### ISSUE TITLE
Test failure: Loader\classloader\SequentialLayout\ManagedSequential\ManagedSequential\ManagedSequential.cmd

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#70295] opened 2022-06-06 18:57 UTC
GCStress=0xc, win-x64/linux-x64

https://dev.azure.com/dnceng/public/_build/results?buildId=1807767&view=ms.vss-test-web.build-test-results-tab&runId=48108696&resultId=104761&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

```
C:\h\w\A2BA08F2\w\ADAE09AA\e>type C:\h\w\A2BA08F2\w\ADAE09AA\u\SetStressModes_gcstress0xc.cmd 
set COMPlus_TieredCompilation=0
set COMPlus_GCStress=0xC

C:\h\w\A2BA08F2\w\ADAE09AA\e>set PATH=C:\h\w\A2BA08F2\p\dotnet-cli;C:\python3\Scripts\;C:\python3\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Users\runner\AppData\Local\Microsoft\WindowsApps 

C:\h\w\A2BA08F2\w\ADAE09AA\e>set DOTNET_ROOT=C:\h\w\A2BA08F2\p\dotnet-cli 

C:\h\w\A2BA08F2\w\ADAE09AA\e>set DOTNET_CLI_TELEMETRY_OPTOUT=1 

C:\h\w\A2BA08F2\w\ADAE09AA\e>set DOTNET_CLI_HOME=C:\h\w\A2BA08F2\w\ADAE09AA\e\.dotnet 

C:\h\w\A2BA08F2\w\ADAE09AA\e>set NUGET_PACKAGES=C:\h\w\A2BA08F2\w\ADAE09AA\e\.nuget 

C:\h\w\A2BA08F2\w\ADAE09AA\e>dotnet C:\h\w\A2BA08F2\p\xunit\xunit.console.dll Loader\classloader\Loader.classloader.XUnitWrapper.dll -parallel collections -nocolor -noshadow -xml testResults.xml -trait TestGroup=Loader.classloader 
Microsoft.DotNet.XUnitConsoleRunner v2.5.0 (64-bit .NET 7.0.0-preview.3.22175.4)
  Discovering: Loader.classloader.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  Loader.classloader.XUnitWrapper (found 320 of 529 test cases)
  Starting:    Loader.classloader.XUnitWrapper (parallel test collections = on, max threads = 4)
    Loader\classloader\SequentialLayout\ManagedSequential\ManagedSequential\ManagedSequential.cmd [FAIL]
      
      Return code:      1
      Raw output file:      C:\h\w\A2BA08F2\w\ADAE09AA\uploads\Reports\Loader.classloader\SequentialLayout\ManagedSequential\ManagedSequential\ManagedSequential.output.txt
      Raw output:
      BEGIN EXECUTION
       "C:\h\w\A2BA08F2\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  ManagedSequential.dll 
      Xunit.Sdk.EqualException: Assert.Equal() Failure
      Expected: 8
      Actual:   752
         at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 96
         at Program.<Main>$(String[] args)
      Expected: 100
      Actual: 101
      END EXECUTION - FAILED
      FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=C:\h\w\A2BA08F2\p
      > C:\h\w\A2BA08F2\w\ADAE09AA\e\Loader\classloader\SequentialLayout\ManagedSequential\ManagedSequential\ManagedSequential.cmd
      Expected: True
      Actual:   False
      Stack Trace:
           at Loader_classloader._SequentialLayout_ManagedSequential_ManagedSequential_ManagedSequential_._SequentialLayout_ManagedSequential_ManagedSequential_ManagedSequential_cmd()
      Output:
        
        Return code:      1
        Raw output file:      C:\h\w\A2BA08F2\w\ADAE09AA\uploads\Reports\Loader.classloader\SequentialLayout\ManagedSequential\ManagedSequential\ManagedSequential.output.txt
        Raw output:
        BEGIN EXECUTION
         "C:\h\w\A2BA08F2\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  ManagedSequential.dll 
        Xunit.Sdk.EqualException: Assert.Equal() Failure
        Expected: 8
        Actual:   752
           at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 96
           at Program.<Main>$(String[] args)
        Expected: 100
        Actual: 101
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=C:\h\w\A2BA08F2\p
        > C:\h\w\A2BA08F2\w\ADAE09AA\e\Loader\classloader\SequentialLayout\ManagedSequential\ManagedSequential\ManagedSequential.cmd
  Finished:    Loader.classloader.XUnitWrapper
=== TEST EXECUTION SUMMARY ===
   Loader.classloader.XUnitWrapper  Total: 320, Errors: 0, Failed: 1, Skipped: 0, Time: 157.111s
```

**Comment by jakobbotsch** [comment] 2022-07-22 08:29
#71987 was a duplicate of this it looks like, and this has already been fixed by #72003

**Closed by jakobbotsch** 2022-07-22 08:29 UTC
Labels: GCStress, arch-x64, area-AssemblyLoader-coreclr, blocking-clean-ci-optional
