### ISSUE TITLE
System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

### ISSUE THREAD

**Issue by sssdsgg** [dotnet/runtime#91052] opened 2023-08-24 10:30 UTC
Our production code runs .net 6.0 deployed in azure function and is getting a TON of these errors:

```
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (prod-39.westus.logic.azure.com:443)
---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at Datadog.Trace.ClrProfiler.CallTarget.Handlers.Continuations.TaskContinuationGenerator`4.ContinuationAction(Task`1 previousTask, TTarget target, CallTargetState state) in c:\mnt\tracer\src\Datadog.Trace\ClrProfiler\CallTarget\Handlers\Continuations\TaskContinuationGenerator`1.cs:line 105
at Datadog.Trace.ClrProfiler.CallTarget.Handlers.Continuations.TaskContinuationGenerator`4.ContinuationAction(Task`1 previousTask, TTarget target, CallTargetState state) in c:\mnt\tracer\src\Datadog.Trace\ClrProfiler\CallTarget\Handlers\Continuations\TaskContinuationGenerator`1.cs:line 105
at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0
```

**Comment by karelz** [comment] 2023-08-24 13:12
It looks like your server is inaccessible, or your local environment has trouble to access it. You will need to investigate the environments (server or client), which may be challenging in Azure Functions area - you might need to reach their support.

**Comment by wfurt** [comment] 2023-08-24 17:10
You should get packet captures @sssdsgg if you can. This bailly means that the process is failing to establish TCP connection. That can be caused by network, firewalls severs or whatever. If this is outbound connection depending on the subscription you may be running to port exhaustion problem: https://learn.microsoft.com/en-us/azure/load-balancer/load-balancer-outbound-connections

as @karelz suggested I think you should look at your stats and and talk to Azure support. I don't think there is problem with .NET sockets or HTTP.

**Comment by karelz** [comment] 2023-08-29 09:05
Closing per discussion above.

**Closed by karelz** 2023-08-29 09:05 UTC
Labels: area-System.Net.Http, untriaged, needs-author-action
