### ISSUE TITLE
Flaky test: Breadcrumb_thread_does_not_finish_when_app_has_unhandled_exception can fail due to output interleaving

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#60980] opened 2021-10-28 17:58 UTC
Issue identified here: https://github.com/dotnet/runtime/pull/60954#issuecomment-954009612

CC @lewing @vitek-karas 

This test can fail if the breadcrumb thread writes it's output in the middle of the runtime writing the unhandled exception.

The test should be fixed to have separate assertions.

**Comment by vitek-karas** [comment] 2021-10-29 18:48
Dupe of https://github.com/dotnet/runtime/issues/57243.

**Closed by vitek-karas** 2021-10-29 18:48 UTC
Labels: area-Host, untriaged
