### ISSUE TITLE
`Directory.EnumerateFileSystemEntries` returns nonexistent paths on malformed input path

### ISSUE THREAD

**Issue by AtomCrafty** [dotnet/runtime#88504] opened 2023-07-07 00:55 UTC
### Description

`Directory.EnumerateFileSystemEntries` and related methods behave very strangely when provided malformed search paths and will return paths that do not exist. I identified the following three scenarios, but there might be more.

Fixing this strange behavior would likely qualify as a breaking change, but I seriously hope there is no code out there relying on this...

For context: The test project is located on my D drive, which will become relevant shortly.

#### 1. Space at the end of the search path
Enumerating `C:\path\ ` with a trailing space will list the contents of `C:\path`, but prefix all returned paths with `C:\path\ \`, making them invalid. ~I assume this is done because it is expected that all return values have the input path as a prefix, but returning nonexistent paths is hardly a good solution.~ *More likely that is simply the result of `Path.Combine(@"D:\ ", ...)`.* In this case it would probably be best to throw a `DirectoryNotFoundException` because there is no directory called ` ` under `C:\path`. Enumerating `C:\path\ \` with a trailing directory separator correctly throws.
This scenario has already been described in #37212.

#### 2. Drive letter without trailing directory separator
Enumerating `D:` does not list the contents of the D drive, but instead all files in the current working directory, but pretends they are located directly under `D:\`. These paths are obviously incorrect. Worst of all, this issue only occurs if the current working directory is located on the same drive whose root directory is being queried. If I call `Directory.SetCurrentDirectory(@"C:\")` first, the contents of `D:\` are listed, as expected.

#### 3. Drive letter without trailing directory separator and trailing space
This is sort of a combination of the above two. Enumerating `D: ` also lists the contents of the current working directory - provided it is located on the D drive - but will now prefix all paths with `D: \`, which in itself can never be part of a valid path.
This should again throw a `DirectoryNotFoundException`, or maybe a `NotSupportedException` as it does for other invalid paths like `D::`.

This combination results in particularly egregious results when combined with `Path.GetFullPath`, because that will happily expand the invalid path `D: \FileApiTest.exe` with the current working directory, resulting in nonsense like `D:\Code\Tests\FileApiTest\FileApiTest\bin\Debug\net7.0\ \FileApiTest.exe`.

### Reproduction Steps

The following program will demonstrate all three issues when run on the D drive.
```cs
namespace FileApiTest;

internal class Program {
	static void Main(string[] args) {
		//Directory.SetCurrentDirectory(@"C:\");
	
		ListEntries(@"D:\ ");
		ListEntries(@"D:");
		ListEntries(@"D: ");
	}

	static void ListEntries(string path) {
		Console.WriteLine($"Directory.EnumerateFileSystemEntries(@\"{path}\")");

		foreach(string entry in Directory.EnumerateFileSystemEntries(path)) {
			bool exists = Directory.Exists(entry) || File.Exists(entry);
			Console.WriteLine($"  {entry,-50} [{(exists ? "exists" : "does not exist")}]");
		}

		Console.WriteLine();
	}
}
```

### Expected behavior

I believe the behavior of the `dir` command would be a reasonable reference for how the API should behave on Windows.

`dir "D:\ "` shows "File not found" → throw an exception
`dir "D:"` lists the contents of `D:\` → enumerate `D:\`
`dir "D: "` shows "File not found" → throw an exception

### Actual behavior

```
Directory.EnumerateFileSystemEntries(@"D:\ ")
  D:\ \$RECYCLE.BIN                                  [does not exist]
  D:\ \Code                                          [does not exist]
  D:\ \Games                                         [does not exist]
  D:\ \System Volume Information                     [does not exist]

Directory.EnumerateFileSystemEntries(@"D:")
  D:\FileApiTest.deps.json                           [does not exist]
  D:\FileApiTest.dll                                 [does not exist]
  D:\FileApiTest.exe                                 [does not exist]
  D:\FileApiTest.pdb                                 [does not exist]
  D:\FileApiTest.runtimeconfig.json                  [does not exist]

Directory.EnumerateFileSystemEntries(@"D: ")
  D: \FileApiTest.deps.json                          [does not exist]
  D: \FileApiTest.dll                                [does not exist]
  D: \FileApiTest.exe                                [does not exist]
  D: \FileApiTest.pdb                                [does not exist]
  D: \FileApiTest.runtimeconfig.json                 [does not exist]
```

### Known Workarounds

Sanitizing the input path by trimming trailing spaces and adding a directory separator if not present will avoid all of the above issues.

### Configuration

Tested on .NET 6.0 and .NET 7.0
Windows 11 Home 22H2, 64 bit
Probably not specific to this particular Windows version

**Comment by danmoseley** [comment] 2023-07-07 01:22
Cc @JeremyKuhne for opinion

**Comment by AtomCrafty** [comment] 2023-07-07 03:40
https://learn.microsoft.com/en-us/archive/blogs/jeremykuhne/path-normalization
This blog post provided some interesting insights into *why* the directories are enumerated the way they are, but the `Directory.*` methods still shouldn't return invalid or nonexistent paths.

**Comment by skyoxZ** [comment] 2023-07-07 09:43
duplicate #68503

**Comment by Jozkee** [comment] 2023-07-24 20:33
Thanks for filing the issue and sharing your scenarios, however I'm going to close it as duplicate of https://github.com/dotnet/runtime/issues/68503, https://github.com/dotnet/runtime/issues/37212.
___
> dir "D:" lists the contents of D:\ → enumerate D:\

I don't think that's right, when I do `dir C:` I do get enumerated the contents of the current working directory.

**Closed by Jozkee** 2023-07-24 20:33 UTC
Labels: area-System.IO, untriaged

**Comment by AtomCrafty** [comment] 2023-07-24 20:37
> I don't think that's right, when I do `dir C:` I do get enumerated the contents of the current working directory.

Yeah, you get the cwd contents when you specify the drive you are currently on, otherwise the root of the drive specified.
Sorry for the duplicate, I didn't find the other issues during my preliminary search. I'll monitor progress there 👍
