### ISSUE TITLE
coreclr build fails when specifying cmakeargs -DCLR_CMAKE_USE_SYSTEM_LIBUNWIND=TRUE

### ISSUE THREAD

**Issue by dseefeld** [dotnet/runtime#2014] opened 2020-01-22 16:49 UTC
When trying to build coreclr using the system version of libunwind, the build fails with the following error:

```console
$ ./build.sh cmakeargs -DCLR_CMAKE_USE_SYSTEM_LIBUNWIND=TRUE
...
../../dlls/mscordac/libmscordaccore.so: undefined reference to `_OOP_find_proc_info'
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [src/debug/createdump/createdump] Error 1
gmake[1]: *** [src/debug/createdump/CMakeFiles/createdump.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[100%] Built target mscordbi
gmake: *** [all] Error 2
Failed to build CoreCLR component.
```

**Comment by hoyosjs** [comment] 2020-01-22 21:21
What system/OS is this?

**Comment by hoyosjs** [comment] 2020-01-22 21:57
@mikem8361 looks like this comes from our work in ARM unwinding (b61cc2fa). Looks like `_OOP_find_proc_info` was added directly to libunwind. However this function only gets build then: https://github.com/dotnet/runtime/blob/696e72b14d29979d7dab11eb4384ae656fdfaba6/src/coreclr/src/pal/src/CMakeLists.txt#L16 The easiest solution would be to hoist such logic into another statically linkable asset, but if memory serves he right we use types that are not available in the public libunwind surface area.

@dseefeld is this for sourcebuild? What's the impact if so? Or is this more around serviceability or the ability to build like that?

**Comment by dseefeld** [comment] 2020-01-22 22:27
@hoyosjs Yes.  This is for sourcebuild.  The impact is that RedHat has requested that we use the local system's libunwind for portable builds.  See https://github.com/dotnet/source-build/pull/391  The OS that I'm using to build this is CentOS.

**Comment by sdmaclea** [comment] 2020-06-18 20:32
https://github.com/libunwind/libunwind/pull/187 is starting the process of adding `_OOP_find_proc_info` to libunwind, but it is unlikely to make it into system version of libunwind for a while.  It would need to wait at least to the 1.6 release. (1.5 isn't released yet).

Since this is only needed for the DAC unwind, the solution maybe to either:
+ Disable the the DAC Out of Process unwind feature.
+ Use the local libunwind source for DAC only.

**Comment by mikem8361** [comment] 2020-06-18 23:46
>> •       Disable the the DAC Out of Process unwind feature.
This breaks a lot of stack traces that have HelpMethodFrames (fairly common), but it is limited to dotnet-dump/CLRMD on coredumps. Live managed debugging and live SOS debugging under lldb will work fine.

>> •       Use the local libunwind source for DAC only.
This still breaks the source build because the DAC is still built along with the rest of the runtime. But maybe our source build customers would like it slide (RHEL).

**Comment by sdmaclea** [comment] 2020-06-19 01:18
I guess the third option would be to revert part of #26082 when `CLR_CMAKE_USE_SYSTEM_LIBUNWIND=TRUE` until https://github.com/libunwind/libunwind/pull/187 is released and available to RHEL.

**Comment by omajid** [comment] 2020-06-24 19:46
cc @tmds

**Comment by mikem8361** [comment] 2020-06-29 21:22
Adding @jashook

**Comment by tmds** [comment] 2020-06-30 14:04
> I guess the third option would be to revert part of #26082 (to keep our custom oop code) when CLR_CMAKE_USE_SYSTEM_LIBUNWIND=TRUE until libunwind/libunwind#187 is released and available to RHEL.

So this option is: allow to use the system libunwind, and provide `_OOP_find_proc_info` as part of the runtime repo?

This seems like the most interesting option to me.

**Comment by mikem8361** [comment] 2020-06-30 20:32
The problem is the functions that _OOP_find_proc_info uses are internal to libunwind.

**Comment by tmds** [comment] 2020-07-01 11:26
Until @sdmaclea 's libunwind PR gets merged and becomes available, the least work is to use the packed libunwind.
We can look at backporting the PR for distros we care about.

We should keep this issue open to get `CLR_CMAKE_USE_SYSTEM_LIBUNWIND=true` back in a working state.

@omajid wdyt?

**Comment by tmds** [comment] 2020-07-15 08:05
@sdmaclea are you still actively pursuing https://github.com/libunwind/libunwind/pull/187?

@omajid are you ok with using the packed libunwind until the feature is available as part of system libunwind?
We can consider backporting it once the feature is merged upstream.

**Comment by sdmaclea** [comment] 2020-07-15 16:23
I have been working on other issues.  I can probably look at https://github.com/libunwind/libunwind/pull/187 later this week.

**Comment by sdmaclea** [comment] 2020-07-15 16:26
#39213 restored some of the code which was removed in #26082.  It makes it simpler to fix this issue more directly.  @mikem8361 has been considering an approach like this...

**Comment by mikem8361** [comment] 2020-07-15 19:58
I have this coded up and I'm testing.

**Comment by omajid** [comment] 2020-07-15 20:51
> @omajid are you ok with using the packed libunwind until the feature is available as part of system libunwind? We can consider backporting it once the feature is merged upstream.

Yes, we can use the bundled libunwind until the features are available upstream.

**Closed** 2020-07-16 06:09 UTC
Labels: area-Diagnostics-coreclr, p1
