### ISSUE TITLE
VB late binder should disallow writing to init-only property

### ISSUE THREAD

**Issue by jcouv** [dotnet/runtime#47499] opened 2021-01-26 23:37 UTC
In VB 16.9 (roslyn version 3.9), we're allowing VB code to invoke init setters in certain contexts.
It would probably be good for the VB late-binder to disallow settings such properties, as we did for dynamic binder in PR https://github.com/dotnet/runtime/pull/41293.

FYI @AlekseyTs @cston

**Comment by cston** [comment] 2021-03-05 17:10
Duplicate of https://github.com/dotnet/runtime/issues/45039.

**Closed by cston** 2021-03-05 17:10 UTC
Labels: area-Microsoft.VisualBasic, untriaged
