### ISSUE TITLE
LDAP: System.DirectoryServices.Protocols SearchRequest don't work on linux (5.0.0-rc.2.20475.5)

### ISSUE THREAD

**Issue by wli3** [dotnet/runtime#44566] opened 2020-11-12 01:02 UTC
@mduperche commented on [Tue Nov 03 2020](https://github.com/dotnet/sdk/issues/14414)

On linux I Received this message but on Windows it Work.
**Error message**
```
An operation error occurred.System.DirectoryServices.Protocols.DirectoryOperationException: An operation error occurred.

at System.DirectoryServices.Protocols.LdapConnection.ConstructResponseAsync(Int32 messageId, LdapOperation operation, ResultAll resultType, TimeSpan requestTimeOut, Boolean exceptionOnTimeOut, Boolean sync)

at System.DirectoryServices.Protocols.LdapConnection.SendRequest(DirectoryRequest request, TimeSpan requestTimeout)
...
```
**Wired Shark response**
```
Lightweight Directory Access Protocol
    LDAPMessage searchResDone(3) operationsError (000004DC: LdapErr: DSID-0C090A22, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v3839) [0 results]
        messageID: 3
        protocolOp: searchResDone (5)
            searchResDone
                resultCode: operationsError (1)
                matchedDN: 
                errorMessage: 000004DC: LdapErr: DSID-0C090A22, comment: In order to perform this operation a successful bind must be completed on the connection
```
**Code**
```
var username = "username@company.com";
var id = new LdapDirectoryIdentifier(Parameters.Domain, 389);
            using (var connection = new LdapConnection(id, new NetworkCredential("serviceAccount", "servicePassword"), AuthType.Basic))
{
    connection.Bind();
    var query = new SearchRequest("DC=pub,DC=company,DC=com", $"(&(objectClass=user)(userPrincipalName={username}))", SearchScope.Subtree);
    var response = (SearchResponse)connection.SendRequest(query);
}
```
**System info**
- Linux
- docker: mcr.microsoft.com/dotnet/core/aspnet:2.1-stretch-slim
- dotnet core 2.1 
- Nuget: System.DirectoryServices.Protocols version 5.0.0-rc.2.20475.5

**Comment by stcpottdav** [comment] 2021-01-07 16:50
I am also receiving this error with the 5.0.0 version of the package.  Bind works on linux but not search.  Both work on windows.  
Novell.Directory.Ldap.NETStandard does work for both bind and search.

**Comment by joperezr** [comment] 2021-02-09 23:09
Hello @wli3 thanks for logging this issue. By looking at the wireshark response, it seems like the problem is that the Bind operation didn't finish succesfully. Can you try setting the protocol verison to 3.0 before sending the searchRequest?

```c#
            connection.Bind();
            connection.SessionOptions.ProtocolVersion = 3;
```

**Comment by stcpottdav** [comment] 2021-02-10 17:01
It seems that it does not support searching a the domain level as per this ticket:
https://github.com/dotnet/runtime/issues/44826

Once I changed my SearchBase to something lower it worked for me.

Basically changing:
"DC=pub,DC=company,DC=com"
to
"OU=UsersOU,DC=pub,DC=company,DC=com"

**Comment by joperezr** [comment] 2021-02-10 19:14
I see, thanks for confirming. I'll close this issue then as a dupe so we can focus on that one instead. Feel free to log other issues or reopen if you hit any additional problems.

**Closed** 2021-02-10 19:14 UTC
Labels: area-System.DirectoryServices, untriaged
