### ISSUE TITLE
JsonPolymorphic Deserialization Fails When TypeDiscriminatorPropertyName Not First Property

### ISSUE THREAD

**Issue by troysteinbauer** [dotnet/runtime#78447] opened 2022-11-16 05:40 UTC
### Description

I am attempting to deserialize external json from a service which is structured in a way that I can take advantage of `JsonPolymorphic` attribute, however it appears that it needs the type discriminator as the first property in the json object. I don't have control over this external source of json to adjust it, and many libraries treat json objects as an unordered collection.

Is there a work around? I assume this is for performance to only look ahead for the first property, but I believe it is common to not have control over the ordering of the json. I couldn't find any documentation about this limitation either.

### Reproduction Steps

```c#
using System.Text.Json;
using System.Text.Json.Serialization;

public class PolymorphicJsonExample
{
    private static readonly JsonSerializerOptions JsonSerializerOptions = new JsonSerializerOptions(JsonSerializerOptions.Default);
    [JsonPolymorphic(TypeDiscriminatorPropertyName = "Type")]
    [JsonDerivedType(typeof(TypeA), "a")]
    [JsonDerivedType(typeof(TypeB), "b")]
    private abstract record Base(string Type);
    private sealed record TypeA(string Type, int ValueA) : Base(Type);
    private sealed record TypeB(string Type, bool ValueB) : Base(Type);

    [Test]
    public void FromJsonA()
    {
        const string jsonA = """{"Type":"a","ValueA":1}""";
        var valueA = JsonSerializer.Deserialize<Base>(jsonA, JsonSerializerOptions);
        Assert.That(valueA, Is.TypeOf<TypeA>());
    }

    [Test]
    public void FromJsonA_Revered()
    {
        const string jsonA = """{"ValueA":1,"Type":"a"}""";
        var valueA = JsonSerializer.Deserialize<Base>(jsonA, JsonSerializerOptions);
        Assert.That(valueA, Is.TypeOf<TypeA>());
    }
}
```

### Expected behavior

No exceptions thrown during test `PolymorphicJsonExample.FromJsonA_Reverse()` and it successfully passes.

### Actual behavior

Exception thrown:
```
  Failed FromJsonA_Revered [< 1 ms]
  Error Message:
   System.NotSupportedException : Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'Tape.Net.Tests.PolymorphicJsonExampleUpper+Base'. Path: $ | LineNumber: 0 | BytePositionInLine: 10.
  ----> System.NotSupportedException : Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'Tape.Net.Tests.PolymorphicJsonExampleUpper+Base'.
  Stack Trace:
     at System.Text.Json.ThrowHelper.ThrowNotSupportedException(ReadStack& state, Utf8JsonReader& reader, NotSupportedException ex)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Tape.Net.Tests.PolymorphicJsonExampleUpper.FromJsonA_Revered() in PolymorphicJsonExampleUpper.cs:line 29
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
--NotSupportedException
```

### Configuration

- dotnet 7.0.100
- System.Text.Json 7.0.0

**Comment by Symbai** [comment] 2022-11-16 05:58
Dupe of #73693 and #72604

**Comment by eiriktsarpalis** [comment] 2022-11-16 11:10
Duplicate of #72604.

**Closed by eiriktsarpalis** 2022-11-16 11:10 UTC
Labels: area-System.Text.Json, untriaged
