### ISSUE TITLE
When publish settings are set to produce single file in .Net 5, ConfigurationManager will not be able to save

### ISSUE THREAD

**Issue by tgckpg** [dotnet/runtime#44955] opened 2020-11-14 04:30 UTC
# Application will attempt to save an invalid file name with `<Unknown>.config`

```
System.Configuration.ConfigurationErrorsException
  HResult=0x80131902
  Message=Unable to save config to file 'D:\penguin\Documents\Visual Studio 2019\Projects\ScreenMask\ScreenMask\bin\Publish\<Unknown>.config'.
  Source=System.Configuration.ConfigurationManager
  StackTrace:
   at System.Configuration.Internal.WriteFileContext.ReplaceFile(String source, String target)
   at System.Configuration.Internal.WriteFileContext.Complete(String filename, Boolean success)
   at System.Configuration.Internal.InternalConfigHost.System.Configuration.Internal.IInternalConfigHost.WriteCompleted(String streamName, Boolean success, Object writeContext)
   at System.Configuration.Internal.DelegatingConfigHost.WriteCompleted(String streamName, Boolean success, Object writeContext)
   at System.Configuration.UpdateConfigHost.WriteCompleted(String streamName, Boolean success, Object writeContext)
   at System.Configuration.Internal.DelegatingConfigHost.WriteCompleted(String streamName, Boolean success, Object writeContext)
   at System.Configuration.MgmtConfigurationRecord.SaveAs(String filename, ConfigurationSaveMode saveMode, Boolean forceUpdateAll)
   at System.Configuration.Configuration.SaveAsImpl(String filename, ConfigurationSaveMode saveMode, Boolean forceSaveAll)
   at System.Configuration.Configuration.Save(ConfigurationSaveMode saveMode)
   at ScreenMask.Config.AppConfig.Save()
   at ScreenMask.ModeMask.SaveSettings()
   at ScreenMask.ModeMask.Grid_MouseUp(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at ScreenMask.App.Main()
```

# General
This is using `ConfigurationManager.OpenExeConfiguration( ConfigurationUserLevel.None )`

**Comment by safern** [comment] 2020-11-19 18:59
Hello, @tgckpg this issue is a dupe of: https://github.com/dotnet/runtime/issues/42161. 

This was fixed on: https://github.com/dotnet/runtime/pull/42176, however the fix didn't make it early enough to make it into .NET 5.0. 

Does this workaround works for you? https://github.com/dotnet/runtime/pull/42176#issuecomment-699022219

cc: @danmosemsft @agocke @ericstj

**Comment by safern** [comment] 2020-11-19 19:01
Closing as in the discussion it was decided that there was risk on the fix and we're trying to improve our test coverage for single file at the moment to which we don't have.

**Closed by safern** 2020-11-19 19:01 UTC
Labels: area-System.Configuration, untriaged

**Comment by tgckpg** [comment] 2020-11-21 08:41
Sorry but no, guess I'll stick with non-single file for now.

Reading through the posts, I conclude that it does not work for me:
1. I'm making a desktop app, so I need a quick and simple way to store the configs. So `Microsoft.Extensions.Configuration` is too much hassle - not suitable.
1. The provided workaround lack of `ConfigurationSaveMode.Minimal`, implementing it myself violates (1)
