### ISSUE TITLE
[API Proposal]: ArgumentException.ThrowIfNullOrWhiteSpace(string) 

### ISSUE THREAD

**Issue by Marusyk** [dotnet/runtime#80986] opened 2023-01-22 00:14 UTC
### Background and motivation

Inspired by `ArgumentNullException.ThrowIfNull(object)` and `ArgumentException.ThrowIfNullOrEmpty` from #62628.
`string.IsNullOrWhiteSpace(text)` is a frequent check, especially in Web/Console projects. 

Now:
```
if (string.IsNullOrWhiteSpace(input))
{ 
     throw new ArgumentException($"{nameof(input)} must contain value.");
}
```

### API Proposal

```csharp
namespace System
{
    public class ArgumentException : SystemException
    {
        public static void ThrowIfNullOrWhiteSpace([NotNull] string? argument, [CallerArgumentExpression("argument")] string? paramName = null)
    }
}
```

### API Usage

```csharp
string input = " ";
ArgumentException.ThrowIfNullOrWhiteSpace(input);
```

### Alternative Designs

Define it as an extension method
```csharp

public static void ThrowIfNullOrWhiteSpace(this [NotNull] string? argument, [CallerArgumentExpression("argument")] string? paramName = null)
```

**Comment by stephentoub** [comment] 2023-01-22 01:39
Duplicate of https://github.com/dotnet/runtime/issues/77749

**Closed by stephentoub** 2023-01-22 01:39 UTC
Labels: api-suggestion, untriaged
