### ISSUE TITLE
"The remote certificate is invalid because of errors in the certificate chain: RevocationStatusUnknown" in XHarness tasks

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#68298] opened 2022-04-20 20:04 UTC
This takes out one or more legs in CI very frequently recently.
```
.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22179.1/tools/xharness-runner/XHarnessRunner.targets#L122
.packages/microsoft.dotnet.helix.sdk/7.0.0-beta.22179.1/tools/xharness-runner/XHarnessRunner.targets(122,5): error MSB4018: The "CreateXHarnessAppleWorkItems" task failed unexpectedly.
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: RevocationStatusUnknown
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.DotNet.Helix.Sdk.ProvisioningProfileProvider.<>c__DisplayClass14_0.<<DownloadProvisioningProfile>b__0>d.MoveNext() in /_/src/Microsoft.DotNet.Helix/Sdk/ProvisioningProfileProvider.cs:line 190
--- End of stack trace from previous location ---
   at Microsoft.Arcade.Common.Helpers.<>c__DisplayClass7_0.<DirectoryMutexExec>b__0() in /_/src/Common/Microsoft.Arcade.Common/Helpers.cs:line 71
   at Microsoft.Arcade.Common.Helpers.MutexExec[T](Func`1 function, String mutexName) in /_/src/Common/Microsoft.Arcade.Common/Helpers.cs:line 45
   at Microsoft.Arcade.Common.Helpers.DirectoryMutexExec[T](Func`1 function, String path) in /_/src/Common/Microsoft.Arcade.Common/Helpers.cs:line 64
   at Microsoft.Arcade.Common.Helpers.DirectoryMutexExec(Func`1 function, String path) in /_/src/Common/Microsoft.Arcade.Common/Helpers.cs:line 71
   at Microsoft.DotNet.Helix.Sdk.ProvisioningProfileProvider.DownloadProvisioningProfile(ApplePlatform platform) in /_/src/Microsoft.DotNet.Helix/Sdk/ProvisioningProfileProvider.cs:line 179
   at Microsoft.DotNet.Helix.Sdk.ProvisioningProfileProvider.AddProfileToPayload(String archivePath, String testTarget) in /_/src/Microsoft.DotNet.Helix/Sdk/ProvisioningProfileProvider.cs:line 99
   at Microsoft.DotNet.Helix.Sdk.CreateXHarnessAppleWorkItems.PrepareWorkItem(IZipArchiveManager zipArchiveManager, IFileSystem fileSystem, IProvisioningProfileProvider provisioningProfileProvider, ITaskItem appBundleItem) in /_/src/Microsoft.DotNet.Helix/Sdk/CreateXHarnessAppleWorkItems.cs:line 189
   at Microsoft.DotNet.Helix.Sdk.CreateXHarnessAppleWorkItems.ExecuteTask(IProvisioningProfileProvider provisioningProfileProvider, IZipArchiveManager zipArchiveManager, IFileSystem fileSystem) in /_/src/Microsoft.DotNet.Helix/Sdk/CreateXHarnessAppleWorkItems.cs:
```

**Comment by ViktorHofer** [comment] 2022-04-20 20:13
cc @premun @akoeplinger

**Comment by steveisok** [comment] 2022-04-20 20:37
Duplicate of https://github.com/dotnet/runtime/issues/67349.  Closing in favor of that issue.

This should be fixed (or fail less) if either https://github.com/dotnet/runtime/pull/68024 or https://github.com/dotnet/runtime/pull/67771 lands.

**Closed by steveisok** 2022-04-20 20:37 UTC
Labels: blocking-clean-ci, area-Infrastructure, untriaged
