### ISSUE TITLE
Test failure: System.Diagnostics.Tests.ProviderMetadataTests.GetProviderNames_AssertProperties

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#45350] opened 2020-11-30 09:08 UTC
failed in job: https://dev.azure.com/dnceng/public/_build/results?buildId=902001&view=ms.vss-test-web.build-test-results-tab&runId=28806080&resultId=104557&paneView=debug

net6.0-windows-Release-x86-CoreCLR_checked-jitstress2_jitstressregs3-Windows.10.Amd64.Open

Error message
~~~
System.NullReferenceException : Object reference not set to an instance of an object.

Stack trace
   at System.Collections.Generic.ObjectEqualityComparer`1.IndexOf(T[] array, T value, Int32 startIndex, Int32 count) in /_/src/coreclr/src/System.Private.CoreLib/src/System/Collections/Generic/EqualityComparer.CoreCLR.cs:line 119
   at System.Array.IndexOf[T](T[] array, T value, Int32 startIndex, Int32 count) in /_/src/libraries/System.Private.CoreLib/src/System/Array.cs:line 1133
   at System.SZArrayHelper.Contains[T](T value) in /_/src/coreclr/src/System.Private.CoreLib/src/System/Array.CoreCLR.cs:line 580
   at System.Diagnostics.Tests.ProviderMetadataTests.GetProviderNames_AssertProperties() in /_/src/libraries/System.Diagnostics.EventLog/tests/System/Diagnostics/Reader/ProviderMetadataTests.cs:line 88
~~~

**Comment by GrabYourPitchforks** [comment] 2020-11-30 09:18
Likely dupe of https://github.com/dotnet/runtime/issues/45317, fixed by https://github.com/dotnet/runtime/pull/45320

**Closed by GrabYourPitchforks** 2020-11-30 09:18 UTC
Labels: area-System.Diagnostics, untriaged
