### ISSUE TITLE
Weird Array.Sort() behavior

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#54472] opened 2021-06-21 06:53 UTC
See different results on Windows and Linux if I use Array.Sort(array):
Windows:
```
Priority
process
ProcessModule
ProcessWithUserName
'R A M'
StartTime
```
Linux:
```
'R A M'
Priority
process
ProcessModule
ProcessWithUserName
StartTime
```

Is the behavior expected? Since ICU is used I'd expect the same result on all platforms.
If it is by design how I can get the same result on all platforms?

/cc @tarekgh 

PS: This leads to differences in PowerShell _tab-completion_ behavior.

**Comment by tarekgh** [comment] 2021-06-21 15:41
@iSazonov `Array.Sort(Array)` uses `Comparer.Default` which depends on `CultureInfo.CurrentCulture`. That means, if you have different default culture on Windows and Linux, can get different sort behavior. Please confirm what is the current culture used on Windows and Linux which seeing this behavior. Also, need to confirm ICU is used in both cases. I mean the NLS nor Globalization invariant modes are not enabled. 

If you want to control the behavior, you can use [Array.Sort](https://docs.microsoft.com/en-us/dotnet/api/system.array.sort?view=net-5.0#System_Array_Sort_System_Array_System_Array_System_Collections_IComparer_) overload which takes IComparer object.

**Comment by iSazonov** [comment] 2021-06-21 18:03
I caught the issue in PowerShell repo CIs and currently see the same on WSL. I set en_US.UTF-8 on WSL (Ubuntu 20.04 - default locale is C.UTF-8) and still see `'R A M'` on first place. There is latest PowerShell 7.2 preview on .Net 6.0 Preview4 without switching from ICU to NLS. 
I tried switch to NLS and use explicit comparer and see the same result.

**Comment by tarekgh** [comment] 2021-06-21 19:44
> still see 'R A M' on first place.

This is the correct behavior.

I cannot reproduce this issue. When running on Windows I am getting consistent result as what I get on Linux.

```
Microsoft Windows 10.0.21390
.NET 6.0.0-preview.5.21253.3
CurrentCulture: en-US

'R A M'
Priority
process
ProcessModule
ProcessWithUserName
StartTime
```

Looks to me your Windows configuration somehow having something wrong.

**Comment by iSazonov** [comment] 2021-06-22 06:13
> Looks to me your Windows configuration somehow having something wrong.

Thanks for pointing right behavior. 
As I said I saw it in [PowerShell CIs](https://github.com/PowerShell/PowerShell/pull/14513) and I see the same thing on my local machine. I can confirm that in both cases it is en_US.

I don't see in procexp.exe that ICU assembly is loaded. How can I determine the cause?

**Comment by tarekgh** [comment] 2021-06-22 17:50
Could you please try printing the following on the machine you are seeing the problem with? 

```C$
            Console.WriteLine($"{RuntimeInformation.OSDescription}");
            Console.WriteLine($"{RuntimeInformation.FrameworkDescription}");
            try
            {
                Console.WriteLine($".... UseNls: {typeof(object).Assembly.GetType("System.Globalization.GlobalizationMode").GetProperty("UseNls", BindingFlags.Static | BindingFlags.NonPublic).GetValue(null)} ....");
            }
            catch
            {
                Console.WriteLine($".... UseNls: Couldn't Evaluate it ....");
            }

            Console.WriteLine($"{CultureInfo.GetCultureInfo("en-US").NumberFormat.CurrencySymbol}");
```

**Comment by iSazonov** [comment] 2021-06-22 18:11
```
Microsoft Windows 10.0.19041
.NET 6.0.0-preview.4.21253.7
.... UseNls: False .... 
$ 
```

**Comment by iSazonov** [comment] 2021-06-22 18:22
I have added in the code:
```c#
            var a = new string[] { "'R A M'", "Priority", "process", "ProcessModule", "ProcessWithUserName", "StartTime" };
            Array.Sort(a);
            foreach (var s in a) Console.WriteLine(s);
```
and get:
```
'R A M'
Priority
process
ProcessModule
ProcessWithUserName
StartTime
```
So it is seem PowerShell issue.

**Comment by tarekgh** [comment] 2021-06-22 18:23
Everything looks good. Could you please print the following output too?

```C#
            Console.WriteLine($"CurrentCulture: {CultureInfo.CurrentCulture}");
            string [] arrayToSort = new string []
            {
                "Priority",
                "process",
                "ProcessModule",
                "ProcessWithUserName",
                "'R A M'",
                "StartTime",
            };

            Array.Sort(arrayToSort);

            foreach (string s in arrayToSort)
            {
                Console.WriteLine(s);
            }

            foreach (ProcessModule module in Process.GetCurrentProcess().Modules)
            {
                if (module.FileName.IndexOf("icu", StringComparison.OrdinalIgnoreCase) >= 0)
                    Console.WriteLine($"{module.FileName} ... {module.FileVersionInfo}");
            }
```

**Comment by tarekgh** [comment] 2021-06-22 18:26
I cross replying your last response :-) so you may ignore it then as you figured out this is a PS issue :-) I am closing the issue but feel free to reply with any more questions if you have any.

**Closed by tarekgh** 2021-06-22 18:26 UTC
Labels: area-System.Globalization, needs further triage

**Comment by iSazonov** [comment] 2021-06-22 18:36
From PowerShell:
```
[object].GetType().Assembly.GetType("System.Globalization.GlobalizationMode").GetProperty("UseNls", [System.Reflection.BindingFlags]::Static + [System.Reflection.BindingFlags]::NonPublic).GetValue($null)
True
```
I wonder why it returns true. @tarekgh Have you any ideas how I could find a root of the issue? Is it possible configure the option in application after its start? 
Or it is TPA?

**Comment by tarekgh** [comment] 2021-06-22 19:05
Check if the config switch is set in your PS environment https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/globalization-icu#use-nls-instead-of-icu.

**Comment by iSazonov** [comment] 2021-06-22 19:10
No, all three options are absent.

**Comment by tarekgh** [comment] 2021-06-22 21:09
Is there a way to create a [TTT](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/time-travel-debugging-overview) for a small PS script run and share it with me?

**Comment by iSazonov** [comment] 2021-06-23 04:20
Done:
[icu_test.zip](https://github.com/dotnet/runtime/files/6698861/icu_test.zip)

Script:
```powershell
 $expected = "'R A M'", "Priority", "process", "ProcessModule", "ProcessWithUserName", "StartTime"
[Array]::Sort($expected)
$expected
```

**Comment by tarekgh** [comment] 2021-06-23 16:14
Unfortunately, you have captured the pwsh process and not the dotnet process. If it is hard to capture the dotnet process, you may try to execute this code. That should tell exactly how NLS mode is enabled.

```C#
    if (!AppContext.TryGetSwitch("System.Globalization.UseNls", out bool ret))
    {
        string? switchValue = Environment.GetEnvironmentVariable("DOTNET_SYSTEM_GLOBALIZATION_USENLS");
        if (switchValue != null)
        {
            Console.WriteLine($"Environment variable DOTNET_SYSTEM_GLOBALIZATION_USENLS is defined");
            ret = bool.IsTrueStringIgnoreCase(switchValue) || switchValue.Equals("1");
        }
    }
    else
    {
        Console.WriteLine($"Config switch System.Globalization.UseNls is defined");
    }
```

**Comment by iSazonov** [comment] 2021-06-23 18:17
> Unfortunately, you have captured the pwsh process and not the dotnet process. If it is hard to capture the dotnet process, you may try to execute this code.

If I run an simple dotnet app I don't see the issue. The issue exists only on pwsh..

**Comment by tarekgh** [comment] 2021-06-23 18:27
Can you write the same code inside pwsh script and run it?

**Comment by iSazonov** [comment] 2021-06-23 18:41
This returns nothing in script.

**Comment by tarekgh** [comment] 2021-06-23 18:50
and if you add the following code to the same script, it returns the wrong sort order? this is very weird. 

```C#
    string [] arrayToSort = new string []
    {
        "Priority",
        "process",
        "ProcessModule",
        "ProcessWithUserName",
        "'R A M'",
        "StartTime",
    };

    Array.Sort(arrayToSort);

    foreach (string s in arrayToSort)
    {
        Console.WriteLine(s);
    }
```

**Comment by iSazonov** [comment] 2021-06-23 19:22
I inserted the code in PowerShell startup code, compile and stop on breakpoint in the C# code.

On my enterprise computer I see the issue. I run WInternals ProcExp and I don't see that ICU dll is loaded.
On my home computer I don't see the issue and ProcExp shows ICU is loaded.

**Comment by tarekgh** [comment] 2021-06-23 19:28
> enterprise computer

Is this Windows client or server machine?

**Comment by iSazonov** [comment] 2021-06-23 19:29
On my home computer - C:\Windows\System32\icu.dll presents. ( icuin.dll and icuuc.dll present)
Microsoft Windows [Version 10.0.19041.1052]

On my enterprise computer only icuin.dll and icuuc.dll present.
Microsoft Windows [Version 10.0.17763.1999]

**Comment by iSazonov** [comment] 2021-06-23 19:34
I wonder if globally only icu.dll is searched.
https://github.com/dotnet/runtime/blob/3ead4ac16ac127558943dd72555a54ec3bc6ac67/src/libraries/System.Private.CoreLib/src/System/Globalization/GlobalizationMode.Windows.cs#L12-L29

**Comment by tarekgh** [comment] 2021-06-23 19:41
Ok, now that make sense then :-) 

you have RS5 which .NET can't use the icu library from there (because of some COM issues). Either you need to upgrade to higher version, or you force the ICU [app-local](https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/globalization-icu?ranMID=46131&ranEAID=a1LgFw09t88&ranSiteID=a1LgFw09t88-22Ivk4AW13lwjsB0kz.4ew&epi=a1LgFw09t88-22Ivk4AW13lwjsB0kz.4ew&irgwc=1&OCID=AID2000142_aff_7806_1243925&tduid=%28ir__mrdukhopi0kfqxeykk0sohzifv2xuvgehvxvqk3y00%29%287806%29%281243925%29%28a1LgFw09t88-22Ivk4AW13lwjsB0kz.4ew%29%28%29&irclickid=_mrdukhopi0kfqxeykk0sohzifv2xuvgehvxvqk3y00#app-local-icu).


```Xml
<ItemGroup">
  <PackageReference Include="Microsoft.ICU.ICU4C.Runtime" Version="68.2.0.6" />
  <RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="68.2" />
</ItemGroup>
```

**Comment by iSazonov** [comment] 2021-06-23 19:44
@tarekgh Thanks for great help! Will discuss with PowerShell team.

**Comment by iSazonov** [comment] 2021-06-24 02:46
@tarekgh What is OS versions supported by Microsoft.ICU.ICU4C.Runtime? Will this work on Windows 7 and Ubuntu 16.04?

**Comment by tarekgh** [comment] 2021-06-24 15:45
@jefgen could you please help with @iSazonov question?

**Comment by jefgen** [comment] 2021-06-24 19:45
> @jefgen could you please help with @iSazonov question?

> What is OS versions supported by Microsoft.ICU.ICU4C.Runtime? Will this work on Windows 7 and Ubuntu 16.04?

I created a new wiki page here with some more info:
https://github.com/microsoft/icu/wiki/Microsoft.ICU.ICU4C.Runtime-package-supported-OS-versions

The `win-x64` and `win-x86` sub packages should work on Windows 7 and above. But you'll need to have the UCRT installed first on Win 7 and Win8. (It is already present on Win10 and above.)

The `linux-x64` sub package is built using the .NET Core CentOS 7 docker image, and should work for all *glibc* based distros -- so yes it should work on Ubuntu 16.04.
