### ISSUE TITLE
Unexpected change in behavior with DateTime.AddSeconds() between .NET 6 and 7

### ISSUE THREAD

**Issue by wallacepca** [dotnet/runtime#91820] opened 2023-09-08 20:33 UTC
### Description

I recently upgraded our .NET codebase to .NET 7 and I started to notice some issues related to DateTime precision. I may have missed some announcement about this, but since I'm not sure and couldn't find anything, I think it could be a bug.

### Reproduction Steps

The following example does not return the same result in NET 6 e 7

```
using System;
					
public class Program
{
	public static void Main()
	{
	    var baseDatetime = new DateTime(63772324434);

            var dateTime1 = baseDatetime.AddSeconds(1.2);

            var dateTime2 = baseDatetime.Add(TimeSpan.FromSeconds(1.2));

            Console.WriteLine(dateTime1 == dateTime2);
	    Console.WriteLine(dateTime1.Ticks);
	    Console.WriteLine(dateTime2.Ticks);
	}
}
```
NET 6 output:

True
63784324434
63784324434

NET 7 output:
False
63784324433
63784324434

runnable examples

https://dotnetfiddle.net/PSWzro NET6

https://dotnetfiddle.net/Yh4xVI NET7

### Expected behavior

I expected both methods DateTime.AddSeconds(double) and DateTime.Add(timespan) to work the exactly same way.

### Actual behavior

- 

### Regression?

When I run the above sample code with the latest .NET 6 and .NET 7 I see a difference in the behavior that I don't expect.

### Known Workarounds

I'm avoiding using DateTime.AddSeconds() and using DateTime.Add(TimeSpan.FromSeconds()) instead

**Comment by reflectronic** [comment] 2023-09-08 20:58
This is a result of https://github.com/dotnet/runtime/issues/66815, which is an intentional change that increased the precision of these operations. There is a previous discussion in https://github.com/dotnet/runtime/issues/80549

**Comment by Neme12** [comment] 2023-09-08 21:10
> I'm avoiding using DateTime.AddSeconds() and using DateTime.Add(TimeSpan.FromSeconds()) instead

The issue isn't in AddSeconds. The issue is in Add(TimeSpan.FromSecond(double)), where you are passing in a `double` and expecting it to behave like `decimal`. `double` is inherently imprecise in that it can't exactly represent decimal values like `1.2`.

**Comment by Neme12** [comment] 2023-09-08 21:14
I think there should be an overload of `TimeSpan.FromSeconds` that takes a `decimal`, because of issues like this when using `double`.

**Comment by Neme12** [comment] 2023-09-08 21:14
cc @tannergooding

**Comment by tarekgh** [comment] 2023-09-08 21:53
This is announced by the breaking change https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/7.0/datetime-add-precision. Closing this as duplicate of https://github.com/dotnet/runtime/issues/80549

**Closed by tarekgh** 2023-09-08 21:53 UTC
Labels: untriaged, area-System.DateTime
