### ISSUE TITLE
Regex different behavior on .NET 6 and 7

### ISSUE THREAD

**Issue by qtoyam** [dotnet/runtime#74266] opened 2022-08-19 17:58 UTC
### Description

Code blocks `Sample 1` and `Sample 2` give equal results on .NET 6 but different on .NET 7.

### Reproduction Steps

Code:
```cs
using System.Text.RegularExpressions;

Regex regex = new(@"<a class=""btn"" href=""(?<href>.+)"" role=""button"">(?<num>\d+)<\/a>");
string str =
@"
start
...
<a class=""btn"" href=""x1"" role=""button"">110</a>
...
<a class=""btn"" href=""x1"" role=""button"">110</a>
...
end
";
int start = str.IndexOf("...");
int end = str.LastIndexOf("...");
{
	//Sample 1
	var match = regex.Match(str, start, end - start);
	var match2 = match.NextMatch();
	Console.WriteLine($"Sample 1: {match.Success}, {match2.Success}");
}
{
	//Sample 2
	string subStr = str.Substring(start, end - start);
	var match = regex.Match(subStr);
	var match2 = match.NextMatch();
	Console.WriteLine($"Sample 2: {match.Success}, {match2.Success}");
}
```

### Expected behavior

On both .Net 6 and 7:
Sample 1: True, True
Sample 2: True, True

### Actual behavior

.NET 6:
Sample 1: True, True
Sample 2: True, True

.NET 7:
Sample 1: True, False
Sample 2: True, True

### Configuration

VS 22 Version 17.4.0 Preview 1.0
.NET 6.0.400
,NET 7.0.100-preview.5.22307.18 / 7.0.100-preview.7.22377.5

**Comment by Clockwork-Muse** [comment] 2022-08-19 18:40
... regardless of the outcome of this issue, parsing HTML via Regex does not perform or behave well, and the recommendation is to use a purpose-built parser.

**Comment by danmoseley** [comment] 2022-08-19 20:09
[Indeed](https://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags/1732454#1732454)

Looking..

**Comment by danmoseley** [comment] 2022-08-19 20:25
Slightly simplified repro
```c#
using System.Text.RegularExpressions;

Regex regex = new(@"_(\d+)");
string str = @" :_0_0: ";

int start = str.IndexOf(":");
int end = str.LastIndexOf(":");
{
	var match = regex.Match(str, 1, 5);
	var match2 = match.NextMatch();
	Console.WriteLine($"Sample 1: {match.Success}, {match2.Success}");
}
{
	var match = regex.Match( str.Substring(1, 5));
	var match2 = match.NextMatch();
	Console.WriteLine($"Sample 2: {match.Success}, {match2.Success}");
}
```

It seems NextMatch is no longer advancing to the position the last match ended.

**Comment by am11** [comment] 2022-08-19 20:43
Reproduces with `7.0.0-preview.7.22375.6` but not `7.0.0-rc.1.22411.12`.

**Comment by danmoseley** [comment] 2022-08-19 20:56
Probably fixed by #72728

**Closed** 2022-08-19 20:57 UTC
Labels: area-System.Text.RegularExpressions, regression-from-last-release

**Comment by qtoyam** [comment] 2022-08-19 21:32
> can you please try a build from https://github.com/dotnet/installer and confirm you're all good?

Yes, it works with .NET 7.0.100-rc.2.22419.9. Thank you!

**Comment by danmoseley** [comment] 2022-08-19 22:58
Great. By the way, you've probably seen our posts on regex perf improvements in .NET 5, 6, 7. Let us know if you have feedback on those.  Also you can try the source generator
https://devblogs.microsoft.com/dotnet/regular-expression-improvements-in-dotnet-7/#source-generation

Note in latest builds the attribute  [RegexGenerator] changed to [GeneratedRegex]

**Comment by danmoseley** [comment] 2022-08-19 22:58
@stephentoub since folks may refer to your blog post above for reference, should we add a note somehow about the name change?

**Comment by stephentoub** [comment] 2022-09-06 02:46
> should we add a note somehow about the name change?

I added an EDIT note in the text of the post.
