### ISSUE TITLE
.NET 5.0+ Marshal.PtrToStructure  is slower 8x than netcore3.1

### ISSUE THREAD

**Issue by sunliusi** [dotnet/runtime#45100] opened 2020-11-23 03:07 UTC
Here is my test code:

```csharp
public class PtrBenchmarkTest
    {
        private readonly byte[] buff = new byte[Marshal.SizeOf<StructObject>()];

        public PtrBenchmarkTest()
        {
            var obj = new StructObject();
            obj.Symbol = "rb2101";
            obj.Exchange = 12;
            obj.Px = 54.90F;
            unsafe
            {
                fixed (byte* bp = buff)
                {
                    Marshal.StructureToPtr(obj, (IntPtr)bp, false);
                }
            }
        }

        [Benchmark]
        public StructObject PtrToStructure()
        {
            unsafe
            {
                fixed (byte* bp = buff)
                {
                    return (StructObject)Marshal.PtrToStructure((IntPtr)bp, typeof(StructObject));
                }
            }
        }
    }

    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public class StructObject
    {
        [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 16)]
        public string Symbol;

        [MarshalAs(UnmanagedType.I8)]
        public Int64 Exchange;

        [MarshalAs(UnmanagedType.R4)]
        public float Px;
    };

```
netcore3.1 Benchmark test result:
|         Method |      Mean |     Error |    StdDev |    Median |
|--------------- |----------:|----------:|----------:|----------:|
| PtrToStructure | 522.44 ns | 29.418 ns | 84.878 ns | 503.07 ns |

net5.0 Benchmark test result:
|         Method |        Mean |      Error |     StdDev |      Median |
|--------------- |------------:|-----------:|-----------:|------------:|
| PtrToStructure | 4,098.30 ns | 132.015 ns | 372.350 ns | 4,004.22 ns |

os: windows 10

**Comment by GrabYourPitchforks** [comment] 2020-11-23 04:18
Note to whoever looks into this - the PR https://github.com/dotnet/runtime/pull/32520 will impact `PtrToStructure` performance. If you're running benchmarks between 3.x / 5.0 / 6.0 master, double-check whether that PR has been merged, otherwise it could mask any regressions introduced in 5.0.

**Comment by jkotas** [comment] 2020-11-23 05:48
@jkoritzinsky

**Comment by jkoritzinsky** [comment] 2020-11-23 18:19
This regression was caused by https://github.com/dotnet/coreclr/pull/26340. That PR improved performance in the P/Invoke and Reverse P/Invoke cases, but we didn't realize until recently that it regressed performance for the Marshal APIs.

Generally for best performance in interop scenarios, we [recommend using blittable types](https://docs.microsoft.com/dotnet/standard/native-interop/best-practices) when possible.

In any case, I'll investigate and see if there's a way we can get this performance loss back in .NET 6.

**Comment by NN---** [comment] 2020-11-23 18:27
@sunliusi Unexpectedly in C# it is type safer to use pointers , also it makes faster code since it doesn't involve copying which Marshal methods do.

**Comment by sunliusi** [comment] 2020-11-26 03:12
It is more efficient to use Pointers directly.

here is my code:
`[Benchmark]
        public StructObject ReadIntPtrUtf8()
        {
            var packet = new StructObject();
            unsafe
            {
                fixed (byte* bp = buff)
                {
                    packet.Symbol = Encoding.UTF8.GetString(bp, 16);
                    Unsafe.Copy(ref packet.Exchange, bp + 16);
                    Unsafe.Copy(ref packet.Px, bp + 24);
                }
            }
            return packet;
        }`

netcore3.1 Benchmark test result:
|         Method |      Mean |     Error |    StdDev |    Median |
|--------------- |----------:|----------:|----------:|----------:|
| ReadIntPtrUtf8 |  63.93 ns |  2.083 ns |  6.011 ns |  62.61 ns |
| PtrToStructure | 575.86 ns | 25.006 ns | 69.292 ns | 555.69 ns |

net5.0 Benchmark test result:
|         Method |        Mean |     Error |     StdDev |      Median |
|--------------- |------------:|----------:|-----------:|------------:|
| ReadIntPtrUtf8 |    54.64 ns |  2.280 ns |   6.541 ns |    53.60 ns |
| PtrToStructure | 3,483.66 ns | 69.699 ns | 169.657 ns | 3,424.06 ns |

**Comment by AaronRobinsonMSFT** [comment] 2021-06-22 03:38
I think given we have a best-practice and there was a reason for other more common scenarios to be improved we can defer this for now.

**Comment by deeprobin** [comment] 2022-02-19 13:43
I suspect it is because we are creating a new instance via the `Activator`.
https://github.com/dotnet/runtime/blob/0419950e047cc1a75892b2bde78400dccaef7c4e/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.cs#L529-L555
Can you provide a benchmark which affects the generic overload `PtrToStructure<T>`.

**Comment by gchernis** [comment] 2023-02-03 13:19
The performance issue is real.  We have relied on the performant mapping of bytes to structs with MarshalAs/SizeConst for quite some time, with just under 100 hits throughout the code base.

**Comment by d79ima** [comment] 2023-02-03 14:43
> The performance issue is real. We have relied on the performant mapping of bytes to structs with MarshalAs/SizeConst for quite some time, with just under 100 hits throughout the code base. Please find the time to resurrect the speed.

I would second that

**Comment by AaronRobinsonMSFT** [comment] 2023-02-03 15:57
> The performance issue is real. We have relied on the performant mapping of bytes to structs with MarshalAs/SizeConst for quite some time, with just under 100 hits throughout the code base. Please find the time to resurrect the speed.

For the best performance avoiding this API is recommended. As noted in https://github.com/dotnet/runtime/issues/45100#issuecomment-734048041, it is far more efficient to fallback to pointers if needed or ideally switch over to [`LibraryImport`](https://learn.microsoft.com/dotnet/standard/native-interop/pinvoke-source-generation) with [custom struct marshalling](https://learn.microsoft.com/dotnet/standard/native-interop/tutorial-custom-marshaller) - which can provide the most ideal performance.

This isn't to say the issue isn't real, it very much is a regression. The push back is based on the benefits that were gained in the other scenarios as noted in https://github.com/dotnet/runtime/issues/45100#issuecomment-732339540.

Understanding why teams cannot move to blittable types or `LibraryImport` will help us to provide guidance but at this point effort to gain back the regression for this API will be minimal.

**Comment by Symbai** [comment] 2023-02-04 11:06
> ideally switch over to [`LibraryImport`](https://learn.microsoft.com/dotnet/standard/native-interop/pinvoke-source-generation) with [custom struct marshalling](https://learn.microsoft.com/dotnet/standard/native-interop/tutorial-custom-marshaller) - which can provide the most ideal performance.

It would be superior if we could use VS to convert existing structs into `custom struct marshalling ones`. Especially as we can currently use VS to convert `DllImport` to `LibraryImport`. This would makes it a LOT easier for developers to gain the most performance without knowing all the underlying details. Can this be done? Where can I add a request for it?

**Comment by AaronRobinsonMSFT** [comment] 2023-02-04 23:59
> Can this be done? Where can I add a request for it?

It can. @jkoritzinsky has been working on a source generator for producing custom struct marshallers. Work is being done for a COM source generator right now. After that, having support for a source generator solution is possible, especially with user request. Feel free to file a new issue in this repo for that feature.

/cc @agocke @dotnet/interop-contrib

**Closed** 2023-02-10 16:57 UTC
Labels: tenet-performance, area-Interop-coreclr, in-pr
