### ISSUE TITLE
Executable from `dotnet publish` with -p:PublishSingleFIle=true for Apple Silicon M1 is not working. .net 6 preview 7

### ISSUE THREAD

**Issue by parkycai** [dotnet/runtime#57552] opened 2021-08-17 05:44 UTC
```--self-contained``` is working, but with ```-p:PublishSingleFile=true```, it's broken.

Test Script:
```
mkdir helloworld
cd helloworld 
dotnet new console

echo "### Testing dotnet run"
dotnet run

echo "### Testing intel publish"
dotnet publish --self-contained -r osx-x64 -p:PublishSingleFile=true -o intel
lipo -info intel/helloworld
./intel/helloworld                                                     

echo "### Testing arm64 publish"
dotnet publish --self-contained -r osx-arm64 -p:PublishSingleFile=true -o arm64
lipo -info arm64/helloworld
./arm64/helloworld 
```

My output:
```
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on /Users/waynecai/Documents/Workspaces/NetCore/helloworld/helloworld.csproj...
  Determining projects to restore...
  Restored /Users/waynecai/Documents/Workspaces/NetCore/helloworld/helloworld.csproj (in 126 ms).
Restore succeeded.

### Testing dotnet run
Hello, World!
### Testing intel publish
Microsoft (R) Build Engine version 17.0.0-preview-21378-03+d592862ed for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /Users/waynecai/Documents/Workspaces/NetCore/helloworld/helloworld.csproj (in 161 ms).
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  helloworld -> /Users/waynecai/Documents/Workspaces/NetCore/helloworld/bin/Debug/net6.0/osx-x64/helloworld.dll
  helloworld -> /Users/waynecai/Documents/Workspaces/NetCore/helloworld/intel/
Non-fat file: intel/helloworld is architecture: x86_64
Hello, World!
### Testing arm64 publish
Microsoft (R) Build Engine version 17.0.0-preview-21378-03+d592862ed for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /Users/waynecai/Documents/Workspaces/NetCore/helloworld/helloworld.csproj (in 159 ms).
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  helloworld -> /Users/waynecai/Documents/Workspaces/NetCore/helloworld/bin/Debug/net6.0/osx-arm64/helloworld.dll
  helloworld -> /Users/waynecai/Documents/Workspaces/NetCore/helloworld/arm64/
Non-fat file: arm64/helloworld is architecture: arm64
zsh: killed     ./arm64/helloworld
```
I notice that ```codesign -s - ./arm64/helloworld```
reports ```./arm64/helloworld: is already signed```

and ```codesign -f -s - ./arm64/helloworld```
reports 
```
./arm64/helloworld: replacing existing signature
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate: object: /Users/waynecai/Documents/Workspaces/NetCore/helloworld/arm64/helloworld malformed object (code signature data at offset 9994656 with a size of 96384, overlaps string table at offset 8608472 with a size of 62057869)
./arm64/helloworld: the codesign_allocate helper tool cannot be found or used
```

and `codesign --verify --verbose ./arm64/helloworld`
reports:
```
./arm64/helloworld: invalid signature (code or signature have been modified)
In architecture: arm64
```

Enviroments:
```
ProductName:	macOS
ProductVersion:	11.5
BuildVersion:	20G71
Hardware:

    Hardware Overview:

      Model Name: MacBook Air
      Model Identifier: MacBookAir10,1
      Chip: Apple M1
      Total Number of Cores: 8 (4 performance and 4 efficiency)
      Memory: 16 GB
      System Firmware Version: 6723.140.2
      OS Loader Version: 6723.140.2

6.0.100-preview.7.21379.14
Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
6.0.100-preview.7.21379.14 [/usr/local/share/dotnet/sdk]

```

**Comment by vitek-karas** [comment] 2021-08-17 14:30
This is a duplicate of https://github.com/dotnet/runtime/issues/57242 with a much more detailed description of the problem. Thanks for reporting this. We're working on fixing this. One possible candidate fix is https://github.com/dotnet/runtime/pull/57312.

**Comment by vitek-karas** [comment] 2021-08-17 14:31
Closing this in favor of #57242.

**Closed by vitek-karas** 2021-08-17 14:31 UTC
Labels: area-AssemblyLoader-coreclr, untriaged

**Comment by agocke** [comment] 2021-08-17 18:54
Note: if you want to workaround this in P7 you should be able to set `_EnableMacOSCodeSign` to false, then manually run `codesign -s - {appexe}` after the publish to sign the exe
