### ISSUE TITLE
MetadataLoadContext accessing attribute on base type

### ISSUE THREAD

**Issue by Forgind** [dotnet/runtime#69066] opened 2022-05-09 18:51 UTC
### Description

When I loaded an assembly using System.Reflection.MetadataLoadContext and tried to access an attribute that was only appended to a type it extended, it didn't realize it was there.

### Reproduction Steps

Load an assembly using S.R.MLC and access a type from it that extends a type with an attribute of interest—LoadInSeparateAppDomainAttribute in my case.

Try to access it with <type>.GetTypeInfo().IsDefined(typeof(LoadInSeparateAppDomainAttribute), true);

### Expected behavior

The above call returns true.

### Actual behavior

It returns false.

### Regression?

No

### Known Workarounds

You can walk through the base types until you hit the relevant one, checking each as you go like:

```C#
Type t = type;
while (t is not null) {
    if (CustomAttributeData.GetCustomAttributes(t).Any(attr => attr.AttributeType.Name.Equals(nameof(LoadInSeparateAppDomainAttribute))))
    {
         HasLoadInSeparateAppDomainAttribute = true;
    }
    t = t.BaseType;
}

### Configuration

_No response_

### Other information

_No response_

**Comment by teo-tsirpanis** [comment] 2022-05-09 21:54
I think this is by design. [`MetadataLoadContext` is described as "a closed universe of `Type` objects"](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.metadataloadcontext). Mixing `Type` objects from different sources (like another MLC or the runtime) is not expected to work.

**Comment by Forgind** [comment] 2022-05-09 23:05
Yes, but in my case, I loaded an ITaskItem from _the same_ MLC, and it still didn't work.

**Comment by Forgind** [comment] 2022-05-09 23:07
I had something similar with checking if a particular type extends an interface, and even if I loaded the interface from the same MLC, it still always returned false. I actually neglected to verify the same was true in this case, but I'd guess so. (I can try to check if you'd like.)

**Comment by buyaa-n** [comment] 2022-05-17 05:47
I wonder why you did not get an exception, for me an exception thrown, which clearly expressed that it is not supported by MLC:
`System.InvalidOperationException: 'The requested operation cannot be used on objects loaded by a MetadataLoadContext. Use CustomAttributeData instead.'`
Apparently your only option is the workaround you mentioned

**Comment by Forgind** [comment] 2022-05-17 19:14
Why should it not be supported on objects loaded by a MLC? Especially if I provide an attribute loaded from the MLC, it seems pretty reasonable.

**Comment by steveharter** [comment] 2022-11-02 21:02
> I think this is by design. [MetadataLoadContext is described as "a closed universe of Type objects"](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.metadataloadcontext). Mixing Type objects from different sources (like another MLC or the runtime) is not expected to work.

Yes exactly.

> Try to access it with .GetTypeInfo().IsDefined(typeof(LoadInSeparateAppDomainAttribute), true);

So `typeof(LoadInSeparateAppDomainAttribute)` will return a Type that from the runtime, not from MetadataLoadContext. You'll have to get ask for that type from MLC.

**Comment by steveharter** [comment] 2022-11-02 21:02
Closing as by design

**Closed by steveharter** 2022-11-02 21:02 UTC
Labels: area-System.Reflection, needs-further-triage
