### ISSUE TITLE
Sometimes enums are not blittable on Blazor WASM

### ISSUE THREAD

**Issue by mattleibow** [dotnet/runtime#61350] opened 2021-11-09 03:54 UTC
### Description

I have this pinvoke code:

```cs
[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
internal unsafe delegate UnicodeGeneralCategory UnicodeGeneralCategoryProxyDelegate(IntPtr ufuncs, UInt32 unicode, void* user_data);
```

And compiler gives this:

```
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\6.0.0\Sdk\WasmApp.Native.targets(239,5): error : The return type 'BlazorApp8.UnicodeGeneralCategory' of pinvoke callback method 'BlazorApp8.UnicodeGeneralCategory GeneralCategoryProxyImplementation(System.IntPtr, System.UInt32, System.Void*)' needs to be blittable.
```

### Reproduction Steps

[BlazorApp8.zip](https://github.com/dotnet/runtime/files/7501826/BlazorApp8.zip)

### Expected behavior

Compiles

### Actual behavior

Error

### Regression?

Probably not.

### Known Workarounds

Make the return type an int and then cast to an enum.

**Comment by radical** [comment] 2021-11-09 04:02
Dupe of https://github.com/dotnet/runtime/issues/61144 .

**Closed by radical** 2021-11-09 04:02 UTC
Labels: untriaged
