### ISSUE TITLE
Test failure System.Text.Json.Serialization.Tests.ConstructorTests_SyncStream.MultipleThreadsLooping

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#69772] opened 2022-05-25 02:21 UTC
Run: [runtime-libraries-coreclr outerloop 20220524.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1786285&view=ms.vss-test-web.build-test-results-tab&runId=47814616&paneView=debug&resultId=103484)

Failed test:
```
net7.0-Linux-Release-arm64-CoreCLR_release-(Alpine.313.Arm64.Open)ubuntu.1804.armarch.open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.13-helix-arm64v8-20210910135808-8a6f4f3

- System.Text.Json.Serialization.Tests.ConstructorTests_SyncStream.MultipleThreadsLooping

```
**Error message:**
````
Assert.Equal() Failure
↓ (pos 0)
Expected: value
Actual:   JsonDocument { RootElement = Hello }
↑ (pos 0)


Stack trace
   at System.Text.Json.Serialization.Tests.ObjWCtorMixedParams.Verify() in /_/src/libraries/System.Text.Json/tests/Common/TestClasses/TestClasses.Constructor.cs:line 1068
   at System.Text.Json.Serialization.Tests.Parameterized_Class_With_ComplexTuple.Verify() in /_/src/libraries/System.Text.Json/tests/Common/TestClasses/TestClasses.Constructor.cs:line 1986
   at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__DeserializeObjectAsync|13_0(String json, Type type, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.Cache.cs:line 34
   at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__DeserializeObjectNormalAsync|13_3(Type type, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.Cache.cs:line 53
   at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__RunTestAsync|13_5(Type type) in /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.Cache.cs:line 82
   at System.Text.Json.Serialization.Tests.ConstructorTests.MultipleThreads() in /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.Cache.cs:line 87
   at System.Text.Json.Serialization.Tests.ConstructorTests.MultipleThreadsLooping() in /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.Cache.cs:line 22
--- End of stack trace from previous location ---
````
No Kusto information.

**Comment by krwq** [comment] 2022-06-07 11:11
@VincentBu is this consistently failing or a single instance? I haven't seen this locally

**Comment by VincentBu** [comment] 2022-06-08 01:09
We will leave comment if the tests fail again after 7 days. According to the thread, this test hasn't failed in the past week.

**Comment by krwq** [comment] 2022-07-07 13:09
This seem to be the same root cause as https://github.com/dotnet/runtime/issues/65418 so closing this issue in favor of the other one

**Closed by krwq** 2022-07-07 13:09 UTC
Labels: bug, arch-arm32, area-System.Text.Json, os-linux, blocking-outerloop
