### ISSUE TITLE
Add BlockingCollection<T>.GetConsumingAsyncEnumerable()

### ISSUE THREAD

**Issue by mburbea** [dotnet/runtime#47587] opened 2021-01-28 18:05 UTC
## Background and Motivation
BlockingCollection provides an excellent mechanism for wrapping producer consumers patterns. My proposal is to create a IAsyncEnumerable() so that when the enumerable is not yet complete but is currently empty, instead of blocking the api can yield. 

## Proposed API
```diff
public partial class BlockingCollection<T>
{
+    public IAsyncEnumerable<T> GetConsumingAsyncEnumerable(CancellationToken cancellationToken);
}
```
-->

## Usage Examples
The usage would look like the following::
```cs
public Task DoSomeWorkAsync(CancellationToken cancellationToken)
{
     var collection = new BlockingCollection<T>();
     var producer = Producer(collection);
     var workers =  Enumerable.Range(0, 4).Select(x=> 
     Worker(collection.GetConsumingEnumerableAsync(cancellationToken)).ToArray();
     await Task.WhenAll(workers.Prepend(producer));
}
```

## Risks
- None?

**Comment by theodorzoulias** [comment] 2021-01-29 11:58
The `BlockingCollection` class is blocking by nature. Its expected behavior is embedded in its name. Being able to consume it without being blocked would be a bit paradoxical.

**Comment by davidfowl** [comment] 2021-01-29 12:11
> BlockingCollection has zero support in its implementation today for asynchronously retrieving values, via an enumerable or otherwise. I'd recommend using Channel<T> instead.

Can we add this to the blocking collection API docs?

**Comment by eiriktsarpalis** [comment] 2021-01-29 20:27
> Can we add this to the blocking collection API docs?

I've posted a PR that adds that recommendation to dotnet-api-docs. 

I'm going to close this issue since we won't consider adding async support to `BlockingCollection<T>`.

**Closed by eiriktsarpalis** 2021-01-29 20:27 UTC
Labels: api-suggestion, area-System.Linq, documentation
