### ISSUE TITLE
AzDO "runtime-libraries stress-http" pipeline failures

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#38944] opened 2020-07-08 17:22 UTC
This pipeline continues to fail every run.

Example failure snippet:
```
client_1  | Error from iteration 5848 (13: PUT Slow) in task 3 with 21915 successes / 1 fails:
client_1  | System.Net.Http.HttpRequestException: An error occurred while sending the request.
client_1  |  ---> System.IO.IOException: The request was aborted.
client_1  |  ---> System.IO.IOException: The response ended prematurely while waiting for the next frame from the server.
client_1  |    at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
client_1  |    --- End of inner exception stack trace ---
client_1  |    at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
client_1  |    at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
client_1  |    at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders()
client_1  |    at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(CancellationToken cancellationToken)
client_1  |    at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
client_1  |    --- End of inner exception stack trace ---
client_1  |    at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
client_1  |    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
client_1  |    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
client_1  |    at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts, CancellationToken callerToken, Int64 timeoutTime)
client_1  |    at HttpStress.RequestContext.SendAsync(HttpRequestMessage request, HttpCompletionOption httpCompletion, Nullable`1 token) in /app/ClientOperations.cs:line 94
client_1  |    at HttpStress.ClientOperations.<>c.<<get_Operations>b__1_13>d.MoveNext() in /app/ClientOperations.cs:line 465
client_1  | --- End of stack trace from previous location ---
client_1  |    at HttpStress.StressClient.<>c__DisplayClass15_0.<<StartCore>g__RunWorker|2>d.MoveNext() in /app/StressClient.cs:line 165
```

https://dev.azure.com/dnceng/public/_build/results?buildId=720846&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=45b31e99-b18c-506f-46cf-7d3a4d5140a9

Builds were apparently fixed with https://github.com/dotnet/runtime/pull/35011. `stress-ssl` pipeline is now clean, but `stress-http` is still failing.

@dotnet/ncl @alnikola Is there already work being done (and an issue) to fix this?

**Comment by alnikola** [comment] 2020-07-09 12:51
It's on our team's backlog, but currently we are busy with other higher priority tasks.

**Comment by alnikola** [comment] 2020-08-13 13:12
This error is already tracked in the umbrella issue. #40388 

>Http2Stream.ReadResponseHeadersAsync / Http2Connection.ProcessIncomingFramesAsync / IOException: The response ended prematurely while waiting for the next frame from the server.

**Comment by alnikola** [comment] 2020-08-13 13:12
Duplicate of #40388

**Closed by alnikola** 2020-08-13 13:12 UTC
Labels: area-System.Net, test bug
