### ISSUE TITLE
Problem with debugging WASM

### ISSUE THREAD

**Issue by exo0** [dotnet/runtime#82777] opened 2023-02-28 08:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi, 

I'm trying to debug a fresh Blazor WASM application. Unfortunately I'm getting the following error:

```
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] sending error response for id: msg-:::2 -> [Result: IsOk: False, IsErr: True, Value: , Error: {   "code": -32602,   "message": "Domain must be enabled" } ]
```

### Steps To Reproduce

Create a new WASM application in Visual Studio 2022

Checked that those packages are installed:
```
Microsoft.AspNetCore.Components.WebAssembly
Microsoft.AspNetCore.Components.WebAssembly.DevServer
```
Checked that inspectUri exists:
```
"inspectUri": "{wsProtocol}://{url.hostname}:{url.port}/_framework/debug/ws-proxy?browser={browserInspectUri}",
```

Tried to debug it on client side using Google Chrome and Edge, but after I open the debug console SHIFT + ALT + D
I'm getting the following error in debug console 

```
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] sending error response for id: msg-:::2 -> [Result: IsOk: False, IsErr: True, Value: , Error: {   "code": -32602,   "message": "Domain must be enabled" } ]
```

I also tried to debug it inside the Visual Studio or VSCode, but no symbols were added. 

### .NET Version

6.0.309

### Anything else?

dotnet --info
```
.NET SDK (reflecting any global.json):
 Version:   6.0.309
 Commit:    f629b020f8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.309\

global.json file:
  Not found

Host:
  Version:      6.0.14
  Architecture: x64
  Commit:       2a90daa2cc

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.114 [C:\Program Files\dotnet\sdk]
  6.0.300 [C:\Program Files\dotnet\sdk]
  6.0.309 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

VSCode version 
```
1.75.1
```

VS2022 Version
```
x64 17.2.0
```

**Comment by thaystg** [comment] 2023-02-28 17:46
@exo0 I can reproduce the message "domain must be enables" but I can still add breakpoints and debug it after pressing alt-shift-d, is this your scenario?
![image](https://user-images.githubusercontent.com/4503299/221935040-ee8447cb-1141-45cd-9e38-b8682a5e431f.png)

Also, from VS or VSCode how are you trying to debug?
Can you share with us your solution?

Thanks.

**Comment by exo0** [comment] 2023-02-28 22:14
I'm trying to debug a sample WebAssembly application like you're. In my case, it looks like that 
![image](https://user-images.githubusercontent.com/36488878/221993090-8467c724-5d44-4d71-b846-aea2578cefc5.png)

As you can see in the picture above I can't see the file:// objects. 
Regarding VS or VSCode, I'm not getting any errors, just information that "No symbols have been loaded for this document"

![image](https://user-images.githubusercontent.com/36488878/221993578-35b4c428-b99a-4d35-80dc-f4eeb915e59c.png)

**Comment by thaystg** [comment] 2023-02-28 22:21
> WebAssembly application like you're. In my case, it looks like that

Which browser are you using?
Also which command are you using to run the app?
Also can you paste here an screenshot of the DevTools console?

**Comment by exo0** [comment] 2023-03-01 21:17
Chrome (v.110.0.5481.178) and Edge (v.110.0.1587.57)

I'm using this command (Chrome example):
```
chrome --remote-debugging-port=9222 --user-data-dir="C:\Users\Michal.Deska\AppData\Local\Temp\blazor-chrome-debug" https://localhost:8741/counter
```

Of course:
![image](https://user-images.githubusercontent.com/36488878/222266912-9d3889c8-83d5-4fb7-acc7-cdf28fc2c73a.png)

**Comment by thaystg** [comment] 2023-03-01 21:19
And you are running the app using `dotnet run`?

**Comment by exo0** [comment] 2023-03-02 17:43
I was trying to run it by ```dotnet run``` or by clicking the arrow button on UI (VSCode and VS2022), but it doesn't matter, because I'm getting this same effect. 
![image](https://user-images.githubusercontent.com/36488878/222508148-d8f5e13e-0c22-471b-b73d-0be5ce522d36.png)


Regarding my path so it is standard: https://localhost:8741/counter

An additional thing that I found when I started playing with the tabs inside DevTools and opened the "Application" tab
![image](https://user-images.githubusercontent.com/36488878/222508910-32b36251-e1bc-450d-9183-fe0e11abbc04.png)
I got the following error:
![image](https://user-images.githubusercontent.com/36488878/222508765-2e754fd6-8bda-4c5d-9474-394452ee6b9c.png)

**Comment by exo0** [comment] 2023-03-02 18:05
Small update from my side:
- added to chrome properties to run as an administrator
-  changed code that I was using to debug from
```chrome --remote-debugging-port=9222 --user-data-dir="C:\Users\Michal.Deska\AppData\Local\Temp\blazor-chrome-debug" https://localhost:9541/counter```
to
```chrome --remote-debugging-port=9222 --user-data-dir="C:\Users\Michal.Deska\AppData\Local\Temp\blazor-chrome-debug" http://localhost:9541/counter```

After this operation, I was able to see code inside DevTools

Anyway, from VSCode or VS2022 it's still don't working (I'm running VSCode and VS2022 as an administrator), additionally I changed the browser properties inside VS2022 during the start to meet the same criteria that I'm using by clicking WIN + R 

![image](https://user-images.githubusercontent.com/36488878/222513862-1462083f-1024-4be4-8741-4621e2c97be2.png)

**Comment by exo0** [comment] 2023-03-06 22:08
Thank you, after I disabled HTTPS it started working. Anyway, it's normal behavior? I mean that without https it's working correctly? In this scenario I need two separate profiles: 
- without HTTPS to be able to debug it locally
- with HTTPS to deploy it on the remote environment

**Comment by thaystg** [comment] 2023-03-06 22:10
Can you run this command and then test http again?

`dotnet dev-certs https --trust`

**Comment by exo0** [comment] 2023-05-30 08:42
Hi, sorry for the delay from my side. I tried this command but I was getting the following error:
![image](https://github.com/dotnet/runtime/assets/36488878/a95ccae5-d36b-4f9a-908e-ab06408011ce)

**Comment by thaystg** [comment] 2023-05-31 14:06
Can you run it in an administrator command prompt?

**Comment by thaystg** [comment] 2023-07-26 18:31
I will close the issue because I didn't have any feedback.

**Closed by thaystg** 2023-07-26 18:31 UTC
Labels: arch-wasm, area-Debugger-mono
