### ISSUE TITLE
[AOT] In special generate argument, the aot application will crash

### ISSUE THREAD

**Issue by Cricle** [dotnet/runtime#105397] opened 2024-07-24 12:43 UTC
### Description

```csharp
interface ITest<TResult>
{
    TReturn UsingDatabaseResult<TState, TReturn>(TState state, Func<TResult, TState, TReturn> @using);
}
class Test<TResult>:ITest<TResult>
{
    public TReturn UsingDatabaseResult<TState, TReturn>(TState state, Func<TResult, TState, TReturn> @using)
    {
        return default;
    }
}

//The main method
ITest<object> t = new Test<object>();
t.UsingDatabaseResult<IEnumerable<IEnumerable<double?>>, int>(null, (x,y) => 1);

```

Use command ` dotnet publish -c Release -r win-x64 -p:PublishAot=true -f net8.0` and run the app will print

```
Process terminated. Failed to create generic virtual method implementation

Declaring type: npnp.Test`1<System.Object>
Method name: UsingDatabaseResult
Instantiation:
  Argument 00000000: System.Collections.Generic.IEnumerable`1<System.Collections.Generic.IEnumerable`1<System.Nullable`1<System.Double>>>
  Argument 00000001: System.Int32
```

### Reproduction Steps

Publish with aot and run the code

### Expected behavior

No crash

### Actual behavior

Crash with message

### Configuration

```
Host:
  Version:      8.0.7
  Architecture: x64
  Commit:       2aade6beb0

.NET SDKs installed:
  7.0.202 [C:\Program Files\dotnet\sdk]
  8.0.100 [C:\Program Files\dotnet\sdk]
  8.0.303 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by huoyaoyuan** [comment] 2024-07-24 12:47
Looks like duplicate of #104913

**Closed** 2024-08-02 07:48 UTC
Labels: in-pr, area-NativeAOT-coreclr
