### ISSUE TITLE
MemoryCache looses entries when SetEntry results in exceeding capacity.

### ISSUE THREAD

**Issue by fuocor** [dotnet/runtime#61495] opened 2021-11-12 04:44 UTC
### Description

The new implementation of the memory cache will drop an entry that is being set when it results in the capacity being exceeded.

The following method will not update the cache size when it results in it overloading

https://github.com/dotnet/runtime/blob/99dd33b9740d86a7da112d077226b5785ff03cd6/src/libraries/Microsoft.Extensions.Caching.Memory/src/MemoryCache.cs#L321

which result in the `SetEntry` triggering compaction and invalidating any prior entry and issuing an eviction notice on the new one.

The only problem is that a caller using any of the extension methods is clueless to the fact that the new entry was rejected. 

### Reproduction Steps

Reduce the SizeLimit  or increase the time until the test fails 
https://github.com/dotnet/runtime/blob/5fa6dd364982be4ffd83358adbf130d88049c72a/src/libraries/Microsoft.Extensions.Caching.Memory/tests/MemoryCacheSetAndRemoveTests.cs#L612

### Expected behavior

Either add the new entry prior to triggering compaction or reevaluate how the extension methods deal with the eviction notice after the entry is disposed.

### Actual behavior

The entry falls into a black hole

### Configuration

net6
Windows
x64

it is on all platforms

**Comment by adamsitnik** [comment] 2023-11-15 11:38
Closing as a duplicate of #42624 (or #36039).

**Closed by adamsitnik** 2023-11-15 11:38 UTC
Labels: bug, area-Extensions-Caching
