### ISSUE TITLE
WASM windows AOT: Timeout compiling native assets with emcc with -Oz

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#84362] opened 2023-04-05 17:46 UTC
Found in PR: https://github.com/dotnet/runtime/pull/84079

### Error Blob

```json
{
  "ErrorMessage": "Executor timed out after 3600 seconds and was killed",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Reproduction Steps

- Queue: `browser-wasm windows Release LibraryTests_AOT`
- Job: https://dev.azure.com/dnceng-public/public/_build/results?buildId=227876&view=logs&j=b455efc5-4fe2-50ab-5106-412ad73c23a0&t=607d8ddd-2371-58ff-95a3-14f9242e8c35&l=60
- Log: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-84079-merge-46b8794d92c04656b2/WasmTestOnBrowser-System.Runtime.Tests/1/console.e6badc04.log?helixlogtype=result
- Output:
```
  ...
  [67/68] System.Runtime.Tests.dll -> System.Runtime.Tests.dll.bc
  [68/68] aot-instances.dll -> aot-instances.dll.bc
  Compiling native assets with emcc with -Oz. This may take a while ...

...
[EXECUTION TIMED OUT]
Exit Code:-3Executor timed out after 3600 seconds and was killed

['WasmTestOnBrowser-System.Runtime.Tests' END OF WORK ITEM LOG: Command timed out, and was killed]
```

**Comment by lewing** [comment] 2023-04-05 17:53
this is a duplicate of https://github.com/dotnet/runtime/issues/83655 and should be fixed

**Closed by lewing** 2023-04-05 17:53 UTC
Labels: arch-wasm, os-windows, blocking-clean-ci, untriaged, wasm-aot-test, Known Build Error, needs-area-label
