### ISSUE TITLE
Every minor version of .NET 5 exist at the same time

### ISSUE THREAD

**Issue by doyenho** [dotnet/runtime#57629] opened 2021-08-18 07:53 UTC
The minor version should replace the older version, else they will occupy large disk space, no many garbage files there.

**Comment by KalleOlaviNiemitalo** [comment] 2021-08-29 22:48
This might be a duplicate of <https://github.com/dotnet/installer/issues/7368>, if the leftover directories were empty. However, @doyenho mentioned "many garbage files".

**Comment by NikolaMilosavljevic** [comment] 2021-09-01 20:47
[Triage] @doyenho can you share the steps to get to the state you see on your machine? Which installers did you run, etc?

**Comment by NikolaMilosavljevic** [comment] 2021-09-22 20:35
[Triage] Closing, not enough information to investigate this issue.

**Closed by NikolaMilosavljevic** 2021-09-22 20:35 UTC
Labels: needs more info, area-Setup, untriaged
