### ISSUE TITLE
Disabled tests: System.IO.MemoryMappedFiles.MemoryMappedViewAccessor.ValidAccessLevelCombinations on MacCatalyst arm64

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#53601] opened 2021-06-02 14:06 UTC
Disabled in https://github.com/dotnet/runtime/pull/53197#issuecomment-852603282:
* `System.IO.MemoryMappedFiles.Tests.MemoryMappedViewAccessorTests.ValidAccessLevelCombinations`
* `System.IO.MemoryMappedFiles.Tests.MemoryMappedViewStreamTests.ValidAccessLevelCombinations`

Probably unrelated to https://github.com/dotnet/runtime/issues/49104 (which has `PlatformDetection.IsMacOsAppleSilicon` applied - so maybe we need `IsMacOsCatalystAppleSilicon`, too), because most of the other tests are passing.  Just the ones that are trying various permissions.

In particular the ReadWriteExecute permissions tests aren't likely to work (because of the W^X prohibition on silicon).

**Comment by SamMonoRT** [comment] 2021-06-24 19:01
@BrzVlad - please take a look.

**Comment by lambdageek** [comment] 2021-06-24 19:26
IMO, the important thing here is to understand if just read-only or read-write permissions are working.  The write-execute stuff is expected not to work on Apple M1

**Comment by BrzVlad** [comment] 2021-08-02 07:44
I'm not sure yet what is the proper fix for this. Here are the conclusions though.
- when trying to do mappings with write execute permissions, which are not supposed to work, mmap returns 0 and the mapping attempt throws. We already have a catch for such exceptions on MacOS where the test is skipped, I guess we could just add another check for MacOSCatalyst and not bother anymore with it ? Other mappings work fine.
- I don't know what was originally reproduced, but locally I was getting a crash with test args `[InlineData(MemoryMappedFileAccess.ReadExecute, MemoryMappedFileAccess.ReadExecute)]`. The mapping was created successfully but when accessing the mapped memory the application simply crashed. After some investigation it turns out codesigning the application fixes this issue. I did this manually, are we already codesigning automatically on the CI ?

**Comment by BrzVlad** [comment] 2021-08-05 18:07
Disabled test on maccatalyst

**Closed by BrzVlad** 2021-08-05 18:07 UTC
Labels: disabled-test, area-Codegen-Interpreter-mono, runtime-mono, os-maccatalyst
