### ISSUE TITLE
Exception when Deserializing Nullable<double>

### ISSUE THREAD

**Issue by ashotkhachatryan** [dotnet/runtime#81025] opened 2023-01-23 14:08 UTC
### Description

We are using **DataContractSerializer** and **XmlDictionaryReader** to deserialize binary data coming from server. After upgrading .NET version from 6 to 7 we are getting an exception - **The input source is not correctly formatted.**

After some investigation we found that the issue happens if one of DataMembers is Nullable double and it throws an exception not always but for some values.

Please note that **.NET7** preview versions work fine as well.

### Reproduction Steps

Create a Console application using .NET 7 and run the following code.
Change back to .NET6 and make sure that works fine.

```
internal class Program
{
    [DataContract(Namespace = "http://schemas.datacontract.org/2004/07/MyDataNamespace")]
    public class MyData
    {
        [DataMember()]
        public string Member1 { get; set; }

        [DataMember()]
        public Nullable<double> Member2 { get; set; }
    }
    private static void Main(string[] args)
    {
        List<MyData> data = new List<MyData>()
        {
            new MyData() { Member1 = "Mem1", Member2 = 12345678 },
            new MyData() { Member1 = "Mem2", Member2 = 87654321 },
        };

        var serializer = new DataContractSerializer(typeof(List<MyData>));

        MemoryStream s = new MemoryStream();
        var writer = System.Xml.XmlDictionaryWriter.CreateBinaryWriter(s);
        serializer.WriteObject(writer, data);
        writer.Flush();
        s.Position = 0;

        var reader = System.Xml.XmlDictionaryReader.CreateBinaryReader(s, System.Xml.XmlDictionaryReaderQuotas.Max);
        var res = serializer.ReadObject(reader, verifyObjectName: false) as List<MyData>;
        Console.WriteLine(res.Count());
    }
}
```

### Expected behavior

No exception.

### Actual behavior

Throws an exception.

**Comment by GrabYourPitchforks** [comment] 2023-01-27 05:30
Dupe of https://github.com/dotnet/runtime/issues/78913. Please reopen if this resolution is incorrect.

**Closed by GrabYourPitchforks** 2023-01-27 05:30 UTC
Labels: area-Serialization
