### ISSUE TITLE
Exception connecting to Signalr hub when using windows auth

### ISSUE THREAD

**Issue by atj414** [dotnet/runtime#39011] opened 2020-07-09 15:24 UTC
### Describe the bug
The signalr client throws an exception connecting to the hub when using Windows Authentication with core 5.0 preview 6. The hub is hosted behind IIS express.
If I change the client TargetFramework to netcoreapp3.1 it connects normally (hub is still on 5):
```
info: Microsoft.AspNetCore.Http.Connections.Client.Internal.WebSocketsTransport[1]
      Starting transport. Transfer mode: Text. Url: 'wss://localhost:44356/chathub?id=yrfeYHigZPZ1KxrRXa6xcg'.
info: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[3]
      HttpConnection Started.
info: Microsoft.AspNetCore.SignalR.Client.HubConnection[24]
      Using HubProtocol 'json v1'.
info: Microsoft.AspNetCore.SignalR.Client.HubConnection[44]
      HubConnection started.
Starting connection. Press Ctrl-C to close.
```

### To Reproduce

https://github.com/atj414/signalrbug

### Exceptions (if any)

```
Exception thrown: 'System.ComponentModel.Win32Exception' in System.Private.CoreLib.dll
Exception thrown: 'System.ComponentModel.Win32Exception' in System.Private.CoreLib.dll
An exception of type 'System.ComponentModel.Win32Exception' occurred in System.Private.CoreLib.dll but was not handled in user code

fail: Microsoft.AspNetCore.Http.Connections.Client.HttpConnection[10]
      Failed to start connection. Error getting negotiation response from 'https://localhost:44356/chathub'.
System.ComponentModel.Win32Exception (0x80090308): The token supplied to the function is invalid
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal& statusCode)
   at System.Net.NTAuthentication.GetOutgoingBlob(String incomingBlob)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.AccessTokenHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.Internal.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts, CancellationToken callerToken, Int64 timeoutTime)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync(Uri url, HttpClient httpClient, ILogger logger, CancellationToken cancellationToken)
```

### Further technical details
- VS2019 16.7.0 Preview 3.1
```
.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.6.20318.15
 Commit:    4356580024

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.6.20318.15\

Host (useful for support):
  Version: 5.0.0-preview.6.20305.6
  Commit:  4ba9ecaabd

.NET SDKs installed:
  1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.511 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]
  3.1.400-preview-015178 [C:\Program Files\dotnet\sdk]
  5.0.100-preview.6.20318.15 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-preview.6.20312.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-preview.6.20305.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-preview.6.20308.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by BrennanConroy** [comment] 2020-07-09 19:21
Transferred to Runtime as they own HttpClient.

**Comment by karelz** [comment] 2020-07-21 20:05
It would be really great to have a minimal repro without SignalR -- directly on `HttpClient` or `WebSockets`. Is that possible?

**Comment by BrennanConroy** [comment] 2020-07-21 20:16
> directly on `HttpClient`

Is:
```c#
var client = new HttpClient(new HttpMessageHandler() { UseDefaultCredentials = true });
await client.GetAsync("url");
```
not exactly that?

**Comment by karelz** [comment] 2020-07-21 22:29
@BrennanConroy I think we missed that part during our discussion based on what everyone remembered.
Are those 2 lines in HelloWorld app sufficient to reproduce it? How do I set up server to run against? Is HelloWorld ASP.NET server enough? Or does it have to be SignalR?

**Comment by BrennanConroy** [comment] 2020-07-21 23:07
SignalR not required, just a simple Server with Windows Auth enabled. You can use the app provided in the original comment and just hit the base url endpoint.

**Comment by CarnaViire** [comment] 2020-07-30 15:01
I've done a little investigation on that. As far as I've seen in my repro, the issue happens with 5.0 client and both 5.0 and 3.1 servers. However, 3.1 client works fine with both 5.0 and 3.1 servers. So I believe the problem is within the client and it was introduced somewhere in 5.0.

The debug of 5.0 client shows that during auth the client goes into negotiations with server using method GetOutgoingBlob in [NTAuthentication.Common.cs](https://github.com/dotnet/runtime/blob/master/src/libraries/Common/src/System/Net/NTAuthentication.Common.cs#L213), and first reply from server was ContinueNeeded, and the second reply was InvalidToken, which produces the [exception](https://github.com/dotnet/runtime/blob/master/src/libraries/Common/src/System/Net/NTAuthentication.Common.cs#L280) in the issue.

**Comment by geoffkizer** [comment] 2020-07-30 16:46
It would be good to debug 3.1 and see why it doesn't get InvalidToken here...

**Comment by wfurt** [comment] 2020-07-30 16:55
_if_ the Negotiate is going down the Kerberos path, we made some changes in 5. I'm going to set it up same way as @CarnaViire did and I'll take a look at the the blob.

**Comment by wfurt** [comment] 2020-07-30 21:23
For me it only fails if HTTPS is used. If I use HTTP, I get NTLM exchange and 200 at the end. 
I'm wondering if we broke ChannelBinding (or something similar) inside SslStream. 
From packet capture, I don't see anything wrong at HttpClient - it creates single connection and it fails at the end.
I will take a look at the Ssl layer.

**Comment by wfurt** [comment] 2020-07-31 07:20
I confirmed that the problem lives in ChannelBinding. If I disable that extra layer, everything works fine even with https. 
It is curious that aside from nullability, that part of code was not touched for very long time.
It also seems to be problem only on Windows. Using Linux with NTLM seems to work fine.

**Comment by geoffkizer** [comment] 2020-07-31 07:26
I was under the impression that ChannelBinding is a Windows thing... could be wrong though...

**Comment by wfurt** [comment] 2020-07-31 07:32
There seems to be fragments of managed/Unix implementation. I did not verify they are actually used. I just run same code on Linux and it works without any troubles. I'll try to do some A/B testing tomorrow with 3.1 to see if I can find any differences.

https://github.com/dotnet/runtime/blob/98eee0587dfd0752c030fe49b3fd9b45f4b2e5c5/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/AuthenticationHelper.NtAuth.cs#L123-L124

If I set `channelBinding = null;` between the lines above, authentication succeed.

**Comment by karelz** [comment] 2020-08-10 19:32
Fixed by #40222

**Comment by karelz** [comment] 2020-08-10 19:33
@wfurt please create tracking issue to add test in our enterprise test lab (in future for Windows as well)

**Comment by karelz** [comment] 2020-08-28 10:49
Reopening to track porting to 5.0

**Comment by karelz** [comment] 2020-08-28 10:50
(closing again, it was reopened by mistake, sorry)

**Closed by karelz** 2020-08-28 10:50 UTC
Labels: area-System.Net.Http, bug, tenet-compatibility
