### ISSUE TITLE
One more constructor to Microsoft.Extensions.Logging.LoggerFactory to enable DI of external scope provider

### ISSUE THREAD

**Issue by Sundow** [dotnet/runtime#52153] opened 2021-05-01 08:58 UTC
## Background and Motivation

Currently Microsoft.Extensions.Logging.LoggerFactory class always instantiates  IExternalScopeProvider with a default implementation. #50590 proposes to enable dependency injection so it is possible to use a custom implementation. This requires to add a constructor with one more parameter of type IExternalScopeProvider to be used by DI engine.

## Proposed API

```csharp
public partial class LoggerFactory : Microsoft.Extensions.Logging.ILoggerFactory
{
    public LoggerFactory(System.Collections.Generic.IEnumerable<Microsoft.Extensions.Logging.ILoggerProvider> providers, Microsoft.Extensions.Options.IOptionsMonitor<Microsoft.Extensions.Logging.LoggerFilterOptions> filterOption, Microsoft.Extensions.Options.IOptions<Microsoft.Extensions.Logging.LoggerFactoryOptions> options = null, Microsoft.Extensions.Logging.IExternalScopeProvider scopeProvider = null) { }
}
```

## Usage Examples

Will be implicitly used by DI engine.

## Risks

Low, as no existing interfaces are changed and only a trivial field assignment is required for a new one.

## Other notes
The actual implementation of the proposal already exists in #52132 and can be looked at there, but requires API change approval.

**Comment by maryamariyan** [comment] 2021-05-03 23:07
Thanks @Sundow. Closing this as dupe of https://github.com/dotnet/runtime/issues/50590, to track in one place. Updated its description with the above

**Closed by maryamariyan** 2021-05-03 23:07 UTC
Labels: api-suggestion, area-Extensions-Logging, untriaged
