### ISSUE TITLE
Stopwatch class seems to have issues with AOT

### ISSUE THREAD

**Issue by daveyostcom** [dotnet/runtime#87795] opened 2023-06-20 00:59 UTC
### Description

Building this Console F# app to publish with AOT gets warnings and running gets an exception.

### Reproduction Steps

```
Z% dotnet publish -f net8.0 -r osx-x64`
Z% bin/Release/net8.0/osx-x64/publish/StopwatchAOT
```
[Program.fs.txt](https://github.com/dotnet/runtime/files/11794787/Program.fs.txt)
[StopwatchAOT.fsproj.txt](https://github.com/dotnet/runtime/files/11794808/StopwatchAOT.fsproj.txt)

### Expected behavior

Would like it to run without an exception.
(I can’t find documentation to tell me what I have to change.)

### Actual behavior

```
Z% dotnet publish -f net8.0 -r osx-x64            
MSBuild version 17.7.0-preview-23281-03+4ce2ff1f8 for .NET
  Determining projects to restore...
  Restored /Users/me/p/f#/aot/StopwatchAOT/StopwatchAOT/StopwatchAOT.fsproj (in 174 ms).
/usr/local/share/dotnet/sdk/8.0.100-preview.5.23303.2/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(314,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/Users/me/p/f#/aot/StopwatchAOT/StopwatchAOT/StopwatchAOT.fsproj]
  StopwatchAOT -> /Users/me/p/f#/aot/StopwatchAOT/StopwatchAOT/bin/Release/net8.0/osx-x64/StopwatchAOT.dll
  Generating native code
/Users/me/.nuget/packages/fsharp.core/7.0.400-beta.23281.1/lib/netstandard2.1/FSharp.Core.dll : warning IL3053: Assembly 'FSharp.Core' produced AOT analysis warnings. [/Users/me/p/f#/aot/StopwatchAOT/StopwatchAOT/StopwatchAOT.fsproj]
/Users/me/.nuget/packages/fsharp.core/7.0.400-beta.23281.1/lib/netstandard2.1/FSharp.Core.dll : warning IL2104: Assembly 'FSharp.Core' produced trim warnings. For more information see https://aka.ms/dotnet-illink/libraries [/Users/me/p/f#/aot/StopwatchAOT/StopwatchAOT/StopwatchAOT.fsproj]
  StopwatchAOT -> /Users/me/p/f#/aot/StopwatchAOT/StopwatchAOT/bin/Release/net8.0/osx-x64/publish/
Z% ./bin/Release/net8.0/osx-x64/publish/StopwatchAOT
Unhandled Exception: System.NotSupportedException: 'Microsoft.FSharp.Core.PrintfImpl+Specializations`3[System.IO.TextWriter,Microsoft.FSharp.Core.Unit,Microsoft.FSharp.Core.Unit].CaptureFinal1[System.Int32](Microsoft.FSharp.Core.PrintfImpl+Step[])' is missing native code. MethodInfo.MakeGenericMethod() is not compatible with AOT compilation. Inspect and fix AOT related warnings that were generated when the app was published. For more information see https://aka.ms/nativeaot-compatibility
   at System.Reflection.Runtime.MethodInfos.RuntimeNamedMethodInfo`1.GetUncachedMethodInvoker(RuntimeTypeInfo[], MemberInfo) + 0x5c
   at System.Reflection.Runtime.MethodInfos.RuntimeNamedMethodInfo`1.MakeGenericMethod(Type[]) + 0x1c0
   at Microsoft.FSharp.Core.PrintfImpl.FormatParser`4.buildCaptureFunc[a](PrintfImpl.FormatSpecifier, a, Type[], Type, Tuple`5) + 0x24d
   at Microsoft.FSharp.Core.PrintfImpl.FormatParser`4.parseAndCreateFuncFactoryAux(FSharpList`1, String, Type, Int32&) + 0x29d
   at Microsoft.FSharp.Core.PrintfImpl.FormatParser`4.parseAndCreateFunctionFactory() + 0x72
   at Microsoft.FSharp.Core.PrintfImpl.FormatParser`4.GetCurriedPrinterFactory() + 0x25
   at Microsoft.FSharp.Core.PrintfModule.gprintf[a, TState, TResidue, TResult, TPrinter](FSharpFunc`2, PrintfFormat`4) + 0x42
   at Program.timeIt[a](FSharpFunc`2) + 0xbf
   at StopwatchAOT!<BaseAddress>+0x1e044d
Z% 
```

### Configuration

.NET 8.0.100-preview.5.23303.2
Darwin x.local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:51:50 PDT 2023; root:xnu-8796.121.2~5/RELEASE_X86_64 x86_64

Don’t know if config specific

**Comment by MichalStrehovsky** [comment] 2023-06-20 01:03
This is not an issue with Stopwatch - it's an issue in F#'s implementation of printf - it's not compatible with AOT. This is what the compile time warnings are about as well.

F# repo tracks this at dotnet/fsharp#13398 (look for `printf`) - closing as a duplicate of that.

**Closed by MichalStrehovsky** 2023-06-20 01:03 UTC
Labels: untriaged, area-NativeAOT-coreclr
