### ISSUE TITLE
[wasm][aot][tests] Runtime crash on `main`, for `System.Collections.NonGeneric.Tests`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#54288] opened 2021-06-16 18:05 UTC
This was seen twice:
- [Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1185489&view=logs&j=f217f715-90ad-5404-53bd-b93e3b80f465&t=9df76bd4-3041-5537-002b-9e29a53263b9) [Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-da525a2addf8493589/System.Collections.NonGeneric.Tests/console.6b6adeca.log?sv=2019-07-07&se=2021-07-03T22%3A04%3A14Z&sr=c&sp=rl&sig=%2B%2BdctXaI1gz4oH8JvoObn2ytRSNBsy3H0S2VBExFvsI%3D)
- [Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1185545&view=logs&j=f217f715-90ad-5404-53bd-b93e3b80f465) [Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-926584ca113443bd84/System.Collections.NonGeneric.Tests/console.b57f9e39.log?sv=2019-07-07&se=2021-07-03T23%3A58%3A04Z&sr=c&sp=rl&sig=C42N2vki8aGQGXCHlLZFfrZUxjhU1S8nqFnbuus7ocE%3D)
```
Starting:    System.Collections.NonGeneric.Tests.dll

console.error: RuntimeError: memory access out of bounds
console.error: RuntimeError: memory access out of bounds

    at corlib_string_CompareTo_object (<anonymous>:wasm-function[29758]:0x5bf0cd)
    at corlib_aot_wrapper_gsharedvt_out_sig_i4_this_obj (<anonymous>:wasm-function[40765]:0x8fc268)
    at jit_call_cb (<anonymous>:wasm-function[9019]:0x147159)
    at invoke_vi (dotnet.js:11243:25)
    at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[5828]:0xdb44b)
    at do_jit_call (<anonymous>:wasm-function[8979]:0x146413)
    at interp_exec_method (<anonymous>:wasm-function[8920]:0x139795)
    at interp_entry (<anonymous>:wasm-function[8962]:0x145a2a)
    at interp_entry_instance_ret_2 (<anonymous>:wasm-function[9044]:0x147948)
    at corlib_aot_wrapper_gsharedvt_in_sig_u1_this_objobj (<anonymous>:wasm-function[40781]:0x8fc704)
    at xunit_assert_Xunit_Sdk_AssertEqualityComparer_1_T_REF_Equals_T_REF_T_REF (<anonymous>:wasm-function[22770]:0x3ea217)
    at xunit_assert_Xunit_Assert_Equal_T_REF_T_REF_T_REF_System_Collections_Generic_IEqualityComparer_1_T_REF (<anonymous>:wasm-function[22696]:0x3e2802)
    at xunit_assert_Xunit_Assert_Equal_T_REF_T_REF_T_REF (<anonymous>:wasm-function[22695]:0x3e268d)
    at System_Collections_NonGeneric_Tests_System_Collections_Tests_SortedListTests__c__DisplayClass25_0__CopyTob__0_System_Collections_SortedList (<anonymous>:wasm-function[62804]:0x118ff6c)
    at System_Collections_NonGeneric_Tests_wrapper_delegate_invoke_System_Action_1_System_Collections_SortedList_invoke_void_T_System_Collections_SortedList (<anonymous>:wasm-function[63232]:0x11b3bd0)
    at System_Collections_NonGeneric_Tests_System_Collections_Tests_Helpers_PerformActionOnAllSortedListWrappers_System_Collections_SortedList_System_Action_1_System_Collections_SortedList (<anonymous>:wasm-function[61463]:0x10f4a78)
    at System_Collections_NonGeneric_Tests_System_Collections_Tests_SortedListTests_CopyTo_int_int (<anonymous>:wasm-function[61736]:0x1131e2b)
    at corlib_aot_wrapper_gsharedvt_out_sig_void_this_i4i4 (<anonymous>:wasm-function[41029]:0x90639d)
    at jit_call_cb (<anonymous>:wasm-function[9019]:0x147159)
    at invoke_vi (dotnet.js:11243:25)
    at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[5828]:0xdb44b)
    at do_jit_call (<anonymous>:wasm-function[8979]:0x146413)
    at interp_exec_method (<anonymous>:wasm-function[8920]:0x1398d6)
    at interp_runtime_invoke (<anonymous>:wasm-function[8919]:0x1384f6)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[4803]:0xb9d25)
    at do_runtime_invoke (<anonymous>:wasm-function[2163]:0x75f8c)
    at mono_runtime_invoke_checked (<anonymous>:wasm-function[2161]:0x75f37)
    at mono_runtime_try_invoke_array (<anonymous>:wasm-function[2313]:0x7a0e6)
    at mono_runtime_invoke_array_checked (<anonymous>:wasm-function[2317]:0x7a700)
    at ves_icall_InternalInvoke (<anonymous>:wasm-function[1017]:0x55eed)
    at ves_icall_InternalInvoke_raw (<anonymous>:wasm-function[1176]:0x5acc5)
    at do_icall (<anonymous>:wasm-function[9012]:0x146a95)
    at do_icall_wrapper (<anonymous>:wasm-function[8975]:0x145f40)
    at interp_exec_method (<anonymous>:wasm-function[8920]:0x139565)
    at interp_entry (<anonymous>:wasm-function[8962]:0x145a2a)
    at interp_entry_instance_ret_5 (<anonymous>:wasm-function[9047]:0x147a44)
    at corlib_aot_wrapper_gsharedvt_in_sig_obj_this_obji4objobjobj (<anonymous>:wasm-function[42257]:0x91fea8)
    at corlib_System_Reflection_RuntimeMethodInfo_Invoke_object_System_Reflection_BindingFlags_System_Reflection_Binder_object___System_Globalization_CultureInfo (<anonymous>:wasm-function[36003]:0x790abe)
    at corlib_System_Reflection_MethodBase_Invoke_object_object__ (<anonymous>:wasm-function[35888]:0x788bcb)
    at corlib_aot_wrapper_gsharedvt_out_sig_obj_this_objobj (<anonymous>:wasm-function[41060]:0x907113)
    at jit_call_cb (<anonymous>:wasm-function[9019]:0x147176)
    at invoke_vi (dotnet.js:11243:25)
    at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[5828]:0xdb44b)
    at do_jit_call (<anonymous>:wasm-function[8979]:0x146413)
    at interp_exec_method (<anonymous>:wasm-function[8920]:0x1398d6)
    at interp_entry (<anonymous>:wasm-function[8962]:0x145a2a)
    at interp_entry_static_1 (<anonymous>:wasm-function[9052]:0x147be8)
    at corlib_aot_wrapper_gsharedvt_in_sig_void_bii (<anonymous>:wasm-function[41458]:0x90ea4a)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_ExecutionTimer__AggregateAsyncd__4_Xunit_Sdk_ExecutionTimer__AggregateAsyncd__4_ (<anonymous>:wasm-function[21196]:0x39920f)
    at xunit_execution_dotnet_Xunit_Sdk_ExecutionTimer_AggregateAsync_System_Func_1_System_Threading_Tasks_Task (<anonymous>:wasm-function[19426]:0x30a985)
    at corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_obj (<anonymous>:wasm-function[40437]:0x8f661c)
    at jit_call_cb (<anonymous>:wasm-function[9019]:0x147159)
    at invoke_vi (dotnet.js:11243:25)
    at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[5828]:0xdb44b)
    at do_jit_call (<anonymous>:wasm-function[8979]:0x146413)
    at interp_exec_method (<anonymous>:wasm-function[8920]:0x1398d6)
    at interp_entry (<anonymous>:wasm-function[8962]:0x145a2a)
    at interp_entry_static_1 (<anonymous>:wasm-function[9052]:0x147be8)
    at corlib_aot_wrapper_gsharedvt_in_sig_void_bii (<anonymous>:wasm-function[41458]:0x90ea4a)
    at xunit_core_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_ExceptionAggregator__RunAsyncd__9_Xunit_Sdk_ExceptionAggregator__RunAsyncd__9_ (<anonymous>:wasm-function[22473]:0x3d9160)
    at xunit_core_Xunit_Sdk_ExceptionAggregator_RunAsync_System_Func_1_System_Threading_Tasks_Task (<anonymous>:wasm-function[22255]:0x3c50d8)
    at corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_obj (<anonymous>:wasm-function[40437]:0x8f661c)
    at jit_call_cb (<anonymous>:wasm-function[9019]:0x147159)
    at invoke_vi (dotnet.js:11243:25)
    at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[5828]:0xdb44b)
    at do_jit_call (<anonymous>:wasm-function[8979]:0x146413)
    at interp_exec_method (<anonymous>:wasm-function[8920]:0x1398d6)
    at interp_entry (<anonymous>:wasm-function[8962]:0x145a2a)
    at interp_entry_instance_1 (<anonymous>:wasm-function[9034]:0x14760e)
    at corlib_aot_wrapper_gsharedvt_in_sig_void_this_bii (<anonymous>:wasm-function[42100]:0x91c3d2)
    at xunit_execution_dotnet_Xunit_Sdk_TestInvoker_1_TTestCase_REF_InvokeTestMethodAsync_object (<anonymous>:wasm-function[19572]:0x315151)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestInvoker_InvokeTestMethodAsync_object (<anonymous>:wasm-function[19746]:0x3236b5)
    at corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_obj (<anonymous>:wasm-function[40437]:0x8f661c)
    at jit_call_cb (<anonymous>:wasm-function[9019]:0x147159)
    at invoke_vi (dotnet.js:11243:25)
    at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[5828]:0xdb44b)
    at do_jit_call (<anonymous>:wasm-function[8979]:0x146413)
    at interp_exec_method (<anonymous>:wasm-function[8920]:0x139795)
    at interp_entry (<anonymous>:wasm-function[8962]:0x145a2a)
    at interp_entry_static_1 (<anonymous>:wasm-function[9052]:0x147be8)
    at corlib_aot_wrapper_gsharedvt_in_sig_void_bii (<anonymous>:wasm-function[41458]:0x90ea4a)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_ExceptionAggregator__RunAsyncd__10_1_System_Decimal_Xunit_Sdk_ExceptionAggregator__RunAsyncd__10_1_System_Decimal_ (<anonymous>:wasm-function[21630]:0x3a9a32)
    at xunit_execution_dotnet_Xunit_Sdk_ExceptionAggregator_RunAsync_System_Decimal_System_Func_1_System_Threading_Tasks_Task_1_System_Decimal (<anonymous>:wasm-function[21223]:0x39a7e2)
    at xunit_execution_dotnet_Xunit_Sdk_TestInvoker_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[19571]:0x315018)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestRunner_InvokeTestMethodAsync_Xunit_Sdk_ExceptionAggregator (<anonymous>:wasm-function[19759]:0x3244f0)
    at corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_obj (<anonymous>:wasm-function[40437]:0x8f661c)
    at jit_call_cb (<anonymous>:wasm-function[9019]:0x147159)
    at invoke_vi (dotnet.js:11243:25)
    at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[5828]:0xdb44b)
    at do_jit_call (<anonymous>:wasm-function[8979]:0x146413)
    at interp_exec_method (<anonymous>:wasm-function[8920]:0x139795)
    at interp_entry (<anonymous>:wasm-function[8962]:0x145a2a)
    at interp_entry_static_1 (<anonymous>:wasm-function[9052]:0x147be8)
    at corlib_aot_wrapper_gsharedvt_in_sig_void_bii (<anonymous>:wasm-function[41458]:0x90ea4a)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_XunitTestRunner__InvokeTestAsyncd__4_Xunit_Sdk_XunitTestRunner__InvokeTestAsyncd__4_ (<anonymous>:wasm-function[21259]:0x39ba87)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestRunner_InvokeTestAsync_Xunit_Sdk_ExceptionAggregator (<anonymous>:wasm-function[19758]:0x3241b2)
    at corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_obj (<anonymous>:wasm-function[40437]:0x8f661c)
    at jit_call_cb (<anonymous>:wasm-function[9019]:0x147159)
    at invoke_vi (dotnet.js:11243:25)
    at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[5828]:0xdb44b)
    at do_jit_call (<anonymous>:wasm-function[8979]:0x146413)
    at interp_exec_method (<anonymous>:wasm-function[8920]:0x139795)
    at interp_entry (<anonymous>:wasm-function[8962]:0x145a2a)
    at interp_entry_static_1 (<anonymous>:wasm-function[9052]:0x147be8)
    at corlib_aot_wrapper_gsharedvt_in_sig_void_bii (<anonymous>:wasm-function[41458]:0x90ea4a)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_XunitTheoryTestCaseRunner__RunTestAsyncd__11_Xunit_Sdk_XunitTheoryTestCaseRunner__RunTestAsyncd__11_ (<anonymous>:wasm-function[21262]:0x39bb94)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTheoryTestCaseRunner_RunTestAsync (<anonymous>:wasm-function[19766]:0x324dad)
    at corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_ (<anonymous>:wasm-function[40423]:0x8f632d)
    at jit_call_cb (<anonymous>:wasm-function[9019]:0x147141)
    at invoke_vi (dotnet.js:11243:25)
    at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[5828]:0xdb44b)
    at do_jit_call (<anonymous>:wasm-function[8979]:0x146413)
    at interp_exec_method (<anonymous>:wasm-function[8920]:0x139795)
    at interp_entry (<anonymous>:wasm-function[8962]:0x145a2a)
    at interp_entry_static_1 (<anonymous>:wasm-function[9052]:0x147be8)
    at corlib_aot_wrapper_gsharedvt_in_sig_void_bii (<anonymous>:wasm-function[41458]:0x90ea4a)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__1 (<anonymous>:wasm-function[21625]:0x3a9843)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__1 (<anonymous>:wasm-function[21209]:0x399893)
    at xunit_execution_dotnet_Xunit_Sdk_TestCaseRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[19419]:0x309ff5)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTheoryTestCase_RunAsync_Xunit_Abstractions_IMessageSink_Xunit_Sdk_IMessageBus_object___Xunit_Sdk_ExceptionAggregator_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[20017]:0x339f10)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestMethodRunner_RunTestCaseAsync_Xunit_Sdk_IXunitTestCase (<anonymous>:wasm-function[19756]:0x324060)
    at corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_obj (<anonymous>:wasm-function[40437]:0x8f661c)
    at jit_call_cb (<anonymous>:wasm-function[9019]:0x147159)
    at invoke_vi (dotnet.js:11243:25)
    at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[5828]:0xdb44b)
    at do_jit_call (<anonymous>:wasm-function[8979]:0x146413)
    at interp_exec_method (<anonymous>:wasm-function[8920]:0x139795)
    at interp_entry (<anonymous>:wasm-function[8962]:0x145a2a)
    at interp_entry_static_1 (<anonymous>:wasm-function[9052]:0x147be8)
    at corlib_aot_wrapper_gsharedvt_in_sig_void_bii (<anonymous>:wasm-function[41458]:0x90ea4a)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__7 (<anonymous>:wasm-function[21632]:0x3a9afa)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__6 (<anonymous>:wasm-function[21230]:0x39ab5c)
    at xunit_execution_dotnet_Xunit_Sdk_TestMethodRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[19605]:0x316785)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestClassRunner_RunTestMethodAsync_Xunit_Abstractions_ITestMethod_Xunit_Abstractions_IReflectionMethodInfo_System_Collections_Generic_IEnumerable_1_Xunit_Sdk_IXunitTestCase_object__ (<anonymous>:wasm-function[19693]:0x31d84e)
    at corlib_aot_wrapper_gsharedvt_out_sig_obj_this_objobjobjobj (<anonymous>:wasm-function[41218]:0x90b3b9)
    at jit_call_cb (<anonymous>:wasm-function[9019]:0x1471bf)
    at invoke_vi (dotnet.js:11243:25)
    at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[5828]:0xdb44b)
    at do_jit_call (<anonymous>:wasm-function[8979]:0x146413)
    at interp_exec_method (<anonymous>:wasm-function[8920]:0x139795)
    at interp_entry (<anonymous>:wasm-function[8962]:0x145a2a)
    at interp_entry_static_1 (<anonymous>:wasm-function[9052]:0x147be8)
    at corlib_aot_wrapper_gsharedvt_in_sig_void_bii (<anonymous>:wasm-function[41458]:0x90ea4a)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__2 (<anonymous>:wasm-function[21626]:0x3a98a7)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__2 (<anonymous>:wasm-function[21215]:0x39a3c7)
    at xunit_execution_dotnet_Xunit_Sdk_TestClassRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[19510]:0x310ff8)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestCollectionRunner_RunTestClassAsync_Xunit_Abstractions_ITestClass_Xunit_Abstractions_IReflectionTypeInfo_System_Collections_Generic_IEnumerable_1_Xunit_Sdk_IXunitTestCase (<anonymous>:wasm-function[19726]:0x321cc8)
    at corlib_aot_wrapper_gsharedvt_out_sig_obj_this_objobjobj (<anonymous>:wasm-function[41215]:0x90b210)
    at jit_call_cb (<anonymous>:wasm-function[9019]:0x147198)
    at invoke_vi (dotnet.js:11243:25)
    at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[5828]:0xdb44b)
    at do_jit_call (<anonymous>:wasm-function[8979]:0x146413)
    at interp_exec_method (<anonymous>:wasm-function[8920]:0x139795)
    at interp_entry (<anonymous>:wasm-function[8962]:0x145a2a)
    at interp_entry_static_1 (<anonymous>:wasm-function[9052]:0x147be8)
    at corlib_aot_wrapper_gsharedvt_in_sig_void_bii (<anonymous>:wasm-function[41458]:0x90ea4a)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__4 (<anonymous>:wasm-function[21628]:0x3a996f)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__4 (<anonymous>:wasm-function[21220]:0x39a5f8)
    at xunit_execution_dotnet_Xunit_Sdk_TestCollectionRunner_1_TTestCase_REF_RunAsync (<anonymous>:wasm-function[19538]:0x312ae3)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestAssemblyRunner_RunTestCollectionAsync_Xunit_Sdk_IMessageBus_Xunit_Abstractions_ITestCollection_System_Collections_Generic_IEnumerable_1_Xunit_Sdk_IXunitTestCase_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[19649]:0x318e29)
    at corlib_aot_wrapper_gsharedvt_out_sig_obj_this_objobjobjobj (<anonymous>:wasm-function[41218]:0x90b3b9)
    at jit_call_cb (<anonymous>:wasm-function[9019]:0x1471bf)
    at invoke_vi (dotnet.js:11243:25)
    at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[5828]:0xdb44b)
    at do_jit_call (<anonymous>:wasm-function[8979]:0x146413)
    at interp_exec_method (<anonymous>:wasm-function[8920]:0x139795)
    at interp_entry (<anonymous>:wasm-function[8962]:0x145a2a)
    at interp_entry_static_1 (<anonymous>:wasm-function[9052]:0x147be8)
    at corlib_aot_wrapper_gsharedvt_in_sig_void_bii (<anonymous>:wasm-function[41458]:0x90ea4a)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_INST_TStateMachine_INST__0 (<anonymous>:wasm-function[21623]:0x3a9748)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_TResult_REF_Start_TStateMachine_INST_TStateMachine_INST__0 (<anonymous>:wasm-function[21202]:0x3994ce)
    at xunit_execution_dotnet_Xunit_Sdk_TestAssemblyRunner_1_TTestCase_REF_RunTestCollectionsAsync_Xunit_Sdk_IMessageBus_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[19464]:0x30dd41)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestAssemblyRunner__n__0_Xunit_Sdk_IMessageBus_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[19651]:0x319072)
    at corlib_aot_wrapper_gsharedvt_out_sig_obj_this_objobj (<anonymous>:wasm-function[41060]:0x907113)
    at jit_call_cb (<anonymous>:wasm-function[9019]:0x147176)
    at invoke_vi (dotnet.js:11243:25)
    at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[5828]:0xdb44b)
    at do_jit_call (<anonymous>:wasm-function[8979]:0x146413)
    at interp_exec_method (<anonymous>:wasm-function[8920]:0x1398d6)
    at interp_entry (<anonymous>:wasm-function[8962]:0x145a2a)
    at interp_entry_static_1 (<anonymous>:wasm-function[9052]:0x147be8)
    at corlib_aot_wrapper_gsharedvt_in_sig_void_bii (<anonymous>:wasm-function[41458]:0x90ea4a)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_XunitTestAssemblyRunner__RunTestCollectionsAsyncd__14_Xunit_Sdk_XunitTestAssemblyRunner__RunTestCollectionsAsyncd__14_ (<anonymous>:wasm-function[21236]:0x39ae08)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestAssemblyRunner_RunTestCollectionsAsync_Xunit_Sdk_IMessageBus_System_Threading_CancellationTokenSource (<anonymous>:wasm-function[19648]:0x318ba4)
    at corlib_aot_wrapper_gsharedvt_out_sig_obj_this_objobj (<anonymous>:wasm-function[41060]:0x907113)
    at jit_call_cb (<anonymous>:wasm-function[9019]:0x147176)
    at invoke_vi (dotnet.js:11243:25)
    at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[5828]:0xdb44b)
    at do_jit_call (<anonymous>:wasm-function[8979]:0x146413)
    at interp_exec_method (<anonymous>:wasm-function[8920]:0x139795)
    at interp_entry (<anonymous>:wasm-function[8962]:0x145a2a)
    at interp_entry_static_1 (<anonymous>:wasm-function[9052]:0x147be8)
    at corlib_aot_wrapper_gsharedvt_in_sig_void_bii (<anonymous>:wasm-function[41458]:0x90ea4a)
    at xunit_execution_dotnet_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Xunit_Sdk_XunitTestFrameworkExecutor__RunTestCasesd__8_Xunit_Sdk_XunitTestFrameworkExecutor__RunTestCasesd__8_ (<anonymous>:wasm-function[21297]:0x39c88f)
    at xunit_execution_dotnet_Xunit_Sdk_XunitTestFrameworkExecutor_RunTestCases_System_Collections_Generic_IEnumerable_1_Xunit_Sdk_IXunitTestCase_Xunit_Abstractions_IMessageSink_Xunit_Abstractions_ITestFrameworkExecutionOptions (<anonymous>:wasm-function[20012]:0x339835)
    at xunit_execution_dotnet_Xunit_Sdk_TestFrameworkExecutor_1_TTestCase_REF_RunTests_System_Collections_Generic_IEnumerable_1_Xunit_Abstractions_ITestCase_Xunit_Abstractions_IMessageSink_Xunit_Abstractions_ITestFrameworkExecutionOptions (<anonymous>:wasm-function[19884]:0x32def8)
    at xunit_runner_utility_netcoreapp10_Xunit_Xunit2_RunTests_System_Collections_Generic_IEnumerable_1_Xunit_Abstractions_ITestCase_Xunit_Abstractions_IMessageSink_Xunit_Abstractions_ITestFrameworkExecutionOptions (<anonymous>:wasm-function[15884]:0x2078db)
    at xunit_runner_utility_netcoreapp10_TestFrameworkExtensions_RunTests_Xunit_Abstractions_ITestFrameworkExecutor_System_Collections_Generic_IEnumerable_1_Xunit_Abstractions_ITestCase_Xunit_IMessageSinkWithTypes_Xunit_Abstractions_ITestFrameworkExecutionOptions (<anonymous>:wasm-function[15613]:0x1f9a51)
    at corlib_aot_wrapper_gsharedvt_out_sig_void_objobjobjobj (<anonymous>:wasm-function[42083]:0x91bde0)
    at jit_call_cb (<anonymous>:wasm-function[9019]:0x147176)
    at invoke_vi (dotnet.js:11243:25)
    at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[5828]:0xdb44b)
    at do_jit_call (<anonymous>:wasm-function[8979]:0x146413)
    at interp_exec_method (<anonymous>:wasm-function[8920]:0x1398d6)
    at interp_entry (<anonymous>:wasm-function[8962]:0x145a2a)
    at interp_entry_static_1 (<anonymous>:wasm-function[9052]:0x147be8)
    at corlib_aot_wrapper_gsharedvt_in_sig_void_bii (<anonymous>:wasm-function[41458]:0x90ea4a)
    at Microsoft_DotNet_XHarness_TestRunners_Xunit_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner__Rund__0_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner__Rund__0_ (<anonymous>:wasm-function[65008]:0x120894c)
    at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_ThreadlessXunitTestRunner_Run_string_bool_Xunit_XunitFilters (<anonymous>:wasm-function[64867]:0x11fcfae)
    at Microsoft_DotNet_XHarness_TestRunners_Xunit_aot_wrapper_gsharedvt_out_sig_obj_obju1obj (<anonymous>:wasm-function[65009]:0x120899b)
    at jit_call_cb (<anonymous>:wasm-function[9019]:0x147176)
    at invoke_vi (dotnet.js:11243:25)
    at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[5828]:0xdb44b)
    at do_jit_call (<anonymous>:wasm-function[8979]:0x146413)
    at interp_exec_method (<anonymous>:wasm-function[8920]:0x1398d6)
    at interp_entry (<anonymous>:wasm-function[8962]:0x145a2a)
    at interp_entry_static_1 (<anonymous>:wasm-function[9052]:0x147be8)
    at corlib_aot_wrapper_gsharedvt_in_sig_void_bii (<anonymous>:wasm-function[41458]:0x90ea4a)
    at Microsoft_DotNet_XHarness_TestRunners_Xunit_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint__Rund__24_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint__Rund__24_ (<anonymous>:wasm-function[65055]:0x1209645)
    at Microsoft_DotNet_XHarness_TestRunners_Xunit_Microsoft_DotNet_XHarness_TestRunners_Xunit_WasmApplicationEntryPoint_Run (<anonymous>:wasm-function[64898]:0x11feab3)
    at corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_this_ (<anonymous>:wasm-function[40423]:0x8f632d)
    at jit_call_cb (<anonymous>:wasm-function[9019]:0x147141)
    at invoke_vi (dotnet.js:11243:25)
    at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[5828]:0xdb44b)
    at do_jit_call (<anonymous>:wasm-function[8979]:0x146413)
    at interp_exec_method (<anonymous>:wasm-function[8920]:0x1398d6)
    at interp_entry (<anonymous>:wasm-function[8962]:0x145a2a)
    at interp_entry_static_1 (<anonymous>:wasm-function[9052]:0x147be8)
    at corlib_aot_wrapper_gsharedvt_in_sig_void_bii (<anonymous>:wasm-function[41458]:0x90ea4a)
    at WasmTestRunner_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_SimpleWasmTestRunner__Maind__0_SimpleWasmTestRunner__Maind__0_ (<anonymous>:wasm-function[23312]:0x40e689)
    at WasmTestRunner_SimpleWasmTestRunner_Main_string__ (<anonymous>:wasm-function[23264]:0x40a702)
    at corlib_aot_wrapper_gsharedvt_out_sig_pinvoke_obj_obj (<anonymous>:wasm-function[40421]:0x8f6279)
    at jit_call_cb (<anonymous>:wasm-function[9019]:0x147141)
    at invoke_vi (dotnet.js:11243:25)
    at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[5828]:0xdb44b)
    at do_jit_call (<anonymous>:wasm-function[8979]:0x146413)
    at interp_exec_method (<anonymous>:wasm-function[8920]:0x1398d6)
    at interp_runtime_invoke (<anonymous>:wasm-function[8919]:0x1384f6)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[4803]:0xb9d25)
    at do_runtime_invoke (<anonymous>:wasm-function[2163]:0x75f8c)
    at mono_runtime_try_invoke (<anonymous>:wasm-function[2172]:0x76586)
    at mono_runtime_invoke (<anonymous>:wasm-function[2247]:0x785b3)
    at mono_wasm_invoke_method (<anonymous>:wasm-function[65274]:0x120d088)
    at Object.Module._mono_wasm_invoke_method [as invoke_method] (dotnet.js:10641:117)
    at Object._call_method_with_converted_args (dotnet.js:8902:30)
    at Object.call_method (dotnet.js:8862:18)
    at dotnet.js:9121:29
    at Object.call_assembly_entry_point (dotnet.js:9128:66)
    at Object.init (runtime.js:355:24)
    at Object.config.loaded_cb (runtime.js:241:8)
    at Object._finalize_startup (dotnet.js:7076:11)
    at onPendingRequestComplete (dotnet.js:7113:14)
    at processFetchResponseBuffer (dotnet.js:7128:8)

Process v8 exited with 1
```

cc @vargaz

**Comment by vargaz** [comment] 2021-07-05 21:31
Can't reproduce this locally.

**Comment by vargaz** [comment] 2021-07-14 13:40
Will be fixed by https://github.com/dotnet/runtime/pull/55598

**Closed** 2021-07-14 13:45 UTC
Labels: arch-wasm, area-Codegen-AOT-mono, wasm-aot-test
