### ISSUE TITLE
.NET 6.0.2

### ISSUE THREAD

**Issue by czdietrich** [dotnet/runtime#64529] opened 2022-01-31 11:42 UTC
Hi, I just wanted to ask kindly whether there is an expected timeframe for the next service pack of .NET (SDK)? I know there are no specific dates for releases but usually it's about once a month and the last one (6.0.1) was on Dec. 14th. I would not explicitly ask but .NET 6 introduced a hand full of regressions that are already fixed but not yet released which is a show stopper for the release of our application suite. So is there anything blocking the next release or is it already in the pipeline?

Best regards
Michael

**Comment by danmoseley** [comment] 2022-01-31 12:08
Hello @czdietrich . It is expected to ship in the 2nd Tuesday of February. We ship almost every month, but skip January because of the holidays.

Are there any issues you are encountering that you have not confirmed are fixed in it?

**Comment by czdietrich** [comment] 2022-01-31 12:25
Hi @danmoseley, thank you for the quick response. 
The both regressions I am referring to are a [bug that created broken installers](https://github.com/dotnet/runtime/pull/62908) that is already merged and a [bug in WPF that could lead to crashes](https://github.com/dotnet/wpf/pull/6002) that is currently about to be merged into .NET 6.0 servicing branch.

So, if these both are fixed then we are fine with our release. :)

**Comment by danmoseley** [comment] 2022-01-31 12:34
The 6.0.2 build is apart prepared , so that WPF fix would unfortunately not be in it. I am not familiar with it - perhaps there is a workaround? I am sorry to hear it is delaying your release.

**Closed** 2022-01-31 16:32 UTC
Labels: question, area-Meta, untriaged

**Comment by czdietrich** [comment] 2022-02-02 10:13
Thank you for clarification. That the WPF bug won't be part of the upcoming .NET 6 servicing release is very unfortunate, since there seems to be no easy workaround for it, but waiting for a following servicing release is not an option, so we simply have to take it how it is at the moment.
