### ISSUE TITLE
ARM64: Fuzzlyn example Debug outputs `97` and Release outputs `0`

### ISSUE THREAD

**Issue by TIHan** [dotnet/runtime#105414] opened 2024-07-24 18:03 UTC
https://dev.azure.com/dnceng-public/public/_build/results?buildId=749360&view=logs&j=1c4513f5-15be-5f8c-3c15-7e4daaa8a0df&t=87ceac4d-3cf3-5913-4346-e944a7837833

```
2024-07-21T19:23:48.5903900Z ##[section]Starting: Summarize (osx arm64)
2024-07-21T19:23:48.5914470Z ==============================================================================
2024-07-21T19:23:48.5914680Z Task         : Command line
2024-07-21T19:23:48.5914770Z Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
2024-07-21T19:23:48.5914970Z Version      : 2.237.1
2024-07-21T19:23:48.5915060Z Author       : Microsoft Corporation
2024-07-21T19:23:48.5915170Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
2024-07-21T19:23:48.5915350Z ==============================================================================
2024-07-21T19:23:48.7806710Z Generating script.
2024-07-21T19:23:48.7821140Z Script contents:
2024-07-21T19:23:48.7822660Z /Users/runner/work/1/s/venv/bin/python3 /Users/runner/work/1/s/src/coreclr/scripts/fuzzlyn_summarize.py -issues_directory /Users/runner/work/1/s/artifacts/issues/ -arch arm64 -platform osx -build_config Checked
2024-07-21T19:23:48.7823570Z ========================== Starting Command Output ===========================
2024-07-21T19:23:48.7845810Z [command]/bin/bash --noprofile --norc /Users/runner/work/_temp/80783a33-9bfc-423b-bac5-7a3f73bcf896.sh
2024-07-21T19:23:49.1755210Z # General information about run
2024-07-21T19:23:49.1755530Z * Platform: osx
2024-07-21T19:23:49.1755730Z * Architecture: arm64
2024-07-21T19:23:49.1756200Z * Build config: Checked
2024-07-21T19:23:49.1756440Z * Total programs generated: 635149
2024-07-21T19:23:49.1756670Z * Number of examples found: 1
2024-07-21T19:23:49.1756950Z * Number of known errors hit: 0
2024-07-21T19:23:49.1757060Z 
2024-07-21T19:23:49.1757840Z # 1 reduced examples are available
2024-07-21T19:23:49.1758440Z ```csharp
2024-07-21T19:23:49.1792760Z // Generated by Fuzzlyn v1.6 on 2024-07-21 18:56:29
2024-07-21T19:23:49.1793250Z // Run on Arm64 MacOS
2024-07-21T19:23:49.1793520Z // Seed: 2890024859390261003
2024-07-21T19:23:49.1793810Z // Reduced from 643.3 KiB to 1.2 KiB in 00:04:09
2024-07-21T19:23:49.1794190Z // Debug: Outputs 97
2024-07-21T19:23:49.1794420Z // Release: Outputs 0
2024-07-21T19:23:49.1794630Z using System.Runtime.CompilerServices;
2024-07-21T19:23:49.1794780Z 
2024-07-21T19:23:49.1794940Z public struct S0
2024-07-21T19:23:49.1795130Z {
2024-07-21T19:23:49.1795290Z     public ulong F0;
2024-07-21T19:23:49.1795480Z     public long F1;
2024-07-21T19:23:49.1796160Z     public ulong F2;
2024-07-21T19:23:49.1796350Z     public sbyte F3;
2024-07-21T19:23:49.1796530Z     public int F4;
2024-07-21T19:23:49.1796700Z     public sbyte F5;
2024-07-21T19:23:49.1796910Z     public short F6;
2024-07-21T19:23:49.1797090Z     public byte F7;
2024-07-21T19:23:49.1797270Z     public int F8;
2024-07-21T19:23:49.1797480Z     public S0(ulong f2): this()
2024-07-21T19:23:49.1797650Z     {
2024-07-21T19:23:49.1797860Z         F2 = f2;
2024-07-21T19:23:49.1798020Z     }
2024-07-21T19:23:49.1798160Z }
2024-07-21T19:23:49.1798220Z 
2024-07-21T19:23:49.1798410Z public struct S2
2024-07-21T19:23:49.1798580Z {
2024-07-21T19:23:49.1798740Z     public int F0;
2024-07-21T19:23:49.1798920Z     public uint F1;
2024-07-21T19:23:49.1799100Z     public long F2;
2024-07-21T19:23:49.1799460Z     public S0 F3;
2024-07-21T19:23:49.1799820Z     public ulong F4;
2024-07-21T19:23:49.1800190Z     public S0 F5;
2024-07-21T19:23:49.1800580Z     public byte F6;
2024-07-21T19:23:49.1800890Z     public byte F7;
2024-07-21T19:23:49.1801290Z     public bool F8;
2024-07-21T19:23:49.1801730Z     public uint F9;
2024-07-21T19:23:49.1802120Z     public S2(S0 f3): this()
2024-07-21T19:23:49.1802560Z     {
2024-07-21T19:23:49.1802890Z         F3 = f3;
2024-07-21T19:23:49.1803230Z     }
2024-07-21T19:23:49.1803570Z }
2024-07-21T19:23:49.1803710Z 
2024-07-21T19:23:49.1804050Z public struct S3
2024-07-21T19:23:49.1804410Z {
2024-07-21T19:23:49.1804830Z     public long F0;
2024-07-21T19:23:49.1805210Z     public ulong F1;
2024-07-21T19:23:49.1805610Z     public long F2;
2024-07-21T19:23:49.1805980Z     public ushort F3;
2024-07-21T19:23:49.1807370Z     public ushort F4;
2024-07-21T19:23:49.1808060Z     public long F5;
2024-07-21T19:23:49.1808770Z     public ushort F6;
2024-07-21T19:23:49.1809140Z     public short F7;
2024-07-21T19:23:49.1809470Z     public S2 F8;
2024-07-21T19:23:49.1810100Z     public ushort F9;
2024-07-21T19:23:49.1810390Z     public S3(S2 f8): this()
2024-07-21T19:23:49.1810800Z     {
2024-07-21T19:23:49.1811170Z         F8 = f8;
2024-07-21T19:23:49.1811400Z     }
2024-07-21T19:23:49.1811590Z }
2024-07-21T19:23:49.1811680Z 
2024-07-21T19:23:49.1812140Z public class Program
2024-07-21T19:23:49.1812370Z {
2024-07-21T19:23:49.1812720Z     public static S3 s_6 = new S3(new S2(new S0(8110248874075086321UL)));
2024-07-21T19:23:49.1813260Z     public static void Main()
2024-07-21T19:23:49.1813590Z     {
2024-07-21T19:23:49.1814180Z         s_6.F8.F3 = Unsafe.ReadUnaligned<S0>(ref Unsafe.As<uint, byte>(ref s_6.F8.F1));
2024-07-21T19:23:49.1814870Z         System.Console.WriteLine(s_6.F8.F3.F5);
2024-07-21T19:23:49.1815180Z     }
2024-07-21T19:23:49.1815400Z }
2024-07-21T19:23:49.1815690Z ```
2024-07-21T19:23:49.1815800Z 
2024-07-21T19:23:49.1816020Z # Run summaries per partition
2024-07-21T19:23:49.1816660Z |Partition|# Programs generated|# Examples found|# Examples with known errors|Run time|Degree of parallelism|
2024-07-21T19:23:49.1817460Z |---|---|---|---|---|---|
2024-07-21T19:23:49.1817960Z |Partition0|162213|0|0|03:00:11.3941520|8|
2024-07-21T19:23:49.1818460Z |Partition1|160933|0|0|03:00:00.5086924|8|
2024-07-21T19:23:49.1818830Z |Partition2|160226|1|0|03:00:01.5699280|8|
2024-07-21T19:23:49.1819360Z |Partition3|151777|0|0|03:00:00.8918309|8|
2024-07-21T19:23:49.1819530Z 
2024-07-21T19:23:49.1819740Z 
2024-07-21T19:23:49.1924100Z ##[error]Bash exited with code '255'.
2024-07-21T19:23:49.1944950Z ##[section]Finishing: Summarize (osx arm64)
```

**Comment by jakobbotsch** [comment] 2024-07-24 18:21
This is a duplicate of #7539

**Closed by jakobbotsch** 2024-07-24 18:21 UTC
Labels: bug, arch-arm64, os-mac-os-x, area-CodeGen-coreclr, untriaged
