### ISSUE TITLE
[API Proposal]: Make HttpClient.Send() available on .NET Standard 2.0

### ISSUE THREAD

**Issue by Epic-Santiago** [dotnet/runtime#91810] opened 2023-09-08 18:35 UTC
### Background and motivation

There are many scenarios where doing async is just not possible. For example in large legacy code bases. To support such scenarios, HttpClient.Send() was added to .NET 5. However, scenarios where async code is not an option are more prevalent on older .NET Framework code bases than on newer .NET code bases. The lack of this method leads to at best, a plethora of workarounds (see https://stackoverflow.com/questions/53529061/whats-the-right-way-to-use-httpclient-synchronously) and at worst, deadlocks. The only two options are sync-over-async (deadocks) or `WebRequest` (deprecated). Therefore there is no good option on .NET Standard 2.0/.NET Framework.

The lack of parity in the System.Net.Http NuGet package depending on the platform is also surprising to the user.

### API Proposal

```csharp
namespace System.Net.Http
{
    public partial class HttpClient
    {
        public HttpResponseMessage Send(HttpRequestMessage request)
        {
        }
    }
}
```

### API Usage

```csharp
var client = new HttpClient();
var message = new HttpRequestMessage();
client.Send(message);
```

### Alternative Designs

Asking to bring an existing API to another platform. No alternative design available.

### Risks

New API so there should be no risk of affecting existing code.

**Comment by MihaZupan** [comment] 2023-09-08 18:45
`WebRequest` is okay to use on .NET Framework - in fact, HttpClient is built on top of it there.

The API on its own is simple, e.g. you can polyfill it with `SendAsync().GetAwaiter().GetResult()`.
The difficult part is actually implementing it in a way that flows the information about whether to use sync vs. async I/O all the way down the stack to the network calls, and we currently have no plans to backport such functionality.

**Comment by Epic-Santiago** [comment] 2023-09-08 18:49
`SendAsync().GetAwaiter().GetResult()` is what we are doing. But we've been experiencing deadlocks. That's why we created this issue.

**Comment by WeihanLi** [comment] 2023-09-11 10:40
Would `SendAsync().ConfigureAwait(false).GetAwaiter().GetResult()` help?

**Comment by Epic-Santiago** [comment] 2023-09-11 15:21
> Would `SendAsync().ConfigureAwait(false).GetAwaiter().GetResult()` help?

It would not. ConfigureAwait(false) is implicit when doing GetAwaiter().GetResult().

**Comment by wfurt** [comment] 2023-09-11 19:23
NET Standard 2.0 ship have sailed long time ago. I don't think there is possibility to crack that open. 
While the `WebRequest` is obsolete it may be suitable for legacy apps and it is using `HttpClient` under the cover anyway. 

If you post simple runable repro @Epic-Santiago we may be able to figure out what is happing. I feel that recommendation from @MihaZupan should just work e.g. there may be some other problem.

**Comment by Epic-Santiago** [comment] 2023-09-11 19:59
Thank you for the response @wfurt. I do understand that netstandard is set in stone by now. But my hope is that since HttpClient is part of a NuGet package (System.Net.Http) rather than part of .NET Standard itself, there may be an opportunity. For example, adding Send() as an extension method in the package without changing HttpClient itself or something along those lines.

As for repro, we're working on it. We've narrowed it down to having automatic decompression enabled (`AutomaticDecompression = DecompressionMethods.GZip`). My hypothesis is that when we do this, both the send and decompression are happening within the sync-to-async thus making that shaky transition larger. Our preliminary findings are that setting `AutomaticDecompression = DecompressionMethods.None` and doing the decompression ourselves appears to step around the foot gun.

Even with the understanding that investment is focused on .NET and not .NET Framework, this is not a good experience and it could be made better.

P.S.: Now that we may have pointed the finger to sync-over-async with `AutomaticDecompression`, perhaps this should be reported as a bug rather than an API suggestion? `AutomaticDecompression` shouldn't lead to deadlocks.

**Comment by wfurt** [comment] 2023-09-11 20:34
If we get repro we can investigate and route it properly. I don't see reason why decompression would need any `async` but that is not area of my expertise. (also it could be just timing) 

And I agree about the experience. However, there are practical limits and resource constrains so we cannot always do everything we want to.

**Comment by karelz** [comment] 2023-09-15 17:58
@Epic-Santiago, thanks for your report! Here are some answers:

> ... there is no good option on .NET Standard 2.0/.NET Framework.

As you found out, there are 2 options for synchronous Networking stack in .NET:
- [`HttpClient.Send`](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.send)
    - Available on: .NET 5+
    - Limitations: No HTTP/2+ support, no support for certain custom `HttpContent` and `HttpMessageHandler`, and overall worse perf than async counterparts.
- [`WebRequest`](https://learn.microsoft.com/en-us/dotnet/api/system.net.webrequest), which is obsolete for **new development**
    - Available on:
        - .NET Framework
        - .NET (Core) for migration from .NET Framework - with **additional** limitations (see below)
    - Limitations: No HTTP/2+ support, and overall worse perf than async counterparts.
    - **Additional** limitations on .NET (Core): Some `WebRequest`/`ServicePoint` APIs are no-op as they were hard/impossible to implement prior to .NET 5. Most of the hardship was lifted in .NET 5 by introduction of [`HttpClient.Send`](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.send) and [`SocketsHttpHandler.ConnectCallback`](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.connectcallback) which enabled us to implement much more. However, we didn't have strong customer demand, so it didn't happen yet. However, it is something we are willing to revisit and consider for servicing of older supported versions (at the moment .NET 6.0, .NET 7.0, and .NET 8.0) - no promise here, but I think we can make strong enough case for migration scenarios from .NET Framework if needed.
    - Note: `WebRequest` is considered obsolete mainly due to its global API model which does not allow for easy isolation between components in the process. (At least I think that was the main reason why `HttpClient` was introduced in .NET Framework 4.5)

Scenarios where you cannot use async are typically legacy apps / libraries limited by long-existing code base on .NET Framework, where switching to async is huge undertaking. Such scenarios are NOT a new development, therefore the obsoletion of `(Http)WebRequest` does not apply there. You should feel free to continue using the API in those scenarios.

Regarding .NET Standard 2.0 support - there are 2 main reasons to use it:
1. **Larger migrations** from .NET Framework to .NET (Core) - break the migration into stages by compiling components against .NET Standard 2.0 in first stage, and then test and/or run components on .NET Core in second phase.
    - As mentioned above, in such scenarios using `WebRequest` APIs on .NET (Core) is valid use case - migration to .NET (Core) from .NET Framework. However, we would expect afterwards migration to modern networking API `HttpClient` and migration to async APIs (in either order) to benefit the modern capabilities and performance wins, which is typically the key point of migration to .NET (Core).
2. **Modern libraries** target .NET Standard 2.0 to be available for both modern and legacy applications.
    - If the library needs to use sync networking APIs (e.g. because it exposes sync APIs to its users, like some Azure SDKs), we recommend multi-targeting - use `HttpClient.Send` on .NET (Core) and `WebRequest` on .NET Framework.

> The lack of parity in the System.Net.Http NuGet package depending on the platform is also surprising to the user.

System.Net.Http NuGet shouldn't have ever existed as a standalone NuGet package. We regret it until today. Originally it was created to deliver faster innovation to .NET Framework out of band (especially via [WinHttpHandler](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.winhttphandler) which supported also HTTP/2) and then it bit us. We realized we have to roll back all its value and make the System.Net.Http NuGet package just forwarder into the underlying .NET platform. You can see some of the complicated history in #18280 and https://github.com/dotnet/runtime/issues/20777#issuecomment-338418610.

> Asking to bring an existing API to another platform. No alternative design available.

Such change would have to happen in .NET Framework, not in NuGet package as explained above. And for that to be useful, we would need a time machine to travel back to .NET Framework 4.6.2, or at least 4.7 and add it there :(.

I hope it sheds some light on the problematic and I hope it is at least a little bit useful.

**Comment by karelz** [comment] 2023-09-15 18:12
> But my hope is that since HttpClient is part of a NuGet package (System.Net.Http) rather than part of .NET Standard itself, there may be an opportunity. For example, adding Send() as an extension method in the package without changing HttpClient itself or something along those lines.

As explained above, `HttpClient` is in fact part of the .NET Platform, not part of a NuGet package -- that is just reference assembly.
We are not aware of any way to extend the existing class in .NET Framework.

> Now that we may have pointed the finger to sync-over-async with `AutomaticDecompression`, perhaps this should be reported as a bug rather than an API suggestion? `AutomaticDecompression` shouldn't lead to deadlocks.

The problem is that what is used here is `HttpClient` in .NET Framework. We would have to go and harden it for sync-over-async scenarios. That is rather large cost and it is unclear if it is even possible.
Applications have a path forward by following the earlier mentioned migration scenario with `WebRequest`. Libraries would not be able to benefit from this anyway, because they would require latest patch of .NET Framework, which is not easily doable (can't be expressed via dependencies) and not all users can make that upgrade that quickly anyway.

I don't think it makes sense to dig deeper into the sync-over-async path here.

**Comment by Epic-Santiago** [comment] 2023-09-16 00:10
Thank you for the detailed response, @karelz. I appreciate you taking the time to research the issue. While this is of course not the outcome I was hoping for, it sounds like we've taken it as far as it can go. Feel free to close the issue unless there is more investigation to be done.

**Comment by karelz** [comment] 2023-09-16 10:56
No more investigation we can think of.
If you are in the camp of migrating larger code base to .NET Framework and beefed up `WebRequest` on .NET (Core) would be valuable to you, please give us heads up.

Closing as everything is answered.

**Closed by karelz** 2023-09-16 10:56 UTC
Labels: api-suggestion, area-System.Net, untriaged
