### ISSUE TITLE
Infinite recursion in System.Private.CoreLib

### ISSUE THREAD

**Issue by TheArcaneBrony** [dotnet/runtime#53833] opened 2021-06-07 20:11 UTC
### Description
Infinite recursion exception in System.Private.CoreLib when directory is not found

### Configuration

.NET Version: 6.0.100-preview.4.21255.9
OS: Windows 10, build 21390
Arch: x64
Specific to this configuration: I don't think so
### Regression?

Did it work in a previous build of .NET Core: I was able to reproduce this issue in .NET 5.0.200-preview.21077.7, however the behavior was more expected (throwing a System.IO.IOException)
### Other information

Pointers: FileSystemEnumerator.Windows.cs:113 (where it jumps to under my debugger when throwing)
Stack trace (.NET 6 Preview 1 + .NET 6 Preview 4): [Pastery](https://www.pastery.net/hejezr+usvxvh/#usvxvh)
.NET 6 Preview 4:
```cs
Unhandled exception. Process terminated. Infinite recursion during resource look
up within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib,
or potentially in certain extensibility points such as assembly resolve events o
r CultureInfo names.  Resource name: Exception_EndOfInnerExceptionStack
   at System.Environment.FailFast(System.String)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String)
   at System.SR.get_Exception_EndOfInnerExceptionStack()
   at System.Exception.ToString()
   at System.IO.Enumeration.FileSystemEnumerator`1[[System.__Canon, System.Priva
te.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].
CreateDirectoryHandle(System.String, Boolean)
   at System.IO.Enumeration.FileSystemEnumerator`1[[System.__Canon, System.Priva
te.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].
Init()
   at System.IO.Enumeration.FileSystemEnumerator`1[[System.__Canon, System.Priva
te.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].
.ctor(System.String, Boolean, System.IO.EnumerationOptions)
   at System.IO.Enumeration.FileSystemEnumerable`1+DelegateEnumerator[[System.__
Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=
7cec85d7bea7798e]]..ctor(System.IO.Enumeration.FileSystemEnumerable`1<System.__C
anon>, Boolean)
   at System.IO.Enumeration.FileSystemEnumerable`1[[System.__Canon, System.Priva
te.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].
.ctor(System.String, FindTransform<System.__Canon>, System.IO.EnumerationOptions
, Boolean)
   at System.IO.Enumeration.FileSystemEnumerable`1[[System.__Canon, System.Priva
te.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].
.ctor(System.String, FindTransform<System.__Canon>, System.IO.EnumerationOptions
)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(System.String,
 System.String, System.IO.EnumerationOptions)
   at System.IO.Directory.InternalEnumeratePaths(System.String, System.String, S
ystem.IO.SearchTarget, System.IO.EnumerationOptions)
   at System.IO.Directory.GetFiles(System.String, System.String, System.IO.Enume
rationOptions)
   at System.IO.Directory.GetFiles(System.String)
   at EasyDiskCleaner.Program.ScanDir(System.String, System.String[])
   at EasyDiskCleaner.Program.ScanDir(System.String)
   at EasyDiskCleaner.Program+<>c__DisplayClass5_1.<Main>b__12()
   at System.Threading.Thread+StartHelper.RunWorker()
   at System.Threading.Thread+StartHelper.Run()
   at System.Threading.Thread.StartCallback()```

**Comment by GrabYourPitchforks** [comment] 2021-06-07 20:36
Moving to _System.Runtime_. I think in the past this has been caused by mismatched binaries in the SDK folder; e.g., a JIT build for one architecture and a CoreLib built for a different architecture. But the low-level runtime folks can confirm.

**Comment by tannergooding** [comment] 2021-06-07 20:48
CC. @tarekgh, here is another case where the infinite recursion exception is making it difficult to see what the actual failure is.

I'm still in favor of doing something so we never see this resource lookup failure for the framework itself.

**Comment by tarekgh** [comment] 2021-06-07 21:05
CC @jkotas

> I'm still in favor of doing something so we never see this resource lookup failure for the framework itself.

I am not objecting but what you are suggesting here? as I mentioned in other places, reaching this stage means there is something seriously wrong and not necessary it is even part of the stack. This one looks more related to the debugger. 
Are you suggesting making the resources just return some fake resource value and let the execution continue to crash in some other random places? 


CC @joperezr the owner of resources area.

**Comment by tannergooding** [comment] 2021-06-07 21:10
> Are you suggesting making the resources just return some fake resource value and let the execution continue to crash in some other random places?

Most of the time I've seen this failure its part of a lookup to throw the real exception. When we are doing that and the lookup fails, this completely masks the actual failure and makes it difficult to diagnose without actually attaching a debugger.

**Comment by jkotas** [comment] 2021-06-07 21:23
When this fails, there is something seriously wrong with the process health. I think the current behavior is correct - we should stop as soon as possible when this fails. It gives us better chance to get a dump that can reveal what is wrong with process.

**Comment by tarekgh** [comment] 2021-06-07 21:24
Also, don't the stack already pointing at https://github.com/dotnet/runtime/blob/44f050acc0f7791d6cd7ac772945444912bcf299/src/libraries/System.Private.CoreLib/src/System/IO/Enumeration/FileSystemEnumerator.Windows.cs#L113? which giving the hint where the original exception is thrown?

**Comment by jkotas** [comment] 2021-06-07 21:25
> this failure its part of a lookup to throw the real exception.

I think it is likely that the "real exception" in this case is bogus too - that was also thrown as a result of the overall process state corruption.

**Comment by tarekgh** [comment] 2021-06-07 21:37
@TheArcaneBrony is it possible you can capture the [debugger dump](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dumps?ranMID=46131&ranEAID=a1LgFw09t88&ranSiteID=a1LgFw09t88-O7Ng_o3gyyofISMR84znlg&epi=a1LgFw09t88-O7Ng_o3gyyofISMR84znlg&irgwc=1&OCID=AID2000142_aff_7806_1243925&tduid=%28ir__mrdukhopi0kfqxeykk0sohzifv2xupwfmuxvqyey00%29%287806%29%281243925%29%28a1LgFw09t88-O7Ng_o3gyyofISMR84znlg%29%28%29&irclickid=_mrdukhopi0kfqxeykk0sohzifv2xupwfmuxvqyey00) when it fails?

**Closed** 2022-06-01 06:01 UTC
Labels: area-System.Runtime, no-recent-activity, needs-author-action
