### ISSUE TITLE
.NET 6.0-preview1 frequently hangs on shutting the engine down during ETW provider enabling

### ISSUE THREAD

**Issue by ww898** [dotnet/runtime#48461] opened 2021-02-18 16:29 UTC
Hi, I tried new .NET6 in our CI, some test scenarios 100% hangs on slow computers. So, I created the dump and ready to share it with the .NET team for final investigation. My investigation shows that there is the deadlock between enabling the ETW provider and shutting the CoreCLR engine down.

Windows 10 Pro x64 Version 1809 (Build 17763.557)
.NET 6.0.100-preview.1.21103.13

The application:
```
using System;

namespace TTT
{
  internal static class Program
  {
    [STAThread]
    private static void Main()
    {
      Console.WriteLine("*****************************************************************************");
    }
  }
}
```
Call stacks:
```
0:011> ~0 k
 # Child-SP          RetAddr           Call Site
00 00000008`6d57e7e8 00007ff9`ebecf5cd win32u!NtUserMsgWaitForMultipleObjectsEx+0x14
01 00000008`6d57e7f0 00007ff9`eb3a586c user32!RealMsgWaitForMultipleObjectsEx+0x1d
02 00000008`6d57e830 00007ff9`eb3a52ee combase!CCliModalLoop::BlockFn+0x14c [onecore\com\combase\dcomrem\callctrl.cxx @ 2257] 
03 00000008`6d57e8b0 00007ff9`eb3688a6 combase!ClassicSTAThreadWaitForHandles+0xce [onecore\com\combase\dcomrem\classicsta.cpp @ 51] 
04 00000008`6d57e9e0 00007ff9`beb13c5b combase!CoWaitForMultipleHandles+0x76 [onecore\com\combase\dcomrem\sync.cxx @ 124] 
05 (Inline Function) --------`-------- coreclr!MsgWaitHelper+0x30 [F:\workspace\_work\1\s\src\coreclr\vm\threads.cpp @ 3268] 
06 (Inline Function) --------`-------- coreclr!Thread::DoAppropriateAptStateWait+0xee6f4 [F:\workspace\_work\1\s\src\coreclr\vm\threads.cpp @ 3306] 
07 00000008`6d57ea20 00007ff9`bea25371 coreclr!Thread::DoAppropriateWaitWorker+0xee8ab [F:\workspace\_work\1\s\src\coreclr\vm\threads.cpp @ 3443] 
08 00000008`6d57eb10 00007ff9`bea69479 coreclr!Thread::DoAppropriateWait+0x89 [F:\workspace\_work\1\s\src\coreclr\vm\threads.cpp @ 3160] 
09 (Inline Function) --------`-------- coreclr!CLREventBase::WaitEx+0x27 [F:\workspace\_work\1\s\src\coreclr\vm\synch.cpp @ 463] 
0a (Inline Function) --------`-------- coreclr!CLREventBase::Wait+0x27 [F:\workspace\_work\1\s\src\coreclr\vm\synch.cpp @ 416] 
0b 00000008`6d57eb90 00007ff9`bea2cb5a coreclr!FinalizerThread::RaiseShutdownEvents+0x71 [F:\workspace\_work\1\s\src\coreclr\vm\finalizerthread.h @ 64] 
0c 00000008`6d57ebe0 00007ff9`bea2c8a6 coreclr!EEShutDownHelper+0x272 [F:\workspace\_work\1\s\src\coreclr\vm\ceemain.cpp @ 1303] 
0d 00000008`6d57ee00 00007ff9`bea2fb80 coreclr!EEShutDown+0x66 [F:\workspace\_work\1\s\src\coreclr\vm\ceemain.cpp @ 1709] 
0e 00000008`6d57ee40 00007ff9`bea62a79 coreclr!CorHost2::UnloadAppDomain2+0x40 [F:\workspace\_work\1\s\src\coreclr\vm\corhost.cpp @ 922] 
0f 00000008`6d57ee70 00007ff9`c36d91c7 coreclr!coreclr_shutdown_2+0x59 [F:\workspace\_work\1\s\src\coreclr\dlls\mscoree\unixinterface.cpp @ 357] 
10 (Inline Function) --------`-------- hostpolicy!coreclr_t::shutdown+0x45 [F:\workspace\_work\1\s\src\installer\corehost\cli\hostpolicy\coreclr.cpp @ 132] 
11 00000008`6d57eec0 00007ff9`c36d947c hostpolicy!run_app_for_context+0x5c7 [F:\workspace\_work\1\s\src\installer\corehost\cli\hostpolicy\hostpolicy.cpp @ 264] 
12 00000008`6d57f060 00007ff9`c36d9fd8 hostpolicy!run_app+0x3c [F:\workspace\_work\1\s\src\installer\corehost\cli\hostpolicy\hostpolicy.cpp @ 284] 
13 00000008`6d57f0a0 00007ff9`c740b298 hostpolicy!corehost_main+0x108 [F:\workspace\_work\1\s\src\installer\corehost\cli\hostpolicy\hostpolicy.cpp @ 430] 
14 00000008`6d57f250 00007ff9`c740dfd7 hostfxr!execute_app+0x2e8 [F:\workspace\_work\1\s\src\installer\corehost\cli\fxr\fx_muxer.cpp @ 146] 
15 00000008`6d57f350 00007ff9`c7410302 hostfxr!`anonymous namespace'::read_config_and_execute+0x97 [F:\workspace\_work\1\s\src\installer\corehost\cli\fxr\fx_muxer.cpp @ 520] 
16 00000008`6d57f450 00007ff9`c740e62d hostfxr!fx_muxer_t::handle_exec_host_command+0x152 [F:\workspace\_work\1\s\src\installer\corehost\cli\fxr\fx_muxer.cpp @ 1001] 
17 00000008`6d57f4f0 00007ff9`c7408ff8 hostfxr!fx_muxer_t::execute+0x47d [F:\workspace\_work\1\s\src\installer\corehost\cli\fxr\fx_muxer.cpp @ 566] 
18 00000008`6d57f630 00007ff7`594e1dfc hostfxr!hostfxr_main_startupinfo+0x98 [F:\workspace\_work\1\s\src\installer\corehost\cli\fxr\hostfxr.cpp @ 60] 
19 00000008`6d57f730 00007ff7`594e216b Child_exe!exe_start+0x8bc [F:\workspace\_work\1\s\src\installer\corehost\corehost.cpp @ 236] 
1a 00000008`6d57f900 00007ff7`594e3b88 Child_exe!wmain+0xab [F:\workspace\_work\1\s\src\installer\corehost\corehost.cpp @ 305] 
1b (Inline Function) --------`-------- Child_exe!invoke_main+0x22 [d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 90] 
1c 00000008`6d57f930 00007ff9`ec2f7974 Child_exe!__scrt_common_main_seh+0x10c [d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 288] 
1d 00000008`6d57f970 00007ff9`ee0aa271 kernel32!BaseThreadInitThunk+0x14
1e 00000008`6d57f9a0 00000000`00000000 ntdll!RtlUserThreadStart+0x21
0:011> ~10 k
 # Child-SP          RetAddr           Call Site
00 00000008`6eafebf8 00007ff9`eacbc7ce ntdll!NtWaitForMultipleObjects+0x14
01 00000008`6eafec00 00007ff9`bea255a8 KERNELBASE!WaitForMultipleObjectsEx+0xfe
02 (Inline Function) --------`-------- coreclr!Thread::DoAppropriateAptStateWait+0x41 [F:\workspace\_work\1\s\src\coreclr\vm\threads.cpp @ 3311] 
03 00000008`6eafef00 00007ff9`bea25371 coreclr!Thread::DoAppropriateWaitWorker+0x1f8 [F:\workspace\_work\1\s\src\coreclr\vm\threads.cpp @ 3443] 
04 00000008`6eafeff0 00007ff9`bea252d5 coreclr!Thread::DoAppropriateWait+0x89 [F:\workspace\_work\1\s\src\coreclr\vm\threads.cpp @ 3160] 
05 (Inline Function) --------`-------- coreclr!CLREventBase::WaitEx+0x53 [F:\workspace\_work\1\s\src\coreclr\vm\synch.cpp @ 463] 
06 00000008`6eaff070 00007ff9`bea24d46 coreclr!CLREventBase::Wait+0x59 [F:\workspace\_work\1\s\src\coreclr\vm\synch.cpp @ 417] 
07 00000008`6eaff0c0 00007ff9`bea24b76 coreclr!AwareLock::EnterEpilogHelper+0x1b6 [F:\workspace\_work\1\s\src\coreclr\vm\syncblk.cpp @ 2616] 
08 00000008`6eaff1b0 00007ff9`bea24aaa coreclr!AwareLock::EnterEpilog+0x42 [F:\workspace\_work\1\s\src\coreclr\vm\syncblk.cpp @ 2487] 
09 00000008`6eaff200 00007ff9`bea99f5b coreclr!AwareLock::Enter+0x96 [F:\workspace\_work\1\s\src\coreclr\vm\syncblk.cpp @ 2389] 
0a 00000008`6eaff230 00007ff9`bea31287 coreclr!JIT_MonEnter_Helper+0x10b [F:\workspace\_work\1\s\src\coreclr\vm\jithelpers.cpp @ 3669] 
0b 00000008`6eaff3d0 00007ff9`5ef070a8 coreclr!JIT_MonReliableEnter_Portable+0xd7 [F:\workspace\_work\1\s\src\coreclr\vm\jithelpers.cpp @ 3717] 
0c 00000008`6eaff410 00007ff9`5ef06f3f 0x00007ff9`5ef070a8
0d 00000008`6eaff490 00007ff9`5ef000d0 0x00007ff9`5ef06f3f
0e 00000008`6eaff520 00007ff9`5eeff24a 0x00007ff9`5ef000d0
0f 00000008`6eaff650 00007ff9`ee0b4c64 0x00007ff9`5eeff24a
10 00000008`6eaff6e0 00007ff9`ee08d6e6 ntdll!EtwpEventApiCallback+0xd4
11 00000008`6eaff790 00007ff9`ee0abdd0 ntdll!EtwpUpdateEnableInfoAndCallback+0xe2
12 00000008`6eaff7e0 00007ff9`ee0ab87d ntdll!EtwpProcessNotification+0x50
13 00000008`6eaff810 00007ff9`ee0ab6cd ntdll!EtwDeliverDataBlock+0xdd
14 00000008`6eaff8a0 00007ff9`ee0b529c ntdll!EtwpNotificationThread+0x6d
15 00000008`6eaffa20 00007ff9`ee090348 ntdll!TppExecuteWaitCallback+0xa4
16 00000008`6eaffa70 00007ff9`ec2f7974 ntdll!TppWorkerThread+0x3c8
17 00000008`6eaffd60 00007ff9`ee0aa271 kernel32!BaseThreadInitThunk+0x14
18 00000008`6eaffd90 00000000`00000000 ntdll!RtlUserThreadStart+0x21
0:011> ~11 k
 # Child-SP          RetAddr           Call Site
00 00000008`6ec7f7f8 00007ff9`ee091a31 ntdll!NtWaitForAlertByThreadId+0x14
01 00000008`6ec7f800 00007ff9`ee09633a ntdll!RtlAcquireSRWLockExclusive+0x131
02 00000008`6ec7f870 00007ff9`5f06c681 ntdll!EtwNotificationUnregister+0x6a
03 00000008`6ec7f8a0 00007ff9`5f06c5e4 0x00007ff9`5f06c681
04 00000008`6ec7f960 00007ff9`5f06c551 0x00007ff9`5f06c5e4
05 00000008`6ec7f990 00007ff9`5f06c475 0x00007ff9`5f06c551
06 00000008`6ec7f9e0 00007ff9`5f06c3b6 0x00007ff9`5f06c475
07 00000008`6ec7fa10 00007ff9`5f04a44f 0x00007ff9`5f06c3b6
08 00000008`6ec7fa50 00007ff9`5f049741 0x00007ff9`5f04a44f
09 00000008`6ec7fac0 00007ff9`bea74053 0x00007ff9`5f049741
0a 00000008`6ec7fb20 00007ff9`be95a7f0 coreclr!CallDescrWorkerInternal+0x83
0b 00000008`6ec7fb60 00007ff9`bea2fcc5 coreclr!MethodDescCallSite::CallTargetWorker+0x268 [F:\workspace\_work\1\s\src\coreclr\vm\callhelpers.cpp @ 556] 
0c (Inline Function) --------`-------- coreclr!MethodDescCallSite::Call+0x12 [F:\workspace\_work\1\s\src\coreclr\vm\callhelpers.h @ 458] 
0d (Inline Function) --------`-------- coreclr!AppDomain::RaiseExitProcessEvent+0x2d [F:\workspace\_work\1\s\src\coreclr\vm\appdomain.cpp @ 4300] 
0e 00000008`6ec7fca0 00007ff9`ec2f7974 coreclr!FinalizerThread::FinalizerThreadStart+0x105 [F:\workspace\_work\1\s\src\coreclr\vm\finalizerthread.cpp @ 392] 
0f 00000008`6ec7fdc0 00007ff9`ee0aa271 kernel32!BaseThreadInitThunk+0x14
10 00000008`6ec7fdf0 00000000`00000000 ntdll!RtlUserThreadStart+0x21
0:011> ~10 e !clrstack
OS Thread Id: 0x1d84 (10)
        Child SP               IP Call Site
000000086EAFF2A8 00007ff9ee0e02b4 [HelperMethodFrame_1OBJ: 000000086eaff2a8] System.Threading.Monitor.ReliableEnter(System.Object, Boolean ByRef)
000000086EAFF410 00007ff95ef070a8 System.Diagnostics.Tracing.EventSource.SendCommand(System.Diagnostics.Tracing.EventListener, System.Diagnostics.Tracing.EventProviderType, Int32, Int32, System.Diagnostics.Tracing.EventCommand, Boolean, System.Diagnostics.Tracing.EventLevel, System.Diagnostics.Tracing.EventKeywords, System.Collections.Generic.IDictionary`2) [/_/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs @ 2381]
000000086EAFF490 00007ff95ef06f3f System.Diagnostics.Tracing.EventSource+OverrideEventProvider.OnControllerCommand(System.Diagnostics.Tracing.ControllerCommand, System.Collections.Generic.IDictionary`2, Int32, Int32) [/_/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs @ 2295]
000000086EAFF520 00007ff95ef000d0 System.Diagnostics.Tracing.EventProvider.EtwEnableCallBack(System.Guid ByRef, Int32, Byte, Int64, Int64, EVENT_FILTER_DESCRIPTOR*, Void*) [/_/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventProvider.cs @ 312]
000000086EAFF650 00007ff95eeff24a ILStubClass.IL_STUB_ReversePInvoke(IntPtr, Int32, Byte, Int64, Int64, Int64, Int64)
0:011> ~11 e !clrstack
OS Thread Id: 0x176c (11)
        Child SP               IP Call Site
000000086EC7F8C8 00007ff9ee0e3074 [InlinedCallFrame: 000000086ec7f8c8] Interop+Advapi32.EventUnregister(Int64)
000000086EC7F8C8 00007ff95f06c681 [InlinedCallFrame: 000000086ec7f8c8] Interop+Advapi32.EventUnregister(Int64)
000000086EC7F8A0 00007ff95f06c681 System.Diagnostics.Tracing.EtwEventProvider.System.Diagnostics.Tracing.IEventProvider.EventUnregister(Int64) [/_/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventProvider.cs @ 1287]
000000086EC7F960 00007ff95f06c5e4 System.Diagnostics.Tracing.EventProvider.EventUnregister(Int64) [/_/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventProvider.cs @ 1231]
000000086EC7F990 00007ff95f06c551 System.Diagnostics.Tracing.EventProvider.Dispose(Boolean) [/_/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventProvider.cs @ 213]
000000086EC7F9E0 00007ff95f06c475 System.Diagnostics.Tracing.EventProvider.Dispose() [/_/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventProvider.cs @ 165]
000000086EC7FA10 00007ff95f06c3b6 System.Diagnostics.Tracing.EventSource.Dispose(Boolean) [/_/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs @ 1361]
000000086EC7FA50 00007ff95f04a44f System.Diagnostics.Tracing.EventListener.DisposeOnShutdown() [/_/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs @ 4070]
000000086EC7FAC0 00007ff95f049741 System.AppContext.OnProcessExit() [/_/src/libraries/System.Private.CoreLib/src/System/AppContext.cs @ 77]
```

**Comment by jkotas** [comment] 2021-02-18 16:50
Duplicate of #48342 ?

cc @sywhang

**Comment by sywhang** [comment] 2021-02-18 17:11
From the call stack, it does look like a duplicate of #48342.

**Comment by tommcdon** [comment] 2021-05-07 00:02
Closing as a dupe of #48342

**Closed by tommcdon** 2021-05-07 00:02 UTC
Labels: area-Tracing-coreclr
