### ISSUE TITLE
NetworkAddressChange.Unix can start reading from unrelated handles.

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#64319] opened 2022-01-26 07:49 UTC
The NetworkAddressChange implementation for Unix has a read loop with a raw handle:

https://github.com/dotnet/runtime/blob/43ceed5514ca93242ff41f9f1ee53fc108c5dc1b/src/libraries/System.Net.NetworkInformation/src/System/Net/NetworkInformation/NetworkAddressChange.Unix.cs#L173-L179

Between the condition-check in the `while` loop, and passing the handle to `ReadEvents` the handle may be re-used for something other. That means we'll be reading for some one else's file descriptor.

**Comment by tmds** [comment] 2022-01-26 07:51
cc @ManickaP @wfurt @vdjuric

**Comment by tmds** [comment] 2022-01-26 07:52
I'll look into fixing this once https://github.com/dotnet/runtime/pull/63963 is merged.

**Comment by am11** [comment] 2022-01-27 06:45
I think we may need to dup() file descriptor to avoid it from getting reassigned unless both original and duplicate fds are closed (we would need to keep track of both).

Alternatively, in a go-lang library `fsnotify`, I [noticed](https://github.com/fsnotify/fsnotify/blob/712fe1d802d8c20c95e843adac4d8b11c1d636d1/inotify.go#L43) that they create additional epoll handle around fd being watched (by inotify) to avoid hitting "fd was reassigned by kernel" race conditions. We are also missing such guards in inotify-based file watcher that maybe the cause of some FileSystemWatcher area issues on Linux.

**Comment by ManickaP** [comment] 2022-01-27 09:16
FYI, I just merged #63963.

**Comment by karelz** [comment] 2022-02-15 17:39
Triage: It is reliability problem. It is now used in HTTP/3.

**Closed** 2022-02-22 17:31 UTC
Labels: bug, area-System.Net, in-pr
