### ISSUE TITLE
Nullable annotations for `Microsoft.Extensions.Configuration`

### ISSUE THREAD

**Issue by maxkoshevoi** [dotnet/runtime#57200] opened 2021-08-11 11:09 UTC
### Description

Indexer and `GetConnectionString` can return null, but they are not annotated to indicate that.

https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Configuration.Abstractions/src/ConfigurationExtensions.cs#L34

### Regression?

No

### Other information

I'm willing to fix it myself

**Comment by stephentoub** [comment] 2021-08-11 11:24
This library hasn't been annotated for nullability at all.

**Comment by maxkoshevoi** [comment] 2021-08-11 11:32
@stephentoub Would PR that annotates it be accepted? If so, I can do it.

**Comment by stephentoub** [comment] 2021-08-11 11:41
Yes, that would be welcome. Thanks.

**Comment by MaledongGit** [comment] 2021-08-12 03:14
https://github.com/dotnet/runtime/blob/79836486e75cbcc1c0525306f68a0ef71d0f8cf6/src/libraries/Microsoft.Extensions.Configuration.Abstractions/src/ConfigurationExtensions.cs#L34

Is it necessary to use "?" at the back of "configuration"? This is an extended method, the "configuration" shouldn't be null. Maybe the "?" should be removed.

**Comment by danmoseley** [comment] 2021-08-12 04:40
Seconding that, we would welcome help annotating our last remaining libraries. This may help you:

https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/api-guidelines/nullability.md

Reach out if you need help from us.

**Comment by stephentoub** [comment] 2021-08-12 14:28
> Do you know why Visual Studio 2019 might not generate nullable errors even though nullable is enabled (I tried enabling it everywhere down to `#nullable enabled in the source file)?

The library only has a netstandard2.0 and net461 configuration today:
https://github.com/dotnet/runtime/blob/3b40c7cfc4519a95e9d03ac85a2a2de68299aa7f/src/libraries/Microsoft.Extensions.Configuration.Abstractions/src/Microsoft.Extensions.Configuration.Abstractions.csproj#L4
and we explicitly disable nullable warnings across the repo for such projects:
https://github.com/dotnet/runtime/blob/3b40c7cfc4519a95e9d03ac85a2a2de68299aa7f/src/libraries/Directory.Build.targets#L27
You can try overriding it by explicitly adding `<NoWarn/>` to the csproj, but I expect you may run into some additional complications, including the reasons why we suppress them for this configuration.  For example, because of lack of annotations on `Debug.Assert` in the reference assemblies for those target frameworks, the compiler won't consider `Debug.Assert(x != null)` as part of its nullable flow analysis.

**Comment by eerhardt** [comment] 2021-08-12 14:57
Duplicate of https://github.com/dotnet/runtime/issues/43605. I'm going to close this issue as there is no reason to track this in multiple places.

> The library only has a netstandard2.0 and net461 configuration today

The plan for all Microsoft.Extensions.* libraries is to add a `$(NetCoreAppCurrent)` TFM to the project. That will allow the compiler to give the correct nullable warnings. (Plus it will give us other benefits as well.) See https://github.com/dotnet/runtime/issues/54012. 

We've been adding the `$(NetCoreAppCurrent)` TFM to other Extensions libraries as we've needed. e.g. #56324. So @maxkoshevoi, if you were going to add nullable annotations for Configuration, you can just add the new TFM as well in the same PR. But be sure to check all the `#if`s are still correct for the new TFM. We've hit that issue in the past when adding new TFMs - for example #56843.

**Closed by eerhardt** 2021-08-12 14:57 UTC
Labels: untriaged, area-Extensions-Configuration
