### ISSUE TITLE
Test failure: System.InvalidOperationException : Cannot load Counter Name data because an invalid index '' was read from the registry.

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#45814] opened 2020-12-09 02:22 UTC
failed in job: https://dev.azure.com/dnceng/public/_build/results?buildId=912067&view=ms.vss-test-web.build-test-results-tab&runId=29050600&resultId=180276&paneView=debug

pipeline: runtime-coreclr libraries-jitstress

failed tests:
System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Obsolete_CCD
System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_GetCategories
System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_ReadCategory
System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_BeginInit_ProcessorCounter
System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_InstanceExists_Static
System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_CounterExists_StaticInterruptsPerSec
System.Diagnostics.Tests.CounterCreationDataCollectionTests.PerformanceCounterCategory_CreateCategory
System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Obsolete
System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_CreateCounter_Count0
System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_CreateCounter_ProcessorCounter
System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_CounterExists_InterruptsPerSec
System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_BeginInitEndInit_ProcessorCounter
System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_DeleteCategory
System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_RemoveInstance

net6.0-windows-Release-arm64-CoreCLR_checked-no_tiered_compilation-Windows.10.Arm64v8.Open

Error message
~~~
System.InvalidOperationException : Cannot load Counter Name data because an invalid index '' was read from the registry.

Stack trace
   at System.Diagnostics.PerformanceCounterLib.GetStringTable(Boolean isHelp) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs:line 1120
   at System.Diagnostics.PerformanceCounterLib.get_NameTable() in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs:line 241
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable() in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs:line 174
   at System.Diagnostics.PerformanceCounterLib.CategoryExists(String machine, String category) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs:line 281
   at System.Diagnostics.Tests.Helpers.DeleteCategory(String name) in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/Helpers.cs:line 46
   at System.Diagnostics.Tests.Helpers.CreateCategory(String name, PerformanceCounterCategoryType categoryType) in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/Helpers.cs:line 25
   at System.Diagnostics.Tests.PerformanceCounterTests.CreateCounterWithCategory(String name, Boolean readOnly, PerformanceCounterCategoryType categoryType)
   at System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_RemoveInstance() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterTests.cs:line 260
~~~

**Comment by tommcdon** [comment] 2020-12-09 19:12
@krwq I've marked this item as triaged for .NET 6

**Comment by v-haren** [comment] 2020-12-21 06:48
failed again in job: [runtime-coreclr libraries-jitstressregs 20201220.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=927836&view=ms.vss-test-web.build-test-results-tab&runId=29414466&resultId=180355&paneView=debug)

failed tests:
System.Diagnostics.Tests.InstanceDataTests.InstanceDataCollectionCollection_GetKeys
System.Diagnostics.Tests.InstanceDataTests.InstanceDataCollectionCollection_Contains_inValid
System.Diagnostics.Tests.InstanceDataTests.InstanceDataCollection_GetItem_ExistingCounter
System.Diagnostics.Tests.InstanceDataTests.InstanceDataCollection_GetValues
System.Diagnostics.Tests.InstanceDataTests.InstanceDataCollectionCollection_Contains_Valid
System.Diagnostics.Tests.InstanceDataTests.InstanceDataCollection_GetKeys
System.Diagnostics.Tests.InstanceDataTests.InstanceDataCollectionCollection_GetItem_Invalid
System.Diagnostics.Tests.InstanceDataTests.InstanceDataCollectionCollection_CopyTo
System.Diagnostics.Tests.InstanceDataTests.InstanceDataCollection_NullTest
System.Diagnostics.Tests.InstanceDataTests.InstanceDataCollectionCollection_GetValues
System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_BeginInitEndInit_ProcessorCounter
System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_GetCategories
System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_CounterExists_StaticInterruptsPerSec
System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_InstanceExists_Static
System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_CreateCounter_ProcessorCounter
System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_RemoveInstance
System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_CreateCounter_Count0
System.Diagnostics.Tests.PerformanceCounterTests.PerformanceCounter_BeginInit_ProcessorCounter
System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_ReadCategory
System.Diagnostics.Tests.CounterCreationDataCollectionTests.PerformanceCounterCategory_CreateCategory
System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_CounterExists_InterruptsPerSec
System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Obsolete
System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_DeleteCategory
System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_Create_Obsolete_CCD

net6.0-windows-Release-arm64-CoreCLR_checked-jitstressregs1-Windows.10.Arm64v8.Open


Error message
~~~
System.AggregateException : One or more errors occurred. (Cannot load Counter Name data because an invalid index '' was read from the registry.) (Cannot load Counter Name data because an invalid index '' was read from the registry.) (Cannot load Counter Name data because an invalid index '' was read from the registry.) (Cannot load Counter Name data because an invalid index '' was read from the registry.) (Cannot load Counter Name data because an invalid index '' was read from the registry.) (Cannot load Counter Name data because an invalid index '' was read from the registry.) (Cannot load Counter Name data because an invalid index '' was read from the registry.) (Cannot load Counter Name data because an invalid index '' was read from the registry.) (Cannot load Counter Name data because an invalid index '' was read from the registry.) (Cannot load Counter Name data because an invalid index '' was read from the registry.)
---- System.InvalidOperationException : Cannot load Counter Name data because an invalid index '' was read from the registry.
---- System.InvalidOperationException : Cannot load Counter Name data because an invalid index '' was read from the registry.
---- System.InvalidOperationException : Cannot load Counter Name data because an invalid index '' was read from the registry.
---- System.InvalidOperationException : Cannot load Counter Name data because an invalid index '' was read from the registry.
---- System.InvalidOperationException : Cannot load Counter Name data because an invalid index '' was read from the registry.
---- System.InvalidOperationException : Cannot load Counter Name data because an invalid index '' was read from the registry.
---- System.InvalidOperationException : Cannot load Counter Name data because an invalid index '' was read from the registry.
---- System.InvalidOperationException : Cannot load Counter Name data because an invalid index '' was read from the registry.
---- System.InvalidOperationException : Cannot load Counter Name data because an invalid index '' was read from the registry.
---- System.InvalidOperationException : Cannot load Counter Name data because an invalid index '' was read from the registry.


Stack trace
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen) in /_/src/libraries/Common/tests/TestUtilities/System/RetryHelper.cs:line 48
   at System.Diagnostics.Tests.Helpers.RetryOnAllPlatforms[T](Func`1 func)
   at System.Diagnostics.Tests.InstanceDataTests.InstanceDataCollectionCollection_GetKeys() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/InstanceDataTests.cs:line 86
----- Inner Stack Trace #1 (System.InvalidOperationException) -----
   at System.Diagnostics.PerformanceCounterLib.GetStringTable(Boolean isHelp) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs:line 1120
   at System.Diagnostics.PerformanceCounterLib.get_NameTable() in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs:line 241
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable() in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs:line 174
   at System.Diagnostics.PerformanceCounterLib.GetCategorySample(String category) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs:line 833
   at System.Diagnostics.PerformanceCounterLib.GetCategorySample(String machine, String category) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs:line 811
   at System.Diagnostics.PerformanceCounterCategory.ReadCategory() in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs:line 581
   at System.Diagnostics.Tests.Helpers.<>c__DisplayClass11_0`1.<RetryOnAllPlatforms>b__0() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/Helpers.cs:line 59
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen) in /_/src/libraries/Common/tests/TestUtilities/System/RetryHelper.cs:line 40
----- Inner Stack Trace #2 (System.InvalidOperationException) -----
   at System.Diagnostics.PerformanceCounterLib.GetStringTable(Boolean isHelp) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs:line 1120
   at System.Diagnostics.PerformanceCounterLib.get_NameTable() in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs:line 241
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable() in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs:line 174
   at System.Diagnostics.PerformanceCounterLib.GetCategorySample(String category) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs:line 833
   at System.Diagnostics.PerformanceCounterLib.GetCategorySample(String machine, String category) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs:line 811
   at System.Diagnostics.PerformanceCounterCategory.ReadCategory() in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs:line 581
   at System.Diagnostics.Tests.Helpers.<>c__DisplayClass11_0`1.<RetryOnAllPlatforms>b__0() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/Helpers.cs:line 59
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen) in /_/src/libraries/Common/tests/TestUtilities/System/RetryHelper.cs:line 40
----- Inner Stack Trace #3 (System.InvalidOperationException) -----
   at System.Diagnostics.PerformanceCounterLib.GetStringTable(Boolean isHelp) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs:line 1120
   at System.Diagnostics.PerformanceCounterLib.get_NameTable() in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagn
~~~

**Comment by danmosemsft** [comment] 2021-01-04 16:43
dupe of https://github.com/dotnet/runtime/issues/38756

**Closed by danmosemsft** 2021-01-04 16:43 UTC
Labels: area-System.Diagnostics
