### ISSUE TITLE
[Perf -29%] PerfLabTests.CastingPerf (2)

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#37803] opened 2020-06-12 17:32 UTC
### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Changes | [diff](https://github.com/dotnet/installer/compare/a4a49f07fbf986d496ef57521e76b22caaf9bfb3...ccd701fe23f236755650af3ce3d9ab6bdd8a4af9)

### Regressions in PerfLabTests.CastingPerf

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier
-- | -- | -- | -- | -- | --
CheckObjIsInterfaceNo | 218.29 μs | 280.64 μs | 1.29 |  | False
CheckIsInstAnyIsInterfaceNo | 218.29 μs | 280.65 μs | 1.29 |  | False

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/06_11_2020/Windows%2010.0.18362_x64/PerfLabTests.CastingPerf_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/06_11_2020/Windows%2010.0.18362_x64/PerfLabTests.CastingPerf_2.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/06_11_2020/Windows%2010.0.18362_x64/PerfLabTests.CastingPerf.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'PerfLabTests.CastingPerf*';
```
<details>

#### PerfLabTests.CastingPerf.CheckObjIsInterfaceNo

```log
[217888.775 ; 232960.149) | @@@@@@@@@@@@
[232960.149 ; 252981.511) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@
[252981.511 ; 270375.304) | 
[270375.304 ; 285446.677) | @@@@@@@@@@@@@@@@@@@
```
#### PerfLabTests.CastingPerf.CheckIsInstAnyIsInterfaceNo

```log
[209794.928 ; 226755.346) | @@@@@@@@@@@@@
[226755.346 ; 237218.013) | 
[237218.013 ; 254170.131) | @@@@@@@@@@@@@@@@@@@@@@@@@
[254170.131 ; 269951.518) | 
[269951.518 ; 286903.637) | @@@@@@@@@@@@@@@@@@@@
[286903.637 ; 303354.976) | 
[303354.976 ; 320307.095) | @
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by DrewScoggins** [comment] 2020-06-12 17:32
@adamsitnik @VSadov

**Comment by VSadov** [comment] 2020-07-21 18:49
Could be the cost of tiered compiler indirection showing up on a fast cast. Native implementation did not have that expense.

The cost of tiering indirection could be easily avoided by opting out the cating helper from tiering. That would mean jitting it at start up time. We decided against that, since these are "fast" casts and generally not a perf concern.

I will take a look to be sure.

**Comment by mangod9** [comment] 2020-08-06 02:17
@VSadov the last time we chatted I believe you mentioned this perf was reasonable. Is there anything actionable here?

**Comment by VSadov** [comment] 2020-08-06 21:51
@mangod9  Right. I just looked at this again to be sure. The code that we run here is the same as in the native implementation - these are simple cases that just compare the target interface against implemented interfaces (which in these benchmarks is a list of length 1).

The difference is that the managed implementation is called via an extra indirection due to tiering callsite, which is a trade off for the start up latency.
The only reason why we see the impact of an extra `jmp` is because the operation is extremely fast. The measurements are for loops that do 100000 casts.

I think we can accept the current performance. It is unlikely to cause issues in real world scenarios.

**Comment by mangod9** [comment] 2020-08-06 21:58
thanks for the follow up. Will close this out. @DrewScoggins is there anything required to track any further regressions in the future?

**Comment by VSadov** [comment] 2020-08-06 22:02
BTW, I like that we have tests sensitive to this.

**Comment by VSadov** [comment] 2020-08-06 22:03
Also, I think I can resolve https://github.com/dotnet/runtime/issues/1994 , which was asking for impact of tiering on casting and it is exactly what we are looking at here.

**Closed** 2020-08-07 02:59 UTC
Labels: arch-x64, area-VM-coreclr, os-windows, tenet-performance, tenet-performance-benchmarks
