### ISSUE TITLE
Deserializing to an array of a type decorated with the custom JsonConverter is not working

### ISSUE THREAD

**Issue by ChThy** [dotnet/runtime#49956] opened 2021-03-21 10:46 UTC
### Description

When deserializing an array of objects from json to an array of objects of which the type is decorated with a custom JsonConverter, it throws the following exception:

```
System.Text.Json.JsonException: The converter 'MoneyMaker.Core.converters.JsonCandleConverter' read too much or not enough. Path: $[0] | LineNumber: 0 | BytePositionInLine: 89313.
         at System.Text.Json.ThrowHelper.ThrowJsonException_SerializationConverterRead(JsonConverter converter)
         at System.Text.Json.Serialization.JsonConverter`1.VerifyRead(JsonTokenType tokenType, Int32 depth, Int64 bytesConsumed, Boolean isValueConverter, Utf8JsonReader& reader)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
         at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
         at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
         at MoneyMaker.Core.Services.MarketService.<>c__DisplayClass2_0.<<GetCandles>b__0>d.MoveNext() in D:\GitRepositories\MoneyMaker\MoneyMaker.Core\Services\MarketService.cs:line 41
      --- End of stack trace from previous location ---
```

The code getting the json object and trying to deserialize it: 
``` 
var response = await client.GetAsync(uriBuilder.ToString());
var body = await response.Content.ReadAsStringAsync();
var candles = JsonSerializer.Deserialize<CandleModel[]>(body);
```

Type to convert to: 
``` 
[JsonConverter(typeof(JsonCandleConverter))]
    public class CandleModel
    {
        public long Time { get; set; }
        public decimal Open { get; set; }
        public decimal High { get; set; }
        public decimal Low { get; set; }
        public decimal Close { get; set; }
        public decimal Volume { get; set; }
    }
```

When debugging in the custom JsonConverter, the reader is passed a reference who has access to the complete json instead of 1 json array.

I would expect that the custom JsonConverter is called for each entry in the json object to deserialize, but this is not the case.

### Configuration
* Running on .NET 5.0.1
* Windows 10 Pro OS build 19041.867
* x64 architecture

**Comment by eiriktsarpalis** [comment] 2021-03-24 16:40
Hi @ChThy, it is possible that there is a bug in your custom converter. Would you be able to share a minimal reproduction that includes the converter code as well? Thanks.

**Comment by eiriktsarpalis** [comment] 2021-03-25 13:47
I took the time to transcribe your response into a minimal reproduction:
```csharp
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

class Program
{
    [JsonConverter(typeof(JsonCandleConverter))]
    public class CandleModel
    {
        public long Time { get; set; }
        public decimal Open { get; set; }
        public decimal High { get; set; }
        public decimal Low { get; set; }
        public decimal Close { get; set; }
        public decimal Volume { get; set; }
    }

    public class JsonCandleConverter : JsonConverter<CandleModel>
    {
        public override bool CanConvert(Type typeToConvert)
        {
            return typeToConvert == typeof(CandleModel);
        }

        public override CandleModel Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var values = new List<string>();
            while (reader.Read())
            {
                var token = reader.TokenType;
                switch (token)
                {
                    case JsonTokenType.None:
                        break;
                    case JsonTokenType.StartObject:
                        break;
                    case JsonTokenType.EndObject:
                        break;
                    case JsonTokenType.StartArray:
                        break;
                    case JsonTokenType.EndArray:
                        break;
                    case JsonTokenType.PropertyName:
                        break;
                    case JsonTokenType.Comment:
                        break;
                    case JsonTokenType.String:
                        values.Add(reader.GetString());
                        break;
                    case JsonTokenType.Number:
                        break;
                    case JsonTokenType.True:
                        break;
                    case JsonTokenType.False:
                        break;
                    case JsonTokenType.Null:
                        break;
                    default:
                        break;
                }
            }

            return new CandleModel
            {
                Time = long.Parse(values[0]),
                Open = decimal.Parse(values[1]),
                High = decimal.Parse(values[2]),
                Low = decimal.Parse(values[3]),
                Close = decimal.Parse(values[4]),
                Volume = decimal.Parse(values[5])
            };
        }

        public override void Write(Utf8JsonWriter writer, CandleModel value, JsonSerializerOptions options)
        {
            throw new NotImplementedException();
        }
    }

    static void Main()
    {
        var body = @"[""1538784000000"",""4999"",""5012"",""4999"",""5012"",""0.45""]";
        var candles = JsonSerializer.Deserialize<CandleModel[]>(body);
    }
}
```
which fails with a different exception:
```
Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Program.JsonCandleConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) in C:\Users\eitsarpa\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 64
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
```
This is because the converter anticipates 6 elements in the list and fails since the input only contains 5 elements.

**Comment by ChThy** [comment] 2021-03-26 13:22
Hi @eiriktsarpalis, thank you for investing time on this. I isolated the issue into the attached console app.

Running this throws the exception.

[ConsoleApp1.zip](https://github.com/dotnet/runtime/files/6212023/ConsoleApp1.zip)

**Comment by eiriktsarpalis** [comment] 2021-03-26 13:38
Transcribing your zip file into code:
````csharp
using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

class Program
{
    [JsonConverter(typeof(JsonCandleConverter))]
    public class CandleModel
    {
        public long Time { get; set; }
        public decimal Open { get; set; }
        public decimal High { get; set; }
        public decimal Low { get; set; }
        public decimal Close { get; set; }
        public decimal Volume { get; set; }
    }

    public class JsonCandleConverter : JsonConverter<CandleModel>
    {
        public override bool CanConvert(Type typeToConvert)
        {
            return typeToConvert == typeof(CandleModel);
        }

        public override CandleModel Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var values = new List<string>();
            while (reader.Read())
            {
                var token = reader.TokenType;
                switch (token)
                {
                    case JsonTokenType.None:
                        break;
                    case JsonTokenType.StartObject:
                        break;
                    case JsonTokenType.EndObject:
                        break;
                    case JsonTokenType.StartArray:
                        break;
                    case JsonTokenType.EndArray:
                        break;
                    case JsonTokenType.PropertyName:
                        break;
                    case JsonTokenType.Comment:
                        break;
                    case JsonTokenType.String:
                        values.Add(reader.GetString());
                        break;
                    case JsonTokenType.Number:
                        break;
                    case JsonTokenType.True:
                        break;
                    case JsonTokenType.False:
                        break;
                    case JsonTokenType.Null:
                        break;
                    default:
                        break;
                }
            }

            return new CandleModel
            {
                Time = long.Parse(values[0]),
                Open = decimal.Parse(values[1]),
                High = decimal.Parse(values[2]),
                Low = decimal.Parse(values[3]),
                Close = decimal.Parse(values[4]),
                Volume = decimal.Parse(values[5])
            };
        }

        public override void Write(Utf8JsonWriter writer, CandleModel value, JsonSerializerOptions options)
        {
            throw new NotImplementedException();
        }
    }

    static void Main()
    {
        var json = "[[\"1616763600000\",\"45065\",\"45179\",\"44986\",\"45101\",\"4.86379968\"],[\"1616760000000\",\"44787\",\"45213\",\"44647\",\"45074\",\"65.37713988\"],[\"1616756400000\",\"45471\",\"45521\",\"44681\",\"44785\",\"102.60979565\"]]";

        var candles = JsonSerializer.Deserialize<CandleModel[]>(json);
    }
}
```

the `while(reader.Read()) { }` loop in your converter will consume the entire remaining json document, which is beyond the scope of the current list being read. STJ will detect this and throw an error, by design. You need to update your converter so that the loop is exited as soon as `JsonTokenType.EndArray` is encountered.

Closing, since this is by-design behaviour.

**Closed by eiriktsarpalis** 2021-03-26 13:38 UTC
Labels: area-System.Text.Json, needs more info, untriaged
