### ISSUE TITLE
improve Immutable by removing or adding some checks

### ISSUE THREAD

**Issue by MaledongGit** [dotnet/runtime#58977] opened 2021-09-11 00:58 UTC
1. After reading the source code of ImmutableList<T> (an extended method):
https://github.com/dotnet/runtime/blob/73c0f8d7f6635d589470c7ff7d9680128342aac4/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList.cs#L289-L292

It seems we don't need to have a check for both Count == 0 and startIndex == 0, because if the Count == 0, this means there's no element inside the container, directly to return you -1 to avoid some exceptions (according to the some "LastIndexOf()" functions).

2. https://github.com/dotnet/runtime/blob/73c0f8d7f6635d589470c7ff7d9680128342aac4/src/libraries/System.Collections.Immutable/src/System/Collections/Immutable/ImmutableList.cs#L320
The codes below also need a check for Count, just like others' "LastIndexOf()" in case of Arguement out of range exception, and there doesn't seem possible if there's no element there. We can find nothing through "LastIndexOf".

I'm not sure whether will break changes or not, but it seems very strange why the last "LastIndexOf()" doesn't need check for Count but for others we need? So I made an improvement for it.

Welcome your discussions if there's anything special, It seems all the test cases are passed.

**Comment by eiriktsarpalis** [comment] 2021-09-13 08:49
> to avoid some exceptions (according to the some "LastIndexOf()" functions).

Which implementations result in exceptions currently? Can you share a minimal reproduction?

**Comment by krwq** [comment] 2021-09-27 08:19
@MaledongGit can you please share specific issue you're seeing? Or is the point to just make the code cleaner? Without extra info I'm leaning toward closing this issue as by design at this point

**Closed** 2021-11-17 06:01 UTC
Labels: area-System.Collections, needs more info, no recent activity
