### ISSUE TITLE
.NET seems to special-case renaming of EML files

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#61991] opened 2021-11-23 22:44 UTC
### Description

When you rename any file, the file preserves its date created and date modified attributes... UNLESS it is a .EML file.

### Reproduction Steps

Run this code:

```

var RootFolder = System.Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
var DestFolder = System.IO.Path.Combine(RootFolder, "Test");
System.IO.Directory.CreateDirectory(DestFolder);

var Extensions = new List<string>() {
    "txt",
    "pdf",
    "eml"
};

var TempFiles = new Dictionary<string, string>();

foreach (var Extension in Extensions) {
    var DestFile = System.IO.Path.Combine(DestFolder, $@"{Extension}.tmp");
    TempFiles[Extension] = DestFile;
}

var FinalFiles = new Dictionary<string, string>();

foreach (var Extension in Extensions) {
    var DestFile = System.IO.Path.Combine(DestFolder, $@"{Extension}.{Extension}");
    FinalFiles[Extension] = DestFile;

    if (System.IO.File.Exists(DestFile)) {
        System.IO.File.Delete(DestFile);
    }

}

foreach (var File in TempFiles) {
    using var temp = System.IO.File.Create(File.Value);
}

await Task.Delay(65 * 1000);

foreach (var Extension in Extensions) {
    System.IO.File.Move(TempFiles[Extension], FinalFiles[Extension], true);
}

foreach (var File in FinalFiles.Values) {
    var DateCreated = System.IO.File.GetCreationTime(File);
    var DateModified = System.IO.File.GetLastWriteTime(File);

    if (DateModified > DateCreated) {
        Console.WriteLine($@"Move changed last write time: {File}");
    }
}

Console.ReadLine();

```

And navigate to the TEST folder on your desktop.

### Expected behavior

EML files behave the same way as every other file extension

### Actual behavior

The DateModified value of EML files changes.

### Regression?

I think so.

### Known Workarounds

none that I can think of.

### Configuration

Windows 11.  x64.  NET 6.0

**Comment by filipnavara** [comment] 2021-11-23 22:54
It sounds much more likely that it's the search indexer or antivirus doing some background modifications. Did you try running Process Monitor with a filter on the particular path to see if other process accesses it?

**Comment by TonyValenti** [comment] 2021-11-23 23:32
@filipnavara Thanks so much for the thoughts!  I just used Process Monitor and it SeachProtocolHost seems to clobber the date modified on eml files.  How do I get that in front of someone at MS?

**Comment by filipnavara** [comment] 2021-11-23 23:45
I'd suggest checking "Indexing options" in Windows to see what indexer is associated with .eml files. It could still be 3rd party application. If it's not then you may use the Feedback tool in Windows to report it.

**Comment by Jozkee** [comment] 2021-11-24 18:40
@TonyValenti, what @filipnavara suggests sounds like a good approach. Please use the Feedback tool to report the issue directly to Windows through Feedback Hub app.

Since this issue is not caused by .NET I will close it.

**Closed by Jozkee** 2021-11-24 18:40 UTC
Labels: area-System.IO, untriaged
