### ISSUE TITLE
ILVerify falsely reports a field being modified

### ISSUE THREAD

**Issue by masonwheeler** [dotnet/runtime#102997] opened 2024-06-03 15:18 UTC
### Description

ILVerify is usually pretty good at finding invalid IL in your code.  But I've stumbled across something that's either a false positive or a bug in Roslyn's C# codgen, and I'm guessing it's the former, because the error message does not match what's in either the C# code or the decompiled CIL.  (If this is actually a Roslyn problem, let me know and I'll refile this bug on the Roslyn repo.)

### Reproduction Steps

Build the following, then examine the resulting DLL in ILVerify

```
using System.Reflection.Emit;

namespace CorruptRoslynCodegen
{
	internal class Program
	{
		static void Main(string[] args)
		{
			Console.WriteLine("Hello, World!");
		}

		protected static bool IsStobj(OpCode code)
		{
			return OpCodes.Stobj.Value == code.Value;
		}
	}
}
```

### Expected behavior

As the flagship .NET language, it's expected that the official C# compiler does not produce invalid IL.

It is also expected that official IL verification tools do not report invalid IL where none exists.

### Actual behavior

> [IL]: Error [InitOnly]: [C:\...\CorruptRoslynCodegen.dll : CorruptRoslynCodegen.Program::IsStobj([S.P.CoreLib]System.Reflection.Emit.OpCode)][offset 0x00000001] Cannot change initonly field outside its .ctor.

### Configuration

.NET 9, most recent daily build as of 6/3/2024
Windows 10, x64

**Comment by MichalStrehovsky** [comment] 2024-06-04 06:26
The message could be better (it matches peverify.exe per https://github.com/dotnet/corert/issues/4911 though), but the gist is that ILVerify checks whether the input is _verifiable_ and ldsflda with an initonly field is documented as not verifiable in the ECMA-335 spec. We track adding a weaker mode to ILVerify that checks for _valid_ IL in #37391.

Roslyn generates ldsflda because the OpCode struct is marked readonly and therefore this doesn't violate C# type safety rules. But the code is unverifiable and ILVerify will warn.

**Comment by masonwheeler** [comment] 2024-06-04 12:04
So basically, the `ldsflda` sets things up to that further down the line, something else *could* violate type safety, but nothing is actually doing so?

**Comment by jkotas** [comment] 2024-06-04 14:35
ILVerify implements .NET Framework 4.0 set of verification rules. These rules were not officially amended for the new constructs such as `readonly` structs and methods in this case. We would be happy to merge changes to amend the verification rules for the new constructs such as this one.

**Comment by masonwheeler** [comment] 2024-06-04 14:39
> These rules were not officially amended for the new constructs such as readonly structs and methods in this case.

Are those rules unofficially described anywhere besides compiler source code?

**Comment by jkotas** [comment] 2024-06-05 22:58
Resolving as duplicate of https://github.com/dotnet/runtime/issues/57444

**Closed by jkotas** 2024-06-05 22:58 UTC
Labels: help wanted, area-Tools-ILVerification
