### ISSUE TITLE
.NET 6 Application fails after windows updates with Hostpolicy.dll missing

### ISSUE THREAD

**Issue by vinaygangaraj** [dotnet/runtime#101231] opened 2024-04-18 09:43 UTC
I have a .NET 6 application that operates on the .NET 6.0.11 runtime. Occasionally, when Windows updates occur, they install newer versions of .NET 6, such as .NET 6.0.26. Following these updates, my application fails to execute.

Upon reviewing the event viewer logs, I've encountered the following error. What might be causing this problem? How can I safeguard my application from being impacted by these Windows updates? Any assistance would be greatly valued.

The only Workaround is to un-install and re-install the higher version of .NET 6 runtime again to make application to run. But, the question here is: why would windows update is causing this issue?

```
Description: A .NET application failed.
Application: MyApp.exe
Path: C:\Test\MyApp.exe
Message: Cannot use file stream for [C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.26\Microsoft.NETCore.App.deps.json]: No such file or directory
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.26'.
```

**Comment by AaronRobinsonMSFT** [comment] 2024-04-19 20:47
Are you sure this is a Windows Update? I don't think that Windows updates .NET 6+. Visual Studio does install and update .NET 6+, so it is possible that the tool impacting the install.

@elinor-fung Any thoughts?

**Comment by logicaloud** [comment] 2024-04-21 04:34
It sounds like this issue https://github.com/dotnet/runtime/issues/60144 that also affects latest .NET versions (https://github.com/dotnet/runtime/issues/100452).

**Comment by vinaygangaraj** [comment] 2024-04-24 05:55
@elinor-fung I could not verify whether those files were present or not, we will try to get this information soon. After re-installing the higher version of .NET 6 Windows hosting bundle fixed the issue. Since this issue happens only after the windows updates are pushed, it is quite challenging to reproduce the issue.

**For example:** When the below Windows update happened it results into the same issue.
https://support.microsoft.com/en-us/topic/-net-6-0-update-february-13-2024-kb5035119-d1ab28fa-38e5-4835-af44-8c26f7fbde33

**Comment by NikolaMilosavljevic** [comment] 2024-07-01 18:22
@vinaygangaraj I was not able to reproduce this issue. Closing for now. Please reopen if you can provide consistent repro steps.

**Closed by NikolaMilosavljevic** 2024-07-01 18:22 UTC
Labels: area-Host
