### ISSUE TITLE
Unable to get architecture of the current processor

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#43246] opened 2020-10-10 00:31 UTC
It seems as though the ProcessArchitecture enum does not contain ARM64/32 variants which should be added.

**Comment by danmosemsft** [comment] 2020-10-10 00:40
It is present?

https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/Reflection/ProcessorArchitecture.cs

**Comment by TonyValenti** [comment] 2020-10-10 08:41
@danmosemsft -
It has Arm, but not Arm32 or Arm64.  There should be a separate value for each.

Similarly, it would be really nice if there were functions like ```Architecture.IsArm32()``` that functioned like hardware intrinsics ```System.Runtime.Intrinsics._____.IsSupported``` or the ```OperatingSystem.Is______``` methods.

**Comment by TonyValenti** [comment] 2020-10-10 09:02
Actually it appears this may already exist.

https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation.processarchitecture?view=netcore-3.1

**Comment by TonyValenti** [comment] 2020-10-10 09:33
@danmosemsft I don't believe that is it.  How would I get the architecture of the current processor?

This is close:
https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation.processarchitecture?view=netcore-3.1

But that gives the process architecture of the currently running app, not of the machine.

I need to be able to detect if an x86 app is running on an x64 or arm64 processor.  Using the above, running x86 on x64 returns x86 which is not what I need.

**Comment by danmosemsft** [comment] 2020-10-10 16:01
Ah, I'm not sure whether we attempt to expose that -- generally, the OS tries hard to conceal it from you. 

Outside of .NET, I have usually seen people check eg the PROCESSOR_ARCHITEW6432 environment variable (at least that's for detecting WOW64, not sure about on ARM)

**Comment by iSazonov** [comment] 2020-10-16 07:38
Is it related with adding osx-arm64 https://github.com/dotnet/runtime/issues/43313?

**Comment by steveharter** [comment] 2020-11-12 22:58
The System.Reflection namespace is not intended for environmental detection. The linked [System.Runtime.InteropServices](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation.processarchitecture) is a better fit.

**Comment by AaronRobinsonMSFT** [comment] 2020-12-02 19:46
@danmosemsft and @TonyValenti This is a good question and one that warrants a longer discussion. The [`RuntimeInformation.ProcessorArchitecture`](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.runtimeinformation.processarchitecture) is meant to indicate the processor type the runtime is on top of, not necessarily details about the underlying hardware. Since there is an x86 emulation layer on an ARM64 machine this is stating what it was intended to state - the emulation layer is in play here and confusing things further. I don't think this is something the runtime should try and handle honestly. It becomes an exercise in futility as we must try to constantly peer into how the runtime is being run and honestly the entire point of the runtime is to abstract that away - not possible in all cases but is an ideal.

I also think this is enough of niche case that we should defer this until we get more user feedback. I would have some reservations about creating a new API. For context, APIs that represent this distinction on Windows are [`GetSystemInfo`](https://docs.microsoft.com/windows/win32/api/sysinfoapi/nf-sysinfoapi-getsysteminfo) and [`GetNativeSystemInfo`](https://docs.microsoft.com/windows/win32/api/sysinfoapi/nf-sysinfoapi-getnativesysteminfo) - the runtime uses `GetSystemInfo` in the [implementation](https://github.com/dotnet/runtime/blob/b9de3d04a0921199f24faee9d34a875044ecfe96/src/libraries/System.Runtime.InteropServices.RuntimeInformation/src/System/Runtime/InteropServices/RuntimeInformation/RuntimeInformation.Windows.cs#L52-L68).

**Comment by jkotas** [comment] 2021-12-25 01:06
Duplicate of #58463

**Closed by jkotas** 2021-12-25 01:06 UTC
Labels: api-suggestion, area-System.Runtime.InteropServices
