### ISSUE TITLE
Test failure: ConnectWithCertificateForDifferentName_Throws - NullReferenceException

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#56454] opened 2021-07-28 10:12 UTC
Test: System.Net.Quic.Tests.MsQuicTests.ConnectWithCertificateForDifferentName_Throws

Failures 5/28-7/28 (incl. PRs)

Day | Failures
-- | --
7/26 | 2x PRs -- PR #56281, PR #56306
7/27 | 4x PR -- PR #56367, PR #56215 (Mono), PR #56387, PR #56430
7/28 | PR #56463

```
System.NullReferenceException : Object reference not set to an instance of an object.

   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.ConnectAsync(CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicConnection.cs:line 603
   at System.Net.Quic.QuicConnection.ConnectAsync(CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 68
   at System.Net.Quic.Tests.MsQuicTests.ConnectWithCertificateForDifferentName_Throws() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs:line 270
--- End of stack trace from previous location ---
```

**Comment by CarnaViire** [comment] 2021-07-28 10:16
I guess the root cause is the same as in https://github.com/dotnet/runtime/issues/56263 and it will most possibly be fixed in https://github.com/dotnet/runtime/pull/56283

**Comment by karelz** [comment] 2021-07-28 10:18
@CarnaViire it is weird that it started failing few days later than the related issue #56263.
I will rather disable it now and we can re-enable and retest once the PR is merged. What do you think?

**Comment by CarnaViire** [comment] 2021-07-28 12:08
> I will rather disable it now and we can re-enable and retest once the PR is merged

Sure. I just commented so we wouldn't forget about it

**Comment by karelz** [comment] 2021-07-28 13:39
Test disabled by PR #56456 on 7/28.

**Closed** 2021-07-29 05:02 UTC
Labels: area-System.Net.Quic, disabled-test, test-run-core
