### ISSUE TITLE
Loss of scoped lifetime service instances when resolving HttpClient services configured through IServiceCollection.AddHttpClient(...)

### ISSUE THREAD

**Issue by BoricuaEnLaLuna** [dotnet/runtime#42142] opened 2019-12-27 07:08 UTC
# Issue description

Hi, it seems there is an issue that causes scoped lifetime service instances to be lost (and potentially re-instantiated within the same request/scope). This is completely the opposite of what one would intend when setting up a service with scoped lifetime and can cause bugs that are really cryptic to figure out (especially since the behavior can vary depending on the order in which services are defined in the constructors of the services they are injected into). 

This seems to happen only when resolving services that are setup as "http clients" following the instructions in the following documentation: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.2

This is a bit tedious to explain, but Ill try my best here. I am using Azure Functions V2 (.Net Core 2.2 & Microsoft.Extensions.Http 2.2.0). For the purposes of the following scenarios assume I have the following:

```c#
    public class Functions
    {
        private readonly IScoped1 scoped1;
        public Functions(IScoped1 scoped1)
        {
            this.scoped1 = scoped1;
        }
        [FunctionName("Function1")]
        public async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequest req,
            ILogger log)
        {
            log.LogInformation("C# HTTP trigger function processed a request.");
            return new OkObjectResult($"Hello");
        }
    }
    public interface IScoped1 { }
    public class Scoped1 : IScoped1
    {
        private readonly IScoped2 scoped2;
        private readonly IHttpClient1 httpClient1;
        private readonly IHttpClient2 httpClient2;
        public Scoped1(IScoped2 scoped2, IHttpClient1 httpClient1, IHttpClient2 httpClient2)
        {
            Console.WriteLine($"{this.GetType().Name}()");
            this.scoped2 = scoped2;
            this.httpClient1 = httpClient1;
            this.httpClient2 = httpClient2;
        }
    }

    public interface IScoped2 { }
    public class Scoped2 : IScoped2
    {
        public Scoped2()
        {
            Console.WriteLine($"{this.GetType().Name}()");
        }
    }

    public interface IHttpClient1 { }
    public class HttpClient1 : IHttpClient1
    {
        private readonly HttpClient httpClient;
        private readonly IScoped2 scoped2;
        public HttpClient1(HttpClient httpClient, IScoped2 scoped2)
        {
            Console.WriteLine($"{this.GetType().Name}()");
            this.httpClient = httpClient;
            this.scoped2 = scoped2;
        }
    }

    public interface IHttpClient2 { }
    public class HttpClient2 : IHttpClient2
    {
        private readonly HttpClient httpClient;
        private readonly IScoped2 scoped2;
        public HttpClient2(HttpClient httpClient, IScoped2 scoped2)
        {
            Console.WriteLine($"{this.GetType().Name}()");
            this.httpClient = httpClient;
            this.scoped2 = scoped2;
        }
    }
```

**Scenario 1: If NOT using AddHttpClient the scoped lifetimes work as expected.**

In this case I setup my http client services as simple Transients:

```c#
            builder.Services.AddScoped<IScoped1, Scoped1>();
            builder.Services.AddScoped<IScoped2, Scoped2>();
            builder.Services.AddTransient<IHttpClient1, HttpClient1>();
            builder.Services.AddTransient<IHttpClient2, HttpClient2>();
```

With this setup when I call the "Function1" httptrigger through POSTMAN I see the expected sequence of service instantiations:

1. Scoped2()
2. HttpClient1()
3. HttpClient2()
4. Scoped1()

**Scenario 2: If using AddHttpClient then scoped lifetime services can be instantiated more than once per request.**

In this case I setup my http client services with AddHttpClient following the documentation I referenced above:

```c#
            builder.Services.AddScoped<IScoped1, Scoped1>();
            builder.Services.AddScoped<IScoped2, Scoped2>();
            builder.Services.AddHttpClient<IHttpClient1, HttpClient1>();
            builder.Services.AddHttpClient<IHttpClient2, HttpClient2>();
```

With this setup when I call the "Function1" httptrigger through POSTMAN I see the unexpected re-instantiations of class Scoped2:

1. Scoped2()
2. Scoped2() --> This should be reusing the previous instantation of Scoped2
3. HttpClient1()
4. Scoped2() --> This should be reusing the previous instantation of Scoped2
5. HttpClient2()
6. Scoped1()

Additional to this example if I switch around the order of the parameters in the constructor of class "Scoped1" I also see different unexpected instantiation sequences. After playing around with this for a while I believe what is happening is that each time an "http client" service is resolved for the very first time in the lifetime of a request, it seems to clear any services that may have already been resolved in the scoped lifetime up to that point. However if that same service is resolved a 2nd+ time (within the same request lifetime) then it no longer seems to clear the scoped lifetime services.

Is this a known issue or am I misunderstanding something?
Thanks

# Software versions

Check the .NET target framework(s) being used, and include the version number(s).

- [X] .NET Core (v2.2) through Azure Functions V2
- [ ] .NET Framework
- [ ] .NET Standard

If using the .NET Core SDK, include `dotnet --info` output. If using .NET Framework without the .NET Core SDK, include info from Visual Studio's **Help** > **About Microsoft Visual Studio** dialog.

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by ericstj** [comment] 2020-09-14 18:28
Ping @dotnet/ncl @karelz

**Comment by DillonN** [comment] 2020-12-03 07:16
Maybe another perspective would help, if you consider this service registration:

```csharp
services.AddHttpClient<MyClient>(ConfigureClient).AddHttpMessageHandler(CreateHandler);

DelegatingHandler CreateHandler(IServiceProvider sp)
{
    // Something where scope of sp is important
}

void ConfigureClient(HttpClient client) { ... }
```

Since `MyClient` is registered as transient, I would expect this to work. I.e. I would expect the scope of `sp` in `CreateHandler` to be the same as where `MyClient` is being resolved from

But this doesn't work because `DefaultHttpClientFactory` is managing the `IServiceProvider` and it's a singleton:

https://github.com/dotnet/runtime/blob/f9004fe53b16abb45b846ad6fc8c02de465aef01/src/libraries/Microsoft.Extensions.Http/src/DefaultHttpClientFactory.cs#L153-L166

So instead you're forced to workaround by basically replacing `AddHttpClient<T>` and `DefaultHttpClientFactory.CreateClient`, something along the lines of:

```csharp
services.AddHttpClient();
services.AddTransient<MyClient>(sp =>
{
    var messageHandlerFactory = sp.GetRequiredService<IHttpMessageHandlerFactory>();
    var clientFactory = sp.GetRequiredService<ITypedHttpClientFactory<MyClient>>();

    var factoryHandler = messageHandlerFactory.CreateHandler();
    var fullHandler = CreateHandler(sp);
    fullHandler.InnerHandler = factoryHandler;

    var httpClient = new HttpClient(fullHandler, disposeHandler: false);
    ConfigureClient(httpClient);

    return clientFactory.CreateClient(httpClient);
}
```

Which is not ideal for many reasons. 

I see a couple possible solutions for this, but unfortunately nothing non-breaking.. One way though could be to add an overload to `IHttpClientFactory.CreateClient(string)` that also takes an `IServiceProvider` so one could be passed down. Another would be registering `DefaultHttpClientFactory` as transient and moving the pooling stuff to a separate singleton service

But then you get into a more fundamental problem. Since the main point of `DefaultHttpClientFactory` is to pool and reuse handlers across scopes, having them always be built from the resolving scope definitely can't be guaranteed. Maybe that's when relying on the `SocketsHttpHandler` feature makes a lot of sense (#35987)

**Comment by CarnaViire** [comment] 2021-02-01 15:23
Triage: Reproduces on Azure Functions environment, doesn't reproduce on .NET Core Generic Host. Next step: try ASP.NET Core environment

**Comment by CarnaViire** [comment] 2021-02-02 19:49
I discovered that by default Azure Functions work with DI scopes in a non-"conventional" way: creating a new scope "hides" an existing scope until that new scope is disposed. That is why the behavior described in this issue is only reproducible in Azure Functions environment. `HttpClientFactory` implementation relies on the fact that any number of scopes can exist and not interfere with each other, and that is true for both ASP.NET and .NET Generic Host.

There is actually a tracking issue for that https://github.com/Azure/azure-functions-host/issues/5098
In this issue, it is advised to use feature flag if you want to get a "conventional" behavior for scopes:
`"AzureWebJobsFeatureFlags": "EnableEnhancedScopes"`

Please let me know if adding this feature flag solved the problem @BoricuaEnLaLuna

**Comment by CarnaViire** [comment] 2021-02-04 12:19
Closing as answered above

**Closed by CarnaViire** 2021-02-04 12:19 UTC
Labels: area-Extensions-HttpClientFactory
