### ISSUE TITLE
[API Proposal]: Allow setting explicit packing for 32 bit platforms only.

### ISSUE THREAD

**Issue by JeremyKuhne** [dotnet/runtime#95802] opened 2023-12-08 20:10 UTC
### Background and motivation

In Win32 there are a number of headers that are set for single byte packing on 32 bit (notably in the shell). The 64 bit definitions use default packing in all of the cases I know of. This creates a problem for defining structs for interop when building for AnyCPU (as WinForms does). We either have to define twice or, in some cases, just ignore the packing as things align on the same boundaries they would with default 32 bit packing (which has risk if one nests struct definitions).

This is blocking us from directly utilizing the published Win32 metadata (through CsWin32) in these cases. If we could specify the packing for 32 bit we would be able to safely generate Win32 interop methods.

I believe this would require a change to the CLI and the runtime / JIT. My naive idea is that if the first byte of `PackingSize` is specified it would be the 32 bit specific packing and the second byte would be "normal" packing (as the spec limits the packing to a max of 128).

### API Proposal

```csharp
namespace System.Runtime.InteropServices;

public sealed class StructLayoutAttribute : Attribute
{
    // Added (value is shifted into the high byte in metadata)
    public int Pack32BitPlatform;
}
```

### API Usage

```csharp
[StructLayout(LayoutKind.Sequential, Pack32BitPlatform = 1)]
public partial struct PRINTDLGW
{
   // ...
}
```

### Alternative Designs

Perhaps introducing another attribute? `StructLayout32Attribute`?

**Comment by tannergooding** [comment] 2023-12-08 23:43
> Perhaps introducing another attribute? StructLayout32Attribute?

I expect this would be required, `StructLayout` is a "magic" attribute that has special metadata encoding.

I expect that just `StructLayout32` would also not be sufficient. Win32 has some ARM specific packing, some 32-bit specific packing, some 64-bit specific packing, etc. So I would push us towards ensuring any "new" thing could sufficiently handle the nuances of this and allow valid CPU/OS combinations as needed.

**Comment by MichalPetryka** [comment] 2023-12-08 23:49
I'd think that some `PlatformLayout(SystemRuntimeIntrinsics.Architecture)` would make the most sense and would allow overriding every element of layout (I guess for explicit layouts we'd need `PlatformOffset` too).

The issue would be that checking this custom attribute could be expensive for the type loader, but I guess it could be worked around by using the currently free LayoutKind value of 1 to be `encoded in custom attributes` which would make the VM only check them in such rare cases. In such case "transparent layout` could be also encoded as a custom attribute if there'd be a decision to add it.

**Comment by jkotas** [comment] 2023-12-09 01:58
Duplicate of https://github.com/dotnet/runtime/issues/60573

**Comment by am11** [comment] 2023-12-09 09:09
> We either have to define twice

Or as many times as needed. Statically generating all the required variants of struct at build-time is laborious (can be source generated) but less intense than the full Reflection.Emit alternative. Conditions based on APIs like `OS.IsWindows()`, `RuntimeInformation.ProcessArchitecture == Architecture.X86` and `Environment.Is64BitProcess` are pretty cheap, AOT friendly and can be used to avoid the reflection stack.

**Comment by AaronRobinsonMSFT** [comment] 2024-01-02 22:48
Closing as duplicate.

**Closed by AaronRobinsonMSFT** 2024-01-02 22:48 UTC
Labels: api-suggestion, area-Interop-coreclr, untriaged
