### ISSUE TITLE
SocketInformation is not marked as serializable

### ISSUE THREAD

**Issue by scalablecory** [dotnet/runtime#34596] opened 2020-04-06 16:13 UTC
_From @soyang2828 on Friday, February 21, 2020 8:12:06 AM_

Now we have DuplicateAndClone() supported (https://github.com/dotnet/runtime/issues/1760)
But the entire scenario would be needing to serialize SocketInformation to another process.
So should SocketInformation marked as serializable?

_Copied from original issue: microsoft/dotnet#1176_

**Comment by GrabYourPitchforks** [comment] 2020-04-06 16:22
\<security-hat\>
There's nothing inherently dangerous about this type that would prevent slapping `[Serializable]` on it. But we __really__ don't want to be in a world where we're encouraging developers to take further dependencies on `BinaryFormatter`. Encouraging our developer audience to make further use of that type is a recipe for disaster.

It's 2020. At this point we've been saying for almost a decade that people need to stop using that API.
\</security-hat\>

**Comment by soyang2828** [comment] 2020-04-06 16:39
@GrabYourPitchforks , I will take it as an answer.

**Comment by GrabYourPitchforks** [comment] 2020-04-06 17:09
Ultimately the decision is in the hands of the larger product team. I am but one member voicing an opinion. :)

**Comment by danmosemsft** [comment] 2020-04-06 17:57
We don't plan to mark more types as `[Serializable]`. @soyang2828 can you accmoplish your goal some other way?

**Comment by soyang2828** [comment] 2020-04-06 18:05
We will move to protobuf after this is confirmed that it's not going to be supported.

**Comment by scalablecory** [comment] 2020-04-06 19:06
The original Framework type was marked serializable, so we might do it if there's an important compat scenario missing. I suspect the `DuplicateAndClose` method is used pretty rarely though. It seems like any serializer that works with public properties will work just fine here -- like System.Text.Json.

**Comment by GrabYourPitchforks** [comment] 2020-04-06 21:29
If you need to transmit a `SocketInformation` struct across a process boundary, there's no need to involve any type of serializer at all. BinaryFormatter, protobuf, even JSON are all very heavyweight solutions to this problem.

Since the struct is just two fields it can be smuggled easily as a single string, as shown below.

```cs
public static string Serialize(SocketInformation si)
{
    return $"{si.Options}:{Convert.ToBase64String(si.ProtocolInformation)}";
}

public static SocketInformation Deserialize(string serialized)
{
    string[] split = serialized.split(':');
    return new SocketInformation
    {
        Options = Enum.Parse<SocketInformationOptions>(split[0]),
        ProtocolInformation = Convert.FromBase64String(split[1])
    };
}
```

**Comment by antonfirsov** [comment] 2020-04-22 22:34
I left out `[Serializable]` intentionally from #1858 (also mentioned it in the PR).

We have a bunch of types which are `[Serializable]` in Framework, but are no longer marked as such in .NET Core (eg. `System.Net.IPEndPoint`), while other types (like `System.Net.Cookie`) seem to be `[Serializable]`.

I don't think the problem is specific to `SocketInformation`, we need a consistent rule for marking/not marking types.

**Comment by stephentoub** [comment] 2020-04-22 22:50
> we need to make a decision whether we want to mark all "old" types for compatibility. I guess we don't.

The decision has been made. We are not making such types serializable. Other than for Exceptions, we plan to not mark anything else [Serializable].

Thanks for the discussion.

**Closed by stephentoub** 2020-04-22 22:50 UTC
Labels: area-System.Net.Sockets, untriaged
