### ISSUE TITLE
`int.Parse()` invalid results on x86_64/Android: RadioButton with ControlTemplate crashes on Android in the release mode

### ISSUE THREAD

**Issue by holecekp** [dotnet/runtime#104245] opened 2024-06-23 10:31 UTC
### Description

If RadioButton uses a ControlTemplate, it works on Android in the debug mode. However, running the app in the release mode causes an instant crash when the page with the RadioButtons is displayed.

The crash is caused in the following following exception in MAUI:
```System.FormatException: Format_InvalidStringWithOffsetAndReason, ??????????????11, Format_ExpectedAsciiDigit"``` at RadioButton.ContentAsString(). I am 

I am including the full Logcat log (I needed to rename the extension of the file to ".json" because uploading ".logcat" files is not supported here.
[MauiRadioButtonCrash.json](https://github.com/user-attachments/files/15944020/MauiRadioButtonCrash.json)

I am including a repro project wich is a simple combination of a new MAUI app using the standard VS template and the XAML for radion buttons from the demo project linked from the official MAUI documantation on RadioButtons.

The issue is somehow similar to https://github.com/dotnet/maui/issues/22377, however in that issue the problem is for iOS only and it is caused by setting the control template for all RadioButtons from styles. There is a workaround - to set the ContentTemplate for each of the RadionButtons directly without a style. Howevere, this workaroud does not work for my issue so I assime they are different (this one is more severe because there is no workaround).

I have tried to update from MAUI 8.0.40 used in the default VS template to the latest 8.0.60 and it did not help. The app still crashes, just this time the same crash is reported in the FontManager.

### Steps to Reproduce

1. Clone the repository https://github.com/holecekp/MauiBugsRadioButton
2. Run the app on Android emulator in the debug mode. You can see that it works.
3. Switch to the Release mode and press Ctrl+F5 to run the app in the release mode. A splash screen is displayed for a fraction of second and then the app crashes.

### Link to public reproduction project repository

https://github.com/holecekp/MauiBugsRadioButton

### Version with bug

8.0.40 SR5

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Tested on Android 14 emulator

### Did you find any workaround?

No workaround. The only way is to use RadioButtons with a simple string without any ControlTemplate.

### Relevant log output

```shell
Logcat shows an exception:

android.runtime.JavaProxyThrowable: System.FormatException: Format_InvalidStringWithOffsetAndReason, ??????????????11, Format_ExpectedAsciiDigit"
              at System.Text.CompositeFormat.Parse(String )
at Microsoft.Extensions.Logging.LogValuesFormatter..ctor(String )                                                                                                       ...
at Microsoft.Maui.Controls.RadioButton.ContentAsString()
Microsoft.Maui.Controls.RadioButton.UpdateSemantics()                                                                                                      
at Microsoft.Maui.Controls.VisualElement.Microsoft.Maui.IView.get_Semantics()
at Microsoft.Maui.Handlers.ViewHandler.MappingSemantics(IViewHandler handler, IView view)
at Microsoft.Maui.Handlers.ViewHandler.MapSemantics(IViewHandler handler, IView view)
...
```

**Comment by tannergooding** [comment] 2024-07-02 14:54
@holecekp, could you share what those unknown Unicode characters are?

Given this is `int.ToString()` on x64, I imagine many other apps would be seeing failing scenarios if it were a problem with the core code or RyuJIT. Just `int.ToString()` is itself relatively simplistic and there's not many opportunities it could get messed up

Given Mono has a `SmallNumberCacheLength` of 10, compared to RyuJIT's 300, and the failure includes `12` and `200`; I'd guess the issue is rather in `UInt32ToDecStr_NoSmallNumberCheck`, in which case the most likely issue is in whatever Mono is producing from `FormattingHelpers.CountDigits`. If you were able to debug and breakpoint, my guess is you'd see that its returning some too large value.

This could be representative of an emulator bug or maybe some intrinsic getting mishandled on the Mono side.

**Comment by holecekp** [comment] 2024-07-03 18:26
The extra characters have ASCII code 0. I did another test with numbers with various number of digits. I am including the result returned by int.ToString() method (the length of the resulting string and the ASCII codes of the individual characters in it:
- **0**: Length 10. Characters: 0,0,0,0,0,0,0,0,0,48
- **10**: Length 9. Characters: 0,0,0,0,0,0,0,49,48
- **100**: Length 8. Characters: 0,0,0,0,0,49,48,48
- **1000**: Length 7. Characters: 0,0,0,49,48,48,48
- **10000**: Length 6. Characters: 0,49,48,48,48,48
- **100000**: Length 6. Characters: 49,48,48,48,48,48
- **1000000**: App crashes: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7de484800000 in tid 3227 (bugsradiobutton), pid 3227 (bugsradiobutton)

Other numeric types have similar problem. I have tested byte.ToString() values 0, 10, 100 and it returns string of length 10, 9, 8.  

Long.ToString() behaves in a similar way. In case of 0 it returns the same result as int.ToString() and byte.ToString(). For higher numbers 10, 100, 1000, ... the resulting strings have lengths 18, 17, 16, ... With each correct digit added, two unwanted ASCII 0 characters are removed from the beginning of the string.

The problem is in MAUI in the Release mode only and only if it runs on x86_64 processor architecture emulator. The same code runs well in Debug mode on the same emulator. It runs well also in the Release mode but on x86 emulator. Moreover, I have tested that this is specific to MAUI. The same code in Xamarin.Forms project gives the correct results also in the Release mode on the problematic emulator where the same code placed in MAUI project have the issue.

**Comment by tannergooding** [comment] 2024-07-10 18:31
Moving this to Mono as it doesn't reproduce on RyuJIT. It appears to be unique to Mono

**Comment by lambdageek** [comment] 2024-07-10 19:44
Doesn't repro with and arm64 android emulator.

Doesn't repro with a mono x86-64 console app (on an osx-arm64 mac via rosetta, anyway):

```csharp
public class Program
{
    public static unsafe void Main()
    {
        int i = 200;
        Foo(i.ToString(), "200");
    }

    public static void Foo (string s, string e)
    {
        Console.WriteLine (s.Length);
        Console.WriteLine (s == e ? "ok" : "unequal");
        for (int i = 0; i < s.Length; i++)
        {
            int n = (int)s[i];
            Console.WriteLine ($"{i}: 0x{n:x8}");
        }
    }
}
```

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup Condition="true">
    <SelfContained>true</SelfContained>
    <UseMonoRuntime>true</UseMonoRuntime>
  </PropertyGroup>

</Project>
```

---

setting up an x86-64 android emulator...

**Comment by lambdageek** [comment] 2024-07-11 15:42
@holecekp I can't reproduce this with .NET 8.0.7 

What I did:

1. using VS 17.11 Preview 3
2. installed the 8.0.303 SDK from https://get.dot.net/
3. `dotnet workload install maui`
4. opened https://github.com/holecekp/MauiBugsRadioButton/tree/5IntParse
5. setup a "Pixel 5 - API 34 (Android 14.0 - API 34)" x86-64 emulator
6. select Release configuration
7. Ctrl-F5

App labels show "OK" 3 times

**Comment by holecekp** [comment] 2024-07-11 21:17
Thank you for trying to reproduce the isssue. It is a mistery for me why the issue is on my computer only. I have updated everything in the meanwhile (latest VS preview 3, latest MAUI 8.0.70). Still the issue is there. I had a lot of old dotnet SDKs installed (.NET 6, .NET 5). I have unistalled them but this also had no effect on the issue.

I have also tried to uncheck Optimize code checkbox in the project properties for the Release version to make it more similar to Debug version, which works. Unfortunatelly, this did not solved the issue either.

I have created APK and I will try it tommorow on an x86_64 emulator on a different computer so that I would know if the problem is really in the APK created by VS, or if it just an emulator issue.

**Comment by tannergooding** [comment] 2024-07-11 21:33
Are you running on an i7-i9 13000 series Intel processor?

**Comment by tannergooding** [comment] 2024-07-11 21:35
If so, you might be encountering https://community.intel.com/t5/Processors/June-2024-Guidance-regarding-Intel-Core-13th-and-14th-Gen-K-KF/m-p/1607807 and may see it fixed by updating your bios, which should acquire the latest microcode patches

**Comment by holecekp** [comment] 2024-07-13 15:16
Thank you for the investigation of the issue and for the suggestion what could cause it. The processor in the the computer with the issue is however older (i5-3470). The issue is also completely deterministic. The result is the same every time. If the issue would be caused by processor instabilities I would expect that the behavior would be probably more random.

I have found something interesting. I have created an APK for the repro project. When I install it and run it in the x86_64 emulator manually (drag&drop in the Android Studio] on my computer, there is the mentioned issue. However, when I install and run the same APK on a different computer (12th Gen Intel  Core i7-1260P) on an emulator with the same configuration, it works correctly.  So it seems that the problem could be in the emulator on my computer (however everything should be up-to-date, I have installed all available updates in the Android SDK Manager).

**Comment by steveisok** [comment] 2024-07-24 16:48
@holecekp since we are unable to reproduce, there's not a lot of action we can take. As a result, I'm going to close the issue. If you have any extra info that would help, please feel free to comment and reopen the issue.

**Closed by steveisok** 2024-07-24 16:48 UTC
Labels: area-Codegen-meta-mono, needs-further-triage
