### ISSUE TITLE
System.Net.Sockets.Tests.DualModeAcceptAsync.AcceptAsyncV4BoundToSpecificV6_CantConnect test failed in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#31231] opened 2019-10-20 22:52 UTC
https://dnceng.visualstudio.com/public/_build/results?buildId=393221&view=ms.vss-test-web.build-test-results-tab&runId=12222448&resultId=177679&paneView=debug

Configuration: `netcoreapp-Windows_NT-Release-x86-Windows.10.Amd64.Client19H1.Open`

```
Assert.Throws() Failure\r\nExpected: typeof(System.Net.Sockets.SocketException)\r\nActual: typeof(System.TimeoutException): Timed out while waiting for either of client and server connections...\r\n---- System.TimeoutException : Timed out while waiting for either of client and server connections...
 at System.Net.Sockets.Tests.DualModeAcceptAsync.DualModeConnect_AcceptAsync_Helper(IPAddress listenOn, IPAddress connectTo) in /_/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 973
   at System.Net.Sockets.Tests.DualModeAcceptAsync.<AcceptAsyncV4BoundToSpecificV6_CantConnect>b__5_0() in /_/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 924
----- Inner Stack Trace -----
   at System.Net.Sockets.Tests.DualModeAcceptAsync.DualModeConnect_AcceptAsync_Helper(IPAddress listenOn, IPAddress connectTo) in /_/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 973
   at System.Net.Sockets.Tests.DualModeAcceptAsync.<AcceptAsyncV4BoundToSpecificV6_CantConnect>b__5_0() in /_/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 924
```

cc @davidsh, @wfurt, @scalablecory, @eiriktsarpalis, @karelz

**Comment by karelz** [comment] 2020-04-03 22:26
Duplicate of #22620

**Closed by karelz** 2020-04-03 22:26 UTC
Labels: area-System.Net.Sockets, test bug, test-run-core
