### ISSUE TITLE
[Perf -35%] System.Threading.Tests.Perf_Thread.GetCurrentProcessorId

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#37804] opened 2020-06-12 17:33 UTC
### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Changes | [diff](https://github.com/dotnet/installer/compare/a4a49f07fbf986d496ef57521e76b22caaf9bfb3...ccd701fe23f236755650af3ce3d9ab6bdd8a4af9)

### Regressions in System.Threading.Tests.Perf_Thread

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier
-- | -- | -- | -- | -- | --
GetCurrentProcessorId | 4.26 ns | 5.74 ns | 1.35 |  | False

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/06_11_2020/Windows%2010.0.18362_x64/System.Threading.Tests.Perf_Thread_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/06_11_2020/Windows%2010.0.18362_x64/System.Threading.Tests.Perf_Thread.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Threading.Tests.Perf_Thread*';
```
<details>

#### System.Threading.Tests.Perf_Thread.GetCurrentProcessorId

```log
[3.832 ; 4.527) | @@@@
[4.527 ; 5.222) | 
[5.222 ; 6.112) | @@@@@@@@@@@@@@@
[6.112 ; 6.602) | @@@
[6.602 ; 6.862) | 
[6.862 ; 7.557) | @
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by DrewScoggins** [comment] 2020-06-12 17:33
@adamsitnik @VSadov

**Comment by VSadov** [comment] 2020-06-12 19:30
`GetCurrentProcessorId` was "fast" previously because of aggressive caching. It would return the same result for 3000 invocations (or was it 50000 invocations?, i do not remember..)

Since the threads can move between cores, long caching diminishes the value of this API. We saw problems with that.
However there are machines/OSs/hypervisors where underlying implementation is very slow (on order of 1000x slower than fast systems) and such caching could be the only way to not make this API an occasional perf trap.

The change was to measure the underlying implementation and adjust caching accordingly.
The goal was to improve precision on systems where it is possible, while not regressing hopelessly on older/slower systems. 

Since, I assume you have a relatively modern system, the former performance of this API was basically measuring access to a thread local. Not much real work was happening comparatively.

35% is acceptable regression in this case. The calibration expects that "working" implementation will be a bit more expensive than just fetching a value from TLS. 

3x-5x regression would be alarming. It would mean our measurements are off.

**Comment by mangod9** [comment] 2020-07-22 18:47
Closing based on analysis above.

**Closed by mangod9** 2020-07-22 18:47 UTC
Labels: area-System.Threading
