### ISSUE TITLE
Breaking change with timeout reading serial port in .NET 7 (Possible Overlapped I/O change)

### ISSUE THREAD

**Issue by dementedmonkey** [dotnet/runtime#80079] opened 2022-12-31 08:29 UTC
### Description

In .NET 6 and earlier, when `System.IO.Ports.SerialPort.Read` times out, it will throw a `TimeoutException`.   In .NET 7, it will throw an `IOException` with an HResult of 0x800705B4 (1460: ERROR_TIMEOUT)

### Reproduction Steps

Use the following code (substitute your own valid serial port values)
* VS2022 or .NET 7 SDK on Windows.
* Nuget Reference to `System.IO.Ports` version 7.0.0 (OK with eariler versions too)
* Target `net7.0` to see it fail, or `net6.0` to see it work.

```
using System;
using System.IO;
using System.IO.Ports;

class Program
{
    static void Main()
    {
        var serialPort = new SerialPort("COM42", 115200, Parity.None, 8, StopBits.One)
        {
            DtrEnable = false,
            WriteTimeout = 500,
            ReadTimeout = 500,
        };
        serialPort.Open();
        var data = new byte[100];
        try
        {
            var numRead = serialPort.Read(data, 0, data.Length);
            Console.WriteLine("Read {0}", numRead);
        }
        catch (TimeoutException)
        {
            Console.WriteLine(".NET <=6 Timed out");
        }
        catch (IOException e)
        {
            Console.WriteLine(".NET 7: IO {0}  HR:0x{1:X}", e.HResult & 0xFFFF, e.HResult);
        }
    }
}
```

### Expected behavior

Output of `.NET <=6 Timed out`

### Actual behavior

Output of  `.NET 7: IO 1460  HR:0x800705B4`

### Regression?

Yes.   Worked for .NET 6 and 5.

You can easily test this but switching target framework.  If you switch to .NET 6 you get the `TimeoutException`, if you switch to .NET 7 you get the `IOException`

### Known Workarounds

Code catching the `TimeoutException` would have to catch the `IOException` check the HResult and handle it the same way.

### Configuration

.net 7.0.101 Windows 11, Target X64 or x86 has the problem.  
Debug or release doesn't seem to matter.

Ubuntu WSL2 with 7.0.101 does _not_ have the problem.

### Other information

This seems to be caused by changed in overlapped IO introduced in .net7

The difference can be observed here:  
https://github.com/dotnet/runtime/blob/d099f075e45d2aa6007a22b71b45a08758559f80/src/libraries/System.IO.Ports/src/System/IO/Ports/SerialStream.Windows.cs#L1505  
On .net6, the errorCode is 0, on .net7 it's 1460

The call stack invoking this function is very different on .net 6 and 7.

On .net7, `AsyncFSCallback` is getttiong called from `PortableThreadPool` and the error is set here:
https://github.com/dotnet/runtime/blob/d099f075e45d2aa6007a22b71b45a08758559f80/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.IO.Windows.cs#L262

On .net6, it's getting called from `_IOCompletionCallback.PerformIOCompletionCallback`  The stack stops there, and I didn't dig any deeper to see where it's getting its parameters from.

**Comment by krwq** [comment] 2023-01-13 13:08
See workaround for this issue in https://github.com/dotnet/runtime/issues/78319 (note it was closed as dup since this one has more details)

**Comment by AlquistArj** [comment] 2023-01-18 11:21
I also have this issue with .NET 7 serial port code (it used to work in .NET 4.8).

**Comment by hugo-lyppens** [comment] 2023-01-23 19:09
What is the ETA for the fix? Is it just going to be a new https://nuget.info/packages/System.IO.Ports/7.0.0 or a .NET 7 fix?

**Comment by krwq** [comment] 2023-01-24 14:14
@hugo-lyppens I can't promise anything specific to a timeline.

I couldn't pinpoint any specific change which could have regressed this so I've done some sanity testing and here are my findings:

| Target Framework | System.IO.Ports version | Exception |
| --- | --- | --- |
| 6.0 | 6.0 | TimeoutException |
| 6.0 | 7.0 | TimeoutException |
| 7.0 | 6.0 | IOException |
| 7.0 | 7.0 | IOException |

Given above this doesn't look like regression was in System.IO.Ports and was likely somewhere on System.IO layer.
I'm not sure if change in System.IO was intentional or not and if we should try to workaround it in System.IO.Ports.

@dotnet/area-system-io will need to take a look and from there we can decide on the next steps

**Comment by jkotas** [comment] 2023-01-24 14:45
This is likely caused by a switch to portable thread pool. cc @kouvel

**Comment by kouvel** [comment] 2023-02-07 06:26
The `NTSTATUS` value from the IO completion is 258 (`WAIT_TIMEOUT`). In .NET 6 `GetQueuedCompletionStatus` treats that value as a success. In .NET 7 the value is incorrectly treated and reported as an error by the portable thread pool, leading to a different exception.

A workaround is to set the environment variable `DOTNET_ThreadPool_UsePortableThreadPoolForIO=0` before starting the app.

I have put up PRs for fixes in https://github.com/dotnet/runtime/pull/81744 (main) and https://github.com/dotnet/runtime/pull/81745 (7.0).

**Comment by kouvel** [comment] 2023-02-07 06:40
> What is the ETA for the fix? Is it just going to be a new https://nuget.info/packages/System.IO.Ports/7.0.0 or a .NET 7 fix?

It's a .NET 7 runtime fix. If the 7.0 PR is approved it'll be marked with a milestone indicating the runtime version that would include the fix.

**Closed** 2023-02-15 18:57 UTC
Labels: bug, area-System.Threading, regression-from-last-release, in-pr
