### ISSUE TITLE
simpleprovidervalidation test failed with `Process is not supported on this platform.`

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#81897] opened 2023-02-09 16:12 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=164331
Build error leg or test failing: tracing/eventpipe/simpleprovidervalidation/simpleprovidervalidation/simpleprovidervalidation.sh
Pull request: https://github.com/dotnet/runtime/pull/81831

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

runtime (Build browser-wasm linux Release AllSubsets_Mono_RuntimeTests monointerpreter) 
Mono browser wasm Release @ Ubuntu.1804.Amd64.Open

```
          0.0s: ==TEST STARTING==
          0.1s: System.PlatformNotSupportedException: System.Diagnostics.Process is not supported on this platform.
           at System.Diagnostics.Process.GetProcesses()
           at Tracing.Tests.Common.IpcTraceTest.<>c.<EnsureCleanEnvironment>b__10_0()
           at Tracing.Tests.Common.IpcTraceTest.EnsureCleanEnvironment()
           at Tracing.Tests.Common.IpcTraceTest.Validate(Boolean enableRundownProvider)
           at Tracing.Tests.Common.IpcTraceTest.RunAndValidateEventCounts(Dictionary`2 expectedEventCounts, Action eventGeneratingAction, List`1 providers, Int32 circularBufferMB, Func`2 optionalTraceValidator, Boolean enableRundownProvider)
          0.1s: ==TEST FINISHED: FAILED!==
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by radical** [comment] 2023-02-09 17:23
the linked build didn't include the fix. Closing as duplicate of https://github.com/dotnet/runtime/issues/81859 .

**Closed by radical** 2023-02-09 17:23 UTC
Labels: blocking-clean-ci, untriaged, area-Codegen-Interpreter-mono, Known Build Error
