### ISSUE TITLE
CI test failure: System.IO.FileSystem.Tests

### ISSUE THREAD

**Issue by layomia** [dotnet/runtime#35743] opened 2020-05-02 06:17 UTC
Encountered in https://github.com/dotnet/runtime/pull/35700.

Libraries Test Run release coreclr Windows_NT x86 Release failed

Azure pipelines URL: https://dev.azure.com/dnceng/public/_build/results?buildId=627684&view=logs&jobId=85312bf4-08bc-52d1-d0fc-b5f2255cc3aa&j=85312bf4-08bc-52d1-d0fc-b5f2255cc3aa&t=361fd1e3-c164-5be7-cbf1-ec0d6b8f4a50

Failure log: https://helix.dot.net/api/2019-06-17/jobs/10395141-596e-4cc7-be25-344dcb332af8/workitems/System.IO.FileSystem.Tests/console

**Comment by jkotas** [comment] 2020-05-02 09:14
```
      		Thread #2 (OS 0x16E4) [Finalizer] [Background] [MTA]
      			[InlinedCallFrame]
      			System.Diagnostics.Tracing.EtwEventProvider.System.Diagnostics.Tracing.IEventProvider.EventUnregister(Int64)
      			System.Diagnostics.Tracing.EventProvider.Dispose(Boolean)
      			System.Diagnostics.Tracing.EventSource.Dispose(Boolean)
      			System.Diagnostics.Tracing.EventListener.DisposeOnShutdown(System.Object, System.EventArgs)
      			System.AppContext.OnProcessExit()
```

**Comment by jkotas** [comment] 2020-05-02 09:14
Duplicate of https://github.com/dotnet/runtime/issues/35451

**Closed by jkotas** 2020-05-02 09:14 UTC
Labels: area-System.IO, untriaged
