### ISSUE TITLE
Wasm debugger test timing out

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#83847] opened 2023-03-23 20:00 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=214012
Build error leg or test failing: chrome-DebuggerTests.SteppingTests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/83787

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "DXVAVDA fatal error: could not LoadLibrary: mf.dll: The specified module could not be found",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[228097](https://dev.azure.com/dnceng-public/public/_build/results?buildId=228097)|dotnet/runtime|[chrome-DebuggerTests.BreakpointTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=228097&view=ms.vss-test-web.build-test-results-tab&runId=4302578&resultId=100322)|dotnet/runtime#84335|
|[228059](https://dev.azure.com/dnceng-public/public/_build/results?buildId=228059)|dotnet/runtime|[chrome-DebuggerTests.BreakpointTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=228059&view=ms.vss-test-web.build-test-results-tab&runId=4301146&resultId=100322)|dotnet/runtime#84271|
|[228055](https://dev.azure.com/dnceng-public/public/_build/results?buildId=228055)|dotnet/runtime|[chrome-DebuggerTests.BreakpointTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=228055&view=ms.vss-test-web.build-test-results-tab&runId=4300628&resultId=100322)|dotnet/runtime#84273|
|[228042](https://dev.azure.com/dnceng-public/public/_build/results?buildId=228042)|dotnet/runtime|[chrome-DebuggerTests.BreakpointTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=228042&view=ms.vss-test-web.build-test-results-tab&runId=4300014&resultId=100322)|dotnet/runtime#74623|
|[228035](https://dev.azure.com/dnceng-public/public/_build/results?buildId=228035)|dotnet/runtime|[chrome-DebuggerTests.BreakpointTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=228035&view=ms.vss-test-web.build-test-results-tab&runId=4299844&resultId=100322)|dotnet/runtime#84329|
|[227981](https://dev.azure.com/dnceng-public/public/_build/results?buildId=227981)|dotnet/runtime|[chrome-DebuggerTests.BreakpointTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=227981&view=ms.vss-test-web.build-test-results-tab&runId=4298498&resultId=100322)|dotnet/runtime#84148|
|[227824](https://dev.azure.com/dnceng-public/public/_build/results?buildId=227824)|dotnet/runtime|[chrome-DebuggerTests.BreakpointTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=227824&view=ms.vss-test-web.build-test-results-tab&runId=4295158&resultId=100322)|dotnet/runtime#84170|
|[227763](https://dev.azure.com/dnceng-public/public/_build/results?buildId=227763)|dotnet/runtime|[chrome-DebuggerTests.BreakpointTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=227763&view=ms.vss-test-web.build-test-results-tab&runId=4293600&resultId=100321)||
|[227758](https://dev.azure.com/dnceng-public/public/_build/results?buildId=227758)|dotnet/runtime|[chrome-DebuggerTests.CallFunctionOnTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=227758&view=ms.vss-test-web.build-test-results-tab&runId=4293146&resultId=100322)||
|[227643](https://dev.azure.com/dnceng-public/public/_build/results?buildId=227643)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=227643&view=ms.vss-test-web.build-test-results-tab&runId=4290500&resultId=100322)|dotnet/runtime#84148|
|[227254](https://dev.azure.com/dnceng-public/public/_build/results?buildId=227254)|dotnet/runtime|[chrome-DebuggerTests.DelegateTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=227254&view=ms.vss-test-web.build-test-results-tab&runId=4279412&resultId=100322)|dotnet/runtime#84289|
|[227157](https://dev.azure.com/dnceng-public/public/_build/results?buildId=227157)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=227157&view=ms.vss-test-web.build-test-results-tab&runId=4275148&resultId=100322)||
|[226099](https://dev.azure.com/dnceng-public/public/_build/results?buildId=226099)|dotnet/runtime|[chrome-DebuggerTests.SteppingTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=226099&view=ms.vss-test-web.build-test-results-tab&runId=4274214&resultId=100322)|dotnet/runtime#84242|
|[226564](https://dev.azure.com/dnceng-public/public/_build/results?buildId=226564)|dotnet/runtime|[chrome-DebuggerTests.SteppingTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=226564&view=ms.vss-test-web.build-test-results-tab&runId=4260818&resultId=100322)|dotnet/runtime#84148|
|[226490](https://dev.azure.com/dnceng-public/public/_build/results?buildId=226490)|dotnet/runtime|[chrome-DebuggerTests.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=226490&view=ms.vss-test-web.build-test-results-tab&runId=4259708&resultId=100322)|dotnet/runtime#83461|
|[226452](https://dev.azure.com/dnceng-public/public/_build/results?buildId=226452)|dotnet/runtime|[DebuggerTests.EvaluateOnCallFrameTests.DebuggerTests.EvaluateOnCallFrameTests.EvaluateTypeInstanceMembers](https://dev.azure.com/dnceng-public/public/_build/results?buildId=226452&view=ms.vss-test-web.build-test-results-tab&runId=4259102&resultId=100243)|dotnet/runtime#82981|
|[226249](https://dev.azure.com/dnceng-public/public/_build/results?buildId=226249)|dotnet/runtime|[chrome-DebuggerTests.SteppingTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=226249&view=ms.vss-test-web.build-test-results-tab&runId=4255192&resultId=100322)|dotnet/runtime#82005|
|[226127](https://dev.azure.com/dnceng-public/public/_build/results?buildId=226127)|dotnet/runtime|[chrome-DebuggerTests.BreakpointTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=226127&view=ms.vss-test-web.build-test-results-tab&runId=4252832&resultId=100322)|dotnet/runtime#84247|
|[225939](https://dev.azure.com/dnceng-public/public/_build/results?buildId=225939)|dotnet/runtime|[chrome-DebuggerTests.PointerTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=225939&view=ms.vss-test-web.build-test-results-tab&runId=4248518&resultId=100322)|dotnet/runtime#83714|
|[225875](https://dev.azure.com/dnceng-public/public/_build/results?buildId=225875)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=225875&view=ms.vss-test-web.build-test-results-tab&runId=4246142&resultId=100322)||
|[225567](https://dev.azure.com/dnceng-public/public/_build/results?buildId=225567)|dotnet/runtime|[DebuggerTests.EvaluateOnCallFrameTests.DebuggerTests.EvaluateOnCallFrameTests.EvaluateTypeInstanceMembers](https://dev.azure.com/dnceng-public/public/_build/results?buildId=225567&view=ms.vss-test-web.build-test-results-tab&runId=4238210&resultId=100243)||
|[225411](https://dev.azure.com/dnceng-public/public/_build/results?buildId=225411)|dotnet/runtime|[chrome-DebuggerTests.GetPropertiesTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=225411&view=ms.vss-test-web.build-test-results-tab&runId=4234622&resultId=100322)||
|[224800](https://dev.azure.com/dnceng-public/public/_build/results?buildId=224800)|dotnet/runtime|[chrome-DebuggerTests.BreakpointTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=224800&view=ms.vss-test-web.build-test-results-tab&runId=4223014&resultId=100322)|dotnet/runtime#84191|
|[224455](https://dev.azure.com/dnceng-public/public/_build/results?buildId=224455)|dotnet/runtime|[chrome-DebuggerTests.GetPropertiesTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=224455&view=ms.vss-test-web.build-test-results-tab&runId=4217288&resultId=100322)|dotnet/runtime#84148|
|[223906](https://dev.azure.com/dnceng-public/public/_build/results?buildId=223906)|dotnet/runtime|[chrome-DebuggerTests.BreakpointTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=223906&view=ms.vss-test-web.build-test-results-tab&runId=4204220&resultId=100322)|dotnet/runtime#83716|
|[223892](https://dev.azure.com/dnceng-public/public/_build/results?buildId=223892)|dotnet/runtime|[chrome-DebuggerTests.CallFunctionOnTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=223892&view=ms.vss-test-web.build-test-results-tab&runId=4203500&resultId=100322)||
|[222367](https://dev.azure.com/dnceng-public/public/_build/results?buildId=222367)|dotnet/runtime|[chrome-DebuggerTests.GetPropertiesTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=222367&view=ms.vss-test-web.build-test-results-tab&runId=4172350&resultId=100322)||
|[222333](https://dev.azure.com/dnceng-public/public/_build/results?buildId=222333)|dotnet/runtime|[chrome-DebuggerTests.BreakpointTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=222333&view=ms.vss-test-web.build-test-results-tab&runId=4171278&resultId=100322)|dotnet/runtime#80297|
|[221876](https://dev.azure.com/dnceng-public/public/_build/results?buildId=221876)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=221876&view=ms.vss-test-web.build-test-results-tab&runId=4162312&resultId=100322)|dotnet/runtime#84097|
|[221800](https://dev.azure.com/dnceng-public/public/_build/results?buildId=221800)|dotnet/runtime|[chrome-DebuggerTests.CallFunctionOnTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=221800&view=ms.vss-test-web.build-test-results-tab&runId=4161100&resultId=100322)|dotnet/runtime#84085|
|[221596](https://dev.azure.com/dnceng-public/public/_build/results?buildId=221596)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=221596&view=ms.vss-test-web.build-test-results-tab&runId=4157372&resultId=100322)|dotnet/runtime#84083|
|[221504](https://dev.azure.com/dnceng-public/public/_build/results?buildId=221504)|dotnet/runtime|[chrome-DebuggerTests.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=221504&view=ms.vss-test-web.build-test-results-tab&runId=4154928&resultId=100322)|dotnet/runtime#84080|
|[221205](https://dev.azure.com/dnceng-public/public/_build/results?buildId=221205)|dotnet/runtime|[chrome-DebuggerTests.CallFunctionOnTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=221205&view=ms.vss-test-web.build-test-results-tab&runId=4149492&resultId=100322)|dotnet/runtime#84004|
|[221207](https://dev.azure.com/dnceng-public/public/_build/results?buildId=221207)|dotnet/runtime|[chrome-DebuggerTests.BreakpointTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=221207&view=ms.vss-test-web.build-test-results-tab&runId=4149430&resultId=100322)|dotnet/runtime#84017|
|[221056](https://dev.azure.com/dnceng-public/public/_build/results?buildId=221056)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=221056&view=ms.vss-test-web.build-test-results-tab&runId=4144276&resultId=100321)|dotnet/runtime#84068|
|[221041](https://dev.azure.com/dnceng-public/public/_build/results?buildId=221041)|dotnet/runtime|[chrome-DebuggerTests.BreakpointTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=221041&view=ms.vss-test-web.build-test-results-tab&runId=4143944&resultId=100322)|dotnet/runtime#84067|
|[220983](https://dev.azure.com/dnceng-public/public/_build/results?buildId=220983)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=220983&view=ms.vss-test-web.build-test-results-tab&runId=4142240&resultId=100322)|dotnet/runtime#83776|
|[220770](https://dev.azure.com/dnceng-public/public/_build/results?buildId=220770)|dotnet/runtime|[DebuggerTests.EvaluateOnCallFrameTests.DebuggerTests.EvaluateOnCallFrameTests.EvaluateTypeInstanceMembers](https://dev.azure.com/dnceng-public/public/_build/results?buildId=220770&view=ms.vss-test-web.build-test-results-tab&runId=4137634&resultId=100252)|dotnet/runtime#84058|
|[220319](https://dev.azure.com/dnceng-public/public/_build/results?buildId=220319)|dotnet/runtime|[chrome-DebuggerTests.GetPropertiesTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=220319&view=ms.vss-test-web.build-test-results-tab&runId=4127228&resultId=100322)|dotnet/runtime#84027|
|[220279](https://dev.azure.com/dnceng-public/public/_build/results?buildId=220279)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=220279&view=ms.vss-test-web.build-test-results-tab&runId=4126262&resultId=100322)||
|[220262](https://dev.azure.com/dnceng-public/public/_build/results?buildId=220262)|dotnet/runtime|[chrome-DebuggerTests.BreakpointTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=220262&view=ms.vss-test-web.build-test-results-tab&runId=4126134&resultId=100322)|dotnet/runtime#83838|
|[219923](https://dev.azure.com/dnceng-public/public/_build/results?buildId=219923)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=219923&view=ms.vss-test-web.build-test-results-tab&runId=4118850&resultId=100322)|dotnet/runtime#84004|
|[219916](https://dev.azure.com/dnceng-public/public/_build/results?buildId=219916)|dotnet/runtime|[chrome-DebuggerTests.SetVariableValueTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=219916&view=ms.vss-test-web.build-test-results-tab&runId=4118746&resultId=100322)|dotnet/runtime#83657|
|[219516](https://dev.azure.com/dnceng-public/public/_build/results?buildId=219516)|dotnet/runtime|[chrome-DebuggerTests.PointerTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=219516&view=ms.vss-test-web.build-test-results-tab&runId=4109314&resultId=100322)|dotnet/runtime#83776|
|[219412](https://dev.azure.com/dnceng-public/public/_build/results?buildId=219412)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=219412&view=ms.vss-test-web.build-test-results-tab&runId=4106778&resultId=100322)|dotnet/runtime#84011|
|[219349](https://dev.azure.com/dnceng-public/public/_build/results?buildId=219349)|dotnet/runtime|[chrome-DebuggerTests.GetPropertiesTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=219349&view=ms.vss-test-web.build-test-results-tab&runId=4104974&resultId=100322)|dotnet/runtime#82981|
|[218775](https://dev.azure.com/dnceng-public/public/_build/results?buildId=218775)|dotnet/runtime|[chrome-DebuggerTests.CallFunctionOnTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=218775&view=ms.vss-test-web.build-test-results-tab&runId=4095584&resultId=100322)||
|[218041](https://dev.azure.com/dnceng-public/public/_build/results?buildId=218041)|dotnet/runtime|[chrome-DebuggerTests.GetPropertiesTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=218041&view=ms.vss-test-web.build-test-results-tab&runId=4078328&resultId=100322)||
|[217847](https://dev.azure.com/dnceng-public/public/_build/results?buildId=217847)|dotnet/runtime|[chrome-DebuggerTests.GetPropertiesTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=217847&view=ms.vss-test-web.build-test-results-tab&runId=4072870&resultId=100322)||
|[216609](https://dev.azure.com/dnceng-public/public/_build/results?buildId=216609)|dotnet/runtime|[chrome-DebuggerTests.DelegateTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=216609&view=ms.vss-test-web.build-test-results-tab&runId=4071334&resultId=100322)|dotnet/runtime#83896|
|[217523](https://dev.azure.com/dnceng-public/public/_build/results?buildId=217523)|dotnet/runtime|[chrome-DebuggerTests.SteppingTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=217523&view=ms.vss-test-web.build-test-results-tab&runId=4065498&resultId=100322)|dotnet/runtime#82981|
|[217087](https://dev.azure.com/dnceng-public/public/_build/results?buildId=217087)|dotnet/runtime|[chrome-DebuggerTests.SteppingTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=217087&view=ms.vss-test-web.build-test-results-tab&runId=4053576&resultId=100322)|dotnet/runtime#83630|
|[216733](https://dev.azure.com/dnceng-public/public/_build/results?buildId=216733)|dotnet/runtime|[chrome-DebuggerTests.BreakpointTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=216733&view=ms.vss-test-web.build-test-results-tab&runId=4046830&resultId=100322)|dotnet/runtime#83882|
|[216694](https://dev.azure.com/dnceng-public/public/_build/results?buildId=216694)|dotnet/runtime|[chrome-DebuggerTests.CallFunctionOnTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=216694&view=ms.vss-test-web.build-test-results-tab&runId=4045370&resultId=100322)|dotnet/runtime#83838|
|[216631](https://dev.azure.com/dnceng-public/public/_build/results?buildId=216631)|dotnet/runtime|[chrome-DebuggerTests.GetPropertiesTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=216631&view=ms.vss-test-web.build-test-results-tab&runId=4043694&resultId=100322)||
|[216554](https://dev.azure.com/dnceng-public/public/_build/results?buildId=216554)|dotnet/runtime|[chrome-DebuggerTests.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=216554&view=ms.vss-test-web.build-test-results-tab&runId=4041906&resultId=100322)|dotnet/runtime#83894|
|[216472](https://dev.azure.com/dnceng-public/public/_build/results?buildId=216472)|dotnet/runtime|[chrome-DebuggerTests.ArrayTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=216472&view=ms.vss-test-web.build-test-results-tab&runId=4039982&resultId=100322)|dotnet/runtime#80297|
|[216419](https://dev.azure.com/dnceng-public/public/_build/results?buildId=216419)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=216419&view=ms.vss-test-web.build-test-results-tab&runId=4038788&resultId=100322)|dotnet/runtime#83882|
|[216403](https://dev.azure.com/dnceng-public/public/_build/results?buildId=216403)|dotnet/runtime|[chrome-DebuggerTests.CallFunctionOnTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=216403&view=ms.vss-test-web.build-test-results-tab&runId=4038302&resultId=100322)|dotnet/runtime#83624|
|[216232](https://dev.azure.com/dnceng-public/public/_build/results?buildId=216232)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests2.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=216232&view=ms.vss-test-web.build-test-results-tab&runId=4034712&resultId=100322)|dotnet/runtime#83882|
|[216166](https://dev.azure.com/dnceng-public/public/_build/results?buildId=216166)|dotnet/runtime|[chrome-DebuggerTests.BreakpointTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=216166&view=ms.vss-test-web.build-test-results-tab&runId=4033360&resultId=100322)|dotnet/runtime#83670|
|[215642](https://dev.azure.com/dnceng-public/public/_build/results?buildId=215642)|dotnet/runtime|[chrome-DebuggerTests.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=215642&view=ms.vss-test-web.build-test-results-tab&runId=4019508&resultId=100322)|dotnet/runtime#83856|
|[215329](https://dev.azure.com/dnceng-public/public/_build/results?buildId=215329)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=215329&view=ms.vss-test-web.build-test-results-tab&runId=4014346&resultId=100322)|dotnet/runtime#83624|
|[214831](https://dev.azure.com/dnceng-public/public/_build/results?buildId=214831)|dotnet/runtime|[chrome-DebuggerTests.BreakpointTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=214831&view=ms.vss-test-web.build-test-results-tab&runId=4005084&resultId=100322)|dotnet/runtime#82981|
|[214012](https://dev.azure.com/dnceng-public/public/_build/results?buildId=214012)|dotnet/runtime|[chrome-DebuggerTests.SteppingTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=214012&view=ms.vss-test-web.build-test-results-tab&runId=3980022&resultId=100322)|dotnet/runtime#83787|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|26|65|

**Comment by agocke** [comment] 2023-03-23 20:03
@jkoritzinsky @hoyosjs Could you check the regex I used here and see if it matches like I think it does? I'm not sure if multi-line works or whether it works like I think.

**Comment by agocke** [comment] 2023-03-23 23:04
Yeah, I don't think this worked. @markwilkie any chance you could provide insight to what I'm doing wrong?

**Comment by hoyosjs** [comment] 2023-03-23 23:05
I am looking at it, but I am not sure what you are trying to match it against.

**Comment by agocke** [comment] 2023-03-23 23:14
Ah, I'm trying to match this console log: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-83787-merge-8c3242e441a340b79e/chrome-DebuggerTests.SteppingTests/1/console.cbbe6fd0.log?helixlogtype=result

In particular, the test output "Test timed out", then having it walk all the way down to the stack trace, where the string "wasm" appears.

Basically, I want to catch timeouts where wasm is involved.

**Comment by carlossanlop** [comment] 2023-03-23 23:19
> "Test timed out(.|\n|\r)*wasm"

This would match: 

- "Test timed out"
- Zero or more times: 
  - Any character, or
  - a "\n" character
  - a "\r" character
- Followed by "wasm"

I am unsure if these regex searches work with multiple lines.

Is there a reason why you don't want to match the error lines that look like this?:

> browser-stderr [0322/182943.716:ERROR:dxva_video_decode_accelerator_win.cc(1426)] DXVAVDA fatal error: could not LoadLibrary: mf.dll: The specified module could not be found. (0x7E)

**Comment by agocke** [comment] 2023-03-23 23:21
> Is there a reason why you don't want to regex-match the error lines that look like this?:

I assumed the test could fail for more reasons than this and we would still want to catch it, but tbh that's probably better to start with.

**Comment by carlossanlop** [comment] 2023-03-23 23:28
@agocke confirmed, the search is _not_ multiline: https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#regex-matching

Can only match one line, no backtracking, and is case insensitive.

I think if we have many different types of timeouts, it's ok to have multiple issues open if we are able to match unique lines from the error output. Even if they have the same root cause in the end, at least we can get them marked as Known Build Error.

**Comment by hoyosjs** [comment] 2023-03-23 23:32
@agocke you set `ExcludeConsoleLog=true`

**Comment by agocke** [comment] 2023-03-23 23:33
Oops. Fixed :)

**Comment by hoyosjs** [comment] 2023-03-23 23:37
Hmm, it's definitely sad if multiline is not allowed though... And that new test string seems a bit too wide. That sounds like a red herring for a debugger hang.

**Comment by hoyosjs** [comment] 2023-03-23 23:48
I am not surprised if that's always the case even if it's a good run.

**Comment by lewing** [comment] 2023-04-06 18:22
@thaystg committed a fix and it seems to be working

**Closed by lewing** 2023-04-06 18:22 UTC
Labels: arch-wasm, blocking-clean-ci, area-Infrastructure-mono, Known Build Error
