### ISSUE TITLE
Transient services implementing IDisposable cause a memory leak

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/runtime#66483] opened 2022-03-10 22:48 UTC
### Description

When the framework creates a service to inject, if that service implements IDisposable then a reference is held by the scope so `Dispose` can be called when the Scope is destroyed.

Blazor Server keeps a single scope for the duration of the user's session. This means Transient register services are never disposed, causing a memory leak.

### Reproduction Steps

1: Create a Blazor Server app
2: Create a service that implements IDisposable
3: Register it as Transient
4: Have one of the default Blazor pages inject that service

Each time you navigate away from the consuming page and then back a new service instance will be created, and none of them will ever be garbage collected, causing a memory leak.

### Expected behavior

Memory should not leak

### Actual behavior

It does leak :)

### Configuration

.net 6.0 (and all earlier versions of Blazor)

**Comment by eerhardt** [comment] 2022-03-10 22:56
@mrpmorris - thank you for reporting the issue.

Do you think you could create a minimal reproduction, i.e. the smallest size of code/configuration required to reproduce the wrong behavior? That will aid us greatly in investigating here. That way we aren't guessing at the repro steps.

See: https://github.com/dotnet/runtime/blob/main/CONTRIBUTING.md#writing-a-good-bug-report

**Comment by mrpmorris** [comment] 2022-03-11 00:14
@eerhardt Of course, I've created one here -> https://github.com/mrpmorris/dotnet-IDisposable-memory-leak

1: Run the app
2: Click the link to go to the leaky page
3: Click the link to go back to the main page
4: Goto 2

Note how the one that doesn't implement IDisposable gets Finalized, whereas the one that implements IDisposable doesn't get Disposed or Finalized.

**Comment by BrennanConroy** [comment] 2022-03-11 16:30
@dotnet/aspnet-blazor-eng

**Comment by javiercn** [comment] 2022-03-11 16:57
Dupe of https://github.com/dotnet/aspnetcore/issues/26676

**Closed** 2022-03-11 19:50 UTC
Labels: untriaged, area-Extensions-DependencyInjection
