### ISSUE TITLE
Inconsistent behaviour between DateTime and TimeSpan ToString

### ISSUE THREAD

**Issue by bijington** [dotnet/runtime#35562] opened 2020-04-28 09:28 UTC
The current issue has been observed in **.NET 4.6.1** and also **.NET Core 3.1**.

When providing a format string of "hh:mm" to `DateTime.ToString()` it safely returns the formatted time in a string.

When providing the same format string of "hh:mm" to `TimeSpan.ToString()` it throws a `FormatException`.

**NOTE** that both `DateTime` and `TimeSpan` correctly return the expected string when supplied with a format string of "hh\:mm".

**Additional notes**

I have dug in to the code for both implementations and discovered that `DateTimeFormat.FormatCustomized` does in fact handle the `case` when a ':' character is present. The same is **not** true of the `TimeSpanFormat.FormatCustomized` implementation.

I appreciate that this code has been around for some time and that there is some risk in changing it. Are there any known reasons why this behavioural difference between `DateTime` and `TimeSpan` exists?

**Comment by Clockwork-Muse** [comment] 2020-04-28 15:26
["As designed", I guess](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-timespan-format-strings?view=netcore-3.1):

> The custom TimeSpan format specifiers don't include placeholder separator symbols, such as the symbols that separate days from hours, hours from minutes, or seconds from fractional seconds. Instead, these symbols must be included in the custom format string as string literals. For example, `"dd\.hh\:mm"` defines a period (.) as the separator between days and hours, and a colon (:) as the separator between hours and minutes.

... This feels especially odd, given that `ToString` _does_ use a `DateTimeFormatInfo` for at least standard formatting strings...

(Also, somewhat annoyed there isn't a ISO-8601 compatible format as a standard string.)

**Comment by bijington** [comment] 2020-05-05 18:18
@Clockwork-Muse Sadly I suspect you are correct. I did have big plans of attempting a ‘fix’ and see if I could supply a Pull Request. Not found the time yet though

**Comment by Clockwork-Muse** [comment] 2020-05-05 20:31
... not sure whether or not this would be accepted.  Although it's probably safe from being a "breaking" change...

**Comment by joperezr** [comment] 2020-07-07 21:48
cc: @tarekgh even though this does seem to be by design, I wonder if we should consider having consistency between DateTime and TimeSpan?

**Comment by tarekgh** [comment] 2020-07-07 23:07
This is by design.TimeSpan doesn't allow passing naked separator. if you want to format TimeSpan with any separator you'll need to pass it with like `hh\:mm`. I believe this is done that way as time separator like ':' when used with DateTime(Offset) it doesn't mean the ':' but it means a time separator stored in the current culture. so, if the culture used '.' as a time separator and the format has ':', then '.' will replace the ':'. But this is not the case for TimeSpan.

**Comment by Clockwork-Muse** [comment] 2020-07-08 15:45
@tarekgh - Right.  I think the ask was to enable culture replacement for `TimeSpan`.
@bijington - Can you comment about that?

**Comment by tarekgh** [comment] 2020-07-08 17:00
I don't think timespan should be cultural sensitive. It is not really a date/time but anyway I love to hear other opinions.

**Comment by bijington** [comment] 2020-07-08 19:17
@Clockwork-Muse no I was only really interested in getting to a consistent format between `TimeSpan` (supports hh\:mm) and `DateTime` (supports hh\:mm and hh:mm) if possible. Especially as when you dig down in to the code they both seem to use `DateTimeFormatInfo` for checking specific details.

@tarekgh and @joperezr thank you for confirming it is by design. I did assume that it would be unlikely this would change.

**Comment by joperezr** [comment] 2020-07-08 19:38
Closing this issue for now as per discussion. Feel free to reopen.

**Closed by joperezr** 2020-07-08 19:38 UTC
Labels: area-System.Runtime, enhancement
