### ISSUE TITLE
ReadOnlySequence GetPosition does not respect slice boundaries

### ISSUE THREAD

**Issue by ladeak** [dotnet/runtime#86509] opened 2023-05-19 16:39 UTC
### Description

GetPosition does not respect the slicing operation.

```csharp
ReadOnlySequence<byte> sequence = new ReadOnlySequence<byte>(new byte[] { 128, 0, 0, 2 });
ReadOnlySequence<byte> slice = sequence. Slice(1);
SequencePosition slicePos = slice.GetPosition(1);
long sliceOffset = slice.GetOffset(slicePos); // 2
```

This is really confusing when a sequence gets sliced and passed into as an argument to a method. Then that private method, cannot trust/use the Position/Offset values, relative to the Slice it is given.

### Reproduction Steps

```csharp
ReadOnlySequence<byte> sequence = new ReadOnlySequence<byte>(new byte[] { 128, 0, 0, 2 });
ReadOnlySequence<byte> slice = sequence. Slice(1);
SequencePosition slicePos = slice.GetPosition(1);
long sliceOffset = slice.GetOffset(slicePos);
```

### Expected behavior

I would expect `sliceOffset` to be 1 as the offset in the current `slice` is one. 

### Actual behavior

`sliceOffset` is actually 2.

### Regression?

No

### Known Workarounds

No known workarounds

### Configuration

.NET 8 Preview 4
Windows 11 x64

### Other information

See corresponding discussion: https://github.com/dotnet/aspnetcore/issues/48203

**Comment by ladeak** [comment] 2023-05-19 16:43
@jeffhandley could you review again, the previous (referenced ticket go transferred), but apparently this is the suggested place to file the issue.

**Comment by ladeak** [comment] 2023-05-22 19:23
Indeed it looks similar.

**Comment by jeffhandley** [comment] 2023-05-24 21:46
Thanks for spotting that, @hrrrrustic. Indeed, I'm going to close this as a duplicate of #75866.

**Closed by jeffhandley** 2023-05-24 21:46 UTC
Labels: area-System.Memory, untriaged
