### ISSUE TITLE
Analyzer: Introduce an analyzer to help keep nullable annotations clean and efficient

### ISSUE THREAD

**Issue by geeknoid** [dotnet/runtime#85527] opened 2023-04-28 14:29 UTC
Nullable annotations have substantially improved C#'s usability and reliability by making it possible to mostly eliminate null reference exceptions and greatly simplifying the task of reasoning about null handling when creating code. Unfortunately, as code evolves, it's easy to leftover annotations to pollute a codebase. Something that used to be nullable no longer is, but stray ?, ?? or ??= remain in the code. All these conditional constructs not only pollute the semantics of the code, confusing future you about what's going on, they also cost real cycles at runtime.

There should be an analyzer to report when conditional constructs are unnecessary based on the nullable annotations in the code. So if the compiler says "foo" is not nullable, then report the use of "foo?.X" or "foo ??= X" or "foo ?? X" has being inconsistent and likely superfluous.

**Comment by geeknoid** [comment] 2023-04-28 14:32
Here are the implementations of analyzers for each of ?, ?? and ??=. These could be combined into a single do-it-all analyzer to track "inconsistent nullable conditionals".

```csharp
/// <summary>
/// C# analyzer that recommends removing superfluous uses of ?? and ??=.
/// </summary>
[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class CoalesceAnalyzer : DiagnosticAnalyzer
{
    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics => ImmutableArray.Create(DiagDescriptors.CoalesceAssignment, DiagDescriptors.Coalesce);

    public override void Initialize(AnalysisContext context)
    {
        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.EnableConcurrentExecution();

        context.RegisterCompilationStartAction(compilationStartContext =>
        {
            // only report diagnostics on .NET 6, since previous runtimes don't have good enough nullability annotations
            if (compilationStartContext.Compilation.IsNet6OrGreater())
            {
                compilationStartContext.RegisterOperationAction(operationAnalysisContext =>
                {
                    var op = (ICoalesceAssignmentOperation)operationAnalysisContext.Operation;

                    var type = op.Target.Type;
                    if (type != null
                        && type.NullableAnnotation == NullableAnnotation.NotAnnotated
                        && type.OriginalDefinition.SpecialType != SpecialType.System_Nullable_T)
                    {
                        if (op.Target.Kind == OperationKind.ParameterReference)
                        {
                            var pr = (IParameterReferenceOperation)op.Target;
                            var method = pr.Parameter.ContainingSymbol as IMethodSymbol;

                            if (pr.Parameter.ContainingSymbol.IsExternallyVisible()
                                || (method != null && method.ImplementsPublicInterface()))
                            {
                                // this is a ??= applied to a parameter of a public method, let it slide...
                                return;
                            }
                        }

                        var diagnostic = Diagnostic.Create(DiagDescriptors.CoalesceAssignment, op.Syntax.GetLocation());
                        operationAnalysisContext.ReportDiagnostic(diagnostic);
                    }
                }, OperationKind.CoalesceAssignment);

                compilationStartContext.RegisterOperationAction(operationAnalysisContext =>
                {
                    var op = (ICoalesceOperation)operationAnalysisContext.Operation;

                    var type = op.Value.Type;
                    if (type != null
                        && type.NullableAnnotation == NullableAnnotation.NotAnnotated
                        && type.OriginalDefinition.SpecialType != SpecialType.System_Nullable_T)
                    {
                        if (op.Value.Kind == OperationKind.ParameterReference)
                        {
                            var pr = (IParameterReferenceOperation)op.Value;
                            var method = pr.Parameter.ContainingSymbol as IMethodSymbol;

                            if (pr.Parameter.ContainingSymbol.IsExternallyVisible()
                                || (method != null && method.ImplementsPublicInterface()))
                            {
                                // this is a ?? applied to a parameter of a public method, let it slide...
                                return;
                            }
                        }

                        var diagnostic = Diagnostic.Create(DiagDescriptors.Coalesce, op.Syntax.GetLocation());
                        operationAnalysisContext.ReportDiagnostic(diagnostic);
                    }
                }, OperationKind.Coalesce);
            }
        });
    }
}
```

```csharp
/// <summary>
/// C# analyzer that recommends removing superfluous uses of ?.
/// </summary>
[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class ConditionalAccessAnalyzer : DiagnosticAnalyzer
{
    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics => ImmutableArray.Create(DiagDescriptors.ConditionalAccess);

    public override void Initialize(AnalysisContext context)
    {
        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.EnableConcurrentExecution();

        context.RegisterCompilationStartAction(compilationStartContext =>
        {
            // only report diagnostics on .NET 6 or above since previous runtimes don't have good enough nullability annotations
            if (compilationStartContext.Compilation.IsNet6OrGreater())
            {
                var maybeNull = compilationStartContext.Compilation.GetTypeByMetadataName("System.Diagnostics.CodeAnalysis.MaybeNullAttribute");

                compilationStartContext.RegisterOperationAction(operationAnalysisContext =>
                {
                    var op = (IConditionalAccessOperation)operationAnalysisContext.Operation;

                    ITypeSymbol? type;
                    switch (op.Operation.Kind)
                    {
                        case OperationKind.PropertyReference:
                        {
                            var propRef = (IPropertyReferenceOperation)op.Operation;
                            if (MaybeNull(propRef.Property.GetAttributes()))
                            {
                                // property can be null, independent of its type signature
                                return;
                            }

                            type = propRef.Property.Type;
                            break;
                        }

                        case OperationKind.FieldReference:
                        {
                            var fieldRef = (IFieldReferenceOperation)op.Operation;
                            if (MaybeNull(fieldRef.Field.GetAttributes()))
                            {
                                return;
                            }

                            type = fieldRef.Field.Type;
                            break;
                        }

                        case OperationKind.Invocation:
                        {
                            var invocation = (IInvocationOperation)op.Operation;
                            if (MaybeNull(invocation.TargetMethod.GetReturnTypeAttributes()))
                            {
                                return;
                            }

                            type = op.Operation.Type;
                            break;
                        }

                        default:
                        {
                            type = op.Operation.Type;
                            break;
                        }
                    }

                    if (type != null)
                    {
                        if (type is ITypeParameterSymbol tp)
                        {
                            if (!tp.HasNotNullConstraint)
                            {
                                // a generic type without a notnull constraint can potentially hold null values
                                return;
                            }
                        }

                        // if the type of the operand is not nullable, then we have a candidate
                        if (type.NullableAnnotation == NullableAnnotation.NotAnnotated)
                        {
                            // if the operand is a parameter on a public method or interface method, then don't report it
                            if (op.Operation.Kind == OperationKind.ParameterReference)
                            {
                                var pr = (IParameterReferenceOperation)op.Operation;
                                var method = pr.Parameter.ContainingSymbol as IMethodSymbol;

                                if (pr.Parameter.ContainingSymbol.IsExternallyVisible()
                                    || (method != null && method.ImplementsPublicInterface()))
                                {
                                    // this is a ? applied to a parameter of a public method, let it slide...
                                    return;
                                }
                            }

                            var diagnostic = Diagnostic.Create(DiagDescriptors.ConditionalAccess, op.Syntax.GetLocation());
                            operationAnalysisContext.ReportDiagnostic(diagnostic);
                        }
                    }
                }, OperationKind.ConditionalAccess);

                bool MaybeNull(ImmutableArray<AttributeData> attrs)
                {
                    foreach (var attr in attrs)
                    {
                        if (SymbolEqualityComparer.Default.Equals(attr.AttributeClass, maybeNull))
                        {
                            return true;
                        }
                    }

                    return false;
                }
            }
        });
    }
}
```

**Comment by buyaa-n** [comment] 2023-05-17 21:57
Closing as duplicate of https://github.com/dotnet/roslyn/issues/65435,

**Closed by buyaa-n** 2023-05-17 21:57 UTC
Labels: area-Meta, untriaged, code-analyzer, code-fixer
