### ISSUE TITLE
Accessing physical drives throws when accessing from the end and retrieving .Length

### ISSUE THREAD

**Issue by virzak** [dotnet/runtime#73669] opened 2022-08-10 01:37 UTC
### Description

Stream.Length throws:

```
  Message: 
System.IO.IOException : Incorrect function. : '\\?\PhysicalDrive0'

  Stack Trace: 
SafeFileHandle.<GetFileLength>g__GetFileLengthCore|31_0()
SafeFileHandle.GetFileLength()
BufferedFileStreamStrategy.get_Length()
DeviceInfoTests.GetStreamLength(String path) line 19
RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Reading from the end throws

```
  Message: 
System.IO.IOException : The parameter is incorrect. : '\\?\PhysicalDrive0'

  Stack Trace: 
RandomAccess.ReadAtOffset(SafeFileHandle handle, Span`1 buffer, Int64 fileOffset)
ThreadPoolValueTaskSource.ExecuteInternal()
--- End of stack trace from previous location ---
ThreadPoolValueTaskSource.GetResult(Int16 token)
Int32>.GetResult(Int16 token)
BufferedFileStreamStrategy.ReadAsyncSlowPath(Task semaphoreLockTask, Memory`1 buffer, CancellationToken cancellationToken)
IValueTaskSource<TResult>.GetResult(Int16 token)
DeviceInfoTests.ReadBeginningAndEnd(String path) line 47
--- End of stack trace from previous location ---
```

### Reproduction Steps

Test cases are here:

https://github.com/virzak/retrieve-disks/blob/44d822f14cf260af518b1b7a39c5c4992456c9da/tests/RetrieveDisksTests/DeviceInfoTests.cs

Or run the following:

```cs
[Theory]
[InlineData("C:\\Windows\\System32\\drivers\\etc\\hosts")]
[InlineData("//?/PhysicalDrive0")]
public void GetStreamLength(string path)
{
    using var stream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read);
    var streamLength = stream.Length;
    Assert.True(streamLength > 0);
}

[Theory]
[InlineData("C:\\Windows\\System32\\drivers\\etc\\hosts")]
[InlineData("//?/PhysicalDrive0")]
public async Task ReadBeginningAndEnd(string path)
{
    var byteCount = 1;
    var bytesBeginning = new byte[byteCount];
    var byteEnd = new byte[byteCount];

    using var stream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read);
    await stream.ReadAsync(bytesBeginning.AsMemory());

    // Band aid solution to get length
    long streamLength;
    try
    {
        streamLength = stream.Length;
    }
    catch (IOException)
    {
        streamLength = DeviceInfo.GetDeviceInfo(path).DiskLength;
    }

    stream.Seek(streamLength - byteCount, SeekOrigin.Begin);
    await stream.ReadAsync(byteEnd.AsMemory());
}

```

### Expected behavior

Physical devices should execute without exceptions

### Actual behavior

Exceptions occur

### Known Workarounds

The workaround for getting a stream length of a drive is using `DeviceIoControl` with `IOCTL_STORAGE_READ_CAPACITY`.

### Configuration

.NET 6, .NET 7-preview.7
Windows 11 x64

### Other information

@adamsitnik looks similar to #62851

**Comment by adamsitnik** [comment] 2022-08-10 09:10
Hi @virzak 

Thank you for a very detailed bug report.

I was able to reproduce the issue locally for .NET 5, 6 and 7.

<details>

```cs
using System;
using System.IO;
using System.Threading.Tasks;

namespace PhysicalDrive
{
    internal class Program
    {
        static async Task Main()
        {
            using var stream = new FileStream("//?/PhysicalDrive0", FileMode.Open, FileAccess.Read, FileShare.Read);

            int byteCount = await stream.ReadAsync(new byte[100]);
            Console.WriteLine($"Read {byteCount} bytes");
            Console.WriteLine($"Length is {stream.Length}");
        }
    }
}
```

```log
PS C:\Users\adsitnik\source\repos\PhysicalDrive> dotnet run -f net5.0
Read 100 bytes
Unhandled exception. System.IO.IOException: Incorrect function. : '\\?\PhysicalDrive0'
   at System.IO.FileStream.GetLengthInternal()
   at System.IO.FileStream.get_Length()
   at PhysicalDrive.Program.Main() in C:\Users\adsitnik\source\repos\PhysicalDrive\Program.cs:line 15
   at PhysicalDrive.Program.<Main>()
PS C:\Users\adsitnik\source\repos\PhysicalDrive> dotnet run -f net6.0
Read 100 bytes
Unhandled exception. System.IO.IOException: Incorrect function. : '\\?\PhysicalDrive0'
   at System.IO.RandomAccess.GetFileLength(SafeFileHandle handle)
   at System.IO.Strategies.OSFileStreamStrategy.get_Length()
   at System.IO.Strategies.BufferedFileStreamStrategy.get_Length()
   at System.IO.FileStream.get_Length()
   at PhysicalDrive.Program.Main() in C:\Users\adsitnik\source\repos\PhysicalDrive\Program.cs:line 15
   at PhysicalDrive.Program.<Main>()
PS C:\Users\adsitnik\source\repos\PhysicalDrive> dotnet run -f net7.0
Read 100 bytes
Unhandled exception. System.IO.IOException: Incorrect function. : '\\?\PhysicalDrive0'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.<GetFileLength>g__GetFileLengthCore|31_0()
   at Microsoft.Win32.SafeHandles.SafeFileHandle.GetFileLength()
   at System.IO.Strategies.BufferedFileStreamStrategy.get_Length()
   at PhysicalDrive.Program.Main() in C:\Users\adsitnik\source\repos\PhysicalDrive\Program.cs:line 15
   at PhysicalDrive.Program.<Main>()
```

</details>

 `GetFileType` returns `FILE_TYPE_DISK` for `//?/PhysicalDrive0` so we assume that seeking is possible and later fail when trying to obtain length using `GetFileInformationByHandleEx` sys-call.

**Comment by adamsitnik** [comment] 2022-08-10 09:23
Since we are very close to the .NET 7 release and it's not a regression from last release, I am going to move it to 8.0 milestone and make it up-for-grabs.

The contributor who is willing to work on this issue should:

- [ ] add new unit test to the existing [Length unit tests](https://github.com/dotnet/runtime/blob/main/src/libraries/System.IO.FileSystem/tests/RandomAccess/GetLength.cs)
- [ ] the test needs to be enabled only on Windows and Admin, this can be achieved by using `[ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsWindowsAndElevated))]` attribute
- [ ] perform a research about what is the fastest and most reliable way of getting file length by comparing various sys-calls available on Windows
- [ ] if there is a sys-call that works for all scenarios and is faster than the one we are currently using, change the implementation to use it by default. If it works only for devices, use it as a fallback for getting length when current sys-call fails.

**Comment by virzak** [comment] 2022-08-10 13:13
Thanks @adamsitnik,

Retrieving Length has a workaround, so this isn't as crucial.
The real issue is reading from the end, which I don't currently have a solution for. Any advice?

Also, if I send a PR in the next little while could it be merged into .Net 7 still? The client wouldn't like to wait until Nov 2023 for .Net 8.

**Comment by danmoseley** [comment] 2022-08-10 14:52
For .NET 7, this shows the schedule: https://github.com/dotnet/runtime/issues/72297

Speaking generally, if a PR is available and signed off in time, whether it was merged into .NET 7 would depend on the risk level - as there is not much time to discover a problem before we ship. If a change is made in .NET 8, a backport into servicing release may be possible, but we look for major impact and no reasonable workaround as well as evaluating risk.

**Comment by adamsitnik** [comment] 2022-08-12 15:17
Update: it turned out that this specific file (device) can seek only by a volume vector size (4096): https://github.com/dotnet/runtime/pull/73708#issuecomment-1213219850

I currently don't have any ideas for more generic fix similar to https://github.com/dotnet/runtime/pull/63625 because:
- Windows `GetFileType` recognizes this file as `FILE_TYPE_DISK` which means "it's regular file"
- the file is not opened with `NO_BUFFERING` so we can't treat it as such.

**Comment by danmoseley** [comment] 2022-08-13 03:21
should we close then, with #63625 now merged?

**Comment by adamsitnik** [comment] 2022-08-17 16:20
> should we close then, with https://github.com/dotnet/runtime/pull/63625 now merged?

I agree, we should close it as I currently don't see any way of fixing the remaining issue.

**Closed by adamsitnik** 2022-08-17 16:20 UTC
Labels: area-System.IO, help wanted
