### ISSUE TITLE
Test faliure GC\\API\\Frozen\\Frozen\\Frozen.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#73672] opened 2022-08-10 01:46 UTC
Run: [runtime-coreclr outerloop 20220809.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1932185&view=ms.vss-test-web.build-test-results-tab&runId=49917266&paneView=debug&resultId=107151)

Failed test:
```
R2R-CG2 windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open
- GC\\API\\Frozen\\Frozen\\Frozen.cmd
- GC\\API\\Frozen\\Frozen\\Frozen.cmd
- GC\\API\\Frozen\\Frozen\\Frozen.cmd

R2R-CG2 Linux arm64 Checked no_tiered_compilation @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652
- GC/API/Frozen/Frozen/Frozen.sh

R2R-CG2 Linux arm64 Checked @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652
- GC/API/Frozen/Frozen/Frozen.sh

R2R-CG2 Linux arm64 Checked no_tiered_compilation @ (Alpine.314.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm64v8-20210910135810-8a6f4f3
- GC/API/Frozen/Frozen/Frozen.sh

coreclr windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open
- GC\\API\\Frozen\\Frozen\\Frozen.cmd

R2R-CG2 Linux arm64 Checked @ (Alpine.314.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm64v8-20210910135810-8a6f4f3
- GC/API/Frozen/Frozen/Frozen.sh

R2R-CG2 windows arm64 Checked @ Windows.10.Arm64v8.Open
- GC\\API\\Frozen\\Frozen\\Frozen.cmd

coreclr windows arm64 Checked @ Windows.10.Arm64v8.Open
- GC\\API\\Frozen\\Frozen\\Frozen.cmd

R2R-CG2 Linux x64 Checked no_tiered_compilation @ (Alpine.314.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64-20210910135833-1848e19
- GC/API/Frozen/Frozen/Frozen.sh

coreclr windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open
- GC\\API\\Frozen\\Frozen\\Frozen.cmd

R2R-CG2 Linux x64 Checked no_tiered_compilation @ Ubuntu.1804.Amd64.Open
- GC/API/Frozen/Frozen/Frozen.sh

coreclr Linux arm64 Checked no_tiered_compilation @ (Alpine.314.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm64v8-20210910135810-8a6f4f3
- GC/API/Frozen/Frozen/Frozen.sh

coreclr windows x64 Checked @ Windows.10.Amd64.Open
- GC\\API\\Frozen\\Frozen\\Frozen.cmd

R2R-CG2 windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open
- GC\\API\\Frozen\\Frozen\\Frozen.cmd

R2R-CG2 Linux x64 Checked @ (Alpine.314.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64-20210910135833-1848e19
- GC/API/Frozen/Frozen/Frozen.sh

R2R-CG2 windows x64 Checked @ Windows.10.Amd64.Open
- GC\\API\\Frozen\\Frozen\\Frozen.cmd

coreclr Linux arm64 Checked @ (Alpine.314.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm64v8-20210910135810-8a6f4f3
- GC/API/Frozen/Frozen/Frozen.sh

coreclr Linux arm64 Checked no_tiered_compilation @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652
- GC/API/Frozen/Frozen/Frozen.sh

R2R-CG2 Linux x64 Checked @ Ubuntu.1804.Amd64.Open
- GC/API/Frozen/Frozen/Frozen.sh

coreclr Linux arm64 Checked @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652
- GC/API/Frozen/Frozen/Frozen.sh

coreclr Linux x64 Checked @ Ubuntu.1804.Amd64.Open
- GC/API/Frozen/Frozen/Frozen.sh

coreclr Linux x64 Checked no_tiered_compilation @ Ubuntu.1804.Amd64.Open
- GC/API/Frozen/Frozen/Frozen.sh

coreclr Linux x64 Checked @ (Alpine.314.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64-20210910135833-1848e19
- GC/API/Frozen/Frozen/Frozen.sh

coreclr Linux x64 Checked no_tiered_compilation @ (Alpine.314.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64-20210910135833-1848e19
- GC/API/Frozen/Frozen/Frozen.sh
```
**Error message:**
```
Assert failure(PID 4960 [0x00001360], Thread: 10996 [0x2af4]): (g_gc_lowest_address <= address) && (address < g_gc_highest_address)

CORECLR! WKS::gc_heap::verify_region_to_generation_map + 0x90 (0x00007ff91e108b28) CORECLR! WKS::gc_heap::mark_phase + 0x230 (0x00007ff91e0f41f0)
CORECLR! WKS::gc_heap::gc1 + 0x25C (0x00007ff91e0ea784) CORECLR! WKS::gc_heap::garbage_collect + 0x694 (0x00007ff91e0ea4e4)
CORECLR! WKS::GCHeap::GarbageCollectGeneration + 0x4AC (0x00007ff91e0d2314) CORECLR! WKS::GCHeap::GarbageCollect + 0x1C8 (0x00007ff91e0d1de8)
CORECLR! GCInterface_Collect + 0x12C (0x00007ff91def09dc) SYSTEM.PRIVATE.CORELIB! System.GC::Collect()$##6000508 + 0x3C (0x00007ff91cd37acc)
FROZEN! <no symbol> + 0x0 (0x00007ff95dd31cac) CORECLR! CallDescrWorkerInternal + 0x84 (0x00007ff91dd51fbc)
File: D:\a_work\1\s\src\coreclr\gc\gc.cpp Line: 3573
Image: D:\h\w\A7050902\p\corerun.exe

Return code:      1
Raw output file:      D:\h\w\A7050902\w\A35308CA\uploads\Reports\GC.API\Frozen\Frozen\Frozen.output.txt
Raw output:
BEGIN EXECUTION
Frozen.dll
1 file(s) copied.
14:29:05.87
Response file: D:\h\w\A7050902\w\A35308CA\e\GC\API\Frozen\Frozen\Frozen.dll.rsp
D:\h\w\A7050902\w\A35308CA\e\GC\API\Frozen\Frozen\IL-CG2\Frozen.dll
-o:D:\h\w\A7050902\w\A35308CA\e\GC\API\Frozen\Frozen\Frozen.dll
--targetarch:arm64
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\A7050902\p\System..dll
-r:D:\h\w\A7050902\p\Microsoft..dll
-r:D:\h\w\A7050902\p\mscorlib.dll
-r:D:\h\w\A7050902\p\netstandard.dll
-O
" "dotnet" "D:\h\w\A7050902\p\crossgen2\crossgen2.dll" @"D:\h\w\A7050902\w\A35308CA\e\GC\API\Frozen\Frozen\Frozen.dll.rsp"   -r:D:\h\w\A7050902\w\A35308CA\e\GC\API\Frozen\Frozen\IL-CG2*.dll"
Emitting R2R PE file: D:\h\w\A7050902\w\A35308CA\e\GC\API\Frozen\Frozen\Frozen.dll
14:29:09.92
"D:\h\w\A7050902\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  Frozen.dll
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\A7050902\p
D:\h\w\A7050902\w\A35308CA\e\GC\API\Frozen\Frozen\Frozen.cmd
Expected: True
Actual:   False


Stack trace
   at GC_API._Frozen_Frozen_Frozen_._Frozen_Frozen_Frozen_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by MichalStrehovsky** [comment] 2022-08-10 02:41
Duplicate of #73653.

**Closed by MichalStrehovsky** 2022-08-10 02:41 UTC
Labels: arch-arm64, os-linux, os-windows, arch-x64, area-GC-coreclr, untriaged, blocking-outerloop
