### ISSUE TITLE
 System.Text.Json ：The JSON  value could not be converted to System.String

### ISSUE THREAD

**Issue by quan0zhou** [dotnet/runtime#56760] opened 2021-08-03 02:39 UTC
the json such as
`"{\"payid\":8752593,\"payPreferential\":0,\"payStatus\":\"1\"}"`

```C#
public class PayNotifyModel
 {
        public string PayId { get; set; }
        
        public string PayStatus { get; set; }

       public int PayPreferential { get; set; }
  }
 
```
`var model=JsonSerializer.Deserialize<PayNotifyModel>(json, new JsonSerializerOptions  { PropertyNameCaseInsensitive = true })  --error System.Text.Json.JsonException:“The JSON value could not be converted to System.String. Path: $.payid | LineNumber: 0 | BytePositionInLine: 149
`

**Comment by ryank425** [comment] 2021-08-03 03:01
Aside from not knowing what Data.DecryptByPrivateKey(priviteKey) returns in this context,

JSON `"{payid\":8752593,\"payPreferential\":0,\"payStatus\":\"1\"}"`
--> `"{\"payid\":\"8752593\",\"payPreferential\":0,\"payStatus\":\"1\"}"` (after adding \" to it to make valid)

is still invalid for 
```

public class PayNotifyModel
{
    public string PayId { get; set; }

    public string PayStatus { get; set; }

    public int PayPreferential { get; set; }
}
```

as you have PayId declared as string in this class but you have payid to be number in JSON.

**Comment by quan0zhou** [comment] 2021-08-03 03:54
@ryank425  
Sorry, the code above is unclear, returning JSON is described above.
`"{\"payid\":8752593,\"payPreferential\":0,\"payStatus\":\"1\"}"`

**Comment by ryank425** [comment] 2021-08-03 04:06
> @ryank425
> Sorry, the code above is unclear, returning JSON is described above.
> `"{\"payid\":8752593,\"payPreferential\":0,\"payStatus\":\"1\"}"`

I think the issue is still the same. Your payid JSON contains a numeric value, 8752593, which is not enclosed with double quotes like payStatus, but your class definition contains PayId as string.

Either making the JSON value to hold the string representation ("8752593"), or changing the following line doesn't produce any more exceptions.

From
`    public string PayId { get; set; }
`
To
`    public int PayId { get; set; }
`

**Comment by quan0zhou** [comment] 2021-08-03 04:17
@ryank425 
Yes, according to the above modification is no problem, but the customer interface is possible to return to the int type PayID or return the string type PayID，
Now, I use `Newtonsoft.json` is no problem, it can convert JSON int  value to string value

**Comment by eiriktsarpalis** [comment] 2021-08-03 08:25
> Yes, according to the above modification is no problem, but the customer interface is possible to return to the int type PayID or return the string type PayID

Assuming string PayID's still use numeric representation you might want to consider doing the following:
```csharp
public class PayNotifyModel
{
    public int PayId { get; set; }
}
```
then using the following configuration:
```csharp
var options = new JsonSerializerOptions 
{ 
    PropertyNameCaseInsensitive  = true, 
    NumberHandling = JsonNumberHandling.AllowReadingFromString 
};

var result = JsonSerializer.Deserialize<PayNotifyModel>(json, options);
```
deserialization should work for both `{"payid":8752593}` and `{"payid":"8752593"}` representations.

**Comment by steveharter** [comment] 2021-08-04 17:31
Closing; quoted strings are opt-in in STJ

**Closed by steveharter** 2021-08-04 17:31 UTC
Labels: area-System.Text.Json, customer assistance
