### ISSUE TITLE
Failed test: GetAsync_SettingsFrameNotSentOnNewConnection_ClientApplies100StreamLimit

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#45958] opened 2020-12-11 12:40 UTC
failed again in job: [runtime-libraries-coreclr outerloop 20201210.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=915576&view=ms.vss-test-web.build-test-results-tab&runId=29128826&resultId=103176&paneView=debug)

failed test: System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.GetAsync_SettingsFrameNotSentOnNewConnection_ClientApplies100StreamLimit

net6.0-Linux-Release-arm-CoreCLR_release-(Debian.9.Arm32.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-9-helix-arm32v7-bfcd90a-20200121150037

Error message
~~~
System.OperationCanceledException : The operation was canceled.


Stack trace
   at System.Threading.CancellationToken.ThrowOperationCanceledException() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationToken.cs:line 368
   at System.Threading.CancellationToken.ThrowIfCancellationRequested() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationToken.cs:line 362
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 947
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 916
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs:line 781
   at System.Net.Test.Common.Http2LoopbackConnection.FillBufferAsync(Memory`1 buffer, CancellationToken cancellationToken) in /_/src/libraries/Common/tests/System/Net/Http/Http2LoopbackConnection.cs:line 124
   at System.Net.Test.Common.Http2LoopbackConnection.ReadFrameAsync(CancellationToken cancellationToken) in /_/src/libraries/Common/tests/System/Net/Http/Http2LoopbackConnection.cs:line 219
   at System.Net.Test.Common.Http2LoopbackConnection.ReadFrameAsync(CancellationToken cancellationToken) in /_/src/libraries/Common/tests/System/Net/Http/Http2LoopbackConnection.cs:line 219
   at System.Net.Test.Common.Http2LoopbackConnection.ReadFrameAsync(TimeSpan timeout) in /_/src/libraries/Common/tests/System/Net/Http/Http2LoopbackConnection.cs:line 149
   at System.Net.Test.Common.Http2LoopbackConnection.ReadRequestHeadersFrames()+MoveNext() in /_/src/libraries/Common/tests/System/Net/Http/Http2LoopbackConnection.cs:line 556
   at System.Net.Test.Common.Http2LoopbackConnection.ReadRequestHeadersFrames()+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Net.Test.Common.Http2LoopbackConnection.ReadAndParseRequestHeaderAsync(Boolean readBody) in /_/src/libraries/Common/tests/System/Net/Http/Http2LoopbackConnection.cs:line 591
   at System.Net.Test.Common.Http2LoopbackConnection.ReadAndParseRequestHeaderAsync(Boolean readBody) in /_/src/libraries/Common/tests/System/Net/Http/Http2LoopbackConnection.cs:line 591
   at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter[TResult](Task`1 task, TimeSpan timeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 55
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.GetAsync_SettingsFrameNotSentOnNewConnection_ClientApplies100StreamLimit() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 433
--- End of stack trace from previous location ---
~~~

_Originally posted by @v-haren in https://github.com/dotnet/runtime/issues/44183#issuecomment-742912022_

**Comment by karelz** [comment] 2020-12-17 17:01
Triage: @alnikola wanted to take a brief look as this is a test he introduced and is surprised why it timed out ...

**Comment by alnikola** [comment] 2021-01-04 15:52
I checked the test, it uses only the loopback server with timeout set to 3 seconds which seems reasonable in this case. So, it looks like yet another case of an unexplained test VM hang we observe from time to time.
cc: @karelz

**Comment by alnikola** [comment] 2021-01-04 15:55
It's worth mentioning, there is another less probable option that the loopback server has some subtle bug that causes those unexplained hangs from time to time. But, I have not got any evidence supporting that theory so far.

**Comment by wfurt** [comment] 2021-01-04 18:48
I see only this one failure in Kusto. 
I think we would need dump or a way to reproduce it. 
Since this seems like oddball, I'm not sure Huw much effort we want to put into this.

**Comment by karelz** [comment] 2021-05-10 17:47
No failure between 2/23-5/10 (incl. PRs). Closing.

**Closed by karelz** 2021-05-10 17:47 UTC
Labels: area-System.Net.Http, test-run-core
