### ISSUE TITLE
Strange ASP.NET Core behavior with advanced runtime features

### ISSUE THREAD

**Issue by richlander** [dotnet/runtime#73828] opened 2022-08-12 00:06 UTC
I'm [updating our docker samples](https://github.com/dotnet/dotnet-docker/pull/3989). We do that each release just before RC1. We have some existing trimming samples for ASP.NET Core. They are producing trimming warnings for both .NET 6 and 7, but the app doesn't work correctly with .NET 7 (see screenshow below).

Should I use a different trimming mode or something else? Or is this a bug?

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/2608468/184261481-20da0a83-b55f-4104-a747-64aaa39397bb.png">

These .NET 6 Dockerfiles work fine:

- https://github.com/dotnet/dotnet-docker/blob/main/samples/aspnetapp/Dockerfile
- https://github.com/dotnet/dotnet-docker/blob/main/samples/aspnetapp/Dockerfile.alpine-x64
- https://github.com/dotnet/dotnet-docker/blob/main/samples/aspnetapp/Dockerfile.alpine-x64-slim

These .NET 7 Dockerfiles work fine (my branch):

- https://github.com/richlander/dotnet-docker/blob/samples7/samples/aspnetapp/Dockerfile
- https://github.com/richlander/dotnet-docker/blob/samples7/samples/aspnetapp/Dockerfile.alpine-x64

This .NET 7 one doesn't (my branch):

- https://github.com/richlander/dotnet-docker/blob/samples7/samples/aspnetapp/Dockerfile.alpine-x64-slim

Instructions:

```bash
rich@kamloops:~/git/dotnet-docker/samples/aspnetapp$ docker build --pull -t testapp-alpine-slim -f Dockerfile.alpine-x64-slim .
rich@kamloops:~/git/dotnet-docker/samples/aspnetapp$ docker run --rm -it -p 8001:80 testapp-alpine-slim
```

I had to refresh the page multiple times to see the bad output.

You can also test the .NET 6 sample from https://mcr.microsoft.com/en-us/product/dotnet/samples/about.

**Comment by jtschuster** [comment] 2022-08-12 00:16
My initial thought is that this is related to the change to trim everything by default. If you add `/p:TrimMode=partial` to the publish command does the same thing happen?

**Comment by jkotas** [comment] 2022-08-12 03:03
TrimMode partial is automatically set for ASP.NET apps here: https://github.com/dotnet/sdk/blob/83a2f2ca7fec1a7482b1bcc41aacb25e7af8ac89/src/WebSdk/Publish/Targets/Microsoft.NET.Sdk.Publish.targets#L89-L90

> I had to refresh the page multiple times to see the bad output.

This suggests that the problem is not caused by trimming, but by one of the tiering schemes we have in the product (JIT tiering, reflection invoke tiering, ASP.NET invokers tiering, ...). Does this repro with Trimming disable? Tiered compilation disable? R2R disabled?

**Comment by MichalStrehovsky** [comment] 2022-08-12 03:49
Trimming removes the R2R and PGO data so it would have all sorts of effects on codegen. I would place my bet around UTF-8 transcoding getting a `+1` somewhere.

**Comment by richlander** [comment] 2022-08-12 05:03
I just re-tested it. It repros after I refresh the page six times in a row. I'm not sure if it is reliably that number, but that obviously doesn't matter.

I re-tested a variety of scenarios. It repros with this (for both `linux-x64` and `linux-musl-x64` RIDs):

```bash
RUN dotnet publish -c Release -o /app -r linux-x64 --self-contained true --no-restore /p:PublishReadyToRun=true /p:PublishSingleFile=true
```

If I remove either of those two `Publish*` properties, the issues doesn't repro.

If I add the `TieredCompilation` properties, it doesn't repo.

```bash
RUN dotnet publish -c Release -o /app -r linux-x64 --self-contained true --no-restore /p:PublishReadyToRun=true /p:PublishSingleFile=true /p:TieredCompilation=false
```

It appears to have nothing to do with trimming. It does however suggest that there is a bad interaction between single file, R2R, and tiering. Good call Jan.

**Comment by jkotas** [comment] 2022-08-12 07:50
This is most likely a codegen issue.

**Comment by jakobbotsch** [comment] 2022-08-12 08:02
I'll investigate.

**Comment by jakobbotsch** [comment] 2022-08-12 09:09
Are there instructions somewhere for how I can swap out bits in the single-file published build?

**Comment by jakobbotsch** [comment] 2022-08-12 16:21
Using event pipe and some guesses I managed to create a self contained example:
```csharp
using System;
using System.Buffers;
using System.Linq;
using System.Reflection;
using System.Text.Encodings.Web;
using System.Threading;

public class Program
{
    public static void Main()
    {
        var enc = HtmlEncoder.Default;
        object o = enc.GetType().GetField("_innerEncoder", BindingFlags.NonPublic | BindingFlags.Instance).GetValue(enc);
        EncodeDelegate del = o.GetType().GetMethod("Encode").CreateDelegate<EncodeDelegate>(o);

        char[] chars = new char[50];
        char[] input = string.Concat(Enumerable.Repeat("foo bar this is a test 12345 GiB hmm", 100)).ToCharArray();

        for (int i = 0; i < 100; i++)
        {
            ReadOnlySpan<char> inputSpan = input;
            Span<char> output = chars;
            while (inputSpan.Length > 0)
            {
                del(inputSpan, output, out int charsConsumed, out int charsWritten, true);
                Console.Write(output[0..charsWritten].ToString());
                inputSpan = inputSpan[charsConsumed..];
                Thread.Sleep(25);
            }

            Console.WriteLine(new string(chars, 0, chars.Length - output.Length));
        }
    }

    delegate OperationStatus EncodeDelegate(ReadOnlySpan<char> source, Span<char> dest, out int charsConsumed, out int charsWritten, bool isFinalBlock);
}
```

Which outputs:
```scala
...snip...
foo bar this is a test 12345 GiBfoo bar this is a
test 12345 GiBfoo bar this is a test 12345 GiBfoo
bar this is a test 12345 GiBfoo bar this is a test
 12345 GiBfoo bar this is a test 12345 GiBfoo bar
this is a test 12345 GiBfoo bar this is a test 123
56!HjCgpp!cbs!uijt!jt!b!uftu!23456!HjCgpp!cbs!uijt
!jt!b!uftu!23456!HjCgpp!cbs!uijt!jt!b!uftu!23456!H
jCgpp!cbs!uijt!jt!b!uftu!23456!HjCgpp!cbs!uijt!jt!
b!uftu!23456!HjCgpp!cbs!uijt!jt!b!uftu!23456!HjCgp
p!cbs!uijt!jt!b!uftu!23456!HjCgpp!cbs!uijt!jt!b!uf
tu!23456!HjCgpp!cbs!uijt!jt!b!uftu!23456!HjCgpp!cb
```
when built with
```scala
dotnet publish -c Release -o app -r linux-x64 --self-contained true /p:PublishReadyToRun=true /p:PublishSingleFile=true
```
So seems like `OptimizedInboxTextEncoder.Encode` is the culprit.

**Comment by jakobbotsch** [comment] 2022-08-12 16:55
Hmm, seems likely this is the same problem as #73728 actually. The assertion from there:
```scala
Assert failure(PID 13708 [0x0000358c], Thread: 3532 [0x0dcc]): Verify_FieldOffset 'System.Text.Encodings.Web.OptimizedInboxTextEncoder._allowedAsciiCodePoints' Field offset 16!=24(actual) || baseOffset 8!=8(actual)
```

**Comment by jakobbotsch** [comment] 2022-08-12 17:17
Diff between R2R and runtime code:
https://www.diffchecker.com/abWxBrQ0

There are diffs like:
```diff
-lea    rcx, [r12 + 0x20]
+lea    rsi, [r12 + 0x28]
```
where `r12` is the `this` pointer.

I'll move this to crossgen2.
cc @trylek

**Comment by JulieLeeMSFT** [comment] 2022-08-12 17:18
> Hmm, seems likely this is the same problem as #73728 actually. The assertion from there:
> 
> ```scala
> Assert failure(PID 13708 [0x0000358c], Thread: 3532 [0x0dcc]): Verify_FieldOffset 'System.Text.Encodings.Web.OptimizedInboxTextEncoder._allowedAsciiCodePoints' Field offset 16!=24(actual) || baseOffset 8!=8(actual)
> ```

@mangod9 @trylek

**Comment by mangod9** [comment] 2022-08-12 17:30
#73728 is related to composite mode (ah SingleFile is enforcing composite mode now I guess), so that is the likely cause.

**Comment by jakobbotsch** [comment] 2022-08-12 17:32
Right yeah, I was just looking at that. The normal R2R code looks completely different for that function, and indeed, it repros with composite mode too (and without single-file mode).

**Comment by mangod9** [comment] 2022-08-12 18:00
ok, Tomas will investigate a fix next week.

**Comment by mangod9** [comment] 2022-08-22 15:55
@trylek this is a dupe of the field layout fix you made recently. Assume this can be closed out too?

**Comment by trylek** [comment] 2022-08-22 19:06
Right, this was fixed last week and Jeff has already merged its backport into the .NET 7 RC1 branch, I believe this issue is safe to close.

**Closed by trylek** 2022-08-22 19:06 UTC
Labels: blocking-release, area-crossgen2-coreclr
