### ISSUE TITLE
[Perf -40%] System.Tests.Perf_Char.Char_ToUpperInvariant

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#39723] opened 2020-07-21 17:14 UTC
### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Changes | [diff](https://github.com/dotnet/runtime/compare/cf774155778050ad93a9158caf389e26d49f1411...bf0076c80b9b2f1d2080016c7c7edb66ed61fa73)

### Regressions in System.Tests.Perf_Char

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier
-- | -- | -- | -- | -- | --
Char_ToUpperInvariant | 23.68 ns | 33.19 ns | 1.40 | Bimodal | False

### Related Issue on x64 ubuntu
[[Perf -22%] System.Tests.Perf_Char.Char_IsLower](https://github.com/DrewScoggins/performance-2/issues/1100)

### Related Issue on x86 Windows
[[Perf -26%] System.Tests.Perf_Char.Char_IsLower](https://github.com/DrewScoggins/performance-2/issues/1088)

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_21_2020/refs/heads/master_x64_Windows%2010.0.18362/System.Tests.Perf_Char_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_21_2020/refs/heads/master_x64_Windows%2010.0.18362/System.Tests.Perf_Char.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Tests.Perf_Char*';
```
<details>

#### System.Tests.Perf_Char.Char_ToUpperInvariant(input: "Hello World!")

```log
[23.086 ; 24.576) | @@@@@@@@@@@@@@@@@@@@@@@@@@
[24.576 ; 25.113) | 
[25.113 ; 26.602) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[26.602 ; 27.868) | @@@@@@@@@@@@
[27.868 ; 29.169) | @@
[29.169 ; 30.659) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[30.659 ; 32.471) | 
[32.471 ; 34.031) | @@@@@@@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Changes | [diff](https://github.com/dotnet/runtime/compare/1d05f27bf92586e8b7e0d312194b83de6a35ba67...4c18fb2cea5a7e0123fee52e61139836be3362b4)

### Regressions in System.Tests.Perf_Char

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier
-- | -- | -- | -- | -- | --
Char_ToUpperInvariant | 26.47 ns | 28.70 ns | 1.08 |  | True
Char_IsUpper | 60.76 ns | 87.22 ns | 1.44 |  | True

### Related Issue on x86 Windows
[[Perf -26%] System.Tests.Perf_Char.Char_IsLower](https://github.com/DrewScoggins/performance-2/issues/1088)

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/08_04_2020/refs/heads/master_x64_Windows%2010.0.18362/System.Tests.Perf_Char_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/08_04_2020/refs/heads/master_x64_Windows%2010.0.18362/System.Tests.Perf_Char_2.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/08_04_2020/refs/heads/master_x64_Windows%2010.0.18362/System.Tests.Perf_Char.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Tests.Perf_Char*';
```
<details>

#### System.Tests.Perf_Char.Char_ToUpperInvariant(input: "Hello World!")

```log
[23.086 ; 24.214) | @
[24.214 ; 25.342) | 
[25.342 ; 26.157) | 
[26.157 ; 27.285) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[27.285 ; 28.184) | 
[28.184 ; 29.312) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[29.312 ; 30.440) | 
[30.440 ; 31.568) | 
[31.568 ; 32.727) | 
[32.727 ; 34.001) | @@@@@@@@@@@@@@
```
#### System.Tests.Perf_Char.Char_IsUpper(input: "Good afternoon, Constable!")

```log
[58.177 ; 64.350) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[64.350 ; 70.523) | 
[70.523 ; 76.696) | 
[76.696 ; 84.208) | 
[84.208 ; 92.195) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[92.195 ; 98.368) | @
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by tarekgh** [comment] 2020-07-21 18:56
@DrewScoggins I am seeing you have assigned @kunalspathak to this issue. is he doing anything with that?

**Comment by kunalspathak** [comment] 2020-07-21 20:17
> @DrewScoggins I am seeing you have assigned @kunalspathak to this issue. is he doing anything with that?

My initial investigation is to check if this is because of codegen or something else by diffing the assembly code between baseline vs. test and go from there.

**Comment by tarekgh** [comment] 2020-07-21 20:25
@kunalspathak thanks for the info. please update the issue when you have more news. I was asking because I am already looking at some perf issues related of using ICU.

**Comment by danmosemsft** [comment] 2020-08-05 20:41
Do you guys actually repro this? Here is what I get with latest bits:
```
2020/08/05 13:35:52][INFO] // * Summary *
[2020/08/05 13:35:52][INFO]
[2020/08/05 13:35:52][INFO] BenchmarkDotNet=v0.12.1.1405-nightly, OS=Windows 10.0.19042
[2020/08/05 13:35:52][INFO] Intel Core i7-7700 CPU 3.60GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
[2020/08/05 13:35:52][INFO] .NET Core SDK=5.0.100-rc.1.20405.4
[2020/08/05 13:35:52][INFO]   [Host]     : .NET Core 3.1.6 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.31603), X64 RyuJIT
[2020/08/05 13:35:52][INFO]   Job-QGREIZ : .NET Core 3.1.6 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.31603), X64 RyuJIT
[2020/08/05 13:35:52][INFO]
[2020/08/05 13:35:52][INFO] PowerPlanMode=00000000-0000-0000-0000-000000000000  Runtime=.NET Core 3.1  Arguments=/p:DebugType=portable
[2020/08/05 13:35:52][INFO] Toolchain=netcoreapp3.1  IterationTime=250.0000 ms  MaxIterationCount=20
[2020/08/05 13:35:52][INFO] MinIterationCount=15  WarmupCount=1
[2020/08/05 13:35:52][INFO]
[2020/08/05 13:35:52][INFO] |                Method | c | cultureName |                      input |       Mean |     Error |    StdDev |     Median |        Min |        Max | Gen 0 | Gen 1 | Gen 2 | Allocated |
[2020/08/05 13:35:52][INFO] |---------------------- |-- |------------ |--------------------------- |-----------:|----------:|----------:|-----------:|-----------:|-----------:|------:|------:|------:|----------:|
[2020/08/05 13:35:52][INFO] |    GetUnicodeCategory | . |           ? |                          ? |  0.2506 ns | 0.0141 ns | 0.0118 ns |  0.2531 ns |  0.2252 ns |  0.2668 ns |     - |     - |     - |         - |
[2020/08/05 13:35:52][INFO] |          Char_ToLower | A |       en-US |                          ? |  4.0017 ns | 0.0617 ns | 0.0577 ns |  4.0169 ns |  3.8711 ns |  4.0822 ns |     - |     - |     - |         - |
[2020/08/05 13:35:52][INFO] |          Char_ToUpper | A |       en-US |                          ? |  4.6869 ns | 0.5509 ns | 0.6344 ns |  4.3569 ns |  4.0834 ns |  6.2298 ns |     - |     - |     - |         - |
[2020/08/05 13:35:52][INFO] |          Char_IsLower | ? |           ? | Good afternoon, Constable! | 62.4100 ns | 1.8153 ns | 1.9424 ns | 62.6970 ns | 58.5379 ns | 65.9387 ns |     - |     - |     - |         - |
[2020/08/05 13:35:52][INFO] |          Char_IsUpper | ? |           ? | Good afternoon, Constable! | 75.8917 ns | 0.9247 ns | 0.8650 ns | 75.9801 ns | 73.9466 ns | 77.4422 ns |     - |     - |     - |         - |
[2020/08/05 13:35:52][INFO] | Char_ToUpperInvariant | ? |           ? |               Hello World! | 51.2258 ns | 1.0132 ns | 0.9951 ns | 50.9326 ns | 50.0946 ns | 53.4753 ns |     - |     - |     - |         - |
[2020/08/05 13:35:52][INFO] | Char_ToLowerInvariant | ? |           ? |               Hello World! | 52.2148 ns | 1.2669 ns | 1.3556 ns | 51.6066 ns | 50.0324 ns | 54.7427 ns |     - |     - |     - |         - |
[2020/08/05 13:35:52][INFO] |          Char_ToLower | a |       en-US |                          ? |  4.5142 ns | 0.1568 ns | 0.1611 ns |  4.5032 ns |  4.2856 ns |  4.8385 ns |     - |     - |     - |         - |
[2020/08/05 13:35:52][INFO] |          Char_ToUpper | a |       en-US |                          ? |  4.1490 ns | 0.0955 ns | 0.0797 ns |  4.1623 ns |  4.0424 ns |  4.2861 ns |     - |     - |     - |         - |
[2020/08/05 13:35:52][INFO] |    GetUnicodeCategory | a |           ? |                          ? |  0.2299 ns | 0.0181 ns | 0.0169 ns |  0.2279 ns |  0.2097 ns |  0.2591 ns |     - |     - |     - |         - |
[2020/08/05 13:35:52][INFO] |          Char_ToLower | I |       en-US |                          ? | 46.0967 ns | 0.4310 ns | 0.4032 ns | 46.0461 ns | 45.4633 ns | 46.7857 ns |     - |     - |     - |         - |
[2020/08/05 13:35:52][INFO] |          Char_ToUpper | I |       en-US |                          ? | 46.2747 ns | 0.5226 ns | 0.4888 ns | 46.2215 ns | 45.4795 ns | 47.0246 ns |     - |     - |     - |         - |
[2020/08/05 13:35:52][INFO] |    GetUnicodeCategory | ? |           ? |                          ? |  2.1269 ns | 0.0509 ns | 0.0476 ns |  2.1150 ns |  2.0745 ns |  2.2235 ns |     - |     - |     - |         - |
[2020/08/05 13:35:52][INFO] |          Char_ToLower | ? |     zh-Hans |                          ? | 46.7511 ns | 0.9459 ns | 0.8385 ns | 46.7376 ns | 45.5305 ns | 48.7146 ns |     - |     - |     - |         - |
[2020/08/05 13:35:52][INFO] |          Char_ToUpper | ? |     zh-Hans |                          ? | 46.4638 ns | 0.5388 ns | 0.5040 ns | 46.5219 ns | 45.7887 ns | 47.5911 ns |     - |     - |     - |         - |
[2020/08/05 13:35:52][INFO]

[2020/08/05 13:38:26][INFO] BenchmarkDotNet=v0.12.1.1405-nightly, OS=Windows 10.0.19042
[2020/08/05 13:38:26][INFO] Intel Core i7-7700 CPU 3.60GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
[2020/08/05 13:38:26][INFO] .NET Core SDK=5.0.100-rc.1.20405.4
[2020/08/05 13:38:26][INFO]   [Host]     : .NET Core 5.0.0 (CoreCLR 5.0.20.40416, CoreFX 5.0.20.40416), X64 RyuJIT
[2020/08/05 13:38:26][INFO]   Job-HWKUEZ : .NET Core 5.0.0 (CoreCLR 5.0.20.40416, CoreFX 5.0.20.40416), X64 RyuJIT
[2020/08/05 13:38:26][INFO]
[2020/08/05 13:38:26][INFO] PowerPlanMode=00000000-0000-0000-0000-000000000000  Runtime=.NET Core 5.0  Arguments=/p:DebugType=portable
[2020/08/05 13:38:26][INFO] Toolchain=netcoreapp5.0  IterationTime=250.0000 ms  MaxIterationCount=20
[2020/08/05 13:38:26][INFO] MinIterationCount=15  WarmupCount=1
[2020/08/05 13:38:26][INFO]
[2020/08/05 13:38:26][INFO] |                Method | c | cultureName |                      input |       Mean |     Error |    StdDev |     Median |        Min |        Max | Gen 0 | Gen 1 | Gen 2 | Allocated |
[2020/08/05 13:38:26][INFO] |---------------------- |-- |------------ |--------------------------- |-----------:|----------:|----------:|-----------:|-----------:|-----------:|------:|------:|------:|----------:|
[2020/08/05 13:38:26][INFO] |    GetUnicodeCategory | . |           ? |                          ? |  0.2743 ns | 0.0193 ns | 0.0180 ns |  0.2753 ns |  0.2518 ns |  0.3047 ns |     - |     - |     - |         - |
[2020/08/05 13:38:26][INFO] |          Char_ToLower | A |       en-US |                          ? |  3.0765 ns | 0.0540 ns | 0.0505 ns |  3.0935 ns |  3.0033 ns |  3.1634 ns |     - |     - |     - |         - |
[2020/08/05 13:38:26][INFO] |          Char_ToUpper | A |       en-US |                          ? |  3.9030 ns | 0.0603 ns | 0.0535 ns |  3.8879 ns |  3.8150 ns |  3.9967 ns |     - |     - |     - |         - |
[2020/08/05 13:38:26][INFO] |          Char_IsLower | ? |           ? | Good afternoon, Constable! | 45.2696 ns | 0.7102 ns | 0.6643 ns | 45.1461 ns | 44.5217 ns | 46.5520 ns |     - |     - |     - |         - |
[2020/08/05 13:38:26][INFO] |          Char_IsUpper | ? |           ? | Good afternoon, Constable! | 49.7416 ns | 0.4748 ns | 0.3965 ns | 49.7288 ns | 49.1926 ns | 50.4262 ns |     - |     - |     - |         - |
[2020/08/05 13:38:26][INFO] | Char_ToUpperInvariant | ? |           ? |               Hello World! | 22.0601 ns | 0.3785 ns | 0.3355 ns | 22.0315 ns | 21.6714 ns | 22.7502 ns |     - |     - |     - |         - |
[2020/08/05 13:38:26][INFO] | Char_ToLowerInvariant | ? |           ? |               Hello World! | 26.5752 ns | 0.3419 ns | 0.2855 ns | 26.6111 ns | 26.1321 ns | 27.0054 ns |     - |     - |     - |         - |
[2020/08/05 13:38:26][INFO] |          Char_ToLower | a |       en-US |                          ? |  3.3169 ns | 0.0736 ns | 0.0652 ns |  3.2990 ns |  3.2390 ns |  3.4313 ns |     - |     - |     - |         - |
[2020/08/05 13:38:26][INFO] |          Char_ToUpper | a |       en-US |                          ? |  3.6122 ns | 0.0644 ns | 0.0603 ns |  3.6143 ns |  3.4783 ns |  3.6876 ns |     - |     - |     - |         - |
[2020/08/05 13:38:26][INFO] |    GetUnicodeCategory | a |           ? |                          ? |  0.2784 ns | 0.0207 ns | 0.0184 ns |  0.2706 ns |  0.2564 ns |  0.3202 ns |     - |     - |     - |         - |
[2020/08/05 13:38:26][INFO] |          Char_ToLower | I |       en-US |                          ? | 21.0881 ns | 0.2754 ns | 0.2576 ns | 21.1128 ns | 20.6936 ns | 21.5121 ns |     - |     - |     - |         - |
[2020/08/05 13:38:26][INFO] |          Char_ToUpper | I |       en-US |                          ? | 19.8264 ns | 0.2733 ns | 0.2556 ns | 19.7476 ns | 19.5077 ns | 20.3432 ns |     - |     - |     - |         - |
[2020/08/05 13:38:26][INFO] |    GetUnicodeCategory | ? |           ? |                          ? |  4.1110 ns | 0.0574 ns | 0.0537 ns |  4.1269 ns |  4.0240 ns |  4.1690 ns |     - |     - |     - |         - |
[2020/08/05 13:38:26][INFO] |          Char_ToLower | ? |     zh-Hans |                          ? | 21.9396 ns | 0.2983 ns | 0.2644 ns | 21.8734 ns | 21.5799 ns | 22.4682 ns |     - |     - |     - |         - |
[2020/08/05 13:38:26][INFO] |          Char_ToUpper | ? |     zh-Hans |                          ? | 21.4260 ns | 0.1817 ns | 0.1611 ns | 21.4737 ns | 21.0646 ns | 21.6372 ns |     - |     - |     - |         - |
```
We seem a lot faster than in 3.1

**Comment by kunalspathak** [comment] 2020-08-05 20:47
We might be faster compared to .NET 3.1, but I think this issue compares between July15 vs. July 21. Another related issue that we triaged yesterday was https://github.com/DrewScoggins/performance-2/issues/1168. I will again spend some time this week to make sure that it is not JIT related and if ICU has to do anything with it.

@tarekgh - In case, I can't repro this, is it possible that it is because of culture/language setting on my dev machine vs. the ones that runs in lab which might trigger different code path for isUpper?

**Comment by danmosemsft** [comment] 2020-08-05 20:47
Here are results with `set DOTNET_SYSTEM_GLOBALIZATION_USENLS=1` a little slower (interestingly - cc @safern) but still better than 3.1.
```
[2020/08/05 13:45:26][INFO] BenchmarkDotNet=v0.12.1.1405-nightly, OS=Windows 10.0.19042
[2020/08/05 13:45:26][INFO] Intel Core i7-7700 CPU 3.60GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
[2020/08/05 13:45:26][INFO] .NET Core SDK=5.0.100-rc.1.20405.4
[2020/08/05 13:45:26][INFO]   [Host]     : .NET Core 5.0.0 (CoreCLR 5.0.20.40416, CoreFX 5.0.20.40416), X64 RyuJIT
[2020/08/05 13:45:26][INFO]   Job-AOJOYB : .NET Core 5.0.0 (CoreCLR 5.0.20.40416, CoreFX 5.0.20.40416), X64 RyuJIT
[2020/08/05 13:45:26][INFO]
[2020/08/05 13:45:26][INFO] PowerPlanMode=00000000-0000-0000-0000-000000000000  Runtime=.NET Core 5.0  Arguments=/p:DebugType=portable
[2020/08/05 13:45:26][INFO] Toolchain=netcoreapp5.0  IterationTime=250.0000 ms  MaxIterationCount=20
[2020/08/05 13:45:26][INFO] MinIterationCount=15  WarmupCount=1
[2020/08/05 13:45:26][INFO]
[2020/08/05 13:45:26][INFO] |                Method | c | cultureName |                      input |       Mean |     Error |    StdDev |     Median |        Min |        Max | Gen 0 | Gen 1 | Gen 2 | Allocated |
[2020/08/05 13:45:26][INFO] |---------------------- |-- |------------ |--------------------------- |-----------:|----------:|----------:|-----------:|-----------:|-----------:|------:|------:|------:|----------:|
[2020/08/05 13:45:26][INFO] |    GetUnicodeCategory | . |           ? |                          ? |  0.3343 ns | 0.0205 ns | 0.0192 ns |  0.3335 ns |  0.3017 ns |  0.3600 ns |     - |     - |     - |         - |
[2020/08/05 13:45:26][INFO] |          Char_ToLower | A |       en-US |                          ? |  3.0331 ns | 0.0489 ns | 0.0382 ns |  3.0331 ns |  2.9689 ns |  3.1147 ns |     - |     - |     - |         - |
[2020/08/05 13:45:26][INFO] |          Char_ToUpper | A |       en-US |                          ? |  3.0293 ns | 0.0488 ns | 0.0457 ns |  3.0379 ns |  2.9443 ns |  3.0976 ns |     - |     - |     - |         - |
[2020/08/05 13:45:26][INFO] |          Char_IsLower | ? |           ? | Good afternoon, Constable! | 51.0696 ns | 0.5837 ns | 0.5460 ns | 51.1462 ns | 50.1148 ns | 52.1184 ns |     - |     - |     - |         - |
[2020/08/05 13:45:26][INFO] |          Char_IsUpper | ? |           ? | Good afternoon, Constable! | 58.4978 ns | 0.7533 ns | 0.6678 ns | 58.7088 ns | 57.2868 ns | 59.3689 ns |     - |     - |     - |         - |
[2020/08/05 13:45:26][INFO] | Char_ToUpperInvariant | ? |           ? |               Hello World! | 26.7421 ns | 0.2518 ns | 0.2232 ns | 26.7493 ns | 26.4151 ns | 27.1780 ns |     - |     - |     - |         - |
[2020/08/05 13:45:26][INFO] | Char_ToLowerInvariant | ? |           ? |               Hello World! | 26.3330 ns | 0.2759 ns | 0.2580 ns | 26.3784 ns | 25.8960 ns | 26.8993 ns |     - |     - |     - |         - |
[2020/08/05 13:45:26][INFO] |          Char_ToLower | a |       en-US |                          ? |  3.3509 ns | 0.0435 ns | 0.0386 ns |  3.3347 ns |  3.3041 ns |  3.4292 ns |     - |     - |     - |         - |
[2020/08/05 13:45:26][INFO] |          Char_ToUpper | a |       en-US |                          ? |  2.9274 ns | 0.0363 ns | 0.0322 ns |  2.9309 ns |  2.8590 ns |  2.9717 ns |     - |     - |     - |         - |
[2020/08/05 13:45:26][INFO] |    GetUnicodeCategory | a |           ? |                          ? |  0.3502 ns | 0.0172 ns | 0.0160 ns |  0.3493 ns |  0.3232 ns |  0.3804 ns |     - |     - |     - |         - |
[2020/08/05 13:45:26][INFO] |          Char_ToLower | I |       en-US |                          ? | 51.0561 ns | 0.5036 ns | 0.4464 ns | 51.0981 ns | 50.2854 ns | 51.8301 ns |     - |     - |     - |         - |
[2020/08/05 13:45:26][INFO] |          Char_ToUpper | I |       en-US |                          ? | 51.6923 ns | 1.0112 ns | 1.0384 ns | 51.6310 ns | 50.1986 ns | 53.4795 ns |     - |     - |     - |         - |
[2020/08/05 13:45:26][INFO] |    GetUnicodeCategory | ? |           ? |                          ? |  3.6902 ns | 0.0581 ns | 0.0485 ns |  3.6870 ns |  3.6308 ns |  3.7750 ns |     - |     - |     - |         - |
[2020/08/05 13:45:26][INFO] |          Char_ToLower | ? |     zh-Hans |                          ? | 51.3770 ns | 0.9953 ns | 0.9310 ns | 51.4167 ns | 50.2670 ns | 53.2437 ns |     - |     - |     - |         - |
[2020/08/05 13:45:27][INFO] |          Char_ToUpper | ? |     zh-Hans |                          ? | 52.3680 ns | 1.0033 ns | 0.9385 ns | 51.9494 ns | 51.2888 ns | 53.8368 ns |     - |     - |     - |         - |
[2020/08/05 13:45:27][INFO]
```

**Comment by tarekgh** [comment] 2020-08-05 20:54
> In case, I can't repro this, is it possible that it is because of culture/language setting on my dev machine vs. the ones that runs in lab which might trigger different code path for isUpper?

Invariant culture tests shouldn't be affected by the settings. Char casing depends on the current culture. from what @danmosemsft pasted, looks the test is explicit using specific cultures which means the machine settings shouldn't affect the test.

I am noticing culture names "?" which I am not sure what is it. is it the Invariant?

**Comment by kunalspathak** [comment] 2020-08-05 21:21
> Invariant culture tests shouldn't be affected by the settings. Char casing depends on the current culture. from what @danmosemsft pasted, looks the test is explicit using specific cultures which means the machine settings shouldn't affect the test.
> 
> I am noticing culture names "?" which I am not sure what is it. is it the Invariant?

Input contains non-ascii inputs with Chinese culture. Source code [here](https://github.com/dotnet/runtime/issues/39723#issuecomment-669502919).

**Comment by tarekgh** [comment] 2020-08-05 21:43
@kunalspathak I think you meant the source https://github.com/dotnet/performance/blob/1c160f6fd074d104e6de39b2fae48d657673a5ab/src/benchmarks/micro/libraries/System.Runtime/Perf.Char.cs

looking at that, the tests that takes `Char_ChangeCase_MemberData` like https://github.com/dotnet/performance/blob/1c160f6fd074d104e6de39b2fae48d657673a5ab/src/benchmarks/micro/libraries/System.Runtime/Perf.Char.cs#L54 shouldn't be affected by the settings. 

The rest of tests which takes literal strings can be affected by setting current culture. but most of passed strings are Ascii which we have some optimization for this scenario. but it is possible this affected by the settings.

**Comment by kunalspathak** [comment] 2020-08-06 18:25
I pulled out the latest graph of `Char_ToUpperInvariant()` reported in DrewScoggins/performance-2#1168.

![image](https://user-images.githubusercontent.com/12488060/89567640-d84b2d00-d7d6-11ea-855d-5e54986dcf67.png)

So essentially, the regression of `33.19ns` reported here doesn't show up in latest data. However, the measurements stays to `~26.62ns` and then around Aug 4, goes to `28.70ns`.

So my interpretation of that data is, from July 15 to Aug 4 is `23.68ns` ->  `26.62ns` -> `28.70ns`.

@tarekgh - Were there any ICU changes done during that time that could affect the test?

**Comment by DrewScoggins** [comment] 2020-08-07 01:17
I just updated this issue with the other tests in this same vein that are regressing.

**Comment by kunalspathak** [comment] 2020-08-07 01:35
I am not able to repro the regression in `IsUpper()`. But I am able to consistently repro the regression in `ToUpperInvariant()`. 

I came up with standalone app removing benchmark-dotnet.
```csharp
Stopwatch st = new Stopwatch();
st.Start();
ToUpperInvariant toUpper = new ToUpperInvariant();
for (int i = 0; i < 1000 * 1000 * 200; i++)
{
  toUpper.Char_ToUpperInvariant("Hello World!");
}
st.Stop();
Console.WriteLine("Time: " + st.ElapsedMilliseconds + " msec.");
```

Base = 4f703e60c34
Test = 4c18fb2cea5
```cmd
Base: 6169 msec.
Test: 6960 msec.
```

Profile data doesn't show anything JIT related (left is base, right is test)

![image](https://user-images.githubusercontent.com/12488060/89598666-3a755380-d812-11ea-9b5b-f96bb169c574.png)

Looks like we need further investigation in `ToUpperInvariant()`

![image](https://user-images.githubusercontent.com/12488060/89598859-cab39880-d812-11ea-96b5-06edc931b8c0.png)

@safern @tarekgh @krwq

**Comment by kunalspathak** [comment] 2020-08-07 01:36
@tarekgh  - I am assigning bug to you.

**Comment by kunalspathak** [comment] 2020-08-07 01:43
I was not able to repro `Char_IsUpper()` regression between 4f703e6 and 4c18fb2. I also didn't see any JIT difference.

**Comment by tarekgh** [comment] 2020-08-07 02:07
I'll take a look later.

@DrewScoggins This issue marked with x64 tag. is this the case or the same regression show up on other architectures? if the ICU is the reason of the regression I expect to see it on all architectures.

**Comment by safern** [comment] 2020-08-07 02:12
@tarekgh something to note is that the regression is way after the move to use ICU on Windows.

**Comment by adamsitnik** [comment] 2020-08-17 19:14
This is not caused by ICU and 5.0 is much faster than 3.1 (3x). Closing

|                Method |        input | 3.1 Mean |  5.0 ICU |  5.0 NLS |
|---------------------- |------------- |---------:|---------:|---------:|
| Char_ToUpperInvariant | Hello World! | 59.53 ns | 19.93 ns | 24.94 ns |

Codgen can be found in the details below:

<details>

## .NET Core 3.1.6 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.31603), X64 RyuJIT
```assembly
; System.Tests.Perf_Char.Char_ToUpperInvariant(System.String)
       7FFB7E3C3BC0 push      r14
       7FFB7E3C3BC2 push      rdi
       7FFB7E3C3BC3 push      rsi
       7FFB7E3C3BC4 push      rbp
       7FFB7E3C3BC5 push      rbx
       7FFB7E3C3BC6 sub       rsp,20
       7FFB7E3C3BCA mov       rsi,rdx
       7FFB7E3C3BCD xor       edi,edi
       7FFB7E3C3BCF xor       ebx,ebx
       7FFB7E3C3BD1 mov       ebp,[rsi+8]
       7FFB7E3C3BD4 test      ebp,ebp
       7FFB7E3C3BD6 jle       short M00_L01
M00_L00:
       7FFB7E3C3BD8 movsxd    rcx,ebx
       7FFB7E3C3BDB movzx     r14d,word ptr [rsi+rcx*2+0C]
       7FFB7E3C3BE1 mov       rcx,1CE10002448
       7FFB7E3C3BEB mov       rcx,[rcx]
       7FFB7E3C3BEE call      qword ptr [7FFB7E3CA400]
       7FFB7E3C3BF4 mov       rcx,rax
       7FFB7E3C3BF7 mov       edx,r14d
       7FFB7E3C3BFA mov       rax,[rax]
       7FFB7E3C3BFD mov       rax,[rax+48]
       7FFB7E3C3C01 call      qword ptr [rax+30]
       7FFB7E3C3C04 add       edi,eax
       7FFB7E3C3C06 inc       ebx
       7FFB7E3C3C08 cmp       ebp,ebx
       7FFB7E3C3C0A jg        short M00_L00
M00_L01:
       7FFB7E3C3C0C mov       eax,edi
       7FFB7E3C3C0E add       rsp,20
       7FFB7E3C3C12 pop       rbx
       7FFB7E3C3C13 pop       rbp
       7FFB7E3C3C14 pop       rsi
       7FFB7E3C3C15 pop       rdi
       7FFB7E3C3C16 pop       r14
       7FFB7E3C3C18 ret
; Total bytes of code 89
```
```assembly
; System.Globalization.CultureInfo.get_TextInfo()
       7FFB7E3C5250 push      rdi
       7FFB7E3C5251 push      rsi
       7FFB7E3C5252 sub       rsp,28
       7FFB7E3C5256 mov       rsi,rcx
       7FFB7E3C5259 cmp       qword ptr [rsi+10],0
       7FFB7E3C525E jne       short M01_L00
       7FFB7E3C5260 mov       rcx,offset MT_System.Globalization.TextInfo
       7FFB7E3C526A call      CORINFO_HELP_NEWSFAST
       7FFB7E3C526F mov       rdi,rax
       7FFB7E3C5272 mov       rdx,[rsi+30]
       7FFB7E3C5276 mov       rcx,rdi
       7FFB7E3C5279 call      System.Globalization.TextInfo..ctor(System.Globalization.CultureData)
       7FFB7E3C527E movzx     edx,byte ptr [rsi+60]
       7FFB7E3C5282 mov       [rdi+30],dl
       7FFB7E3C5285 lea       rcx,[rsi+10]
       7FFB7E3C5289 mov       rdx,rdi
       7FFB7E3C528C call      CORINFO_HELP_ASSIGN_REF
M01_L00:
       7FFB7E3C5291 mov       rax,[rsi+10]
       7FFB7E3C5295 add       rsp,28
       7FFB7E3C5299 pop       rsi
       7FFB7E3C529A pop       rdi
       7FFB7E3C529B ret
; Total bytes of code 76
```

## .NET Core 5.0.0 (CoreCLR 5.0.20.40416, CoreFX 5.0.20.40416), X64 RyuJIT
```assembly
; System.Tests.Perf_Char.Char_ToUpperInvariant(System.String)
       7FFB906720F0 push      rdi
       7FFB906720F1 push      rsi
       7FFB906720F2 push      rbp
       7FFB906720F3 push      rbx
       7FFB906720F4 sub       rsp,28
       7FFB906720F8 mov       rsi,rdx
       7FFB906720FB xor       edi,edi
       7FFB906720FD xor       ebx,ebx
       7FFB906720FF mov       ebp,[rsi+8]
       7FFB90672102 test      ebp,ebp
       7FFB90672104 jle       short M00_L01
M00_L00:
       7FFB90672106 movsxd    rcx,ebx
       7FFB90672109 movzx     ecx,word ptr [rsi+rcx*2+0C]
       7FFB9067210E call      System.Globalization.TextInfo.ToUpperInvariant(Char)
       7FFB90672113 movzx     eax,ax
       7FFB90672116 add       edi,eax
       7FFB90672118 inc       ebx
       7FFB9067211A cmp       ebp,ebx
       7FFB9067211C jg        short M00_L00
M00_L01:
       7FFB9067211E mov       eax,edi
       7FFB90672120 add       rsp,28
       7FFB90672124 pop       rbx
       7FFB90672125 pop       rbp
       7FFB90672126 pop       rsi
       7FFB90672127 pop       rdi
       7FFB90672128 ret
; Total bytes of code 57
```
```assembly
; System.Globalization.TextInfo.ToUpperInvariant(Char)
       7FFB90674780 movzx     edx,cx
       7FFB90674783 cmp       edx,7F
       7FFB90674786 ja        short M01_L01
       7FFB90674788 mov       eax,edx
       7FFB9067478A lea       ecx,[rax+0FF9F]
       7FFB9067478D cmp       ecx,19
       7FFB90674790 ja        short M01_L00
       7FFB90674792 and       eax,5F
M01_L00:
       7FFB90674795 ret
M01_L01:
       7FFB90674796 mov       rcx,27AB45316E0
       7FFB906747A0 mov       rcx,[rcx]
       7FFB906747A3 mov       r8d,1
       7FFB906747A9 cmp       [rcx],ecx
       7FFB906747AB jmp       near ptr System.Globalization.TextInfo.ChangeCase(Char, Boolean)
; Total bytes of code 48
```

</details>

**Closed by adamsitnik** 2020-08-17 19:14 UTC
Labels: arch-x64, area-System.Globalization, os-windows, tenet-performance, tenet-performance-benchmarks
