### ISSUE TITLE
Feature request: Add overloads for CancellationToken.[Unsafe]Register that pass the CancellationToken to the registered function 

### ISSUE THREAD

**Issue by geoffkizer** [dotnet/runtime#40475] opened 2020-08-06 17:13 UTC
## Background and Motivation

CancellationToken.Register and UnsafeRegister currently take callback arguments typed as either `Action` or `Action<object>` when used with user state.

It's very common for the registered callback to need to access the CancellationToken on which it is registered. For example, you often want to generate an OperationCanceledException with the original CancellationToken. Since the callback does not get passed this token, it needs to store it separately, often only for this specific purpose.

See for example: https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/CreditWaiter.cs#L51

## Proposed API

```csharp
struct CancellationToken
{
    public CancellationTokenRegistration Register(Action<object?, CancellationToken> callback, object? state);
    public CancellationTokenRegistration UnsafeRegister(Action<object?, CancellationToken> callback, object? state);
}
```

## Usage Examples

Considering the above example from CreditWaiter, this would allow the _cancellationToken field to be removed, and the code changed to the following:

```csharp
    _registration = cancellationToken.UnsafeRegister(static (token, s) =>
    {
        var thisRef = (CreditWaiter)s!;
        thisRef._source.SetException(ExceptionDispatchInfo.SetCurrentStackTrace(new OperationCanceledException(token)));
    }, this);
```

**Comment by stephentoub** [comment] 2020-08-06 19:01
Dup of https://github.com/dotnet/runtime/issues/24693

**Comment by tarekgh** [comment] 2020-08-07 16:53
@geoffkizer Closing as duplicate of #24693. Please let's know if you think otherwise.

**Comment by geoffkizer** [comment] 2020-10-01 03:59
I'm reopening this because I want to get the API reviewed, and this seems like the best issue to do it with (as opposed to editing the issue it's marked as a dupe of).

**Comment by geoffkizer** [comment] 2020-10-01 04:00
@stephentoub I marked this as api-ready-for-review. If you don't agree please let me know and remove the label.

**Comment by tarekgh** [comment] 2020-10-01 13:28
@geoffkizer do you see this is different than #24693? I am not opposing the proposal here. Just checking if we should close one of them if both same issue.

**Comment by stephentoub** [comment] 2020-10-01 17:43
Yes.

We might consider swapping the order of the arguments to the delegate, so that in all delegates the object state is first.

I'd also be happy with us not proactively adding:
```C#
public CancellationTokenRegistration Register(Action<CancellationToken, object> callback, object state, bool useSynchronizationContext);
```
and only adding it if someone actually comes forth with a good use case of it.  Passing true for useSynchronizationContext is very rare; I think I can count the number of times I've seen it on one hand.

Otherwise, it should be fine, and while there'll be a tad more overhead added due to needing to now check what kind of delegate is being used, it's unlikely to be measurable.

**Comment by tarekgh** [comment] 2020-10-01 17:50
@geoffkizer here is what @stephentoub suggested, let's know if you are ok with it.  

```C#
struct CancellationToken
{
    public CancellationTokenRegistration Register(Action<object, CancellationToken> callback, object state);
    public CancellationTokenRegistration UnsafeRegister(Action<object, CancellationToken> callback, object state);
}
```

**Comment by stephentoub** [comment] 2020-10-01 19:44
@tarekgh, I've edited your post above to also factor in nullable reference types.

**Comment by geoffkizer** [comment] 2020-10-01 19:50
LGTM

**Comment by tarekgh** [comment] 2020-10-01 20:01
Thanks all, 

I have updated the proposal in the top. pasting here the original proposal just for the record

```C#
struct CancellationToken
{
    public CancellationTokenRegistration Register(Action<CancellationToken, object> callback, object state);
    public CancellationTokenRegistration Register(Action<CancellationToken, object> callback, object state, bool useSynchronizationContext);
    public CancellationTokenRegistration UnsafeRegister(Action<CancellationToken, object> callback, object state);
}
```

**Comment by terrajobst** [comment] 2020-10-06 17:21
* Looks good as proposed

```C#
namespace System.Threading
{
    public struct CancellationToken
    {
        public CancellationTokenRegistration Register(Action<object?, CancellationToken> callback, object? state);
        public CancellationTokenRegistration UnsafeRegister(Action<object?, CancellationToken> callback, object? state);
    }
}
```

**Closed** 2020-10-09 01:57 UTC
Labels: api-approved, area-System.Threading.Tasks

**Comment by marek-safar** [comment] 2020-10-19 13:22
Why is the method signature forcing `object?` type for the state? Wouldn't be better to have something like this instead?

```c#
namespace System.Threading
{
    public struct CancellationToken
    {
        public CancellationTokenRegistration Register<T>(Action<T, CancellationToken> callback, T state);
        public CancellationTokenRegistration UnsafeRegister<T>(Action<T, CancellationToken> callback, T state);
    }
}
```

**Comment by stephentoub** [comment] 2020-10-19 13:30
> Why is the method signature forcing object? type for the state? Wouldn't be better to have something like this instead?

It would make the implementation much more expensive (e.g. right now the CancellationTokenSource can cache the objects used to store the registration, but that caching becomes a lot more challenging when it needs to differentiate by T), there's slightly more cost at runtime due to generic dictionaries when the state is a reference type, the vast, vast majority of usage has a reference type state such that the T saves very little in usability (just a cast) and nothing measurable in perf, ...

**Comment by marek-safar** [comment] 2020-10-19 13:49
Yes, I'm concern about usability for seasonal developers. The implementation would stay the same but instead of asking every user of this API to do an odd explicit cast with bang we could cast inside the API.

**Comment by stephentoub** [comment] 2020-10-19 14:16
> I'm concern about usability for seasonal developers

`object state` shows up in tons of APIs. Why this one in particular?  This overload is already for cases where developers are thinking through higher performance; otherwise, they'd just capture the state they need via closure.

**Comment by marek-safar** [comment] 2020-10-19 15:54
> How would the delegate be invoked?

Good point.
