### ISSUE TITLE
NullReferenceException is not producing any helpful information for releases

### ISSUE THREAD

**Issue by Kokujou** [dotnet/runtime#57488] opened 2021-08-16 11:05 UTC
This issue is now persistent for a very long time and caused a lot of problems in a project i'm working on.
Everytime a NullReferenceException occurs it never says anything about the parameter name the exception was thrown on.
Dpeending on the quality of the code this can cause really huge issues for testing and reproducing reported errors.

i know when you're debugigng code the debugger tells you what variable it is, but for release this information is not accessible.

i think it would benefit a lot of developers if this exception would generate a better error message, especially since the NullReferenceException is always bound to a parameter.

i didn't see any similar issues filed, so i hope this will get processed

**Comment by EgorBo** [comment] 2021-08-16 11:56
Duplicates https://github.com/dotnet/runtime/issues/3858

**Comment by mangod9** [comment] 2021-08-16 15:41
Closing as dupe of #3858 as mentioned above.

**Closed by mangod9** 2021-08-16 15:41 UTC
Labels: area-ExceptionHandling-coreclr, untriaged
