### ISSUE TITLE
Test failure in JIT\\Regression\\CLR-x86-JIT\\v2.1\\DDB\\B168384\\LdfldaHack\\LdfldaHack.cmd

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#32723] opened 2020-02-24 07:42 UTC
Job: [runtime-coreclr crossgen2 20200222.1](https://dev.azure.com/dnceng/public/_build/results?buildId=533488&view=ms.vss-test-web.build-test-results-tab&runId=16936268&resultId=102207&paneView=debug)

Error message
`
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.\r\n at LdfldaHack.Main()\r\n\r\nReturn code: 1\r\nRaw output file: C:\h\w\986B0834\w\9797088F\e\JIT\Regression\Reports\JIT.Regression\CLR-x86-JIT\v2.1\DDB\B168384\LdfldaHack\LdfldaHack.output.txt\r\nRaw output:\r\nBEGIN EXECUTION\r\n 1 file(s) copied.\r\n" "C:\h\w\986B0834\p\crossgen2\crossgen2" C:\h\w\986B0834\w\9797088F\e\JIT\Regression\CLR-x86-JIT\v2.1\DDB\B168384\LdfldaHack\LdfldaHack.org -o:C:\h\w\986B0834\w\9797088F\e\JIT\Regression\CLR-x86-JIT\v2.1\DDB\B168384\LdfldaHack\LdfldaHack.dll --targetarch:x64 -O --inputbubble -r:"C:\h\w\986B0834\p\System..dll" -r:"C:\h\w\986B0834\p\Microsoft..dll" -r:"C:\h\w\986B0834\p\mscorlib.dll" -r:C:\h\w\986B0834\w\9797088F\e\JIT\Regression\CLR-x86-JIT\v2.1\DDB\B168384\LdfldaHack\.dll"\r\nWarning: No files matching C:\h\w\986B0834\w\9797088F\e\JIT\Regression\CLR-x86-JIT\v2.1\DDB\B168384\LdfldaHack\.dll\r\nEmitting R2R PE file: C:\h\w\986B0834\w\9797088F\e\JIT\Regression\CLR-x86-JIT\v2.1\DDB\B168384\LdfldaHack\LdfldaHack.dll\r\n "C:\h\w\986B0834\p\corerun.exe" LdfldaHack.dll \r\nExpected: 100\r\nActual: -1073741819\r\nEND EXECUTION - FAILED\r\nFAILED\r\nTest Harness Exitcode is : 1\r\nTo run the test:\r\n> set CORE_ROOT=C:\h\w\986B0834\p\r\n> C:\h\w\986B0834\w\9797088F\e\JIT\Regression\CLR-x86-JIT\v2.1\DDB\B168384\LdfldaHack\LdfldaHack.cmd\r\nExpected: True\r\nActual: False
`

**Comment by AriNuer** [comment] 2020-03-04 06:02
Test `JIT\\Regression\\CLR-x86-JIT\\v2.1\\DDB\\B168384\\LdfldaHack\\LdfldaHack.cmd` failed again.

**Job:**
[runtime-coreclr crossgen2:#20200303.1](https://dev.azure.com/dnceng/public/_build/results?buildId=545735&view=results)

**Error message:**
`
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.\r\n at LdfldaHack.Main()\r\n\r\nReturn code: 1\r\nRaw output file: C:\h\w\AE250995\w\B90A09BE\e\JIT\Regression\Reports\JIT.Regression\CLR-x86-JIT\v2.1\DDB\B168384\LdfldaHack\LdfldaHack.output.txt\r\nRaw output:\r\nBEGIN EXECUTION\r\n 1 file(s) copied.\r\n" "C:\h\w\AE250995\p\crossgen2\crossgen2" C:\h\w\AE250995\w\B90A09BE\e\JIT\Regression\CLR-x86-JIT\v2.1\DDB\B168384\LdfldaHack\LdfldaHack.org -o:C:\h\w\AE250995\w\B90A09BE\e\JIT\Regression\CLR-x86-JIT\v2.1\DDB\B168384\LdfldaHack\LdfldaHack.dll --targetarch:x64 -O --inputbubble -r:"C:\h\w\AE250995\p\System..dll" -r:"C:\h\w\AE250995\p\Microsoft..dll" -r:"C:\h\w\AE250995\p\mscorlib.dll" -r:C:\h\w\AE250995\w\B90A09BE\e\JIT\Regression\CLR-x86-JIT\v2.1\DDB\B168384\LdfldaHack\.dll"\r\nWarning: No files matching C:\h\w\AE250995\w\B90A09BE\e\JIT\Regression\CLR-x86-JIT\v2.1\DDB\B168384\LdfldaHack\.dll\r\nEmitting R2R PE file: C:\h\w\AE250995\w\B90A09BE\e\JIT\Regression\CLR-x86-JIT\v2.1\DDB\B168384\LdfldaHack\LdfldaHack.dll\r\n "C:\h\w\AE250995\p\corerun.exe" LdfldaHack.dll \r\nExpected: 100\r\nActual: -1073741819\r\nEND EXECUTION - FAILED\r\nFAILED\r\nTest Harness Exitcode is : 1\r\nTo run the test:\r\n> set CORE_ROOT=C:\h\w\AE250995\p\r\n> C:\h\w\AE250995\w\B90A09BE\e\JIT\Regression\CLR-x86-JIT\v2.1\DDB\B168384\LdfldaHack\LdfldaHack.cmd\r\nExpected: True\r\nActual: False
`

**Satck trace:**
`
at JIT_Regression._CLR_x86_JIT_v2_1_DDB_B168384_LdfldaHack_LdfldaHack_._CLR_x86_JIT_v2_1_DDB_B168384_LdfldaHack_LdfldaHack_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x64.Checked\TestWrappers\JIT.Regression\JIT.Regression.XUnitWrapper.cs:line 33799
`

**Details:**
https://dev.azure.com/dnceng/public/_build/results?buildId=545735&view=ms.vss-test-web.build-test-results-tab&runId=17264072&resultId=101777&paneView=debug

**Comment by AriNuer** [comment] 2020-03-09 07:06
Test `Interop\\COM\\Dynamic\\Dynamic\\Dynamic.cmd` failed with similar exception.
**Job:**
[runtime-coreclr gcstress-extra:20200307.1](https://dev.azure.com/dnceng/public/_build/results?buildId=550942&view=results)

**Error message:**
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
at DynamicClass.IDispatchInvoke(IntPtr, Int32, System.Runtime.InteropServices.ComTypes.INVOKEKIND, System.Runtime.InteropServices.ComTypes.DISPPARAMS ByRef, System.Runtime.InteropServices.Variant ByRef, Microsoft.CSharp.RuntimeBinder.ComInterop.ExcepInfo ByRef, UInt32 ByRef)
at Microsoft.CSharp.RuntimeBinder.ComInterop.UnsafeMethods.IDispatchInvoke(IntPtr, Int32, System.Runtime.InteropServices.ComTypes.INVOKEKIND, System.Runtime.InteropServices.ComTypes.DISPPARAMS ByRef, System.Runtime.InteropServices.Variant ByRef, Microsoft.CSharp.RuntimeBinder.ComInterop.ExcepInfo ByRef, UInt32 ByRef)
at DynamicClass.CallSite.Target(System.Runtime.CompilerServices.Closure, System.Runtime.CompilerServices.CallSite, Microsoft.CSharp.RuntimeBinder.ComInterop.ComObject, Int32[])
at System.Dynamic.UpdateDelegates.UpdateAndExecute2[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Runtime.CompilerServices.CallSite, System.__Canon, System.__Canon)
at System.Dynamic.UpdateDelegates.UpdateAndExecute2[[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Runtime.CompilerServices.CallSite, System.__Canon, System.__Canon)
at Dynamic.CollectionTest.Array()
at Dynamic.CollectionTest.Run()
at Dynamic.Program.Main(System.String[])

Return code: 1
Raw output file: C:\h\w\AB3E094F\w\AFA209CC\e\Interop\COM\Reports\Interop.COM\Dynamic\Dynamic\Dynamic.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\AB3E094F\p\corerun.exe" Dynamic.dll
Running BasicTest
Running CollectionTest
Expected: 100
Actual: -1073741819
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\AB3E094F\p
> C:\h\w\AB3E094F\w\AFA209CC\e\Interop\COM\Dynamic\Dynamic\Dynamic.cmd
Expected: True
Actual: False
```
**Stack trace:**
`

`

**Comment by mangod9** [comment] 2020-03-10 23:22
This is a dupe of https://github.com/dotnet/runtime/issues/615. @AriNuer the other issue you have listed above doesn't appear to be related to this. Thanks!

**Comment by mangod9** [comment] 2020-07-24 04:30
Closing as this is dupe of the JIT bug.

**Closed by mangod9** 2020-07-24 04:30 UTC
Labels: arch-x64, area-crossgen2-coreclr
