### ISSUE TITLE
Mono Wasm - System.Tests.ArrayTests.Copy_SZArray

### ISSUE THREAD

**Issue by Jozkee** [dotnet/runtime#105093] opened 2024-07-18 15:39 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=743515
Build error leg or test failing: System.Tests.ArrayTests.Copy_SZArray
Pull request: https://github.com/dotnet/runtime/pull/104988

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "[FAIL] System.Tests.ArrayTests.Copy_SZArray(sourceArray: [1, 2, 3], sourceIndex: 0, destinationArray: ['\0', '\0', '\0'], destinationIndex: 0, length: 3, expected: [0x0001, 0x0002, 0x0003])",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

## Additional Info

Failed on net9.0-browser-Release-wasm-Mono_Release-WasmTestOnChrome-(Windows.Amd64.Server2022.Open)windows.amd64.server2022.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-ltsc2022-helix-webassembly-20240702174122-7aba2af

xharness error log:
```
Running in: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/126.0.6478.0 Safari/537.36
Running at: http://127.0.0.1:49175/index.html?arg=--run&arg=WasmTestRunner.dll&arg=System.Runtime.Tests.dll&arg=-notrait&arg=category%3dAdditionalTimezoneChecks&arg=-notrait&arg=category%3dIgnoreForCI&arg=-notrait&arg=category%3dOuterLoop&arg=-notrait&arg=category%3dfailing&arg=-verbosity&arg=Info
could not load /runArgs.json: 404. Ignoring
Incoming arguments: --run WasmTestRunner.dll System.Runtime.Tests.dll -notrait category=AdditionalTimezoneChecks -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -verbosity Info
Application arguments: --run WasmTestRunner.dll System.Runtime.Tests.dll -notrait category=AdditionalTimezoneChecks -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -verbosity Info
Initializing dotnet version 9.0.0-ci commit hash 76cdee0e0dec702bbe0e40e37a0c75838a1311b2
Using threadless Xunit runner
Discovering: System.Runtime.Tests.dll (method display = ClassAndMethod, method display options = None)
Discovered:  System.Runtime.Tests.dll (found 9270 of 9411 test cases)
Starting:    System.Runtime.Tests.dll
[FAIL] System.Tests.ArrayTests.Copy_SZArray(sourceArray: [1, 2, 3], sourceIndex: 0, destinationArray: ['\0', '\0', '\0'], destinationIndex: 0, length: 3, expected: [0x0001, 0x0002, 0x0003])
Assert.Equal() Failure: Exception thrown during comparison
           ↓ (pos 0)
Expected: [null, 0x0002, 0x0003]
Actual:   [0x0001, 0x0002, 0x0003]
           ↑ (pos 0)
---- System.NullReferenceException : Object reference not set to an instance of an object.
   at System.Object.InvokeStub_ArrayTests.Copy_SZArray(Object , Span`1 )
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object , BindingFlags , Binder , Object[] , CultureInfo )
----- Inner Stack Trace -----

Finished:    System.Runtime.Tests.dll
Finished writing 17484970 bytes of RESULTXML
Xml file was written to the provided writer.

=== TEST EXECUTION SUMMARY ===
Tests run: 64398 Passed: 64296 Inconclusive: 0 Failed: 1 Ignored: 0 Skipped: 101
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by jeffschwMSFT** [comment] 2024-07-24 19:58
removing blocking-clean-ci as it has not failed in 30 days

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by lewing** [comment] 2024-07-29 17:59
closing, the build is gone and there were never any matches.

**Closed by lewing** 2024-07-29 17:59 UTC
Labels: arch-wasm, area-System.Runtime, runtime-mono, Known Build Error

**Comment by lewing** [comment] 2024-07-29 18:01
I'm pretty sure it is a duplicate of a different issue and BA analysis was behind due to unfra issues
