### ISSUE TITLE
.Net6 Core inconsistent/breaking change for StartsWith

### ISSUE THREAD

**Issue by coderdude87** [dotnet/runtime#68829] opened 2022-05-03 17:36 UTC
### Description

as of .Net Core 3.1 this was true:
```
string test = "This is test string\x03";
test[0] == '\x02'   -> false
test.StartsWith("\x02");  -> false
```

as of .Net 6 this is no longer true
```
string test = "This is test string\x03";
test[0] == '\x02'   -> false
test.StartsWith("\x02");  -> **TRUE**
```

### Reproduction Steps

Starting with console project set to .Net 3.1 Core
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
```

```
using System;

public class Program
{
  public static void Main ( string[] args )
  {
    string test = "Command\x03";

    if ( test[ 0 ] == '\x02' )
      throw new Exception ( "Array Index 0 == \x02" );

    if ( test.StartsWith ( "\x02" ) )
      throw new Exception ( "test Starts with \x02" );
  }
}
```
No error will be thrown.

Now,  switch project to .Net 6
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
```

and this error will get thrown

Exception ("test Starts with \x02")

### Expected behavior

Would expect StartsWith to work consistant with all releases of .Net whether core or not.

### Actual behavior

StartsWith now seems to return true even if condition is false.

### Regression?

This was tested in previous versions and worked as expected.

**Comment by tarekgh** [comment] 2022-05-03 18:08
Please have a look at ethe docs for more information about that: 
- https://docs.microsoft.com/en-us/dotnet/core/compatibility/globalization/5.0/icu-globalization-api
- https://docs.microsoft.com/en-us/dotnet/core/extensions/globalization-icu

The second doc also point how you can get the [old behavior](https://docs.microsoft.com/en-us/dotnet/core/extensions/globalization-icu#use-nls-instead-of-icu) if you need it.

I am closing the issue but feel free to send any follow up question.

**Closed by tarekgh** 2022-05-03 18:08 UTC
Labels: area-System.Globalization, untriaged

**Comment by tarekgh** [comment] 2022-05-03 22:42
> HOWEVER: If I ask if "\x02" is at the start of the string, and it IS NOT, then in no global setting should that return that it is.
> This is still a bug.

It is not a bug and working as expected. You are performing a linguistic string search and not Ordinal search. If you want to get the behavior you desire, you'll need to the ordinal search, something like:

```C#
test.StartsWith("\x02", StringComparison.Ordinal);
```

If you are not passing `, StringComparison.Ordinal` that means the operation will be performed linguistically. When using the `\x02` character, this character is ignored character per [Unicode Standard](https://www.unicode.org/charts/collation/chart_Ignored.html). This means when using `\x02` it is same as if the character does not exist at all in the string. That is why you'll get true.
