### ISSUE TITLE
Version 4.7.1 nuspec does not match the actual System.Memory reference

### ISSUE THREAD

**Issue by avivanoff** [dotnet/runtime#44304] opened 2020-11-05 15:33 UTC
The version 4.7.1 of the package specifies the dependency on System.Memory 4.5.4 (assembly version 4.0.1.1):

`<dependency id="System.Memory" version="4.5.4" />`

But the binary was built against version 4.0.1.0, which is version 4.5.1 of the System.Memory package:

```
// Metadata version: v4.0.30319
.assembly extern mscorlib
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )                         // .z\V.4..
  .ver 4:0:0:0
}
.assembly extern System.Memory
{
  .publickeytoken = (CC 7B 13 FF CD 2D DD 51 )                         // .{...-.Q
  .ver 4:0:1:0
}
.assembly extern System
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )                         // .z\V.4..
  .ver 4:0:0:0
}

```

**Comment by safern** [comment] 2021-02-01 18:24
cc: @ericstj

I believe this is a dupe of: https://github.com/dotnet/runtime/issues/45921

**Closed by safern** 2021-02-01 18:24 UTC
Labels: area-Infrastructure-libraries, untriaged
