### ISSUE TITLE
Exception stack trace does not have line numbers for Self-Contained(Single Executable) apps with embedded PDBs

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/runtime#39987] opened 2020-07-28 03:23 UTC
### Description
The publish app as Self-Contained(Single Executable), its exception stack trace does not have line numbers, even if there is a `pdb` file at the same folder to the `exe`.

### Configuration

```
.NET Core SDK（反映任何 global.json）:
 Version:   3.1.302
 Commit:    41faccf259

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.302\

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Regression?

.net core 3.1.

### Other information

![image](https://user-images.githubusercontent.com/4510984/88615428-7eef4980-d0c4-11ea-965a-d86603b20ee5.png)

![image](https://user-images.githubusercontent.com/4510984/88620828-82d59880-d0d1-11ea-80e0-591a9176fb81.png)

**Comment by agocke** [comment] 2020-08-10 17:52
I believe placing the PDBs next to the single-file is not sufficient in .NET Core 3.x. I think you need to actually embed the PDBs in the single-file application, either by using the compiler to embed the PDBs with the `<DebugType>embedded</DebugType>` option in MSBuild, or setting `<IncludeSymbolsInSingleFile>true</IncludeSymbolsInSingleFile>` during publish.

**Comment by josalem** [comment] 2020-08-10 21:04
CC @mikem8361 @tommcdon @hoyosjs

**Comment by mikem8361** [comment] 2020-08-12 22:09
I can't seem to repro your issue with my simple test case that throws an unhandled exception.  I made it a self-contained app and the pdb is next to the exe and I get source/line info.  Using the exact same SDK version. There may be something unique about your environment or app.  Have you tried the above suggestions (embeded PDB, etc.)?

```
SymbolTestApp starting c:\sd\builds\SymbolTestDll2\bin\Debug\netstandard2.0\win-x64
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Exception: Exception of type 'System.Exception' was thrown.
   at SymbolTestDll.TestClass.Foo7() in c:\sd\builds\SymbolTestDll2\TestClass.cs:line 30
   at SymbolTestDll.TestClass.Foo6(Int32 x) in c:\sd\builds\SymbolTestDll2\TestClass.cs:line 22
   at SymbolTestDll.TestClass.Foo5(Int32 x) in c:\sd\builds\SymbolTestDll2\TestClass.cs:line 17
   at SymbolTestDll.TestClass.ThrowException() in c:\sd\builds\SymbolTestDll2\TestClass.cs:line 12
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at SymbolTestApp.Program.Foo4(String dllPath) in c:\sd\builds\SymbolTestApp2\Program.cs:line 56
   at SymbolTestApp.Program.Foo2(Int32 x, String dllPath) in c:\sd\builds\SymbolTestApp2\Program.cs:line 30
   at SymbolTestApp.Program.Foo1(Int32 x, String dllPath) in c:\sd\builds\SymbolTestApp2\Program.cs:line 25
   at SymbolTestApp.Program.Main(String[] args) in c:\sd\builds\SymbolTestApp2\Program.cs:line 20
```

**Comment by GF-Huang** [comment] 2020-08-12 23:44
@mikem8361 I will try it later and report it, thanks for reminding.

**Comment by GF-Huang** [comment] 2020-09-01 03:04
> I believe placing the PDBs next to the single-file is not sufficient in .NET Core 3.x. I think you need to actually embed the PDBs in the single-file application, either by using the compiler to embed the PDBs with the `<DebugType>embedded</DebugType>` option in MSBuild, or setting `<IncludeSymbolsInSingleFile>true</IncludeSymbolsInSingleFile>` during publish.

Is seems not work, still not line numbers.

![image](https://user-images.githubusercontent.com/4510984/91790275-f0319780-ec42-11ea-8e43-9e0217f63996.png)

**Comment by GF-Huang** [comment] 2020-09-01 03:19
`<DebugType>embedded</DebugType>`  works well, but why `<IncludeSymbolsInSingleFile>true</IncludeSymbolsInSingleFile>` not work?

**Comment by agocke** [comment] 2020-09-01 20:46
We recently removed IncludeSymbolsInSingleFile from 5.0 in preference of `<DebugType>embedded`.

**Comment by mikem8361** [comment] 2021-01-25 18:59
It sounds like this issue is resolved by adding <DebugType>embedded</DebugType> to the project file.  @agocke are we planning to support portable/full PDBs for single-contained apps?  Otherwise, we should close this issue.

**Comment by trebor678** [comment] 2021-09-13 16:40
This still isn't working with .NET 5.0 when you produce a single file, even with `<DebugType>embedded</DebugType>` specified

**Comment by agocke** [comment] 2021-09-13 21:30
@mikem8361 I tried this with DebugType=embedded and it looks like the line numbers are still missing in net5. I will try net6 to see if this is fixed.

**Comment by agocke** [comment] 2021-09-27 18:25
Doesn't look like it's fixed in net6.0 either -- this looks like a bug in the debugger.

**Comment by splitice** [comment] 2021-12-17 05:25
Can also confirm that embedded debug symbols doesnt work with .net core 5 on linux

**Comment by pspgit** [comment] 2022-01-03 16:25
I'm also reproducing it on ASP .NET 5.0 on Windows:
- Deployment Mode: Self-contained
- File Publish Options: **Produce single file**
- DebugType: reproduces for all options: embedded, full, portable
- No line numbers

When unchecking "Produce single file" - line numbers come back.

**Comment by splitice** [comment] 2022-04-25 22:32
Sorry I can't as none are open source. But I can say that I'm yet to see any project that does have exception lime numbers. I've been involved in 3 projects all containerised and on Linux.

**Comment by mikem8361** [comment] 2022-04-29 21:43
@GF-Huang, does this repro with the 6.0 SDK for you? If not I would like to close this issue.

**Comment by GF-Huang** [comment] 2022-04-30 05:28
Sorry, I haven't been paying attention to this issue lately, it's better to ask other people with similar questions to make sure .NET 6 has addressed their similar needs.

**Comment by mikem8361** [comment] 2022-04-30 19:34
I'm assuming this is fixed in 6.0

**Closed by mikem8361** 2022-04-30 19:34 UTC
Labels: area-Diagnostics-coreclr, area-Single-File, needs-further-triage
