### ISSUE TITLE
Path.Combine incorrect exception

### ISSUE THREAD

**Issue by Forgind** [dotnet/runtime#49487] opened 2021-03-10 18:12 UTC
https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.IO/Path.xml
https://docs.microsoft.com/en-us/dotnet/api/system.io.path.combine?view=net-5.0&source=docs
I made a simple console app with:
```C#
string path = @"abc\def\g" + Path.GetInvalidPathChars()[1] + @"hi\jk";
Console.WriteLine(Path.Combine(path, "hi"));
```

and it ran without throwing an exception, which is not what the docs said would happen.

**Comment by antonfirsov** [comment] 2021-03-11 15:54
This seems to fail on .NET Framework, so it might be an actually product bug.

Transferring to the runtime repo for now.

**Comment by Forgind** [comment] 2021-03-11 16:19
I should have mentioned that I built and ran it with VS version 16.10 preview 1.

**Comment by carlossanlop** [comment] 2021-03-11 18:52
We used to throw in .NET Framework because we were doing a check for invalid chars on purpose in most `Path` APIs.

In .NET Core+ we only throw when we detect invalid path chars if we are about to send the path to the OS. Examples:

- Windows: [`Path.GetFullPath`](https://github.com/dotnet/runtime/blob/79ae74f5ca5c8a6fe3a48935e85bd7374959c570/src/libraries/System.Private.CoreLib/src/System/IO/Path.Windows.cs#L77)
- Unix: [`Path.GetFullPath`](https://github.com/dotnet/runtime/blob/79ae74f5ca5c8a6fe3a48935e85bd7374959c570/src/libraries/System.Private.CoreLib/src/System/IO/Path.Unix.cs#L26)

All other `Path` APIs that don't communicate the OS do not throw when an invalid path char is included in the path strings. See [this issue](https://github.com/dotnet/runtime/issues/24223) and [this PR](https://github.com/dotnet/coreclr/pull/15191) for more info.

We have an open issue [in docs](https://github.com/dotnet/docs/issues/20004) to amend the 2.1 breaking changes list, but we should also amend the documentation of APIs that used to throw and indicate that the exception is only thrown in .NET Framework and versions older than .NET Core 2.1.

**Comment by carlossanlop** [comment] 2021-03-11 18:53
Duplicate of https://github.com/dotnet/runtime/issues/44960

**Closed by carlossanlop** 2021-03-11 18:53 UTC
Labels: area-System.IO, needs further triage, tenet-compatibility
