### ISSUE TITLE
Setting COMPlus_EnableHWIntrinsic=0 causes System.PlatformNotSupportedException with optimized libraries code

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/runtime#60035] opened 2021-10-05 23:01 UTC
While working on #38162 I observed behavior (that I believe is incorrect) when running with .NET 6 SDK RC1.

To reproduce the issue build and run the project using the following sequence of commands:

```
dotnet build -c Release

set COMPlus_EnableHWIntrinsic=0

dotnet run -c Release
```

**Runtime_60035.csproj**
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

</Project>
```

**Runtime_60035.cs**
```cs
using System;
using System.Text;
using System.Text.Encodings.Web;

namespace Runtime_60035
{
    class Program
    {
        static void Main(string[] args)
        {
            byte[] inputBytes = Encoding.UTF8.GetBytes("https://github.com/dotnet/runtime");
            Console.WriteLine(UrlEncoder.Default.FindFirstCharacterToEncodeUtf8(inputBytes));
        }
    }
}
```

The result will be a failure with the following stack trace

```
Unhandled exception. System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Runtime.Intrinsics.X86.Sse2.LoadVector128(Byte* address)
   at System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstByteToEncodeSsse3(Byte* pData, UIntPtr lengthInBytes)
   at System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstByteToEncode(ReadOnlySpan`1 data)
   at System.Text.Encodings.Web.DefaultUrlEncoder.FindFirstCharacterToEncodeUtf8(ReadOnlySpan`1 utf8Text)
   at Runtime_60035.Program.Main(String[] args) in D:\echesako\GitHub\Runtime_60035\Program.cs:line 12
```

If in addition to setting `COMPlus_EnableHWIntrinsic=0` I set `COMPlus_ReadyToRun=0` the issue goes away.

**Comment by echesakovMSFT** [comment] 2021-10-05 23:14
@tannergooding  I wonder why we take `OptimizedInboxTextEncoder.GetIndexOfFirstByteToEncodeSsse3` [here](https://github.com/dotnet/runtime/blob/67354a2fb4308650eb1d7db3277c862b8464c895/src/libraries/System.Text.Encodings.Web/src/System/Text/Encodings/Web/OptimizedInboxTextEncoder.cs#L372) with `COMPlus_EnableHWIntrinsic=0`. 

@davidwrighton Do we have special handling for `Ssse3.IsSupported` and friends in crossgen2 (as we used to have in crossgen) to treat them as regular calls and not as intrinsics? Or this is done via a different mechanism in crossgen2?

**Comment by danmoseley** [comment] 2021-10-05 23:40
I know we discussed this in the past but I don’t know where we ended up. Do we test anything but AVX paths in the libraries (on x64)? And where we have added intrinsic paths for Arm64, do we test the software fallback paths? Just wondering how large the test gap might be.

**Comment by tannergooding** [comment] 2021-10-06 03:55
I think we should be able to yes, especially as an outerloop. We just need to define the jobs and ensure the right environment variables are set.

I can sink with Santi or someone else tomorrow and figure this out.

**Comment by danmoseley** [comment] 2021-10-06 19:05
I fear we have hijacked this issue 😄 moving to https://github.com/dotnet/runtime/issues/950

**Comment by jkotas** [comment] 2021-10-07 04:40
The problem seems to be that the env variables like `EnableHWIntrinsic` are only respected by the JIT and not by the VM. It means that the crossgened code and JITed code have different assumptions about the supported hardware intrinsics, and mixing of crossgened and JITed code can lead to crashes like above.

We need to move reading of these env variables to the VM.

**Comment by brantburnett** [comment] 2021-11-09 20:03
I'm not certain if this is the same issue, but I encountered something similar with `COMPlus_EnableSSSE3=0` and the `dotnet test` command after upgrading to .NET SDK 6.

In simple terms, I'm using a matrix in GitHub actions to run my unit test suite against various hardware situations in order to ensure that my fallback logic when the intrinsic is not supported is accurate. It appears that MSBuildnce `dotnet test` attempts to run build, but the build is failing due to the intrinsics being disabled internally for MSBuild's use.

```
error MSB4018: The "GenerateDepsFile" task failed unexpectedly. [/home/runner/work/Snappier/Snappier/Snappier/Snappier.csproj]
/home/runner/.dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018: System.PlatformNotSupportedException: Operation is not supported on this platform. [/home/runner/work/Snappier/Snappier/Snappier/Snappier.csproj][/home/runner/work/Snappier/Snappier/Snappier/Snappier.csproj]
/home/runner/.dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at System.Runtime.Intrinsics.X86.Ssse3.Shuffle(Vector128`1 value, Vector128`1 mask)
/home/runner/.dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstCharToEncodeSsse3(Char* pData, UIntPtr lengthInChars) [/home/runner/work/Snappier/Snappier/Snappier/Snappier.csproj]
/home/runner/.dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstCharToEncode(ReadOnlySpan`1 data) [/home/runner/work/Snappier/Snappier/Snappier/Snappier.csproj]
/home/runner/.dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at System.Text.Encodings.Web.DefaultJavaScriptEncoder.FindFirstCharacterToEncode(Char* text, Int32 textLength) [/home/runner/work/Snappier/Snappier/Snappier/Snappier.csproj]
/home/runner/.dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at System.Text.Json.JsonWriterHelper.NeedsEscaping(ReadOnlySpan`1 value, JavaScriptEncoder encoder) [/home/runner/work/Snappier/Snappier/Snappier/Snappier.csproj]
/home/runner/.dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at System.Text.Json.Utf8JsonWriter.WriteStartEscape(ReadOnlySpan`1 propertyName, Byte token) [/home/runner/work/Snappier/Snappier/Snappier/Snappier.csproj]
/home/runner/.dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at System.Text.Json.Utf8JsonWriter.WriteStartObject(ReadOnlySpan`1 propertyName) [/home/runner/work/Snappier/Snappier/Snappier/Snappier.csproj]
/home/runner/.dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at System.Text.Json.Utf8JsonWriter.WriteStartObject(String propertyName) [/home/runner/work/Snappier/Snappier/Snappier/Snappier.csproj]
/home/runner/.dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at Microsoft.Extensions.DependencyModel.DependencyContextWriter.WriteRuntimeTargetInfo(DependencyContext context, Utf8JsonWriter jsonWriter) [/home/runner/work/Snappier/Snappier/Snappier/Snappier.csproj]
/home/runner/.dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at Microsoft.Extensions.DependencyModel.DependencyContextWriter.Write(DependencyContext context, Stream stream) [/home/runner/work/Snappier/Snappier/Snappier/Snappier.csproj]
/home/runner/.dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateDepsFile.WriteDepsFile(String depsFilePath) [/home/runner/work/Snappier/Snappier/Snappier/Snappier.csproj]
/home/runner/.dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateDepsFile.ExecuteCore() [/home/runner/work/Snappier/Snappier/Snappier/Snappier.csproj]
/home/runner/.dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [/home/runner/work/Snappier/Snappier/Snappier/Snappier.csproj]
/home/runner/.dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/home/runner/work/Snappier/Snappier/Snappier/Snappier.csproj]
/home/runner/.dotnet/sdk/6.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/home/runner/work/Snappier/Snappier/Snappier/Snappier.csproj]
```

This works fine with the .NET 5 SDK, so it seems like a regression to me. However, there is a pretty easy workaround for this specific scenario. For me, the workaround is to run `dotnet build` first without the environment variable, then run `dotnet test --no-build` to test with the environment variable.

```yaml
- name: Install dependencies
  run: dotnet restore
- name: Build dependencies
  run: dotnet build --configuration Release --verbosity normal
- name: Test
  run: |
    export COMPlus_Enable${{ matrix.disable }}=0 && \
    dotnet test --no-build -f ${{ matrix.framework }} --configuration Release --verbosity normal --logger "trx;LogFileName=results.trx"
```

**Comment by echesakovMSFT** [comment] 2021-11-09 23:59
@brantburnett I believe this is a occurrence of the same issue. 

cc @davidwrighton

**Closed** 2022-01-12 00:24 UTC
Labels: area-System.Runtime.Intrinsics, in pr
