### ISSUE TITLE
Memory leak in ContextMenuStrip with ToolStripMenuItem submenus

### ISSUE THREAD

**Issue by romanzimin22** [dotnet/runtime#93520] opened 2023-10-06 15:01 UTC
### .NET version

8.0 Preview 8.0.100-rc.1.23455.8

### Did it work in .NET Framework?

Yes

### Did it work in any of the earlier releases of .NET Core or .NET 5+?

Worked in net6 and seems to work if built for net7

### Issue description

Creating context menu with submenus causes memory usage growing at a rate 1GB per sec without any client actions

### Steps to reproduce

[WinFormsApp1.zip](https://github.com/dotnet/winforms/files/12832438/WinFormsApp1.zip)

1. Start attached app
2. Click the button - it will show Form2
3. Watch the memory. If it doesn't start growing, close the second form and repeat step 2
4. May take 3-5 retries until memory starts growing by itself without any actions

In a complex UI it takes 1 click to repro, so the issue isn't in disposing.
And the menu is much smaller. Could be 12 items with the same result of uncontrolled memory leaking

**Comment by jkotas** [comment] 2023-10-14 15:56
@jakobbotsch Is this duplicate of https://github.com/dotnet/runtime/issues/93342 ?

**Comment by jakobbotsch** [comment] 2023-10-14 20:13
Yes, this is the same problem. We hit the issue while compiling `System.Windows.Forms.ToolStripControlHost.OnSubscribeControlEvents(System.Windows.Forms.Control)` with PGO data.

Thanks for reporting this @romanzimin22, and thanks everyone who helped investigate. I've confirmed this issue is fixed for the provided repro case. The fix will be part of the GA release of .NET 8.

**Closed by jakobbotsch** 2023-10-14 20:13 UTC
Labels: area-CodeGen-coreclr, untriaged, needs-area-label

**Comment by elachlan** [comment] 2023-10-15 03:10
Has this fix been included in .NET 9 as well?

**Comment by jakobbotsch** [comment] 2023-10-15 13:17
> Has this fix been included in .NET 9 as well?

The fix is in main, but it looks like the current .NET 9 build on dotnet/installer is very outdated (from Sep 20), so the fix hasn't propagated there yet.
