### ISSUE TITLE
UserPrincipal.Current throws InvalidCastException

### ISSUE THREAD

**Issue by orinem** [dotnet/runtime#38411] opened 2020-06-25 20:24 UTC
### Description

See also #30408

If logged on as an Azure AD user, UserPrincipal.Current throws an InvalidCastException.

Steps to reproduce:

Connect a non-domain connected Windows 10 computer to an Azure Active Directory:

Settings App
Select Accounts
Select "Access work or school"
Click "Connect" and follow the steps.

When it completes, restart and log in as the Azure AD user.  Run the code below.

### Code

```
using System;
using System.DirectoryServices.AccountManagement;

namespace TestDotNetCore
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                var principal = UserPrincipal.Current;
                Console.WriteLine(principal.Name);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }
        }
    }
}
```

It prints:

```
Unable to cast object of type 'System.DirectoryServices.AccountManagement.GroupPrincipal' to type 'System.DirectoryServices.AccountManagement.UserPrincipal'.
```

### Configuration

Tried with the following:  x86, .net Framework 4.5.2, 4.7.2, Core 3.1.

**Comment by orinem** [comment] 2020-06-25 21:03
Use area-System.DirectoryServices then delete this comment.

**Comment by orinem** [comment] 2020-06-26 06:12
The first problem is that the Azure AD user SID has an S-1-12-1 prefix which ClassifySID classifies as FakeObject.  It's expecting an S-1-5-21 prefix.

If ClassifySID is changed to allow S-1-12-1, then EqualDomainSid() in IsSamUser() fails.  This asserts in the DEBUG build and that's as far as I got.

**Comment by ericstj** [comment] 2020-07-09 16:55
duplicate of #30408

**Closed by ericstj** 2020-07-09 16:55 UTC
Labels: area-System.DirectoryServices, untriaged
