### ISSUE TITLE
[MONO][Interp] JIT/Methodical/eh/basics/throwinfilter_* failed on Android x64 with interpreter

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#54389] opened 2021-06-18 01:56 UTC
Failed tests list:

- JIT/Methodical/eh/basics/throwinfilter_d/throwinfilter_d.sh
- JIT/Methodical/eh/basics/throwinfilter_r/throwinfilter_r.sh

[Full log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54084-merge-7fe5a3a9adcf43bb89/JIT.Methodical.eh/console.1da4e5ee.log?sv=2019-07-07&se=2021-07-07T16%3A35%3A55Z&sr=c&sp=rl&sig=9XwT59x%2Bj3Sscfb8zn3gZ4RalUABqgsDFGMafqXPHQ4%3D)

```
06-17 16:44:07.174  7253  7271 I DOTNET  : MonoRunner initialize,, entryPointLibName=throwinfilter_d.dll
      06-17 16:44:07.174  7253  7271 D DOTNET  : file_path: /data/user/0/net.dot.JIT_Methodical/files/runtimeconfig.bin
      06-17 16:44:07.176  7253  7271 D DOTNET  : Interp Enabled
      06-17 16:44:07.178  7253  7271 D DOTNET  : assembly_preload_hook: System.Private.CoreLib (null) /data/user/0/net.dot.JIT_Methodical/files
      06-17 16:44:07.203  7253  7271 D DOTNET  : assembly_preload_hook: throwinfilter_d.dll (null) /data/user/0/net.dot.JIT_Methodical/files
      06-17 16:44:07.203  7253  7271 D DOTNET  : Executable: throwinfilter_d.dll
      06-17 16:44:07.203  7253  7271 D DOTNET  : assembly_preload_hook: mscorlib  /data/user/0/net.dot.JIT_Methodical/files
      06-17 16:44:07.205  7253  7271 D DOTNET  : assembly_preload_hook: common  /data/user/0/net.dot.JIT_Methodical/files
      06-17 16:44:07.206  7253  7271 D DOTNET  : assembly_preload_hook: System.Runtime  /data/user/0/net.dot.JIT_Methodical/files
      06-17 16:44:07.206  7253  7271 D DOTNET  : assembly_preload_hook: System.Console  /data/user/0/net.dot.JIT_Methodical/files
      06-17 16:44:07.218  7253  7271 D DOTNET  : assembly_preload_hook: System.Threading  /data/user/0/net.dot.JIT_Methodical/files
      06-17 16:44:07.224  7253  7271 D DOTNET  : assembly_preload_hook: System.Runtime.InteropServices  /data/user/0/net.dot.JIT_Methodical/files
      06-17 16:44:07.228  7253  7271 I DOTNET  : In try, throwing the first obj
      06-17 16:44:07.228  7253  7271 I DOTNET  : 
      06-17 16:44:07.258  7253  7271 I DOTNET  : In filter
      06-17 16:44:07.258  7253  7271 I DOTNET  : 
      06-17 16:44:07.258  7253  7271 I DOTNET  : In handler, should be unreached
      06-17 16:44:07.258  7253  7271 I DOTNET  : 
      06-17 16:44:07.258  7253  7271 I DOTNET  : Done
      06-17 16:44:07.258  7253  7271 I DOTNET  : 
      06-17 16:44:07.263  7253  7271 I DOTNET  : 
      06-17 16:44:07.264  7253  7271 I DOTNET  : FAILED!
      06-17 16:44:07.264  7253  7271 I DOTNET  : 
      06-17 16:44:07.264  7253  7271 I DOTNET  : [EXPECTED OUTPUT]
      06-17 16:44:07.264  7253  7271 I DOTNET  : In try, throwing the first obj
      06-17 16:44:07.264  7253  7271 I DOTNET  : In filter
      06-17 16:44:07.264  7253  7271 I DOTNET  : In catch
      06-17 16:44:07.264  7253  7271 I DOTNET  : Done
      06-17 16:44:07.264  7253  7271 I DOTNET  : 
      06-17 16:44:07.264  7253  7271 I DOTNET  : [DIFF RESULT]
      06-17 16:44:07.264  7253  7271 I DOTNET  : < In catch
      06-17 16:44:07.264  7253  7271 I DOTNET  : ---
      06-17 16:44:07.264  7253  7271 I DOTNET  : > In handler, should be unreached
      06-17 16:44:07.264  7253  7271 I DOTNET  : 
      06-17 16:44:07.264  7253  7271 D DOTNET  : Exit code: 1.
      06-17 16:44:07.269  7253  7271 I DOTNET  : MonoRunner finished, return-code=1
      06-17 16:44:07.269  1787  2621 I ActivityManager: Force stopping net.dot.JIT_Methodical appid=10141 user=0: finished inst
      06-17 16:44:07.269  1787  2621 I ActivityManager: Killing 7253:net.dot.JIT_Methodical/u0a141 (adj 0): stop net.dot.JIT_Methodical
      06-17 16:44:07.270  1787  6702 W Binder  : Outgoing transactions from this process must be FLAG_ONEWAY
      06-17 16:44:07.270  1787  6702 W Binder  : java.lang.Throwable
      06-17 16:44:07.270  1787  6702 W Binder  : 	at android.os.BinderProxy.transact(BinderProxy.java:480)
      06-17 16:44:07.270  1787  6702 W Binder  : 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:205)
      06-17 16:44:07.270  1787  6702 W Binder  : 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
      06-17 16:44:07.271  7243  7243 D AndroidRuntime: Shutting down VM
      06-17 16:44:07.288  7243  7274 E app_process: Thread attaching to non-existent runtime: Binder:7243_3
      06-17 16:44:07.288  7243  7274 I AndroidRuntime: NOTE: attach of thread 'Binder:7243_3' failed
      06-17 16:44:07.301  1533  1533 I Zygote  : Process 7253 exited due to signal 9 (Killed)
      06-17 16:44:07.309  1787  1814 I libprocessgroup: Successfully killed process cgroup uid 10141 pid 7253 in 39ms
```

**Comment by lambdageek** [comment] 2021-06-22 16:23
This one is worth investigating deeper - we're relying on exception filters to work correctly in the interpreter for some scenarios (e.g. browser-wasm with hybrid AOT/interp), so it's important to get right.

**Comment by BrzVlad** [comment] 2021-06-23 07:43
Throws from filters are incorrect on mono, both on jit and interp. This might be a duplicate of https://github.com/dotnet/runtime/issues/47624.

**Comment by BrzVlad** [comment] 2021-07-01 07:56
Closing as duplicate. The issue is that we don't catch all exception thrown from filters so they bubble up.

**Closed by BrzVlad** 2021-07-01 07:56 UTC
Labels: area-Codegen-Interpreter-mono
