### ISSUE TITLE
Inconsistent debug views of dictionaries

### ISSUE THREAD

**Issue by arturek** [dotnet/runtime#91506] opened 2023-09-02 15:15 UTC
Currently standard dictionary classes have two different ways of showing their content in a debugger. The non-generic dictionary classes (i.e. `Hashtable` and `SortedList`) presents keys and values in separate columns:
![Hashtable debug view](https://github.com/dotnet/runtime/assets/381257/3335ac4f-2efe-49b9-aef8-91d590d8c4bc)

On the other hand, generic dictionaries show their content as a list indexed by numbers with keys and values together:
![Generic dictionary debug view](https://github.com/dotnet/runtime/assets/381257/9d63e807-27d9-4d31-809a-54d97ade6837)

I assume, that this difference is not intended, so presenting all of them more consistently would be an improvement. In my opinion, the first view looks better, closer to the idea of a dictionary. The later view is better for lists (or anything indexed by numbers). But choosing any of them should help.

What do you think about it?

**Comment by stephentoub** [comment] 2023-09-02 15:39
Duplicate of https://github.com/dotnet/runtime/issues/88736

**Comment by Neme12** [comment] 2023-09-02 21:01
I like the first option as well.

**Comment by tarekgh** [comment] 2023-09-03 23:51
Closing this as we are tracking the same issue in https://github.com/dotnet/runtime/issues/88736. @arturek thanks for opening this issue. Feel free to comment more on https://github.com/dotnet/runtime/issues/88736 if you feel there is anything missing there.

**Closed by tarekgh** 2023-09-03 23:51 UTC
Labels: area-System.Collections, untriaged
