### ISSUE TITLE
ActivatorUtilitiesConstructorAttribute Does Not Work in Some Cases

### ISSUE THREAD

**Issue by lawrence-laz** [dotnet/runtime#42339] opened 2020-07-24 08:21 UTC
### Describe the bug
`ActivatorUtilities.CreateInstance<T>(IServiceProvider provider, params object[] parameters)` does not respect `ActivatorUtilitiesConstructorAttribute` in a case when constructor ordering is changed.

### To Reproduce
1. Using version '3.1.6' of package 'Microsoft.Extensions.DependencyInjection'
2. Run this test code:
    ```csharp
    using Microsoft.Extensions.DependencyInjection;
    using System;
    using Xunit;
    
    namespace UnitTests
    {
        public class ActivatorUtilitiesConstructorTests
        {
            public class Dependency1 { }
            public class Dependency2 { }
            public class Dependency3 { }
    
            public class Service1
            {
                public Service1(Dependency1 dependency1, Dependency3 dependency3)
                {
                    throw new Exception("This should not be called.");
                }
    
                [ActivatorUtilitiesConstructor]
                public Service1(Dependency1 dependency1, Dependency2 dependency2, Dependency3 dependency3)
                {
                }
            }
    
            public class Service2
            {
                [ActivatorUtilitiesConstructor]
                public Service2(Dependency1 dependency1, Dependency2 dependency2, Dependency3 dependency3)
                {
                }
    
                public Service2(Dependency1 dependency1, Dependency3 dependency3)
                {
                    throw new Exception("This should not be called.");
                }
            }
    
            [Fact]
            public void CreateInstance_WithActivatorUtilitiesConstructorBeingSecond_ShouldChooseMarkedCtor()
            {
                // Arrange
                var dependency1 = new Dependency1();
                var dependency3 = new Dependency3();
    
                var provider = new ServiceCollection()
                    .AddScoped<Dependency2>()
                    .BuildServiceProvider();
    
                // Act & Assert
                ActivatorUtilities.CreateInstance<Service1>(provider, dependency1, dependency3); // This works.
            }
    
            [Fact]
            public void CreateInstance_WithActivatorUtilitiesConstructorBeingFirst_ShouldChooseMarkedCtor()
            {
                // Arrange
                var dependency1 = new Dependency1();
                var dependency3 = new Dependency3();
    
                var provider = new ServiceCollection()
                    .AddScoped<Dependency2>()
                    .BuildServiceProvider();
    
                // Act & Assert
                ActivatorUtilities.CreateInstance<Service2>(provider, dependency1, dependency3); // This fails.
            }
        }
    }
    ```
4. See error `This should not be called.` when constructor marked with `ActivatorUtilitiesConstructorAttribute` is defined first, but no error when it is defined second.

### Expected behavior
I expect `ActivatorUtilitiesConstructorAttribute` to be respected regardless of the order in which constructors were defined.

### Additional context
The given example is reproduced using 3 dependencies. Removing one dependency makes both tests pass. Maybe this will help to get on a right path.

**Comment by maryamariyan** [comment] 2021-03-29 23:16
Closing as dupe of https://github.com/dotnet/runtime/issues/46132 since there is more discussion there

**Closed by maryamariyan** 2021-03-29 23:16 UTC
Labels: area-Extensions-DependencyInjection, bug

**Comment by steveharter** [comment] 2024-03-04 19:03
Note that this issue was closed, but there are still issues with the attribute not working. For example adding this to the original repro fails:
```cs
        public class Service3
        {
            [ActivatorUtilitiesConstructor]
            public Service3(Dependency1 dependency1, Dependency3 dependency3)
            {
            }

            public Service3(Dependency1 dependency1, Dependency2 dependency2, object? o)
            {
                throw new Exception("This should not be called.");
            }
        }

        [Fact]
        public void Test()
        {
            var dependency1 = new Dependency1();
            var dependency3 = new Dependency3();

            var provider = new ServiceCollection()
                .AddScoped<Dependency2>()
                .BuildServiceProvider();

            // This should call (d1, d3) but instead calls (d1, d2, null).
            ActivatorUtilities.CreateInstance<Service3>(provider, dependency1, dependency3); 

        }
```
