### ISSUE TITLE
[Mono][Wasm] 14 % Regression in System.Tests.Perf_Random

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#45916] opened 2020-12-10 21:04 UTC
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [153604ea20fe3b36ef0f0ee2e071d8341f8d4c63](https://github.com/dotnet/runtime/commit/153604ea20fe3b36ef0f0ee2e071d8341f8d4c63)
Compare | [9528b1d77741492a032315cc7c4e765e4e496ce0](https://github.com/dotnet/runtime/commit/9528b1d77741492a032315cc7c4e765e4e496ce0)

### Regressions in System.Tests.Perf_Random

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[Next_int_int](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=micro/System.Tests.Perf_Random.Next_int_int.html>) | 143.48 ns | 163.89 ns | 1.14 | | |
[Next_int](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=micro/System.Tests.Perf_Random.Next_int.html>) | 122.18 ns | 146.33 ns | 1.20 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/11_30_2020/refs/heads/master_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=micro_Regression/System.Tests.Perf_Random_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/11_30_2020/refs/heads/master_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=micro_Regression/System.Tests.Perf_Random_2.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/11_30_2020/refs/heads/master_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=micro/System.Tests.Perf_Random.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Tests.Perf_Random*'
```
<details>

.
### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-69dcfc1c-770c-4a9d-8fa4-647fd0cd06c17a73d362ab14a2291/1c0401e4-ad6c-4246-94b7-5de30a430731.zip?sv=2019-07-07&se=2020-12-28T17%3A36%3A04Z&sr=c&sp=rl&sig=Qn5278RC%2BDCAzdwgmi2wM%2BqcGB1UGRZg%2Be3SEThx9j0%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-aa81aa47-caaf-4677-b13f-c99e2fd4e215f4acf44f19647438e/a354c1cf-ad46-440a-b400-2b83f26078d8.zip?sv=2019-07-07&se=2020-12-30T07%3A04%3A51Z&sr=c&sp=rl&sig=2R9042oPERIX48aCSF%2FnTl%2FcpgyiO42bf9HnZuJJwx0%3D>)

#### System.Tests.Perf_Random.Next_int_int

```log
[134.900 ; 140.424) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[140.424 ; 145.900) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[145.900 ; 151.025) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[151.025 ; 156.336) | @@@@@@@@@@@@@@@@@@@@@@
[156.336 ; 160.399) | @@@@@@
[160.399 ; 165.789) | @@@@@
[165.789 ; 173.827) | @@
```
#### System.Tests.Perf_Random.Next_int

```log
[118.912 ; 121.452) | @@@@@@
[121.452 ; 124.417) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[124.417 ; 128.584) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[128.584 ; 133.249) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[133.249 ; 137.710) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[137.710 ; 141.264) | @@@@@
[141.264 ; 144.859) | @@
[144.859 ; 149.361) | @@@@
[149.361 ; 154.609) | @
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [153604ea20fe3b36ef0f0ee2e071d8341f8d4c63](https://github.com/dotnet/runtime/commit/153604ea20fe3b36ef0f0ee2e071d8341f8d4c63)
Compare | [9528b1d77741492a032315cc7c4e765e4e496ce0](https://github.com/dotnet/runtime/commit/9528b1d77741492a032315cc7c4e765e4e496ce0)

### Regressions in System.Collections.CreateAddAndClear<Int32>

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[Array](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=micro/System.Collections.CreateAddAndClear(Int32).Array(Size%3a%20512).html>) | 9.06 μs | 9.98 μs | 1.10 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/11_30_2020/refs/heads/master_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=micro_Regression/System.Collections.CreateAddAndClear(Int32)_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/11_30_2020/refs/heads/master_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=micro/System.Collections.CreateAddAndClear(Int32).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Collections.CreateAddAndClear<Int32>*'
```
<details>

.
### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-69dcfc1c-770c-4a9d-8fa4-647fd0cd06c17a73d362ab14a2291/1c0401e4-ad6c-4246-94b7-5de30a430731.zip?sv=2019-07-07&se=2020-12-28T17%3A36%3A04Z&sr=c&sp=rl&sig=Qn5278RC%2BDCAzdwgmi2wM%2BqcGB1UGRZg%2Be3SEThx9j0%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-aa81aa47-caaf-4677-b13f-c99e2fd4e215f4acf44f19647438e/a354c1cf-ad46-440a-b400-2b83f26078d8.zip?sv=2019-07-07&se=2020-12-30T07%3A04%3A51Z&sr=c&sp=rl&sig=2R9042oPERIX48aCSF%2FnTl%2FcpgyiO42bf9HnZuJJwx0%3D>)

#### System.Collections.CreateAddAndClear<Int32>.Array(Size: 512)

```log
[8828.285 ;  9102.469) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[9102.469 ;  9335.940) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[9335.940 ;  9679.214) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[9679.214 ;  9903.650) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[9903.650 ; 10180.892) | @@@@@@@@@@@@@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [153604ea20fe3b36ef0f0ee2e071d8341f8d4c63](https://github.com/dotnet/runtime/commit/153604ea20fe3b36ef0f0ee2e071d8341f8d4c63)
Compare | [9528b1d77741492a032315cc7c4e765e4e496ce0](https://github.com/dotnet/runtime/commit/9528b1d77741492a032315cc7c4e765e4e496ce0)

### Regressions in System.Collections.IterateForEach<Int32>

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[Queue](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04_CompliationMode=wasm_RunKind=micro/System.Collections.IterateForEach(Int32).Queue(Size%3a%20512).html>) | 37.63 μs | 47.68 μs | 1.27 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/11_30_2020/refs/heads/master_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=micro_Regression/System.Collections.IterateForEach(Int32)_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/11_30_2020/refs/heads/master_x64_ubuntu%2018.04_CompilationMode=wasm_RunKind=micro/System.Collections.IterateForEach(Int32).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Collections.IterateForEach<Int32>*'
```
<details>

.
### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-69dcfc1c-770c-4a9d-8fa4-647fd0cd06c17a73d362ab14a2291/1c0401e4-ad6c-4246-94b7-5de30a430731.zip?sv=2019-07-07&se=2020-12-28T17%3A36%3A04Z&sr=c&sp=rl&sig=Qn5278RC%2BDCAzdwgmi2wM%2BqcGB1UGRZg%2Be3SEThx9j0%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-aa81aa47-caaf-4677-b13f-c99e2fd4e215f4acf44f19647438e/a354c1cf-ad46-440a-b400-2b83f26078d8.zip?sv=2019-07-07&se=2020-12-30T07%3A04%3A51Z&sr=c&sp=rl&sig=2R9042oPERIX48aCSF%2FnTl%2FcpgyiO42bf9HnZuJJwx0%3D>)

#### System.Collections.IterateForEach<Int32>.Queue(Size: 512)

```log
[36936.599 ; 37918.438) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[37918.438 ; 38972.559) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[38972.559 ; 40405.321) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[40405.321 ; 41551.228) | @@@@@@@@@@@@@@@@@@@
[41551.228 ; 42779.759) | @@
[42779.759 ; 44116.064) | @@@@
[44116.064 ; 45067.754) | 
[45067.754 ; 46449.574) | @@
[46449.574 ; 47912.744) | @@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by kg** [comment] 2020-12-11 21:26
Running measurements comparing current dotnet/runtime master and the baseline revision from this issue, I see a consistent performance improvement favoring master across multiple versions of v8 for these Perf_Random tests.

Do we know whether any configuration changes occurred on the machines running these benchmarks? I thought perhaps it was a v8 update (since we don't seem to pin it), but from testing various versions of v8 it seems like performance has consistently improved over time.

**Comment by danmosemsft** [comment] 2020-12-11 21:32
@naricc I guess this should have benchmarks label

**Comment by kg** [comment] 2020-12-11 23:02
I believe I identified the problem. If I manually switch to emscripten 2.0.6 (the version we were configured to use at the baseline revision), it causes a performance drop for ```master``` across all 3 v8 versions I tested. So between emscripten 2.0.6 and 2.0.9 the codegen got worse, at least for these benchmarks. We bumped to 2.0.9 at some point between baseline and now. It can be easy to miss this since by default most of our workflows do not involve moving to the currently selected version of emscripten.

**Comment by naricc** [comment] 2020-12-12 04:04
@danmosemsft Thank you, I some how missed that that label existed.

**Comment by naricc** [comment] 2020-12-12 04:05
@kg So what should we do about it? Dig into what is wrong and file an issue with emsciptem?

**Comment by kg** [comment] 2020-12-12 05:59
I'm planning to dig into the generated code, but if it's a regression in the interpreter it may be difficult to learn much from it. The interpreter is enormous.

Running tests against 2.0.6, 2.0.7, 2.0.8, and 2.0.9 didn't reveal any obvious point at which the codegen got worse, but it's also just plain hard to tell because the gap between a good run and a bad run is small and the timing variance between runs is big. I had thought BenchmarkDotNet took steps to address this, but it doesn't seem like it's prepared to cope with being run in an interpreter under v8.

Some timings below, for reference (run with ```~/.jsvu/v8-8.9.100 --filter System.Tests.Perf_Random* --iterationTime 2000```)

emscripten 2.0.6, v8 8.9.100, latest master:
```
|       Method |         Mean |     Error |    StdDev |       Median |
|         ctor |  19,487.0 ns |  87.94 ns |  82.26 ns |  19,454.4 ns 
|     Next_int |     184.9 ns |   0.81 ns |   0.64 ns |     185.1 ns 
| Next_int_int |     214.4 ns |   0.71 ns |   0.63 ns |     214.2 ns 
|    NextBytes | 154,001.3 ns | 334.24 ns | 312.65 ns | 153,949.5 ns 
|   NextDouble |     199.3 ns |   2.43 ns |   2.28 ns |     199.8 ns 
```

emscripten 2.0.9
```
|       Method |         Mean |     Error |    StdDev |       Median |
|         ctor |  20,136.7 ns |  41.07 ns |  32.06 ns |  20,141.0 ns 
|     Next_int |     183.3 ns |   0.62 ns |   0.49 ns |     183.4 ns 
| Next_int_int |     263.0 ns |   2.70 ns |   2.25 ns |     262.3 ns 
|    NextBytes | 125,629.6 ns | 452.76 ns | 378.08 ns | 125,594.4 ns 
|   NextDouble |     166.6 ns |   1.53 ns |   1.27 ns |     166.6 ns 
```

The really bad news: This timing increase was not consistent across runtimes. For some of these test runs, v8 8.9.50 was faster than .100, and .138 (the latest) was also faster than .100, in other cases the performance trends positively as you move closer to current v8. You'll notice in this case that while Next_int_int and ctor got slower, NextDouble and NextBytes got faster. 🤷‍♀️

**Comment by kg** [comment] 2020-12-15 21:15
I'm still looking into whether the codegen changed in some significant way, but more test runs have convinced me that BDN measurements for wasm (at least in interpreted mode) are noisy enough to be useless. I'm seeing enormous variances between runs even after I try to control for variables (setting my VM to 2 cores and locking it to specific physical cores, closing everything else i have running, etc). BDN clearly makes efforts to warm the code being measured and determine a good number of iterations to run the test for but something about this execution environment just produces bad data.

It's certainly possible this is a regression, but at this point I can't find any way to prove it or identify when it actually regressed.

**Comment by SamMonoRT** [comment] 2021-06-14 15:44
@kg @naricc - is this still relevant based on recent runs ?

**Closed** 2021-07-07 20:27 UTC
Labels: arch-wasm, area-Codegen-Interpreter-mono, tenet-performance, tenet-performance-benchmarks
