### ISSUE TITLE
Test failure: Loader\ContextualReflection\ContextualReflection\ContextualReflection.cmd

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#55518] opened 2021-07-12 17:12 UTC
CoreCLR windows x86 Checked gcstress0xc

https://dev.azure.com/dnceng/public/_build/results?buildId=1231743&view=ms.vss-test-web.build-test-results-tab&runId=36679588&paneView=debug

```
  Starting:    Loader.ContextualReflection.XUnitWrapper (parallel test collections = on, max threads = 4)
    Loader\ContextualReflection\ContextualReflection\ContextualReflection.cmd [FAIL]
      
      Assert failure(PID 7972 [0x00001f24], Thread: 6620 [0x19dc]): ptrManagedAssemblyLoadContext != NULL
      
      CORECLR! AssemblyNative::GetLoadContextForAssembly + 0xF3 (0x70de4bd3)
      SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x6fd61d92)
      SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x6fd639cb)
      <no module>! <no symbol> + 0x0 (0x08929ab9)
      <no module>! <no symbol> + 0x0 (0x089289b3)
      <no module>! <no symbol> + 0x0 (0x0520eef8)
      <no module>! <no symbol> + 0x0 (0x0520ba88)
      CORECLR! CallDescrWorkerInternal + 0x34 (0x710ef801)
      CORECLR! CallDescrWorker + 0xAA (0x70df5789)
      CORECLR! CallDescrWorkerWithHandler + 0xDE (0x70df58c7)
          File: D:\workspace\_work\1\s\src\coreclr\vm\assemblynative.cpp Line: 1317
          Image: C:\h\w\A53508CA\p\corerun.exe
      
      
      Return code:      1
      Raw output file:      C:\h\w\A53508CA\w\A8DD0917\uploads\Reports\Loader.ContextualReflection\ContextualReflection\ContextualReflection.output.txt
      Raw output:
      BEGIN EXECUTION
       "C:\h\w\A53508CA\p\corerun.exe"  ContextualReflection.dll 
      Expected: 100
      Actual: -1073740286
      END EXECUTION - FAILED
      FAILED
```

@vitek-karas Looks like you've looked at this test in the past: https://github.com/dotnet/runtime/issues/48579

**Comment by mateoatr** [comment] 2021-07-19 15:49
Failed again: [runtime-coreclr gcstress-extra](https://dev.azure.com/dnceng/public/_build/results?buildId=1244444&view=results).

**Comment by buyaa-n** [comment] 2021-07-21 19:19
@Ap0k please take a look, seems same test failure as #48579

**Comment by Ap0k** [comment] 2021-07-26 04:07
@buyaa-n I will look soon

**Comment by VincentBu** [comment] 2021-07-27 01:59
Failed again in [runtime-coreclr gcstress-extra 20210725.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1257932&view=ms.vss-test-web.build-test-results-tab&runId=37305710&paneView=debug&resultId=109594)

Failed tests:
```
CoreCLR windows x86 Checked gcstress0xc_tailcallstress @ Windows.10.Amd64.Open
 - Loader\\ContextualReflection\\ContextualReflection\\ContextualReflection.cmd
```

Error message:
```
Assert failure(PID 3124 [0x00000c34], Thread: 1372 [0x055c]): ptrManagedAssemblyLoadContext != NULL

CORECLR! AssemblyNative::GetLoadContextForAssembly + 0xF3 (0x70725e73)
SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x6f67f9d2)
SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x6f6817eb)
<no module>! <no symbol> + 0x0 (0x081296d9)
<no module>! <no symbol> + 0x0 (0x081285cb)
<no module>! <no symbol> + 0x0 (0x0469eef2)
<no module>! <no symbol> + 0x0 (0x0469ba48)
CORECLR! CallDescrWorkerInternal + 0x34 (0x70a34ba1)
CORECLR! CallDescrWorker + 0xAA (0x707369f9)
CORECLR! CallDescrWorkerWithHandler + 0xDE (0x70736b37)
File: D:\workspace_work\1\s\src\coreclr\vm\assemblynative.cpp Line: 1317
Image: C:\h\w\BFA20A40\p\corerun.exe

Return code:      1
Raw output file:      C:\h\w\BFA20A40\w\A95A08D7\uploads\Reports\Loader.ContextualReflection\ContextualReflection\ContextualReflection.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\BFA20A40\p\corerun.exe"  ContextualReflection.dll
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\BFA20A40\p
C:\h\w\BFA20A40\w\A95A08D7\e\Loader\ContextualReflection\ContextualReflection\ContextualReflection.cmd
Expected: True
Actual:   False

Stack trace
   at Loader_ContextualReflection._ContextualReflection_ContextualReflection_._ContextualReflection_ContextualReflection_cmd() in Loader.ContextualReflection.XUnitWrapper.dll:token 0x6000004+0x284
```

**Comment by BruceForstall** [comment] 2021-07-28 18:44
Another case: https://dev.azure.com/dnceng/public/_build/results?buildId=1262301&view=ms.vss-test-web.build-test-results-tab&runId=37404074&resultId=109138&paneView=debug

**Comment by janvorli** [comment] 2021-08-04 22:24
@Ap0k I've investigated the issue a bit more deeply and the issue seems to be that the dynamic assembly (represented by InternalAssemblyBuilder instance) is referencing a managed LoaderAllocator that doesn't match the assembly load context that we get from pAssembly->GetFile()->GetAssemblyLoadContext(); If I dump the managed dynamic assembly objects in WinDbg and then dump the object referenced by its m_syncRoot, then the one referenced by the m_scout field from that object and finally the m_nativeLoaderAllocator, I get a native AssemblyLoaderAllocator instance that has the m_binderToRelease set to NULL while it should have it set to the same pBinder that we get from the pAssembly->GetFile()->GetAssemblyLoadContext(); 
This is causing the problem, as the assembly itself holds alive a different AssemblyLoadContext than the one it is really loaded into. 
I still don't understand why this happens, but I suspect that the assemblyLoadContext.EnterContextualReflection() is somehow involved.  Maybe we apply the assemblyLoadContext only to some stuff when constructing the dynamic assembly or something like that.

I have also found a way to reliably repro the problem. I have updated the test so that the RunTests method looks like this:
```c#
        public void RunTests()
        {
            for (int i = 0; i < 1000; i++)
            {
                TestDynamicAssembly(true);
                TestDynamicAssembly(false);
            }
        }
```
This always repros the issue with GC stress C.

**Comment by Ap0k** [comment] 2021-08-05 04:35
@janvorli  A separate `AssemblyLoaderAllocator` is created for dynamic assemblies that are created with the 
`AssemblyBuilderAccess.RunAndCollect` flag.
https://github.com/dotnet/runtime/blob/5bef921d41e1dc6832c61d2d6e7cae13dc35a2db/src/coreclr/vm/assembly.cpp#L583
This in turn allows you to unload a dynamic assembly without unloading its associated `AssemblyLoadContext`. This logic works fine if the dumped dynamic assembly is placed in `AssemblyLoadContext.Default` or any other non-unloaded ALC.
Problems begin only when placing the unloaded assembly in the unloaded ALC. In my opinion, the problem is that the GC unloads the managed part of the ALC before the dynamic assembly itself. Although this is rather strange, since when creating the assembly, we explicitly specify ALC as FallbackLoadContextBinder.
https://github.com/dotnet/runtime/blob/5bef921d41e1dc6832c61d2d6e7cae13dc35a2db/src/coreclr/vm/assembly.cpp#L573
I think the problem is precisely in this and the work should be carried out in this direction.

**Comment by janvorli** [comment] 2021-08-05 12:47
You are right. I believe that the fix should be to create dependency link between the LoaderAllocator of the dynamic assembly and the LoaderAllocator of the AssemblyLoadContext that we use for the contextual reflection. So that the latter would be held alive as long as the former exists. There is a LoaderAllocator::EnsureReference function that does that.

**Comment by vitek-karas** [comment] 2021-08-09 12:51
@Ap0k Do you think that https://github.com/dotnet/runtime/pull/56668 should fix this issue? Should we close it then?

**Comment by Ap0k** [comment] 2021-08-09 13:16
@vitek-karas I think #56668 solves this problem. The ticket can be closed.

**Closed** 2021-08-09 14:50 UTC
Labels: area-System.Reflection, GCStress, needs further triage
