### ISSUE TITLE
System.Text.json deserialize doesn't support case insensitive Hashset 

### ISSUE THREAD

**Issue by lyndaidaii** [dotnet/runtime#67311] opened 2022-03-29 22:22 UTC
### Description

We initialized hashset with case insensitive in object, we used system.text.json deserialize content from json file to object. 
Noticed that Hashset was case sensitive, not insensitive as expected

### Reproduction Steps

```
public class Config
{
  public HashSet<string>Set {get; set;}
  public Config(){
      Set = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
  } 

// json contains a list of string. 
public class initialize
{
  var options = new JsonSerializerOptions
  {
      PropertyNameCaseInsensitive = true
  };
  Config config = JsonSerializer.Deserialize<Config>(json, options);
}
```

### Expected behavior

expected to be case insensitive.

### Actual behavior

HashSet is case sensitive

### Known Workarounds

```
public class Config
{
  public HashSet<string>Set {get;}
  public Config(HashSet<string> set){
      Set = new HashSet<string>(set, StringComparer.OrdinalIgnoreCase);
  } 

// json contains a list of string. 
public class initialize
{
  var options = new JsonSerializerOptions
  {
      PropertyNameCaseInsensitive = true
  };
  Config config = JsonSerializer.Deserialize<Config>(json, options);
}
```

**Comment by danmoseley** [comment] 2022-03-30 02:27
@lyndaidaii can you please update your sample with a minimal, runnable repro example? BTW you can use triple back ticks above and below to format as code.

**Comment by eiriktsarpalis** [comment] 2022-03-30 08:52
Likely related to #30258. System.Text.Json does not currently support appending elements to properties with existing collections and we're looking to get this addressed in .NET 7.

**Comment by eiriktsarpalis** [comment] 2022-04-04 12:11
Closing as duplicate of #30258. I should point out that the `PropertyNameCaseInsensitive` concerns matching JSON properties to POCO properties, and does not have any impact on the case sensitivity of deserialized dictionary types.

**Closed by eiriktsarpalis** 2022-04-04 12:11 UTC
Labels: area-System.Text.Json, needs-further-triage
