### ISSUE TITLE
system.text.json IformCollection not supported

### ISSUE THREAD

**Issue by KamranShahid** [dotnet/runtime#31285] opened 2019-10-24 14:04 UTC
I am migrating my newtonsoft implementation to System.text.json. For some auditing purpose i am serializing Request.Form and Request.Query previously
After conversion when i tried same in System.Text.Json i am getting following exception 

```
System.NotSupportedException: The collection type 'Microsoft.AspNetCore.Http.IFormCollection' on '<>f__AnonymousType1`2[Microsoft.AspNetCore.Http.IFormCollection,Microsoft.AspNetCore.Http.IQueryCollection].Form' is not supported.
   at System.Text.Json.JsonClassInfo.GetElementType(Type propertyType, Type parentType, MemberInfo memberInfo, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo.CreateProperty(Type declaredPropertyType, Type runtimePropertyType, Type implementedPropertyType, PropertyInfo propertyInfo, Type parentClassType, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo.AddProperty(Type propertyType, PropertyInfo propertyInfo, Type classType, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)

```

**Comment by layomia** [comment] 2020-07-31 21:10
This is a duplicate of https://github.com/dotnet/runtime/issues/1559. The issue here is that the element type [StringValues](https://docs.microsoft.com/dotnet/api/microsoft.extensions.primitives.stringvalues?view=dotnet-plat-ext-3.1) is currently not supported for deserialization as it doesn't have a public parameterless ctor. The serializer would need to implement a new convention where we check for ctors that take a T array (`T[]`).

**Closed by layomia** 2020-07-31 21:10 UTC
Labels: area-System.Text.Json
