### ISSUE TITLE
SSL connection ERROR - dotnet core 3.0 + OpenSSL 1.1.1 + Ubuntu Server 18.04

### ISSUE THREAD

**Issue by programando-ideas** [dotnet/runtime#662] opened 2019-12-07 15:50 UTC
Hi! please help me. 

With this code

```c#
            try
            {
                var client = new HttpClient();
                var result = client.GetAsync("https://api.twilio.com:8443/").Result;
                Console.WriteLine(result);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message, e);
            }
```

give me this error

`One or more errors occurred. (The SSL connection could not be established, see inner exception.)`

Information about the execution environment

```
dotnet core 3.0 Console App
<TargetFramework>netcoreapp3.0</TargetFramework>

$:# openssl version
	OpenSSL 1.1.1d  10 Sep 2019

$:# dotnet --list-runtimes
	Microsoft.AspNetCore.All 2.1.14 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
	Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
	Microsoft.AspNetCore.App 2.1.14 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
	Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
	Microsoft.AspNetCore.App 3.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
	Microsoft.NETCore.App 2.1.14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
	Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
	Microsoft.NETCore.App 3.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

$:# lsb_release -a
	No LSB modules are available.
	Distributor ID: Ubuntu
	Description:    Ubuntu 18.04.3 LTS
	Release:        18.04
	Codename:       bionic

```

in dotnet core 2.2 this works.
thanks!

**Comment by davidsh** [comment] 2019-12-07 16:18
>One or more errors occurred. (The SSL connection could not be established, see inner exception.)

Can you please post more information about this error? Please include the complete error message including the call stack.

**Comment by programando-ideas** [comment] 2019-12-07 18:13
Hi @davidsh, thanks for your response.

This is the code, there is a ConsoleApp dotnet core 3.0

```
using System;
using System.Net.Http;

namespace Pruebatwilio
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                var client = new HttpClient();
                var result = client.GetAsync("https://twilio.com/").Result;
                Console.WriteLine(result);
                Console.WriteLine(result.Content);
            }
            catch (Exception e)
            {
                Console.WriteLine("ERROR: " + e.Message);
                Console.WriteLine("StackTrace: " + e.StackTrace);
            }
        }
    }
}
```

The error is:
```

ERROR: One or more errors occurred. (The SSL connection could not be established                                                                                             , see inner exception.)
StackTrace:    
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitComple                                                                                             tionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Pruebatwilio.Program.Main(String[] args) in C:\Users\Luciano\source\repos\                                                                                             PruebaMailJet\PruebaMailJet\Program.cs:line 56
```

In Windows this works, but, in Ubuntu 18.04 with openssl 1.1.1d doesn't work. 

In this [issue#1941](https://github.com/dotnet/core/issues/1941) you can found the similar problem, but the solution doesn's work form me.

if you do this it works, the problem is that I get Twilio's api from nuget and I can't alter its source code.

```
var handler = new HttpClientHandler
            {
                ServerCertificateCustomValidationCallback = (message, cert, chain, errors) =>{  return true;  }
            };
var client = new HttpClient(handler );

```
I also don't think it's right to skip the certificate validation.

**Comment by programando-ideas** [comment] 2019-12-07 18:15
Hi @davidsh, thanks for your response.

This is the code, there is a ConsoleApp dotnet core 3.0

```
using System;
using System.Net.Http;

namespace Pruebatwilio
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                var client = new HttpClient();
                var result = client.GetAsync("https://twilio.com/").Result;
                Console.WriteLine(result);
                Console.WriteLine(result.Content);
            }
            catch (Exception e)
            {
                Console.WriteLine("ERROR: " + e.Message);
                Console.WriteLine("StackTrace: " + e.StackTrace);
            }
        }
    }
}
```

The error is:
```

ERROR: One or more errors occurred. (The SSL connection could not be established                                                                                             , see inner exception.)
StackTrace:    
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitComple                                                                                             tionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Pruebatwilio.Program.Main(String[] args) in C:\Users\Luciano\source\repos\                                                                                             PruebaMailJet\PruebaMailJet\Program.cs:line 56
```

In Windows this works, but, in Ubuntu 18.04 with openssl 1.1.1d doesn't work. 

In this [issue#1941](https://github.com/dotnet/core/issues/1941) you can found the similar problem, but the solution doesn's work form me.

if you do this it works, the problem is that I get Twilio's api from nuget and I can't alter its source code.

```
var handler = new HttpClientHandler
            {
                ServerCertificateCustomValidationCallback = (message, cert, chain, errors) =>{  return true;  }
            };
var client = new HttpClient(handler );

```
I also don't think it's right to skip the certificate validation.

I also tried this https://unix.stackexchange.com/questions/90450/adding-a-self-signed-certificate-to-the-trusted-list but it didn't work either

**Comment by davidsh** [comment] 2019-12-07 20:31
On my Ubuntu 18.04.3 LTS I have "OpenSSL 1.1.1  11 Sep 2018".  It is the latest one that is obtained when doing an "apt-get install openssl".

So, did you manually update to OpenSSL 1.1.1d ?

**Comment by davidsh** [comment] 2019-12-07 20:36
@bartonjs

**Comment by vcsjones** [comment] 2019-12-07 21:41
I can't reproduce this with 1.1.1c that is in-the-box with Ubuntu, however if I build the 1.1.1d tag myself and use that:

```
LD_PRELOAD=/code/personal/openssl/libssl.so:/code/personal/openssl/libcrypto.so dotnet run
```

I get:

> One or more errors occurred. (The SSL connection could not be established, see inner exception.)

> The SSL connection could not be established, see inner exception.

> The remote certificate is invalid according to the validation procedure.

**Comment by davidsh** [comment] 2019-12-07 21:44
>The remote certificate is invalid according to the validation procedure.

Usually this happens if you custom install a new OpenSSL and don't re-enable to default set of trusted roots.  See https://github.com/dotnet/core/issues/1941#issuecomment-421387136 for guidance.

What happens if you use 'curl' instead of .NET Core? Is 'curl' able to connect to that HTTPS site?

**Comment by vcsjones** [comment] 2019-12-07 21:49
@davidsh you're right, my mistake. When I get the root store set back up correctly both OpenSSL 1.1.1d and curl built with 1.1.1d work correctly.

**Comment by vcsjones** [comment] 2019-12-07 21:57
@programando-ideas does running with `export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt` address the problem for you?

**Comment by programando-ideas** [comment] 2019-12-08 00:34
Hi @vcsjones @davidsh.

The command `export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt` and `update-ca-certificates` did not work for me.

In the end I made a **downgrade from version 1.1.1d to 1.1.1 and it worked**. Before testing the example, I ran the `update-ca-certificates` command. Obviously there is a problem with OpenSSL version 1.1.1d :(

Can you inform to the community of this problem?

thanks very much for your help!!

**Comment by davidsh** [comment] 2019-12-08 00:42
@wfurt

**Comment by karelz** [comment] 2020-03-26 16:22
Triage: Looks like a problem in OpenSSL 1.1.1d. Not actionable for us, closing.

**Closed by karelz** 2020-03-26 16:22 UTC
Labels: area-System.Net.Http, os-linux, untriaged
