### ISSUE TITLE
Check new Guid at compile time if available

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#101517] opened 2024-04-24 20:01 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Check-new-Guid-at-compile-time-if-availa/10594406)._

---
![image](https://github.com/dotnet/runtime/assets/5169960/88920564-2f43-4e08-b5a7-a87361458db9)

Please: Compile time error or warning if string constant is invalid.

---
#### Feedback Bot on 2/26/2024, 02:27 AM: 

(private comment, text removed)

**Comment by terrajobst** [comment] 2024-04-24 20:01
*if* we do this, this should be analyzer but frankly I don't see the value.

**Comment by stephentoub** [comment] 2024-04-24 20:10
I can't see the provided image and so don't know what exactly is being requested. Guessing this is to warn if someone does `Guid.Parse("somethingnotaguid")`?  I think this would effectively be the analyzer half of https://github.com/dotnet/runtime/issues/79655, where _if_ we were to add a StringSyntaxAttribute.Guid, then we'd both annotate relevant parameters and ship an analyzer that analyzed constants passed to those parameters. But I'm also similarly skeptical of the ROI.

**Comment by tannergooding** [comment] 2024-04-24 20:18
Interestingly enough, Roslyn actually has a built in guid string validation mechanism already and uses it for the `System.Runtime.InteropServices.GuidAttribute`: https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBLANmgExAGoAfAAQAYACcgRgDoAlAVwDsNsBbGBgSQ4woEAA4BlIQDdsYGAGcA3AFgAUKoDaAcRbYCACgBEAUQAiAJjoBWAMIBBAMxwAnGaRG4KWwCFrzsyi84IyYmAHkmAwBKAF1VcntaM2pragBvagBfIA===

That is, the following program
```csharp

**Comment by terrajobst** [comment] 2024-04-24 20:25
@stephentoub 

> I can't see the provided image and so don't know what exactly is being requested.

Looks like that got broken when transferring DevCommunity pictures. I fixed it by hand.

> I think this would effectively be the analyzer half of #79655, where _if_ we were to add a StringSyntaxAttribute.Guid

That would be reasonable IMHO but yeah, GUIDs are probably low on that list.

@tannergooding 

> Interestingly enough, Roslyn actually has a built in guid string validation mechanism already and uses it for the `System.Runtime.InteropServices.GuidAttribute`:

That's funny actually. If I had to guess, they implemented that because GuidAttribute for COM are encoded specially in metadata and the underlying format requries a valid GUID.

**Comment by stephentoub** [comment] 2024-07-02 12:59
Closing as a duplicate of https://github.com/dotnet/runtime/issues/79655

**Closed by stephentoub** 2024-07-02 12:59 UTC
Labels: area-System.Runtime, untriaged, code-analyzer
