### ISSUE TITLE
Test failure: profiler\\multiple\\multiple\\multiple.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#98787] opened 2024-02-22 01:24 UTC
**Failed in:** [runtime-coreclr jitstress 20240220.2](https://dev.azure.com/dnceng-public/public/_build/results?buildId=573869&view=ms.vss-test-web.build-test-results-tab&runId=13756632&resultId=120131&paneView=debug)

**Failed tests:**
```
coreclr windows arm64 Checked zapdisable @ Windows.11.Arm64.Open
    - profiler\\multiple\\multiple\\multiple.cmd
```

**Error message:**
```
 Unhandled exception. System.Exception: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
   at Profiler.Tests.ProfilerTestRunner.FailFastWithMessage(String error)
   at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions, Dictionary`2 envVars, String reverseServerName, Boolean loadAsNotification, Int32 notificationCopies)
   at Profiler.Tests.MultiplyLoaded.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\AEC90971\w\AD460975\uploads\Reports\profiler.multiple\multiple\multiple.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\AEC90971\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  multiple.dll 
Profiler path: C:\h\w\AEC90971\w\AD460975\e\profiler\multiple\multiple\Profiler.dll
Profiler path: C:\h\w\AEC90971\w\AD460975\e\profiler\multiple\multiple\Profiler.dll
Profiler.dll!DllGetClassObject
MultiplyLoaded::Initialize
Profiler.dll!Profiler::Initialize
Profiler.dll!DllGetClassObject
MultiplyLoaded::Initialize
Profiler.dll!Profiler::Initialize
Profiler path: C:\h\w\AEC90971\w\AD460975\e\profiler\multiple\multiple\Profiler.dll
Profiler.dll!DllGetClassObject
MultiplyLoaded::InitializeForAttach
Profiler.dll!Profiler::Initialize
Throwing exception
Exception caught
Waiting for profilers to all detach
Profiler did not set the callback, test will fail.
MultiplyLoaded::ExceptionThrown, number seen = 1
MultiplyLoaded::ExceptionThrown, number seen = 2
MultiplyLoaded::ExceptionThrown, number seen = 3
Requesting detach!!
RequestProfilerDetach hr=0x0
Requesting detach!!
Requesting detach!!
ProfilerDetachSucceeded _detachCount=1
RequestProfilerDetach hr=0x0
RequestProfilerDetach hr=0x0
ProfilerDetachSucceeded _detachCount=2

Test failed: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
Expected: 100
Actual: -532462766
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:\cores since 2/21/2024 5:55:29 AM
Processing C:\cores\corerun.exe.8124.dmp
Unable to find cdb.exe at C:\Program Files (x86)\Windows Kits\10\Debuggers\arm64\cdb.exe
Processing C:\cores\WindowsPackageManagerServer.exe.3712.dmp
Unable to find cdb.exe at C:\Program Files (x86)\Windows Kits\10\Debuggers\arm64\cdb.exe
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\AEC90971\p
> C:\h\w\AEC90971\w\AD460975\e\profiler\multiple\multiple\multiple.cmd
```

**Stack trace:**
```
   at profiler_multiple._multiple_multiple_._multiple_multiple_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by BruceForstall** [comment] 2024-02-26 00:28
@davmason Looks like a profiler test "flaky" failure?

**Comment by tommcdon** [comment] 2024-02-26 15:56
@davmason is this fixed by https://github.com/dotnet/runtime/pull/98685?

**Comment by kunalspathak** [comment] 2024-02-27 19:50
Dup of https://github.com/dotnet/runtime/issues/98817

**Comment by davmason** [comment] 2024-02-28 08:14
Closing as dupe of #98817

**Closed by davmason** 2024-02-28 08:14 UTC
Labels: arch-arm64, os-windows, JitStress, area-Diagnostics-coreclr, blocking-clean-ci-optional
