### ISSUE TITLE
System.Text.Json: Support DateOnly and TimeOnly members

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#61098] opened 2021-11-02 13:27 UTC
### Description

.NET should support (de)serialization of DateOnly and TimeOnly members

### Reproduction Steps

Serialize a class that has a DateOnly or TimeOnly member.

### Expected behavior

It should work.

### Actual behavior

It errors:
```
System.NotSupportedException: 'Serialization and deserialization of 'System.DateOnly' instances are not supported. Path: $.Date.'
```

### Regression?

No

### Known Workarounds

Create a custom converter.

**Comment by stephentoub** [comment] 2021-11-02 13:31
Duplicate of https://github.com/dotnet/runtime/issues/53539

**Closed by stephentoub** 2021-11-02 13:31 UTC
Labels: area-System.Text.Json, untriaged
