### ISSUE TITLE
Distributed transactions

### ISSUE THREAD

**Issue by pappasa** [dotnet/runtime#47152] opened 2021-01-19 10:13 UTC
Our business logic code in .NET 4.0 uses System.EnterpriseServices (COM+) which takes care of distributed transactions (for example get from IBM MQ and write to the database, or call the host, through a COM+ function, and write to the database). We would like to port the business logic code to .NET 5. We therefore need distributed transactions.

**Comment by roji** [comment] 2021-01-19 20:39
Duplicate of #715

**Closed by roji** 2021-01-19 20:39 UTC
Labels: area-System.Transactions, untriaged
