### ISSUE TITLE
NETSDK1203: Ahead-of-time compilation is not supported for the target runtime identifier 'ios-arm64'.

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#95958] opened 2023-12-13 11:02 UTC
_From @rsanford-hh2 on Wed, 13 Dec 2023 04:09:26 GMT_

### Steps to Reproduce

Following the instructions at https://github.com/dotnet/samples/tree/main/core/nativeaot/NativeLibrary.
- dotnet new classlib -o NativeLibrary
- add the PublishAOT true flag to the .csproj file
- `dotnet publish /p:NativeLib=Shared --use-current-runtime` succeeds
- `dotnet publish -r:ios-arm64' fails with the error message in the title of the issue and in the Actual Behavior section

### Expected Behavior
I expect that I will get an AOT library for iOS. iOS for ARM64 is experimental according to... 
https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/?tabs=net8plus%2Cwindows 

### Actual Behavior
NETSDK1203: Ahead-of-time compilation is not supported for the target runtime identifier 'ios-arm64'. [/Users/myusername/Projects/MyNetProject/NativeLib/NativeLib.csproj::TargetFramework=net8.0]
### Environment

<details>
<summary>Version information</summary>
```
Visual Studio Professional 2022 for Mac
Version 17.6.7 (build 417)
Installation UUID: da5a6a50-0b52-4e5f-8830-f56890f8cecd

Runtime
.NET 7.0.3 (64-bit)
Architecture: Arm64
Microsoft.macOS.Sdk 13.1.1007; git-rev-head:8afca776a0a96613dfb7200e0917bb57f9ed5583; git-branch:release/7.0.1xx-xcode14.2

Roslyn (Language Service)
4.6.0-3.23180.6+99e956e42697a6dd886d1e12478ea2b27cceacfa

NuGet
Version: 6.4.0.117

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/8.0.100/Sdks
SDK Versions:
	8.0.100
	7.0.311
	6.0.417
	6.0.416
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	8.0.0
	7.0.14
	6.0.25
	6.0.24

Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode: 15.1 22502
Build: 15C65

Xamarin.Mac
Version: 9.3.0.23 Visual Studio Professional
Hash: 9defd91b3
Branch: xcode14.3
Build date: 2023-10-23 16:14:59-0400

Xamarin.iOS
Version: 16.4.0.23 Visual Studio Professional
Hash: 9defd91b3
Branch: xcode14.3
Build date: 2023-10-23 16:15:00-0400

Xamarin Designer
Version: 17.6.3.9
Hash: 2648399ae8
Branch: remotes/origin/d17-6
Build date: 2023-11-10 12:19:46 UTC

Xamarin.Android
Version: 13.2.2.0 (Visual Studio Professional)
Commit: xamarin-android/d17-5/45b0e14
Android SDK: /Users/ebenezer/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		12.0 (API level 31)
		13.0 (API level 33)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 34.0.3
SDK Build Tools Version: 32.0.0

Build Information: 
Mono: d9a6e87
Java.Interop: xamarin/java.interop/d17-5@149d70fe
SQLite: xamarin/sqlite/3.40.1@68c69d8
Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.6.0.50
Hash: a715dca
Branch: HEAD
Build date: 2023-11-10 12:19:52 UTC

Android Device Manager
Version: 0.0.0.1309
Hash: 06e3e77
Branch: HEAD
Build date: 2023-11-10 12:19:52 UTC

Build Information
Release ID: 1706070417
Git revision: 179aa48a5702754e41a8218d0403ddc3be46706f
Build date: 2023-11-10 12:18:09+00
Build branch: release-17.6
Build lane: release-17.6

Operating System
Mac OS X 14.2.0
Darwin 23.2.0 Darwin Kernel Version 23.2.0
    Wed Nov 15 21:55:06 PST 2023
    root:xnu-10002.61.3~2/RELEASE_ARM64_T6020 arm64

Enabled user installed extensions
Project System Tools 0.13
```

</details>

### Example Project (If Possible)

[NativeLib_Debug_Build_2023-12-13T04_04_13.5060410Z.msbuild.log](https://github.com/xamarin/xamarin-macios/files/13655816/NativeLib_Debug_Build_2023-12-13T04_04_13.5060410Z.msbuild.log)

_Copied from original issue xamarin/xamarin-macios#19626_

**Comment by rolfbjarne** [comment] 2023-12-13 11:03
CC @steveisok I believe this is what you've been working on for .NET 8

**Comment by jkotas** [comment] 2023-12-13 13:42
@ivanpovazan Duplicate of https://github.com/dotnet/runtime/issues/88737 ?

**Comment by ivanpovazan** [comment] 2023-12-13 13:51
@jkotas yes that is correct.
Closing this issues as a duplicate of https://github.com/dotnet/runtime/issues/88737

**Closed by ivanpovazan** 2023-12-13 13:51 UTC
Labels: untriaged, os-ios, area-NativeAOT-coreclr
