### ISSUE TITLE
KeepAlive on macOS (packets don't flow) and Linux (failure on API call) issues

### ISSUE THREAD

**Issue by alexkeh** [dotnet/runtime#42679] opened 2020-09-24 15:02 UTC
We're using .NET Core 3.1 APIs to use KeepAlive functionality. My team implements a database ADO.NET provider. We hit a problem when using KeepAlive on macOS and on Linux. Any recommendations for how to resolve these two issues or are they bugs? 

* On Windows, the APIs work fine.
* On macOS, the APIs return success on call, but Keepalive packets don't flow.
* On Oracle Linux, the APIs return failure on call (invalid argument, see below).

Exception on Linux:

 ---> System.Net.Sockets.SocketException (22): Invalid argument
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OracleInternal.Network.TcpTransportAdapter.SetKeepAlive_Core3(Socket sock, Int32 time, Int32 interval)

**Comment by wfurt** [comment] 2020-09-24 15:35
can you provide repro app? What OS/Kernel are you testing on?

**Comment by alexkeh** [comment] 2020-09-24 15:39
@scotmac

**Comment by ScotMac** [comment] 2020-09-29 04:45
Linux is Oracle Linux  4.1.12.124.

The MacOS is 17.7 (Darwin version).

We are simply doing the following:
  soc.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.KeepAlive, true);
  soc.SetSocketOption(SocketOptionLevel.Tcp, SocketOptionName.TcpKeepAliveRetryCount, count);
  soc.SetSocketOption(SocketOptionLevel.Tcp, SocketOptionName.TcpKeepAliveTime, time);
  soc.SetSocketOption(SocketOptionLevel.Tcp, SocketOptionName.TcpKeepAliveInterval, interval);

Where the count is fixed at 10, and the time and interval are config items that were set to 5000ms and 2000ms, respectively, for the test runs.

**Comment by wfurt** [comment] 2020-09-29 04:52
17.7 kernel would map to 10.13 and that is way out of support. What `sw_vers` gives you on MacOS?

**Comment by wfurt** [comment] 2020-09-29 04:53
btw did you test this on any other macOS version?

**Comment by wfurt** [comment] 2020-09-29 06:37
So far I was not able to reproduce it on Linux with similar kernels. Is there VM image that can be used for testing? 
Also the time and interval is in [seconds](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socketoptionname?view=netcore-3.1#System_Net_Sockets_SocketOptionName_TcpKeepAliveTime) right? So I assume you pass in 5 and 2? Is address family specified and any other options set? Complete runnable repro would be much better starting point.It is not clear from the trace what setting is actually failing. 

By brief look, Windows may expect time in ms and that contradicts documentation. 
https://github.com/dotnet/corefx/commit/88a2b199ffddc2171c65b583025d7f2acd3224b9
cc: @stephentoub

**Comment by ScotMac** [comment] 2020-09-29 15:58
We are definitely passing milliseconds. 

"By brief look, Windows may expect time in ms and that contradicts documentation." Maybe that is why it works on windows and not on the other platforms? Also, windows has always taken ms for its other interfaces.

I will try it via seconds on MacOS and Linux.

**Comment by wfurt** [comment] 2020-10-01 05:15
Do you have any updates @ScotMac? I verified that Linux expects time in seconds (according to documentation).
Linux kernel will fail with EINVAL if the values are smaller than 1 or bigger then MAX_TCP_KEEPINTVL or MAX_TCP_KEEPIDLE (both set to 32767) That should work fine for the times you mentioned but it would be suspect for anything beyond 32s if passed in as ms. 
On Windows 10, the interval does not seems be respected and both initial delay and interval are determined by time value.

**Comment by ScotMac** [comment] 2020-10-01 17:17
@wfurt, see above where i said we are passing 5 and 2 (we take the values IN via ms, but convert to seconds for the NEW interface).

**Comment by karelz** [comment] 2021-05-13 16:04
Triage: Unclear what is the next step here. Looks like it was just confusion between seconds and milliseconds.
@wfurt thinks we lack currently repro.

Closing for now. If there is more details, feel free to reopen and we can decide on 6.0 vs. Future.

**Closed by karelz** 2021-05-13 16:04 UTC
Labels: area-System.Net.Sockets, bug
