### ISSUE TITLE
'System.PlatformNotSupportedException' and 'System.Configuration.ConfigurationErrorsException' in System.Configuration.ConfigurationManager.dll

### ISSUE THREAD

**Issue by ivan2007** [dotnet/runtime#48423] opened 2021-02-17 21:51 UTC
### Description
Win32 app that calls a c++/cli NET Core 3.1 lib. The c++/cli lib calls a WPF NET Core 3.1 lib
Running the app the output window of VS shows:
'System.PlatformNotSupportedException' in System.Configuration.ConfigurationManager.dll
'System.Configuration.ConfigurationErrorsException' in System.Configuration.ConfigurationManager.dll
You can find more details [here ](https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/306) and [here](https://github.com/dotnet/wpf/issues/2395#issuecomment-779458130)
The test project can be found [here](https://github.com/ivan2007/ViewerNativeNetCore)

### Configuration
NET Core 3.1
architecture x64

**Comment by ericstj** [comment] 2021-02-17 22:09
Duplicate of https://github.com/dotnet/runtime/issues/25027, already fixed in 5.0.

These are first chance exceptions.  Can you clarify how your application is impacted by this issue?

**Comment by ivan2007** [comment] 2021-02-17 23:16
Ok, I only followed the suggestion of @SamBent. I am not trying to use an app.exe.config file so for this issue I am fine

**Closed** 2021-02-18 01:36 UTC
Labels: area-System.Configuration, untriaged

**Comment by ericstj** [comment] 2021-02-18 01:37
Thanks for the clarification
