### ISSUE TITLE
Office Interop on .net core not working with Office 2021, but works on framework. 

### ISSUE THREAD

**Issue by the-black-wolf** [dotnet/runtime#76833] opened 2022-09-29 11:27 UTC
Currently, Microsoft.Office.Interop.Excel libary on NuGet, as of June, is 15.0.4795.1001. However, Office 2021 has been out for a year and this interop library does not work with it using .net core (via .net standard). It reports:

`{"Could not load file or assembly 'office, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c'. The system cannot find the file specified.":"office, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c"}`

so it seems to bind up to Office 2019 and won't bind to v16 COM. However, we updated all the workstations, so nobody has 2019 any more. 

The weird thing is, the .NET Framework using the same library properly works, this only happens  in core, specifically net60. 

Can you please update Office interop libraries to seamlessly support Office2021?

**Comment by AaronRobinsonMSFT** [comment] 2022-10-10 18:49
@the-black-wolf I think we are likely to see this is related to some assembly binder logic that is being picky about version. I'm not entirely sure the best way to reproduce this locally. It would be helpful if we could get a track of the failure and see what the loader is or isn't finding. Details on this tracing can be found at https://learn.microsoft.com/dotnet/core/dependency-loading/collect-details.

/cc @elinor-fung

**Comment by the-black-wolf** [comment] 2022-10-11 08:08
@AaronRobinsonMSFT hi, I've collected the trace, it shows resolution failing for office 

[trace.zip](https://github.com/dotnet/runtime/files/9752864/trace.zip)

**Comment by AaronRobinsonMSFT** [comment] 2022-10-11 17:43
@the-black-wolf I've been able to reproduce this issue. I initially was very confused how this was working at all but looking at the [Microsoft.Office.Interop.Excel](https://www.nuget.org/packages/Microsoft.Office.Interop.Excel) package on NuGet, I see the problem. The most telling is the following from the packages README:

> This an assembly you can use for Excel 2013/2016/2019 COM interop, generated and signed by Microsoft. This is entirely unsupported and there is no license since it is a repackaging of Office assemblies.

This package is not supported by Microsoft and isn't really complete in its current form. This works without issue on .NET Framework because the GAC contains the needed assemblies. However, on .NET Core/.NET 5+ there is no such mechanism so this load will always fail without some knowledge of where the additional assemblies exist (that is, `office`). Using the `ildasm` tool, the dependencies for `Microsoft.Office.Interop.Excel` can be found:

```
.assembly extern mscorlib
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )                         // .z\V.4..
  .ver 2:0:0:0
}
.assembly extern office
{
  .publickeytoken = (71 E9 BC E1 11 E9 42 9C )                         // q.....B.
  .ver 15:0:0:0
}
.assembly extern Microsoft.Vbe.Interop
{
  .publickeytoken = (71 E9 BC E1 11 E9 42 9C )                         // q.....B.
  .ver 15:0:0:0
}
```

It isn't obvious why/how any previous version of .NET Core would have been able to load this assembly, but without the dependent assemblies, consuming this assembly will not work. The author should be contacted to update the package appropriately or perhaps understand the purposes of this package. This package may have value if the definitions of the interfaces are being used in an embedded (PIA) scenario, but I don't see how they can be used directly.

Since this isn't a runtime issue but rather consumption of a 3rd party package issue, I am going to close this issue.

**Closed by AaronRobinsonMSFT** 2022-10-11 17:43 UTC
Labels: area-Interop-coreclr, untriaged, needs-further-triage

**Comment by the-black-wolf** [comment] 2022-10-12 06:25
@AaronRobinsonMSFT - wait, you are saying that Microsoft.Office.Interop.Excel package is not made by Microsoft? I thought you guys registered/reserved Microsoft.* prefix for your packages? 

Either way, which Office packages are then published by MS?

**Comment by ericstj** [comment] 2022-10-12 19:03
Prefix reservation didn't always exist in NuGet.  That was added later (2017?) and it looks like these packages predate that and remain.

From https://learn.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation
> All previously existing packages that match the reserved ID prefix, but are not owned by the owner of the reserved prefix will remain unchanged (they will not be unlisted, but they will also not have the visual indicator). In addition, owners of these packages will still be able to submit new versions to the package.

**Comment by the-black-wolf** [comment] 2022-10-14 07:23
@AaronRobinsonMSFT ah, ok. sorry I wasted your time on debugging this then, I was acting under the impression this is an official interop package for Office (you should make one though, avoid the ambiguity).
