### ISSUE TITLE
Json serializer code generator doesn't support internal constructors

### ISSUE THREAD

**Issue by dotMorten** [dotnet/runtime#77016] opened 2022-10-13 17:05 UTC
### Description

If I have a public class that I want to be able to deserialize, but I don't want that class publicly constructable, I can no longer deserialize it, even though the generated deserializer code has access to the internal constructor.

This issue prevents moving from `DataContractJsonSerializer` to S.T.J.

### Reproduction Steps

In a console app, add the following code:
```cs
using System.Text.Json;
using System.Text.Json.Serialization;

string json = "{\"name\":\"Hello World\"}";

var obj = JsonSerializer.Deserialize(json, MyDataModelSerializationContext.Default.MyDataModel);

[JsonSerializable(typeof(MyDataModel))]
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
internal partial class MyDataModelSerializationContext : JsonSerializerContext
{
}

public class MyDataModel
{
    // [JsonConstructor] Won't make a difference
    internal MyDataModel() { }
    public string? Name { get; set; }
}
```

### Expected behavior

Object deserializes.

### Actual behavior

Exception thrown on deserialize:
> System.NotSupportedException: 'Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'MyDataModel'. Path: $ | LineNumber: 0 | BytePositionInLine: 1.'
![image](https://user-images.githubusercontent.com/1378165/195660127-1992097a-dd81-4c5c-bf03-3f006ff95b46.png)

Looking at the generated code, you'll note the `ObjectCreator` is null.
<img width="496" alt="image" src="https://user-images.githubusercontent.com/1378165/195659841-f3773eae-db27-4933-8f1c-b79b295789dc.png">
Compare that to when the constructor is declared public:
<img width="426" alt="image" src="https://user-images.githubusercontent.com/1378165/195659991-c10acd37-d8bf-4ab5-a86c-35c5ffd465da.png">

### Related
A similar issue is hit with a data model like this:
```cs
internal class MyDataModel
{
    [JsonPropertyName("name")]
    public string? Name { get; internal set; }
}
```
In this case for this internal class, a setter isn't generated for the Name property and during serialization the value is never defined. Granted in this case there's no need to mark it internal since the entire class is already internal - however even if the class is public, I can't restrict the setter from public abuse and only allow the deserializer to set it.

### Known Workarounds

Not really. If I make the entire class internal (and make the constructor public albeit it is effectively internal now), it works again. However I do want my class to be publicly accessible

### Configuration

.net 6.0.401

**Comment by layomia** [comment] 2022-10-13 17:54
Triage: this can be considered for .NET 8.0.

**Comment by eiriktsarpalis** [comment] 2022-10-13 18:01
FWIW this is by design and consistent with the behavior of the reflection-based serializer. A notable exception is internal getter/setter support via the [`JsonIncludeAttribute`](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonincludeattribute?view=net-6.0) -- we might consider extending this to constructors (or extend the `JsonConstructorAttribute` so that internal constructors can be annotated) but obviously there will be restrictions when it comes to the source generator.

**Comment by dotMorten** [comment] 2022-10-13 18:28
> FWIW this is by design and consistent with the behavior of the reflection-based serializer.

I'm literally porting from the reflection based DataContractSerializer and it works just fine with these internal classes and properties. If we don't have parity I find it hard for us to move and start supporting full trimming in our assemblies. Perhaps there could at least be a setting on `JsonSourceGenerationOptions` to support internal members?

**Comment by eiriktsarpalis** [comment] 2022-10-13 20:04
Is making the constructors public an option?

**Comment by dotMorten** [comment] 2022-10-13 20:22
No :(

**Comment by jkotas** [comment] 2022-12-02 00:41
EF Core is running into similar set of issues with source-generating equivalent of private reflection. Once you start looking at this, we should talk about the possible solutions.

**Comment by eiriktsarpalis** [comment] 2022-12-02 16:19
What might be a way to offer a source-generating equivalent of private reflection? I suppose it might be possible to generate member accessor stubs inside the type declaration itself provided it lives in the same project, but is there any other way you have in mind?

**Comment by jkotas** [comment] 2022-12-03 01:52
> What might be a way to offer a source-generating equivalent of private reflection? 

One extreme is to make JIT pattern-match reflection calls with constant inputs and replace them with direct invocations. For example, if you wrote `typeof(MyType).GetMethod("MyMethod", new Type[] { typeof(string), BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance, typeof(int) }).Invoke(thisArg, new object[] { stringArg, intArg })`, the JIT can replace it with `thisArg.MyMethod(stringArg, intArg)` in theory. This would be a very complex and fragile pattern match. I do not think we want to do that.

Other extreme is to emit IL (either via an extra IL .dll or via IL rewriting). It is possible to suppress visibility checks in IL today using `IgnoresAccessChecksToAttribute`. https://gist.github.com/jkotas/ddfeb9ec47bff90b4249534c4cd0761a shows a small demo using Fody. Extra IL file or IL rewriting comes with a bunch of problems that are very hard to solve (e.g. IL rewriting breaks edit-and-continue). I do not think we want to do that.

So the idea is that we may be able to come up with something viable (e.g. new runtime API) between these two extremes.

**Comment by eiriktsarpalis** [comment] 2023-06-12 21:29
Closing in favor of the more general user story tracked in https://github.com/dotnet/runtime/issues/87431

**Closed by eiriktsarpalis** 2023-06-12 21:29 UTC
Labels: enhancement, area-System.Text.Json
