### ISSUE TITLE
Test failure on ARM64 macOS: Unable to find an entry point named 'objc_msgSend_fpret' in shared library '/usr/lib/libobjc.dylib'

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#52962] opened 2021-05-19 10:07 UTC
Example runtime-staging build: https://dev.azure.com/dnceng/public/_build/results?buildId=1137913&view=results

```
Unhandled exception. Xunit.Sdk.ThrowsException: Assert.Throws() Failure
Expected: typeof(System.Runtime.InteropServices.Tests.PendingExceptionTests+PendingException)
Actual:   (No exception was thrown)
   at Xunit.Assert.Throws(Type exceptionType, Exception exception) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\ExceptionAsserts.cs:line 145
   at Xunit.Assert.Throws[T](Func`1 testCode) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\ExceptionAsserts.cs:line 41
   at System.Runtime.InteropServices.Tests.PendingExceptionTests.ValidateSetMessageSendPendingExceptionImpl(MessageSendFunction funcToOverride) in /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/PendingExceptionTests.cs:line 90
   at System.Runtime.InteropServices.Tests.PendingExceptionTests.<>c.<ValidateSetMessageSendPendingException>b__8_0(String funcToOverrideAsStr) in /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/PendingExceptionTests.cs:line 70
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 94
Unhandled exception. System.EntryPointNotFoundException: Unable to find an entry point named 'objc_msgSend_fpret' in shared library '/usr/lib/libobjc.dylib'.
   at System.Runtime.InteropServices.Tests.LibObjC.objc_msgSend_fpret(IntPtr self, IntPtr selector)
   at System.Runtime.InteropServices.Tests.LibObjC.CallPInvoke(MessageSendFunction msgSend, IntPtr inst, IntPtr sel) in /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/LibObjC.cs:line 54
   at System.Runtime.InteropServices.Tests.MessageSendTests.SetMessageSendCallbackImpl(MessageSendFunction[] funcsToOverride) in /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/MessageSendTests.cs:line 137
   at System.Runtime.InteropServices.Tests.MessageSendTests.<>c.<SetMessageSendCallback>b__13_0(String funcsToOverrideAsStr) in /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/MessageSendTests.cs:line 99
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 94
    System.Runtime.InteropServices.Tests.MessageSendTests.SetMessageSendCallback(funcsToOverride: [MsgSend, MsgSendStret]) [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:
        
        Child exception:
          System.EntryPointNotFoundException: Unable to find an entry point named 'objc_msgSend_fpret' in shared library '/usr/lib/libobjc.dylib'.
           at System.Runtime.InteropServices.Tests.LibObjC.objc_msgSend_fpret(IntPtr self, IntPtr selector)
        /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/LibObjC.cs(54,0): at System.Runtime.InteropServices.Tests.LibObjC.CallPInvoke(MessageSendFunction msgSend, IntPtr inst, IntPtr sel)
        /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/MessageSendTests.cs(137,0): at System.Runtime.InteropServices.Tests.MessageSendTests.SetMessageSendCallbackImpl(MessageSendFunction[] funcsToOverride)
        /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/MessageSendTests.cs(99,0): at System.Runtime.InteropServices.Tests.MessageSendTests.<>c.<SetMessageSendCallback>b__13_0(String funcsToOverrideAsStr)
        
        Child process:
          System.Runtime.InteropServices.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Runtime.InteropServices.Tests.MessageSendTests+<>c Void <SetMessageSendCallback>b__13_0(System.String)
        
        Child arguments:
          MsgSend;MsgSendStret
        
    System.Runtime.InteropServices.Tests.PendingExceptionTests.ValidateSetMessageSendPendingException(func: MsgSend) [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:
        
        Child exception:
          Xunit.Sdk.ThrowsException: Assert.Throws() Failure
        Expected: typeof(System.Runtime.InteropServices.Tests.PendingExceptionTests+PendingException)
        Actual:   (No exception was thrown)
        /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/PendingExceptionTests.cs(90,0): at System.Runtime.InteropServices.Tests.PendingExceptionTests.ValidateSetMessageSendPendingExceptionImpl(MessageSendFunction funcToOverride)
        /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/PendingExceptionTests.cs(70,0): at System.Runtime.InteropServices.Tests.PendingExceptionTests.<>c.<ValidateSetMessageSendPendingException>b__8_0(String funcToOverrideAsStr)
        
        Child process:
          System.Runtime.InteropServices.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Runtime.InteropServices.Tests.PendingExceptionTests+<>c Void <ValidateSetMessageSendPendingException>b__8_0(System.String)
        
        Child arguments:
          MsgSend
        
Unhandled exception. Xunit.Sdk.ThrowsException: Assert.Throws() Failure
Expected: typeof(System.Runtime.InteropServices.Tests.PendingExceptionTests+PendingException)
Actual:   (No exception was thrown)
   at Xunit.Assert.Throws(Type exceptionType, Exception exception) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\ExceptionAsserts.cs:line 145
   at Xunit.Assert.Throws[T](Func`1 testCode) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\ExceptionAsserts.cs:line 41
   at System.Runtime.InteropServices.Tests.PendingExceptionTests.ValidateSetMessageSendPendingExceptionImpl(MessageSendFunction funcToOverride) in /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/PendingExceptionTests.cs:line 90
   at System.Runtime.InteropServices.Tests.PendingExceptionTests.<>c.<ValidateSetMessageSendPendingException>b__8_0(String funcToOverrideAsStr) in /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/PendingExceptionTests.cs:line 70
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 94
    System.Runtime.InteropServices.Tests.PendingExceptionTests.ValidateSetMessageSendPendingException(func: MsgSendFpret) [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:
        
        Child exception:
          Xunit.Sdk.ThrowsException: Assert.Throws() Failure
        Expected: typeof(System.Runtime.InteropServices.Tests.PendingExceptionTests+PendingException)
        Actual:   (No exception was thrown)
        /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/PendingExceptionTests.cs(90,0): at System.Runtime.InteropServices.Tests.PendingExceptionTests.ValidateSetMessageSendPendingExceptionImpl(MessageSendFunction funcToOverride)
        /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/PendingExceptionTests.cs(70,0): at System.Runtime.InteropServices.Tests.PendingExceptionTests.<>c.<ValidateSetMessageSendPendingException>b__8_0(String funcToOverrideAsStr)
        
        Child process:
          System.Runtime.InteropServices.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Runtime.InteropServices.Tests.PendingExceptionTests+<>c Void <ValidateSetMessageSendPendingException>b__8_0(System.String)
        
        Child arguments:
          MsgSendFpret
        
Unhandled exception. Xunit.Sdk.ThrowsException: Assert.Throws() Failure
Expected: typeof(System.Runtime.InteropServices.Tests.PendingExceptionTests+PendingException)
Actual:   (No exception was thrown)
   at Xunit.Assert.Throws(Type exceptionType, Exception exception) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\ExceptionAsserts.cs:line 145
   at Xunit.Assert.Throws[T](Func`1 testCode) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\ExceptionAsserts.cs:line 41
   at System.Runtime.InteropServices.Tests.PendingExceptionTests.ValidateSetMessageSendPendingExceptionImpl(MessageSendFunction funcToOverride) in /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/PendingExceptionTests.cs:line 90
   at System.Runtime.InteropServices.Tests.PendingExceptionTests.<>c.<ValidateSetMessageSendPendingException>b__8_0(String funcToOverrideAsStr) in /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/PendingExceptionTests.cs:line 70
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 94
    System.Runtime.InteropServices.Tests.PendingExceptionTests.ValidateSetMessageSendPendingException(func: MsgSendSuper) [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:
        
        Child exception:
          Xunit.Sdk.ThrowsException: Assert.Throws() Failure
        Expected: typeof(System.Runtime.InteropServices.Tests.PendingExceptionTests+PendingException)
        Actual:   (No exception was thrown)
        /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/PendingExceptionTests.cs(90,0): at System.Runtime.InteropServices.Tests.PendingExceptionTests.ValidateSetMessageSendPendingExceptionImpl(MessageSendFunction funcToOverride)
        /_/src/libraries/System.Runtime.InteropServices/tests/System/Runtime/InteropServices/ObjectiveC/PendingExceptionTests.cs(70,0): at System.Runtime.InteropServices.Tests.PendingExceptionTests.<>c.<ValidateSetMessageSendPendingException>b__8_0(String funcToOverrideAsStr)
        
        Child process:
          System.Runtime.InteropServices.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Runtime.InteropServices.Tests.PendingExceptionTests+<>c Void <ValidateSetMessageSendPendingException>b__8_0(System.String)
        
        Child arguments:
          MsgSendSuper
        
  Finished:    System.Runtime.InteropServices.Tests
=== TEST EXECUTION SUMMARY ===
   System.Runtime.InteropServices.Tests  Total: 928, Errors: 0, Failed: 4, Skipped: 4, Time: 26.320s
```

**Comment by akoeplinger** [comment] 2021-05-19 10:08
@AaronRobinsonMSFT just found https://github.com/dotnet/runtime/issues/52737, do you think this is the same/similar issue?

**Comment by AaronRobinsonMSFT** [comment] 2021-05-19 15:03
@akoeplinger yes, it is the same issue. It should be fixed today.

**Comment by AaronRobinsonMSFT** [comment] 2021-05-19 15:04
Closing as duplicate of #52737

**Comment by AaronRobinsonMSFT** [comment] 2021-05-19 15:05
Oops. No. This is slightly different. I know the issue here though.

**Closed** 2021-05-20 05:03 UTC
Labels: arch-arm64, area-System.Runtime.InteropServices, in pr, os-mac-os-x
