### ISSUE TITLE
The runtime can't load some types with mutual references.

### ISSUE THREAD

**Issue by gdar91** [dotnet/runtime#78781] opened 2022-11-23 20:24 UTC
### Description

The runtime crashes on some arrangement of types with mutual references, even though the compilation succeeds and there are no cyclic struct references in them.

``Unhandled exception. System.TypeLoadException: Could not load type '***' from assembly ***``

### Reproduction Steps

Take this code, for example:

```
var x = new History<int>(new HistoryF<History<int>, int>(null, 10));

Console.WriteLine($"Hello, World! {x}");



public readonly record struct History<TValue>(HistoryF<History<TValue>, TValue> UnFix);

public readonly record struct HistoryF<THistory, TValue>(HistoryPrevious<THistory, TValue>? Previous, TValue Value);

public sealed record HistoryPrevious<THistory, TValue>(THistory Previous, DateTimeOffset Time);
```

### Expected behavior

I think this should work fine.

### Actual behavior

It will compile fine but will fail at runtime.

### Known Workarounds

It will work if you change the History to a class: ``public sealed record History<TValue>(HistoryF<History<TValue>, TValue> UnFix);``

### Configuration

I'm testing it on .NET 7 (7.0.100) console application on macOS Ventura, arm64 chip.

**Comment by svick** [comment] 2022-11-23 21:41
There *is* a cycle in your `struct`s and the runtime does not allow it, because those are not references.

Specifically:

* `History<int>` has a field of type `HistoryF<History<int>, int>`
* `HistoryF<History<int>, int>` has a field of type `HistoryPrevious<History<int>, int>`
* `HistoryPrevious<History<int>, int>` has a field of type `History<int>`

**Comment by gdar91** [comment] 2022-11-23 21:45
> There _is_ a cycle in your `struct`s and the runtime does not allow it, because those are not references (which is why it works with a class, which is a reference type).
> 
> Specifically:
> 
>     * `History<int>` has a field of type `HistoryF<History<int>, int>`
> 
>     * `HistoryF<History<int>, int>` has a field of type `HistoryPrevious<History<int>, int>`
> 
>     * `HistoryPrevious<History<int>, int>` has a field of type `History<int>`

But it compiles without any errors. AFAIK cycles are allowed if they are done via pointers and in this case, HistoryPrevious is a class that breaks the struct cycle, because it uses a pointer, not a value type.

**Comment by svick** [comment] 2022-11-23 21:46
@gdar91 Sorry, the part that I missed is that `HistoryPrevious` is not a `struct`.

**Comment by teo-tsirpanis** [comment] 2022-11-26 12:24
Duplicate of #6924.

**Closed by teo-tsirpanis** 2022-11-26 12:24 UTC
Labels: area-TypeSystem-coreclr, untriaged
