### ISSUE TITLE
[mono] Regression of BigInteger.Multiply on arm64 AOT-llvm

### ISSUE THREAD

**Issue by matouskozak** [dotnet/runtime#95403] opened 2023-11-29 14:58 UTC
### Description
Mono runtime recorded regressions for `BigInteger.Multiple` https://github.com/dotnet/perf-autofiling-issues/issues/24512 on arm64 AOT-llvm. The regressions are possibly caused by https://github.com/dotnet/runtime/commit/e733539a38458c5c3a64688b55a702444e470700 and isolated to Mono runtime (CoreCLR is unaffected).

### Configuration
Linux arm64 AOT-llvm

### Data

![image](https://github.com/dotnet/runtime/assets/55735845/c1b1e7bf-bd89-4056-a4b0-c41e7979d13e)

**Comment by jkotas** [comment] 2023-11-29 16:51
cc @adamsitnik @kzrnm

**Comment by adamsitnik** [comment] 2023-11-29 18:37
@jkotas as I wrote in https://github.com/dotnet/perf-autofiling-issues/issues/24512#issuecomment-1809833087, CoreCLR has improved on both arm64 and x64. The changes were relatively simple, I don't know what could have caused the regression only on Mono arm64.

**Comment by vargaz** [comment] 2023-12-01 12:40
Can't reproduce this locally.

**Comment by kotlarmilos** [comment] 2024-08-01 10:14
Do we plan this for .NET 9+?

**Comment by tannergooding** [comment] 2024-08-12 17:39
Multiple users cannot reproduce this (I can't either) and there are measured reproducible significant improvements that went along with the change (https://github.com/dotnet/perf-autofiling-issues/issues/24513).

Please feel free to reopen if we feel this needs more in depth investigation, but as is I'm going to close this as "by design" given its likely some microarchitectural specific quirk and not something related to the S.Numerics implementation

**Closed by tannergooding** 2024-08-12 17:39 UTC
Labels: area-System.Numerics, tenet-performance, needs-further-triage
