### ISSUE TITLE
System.Text.Json.JsonSerializer.Deserialize crashes when parsing large string using Blazor

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#41604] opened 2020-08-28 17:27 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1163083/systemtextjsonjsonserializerdeserialize-crashes-wh.html)._

---
[severity:Other] [regression] [worked-in:somewhere before 16.7.1]
Using Blazor/Wasm (3.2.0) and trying to parse a large json-string (135123600 chars) loaded from a file on my local windows machine, System.Text.Json.JsonSerializer.Deserialize crashes with the following internal exception (or similar, varies somewhat from run to run):

>Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: 'r' is an invalid start of a property name. Expected a '"'. Path: $[4888].ID | LineNumber: 63547 | BytePositionInLine: 0.
System.Text.Json.JsonException: 'r' is an invalid start of a property name. Expected a '"'. Path: $[4888].ID | LineNumber: 63547 | BytePositionInLine: 0. ---> System.Text.Json.JsonReaderException: 'r' is an invalid start of a property name. Expected a '"'. LineNumber: 63547 | BytePositionInLine: 0.
  at System.Text.Json.ThrowHelper.ThrowJsonReaderException (System.Text.Json.Utf8JsonReader& json, System.Text.Json.ExceptionResource resource, System.Byte nextByte, System.ReadOnlySpan`1[T] bytes) <0x8575f78 + 0x00020> in <filename unknown>:0 
  at System.Text.Json.Utf8JsonReader.ConsumeNextToken (System.Byte marker) <0x285e1d8 + 0x00264> in <filename unknown>:0 
  at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback (System.Byte marker) <0x285dfa8 + 0x0003a> in <filename unknown>:0 
  at System.Text.Json.Utf8JsonReader.ReadSingleSegment () <0x2851dd8 + 0x001de> in <filename unknown>:0 
  at System.Text.Json.Utf8JsonReader.Read () <0x2851960 + 0x0000e> in <filename unknown>:0 
  at System.Text.Json.JsonSerializer.ReadCore (System.Text.Json.JsonSerializerOptions options, System.Text.Json.Utf8JsonReader& reader, System.Text.Json.ReadStack& readStack) <0x28799e0 + 0x00060> in <filename unknown>:0 

Line number of the file  and position varies where it fails /(and therefore what is expected (number, string or property name).

The string contains a list of objects like:
>[
  {
    "ID": 0,
    "DateTime": "2018-08-09T08:57:34",
    "SiteWrapper": null,
    "SiteWrapperID": 1,
    "Lev": [
      40.3,
      0,
      78.9,
      65.6,
      55.5
    ]
  },
  {
    "ID": 0,
    "DateTime": "2018-08-09T08:57:35",
    "SiteWrapper": null,
    "SiteWrapperID": 1,
    "Lev": [
      70.4,
      72.1,
      71.2,
      0,
      64.5
    ]
  },

and so on. (all in all 604621 instances). 
(so far tested on Chrome 84.0.4147.135 and Microsoft Edge 44.18362.449.0)

---
#### Feedback Bot on 8/27/2020, 01:09 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by layomia** [comment] 2020-09-01 17:18
@erikthysell are you able to share a small repro app (sanitized if necessary) that highlights the issue? This would include all types being (de)serialized, any custom converters, and the JSON payload being passed to the serializer.

**Comment by erikthysell** [comment] 2020-09-02 18:43
Sure..
Here is a zip with the test data
[Testdata-2018-08-09-15.zip](https://github.com/dotnet/runtime/files/5164143/Testdata-2018-08-09-15.zip)
And here is a test solution/project - it needs the [Tewr Blazor FileReader](https://www.nuget.org/packages/Tewr.Blazor.FileReader/)

[BlazorTesting.zip](https://github.com/dotnet/runtime/files/5164150/BlazorTesting.zip)


I hope that is all that is needed...
Thanks for all the good you guys do!!

**Comment by erikthysell** [comment] 2020-09-03 06:15
I can confirm that it happens using .NET 5.0 preview 8 also. But it **seems** to be working a lot faster and reaches higher row numbers before it throws an error.

**Comment by layomia** [comment] 2020-09-03 17:12
@erikthysell thanks a lot. I'll take a look.

**Comment by ericstj** [comment] 2020-09-08 16:23
Just grabbed this data file and checked it out.  The offending double array looks like this:
```
"Lev": [
      77.2,
      66.5,
      64.6,
      76,
      70.9
    ]
```

Looks fine to me.  This isn't the first occurrence of a double without a decimal point in the file.  @layomia were you able to repro?  @erikthysell did this only repro in blazor?  When it repros is it always on the same position in the JSON?

**Comment by erikthysell** [comment] 2020-09-08 17:11
@ericstj : I have only tried with blazor wasm (client side) core 3.1 and .net 5 preview 8, chrome 85ish and edge 44. Always different position, sometimes  the Lev array othertimes other properties.

**Comment by layomia** [comment] 2020-09-09 08:02
I was able to repro this with in a blazor wasm app as described by @erikthysell and also in a test CI run (https://github.com/dotnet/runtime/pull/42004/) where the scenario fails for blazor wasm and Mono interpreter builds. The issue doesn't repro in a plain console app (CoreCLR JIT).

Trying to root-cause this now. The JSON payload, while very large, is fine and shouldn't cause exceptions to be thrown here. Might be an error with the [IndexOfQuoteOrAnyControlOrBackSlash](https://github.com/dotnet/runtime/blob/650f28f2c841c44b0a247e18a9f983c8619286dc/src/libraries/System.Text.Json/src/System/Text/Json/Reader/JsonReaderHelper.cs#L68) method, similar to the issue in https://github.com/dotnet/runtime/issues/41582#issuecomment-686534763.

fwiw, the deserialization appeared to work as expected when I refactored the repro code slightly to use the [`JsonSerializer.DeserializeAsync<T>`](https://docs.microsoft.com/dotnet/api/system.text.json.jsonserializer.deserializeasync?view=netcore-3.1#System_Text_Json_JsonSerializer_DeserializeAsync__1_System_IO_Stream_System_Text_Json_JsonSerializerOptions_System_Threading_CancellationToken_) overload instead of `Deserialize<T>`.

**Comment by steveharter** [comment] 2020-09-09 16:56
@layomia in order to help determine interpreter issue vs. `IndexOfQuoteOrAnyControlOrBackSlash` issue, running the repro on CoreCLR with `Vector.IsHardwareAccelerated == false` may help. This can be done by modifying the source of `IndexOfQuoteOrAnyControlOrBackSlash` or by running with environment variable `COMPlus_EnableHWIntrinsic=0`. If it fails on CoreCLR, then it's an issue in `IndexOfQuoteOrAnyControlOrBackSlash`.

FWIW for performance, this method was one that was considered for intrinsifying in the interpreter or re-write in C# for mono but that never happened. See https://github.com/dotnet/runtime/pull/41097, https://github.com/dotnet/runtime/pull/40705 and  https://github.com/dotnet/runtime/pull/39733.

**Comment by erikthysell** [comment] 2020-09-10 06:11
@layomia  thanks for the tip about the async version!

**Comment by layomia** [comment] 2020-09-10 19:39
@steveharter thanks! I ran the tests with `COMPlus_EnableHWIntrinsic=0` on CoreCLR and verified that there's no issue, `IndexOfQuoteOrAnyControlOrBackSlash` doesn't seem to be the issue for now. Which reach out offline to discuss further.

**Comment by steveharter** [comment] 2020-09-15 16:37
Based on additional testing by @layomia by using a simple implementation of IndexOfQuoteOrAnyControlOrBackSlash, this is now considered an issue in the mono\wasm area and not STJ.

Async may be working because it allocates a lot less memory than the non-async version. The async mode starts with a 16K buffer an will re-use that for all JSON until there is a property value that is too large to fit in the remaining buffer, then it will double the buffer, etc. In any case, a 110MB payload will not allocate anywhere near 110MB in async mode unless the 110MB is a single property value...

**Comment by SamMonoRT** [comment] 2020-09-18 19:50
@lewing @marek-safar - possibly RC candidate

**Comment by lewing** [comment] 2020-09-18 22:45
@SamMonoRT agreed

**Comment by BrzVlad** [comment] 2020-09-21 11:00
This doesn't look related to Json or the runtime, therefore not a release blocker. It seems to be an issue on the JS interop layer in a third party library. Submitted bug https://github.com/Tewr/BlazorFileReader/issues/161.

**Comment by CoffeeFlux** [comment] 2020-09-21 15:47
I believe this was fixed by https://github.com/dotnet/runtime/pull/42486, which should be backported soon. Can you validate that fix if you have the repro handy?

**Comment by BrzVlad** [comment] 2020-09-21 17:01
@CoffeeFlux it was not fixed

**Comment by CoffeeFlux** [comment] 2020-09-21 17:11
Gotcha. If so, we probably should close the issue or move it off 5.0.

**Comment by lewing** [comment] 2020-09-23 16:41
This was an issue in the library not the runtime and discussion has moved to Tewr/BlazorFileReader#161.  Closing.

**Closed by lewing** 2020-09-23 16:41 UTC
Labels: arch-wasm, area-VM-meta-mono, bug, tenet-reliability
