### ISSUE TITLE
Remote debugging doesn't work: VS2019 -> linux-arm (Attach failed with error 0x80131c4f)

### ISSUE THREAD

**Issue by XXXBold** [dotnet/runtime#44941] opened 2020-11-19 13:24 UTC
### Description
I'm not able to perform remote debugging on a Linux target from a Windows 10 host. This error occurs both on .NET Core 3.1 and 5.0. 
I'm always getting a message box saying: "Unable to attach to CoreCLR. Unknown Error: 0x80131c4f" when trying to launch the application from VS on the host (using a launch.json file, see below).
The process itself on the target seems to start as intended, and VS stays within the debug mode until I stop it manually, which also terminates the process on the target, but for some reasen attaching doesn't work.
![htop-vsdbg](https://user-images.githubusercontent.com/30773753/99674098-df403780-2a75-11eb-87fc-f1bac7e089bc.PNG)

I followed this guide to set up all the related stuff: https://github.com/Microsoft/MIEngine/wiki/Offroad-Debugging-of-.NET-Core-on-Linux---OSX-from-Visual-Studio#linux-computer

Dotnet is installed (manually) on /home/root/dotnet-sdk, and PATH + DOTNET_ROOT is set in the environment aswell.
vsdbg is installed on /home/root/vsdbg

For testing, I'm using a simple Hello World VB.NET program:
```
Imports System

Module Program
    Sub Main(args As String())
        While 1
            Console.WriteLine("Hello World!")
            Task.Delay(2000).Wait()
        End While
    End Sub
End Module
```
To create the approriate files, the "publish" functionality is used within VS:
![vs-dotnet-publish](https://user-images.githubusercontent.com/30773753/99674663-a81e5600-2a76-11eb-80fd-a24273c096e0.PNG)

These files are then distributed using `pscp ./* root@xx.xx.xx.xx:/home/root/ConsoleApp2`
```
ConsoleApp2               | 75 kB |  75.7 kB/s | ETA: 00:00:00 | 100%
ConsoleApp2.deps.json     | 0 kB |   0.5 kB/s | ETA: 00:00:00 | 100%
ConsoleApp2.dll           | 4 kB |   4.0 kB/s | ETA: 00:00:00 | 100%
ConsoleApp2.pdb           | 9 kB |   9.4 kB/s | ETA: 00:00:00 | 100%
ConsoleApp2.runtimeconfig | 0 kB |   0.2 kB/s | ETA: 00:00:00 | 100%
ConsoleApp2.runtimeconfig | 0 kB |   0.2 kB/s | ETA: 00:00:00 | 100%
```

I'm able to run the application directly from the CLI on the target using `dotnet ConsoleApp2.dll` without issues.

### Configuration
I'm using the Visual Studio 2019 and a custom launch.json file for remote debugging.
.NET (core) versions: 3.1.404 and 5.0.100 tested
OS: Host: Windows 10 Pro, Target: Linux ARM (Yocto based BSP from Toradex for the Colibri T30 (v2.8): https://developer.toradex.com/software/linux/linux-software#2-bsp-28)
Custom launch.json, started from command window with `DebugAdapterHost.Launch /LaunchJson:launch.json /ConfigurationName:RL`
File:
```
{
  "__comment": "Run in VS2019 terminal using DebugAdapterHost.Launch /LaunchJson:<path>",
  "version": "0.2.0",
  "adapter": "plink.exe",
  "adapterArgs": "root@xx.xx.xx.xx -batch -T /home/root/vsdbg/vsdbg --interpreter=vscode",
  "configurations": [
    {
      "name": "RL",
      "type": "coreclr",
      "request": "launch",
      "cwd": "~/ConsoleApp2",
      "program": "~/dotnet-sdk/dotnet",
      "args": "ConsoleApp2.dll",
      "engineLogging": true,
    },
  ]
}
```

### Regression?
Unknown, I only tested the two Runtimes listed above.

### Other information
Currently, no workarounds known.

Debug Adapter Log:
```
 1> DebugAdapterHost version: 16.8.40922.1 commit:6ac6030cbe2c515a73b952feec2d243d418d0915
 1> State: Unset => Initializing
 1> Sending VS event: IDebugEngineCreateEvent2 (fe5b734c-759d-4e59-ab04-f103343bdd06)
 1> Sending VS event: IDebugProgramCreateEvent2 (96cd11ee-ecd4-4e89-957e-b5d496fc4139)
 1> Starting 'plink.exe' with arguments 'root@xx.xx.xx.xx -batch -T /home/root/vsdbg/vsdbg --interpreter=vscode'
 1> WARNING: 'Language' not specified in engine registration!
 1> WARNING: 'LanguageId' not specified in engine registration!
 1> [DebugAdapter] --> C (initialize-1): {"type":"request","command":"initialize","arguments":{"pathFormat":"path","clientID":"visualstudio","clientName":"Visual Studio","adapterID":"coreclr","locale":"en-US","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsRunInTerminalRequest":true,"supportsMemoryReferences":true,"supportsProgressReporting":true,"SupportsMessageBox":true,"supportsHandshakeRequest":true,"supportsVsAdditionalBreakpointBinds":true,"supportsHitCountsChange":true,"supportsVsCustomMessages":true},"seq":1}
 1> WARNING: Request 'initialize-1' has not received a response within 1000 ms!
 1> [DebugAdapter] <--   R (initialize-1) [2339 ms]: {"type":"response","request_seq":1,"success":true,"command":"initialize","body":{"supportsConfigurationDoneRequest":true,"supportsFunctionBreakpoints":true,"supportsConditionalBreakpoints":true,"supportsHitConditionalBreakpoints":true,"supportsEvaluateForHovers":true,"exceptionBreakpointFilters":[{"filter":"all","label":"All Exceptions","default":false},{"filter":"user-unhandled","label":"User-Unhandled Exceptions","default":true}],"supportsSetVariable":true,"supportsGotoTargetsRequest":true,"supportsModulesRequest":true,"additionalModuleColumns":[{"attributeName":"vsLoadAddress","label":"Load Address","type":"string"},{"attributeName":"vsPreferredLoadAddress","label":"Preferred Load Address","type":"string"},{"attributeName":"vsModuleSize","label":"Module Size","type":"number"},{"attributeName":"vsLoadOrder","label":"Order","type":"number"},{"attributeName":"vsTimestampUTC","label":"Timestamp","type":"unixTimestampUTC"},{"attributeName":"vsIs64Bit","label":"64-bit","type":"boolean"},{"attributeName":"vsAppDomain","label":"AppDomain","type":"string"},{"attributeName":"vsAppDomainId","label":"AppDomainId","type":"number"}],"supportedChecksumAlgorithms":["MD5","SHA1","SHA256"],"supportsExceptionOptions":true,"supportsValueFormattingOptions":true,"supportsExceptionInfoRequest":true,"supportTerminateDebuggee":true,"supportsSetExpression":true,"supportsReadMemoryRequest":true,"supportsCancelRequest":true,"supportsExceptionConditions":true,"supportsLoadSymbolsRequest":true,"supportsModuleSymbolSearchLog":true,"supportsDebuggerProperties":true,"supportsSetSymbolOptions":true,"supportsHitBreakpointIds":true,"supportsVsIndividualBreakpointOperations":true,"supportsSetHitCount":true,"supportsVsCustomMessages":true,"supportsEvaluationOptions":true,"supportsExceptionStackTrace":true,"supportsObjectId":true},"seq":0}
 1> Sending VS event: IDebugEngineMetricsUpdatedEvent166 (45b79d58-0620-410f-8f39-c7c8c155e36c)
 1> [DebugAdapter] --> C (launch-2): {"type":"request","command":"launch","arguments":{"name":"RL","type":"coreclr","request":"launch","cwd":"~/ConsoleApp2","program":"~/dotnet-sdk/dotnet","args":"ConsoleApp2.dll","engineLogging":true},"seq":2}
 1> [DebugAdapter] <--   C (handshake-1): {"type":"request","command":"handshake","arguments":{"value":"tlypae87ScyXvfCe1B5dcAq6IJCHK/hVQ6fYtlyF/VU="},"seq":1}
 1> [DebugAdapter] --> R (handshake-1): {"type":"response","request_seq":1,"success":true,"command":"handshake","body":{"signature":"7354/8opc0BAQNFSIdJo8pty2xTDXyvEknTFXYowBAkHSY="},"seq":3}
 1> [DebugAdapter] <--   E (output): {"type":"event","event":"output","body":{"category":"console","output":"-------------------------------------------------------------------\nYou may only use the Microsoft .NET Core Debugger (vsdbg) with\nVisual Studio Code, Visual Studio or Visual Studio for Mac software\nto help you develop and test your applications.\n-------------------------------------------------------------------\n","severity":"ok"},"seq":2}
 1> Sending VS event: IDebugMessageEvent2 (3bdb28cf-dbd2-4d24-af03-01072b67eb9e)
 1> [DebugAdapter] <--   R (launch-2) [21 ms]: {"type":"response","request_seq":2,"success":true,"command":"launch","seq":3}
 1> State: Initializing => Running
 1> [DebugAdapter] <--   E (initialized): {"type":"event","event":"initialized","body":{},"seq":4}
 1> [DebugAdapter] --> C (setDebuggerProperty-4): {"type":"request","command":"setDebuggerProperty","arguments":{"AllowOutOfProcessSymbols":1},"seq":4}
 1> [DebugAdapter] --> C (setDebuggerProperty-5): {"type":"request","command":"setDebuggerProperty","arguments":{"DisableJITOptimization":0},"seq":5}
 1> [DebugAdapter] --> C (setDebuggerProperty-6): {"type":"request","command":"setDebuggerProperty","arguments":{"EnableFastEvaluate":1},"seq":6}
 1> [DebugAdapter] --> C (setDebuggerProperty-7): {"type":"request","command":"setDebuggerProperty","arguments":{"InterpreterOptions":1},"seq":7}
 1> [DebugAdapter] --> C (setDebuggerProperty-8): {"type":"request","command":"setDebuggerProperty","arguments":{"JustMyCodeStepping":1},"seq":8}
 1> [DebugAdapter] --> C (setDebuggerProperty-9): {"type":"request","command":"setDebuggerProperty","arguments":{"StopOnExceptionCrossingManagedBoundary":0},"seq":9}
 1> [DebugAdapter] --> C (setDebuggerProperty-10): {"type":"request","command":"setDebuggerProperty","arguments":{"WarnIfNoUserCodeOnLaunch":1},"seq":10}
 1> [DebugAdapter] --> C (setDebuggerProperty-11): {"type":"request","command":"setDebuggerProperty","arguments":{"EnableStepFiltering":true},"seq":11}
 1> [DebugAdapter] --> C (setSymbolOptions-12): {"type":"request","command":"setSymbolOptions","arguments":{"symbolOptions":{"cachePath":"","moduleFilter":{"mode":"loadAllButExcluded","excludedModules":[""]}}},"seq":12}
 1> [DebugAdapter] <--   R (setDebuggerProperty-4) [9 ms]: {"type":"response","request_seq":4,"success":true,"command":"setDebuggerProperty","body":{},"seq":5}
 1> [DebugAdapter] --> C (setFunctionBreakpoints-13): {"type":"request","command":"setFunctionBreakpoints","arguments":{"breakpoints":[]},"seq":13}
 1> Sending VS event: IDebugMessagableProgramReadyEvent167 (68bdc978-c107-46e1-80ad-29eb7af9472d)
 1> [DebugAdapter] <--   R (setDebuggerProperty-5) [11 ms]: {"type":"response","request_seq":5,"success":true,"command":"setDebuggerProperty","body":{},"seq":6}
 1> [DebugAdapter] <--   R (setDebuggerProperty-6) [11 ms]: {"type":"response","request_seq":6,"success":true,"command":"setDebuggerProperty","body":{},"seq":7}
 1> [DebugAdapter] <--   R (setDebuggerProperty-7) [11 ms]: {"type":"response","request_seq":7,"success":true,"command":"setDebuggerProperty","body":{},"seq":8}
 1> [DebugAdapter] <--   R (setDebuggerProperty-8) [11 ms]: {"type":"response","request_seq":8,"success":true,"command":"setDebuggerProperty","body":{},"seq":9}
 1> [DebugAdapter] <--   R (setDebuggerProperty-9) [11 ms]: {"type":"response","request_seq":9,"success":true,"command":"setDebuggerProperty","body":{},"seq":10}
 1> [DebugAdapter] <--   R (setDebuggerProperty-10) [11 ms]: {"type":"response","request_seq":10,"success":true,"command":"setDebuggerProperty","body":{},"seq":11}
 1> [DebugAdapter] <--   R (setDebuggerProperty-11) [11 ms]: {"type":"response","request_seq":11,"success":true,"command":"setDebuggerProperty","body":{},"seq":12}
 1> [DebugAdapter] <--   R (setSymbolOptions-12) [445 ms]: {"type":"response","request_seq":12,"success":true,"command":"setSymbolOptions","seq":13}
 1> [DebugAdapter] <--   R (setFunctionBreakpoints-13) [438 ms]: {"type":"response","request_seq":13,"success":true,"command":"setFunctionBreakpoints","body":{"breakpoints":[]},"seq":14}
 1> [DebugAdapter] --> C (setExceptionBreakpoints-14): {"type":"request","command":"setExceptionBreakpoints","arguments":{"filters":[],"exceptionOptions":[]},"seq":14}
 1> [DebugAdapter] <--   R (setExceptionBreakpoints-14) [7 ms]: {"type":"response","request_seq":14,"success":true,"command":"setExceptionBreakpoints","seq":15}
 1> [DebugAdapter] --> C (configurationDone-15): {"type":"request","command":"configurationDone","arguments":{},"seq":15}
 1> [DebugAdapter] <--   E (output): {"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/ProcessCreate","data":{"VS.Diagnostics.Debugger.vsdbg.Distribution.Version":"","VS.Diagnostics.Debugger.vsdbg.Distribution.Name":"e05d318","VS.Diagnostics.Debugger.vsdbg.OSFamily":"Linux","VS.Diagnostics.Debugger.vsdbg.Version":"16.8.11013.1 commit:4b0f186e434a6a8e833baeddc7bd2fad8dd08f41"}},"seq":16}
 1> [DebugAdapter] <--   E (telemetryDetails): {"type":"event","event":"telemetryDetails","body":{"telemetryEventName":"vs/diagnostics/debugger/process/context","telemetryProperties":{"VS.Diagnostics.Debugger.AD7Process.Architecture":"ARM"}},"seq":17}
 1> Sending VS event: IDebugTelemetryDetailsEvent150 (8f2652b2-cd3c-4aed-a946-a3db6f379412)
 1> [DebugAdapter] <--   E (process): {"type":"event","event":"process","body":{"name":"~/dotnet-sdk/dotnet","systemProcessId":510,"startMethod":"launch","pointerSize":32},"seq":18}
 1> Sending VS event: IDebugProcessInfoUpdatedEvent158 (96c242fc-f584-4c3e-8fed-384d3d13ef36)
 1> [DebugAdapter] <--   E (output): {"type":"event","event":"output","body":{"category":"telemetry","output":"VS/Diagnostics/Debugger/vsdbg/Launch","data":{"VS.Diagnostics.Debugger.vsdbg.AdapterId":"coreclr","VS.Diagnostics.Debugger.vsdbg.Launch.Duration":520,"VS.Diagnostics.Debugger.vsdbg.VisualizerFileUsed":false,"VS.Diagnostics.Debugger.vsdbg.TargetType":"Live","VS.Diagnostics.Debugger.vsdbg.Distribution.Version":"","VS.Diagnostics.Debugger.vsdbg.Distribution.Name":"e05d318","VS.Diagnostics.Debugger.vsdbg.OSFamily":"Linux","VS.Diagnostics.Debugger.vsdbg.SourceFileMappings":0,"VS.Diagnostics.Debugger.vsdbg.Version":"16.8.11013.1 commit:4b0f186e434a6a8e833baeddc7bd2fad8dd08f41"}},"seq":19}
 1> [DebugAdapter] <--   R (configurationDone-15) [67 ms]: {"type":"response","request_seq":15,"success":true,"command":"configurationDone","seq":20}
 1> Sending VS event: IDebugLoadCompleteEvent2 (b1844850-1349-45d4-9f12-495212f5eb0b)
 1> [DebugAdapter] <--   E (output): {"type":"event","event":"output","body":{"category":"messageBox","output":"Unable to attach to CoreCLR. Unknown Error: 0x80131c4f","severity":"error"},"seq":21}
 1> Sending VS event: IDebugMessageEvent2 (3bdb28cf-dbd2-4d24-af03-01072b67eb9e)
```

**Comment by tommcdon** [comment] 2020-11-20 18:23
@mikem8361 @hoyosjs This is an CORDBG_E_MISSING_DEBUGGER_EXPORTS issue

**Comment by hoyosjs** [comment] 2020-11-23 21:14
Closing as dupe of #44745

**Closed by hoyosjs** 2020-11-23 21:14 UTC
Labels: arch-arm32, area-Diagnostics-coreclr, bug, os-linux

**Comment by XXXBold** [comment] 2020-11-23 21:18
Are you sure this is the same issue? #44745 states that the problem only occurs in .NET 5.0, but works on 3.1. However, I've got the issue on both versions.
