### ISSUE TITLE
IAsyncEnumerable - ICorProfilerCallback::JITCompilationStarted not firing when await foreach is used

### ISSUE THREAD

**Issue by holc-tkomp** [dotnet/runtime#37504] opened 2020-06-05 19:05 UTC
https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/icorprofilercallback-jitcompilationstarted-method

## Use case / intro
When adding instrumentation for [Asynchronous streams](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#asynchronous-streams) to our profiler, I stumbled on quite an issue.

Our profiler utilizes `JITCompilationStarted` callback in order to process and instrument used/executed methods. Instrumentation is done mostly by modifying the IL body of the method.

## Description
After general instrumentation of `IAsyncEnumerable` methods (marked by `[AsyncIteratorStateMachine]`), I've noticed that something's still not right. I was surprised that `JITCompilationStarted` was not always called for `IAsyncEnumerable` methods, but at this point I had no clue why have this happened, I only knew that disabling inlining (using `COR_PRF_DISABLE_INLINING` flag) was solving this.

After some more time, and thanks to some more sample applications, I learned that **it was combination of `Optimize code` option, inlining and usage of `await foreach`**, that was causing this. If any of the condition weren't met, the `JITCompilationStarted` was magically called again.

It appears to work the same for .NET Core 3.1, 2.1 and .NET Framework 4.8 (haven't tested more).

### Example
Create .NET Core 3.1 Console App and use code below.

Turning on `Optimize code` in project settings (or just switching to Release configuration) and commenting-out `await GetFirstValue();` will cause the `JITCompilationStarted` event not being called.

Turning off `Optimize code`, or disabling JIT inlining, will make `JITCompilationStarted` fire.

Calling `await GetFirstValue()` will also show up that `JITCompilationStarted` event fired, but this have only effect on the `GetFirstValue` (`UseForEach`/`UseForEachEquivalent` methods body will be unaffected by this).

<details><summary>Application code</summary>

```c#
class Program
{
    static async Task Main(string[] args)
    {
        await UseForEach();
        await UseForEachEquivalent();
        await GetFirstValue(); // Commenting this out, will result in JITCompilationStarted not being called, when optimization and inlining is on

        Console.WriteLine("Press Enter to quit...");
        Console.ReadLine();
    }

    static async Task UseForEach()
    {
        Console.WriteLine("UseForEach: ");
        await foreach (var value in GetSomeValuesAsync())
        {
            Console.WriteLine(value);
        }
    }

    static async Task UseForEachEquivalent()
    {
        Console.WriteLine("UseManualEnumeration: ");
        var enumerator = GetSomeValuesAsync().GetAsyncEnumerator();
        while (await enumerator.MoveNextAsync())
        {
            Console.WriteLine(enumerator.Current);
        }
    }

    static async Task GetFirstValue()
    {
        Console.WriteLine("GetFirstValue: ");
        await using var enumerator = GetSomeValuesAsync().GetAsyncEnumerator();
        await enumerator.MoveNextAsync();
        var value = enumerator.Current;
        Console.WriteLine(value);
    }

    static async IAsyncEnumerable<int> GetSomeValuesAsync()
    {
        for (var i = 0; i < 5; i++)
        {
            await Task.Delay(100);
            yield return i;
        }
    }
}
```

</details>

<details><summary>Callbacks called (filtered to meaningful entries, only CompilationStarted and Inlining)</summary>

```
Optimization, inlining: enabled, WITHOUT .GetFirstValue() being called
    JITCompilationStarted: AwaitForEachIssue.Program+<UseForEach>d__1.MoveNext()
        JITInlining: AwaitForEachIssue.Program.GetSomeValuesAsync
    JITCompilationStarted: AwaitForEachIssue.Program+<UseForEachEquivalent>d__2.MoveNext()
        JITInlining: AwaitForEachIssue.Program.GetSomeValuesAsync
    // JITCompilationStarted was never triggered for GetSomeValuesAsync - this is core of the issue

Optimization, inlining: enabled, WITH .GetFirstValue() being called
    JITCompilationStarted: AwaitForEachIssue.Program+<UseForEach>d__1.MoveNext()
        JITInlining: AwaitForEachIssue.Program.GetSomeValuesAsync
    JITCompilationStarted: AwaitForEachIssue.Program+<UseForEachEquivalent>d__2.MoveNext()
        JITInlining: AwaitForEachIssue.Program.GetSomeValuesAsync
    JITCompilationStarted: AwaitForEachIssue.Program.GetFirstValue()
    JITCompilationStarted: AwaitForEachIssue.Program.GetSomeValuesAsync() // Note: This will only affect IL in GetFirstValue method, as it appears that raw GetSomeValuesAsync was already inlined into UseForEach and UseForEachEquivalent before this event was triggered

No optimization AND/OR inlining: disabled
    JITCompilationStarted: AwaitForEachIssue.Program.UseForEach()
    JITCompilationStarted: AwaitForEachIssue.Program.UseManualEnumeration()
    JITCompilationStarted: AwaitForEachIssue.Program.GetFirstValue()
    JITCompilationStarted: AwaitForEachIssue.Program.GetSomeValuesAsync() // JITCompilationStarted was fired as expected
```

</details>

### Current behavior
`JITCompilatonStarted` is not called for `IAsyncEnumerable` methods, that were inlined into methods using them via `await foreach` (or something that compiles to similar IL).

### Expected behavior
`JITCompilationStarted` being always called for `IAsyncEnumerable` methods, before their code is inlined into some other method.

Or at least some workaround, that'll let use modify IL of `IAsyncEnumerable` method, before it's being inlined.

## Configuration

OS: Windows 10 x64
VS version: 16.4.2

Event mask:
```
COR_PRF_MONITOR_ENTERLEAVE 
 | COR_PRF_MONITOR_THREADS 
 | COR_PRF_USE_PROFILE_IMAGES
 | COR_PRF_MONITOR_CACHE_SEARCHES
 | COR_PRF_MONITOR_EXCEPTIONS 
 | COR_PRF_MONITOR_CODE_TRANSITIONS 
 | COR_PRF_MONITOR_JIT_COMPILATION
 | COR_PRF_MONITOR_ASSEMBLY_LOADS
 | COR_PRF_MONITOR_MODULE_LOADS
 | COR_PRF_DISABLE_TRANSPARENCY_CHECKS_UNDER_FULL_TRUST

 | COR_PRF_DISABLE_INLINING // configurable
```

## Regression?
Appears to work like this with apps targetting:
 - .NET Core 3.1
 - .NET Core 2.1 (+`Microsoft.Bcl.AsyncInterfaces 1.1.1`)
 - .NET Framework 4.8 (+`Microsoft.Bcl.AsyncInterfaces 1.1.1`)
(haven't tested more)

## Other information
If you require any more information, let me know.

**Comment by hoyosjs** [comment] 2020-06-05 19:56
cc @davmason

**Comment by davmason** [comment] 2020-06-05 20:12
Hi @holc-tkomp,

That is expected behavior. You will only receive JITCompilationStarted callbacks for methods which are jitted. For inlined methods you will get a JITInlining callback but not a JITCompilationStartedCallback. You can set *pfShouldInline to false in JITInlining if you want to prevent the method in question from being inlined.

Or you can globally disable inlining as you mention with COR_PRF_DISABLE_INLINING, but most people find that to be an unacceptable performance tradeoff.

**Comment by tommcdon** [comment] 2020-07-27 19:19
Closing since this looks like expected behavior

**Closed by tommcdon** 2020-07-27 19:19 UTC
Labels: area-Diagnostics-coreclr, customer assistance
