### ISSUE TITLE
Microsoft.Extensions.Http.Polly 5.0.0 broke AddHttpClient - configureClient not called

### ISSUE THREAD

**Issue by cmeeren** [dotnet/runtime#45035] opened 2020-11-19 11:37 UTC
After updating from 3.1.10 to 5.0.0, the `configureClient` parameter of `AddHttpClient` is no longer called. In particular, it is the overload that accepts `string` and `Action<HttpClient>` I have tried. I have not tested others. Reverting to 3.1.10 fixes the issue.

The relevant code (F#):

```f#
type Startup(config: IConfiguration) =

  member __.ConfigureServices(services: IServiceCollection) : unit =
    services
      .AddHttpClient(HttpClientNames.chkbox, fun client -> ... )
```

Hopefully this is trivial to reproduce. Let me know if not.

### Additional context

Output of `dotnet --info`:

```
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.404 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by CarnaViire** [comment] 2020-11-23 15:51
@cmeeren Unfortunately I wasn't able to reproduce the issue. Could you please provide a minimal repro?

**Comment by cmeeren** [comment] 2020-11-23 19:02
Here's a repro:

[Test.zip](https://github.com/dotnet/runtime/files/5585188/Test.zip)

@BrennanConroy was right in that Polly was a red herring. If you target `net5.0` (as the repro is), the bug is there. If you change the target to `netcoreapp3.1`, it works fine.

The relevant code:

```f#
open System
open System.Net.Http
open Microsoft.AspNetCore.Builder
open Microsoft.AspNetCore.Hosting
open Microsoft.Extensions.DependencyInjection
open Microsoft.Extensions.Hosting


type Startup() =

  member _.ConfigureServices(services: IServiceCollection) : unit =
    services.AddHttpClient("test", fun client -> client.BaseAddress <- Uri("https://example.com"))
    |> ignore


  member _.Configure(app: IApplicationBuilder) : unit =
    let factory = app.ApplicationServices.GetService<IHttpClientFactory>()
    let client = factory.CreateClient("test")
    Console.WriteLine(
      "\nCLIENT BASE ADDRESS = "
      + if isNull client.BaseAddress then "NULL" else client.BaseAddress.ToString()
      + "\n"
    )


[<EntryPoint>]
let main args =
  Host
    .CreateDefaultBuilder(args)
    .ConfigureWebHostDefaults(fun builder ->
       builder.UseStartup<Startup>()|> ignore)
    .Build()
    .Run()
  0
```

Expected output (and actual output with `netcoreapp3.1`):

```
CLIENT BASE ADDRESS = https://example.com/
```

Actual output (with `net5.0`):

```
CLIENT BASE ADDRESS = NULL
```

**Comment by CarnaViire** [comment] 2020-11-23 22:39
Thank you @cmeeren! It turns out the issue happens only with F#.

The problem here is that the wrong overload of `AddHttpClient` is called for some reason. The one that you expected to be called (and the one that C# calls without problems) is 
```C#
AddHttpClient(this IServiceCollection services, string name, Action<HttpClient> configureClient)
``` 
([link](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.httpclientfactoryservicecollectionextensions.addhttpclient?view=dotnet-plat-ext-5.0#Microsoft_Extensions_DependencyInjection_HttpClientFactoryServiceCollectionExtensions_AddHttpClient_Microsoft_Extensions_DependencyInjection_IServiceCollection_System_String_System_Action_System_Net_Http_HttpClient__))

but the one that gets actually called from F# is 
```C#
AddHttpClient<TClient,TImplementation>(this IServiceCollection services, string name, Func<HttpClient,TImplementation> factory)
```
 ([link](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.httpclientfactoryservicecollectionextensions.addhttpclient?view=dotnet-plat-ext-5.0#Microsoft_Extensions_DependencyInjection_HttpClientFactoryServiceCollectionExtensions_AddHttpClient__2_Microsoft_Extensions_DependencyInjection_IServiceCollection_System_String_System_Func_System_Net_Http_HttpClient___1__))

where both `TClient` and `TImplementation` are the `unit` type ([link](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/unit-type)). The result of the wrong method being called is that `HttpClient` is registered on the name, but the action is not treated as `HttpClient` configuration but as an instance factory for a typed client and therefore is not called when `HttpClient` is created.

The latter `AddHttpClient` method was added in 5.0, that's why it doesn't fail on 3.1.

It seems that F# treats `Action<T>` as `Func<T,unit>`, but it still should be able to tell between two overloads. We will investigate this further.

Meanwhile, you may use the following workaround
```F#
services.AddHttpClient("test")
        .ConfigureHttpClient(fun client -> client.BaseAddress <- Uri("https://example.com"))
```
Please let me know if the workaround worked for you.

**Comment by cmeeren** [comment] 2020-11-24 06:38
Thank you for looking into this! I can confirm that the workaround works.

**Comment by CarnaViire** [comment] 2020-11-24 21:15
Hey @eiriktsarpalis my team suggested that you could take a look at this, because you know F# well 😃 Could you please help us to understand what is happening?

**Comment by halter73** [comment] 2020-11-25 02:41
Another workaround is to a named argument for the AddHttpClient configuration callback 

```f#
  member _.ConfigureServices(services: IServiceCollection) : unit =
    services.AddHttpClient("test", configureClient = fun client -> client.BaseAddress <- Uri("https://example.com"))
    |> ignore
```

This works because the overload it was using names it's callback `factory` not `configureClient`. It's too bad F# prefers the overload expecting `Func<T, TResult>` over the overload that takes `Action<T>` when the lambda signature is `T -> unit`. Maybe that can be fixed in the F# compiler.

**Comment by eiriktsarpalis** [comment] 2020-11-25 12:13
This is a known limitation of F# delegate interop. In order to support currying, F# native lambdas use [their own dedicated type](https://fsharp.github.io/fsharp-core-docs/reference/fsharp-core-fsharpfunc-2.html) but the compiler is generally capable of implicitly converting lambda _literals_ into delegate types, sometimes requiring a bit of help.

There are a few ways you can provide hints to the compiler so that the right overload is resolved (other than the one provided by @halter73):

In this case, constraining the type parameter arity should suffice:
```fsharp
  member _.ConfigureServices(services: IServiceCollection) : unit =
    services.AddHttpClient<_>("test", fun client -> client.BaseAddress <- Uri("https://example.com"))
    |> ignore
```
My personal preference however is to just explicitly define the delegate type, which should make your code more resilient against potential new overloads breaking your code in the future:
```fsharp
  member _.ConfigureServices(services: IServiceCollection) : unit =
    services.AddHttpClient("test", Action<HttpClient>(fun client -> client.BaseAddress <- Uri("https://example.com")))
    |> ignore
```

That being said, it feels to me that the compiler should have produced an error here. @cartermp thoughts?

**Comment by eiriktsarpalis** [comment] 2020-11-25 12:30
> It's too bad F# prefers the overload expecting Func<T, TResult> over the overload that takes Action<T> when the lambda signature is T -> unit. Maybe that can be fixed in the F# compiler.

I should note that `unit` is not a synonym for `void`. It is a singleton type and lambdas of type `'T -> unit` are represented as `FSharpFunc<'T, unit>`, equivalent to `Func<'T, unit>`.

**Comment by cartermp** [comment] 2020-11-25 17:19
Yep, I think @eiriktsarpalis's suggestion about being explicit w.r.t `Action`. vs. `Func` for the parameter in question is the best overall approach.

Note: I still consider myself a novice when it comes to the intricacies of overload resolution. As far as I can tell, F# will prefer the `Func` over the `Action` when both are present, which you can see in [this sharplab](https://sharplab.io/#v2:DYLgZgzgNAJiDUAfA9gBwKYDsAEBlAnhAC7oC2AsAFBVH4bYDCAFAJTYC8V232pZARugBO2APoA6ALJMAhiGwBBAMZEAlskwAeVZiIA+Nu2ysuPPqUEiJ0sPIBiAV0xLtuqNier9h4y1PcqYHQibCUORhNKJSkmMCcxbABaPV8WIA===). Ordering doesn't matter. If you remove the `Func` overload, the `Action` one is picked and it compiles just fine. Since this behavior holds for a simple F# snippet in purely F# code, I don't think there's much to do here. It's just the behavior of the compiler that likely goes back to at least F# 4.0 (I mention this only because this is the earliest point it was fully OSS; the pre-OSS history is something I just can't speak towards).

There's a general problem of F# type inference combined with overloads that is unavoidable - an added overload can be a breaking change for F# callers that rely on type inference - and this is what hit. This is an example of that. Using explicit types or named parameters can help.

**Comment by cartermp** [comment] 2020-11-25 17:20
Perhaps the `Action` vs. `Func` stuff is worth documenting as guidance in the F# docs. It's common enough to encounter methods that accept on or the other and it's always kind of a pain to interop with them.

**Comment by CarnaViire** [comment] 2020-11-26 13:37
@eiriktsarpalis @cartermp thanks a lot for the explanations!

@cartermp can you please link the F# docs issue once you file?
Closing this issue, as it is general F# limitation, not much we can do about it here.

**Closed by CarnaViire** 2020-11-26 13:37 UTC
Labels: area-Extensions-HttpClientFactory, untriaged
