### ISSUE TITLE
System.IO divergence between framework and core in Windows with colon ':' in file name.

### ISSUE THREAD

**Issue by ConnerPhillis** [dotnet/runtime#55052] opened 2021-07-02 01:54 UTC
### Description

Recently my team stumbled upon a difference in how .NET Framework and Core handles a colon (':') in the file name. 

The following code was used to test:

```CS
string s = "This is the contents of the file!";
File.WriteAllText("file: 12345.txt", s);
```

On .NET Framework `File.WriteAllText` throws `System.NotSupportedException: 'The given path's format is not supported.'`

On .NET Core `File.WriteAllText` does not throw and instead creates a file with the path correct all the way up to the colon containing no data. e.g. `file: 12345.txt` became `file` and was completely empty.

### Configuration

Tested on .NET Framework 4.7.2 and .NET 5 using the standard Visual Studio Console App. OS is Windows 10 Pro

Hopefully this is enough information for everyone to go off of. I know that .NET is cross platform now and the colon is valid in a file name in unix, so if this is desired behavior then I totally understand. Also, it seems that .NET core has been out long enough now to where a bug like this would have been reported already if it wasn't expected behavior.

That being said, this doesn't _feel_ like expected behavior, and I couldn't find a documented exception for this in the MS docs or any mention in previous GH issues, so I leave it to those smarter than me to tell me what is expected here.

**Comment by stephentoub** [comment] 2021-07-02 02:39
This is by design.

Windows and NTFS have the concept of Alternate Data Streams, and the syntax for specifying that is a colon after the filename; the text after the colon is then the name of the stream.  Try adding `Console.WriteLine(File.ReadAllText("file: 12345.txt"));` to the end of your repro, and you'll see that it prints out the text you previously wrote to that alternate data stream of that file.

.NET Framework blocked this.  In .NET Core we removed such blocks and let the operating system do with it what it can.

**Comment by adamsitnik** [comment] 2021-07-02 07:12
I've created following test:

```cs
using System;
using System.IO;
using Xunit;

namespace VariousTests
{
    public class FileTests
    {
        [Fact]
        public void ColonInTheFileName()
        {
            const string content = "This is the contents of the file!";
            const string path = "file: 12345.txt";

            File.WriteAllText(path, content);
            Assert.Equal(content, File.ReadAllText(path));
        }
    }
}
```

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48;net5.0;net6.0</TargetFrameworks>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.9.4" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="3.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```

It passes for .NET 5 and 6, but fails for 4.8:

```log
[xUnit.net 00:00:00.50]     VariousTests.FileTests.ColonInTheFileName [FAIL]
  Failed VariousTests.FileTests.ColonInTheFileName [10 ms]
  Error Message:
   System.NotSupportedException : The given path's format is not supported.
  Stack Trace:
     at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents)
   at VariousTests.FileTests.ColonInTheFileName() in C:\Users\adsitnik\source\repos\VariousTests\UnitTest1.cs:line 15

Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration:  - VariousTests.dll (net48)
Test run for C:\Users\adsitnik\source\repos\VariousTests\bin\Debug\net5.0\VariousTests.dll (.NETCoreApp,Version=v5.0)
Microsoft (R) Test Execution Command Line Tool Version 17.0.0-preview-20210331-03
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: < 1 ms - VariousTests.dll (net5.0)
Test run for C:\Users\adsitnik\source\repos\VariousTests\bin\Debug\net6.0\VariousTests.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.0.0-preview-20210331-03
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: < 1 ms - VariousTests.dll (net6.0)
```

Since this is be design and we don't plan to change that, I am going to close the issue.

**Closed by adamsitnik** 2021-07-02 07:12 UTC
Labels: area-System.IO
