### ISSUE TITLE
System.Drawing.Image.SetPropertyItem: Property is not supported

### ISSUE THREAD

**Issue by Socolin** [dotnet/runtime#46410] opened 2020-12-26 20:01 UTC
Hello,

SetPropertyItem throw an exception with the message `Property is not supported`

## Repro
```

        private static void Main()
        {
            var webClient = new WebClient();
            webClient.DownloadFile("https://raw.githubusercontent.com/ianare/exif-samples/master/jpg/Canon_40D.jpg", "1.jpg");
            var source = System.Drawing.Image.FromFile("1.jpg");

            var bitmap = new Bitmap(source.Width, source.Height);
            bitmap.SetResolution(source.HorizontalResolution, source.VerticalResolution);

            using (var graphics = Graphics.FromImage(bitmap))
            {
                var rectangle = new Rectangle(0, 0, source.Width, source.Height);
                graphics.DrawImage(source, rectangle, 0, 0, source.Width, source.Height, GraphicsUnit.Pixel, new ImageAttributes());
            }

            foreach (var propertyItem in source.PropertyItems)
                bitmap.SetPropertyItem(propertyItem);
        }
```

Stack
```
Unhandled exception. System.ArgumentException: Property is not supported.
   at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
   at System.Drawing.Image.SetPropertyItem(PropertyItem propitem)
   at ReproBugMicrosoft.Program2.Main() in /home/socolin/RiderProjects/ReproBugMicrosoft/ReproBugMicrosoft/Program2.cs:line 29

```

## Info
csproj
```

        private static void Main()
        {
            var webClient = new WebClient();
            webClient.DownloadFile("https://raw.githubusercontent.com/ianare/exif-samples/master/jpg/Canon_40D.jpg", "1.jpg");
            var source = System.Drawing.Image.FromFile("1.jpg");

            var bitmap = new Bitmap(source.Width, source.Height);
            bitmap.SetResolution(source.HorizontalResolution, source.VerticalResolution);

            using (var graphics = Graphics.FromImage(bitmap))
            {
                var rectangle = new Rectangle(0, 0, source.Width, source.Height);
                graphics.DrawImage(source, rectangle, 0, 0, source.Width, source.Height, GraphicsUnit.Pixel, new ImageAttributes());
            }

            foreach (var propertyItem in source.PropertyItems)
                bitmap.SetPropertyItem(propertyItem);
        }
```

dotnet info
```
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.101/

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  3.1.404 [/usr/share/dotnet/sdk]
  5.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

```

**Comment by safern** [comment] 2021-01-04 20:34
Thanks @Socolin. I was able to get a repro for this and I see that the issue is mainly coming from [libgdiplus](https://github.com/mono/libgdiplus). The problem is that the image format a bitmap is created when using the `Bitmap(int, int)` constructor, the image format is set to `MemoryBMP` [here](https://github.com/mono/libgdiplus/blob/9efff6a9ed1c3286362270b704dcdcf7a2670d54/src/bitmap.c#L869). 

Then when calling `SetPropertyItem`, `libgdiplus` doesn't consider that format as valid to set the property item for and it returns the invalid property error code: https://github.com/mono/libgdiplus/blob/9efff6a9ed1c3286362270b704dcdcf7a2670d54/src/image.c#L2110. 

I think this needs to be fixed in libgdiplus as we're just a wrapper around their library on `Unix`. 

However, you can workaround this issue by following other approaches, is there any reason why you're copying the image manually into a Bitmap and recreating it? You could instead use `Bitmap.FromFile` or save `source` into a `MemoryStream` and then use `Bitmap.FromStream`, that will return the right format for the image (`JPG`) in this case and will have the same property items.

**Closed** 2021-01-26 07:01 UTC
Labels: area-System.Drawing, needs author feedback, no recent activity
