### ISSUE TITLE
[API Proposal]: Improve lock() statement to be safer

### ISSUE THREAD

**Issue by AdamFrisby** [dotnet/runtime#55807] opened 2021-07-16 10:26 UTC
### Background and motivation

After yet another afternoon debugging an impossible-to-find deadlock triggered by a complicated recursive call to lock(), and no access to a proper debugger in the host environment; I would like to propose a slight addition to the lock() statement in C# to add a optional Timeout parameter. If the Timeout is exceeded, then it will throw a LockTimeoutException at the lock() statement.

LockTimeoutException does not yet exist, but suggested to differentiate from TimeoutException's called within the lock() scope.

### API Proposal

Add a secondary optional argument to the lock() statement which passes a TimeSpan. This is internally mapped to Monitor.TryEnter (instead of Monitor.Enter) with an exception being thrown in the case of failure.

```C#
     lock(foo) {
     
     }
```
Remains translated as:
```C#
     Monitor.Enter(foo);
     try {
     
     } 
     finally 
     {
        Monitor.Exit(foo);
     }
```     
However
```C#
     lock(foo, timespan) {
     
     }
```
Becomes:
```C#
     if(!Monitor.TryEnter(foo, timespan)) {
          throw new LockTimeoutException(foo);
     }
     try {
     
     } 
     finally 
     {
        Monitor.Exit(foo);
     }
```     

### API Usage

```C#
public class PoorlyWrittenClass {
     private object _lockTarget = new object();

     public void MyBadlyWrittenFunction()
     {
            try {
                lock(_lockTarget, TimeSpan.FromSeconds(1)) 
                {
                     MyBadlyWrittenFunction();
                }
            } 
            catch(LockTimeoutException) 
            {
               Console.WriteLine("you deadlocked.");
               throw;
            }
     }
}
```     

### Risks

Minimal risks as far as I can see - lock only allows for a single argument at present.

Potentially this makes some complicated code safer by allowing developers to inject sanity checks into locks to prevent infinite locks.

**Comment by AdamFrisby** [comment] 2021-07-16 10:28
(also sorry if I've placed this in the wrong location! Couldn't quite find the right spot from the picker on dotnet/core.)

**Comment by huoyaoyuan** [comment] 2021-07-16 10:28
This is a language proposal and belongs to https://github.com/dotnet/csharplang .
I recall there was discussion that lock statement was considered a mistake. I'm pretty sure that it probably won't get updated.

**Comment by teo-tsirpanis** [comment] 2021-07-16 10:30
Seems like a duplicate of https://github.com/dotnet/csharplang/discussions/1450.

**Comment by AdamFrisby** [comment] 2021-07-16 10:32
> Seems like a duplicate of [dotnet/csharplang#1450](https://github.com/dotnet/csharplang/discussions/1450).

Looks like it is. I'll go ahead and close this, and +1 the existing ticket. Thanks everyone.

**Closed** 2021-07-16 10:32 UTC
Labels: api-suggestion, untriaged
