### ISSUE TITLE
System.Text.Json.JsonSerializer.Deserialize add support for change the collection type 

### ISSUE THREAD

**Issue by martindybal** [dotnet/runtime#60453] opened 2021-10-15 02:46 UTC
### Background and motivation

Currently is not possible to deserialize an object with parametric constructor which has another type of collection than property of that object. -> `System.InvalidOperationException`. It's handy to have a `IEnumerable<T>` in constructor and `IList<T>` property for an example. 

```  
Each parameter in constructor 'Void .ctor(System.Collections.Generic.List`1[System.String])' on type 'Tests.NG_SOS.Infrastructure.JsonSerializationTests+TestRecord' must bind to an object property or field on deserialization. Each parameter name must match with a property or field on the object. The match can be case-insensitive.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ConstructorParameterIncompleteBinding(ConstructorInfo constructorInfo, Type parentType)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
```  

### API Proposal

```C#
        public record TestRecord
        {
            public IReadOnlyCollection<string> Values { get; init; }
            
            public TestRecord(List<string> values)
            {
                Values = values.AsReadOnly();
            }
        }
```     

### API Usage

```C#
var testObject = new TestRecord(new List<string> { "test value" });

var testObjectJson = System.Text.Json.JsonSerializer.Serialize(testObject);
var deserializedTestObject = System.Text.Json.JsonSerializer.Deserialize<TestRecord>(testObjectJson);
```

**Comment by eiriktsarpalis** [comment] 2021-10-15 11:33
Hi @martindybal. This is a duplicate of https://github.com/dotnet/runtime/issues/44428#issuecomment-767217872, feel free to contribute to the conversation in that other issue.

**Closed by eiriktsarpalis** 2021-10-15 11:33 UTC
Labels: area-System.Text.Json, untriaged
