### ISSUE TITLE
Tiered compilation fails to elide value type null check

### ISSUE THREAD

**Issue by sharwell** [dotnet/runtime#1713] opened 2020-01-14 15:53 UTC
`AsyncMethodBuilderCore` is implemented with the assumption that value type state machines will not be boxed for a runtime comparison with null:

https://github.com/dotnet/runtime/blob/f05dee0d58dd7aeb72347ff9075583196f032281/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs#L23-L26

This assumption does not hold for Tier 0 compilation. For a release build of Roslyn, execution of analyzers on Roslyn.sln produces 20% (70GB) of its total allocations boxing state machines for this null check.

**Comment by stephentoub** [comment] 2020-01-14 16:01
Related:
https://github.com/dotnet/coreclr/issues/14474
https://github.com/dotnet/coreclr/pull/22984
https://github.com/dotnet/coreclr/compare/master...AndyAyersMS:EnableBoxingOptsTier0

cc: @AndyAyersMS, @kouvel

**Comment by AndyAyersMS** [comment] 2020-01-14 16:23
Thanks -- is this with latest builds only or do you see it in 3.x too?

The fix for unexpected boxing at Tier0 in the 3.0 cycle was:
* selectively use `AggressiveOptimization` on some key methods (dotnet/#22984).
* enable some simple IL pattern based opts (dotnet/coreclr#23550).

I would have expected the IL pattern based opts to kick in here.

**Comment by sharwell** [comment] 2020-01-14 16:25
I was running the tool using the executable it generated during the build. Is there a way to see which version of dotnet it executes under the covers?

**Comment by sharwell** [comment] 2020-01-14 16:43
I re-ran this with the `dotnet` tool to get a specific version:

```
PS C:\dev\roslyn> dotnet --version
5.0.100-alpha1-015536
```

**Comment by AndyAyersMS** [comment] 2020-01-14 18:29
Yes, the boxing remains in Tier0, but gets optimized away in Tier1.

The unboxing opt at Tier0 gets blocked by the fact that we're boxing a byref arg and the byref might be null. At Tier1 we're able to handle this by leaving a residual null check behind.

Let me see how hard it is to extend the Tier0 version to cover this case.

**Comment by AndyAyersMS** [comment] 2020-01-14 18:54
I'm going to label this as codegen.

We've seen Tier0 code do a lot of allocation in a short time window -- but would be good to verify that the tiering logic is working as expected here. So @kouvel it is probably interesting to look at when/if tiering kicks in on this case.

**Comment by sharwell** [comment] 2020-01-14 20:22
💭 One option would be extracting this type of argument null check to a method where aggressive optimizations can be applied. This would allow the code to use the fast null check in Tier 0 without impacting the normal Tier0&rarr;Tier1 path.

**Comment by AndyAyersMS** [comment] 2020-01-14 20:26
This looks like it can be fairly easily fixed in the jit -- I'm evaluating a prospective fix now.

**Closed** 2020-01-15 18:35 UTC
Labels: area-CodeGen

**Comment by AndyAyersMS** [comment] 2020-03-05 04:20
@sharwell is this something you think we should try and fix in 3.1? I don't know if it would make the cut, but we could propose it and see.

**Comment by sharwell** [comment] 2020-03-05 07:17
@AndyAyers it really depends on whether users are expected to use tiered compilation. The numbers at the top are accurate for our scenario, but the issue is resolved by disabling the feature.

**Comment by AndyAyersMS** [comment] 2020-03-06 03:59
It's on by default, so yes we expect most users to use it. If I get this fixed in 3.x will you re-enable?

We do not want users to see regressions when moving from 2.x to 3.x, or decide the feature as a whole can't be trusted and decide to just turn it off forever.
