### ISSUE TITLE
[Bug] COM component using netstandard2.0 library with correct binding redirects cannot find dependency

### ISSUE THREAD

**Issue by m-redding** [dotnet/runtime#109417] opened 2024-10-31 15:01 UTC
This issue has been transferred from the Azure SDK for .NET repository, https://github.com/Azure/azure-sdk-for-net/issues/45734

The original author of the issue is @jwangga please include them for additional questions or replies.

@jwangga is trying to use Azure.Maps.Search in a COM component in order to use modern services within a VC++/MFC-based application. Registering the component works as expected. However, when the code is invoked by a COM client, an exception is thrown:

`"Could not load file or assembly
'System.Diagnostics.DiagnosticSource, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its
dependencies. The system cannot find the file specified."`

They were able to create a small reproduction using a .NET Framework library class project and use it in PowerShell, as described in the original issue.

Even though the Azure SDK for .NET packages target netstandard2.0, the libraries work with .NET framework as long as binding redirects are enabled (see a related issue: https://github.com/Azure/azure-sdk-for-net/issues/39798#issuecomment-1811064283).

In this case, this issue is reproducible even with the proper binding redirects turned on in the library. 

This issue is beyond the scope of the Azure SDK packages because they work as expected in .NET core and .NET framework applications. To me, this error seems specific to the COM client not properly preserving the binding redirects.

## Repr

Reproduction Steps
1) Create a .NET Framework library class project
2) Create a class and make it COM visible, as following:
    ```csharp
    namespace AzureMapWrapper
    {
        [ClassInterface(ClassInterfaceType.AutoDual)]
        [ComVisible(true)]
        public class AzureMapCOMWrapper
        {
            [ComVisible(true)]
            public ArrayList GeocodeSite(string address)
            {
                string subscriptionKey = <AzureMapsKey>;
                var credential = new AzureKeyCredential(subscriptionKey);
        
                var client = new MapsSearchClient(credential);
        
                Response<GeocodingResponse> result = client.GetGeocoding(address);
        
                ArrayList coordinates = new ArrayList();
                var rawResponse = result.GetRawResponse();
                int status = rawResponse.Status;
                if (result.Value.Features.Count > 0)
                {
                    coordinates.Add(result.Value.Features[0].Geometry.Coordinates[0]);
                    coordinates.Add(result.Value.Features[0].Geometry.Coordinates[1]);
                }
                return coordinates;
            }
        }
    }
    ```
3. Compile the project
4. Invoke the code in PowerShell like this:
    ```powershell
    $obj = New-Object -ComObject "AzureMapWrapper.AzureMapCOMWrapper"
    $result = $obj.GeocodeSite("641 Avenue of the Americas New York, NY 10011")
    ```

**Comment by AaronRobinsonMSFT** [comment] 2024-11-01 17:27
> This issue is beyond the scope of the Azure SDK packages because they work as expected in .NET core and .NET framework applications. To me, this error seems specific to the COM client not properly preserving the binding redirects.

@m-redding This not a .NET Core runtime issue. .NET Core doesn't have nor suppor binding redirects. The issue is the package has a .NET Core dependency that doesn't exist in .NET Framework. This is an issue with the related Azure dependencies and again, has nothing to do with COM.

> COM component in order to use modern services within a VC++/MFC-based application.

The MFC dimension is possibly an issue here, but isn't necessarily a .NET issue but is likely a needed configuration in the package to work in that sort of environment.

**Comment by m-redding** [comment] 2024-11-01 17:37
The package only targets netstandard2.0, shouldn't it be compatible with .NET Framework?

**Comment by hoyosjs** [comment] 2024-11-01 21:32
You can target netstandard2.0 - that just means what API surface is available. It tells you nothing about what provides such API. System.Diagnostics.DiagnosticSource has a ns2.0 compatible assembly with a 6.0.0.0 version in a nuget - your build is responsible for copying it to the output directory since .NET Framework doesn't ship with this DLL.

**Comment by AaronRobinsonMSFT** [comment] 2024-11-01 22:42
I think I see part of the issue here and it is entirely a .NET Framework configuration issue.

@jwangga This is mostly by-design. The activation of the CLR runtime and binding redirects at the assembly level are a bit of a confusion. There are two broad solutions here.

1) Create a `.config` file for the EXE and place the binding redirects in there.
2) Update the COM server to look next to it and load the correct assemblies.
    ```csharp
            static AzureMapCOMWrapper()
            {
                AppDomain.CurrentDomain.AssemblyResolve += CurrentDomain_AssemblyResolve;
            }
    
            private static Assembly CurrentDomain_AssemblyResolve(object sender, ResolveEventArgs args)
            {
                if (args.Name.StartsWith("System.Runtime.CompilerServices.Unsafe,")
                    || args.Name.StartsWith("System.Text.Json,")
                    || args.Name.StartsWith("System.Diagnostics.DiagnosticSource,"))
                {
                    string root = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
                    return Assembly.LoadFrom(Path.Combine(root, args.Name.Split(',')[0] + ".dll"));
                }
                return null;
            }
    ```

@ericstj Am I missing something with binding redirects for a .DLL on .NET Framework?

**Comment by jwangga** [comment] 2024-11-02 03:24
@AaronRobinsonMSFT It appears that the solution 1 does the trick. Adding the binding redirects in the .config file of the exe resolve the issue. It is a good timing as I was about to give up and take the route of calling Azure.Maps API directly.

Thanks to everyone who spent time looking into this issue.

**Comment by AaronRobinsonMSFT** [comment] 2024-11-02 04:23
@jwangga Glad you are unblocked. I'll close this issue. Please open and new one if you hit any further problems activating .NET implemented COM servers.

**Closed by AaronRobinsonMSFT** 2024-11-02 04:23 UTC
Labels: area-Interop-coreclr, untriaged
