### ISSUE TITLE
Create SLES 15, openSUSE Leap 15.2, Leap 16.0 dotnet-runtime-deps for libicu change

### ISSUE THREAD

**Issue by dagood** [dotnet/runtime#33672] opened 2020-03-17 14:54 UTC
In SLES 15 SP2, openSUSE Leap 15.2+, and openSUSE Leap 16.0+, the libicuXX_X package is taking this change to remove the `libicu` Provides clause:

https://build.opensuse.org/request/show/724939

This breaks the .NET Core package dependency. We need to create a new `dotnet-runtime-deps` package for each distro/version that depends directly on the version-specific libicu package (e.g. `libicu60_2`). In the future, we'll have to stay on top of this and create additional packages for each future Leap release whenever ICU is upgraded.

You can see that it's applied to the listed distros with these links:

https://build.opensuse.org/package/view_file/SUSE:SLE-15-SP2:GA/icu/icu.spec?expand=1
https://build.opensuse.org/package/view_file/openSUSE:Leap:15.2/icu/icu.spec?expand=1
(16.0 not yet linkable this way, but it's expected, since 16.0 will branch from Tumbleweed which has this change.)

---

This is an updated reopening of https://github.com/dotnet/runtime/issues/913 based on additional info provided in a report at https://github.com/dotnet/docs/issues/17470.

@NikolaMilosavljevic @leecow @nakarnam

**Comment by dagood** [comment] 2020-03-17 15:04
Alternative: we can give up on keeping the dependency minimal and instead depend on the `icu` package, which is built by the distro and takes a dependency on the current `libicu##_#` package. I looked into this a bit at https://github.com/dotnet/runtime/issues/3523#issuecomment-479082023.

**Comment by SchoolGuy** [comment] 2020-03-17 16:45
Another possibility would be (as Microsoft ist a SUSE Partner) that you open a ticket in the Jira/Bugzilla that you need this Provide in the specfile. This does not guarantee that you get that feature for that package but at least SUSE will evaluate this.

**Comment by leecow** [comment] 2020-03-18 17:24
@NikolaMilosavljevic - could you open the issue as @SchoolGuy suggests? I'd rather not start carrying around `icu` so without that attribute, we'll need to stay on top of deps updates.

/cc @nakarnam

**Comment by NikolaMilosavljevic** [comment] 2020-03-31 17:00
I've created an issue in OpenSUSE bugzilla: https://bugzilla.opensuse.org/show_bug.cgi?id=1167603

**Comment by SchoolGuy** [comment] 2020-04-01 07:39
@NikolaMilosavljevic That is not the right place to put this. If MS wants to have this backed up, you need to open a JIRA-Ticket at https://jira.suse.com

You have a dedicated contact inside your company which has access to that Jira and can open tickets there. The opensuse bugzilla is (especially in that category) just community driven and thus I guess noone will look at this. Escpecially as this is a P5 and thus not triaged.

I have contacted our internal TAM for you guys but did not have the time to write a follow up mail. I will write that now and the TAM will then (hopefully - as I can't promise anything) get in touch with you.

**Comment by SchoolGuy** [comment] 2020-04-01 07:40
CC @leecow

**Comment by SchoolGuy** [comment] 2020-04-01 07:40
Also opensuse 16 is a looooong time to go. You want this soner...

**Comment by NikolaMilosavljevic** [comment] 2020-04-09 16:17
Hi @SchoolGuy , I got a notification that a feature request in Jira was created - thank you!

It seems that Jira is internal - is there a way to get notifications of status changes or contribute to discussion?

**Comment by SchoolGuy** [comment] 2020-04-09 16:22
@NikolaMilosavljevic It is Internal and for Partners. There are MS Employees who have accounts since MS has partner status as far as I know. So you just need to find the person responsible for the communication with SUSE. They can ask for an account inside Jira for you. We do not grant anyone an account automatically since Atlassian and Plugin Vendors are billing by the number of accounts registered in our instance.

**Comment by NikolaMilosavljevic** [comment] 2020-06-25 16:39
SUSE has fixed this issue - we need to test it before closing.

**Comment by NikolaMilosavljevic** [comment] 2020-07-30 17:23
Confirmed that this is was fixed, using opensuse/leap:15.2 docker image.

OpenSUSE bug for reference: https://bugzilla.opensuse.org/show_bug.cgi?id=1167603

**Closed by NikolaMilosavljevic** 2020-07-30 17:23 UTC
Labels: area-Setup
