### ISSUE TITLE
HttpClient.DefaultRequestHeaders.Add('X-Request-Id', "...") difference between .NET Framework and .NET Core

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#53699] opened 2021-06-03 20:36 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/HttpClientDefaultRequestHeadersAddX-/1396615)._

---
Here's an example to reproduce the problem:

```C#
HttpClient client = new HttpClient();
var reuqestId = Guid.NewGuid();
client. DefaultRequestHeaders.Add("X-Request-Id", reuqestId.ToString());
```
In .NET Framework, the result of test is:

![Bb4265a7992364f4ab1533e53bb754885637538798104237677_1](https://user-images.githubusercontent.com/5169960/120708856-f1f9e700-c470-11eb-9d9b-a85ed9fe23f8.png)

But in .NET Core (including . NET 5), 'Id' becomes 'ID':

![B7a5a4c7bb9024fcdbb464a8c69409c7b637538800662076541_2](https://user-images.githubusercontent.com/5169960/120708853-f1615080-c470-11eb-9de7-33eb426a8b8b.png)

I want to know what makes the difference. Is there any way to prevent ‘id’ become 'ID'?

---
#### Feedback Bot on 4/13/2021, 03:51 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by MihaZupan** [comment] 2021-06-03 20:44
`X-Request-ID` is a known header internally, so we use a cached value of the name.
As per RFC, the name should be considered as case-insensitive.

Closing as a duplicate of #51583. That one is about `TryAddWithoutValidation` instead of `Add`, but the cause of the behaviour is the same.

**Closed by MihaZupan** 2021-06-03 20:44 UTC
Labels: area-System.Net, untriaged
