### ISSUE TITLE
Linq IntersectBy() just returns first item on same keySelector

### ISSUE THREAD

**Issue by MoienTajik** [dotnet/runtime#75066] opened 2022-09-04 07:42 UTC
### Description

Currently, Linq `IntersectBy()` works as follows:
```csharp
private static IEnumerable<TSource> IntersectByIterator<TSource, TKey>(IEnumerable<TSource> first, IEnumerable<TKey> second, Func<TSource, TKey> keySelector, IEqualityComparer<TKey>? comparer)
{
    var set = new HashSet<TKey>(second, comparer);

    foreach (TSource element in first)
    {
        if (set.Remove(keySelector(element)))
        {
            yield return element;
        }
    }
}
```

Due to the fact that [`IntersectBy()` currently uses Hashset's `Remove()` method](https://github.com/dotnet/runtime/blob/ebba1d4acb7abea5ba15e1f7f69d1d1311465d16/src/libraries/System.Linq/src/System/Linq/Intersect.cs#L95) instead of `Contains()` in its implementation, it just picks the **first** item found by `keySelector` and ignores the other possibly duplicate ones.

I couldn't find a test case for this scenario, and I am able to fix it if it is confirmed to be a bug.

### Reproduction Steps

```csharp
var people = new List<Person>
{
	new Person(1, "Moien"),
	new Person(2, "Moien")
};

var names = new List<string>
{
	"Moien"
};

var result = people.IntersectBy(names, person => person.Name);

public record Person(int Id, string Name);
```

### Expected behavior

`result` variable contains both items in the `people` collection:

```json
"result": [
	{ "Id": 1, "Name": "Moien" },
	{ "Id": 2, "Name": "Moien" }
]
```

### Actual behavior

`result` variable contains just the first item in the `people` collection:

```json
"result": [
	{ "Id": 1, "Name": "Moien" }
]
```

### Regression?

No

### Known Workarounds

Changing the `IntersectByIterator()` in this way will fix the issue:

```csharp
 private static IEnumerable<TSource> IntersectByIterator<TSource, TKey>(IEnumerable<TSource> first,
        IEnumerable<TKey> second,
        Func<TSource, TKey> keySelector,
        IEqualityComparer<TKey>? comparer)
{
    var set = new HashSet<TKey>(second, comparer);

    foreach (TSource element in first)
    {
        if (set.Contains(keySelector(element)))
        {
            yield return element;
        }
    }
}
```

### Configuration

.NET 6

**Comment by KeterSCP** [comment] 2022-09-04 10:41
`IntersectBy` is one of the [set operations](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/set-operations). Result of this method is a set, and by definition, set is something that does not contain duplicate elements. So for your case it correctly eliminated duplicates using provided `keySelector`

**Comment by MoienTajik** [comment] 2022-09-04 10:58
That makes sense, but I think it's better to have a proper method summary (description) for these cases.

I believe an extra argument could be added to these methods as well to accept/reject duplicate items. The current results are unexpected for developers IMO, and I realized this while debugging why many of my collection items are removed after applying `IntersectionBy()`.

**Comment by KeterSCP** [comment] 2022-09-04 11:18
> it's better to have a proper method summary (description) for these cases

If you think that method's summary or documentation is not fully described, you can make a PR with suggested changes.

> I believe an extra argument could be added to these methods as well to accept/reject duplicate items

I really doubt that libraries team will accept that ever, as these methods were designed to operate on sets and there should be no exceptions

**Comment by En3Tho** [comment] 2022-09-04 11:42
Fixing it like this is

 1) a breaking change

 2) I assume you want all intersections, meaning all items with given key if key is present in both set1 and set2. But your implementation will simply ignore items in set1 and return only those of set2. Also, set will be constructed in similar fashion - only first item will be inserted.

**Comment by krwq** [comment] 2022-09-06 10:25
@En3Tho sets are not supposed to have duplicate entries. I assume that what you actually want is something like:

```csharp
people.Where((person) => names.Contains(person.Name))
```

and not intersect. For efficiency might be a good idea to make names a HashSet.

Note that in your specific example set is identified by (id + name) but you ignore the id which causes weird behavior.

**Comment by krwq** [comment] 2022-09-06 10:31
If you feel like it you can send a patch to the documentation to mention that elements (https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.intersectby?view=net-6.0 and click edit button).

**Comment by En3Tho** [comment] 2022-09-06 11:11
I think @krwq meaned to tag @MoienTajik, not me. So retagging.

**Comment by krwq** [comment] 2022-09-06 11:18
You're right, I also edited😄

**Comment by MoienTajik** [comment] 2022-09-06 14:33
> @MoienTajik sets are not supposed to have duplicate entries. I assume that what you actually want is something like:
> 
> ```cs
> people.Where((person) => names.Contains(person.Name))
> ```
> 
> and not intersect. For efficiency might be a good idea to make names a HashSet.
> 
> Note that in your specific example set is identified by (id + name) but you ignore the id which causes weird behavior.

Thanks for your explanations.
It was exactly what I needed and tried that at first but with large collections it's too slow, so I decided to go with a `HashSet`, and I thought `IntersectBy()` would do the same thing (as it's using `HashSet` internally) as its code summary does not mention removing duplicate items, so I got weird results.

I will open a separate PR on the documentation about this and update the summaries.
I think having test cases for `IntersectBy()` for this scenario would be beneficial too.

**Comment by krwq** [comment] 2022-09-07 08:42
I'm closing this issue in that case since this is by design. Feel free to open new issue in the [api-docs repo](https://github.com/dotnet/dotnet-api-docs)

**Closed by krwq** 2022-09-07 08:42 UTC
Labels: area-System.Linq, untriaged
