### ISSUE TITLE
High base memory usage with .NET 7

### ISSUE THREAD

**Issue by jupjohn** [dotnet/runtime#75049] opened 2022-09-03 07:47 UTC
### Description

When running a simple "Hello World"-style console app in .NET 7 preview 7, initial memory usage is more than quadruple the same code built with .NET 6. 

I've create a minimal test console app in [this repository](https://github.com/jammehcow/net7-memory-usage) with a branch for the .NET 6 build and .NET 7 build. Running each in a Docker container (Dockerfile is in repo), the .NET 6 app appears to use `21`MB and the .NET 7 app uses `95`MB.

### Configuration

.NET Version: `7.0.100-preview.7.22377.5`
OS: `Arch Linux, kernel: 5.19.6-zen1-1-zen` (also replicated using the dotnet/runtime docker image)

Relevant hardware:
 - CPU: Ryzen 9 5900x
 - RAM: 32GB

### Regression?

Tested both .NET 6 and .NET 7 (preview 7). Will do some more testing to determine if another preview introduced this.

EDIT: tested, introduced in .NET 7 preview 3

**Comment by jammehcow** [comment] 2022-09-03 11:10
This issue appears to have been introduced in preview 3. Preview 22 exhibited the expected ~20MB consumption, whereas preview 3 is ~100MB

**Comment by jammehcow** [comment] 2022-09-05 02:19
Tested with a Windows 10 host, does not exhibit same behaviour. Seems to be a Linux-specific bug.

**Comment by mangod9** [comment] 2022-09-06 16:08
Hi @jammehcow, what is the available memory in the linux container, there has been some increases for 64gb+ available memory, but if you restrict it to something reasonable around 4/8gb do you still observe the increase?

**Comment by jammehcow** [comment] 2022-09-06 18:54
Running on my local machine it would've had access to all 32GB - container or native. I can try reducing it later today. 

Interested as to why this was assigned to the 8.0.0 milestone as it's a regression that will impact .NET 7

**Comment by MichalPetryka** [comment] 2022-09-06 18:58
Does disabling GC regions with `DOTNET_GCName=clrgc` remove the issue?

**Comment by mangod9** [comment] 2022-09-06 19:11
yeah please try with lower limits. Current thinking is that with reasonable limits you shouldnt be seeing a regression in 7.

**Comment by Maoni0** [comment] 2022-09-06 23:26
hi @jammehcow would you mind telling me how much value we are seeing for the GC heap usage? you could get it via sos's !eeheap -gc command (it should print out how much is committed for the whole GC heap in the last line).

**Comment by jammehcow** [comment] 2022-09-07 03:29
> Does disabling GC regions with `DOTNET_GCName=clrgc` remove the issue?

@MichalPetryka  tested, no it does not.

> yeah please try with lower limits. Current thinking is that with reasonable limits you shouldnt be seeing a regression in 7.

@mangod9 setting explicit limits on a docker container greatly reduces the base memory usage - even if the explicit value is equal to the system's available memory:
![image](https://user-images.githubusercontent.com/4962764/188781470-47a64c0b-45ad-4eb9-bc4e-27ba55171067.png)

That's only for a container though - running outside of a container has the same high usage.

> hi @jammehcow would you mind telling me how much value we are seeing for the GC heap usage? you could get it via sos's !eeheap -gc command (it should print out how much is committed for the whole GC heap in the last line).

@Maoni0 with an initial output of `104`MB, the committed heap size is 76201312 bytes.

**Comment by jammehcow** [comment] 2022-09-09 06:37
> @jammehcow thanks, what about on 6.0?

@Maoni0 With an initial output of `29`MB, committed bytes is `78265664`.

**Comment by Maoni0** [comment] 2022-09-09 06:53
ahh, so the numbers you quoted were working set, not committed bytes. 

I didn't notice that you were running in a container without memory limits. that explains what you are seeing. on linux our OS layer does some bookkeeping to keep track of pages it gives out. and that bookkeeping uses one byte for each page. since you don't have a memory limit, in .net 7.0 we reserve a 256GB range which takes 64mb for the linux OS layer to keep track of. this behavior does not exist on windows (ie, our windows OS layer does not do this bookkeeping). when you have a memory limit specified we only reserve twice as much the limit you specified.

**Comment by jammehcow** [comment] 2022-09-09 07:23
So just to clarify, this is intended behaviour for both:
 - Linux containers without set memory limits
 - non-containerised Linux hosts?

**Comment by Maoni0** [comment] 2022-09-09 07:30
correct. I was told that we are planning to get rid of this bookkeeping in our linux OS layer but not in this release.

**Comment by jammehcow** [comment] 2022-09-10 23:35
Cool. Is it okay to leave this issue open until it's fixed in whatever release that is? If anyone else runs into this there will at least be an open issue for them to find.

**Comment by mangod9** [comment] 2022-09-11 00:43
Yeah we will leave the issue open and resolve early in 8.

**Comment by abrasat** [comment] 2022-11-13 22:18
Does this mean that if writing a NET based c# application for a linux host it would be better to stay on NET 6 until NET 8 is released, especially if the linux host has limited hardware resources?
Is there any recommendation for the minimum memory necessary on an embedded linux host system, in view to run a NET 6 application?

**Comment by mangod9** [comment] 2022-11-14 04:32
You can explicitly set `DOTNET_GCHeapHardLimit` to something reasonable for your scenario. That would reduce the extra bookkeeping. We are also looking at porting a fix back to 7 servicing.

**Comment by abrasat** [comment] 2022-11-14 08:35
Thanks for the feedback. Is it possible to accurately estimate the runtime memory usage of a NET application, before installing it on the linux host system? For instance by running it in WSL 2?

**Comment by mangod9** [comment] 2022-11-18 03:02
memory usage will depend on the application behavior as might be expected. WSL2 should be very close to evaluating memory usage assuming it runs with the production load profile.

**Comment by abrasat** [comment] 2022-11-18 06:45
Thanks for the reply. I am aware that memory usage is application dependent, I just wanted to know an approximate estimation for a "regular" application. Probably a couple of threads: for instance a main loop reading cyclically some i-o/memory registers from the embedded system, once in a while a database access and also some tcp-ip communication. I am planning to test with WSL2, but I dont think I will be able to simulate the physical memeory access, the rest should be no problem. Could 1 GB for instance be enough, or maybe 2 GB? Could you eventually recommend some tools or APIs for the memory usage, cpu load, performance metrics ?

**Comment by ibruynin** [comment] 2022-11-29 12:47
> You can explicitly set `DOTNET_GCHeapHardLimit` to something reasonable for your scenario. That would reduce the extra bookkeeping. We are also looking at porting a fix back to 7 servicing. 

Is this a viable workaround for AKS as well? And that would result in hard limits per container/pod in k8s, or do I get it wrong?

**Comment by ibruynin** [comment] 2022-11-29 16:03
> > You can explicitly set `DOTNET_GCHeapHardLimit` to something reasonable for your scenario. That would reduce the extra bookkeeping. We are also looking at porting a fix back to 7 servicing. 
> 
> Is this a viable workaround for AKS as well? And that would result in hard limits per container/pod in k8s, or do I get it wrong?

Tried this in a helm chart and that seems to limit the memory consumption in k9s:

          resources:
            requests:
              memory: 50Mi
            limits:
              memory: 4096Mi # based on the specs of the vm in the node pool

**Comment by mangod9** [comment] 2022-11-29 16:05
Correct, the issue only occurs with unbounded memory configurations. If you limit using the environment variable or via docker or K8s memory limits it should reduce the 64mb overhead due to large reservation size.

**Comment by ibruynin** [comment] 2022-11-30 10:20
Is that reservation linear?
I mean 256 gb limit -> 64 mb reservation
Does that mean 16 gb limit -> 4 mb?

Thanks

**Comment by mangod9** [comment] 2022-11-30 21:26
yeah its proportional to the reservation size. We additional overhead is fixed in .NET 8 and we hope to port the fix to 7 in an upcoming release too.

**Comment by mattbdc** [comment] 2023-01-13 04:08
Can confirm restricting available memory via cgroups / docker or in our case at dokku level brings it back from 95mb to around ~20mb

**Comment by mattbdc** [comment] 2023-01-14 07:47
![image](https://user-images.githubusercontent.com/83773047/212461925-5fa8a23f-ea3f-48cd-9dcc-55744d4eb65e.png) Weirdly it does seem to creep up over 24hrs for no apparent reason - from <20mb to 35mb

It hasn't serve a single request either (no virtual host exposed yet)
![image](https://user-images.githubusercontent.com/83773047/212461972-ec63be2c-53a5-4c91-8682-9cd599a2593f.png)

**Comment by arnecornillie-gantner** [comment] 2023-02-16 13:12
Hi,

We are encountering the same issue. We have several microservices running on an AWS ECS cluster. We migrated some of them to .net7, and we are using the "mcr.microsoft.com/dotnet/aspnet:7.0" docker image.
We are using datadog as a monitoring tool & over there we see the following behavior when using .net 7.
![image](https://user-images.githubusercontent.com/84460326/219373883-5af091dd-e983-4ba0-a635-c836d7c2b976.png)

Looks like there is some kind of caching memory layer added in the .net7 runtime?

Thanks!

**Comment by mangod9** [comment] 2023-02-17 04:59
@arnecornillie-gantner, could you please clarify what the char is showing? Is it available (free) memory? This issue will cause an absolute 64mb working set increase for unbounded memory containers. If you have memory constraints configured for your container this is probably a different issue you are running into. Thx

**Comment by arnecornillie-gantner** [comment] 2023-02-17 08:50
Hi @mangod9 , thanks for the reply!

It sounds like another issue I think. I had a look together with a technical person of AWS itself & since .net7, the docker image is using more memory than .net6. When taking a deeper look, it looks like the "cgroup" is having some "cache" memory metrics. This was not the case in .net6 docker image.

In our datadog chart, the memory in use is shown. The blue part is the memory used by the service & the purple part is the caching memory. 

I thought maybe this is caused by the same issue. But I can be wrong.

Thanks!

**Comment by mangod9** [comment] 2023-04-11 19:18
The fix should be available in the latest 7.0.4 release. Could you please try it out?

**Comment by enclave-alistair** [comment] 2023-05-04 13:31
@mangod9; the issue seems to have been resolved in that 7.0.4 release; thanks.

**Comment by mangod9** [comment] 2023-05-04 16:29
Thanks closing this out to avoid other memory related issues being reported here. For other high memory cases or OOMs please open a separate issue. Thanks!

**Closed by mangod9** 2023-05-04 16:29 UTC
Labels: tenet-performance, area-PAL-coreclr
