### ISSUE TITLE
System.Text.Json source generator fails if [Required(ErrorMessage = "...")] attribute is present.

### ISSUE THREAD

**Issue by Kloizdena** [dotnet/runtime#62937] opened 2021-12-17 01:01 UTC
### Description

I tried to use the Json source generator with a class which has a [Required] attribute with an error message, but the generator succeeds only when the ErrorMessage is not specified. I tried it with other Validation attributes (StringLength, Range), and I got the same result.

### Reproduction Steps

Add the following two classes in a .NET 6.0 project, then try to build it.

```csharp
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

public class TestDto
{
    [Required(ErrorMessage = "asdf")]
    public string Name { get; set; }
}

[JsonSerializable(typeof(TestDto))]
public partial class Serializers : JsonSerializerContext
{

}

```

### Expected behavior

The source generator should generate the properties and the build should succeed.

### Actual behavior

The source generator and the build fails and I get an error in the Output window:

```
Build started...
1>------ Build started: Project: SystemTextJsonTest, Configuration: Debug Any CPU ------
1>CSC : warning CS8785: Generator 'JsonSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'InvalidOperationException' with message 'Sequence contains no elements'
1>D:\src\SystemTextJsonTest\SystemTextJsonTest\TestDto.cs(11,22,11,33): error CS0534: 'Serializers' does not implement inherited abstract member 'JsonSerializerContext.GetTypeInfo(Type)'
1>D:\src\SystemTextJsonTest\SystemTextJsonTest\TestDto.cs(11,22,11,33): error CS0534: 'Serializers' does not implement inherited abstract member 'JsonSerializerContext.GeneratedSerializerOptions.get'
1>Done building project "SystemTextJsonTest.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

### Known Workarounds

Remove the ErrorMessage, ErrorMessageResourceName and ErrorMessageResourceType properties from the validation attributes.

### Configuration

.NET 6.0.100
Microsoft Windows [Version 10.0.19043.1348]
x64

**Comment by layomia** [comment] 2021-12-20 22:36
Can repro. This bug can affect lots of users and a bug fix should be considered for 6.0.

**Comment by deeprobin** [comment] 2022-01-09 10:24
If it's just a small fix and I can more or less take that from your other PR, of course I can take that.
Is there anything to keep in mind for PRs on v6.0 other than choosing the right branch?

**Comment by deeprobin** [comment] 2022-01-09 10:35
Oh I see the bot has already created a backport PR.

**Comment by veertien** [comment] 2022-02-12 15:35
This issue did not surface for me until I used .NET SDK 6.0.2 (dotnet/core#7172).

sdk | setup | result
--|--|--
6.0.1 | JsonSerializerContext in project A, type to serialize with RequiredAttribute in project B | both projects compile without error
6.0.1 | JsonSerializerContext and type to serialize both in the same project | build error due to 'JsonSourceGenerator' failed to generate source
6.0.2 | JsonSerializerContext in project A, type to serialize with RequiredAttribute in project B | build error due to 'JsonSourceGenerator' failed to generate source
6.0.2 | JsonSerializerContext and type to serialize both in the same project | build error due to 'JsonSourceGenerator' failed to generate source

**Comment by JakeYallop** [comment] 2022-04-02 14:29
I've just ran into this issue as well (using the required attribute). For what its worth, I'm able to repro the issue in 6.0.1 as well as 6.0.2.

Easy repro here, switching to 6.0.1 of STJ still reproduces the issue. https://github.com/JakeYallop/JsonSerializerContextInvalidOperationExceptionRepro
```csharp
public class MyClass
{
    [Derived(BaseProperty = "")] //source generator does not compile
    //[Derived(DerivedProperty = "", BaseProperty = "")] //does not compile
    //[Derived] //compiles fine
    //[Derived(DerivedProperty = "")] //compiles fine
    public string Property { get; set; } = null!;
}

public abstract class BaseAttribute : Attribute
{
    public string BaseProperty { get; set; } = null!;
}

[AttributeUsage(AttributeTargets.All)]
public class DerivedAttribute : BaseAttribute
{
    public string DerivedProperty { get; set; } = null!;
}

[JsonSourceGenerationOptions]
[JsonSerializable(typeof(MyClass))]
public partial class JsonContext : JsonSerializerContext
{

}
```

As a workaround for the short term, I've added an explicit reference to version 7.0.0-preview.2.22152.2 in my .NET 6 project which includes the PR above (I usually just use the in-box version, rather than an explicit reference).

Will this fix make it into a 6.0.x version of the STJ package in future?

**Comment by eiriktsarpalis** [comment] 2022-07-19 12:57
Moving to .NET 8 milestone.

**Comment by JakeYallop** [comment] 2022-09-09 19:47
I'm not sure if this issue should still be open - it seems like this is fixed in .NET 7.0.

**Comment by eiriktsarpalis** [comment] 2022-09-12 18:25
@layomia According to https://github.com/dotnet/runtime/issues/62937#issuecomment-1037259847 this is a regression in servicing. Should we consider backporting #63837 to .NET 6?

**Comment by onionhammer** [comment] 2022-10-13 15:32
.net 7's new 'required' & init-only props are also unsupported;

i.e. `public required string Test { get; init; }`

Is there something tracking this I can subscribe to?

**Comment by eiriktsarpalis** [comment] 2022-10-13 15:38
Yes, see https://github.com/dotnet/runtime/issues/58770

**Comment by eiriktsarpalis** [comment] 2022-11-30 10:51
@veertien I checked this particular scenario using sdk version 6.0.101

sdk | setup | result
--|--|--
6.0.1 | JsonSerializerContext in project A, type to serialize with RequiredAttribute in project B | both projects compile without error

On my machine the compile error is reproducing with that configuration as well. I don't believe we're dealing with a servicing regression here, so I'm going to close this issue. .NET 6 impacted by this issue can try referencing the v7 [System.Text.Json NuGet package](https://www.nuget.org/packages/System.Text.Json) to incorporate the fix.

**Closed by eiriktsarpalis** 2022-11-30 10:51 UTC
Labels: bug, area-System.Text.Json

**Comment by xlievo** [comment] 2022-12-07 08:57
CS0534:
So far, it is still easy to reproduce this problem. Referencing [Business.SourceGenerator.Test](https://www.nuget.org/packages/Business.SourceGenerator.Test)
v7 [System.Text.Json NuGet package](https://www.nuget.org/packages/System.Text.Json) It didn't work!

**Comment by eiriktsarpalis** [comment] 2022-12-07 15:07
@xlievo please create a new issue containing a minimal reproduction. Thanks!
