### ISSUE TITLE
PlatformNotSupported after system updates (Ubuntu 22.04 LTS x64)

### ISSUE THREAD

**Issue by luanmm** [dotnet/runtime#75427] opened 2022-09-11 23:22 UTC
### Description

After system updates, something occurred and a project that was working in the same machine/environment (connecting to SQL Server) started giving an error:

System.PlatformNotSupportedException: Strings.PlatformNotSupported_DataSqlClient
   at Microsoft.Data.SqlClient.SqlConnectionStringBuilder..ctor(String connectionString)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.<>c.<get_IsMultipleActiveResultSetsEnabled>b__7_0(String cs)

The project has never set explicitly any runtime identifiers and everything worked great until now. It seems to be a problem identifying the correct platform/DLL (see the workaround).

### Reproduction Steps

It is complicated to give "a minimal example" because it depends on the platform.

I think it can be reproduced installing .NET 6 in Ubuntu 22.04 LTS, using `apt-get install dotnet6`, and running a simple project that connects to SQL Server.

### Expected behavior

Load the correct library based on the platform.

### Actual behavior

Not identifying the correct platform.

### Regression?

It seems to work on earlier versions in Ubuntu, but I couldn't identify how to test this (the error seems to be started after system updates).

### Known Workarounds

Running with `dotnet run --arch x64 --os linux` works.

### Configuration

$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.108
 Commit:    4e3a463d2b

Runtime Environment:
 OS Name:     pop
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/lib/dotnet/dotnet6-6.0.108/sdk/6.0.108/

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  6.0.108 [/usr/lib/dotnet/dotnet6-6.0.108/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.8 [/usr/lib/dotnet/dotnet6-6.0.108/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.8 [/usr/lib/dotnet/dotnet6-6.0.108/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

### Other information

Could not identify anything specific, but all this issues seems to be related:

https://github.com/dotnet/SqlClient/issues/1427
https://github.com/dotnet/SqlClient/issues/1423
https://github.com/dotnet/efcore/issues/28934
https://github.com/dotnet/efcore/issues/28786

As can be stated in the EF Core and SqlClient repos, people that knows the code states that it isn't a problem with the libraries (and I tend to agree, because it was working before without dependecies version changes).

**Comment by jvbsl** [comment] 2022-09-12 20:42
Did you try .Net 7 or .Net 5 respectively? Because I have a problem which could be the same:
https://github.com/jvbsl/DotnetDependencyProblem
Example for System.Drawing.Common, which throws PlatformNotSupportedException, as well as a Project using a modified SharpFont version of myself which needs to load a library from the runtimes folder dependent on platform which can't be loaded.

Basically these projects work fine with .Net 5 and .Net 7 but can't find the runtime dependencies using dotnet 6.

Workaround mentioned by @luanmm does work in my case as well. Additional workaround is to change the rid for the runtime library in deps.json to "linux-x64" explicitly("linux" does not work)

**Comment by luanmm** [comment] 2022-09-12 21:06
> Did you try .Net 7 or .Net 5 respectively?

Not really. The project I'm working on, when this happened, is using .NET 6 (that is the current LTS).

If I have some time to try these other versions in this project, I update here.

**Comment by teo-tsirpanis** [comment] 2022-09-12 21:08
@jvbsl [`System.Drawing.Common` is not supported on non-Windows](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only).

**Comment by jvbsl** [comment] 2022-09-12 21:12
Well yes and no. The problem has nothing to do with whether it is supported on non-windows or not, because it still works, it is even still meant to work on Linux in .Net 6
> "System.Drawing.EnableUnixSupport": true
further down in your URL (Which btw. currently does not change a thing, because the problem mentioned here is a different one)

And as I said, just an example(and it works with .Net 7 btw) and I also have an example using another library in there which demonstrates the exact same behaviour

**Comment by elinor-fung** [comment] 2023-01-20 19:17
Sorry for the late response here.

@luanmm @jvbsl could you collect and share a [host trace](https://learn.microsoft.com/dotnet/core/tools/dotnet-environment-variables#corehost_trace) of the failure?

**Comment by luanmm** [comment] 2023-01-20 21:36
Sorry, @elinor-fung, but I had to install .NET 7.0 and could not reproduce it anymore (but I may try to reproduce it in a later time reverting temporary to version 6.0).

Disclaimer: the current installation of .NET in my environment (the one that works) was done entire manually (downloading, extracting, setting env vars, etc).

I think the problem is related to .NET builds from the common installation sources (which I always used before the current one). The build that gave me this error was installed from "apt-get" sources (tested with Ubuntu and Microsoft repositories, with same resulting error).

**Comment by elinor-fung** [comment] 2023-01-20 22:04
> I think the problem is related to .NET builds from the common installation sources (which I always used before the current one).

Do you recall if you were on a clean (no .NET) machine? I know there was some stress with package mixups in .NET 6: https://github.com/dotnet/core/issues/7699

**Comment by luanmm** [comment] 2023-01-20 23:00
Yep, @elinor-fung. I think it can be considered "a clean machine".

I had already installed .NET 3.1 and 5.0 in the same machine before, but, when this platform errors occurred, I found this thread about conflicting packages. So I tried to "reset" all the configurations, delete all folders, env variables, etc. I tried to install from Microsoft packages (in Ubuntu this was the way till version 6.0) and directly from Ubuntu 22.04 official repositories (removing the Microsoft package configurations).

Because of this "resets" and different configuration setups, I don't think that this error was throwing for "historical reasons" and conflicts like this (but cannot be sure too).

**Comment by jvbsl** [comment] 2023-01-25 17:03
Well if I install dotnet 6 now it does work, no idea what is actually different. Beforehand I installed dotnet manually as well(Manjaro)
And I can't reproduce it in a docker with sdk 6.0.102, 6.0.202, 6.0.302, 6.0.403 (could not find 6.0.8 from there) from https://mcr.microsoft.com/en-us/product/dotnet/sdk/
Apart from that to me personally it isn't that relevant any more because I switched to .net 7 as well.

**Comment by elinor-fung** [comment] 2023-02-24 21:25
Thanks, all. I'm going to close this as it does not appear to be reproducing or blocking folks anymore. Please do report back / file an issue if you see this again.

**Closed by elinor-fung** 2023-02-24 21:25 UTC
Labels: area-Host, untriaged
