### ISSUE TITLE
Add direct support for structs when deserializing with System.Text.Json.Serialization

### ISSUE THREAD

**Issue by astrowalker** [dotnet/runtime#61264] opened 2021-11-05 20:14 UTC
Here is the relevant doc https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-5-0#deserialize-to-immutable-classes-and-structs

The solution described there is not 100% accurate. Given the type:

```
    public class FooBar
    {
        public int X { get; }
        public int Y { get; }

        public FooBar(int x,int y)
        {
            X = x;
            Y = y;
        }
    }

```

Serialization and deserialization works out of the box, which is always a good thing.

But if one switches this to struct it does not work, just because (I suspect) structs have always "secondary" constructor and it seems serializer is fooled by it.

Now,  [JsonConstructor] attribute helps here, but such cases are too trivial to use attribute for it. There is ton of basic types like Angles, Lengths, Points, and so on which now have to be (in theory) decorated just to serializer pick them up. Moreover decorating is often not possible, because those types can be located in 3rd party libraries.

So please add direct support (i.e. without decorating) to such basic cases. Given the fact the default constructor for struct cannot be customized, I would suggest that deserializer could forget about it for a second and check if all other conditions are OK, if they are, then deserialize the type via user constructor instead of default one.

**Comment by eiriktsarpalis** [comment] 2021-11-08 10:43
> just because (I suspect) structs have always "secondary" constructor and it seems serializer is fooled by it.

It's not "fooled" by it, this is by-design behavior. A struct such as 
```csharp
public struct FooBar
{
    public int X { get; }
    public int Y { get; }

    public FooBar(int x, int y)
    {
        X = x;
        Y = y;
    }
}
```
Is equivalent to writing the following class
```csharp
public class FooBar
{
    public int X { get; }
    public int Y { get; }

    public FooBar()
    {
    }

    public FooBar(int x, int y)
    {
        X = x;
        Y = y;
    }
}
```
As such the deserialization behavior is the same (has preference for the default constructor unless specified otherwise). Even if we did change the default behavior now this would likely be a breaking change. I would suggest a couple of workarounds:

1. As you suggested, apply the JsonConstructorAttribute to the desired constructor.
2. If working with readonly structs, consider using init-only properties instead of constructors.

One possible workaround in future releases might be to customize the constructor selection algorithm via #34456. Duplicate of #59309 and #59394.

**Closed by eiriktsarpalis** 2021-11-08 10:43 UTC
Labels: area-System.Text.Json, untriaged
