### ISSUE TITLE
`ref readonly` parameters of a generic type may get corrupted

### ISSUE THREAD

**Issue by Rekkonnect** [dotnet/runtime#107710] opened 2024-09-11 21:18 UTC
### Description

I have a method with two `ref readonly` parameters from which I extract two spans. When trying to operate on these spans, the second parameter's span does not behave as intended. This appears to be a JIT bug, incorrectly mixing the spans on which to operate.

### Reproduction Steps

SharpLab repro [here](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK4wD4AEBMBGAWACgsAGAAizwDoAZWARwG5izKaAldBKMAU2oBhAPZgADlAA2fZAGUZANygBjPgGcWJClWpcYPftQCS+mcLHzkS1RuLEYEfmrERV5ACrqeMAObUAUlAIAEKofhx8AGYREAAmwjCSAJ7UnmoItkSsOADMxADexOTFlDg4RSWFRCU15AoQyOQIXmrkALzkMHwA7h4AFrA+aRkAFACUmrUlwMLCkuRqqMo2rR3N6WrUAGLQklvCyBFiyMLjk1PsAJwji8vqahMVxQC+xK9ZJDml/YPDagVPShfGZzcg7KT7Q58Y6nMaAqoXOoNcjSSIIdqdHo/XwjADaeAAuo9qhd6o1kFAfH10R0ur13AMcbicHByDkiZpATUsAB2chHE5GcSSEawFFRBCssUUqmShYIVwAawgkkkwmU5GASWauJl1LofF8CD6HMB70BAHoLfy+GBhAo+OQAOTIKLkV1xBLJJ3kA7kZR9CC+R3uJrCbE+X0wch8IJ9GSsoOxJoDVrdKTzboHRX+g6u5QIZKArBfKgANk1s3mAuEQrEkgAPO4AHwjLklV2Rd18T2JJIecVo1md7u95IDvVy2QuGANrXNZuY7qhSKRGRwklTbrx10DkDkIwMwbw9vFMmDhDToMY1EIagAcT4CAAqjA1BA11eYGdT0jyZTqS/DFJwfJ9X3fT8Zx/TdalvagABFhFkUQn0ZHxoMRScvyEcwkncU46RXNdkGJRFeSXIiZGoeQGFQQ1VAAUVolURhAx8XzfD8+C/cZSJKd5zU+chYGaZBIlcR1DzQgEYKwAAWchEOQ/hjUGDCShiWIAHk+y/OdtT4Rd2PArieOJQSS1HeI+3IdAIMddI0ALCMRk0nTkj0+dDM1AyHnIfcpOPIgERKY4oHqZorK9fsRPIAB9aQjT6DEvM2WhDR8Y1zmKMKIsdD1rPHVBYri44oigAAPDF2IANRVOithOMA9OK/RW1S4liy+WL0qS9pFwSjKsrsWTSwUpSUNUnExnIfJyEEmpcogSLywHWr6r4RrRD0ltXJ7bTdJnfSFx89YN0RbcZBDfzbJgSAHB8PhYhPGCalDepJDojFYiiCBUEkBBstqVKcLEPDTgAWVtA4kghho1EDSQhA9ZoeJHEy12oABBNQm1ZLzWxHD66LGVk1CgAAvPhhEiEZ3DGBmge5Plib4IGFpKSy3MOoNju84zOMgoNxhezC3XPMrIkqiJiPox0OnRwWBBxmXRWjUrO0qvipiJ5EvIABU1qqFbdDHldx1q5QJ1i3Ul6WoiumBVG12pyKhu1kFh+HEeRntmm5jyoJHA2jdZQakpdgTiCAA) -- many thanks to @jnm2 for reducing the repro code from the code below:

Initial source of the bug [here](https://github.com/Rekkonnect/UmbraString/blob/5a10a2f290a81edc92854799d10600e0d181ab62/UmbraString/UmbraStringHelpers.cs#L20-L37)

### Expected behavior

The operations are executed successfully and the structs are not corrupted.

### Actual behavior

The structs are corrupted and the copy to the new buffer does not behave as expected.

### Known Workarounds

Do not use `ref readonly`, or do not use generics, as shown in the comments in the example repro

**Comment by jnm2** [comment] 2024-09-11 21:21
I would also point out that removing or reordering the DoSomething call affects this repro.

**Comment by JulieLeeMSFT** [comment] 2024-09-11 22:23
@AndyAyersMS, PTAL.

**Comment by AndyAyersMS** [comment] 2024-09-11 23:41
Looks like this is running vs 8.0.

**Comment by jkotas** [comment] 2024-09-12 03:26
This method does not do what you think that it does:
```csharp
    public static bool ReproImpl<T>(
        ref readonly T left, ref readonly T right, Span<byte> newBuffer)
        where T : IThing
    {
        var leftSpan = left.GetUnsafeSpan();
        var rightSpan = right.GetUnsafeSpan();
        left.DoSomething();
        rightSpan.CopyTo(newBuffer);
        return newBuffer.SequenceEqual(right.GetUnsafeSpan());
    }
}
```
`GetUnsafeSpan` and `DoSomething` are not a read-only methods. When non-readonly methods are called on readonly values, the C# compiler has to create a temporary local mutable copy per C# language spec. The code of this method is equivalent to:
```csharp
        T temp;
        temp = left;
        var leftSpan = temp.GetUnsafeSpan();
        temp = rigth;
        var rightSpan = temp.GetUnsafeSpan();
        temp = left;
        temp.DoSomething();
        rightSpan.CopyTo(newBuffer);
        return newBuffer.SequenceEqual(right.GetUnsafeSpan());
```
It explains why the Span are not equal. The rightSpan points into the temp value that gets reused by the DoSomething call.

The hidden copies inserted by the C# compiler for readonly values are hard to see, and when combined with unsafe refs create a dangerous mix. I would avoid mixing readonly and unsafe refs together.

**Comment by AndyAyersMS** [comment] 2024-09-12 17:12
Not a 9.0 issue at any rate.

**Comment by colejohnson66** [comment] 2024-09-13 14:13
So the issue is that the compiler can't tell that `Thing` is readonly (only the JIT can), so it makes defensive copies. This is unfortunate. Are there any built-in analyzers to flag these hidden copies?

**Comment by jkotas** [comment] 2024-09-13 15:00
There is community provided one at https://github.com/SergeyTeplyakov/ErrorProne.NET?tab=readme-ov-file#defensive-copy-analyzers . You can open suggestion to create a built-in one in https://github.com/dotnet/roslyn-analyzers repo.

**Comment by JulieLeeMSFT** [comment] 2024-09-13 19:00
@colejohnson66, closing this issue and we suggest you to open an issue in dotnet/roslyn-analyzers repo. Please feel free to open this issue again if you have further comments.

> There is community provided one at https://github.com/SergeyTeplyakov/ErrorProne.NET?tab=readme-ov-file#defensive-copy-analyzers . You can open suggestion to create a built-in one in https://github.com/dotnet/roslyn-analyzers repo.

**Closed by JulieLeeMSFT** 2024-09-13 19:00 UTC
Labels: question, area-CodeGen-coreclr
