### ISSUE TITLE
Performance regressions from #74665 and #74777

### ISSUE THREAD

**Issue by SingleAccretion** [dotnet/runtime#75157] opened 2022-09-06 19:33 UTC
- https://github.com/dotnet/runtime/pull/74665#issuecomment-1238400852
- https://github.com/dotnet/runtime/pull/74777#issuecomment-1238397104

These need to be investigated and fixed (this may prove challenging for the first set; the presumed source is a correctness fix).

category:performance
theme:benchmarks
skill-level:intermediate
cost:small
impact:small

**Comment by AndyAyersMS** [comment] 2023-07-31 20:54
Via the collation tool, only 5 of these are still more than 5% regressed. Four of those are bimodal or noisy tests.

Only `Quaternion.MultiplyByQuaternionBenchmark` on arm64 seems to be related, likely caused by #74665. Since that was a bug fix I'm going to close this as expected.

| Notes | Recent Score | Orig Score | arm64 ubuntu | arm64 windows | x64 ubuntu |  Benchmark |
| ---  | --: |--: | --: |  --: |  --: |  :-- |
| bimodal | 1.20 | 1.20 | | | [1.20 <br /> 1.20](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/PerfLabTests.LowLevelPerf.ClassVirtualMethod.html) |PerfLabTests.LowLevelPerf.ClassVirtualMethod |
| bimodal | 1.15 | 1.40 | | | [1.15 <br /> 1.40](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.Collections.CtorFromCollection%28Int32%29.SortedSet%28Size%3a%20512%29.html) |System.Collections.CtorFromCollection(Int32).SortedSet(Size: 512) |
| bimodal | 1.09 | 1.09 | | | [1.09 <br /> 1.09](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.Globalization.Tests.StringSearch.LastIndexOf_Word_NotFound%28Options%3a%20%28en-US%2c%20OrdinalIgnoreCase%2c%20False%29%29.html) |System.Globalization.Tests.StringSearch.LastIndexOf_Word_NotFound(Options: (en-US, OrdinalIgnoreCase, False)) |
| noisy | 1.07 | 1.08 | | | [1.07 <br /> 1.08](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.Tests.Perf_Char.Char_ToUpper%28c%3a%20%27%c4%b0%27%2c%20cultureName%3a%20en-US%29.html) |System.Tests.Perf_Char.Char_ToUpper(c: 'İ', cultureName: en-US) |
| | 1.04 | 1.09 | | | [1.04 <br /> 1.09](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.Collections.AddGivenSize%28String%29.ICollection%28Size%3a%20512%29.html) |System.Collections.AddGivenSize(String).ICollection(Size: 512) |
| | 1.03 | 1.18 | | | [1.03 <br /> 1.18](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.Collections.Tests.Perf_BitArray.BitArraySet%28Size%3a%20512%29.html) |System.Collections.Tests.Perf_BitArray.BitArraySet(Size: 512) |
| | 1.01 | 1.12 | | | [1.01 <br /> 1.12](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/BenchmarksGame.PiDigits_3.RunBench%28n%3a%203000%2c%20expected%3a%20%228649423196%5ct%3a3000%22%29.html) |BenchmarksGame.PiDigits_3.RunBench(n: 3000, expected: "8649423196\t:3000") |
| | 1.00 | 1.20 | | | [1.00 <br /> 1.20](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/PerfLabTests.LowLevelPerf.StructWithInterfaceInterfaceMethod.html) |PerfLabTests.LowLevelPerf.StructWithInterfaceInterfaceMethod |
| | 1.00 | 1.20 | | | [1.00 <br /> 1.20](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/PerfLabTests.LowLevelPerf.SealedClassInterfaceMethod.html) |PerfLabTests.LowLevelPerf.SealedClassInterfaceMethod |
| | 0.98 | 1.07 | | | [0.98 <br /> 1.07](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/Benchstone.BenchI.Array1.Test.html) |Benchstone.BenchI.Array1.Test |
| from #74665 (bug fix) | 0.98 | 3.03 | [1.98 <br /> 3.99](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_ubuntu%2020.04/System.Numerics.Tests.Perf_Quaternion.MultiplyByQuaternionBenchmark.html) | [1.82 <br /> 5.19](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_Windows%2010.0.25094/System.Numerics.Tests.Perf_Quaternion.MultiplyByQuaternionBenchmark.html) | [0.26 <br /> 1.34](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.Numerics.Tests.Perf_Quaternion.MultiplyByQuaternionBenchmark.html) |System.Numerics.Tests.Perf_Quaternion.MultiplyByQuaternionBenchmark |
| | 0.98 | 1.11 | | | [0.98 <br /> 1.11](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.Tests.Perf_HashCode.Add.html) |System.Tests.Perf_HashCode.Add |
| | 0.97 | 1.18 | | | [0.97 <br /> 1.18](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.Tests.Perf_String.Interpolation_MultipleArgs%28c%3a%20%271%27%2c%20s%3a%20%22Foo%22%29.html) |System.Tests.Perf_String.Interpolation_MultipleArgs(c: '1', s: "Foo") |
| | 0.95 | 1.06 | | | [0.95 <br /> 1.06](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.MathBenchmarks.Single.Log2.html) |System.MathBenchmarks.Single.Log2 |
| | 0.93 | 1.08 | | | [0.93 <br /> 1.08](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.Collections.CreateAddAndClear%28String%29.ICollection%28Size%3a%20512%29.html) |System.Collections.CreateAddAndClear(String).ICollection(Size: 512) |
| | 0.93 | 1.08 | | | [0.93 <br /> 1.08](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/Burgers.Test0.html) |Burgers.Test0 |
| | 0.93 | 1.38 | | | [0.93 <br /> 1.38](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.Buffers.Text.Tests.Utf8ParserTests.TryParseInt64%28value%3a%209223372036854775807%29.html) |System.Buffers.Text.Tests.Utf8ParserTests.TryParseInt64(value: 9223372036854775807) |
| | 0.92 | 1.14 | | | [0.92 <br /> 1.14](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.Collections.TryAddGiventSize%28Int32%29.Dictionary%28Count%3a%20512%29.html) |System.Collections.TryAddGiventSize(Int32).Dictionary(Count: 512) |
| | 0.92 | 1.36 | | | [0.92 <br /> 1.36](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.Buffers.Text.Tests.Utf8ParserTests.TryParseInt64%28value%3a%20-9223372036854775808%29.html) |System.Buffers.Text.Tests.Utf8ParserTests.TryParseInt64(value: -9223372036854775808) |
| | 0.92 | 1.05 | | | [0.92 <br /> 1.05](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.Collections.ContainsFalse%28String%29.Span%28Size%3a%20512%29.html) |System.Collections.ContainsFalse(String).Span(Size: 512) |
| | 0.89 | 1.06 | | | [0.89 <br /> 1.06](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.Collections.Sort%28IntClass%29.LinqOrderByExtension%28Size%3a%20512%29.html) |System.Collections.Sort(IntClass).LinqOrderByExtension(Size: 512) |
| | 0.84 | 1.11 | | | [0.84 <br /> 1.11](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.Linq.Tests.Perf_Enumerable.WhereFirst_LastElementMatches%28input%3a%20Array%29.html) |System.Linq.Tests.Perf_Enumerable.WhereFirst_LastElementMatches(input: Array) |
| | 0.83 | 1.08 | | | [0.83 <br /> 1.08](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.Collections.ContainsKeyFalse%28Int32%2c%20Int32%29.ImmutableDictionary%28Size%3a%20512%29.html) |System.Collections.ContainsKeyFalse(Int32, Int32).ImmutableDictionary(Size: 512) |
| | 0.83 | 1.09 | | | [0.83 <br /> 1.09](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/Benchstone.BenchI.Fib.Test.html) |Benchstone.BenchI.Fib.Test |
| | 0.78 | 1.12 | | | [0.78 <br /> 1.12](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.Linq.Tests.Perf_Enumerable.WhereAny_LastElementMatches%28input%3a%20Array%29.html) |System.Linq.Tests.Perf_Enumerable.WhereAny_LastElementMatches(input: Array) |
| | 0.67 | 1.13 | | | [0.67 <br /> 1.13](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.Linq.Tests.Perf_Enumerable.WhereSingle_LastElementMatches%28input%3a%20Array%29.html) |System.Linq.Tests.Perf_Enumerable.WhereSingle_LastElementMatches(input: Array) |
| | 0.64 | 1.07 | | | [0.64 <br /> 1.07](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.Text.RegularExpressions.Tests.Perf_Regex_Industry_Leipzig.Count%28Pattern%3a%20%22%28%3fi%29Tom%7cSawyer%7cHuckleberry%7cFinn%22%2c%20Options%3a%20NonBacktracking%29.html) |System.Text.RegularExpressions.Tests.Perf_Regex_Industry_Leipzig.Count(Pattern: "(?i)Tom|Sawyer|Huckleberry|Finn", Options: NonBacktracking) |
| | 0.63 | 1.13 | | | [0.63 <br /> 1.13](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.Collections.IterateForEach%28Int32%29.ConcurrentBag%28Size%3a%20512%29.html) |System.Collections.IterateForEach(Int32).ConcurrentBag(Size: 512) |
| | 0.53 | 1.07 | | | [0.53 <br /> 1.07](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.Collections.ContainsTrue%28String%29.LinkedList%28Size%3a%20512%29.html) |System.Collections.ContainsTrue(String).LinkedList(Size: 512) |
| | 0.51 | 1.06 | | | [0.51 <br /> 1.06](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.Numerics.Tests.Perf_VectorOf%28Byte%29.MultiplyOperatorBenchmark.html) |System.Numerics.Tests.Perf_VectorOf(Byte).MultiplyOperatorBenchmark |
| | 0.51 | 1.07 | | | [0.51 <br /> 1.07](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.Numerics.Tests.Perf_VectorOf%28SByte%29.MultiplyOperatorBenchmark.html) |System.Numerics.Tests.Perf_VectorOf(SByte).MultiplyOperatorBenchmark |
| | 0.41 | 1.06 | | | [0.41 <br /> 1.06](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.Linq.Tests.Perf_Enumerable.CastToSameType%28input%3a%20IEnumerable%29.html) |System.Linq.Tests.Perf_Enumerable.CastToSameType(input: IEnumerable) |
| | 0.38 | 1.08 | | | [0.38 <br /> 1.08](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.Linq.Tests.Perf_Enumerable.Where%28input%3a%20Array%29.html) |System.Linq.Tests.Perf_Enumerable.Where(input: Array) |
| | 0.34 | 1.08 | | | [0.34 <br /> 1.08](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.Linq.Tests.Perf_Enumerable.EmptyTakeSelectToArray.html) |System.Linq.Tests.Perf_Enumerable.EmptyTakeSelectToArray |
| | 0.26 | 1.08 | | | [0.26 <br /> 1.08](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.Numerics.Tests.Perf_Quaternion.MultiplyByQuaternionOperatorBenchmark.html) |System.Numerics.Tests.Perf_Quaternion.MultiplyByQuaternionOperatorBenchmark |
| | 0.26 | 1.35 | | [0.26 <br /> 1.35](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_Windows%2010.0.25094/System.Numerics.Tests.Perf_Quaternion.InverseBenchmark.html) | |System.Numerics.Tests.Perf_Quaternion.InverseBenchmark |
| | 0.25 | 1.08 | | | [0.25 <br /> 1.08](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.Numerics.Tests.Perf_Quaternion.ConcatenateBenchmark.html) |System.Numerics.Tests.Perf_Quaternion.ConcatenateBenchmark |
| | 0.21 | 1.19 | | | [0.21 <br /> 1.19](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.Collections.IterateForEach%28Int32%29.ImmutableQueue%28Size%3a%20512%29.html) |System.Collections.IterateForEach(Int32).ImmutableQueue(Size: 512) |

**Closed by AndyAyersMS** 2023-07-31 20:54 UTC
Labels: area-CodeGen-coreclr
