### ISSUE TITLE
Introduce Propagators API in DiagnosticSource package

### ISSUE THREAD

**Issue by cijothomas** [dotnet/runtime#46054] opened 2020-12-14 23:25 UTC
## Background and Motivation

`DiagnosticSource` package was enhanced in 5.0 to achieve OpenTelemetry Tracing API scenarios. There were few areas which were required in OpenTelemetry API, but was not included in 5.0, due to timing issues/OpenTelemetry spec not being ready before .NET 5 cut off time. One of the key missing pieces is the Propagators API. A propagator API allows libraries to inject and/or extract distributed tracing context when leaving process boundaries.

This API would be used by libraries such as Asp.Net Core, HttpClient, to extract/inject context from/to the next hop in a distributed trace. Currently, these libraries have a hard-coded propagators (following W3CTraceContext), baked into the library itself. This causes issues, when the end user want to use a non W3CTraceContext propagator. There is an issue opened in AspNetCore repo to allow pluggable propagators, but to make it happen, an API must be exposed by the runtime itself. (https://github.com/dotnet/aspnetcore/issues/28642)

## Proposed API

The proposal is to expose an API, which matches the [OpenTelemetry specification for Propagators.](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/context/api-propagators.md).

**Comment by MihaZupan** [comment] 2021-08-03 18:11
Should this be closed as a dupe of #50658?

**Closed** 2021-08-03 18:45 UTC
Labels: api-suggestion, area-System.Diagnostics.Tracing, feature request
