### ISSUE TITLE
JsonObject does not respect JsonIgnoreCondition.WhenWritingNull

### ISSUE THREAD

**Issue by ddunkin** [dotnet/runtime#54184] opened 2021-06-14 22:04 UTC
### Description

Serializing a `JsonObject` with serializer options `DefaultIgnoreCondition` set to `JsonIgnoreCondition.WhenWritingNull` does not ignore null values for properties on the `JsonObject`. There is no obvious way to not write those null values.

```c#
using System.Text.Json.Node;
using System.Text.Json.Serialization;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace JsonObjectNullTest
{
	[TestClass]
	public class UnitTest
	{
		[TestMethod]
		public void TestJsonIgnoreCondition()
		{
			var obj = new JsonObject { ["foo"] = null, ["bar"] = true };
			var json = obj.ToJsonString(new() { DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull });
			Assert.AreEqual("{\"bar\":true}", json);
		}
	}
}
```

### Configuration

macOS 10.15.7 x64
6.0.100-preview.4.21255.9

### Regression?

No

### Other information

My current workaround is to recursively check `JsonObject` for any null properties and delete them before serializing.

I would expect [JsonObject.WriteTo](https://github.com/dotnet/runtime/blob/6474c725025a8b29b4265c4d9485018982ee6b16/src/libraries/System.Text.Json/src/System/Text/Json/Nodes/JsonObject.cs#L103-L107) to have something like:

```c#
                foreach (KeyValuePair<string, JsonNode?> kvp in Dictionary)
                {
                    if (kvp.Value is null && options.DefaultIgnoreCondition == JsonIgnoreCondition.WhenWritingNull)
                        continue;
                    writer.WritePropertyName(kvp.Key);
                    JsonNodeConverter.Instance.Write(writer, kvp.Value!, options);
                }
```

**Comment by eiriktsarpalis** [comment] 2021-07-16 13:15
I can reproduce. I would presume that this happens because `JsonNode` tree serialization is handled recursively by the relevant converter without relying on the `JsonPropertyInfo` infrastructure that typically handles `JsonIgnoreCondition` settings. I defer to @steveharter on whether this is by design or should be fixed.

**Comment by steveharter** [comment] 2021-07-19 15:31
The behavior is expected. The `JsonSerializerOptions` passed to serialize is used for custom converters and not for the other values.

`JsonNode` is backed by a `JsonElement` after a `JsonNode.Parse()`, so when serializing a node those semantics are used which do not support "default values". For consistency, the same is true in "edit" mode when creating a `JsonNode` directly. This behavior of using `JsonSerializerOptions` was discussed heavily during the design phase and is the main reason `JsonNodeOptions` was added.

If we want `JsonNode` to support "default values" (and the many other serializer features), then we need to add options to both `JsonNodeOptions` and for consistency also to `JsonWriterOptions` or `JsonReaderOptions` depending. So for this case, we would want to add:
```diff
namespace System.Text.Json
{
    public struct JsonWriterOptions
    {
+        public JsonIgnoreCondition DefaultIgnoreCondition { get; set; }
    }
}

namespace System.Text.Json.Nodes
{
    public struct JsonNodeOptions
    {
+        public JsonIgnoreCondition DefaultIgnoreCondition { get set; }
    }
}
```

With code like this:
```cs
JsonNodeOptions nodeOptions = new () { DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull };
var obj = new JsonObject(nodeOptions) { ["foo"] = null, ["bar"] = true };
var json = obj.ToJsonString();
Assert.AreEqual("{\"bar\":true}", json);
```

**Comment by steveharter** [comment] 2021-07-30 21:40
Moving to 7.0; also if other interop is needed with serializer features they should be combined into a single issue.

**Comment by eiriktsarpalis** [comment] 2022-01-13 11:40
Similar report concerning `JsonDocument`: https://github.com/dotnet/docs/issues/27824

**Comment by layomia** [comment] 2022-01-21 23:12
Yeah, I say we close this issue as a documentation issue - dotnet/docs#27824. @ddunkin please consider a new proposal to extend `JsonNodeOptions` if you still need this functionality.

**Closed by layomia** 2022-01-21 23:12 UTC
Labels: enhancement, area-System.Text.Json
