### ISSUE TITLE
new PrincipalContext(ContextType.Domain) is not disposed at the end of the function

### ISSUE THREAD

**Issue by achufistov** [dotnet/runtime#94774] opened 2023-11-15 13:42 UTC
### Description

dotnet 6.0

File: /src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/User.cs:195

Problem: new PrincipalContext(ContextType.Domain) is not disposed at the end of the function 

### Reproduction Steps

1) Role: detected
detected
[User.cs:[195:0]]

2) Role: tracepoint
2.1 Step 1: Condition Utils.IsSamUser() taking false branch
[User.cs:[179:21]]
2.2 created in constructor System.DirectoryServices.AccountManagement.PrincipalContext.PrincipalContext(System.DirectoryServices.AccountManagement.ContextType)
[User.cs:[195:31]]
2.3. no escape
[User.cs:[195:31]]
2.4 assigned
[User.cs:[195:21]]
2.5 no escape
[User.cs:[215:28]]
2.6 Step 2: Condition pSid != IntPtr.Zero taking any branch
[User.cs:[219:25]]
2.7 Step 3: Condition user == null taking false branch
[User.cs:[225:21]]
2. 8 return
[User.cs:[231:24]]

### Expected behavior

memory leak

### Actual behavior

memory leak

### Other information

Found by Linux Verification Center (linuxtesting.org) with SVACE.

**Comment by achufistov** [comment] 2023-11-17 08:44
I would like to suggest a pull request.

**Comment by buyaa-n** [comment] 2024-01-17 19:22
Closing as duplicate of https://github.com/dotnet/runtime/issues/94772

**Closed by buyaa-n** 2024-01-17 19:22 UTC
Labels: area-System.DirectoryServices, untriaged
