### ISSUE TITLE
Ability to export constant on app host

### ISSUE THREAD

**Issue by huoyaoyuan** [dotnet/runtime#3847] opened 2019-11-23 10:00 UTC
The use case is `NvOptimusEnablement`.
There seems to be a way to write export constants in IL, but IL cannot be written easily together with C#.
Using C++/CLI is unsuitable, because the whole project contains no native code and is cross platform.

A potential pure C# solution is adding a custom attribute:
```csharp
[AttributeUsage(AttributeTargets.Assembly)]
public sealed class ExportConstantAttribute : Attribute
{
    public string Name { get; set; }
    public Type Type { get; set; }
    public object Value { get; set; }
}

// usage
[assembly: ExportConstant("NvOptimusEnablement" ,typeof(int), 1)]
```
The build process emits the export on output native host.

Alternative:
```csharp
[AttributeUsage(AttributeTargets.Field)]
public sealed class DllExportAttribute : Attribute {}

[DllExport]
public const int NvOptimusEnablement = 1;
```
Let the compiler special treats it like `DllExport`, and just copy exports from managed to native.

**Comment by jkotas** [comment] 2020-04-06 08:02
Duplicate of https://github.com/dotnet/runtime/issues/10929

**Closed by jkotas** 2020-04-06 08:02 UTC
Labels: area-Host
