### ISSUE TITLE
GCC JIT build warnings on type width

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/runtime#55479] opened 2021-07-11 20:19 UTC
The GCC build of the JIT has plenty of warnings that look like:

```
/__w/1/s/src/coreclr/jit/emit.h:534:25: warning: 'emitter::emitAddrMode::amScale' is too small to hold all values of 'enum emitter::opSize'
  534 |         emitter::opSize amScale : 2;
      |                         ^~~~~~~
/__w/1/s/src/coreclr/jit/emit.h:853:27: warning: 'emitter::instrDesc::idAddrUnion::<unnamed struct>::_idReg3' is too small to hold all values of 'regNumber' {aka 'enum _regNumber_enum'}
  853 |                 regNumber _idReg3 : REGNUM_BITS;
      |                           ^~~~~~~
/__w/1/s/src/coreclr/jit/emit.h:854:27: warning: 'emitter::instrDesc::idAddrUnion::<unnamed struct>::_idReg4' is too small to hold all values of 'regNumber' {aka 'enum _regNumber_enum'}
  854 |                 regNumber _idReg4 : REGNUM_BITS;
      |                           ^~~~~~~
/__w/1/s/src/coreclr/jit/emit.h:667:19: warning: 'emitter::instrDesc::_idReg1' is too small to hold all values of 'regNumber' {aka 'enum _regNumber_enum'}
  667 |         regNumber _idReg1 : REGNUM_BITS; // register num
      |                   ^~~~~~~
/__w/1/s/src/coreclr/jit/emit.h:669:19: warning: 'emitter::instrDesc::_idReg2' is too small to hold all values of 'regNumber' {aka 'enum _regNumber_enum'}
  669 |         regNumber _idReg2 : REGNUM_BITS;
      |   
```

cc: @am11, @dotnet/jit-contrib

**Comment by am11** [comment] 2021-07-11 20:35
It is the duplicate of #33541. The original issue was fixed by updating gcc to v9, the remaining warnings are non-critical but correct depending on how developer or compiler look at it (https://github.com/dotnet/runtime/issues/33541#issuecomment-754285791).

**Closed** 2021-07-11 23:26 UTC
Labels: area-CodeGen-coreclr, untriaged
