### ISSUE TITLE
System.Reflection.MetadataLoadContext doesn't support function pointer types

### ISSUE THREAD

**Issue by vargaz** [dotnet/runtime#43791] opened 2020-10-24 00:44 UTC
To reproduce: run the attached project
Version: master
Expected result: works
Actual result:
```
Unhandled exception. System.NotSupportedException: Parsing function pointer types in signatures is not supported.
   at System.Reflection.TypeLoading.Ecma.EcmaModule.GetFunctionPointerType(MethodSignature`1 signature)
   at System.Reflection.Metadata.Ecma335.SignatureDecoder`2.DecodeType(BlobReader& blobReader, Boolean allowTypeSpecifications, Int32 typeCode)
   at System.Reflection.Metadata.Ecma335.SignatureDecoder`2.DecodeMethodSignature(BlobReader& blobReader)
   at System.Reflection.TypeLoading.Ecma.EcmaMethodDecoder.SpecializeMethodSig(IRoMethodBase roMethodBase)
   at System.Reflection.TypeLoading.RoDefinitionMethod`1.ComputeMethodSig()
   at System.Reflection.TypeLoading.RoMethod.get_MethodSig()
   at System.Reflection.TypeLoading.RoMethod.get_ReturnParameter()
   at System.Reflection.TypeLoading.RoMethod.get_ReturnType()
```

**Comment by vargaz** [comment] 2020-10-24 00:45
[test.tar.gz](https://github.com/dotnet/runtime/files/5432226/test.tar.gz)

**Comment by marek-safar** [comment] 2020-10-24 12:18
Hmm how is Roslyn reading such metadata?

@jaredpar @MichalStrehovsky

**Comment by MichalStrehovsky** [comment] 2020-10-24 14:37
This looks like a bug in System.Reflection.MetadataLoadContext. It's a library built on top of System.Reflection.Metadata that provides additional abstractions over the metadata. Roslyn only uses S.R.Metadata, not this extra layer with the missing implementation.

**Comment by steveharter** [comment] 2020-11-12 15:27
> This looks like a bug in System.Reflection.MetadataLoadContext

It is apparently by design since it throws an explicit `NotSupportedException` when detecting a function pointer.

This overlaps with https://github.com/dotnet/runtime/issues/11354 where we don't return function pointer type from standard reflection either and need a way to represent that.

Doing a `typeof(delegate*<void>)` (for example) returns `System.IntPtr` as the type, so it would be expected that MLC return `IntPtr` as the type. However, that doesn't allow inspection of the parameters or return type and there is not an existing "function pointer" type in .NET.

**Comment by steveharter** [comment] 2020-11-12 15:33
@vargaz @CoffeeFlux can you add more detail including the workaround you use, and the "blocking" label if you consider it blocking. Thanks

**Comment by vargaz** [comment] 2020-11-12 23:22
We just hardcode to method names which have these types in our code, its not currently a blocker for us.

**Comment by lewing** [comment] 2020-11-13 19:33
@steveharter the current workaround is here
https://github.com/dotnet/runtime/blob/master/tools-local/tasks/mobile.tasks/WasmAppBuilder/PInvokeTableGenerator.cs#L156..L161

**Comment by jeromelaban** [comment] 2020-11-28 02:15
This is a feature that will be a important addition for libraries like SkiaSharp running on WebAssembly.

**Comment by lewing** [comment] 2020-11-28 19:00
Yes it will be required for https://github.com/dotnet/runtime/issues/44636

**Comment by lewing** [comment] 2021-07-22 23:14
This will be an ongoing issue for blazor/webassembly.

**Comment by marek-safar** [comment] 2021-07-23 20:56
@krwq why was it moved to 7.0 when https://github.com/dotnet/runtime/issues/43791#issuecomment-735277035 explained that this is needed for P1 .NET user story?

**Comment by MichalStrehovsky** [comment] 2021-07-24 07:51
My 5 cents: I'm not sure this can be implemented in MetadataLoadContext without first defining how function pointers are supposed to look like within the runtime/reflection stack (#11354 tracks parts of that), like @steveharter pointed out.

Function pointer behavior is currently pretty arbitrary within the runtime reflection stack: https://twitter.com/MStrehovsky/status/1311247635756412928

I don't know if it's good use of time to make `MetadataLoadContext` emulate that behavior only so that we can break it again when #11354 is defined just because a tool took a dependency on it.

I would suggest looking into a technology that is [more suitable to build compiler components](https://github.com/dotnet/runtime/issues/29723#issuecomment-595374594) - System.Reflection.Metadata directly, or even Cecil.

**Comment by vargaz** [comment] 2021-07-24 08:00
Maybe we can fix our wasm tooling to work around this, but function pointer types are increasing in usage, so other users will run into this problem.

**Comment by krwq** [comment] 2021-07-28 15:39
@marek-safar we've moved most of the issues marked as `enhancement` to 7.0.0/Future - must've missed the comment. Should this issue have `arch-wasm` - this way it will disappear from our radar?

**Comment by lambdageek** [comment] 2022-06-22 01:37
@steveharter Will the https://github.com/dotnet/runtime/issues/69273 MetadataLoadContext work also happen in 7? Will that include also the .NET Framework version of MLC? If so, that will help us with this issue with the wasm tooling.

**Comment by steveharter** [comment] 2022-07-06 21:29
@lambdageek yes MetadataLoadContext will be updated along with the CoreClr runtime. The active PR is https://github.com/dotnet/runtime/pull/71516.

It should be possible to use .NET framework with MetadataLoadContext function pointers although reflection will necessary to call the new APIs on Type. I'll provide an example once that PR is in.

**Comment by jkotas** [comment] 2022-07-11 15:41
> It should be possible to use .NET framework with MetadataLoadContext function pointers although reflection will necessary to call the new APIs on Type. I'll provide an example once that PR is in.

We may want to provide extension methods so that it is not necessary to use reflection.

**Comment by steveharter** [comment] 2022-07-13 17:27
Moving to 8.0; we need to update the API and design based on feedback from https://github.com/dotnet/runtime/pull/71516.

**Closed** 2023-02-16 20:39 UTC
Labels: enhancement, area-System.Reflection, in-pr
