### ISSUE TITLE
JsonSerializerOptionsNoTypeInfoResolverSpecified after upgrading from .NET 8 Preview 6 to 7 (release mode only)

### ISSUE THREAD

**Issue by DM-98** [dotnet/runtime#90395] opened 2023-08-11 14:09 UTC
### Description

App works fine in debug mode for both Preview 6 and 7.
App crashes in release mode for just Preview 7: JsonSerializerOptionsNoTypeInfoResolverSpecified.

My app worked fine in .NET 8 Preview 6:
![DebugMode](https://github.com/dotnet/runtime/assets/10290906/4f74cf99-fc91-403c-a0bf-e56663ab8a68)

After upgrading to .NET 8 Preview 7:
![ReleaseMode](https://github.com/dotnet/runtime/assets/10290906/0c651b2a-993f-484d-a824-7474cb327705)

Seems like a JsonSerializer bug in the .NET Preview 7 install package. I tried these:
* Keeping same codebase, but changing from 6 to 7 and back to 6 to confirm the issue
* Changing JsonSerializer to JsonConvert, issue persists
* Creating my own JsonSerializerContext class using the attributes and applying it as my TypeInfoResolver for the JsonSerializerOptions: [JsonSourceGenerationOptions] & [JsonSerializable(typeof(MySerializableType))], then the error changes to NoMetadataSpecified or something like that
* Removed JsonSerializerOptions entirely in my code, issue persists
* Used PostAsync instead of PostAsJsonAsync, issue persists

### Steps to Reproduce

1. Create an API with a HttpPost endpoint that accepts a complex object in body
2. Create a MAUI app that runs on .NET 8 Preview 7 (dotnet workload install maui)
3. Call the API endpoint with a Post request using PostAsJsonAsync method
4. Run the app in Release mode using .NET 8 Preview 7

### Link to public reproduction project repository

[https://github.com/DM-98/MauiApp1](https://github.com/DM-98/MauiApp1)

### Version with bug

8.0.0-preview.7.8842

### Is this a regression from previous behavior?

Yes, this used to work in .NET MAUI

### Last version that worked well

8.0.0-preview.6.8686

### Affected platforms

Android, I was *not* able test on other platforms

### Affected platform versions

Android 13, not tested on other.

### Did you find any workaround?

Change back to previous SDK: .NET 8 Preview 6.

**Comment by eiriktsarpalis** [comment] 2023-08-11 15:27
Appears to be a duplicate of https://github.com/dotnet/maui/issues/16038

**Closed by eiriktsarpalis** 2023-08-11 15:27 UTC
Labels: area-System.Text.Json, untriaged

**Comment by DM-98** [comment] 2023-08-11 15:36
@eiriktsarpalis That worked, thanks. When will this be fixed, and after fix can I remove that line? in .NET 8 RC1?

**Comment by eiriktsarpalis** [comment] 2023-08-11 15:37
@DM-98 I would recommend subscribing to https://github.com/dotnet/maui/issues/16038 for updates on the issue.
