### ISSUE TITLE
Test failure GC\\Scenarios\\FinalizeTimeout\\FinalizeTimeout\\FinalizeTimeout.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#73668] opened 2022-08-10 01:28 UTC
Run: [runtime-coreclr outerloop 20220809.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1932185&view=ms.vss-test-web.build-test-results-tab&runId=49917266&resultId=106361&paneView=debug)

Failed test:
```
R2R-CG2 windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open

- GC\\Scenarios\\FinalizeTimeout\\FinalizeTimeout\\FinalizeTimeout.cmd

R2R-CG2 windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open

- JIT\\Regression\\JitBlue\\GitHub_27924\\GitHub_27924\\GitHub_27924.cmd

R2R-CG2 OSX x64 Checked no_tiered_compilation @ OSX.1200.Amd64.Open

- GC/Scenarios/FinalizeTimeout/FinalizeTimeout/FinalizeTimeout.sh
```

**Error message:**
```
Assert failure(PID 11304 [0x00002c28], Thread: 9296 [0x2450]): slot_table[slot_index] == nullptr

CORECLR! dynamic atexit destructor for 'WKS::gc_heap::mark_queue'' + 0x3C (0x00007ff91e3af3fc)
CORECLR! <lambda_d121dba8a4adeaf3a9819e48611155df>::operator() + 0x13C (0x00007ff91e2c20bc) CORECLR! _crt_seh_guarded_call<int>::operator()<<lambda_6a47f4c8fd0152770a780fc1d70204eb>,<lambda_d121dba8a4adeaf3a9819e48611155df> &,<lambda_6aaa2265f5b6a89667e7d7630012e97a> > + 0x34 (0x00007ff91e2c17d4)
CORECLR! _acrt_lock_and_call<<lambda_d121dba8a4adeaf3a9819e48611155df> > + 0x50 (0x00007ff91e2c1908) CORECLR! execute_onexit_table + 0x38 (0x00007ff91e2c22d0)
CORECLR! <lambda_6e4b09c48022b2350581041d5f6b0c4c>::operator() + 0xC0 (0x00007ff91e2bf638) CORECLR! _crt_seh_guarded_call<void>::operator()<<lambda_d80eeec6fff315bfe5c115232f3240e3>,<lambda_6e4b09c48022b2350581041d5f6b0c4c> &,<lambda_2358e3775559c9db80273638284d5e45> > + 0x2C (0x00007ff91e2bf30c)
CORECLR! _acrt_lock_and_call<<lambda_6e4b09c48022b2350581041d5f6b0c4c> > + 0x50 (0x00007ff91e2bf370) CORECLR! common_exit + 0x80 (0x00007ff91e2bf8a0)
CORECLR! cexit + 0x1C (0x00007ff9`1e2bfbdc)
File: D:\a_work\1\s\src\coreclr\gc\gc.cpp Line: 23966
Image: D:\h\w\A7050902\p\corerun.exe

Return code:      1
Raw output file:      D:\h\w\A7050902\w\A35308CA\uploads\Reports\GC.Scenarios\FinalizeTimeout\FinalizeTimeout\FinalizeTimeout.output.txt
Raw output:
BEGIN EXECUTION
FinalizeTimeout.dll
1 file(s) copied.
13:59:23.80
Response file: D:\h\w\A7050902\w\A35308CA\e\GC\Scenarios\FinalizeTimeout\FinalizeTimeout\FinalizeTimeout.dll.rsp
D:\h\w\A7050902\w\A35308CA\e\GC\Scenarios\FinalizeTimeout\FinalizeTimeout\IL-CG2\FinalizeTimeout.dll
-o:D:\h\w\A7050902\w\A35308CA\e\GC\Scenarios\FinalizeTimeout\FinalizeTimeout\FinalizeTimeout.dll
--targetarch:arm64
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\A7050902\p\System..dll
-r:D:\h\w\A7050902\p\Microsoft..dll
-r:D:\h\w\A7050902\p\mscorlib.dll
-r:D:\h\w\A7050902\p\netstandard.dll
-O
" "dotnet" "D:\h\w\A7050902\p\crossgen2\crossgen2.dll" @"D:\h\w\A7050902\w\A35308CA\e\GC\Scenarios\FinalizeTimeout\FinalizeTimeout\FinalizeTimeout.dll.rsp"   -r:D:\h\w\A7050902\w\A35308CA\e\GC\Scenarios\FinalizeTimeout\FinalizeTimeout\IL-CG2*.dll"
Emitting R2R PE file: D:\h\w\A7050902\w\A35308CA\e\GC\Scenarios\FinalizeTimeout\FinalizeTimeout\FinalizeTimeout.dll
13:59:27.60
"D:\h\w\A7050902\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  FinalizeTimeout.dll
Main start
Finalizer start
Finalizer end
Main end
Finalizer start
Finalizer end
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\A7050902\p
D:\h\w\A7050902\w\A35308CA\e\GC\Scenarios\FinalizeTimeout\FinalizeTimeout\FinalizeTimeout.cmd
Expected: True
Actual:   False


Stack trace
   at GC_Scenarios._FinalizeTimeout_FinalizeTimeout_FinalizeTimeout_._FinalizeTimeout_FinalizeTimeout_FinalizeTimeout_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by radical** [comment] 2022-08-10 06:46
Also being hit on `runtime` pipeline - https://dev.azure.com/dnceng/public/_build/results?buildId=1933642&view=logs&jobId=bb94f37e-a09b-5b51-09b2-ab78e7aa5103&j=bb94f37e-a09b-5b51-09b2-ab78e7aa5103&t=506cadc9-3cc4-5d96-6847-011f75a33382 .

**Comment by am11** [comment] 2022-08-10 13:49
Failing in `coreclr Pri0 Runtime Tests Run OSX x64 checked`as well: https://helix.dot.net/api/2019-06-17/jobs/a05e6ce5-b747-414f-8b8a-26863ad568f7/workitems/PayloadGroup0/console

PR #73686

**Comment by mangod9** [comment] 2022-08-10 19:09
This is a dupe of https://github.com/dotnet/runtime/issues/73679

**Closed by mangod9** 2022-08-10 19:09 UTC
Labels: arch-arm64, arch-x86, os-mac-os-x, os-windows, arch-x64, area-crossgen2-coreclr, blocking-clean-ci, untriaged, blocking-outerloop
