### ISSUE TITLE
Inconsistent socket behavior between dotnet and native

### ISSUE THREAD

**Issue by matthew798** [dotnet/runtime#30782] opened 2019-09-06 12:21 UTC
I have observed what I believe to be a discrepancy between managed and native socket.

I am on dotnet core 2.2 and 3.0 on linux x64.

The problem is when you have 2 sockets. Both _bound_ to the same endpoint (`localEP`), and one _connected_ to a remote endpoint (`remoteEp`). AFAIK, dgrams from `remoteEp` should _always_ end up at the _connected_ socket, and dgrams from _anywhere_ else should end up at the _bound_ socket. This behavior can be observed in the code from [here](https://github.com/nplab/DTLS-Examples/blob/master/src/dtls_udp_echo.c). This code implements a DTLS server. It listens for DTLS connection requests on one socket which is only bound to a local EP. When a connection is established, it creates a new socket _bound to the same EP_ and _connects_ it to the remote EP.

The result is that all dgrams from a connected client end up at their respective sockets.

In C# (dotnet 2.2 and 3.0), this cannot be reproduced. Take, for example, the following:

```c#
var localEp = new IPEndPoint(IPAddress.Loopback, 1114);

var socket = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp);
socket.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseAddress, true);
socket.Bind(localEp);
...
accept a connection...
...
var clientSocket = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp);
clientSocket.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseAddress, true);
clientSocket.Bind(localEp);
clientSocket.Connect(remoteEp);
```

At this point, there is no way to guarantee that the client's dgrams will make it to clientSocket. This does not match the behavior of the code I linked above.

From reading dotnet/runtime#27274 I know that as of core 3.0, when setting SO_REUSEADDRESS, SO_REUSEPORT is also set. In the linked code, SO_REUSEPORT is _not_ set on linux. I doubt this is the problem however since my code also doesn't work in 2.2.

I posted a [question on SO](https://stackoverflow.com/questions/57780384/managed-sockets-not-behaving-as-i-expected). I did a test with managed sockets and the result is confusing at best.

[This document](https://lwn.net/Articles/542629/) confirms the expected behavior:

> The first of these is a useful aspect of the implementation. Incoming connections and datagrams are distributed to the server sockets using a hash based on the 4-tuple of the connection—that is, the peer IP address and port plus the local IP address and port. This means, for example, that if a client uses the same socket to send a series of datagrams to the server port, then those datagrams will all be directed to the same receiving server (as long as it continues to exist). This eases the task of conducting stateful conversations between the client and server.

**Comment by tmds** [comment] 2020-06-26 11:20
> We can see if it makes sense to not set SO_REUSEPORT for ReuseAddress for UDP on Linux.

Looking at nodejs implementation, when reuse is enabled for udp:
SO_REUSEPORT is set, except on Linux, where SO_REUSEADDR is set.

The effect of not setting SO_REUSEPORT on Linux, is that unicast traffic will no longer be distributed across multiple bound UDP sockets.
Multicast, and broadcast will still be received by all bound sockets.

From reading the Windows docs, I _think_ `SocketOptionName.ReuseAddress` doesn't distribute accross multiple bound UDP sockets.

This matches libuv docs for `UV_UDP_REUSEADDR`:
```
What that means is that
    * multiple threads or processes can bind to the same address without error
    * (provided they all set the flag) but only the last one to bind will receive
    * any traffic, in effect "stealing" the port from the previous listener.
    */
```

So based on this, I think we can change the implementation so it doesn't set SO_REUSEPORT for `SocketOptionName.ReuseAddress` for UDP on Linux.

**Comment by tmds** [comment] 2021-02-05 14:26
@karelz can you close this? This PR should fix the issue: https://github.com/dotnet/runtime/pull/38534, but we are unable to reproduce the issue (https://github.com/dotnet/runtime/pull/38534#issuecomment-732219316).

**Comment by karelz** [comment] 2021-02-08 16:05
Closing per comment above -- we couldn't reproduce, so Won't Fix.

**Closed by karelz** 2021-02-08 16:05 UTC
Labels: area-System.Net.Sockets, os-linux, question
