### ISSUE TITLE
Test crossgen-comparison timing out 

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#33404] opened 2020-03-09 22:36 UTC
https://dev.azure.com/dnceng/public/_build/results?buildId=552789&view=logs&j=e14ed261-6507-56f9-47b6-1ad25f52112f&t=092d7480-ef4c-554b-1734-6f013bac0005&l=24

**Comment by jaredpar** [comment] 2020-03-10 04:33
@jkoritzinsky where are you seeing that 404 in that build? I see 

- One instance of #33271
- Two instance of the NuGet restore issue
- Crossgen timeout

I didn't see a new 404 though. Which build job is this hitting?

**Comment by jkoritzinsky** [comment] 2020-03-10 05:02
I didn’t realize that the crossgen timeout could surface as a 404. It wasn’t the usual AzDO job timeout so I didn’t think it was that. I opened an issue in case we weren’t tracking it somewhere.

**Comment by jaredpar** [comment] 2020-03-10 05:10
@jashook recently updated the timeout here to two hours but it looks like that isn't enough.

**Comment by jaredpar** [comment] 2020-03-10 05:12
@MattGal seems like there is also a Helix issue here. The link put into the logs here is 404ing 

https://helix.dot.net/api/2019-06-17/jobs/130b89a9-5f96-491c-b19b-14f6cbd9e5fc/workitems/WorkItem/console

**Comment by MattGal** [comment] 2020-03-10 16:25
> @MattGal seems like there is also a Helix issue here. The link put into the logs here is 404ing as @jkoritzinsky noted
> 
> https://helix.dot.net/api/2019-06-17/jobs/130b89a9-5f96-491c-b19b-14f6cbd9e5fc/workitems/WorkItem/console

Sort of.  Yes, this work item never ran, hence the 404'ed console log.  We could make that experience better (it's supposed to send you to https://dotnet.github.io/core-eng/helix-workitem-deadletter.txt as it is in the Kusto DB, not just 404; this is likely a subtle bug with the console log API I can file).

The real problem here is that this workitem's payload is 782 MB.  If you go to [the helix api for it](https://helix.dot.net/api/2019-06-17/jobs/130b89a9-5f96-491c-b19b-14f6cbd9e5fc/workitems/WorkItem) you can see this:

```
{
	"FailureReason": null,
	"Id": "3151d3a7-cb96-48a1-a3c9-283c33815189",
	"MachineName": "ddvsotx2l248",
	"ExitCode": -3,
	"ConsoleOutputUri": null,
	"Errors": [{
		"Id": "DownloadError",
		"Message": "Unable to download https://helixde107v0xdeko0k025g8.blob.core.windows.net/helix-job-aa658276-2739-4153-9b22-45030c59491514f522acafe4c7d90/8c541d3a-b94b-4a05-90f3-cbdba0207025.zip after retrying. Execution may fail as a result.",
		"LogUri": null
	}],
...
```
basically, these little devices (Jetsons, Pis, and Hummingboards) have slow network connections, and downloading and unpacking a Helix workitem's payload times out at 10 minute (excerpt from [the log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-33393-merge-130b89a95f96491cb1/WorkItem.Attempt.2/7be520eb-ead3-455d-a63d-a18e132aa1eb.log?sv=2019-02-02&se=2020-03-19T19%3A43%3A23Z&sr=c&sp=rl&sig=N66dNPbhguUhVKXvHI4P7wEALyO2beOwbrZLX7dNXDw%3D)):

```
2020-03-09T20:57:51. 91Z	INFO   	servicebusrepository(109)	renew_workitem_lock	Renewed work item lock. Status Code: 200
2020-03-09T20:58:29.121Z	INFO   	executor(354)	_download_to	Signal response processing thread to terminate as it is running for more than 10 mins True
2020-03-09T20:58:29.128Z	INFO   	executor(489)	_get_unpacked_file_paths	Reading archive file:/ssd/work/A75909B5/w/A57208B6/8c541d3a-b94b-4a05-90f3-cbdba0207025.zip.partial
2020-03-09T20:58:29.129Z	INFO   	executor(314)	_download_request	response processing thread is set to terminate True
2020-03-09T20:58:29.135Z	INFO   	executor(690)	_delete_if_exists	Deleting file: /ssd/work/A75909B5/w/A57208B6/8c541d3a-b94b-4a05-90f3-cbdba0207025.zip.partial
2020-03-09T20:58:29.327Z	ERROR  	executor(220)	_download_and_unpack	Exception "File is not a zip file" seen downloading: 
Traceback (most recent call last): (irrelevant; this isn't a zip file because we terminated the downloads)
```

So, the only way we can make slow-network on prem machines succeed in doing what you're trying to do here would be to drastically increase the 10-minute time for payload downloading (in practice, from trying out on the real hardware a ~700 MB file can take as much as 29 minutes on one of these devices).  See @Chrisboh if you feel strongly we should do this.

I think there's real room for improvement in how you're constructing [this work item payload](https://helixde107v0xdeko0k025g8.blob.core.windows.net/helix-job-aa658276-2739-4153-9b22-45030c59491514f522acafe4c7d90/8c541d3a-b94b-4a05-90f3-cbdba0207025.zip)

You have 4482 files that unpack that include things like:
- 1.4 GB of "bin" directory that contains lots of duplicate files as the other folders
- 326 MB of Testhost including its own copy of framework DLLs.
- 40 MB of XML docs
- 73 MB of reference assemblies for build-time stuff including desktop .NET
- 4x identical copies of libcoreclr.so (147,781,152 bytes apiece)
- 445 MB of core-root files (should be a correlation payload ideally)
- the send to helix binlog
- temp folders
- logs
- 150 MB of x64 .so files (this is ARM?)
- 18 MB of Targeting Pack including x86 and x64 binaries (this is ARM?)

Even if the performance for on-prem machines could handle this much network bandwidth, this is a very slow way to run tests.  This payload doesn't make sense to me, and I think is just someone's repo all zipped up.  This is not how Helix was intended to be used.

**Comment by jashook** [comment] 2020-03-31 16:34
This is closed via:

https://github.com/dotnet/runtime/pull/33498
https://github.com/dotnet/runtime/pull/33436
https://github.com/dotnet/runtime/pull/33175

**Closed by jashook** 2020-03-31 16:34 UTC
Labels: area-Infrastructure, blocking-clean-ci
