### ISSUE TITLE
[browser][MT] legacy JS interop needs GC boundaries on main thread too

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#90044] opened 2023-08-04 18:36 UTC
Calling legacy `mono_wasm_invoke_method_ref` on the main thread could lead to GC transition assert at `mono-threads-state-machine.c:807`

See https://github.com/dotnet/runtime/issues/89909#issuecomment-1665811281

**Comment by kg** [comment] 2023-08-04 19:22
Is this still 8.0 if the related issue is 9.0?

**Comment by pavelsavara** [comment] 2023-08-07 12:16
I think this is bug, not a new feature.

**Comment by lewing** [comment] 2023-08-13 04:27
closing as a duplicate of https://github.com/dotnet/runtime/issues/89909

**Closed** 2024-01-19 15:23 UTC
Labels: arch-wasm, area-VM-threading-mono, in-pr, os-browser
