### ISSUE TITLE
[mono] Tests failed due to PNSE on windows: Microsoft.Extensions.*

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#34580] opened 2020-04-06 09:42 UTC
Some `Microsoft.Extensions` test namespaces fail on windows with `System.PlatformNotSupportedException : This API is specific to the way in which Windows handles asynchronous I/O, and is not supported on this platform.`:
- Microsoft.Extensions.FileProviders.PhysicalFileProviderTests
- Microsoft.Extensions.FileProviders.Physical.Tests.PhysicalFilesWatcherTests
-  Microsoft.Extensions.Configuration.FunctionalTests.ArrayTests
-  Microsoft.Extensions.Configuration.Test.ConfigurationTests
- Microsoft.Extensions.Configuration.UserSecrets.Test.ConfigurationExtensionTest
- Microsoft.Extensions.Hosting.HostTests
- Microsoft.Extensions.Hosting.HostBuilderTests

The example of the output:
```
System.PlatformNotSupportedException : This API is specific to the way in which Windows handles asynchronous I/O, and is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Private.CoreLib\src\System\Threading\ThreadPoolBoundHandle.PlatformNotSupported.cs(25,0): at System.Threading.ThreadPoolBoundHandle.BindHandle(SafeHandle handle)
    _\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.Win32.cs(74,0): at System.IO.FileSystemWatcher.StartRaisingEvents()
    _\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.cs(639,0): at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed()
    _\src\libraries\System.IO.FileSystem.Watcher\src\System\IO\FileSystemWatcher.cs(154,0): at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value)
    _\src\libraries\Microsoft.Extensions.FileProviders.Physical\src\PhysicalFilesWatcher.cs(378,0): at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher()
    _\src\libraries\Microsoft.Extensions.FileProviders.Physical\src\PhysicalFilesWatcher.cs(134,0): at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter)
    _\src\libraries\Microsoft.Extensions.FileProviders.Physical\src\PhysicalFileProvider.cs(336,0): at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter)
    _\src\libraries\Microsoft.Extensions.Configuration.FileExtensions\src\FileConfigurationProvider.cs(37,0): at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0()
    _\src\libraries\Microsoft.Extensions.Primitives\src\ChangeToken.cs(72,0): at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1[[System.Action, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, Action state)
    _\src\libraries\Microsoft.Extensions.Primitives\src\ChangeToken.cs(33,0): at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
    _\src\libraries\Microsoft.Extensions.Configuration.FileExtensions\src\FileConfigurationProvider.cs(36,0): at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source)
    _\src\libraries\Microsoft.Extensions.Configuration.Json\src\JsonConfigurationProvider.cs(21,0): at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider..ctor(JsonConfigurationSource source)
    _\src\libraries\Microsoft.Extensions.Configuration.Json\src\JsonConfigurationSource.cs(22,0): at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder)
    _\src\libraries\Microsoft.Extensions.Configuration\src\ConfigurationBuilder.cs(52,0): at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
    _\src\libraries\Microsoft.Extensions.Hosting\src\HostBuilder.cs(199,0): at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
    _\src\libraries\Microsoft.Extensions.Hosting\src\HostBuilder.cs(131,0): at Microsoft.Extensions.Hosting.HostBuilder.Build()
    _\src\libraries\Microsoft.Extensions.Hosting\tests\UnitTests\HostTests.cs(39,0): at Microsoft.Extensions.Hosting.HostTests.CreateDefaultBuilder_IncludesCommandLineArguments()
    _\src\mono\netcore\System.Private.CoreLib\src\System\Reflection\RuntimeMethodInfo.cs(359,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

The failing tests will be marked with `ActiveIssue` in https://github.com/dotnet/runtime/pull/32592.

**Comment by danmosemsft** [comment] 2020-04-07 00:24
dupe of https://github.com/dotnet/runtime/issues/34582

**Closed by danmosemsft** 2020-04-07 00:24 UTC
Labels: area-Microsoft.Extensions, untriaged
