### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kronic** [dotnet/runtime#1187] opened 2019-12-27 10:50 UTC
The Test(int a) function returns False instead of null, is this normal behavior?
```csharp
#region

using System;

#endregion

namespace MlTest
{
	internal static class Program
	{
		private static void Main()
		{
			var b = Test(10);
			Console.Write(b?.ToString() ?? "null"); //False
			Console.ReadKey();
		}
		private static bool? Test(int a) =>
			a switch
			{
				1 => true,
				2 => false,
				_ => default
			};
	}
}

**Comment by Gnbrkm41** [comment] 2019-12-27 11:05
I believe this is more suited to dotnet/roslyn (or even dotnet/csharpland) rather than this repo. It appears that the switch statement above generates a `bool` value, not `bool?`;
IL generated:
```
Test:
IL_0000:  ldarg.0     
IL_0001:  ldc.i4.1    
IL_0002:  beq.s       IL_000A
IL_0004:  ldarg.0     
IL_0005:  ldc.i4.2    
IL_0006:  beq.s       IL_000E
IL_0008:  br.s        IL_0012
IL_000A:  ldc.i4.1    
IL_000B:  stloc.0     
IL_000C:  br.s        IL_0014
IL_000E:  ldc.i4.0    
IL_000F:  stloc.0     
IL_0010:  br.s        IL_0014
IL_0012:  ldc.i4.0    
IL_0013:  stloc.0     
IL_0014:  ldloc.0     
IL_0015:  newobj      System.Nullable<System.Boolean>..ctor
IL_001A:  ret         
```

Which is roughly the same as:
```cs
private static bool? Test(int a)
{
	bool value;
	switch (a)
	{
	case 1:
		value = true;
		break;
	case 2:
		value = false;
		break;
	default:
		value = false;
		break;
	}
	return value;
}
```

**Comment by kronic** [comment] 2019-12-27 11:18
@Gnbrkm41 That is, is it still a mistake?

**Comment by Gnbrkm41** [comment] 2019-12-27 11:32
I'm not entirely sure... it *kind of* makes sense given that all the return values of the switch expression are `bool` (therefore `default` in that context becomes `default(bool)` which is false).

Is it an actual error/mistake? It's very hard to tell for me. *Possibly* It is by design. The correct place to ask would be https://github.com/dotnet/roslyn/issues. If it is by design, the folks there would close it (at which point you could make a proposal at https://github.com/dotnet/csharplang/issues where they will decide whether to leave this as a quirk or fix it.)

**Comment by kronic** [comment] 2019-12-27 11:38
https://github.com/dotnet/roslyn/issues/40618

**Comment by jkotas** [comment] 2019-12-27 15:43
As @Gnbrkm41 said, this is really a question for Roslyn and the behavior you are seeing is by design.

**Closed by jkotas** 2019-12-27 15:43 UTC
Labels: untriaged

**Comment by kronic** [comment] 2019-12-27 19:27
not at all obvious
