### ISSUE TITLE
The callback for the Hot Reload MetadataUpdateHandlerAttribute does not invoke.

### ISSUE THREAD

**Issue by idexus** [dotnet/runtime#82625] opened 2023-02-24 15:18 UTC
### Description

The callback for the Hot Reload MetadataUpdateHandlerAttribute does not invoke

```cs

[assembly: System.Reflection.Metadata.MetadataUpdateHandlerAttribute(typeof(ExampleApp.VSHotReloadService))]

#pragma warning disable CS8632

namespace ExampleApp
{
    public static class VSHotReloadService
    {
        public static void ClearCache(Type[]? updatedTypes)
        {
            // does not invoke
        }

        public static void UpdateApplication(Type[]? updatedTypes)
        {
            // does not invoke
        }
    }
}

#pragma warning restore CS8632 
```

### Configuration

- .NET 7 / Maui project
- Visual Studio 2022 for Windows - both amd64 and arm64

<img width="300" alt="Screenshot 2023-02-24 at 16 12 06" src="https://user-images.githubusercontent.com/13457760/221215707-e2072e6c-7b6e-46d3-ba09-7e5268e9f765.png">

**Comment by steveharter** [comment] 2023-03-13 14:27
Closing as duplicate of https://github.com/dotnet/maui/issues/4592.

**Closed by steveharter** 2023-03-13 14:27 UTC
Labels: area-System.Reflection, untriaged
