### ISSUE TITLE
ArrayPool<T>.Shared.Return does not check if array already returned

### ISSUE THREAD

**Issue by kefyru** [dotnet/runtime#75518] opened 2022-09-13 08:58 UTC
### Description

I think it is wrong behaviour.
ArrayPool should throw if we return array which already in pool, otherwise it leads to unpredictable behavior and very difficult error detection

```cs
var arr = ArrayPool<byte>.Shared.Rent(8);
ArrayPool<byte>.Shared.Return(arr);
ArrayPool<byte>.Shared.Return(arr);
var arr1 = ArrayPool<byte>.Shared.Rent(8);
var arr2 = ArrayPool<byte>.Shared.Rent(8);
if (ReferenceEquals(arr1, arr2)) throw new Exception(); // throws !!!
```

### Reproduction Steps

see description

### Expected behavior

```cs
var arr = ArrayPool<byte>.Shared.Rent(8);
ArrayPool<byte>.Shared.Return(arr); // ok
ArrayPool<byte>.Shared.Return(arr); // should throw InvalidArgumentException("array already in pool")
```

### Actual behavior

```cs
var arr = ArrayPool<byte>.Shared.Rent(8);
ArrayPool<byte>.Shared.Return(arr); // ok
ArrayPool<byte>.Shared.Return(arr); // ok!!
```

**Comment by stephentoub** [comment] 2022-09-13 10:35
Duplicate of https://github.com/dotnet/runtime/issues/7532

This would be untenably slow by default.

**Closed by stephentoub** 2022-09-13 10:35 UTC
Labels: area-System.Buffers, untriaged
