### ISSUE TITLE
[API Proposal]: Add `System.Text.RegularExpressions.ValueMatch.GroupName`

### ISSUE THREAD

**Issue by alrz** [dotnet/runtime#110383] opened 2024-12-04 03:27 UTC
### Background and motivation

Currently `EnumerateMatches` returns the match bounds but it doesn't expose any info about the capture group that the match comes from.

### API Proposal

```csharp
namespace System.Text.RegularExpressions;

public readonly ref struct ValueMatch
{
+    public string? GroupName { get; }
}
```

### API Usage

```csharp
foreach (var m in Regex.EnumerateMatches(input, @"(?<n>\d+)|(?<w>\w+)", ExplicitCatprues))  {
  if (m.GroupName == "w") {
  }
}
```

**Comment by stephentoub** [comment] 2024-12-04 03:58
I don't understand the proposed semantics here. The match being reported is for the whole expression, not a part of it.

Seems like what you're really after is all of the capture group information. That's covered by https://github.com/dotnet/runtime/issues/73223.

**Comment by stephentoub** [comment] 2024-12-06 13:07
> The current Matches method also doesn't give out this information and you should brute force each group to see there's a match.

It does.
https://learn.microsoft.com/en-us/dotnet/standard/base-types/grouping-constructs-in-regular-expressions#grouping-constructs-and-regular-expression-objects

**Comment by stephentoub** [comment] 2024-12-06 13:36
And when multiple groups capture, this property doesn't make sense.

**Comment by stephentoub** [comment] 2024-12-06 22:20
> I might be looking at it in a wrong way, what I'm trying to do is to make a `(substring)->(group name)` mapping given a regex in the form of `(?<n>\d+)|(?<w>\w+)` via EnumerableMatches, could this be done efficiently using current APIs or [#73223](https://github.com/dotnet/runtime/issues/73223)?

Today with Match/Matches, that's just a simple check per group:
```C#
using System.Text.RegularExpressions;

Match m = Regex.Match("abc", @"(?<n>\d+)|(?<w>\w+)");
if (m.Success)
{
    if (m.Groups["n"].Success)
        Console.WriteLine("matched n");
   
    if (m.Groups["w"].Success)
        Console.WriteLine("matched w");
}
```

#73223 is about coming up with a good way to represent this in a safe manner for the non-allocating EnumerateMatches.

If a `GroupName` existed with semantics of "return me the name of the first group that had a match", that's effectively what its implementation would be, just walking through the groups looking for one that was successful. It's not adding anything meaningful on top of what's already possible for Match, and its semantics would be really strange... it only makes sense in a world where only one capture group can possibly match, which is the vast minority use of capture groups.

**Comment by stephentoub** [comment] 2024-12-09 01:55
The API originally proposed in #73223 is not one we'd ship. That issue is just tracking the general desire to ship an allocation-free way of enumerating matches with full detail about captures. One possible way of doing so would be an enumerator like you allude to, though usability would be an issue with that design; there are lots of uses where folks pull out multiple named capture groups from a match, and having to enumerate to find them would be less than ideal. I suggest switching over to that issue to contribute to its design.

**Comment by stephentoub** [comment] 2024-12-09 14:14
Closing as a duplicate of #73223. Thanks.

**Closed by stephentoub** 2024-12-09 14:14 UTC
Labels: api-suggestion, area-System.Text.RegularExpressions, needs-further-triage
