### ISSUE TITLE
Strange behavior of System.ComponentModel.Int128Converter

### ISSUE THREAD

**Issue by mata007** [dotnet/runtime#109148] opened 2024-10-23 13:28 UTC
### Description

It seems to me that the class `System.ComponentModel.Int128Converter` is incorrectly implemented. It only implements conversions from strings and leaves everything else to the base class implementation (`BaseNumberConverter`). `BaseNumberConverter` works correctly as a base for converters of primitive types, but not for the new types `Int128`, `UInt128`, and `Half`.

For conversion to primitive types, `CanConvertTo` returns `true`, but `ConvertTo` throws an exception, stating that the input object does not implement `IConvertible`.

This is caused by the code below in the `BaseNumberConverter.ConvertTo` method.

```csharp
if (destinationType.IsPrimitive)
	return Convert.ChangeType(value, destinationType, culture);
```

Int128Converter by pravděpodobně měl mít vlastní implementaci CanConvertTo a ConvertTo.

### Reproduction Steps

Example of use

```csharp
using System.ComponentModel;
using System.Reflection.Metadata;

int result;
object value = (Int128)1234;
var converter = TypeDescriptor.GetConverter(value.GetType());
if (converter.CanConvertTo(typeof(int)))
    result = (int)converter.ConvertTo(value, typeof(int));
```

The last line of code throws an exception: "**System.InvalidCastException**: Object must implement IConvertible."

### Expected behavior

I would expect `Int128Converter` to allow conversions to and from primitive numeric types, since `Int128` has overloaded operators for casting to all of these types.

### Actual behavior

As I mentioned above, `Int128Converter.ConvertTo` throws an exception "**System.InvalidCastException**: Object must implement IConvertible" when converting to primitive numeric types.

**Comment by mata007** [comment] 2024-10-24 15:03
Yes, I also find it strange that Int128 doesn't implement `IConvertible` ;-)
If `Int128Converter` supports conversion to `Int32`, but `Int32Converter` doesn’t support conversion to `Int128`, it’s unfortunate, but you can work with it by acknowledging that I`nt32Converter` is historical and hasn’t been updated. If I create any custom type, it will support conversions to and from anything, but the converters of those other types won’t support it. However, if I’m working on an algorithm for converting an object to another type, I can work with that. For example:

```csharp
var valueType = value.GetType();
var converter = TypeDescriptor.GetConverter(targetType);
if (converter?.CanConvertFrom(valueType) ?? false)
         return converter.ConvertFrom(null, invariantCulture, value);

converter = TypeDescriptor.GetConverter(valueType);
if (converter?.CanConvertTo(targetType) ?? false)
         return converter.ConvertTo(null, invariantCulture, value, targetType);
```

A significant issue with the current implementation of `Int128Converter` is that **`CanConvertTo`** returns true for int32, but when performing the conversion, it throws an exception. Catching exceptions then unnecessarily slows it down.

**Comment by steveharter** [comment] 2024-10-24 16:40
Closing as duplicate of https://github.com/dotnet/runtime/issues/70104.

**Closed by steveharter** 2024-10-24 16:40 UTC
Labels: area-System.ComponentModel, untriaged
