### ISSUE TITLE
Test failure JIT/Methodical/Coverage/hole/hole.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#53216] opened 2021-05-25 07:00 UTC
Run: [runtime-coreclr crossgen2 20210523.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1152546&view=ms.vss-test-web.build-test-results-tab&runId=34841562&resultId=100618&paneView=debug)

Failed test:
```
R2R-CG2 OSX arm64 Checked @ OSX.1100.ARM64.Open

- JIT/Methodical/Coverage/hole/hole.sh

```
**Error message:**
```
/private/tmp/helix/working/A33108F2/w/BA7A0A66/e/JIT/Methodical/Coverage/hole/hole.sh: line 254: -r:/private/tmp/helix/working/A33108F2/w/BA7A0A66/e/JIT/Methodical/Coverage/hole/IL-CG2/*.dll: No such file or directory
rm: /private/tmp/helix/working/A33108F2/w/BA7A0A66/e/JIT/Methodical/Coverage/hole/hole.dll.rsp: No such file or directory
Unhandled exception. System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
---> System.NullReferenceException: Object reference not set to an instance of an object.
at ILCompiler.Sorting.Implementation.MergeSortCore5.ParallelSort(TDataStructure arrayToSort, Int32 index, Int32 length, TComparer comparer) --- End of inner exception stack trace --- at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) at System.Threading.Tasks.Task.Wait() at ILCompiler.Sorting.Implementation.MergeSortCore5.ParallelSortApi(TDataStructure arrayToSort, TComparer comparer)
at ILCompiler.DependencyAnalysis.ReadyToRun.MethodWithGCInfo.GetFixupBlob(NodeFactory factory)
at ILCompiler.DependencyAnalysis.ReadyToRun.MethodEntryPointTableNode.GetData(NodeFactory factory, Boolean relocsOnly)
at ILCompiler.DependencyAnalysis.ReadyToRunObjectWriter.EmitPortableExecutable()
at ILCompiler.ReadyToRunCodegenCompilation.Compile(String outputFile)
at ILCompiler.Program.RunSingleCompilation(Dictionary2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary2 unrootedInputFilePaths, HashSet`1 versionBubbleModulesHash, CompilerTypeSystemContext typeSystemContext)
at ILCompiler.Program.Run(String[] args)
at ILCompiler.Program.Main(String[] args)
dyld: Library not loaded: @rpath/libmscordaccore.dylib
Referenced from: /private/tmp/helix/working/A33108F2/p/dotnet-cli/shared/Microsoft.NETCore.App/6.0.0-preview.3.21201.4/createdump
Reason: image not found
/private/tmp/helix/working/A33108F2/w/BA7A0A66/e/JIT/Methodical/Coverage/hole/hole.sh: line 204: 41803 Abort trap: 6           (core dumped) $__Command

Return code:      1
Raw output file:      /private/tmp/helix/working/A33108F2/w/BA7A0A66/e/JIT/Methodical/Reports/JIT.Methodical/Coverage/hole/hole.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/private/tmp/helix/working/A33108F2/w/BA7A0A66/e/JIT/Methodical/Coverage/hole/IL-CG2/hole.dll
Response file: /private/tmp/helix/working/A33108F2/w/BA7A0A66/e/JIT/Methodical/Coverage/hole/hole.dll.rsp
/private/tmp/helix/working/A33108F2/w/BA7A0A66/e/JIT/Methodical/Coverage/hole/IL-CG2/hole.dll
-o:/private/tmp/helix/working/A33108F2/w/BA7A0A66/e/JIT/Methodical/Coverage/hole/hole.dll
-r:/tmp/helix/working/A33108F2/p/System..dll
-r:/tmp/helix/working/A33108F2/p/Microsoft..dll
-r:/tmp/helix/working/A33108F2/p/mscorlib.dll
--verify-type-and-field-layout
--targetarch:arm64
-O
Running CrossGen2:  dotnet /tmp/helix/working/A33108F2/p/crossgen2/crossgen2.dll @/private/tmp/helix/working/A33108F2/w/BA7A0A66/e/JIT/Methodical/Coverage/hole/hole.dll.rsp

Emitting R2R PE file: /private/tmp/helix/working/A33108F2/w/BA7A0A66/e/JIT/Methodical/Coverage/hole/hole.dll
Crossgen2 failed with exitcode: 134
in ReleaseLock
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/tmp/helix/working/A33108F2/p
/private/tmp/helix/working/A33108F2/w/BA7A0A66/e/JIT/Methodical/Coverage/hole/hole.sh
Expected: True
Actual:   False


Stack trace
   at JIT_Methodical._Coverage_hole_hole_._Coverage_hole_hole_sh()
```

**Comment by mangod9** [comment] 2021-05-26 04:57
This is another case of a known macos arm64 intermittent failure.

**Comment by mangod9** [comment] 2021-07-20 02:07
Dupe of #51250

**Closed by mangod9** 2021-07-20 02:07 UTC
Labels: arch-arm64, area-crossgen2-coreclr, os-mac-os-x, untriaged
