### ISSUE TITLE
[System.Text.Json] A class level attribute that configures the serialization options.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/runtime#36671] opened 2020-05-18 22:07 UTC
## Background and Motivation

Well for starters, there are already attributes in System.Text.Json for class members that needs custom converters, defines what the name in the json element to deserialize from, etc. However the options would have to be manually made. What if a class needed more options set than most?

Because of this I propose an ``JsonOptionsAttribute`` class that inherits from ``Attribute`` with attribute targets set to ``Class`` only.

## Proposed API

```diff
namespace System.Text.Json
{
+    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false)]
+    public class JsonOptionsAttribute : Attribute
+    {
+        internal JsonSerializerOptions SerializerOptions { get; private set; }
+        public JsonOptionsAttribute();
+        private JsonOptionsAttribute(JsonSerializerOptions serializerOptions);
+        // the following proxies the options in SerializerOptions class so they can be
+        // set explicitly property style in the attribute. They really manipulate the
+        // internal property SerializerOptions. This SerializerOptions would then be
+        // used internally inside of JsonSerializer.Serialize/Deserialize when it
+        // finds this attribute the class type passed in to it's TValue.
+        public bool AllowTrailingCommas {get; set; }
+        public int DefaultBufferSize { get; set; }
+        public JavaScriptEncoder? Encoder { get; set; }
+        public JsonNamingPolicy? DictionaryKeyPolicy { get; set; }
+        [Obsolete("Use DefaultIgnoreCondition instead.", error: false)]
+        [EditorBrowsable(EditorBrowsableState.Never)]
+        public bool IgnoreNullValues { get; set; }
+        public JsonIgnoreCondition DefaultIgnoreCondition { get; set; }
+        public bool IgnoreReadOnlyProperties { get; set; }
+        public int MaxDepth { get; set; }
+        public JsonNamingPolicy? PropertyNamingPolicy { get; set; }
+        public bool PropertyNameCaseInsensitive { get; set; }
+        public JsonCommentHandling ReadCommentHandling { get; set; }
+        public bool WriteIndented { get; set; }
+        public ReferenceHandling ReferenceHandling { get; set; }
+    }
}
```

## Usage Examples

```cs
[JsonOptions(WriteIndented = true, MaxDepth = 999, ReadCommentHandling = JsonCommentHandling.Skip)]
public class DiscordRoleCache
{
    [JsonPropertyName("RoleIds")]
    public List<ulong> RoleIds { get; set; } = new List<ulong>();

    public static DiscordRoleCache? FromJsonFile(string path)
        => File.Exists(path) ? FromJson(File.ReadAllText(path)) : null;

    public static DiscordRoleCache? FromJson(string json)
        => JsonSerializer.Deserialize<DiscordRoleCache>(json);

    public void ToJsonFile(string path)
        => File.WriteAllText(path, this.ToJson());

    public string ToJson()
        => JsonSerializer.Serialize(this);
}
```

And then the Serialize / Deserialize would then pick up the attribute used on the type passed in.

## Alternative Designs

I thought about naming the attribute as ``JsonSerializerOptionsAttribute`` but figured it would be too long of a name and possibly cause a confusion with consumers using the api so I shortened the name.

## Risks

I think the risk is minimal. Due to the fact there are multiple ways of configuring converters, and whatnot. There should be multiple ways of passing in the options as well.

Also most of the checking on if the type has the attribute in it can be done in methods already in the API and *should* if done right not break them at all. Would have to support all the other ways as well on converters and things on merging them in to the attribute version of options as well.

Also there might be need to somehow check for a few things as well which are:
- 1. Attribute style Converters explicitly set in the class.
- 2. Converters passed in the method from another instance of ``JsonSerializerOptions``.

And this is so then they get merged into the instance of ``JsonSerializerOptions`` from the attribute itself. That part I have yet to figure out sadly.

**Comment by layomia** [comment] 2020-06-10 00:12
Can you a provide a concrete scenario where it is useful to specify options for a type which differ from options set for other types in the (de)serialization routine? It would be good to see specifically which options would be set and why they differ.

**Comment by AraHaan** [comment] 2020-06-10 02:40
On some of my jsons (the ones written to file vs the ones not written to any file) from another api it calls. On the ones written to a file I write them indented vs the ones I exclude the writing indention options on some of those because of the fact I do not need to save some of them to a file. Also some of them I had to increase the max depth on while also abstracting away the things needed to ensure everything is converted to the type from json properly in the method bodies that gets the request responses in json form. As such I needed the options to be class level because otherwise the code could throw exemptions for specific conditions returned from that api that I would want to avoid while also not pulling in newtonsoft. In a nutshell it would not only allow easier abstactions but also allow the person making the type that it converts to to also specify what options is required to properly serialize/deserialize the data.

**Comment by JorgenLindell** [comment] 2020-11-25 17:48
Another use could be when a specific external service answers in some quirky format that you want to handle, for example a specific naming policy, or when code outside your control demands a specific naming policy on what you send.

This can of course be handled per property, but it would be simpler to put that on the class itself

**Comment by eiriktsarpalis** [comment] 2022-09-02 15:58
This would be incredibly expensive to implement, given that most of the STJ implementation assumes one `JsonSerializerOptions` instance scoped to the entire object graph. Instead of a blanket solution that scopes arbitrary `JsonSerializerOptions` instances to particular types, we should instead be looking at exposing type-level configuration points where meaningful.

Duplicate of #67097.

**Closed by eiriktsarpalis** 2022-09-02 15:58 UTC
Labels: api-suggestion, area-System.Text.Json, wishlist

**Comment by AraHaan** [comment] 2022-09-02 16:44
But isn't https://github.com/dotnet/runtime/issues/67097 a duplicate of this because this is older? @eiriktsarpalis

**Comment by eiriktsarpalis** [comment] 2022-09-02 16:54
If A is a duplicate of B, then it follows that B is a duplicate of A. The other issue has been referenced for archiving purposes and is in no way attributing dibs to the proposal :-)
