### ISSUE TITLE
.NET7 RC2 PrintDocument exception.

### ISSUE THREAD

**Issue by MiyamuraMiyako** [dotnet/runtime#77340] opened 2022-10-22 16:42 UTC
### Description

.NET7(x86) PrintDocument will throw AccessViolationException when execute to Print, x64 is ok.

### Reproduction Steps

1. Create new .net7 project and set to x86.
2. 
3. Use below code :
```c#
PrintDocument pd = new PrintDocument();
pd.PrinterSettings.PrinterName = "Microsoft Print to PDF";
pd.PrintController = new StandardPrintController();

pd.PrintPage += (sender, e) => { };
pd.Print();
```

4. Start program and will throw `System.AccessViolationException:“Attempted to read or write protected memory. This is often an indication that other memory is corrupt.”`

### Expected behavior

Print normally.

### Actual behavior

Throw AccessViolationException when execute to Print.

### Known Workarounds

Downgrade to .NET6 sdk and packages.

**Comment by jkotas** [comment] 2022-10-22 18:59
Thank you for reporting the issue. It is duplicate of https://github.com/dotnet/runtime/issues/76538. The fix will be included in .NET 7.

**Closed by jkotas** 2022-10-22 18:59 UTC
Labels: area-System.Drawing, untriaged
