### ISSUE TITLE
[.NET 5] Issue with SocketsHttpHandler & TLS 1.3

### ISSUE THREAD

**Issue by Glutwolf** [dotnet/runtime#58439] opened 2021-08-31 13:09 UTC
Hello there! I am currently working on a network protocol (stack).

### Description

One of the protocols in the stack is placed on top of the WebSocket protocol ([rfc6455](https://datatracker.ietf.org/doc/html/rfc6455)) and mandatorily requires TLS 1.3 ([rfc8446](https://datatracker.ietf.org/doc/html/rfc8446)). Unfortunately, the class `System.Net.WebSockets.ClientWebSocket` does not allow you to specify the TLS version explicitly, so I took the class [`System.Net.WebSockets.WebSocketHandle`](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.WebSockets.Client/src/System/Net/WebSockets/WebSocketHandle.Managed.cs) as a reference and created my own version, adapted to my network protocol stack.

During connection establishement, the following code is called:

```cs
SocketsHttpHandler socketsHttpHandler = new()
{
    SslOptions = new()
    {
        EnabledSslProtocols = SslProtocols.Tls13,
        CertificateRevocationCheckMode = X509RevocationMode.NoCheck,
        EncryptionPolicy = EncryptionPolicy.RequireEncryption,
        RemoteCertificateValidationCallback = (sender, certificate, chain, sslPolicyErrors) =>
        {
            return true;
        },
    },
};

HttpMessageInvoker httpMessageInvoker = new(socketsHttpHandler);
HttpResponseMessage httpResponseMessage = await httpMessageInvoker.SendAsync(httpRequestMessage, CancellationToken.None);
```

As soon as the method in the last line is called, the following exception occurs:

```
The SSL connection could not be established, see inner exception.
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
```

```
Authentication failed, see inner exception.
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
```

```
Die lokale Sicherheitsautorität (LSA) ist nicht erreichbar.
```

The last exception can be translated to "_The Local Security Authority cannot be contacted._".

If you now look at the connection establishment in Wireshark, you will notice that the connection gets closed during or at the end of the TLS 1.3 handshake. In order to decrypt the encrypted connection, I additionally use [mitmproxy v7.0](https://mitmproxy.org/) listening on port 8080.

![1](https://user-images.githubusercontent.com/17489620/131505516-67136359-49c6-459d-a44b-ab851a6b7f01.png)

Surprisingly, the connection gets not closed if the `EnabledSslProtocols` property is not set, even though my WebSocket server exclusively uses TLS 1.3.

![2](https://user-images.githubusercontent.com/17489620/131505536-b60147f8-82ac-4377-b002-d2ab423e5327.png)

In order to test the communication, I implemented a WebSocket server listening on port 5001 with the following code:

```cs
public class Program
{
    public static void Main(string[] args)
    {
        CreateHostBuilder(args).Build().Run();
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureWebHostDefaults(webHostBuilder =>
            {
                webHostBuilder.UseKestrel(kestrelServerOptions =>
                {
                    kestrelServerOptions.ConfigureEndpointDefaults(listenOptions =>
                    {
                        HttpsConnectionAdapterOptions httpsConnectionAdapterOptions = new();
                        httpsConnectionAdapterOptions.SslProtocols = SslProtocols.Tls13;
                        httpsConnectionAdapterOptions.CheckCertificateRevocation = false;
                        httpsConnectionAdapterOptions.ClientCertificateMode = ClientCertificateMode.NoCertificate;
                        httpsConnectionAdapterOptions.AllowAnyClientCertificate();

                        using (X509Store x509Store = new (StoreName.My, StoreLocation.CurrentUser))
                        {
                            x509Store.Open(OpenFlags.ReadOnly);

                            X509Certificate2Collection x509Certificate2Collection = x509Store.Certificates.Find(X509FindType.FindByThumbprint, "<THUMBPRINT>", true);

                            X509Certificate2 x509Certificate2 = x509Certificate2Collection.OfType<X509Certificate2>().Single();

                            httpsConnectionAdapterOptions.ServerCertificate = x509Certificate2;

                            x509Store.Close();
                        }                       

                        listenOptions.UseHttps(httpsConnectionAdapterOptions);
                        listenOptions.Protocols = HttpProtocols.Http1AndHttp2;
                    });
                });
                webHostBuilder.UseStartup<Startup>();
            });
}
```

In order to get a self-signed certificate for my WebSocket server I've used the following command:

`New-SelfSignedCertificate -DnsName "localhost" -CertStoreLocation "Cert:\CurrentUser\My" -KeyAlgorithm "secP256r1"`

However, if I use the following command, the situation gets even worse:

`New-SelfSignedCertificate -DnsName "localhost" -CertStoreLocation "Cert:\CurrentUser\My" -KeyAlgorithm "secP521r1"`

If I use this certificate, the WebSocket server throws the same exception as the client:

```
fail: Microsoft.AspNetCore.Server.Kestrel[0]
      Unhandled exception while processing 0HMBCFT4TS9DC.
      System.ComponentModel.Win32Exception (0x80090304): Die lokale Sicherheitsautorität (LSA) ist nicht erreichbar.
         at System.Net.SSPIWrapper.AcquireCredentialsHandle(ISSPIInterface secModule, String package, CredentialUse intent, SCH_CREDENTIALS* scc)
         at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCH_CREDENTIALS* secureCredential)
         at System.Net.Security.SslStreamPal.AcquireCredentialsHandleSchCredentials(X509Certificate certificate, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
         at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslStreamCertificateContext certificateContext, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
         at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint)
         at System.Net.Security.SecureChannel.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)
         at System.Net.Security.SecureChannel.NextMessage(ReadOnlySpan`1 incomingBuffer)
         at System.Net.Security.SslStream.ProcessBlob(Int32 frameSize)
         at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
         at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelConnection`1.ExecuteAsync()
```

Unfortunately, I don't know what to do from this point on. I suspect that it could be a bug. Maybe someone could take a look at it and push me in the right direction.

### Configuration

.NET SDK version: 5.0.400
OS version: Windows 21H1 (Build 19043.1165)
Architecture: x64

### Other information

Entries added to the registry in order to enable TLS 1.3:

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Client]
"DisabledByDefault"=dword:00000000
"Enabled"=dword:00000001

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Server]
"DisabledByDefault"=dword:00000000
"Enabled"=dword:00000001
```

**Comment by vcsjones** [comment] 2021-08-31 16:04
>  OS version: Windows 21H1 (Build 19043.1165)

I reported pretty much exactly this in https://github.com/dotnet/runtime/issues/53537 and determined that this is an issue in Windows 21H1. 

It seems that TLS 1.3 [is not supported][1] in 21H1 if the _only_ enabled protocol is TLS 1.3. I was not able to reproduce this in Windows Server 2022.

[1]: https://docs.microsoft.com/en-us/windows/win32/secauthn/protocols-in-tls-ssl--schannel-ssp-

**Comment by wfurt** [comment] 2021-08-31 16:09
It would be great if you can try it on Win11 or Server 2022. If we can reproduce on supported OS I can take it back to Windows team.

**Comment by wfurt** [comment] 2021-08-31 16:10
https://docs.microsoft.com/en-us/windows/win32/secauthn/protocols-in-tls-ssl--schannel-ssp- 21H1 was added as not-supported (after #53537 was created)

**Comment by karelz** [comment] 2021-09-02 16:24
Triage: If it fails on Win11 or Server 2022, we should investigate. It is unsupported scenario on lower OS versions.

@Glutwolf will you be able to test your scenario on one of those OS versions?

**Comment by Glutwolf** [comment] 2021-09-03 07:47
@vcsjones Thanks for pointing me to the issue you've created, I've searched half the internet for people with a similar problem.

@wfurt @karelz I ran my code again on _Windows 11 Insider Preview (Dev Channel) - Build 22000.132_ (this was the edition I've downloaded, see specific version below) and noticed that it only works partially.

My code works with the self-signed certificate I've created with this command:

`New-SelfSignedCertificate -DnsName "localhost" -CertStoreLocation "Cert:\CurrentUser\My" -KeyAlgorithm "secP256r1"`

My code DOES NOT work with the self-signed certificate I've created with this command:

`New-SelfSignedCertificate -DnsName "localhost" -CertStoreLocation "Cert:\CurrentUser\My" -KeyAlgorithm "secP521r1"`

So my WebSocket server is still throwing the same exception as before if I choose the curve _secP521r1_.

OS version: Windows 21H2 (Build 22000.176)
Architecture: x64
.NET SDK version: 5.0.400

**Comment by karelz** [comment] 2021-09-03 08:47
@wfurt if it is certificate specific, I assume we should ask Schannel to take a look. What kind of logs will they need?

**Comment by vcsjones** [comment] 2021-09-03 11:49
> So my WebSocket server is still throwing the same exception as before if I choose the curve secP521r1.

P521 is a somewhat rare choice for an HTTPS certificate and not all platforms support it. I don't believe all Apple platforms support it for HTTPS, either. I'm not aware of documentation for SChannel however.

Also public CAs are not allowed to issue p521 certificates, only p256 and p384.

**Comment by wfurt** [comment] 2021-09-03 18:00
According to https://docs.microsoft.com/en-us/windows/win32/secauthn/tls-elliptic-curves-in-windows-10-1607-and-later `secP521r1` should be supported but not enabled by default.  Would expect one can verify that with TLS 1.2 to see if this is culprit or not.

**Comment by Glutwolf** [comment] 2021-09-06 06:40
> P521 is a somewhat rare choice for an HTTPS certificate and not all platforms support it. I don't believe all Apple platforms support it for HTTPS, either. I'm not aware of documentation for SChannel however.
> 
> Also public CAs are not allowed to issue p521 certificates, only p256 and p384.

@vcsjones Thanks for the information, do you have any sources for these statements? I have not read anywhere that said parameters are rare or that public CAs are not allowed to issue p521 certificates.

Even in [rfc8446](https://datatracker.ietf.org/doc/html/rfc8446) there are a few places, e.g. [7.4.2. Elliptic Curve Diffie-Hellman](https://datatracker.ietf.org/doc/html/rfc8446#section-7.4.2), where secp521r1 is mentioned in the context of ECDH calculations. So from my point of view, my approach was legitimate. However, I would be happy if you could give me some more details about this.

> According to https://docs.microsoft.com/en-us/windows/win32/secauthn/tls-elliptic-curves-in-windows-10-1607-and-later `secP521r1` should be supported but not enabled by default. Would expect one can verify that with TLS 1.2 to see if this is culprit or not.

@wfurt The document you mentioned says that secP256r1 should be disabled by default, so the usage of the certificate I created with that curve should also result in errors, but it doesn't. Also the output of the cmdlet `Get-TlsEccCurve` confirms that secP256r1 is disabled on my computer.

```
PS C:\Windows\System32> Get-TlsEccCurve
curve25519
NistP256
NistP384
```

However, in Wireshark I could see that my WebSocket client says that it supports x25519, secp256r1 and secp384r1. Maybe the two types of curves (NistP & secP) are interchangeable in some way, so that the whole process works correctly. I don't know.

In the meantime, I've tried to activate secP521r1 by executing the cmdlet `Enable-TlsEccCurve secP521r1` on my Windows 11 system and then checked the result with the cmdlet `Get-TlsEccCurve`. Here's the result:

In the meantime, I tried to enable secP521r1 by executing the `Enable-TlsEccCurve secP521r1` cmdlet on my Windows 11 system and then using the `Get-TlsEccCurve` cmdlet to check the result:

```
PS C:\Windows\System32> Get-TlsEccCurve
curve25519
NistP256
NistP384
secP521r1
```

The secP521r1 curve has been successfully activated and everything works now.

It looks like this is the solution to the problem. However, the error messages could be a bit more specific.

Also, the fact that NistP256 and secP256r1 are somehow interchangeable seems a bit strange to me. Maybe someone could shed some light on this.

**Comment by vcsjones** [comment] 2021-09-06 15:01
> Also, the fact that NistP256 and secP256r1 are somehow interchangeable seems a bit strange to me. Maybe someone could shed some light on this.

Yeah, there are multiple identifiers for the same EC curve. This is the unfortunate result of multiple standards bodies all coming up with different names for the same thing.

https://github.com/dotnet/runtime/blob/32df6797cb5704edb589250f8bfeae8c275e9994/src/libraries/System.Security.Cryptography.Encoding/src/Internal/Cryptography/OidLookup.cs#L212-L214

>  do you have any sources for these statements?

P-521 has been discussed a lot in the Web PKI community, for example in https://groups.google.com/g/mozilla.dev.security.policy/c/7O34-DmZeC8/m/lZjzmOEuCQAJ.

**Comment by wfurt** [comment] 2021-09-08 16:34
That link was about enabling EC for Schannel e.g. TLS. It may work for some other operations - like crypto primitives and certificates. And I agree about the messages but .NET works with what we get from OS e.g. error code we map to user visible text. 

It seems like you are set and this can be closed @Glutwolf ?

**Comment by karelz** [comment] 2021-09-09 16:10
Triage: Looks like it was disabled in the OS and it is by design. Closing.
Feel free to reopen if it is not the case. Thanks!

**Closed by karelz** 2021-09-09 16:10 UTC
Labels: area-System.Net.Http, needs more info, untriaged

**Comment by Glutwolf** [comment] 2021-09-10 05:41
Yes, my problem is solved and the issue can be closed.
@wfurt @vcsjones @karelz Thanks for your help!

### Summary
- Support from the SCHANNEL SSP for TLS 1.3 on Windows starts with _Windows 11_ and _Windows Server 2022_
(see https://docs.microsoft.com/en-us/windows/win32/secauthn/protocols-in-tls-ssl--schannel-ssp-)
- Some curves have to be activated on Windows (`Get-TlsEccCurve` & `Enable-TlsEccCurve`) before they can be used
(see https://docs.microsoft.com/en-us/windows/win32/secauthn/tls-elliptic-curves-in-windows-10-1607-and-later)
