### ISSUE TITLE
Size of cache growing even when the CacheMemoryLimitMegabytes is 2 mb and Sliding expiration is 2 sec

### ISSUE THREAD

**Issue by harshikesh** [dotnet/runtime#35009] opened 2020-04-15 16:31 UTC
The object size of memory cache becomes huge and gc runs heavily. 
The below is the configuration. Still it can reach to 1 gb or more.
![s1](https://user-images.githubusercontent.com/4974878/79362830-b2b6c100-7f64-11ea-9405-1a5e17ab767d.JPG)
![s2](https://user-images.githubusercontent.com/4974878/79362899-ca8e4500-7f64-11ea-8b54-da424868fc45.JPG)

```

TimeSpan expirationTime = TimeSpan.FromSeconds(1);
            CacheItemPolicy cachingPolicy = new CacheItemPolicy()
            {
                SlidingExpiration = expirationTime
            };

            NameValueCollection config = null;

                config = new NameValueCollection
                    {
                        { "CacheMemoryLimitMegabytes", "2" },
                         { "physicalMemoryLimitPercentage", "1" }
                    };




            Program.cache = new MemoryCache("TestCache", config);
```

area-System.Runtime.Caching

**Comment by harshikesh** [comment] 2020-04-15 16:40
> I couldn't figure out the best area label to add to this issue. Please help me learn by adding exactly one [area label](https://github.com/dotnet/runtime/blob/master/docs/area-owners.md).

**Comment by harshikesh** [comment] 2020-04-25 14:50
@StephenMolloy  @HongGit  @stephentoub

**Comment by HongGit** [comment] 2020-04-30 22:48
Duplicate of #1427

**Closed by HongGit** 2020-04-30 22:48 UTC
Labels: area-System.Runtime.Caching, untriaged
