### ISSUE TITLE
Consider tracking JSON path while deserializing JsonElement to return better JsonException

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/runtime#32359] opened 2020-02-15 02:17 UTC
We should only do this if it doesn't regress `JsonElement` performance noticably.

https://github.com/dotnet/runtime/blob/d4b06b1a9e3c56e343c42efad2211c04c196a0cf/src/libraries/System.Text.Json/tests/Serialization/ExceptionTests.cs#L366-L380

cc @steveharter

**Comment by layomia** [comment] 2020-02-21 23:08
Closing as duplicate of https://github.com/dotnet/runtime/issues/29715.

**Closed by layomia** 2020-02-21 23:08 UTC
Labels: area-System.Text.Json
