### ISSUE TITLE
Test failure JIT/Regression/JitBlue/Runtime_76194/Runtime_76194/Runtime_76194.sh

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#78791] opened 2022-11-24 01:20 UTC
Failed in Run: [runtime-coreclr outerloop 20221123.5](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=92257)
 
 **Failed tests:**
 ```
coreclr Linux arm Checked @ (Alpine.314.Arm32.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm32v7

- JIT/Regression/JitBlue/Runtime_76194/Runtime_76194/Runtime_76194.sh

coreclr Linux arm Checked no_tiered_compilation @ (Alpine.314.Arm32.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm32v7

- JIT/Regression/JitBlue/Runtime_76194/Runtime_76194/Runtime_76194.sh
 ```
 
 **Error message:**
 ```
 Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Runtime_76194.Read1(Byte* location)
   at Runtime_76194.Main()
[createdump] waitpid() returned successfully (wstatus 00000000)
/root/helix/work/workitem/e/JIT/Regression/JitBlue/Runtime_76194/Runtime_76194/Runtime_76194.sh: line 426:  7743 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.Regression/JitBlue/Runtime_76194/Runtime_76194/Runtime_76194.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false Runtime_76194.dll ''
[createdump] Gathering state for process 7743 corerun
[createdump] Crashing thread 00001e3f signal 00000006
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.7743.dmp
[createdump] Written 32780288 bytes (8003 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 2683ms
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/e/JIT/Regression/JitBlue/Runtime_76194/Runtime_76194/Runtime_76194.sh
Expected: True
Actual:   False
 ```
 
 **Stack trace:**
 ```
    at JIT_Regression._JitBlue_Runtime_76194_Runtime_76194_Runtime_76194_._JitBlue_Runtime_76194_Runtime_76194_Runtime_76194_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
 ```
Queued | OS | Arch | Column1
-- | -- | -- | --
2022-11-23T19:34:25.51Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=92257&view=ms.vss-test-web.build-test-results-tab&runId=1943948&resultId=119815&paneView=debug)
2022-11-23T19:34:24.361Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=92257&view=ms.vss-test-web.build-test-results-tab&runId=1943946&resultId=120125&paneView=debug)
2022-11-23T10:49:52.692Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=91836&view=ms.vss-test-web.build-test-results-tab&runId=1934898&resultId=120146&paneView=debug)
2022-11-23T10:49:51.219Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=91836&view=ms.vss-test-web.build-test-results-tab&runId=1934900&resultId=114839&paneView=debug)
2022-11-23T02:33:26.691Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=91616&view=ms.vss-test-web.build-test-results-tab&runId=1930156&resultId=114929&paneView=debug)
2022-11-23T02:33:25.157Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=91616&view=ms.vss-test-web.build-test-results-tab&runId=1930154&resultId=120011&paneView=debug)
<details>
<summary>More failures</summary>

Queued | OS | Arch | Column1
-- | -- | -- | --
2022-11-22T19:40:53.184Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=91123&view=ms.vss-test-web.build-test-results-tab&runId=1921496&resultId=119632&paneView=debug)
2022-11-22T19:40:52.184Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=91123&view=ms.vss-test-web.build-test-results-tab&runId=1921498&resultId=114881&paneView=debug)
2022-11-22T10:33:13.22Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=90661&view=ms.vss-test-web.build-test-results-tab&runId=1910694&resultId=114881&paneView=debug)
2022-11-22T10:33:11.607Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=90661&view=ms.vss-test-web.build-test-results-tab&runId=1910692&resultId=119893&paneView=debug)
2022-11-22T02:34:10.445Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=90356&view=ms.vss-test-web.build-test-results-tab&runId=1906238&resultId=109185&paneView=debug)
2022-11-22T02:33:50.594Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=90356&view=ms.vss-test-web.build-test-results-tab&runId=1906236&resultId=120195&paneView=debug)
2022-11-21T10:41:48.799Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=89373&view=ms.vss-test-web.build-test-results-tab&runId=1883212&resultId=119728&paneView=debug)
2022-11-21T10:41:47.688Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=89373&view=ms.vss-test-web.build-test-results-tab&runId=1883214&resultId=114802&paneView=debug)
2022-11-21T02:52:25.893Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=89243&view=ms.vss-test-web.build-test-results-tab&runId=1878184&resultId=114528&paneView=debug)
2022-11-21T02:52:24.827Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=89243&view=ms.vss-test-web.build-test-results-tab&runId=1878182&resultId=119637&paneView=debug)
2022-11-20T19:29:53.049Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=89094&view=ms.vss-test-web.build-test-results-tab&runId=1875392&resultId=119882&paneView=debug)
2022-11-20T19:29:51.748Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=89094&view=ms.vss-test-web.build-test-results-tab&runId=1875390&resultId=120063&paneView=debug)
2022-11-20T10:30:52.172Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=88961&view=ms.vss-test-web.build-test-results-tab&runId=1872416&resultId=114884&paneView=debug)
2022-11-20T10:30:51.047Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=88961&view=ms.vss-test-web.build-test-results-tab&runId=1872414&resultId=120185&paneView=debug)
2022-11-20T02:39:36.244Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=88829&view=ms.vss-test-web.build-test-results-tab&runId=1869564&resultId=113255&paneView=debug)
2022-11-20T02:39:35.03Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=88829&view=ms.vss-test-web.build-test-results-tab&runId=1869562&resultId=120052&paneView=debug)
2022-11-19T20:02:46.679Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=88688&view=ms.vss-test-web.build-test-results-tab&runId=1867076&resultId=114070&paneView=debug)
2022-11-19T20:02:45.52Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=88688&view=ms.vss-test-web.build-test-results-tab&runId=1867074&resultId=119673&paneView=debug)
2022-11-19T10:46:04.333Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=88502&view=ms.vss-test-web.build-test-results-tab&runId=1862798&resultId=119884&paneView=debug)
2022-11-19T10:46:03.246Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=88502&view=ms.vss-test-web.build-test-results-tab&runId=1862802&resultId=114736&paneView=debug)
2022-11-19T02:58:24.231Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=88388&view=ms.vss-test-web.build-test-results-tab&runId=1860810&resultId=113716&paneView=debug)
2022-11-19T02:58:23.041Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=88388&view=ms.vss-test-web.build-test-results-tab&runId=1860808&resultId=120112&paneView=debug)
2022-11-18T11:13:36.604Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=87546&view=ms.vss-test-web.build-test-results-tab&runId=1836762&resultId=112776&paneView=debug)
2022-11-18T11:13:35.493Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=87546&view=ms.vss-test-web.build-test-results-tab&runId=1836760&resultId=119747&paneView=debug)
2022-11-17T20:16:47.637Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=86808&view=ms.vss-test-web.build-test-results-tab&runId=1822518&resultId=114340&paneView=debug)
2022-11-17T20:16:46.762Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr outerloop Checked](https://dev.azure.com/dnceng/public/_build/results?buildId=86808&view=ms.vss-test-web.build-test-results-tab&runId=1822516&resultId=119955&paneView=debug)
</details>

**Comment by jkotas** [comment] 2022-11-24 04:23
Duplicate of https://github.com/dotnet/runtime/issues/78758

**Closed by jkotas** 2022-11-24 04:23 UTC
Labels: os-linux, untriaged, blocking-outerloop
