### ISSUE TITLE
Add ability to detect if a service is registered in the DI container

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#53919] opened 2021-06-09 06:16 UTC
## Background and Motivation

We have a couple of scenarios where various components want to detect if a type is a registered/resolvable in the DI container without actually resolving the service (as this has side effects). See the following issues:
- https://github.com/dotnet/runtime/issues/46132 - This would allow the logic in ActivatorUtilities to pick the constructor based on what services are registered in the container. Today the logic is pretty broken.
- https://github.com/dotnet/aspnetcore/pull/32737 - Minimal APIs want to be able to differentiate arguments to the method that are resolvable as services without explicit attributes.
- https://github.com/microsoft/reverse-proxy/pull/915/files#diff-1d82d5e829d3ed9881a0e402a311fec7cca647fcf40d878e8f26d9886ab7ae9fR62 YARP - Wanted to enable diagnostic features based on what services where registered.

This would be an optional service that could be implemented by a DI container implementation similar to [ISupportRequiredService](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ISupportRequiredService.cs). Since it is optional, consumers need to decide what to do if the interface isn't implemented.

## Proposed API

```diff
namespace Microsoft.Extensions.DependencyInjection
{
+    public interface ISupportServiceQuery
+    {
+        bool IsService(Type serviceType);
+    }
}
```

## Usage Examples

``` C#
bool? HasServiceType<T>(IServiceProvider sp)
{
    return sp.GetService<ISupportServiceQuery>()?.IsService(typeof(T));
}

HasServiceType<TodoDbContext>();
```

- Open generics supported by the container will always return true. e.g.:

```C#
void Tests(IServiceProvider sp)
{
    // Assuming the container supports Func<T> and IEnumerable<T>
    var supportsQuery = sp.GetRequiredService<ISupportServiceQuery>();
    Assert.True(supportsQuery.IsService(typeof(Func<IFoo>)));
    Assert.True(supportsQuery.IsService(typeof(IEnumerable<IFoo>)));
}
```

Null means we can't tell if the service is registered since `ISupportServiceQuery` is optional.

## Risks

None

**DI council:** @alexmg @tillig @pakrym @ENikS @ipjohnson @dadhi @seesharper @jeremydmiller @alistairjevans 

@halter73 @DamianEdwards

**Comment by dadhi** [comment] 2021-06-09 07:01
@davidfowl

> Open generics supported by the container will always return true.

Why? Because presumably most of the libraries here support the functionality (DryIoc [does](https://github.com/dadhi/DryIoc/blob/master/docs/DryIoc.Docs/RegisterResolve.md#isregistered)) and the libraries also support the generics.

**Comment by davidfowl** [comment] 2021-06-09 07:05
I think that was just meant to be a bullet point that clarified "resolvable" vs "registered". If the container natively supports `Func<>` then any `Func<T>` would return true right?

**Comment by dadhi** [comment] 2021-06-09 07:07
> Func<T> would return true right?

I think, no. Funny enough that the
most containers may implement `IsResolvable` as `TryResolve<Func<X>>() != null`

**Comment by davidfowl** [comment] 2021-06-09 07:12
> I think, no.

This is something we need to resolve. If I ask about any `IEnumerable<T>` I think it should return true for example. Otherwise it basically doesn't work for open generics. Same with `IOptions<T>`  in the case of generic host based apps.

> Funny enough that the
most containers may implement IsResolvable as TryResolve<Func<X>>() != null

I hope not as that would lead to the side effects that caused this to be created in the first place. If you actually resolve the instance 
then you have to worry about disposal (and async disposal).

**Comment by dadhi** [comment] 2021-06-09 07:25
Ok, just to be on the same page. And I will talk just about DryIoc.

- For open-generics you may only ask if they registered or not, because you cannot actually resolve something open.
- The `IEnumerable<>` and `Func<>`, etc. are wrappers in the DryIoc terms, and you may check if the specific wrapper is registered.
- Given the closed type X, you may ask if `IsRegistered<X>()` which does not automatically mean the X is resolvable (missing dependency, wrong lifestyle, etc.).
-  To check if X is resolvable without creating the instance the simplest robust way (closest  to how container will actually resolve things) will be `Resolve<Func<X>>(ifUnresolved.ReturnDefault) != null`.

**Comment by davidfowl** [comment] 2021-06-09 08:01
Great! That sounds good. I think this is a good distinction to flesh out:

> To check if X is resolvable without creating the instance the simplest robust way (closest to how container will actually resolve things) will be Resolve<Func<X>>(ifUnresolved.ReturnDefault) != null.

Right, I think this is what the API needs to be. It doesn't actually check if the service will resolve if you call GetService as that might fail for other reasons. I like the idea that it'll tell you if you *can* resolve the service at all. 

Spec tests

### Basic Service

```C#
var services = new ServiceCollection();
services.AddSingleton<IFoo, Foo>();
var serviceProvider = BuildServiceProvider(services); // Assume this builds a specific implementation

var supportsQuery = serviceProvider.GetRequiredService<ISupportServiceQuery>();

Assert.True(supportsQuery.CanGetService(typeof(IFoo)));
Assert.False(supportsQuery.CanGetService(typeof(Foo)));

interface IFoo { }
class Foo : IFoo { }
````


### Open generic 

```C#
var services = new ServiceCollection();
services.AddSingleton(typeof(IOptions<>), typeof(Options<>));
var serviceProvider = BuildServiceProvider(services); // Assume this builds a specific implementation

var supportsQuery = serviceProvider.GetRequiredService<ISupportServiceQuery>();

Assert.True(supportsQuery .CanGetService(typeof(IOptions<>)));
````

### Closed generic 

```C#
var services = new ServiceCollection();
services.AddSingleton(typeof(IOptions<>), typeof(Options<>));
var serviceProvider = BuildServiceProvider(services); // Assume this builds a specific implementation

var supportsQuery = serviceProvider.GetRequiredService<ISupportServiceQuery>();

// Closed generic test with a wrapper
Assert.True(supportsQuery .CanGetService(typeof(IOptions<MyOptions>)));

class MyOptions { }
````

**Comment by alistairjevans** [comment] 2021-06-09 09:07
From an Autofac perspective, there are a couple of things to consider about generics (anything not generic-based is fine).

### Querying for Open Generics

When a user calls `RegisterGeneric` on their container, we do not add an actual registration, we add a 'registration source' that _may_ be able to provide a given service when it is resolved. 

When someone interrogates the component registry to ask if a service is registered, we check whether we have anything (either a direct registration, or a registration source) that can provide that service.

Nothing can provide an instance of an open generic, so a call to `IsRegistered` for the open generic `IOptions<>` will always return false, unlike querying the closed generic `IOptions<MyOptions>`, which will return true if `Options<>` was appropriately registered in the container.

```csharp
 var builder = new ContainerBuilder();

builder.RegisterGeneric(typeof(Options<>)).As(typeof(IOptions<>));

var container = builder.Build();

Assert.False(container.ComponentRegistry.IsRegistered(new TypedService(typeof(IOptions<>))));

Assert.True(container.ComponentRegistry.IsRegistered(new TypedService(typeof(IOptions<MyOptions>))));
```

I'd be interested to understand the use-case where someone needs to check for the open generic at runtime rather than the closed generic they actually may need to resolve.

### Wrappers

For `Func<>` and other factory wrappers, similar rules are followed as for regular generics, in that we will only return `true` for `IsRegistered` checks if the registry knows that something can provide that service:

```csharp
var builder = new ContainerBuilder();

// ExampleComponent registered, but not ExampleComponent2.
builder.RegisterInstance(new ExampleComponent());

var container = builder.Build();

// Factory for ExampleComponent? No problem, you registered ExampleComponent already.
Assert.True(container.ComponentRegistry.IsRegistered(new TypedService(typeof(Func<ExampleComponent>))));

// Not registered ExampleComponent2, can't give you a factory for it.
Assert.False(container.ComponentRegistry.IsRegistered(new TypedService(typeof(Func<ExampleComponent2>))));

// As already stated, you can't resolve an open generic, so IsRegistered will be false
Assert.False(container.ComponentRegistry.IsRegistered(new TypedService(typeof(Func<>))));
```

`IEnumerable<>` is different in that if there are no registrations for a service, you just get an empty set; so Autofac will return true for any closed `IEnumerable<>`:

```csharp
var builder = new ContainerBuilder();

builder.RegisterInstance(new ExampleComponent());

var container = builder.Build();

// Doesn't matter whether you registered a component or not.
Assert.True(container.ComponentRegistry.IsRegistered(new TypedService(typeof(IEnumerable<ExampleComponent>))));
Assert.True(container.ComponentRegistry.IsRegistered(new TypedService(typeof(IEnumerable<ExampleComponent2>))));

// Still can't check IsRegistered for something that isn't ever resolvable.
Assert.False(container.ComponentRegistry.IsRegistered(new TypedService(typeof(IEnumerable<>))));
```

### Constrained Generics

Something that hasn't been mentioned yet is constrained generics; Autofac will respect generic constraints when checking if a service is registered:

```csharp
var builder = new ContainerBuilder();

builder.RegisterGeneric(typeof(GenericComponent<>)).As(typeof(IGenericService<>));

var container = builder.Build();

// Can provide, generic constraints are valid.
Assert.True(container.ComponentRegistry.IsRegistered(new TypedService(typeof(IGenericService<int>))));

// Nothing provides IGenericService<T> that matches the constraints.
Assert.False(container.ComponentRegistry.IsRegistered(new TypedService(typeof(IGenericService<string>))));
```

**Comment by jeremydmiller** [comment] 2021-06-09 13:05
You might want semantically different methods for IsRegistered(service type) and the “can resolve” method to differentiate between being explicitly registered and the container being able to “figure out” how to resolve the service type in some cases.

And rather than do this, can you instead use some kind of nullify service registration as a stand in instead of doing the branching logic based on container registrations? That’s always my recommendation to users over relying on magic constructor selection logic

**Comment by eerhardt** [comment] 2021-06-09 14:38
> return sp.GetService<ISupportServiceQuery>()?.CanGetService(typeof(T));

Why this pattern vs. 

```C#
return (sp as ISupportServiceQuery)?.CanGetService(typeof(T));
```

It seems like the SerivceProvider should be the one answering the question - and not some service that I get from the ServiceProvider.

**Comment by ENikS** [comment] 2021-06-09 16:05
`CanGetService(typeof(T))` can get complicated really quick. For example:
* Is it enough for the container to check if it is POCO type and assume it could be resolved?
* Should it check if there are any public constructor?
* Can any of the constructors be instantiated (satisfied with dependencies)?
* How about now, after something else has been registered?

Where do you draw the line and define minimum criteria?

**Comment by dadhi** [comment] 2021-06-09 16:10
ˋˋˋcs
sp.GetService<ISupportRequiredService>()?.CanGetService(typeof(T));
```
This pattern provides a better composability. I may not want to implement the feature services on the core container because they require additional package dependency.

**Comment by alistairjevans** [comment] 2021-06-09 16:42
I would probably echo @eerhardt around adding the functionality in the same way as `ISupportRequiredService`, where the `IServiceProvider` is extended with additional interfaces.

At a conceptual level, if a component other than the `IServiceProvider` itself is responsible for stating whether that `IServiceProvider` can provide a service, that feels like a strange disconnect to me. It would be possible for someone to register their own `ISupportServiceQuery` service override, and give very strange results to the caller that don't match up with the service provider at all.

On the package dependency note, for Autofac we already have a separate library with the MS DI package dependency, and we could add an `ISupportServiceQuery` to our existing `AutofacServiceProvider` implementation fairly trivially.

**Comment by davidfowl** [comment] 2021-06-09 16:47
@alistairjevans Thanks for that, I didn't consider the constrained generics scenario. I will add that to the tests above. Also I don't have a concrete scenario for open generics, I'm fine if they return false. I wanted to put this to the group to see what the consensus was.

@jeremydmiller 

> You might want semantically different methods for IsRegistered(service type) and the “can resolve” method to differentiate between being explicitly registered and the container being able to “figure out” how to resolve the service type in some cases.

Maybe. I think the only difference is with respect to the wrappers/factories whatever you want to call the open generic "things" that containers can manifest on the fly. I'm not sure that difference is observable in the scenarios I mentioned above, at least, I don't have a scenario where the differentiation is needed.

> And rather than do this, can you instead use some kind of nullify service registration as a stand in instead of doing the branching logic based on container registrations? That’s always my recommendation to users over relying on magic constructor selection logic

This doesn't work for the scenarios listed above. They are from framework code that is trying to inspect the container without side effects. That's the key.

@eerhardt 

> It seems like the SerivceProvider should be the one answering the question - and not some service that I get from the ServiceProvider.

Yes but to @dadhi's point on composability. I might be wrapping the IServiceProvider now I've lost this feature because of that I need to re-implement these optional interfaces just in case the underlying provider supports it.

@ENikS 
> Where do you draw the line and define minimum criteria?

That's up to the people on this issue to define. I think usually we start with the minimum. I don't see anything fundamentally wrong with the questions you pose, we just need to make some decisions.

**Comment by tillig** [comment] 2021-06-09 16:55
>> You might want semantically different methods for IsRegistered(service type) and the “can resolve” method

> I think the only difference is with respect to the wrappers/factories whatever you want to call the open generic "things" that containers can manifest on the fly. I'm not sure that difference is observable in the scenarios I mentioned above

From an Autofac standpoint, we can tell you if something _is registered_ but we can't really tell you without trying to resolve _whether you can actually get it_. I think maybe it's just a naming thing - I would call it `IsRegistered` or something like that rather than `CanGetService` simply because of the `CanGetService` -> `GetService` implied naming relationship. "I can get it, but when I tried to get it I got an exception!"

**Comment by ENikS** [comment] 2021-06-09 16:55
> That's up to the people on this issue to define. I think usually we start with the minimum. I don't see anything fundamentally wrong with the questions you pose, we just need to make some decisions.

We could decide on the minimum, but what if a container performs more thorough magic than the baseline and succeeds where default container fails? Not an unreasonable scenario, I had one case like this with internal `CanResolve` in the service provider. 
This will break expected behavior and create two different paths of execution.

**Comment by davidfowl** [comment] 2021-06-09 17:12
> From an Autofac standpoint, we can tell you if something is registered but we can't really tell you without trying to resolve whether you can actually get it. I think maybe it's just a naming thing - I would call it IsRegistered or something like that rather than CanGetService simply because of the CanGetService -> GetService implied naming relationship. "I can get it, but when I tried to get it I got an exception!"

Done. I renamed it to `IsRegistered`.

> We could decide on the minimum, but what if a container performs more thorough magic than the baseline and succeeds where default container fails? Not an unreasonable scenario, I had one case like this with internal CanResolve in the service provider.

I'm not sure how this would break based on the intended use cases. Supporting more than the default container is fine and what other containers do today (supporting less on the other hand is what is broken). This is what the specification tests are for. Can you clarify what the broken scenario is?

**Comment by davidfowl** [comment] 2021-06-09 17:14
> Not an unreasonable scenario, I had one case like this with internal CanResolve in the service provider.
Another example would be behavior like this

Sounds like a missed test case. These happen but they don't mean we should stop and do nothing. They get fixed and we move on.

**Comment by ENikS** [comment] 2021-06-09 17:23
@davidfowl

It is more than that. 
For example, Unity can resolve structs (if they are not ref). It is the only container that does it. So, if constructor has struct parameter Unity will succeed, but default will fail. Other containers might have different peculiarity.

**Comment by davidfowl** [comment] 2021-06-09 17:31
> For example, Unity can resolve structs (if they are not ref). It is the only container that does it. So, if constructor has struct parameter Unity will succeed, but default will fail. Other containers might have different peculiarities.

I don't know why that matters. If you're using unity, then you can resolve structs. That feature doesn't need to be in the base feature set.

**Comment by pakrym** [comment] 2021-06-09 17:56
>Done. I renamed it to IsRegistered.

To satisfy scenarios this type is intended for I think the semantics have to be similar `GetService() != null` but without actual instantiation. The `IsRegistered` just muddies the water as `IEnumerable<IService>` is not explicitly registered.

**Comment by halter73** [comment] 2021-06-09 18:39
Agreed @pakrym. I like IsResolvable better than IsRegistered. I still think I like CanGetService best.

@eerhardt 

> It seems like the SerivceProvider should be the one answering the question - and not some service that I get from the ServiceProvider.

In addition to @dadhi's point on composability, there's also precedent here with IServiceScopeFactory.

**Comment by eerhardt** [comment] 2021-06-09 18:51
> there's also precedent here with IServiceScopeFactory.

And there's also precedent the other way with `ISupportRequiredService`. 😉

**Comment by halter73** [comment] 2021-06-09 19:10
> I can tell you that IComponent is registered. I can't really tell you that it's not actually resolvable because there's logic involved doing service location in an imperative fashion.

While true, I think this is unimportant when it comes to naming. What we really want is the container's best guess as to whether it can resolve a service without incurring the side effects that actually creating the service instance would entail.

Might the container actually fail to resolve something it claims is resolvable because of something it couldn't know until it tried to build it? Sure, but I don't think that's a big deal or a reason to change the name to IsRegistered.

**Comment by davidfowl** [comment] 2021-06-09 19:22
> Point being - there's a significant difference between IsRegistered and IsResolvable.

Exactly, but I think we should drive this discussion with the unit tests https://github.com/dotnet/runtime/issues/53919#issuecomment-857479162.

There are scenarios mentioned above and unit tests that reflect the expected behavior, lets choose the behavior based on that. What should each of these assertions do?

**Comment by tillig** [comment] 2021-06-09 19:23
I'd argue it's a _huge_ difference. I can't tell you if you _can actually get it_ and the method isn't `CanProbablyGetServiceButNotGuaranteed<T>()` so it seems like `CanGetService` or `IsResolvable` isn't promising on its name. `Can` and `Is` have connotations - they're Boolean. You _can_ or you _can't_; it's not quantum.

I mean, you could switch it be tri-state return value - "guaranteed you can get this," "you might be able to get this but you won't know until you try," "don't even try to get this" - but that seems more complex than what the original intent is. (Likely Autofac would end up returning the "you might be able to get this" based on `IsRegistered` and never guarantee anything.)

I hope this doesn't come down to bikeshedding on the name; I'm just really frustrated when I run across an API that supposedly has a sort of safety check ("Can I do this?") and it tells me everything's going to be good, then I do the thing it just said I could do and the thing fails.

By way of comparison, this would really suck:

```c#
var t = new Dictionary<string, string>();
lock(syncroot) {
  if(t.ContainsKey("key")) {
    // If this fails - even if I've locked around it and it's not
    // a case where someone yanked the key out from under
    // me, I'd be irritated.
    Console.WriteLine(t["key"]);
  }
}
```

**Comment by halter73** [comment] 2021-06-09 19:31
You could make any API name longer by calling out all the edge cases. We want to know without incurring side effects what types a container will return null from GetService for instead of returning an instance or throwing due to misconfiguration.

I think MEDI can do this and be right 100% of the time. (Am I wrong about this?) I understand there might be edge cases for other containers where you might know this with as much certainty, but is there a use case that really breaks hard with this interpretation?

**Comment by ENikS** [comment] 2021-06-09 19:43
Perhaps if we list criteria of what should be considered **resolvable** it would be easier to understand and decide?  
What would be default set we will have to implement?

**Comment by davidfowl** [comment] 2021-06-09 19:44
I'd like to take this to the next API review (Thursday and you should all join!) so lets agree on the semantics and worry about naming after we decide.

**Comment by tillig** [comment] 2021-06-09 19:49
> We want to know without incurring side effects what types a container will return null from GetService for instead of returning an instance or throwing due to misconfiguration.

Well, that sounds like `CanResolve` or `CanGetService` then, and the only way to do that, at least in Autofac, is to actually do the resolution. @alistairjevans can correct me on this one, but we can tell you easily if it's registered; and absolutely can't tell you if you're going to succeed at resolving without doing the operation.

I'm not sure how MEDI verifies this will work at all:

```c#
services.AddSingleton<IMyDep>(sp => new MyDep(sp.GetService<Dependency>()));
```

...but maybe there's some sort of Roslyn magic going on that Autofac hasn't implemented.

The unit tests provided show valid registrations being checked. What's the expectation for something like this?

## Lambda Service with Working Registration

```c#
var services = new ServiceCollection();
services.AddSingleton<IFoo>(sp => new Foo());
var serviceProvider = BuildServiceProvider(services); // Assume this builds a specific implementation

var supportsQuery = serviceProvider.GetRequiredService<ISupportServiceQuery>();

// These still seem right...
Assert.True(supportsQuery.IsRegistered(typeof(IFoo)));
Assert.False(supportsQuery.IsRegistered(typeof(Foo)));

interface IFoo { }
class Foo : IFoo { }
```

## Lambda Service with Broken Registration

```c#
var services = new ServiceCollection();
services.AddSingleton<IFoo>(sp => new Foo(null));
var serviceProvider = BuildServiceProvider(services); // Assume this builds a specific implementation

var supportsQuery = serviceProvider.GetRequiredService<ISupportServiceQuery>();

// ...but are these right? You can't actually resolve the IFoo
// and you might not know it until you execute the resolution.
Assert.True(supportsQuery.IsRegistered(typeof(IFoo)));
Assert.False(supportsQuery.IsRegistered(typeof(Foo)));

interface IFoo { }
class Foo : IFoo {
  public Foo(string name) {
    if(name == null)
      throw new ArgumentNullException(nameof(name));
  }
}
```

**Comment by davidfowl** [comment] 2021-06-09 19:53
We don't care if GetService fails because there's broken dependencies. We care more about if its possible to resolve or not. The use cases above don't rely on GetService/GetRequiredSerice succeeding after a call to `CanGetService`. They are using that knowledge to filter out constructors or determine that something "is a service" because it was added to the DI container. 

The only place where this was fuzzy in my original proposal was wrappers/factories/open generics that would always return true when closed but weren't explicitly added the container (IEnumerable\<T\>, Func\<T\> etc)

**Comment by davidfowl** [comment] 2021-06-09 19:57
What about the name `IsCandidateForResolution`

**Comment by tillig** [comment] 2021-06-09 19:57
> We don't care if GetService fails because there's broken dependencies.

OK, that counters the @halter73 viewpoint that

> We want to know without incurring side effects what types a container will return null from GetService for instead of returning an instance or throwing due to misconfiguration.

And there's the rub - either it's "we don't care if it's going to fail" vs "we care if it's going to fail." If we can answer that, this whole thing gets resolved.

What are the details on that API review meeting? Depending on time and day job pressures, I'll try to be there.

**Comment by tillig** [comment] 2021-06-09 20:00
Assuming there's no guarantee of resolution, I'm fine with anything like

- `IsRegistered`
- `HasRegistration` or `HasRegistrationFor`
- `IsCandidateForResolution`
- `CanTryResolve` or `CanTryResolution`
- `IsInContainer` or `IsInProvider`

**Comment by DamianEdwards** [comment] 2021-06-09 20:01
I agree with @davidfowl's take on this, in that for the cases being discussed we care about whether it's registered or not, not knowing if for some reason the `GetService` call will fail. As pointed out by @tillig there are quite literally an infinite number of ways actually resolving a service might fail.

**Comment by halter73** [comment] 2021-06-09 20:18
> The IsRegistered just muddies the water as IEnumerable<IService> (and other patterns provided by 3rd party containers) are not explicitly registered.

This is why I agreed with @pakrym and don't like "registered" in the API name. Yes, we are querying the registrations and not actually getting any service, but `CanGetService()` should return false when `GetService()` would return null, and return true otherwise.

Yes there are an infinite number of ways `GetService()` could throw after `CanGetService()` returned true, but that's not enough of a reason to rename  `CanGetService()` to `IsRegistered()` and muddying the waters about when this API should return true vs false.

**Comment by alistairjevans** [comment] 2021-06-09 20:57
From my understanding of the requirement here, what we're after is a way to ask:

 "Has someone/something previously expressed an **intent** to supply an instance of a given type from the container?"

Being able to answer that questions means that, if someone uses a type in a method, the (for example) ASP.NET Core routing engine can determine that it should ask the service provider for the instance, rather than trying to bind it from somewhere else (like the route).

In my mind, a user may express an intent to supply "MyCustomService", the ASP.NET Core runtime may express an intent to supply "IOptions<T>", and Autofac has expressed an intent to supply "IEnumerable<T>".

As @tillig says (and as far as I can tell we all agree), it's unreasonable to define an API that will actually try to tell you whether you can **definitely** get an instance of a service back from a `GetService` call without errors, without actually doing the thing, but the described requirement doesn't require that level of accuracy, just an understanding of the aforementioned **intent**.

If that statement is true, then the names can perhaps be agreed later, but my vote is for a name that reflects verifying that intent, like `InProvider`, `SuppliedByProvider`, `AvailableAsService`, `IsService` or similar.

I would also be up for attending an API review meeting on this if someone can provide details (and the timezones work out).

**Comment by davidfowl** [comment] 2021-06-09 21:18
I like IsService.

**Comment by halter73** [comment] 2021-06-09 21:44
> I would also be up for attending an API review meeting on this if someone can provide details (and the timezones work out).

@terrajobst can you help out with this?

**Comment by terrajobst** [comment] 2021-06-09 22:26
@dadhi @alexmg @seesharper @tillig @ENikS @ipjohnson I don't have access to your email. We'll do the API review tomorrow sometime between 10-12. We can probably front load this to 10 AM as it seems many of you are from Europe. If you want an invite, please send me email to immol at microsoft dot com and I can add you the call.

**Comment by seesharper** [comment] 2021-06-10 11:55
Hi guys and sorry for being late to to the party :) 

This feature has been in LightInject since the early days and it is called `CanGetInstance`. 

It is NOT a guarantee that the service actually can be resolved. It basically checks to see of the service is registered

So given these services 

```
public interface IFoo { }

public class Foo : IFoo
{
    public Foo(IBar bar) { }
}

public interface IBar { }

public class Bar : IBar { }
```

The following example shows that `IFoo` is registered, but the dependency `IBar` is not.

```
var container = new ServiceContainer();
container.Register<IFoo, Foo>();
Assert.True(container.CanGetInstance(typeof(IFoo), string.Empty));
```

> Note: Never mind the empty string being passed in here. LightInject support named services which is not really relevant here

As we can see `IFoo` is considered to be "resolvable" just by being registered in the container.

Going down the route of `GetService() != null` semantics without actually creating an instance would be far more complex and there will be edge cases where it might still not be true.

I think it is crucial to keep the behaviour of the feature as simple as possible, meaning that if it is registered it is considered "resolvable".

As for `Func<T>`, LightInject will check to see if `T` is registered

```
var container = new ServiceContainer();
container.Register<IFoo, Foo>();
Assert.True(container.CanGetInstance(typeof(Func<IFoo>), string.Empty));
Assert.False(container.CanGetInstance(typeof(Func<IBar>), string.Empty));
```

For `IEnumerable<T>` it will always return `true` since an empty list is also considered valid

This is how the feature basically works in LightInject and it is used to determine the "most resolvable constructor".

**Comment by davidfowl** [comment] 2021-06-10 15:33
@seesharper This is *EXACTLY* what we were thinking.

**Comment by davidfowl** [comment] 2021-06-10 15:46
I updated the spec tests above to specify the behavior of `IEnumerable<T>` where T is a valid service type vs when it is not. Essentially, for the built-in wrapper types like IEnumerable\<T\> (the only one supported out of the box by the spec), Func\<T\>, Lazy\<T\>:

`ISupportServiceQuery.IsService(IEnumerable<T>)` is true if `ISupportServiceQuery.IsService(T)` is also true

**Comment by pakrym** [comment] 2021-06-10 15:50
>ISupportServiceQuery.IsService(IEnumerable<T>) is true if ISupportServiceQuery.IsService(T) is also true

Are you sure it's correct for MEDI? IIRC, you can resolve IEnumerable<> of non-registered service just fine.

**Comment by davidfowl** [comment] 2021-06-10 15:54
> Are you sure it's correct for MEDI? IIRC, you can resolve IEnumerable<> of non-registered service just fine.

That's true, it'll just return an empty enumeration. OK this one is actually special. So `IsService(typeof(IEnumerable<Foo>))` where Foo isn't registered should return true.

**Comment by ENikS** [comment] 2021-06-10 16:30
Same behavior should be added for the array

On Jun 10, 2021, at 08:47, David Fowler ***@***.***> wrote:

﻿

I updated the spec tests above to specify the behavior of IEnumerable<T> where T is a valid service type vs when it is not. Essentially, for the built-in wrapper types like IEnumerable<T> (the only one supported out of the box by the spec), Func<T>, Lazy<T>:

ISupportServiceQuery.IsService(IEnumerable<T>) is true if ISupportServiceQuery.IsService(T) is also true

**Comment by bartonjs** [comment] 2021-06-10 18:14
* The existing ISupportRequiredService is used with an as-cast from IServiceProvider, so this shouldn't start with ISupport if it's used in a different way.
  * Either a different naming pattern, or change the usage to be as-based instead of GetService-based.
  * Last minute proposal was "IServiceProvider[PrimaryMethodName]" for this new kind of thing.

```C#
namespace Microsoft.Extensions.DependencyInjection
{
     public interface IServiceProviderIsService
     {
         bool IsService(Type serviceType);
     }
}
```

**Comment by davidfowl** [comment] 2021-06-10 18:30
`IServiceProviderIsService` what is this name 😄

**Comment by tillig** [comment] 2021-06-10 18:51
Unrelated to the naming: I had mentioned during the chat that results from calling the `IsService` method shouldn't be too aggressively cached. I thought I'd expand on that a bit.

At least in Autofac, we have the ability to register things into child lifetime scopes at scope creation time. While the container itself is immutable, this mechanism allows you to, for example, add the current `HttpRequestMessage` into the web request lifetime scope in Web API.

```c#
var builder = new ContainerBuilder();
builder.RegisterType<Component1>().As<IService1>();
var container = builder.Build();
Assert.True(container.IsRegistered<IService1>());
Assert.False(container.IsRegistered<IService2>());

using var scope = container.BeginLifetimeScope(b => b.RegisterType<Component2>().As<IService2>())
{
  Assert.True(scope.IsRegistered<IService1>());
  Assert.True(scope.IsRegistered<IService2>());
}
```

In Web API we ran into some challenges getting per-request action filters to work due to the aggressive caching of the filter instances. Pretty much all of that has been fixed with ASP.NET Core.

However, if/when `IServiceProviderIsService.IsService()` becomes available (or whatever the name of it becomes), I'd caution against being too aggressive about caching whether the service provider has the service in question registered. Depending on whether the query is against `ApplicationServices` or `RequestServices` and the context of the query, the result of the query _may actually be different_. I'm thinking particularly about `RequestServices` since that's the point at which new lifetime scopes are spawned, but multitenant application-level container support could also return a different value at the `ApplicationServices` level based on which tenant is accessing at the given time.

**Comment by davidfowl** [comment] 2021-06-11 05:10
I opened a PR for this change, let me know if I missed any edge cases in the spec tests.

**Closed** 2021-06-11 22:11 UTC
Labels: api-approved, area-Extensions-DependencyInjection, in pr

**Comment by davidfowl** [comment] 2021-07-06 06:51
@alexmg @tillig @pakrym @ENikS @ipjohnson @dadhi @seesharper @jeremydmiller @alistairjevans I assume you'll are gonna add support for this interface once .NET 6 ships?

**Comment by alistairjevans** [comment] 2021-07-06 07:17
For Autofac, based on what we've done before, we may have a pre-release package against a 6 preview ready a little while before the release, and then yes, release a new version once .NET 6 drops.

**Comment by dadhi** [comment] 2021-07-06 10:44
For DryIoc, yes. Will be tested first with the preview.

**Comment by ipjohnson** [comment] 2021-07-06 12:01
Yes I plan to support it in Grace soon after .net 6 releases.

**Comment by seesharper** [comment] 2021-07-06 14:08
LightInject will implement the interface in good time before the .Net 6 release 👍

**Comment by ENikS** [comment] 2021-07-06 16:47
It will be added in next major release

**Comment by alistairjevans** [comment] 2021-07-15 20:02
Thought I'd mention that we've just pushed [7.2.0-preview.1](https://www.nuget.org/packages/Autofac.Extensions.DependencyInjection/7.2.0-preview.1) of Autofac.Extensions.DependencyInjection, which consumes .NET 6 Preview 6 and adds support for `IServiceProviderIsService`; all the new spec tests pass fine. 👍

**Comment by davidfowl** [comment] 2021-07-15 20:25
Woop!
