### ISSUE TITLE
WasmTestOnBrowser-System.Threading.Tests' END OF WORK ITEM LOG: Command timed out, and was killed

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#98195] opened 2024-02-08 23:28 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=558932
Build error leg or test failing: WasmTestOnBrowser-System.Threading.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/97766

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "WasmTestOnBrowser-System.Threading.Tests' END OF WORK ITEM LOG: Command timed out, and was killed",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=558932
**Error message validated:** `[WasmTestOnBrowser-System.Threading.Tests' END OF WORK ITEM LOG: Command timed out, and was killed`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 2/8/2024 11:29:09 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[612542](https://dev.azure.com/dnceng-public/public/_build/results?buildId=612542)|dotnet/runtime|[WasmTestOnBrowser-System.Threading.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=612542&view=ms.vss-test-web.build-test-results-tab&runId=14956432&resultId=187011)|dotnet/runtime#100087|
|[611393](https://dev.azure.com/dnceng-public/public/_build/results?buildId=611393)|dotnet/runtime|[WasmTestOnBrowser-System.Threading.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=611393&view=ms.vss-test-web.build-test-results-tab&runId=14927052&resultId=187040)|dotnet/runtime#99956|
|[611333](https://dev.azure.com/dnceng-public/public/_build/results?buildId=611333)|dotnet/runtime|[WasmTestOnBrowser-System.Threading.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=611333&view=ms.vss-test-web.build-test-results-tab&runId=14924124&resultId=187039)|dotnet/runtime#96169|
|[600665](https://dev.azure.com/dnceng-public/public/_build/results?buildId=600665)|dotnet/runtime|[WasmTestOnBrowser-System.Threading.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=600665&view=ms.vss-test-web.build-test-results-tab&runId=14565136&resultId=187186)||
|[596739](https://dev.azure.com/dnceng-public/public/_build/results?buildId=596739)|dotnet/runtime|[WasmTestOnBrowser-System.Threading.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=596739&view=ms.vss-test-web.build-test-results-tab&runId=14449606&resultId=187040)|dotnet/runtime#99188|
|[596647](https://dev.azure.com/dnceng-public/public/_build/results?buildId=596647)|dotnet/runtime|[WasmTestOnBrowser-System.Threading.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=596647&view=ms.vss-test-web.build-test-results-tab&runId=14445832&resultId=187040)||
|[596210](https://dev.azure.com/dnceng-public/public/_build/results?buildId=596210)|dotnet/runtime|[WasmTestOnBrowser-System.Threading.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=596210&view=ms.vss-test-web.build-test-results-tab&runId=14429736&resultId=187039)|dotnet/runtime#99188|
|[595206](https://dev.azure.com/dnceng-public/public/_build/results?buildId=595206)|dotnet/runtime|[WasmTestOnBrowser-System.Threading.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=595206&view=ms.vss-test-web.build-test-results-tab&runId=14400722&resultId=181525)|dotnet/runtime#99422|
|[592874](https://dev.azure.com/dnceng-public/public/_build/results?buildId=592874)|dotnet/runtime|[WasmTestOnBrowser-System.Threading.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=592874&view=ms.vss-test-web.build-test-results-tab&runId=14330026&resultId=186893)|dotnet/runtime#99400|
|[591221](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591221)|dotnet/runtime|[WasmTestOnBrowser-System.Threading.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591221&view=ms.vss-test-web.build-test-results-tab&runId=14279650&resultId=186886)|dotnet/runtime#99240|
|[591039](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591039)|dotnet/runtime|[WasmTestOnBrowser-System.Threading.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=591039&view=ms.vss-test-web.build-test-results-tab&runId=14274026&resultId=187042)|dotnet/runtime#99259|
|[590968](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590968)|dotnet/runtime|[WasmTestOnBrowser-System.Threading.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590968&view=ms.vss-test-web.build-test-results-tab&runId=14270752&resultId=187028)|dotnet/runtime#99185|
|[590965](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590965)|dotnet/runtime|[WasmTestOnBrowser-System.Threading.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=590965&view=ms.vss-test-web.build-test-results-tab&runId=14270604&resultId=186884)|dotnet/runtime#99185|
|[586040](https://dev.azure.com/dnceng-public/public/_build/results?buildId=586040)|dotnet/runtime|[WasmTestOnBrowser-System.Threading.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=586040&view=ms.vss-test-web.build-test-results-tab&runId=14115136&resultId=186845)||
|[581587](https://dev.azure.com/dnceng-public/public/_build/results?buildId=581587)|dotnet/runtime|[WasmTestOnBrowser-System.Threading.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=581587&view=ms.vss-test-web.build-test-results-tab&runId=13977360&resultId=186821)|dotnet/runtime#99011|
|[579256](https://dev.azure.com/dnceng-public/public/_build/results?buildId=579256)|dotnet/runtime|[WasmTestOnBrowser-System.Threading.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=579256&view=ms.vss-test-web.build-test-results-tab&runId=13905382&resultId=186958)|dotnet/runtime#98495|
|[575938](https://dev.azure.com/dnceng-public/public/_build/results?buildId=575938)|dotnet/runtime|[WasmTestOnBrowser-System.Threading.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=575938&view=ms.vss-test-web.build-test-results-tab&runId=13812142&resultId=181546)|dotnet/runtime#98802|
|[574404](https://dev.azure.com/dnceng-public/public/_build/results?buildId=574404)|dotnet/runtime|[WasmTestOnBrowser-System.Threading.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=574404&view=ms.vss-test-web.build-test-results-tab&runId=13771150&resultId=186798)|dotnet/runtime#98672|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|2|3|17|

**Comment by lewing** [comment] 2024-02-08 23:32
cc @pavelsavara

**Comment by pavelsavara** [comment] 2024-03-22 11:19
closing as duplicate of https://github.com/dotnet/runtime/issues/99888

**Closed by pavelsavara** 2024-03-22 11:19 UTC
Labels: arch-wasm, blocking-clean-ci, area-VM-threading-mono, Known Build Error, os-browser
