### ISSUE TITLE
Support constructing file URI from Unix-style path on Windows

### ISSUE THREAD

**Issue by b11p** [dotnet/runtime#54277] opened 2021-06-16 15:04 UTC
The following code runs well on Linux, but throws on Windows.
```cs
var uri = new Uri("/dir/file");
Console.WriteLine(uri.AbsoluteUri);
```
Expected output:
```
file:///dir/file
```
Constructing such file URI on Windows may be needed, because the URI may be used on other machines. So, I was wondering if some changes can be made to do this.

**Comment by karelz** [comment] 2021-06-17 10:12
AFAIK we do not plan to recognize Unix file path automatically on Windows.
If you know you have a file path, adding a schema `file://` or using `IO` APIs would be best way to handle it consistently across platforms.

**Comment by b11p** [comment] 2021-06-18 11:13
Hi, Karel, thanks for your reply.

The main problem is to handle URI escape. I believe there is no API in `System.IO` to handle that. The closest API is `System.Web.HttpUtility.UrlPathEncode`. However, it does not always return the correct result for this scenario.

For example, if the file path is `/dir name%20/file?ww=33`, on Linux, `new Uri("/dir name%20/file?ww=33").AbsoluteUri` returns `file:///dir%20name%2520/file%3Fww=33`. On Windows, `System.Web.HttpUtility.UrlPathEncode("/dir name%20/file?ww=33")` returns `/dir%20name%20/file?ww=33` which does not represent desired file path in file URI.

So far as I know, there is no convenient workaround on Windows to create file URI for Unix file paths. Currently, creating file URI for Windows file paths on Linux is possible. It really helps if you can make it vice versa.

**Comment by MihaZupan** [comment] 2021-06-21 12:16
I agree with Karel that using `System.IO.Path` APIs is the most reliable (and potentially most correct) way to work with file paths.

Can you elaborate on what you are trying to achieve/what is your scenario - how come you are manipulating Linux file paths on Windows.

Depending on what exactly you are working with, APIs like `Uri.EscapeDataString`, `Uri.UnescapeDataString` may be appropriate if you are merely trying to transmit the values across the network.

**Comment by b11p** [comment] 2021-06-24 03:12
MihaZupan, thanks for your reply. My scenario is that program A sends a file URI to B, and B processes the represented file. B is not maintained by me, and there is no guarantee that A and B run on the same OS. I cannot control the file name either.

I find the restriction may have been added specifically [here](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.Uri/src/System/UriExt.cs#L56), so just removing the restriction may work for me.

Using `Uri.EscapeUriString` is a good idea, but this API still does not treat the whole string as a file path. For example, `Uri.EscapeUriString("/dir name%20/file?ww=33")` returns `/dir%20name%2520/file?ww=33`, while I expect `/dir%20name%2520/file%3Fww=33`.

Thank you.

**Comment by KalleOlaviNiemitalo** [comment] 2021-06-24 06:55
If you know you have a Unix-style path but don't know which OS your app runs on, I think you should split the path at slash characters (using String methods rather than Path methods), encode each segment with Uri.EscapeDataString (not EscapeUriString), and build the URI string from the results.

**Comment by b11p** [comment] 2021-06-24 07:09
KalleOlaviNiemitalo, I know that will work. But why not remove the restriction in `Uri`? At least it currently accepts Windows paths on Linux. Why not accept Unix-style paths on Windows?

**Comment by karelz** [comment] 2021-06-24 09:52
@b11p supporting Windows paths on Linux is compat for people migrating from Windows to Linux (fairly common user scenario for .NET Core). In ideal world, we would not support even this ... but the decision has been made in the past and removing it now would cause more troubles and breaking changes than value.
Adding Linux file path support to Windows (which overlaps with relative `Uri` path format) could cause breaking changes on Windows (previously invalid Uris would suddenly become valid as "file://"). Given the use case is smaller and given that ideally `Uri` should NOT handle ANY file paths directly (unfortunately we do not have a time machine to fix that mistake :(), I don't think we should extend Linux file paths support on Windows in `Uri`.

Either there needs to be general `IO` API which allows you to manipulate/create file paths of any OS on any OS (designed to handle addition of future OS support) and have ability to export it into `Uri` (with "file://" schema). `Uri` should not be that API.
Or if you need to just transfer some file path to another machine via `Uri`, you can use `Uri.EscapeDataString`/`Uri.UnescapeDataString` on the whole file path to treat it as general data and include it in some `Uri`.

I recommend to close this issue as Won't Fix / By Design.

**Comment by MihaZupan** [comment] 2021-06-24 11:54
> I find the restriction may have been added specifically here, so just removing the restriction may work for me.

The checks are spread throughout the codebase. While removing them would help your case, it would break many others.

Absolute Unix file paths are indistinguishable from relative Uris.
As Karel said, if we had a chance to do it again, file path support would never be added to Uri.

> For example, if the file path is /dir name%20/file?ww=33, on Linux, new Uri("/dir name%20/file?ww=33").AbsoluteUri returns file:///dir%20name%2520/file%3Fww=33. On Windows, System.Web.HttpUtility.UrlPathEncode("/dir name%20/file?ww=33") returns /dir%20name%20/file?ww=33 which does not represent desired file path in file URI.

You are comparing `Uri.AbsoluteUri` on Linux vs. `HttpUtility.UrlPathEncode` on Windows.

`new Uri("file:///dir name%20/file?ww=33").AbsoluteUri` will return the same (`file:///dir%20name%20/file?ww=33`) on both platforms.
The only differences would be in the handling of backslash characters.

**Comment by KalleOlaviNiemitalo** [comment] 2021-06-24 12:08
> Either there needs to be general `IO` API which allows you to manipulate/create file paths of any OS on any OS (designed to handle addition of future OS support) and have ability to export it into `Uri` (with "file://" schema). `Uri` should not be that API.

I imagine [Uri.LocalPath](https://docs.microsoft.com/dotnet/api/system.uri.localpath?view=net-5.0#System_Uri_LocalPath) would be deprecated as part of adding that.

**Comment by KalleOlaviNiemitalo** [comment] 2021-06-24 12:39
If someone wants to design a .NET API for foreign-OS paths, then the [File specification](<https://wiki.vmssoftware.com/File_specification> "File specification - VSI OpenVMS Wiki") page in the VSI OpenVMS wiki may be useful. The [file name functions in Common Lisp](<http://www.ai.mit.edu/projects/iiip/doc/CommonLISP/HyperSpec/Body/sec_the_filen_s_dictionary.html> "CLHS: Section The Filenames Dictionary") support the same components as VMS, but they do not let the application specify which namestring syntax to use.

**Comment by b11p** [comment] 2021-06-26 00:50
@karelz @MihaZupan  Thanks for your explanation. Now I understand your decision. @KalleOlaviNiemitalo 's approach is a good workaround for me.

**Comment by karelz** [comment] 2021-06-26 11:24
Closing as answered

**Closed by karelz** 2021-06-26 11:24 UTC
Labels: area-System.Net, untriaged
