### ISSUE TITLE
SendPacketsElement_FileZeroCount_Success failed on Windows 11 x64

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#63270] opened 2022-01-03 01:22 UTC
Should timeout  be raised from 10sec?
```
Console log: 'System.Net.Sockets.Tests' from job 1ee997a7-fb2b-4336-a2d0-1ba6187ac51c workitem ebba554f-5851-43af-9a22-cac7a5b116c8 (windows.11.amd64.clientpre.open) executed on machine a0046N2
...
    System.Net.Sockets.Tests.SendPacketsAsync.SendPacketsElement_FileZeroCount_Success [FAIL]
      Timed out
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SendPacketsAsync.cs(691,0): at System.Net.Sockets.Tests.SendPacketsAsync.SendPackets(SendPacketsElement[] elements, SocketError expectedResult, Int32 bytesExpected, Byte[] contentExpected)
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SendPacketsAsync.cs(663,0): at System.Net.Sockets.Tests.SendPacketsAsync.SendPackets(SendPacketsElement element, Int32 bytesExpected, Byte[] contentExpected)
        /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/SendPacketsAsync.cs(307,0): at System.Net.Sockets.Tests.SendPacketsAsync.SendPacketsElement_FileZeroCount_Success()
      Output:
        Created file C:\h\w\B241099B\t\inhts4sp.wxd_.ctor_37 with size: 1024
```
failed on https://github.com/dotnet/runtime/pull/63259

**Comment by antonfirsov** [comment] 2022-01-03 13:44
Looks like duplicate of #60017, @danmoseley feel free to reopen if you think I missed something.

**Closed by antonfirsov** 2022-01-03 13:44 UTC
Labels: area-System.Net.Sockets, untriaged
