### ISSUE TITLE
Exception Type not loged to EventLog when a Exception crashes the application

### ISSUE THREAD

**Issue by jogibear9988** [dotnet/runtime#76741] opened 2022-10-07 09:57 UTC
### Description

We've had a Application crash, and the following in our EventLog:

![image](https://user-images.githubusercontent.com/364896/194527108-d7972c22-855c-457e-8d61-59cc7a4f7a6f.png)

So we see, that a unhandled Exception has occured, but we don't see what the exception Type was. (Wich would help us to indentify the problem)

We have a Try/Catch around this code, so it seems to be a uncatchable exception, but we don't know what the type was.

### Reproduction Steps

It's not reproducible for us at the moment

### Expected behavior

The Exception Type should also be printed to eventlog

### Actual behavior

Only the Stacktrace is in the Eventlog

**Comment by jogibear9988** [comment] 2022-10-07 09:58
maybe related #75245

**Comment by jogibear9988** [comment] 2022-10-11 13:32
I now got the same exception again, and a dump:
see this issue: https://github.com/dotnet/runtime/issues/76875
So the logged Exception type should be: HeapGotCorrupted or something?

**Comment by jkotas** [comment] 2022-10-11 14:25
This is fatal crash in unmanaged code that was not translated into managed exception. It is why you do not see managed exception name in the message.

Exception code 0xc0000005 is `STATUS_ACCESS_VIOLATION`. Windows status codes are documented here: 
https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55 .

It is likely caused by heap corruption. Same root cause as https://github.com/dotnet/runtime/issues/76875. Resolving as duplicate. The other issue has more details.

**Closed by jkotas** 2022-10-11 14:25 UTC
Labels: area-Diagnostics-coreclr, untriaged
