### ISSUE TITLE
System.CodeDom.Compiler.Tests.CodeCompilerTests.GetResponseFileCmdArgs_ValidCmdArgs_ReturnsExpected test failing in CI

### ISSUE THREAD

**Issue by Jozkee** [dotnet/runtime#34112] opened 2020-03-26 05:20 UTC
Found on https://github.com/dotnet/runtime/pull/33459

Error and stack trace:
```
System.IO.DirectoryNotFoundException : Could not find a part of the path 'C:\Users\runner\AppData\Local\Temp\0lw3mff1\0lw3mff1.cmdline'.
Stack Trace:
    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
    at System.CodeDom.Compiler.CodeCompiler.GetResponseFileCmdArgs(CompilerParameters options, String cmdArgs)
    /_/src/libraries/System.CodeDom/tests/System/CodeDom/Compiler/CodeCompilerTests.cs(465,0): at System.CodeDom.Compiler.Tests.CodeCompilerTests.GetResponseFileCmdArgs_ValidCmdArgs_ReturnsExpected(String cmdArgs)AAAAAAA
```

@buyaa-n @krwq

**Comment by danmosemsft** [comment] 2020-03-26 18:21
@Jozkee its worth mentioning this was not on .NET Core: net472-Windows_NT-Release-x86-Windows.10.Amd64.Client19H1.Open

either the path was never created correctly, or it got deleted async. this test has its own TempFileCollection. my guess is the bug is in the product - in creating a unique file, or verifying it's created successfully. the code for both is different to .NET Core. it's not obvious to me what the issue could be in briefly looking.

probably most reasonable to just disable CodeDom tests from running on .NET Framework anymore.

**Comment by danmosemsft** [comment] 2020-03-26 18:22
possibly relevant but not clear how
https://github.com/dotnet/corefx/pull/12680/files#diff-7344081853370a2ec275db83f03f7076
https://referencesource.microsoft.com/#System/compmod/system/codedom/compiler/TempFiles.cs,227

**Comment by krwq** [comment] 2020-04-21 19:09
@Jozkee have you seen any CodeDom tests failing recently with similar stack trace? Did it pass after retrying? Have you seen it failing anywhere on .NET Core? Full framework is very unlikely to get patched at this point even if we find a fix.

**Comment by v-haren** [comment] 2020-05-06 02:31
failed again in job: [runtime 20200505.59](https://dev.azure.com/dnceng/public/_build/results?buildId=631931&view=ms.vss-test-web.build-test-results-tab&runId=19703072&resultId=104774&paneView=debug)

failed test: System.CodeDom.Compiler.Tests.CodeCompilerTests.GetResponseFileCmdArgs_ValidCmdArgs_ReturnsExpected(cmdArgs: null)


Error message
~~~
System.IO.DirectoryNotFoundException : Could not find a part of the path 'C:\Users\runner\AppData\Local\Temp\pnfz2ogr\pnfz2ogr.cmdline'.


Stack trace
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.CodeDom.Compiler.CodeCompiler.GetResponseFileCmdArgs(CompilerParameters options, String cmdArgs)
   at System.CodeDom.Compiler.Tests.CodeCompilerTests.GetResponseFileCmdArgs_ValidCmdArgs_ReturnsExpected(String cmdArgs) in /_/src/libraries/System.CodeDom/tests/System/CodeDom/Compiler/CodeCompilerTests.cs:line 465
~~~

**Comment by buyaa-n** [comment] 2020-06-22 21:11
As Dan mentioned sounds better to disable the tests on .NET Framework

**Comment by buyaa-n** [comment] 2021-02-16 19:17
The failure logs are gone, from the stack trace and log, and after looking into the code in `.NET Framework` i don't think this issue is caused by a code/test bug, by accounting that this failure hasn't happened for a while i am gonna just close this issue

**Closed by buyaa-n** 2021-02-16 19:17 UTC
Labels: area-System.CodeDom, up-for-grabs
