### ISSUE TITLE
UTC Conversion of DateTime.MinValue for UTC-xy timezones return different results

### ISSUE THREAD

**Issue by mooware** [dotnet/runtime#77376] opened 2022-10-24 12:09 UTC
### Description

`DateTime.MinValue.ToUniversalTime()` for UTC offsets >= 0 (e.g. UTC+2) always returns a DateTime with Ticks=0, but for offsets < 0 (e.g. UTC-8) it returns different non-zero tick values depending on timezone.

I've noticed that `MinValue` is `DateTimeKind.Unspecified`, so I thought maybe I can't expect a conversion to the UTC minimum time, but then I would expect the tick value to change both for negative and positive offsets.

The documentation (https://learn.microsoft.com/en-us/dotnet/api/system.datetime.minvalue?view=net-6.0) also states "The value of this constant is equivalent to 00:00:00.0000000 UTC, January 1, 0001, in the Gregorian calendar", which I would expect to be reflected in the result of `ToUniversalTime()`.

### Reproduction Steps

With the following source code:

```csharp
var dt = DateTime.MinValue.ToUniversalTime();
Console.WriteLine($"{dt:O}, ticks: {dt.Ticks}, tz: {TimeZoneInfo.Local}");
```

Go to the Date & time settings dialog in Windows, and set different timezones with positive and negative offsets.

### Expected behavior

I would expect the UTC conversion to always return the same timestamp, with Ticks = 0, or as the documentation states, "The value of this constant is equivalent to 00:00:00.0000000 UTC, January 1, 0001, in the Gregorian calendar".

If this is not a bug, but rather some kind of complication with the different timezones, then I would expect the documentation to contain some notes about these possible issues.

### Actual behavior

The included sample program run with different timezones:

0001-01-01T00:00:00.0000000Z, ticks: 0, tz: (UTC+10:00) Canberra, Melbourne, Sydney
0001-01-01T00:00:00.0000000Z, ticks: 0, tz: (UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi
0001-01-01T00:00:00.0000000Z, ticks: 0, tz: (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
0001-01-01T00:00:00.0000000Z, ticks: 0, tz: (UTC+00:00) Dublin, Edinburgh, Lisbon, London
0001-01-01T00:00:00.0000000Z, ticks: 0, tz: (UTC) Coordinated Universal Time
0001-01-01T01:00:00.0000000Z, ticks: 36000000000, tz: (UTC-01:00) Azores
0001-01-01T05:00:00.0000000Z, ticks: 180000000000, tz: (UTC-05:00) Havana
0001-01-01T08:00:00.0000000Z, ticks: 288000000000, tz: (UTC-08:00) Pacific Time (US & Canada)
0001-01-01T10:00:00.0000000Z, ticks: 360000000000, tz: (UTC-10:00) Hawaii

### Configuration

Target Framework: net6.0

dotnet --info:

```
.NET SDK (reflecting any global.json):
 Version:   6.0.401
 Commit:    0906eae6f8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.401\

global.json file:
  Not found

Host:
  Version:      6.0.9
  Architecture: x64
  Commit:       163a63591c

.NET SDKs installed:
  3.1.302 [C:\Program Files\dotnet\sdk]
  3.1.415 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]
  6.0.201 [C:\Program Files\dotnet\sdk]
  6.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by Clockwork-Muse** [comment] 2022-10-24 15:11
@dotnet/area-system-globalization 
(I think)

> If this is not a bug, but rather some kind of complication with the different timezones, then I would expect the documentation to contain some notes about these possible issues.

Essentially.
The problem is that values below zero ticks aren't valid for `DateTime`, so calling `ToUniversalTime()` in such a situation has two options:
 - return `0` ticks again
 - Throw an error.

That aside, [it is in the documentation](https://learn.microsoft.com/en-us/dotnet/api/system.datetime.touniversaltime?view=net-7.0#returns):

>  An object whose [Kind](https://learn.microsoft.com/en-us/dotnet/api/system.datetime.kind?view=net-7.0#system-datetime-kind) property is [Utc](https://learn.microsoft.com/en-us/dotnet/api/system.datetimekind?view=net-7.0#system-datetimekind-utc), and whose value is the UTC equivalent to the value of the current [DateTime](https://learn.microsoft.com/en-us/dotnet/api/system.datetime?view=net-7.0) object, or [DateTime.MaxValue](https://learn.microsoft.com/en-us/dotnet/api/system.datetime.maxvalue?view=net-7.0) if the converted value is too large to be represented by a [DateTime](https://learn.microsoft.com/en-us/dotnet/api/system.datetime?view=net-7.0) object, or **[DateTime.MinValue](https://learn.microsoft.com/en-us/dotnet/api/system.datetime.minvalue?view=net-7.0) if the converted value is too small to be represented by a [DateTime](https://learn.microsoft.com/en-us/dotnet/api/system.datetime?view=net-7.0) object**.

(emphasis mine)

**Comment by tarekgh** [comment] 2022-10-24 15:22
Closing it per @Clockwork-Muse as the behavior is already documented and this is not a bug.

**Closed by tarekgh** 2022-10-24 15:22 UTC
Labels: area-System.Runtime
