### ISSUE TITLE
Use of ReferenceHandler.Preserve (considerably) increase Memory Pressure

### ISSUE THREAD

**Issue by codingdna2** [dotnet/runtime#47569] opened 2021-01-28 09:07 UTC
### Description

I've enabled in my ASP.NET Core project the usage of the built-in ReferenceHandler as following.

```C#
services.AddControllers()
    .AddJsonOptions(options =>
    {
        options.JsonSerializerOptions.IgnoreNullValues = true;
        options.JsonSerializerOptions.Converters.Add(new TimeSpanConverter());
        options.JsonSerializerOptions.ReferenceHandler = ReferenceHandler.Preserve;
    });
```

I've observed my process, which was previously running with a memory consuption of 110-120Mb, running at over 2GB (and increasing) a few  ~~seconds~~ minutes after I've connected my client. My client is a C# client generated with NSwag.

### Configuration

* NET 5.0
* Windows 10 v20H2 build 19042.746
* Architecture x64

### Other information

I've tried to have a look at source code and I see PreserveReferenceHandler have a static reference ([ReferenceHandler.cs](https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/ReferenceHandler.cs)) and contains a dictionary from which values are never removed [(PreserveReferenceResolver.cs).](https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/PreserveReferenceResolver.cs). So I can just guess disposing would occur when the whole serializer is disposed but it's not clear to me when this happens. 

Am I using it in a wrong way?
Thanks in advance for any help.
Dan

**Comment by eiriktsarpalis** [comment] 2021-01-28 15:17
Hi @codingdna2, would you be able to supply a minimal reproduction that demonstrates the issue? If not, have you tried profiling your application?

**Comment by layomia** [comment] 2021-01-28 15:30
cc @Jozkee 

This reminds me of https://github.com/dotnet/aspnetcore/discussions/24230. Are you able to take a memory dump, similar to that issue, and share what you find with us?

How many elements (unique objects with different `$id`s) are placed in the reference dictionary you mentioned? `JsonSerializer`, by default, news up an instance of the reference dictionary for every call to the serializer, which is destroyed when (de)serialization is complete. If the problem here is using the preserve-reference feature, this suggests to me that a single call to the serializer is creating a whole lot of objects based on the incoming JSON payload (when deserializing), or based on the size of the instantiated input object graph (when serializing).

Is it possible to check if the same issue happens if `Newtonsoft.Json` is used instead?

**Comment by codingdna2** [comment] 2021-01-28 15:50
Hi @eiriktsarpalis, I'll try my best to create a sample repo. 

What I've done was to enable/disable the reference handling and observing the memory increase. My model is quite big and I've tried to use reference handling to decrease the size of my JSONs. The client is also quite complex and makes various call to the APIs in response to some SignalR notifications.

I've also tried to profile the application but I cannot understand exactly what kind of objects get allocated (probably I don't have the experience to carry such investigation myself).

@layomia About object graph, I've checked one of my responses and the biggest $id I see is 3478. But as you said if the dictionary is destroyed at every call, I wouldn't expect them to pile.  

Give me some time, I'll try to collect some more informations.

**Comment by codingdna2** [comment] 2021-01-28 16:10
Here's some screenshot of the profiling... as said, I've no much experience in this kind of investigations (so please excuse me):

![image](https://user-images.githubusercontent.com/6033635/106164672-88985d80-618a-11eb-911b-e9d02ea4edbb.png)

![image](https://user-images.githubusercontent.com/6033635/106164714-964de300-618a-11eb-8a6d-2900a79f885f.png)

It seems that between snapshots, the `Count` of `JsonSerializerOptions` doesn't increase but its `Inclusive Size` does. As I totally feel unfit for this task, if you don't have any specific instructions on this (which I'll gladly follow), I'll move to try create a sample repo.

**Comment by layomia** [comment] 2021-01-28 17:04
Thanks @codingdna2. I'll start to look at this, but yes a sample repro would be really helpful.

**Comment by codingdna2** [comment] 2021-01-29 08:51
Sorry for the delay, I had to do daddy stuff :) 

Here is the [sample repro](https://github.com/codingdna2/JsonReferenceHandlerIssue). It's close enough to my configuration. The model is quite simple and the memory grows slowly (but steady).

**Comment by codingdna2** [comment] 2021-01-29 14:32
Last question asked by @layomia. 
> Is it possible to check if the same issue happens if `Newtonsoft.Json` is used instead?

Yes, It seems to have the same effect.

```C#
services.AddControllers().AddNewtonsoftJson(
    options =>
    {
        options.SerializerSettings.PreserveReferencesHandling = Newtonsoft.Json.PreserveReferencesHandling.All;
    });
```

**Comment by codingdna2** [comment] 2021-01-29 15:35
I've done an additional test using `<ServerGarbageCollection>false</ServerGarbageCollection>` which has finally convinced me there's no leak. Memory is stable at 61MB. I leave at @layomia, @eiriktsarpalis decision to close the issue or not, but I guess it was a false alarm. Surely `ReferenceHandler` have a strong impact on memory which makes it unusable for me.

**Comment by eiriktsarpalis** [comment] 2021-01-29 20:11
I would recommend closing the issue for now. If you could provide us with a reproduction (e.g. containing the type of object graphs that illustrate the behaviour you are seeing) we can take a second look.

**Comment by Jozkee** [comment] 2021-01-29 20:18
> Why having entities in a dictionary for the time of the serialization, (apparently) cause GC to move them to an higher generation?

@codingdna2 the dictionary holds unique objects found during serialization and helps us to determine if the current object to be serialized was previously serialized, if so, the serializer only writes an object with a pointer property (`$ref`) instead of writing the whole object for a second time.

This is beneficial for a couple cases:
1. If your object has a large amount of duplicate references, using ReferenceHandler.Preserve can significantly reduce the size of your resulting JSON. 
2. If your object happens to contain a cycle, the pointer written by the serializer when Preserve is on serves as a terminator to avoid infinite recursion.

**Comment by codingdna2** [comment] 2021-01-29 20:22
> I would recommend closing the issue for now. If you could provide us with a reproduction (e.g. containing the type of object graphs that illustrate the behaviour you are seeing) we can take a second look.

It was posted above...

https://github.com/codingdna2/JsonReferenceHandlerIssue

**Comment by codingdna2** [comment] 2021-01-29 20:28
> > Why having entities in a dictionary for the time of the serialization, (apparently) cause GC to move them to an higher generation?
> 
> 
> 
> @codingdna2 the dictionary holds unique objects found during serialization and helps us to determine if the current object to be serialized was previously serialized, if so, the serializer only writes an object with a pointer property (`$ref`) instead of writing the whole object for a second time.
> 
> 
> 
> This is beneficial for a couple cases:
> 
> 1. If your object has a large amount of duplicate references, using ReferenceHandler.Preserve can significantly reduce the size of your resulting JSON. 
> 
> 2. If your object happens to contain a cycle, the pointer written by the serializer when Preserve is on serves as a terminator to avoid infinite recursion. 
> 
> 

Thanks, still not understand why 3000 objects gets disposed almost immediately, while introducing a dictionary containing some ids fill the memory so much. Attached is a repro. If you run it, you'll notice memory growing. If you change serialization option and disable reference handler, memory is stable.

**Comment by eiriktsarpalis** [comment] 2021-04-01 15:49
Hi @codingdna2, I tried running your code locally and was able to reproduce the increase in memory consumption. This however only happened when hosting the server on the debugger, running it standalone either using Debug or Release builds never exceeded 300 MB of memory consumption.

I took a snapshot of the debug process and the heap looks rather inconspicuous:
![image](https://user-images.githubusercontent.com/2813363/113316659-82e40300-9306-11eb-9163-f52b9d79330e.png)

Note that memory usage is dominated by Newtonsoft types, which I think have been pulled in because of the swagger dependencies. One problem I see here is that this is not a minimal reproduction: the app has many dependencies unrelated to the issue at hand. As soon as I removed NSwag and NLog, memory consumption was stabilized below 300 megs in the debugger as well.

This is not to say that there isn't an issue with reference preservation memory consumption, but I think there are too many at factors at play that might obscure the root cause. I would recommend trimming down your app to a minimal reproduction (gradually removing components that are not contributing to the observed issue).

**Comment by codingdna2** [comment] 2021-04-06 14:00
Hi @eiriktsarpalis, I've followed your indication and removed unnecessary components (modifications were commited on the same [repository](https://github.com/codingdna2/JsonReferenceHandlerIssue))

Made a simple test running the server process compiled in Debug mode without and with reference preservation for about 10 minutes. Measuring using Task Manager with attached debugger, I see 60MB consumption without and 180MB with reference preservation, totaling a 215% increase (or a 105% difference). Almost same results were observed without attached debugger. 

Of course this refers to the simple model I've used to create the repro. Using a more complex model exacerbate the problem (my own project moves from 800MB to over 2GB). If this values are expected, feel free to close the issue.

**Comment by eiriktsarpalis** [comment] 2021-04-19 16:02
> Made a simple test running the server process compiled in Debug mode without and with reference preservation for about 10 minutes.

What happens if you run the test in Release mode though?

**Comment by codingdna2** [comment] 2021-04-26 09:26
I see almost the same results. Here's a summary:

| Mode      | Reference Preservation | Memory Consuption |
| ----------- | ----------- | ----------- |
| Debug      | W/O       | 60 MB |
| Debug   | W        | 180 MB |
| Release | W/O | 66 MB |
| Release | W | 167 MB | 

Note: Attach the debugger doesn't seems to affect the results significantly.

**Comment by eiriktsarpalis** [comment] 2021-04-26 16:34
But does memory consumption increase over time? This is not something I could detect unless running the process from the debugger. I also can't find any evidence of a memory leak happening in System.Text.Json. 

I tried tightening the loop of your reproduction by [making the following changes](https://github.com/eiriktsarpalis/JsonReferenceHandlerIssue/commit/c04303019ce9d059e75fc1924eeec9f6fec58702): while enabling reference preservation does result in slightly increased memory usage (which is expected), there is no indication of any memory leaks happening.

**Comment by codingdna2** [comment] 2021-04-27 12:25
Not sure if it'll get to a stable point but after two hours in Release mode I have the following:

![image](https://user-images.githubusercontent.com/6033635/116239014-6ea6f080-a762-11eb-8852-713f78d031cf.png)

I'll leave it running for the day to see where it goes...

>  I also can't find any evidence of a memory leak happening in System.Text.Json.

You're probably right about the memory leak. I guess, if there's a problem, it's more a promotion to an higher generation in garbage collection than a real leak. 

Previously, I made a test using `<ServerGarbageCollection>false</ServerGarbageCollection>` (see above) and it was stable. I've not repeated the test since then but I suppose it's enough to exclude the leak.

> I tried tightening the loop of your reproduction by making the following changes

I see what you did and I'll run some tests leaving all the ASPNET infrastructure aside.

> while enabling reference preservation does result in slightly increased memory usage

Not sure it fits the slightly definition.

**Comment by eiriktsarpalis** [comment] 2021-04-27 12:33
> while enabling reference preservation does result in slightly increased memory usage
>
> Not sure it fits the slightly definition.

I was referring to the standalone console app, where memory consumption differs by a couple of megabytes.

**Comment by codingdna2** [comment] 2021-05-04 14:59
About the previous test, it stabilize around 300/400 MB.

I just [pushed the same standalone program](https://github.com/codingdna2/JsonReferenceHandlerIssue/tree/master/StandaloneSerialization) as you did. 

If I run it as it is I get a stable 26MB memory usage.
BUT, If I enable the **Server GC** in _csproj_, it grows like a crazy (600 MB in 30 seconds and growing).
If I still use Server GC and disable Reference preservation, it runs at 46-49 MB steady.

**Comment by eiriktsarpalis** [comment] 2021-07-30 16:44
When profiling your reproducing app I can see clear differences in the allocation profiles for server and workstation GC:

### Workstation GC
<img width="720" alt="Capture2" src="https://user-images.githubusercontent.com/2813363/127684455-e607bb4b-381d-4c1d-b229-c45c303e8bac.PNG">

### Server GC
<img width="927" alt="Capture" src="https://user-images.githubusercontent.com/2813363/127684400-7726a376-7f1e-4f1a-9751-2b59aba17111.PNG">

I tried [removing System.Text.Json from the reproducing app](https://github.com/eiriktsarpalis/JsonReferenceHandlerIssue/commit/e5d7cfb2d335849b0b9c88ae5e5af91caba612db) simply running the logic of [PreserveReferenceResolver](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/PreserveReferenceResolver.cs) in a loop. Sure enough, on my machine memory usage balloons from ~15M to ~900M when switching to server GC.

Tagging @dotnet/gc who might know if this is expected behavior.

**Comment by Maoni0** [comment] 2021-08-02 19:59
the best way to investigate a managed memory related issue is to start with [collecting the top level GC events](https://github.com/Maoni0/mem-doc/blob/master/doc/.NETMemoryPerformanceAnalysis.md#how-to-collect-top-level-gc-metrics). my guess is you have quite a few heaps in Server GC and/or the survival rate is high which means the gen0 budget is quite a high which then leads to much higher memory usage before the next GC is triggered. this can all be verified by the top level GC trace.

**Comment by eiriktsarpalis** [comment] 2021-08-03 12:17
> my guess is you have quite a few heaps in Server GC and/or the survival rate is high which means the gen0 budget is quite a high which then leads to much higher memory usage before the next GC is triggered.

This seems consistent with what I'm seeing in the VS profiler. FWIW here are the collected events for the reproducing app:

## Workstation GC

![image](https://user-images.githubusercontent.com/2813363/128013804-25f0b7f5-4e0e-4203-ae17-500694f65830.png)

![image](https://user-images.githubusercontent.com/2813363/128013863-9170c031-6329-46cf-b0d8-b1a1b66aed41.png)

## Server GC

![image](https://user-images.githubusercontent.com/2813363/128012946-3057cebc-68ff-409a-a4af-06e12b13273a.png)

![image](https://user-images.githubusercontent.com/2813363/128012692-cb9e3890-cc77-44f9-9863-7b3300328508.png)

**Comment by Maoni0** [comment] 2021-08-03 21:57
yeah, as expected you are doing a lot fewer GCs with Server GC because it allows you to allocate a lot more before triggering a GC. is there any reason why you need to use Server GC if you want a small memory footprint?

**Comment by codingdna2** [comment] 2021-08-04 08:00
@Maoni0 This is just a sample repro used to demonstrate the issue that arise in a ASPNET core project enabling a functionality of the json serializer. The ASPNET core uses Server GC by default and so does the repro. 

@eiriktsarpalis I've run your latest repro and the issue disappears if the "Clear" on dictionary is called. So it seems that Server GC is having an issue if the Dictionary is not cleared while Workstation GC does not. The actual SJT implementation you [linked](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/PreserveReferenceResolver.cs) seems not to include a "Clear" of the dictionary.

Latest repro [here](https://github.com/codingdna2/JsonReferenceHandlerIssue/blob/master/StandaloneSerialization/Program.cs).

**Comment by eiriktsarpalis** [comment] 2021-08-04 08:39
> @eiriktsarpalis I've run your latest repro and the issue disappears if the "Clear" on dictionary is called. So it seems that Server GC is having an issue if the Dictionary is not cleared while Workstation GC does not. The actual STJ implementation you linked seems not to include a "Clear" of the dictionary.
>
> Latest repro here.

STJ does not share state across serializations so maintaining a global dictionary like your changes suggest is not something we could realistically incorporate into the reference preservation feature. Also note that your changes do not in fact clear the global dictionary at the end of each iteration: this results in operations becoming idempotent after the first iteration and no allocations being recorded subsequently.

I'm going to close this issue as by-design. Reference preservation is a memory intensive feature, per @maoni0's feedback enabling Server GC results in GC events being fewer and further between which would correlate with increased memory usage.

**Closed by eiriktsarpalis** 2021-08-04 08:39 UTC
Labels: area-System.Collections, customer assistance

**Comment by eiriktsarpalis** [comment] 2021-08-04 11:08
I might have misunderstood your comments then. Clearing the dictionary should only be meaningful in this context if the same dictionary instance is being reused across iterations. But I failed to spot any clearing operation in the latest reproduction that you shared.

**Comment by codingdna2** [comment] 2021-08-04 12:34
> Clearing the dictionary should only be meaningful in this context if the same dictionary instance is being reused across iterations.

I expected the same as you but the repro shows that the memory pressure almost disappear if the dictionary is cleared before going out of scope (and later collected by Server GC).

>  But I failed to spot any clearing operation in the latest reproduction that you shared.

I took yours and cleared. Anyway at [line 27](https://github.com/codingdna2/JsonReferenceHandlerIssue/blob/129313aafd186a9b8d5d0c7b889195d8082703db/StandaloneSerialization/Program.cs#L27), there's a `handler.Reset()` call which call `[_objectToReferenceIdMap.Clear();](https://github.com/codingdna2/JsonReferenceHandlerIssue/blob/129313aafd186a9b8d5d0c7b889195d8082703db/StandaloneSerialization/Program.cs#L55)`. Uncommenting the `handler.Reset()` solve the issue (which shouldn't, but it does).

**Comment by eiriktsarpalis** [comment] 2021-08-04 13:55
I see now. Per [my comment in the original repro](https://github.com/eiriktsarpalis/JsonReferenceHandlerIssue/commit/d0389ff689d45a7c0ab6018e0ecb697866d92a10#diff-5610e8be0e29a69cb792d78c8d2c24483a45049f285bb31fb379ab5408f77777R16) this was testing a global dictionary that was getting cleared at the end of each loop. However you are pointing out that simply clearing the (freshly allocated) dictionary at the end of each iteration makes memory consumption decrease significantly.

Running the code in the VS profiler seems to indicate that clearing the dictionary before it falls out of scope results in GC events happening much more frequently, thus contributing to reduced memory consumption in the app. I'm sure @Maoni0 can provide insight as to why this is happening.

**Comment by Maoni0** [comment] 2021-08-04 20:43
[this](https://github.com/Maoni0/mem-doc/blob/master/doc/.NETMemoryPerformanceAnalysis.md#the-one-rule-to-remember) should help explain what you are seeing.
