### ISSUE TITLE
Test failure: GC\\Features\\HeapExpansion\\plug\\plug.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#105211] opened 2024-07-22 02:12 UTC
**Failed in:** [runtime-coreclr jitstress2-jitstressregs 20240721.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=749394&view=ms.vss-test-web.build-test-results-tab&runId=18962444&resultId=121772&paneView=debug)

**Failed tests:**
```
coreclr windows x86 Checked jitstress2_jitstressregs0x10 @ Windows.10.Amd64.Open
    - GC\\Features\\HeapExpansion\\plug\\plug.cmd
```

**Error message:**
```
 
Assert failure(PID 6940 [0x00001b1c], Thread: 6336 [0x18c0]): Consistency check failed: AV in clr at this callstack:
------
CORECLR! WKS::gc_heap::background_mark_simple + 0x21 (0x700120cf)
CORECLR! WKS::gc_heap::background_promote + 0x109 (0x700127d9)
CORECLR! PinObject + 0xF3 (0x6ffdb593)
CORECLR! ScanConsecutiveHandlesWithoutUserData + 0x44 (0x6ffda454)
CORECLR! BlockScanBlocksWithoutUserData + 0x29 (0x6ffd9ec9)
CORECLR! ProcessScanQNode + 0x32 (0x6ffda322)
CORECLR! ProcessScanQueue + 0x2E (0x6ffda361)
CORECLR! xxxTableScanQueuedBlocksAsync + 0xA5 (0x6ffda944)
CORECLR! xxxAsyncSegmentIterator + 0x35 (0x6ffda7b5)
CORECLR! TableScanHandles + 0xB0 (0x6ffda6d0)
CORECLR! xxxTableScanHandlesAsync + 0x97 (0x6ffda867)
CORECLR! HndScanHandlesForGC + 0x139 (0x6ffd84f9)
CORECLR! Ref_TracePinningRoots + 0xC8 (0x6ffdcdbf)
CORECLR! GCScan::GcScanHandles + 0x64 (0x6ffdf985)
CORECLR! WKS::gc_heap::background_mark_phase + 0x1E3 (0x70011336)
CORECLR! WKS::gc_heap::gc1 + 0x137 (0x7001b743)
CORECLR! WKS::gc_heap::bgc_thread_function + 0xD2 (0x70013a24)
CORECLR! WKS::gc_heap::bgc_thread_stub + 0x27 (0x70013be7)
CORECLR! <lambda_d25fb625c39c5b05f3f08c0277a0e775>::operator() + 0x84 (0x6fdd8d13)
-----
.AV on tid=0x18c0 (6336), cxr=0899ECF0, exr=0899ECA0
FAILED: false

CORECLR! CHECK::Trigger + 0x264 (0x70070f75)
CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x1D7 (0x6fbfcaef)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x4E (0x6fbfc7e4)
CORECLR! CLRVectoredExceptionHandler + 0x12C (0x6fbfc78e)
CORECLR! CLRVectoredExceptionHandlerShim + 0x161 (0x6fbfcce1)
NTDLL! WinSqmEventWrite + 0x1B825 (0x7721f2f5)
NTDLL! RtlUnwind + 0x1BA (0x771dea7a)
NTDLL! KiUserExceptionDispatcher + 0xF (0x771f115f)
CORECLR! WKS::gc_heap::background_promote + 0x109 (0x700127d9)
CORECLR! PinObject + 0xF3 (0x6ffdb593)
    File: D:\a\_work\1\s\src\coreclr\vm\excep.cpp:6877
    Image: C:\h\w\9F5B08B0\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\9F5B08B0\w\C5B50AB9\uploads\Reports\GC.Features\HeapExpansion\plug\plug.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\9F5B08B0\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  plug.dll 
Running 100 iterations
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:\cores since 7/21/2024 7:03:44 PM
Processing C:\cores\corerun.exe.6940.dmp
Invoking: C:\Program Files (x86)\Windows Kits\10\Debuggers\x86\cdb.exe -c "$<C:\h\w\9F5B08B0\t\tmpt1rp1d.tmp" -z "C:\cores\corerun.exe.6940.dmp"
stdout: 
Microsoft (R) Windows Debugger Version 10.0.18362.1 X86
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:\cores\corerun.exe.6940.dmp]
User Mini Dump File with Full Memory: Only application data is available


************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:\h\w\9F5B08B0\p\PDB
Symbol search path is: C:\h\w\9F5B08B0\p\PDB
Executable search path is: 
Windows 10 Version 14393 MP (4 procs) Free x86 compatible
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.6343 (rs1_release.230913-1727)
Machine Name:
Debug session time: Sun Jul 21 19:03:55.000 2024 (UTC + 0:00)
System Uptime: 0 days 0:04:25.132
Process Uptime: 0 days 0:00:11.000
..................................

************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  The system cannot find the file specified

You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.sympath) is correct.
This dump file has an exception of interest stored in it.
The stored e
```

**Stack trace:**
```
   at GC_Features._HeapExpansion_plug_plug_._HeapExpansion_plug_plug_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by mangod9** [comment] 2024-08-01 21:38
I am closing this as a dupe of the other heap corruption recently fixed.

**Closed by mangod9** 2024-08-01 21:38 UTC
Labels: arch-x86, os-windows, JitStress, area-GC-coreclr, untriaged, blocking-clean-ci-optional
