### ISSUE TITLE
Performance issue occurs while using DynamicInvoke

### ISSUE THREAD

**Issue by ChidanandMurugaiah** [dotnet/runtime#88469] opened 2023-07-06 10:53 UTC
### Configuration

* Which version of .NET is the code running on? .NET Framework 4.7.2
* What OS version, and what distro if applicable? windows 10 Enterprise
 
### Description

Occurs performance difference between Invoke and Dynamic Invoke. I try to Invoke a function in a foreach, and its loop count is 5000000. And I tried Dynamic Invoke to the same function in a foreach with the same loop count. 

Please refer the below code snippet and gif file.

  
     private void Button_Click(object sender, RoutedEventArgs e)
     {
         // Create a parameter expression representing an input parameter
         ParameterExpression parameter = Expression.Parameter(typeof(int), "x");

         // Create a body expression representing an arithmetic operation
         BinaryExpression multiplication = Expression.Multiply(parameter, Expression.Constant(5));

         // Create a lambda expression with the parameter and the body expression
         LambdaExpression lambda = Expression.Lambda(multiplication, parameter);

         // Compile the lambda expression to a delegate
         Func<int, int> multiplyByFive = (Func<int, int>)lambda.Compile();

         //Invoke the compiled delegate
         Stopwatch watch = new Stopwatch();
         watch.Start();
         for (int i = 0; i < 5000000; i++)
         {
             multiplyByFive.Invoke(10);
         }
         watch.Stop();
         textBox1.Text = watch.ElapsedMilliseconds + "ms";

         Stopwatch watch2 = new Stopwatch();
         watch2.Start();
         for (int i = 0; i < 5000000; i++)
         {
             multiplyByFive.DynamicInvoke(10);
         }
         watch2.Stop();
         textBox2.Text = watch2.ElapsedMilliseconds + "ms";
     }

### Output Video

![Analyzation Video](https://github.com/dotnet/runtime/assets/124787498/90561c15-8012-46de-91b7-7e34c751cc34)

### Query

In this simple code snippet, it took 3263ms but in our case it took 2 to 3 seconds to process. Need a solution to resolve the Performance delay when using DynamicInvoke.

**Comment by davidfowl** [comment] 2023-07-06 11:27
Why are you using dynamic invoke if you care about performance? Also, this issues fixed here don't apply to .NET Framework, just .NET 6+

**Comment by hez2010** [comment] 2023-07-06 11:29
In my local test the result is 7ms and 330ms on .NET 7.

**Comment by cston** [comment] 2024-08-13 17:29
Closing since it seems this may be more of an issue with .NET Framework than .NET 7+.

Also, the `System.Linq.Expressions` library is effectively archived, and we are only taking changes that address significant bugs or regressions, or changes needed to continue shipping - see [README.md](https://github.com/dotnet/runtime/tree/main/src/libraries/System.Linq.Expressions/README.md).

**Closed by cston** 2024-08-13 17:29 UTC
Labels: area-System.Linq.Expressions, tenet-performance, untriaged
