### ISSUE TITLE
[mono] mono crash on ios

### ISSUE THREAD

**Issue by gemSender** [dotnet/runtime#68849] opened 2022-05-04 07:55 UTC
### Description

mono's hybird mode crash on ios

### Reproduction Steps

Run with mono's hybrid mode(MONO_AOT_MODE_INTERP), some assemblies are compiled with aot (parameters --aot=interp, full, ... have been added for all aot modules), when the interpreted assembly calls this aot-compiled method
![image](https://user-images.githubusercontent.com/6006458/166637712-fdba1d9f-1578-447d-856e-c9c214689b70.png)

, mono crashes, and The following logs are output:
![image](https://user-images.githubusercontent.com/6006458/166637546-0d87f012-1cc6-4fce-9b36-dfbb7558da54.png)

And when I add some unused parameters to this method, it didn't crash anymore
![image](https://user-images.githubusercontent.com/6006458/166638630-15b0a181-5517-4f8a-8cda-7a340a977c77.png)

### Expected behavior

should not crash

## Stacktrace
![image](https://user-images.githubusercontent.com/6006458/166641294-db08ff04-d506-4b31-a3b1-209948d6715f.png)

### Known Workarounds
Mono, Interp, Aot

### Configuration

runtime version: mono 12.0
platform: ios 14.2

**Comment by gemSender** [comment] 2022-07-05 15:31
I found that it only crashes when the parameter has a default value, and when I remove the default value for the parameter, it doesn't crash anymore！

**Comment by BrzVlad** [comment] 2022-08-14 22:04
This crash seems to happen on old profile mono/2020-02, in which case this issue is not a blocking release for .net 7. @gemSender Could you confirm that this is the old framework ? Also do you have a sample app that reproduces this crash ?

**Comment by gemSender** [comment] 2022-08-15 03:30
My mono version is 6.12.x. @BrzVlad , you can close the issue if it was fixed in .net 7

**Comment by BrzVlad** [comment] 2022-08-15 09:00
It is not clear to me if this issue exists on .net 7 since I don't understand why it happens on mono 6.12 in the first place. Do you have any kind of repro ? Either project source code, entire app binary or at least some binaries within application (the dll and aot image where that method lives)

**Comment by gemSender** [comment] 2022-08-15 10:51
[AotTest.tar.gz](https://github.com/dotnet/runtime/files/9336746/AotTest.tar.gz)
this is the c# project and the folder 'binary' is the output of dotnetbuild and aotbuild output 
@BrzVlad

**Comment by BrzVlad** [comment] 2022-08-17 13:47
@gemSender Thank you for the quick replies. After some investigations it turns out that this was indeed fixed on `dotnet/runtime` by https://github.com/dotnet/runtime/pull/40498. There was also a mono PR with this fix but somehow it wasn't backported to the release branch

**Closed by BrzVlad** 2022-08-17 13:47 UTC
Labels: area-Codegen-Interpreter-mono
