### ISSUE TITLE
Double Array members with Microsoft.Extensions.Configuration.Get and Records

### ISSUE THREAD

**Issue by bartkemps** [dotnet/runtime#99080] opened 2024-02-28 20:36 UTC
### Description

I'm using records for my configuration / option classes.
This worked fine until I decided to add an array: now the content of the array is doubled.
I'm guessing array members are added in the constructer and later again though reflection.

### Reproduction Steps

In a .net 8 web api application (at least, that's what I'm using) add an options record:
```
public record MyOptions ( int Foo, string[] Bar);
```
Add appsetings.json
```
{ MySettings: { Foo: 1, Bar: ["Fizz", "Buzz"]}
```
Add Program.cs:

```
var builder = WebApplication.CreateBuilder(args);
var myOptions = builder.Configuration.GetSection("MySettings").Get<MyOptions>()
// set a breakpoint here to inspect the value of myOptions
services.AddScoped(_=>Options.Create(vbpApiOptions));
```

_NOTE: this does not work either because an empty constructor is expected. This should be fixed too._
```
services.Configure<VbpApiOptions>("AppSettings", configuration);
```

### Expected behavior

The value of `myOptions.Bar` should be `string[] {"Fizz", "Buzz"}`

### Actual behavior

The value of `myOptions.Bar` is `string[] {"Fizz", "Buzz", "Fizz", "Buzz"}`

### Known Workarounds

* Don't use arrays where repeated values cause problems.
* Don't use record types

**Comment by bartkemps** [comment] 2024-02-28 21:00
This may be the same issue as this one:
https://github.com/dotnet/runtime/issues/83803

**Comment by tarekgh** [comment] 2024-02-28 21:07
Yes this is a duplicate of https://github.com/dotnet/runtime/issues/83803. The work around is not using record for now.

**Closed by tarekgh** 2024-02-28 21:07 UTC
Labels: untriaged, area-Extensions-Options
