### ISSUE TITLE
Test failure: ConnectionClosedByPeer_WithPendingAcceptAndConnect_PendingAndSubsequentThrowConnectionAbortedException

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#56926] opened 2021-08-05 18:53 UTC
Test `System.Net.Quic.Tests.QuicConnectionTests_MsQuicProvider.ConnectionClosedByPeer_WithPendingAcceptAndConnect_PendingAndSubsequentThrowConnectionAbortedException`

Day | Run | OS
-----|-----|-----
8/5 | PR #56915 | ubuntu.1604.amd64.open.rt
8/3 | Official run | ubuntu.1604.amd64.open.rt
8/2 | PR #56735 | ubuntu.1604.amd64.open.rt

```
System.Net.Quic.QuicException : Connection has been shutdown by transport. Error Code: CONNECTION_REFUSED
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventShutdownInitiatedByTransport(State state, ConnectionEvent& connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicConnection.cs:line 249
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.NativeCallbackHandler(IntPtr connection, IntPtr context, ConnectionEvent& connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicConnection.cs:line 684
--- End of stack trace from previous location ---
   at System.Net.Quic.Tests.QuicTestBase`1.<>c__DisplayClass32_0.<<RunClientServer>b__1>d.MoveNext() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 173
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 64
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 91
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 55
   at System.Net.Quic.Tests.QuicTestBase`1.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions) in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 157
   at System.Net.Quic.Tests.QuicConnectionTests`1.ConnectionClosedByPeer_WithPendingAcceptAndConnect_PendingAndSubsequentThrowConnectionAbortedException() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicConnectionTests.cs:line 140
--- End of stack trace from previous location ---
```

**Comment by ManickaP** [comment] 2021-08-06 08:05
@wfurt: is this the same thing as #56875 i.e. a symptom of #55979? Seems like it to me.

**Comment by geoffkizer** [comment] 2021-08-06 08:11
My understanding is that any `CONNECTION_REFUSED` is #55979. But @wfurt can confirm.

**Comment by ManickaP** [comment] 2021-08-10 17:12
Triage: closing as a dupe, we can reopen if it turns out it isn't.
Duplicate of #55979

**Closed by ManickaP** 2021-08-10 17:12 UTC
Labels: test-run-core, area-System.Net.Quic
