### ISSUE TITLE
[System.Net.Http.Json] ReadFromJsonAsync throws System.NotSupportedException : The provided ContentType is not supported - when content is NULL

### ISSUE THREAD

**Issue by arabelaa** [dotnet/runtime#40706] opened 2020-08-12 12:59 UTC
When having a null return type `ReadFromJsonAsync `throws an Exception because `ValidateContent `checks for mediaType.
In this case mediaType is null and an exception is thrown - `System.NotSupportedException : The provided ContentType is not supported; the supported types are 'application/json' and the structured syntax suffix 'application/+json'`. 
```c#
   private static void ValidateContent(HttpContent content)
        {
            if (content == null)
            {
                throw new ArgumentNullException(nameof(content));
            }

            string? mediaType = content.Headers.ContentType?.MediaType;

            if (mediaType == null ||
                !mediaType.Equals(JsonContent.JsonMediaType, StringComparison.OrdinalIgnoreCase) &&
                !IsValidStructuredSyntaxJsonSuffix(mediaType.AsSpan()))
            {
                throw new NotSupportedException(SR.ContentTypeNotSupported);
            }
        }
```

I assume this is by design but I find it restrictive.
Is there a way I can avoid the exception?

Thanks

**Comment by geoffkizer** [comment] 2020-08-12 19:52
Dup of https://github.com/dotnet/runtime/issues/38713

**Comment by karelz** [comment] 2020-08-13 10:27
Duplicate of #38713

**Closed by karelz** 2020-08-13 10:27 UTC
Labels: area-System.Net.Http, untriaged
