### ISSUE TITLE
AOT warning emitted for code inside RuntimeFeature.IsDynamicCodeSupported check

### ISSUE THREAD

**Issue by roji** [dotnet/runtime#79201] opened 2022-12-04 16:19 UTC
In the following code:

```c#
if (RuntimeFeature.IsDynamicCodeSupported)
{
    Foo(); // [IL3050] Using member 'Foo()' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. Foo not compatible.
}

[RequiresDynamicCode("Foo not compatible")]
void Foo()
{
}
```

Since the code is within RuntimeFeature.IsDynamicCodeSupported, it seems like the analyzer shouldn't emit the diagnostic (not critical since the warning can be suppressed).

/cc @jkotas @eerhardt @ajcvickers @AndriySvyryd

**Comment by teo-tsirpanis** [comment] 2022-12-04 16:22
Duplicate of dotnet/linker#2715.

**Closed** 2022-12-04 16:22 UTC
Labels: untriaged, area-NativeAOT-coreclr

**Comment by roji** [comment] 2022-12-04 16:25
Thanks @teo-tsirpanis, looked in the wrong repo.
