### ISSUE TITLE
Bug when deserializing immutable collection property with ignore null values

### ISSUE THREAD

**Issue by mwikstrom** [dotnet/runtime#33546] opened 2020-03-13 07:23 UTC
Reproduction 1:

```cs
class C1
{
    public ImmutableList<int> P { get; set; } = ImmutableList<int>.Empty;
}

static void Bug1()
{
    var options = new JsonSerializerOptions { IgnoreNullValues = true };
    JsonSerializer.Deserialize<C1>("{\"P\":[]}", options);
}
```

`Bug1` throws a `NotSupportedException`:

    System.NotSupportedException: Specified method is not supported.
       at System.Collections.Immutable.ImmutableList`1.System.Collections.IList.Add(Object value)
       at System.Text.Json.JsonSerializer.ApplyObjectToEnumerable(Object value, ReadStack& state, Boolean setPropertyDirectly)
       at System.Text.Json.JsonSerializer.HandleEndArray(JsonSerializerOptions options, ReadStack& state)
       at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
       at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
       at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
       at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)

----

Reproduction 2:

```cs
class C2
{
    public ImmutableHashSet<int> P { get; set; } = ImmutableHashSet<int>.Empty;
}

static void Bug2()
{
    var options = new JsonSerializerOptions { IgnoreNullValues = true };
    JsonSerializer.Deserialize<C2>("{\"P\":[]}", options);
}
```
`Bug2` throws an `InvalidCastException`:

    System.InvalidCastException: Unable to cast object of type 'System.Collections.Immutable.ImmutableHashSet`1[System.Int32]' to type 'System.Collections.IList'.
       at System.Text.Json.JsonSerializer.ApplyObjectToEnumerable(Object value, ReadStack& state, Boolean setPropertyDirectly)
       at System.Text.Json.JsonSerializer.HandleEndArray(JsonSerializerOptions options, ReadStack& state)
       at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
       at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
       at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
       at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)

----

Target framework is: `netcoreapp3.1`

Please notice that `IgnoreNullValues` must be true and property must have an initializer to reproduce this bug.

**Comment by layomia** [comment] 2020-03-13 21:58
Closing as duplicate of https://github.com/dotnet/runtime/issues/2387. This is fixed in 5.0 - can you try the fix?

**Closed by layomia** 2020-03-13 21:58 UTC
Labels: area-System.Text.Json
