### ISSUE TITLE
ProcessNameMatchesScriptName fails intermittently with NativeAot

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#73928] opened 2022-08-15 04:44 UTC
Does the test have a race condition?

```
[FAIL] System.Diagnostics.Tests.ProcessTests.ProcessNameMatchesScriptName
Assert.Equal() Failure
          ↓ (pos 0)
Expected: /bin/sh\0/tmp/#ProcessTests_tvle4bt3.ucl/P···
Actual:   
          ↑ (pos 0)
   at System.Diagnostics.Tests.ProcessTests.ProcessNameMatchesScriptName() + 0x3bc
   at System.Diagnostics.Process!<BaseAddress>+0x105a244
   at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) + 0xd8
```

**Comment by jkotas** [comment] 2022-08-15 05:15
Duplicate of https://github.com/dotnet/runtime/issues/13757

**Closed by jkotas** 2022-08-15 05:15 UTC
Labels: area-System.Diagnostics.Process, untriaged
