### ISSUE TITLE
.Net5 vs .Net6 Performance downgrade in Blazor wasm

### ISSUE THREAD

**Issue by plachor** [dotnet/runtime#51068] opened 2021-04-11 06:41 UTC
### Description

I have made some naive POC to check some performance capabilities and found some serious performance degradation of CPU intensive task in Blazor wasm.  I'm running project directly form console.  bellow is a code snippet of simple page concatenating string and encoding it in to UTF8 (just replace counter page in template).

```
@page "/counter"
@using System.Text
@using System.Diagnostics
@using System.IO

<h1>.Net 6 (6.0.0-preview.3.21201.13)</h1>

<p>Encoding Time: @(string.Join(", ", basedOnEncodingMs.Select((t, i) => $"{i}: {t}")))</p>
<p>StreamWitter Time: @(string.Join(", ", basedOnStreamWriterMs.Select((t, i) => $"{i}: {t}")))</p>

<button class="btn btn-primary" @onclick="BuildByteArrayUsingStreamWriterAndStringBuilders">Test using StreamWriter</button>
<button class="btn btn-primary" @onclick="BuildByteArrayUsingEncodingDirectly">Test using Encoding</button>


@code {
    private List<long> basedOnEncodingMs = new List<long>();
    private List<long> basedOnStreamWriterMs = new List<long>();

    Guid[] preCreatedGuids = Enumerable.Range(1, 1000).Select(t => Guid.NewGuid()).ToArray();

    private Guid next(ref int index)
    {
        if (index + 1 == preCreatedGuids.Length)
            index = 0;

        return preCreatedGuids[++index];
    }

    private void BuildByteArrayUsingStreamWriterAndStringBuilders()
    {
        var sw = Stopwatch.StartNew();
        var mem = new MemoryStream();
        using var stream = new StreamWriter(mem, Encoding.UTF8);

        int id = 0;
        for (int i = 0; i < 10000; i++)
        {
            var sb = new StringBuilder();
            sb.AppendFormat("[{0},{1},{2}", next(ref id), next(ref id), next(ref id));
            sb.AppendFormat(",{0},{1},{2}", next(ref id), next(ref id), next(ref id));
            sb.AppendFormat(",{0},{1},{2}],", next(ref id), next(ref id), next(ref id));
            stream.Write(sb);
        }

        basedOnStreamWriterMs.Add(sw.ElapsedMilliseconds); ;
    }

    private void BuildByteArrayUsingEncodingDirectly()
    {
        var sw = Stopwatch.StartNew();
        var sb = new StringBuilder(2000_000);

        int id = 0;
        for (int i = 0; i < 10000; i++)
        {
            sb.AppendFormat("[{0},{1},{2}", next(ref id), next(ref id), next(ref id));
            sb.AppendFormat(",{0},{1},{2}", next(ref id), next(ref id), next(ref id));
            sb.AppendFormat(",{0},{1},{2}],", next(ref id), next(ref id), next(ref id));
        }

        var bytes = Encoding.UTF8.GetBytes(sb.ToString());
        basedOnEncodingMs.Add(sw.ElapsedMilliseconds);
    }
}

```

### Configuration

Running this code under .Net5 times are:

```
.Net 5

Encoding Time: 0: 915, 1: 831, 2: 816, 3: 843, 4: 794, 5: 792, 6: 809, 7: 814, 8: 836, 9: 812, 10: 833

StreamWitter Time: 0: 1208, 1: 1265, 2: 1184, 3: 1185, 4: 1337, 5: 1185, 6: 1263, 7: 1253, 8: 1180, 9: 1350, 10: 1281
```

After switching to .Net6 (latest preview)

```
.Net 6 (6.0.0-preview.3.21201.13)

Encoding Time: 0: 1882, 1: 2005, 2: 1995, 3: 1929, 4: 1973, 5: 1961, 6: 1968, 7: 1869, 8: 1946, 9: 1858, 10: 1773

StreamWitter Time: 0: 2199, 1: 2088, 2: 2185, 3: 2143, 4: 2232, 5: 2078, 6: 2112, 7: 2414, 8: 2260, 9: 2063, 10: 2194
```

Is this performance degradation expected (like more restrictive usage of UI thread) or unintentional?

**Comment by plachor** [comment] 2021-04-11 07:31
Times were reported for FireFox, but same degradation is observed in Chrome and Edge. For Chrome:

Net5
```
.Net 5
Encoding Time: 0: 618, 1: 625, 2: 601, 3: 631

StreamWitter Time: 0: 999, 1: 984, 2: 1017, 3: 1064
```

.Net6
```
.Net 6 (6.0.0-preview.3.21201.13)
Encoding Time: 0: 2733, 1: 2673, 2: 2706, 3: 2473

StreamWitter Time: 0: 2855, 1: 2864, 2: 2982, 3: 2888
```

**Comment by GrabYourPitchforks** [comment] 2021-04-11 08:06
Possible dupe of https://github.com/dotnet/runtime/issues/50260.

**Comment by lewing** [comment] 2021-06-17 00:46
This was almost certainly the encoding regression.  Please reopen if you can still reproduce this problem.

**Closed by lewing** 2021-06-17 00:46 UTC
Labels: arch-wasm, area-System.Text.Encoding, tenet-performance, untriaged
