### ISSUE TITLE
Analyzer: Introduce an analyzer to recommend upgrading reference tuples to the more efficient value tuples

### ISSUE THREAD

**Issue by geeknoid** [dotnet/runtime#85488] opened 2023-04-27 21:18 UTC
Introduce a performance-centric analyzer to recommend code be upgraded from using the original reference-based tuple abstractions to the more efficient and generally cleaner value tuples.

Our version of this analyzer simply looks for calls to the various Tuple<>.Create functions and constructors and suggests to the user to upgrade their code.

**Comment by buyaa-n** [comment] 2023-05-17 21:17
Duplicate of https://github.com/dotnet/runtime/issues/33791

**Closed by buyaa-n** 2023-05-17 21:17 UTC
Labels: area-System.Runtime, untriaged, code-analyzer
