### ISSUE TITLE
Mono perf regression based on TechEmpower PlaintextPlatform benchmark

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#38718] opened 2020-07-02 18:28 UTC
Recently, there is a ~5% regression on TechEmpower PlaintextPlatform benchmark for all 3 different flavors of mono (JIT, LLVM JIT, LLVM AOT)

Based on bisect, the regression was introduced by https://github.com/dotnet/runtime/commit/778be98101ea3d5deadbaf90765ac18c1e63575b

For mono JIT, with the commit before this one, RPS (requests per second) was 9,173,356; with this commit, RPS was 8,709,109. For LLVM JIT and LLVM AOT, the regression percentage was similar. For LLVM AOT, the number went from 10,244,296 to 9,795,509.

To get the results from your own machine:
1. Clone https://github.com/aspnet/Benchmarks
2. cd Benchmarks/src/BenchmarksDriver2
3. dotnet run -- --config ../BenchmarksApps/Kestrel/PlatformBenchmarks/platform.benchmarks.yml --scenario plaintext --profile aspnet-citrine-lin --application.selfContained true --application.runtimeVersion 5.0.0-preview.8.20324.2 -i 3 --application.options.outputFiles path_to/System.Private.CoreLib.dll --application.options.outputFiles path_to/libcoreclr.so

* Note that System.Private.CoreLib.dll and libcoreclr.so should comes from linux build. They usually live at
artifacts/obj/mono/Linux.x64.Release/mono/mini/.libs/libmonosgen-2.0.so (needs to be rename to libcoreclr.so)
artifacts/bin/mono/Linux.x64.Release/System.Private.CoreLib.dll

/cc @tannergooding @imhameed

**Comment by tannergooding** [comment] 2020-07-02 18:58
Mono fully supports `Vector<T>`, correct? If so, this sounds like a dead-code optimization issue

**Comment by danmosemsft** [comment] 2020-07-02 19:08
How can this commit affect Mono benchmark performance? It's a change to CoreCLR JIT, and associated tests.

**Comment by tannergooding** [comment] 2020-07-02 19:41
It was a change to the library code, to ensure that it properly throws for unsupported T. So it would also impact Mono

**Comment by danmosemsft** [comment] 2020-07-02 19:43
Oh! My bad. I did not scroll enough.

**Comment by imhameed** [comment] 2020-07-02 20:30
I'll look into this later today.

**Comment by fanyang-mono** [comment] 2020-07-21 13:37
With Imran's recent PR #39322, RPS for mono JIT went from 8,351,923 to 8,409,044.

**Comment by SamMonoRT** [comment] 2020-07-27 15:20
We haven't had regular runs in the perf labs since Jun 25th as they are upgrading the driver system and can't be certain if there were other regressions creeping in while the lab was offline(Mono runs not being executed).  We haven't quite achieved the same perf numbers as before, and are waiting on the new runs to be enabled in perf labs. if those numbers from newer runs are trending in positive direction we can close this issue. @fanyang-mono @imhameed

**Comment by vargaz** [comment] 2020-07-28 00:22
Would it be possible to rerun the tests after this:
https://github.com/dotnet/runtime/commit/fa72c754c513e1a681e3df59c87573af59656afd

**Comment by SamMonoRT** [comment] 2020-07-28 11:50
@vargaz - Yes, luckily the official runs(atleast for JIT)  have just restarted in the labs again. We should have never set of results at end of the day.

**Comment by SamMonoRT** [comment] 2020-07-29 15:14
@vargaz new numbers from last night's run are published. For plaintextplatform benchmark, MonoVM- Jit config had ~3% increase. I have not pinpointed the exact change which attributed to the increase, but your change in fa72c75 could surely have had an effect. 
8.828M reqs/sec June 26th
9.081M reqs/sec June 28th (which should have your change merged)

**Comment by SamMonoRT** [comment] 2020-07-31 13:42
We can close this issue.

**Closed by SamMonoRT** 2020-07-31 13:42 UTC
Labels: area-Codegen-JIT-mono, runtime-mono
