### ISSUE TITLE
.net 5 seeks http SPN with port

### ISSUE THREAD

**Issue by galakt** [dotnet/runtime#51980] opened 2021-04-28 11:53 UTC
### Description

We have
* http service `someapi.domain:9200`
* SPNs
  1. HTTP/someapi
  2. HTTP/someapi.domain
* Code 
```c#
using (var client = new HttpClient(new SocketsHttpHandler { Credentials = CredentialCache.DefaultCredentials })
{
    BaseAddress = new Uri("https://someapi.domain:9200")
})
{
    var result = await client.PostAsync("/api", new StringContent("{}", Encoding.UTF8, "application/json"));
    Console.WriteLine(result.StatusCode);
}
```

|                  |     | Windows  | Linux  |
| ------------- |:---:|:-------------:| -----:|
| .NET 3.1     | StatusCode | 200 | 200 |
|                    | Event log part| NTAuthentication#60495737,Initialize,Peer SPN-> '**HTTP/someapi.domain**' | NTAuthentication#37489757,Initialize,Peer SPN-> '**HTTP/someapi.domain**'' |
| .NET 5        | StatusCode |  401|  Unhandled exception. System.ComponentModel.Win32Exception (0x80090020): GSSAPI operation failed with error - Unspecified GSS failure.  Minor code may provide more information (Server not found in Kerberos database). |
|                    | Event log part| NTAuthentication#51812814,Initialize,Peer SPN-> '**HTTP/someapi.domain:9200**' | NTAuthentication#44624228,Initialize,Peer SPN-> '**HTTP/someapi.domain:9200**' |

### Configuration

```
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.201/

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  2.1.814 [/usr/share/dotnet/sdk]
  3.1.407 [/usr/share/dotnet/sdk]
  5.0.201 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.26 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

### Regression?

Yes

### Other information

If create SPN `HTTP/someapi.domain:9200` request returns 200

### Question
Is it intended change in SPN search process and/or I missed something?

**Comment by wfurt** [comment] 2021-04-28 18:04
The 5.0 behavior should match .NET Framework and 3.1 was not right. We can perhaps document that as breaking change between 3.1 and 5.0.

**Comment by SeymourRu** [comment] 2021-04-28 22:58
Sorry, but is there even a reason for such behaviour other than mentioned above?

**Comment by wfurt** [comment] 2021-04-29 03:49
correctness? 
https://social.technet.microsoft.com/wiki/contents/articles/717.service-principal-names-spn-setspn-syntax.aspx

The example there is pretty clear.

**Comment by SeymourRu** [comment] 2021-04-29 13:22
Your example pretty clearly states that port is is _not_ an obligatory. So I can't get an idea why port should be strictly checked if it is not default. This behavior should be at least controllable.

**Comment by karelz** [comment] 2021-04-29 16:29
Duplicate of #51701

**Closed by karelz** 2021-04-29 16:29 UTC
Labels: area-System.Net.Http, needs-breaking-change-doc-created, untriaged
