### ISSUE TITLE
Discrepancy between OTel semantic conventions and built-in System.Net metrics

### ISSUE THREAD

**Issue by xakep139** [dotnet/runtime#97395] opened 2024-01-23 15:18 UTC
Current implementation of https://github.com/dotnet/runtime/blob/55fbb23f8c4e05a17ee27ea19679813f7f5cf285/src/libraries/System.Net.Http/src/System/Net/Http/Metrics/MetricsHandler.cs#L12
has a discrepancy with OpenTelemetry [semantic conventions](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/http-metrics.md#metric-httpclientrequestduration): `server.port` is required, but it's set only when a port isn't a default one: https://github.com/dotnet/runtime/blob/55fbb23f8c4e05a17ee27ea19679813f7f5cf285/src/libraries/System.Net.Http/src/System/Net/Http/Metrics/MetricsHandler.cs#L195

One more thing not related to OTel: the documentation says that `network.protocol.version` is always present, but it's added only when a response is available. I created a PR to fix the documentation (https://github.com/dotnet/docs/pull/39223), but I'm wondering wether it should be fixed on the implementation side, and the docs are correct.

**Comment by xakep139** [comment] 2024-01-23 15:19
cc @antonfirsov @CarnaViire

**Comment by antonfirsov** [comment] 2024-01-23 16:11
> `server.port` is required, but it's set only when a port isn't a default one

[There is a note](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/dotnet/dotnet-http-metrics.md#metric-httpclientrequestduration) in the dotnet-specific part of spec:

>> server.port is not reported when it matches a default one for provided scheme (443 for https and 80 for http)

@lmolkova do you happen to remember why did we specify & implement it like this originally? How did we justify that in this case *Required* doesn't mean *always present* in https://github.com/open-telemetry/semantic-conventions/pull/283?

We can certainly think about making `server.port` always present in 9.0, but we should do it across all the metrics, not just duration and it would be a breaking change. @xakep139 are you facing any practical issues because of the way this works today?

> `network.protocol.version` [...] but I'm wondering wether it should be fixed on the implementation side

It's not possible to include `network.protocol.version` when there is no response, because of implementation constraints, at least not with the current design that doesn't bake request metrics into `SocketsHttpHandler`. An `HttpResponseMessage` is needed to fetch the actual negotiated HTTP version. When an exception is being thrown by the underlying handler, there is no response object to work with.

**Comment by xakep139** [comment] 2024-01-23 16:54
I'm trying to understand whether it's a gap in OTel SemConv, or it was a miss on the .NET implementation side.
Now I understand the limitation, and wondering how other SDKs (i.e. programming languages) might follow the semantic conventions if a request might fail even without being sent (e.g. a DNS resolution has failed). In that case the negotiated HTTP version won't be known, right?
@cijothomas @reyang FYI

**Comment by antonfirsov** [comment] 2024-01-26 15:19
Triage: we should decide if we want to change the `server.port` behavior.

**Comment by lmolkova** [comment] 2024-02-02 17:42
> @lmolkova do you happen to remember why did we specify & implement it like this originally? How did we justify that in this case Required doesn't mean always present in https://github.com/open-telemetry/semantic-conventions/pull/283?

the port was changed after .NET metrics were completely frozen (there were some corner cases where we didn't set `url.scheme` and `server.port` making things ambiguous and maybe some other issues) - here's an existing issue on it https://github.com/dotnet/runtime/issues/94829

**Comment by lmolkova** [comment] 2024-02-02 17:50
@antonfirsov, regarding your comment here:

https://github.com/dotnet/docs/pull/39223#issuecomment-1921952735
I agree it's misleading

> IMO this would be misleading. Imagine the following scenario:

> A user sets request.Version = 2.0
It falls back to 1.1 during negotiation, and an HTTP/1.1 connection starts serving the request
Something goes wrong in the middle (eg. invalid response) and an exception is thrown
Telemetry would log network.protocol.version=2.0 which was not the actual protocol version used for the failing communication attempt

But not having it is also misleading:

- A user sets request.Version = foo/42
- Server dies in attempt to serve this bogus request and never responds
- User tries to understand why a certain subset of requests fails and does not see foo/42 anywhere

I think we might have a small problem in otel semconv where we have one attribute for something ambiguous. Let me create a spec issue on it.


It falls back to 1.1 during negotiation, and an HTTP/1.1 connection starts serving the request
Something goes wrong in the middle (eg. invalid response) and an exception is thrown
Telemetry would log network.protocol.version=2.0 which was not the actual protocol version used for the failing communication attempt

**Comment by antonfirsov** [comment] 2024-02-05 16:55
> Server only supports `bar/123` and dies in attempt to serve this bogus request and never responds

This will result in an `HttpRequestException` with `HttpRequestError.VersionNegotiationError` and also logged in `error.type`, so users won't be left clueless. Note that `HttpRequestMessage.Version` alone is not sufficient to troubleshoot such problems, `VersionPolicy` is also needed, which makes this information hard to standardize (like you mention in https://github.com/open-telemetry/semantic-conventions/issues/686#issuecomment-1924910285, okhttp uses an array of allowed protocols). Also, we [do emit this info in our event logs](https://github.com/dotnet/runtime/blob/b94a82d63580775b2adb0ccac478719b8cd7049b/src/libraries/System.Net.Http/src/System/Net/Http/HttpTelemetry.cs#L37C22-L37C34) and IMO such diagnostic information belongs more to logging than to metrics.

**Comment by lmolkova** [comment] 2024-02-05 18:41
@antonfirsov makes sense, thank you

**Comment by MihaZupan** [comment] 2024-06-05 14:19
Looks like the `version` part has been answered - https://github.com/dotnet/runtime/issues/97395#issuecomment-1927470177.

Closing this as a dupe of #94829 to continue tracking the default `server.port` part.

**Closed by MihaZupan** 2024-06-05 14:19 UTC
Labels: area-System.Net.Http
