### ISSUE TITLE
[dotnet-sdk-8.0.100-preview.3.23159.20]The type of exception changed from TaskCanceledException to OperationCanceledException

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/runtime#83382] opened 2023-03-14 10:11 UTC
### Description

**When run the grpc test with the latest .NET 8 Preview3 runtime, the type of exception changed from TaskCanceledException to OperationCanceledException.**

**GitHub Site:**
[grpc-dotnet/HttpContextStreamReaderTests.cs at master · grpc/grpc-dotnet · GitHub](https://github.com/grpc/grpc-dotnet/blob/master/test/Grpc.AspNetCore.Server.Tests/HttpContextStreamReaderTests.cs)

**Test Project** : https://github.com/grpc/grpc-dotnet/tree/master/test/Grpc.AspNetCore.Server.Tests
**Or App Location checking at**: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1772542/

### Reproduction Steps

**Repro steps:**
**The machine only has dotnet-sdk-8.0.100-preview.3.23159.20 installed. And DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX=2 is set.**
1. Launch cmd window. 
2. Cd to “\grpcdotnetTest04”.
3. Input “dotnet vstest Grpc.AspNetCore.Server.Tests.dll /Tests:MoveNext_TokenCancelledDuringMoveNext_CancelTask”. 
4. Press keyboard “Enter”. 

### Expected behavior

A total of 1 test files matched the specified pattern.
Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: 74 ms - Grpc.AspNetCore.Server.Tests.dll (net7.0)

### Actual behavior

A total of 1 test files matched the specified pattern.
```
  Failed MoveNext_TokenCancelledDuringMoveNext_CancelTask [293 ms]
  Error Message:
   System.OperationCanceledException : A task was canceled.
  ----> System.Threading.Tasks.TaskCanceledException : A task was canceled.
  Stack Trace:
     at System.IO.Pipelines.StreamPipeReader.<ReadAsync>g__Core|38_0(StreamPipeReader reader, CancellationTokenSource tokenSource, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Grpc.AspNetCore.Server.Internal.PipeExtensions.ReadStreamMessageAsync[T](PipeReader input, HttpContextServerCallContext serverCallContext, Func`2 deserializer, CancellationToken cancellationToken) in C:\upgrade\grpc-dotnet\src\Grpc.AspNetCore.Server\Internal\PipeExtensions.cs:line 298
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Grpc.AspNetCore.Server.Internal.HttpContextStreamReader`1.<MoveNext>g__MoveNextAsync|9_0(ValueTask`1 readStreamTask) in C:\upgrade\grpc-dotnet\src\Grpc.AspNetCore.Server\Internal\HttpContextStreamReader.cs:line 44
   at Grpc.AspNetCore.Server.Tests.HttpContextStreamReaderTests.MoveNext_TokenCancelledDuringMoveNext_CancelTask() in C:\upgrade\grpc-dotnet\test\Grpc.AspNetCore.Server.Tests\HttpContextStreamReaderTests.cs:line 76
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated(ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated[T](Func`1 func)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()
--TaskCanceledException
   at Grpc.Tests.Shared.SyncPointMemoryStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken) in C:\upgrade\grpc-dotnet\test\Shared\SyncPointMemoryStream.cs:line 107
   at System.IO.Pipelines.StreamPipeReader.<ReadAsync>g__Core|38_0(StreamPipeReader reader, CancellationTokenSource tokenSource, CancellationToken cancellationToken)

Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: 293 ms - Grpc.AspNetCore.Server.Tests.dll (net7.0)
```

### Regression?

Yes
**Verify Scenarios**:
1). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.100-preview.3.23159.20 : Fail
2). Windows 10 21H2 AMD64 + dotnet-sdk-7.0.202-win-x64 : Pass
3). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.100-preview.1.23112.5 : Pass
4). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.100-preview.3.23157.7 : Pass

### Configuration

**Application Name**: grpc-dotnet
**OS:** Windows10 21h2
**CPU**: x64

### Other information

**Findings:**

1. When we run the test MoveNext_TokenCancelledDuringMoveNext_CancelTask on dotnet-sdk-8.0.100- 
preview.3.23159.20, it throws OperationCanceledException. But Catch is expecting TaskCanceledException

   In previous runtimes, it throws TaskCanceledException, so cases can pass.
  
   In the code If we change TaskCanceledException to OperationCanceledException or Exception, test will pass in dotnet-sdk-8.0.100-preview.3.23159.20
  
  ![image](https://user-images.githubusercontent.com/83067197/224967021-e2eff35d-cedc-4c13-ad23-6f4c24c16fe0.png)
  ![image](https://user-images.githubusercontent.com/83067197/224967052-9faf93db-10a8-4f92-85f5-bf91d4f873ae.png)

2. According to the document, TaskCanceledException inherits from OperationCanceledException.

  [TaskCanceledException Class (System.Threading.Tasks) | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskcanceledexception?view=net-8.0)

3. We found the pull request related to this exception on github:

  https://github.com/dotnet/runtime/pull/82745

@dotnet-actwx-bot @dotnet/compat

**Comment by stephentoub** [comment] 2023-03-14 11:30
We were previously throwing the wrong exception, so this is a bug fix and the impact is by design. The test in question did be changed to handle OCE instead.

In general, we discourage catching TaskCanceledException instead of OperationCanceledException. The former is just the latter the carries a bit of extra information and is otherwise intended to be interchangeable. If we could do it over, we wouldn't have TCE at all, it's caused too many such issues.

Come to think of it, we should add an analyzer that flags TCE catch blocks that dont have an associated OCE backstop. cc: @terrajobst 

cc: @halter73

**Comment by tannergooding** [comment] 2023-03-23 15:15
Closing as "by design"

**Closed** 2023-03-23 15:15 UTC
Labels: area-System.Threading.Tasks
