### ISSUE TITLE
[API Proposal]: Add static factory for InvalidEnumArgumentException

### ISSUE THREAD

**Issue by xtofs** [dotnet/runtime#109099] opened 2024-10-22 03:17 UTC
### Background and motivation

A switch over a Enum **always** requires a default case. The compiler cannot check for exhaustive case coverage because Enums can be created with values that are not listed in the named enum members. 
There is the System.ComponentModel.InvalidEnumArgumentException  exception but constructing it is quite noisy since it should show the Enum type, underlying value of the Enum and the parameter name.

I am proposing a helper method, a static factory method for InvalidEnumArgumentException that makes is easier and therefore I believe more consistent to implement the default case.

```csharp
throw InvalidEnumArgumentException.From(x);
```

### API Proposal

```csharp

class InvalidEnumArgumentException
{
    /* ... */


        /// <summary>
        /// Creates an exception for an invalid enum argument.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="value">the invalid value</param>
        /// <param name="argumentName">the name of the argument</param>
        /// <returns></returns>
        public static InvalidEnumArgumentException From<T>(T value, [CallerArgumentExpression(nameof(value))] string argumentName = null!)
            where T : Enum
        {
            return new InvalidEnumArgumentException(argumentName, (int)Convert.ChangeType(value, typeof(int))!, typeof(T));
        }

}
```

### API Usage

```csharp
MyEnum x = (MyEnum)(-9999);

switch(x)
{
  /* ... */
  default:
    throw InvalidEnumArgumentException.From(x);
}
```

### Alternative Designs

Currently it is not possible to externally extend the  InvalidEnumArgumentException with a static method.

This might change with the "extension everything" proposals but right now, it is only possible by creating a new static class for this which probably leads to inconsistent naming and slow adoption. 

### Risks

- InvalidEnumArgumentException requires an int argument but frankly I am not 100% sure how to get the underlying value of an Enum with a non-int underlying type in an efficient manner.

**Comment by colejohnson66** [comment] 2024-10-22 13:26
Duplicate of #95696

**Comment by colejohnson66** [comment] 2024-10-22 17:36
It also doesn't help that it's in `System.ComponentModel`, a namespace focused more on UI design.

**Comment by colejohnson66** [comment] 2024-10-23 11:57
I agree with you, and I was disappointed that API review denied my proposal. But after watching the discussion, it's understandable. Over half of the team on the call didn't even know this type existed. There's also the nasty bit of it being in `System.ComponentModel` of all places, which is the wrong place for a proper enum-based `ArgumentOutOfRangeException`.

I, too, love the idea of a simple "this enum value is not allowed" exception, and I wish there was something better, but you're probably going to have a hard time getting there.

**Comment by steveharter** [comment] 2024-10-24 16:37
Closing as duplicate of #95696. The recommendation there is to throw `ArgumentOutOfRangeException`.

**Closed by steveharter** 2024-10-24 16:37 UTC
Labels: api-suggestion, area-System.ComponentModel, untriaged
