### ISSUE TITLE
System.Text.Json serializer throws NullReferenceException on `List<Version?>` with a null element

### ISSUE THREAD

**Issue by AArnott** [dotnet/runtime#85983] opened 2023-05-09 16:09 UTC
### Description

The `JsonSerializer` is unable to serialize a `List<Version?>` that contains null elements. Throwing `NullReferenceException` is pretty clearly a sign of an internal bug.

### Reproduction Steps

```cs
[Fact]
public void ImmutableSortedSetWithNullElement()
{
    var set = new List<Version?>();
    set.Add(new Version(1, 2, 3, 4));
    set.Add(null);
    Assert.Equal(2, set.Count);

    string json = JsonSerializer.Serialize(set);
    this.Logger.WriteLine(json);

    List<Version?>? set2 = JsonSerializer.Deserialize<List<Version?>>(json);
    Assert.Equal(2, set2?.Count);
}
```

### Expected behavior

A passing test, after logging 

```json
["1.2.3.4",null]
```

### Actual behavior

The test fails with an unhandled exception:

```
Message: 
    System.NullReferenceException : Object reference not set to an instance of an object.

  Stack Trace: 
    VersionConverter.Write(Utf8JsonWriter writer, Version value, JsonSerializerOptions options)
    ListOfTConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
    JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
    JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
    JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
    JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo`1 jsonTypeInfo)
    JsonSerializer.WriteString[TValue](TValue& value, JsonTypeInfo`1 jsonTypeInfo)
    JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
    JsonRpcSystemTextJsonHeadersTests.ImmutableSortedSetWithNullElement() line 37
```

### Configuration

.NET 6
System.Text.Json 7.0.2

**Comment by eiriktsarpalis** [comment] 2023-05-10 13:50
Duplicate of #85981, see https://github.com/dotnet/runtime/issues/85981#issuecomment-1542252625 for an analysis of the issue.

**Closed by eiriktsarpalis** 2023-05-10 13:50 UTC
Labels: area-System.Text.Json, untriaged
