### ISSUE TITLE
Test failure baseservices\\threading\\threadpool\\bindhandle\\bindhandle1\\bindhandle1.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#65685] opened 2022-02-22 01:22 UTC
Run: [runtime-coreclr r2r-extra 20220220.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1623899&view=ms.vss-test-web.build-test-results-tab&runId=45113364&resultId=100056&paneView=debug)

Failed test:
```
R2R windows x86 Checked jitstress2_tiered @ Windows.10.Amd64.Open

- baseservices\\threading\\threadpool\\bindhandle\\bindhandle1\\bindhandle1.cmd

```
**Error message:**
```
Could Not Find C:\h\w\A9D4097B\w\BB310A2B\e\baseservices\threading\threadpool\bindhandle\bindhandle1\IL-CG2\composite-r2r.dll
Could Not Find C:\h\w\A9D4097B\w\BB310A2B\e\baseservices\threading\threadpool\bindhandle\bindhandle1\bindhandle1.dll.rsp
Unhandled exception. System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)
at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable1 searchPath, Boolean throwOnError) at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable1 searchPath)
at Internal.JitInterface.JitConfigProvider.<>c__DisplayClass5_0.<Initialize>b__0(String libName, Assembly assembly, Nullable1 searchPath) at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags) at Internal.JitInterface.CorInfoImpl.GetJitHost(IntPtr configProvider) at Internal.JitInterface.CorInfoImpl.Startup(CORINFO_OS os) at Internal.JitInterface.JitConfigProvider.Initialize(TargetDetails target, IEnumerable1 jitFlags, IEnumerable1 parameters, String jitPath) at ILCompiler.ReadyToRunCodegenCompilationBuilder.ToCompilation() at ILCompiler.Program.RunSingleCompilation(Dictionary2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary2 unrootedInputFilePaths, HashSet1 versionBubbleModulesHash, CompilerTypeSystemContext typeSystemContext)
at ILCompiler.Program.Run(String[] args)
at ILCompiler.Program.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\A9D4097B\w\BB310A2B\uploads\Reports\baseservices.threading\threadpool\bindhandle\bindhandle1\bindhandle1.output.txt
Raw output:
BEGIN EXECUTION
bindhandle1.dll
1 file(s) copied.
Response file: C:\h\w\A9D4097B\w\BB310A2B\e\baseservices\threading\threadpool\bindhandle\bindhandle1\bindhandle1.dll.rsp
C:\h\w\A9D4097B\w\BB310A2B\e\baseservices\threading\threadpool\bindhandle\bindhandle1\IL-CG2\bindhandle1.dll
-o:C:\h\w\A9D4097B\w\BB310A2B\e\baseservices\threading\threadpool\bindhandle\bindhandle1\bindhandle1.dll
--targetarch:x86
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\A9D4097B\p\System..dll
-r:C:\h\w\A9D4097B\p\Microsoft..dll
-r:C:\h\w\A9D4097B\p\mscorlib.dll
-r:C:\h\w\A9D4097B\p\netstandard.dll
-O
" "dotnet" "C:\h\w\A9D4097B\p\crossgen2\crossgen2.dll" @"C:\h\w\A9D4097B\w\BB310A2B\e\baseservices\threading\threadpool\bindhandle\bindhandle1\bindhandle1.dll.rsp"   -r:C:\h\w\A9D4097B\w\BB310A2B\e\baseservices\threading\threadpool\bindhandle\bindhandle1\IL-CG2*.dll"
Crossgen2 failed with exitcode - -532462766
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\A9D4097B\p
C:\h\w\A9D4097B\w\BB310A2B\e\baseservices\threading\threadpool\bindhandle\bindhandle1\bindhandle1.cmd
Expected: True
Actual:   False


Stack trace
   at baseservices_threading._threadpool_bindhandle_bindhandle1_bindhandle1_._threadpool_bindhandle_bindhandle1_bindhandle1_cmd()
```

**Comment by trylek** [comment] 2022-04-04 20:30
Closing as duplicate of: https://github.com/dotnet/runtime/issues/66570

**Closed by trylek** 2022-04-04 20:30 UTC
Labels: arch-x86, os-windows, JitStress, area-crossgen2-coreclr, untriaged
