### ISSUE TITLE
Test failure: Interop/NativeLibrary/Callback/CallbackStressTest_TargetUnix/CallbackStressTest_TargetUnix.cmd

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#99885] opened 2024-03-18 04:56 UTC
Pipeline: runtime-coreclr r2r

R2R-CG2 linux arm Checked no_tiered_compilation
R2R-CG2 linux arm Checked

https://dev.azure.com/dnceng-public/public/_build/results?buildId=605585&view=ms.vss-test-web.build-test-results-tab

```
06:51:47.310 Running test: Interop/NativeLibrary/Callback/CallbackStressTest_TargetUnix/CallbackStressTest_TargetUnix.cmd
Attempting to collect crash dump: /home/helixbot/dotnetbuild/dumps/crashdump_2424.dmp
Invoking: sudo /root/helix/work/correlation/createdump --crashreport --name "/home/helixbot/dotnetbuild/dumps/crashdump_2424.dmp" 2424 --withheap
Xunit.Sdk.FailException: Test Infrastructure Failure: System.AggregateException: Not all processes in process tree could be terminated. (Operation not permitted)
 ---> System.ComponentModel.Win32Exception (1): Operation not permitted
   --- End of inner exception stack trace ---
   at System.Diagnostics.Process.Kill(Boolean entireProcessTree) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.NonUap.cs:line 31
   at CoreclrTestLib.CoreclrTestWrapperLib.CollectCrashDumpWithCreateDump(Process process, String crashDumpPath, StreamWriter outputWriter)
   at CoreclrTestLib.CoreclrTestWrapperLib.RunTest(String executable, String outputFile, String errorFile, String category, String testBinaryBase, String outputDir)
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Xunit.Assert.Fail(String message) in /_/src/Microsoft.DotNet.XUnitAssert/src/FailAsserts.cs:line 34
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor251|25_252(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass25_0&)
07:31:47.445 Failed test: Interop/NativeLibrary/Callback/CallbackStressTest_TargetUnix/CallbackStressTest_TargetUnix.cmd
```

@dotnet/interop-contrib

**Comment by BruceForstall** [comment] 2024-03-27 16:49
@dotnet/interop-contrib

**Comment by v-wenyuxu** [comment] 2024-04-01 01:59
**Failed in:** [runtime-coreclr r2r-extra 20240330.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=625095&view=ms.vss-test-web.build-test-results-tab&runId=15320266&resultId=116114&paneView=debug)

**Failed tests:**
```
R2R-CG2 linux arm Checked jitstress2 @ (Ubuntu.1804.Arm32.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - Interop/NativeLibrary/Callback/CallbackStressTest_TargetUnix/CallbackStressTest_TargetUnix.cmd
R2R-CG2 linux arm Checked gcstress0xc @ (Ubuntu.1804.Arm32.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - Interop/NativeLibrary/Callback/CallbackStressTest_TargetUnix/CallbackStressTest_TargetUnix.cmd
R2R-CG2 linux arm Checked jitstressregs0x80 @ (Ubuntu.1804.Arm32.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - Interop/NativeLibrary/Callback/CallbackStressTest_TargetUnix/CallbackStressTest_TargetUnix.cmd
R2R-CG2 linux arm Checked jitstressregs8 @ (Ubuntu.1804.Arm32.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - Interop/NativeLibrary/Callback/CallbackStressTest_TargetUnix/CallbackStressTest_TargetUnix.cmd
R2R-CG2 linux arm Checked jitstressregs1 @ (Ubuntu.1804.Arm32.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - Interop/NativeLibrary/Callback/CallbackStressTest_TargetUnix/CallbackStressTest_TargetUnix.cmd
```

**Error message:**
```
 Test Infrastructure Failure: System.AggregateException: Not all processes in process tree could be terminated. (Operation not permitted)
 ---> System.ComponentModel.Win32Exception (1): Operation not permitted
   --- End of inner exception stack trace ---
   at System.Diagnostics.Process.Kill(Boolean entireProcessTree) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.NonUap.cs:line 31
   at CoreclrTestLib.CoreclrTestWrapperLib.CollectCrashDumpWithCreateDump(Process process, String crashDumpPath, StreamWriter outputWriter)
   at CoreclrTestLib.CoreclrTestWrapperLib.RunTest(String executable, String outputFile, String errorFile, String category, String testBinaryBase, String outputDir)
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
```

**Stack trace:**
```
   at Xunit.Assert.Fail(String message) in /_/src/Microsoft.DotNet.XUnitAssert/src/FailAsserts.cs:line 34
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor251|25_252(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass25_0&)
```

**More failure:** [runtime-coreclr r2r 20240330.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=625136&view=ms.vss-test-web.build-test-results-tab&runId=15321148&resultId=116114&paneView=debug)
```
R2R-CG2 linux arm Checked no_tiered_compilation @ (Ubuntu.1804.Arm32.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - Interop/NativeLibrary/Callback/CallbackStressTest_TargetUnix/CallbackStressTest_TargetUnix.cmd
```

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2024-03-31T07:33:02.486Z | coreclr-release-outerloop-nightly | Release-no_tiered_compilation | ubuntu.2004.armarch.open | arm | Interop/NativeLibrary/Callback/CallbackStressTest_TargetUnix/CallbackStressTest_TargetUnix.cmd | Failed | {"CollectionUri":"https://dev.azure.com/dnceng-public/","System.StageAttempt":"1","AzurePipelinesTestRunId":"15321360","System.JobId":"c8f31202-1062-5d6a-be4d-45312a30ae25","System.StageName":"Build","configuration":"Release-no_tiered_compilation","System.PhaseAttempt":"1","operatingSystem":"(Alpine.316.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.17-helix-arm32v7","architecture":"arm","BuildNumber":"20240330.1","DefinitionName":"coreclr-release-outerloop-nightly","Project":"public","System.JobName":"__default","Reason":"Schedule","System.JobAttempt":"1","System.PhaseName":"run_test_p1_R2R_linux_musl_arm_release","DefinitionId":"135","BuildId":"625141"} | Schedule
2024-03-29T07:32:29.466Z | coreclr-release-outerloop-nightly | Release-no_tiered_compilation | ubuntu.2004.armarch.open | arm | Interop/NativeLibrary/Callback/CallbackStressTest_TargetUnix/CallbackStressTest_TargetUnix.cmd | Failed | {"Project":"public","Reason":"Schedule","BuildId":"623537","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseName":"run_test_p1_R2R_linux_musl_arm_release","architecture":"arm","AzurePipelinesTestRunId":"15273954","System.JobName":"__default","DefinitionId":"135","System.PhaseAttempt":"1","System.StageAttempt":"1","BuildNumber":"20240328.1","System.JobAttempt":"1","System.JobId":"c8f31202-1062-5d6a-be4d-45312a30ae25","operatingSystem":"(Alpine.316.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.17-helix-arm32v7","configuration":"Release-no_tiered_compilation","System.StageName":"Build","DefinitionName":"coreclr-release-outerloop-nightly"} | Schedule

**Comment by mikelle-rogers** [comment] 2024-04-02 00:12
@AaronRobinsonMSFT, what is the status of this failure?

**Comment by AaronRobinsonMSFT** [comment] 2024-04-02 03:26
@mikelle-rogers This hasn't been investigated yet. I can say that this is unlikely to be anything related to the interop space. This test and the underlying code only appears to be failing on arm, which makes this far more likely to be an issue with the JIT or R2R infrastructure.

**Comment by jkotas** [comment] 2024-04-02 06:52
> AggregateException: Not all processes in process tree could be terminated.

This is same problem as https://github.com/dotnet/runtime/issues/93321 . It seems to be a race condition in System.Diagnostics.Process.Kill(bool entireProcessTree)

**Comment by jkotas** [comment] 2024-04-02 06:52
Duplicate of https://github.com/dotnet/runtime/issues/93321

**Closed by jkotas** 2024-04-02 06:52 UTC
Labels: area-Interop-coreclr, untriaged, blocking-clean-ci-optional
