### ISSUE TITLE
2nd call to MemoryCache.Set() with the same key erases entry if cache is full

### ISSUE THREAD

**Issue by anderslyman** [dotnet/runtime#36039] opened 2020-03-10 23:09 UTC
### Describe the bug
If I make a call to `MemoryCache.Set()` to update an _existing_ item when the cache is full (size limit reached), the item is instead removed.

### To Reproduce
LINQPad script: http://share.linqpad.net/kmpxj3.linq

```
void Main()
{
    var memoryCache = new MemoryCache(new MemoryCacheOptions
    {
        SizeLimit = 1 // <-- Setting to 2 fixes the issue
    });

    Set(memoryCache);
    memoryCache.Get("A").Dump(); // Yields 1
    Set(memoryCache);
    memoryCache.Get("A").Dump(); // Yields null
}

private void Set(MemoryCache memoryCache)
{
    //memoryCache.Remove("A"); // <-- Also fixes the issue

    memoryCache.Set("A", 1, new MemoryCacheEntryOptions
    {
        AbsoluteExpirationRelativeToNow = TimeSpan.FromDays(1), 
        SlidingExpiration = TimeSpan.FromDays(1), 
        Size = 1
    });
}
```

### Expected behavior
I would expect the item to be updated.

### Additional Info
Initially posted a question here:
https://stackoverflow.com/questions/60626316/2nd-call-to-memorycache-set-with-the-same-key-erases-entry-if-cache-is-full

There was a link added by another user to a related, closed bug: https://github.com/dotnet/extensions/issues/1889
While this is a different scenario, it seems like it might have the same root cause.

**Comment by ericstj** [comment] 2020-07-07 15:49
Agreed it appears to be same root case.  Set actually ends up calling CreateEntry.  If you wanted to update an entry you could try calling TryGetValue although here that wouldn't help since your value is not mutable (int).  I suspect that there is something that could be tweaked here to improve the case where two entries are created with the same key name.  We can take a look.

**Comment by anderslyman** [comment] 2020-07-13 17:47
In our case it was simple to adjust the capacity of the cache with `desiredSize + 1` since we know ahead of time how many entries we want to store.
It'd be good to fix it, but I think leaving this as a known bug along with a note in the docs would be pretty acceptable too.

**Comment by danmoseley** [comment] 2022-07-26 00:30
There is a test for this, which suggests it was intentional behavior:
https://github.com/dotnet/runtime/blob/3921b8efbd4aff7f8e7730423f0af81d883b58f4/src/libraries/Microsoft.Extensions.Caching.Memory/tests/CapacityTests.cs#L274

@Tratcher

**Comment by Tratcher** [comment] 2022-08-09 22:51
@danmoseley that test covers the case when the size limit is exceeded. In this issue the cache is full but it should be able to replace one entry with another of the same size. This seems like a bug with how the limits are enforced.

I think the issue is that the prior entry is marked as expired, but its size isn't subtracted until after the capacity check:
https://github.com/dotnet/runtime/blob/22ba36d5b0e78c984d8e0b24ae389cabd345ec30/src/libraries/Microsoft.Extensions.Caching.Memory/src/MemoryCache.cs#L129-L132
https://github.com/dotnet/runtime/blob/22ba36d5b0e78c984d8e0b24ae389cabd345ec30/src/libraries/Microsoft.Extensions.Caching.Memory/src/MemoryCache.cs#L142
https://github.com/dotnet/runtime/blob/22ba36d5b0e78c984d8e0b24ae389cabd345ec30/src/libraries/Microsoft.Extensions.Caching.Memory/src/MemoryCache.cs#L160

**Comment by adamsitnik** [comment] 2023-11-15 10:48
Related issue: https://github.com/dotnet/runtime/issues/42624

**Closed** 2024-06-28 19:34 UTC
Labels: bug, help wanted, area-Extensions-Caching, in-pr
