### ISSUE TITLE
Remove BinaryFormatter usage from ResourceReader

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#39290] opened 2020-07-14 16:52 UTC
Ref:

https://github.com/dotnet/runtime/blob/af828ae24cd094b7f0abfe5f208e329049934b37/src/libraries/System.Private.CoreLib/src/System/Resources/ResourceReader.Core.cs#L67-L85

This issue tracks the removal and replacement of this code per [the `BinaryFormatter` obsoletion plan](https://github.com/dotnet/designs/pull/141).

**Comment by pgovind** [comment] 2021-04-08 23:39
Alright, so I spent some time looking at the BinaryFormatter usage here. It is very simple to hide the BinaryFormatter usage in `ResourceReader.Core.cs` behind an AppContextSwitch, however, I think this is premature at this point. First, some context: Our own tools (ResGen, WinForms) create resx files at the moment that may contain binary formatted data. Assuming we have a serialized resx file, there are 2 ways to deserialize at the moment: Using ResourceReader from S.P.CoreLib or using ResourceReader from S.Resources.Extensions (SRE). BF usage in SRE is tracked by https://github.com/dotnet/runtime/issues/39292. So, this means that currently both these code paths are being used to deserialize their resx files. So, our options here seem to be:
1. Follow the deprecation steps outlined by @ericstj in https://github.com/dotnet/runtime/issues/39292. This would mean this issue will remain blocked until https://github.com/dotnet/runtime/issues/39292 is fixed.
2. Deprecate BF usage in S.P.CoreLib's `ResourceReader` alone by hiding it behind an AppContext switch. This will likely "break" anyone not using SRE currently (possibly everyone generating resx files in NET Framework and reading them in .NET Core) but these folks can always turn the AppContext switch on to preserve current behavior. If we decide to go down this road, we need to determine when we want to do the deprecation. We can do it right now for Preview 4 or we can do it in P1 of the next release.

Curious to hear more opinions here.

cc @GrabYourPitchforks @ericstj @jeffhandley @jkotas

**Comment by jkotas** [comment] 2021-04-11 08:01
> It is very simple to hide the BinaryFormatter usage in ResourceReader.Core.cs behind an AppContextSwitch

The binary formatter usage is behind `System.Resources.ResourceManager.AllowCustomResourceTypes` switch in this file already. 

> This would mean this issue will remain blocked until #39292 is fixed.

Right, the real for this issue is WinForms (https://github.com/dotnet/runtime/issues/39292#issuecomment-706339081). I think it should be fine to resolve this issue as as dup of #39292.

**Comment by danmoseley** [comment] 2023-05-25 02:49
dupe of #39292

**Closed by danmoseley** 2023-05-25 02:49 UTC
Labels: enhancement, area-System.Resources
