### ISSUE TITLE
AssemblyLoadContext not unloaded when server started and stopped

### ISSUE THREAD

**Issue by lukaspirkl** [dotnet/runtime#90114] opened 2023-08-04 09:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I want to create an application that can load and unload plugins during runtime. Each plugin should be able to provide gRPC endpoints. My first idea was to add/remove endpoints to an already running server dynamically. But I had problems when the server was holding references to plugin types so unloading was not working. So I stepped back and tried to start a separate server for each plugin. I am following [the official guide for debugging unloadability](https://learn.microsoft.com/en-us/dotnet/standard/assembly/unloadability).

I crated simple project which can demonstrate the issue. 
https://github.com/lukaspirkl/UnloadablePluginWithServer

There is just one plugin and it is [almost empty](https://github.com/lukaspirkl/UnloadablePluginWithServer/blob/master/Plugin/Plugin.cs#L7). The main application is loading [the plugin into its own AssemblyLoadContext](https://github.com/lukaspirkl/UnloadablePluginWithServer/blob/master/ExperimentOneProcess/Program.cs#L33C8-L36C47), then [it creates and starts the server](https://github.com/lukaspirkl/UnloadablePluginWithServer/blob/master/ExperimentOneProcess/Program.cs#L38C9-L41C107). When the plugin should be unloaded [the server is stopped and disposed](https://github.com/lukaspirkl/UnloadablePluginWithServer/blob/master/ExperimentOneProcess/Program.cs#L72C13-L74C29). After this [the AssemblyLoadContext is unloaded](https://github.com/lukaspirkl/UnloadablePluginWithServer/blob/master/ExperimentOneProcess/Program.cs#L79C9-L82C24) and I am saving WeakReference to know whether[ the unload is successful](https://github.com/lukaspirkl/UnloadablePluginWithServer/blob/master/ExperimentOneProcess/Program.cs#L57C9-L64C10). The problem is that the reference is always alive which means that the AssemblyLoadContext is not unloaded.

I tried to use WinDbg to see what is holding the reference. But the `!dumpheap -type LoaderAllocator` doesn't show anything. When I comment out [the line that is starting the server](https://github.com/lukaspirkl/UnloadablePluginWithServer/blob/master/ExperimentOneProcess/Program.cs#L41), the AssemblyLoadContext is unloaded correctly.

### Expected Behavior

The AssemblyLoadContext is unloaded correctly when the server is disposed and it is not holding the references to types from AssemblyLoadContext.

### Steps To Reproduce

Just run the console app from https://github.com/lukaspirkl/UnloadablePluginWithServer

### .NET Version

7.0.306

### Anything else?

Target framework: net6.0-windows

**Comment by adityamandaleeka** [comment] 2023-08-07 21:51
cc @janvorli

**Comment by janvorli** [comment] 2023-08-14 15:41
I'll take a look. Based on the details @adityamandaleeka has shared, it sounds like some JIT generated locals in the async machinery are holding the context alive. I guess that it might be the case that for async marking the `UnloadAsync` as `NoInlining` is not sufficient and that the `var alcWeakRef = await UnloadAsync();` leaves a state for the async state machine in the frame of the `UnloadPluginAsync`.

**Comment by janvorli** [comment] 2023-08-14 18:40
My feeling was correct. The async state machinery for the `UnloadAsync` method was holding the PluginLoadContext in some JIT generated locals. The following change fixes the issue. The trick is to do the unload in a sync method marked as NoInlining so that no async state machinery gets created for it. And it is also important to not to access the `m_LoadContext` in any of the async methods, as the JIT might just create a temp local for it.

```c#
    [MethodImpl(MethodImplOptions.NoInlining)]
    private WeakReference DoUnloadAsync()
    {
        var weakRef = new WeakReference(m_LoadContext);
        m_LoadContext?.Unload();
        m_LoadContext = null;
        return weakRef;
    }

    private async Task<WeakReference> UnloadAsync()
    {
        if (m_Server != null)
        {
            await m_Server.StopAsync();
            await m_Server.DisposeAsync();
            m_Server = null;
        }

        m_Plugin = null;

        return DoUnloadAsync();
    }
```

**Comment by agocke** [comment] 2023-08-15 18:36
Closed as by design

**Closed by agocke** 2023-08-15 18:36 UTC
Labels: area-AssemblyLoader-coreclr, untriaged
