### ISSUE TITLE
Wrong hyperlink on nuget.org

### ISSUE THREAD

**Issue by Der-Kraken** [dotnet/runtime#40077] opened 2020-07-29 12:59 UTC
Hi,

the hyperlink "Source repository" on [nuget.org/packages/Microsoft.Extensions.Logging.Abstractions](https://www.nuget.org/packages/Microsoft.Extensions.Logging.Abstractions/) is directing to [github.com/dotnet/extensions](https://github.com/dotnet/extensions) but should direct to [github.com/dotnet/runtime](https://github.com/dotnet/runtime).

**Comment by campersau** [comment] 2020-07-29 16:40
It does since the 5.0 previews e.g. https://www.nuget.org/packages/Microsoft.Extensions.Logging.Abstractions/5.0.0-preview.7.20364.11
The repository has moved serveral times in the past and nuget packages are immutable.

**Comment by KalleOlaviNiemitalo** [comment] 2020-07-29 18:37
<https://github.com/NuGet/NuGetGallery/issues/7537> could make the "Source Repository" hyperlink at <https://www.nuget.org/packages/Microsoft.Extensions.Logging.Abstractions/3.1.6> point to <https://github.com/aspnet/Extensions/tree/be18161fbed286d6fb7a7b1c7999ce70a50cf3eb> instead. Then it would redirect to <https://github.com/dotnet/extensions/tree/be18161fbed286d6fb7a7b1c7999ce70a50cf3eb> and you could navigate to the source code at <https://github.com/dotnet/extensions/tree/be18161fbed286d6fb7a7b1c7999ce70a50cf3eb/src/Logging/Logging.Abstractions/src>.

**Comment by ViktorHofer** [comment] 2020-07-29 22:26
Closing as by design.

**Closed by ViktorHofer** 2020-07-29 22:26 UTC
Labels: area-Microsoft.Extensions
