### ISSUE TITLE
.net core 8 UDP Socket gets stuck on the first endpoint it sends to

### ISSUE THREAD

**Issue by moustakakisCon** [dotnet/runtime#99863] opened 2024-03-16 15:04 UTC
### Description

in .net core 8 (dotnet-sdk-8.0.203) the UDP socket will only send to the first endpoint used. trying to send to another endpoint ends up sending it in the first one used.

![Screenshot 2024-03-16 161535](https://github.com/dotnet/runtime/assets/672879/e124351d-7a97-40bc-b954-d8a1bc0a8797)

![Screenshot 2024-03-16 161902](https://github.com/dotnet/runtime/assets/672879/4a63ee84-e6b3-4dce-8b77-c32b8698748b)

### Reproduction Steps

[not available at the moment]

### Expected behavior

Expected behaviour is for the socket to be able to send to the endpoint provided

### Actual behavior

Actual behaviour is that the socket will only send to the first endpoint used.

### Regression?

issue is **not** present in .net core 6 nor .net core 7

**Comment by MichalPetryka** [comment] 2024-03-16 15:28
Duplicate of #97965?

**Comment by wfurt** [comment] 2024-03-19 04:12
It would be great if you can try the 9.0 build @moustakakisCon  https://github.com/dotnet/installer
I'm trying to get the fix to servicing https://github.com/dotnet/runtime/pull/99695

**Comment by wfurt** [comment] 2024-03-19 04:21
this was fixes in 9.0 by https://github.com/dotnet/runtime/pull/98134. Backport is waiting for approval.

**Comment by moustakakisCon** [comment] 2024-03-19 09:42
@wfurt i can confirm that in dotnet-sdk-9.0.100-preview.3.24165.20-win-x64 the issue is fixed

**Comment by karelz** [comment] 2024-03-26 21:10
Duplicate #97965

**Closed by karelz** 2024-03-26 21:10 UTC
Labels: area-System.Net.Sockets
