### ISSUE TITLE
Assertion failed 'm_comp->lvaGetDesc(m_srcLclNode)->IsAddressExposed()' during 'Optimize index checks'

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#73628] opened 2022-08-09 16:30 UTC
```c#
// Found by Antigen
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
public class TestClass
{
    public struct S1
    {
        public sbyte sbyte_0;
        public short short_1;
    }
    public struct S3
    {
        public struct S3_D1_F1
        {
            public struct S3_D2_F2
            {
                public S1 s1_4;
            }
            public struct S3_D2_F3
            {
            }
            public float float_3;
        }
        public struct S3_D1_F3
        {
            public struct S3_D2_F1
            {
                public double double_8;
            }
            public int int_13;
        }
        public ushort ushort_7;
    }
    public void Method0()
    {
        unchecked
        {
            short short_197 = 0;
            long long_199 = 0;
            float float_201 = 3.0784314f;
            ushort ushort_203 = 5;
            S1 s1_206 = new S1();
            S1 s1_207 = s1_206;
            S3.S3_D1_F1.S3_D2_F2 s3_s3_d1_f1_s3_d2_f2_209 = new S3.S3_D1_F1.S3_D2_F2();
            S3.S3_D1_F1.S3_D2_F2 s3_s3_d1_f1_s3_d2_f2_210 = s3_s3_d1_f1_s3_d2_f2_209;
            S3.S3_D1_F1.S3_D2_F3 s3_s3_d1_f1_s3_d2_f3_211 = new S3.S3_D1_F1.S3_D2_F3();
            S3.S3_D1_F1.S3_D2_F3 s3_s3_d1_f1_s3_d2_f3_212 = s3_s3_d1_f1_s3_d2_f3_211;
            S3.S3_D1_F1 s3_s3_d1_f1_213 = new S3.S3_D1_F1();
            S3.S3_D1_F1 s3_s3_d1_f1_214 = s3_s3_d1_f1_213;
            S3.S3_D1_F3.S3_D2_F1 s3_s3_d1_f3_s3_d2_f1_215 = new S3.S3_D1_F3.S3_D2_F1();
            S3.S3_D1_F3 s3_s3_d1_f3_217 = new S3.S3_D1_F3();
            S3.S3_D1_F3 s3_s3_d1_f3_218 = s3_s3_d1_f3_217;
            S3 s3_219 = new S3();
            S3 s3_220 = s3_219;
            Log("s3_s3_d1_f", s3_s3_d1_f3_s3_d2_f1_215.double_8);
            Log("short_197", short_197);
            Log("s3_s3_d1_f", s3_s3_d1_f1_s3_d2_f2_209.s1_4.short_1);
            Log("long_199", long_199);
            Log("s1_207.sby", s1_207.sbyte_0);
            Log("s3_s3_d1_f", s3_s3_d1_f1_s3_d2_f2_210.s1_4.sbyte_0);
            Log("float_201", float_201);
            Log("s3_s3_d1_f", s3_s3_d1_f1_214.float_3);
            Log("ushort_203", ushort_203);
            Log("s1_206", s1_206);
            Log("s3_s3_d1_f", s3_s3_d1_f1_s3_d2_f3_211);
            Log("s3_s3_d1_f", s3_s3_d1_f1_s3_d2_f3_212);
            Log("s3_s3_d1_f", s3_s3_d1_f1_213);
            Log("s3_s3_d1_f", s3_s3_d1_f3_217);
            Log("s3_s3_d1_f", s3_s3_d1_f3_218);
            Log("s3_219", s3_219);
            Log("s3_220", s3_220);
            return;
        }
    }
    public static void Main(string[] args)
    {
        new TestClass().Method0();
    }
    [MethodImpl(MethodImplOptions.NoInlining)]
    public static void Log(string varName, object varValue)
{}    }

/*
Environment:

set COMPlus_TieredCompilation=0
set COMPlus_JitStress=1

Assert failure(PID 44016 [0x0000abf0], Thread: 65364 [0xff54]): Assertion failed 'm_comp->lvaGetDesc(m_srcLclNode)->IsAddressExposed()' in 'TestClass:Method0():this' during 'Optimize index checks' (IL size 414; hash 0x46e9aa75; FullOpts)
    File: D:\git\dotnet-runtime\src\coreclr\jit\morphblock.cpp Line: 746
    Image: d:\git\dotnet-runtime\artifacts\tests\coreclr\windows.x64.Checked\tests\Core_Root\CoreRun.exe
*/

**Comment by JulieLeeMSFT** [comment] 2022-08-09 16:39
@AndyAyersMS for assertion failure in Morph.

**Comment by SingleAccretion** [comment] 2022-08-09 18:18
This is a VN bug.

```scala
***** BB01, STMT00014(before)
N003 (  5,  6) [000334] -A------R--                         *  ASG       int   
N002 (  3,  4) [000332] D------N---                         +--*  LCL_FLD   int    V15 loc14        d:2[+0]
N001 (  1,  1) [000333] -----------                         \--*  LCL_VAR   int    V38 tmp20        u:2

N001 [000333]   LCL_VAR   V38 tmp20        u:2 => $40 {IntCns 0}
N002 [000332]   LCL_FLD   V15 loc14        d:2[+0] => $VN.Void
    VNForLoadStoreBitcast returns $200 {BitCast<struct <- int>($40)}
Tree [000334] assigned VN to local var V15/2: $200 {BitCast<struct <- int>($40)}
N003 [000334]   ASG       => $VN.Void

***** BB01, STMT00014(after)
N003 (  5,  6) [000334] -A------R--                         *  ASG       int    $VN.Void
N002 (  3,  4) [000332] D------N---                         +--*  LCL_FLD   int    V15 loc14        d:2[+0] $VN.Void
N001 (  1,  1) [000333] -----------                         \--*  LCL_VAR   int    V38 tmp20        u:2 $40

***** BB01, STMT00016(before)
N003 (  7,  8) [000340] -A------R--                         *  ASG       ushort
N002 (  4,  5) [000338] D------N---                         +--*  LCL_FLD   ushort V17 loc16        d:2[+0]
N001 (  2,  2) [000339] -----------                         \--*  LCL_VAR   ushort V39 tmp21        u:2

N001 [000339]   LCL_VAR   V39 tmp21        u:2 => $40 {IntCns 0}
N002 [000338]   LCL_FLD   V17 loc16        d:2[+0] => $VN.Void
    VNForLoadStoreBitcast returns $200 {BitCast<struct <- int>($40)}
Tree [000340] assigned VN to local var V17/2: $200 {BitCast<struct <- int>($40)}
N003 [000340]   ASG       => $VN.Void

***** BB01, STMT00016(after)
N003 (  7,  8) [000340] -A------R--                         *  ASG       ushort $VN.Void
N002 (  4,  5) [000338] D------N---                         +--*  LCL_FLD   ushort V17 loc16        d:2[+0] $VN.Void
N001 (  2,  2) [000339] -----------                         \--*  LCL_VAR   ushort V39 tmp21        u:2 $40
```

There is an assumption with bitcasts that the source VN represents a value of the same "width" as the target, that's why it doesn't encode the size for `TYP_STRUCT`. The problem is that structs can have "true" small types, while non-struct VNs cannot (except for `VNF_Cast`, but that's a separate issue).

The fix would be to expand the target type encoding. I'll take care of it.

**Comment by AndyAyersMS** [comment] 2022-08-09 22:41
@SingleAccretion thanks.

**Comment by JulieLeeMSFT** [comment] 2022-08-11 06:05
Assigned to @jakobbotsch for VN bug.

**Closed** 2022-08-11 19:35 UTC
Labels: bug, area-CodeGen-coreclr, in-pr
