### ISSUE TITLE
Mistake in isProxyAuth condition in the InnerSendAsync

### ISSUE THREAD

**Issue by Dimamar** [dotnet/runtime#94504] opened 2023-11-08 08:42 UTC
### Description

I think it:
```
// runtime/tree/main/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/AuthenticationHelper.cs: 206
private static ValueTask<HttpResponseMessage> InnerSendAsync(HttpRequestMessage request, bool async, bool isProxyAuth, bool doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
        {
            return isProxyAuth ?
                pool.SendWithVersionDetectionAndRetryAsync(request, async, doRequestAuth, cancellationToken) :
                pool.SendWithProxyAuthAsync(request, async, doRequestAuth, cancellationToken);
        }
```
can be mistake. The positive line of the `if` should call `pool.SendWithProxyAuthAsync(...)`.

### Reproduction Steps

Just look to the /runtime/tree/main/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/AuthenticationHelper.cs: 206 InnerSendAsync(...)
and it's condition
```
return isProxyAuth ?
                pool.SendWith...
                pool.SendWithProxyAuth...
```
:)

### Expected behavior

Invert the condition in
/runtime/tree/main/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/AuthenticationHelper.cs: 206 InnerSendAsync(...)
to

```
return isProxyAuth ?
                pool.SendWithProxyAuth...
                pool.SendWith...
```

### Actual behavior

I didn't found any wrong behaviour, but I can`t to test it in a deep

**Comment by ManickaP** [comment] 2023-11-08 09:19
The parameter means that the call stack is already in the ProxyAuth call chain and now we need to actually send request.
If you'd invert the calls in the condition as you suggest, you'd end up in an infinite loop of:
[InnerSendAsync](https://source.dot.net/System.Net.Http/R/64d0a44b8dcc6132.html)
[SendWithProxyAuthAsync](https://source.dot.net/System.Net.Http/R/c78c46ef8097870a.html)
[SendWithProxyAuthAsync](https://source.dot.net/System.Net.Http/R/a96a2f5bb543c8bc.html)
[SendWithAuthAsync](https://source.dot.net/System.Net.Http/R/d3357106053b8857.html)
[InnerSendAsync](https://source.dot.net/System.Net.Http/R/64d0a44b8dcc6132.html)

Hope this helped. 

As this is not a bug, I'm closing this, but feel free to continue the discussion if you have more questions.

**Closed by ManickaP** 2023-11-08 09:19 UTC
Labels: area-System.Net.Http, untriaged

**Comment by Dimamar** [comment] 2023-11-08 16:05
Thanks for explanation.
Maybe, to rename parameter `isProxyAuth` to `isProxyAuthHasApplyed` can made the method logic clearly.
