### ISSUE TITLE
Test failure JIT\\HardwareIntrinsics\\X86\\Sse41\\ConvertToVector128_ro\\ConvertToVector128_ro.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#66629] opened 2022-03-15 01:33 UTC
Run: [runtime-coreclr r2r-extra 20220313.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1661469&view=ms.vss-test-web.build-test-results-tab&runId=45727202&resultId=100159&paneView=debug)

Failed test:
```
R2R windows x64 Checked forcerelocs @ Windows.10.Amd64.Open

- JIT\\HardwareIntrinsics\\X86\\Sse41\\ConvertToVector128_ro\\ConvertToVector128_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse41\\DotProduct_ro\\DotProduct_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse41\\MinHorizontal_r\\MinHorizontal_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse41\\Blend_ro\\Blend_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse41\\DotProduct_r\\DotProduct_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse41\\LoadAlignedVector128NonTemporal_ro\\LoadAlignedVector128NonTemporal_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse41_Overloaded\\Sse41_Overloaded_r\\Sse41_Overloaded_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse41_Overloaded\\Sse41_Overloaded_ro\\Sse41_Overloaded_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse41.X64\\Sse41.X64_r\\Sse41.X64_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse41\\MultipleSumAbsoluteDifferences_ro\\MultipleSumAbsoluteDifferences_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse41\\MultipleSumAbsoluteDifferences_r\\MultipleSumAbsoluteDifferences_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse41\\Sse41_ro\\Sse41_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse41\\Blend_r\\Blend_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse41.X64\\Sse41.X64_ro\\Sse41.X64_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse41\\Multiply_ro\\Multiply_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse41\\MinHorizontal_ro\\MinHorizontal_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse41\\LoadAlignedVector128NonTemporal_r\\LoadAlignedVector128NonTemporal_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse41\\Sse41_r\\Sse41_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse41\\Multiply_r\\Multiply_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse41\\ConvertToVector128_r\\ConvertToVector128_r.cmd
```
**Error message:**
```
Could Not Find C:\h\w\C0D909DB\w\B14009A6\e\JIT\HardwareIntrinsics\X86\Sse41\ConvertToVector128_ro\IL-CG2\composite-r2r.dll
Could Not Find C:\h\w\C0D909DB\w\B14009A6\e\JIT\HardwareIntrinsics\X86\Sse41\ConvertToVector128_ro\ConvertToVector128_ro.dll.rsp
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'System.IO.Compression, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. An attempt was made to load a program with an incorrect format.
File name: 'System.IO.Compression, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
at System.Reflection.PortableExecutable.PEReader.DecodeEmbeddedPortablePdbDebugDirectoryData(AbstractMemoryBlock block)
at System.Reflection.PortableExecutable.PEReader.ReadEmbeddedPortablePdbDebugDirectoryData(DebugDirectoryEntry entry)
at Internal.TypeSystem.Ecma.PortablePdbSymbolReader.TryOpenEmbedded(PEReader peReader, MetadataStringDecoder stringDecoder)
at ILCompiler.CompilerTypeSystemContext.AddModule(String filePath, String expectedSimpleName, Boolean useForBinding, ModuleData oldModuleData)
at ILCompiler.CompilerTypeSystemContext.GetOrAddModuleFromPath(String filePath, Boolean useForBinding)
at ILCompiler.Program.Run(String[] args)
at ILCompiler.Program.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\C0D909DB\w\B14009A6\uploads\Reports\JIT.HardwareIntrinsics\X86\Sse41\ConvertToVector128_ro\ConvertToVector128_ro.output.txt
Raw output:
BEGIN EXECUTION
ConvertToVector128_ro.dll
TestLibrary.dll
2 file(s) copied.
Response file: C:\h\w\C0D909DB\w\B14009A6\e\JIT\HardwareIntrinsics\X86\Sse41\ConvertToVector128_ro\ConvertToVector128_ro.dll.rsp
C:\h\w\C0D909DB\w\B14009A6\e\JIT\HardwareIntrinsics\X86\Sse41\ConvertToVector128_ro\IL-CG2\ConvertToVector128_ro.dll
-o:C:\h\w\C0D909DB\w\B14009A6\e\JIT\HardwareIntrinsics\X86\Sse41\ConvertToVector128_ro\ConvertToVector128_ro.dll
--targetarch:x64
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\C0D909DB\p\System..dll
-r:C:\h\w\C0D909DB\p\Microsoft..dll
-r:C:\h\w\C0D909DB\p\mscorlib.dll
-r:C:\h\w\C0D909DB\p\netstandard.dll
-O
" "dotnet" "C:\h\w\C0D909DB\p\crossgen2\crossgen2.dll" @"C:\h\w\C0D909DB\w\B14009A6\e\JIT\HardwareIntrinsics\X86\Sse41\ConvertToVector128_ro\ConvertToVector128_ro.dll.rsp"   -r:C:\h\w\C0D909DB\w\B14009A6\e\JIT\HardwareIntrinsics\X86\Sse41\ConvertToVector128_ro\IL-CG2*.dll"
Crossgen2 failed with exitcode - -532462766
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\C0D909DB\p
C:\h\w\C0D909DB\w\B14009A6\e\JIT\HardwareIntrinsics\X86\Sse41\ConvertToVector128_ro\ConvertToVector128_ro.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_HardwareIntrinsics._X86_Sse41_ConvertToVector128_ro_ConvertToVector128_ro_._X86_Sse41_ConvertToVector128_ro_ConvertToVector128_ro_cmd()
```

**Comment by BruceForstall** [comment] 2022-03-16 01:52
@mangod9 @trylek This looks like the same as https://github.com/dotnet/runtime/issues/66690

**Comment by trylek** [comment] 2022-04-04 20:21
Closing as duplicate of: https://github.com/dotnet/runtime/issues/65646

**Closed by trylek** 2022-04-04 20:21 UTC
Labels: os-windows, arch-x64, area-crossgen2-coreclr
