### ISSUE TITLE
TIME OUT - Mono llvmfullaot Pri0 Runtime Tests Run Linux arm64 release

### ISSUE THREAD

**Issue by thaystg** [dotnet/runtime#66083] opened 2022-03-02 14:14 UTC
We couldn't find any obvious change that could be causing it between these commits:
git diff a82d92c36624e89e831e37515a9b0c95a4cfe183..c8da2fd5d8b841fc34845218158399cf35eb8bcf

Log which the timeout started:
https://dev.azure.com/dnceng/public/_build/results?buildId=1633880&view=results

**Comment by thaystg** [comment] 2022-03-02 14:15
@MattGal did we have any relevant infra change between friday and saturday?

**Comment by MattGal** [comment] 2022-03-02 16:59
> @MattGal did we have any relevant infra change between friday and saturday?

Aside from serious "world-on-fire" hot-fixes we will not make infrastructure changes on a Friday evening or Saturday morning.  If something's going to roll out and affect you, it'll almost always be on a Wednesday in the morning time for the Pacific time zone.

If your investigation does make you think there are infra issues, please feel free to also/instead tag @dotnet/dnceng  as sometimes I take vacation days and there are other folks who might reply faster on those days.  Including things like the Job GUID (sometimes called Correlation id), Work item friendly name, and why you think we caused your timeout can also speed investigation.  Sounds like we're waiting for Simon to check it out first, though.

**Comment by vargaz** [comment] 2022-03-02 17:29
This seems to be caused by more assemblies getting AOTed.
In particular, every test project now seems to include TestLibrary.dll, so we end up AOTing it like 2000 extra times. The original lane already took about 2 hours, so these extra AOT steps might push it over the timeout.

**Comment by vargaz** [comment] 2022-03-02 19:06
The extra TestLibrary dll was added by 
https://github.com/dotnet/runtime/commit/572405acd98aedfc9a57dc63debd1a1819431dd1#diff-13390079908954088047032dd93629fec2bcfd68749c2c7422c9ed60511ea108L73
Which adds TestLibrary to every test project.

**Comment by lewing** [comment] 2022-03-02 20:27
cc @trylek

**Comment by naricc** [comment] 2022-03-02 21:08
@trylek @jkoritzinsky  Did you complete the test grouping change for this lane? That should have made it faster, since there would be less redundant AOT work.

**Comment by jkoritzinsky** [comment] 2022-03-02 21:20
We're part-way through the work. We added the `TestLibrary` reference to each project to make it simpler than adding the reference to each project individually. If that's causing issues, then we can move to manually adding the project references to the required projects.

**Comment by fanyang-mono** [comment] 2022-03-02 21:25
> We're part-way through the work. We added the `TestLibrary` reference to each project to make it simpler than adding the reference to each project individually. If that's causing issues, then we can move to manually adding the project references to the required projects.

Is it possible to create one copy of `TestLibrary` and put it under `Core_Root`?

**Comment by SamMonoRT** [comment] 2022-03-03 14:50
> We're part-way through the work. We added the `TestLibrary` reference to each project to make it simpler than adding the reference to each project individually. If that's causing issues, then we can move to manually adding the project references to the required projects.

Yes, please switch to manually adding the project references. We need to keep this lane running in PR (in lieu of iOS device runtime tests).

**Comment by jkoritzinsky** [comment] 2022-03-03 16:26
cc @trylek can you make this change? (I’m stretched a little thin on cycles right now)

**Comment by trylek** [comment] 2022-03-03 18:35
@koritzinsky - Sure, will do. I suppose that basically means we need to manually reference TestLibrary from each test using PlatformDetection.

**Comment by fanyang-mono** [comment] 2022-03-04 15:16
With @trylek's PR, the `Mono llvmfullaot Pri0 Runtime Tests Run Linux arm64 release` lane still time out. And the time out currently was because the tests running on helix step took too long to finish (10min -> 1h). @simonrozsival Could you re-open your revert PR and merge main to it to see if the testing time would go down? (https://github.com/dotnet/runtime/pull/66088)

**Comment by SamMonoRT** [comment] 2022-03-04 17:13
The aot time build issue seems to be fixed by the PR - but we still are seeing some tests running longer and exceeding the overall timeout of the lanes. Changing ownership of issue till we determine what is causing the tests to run longer than expected.

**Comment by MattGal** [comment] 2022-03-04 20:04
> The aot time build issue seems to be fixed by the PR - but we still are seeing some tests running longer and exceeding the overall timeout of the lanes. Changing ownership of issue till we determine what is causing the tests to run longer than expected.

Don't forget that ARM64 test machines are a limited, not-scalable resources and the runtime team is sending thousands of hours of work through them.  Being more clever saves time but we can't forget that we have a static number of limited resources.

**Closed** 2022-03-07 14:48 UTC
Labels: blocking-clean-ci, area-Infrastructure-mono
