### ISSUE TITLE
Analyzer should warn when using [UnsafeAccessor] with a local function

### ISSUE THREAD

**Issue by jnm2** [dotnet/runtime#91740] opened 2023-09-07 15:57 UTC
### Description

Discovered after starting a top-level program.

### Reproduction Steps

```cs
using System.Runtime.CompilerServices;

class Program
{
    static void Main()
    {
        // Crashes at runtime with System.MissingMethodException:
        // 💣 Method not found: 'System.Object.<Main>g__MemberwiseClone|0_0'.
        _ = MemberwiseClone(new object());

        // No compiler errors or even warnings here
        [UnsafeAccessor(UnsafeAccessorKind.Method)]
        static extern object MemberwiseClone(object obj);
    }
}
```

_or_

```cs
using System.Runtime.CompilerServices;

// Crashes at runtime with System.MissingMethodException:
// 💣 Method not found: 'System.Object.<<Main>$>g__MemberwiseClone|0_0'.'
_ = MemberwiseClone(new object());

// No compiler errors or even warnings here
[UnsafeAccessor(UnsafeAccessorKind.Method)]
static extern object MemberwiseClone(object obj);
```

### Expected behavior

An SDK diagnostic error explaining that this can't possibly be intended. The mangled name of the local function will never be the right thing to set up. Even if somehow it worked in a certain scenario by accident, you'd be relying on a generated name which the compiler makes no promise about.

### Actual behavior

No build failure, not even a warning.

### Configuration

.NET 8.0.0-preview.7.23376.1

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

</Project>
```

**Comment by vitek-karas** [comment] 2023-09-07 16:50
@AaronRobinsonMSFT we've discussed this some time ago.

Maybe the right solution is an analyzer which raises a warning if there's no `Name` property specified and the attribute is on a local function.

That said, it's not expected that people will be writing these by hand often (the main target audience for `UnsafeAccessor` are source generators). And if they do use it manually, it's an expert level feature, so the priority of writing an analyzer for this is pretty low.

**Comment by AaronRobinsonMSFT** [comment] 2023-09-07 16:58
Is this an issue for the runtime or Roslyn or perhaps the analyzer repo? The runtime feature itself is working as expected, but the usage in a C# context is the confusing part.

@jaredpar Do you have a suggestion on where this should go?

**Comment by jnm2** [comment] 2023-09-07 17:43
I actually had SDK analyzers in mind, but I thought they were discussed here at the same level as APIs in a sense, even though they're implemented in roslyn-analyzers.

**Comment by stephentoub** [comment] 2023-09-07 17:54
> Is this an issue for the runtime or Roslyn or perhaps the analyzer repo?

For analyzers related to runtime APIs, we use issues in dotnet/runtime to define them.  They're then implemented either in dotnet/runtime (e.g. if they're closely associated with something for which we already have a source generator) or dotnet/roslyn-analyzers, which produces analyzer assemblies that both feed into the .NET SDK and into separately obtainable nugets.

**Comment by jkotas** [comment] 2023-09-07 17:54
This was discussed a few times (e.g. here: https://github.com/dotnet/runtime/issues/81741#issuecomment-1542982862).

> An SDK diagnostic error explaining that this can't possibly be intended. 

This can be intended. For example, the API being called may not exist on all platforms and this pattern is being used for light-up on platforms where this API exist.

**Comment by jnm2** [comment] 2023-09-07 17:56
> This can be intended. For example, the API being called may not exist on all platforms and this pattern is being used for light-up on platforms where this API exist.

This is confusing. It can be intended to take the name `<Main>g__MemberwiseClone|0_0` as the method to unsafely access on some type?

**Comment by jkotas** [comment] 2023-09-07 18:43
> I'm asking to block usage of the attribute on local functions.

I have missed that this is proposed for local functions only. This makes sense. It should only warn for `[UnsafeAccessor]` without explicit name.

**Comment by jaredpar** [comment] 2023-09-07 21:41
I think the warning should exist when the attribute is applied to any member for which the language doesn't define the emitted name. Places I can think off of hand for members: 

- local functions
- explicitly implemented interface members

**Comment by jnm2** [comment] 2023-09-07 21:55
Also, attributes can be placed on lambda expressions.

**Comment by jaredpar** [comment] 2023-09-07 22:14
@jnm2 ah yes good catch. Forgot that we consider those methods for purposes of attribute targets. Added to the list.

**Comment by ericstj** [comment] 2023-11-28 18:01
@AaronRobinsonMSFT I moved this to [area-VM-coreclr](https://github.com/dotnet/runtime/labels/area-VM-coreclr) since that's what the original `UnsafeAccessor` feature was part of - please help triage this.

**Comment by AaronRobinsonMSFT** [comment] 2023-11-28 18:26
@ericstj This is by design from a feature stand point. The action item here is a doc update (P1) is warranted when used defined as a local function and a warning (P2) could to be emited. I can handle the P1, but the warning is a nice to have for such a niche feature.

**Comment by AaronRobinsonMSFT** [comment] 2023-11-28 21:38
Closing this issue in lieu of an API proposal for a new analyzer - https://github.com/dotnet/runtime/issues/95361.

Documentation was updated and clarified for this scenario - https://github.com/dotnet/dotnet-api-docs/pull/9481.

**Closed by AaronRobinsonMSFT** 2023-11-28 21:38 UTC
Labels: area-VM-coreclr, code-analyzer

**Comment by jkotas** [comment] 2023-11-28 22:52
> I moved this to [area-VM-coreclr](https://github.com/dotnet/runtime/labels/area-VM-coreclr) since that's what the original UnsafeAccessor feature was part of

The original UnsafeAccessor feature was under area-System.Runtime.CompilerServices: https://github.com/dotnet/runtime/issues/81741. (Some parts of the implementation were tracked under runtime specific areas.)

Runtime neutral aspects of the public API surface (like this one) are typically tracked under area-System.*.
