### ISSUE TITLE
Typo in ClrEtwAll.man

### ISSUE THREAD

**Issue by RobertHenry6bev** [dotnet/runtime#74832] opened 2022-08-30 18:05 UTC
### Description

https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/ClrEtwAll.man contains 2 substrings "Destory".

From context I believe this substrings should be "Destroy"

I do not know the impact of this typo, nor how to mechanically check for other typos like this in the source code.

### Reproduction Steps

grep

### Expected behavior

no typo

### Actual behavior

typo

### Other information

/cc @jkotas

**Comment by jkotas** [comment] 2022-08-30 18:18
Duplicate of https://github.com/dotnet/runtime/issues/72324

**Closed by jkotas** 2022-08-30 18:18 UTC
