### ISSUE TITLE
WasmStripILAfterAOT results in runtime error

### ISSUE THREAD

**Issue by mrentier** [dotnet/runtime#92589] opened 2023-09-25 14:30 UTC
### Description

Compiling a larger app with https://github.com/dotnet/core/issues/8439 enabled results in the following error:
> service-worker.js:26 Service worker: Activate
dotnet.native.8.0.0-rc.1.23419.4.t8b2aypvfm.js:1275 MONO interpreter: NIY encountered in method .ctor
dotnet.runtime.8.0.0-rc.1.23419.4.4bb211gofp.js:3 Error: [MONO] * Assertion: should not be reached at /__w/1/s/src/mono/mono/mini/interp/interp.c:3863

>    at ht (dotnet.runtime.8.0.0-rc.1.23419.4.4bb211gofp.js:3:12730)
    at El (dotnet.runtime.8.0.0-rc.1.23419.4.4bb211gofp.js:3:175383)
    at dotnet.native.wasm:0x1d0b1ce
    at dotnet.native.wasm:0x1b2fd30
    at dotnet.native.wasm:0x1b2c1b6
    at dotnet.native.wasm:0x1b2c2e7
    at dotnet.native.wasm:0x1b2c356
    at dotnet.native.wasm:0x1afeddc
    at dotnet.native.wasm:0x1b0e067
    at dotnet.native.wasm:0x1b0e568
> El @ dotnet.runtime.8.0.0-rc.1.23419.4.4bb211gofp.js:3
2dotnet.runtime.8.0.0-rc.1.23419.4.4bb211gofp.js:3 Error: [MONO] * Assertion at /__w/1/s/src/mono/mono/mini/interp/interp.c:2771, condition `<disabled>' not met

>    at ht (dotnet.runtime.8.0.0-rc.1.23419.4.4bb211gofp.js:3:12730)
    at El (dotnet.runtime.8.0.0-rc.1.23419.4.4bb211gofp.js:3:175383)
    at dotnet.native.wasm:0x1d0b1ce
    at dotnet.native.wasm:0x1b2fd30
    at dotnet.native.wasm:0x1b2c1b6
    at dotnet.native.wasm:0x1b2c2e7
    at dotnet.native.wasm:0x1b2c32e
    at dotnet.native.wasm:0x1b2c2ff
    at dotnet.native.wasm:0x1b0bb13
    at dotnet.native.wasm:0x1aff754
El @ dotnet.runtime.8.0.0-rc.1.23419.4.4bb211gofp.js:3
blazor.webassembly.js:1 ExitStatusmessage: "Program terminated with exit(1)"name: "ExitStatus"status: 1[[Prototype]]: Object
callEntryPoint @ blazor.webassembly.js:1

### Reproduction Steps

I am not able to share the code base :(

### Expected behavior

Smaller size.

### Actual behavior

Runtime error

**Comment by radical** [comment] 2023-09-25 14:52
Closing as duplicate of https://github.com/dotnet/runtime/issues/92238 .

**Closed by radical** 2023-09-25 14:52 UTC
Labels: untriaged, needs-area-label
