### ISSUE TITLE
Test failure System.IO.Tests.FileSystemWatcherTests_netstandard17.DroppedWatcher_Collectible

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#86564] opened 2023-05-22 01:54 UTC
Run: [runtime-coreclr libraries-jitstress-random 20230520.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=280962&view=ms.vss-test-web.build-test-results-tab&runId=5572848&resultId=159112&paneView=debug)

Failed test:
```
net8.0-linux-Release-arm64-CoreCLR_checked-jitstress_random_2-(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8

- System.IO.Tests.FileSystemWatcherTests_netstandard17.DroppedWatcher_Collectible
```
**Error message:**
```
Assert.True() Failure
Expected: True
Actual:   False



Stack trace
   at System.IO.Tests.FileSystemWatcherTests_netstandard17.DroppedWatcher_Collectible() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.cs:line 229
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
```

**Comment by v-wenyuxu** [comment] 2023-07-31 01:24
**Failed again in:** [runtime-coreclr libraries-jitstress-random 20230729.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=356444&view=ms.vss-test-web.build-test-results-tab&runId=7498892&resultId=152448&paneView=debug)

**Failed tests:**
```
net8.0-linux-Release-arm-CoreCLR_checked-jitstress_random_2-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - System.IO.Tests.FileSystemWatcherTests_netstandard17.DroppedWatcher_Collectible
```

**Error message:**
```
Assert.True() Failure
Expected: True
Actual:   False
```

**Stack trace:**
```
   at System.IO.Tests.FileSystemWatcherTests_netstandard17.DroppedWatcher_Collectible() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.cs:line 229
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by v-wenyuxu** [comment] 2023-08-14 01:15
**Failed again in:** [runtime-coreclr libraries-jitstress-random 20230812.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372023&view=ms.vss-test-web.build-test-results-tab&runId=7894116&resultId=149348&paneView=debug)

**Failed tests:**
```
net8.0-linux-Release-arm-CoreCLR_checked-jitstress_random_1-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - System.IO.Tests.FileSystemWatcherTests_netstandard17.DroppedWatcher_Collectible
```

**Error message:**
```
Assert.True() Failure
Expected: True
Actual:   False
```

**Stack trace:**
```
   at System.IO.Tests.FileSystemWatcherTests_netstandard17.DroppedWatcher_Collectible() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.cs:line 229
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by BruceForstall** [comment] 2023-08-15 21:56
@adamsitnik Why did you put this in "Future"?

Is the test normally 100% reliable?

Given that it only has failed in the jitstress-random pipeline, I'm moving this to the JIT team.

**Comment by TIHan** [comment] 2023-08-16 03:26
I got this reproducing in a docker container, will be iterating on it.

**Comment by BruceForstall** [comment] 2023-08-16 04:27
@TIHan Does it fail only under JIT stress? Does it fail under JITMinOpts?

**Comment by TIHan** [comment] 2023-08-16 16:39
It only fails under `DOTNET_JitStress=272`. The test itself is this:

```csharp
        [ConditionalFact(typeof(PlatformDetection), nameof(PlatformDetection.IsPreciseGcSupported))]
        public void DroppedWatcher_Collectible()
        {
            WeakReference watcher = CreateEnabledWatcher(TestDirectory);
            File.Create(GetTestFilePath()).Dispose();
            Assert.True(SpinWait.SpinUntil(() =>
            {
                GC.Collect();
                return !watcher.IsAlive;
            }, LongWaitTimeout));

        }
```

The test fails because the timeout is reached, which `LongWaitTimeout` is 5 seconds. I tried increasing the timeout to 50 seconds, but it just took longer for the test to fail under JitStress. `DOTNET_JITMinOpts=1` made no difference, still fails if it's with JitStress.

**Comment by TIHan** [comment] 2023-08-17 02:44
[dump.txt](https://github.com/dotnet/runtime/files/12364942/dump.txt)
[dump_with_stress.txt](https://github.com/dotnet/runtime/files/12364943/dump_with_stress.txt)

The thing that stands out to me is the 'GSCookie' which I am unfamiliar with at the moment.

**Comment by danmoseley** [comment] 2023-08-17 03:04
What if you make the wait super long - could it just be super slow?

**Comment by TIHan** [comment] 2023-08-17 03:07
I let it run for 3 hours and it still didn't complete. There are also times where it does complete successfully in 14 seconds with the same stress levels.

**Comment by TIHan** [comment] 2023-08-17 19:07
It definitely looks like that the object is not getting collected, despite `CreateEnabledWatcher` being marked as no-inline and returning the WeakReference.

**Comment by BruceForstall** [comment] 2023-08-24 17:31
This continues to fail in CI:

https://dev.azure.com/dnceng-public/public/_build/results?buildId=384544&view=ms.vss-test-web.build-test-results-tab&runId=8209298&resultId=166431&paneView=debug

**Comment by v-wenyuxu** [comment] 2023-08-25 01:11
**Failed again in:** [runtime-coreclr libraries-jitstress 20230824.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=384544&view=ms.vss-test-web.build-test-results-tab&runId=8209318&resultId=148093&paneView=debug)

**Failed tests:**
```
net8.0-linux-Release-x64-CoreCLR_checked-jitstress2_tiered-Ubuntu.1804.Amd64.Open
    - System.IO.Tests.FileSystemWatcherTests_netstandard17.DroppedWatcher_Collectible
net8.0-linux-Release-x64-CoreCLR_checked-jitstress1_tiered-Ubuntu.1804.Amd64.Open
    - System.IO.Tests.FileSystemWatcherTests_netstandard17.DroppedWatcher_Collectible
net8.0-linux-Release-arm64-CoreCLR_checked-jitstress1_tiered-(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
    - System.IO.Tests.FileSystemWatcherTests_netstandard17.DroppedWatcher_Collectible
net8.0-linux-Release-arm64-CoreCLR_checked-jitstress2_tiered-(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
    - System.IO.Tests.FileSystemWatcherTests_netstandard17.DroppedWatcher_Collectible
```

**Error message:**
```
Assert.True() Failure
Expected: True
Actual:   False
```

**Stack trace:**
```
   at System.IO.Tests.FileSystemWatcherTests_netstandard17.DroppedWatcher_Collectible() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.cs:line 229
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Closed** 2023-09-01 03:42 UTC
Labels: arch-arm64, os-linux, JitStress, area-CodeGen-coreclr
