### ISSUE TITLE
Can runtime created type using Reflection.Emit be deleted or updated

### ISSUE THREAD

**Issue by SunSi12138** [dotnet/runtime#88429] opened 2023-07-05 16:42 UTC
### Description

Error when creating a duplicate class using TypeBuilder in runtime

### Reproduction Steps

Use TypeBuilder to create a class at runtime.
Create another TypeBuilder with the same name to create the same class.

### Expected behavior

The class created using TypeBuilder at runtime should be updatable or allow for re-creation after being destroyed.

### Actual behavior

The class created using TypeBuilder at runtime throws an error indicating that the class already exists:
```
System.ArgumentException: Duplicate type name within an assembly.
at System.Reflection.Emit.ModuleBuilder.CheckTypeNameConflict(String strTypeName, Type enclosingType)
at System.Reflection.Emit.TypeBuilder..ctor(String fullname, TypeAttributes attr, Type parent, Type[] interfaces, ModuleBuilder module, PackingSize iPackingSize, Int32 iTypeSize, TypeBuilder enclosingType)
at System.Reflection.Emit.ModuleBuilder.DefineType(String name, TypeAttributes attr, Type parent, Type[] interfaces)

```

### Known Workarounds

I'm developing a no-code database platform that can dynamically generate corresponding database tables by adding data descriptions at runtime. I'm using EfCore for performing CRUD operations on the data. Therefore, I need to create classes for the data tables at runtime instead of writing fixed code for uncertain classes beforehand.

Issue Description:
When creating a class using TypeBuilder at runtime and subsequently attempting to create the same class with additional members, an error is thrown stating that the class has already been defined.

I can generate versions of the corresponding types based on the data description, such as Blog1 and Blog2, to differentiate them. However, the old versions of the types are no longer used, and it seems to have a negative impact on memory consumption. A better solution would be to discard the old classes. Do you have any suggestions? Thank you for your help!

### Configuration

.NET Version: dotnet core 7.0
os：Mac os
architecture：arm

### Other information

According to the official documentation, "Before a type is used, the TypeBuilder.CreateType method must be called. CreateType completes the creation of the type. Following the call to CreateType, the caller can instantiate the type by using the Activator.CreateInstance method and invoke members of the type by using the Type.InvokeMember method. It is an error to invoke methods that change the implementation of a type after CreateType has been called. For example, the common language runtime throws an exception if the caller tries to add new members to a type." (source: https://learn.microsoft.com/en-us/dotnet/api/system.reflection.emit.typebuilder?view=net-7.0)

Additionally, I haven't found any other information regarding creating classes at runtime using Reflection.Emit.

**Comment by jkotas** [comment] 2023-07-05 19:10
.NET runtime does not support unloading individual types. It supports unloading whole assemblies only.

You can create a type with the same name by creating a new assembly.

**Comment by buyaa-n** [comment] 2023-07-07 23:56
Hope above comment answered your question, closing it by design

**Closed by buyaa-n** 2023-07-07 23:56 UTC
Labels: area-System.Reflection.Emit, untriaged
