### ISSUE TITLE
PathTooLongException with MemoryMappedView{Accessor,Stream} tests on osx-arm64 release with mono runtime

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#64947] opened 2022-02-07 22:43 UTC
There are 45 failures in different tests.

logs: https://helix.dot.net/api/2019-06-17/jobs/e20fce52-2b6f-4cd7-9c13-8a370de51bec/workitems/System.IO.MemoryMappedFiles.Tests/console

e.g.
```
  Discovered:  System.IO.MemoryMappedFiles.Tests (found 200 of 223 test cases)
  Starting:    System.IO.MemoryMappedFiles.Tests (parallel test collections = on, max threads = 8)
    System.IO.MemoryMappedFiles.Tests.MemoryMappedFileTests_CreateNew.ValidArgumentCombinations(mapName: null, capacity: 1, access: Read, options: None, inheritability: None) [FAIL]
      System.IO.PathTooLongException : The specified file name or path is too long, or a component of the specified path is too long.
      Stack Trace:
        /_/src/libraries/System.IO.MemoryMappedFiles/src/System/IO/MemoryMappedFiles/MemoryMappedFile.Unix.cs(214,0): at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateSharedBackingObjectUsingMemory(MemoryMappedProtections protections, Int64 capacity, HandleInheritability inheritability)
        /_/src/libraries/System.IO.MemoryMappedFiles/src/System/IO/MemoryMappedFiles/MemoryMappedFile.Unix.cs(170,0): at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateSharedBackingObject(MemoryMappedProtections protections, Int64 capacity, HandleInheritability inheritability)
        /_/src/libraries/System.IO.MemoryMappedFiles/src/System/IO/MemoryMappedFiles/MemoryMappedFile.Unix.cs(112,0): at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateCore(FileStream fileStream, String mapName, HandleInheritability inheritability, MemoryMappedFileAccess access, MemoryMappedFileOptions options, Int64 capacity)
        /_/src/libraries/System.IO.MemoryMappedFiles/src/System/IO/MemoryMappedFiles/MemoryMappedFile.cs(287,0): at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateNew(String mapName, Int64 capacity, MemoryMappedFileAccess access, MemoryMappedFileOptions options, HandleInheritability inheritability)
        /_/src/libraries/System.IO.MemoryMappedFiles/src/System/IO/MemoryMappedFiles/MemoryMappedFile.cs(237,0): at System.IO.MemoryMappedFiles.MemoryMappedFile.CreateNew(String mapName, Int64 capacity)
        /_/src/libraries/System.IO.MemoryMappedFiles/tests/MemoryMappedFile.CreateNew.Tests.cs(194,0): at System.IO.MemoryMappedFiles.Tests.MemoryMappedFileTests_CreateNew.ValidArgumentCombinations(String mapName, Int64 capacity, MemoryMappedFileAccess access, MemoryMappedFileOptions options, HandleInheritability inheritability)
```

cc @vargaz, @lambdageek, @mdh1418, maybe related to https://github.com/dotnet/runtime/issues/51375 (iOS, MacCatalyst tests are disabled against that issue)? Not sure if we run these tests on osx-arm64 coreclr runtime. :thinking:

**Comment by MaximLipnin** [comment] 2022-02-08 08:18
It's dupe of https://github.com/dotnet/runtime/issues/63240

**Closed** 2022-02-08 08:33 UTC
Labels: area-System.IO, untriaged
