### ISSUE TITLE
Double.ToString(format) not throwing FormatException

### ISSUE THREAD

**Issue by matthewm8m** [dotnet/runtime#64295] opened 2022-01-25 21:55 UTC
### Description

I am using the `Double.ToString(string? format)` method as documented [here](https://docs.microsoft.com/en-us/dotnet/api/system.double.tostring?view=net-5.0#system-double-tostring(system-string)). I expect that if the format specifier that I am passing in as an argument is not a valid standard or custom format specifier, that a `FormatException` is raised as noted in the documentation. Instead, the method yields the format specified if not valid. At very least, either the implementation is not correct or the documentation is misleading.

### Reproduction Steps

I ran the following minimal code example:

```csharp
using System;

class Program
{
  public static void Main (string[] args)
  {
    Console.WriteLine(3.14.ToString("C"));
    Console.WriteLine(3.14.ToString("abcC"));
  }
}
```

### Expected behavior

I expected the following output where `[...]` indicates a non-output.

```
$3.14
[System.FormatException]
```

### Actual behavior

I received the following output.

```
$3.14
abcC
```

### Regression?

I tested this code against .NET Core 3.0.103 and produced the same results so as far as I can tell, this is not a regression.

### Known Workarounds

I attempted to use the following code instead but got the same results. I do not any workarounds to produce the desired `FormatException`.
```csharp
using System;

class Program
{
  public static void Main (string[] args)
  {
    Console.WriteLine(String.Format("{0:C}", 3.14));
    Console.WriteLine(String.Format("{0:abcC}", 3.14));
  }
}
```

### Configuration

- .NET Version: 5.0.404
- OS: Ubuntu 20.04.03 LTS
- Architecture: x64

I do not think that the problem is specific to the configuration.

**Comment by Clockwork-Muse** [comment] 2022-01-25 22:03
> I expect that if the format specifier that I am passing in as an argument is not a valid standard or custom format specifier,

But it is [a valid custom format specifier](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-numeric-format-strings#character-literals): 
> All other characters are always interpreted as character literals and, in a formatting operation, are included in the result string unchanged.

**Comment by danmoseley** [comment] 2022-01-26 00:40
I agree, I believe this is by design. @matthewm8m is there anything you're trying to do that you can't achieve, or you simply noticed this?

**Comment by matthewm8m** [comment] 2022-01-26 00:43
@Clockwork-Muse Ah. You are totally right. That's fair. It is a bit counterintuitive that `format="C"` and `format="abC"` function so differently simply because `"abC"` is not a standard format specifier. I'd prefer it to function more similarly to `String.Format` so I could use `3.14.ToString("ab{C}")`. Anyway, it's clear that this isn't a bug.

Related to that example though, here's a question. How would I specify literal characters and the local currency symbol using a format string for instance? So, `3.14` becomes `"$3.14"` or `"£3.14"` depending on local. Something that wouldn't work is `3.14.ToString("$0.00")`.

**Comment by Clockwork-Muse** [comment] 2022-01-26 03:35
> local currency symbol 

Provide the culture, don't specify it as a literal, and use the precision specifier: `3.14.ToString("C2", whateverCulture)`, which also means that the separators would appear in the correct places (some cultures separate every 4 places, not 3).   Although note that doubles aren't the best for currency representation, because there's issues due to the fact that `float/`double` are binary - base 2 - floating point instead of base 10.  For currency values, you should be using `decimal`.

That aside, you're probably going to want to use `string.Create(...)`, rather than calling `ToString()` directly on the value.:
```csharp 
public static string FormatAmount(IFormatProvider provider, decimal amount) => string.Create(provider, $"{amount:C2}");
```
... because this allows the compiler to do some funny things on your behalf.
[There are more details here](https://devblogs.microsoft.com/dotnet/string-interpolation-in-c-10-and-net-6/).

**Comment by tannergooding** [comment] 2022-01-26 18:01
Thanks for answering this above. If there are no other questions please feel free to close the issue :)

> It is a bit counterintuitive that format="C" and format="abC" function so differently simply because "abC" is not a standard format specifier.

Yes and its caused various issues and confusion in the past as well. It's also made certain scenarios breaking changes, such as introducing new format specifiers or even extending the existing format support. We took one such breaking change in .NET 6 because it reduced the overall confusion: https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/numeric-format-parsing-handles-higher-precision.

For example, in .NET Core 3.1 `(5.0f).ToString("G99")` was the "max precision" supported and `(5.0f).ToString("G100")` was treated as a custom format string. So the former would print `5` while the latter would print `G105`. In .NET 6 or later in order to to support floats/doubles as they may need up to `113` or `768` significant digits, respectively, to fully represent the underlying value. So the change was to always treat such format strings as the `"G"` standard format specifier and `#####` precision, throwing a `FormatException` if `#####` doesn't fit in `int.MaxValue`

**Closed** 2022-01-27 14:03 UTC
Labels: area-System.Runtime, untriaged
