### ISSUE TITLE
dotnet global tools install problem in Amazon Linux Arm64

### ISSUE THREAD

**Issue by birojnayak** [dotnet/runtime#72636] opened 2022-07-21 19:59 UTC
### Description

I installed dotnet 6 to EC2 Amazon Linux Arm64. Installed dotnet-counters to do some bechmarking. Was able to successfully install the tool, but when I ran the tool it tells me 

You must install .NET to run this application.

App: /home/ec2-user/.dotnet/tools/dotnet-counters
Architecture: arm64
App host version: 6.0.7
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=arm64&rid=amzn.2-arm64&apphost_version=6.0.7

when I did my on 
```shell
[ec2-user@ip-foobar ~]$ cat ~/.bash_profile 
# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# User specific environment and startup programs

PATH=/home/ec2-user/.dotnet:/home/ec2-user/.dotnet/tools:$PATH:$HOME/.local/bin:$HOME/bin:

export PATH 
```
when I did 
```shell
[ec2-user@ip-foobar ~]$ dotnet --info
```
.NET SDK (reflecting any global.json):
 Version:   6.0.302
 Commit:    c857713418

Runtime Environment:
 OS Name:     amzn
 OS Version:  2
 OS Platform: Linux
 RID:         linux-arm64
 Base Path:   /home/ec2-user/.dotnet/sdk/6.0.302/

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: arm64
  Commit:       0ec02c8c96

.NET SDKs installed:
  6.0.302 [/home/ec2-user/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.7 [/home/ec2-user/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.7 [/home/ec2-user/.dotnet/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

what fixed is setting up export DOTNET_ROOT=/home/ec2-user/.dotnet and DOTNET_HOME=/home/ec2-user/.dotnet....
this is not a good experience...

### Reproduction Steps

=> launch ec2 Amazon Linux Arm64
=> do yum update and yum install libicu60
=> wget https://dot.net/v1/dotnet-install.sh
=>chmod u+x dotnet-install.sh
=>./dotnet-install.sh -c Current --architecture arm64 --verbose
=>set bash_profile to include dotnet path /home/ec2-user/.dotnet
=>dotnet tool install --global dotnet-counters
=> set tool path in bash_profile as  /home/ec2-user/.dotnet/tools
=>dotnet-counters list
you should see the bug I am reporting 

App: /home/ec2-user/.dotnet/tools/dotnet-counters
Architecture: arm64
App host version: 6.0.7
.NET location: Not found

Learn about runtime installation:
https://aka.ms/dotnet/app-launch-failed

Download the .NET runtime:
https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=arm64&rid=amzn.2-arm64&apphost_version=6.0.7

### Expected behavior

the dotnet cli tool should work 

### Actual behavior

it's not working

### Known Workarounds

explicitly set 
export DOTNET_ROOT=/home/ec2-user/.dotnet  
export DOTNET_HOME=/home/ec2-user/.dotnet

**Comment by jonlouie** [comment] 2022-07-21 20:35
Ran into a similar issue when trying to run a project I built myself. I was able to get around it by executing the .dll artifact generated by my build using `dotnet /path/to/my/project.dll`. 

I agree though, executing dotnet applications on Linux should be a similar experience regardless of whether it is run on an x86/64 or ARM platform.

**Comment by vitek-karas** [comment] 2022-07-21 21:10
This is due to usage of the `dotnet-install.sh` script. That script is intended to be used for CI-like scenarios and you do need to change certain env. variables for it to work fully. Namely you need to update `PATH` and to run apps (global tools are apps) also `DOTNET_ROOT`.

If you use the package installers those would setup everything such that running apps just works (without environment variables).

Speaking more technically: The `dotnet-install.sh` just downloads and extracts an archive to a specified location - it doesn't "register" it in any way. So it's impossible for apps to find it on their own. The package installers "register" the installed runtime. Specifically for running of apps they write the location of the installation into `/etc/dotnet/install_location_arm64`. When you run a .NET app it looks there to find where to look for the runtime. For more details see: https://github.com/dotnet/designs/blob/main/accepted/2021/install-location-per-architecture.md

**Comment by agocke** [comment] 2022-07-26 20:33
Closing as by design

**Closed by agocke** 2022-07-26 20:33 UTC
Labels: area-Host, untriaged
