### ISSUE TITLE
QUIC ReadWrite_MessagesSmallerThanReadBuffer_Success test hung CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#55967] opened 2021-07-19 21:25 UTC
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55925-merge-d2e7aeb45c464a44a8/System.Net.Quic.Functional.Tests/console.6d103b01.log?sv=2019-07-07&se=2021-08-08T18%3A53%3A00Z&sr=c&sp=rl&sig=uNutFBxWQIskzJ8103hzHX0HErS6948iyfFS26JgvJM%3D

net6.0-Linux-Debug-x64-CoreCLR_release-(Fedora.32.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-32-helix-20210710031120-870c408

```
  Discovering: System.Net.Quic.Functional.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Quic.Functional.Tests (found 106 of 121 test cases)
  Starting:    System.Net.Quic.Functional.Tests (parallel test collections = on, max threads = 2)
   System.Net.Quic.Functional.Tests: [Long Running Test] 'System.Net.Quic.Tests.MsQuicQuicStreamConformanceTests.ReadWrite_MessagesSmallerThanReadBuffer_Success', Elapsed: 00:02:07
[Long Running Test] 'System.Net.Quic.Tests.QuicStreamTests_MsQuicProvider.ReadWrite_Random_Success', Elapsed: 00:02:12
   System.Net.Quic.Functional.Tests: [Long Running Test] 'System.Net.Quic.Tests.MsQuicQuicStreamConformanceTests.ReadWrite_MessagesSmallerThanReadBuffer_Success', Elapsed: 00:04:07
[Long Running Test] 'System.Net.Quic.Tests.QuicStreamTests_MsQuicProvider.ReadWrite_Random_Success', Elapsed: 00:04:13
   System.Net.Quic.Functional.Tests: [Long Running Test] 'System.Net.Quic.Tests.MsQuicQuicStreamConformanceTests.ReadWrite_MessagesSmallerThanReadBuffer_Success', Elapsed: 00:06:07
[Long Running Test] 'System.Net.Quic.Tests.QuicStreamTests_MsQuicProvider.ReadWrite_Random_Success', Elapsed: 00:06:13
   System.Net.Quic.Functional.Tests: [Long Running Test] 'System.Net.Quic.Tests.MsQuicQuicStreamConformanceTests.ReadWrite_MessagesSmallerThanReadBuffer_Success', Elapsed: 00:08:07
[Long Running Test] 'System.Net.Quic.Tests.QuicStreamTests_MsQuicProvider.ReadWrite_Random_Success', Elapsed: 00:08:13
   System.Net.Quic.Functional.Tests: [Long Running Test] 'System.Net.Quic.Tests.MsQuicQuicStreamConformanceTests.ReadWrite_MessagesSmallerThanReadBuffer_Success', Elapsed: 00:10:07
[Long Running Test] 'System.Net.Quic.Tests.QuicStreamTests_MsQuicProvider.ReadWrite_Random_Success', Elapsed: 00:10:13
   System.Net.Quic.Functional.Tests: [Long Running Test] 'System.Net.Quic.Tests.MsQuicQuicStreamConformanceTests.ReadWrite_MessagesSmallerThanReadBuffer_Success', Elapsed: 00:12:07
[Long Running Test] 'System.Net.Quic.Tests.QuicStreamTests_MsQuicProvider.ReadWrite_Random_Success', Elapsed: 00:12:13
   System.Net.Quic.Functional.Tests: [Long Running Test] 'System.Net.Quic.Tests.MsQuicQuicStreamConformanceTests.ReadWrite_MessagesSmallerThanReadBuffer_Success', Elapsed: 00:14:07
[Long Running Test] 'System.Net.Quic.Tests.QuicStreamTests_MsQuicProvider.ReadWrite_Random_Success', Elapsed: 00:14:13

...
[EXECUTION TIMED OUT]
Exit Code:-3Executor timed out after 900 seconds and was killed
['System.Net.Quic.Functional.Tests' END OF WORK ITEM LOG: Command timed out, and was killed]
```

**Comment by wfurt** [comment] 2021-07-19 21:27
this is same root case IMHO as #55642. 
We basically hang in synchronous Write in MsQuicStream.

**Comment by ManickaP** [comment] 2021-07-20 07:59
Duplicate of #55642

**Closed by ManickaP** 2021-07-20 07:59 UTC
Labels: area-System.Net.Quic, untriaged
