### ISSUE TITLE
System.Configuration.ConfigurationManager cannot read AppSettings when published with publishSingleFile=true

### ISSUE THREAD

**Issue by mshobohm** [dotnet/runtime#42161] opened 2020-09-12 18:23 UTC
### Description

System.Configuration.ConfigurationManager cannot read AppSettings when published with publishSingleFile=yes 

### Configuration
.net 5 preview 8
tried out with windows-x64 and linux-64

### Regression?
I couldnt get this bug working in 3.1

### Other information

C:\Projekte\AppSetting>dotnet --version
5.0.100-preview.8.20417.9

C:\Projekte\AppSetting>dotnet run
OK

C:\Projekte\AppSetting>dotnet publish -c Release
Microsoft (R)-Build-Engine, Version 16.8.0-preview-20414-02+a55ce4fbb für .NET
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

  Wiederherzustellende Projekte werden ermittelt...
  Alle Projekte sind für die Wiederherstellung auf dem neuesten Stand.
  Sie verwenden eine Vorschauversion von .NET Core. Weitere Informationen: https://aka.ms/dotnet-core-preview
  AppSetting -> C:\Projekte\AppSetting\bin\Release\net50\win-x64\AppSetting.dll
  AppSetting -> C:\Projekte\AppSetting\bin\Release\net50\win-x64\publish\

C:\Projekte\AppSetting>C:\Projekte\AppSetting\bin\Release\net50\win-x64\publish\AppSetting.exe
Not Found
(Expected behavior is the output of "OK" as with dotnet run)

[AppSetting.zip](https://github.com/dotnet/runtime/files/5213079/AppSetting.zip)

**Comment by am11** [comment] 2020-09-15 07:23
@agocke, this is a 3.1 to 5.0.0 regression. Should it be considered for backporting?

**Comment by am11** [comment] 2020-09-15 07:23
@agocke, @safern, this is clearly a 3.1 to 5.0.0 regression. Should it be considered for backporting?

**Comment by safern** [comment] 2020-09-15 15:36
> @agocke, @safern, this is clearly a 3.1 to 5.0.0 regression. Should it be considered for backporting?

cc: @ericstj @danmosemsft

**Comment by danmosemsft** [comment] 2020-09-15 15:54
Can someone investigate and understand the issue?

**Comment by am11** [comment] 2020-09-15 15:55
@danmosemsft, done and fixed by https://github.com/dotnet/runtime/pull/42176.

**Comment by ericstj** [comment] 2020-09-15 16:03
So the breaking change was that `GetEntryAssembly().ManifestModule.Name` was returning the app name for single file in 3.x and starting in 5.0 it returns null.  System.Configuration.ConfigurationManager was just one consumer of this.  Why not undo the change to runtime that caused the regression?

**Comment by ericstj** [comment] 2020-09-15 16:05
I believe the entry assembly physically exists on disk, right?

**Comment by am11** [comment] 2020-09-15 16:05
> starting in 5.0 it returns null

The breaking change was that it returns `<Unknow>` string. We have detected isSingleFile and special case it.

**Comment by jkotas** [comment] 2020-09-15 16:07
No, the assembly does not physically exist on disk as .dll. The only file that physically exist on disk in true single-file mode is the unmanaged host. All managed assemblies are embedded as resources to it and loaded as in-memory loads.

**Comment by jkotas** [comment] 2020-09-15 16:08
> The breaking change was that it returns `<Unknown>` string. 

`<Unknown>` is the expected return value of this API for assemblies loaded from memory.

**Comment by ericstj** [comment] 2020-09-15 16:08
I see, understood.  I can see why you want to do this, because most code that would follow after consuming a faked `GetEntryAssembly` will do the wrong thing.

I wonder if all these places need similar fixes: https://source.dot.net/#System.Private.CoreLib/Assembly.cs,0b58cbf47b813b13,references

**Comment by am11** [comment] 2020-09-15 16:10
> `<Unknown>` is the expected return value of this API for assemblies loaded from memory.

True. I meant from the prespective of its usage in ConfigurationManager, it is a breaking change. Even with 3.1, the assembly name `<appname>.exe` exists on the disk, but not `<appname>.dll` in case of single file on Windows, but the underlying API returns `<appname>.dll` which is how it was working correctly before.

**Comment by jkotas** [comment] 2020-09-15 16:11
> Even with 3.1, the assembly name <appname>.exe exists on the disk, but not <appname>.dll in case of single file on Windows

`<appname>.dll` does exist on disk in the temp directory in 3.1.

**Comment by ericstj** [comment] 2020-09-15 16:43
I tested a few of the cases I found in the link shared above and this is broken as well:
```
            try
            {
                var store = IsolatedStorageFile.GetUserStoreForApplication();
                var file = store.CreateFile("test.txt");
                Console.WriteLine(file.Name);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
```

Works in 3.1, fails in 5.0.  Haven't gone through all.

**Comment by am11** [comment] 2020-09-15 16:46
@ericstj, here is a quick search result of `ManifestModule` usage in the repo:

```sh
# git pathspec: include all C# code and exclude *Test* like paths
~/projects/runtime $ git grep \\.ManifestModule :/*.cs ':(exclude)*Test*'

src/coreclr/src/System.Private.CoreLib/src/System/Reflection/CustomAttribute.cs:            return GetCustomAttributes((RuntimeModule)target.ManifestModule, RuntimeAssembly.GetToken(target.GetNativeHandle()));
src/coreclr/src/System.Private.CoreLib/src/System/Reflection/CustomAttribute.cs:            return IsCustomAttributeDefined((assembly.ManifestModule as RuntimeModule)!, RuntimeAssembly.GetToken(assembly.GetNativeHandle()), caType);
src/coreclr/src/System.Private.CoreLib/src/System/Reflection/CustomAttribute.cs:            return GetCustomAttributes((assembly.ManifestModule as RuntimeModule)!, assemblyToken, 0, caType);
src/coreclr/src/System.Private.CoreLib/src/System/Reflection/Emit/DynamicMethod.cs:                s_anonymouslyHostedDynamicMethodsModule = (InternalModuleBuilder)assembly.ManifestModule!;
src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ClientConfigPaths.cs:                    string configBasePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, exeAssembly.ManifestModule.Name);
src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ClientConfigPaths.cs:                Uri codeBase = new Uri(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, assembly.ManifestModule.Name));
src/libraries/System.Reflection.Context/src/System/Reflection/Context/Delegation/DelegatingAssembly.cs:            get { return UnderlyingAssembly.ManifestModule; }
src/libraries/System.Reflection.Context/src/System/Reflection/Context/Projection/ProjectingAssembly.cs:            get { return Projector.ProjectModule(base.ManifestModule); }
src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/MetadataLoadContext.Loading.cs:                    if (candidate.ManifestModule.ModuleVersionId != winner.ManifestModule.ModuleVersionId)
src/mono/netcore/System.Private.CoreLib/src/System/Reflection/Emit/DynamicMethod.cs:            public static readonly Module anon_host_module = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName() { Name = "Anonymously Hosted DynamicMethods Assembly" }, AssemblyBuilderAccess.Run).ManifestModule;
```

`Name` property is not used in many places.

**Comment by am11** [comment] 2020-09-15 17:06
> Works in 3.1 single file, fails in 5.0 single file. Haven't gone through all.

This is different as it is about another API `CodeBase` deprecated in 5.0. The exception is:

```
Unhandled exception. System.NotSupportedException: CodeBase is not supported on assemblies loaded from a single-file bundle.
   at System.Reflection.RuntimeAssembly.get_CodeBase()
```

Should we have a separate issue to track it?

**Comment by ericstj** [comment] 2020-09-15 17:48
> about another API CodeBase deprecated in 5.0. 

This isn't a deprecation.  Deprecation is design-time warning with no runtime behavior change.  This is a breaking change due to single-file changes.  Sure, it can be a new issue.  I'm more worried that this is a new issue.  That means there are multiple breaking changes to single-file that don't have good test coverage in libraries.  cc @jeffschwMSFT

**Comment by am11** [comment] 2020-09-15 17:59
> This isn't a deprecation. Deprecation is design-time warning with no runtime behavior change. 

Agreed. We suppress the deprecation warning here: https://github.com/dotnet/runtime/blob/b19d7980c6a0e1f03312c8c2033fcbd13822378f/src/libraries/System.IO.IsolatedStorage/src/System/IO/IsolatedStorage/Helper.Win32Unix.cs#L57-L59

Maybe we can try to use the recommended `Assembly.Location` API there and handle `isSingleFile = Assembly.Location.Length ==0; if(isSingleFile) ..do not throw..`.

Single file integration tests (maybe with remote execution; outerloop) support would be great. I tried to figure out how to effectively test the PR changes in the CI, but couldn't find much.

**Comment by agocke** [comment] 2020-09-15 18:05
> That means there are multiple breaking changes to single-file that don't have good test coverage in libraries.

I would agree with this. Our current inability to compile the unit tests and run them through single-file publish means our test coverage is very limited.

**Comment by agocke** [comment] 2020-09-15 18:06
@am11 We have some limited API tests for running in single-file here: https://github.com/dotnet/runtime/blob/master/src/installer/tests/Assets/TestProjects/SingleFileApiTests/Program.cs

**Comment by ericstj** [comment] 2020-09-15 18:11
Seems like this is a similar test problem that we've solved in the past for blazor / UWP / etc.  If single file presents itself in a way that runtime and libraries have significantly different behaviors we should test it like a new platform.

**Comment by am11** [comment] 2020-09-15 18:11
@agocke, thanks. Would it be out of scope of this test project, if we the ConfigurationManager and IsolatedStorage APIs tests in SingleFileApiTests (for now™️, until there is proper infra support for singlefile in src/libraries tests)?

**Comment by agocke** [comment] 2020-09-15 18:14
@ericstj I suspect many of these APIs are similarly broken for blazor/UWP/.NET Native. I know CodeBase throws on .NET Native, so anything that uses it is certainly broken.

**Comment by ericstj** [comment] 2020-09-15 18:37
I was saying that folks solved the engineering problem to get testing running for those platforms. I think we could solve the same here if we think it’s important enough to not regress.

We actually did a lot of work to minimize the number of libraries that were broken on these platforms in the past.  Fixes similar to what @am11 did here.

Right now “certainly broken” is “certainly regressed from 3.1” which is why we are talking about this now.

**Comment by agocke** [comment] 2020-09-15 18:58
Agreed, I think finding a way to run at least some of the unit tests in a single-file publish is possible and valuable.

**Comment by safern** [comment] 2020-09-15 19:13
> Seems like this is a similar test problem that we've solved in the past for blazor / UWP / etc. If single file presents itself in a way that runtime and libraries have significantly different behaviors we should test it like a new platform. cc @ViktorHofer

With the infrastructure that we did to build against ref pack and publish mobile tests with live runtime pack, this should be very doable and we could just add new build legs.

**Closed** 2020-09-24 17:53 UTC
Labels: area-System.Configuration
