### ISSUE TITLE
[AOT][Blazor][Net8] Performance issue in async code

### ISSUE THREAD

**Issue by arivoir** [dotnet/runtime#89733] opened 2023-07-31 17:59 UTC
I'm profiling a Blazor .Net 8 application using AOT, and found the method _corlib_System_Runtime_CompilerServices_AsyncMethodBuilderCore_Start_TStateMachine_GSHAREDVT_TStateMachine_GSHAREDVT__ is taking too much time to fiinish

![image](https://github.com/dotnet/runtime/assets/17496741/9e13ceb7-51bd-4386-a292-d312a8935b1f)

![image](https://github.com/dotnet/runtime/assets/17496741/c4a58c01-2b14-4aa5-a148-1cecb6e97f0c)

The application has the following properties

> 		<RunAOTCompilation>true</RunAOTCompilation>
> 		<RunAOTCompilationAfterBuild>true</RunAOTCompilationAfterBuild>
> 		<WasmNativeStrip>false</WasmNativeStrip>

I'm attaching the chrome profiling session in case it helps
[Trace-20230731T140346.zip](https://github.com/dotnet/runtime/files/12217873/Trace-20230731T140346.zip)

**Comment by SamMonoRT** [comment] 2023-07-31 23:24
cc @radekdoulik @vargaz

**Comment by kg** [comment] 2023-08-01 16:42
Can you provide a sample application or more information? What you're seeing is usually a symptom of an async function blocking the main thread for a long period of time. If you look at the implementation of Start, it doesn't do much other than invoke the underlying state machine for the task: https://github.com/dotnet/runtime/blob/13d98277966de4541ca9893f5e419772df649e17/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs#L38

I'm not sure why the profile looks like that, though. It is odd.

**Comment by arivoir** [comment] 2023-08-03 19:01
I was debugging further and found the issue is only seen when the project is compiled in "Debug"

Debug
![image](https://github.com/dotnet/runtime/assets/17496741/4f738699-e9b1-4b83-96c8-2db02e879bd7)
Release
![image](https://github.com/dotnet/runtime/assets/17496741/f96fe575-4107-42ae-8e60-09dfa2e370db)

Notice the exact same operation takes 180ms in Debug whearas it takes 6ms in Release configuration

Any idea why is that different?

1>C:\Program Files\dotnet\sdk\8.0.100-preview.6.23330.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(314,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy

**Comment by kg** [comment] 2023-08-03 19:19
Codegen for debug is going to be very different. I'm not certain how much we care about Debug AOT as a configuration in terms of performance - I'll try to find out. I'm glad to hear Release AOT works okay. The stack trace from the Release build at least provides some hints to what might be taking time in Debug builds.

**Comment by lewing** [comment] 2023-08-04 00:10
cc @radical for the Debug settings

**Comment by kg** [comment] 2023-10-11 23:16
Just following up to let you know that we don't consider Debug AOT performance a priority, since it typically combines the worst traits of both release-AOT and debug-interp modes without most of their advantages (not meaningfully easier to debug, file sizes still enormous, startup still slower, etc).

If there are specific scenarios where you *need* Debug AOT to be more performant, or where something is broken, feel free to file issues about those with relevant details so we can figure out whether we should reprioritize it.

In this specific case given that the code takes at least 6ms in release builds, it's not unprecedented that a debug build would be much slower - 30x is a scary ratio but debug codegen can be much worse to the point of seeing regressions that big, and browser devtools happen to amplify the size of performance regressions like this.

So at present I'll close this because to my knowledge this is more or less "working as expected", but as I said feel free to open issues if you run into cases where debug AOT is broken or if you would like us to consider reprioritizing it to support a specific scenario, so we can evaluate that for .NET 9.

Thanks for the report!

**Closed by kg** 2023-10-11 23:16 UTC
Labels: arch-wasm, tenet-performance, area-Codegen-AOT-mono
