### ISSUE TITLE
[API Proposal]: implicit cast ValueTask<T> to ValueTask

### ISSUE THREAD

**Issue by timcassell** [dotnet/runtime#67212] opened 2022-03-27 22:53 UTC
### Background and motivation

Currently, converting a `ValueTask<T>` to a `ValueTask` requires a separate state machine to asynchronously convert it.

```cs
// ValueTask<T> can't be converted to a ValueTask for free, so we must create a state machine.
public static async ValueTask ToValueTaskVoid<T>(ValueTask<T> task)
{
    _ = await task.ConfigureAwait(false);
}
```

Adding an implicit cast would make that conversion free, no allocations or state machinery necessary.

```cs
public static ValueTask ToValueTaskVoid<T>(ValueTask<T> task)
{
    return task;
}
```

### API Proposal

`IValueTaskSource<TResult>` interface changed to this:

```cs
public interface IValueTaskSource<out TResult> : IValueTaskSource
{
    new TResult GetResult(short token);
    new ValueTaskSourceStatus GetStatus(short token);
    new void OnCompleted(Action<object> continuation, object state, short token, ValueTaskSourceOnCompletedFlags flags);

    void IValueTaskSource.GetResult(short token) => GetResult(token);
    ValueTaskSourceStatus IValueTaskSource.GetStatus(short token) => GetStatus(token);
    void IValueTaskSource.OnCompleted(Action<object> continuation, object state, short token, ValueTaskSourceOnCompletedFlags flags) => OnCompleted(continuation, state, token, flags);
}
```

Which will allow adding an implicit cast operator:

```cs
public readonly struct ValueTask<TResult>
{
    public static implicit operator ValueTask(ValueTask<TResult> rhs)
        => new ValueTask(rhs._canceledTask, rhs._obj, rhs._token, rhs._continueOnCapturedContext);
}
```

### API Usage

```cs
public class MyService
{
    public static ValueTask FuncAsync()
    {
        return OtherService.GetResultAsync();
    }
}


public class OtherService
{
    public static async ValueTask<string> GetResultAsync()
    {
        await Task.Delay(100);
        return "42";
    }
}
```

### Alternative Designs

N/A

### Risks

Default interface implementation takes care of existing `IValueTaskSource<T>` implementations. But there could be some breaking changes to code that uses reflection to check the interface, since the 2 interfaces don't currently inherit.

**Comment by stephentoub** [comment] 2022-03-27 23:35
Duplicate of https://github.com/dotnet/runtime/issues/31503

**Comment by timcassell** [comment] 2022-03-27 23:44
> Duplicate of #31503

Ah woops, I searched if an issue already existed for this and missed that! (And it's locked so I couldn't add anything anyway.)

But do you think the default interface implementation could solve the issue?

**Comment by joperezr** [comment] 2022-10-10 19:16
@stephentoub should this be closed as a dupe then?

**Comment by stephentoub** [comment] 2023-01-21 22:20
> But do you think the default interface implementation could solve the issue?

It assumes that any concrete implementations of both the generic interface and the non-generic interface provide the same functionality, since the cast effectively relies on that.

I'm going to close this as a dup of https://github.com/dotnet/runtime/issues/31503.  If someone wants to experiment with various approaches to using default interface methods here and see how things shake out with all the implementations in netcoreapp, we could consider reopening the original https://github.com/dotnet/runtime/issues/31503.

**Closed by stephentoub** 2023-01-21 22:20 UTC
Labels: api-suggestion, area-System.Threading.Tasks

**Comment by timcassell** [comment] 2023-01-21 23:16
> It assumes that any concrete implementations of both the generic interface and the non-generic interface provide the same functionality

Is that not a safe assumption? Their APIs are practically identical, minus the result type. I can't imagine a scenario where an implementation would diverge on behavior for each interface. Does such an example exist?

**Comment by stephentoub** [comment] 2023-01-21 23:55
I know of real examples (not open) where the generic ivts is implemented multiple times with different Ts and different, unrelated implementations between them; it's not a big leap to assume the same is true between the generic and non-generic. Devs trying to minimize allocations will often use a single object to represent many unrelated things, often by implementing an interface per purpose.

**Comment by stephentoub** [comment] 2023-01-22 00:12
I have an idea for an approach that's likely to be safe. I'll try it out and if it's good I'll open an issue for it.

**Comment by timcassell** [comment] 2023-01-22 00:13
Hm, well that is interesting. But, I don't think that really matters for this case. A consumer converting a `ValueTask<T>` to a `ValueTask` is equivalent to awaiting the original `ValueTask<T>` and ignoring the return value. Even if a single object implements `ValueTask<T>` with many different `T`s, each one when converted to a `ValueTask` will still retain its original await behavior. It's simply discarding the result.
