### ISSUE TITLE
. net core3.1 runtime. missing libgdiplus  in the Linux environment

### ISSUE THREAD

**Issue by lisen508** [dotnet/runtime#38702] opened 2020-07-02 08:09 UTC
. net core3.1 runtime. In Linux environment, GDI component is missing. If it is related image operation or export excel, GDI will not be found. When dockerfile generates image, libgdiplus installation failed due to network problems in China. I suggest that the docker image of the. Net core3.1 runtime provide gdiplus components that run in the Linux environment

The contents of the dockerfile file are as follows, but the docker image cannot be generated successfully

`FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 
RUN apt-get update -y && apt-get install -y libgdiplus && apt-get install -y libc6-dev
RUN apt-get clean && ln -s /usr/lib/libgdiplus.so /usr/lib/gdiplus.dll

WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build

WORKDIR /src
COPY ["BookingPlatformApi/BookingPlatformApi.csproj", "BookingPlatformApi/"]
COPY ["BookingPlatform.Extensions/BookingPlatform.Extensions.csproj", "BookingPlatform.Extensions/"]
COPY ["BookingPlatform.Common/BookingPlatform.Common.csproj", "BookingPlatform.Common/"]
COPY ["BookingPlatform.Core/BookingPlatform.Core.csproj", "BookingPlatform.Core/"]
COPY ["BookingPlatform.Service/BookingPlatform.Service.csproj", "BookingPlatform.Service/"]
COPY ["BookingPlatform.Dal/BookingPlatform.Dal.csproj", "BookingPlatform.Dal/"]
RUN dotnet restore "BookingPlatformApi/BookingPlatformApi.csproj"
COPY . .
WORKDIR "/src/BookingPlatformApi"
RUN dotnet build "BookingPlatformApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "BookingPlatformApi.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "BookingPlatformApi.dll"]
#`

**Comment by davidfowl** [comment] 2020-07-02 08:20
cc @richlander

**Comment by Symbai** [comment] 2020-07-02 08:40
This is expected behavior. Take a look at the .[NET Core dependencies for Linux](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#dependencies) it clearly says to install libgdiplus library yourself.

**Comment by lisen508** [comment] 2020-07-02 09:31
I looked at this dependency because my project runs through docker,
However, maybe due to network problems, when I install libgdiplus through the configuration container in dockerfile, the image generation through vs2019 fails; I can't find out where the error occurs







For .NET Core apps that use the&nbsp;System.Drawing.Common&nbsp;assembly, you also need the following dependency:


libgdiplus (version 6.0.1 or later)











------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Symbai"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月2日(星期四) 下午4:40
收件人:&nbsp;"dotnet/runtime"<runtime@noreply.github.com&gt;;
抄送:&nbsp;"497227965"<497227965@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dotnet/runtime] . net core3.1 runtime. missing libgdiplus  in the Linux environment (#38702)





 
This is expected behavior. Take a look at the .NET Core dependencies for Linux it clearly says to install libgdiplus library yourself.

**Comment by wfurt** [comment] 2020-07-07 05:32
as far as I know this is done on purpose to keep docker images reasonably small by not installing everything. (this is also true for some other rarely used parts like Printing)
Networking issues can be probably resolved by caching and using local mirrors.

**Comment by safern** [comment] 2020-07-07 17:59
Also, I guess the reason why libgdiplus is not in the .NET Core docker images is because System.Drawing.Common is an OOB package and not part of the shared framework. @richlander what do you think we should do here?

**Comment by jkotas** [comment] 2020-07-07 20:26
We have the dependency mentioned in https://docs.microsoft.com/en-us/dotnet/core/install/linux-debian#dependencies . Add an explicit note that it is not included in the default dotnet containers?

**Comment by JeremyKuhne** [comment] 2023-03-14 22:53
Closing this issue as System.Drawing.Common is only supported [on Windows](https://learn.microsoft.com/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only) now.

**Closed by JeremyKuhne** 2023-03-14 22:53 UTC
Labels: area-System.Drawing
