### ISSUE TITLE
Discussion: Deserialization should not validate the match on the property/field data type

### ISSUE THREAD

**Issue by raffaeler** [dotnet/runtime#59804] opened 2021-09-30 12:07 UTC
Let's say I have the following class
```
    public record A
    {
        [JsonConstructor]
        public A(int x) { }

        public int X { get; init; }
    }
```

and I later modify it to the following one:
```
    public record A
    {
        [JsonConstructor]
        public A(int x)
        {
           X = (double)x;
        }

        public double X { get; init; }

    }
```

When deserializing the old json document to the new version of the class I get:

```
System.InvalidOperationException: 'Each parameter in constructor 'Void .ctor(Int32)' on type 'MyConsole.A'
must bind to an object property or field on deserialization.
Each parameter name must match with a property or field on the object. The match can be case-insensitive.'
```

I don't get why the restriction applies to the data type of the property `X` and not just the name.
There are many scenarios where I have to manipulate the data type:
* transforming an array to a list so that it plays well with `IEquatable<>`
* applying a formula to transform the data to a differrent numeric / decimal one
* converting a single element into a collection

The current policy in the serializer is "strict" which I don't understand. Typically json serialization is less aggressive and open to changes (which is the whole point around REST vs SOAP, generally speaking)

**Comment by eiriktsarpalis** [comment] 2021-09-30 13:40
This is something we're considering for .NET 7. Duplicate of #44428.

**Closed by eiriktsarpalis** 2021-09-30 13:40 UTC
Labels: area-System.Text.Json, untriaged

**Comment by eiriktsarpalis** [comment] 2021-09-30 13:43
FWIW this is the proposed design https://github.com/dotnet/runtime/issues/44428#issuecomment-767217872. Please let us know in the other issue if that would solve the issue for you.
