### ISSUE TITLE
Test failure BasicEventSourceTests.TestsWrite.Test_Write_T_ETW

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#93272] opened 2023-10-10 01:21 UTC
Run: [runtime-coreclr libraries-jitstress2-jitstressregs 20230930.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=423555&view=ms.vss-test-web.build-test-results-tab&runId=9310200&resultId=168633&paneView=debug)

Failed test:
```
net9.0-windows-Release-x64-CoreCLR_checked-jitstress2_jitstressregs0x2000-Windows.10.Amd64.Open

- BasicEventSourceTests.TestsWrite.Test_Write_T_ETW
```
**Error message:**
```
System.Runtime.InteropServices.COMException : The instance name passed was not recognized as valid by a WMI data provider. (0x80071069)



Stack trace
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.Flush()
   at BasicEventSourceTests.EtwListener.Dispose() in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/Harness/EtwListener.cs:line 97
   at BasicEventSourceTests.TestsWrite.Test_Write_T_ETW() in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/TestsWrite.Etw.cs:line 27
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by danmoseley** [comment] 2023-10-10 03:26
dupe of https://github.com/dotnet/runtime/issues/91769

**Closed by danmoseley** 2023-10-10 03:26 UTC
Labels: area-System.Diagnostics.Tracing, os-windows, JitStress, arch-x64, untriaged
