### ISSUE TITLE
Enhance JsonConsoleFormatter to be configurable and avoid to duplicate information

### ISSUE THREAD

**Issue by rmannibucau** [dotnet/runtime#110373] opened 2024-12-03 19:56 UTC
### Description

By default the json console formatter will create a message field and will duplicate it within the state and setting IncludeState=false is quite useless there.

What is desired is to be able to switch between both but ultimately not have both (either be fully structured or precomputed).

Some new options can solve it easily so guess it is the way to go.

### Reproduction Steps

Just log in json over the console

### Expected behavior

message is not in the state

### Actual behavior

message is both at the root and within nested state objects

### Known Workarounds

custom provider but highly undesired

**Comment by tarekgh** [comment] 2024-12-03 22:19
This is duplicate of https://github.com/dotnet/runtime/issues/104409.

**Closed by tarekgh** 2024-12-03 22:19 UTC
Labels: untriaged, area-Extensions-Logging
