### ISSUE TITLE
[Regression] Header value duplicated

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#55898] opened 2021-07-19 04:43 UTC
I am running the Grpc.Net.Client tests on .NET 6. I have noticed some intermittent errors caused by `SocketsHttpHandler` returning two values for an HTTP/2 header that should only ever have one value.

![image](https://user-images.githubusercontent.com/303201/126103286-6d05587a-11de-4627-b58d-7fc1b9ccac15.png)

Headers in the client (note the duplicate "14" values):

![image](https://user-images.githubusercontent.com/303201/126103884-1c852962-1b09-4f60-b1f9-46d91176880b.png)

I have confirmed the server is only returning the header once:

![image](https://user-images.githubusercontent.com/303201/126103822-437f3b07-ff12-4841-a5ad-7e00df29ec34.png)

This error is intermittent. Is it a thread-safety/race condition?

Wireshark trace: [duplicate-footer-value.zip](https://github.com/dotnet/runtime/files/6837954/duplicate-footer-value.zip)

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.6.21328.10
 Commit:    2630e4ccfe
```

**Comment by JamesNK** [comment] 2021-07-19 05:00
Got a different error while trying to get more detail:
```
Object reference not set to an instance of an object.
   at System.Net.Http.Headers.HttpHeaders.ReadStoreValues[T](Span`1 values, Object storeValue, HttpHeaderParser parser, Int32& currentIndex)
   at System.Net.Http.Headers.HttpHeaders.GetStoreValuesAsStringOrStringArray(HeaderDescriptor descriptor, Object sourceValues, String& singleValue, String[]& multiValue)
   at System.Net.Http.Headers.HttpHeaders.GetStoreValuesAsStringArray(HeaderDescriptor descriptor, HeaderStoreItemInfo info)
   at System.Net.Http.Headers.HttpHeaders.<GetEnumeratorCore>d__27.MoveNext()
   at Grpc.Net.Client.Internal.GrpcProtocolHelpers.BuildMetadata(HttpHeaders responseHeaders) in C:\Development\Source\grpc-dotnet\src\Grpc.Net.Client\Internal\GrpcProtocolHelpers.cs:line 66
```
I think this error, the duplicate headers and https://github.com/dotnet/runtime/issues/55896 are all related. Race conditions in response headers are causing many different issues.

**Comment by MihaZupan** [comment] 2021-07-19 08:26
Is any special setup required to reproduce the issue?

I haven't hit such a failure yet running `dotnet test Grpc.Net.Client.Tests -f net6.0` with `6.0.100-preview.6.21328.10`.

**Comment by JamesNK** [comment] 2021-07-19 09:23
https://github.com/JamesNK/grpc-dotnet/tree/jamesnk/http3-headers-issue

Running the tests in ﻿`Grpc.AspNetCore.FunctionalTests (net6.0)` will cause some tests to fail. There are various test failures, some I haven't raised issues for. The header issue failures tend to be in the `HedgingTests` and `RetryTests` classes.

It might be difficult to narrow down because the tests this fails in changes and there are other issues causing failures.

**Comment by karelz** [comment] 2021-07-19 09:50
@JamesNK can you please confirm it is HTTP/2? (your repro is named http3)

**Comment by JamesNK** [comment] 2021-07-19 20:04
I'm updating to .NET 6 to test out HTTP/3, but this is an HTTP/2 test that is failing.

In the server logs above you can see the server receiving and sending HTTP/2 frames.

**Comment by MihaZupan** [comment] 2021-07-20 14:47
I believe all of these issues (duplicated value, NRE in enumeration and the invalid cast) all share the same underlying cause:
**`HttpHeaders` is not a thread-safe collection - not even for reading.***

Enumerating / accessing values will force parsing, which involves mutating the internal state of the headers collection.

Note that `HttpHeaders` were not thread-safe in 5.0 either. You may run into side-effects from concurrent `Dictionary` modifications. By sheer luck of those being in-place replacements / removes only, you may actually get away with it.
cc: @stephentoub 

What changed in 6 was that the race window increased and more side-effects of violating thread-safety became possible.
#54130 removed a lock around parsing that was preventing the effects you reported:
- Duplicated values (both threads see raw values and start parsing, both end up storing the parsed value)
  - #55896 is just another way of the duplication breaking internal assumptions leading to undefined behavior
- Non-initialized state (NRE in `ReadStoreValues` during enumeration)


*Reading may be thread-safe if you are only using the `NonValidated` view of the headers, as that is effectively just wrapping `Dictionary` reads.

**Comment by MihaZupan** [comment] 2021-07-20 14:50
Looking at the gRPC implementation, it looks like multiple threads may wait for the internal `httpResponseTask` to complete and may all inspect response headers at the same time.

It is possible that this was "safe" in 5.0 by chance, not design.

**Comment by karelz** [comment] 2021-07-20 15:16
Interesting analysis and find @MihaZupan!
If it is true, then we should consider where to do the fix ... in gRPC or try to provide similar (unintended) guarantees in .NET Core ... @JamesNK @geoffkizer what do you think?

**Comment by JamesNK** [comment] 2021-07-20 19:48
In my opinion, it is pretty weird that a collection isn't thread-safe to read from. It was thread-safe before now because the code that is failing hasn't changed and I haven't seen problems.

**Comment by JamesNK** [comment] 2021-07-20 19:54
I can update gRPC to lock when reading the headers if the decision is to leave it unchanged. However I worry about all the other code out there that works today and will subtly start breaking in .NET 6...

**Comment by karelz** [comment] 2021-07-20 21:10
We discussed it today and believe that 99.9% of code will be single-threaded in usage. If gRPC can make the fix, we will wait for another report and then consider fixing it (even in servicing as the change is targeted).

**Comment by JamesNK** [comment] 2021-07-20 22:51
I agree it isn't common, the question is how many people is 0.1%? 😬

I updated gRPC to use `Headers.NonValidated` and the issue has disappeared: https://github.com/JamesNK/grpc-dotnet/commit/7420200e6930a1c6bbe1d19db9148975a412ac10

**Comment by stephentoub** [comment] 2021-07-20 23:01
> I agree it isn't common

It's not that it's not common,  it's that it's incorrect. Lots of things mutate on read, anything lazily initialized (which is effectively what this is), and the type simply isn't thread safe, never has been. If we were to add the lock (which doesn't actually make the type thread-safe),  it would be to mitigate buggy consuming code like that in gRPC.

**Comment by stephentoub** [comment] 2021-07-20 23:45
Can you elaborate on why gRPC ends up consuming the headers concurrently? I'm glad you're using NonValidated; it's better for perf.  But technically it has the same issue,  and the fact that it works concurrently today is an implementation detail we don't actually guarantee.  We could choose to document it as such,  but I'm hesitant to do so as it can back us into a corner.

**Comment by JamesNK** [comment] 2021-07-21 01:31
The gRPC client needs to validate headers before providing the result (i.e. is the content-type `application/grpc`), and also give access to response headers.

e.g.
```cs
var call = client.SayHello(...);
var resultTask = call.GetResultAsync();
var headersTask = call.GetResponseHeadersAsync();

var result = await resultTask;
var headers = await headersTask;
```

There are some other reasons as well.

I'll see if there is a clean way to lock access to the headers connection. It is used in quite a few places.

**Comment by stephentoub** [comment] 2021-07-21 11:47
> The gRPC client needs to validate headers before providing the result (i.e. is the content-type application/grpc), and also give access to response headers.

It can't validate them as part of giving access to them?

**Comment by JamesNK** [comment] 2021-07-21 20:06
Accessing response headers is optional. Most people don't and get the result only.

It would be simple to create a collection and copy all the headers and then use them however we want, including giving that collection back to the user, but I don't want to do that for performance. I want to keep accessing response headers pay-for-play.

**Comment by MihaZupan** [comment] 2021-07-22 01:27
If I understand Stephen's suggestion, you can perform the validation of the headers you care about internally before releasing the response task.

i.e. instead of synchronizing on a `Task<HttpResponseMessage>`, expose `Task<MyFancyResponse>` where you perform the common parsing/validation logic ahead of time.
```c#
internal sealed class MyFancyResponse
{
    public readonly HttpResponseMessage Response;
    public readonly Status? Status;
    public readonly Metadata? Trailers;
    public readonly Metadata Metadata;
    public readonly string GrpcEncoding;

    public MyFancyResponse(HttpResponseMessage response)
    {
        Response = response;
        Status = ValidateHeaders(response, out Trailers);
        Metadata = GrpcProtocolHelpers.BuildMetadata(response.Headers);
        GrpcEncoding = GrpcProtocolHelpers.GetGrpcEncoding(response);
        // ...
    }
}
```

(I was just skimming the gRPC codebase so idk how applicable all of the above is)

**Comment by karelz** [comment] 2021-07-29 08:01
Triage: As discussed above, we don't believe this is common use case for customers and there is workaround (locking externally).
We do not believe it is worth adding complexity and perf overhead for scenarios which don't need this. Closing.

**Closed by karelz** 2021-07-29 08:01 UTC
Labels: area-System.Net.Http, bug
