### ISSUE TITLE
System.Diagnostics.Tracing.Tests BasicEventSourceTests.TestsManifestGeneration test fails on windows x86 leg

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#97255] opened 2024-01-20 22:16 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=534064
Build error leg or test failing: `BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGeneration` and `BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover`
Pull request: https://github.com/dotnet/runtime/pull/97177

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Test_EventSource_EtwManifestGeneration",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```
From [log](https://helix.dot.net/api/2019-06-17/jobs/ba7e7b90-1d04-4a5d-805f-d0e52f81ea56/workitems/System.Diagnostics.Tracing.Tests/console):
```log
Did not see ManifestData event from SimpleEventSource, test will fail. Additional info:
    file name initialFile.2884.etl
    total event count 0
    total providers 0
Did not see ManifestData event from SimpleEventSource, test will fail. Additional info:
    file name initialFile.2884.etl
    total event count 0
    total providers 0
    BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/TestsManifestGeneration.Etw.cs(132,0): at BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(48,0): at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[534656](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534656)|dotnet/runtime|[BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534656&view=ms.vss-test-web.build-test-results-tab&runId=12626382&resultId=130538)|dotnet/runtime#97177|
|[534648](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534648)|dotnet/runtime|[BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534648&view=ms.vss-test-web.build-test-results-tab&runId=12626266&resultId=126363)|dotnet/runtime#92974|
|[534575](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534575)|dotnet/runtime|[BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534575&view=ms.vss-test-web.build-test-results-tab&runId=12624764&resultId=135420)|dotnet/runtime#97234|
|[534574](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534574)|dotnet/runtime|[BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534574&view=ms.vss-test-web.build-test-results-tab&runId=12624612&resultId=138663)|dotnet/runtime#97237|
|[534548](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534548)|dotnet/runtime|[BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534548&view=ms.vss-test-web.build-test-results-tab&runId=12623186&resultId=126272)|dotnet/runtime#97253|
|[534228](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534228)|dotnet/runtime|[BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534228&view=ms.vss-test-web.build-test-results-tab&runId=12621766&resultId=125145)|dotnet/runtime#97246|
|[534531](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534531)|dotnet/runtime|[BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534531&view=ms.vss-test-web.build-test-results-tab&runId=12621456&resultId=135211)||
|[534277](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534277)|dotnet/runtime|[BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534277&view=ms.vss-test-web.build-test-results-tab&runId=12621422&resultId=150471)|dotnet/runtime#97109|
|[534478](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534478)|dotnet/runtime|[BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534478&view=ms.vss-test-web.build-test-results-tab&runId=12620554&resultId=124000)|dotnet/runtime#97152|
|[534443](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534443)|dotnet/runtime|[BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534443&view=ms.vss-test-web.build-test-results-tab&runId=12619682&resultId=129927)|dotnet/runtime#97098|
|[533560](https://dev.azure.com/dnceng-public/public/_build/results?buildId=533560)|dotnet/runtime|[BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover](https://dev.azure.com/dnceng-public/public/_build/results?buildId=533560&view=ms.vss-test-web.build-test-results-tab&runId=12617254&resultId=157375)|dotnet/runtime#96732|
|[534303](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534303)|dotnet/runtime|[BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534303&view=ms.vss-test-web.build-test-results-tab&runId=12614562&resultId=135512)|dotnet/runtime#96941|
|[534064](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534064)|dotnet/runtime|[BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534064&view=ms.vss-test-web.build-test-results-tab&runId=12613518&resultId=160566)|dotnet/runtime#97177|
|[534236](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534236)|dotnet/runtime|[BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534236&view=ms.vss-test-web.build-test-results-tab&runId=12612724&resultId=126511)|dotnet/runtime#97130|
|[534201](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534201)|dotnet/runtime|[BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534201&view=ms.vss-test-web.build-test-results-tab&runId=12611950&resultId=130495)|dotnet/runtime#97244|
|[534171](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534171)|dotnet/runtime|[BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534171&view=ms.vss-test-web.build-test-results-tab&runId=12611378&resultId=129794)|dotnet/runtime#96386|
|[534134](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534134)|dotnet/runtime|[BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534134&view=ms.vss-test-web.build-test-results-tab&runId=12610786&resultId=150946)|dotnet/runtime#97237|
|[534109](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534109)|dotnet/runtime|[BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover](https://dev.azure.com/dnceng-public/public/_build/results?buildId=534109&view=ms.vss-test-web.build-test-results-tab&runId=12610540&resultId=148002)|dotnet/runtime#97238|
|[533969](https://dev.azure.com/dnceng-public/public/_build/results?buildId=533969)|dotnet/runtime|[BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover](https://dev.azure.com/dnceng-public/public/_build/results?buildId=533969&view=ms.vss-test-web.build-test-results-tab&runId=12610190&resultId=138105)|dotnet/runtime#97234|
|[533830](https://dev.azure.com/dnceng-public/public/_build/results?buildId=533830)|dotnet/runtime|[BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover](https://dev.azure.com/dnceng-public/public/_build/results?buildId=533830&view=ms.vss-test-web.build-test-results-tab&runId=12606606&resultId=155099)|dotnet/runtime#97232|
|[533920](https://dev.azure.com/dnceng-public/public/_build/results?buildId=533920)|dotnet/runtime|[BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover](https://dev.azure.com/dnceng-public/public/_build/results?buildId=533920&view=ms.vss-test-web.build-test-results-tab&runId=12605752&resultId=155358)|dotnet/runtime#97089|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|18|21|21|

**Comment by tommcdon** [comment] 2024-01-20 22:25
@davmason @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment] 2024-01-21 01:03
Sad. I'm going to disable this test now. I'm very confused as to why this is occuring.

**Comment by v-wenyuxu** [comment] 2024-05-30 01:17
**Failed in:** [runtime-coreclr libraries-jitstress 20240529.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=690710&view=ms.vss-test-web.build-test-results-tab&runId=17154110&resultId=151071&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x64-disabler2r-Windows.10.Amd64.Open
    - BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover
```

**Error message:**
```
 Assert.True() Failure
Expected: True
Actual:   False
```

**Stack trace:**
```
   at BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover() in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/TestsManifestGeneration.Etw.cs:line 123
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by v-wenyuxu** [comment] 2024-06-24 06:29
**Failed in:** [runtime-coreclr libraries-jitstress 20240621.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=715271&view=ms.vss-test-web.build-test-results-tab&runId=17897042&resultId=146252&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-arm64-disabler2r-Windows.11.Arm64.Open
    - BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover
```

**Error message:**
```
Assert.True() Failure
Expected: True
Actual:   False
```

**Stack trace:**
```
   at BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover() in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/TestsManifestGeneration.Etw.cs:line 123
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by v-wenyuxu** [comment] 2024-06-26 01:52
**Failed in:** [runtime-coreclr libraries-jitstress 20240625.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=719303&view=ms.vss-test-web.build-test-results-tab&runId=18029066&resultId=143745&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-arm64-disabler2r-Windows.11.Arm64.Open
    - BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover
```

**Error message:**
```
 Assert.True() Failure
Expected: True
Actual:   False
```

**Stack trace:**
```
   at BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover() in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/TestsManifestGeneration.Etw.cs:line 123
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by v-wenyuxu** [comment] 2024-07-10 01:33
**Failed in:** [runtime-coreclr libraries-jitstress 20240709.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=734095&view=ms.vss-test-web.build-test-results-tab&runId=18482862&resultId=148346&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x64-disabler2r-Windows.10.Amd64.Open
    - BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover
```

**Error message:**
```
 Assert.True() Failure
Expected: True
Actual:   False
```

**Stack trace:**
```
   at BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover() in /_/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/TestsManifestGeneration.Etw.cs:line 123
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by davmason** [comment] 2024-07-18 07:16
Closing as duplicate of #88027

**Closed by davmason** 2024-07-18 07:16 UTC
Labels: arch-x86, area-System.Diagnostics.Tracing, disabled-test, os-windows
