### ISSUE TITLE
Project including "System.Management" nuget package can not be used by other project(dynamic load this project), because "System.Management" causes an exception: FileNotFoundException

### ISSUE THREAD

**Issue by ehnap** [dotnet/runtime#31563] opened 2019-11-25 10:26 UTC
[TestManagementLoad.zip](https://github.com/dotnet/corefx/files/3886032/TestManagementLoad.zip)

System.Management is 4.6.0

Maybe the same question: [#39975](https://github.com/dotnet/corefx/issues/39975)

I write a demo.

- Project ManagementProxy add "System.Management" nuget and use it.
- Project TestManagementLoad loads Project ManagementProxy. 

Run it. An exception occurred.

**System.Reflection.TargetInvocationException:“Exception has been thrown by the target of an invocation.”**
Inner exception
**FileNotFoundException: Could not load file or assembly 'System.Management, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'**

**Comment by Anipik** [comment] 2020-06-24 18:11
cc @joperezr

**Comment by joperezr** [comment] 2020-07-17 19:08
Hello @ehnap I'm so sorry for some reason I missed the pings on this issue until now. What you are seeing is by design, and the reason is that building a class library will by default not include it's dependencies with it on the output directory so what your ManagementProxy project is doing is only building the .dll and copying only ManagementProxy.dll over into the bin folder of your TestManagementLoad, so when you try to execute that application, System.Management is not placed with it.

What you are probably looking for would be resolved if instead of just building ManagementProxy project, you publish it. When publishing a class library, all of the dependencies will get copied to the publish directory as well so in this case, it should include System.Management.dll as well.

For your concrete example, I tried the exact same example except that instead of just building your ManagmenetProxy project, I went and removed the lines that were doing the binplacing into a different output path and instead used a command like:
`dotnet publish ManagementProxy.csproj -r win-x64 -o .\..\TestManagementLoad\bin\Debug\netcoreapp3.1\` and that did it for me as now the library System.Management.dll was also copied and the application was able to load it via reflection.

I'll go ahead and close this issue for now given the question has been answered but please don't hesitate on reopening if you have any follow up questions.

**Closed by joperezr** 2020-07-17 19:08 UTC
Labels: area-System.Management, untriaged

**Comment by joperezr** [comment] 2020-07-17 19:09
Also just for bonus points, Once I got this to work on my machine I noticed that you will start hitting a different exception on your Class1.cs because you forgot to initialize sDeviceNameString :) here is the fix:
```cs
        private static string sDeviceNameString = string.Empty;

        public static string UseManagement()
        {
            if (sDeviceNameString.Length == 0)
            {
```

**Comment by jkotas** [comment] 2020-07-17 19:52
Also, once you are get ManagemtProxy.dll published correctly, you may consider loading it using `Assembly.Load`. `Assembly.LoadFile` loads the assembly into its own load context that is typically not what you want for standalone application.

**Comment by ehnap** [comment] 2020-07-18 15:56
Thx! 😁
