### ISSUE TITLE
timeout in FailedRequests_ConnectionClosedWhileReceivingHeaders_Recorded 

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#88921] opened 2023-07-14 16:54 UTC
```
Console log: 'System.Net.Http.Functional.Tests' from job f2a94597-4961-4bcf-869c-b538b124b3ba workitem 983827fb-985c-4a56-bc1c-b16f6db5925f (osx.1200.amd64.open) executed on machine dci-mac-build-192 running macOS-12.6.6

    System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async.FailedRequests_ConnectionClosedWhileReceivingHeaders_Recorded [FAIL]
      System.TimeoutException : The operation has timed out.
      Stack Trace:
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/MetricsTest.cs(500,0): at System.Net.Http.Functional.Tests.HttpMetricsTest_Http11.<>c__DisplayClass4_0.<<FailedRequests_ConnectionClosedWhileReceivingHeaders_Recorded>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(120,0): at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(90,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Net/Http/GenericLoopbackServer.cs(39,0): at System.Net.Test.Common.LoopbackServerFactory.<>c__DisplayClass5_0.<<CreateClientAndServerAsync>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs(107,0): at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/MetricsTest.cs(494,0): at System.Net.Http.Functional.Tests.HttpMetricsTest_Http11.FailedRequests_ConnectionClosedWhileReceivingHeaders_Recorded()
        --- End of stack trace from previous location ---
```
https://[helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-88913-merge-f2a9459749614bcf86/System.Net.Http.Functional.Tests/3/console.353c738b.log?helixlogtype=result](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-88913-merge-f2a9459749614bcf86/System.Net.Http.Functional.Tests/3/console.353c738b.log?helixlogtype=result)

hit in https://github.com/dotnet/runtime/pull/88913

## Error Message

```json
{
    "ErrorMessage": "FailedRequests_ConnectionClosedWhileReceivingHeaders_Recorded",
    "BuildRetry": false,
    "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[342249](https://dev.azure.com/dnceng-public/public/_build/results?buildId=342249)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async.FailedRequests_ConnectionClosedWhileReceivingHeaders_Recorded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=342249&view=ms.vss-test-web.build-test-results-tab&runId=7148728&resultId=207587)|dotnet/runtime#89030|
|[342208](https://dev.azure.com/dnceng-public/public/_build/results?buildId=342208)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async.FailedRequests_ConnectionClosedWhileReceivingHeaders_Recorded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=342208&view=ms.vss-test-web.build-test-results-tab&runId=7147124&resultId=208001)|dotnet/runtime#89026|
|[342096](https://dev.azure.com/dnceng-public/public/_build/results?buildId=342096)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async.FailedRequests_ConnectionClosedWhileReceivingHeaders_Recorded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=342096&view=ms.vss-test-web.build-test-results-tab&runId=7144348&resultId=207615)|dotnet/runtime#89018|
|[341962](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341962)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async.FailedRequests_ConnectionClosedWhileReceivingHeaders_Recorded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341962&view=ms.vss-test-web.build-test-results-tab&runId=7140672&resultId=202852)|dotnet/runtime#84169|
|[341912](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341912)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async.FailedRequests_ConnectionClosedWhileReceivingHeaders_Recorded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341912&view=ms.vss-test-web.build-test-results-tab&runId=7140236&resultId=207714)|dotnet/runtime#89000|
|[341906](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341906)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async.FailedRequests_ConnectionClosedWhileReceivingHeaders_Recorded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341906&view=ms.vss-test-web.build-test-results-tab&runId=7140090&resultId=207618)|dotnet/runtime#88999|
|[341721](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341721)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async.FailedRequests_ConnectionClosedWhileReceivingHeaders_Recorded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341721&view=ms.vss-test-web.build-test-results-tab&runId=7136584&resultId=208149)|dotnet/runtime#87773|
|[341711](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341711)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async.FailedRequests_ConnectionClosedWhileReceivingHeaders_Recorded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341711&view=ms.vss-test-web.build-test-results-tab&runId=7134964&resultId=207823)|dotnet/runtime#86089|
|[341703](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341703)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async.FailedRequests_ConnectionClosedWhileReceivingHeaders_Recorded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341703&view=ms.vss-test-web.build-test-results-tab&runId=7134846&resultId=207943)|dotnet/runtime#88723|
|[341622](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341622)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async.FailedRequests_ConnectionClosedWhileReceivingHeaders_Recorded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341622&view=ms.vss-test-web.build-test-results-tab&runId=7134832&resultId=176690)||
|[341678](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341678)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async.FailedRequests_ConnectionClosedWhileReceivingHeaders_Recorded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341678&view=ms.vss-test-web.build-test-results-tab&runId=7134738&resultId=208200)|dotnet/runtime#88656|
|[341591](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341591)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async.FailedRequests_ConnectionClosedWhileReceivingHeaders_Recorded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341591&view=ms.vss-test-web.build-test-results-tab&runId=7131700&resultId=208176)|dotnet/runtime#88550|
|[341577](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341577)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async.FailedRequests_ConnectionClosedWhileReceivingHeaders_Recorded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341577&view=ms.vss-test-web.build-test-results-tab&runId=7130710&resultId=207362)||
|[341533](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341533)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async.FailedRequests_ConnectionClosedWhileReceivingHeaders_Recorded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341533&view=ms.vss-test-web.build-test-results-tab&runId=7129050&resultId=208216)|dotnet/runtime#86089|
|[341492](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341492)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async.FailedRequests_ConnectionClosedWhileReceivingHeaders_Recorded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341492&view=ms.vss-test-web.build-test-results-tab&runId=7127736&resultId=208589)|dotnet/runtime#88871|
|[341426](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341426)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async.FailedRequests_ConnectionClosedWhileReceivingHeaders_Recorded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341426&view=ms.vss-test-web.build-test-results-tab&runId=7126600&resultId=207912)|dotnet/runtime#88970|
|[341416](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341416)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async.FailedRequests_ConnectionClosedWhileReceivingHeaders_Recorded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341416&view=ms.vss-test-web.build-test-results-tab&runId=7126452&resultId=207695)|dotnet/runtime#88853|
|[341397](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341397)|dotnet/runtime|[WasmTestOnBrowser-System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341397&view=ms.vss-test-web.build-test-results-tab&runId=7125894&resultId=185849)|dotnet/runtime#88974|
|[341305](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341305)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async.FailedRequests_ConnectionClosedWhileReceivingHeaders_Recorded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341305&view=ms.vss-test-web.build-test-results-tab&runId=7124652&resultId=172938)||
|[341298](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341298)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async.FailedRequests_ConnectionClosedWhileReceivingHeaders_Recorded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341298&view=ms.vss-test-web.build-test-results-tab&runId=7124632&resultId=175353)|dotnet/runtime#88723|
|[341260](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341260)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async.FailedRequests_ConnectionClosedWhileReceivingHeaders_Recorded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341260&view=ms.vss-test-web.build-test-results-tab&runId=7122116&resultId=206411)|dotnet/runtime#88869|
|[341220](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341220)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async.FailedRequests_ConnectionClosedWhileReceivingHeaders_Recorded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341220&view=ms.vss-test-web.build-test-results-tab&runId=7121970&resultId=177910)|dotnet/runtime#87847|
|[341209](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341209)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async.FailedRequests_ConnectionClosedWhileReceivingHeaders_Recorded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341209&view=ms.vss-test-web.build-test-results-tab&runId=7120762&resultId=176890)|dotnet/runtime#88163|
|[341090](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341090)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async.FailedRequests_ConnectionClosedWhileReceivingHeaders_Recorded](https://dev.azure.com/dnceng-public/public/_build/results?buildId=341090&view=ms.vss-test-web.build-test-results-tab&runId=7118640&resultId=176828)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|21|24|24|

**Comment by CarnaViire** [comment] 2023-07-14 17:24
Seems like a dupe of #88868?

**Comment by antonfirsov** [comment] 2023-07-17 20:56
Duplicate of https://github.com/dotnet/runtime/issues/88868.

**Closed by antonfirsov** 2023-07-17 20:56 UTC
Labels: area-System.Net.Http, untriaged, Known Build Error
