### ISSUE TITLE
JsonElement returned from JsonElement.ParseValue contains disposable resource (JsonDocument)

### ISSUE THREAD

**Issue by scharnyw** [dotnet/runtime#89832] opened 2023-08-02 03:19 UTC
I was led here from [this Stackoverflow question](https://stackoverflow.com/questions/57505912/am-i-creating-a-leak-here/58119555#58119555).

When consumers call `JsonElement.ParseValue()` (and `JsonElement.TryParseValue()`), the returned `JsonElement` owns a `JsonDocument`, which not only implements `IDisposable`, but also has its `IsDisposable` property set to `true`. To consumers, this implies that it holds disposable resources and should be disposed of properly, but of course this is impossible because the `JsonDocument` is not exposed to consumers. I think this may cause confusion for developers who use the `JsonElement.ParseValue()` API (which BTW is used as the underlying implementation by a ton of other APIs that create `JsonElement`s) because it violates a basic coding rule in .NET (ensure that disposable resources are properly disposed of) which is entrenched and well-codified via the `IDisposable` interface.

Since it appears that the `JsonDocument` created in `JsonElement.ParseValue()` does not actually use any rented memory, and it's impossible to be disposed of anyway, may I suggest the following:
1. Set its `IsDisposable` property to `false`
2. Document this behavior of `JsonElement.ParseValue()` or `JsonDocument` to avoid confusion (maybe something along the lines of "If the `IsDisposable` property returns `false`, you do not need to worry about disposing it"?). Personally I've spent quite some time investigating whether this will cause a resource leak/performance impact and apparently I'm not the only one with such a concern, which could be addressed much more quickly with some concrete documentation from MS.

These are just primitive thoughts from someone who consumes STJ and knows nothing about its internal workings, so they may not be valid. Any advice or opinions on this matter would be appreciated.

**Comment by eiriktsarpalis** [comment] 2023-08-02 10:02
Duplicate of https://github.com/dotnet/runtime/issues/87751. Should be fixed in .NET 8 by #87766

**Closed by eiriktsarpalis** 2023-08-02 10:02 UTC
Labels: area-System.Text.Json, untriaged
