### ISSUE TITLE
CoreCLR version in profiler API

### ISSUE THREAD

**Issue by iskiselev** [dotnet/runtime#12125] opened 2019-02-26 02:07 UTC
Profiler API already exposed method that expect to be used to resolve version, ICorProfilerInfo3::GetRuntimeInformation.
Unfortunately there is no documentation that will map results from it to marketing CoreCLR releases.
Per my tests it returns on Windows:
4.0.22220 for CoreCLR 2.0.9
4.0.30319 for  CoreCLR 2.1.8, 2.2.0

Should it return value unique for each CoreCLR release? Should there be another API to resolve coreclr version (if we are talking about profiler, it will be some version associated with coreclr.dll)? Is there any existing way to resolve this version cross-platform? coreclr.dll on windows has File Version and Product version, are there something similar on other OS?

Will dotnet/runtime#12124 fix version resolution in profiler API?

cc: @noahfalk

**Comment by ww898** [comment] 2020-03-17 14:21
Hi @davmason, just tested `v5.0.0-preview1`. The issue is till present: `System.Environment.Version` returns `5.0.0`, but `ICorProfilerInfo3::GetRuntimeInformation` still `4.0.30319`.

**Comment by ww898** [comment] 2020-03-18 20:30
I found new `ICorProfilerInfo12`. It helps me to detect .NET v5.0.

**Comment by davmason** [comment] 2020-04-27 21:29
Fixed in #35327

**Closed by davmason** 2020-04-27 21:29 UTC
Labels: area-Diagnostics-coreclr, enhancement
