### ISSUE TITLE
Interoperability of C# and F# Record Types

### ISSUE THREAD

**Issue by shanoaice** [dotnet/runtime#58687] opened 2021-09-05 03:42 UTC
*(Unsure where should this issue fit)*
F# Records and C# Records (added in C# 9.0), on the surface, looked very similiar: they both have immutable fields, value equality (structural equality) and able to create a new record based on a previous record using the `with` keyword. They even have a similiar type signature when exposed to each other (unsure about this). 

However, C# and F# both don't understand the record of the other one, meaning that when F# records are exposed to a C# App/Lib, they are treated as normal classes with readonly properties and cannot be used in a with expression. This is the same vice versa. 

I am thinking about if it is possible to make them equivalent, so that C# records can be used as if it is the F# counterpart in F# projects, and vice versa.

**Comment by am11** [comment] 2021-09-05 04:58
At CIL level, C# record is compiled down to [a class](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBLANgHwGEACMYgXmIDsYB3ACgEoBuAWACgwA6ADQuICMbTlwCa/AEzCOAAQDMxWJCgATYoQ4B6TQAcArsGxkZE9RwDeHYteLzi2KhmI9hN2wodPRwgL5A==) (with some helpers). There is no special idiom for record in the IL.

**Comment by shanoaice** [comment] 2021-09-05 06:09
> At CIL level, C# record is compiled down to [a class](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBLANgHwGEACMYgXmIDsYB3ACgEoBuAWACgwA6ADQuICMbTlwCa/AEzCOAAQDMxWJCgATYoQ4B6TQAcArsGxkZE9RwDeHYteLzi2KhmI9hN2wodPRwgL5A==) (with some helpers). There is no special idiom for record in the IL.

I do notice that, so do F# records, but F# records is also compiled down to a class with some helper, I see their IL is a bit different, but is it possible to let F# able to apply with expression on a C# record or construct a C# record in F#'s way (i.e. a bracket notation like this: `let someCSharpRecord = { CSharpRecord.X = 1; Y = 1 }`

**Comment by teo-tsirpanis** [comment] 2021-09-05 06:43
Duplicate of fsharp/fslang-suggestions#903 and fsharp/fslang-suggestions#904.

**Comment by shanoaice** [comment] 2021-09-05 13:43
> Duplicate of [fsharp/fslang-suggestions#903](https://github.com/fsharp/fslang-suggestions/issues/903) and [fsharp/fslang-suggestions#904](https://github.com/fsharp/fslang-suggestions/issues/904).

thanks for your reply! so......should I close this issue?

**Comment by teo-tsirpanis** [comment] 2021-09-05 13:48
Yes, I think so.

**Closed** 2021-09-05 13:48 UTC
Labels: untriaged
