### ISSUE TITLE
CILJit::compileMethod  ::  Slow processing 

### ISSUE THREAD

**Issue by TuniDev83** [dotnet/runtime#103751] opened 2024-06-20 10:53 UTC
Greeting,

We are using Azure WebApp, with windows system and .Net8
Randomly, some response from our API suck and take time because of CILJit::compileMethod

Is there any recommendation to solve this issue.
Thank's

![image](https://github.com/dotnet/runtime/assets/170094015/8ba9c3d2-5550-403b-b432-e28dbfe29171)

**Comment by En3Tho** [comment] 2024-06-20 11:14
Can you export this graph somehow (text maybe)? Or at least jit related parts.

**Comment by TuniDev83** [comment] 2024-06-20 12:25
Sorry, from Azure I'm not able to do any export such data, 
but there is something got my attention. Inside CILJit::compileMethod (deep level, there is waiting). 
I'm not able to know for what!!!

![image](https://github.com/dotnet/runtime/assets/170094015/8985e06c-0534-46c5-8a5c-df41017b6f1d)

**Comment by EgorBo** [comment] 2024-06-20 12:35
Looks like a dead-lock in `EEJitManager::allocCode` ? 🤔

**Comment by AndyAyersMS** [comment] 2024-06-20 14:43
Might be the same issue as in https://github.com/dotnet/runtime/issues/102858

**Comment by ken-swyfft** [comment] 2024-06-20 15:47
One way to troubleshoot this would be to disable the Azure Application Insights Profiler - see this SO post here: https://stackoverflow.com/a/78524471/68231.

We were having a similar (same?) problem, where certain API calls to our website would randomly take 100-1000 times as long as they should. Turning off the Application Insights Profiler fixed it immediately. I think ours was the specific problem that kicked off #102858.

**Comment by JulieLeeMSFT** [comment] 2024-06-20 15:55
@brianrob, PTAL.

**Comment by brianrob** [comment] 2024-06-20 22:54
Based on what I can see in the screenshot, I expect this is a dupe of https://github.com/dotnet/runtime/issues/102858.

**Comment by brianrob** [comment] 2024-06-20 22:55
@pharring, does this look like the same issue we looked at regarding rundown?

**Comment by TuniDev83** [comment] 2024-07-05 08:15
Hello again,
Is there any solution for that issue ?

**Comment by brianrob** [comment] 2024-07-11 22:53
This is a duplicate of #102858.  There is not a solution at this point, but #102858 will track the fix.

**Closed by brianrob** 2024-07-11 22:53 UTC
Labels: tenet-performance, area-CodeGen-coreclr
