### ISSUE TITLE
JSON source generator fails to compile with CS1503 errors if two enums with the same name are used

### ISSUE THREAD

**Issue by martincostello** [dotnet/runtime#62080] opened 2021-11-26 15:02 UTC
### Description

If an application tries to use the JSON source generator where there are two different enum types with the same name in different namespaces registered with a `JsonSerializerContext`, the application fails to compile with a `CS1503` error.

Further, the suggested workaround for the `SYSLIB1031` warning cannot be used as `[JsonSerializable]` only supports being applied to classes.

### Reproduction Steps

To reproduce run `dotnet build` using the .NET 6.0.100 SDK for the below application.

```csharp
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace MyApp
{
    public static class Program
    {
        public static void Main()
        {
            var value = new MyGarageApp.Car { Color = MyGarageApp.Color.FerrariRed };
            var bytes = JsonSerializer.SerializeToUtf8Bytes(value, typeof(MyGarageApp.Car), new MyJsonContext(new(JsonSerializerDefaults.Web)));
            var json = Encoding.UTF8.GetString(bytes);

            Console.WriteLine(json);
        }
    }

    [JsonSerializable(typeof(MyGarageApp.Car))]
    [JsonSerializable(typeof(MyHangerApp.Aircraft))]
    public partial class MyJsonContext : JsonSerializerContext
    {
    }
}

namespace MyGarageApp
{
    /*
     * CS0592	Attribute 'JsonSerializable' is not valid on this declaration type. It is only valid on 'class' declarations.
    [JsonSerializable(typeof(Color), TypeInfoPropertyName = "CarColor")]
    */
    public enum Color
    {
        FerrariRed,
        RacingGreen,
    }

    public class Car
    {
        public Color Color { get; set; }
    }
}

namespace MyHangerApp
{
    /*
     * CS0592	Attribute 'JsonSerializable' is not valid on this declaration type. It is only valid on 'class' declarations.
    [JsonSerializable(typeof(Color), TypeInfoPropertyName = "AircraftColor")]
    */
    public enum Color
    {
        RedArrowsRed,
        BlueAngelsBlue,
    }

    public class Aircraft
    {
        public Color Color { get; set; }
    }
}
```

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <NoWarn>$(NoWarn);CA1050</NoWarn>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
</Project>
```

### Expected behavior

The application compiles successfully.

### Actual behavior

The application fails to compile with a `CS1503` error.

```sh
> dotnet build
Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
CSC : warning SYSLIB1031: There are multiple types named Color. Source was generated for the first one detected. Use 'JsonSerializableAttribute.TypeInfoPropertyName' to resolve this collision. [C:\Coding\martincostello\JsonSourceGeneratorObsoleteProperties\JsonSourceGeneratorObsoleteProperties.csproj]
C:\Coding\martincostello\JsonSourceGeneratorObsoleteProperties\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\MyJsonContext.Aircraft.g.cs(80,63): error CS1503: Argument 1: cannot convert from 'System.Text.Json.Utf8JsonWriter' to 'System.IO.Stream' [C:\Coding\martincostello\JsonSourceGeneratorObsoleteProperties\JsonSourceGeneratorObsoleteProperties.csproj]
C:\Coding\martincostello\JsonSourceGeneratorObsoleteProperties\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\MyJsonContext.Aircraft.g.cs(80,84): error CS1503: Argument 3: cannot convert from 'System.Text.Json.Serialization.Metadata.JsonTypeInfo<MyGarageApp.Color>' to 'System.Type' [C:\Coding\martincostello\JsonSourceGeneratorObsoleteProperties\JsonSourceGeneratorObsoleteProperties.csproj]

Build FAILED.

CSC : warning SYSLIB1031: There are multiple types named Color. Source was generated for the first one detected. Use 'JsonSerializableAttribute.TypeInfoPropertyName' to resolve this collision. [C:\Coding\martincostello\JsonSourceGeneratorObsoleteProperties\JsonSourceGeneratorObsoleteProperties.csproj]
C:\Coding\martincostello\JsonSourceGeneratorObsoleteProperties\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\MyJsonContext.Aircraft.g.cs(80,63): error CS1503: Argument 1: cannot convert from 'System.Text.Json.Utf8JsonWriter' to 'System.IO.Stream' [C:\Coding\martincostello\JsonSourceGeneratorObsoleteProperties\JsonSourceGeneratorObsoleteProperties.csproj]
C:\Coding\martincostello\JsonSourceGeneratorObsoleteProperties\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\MyJsonContext.Aircraft.g.cs(80,84): error CS1503: Argument 3: cannot convert from 'System.Text.Json.Serialization.Metadata.JsonTypeInfo<MyGarageApp.Color>' to 'System.Type' [C:\Coding\martincostello\JsonSourceGeneratorObsoleteProperties\JsonSourceGeneratorObsoleteProperties.csproj]
    1 Warning(s)
    2 Error(s)

Time Elapsed 00:00:00.80
```

### Regression?

No.

### Configuration

Partial output from `dotnet --info`:

```sh
> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa
```

**Comment by eiriktsarpalis** [comment] 2021-11-26 15:13
Duplicate of #58938. It should be possible to work around the issue by setting a custom property name in the `TypeInfoPropertyName` parameter of `JsonSerializable`.

**Closed by eiriktsarpalis** 2021-11-26 15:13 UTC
Labels: area-System.Text.Json, untriaged
