### ISSUE TITLE
System.IO.Packaging.Open throws FileFormatException saying File contains corrupted data when the size of the package is more than 4GB and targeting .NET Framework

### ISSUE THREAD

**Issue by SeenaAugusty** [dotnet/runtime#94899] opened 2023-11-17 07:42 UTC
### Description

Our DacFx code uses System.IO.Packaging for packing the schema and when it is packaged with more than 4GB, it throw FileFormat Exception saying File contains corrupted data when it is used in a console app targeting .NET Framework but the same package loads fine in .NET Core

File contains corrupted data. 

Program Location:

```
at MS.Internal.IO.Zip.ZipIOLocalFileBlock.Validate(String fileName, ZipIOCentralDirectoryBlock centralDir, ZipIOCentralDirectoryFileHeader centralDirFileHeader)
at MS.Internal.IO.Zip.ZipIOLocalFileBlock.ParseRecord(BinaryReader reader, String fileName, Int64 position, ZipIOCentralDirectoryBlock centralDir, ZipIOCentralDirectoryFileHeader centralDirFileHeader)
at MS.Internal.IO.Zip.ZipIOLocalFileBlock.SeekableLoad(ZipIOBlockManager blockManager, String fileName)
at MS.Internal.IO.Zip.ZipIOBlockManager.LoadLocalFileBlock(String zipFileName)
at MS.Internal.IO.Zip.ZipArchive.GetFile(String zipFileName)
at MS.Internal.IO.Zip.ZipArchive.GetFiles()
at System.IO.Packaging.ZipPackage.ContentTypeHelper..ctor(ZipArchive zipArchive, IgnoredItemHelper ignoredItemHelper)
at System.IO.Packaging.ZipPackage..ctor(String path, FileMode mode, FileAccess access, FileShare share, Boolean streaming)
at System.IO.Packaging.Package.Open(String path, FileMode packageMode, FileAccess packageAccess, FileShare packageShare, Boolean streaming)
at Microsoft.Data.Tools.Schema.Sql.Build.SqlPackage.Artifact.InitializefromFile(FileInfo fileInfo, FileMode mode, FileAccess access)
```

### Reproduction Steps

1. Create a console app targeting **.NET core** and package a file of size greater than 4 or 6GB using System.IO.Packaging library
2. Create another console app targeting **.NET framework** and try to open the package created in step 1 using System.IO.Packaging library, it would throw File Format Exception.

### Expected behavior

It should open the package in the console app targeting .Net Framework

### Actual behavior

It throws File Format exception saying File contains corrupted data when it works fine in the console app targeting .NET core

### Known Workarounds

Open the package in the console app targeting .NET Core

### Other information

It has been reported here in https://github.com/dotnet/wpf/issues/2676 and because of this issue, we have an issue opened in DacFx https://github.com/microsoft/DacFx/issues/363

**Comment by zijchen** [comment] 2023-11-17 19:04
We can repro this with version 5.0.0 but it's possible the issue was in prior versions too

**Comment by karakasa** [comment] 2023-11-19 04:46
the bug occurs because `VersionNeededToExtract` (20) in the local file block is different from that in the central directory file header (45). I'm unsure if it's allowed.

**Comment by karakasa** [comment] 2023-11-19 05:54
The required version for unzipping is different in the local header (20, Deflate) compared to that in central directory (45, ZIP64).

The underlying reason is that all small files after large files (>4GB) requires ZIP64 header because their file offsets are >4GB. `ZipArchiveEntry.WriteCentralDirectoryFileHeader()` catches that so CD is correct, however LHs are unaware of the offset issue when created in `ZipArchiveEntry.WriteCrcAndSizesInLocalHeader()` so versions in LH is 20.

I'm unsure whether the discrepancy is allowed by the spec but it seems the latest .NET doesn't validate that as the Framework used to do. If allowed, the bug can only be fixed from the Framework side because the issue is within `WindowsBase.dll`.

**Comment by pwoosam** [comment] 2023-11-23 00:16
@karakasa, My understanding is that the central directory headers must match the local file headers.
[Reference to APPNOTE-6.3.10.TXT on pkware.cachefly.net](https://pkware.cachefly.net/webdocs/APPNOTE/APPNOTE-6.3.10.TXT)

The central directory header is intended to provide a quick lookup of all zip file metadata without needing to scan the entire file. It should contain identical data to the local file header. Mismatched headers may indicate corruption and is invalid.

Multiple compression methods in the spec also specify the expectation that the compression bytes will match in both the central directory headers and local file headers.

![image](https://github.com/dotnet/runtime/assets/18713517/8a5d5b90-c719-4b01-8e5d-0a5905004cc9)
![image](https://github.com/dotnet/runtime/assets/18713517/353841ae-ad90-47fb-b8f2-a7fd480d7e2a)
![image](https://github.com/dotnet/runtime/assets/18713517/191cf4b1-ada7-4b01-9584-37693308a419)
![image](https://github.com/dotnet/runtime/assets/18713517/78fe000f-bf0c-4c83-919b-a8b2dc19417a)

**Comment by SeenaAugusty** [comment] 2024-02-01 07:50
@karakasa I was wondering if this fixed in net8?

**Comment by carlossanlop** [comment] 2024-03-19 22:16
@SeenaAugusty not yet but we will backport it to 8.0 once the fix is merged.

**Comment by llali** [comment] 2024-03-22 17:12
@carlossanlop do you have any ETA on when this fix will be ported to 8.0? in which sdk version?

**Comment by carlossanlop** [comment] 2024-03-22 17:14
We need to merge the fix to main first, then we can backport it and have it included in the upcoming release at that point.

**Comment by ssreerama** [comment] 2024-04-19 03:37
@carlossanlop, does the error "**The archive entry was compressed using an unsupported compression method**" related to the System.IO.Packaging? we get this error in one of the scenarios where customer is exporting bacpac in LINUX server and trying to import on Windows. I see couple of issues created here https://github.com/dotnet/runtime/issues/82015 and https://github.com/dotnet/runtime/issues/409. Do you have any workaround for the issue?

**Comment by pwoosam** [comment] 2024-04-19 04:13
@ssreerama I'm not 100% sure this is the same error, but it sounds related. If it's the same error, then the workaround would be to use .Net Framework versions of the tools you're using to export the bacpac. You may need to perform the export on a Windows machine.

You can use the .Net Framework version of SqlPackage to export a bacpac. You can install the .Net Framework version of SqlPackage using the .msi installer from https://learn.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-download?view=sql-server-ver16

**Comment by llali** [comment] 2024-05-08 20:45
@pwoosam I believe this is a different bug. still might be related to the header of the file but different issue. we don't have a workaround for this since using .NetFrameowork version fails with the "corrupted data" error. I think this is the place that's happening https://github.com/dotnet/runtime/blob/cdef0ddb652258bd627bcad560a6cf4f73629091/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/Inflater.cs#L315

**Closed** 2024-05-31 20:42 UTC
Labels: area-System.IO.Compression, in-pr
