### ISSUE TITLE
System.Text.Json.SourceGeneration can't generate code correctly with a conflict classname

### ISSUE THREAD

**Issue by DCTewi** [dotnet/runtime#106230] opened 2024-08-10 16:31 UTC
### Description

When you try to serialize any class named `Options`, the source generator will be broken because of class `JsonSerializerContext` has a public property named `Options`, too.

It will cause `CS1061`: 'JsonTypeInfo<Options>' does not contain a definition for 'GetTypeInfo' and no accessible extension method 'GetTypeInfo' accepting a first argument of type 'JsonTypeInfo<Options>' could be found.

### Reproduction Steps

It's easy to reproduction in a single file:

```csharp
using System.Text.Json;
using System.Text.Json.Serialization;

namespace SourceGenerationBug
{
    internal class Options
    {
        public int MyProperty { get; set; }
    }

    [JsonSerializable(typeof(Options))]
    internal partial class JsonSourceGenerationContext : JsonSerializerContext { }

    internal class Program
    {
        static void Main(string[] args)
        {
            Options options = new() { MyProperty = 1 };

            var resultJson = JsonSerializer.Serialize(
                options!, JsonSourceGenerationContext.Default.Options);

            Console.WriteLine(resultJson);
        }
    }
}

```

### Expected behavior

The generator should use `base.Options` or `(this as JsonSerializerContext).Options` to access property `Options` correctly from base class `JsonSerializerContext`.

### Actual behavior

Actual generated code is like below:

```csharp
/// <summary>
/// Defines the source generated JSON serialization contract metadata for a given type.
/// </summary>
public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::SourceGenerationBug.Options> Options
{
    get => _Options ??= (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::SourceGenerationBug.Options>)Options.GetTypeInfo(typeof(global::SourceGenerationBug.Options));
}
```

with Options.GetTypeInfo is ambiguous.

### Known Workarounds

It seems that the only way to avoid this problem is by not naming any class ‘Options’ when you want serialize it.

### Configuration

.NET SDK:
 - Version:           8.0.303
 - Commit:            29ab8e3268
 - Workload version:  8.0.300-manifests.34944930
 - MSBuild version:   17.10.4+10fbfbf2e

OS Name:     Windows
OS Version:  10.0.22631
OS Platform: Windows
RID:         win-x64

Host:
 - Version:      8.0.7
 - Architecture: x64
 - Commit:       2aade6beb0

### Other information

I think the key to solving this bug is

https://github.com/dotnet/runtime/blob/8fee24fbde0882fd83b68042747b210001c8ab33/src/libraries/System.Text.Json/gen/JsonSourceGenerator.Emitter.cs#L1081

and

https://github.com/dotnet/runtime/blob/8fee24fbde0882fd83b68042747b210001c8ab33/src/libraries/System.Text.Json/gen/JsonSourceGenerator.Emitter.cs#L1367

`{{OptionsInstanceVariableName}}` should be replaced with `base.{{OptionsInstanceVariableName}}`.

However, I’m not sure if this is robust enough.

**Comment by JakeYallop** [comment] 2024-08-10 16:58
The `JsonSerializableAttribute` has a `TypeInfoPropertyName` property that can be used to tell the source generator the name to use for the type info property, in order to avoid name conflicts.

```csharp
[JsonSerializable(typeof(Options), TypeInfoPropertyName = "MyOptions")]
internal partial class JsonSourceGenerationContext : JsonSerializerContext { }
```

**Comment by eiriktsarpalis** [comment] 2024-08-10 21:02
Duplicate of #71547. Naming conflicts should be handled manually using the `JsonSerializableAttribute .TypeInfoPropertyName` property.

**Closed by eiriktsarpalis** 2024-08-10 21:02 UTC
Labels: area-System.Text.Json, untriaged
