### ISSUE TITLE
NullReferenceException when you use the short format of string.format $"{sample}" when debugging .NET 7 on x64 macOS

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#78991] opened 2022-11-29 20:00 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NullReferenceException-when-you-use-the-/10205413)._

---
[severity:I'm unable to use this version] [regression] [worked-in:net 6]
When you use the short format $"{sample}" to concatenate/format a string with variables you get this if is inside a try/catch

I have this piece of code:

```
[Fact]
public void NullReferenceException()
{
    var cname = "component";
    var callerName = "caller";
    var message = "message";

    string text = null;
    string textFormat = null;
    string textNRE = null;

    textNRE = $"{cname}.{callerName}: {message}"; // this works fine ;0

    try
    {
        text = cname + "." + callerName + ": " + message;
        textFormat = string.Format("{0}.{1}: {2}", cname, callerName, message);
        textNRE = $"{cname}.{callerName}: {message}"; // this throws the NullReferenceException
    }
    catch (Exception exp)
    { }
}
```
The given exception message is:
>Object reference not set to an instance of an object.

Stack trace: 
>   at System.Buffer.Memmove(Byte& dest, Byte& src, UIntPtr len)
   at System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted(String value)
   at framework.POCs.NullReferenceException() in /Users/jmrpineda/Projects/GitHub/PinedaTec.eu/InGameServices/arn/arn.test/framework/POCs.cs:line 63

I marked this issue as stopper due I have a lot of lines using this try/catch and short string format

If you need additional info, please ask me

thanks, regards

---
#### Feedback Bot on 11/17/2022, 06:08 PM: 

(private comment, text removed)
#### Josema R. Pineda on 11/17/2022, 11:15 PM: 

(private comment, text removed)
#### Josema R. Pineda on 11/18/2022, 00:13 AM: 

(private comment, text removed)
#### Feedback Bot on 11/29/2022, 08:59 AM: 

(private comment, text removed)
#### Feedback Bot on 11/29/2022, 11:48 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jmrpineda** [comment] 2022-11-29 23:33
Additional info:

Visual Studio for Mac preview 17.5 Preview (17.5 build 437)

macOS: Ventura 13.0.1 (22A400)

Project info:
```
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
		<IsPackable>false</IsPackable>
		<ReleaseVersion>0.0.5.4</ReleaseVersion>
	</PropertyGroup>
	<ItemGroup>
```

If you downgrade the target framework to net 6.0, the test works fine.

**Comment by MichalPetryka** [comment] 2022-11-29 23:47
Is this on an x64 or ARM64 Mac?

**Comment by jmrpineda** [comment] 2022-11-30 04:44
> Is this on an x64 or ARM64 Mac?

x64,
Intel Core i9

**Comment by danmoseley** [comment] 2022-12-08 13:53
@mkrivacek Can you provide minimal repro code that compiles?

**Comment by Code-DJ** [comment] 2022-12-08 17:08
I have the same issue. It has something to do with Threading on macOS.

@danmoseley Here's a simple console app:

The interpolation with ToString() works fine, the ones without crashes with the error mentioned above. When you run the same code outside a thread, it works fine.

```
using System.Collections.Concurrent;

BlockingCollection<int> Queue = new();

void ProcessQueue()
{
    foreach (var item in Queue.GetConsumingEnumerable())
    {
        var number = 100;

        Console.WriteLine($"{DateTime.Now.ToString()}");
        Console.WriteLine($"{number.ToString()}");

        Console.WriteLine($"{DateTime.Now}");
        Console.WriteLine($"{number}");
    }
}

var t = new Thread(ProcessQueue);
t.Start();

Queue.Add(0);

t.Join();
```

**Comment by danmoseley** [comment] 2022-12-08 17:11
@stephentoub

**Comment by Code-DJ** [comment] 2022-12-08 20:17
For me it only happens when debugging.

Works fine with both debug and release builds:
```
dotnet build
cd bin/Debug/net7.0
dotnet Test.dll

dotnet build -c Release
cd bin/Release/net7.0
dotnet Test.dll
```

**Comment by danmoseley** [comment] 2022-12-08 22:19
@jmrpineda  @mkrivacek does this only happen for you both during debugging as well? If so I think we would send this to the debugging area.

**Comment by jmrpineda** [comment] 2022-12-08 22:21
I will check it the next week, I am far away now, sorry ;(

**Comment by jmrpineda** [comment] 2022-12-08 22:43
> @jmrpineda @mkrivacek does this only happen for you both during debugging as well? If so I think we would send this to the debugging area.

I just do a remote connection,
Only when you are debugging the issue appears

**Comment by danmoseley** [comment] 2022-12-09 03:19
@stephentoub  should we move to diagnostics team?

**Comment by lmilskiddev** [comment] 2022-12-09 14:45
Similar issue here.

Mac OS 12.6.1 Intel Core i7
dotnet 7.0.100
Using VS Code or Visual Studio  for Mac 17.4.1 (build 28)

**Comment by stephentoub** [comment] 2022-12-09 14:46
@lmilskiddev, also only when debugging?

**Comment by lmilskiddev** [comment] 2022-12-09 15:02
> Yes and here are some other observations.
This line failed
AppLog.LogInfo($"cjevent Host {domain} '{cjEventData}'");
Change it to this and it stopped failing
AppLog.LogInfo($"cjevent Host {domain} {cjEventData}");

I have also seen where the behavior changes based on if the debugger is at a break and you step through code. Some (but not all) of my $" lines only fail when stepping through code.

> @lmilskiddev, also only when debugging?

**Comment by hoyosjs** [comment] 2022-12-14 01:18
I've been trying to repro this against 7.0.1 on a Ventura m1. Neither of the programs seem to repro this for me.

**Comment by danmoseley** [comment] 2022-12-14 02:14
hmm -- I assume you're using release bits, @hoyosjs ?

I'm guessing you have 13.0.1 as well, as some folks above do.

**Comment by lmilskiddev** [comment] 2022-12-14 02:24
I have
Mac OS 12.6.1 Intel Core i7 x64
dotnet 7.0.100
Using VS Code or Visual Studio for Mac 17.4.1 (build 28)

My coworker in on M1 Ventura and he is not having any problems.

**Comment by Code-DJ** [comment] 2022-12-14 03:39
Intel Inside.

**Comment by hoyosjs** [comment] 2022-12-14 08:00
@dotnet/dotnet-diag does anyone have an x64 macOS device we can use to diagnose this?

**Comment by jmrpineda** [comment] 2022-12-14 08:02
> @dotnet/dotnet-diag does anyone have an x64 macOS device we can use to diagnose this?

What do you need? give us the steps like for a dummy ;)

**Comment by ysbakker** [comment] 2022-12-28 10:07
Just ran into this as well - let me know if I can help with the diagnosis.

**Comment by jmrpineda** [comment] 2022-12-28 10:52
> Just ran into this as well - let me know if I can help with the diagnosis.

This issue was reported by me, I was asking if I could test anything else

**Comment by a7medpa** [comment] 2023-01-08 01:58
I am having the same issue.
Processor: 2.8 GHz Quad-Core Intel Core i7
MacOS: Ventura 13.1
Visual Studio Version: 17.4.2 (build 17)

When can we expect a fix?

**Comment by steven-r** [comment] 2023-01-29 12:11
@tommcdon: MS 8.0.0 (Plan: November 23)? This implies buggy debugging until November?

**Comment by pajacz** [comment] 2023-01-29 12:14
Hmm.. not good.. for all of us on MacOs :(

**Comment by tommcdon** [comment] 2023-01-29 15:02
> MS 8.0.0 (Plan: November 23)? This implies buggy debugging until November?

Our team's workflow is to first address the active issue in the active development branch which is currently "main".  All fixes/features in main will ship with 8.0.  Once we have a fix, for issues that are impacting customers in existing .NET Core releases, our workflow is to take this issue to the .NET servicing team to backport to the requested servicing release(s).   So the milestone date does not necessarily correspond to the first release to customers as we have the ability to backport the changes to servicing (once the fix is available).  This issue is on our team's backlog and we plan on investigating this up after our existing/assigned work is completed.

**Comment by bc3** [comment] 2023-03-14 10:43
same issue here:

macbook pro 2019
2,4 GHz 8-Core Intel Core i9
64 GB 2667 MHz DDR4
.NET 7

using a regular string interpolation fails during debugging

```
] NullReferenceException - Object reference not set to an instance of an object. - at System.Buffer.Memmove(Byte& dest, Byte& src, UIntPtr len)
 at System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted(String value)
```

I had to replace it with a string.format : `$"{streetName} {request?.Number} {request?.Box}, {city?.Zip} {city?.Name}"`

```
 var address = string.Format("{0} {1} {2}, {3} {4}", streetName, request?.Number, request?.Box,
                    city?.Zip, city?.Name);
```

euuueeueuuehehehe WHAT !!!
i strongly sugges fix it ASAP, we can't tell our management to wait for more than half a year t use normal code

**Comment by co0ke** [comment] 2023-03-20 11:38
Just encountered this issue too. Is there any more information on a fix date? This is a huge blocker.

MacBook Pro 2020
macOS Monterey 12.5
2 GHz Quad-Core Intel Core i5
.NET 7

**Comment by hghansen** [comment] 2023-03-20 12:18
I have experienced that a possible workaround is to set a new breakpoint below the code-line with string interpolation, and run to it instead of stepping over it.

**Comment by RachelAmbler** [comment] 2023-04-19 19:56
Also getting it here. Oddly _some_ strings work OK!

```cs
try
{
    var a = "a";
    var b = "b";
    var r1 = "r";
    var r1x = $"r2x1={a}.{b}.{r1}";  // < Line 6 - F10 here will give you an exception
    var r1y = $"r2x1={a}.{b}" + r1;  // < Line 7 - F10 here will execute just fine
    var r1z = $"r2x1={a}.{b}." + r1; // < Line 8 - F10 here will give you an exception - even though the only difference is a trailing period
    var r1a = $"r2x1={a}.{b}{r1}";   // < Line 9 - F10 here will give you an exception
    Console.WriteLine(r1x);
    
}
catch (NullReferenceException e)
{
    Console.WriteLine(e);
}
```

**Comment by alexbaker2002** [comment] 2023-04-20 13:53
> I have experienced that a possible workaround is to set a new breakpoint below the code-line with string interpolation, and run to it instead of stepping over it.

This worked for me. Thanks!

**Comment by hoyosjs** [comment] 2023-04-21 22:19
That last example expands to:

```c#
string text = "a";
string text2 = "b";
string text3 = "r";
DefaultInterpolatedStringHandler defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(7, 3);
defaultInterpolatedStringHandler.AppendLiteral("r2x1=");
defaultInterpolatedStringHandler.AppendFormatted(text);
defaultInterpolatedStringHandler.AppendLiteral(".");
defaultInterpolatedStringHandler.AppendFormatted(text2);
defaultInterpolatedStringHandler.AppendLiteral(".");
defaultInterpolatedStringHandler.AppendFormatted(text3);
string value = defaultInterpolatedStringHandler.ToStringAndClear();
string[] array = new string[5];
array[0] = "r2x1=";
array[1] = text;
array[2] = ".";
array[3] = text2;
array[4] = text3;
string text4 = string.Concat(array);
defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(7, 2);
defaultInterpolatedStringHandler.AppendLiteral("r2x1=");
defaultInterpolatedStringHandler.AppendFormatted(text);
defaultInterpolatedStringHandler.AppendLiteral(".");
defaultInterpolatedStringHandler.AppendFormatted(text2);
defaultInterpolatedStringHandler.AppendLiteral(".");
string text5 = string.Concat(defaultInterpolatedStringHandler.ToStringAndClear(), text3);
defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(6, 3);
defaultInterpolatedStringHandler.AppendLiteral("r2x1=");
defaultInterpolatedStringHandler.AppendFormatted(text);
defaultInterpolatedStringHandler.AppendLiteral(".");
defaultInterpolatedStringHandler.AppendFormatted(text2);
defaultInterpolatedStringHandler.AppendFormatted(text3);
string text6 = defaultInterpolatedStringHandler.ToStringAndClear();
Console.WriteLine(value);
```

Line 7 is fine because of the array and not using the `DefaultInterpolatedStringHandler`.

The crash stack is:

```
System.Private.CoreLib.dll!System.Buffer.Memmove(ref byte dest, ref byte src, System.UIntPtr len) Line 214 (Buffer.cs:214)
System.Private.CoreLib.dll!System.Buffer.Memmove<char>(ref char destination, ref char source, System.UIntPtr elementCount) Line 117 (Buffer.CoreCLR.cs:117)
System.Private.CoreLib.dll!string.TryCopyTo(System.Span<char> destination) Line 440 (String.cs:440)
System.Private.CoreLib.dll!System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendStringDirect(string value) Line 195 (DefaultInterpolatedStringHandler.cs:195)
System.Private.CoreLib.dll!System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendLiteral(string value) Line 188 (DefaultInterpolatedStringHandler.cs:188)
stringInterpolation.dll!Program.<Main>$(string[] args) Line 6 (/Users/juhoyosa/mocks/stringInterpolation/Program.cs:6)
[Native to Managed Transition] (Unknown Source:0)
```

**Comment by hoyosjs** [comment] 2023-05-05 22:36
Looking at this some more it's a bit of an issue between the JIT emitted code and what the debugger believes the `this` pointer is for the `DefaultInterpolatedStringHandler` is (probably construct this relative to an instrumented method body, but still need to investigate more - but that's likely since it's a ref struct). We end up calling memmove on a null pointer for the `Span<char>` in the `DefaultInterpolatedStringHandler`. A workaround for this while we figure if a fix that's easy to backport is to set `DOTNET_EnableAVX=0` in the environment setting before launching the app to be debugged.

**Comment by VictorHaine** [comment] 2023-05-29 16:27
Thanks @hoyosjs, adding `DOTNET_EnableAVX=0` resolves debugging exceptions with Rider as well 👍

**Comment by danmoseley** [comment] 2023-05-29 17:05
Unrelated to the exception - @stephentoub   I'm curious why one of the examples above just uses String.Join. Some heuristic I assume? It's not clear to me why it does in that particular case.

**Comment by stephentoub** [comment] 2023-05-29 20:21
> Unrelated to the exception - @stephentoub I'm curious why one of the examples above just uses String.Join. Some heuristic I assume? It's not clear to me why it does in that particular case.

What are you referring to?

**Comment by drieseng** [comment] 2023-05-29 21:16
@stephentoub, perhaps @danmoseley was talking about `String.Concat`. I recently noticed this myself and did I quick benchmark:

<details>
<summary>Benchmark code</summary>

```c#
using BenchmarkDotNet.Attributes;

public class InterpolationBenchmarks
{
    [Benchmark]
    public string Interpolation_4()
    {
        return $"1{Environment.NewLine}" +
               $"2{Environment.NewLine}" +
               $"3{Environment.NewLine}" +
               $"4{Environment.NewLine}";
    }

    [Benchmark]
    public string Interpolation_5()
    {
        return $"1{Environment.NewLine}" +
               $"2{Environment.NewLine}" +
               $"3{Environment.NewLine}" +
               $"4{Environment.NewLine}" +
               $"5{Environment.NewLine}";
    }
}
```
</details>

<details>
<summary>Expanded code</summary>

```
public string Interpolation_4()
{
    string[] array = new string[8];
    array[0] = "1";
    array[1] = Environment.NewLine;
    array[2] = "2";
    array[3] = Environment.NewLine;
    array[4] = "3";
    array[5] = Environment.NewLine;
    array[6] = "4";
    array[7] = Environment.NewLine;
    return string.Concat(array);
}

public string Interpolation_5()
{
    DefaultInterpolatedStringHandler defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(5, 5);
    defaultInterpolatedStringHandler.AppendLiteral("1");
    defaultInterpolatedStringHandler.AppendFormatted(Environment.NewLine);
    defaultInterpolatedStringHandler.AppendLiteral("2");
    defaultInterpolatedStringHandler.AppendFormatted(Environment.NewLine);
    defaultInterpolatedStringHandler.AppendLiteral("3");
    defaultInterpolatedStringHandler.AppendFormatted(Environment.NewLine);
    defaultInterpolatedStringHandler.AppendLiteral("4");
    defaultInterpolatedStringHandler.AppendFormatted(Environment.NewLine);
    defaultInterpolatedStringHandler.AppendLiteral("5");
    defaultInterpolatedStringHandler.AppendFormatted(Environment.NewLine);
    return defaultInterpolatedStringHandler.ToStringAndClear();
}
```
</details>

For the **4** version, Roslyn generates the `String.Concat` flavor while the **5** version uses **DefaultInterpolatedStringHandler**.

The **5** version is both faster and allocates less:

```
|          Method |      Mean |    Error |   StdDev |   Gen0 | Allocated |
|---------------- |----------:|---------:|---------:|-------:|----------:|
| Interpolation_4 |  66.44 ns | 0.249 ns | 0.194 ns | 0.0324 |     136 B |
| Interpolation_5 |  51.39 ns | 0.511 ns | 0.478 ns | 0.0134 |      56 B |
```

I'm sure there are good reasons for the current heuristics though.

**Comment by stephentoub** [comment] 2023-05-29 21:29
> For the 4 version, Roslyn generates the String.Concat flavor while the 5 version uses DefaultInterpolatedStringHandler.

@333fred, this looks like a Roslyn bug.  I thought we were only going to use string.Concat when it wouldn't result in a string[], i.e. when there were at most four strings? Four holes != four strings, of course.

**Comment by danmoseley** [comment] 2023-05-29 23:42
> perhaps @danmoseley was talking about String.Concat

indeed, thank you.

**Comment by 333fred** [comment] 2023-06-12 20:44
> @333fred, this looks like a Roslyn bug. I thought we were only going to use string.Concat when it wouldn't result in a string[], i.e. when there were at most four strings? Four holes != four strings, of course.

It's to do with the `+ notAString` part. That turns off interpolated string optimizations, because it's now an interpolated string plus "thing that is not an interpolated string". If you try `var r1y = $"r2x1={a}.{b}{r1}";`, you'll see the IL is using `DefaultInterpolatedStringHandler` as you might have expected. There are some potential opportunities that roslyn could take around optimizing this scenario further, but we don't currently.

**Comment by danmoseley** [comment] 2023-06-12 20:49
@333fred are you referring to @drieseng example here https://github.com/dotnet/runtime/issues/78991#issuecomment-1567524054 ?
the 4 and 5 versions seem to have an identical pattern, but 4 doesn't use the interpolation. there's no 'notastring'

**Comment by danmoseley** [comment] 2023-06-12 21:25
Will you open - could you link it?

**Comment by 333fred** [comment] 2023-06-12 21:43
I just opened a PR instead: https://github.com/dotnet/runtime/issues/78991#issuecomment-1567524054

**Comment by rmarinho** [comment] 2023-06-21 10:59
Is this going to be released on net7 service release ? if so what version of the sdk?

**Comment by c-ed** [comment] 2023-07-12 03:44
Still seeing this issue on macOS with the 7.0.9 that was released today.

**Comment by tommcdon** [comment] 2023-07-19 14:36
@c-ed @jchannon @rmarinho The referenced Roslyn fix addresses a performance problem related to string interpolation and string concatenation.  This issue is debugger specific and is under investigation.  Would you mind confirming that https://github.com/dotnet/runtime/issues/78991#issuecomment-1536857770 posted by @hoyosjs works around the issue?

**Comment by tommcdon** [comment] 2023-07-31 22:36
Moving to .NET 9 as we have confirmed `DOTNET_EnableAVX=0` works around the issue and this is a hard problem to solve in the time constraints for .NET 8.  We will continue investigating and once we have a fix, we will consider it for servicing.

**Comment by Nectivio** [comment] 2023-09-15 16:31
I also just ran into this issue. Works as expected if you run the app in debug or release, but put a breakpoint before the string interpolation and step over it and you'll get the exception.

Simple as possible reproduction steps:

Program.cs
```
const double pi = 3.141592653589793;
string message;
try
{
    message = $"The value of pi is {pi}";
}
catch (NullReferenceException)
{
    message = "What the heck?";
}
Console.WriteLine(message);
```

ConsoleApp.csproj
```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
</Project>
```

**Comment by tommcdon** [comment] 2023-09-15 16:35
Hi @Nectivio  thanks for the repro steps!  Please let us know if setting the `DOTNET_EnableAVX=0` environment variable does not workaround the issue.  Note if you are using VS Code, the env variable can be set in launch.json, please see https://code.visualstudio.com/docs/csharp/debugger-settings#_environment-variables for reference.

**Comment by Nectivio** [comment] 2023-09-15 16:56
@tommcdon Correct.  When debugging with both rider and vscode, it works as expected if I add `DOTNET_EnableAVX=0` to my environment variables.

**Comment by igblip** [comment] 2023-10-06 14:09
DOTNET_EnableAVX=0 
will also fix an issue with multiple return values from a function

**Comment by bunyadahmadli** [comment] 2023-12-18 20:14
I got the same error too. IDE: Jetbrains Rider  macOS : Sonoma 14.1.1 (22A400)  
with SDK 8.0, Runtime 8.0

**Comment by pajohns** [comment] 2024-01-25 06:56
I have the same error. Here is my class:

```csharp
var sender = new Sender
{
    FirstName = "Foo",
    LastName = "Bar",
    Email = "test@test.com"
}

Console.WriteLine($"{client.FirstName} {client.LastName}<{client.Email}>");
```

I'm getting a null reference exception when it hits this WriteLine. I've reverted to:

```csharp
Console.WriteLine(client.FirstName + " " + client.LastName + "<" + client.Email + ">");
```

which works fine.

**Closed** 2024-07-09 08:34 UTC
Labels: os-mac-os-x, arch-x64, area-Diagnostics-coreclr, hard-problem

**Comment by jchannon** [comment] 2024-07-09 10:20
@mikelle-rogers @janvorli will this be released in a new sdk release soon?

**Comment by mikelle-rogers** [comment] 2024-07-09 19:09
This fix should make it into the .NET 9 preview 7 release, which is set for August 13th.

**Comment by janvorli** [comment] 2024-07-09 19:35
It seems we would also want to backport it to 8.0.
