### ISSUE TITLE
[API Proposal]: System.DateOnly  should  Add Calculate the difference between two DateOnly  methods

### ISSUE THREAD

**Issue by winxp2002** [dotnet/runtime#109041] opened 2024-10-19 05:06 UTC
### Background and motivation

How Calculate the difference between two DateOnly ？

DateTime.Now   -  DateOnly
DateTimeOffset -  DateOnly  

2024-10-1  to  2023-12-23 

### API Proposal

```csharp
namespace System
{
    public class TimeOnly
    {
        public static TimeSpan  operator -(TimeOnly c1, TimeOnly c2);
    }
}
```

### API Usage

```csharp
using System;
DateOnly begin = new DateOnly(2023, 10, 1);
DateOnly end = new DateOnly(2023, 10, 31);

TimeSpan difference = end  - begin ;

 Console.WriteLine($" {end} - {begin}  = {t.TotalDays} (days)");
```

**Comment by Clockwork-Muse** [comment] 2024-10-19 07:21
For the equivalent information that the existing [`TimeSpan`](https://learn.microsoft.com/en-us/dotnet/api/system.timespan?view=net-8.0) type would give you, you can get the information via use of the `DayNumber` property and some trivial math:

```csharp
// Assuming start/end are DateOnly
var days = end.DayNumber - start.DayNumber;
```

... this is because `TimeSpan` only does **absolute** difference, as in days/minutes/seconds.

If instead you want **relative** time, duplicate of 
#54400
#72064

**Closed by Clockwork-Muse** 2024-10-19 07:21 UTC
Labels: api-suggestion, untriaged, area-System.DateTime
