### ISSUE TITLE
FTP Downloading Randomly Missing Bytes in .NET 6.0

### ISSUE THREAD

**Issue by adamjhilton** [dotnet/runtime#77232] opened 2022-10-19 20:32 UTC
### Description

I'm putting some FTP functionality into a MAUI app (Android/Windows Machine) that I'm working on to backup and restore the app's SQLite database. The upload works just fine. But the download only works maybe 1 time out of 5. I'm finding that a random number of bytes are 'missing' from the download. For example, if the database file is 2,179,072 bytes large, sometimes the downloaded file will only have 2,179,070 bytes, or 2,178,168 bytes, or 2,179,007 bytes, etc. It's completely random. I was initially thinking it was just an issue with the way the database get's written once it's downloaded, but the database becomes corrupted if it's missing pieces. 

But here's where it gets interesting: I tried the code in a separate WPF desktop application. The **exact same code** works perfectly fine in the full .NET Framework 4.7.2. It's just an issue with .NET Core 6.0.

### Reproduction Steps

Add this code to a test app and call TestFtpDownload(). You'll need credentials to an FTP server as I replaced my credentials with placeholders.

```cs
  public FtpsUtilities.FtpsCredentials MurrayFtpCredentials
  { get; } = new FtpsUtilities.FtpsCredentials($"{MurrayFtpAccount}@murraycontrolpro.com", MurrayFtpPassword);
  private static string ApplicationDatabasePath
  { get; } = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Personal), DatabaseFileName);
  private static string TempApplicationDatabasePath
  { get; } = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Personal), $"_{DatabaseFileName}");

  private const string MurrayFtpAccount = "ftpUsername";

  private const string MurrayFtpPassword = "ftpPassword";
  private const string FtpBackupFolder = "TestFolder01";

  private const string MurrayFtpHost = @"ftp://testftp.com";

  private const string MurrayFtpDatabaseFilesFolder = "DatabaseFiles";
  private const string DatabaseFileName = "database.db3";

  private void TestFtpDownload()
  {
   FileSpaceUtilities.DeleteFile(TempApplicationDatabasePath);
   string serverPath = FtpPathCombine(MurrayFtpHost, MurrayFtpDatabaseFilesFolder);
   serverPath = FtpPathCombine(serverPath, FtpBackupFolder);
   serverPath = FtpPathCombine(serverPath, DatabaseFileName);
   string message = DownloadFile2(serverPath, TempApplicationDatabasePath, false, MurrayFtpCredentials);
  }

  public static string FtpPathCombine(string serverPath, string file) => $"{serverPath}/{file}";

  public static string DownloadFile2(
   string serverPath,
   string localPath,
   bool deleteAfterDownload,
   FtpsCredentials credentials)
  {
   try
   {
    long fileSize = GetFileSize(serverPath, credentials);
    long bytesRead = 0;
    FtpWebRequest request = CreateRequest(serverPath, WebRequestMethods.Ftp.DownloadFile, credentials);
    using (FtpWebResponse response = (FtpWebResponse)request.GetResponse())
    using (Stream responseStream = response.GetResponseStream())
    using (FileStream fileStream = File.Create(localPath))
    {
     byte[] buffer = new byte[2048];
     while (true)
     {
      int read = responseStream.Read(buffer, 0, buffer.Length);
      if (read <= 0)
       break;
      bytesRead += read;
      fileStream.Write(buffer, 0, read);
     }
    }

    FileInfo fileInfo = new FileInfo(localPath);
    if (fileSize != bytesRead)
     return $"File size mismatch. FTP: {fileSize:n0}; local: {bytesRead:n0}";

    if (deleteAfterDownload)
     DeleteFile(serverPath, credentials);
   }
   catch (Exception e)
   {
    string message = e.GetInnerMessage();
    return message;
   }
   return null;
  }

  private static FtpWebRequest CreateRequest(string serverPath, string method, FtpsCredentials credentials)
  {
   FtpWebRequest request = (FtpWebRequest)WebRequest.Create(new Uri(serverPath));
   request.Credentials = new NetworkCredential(credentials.UserName, credentials.Password);
   request.UseBinary = true;
   request.UsePassive = true;
   request.Proxy = null;
   request.KeepAlive = true;
   request.Method = method;
   request.Timeout = RequestTimeOut;
   return request;
  }

  private static long GetFileSize(string serverPath, FtpsCredentials credentials)
  {
   long fileSize = -1;
   FtpWebRequest request = CreateRequest(serverPath, WebRequestMethods.Ftp.GetFileSize, credentials);
   using (FtpWebResponse response = (FtpWebResponse)request.GetResponse())
   {
    fileSize = response.ContentLength;
    response.Close();
   }
   return fileSize;
  }

  public class FtpsCredentials
  {
   public FtpsCredentials(string userName, string password)
   {
    UserName = userName;
    Password = password;
   }

   public string UserName;
   public string Password;
  }
```

### Expected behavior

The file downloads with all bytes. In other words, the size of the locally created file will match the size of the file on the FTP server exactly. 

### Actual behavior

When executed in an solution using .NET Framework 4.7.2, the file downloads correctly. When executed in a solution using .NET Core 6.0, bytes are missing. 

### Known Workarounds

Keep trying it until it works.

### Other information

MS devs can reach out to me and I'll provide FTP credentials to our FTP server if needed.

**Comment by adamjhilton** [comment] 2022-10-20 12:39
I have a workaround: make the buffer tiny. I set the buffer to byte[128] and this seems to work 9 times out of 10. There still a bug here, but this works in the interim.

**Comment by antonfirsov** [comment] 2022-10-20 16:22
Does this also fail with WPF + .NET 6 or only MAUI + .NET 6 (on Windows I assume)? Can you provide instructions to create a server setup that reproduces the issue? Do you see this happening with any server? It would be very hard to address this without a repro at our hands that also includes the server.

**Comment by adamjhilton** [comment] 2022-10-20 16:48
@antonfirsov 

I have not tried WPF + .NET 6. But I would assume that the behavior would be the same as the logic doesn't have any MAUI-specific code in the actual FTP download. The behavior is the same if I execute the code in an Android emulator running on Widows, side-loading the .APK onto an Android tablet, or compiling the code and running it on a 'Windows Machine'. 

As for your asks, I can create a quick repo with the code in it. I could also create a temporary login for our FTP server and stick a SQLite database file up there for you to download. Should I just link the repo here, or send you the link as it'll have FTP credentials in it?

Thanks!

**Comment by antonfirsov** [comment] 2022-10-20 17:36
> Should I just link the repo here, or send you the link as it'll have FTP credentials in it?

Better to share the repro here without the credentials, and share the credentials at some temporary location you can delete after my confirmation.

> I could also create a temporary login

This is good for us to confirm the repro, but it's unlikely the test login will be still available by the time we will actually address the issue, so it would be also important for us to know as much details about your server setup as possible.

**Comment by wfurt** [comment] 2022-10-20 17:39
It may be worth of checking if this is `Android` specific issue. e.g. does the code run fine on plain Linux or Windows?

**Comment by adamjhilton** [comment] 2022-10-20 20:11
I'm working on getting things put together. I evidently got this issue mixed up with a couple other bugs that I'm working through. So, I stand corrected on one thing: this is an **Android emulator** specific issue. FTP downloading works fine when installed on an Android device or when run as a Windows executable. Do I need to re-report this bug in a different forum?

**Comment by wfurt** [comment] 2022-10-21 00:33
any thoughts on this @simonrozsival ?

**Comment by adamjhilton** [comment] 2022-10-21 12:34
Alright, I have a repo with a couple of bugs that I'm submitting. 

https://github.com/adamjhilton/MauiBugs.git

Clicking the Download button will try to download a 2,179,072 byte 'registers.db3' file from a our FTP server using a temporary set of credentials. In an Android emulator, this will fail most of the time. Changing the buffer size to 128 will allow the download to succeed most of the time. I have two emulators that both have the same behavior:
* Pixel 2 XL - API 30 (Android 11.0 - API 30)
* Tablet M-DPI 10.1in - API 30 (Android 11.0 - API 30)

![image](https://user-images.githubusercontent.com/31253633/197194635-7d495d0b-4719-406b-9615-da2f957e30e1.png)

**Comment by simonrozsival** [comment] 2022-10-21 14:27
I can't reproduce it locally (my Android device running API 31 and an emulator running API 30). It always succeeds. And I can't think of a reason why this should skip a few bytes 🤔

**Comment by simonrozsival** [comment] 2022-10-21 14:36
@adamjhilton can you check that `fileInfo.Length == bytesRead != 2_179_072` when the problem occurs?

**Comment by adamjhilton** [comment] 2022-10-21 14:42
Okay, I still run into this on an API 32 emulator. Maybe it's a 'Me' issue somewhere? Aggravating...

**Comment by steveisok** [comment] 2023-07-12 16:46
@adamjhilton since we can't reproduce this on our end, I'm going to close the issue since it doesn't appear there's anything we can do.

**Closed by steveisok** 2023-07-12 16:46 UTC
Labels: area-System.Net, os-android, needs-further-triage
