### ISSUE TITLE
Documentation missing for CA1727 and CA1848 

### ISSUE THREAD

**Issue by flcdrg** [dotnet/runtime#62826] opened 2021-12-15 01:16 UTC
The analyzer(s) for these refer to the following links which both return 404 not found:

- https://docs.microsoft.com/en-au/dotnet/fundamentals/code-analysis/quality-rules/ca1848
- https://docs.microsoft.com/en-au/dotnet/fundamentals/code-analysis/quality-rules/ca1727

**Comment by timheuer** [comment] 2021-12-15 01:33
Tracked in https://github.com/dotnet/docs/issues/23900

**Comment by danmoseley** [comment] 2021-12-15 22:53
@flcdrg I will close this as a duplicate of that. BTW, if you are interested I know they would be glad to have a PR.

**Closed by danmoseley** 2021-12-15 22:53 UTC
Labels: untriaged
