### ISSUE TITLE
crash in the application

### ISSUE THREAD

**Issue by RamanSggs** [dotnet/runtime#70886] opened 2022-06-17 10:00 UTC
### Description

Our application is crashing randomly in production. While performing crash dump analysis we are getting below call stack repeatedly. 

_ed ntdll!RtlpCallVectoredHandlers
ee ntdll!RtlDispatchException
ef ntdll!KiUserExceptionDispatch
f0 coreclr!CExecutionEngine::GetTlsData
f1 coreclr!CExecutionEngine::CheckThreadStateNoCreate
f2 coreclr!SaveCurrentExceptionInfo
f3 coreclr!CLRVectoredExceptionHandlerShim

f4 ntdll!RtlpCallVectoredHandlers
f5 ntdll!RtlDispatchException
f6 ntdll!KiUserExceptionDispatch
f7 coreclr!CExecutionEngine::GetTlsData
f8 coreclr!CExecutionEngine::CheckThreadStateNoCreate
f9 coreclr!SaveCurrentExceptionInfo
fa coreclr!CLRVectoredExceptionHandlerShim_
.
.
.

ERROR_CODE: (NTSTATUS) 0xc0000005 

### Reproduction Steps

Not available

### Expected behavior

Application should not crash

### Actual behavior

Application crashing

**Comment by jkotas** [comment] 2022-06-17 12:15
This looks like a duplicate of https://github.com/dotnet/runtime/issues/12072 that was fixed for .NET Core 3.0.

What is the .NET runtime version that your application is running on? If it is earlier than .NET Core 3.1, could you please update to a newer version?

**Closed** 2022-08-10 00:02 UTC
Labels: area-ExceptionHandling-coreclr, no-recent-activity, needs-author-action
