### ISSUE TITLE
Dead code after switch over int64 influences result

### ISSUE THREAD

**Issue by s-a-c-h** [dotnet/runtime#68568] opened 2022-04-26 19:18 UTC
### Description

I attached two .il files, they are almost the same. In Switch0.il.txt the trailing dead code is commented out, in Switch4.il.txt it is not. The two programs have different results.

### Reproduction Steps

[Switch0.il.txt](https://github.com/dotnet/runtime/files/8566128/Switch0.il.txt)
$ ~/dotnet-bld/artifacts/bin/coreclr/Linux.x64.Release/ilasm -output:Switch0.exe Switch0.il.txt 

Microsoft (R) .NET IL Assembler.  Version 5.0.0
[...]
Operation completed successfully
$ ~/dotnet-bld/artifacts/bin/coreclr/Linux.x64.Release/corerun -c ~/dotnet-bld/.dotnet/shared/Microsoft.NETCore.App/5.0.0-rc.2.20475.5/ Switch0.exe
$ echo $?
0

[Switch4.il.txt](https://github.com/dotnet/runtime/files/8566129/Switch4.il.txt)
$ ~/dotnet-bld/artifacts/bin/coreclr/Linux.x64.Release/ilasm -output:Switch4.exe Switch4.il.txt 

Microsoft (R) .NET IL Assembler.  Version 5.0.0
[...]
Operation completed successfully
$ ~/dotnet-bld/artifacts/bin/coreclr/Linux.x64.Release/corerun -c ~/dotnet-bld/.dotnet/shared/Microsoft.NETCore.App/5.0.0-rc.2.20475.5/ Switch4.exe
$ echo $?
4

### Expected behavior

Both programs should return the same exitcode.

### Actual behavior

Switch0.exe returns 0, Switch4.exe returns 4.

### Configuration

$ cd ~/dotnet-bld/
$ git log                                                                                                         
commit cf258a14b70ad9069470a108f13765e0e5988f51 (HEAD, tag: v5.0.0-rtm.20519.4, tag: v5.0.0)
[...]
$ uname -a
Linux 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by SingleAccretion** [comment] 2022-04-26 19:24
Is the issues reproducible on 6.0/7.0 runtimes?

**Comment by s-a-c-h** [comment] 2022-04-26 19:26
Sorry, I haven't managed to build any newer runtimes (I'm building them from source because the Ubuntu package doesn't have ilasm included). 5.0 is the latest one.

**Comment by jakobbotsch** [comment] 2022-04-27 09:07
Looks like the problem is still there in latest main, although both switch0 and switch4 give the wrong result (4) when optimizations are turned on.

**Comment by jakobbotsch** [comment] 2022-04-27 09:38
I suppose the wrong result comes down to how the JIT handles switches on large integers. ECMA-335 is not super specific in its documentation of `switch`, but it looks like `switch` operates on natively sized integers. That would mean that the example should give different results on 32-bit and 64-bit machines since it is switching on `0x100000000`.

If that is the case then the issue is that we are discarding the upper half when we fold switches on constants here:
https://github.com/dotnet/runtime/blob/a077f271c3b5a8487f94111dc00a404a01fdc86b/src/coreclr/jit/morph.cpp#L15271

Note that C# always adds an `int32` cast when switching on a larger value, so we don't have that problem there.

cc @dotnet/jit-contrib

**Comment by AndyAyersMS** [comment] 2022-04-29 19:25
> ECMA-335 is not super specific 

In ECMA III.3.66 it seems pretty clear that values greater than 2^32 should only ever select the default:

> The switch instruction implements a jump table. The format of the instruction is an unsigned int32 representing the number of targets N ...  The switch instruction pops value off the stack and compares it, as an unsigned integer, to n

**Comment by jakobbotsch** [comment] 2022-04-29 20:21
> In ECMA III.3.66 it seems pretty clear that values greater than 2^32 should only ever select the default:

I.e. the JIT should be producing 64-bit operations for 8-byte integers? FWIW, in the JIT we currently BADCODE on 32-bit architectures if you try to switch on an 8 byte value.

**Comment by JulieLeeMSFT** [comment] 2022-05-05 20:28
@AndyAyersMS, because it is an undefined behavior, can we close this issue?

**Comment by jakobbotsch** [comment] 2022-05-05 20:30
I think we should fix things so we at least have consistent debug/release behavior. I can submit a PR.

**Comment by GSPP** [comment] 2022-05-16 07:51
ECMA seems pretty clear that switch operates on a uint32. What value is there in allowing anything else? Is compatibility a concern here? C# does not seem to ever produce this pattern, so it can only be manual IL generation.

From a debugging standpoint, it's usually best to be strict about inputs so that bugs can be detected quickly.

**Comment by jakobbotsch** [comment] 2022-05-16 08:11
> ECMA seems pretty clear that switch operates on a uint32.

It is not that clear to me. ECMA just says that the value is treated as an unsigned integer without bounding it to a 32-bit integer.

> Is compatibility a concern here?

Yes.

**Comment by jakobbotsch** [comment] 2022-05-16 08:24
I can see that we have several tests in the JIT that switch on native-sized integers, e.g. 
https://github.com/dotnet/runtime/blob/e22c63e2fa78931c6a4802e555370324c34475bd/src/tests/JIT/Methodical/ELEMENT_TYPE_IU/i_flow.il#L65
is one such switch. So I definitely do not think we should change behavior here, just fix our existing behavior.

**Closed** 2022-06-10 20:56 UTC
Labels: os-linux, arch-x64, area-CodeGen-coreclr, in-pr
