### ISSUE TITLE
System.DirectoryServices.AccountManagement - Invalid URI after upgrade to 9.0

### ISSUE THREAD

**Issue by maxima120** [dotnet/runtime#110400] opened 2024-12-04 15:40 UTC
### Description

I have stable WPF .NET 8 app. After upgrading System.DirectoryServices.AccountManagement from 8.0.1 to 9.0 I got this error:

`System.UriFormatException: 'Invalid URI: The hostname could not be parsed.'`

### Reproduction Steps

```
var ctx = new PrincipalContext(ContextType.Domain);
var usr = UserPrincipal.FindByIdentity(ctx, IdentityType.SamAccountName, "myname");
var test = usr.GetGroups();
```

### Expected behavior

no exception

### Actual behavior

exception

### Regression?

Worked for couple years now.

### Known Workarounds

Downgrade to 8.0.1 solves this immediately.

### Configuration

Windows 10 Enterprise with login via LDAP.

**Comment by steveharter** [comment] 2024-12-05 19:11
This is a duplicate of https://github.com/dotnet/runtime/pull/109977 which is fixed in v10 and being ported to 9.0.x.

**Closed by steveharter** 2024-12-05 19:11 UTC
Labels: area-System.DirectoryServices, untriaged
