### ISSUE TITLE
SendMoreThanStreamLimitRequestsConcurrently_LastWaits test fails with timeout

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#106597] opened 2024-08-18 19:44 UTC
```
    System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.SendMoreThanStreamLimitRequestsConcurrently_LastWaits(streamLimit: 1000) [FAIL]
      System.TimeoutException : The operation has timed out.
      Stack Trace:
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(55,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs(275,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.SendMoreThanStreamLimitRequestsConcurrently_LastWaits(Int32 streamLimit)
        --- End of stack trace from previous location ---
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=779538
Build error leg or test failing: System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.SendMoreThanStreamLimitRequestsConcurrently_LastWaits
Pull request: https://github.com/dotnet/runtime.git/pull/106589

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": ["System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.SendMoreThanStreamLimitRequestsConcurrently_LastWaits.*FAIL","System.TimeoutException . The operation has timed out.","at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.SendMoreThanStreamLimitRequestsConcurrently_LastWaits"],
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=779538
**Error message validated:** `[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.SendMoreThanStreamLimitRequestsConcurrently_LastWaits.*FAIL System.TimeoutException . The operation has timed out. at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.SendMoreThanStreamLimitRequestsConcurrently_LastWaits`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 8/18/2024 7:44:39 PM UTC

**Comment by liveans** [comment] 2024-08-18 19:47
Duplicate of #106596

**Closed by liveans** 2024-08-18 19:47 UTC
Labels: area-System.Net.Http, blocking-clean-ci, untriaged, Known Build Error
