### ISSUE TITLE
Applications requesting download of .NET 8 runtime even when it is installed

### ISSUE THREAD

**Issue by clin1234** [dotnet/runtime#105615] opened 2024-07-29 12:08 UTC
![Screenshot 2024-07-27 125456](https://github.com/user-attachments/assets/b5dd62d4-28dc-45a9-a4e8-2387fe4755f3)

Even though I already have it installed:

```
❯ dir "c:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\
 Volume in drive C is Blade 17
 Volume Serial Number is BE09-C168

 Directory of c:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7

07/28/2024  09:29 AM    <DIR>          .
07/28/2024  09:29 AM    <DIR>          ..
06/13/2024  07:56 PM                49 .version
06/13/2024  10:49 PM           310,960 clretwrc.dll
06/13/2024  10:51 PM           672,008 clrgc.dll
06/13/2024  10:49 PM         1,787,144 clrjit.dll
06/13/2024  10:49 PM         5,034,768 coreclr.dll
06/13/2024  10:49 PM            65,760 createdump.exe
06/13/2024  10:49 PM           399,008 hostpolicy.dll
06/13/2024  10:51 PM         1,005,848 Microsoft.CSharp.dll
04/27/2024  11:20 PM         2,309,152 Microsoft.DiaSymReader.Native.amd64.dll
06/13/2024  08:00 PM            28,516 Microsoft.NETCore.App.deps.json
06/13/2024  08:00 PM                53 Microsoft.NETCore.App.runtimeconfig.json
06/13/2024  10:49 PM         1,247,392 Microsoft.VisualBasic.Core.dll
06/13/2024  10:49 PM            17,568 Microsoft.VisualBasic.dll
06/13/2024  10:49 PM            15,520 Microsoft.Win32.Primitives.dll
06/13/2024  10:49 PM           120,992 Microsoft.Win32.Registry.dll
06/13/2024  07:38 PM         1,337,352 mscordaccore.dll
06/13/2024  07:38 PM         1,337,352 mscordaccore_amd64_amd64_8.0.724.31311.dll
06/13/2024  07:38 PM         1,241,624 mscordbi.dll
06/13/2024  10:49 PM            59,552 mscorlib.dll
06/13/2024  10:49 PM           136,864 mscorrc.dll
03/12/2024  04:41 PM           538,136 msquic.dll
06/13/2024  10:49 PM           101,040 netstandard.dll
06/13/2024  10:49 PM            15,520 System.AppContext.dll
06/13/2024  10:49 PM            15,536 System.Buffers.dll
06/13/2024  10:49 PM           276,656 System.Collections.Concurrent.dll
06/13/2024  10:51 PM           260,368 System.Collections.dll
06/13/2024  10:49 PM           837,792 System.Collections.Immutable.dll
06/13/2024  10:49 PM           104,608 System.Collections.NonGeneric.dll
06/13/2024  10:49 PM           104,608 System.Collections.Specialized.dll
06/13/2024  10:49 PM           202,928 System.ComponentModel.Annotations.dll
06/13/2024  11:10 PM            17,056 System.ComponentModel.DataAnnotations.dll
06/13/2024  10:49 PM            30,880 System.ComponentModel.dll
06/13/2024  10:49 PM            47,280 System.ComponentModel.EventBasedAsync.dll
06/13/2024  10:49 PM            80,032 System.ComponentModel.Primitives.dll
06/13/2024  10:49 PM           743,584 System.ComponentModel.TypeConverter.dll
06/13/2024  10:49 PM            19,616 System.Configuration.dll
06/13/2024  10:49 PM           174,256 System.Console.dll
06/13/2024  10:49 PM            23,712 System.Core.dll
06/13/2024  10:49 PM         2,861,216 System.Data.Common.dll
06/13/2024  10:49 PM            16,032 System.Data.DataSetExtensions.dll
06/13/2024  10:49 PM            25,264 System.Data.dll
06/13/2024  10:49 PM            16,560 System.Diagnostics.Contracts.dll
06/13/2024  10:49 PM            16,032 System.Diagnostics.Debug.dll
06/13/2024  10:48 PM           415,920 System.Diagnostics.DiagnosticSource.dll
06/13/2024  10:49 PM            47,280 System.Diagnostics.FileVersionInfo.dll
06/13/2024  10:49 PM           338,096 System.Diagnostics.Process.dll
06/13/2024  10:49 PM            47,280 System.Diagnostics.StackTrace.dll
06/13/2024  10:49 PM            67,744 System.Diagnostics.TextWriterTraceListener.dll
06/13/2024  10:49 PM            15,520 System.Diagnostics.Tools.dll
06/13/2024  10:49 PM           145,568 System.Diagnostics.TraceSource.dll
06/13/2024  10:49 PM            16,560 System.Diagnostics.Tracing.dll
06/13/2024  10:49 PM            50,352 System.dll
06/13/2024  10:49 PM            20,640 System.Drawing.dll
06/13/2024  10:49 PM           133,280 System.Drawing.Primitives.dll
06/13/2024  10:49 PM            16,560 System.Dynamic.Runtime.dll
06/13/2024  10:49 PM           243,888 System.Formats.Asn1.dll
06/13/2024  10:49 PM           272,560 System.Formats.Tar.dll
06/13/2024  10:49 PM            16,048 System.Globalization.Calendars.dll
06/13/2024  10:49 PM            16,032 System.Globalization.dll
06/13/2024  10:49 PM            15,536 System.Globalization.Extensions.dll
06/13/2024  10:49 PM            84,128 System.IO.Compression.Brotli.dll
06/13/2024  10:49 PM           264,352 System.IO.Compression.dll
06/13/2024  10:49 PM            15,520 System.IO.Compression.FileSystem.dll
06/13/2024  10:49 PM           835,744 System.IO.Compression.Native.dll
06/13/2024  10:49 PM            55,456 System.IO.Compression.ZipFile.dll
06/13/2024  10:49 PM            16,032 System.IO.dll
06/13/2024  10:51 PM           104,728 System.IO.FileSystem.AccessControl.dll
06/13/2024  10:49 PM            16,032 System.IO.FileSystem.dll
06/13/2024  10:49 PM            55,456 System.IO.FileSystem.DriveInfo.dll
06/13/2024  10:49 PM            15,536 System.IO.FileSystem.Primitives.dll
06/13/2024  10:49 PM            88,224 System.IO.FileSystem.Watcher.dll
06/13/2024  10:49 PM            92,320 System.IO.IsolatedStorage.dll
06/13/2024  10:49 PM            84,128 System.IO.MemoryMappedFiles.dll
06/13/2024  10:49 PM            16,544 System.IO.Pipes.AccessControl.dll
06/13/2024  10:49 PM           166,048 System.IO.Pipes.dll
06/13/2024  10:49 PM            15,632 System.IO.UnmanagedMemoryStream.dll
06/13/2024  10:49 PM           542,896 System.Linq.dll
06/13/2024  10:51 PM         3,676,440 System.Linq.Expressions.dll
06/13/2024  10:49 PM           805,144 System.Linq.Parallel.dll
06/13/2024  10:49 PM           174,256 System.Linq.Queryable.dll
06/13/2024  10:49 PM           157,872 System.Memory.dll
06/13/2024  10:49 PM            17,584 System.Net.dll
06/13/2024  10:49 PM         1,730,736 System.Net.Http.dll
06/13/2024  10:49 PM           129,200 System.Net.Http.Json.dll
06/13/2024  10:49 PM           551,072 System.Net.HttpListener.dll
06/13/2024  10:49 PM           432,304 System.Net.Mail.dll
06/13/2024  10:51 PM           112,920 System.Net.NameResolution.dll
06/13/2024  10:49 PM           157,872 System.Net.NetworkInformation.dll
06/13/2024  10:49 PM            96,416 System.Net.Ping.dll
06/13/2024  10:51 PM           231,696 System.Net.Primitives.dll
06/13/2024  10:49 PM           280,736 System.Net.Quic.dll
06/13/2024  10:49 PM           346,288 System.Net.Requests.dll
06/13/2024  10:49 PM           669,872 System.Net.Security.dll
06/13/2024  10:49 PM            47,264 System.Net.ServicePoint.dll
06/13/2024  10:49 PM           546,976 System.Net.Sockets.dll
06/13/2024  10:49 PM           170,144 System.Net.WebClient.dll
06/13/2024  10:49 PM            67,744 System.Net.WebHeaderCollection.dll
06/13/2024  10:49 PM            43,168 System.Net.WebProxy.dll
06/13/2024  10:49 PM           100,512 System.Net.WebSockets.Client.dll
06/13/2024  10:49 PM           190,624 System.Net.WebSockets.dll
06/13/2024  10:48 PM            15,520 System.Numerics.dll
06/13/2024  10:49 PM            16,032 System.Numerics.Vectors.dll
06/13/2024  10:50 PM            80,136 System.ObjectModel.dll
06/13/2024  10:49 PM        13,170,848 System.Private.CoreLib.dll
06/13/2024  10:49 PM         2,082,976 System.Private.DataContractSerialization.dll
06/13/2024  10:49 PM           260,272 System.Private.Uri.dll
06/13/2024  10:50 PM         7,989,424 System.Private.Xml.dll
06/13/2024  10:49 PM           403,616 System.Private.Xml.Linq.dll
06/13/2024  10:49 PM            75,952 System.Reflection.DispatchProxy.dll
06/13/2024  10:49 PM            16,560 System.Reflection.dll
06/13/2024  10:49 PM           129,184 System.Reflection.Emit.dll
06/13/2024  10:49 PM            16,032 System.Reflection.Emit.ILGeneration.dll
06/13/2024  10:49 PM            16,144 System.Reflection.Emit.Lightweight.dll
06/13/2024  10:49 PM            15,520 System.Reflection.Extensions.dll
06/13/2024  10:49 PM         1,116,440 System.Reflection.Metadata.dll
06/13/2024  10:49 PM            16,136 System.Reflection.Primitives.dll
06/13/2024  10:49 PM            43,168 System.Reflection.TypeExtensions.dll
06/13/2024  10:49 PM            15,536 System.Resources.Reader.dll
06/13/2024  10:49 PM            16,032 System.Resources.ResourceManager.dll
06/13/2024  10:49 PM            51,376 System.Resources.Writer.dll
06/13/2024  10:49 PM            15,520 System.Runtime.CompilerServices.Unsafe.dll
06/13/2024  10:51 PM            30,992 System.Runtime.CompilerServices.VisualC.dll
06/13/2024  10:49 PM            43,696 System.Runtime.dll
06/13/2024  10:49 PM            18,080 System.Runtime.Extensions.dll
06/13/2024  10:49 PM            15,536 System.Runtime.Handles.dll
06/13/2024  10:49 PM            96,432 System.Runtime.InteropServices.dll
06/13/2024  10:49 PM            51,376 System.Runtime.InteropServices.JavaScript.dll
06/13/2024  10:49 PM            15,536 System.Runtime.InteropServices.RuntimeInformation.dll
06/13/2024  10:49 PM            17,056 System.Runtime.Intrinsics.dll
06/13/2024  10:49 PM            16,032 System.Runtime.Loader.dll
06/13/2024  10:49 PM           329,888 System.Runtime.Numerics.dll
06/13/2024  10:48 PM            17,056 System.Runtime.Serialization.dll
06/13/2024  10:49 PM           309,424 System.Runtime.Serialization.Formatters.dll
06/13/2024  10:49 PM            16,032 System.Runtime.Serialization.Json.dll
06/13/2024  10:49 PM            39,072 System.Runtime.Serialization.Primitives.dll
06/13/2024  10:49 PM            17,056 System.Runtime.Serialization.Xml.dll
06/13/2024  10:49 PM           231,584 System.Security.AccessControl.dll
06/13/2024  10:49 PM           100,512 System.Security.Claims.dll
06/13/2024  10:49 PM            17,568 System.Security.Cryptography.Algorithms.dll
06/13/2024  10:49 PM            16,544 System.Security.Cryptography.Cng.dll
06/13/2024  10:49 PM            16,032 System.Security.Cryptography.Csp.dll
06/13/2024  10:49 PM         2,050,208 System.Security.Cryptography.dll
06/13/2024  10:49 PM            16,032 System.Security.Cryptography.Encoding.dll
06/13/2024  10:49 PM            15,520 System.Security.Cryptography.OpenSsl.dll
06/13/2024  10:49 PM            16,032 System.Security.Cryptography.Primitives.dll
06/13/2024  10:49 PM            17,072 System.Security.Cryptography.X509Certificates.dll
06/13/2024  10:49 PM            18,592 System.Security.dll
06/13/2024  10:49 PM            15,520 System.Security.Principal.dll
06/13/2024  10:49 PM           186,528 System.Security.Principal.Windows.dll
06/13/2024  10:49 PM            15,520 System.Security.SecureString.dll
06/13/2024  11:10 PM            17,072 System.ServiceModel.Web.dll
06/13/2024  10:49 PM            16,048 System.ServiceProcess.dll
06/13/2024  10:49 PM           862,368 System.Text.Encoding.CodePages.dll
06/13/2024  10:49 PM            16,032 System.Text.Encoding.dll
06/13/2024  10:49 PM            16,144 System.Text.Encoding.Extensions.dll
06/13/2024  10:49 PM           133,280 System.Text.Encodings.Web.dll
06/13/2024  10:49 PM         1,501,344 System.Text.Json.dll
06/13/2024  10:48 PM         1,022,112 System.Text.RegularExpressions.dll
06/13/2024  10:49 PM           133,280 System.Threading.Channels.dll
06/13/2024  10:49 PM            84,128 System.Threading.dll
06/13/2024  10:49 PM            16,032 System.Threading.Overlapped.dll
06/13/2024  10:49 PM           489,632 System.Threading.Tasks.Dataflow.dll
06/13/2024  10:49 PM            17,056 System.Threading.Tasks.dll
06/13/2024  10:49 PM            16,032 System.Threading.Tasks.Extensions.dll
06/13/2024  10:51 PM           133,400 System.Threading.Tasks.Parallel.dll
06/13/2024  10:49 PM            16,048 System.Threading.Thread.dll
06/13/2024  10:49 PM            16,048 System.Threading.ThreadPool.dll
06/13/2024  10:49 PM            15,536 System.Threading.Timer.dll
06/13/2024  10:49 PM            16,560 System.Transactions.dll
06/13/2024  10:49 PM           661,664 System.Transactions.Local.dll
06/13/2024  10:49 PM            15,520 System.ValueTuple.dll
06/13/2024  10:49 PM            15,520 System.Web.dll
06/13/2024  10:49 PM            59,568 System.Web.HttpUtility.dll
06/13/2024  10:49 PM            16,032 System.Windows.dll
06/13/2024  10:49 PM            23,712 System.Xml.dll
06/13/2024  10:49 PM            16,032 System.Xml.Linq.dll
06/13/2024  10:49 PM            22,176 System.Xml.ReaderWriter.dll
06/13/2024  10:49 PM            16,544 System.Xml.Serialization.dll
06/13/2024  10:49 PM            16,048 System.Xml.XDocument.dll
06/13/2024  10:49 PM            16,032 System.Xml.XmlDocument.dll
06/13/2024  10:49 PM            18,096 System.Xml.XmlSerializer.dll
06/13/2024  10:48 PM            16,032 System.Xml.XPath.dll
06/13/2024  10:49 PM            30,896 System.Xml.XPath.XDocument.dll
06/13/2024  11:10 PM            16,544 WindowsBase.dll
             184 File(s)     73,568,194 bytes
               2 Dir(s)  13,455,122,432 bytes free
```

Trying the "Repair" option within the installer did not work either

**Comment by NikolaMilosavljevic** [comment] 2024-07-30 21:07
[Triage] @clin1234 this seems to be an issue with the Update Checker tool. Presumably, it is checking for 8.0.0 version explicitly.

**Comment by NikolaMilosavljevic** [comment] 2024-08-13 21:26
[Triage] Closing as we could not reproduce this issue.

**Closed by NikolaMilosavljevic** 2024-08-13 21:26 UTC
Labels: area-Setup, untriaged
