### ISSUE TITLE
1 XOR 1 computes to 1 in release mode

### ISSUE THREAD

**Issue by bradmarder** [dotnet/runtime#80711] opened 2023-01-16 19:23 UTC
### Description

@jakobbotsch 

`1 ^ 1`  should compute to `0` in release mode. 

### Reproduction Steps

```c#
// Generated by Fuzzlyn v1.5 on 2023-01-16 17:01:38
// Run on X64 Windows
// Seed: 10178493004625664135
// Reduced from 625.1 KiB to 1.5 KiB in 00:03:14
// Debug: Outputs 0
// Release: Outputs 1
public struct S0
{
	public bool F1;
}

public struct S1
{
	public S0 F2;
}

public class Program
{
	public static ushort s_19;
	public static S1 s_21;
	public static ushort[] s_32;

	public static void Main()
	{
		ulong[] vr0 = new ulong[] { 0 };
		for (int vr1 = 0; vr1 < 2; vr1++)
		{
			vr0[0] = 1;
			if (s_21.F2.F1)
			{
				s_32[0] = s_19;
			}

			vr0[0] ^= vr0[0];
			Console.WriteLine(vr1);
		}
		Console.WriteLine(vr0[0]);
	}
}
```

### Expected behavior

`1 ^ 1` should compute to `0`.

### Actual behavior

`1 ^ 1` computes to `1`.

### Regression?

No, reproduces in net6.

**Comment by EgorBo** [comment] 2023-01-16 20:00
From a quick glance it's Loop Hoisting hoisted `vr0[0]`

**Comment by jakobbotsch** [comment] 2023-01-16 20:55
This is probably a duplicate of #75442.

**Comment by jakobbotsch** [comment] 2023-06-20 11:51
Closing as a dup of #75442

**Closed by jakobbotsch** 2023-06-20 11:51 UTC
Labels: bug, area-CodeGen-coreclr
