### ISSUE TITLE
[wasm] Add flag to remove non-blittable marshaling functionality from the runtime

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/runtime#43691] opened 2020-10-21 17:07 UTC
Most of this is not needed on wasm and takes up quite a bit of space: for a low-end ballpark: `mono_marshal_*` is around 15K and `emit_*` (mostly marshalling) is around 30K. We will need a new flag specifically for this.

We can also push people to use source generators, see https://github.com/dotnet/runtime/issues/43060

**Comment by CoffeeFlux** [comment] 2021-02-02 15:50
This was initially added a while back with https://github.com/dotnet/runtime/pull/46444

There is more work to be done here, since there is more code we can get behind the flag, but the core functionality exists. The remaining bit is lower priority since it's not useful until the Interop team's work on the PInvoke generation is completed.

**Comment by SamMonoRT** [comment] 2021-06-21 16:18
Remaining low priority work can be tackled in 7.0.0

**Comment by lambdageek** [comment] 2022-02-07 20:31
This is related to #61685, although I think we're aiming for a less `#ifdef`-y apprach now using mono runtime components instead

**Comment by ilonatommy** [comment] 2022-06-13 10:15
@SamMonoRT, how is it progressing?

**Comment by naricc** [comment] 2022-08-01 17:29
This is actualy a duplicate of: https://github.com/dotnet/runtime/issues/61685, which spells out more details.

**Closed by naricc** 2022-08-01 17:29 UTC
Labels: arch-wasm, area-VM-meta-mono, size-reduction
