### ISSUE TITLE
Timezone convert back and forth on linux is not working

### ISSUE THREAD

**Issue by tire0011** [dotnet/runtime#51970] opened 2021-04-28 06:26 UTC
### Description

When I run this code snippet:
`TimeZoneInfo.FromSerializedString(TimeZoneInfo.Local.ToSerializedString())`
or on powershell core
`[TimeZoneInfo]::FromSerializedString([TimeZoneInfo]::Local.ToSerializedString())`
 then a exception is thrown
"An error occurred while deserializing the object.  The serialized data is corrupt."

### Configuration

* Which version of .NET is the code running on?
 dotnet --info

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

* What OS and version, and what distro if applicable?
PS /app> cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
* What is the architecture (x64, x86, ARM, ARM64)?
* Do you know whether it is specific to that configuration?
It is tested at a docker container Enviroment variable:
TZ=Europe/Berlin

### Other information

* Please include any relevant stack traces or error messages. If possible please include text as text rather than images (so it shows up in searches).
* If you have an idea where the problem might lie, let us know that here. Please include any pointers to code, relevant changes, or related issues you know of.
* Do you know of any workarounds?
If I remove the Enviroment var TZ=Europe/Berlin, default is Etc/UTC then it is working.

**Comment by tarekgh** [comment] 2021-04-29 17:26
This is a duplicate of https://github.com/dotnet/runtime/issues/19794

We are not recommending using `FromSerializedString` anymore and we are thinking to obsolete it. Now there are standard time zones which covering the whole world. so you can just serialize only the time zone id and then reconstruct this time zone using this id when you want to deserialize it.

**Closed by tarekgh** 2021-04-29 17:26 UTC
Labels: area-System.Runtime
