### ISSUE TITLE
(foo is not FooClass notNullFoo) is not the same as (!(foo is FooClass notNullFoo))

### ISSUE THREAD

**Issue by Trolldemorted** [dotnet/runtime#44705] opened 2020-11-15 16:41 UTC
### Description

Take this program:
```c#
using System;

SomeRecord? sr = new SomeRecord("foo");

if (sr is not SomeRecord notNullRecord1)
    throw new Exception();

if (!(sr is SomeRecord notNullRecord2))
    throw new Exception();

Console.WriteLine($"sr null?             {sr == null}");
Console.WriteLine($"notNullRecord1 null? {notNullRecord1 == null}");
Console.WriteLine($"notNullRecord2 null? {notNullRecord2 == null}");

public record SomeRecord(string Foo);
```

It outputs:
```
sr null?             False
notNullRecord1 null? True
notNullRecord2 null? False
```

Imo non-nullable reference types should not be null, and the program should output:
```
sr null?             False
notNullRecord1 null? False
notNullRecord2 null? False
```

This makes dealing with non-nullable reference types in combination with System.Text.Json's deserialization even worse. Visual Studio's tooltip indicates that all 3 variables are not null.

Additionally VS 2019 (16.8.1) is showing an IDE0083 message ("Use pattern matching") in line 8, and if I apply the suggestion it converts `if (!(sr is SomeRecord notNullRecord2))` to `if (sr is not SomeRecord notNullRecord1)`, so applying the suggestion changes the behaviour of the program.

### Configuration
- dotnet 5.0.100, VS 2019 (16.8.1)
- W10 2004
- x64

**Comment by huoyaoyuan** [comment] 2020-11-15 16:42
dotnet/roslyn#49262

**Comment by jkotas** [comment] 2020-11-15 17:24
Duplicate of dotnet/roslyn#49262

**Closed by jkotas** 2020-11-15 17:24 UTC
Labels: untriaged
