### ISSUE TITLE
Utf8JsonWriter support WriteStringValue without quote options  (literal string value)

### ISSUE THREAD

**Issue by yongkeecho** [dotnet/runtime#48661] opened 2021-02-23 19:34 UTC
I need to serialize my object which contains a 3rd party object very hard to serialize.
```C#
class MyObject {
  public string Name { get; set; }

  [JsonPropertyName("complexObject"]
  [JsonConverter(typeof(ComplexObjectConverter))]
  public VeryComplexObject Object { get; set; }
}
```
So I'd like to use its own _SerializeToString_ function in my **ComplexObjectConverter**.
```C#
public override void Write(Utf8JsonWriter writer, VeryComplexObject value, JsonSerializerOptions options)
{
  writer.WriteStringValue(value.SerializeToString());
}
```
**MyObject** is serialized as below

```json
{
  "name": "test1",
  "complexObject": "{"k1": "v1", .... }"
}
```
Eventually I need to remove double quotes around the serialized json using regular expression.
I want to have an option like below
```C#
writer.WriteStringValue(value.SerializeToString(), ValueOptions.WithoutDoubleDoubleQuotes);
```
So I can write a json string without quote.
```json
{
  "name": "test1",
  "complexObject": {"k1": "v1", .... }
}
```

**Comment by eiriktsarpalis** [comment] 2021-02-23 20:02
I believe your use case would be solved using the proposed `Utf8JsonWriter.WriteRawValue` in #1784. We are considering this feature for .NET 6.

**Comment by eiriktsarpalis** [comment] 2021-02-23 20:03
Closing as dupe of #1784.

**Closed by eiriktsarpalis** 2021-02-23 20:03 UTC
Labels: api-suggestion, area-System.Text.Json, untriaged
