### ISSUE TITLE
Allow using multi pattern in Directory.GetFiles

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/runtime#35747] opened 2020-05-02 15:59 UTC
I want to search for files with the extensions .txt or .doc. I had to use this:
```
For Each f In IO.Directory.GetFiles("*.txt").Union(
                      IO.Directory.GetFiles("*.doc"))

Next
```

Or I can get all files, and write conditions or use Regex to check the pattern myself.
Instead, I suggest to use the `|` to match one of many patterns like this:
```
For Each f In IO.Directory.GetFiles("*.txt|*.doc")

Next
```

The `|` character is invalid in file and folders, so, this change wil not break any existing code.
Note that this applies also to all directory and file classes that use a search pattern, such as DirectoryInfo… etc.

**Comment by VBAndCs** [comment] 2020-05-02 16:31
@danmosemsft
What do this mean?
> Tagging subscribers to this area: @Jozkee
 Notify danmosemsft if you want to be subscribed.

**Comment by svick** [comment] 2020-05-02 17:33
> The `|` character is invalid in file and folders

It's invalid on Windows, but valid on Linux. So, what do you propose happens on OSes where `|` is a valid filename character (and where changing the meaning of `|` in `GetFiles` would be a breaking change)?

**Comment by VBAndCs** [comment] 2020-05-02 17:46
We can choose a common invalid char.

**Comment by VBAndCs** [comment] 2020-05-02 17:47
Another solution is to use a param array for patterns

**Comment by danmosemsft** [comment] 2020-05-02 21:36
> What do this mean?

It just means that @Jozkee helps manage area-System.IO.

**Comment by pinkfloydx33** [comment] 2020-05-03 08:46
Weren't new directory enumerating APIs added that would allow you to "manually" support this case? I know I had read a blog announcement or two about the newer APIs but I can't for the life of me find them anywhere to confirm.

**Comment by svick** [comment] 2020-05-05 10:57
@pinkfloydx33 I think you're talking about [the `FileSystemEnumerable` class](https://docs.microsoft.com/en-us/dotnet/api/system.io.enumeration.filesystemenumerable-1). That would allow you to write something like:

```c#
var files = new FileSystemEnumerable<string>(
    directory,
    (ref FileSystemEntry entry) => entry.ToSpecifiedFullPath())
{
    ShouldIncludePredicate = (ref FileSystemEntry entry) =>
        !entry.IsDirectory &&
        (entry.FileName.EndsWith(".txt") || entry.FileName.EndsWith(".doc"))
};
```

While this would be quite efficient, it's also very verbose, and I think that would defeat the purpose of this request.

**Comment by pinkfloydx33** [comment] 2020-05-05 11:26
@svick that is indeed what I was thinking of. I couldn't remember the specifics of those APIs--I thought they may have included something that would've satisfied the request.

**Comment by carlossanlop** [comment] 2020-05-15 22:49
I'm closing this issue as duplicate of https://github.com/dotnet/runtime/issues/21362 , which is an existing ask to add Globbing and RegEx support.

**Closed by carlossanlop** 2020-05-15 22:49 UTC
Labels: area-System.IO, untriaged
