### ISSUE TITLE
Nullable value type corrupted on Arm64

### ISSUE THREAD

**Issue by destator** [dotnet/runtime#99377] opened 2024-03-06 19:15 UTC
### Description

Nullable value type corrupted when passed as arguments on Arm64

### Reproduction Steps

Program.cs

```
using System;

namespace NullableTest {
    public static class Program {
        public static void Main() {
            TestLongs(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12);
        }

        private static void TestLongs(long? p0, long? p1, long? p2, long? p3, long? p4, long? p5, long? p6, long? p7, long? p8, long? p9, long? p10, long? p11, long? p12) {
            Console.WriteLine($"p0:{p0}, p1:{p1}, p2:{p2}, p3:{p3}, p4:{p4}, p5:{p5}, p6:{p6}, p7:{p7}, p8:{p8}, p9:{p9}, p10:{p10}, p11:{p11}, p12:{p12}");
        }
    }
}
```

### Expected behavior

Run on x86_64 Linux 4.19 SDK 2.2.402 inside docker

```
root@cb520a5811e1 /app # dotnet NullableTest.dll
p0:0, p1:1, p2:2, p3:3, p4:4, p5:5, p6:6, p7:7, p8:8, p9:9, p10:10, p11:11, p12:12
root@cb520a5811e1 /app # dotnet --version
2.2.402
root@cb520a5811e1 /app # uname -a
Linux cb520a5811e1 4.19.0-16-cloud-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux
```

### Actual behavior

Run on Arm64 Linux 5.10 SDK 2.2.402 inside docker

```
root@890b92de1a09 /app # dotnet NullableTest.dll
p0:0, p1:1, p2:2, p3:3, p4:281474025525504, p5:281474025526016, p6:281474025526272, p7:0, p8:0, p9:281474025525760, p10:281473399363840, p11:281473337481472, p12:281473337481472
root@890b92de1a09 /app # dotnet NullableTest.dll
p0:0, p1:1, p2:2, p3:3, p4:281474687468800, p5:281474687469312, p6:281474687469568, p7:0, p8:0, p9:281474687468800, p10:281473041037568, p11:281472979155200, p12:281472979155200
root@890b92de1a09 /app # dotnet NullableTest.dll
p0:0, p1:1, p2:2, p3:3, p4:281474744266496, p5:281474744266752, p6:281474744267264, p7:0, p8:0, p9:281474744266496, p10:281473193519360, p11:281473131636992, p12:281473131636992
root@890b92de1a09 /app # dotnet --version
2.2.402
root@890b92de1a09 /app # uname -a
Linux 890b92de1a09 5.10.0-26-cloud-arm64 #1 SMP Debian 5.10.197-1 (2023-09-29) aarch64 GNU/Linux
```

### Other information

This bug has been fixed in newer versions, but I couldn't find any info about, what causes it, or what else it affects.

**Comment by jkotas** [comment] 2024-03-07 00:13
> .NET SDK 2.2

Arm64 support in .NET 2.x shipped as a preview and it had number of bugs that has been fixed since then.

As you have pointed out, the problem is fixed in the currently supported .NET runtime versions.

**Closed by jkotas** 2024-03-07 00:13 UTC
Labels: area-CodeGen-coreclr, untriaged
