### ISSUE TITLE
Unable to use Process.Start() in Mac Catalyst Universal application in Release configuration

### ISSUE THREAD

**Issue by Bodkens** [dotnet/runtime#100129] opened 2024-03-22 00:42 UTC
### Description

I have Mac Catalyst application that needs run another app with. I do this with `Process.Start()` It works fine in Debug mode, but when i do `dotnet publish` it does not work in Universal build of Release config. It return me this error below. I turned off sandbox mode. Is there another way and more correct way to start applications in Mac?

<img width="1031" alt="Снимок экрана 2024-03-22 в 01 06 18" src="https://github.com/dotnet/maui/assets/59771705/8e8b2d48-ac46-44aa-9124-9e94c3b3ceca">

My workload 

Installed Workload Id      Manifest Version      Installation Source
maui-maccatalyst           8.0.7/8.0.100         SDK 8.0.100        
maui-ios                   8.0.7/8.0.100         SDK 8.0.100        
maui-android               8.0.7/8.0.100         SDK 8.0.100        
maui                       8.0.7/8.0.100         SDK 8.0.100        

### Steps to Reproduce

1) Create example MAUI App
2) In Platform/Entitlements.plist set `com.apple.security.app-sandbox` to false
3) Edit MAUI example app to start another app, for example Weather(Weather can crush if we start it that way but main point that it detects and runs weather app)
```
public partial class MainPage : ContentPage
{
	int count = 0;

	public MainPage()
	{
		InitializeComponent();
	}

	private void OnCounterClicked(object sender, EventArgs e)
	{
		count++;
		try{
			Process.Start("/System/Applications/Weather.app/Contents/MacOS/Weather");
		}
		catch(Exception ex){
			this.DisplayAlert("Error", ex.Message, "Ok"); 
		}
```
4) Run and see that it works in debug
5) Create release configuration by `dotnet publish -f net8.0-maccatalyst -c Release -p:CreatePackage=false`
6) Run bin/Release/net8.0-maccatalyst/MauiApp.app and see that it returns Attempting to JIT compile method 'void System.Runtime.Serialization.SerializationGuard:<ThrowIfDeserializationInProgress>g__ThrowIfDeserializationInProgress|0_0 (System.Runtime.Serialization.SerializationInfo,string,int&)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.

### Version with bug

8.0.7 SR2

### Is this a regression from previous behavior?

No, this is something new

### Last version that worked well

Unknown/Other

### Affected platforms

macOS

**Comment by simonrozsival** [comment] 2024-07-18 10:40
I can repro the exception in .NET 8. When I run the same code with .NET 9 Preview 6, it works correctly. [SerializationGuard uses `[UnsafeAccessor]`](https://github.com/dotnet/runtime/blob/release/8.0/src/libraries/Common/src/System/Runtime/Serialization/SerializationGuard.cs#L22-L23), so maybe this is due to some fixes/improvements to this feature in Mono in .NET 9?

**Comment by simonrozsival** [comment] 2024-07-19 08:49
I'm closing the issue now since it's not reproducible in upcoming .NET 9 release anymore. Please feel free to reopen the issue if you need this fix backported to .NET 8 servicing, @Bodkens.

**Closed by simonrozsival** 2024-07-19 08:49 UTC
Labels: area-System.Diagnostics.Process, untriaged, os-maccatalyst
