### ISSUE TITLE
Pointer Type objects IsClass returning unexpected value.

### ISSUE THREAD

**Issue by CryoMyst** [dotnet/runtime#92367] opened 2023-09-20 19:43 UTC
### Description

Seems pointer types with `Type.IsClass` will return `true`, this seems unexpected as I would expect an untyped raw pointer to be the same as an `nint`. This also seems to be the case with `IsPrimitive` returning false but I am unsure if untyped pointers should have the same return as nint here.

### Reproduction Steps

```csharp
typeof(void*).IsClass == true
```

### Expected behavior

I would expect a pointer type to not be a class.

### Actual behavior

Type.IsClass is returning true for pointer types.

### Known Workarounds

Can always do another check using `Type.IsPointer` before checking for `Type.IsClass'.

**Comment by huoyaoyuan** [comment] 2023-09-21 06:28
See also #90993

**Comment by steveharter** [comment] 2023-10-10 19:09
Closing as by design. The [documentation ](https://learn.microsoft.com/dotnet/api/system.type.isclass)says "Gets a value indicating whether the Type is a class or a delegate; that is, not a value type or interface."

A pointer is a reference type; see this discussion: https://github.com/dotnet/runtime/issues/90993#issuecomment-1705315813.

**Closed by steveharter** 2023-10-10 19:09 UTC
Labels: area-System.Reflection, untriaged
