### ISSUE TITLE
Net5 RC2/GetPhysicalAddress

### ISSUE THREAD

**Issue by quzefeng** [dotnet/runtime#43990] opened 2020-10-15 10:37 UTC
# Issue Title

Net5 RC2/GetPhysicalAddress Not Get PhysicalAddress In Ubuntu18.04

# General

The function of obtaining the physical network card address is normal on windows, but the physical address of the network card cannot be obtained on ubuntu18.04. Please help to find out the reason;

![QQ截图20201015183515](https://user-images.githubusercontent.com/17823304/96112558-65b4a700-0f15-11eb-8897-3e0130dbf369.png)

```cs
public static void DisplayTypeAndAddress()
        {
            IPGlobalProperties computerProperties = IPGlobalProperties.GetIPGlobalProperties();
            NetworkInterface[] nics = NetworkInterface.GetAllNetworkInterfaces();
            Console.WriteLine("Interface information for {0}.{1}     ",
                    computerProperties.HostName, computerProperties.DomainName);
            foreach (NetworkInterface adapter in nics)
            {
                IPInterfaceProperties properties = adapter.GetIPProperties();
                Console.WriteLine(adapter.Description);
                Console.WriteLine(String.Empty.PadLeft(adapter.Description.Length, '='));
                Console.WriteLine("  Interface type .......................... : {0}", adapter.NetworkInterfaceType);
                Console.WriteLine("  Physical Address ........................ : {0}",
                           adapter.GetPhysicalAddress().ToString());
                Console.WriteLine("  Is receive only.......................... : {0}", adapter.IsReceiveOnly);
                Console.WriteLine("  Multicast................................ : {0}", adapter.SupportsMulticast);
                Console.WriteLine();
            }
        }
```

**Comment by carlossanlop** [comment] 2020-10-28 22:27
@wfurt can you please take a look?

**Comment by wfurt** [comment] 2020-10-29 00:25
It does lookalike like dup as @omajid mentioned. Could you try the RTM build https://github.com/dotnet/installer @quzefeng? If that does not work, I'll take a look.

**Comment by quzefeng** [comment] 2020-10-29 00:49
OK, I'll see if the RTM build works, and I'll see how it works on Ubuntu 18.04. @wfurt

**Comment by karelz** [comment] 2020-10-29 17:28
Duplicate of #42870

**Comment by karelz** [comment] 2020-10-29 17:28
@quzefeng please let us know if RTM does not work for you and our duplicate decision was premature -- we would reopen in such case. Thanks!

**Closed by karelz** 2020-10-29 17:28 UTC
Labels: area-System.Net, untriaged
