### ISSUE TITLE
Authentication validation failed with error - InvalidToken exception on .net 7 and .net 8 preview 6

### ISSUE THREAD

**Issue by drpdrp** [dotnet/runtime#88874] opened 2023-07-13 23:42 UTC
### Description

With .net 7.0 or 8.0 preview 6 as WCF client in console app the request to WCF server API fails. The server sees the request and produces results (probably sees no error, but I have no access), the client throws an exception.

The same code works when target framework is set to .net 6.0.

### Reproduction Steps

Configuration of client binding:

> System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
> result.MaxBufferSize = int.MaxValue;
> result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
> result.MaxReceivedMessageSize = int.MaxValue;
> result.AllowCookies = true;
> result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
> result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.Windows;

Reference to WCF service was generated with svc.exe with wsdl file.

### Expected behavior

The request succeeds with response from the server.

### Actual behavior

Exception is produced:

> System.ServiceModel.CommunicationException: 'Authentication validation failed with error - InvalidToken.'
> 
> System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(System.Net.Http.HttpRequestMessage, System.Uri, bool, System.Net.ICredentials, bool, System.Net.Http.HttpConnection, System.Net.Http.HttpConnectionPool, System.Threading.CancellationToken) in AuthenticationHelper.NtAuth.cs
> System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(System.Net.Http.HttpRequestMessage, bool, bool, System.Threading.CancellationToken) in HttpConnectionPool.cs
> System.Threading.Tasks.ValueTask<TResult>.Result.get() in ValueTask.cs
> System.Net.Http.AuthenticationHelper.SendWithAuthAsync(System.Net.Http.HttpRequestMessage, System.Uri, bool, System.Net.ICredentials, bool, bool, bool, System.Net.Http.HttpConnectionPool, System.Threading.CancellationToken) in AuthenticationHelper.cs
> System.Threading.Tasks.ValueTask<TResult>.Result.get() in ValueTask.cs
> System.Net.Http.RedirectHandler.SendAsync(System.Net.Http.HttpRequestMessage, bool, System.Threading.CancellationToken) in RedirectHandler.cs
> System.Threading.Tasks.ValueTask<TResult>.Result.get() in ValueTask.cs
> System.Net.Http.DecompressionHandler.SendAsync(System.Net.Http.HttpRequestMessage, bool, System.Threading.CancellationToken) in DecompressionHandler.cs
> System.Net.Http.HttpClient.SendAsync.__Core|83_0(System.Net.Http.HttpRequestMessage, System.Net.Http.HttpCompletionOption, System.Threading.CancellationTokenSource, bool, System.Threading.CancellationTokenSource, System.Threading.CancellationToken) in HttpClient.cs
> System.ServiceModel.Channels.HttpChannelFactory<TChannel>.HttpClientRequestChannel.HttpClientChannelAsyncRequest.SendRequestAsync(System.ServiceModel.Channels.Message, System.Runtime.TimeoutHelper) in HttpChannelFactory.cs
> 

### Regression?

Currently works in .net 6.0. This is a blocking error for us to migrate to latest .net version.

### Known Workarounds

While debugging, stepping trought System.Net.Http code, it was possible to get to the success result with the servers response. So it seems this is some kind of race condition/time dependent issue.

### Configuration

.net 7 or 8 preview 6
Windows 10 x64
console application

used project package references:

System.ServiceModel.Duplex 6.0.0
System.ServiceModel.Federation 6.0.0
System.ServiceModel.Http 6.0.0
System.ServiceModel.NetTcp 6.0.0

**Comment by filipnavara** [comment] 2023-07-14 06:25
This is essentially a duplicate of https://github.com/dotnet/runtime/issues/81595. In .NET 7 we actually started checking the integrity token that's part of the last HTTP request exchange in Negotiate authentication. That's actually a security protection but unfortunately it may trigger on misconfigured servers. You can follow the diagnostic steps in that issue to produce Fiddler trace so the HTTP request/response exchange can be checked for those wrong authentication headers.

**Comment by drpdrp** [comment] 2023-07-14 08:27
I'm going trought the referenced issue. Using Fiddler as MITM, there is no exception and the call succeeds. Is there a (straightfoward) way to see what is actually wrong with the authentication header, so I can communicate it with server side support? Thanks

**Comment by filipnavara** [comment] 2023-07-14 08:41
We never actually got any full trace back from the customers, so it's not easy to tell what exactly is wrong. The gist is that the authentication will go like this:
- First request should give `WWW-Authenticate: Negotiate` header from the server side and 401 Unauthorized status code
- Then server tokens will be exchanged with the client sending `Authorization: Negotiate <base64 token>` and the server responding with either 401 Unauthorized + `WWW-Authenticate: Negotiate <base64 token>`, or some HTTP 2xx success code (assuming the authorization succeeds).

On the last request of the exchange where the server sends the HTTP 2xx status code, it is important what headers are received from the server. Specifically, there should be a `WWW-Authenticate: Negotiate <base64 token>` header which contains the integrity checksum that prevents MITM downgrade attacks. There should NOT be other `WWW-Authenticate: Negotiate` header, and possibly no other WWW-Authenticate header either.

There are lot of little nuances. For example, old versions and some of the old implementations of the Negotiate protocol lack this last token. To analyze this, it's actually necessary to look at the content of the tokens themselves. This requires specialized tools (eg. Kerberos.NET has a visualization tool), or intricate knowledge of the specifications (and then the tokens can be decoded in https://lapo.it/asn1js/).

If you feel like sharing the Fiddler trace privately, I can have a look (my email is on GitHub). Note that the tokens are potentially sensitive, but they also expire and in majority of the cases they are not usable for a reply attack so I would not be able to use them to authenticate (unless it's really old and misconfigured NTLM which should not be in use for the last ~20 years).

**Comment by filipnavara** [comment] 2023-07-14 08:43
> Using Fiddler as MITM, there is no exception and the call succeeds.

It's possible that Fiddler does some sanitization of the headers returned from the server and it may mask the issue. I cannot tell for sure without seeing the trace. There are alternative tools like ProxyMan, or Charles, that may behave differently. If plain HTTP endpoint (ie. no HTTPS) is an option then Wireshark could also capture usable log.

**Comment by filipnavara** [comment] 2023-07-14 10:42
I got the Fiddler trace and here's the explanation why it fails. The server really sends an invalid token. The client begins the Negotiation normally and chooses to optimistically authenticate with Kerberos V5. The server replies with this (token data are redacted):

```
[1] (1 elem)
  SEQUENCE (4 elem)
    [0] (1 elem)
      ENUMERATED 0
    [1] (1 elem)
      OBJECT IDENTIFIER 1.2.840.48018.1.2.2
    [2] (1 elem)
      OCTET STRING (153 byte) …
        Application 0 (3 elem)
          OBJECT IDENTIFIER 1.2.840.113554.1.2.2
          INTEGER 0
          Application 15 (1 elem)
            SEQUENCE (3 elem)
              [0] (1 elem)
                INTEGER 5
              [1] (1 elem)
                INTEGER 15
              [2] (1 elem)
                SEQUENCE (2 elem)
                  [0] (1 elem)
                    INTEGER 18
                  [2] (1 elem)
                    OCTET STRING (108 byte) …
    [3] (1 elem)
      OCTET STRING (153 byte) …
        Application 0 (3 elem)
          OBJECT IDENTIFIER 1.2.840.113554.1.2.2
          INTEGER 0
          Application 15 (1 elem)
            SEQUENCE (3 elem)
              [0] (1 elem)
                INTEGER 5
              [1] (1 elem)
                INTEGER 15
              [2] (1 elem)
                SEQUENCE (2 elem)
                  [0] (1 elem)
                    INTEGER 18
                  [2] (1 elem)
                    OCTET STRING (108 byte) …
```

This is ASN.1 token specified by https://datatracker.ietf.org/doc/html/rfc4178#section-4.2.2. The problem is that instead of sending the MIC token in `[3]` it sends the exact same Kerberos token as in `[2]`. This is obviously rejected by Windows SSPI as invalid.

There's not much indication of what server software generated the token besides a `X-Powered-By: Servlet/3.0` header.

**Comment by filipnavara** [comment] 2023-07-14 10:48
@SteveSyfuhs does the buggy token ring any bells, by chance?

**Comment by SteveSyfuhs** [comment] 2023-07-14 15:35
It does not ring any bells. That is quite the unfortunate behavior though. No doubt about it, if you're seeing an AP-REP (you are: OID + app 15 + [0]=5 + [1]=15) in the mechlistMIC, the server messed up. Nothing about that is normal.

Given all the details: wcf, kerberos, servlet -- this is almost certainly going to be a Java server implementation. I doubt this is getting produced by MIT or Heimdal, or if it is, it's being produced by a very old version.
________________________________

**Comment by filipnavara** [comment] 2023-07-14 15:39
Thanks. I appreciate the extra pair of eyes and wisdom. I agree it looks like some Java server (no Server header so very little info there). I've also never seen anything like that produced by MIT, Heimdal, or any derivative version of those.

**Comment by filipnavara** [comment] 2023-07-14 15:59
This could be the underlying issue on the server side: https://www.ibm.com/support/pages/apar/IV74044

**Comment by SteveSyfuhs** [comment] 2023-07-14 16:06
That looks like a good candidate and IBM was high on my list of likely culprits.
________________________________

**Comment by karelz** [comment] 2023-07-16 11:07
Looks like culprit was identified and there is not anything we can do on our side. Closing.

**Closed by karelz** 2023-07-16 11:07 UTC
Labels: area-System.Net.Http, untriaged

**Comment by filipnavara** [comment] 2023-07-18 08:38
There's currently no way to turn off the client side ticket validation. I would hesitate to make it an option because it's a security feature, but ultimately it's not my call.

There's a good chance that .NET 8 will ship with an optional switch to use Managed NTLM and SPNEGO implementation. It's currently in a pull request. I will check the history of the workaround in MIT KRB5. If it comes out as a reasonable option we may implement the workaround in the Managed SPNEGO implementation.

I'll keep you updated. However, I still strongly recommend to update the server side to fix the bug. Do we have more information about what software is actually running on the server? It may help other people who experience the problem to diagnose it.

**Comment by drpdrp** [comment] 2023-07-18 13:51
Server is IBM Websphere 8.5.5.19 on Java 1.8

**Comment by filipnavara** [comment] 2023-08-01 16:32
The managed implementation was updated to handle the IBM Websphere bug in the same way as MIT KRB5 does, which covers the solution for macOS, Linux, and mobile platforms (an optional app config switch may be necessary). Unfortunately it won't help you since the switch to managed implementation is not available on Windows.

I am not sure if there's anything more that can be done here. Removing the check in HTTP code would reintroduce a potential man-in-the-middle attack. Enabling the managed implementation of NTLM/SPNEGO on Windows is a non-starter. There are valid reasons to have it on Unix platforms, like buggy implementation on macOS, and NTLM SSP not available on many Linux systems. However, on Windows NTLM is currently always present and it's basically the reference implementation.
