### ISSUE TITLE
System.Text.Json: Serialize to stream ignores property

### ISSUE THREAD

**Issue by nbreinl** [dotnet/runtime#96001] opened 2023-12-14 07:14 UTC
### Description

When serializing an object with a specific structure to a stream, the serializer ignores certain properties. For the bug to happen, there needs to be at least one nesting level in the object. Additionally, the child object needs to implement an interface, that again needs to implement another interface. Properties from the last mentioned interface will be ignored during serialization.

### Reproduction Steps

        [Fact]
        public void MS_Test()
        {
            var parent = new Parent(new Child(100, 200));

            var stream = new MemoryStream();
            JsonSerializer.Serialize(stream, parent);

            stream.Position = 0;

            var jsonDoc = JsonDocument.Parse(stream);
        }
    

    public interface IParent
    {
        IChild? Child { get; }
    }

    public interface IChild : IBaseChild
    {
        decimal? FirstProperty { get; }
    }

    public interface IBaseChild
    {
        decimal? SecondProperty { get; }
    }

    public record Parent(IChild? Child) : IParent;
    public record Child(decimal? FirstProperty, decimal? SecondProperty) : IChild;`

### Expected behavior

I would expect JsonDocument to look like this:

```
Child: {
 "FirstProperty": 100,
 "SecondProperty": 200
}
```

### Actual behavior

_SecondProperty_ does not get serialized, so JsonDocument looks like this:

```
Child: {
 "FirstProperty": 100
}
```

### Known Workarounds

Adding _SecondProperty_ directly to _IChild_ (or completely removing the interfaces) removes the issue.

```
  public interface IChild
  {
      decimal? FirstProperty { get; }
      decimal? SecondProperty { get; }
  }
```

### Configuration

- dotnet version: 6.0.417
- Windows 10

**Comment by huoyaoyuan** [comment] 2023-12-14 07:29
This is expected. If the member type is anything other than `object`, it will be serialized as the declared member type, instead of object type. See #51906.

**Comment by huoyaoyuan** [comment] 2023-12-14 07:29
BTW I wonder if there's any documentation explicitly call this out?

**Comment by eiriktsarpalis** [comment] 2023-12-14 07:33
Duplicate of https://github.com/dotnet/runtime/issues/41749. Interface hierarchy serialization has been fixed in .NET 8 and the System.Text.Json 8.0 nuget package.

**Closed by eiriktsarpalis** 2023-12-14 07:33 UTC
Labels: area-System.Text.Json, untriaged
