### ISSUE TITLE
JsonPropertyName is not inherited from abstract property

### ISSUE THREAD

**Issue by Prochy** [dotnet/runtime#98663] opened 2024-02-19 16:00 UTC
### Description

An abstract property that has defined JsonPropertyName attribute is not inherited in a child class.

### Reproduction Steps

```
public abstract class AbstractClass
{
    [JsonPropertyName("propertyname")]
    public abstract string PropertyName { get; }
}

public class Sample : AbstractClass
{
    public override string PropertyName => "PropertyValue";
}

internal class Program
{
    static void Main(string[] args)
    {
        var sample = new Sample();
        Console.WriteLine(System.Text.Json.JsonSerializer.Serialize(sample));
    }
}
```

### Expected behavior

`{"propertyname":"PropertyValue"}`

### Actual behavior

`{"PropertyName":"PropertyValue","propertyname":"PropertyValue"}`

### Known Workarounds

Define JsonPropertyName on the derived class. 

### Configuration

Windows: 19045.3930
.NET: 8.0.2
Console application
System.Text.Json: 8.0.2

### Other information

In my opinion, the possible workaround produce unwanted that should be cover by .NET library and this should be fixed in the library itself and not by the workaround.

**Comment by eiriktsarpalis** [comment] 2024-02-19 16:16
Duplicate of https://github.com/dotnet/runtime/issues/51165#issuecomment-818676240 and tracked by https://github.com/dotnet/runtime/issues/73255

**Closed by eiriktsarpalis** 2024-02-19 16:16 UTC
Labels: area-System.Text.Json, untriaged
