### ISSUE TITLE
Can't Deserialize the Object with the same options Serialized Object in System.Text.Json

### ISSUE THREAD

**Issue by occulter** [dotnet/runtime#50731] opened 2021-04-05 06:20 UTC
### Description
I can't Deserialize the same object with the same options in System.Text.Json

### Configuration
using .net core standard 2.1

I used options like below
`var options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = false,
                ReadCommentHandling = JsonCommentHandling.Skip,
                AllowTrailingCommas = true,
                 Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping
            };`

The Object is 
`  public class DisAnswerVO
    {
        public int ResChoice;
        public string ResAnswer;
    }
   
   var x = new ResAnswer{
       ResChoice = 1,
       ResAnswer = "yes \r\n no";
     }
   
   var jsonStr = JsonSerializer.Serialize(x, options);

   var y = JsonSerializer.Deserialize<DisAnswerVO>(x,options);
`

### Regression?
It popup that Json Deserialze Exception because "0x0A" not esapced.  I looked up the jsonStr it contains "\r\n" unescaped, I modify it as "\\r\\n" , it work normally. 

How can I deal with it then?

**Comment by eiriktsarpalis** [comment] 2021-04-06 07:15
Hi @occulter. I transcribed your post into what I think was the intended reproducing app:
```csharp
using System.Text.Encodings.Web;
using System.Text.Json;

namespace JsonMaxDepthIssue
{
    class Program
    {
        public class DisAnswerVO
        {
            public int ResChoice;
            public string ResAnswer;
        }

        static void Main()
        {
            var options = new JsonSerializerOptions 
            { 
                PropertyNameCaseInsensitive = false, 
                ReadCommentHandling = JsonCommentHandling.Skip, 
                AllowTrailingCommas = true, 
                Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping
            };

            var x = new DisAnswerVO
            {
                ResChoice = 1,
                ResAnswer = "yes \r\n no"
            };

            var jsonStr = JsonSerializer.Serialize(x, options);
            var y = JsonSerializer.Deserialize<DisAnswerVO>(jsonStr, options);
        }
    }
}
```
This doesn't produce anything unexpected: `x` is serialized as an empty object since `ResChoice` and `ResAnswer` are defined as fields, however nothing unexpected happened when I changed the fields to properties. I certainly didn't observe any exceptions.

> using .net core standard 2.1

Could you clarify if this means `netcoreapp2.1` or `netstandard2.1`? What runtime version is your code running in? If you're consuming `System.Text.Json` via a nuget package could you share its version as well?

Please provide a standalone minimal reproduction with a description of the expected and actual behavior of the app.

**Comment by occulter** [comment] 2021-04-07 07:15
> Hi @occulter. I transcribed your post into what I think was the intended reproducing app:
> 
> ```cs
> using System.Text.Encodings.Web;
> using System.Text.Json;
> 
> namespace Repro
> {
>     class Program
>     {
>         public class DisAnswerVO
>         {
>             public int ResChoice;
>             public string ResAnswer;
>         }
> 
>         static void Main()
>         {
>             var options = new JsonSerializerOptions 
>             { 
>                 PropertyNameCaseInsensitive = false, 
>                 ReadCommentHandling = JsonCommentHandling.Skip, 
>                 AllowTrailingCommas = true, 
>                 Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping
>             };
> 
>             var x = new DisAnswerVO
>             {
>                 ResChoice = 1,
>                 ResAnswer = "yes \r\n no"
>             };
> 
>             var jsonStr = JsonSerializer.Serialize(x, options);
>             var y = JsonSerializer.Deserialize<DisAnswerVO>(jsonStr, options);
>         }
>     }
> }
> ```
> 
> This doesn't produce anything unexpected: `x` is serialized as an empty object since `ResChoice` and `ResAnswer` are defined as fields, however nothing unexpected happened when I changed the fields to properties. I certainly didn't observe any exceptions.
> 
> > using .net core standard 2.1
> 
> Could you clarify if this means `netcoreapp2.1` or `netstandard2.1`? What runtime version is your code running in? If you're consuming `System.Text.Json` via a nuget package could you share its version as well?
> 
> Please provide a standalone minimal reproduction with a description of the expected and actual behavior of the app.

Thank u very very much.

**Comment by occulter** [comment] 2021-04-07 07:21
> Hi @occulter. I transcribed your post into what I think was the intended reproducing app:
> 
> ```cs
> using System.Text.Encodings.Web;
> using System.Text.Json;
> 
> namespace Repro
> {
>     class Program
>     {
>         public class DisAnswerVO
>         {
>             public int ResChoice;
>             public string ResAnswer;
>         }
> 
>         static void Main()
>         {
>             var options = new JsonSerializerOptions 
>             { 
>                 PropertyNameCaseInsensitive = false, 
>                 ReadCommentHandling = JsonCommentHandling.Skip, 
>                 AllowTrailingCommas = true, 
>                 Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping
>             };
> 
>             var x = new DisAnswerVO
>             {
>                 ResChoice = 1,
>                 ResAnswer = "yes \r\n no"
>             };
> 
>             var jsonStr = JsonSerializer.Serialize(x, options);
>             var y = JsonSerializer.Deserialize<DisAnswerVO>(jsonStr, options);
>         }
>     }
> }
> ```
> 
> This doesn't produce anything unexpected: `x` is serialized as an empty object since `ResChoice` and `ResAnswer` are defined as fields, however nothing unexpected happened when I changed the fields to properties. I certainly didn't observe any exceptions.
> 
> > using .net core standard 2.1
> 
> Could you clarify if this means `netcoreapp2.1` or `netstandard2.1`? What runtime version is your code running in? If you're consuming `System.Text.Json` via a nuget package could you share its version as well?
> 
> Please provide a standalone minimal reproduction with a description of the expected and actual behavior of the app.

Thank u very very much.

I am using a class library that SDK is .Net Standard 2.0.3 and System.Text.Json 5.0.1 installed by Nuget.

**Comment by eiriktsarpalis** [comment] 2021-04-07 13:20
> I am using a class library that SDK is .Net Standard 2.0.3

What is the [target framework](https://docs.microsoft.com/en-us/dotnet/standard/frameworks) used by the application that you are using to reproduce the issue? Could you also share the exception you are seeing (and confirm that the code I pasted above reproduces it?)

**Comment by eiriktsarpalis** [comment] 2021-07-23 17:24
In the interest of clearing our untriaged issues ahead of the .NET 6 release, I'm going to close this issue. Feel free to reopen whenever you are able to return with more information about this. Thanks!

**Closed by eiriktsarpalis** 2021-07-23 17:24 UTC
Labels: area-System.Text.Json, needs more info, untriaged
