### ISSUE TITLE
Severe degradation of JsonNode.Parse in net 7 ?

### ISSUE THREAD

**Issue by MichaelLogutov** [dotnet/runtime#78966] opened 2022-11-29 14:41 UTC
Hello.
We've faced severe degradation of our .net logs parser after switching from net 6 to net 7.
After some digging around with perfoкmance profiler I found pretty strange issue that I've isolated in Benchmark.NET code:

```
[SimpleJob(RuntimeMoniker.Net60, baseline: true)]
[SimpleJob(RuntimeMoniker.Net70)]
public class SystemTextJsonBenchmark
{
    [Benchmark]
    public void GetItemByIndexer() => JsonNode.Parse("{ \"value\": \"aaa\" }");
}
```

Which on my machine produces:
```
BenchmarkDotNet=v0.13.2, OS=Windows 11 (10.0.22000.1281/21H2)
11th Gen Intel Core i7-11800H 2.30GHz, 1 CPU, 16 logical and 8 physical cores
.NET SDK=7.0.100
  [Host]   : .NET 7.0.0 (7.0.22.51805), X64 RyuJIT AVX2
  .NET 6.0 : .NET 6.0.11 (6.0.1122.52304), X64 RyuJIT AVX2
  .NET 7.0 : .NET 7.0.0 (7.0.22.51805), X64 RyuJIT AVX2


|           Method |      Job |  Runtime |     Mean |   Error |  StdDev | Ratio | RatioSD |
|----------------- |--------- |--------- |---------:|--------:|--------:|------:|--------:|
| GetItemByIndexer | .NET 6.0 | .NET 6.0 | 267.5 ns | 2.13 ns | 1.99 ns |  1.00 |    0.00 |
| GetItemByIndexer | .NET 7.0 | .NET 7.0 | 546.2 ns | 5.17 ns | 4.32 ns |  2.04 |    0.02 |

// * Hints *
Outliers
  SystemTextJsonBenchmark.GetItemByIndexer: .NET 7.0 -> 2 outliers were removed (560.97 ns, 562.93 ns)
```

Am I doing something wrong or missing something?

Here [BenchmarkSandbox project](https://github.com/dotnet/runtime/files/10114064/BenchmarkSandbox.zip)

**Comment by stephentoub** [comment] 2022-11-29 15:03
I've not tried the benchmark, but I suspect this is a duplicate of https://github.com/dotnet/runtime/issues/78089, which was fixed in main by https://github.com/dotnet/runtime/pull/78130 and ported to release/7.0 in https://github.com/dotnet/runtime/pull/78147, such that a fix should be in the next servicing release.

**Comment by MichaelLogutov** [comment] 2022-11-29 15:07
Yeah, looks like it. Thanks.

**Comment by eiriktsarpalis** [comment] 2022-11-29 18:54
I tried your benchmark on the latest .NET 7, can confirm that it's a duplicate of https://github.com/dotnet/runtime/issues/78089.

**Closed by eiriktsarpalis** 2022-11-29 18:54 UTC
Labels: area-System.Text.Json, tenet-performance, untriaged
