### ISSUE TITLE
Standard Microsoft-Support for SFTP

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#40424] opened 2020-08-05 22:51 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1067836/standard-microsoft-support-for-sftp.html)._

---
<p>I would very much like to see a Microsoft made solution to support SFTP. Currently you have to use Nuget packages, which I think is a shame, since there is also official support from MS under &quot;using System.Net&quot; for FTP there. The third party providers are not bad, but I would like that something like this is supported from the start without additional installations.</p>

---
#### Julian Adler on 6/6/2020, 02:46 PM: 

<p>If there is already an SFTP function, I would ask you to tell me where I can find it.</p>

#### Feedback Bot on 6/8/2020, 03:12 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.
#### Patrick Hintermayer on 7/31/2020, 06:00 AM: 

<p>I agree with you. Adding support for SFTP would be a logical addition to the current FTP support.</p>

**Comment by scalablecory** [comment] 2020-08-06 08:57
> The third party providers are not bad, but I would like that something like this is supported from the start without additional installations.

I think it's a mistake to want to build everything in-box -- we should encourage growth of 3rd party libraries such as [FluentFTP](https://github.com/robinrodricks/FluentFTP).

We should consider baking something in-box only if we have different goals or are not satisfied with the quality of 3rd party libraries.

**Comment by samsosa** [comment] 2020-08-06 15:53
> I think it's a mistake to want to build everything in-box -- we should encourage growth of 3rd party libraries such as FluentFTP.

SFTP (File-Transfer over SSH) is not FTPS (FTP over TLS) ... and FluentFTP doesn't support SFTP. 😉

**Comment by MihaZupan** [comment] 2020-08-06 15:59
Looks like there's a different library available for SFTP that FlientFTP links to: [SSH.NET](https://github.com/sshnet/SSH.NET)

**Comment by wfurt** [comment] 2020-08-06 16:20
this is dup of #31437. It may make sense to bring the package to .NET foundation if we feel good about it.

**Comment by scalablecory** [comment] 2020-08-06 16:41
Ah, thanks for finding that @wfurt.

**Comment by scalablecory** [comment] 2020-08-06 16:41
Duplicate of #31437

**Closed by scalablecory** 2020-08-06 16:41 UTC
Labels: area-System.Net
