### ISSUE TITLE
TcpClient reports "Connected" despite closed firewall in the middle

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [dotnet/runtime#50586] opened 2021-04-01 17:34 UTC
### Description

If I `ConnectAsync` a `TcpClient` to a server using a port that I KNOW is not exposed, I get an error as expected (eg: google.com port 9999 fails). But if I open one to a exposed port, it will report `Connected`, despite a firewall being in the middle of the way dropping all packages.

In another words, 
- `telnet knowHostBlockedByFirewall.com 9999` => time-out
- `tcpClient.ConnectAsync("knowHostBlockedByFirewall.com", 9999)` => connection ok.

### Configuration

using .NET 5. 
using dist: `mcr.microsoft.com/dotnet/aspnet:5.0`. 
x64 architecture

### Regression?

Unknown

**Comment by wfurt** [comment] 2021-04-01 18:18
Get packet capture with Wireshark @Leonardo-Ferreira

**Comment by Leonardo-Ferreira** [comment] 2021-04-01 21:17
@wfurt OK! but right now I don't have a reproducible scenario... this one I encountered on my company's production environment... any ideas on how I would be able reproduce it?

**Comment by wfurt** [comment] 2021-04-01 21:24
No. I suspect that the firewall or any other networking gear is accepting the TCP for deep inspection on behalf of the server. 
So even if the port is closed on the destination, the client can still complete handshake. You would see that (or not) if you can collect the package capture.

**Comment by Leonardo-Ferreira** [comment] 2021-04-01 21:55
@wfurt while I try to get a firewall going, tell me something: if that is the case, why does `telnet myserver.com 80` fails?

**Comment by Leonardo-Ferreira** [comment] 2021-04-01 22:14
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/5585339/113359440-27be0a80-931e-11eb-80f8-4d25d19c7b3c.png">
See, the first 3 packages is the TcpClient opening a connection to google on port 80, the second one is the telnet client... after that 3rd package, telnet report success and etc...
Note that they are the same size and the response is the same also...

**Comment by wfurt** [comment] 2021-04-01 22:14
Could it be default address family? In case `myserver.com` resolves to both IPv4 & Ipv6?
What ever it is, this is not really actionable at moment.

**Comment by Leonardo-Ferreira** [comment] 2021-04-01 22:20
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/5585339/113359988-440e7700-931f-11eb-8e20-bb63981b5341.png">
now this is both my app and telnet trying a port 9999 on google... also similar behavior

**Comment by wfurt** [comment] 2021-04-01 22:23
Right. There are really only three scenarios IMHO. No response -> timeout. SYN+ACK back -> connected, RST, ICMP or something else -> specific error.
Since you cannot reproduce it outside of the production that suggest that there is something unique in that environment.

**Comment by geoffkizer** [comment] 2021-04-02 17:42
> it will report `Connected`

What exactly do you mean by this? Are you polling the Connected property?

**Comment by Leonardo-Ferreira** [comment] 2021-04-03 04:25
By `it will report Connected`, it will not throw a exception on `Connect()`/`ConnectAsync()` and a check on the very next line, will state that `Connected` is true.

@wfurt, looking deeper in my production scenario, I discovered I have not 1, but 2 firewalls: one to control the outbound flow of azure and one to controle the inbound of my destination... I also discovered that only the second one (inbound at destination) was not properly configured.

**Comment by karelz** [comment] 2021-04-13 19:54
Triage: Seems like it was misconfiguration, closing.
Feel free to reopen if we missed anything -- please provide a working repro in that case to simplify investigation. Thanks!

**Closed by karelz** 2021-04-13 19:54 UTC
Labels: area-System.Net, untriaged
