### ISSUE TITLE
variable is not as expected in System.Threading.Tasks

### ISSUE THREAD

**Issue by 1zhhhhh** [dotnet/runtime#75117] opened 2022-09-06 09:27 UTC
### Description

![image](https://user-images.githubusercontent.com/112938734/188598432-76bf242f-bb83-41ef-8534-433e6388fece.png)

the variable "id" I passed to Task is not from 0 to 5. it is always 5. Is it by design?

### Reproduction Steps

using System;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    class Program
    {
        static private Task[] someTasks = new Task[20];

        static private int taskid = -1;

        static private async void Func(int id)
        {
            int id2 = ++taskid;
            while (true)
            {
                Console.WriteLine($"{id}task {id2}\n");
                await Task.Delay(1000);
            }

        }

        static void Main(string[] args)
        {
            for (int i = 0; i < 5; ++i)
            {
                Program.someTasks[i] = Task.Run(() => Program.Func(i));
            }

            while (true);
        }
    }
}

### Expected behavior

I think the variable 'id' in someTasks[0 to 5] should be 0 to 5. 

### Actual behavior

the variable 'id' in someTasks[0 to 5] is 5. 

### Regression?

.net core 3.1

### Configuration

.net core 3.1
windows

**Comment by AntonLapounov** [comment] 2022-09-06 09:53
Yes, that is by design.  You need to make a local copy of `i`:
```C#
for (int i = 0; i < 5; ++i)
{
    int j = i;
    Program.someTasks[i] = Task.Run(() => Program.Func(j));
}
```
Please see this [blog post](https://docs.microsoft.com/en-us/archive/blogs/ericlippert/closing-over-the-loop-variable-considered-harmful) for details.

**Closed** 2022-09-06 11:56 UTC
Labels: untriaged
