### ISSUE TITLE
[Perf -19%] System.Collections.CreateAddAndRemove<Int32> (2)

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#39107] opened 2020-07-10 21:36 UTC
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Changes | [diff](https://github.com/dotnet/installer/compare/a4a49f07fbf986d496ef57521e76b22caaf9bfb3...3c6656f83b01ece6af7e11eb75ec0145554b139d)

### Regressions in System.Collections.CreateAddAndRemove<Int32>

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier
-- | -- | -- | -- | -- | --
List | 12.20 μs | 14.24 μs | 1.17 |  | False
SortedList | 75.89 μs | 91.68 μs | 1.21 |  | False

### Related Issue on x86 Windows
[[Perf -13%] System.Collections.CreateAddAndRemove<Int32> (2)](https://github.com/DrewScoggins/performance-2/issues/912)

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_10_2020/release/3.1.1xx%20-%3E%20master_x64_ubuntu%2018.04/System.Collections.CreateAddAndRemove(Int32)_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_10_2020/release/3.1.1xx%20-%3E%20master_x64_ubuntu%2018.04/System.Collections.CreateAddAndRemove(Int32)_2.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_10_2020/release/3.1.1xx%20-%3E%20master_x64_ubuntu%2018.04/System.Collections.CreateAddAndRemove(Int32).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Collections.CreateAddAndRemove<Int32>*';
```
<details>

#### System.Collections.CreateAddAndRemove<Int32>.List(Size: 512)

```log
[10580.943 ; 11622.595) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[11622.595 ; 12410.161) | @@@@@@@@@
[12410.161 ; 12754.842) | 
[12754.842 ; 13542.407) | @@@@@@@@@@@@@@@@@@@@@@@
[13542.407 ; 14082.740) | 
[14082.740 ; 14756.791) | @@@@@@
[14756.791 ; 15544.356) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[15544.356 ; 16323.314) | @@@@@@@@@@@@@@@@@
[16323.314 ; 16859.957) | @@@
```
#### System.Collections.CreateAddAndRemove<Int32>.SortedList(Size: 512)

```log
[72393.597 ; 75678.155) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[75678.155 ; 78041.146) | @@@@@@
[78041.146 ; 81949.877) | @@@@@@
[81949.877 ; 85234.435) | @@@@@@@@@@@@@@@@
[85234.435 ; 87239.391) | @@@@@@
[87239.391 ; 90717.307) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[90717.307 ; 94001.865) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[94001.865 ; 97426.333) | @@@@@@@@@@@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by danmosemsft** [comment] 2020-08-01 00:53
Duplicate of #39112

**Closed by danmosemsft** 2020-08-01 00:53 UTC
Labels: arch-x64, area-System.Collections, os-linux, tenet-performance, tenet-performance-benchmarks, untriaged
