### ISSUE TITLE
Can we custom the ConsoleLogger output color by configuration?

### ISSUE THREAD

**Issue by lindexi** [dotnet/runtime#38321] opened 2020-06-24 07:32 UTC
I want to custom the ConsoleLogger output color, such as we can use the Blue color as the info color and use the white-black color as the warning color

As we know, we can only do it by re-write a new custom console logger, and we can not use configuration to do custom it.

https://github.com/dotnet/runtime/blob/d908270add914db0e9fb3ce72e93c410e8f0f95a/src/libraries/Microsoft.Extensions.Logging.Console/src/ConsoleLogger.cs#L279-L292

As you can see, can we make this code read from configuration replace the hard code

Related issues: #37421 #33980

**Comment by maryamariyan** [comment] 2020-07-09 18:30
Dupe of #34742. Your issue would be covered by this.

Once the feature is complete you would basically write your own custom Console Formatter.

**Closed by maryamariyan** 2020-07-09 18:30 UTC
Labels: area-Extensions-Logging

**Comment by lindexi** [comment] 2020-07-10 01:08
@maryamariyan  Thank you
