### ISSUE TITLE
Type.GetProperties does not return non-public properties from inherited type on Android

### ISSUE THREAD

**Issue by Ropack** [dotnet/runtime#86149] opened 2023-05-11 06:31 UTC
### Description

_This may be bug of some underlying framework/runtime, possibly Mono. If this is not appropriate repo to file this issue in, please direct me to correct one._

During upgrade from Xamarin.Forms to MAUI we discovered odd bug. Reflection after upgrade is not behaving the same as before. When getting all properties for a type, including the non-public ones, the protected properties declared in inherited type are not returned. 

As described in the repro steps as well as in linked repro project, when declaring type Foo, that inherits from type Bar, the properties returned by `GetProperties` method does not include non-public properties declared in Bar even though the BindingFlags specify that they should. 

Issue is experienced only in Android, when the same app is run in Windows, it returns expected results.

### Steps to Reproduce

1. Create new MAUI App
2. Create two types with public and private properties, one inherited from another
``` csharp
public class Foo : Bar
{
    public string PublicFromFoo { get; set; }
    private string PrivateFromFoo { get; set; }
}

public class Bar
{
    public string PublicFromBar { get; set; }
    protected string ProtectedFromBar { get; set; }
}
```
3. In MainPage add code, that should get all properties from type Foo
`var properties = typeof(Foo).GetProperties(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);` `

Expected result: properties is array with Length 4
Actual result: properties is array with Length 3

### Link to public reproduction project repository

https://github.com/Ropack/MauiReflectionBugRepro

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

**Comment by ivanpovazan** [comment] 2023-05-24 11:51
@Ropack thank you for providing a detailed repro steps.

I have managed to reproduce the issue with: `dotnet 7.0.100`
However, when I tried it with: `dotnet 8.0.100-preview.3.23178.7` the message correctly shows there are 4 properties, meaning that the issue seems to be fixed in the meantime.

Would you mind trying it yourself with .NET8? 

I will try to find which PR got it fixed and check if the fix is going to be backported to .NET7.

**Comment by Ropack** [comment] 2023-06-22 08:33
@ivanpovazan sorry for a late reply. I can confirm that this is fixed in .net8.0, tried with `8.0.100-preview.4.23260.5`, thank you for investigating.

**Comment by ivanpovazan** [comment] 2023-06-22 08:49
No worries and thank you for the confirmation!
The fix will also be backported to .net7, so will keep the issue open until it is fully merge in .net7 branch.

**Comment by ivanpovazan** [comment] 2023-06-30 14:03
Closing as the fix has been backported to .net7 via: https://github.com/dotnet/runtime/pull/87175

**Closed by ivanpovazan** 2023-06-30 14:03 UTC
Labels: area-VM-reflection-mono
