### ISSUE TITLE
System.Data.Common.Tests tests failing on iOS and tvOS

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#36879] opened 2020-05-22 14:45 UTC
### System.Data.Common.Tests:
System.Data.Common.DbProviderFactoriesTests.RegisterFactoryWithTypeNameTest
System.Data.Common.DbProviderFactoriesTests.TryGetFactoryTest
System.Data.Common.DbProviderFactoriesTests.RegisterFactoryWithAssemblyQualifiedNameTest
System.Data.Common.DbProviderFactoriesTests.RegisterFactoryWithInstanceTest
System.Data.Common.DbProviderFactoriesTests.RegisterFactoryWithBadInvariantNameTest
System.Data.Common.DbProviderFactoriesTests.GetProviderInvariantNamesTest
System.Data.Common.DbProviderFactoriesTests.GetFactoryWithDbConnectionTest
System.Data.Common.DbProviderFactoriesTests.ReplaceFactoryWithRegisterFactoryWithTypeTest
System.Data.Common.DbProviderFactoriesTests.UnregisterFactoryTest
System.Data.Common.DbProviderFactoriesTests.GetFactoryWithInvariantNameTest
System.Data.Common.DbProviderFactoriesTests.RegisterFactoryWithTypeTest
System.Data.Common.DbProviderFactoriesTests.GetFactoryWithDataRowTest

```
System.Data.Common.Tests.dll   Failed: 12

Test collection for System.Data.Common.DbProviderFactoriesTests
System.Data.Common.DbProviderFactoriesTests.RegisterFactoryWithTypeNameTest
    System.InvalidOperationException : The requested .NET Data Provider's implementation does not have an Instance field of a System.Data.Common.DbProviderFactory derived type.
System.Data.Common.DbProviderFactoriesTests.TryGetFactoryTest
    System.ArgumentNullException : Value cannot be null. (Parameter 'factory')
System.Data.Common.DbProviderFactoriesTests.RegisterFactoryWithAssemblyQualifiedNameTest
    System.InvalidOperationException : The requested .NET Data Provider's implementation does not have an Instance field of a System.Data.Common.DbProviderFactory derived type.
System.Data.Common.DbProviderFactoriesTests.RegisterFactoryWithInstanceTest
    System.ArgumentNullException : Value cannot be null. (Parameter 'factory')
System.Data.Common.DbProviderFactoriesTests.RegisterFactoryWithBadInvariantNameTest
    Assert.Throws() Failure\nExpected: typeof(System.ArgumentException)\nActual:   typeof(System.InvalidOperationException): The requested .NET Data Provider's implementation does not have an Instance field of a System.Data.Common.DbProviderFactory derived type.\n---- System.InvalidOperationException : The requested .NET Data Provider's implementation does not have an Instance field of a System.Data.Common.DbProviderFactory derived type.
System.Data.Common.DbProviderFactoriesTests.GetProviderInvariantNamesTest
    System.InvalidOperationException : The requested .NET Data Provider's implementation does not have an Instance field of a System.Data.Common.DbProviderFactory derived type.
System.Data.Common.DbProviderFactoriesTests.GetFactoryWithDbConnectionTest
    System.InvalidOperationException : The requested .NET Data Provider's implementation does not have an Instance field of a System.Data.Common.DbProviderFactory derived type.
System.Data.Common.DbProviderFactoriesTests.ReplaceFactoryWithRegisterFactoryWithTypeTest
    System.InvalidOperationException : The requested .NET Data Provider's implementation does not have an Instance field of a System.Data.Common.DbProviderFactory derived type.
System.Data.Common.DbProviderFactoriesTests.UnregisterFactoryTest
    System.ArgumentNullException : Value cannot be null. (Parameter 'factory')
System.Data.Common.DbProviderFactoriesTests.GetFactoryWithInvariantNameTest
    System.InvalidOperationException : The requested .NET Data Provider's implementation does not have an Instance field of a System.Data.Common.DbProviderFactory derived type.
System.Data.Common.DbProviderFactoriesTests.RegisterFactoryWithTypeTest
    System.InvalidOperationException : The requested .NET Data Provider's implementation does not have an Instance field of a System.Data.Common.DbProviderFactory derived type.
System.Data.Common.DbProviderFactoriesTests.GetFactoryWithDataRowTest
    System.InvalidOperationException : The requested .NET Data Provider's implementation does not have an Instance field of a System.Data.Common.DbProviderFactory derived type.

**Comment by danmosemsft** [comment] 2020-05-23 02:23
Mostly
`<![CDATA[System.Globalization.CultureNotFoundException : Culture is not supported. (Parameter 'culture')\n4108 (0x100c) is an invalid culture identifier.]]>`
with various cultures, and a few 
`<![CDATA[System.IO.FileNotFoundException : Could not load file or assembly 'System.Data.SqlClient, Version=4.6.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.]]>`
or `<![CDATA[System.TypeLoadException : Could not load type 'Microsoft.SqlServer.Server.SqlMetaData' from assembly 'System.Data, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.]]>`

**Comment by ajcvickers** [comment] 2020-06-22 22:41
Moving to the SqlClient area since the tests are attempting to load SQL-specific assemblies. /cc @cheenamalhotra

**Comment by cheenamalhotra** [comment] 2020-06-22 23:01
Hi @mdh1418 

Please provide us more info:
- Have you always seen these failures with System.Data.SqlClient in this environment or has something changed recently that is leading to these issues?
- Could you reproduce the issues in a standalone console app and upload here - that would be easier to diagnose.

cc @saurabh500

**Comment by danmosemsft** [comment] 2020-06-23 03:00
@ajcvickers @cheenamalhotra please disregard this issue. Any and all issues tagged os-ios or os-android can be ignored for 5.0. (Apologies for not communicating this broadly enough.)

Only @safern is looking at these. Besides, any fixes here are likely outside of System.Data.

**Comment by danmosemsft** [comment] 2020-06-23 03:02
Eh, I think the glob issue already has an issue tracking it..

**Comment by mdh1418** [comment] 2022-07-18 16:55
As of commit 349d8113bab, the tests pass on iOSSimulator x64 Debug. I'll have to check device at another point when I have a iOS device available.

**Closed** 2022-07-26 13:50 UTC
Labels: area-System.Data.SqlClient, os-ios, os-tvos, in-pr
