### ISSUE TITLE
[HttpStress] massive timeouts around HTTP/3 stress test startup

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#77126] opened 2022-10-17 19:49 UTC
This happened 3 times in the past 4 weeks, `main` and `release/7.0` are both affected:
- [09/24](https://dev.azure.com/dnceng-public/public/_build/results?buildId=28755&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=1451f5f3-0108-5a08-5b92-e984b2a85bbd)
- [09/26](https://dev.azure.com/dnceng-public/public/_build/results?buildId=30067&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=1451f5f3-0108-5a08-5b92-e984b2a85bbd)
- [10/10](https://dev.azure.com/dnceng-public/public/_build/results?buildId=46233&view=logs&j=22fea640-1099-5f32-ec5d-316ad83f359a&t=a923b061-8445-5c16-cd6e-848990587cb0)

Looks like sometimes the stress server is unresponsive for a long time around startup in these cases.

**Comment by CarnaViire** [comment] 2022-10-18 14:49
I've seen this happening on local runs as well; we suspected it might be related to https://github.com/dotnet/runtime/issues/55979

**Comment by ManickaP** [comment] 2022-11-01 18:24
Triage: we should investigate to confirm if it's https://github.com/dotnet/runtime/issues/55979. Either way, we should at least put a mitigation in stress to not to fail the test in this case.

**Comment by antonfirsov** [comment] 2023-05-23 16:46
Unfortunately, this is still happening :( Looks like #84793 didn't help, there were at least 3 occurrences in the last 30 days:

- https://dev.azure.com/dnceng-public/public/_build/results?buildId=280888&view=logs&j=22fea640-1099-5f32-ec5d-316ad83f359a&t=a923b061-8445-5c16-cd6e-848990587cb0
- https://dev.azure.com/dnceng-public/public/_build/results?buildId=257086&view=logs&j=22fea640-1099-5f32-ec5d-316ad83f359a&t=a923b061-8445-5c16-cd6e-848990587cb0
- https://dev.azure.com/dnceng-public/public/_build/results?buildId=254739&view=logs&j=22fea640-1099-5f32-ec5d-316ad83f359a&t=a923b061-8445-5c16-cd6e-848990587cb0

Could it be a server-side issue?

<details>

```
System.Net.Http.HttpRequestException: Requesting HTTP version 3.0 with version policy RequestVersionExact while unable to establish HTTP/3 connection.
client_1  |  ---> System.Net.Http.HttpRequestException: The operation was canceled. (server:5001)
client_1  |  ---> System.OperationCanceledException: The operation was canceled.
client_1  |    at System.Net.Quic.ValueTaskSource.TryComplete(Exception exception) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ValueTaskSource.cs:line 119
client_1  |    at System.Net.Quic.ValueTaskSource.TrySetException(Exception exception) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ValueTaskSource.cs:line 166
client_1  |    at System.Net.Quic.ValueTaskSource.<>c.<TryInitialize>b__10_0(Object obj, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ValueTaskSource.cs:line 70
client_1  |    at System.Threading.CancellationTokenSource.Invoke(Delegate d, Object state, CancellationTokenSource source) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs:line 981
client_1  |    at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs:line 806
client_1  |    at System.Threading.CancellationTokenSource.Invoke(Delegate d, Object state, CancellationTokenSource source) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs:line 977
client_1  |    at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs:line 806
client_1  |    at HttpStress.RequestContext.SendAsync(HttpRequestMessage request, HttpCompletionOption httpCompletion, Nullable`1 token) in /app/ClientOperations.cs:line 89
client_1  |    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 38
client_1  |    at HttpStress.RequestContext.SendAsync(HttpRequestMessage request, HttpCompletionOption httpCompletion, Nullable`1 token)
client_1  |    at HttpStress.ClientOperations.<>c.<<get_Operations>b__1_0>d.MoveNext() in /app/ClientOperations.cs:line 193
client_1  |    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 38
client_1  |    at HttpStress.ClientOperations.<>c.<get_Operations>b__1_0(RequestContext ctx)
client_1  |    at HttpStress.StressClient.<>c__DisplayClass17_0.<<StartCore>g__RunWorker|0>d.MoveNext() in /app/StressClient.cs:line 204
client_1  |    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 38
client_1  |    at HttpStress.StressClient.<>c__DisplayClass17_0.<StartCore>g__RunWorker|0(Int32 taskNum)
client_1  |    at System.Linq.Enumerable.SelectRangeIterator`1.Fill(Span`1 results, Int32 start, Func`2 func) in /_/src/libraries/System.Linq/src/System/Linq/Select.SpeedOpt.cs:line 227
client_1  |    at System.Linq.Enumerable.SelectRangeIterator`1.ToArray() in /_/src/libraries/System.Linq/src/System/Linq/Select.SpeedOpt.cs:line 210
client_1  |    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source) in /_/src/libraries/System.Linq/src/System/Linq/ToCollection.cs:line 17
client_1  |    at HttpStress.StressClient.StartCore() in /app/StressClient.cs:line 184
client_1  |    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 38
client_1  |    at HttpStress.StressClient.StartCore()
client_1  |    at HttpStress.StressClient.Start() in /app/StressClient.cs:line 92
client_1  |    at HttpStress.Program.Run(Configuration config) in /app/Program.cs:line 197
```

</detalis>

**Comment by ManickaP** [comment] 2023-06-22 14:19
Revert of the hack is up in https://github.com/dotnet/runtime/pull/87926. When it starts manifesting in the original way, we can mitigate that with targeted error handling.

**Comment by ManickaP** [comment] 2023-06-23 08:01
Looking at the error in more detail, this is something else. It's not timeout. If you look bellow the exception you can see it's mostly not cancelled and very fast:
```
Duration: 00:00:00.0010132, Cancelled: False
```
All three errors are the same, just coming from a different operation and they are the same with or without the hack. This is completely new problem that might have started occurring at similar time as we merged https://github.com/dotnet/runtime/pull/84793. But right know I'm not convinced this was caused by this.

Also, AFAIR, the original error was the server dropping connections due to overload, i.e. `System.Net.Quic.QuicException : Connection has been shutdown by transport. Error Code: CONNECTION_REFUSED`. I will re-close this issue and create a new one for the cancellation error we're now seeing.

**Closed by ManickaP** 2023-06-23 08:01 UTC
Labels: area-System.Net.Http, test-bug
