### ISSUE TITLE
[API Proposal]: Generic type in Math

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#85066] opened 2023-04-19 20:03 UTC
### Background and motivation

https://learn.microsoft.com/uk-ua/dotnet/api/system.math?view=net-7.0
https://github.com/Mr0N/example
I suggest adding new methods to Math with generic types.

### API Proposal

```csharp
Math.Sqrt((byte)21);
class Math
{
    public static T Sqrt<T>(T value) where T:INumber<T>
    {
        throw new Exception();
    }
}
```

### API Usage

```csharp
Math.Sqrt((byte)21);
```

**Comment by Mr0N** [comment] 2023-04-19 20:09
For almost all methods of the Math class

**Comment by skyoxZ** [comment] 2023-04-20 01:28
Could give an example how to implement these methods such as `Math.Sqrt`?

**Comment by huoyaoyuan** [comment] 2023-04-20 02:03
Duplicate of #63732.

**Comment by danmoseley** [comment] 2023-04-20 03:29
@Mr0N in your own code, what are the types you have needed to calculate a square root for?

**Comment by Mr0N** [comment] 2023-04-20 18:27
> @Mr0N in your own code, what are the types you have needed to calculate a square root for?

well, I gave this method as an example, I am talking about other methods from this class

**Comment by Mr0N** [comment] 2023-04-20 18:28
> Could you give an example how to implement these methods such as `Math.Sqrt`?

no, I'm not much of a mathematician)

**Comment by teo-tsirpanis** [comment] 2023-04-20 23:50
Closing as duplicate of #63732. Taking the square root is only supported in floating-point numbers. Your generic needs to be constrained on `IFloatingPointIeee754<T>` (or `IRootFunctions<T>` strictly speaking).

**Closed by teo-tsirpanis** 2023-04-20 23:50 UTC
Labels: api-suggestion, area-System.Numerics, untriaged
