### ISSUE TITLE
Unable to inject IKeyedServiceProvider into service with .NET 8 Preview 7

### ISSUE THREAD

**Issue by WestDiscGolf** [dotnet/runtime#90528] opened 2023-08-14 16:59 UTC
### Description

The update to dependency injection to allow for Keyed Services really interested me so I had a play.

I am unable to resolve a service which has a dependency on `IKeyedServiceProvider` to then try and resolve a named dependency at runtime.

This works (as it has done for years!)

```
    [Fact]
    public void SimpleServiceProviderResolution()
    {
        // Arrange
        var services = new ServiceCollection();
        services.AddTransient<ServiceProviderService>();
        var sp = services.BuildServiceProvider();

        // Act
        var result = sp.GetService<ServiceProviderService>();

        // Assert
        result.ServiceProvider.Should().NotBeNull();
    }
```
With the following Service definition

```
public class ServiceProviderService
{
    private readonly IServiceProvider _serviceProvider;

    public ServiceProviderService(IServiceProvider serviceProvider)
    {
        _serviceProvider = serviceProvider;
    }

    public IServiceProvider ServiceProvider => _serviceProvider;
}
```
In the reproduction steps I am unable to take a Service which has a dependency on `IKeyedServiceProvider` as it does not appear to be automatically registered when the service provider is built in the same way the `IServiceProvider` is registered.

### Reproduction Steps

```
namespace KeyedServicePlayground;

public class DynamicResolvedDependencyTests
{
    [Fact]
    public void SimpleServiceKeyedResolution()
    {
        // Arrange
        var services = new ServiceCollection();
        services.AddKeyedTransient<ISimpleService, SimpleService>("simple");
        services.AddKeyedTransient<ISimpleService, AnotherSimpleService>("another");
        services.AddTransient<SimpleParentWithDynamicKeyedService>();
        var sp = services.BuildServiceProvider();
        var sut = sp.GetService<SimpleParentWithDynamicKeyedService>();

        // Act
        var result = sut!.GetService("simple");

        // Assert
        result.Should().BeOfType<SimpleService>();
    }
}

public class SimpleParentWithDynamicKeyedService
{
    private readonly IKeyedServiceProvider _serviceProvider;

    public SimpleParentWithDynamicKeyedService(IKeyedServiceProvider serviceProvider)
    {
        _serviceProvider = serviceProvider;
    }

    public ISimpleService GetService(string name) => _serviceProvider.GetKeyedService<ISimpleService>(name)!;
}

public interface ISimpleService { }

public class SimpleService : ISimpleService { }

public class AnotherSimpleService : ISimpleService { }
```

### Expected behavior

The keyed service which has been registered with the name "simple" is resolved and returned from the `GetService` method on the `SimpleParentWithDynamicKeyedService` instance.

### Actual behavior

Exception thrown:

```

System.InvalidOperationException
Unable to resolve service for type 'Microsoft.Extensions.DependencyInjection.IKeyedServiceProvider' while attempting to activate 'KeyedServicePlayground.SimpleParentWithDynamicKeyedService'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(ServiceIdentifier serviceIdentifier, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, ServiceIdentifier serviceIdentifier, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceIdentifier serviceIdentifier, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at KeyedServicePlayground.DynamicResolvedDependencyTests.SimpleServiceKeyedResolution() in C:\Users\<username_redacted>\source\repos\KeyedServicePlayground\KeyedServicePlayground\DirectServiceRequestTests.cs:line 155
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by steveharter** [comment] 2023-08-14 21:24
Note the repro above does not require transient services; singleton repros as well.

@benjaminpetit I believe `CallSiteFactory.TryCreateExact(...)` should result in the IKeyedService being returned but doesn't.

**Comment by benjaminpetit** [comment] 2023-08-15 13:17
We didn't expected the user to use `IKeyedServiceProvider` directly,all extensions methods target `IServiceProvider` for example.

But I guess we could add it to the list of "built in services", like we do today for `IServiceProvider`.

**Comment by benjaminpetit** [comment] 2023-08-16 09:11
It was fixed here: https://github.com/dotnet/runtime/pull/89509, I don't repro this issue with a more recent build.

**Comment by benjaminpetit** [comment] 2023-08-16 14:18
No backport for preview 7 was done, it will be included in the next preview release.

**Comment by steveharter** [comment] 2023-08-16 14:48
Closing as by design (must inject `IServiceProvider`, not `IKeyedServiceProvider`) and previously fixed (cannot use `GetKeyedService` when using `IServiceProvider` that was resolved from DI).

**Closed by steveharter** 2023-08-16 14:48 UTC
Labels: regression-from-last-release, area-Extensions-DependencyInjection

**Comment by WestDiscGolf** [comment] 2023-08-17 08:35
In case anyone else stumbles across this issue in preview 7 Andrew Lock demonstrates it well in this blog post - https://andrewlock.net/exploring-the-dotnet-8-preview-keyed-services-dependency-injection-support/#limitations-with-the-current-implementation
