### ISSUE TITLE
Test failure: Interop\\PInvoke\\Delegate\\DelegateTest\\DelegateTest.cmd

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#39934] opened 2020-07-26 18:05 UTC
CoreCLR Windows_NT x86 Checked gcstress0xc_zapdisable_jitstress2

```
    Interop\PInvoke\Delegate\DelegateTest\DelegateTest.cmd [FAIL]
      
      Assert failure(PID 9092 [0x00002384], Thread: 3112 [0x0c28]): gcHappened
      
      CORECLR! checkAndUpdateReg + 0x2D (0x6ef60b97)
      CORECLR! DoGcStress + 0x341 (0x6ef5fe86)
      CORECLR! OnGcCoverageInterrupt + 0x15A (0x6ef603c8)
      CORECLR! IsGcMarker + 0x93 (0x6eda52f5)
      CORECLR! CLRVectoredExceptionHandlerShim + 0xC5 (0x6ed9a805)
      NTDLL! WinSqmEventWrite + 0x1C907 (0x776a0317)
      NTDLL! RtlUnwind + 0x1BA (0x776603ea)
      NTDLL! KiUserExceptionDispatcher + 0xF (0x7767108f)
      <no module>! <no symbol> + 0x0 (0x0458532d)
      <no module>! <no symbol> + 0x0 (0x0819de62)
          File: F:\workspace\_work\1\s\src\coreclr\src\vm\gccover.cpp Line: 1173
          Image: C:\h\w\B30D094F\p\CoreRun.exe
      
      
      Return code:      1
```

https://dev.azure.com/dnceng/public/_build/results?buildId=745918&view=ms.vss-test-web.build-test-results-tab&runId=23119160&paneView=debug&resultId=102664

Looks like an x86 GC infrastructure issue.

cc @janvorli @AndyAyersMS

**Comment by BruceForstall** [comment] 2020-07-26 18:07
Another failure that looks related (assert is on the next line from the assert shown above):

CoreCLR Windows_NT x86 Checked gcstress0xc_zapdisable_heapverify1

```
    Interop\ExecInDefAppDom\ExecInDefAppDom\ExecInDefAppDom.cmd [FAIL]
      
      Assert failure(PID 3300 [0x00000ce4], Thread: 10776 [0x2a18]): GCHeapUtilities::GetGCHeap()->IsHeapPointer((BYTE*) size_t(origVal))
      
      CORECLR! checkAndUpdateReg + 0x65 (0x6e930bcf)
      CORECLR! DoGcStress + 0x341 (0x6e92fe86)
      CORECLR! OnGcCoverageInterrupt + 0x15A (0x6e9303c8)
      CORECLR! IsGcMarker + 0x93 (0x6e7752f5)
      CORECLR! CLRVectoredExceptionHandlerShim + 0xC5 (0x6e76a805)
      NTDLL! WinSqmEventWrite + 0x1C907 (0x76f80317)
      NTDLL! RtlUnwind + 0x1BA (0x76f403ea)
      NTDLL! KiUserExceptionDispatcher + 0xF (0x76f5108f)
      <no module>! <no symbol> + 0x0 (0x08e93c56)
      CORECLR! CallDescrWorkerInternal + 0x34 (0x6ebac411)
          File: F:\workspace\_work\1\s\src\coreclr\src\vm\gccover.cpp Line: 1174
          Image: C:\h\w\8D9307F9\p\CoreRun.exe
      
      
      Return code:      1
```

https://dev.azure.com/dnceng/public/_build/results?buildId=745918&view=ms.vss-test-web.build-test-results-tab&runId=23119162&paneView=debug

**Comment by davidwrighton** [comment] 2020-08-06 00:18
This is a duplicate of #39571

**Closed** 2020-08-06 00:18 UTC
Labels: GCStress, arch-x86, area-VM-coreclr, os-windows
