### ISSUE TITLE
[API Proposal]: Provide a way to resolve native P/Invoke method names

### ISSUE THREAD

**Issue by msedi** [dotnet/runtime#59830] opened 2021-09-30 21:32 UTC
### Background and motivation

With the NativeLibrary it is now possible to attach a handler to resolve the native library name, by using the NativeLibrary.SetDllImportResolver which is really essential when trying to make the library runnable on many OSses.

Another problem is though, that something similar would be needed when it comes to the resolution of native methods.
Some vendors for example deliver their own GetProcAddress methods. For example: CUDA has cuGetProcessAddress, with a different method signature than the regular GetProcAddress. Vulkan has something similar (here as far as I remember not even only one for the whole library, but one for each level). Sometimes method names are named differently for linux or windows.

### API Proposal

So I propose a possibility to add a method to be able to intercept the retrieval of the internal GetProcessAddress and allow to override it with your own handler. There are two ideas where this could happen.

1. In NativeLibrary
A global NativeLibrary.SetGetExportResolver as it is done with NativeLibrary.SetDllImportResolver.
The handler would look like this (there is surely more, like calling convention and a few other things that are given in the DllImport or DllImportAttribute or some derivation is directly handed over in the parameter list.

public IntPtr ResolveExportHandler(string libraryName, string symbol)

2. In DllImport
You can directly hand-over a static resolver method that follows the same handler rules as above, but you can more precisly control the resolution.

Depending on where the handler is placed, if null i returned the default action is used.

### API Usage

```C#
NativeLibrary.SetGetExportResolver(ResolveExportHandler)

[DllImport("vulkan")]
public extern static void vkGetProcAddress(IntPtr handle, string symbolName);

public IntPtr ResolveExportHandler(IntPtr handle, string libraryName, string symbol)
{
  if(libraryName = "vulkan")
    return vkGetProcAddress(handle, symbol);

  return NativeLibrary.GetExport(handle, symbol);
}
```     

### Risks

I assume there might be performance issues so I'm not quite sure what would be the best option.

**Comment by jkoritzinsky** [comment] 2021-09-30 22:14
This is a duplicate of https://github.com/dotnet/runtime/issues/1906

**Closed** 2021-09-30 22:50 UTC
Labels: api-suggestion, area-Interop-coreclr, untriaged
