### ISSUE TITLE
Test failure:JIT/Regression/JitBlue/Runtime_39424/Runtime_39424/Runtime_39424.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#107008] opened 2024-08-27 01:27 UTC
**Failed in:** [runtime-coreclr r2r-extra 20240825.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=787917&view=ms.vss-test-web.build-test-results-tab&runId=20243018&resultId=122465&paneView=debug)

**Failed tests:**
```
R2R-CG2 osx arm64 Checked jitstressregs3 @ OSX.1200.ARM64.Open
    - JIT/Regression/JitBlue/Runtime_39424/Runtime_39424/Runtime_39424.cmd
```

**Error message:**
```
 /private/tmp/helix/working/A5AF08F9/w/B0BE0965/e/JIT/Regression/Regression_2/../JitBlue/Runtime_39424/Runtime_39424/Runtime_39424.sh: line 316: -r:/private/tmp/helix/working/A5AF08F9/w/B0BE0965/e/JIT/Regression/JitBlue/Runtime_39424/Runtime_39424/IL-CG2/*.dll: No such file or directory
DOTNET_DbgEnableMiniDump is set and the createdump binary does not exist: /private/tmp/helix/working/A5AF08F9/p/crossgen2/createdump
/private/tmp/helix/working/A5AF08F9/w/B0BE0965/e/JIT/Regression/Regression_2/../JitBlue/Runtime_39424/Runtime_39424/Runtime_39424.sh: line 254: 39791 Segmentation fault: 11  (core dumped) $__Command

Return code:      1
Raw output file:      /tmp/helix/working/A5AF08F9/w/B0BE0965/uploads/JitBlue/Runtime_39424/Runtime_39424/output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/private/tmp/helix/working/A5AF08F9/w/B0BE0965/e/JIT/Regression/JitBlue/Runtime_39424/Runtime_39424/IL-CG2/Runtime_39424.dll
20:42:55
Response file: /private/tmp/helix/working/A5AF08F9/w/B0BE0965/e/JIT/Regression/JitBlue/Runtime_39424/Runtime_39424/Runtime_39424.dll.rsp
/private/tmp/helix/working/A5AF08F9/w/B0BE0965/e/JIT/Regression/JitBlue/Runtime_39424/Runtime_39424/IL-CG2/Runtime_39424.dll
-o:/private/tmp/helix/working/A5AF08F9/w/B0BE0965/e/JIT/Regression/JitBlue/Runtime_39424/Runtime_39424/Runtime_39424.dll
-r:/tmp/helix/working/A5AF08F9/p/System.*.dll
-r:/tmp/helix/working/A5AF08F9/p/Microsoft.*.dll
-r:/tmp/helix/working/A5AF08F9/p/xunit.*.dll
-r:/tmp/helix/working/A5AF08F9/p/mscorlib.dll
--verify-type-and-field-layout
--method-layout:random
--targetarch:arm64
--targetos:osx
Running CrossGen2:  /tmp/helix/working/A5AF08F9/p/crossgen2/crossgen2 @/private/tmp/helix/working/A5AF08F9/w/B0BE0965/e/JIT/Regression/JitBlue/Runtime_39424/Runtime_39424/Runtime_39424.dll.rsp  
Running R2RDump:  dotnet /tmp/helix/working/A5AF08F9/p/R2RDump/R2RDump.dll --header --sc --in /private/tmp/helix/working/A5AF08F9/w/B0BE0965/e/JIT/Regression/JitBlue/Runtime_39424/Runtime_39424/Runtime_39424.dll --out /private/tmp/helix/working/A5AF08F9/w/B0BE0965/e/JIT/Regression/JitBlue/Runtime_39424/Runtime_39424/Runtime_39424.dll.r2rdump --val
Error: System.BadImageFormatException: The file is not a ReadyToRun image
   at ILCompiler.Reflection.ReadyToRun.ReadyToRunReader.Initialize(IAssemblyMetadata metadata) in /_/src/coreclr/tools/aot/ILCompiler.Reflection.ReadyToRun/ReadyToRunReader.cs:line 467
   at R2RDump.Program.Run() in /_/src/coreclr/tools/r2rdump/Program.cs:line 449
20:43:06
Crossgen2 failed with exitcode: 139
in ReleaseLock
Test failed. Trying to see if dump file was created in /cores since 8/25/2024 8:42:54 PM
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> /private/tmp/helix/working/A5AF08F9/w/B0BE0965/e/JIT/Regression/Regression_2/../JitBlue/Runtime_39424/Runtime_39424/Runtime_39424.sh
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 128
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor522|0_523(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by ivdiazsa** [comment] 2024-09-03 16:52
Duplicate of issue #106675.

**Closed by ivdiazsa** 2024-09-03 16:52 UTC
Labels: arch-arm64, os-mac-os-x, JitStress, area-crossgen2-coreclr, untriaged, blocking-clean-ci-optional
