### ISSUE TITLE
Potential misunderstanding and misuses in Random.GetItems

### ISSUE THREAD

**Issue by khalidabuhakmeh** [dotnet/runtime#88247] opened 2023-06-30 13:06 UTC
### Description

The new `Random.Shared.GetItems` method will not get items in a mutually exclusive way. It retrieves items randomly by index, meaning the resulting random collection can include duplicate entries.

### Reproduction Steps

```csharp
var advocates = new[]
{
    "Maarten", "Matt",
    "Rachel", "Matthias",
    "Khalid"
};

Span<string> thunderdome = new string[2];
Random.Shared.GetItems(advocates, thunderdome);
```

Running this code can sometimes produce a collection of `[ Maarten, Maarten ]` or `[Khalid, Khalid]`.

This might confuse folks who think it produces a random and exclusive result. 

### Expected behavior

This may be the expected behavior, but adding an overload that provides a mutually exclusive result set would also be beneficial.

### Actual behavior

You get a resulting collection that may have duplicate entries.

### Known Workarounds

- Copy the existing collection to a new variable/memory space and then `Shuffle` and use `Take`
- Use LINQ to sort the collection by a Random value and then `Take` the number of items you need.

### Configuration

.NET 8 preview 5

**Comment by stephentoub** [comment] 2023-06-30 13:12
> The new Random.Shared.GetItems method will not get items in a mutually exclusive way. It retrieves items randomly by index, meaning the resulting random collection can include duplicate entries.

Correct. This is by design.  If your goal is to instead perform a random shuffling of the items, there's Shuffle.

**Comment by danmoseley** [comment] 2023-06-30 14:56
@khalidabuhakmeh Do you think the doc needs to be improved?

**Comment by khalidabuhakmeh** [comment] 2023-06-30 16:59
I guess it is there in the `<remarks>` tag. 😅

```xml
<remarks>
  The method uses <see cref="Next(int)" /> to select items randomly from <paramref name="choices" />
   by index. This is used to populate a newly-created array.
</remarks>
```

Although the `<return>` tag isn't clear as it used the term "random items".

```xml
<returns>An array populated with random items.</returns>
```

Maybe an additional note that says, "values in the newly-created array may be duplicated."

**Comment by tannergooding** [comment] 2023-08-14 18:32
Closing as by design. Docs contributions to improve clarity are always welcome.

**Closed by tannergooding** 2023-08-14 18:32 UTC
Labels: area-System.Runtime, untriaged

**Comment by VisualMelon** [comment] 2023-09-10 12:34
I think this definitely could do with a docs improvement. The remark isn't clear enough (it's describing an implementation detail, and strictly provides no specification), and it should be in the summary that it is a sampling with replacement. I'm happy to put a PR together for the various overloads changing the summaries the form

```
Fills the elements of a specified span with items chosen at random with replacement from the provided set of choices with replacement.
```

"With replacement" is a familiar and easily searchable term that qualified the behaviour. Should probably be explained in lay terms in the remarks (I'm not sure how best to phrase that, and apparently am incapable of coming up with writing something where the word "independent" doesn't create more chance for confusion, and IID is a bit cryptic)

This caught my attention in the .NET 8 change notes because the interpretation suggested in the OP for a without-replacement sampling is present in a number of other programming environments, e.g. Python's `random.sample` or PowerShell's `Get-Random` or C++'s `std::sample` (though their behaviour when the number of requested elements is longer than the sample population varies (e.g. python throws; pwsh truncates)); I'm not familiar with standard library implementations that sample with replacement that exist alongside these (not to say they don't exist, but it's very trivial so I assume deemed unnecessary and I can't find them with a cursory search), and I was consequently surprised that this was the behaviour of `GetItems`.

The name and behaviour of `GetItems` as-is fits in with e.g. `GetBytes`, though won't help someone who isn't familiar with the existing APIs understand the code; providing a well-named method for a sampling without replacement would help with disambiguation in the docs/intellisense, but personally I'd prefer the method was called `GetItemsWithReplacement` or similar so that it's totally unambiguous: a misunderstanding of the behaviour will create hard to trace bugs, because if you are e.g. trying to select 2 different elements from a list of a million, it's not going to give you duplicates very often.

I looked but couldn't find an API discussion for these methods: is there one about?
