### ISSUE TITLE
API documentation debt - System.Diagnostics

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#43860] opened 2020-10-26 23:34 UTC
Area owners: @noahfalk @tommcdon @tarekgh @Anipik @krwq 

The APIs in the list below are missing some or all of their documentation. I noticed these APIs are part of Platform Extensions, and were not added to the `dotnet-plat-ext-5.0` moniker. I am not sure if this means they are obsolete, so if they are unsupported, please let me know if you decide not to document them.

If you do decide to document them, feel free to document them in triple slash directly and we will make sure they get ported. If it's easier to get them documented in dotnet-api-docs, that is ok too.

Make sure to follow the documentation guidelines defined in the dotnet-api-docs wiki:
https://github.com/dotnet/dotnet-api-docs/wiki

Also please add me as a PR reviewer.

Community contributions are welcome.

<details>
  <summary>System.Diagnostics.DiagnosticListenerExtensions</summary>

  DocId | Summary | Parameters | TypeParameters | ReturnValue | Source File Path | Docs URL
  -- | -- | -- | -- | -- | -- | --
  T:System.Diagnostics.DiagnosticListenerExtensions | Missing | NA | NA | NA | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Diagnostics/DiagnosticListenerExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Diagnostics.DiagnosticListenerExtensions?branch=master
  M:System.Diagnostics.DiagnosticListenerExtensions.SubscribeWithAdapter(System.Diagnostics.DiagnosticListener,System.Object) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Diagnostics/DiagnosticListenerExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Diagnostics.DiagnosticListenerExtensions.SubscribeWithAdapter?branch=master
  M:System.Diagnostics.DiagnosticListenerExtensions.SubscribeWithAdapter(System.Diagnostics.DiagnosticListener,System.Object,System.Func{System.String,System.Boolean}) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Diagnostics/DiagnosticListenerExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Diagnostics.DiagnosticListenerExtensions.SubscribeWithAdapter?branch=master
  M:System.Diagnostics.DiagnosticListenerExtensions.SubscribeWithAdapter(System.Diagnostics.DiagnosticListener,System.Object,System.Func{System.String,System.Object,System.Object,System.Boolean}) | Missing | Missing | NA | Missing | https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Diagnostics/DiagnosticListenerExtensions.xml | https://review.docs.microsoft.com/en-us/dotnet/api/System.Diagnostics.DiagnosticListenerExtensions.SubscribeWithAdapter?branch=master

</details>

**Comment by noahfalk** [comment] 2021-07-28 21:56
@tarekgh @ericstj - do either of you recognize Microsoft.Extensions.DiagnosticAdapter assembly? According to the docs links that is the assembly which contains these APIs but I didn't find this type in our repo.

**Comment by tarekgh** [comment] 2021-07-28 22:12
@ericstj @Anipik @maryamariyan may know better about this one. I am seeing originally the code was in the extensions repo https://github.com/dotnet/extensions/blob/release/2.1/src/DiagnosticAdapter/src/DiagnosticListenerExtensions.cs but I don't from where we released the last version https://www.nuget.org/packages/Microsoft.Extensions.DiagnosticAdapter/5.0.0-preview.3.20215.2. Looks to me it is released as part of asp.net as the NuGet page indicate.

**Comment by ericstj** [comment] 2021-07-28 22:17
Per https://github.com/aspnet/Announcements/issues/411 that component was dead-ended.  The last place the code lived is here: https://github.com/dotnet/extensions/tree/release/3.1/src/DiagnosticAdapter

**Comment by noahfalk** [comment] 2021-07-29 02:55
Thanks all!

>  I am not sure if this means they are obsolete, so if they are unsupported, please let me know if you decide not to document them.

Based on info from @ericstj this assembly was last shipped in 3.1 and we've decided not to ship new releases. It is by design that there is no 5.0 version.

**Closed by noahfalk** 2021-07-29 02:55 UTC
Labels: area-System.Diagnostics, documentation, up-for-grabs
