### ISSUE TITLE
Unable to debug .NET 5 application after upgrading to macOS Big Sur

### ISSUE THREAD

**Issue by areller** [dotnet/runtime#45282] opened 2020-11-27 18:41 UTC
### Description

Recently, I've upgraded my mac to macOS Big Sur, now, I'm no longer able to debug .NET applications via vscode.
Whenever I try to attach a debugger, I get this error

```
Unable to attach to CoreCLR. Unknown Error: 0x80131c3c
```

![image](https://user-images.githubusercontent.com/15989650/100475142-5433f280-30b0-11eb-9f4f-060a0df257ef.png)

### Configuration

I'm running .NET 5.0.100 on macOS Big Sur (Macbook 2017 Pro, Intel x64)
This happens with any .NET application

### Regression?

I tried changing the target framework to `netcoreapp3.1` and got the same error.

### Other information

I read that some people have fixed a similar problem by downgrading XCode from v12 to v11, I tried it myself (downgraded to v11.7) but it didn't work

**Comment by tommcdon** [comment] 2020-11-29 02:17
@hoyosjs

**Comment by hoyosjs** [comment] 2020-11-29 02:20
This is a dupe of #423111. Closing in favor of that one.

**Closed** 2020-11-29 02:20 UTC
Labels: area-Diagnostics-coreclr
