### ISSUE TITLE
Test failure in Regressions\coreclr\9414\readonlyPrefix\readonlyPrefix.cmd

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#1782] opened 2020-01-15 22:24 UTC
Failure in Windows x86. Passes on x64.

Only fails with `COMPlus_JITMinOpts=1`.

```
F:\gh\runtime2\artifacts\tests\coreclr\Windows_NT.x86.Checked\Regressions\coreclr\9414\readonlyPrefix>readonlyPrefix.cmd -coreroot F:\gh\runtime2\artifacts\tests\coreclr\Windows_NT.x86.Checked\Tests\Core_Root
BEGIN EXECUTION
 "F:\gh\runtime2\artifacts\tests\coreclr\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" readonlyPrefix.dll
Unhandled exception. System.ArrayTypeMismatchException: Attempted to access an element as a type incompatible with the array.
   at Program.Foo`1.FrobAll(T[,] arr) in F:\gh\runtime2\src\coreclr\tests\src\Regressions\coreclr\9414\readonlyPrefix.cs:line 26
   at Program.Main() in F:\gh\runtime2\src\coreclr\tests\src\Regressions\coreclr\9414\readonlyPrefix.cs:line 33
Expected: 100
Actual: -532462766
END EXECUTION - FAILED
FAILED
```

**Comment by BruceForstall** [comment] 2020-01-15 22:54
@kouvel @dotnet/jit-contrib

**Comment by BruceForstall** [comment] 2020-01-15 23:37
In the minopts case, we don't inline the `call System.Object[,]:Address(int,int):byref:this`

Is this some fallout to #1201? @VSadov

**Comment by VSadov** [comment] 2020-01-15 23:40
Most likely. I will take a look..

**Comment by VSadov** [comment] 2020-01-15 23:41
If this is because of no inlining, would this fail in debug too?

**Comment by VSadov** [comment] 2020-01-16 00:03
Yes. I removed masking of the lower 2 bits, since arrays are not typedescs anymore, but that was also used as null check. 

Will have to add `test eax, eax`

**Comment by BruceForstall** [comment] 2020-01-16 00:33
> If this is because of no inlining, would this fail in debug too?

Depends if the VM tells us we can inline or not for the IL. C# debug compilations say no, I think. And with tiered compilation enabled, tier 0 is minopts.

**Comment by VSadov** [comment] 2020-01-16 04:15
Reproduces in Debug.

**Comment by VSadov** [comment] 2020-01-16 20:49
Fixed in https://github.com/dotnet/runtime/pull/1798

**Closed by VSadov** 2020-01-16 20:49 UTC
Labels: area-CodeGen

**Comment by BruceForstall** [comment] 2020-01-16 21:18
Thank you for the quick fix!
