### ISSUE TITLE
.NET 9 Assembly.GetCallingAssembly() In certain situations, the program may crash. Exit code is -1073740791

### ISSUE THREAD

**Issue by gaoyang** [dotnet/runtime#110261] opened 2024-11-29 07:19 UTC
### Description

Currently, it is only found that executing the` Assembly.GetCallingAssembly()` function in the catch block when an exception occurs in building the regular expression will cause the program to crash. Exit code is -1073740791

MacOS did not encounter this issue.
.NET 8 did not encounter this issue.

### Reproduction Steps

```c#
try
{
    var regex = new Regex("+123456$");
}
catch (Exception e)
{
    var callingAssembly = Assembly.GetCallingAssembly(); // Crash
}
```

### Expected behavior

This simple operation theoretically should not cause a crash.

### Actual behavior

Exit code is -1073740791

### Configuration

Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100\

Host:
  Version:      9.0.0
  Architecture: x64
  Commit:       9d5a6a9aa4

**Comment by jkotas** [comment] 2024-11-29 07:57
Thank you for reporting this issue. It is duplicate of https://github.com/dotnet/runtime/issues/109242 that is going to be fixed by https://github.com/dotnet/runtime/pull/109530 in one of the upcoming .NET 9 servicing updates.

**Closed by jkotas** 2024-11-29 07:57 UTC
Labels: area-VM-coreclr, untriaged
