### ISSUE TITLE
[Mono WASM] CoreCLR tests on WASM: tests depending on thread support failed

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#41472] opened 2020-08-27 20:15 UTC
### Description

The following tests are not passing because WASM doesn't support multithreading yet
1. Cannot start threads on this runtime
```
System.PlatformNotSupportedException: Cannot start threads on this runtime.
           at System.Threading.Thread.Start()
           at Precise.Driver.Main()
           at System.Threading.Thread.Start()
           at Precise.Driver.Main()
```
Affected tests are
- JIT/Methodical/cctor/misc/threads1_cs_do/threads1_cs_do.sh
- JIT/Performance/CodeQuality/BenchmarksGame/reverse-complement/reverse-complement-6/reverse-complement-6.sh
- baseservices/threading/DeadThreads/DeadThreads/DeadThreads.sh
- baseservices/threading/coverage/OSThreadId/osthreadid/osthreadid.sh
- JIT/CodeGenBringUpTests/LocallocLarge_d/LocallocLarge_d.s
- JIT/CodeGenBringUpTests/LocallocLarge_do/LocallocLarge_do.sh
- JIT/CodeGenBringUpTests/LocallocLarge_ro/LocallocLarge_ro.sh
- JIT/CodeGenBringUpTests/LocallocLarge_r/LocallocLarge_r.sh
- JIT/Regression/VS-ia64-JIT/V1.2-M01/b10827/b10827/b10827.sh
- JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b425314/b425314/b425314.sh
- JIT/Regression/JitBlue/Runtime_40444/Runtime_40444/Runtime_40444.sh
- JIT/Regression/CLR-x86-JIT/V1-M13-RTM/b99969/b99969/b99969.sh
- JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b426654/b426654/b426654.sh
- Loader/classloader/regressions/523654/test532654_b/test532654_b.sh
- Loader/classloader/TypeInitialization/CoreCLR/CircularCctorThreeThreads03/CircularCctorThreeThreads03.sh
- Loader/classloader/TypeInitialization/CircularCctors/CircularCctorFourThreadsBFI/CircularCctorFourThreadsBFI.sh
- JIT/jit64/opt/cse/VolatileTest_op_mul/VolatileTest_op_mul.sh
- JIT/jit64/opt/rngchk/ArrayWithThread_o/ArrayWithThread_o.sh
- GC/Scenarios/DoublinkList/dlbigleakthd/dlbigleakthd.sh
2. Cannot wait on monitors on this runtime
```
Exception:System.PlatformNotSupportedException: Cannot wait on monitors on this runtime.
           at System.Threading.Monitor.ObjWait(Boolean exitContext, Int32 millisecondsTimeout, Object obj)
           at System.Threading.Monitor.Wait(Object obj, Int32 millisecondsTimeout, Boolean exitContext)
           at System.Threading.Monitor.Wait(Object obj, Int32 millisecondsTimeout)
           at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
           at System.Threading.Tasks.Task.SpinThenBlockingWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
           at System.Threading.Tasks.Task.InternalWaitCore(Int32 millisecondsTimeout, CancellationToken cancellationToken)
           at System.Threading.Tasks.Task.InternalWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
           at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
           at System.Threading.Tasks.Task.Wait()
           at Program.Main(String[] args)
```
Affected tests are
- JIT/opt/Devirtualization/box2/box2.sh
- JIT/Performance/CodeQuality/BenchmarksGame/regex-redux/regex-redux-5/regex-redux-5.sh
- JIT/Performance/CodeQuality/BenchmarksGame/k-nucleotide/k-nucleotide-9/k-nucleotide-9.sh
- JIT/Regression/JitBlue/GitHub_27924/GitHub_27924/GitHub_27924.sh
- JIT/Performance/CodeQuality/BenchmarksGame/spectralnorm/spectralnorm-3/spectralnorm-3.sh
- JIT/Performance/CodeQuality/BenchmarksGame/binarytrees/binarytrees-5/binarytrees-5.sh
- JIT/Performance/CodeQuality/BenchmarksGame/fasta/fasta-1/fasta-1.sh
- JIT/Performance/CodeQuality/BenchmarksGame/mandelbrot/mandelbrot-7/mandelbrot-7.sh

### Reproduction Steps

1. Get dotnet/runtime repo
2. Remove the test(s) that you would like to reproduce from `<repo_root>/src/coreclr/tests/issues.targets`
2. Build WASM: `./build.sh --os Browser --arch wasm --subset mono+libs -c Release`
3. Build runtime tests: `cd src/coreclr/ && ./build-test.sh -skipstressdependencies -excludemonofailures os Browser wasm Release`
4. To run all runtime tests, at the end of the runtime tests build log, there is "Example runtest.sh command". Use that command plus `wasm`. For example, for me it was
`./tests/runtest.sh --coreOverlayDir=/Users/fanyang/Documents/work/dotnet_naricc/runtime/artifacts/tests/coreclr/Browser.wasm.Release/Tests/Core_Root --testNativeBinDir=/Users/fanyang/Documents/work/dotnet_naricc/runtime/artifacts/obj/coreclr/Browser.wasm.Release/tests --testRootDir=/Users/fanyang/Documents/work/dotnet_naricc/runtime/artifacts/tests/coreclr/Browser.wasm.Release --copyNativeTestBin Release wasm`
5. To run a single test, you could do
```
set CORE_ROOT=<repo_root>/artifacts/tests/coreclr/Browser.wasm.Release/Tests/Core_Root     
<repo_root>/artifacts/tests/coreclr/Browser.wasm.Release/JIT/Methodical/switch/switch5/switch5.sh
```

### Regression?

No. WASM is a new product.

**Comment by marek-safar** [comment] 2020-08-31 10:00
That's exected, these tests need to be excluded/disabled.

**Comment by SamMonoRT** [comment] 2021-06-21 15:38
These tests are excluded and we'll not support that in 6.0 - Moving to 7.0

**Comment by ilonatommy** [comment] 2022-06-10 07:15
@fanyang-mono, what's the status on this? Did they get disabled temporarily?

**Comment by fanyang-mono** [comment] 2022-06-10 14:00
@ilonatommy Yes, they were disabled. If you search this issue number in `issues.targets` file you can see the details. For example,
https://github.com/dotnet/runtime/blob/main/src/tests/issues.targets#L3290-L3294

**Closed** 2023-07-11 00:13 UTC
Labels: arch-wasm, area-VM-threading-mono

**Comment by lambdageek** [comment] 2023-10-24 17:09
I don't understand this issue:

1. It is used in src/tests/issues.targets to mark some tests.  But the issue is closed.  
2. It looks like a lot of the tests are not actually expected to work (for example tests that need multiple threads are not expected to work on wasm).  In that case they shouldn't be marked with a GH issue, IMO.
3. Actually the excluded tests are in `<ItemGroup Condition="'$(TargetArchitecture)' == 'wasm' or '$(TargetsAppleMobile)' == 'true'">` - so they're excluded on WASM, but also on AppleMobile?  Apple devices support threading - so why are the tests excluded?
4.

**Comment by kotlarmilos** [comment] 2023-10-24 20:58
When I attempted to enable Apple mobile runtime tests, I encountered similar failures as with wasm tests, so I disabled the same subset of tests. However, there is a possibility that some of them may actually pass on Apple mobile platforms. I will check them locally and if they do pass we can proceed with a PR.

**Comment by fanyang-mono** [comment] 2023-10-24 21:02
I will go through these tests for WASM to mark them properly.
