### ISSUE TITLE
[API Proposal]: Span based constructors for BitArray

### ISSUE THREAD

**Issue by alitas** [dotnet/runtime#89038] opened 2023-07-17 19:24 UTC
### Background and motivation

The current constructors for BitArray (`BitArray(byte[])` and `BitArray(int[])`) all copy values from the input to the internal array of the object. Converting a `Span<byte>` into a `BitArray` requires copying values into a temp byte array, which causes unnecessary allocations.  

### API Proposal

```csharp
namespace System.Collections;

public sealed class BitArray : ICollection, ICloneable
{
     public BitArray(ReadOnlySpan<byte> bytes) {}
     public BitArray(ReadOnlySpan<int> values) {}
}
```

### Current State
```csharp
// A large byte array
var bytes = new byte[65536];

// Copy relevant bytes into a temporary array
var tmpBytes = new byte[8];
bytes.AsSpan(0, 8).CopyTo(tmpBytes);

// Convert the first 8 bytes into a byte array
var bitArray = new BitArray(tmpBytes);
```

### After Proposed API Changes
```csharp
// A large byte array
var bytes = new byte[65536];

// Convert the first 8 bytes into a byte array
var bitArray = new BitArray(bytes.AsSpan(0, 8));
```

### Alternative Designs

Alternative designs may be constructors that take offset and count parameters such as `BitArray(byte[] bytes, int offset, int count)`.

### Risks

Depending on the implementation, a null input might construct an empty `BitArray` instead of throwing `ArgumentNullException` if a `byte[]` is implicitly converted to a `ReadOnlySpan<byte>`.

**Comment by stephentoub** [comment] 2023-07-17 20:19
Thanks. This is a duplicate of https://github.com/dotnet/runtime/issues/80263.

**Closed by stephentoub** 2023-07-17 20:19 UTC
Labels: api-suggestion, area-System.Collections, untriaged, in-pr
