### ISSUE TITLE
DateTime.TryParse allows invalid characters

### ISSUE THREAD

**Issue by pranavkm** [dotnet/runtime#39981] opened 2020-07-27 22:49 UTC
Noticed this when running our test suite:

```C#
static void Main(string[] args)
{
    var result = DateTime.TryParse("06/02A", out var converted);

    Console.WriteLine(result + " " + converted);
}
```

In 3.1, this produces

> False 1/1/0001 12:00:00 AM

In 5.0 (Runtime: 5.0.0-rc.1.20371.13), this produces

> True 6/2/2020 12:00:00 AM.

I'd thought it was treating the letter A as a cool new short form for AM, but that's not the case. Using any other letter results in a result comparable to 3.1. This is not blocking, just looked suspect.

**Comment by tarekgh** [comment] 2020-07-28 00:46
@pranavkm what is your current culture?

**Comment by pranavkm** [comment] 2020-07-28 00:49
`CultureInfo.CurrentCulture: en-US`

**Comment by safern** [comment] 2020-07-28 01:07
@tarekgh and I looked at this and the difference comes from the switch to use ICU on Windows by default. The reason why you're able to parse it successfully on 5.0 is because the `en-US` era name in ICU is `AD` and in NLS is `A.D` so the abbreviated era name in `ICU` is `A` and in NLS is `AD` because ICU doesn't contain `.` in the era name. 

Closing as this is by design in ICU.

**Closed by safern** 2020-07-28 01:07 UTC
Labels: area-System.Runtime, untriaged

**Comment by danmosemsft** [comment] 2020-07-31 18:56
@safern seems like we're getting an issue every week where folks spot differences caused by the ICU change. I wonder whether it's worth including several of these as examples into https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/globalization-icu (if not now then later)

**Comment by safern** [comment] 2020-08-03 17:44
> @safern seems like we're getting an issue every week where folks spot differences caused by the ICU change. I wonder whether it's worth including several of these as examples into

Thanks for the suggestion @danmosemsft -- I chatted with @tarekgh about this and we think it is not a good idea to document all the differences because data might change in ICU or even in NLS so it is not guaranteed that these behaviors will stay like that. However, we do think it might make sense to add some examples to the docs. I'll add it to my TODO list.
