### ISSUE TITLE
fsharp code gives incorrect result in .NET 6 when compiled in release.

### ISSUE THREAD

**Issue by sylvainouel** [dotnet/runtime#62103] opened 2021-11-28 02:02 UTC
The following code:

```
open System
type T2 () =
    member this.f b =
        if b = Unchecked.defaultof<Guid> then 
            failwith "Houlala gross problem!"
        else
            hash(b)

[<EntryPoint>]
let main args =
    try
        T2().f (Guid.NewGuid()) |> ignore
    with e -> printfn "%s" e.Message
    0
```

in the following project:

```

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>

```

gives an incorrect output when compiled in release. The exception is thrown.
The correct output is given when program is compiled in debug (eixt status of 0 without any output) or when compiled targeting .NET 5.

dotnet info output is:

 dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

**Comment by sylvainouel** [comment] 2021-11-28 03:31
Further simplification:
```
open System
let f b =
    if b = Unchecked.defaultof<Guid> then 
        failwith "Houlala gross problem!"
    else
        hash(b)

[<EntryPoint>]
let main args =
    try
        f (Guid.NewGuid()) |> ignore
    with e -> printfn "%s" e.Message
    0
```

**Comment by jakobbotsch** [comment] 2021-11-28 22:13
Looks like in .NET 6 we miss a zero-init of `xmm0`, but it does not repro in .NET 7. I bisected it to #58410.
cc @BruceForstall, potential backport candidate?

**Comment by mrange** [comment] 2021-12-04 19:51
This might be obvious to everyone but FYI I tested in x64 and x86 and the issue reproduced in x64 but not in x86. That could be a potential workaround if you are hit by this issue then.

**Comment by akoeplinger** [comment] 2022-01-14 18:29
Fixed by the backportin https://github.com/dotnet/runtime/pull/62207

**Closed by akoeplinger** 2022-01-14 18:29 UTC
Labels: area-CodeGen-coreclr
