### ISSUE TITLE
DispatchProxy.Create<IProxy, Base> uncastable to Base in custom load context

### ISSUE THREAD

**Issue by vuplea** [dotnet/runtime#60468] opened 2021-10-15 14:17 UTC
### Description

We are loading our plugins and their dependencies in a custom load context, except for the .NET runtime assemblies which are used from the default context.

One of our dependencies is loaded in both Default and plugin context since it is used by both host and plugins.
This dependency is using `(Base)DispatchProxy.Create<IProxy, Base>` which succeeds in default context but fails in plugin context with `InvalidCastException`.

### Reproduction Steps

```
public class Program : DispatchProxy
{
    static void Main()
    {
        Console.WriteLine(DispatchProxyCreate(typeof(Program)).GetType().IsAssignableTo(typeof(Program)));
        // True

        var typeofProgramInCustomContext = new AssemblyLoadContext("custom")
            .LoadFromAssemblyPath(typeof(Program).Assembly.Location)
            .GetType(typeof(Program).FullName);

        Console.WriteLine(DispatchProxyCreate(typeofProgramInCustomContext).GetType().IsAssignableTo(typeofProgramInCustomContext));
        // False
    }

    public static object DispatchProxyCreate(Type parentType) => typeof(Program)
        .GetMethod(nameof(DispatchProxyCreateGeneric))
        .MakeGenericMethod(parentType)
        .Invoke(null, null);

    public static object DispatchProxyCreateGeneric<T>() where T : DispatchProxy =>
        DispatchProxy.Create<IDisposable, T>();

    protected override object Invoke(MethodInfo targetMethod, object[] args) => null;
}
```

Quick investigation reveals that this is induced by the single static `AssemblyBuilder` used for all proxies, which binds the parent type to the default context.
```
var typeId = 0;
var moduleBuilder = AssemblyBuilder
    .DefineDynamicAssembly(new AssemblyName("assembly"), AssemblyBuilderAccess.Run)
    .DefineDynamicModule("module");

Console.WriteLine(CreateDerivedType(typeof(Program)).IsAssignableTo(typeof(Program)));
// True

var typeofProgramInCustomContext = new AssemblyLoadContext("custom")
    .LoadFromAssemblyPath(typeof(Program).Assembly.Location)
    .GetType(typeof(Program).FullName);

Console.WriteLine(CreateDerivedType(typeofProgramInCustomContext).IsAssignableTo(typeofProgramInCustomContext));
// False

Type CreateDerivedType(Type parentType) => moduleBuilder
    .DefineType($"type{typeId++}", TypeAttributes.Public, parentType)
    .CreateType();
```

**Comment by vitek-karas** [comment] 2021-11-22 22:21
There are actually two bugs here:

### DispatchProxy's AssemblyBuilder singleton
As noted by @vuplea the `DispatchProxy` implementation uses a [singleton value](https://github.com/dotnet/runtime/blob/4892e4f581525dfe1ec3af9cfd3ce17e3cc32b52/src/libraries/System.Reflection.DispatchProxy/src/System/Reflection/DispatchProxyGenerator.cs#L61) for `ProxyAssembly` class, which wraps the `AssemblyBuilder`.
This caused the reported issue here due to the second bug below, but it's basically the root cause of all of this (See the description of the second bug below).
It also means that the generated proxy is created in Default load context. This could potentially cause problems running code in it due to different assembly resolution behavior. It will also break unloadability. The defined types are tied to the Default ALC which is not unloadable -> since they depend on their base type which could be from unloadable ALC, those base types become not unloadable as well (rooted). 
https://github.com/dotnet/runtime/pull/48072 added the ability for `AssemblyBuilder` to create types in dynamic assemblies associated with custom load contexts (through the contextual reflection property). The DispatchProxy should use this ability ideally.

This does have sort of a workaround - use `AssemblyLoadContext.EnterContextualReflection` and use the assembly in the custom ALC (the assembly of the base type). This will create the dynamic type in an assembly based on the custom ALC. Works also for DispatchProxy.

That said this workaround is really problematic for DispatchProxy as it will create all dispatch proxies in the ALC where the first proxy was created. So even with the workaround above, it can easily break any app if that app happens to create proxies from two different ALCs (as only the first one will take effect).

I think DispatchProxy should:
* Create ProxyAssembly per ALC (this fixes the caching behavior and also avoids the second problem described below)
* It's an open question if it should always use the ALC of the base type, or if it should react to current contextual reflection setting. Right now I think it should probably react to contextual reflection, but it will probably need more thought.

### TypeBuilder seems to cache the base type by name?
In the above repro with just the TypeBuilder (for simplicity), it:
* Creates a derived type from the Default `Program` class
* Then it creates a derived type from a Custom ALC `Program` class
* The second derived type ends up having its base type the Default `Program`!!!

BUT, if I skip creating the first derived type, and only create the derived type from the Custom ALC `Program`, the created type has its base type the Custom ALC `Program`!!!!.

This is definitely wrong - creating a derived type of a given Type instance should return type which base type is the specified Type instance - it's not the case here.

This causes the actual failure reported above, as it makes the returned type unassignable to its intended base type.

This is a tricky problem - under the hood runtime creates basically a normal assembly for every assembly builder. Such assembly has only one way to refer to types from other assemblies - typeref+assemblyref. Both of these specify just simple names. And then these go through normal assembly resolution process - which will effectively cache the first result (this is simplified, the logic to get the type ref is pretty complex and there might be other tricks to it, but it does eventually create a simple assembly ref).

I don't think TypeBuilder can truly fix this - given the current implementation (where it generates real metadata with tokens and everything), since the underlying IL metadata doesn't have a way to express two assembly references to two different assemblies of the same exact name.

That said TypeBuilder should guard against this - ideally it should basically create the type ref, resolve it and validate that it got back the original Type instance - if not, it should fail as otherwise it creates wrong output.

### Conclusion
The repro without dispatch proxy can be fixed by using two separate type builders and contextual reflection, but the dispatch proxy is broken and needs changes to make this work correctly.

The TypeBuilder behavior is also wrong, but in a way secondary - if the DispatchProxy is fixed it will never tun into it.

The full fix for dispatch proxy should contain validation for both this issue as well as validation that the proxy types are unloadable along with the base type's ALC.

**Comment by buyaa-n** [comment] 2021-11-22 23:32
Thanks for the explanation @vitek-karas , I thought it is caused by `AssemblyLoadContext` 😝, moving back to the Reflection area

**Comment by vitek-karas** [comment] 2021-11-26 10:47
https://github.com/dotnet/runtime/issues/62050 shows another case where it doesn't work at all since the runtime disallows direct references from non-collectible to collectible assemblies.

**Comment by vitek-karas** [comment] 2021-12-01 13:51
I created https://github.com/dotnet/runtime/issues/62234 to track the `TypeBuilder` problem described above.

**Closed** 2021-12-03 17:52 UTC
Labels: bug, area-System.Reflection, in pr
