### ISSUE TITLE
crossgen2 fails with simple MAUI application

### ISSUE THREAD

**Issue by ErikApption** [dotnet/runtime#86727] opened 2023-05-24 21:28 UTC
### Description

```
dotnet publish /restore /t:Publish /p:TargetFramework=net7.0-windows10.0.20348 /p:configuration=release /p:WindowsAppSDKSelfContained=true /p:Platform=x64 /p:PublishSingleFile=true /p:WindowsPackageType=None /p:RuntimeIdentifier=win10-x64 /p:PublishReadyToRun=true -v d
```

returns

```
   "C:\code\SSC\datahub-portal\datahub-uploader\datahub-uploader.csproj" (Publish;Publish target) (1:10) ->
       (_CreateR2RImages target) ->
         C:\Program Files\dotnet\sdk\7.0.400-preview.23225.8\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(470,5): error MSB6006: "C:\Users\erik\.nuget\packages\microsoft.netcore.app.crossgen2.win-x64\7.0.5\tools\crossgen2.exe" exited with
        code -1073741819. [C:\code\SSC\datahub-portal\datahub-uploader\datahub-uploader.csproj::TargetFramework=net7.0-windows10.0.20348]


       "C:\code\SSC\datahub-portal\datahub-uploader\datahub-uploader.csproj" (Publish;Publish target) (1:10) ->
       (CreateReadyToRunImages target) ->
         C:\Program Files\dotnet\sdk\7.0.400-preview.23225.8\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(358,5): error NETSDK1096: Optimizing assemblies for performance failed. You can either exclude the failing assemblies from being opt
       imized, or set the PublishReadyToRun property to false. [C:\code\SSC\datahub-portal\datahub-uploader\datahub-uploader.csproj::TargetFramework=net7.0-windows10.0.20348]
```

### Reproduction Steps

1. Checkout branch https://github.com/ssc-sp/datahub-portal/tree/maui_uploader from datahub portal
2. open datahub-uploader folder
3. run 
```
dotnet publish /restore /t:Publish /p:TargetFramework=net7.0-windows10.0.20348 /p:configuration=release /p:WindowsAppSDKSelfContained=true /p:Platform=x64 /p:PublishSingleFile=true /p:WindowsPackageType=None /p:RuntimeIdentifier=win10-x64 /p:PublishReadyToRun=true -v d
```

### Expected behavior

crossgen2 generates a r2r file or crossgen2 points to the assembly that cannot be optimized

### Actual behavior

build fails with crossgen2 error

### Configuration

- windows 11
- dotnet sdk 7.0.400-preview.23225.8

**Comment by trylek** [comment] 2023-05-25 00:01
I think it's this line:

https://github.com/dotnet/sdk/blob/fa5eeeb2ebb567117cbc1d491fdcdd5b4447f6cc/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.CrossGen.targets#L21

**Comment by trylek** [comment] 2023-05-25 00:03
If it turns out not to be the case, we should be able to use the binlog to find out more detail, that should let us see all the property value shenanigans that take place there.

**Comment by ErikApption** [comment] 2023-07-12 14:12
@trylek  this still happens with 8.0.100-preview.5.23303.2 sdk. I don't mind editing the crossgen.targets but what change are you suggesting? Also how do I generate a binlog?

**Comment by mangod9** [comment] 2023-07-24 18:32
Is this a regression in 8?

**Comment by ErikApption** [comment] 2023-08-09 20:41
@trylek this was merged into the main branch https://github.com/ssc-sp/datahub-portal + steps above are causing the same issue on my side

**Comment by MaxDeVos** [comment] 2023-10-26 10:30
I was able to replicate this with the unmodified `maui-blazor` template on framework `net7.0-windows10.0.19041.0`.

Steps to reproduce:
1) `mkdir DefaultMauiBlazorApp`
2) `cd DefaultMauiBlazorApp`
3) `dotnet new maui-blazor`
4) `msbuild DefaultMauiBlazorApp.csproj /restore /t:Publish /p:TargetFramework=net7.0-windows10.0.19041.0 /p:configuration=release /p:WindowsAppSDKSelfContained=true /p:Platform=x64 /p:PublishSingleFile=true /p:WindowsPackageType=None /p:RuntimeIdentifier=win10-x64`

Console Output

    C:\Program Files\dotnet\sdk\7.0.304\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(470,5): error MSB6006: "C:\Users\Max\.nuget\packages\microsoft.netcore.app.crossgen2.win-x64\7.0.7\tools\crossgen2.exe" exited with code -1073741819. [C:\Workspace\CSharp\DefaultMauiBlazorApp\DefaultMauiBlazorApp.csproj::TargetFramework=net7.0-windows10.0.19041.0] 
    Build continuing because "ContinueOnError" on the task "RunReadyToRunCompiler" is set to "ErrorAndContinue".
    C:\Program Files\dotnet\sdk\7.0.304\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(358,5): error NETSDK1096: Optimizing assemblies for performance failed. You can either exclude the failing assemblies from being optimized,or set the PublishReadyToRun property to false. [C:\Workspace\CSharp\DefaultMauiBlazorApp\DefaultMauiBlazorApp.csproj::TargetFramework=net7.0-windows10.0.19041.0]
    Done Building Project "C:\Workspace\CSharp\DefaultMauiBlazorApp\DefaultMauiBlazorApp.csproj" (Publish target(s)) -- FAILED.
    
    Build FAILED.
    
    "C:\Workspace\CSharp\DefaultMauiBlazorApp\DefaultMauiBlazorApp.csproj" (Publish target) (1:10) -> (_CreateR2RImages target) -> C:\Program Files\dotnet\sdk\7.0.304\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(470,5): error MSB6006: "C:\Users\Max\.nuget\packages\microsoft.netcore.app.crossgen2.win-x64\7.0.7\tools\crossgen2.exe" exited with code -1073741819. [C:\Workspace\CSharp\DefaultMauiBlazorApp\DefaultMauiBlazorApp.csproj::TargetFramework=net7.0-windows10.0.19041.0]
    "C:\Workspace\CSharp\DefaultMauiBlazorApp\DefaultMauiBlazorApp.csproj" (Publish target) (1:10) -> (CreateReadyToRunImages target) ->  C:\Program Files\dotnet\sdk\7.0.304\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.CrossGen.targets(358,5): error NETSDK1096: Optimizing assemblies for performance failed. You can either exclude the failing assemblies from being optimized, or set the PublishReadyToRun property to false. [C:\Workspace\CSharp\DefaultMauiBlazorApp\DefaultMauiBlazorApp.csproj::TargetFramework=net7.0-windows10.0.19041.0]
    
        0 Warning(s)
        2 Error(s)
    
    Time Elapsed 00:00:26.56

**Comment by steveisok** [comment] 2024-06-28 14:46
@ivdiazsa does r2r log what assemblies failed? Not having that easily surfaced is what I think this issue may be boiling down to.

**Comment by ivdiazsa** [comment] 2024-07-03 19:30
I wasn't able to reproduce it with the latest official builds of .NET 8 and .NET 9 preview 5. Everything built fine.

For reference, here's the command-line:

`dotnet publish -c Release -p:TargetFramework=net9.0-windows10.0.19041.0 -p:WindowsAppSDKSelfContained=true -p:PublishSingleFile=true -p:WindowsPackageType=None -p:RuntimeIdentifier=win10-x64`

And this is the csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk.Razor">
    <PropertyGroup>
        <!-- <TargetFrameworks>net8.0-windows10.0.19041.0</TargetFrameworks> -->
        <TargetFrameworks>net9.0-windows10.0.19041.0</TargetFrameworks>
        <!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
        <!-- <TargetFrameworks>$(TargetFrameworks);net6.0-tizen</TargetFrameworks> -->
        <OutputType>Exe</OutputType>
        <RootNamespace>ReproMauiBlazorApp</RootNamespace>
        <UseMaui>true</UseMaui>
        <SingleProject>true</SingleProject>
        <ImplicitUsings>enable</ImplicitUsings>
        <EnableDefaultCssItems>false</EnableDefaultCssItems>

        <!-- Display name -->
        <ApplicationTitle>ReproMauiBlazorApp</ApplicationTitle>

        <!-- App Identifier -->
        <ApplicationId>com.companyname.repromauiblazorapp</ApplicationId>
        <ApplicationIdGuid>90E2596E-4967-41E4-82E0-450866288970</ApplicationIdGuid>

        <!-- Versions -->
        <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
        <ApplicationVersion>1</ApplicationVersion>
    </PropertyGroup>

    <ItemGroup>
        <!-- App Icon -->
        <MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

        <!-- Splash Screen -->
        <MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

        <!-- Images -->
        <MauiImage Include="Resources\Images\*" />
        <MauiImage Update="Resources\Images\dotnet_bot.svg" BaseSize="168,208" />

        <!-- Custom Fonts -->
        <MauiFont Include="Resources\Fonts\*" />

        <!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
        <MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
    </ItemGroup>
</Project>
```

**Comment by ivdiazsa** [comment] 2024-08-01 17:48
Closing since this issue no longer repros with the currently supported dotnet versions. Will reopen if it starts happening again.

**Closed by ivdiazsa** 2024-08-01 17:48 UTC
Labels: area-crossgen2-coreclr
