### ISSUE TITLE
Publishing for ARM target run time

### ISSUE THREAD

**Issue by kalijana** [dotnet/runtime#52692] opened 2021-05-13 07:31 UTC
have a armv5 custom SOC and trying to publish linux-arm  with self contained and single file options .( from windows 10 system)

 But unable to run the application . OS is Debian GNU linux

**Comment by vitek-karas** [comment] 2021-05-13 08:31
Could you please provide a bit more info:
* "Unable to run the app" - what does this mean? How does it fail?
* What version of .NET are you using?
* Does it work if you try it non-single-file?
* What version of the OS?

**Comment by jkotas** [comment] 2021-05-13 13:13
> a armv5 custom SOC

.NET needs armv7

**Comment by kalijana** [comment] 2021-05-13 15:44
.net version 3.1 
.debian gnu 3.1 as well 
issue is the executable does not get recognized

**Comment by kalijana** [comment] 2021-05-13 15:53
processor       : ARM926EJ-S rev 0 (v5l)
CPU architecture: 5TEJ

**Comment by kalijana** [comment] 2021-05-14 00:14
so does that mean that for this ARM SOC i cant do a cross compile ?

**Comment by jkotas** [comment] 2021-05-14 00:22
It would not work even if you compiled natively. This SOC is ARM v5, but .NET needs ARM v7.

**Comment by jkotas** [comment] 2021-05-14 00:22
Duplicate of https://github.com/dotnet/runtime/issues/7764

**Closed by jkotas** 2021-05-14 00:22 UTC
Labels: area-Single-File, untriaged
