### ISSUE TITLE
Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBinderTests.GetCanReadStaticProperty test failing

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#91308] opened 2023-08-30 05:13 UTC
```
Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBinderTests.GetCanReadStaticProperty [FAIL]
      Assert.Equal() Failure
      Expected: stuff
      Actual:   (null)
      Stack Trace:
        /_/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/Common/ConfigurationBinderTests.cs(751,0): at Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBinderTests.GetCanReadStaticProperty()
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=390065
Build error leg or test failing: Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBinderTests.GetCanReadStaticProperty
Pull request: https://github.com/dotnet/runtime/pull/91300

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBinderTests.GetCanReadStaticProperty [FAIL]",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=390065
**Error message validated:** `Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBinderTests.GetCanReadStaticProperty [FAIL]`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 8/30/2023 5:14:07 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by tarekgh** [comment] 2023-08-30 15:24
This is duplicate of https://github.com/dotnet/runtime/issues/86532 and https://github.com/dotnet/runtime/issues/91188. I'll keep this one and resolve the other.

**Comment by tarekgh** [comment] 2023-11-20 17:58
This should be already fixed now.

**Closed by tarekgh** 2023-11-20 17:58 UTC
Labels: blocking-clean-ci, untriaged, area-Extensions-Configuration, Known Build Error
