### ISSUE TITLE
required and jsignore prevent correct serialization

### ISSUE THREAD

**Issue by toasteur** [dotnet/runtime#83257] opened 2023-03-10 11:50 UTC
### Description

when creating a record inheriting from another one, where i set a string property to required but don't want it to be serialized, the serializer produces an exception on the required property but
- this property is correctly set
- this property does not have to appear in the serialized json so shouldn't be taken in account

doing the same operation works when putting the required property directly in the base record

### Reproduction Steps

- create a web api project
- create an inherited record from WeatherForecast
- add a required string property with a jsignore attribute
- change the Get() method in the weatherforecast controller to instanciate this new record and fill the required property with some text

### Expected behavior

the get method from the api returns exactly the same json as before

### Actual behavior

there is an serializer exception like this
"System.InvalidOperationException: JsonPropertyInfo 'textToIgnore' defined in type 'TestJsonIgnore.WeatherForecastWithInternalData' is marked required but does not specify a setter."

### Known Workarounds

set the string as optional (string?) and be forced to use a ! on all code using the property

### Configuration

.Net 7.0.3 with system.text.json 7.0.2 on windows 10 in portable runtime

**Comment by eiriktsarpalis** [comment] 2023-03-10 14:12
Duplicate of #78443. `required` and `JsonIgnoreAttribute` are mutually exclusive configurations

**Closed by eiriktsarpalis** 2023-03-10 14:12 UTC
Labels: area-System.Text.Json, untriaged
