### ISSUE TITLE
Implicit DateTime to DateTimeOffset conversion throws exception. An analyzer could help catch?

### ISSUE THREAD

**Issue by timmydo** [dotnet/runtime#99828] opened 2024-03-15 17:41 UTC
We recently had a developer on our team run into this issue. This code depends on the timezone it's run in. I am running it from UTC-8/UTC-7 PST/PDT.

I'm wondering if an analyzer could catch this implicit conversion and warn that it may throw under certain circumstances.
 
Program.cs:
```
namespace DateTimeTest
{
    internal class Program
    {
        static void Main(string[] args)
        {
            DateTime t1 = DateTime.MaxValue;
            var t2 = DateTimeOffset.UtcNow;
            if (t1 > t2)
            {
                Console.WriteLine("hi");
            }
        }
    }
}

```

Project.csproj
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest-all</AnalysisLevel>
  </PropertyGroup>
</Project>
```

Exception:
```
System.ArgumentOutOfRangeException: 'The UTC time represented when the offset is applied must be between year 0 and 10,000. (Parameter 'offset')'
```

**Comment by martincostello** [comment] 2024-03-16 03:35
It's possible to do this today with the [banned API analyzers](https://github.com/dotnet/roslyn-analyzers/blob/main/src/Microsoft.CodeAnalysis.BannedApiAnalyzers/BannedApiAnalyzers.Help.md) - I've been bitten by implicit conversions causing time zone issues in the past before, so I've configured the implicit operator to cause a compiler error to prevent accidental usage.

**Comment by huoyaoyuan** [comment] 2024-03-18 06:51
> I've been bitten by implicit conversions causing time zone issues in the past before

I usually just ban the `DateTime` type totally and use `DateTimeOffset` exclusively.

**Comment by Clockwork-Muse** [comment] 2024-03-18 16:12
> > I've been bitten by implicit conversions causing time zone issues in the past before
> 
> I usually just ban the `DateTime` type totally and use `DateTimeOffset` exclusively.

The usual reason being because `DateTime.Kind`/`DateTimeKind` causes _all sorts of problems_, ones that you generally can't (reasonably) program around.

If you need something simple, `DateTimeOffset` works great.
If you need something more involved, you want to use `NodaTime`.

**Comment by timmydo** [comment] 2024-03-18 16:54
> It's possible to do this today with the [banned API analyzers](https://github.com/dotnet/roslyn-analyzers/blob/main/src/Microsoft.CodeAnalysis.BannedApiAnalyzers/BannedApiAnalyzers.Help.md) - I've been bitten by implicit conversions causing time zone issues in the past before, so I've configured the implicit operator to cause a compiler error to prevent accidental usage.

@martincostello  Would you mind sharing the entries you created for the banned API analyzer?

**Comment by martincostello** [comment] 2024-03-18 20:53
Sure - it'll be a few days until I'm back at a computer where I have access to the code for them though.

**Comment by martincostello** [comment] 2024-03-21 12:36
> Sure - it'll be a few days until I'm back at a computer where I have access to the code for them though.

```
M:System.DateTimeOffset.op_Implicit(System.DateTime); Do not implicitly cast DateTime to DateTimeOffset.
```

**Comment by tarekgh** [comment] 2024-06-20 18:51
This is duplicate of https://github.com/dotnet/runtime/issues/75400.

**Closed by tarekgh** 2024-06-20 18:51 UTC
Labels: untriaged, code-analyzer, area-System.DateTime
