### ISSUE TITLE
Missing methods of IStream from PortableDeviceApiLib

### ISSUE THREAD

**Issue by Bassman2** [dotnet/runtime#35453] opened 2020-04-25 13:25 UTC
The methods Stat and Seek from the interface IStream from the library Interop.PortableDeviceApiLib.dll always throw the exception NotImplementedException under all versions of Windows Core under Windows x64. 
The same code works well under the .NET Framework 4.5.

```
stream.Stat(out STATSTG stat, 1);
IntPtr pLength = Marshal.AllocHGlobal(16);
stream.Seek(0, 2, pLength); 
```

**Comment by jkotas** [comment] 2020-04-25 13:29
Could you please attach a complete code that can be used to reproduce this issue?

**Comment by AaronRobinsonMSFT** [comment] 2020-05-11 19:23
Closing due to non-response for more info.

**Closed by AaronRobinsonMSFT** 2020-05-11 19:23 UTC
Labels: area-Interop-coreclr, needs more info, untriaged
