### ISSUE TITLE
Crossgen2 crashing on SPCL

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtime#69926] opened 2022-05-27 22:45 UTC
For local Debug builds on Windows x64, a crash is occasionally observed. A crash DMP was collected and that can be shared offline.

```
  Emitting R2R PE file: D:\runtime\artifacts\bin\coreclr\windows.x64.Debug\System.Private.CoreLib.dll
  Fatal error. Internal CLR error. (0x80131506)
D:\runtime\src\coreclr\crossgen-corelib.proj(104,5): error MSB3073: The command "D:\runtime\dotnet.cmd D:\runtime\artifacts\bin\coreclr\windows.x64.Debug\crossgen2\crossgen2.dll -o:D
:\runtime\artifacts\bin\coreclr\windows.x64.Debug\System.Private.CoreLib.dll -r:D:\runtime\artifacts\bin\coreclr\windows.x64.Debug\IL\*.dll --targetarch:x64 -O --verify-type-and-fiel
d-layout D:\runtime\artifacts\bin\coreclr\windows.x64.Debug\IL\System.Private.CoreLib.dll --pdb --pdb-path:D:\runtime\artifacts\bin\coreclr\windows.x64.Debug\PDB" exited with code -1       
073741819.

d-layout D:\runtime\artifacts\bin\coreclr\windows.x64.Debug\IL\System.Private.CoreLib.dll --pdb --pdb-path:D:\runtime\artifacts\bin\coreclr\windows.x64.Debug\PDB" exited with code -1 
073741819.
Build FAILED.
D:\runtime\src\coreclr\crossgen-corelib.proj(104,5): error MSB3073: The command "D:\runtime\dotnet.cmd D:\runtime\artifacts\bin\coreclr\windows.x64.Debug\crossgen2\crossgen2.dll -o:D 
:\runtime\artifacts\bin\coreclr\windows.x64.Debug\System.Private.CoreLib.dll -r:D:\runtime\artifacts\bin\coreclr\windows.x64.Debug\IL\*.dll --targetarch:x64 -O --verify-type-and-fiel d-layout D:\runtime\artifacts\bin\coreclr\windows.x64.Debug\IL\System.Private.CoreLib.dll --pdb --pdb-path:D:\runtime\artifacts\bin\coreclr\windows.x64.Debug\PDB" exited with code -1 
073741819.
    0 Warning(s)
    1 Error(s)
```

Cursory debugging notes:

The result of `eestack` are below. I've confirm the passed in array is a `Byte[]` and its element type is non-null and `Byte`, however it seems that `null` is being returned for some reason.

```
0:000> !eestack
---------------------------------------------
Thread   0
Current frame: coreclr!MethodTable::GetVerifierCorElementType [D:\a\_work\1\s\src\coreclr\vm\methodtable.cpp:4464]
Child-SP         RetAddr          Caller, Callee
0000002259D7CCE0 00007ffdbe96df9e coreclr!ArrayNative::GetCorElementTypeOfElementType + 0x1e [D:\a\_work\1\s\src\coreclr\classlibnative\bcltype\arraynative.cpp:29], calling coreclr!TypeHandle::GetVerifierCorElementType [D:\a\_work\1\s\src\coreclr\vm\typehandle.cpp:1264]
0000002259D7CD20 00007ffd5f63ffb0 (MethodDesc 00007ffd5ef08040 + 0x50 System.Buffer.BlockCopy(System.Array, Int32, System.Array, Int32, Int32)), calling 00007ffdbe96df80 (stub for System.Array.GetCorElementTypeOfElementType())
0000002259D7CD40 00007ffd5f639d66 (MethodDesc 00007ffd5f196f50 + 0x46 Internal.TypeSystem.Ecma.EcmaAssembly.ToString()), calling (MethodDesc 00007ffd5ef0f048 + 0 System.Reflection.AssemblyName.get_Name())
0000002259D7CD80 00007ffd5f6358c2 (MethodDesc 00007ffd5f741600 + 0x62 Internal.Text.Utf8StringBuilder.Append(Byte[])), calling (MethodDesc 00007ffd5ef08040 + 0 System.Buffer.BlockCopy(System.Array, Int32, System.Array, Int32, Int32))
0000002259D7CDC0 00007ffd5f6357d3 (MethodDesc 00007ffd5f7415e8 + 0x53 Internal.Text.Utf8StringBuilder.Append(Internal.Text.Utf8String)), calling (MethodDesc 00007ffd5f741600 + 0 Internal.Text.Utf8StringBuilder.Append(Byte[]))
0000002259D7CE10 00007ffd5f636a3b (MethodDesc 00007ffd5f544b88 + 0x9b Internal.JitInterface.MethodWithToken.AppendMangledName(ILCompiler.NameMangler, Internal.Text.Utf8StringBuilder)), calling (MethodDesc 00007ffd5f7415e8 + 0 Internal.Text.Utf8StringBuilder.Append(Internal.Text.Utf8String))
0000002259D7CED0 00007ffd5f641d93 (MethodDesc 00007ffd5f2737a0 + 0x143 ILCompiler.DependencyAnalysis.ReadyToRun.VirtualResolutionFixupSignature.AppendMangledName(ILCompiler.NameMangler, Internal.Text.Utf8StringBuilder)), calling (MethodDesc 00007ffd5f544b88 + 0 Internal.JitInterface.MethodWithToken.AppendMangledName(ILCompiler.NameMangler, Internal.Text.Utf8StringBuilder))
0000002259D7CF90 00007ffd5f636763 (MethodDesc 00007ffd5f31b360 + 0x83 ILCompiler.DependencyAnalysis.SignatureEmbeddedPointerIndirectionNode.AppendMangledName(ILCompiler.NameMangler, Internal.Text.Utf8StringBuilder))
0000002259D7D000 00007ffd5f63a80f (MethodDesc 00007ffd5f272c18 + 0xaf ILCompiler.DependencyAnalysis.ReadyToRun.Import.AppendMangledName(ILCompiler.NameMangler, Internal.Text.Utf8StringBuilder))
0000002259D7D020 00007ffdbe8f6aec coreclr!JIT_GetSharedGCThreadStaticBase + 0x7c [D:\a\_work\1\s\src\coreclr\vm\jithelpers.cpp:1832], calling coreclr!__security_check_cookie [d:\a01\_work\12\s\src\vctools\crt\vcstartup\src\gs\amd64\amdsecgs.asm:45]
0000002259D7D060 00007ffd5f62bd96 (MethodDesc 00007ffd5f741450 + 0xa6 ILCompiler.DependencyAnalysis.ISymbolNodeExtensions.GetMangledName(ILCompiler.DependencyAnalysis.ISymbolNode, ILCompiler.NameMangler))
0000002259D7D0D0 00007ffd5f62b840 (MethodDesc 00007ffd5f42e5b0 + 0xb0 ILCompiler.DependencyAnalysis.ReadyToRunObjectWriter.EmitObjectData(ILCompiler.PEWriter.R2RPEBuilder, ObjectData, Int32, System.String, ILCompiler.DependencyAnalysis.ObjectNodeSection)), calling (MethodDesc 00007ffd5f741450 + 0 ILCompiler.DependencyAnalysis.ISymbolNodeExtensions.GetMangledName(ILCompiler.DependencyAnalysis.ISymbolNode, ILCompiler.NameMangler))
0000002259D7D100 00007ffd5f39df2c (MethodDesc 00007ffd5f453b90 + 0xdc ILCompiler.DependencyAnalysis.ObjectDataBuilder.ToObjectData()), calling (MethodDesc 00007ffd5f34d590 + 0 ILCompiler.DependencyAnalysis.ObjectNode+ObjectData..ctor(Byte[], ILCompiler.DependencyAnalysis.Relocation[], Int32, ILCompiler.DependencyAnalysis.ISymbolDefinitionNode[]))
0000002259D7D260 00007ffd5f6273b4 (MethodDesc 00007ffd5f42e580 + 0x9a4 ILCompiler.DependencyAnalysis.ReadyToRunObjectWriter.EmitPortableExecutable()), calling (MethodDesc 00007ffd5f42e5b0 + 0 ILCompiler.DependencyAnalysis.ReadyToRunObjectWriter.EmitObjectData(ILCompiler.PEWriter.R2RPEBuilder, ObjectData, Int32, System.String, ILCompiler.DependencyAnalysis.ObjectNodeSection))
0000002259D7D2B0 00007ffdbe8ce38c coreclr!MethodDesc::DoBackpatch + 0x82c [D:\a\_work\1\s\src\coreclr\vm\prestub.cpp:253], calling coreclr!MethodDescBackpatchInfoTracker::ConditionalLockHolderForGCCoop::~ConditionalLockHolderForGCCoop
0000002259D7D7B0 00007ffd5f626111 (MethodDesc 00007ffd5f42e5c8 + 0x111 ILCompiler.DependencyAnalysis.ReadyToRunObjectWriter.EmitObject(System.String, Internal.TypeSystem.Ecma.EcmaModule, System.Collections.Generic.IEnumerable`1<System.String>, System.Collections.Generic.IEnumerable`1<ILCompiler.DependencyAnalysisFramework.DependencyNode>, ILCompiler.DependencyAnalysis.NodeFactory, Boolean, Boolean, Boolean, System.String, Boolean, System.String, Int32, Boolean, ILCompiler.CallChainProfile, Int32)), calling (MethodDesc 00007ffd5f42e580 + 0 ILCompiler.DependencyAnalysis.ReadyToRunObjectWriter.EmitPortableExecutable())
0000002259D7D860 00007ffd5f39a5da (MethodDesc 00007ffd5f277e90 + 0x27a ILCompiler.ReadyToRunCodegenCompilation.Compile(System.String)), calling (MethodDesc 00007ffd5f42e5c8 + 0 ILCompiler.DependencyAnalysis.ReadyToRunObjectWriter.EmitObject(System.String, Internal.TypeSystem.Ecma.EcmaModule, System.Collections.Generic.IEnumerable`1<System.String>, System.Collections.Generic.IEnumerable`1<ILCompiler.DependencyAnalysisFramework.DependencyNode>, ILCompiler.DependencyAnalysis.NodeFactory, Boolean, Boolean, Boolean, System.String, Boolean, System.String, Int32, Boolean, ILCompiler.CallChainProfile, Int32))
0000002259D7DA40 00007ffd5ee6a0d3 (MethodDesc 00007ffd5ef0a5a8 + 0x1703 ILCompiler.Program.RunSingleCompilation(System.Collections.Generic.Dictionary`2<System.String,System.String>, ILCompiler.InstructionSetSupport, System.String, System.Collections.Generic.Dictionary`2<System.String,System.String>, System.Collections.Generic.HashSet`1<Internal.TypeSystem.ModuleDesc>, ILCompiler.CompilerTypeSystemContext))
0000002259D7E0F0 00007ffd5ee420c5 (MethodDesc 00007ffd5ef0a590 + 0x1675 ILCompiler.Program.Run(System.String[])), calling (MethodDesc 00007ffd5ef0a5a8 + 0 ILCompiler.Program.RunSingleCompilation(System.Collections.Generic.Dictionary`2<System.String,System.String>, ILCompiler.InstructionSetSupport, System.String, System.Collections.Generic.Dictionary`2<System.String,System.String>, System.Collections.Generic.HashSet`1<Internal.TypeSystem.ModuleDesc>, ILCompiler.CompilerTypeSystemContext))
0000002259D7E890 00007ffd5ee40746 (MethodDesc 00007ffd5ef0a668 + 0x76 ILCompiler.Program.Main(System.String[])), calling (MethodDesc 00007ffd5ef0a590 + 0 ILCompiler.Program.Run(System.String[]))
```

Details on array and element `MethodTable`s.

```
0:000> !DumpMT /d 00007ffd5f035fd8
EEClass:         00007ffd5f035f58
Module:          00007ffd5ecb4000
Name:            System.Byte[]
mdToken:         0000000002000000
File:            D:\runtime\.dotnet\shared\Microsoft.NETCore.App\7.0.0-preview.3.22175.4\System.Private.CoreLib.dll
BaseSize:        0x18
ComponentSize:   0x1
DynamicStatics:  false
ContainsPointers false
Slots in VTable: 28
Number of IFaces in IFaceMap: 6
0:000> dt (coreclr!MethodTable)00007ffd5f035fd8
   =00007ffd`becbee70 s_pMethodDataCache : 0x00000163`7708d6b0 MethodDataCache
   =00007ffd`becbee78 s_fUseParentMethodData : 0n1
   =00007ffd`becbee68 s_fUseMethodDataCache : 0n1
   +0x000 m_dwFlags        : 0x800a0001
   +0x004 m_BaseSize       : 0x18
   +0x008 m_wFlags2        : 0xb
   +0x00a m_wToken         : 0
   +0x00c m_wNumVirtuals   : 0x18
   +0x00e m_wNumInterfaces : 6
   +0x010 m_pParentMethodTable : 0x00007ffd`5edcacf8 MethodTable
   +0x018 m_pLoaderModule  : 0x00007ffd`5ecb4000 Module
   +0x020 m_pWriteableData : 0x00007ffd`5f036090 MethodTableWriteableData
   +0x028 m_pEEClass       : 0x00007ffd`5f035f58 EEClass
   +0x028 m_pCanonMT       : 0x00007ffd`5f035f58
   +0x030 m_pPerInstInfo   : 0x00007ffd`5ee05e68  -> 0x00000018`00070000 Dictionary
   +0x030 m_ElementTypeHnd : 0x00007ffd`5ee05e68
   +0x030 m_pMultipurposeSlot1 : 0x00007ffd`5ee05e68
   +0x038 m_pInterfaceMap  : 0x00007ffd`5f036040 InterfaceInfo_t
   +0x038 m_pMultipurposeSlot2 : 0x00007ffd`5f036040
   =00007ffd`bec06338 c_DispatchMapSlotOffsets : [0]  "080@???"
   =00007ffd`bec06330 c_NonVirtualSlotsOffsets : [0]  "080@8@@H080@???"
   =00007ffd`bec06320 c_ModuleOverrideOffsets : [0]  "080@8@@H8@@H@HHP080@8@@H080@???"
   =00007ffd`bec18ae8 c_OptionalMembersStartOffsets : [0]  "@@@@@@@H@@@H@HHP@@@H@HHP@HHPHPPX"
0:000> !dumpmt 0x00007ffd`5ee05e68
EEClass:         00007ffd5edf4670
Module:          00007ffd5ecb4000
Name:            System.Byte
mdToken:         00000000020000ED
File:            D:\runtime\.dotnet\shared\Microsoft.NETCore.App\7.0.0-preview.3.22175.4\System.Private.CoreLib.dll
BaseSize:        0x18
ComponentSize:   0x0
DynamicStatics:  false
ContainsPointers false
Slots in VTable: 110
Number of IFaces in IFaceMap: 28
```

**Comment by jkotas** [comment] 2022-05-27 23:01
This is likely dup of https://github.com/dotnet/runtime/issues/68443 . 

Resolving as duplicate of https://github.com/dotnet/runtime/issues/69454 tracking similar crash in crossgen.

**Closed by jkotas** 2022-05-27 23:01 UTC
Labels: area-crossgen2-coreclr, untriaged
