### ISSUE TITLE
wasm library test failure EnableAggressiveTrimming -  System.ArgumentNullException

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#46758] opened 2021-01-08 18:42 UTC
In effort to run library tests with AOT compilation and EnableAggressiveTrimming enabled on CI https://github.com/dotnet/runtime/pull/48226 these errors are hit.

### EnableAggressiveTrimming related
- [ ] `System.ArgumentNullException : Value cannot be null. (Parameter 'method')`
`System.ComponentModel.TypeConverter.Tests` [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.ComponentModel.TypeConverter.Tests/console.30f4aaee.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)
`Microsoft.Extensions.Http.Tests` [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/Microsoft.Extensions.Http.Tests/console.31889118.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)
`System.Diagnostics.DiagnosticSource.Tests` [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-763c687ce1484b1abb/System.Diagnostics.DiagnosticSource.Tests/console.159e3105.log?sv=2019-07-07&se=2021-03-22T22%3A42%3A11Z&sr=c&sp=rl&sig=j3nkjEXoSYKeYivb%2F4MGWEFD4%2Bb8GzvR%2BF1Hzlivu7I%3D)

Repro:
Check out changes in 
https://github.com/dotnet/runtime/pull/48226/commits/4f17c4e647209433bf05f53374e54b74b8db1fe5 without this, many tests are not discovered.
~~https://github.com/dotnet/runtime/pull/48226/commits/4e7ab852bd4419e40d5e9adca70855c963fe6dd7 this one helps avoid some AOT compilation errors with this exception filter.~~ There shouldn't be exception filter issues anymore.

`./build.sh -os Browser -arch wasm -c Release`
`./dotnet.sh build /t:Test /p:TargetOS=Browser /p:TargetArchitecture=wasm /p:Configuration=Release /p:EnableAggressiveTrimming=true /p:RunAOTCompilation=true src/libraries/<path-to-test-proj>`

**Comment by radical** [comment] 2021-01-12 20:37
I'm unable to reproduce this:

```
  XHarness command issued: wasm test --app=. --engine=V8 --engine-arg=--stack-trace-limit=1000 --js-file=runtime.js --output-directory=/Users/radical/dev/r2/artifacts/bin/Microsoft.Extensions.FileSystemGlobbing.Tests/net6.0-Release/browser-wasm/AppBundle/xharness-output
-- --run WasmTestRunner.dll Microsoft.Extensions.FileSystemGlobbing.Tests.dll -notrait category=OuterLoop -notrait category=failing

  info: 15:35:57.4842150 v8 --expose_wasm --stack-trace-limit=1000 runtime.js -- --run WasmTestRunner.dll Microsoft.Extensions.FileSystemGlobbing.Tests.dll -notrait category=OuterLoop -notrait category=failing

  info: Arguments: --run,WasmTestRunner.dll,Microsoft.Extensions.FileSystemGlobbing.Tests.dll,-notrait,category=OuterLoop,-notrait,category=failing
  info: console.debug: MONO_WASM: Initializing mono runtime
  info: console.debug: MONO_WASM: ICU data archive(s) loaded, disabling invariant mode
  info: console.debug: mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
  info: Initializing.....
  info: Discovering: Microsoft.Extensions.FileSystemGlobbing.Tests.dll (method display = ClassAndMethod, method display options = None)
  info: Discovered:  Microsoft.Extensions.FileSystemGlobbing.Tests.dll (found 53 of 53 test cases)
  info: Starting:    Microsoft.Extensions.FileSystemGlobbing.Tests.dll
  info: Finished:    Microsoft.Extensions.FileSystemGlobbing.Tests.dll
  info:
  info: === TEST EXECUTION SUMMARY ===
  info: Total: 53, Errors: 0, Failed: 0, Skipped: 0, Time: 1.665764s
  info:
  info: 15:36:00.5108090 Process v8 exited with 0

  info: Application has finished with exit code: 0
  XHarness exit code: 0
  XHarness artifacts: /Users/radical/dev/r2/artifacts/bin/Microsoft.Extensions.FileSystemGlobbing.Tests/net6.0-Release/browser-wasm/AppBundle/xharness-output
```

**Comment by naricc** [comment] 2021-03-16 16:13
I will take this one now; I will assign more of these to myself once I do this one and get a better estimate for the work involved.

**Comment by SamMonoRT** [comment] 2021-06-21 15:26
@radical - this should be fixed, Please confirm if so, and close the issue

**Comment by naricc** [comment] 2021-06-21 15:26
I believe this is fixed by: https://github.com/dotnet/runtime/pull/50645

**Comment by radical** [comment] 2021-06-21 17:38
AFAICS, this is fixed.

**Closed by radical** 2021-06-21 17:38 UTC
Labels: arch-wasm, area-Infrastructure-libraries
