### ISSUE TITLE
Could not load type 'SqlGuidCaster' from assembly System.Data.SqlClient on .NET 8 Preview

### ISSUE THREAD

**Issue by tippmar-nr** [dotnet/runtime#86969] opened 2023-05-31 19:06 UTC
### Description

Running on .NET 8 Preview 4, reflection into `System.Data.SqlClient` throws an exception:
```
Could not load type 'SqlGuidCaster' from assembly 'System.Data.SqlClient, Version=4.6.1.5, Culture=neutral, 
PublicKeyToken=b03f5f7f11d50a3a' because it contains an object field at offset 0 that is incorrectly aligned 
or overlapped by a non-object field.
```
This appears to be identical to [the issue reported for Microsoft.Data.SqlClient](https://github.com/dotnet/SqlClient/issues/1930) a few months ago.

### Reproduction Steps

Console app, targeting .NET 8 Preview 4.
Add the latest `System.Data.SqlClient` package

```using System;
using System.Data.SqlClient;
using System.Linq;

namespace SDSqlClientRepro
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var sqlConnection = new SqlConnection();

            var assemblies = AppDomain.CurrentDomain.GetAssemblies().ToList();

            foreach (var assembly in assemblies)
            {
                foreach (var type in assembly.GetTypes()) // boom
                {
                }
            }

            Console.WriteLine("Done!");
        }
   }
}
```

### Expected behavior

Application should not throw an exception

### Actual behavior

Exception as noted above

### Regression?

Works fine under .NET 7.0

**Comment by JRahnama** [comment] 2023-05-31 20:23
@tippmar-nr this is a duplicate of [#1930](https://github.com/dotnet/SqlClient/issues/1930) in SqlClient. I will close this issue and you can follow the progress on the mentioned issue and related PR.

**Closed by JRahnama** 2023-05-31 20:23 UTC
Labels: area-System.Data.SqlClient, untriaged

**Comment by tippmar-nr** [comment] 2023-06-01 15:40
@JRahnama So should we expect this issue to be resolved for `System.Data.SqlClient` when it is resolved for `Microsoft.Data.SqlClient`? It looks like the fix will require a .NET 8 specific build of the package.

**Comment by danmoseley** [comment] 2023-06-01 17:10
This is owned by the SQL team -- @David-Engel  (per https://github.com/dotnet/runtime/blob/main/docs/area-owners.md) should answer.

Note, it may be easier to ask them over in https://github.com/dotnet/sqlclient

**Comment by David-Engel** [comment] 2023-06-01 20:01
System.Data.SqlClient, is unlikely to receive further updates, much less those that are only for fixing Reflection issues.

Regards,
David
