### ISSUE TITLE
Test failure: profiler\\elt\\slowpatheltleave\\slowpatheltleave.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#106946] opened 2024-08-26 01:51 UTC
**Failed in:** [runtime-coreclr pgostress 20240823.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=787269&view=ms.vss-test-web.build-test-results-tab&runId=20223110&resultId=101171&paneView=debug)

**Failed tests:**
```
coreclr windows arm64 Checked fullpgo @ Windows.11.Arm64.Open
    - profiler\\elt\\slowpatheltleave\\slowpatheltleave.cmd
```

**Error message:**
```
 
Assert failure(PID 8156 [0x00001fdc], Thread: 5988 [0x1764]): Consistency check failed: AV in clr at this callstack:
------
CORECLR! MDInternalRW::GetNameAndSigOfMethodDef + 0xE8 (0x00007ff8`3fb361a8)
CORECLR! MethodTableBuilder::MethodSignature::CheckGetMethodAttributes + 0x12C (0x00007ff8`3f86e30c)
CORECLR! MethodTableBuilder::bmtInterfaceEntry::CreateSlotTable + 0x450 (0x00007ff8`3f86fc18)
CORECLR! MethodTableBuilder::PlaceInterfaceMethods + 0x740 (0x00007ff8`3f8803c0)
CORECLR! MethodTableBuilder::BuildMethodTableThrowing + 0x1148 (0x00007ff8`3f86c0c8)
CORECLR! ClassLoader::CreateTypeHandleForTypeDefThrowing + 0xCAC (0x00007ff8`3f870c7c)
CORECLR! ClassLoader::CreateTypeHandleForTypeKey + 0x15C (0x00007ff8`3f6a6dac)
CORECLR! ClassLoader::DoIncrementalLoad + 0x200 (0x00007ff8`3f6a75b0)
CORECLR! ClassLoader::LoadTypeHandleForTypeKey_Body + 0x840 (0x00007ff8`3f6ab2f0)
CORECLR! ClassLoader::LoadTypeHandleForTypeKey + 0x134 (0x00007ff8`3f6aa834)
CORECLR! ClassLoader::LoadConstructedTypeThrowing + 0x184 (0x00007ff8`3f6a94a4)
CORECLR! ClassLoader::LoadGenericInstantiationThrowing + 0x1C0 (0x00007ff8`3f6a9718)
CORECLR! SigPointer::GetTypeHandleThrowing + 0x14AC (0x00007ff8`3f784cfc)
CORECLR! `anonymous namespace'::DetermineBlittabilityAndManagedSequential + 0x2B0 (0x00007ff8`3f6a2d20)
CORECLR! EEClassLayoutInfo::CollectLayoutFieldMetadataThrowing + 0x4D0 (0x00007ff8`3f6a1538)
CORECLR! ClassLoader::CreateTypeHandleForTypeDefThrowing + 0xBA4 (0x00007ff8`3f870b74)
CORECLR! ClassLoader::CreateTypeHandleForTypeKey + 0x15C (0x00007ff8`3f6a6dac)
CORECLR! ClassLoader::DoIncrementalLoad + 0x200 (0x00007ff8`3f6a75b0)
CORECLR! ClassLoader::LoadTypeHandleForTypeKey_Body + 0x840 (0x00007ff8`3f6ab2f0)
-----
.AV on tid=0x1764 (5988), cxr=000000D618775430, exr=000000D6187757C0
FAILED: false

CORECLR! CHECK::Trigger + 0x1C4 (0x00007ff8`3fa52854)
CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x238 (0x00007ff8`3f6d0e68)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x64 (0x00007ff8`3f6d0a2c)
CORECLR! CLRVectoredExceptionHandler + 0x154 (0x00007ff8`3f6d09b4)
CORECLR! CLRVectoredExceptionHandlerShim + 0x208 (0x00007ff8`3f6d1138)
NTDLL! RtlTimeToSecondsSince1970 + 0x1A8 (0x00007ff8`9c596bb8)
NTDLL! RtlRaiseException + 0x198 (0x00007ff8`9c5825b8)
NTDLL! KiUserExceptionDispatcher + 0x24 (0x00007ff8`9c512764)
CORECLR! MDInternalRW::GetNameAndSigOfMethodDef + 0xE8 (0x00007ff8`3fb361a8)
CORECLR! MethodTableBuilder::MethodSignature::CheckGetMethodAttributes + 0x12C (0x00007ff8`3f86e30c)
    File: D:\a\_work\1\s\src\coreclr\vm\excep.cpp:6879
    Image: C:\h\w\B38509B9\p\CoreRun.exe

Unhandled exception. System.Exception: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above. Profilee returned exit code -1073740286.
   at Profiler.Tests.ProfilerTestRunner.FailFastWithMessage(String error)
   at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions, Dictionary`2 envVars, String reverseServerName, Boolean loadAsNotification, Int32 notificationCopies)
   at SlowPathELTTests.SlowPathELTLeave.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\B38509B9\w\9EF608AC\uploads\Reports\profiler.elt\slowpatheltleave\slowpatheltleave.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\B38509B9\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  slowpatheltleave.dll 
Profiler path: C:\h\w\B38509B9\w\9EF608AC\e\profiler\elt\slowpatheltleave\Profiler.dll
Profilee STDOUT: Profiler.dll!DllGetClassObject
Profilee STDOUT: Profiler.dll!Profiler::Initialize
Profilee STDOUT: Testing leave hooks
Test failed:
```

**Stack trace:**
```
   at profiler_elt._slowpatheltleave_slowpatheltleave_._slowpatheltleave_slowpatheltleave_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by mdh1418** [comment] 2024-11-14 20:17
The failure looks unrelated to what the test is targeting. Could it have been caused by pgostress? @jkotas do you have any ideas on what might have caused the assert to fail in [GetNameAndSigOfMethodDef](https://github.com/dotnet/runtime/blob/ed2e02c772226a27174054e6bef4df9df3d71bd9/src/coreclr/md/enc/mdinternalrw.cpp#L1927-L1928)?

**Comment by jkotas** [comment] 2024-11-14 22:15
This test has been failing every once in a while, with a crash that we were not able to diagnose. For example, https://github.com/dotnet/runtime/issues/60665#issuecomment-957302116

I am going to close this since the crash dump for the failure is gone, so there is not much to investigate. We should look at the dump in timely manner when this test fails next time.

**Closed by jkotas** 2024-11-14 22:15 UTC
Labels: arch-arm64, os-windows, area-Diagnostics-coreclr, blocking-clean-ci-optional
