### ISSUE TITLE
TimeSpan.Parse(string) converts hour values > 24 to day values

### ISSUE THREAD

**Issue by NikoUmbleLSPA** [dotnet/runtime#101187] opened 2024-04-17 15:51 UTC
### Description

When parsing a string like `25:00:00`, `TimeSpan.Parse` returns an instance with 25 days instead.

![image](https://github.com/dotnet/runtime/assets/161494325/dc0e336b-94ae-45cf-b964-e282be407b31)

### Reproduction Steps

```
TimeSpan ts = TimeSpan.Parse("25:00:00");

### Expected behavior

Instance is set to 25 hours

### Actual behavior

Instance is set to 25 days

### Regression?

_No response_

### Known Workarounds

_No response_

### Configuration

Microsoft .NET Framework Version 4.8.09032

### Other information

Seems to be a regression of https://github.com/dotnet/runtime/issues/40316, 
which was closed as completed on [Aug 4, 2020](https://github.com/dotnet/runtime/issues/40316#event-3621743601)

**Comment by campersau** [comment] 2024-04-17 16:21
Looks like a duplicate of #90214

**Comment by tarekgh** [comment] 2024-06-20 17:29
That is right, this is a duplicate of https://github.com/dotnet/runtime/issues/90214. We are not willing to change this behavior because of application compatibility.

**Closed by tarekgh** 2024-06-20 17:29 UTC
Labels: untriaged, area-System.DateTime

**Comment by julealgon** [comment] 2024-06-20 17:57
@tarekgh the linked issue doesn't list any "workaround" to the original problem. Are there any? What if someone wants to represent 48 hours, is that allowed somehow by changing the format of the string?

Apologies if this was mentioned somewhere already.

**Comment by tarekgh** [comment] 2024-06-20 19:31
TimeSpan does not support hours outside the range `-23 through 23`. Such an hour value is not correct for TimeSpan. We have another proposal to support Duration https://github.com/dotnet/runtime/issues/72064 which will allow such scenarios. 

For this specific case, if you are sure your format is always in form of "hh:mm:ss", you can manually parse it:

```C#
        public static TimeSpan Parsehhmmss(string value)
        {
            string[] parts = value.Split(':');
            if (parts.Length == 3)
            {
                if (int.TryParse(parts[0], out int hours) && int.TryParse(parts[1], out int minutes) && int.TryParse(parts[2], out int seconds))
                {
                    int days = Math.DivRem(hours, 24, out hours); // hours %= 24
                    return new TimeSpan(days, hours, minutes, seconds);
                }
            }

            throw new FormatException("Invalid TimeSpan format");
        }
```
