### ISSUE TITLE
malloc error during `dotnet restore`on MacOs

### ISSUE THREAD

**Issue by Scyarah** [dotnet/runtime#99056] opened 2024-01-15 15:38 UTC
### Describe the bug
When running `dotnet restore` with sdk version `8.0.101` on MacOs 14.2 I often run into an error. This mostly happensin a big repository with many dependencies but has also happened in an empty newly created webapp project. Unfortunately I have not found a common reason when the error appears and when it does not.
When I switch to version `7.0.202`this has never happened so far.
I have already tried reinstalling, restarting and using different shells. 
```
dotnet(2889,0x16fdcf000) malloc: *** error for object 0x600002c45a80: pointer being freed was not allocated
dotnet(2889,0x16fdcf000) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      dotnet restore --verbosity detailed
```

### To Reproduce
With SDK8 (leads to error):
```
dotnet new webapp
dotnet restore
```

With SDK7 (works):
```
dotnet new globaljson --sdk-version 7.0.202
dotnet new webapp
dotnet restore
```

### Exceptions
```
dotnet(2889,0x16fdcf000) malloc: *** error for object 0x600002c45a80: pointer being freed was not allocated
dotnet(2889,0x16fdcf000) malloc: *** set a breakpoint in malloc_error_break to debug
zsh: abort      dotnet restore --verbosity detailed
```

### Further technical details
```
.NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.69afb982

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.2
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.101/

.NET workloads installed:
 Workload version: 8.0.100-manifests.69afb982
There are no installed workloads to display.

Host:
  Version:      8.0.1
  Architecture: arm64
  Commit:       bf5e279d92

.NET SDKs installed:
  6.0.406 [/usr/local/share/dotnet/sdk]
  6.0.407 [/usr/local/share/dotnet/sdk]
  7.0.200 [/usr/local/share/dotnet/sdk]
  7.0.202 [/usr/local/share/dotnet/sdk]
  8.0.101 [/usr/local/share/dotnet/sdk]
```

**Comment by mangod9** [comment] 2024-02-29 18:46
Thanks for reporting it. Is this a consistent failure or happens intermittently? Does it occur with latest servicing release too?  fyi @janvorli

**Comment by Scyarah** [comment] 2024-02-29 19:37
I have tried around some more with it and couldnt reproduce it for a while, but I am now getting it consistently again but only after I added an Azure Devops package source that requires credentials and then adding those credentials in my NuGet Config.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="MyDevopsPackageSource" value="https://some-devops-server-xyz/project/_packaging/project/nuget/v3/index.json" protocolVersion="3" />
  </packageSources>
  <packageSourceCredentials>
    <MyDevopsPackageSource>
      <add key="Username" value="MyUsername" />
      <add key="ClearTextPassword" value="MyPassword" />
    </MyDevopsPackageSource>
  </packageSourceCredentials>
</configuration>
```

I had to use ClearTextpassword because no other authentication worked. Also right now when I create a new project that does not require any package from that particular source, I am getting no error (although I definitely got them in the past). But in the project that actually requires packages from that source its consistently happening again.

**Comment by mangod9** [comment] 2024-02-29 19:53
@Scyarah given your symptoms this does seem like a dupe of https://github.com/dotnet/runtime/issues/97966 which @tobyperplex has pointed out. Can we use that to track the issue?

**Comment by Scyarah** [comment] 2024-02-29 19:56
Sure, yes. I overlooked that link before.

**Comment by mangod9** [comment] 2024-02-29 19:58
ok thanks. Closing this as dupe. Note that it's an Apple bug in fact so not sure if there is an ETA.

**Closed by mangod9** 2024-02-29 19:58 UTC
Labels: area-VM-coreclr, needs-area-label

**Comment by t0r3x** [comment] 2024-03-01 08:18
Can confirm it was related to me having a nuget.config file present. After deleting the file the malloc error stopped happening.
