### ISSUE TITLE
Uri.TryCreate Returns True For Uris That Are Not Absolute - Linux

### ISSUE THREAD

**Issue by ashleyjlive** [dotnet/runtime#108221] opened 2024-09-25 00:22 UTC
### Description

After migrating our application tests from a Windows based build agent to a Linux based build agent we noticed that Uri.TryCreate has different behaviour.
On Linux, `Uri.TryCreate("/foo", UriKind.Absolute, out var uri)` returns `true` whereas on Windows it returns `false`.
I believe the behaviour on Linux is incorrect.

### Reproduction Steps

Execute `Uri.TryCreate("/foo", UriKind.Absolute, out var uri)` on a Linux machine. Its output will be `true` whereas on Windows it is `false`.

### Expected behavior

It should return `false`.

### Actual behavior

It returns `true`.

### Configuration

Unix 6.5.0.1024

**Comment by vcsjones** [comment] 2024-09-25 02:04
This is a duplicate of https://github.com/dotnet/runtime/issues/80118 and https://github.com/dotnet/runtime/issues/76816.

See those issues for an explanation of why this is expected behavior.

**Comment by MihaZupan** [comment] 2024-09-30 15:12
Closing as (unfortunately) by design as per above info.

**Closed by MihaZupan** 2024-09-30 15:12 UTC
Labels: area-System.Net, untriaged
