### ISSUE TITLE
Test failure: tracing/eventpipe/bigevent/bigevent/bigevent.sh

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#51133] opened 2021-04-12 17:44 UTC
GCStress=3, OSX arm64

Test timeout (1 hour timeout)

https://dev.azure.com/dnceng/public/_build/results?buildId=1082387&view=ms.vss-test-web.build-test-results-tab&runId=33192976&resultId=108630&paneView=debug

**Comment by BruceForstall** [comment] 2021-04-12 17:44
@sdmaclea

**Comment by sdmaclea** [comment] 2021-06-09 18:20
@Josalem I think we can just leave this test disabled unless you disagree.

**Comment by josalem** [comment] 2021-06-09 20:24
Was the issue on ASi ever root caused?

**Comment by sdmaclea** [comment] 2021-06-09 20:34
No root cause.  This was timing out with GCStress...  The bigevent said maybe gcstress incompatible was reasonable.

**Comment by noahfalk** [comment] 2021-07-21 08:14
Closing based on @sdmaclea's suggestion. We'll leave the test disabled on GC-stress.

**Closed by noahfalk** 2021-07-21 08:14 UTC
Labels: GCStress, arch-arm64, area-Tracing-coreclr, disabled-test, os-mac-os-x
