### ISSUE TITLE
Add string indexer and use EnumerateArray as default in System.Text.Json.JsonElement

### ISSUE THREAD

**Issue by kevinandrewsde** [dotnet/runtime#2144] opened 2020-01-24 15:23 UTC
Would it be possible to add a this[string property] indexer to System.Text.Json.JsonElement?
Additionally, could we make JsonElement implement IEnumerable using the JsonElement.ArrayEnumerator as default?

The advantage would be simple usage more akin to the way Newtonsoft JObject works, allowing for more concise Json document parsing code when using dynamic access.

For example, assuming we have a JsonElement:
`var deserialized = JsonDocument.Parse(File.ReadAllText("example.json")).RootElement;`

the following Lines could be simplified:
```
foreach (var question in deserialized.GetProperty("quiz").GetProperty("questions").EnumerateArray())
{
    Console.WriteLine(question.GetProperty("question"));
}
```

to:
```
foreach (var question in deserialize["quiz"]["questions"])
{
    Console.WriteLine(question["question"]);
}
```

I would be willing to complete these changes if it is considered a good idea.

**Comment by ahsonkhan** [comment] 2020-01-25 04:17
> Would it be possible to add a this[string property] indexer to System.Text.Json.JsonElement?

I certainly see the benefit of adding a string indexer to `JsonElement`, where the code you write becomes smaller/simplified.

However, this was brought up in the initial design and discussion of `JsonElement` and we decided not to do so. 
https://github.com/dotnet/corefx/issues/33968

> * The string (and `ReadOnlySpan<char>` and `ReadOnlySpan<byte>`) indexer(s) are now a `GetProperty` method group to convey that they're more than O(1) expensive.

For some context, unlike `JObject` which is a type that represents only Json Objects, `JsonElement` is a union type that represents any JSON token (for example Json array, Json Number, etc.). Having a string indexer only makes sense if the `JsonElement` was a JSON object, but doesn't make sense for an array or a single value types like number, string, true, or false, just like how the integer indexer that we have on `JsonElement` only makes sense for arrays.

Unlike the integer indexer, however, the string indexer cannot be made O(1) in any case because of how `JsonElement` represents the JSON data. It would have to enumerate through all the properties to find the matching one.

Here are some guidelines we tend to follow for indexer properties:
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/property

Adding one now would violate this one since we already have a `GetProperty` method:
> DO NOT provide both an indexer and methods that are semantically equivalent.

That said, we are currently working on a writable DOM feature, which is implemented as a set of `JsonNode` types. We have a `JsonObject` type which implements `JsonNode` and does have a string indexer. See https://github.com/dotnet/corefx/issues/39922
https://github.com/dotnet/runtime/blob/3ec5b24c5cc9ef03e687e4a58ae69a6ab07b66ef/src/libraries/System.Text.Json/src/System/Text/Json/Node/JsonObject.cs#L45

> Additionally, could we make JsonElement implement IEnumerable using the JsonElement.ArrayEnumerator as default?

Regarding `EnumerateArray`, the problem is similar. Since `JsonElement` is a union type, the value of `deserialized.GetProperty("quiz").GetProperty("questions")` could be a JSON object OR some primitive value like number or string instead of a JSON array. What would calling `foreach(...)` in those cases do? Having `foreach(...)` throw for those cases, seemingly silently, would be surprising to folks, which is why we opted to have explicit `EnumerateArray` and `EnumerateObject` method calls. Those method calls can throw if the `JsonElement` has an invalid `ValueKind`, making the error case more explicit to the caller.

For future reference, here's the guideline for the types of details to provide when creating new API proposals (motivation, API shape, sample usage, etc.):
https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md#steps

> `var deserialized = JsonDocument.Parse(File.ReadAllText("example.json")).RootElement;`

As an aside, since JsonDocument is `IDisposable`, you should dispose of it by putting it in a `using`:
```C#
using JsonDocument doc = JsonDocument.Parse(File.ReadAllText("example.json"));
JsonElement deserialized = doc.RootElement;
```

cc @bartonjs

**Comment by ahsonkhan** [comment] 2020-01-25 04:24
> I would be willing to complete these changes if it is considered a good idea.

Thanks, appreciate the offer. Given the design of `JsonElement`, the ideas you proposed were intentionally left out when discussed previously. **We could consider re-evaluating this but I doubt the conclusion will change.** In the meantime, we have several JSON features and issues in the backlog and would love contributions if you are interested:
- https://github.com/dotnet/runtime/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Aarea-System.Text.Json+milestone%3A5.0+
- https://github.com/dotnet/corefx/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Aarea-System.Text.Json+milestone%3A5.0+

If other areas interest you:
- https://github.com/dotnet/runtime/issues?q=is%3Aopen+is%3Aissue+label%3Aeasy
- https://github.com/dotnet/corefx/issues?q=is%3Aopen+is%3Aissue+label%3Aeasy

**Comment by layomia** [comment] 2020-04-07 04:50
Closing given design considerations detailed above.

**Closed by layomia** 2020-04-07 04:50 UTC
Labels: api-suggestion, area-System.Text.Json
