### ISSUE TITLE
Blazor Wasm Debugging Crashes on Startup

### ISSUE THREAD

**Issue by groogiam** [dotnet/runtime#83521] opened 2023-03-16 16:13 UTC
### Description

When attempting to debug my blazor wasm application the debugger crashes on startup.
This just started happening after the latest visual studio updated.

```
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] sending error response for id: msg-4269811E00C32EE1828C126AF20CC992:::1041 -> [Result: IsOk: False, IsErr: True, Value: , Error: {   "code": -32601,   "message": "'DotnetDebugger.setDebuggerProperty' wasn't found" } ]
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] sending error response for id: msg-4269811E00C32EE1828C126AF20CC992:::1042 -> [Result: IsOk: False, IsErr: True, Value: , Error: {   "code": -32601,   "message": "'DotnetDebugger.setDebuggerProperty' wasn't found" } ]
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] sending error response for id: msg-4269811E00C32EE1828C126AF20CC992:::1043 -> [Result: IsOk: False, IsErr: True, Value: , Error: {   "code": -32601,   "message": "'DotnetDebugger.setDebuggerProperty' wasn't found" } ]
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] sending error response for id: msg-4269811E00C32EE1828C126AF20CC992:::1044 -> [Result: IsOk: False, IsErr: True, Value: , Error: {   "code": -32601,   "message": "'DotnetDebugger.setDebuggerProperty' wasn't found" } ]
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] sending error response for id: msg-4269811E00C32EE1828C126AF20CC992:::1045 -> [Result: IsOk: False, IsErr: True, Value: , Error: {   "code": -32601,   "message": "'DotnetDebugger.setDebuggerProperty' wasn't found" } ]
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] sending error response for id: msg-4269811E00C32EE1828C126AF20CC992:::1046 -> [Result: IsOk: False, IsErr: True, Value: , Error: {   "code": -32601,   "message": "'DotnetDebugger.setDebuggerProperty' wasn't found" } ]
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] sending error response for id: msg-4269811E00C32EE1828C126AF20CC992:::1047 -> [Result: IsOk: False, IsErr: True, Value: , Error: {   "code": -32601,   "message": "'DotnetDebugger.setDebuggerProperty' wasn't found" } ]
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] sending error response for id: msg-4269811E00C32EE1828C126AF20CC992:::1048 -> [Result: IsOk: False, IsErr: True, Value: , Error: {   "code": -32601,   "message": "'DotnetDebugger.setDebuggerProperty' wasn't found" } ]
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] sending error response for id: msg-4269811E00C32EE1828C126AF20CC992:::1049 -> [Result: IsOk: False, IsErr: True, Value: , Error: {   "code": -32601,   "message": "'DotnetDebugger.setDebuggerProperty' wasn't found" } ]
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] DevToolsProxy::Run: Exception System.AggregateException: One or more errors occurred. (Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index'))  ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')    at System.Collections.Generic.List`1.get_Item(Int32 index)    at Newtonsoft.Json.Linq.JContainer.GetItem(Int32 index)    at Newtonsoft.Json.Linq.JArray.get_Item(Object key)    at Microsoft.WebAssembly.Diagnostics.MonoProxy.AcceptEvent(SessionId sessionId, String method, JObject args, CancellationToken token)    at Microsoft.WebAssembly.Diagnostics.DevToolsProxy.OnEvent(SessionId sessionId, String method, JObject args, CancellationToken token)    --- End of inner exception stack trace ---    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)    at System.Threading.Tasks.Task`1.get_Result()    at Microsoft.WebAssembly.Diagnostics.DevToolsProxy.Run(Uri browserUri, WebSocket ideSocket)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
```

This may be related to this https://github.com/dotnet/runtime/issues/76026#issuecomment-1308838811

### Reproduction Steps

Debug ASP.NET Core Server backed blazor wasm app in visual studio. 

### Expected behavior

Debugger and application should not crash.

### Actual behavior

Debugger crashes.

### Regression?

Worked prior to 17.5.2 visual studio update.

### Configuration

Using chrome browser.

dotnet info

```
.NET SDK:
 Version:   7.0.202
 Commit:    6c74320bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.202\

Host:
  Version:      7.0.4
  Architecture: x64
  Commit:       0a396acafe

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.201 [C:\Program Files\dotnet\sdk]
  7.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by thaystg** [comment] 2023-03-16 16:16
@groogiam Which version of chrome or edge are you using?

**Comment by groogiam** [comment] 2023-03-16 16:43
Installing chrome beta and using that to debug fixes my issue. That should get me by until the the fix ships. Thanks for your help.

**Comment by halter73** [comment] 2023-03-17 18:55
Someone reported seeing this same ArgumentOutOfRangeException from MonoProxy.AcceptEvent recently via VS feedback.

```
DevToolsProxy::Run: Exception System.AggregateException: One or more errors occurred. (Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')) 
---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')   
   at System.Collections.Generic.List`1.get_Item(Int32 index)   
   at Newtonsoft.Json.Linq.JContainer.GetItem(Int32 index)   
   at Newtonsoft.Json.Linq.JArray.get_Item(Object key)   
   at Microsoft.WebAssembly.Diagnostics.MonoProxy.AcceptEvent(SessionId sessionId, String method, JObject args, CancellationToken token)   
   at Microsoft.WebAssembly.Diagnostics.DevToolsProxy.OnEvent(SessionId sessionId, String method, JObject args, CancellationToken token)    
   --- End of inner exception stack trace ---   
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)   
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)   
   at System.Threading.Tasks.Task`1.get_Result()   
   at Microsoft.WebAssembly.Diagnostics.DevToolsProxy.Run(Uri browserUri, WebSocket ideSocket)
```

Doesn't this ArgumentOutOfRangeException looks suspiciously similar to #66149? I thought this kind of exception wouldn't be possible after #67243 was merged. Do we know why we're still seeing this? Are people using version 7 or later of Microsoft.AspNetCore.Components.WebAssembly.Server?

I understand this isn't an issue with every browser, but I assume the debugger should never crash with an ArgumentOutOfRangeException here. I think we should probably keep this issue open since it seems to be the only issue that contains this stack trace other than #66149 which was closed last year. See https://github.com/search?q=repo%3Adotnet%2Fruntime+MonoProxy+ArgumentOutOfRangeException&type=issues

Maybe the others should be marked as a dupe of this since it include a stack trace. Feel free to close if this is better tracked elsewhere, but I'm reopening now in case the stack trace was missed. It's kinda hidden in one log line. I only found it because I searched for similar errors to the VS feedback on github.

**Comment by thaystg** [comment] 2023-03-17 19:22
This is another error, related to a change that chrome did. Chrome also has already fixed it, that is why it's working on beta and dev versions. Probably it will work again on all Chrome and Edge version soon.

**Closed by thaystg** 2023-03-17 19:22 UTC
Labels: untriaged, area-Debugger-mono
