### ISSUE TITLE
Problem with interception StandardOutput in Linux

### ISSUE THREAD

**Issue by ViTokarev** [dotnet/runtime#73923] opened 2022-08-14 21:33 UTC
### Description

I described the problem in detail in "Reproduction Steps". When I run the code and the process has started, the console output is empty.

### Reproduction Steps

I downloaded from the official site: SA-MP, sever: version 0.3.7-R2 Linux Server (x86) and I try to run this server with my code, getting its output.

```c#
            string filePath = "/media/vscode/samp03svr";

            using (Process process = new Process())
            {
                process.StartInfo.FileName = filePath;
                process.StartInfo.UseShellExecute = false;
                process.StartInfo.RedirectStandardOutput = true;
                //process.StartInfo.WorkingDirectory = folderPath;
                process.OutputDataReceived += new DataReceivedEventHandler((sender, e) =>
                {
                    // Prepend line numbers to each line of the output.
                    if (!String.IsNullOrEmpty(e.Data))
                    {
                        Console.WriteLine(e.Data);
                    }
                    else
                        Console.WriteLine("emtpy");
                });

                Console.WriteLine("Process ready to start");

                var status = process.Start();
                if (status)
                    Console.WriteLine("Process start!");
                else
                    Console.WriteLine("Process DON'T start");

                process.BeginOutputReadLine();


                Console.WriteLine("Process WaitForExit");

                process.WaitForExit();

            }
```

### Expected behavior

Create and a new process and intercept its output.

### Actual behavior

The code starts a new process, and after that it doesn't output anything. No matter how I tried to get the rows.

### Known Workarounds

This code works fine under Windows (and windows version SA-MP server) and intercepts the "server" text that runs the code

### Configuration

.NET6 / debian / linux x64

**Comment by danmoseley** [comment] 2022-08-15 00:59
@tmds

**Comment by tmds** [comment] 2022-08-15 05:15
When I replace:
```
            process.StartInfo.FileName = filePath;
```
with
```
    process.StartInfo.FileName = "hexdump";
    process.StartInfo.Arguments = "-c /dev/random";
```
it works fine on Fedora 36.

If you start the executable on the command-line and redirect its output to a file. Does text appear in the file?
```
/media/vscode/samp03svr >/tmp/output
```

**Comment by ViTokarev** [comment] 2022-08-15 07:50
@tmds 
> When I replace:
> 
> ```
>             process.StartInfo.FileName = filePath;
> ```
> 
> with
> 
> ```
>     process.StartInfo.FileName = "hexdump";
>     process.StartInfo.Arguments = "-c /dev/random";
> ```
I don't know what for, but I checked. I have an output too. But this is not the file with which I have a problem. I think this is a special situation.
Especially for testing, I indicated which file I ran so that you can download and test it.

> If you start the executable on the command-line and redirect its output to a file. Does text appear in the file?
> 
> ```
> /media/vscode/samp03svr >/tmp/output
> ```

Yes, it does. The text is output to a file. Before writing here, I tried all the obvious options)

**Comment by ViTokarev** [comment] 2022-08-15 08:54
I have tried different options. Events, functions, streams, none of it works. It is on the Read(), ReadToEnd() functions or an attempt to read the stream:

```
using (System.IO.StreamReader reader = process.StandardOutput)
                {
                    char[] buffer = new char[1024];
                    int read;
                    while ((read = reader.ReadBlock(buffer, 0, buffer.Length)) > 0)
                    {
                        for (int i = 0; i < read; i++)
                            Console.WriteLine(buffer[i]);
                    }
                }
```
In all cases, the program seems to get stuck while performing the read function and does not continue to be executed.

---

The only output is "StandardOutput.CurrentEncoding":
`stdSystem.Text.UTF8Encoding+UTF8EncodingSealed|`

---

But it is worth removing the property:
`StartInfo.RedirectStandardOutput = true;`
And the output goes to the console. (just to make sure the output exists)

**Comment by tmds** [comment] 2022-08-16 04:57
> I downloaded from the official site: SA-MP, sever: version 0.3.7-R2 Linux Server (x86) and I try to run this server with my code, getting its output.

Do you have a link?

**Comment by ViTokarev** [comment] 2022-08-16 06:50
@tmds https://www.sa-mp.com/download.php

Direct link to download the file from the same site:
http://files.sa-mp.com/samp037svr_R2-1.tar.gz

**Comment by tmds** [comment] 2022-08-16 14:51
The issue is in `samp03srv`.

To do something similar as .NET redirect on the shell, I run: `./samp03svr | less`.

There is no output.

When I terminate by pressing `Ctrl+C` the application output is printed (`Started server on port: 7777, with maxplayers: 50 lanmode is OFF.`).

**Comment by ViTokarev** [comment] 2022-08-18 14:00
> To do something similar as .NET redirect on the shell, I run: `./samp03svr | less`.

Okay, this only works in the shell, but wouldn't it be worth extending the .NET implementation of output interception to prevent such situations?

For example, I still don't know how to intercept such an output and I think such specific cases can happen.
What should developers do in this case if they do not have a possible solution?

**Comment by ViTokarev** [comment] 2022-08-18 15:52
> .NET is not at fault: it doesn't read anything because the child process doesn't write.

But why is it that when I just run "./samp03svr" in the terminal, the output goes to the terminal immediately.

Exactly how I start the "samp03svr" process in .NET code, but without the output redirect, I get the output in the terminal.

**Comment by Jozkee** [comment] 2023-06-21 22:19
@ViTokarev Could it be that `samp03svr` is writing to stderr? Feel free to share and finds in why this specific program doesn't write to the standard output. 

Currently, this doesn't seem actionable on .NET's end so I will go ahead and close it.

**Closed by Jozkee** 2023-06-21 22:19 UTC
Labels: area-System.Diagnostics.Process
