### ISSUE TITLE
Allows JsonStringEnumConverter.CreateConverter to specify a default enum value

### ISSUE THREAD

**Issue by caihongxu** [dotnet/runtime#30851] opened 2019-09-13 18:51 UTC
that allows parsing unrecognized strings/numbers into a specified default enum value. Currently if unrecognized strings/numbers are encountered an exception is thrown.

**Comment by eiriktsarpalis** [comment] 2021-10-15 18:35
Duplicate of #57031

**Closed by eiriktsarpalis** 2021-10-15 18:35 UTC
Labels: enhancement, area-System.Text.Json
