### ISSUE TITLE
Plan to include Regex based Replace option in StringBuilder

### ISSUE THREAD

**Issue by egvijayanand** [dotnet/runtime#62730] opened 2021-12-13 16:39 UTC
Undoubtedly, StringBuilder is a performance booster when working with lot of strings.

But one thing that we as developers miss the most is Regex based Replace option that will make it even more efficient.

Kindly plan to include such an option in the upcoming release.

**Comment by huoyaoyuan** [comment] 2021-12-14 10:15
Note that cost of regex can be *huge* when comparing to string and StringBuilder. Cost of simple wildcards are much less and predictable.

**Comment by alexandrehtrb** [comment] 2022-07-12 18:59
I imagine that using a Regex in StringBuilder would save memory compared to converting the StringBuilder to string first, then applying the Regex.
I think this feature is quite interesting.

**Comment by danmoseley** [comment] 2022-07-12 23:02
We added `ReadOnlySpan<char>` overloads to Regex methods this release to reduce the need to materialize a string simply to run a regex on it. The problem is that StringBuilders are (in general) a linked list of buffers.  The existing regex engines would need significant work to be able to run over a list of buffers. This is essentially the "streaming regex" feature. As far as I'm aware, most engines don't have this -- [Hyperscan is one that does](https://www.intel.com/content/www/us/en/developer/articles/technical/introduction-to-hyperscan.html)

this illustrates the problem
```c#

using System;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

var sb = new StringBuilder(1); // force chunking

sb.Append("a w");
sb.Append("ord here");

Console.WriteLine($"StringBuilder content is '{sb.ToString()}' but chunked");
Console.WriteLine();

foreach (ReadOnlyMemory<char> chunk in sb.GetChunks())
{
	Console.WriteLine($"Chunk of {chunk}");
    foreach(ValueMatch m in Regex.EnumerateMatches(chunk.Span, @"\b\w+\b"))
    {
    	Console.WriteLine($"Match words in '{chunk.Slice(m.Index, m.Length)}'");
    }
    Console.WriteLine();
}
```
which produces
```
StringBuilder content is 'a word here' but chunked

Chunk of a
Match words in 'a'

Chunk of  w
Match words in 'w'

Chunk of ord here
Match words in 'ord'
Match words in 'here'
```

So -- you can do this today, as above, but only if you pre-size your StringBuilder or otherwise arrange for it to be in a contiguous chunk. (Or, if you have a regex that is literally just looking for a single character with no context?)

> But one thing that we as developers miss the most is Regex based Replace option that will make it even more efficient.

StringBuilder replace itself can be a [perf trap if it's chunked](https://github.com/dotnet/runtime/blob/d18554c73e7ee2f95240ade2ef1fee8a59c99772/src/libraries/System.Private.CoreLib/src/System/Text/StringBuilder.cs#L1857-L1922). 

I don't think we have an issue tracking adding streaming support because it would be a huge feature and it's not contemplated. @dotnet/area-system-text-regularexpressions ?

**Comment by danmoseley** [comment] 2022-07-12 23:11
@egvijayanand just curious what you have in mind by 'efficient' here. Would the primary win for you be - not creating strings from StringBuilders? Or not creating strings when you do replacements?

If most of the allocations are the replacing part, you can of course do that without creating strings -- just implement Replace yourself. Also, if it would be used enough, Regex could add Replace overloads that take `Span<char>`.

Other options - dechunkify your StringBuilders by writing into a new StringBuilder -- still an allocation, but your Replaces are in the StringBuilder.

Or the highest performance way you could do this today -- copy the StringBuilder content (perhaps iff it's > 1 chunk) into a pooled array, and regex over that. Again, you'd need to implement Replace as Regex doesn't have overloads that take `Span<char>`

**Comment by danmoseley** [comment] 2022-07-13 17:26
> One issue that would need to be contemplated here is what if the replacement is larger than the original match causing the result to not fit on the passed in Span? 

Right-- I was assuming it would be the same size.

Given this would need streaming as written, my suggestion is to close this. It would be fine to open an issue that's entirely focused on streaming although I don't expect us to do that anytime soon given the size of the work vs. the limited known need. (My guess is that if we really needed streaming support in .NET we'd first look at what interop with an existing library might look like.)

**Closed** 2024-01-14 04:42 UTC
Labels: api-suggestion, area-System.Text.RegularExpressions
