### ISSUE TITLE
crossgen2 packages missing native components

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/runtime#37196] opened 2020-05-30 08:03 UTC
### Description

Running crossgen2.exe using recent SDK  (ex: 5.0.100-preview.6.20280.6) is not working.
This is because the platform-specific crossgen2 packages are missing native binaries.

For example: 
Microsoft.NETCore.App.Runtime.win-x64 (ver 5.0.0-preview.6.20277.12) doesn't have clrcompression.dll
Microsoft.NETCore.App.Runtime.linux-x64 (ver 5.0.0-preview.6.20264.1) doesn't have libSystem.Globalization.Native.a

Consequently, running crossgen2.exe from this package fails because of a missing dependency.

### Repro

Publish a hello-world app using master-branch SDK (5.0.100-preview.6.20280.6) with  `PublishReadyToRun=true`  and `PublishReadyToRunUseCrossgen2=true`.

```
D:\test\hello>dotnet publish -r win-x64 /p:PublishReadyToRun=true /p:PublishReadyToRunUseCrossgen2=true
Microsoft (R) Build Engine version 16.7.0-preview-20270-03+bee129d1b for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored D:\test\hello\hello.csproj (in 95 ms).
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  hello -> D:\test\hello\bin\Debug\net5.0\win-x64\hello.dll
C:\Program Files\dotnet\sdk\5.0.100-preview.6.20278.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(376,5): error : Error: [D:\test\hello\hello.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.6.20278.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(376,5): error :   An assembly specified in the application dependencies manifest (crossgen2.deps.json) was not found: [D:\test\hello\hello.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.6.20278.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(376,5): error :     package: 'runtimepack.Microsoft.NETCore.App.Runtime.win-x64', version: '5.0.0-preview.5.20230.9' [D:\test\hello\hello.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.6.20278.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(376,5): error :     path: 'clrcompression.dll' [D:\test\hello\hello.csproj]
C:\Program Files\dotnet\sdk\5.0.100-preview.6.20278.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(286,5): error NETSDK1096: Optimizing assemblies for performance failed. You can either exclude the failing assemblies from being optimized, or set the PublishReadyToRun property to false. [D:\test\hello\hello.csproj]
```
```
~/test/hello$ ../dotnet-5.preview6/dotnet publish -r linux-x64  /p:PublishReadyToRun=true /p:PublishReadyToRunUseCrossgen2=true
Microsoft (R) Build Engine version 16.7.0-preview-20270-03+bee129d1b for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /home/swaroops/test/hello/hello.csproj (in 11.88 sec).
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  hello -> /home/swaroops/test/hello/bin/Debug/net5.0/linux-x64/hello.dll
/home/swaroops/test/dotnet-5.preview6/sdk/5.0.100-preview.6.20280.6/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(376,5): error : Error: [/home/swaroops/test/hello/hello.csproj]
/home/swaroops/test/dotnet-5.preview6/sdk/5.0.100-preview.6.20280.6/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(376,5): error :   An assembly specified in the application dependencies manifest (crossgen2.deps.json) was not found: [/home/swaroops/test/hello/hello.csproj]
/home/swaroops/test/dotnet-5.preview6/sdk/5.0.100-preview.6.20280.6/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(376,5): error :     package: 'runtimepack.Microsoft.NETCore.App.Runtime.linux-x64', version: '5.0.0-preview.6.20264.1' [/home/swaroops/test/hello/hello.csproj]
/home/swaroops/test/dotnet-5.preview6/sdk/5.0.100-preview.6.20280.6/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(376,5): error :     path: 'libSystem.Globalization.Native.a' [/home/swaroops/test/hello/hello.csproj]
/home/swaroops/test/dotnet-5.preview6/sdk/5.0.100-preview.6.20280.6/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(286,5): error NETSDK1096: Optimizing assemblies for performance failed. You can either exclude the failing assemblies from being optimized, or set the PublishReadyToRun property to false. [/home/swaroops/test/hello/hello.csproj]
```

### Regression?
The problem seems to have started in the last few days, after SDK 5.0.100-preview.6.20266.3.

**Comment by swaroop-sridhar** [comment] 2020-05-30 08:09
CC: @trylek @nattress

**Comment by nattress** [comment] 2020-06-01 20:11
I tried a few recent CG2 packages and some are failing due to being unable to resolve native assets (clrcompression, some are missing SOS_README.md). It looks like the crossgen2 package scripting is brittle and it's time to integrate crossgen2 into Arcade's shared framework: https://github.com/dotnet/runtime/issues/1867

**Comment by nattress** [comment] 2020-06-01 20:14
This is how we currently build the package: https://github.com/dotnet/runtime/blob/660d321e5faba4a5ea5a6327e868e945da1dd625/src/installer/pkg/projects/netcoreapp/pkg/Microsoft.NETCore.App.Crossgen2.pkgproj#L46

**Comment by mangod9** [comment] 2020-06-03 16:44
what is the impact of this? Is the sdk unable to produce any crossgen2-ed binaries or is this for a particular scenario?

**Comment by swaroop-sridhar** [comment] 2020-06-03 22:42
@mangod9  native binaries were missing (non-deterministically) from various crossgen2 packages. When the expected components are missing, crossgen2 cannot be run. That is, all `dotnet publish /p:PublishReadyToRun=true /p:PublishReadyToRunUseCrossgen2=true` runs will fail.

**Comment by swaroop-sridhar** [comment] 2020-06-03 22:59
@nattress  and I talked about it -- the problem could be a race between the construction of microsoft.netcore.app and microsoft.netcore.app.crossgen2 packages.

**Comment by mangod9** [comment] 2020-06-03 23:15
ok assigning to @nattress for now, since we will have revisit all of this to enable composite mode within the sdk.

**Comment by mangod9** [comment] 2020-06-24 22:25
Tagging @AntonLapounov as well since he is looking into enabling composite mode in sdk.

**Closed** 2020-07-01 05:16 UTC
Labels: area-crossgen2-coreclr

**Comment by mangod9** [comment] 2020-07-01 05:22
Thanks @AntonLapounov for resolving this.

**Comment by AntonLapounov** [comment] 2020-07-04 00:54
For the record, this was caused by appending a trailing slash to `TargetPath` in netcoreapp.depproj file in #36781: https://github.com/dotnet/runtime/pull/36781/files#diff-9fac0b3c275ca346bd7e392f9ae3807cL108-R108, which made the native files to be omitted by the following line in Microsoft.NETCore.App.Crossgen2.pkgproj:
```xml
<Crossgen2File Include="@(RuntimeFile)" Condition="'%(RuntimeFile.TargetPath)' == 'runtimes/$(PackageRID)/native'" />
```
