### ISSUE TITLE
macOS: Time Zone round-tripping through ToSerializedString/FromSerializedString is broken

### ISSUE THREAD

**Issue by filipnavara** [dotnet/runtime#63889] opened 2022-01-17 15:51 UTC
### Description

Round-tripping of certain system time zones is broken.

### Reproduction Steps

```csharp
var cet = TimeZoneInfo.FindSystemTimeZoneById("Europe/Dublin");
var cetSerialized = cet.ToSerializedString();
var cetDeserialized = TimeZoneInfo.FromSerializedString(cetSerialized);
```

### Expected behavior

No exception.

### Actual behavior

```
Unhandled exception. System.Runtime.Serialization.SerializationException: An error occurred while deserializing the object.  The serialized data is corrupt.
 ---> System.InvalidTimeZoneException: The elements of the AdjustmentRule array must be in chronological order and must not overlap.
   at System.TimeZoneInfo.ValidateTimeZoneInfo(String id, TimeSpan baseUtcOffset, AdjustmentRule[] adjustmentRules, Boolean& adjustmentRulesSupportDst)
   at System.TimeZoneInfo..ctor(String id, TimeSpan baseUtcOffset, String displayName, String standardDisplayName, String daylightDisplayName, AdjustmentRule[] adjustmentRules, Boolean disableDaylightSavingTime, Boolean hasIanaId)
   at System.TimeZoneInfo.StringSerializer.GetDeserializedTimeZoneInfo(String source)
   --- End of inner exception stack trace ---
   at System.TimeZoneInfo.StringSerializer.GetDeserializedTimeZoneInfo(String source)
   at System.TimeZoneInfo.FromSerializedString(String source)
   at Program.<Main>$(String[] args) in /Users/filipnavara/Projects/tzrt/Program.cs:line 4
```

### Configuration

.NET 6.0.1
macOS Monterey 12.0.1
ARM64 and x64

**Comment by tarekgh** [comment] 2022-01-17 19:40
Duplicate of https://github.com/dotnet/runtime/issues/19794

**Closed by tarekgh** 2022-01-17 19:40 UTC
Labels: area-System.Globalization, untriaged

**Comment by garyhertel** [comment] 2022-02-09 18:12
This is still an active bug in the latest 6.0.2 release. On MacOS Monterey 12, I run into the same problem serializing and deserializing a TimeZoneInfo. Using a .NET Core 3.1.x runtime, I don't see this issue. I also don't see this problem on Windows.

```
TimeZoneInfo input = TimeZoneInfo.FindSystemTimeZoneById("Pacific Standard Time");
string serializedString = input.ToSerializedString();
TimeZoneInfo output = TimeZoneInfo.FromSerializedString(serializedString);
```

**Comment by tarekgh** [comment] 2022-02-09 18:20
@garyhertel first, we don't recommend doing the serialization this way as you can just serialize only the Zone Id. Also, this problem was happening on non-Windows platforms only. It is related to how we exposed the time zone `AdjustmentRule's` on Linux.

**Comment by garyhertel** [comment] 2022-02-09 18:30
That works for non-custom time zones. However, the daylight savings versions are often missing and have to be added as custom time zones. So serializing then requires exporting the time zone offset too. The serialized time zones are ridiculously large though, so it probably is warranted to only serialize the first 5 fields.

**Comment by tarekgh** [comment] 2022-02-09 19:07
@garyhertel, you are right.  

> the daylight savings versions are often missing and have to be added as custom time zones.

Could you please elaborate more on that?

**Comment by garyhertel** [comment] 2022-02-09 19:13
That could easily be a misunderstanding on my part, but I have a DropDown field that lets you select the TimeZone like PDT or PST depending on what a customer puts in a ticket. (maybe they're effectively the same thing and I should list both PDT & PST in the label for PST?)

**Comment by tarekgh** [comment] 2022-02-09 19:48
I am not sure how things work for your product, but in general you need to list the time zones for the user (just using the display names), and you don't need to duplicate the same zone to differentiate between standard time and daylight-saving time. If I am a user and see PDT and PST in the list to choose from, that for sure will confuse me. 

CC @mattjohnsonpint as FYI.

**Comment by garyhertel** [comment] 2022-02-10 03:13
Thanks for the help! I think I've found a much better solution for both the drop down and serialization that's more inline with what you're saying.

It would probably still be good to fix the bug, but I don't think it should be an issue for me after these changes.

**Comment by mattjohnsonpint** [comment] 2022-02-10 03:39
Just wanted to add, the whole concept of "custom time zones" is flawed.  So is the serialized string format.  The only reason .NET still supports them is for API compatibilty.  In general, don't use them.  All the time zones of the world are provided by the system, and referenced by their ID.

**Comment by danmoseley** [comment] 2022-02-10 04:01
Good to still see you here from time to time @mattjohnsonpint !
