### ISSUE TITLE
Behavior change in NullabilityInfoContext between .NET 8 and .NET 9

### ISSUE THREAD

**Issue by mlorbetske** [dotnet/runtime#106636] opened 2024-08-19 14:52 UTC
### Description

In .NET 8 nullability context info for a constructor parameter that is based on a generic argument always returned `NotNull` (even when the supplied argument was nullable). In .NET 9, that behavior changes to always returning `Nullable` (even when the supplied argument was not null).

In our codebase, we're using the nullability context to determine whether a given parameter is optional (in conjunction with type information - like `Nullable<T>` - and default parameter values). While the .NET 8 behavior would overreport requiredness (since more things would be flagged as not being nullable than would actually be the case), the .NET 9 behavior underreports requiredness since all reference type fulfilments of the type parameter now indicate that they are nullable.

If the nullability of the supplied argument isn't being respected, I think it'd be preferable to move to returning `Unknown` for the read and write states, but that may be out of scope for just considering the difference in behavior between the two runtime versions.

### Reproduction Steps

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <!--<TargetFramework>net9.0</TargetFramework>-->
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
```

```csharp
using System.Reflection;

var parameter = typeof(HasGenericParameter<object>).GetConstructors()[0].GetParameters()[0];
var nullabilityContextInfo = new NullabilityInfoContext().Create(parameter);

Console.WriteLine("HasGenericParameter<object>.ctor(object parameter)");
Console.WriteLine(nullabilityContextInfo.ReadState);
Console.WriteLine(nullabilityContextInfo.WriteState);

parameter = typeof(HasGenericParameter<object?>).GetConstructors()[0].GetParameters()[0];
nullabilityContextInfo = new NullabilityInfoContext().Create(parameter);

Console.WriteLine("HasGenericParameter<object?>.ctor(object? parameter)");
Console.WriteLine(nullabilityContextInfo.ReadState);
Console.WriteLine(nullabilityContextInfo.WriteState);

/*
.NET 8 Output
=============
HasGenericParameter<object>.ctor(object parameter)
NotNull
NotNull
HasGenericParameter<object?>.ctor(object? parameter)
NotNull
NotNull
*/

/*
.NET 9 Output
=============
HasGenericParameter<object>.ctor(object parameter)
Nullable
Nullable
HasGenericParameter<object?>.ctor(object? parameter)
Nullable
Nullable
*/
public class HasGenericParameter<T>(T parameter)
{
    public override string? ToString()
    {
        return parameter?.ToString();
    }
}
```

### Expected behavior

The output between .NET 8 and .NET 9 should either be the same, or .NET 9 should move to returning `Unknown` for the nullability of the parameter.

Otherwise, this should probably be documented in the .NET 9 (breaking?) changes

### Actual behavior

.NET 9 reports parameters are nullable when they're reference types and are based on unconstrained (at least) generic type parameters from their containing type.

### Regression?

This is a behavior change between 8.0.7 and 9.0.100-preview.7.24407.12 (at least)

### Known Workarounds

Behaviorally, not using the nullability context info for parameters that fit the above circumstances is the only workaround I've been able to find so far (leveraging just reference vs value type information and default values from the parameter info)

### Configuration

.NET versions: 8.0.7 and 9.0.100-preview.7.24407.12
OS: Windows 11 (Version 10.0.26120.1350)
Architecture: x64
Specific to configuration?: Reproduced on at least a different version of Windows (10)
Blazor?: Not using Blazor in this case

**Comment by ericstj** [comment] 2024-08-19 16:30
Change seems to be caused by https://github.com/dotnet/runtime/pull/92514 - @buyaa-n @eiriktsarpalis can you have a look?

**Comment by buyaa-n** [comment] 2024-08-19 17:43
> In .NET 8 nullability context info for a constructor parameter that is based on a generic argument always returned NotNull (even when the supplied argument was nullable). In .NET 9, that behavior changes to always returning Nullable

The `always returned NotNull on a generic argument` was a bug which is fixed with https://github.com/dotnet/runtime/pull/92514, in this case it should `always returning Nullablle` because generic parameter T is nullable unless it was constrained to not null.

> always returning Nullable (even when the supplied argument was not null).

This is by design, compiler does not reflect the nullability info from typeof expression, therefore below declarations produce exact same runtime type with same nullability annotations, the type parameter `object` will have nullable annotation for both:

```cs
var parameter = typeof(HasGenericParameter<object>);
var parameter = typeof(HasGenericParameter<object?>);
```

Overall, this is not a regression but a `bug fix` + `existing behavior (typeof operator doesn't reflect nullable)`, and we don't normally document a bug fixes as breaking change

@mlorbetske the current scenario looks expected, please let us know if you have any other scenarios that breaking your app

**Comment by mlorbetske** [comment] 2024-08-19 19:15
Thinking on this, it may be better if I rephrase. Consider this example

```
using System.Reflection;

PrintNullabilityOfParameter(typeof(HasGenericParameter<object>));
PrintNullabilityOfParameter(typeof(HasGenericParameter<object?>));
PrintNullabilityOfParameter(typeof(HasNonGenericNonNullableParameter));
PrintNullabilityOfParameter(typeof(HasNonGenericNullableParameter));

void PrintNullabilityOfParameter(Type type)
{
    var parameter = type.GetConstructors()[0].GetParameters()[0];
    var nullabilityContextInfo = new NullabilityInfoContext().Create(parameter);

    Console.WriteLine($"{type}.ctor({parameter.ParameterType} parameter)");
    Console.WriteLine(nullabilityContextInfo.ReadState);
    Console.WriteLine(nullabilityContextInfo.WriteState);
}

public class HasGenericParameter<T>(T parameter)
{
    public override string? ToString()
    {
        return parameter?.ToString();
    }
}

public class HasNonGenericNullableParameter(object? parameter)
{
    public override string? ToString()
    {
        return parameter?.ToString();
    }
}

public class HasNonGenericNonNullableParameter(object parameter)
{
    public override string? ToString()
    {
        return parameter?.ToString();
    }
}
```

According to the compiler:
* `HasGenericParameter<object>`
  * Has a parameter of type `object`, the runtime type of which is `object`
  * The compiler asserts that `null` should not be supplied to that parameter
  * `NullabilityContextInfo` asserts that `null` may be supplied to that parameter
* `HasGenericParameter<object?>` 
  * Has a parameter of type `object?`, the runtime type of which is `object`
  * The compiler asserts that `null` may be supplied to that parameter
  * `NullabilityContextInfo` asserts that `null` may be supplied to that parameter
* `HasNonGenericNonNullableParameter`
  * Has a parameter of type `object`, the runtime type of which is `object`
  * The compiler asserts that `null` should not be supplied to that parameter
  * `NullabilityContextInfo` asserts that `null` should not be supplied to that parameter
* `HasNonGenericNullableParameter` 
  * Has a parameter of type `object?`, the runtime type of which is `object`
  * The compiler asserts that `null` may be supplied to that parameter
  * `NullabilityContextInfo` asserts that `null` may be supplied to that parameter

Program output:
```
HasGenericParameter`1[System.Object].ctor(System.Object parameter)
Nullable
Nullable
HasGenericParameter`1[System.Object].ctor(System.Object parameter)
Nullable
Nullable
HasNonGenericNonNullableParameter.ctor(System.Object parameter)
NotNull
NotNull
HasNonGenericNullableParameter.ctor(System.Object parameter)
Nullable
Nullable
```

While the .NET 8 behavior was wrong (and deserving of a bug fix), what the .NET 9 behavior does is change the semantic of the API. It no longer answers "is `null` an acceptable input for this parameter", instead it answers the question of "is `null` an acceptable input for this parameter - or - how permissive were the constraints on the generic argument that this method parameter uses". In the latter case, it doesn't actually tell you whether `null` is expected to be accepted by the parameter - and also doesn't err on the side of caution like it did before (saying that the parameter would not accept null, even if it would have).

**Comment by eiriktsarpalis** [comment] 2024-08-27 08:27
I think what might convince you that this is in fact not a bug is taking a look at how nullability is handled for generic properties in .NET 8:

```C#
using System.Reflection;

InspectNullability(typeof(HasGenericParameter<object>)); // Nullable Nullable
InspectNullability(typeof(HasGenericParameter<object?>)); // Nullable Nullable

static void InspectNullability(Type type)
{
    var ctx = new NullabilityInfoContext();

    foreach (PropertyInfo prop in type.GetProperties())
    {
        var info = ctx.Create(prop);
        Console.WriteLine($"{info.WriteState} {info.ReadState}");
    }
}

record HasGenericParameter<T>(T Value);
```

> While I understand how NullabilityInfoContext is deriving its return values, I still don't believe this scenario where, in the IDE new `HasGenericParameter<object>(null)` produces a warning but the parameter info for that parameter says it accepts null is consistent or correct. 

This discrepancy can be explained by the fact that `NullabilityInfoContext` can only work with metadata that is present in IL, and cannot have access to Roslyn APIs. Nullability annotations are compile-time metadata that have no first-class representation in IL. While the compiler can [occasionally emit attribute annotations](https://sharplab.io/#v2:D4AQTAjAsAULIGYAE4kFkD2A7DBbDATgA4AWAlgMZKwDesSDKyIEADEgGoCGANgK4BTJDSQBzAQBcA3EgDOkmQF9YioA) in many cases this information [gets erased](https://sharplab.io/#v2:D4AQTAjAsAULD08AEA5A9kgkgGSQWwFMAXAQwBMTSkyBLAMzoICcCA7Imym1gcySIAWBfgHcMRAJ4AHYQQAeUlgGclNNKyWwQEAGxIQAFlTqUAVwA25kgCNzBABQBKJAF4AfEgAqBJUQA8aNYAVgQAxkRuTgDcWrr6RmaWNnZOrh7evgHBYUQA/JGOMXAw2nqGXj7+ngVIAN5IAL5AA=). It's for this reason that the C# compiler explicitly [marks generic parameters as nullable](https://sharplab.io/#v2:D4AQTAjAsAULIGYAE4kAUD2AbAngWwwCcAHACwEsBjAHgBUA+JWAb1iXZWVqQDUBDLAFcApkmZIA5sIAuAbiQBnGfIC+sFUA) unless the type parameter has been [meaningfully constrained](https://sharplab.io/#v2:D4AQTAjAsAULIGYAE4kAUD2AbAngWwwCcAHACwEsBjAYQwDsBnAF0IENy6BTAEwB4AVAHxIA7qU6FOSfkgBcSOhiZ0ArliywA3rCS6UyGQDVWWFVM1IA5pyYBuJAxv2AvrGdA===).

I think we can close this as by-design behaviour.

**Comment by mlorbetske** [comment] 2024-08-28 14:12
Everything you're saying makes sense, don't get me wrong. I do understand that the information used to make the determinations is in some cases unavailable at runtime as well.

That said, the purpose of this API, as I understand it anyway, is to provide runtime information about whether or not `null` is an expected value in the inspected context. For the purposes of calling a method/constructor via reflection, you'd be inspecting the parameters to understand whether the method was written in such a way that it would gracefully handle a `null` value being passed to it and reasoning about whether the values you have available to you are suitable for calling it. Note that what I'm pointing to here is not how one could expect this API to be implemented or what information is available in order to implement it, but just the expectations around the information one expects to gain by exercising the API.

Putting aside the correctness of implementation (and I agree that it's technically correct, where I'm disconnected is on whether it's returning the answer to the question the user is asking), the .NET 8 behavior was "overly safe". If the method returns that `null` is _not_ accepted as a parameter value (or isn't allowed to be assigned to a property or what have you), you wouldn't expect negative side effects from not supplying `null` in that case. Whether the API is actually returning the values based on the developer's intent or not (or whether that intent is actually knowable) isn't really the important part, it's just whether it's known to be safe/intended to pass/assign null. The .NET 9 behavior now indicates that `null` is acceptable in scenarios where it's not actually acceptable (again, understood that `Nullability(2)` is applied to the unconstrained generic argument and that's what's being used to make the determination in the implementation of the method) which does lead to the potential of negative side effects for supplying `null` in contexts where the code does not actually expect it.

**Comment by eiriktsarpalis** [comment] 2024-08-28 15:10
> the .NET 8 behavior was "overly safe". If the method returns that null is not accepted as a parameter value (or isn't allowed to be assigned to a property or what have you), you wouldn't expect negative side effects from not supplying null in that case.

This happens to hold for the case of parameters since they represent an input, however the opposite is true if you consider types also representing outputs such as property getters or fields. Assuming we decided that `NullabilityInfo` should be returning `NotNull` for unconstrained generics then this would also be in contradiction to generic fields returning `null`. Arguably, generic members should have been made to return `NullabilityState.Unknown` denoting that they're nullable-oblivious, but I think that ship has sailed at this point.

cc @stephentoub for a second opinion.

**Comment by mlorbetske** [comment] 2024-08-28 15:19
Exactly - I'm hoping that we move this to returning Unknown, rather than going back to NotNull.

**Comment by eiriktsarpalis** [comment] 2024-08-28 15:24
I think it's unlikely we'd do this, there is a lot of code out there depending on generic members being reported as `Null` today. If we did decide that it's the right call, it would probably involve updating IL codegen in the compiler as opposed to making a change in the `NullabilityInfo` class. For all intents and purposes though, `Unknown` and `Nullable` are semantically equivalent annotations.

**Comment by mlorbetske** [comment] 2024-08-28 15:35
To the point of a lot of code already depending on this returning nullable - while I don't have telemetry or anything to back it up, I'd assume that most code (coming from RTW .net 8) would have the not null assumption since this is a changed behavior in .net 9 preview. 

On unknown and nullable being semantically equivalent - I don't know that I necessarily agree. While treating them as equivalent is potentially valid, the differentiation between intentional nullability and a user choice in the absence of definitive information seems to be an important one. For my case at least, Unknown is treated as equivalent to not null for assignment and equivalent to nullable for access

**Comment by eiriktsarpalis** [comment] 2024-08-28 16:58
> To the point of a lot of code already depending on this returning nullable - while I don't have telemetry or anything to back it up, I'd assume that most code (coming from RTW .net 8) would have the not null assumption since this is a changed behavior in .net 9 preview.

I can attest that there is a lot of MSFT code that depends on the current behavior, including components in this repo. This is how the bug with generic constructor parameters was discovered and fixed, and we've actually incorporated workarounds for targets that are older than .NET 9:

https://github.com/dotnet/runtime/blob/2aca5e53dba1a620ae5b57972c355eebed0cdb08/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/DefaultJsonTypeInfoResolver.Helpers.cs#L494-L503

> For my case at least, Unknown is treated as equivalent to not null for assignment and equivalent to nullable for access.

That's not how nullable-oblivious types work in the language though. They simply match the semantics pre NRT aka every reference type can be null.

> But yes, I've got an issue open on Roslyn in the event that this would be approached via a codegen change.

I think that's the best place to track this issue, if you can share a link I can close this one in favour of the other.

**Comment by mlorbetske** [comment] 2024-08-28 17:12
https://github.com/dotnet/roslyn/issues/74837 is the issue filed on Roslyn

**Comment by eiriktsarpalis** [comment] 2024-08-29 08:50
Closing in favor of #74837.

**Closed by eiriktsarpalis** 2024-08-29 08:50 UTC
Labels: area-System.Reflection

**Comment by jaredpar** [comment] 2024-09-04 06:34
> It's for this reason that the C# compiler explicitly [marks generic parameters as nullable](https://sharplab.io/#v2:D4AQTAjAsAULIGYAE4kAUD2AbAngWwwCcAHACwEsBjAHgBUA+JWAb1iXZWVqQDUBDLAFcApkmZIA5sIAuAbiQBnGfIC+sFUA) unless the type parameter has been [meaningfully constrained](https://sharplab.io/#v2:D4AQTAjAsAULIGYAE4kAUD2AbAngWwwCcAHACwEsBjAYQwDsBnAF0IENy6BTAEwB4AVAHxIA7qU6FOSfkgBcSOhiZ0ArliywA3rCS6UyGQDVWWFVM1IA5pyYBuJAxv2AvrGdA===).

The compiler is not marking them as nullable here. The compiler is marking them as [being absent a specific set of constraints](https://github.com/dotnet/roslyn/blob/main/docs/features/nullable-metadata.md#type-parameters)

> No notnull, class, struct, unmanaged, or type constraints in #nullable enable context (equivalent to an object? constraint): NullableAttribute(2)

This not so much declaring the nullability of the parameter as it is recording the source annotations to metadata.

**Comment by jaredpar** [comment] 2024-09-04 19:25
Reading through the issue today when I'm a bit more awake than last night. One pattern I see a lot in these examples is the following: 

```csharp
PrintNullabilityOfParameter(typeof(HasGenericParameter<object>));
PrintNullabilityOfParameter(typeof(HasGenericParameter<object?>));
```

These are, for all intents and purposes, the exact same call. The nullable reference type annotations do not factor into `typeof` expressions. That is because `typeof` is a .NET Runtime type mechanism while nulllable annotations are a C# type system mechanism. So `typeof(HasGenericParameter<object>) == HasGenericParameter(List<object?>)`.

Practically speaking that means from the perspective of the .NET libraries there is really no way to provide different behavior for nullable for these two type declarations. There will need to be one response for both declarations. Given that limitation I can understand why `Nullable` was chosen here. 

> But yes, I've got an issue open on Roslyn in the event that this would be approached via a codegen change.

The roslyn code gen is not actually saying "this is null" or "that is not null". Instead the roslyn code gen is translating what was written in source code to metadata so that it can be round tripped later on. That means the `[Nullable(2)]` on the attribute is not making a declaration about null or not null. Instead it's quite literally [encoding](https://github.com/dotnet/roslyn/blob/main/docs/features/nullable-metadata.md#type-parameters)that the type parameter was ...

> No notnull, class, struct, unmanaged, or type constraints in #nullable enable context (equivalent to an object? constraint): NullableAttribute(2)

Round tripping these values through metadata as they are written is a pretty fundamental principle of compilation. Changing that is not really an option here.

**Comment by mlorbetske** [comment] 2024-09-04 21:32
I've added workarounds to indicate in our codebase that the nullability is ambiguous in this case, so we're no longer blocked from moving to .NET 9 - so that's nice at least. I don't know that I'd have closed this as completed (in case others think that the behavior has changed to be in line with .NET 8 from a glance), but also the linked issue for closing is about WASM, just happens to have the same number but in a different repo. At any rate, thank you all for the time.

**Comment by jaredpar** [comment] 2024-09-04 22:06
> maybe as not planned as it is in the Roslyn repo 

There is nothing to change in Roslyn though. The metadata encoding is reflecting the state of the source code for round tripping metadata. It's effectively encoding constraints of the source code as an attribute. The encoding today is accurately reflecting the source code and in line with the specification for that metadata encoding. 

> in case others think that the behavior has changed to be in line with .NET 8 from a glance

There is a level of ambiguity as to what this library API should return when inspecting type parameters because there is information lost when translating from C# type names to runtime `Type` instances. That is an accepted limitation when these APIs were implemented. The libraries team has to take a position on how to handle this ambiguity. There is no 100% right answer here, unless there was an option like `Ambiguous`. 

I personally find that taking the position of returning `Nullable` in this ambiguities to be reasonable.

**Comment by mlorbetske** [comment] 2024-09-05 13:54
I was agreeing with the close on the Roslyn repo as not planned being reasonable and am accepting the close on the runtime repo, just thinking it shouldn't be closed as completed.

While I'm not fully on board with the runtime interpretation here, I understand the perspective that there _could_ be a nullable substitution for the generic argument and therefore the parameter is nullable - that's just not enough information to make a determination for a runtime invocation via reflection whether it's safe to pass null (or whether null should be expected as a return).
