### ISSUE TITLE
how can we trim dll unused?

### ISSUE THREAD

**Issue by srxqds** [dotnet/runtime#78633] opened 2022-11-21 10:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have found some dll like diagnostic should not used in product release:
![image](https://user-images.githubusercontent.com/5187024/203030089-3d4aafd2-64b4-426f-8569-6444e32e26bf.png)

### Expected Behavior

no loading these assembly, or can config some assembly not loading

### .NET Version

6.0 blazor webasembly

**Comment by agocke** [comment] 2022-11-22 00:57
Closing as question seems answered.

@srxqds mentions that they're using Blazor, so they're probably already trimming. If the question is about figuring out what is being rooted in these types and why, I think that's a duplicate of https://github.com/dotnet/runtime/issues/78671

**Closed by agocke** 2022-11-22 00:57 UTC
Labels: untriaged, area-Tools-ILLink
