### ISSUE TITLE
Test failure JIT/Regression/JitBlue/GitHub_1161/GitHub_1161/GitHub_1161.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#53518] opened 2021-06-01 06:22 UTC
Run: [runtime-coreclr crossgen2 20210530.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1163954&view=ms.vss-test-web.build-test-results-tab&runId=35092316&resultId=101691&paneView=debug)

Failedbtest:
```
R2R-CG2 OSX arm64 Checked no_tiered_compilation @ OSX.1100.ARM64.Open

- JIT/Regression/JitBlue/GitHub_1161/GitHub_1161/GitHub_1161.sh

```
**Error message:**
```
/private/tmp/helix/working/A5AA08E0/w/B13809A8/e/JIT/Regression/JitBlue/GitHub_1161/GitHub_1161/GitHub_1161.sh: line 254: -r:/private/tmp/helix/working/A5AA08E0/w/B13809A8/e/JIT/Regression/JitBlue/GitHub_1161/GitHub_1161/IL-CG2/*.dll: No such file or directory
rm: /private/tmp/helix/working/A5AA08E0/w/B13809A8/e/JIT/Regression/JitBlue/GitHub_1161/GitHub_1161/GitHub_1161.dll.rsp: No such file or directory
Unhandled exception. System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
---> System.NullReferenceException: Object reference not set to an instance of an object.
at ILCompiler.Sorting.Implementation.MergeSortCore5.ParallelSort(TDataStructure arrayToSort, Int32 index, Int32 length, TComparer comparer) --- End of inner exception stack trace --- at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) at ILCompiler.Sorting.Implementation.MergeSortCore5.ParallelSortApi(TDataStructure arrayToSort, TComparer comparer)
at ILCompiler.DependencyAnalysis.ReadyToRun.GCRefMapNode.GetData(NodeFactory factory, Boolean relocsOnly)
at ILCompiler.DependencyAnalysis.ReadyToRunObjectWriter.EmitPortableExecutable()
at ILCompiler.ReadyToRunCodegenCompilation.Compile(String outputFile)
at ILCompiler.Program.RunSingleCompilation(Dictionary2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary2 unrootedInputFilePaths, HashSet`1 versionBubbleModulesHash, CompilerTypeSystemContext typeSystemContext)
at ILCompiler.Program.Run(String[] args)
at ILCompiler.Program.Main(String[] args)
dyld: Library not loaded: @rpath/libmscordaccore.dylib
Referenced from: /private/tmp/helix/working/A5AA08E0/p/dotnet-cli/shared/Microsoft.NETCore.App/6.0.0-preview.3.21201.4/createdump
Reason: image not found
/private/tmp/helix/working/A5AA08E0/w/B13809A8/e/JIT/Regression/JitBlue/GitHub_1161/GitHub_1161/GitHub_1161.sh: line 204: 73774 Abort trap: 6           (core dumped) $__Command

Return code:      1
Raw output file:      /private/tmp/helix/working/A5AA08E0/w/B13809A8/e/JIT/Regression/Reports/JIT.Regression/JitBlue/GitHub_1161/GitHub_1161/GitHub_1161.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/private/tmp/helix/working/A5AA08E0/w/B13809A8/e/JIT/Regression/JitBlue/GitHub_1161/GitHub_1161/IL-CG2/GitHub_1161.dll
Response file: /private/tmp/helix/working/A5AA08E0/w/B13809A8/e/JIT/Regression/JitBlue/GitHub_1161/GitHub_1161/GitHub_1161.dll.rsp
/private/tmp/helix/working/A5AA08E0/w/B13809A8/e/JIT/Regression/JitBlue/GitHub_1161/GitHub_1161/IL-CG2/GitHub_1161.dll
-o:/private/tmp/helix/working/A5AA08E0/w/B13809A8/e/JIT/Regression/JitBlue/GitHub_1161/GitHub_1161/GitHub_1161.dll
-r:/tmp/helix/working/A5AA08E0/p/System..dll
-r:/tmp/helix/working/A5AA08E0/p/Microsoft..dll
-r:/tmp/helix/working/A5AA08E0/p/mscorlib.dll
--verify-type-and-field-layout
--targetarch:arm64
-O
Running CrossGen2:  dotnet /tmp/helix/working/A5AA08E0/p/crossgen2/crossgen2.dll @/private/tmp/helix/working/A5AA08E0/w/B13809A8/e/JIT/Regression/JitBlue/GitHub_1161/GitHub_1161/GitHub_1161.dll.rsp

Emitting R2R PE file: /private/tmp/helix/working/A5AA08E0/w/B13809A8/e/JIT/Regression/JitBlue/GitHub_1161/GitHub_1161/GitHub_1161.dll
Crossgen2 failed with exitcode: 134
in ReleaseLock
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/tmp/helix/working/A5AA08E0/p
/private/tmp/helix/working/A5AA08E0/w/B13809A8/e/JIT/Regression/JitBlue/GitHub_1161/GitHub_1161/GitHub_1161.sh
Expected: True
Actual:   False


Stack trace
   at JIT_Regression._JitBlue_GitHub_1161_GitHub_1161_GitHub_1161_._JitBlue_GitHub_1161_GitHub_1161_GitHub_1161_sh()
```

**Comment by VincentBu** [comment] 2021-06-01 06:23
Historical failures of this test:

Queued | OS | Arch | Pipeline
-- | -- | -- | --
2021-05-31T07:59:18.319Z | osx.1100.arm64.open | arm64 | [runtime-coreclr crossgen2-composite gcstress   Checked-gcstress0xc_zapdisable](https://dev.azure.com/dnceng/public/_build/results?buildId=1163952&amp;view=ms.vss-test-web.build-test-results-tab&amp;runId=35092742&amp;resultId=107029&amp;paneView=debug)
2021-05-31T07:26:27.768Z | osx.1100.arm64.open | arm64 | [runtime-coreclr crossgen2   Checked-no_tiered_compilation](https://dev.azure.com/dnceng/public/_build/results?buildId=1163954&amp;view=ms.vss-test-web.build-test-results-tab&amp;runId=35092316&amp;resultId=101691&amp;paneView=debug)
2021-05-23T09:15:01.505Z | osx.1100.arm64.open | arm64 | [runtime-coreclr crossgen2-composite gcstress   Checked-gcstress0xc_jitstress1](https://dev.azure.com/dnceng/public/_build/results?buildId=1152004&amp;view=ms.vss-test-web.build-test-results-tab&amp;runId=34830104&amp;resultId=106929&amp;paneView=debug)
2021-05-17T09:17:36.203Z | osx.1100.arm64.open | arm64 | [runtime-coreclr crossgen2-composite gcstress   Checked-gcstress0xc_zapdisable_heapverify1](https://dev.azure.com/dnceng/public/_build/results?buildId=1141420&amp;view=ms.vss-test-web.build-test-results-tab&amp;runId=34601478&amp;resultId=106295&amp;paneView=debug)

**Comment by mangod9** [comment] 2021-07-20 02:05
Dupe of #51250

**Closed by mangod9** 2021-07-20 02:05 UTC
Labels: arch-arm64, area-crossgen2-coreclr, os-mac-os-x, untriaged
