### ISSUE TITLE
Chrome debugger tests timeout

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#76750] opened 2022-10-07 17:46 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=43071
Build error leg or test failing: chrome-DebuggerTests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/75473

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section).

```json
{
  "ErrorMessage": "['chrome-DebuggerTests' END OF WORK ITEM LOG: Command timed out, and was killed]",
  "BuildRetry": false
}
```

Runfo Tracking Issue: [chrome-debuggertests work item](https://runfo.azurewebsites.net/tracking/issue/434)
|Build|Definition|Kind|Run Name|Console|Core Dump|Test Results|Run Client|
|---|---|---|---|---|---|---|---|
|[43071](https://dev.azure.com/dnceng-public/public/_build/results?buildId=43071)|[runtime](https://dnceng-public.visualstudio.com/public/_build?definitionId=129)|[PR 75473](https://github.com/dotnet/runtime/pull/75473)|net7.0-Browser-Release-wasm-Mono_chrome_Release-WasmDebuggerTests-Ubuntu.1804.Amd64.Open|[console.log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-75473-merge-5b827b879f264c498b/chrome-DebuggerTests/1/console.e3af3ee6.log?%3F%253Fhelixlogtype%253Dresult)|||[runclient.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-75473-merge-5b827b879f264c498b/chrome-DebuggerTests/f3a3f45c-6687-4063-93d2-f896392779b1.log?%3F%253Fhelixlogtype%253Dresult)|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|0|1|1|

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[43071](https://dev.azure.com/dnceng-public/public/_build/results?buildId=43071)|dotnet/runtime|[chrome-DebuggerTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=43071&view=ms.vss-test-web.build-test-results-tab&runId=874542&resultId=100001)|dotnet/runtime#75473|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|1|

**Comment by lewing** [comment] 2022-10-08 02:13
looks like a duplicate of https://github.com/dotnet/runtime/issues/76528 but feel free to reopen

**Closed by lewing** 2022-10-08 02:13 UTC
Labels: arch-wasm, blocking-clean-ci, Known Build Error
