### ISSUE TITLE
.Net 6 API in failing at start up post this upgrade to VS2022 17.8. Getting error "Operation is not supported on this platform."

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#96507] opened 2024-01-04 20:44 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Net-6-API-in-failing-at-start-up-post-t/10553228)._

---
[severity:Multiple people on my team are impacted (internal MSFT only)] [regression] [worked-in:17.7.7]
After upgrading to Visual Studio 2022 18.3, .Net 6.0 API stopped working and failing at startup with error 'Operation is not supported on this platform.'
Stack Trace:
   at System.Text.Encodings.Web.OptimizedInboxTextEncoder.AllowedAsciiCodePoints.get_AsVector()
   at System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstCharToEncodeSsse3(Char* pData, UIntPtr lengthInChars)
   at System.Text.Encodings.Web.OptimizedInboxTextEncoder.GetIndexOfFirstCharToEncode(ReadOnlySpan`1 data)
   at System.Text.Encodings.Web.DefaultJavaScriptEncoder.FindFirstCharacterToEncode(Char* text, Int32 textLength)
   at System.Text.Json.JsonWriterHelper.NeedsEscaping(ReadOnlySpan`1 value, JavaScriptEncoder encoder)
   at System.Text.Json.Utf8JsonWriter.WritePropertyName(ReadOnlySpan`1 propertyName)
   at System.Text.Json.Utf8JsonWriter.WritePropertyName(String propertyName)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerOptions.Serialize(Utf8JsonWriter writer)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelEventSource.Configuration(KestrelServerOptions options)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.KestrelEventSource.AddServerOptions(KestrelServerOptions options)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<StartAsync>d__30`1.MoveNext()
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.<StartAsync>d__37.MoveNext()
   at Microsoft.Extensions.Hosting.Internal.Host.<<StartAsync>b__15_1>d.MoveNext()
   at Microsoft.Extensions.Hosting.Internal.Host.<ForeachService>d__18`1.MoveNext()
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>g__LogAndRethrow|15_3(<>c__DisplayClass15_0& )
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__15.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at BDO.Integration.API.Program.Main(String[] args) in C:\BDO\API\APT_API\BDO.APT.API\src\External.API\WebAPI\Program.cs:line 23

---
### Original Comments
(no comments)

---
### Original Solutions
(no solutions)

**Comment by ericstj** [comment] 2024-01-04 20:55
I'm a bit puzzled by this callstack.  

The GetIndexOfFirstByteToEncodeSsse3 call is under `#if NETCOREAPP`
https://github.com/dotnet/runtime/blob/82d75adec91d50ba2cde7cca0c907ce38f0ce7d4/src/libraries/System.Text.Encodings.Web/src/System/Text/Encodings/Web/OptimizedInboxTextEncoder.cs#L350-L372

But the AsVector throwing path is only for `!TARGET_BROWSER`:
https://github.com/dotnet/runtime/blob/82d75adec91d50ba2cde7cca0c907ce38f0ce7d4/src/libraries/System.Text.Encodings.Web/src/System/Text/Encodings/Web/OptimizedInboxTextEncoder.Ascii.cs#L25-L35

**Comment by krwq** [comment] 2024-01-05 11:17
We'll need more info here at minimum I think following will be useful:
- csproj (at least properties and relevant nuget packages)
- how you build/publish
- how you run (i.e. is it same machine or different, what command line are you using if using `dotnet` tool or what output and current working directory you're using)

Currently as @ericstj mentioned stack seems a bit bogus and it's hard to tell if this is a problem with product, symbols, packaging (i.e. using wrong binary or incorrectly compiling it), trimmer or maybe JIT bug. We'll need to narrow this a bit.

I've went through list of patches on release branches from the last year and there wasn't anything which looked like it could have caused regression (unless maybe some packaging changes - I'm not an expert there so can't tell but they looked ok to me).

I've tried to repro based solely on stack trace - I tried targeting both 6.0 and 8.0 with different trimming settings but I didn't have luck getting any repro.

I used following piece of code based on stack trace:
https://github.com/dotnet/aspnetcore/blob/main/src/Servers/Kestrel/Core/src/Internal/Infrastructure/KestrelEventSource.cs#L236C1-L244C86
and
https://github.com/dotnet/aspnetcore/blob/main/src/Servers/Kestrel/Core/src/KestrelServerOptions.cs#L334-L373

I tried to wrap that with async calls tried some different combinations of properties and other random stuff I could think of (suspecting maybe trimming out `nameof(...)` could have caused some issues)

**Comment by ericstj** [comment] 2024-01-05 17:29
Agreed - we really need more repro information from the original filer.  I've made the requst for more info in the VS Dev ticket, and the internal AzDo ticket.  Marking this as blocked.

**Comment by tarekgh** [comment] 2024-01-05 19:07
I pinged the reporter offline to respond to the request here. Expect some delay as he is in a different time zone.

**Comment by krwq** [comment] 2024-01-08 09:01
I just spoke with the reporter and they said neither he or his teammates arenn't able to repro the issue anymore after reinstalling VS. They said I can close the ticket so, I'll go ahead with that since this is not actionable as is even if there is some issue there. If we hear about similar issue and we are able to collect more info we can re-open but I think it doesn't make much sense to keep this open anymore.

**Closed by krwq** 2024-01-08 09:01 UTC
Labels: area-System.Text.Encodings.Web, needs-author-action
