### ISSUE TITLE
EmptyIfNull Extension Method

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#43848] opened 2020-10-26 21:00 UTC
## Background and Motivation
When working with lists that comes from external sources, having to deal with ```null``` collections really clutters up code.  For Example:
```
var Results = (
    from x in (Response?.Data ?? Enumerable.Empty<Node1>)
    from y in (x?.Items ?? Enumerable.Empty<Node2>)
    select y
  ).ToList()
```

## Proposed API
```
public static class EnumerableExtensions {

        public static IEnumerable<T> EmptyIfNull<T>(this IEnumerable<T>? This) {
            return This ?? Enumerable.Empty<T>();
        }

    }
```
## Usage Examples
```
var Results = (
    from x in Response?.Data.EmptyIfNull()
    from y in x?.Items.EmptyIfNull()
    select y
  ).ToList()
```

## Alternative Designs
None

## Risks
None

**Comment by GrabYourPitchforks** [comment] 2020-10-28 16:13
We tend not to include extension methods that can operate on null instances. `MemoryExtensions` is the only counterexample that comes to mind.

Perhaps using an alternative syntax would make the code a little cleaner?

```cs
var list = Response?.Data?.SelectMany(x => x?.Items ?? new[])?.ToList() ?? new();
```

**Comment by adamsitnik** [comment] 2020-10-29 15:58
Hi @TonyValenti 

Thank you for your proposal.

> We tend not to include extension methods that can operate on null instances.

As @GrabYourPitchforks has noticed, we don't accept nulls in extension methods by design. Since we are not planning to change that and you can easily add this extension method to your own code I am going to close the issue.

Thanks,
Adam

**Closed by adamsitnik** 2020-10-29 15:58 UTC
Labels: api-suggestion, area-System.Linq, untriaged
