### ISSUE TITLE
Test failure: System.Media.Test.SoundPlayerTests.Play_InvalidFile_ShortTimeout_ThrowsWebException

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#39259] opened 2020-07-14 07:14 UTC
failed in job: [runtime-libraries outerloop 20200713.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=726827&view=ms.vss-test-web.build-test-results-tab&runId=22506986&resultId=100892&paneView=debug)

Error message
~~~
Assert.Throws() Failure
Expected: typeof(System.Net.WebException)
Actual:   typeof(System.IO.IOException): The operation is not allowed on non-connected sockets.
---- System.IO.IOException : The operation is not allowed on non-connected sockets.


Stack trace
   at System.Net.HttpWebRequest.GetResponse() in /_/src/libraries/System.Net.Requests/src/System/Net/HttpWebRequest.cs:line 1025
   at System.Media.SoundPlayer.LoadSync() in /_/src/libraries/System.Windows.Extensions/src/System/Media/SoundPlayer.cs:line 265
   at System.Media.SoundPlayer.LoadAndPlay(Int32 flags) in /_/src/libraries/System.Windows.Extensions/src/System/Media/SoundPlayer.cs:line 228
   at System.Media.SoundPlayer.Play() in /_/src/libraries/System.Windows.Extensions/src/System/Media/SoundPlayer.cs:line 326
   at System.Media.Test.SoundPlayerTests.<>c__DisplayClass9_0.<Play_InvalidFile_ShortTimeout_ThrowsWebException>b__0() in /_/src/libraries/System.Windows.Extensions/tests/System/Media/SoundPlayerTests.cs:line 157
----- Inner Stack Trace -----
   at System.Net.HttpWebRequest.GetResponse() in /_/src/libraries/System.Net.Requests/src/System/Net/HttpWebRequest.cs:line 1025
   at System.Media.SoundPlayer.LoadSync() in /_/src/libraries/System.Windows.Extensions/src/System/Media/SoundPlayer.cs:line 265
   at System.Media.SoundPlayer.LoadAndPlay(Int32 flags) in /_/src/libraries/System.Windows.Extensions/src/System/Media/SoundPlayer.cs:line 228
   at System.Media.SoundPlayer.Play() in /_/src/libraries/System.Windows.Extensions/src/System/Media/SoundPlayer.cs:line 326
   at System.Media.Test.SoundPlayerTests.<>c__DisplayClass9_0.<Play_InvalidFile_ShortTimeout_ThrowsWebException>b__0() in /_/src/libraries/System.Windows.Extensions/tests/System/Media/SoundPlayerTests.cs:line 157
~~~

**Comment by BruceForstall** [comment] 2020-07-14 17:16
@danmosemsft What is the correct area for this?

**Comment by danmosemsft** [comment] 2020-07-14 18:03
Per https://github.com/dotnet/runtime/blob/master/docs/area-owners.md System.Windows.Extensions is area-Microsoft.Win32

**Comment by danmosemsft** [comment] 2020-07-14 18:13
Relevant code is very simple
```c#
                WebRequest webRequest = WebRequest.Create(_uri);
                webRequest.Timeout = LoadTimeout;

                WebResponse webResponse;
                webResponse = webRequest.GetResponse(); // <<<<
```
cc @dotnet/ncl are we doing this right here?

**Comment by wfurt** [comment] 2020-07-14 18:40
I don't know if it is related but this looks like synchronous API and there was recent change to use new sync implementation instead of using sync over async inside HTTP. The socket error also looks suspicious. 
cc: @ManickaP

**Comment by ManickaP** [comment] 2020-07-14 20:37
This is the same underlying issue as in https://github.com/dotnet/runtime/issues/39279
Since it's obviously a different test, should we keep both issues open?
If not, I'd close this one as a dupe, the original one is closer to the stack where it's happening.

**Comment by danmosemsft** [comment] 2020-07-14 22:11
Duplicate of #39279.

**Closed by danmosemsft** 2020-07-14 22:11 UTC
Labels: area-Microsoft.Win32, untriaged
