### ISSUE TITLE
GC threads assert due to CPU Governor

### ISSUE THREAD

**Issue by y-yamshchikov** [dotnet/runtime#32593] opened 2020-02-20 12:42 UTC
We have variable CPU count on at least [armel Tizen] so this code
https://github.com/dotnet/runtime/blob/052f07a60ed1914c6f80e04dd5579bdfec6bfe19/src/coreclr/src/vm/gcenv.os.cpp#L118-L124
is logically broken: CPU count can variate since setting the thread affinity till fetching it via PAL_GetLogicalCpuCountFromOS.

Are there further assumptions based on this assertion?

@jkotas @alpencolt @gbalykov @kfrolov @clamp03

**Comment by jkotas** [comment] 2020-02-20 14:46
The GC and number of other parts of the runtime and libraries assume that processor count is a constant for the duration of the process. This number is primarily used for performance auto-tuning. If this number is different than the number of processors that the process can run on at any given point, the system should still function correctly, but potentially with lower performance.

I agree that there is potential race condition in this code if the affinity is changing. It should be fixed.

**Comment by jkotas** [comment] 2020-03-01 17:48
Duplicate of https://github.com/dotnet/runtime/issues/12510

**Closed by jkotas** 2020-03-01 17:48 UTC
Labels: area-PAL-coreclr, untriaged
