### ISSUE TITLE
HttpClient The response ended prematurely

### ISSUE THREAD

**Issue by shadow-cs** [dotnet/runtime#72177] opened 2022-07-14 12:21 UTC
### Description

I'm running a legacy HTTP server and I randomly get the `The response ended prematurely` error while receiving the payload body. I was trying to investigate which ultimately led me to a possible bug in `HttpClient` `Connection: close` handling.

I'm using a HTTP 1.0 server implementation, and I'm always sending `Connection: close` and `Content-Length` headers.

The server tries to gracefully close the connection using `shutdown(socket, SD_SEND)` which should be the correct handshake mechanism according to Win32 API Documentation ([here](https://docs.microsoft.com/en-us/windows/win32/api/winsock/nf-winsock-shutdown) and [here](https://docs.microsoft.com/en-us/windows/win32/winsock/graceful-shutdown-linger-options-and-socket-closure-2)).

This has already been discussed in #47612 and possibly other issues.

### Reproduction Steps

Basically have a server that:

- Bind and Listen on a TCP server socket
- Accept a connection
- Receive request headers and data
- Shutdown the read end
- Send response headers and data
- Shutdown the write end
- Wait until Select/Poll returns read is available
- Close the socket

And a `HttpClient` that downloads a resource from this server.

See [repro projects](https://github.com/dotnet/runtime/files/9111592/HttpConnectionCloseHandshake.zip) (this is a crude HTTP server implementation but hopefully is enough to demonstrate the issue, please let me know if there are some mistakes in the logic there). I tried to write a minimalistic server in .NET (the other server that initially produced the error is written in another language), demonstrating the issue. (Run the `SimpleHttpServer` project first then run the `SocketTest` project and the problem should reveal itself after a while.)

I was able to demonstrate this problem on Windows only (I also tried Mac OS on M1 and WSL which didn't show this issue).

I also tried to use a Linger period but it made this worse (the chance of the exception is more likely). In the .NET repro I used (Close with a timeout specified). It appears to me as if the `HttpClient` somehow knows the socket has been closed without having all the data copied to some output buffer.

### Expected behavior

The client to receive all the data and gracefully close the connection without throwing any exceptions.

### Actual behavior

Randomly (once every few thousand requests) the `HttpClient` reports it didn't receive all the data.

```
System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, Boolean async, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionResponseContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Program.<Main>$(String[] args) in C:\Users\User\source\repos\HttpConnectionCloseHandshake\SocketTest\SocketTest.cs:line 38
```

### Regression?

I was able to reproduce this in .NET 6 and .NET 7 preview 6. This has probably been introduced with the `SocketsHttpHandler` in .NET Core 2.1.

### Known Workarounds

On server side: do not call `shutdown` nor `close` just wait for the client to receive all the data and close the socket itself. Then `recv` returns `0` and the server may close the socket as well.

On client side: use `WinHttpHandler` rather than pure .NET implementation.

### Configuration

- Windows only (11 and Server)
- .NET 6 and 7 preview 6
- x64

**Comment by wfurt** [comment] 2022-07-14 16:06
triage: we should investigate the repro

**Comment by haiduong87** [comment] 2022-08-03 07:01
I also have the same issue

Configuration

    Client: Windows Server 2016
    Server: minio k8s (https://docs.min.io/minio/k8s/index.html)
    .NET Core 3.1
    x32

https://github.com/minio/minio-dotnet/issues/667

**Comment by yufeiqi** [comment] 2022-09-01 08:48
We encounter the same issue, too.

**Comment by karelz** [comment] 2022-09-01 10:54
Triage: Moving to 8.0 as we have already 3 reports in last 1.5 months

**Comment by liveans** [comment] 2022-09-06 18:06
I tried to reproduce the issue with both given project and steps, but I couldn't be able to.

**Comment by karelz** [comment] 2022-09-06 18:09
@shadow-cs are you able to reproduce the problem on more than 1 machine? -- looks like we can't reproduce it :(

**Comment by shadow-cs** [comment] 2022-09-06 20:04
@karelz yes at least on our production server and my development laptop (haven't tried more). Is there a problem with the repro I submitted?

**Comment by wfurt** [comment] 2022-09-06 20:14
Timing? The original post says you use `WinHttpHandler` @shadow-cs but the traces looks like `SocketsHttphandler`....????

**Comment by karelz** [comment] 2022-09-07 05:55
@wfurt original post mentions the problem is with `SocketsHttpHandler` and that `WinHttpHandler` is a workaround. What am I missing?

@liveans was not able to reproduce the problem with your repro @shadow-cs

**Comment by shadow-cs** [comment] 2022-09-08 14:49
@karelz funny thing, I couldn't reproduce it again on either my laptop (Windows 11) or desktop (Windows 10). So I decided to give our DEV environment a spin (Window Server 2019 VM) and the problem has revealed itself:

![image](https://user-images.githubusercontent.com/4301974/189151739-1b6107ae-9c5e-4df9-8995-874aafd7f8ea.png)

I also tested with the legacy HTTP server (on my PCs) and it worked without a glitch (I tested tens of thousands of requests, usually I only needed a few thousand to showcase the problem, usually around four or five).

Is it possible the issue is related to Windows itself (and got fixed with an update)? Both my PCs are updated fairly regularly whereas our Cloud infrastructure is patched once in a while by our IT teams.

Is there some information I can gather from the Windows Server VM to help analyze the problem further?

**Comment by shadow-cs** [comment] 2022-09-08 14:58
@wfurt I guess if you leave the client some time, it will hide the issue even more (make it less likely). But I don't think this is the problem here (well unless the Windows scheduler got some serious updates 😉). I originally thought that the sockets client had a flag somewhere saying the connection is closed (because `recv` has returned `0`) but it failed to recognize there are some data left in a buffer (again I'm guessing here) so reading from a closed socket failed. But the tests 👆 got me confused.

**Comment by shadow-cs** [comment] 2022-09-08 16:54
@karelz always, I could test tomorrow to be sure. I have an older VM on my PC (I downloaded a VHD some time ago) and I could share this image with you if it helps (and I'll be able to reproduce the issue).

**Comment by karelz** [comment] 2022-09-08 17:12
That would be great if we have something we can reproduce ourselves locally.

**Comment by shadow-cs** [comment] 2022-09-09 09:55
@karelz unfortunately I couldn't reproduce the issue on either of my VMs (Windows Server 2019 and 2022). I did retest again on our DEV environment and was able to reproduce the issue again. I also tested on our STG environment and I was also able to reproduce the issue (but both VMs run on the same cluster).

I'd very much like to provide you with more information, but at this point, I don't know how to continue.

**Comment by shadow-cs** [comment] 2022-09-09 11:48
@karelz could I run `Perfview` or some other tracing tool (which trace data would be useful to you in this case) to gather some data from the process?

**Comment by karelz** [comment] 2022-09-09 12:59
Let's see if @wfurt or @rzikm have any ideas what we might want to collect ...
Note: We are a bit busy with 7.0 finish at this moment, so answer from them might be delayed for few days / a week ... just FYI

**Comment by shadow-cs** [comment] 2022-09-09 13:09
Understood @karelz I just wanted to handle this in time while we're able to reproduce the issue somewhere. After our patching window, the issue may go away without us knowing the culprit. We're spinning up a clean VM and trying to reproduce it there, I'll post the results as soon as I have them.

**Comment by shadow-cs** [comment] 2022-09-12 09:37
@karelz unfortunately the new VM (same host) did not exhibit the same behavior. I think this has to be OS related (it is highly likely we have different OS updates applied on the new VM than the ones still exhibiting the odd behavior). Is there are system information I can pull from the OSes (maybe some diff can be made on these updates so we can pinpoint which one fixed this).

**Comment by shadow-cs** [comment] 2022-09-12 11:23
Quickly looking at the logs, the VM that I'm able to reproduce the issue on was last patched on 6/22/2022 so maybe if you're able to create such a machine it could be used for testing. Unfortunately my options are limited. Both VMs (the one with the issue and the one without it) were installed from the same image, the only difference is that the newer (working) one was updated during the install.

**Comment by tompanchee** [comment] 2022-09-21 11:04
We have noticed this in a .Net Core 3.1 environment. It happens when there's a big amount of requests towards the same host. The ratio 1 of 1000 failing seems about correct.

We tried switching to WinHttpHandler as mentioned as a workaround but it seems that we have the same problem 'Error 12152 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR - The server returned an invalid or unrecognized response'. The WinHttpHandler error seems to happen at similar situations as the 'premature ending' error and the target does not receive any requests.

**Comment by shadow-cs** [comment] 2022-10-04 13:02
FYI: I still haven't abandoned looking for the problem, it just takes time. We have updated some of our VMs and the problem still persists there. Right now we're in the process of Windows update isolation. Hope I'll have more info soon.

**Comment by shadow-cs** [comment] 2022-11-29 14:54
After we applied these Windows patches, the problem seemed to go away.

- KB5020627
- KB5019966
- KB5020374

The test I posted above failed before the update and did not fail after it. As I also stated above, we tried to create a brand new VM a few months ago and it did not exhibit the same behavior (which was also the case for both my desktop PC and laptop).

It seems to me this has to be somehow OS related although using a socket and trivial HTTP client I wasn't able to reproduce it so maybe .NET is doing something more complex under the hood which makes this issue surface. This is as far as I can get with my analysis I'm afraid.

**Comment by TBRLramboll** [comment] 2022-12-06 13:46
I have the same issue, between two Windows 10 PCs using a dotnet 6 client, Network Traffic looks normal. Note: I do not use keep-alive.

**Comment by shadow-cs** [comment] 2022-12-07 10:05
@tbrl0 do you keep your OSs updated? But I'm not sure whether there is something that can also be fixed in the runtime that surfaced with the OS being in a specific "update" state. If you update your system, please keep track of the updates you installed so we paint a more complete picture.

For us eventually, all the issues went away with some updates.

- On my PCs (Windows 10, Windows 11) during the summer
- On our VMs (Windows Server 2019) in the last patch wave (as I posted above)

**Comment by tbrl0** [comment] 2022-12-13 09:45
@shadow-cs Yes we are up-to-date
![image](https://user-images.githubusercontent.com/119947634/207283845-cc2ec7fe-2e49-4206-bd8e-6ae6d2a80c5a.png)

**Comment by tbrl0** [comment] 2022-12-13 11:08
Also I should mention that working with the exact same server work in .NET Framework 4.8 using SoapHttpClientProtocol works fine.

**Comment by wfurt** [comment] 2022-12-13 18:22
Do you have repro you can share @tbrl0. I look at the updates @shadow-cs and I don't see anything that would be directly relevant. This can still be just timing race condition.

**Comment by tbrl0** [comment] 2022-12-20 19:20
Unfortunately I can't. The software that runs the HTTP-Server is proprietary with high licensing costs. With other ervers I was not able to reproduce this issue. It seems a bit to as if the issue depends on the timing of the reponse packets.

**Comment by tbrl0** [comment] 2023-01-03 09:49
Ok, small update from me: Turns out it was a mistake to trust our supplier to create an HTTP-compliant webserver and another mistake to trust Microsoft Message Analyzer to find errors in the communication. dotnet did everything right, sorry to have bothered you. (I **really** did not expect that the server was the problem especially after it worked fine in .NET Framework 4.8)

**Comment by wfurt** [comment] 2023-01-03 17:18
No problem. It is often very difficult to assure completeness.

**Closed by wfurt** 2023-01-03 17:18 UTC
Labels: bug, area-System.Net.Http

**Comment by shadow-cs** [comment] 2023-01-04 13:22
I'm sorry I couldn't provide more feedback. In the end, the issue seems to be resolved now (too bad we never figured out the source of it).
