### ISSUE TITLE
In linux Centos7, use httpclient Post request error

### ISSUE THREAD

**Issue by ddgweb** [dotnet/runtime#32812] opened 2020-02-25 12:52 UTC
The same code ,for windows +ngix no error , everythiny is ok , but in linux centos, error tips:
### Error while copying content to a stream. Unable to read data from the transport connection: Broken pipe.

what ever httpwebrequest or I try convert httpclient ,all same error

I try everything can do but it doesn't work.

No all website has error, just a few website can tips error.

**Comment by davidsh** [comment] 2020-02-25 19:18
@ddgweb What version of .NET Core are you using? Can you show 'dotnet --info' output?

Please list the external websites that are having trouble.

**Comment by wfurt** [comment] 2020-02-26 05:03
you can lso use `openssl s_client -connect <server:ip>` to see what you get at OS level.

**Comment by ddgweb** [comment] 2020-02-26 06:58
> It looks like the remote cert is invalid. Are you using a self-signed cert, or one which would otherwise not be picked up in the default OpenSSL cert store?

I request that website don't check cert ,It is a https url only, so I have no any cert for request send ,and I already set some "RemoteCertificateValidationCallback" attribute ,no help for this.

**Comment by ddgweb** [comment] 2020-02-26 07:04
> @ddgweb What version of .NET Core are you using? Can you show 'dotnet --info' output?
> 
> Please list the external websites that are having trouble.

@davidsh This querstion occurred  in three months ago, so that maybe .net core 2.1 ~2.2 version , and know I'm updating my linux centos's .Net core runtime to 3.1 version, and I will check this problem alter tell you.

**Comment by wfurt** [comment] 2020-02-26 08:23
If the site is reachable over the internet, it may be worthy of posting specific repro @ddgweb

**Comment by karelz** [comment] 2020-02-27 20:55
@ddgweb please post a minimal HelloWorld-style console repro. That will speed up time to resolution and save on back and forth. Thanks!

**Comment by lostmagicK** [comment] 2020-02-28 09:52
I also have same issue.. i cant figure out problem yet.. problem persists for all https enabled apis, seems like client side encryption problem

**Comment by lostmagicK** [comment] 2020-02-28 09:53
> @ddgweb please post a minimal HelloWorld-style console repro. That will speed up time to resolution and save on back and forth. Thanks!

You can try posting to any https enabled api, through Centos Linux

**Comment by davidsh** [comment] 2020-02-28 19:18
>The SSL connection could not be established, see inner exception. The remote certificate is invalid according to the validation procedure.

@lostmagicK Are you using a self-signed certificate for your server-side ASP.NET Core application? If so, how did you generate it. There is a limitation in Linux OpenSsl that requires extra attributes be set on self-signed certificates being used on Linux. The current 'dotnet devcerts' tool doesn't generate the correct self-signed certificate for Linux. This is a known issue.

**Comment by ddgweb** [comment] 2020-02-29 16:06
> @ddgweb please post a minimal HelloWorld-style console repro. That will speed up time to resolution and save on back and forth. Thanks!

@karelz @wfurt this problem happend 3moth ago, now , that Project is fail and discarded ,  I try find source and release on my server (centos7+nginx)  test agan , .net core 3.1 has the same error too , this request is for url "st.so.com" action "upload-image" , you can catch http-network by chrome -Devtool , then use .net core httpwebrequest or httpclient send post request , that you will find the issure.

**Comment by ddgweb** [comment] 2020-02-29 16:14
> I also have same issue.. i cant figure out problem yet.. problem persists for all https enabled apis, seems like client side encryption problem

I think ,Can't be all https website have this problem , If it is true , .net core maybe have too more issure

**Comment by davidsh** [comment] 2020-02-29 16:48
>this problem happend 3moth ago, now , that Project is fail and discarded , I try find source and release on my server (centos7+nginx) test agan , .net core 3.1 has the same error too , this request is about URL "st.so.com" action "upload-image" , you can catch http-network by chrome -Devtool , then use .net core httpwebrequest or httpclient send post request , that you will find the issure.

@ddgweb Thank you for giving us more information about the problem you're seeing. Unfortunately, I still don't fully understand how to reproduce this problem or exactly what .NET Core 3.1 APIs you're using. You indicate that there is a server involved (centos7+nginx) and also another external server, https://st.so.com/

In order for us to investigate the problem, we need a small repro that we can run ourselves. That repro can be a .NET Core application you create with "dotnet new" or using Visual Studio or Visual Studio Code.

**Comment by lostmagicK** [comment] 2020-03-01 14:45
> > The SSL connection could not be established, see inner exception. The remote certificate is invalid according to the validation procedure.
> 
> @lostmagicK Are you using a self-signed certificate for your server-side ASP.NET Core application? If so, how did you generate it.?There is a limitation in Linux OpenSsl that requires extra attributes be set on self-signed certificates being used on Linux. The current 'dotnet devcerts' tool doesn't generate the correct self-signed certificate for Linux. This is a known issue. See: [dotnet/aspnetcore#7246](https://github.com/dotnet/aspnetcore/issues/7246)

My website is simple http website i just wanted to make a post request to Google's FCM API and there problem exists, Now i am planning to workaround by hosting a php site in subdomain and calling php api using dotnet core. Its irritating but i think its only way...

**Comment by davidsh** [comment] 2020-03-01 16:06
@lostmagicK 

>My website is simple http website i just wanted to make a post request to Google's FCM API and there problem exists, Now i am planning to workaround by hosting a php site in subdomain and calling php api (which calls FCM) using dotnet core. Its irritating but i think its only way...

So, you aren't hosting an ASP.NET Core website using HTTPS? But are you using ASP.NET Core at all to host your HTTP site? And then from that you make outbound requests to Google's websites?

It sounds like your scenario is different from @ddgweb despite getting a similar error.

>Now i am planning to workaround by hosting a php site in subdomain and calling php api (which calls FCM) using dotnet core. Its irritating but i think its only way...

If you want us to diagnose your problem in more detail, I suggest you open a new issue and post a complete repro with your source code showing how you use the .NET Core APIs to call Google. But without a repro we won't be able to diagnose further.

**Comment by wfurt** [comment] 2020-03-03 20:15
I did a quick test with  https://st.so.com/ @ddgweb and it works for me. 
```
{
  Server: openresty
  Date: Tue, 03 Mar 2020 20:12:34 GMT
  Connection: keep-alive
  Vary: Accept-Encoding
  ETag: "5e538946-273d"
  Accept-Ranges: bytes
  Content-Type: text/html
  Content-Length: 10045
  Last-Modified: Mon, 24 Feb 2020 08:28:54 GMT
}
```

If you get repro code, we can investiagte.

**Comment by karelz** [comment] 2020-03-12 00:13
Not actionable without a repro, closing.
Feel free to reopen once you have a repro we can try. Thanks!

**Closed by karelz** 2020-03-12 00:13 UTC
Labels: area-System.Net.Http, needs more info
