### ISSUE TITLE
Static field in value type with empty generic causes `TypeLoadException`

### ISSUE THREAD

**Issue by Aidiakapi** [dotnet/runtime#88030] opened 2023-06-26 08:32 UTC
### Description

```cs
public struct Foo<T>
{
}

public struct Bar
{
    public static readonly Foo<Bar> Baz;
}
```

When loading the `Bar` type, a `TypeLoadException` is thrown.

### Reproduction Steps

```cs
new Bar("Hello world!");

public struct Foo<T>
{
}

public struct Bar
{
    public static readonly Foo<Bar> Baz;
    public Bar(string message) => System.Console.WriteLine(message);
}
```

### Expected behavior

I expect the type to load successfully, or at the very least for it to be a compile time diagnostic, rather than a runtime exception.

### Actual behavior

`TypeLoadException` at runtime.

### Regression?

I don't know any specifics, but testing on SharpLab shows that it's been broken on all .NET (Framework & Core) versions.

### Known Workarounds

Moving the static field to a different type. For example:
```cs
public struct Foo<T>
{
}

public struct Bar
{
    public static class Workaround {
        public static readonly Foo<Bar> Baz;
    }
}
```

Alternatively, making either type a `class` will also workaround the issue.

### Other information

This issue is an overlap of https://github.com/dotnet/runtime/issues/5479 (but that has an actually recursive type in a static field), and https://github.com/dotnet/runtime/issues/6924 (which is generally about unused generics).

The other issues are both closed/merged and locked to contributors. Yet the issue remains, hence I'm opening this issue.

**Comment by hamarb123** [comment] 2024-04-12 10:40
I ran into this also in https://github.com/dotnet/runtime/issues/100950 with `Nullable<S1>`

**Comment by steveisok** [comment] 2024-07-18 15:03
Closing at it's a duplicate of https://github.com/dotnet/runtime/issues/104511

**Closed by steveisok** 2024-07-18 15:03 UTC
Labels: area-TypeSystem-coreclr
