### ISSUE TITLE
Several .NET 5 assemblies are deployed without matching PDBs in MS Symbol Server

### ISSUE THREAD

**Issue by masonwheeler** [dotnet/runtime#60123] opened 2021-10-07 12:56 UTC
### Description

Visual Studio allows you to debug into the runtime by enabling the "Enable .NET Framework Source Stepping" and "Enable Source Server Support" options and setting the Microsoft Symbol Server as a PDB source, and this mostly works.  But some assemblies appear to be out of sync with the symbol server.

### Repro steps

1. Create a new .NET 5 WPF project in Visual Studio 2019
2. Configure Visual Studio to debug into the runtime, as described above.
3. Run the project under the debugger.
4. Check in the Modules window and see how many assemblies failed to load debug information.

I'm seeing this with:

- System.Collections.Concurrent.dll
- System.Collections.dll
- System.ComponentModel.dll
- System.Data.Common.dll
- System.Diagnostics.Debug.dll
- System.Diagnostics.TraceSource.dll
- System.Diagnostics.Tracing.dll
- System.Memory.dll
- System.Private.Uri.dll
- System.Reflection.Emit.dll
- System.Reflection.Emit.ILGeneration.dll
- System.Reflection.Emit.Lightweight.dll
- System.Reflection.Primitives.dll
- System.Resources.ResourceManager.dll
- System.Runtime.CompilerServices.VisualC.dll
- System.Runtime.dll
- System.Runtime.Extensions.dll
- System.Runtime.InteropServices.dll
- System.Runtime.Loader.dll
- System.Runtime.Serialization.Formatters.dll
- System.Runtime.Serialization.Json.dll
- System.Runtime.Serialization.Xml.dll
- System.Text.Encoding.Extensions.dll
- System.Threading.dll
- System.Threading.Tasks.dll
- System.Threading.Thread.dll
- System.Threading.ThreadPool.dll
- System.Xml.ReaderWriter.dll

For each of these, right-clicking on their entry in Modules and checking the Symbol Load Information shows that they were able to download symbols from one or more of [https://referencesource.microsoft.com/symbols, https://msdl.microsoft.com/download/symbols, https://symbols.nuget.org/download/symbols] for the assembly, but in each case, "PDB does not match image."

There are probably more assemblies with this problem; this is only the set of the ones that happen to be in my project.  The one that's really blocking me at the moment is being unable to trace into System.Data.Common.

### Other information

Visual Studio 2019 Community, Version 16.11.3
Windows 10 build 19042

**Comment by safern** [comment] 2021-12-06 16:51
Closing as a dupe of: https://github.com/dotnet/runtime/issues/45649

**Closed by safern** 2021-12-06 16:51 UTC
Labels: area-Infrastructure-libraries, untriaged
