### ISSUE TITLE
JsonSerializer.Serialize fails on Guid deserialization if string doesn't contain '-' characters

### ISSUE THREAD

**Issue by idzmitry** [dotnet/runtime#31627] opened 2020-02-02 11:57 UTC
Here is a code snippet (F#)
```
open System
open System.Text.Json

[<CLIMutable>]
type Test = {
    Id: Guid
    Text: string
}

[<EntryPoint>]
let main _ =
    let str =
        {| Id = "88f871231cee49e4bcfff12252d90410"; Text = "abc" |}
        |> JsonSerializer.Serialize
    
    //works fine
    Guid.Parse "88f871231cee49e4bcfff12252d90410"
    |> printfn "Guid: %A"
    
    //fails
    JsonSerializer.Deserialize(str, typedefof<Test>)
    |> printfn "Record: %A"

    0
```
`Guid.Parse` works fine at same time
.Net Core 3.1

**Comment by Tornhoof** [comment] 2020-02-02 13:07
See https://github.com/dotnet/runtime/issues/30692 and related discussion.

**Comment by layomia** [comment] 2020-02-02 18:39
Closing as duplicate of https://github.com/dotnet/runtime/issues/30692.

**Closed by layomia** 2020-02-02 18:39 UTC
Labels: area-System.Text.Json
