### ISSUE TITLE
System.Drawing.Printing.PrintDocument is missing DefaultEvent and DefaultProperty attributes

### ISSUE THREAD

**Issue by DustinCampbell** [dotnet/runtime#34696] opened 2020-04-08 16:46 UTC
On .NET Framework, [`PrintDocument`](https://referencesource.microsoft.com/#System.Drawing/commonui/System/Drawing/Printing/PrintDocument.cs,275c61df12f04804) is defined with `DefaultEvent` and `DefaultProperty` attributes, which control the behavior at design-time when this component is being modified via the property grid control. These are missing in .NET Core, which negatively affects the designer experience.

**Comment by safern** [comment] 2020-04-14 23:57
Thanks @DustinCampbell -- I added this to the 5.0 backlog.

**Comment by eriawan** [comment] 2020-04-17 19:05
@safern 

I'd like to take this one. Could you please assign this to me? Thanks in advance 🙂

**Comment by safern** [comment] 2020-04-17 20:33
@eriawan done 😄

**Comment by eriawan** [comment] 2020-04-18 17:25
@safern 
Thanks!
I've submitted PR on #35162 and I got some build errors. Let's continue to discuss there on the PR. 🙂

**Comment by eriawan** [comment] 2020-04-18 17:46
@safern 
I think I've found the cause of the build error. I have updated my PR.

**Comment by danmosemsft** [comment] 2020-04-20 17:04
@DustinCampbell I see that we don't have them on BackgroundWorker or Process (and .NET Framework does), do you care about those?

**Comment by DustinCampbell** [comment] 2020-05-01 12:58
We likely do, but we haven't gotten to those components in the WinForms designer yet, so I hadn't noticed them.

**Comment by danmosemsft** [comment] 2020-05-01 15:40
@eriawan do you want to look at those two as well?

**Comment by eriawan** [comment] 2020-05-01 16:58
@danmosemsft 
Sure. 🙂 
I will add those attributes into BackgroundWorker and Process in separate PR, because current PR #35162 is still being reviewed.

cc @safern

**Comment by danmosemsft** [comment] 2020-05-01 17:59
BTW, that's assuming it's appropriate to add these attributes, it wouldn't add a problematic dependency, etc -- that would be for @safern to say as he's the area owner.

**Closed** 2020-06-23 20:15 UTC
Labels: area-System.Drawing, bug, untriaged, up-for-grabs
