### ISSUE TITLE
[R2R] Publishing with ReadyToRunUseCrossgen2 fails on 5.0 RC2

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#43141] opened 2020-10-07 15:16 UTC
After installing .NET 5.0 RTM from dotnet/installer, `dotnet publish -p:PublishReadyToRunUseCrossgen2=True` is failing with `NETSDK1094` due to the missing crossgen2 package.

Repro:
```sh
# bash on macOS

$ rm ~/.dotnet; mkdir ~/.dotnet
$ curl -sSL https://aka.ms/dotnet/net5/daily/Sdk/dotnet-sdk-osx-x64.tar.gz | tar xzf - -C ~/.dotnet

$ dotnet --version
5.0.100-rtm.20506.2

$ dotnet new console -n r2rtest; cd r2rtest
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on r2rtest/r2rtest.csproj...
  Determining projects to restore...
  Restored /Users/am11/projects/r2rtest/r2rtest.csproj (in 78 ms).
Restore succeeded.

# fails both, with and without this NuGet.Config
$ cat > NuGet.Config << EOF
<configuration>
  <packageSources>
    <add key="dotnet5" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json" />
  </packageSources>
</configuration>
EOF

$ dotnet publish -p:PublishReadyToRun=True -p:PublishReadyToRunUseCrossgen2=True -c Release -r osx-x64
Microsoft (R) Build Engine version 16.8.0-preview-20473-01+250161603 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
/Users/am11/.dotnet/sdk/5.0.100-rtm.20506.2/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(63,5): error NETSDK1094: Unable to optimize assemblies for performance: a valid runtime package was not found. Either set the PublishReadyToRun property to false, or use a supported runtime identifier when publishing. [/Users/am11/projects/r2rtest/r2rtest.csproj]
```

**Comment by am11** [comment] 2020-10-07 15:17
cc @dagood, included all the infos here. 🙂

**Comment by mangod9** [comment] 2020-10-07 23:20
@am11 is this only about it failing on OSX? Believe there is a separate issue on windows or linux which we are looking into.

**Comment by am11** [comment] 2020-10-08 00:00
@mangod9, I have just tested on Linux (Ubuntu 20.04) with above steps (replacing `osx-x64` with `linux-x64` in both, `curl` and `dotnet-publish` commands), it fails with a different error `NETSDK1096`

```sh
root@62578a08dec3:/r2rtest# dotnet publish -p:PublishReadyToRun=True -p:PublishReadyToRunUseCrossgen2=True -c Release -r linux-x64
Microsoft (R) Build Engine version 16.8.0-preview-20475-05+aed5e7ed0 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /r2rtest/r2rtest.csproj (in 32.02 sec).
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  r2rtest -> /r2rtest/bin/Release/net5.0/linux-x64/r2rtest.dll
/root/.dotnet/sdk/5.0.100-rtm.20507.6/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(397,5): error : Error: [/r2rtest/r2rtest.csproj]
/root/.dotnet/sdk/5.0.100-rtm.20507.6/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(397,5): error :   An assembly specified in the application dependencies manifest (crossgen2.deps.json) was not found: [/r2rtest/r2rtest.csproj]
/root/.dotnet/sdk/5.0.100-rtm.20507.6/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(397,5): error :     package: 'runtimepack.Microsoft.NETCore.App.Runtime.linux-x64', version: '5.0.0-rc.1.20451.14' [/r2rtest/r2rtest.csproj]
/root/.dotnet/sdk/5.0.100-rtm.20507.6/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(397,5): error :     path: 'System.IO.Pipelines.dll' [/r2rtest/r2rtest.csproj]
/root/.dotnet/sdk/5.0.100-rtm.20507.6/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Publish.targets(295,5): error NETSDK1096: Optimizing assemblies for performance failed. You can either exclude the failing assemblies from being optimized, or set the PublishReadyToRun property to false. [/r2rtest/r2rtest.csproj]
```

Moreover,
* it succeeds on Linux, if we execute the `dotnet-publish` command with SDK `5.0.100-preview.8.20417.9`, that is restored as part of dotnet runtime repo: `./build.sh -restore` then `/projects/runtime/.dotnet/dotnet publish -p:PublishReadyToRun=True -p:PublishReadyToRunUseCrossgen2=True -c Release -r linux-x64`. Looks like the crossgen2 Linux package is not published on dnceng's dotnet5 NuGet feed.
* but throws `NETSDK1094` on OSX, even with `/projects/runtime/.dotnet/dotnet`. Is crossgen2 package on OSX a valid expectation?

**Comment by mangod9** [comment] 2020-10-08 00:05
Ok thanks for the additional info. Yeah the issue seems to be related to the NetCore.App package after RC2 having removed some assemblies. A new RC2 package is not published to nuget yet, we are trying to check on that. 

OSX issue is possibly difference since the crossgen2 package for OSX are not being published, you could run crossgen2 directly however.

**Comment by mangod9** [comment] 2020-10-12 17:25
We are working on a fix for this issue in .net 5 RTM builds. For now a simple workaround is to remove the entries for `System.IO.Pipelines.dll` and `System.Net.Connections.dll` from `crossgen2.deps.json` located in nuget cache for `microsoft.netcore.app.crossgen2` package.

**Comment by AntonLapounov** [comment] 2020-10-13 05:03
Hint: you may specify `--verbosity:normal` (or `-v:n`) on the `dotnet publish` command line to figure out the exact path of the `crossgen2` binary.  The path will be output right after the `_CreateR2RImages` target (I use Windows for this example):
```
       _CreateR2RImages:
         C:\Users\USERNAME\.nuget\packages\microsoft.netcore.app.crossgen2.win-x64\5.0.0-rtm.20506.3\tools\crossgen2.exe ...
```
Then open the `crossgen2.deps.json` file in that directory:
```
notepad C:\Users\USERNAME\.nuget\packages\microsoft.netcore.app.crossgen2.win-x64\5.0.0-rtm.20506.3\tools\crossgen2.deps.json
```
and either remove or comment out with `//` the following two lines:
```
          "System.IO.Pipelines.dll": {},
```
and
```
          "System.Net.Connections.dll": {},
```
Save the changes. The `dotnet publish` command should work after that.

**Comment by am11** [comment] 2020-10-13 11:40
I did not get _CreateR2RImages or _CreateR2RImages on macOS with -v:n or -v:d. I think the NETSDK1094 shows up before those targets are ran. R2R without crossgen2 works fine.

Are there any plans to publish crossgen2 net5.0 package for macOS?

**Comment by AntonLapounov** [comment] 2020-10-13 14:38
@am11 My comment was about the `NETSDK1096` error. `Crossgen2` is still a work in progress and at present only `win-x64` and `linux-x64` packages are published.

**Comment by mangod9** [comment] 2020-10-13 15:40
Hey @am11, I am going to reopen this issue since it tracks the crossgen2 failure on other platforms too. Will update the title to reflect that.

**Comment by mangod9** [comment] 2020-10-15 05:29
the sdk version update has been merged as part of this PR: https://github.com/dotnet/runtime/pull/43321, but need to validate latest sdk builds to ensure the issue is resolved.

**Comment by mangod9** [comment] 2020-10-15 15:49
This is resolved in the latest SDK build `5.0.100-rtm.20515.6`. Thanks!

**Closed by mangod9** 2020-10-15 15:49 UTC
Labels: area-crossgen2-coreclr, blocking-release

**Comment by AntonLapounov** [comment] 2020-11-21 22:22
> Are there any plans to publish crossgen2 net5.0 package for macOS?

We have started publishing Crossgen2 package for macOS in .NET 6 builds:
https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet6&package=Microsoft.NETCore.App.Crossgen2.osx-x64&protocolType=NuGet&version=6.0.0-alpha.1.20571.2&view=versions

**Comment by am11** [comment] 2020-11-22 02:26
Thanks a lot! quickly tested the flow with latest dotnet6 installer and it seems like `ReadyToRunNoValidRuntimePackageError` (aka `NETSDK1094`) is still emitting from one of three methods in https://github.com/dotnet/sdk/blob/b5e5cc01/src/Tasks/Microsoft.NET.Build.Tasks/ResolveReadyToRunCompilers.cs. Might be something else needs to be updated, i'll wait for few days before taking it to test drive. 🙂

---

Separately, the singlefile crossgen2 published app on linux failed to run with SIGABRT:

```sh
$ uname -s
Linux

$ dotnet --version
6.0.100-alpha.1.20571.4

$ dotnet new console -n r2rtest; cd r2rtest
$ dotnet publish -p:'PublishReadyToRun=True,PublishReadyToRunUseCrossgen2=True,PublishSingleFile=true' -c Release -r linux-x64

$ du -h bin/Release/net5.0/linux-x64/publish/r2rtest
73M	bin/Release/net5.0/linux-x64/publish/r2rtest

$ bin/Release/net5.0/linux-x64/publish/r2rtest
Aborted
```

here is the strace output: http://sprunge.us/8Z3arV vs. non-singlefile (which works / exists with code 0): http://sprunge.us/JljrMj. Looks like this line in singlefile variant is either the indication or red herring: `[pid 11183] ioctl(1, TCGETS, 0x7ffc1c903650) = -1 ENOTTY (Inappropriate ioctl for device)`.
(if this is not a known issue, I can open a new one for it 🙂)

**Comment by AntonLapounov** [comment] 2020-11-22 23:01
@am11 Building the package was the first step, we still need to polish the end-to-end scenario.  I have no Mac machine to debug it unfortunately.

Please open a new issue on Crossgen2 not working with PublishSingleFile.  I confirmed it is not working with .NET 5 either, crashing on both Windows and Linux.

**Comment by am11** [comment] 2020-11-27 13:39
> Please open a new issue on Crossgen2 not working with PublishSingleFile. I confirmed it is not working with .NET 5 either, crashing on both Windows and Linux.

Opened #45277.
