### ISSUE TITLE
AccessViolationException 0xc0000005 in CopyWatsonBucketsBetweenThrowables / coreclr.dll

### ISSUE THREAD

**Issue by baal2000** [dotnet/runtime#45929] opened 2020-12-10 23:47 UTC
### Description

A Windows service running in production environment crashes periodically (once-twice a week) with AVs as seen below:

```
Faulting application name: XXXXX.exe, version: 0.0.0.0, time stamp: 0x5f6b3998
Faulting module name: coreclr.dll, version: 4.700.20.47201, time stamp: 0x5f6a7a28
Exception code: 0xc0000005
Fault offset: 0x0000000000232e2b
```
WinDbg:  the point of failure in FW 3.1 is this [line](https://github.com/dotnet/coreclr/blob/release/3.1/src/vm/excep.cpp#L10309):

> PTR_VOID pRawSourceWatsonBucketArray = dac_cast<PTR_VOID>(refSourceWatsonBucketArray->GetDataPtr());

### Configuration

- .NET Core 3.1 (coreclr 4.700.20.47201 and 4.700.20.36602)
- Windows 2016 DataCenter Server x64
- 64 vCPUs, 400 GB of RAM 

### Regression?

On a first sight this started **immediately** after the upgrade to v3.1.7 (dotnet-sdk-3.1.401-win-x64) (coreclr.dll 4.700.20.36602) on August 30 (fault offset 0x0000000000232e1b).

#### Update 1

We found 5 more crashes in our logs going back to beginning of 2020 (although not as frequent as it happens now):
- 3 crashes on coreclr 4.700.20.6602
- 2 crashes on coreclr 4.700.20.20201
 
#### Update 2

Jan 23 2019: a similar exception handing failure: 

```
Faulting application name: XXXXX.exe, version: 0.0.0.0, time stamp: 0x5c007e95
Faulting module name: coreclr.dll, version: 4.6.27129.4, time stamp: 0x5c00327e
Exception code: 0xc0000005
Fault offset: 0x00000000001a3b8d
```

WinDbg > [e:\a\_work\104\s\src\vm\exceptionhandling.cpp @ 1029] (00000001`800379e0)   coreclr!ProcessCLRException+0x16c1ad   |  (00000001`80037e00)   coreclr!ExceptionTracker::ProcessOSExceptionNotification

### Other information

The crash dump attached in Visual Studio:

![image](https://user-images.githubusercontent.com/22180333/101839534-8a418f80-3b10-11eb-9a4c-9870ae464f91.png)

There is  a normal .NET exception ends up in the crash at excep.cpp#L10309. 

Outer exception: 
- {"Exception has been thrown by the target of an invocation."} System.Reflection.TargetInvocationException
- SerializationWatsonBuckets: null

InnerException 
- {"InitializingException: Initializing"} System.Exception {InitializingException}
-  SerializationWatsonBuckets {byte[5616]}

Note that the application is in startup mode and there are quite a few of these `Initializing`(s) flying around, increasing the possibility of the bug to present itself (if there is one). Indeed, the crash is more likely to happen during the takeoff than during the cruising phase of the process lifetime.

Looking around a bit I noticed that the method that hits the null ref is not supposed to run unless `AreWatsonBucketsPresent` returns true. Could it be a race condition?

Please advice if upgrading to FW 5.0 or moving to another OS could help with the issue short term.

I will provide more details as necessary. 

Thank you.

FYI @karelz

**Comment by baal2000** [comment] 2020-12-12 21:04
Update: we could reliably reproduce the crash in prod environment and also possessed a few crash dumps but unfortunately no small-scale repro. It looked like a large number of exceptions plus high allocation activity were the crash triggers.

**Comment by baal2000** [comment] 2020-12-15 16:35
**TargetInvocationException**

It was noticed by our team that `artificially` switching the Asp.Net Core application from a synchronous API method causing the app to crash to an async-like pattern by simply making a synchronous method return _Task.FromResult(result)_ made the crash go away. We looked at how the application middleware handles both types (async/sync) of the reflection-based invocation and also took into account that every crash dump the _Exception_ instance that caused the error was of type _TargetInvocationException_ wrapping the error from synchronous public API. As the result of such review we concluded that having _TargetInvocationException_ or not having it is the difference that either causes the app to crash or not to crash. 

TargetInvocationException is being generated by this line:

```
using (profiler.RecordTime(profiledName))
{
       return methodInfo.Invoke(instance, parameters);
}
```

Note that there is no _TargetInvocationException_ potentially involved into handling of asynchronous API. This is the only thing we could think of what changed after converting synchronous method to asynchronous.

If we could make a change in the synchronous method invocation that makes _TargetInvocationException_  go away then we could potentially solve the crash.
And did we test that theory by replacing the above code with the _Invoke_ variant that uses a little-known, little-documented flag [BindingFlags.DoNotWrapExceptions](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.bindingflags?view=netcore-2.1) that is available there since FW 2.1.

```
using (profiler.RecordTime(profiledName))
{
         return methodInfo.Invoke(instance, BindingFlags.DoNotWrapExceptions, null, parameters, System.Globalization.CultureInfo.InvariantCulture);
}
```
The process hasn’t crashed.

BindingFlags.DoNotWrapExceptions was introduced as the result of

issue: https://github.com/dotnet/coreclr/pull/13767
commit: https://github.com/dotnet/coreclr/commit/1f9aeeb7a3685bc7fd1098fc50d91ac81bae4873

Note that we haven't had these kind of exceptions until a move to FW 2.1. If I am to speculate it is feasible that this change also broke _TargetInvocationException_ somehow as it involved deep updates to _RuntimeTypeHandle_ and elsewhere. FYI: @AustinWise  

We are still working on a smaller-scale reproduction but if there is a will double-check the commit mentioned above or get an available crash dump file or a few for the team's review, we can do that as well.

**Comment by shortspider** [comment] 2020-12-15 17:16
@danmosemsft documentation aside, we are hitting this crash in production. Are or will you guys be looking into this? We have a number of dumps and can reproduce this at will using our application. We would be happy to get on a call and provide anything that you need to help get to the bottom of this.

**Comment by danmosemsft** [comment] 2020-12-15 17:31
I hear you, that's clearly the real issue. I don't have expertise in this area though: it is owned by @janvorli

**Comment by janvorli** [comment] 2020-12-15 18:19
@shortspider, @baal2000 let me read all the details provided, look at the related code and get back to you.

**Comment by janvorli** [comment] 2020-12-15 18:51
Btw, moving to Linux should fix this problem as there is no Watson on Unix and the problematic method is never called.

**Comment by shortspider** [comment] 2020-12-15 18:51
Thank you very much @janvorli and @danmosemsft, if you need anything please let myself of @baal2000 know.

**Comment by shortspider** [comment] 2020-12-15 20:00
@janvorli thanks for that, great to confirm that. Unfortunately we are not going to be able to do that in a short time frame so we really are looking for a Windows fix.

**Comment by janvorli** [comment] 2020-12-15 20:05
That makes sense. I wonder - what does the InitializingException mean? Does it fire on every startup of your application? Or does it fire only sometimes, in the cases when you observe the crash?

**Comment by shortspider** [comment] 2020-12-15 20:14
@janvorli so we have simplified our repro a little bit and ruled out any initialization issues on our app. Once the app is up and running if you throw enough requests at it that cause a TargetInvocationException to be thrown it will crash within a few min. It doesn't matter what exception is thrown, just that it's wrapped into a TargetInvocationException.

We are trying to reproduce with a stock standard asp.net app but no luck yet.

**Comment by janvorli** [comment] 2020-12-15 20:16
Thank you for the details.

**Comment by shortspider** [comment] 2020-12-15 20:21
No problem. If you need anything else from us please let me know.

**Comment by janvorli** [comment] 2020-12-18 19:13
@shortspider I've spent a day trying to figure out a race that could result in the issue you are seeing and to create a repro that could trigger it. I have some initial idea about possible mechanism that could lead to this (even though I am not sure if some of the things that I am thinking of can happen). But I wasn't able to repro the problem.

One thing that may shed some light on the problem would be to get call stacks of all threads when the issue fires. One thing that is sure is that it is a race, as the method CopyWatsonBucketsBetweenThrowables that crashes with null reference in the refSourceWatsonBucketArray is only called after checking that the  watson buckets are actually present.
Regarding the call stacks I care only about the native / managed runtime frames, you can remove all parts of the stack traces containing your private code.

**Comment by shortspider** [comment] 2020-12-18 19:30
@janvorli sure we can get that for you. It will take a bit of time but I'll try and get it for early next week.

**Comment by shortspider** [comment] 2020-12-18 22:02
@janvorli I have the callstacks, is there a way I can share them directly with you only instead of posting it on GitHub?

**Comment by janvorli** [comment] 2020-12-18 22:04
Sure, my email address is my alias (the same as on github) at microsoft.

**Comment by baal2000** [comment] 2020-12-19 02:16
@janvorli 
Here the reproduction of the issue: https://github.com/baal2000/AccessViolationInReflectionInvoke
Details are in README.md, please let me know if it works for you.

**Comment by janvorli** [comment] 2020-12-21 10:22
Thank you very much for the repro. I was able to hit the issue with it. I just wonder - the original error you have reported was an access violation, the repro fails with internal clr error. It is very well possible that the issue has two different failure modes, but I was still wondering if you have also hit the access violation with the repro.

**Comment by janvorli** [comment] 2020-12-21 11:05
I was actually able to repro the access violation too, so I am confident your repro reproes the original failure.

**Comment by baal2000** [comment] 2020-12-21 13:30
No problem @janvorli , glad it worked.

What is "Internal CLR error 0x80131506" anyway: a non-specific managed exception caused by AV? Does one (AV) lead to another (CLR Err) and then the later is being reported to the console while the former remains hidden from view? 

Or there are more than one way the race condition could end up crashing the runtime?

Also, if you could comment on the pattern of reusing a shared exception instance that ultimately triggers the issue: is there anything wrong with that? A the moment we replaced the Invoke with a variant that allows avoiding TargetViolationException to avoid the issue. Would that be sufficient or only moves the issue from one place to another?

**Comment by janvorli** [comment] 2020-12-21 14:46
That error represents an internal .NET error. It represents an unexpected failure that should not happen under normal circumstances and we cannot continue without a risk of further corruption of the application state.

The reason why the one we are seeing sometimes causes the internal error and sometimes it crashes with AV is that it depends on where the racing thread overwrites the watson buckets in the exception object. The native runtime code that processes the exception has multiple places where the code path depends on whether the watson buckets are null or not. So e.g. in the AV case, there is an `if ` that checks whether the buckets are present or not and if it finds they are, it calls another method that expects that the buckets are present. But the other thread overwrites the reference by null right after the check, so we enter a method that tries to use it as a valid reference and crashes. AVs in the native runtime are not translated to null reference exceptions except for few well defined places.

Reusing single exception instance by multiple threads at the same time doesn't sound like a good practice.  I wander what is your reason for doing that? If your reason was to save allocations of the exception objects (reducing the amount of garbage), reusing single one actually causes more allocations. ExceptionDispatchInfo.Capture allocates the ExceptionDispatchInfo, the RestoreDispatchState makes e.g. a deep copy of the stack trace (https://github.com/dotnet/runtime/blob/f8f63b1fde85119c925313caa475d9936297b463/src/coreclr/System.Private.CoreLib/src/System/Exception.CoreCLR.cs#L202-L203).

Having said that, the way you reuse exception objects should not result in runtime crash / internal error, so we should fix that race. However, I think it is not likely that such a fix would be ported back to 5.0 or even 3.1, as this is something you can workaround by not reusing the exception by multiple threads at the same time.

**Comment by baal2000** [comment] 2020-12-21 14:55
Makes sense, thank you so much.

**Comment by baal2000** [comment] 2020-12-21 16:00
@janvorli 
> Reusing single exception instance by multiple threads at the same time doesn't sound like a good practice. I wander what is your reason for doing that?

The reason was to have a shortcut to avoid potentially expensive operation when a system was in a known non-performing state (to bail out fast). If the state produced a certain failure result then it would be beneficial if we could "clone" that result (as cached Exception instance) and pass it down to each individual API request. 

We could've wrapped into some specialized Exception instance, like AggregateException or TargeiInvocationException ourselves and then unwrap on delivery, but we didn't want to do that and simple-mindedly implemented as `ExceptionDispatchInfo.Capture(exception).Throw()`. There was nothing in the documentation that would alert about the dangers or the thread safety for `ExceptionDispatchInfo.Capture` or `ExceptionDispatchInfo.Throw`.

Is there a third way?

**Comment by janvorli** [comment] 2020-12-21 16:14
I am still not sure I understand what is the potentially expensive operation you are worried about. Does the exception that you are throwing in your real world case contain some extra data that are expensive to collect? In that case, you could have that data stored in a separate object and cached and let the exception just have a reference to it.

**Comment by baal2000** [comment] 2020-12-21 17:22
@janvorli 
>I think it is not likely that such a fix would be ported back to 5.0 or even 3.1, as this is something you can workaround by not reusing the exception by multiple threads at the same time.

I should also mention that there are rare instances when we could not trace the AV back to sharing the same instance. May be some other `ExceptionDispatchInfo.Throw()` call was made from a different part of the application code (or a library code) where unintended concurrent instance reuse happened. Unfortunately we could not collect the dump in these circumstances. 

Every usage of ExceptionDispatchInfo class is now a suspect because of that. While it is not up to us to decide whether porting the fix back to at least version 5.0 or 3.1 (LTS) is feasible or not, I'd strongly vote for that to happen.

**Comment by janvorli** [comment] 2020-12-23 12:07
I wonder if you really use this exact ExceptionDispatchInfo.Capture(error).Throw() like in the repro or if you capture at one place and throw at another. I am just curious, it would not fix the problem.

I have found that calling the ExceptionDispatchInfo.Capture(error).Throw() on many threads at once leads to growing the Exception.StackTrace enormously and contains the same frames over and over. It basically cumulates it at each ExceptionDispatchInfo.Capture(error).Throw(). It seems ugly and I don't know if you are aware of that.

As far as I can tell, there doesn't seem to be a mechanism that would allow you to rethrow the original exception with its original stack trace untouched. The closest ways I can see is what you've already mentioned. At the place where you want to throw the cached exception, wrap the cached exception in a new instance of some other exception and throw that. Then unwrap it at the place where you catch it. This seems to be the cleanest way and it won't touch the original exception, thus the watson buckets issue could not happen.

**Comment by baal2000** [comment] 2020-12-23 13:19
> if you really use this exact ExceptionDispatchInfo.Capture(error).Throw() like in the repro

Yes and moving away from that.

> calling the ExceptionDispatchInfo.Capture(error).Throw() on many threads at once leads to growing the Exception.StackTrace

Does that warrant `ExceptionDispatchInfo` documentation update?

Maybe not the right place for this type of feedback but can't help myself but mention that the SDK documentation has moved away from a standard `Thread Safety` section to a free-form, inconsistent notices 
sprinkled around to some classes but not others. Example: [TextWriter](https://docs.microsoft.com/en-us/dotnet/api/system.io.textwriter)

Used to be:

```
Thread Safety
Any public static (Shared in Visual Basic) members of this type are thread safe. Any instance members are not guaranteed to be thread safe.
``` 

Now: buried within the `Remarks` section
```
 By default, a TextWriter is not thread safe....
```

**Closed** 2021-01-07 16:44 UTC
Labels: area-ExceptionHandling-coreclr, in pr
