### ISSUE TITLE
Test failure JIT\\HardwareIntrinsics\\X86\\Sse42\\Crc32_ro\\Crc32_ro.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#65040] opened 2022-02-09 01:24 UTC
Run: [runtime-coreclr outerloop 20220208.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1600096&view=ms.vss-test-web.build-test-results-tab&runId=44696814&paneView=debug&resultId=100147)

Failed test:
```
R2R-CG2 windows x86 Checked @ Windows.10.Amd64.Open

- JIT\\HardwareIntrinsics\\X86\\Sse42\\Crc32_ro\\Crc32_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse42\\Sse42_ro\\Sse42_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse42\\Sse42_r\\Sse42_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse42.X64\\Crc32_r\\Crc32_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse42.X64\\Crc32_ro\\Crc32_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse42\\Crc32_r\\Crc32_r.cmd

```
**Error message:**
```
Could Not Find C:\h\w\B600099D\w\A42B08CC\e\JIT\HardwareIntrinsics\X86\Sse42\Crc32_ro\IL-CG2\composite-r2r.dll
Could Not Find C:\h\w\B600099D\w\A42B08CC\e\JIT\HardwareIntrinsics\X86\Sse42\Crc32_ro\Crc32_ro.dll.rsp
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'System.Collections.Immutable, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The module was expected to contain an assembly manifest.
File name: 'System.Collections.Immutable, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
at ILCompiler.Program.Run(String[] args)
at ILCompiler.Program.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\B600099D\w\A42B08CC\uploads\Reports\JIT.HardwareIntrinsics\X86\Sse42\Crc32_ro\Crc32_ro.output.txt
Raw output:
BEGIN EXECUTION
Crc32_ro.dll
TestLibrary.dll
2 file(s) copied.
Response file: C:\h\w\B600099D\w\A42B08CC\e\JIT\HardwareIntrinsics\X86\Sse42\Crc32_ro\Crc32_ro.dll.rsp
C:\h\w\B600099D\w\A42B08CC\e\JIT\HardwareIntrinsics\X86\Sse42\Crc32_ro\IL-CG2\Crc32_ro.dll
-o:C:\h\w\B600099D\w\A42B08CC\e\JIT\HardwareIntrinsics\X86\Sse42\Crc32_ro\Crc32_ro.dll
--targetarch:x86
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\B600099D\p\System..dll
-r:C:\h\w\B600099D\p\Microsoft..dll
-r:C:\h\w\B600099D\p\mscorlib.dll
-r:C:\h\w\B600099D\p\netstandard.dll
-O
" "dotnet" "C:\h\w\B600099D\p\crossgen2\crossgen2.dll" @"C:\h\w\B600099D\w\A42B08CC\e\JIT\HardwareIntrinsics\X86\Sse42\Crc32_ro\Crc32_ro.dll.rsp"   -r:C:\h\w\B600099D\w\A42B08CC\e\JIT\HardwareIntrinsics\X86\Sse42\Crc32_ro\IL-CG2*.dll"
Crossgen2 failed with exitcode - -532462766
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\B600099D\p
C:\h\w\B600099D\w\A42B08CC\e\JIT\HardwareIntrinsics\X86\Sse42\Crc32_ro\Crc32_ro.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_HardwareIntrinsics._X86_Sse42_Crc32_ro_Crc32_ro_._X86_Sse42_Crc32_ro_Crc32_ro_cmd()
```

**Comment by VincentBu** [comment] 2022-02-18 01:14
Failed again in: [runtime-coreclr outerloop 20220217.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1618268&view=ms.vss-test-web.build-test-results-tab&runId=45013664&resultId=100095&paneView=debug)

Failed test:
```
R2R-CG2 windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open

- JIT\\HardwareIntrinsics\\X86\\Avx2\\BroadcastVector128ToVector256_r\\BroadcastVector128ToVector256_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Avx2\\GatherMaskVector256_r\\GatherMaskVector256_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Avx2\\Avx2_ro\\Avx2_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Avx2\\SubtractSaturate_r\\SubtractSaturate_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Avx2\\UnpackLow_r\\UnpackLow_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Avx2\\ShiftLeftLogicalVariable_r\\ShiftLeftLogicalVariable_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Avx2\\ShiftRightLogicalVariable_ro\\ShiftRightLogicalVariable_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Avx2\\HorizontalSubtract_ro\\HorizontalSubtract_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Avx2_Vector128\\Avx2_ro\\Avx2_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Avx2\\LoadAlignedVector256NonTemporal_ro\\LoadAlignedVector256NonTemporal_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Avx2\\GatherVector256_r\\GatherVector256_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Avx2\\ConvertToVector256_ro\\ConvertToVector256_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Avx2\\HorizontalSubtract_r\\HorizontalSubtract_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Avx2\\ShiftLeftLogicalVariable_ro\\ShiftLeftLogicalVariable_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Avx2\\HorizontalAdd_ro\\HorizontalAdd_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Avx2\\GatherVector128_r\\GatherVector128_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Avx2_Vector128\\Avx2_r\\Avx2_r.cmd
- JIT\\HardwareIntrinsics\\X86\\**

```
**Error message:**
```
Could Not Find C:\h\w\AFAC09BA\w\BA070A03\e\JIT\HardwareIntrinsics\X86\Avx2\BroadcastVector128ToVector256_r\IL-CG2\composite-r2r.dll
Could Not Find C:\h\w\AFAC09BA\w\BA070A03\e\JIT\HardwareIntrinsics\X86\Avx2\BroadcastVector128ToVector256_r\BroadcastVector128ToVector256_r.dll.rsp
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The given assembly name or codebase was invalid. (0x80131047)
File name: 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

Return code:      1
Raw output file:      C:\h\w\AFAC09BA\w\BA070A03\uploads\Reports\JIT.HardwareIntrinsics\X86\Avx2\BroadcastVector128ToVector256_r\BroadcastVector128ToVector256_r.output.txt
Raw output:
BEGIN EXECUTION
BroadcastVector128ToVector256_r.dll
TestLibrary.dll
2 file(s) copied.
Response file: C:\h\w\AFAC09BA\w\BA070A03\e\JIT\HardwareIntrinsics\X86\Avx2\BroadcastVector128ToVector256_r\BroadcastVector128ToVector256_r.dll.rsp
C:\h\w\AFAC09BA\w\BA070A03\e\JIT\HardwareIntrinsics\X86\Avx2\BroadcastVector128ToVector256_r\IL-CG2\BroadcastVector128ToVector256_r.dll
-o:C:\h\w\AFAC09BA\w\BA070A03\e\JIT\HardwareIntrinsics\X86\Avx2\BroadcastVector128ToVector256_r\BroadcastVector128ToVector256_r.dll
--targetarch:x64
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\AFAC09BA\p\System..dll
-r:C:\h\w\AFAC09BA\p\Microsoft..dll
-r:C:\h\w\AFAC09BA\p\mscorlib.dll
-r:C:\h\w\AFAC09BA\p\netstandard.dll
-O
" "dotnet" "C:\h\w\AFAC09BA\p\crossgen2\crossgen2.dll" @"C:\h\w\AFAC09BA\w\BA070A03\e\JIT\HardwareIntrinsics\X86\Avx2\BroadcastVector128ToVector256_r\BroadcastVector128ToVector256_r.dll.rsp"   -r:C:\h\w\AFAC09BA\w\BA070A03\e\JIT\HardwareIntrinsics\X86\Avx2\BroadcastVector128ToVector256_r\IL-CG2*.dll"
Crossgen2 failed with exitcode - -532462766
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\AFAC09BA\p
C:\h\w\AFAC09BA\w\BA070A03\e\JIT\HardwareIntrinsics\X86\Avx2\BroadcastVector128ToVector256_r\BroadcastVector128ToVector256_r.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_HardwareIntrinsics._X86_Avx2_BroadcastVector128ToVector256_r_BroadcastVector128ToVector256_r_._X86_Avx2_BroadcastVector128ToVector256_r_BroadcastVector128ToVector256_r_cmd()
```

**Comment by VincentBu** [comment] 2022-03-09 06:04
Failed again in: [runtime-coreclr outerloop 20220308.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1652840&view=ms.vss-test-web.build-test-results-tab&runId=45580722&resultId=100116&paneView=debug)

Failed test:
```
R2R-CG2 windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open

- JIT\\HardwareIntrinsics\\X86\\Sse42\\Sse42_r\\Sse42_r.cmd

```
**Error message:**
```
Could Not Find C:\h\w\A1FB0901\w\A1E50919\e\JIT\HardwareIntrinsics\X86\Sse42\Sse42_r\IL-CG2\composite-r2r.dll
Could Not Find C:\h\w\A1FB0901\w\A1E50919\e\JIT\HardwareIntrinsics\X86\Sse42\Sse42_r\Sse42_r.dll.rsp
Unhandled exception. System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)
at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable1 searchPath, Boolean throwOnError) at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable1 searchPath)
at Internal.JitInterface.JitConfigProvider.<>c__DisplayClass5_0.<Initialize>b__0(String libName, Assembly assembly, Nullable1 searchPath) at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags) at Internal.JitInterface.CorInfoImpl.GetJitHost(IntPtr configProvider) at Internal.JitInterface.CorInfoImpl.Startup(CORINFO_OS os) at Internal.JitInterface.JitConfigProvider.Initialize(TargetDetails target, IEnumerable1 jitFlags, IEnumerable1 parameters, String jitPath) at ILCompiler.ReadyToRunCodegenCompilationBuilder.ToCompilation() at ILCompiler.Program.RunSingleCompilation(Dictionary2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary2 unrootedInputFilePaths, HashSet1 versionBubbleModulesHash, CompilerTypeSystemContext typeSystemContext)
at ILCompiler.Program.Run(String[] args)
at ILCompiler.Program.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\A1FB0901\w\A1E50919\uploads\Reports\JIT.HardwareIntrinsics\X86\Sse42\Sse42_r\Sse42_r.output.txt
Raw output:
BEGIN EXECUTION
Sse42_r.dll
TestLibrary.dll
2 file(s) copied.
Response file: C:\h\w\A1FB0901\w\A1E50919\e\JIT\HardwareIntrinsics\X86\Sse42\Sse42_r\Sse42_r.dll.rsp
C:\h\w\A1FB0901\w\A1E50919\e\JIT\HardwareIntrinsics\X86\Sse42\Sse42_r\IL-CG2\Sse42_r.dll
-o:C:\h\w\A1FB0901\w\A1E50919\e\JIT\HardwareIntrinsics\X86\Sse42\Sse42_r\Sse42_r.dll
--targetarch:x86
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\A1FB0901\p\System..dll
-r:C:\h\w\A1FB0901\p\Microsoft..dll
-r:C:\h\w\A1FB0901\p\mscorlib.dll
-r:C:\h\w\A1FB0901\p\netstandard.dll
-O
" "dotnet" "C:\h\w\A1FB0901\p\crossgen2\crossgen2.dll" @"C:\h\w\A1FB0901\w\A1E50919\e\JIT\HardwareIntrinsics\X86\Sse42\Sse42_r\Sse42_r.dll.rsp"   -r:C:\h\w\A1FB0901\w\A1E50919\e\JIT\HardwareIntrinsics\X86\Sse42\Sse42_r\IL-CG2*.dll"
Crossgen2 failed with exitcode - -532462766
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\A1FB0901\p
C:\h\w\A1FB0901\w\A1E50919\e\JIT\HardwareIntrinsics\X86\Sse42\Sse42_r\Sse42_r.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_HardwareIntrinsics._X86_Sse42_Sse42_r_Sse42_r_._X86_Sse42_Sse42_r_Sse42_r_cmd()
```

**Comment by tannergooding** [comment] 2022-03-11 17:25
Dupe of https://github.com/dotnet/runtime/issues/65646

**Closed by tannergooding** 2022-03-11 17:25 UTC
Labels: arch-x86, os-windows, area-crossgen2-coreclr, untriaged, blocking-outerloop
