### ISSUE TITLE
CS0759 and CS8795 with LoggerMessageAttribute and single-line "namespace" - the autogenerated code doesn't pick up the namespace.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#58790] opened 2021-09-08 08:33 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/CS0759-and-CS8795-with-LoggerMessageAttr/1503588)._

---
In Visual Studio 2022 preview 3, the following code will generate these errors unless "#define OLD_SYNTAX" is uncommented:

>[redacted]\Microsoft.Extensions.Logging.Generators\Microsoft.Extensions.Logging.Generators.LoggerMessageGenerator\LoggerMessage.g.cs(13,40,13,44): error CS0759: No defining declaration found for implementing declaration of partial method 'TestClass.Log.Test(ILogger)'
>[redacted]\a.cs(16,40,16,44): error CS8795: Partial method 'TestClass.Log.Test(ILogger)' must have an implementation part because it has accessibility modifiers.

It's because the code generator does not recognize single-line "namespace TestNameSpace;" (without { })  and generates code for TestClass not in the correct namespace.

```
//#define OLD_SYNTAX

using Microsoft.Extensions.Logging;

namespace TestNameSpace
#if OLD_SYNTAX
{
#else
;
#endif
    public partial class TestClass
    {
        public static partial class Log
        {
            [LoggerMessage(100, LogLevel.Information, "Test")]
            public static partial void Test(ILogger logger);
        }
    }
#if OLD_SYNTAX
}
#endif

```

---
#### Feedback Bot on 8/16/2021, 00:15 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by maryamariyan** [comment] 2021-09-08 15:53
dupe of https://github.com/dotnet/runtime/issues/57880

**Closed by maryamariyan** 2021-09-08 15:53 UTC
Labels: untriaged, area-Extensions-Logging
