### ISSUE TITLE
Provide overloads for Enumerable.ToArray/ToList/ToHashSet for the initial capacity

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#91888] opened 2023-09-11 16:42 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Provide-overloads-for-EnumerableToArray/1677292)._

---
I'm missing since years the opportunity to pass the correct size of lists or arrays when i use LINQ queries.
Often you know already the expected (or at least you can give a hint), so it's a waste of CPU cycles if you use for example ToArray which is [doubling size algorithm](https://referencesource.microsoft.com/#System.Core/System/Linq/Enumerable.cs,ed118118b642d9d4).

So provide overloads for the capacity.

---
#### Feedback Bot on 2/27/2022, 07:22 PM: 

(private comment, text removed)

**Comment by eiriktsarpalis** [comment] 2023-09-11 17:49
Duplicate of https://github.com/dotnet/runtime/issues/29620 and https://github.com/dotnet/runtime/issues/83807. The sentiment is that if presizing the target collection is essential for performance, then LINQ is likely not the most appropriate API to use. We already have tools such as `TryGetNonEnumeratedCount` that such methods could use to make the appropriate allocations without the user needing to pass an explicit value.

**Closed** 2023-09-20 14:46 UTC
Labels: api-suggestion, area-System.Linq, untriaged
