### ISSUE TITLE
Regression in Microsoft.Extensions.Configuration.Binder in DotNet 6 RC2

### ISSUE THREAD

**Issue by fitdev** [dotnet/runtime#61202] opened 2021-11-04 10:55 UTC
### Description

In DotNet 6 RC1 and before, I could get my custom type:

```cs
public class MyType : IEnumerable<Something> {
public MyType (string value) { 
//do stuff
}
}
```

to be properly instantiated via the constructor and bound to a property on my options class:

```cs
public class MyOptions {
public MyType PropertyName {get; set; }
}

```

from appropriate section in json config:

```json
{
"PropertyName" : "foo"
}
```

However now it throws an exception on my end because of how `MyType` that is being instantiated by the ConfigurationBinder works. The main point though is that in RC2 ( opposed to RC1):

Instead of using `MyType`'s public constructor (or implicit conversion operator from string, which it also has), it creates it some other way _and then starts calling property setters on it_. This is completely wrong. Of course then `MyType` throws because it's not how it supposed to work.

I think the issue is with this commit:
https://github.com/dotnet/runtime/commit/de4151ef17405eb87f1362b51ec1836040186d41#diff-2e6f75e1d4f577e1c8c1b6a32d158ce7812a38ad8fcd3b4d762157b92c03e890

### Reproduction Steps

See Description.

### Expected behavior

When Binder encounters a type `T` on a property that it should instantiate, it should look for and use _public constructor_ on type `T` that accepts either string or int or whatever primitive came from the corresponding json property.

### Actual behavior

Binder does something very strange, apparently it is being tricked by the fact that `MyType` implements `IEnumerable` and so does special collection behavior.

### Regression?

Yes in RC2 from RC1

### Known Workarounds

Install RC1 nuget: https://www.nuget.org/packages/Microsoft.Extensions.Configuration.Binder/6.0.0-rc.1.21451.13

### Configuration

.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.2.21505.57
 Commit:    ab39070116

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-rc.2.21505.57\

Host (useful for support):
  Version: 6.0.0-rc.2.21480.5
  Commit:  6b11d64e7e

.NET SDKs installed:
  2.1.520 [C:\Program Files\dotnet\sdk]
  5.0.400-preview.21328.4 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.4.21255.9 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.5.21302.13 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.2.21505.57 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-rc.2.21480.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21480.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.2.21501.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by safern** [comment] 2021-11-09 03:23
@fitdev thanks for your report this was caused by: https://github.com/dotnet/runtime/commit/7f595ce3f4b79f21a14c43cd87041db90dcd6ad7#

We fixed this on: https://github.com/dotnet/runtime/commit/de4151ef17405eb87f1362b51ec1836040186d41#diff-2e6f75e1d4f577e1c8c1b6a32d158ce7812a38ad8fcd3b4d762157b92c03e890

However the fix didn't make it on time for RC2. However I was able to repro your issue now and validated that with the 6.0.0 package that we released today the issue is fixed, so you can just update your app to reference: https://www.nuget.org/packages/Microsoft.Extensions.Configuration.Binder/6.0.0 and it will be fixed.

I'm going to close the issue as fixed, please let me know if you have any further questions.

**Closed by safern** 2021-11-09 03:23 UTC
Labels: untriaged, area-Extensions-Configuration
