### ISSUE TITLE
Test failure System.IO.Tests.Directory_CreateDirectory.DirectoryLongerThanMaxLongPathWithExtendedSyntax_ThrowsException

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#64080] opened 2022-01-21 01:09 UTC
Run: [runtime 20220120.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1562514&view=ms.vss-test-web.build-test-results-tab&runId=43982628&resultId=170172&paneView=debug)

Failed test:
```
net7.0-windows-Release-x64-CoreCLR_release-Windows.11.Amd64.ClientPre.Open

- System.IO.Tests.Directory_CreateDirectory.DirectoryLongerThanMaxLongPathWithExtendedSyntax_ThrowsException
- System.IO.Tests.DirectoryInfo_Create.DirectoryLongerThanMaxLongPathWithExtendedSyntax_ThrowsException
```
**Error message:**
```
Assert.All() Failure: 2 out of 2 items in the collection did not pass.
[1]: Item: \?\C:\h\w\BDC009DA\t\Directory_CreateDirectory_kwyhmsjr.sty\DirectoryLongerThanMaxLongPathWithExtendedSyntax_ThrowsException_271_1b5f3197\d8425fd79b574b12bb35d01e87a41c22gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg\02645ad49761416ca46b45794580ceedgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg\904871964f4a408d8280d27f80657258gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg\cd58d64ddf1740aaa37244caa4f2ba46gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg\f6a35968682a40f0bea21cb4faca72ebgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg\1f240988f2be4b41b4ca05128dcdeb65gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg\b465879ea1a440539267856d4cd5b1abgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg\531c994729c24913abd499142c66008egggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg\c31ea0d949454adda0fedf1d179a2827gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg\1ce33fed45814b2c8b219cbcf8f72bb3gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg\d2cd30f3be7d45a686f5be185794ff94gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg\ff65e1fc76724a5fa41e6052742e222egggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg\632a2219b1a740b797f72ad2bd387de9gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg\cd855f4424be475c8314276ee1163a3cgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg\c60016f781db42f28863d6f01a6d6e44gggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg\56357b62f1ad4e678ca202476144924dgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg\7c5976317b5640349fcb964d1cda125agggggggggggggggggg


Stack trace
   at System.IO.Tests.Directory_CreateDirectory.DirectoryLongerThanMaxLongPathWithExtendedSyntax_ThrowsException() in /_/src/libraries/System.IO.FileSystem/tests/Directory/CreateDirectory.cs:line 273
```

**Comment by adamsitnik** [comment] 2022-01-21 08:45
It's a duplicate of https://github.com/dotnet/runtime/issues/64019

**Closed by adamsitnik** 2022-01-21 08:45 UTC
Labels: area-System.IO, os-windows, arch-x64, duplicate
