### ISSUE TITLE
[System.Text.Json] Deserialization with private parameterless constructor.

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/runtime#54904] opened 2021-06-29 15:15 UTC
I see deserialization with private parameterless constructor support has been removed in https://github.com/dotnet/runtime/pull/32213. That's fine but the problem is this has been done without providing a workaround to support deserialization with a private parameterless constructor.

I have tried as follows:

```C#
public class UserCreated
{
    /// <summary>
    /// Initializes a new instance of the <see cref="UserCreated"/> class.
    /// </summary>
    /// <param name="firstName">The first name of the user..</param>
    /// <param name="lastName">The last name of the user.</param>
    /// <param name="userName">The user name of the user.</param>
    /// <param name="email">The email of the user.</param>
    public UserCreated(string firstName, string lastName, string userName, string email)
    {
        Id = Guid.NewGuid();
        FirstName = firstName.ThrowIfOutOfLength(1, 30, nameof(firstName));
        LastName = lastName.ThrowIfOutOfLength(1, 20, nameof(lastName));
        UserName = userName.ThrowIfOutOfLength(1, 30, nameof(userName));
        Email = email.ThrowIfNullOrEmpty(nameof(email));
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="UserCreated"/> class. This is used for deserialization.
    /// </summary>
    [JsonConstructor]
    private UserCreated()
    {
    }

    public Guid Id { get; private set; }

    public string FirstName { get; private set; }

    public string LastName { get; private set; }

    public string UserName { get; private set; }

    public string Email { get; private set; }
}
```

Then I have found that [JsonConstructorAttribute](https://docs.microsoft.com/en-us/dotnet/core/compatibility/serialization/5.0/non-public-parameterless-constructors-not-used-for-deserialization) will only work on **public parameterless constructors**. This is another limitation and blocking issue.

**My question is why there is no such attribute-based support for the private parameterless constructor too?** **_Actually `JsonConstructorAttribute` should have worked irrespective of the access modifier of the constructor as I have added this intentionally._**

Now tell me how I can manually add deserialization support for the private parameterless constructor for the above code without moving back to `Newtonsoft.Json`.

Thank you.

**Comment by Symbai** [comment] 2021-06-30 08:40
> the problem is this has been done without providing a workaround

Ehm, the workaround is clearly mentioned in the commit you are referring to. Right at the bottom of the first post.

> Now tell me how I can manually add deserialization support for the private parameterless constructor for the above code without moving back to `Newtonsoft.Json`.

- Use the provided workaround or
- Make your constructor public or
- Switch back to Newtonsoft.Json

**Comment by TanvirArjel** [comment] 2021-06-30 08:46
@Symbai documentation just said:

>Otherwise, implement a `JsonConverter<T>` for the type and control the deserialization behavior.

but did not provide any sample implementation. Could you please write the implementation here for the class I have posted? Thank you.

**Comment by layomia** [comment] 2021-07-22 23:46
Duplicate of https://github.com/dotnet/runtime/issues/38327.

**Closed by layomia** 2021-07-22 23:46 UTC
Labels: area-System.Text.Json, customer assistance, documentation
