### ISSUE TITLE
HttpClient "remembers" Windows credentials

### ISSUE THREAD

**Issue by jmezach** [dotnet/runtime#1242] opened 2020-01-02 07:42 UTC
We're seeing interesting behaviour with .NET Core's HttpClient running on Windows where it seems to "remember" that at some point Windows authentication has been used and then keeps using that for subsequent requests. Maybe this is by design, but we wanted to raise this here since it feels like a security related bug to us.

Let me give some context though. We're currently in the process of building an API gateway using the [Ocelot](https://github.com/ThreeMammals/Ocelot) library that relies on ASP.NET Core and HttpClient to do its thing. Internally it caches the HttpClient instance for each downstream service that you exposes through it. It doesn't (yet) use the IHttpClientFactory though.

In our scenario we're trying to put this API gateway in between in an existing landscape of services. These services are accessed by both clients (browser applications) that use Windows Identity Foundation 3.5 cookies, but there's also service-to-service communication which relies on Windows Authentication. Obviously this isn't ideal, which is why we're introducing the API gateway to modernise our authentication methods.

During testing we noticed that calls made by the browser clients would sometimes fail, because a necessary header wasn't present. That header however is only required when using Windows authentication, so it seemed as if the browser clients were performing Windows authentication which doesn't make much sense. Also, it mostly didn't occur but once it did occur it somehow occurred a lot more often.

After digging in deeper we've managed to establish what was happening. When one of our services tries to call into another service and it goes through the API gateway, a challenge will be sent by the downstream service (through a WWW-Authenticate header). This challenge is then returned to the calling service, prompting it to send along Windows credentials to the API gateway. The gateway itself doesn't accept Windows authentication, so it will simply flow the Authorization header through to the downstream service. The call will then succeed.

However, since the HttpClient instance is cached, all subsequent requests going through that same instance, including requests coming from our browser clients, will now use the same Windows credentials when calling the downstream service. This caused an exception to be thrown, and a 500 Internal Service Error to be returned by the downstream service, since using that authentication method requires an additional header which is not sent by the browser clients. This 500 Internal Service Error effectively seems to reset the HttpClient, so subsequent calls will succeed again, until the next time Windows authentication is used.

For now we've worked around this by removing the Windows authentication headers through a DelegatingHandler in the API gateway so this cannot happen, however we still feel that there's a bug here. Is it by design that the HttpClient seems to cache these credentials? Is there some way to disable that behaviour?

**Comment by scalablecory** [comment] 2020-01-02 08:45
Duplicate of https://github.com/dotnet/corefx/issues/39621

**Closed by scalablecory** 2020-01-02 08:45 UTC
Labels: area-System.Net.Http, untriaged
