### ISSUE TITLE
[WASM] Assertion at /__w/1/s/src/mono/mono/metadata/class-accessors.c:89, condition `<disabled>' not met

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#65957] opened 2022-02-28 12:39 UTC
Configuration: `net7.0-Browser-Release-wasm-Mono_Release-normal-Ubuntu.1804.Amd64.Open`
CI build: [runtime-extra-platforms pipeline of the rolling build](https://dev.azure.com/dnceng/public/_build/results?buildId=1635633&view=ms.vss-test-web.build-test-results-tab&runId=45292506&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab&resultId=144047), [console log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-cb05cff1d8ce47b39e/normal-System.CodeDom.Tests/1/console.6f259020.log?sv=2019-07-07&se=2022-03-20T10%3A13%3A15Z&sr=c&sp=rl&sig=FrVLRF2Cwas27D4TofQcTNu4uFOmISvg4ItVEIYX6tk%3D)

```
[10:39:47] info: Starting:    System.CodeDom.Tests.dll
[10:39:54] fail: 
[10:39:54] fail: ==== JS stack trace =========================================
[10:39:54] fail: 
[10:39:54] fail: Security context: 0x08e70820dca9 <JSObject>#0#
[10:39:54] fail:     0: builtin exit frame: trace(this=0x08e708203701 <console map = 0x8e708240919>#1#,0x08e708108595 <String[100]: c"* Assertion at /__w/1/s/src/mono/mono/metadata/class-accessors.c:89, condition `<disabled>' not met\n">,0x08e708203701 <console map = 0x8e708240919>#1#)
[10:39:54] fail: 
[10:39:54] fail:     1: mono_wasm_trace_logger [0x8e7085d4cf9] [./dotnet.js:3] [bytecode=0x8e708b6a311 offset=153](this=0x08e7085c435d <Object map = 0x8e708246a21>#2#,0,4760266,70760064,4,0)
[10:39:54] fail:     2: _mono_wasm_trace_logger [0x8e70823dbe5] [./dotnet.js:6214] [bytecode=0x8e708b6a219 offset=31](this=0x08e70823f7c9 <JSGlobal Object>#3#)
[10:39:54] fail:     3: arguments adaptor frame: 5->0
...
[10:39:54] fail:   491: receiveInstantiationResult [0x8e7085dd775] [./dotnet.js:1413] [bytecode=0x8e708327fd1 offset=10](this=0x08e70823f7c9 <JSGlobal Object>#3#,0x08e708332375 <Object map = 0x8e708252cf9>#17#)
[10:39:54] fail:   492: StubFrame [pc: 0x55b810a8eef8]
[10:39:54] fail:   493: StubFrame [pc: 0x55b8109faf24]
[10:39:54] fail:   494: EntryFrame [pc: 0x55b8109d88f8]
[10:39:54] fail: =====================
[10:39:54] fail: 
[10:39:54] fail: * Assertion at /__w/1/s/src/mono/mono/metadata/class-accessors.c:89, condition `<disabled>' not met
[10:39:54] fail: 
[10:39:55] info: Process v8 exited with 1
[10:39:55] fail: Application has finished with exit code 1 but 0 was expected
XHarness exit code: 71 (GENERAL_FAILURE)
/datadisks/disk1/work/BD3309CD/w/AD710949/e /datadisks/disk1/work/BD3309CD/w/AD710949/e
----- end Mon Feb 28 10:39:55 UTC 2022 ----- exit code 71 ----------------------------------------------------------
```

**Comment by lambdageek** [comment] 2022-02-28 14:55
That line is `g_assertf (0, "%s: unexpected GC filler class", __func__);` in the call to `mono_class_get_flags`.  So it's some kind of GC issue

**Comment by radical** [comment] 2022-02-28 20:02
Dupe of https://github.com/dotnet/runtime/issues/63749

**Comment by radical** [comment] 2022-02-28 20:05
Closing in favor of #63749 .

**Closed** 2022-02-28 20:06 UTC
Labels: arch-wasm, untriaged, area-GC-mono
