### ISSUE TITLE
Blazor WebAssembly AOT Fails On Windows For Paths With a Space

### ISSUE THREAD

**Issue by Eddie-Hartman** [dotnet/runtime#103293] opened 2024-06-11 16:46 UTC
### Description

Continuation of #101055 since that was closed and I can't comment there.

This is also the third ticket I've submitted for build issues with spaces in paths. Can you please add some form of automated testing to make sure builds don't fail for having spaces in paths and/or project names?

```
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\8.0.6\Sdk\WasmApp.Native.targets(686,5): error : Pr
ecompiling failed for C:\Users\EddieHartman\source\repos\SNBI Collector\SNBI Collector\obj\Release\net8.0\wasm\for-publ
ish\aot-in\aot-instances.dll with exit code 1. [C:\Users\EddieHartman\source\repos\SNBI Collector\SNBI Collector\SNBI C
ollector.csproj]
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\8.0.6\Sdk\WasmApp.Native.targets(686,5): error : Ca
n not open image C:\Users\EddieHartman\source\repos\SNBI [C:\Users\EddieHartman\source\repos\SNBI Collector\SNBI Collec
tor\SNBI Collector.csproj]
```

### Reproduction Steps

See #101055 

### Expected behavior

See #101055 

### Actual behavior

See #101055 

### Known Workarounds

Remove spaces from paths, project name, etc.

### Configuration

Windows 11
Dotnet 8.0.206

### Other information

I upgraded my references and rebuilt and still have the same error. If I need to do something else to get this working please let me know. You can see from my error that this is indeed using 8.0.6 now.

**Comment by Eddie-Hartman** [comment] 2024-06-11 16:49
@ilonatommy and @lewing for awareness.

Please let me know if this may take another couple months to get fixed (meaning the time from report to deployment in a .net patch) as at this point I'm moving on from the project that is having this exact issue. If something is fixed and posted again I can certainly try it out or help as best I can, but my availability to do so will be more spotty.

**Comment by ilonatommy** [comment] 2024-06-12 07:04
I will look into it but we are testing spaces in paths each time we run any `WasmBuildTest` - the original fix added a space to the test path, both in net9 and net8 branch. This is interesting that they do not fail while users can still reproduce

**Comment by ilonatommy** [comment] 2024-06-13 15:20
Confirmed: the change is not in the newest release but we're expecting it to be published in `8.0.7`.

**Comment by Eddie-Hartman** [comment] 2024-07-09 21:52
I was able to get this working fine with today's update locally, however, I get an error in my Azure Devops pipeline which may be related?

```
Linking with emcc with -O2. This may take a while ...
   "C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.34.Node.win-x64\8.0.7\tools\bin\node.exe" C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.34.Sdk.win-x64\8.0.7\tools\emscripten\src\compiler.js C:\Users\VSSADM~1\AppData\Local\Temp\tmpbetknt0z.json --symbols-only
   "C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.34.Sdk.win-x64\8.0.7\tools\bin\wasm-ld.exe" @C:\Users\VSSADM~1\AppData\Local\Temp\emscripten_o9xi0d_o.rsp.utf-8
   "C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.34.Node.win-x64\8.0.7\tools\bin\node.exe" C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.34.Sdk.win-x64\8.0.7\tools\emscripten\src\compiler.js C:\Users\VSSADM~1\AppData\Local\Temp\tmp2r8i3krj.json
   "C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.34.Sdk.win-x64\8.0.7\tools\bin\wasm-opt" --strip-dwarf --post-emscripten -O2 --low-memory-unused --zero-filled-memory --pass-arg=directize-initial-contents-immutable --strip-debug --strip-producers "D:\a\1\s\SNBI Collector\obj\Release\net8.0\wasm\for-publish\dotnet.native.wasm" -o "D:\a\1\s\SNBI Collector\obj\Release\net8.0\wasm\for-publish\dotnet.native.wasm" -g --mvp-features --enable-exception-handling --enable-mutable-globals --enable-sign-ext --enable-simd
emcc : error : 'C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.Emscripten.3.1.34.Sdk.win-x64\8.0.7\tools\bin\wasm-opt --strip-dwarf --post-emscripten -O2 --low-memory-unused --zero-filled-memory --pass-arg=directize-initial-contents-immutable --strip-debug --strip-producers "D:\a\1\s\SNBI Collector\obj\Release\net8.0\wasm\for-publish\dotnet.native.wasm" -o "D:\a\1\s\SNBI Collector\obj\Release\net8.0\wasm\for-publish\dotnet.native.wasm" -g --mvp-features --enable-exception-handling --enable-mutable-globals --enable-sign-ext --enable-simd' failed (returned 3221226505) [D:\a\1\s\SNBI Collector\SNBI Collector.csproj]
C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\8.0.7\Sdk\WasmApp.Native.targets(513,5): error MSB3073: The command "emcc "@C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\8.0.7\runtimes\browser-wasm\native\src\emcc-default.rsp" -msimd128 "@C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.browser-wasm\8.0.7\runtimes\browser-wasm\native\src\emcc-link.rsp" "@D:\a\1\s\SNBI Collector\obj\Release\net8.0\wasm\for-publish\emcc-link.rsp"" exited with code 1. [D:\a\1\s\SNBI Collector\SNBI Collector.csproj]
```

The pipeline is using the updated .net versions and the exact same command succeeds locally.

There are no other details in terms of anything I can see to elaborate on the issue. Any help would be appreciated.

**Comment by Eddie-Hartman** [comment] 2024-07-17 15:32
@lewing @ilonatommy any update? Should I take this up with another team or a new issue?

To me it's clearly related, but I can't speak to why it would work fine on my machine and not in the pipeline since they are both windows machines with the same dotnet versions running the same command.

I'm willing to provide more detail or help if I can, but this is a basic project with nothing special on it so I'm guessing it can be easily re-created using any regular pipeline (this isn't a self-hosted pipeline). You may be able to reproduce it using the same steps I had in the other issue. Just make a project with a name like "Space Test", enable AOT compilation, then build it using the latest windows pipeline and latest .net setup.

**Comment by ilonatommy** [comment] 2024-07-18 13:56
@Eddie-Hartman I tried to reproduce with `8.0.7` on pipeline: https://github.com/ilonatommy/issue-103293. Could you, please help me figure out what's different in my repro than in your project?

**Comment by Eddie-Hartman** [comment] 2024-07-18 14:20
@ilonatommy Will do. Can't right now, but I'll try to get to it by tomorrow EOD.

**Comment by Eddie-Hartman** [comment] 2024-07-19 15:04
@ilonatommy I went ahead and cloned your repo and made a couple changes to get it building in our pipeline (like using windows latest as vmImage). That passed, then I made more changes to get it closer to my command:
`- script: dotnet publish "SNBI Collector/SNBI Collector.csproj" -c "Release" -o $(build.artifactStagingDirectory)/Site`
 At this point, I'm fairly convinced the issue I'm experiencing isn't related and this issue can be closed overall.

In terms of my current problem, any advice on how to proceed or where to raise a new issue? I respect your time and just don't want to have you keep spending time on something that might not be in your wheelhouse or responsibility, but I appreciate your help.

I can slowly keep adding pieces until it starts failing again and then work backwards, but that's a fairly large lift for a generic windows error without any details. The biggest difference right now appearing to be that this smaller test project has 32 assemblies while mine has 133.

I'm willing to set up a call or potentially give temporary private repo access to help take a look, but don't know where the line gets drawn from your end in terms of support.

In the meantime until I hear back, I'll see if I can expand upon your sample to add assembly references that mine has and see if that ends up reproducing the issue.

**Comment by ilonatommy** [comment] 2024-07-23 14:25
Conclusion after taking the issue offline:
the quoted log is a duplicate of this issue https://github.com/dotnet/runtime/issues/73069.
The discussed project could not apply `PublishTrimmed=true` -  it was not prepared for it. Lowering the optimization level of emscripten and adding `<DisableParallelEmccCompile>true</DisableParallelEmccCompile>` helped make the pipeline pass. The long-run fix would be to make the project suitable for trimming.

**Closed by ilonatommy** 2024-07-23 14:25 UTC
Labels: arch-wasm, area-VM-meta-mono
