### ISSUE TITLE
Https against invalid domain names (containing underscores) behaves differently on Linux than Windows and macOS

### ISSUE THREAD

**Issue by erikbra** [dotnet/runtime#58722] opened 2021-09-06 11:52 UTC
### Description

There is a difference in the behaviour of TLS server cert domain name validation on Linux compared to Windows and macOS.
While Windows and macOS accepts domains with underscores in them, Linux fails on certificate validation, with a `RemoteCertificateNameMismatch`.

Minimal repro:
```c#
using System;

using System.Net.Http;
using System.Threading.Tasks;

namespace MinimalRepro
{
    public static class Program
    {
        private const string NonExistent = "nonexistent-but-valid-domainname.wordpress.com";
        private const string Invalid = "invalid_hostname_with_underscores.wordpress.com";

        public static async Task Main()
        {
            var os = Environment.OSVersion;

            Console.WriteLine("\n\nRunning on: " + os);
            Console.WriteLine("==================================================");

            string[] addresses = { NonExistent, Invalid };

            foreach (var address in addresses)
            {
                Console.WriteLine("\n" + address);
                Console.WriteLine("****************************************");
                
                var client = new HttpClient()
                    { BaseAddress = new Uri($"https://{address}/") };

                try
                {
                    var resp = await client.GetAsync("");
                    Console.WriteLine("Response: " + resp);
                }
                catch (Exception e)
                {
                    //Console.WriteLine("Exception: " + e);
                    Console.WriteLine("Inner exception" + e?.InnerException);
                }
            }
        }
    }
}
```

#### Expected behaviour:

The behaviour should be the same on Linux and Windows.

##### Running on Windows and macOS outputs

```
Running on: Microsoft Windows NT 10.0.19043.0
==================================================

nonexistent-but-valid-domainname.wordpress.com
****************************************
Response: StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Server: nginx
  Date: Mon, 06 Sep 2021 11:16:54 GMT
  Transfer-Encoding: chunked
  Connection: keep-alive
  Vary: Accept-Encoding
  X-hacker: If you're reading this, you should visit automattic.com/jobs and apply to join the fun, mention this header.
  Host-Header: WordPress.com
  X-Frame-Options: SAMEORIGIN
  X-ac: 2.arn _dca
  Strict-Transport-Security: max-age=15552000; preload
  Content-Type: text/html; charset=utf-8
}

invalid_hostname_with_underscores.wordpress.com
****************************************
Response: StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Server: nginx
  Date: Mon, 06 Sep 2021 11:16:54 GMT
  Transfer-Encoding: chunked
  Connection: keep-alive
  Vary: Accept-Encoding
  X-hacker: If you're reading this, you should visit automattic.com/jobs and apply to join the fun, mention this header.
  Host-Header: WordPress.com
  X-Frame-Options: SAMEORIGIN
  X-ac: 2.arn _dca
  Strict-Transport-Security: max-age=15552000; preload
  Content-Type: text/html; charset=utf-8
}
```

##### Running in docker (on Alpine-x64), or natively on Linux outputs

```
Running on: Unix 5.10.16.3
==================================================

nonexistent-but-valid-domainname.wordpress.com
****************************************
Response: StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Server: nginx
  Date: Mon, 06 Sep 2021 11:16:34 GMT
  Transfer-Encoding: chunked
  Connection: keep-alive
  Vary: Accept-Encoding
  X-hacker: If you're reading this, you should visit automattic.com/jobs and apply to join the fun, mention this header.
  Host-Header: WordPress.com
  X-Frame-Options: SAMEORIGIN
  X-ac: 1.arn _dca
  Strict-Transport-Security: max-age=15552000; preload
  Content-Type: text/html; charset=utf-8
}

invalid_hostname_with_underscores.wordpress.com
****************************************
Inner exceptionSystem.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
```

### Configuration

.NET 5, on Windows, macOS, Windows

### Repository with repro

I have created a repo containing the code in question, plus scripts for running natively and with docker, here: https://github.com/erikbra/dotnet-ssl-dns-issue

**Comment by karelz** [comment] 2021-09-07 19:39
Triage: This is OS leaking into errors. Not sure if we can ever fully be the same across platforms. @wfurt any further thoughts?

**Comment by wfurt** [comment] 2021-09-08 16:28
This is essentially dup of #35880. As @bartonjs mentioned we rely on OS functions to determine the validity and that brings the platform difference. Attempt to fix it could open another can of worms where .NET has different prospective than underlying OS about what is valid name.
While underscores are technically invalid in DNS, it is annoying that OpenSSL tries to enforce it at crypto layer instead of simple string matching.

https://github.com/openssl/openssl/blob/2f58cda4ce45c88f5c1d284eb155cbc9bcf4705f/crypto/x509v3/v3_utl.c#L662-L669

**Comment by karelz** [comment] 2021-09-08 20:42
Duplicate of #35880

**Closed by karelz** 2021-09-08 20:42 UTC
Labels: area-System.Net.Http, untriaged

**Comment by erikbra** [comment] 2021-09-10 12:27
Thanks for the clarification/comments, and link to the du. I thought the SSL code was natively implemented in C# now, but obviously not all of it :)
