### ISSUE TITLE
WritingShouldUpdateWriteTime_After_SetLastAccessTime [FAIL] 

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#95378] opened 2023-11-29 03:39 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=482375
Build error leg or test failing: System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime
Pull request: https://github.com/dotnet/runtime.git/pull/95334

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "WritingShouldUpdateWriteTime_After_SetLastAccessTime [FAIL]",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=482375
**Error message validated:** `WritingShouldUpdateWriteTime_After_SetLastAccessTime [FAIL]`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 11/29/2023 3:48:36 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[483023](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483023)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=483023&view=ms.vss-test-web.build-test-results-tab&runId=11119434&resultId=150785)|dotnet/runtime#95292|
|[482898](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482898)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482898&view=ms.vss-test-web.build-test-results-tab&runId=11113594&resultId=143163)|dotnet/runtime#95292|
|[482742](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482742)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482742&view=ms.vss-test-web.build-test-results-tab&runId=11109470&resultId=154952)|dotnet/runtime#94737|
|[482734](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482734)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482734&view=ms.vss-test-web.build-test-results-tab&runId=11109168&resultId=141706)|dotnet/runtime#94528|
|[482667](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482667)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482667&view=ms.vss-test-web.build-test-results-tab&runId=11105002&resultId=143538)|dotnet/runtime#94684|
|[482658](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482658)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482658&view=ms.vss-test-web.build-test-results-tab&runId=11104886&resultId=139693)|dotnet/runtime#95352|
|[482565](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482565)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482565&view=ms.vss-test-web.build-test-results-tab&runId=11101494&resultId=142277)|dotnet/runtime#95341|
|[482507](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482507)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482507&view=ms.vss-test-web.build-test-results-tab&runId=11099924&resultId=141911)|dotnet/runtime#85978|
|[482460](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482460)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482460&view=ms.vss-test-web.build-test-results-tab&runId=11098564&resultId=144186)|dotnet/runtime#95260|
|[482375](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482375)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482375&view=ms.vss-test-web.build-test-results-tab&runId=11096322&resultId=143552)|dotnet/runtime#95334|
|[482361](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482361)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482361&view=ms.vss-test-web.build-test-results-tab&runId=11096192&resultId=143827)|dotnet/runtime#95333|
|[482336](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482336)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482336&view=ms.vss-test-web.build-test-results-tab&runId=11095588&resultId=140996)|dotnet/runtime#95329|
|[482326](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482326)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482326&view=ms.vss-test-web.build-test-results-tab&runId=11095072&resultId=143439)|dotnet/runtime#95332|
|[482247](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482247)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482247&view=ms.vss-test-web.build-test-results-tab&runId=11092580&resultId=145532)|dotnet/runtime#95274|
|[482248](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482248)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482248&view=ms.vss-test-web.build-test-results-tab&runId=11092576&resultId=157264)|dotnet/runtime#95274|
|[482145](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482145)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482145&view=ms.vss-test-web.build-test-results-tab&runId=11087638&resultId=143413)|dotnet/runtime#93220|
|[481445](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481445)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481445&view=ms.vss-test-web.build-test-results-tab&runId=11085310&resultId=140495)|dotnet/runtime#95278|
|[482022](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482022)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle_Pathless.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=482022&view=ms.vss-test-web.build-test-results-tab&runId=11083828&resultId=144240)|dotnet/runtime#93220|
|[481904](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481904)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481904&view=ms.vss-test-web.build-test-results-tab&runId=11079820&resultId=144031)|dotnet/runtime#94868|
|[481867](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481867)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481867&view=ms.vss-test-web.build-test-results-tab&runId=11078868&resultId=143558)|dotnet/runtime#95301|
|[481857](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481857)|dotnet/runtime|[System.IO.Tests.File_GetSetTimes_SafeFileHandle.WritingShouldUpdateWriteTime_After_SetLastAccessTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=481857&view=ms.vss-test-web.build-test-results-tab&runId=11078494&resultId=142235)|dotnet/runtime#95307|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|18|21|21|

**Comment by jkotas** [comment] 2023-11-29 05:30
Duplicate of https://github.com/dotnet/runtime/issues/95298. It should be fixed now.

**Closed by jkotas** 2023-11-29 05:30 UTC
Labels: area-System.IO, blocking-clean-ci, untriaged, Known Build Error

**Comment by lewing** [comment] 2023-11-29 05:51
Build analysis was still red on that very pr, so perhaps the checks should rerun analysis once it have be validated?

cc @JulieLeeMSFT @agocke
