### ISSUE TITLE
DataView does not escape property names

### ISSUE THREAD

**Issue by miloush** [dotnet/runtime#85365] opened 2023-04-25 22:13 UTC
### Description

Citing the [Expression Syntax](https://docs.microsoft.com/en-us/dotnet/api/system.data.datacolumn.expression#expression-syntax):

> If the column name is enclosed in square brackets then any `]` and `\` characters (but not any other characters) in it must be escaped by prepending them with the backslash (`\`) character.

Unfortunately `DataView` does not follow this requirement:

https://github.com/dotnet/runtime/blob/4ab5265bd701d0f076979c3f63f130c61772b7be/src/libraries/System.Data.Common/src/System/Data/DataView.cs#L1097-L1104

As a result, trying to sort using columns with these names throws.

### Reproduction Steps

```c#
DataTable dt = new DataTable();
dt.Columns.Add("ahoj[x,y]test");
dt.Rows.Add("row1");
dt.Rows.Add("row2");
            
ITypedList list = dt.DefaultView;
PropertyDescriptorCollection properties = list.GetItemProperties(null);

IBindingListView listView = dt.DefaultView;
listView.ApplySort(properties[0], ListSortDirection.Ascending);
```

### Expected behavior

The column name is escaped as required, no exception.

### Actual behavior

System.ArgumentException: ' [ahoj[x isn't a valid Sort string entry.'

### Regression?

Repros in .NET Framework 4.8.

### Known Workarounds

Theoretically, the sort string can be set manually via `dt.DefaultView.Sort` (though that is not an option when the sorting is controlled by UI controls such as `DataGrid`).

In practice however, that does not work either, see #85367.

### Configuration

8.0.0-preview.3.23174.8
25346.1001.amd64fre.rs_prerelease.230415-1347

**Comment by roji** [comment] 2024-08-27 07:30
Duplicate of #85367

**Closed by roji** 2024-08-27 07:30 UTC
Labels: area-System.Data, untriaged
