### ISSUE TITLE
[API Proposal]: Add BitArray.CopyTo(Span<byte>)

### ISSUE THREAD

**Issue by kamronbatman** [dotnet/runtime#62680] opened 2021-12-11 23:37 UTC
### Background and motivation

We use BitArray to represent bitfields of 700+ values and copy them to buffers. Currently the code looks something like this
```cs
private static byte[] _bitFieldCopyBuffer = new byte[88];
```

```cs
bitField.CopyTo(_bitFieldCopyBuffer, 0);
_bitFieldCopyBuffer.CopyTo(buffer);
```

We are forced to do the copy twice and incur an allocation unless we maintain a static buffer in memory forever.

BitArray currently supports CopyTo for `byte[]` using `Span<byte>` so the mechanics are already in place to handle this.

### API Proposal

```C#
namespace System.Collections
{
    public class BitArray
    { 
        public BitArray(ReadOnlySpan<byte> span);
        public void CopyTo(Span<byte> span);
    }
}
```

I kind of jumped the gun (sorry) and made a pull request #62679. Feel free to close that PR if necessary.

### API Usage

```C#
var bitField = new BitArray(700);
bitField.Set(23, true);

Span<byte> someBuffer = new byte[1000]; // Buffer span from somewhere that we need to write the bitfield to
bitField.CopyTo(someBuffer);
```

**Comment by Symbai** [comment] 2021-12-12 09:23
Dupe of #30821

**Comment by kamronbatman** [comment] 2021-12-12 18:45
> Dupe of #30821

It looks like the appetite for that proposal might require spitting it. So let's not close this yet until we get alignment.

**Comment by layomia** [comment] 2022-01-13 00:46
Dupe of https://github.com/dotnet/runtime/issues/30821.

**Closed by layomia** 2022-01-13 00:46 UTC
Labels: api-suggestion, area-System.Collections, untriaged
