### ISSUE TITLE
Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo,object, IConfiguration, BinderOptions) – harmful call to PropertyInfo.GetValue(object)

### ISSUE THREAD

**Issue by Uzivatel919** [dotnet/runtime#52905] opened 2021-05-18 12:59 UTC
### Description
The [`ConfigurationBinder.BindProperty`](https://source.dot.net/#Microsoft.Extensions.Configuration.Binder/ConfigurationBinder.cs,fd12934fd6da12d8) seems to be 

```c#
private static void BindProperty(PropertyInfo property, object instance, IConfiguration config, BinderOptions options)
{
    // We don't support set only, non public, or indexer properties
    if (property.GetMethod == null ||
        (!options.BindNonPublicProperties && !property.GetMethod.IsPublic) ||
        property.GetMethod.GetParameters().Length > 0)
    {
        return;
    }

    object propertyValue = property.GetValue(instance);
    bool hasSetter = property.SetMethod != null && (property.SetMethod.IsPublic || options.BindNonPublicProperties);

    if (propertyValue == null && !hasSetter)
    {
        // Property doesn't have a value and we cannot set it so there is no
        // point in going further down the graph
        return;
    }

    propertyValue = GetPropertyValue(property, instance, config, options);

    if (propertyValue != null && hasSetter)
    {
        property.SetValue(instance, propertyValue);
    }
}
```
Lines `object propertyValue = property.GetValue(instance);` ,
``` c#
if (propertyValue == null && !hasSetter)
{
  // Property doesn't have a value and we cannot set it so there is no
  // point in going further down the graph
  return;
}
```

are obviously some debris somebody forgotten to remove. The line `object propertyValue = property.GetValue(instance);` can call to properties with not setter – like static properties – forcing them to execute.

Moreover, why to obtain any property value before asking if it can be passed to existing setter. 👎🏻

### Configuration

Microsoft.Extensions.Configuration.Binder 5.0.0 on .NET 5.0

### Area
area-Extensions-Configuration

**Comment by david-jarman** [comment] 2021-08-31 18:59
This is currently biting me, where I have a read-only property on one of my objects that can potentially throw an exception if called before some extra setup is executed. This forces me to modify the behavior of the property so it doesn't throw while the binding process is happening.

example:

```csharp
public class BindingObject
{
    public string BindThisString { get; set; }

    public OtherObject ThisIsNotSetDuringBinding { get; set; }

    // This will throw an exception during binding, because the get is called for no good reason
    public string DerivedPropertyString => $"DerivedProperty={ThisIsNotSetDuringBinding .Id}"
}
```

**Comment by ericstj** [comment] 2022-01-10 19:19
Reopening since the fix introduced a regression and will be reverted.

**Comment by ericstj** [comment] 2022-01-10 19:22
Make sure that any fix for this in the future accounts for the scenario here: https://github.com/dotnet/runtime/issues/63479

**Closed** 2022-04-02 19:01 UTC
Labels: up-for-grabs, area-Extensions-Configuration
