### ISSUE TITLE
Vector256.Shuffle() produces bad results in release mode

### ISSUE THREAD

**Issue by ayende** [dotnet/runtime#86432] opened 2023-05-18 11:14 UTC
### Description

Run the following code with release and debug configuration, it will give different outputs:

**Correct**

```
$ dotnet run -c Debug
<0, 0, 21, 2063, 2066, 3095, 0, 0>
```

**Wrong** 
```
dotnet run -c Release
<0, 0, 21, 2063, 0, 17, 0, 0>
```

Note that the last 4 elements are getting what appear to be random values. Repeated runs get different values.

### Reproduction Steps

Run:

```
using System.Runtime.Intrinsics;

Span<uint> a = stackalloc uint[8] { 0, 21, 2063, 2066, 3095, 0, 0, 0 };
var d = Vector256.Shuffle(
    Vector256.LoadUnsafe(ref a[0]), 
    Vector256.Create(8u, 0, 1, 2, 3, 4, 5, 6)
);

Console.WriteLine( d);

```

In release and debug mode.

### Expected behavior

Should generate the same output in both cases

### Actual behavior

Wrong output

### Configuration

dotnet --version
7.0.203

Tested on x64 Windows machine.

**Comment by hypeartist** [comment] 2023-05-18 12:07
7.0.400-preview.23225.8 (Debug):

```asm
vmovupd			ymm0, ymmword ptr[reloc @RWD00]
vmovupd			ymm1, ymmword ptr[reloc @RWD32]
vpermd			ymm1,ymm1,ymmword ptr [rcx]  
vpand				ymm1,ymm0,ymm1  
vxorps				ymm2,ymm2,ymm2  
vpandn			ymm0,ymm0,ymm2  
vpor					ymm6,ymm1,ymm0 
vextractf128	xmm7,ymm6,1 
vinsertf128		ymm6,ymm6,xmm7,1  
vmovupd			ymmword ptr [rax+8],ymm6 
```

7.0.400-preview.23225.8 (Release):

```asm
vmovupd			ymm0, ymmword ptr[reloc @RWD00]
vmovupd			ymm1, ymmword ptr[reloc @RWD32]
vpermd			ymm1,ymm1,ymmword ptr [rcx]  
vpand				ymm1,ymm0,ymm1  
vxorps				ymm2,ymm2,ymm2  
vpandn			ymm0,ymm0,ymm2  
vpor					ymm0,ymm1,ymm0  
vmovupd			ymmword ptr [rax+8],ymm0  
```

8.0.100-preview.4.23260.5 (Release):

```asm
vmovups			ymm0, ymmword ptr [reloc @RWD00]
vpermd			ymm0, ymm0, ymmword ptr [rax]
vpand				ymm0, ymm0, ymmword ptr [reloc @RWD32]
vmovups			ymmword ptr [rcx], ymm0
```

**Comment by hypeartist** [comment] 2023-05-18 12:23
@EgorBo Annotating method containing the code above with `[MethodImpl(MethodImplOptions.NoInlining)]` breaks 7.0.x Debug results too

**Comment by EgorBo** [comment] 2023-05-18 12:26
The problem that Vector256.Shuffle emits an unnecessary `vpand` here

**Comment by ayende** [comment] 2023-05-18 12:33
As long as we are talking about it, I was expecting that it would do something like:

```
var shiftedPrev = Vector256.Shuffle(prev, Vector256.Create(7u, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff));
```

Translated into:

```
var shiftedPrev = Avx2.PermuteVar8x32(prev, Vector256.Create(7u, 0, 0, 0, 0, 0, 0, 0)) &
            Vector256.Create(uint.MaxValue, 0, 0, 0, 0, 0, 0, 0);
```

**Comment by tannergooding** [comment] 2023-05-18 15:13
This is a duplicate of https://github.com/dotnet/runtime/issues/85132

There was a relatively simple issue with the codegen for out of bounds indices that needs to be backported to .NET 7 (we were only copying the lower 128-bits of the zeroing mask)

> The problem that Vector256.Shuffle emits an unnecessary vpand here in gtNewSimdShuffleNode when it's expected to just do Avx2.PermuteVar8x32

The `and` is expected and necessary so that out of bounds indices zero out the corresponding element in the result.

> As long as we are talking about it, I was expecting that it would do something like:

There are a few optimizations for `Shuffle` that got missed in .NET 7 due to the support coming in so late. They are on my backlog to still complete/improve for .NET 8

**Closed by tannergooding** 2023-05-18 15:13 UTC
Labels: bug, area-CodeGen-coreclr

**Comment by EgorBo** [comment] 2023-05-18 15:44
> The and is expected and necessary so that out of bounds indices zero out the corresponding element in the result.

why? the indexes are compile-time known, aren't they?

**Comment by tannergooding** [comment] 2023-05-18 16:08
> why? the indexes are compile-time known, aren't they?

Because out of bounds indices are documented as zeroing the corresponding result element; the underlying permute instruction doesn't do any zeroing, that's only the behavior of `pshufb` (and only if the most significant bit is set). Other permute instructions mask the index to always be "in range" instead.

**Comment by ayende** [comment] 2023-05-18 16:55
My intent was to actually do just that, zero the unimportant elements, by the way
