### ISSUE TITLE
BigInteger.ToString("x") includes leading zero when first digit is >= 8

### ISSUE THREAD

**Issue by tomtheisen** [dotnet/runtime#81743] opened 2023-02-07 06:04 UTC
### Description

Hexadecimal formatting for `BigInteger` includes an extraneous leading zero whenever the first (hex) digit is 8-F.

### Reproduction Steps

``` 
using System;
System.Numerics.BigInteger b = 200;
Console.WriteLine(b.ToString("x"));
```

### Expected behavior

I expect to see "c8".

### Actual behavior

I see "0c8".

### Regression?

I don't know.

### Known Workarounds

Always include `.TrimStart('0')`.

### Configuration

I'm running 7.0.1 on Windows 11 21H2 (Build 22000.1455).
This is on x64 architecture, but it seems to repro everywhere.

**Comment by vcsjones** [comment] 2023-02-07 14:04
Duplicate of https://github.com/dotnet/runtime/issues/43269 and https://github.com/dotnet/runtime/issues/72426.

This is working by design: the leading zero is to preserve the sign. Without the leading zero, the hex string would represent a negative value.

The documentation for [`Parse`](https://learn.microsoft.com/en-us/dotnet/api/system.numerics.biginteger.parse?view=net-7.0) has some explanation:

>  To make sure that a hexadecimal string is correctly interpreted as a positive number, the first digit in value must have a value of zero. For example, the method interprets 0x80 as a negative value, but it interprets either 0x080 or 0x0080 as a positive value. The following example illustrates the difference between hexadecimal strings that represent negative and positive values.

**Comment by tomtheisen** [comment] 2023-02-07 15:21
Thanks for following up.  I did check the docs for ToString, but didn't think to check Parse.

**Comment by dakersnar** [comment] 2023-02-07 19:58
Closing this for now, although we might want to consider adjusting the ToString docs.

**Closed by dakersnar** 2023-02-07 19:58 UTC
Labels: area-System.Numerics
