### ISSUE TITLE
ZipArchiveEntry.Open returning a truncated stream

### ISSUE THREAD

**Issue by yt6983138** [dotnet/runtime#105797] opened 2024-08-01 09:33 UTC
### Description

The stream returned by ZipArchiveEntry.Open is truncated, like the picture below:
![image](https://github.com/user-attachments/assets/ec81ef37-b683-4fe2-a488-2ecb84771390)
(Up: decompressed by SharpZipLIb, down: System.IO.Compression)
The zip that I was trying to decompress is here:
[save.zip](https://github.com/user-attachments/files/16453834/save.zip)

FYI: All other zip software decompresses just fine, tested: explorer and 7-zip

### Reproduction Steps

```c#
using ZipArchive archive = new(File.OpenRead(/* zip location */), ZipArchiveMode.Read);
ZipArchiveEntry? file = archive.GetEntry("gameRecord");

if (file is null)
	throw new InvalidDataException($"gameRecord not found.");

Stream stream = file.Open();
byte[] decompressed = new byte[file.Length];
stream.Read(decompressed);
stream.Dispose();

// ... write the data somewhere for comparsion
```

### Expected behavior

Data after 0x0FFB are decompressed normally.

### Actual behavior

Data after 0x0FFB are filled with zero.

### Regression?

I don't know

### Known Workarounds

I don't know (or using other library counts?)

### Configuration

.NET 8.0.302
Windows 10 pro 22H2
x64, intel i7-1255U
No I don't know if it's bound to that config
Not using Blazor

**Comment by huoyaoyuan** [comment] 2024-08-01 09:40
Duplicate of #73192, #96343, #97431, #105744 and so on.

`Stream.Read` doesn't guarantee to return all data available. You must read in a loop, or use the new `ReadExcatly` method.

**Closed by huoyaoyuan** 2024-08-01 09:40 UTC
Labels: area-System.IO.Compression, untriaged

**Comment by yt6983138** [comment] 2024-08-01 10:02
Ah, thanks, may i suggest add a remark on the docs? According to the docs
> ...  can be less than the size of the buffer if that many bytes are not currently available ... 

Made me thought that it will try to decompress all then return all data, and not just all _partial decompressed data_

**Comment by yt6983138** [comment] 2024-08-02 03:30
Ah, thanks for the explain
