### ISSUE TITLE
[API Proposal]: Consider adding WriteVoidEndElement and Depth to XmlTextWriter

### ISSUE THREAD

**Issue by CodeSetting** [dotnet/runtime#82091] opened 2023-02-14 13:59 UTC
### Background and motivation

First, you've done a spectacularly good job on the XML text writer!  It's nearly perfect.  I've been using it for decades with great success.

However, recently, I needed to write some HTML. Noticing that `HtmlTextWriter` had fallen somewhat out of favor, I looked to use `XmlTextWriter` instead.  I expected to have to "cheat" my way through a few things but was pleasantly surprised to see how easily I could use it to produce "normal" looking HTML.

I found two places for improvement, both of which I implemented mostly without cheating in a derived class.

**WriteVoidEndElement**
The first involves an inability to close HTML void elements like `<meta>`. Please consider adding a `WriteVoidEndElement` method to the XML writer.

This method would close the tag (and end the element) with a single ">" character instead of " />".  While obviously not valid XML, it would make `XmlTextWriter` friendlier to HTML. It would also nicely complement the pre-existing `WriteFullEndElement`.

And yes, I do know that empty/self-closing elements are well-supported in HTML. They just don't look "right" 😄 

**Depth**
Please consider adding a `Depth` property, which would track the current level of element nesting for the XML writer.

At times, when dealing with inline script, inline style, and "pre" tags, it is useful to temporarily disable formatting. When formatting is reenabled, indentation is often lost on the subsequent end tag. In addition to the pre-existing `IndentChar` and `Indentation` properties, a `Depth` property would allow me to correctly write my own indentation.

This particular property would also, I think, be more generally useful.  It would, for instance, allow consumers to more easily "close out" to a specific level of the document. For example, in my own derivation, I have added a `WriteEndElementUntil(int depth)` method for this purpose.

Thank you, in advance, for your consideration.

### API Proposal

```csharp
public void WriteVoidEndElement() { ... }

public int Depth { get; }
```

### API Usage

**WriteVoidEndElement**
```csharp
writer.WriteStartElement("meta");
writer.WriteAttributeString("charset", "utf-8");
writer.WriteVoidEndElement();
// Expected HTML: <meta charset="utf-8">
```

**Depth**
```csharp
writer.WriteStartElement("html");
writer.WriteStartElement("head");
Console.WriteLine(writer.Depth);
// Expected output: 2
```

### Alternative Designs
After reading the post by @koszeggy, and mostly agreeing with it, I thought I'd suggest an alternative. Provide a lightweight wrapper for `XmlWriter` called `HtmlWriter` that exposes the new `WriteVoidEndElement` method in a supported fashion. This would require the `XmlWriter` class to expose a protected mechanism the derived class could use to change the normal output produced when writing the end of an element.

Below, I discuss what I am currently doing in the absence of this mechanism.
 
**WriteVoidEndElement**
In the meantime, I've cheated my way through this one.  In a derived class, I wrap the original `TextWriter` in my own text writer, which can enable/disable the output.  To implement `WriteVoidEndElement`, I disable the output, call `WriteEndElement` to end the element, reenable the output, and use my underlying text writer to write the final ">" character. This approach works well and preserves formatting/indentation. However, at some point in the future, I'd really like to remove this ugliness.

**Depth**
In the meantime, I've implemented a better-supported workaround for this one. In a derived class, I added my own `Depth` property. I simply override `WriteStartElement` to increment it and `WriteEndElement`/`WriteFullEndElement` to decrement it. This approach works quite well.  However, at some point in the future, I'd really like to remove this ugliness as well.

### Risks

**WriteVoidEndElement**
With a new `WriteVoidEndElement` method, there is no risk to writers. However, there is a small risk that an unaware reader would not properly interpret a resulting file because, though valid HTML, it is not valid XML. This risk is greatly mitigated by the fact that the writer would likely indicate their intent by using a ".htm" or ".html" file extension on those files.

**Depth**
With a new `Depth` property, I honestly can't think of any legitimate risks.

**Comment by koszeggy** [comment] 2023-02-21 16:19
I strongly believe that an `XmlWriter` should not support non-XML content that cannot be parsed back by an `XmlReader`.

If you want to produce something like the old HTML 4 format you should create an SGML document, not XML. Today all HTML documents are XML files (XHTML).

To produce HTML you can use the [`HtmlTextWriter`](https://learn.microsoft.com/en-us/dotnet/api/system.web.ui.htmltextwriter) or [`HtmlContentBuilder`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.html.htmlcontentbuilder) classes instead.  I'm not sure whether they support the old SGML-based HTML 4 format though.

**Comment by CodeSetting** [comment] 2023-02-21 17:54
@koszeggy Thank you for your observations. I assume they are related to `WriteVoidEndElement`, and not `Depth`.|

If this is the case, in an ideal world I would normally agree with you 100%.  Regrettably, somewhat recent changes in .NET have forced me to live in a less-than-ideal world :smile:  This is what sent me looking for `XmlWriter` as an alternative.

I generally try to keep dependencies in my applications to a minimum...especially when they may run on non-Windows platforms.

You may be unaware that `HtmlTextWriter` is no longer available in .NET core. While there are NuGet packages that restore this functionality, security policies at my company prevent me from using them.

The `HtmlContentBuilder` class is generally only available to web applications, which my application is not. It produces HTML for consumption by websites but is not itself a website.

Of the things that are available, without adding dependencies, `XmlWriter` came the closest to fulfilling the requirements for a fast, lightweight means of producing HTML.

An alternative, which I would highly endorse, would be for .NET to provide a derived class (`HtmlWriter`) that adds `WriteVoidEndElement` in a supported fashion. This would require the `XmlWriter` class to expose an additional mechanism so that the derived class could end a void element in a supported fashion.

In consideration of your concerns, I will edit the proposal to list this approach as an alternative. Though, it seems like a lot of effort to me, to avoid adding one new method that no one is forced to call.

Currently, I have essentially pursued the alternative. I already derived my own `HtmlWriter` class. However, I was forced to implement an ugly hack to make it work without the aforementioned additional mechanism. In my own `WriteVoidEndElement`, I am forced to intercept and alter the output of 'XmlWriter.WriteEndElement()'.

It works, but it is ugly :smile:

**Comment by krwq** [comment] 2023-03-08 11:44
@CodeSetting did you consider razor templates instead?

**Comment by CodeSetting** [comment] 2023-03-11 15:02
@krwq thank you for your comments. I did not consider this, because the usage of the writer is not in a web app. Instead, I am working on a class library/nuget package, so I am trying to minimize dependencies that I pass along to consumers. Currently, the only dependency is on the Microsoft.NETCore.App framework.

**Comment by krwq** [comment] 2023-03-23 10:31
@CodeSetting another workaround you can consider here is to use XML to produce only content without meta charset and xml declaration and write them directly in the stream you are writing to with XML (basically create something along like HtmlStream and setup your writer in there and add extra methods in the ctor and Dispose to wrap entire content with whatever you need). Also you can try to use that with XmlSerializer as it might be much less code for you to support entire hierarchy.

I generally agree with previous statements that XML should stay XML without any non-standard syntax support and therefore I'll close this issue as won't fix by design. Please free to ask us any questions (preferably new issue or discussion so it doesn't get lost).

**Closed by krwq** 2023-03-23 10:31 UTC
Labels: api-suggestion, area-System.Xml, untriaged
