### ISSUE TITLE
Start time regressions on windows across many TE benchmarks

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#74315] opened 2022-08-21 22:12 UTC
I noticed a lot of start-time and time-to-first-request regressions on Windows in various benchmarks, e.g.:

### JsonMvc:
<img width=500  src="https://user-images.githubusercontent.com/523221/185812804-c99db3dc-387a-497a-8e8f-853ebc4a6bdd.png">

### PlatformPlaintext:
<img width=500  src="https://user-images.githubusercontent.com/523221/185812864-0c1699ac-5014-4d6c-be36-ce3198867562.png">

### PlaintextMvc:
<img width=500  src="https://user-images.githubusercontent.com/523221/185812902-fc4b33ce-184a-49c6-b607-c68818eaf5de.png">

What is even more interesting that DynamicPGO is now as fast as FullPGO:
<img width=500  src="https://user-images.githubusercontent.com/523221/185812931-a6247ccf-28dc-4a30-8549-bca701f52fbe.png">

it suggests that less methods are R2R'd (or R2R is broken)

cc @sebastienros

**Comment by EgorBo** [comment] 2022-08-21 22:15
dotnet/aspnetcore commit range: https://github.com/dotnet/aspnetcore/compare/14a3e98...87ef6f0
dotnet/runtime commit range: https://github.com/dotnet/runtime/compare/08fdcb7...37193fd

**Comment by EgorBo** [comment] 2022-08-21 22:50
The only thing I can blame is https://github.com/dotnet/runtime/pull/74279 - it bumps R2R format version from 7.1 to 8.0
cc @davidwrighton

**Comment by EgorBo** [comment] 2022-08-21 23:11
Yes, e.g. Kestrel (Microsoft.AspNetCore.Server.Kestrel.Core.dll) is R2R 7.1 while CoreLib is 8.0 for the "after" data point.

**Comment by EgorBo** [comment] 2022-08-21 23:23
It actually feels a bit weird if my guesses are correct - it means when you download a daily SDK - all binaries except corelib are prejitted with some older crossgen, not the one you'd expect

**Comment by mangod9** [comment] 2022-08-22 15:44
R2R version doesnt increment frequently. Agree that we are in a state where all previous crossgen2 built R2R binaries are going to be ignored. We need to ensure that asp.net builds with latest cg2 for RC1 to avoid these regressions.

**Comment by mangod9** [comment] 2022-08-22 15:46
surprising this doesnt show up on Linux? Perhaps the runtime version is not updating yet for those runs?

**Comment by sebastienros** [comment] 2022-08-22 17:11
Also I changed the SDK feed and it's taking 8.0.* now, but the regression doesn't seem related. Might be better to check we get the same numbers with a 7.0 SDK (`--application.sdkVersion 7.0.100-rc.2.22419.9`)

**Comment by mangod9** [comment] 2022-08-22 17:43
do we keep tracking 7 till GA? There are changes still being made there which would impact perf.

**Comment by sebastienros** [comment] 2022-08-22 17:58
We still take runtime and aspnet from 7 branches, just the SDK is updated so we are ready to run with net8.0 TFM when it's available (and runtime+aspnet).

**Comment by ivdiazsa** [comment] 2022-08-22 23:45
For the record, Linux runs have been also showing noticeable slowdowns.

**Comment by mangod9** [comment] 2022-08-24 17:42
Windows startup seems to have normalized, but Linux hasn't yet. Is there a delay in when the sdk is updated for the two platforms on TE?

**Comment by sebastienros** [comment] 2022-08-24 17:45
The benchmarks take the same SDK version for both. Sometimes the charts might be delayed. But I checked the version numbers in the tooltips and they are up to date.

**Comment by sebastienros** [comment] 2022-08-24 23:28
Issue seems to be fixed. The discrepancy is due to some machines using the dotnet8 feeds for builds, which contain some rc1 builds that are older than the latest ones. If you check the runtime version on these benchmarks you'll see it's not going up because of that. The charts that are fixed have up-to-date runtime versions with the fix.

I am pushing a change to _crank_ so that it will look on the other feeds for more recent versions.

**Comment by mangod9** [comment] 2022-08-25 16:14
closing this since its an infra issue.

**Closed by mangod9** 2022-08-25 16:14 UTC
Labels: area-crossgen2-coreclr
