### ISSUE TITLE
runtime-staging leg for PRs fails very frequently

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#49213] opened 2021-03-05 14:53 UTC
Can we do anything to improve this?  It takes out a lot of PRs, typically due to "runtime-staging (Build Android arm64 Release AllSubsets_Mono)" be canceled after running for 3 hours.

If not, can we remove the leg / make it opt-in / some other mitigation?

cc: @ViktorHofer, @safern, @marek-safar

**Comment by safern** [comment] 2021-03-05 16:04
@steveisok can we do something about Android legs that timeout pretty often?

**Comment by ViktorHofer** [comment] 2021-03-05 16:19
Wasn't the purpose of the staging leg to not fail the build and mark it as red?

**Comment by marek-safar** [comment] 2021-03-05 16:23
There is a hardware capacity limit that we at peak times hit. Increased capacity should be available soon though.

/cc @ilyas1974

**Comment by ilyas1974** [comment] 2021-03-05 16:25
The latest update from MLS has our new hardware going in starting Monday.

**Comment by steveisok** [comment] 2021-03-05 16:28
@stephentoub I think the answer for now is that we'll need to wait for increased capacity.  Having the android runs in the staging pipeline should lessen the impact should we run into capacity issues.

**Comment by stephentoub** [comment] 2021-03-05 16:42
> Having the android runs in the staging pipeline should lessen the impact should we run into capacity issues.

So I should ignore failures in the leg, correct?  If so, what's the benefit of running it on every PR if devs are then trained to not pay attention to failures?

**Comment by steveisok** [comment] 2021-03-05 17:01
I think we do and should continue to take these failures seriously.  The difference is that the failures / instability should not stop your PR's from progressing.

**Comment by stephentoub** [comment] 2021-03-05 17:30
There are many developers submitting PRs to dotnet/runtime.  What is the expected action from them when this leg is red?

**Comment by steveisok** [comment] 2021-03-05 17:37
I expect us to call failures / problems out like we normally do.  The difference being that infrastructure & capacity issues should not prevent you from moving forward.

**Comment by stephentoub** [comment] 2021-03-05 17:40
So devs should ignore any failure that shows as the leg being canceled? This morning I re-ran this leg on around 5-7 PRs.  I can stop doing that, yes?

**Comment by ViktorHofer** [comment] 2021-03-05 17:44
Wouldn't it be better to just remove the runtime-staging status indicators from the PR view? The intent of this pipeline is to gather as much data as possible and that is available in the build pipeline UI on AzDO.

**Comment by steveisok** [comment] 2021-03-05 17:55
> Wouldn't it be better to just remove the runtime-staging status indicators from the PR view? The intent of this pipeline is to gather as much data as possible and that is available in the build pipeline UI on AzDO.

We still should try to treat these legs as normally as we possibly can.  The pass rate in the last 7 days for all our mobile legs has been > 90%.  The problem is that when they fail, they fail spectacularly.  If devs see builds being cancelled, I would  like us to track it and then it could be ignored.  

I expect our legs to improve once we add more capacity and have the ability to retry certain failing work items.  In the interim, we could solve the android cancellations by bumping the job timeout as the helix runs *are* finishing.  It's just taking them a long time.

**Comment by safern** [comment] 2021-03-05 18:30
> Wasn't the purpose of the staging leg to not fail the build and mark it as red?

It was design for test failures but we agreed that we should keep build failures failing the build to protect verticals for new platforms and not making it hard for the v-teams to keep those platforms building. 

Unfortunately there is not a way to tell azure devops, don't fail the build if there was a timeout, other than ignoring any failure.

**Comment by ViktorHofer** [comment] 2021-03-05 18:43
> Unfortunately there is not a way to tell azure devops, don't fail the build if there was a timeout, other than ignoring any failure.

Thanks for pointing that out. It wasn't clear to me that test hangs aren't treated the same as test failures.

> In the interim, we could solve the android cancellations by bumping the job timeout as the helix runs are finishing. It's just taking them a long time.

By bumping up the timeout, wouldn't we just create another problem as we would increase the average time it takes for a PR validation to finish? Tbh in most cases I don't wait for the staging pipeline finish in my PRs because they just take far too long. Increasing the timeout doesn't feel like an improvement to me.

Are the ways to minimize hardware consumption, i.e. disabling these legs on 6.0 preview branches (don't know if they run there) or not run them on every PR but only for rolling builds until there's more hardware available? How many PRs can we think of that recently regressed these legs?

**Comment by safern** [comment] 2021-03-05 18:52
> not run them on every PR but only for rolling builds until there's more hardware available? How many PRs can we think of that recently regressed these legs?

I think that is not a wild idea, maybe building these new platforms on PRs and running tests only on CI?

**Comment by marek-safar** [comment] 2021-03-05 19:00
> The latest update from MLS has our new hardware going in starting Monday.

This issue will be resolved on Monday, are you guys talking about a fix for one weekend?

**Comment by ViktorHofer** [comment] 2021-03-05 20:03
> The latest update from MLS has our new hardware going in starting Monday.

> This issue will be resolved on Monday, are you guys talking about a fix for one weekend?

If "going in starting Monday" means being available early next week then there's no follow-up action necessary from my perspective.

**Comment by stephentoub** [comment] 2021-03-11 11:52
> This issue will be resolved on Monday

Marek, the issue continues.

**Comment by steveisok** [comment] 2021-03-11 12:44
The update I got yesterday was that they were being installed.

**Comment by marek-safar** [comment] 2021-03-11 12:48
@ilyas1974 was there a delay in the machines bring up?

**Comment by ilyas1974** [comment] 2021-03-11 18:23
I'm working on a getting an answer to your question from MLS. I will update this thread once I have information to share

**Comment by stephentoub** [comment] 2021-03-19 00:18
This is still taking out most PRs.  It's been two weeks since I opened this issue.  What stop-gap can we put in place asap to stop the bleeding?

**Comment by stephentoub** [comment] 2021-03-19 00:19
![image](https://user-images.githubusercontent.com/2642209/111714053-30dfaf80-8827-11eb-9ef5-c3aebfeb0187.png)

**Comment by safern** [comment] 2021-03-19 00:35
I put up: https://github.com/dotnet/runtime/pull/49844 to run the tests on Android Arm64 only on rolling builds

**Comment by steveisok** [comment] 2021-03-19 01:07
> I put up: #49844 to run the tests on Android Arm64 only on rolling builds

At this point, I think that is fine for now.

**Comment by stephentoub** [comment] 2021-03-19 01:12
Thanks, @safern.

**Comment by ViktorHofer** [comment] 2021-03-23 09:37
Closing as the android arm64 leg was set to run on rolling builds only. Please reopen or create a new issue if this starts happening again.

**Closed by ViktorHofer** 2021-03-23 09:37 UTC
Labels: area-Infrastructure-mono, untriaged
