### ISSUE TITLE
Wasm.Build.Tests.Blazor tests could not find blazor's dotnetjs

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#87024] opened 2023-06-01 19:55 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=292552
Build error leg or test failing: Wasm.Build.Tests.Blazor.BuildPublishTests.BugRegression_60479_WithRazorClassLib
Pull request: https://github.com/dotnet/runtime/pull/86998

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step).

```json
{
  "ErrorMessage": "Could not find blazor's dotnet*js",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[292974](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292974)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.Blazor.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292974&view=ms.vss-test-web.build-test-results-tab&runId=5881142&resultId=100101)|dotnet/runtime#87026|
|[292787](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292787)|dotnet/runtime|[Workloads-Wasm.Build.Tests.Blazor.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292787&view=ms.vss-test-web.build-test-results-tab&runId=5877268&resultId=100101)|dotnet/runtime#86806|
|[292786](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292786)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.Blazor.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292786&view=ms.vss-test-web.build-test-results-tab&runId=5877256&resultId=100101)|dotnet/runtime#86806|
|[292710](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292710)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.Blazor.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292710&view=ms.vss-test-web.build-test-results-tab&runId=5875504&resultId=100101)|dotnet/runtime#86813|
|[292701](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292701)|dotnet/runtime|[Workloads-Wasm.Build.Tests.Blazor.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292701&view=ms.vss-test-web.build-test-results-tab&runId=5875294&resultId=100101)|dotnet/runtime#87019|
|[292587](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292587)|dotnet/runtime|[Workloads-Wasm.Build.Tests.Blazor.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292587&view=ms.vss-test-web.build-test-results-tab&runId=5870662&resultId=100101)|dotnet/runtime#86787|
|[292552](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292552)|dotnet/runtime|[Wasm.Build.Tests.Blazor.MiscTests.NativeBuild_WithDeployOnBuild_UsedByVS](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292552&view=ms.vss-test-web.build-test-results-tab&runId=5870146&resultId=100068)|dotnet/runtime#86998|
|[292478](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292478)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.Blazor.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292478&view=ms.vss-test-web.build-test-results-tab&runId=5866866&resultId=100101)|dotnet/runtime#86035|
|[290278](https://dev.azure.com/dnceng-public/public/_build/results?buildId=290278)|dotnet/runtime|[Wasm.Build.Tests.Blazor.MiscTests.NativeBuild_WithDeployOnBuild_UsedByVS](https://dev.azure.com/dnceng-public/public/_build/results?buildId=290278&view=ms.vss-test-web.build-test-results-tab&runId=5866248&resultId=100068)|dotnet/runtime#86920|
|[292460](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292460)|dotnet/runtime|[Wasm.Build.Tests.Blazor.MiscTests.NativeBuild_WithDeployOnBuild_UsedByVS](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292460&view=ms.vss-test-web.build-test-results-tab&runId=5866468&resultId=100067)|dotnet/runtime#87007|
|[292390](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292390)|dotnet/runtime|[Wasm.Build.Tests.Blazor.BuildPublishTests.DefaultTemplate_NoAOT_WithWorkload](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292390&view=ms.vss-test-web.build-test-results-tab&runId=5864358&resultId=100035)|dotnet/runtime#86759|
|[292358](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292358)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.Blazor.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292358&view=ms.vss-test-web.build-test-results-tab&runId=5864728&resultId=100053)|dotnet/runtime#86255|
|[292330](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292330)|dotnet/runtime|[Wasm.Build.Tests.Blazor.MiscTests.NativeBuild_WithDeployOnBuild_UsedByVS](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292330&view=ms.vss-test-web.build-test-results-tab&runId=5862182&resultId=100067)|dotnet/runtime#86501|
|[292295](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292295)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.Blazor.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292295&view=ms.vss-test-web.build-test-results-tab&runId=5861998&resultId=100101)|dotnet/runtime#87001|
|[292251](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292251)|dotnet/runtime|[Workloads-Wasm.Build.Tests.Blazor.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292251&view=ms.vss-test-web.build-test-results-tab&runId=5860288&resultId=100100)|dotnet/runtime#86652|
|[292245](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292245)|dotnet/runtime|[Workloads-Wasm.Build.Tests.Blazor.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292245&view=ms.vss-test-web.build-test-results-tab&runId=5860184&resultId=100101)|dotnet/runtime#87000|
|[292240](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292240)|dotnet/runtime|[Workloads-Wasm.Build.Tests.Blazor.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292240&view=ms.vss-test-web.build-test-results-tab&runId=5860092&resultId=100101)|dotnet/runtime#86698|
|[292191](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292191)|dotnet/runtime|[Workloads-Wasm.Build.Tests.Blazor.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292191&view=ms.vss-test-web.build-test-results-tab&runId=5857938&resultId=100101)|dotnet/runtime#86787|
|[292068](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292068)|dotnet/runtime|[Workloads-Wasm.Build.Tests.Blazor.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292068&view=ms.vss-test-web.build-test-results-tab&runId=5854460&resultId=100101)|dotnet/runtime#86470|
|[292063](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292063)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.Blazor.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292063&view=ms.vss-test-web.build-test-results-tab&runId=5854374&resultId=100101)|dotnet/runtime#86928|
|[292035](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292035)|dotnet/runtime|[Workloads-Wasm.Build.Tests.Blazor.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=292035&view=ms.vss-test-web.build-test-results-tab&runId=5853870&resultId=100101)||
|[291986](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291986)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.Blazor.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291986&view=ms.vss-test-web.build-test-results-tab&runId=5852346&resultId=100101)|dotnet/runtime#86813|
|[291972](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291972)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.Blazor.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291972&view=ms.vss-test-web.build-test-results-tab&runId=5852110&resultId=100101)|dotnet/runtime#84191|
|[291957](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291957)|dotnet/runtime|[Workloads-Wasm.Build.Tests.Blazor.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291957&view=ms.vss-test-web.build-test-results-tab&runId=5851268&resultId=100101)|dotnet/runtime#85558|
|[291794](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291794)|dotnet/runtime|[Workloads-Wasm.Build.Tests.Blazor.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291794&view=ms.vss-test-web.build-test-results-tab&runId=5847776&resultId=100101)|dotnet/runtime#86892|
|[291749](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291749)|dotnet/runtime|[Workloads-Wasm.Build.Tests.Blazor.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291749&view=ms.vss-test-web.build-test-results-tab&runId=5846326&resultId=100102)|dotnet/runtime#86048|
|[291689](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291689)|dotnet/runtime|[Wasm.Build.Tests.Blazor.MiscTests.NativeBuild_WithDeployOnBuild_UsedByVS](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291689&view=ms.vss-test-web.build-test-results-tab&runId=5844022&resultId=100068)|dotnet/runtime#86981|
|[291654](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291654)|dotnet/runtime|[Wasm.Build.Tests.Blazor.MiscTests.NativeBuild_WithDeployOnBuild_UsedByVS](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291654&view=ms.vss-test-web.build-test-results-tab&runId=5843242&resultId=100068)|dotnet/runtime#86928|
|[291625](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291625)|dotnet/runtime|[Wasm.Build.Tests.Blazor.MiscTests.NativeBuild_WithDeployOnBuild_UsedByVS](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291625&view=ms.vss-test-web.build-test-results-tab&runId=5842526&resultId=100067)|dotnet/runtime#86908|
|[291539](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291539)|dotnet/runtime|[Wasm.Build.Tests.Blazor.MiscTests.NativeBuild_WithDeployOnBuild_UsedByVS](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291539&view=ms.vss-test-web.build-test-results-tab&runId=5840512&resultId=100068)|dotnet/runtime#86972|
|[291538](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291538)|dotnet/runtime|[Wasm.Build.Tests.Blazor.MiscTests.NativeBuild_WithDeployOnBuild_UsedByVS](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291538&view=ms.vss-test-web.build-test-results-tab&runId=5840416&resultId=100067)||
|[291509](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291509)|dotnet/runtime|[Wasm.Build.Tests.Blazor.MiscTests.NativeBuild_WithDeployOnBuild_UsedByVS](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291509&view=ms.vss-test-web.build-test-results-tab&runId=5839756&resultId=100067)|dotnet/runtime#86722|
|[291503](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291503)|dotnet/runtime|[Wasm.Build.Tests.Blazor.MiscTests.DefaultTemplate_AOT_InProjectFile](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291503&view=ms.vss-test-web.build-test-results-tab&runId=5839528&resultId=100062)|dotnet/runtime#86970|
|[291466](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291466)|dotnet/runtime|[Workloads-Wasm.Build.Tests.Blazor.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291466&view=ms.vss-test-web.build-test-results-tab&runId=5839510&resultId=100102)|dotnet/runtime#86048|
|[291481](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291481)|dotnet/runtime|[Workloads-Wasm.Build.Tests.Blazor.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291481&view=ms.vss-test-web.build-test-results-tab&runId=5839484&resultId=100101)|dotnet/runtime#86968|
|[291438](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291438)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.Blazor.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291438&view=ms.vss-test-web.build-test-results-tab&runId=5838610&resultId=100090)|dotnet/runtime#86813|
|[291360](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291360)|dotnet/runtime|[Workloads-NoWebcil-Wasm.Build.Tests.Blazor.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=291360&view=ms.vss-test-web.build-test-results-tab&runId=5837710&resultId=100101)|dotnet/runtime#86963|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|33|37|37|

**Comment by radical** [comment] 2023-06-01 22:52
Dupe of https://github.com/dotnet/runtime/issues/86959 . I fixed the error pattern there to catch the missing cases.

**Closed** 2023-06-01 22:52 UTC
Labels: arch-wasm, blocking-clean-ci, area-Build-mono, Known Build Error
