### ISSUE TITLE
createdump is added to Mac app bundles

### ISSUE THREAD

**Issue by praeclarum** [dotnet/runtime#83613] opened 2023-03-17 20:01 UTC
### Description

An extra binary is output when building net7.0-macos builds. This makes publishing to the store difficult because that binary has to also be signed.

That file should not be output when creating .apps.

During build the code sign tool gets confused:

> /Users/runner/.dotnet/packs/Microsoft.macOS.Sdk/13.1.1040/tools/msbuild/macOS/Xamarin.Shared.targets(2113,3): warning : Code signing has been requested multiple times for 'bin/Release/net7.0-macos/publish/../Calca.app/Contents/MonoBundle/createdump', with different metadata. The metadata 'CodesignEntitlements' has different values for each item (once it's 'obj/Release/net7.0-macos/osx-x64/Entitlements.xcent', another time it's 'obj/Release/net7.0-macos/osx-arm64/Entitlements.xcent'). [/Users/runner/work/Calca/Calca/Calca.Mac/Calca.csproj]

### Reproduction Steps

Try to publish a macOS app for the App Store:

```bash
dotnet build -c Release /p:ArchiveOnBuild=true /p:CreatePackage=true /p:EnablePackageSigning=true /p:EnableCodeSigning=true "/p:CodeSigningKey=Apple Distribution" "/p:CodeSignProvision=Calca for Mac Production" "/p:PackageSigningKey=3rd Party Mac Developer Installer" Calca.Mac/Calca.csproj
```

Project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0-macos</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>
    <SupportedOSPlatformVersion>10.14</SupportedOSPlatformVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <CreatePackage>false</CreatePackage>
    <UseSGen>false</UseSGen>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <CreatePackage>false</CreatePackage>
    <UseSGen>false</UseSGen>
  </PropertyGroup>
</Project>
```

### Expected behavior

I expect a single executable for the app to be in the .app bundle.

### Actual behavior

Some extra createdump is also added to the .app.

That binary then shows up when trying to publish your app: 
<img width="982" alt="Screenshot 2023-03-17 at 1 00 43 PM" src="https://user-images.githubusercontent.com/323548/226019747-a7d2b8e9-4f9a-44d5-8ad3-5e16197b160a.png">

### Regression?

Regression from Xamarin.iOS

### Known Workarounds

None

### Configuration

SDK 7.0.101

Running on macOS 13.1 x64

**Comment by filipnavara** [comment] 2023-03-18 08:20
I consider `createdump` to be essential for diagnostics and we ship it in our macOS bundles. Signing the whole bundle with codesign, or using the built-in Xamarin signing does sign it.

**Comment by tommcdon** [comment] 2023-03-21 00:27
@hoyosjs @agocke

**Comment by hoyosjs** [comment] 2023-03-29 06:34
@praeclarum this is by design of the runtime. So far none of our customers has complained about this being an issue. It might be interesting to follow up with the Xamarin folks on the warning. Creatdump needs to have the following entitlements: https://github.com/dotnet/runtime/blob/main/eng/pipelines/common/createdump-entitlements.plist

**Comment by tommcdon** [comment] 2023-04-28 20:28
Closing as it seems to be a non-runtime issue

**Closed by tommcdon** 2023-04-28 20:28 UTC
Labels: area-Diagnostics-coreclr
