### ISSUE TITLE
[mono] Attempting to JIT compile method (wrapper dynamic-method) void object:WriteArrayOfintToXml

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#110148] opened 2024-11-25 12:11 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=876794&view=logs&j=07effcfd-c63d-5008-e811-03b29530f5cb&t=506b47fe-4551-54d6-41af-334dd2c09566
Build error leg or test failing: iOS.Simulator.XmlFormatWriterGeneratorAot.Test

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "Attempting to JIT compile method '(wrapper dynamic-method) void object:WriteArrayOfintToXml",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

Error log:
```
[11:20:09] dbug: Attempting to JIT compile method '(wrapper dynamic-method) void object:WriteArrayOfintToXml (System.Runtime.Serialization.XmlWriterDelegator,object,System.Runtime.Serialization.XmlObjectSerializerWriteContext,System.Runtime.Serialization.DataContracts.CollectionDataContract)' while running in aot-only mode. See https://learn.microsoft.com/xamarin/ios/internals/limitations for more information.
[11:20:09] dbug: (System.ExecutionEngineException)
[11:20:09] dbug: at System.Delegate.CreateDelegate(Type , Object , MethodInfo , Boolean , Boolean )
[11:20:09] dbug: at System.Delegate.CreateDelegate(Type , Object , MethodInfo , Boolean )
[11:20:09] dbug: at System.Delegate.CreateDelegate(Type , Object , MethodInfo )
[11:20:09] dbug: at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type )
[11:20:09] dbug: at System.Runtime.Serialization.CodeGenerator.EndMethod()
[11:20:09] dbug: at System.Runtime.Serialization.XmlFormatWriterGenerator.CriticalHelper.GenerateCollectionWriter(CollectionDataContract )
[11:20:09] dbug: at System.Runtime.Serialization.XmlFormatWriterGenerator.GenerateCollectionWriter(CollectionDataContract )
[11:20:09] dbug: at System.Runtime.Serialization.DataContracts.CollectionDataContract.CreateXmlFormatWriterDelegate()
[11:20:09] dbug: at System.Runtime.Serialization.DataContracts.CollectionDataContract.get_XmlFormatWriterDelegate()
[11:20:09] dbug: at System.Runtime.Serialization.DataContracts.CollectionDataContract.WriteXmlValue(XmlWriterDelegator , Object , XmlObjectSerializerWriteContext )
[11:20:09] dbug: at System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteDataContractValue(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle declaredTypeHandle)
[11:20:09] dbug: at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeAndVerifyType(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, Boolean verifyKnownType, RuntimeTypeHandle declaredTypeHandle, Type declaredType)
[11:20:09] dbug: at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithXsiTypeAtTopLevel(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle originalDeclaredTypeHandle, Type graphType)
[11:20:09] dbug: at System.Runtime.Serialization.DataContractSerializer.InternalWriteObjectContent(XmlWriterDelegator , Object , DataContractResolver )
[11:20:09] dbug: at System.Runtime.Serialization.DataContractSerializer.InternalWriteObject(XmlWriterDelegator , Object , DataContractResolver )
[11:20:09] dbug: at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator , Object , DataContractResolver )
[11:20:09] dbug: at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator , Object )
[11:20:09] dbug: at System.Runtime.Serialization.DataContractSerializer.WriteObject(XmlWriter , Object )
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=876794
**Error message validated:** `[Attempting to JIT compile method '(wrapper dynamic-method) void object:WriteArrayOfintToXml`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 11/25/2024 12:12:48 PM UTC

**Comment by ivanpovazan** [comment] 2024-11-25 12:48
This seems a duplicate of: https://github.com/dotnet/runtime/issues/104431

**Closed** 2024-11-25 12:59 UTC
Labels: area-VM-meta-mono, os-ios, Known Build Error
