### ISSUE TITLE
[Perf] Regressions in System.Linq.Tests.Perf_Enumerable

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#50006] opened 2021-03-22 17:12 UTC
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [3553284bea7b650874c8dcc3f78d6be085a047bb](https://github.com/dotnet/runtime/commit/3553284bea7b650874c8dcc3f78d6be085a047bb)
Compare | [59594697a94b5add2d91f292283141574e4d0f16](https://github.com/dotnet/runtime/commit/59594697a94b5add2d91f292283141574e4d0f16)

### Regressions in System.Linq.Tests.Perf_Enumerable

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[TakeLastHalf](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04/System.Linq.Tests.Perf_Enumerable.TakeLastHalf(input%3a%20IEnumerable).html>) | 1.23 μs | 1.34 μs | 1.09 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_10_2021/refs/heads/main_x64_ubuntu%2018.04_Regression/System.Linq.Tests.Perf_Enumerable_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_10_2021/refs/heads/main_x64_ubuntu%2018.04_Regression/System.Linq.Tests.Perf_Enumerable.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Linq.Tests.Perf_Enumerable*'
```
<details>

.
### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-171747ca-2682-464d-8a6d-575260e181a7d2c844da15642879d/841dbbb2-94d7-4da2-88cc-f16e206e9c76.zip?sv=2019-07-07&se=2021-03-31T10%3A28%3A05Z&sr=c&sp=rl&sig=liE74NSXKetA5jn3h6KtmCxv4%2B2wZHRl43Gkjt%2BJ54w%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-938fbe71-5d6f-4d1b-ad35-7918c638692a8f11ea9d62d415884/66c8b62d-71f6-4d8c-ae42-b19a64cb6a0a.zip?sv=2019-07-07&se=2021-03-31T21%3A58%3A26Z&sr=c&sp=rl&sig=9IzGoqnoVFO9MZAX8RYTIw%2F4VazdYXRwUO6Rr5uSiVg%3D>)

#### System.Linq.Tests.Perf_Enumerable.TakeLastHalf(input: IEnumerable)

```log
[1222.875 ; 1258.448) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[1258.448 ; 1302.591) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[1302.591 ; 1341.917) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[1341.917 ; 1388.505) | @@@@@@@@@@@@@@@@@@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by DrewScoggins** [comment] 2021-03-22 17:12
https://github.com/dotnet/runtime/pull/48634 looks like the culprit

**Comment by eiriktsarpalis** [comment] 2021-03-23 11:22
This is expected, `TakeLast` is now doing slightly more work because it is being defined in terms of the `Take(Range)` method which optimizes for `ICollection` inputs. This can be seen if we compare with other inputs of the same benchmark:

# e52568de3dd2c91f0bd5a1f0e519b10980bc3313

|       Method |       input |     Mean |     Error |    StdDev |   Median |      Min |      Max |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------- |------------ |---------:|----------:|----------:|---------:|---------:|---------:|-------:|------:|------:|----------:|
| TakeLastHalf | IEnumerable | 1.360 us | 0.0566 us | 0.0651 us | 1.314 us | 1.301 us | 1.456 us | 0.0733 |     - |     - |     752 B |
| TakeLastHalf |        List | 1.669 us | 0.1329 us | 0.1530 us | 1.658 us | 1.505 us | 1.992 us | 0.0743 |     - |     - |     760 B |

# f7308f03ed03a94c5445789daadcf56b9c63dab8

|       Method |       input |       Mean |    Error |   StdDev |     Median |        Min |        Max |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------- |------------ |-----------:|---------:|---------:|-----------:|-----------:|-----------:|-------:|------:|------:|----------:|
| TakeLastHalf | IEnumerable | 1,424.4 ns | 23.57 ns | 19.68 ns | 1,419.6 ns | 1,406.8 ns | 1,465.5 ns | 0.0741 |     - |     - |     776 B |
| TakeLastHalf |        List |   693.1 ns | 21.78 ns | 25.08 ns |   681.0 ns |   669.6 ns |   742.8 ns | 0.0109 |     - |     - |     136 B |

**Comment by adamsitnik** [comment] 2021-04-08 09:08
Compared to 5.0 there is still a regression: https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_Windows%2010.0.18362%2fSystem.Linq.Tests.Perf_Enumerable.TakeLastHalf(input%3a%20List).html

![obraz](https://user-images.githubusercontent.com/6011991/113999721-95a48d80-985a-11eb-853d-07132cc9fe6b.png)

I am reopening, @eiriktsarpalis PTAL

**Comment by eiriktsarpalis** [comment] 2021-04-08 10:29
Yes, this is in line with the trade-offs in that particular change. Notice in https://github.com/dotnet/runtime/issues/50006#issuecomment-804823487 that for `IEnumerable` inputs performance regresses slightly, however for `IList` inputs it improves significantly, both in time and memory consumption.

I would recommend closing this as by-design.

**Comment by eiriktsarpalis** [comment] 2021-04-08 10:30
I just realized you referred to `List` inputs. I'll take a look.

**Comment by adamsitnik** [comment] 2021-04-08 10:34
@eiriktsarpalis sorry I forgot to provide the repro:

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f net5.0 net6.0 --filter 'System.Linq.Tests.Perf_Enumerable.TakeLastHalf'
```

**Comment by eiriktsarpalis** [comment] 2021-04-08 10:51
Looking at the graph, the initial regression in September definitely correlates with this change: https://github.com/dotnet/runtime/pull/42506. 

This was reverting an optimization since it was behaving incorrectly in the context of source mutations. The more recent changes improve performance (as expected), but it is unlikely we can recover the performance of the (incorrect) .NET 5 implementation.

Again, this regression is to be expected, closing the issue.

cc @stephentoub

**Closed by eiriktsarpalis** 2021-04-08 10:51 UTC
Labels: arch-x64, area-System.Linq, os-linux, tenet-performance, tenet-performance-benchmarks, untriaged
