### ISSUE TITLE
(Bounded)Channel Leaks memory on streams with few writes and many cancelled reads.

### ISSUE THREAD

**Issue by to11mtm** [dotnet/runtime#80057] opened 2022-12-30 00:24 UTC
### Description

When the cancellatonToken for `ChannelReader<T>.WaitToReadAsync(CancellationToken cancellationToken)` is cancelled, the underlying `AsyncOperation` is not removed until another write occurs.

### Configuration

OS: Win10/Linux (IDK distro/etc but not relevant AFAIK)
Net Versions: 6

### Regression?

I don't think this is a regression

### Data

Please see Repro below

### Analysis

I think the problem is related to how pending `AsyncOperation`s are stored in a channel. From looking at the code, the Tail is kept as a linked list-esque structure with the previous operation stored in `.Next`. 

However, when a Task is cancelled, it is not cleaned up until the next write. This causes a problem for very 'long lived' channels in certain use cases.

[This Linqpad Repro](https://gist.github.com/to11mtm/3c6aa8bbb9a77e51ec0f8df3206fce48) when run and with variables observed according to comments around debugger breakpoints (may need to manually add breakpoints,) should show the the behavior in question.

I have not tried this yet with an UnboundedChannel.

### Comments:

This use case borderlines on the esoteric, however I felt it was worth at least asking about. The use case in question would be if one wanted to periodically poll, while tracking the length of time before a response actually was received.

### Workarounds:

If your usage permits it, you may wrap the Channel in a wrapper class, holding onto the wait and using `Task<T>.WaitAsync(CancellationToken token)` around the wrapper-held wait to avoid the leak.

**Comment by theodorzoulias** [comment] 2022-12-30 06:44
This seems like a duplicate of the #761.

**Closed** 2022-12-30 13:21 UTC
Labels: area-System.Threading.Channels, tenet-performance, untriaged
