### ISSUE TITLE
Make it possible to disable the built-in HTTP client logging

### ISSUE THREAD

**Issue by evgenyfedorov2** [dotnet/runtime#81540] opened 2023-02-02 15:14 UTC
The AddHttpClient() extension [method](https://github.com/dotnet/runtime/blob/215b39abf947da7a40b0cb137eab4bceb24ad3e3/src/libraries/Microsoft.Extensions.Http/src/DependencyInjection/HttpClientFactoryServiceCollectionExtensions.cs#L23) in .NET runtime automatically [adds ](https://github.com/dotnet/runtime/blob/215b39abf947da7a40b0cb137eab4bceb24ad3e3/src/libraries/Microsoft.Extensions.Http/src/DependencyInjection/HttpClientFactoryServiceCollectionExtensions.cs#L47 )the [LoggingHttpMessageHandlerBuilderFilter](https://github.com/dotnet/runtime/blob/215b39abf947da7a40b0cb137eab4bceb24ad3e3/src/libraries/Microsoft.Extensions.Http/src/Logging/LoggingHttpMessageHandlerBuilderFilter.cs) which then logs all the outgoing HTTP requests. This is added automatically and it ends up logging request URLs in requests and as scopes which can contain sensitive data.

Currently there is no reliable mechanism provided in .NET today to disable this functionality. The only ability that a developer has is to set the LogLevel to a higher value so they aren't logged. Even that's not a complete solution because scopes still contain URL and other information which ends up logging the sensitive information. Let alone something like `IServiceCollection.RemoveAll<IHttpMessageHandlerBuilderFilter>()` which removes all filters but they will get added again if you call AddHttpClient() later.

There needs to be control for users to disable the automatic logging of these requests. There is also additional performance cost for processing and logging these requests which can be avoided if users don't want this functionality.

**Comment by CarnaViire** [comment] 2023-02-02 19:53
Duplicate of #77312

**Closed** 2023-02-02 19:53 UTC
Labels: untriaged, area-Extensions-HttpClientFactory
