### ISSUE TITLE
Test failure DllImportGenerator.UnitTests.ConvertToGeneratedDllImportAnalyzerTests.TypeRequiresMarshalling_ReportsDiagnostic(type: typeof(System.ConsoleKeyInfo))

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#60950] opened 2021-10-28 01:14 UTC
Run: [runtime 20211027.2
](https://dev.azure.com/dnceng/public/_build/results?buildId=1442365&view=ms.vss-test-web.build-test-results-tab&runId=41595644&resultId=103049&paneView=debug)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_release-Windows.10.Arm64.Open
DllImportGenerator.UnitTests.ConvertToGeneratedDllImportAnalyzerTests.TypeRequiresMarshalling_ReportsDiagnostic(type: typeof(System.ConsoleKeyInfo))
```
**Error message:**
```
Microsoft.CodeAnalysis.Testing.Verifiers.EqualWithMessageException : Context: Diagnostics of test state
Mismatch between number of diagnostics returned, expected "2" actual "1"

Diagnostics:
// error AD0001: Analyzer 'Microsoft.Interop.Analyzers.ConvertToGeneratedDllImportAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
Exception occurred with following context:
Compilation: TestProject

System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.CodeAnalysis.MetadataHelpers.GetInfoForImmediateNamespaceMembers(Boolean isGlobalNamespace, Int32 namespaceNameLength, IEnumerable1 typesByNS, StringComparer nameComparer, IEnumerable1& types, IEnumerable1& namespaces) at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamespaceSymbol.LoadAllMembers(IEnumerable1 typesByNS)
at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENestedNamespaceSymbol.EnsureAllMembersLoaded()
at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamespaceSymbol.GetMembers(String name)
at Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceSymbol.LookupNestedNamespace(ImmutableArray1 names) at Microsoft.CodeAnalysis.CSharp.Symbols.NonMissingModuleSymbol.LookupTopLevelMetadataType(MetadataTypeName& emittedName) at Microsoft.CodeAnalysis.CSharp.Symbols.NonMissingAssemblySymbol.LookupTopLevelMetadataTypeWithCycleDetection(MetadataTypeName& emittedName, ConsList1 visitedAssemblies, Boolean digThroughForwardedTypes)
at Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol.LookupTopLevelMetadataType(MetadataTypeName& emittedName, Boolean digThroughForwardedTypes)
at Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol.GetTopLevelTypeByMetadataName(AssemblySymbol assembly, MetadataTypeName& metadataName, AssemblyIdentity assemblyOpt)
at Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol.GetTopLevelTypeByMetadataName(MetadataTypeName& metadataName, AssemblyIdentity assemblyOpt, Boolean includeReferences, Boolean isWellKnownType, ValueTuple2& conflicts, DiagnosticBag warnings, Boolean ignoreCorLibraryDuplicatedTypes) at Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol.GetTypeByMetadataName(String metadataName, Boolean includeReferences, Boolean isWellKnownType, ValueTuple2& conflicts, Boolean useCLSCompliantNameArityEncoding, DiagnosticBag warnings, Boolean ignoreCorLibraryDuplicatedTypes)
at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetTypeByMetadataName(String fullyQualifiedMetadataName)
at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonGetTypeByMetadataName(String metadataName)
at Microsoft.Interop.Analyzers.ConvertToGeneratedDllImportAnalyzer.<>c.<Initialize>b__5_0(CompilationStartAnalysisContext compilationContext) in /_/src/libraries/System.Runtime.InteropServices/gen/DllImportGenerator/Analyzers/ConvertToGeneratedDllImportAnalyzer.cs:line 0
at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteCompilationStartActions>b__44_0(ValueTuple2 data) at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action1 analyze, TArg argument, Nullable`1 info)
Suppress the following diagnostics to disable this analyzer: DLLIMPORTGENANALYZER015
DiagnosticResult.CompilerError("AD0001").WithArguments("Microsoft.Interop.Analyzers.ConvertToGeneratedDllImportAnalyzer", "System.NullReferenceException", "Object reference not set to an instance of an object.", "Exception occurred with following context:
Compilation: TestProject

System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.CodeAnalysis.MetadataHelpers.GetInfoForImmediateNamespaceMembers(Boolean isGlobalNamespace, Int32 namespaceNameLength, IEnumerable1 typesByNS, StringComparer nameComparer, IEnumerable1& types, IEnumerable1& namespaces) at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamespaceSymbol.LoadAllMembers(IEnumerable1 typesByNS)
at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENestedNamespaceSymbol.EnsureAllMembersLoaded()
at Microsoft.CodeAnalysis.CSharp.Symbols.Metadata.PE.PENamespaceSymbol.GetMembers(String name)
at Microsoft.CodeAnalysis.CSharp.Symbols.NamespaceSymbol.LookupNestedNamespace(ImmutableArray1 names) at Microsoft.CodeAnalysis.CSharp.Symbols.NonMissingModuleSymbol.LookupTopLevelMetadataType(MetadataTypeName& emittedName) at Microsoft.CodeAnalysis.CSharp.Symbols.NonMissingAssemblySymbol.LookupTopLevelMetadataTypeWithCycleDetection(MetadataTypeName& emittedName, ConsList1 visitedAssemblies, Boolean digThroughForwardedTypes)
at Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol.LookupTopLevelMetadataType(MetadataTypeName& emittedName, Boolean digThroughForwardedTypes)
at Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol.GetTopLevelTypeByMetadataName(AssemblySymbol assembly, MetadataTypeName& metadataName, AssemblyIdentity assemblyOpt)
at Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol.GetTopLevelTypeByMetadataName(MetadataTypeName& metadataName, AssemblyIdentity assemblyOpt, Boolean includeReferences, Boolean isWellKnownType, ValueTuple2& conflicts, DiagnosticBag warnings, Boolean ignoreCorLibraryDuplicatedTypes) at Microsoft.CodeAnalysis.CSharp.Symbols.AssemblySymbol.GetTypeByMetadataName(String metadataName, Boolean includeReferences, Boolean isWellKnownType, ValueTuple2& conflicts, Boolean useCLSCompliantNameArityEncoding, DiagnosticBag warnings, Boolean ignoreCorLibraryDuplicatedTypes)
at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetTypeByMetadataName(String fullyQualifiedMetadataName)
at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonGetTypeByMetadataName(String metadataName)
at Microsoft.Interop.Analyzers.ConvertToGeneratedDllImportAnalyzer.<>c.<Initialize>b__5_0(CompilationStartAnalysisContext compilationContext) in /_/src/libraries/System.Runtime.InteropServices/gen/DllImportGenerator/Analyzers/ConvertToGeneratedDllImportAnalyzer.cs:line 0
at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteCompilationStartActions>b__44_0(ValueTuple2 data) at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action1 analyze, TArg argument, Nullable`1 info)
Suppress the following diagnostics to disable this analyzer: DLLIMPORTGENANALYZER015"),

Assert.Equal() Failure
Expected: 2
Actual:   1


Stack trace
   at Microsoft.CodeAnalysis.Testing.Verifiers.XUnitVerifier.Equal[T](T expected, T actual, String message) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Testing.Verifiers.XUnit/XUnitVerifier.cs:line 49
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.VerifyDiagnosticResults(IEnumerable`1 actualResults, ImmutableArray`1 analyzers, DiagnosticResult[] expectedResults, IVerifier verifier) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 359
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.VerifyDiagnosticsAsync(EvaluatedProjectState primaryProject, ImmutableArray`1 additionalProjects, DiagnosticResult[] expected, IVerifier verifier, CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 272
   at Microsoft.CodeAnalysis.Testing.CodeFixTest`1.RunImplAsync(CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.CodeFix.Testing/CodeFixTest`1.cs:line 264
   at DllImportGenerator.UnitTests.Verifiers.CSharpCodeFixVerifier`2.Test.RunImplAsync(CancellationToken cancellationToken) in /_/src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/Verifiers/CSharpCodeFixVerifier.cs:line 124
   at Microsoft.CodeAnalysis.Testing.AnalyzerTest`1.RunAsync(CancellationToken cancellationToken) in /_/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/AnalyzerTest`1.cs:line 180
   at DllImportGenerator.UnitTests.Verifiers.CSharpAnalyzerVerifier`1.VerifyAnalyzerAsync(String source, DiagnosticResult[] expected) in /_/src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/Verifiers/CSharpAnalyzerVerifier.cs:line 37
   at DllImportGenerator.UnitTests.ConvertToGeneratedDllImportAnalyzerTests.TypeRequiresMarshalling_ReportsDiagnostic(Type type) in /_/src/libraries/System.Runtime.InteropServices/tests/DllImportGenerator.UnitTests/ConvertToGeneratedDllImportAnalyzerTests.cs:line 53
--- End of stack trace from previous location ---
```

**Comment by AaronRobinsonMSFT** [comment] 2021-11-02 00:25
Duplicate of https://github.com/dotnet/runtime/issues/60909

**Closed by AaronRobinsonMSFT** 2021-11-02 00:25 UTC
Labels: arch-arm64, os-windows, area-Interop-coreclr, untriaged
