### ISSUE TITLE
Test failure System.Net.Mail.Tests.SmtpClientTest.TestGssapiAuthentication

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#85753] opened 2023-05-04 08:35 UTC
**Failed in:** [runtime-coreclr libraries-jitstress 20230503.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260461&view=ms.vss-test-web.build-test-results-tab&runId=5100514&resultId=169068&paneView=debug)

**Failed tests:**
```
net8.0-windows-Release-x86-CoreCLR_checked-jitstress1-Windows.10.Amd64.Open
    - System.Net.Mail.Tests.SmtpClientTest.TestGssapiAuthentication
    - System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery
net8.0-windows-Release-x86-CoreCLR_checked-tailcallstress-Windows.10.Amd64.Open
    - System.Net.Mail.Tests.SmtpClientTest.TestGssapiAuthentication
    - System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery
net8.0-windows-Release-x86-CoreCLR_checked-no_tiered_compilation-Windows.10.Amd64.Open
    - System.Net.Mail.Tests.SmtpClientTest.TestGssapiAuthentication
    - System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery
net8.0-windows-Release-x64-CoreCLR_checked-tailcallstress-Windows.10.Amd64.Open
    - System.Net.Mail.Tests.SmtpClientTest.TestGssapiAuthentication
    - System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery
net8.0-windows-Release-x86-CoreCLR_checked-zapdisable-Windows.10.Amd64.Open
    - System.Net.Mail.Tests.SmtpClientTest.TestGssapiAuthentication
    - System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery
net8.0-windows-Release-x64-CoreCLR_checked-zapdisable-Windows.10.Amd64.Open
    - System.Net.Mail.Tests.SmtpClientTest.TestGssapiAuthentication
    - System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery
net8.0-windows-Release-x64-CoreCLR_checked-no_tiered_compilation-Windows.10.Amd64.Open
    - System.Net.Mail.Tests.SmtpClientTest.TestGssapiAuthentication
    - System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery
net8.0-windows-Release-x64-CoreCLR_checked-jitstress1-Windows.10.Amd64.Open
    - System.Net.Mail.Tests.SmtpClientTest.TestGssapiAuthentication
    - System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery
net8.0-linux-Release-x64-CoreCLR_checked-jitstress1-Ubuntu.1804.Amd64.Open
    - System.Net.Mail.Tests.SmtpClientTest.TestGssapiAuthentication
    - System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery
```

**Error message:**
```
 System.InvalidOperationException : Data stream is still open.
```

**Stack trace:**
```
    at System.Net.Mail.SmtpConnection.ShutdownConnection(Boolean isAbort) in /_/src/libraries/System.Net.Mail/src/System/Net/Mail/SmtpConnection.cs:line 147
   at System.Net.Mail.SmtpConnection.ReleaseConnection() in /_/src/libraries/System.Net.Mail/src/System/Net/Mail/SmtpConnection.cs:line 177
   at System.Net.Mail.SmtpTransport.ReleaseConnection() in /_/src/libraries/System.Net.Mail/src/System/Net/Mail/SmtpTransport.cs:line 165
   at System.Net.Mail.SmtpClient.Dispose(Boolean disposing) in /_/src/libraries/System.Net.Mail/src/System/Net/Mail/SmtpClient.cs:line 1015
   at System.Net.Mail.SmtpClient.Dispose() in /_/src/libraries/System.Net.Mail/src/System/Net/Mail/SmtpClient.cs:line 1000
   at System.Net.Mail.Tests.SmtpClientTest.TestGssapiAuthentication() in /_/src/libraries/System.Net.Mail/tests/Functional/SmtpClientTest.cs:line 578
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
```

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2023-05-03T07:34:51.35Z | runtime-coreclr libraries-jitstress | Release | ubuntu.1804.amd64.open.rt | x64 | System.Net.Mail.Tests.SmtpClientTest.TestGssapiAuthentication | Failed | {"AzurePipelinesTestRunId":"5100440","DefinitionId":"138","System.JobName":"__default","BuildNumber":"20230503.1","System.JobAttempt":"1","DefinitionName":"runtime-coreclr libraries-jitstress","System.PhaseAttempt":"1","System.StageAttempt":"1","configuration":"Release","scenario":"jitstress1","operatingSystem":"Ubuntu.1804.Amd64.Open","BuildId":"260461","System.PhaseName":"libraries_test_run_checked_coreclr_linux_x64_Release","architecture":"x64","Reason":"Schedule","Project":"public","runtimeFlavor":"coreclr","System.StageName":"Build","System.JobId":"fe27627b-bd13-56b8-97c3-9bb28451d0b9","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2023-05-03T07:34:51.35Z | runtime-coreclr libraries-jitstress | Release | ubuntu.1804.amd64.open.rt | x64 | System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery | Failed | {"AzurePipelinesTestRunId":"5100440","DefinitionId":"138","System.JobName":"__default","BuildNumber":"20230503.1","System.JobAttempt":"1","DefinitionName":"runtime-coreclr libraries-jitstress","System.PhaseAttempt":"1","System.StageAttempt":"1","configuration":"Release","scenario":"jitstress1","operatingSystem":"Ubuntu.1804.Amd64.Open","BuildId":"260461","System.PhaseName":"libraries_test_run_checked_coreclr_linux_x64_Release","architecture":"x64","Reason":"Schedule","Project":"public","runtimeFlavor":"coreclr","System.StageName":"Build","System.JobId":"fe27627b-bd13-56b8-97c3-9bb28451d0b9","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
<details>
<summary>More failures</summary>

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T09:49:52.647Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery | Failed | {"BuildId":"252922","DefinitionId":"154","operatingSystem":"OSX.13.Amd64.AppleTV.Open","architecture":"arm64","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","BuildNumber":"20230426.1","System.PhaseAttempt":"1","DefinitionName":"runtime-extra-platforms","AzurePipelinesTestRunId":"4911256","Reason":"Schedule","System.StageName":"Build","System.JobAttempt":"1","System.JobName":"__default","configuration":"Release","runtimeFlavor":"mono","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","Project":"public"} | Schedule
2023-04-26T09:49:52.647Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery | Failed | {"BuildId":"252922","DefinitionId":"154","operatingSystem":"OSX.13.Amd64.AppleTV.Open","architecture":"arm64","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","BuildNumber":"20230426.1","System.PhaseAttempt":"1","DefinitionName":"runtime-extra-platforms","AzurePipelinesTestRunId":"4911256","Reason":"Schedule","System.StageName":"Build","System.JobAttempt":"1","System.JobName":"__default","configuration":"Release","runtimeFlavor":"mono","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","Project":"public"} | Schedule
2023-04-26T09:49:52.647Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery | Failed | {"BuildId":"252922","DefinitionId":"154","operatingSystem":"OSX.13.Amd64.AppleTV.Open","architecture":"arm64","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","BuildNumber":"20230426.1","System.PhaseAttempt":"1","DefinitionName":"runtime-extra-platforms","AzurePipelinesTestRunId":"4911256","Reason":"Schedule","System.StageName":"Build","System.JobAttempt":"1","System.JobName":"__default","configuration":"Release","runtimeFlavor":"mono","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","Project":"public"} | Schedule
2023-04-26T09:49:52.647Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery | Failed | {"BuildId":"252922","DefinitionId":"154","operatingSystem":"OSX.13.Amd64.AppleTV.Open","architecture":"arm64","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","BuildNumber":"20230426.1","System.PhaseAttempt":"1","DefinitionName":"runtime-extra-platforms","AzurePipelinesTestRunId":"4911256","Reason":"Schedule","System.StageName":"Build","System.JobAttempt":"1","System.JobName":"__default","configuration":"Release","runtimeFlavor":"mono","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","Project":"public"} | Schedule
2023-04-25T22:37:03.213Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery | Failed | {"System.PhaseAttempt":"1","System.JobAttempt":"1","architecture":"arm64","AzurePipelinesTestRunId":"4897396","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","BuildId":"252256","System.StageAttempt":"1","System.JobName":"__default","Reason":"Schedule","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","Project":"public","runtimeFlavor":"mono","System.StageName":"Build","BuildNumber":"20230425.3","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.13.Amd64.AppleTV.Open","configuration":"Release","DefinitionId":"154","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2023-04-25T22:37:03.213Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery | Failed | {"System.PhaseAttempt":"1","System.JobAttempt":"1","architecture":"arm64","AzurePipelinesTestRunId":"4897396","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","BuildId":"252256","System.StageAttempt":"1","System.JobName":"__default","Reason":"Schedule","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","Project":"public","runtimeFlavor":"mono","System.StageName":"Build","BuildNumber":"20230425.3","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.13.Amd64.AppleTV.Open","configuration":"Release","DefinitionId":"154","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2023-04-25T22:37:03.213Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery | Failed | {"System.PhaseAttempt":"1","System.JobAttempt":"1","architecture":"arm64","AzurePipelinesTestRunId":"4897396","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","BuildId":"252256","System.StageAttempt":"1","System.JobName":"__default","Reason":"Schedule","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","Project":"public","runtimeFlavor":"mono","System.StageName":"Build","BuildNumber":"20230425.3","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.13.Amd64.AppleTV.Open","configuration":"Release","DefinitionId":"154","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2023-04-25T22:37:03.213Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery | Failed | {"System.PhaseAttempt":"1","System.JobAttempt":"1","architecture":"arm64","AzurePipelinesTestRunId":"4897396","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","BuildId":"252256","System.StageAttempt":"1","System.JobName":"__default","Reason":"Schedule","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","Project":"public","runtimeFlavor":"mono","System.StageName":"Build","BuildNumber":"20230425.3","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.13.Amd64.AppleTV.Open","configuration":"Release","DefinitionId":"154","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2023-04-25T22:37:03.213Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery | Failed | {"System.PhaseAttempt":"1","System.JobAttempt":"1","architecture":"arm64","AzurePipelinesTestRunId":"4897396","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","BuildId":"252256","System.StageAttempt":"1","System.JobName":"__default","Reason":"Schedule","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","Project":"public","runtimeFlavor":"mono","System.StageName":"Build","BuildNumber":"20230425.3","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.13.Amd64.AppleTV.Open","configuration":"Release","DefinitionId":"154","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2023-04-25T22:37:03.213Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery | Failed | {"System.PhaseAttempt":"1","System.JobAttempt":"1","architecture":"arm64","AzurePipelinesTestRunId":"4897396","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","BuildId":"252256","System.StageAttempt":"1","System.JobName":"__default","Reason":"Schedule","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","Project":"public","runtimeFlavor":"mono","System.StageName":"Build","BuildNumber":"20230425.3","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.13.Amd64.AppleTV.Open","configuration":"Release","DefinitionId":"154","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2023-04-25T22:37:03.213Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery | Failed | {"System.PhaseAttempt":"1","System.JobAttempt":"1","architecture":"arm64","AzurePipelinesTestRunId":"4897396","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","BuildId":"252256","System.StageAttempt":"1","System.JobName":"__default","Reason":"Schedule","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","Project":"public","runtimeFlavor":"mono","System.StageName":"Build","BuildNumber":"20230425.3","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.13.Amd64.AppleTV.Open","configuration":"Release","DefinitionId":"154","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
</details>

**Comment by jakobbotsch** [comment] 2023-05-04 14:22
Duplicate of #85637

**Closed by jakobbotsch** 2023-05-04 14:22 UTC
Labels: arch-x86, os-linux, os-windows, JitStress, arch-x64
