### ISSUE TITLE
TimeZoneInfo.ConvertTime(TimeZoneOffset, TimeZoneInfo) for "Africa/Gaborone" shifts offset from UTC+2:00 to UTC+2:10

### ISSUE THREAD

**Issue by NightOwl888** [dotnet/runtime#62247] opened 2021-12-01 19:07 UTC
### Description

When calling `TimeZoneInfo.ConvertTime(TimeZoneOffset, TimeZoneInfo)` with "Africa/Gaborone" as the time zone, the `DateTimeOffset` returned for some dates in the deep past (in this case 1871) are shifted UTC+2:10 instead of UTC+2:00.

The problem is limited to .NET Core 3.1 and .NET 5.0 on Linux and macOS.

### Reproduction Steps

Prerequisite: [TimeZoneConverter 3.5.0](https://www.nuget.org/packages/TimeZoneConverter/3.5.0)

```c#
[Test]
public void TestCAT()
{
    TimeZoneInfo timeZone = TimeZoneConverter.TZConvert.GetTimeZoneInfo("Africa/Gaborone");
    Assert.AreEqual(2, timeZone.BaseUtcOffset.Hours);
    Assert.AreEqual(0, timeZone.BaseUtcOffset.Minutes);

    const long UnixEpochTicks = 621355968000000000L; // Jan 01, 1970 00:00:00
    const long BadTZShift     = 590376582130000000L; // Oct 31, 1871 05:30:13

    // This date adjusts the time zone correctly UTC+2:00
    DateTimeOffset offset1 = new DateTimeOffset(UnixEpochTicks, TimeSpan.Zero);
    DateTimeOffset timeZoneAdjusted1 = TimeZoneInfo.ConvertTime(offset1, timeZone);
    Assert.AreEqual(2, timeZoneAdjusted1.Offset.Hours);
    Assert.AreEqual(0, timeZoneAdjusted1.Offset.Minutes);

    // This date shifts UTC+2:10 on macOS and Linux in .NET Core 3.1 and .NET Core 5.0 only
    DateTimeOffset offset2 = new DateTimeOffset(BadTZShift, TimeSpan.Zero);
    DateTimeOffset timeZoneAdjusted2 = TimeZoneInfo.ConvertTime(offset2, timeZone);
    Assert.AreEqual(2, timeZoneAdjusted2.Offset.Hours);
    Assert.AreEqual(0, timeZoneAdjusted2.Offset.Minutes);
}
```

NOTE: We are testing with random time zones rather than using `TimeZoneConverter` in our tests, so we know for certain that the issue is not related to how it normalizes time zones.

### Expected behavior

[Central Africa Time](https://en.wikipedia.org/wiki/Central_Africa_Time) is supposed to be UTC+2:00.

### Actual behavior

"Africa/Gaborone" is shifting UTC+2:10 for some dates, but UTC+2:00 for others.

### Regression?

The issue doesn't happen in .NET Framework or in .NET 6.0. However, it does happen in .NET Core 3.1 and .NET 5.0, but only happens on macOS and Linux (not Windows).

### Configuration

Fails on:

- .NET 5.0, Ubuntu 20.04, x64
- .NET 5.0, Ubuntu 20.04, x86
- .NET 5.0, macOS 11, x64
- .NET 5.0, macOS 11, x86
- .NET Core 3.1, Ubuntu 20.04, x64
- .NET Core 3.1, Ubuntu 20.04, x86
- .NET Core 3.1, macOS 10.15, x64
- .NET Core 3.1, macOS 10.15, x86

Does not fail on:

- Windows 10
- Windows 2019
- .NET 6.0
- .NET Framework 4.8

**Comment by Clockwork-Muse** [comment] 2021-12-01 20:16
Virtually all timezones started at "local solar noon", so the first adjustment is odd (often including seconds) because they suddenly align to a whole hour offset (usually - some timezones today have half-hour offsets).  Going by the tzdb, it seems the first, corrective, offset was in 1903.

Note that the zone rule data comes from the OS - there's no data in dotnet for us to correct (we will correct parsing errors if it turns out there is one).

This has come up before for other offsets - see #46152.

**Comment by NightOwl888** [comment] 2021-12-01 21:10
@Clockwork-Muse 

Can you explain how it works correctly in .NET 6 if it is controlled by the OS?

**Comment by danmoseley** [comment] 2021-12-01 21:50
I believe @mattjohnsonpint owns TimeZoneConverter, perhaps he knows off the top of his head.

**Comment by mattjohnsonpint** [comment] 2021-12-01 22:36
Windows time zone data doesn't have LMT offsets.  IANA's does.  This is by design.

**Comment by danmoseley** [comment] 2021-12-02 02:58
Thanks!

I'm not clear why .NET 6 has different behavior though. I remember work to [accept either IANA or NLS ID's](https://github.com/dotnet/runtime/pull/49412).

**Comment by Clockwork-Muse** [comment] 2021-12-02 03:40
... this should be failing on Windows 10 for .Net 5/.Net 6 too - they use the ICU, and that's an IANA id.

When I say "controlled by the OS", there's a set of files installed on the OS by _somebody_ that has all the data.  There's ways for this to be manually updated by admins.  You can change the datasource (at least on Windows... besides the fact it has both NLS and ICU datasets now).  If the data is different there, C# won't even notice (since it has no source of truth).
This makes updating distributed applications/machines somewhat tricky....

**Comment by NightOwl888** [comment] 2021-12-02 08:55
> ... this should be failing on Windows 10 for .Net 5/.Net 6 too - they use the ICU, and that's an IANA id.

I am a little confused why you are saying this, but we have a fairly common use case, so let me clarify why we expect the test to pass.

Our scenario is that we are building a query with a **user selected** time zone, an inclusive lower bound with a user selected start date prior to 1970 (adjusted for time zone), and the Unix Epoch as the upper bound (adjusted for time zone). The issue we are running into is that the lower bound isn't matching all of the records it should be matching because of the 10 minute drift from the *modern* LMT rule. In short, we want to use the *same* LMT rule for both start and end date for all time zones, but this particular time zone seems broken in that regard on Linux/macOS in .NET Core 3.1 and .NET 5.

If you are saying that .NET 6/Windows is broken and this drift is the expected behavior, then we need a way to specify to use the rule from the end date to avoid any drift in our date range. For example:

```c#
[Test]
public void TestCAT()
{
    TimeZoneInfo timeZone = TimeZoneConverter.TZConvert.GetTimeZoneInfo("Africa/Gaborone");
    Assert.AreEqual(2, timeZone.BaseUtcOffset.Hours);
    Assert.AreEqual(0, timeZone.BaseUtcOffset.Minutes);

    const long UnixEpochTicks = 621355968000000000L; // Jan 01, 1970 00:00:00
    const long BadTZShift     = 590376582130000000L; // Oct 31, 1871 05:30:13

    // This date adjusts the time zone correctly UTC+2:00
    DateTimeOffset offset1 = new DateTimeOffset(UnixEpochTicks, TimeSpan.Zero);
    DateTimeOffset timeZoneAdjusted1 = TimeZoneInfo.ConvertTime(offset1, timeZone);
    Assert.AreEqual(2, timeZoneAdjusted1.Offset.Hours);
    Assert.AreEqual(0, timeZoneAdjusted1.Offset.Minutes);

    // This date shifts UTC+2:10 on macOS and Linux in .NET Core 3.1 and .NET Core 5.0 only
    DateTimeOffset offset2 = new DateTimeOffset(BadTZShift, TimeSpan.Zero);
 
    // Explicitly specify the DateTimeOffset from which to borrow the LMT rules from.
    DateTimeOffset timeZoneAdjusted2 = TimeZoneInfo.ConvertTime(offset2, timeZone, useLmtRuleFrom: offset1);
    Assert.AreEqual(2, timeZoneAdjusted2.Offset.Hours);
    Assert.AreEqual(0, timeZoneAdjusted2.Offset.Minutes);
}
```

It should be noted that in Java it normalizes to the *modern* LMT rule (at least by default), so this drift doesn't exist in that environment.  .NET 6 seems to work more similarly to Java's `SimpleDateFormat` in this regard, which is what we are trying to mimic across all .NET flavors.

```java
      LOCALE = randomLocale(random());
      TIMEZONE = randomTimeZone(random());
      DATE_STYLE = randomDateStyle(random());
      TIME_STYLE = randomDateStyle(random());
      
      // assumes localized date pattern will have at least year, month, day,
      // hour, minute
      dateFormat = (SimpleDateFormat) DateFormat.getDateTimeInstance(
          DATE_STYLE, TIME_STYLE, LOCALE);
      
      // not all date patterns includes era, full year, timezone and second,
      // so we add them here
      dateFormat.applyPattern(dateFormat.toPattern() + " G s Z yyyy");
      dateFormat.setTimeZone(TIMEZONE);
```

Of course, the above assumes there is such a thing as a UTC+2:10 rule for Oct 31, 1871, but so far I am not convinced that is correct, being that the [first corrective offset was in 1903](https://github.com/dotnet/runtime/issues/62247#issuecomment-984020450).

>  When I say "controlled by the OS", there's a set of files installed on the OS by somebody that has all the data. There's ways for this to be manually updated by admins. You can change the datasource (at least on Windows... besides the fact it has both NLS and ICU datasets now). If the data is different there, C# won't even notice (since it has no source of truth).
This makes updating distributed applications/machines somewhat tricky....

Understood. However, our scenario is being tested on Azure DevOps using a hosted agent OS image with no such modification. So the source of truth is a "clean" one in that regard and we shouldn't be seeing this 10 minute drift (unless there is something wrong with the hosted Azure DevOps images, of course).

**Comment by mattjohnsonpint** [comment] 2021-12-02 15:11
> Our scenario is that we are building a query with a user selected time zone, an inclusive lower bound with a user selected start date prior to 1970 (adjusted for time zone), and the Unix Epoch as the upper bound (adjusted for time zone).

This is the source of the issue.  You've assumed that time zones are relevant, but time zones are a modern concept. They didn't necessarily exist in the way you are expecting over thst time frame.

On top of that, Windows time zone data is only guaranteed consist from 2010 forward. *Some* entries have transitions before that, but not all of them.  Windows assumes the earliest offset and rule it knows about is the one thst applies to all prior dates. 

You said the user enters two dates and a time zone, but you're matching a Unix timestamp, which is a point in time.  So you've made some implicit, arbitrary decision about the time of day component. Probably midnight, I would guess.  It's that time that you're actually adjusting. 

Is the data you're trying to match actually just a date?  If so, you should not assign a time or time zone. Match dates to dates, not timestamps.  (Consider using `DateOnly` in .NET 6.)

If the data is actually a date and time, but you're querying by it's date component, consider projecting the date to another field for the query. For example, if you're using SQL Server, make an indexed computed column with a `date` type and query that instead.

If you stick with the current approach, rather than adjusting an arbitrary historical time to the user's time zone, use midnight UTC, then expand your search range by +/- 14 hours. Then after getting results from the database you can filter out any excess data before returning it to the user.

**Comment by Clockwork-Muse** [comment] 2021-12-02 16:30
> LMT rule

What is this?

> `TimeZoneInfo.ConvertTime(offset2, timeZone, useLmtRuleFrom: offset1);`

This overload doesn't exist in the BCL.  Did you mean `TimeZoneInfo.ConvertTime(offset2, TimeZoneInfo.Utc, timeZone);`?

... besides Matt's comments about the initial rule adjustment, you code seems like you don't account for historical changes in offset, nor daylight savings time.

> It should be noted that in Java it normalizes to the modern LMT rule (at least by default), so this drift doesn't exist in that environment.

Almost certainly, only if you're using the old, deeply flawed and buggy, and deprecated `java.util.Date`.  Java's modern date/time library (which has been around for a decade or so now), `java.time`, uses data based off the IANA data, and should give you the same results.  (I can tell because you're referencing `SimpleDateFormat`, as there's new formatting classes too).

> Of course, the above assumes there is such a thing as a UTC+2:10 rule for Oct 31, 1871, but so far I am not convinced that is correct, being that the first corrective offset was in 1903.

In 1903, Africa/Gabronne changed to a `+2:00` offset.  The question would be... "changed from what?".  Prior to that the _effective_ offset was from local solar noon... which was `+2:10`.

> Understood. However, our scenario is being tested on Azure DevOps using a hosted agent OS image with no such modification. So the source of truth is a "clean" one in that regard and we shouldn't be seeing this 10 minute drift (unless there is something wrong with the hosted Azure DevOps images, of course).

The "clean" data **has the 2:10 offset**.  C#/dotnet has none of this data itself.  There's nothing broken on our side.

I'll echo Matt on this point as well - you're not treating date/time properly when working with timezones; it's far more complicated than most programmers usually have reason to deal with.

**Comment by NightOwl888** [comment] 2021-12-02 19:48
Okay, I am convinced :smirk:.

I also discovered a format string translation problem that fixes our tests. The line to normalize the format string with the time zone  was missing the minutes, so they weren't being round-tripped when parsing the string (chopping off the minutes).

```java
dateFormat.applyPattern(dateFormat.toPattern() + " G s Z yyyy");
```

Was translated to:

```c#
DATE_FORMAT.SetDateFormat(DATE_FORMAT.GetDateFormat() + " g s z yyyy");
```

When it should have been:

```c#
DATE_FORMAT.SetDateFormat(DATE_FORMAT.GetDateFormat() + " %g s zzz yyyy");
```

### Explained Satisfactorily

- Why does the behavior differ between operating systems?
- Why does the behavior differ between .NET Framework and .NET Core?
- Why does the UTC+2:10 offset make our tests fail when most time zones succeed?

### To Be Explained

- Why does the behavior differ between .NET 5.0 and .NET 6.0 on Linux/macOS when the same OS images are used?

**Comment by mattjohnsonpint** [comment] 2021-12-02 20:39
> Why does the behavior differ between .NET 5.0 and .NET 6.0 on Linux/macOS when the same OS images are used?


From   https://devblogs.microsoft.com/dotnet/date-time-and-time-zone-enhancements-in-net-6/#timezoneinfo-adjustmentrule-improvements 

> Two other minor improvements were made to how adjustment rules are populated from IANA data internally on non-Windows operating systems. They don’t affect external behavior, other than to ensure correctness in some edge cases.

I'd have to go dig through my notes to find the specific PRs, but basically .NET 6 is more correctly interpreting the tzdata.  @tarekgh might be able to elaborate.

**Comment by tarekgh** [comment] 2021-12-02 21:47
> I'd have to go dig through my notes to find the specific PRs, but basically .NET 6 is more correctly interpreting the tzdata. @tarekgh might be able to elaborate.

I believe was referring to the following PR's:
https://github.com/dotnet/runtime/pull/50131
https://github.com/dotnet/runtime/pull/49733

@NightOwl888 I am closing this issue. Feel free to send any more questions we can help you with. 

Thanks @Clockwork-Muse and @mattjohnsonpint for your answers here.

**Closed by tarekgh** 2021-12-02 21:47 UTC
Labels: question, area-System.Runtime
