### ISSUE TITLE
Test failure JIT\\Regression\\CLR-x86-JIT\\V1.2-M02\\b115932\\b115932b\\b115932b.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#75577] opened 2022-09-14 01:16 UTC
Run: [runtime-coreclr outerloop 20220913.3](https://dev.azure.com/dnceng-public/public/_build/results?buildId=15089&view=ms.vss-test-web.build-test-results-tab&runId=295946&resultId=109647&paneView=debug)

Failed test:
```
coreclr windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open
- JIT\\Regression\\CLR-x86-JIT\\V1.2-M02\\b115932\\b115932b\\b115932b.cmd

coreclr Linux arm64 Checked no_tiered_compilation @ (Alpine.314.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm64v8-20210910135810-8a6f4f3
- JIT/Regression/CLR-x86-JIT/V1.2-M02/b115932/b115932b/b115932b.sh

coreclr windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open
- JIT\\Regression\\CLR-x86-JIT\\V1.2-M02\\b115932\\b115932b\\b115932b.cmd

coreclr Linux arm64 Checked no_tiered_compilation @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20220824230426-06f234f
- JIT/Regression/CLR-x86-JIT/V1.2-M02/b115932/b115932b/b115932b.sh

coreclr Linux x64 Checked no_tiered_compilation @ (Alpine.314.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64-20210910135833-1848e19
- JIT/Regression/CLR-x86-JIT/V1.2-M02/b115932/b115932b/b115932b.sh

coreclr windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open
- JIT\\Regression\\CLR-x86-JIT\\V1.2-M02\\b115932\\b115932b\\b115932b.cmd

coreclr Linux x64 Checked no_tiered_compilation @ Ubuntu.1804.Amd64.Open
- JIT/Regression/CLR-x86-JIT/V1.2-M02/b115932/b115932b/b115932b.sh

coreclr OSX x64 Checked no_tiered_compilation @ OSX.1200.Amd64.Open
- JIT/Regression/CLR-x86-JIT/V1.2-M02/b115932/b115932b/b115932b.sh

coreclr OSX arm64 Checked no_tiered_compilation @ OSX.1200.ARM64.Open
- JIT/Regression/CLR-x86-JIT/V1.2-M02/b115932/b115932b/b115932b.sh
```
**Error message:**
```
Assert failure(PID 3000 [0x00000bb8], Thread: 3340 [0x0d0c]): Assertion failed '!"Missing flags on tree"' in '<Module>:foo():int' during 'Morph - Global' (IL size 18; hash 0x0dad0069; FullOpts)

File: D:\a\_work\1\s\src\coreclr\jit\fgdiagnostic.cpp Line: 3187
Image: C:\h\w\AD77096C\p\corerun.exe
Return code:      1
Raw output file:      C:\h\w\AD77096C\w\A98008E1\uploads\Reports\JIT.Regression\CLR-x86-JIT\V1.2-M02\b115932\b115932b\b115932b.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\AD77096C\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  b115932b.dll
Missing flags on tree [000007]: #------------
[000007] n---G+-----                         *  IND       int

[000012] H----+-----                         --*  CNS_INT(h) int    0x82A13C4 [ICON_STR_HDL]
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\AD77096C\p
C:\h\w\AD77096C\w\A98008E1\e\JIT\Regression\CLR-x86-JIT\V1.2-M02\b115932\b115932b\b115932b.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_Regression._CLR_x86_JIT_V1_2_M02_b115932_b115932b_b115932b_._CLR_x86_JIT_V1_2_M02_b115932_b115932b_b115932b_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by jakobbotsch** [comment] 2022-09-14 09:09
Duplicate of #75562

**Closed by jakobbotsch** 2022-09-14 09:09 UTC
Labels: arch-arm64, arch-x86, os-linux, os-mac-os-x, os-windows, arch-x64, area-CodeGen-coreclr, untriaged
