### ISSUE TITLE
Test failure: Loader\\classloader\\TypeGeneratorTests\\TypeGeneratorTest1044\\Generated1044\\Generated1044.cmd

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#36204] opened 2020-05-11 05:33 UTC
failed in job: [runtime-coreclr gcstress-extra 20200510.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=638902&view=ms.vss-test-web.build-test-results-tab&runId=19860372&resultId=106014&paneView=debug)

Error message
~~~
Assert failure(PID 7648 [0x00001de0], Thread: 1336 [0x0538]): Consistency check failed: AV in clr at this callstack:
------
CORECLR! WKS::gc_heap::adjust_limit_clr + 0x3DB (0x00007ffb7681e417)
CORECLR! WKS::gc_heap::a_fit_segment_end_p + 0x25C (0x00007ffb7681da68)
CORECLR! WKS::gc_heap::soh_try_fit + 0x278 (0x00007ffb76841d28)
CORECLR! WKS::gc_heap::allocate_soh + 0x2DC (0x00007ffb7681fe4c)

CORECLR! WKS::gc_heap::try_allocate_more_space + 0x30A (0x00007ffb7684364e)
CORECLR! WKS::gc_heap::allocate_more_space + 0x31 (0x00007ffb7681fb49)
CORECLR! WKS::GCHeap::StressHeap + 0x2D0 (0x00007ffb7681c9c0)
CORECLR! DoGcStress + 0x362 (0x00007ffb764ef6c6)
CORECLR! Thread::RedirectedHandledJITCase + 0x1F6 (0x00007ffb76258aae)
CORECLR! RedirectedHandledJITCaseForGCStress_Stub + 0x26 (0x00007ffb76481196)
<no module>! <no symbol> + 0x0 (0x00007ffb16e0a5bb)
<no module>! <no symbol> + 0x0 (0x0000019f00015bb0)
<no module>! <no symbol> + 0x0 (0x0000019f00015bb0)
<no module>! <no symbol> + 0x0 (0x0000002b5177d498)
<no module>! <no symbol> + 0x0 (0x0000002b5177d498)
-----
.AV on tid=0x538 (1336), cxr=0000002B5177BE80, exr=0000002B5177C370
FAILED: false

CORECLR! CHECK::Trigger + 0x2C9 (0x00007ffb760f7c65)
CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x2B2 (0x00007ffb7615145e)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x97 (0x00007ffb76150f1f)
CORECLR! CLRVectoredExceptionHandler + 0x215 (0x00007ffb76150e65)
CORECLR! CLRVectoredExceptionHandlerShim + 0x1A0 (0x00007ffb761516d0)
NTDLL! RtlInitializeCriticalSection + 0x190 (0x00007ffba3ae5ef0)
NTDLL! RtlImageNtHeaderEx + 0x17B (0x00007ffba3abfa7b)
NTDLL! KiUserExceptionDispatcher + 0x3A (0x00007ffba3b2964a)
CORECLR! WKS::gc_heap::adjust_limit_clr + 0x3DB (0x00007ffb7681e417)
CORECLR! WKS::gc_heap::a_fit_segment_end_p + 0x25C (0x00007ffb7681da68)
 File: F:\\workspace\\_work\\1\\s\\src\\coreclr\\src\\vm\\excep.cpp Line: 7575
 Image: C:\\h\\w\\ACB60930\\p\\CoreRun.exe


Return code: 1
Raw output file: C:\\h\\w\\ACB60930\\w\\AE1E0939\\e\\Loader\\classloader\\Reports\\Loader.classloader\\TypeGeneratorTests\\TypeGeneratorTest1044\\Generated1044\\Generated1044.output.txt
Raw output:
BEGIN EXECUTION
 \"C:\\h\\w\\ACB60930\\p\\corerun.exe\" Generated1044.dll 
========================== Method Calling Test ==========================
class G1_C102<class BaseClass1,class BaseClass0> on type class G3_C15161<class BaseClass0>
 -> EXPECTED: G2_C536::ClassMethod1343.MI.9930<System.Object>()
 -> GOT: G2_C536::ClassMethod1343.MI.9930<System.Object>()
class G1_C102<class BaseClass1,class BaseClass0> on type class G3_C15161<class BaseClass0>
 -> EXPECTED: G2_C536::ClassMethod1342.MI.9929<System.Object>()
 -> GOT: G2_C536::ClassMethod1342.MI.9929<System.Object>()
class G1_C102<class BaseClass1,class BaseClass0> on type class G3_C15161<class BaseClass0>
 -> EXPECTED: G2_C536::ClassMethod1341.MI.9928()
 -> GOT: G2_C536::ClassMethod1341.MI.9928()
class G1_C102<class BaseClass1,class BaseClass0> on type class G3_C15161<class BaseClass0>
 -> EXPECTED: G1_C10::ClassMethod1340.4850()
 -> GOT: G1_C10::ClassMethod1340.4850()
class G1_C102<class BaseClass1,class BaseClass0> on type class G3_C15161<class BaseClass0>
 -> EXPECTED: G2_C536::Method6.9924<System.Object>()
 -> GOT: G2_C536::Method6.9924<System.Object>()
class G1_C102<class BaseClass1,class BaseClass0> on type class G3_C15161<class BaseClass0>
 -> EXPECTED: G1_C10::Method5.4847()
 -> GOT: G1_C10::Method5.4847()
class G1_C102<class BaseClass1,class BaseClass0> on type class G3_C15161<class BaseClass0>
 -> EXPECTED: G2_C536::Method4.9921()
 -> GOT: G2_C536::Method4.9921()
class G1_C102<class BaseClass1,class BaseClass0> on type class G3_C1516`1<class BaseC


Stack trace
   at Loader_classloader._TypeGeneratorTests_TypeGeneratorTest1044_Generated1044_Generated1044_._TypeGeneratorTests_TypeGeneratorTest1044_Generated1044_Generated1044_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x64.Checked\TestWrappers\Loader.classloader\Loader.classloader.XUnitWrapper.cs:line 120614
~~~

**Comment by BruceForstall** [comment] 2020-05-11 16:29
From `CoreCLR Windows_NT x64 Checked gcstress0xc_zapdisable_jitstress2`

```
set COMPlus_TieredCompilation=0
set COMPlus_GCStress=0xC
set COMPlus_JitStress=2
set COMPlus_ReadyToRun=0
set COMPlus_ZapDisable=1
```

**Comment by Maoni0** [comment] 2020-05-11 20:58
@BruceForstall if you don't mind, can you also try
set COMPlus_HeapVerify=1
and see where it breaks? I wonder if this is the same as the issue that observed the same thing on mips.

**Comment by BruceForstall** [comment] 2020-05-11 21:00
@Maoni0 This run was in the CI; I haven't run this myself. I just try to add enough details so it is (more) obvious what the precise failure mode is.

**Comment by Maoni0** [comment] 2020-05-11 21:02
@BruceForstall ahh nm then. thanks!

**Comment by jeffschwMSFT** [comment] 2020-05-11 23:23
@PeterSolMS can you help take a look at this issue?

**Comment by PeterSolMS** [comment] 2020-05-12 16:30
I tried to repro this locally, but without success - ran the test about 500 times with the env variables Bruce stated above. I was able though to repro the upper portion of the call stack - the crash location is when adjust_limit_clr is setting the brick for the first object in the allocation context:

        if (gen0_must_clear_bricks > 0)
        {
            //set the brick table to speed up find_object
            size_t b = brick_of (acontext->alloc_ptr);
            set_brick (b, acontext->alloc_ptr - brick_address (b));  <--- we crash here (call is inlined)
            b++;
            dprintf (3, ("Allocation Clearing bricks [%Ix, %Ix[",
                         b, brick_of (align_on_brick (start + limit_size))));
            volatile short* x = &brick_table [b];
            short* end_x = &brick_table [brick_of (align_on_brick (start + limit_size))];

            for (;x < end_x;x++)
                *x = -1;
        }

Not sure about the root cause yet. Seeing that GCHeap::StressHeap allocates a large string object suggests the hypothesis that perhaps the brick table just isn't large enough in some edge case - hitting Thread::RedirectedHandledJITCase suggests we are about to do a GC, but then we allocate yet another large object - perhaps we didn't plan for that??

**Comment by Maoni0** [comment] 2020-05-12 20:14
if you suspect that there was a heap expansion that caused the heap range to be larger, there are  a couple of things that might aid in your debugging -

* the `saved_changed_segs` array that's recorded in gccommon.cpp with `record_changed_seg` it tells you the last 128 segs that were acquired or deleted along with their gc index/bgc state/start end of the seg

* the GC bookkeeping datastructure itself, the `next_card_table` would point to the older copy of it.

**Comment by PeterSolMS** [comment] 2020-05-13 14:50
Do we have a dump anywhere for this failure? Otherwise, I'm a bit stuck as long as I cannot repro the issue locally - just ran it in a loop overnight, without any luck… I will have a look at the source code though to see if I can spot any issue.

**Comment by BruceForstall** [comment] 2020-05-13 16:41
@PeterSolMS I don't have much experience with core dumps in Helix runs, but I don't see any indication in the log files about one being created or uploaded.

**Comment by janvorli** [comment] 2020-05-14 16:23
@PeterSolMS are you running your tests with the checked build of the runtime? I am asking since that's the one that was used in the lab when the failure happened and maybe it repros just in that build.

**Comment by PeterSolMS** [comment] 2020-05-14 17:25
Yes, I am using the checked build.

**Comment by PeterSolMS** [comment] 2020-05-15 13:00
Looking at the source code, I found that both make_card_table and grow_brick_card_tables will fully commit the space for the brick table. Debugging the example, I found that when the process terminates, we only have about 1.5 MB committed, so it seems unlikely there is a heap expansion. Also, grow_brick_card_tables is never hit. So, I still don't have an explanation for the crash.

**Comment by PeterSolMS** [comment] 2020-05-19 13:19
With Maoni's, Jeremy's and Jarret's help I was able to download the dump and the matching coreclr.pdb. The reason for the crash is that alloc_ptr in the acontext parameter is null. The field alloc_limit is null as well. The logic in adjust_limit_clr does not seem to allow this, as the alloc_limit field is unconditionally set:

    acontext->alloc_limit = (start + limit_size - aligned_min_obj_size);

The parameters to adjust_limit_clr that I can see are:
- start: 0x0000019f`0014cce8
- limit_size: 0x14c18
- size: 0x14c00
- acontext: 0x0000019f`78b78678
- flags: 0
- seg: unavailable
- align_const: 7
- gen_number: 0

The alloc_ptr field in the acontext should also be set according to the logic in adjust_limit_clr.

So I wonder if some other thread has cleared the alloc_ptr and alloc_limit fields, however, I don't see any other thread doing anything interesting in the dump.

**Comment by Maoni0** [comment] 2020-05-19 20:55
what exactly is it AVing on? memclr? the crash you were able to repro also shouldn't happen. depending how it's failing it could be related, for example, if alloc_ptr is 0, of course it would AV trying to set the brick.

**Comment by PeterSolMS** [comment] 2020-05-20 08:08
No, I was not able to repro a crash - just parts of the call stack.

The following is derived from the dump: I assume the memclr went ok - the AV happens immediately afterwards when it's trying to set the brick. The machine code looks like this:

00007ffb`7681e408 488b05995b5900  mov     rax,qword ptr [coreclr!WKS::gc_heap::brick_table (00007ffb`76db3fa8)]
00007ffb`7681e40f 4885c9          test    rcx,rcx
00007ffb`7681e412 7803            js      coreclr!WKS::gc_heap::adjust_limit_clr+0x3db (00007ffb`7681e417)
00007ffb`7681e414 66ffc1          inc     cx
00007ffb`7681e417 66890c78        mov     word ptr [rax+rdi*2],cx <-- AV here
00007ffb`7681e41b 498d85ff0f0000  lea     rax,[r13+0FFFh]
00007ffb`7681e422 488b0d7f5b5900  mov     rcx,qword ptr [coreclr!WKS::gc_heap::brick_table (00007ffb`76db3fa8)]
00007ffb`7681e429 4803c6          add     rax,rsi
00007ffb`7681e42c 482500f0ffff    and     rax,0FFFFFFFFFFFFF000h

At the crashsite, rdi = 0x000fffff`e6100000, which is exactly the brick index corresponding to 0 (0 - 0x0000019f`00000000) >> 12).

**Comment by xiangzhai** [comment] 2020-06-04 09:16
> set COMPlus_HeapVerify=1
> and see where it breaks? I wonder if this is the same as the issue that observed the same thing on mips.

:mips-interest :)

**Comment by xiangzhai** [comment] 2020-08-27 12:16
>     * Hang at 1st method with stress

[Fixed](https://github.com/gsvm/coreclr/commit/ab587921f8b91b3c59e24e388ee64eda4af2a43d#diff-4cbc7cebee869048dc921baad12c9240) GCStress=0x4 infinite loop related issue for MIPS64.

**Comment by xiangzhai** [comment] 2020-08-27 12:25
> No, I was not able to repro a crash

[CoreCLR MIPS64](https://github.com/gsvm/coreclr) is not able to repro the crash either.

**Comment by mangod9** [comment] 2020-08-31 20:32
@xiangzhai so guess we should close this now that its not reproing?

**Comment by xiangzhai** [comment] 2020-09-01 01:35
> @xiangzhai so guess we should close this now that its not reproing?

YES!

**Comment by mangod9** [comment] 2020-09-01 04:53
Thanks

**Closed by mangod9** 2020-09-01 04:53 UTC
Labels: GCStress, area-GC-coreclr

**Comment by xiangzhai** [comment] 2020-09-01 05:53
You are welcome!
