### ISSUE TITLE
[API Proposal]: Add support for skipping visibility checks with AssemblyBuilder.DefineDynamicAssembly

### ISSUE THREAD

**Issue by MichalPetryka** [dotnet/runtime#85020] opened 2023-04-18 23:59 UTC
### Background and motivation

DynamicMethod allows accessing non public elements with its `restrictedSkipVisibility` constructor parameter, but using AssemblyBuilder and emitting complete types this way does not provide such functionality.
Accessing such elements can be useful when working with runtime generation for example in serialization scenarios.
There exists a non documented `IgnoreAccessChecksToAttribute` attribute today, runtime users can't however rely on it being always supported due to being undocumented.

### API Proposal

```csharp
namespace System.Reflection.Emit;

public class AssemblyBuilder
{
    public static System.Reflection.Emit.AssemblyBuilder DefineDynamicAssembly(System.Reflection.AssemblyName name, System.Reflection.Emit.AssemblyBuilderAccess access, bool restrictedSkipVisibility);
    public static System.Reflection.Emit.AssemblyBuilder DefineDynamicAssembly(System.Reflection.AssemblyName name, System.Reflection.Emit.AssemblyBuilderAccess access, System.Collections.Generic.IEnumerable<System.Reflection.Emit.CustomAttributeBuilder>? assemblyAttributes, bool restrictedSkipVisibility);
}
```

### API Usage

```csharp
AssemblyName aName = new AssemblyName("DynamicAssemblyExample");
AssemblyBuilder ab = AssemblyBuilder.DefineDynamicAssembly(aName, AssemblyBuilderAccess.Run, true);
// emit module and types
TypeBuilder tb = ...
ConstructorInfo ctorOfSomeNonPublicTypeImplementingISomeInterface = ...

MethodBuilder meth = tb.DefineMethod(
            "MyMethod",
            MethodAttributes.Public,
            typeof(ISomeInterface),
            new Type[] {  });

ILGenerator methIL = meth.GetILGenerator();
methIL.Emit(OpCodes.Newobj, ctorOfSomeNonPublicTypeImplementingISomeInterface);
methIL.Emit(OpCodes.Ret);
```

### Alternative Designs

Document and expose the hidden `IgnoreAccessChecksToAttribute`.

### Risks

Accessing members that shouldn't be accessed, already possible with DynamicMethod though.

**Comment by steveharter** [comment] 2023-05-23 14:46
Since the compiler does not want to support this, this scenario is not supported by design.

Closing this issue in favor of https://github.com/dotnet/runtime/issues/81741.

See also:
- https://github.com/dotnet/runtime/issues/37875
- https://github.com/dotnet/runtime/issues/60650 (test infrastructure uses a hack which doesn't work on Mono)
  
Currently the general supported mechanisms:
- Generating IL to call the method
- Use reflection (which has been made much faster in 7.0)

**Closed by steveharter** 2023-05-23 14:46 UTC
Labels: api-suggestion, area-System.Reflection.Emit, untriaged
