### ISSUE TITLE
System.Text.Json.JsonSerializer: boxing when serialize structs

### ISSUE THREAD

**Issue by vvdev** [dotnet/runtime#94908] opened 2023-11-17 10:58 UTC
### Description

I noticed that JsonSerializer produces at least one boxing per every serialized struct with public properties/fields.
And maybe because of that, serialization of class instances is noticeably faster than serialization of structs with similar structure.

I was trying to implement some allocation-free processing with buffers and Utf8JsonWriter instances pooling, and found that it anyway impossible with current JsonSerializer implementation because of the boxing.
(because if i make my types i need to serialize classes, then i get rid of boxing, but instances i need to create and serialize becoming the source of allocations).

### Configuration

Tested on .NET7 and  .NET8

### Data

Any generic or non-generic struct with public properties/fields, for example PointF or something like:
```
	public struct Test
	{
		private string _value;
		public string Value { get => _test; set => value; }
	}
```
or
```
	public private struct Test<T>
	{
		private T _value;
		public T Value { get => _test; set => value; }
	}
```
### Analysis

Obviously, boxing happens (at least) in ObjectDefaultConverter<T>, method OnTryWrite:
https://github.com/dotnet/runtime/blob/479df4792daa147e9b51757b0fabc248df21264f/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Object/ObjectDefaultConverter.cs#L313

Wouldn't it be good to make this and related code boxing-free?

**Comment by eiriktsarpalis** [comment] 2023-11-17 17:23
This is a side-effect of the current design of the `JsonPropertyInfo` class, which is generic only on the property type but not the declaring type. We have [this issue](https://github.com/dotnet/runtime/issues/82720) tracking a potential improvement however there are trade-offs:

1. It would regress the static footprint of Native AOT applications due to more generic specializations being necessary and
2. The current design has leaked to [public APIs](https://github.com/dotnet/runtime/blob/867b3e53094f2960f0bcc8b10ea2744bae538e0b/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonPropertyInfoValuesOfT.cs#L45-L53) in the case of the source generator, so we would need to author replacement APIs to make this possible.

Duplicate of https://github.com/dotnet/runtime/issues/82720

**Closed by eiriktsarpalis** 2023-11-17 17:23 UTC
Labels: area-System.Text.Json, tenet-performance, untriaged

**Comment by vvdev** [comment] 2023-11-19 00:45
@eiriktsarpalis, thanks for explanation.
