### ISSUE TITLE
Failing on OSX - System.Diagnostics.Tests.ProcessTests.TestCheckChildProcessUserAndGroupIds 

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#93024] opened 2023-10-04 19:11 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=427185
Build error leg or test failing: System.Diagnostics.Tests.ProcessTests.TestCheckChildProcessUserAndGroupIds
Pull request: https://github.com/dotnet/runtime/pull/93001

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "at System.Diagnostics.Tests.ProcessTests.CheckUserAndGroupIds.String userId",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=427185
**Error message validated:** `at System.Diagnostics.Tests.ProcessTests.CheckUserAndGroupIds.String userId`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 10/4/2023 7:18:59 PM UTC

**Comment by carlossanlop** [comment] 2023-10-04 19:27
Duplicate of https://github.com/dotnet/runtime/issues/92944

**Closed by carlossanlop** 2023-10-04 19:27 UTC
Labels: blocking-clean-ci, untriaged, area-System.Diagnostics-mono, Known Build Error
