### ISSUE TITLE
[API Proposal]: Add `ConfigurationBinder.GetRequiredValue<T>`

### ISSUE THREAD

**Issue by alrz** [dotnet/runtime#105919] opened 2024-08-04 14:38 UTC
### Background and motivation

Right now there's `GetRequiredSection` but there's no corresponding `GetRequiredValue` which when chained will still lead to nullable warnings. 

### API Proposal

```csharp
namespace Microsoft.Extensions.Configuration;

public static class ConfigurationBinder
{
+    public static T GetRequiredValue<T>(this IConfiguration configuration, string key);
}
```
**Open question:** Should there be a corresponding required `Get<T>` method as well?

### API Usage

```csharp
string value = configuration.GetRequiredValue<string>("Some:Key");
```

**Comment by tarekgh** [comment] 2024-08-05 15:52
Duplicate of https://github.com/dotnet/runtime/issues/69163

**Closed by tarekgh** 2024-08-05 15:52 UTC
Labels: api-suggestion, untriaged, area-Extensions-Configuration
