### ISSUE TITLE
Test failure in System.Net.Http.Functional.Tests.SyncHttpHandler_HttpClientHandler_Cancellation_Test.GetAsync_CancelDuringResponseBodyReceived_Unbuffered_TaskCanceledQuickly

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#74122] opened 2022-08-18 02:49 UTC
Hit the failure below in this RC1 PR: https://github.com/dotnet/runtime/pull/74103

- Libraries Test Run release coreclr Linux x64 Debug
- Queues: `(Centos.7.Amd64.Open)Ubuntu.1604.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-mlnet-helix-20220601183719-dde38af+RedHat.7.Amd64.Open+(Debian.10.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-amd64-20220810215022-f344011+Ubuntu.1804.Amd64.Open`

Callstack:
```
System.Net.Http.Functional.Tests.SyncHttpHandler_HttpClientHandler_Cancellation_Test.GetAsync_CancelDuringResponseBodyReceived_Unbuffered_TaskCanceledQuickly(chunkedTransfer: True, connectionClose: False, readOrCopyToAsync: False) [FAIL]
      System.TimeoutException : The operation has timed out.
      Stack Trace:
        /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.Cancellation.cs(260,0): at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.<>c__DisplayClass4_2.<<GetAsync_CancelDuringResponseBodyReceived_Unbuffered_TaskCanceledQuickly>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs(101,0): at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
        /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.Cancellation.cs(228,0): at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.GetAsync_CancelDuringResponseBodyReceived_Unbuffered_TaskCanceledQuickly(Boolean chunkedTransfer, Boolean connectionClose, Boolean readOrCopyToAsync)
```

**Comment by CarnaViire** [comment] 2022-08-18 16:00
Triage: we need to check how frequent this is. We might want to disable the test if it hurts CI. @rzikm could you have a look please?

**Comment by carlossanlop** [comment] 2022-08-18 17:38
Thanks @CarnaViire . Also please decide if it needs a fix to get backported to RC1, if it meets the bar. If it's a test being disabled, you can backport that too to clean the other PRs CI results.

**Comment by rzikm** [comment] 2022-08-18 19:14
I have trouble finding this failure in Kusto

```kusto
cluster('engsrvprod.kusto.windows.net').database('engineeringdata').AzureDevOpsTests
    | where TestName contains 'GetAsync_CancelDuringResponseBodyReceived_Unbuffered_TaskCanceledQuickly'
    | where RunCompleted > ago(10d)
```

returns empty result. Nor does looking for the specific JobId or WorkItemId find anything. @dotnet/dncenghot Can you take a look? It should find at least run from this: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-74103-merge-e45453abd21e437ca1/System.Net.Http.Functional.Tests.Attempt.3/2/console.849c5012.log?helixlogtype=result

**Comment by missymessa** [comment] 2022-08-18 20:20
@rzikm I'm investigating the missing test in the test reporting tables.

**Comment by missymessa** [comment] 2022-08-18 20:36
@rzikm it looks like these work items ran during the storage outage we had a couple days ago and since we rely on uploading test data to our storage account to ingest into Kusto, this disrupted the process. I'm sorry that you're not able to find the data you want for that test.

**Comment by ChadNedzlek** [comment] 2022-08-18 23:24
If you look at that PR, this failure is present: [System.Net.Http.Functional.Tests Work Item](https://dev.azure.com/dnceng/public/_build/results?buildId=1950158&view=ms.vss-test-web.build-test-results-tab&runId=50191660&resultId=206049&paneView=debug)

Meaning we didn't run the functional tests at all (or, at least, didn't report them).

**Comment by MattGal** [comment] 2022-08-18 23:28
> If you look at that PR, this failure is present: [System.Net.Http.Functional.Tests Work Item](https://dev.azure.com/dnceng/public/_build/results?buildId=1950158&view=ms.vss-test-web.build-test-results-tab&runId=50191660&resultId=206049&paneView=debug)
> 
> Meaning we didn't run the functional tests at all (or, at least, didn't report them).

This run was definitely impacted by https://github.com/dotnet/arcade/issues/10358.   I've given them 100 more examples of the problem and notified the issue.  You can follow along via the IcM ticket linked.

**Comment by wfurt** [comment] 2022-08-22 19:40
I run the query again and I only see 4 failures on 8/19 (all RedHat7) no failure afterwards and  no failure on `main`. 
This does not look like regression to me @karelz. The test is time sensitive and verifies Cancellation that is best-effort. 

My suggestion would be to move to 8 and add more diagnostic and perhaps change https://github.com/dotnet/runtime/blob/2a2edc89880ba469e561a7b8ddbfb4f422ddd6a1/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.Cancellation.cs#L269 to `PassingTestTimeout`

**Comment by karelz** [comment] 2022-08-23 16:28
Triage: Looks like it was one time hiccup. There does not seem to be more failures. Moving to 8.0.

**Comment by wfurt** [comment] 2023-06-07 11:24
can you please check failure rate @rzikm? It seems like we did not see recent failures and RedHat7 is no longer supported AFAIK. We should probably close it unless there is evidence this is still failing regularly.

**Comment by rzikm** [comment] 2023-07-20 11:28
No recent hard failures, only PassedOnRerun, closing now as no action is necessary for time being and RH7 is no longer supported.

**Closed by rzikm** 2023-07-20 11:28 UTC
Labels: area-System.Net.Http, test-run-core, test-failure
