### ISSUE TITLE
[mono] Tests failed due to PNSE on windows: System.IO.Tests

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#34583] opened 2020-04-06 10:44 UTC
`System.IO.Tests` namespace is disabled in Mono's CoreFX.issues_windows.rsp file and after enabling <s>the only failing tests are `System.IO.Tests.StreamReaderWithBufferedStream_Tests.ReadAsync_Canceled_ThrowsException` and `System.IO.Tests.StreamReaderTests.ReadAsync_Canceled_ThrowsException`</s> a lot of them still fail.  
The example of the output:
```
System.IO.Tests.StreamReaderWithBufferedStream_Tests.ReadAsync_Canceled_ThrowsException(method: 0, precanceled: False) [FAIL]
System.PlatformNotSupportedException : This API is specific to the way in which Windows handles asynchronous I/O, and is not supported on this platform.
Stack Trace:
    _\src\libraries\System.Private.CoreLib\src\System\Threading\ThreadPoolBoundHandle.PlatformNotSupported.cs(25,0): at System.Threading.ThreadPoolBoundHandle.BindHandle(SafeHandle handle)
    _\src\libraries\System.IO.Pipes\src\System\IO\Pipes\PipeStream.Windows.cs(46,0): at System.IO.Pipes.PipeStream.InitializeAsyncHandle(SafePipeHandle handle)
    _\src\libraries\System.IO.Pipes\src\System\IO\Pipes\PipeStream.cs(101,0): at System.IO.Pipes.PipeStream.InitializeHandle(SafePipeHandle handle, Boolean isExposed, Boolean isAsync)
    _\src\libraries\System.IO.Pipes\src\System\IO\Pipes\NamedPipeServerStream.Windows.cs(122,0): at System.IO.Pipes.NamedPipeServerStream.Create(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, PipeSecurity pipeSecurity, HandleInheritability inheritability, PipeAccessRights additionalAccessRights)
    _\src\libraries\System.IO.Pipes\src\System\IO\Pipes\NamedPipeServerStream.Windows.cs(49,0): at System.IO.Pipes.NamedPipeServerStream.Create(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, HandleInheritability inheritability)
    _\src\libraries\System.IO.Pipes\src\System\IO\Pipes\NamedPipeServerStream.cs(85,0): at System.IO.Pipes.NamedPipeServerStream..ctor(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, HandleInheritability inheritability)
    _\src\libraries\System.IO.Pipes\src\System\IO\Pipes\NamedPipeServerStream.cs(41,0): at System.IO.Pipes.NamedPipeServerStream..ctor(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options)
    _\src\libraries\System.IO\tests\StreamReader\StreamReaderTests.cs(525,0): at System.IO.Tests.StreamReaderTests.ReadAsync_Canceled_ThrowsException(Int32 method, Boolean precanceled)
    --- End of stack trace from previous location ---
```

The tests will be marked with `ActiveIssue` in #32592.

**Comment by danmosemsft** [comment] 2020-04-07 00:24
dupe of https://github.com/dotnet/runtime/issues/34582

**Closed by danmosemsft** 2020-04-07 00:24 UTC
Labels: area-System.IO, untriaged
