### ISSUE TITLE
UseWindowsService doesn't work correctly with single file executables

### ISSUE THREAD

**Issue by xt0rted** [dotnet/runtime#36065] opened 2019-08-06 22:10 UTC
### Describe the bug

`.UseWindowsService()` sets the base path to `AppContext.BaseDirectory` which ends up being something like `C:\Windows\Temp\.net\FileUploader\blc0j22k.v0p` when using a single file exe and running as a service. This prevents the `appsettings.json` files from being loaded if they're saved alongside the exe which [I've been told](https://github.com/dotnet/sdk/issues/3469) is an acceptable deployment scenario.

### To Reproduce

1. Using version `3.0.0-preview7.19362.4` of package `Microsoft.Extensions.Hosting.WindowsServices`
2. Create an `appsettings.json` with a setting in it
3. In `.ConfigureServices(ctx, services)` call `ctx.Configuration.GetValue<string>("SomeValue")`
4. Publish the project using `dotnet publish --configuration Release --output artifacts /p:PublishSingleFile=true /p:PublishTrimmed=true`
5. Install the service & run it
6. The value in `appsettings.json` will not be loaded

### Expected behavior

The `appsettings.json` stored alongside the exe should be loaded when running a single file exe as a service.

### Current workaround

I originally was using the following code before I added in the `Microsoft.Extensions.Hosting.WindowsServices` package which I got from [the asp.net core 2.2 docs](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.2&tabs=visual-studio#app-configuration):

```csharp
var isService = !(Debugger.IsAttached || args.Contains("--console"));

if (isService)
{
    using var process = Process.GetCurrentProcess();
    var pathToExe = process.MainModule.FileName;
    var pathToContentRoot = Path.GetDirectoryName(pathToExe);
    Directory.SetCurrentDirectory(pathToContentRoot);
}
```

After adding this package I modified the code like so:

```diff
 var builder = Host.CreateDefaultBuilder()
     .UseWindowsService()
     .ConfigureServices((ctx, services) =>
     {
     });
 
+if (WindowsServiceHelpers.IsWindowsService())
+{
+    using var process = Process.GetCurrentProcess();
+    var pathToExe = process.MainModule.FileName;
+    var pathToContentRoot = Path.GetDirectoryName(pathToExe);
+
+    builder.UseContentRoot(pathToContentRoot);
+}
 else
 {
     builder.UseConsoleLifetime();
 }
 
 var host = builder.Build();
```

Depending on how you publish the application this might not be a bug but rather a documentation note. It seems worth mentioning though.

**Comment by maryamariyan** [comment] 2020-08-12 23:32
Not blocking release of 5.0 product.

**Comment by maryamariyan** [comment] 2020-10-08 15:19
@xt0rted could you please check if this still repros on 5.0? (Dupe of https://github.com/dotnet/runtime/issues/3704)

**Comment by maryamariyan** [comment] 2020-10-22 17:30
Closing issue as resolved on .NET 5.0.

@xt0rted if this gets repro on 5.0 we could reopen it again.

**Closed by maryamariyan** 2020-10-22 17:30 UTC
Labels: area-Extensions-Hosting
