### ISSUE TITLE
ArraySortHelper.cs: Possible unnecessary bounds checks

### ISSUE THREAD

**Issue by colgreen** [dotnet/runtime#46553] opened 2021-01-04 23:23 UTC
This relates to the PickPivotAndPartition() method, of which there are four implementations within ArraySortHelper.cs. The four are:

    1. ArraySortHelper<T>
        private static int PickPivotAndPartition(Span<T> keys, Comparison<T> comparer);

    2. GenericArraySortHelper<T>
        private static int PickPivotAndPartition(Span<T> keys)

    3. ArraySortHelper<TKey, TValue>
        private static int PickPivotAndPartition(Span<TKey> keys, Span<TValue> values, IComparer<TKey> comparer)

    4. GenericArraySortHelper<TKey, TValue>
        private static int PickPivotAndPartition(Span<TKey> keys, Span<TValue> values)

('Generic' here just means 'general purpose', it has nothing to do with C#/.NET generic types).

Implementation number 2 (on GenericArraySortHelper<T>) makes extensive use of Unsafe.Add(), Unsafe.IsAddressLessThan(), and Unsafe.IsAddressGreaterThan(), presumably for performance reasons, because that method handles the simplest scenario of a single array of keys that are either native types, or IComparable. However, it does make the code somewhat harder to read, and that has perhaps caused this redundant code to be missed.

In the two implementations that take an IComparer, these inherently handle null keys as the null values are simply passed to IComparer.Compare(a,b). The other two implementations must contain a null key check, like so (/pivot/ is a key value, and may be null) (this is taken from implementation number 4, in GenericArraySortHelper<TKey, TValue>):

            while (left < right)
            {
                if (pivot == null)
                {
                    while (left < (hi - 1) && keys[++left] == null) ;
                    while (right > 0 && keys[--right] != null) ;
                }
                else
                {
                    while (GreaterThan(ref pivot, ref keys[++left])) ;
                    while (LessThan(ref pivot, ref keys[--right])) ;
                }
                [...]
            }

Notice that the first inner while loop increments _left_ until a non-null value is found, or some bound is reached. That bound check is not necessary when the pivot is non-null (as per the lower _else_ block).

Now let's look at the equivalent section from implementation number 2, in GenericArraySortHelper<T>:

            while (Unsafe.IsAddressLessThan(ref leftRef, ref rightRef))
            {
                if (pivot == null)
                {
                    while (Unsafe.IsAddressLessThan(ref leftRef, ref nextToLastRef) && (leftRef = ref Unsafe.Add(ref leftRef, 1)) == null) ;
                    while (Unsafe.IsAddressGreaterThan(ref rightRef, ref zeroRef) && (rightRef = ref Unsafe.Add(ref rightRef, -1)) != null) ;
                }
                else
                {
                    while (Unsafe.IsAddressLessThan(ref leftRef, ref nextToLastRef) && GreaterThan(ref pivot, ref leftRef = ref Unsafe.Add(ref leftRef, 1))) ;
                    while (Unsafe.IsAddressGreaterThan(ref rightRef, ref zeroRef) && LessThan(ref pivot, ref rightRef = ref Unsafe.Add(ref rightRef, -1))) ;
                }
                [...]
            }

Note that the lower _else_ block contains the unnecessary bounds tests.

I believe these are redundant. Or, if they are not, then they are missing from implementation 4, in GenericArraySortHelper<TKey, TValue>!

--
Update: I wonder if this is intentional, to make absolutely sure the loop doesn't progress beyond the ends of the _keys_ span, given that this is not using the safe span 'indexer' syntax. But that just makes me wonder why the Unsafe.* methods are used here, i.e, doesn't the JIT compiler produce equivalent code now for spans anyway? So maybe we just revert to using indexers instead of Unsafe.* methods, and then remove the redundant bounds checks(?)

**Comment by stephentoub** [comment] 2021-01-05 00:29
This is by design.  An erroneous comparer code cause the loop to walk off the end of the span,  otherwise. With the indexer,  the runtime provides bounds check,  but when using unsafe code,  we need to make absolutely sure the code is still safe even in the face of a poorly-implemented comparer.

In general we shy away from using unsafe code for performance except for critical,  hot-path functions... and this is one such function.

**Comment by colgreen** [comment] 2021-01-05 09:19
Thanks @stephentoub . In which case, I may look into the performance differential between unsafe vs safe code, as (a) My suspicion is that the difference will be minimal due to JITter improvments, and (b) it does cause a functional difference, i.e., the safe code will throw an index-out-of-range exception, whereas the unsafe code will continue executing the overall sort routine.

I appreciate there is a lot fo nuabnce here, e.g. the type and size/width of the key type, the different types of comparer (native inline, IComparablem, IComparer), CPU/hardware platform. So it's not an easy thing to nail down and say one approach is definitively faster than another.

**Comment by stephentoub** [comment] 2021-01-05 11:36
> the safe code will throw an index-out-of-range exception

It's caught higher in the stack. 

> my suspicion is that the difference will be minimal due to JITter improvments

It was quite measurable here the last time I looked several months ago.

**Comment by colgreen** [comment] 2021-01-05 12:43
If you have any performance test code that you think I could use then feel free to point me to it (or send it my way). E.g. code that tries a range of different scenarios (different ordered data, and data types).

My expectation is that either (a) your optimisation will still be faster (given that you observed that recently), or (b) the safe span indexer approach will match performance, which would then give us the option of changing back to safe code, but for no perf gain.

**Comment by stephentoub** [comment] 2021-01-05 12:55
> would then give us the option of changing back to safe code, but for no perf gain.

If we could get equivalent performance here without using unsafe code,  we would happily accept a PR.

> If you have any performance test code that you think I could use then feel free to point me to it (or send it my way).

There are some sorting tests in the dotnet/performance repo. I suggest starting with those.
https://github.com/dotnet/performance/blob/master/src/benchmarks/micro/libraries/System.Collections/Sort.cs

You might also use the microbenchmarks from:
https://github.com/dotnet/coreclr/pull/27700

**Comment by stephentoub** [comment] 2021-01-06 15:08
As the question has been answered, I'm going to close the issue.  If you come up with a good improvement, please do submit a PR :)

Thanks.

**Closed by stephentoub** 2021-01-06 15:08 UTC
Labels: area-System.Collections, question, tenet-performance, untriaged

**Comment by colgreen** [comment] 2021-01-09 19:11
@stephentoub just and fyi for now, but looks like the benchmarks are broken :(

 See https://github.com/dotnet/BenchmarkDotNet/issues/1636

Closely related to your bug report https://github.com/dotnet/BenchmarkDotNet/issues/730
