### ISSUE TITLE
Linq's TryGetNonEnumeratedCount() should check for IReadOnlyCollection<T>

### ISSUE THREAD

**Issue by KPixel** [dotnet/runtime#54764] opened 2021-06-25 21:16 UTC
`IReadOnlyCollection<T>` can provide a Count without enumerating in:

https://github.com/dotnet/runtime/blob/d68754424e0d830aff69d31f65c74aa34508047a/src/libraries/System.Linq/src/System/Linq/Count.cs#L95

Note: This request was already mentioned in #52775. However, since that issue started as something much bigger, I am concerned that this specific request will be missed.

**Comment by huoyaoyuan** [comment] 2021-06-26 12:00
https://github.com/dotnet/runtime/issues/42254

**Comment by teo-tsirpanis** [comment] 2021-06-26 17:51
This change would regress F#'s lists.

For those that don't know, they are implemented as single-linked lists, and their length is computed in linear time by traversing the entire list. They implement `IReadOnlyCollection` but not `ICollection`, which means that with the existing behavior, the TryGet**NonEnumerated**Count method does not actually enumerate over the entire collection, which would happen if the method special-cased `IReadOnlyCollection`s.

**Comment by eiriktsarpalis** [comment] 2021-06-28 14:17
This was considered in the [implementation PR](https://github.com/dotnet/runtime/pull/48239) but ultimately we went with reflecting the checks that exist in `Enumerable.Count()`. The decision was informed by the fact that most BCL types implementing `IReadOnlyCollection<T>` usually also implement `ICollection<T>`. I'm on the fence on this one, it's probably fair to assume that callers of this particular method might prefer one additional runtime check over not knowing the count. @stephentoub thoughts?

**Comment by stephentoub** [comment] 2021-06-28 14:20
> @stephentoub thoughts?

If we're going to start adding checks for `IReadOnlyCollection<T>`, I would like us to do so holistically across LINQ; that doesn't mean we need to add such checks everywhere, but we should evaluate all the places we look at `ICollection<T>` and decide whether a corresponding check for `IReadOnlyCollection<T>` makes sense, not just in this one method (especially since if this method successfully gives you the count, that might suggest subsequent LINQ operations would also be able to optimize by getting the count as part of the implementation).  Also, historically we shied away from `IROC<T>` because its covariant nature made it a much more expensive type check to perform.  We believe we've reduced those costs significantly, but any decision here would need to factor in the performance impact of the check.

**Comment by eiriktsarpalis** [comment] 2021-06-28 14:36
> This change would regress F#'s lists.
>
> For those that don't know, they are implemented as single-linked lists, and their length is computed in linear time by traversing the entire list.

@teo-tsirpanis I see your point but I wouldn't consider it a regression. It is assumed that callers of `TryGetNonEnumeratedCount` need to know the count of the enumerable ahead of enumeration and the only way to achieve this in F# lists is via linear traversal.   Note however that the [`IROC` implementation uses the `Length` property](https://github.com/dotnet/fsharp/blob/095deb31c22abc742154b61647aa5fe97f726105/src/fsharp/FSharp.Core/prim-types.fs#L3782) which is [substantially faster compared to using an enumerator](https://gist.github.com/eiriktsarpalis/b5defaf4d79f20d3f8a83797b3a5a164). Thus technically speaking, the "NonEnumerated" part of `TryGetEnumeratedCount` is still being honored since no enumerator is being created.

**Comment by eiriktsarpalis** [comment] 2021-06-28 14:37
> If we're going to start adding checks for IReadOnlyCollection<T>, I would like us to do so holistically across LINQ

That's probably covered by https://github.com/dotnet/runtime/issues/42254. I'm going to close this issue in favor of that.

**Closed by eiriktsarpalis** 2021-06-28 14:37 UTC
Labels: area-System.Linq, untriaged
