### ISSUE TITLE
More extensible object and collection converters

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#36785] opened 2020-05-20 21:18 UTC
This is the new issue to add a public object\POCO converter. The previous issue was https://github.com/dotnet/runtime/issues/1562 which was re-purposed for a refactoring effort and subsequently closed.

API proposal to come soon. It is expected to address several issues to make authoring converters for POCOs much easier and also be leveraged by a code-gen (AOT) effort that is in progress.

See [5.0 serializer goals](https://github.com/dotnet/runtime/issues/1562) for high-level information on the code-gen effort.

### Work

- [x] https://github.com/dotnet/runtime/issues/728
- [x] https://github.com/dotnet/runtime/issues/39896
- [ ] https://github.com/dotnet/runtime/issues/29861. Note that OnSerialize callbacks can also do this.
- [x] https://github.com/dotnet/runtime/issues/60518
- [x] https://github.com/dotnet/runtime/issues/593
- [x] https://github.com/dotnet/runtime/issues/34456
- [ ] https://github.com/dotnet/runtime/issues/29975
- [x] https://github.com/dotnet/runtime/issues/55781
- [x] https://github.com/dotnet/runtime/issues/51715

**Comment by steveharter** [comment] 2020-08-04 16:02
Moving to future.

There are three aspects to this issue that overlap, so we want a single, consistent model to cover these:
- Extensible model for object and collections, as an alternative to the existing "value-type" converter model:
  - Leverage the existing object- and collection- converters that were exposed in https://github.com/dotnet/runtime/issues/1562  
  - Support before- and after- notifications for (de)serialize.
  - Hook into the existing logic for calling constructors
- Expose metadata (https://github.com/dotnet/runtime/issues/34456).
  - Ability to inspect existing metadata (useful for external tooling such as JSON validation).
  - Ability to change or specify metadata.
  - Ability to specify delegate for setting and getting a property.
  - Metadata includes:
    - For an "object" includes its properties, serialization attributes, converter, and constructor delegate.
    - Metadata for an object "property" includes serialization attributes, converter and delegates to the setter\getter.
    - Metadata for a "collection" includes serialization attributes, converter, element converter and constructor delegate.
- Code-gen effort for performance (startup time, memory) https://github.com/dotnet/runtime/issues/1568
  - Internally this uses the two items above.

**Comment by weifenluo** [comment] 2021-01-19 13:04
Please at least support writing custom converter for `System.Data.DataTable` and `System.Data.DataRow`. Current `JsonConverter<T>` is intended primarily for data types, not full\complex objects.

**Comment by steveharter** [comment] 2021-07-16 15:18
Moving to 7.0 for consideration of remaining features.

**Comment by scottdorman** [comment] 2021-12-03 18:53
In #31257, it's hinted that the OnSerialzing methods from #39896 would be helpful in ignoring properties at run time, but I'm not seeing how this behavior would work.

Specifically, I need to exclude a collection during serialization only when it's empty.

I have a custom collection class

```c#
[JsonConverter(typeof(LinkCollectionConverter))]
public sealed class LinkCollection : IEnumerable<KeyValuePair<string, Link>>, IEnumerable
{
   public static readonly LinkCollection Empty = new(new Dictionary<string, Link>());
   // omitted for brevity
}
```

and the associated converter

```c#
public class LinkCollectionConverter : JsonConverter<LinkCollection>
{
    public override bool HandleNull => false;

    public override LinkCollection? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        Dictionary<string, Link>? value = JsonSerializer.Deserialize<Dictionary<string, Link>>(ref reader, options);
        return new LinkCollection(value);
    }

    public override void Write(Utf8JsonWriter writer, LinkCollection value, JsonSerializerOptions options)
    {
        if (value is not null && value.Count > 0)
        {
            writer.WriteStartObject();

            foreach (KeyValuePair<string, Link> pair in value)
            {
                writer.WritePropertyName(pair.Key);
                JsonSerializer.Serialize(writer, pair.Value, options);
            }

            writer.WriteEndObject();
        }
    }
}
```

The POCO using this collection looks like
```c#
public class LicenseName
{
    [JsonPropertyName("name")]
    [JsonInclude]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
    public string? Name { get; set; }

    [JsonPropertyName("_links")]
    [JsonInclude]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public LinkCollection? Links { get; init; } = null;
}
```

Although this works, what I really want is for the property in the POCO to be this

```c#
[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
public LinkCollection Links { get; init; } = LinkCollection.Empty();
```

A serialized instance should look like 

```json
{"name":"test"}
```

The problem is that when I define my property as I want (with it initialized to an empty collection rather than null), I end up with JSON that looks like

```json
{"name":"test", "_links": }
```

which isn't valid JSON. I really need a way to prevent the property from being written at all when it's empty. Is this possible with the state of STJ in .NET 6? I've tried implementing `IJsonOnSerializing`, but the callback never seems to be called.

When I deserialize into an instance, it should populate the `Links` property or leave it empty, depending on what the source JSON looks like (which is the result of making an `HttpClient` call to a web API).

What would be really nice is if there were an additional `JsonIgnoreCondition` value like `JsonIgnoreCondition.WhenEmpty` that would cause the serialization to behave as expected. It would essentially behave in a way similar to `JsonIgnoreCondition.WhenWritingNull` or `JsonIgnoreCondition.WhenWritingDefault`, but check that if the type being serialized is a collection type and it's empty, then it skips writing the property.

**Comment by DavidErben** [comment] 2021-12-10 07:56
I might have found a solution for this, but it is a bit ugly since you need to implement the IJsonOnSerializing interface in every single class you want to serialize without empty collections. You basically set all empty collections to null before the serializer kicks in. This way the ignore condition is honored and the property is not serialized.

        public class Product : IJsonOnSerializing
        {
            public string Name { get; set; }
            public ICollection<string> Tags { get; set; }

            public Product()
            {
                Tags = new HashSet<string>();
            }

            public void OnSerializing()
            {
                if (Tags is not null && Tags.Count == 0)
                {
                    Tags = null;
                }
            }
        }

        static async Task Main(string[] args)
        {
            var options = new JsonSerializerOptions() { DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull };
            Console.WriteLine(JsonSerializer.Serialize(new Product() { Name = "Test" }, options));
        }

Produces the following output:

{"Name":"Test"}

**Comment by eiriktsarpalis** [comment] 2022-01-20 12:05
Closing in favor of #63686, with a few additional features tracked by #63762.

**Closed by eiriktsarpalis** 2022-01-20 12:05 UTC
Labels: api-needs-work, area-System.Text.Json
