### ISSUE TITLE
Calling AssemblyLoadContext.Unload multiple times causes fatal crash 

### ISSUE THREAD

**Issue by maxima120** [dotnet/runtime#91087] opened 2023-08-24 18:40 UTC
### Description

Unfortunately I cant provide repro case (yet). But at least it is reproducible every time I try certain scenario in my app.

I am getting this exception in WPF .NET 7 app. It happens when I try to unload a dll loaded in run-time.. The unload works if called correctly. 

But if it tries to call `apploadingContext.Unload` second time (there is a bug somewhere in my code) - the exception `ExecutionEngineException` is shown in VS if I debug and if I run it standalone I get this error in event log: 

```
Faulting application name: qqq.exe, version: 0.4.0.1, time stamp: 0x64b07659
Faulting module name: coreclr.dll, version: 7.0.1023.36312, time stamp: 0x64b06d6c
Exception code: 0xc0000005
Fault offset: 0x0000000000133fa2
Faulting process ID: 0xaea4
Faulting application start time: 0x01d9d69df3fe6c1e
Faulting application path: qqqq\bin\Debug\net7.0-windows\qqq.exe
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.10\coreclr.dll
Report ID: 9616639b-d2b2-4669-95da-65f25f23f4e7
Faulting package full name: 
Faulting package-relative application ID: 
```

### Reproduction Steps

N/A

### Expected behavior

Since this exception marked as obsolete I think it should not be thrown. Perhaps new design should react on fatal conditions somehow differently.. Having said that I want to point that dll I am loading is few lines C# compiled in run-time with Roslyn and it does not do any funny stuff like unmanaged memory access, so I suspect that this exception is a side-effect from a bug in AssemblyContextLoader..

### Actual behavior

Application crashes and no way to recover from it.

### Regression?

N/A

### Known Workarounds

None

### Configuration

.NET 7.0 on Windows 10 x64 build 19045

### Other information

the code for the loader is taken from MSDN code:
```
    public class MyAssemblyLoader : AssemblyLoadContext//, IDisposable
    {
        private AssemblyDependencyResolver resolver;

        public MyAssemblyLoader (string pluginPath) : base(pluginPath, true)
        {
            resolver = new AssemblyDependencyResolver(pluginPath);
        }

        protected override Assembly Load(AssemblyName assemblyName)
        {
            string assemblyPath = resolver.ResolveAssemblyToPath(assemblyName);
            if (assemblyPath != null)
            {
                return LoadFromAssemblyPath(assemblyPath);
            }

            return null;
        }

        protected override IntPtr LoadUnmanagedDll(string unmanagedDllName)
        {
            string libraryPath = resolver.ResolveUnmanagedDllToPath(unmanagedDllName);
            if (libraryPath != null)
            {
                return LoadUnmanagedDllFromPath(libraryPath);
            }

            return IntPtr.Zero;
        }
    }
```

**Comment by jkotas** [comment] 2023-08-24 18:46
Duplicate of #63244

**Comment by maxima120** [comment] 2023-08-24 19:36
I disagree with your assessment. The linked issue reported for completely different use case for once. The OP seems to corrupted runtime with unmanaged call with incorrect memory address. And it was reported in .net 7 alpha 2yrs ago.

I specifically stressed that I don't do any unmanaged code. Moreover I repro it in a demo app. Will publish code tomorrow

**Comment by jkotas** [comment] 2023-08-24 20:56
The title of this issue is "Got ExecutionEngineException - although it is marked as obsolete and not supposed to be thrown". The problem described by the title is same as the problem discussed in the linked issues. There is no `ExecutionEngineException ` exception throw, but the UI makes it look like there is.

If you can share a repro for your crash, we will be happy to look at it.

**Comment by maxima120** [comment] 2023-08-25 09:38
[FatalExRepro.zip](https://github.com/dotnet/runtime/files/12437709/FatalExRepro.zip)
this a WPF app.. Run, click Compile, wait till "Success" message appears, click Load, click Unload, click Unload - app crashes (or if ran in VS - gets `ExecutionEngineException`)

**Comment by jkotas** [comment] 2023-08-25 21:46
Stacktrace of the crash:
```
00 00000099`6db7d488 00007ffa`e9b1098b     coreclr!GCHandleManager::DestroyHandleOfType+0x12 [D:\a\_work\1\s\src\coreclr\gc\gchandletable.cpp @ 124] 
01 (Inline Function) --------`--------     coreclr!DestroyHandle+0x18 [D:\a\_work\1\s\src\coreclr\vm\gchandleutilities.h @ 259] 
02 00000099`6db7d490 00007ffa`e99fa09c     coreclr!CustomAssemblyBinder::PrepareForLoadContextRelease+0x2f [D:\a\_work\1\s\src\coreclr\binder\customassemblybinder.cpp @ 239] 
03 00000099`6db7d4c0 00007ffa`ce9f2f3f     coreclr!AssemblyNative_PrepareForAssemblyLoadContextRelease+0x4c [D:\a\_work\1\s\src\coreclr\vm\assemblynative.cpp @ 1262] 
```
@janvorli Could you please take a look?

**Closed** 2023-08-30 17:14 UTC
Labels: area-VM-coreclr, untriaged, in-pr
