### ISSUE TITLE
Test failure JIT\\HardwareIntrinsics\\X86\\X86Base\\Pause_ro\\Pause_ro.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#61901] opened 2021-11-22 02:03 UTC
Run:[ runtime-coreclr jitstress-isas-x86 20211120.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1479583&view=ms.vss-test-web.build-test-results-tab&runId=42375070&paneView=debug&resultId=101667)

Failed test:
```
CoreCLR windows x86 Checked jitstress_isas_x86_nosse @ Windows.10.Amd64.Open
- JIT\\HardwareIntrinsics\\X86\\X86Base\\Pause_ro\\Pause_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\X86Base\\Pause_r\\Pause_r.cmd

CoreCLR windows x86 Checked jitstress_isas_x86_nosse2 @ Windows.10.Amd64.Open
- JIT\\HardwareIntrinsics\\X86\\X86Base\\Pause_r\\Pause_r.cmd
- JIT\\HardwareIntrinsics\\X86\\X86Base\\Pause_ro\\Pause_ro.cmd

CoreCLR windows x86 Checked jitstress_isas_2_x86_nosse @ Windows.10.Amd64.Open
- JIT\\HardwareIntrinsics\\X86\\X86Base\\Pause_ro\\Pause_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\X86Base\\Pause_r\\Pause_r.cmd

CoreCLR windows x64 Checked jitstress_isas_x86_nosse @ Windows.10.Amd64.Open
- JIT\\HardwareIntrinsics\\X86\\X86Base\\Pause_r\\Pause_r.cmd
- JIT\\HardwareIntrinsics\\X86\\X86Base\\Pause_ro\\Pause_ro.cmd

CoreCLR OSX x64 Checked jitstress_isas_x86_nosse2 @ OSX.1014.Amd64.Open
- JIT/HardwareIntrinsics/X86/X86Base/Pause_r/Pause_r.sh
- JIT/HardwareIntrinsics/X86/X86Base/Pause_ro/Pause_ro.sh

CoreCLR Linux x64 Checked jitstress_isas_2_x86_nohwintrinsic @ Ubuntu.1804.Amd64.Open
- JIT/HardwareIntrinsics/X86/X86Base/Pause_r/Pause_r.sh
- JIT/HardwareIntrinsics/X86/X86Base/Pause_ro/Pause_ro.sh

```
**Error message:**
```
Return code:      1
Raw output file:      C:\h\w\AE9209AF\w\B22209B2\uploads\Reports\JIT.HardwareIntrinsics\X86\X86Base\Pause_ro\Pause_ro.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\AE9209AF\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  Pause_ro.dll
Expected: 100
Actual: 0
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\AE9209AF\p
C:\h\w\AE9209AF\w\B22209B2\e\JIT\HardwareIntrinsics\X86\X86Base\Pause_ro\Pause_ro.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_HardwareIntrinsics._X86_X86Base_Pause_ro_Pause_ro_._X86_X86Base_Pause_ro_Pause_ro_cmd()
```

**Comment by echesakovMSFT** [comment] 2021-11-23 20:00
I think `Yield`/`Pause` should belong to `Category_Scalar` rather than `Category_Special` and table-driven importation can be just extended in the following way
```diff
--- a/src/coreclr/jit/hwintrinsic.cpp
+++ b/src/coreclr/jit/hwintrinsic.cpp
@@ -986,8 +986,8 @@ GenTree* Compiler::impHWIntrinsic(NamedIntrinsic        intrinsic,
         switch (numArgs)
         {
             case 0:
-                assert(!isScalar);
-                retNode = gtNewSimdHWIntrinsicNode(retType, intrinsic, simdBaseJitType, simdSize);
+                retNode = isScalar ? gtNewScalarHWIntrinsicNode(retType, intrinsic) : gtNewSimdHWIntrinsicNode(retType, intrinsic, simdBaseJitType, simdSize);
                 break;

             case 1:
```

@tannergooding What do you think?

**Comment by tannergooding** [comment] 2021-11-23 20:07
These are strictly not scalar intrinsics; they are special just like `LoadFence`, `MemoryFence`, `StoreFence`, and others.

The issue with `COMPlus_FeatureSIMD` would be independent and is likely due to `X86Base` and `ArmBase` not being correctly categorized.

**Comment by echesakovMSFT** [comment] 2021-11-23 20:25
What do you mean "`X86Base` and `ArmBase` not being correctly categorized."? 

> We should investigate what the issue there is and fix it so that special/helper intrinsics can still be correctly handled.

The issue is that we call `getBaseJitTypeAndSizeOfSIMDType` for `Yield`/`Pause` for almost no reason:
```
clrjit.dll!Compiler::getBaseJitTypeAndSizeOfSIMDType(CORINFO_CLASS_STRUCT_ * typeHnd, unsigned int * sizeBytes) Line 160
	at D:\echesako\src\runtime2\src\coreclr\jit\simd.cpp(160)
clrjit.dll!Compiler::impHWIntrinsic(NamedIntrinsic intrinsic, CORINFO_CLASS_STRUCT_ * clsHnd, CORINFO_METHOD_STRUCT_ * method, CORINFO_SIG_INFO * sig, bool mustExpand) Line 777
	at D:\echesako\src\runtime2\src\coreclr\jit\hwintrinsic.cpp(777)
clrjit.dll!Compiler::impIntrinsic(GenTree * newobjThis, CORINFO_CLASS_STRUCT_ * clsHnd, CORINFO_METHOD_STRUCT_ * method, CORINFO_SIG_INFO * sig, unsigned int methodFlags, int memberRef, bool readonlyCall, bool tailCall, CORINFO_RESOLVED_TOKEN * pConstrainedResolvedToken, CORINFO_THIS_TRANSFORM constraintCallThisTransform, CorInfoIntrinsics * pIntrinsicID, bool * isSpecialIntrinsic) Line 3767
	at D:\echesako\src\runtime2\src\coreclr\jit\importer.cpp(3767)
clrjit.dll!Compiler::impImportCall(opcode_t opcode, CORINFO_RESOLVED_TOKEN * pResolvedToken, CORINFO_RESOLVED_TOKEN * pConstrainedResolvedToken, GenTree * newobjThis, int prefixFlags, CORINFO_CALL_INFO * callInfo, unsigned int rawILOffset) Line 8691
	at D:\echesako\src\runtime2\src\coreclr\jit\importer.cpp(8691)
clrjit.dll!Compiler::impImportBlockCode(BasicBlock * block) Line 15075
	at D:\echesako\src\runtime2\src\coreclr\jit\importer.cpp(15075)
```

I believe we also do this for `LoadFence`, `MemoryFence`, `StoreFence`. There is no issue since these are defined in `Sse2` and the call to them should be guarded with `Sse2.IsSupported`.

**Comment by tannergooding** [comment] 2021-11-23 20:33
> What do you mean "X86Base and ArmBase not being correctly categorized."?

I mean that this is a general issue for intrinsics in non-SIMD ISAs. This would include X86Base, Bmi1, Bmi2, Lzcnt, ArmBase, and Crc32. Its surfacing for `Pause` and `Yield` because they are the first intrinsics in this category that aren't `HW_Category_Scalar`.

The fix here isn't to go and mark them `Scalar`, because they aren't `Scalar` instructions. They are special instructions that most compilers specially handle (including LLVM/Clang) because they take no operands and sometimes need special handling in how they get interpreted in various parts of code.

The fix is instead to ensure that non-SIMD instructions are going down the right paths, to avoid the issue entirely: https://github.com/dotnet/runtime/pull/61982

**Comment by tannergooding** [comment] 2021-11-23 20:34
`LoadFence`, `MemoryFence`, and `StoreFence` are special as well; but are part of a SIMD ISA and so will always do the correct thing and return `CORINFO_TYPE_UNDEF` here.

**Comment by VincentBu** [comment] 2021-11-30 01:29
Failed again in: [runtime 20211129.50](https://dev.azure.com/dnceng/public/_build/results?buildId=1489344&view=ms.vss-test-web.build-test-results-tab&runId=42578756&resultId=100031&paneView=debug)

Failed test:
```
Mono Linux x64 Release @ Ubuntu.1804.Amd64.Open

- JIT/HardwareIntrinsics/X86/X86Base/Pause_ro/Pause_ro.sh
- JIT/HardwareIntrinsics/X86/X86Base/Pause_r/Pause_r.sh

Mono Linux x64 Release no_tiered_compilation @ Ubuntu.1804.Amd64.Open

- JIT/HardwareIntrinsics/X86/X86Base/Pause_r/Pause_r.sh
- JIT/HardwareIntrinsics/X86/X86Base/Pause_ro/Pause_ro.sh

```
**Error message:**
```
Return code:      1
Raw output file:      /datadisks/disk1/work/B03B0976/w/A7F508BE/uploads/Reports/JIT.HardwareIntrinsics/X86/X86Base/Pause_ro/Pause_ro.output.txt
Raw output:
BEGIN EXECUTION
/datadisks/disk1/work/B03B0976/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false Pause_ro.dll ''
Expected: 100
Actual: 0
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/datadisks/disk1/work/B03B0976/p
/datadisks/disk1/work/B03B0976/w/A7F508BE/e/JIT/HardwareIntrinsics/X86/X86Base/Pause_ro/Pause_ro.sh
Expected: True
Actual:   False


Stack trace
   at JIT_HardwareIntrinsics._X86_X86Base_Pause_ro_Pause_ro_._X86_X86Base_Pause_ro_Pause_ro_sh()
```

**Closed** 2021-12-03 03:02 UTC
Labels: arch-x86, os-linux, os-mac-os-x, os-windows, JitStress, arch-x64, area-CodeGen-coreclr, in pr
