### ISSUE TITLE
[browser][MT] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerWebSocketTest.WebSocketClient_CancelInDifferentThread

### ISSUE THREAD

**Issue by mkhamoyan** [dotnet/runtime#98344] opened 2024-02-13 09:49 UTC
### Error Blob

```json
{
  "ErrorMessage": "[FAIL] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerWebSocketTest.WebSocketClient_CancelInDifferentThread",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Reproduction Steps

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=563433

[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-98321-merge-88fb15401885469699/WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests/1/console.b404384d.log?helixlogtype=result)

```
[22:06:54] info: [STRT] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerWebSocketTest.WebSocketClient_CancelInDifferentThread(executor1: Main, executor2: JSWebWorker)
[22:06:54] info: [0x05fbe398-jsww 22:06:54.695] MONO_WASM: forceDisposeProxies done: 0 imports, 0 exports, 0 GCHandles, 0 JSHandles.
[22:06:59] info: STATE CUE CARD: (? means a positive number, usually 1 or 2, * means any number)
[22:06:59] info: 	0x0	- starting (GOOD, unless the thread is running managed code)
[22:06:59] info: 	0x1	- detached (GOOD, unless the thread is running managed code)
[22:06:59] info: 	0x2	- running (BAD, unless it's the gc thread)
[22:06:59] info: 	0x?03	- async suspended (GOOD)
[22:06:59] info: 	0x?04	- self suspended (GOOD)
[22:06:59] info: 	0x?05	- async suspend requested (BAD)
[22:06:59] info: 	0x6	- blocking (BAD, unless there's no suspend initiator)
[22:06:59] info: 	0x?07	- blocking async suspended (GOOD)
[22:06:59] info: 	0x?08	- blocking self suspended (GOOD)
[22:06:59] info: 	0x?09	- blocking suspend requested (GOOD in coop; BAD in hybrid)
[22:06:59] info: --thread 0xc678e0 id 0xdd56c [0] state 108
[22:06:59] info: --thread 0x206ac10 id 0x20ba5c8 [0] state 105
[22:06:59] info: --thread 0x2395768 id 0x2399170 [0] state 109
[22:06:59] info: --thread 0x28cd510 id 0x26b8030 [0] state 108
[22:06:59] info: --thread 0x2f8a950 id 0x2d88008 [0] state 109
[22:06:59] info: --thread 0x3714c30 id 0x350d3c0 [0] state 109
[22:06:59] info: --thread 0x3dc57b8 id 0x38ae0c0 [0] state 108
[22:06:59] info: --thread 0x47a4960 id 0x5684048 [0] state 109
[22:06:59] info: --thread 0x4502710 id 0x5db6058 [0] state 2  GC INITIATOR
[22:06:59] info: --thread 0x517ea88 id 0x5fbe398 [0] state 108
[22:06:59] info: WAITING for 1 threads, got 0 suspended
[22:06:59] fail: [0x05db6058-long 22:06:59.717] [MONO] /__w/1/s/src/mono/mono/utils/mono-threads.c:330 <disabled>
[22:06:59] fail: [0x000dd56c-main 22:06:59.718] MONO_WASM: Unhandled error: [object Object]
[22:06:59] fail: [0x000dd56c-main 22:06:59.719] MONO_WASM: Unhandled error: [object Object]
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=563433
**Error message validated:** `[[FAIL] System.Runtime.InteropServices.JavaScript.Tests.WebWorkerWebSocketTest.WebSocketClient_CancelInDifferentThread`]
**Result validation:** :x: Known issue did not match with the provided build.
**Validation performed at:** 2/13/2024 9:49:23 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by pavelsavara** [comment] 2024-02-13 10:23
duplicate of https://github.com/dotnet/runtime/issues/96190

**Closed by pavelsavara** 2024-02-13 10:23 UTC
Labels: arch-wasm, blocking-clean-ci, area-VM-threading-mono, Known Build Error, os-browser
