### ISSUE TITLE
[Uri] System.Uri handles certain character sequences starting with '%' inconsistently

### ISSUE THREAD

**Issue by agr** [dotnet/runtime#30818] opened 2019-09-10 21:14 UTC
It's a follow up to dotnet/runtime#23738.

```
>dotnet --version
3.0.100-preview9-014004
```

Repro steps:
1. `dotnet new console`
2. Paste the following code:
```C#
using System;

namespace uri_from_path_net3_test
{
    class Program
    {
        static void Main(string[] args)
        {
            var localPath = @"e:\%41foo%20bar%25.baz";
            var uri = new Uri(localPath);
            Console.WriteLine("{0}", uri.AbsoluteUri);
            Console.WriteLine("Original path: {0}", localPath);
            Console.WriteLine("Path from Uri: {0}", uri.LocalPath);
        }
    }
}
```
3. `dotnet run`

The output is:
```
file:///e:/Afoo%20bar%2525.baz
Original path: e:\%41foo%20bar%25.baz
Path from Uri: e:\Afoo bar%25.baz
```

There is no change in behavior since the previous issue. `System.Uri` still handles '%' characters in input string arbitrarily. Notice that in the first line of the output `%41`, `%20` and `%25` of the input string were processed in three different ways.

Ultimately, I expect to be able to recover the local paths from Uri form, i.e. the following code:
```
            var localPath = @"e:\%41foo%20bar%25.baz";
            var uri = new Uri(localPath);
            var anotherUri = new Uri(uri.AbsoluteUri);
            Console.WriteLine("Original path: {0}", localPath);
            Console.WriteLine("Path from Uri: {0}", anotherUri.LocalPath);
```
should produce same paths in both lines.

**Comment by MihaZupan** [comment] 2020-02-27 04:40
Duplicate of #27399

**Closed by MihaZupan** 2020-02-27 04:40 UTC
Labels: area-System.Net
