### ISSUE TITLE
[Perf] Regressions in Burgers.Test0

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#57087] opened 2021-08-09 20:37 UTC
This was found in a 5.0 -> 6.0 comparison. I noticed that this was never copied over to be investigated.

### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [c7fa2955e3f860f8070adea115f7277281228a2e](https://github.com/dotnet/runtime/commit/c7fa2955e3f860f8070adea115f7277281228a2e)
Compare | [ee3f7daed083477689a4c6240025afa45ffa3352](https://github.com/dotnet/runtime/commit/ee3f7daed083477689a4c6240025afa45ffa3352)

### Regressions in Burgers

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[Test0](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04/Burgers.Test0.html>) | 227.13 ms | 300.60 ms | 1.32 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_02_2021/refs/heads/master_x64_ubuntu%2018.04_Regression/Burgers_2.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/03_02_2021/refs/heads/master_x64_ubuntu%2018.04_Regression/Burgers.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'Burgers*'
```
<details>

.
### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-8fc2cd5f-8dc5-447e-95c9-8cdd533cf740fcb29594a684ab6b5/9af88c5c-06ec-4bc3-8994-46e9a9e3453e.zip?sv=2019-07-07&se=2021-03-28T15%3A18%3A38Z&sr=c&sp=rl&sig=zzcrBXD4WBJIUt4cUpTJmr7jf%2FBEa1vFQEShBlYW348%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-89686172-06a8-4ce4-b6b8-e81d97a5c9a05f2dc57b3a143d9ad/7ac225b6-1245-4069-a932-a5c9abd3bf29.zip?sv=2019-07-07&se=2021-03-29T00%3A40%3A34Z&sr=c&sp=rl&sig=e1r2xzSNHy56oEIv9goQBOXijCLUFKvy%2FgnwssOP3S4%3D>)

#### Burgers.Test2

```log
[173077567.563 ; 180818538.259) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[180818538.259 ; 188559508.954) | 
[188559508.954 ; 196300479.650) | 
[196300479.650 ; 204041450.346) | 
[204041450.346 ; 211782421.042) | 
[211782421.042 ; 217157535.712) | 
[217157535.712 ; 224898506.407) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[224898506.407 ; 235629468.257) | 
[235629468.257 ; 243618923.481) | @@@@@@@@@@@
```
#### Burgers.Test0

```log
[221800734.528 ; 229054539.920) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[229054539.920 ; 237545194.113) | @@@@@@@
[237545194.113 ; 246815564.573) | 
[246815564.573 ; 253034981.489) | 
[253034981.489 ; 262781984.527) | @@@@
[262781984.527 ; 272052354.987) | 
[272052354.987 ; 281322725.447) | 
[281322725.447 ; 290593095.907) | 
[290593095.907 ; 297131428.042) | 
[297131428.042 ; 303545307.882) | @@@@@@@@@@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by briansull** [comment] 2021-08-10 21:26
<html>
<body>


Compare | ee3f7daed083477689a4c6240025afa45ffa3352
-- | --



</body>
</html>

Baseline / Compare change hash indicates that this PR was responsible.  (Or possibly a previous PR on the same day or two)

Separate refactoring changes in 43250 (#48199)
 main (#48199)
 v6.0.0-preview.7.21377.19 
…
 v6.0.0-preview.3.21201.4
@echesakovMSFT
echesakovMSFT committed on Feb 26

**Comment by briansull** [comment] 2021-08-10 21:30
Possibly related regression:
#49163

**Comment by EgorBo** [comment] 2021-08-12 07:01
> This was found in a 5.0 -> 6.0 comparison. I noticed that this was never copied over to be investigated.

@DrewScoggins that comparison was also made on Ubuntu?
I can't reproduce this issue locally on both ubuntu-x64 and win-x64 🙁 

The histogram states that the only commit that could affect this benchmark was [Enable CSE for floating-point constants (#44419)](https://github.com/dotnet/runtime/commit/70676fd9631e0475ebc18e5903fec4549e888226)

![image](https://user-images.githubusercontent.com/523221/129151298-70eb5cb2-b000-461c-8ef7-65def21ebfe2.png)

and indeed, Burgers benchmark do a lot of floating-point operations with constants so, in theory, CSE could lead to spills inside loops for loop-carried dependencies, but I wasn't able to reproduce any noticeable differences before after that commit (the issues states it became 30% slower). Neither I could reproduce it for .NET 5.0 vs .NET 6.0P7, performance results are the same.

Here is the codegen diff: https://www.diffchecker.com/XtHoG3rP
there are some oddities like a spill and some loads aren't "contained" inside the main loop, but I still don't see any difference in final report BDN makes for me.

**Comment by JulieLeeMSFT** [comment] 2021-08-13 22:54
> @DrewScoggins that comparison was also made on Ubuntu?

Ping @DrewScoggins since we are trying to fix issues before RC1 snap on 8/17.

**Comment by DrewScoggins** [comment] 2021-08-13 22:57
I have been working with @EgorBo on this offline. I think he has everything he needs from me, but he can let me know if he needs anything else.

**Comment by EgorBo** [comment] 2021-08-14 08:43
I managed to get a stable repro (10-15% regression) after some tuning in my BIOS, so here is the asm diff: https://www.diffchecker.com/9StkXdFY so it's indeed a regression caused by https://github.com/dotnet/runtime/commit/70676fd9631e0475ebc18e5903fec4549e888226

we had 
```asm
vmulsd    xmm0,xmm0,qword ptr [7F1BA7074F90] ; last one is a const that is loaded from data section
```
but after CSE-for-floats PR we now have:
```asm
vmovsd    xmm6,qword ptr [rbp-50]
vmulsd    xmm0,xmm0,xmm6
```
So we hoisted the const but it was spilled to stack so in theory we shouldn't have hoisted/CSE it at all in these conditions (lots of computations/registers are busy)

/cc @briansull @kunalspathak

**Comment by AndyAyersMS** [comment] 2021-08-14 16:06
There are no callee-save XMMs on SysV, so on such platforms we should be pretty reluctant to do a float CSE that crosses calls.

Are we sure we're checking the right conditions in the CSE heuristics?

**Comment by JulieLeeMSFT** [comment] 2021-08-14 16:33
> Are we sure we're checking the right conditions in the CSE heuristics?

CC @briansull

**Comment by EgorBo** [comment] 2021-08-14 19:18
![image](https://user-images.githubusercontent.com/523221/129457967-20b2eb4e-fb14-43c0-9f94-e1cd6dd33133.png)

while on Windows we save xmm0 to xmm6 before the loop.

**Comment by AndyAyersMS** [comment] 2021-08-14 21:39
More apropos:
```C#
using System;
using System.Runtime.CompilerServices;

class X
{
     public static float F(int N)
     {
          float result = 0.0F;

          for (int i = 0; i < N; i++)
          {
             result += 3.14F;
             G();
             result += 3.14F;
          }
          return result;
           
     }

    [MethodImpl(MethodImplOptions.NoInlining)]
    public static void G() {}
}
```
Win X64
```asm
; Assembly listing for method X:F(int):float
; Emitting BLENDED_CODE for X64 CPU with AVX - Windows
; optimized code
; rsp based frame
; partially interruptible
; No PGO data
; Final local variable assignments
;
;  V00 arg0         [V00,T01] (  4,  7   )     int  ->  rsi         single-def
;  V01 loc0         [V01,T02] (  6, 18   )   float  ->  mm6        
;  V02 loc1         [V02,T00] (  4, 13   )     int  ->  rdi        
;  V03 OutArgs      [V03    ] (  1,  1   )  lclBlk (32) [rsp+00H]   "OutgoingArgSpace"
;  V04 cse0         [V04,T03] (  3,  9   )   float  ->  mm7         "CSE - aggressive"
;
; Lcl frame size = 72

G_M28134_IG01:
       push     rdi
       push     rsi
       sub      rsp, 72
       vzeroupper 
       vmovaps  qword ptr [rsp+30H], xmm6
       vmovaps  qword ptr [rsp+20H], xmm7
       mov      esi, ecx
						;; bbWeight=1    PerfScore 9.50
G_M28134_IG02:
       vxorps   xmm6, xmm6
       xor      edi, edi
       test     esi, esi
       jle      SHORT G_M28134_IG04
       vmovss   xmm7, dword ptr [reloc @RWD00]
						;; bbWeight=1    PerfScore 3.83
G_M28134_IG03:
       vaddss   xmm6, xmm6, xmm7
       call     X:G()
       vaddss   xmm6, xmm6, xmm7
       inc      edi
       cmp      edi, esi
       jl       SHORT G_M28134_IG03
						;; bbWeight=4    PerfScore 34.00
G_M28134_IG04:
       vmovaps  xmm0, xmm6
						;; bbWeight=1    PerfScore 0.25
G_M28134_IG05:
       vmovaps  xmm6, qword ptr [rsp+30H]
       vmovaps  xmm7, qword ptr [rsp+20H]
       add      rsp, 72
       pop      rsi
       pop      rdi
       ret      
						;; bbWeight=1    PerfScore 10.25
RWD00  	dd	4048F5C3h		;      3.14
```
SysV X64
```asm
; Assembly listing for method X:F(int):float
; Emitting BLENDED_CODE for X64 CPU with AVX - Unix
; optimized code
; rbp based frame
; partially interruptible
; No PGO data
; invoked as altjit
; Final local variable assignments
;
;  V00 arg0         [V00,T01] (  4,  7   )     int  ->  rbx         single-def
;  V01 loc0         [V01,T02] (  6, 18   )   float  ->  [rbp-14H]  
;  V02 loc1         [V02,T00] (  4, 13   )     int  ->  r14        
;# V03 OutArgs      [V03    ] (  1,  1   )  lclBlk ( 0) [rsp+00H]   "OutgoingArgSpace"
;  V04 cse0         [V04,T03] (  3, 12   )   float  ->  [rbp-18H]   spill-single-def "CSE - aggressive"
;
; Lcl frame size = 16

G_M28134_IG01:
       push     rbp
       push     r14
       push     rbx
       sub      rsp, 16
       vzeroupper 
       lea      rbp, [rsp+20H]
       mov      ebx, edi
						;; bbWeight=1    PerfScore 5.00
G_M28134_IG02:
       vxorps   xmm0, xmm0
       xor      r14d, r14d
       test     ebx, ebx
       jle      SHORT G_M28134_IG04
						;; bbWeight=1    PerfScore 1.83
G_M28134_IG03:
       vmovss   xmm1, dword ptr [reloc @RWD00]
       vmovss   dword ptr [rbp-18H], xmm1
       vaddss   xmm0, xmm0, xmm1
       vmovss   dword ptr [rbp-14H], xmm0
       call     X:G()
       vmovss   xmm1, dword ptr [rbp-18H]
       vaddss   xmm0, xmm1, dword ptr [rbp-14H]
       inc      r14d
       cmp      r14d, ebx
       jl       SHORT G_M28134_IG03
						;; bbWeight=4    PerfScore 62.00
G_M28134_IG04:
       add      rsp, 16
       pop      rbx
       pop      r14
       pop      rbp
       ret      
						;; bbWeight=1    PerfScore 2.75
RWD00  	dd	4048F5C3h		;      3.14
```
Not only is the latter CSE harmful, it's made even worse as we don't hoist its def out of the loop either....

**Comment by EgorBo** [comment] 2021-08-14 22:21
@AndyAyersMS in your case it seems we give up on hoisting the def here: 
https://github.com/dotnet/runtime/blob/53ebce3c5e10c6ede66e7ece61c466a97a2a9574/src/coreclr/jit/optimizer.cpp#L6013-L6020

where availRegCount is 0 because `CNT_CALLEE_SAVED_FLOAT` is `0` for SysV and we don't use `CNT_CALLEE_TRASH_FLOAT` because we have a call in the loop.

**Comment by EgorBo** [comment] 2021-08-14 22:28
A fix? https://github.com/EgorBo/runtime-1/commit/00f9eab9591073fea6070a6b1f2da65a0046622c, Diff: https://www.diffchecker.com/wakOETMr

**Comment by AndyAyersMS** [comment] 2021-08-14 22:29
Right, not hoisting is reasonable. But CSEing is not. Not hoisting and then CSEing is the worst of all. Hoist and CSE need to be on the same page.

optcse.cpp never refers to `CNT_CALLEE_SAVED_FLOAT` -- seems like it should.

**Comment by AndyAyersMS** [comment] 2021-08-14 22:32
Blocking all non-hoistable CSEs is probably sub-optimal -- if all uses are one one side of the call or the other then a CSE will likely pay off even if the def is not hoisted. But we should not be doing cross-call CSEs of cheap float trees on SysV.

**Closed** 2021-08-17 15:06 UTC
Labels: os-linux, tenet-performance, tenet-performance-benchmarks, arch-x64, area-CodeGen-coreclr, in pr
