### ISSUE TITLE
Reflection-emit'ing invalid IL results in debug assert in System.Reflection.Metadata when executed

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#1642] opened 2020-01-12 03:09 UTC
```
  Process terminated. Assertion failed.
     at System.Reflection.Metadata.MethodDebugInformation..ctor(MetadataReader reader, MethodDebugInformationHandle handle)
     at System.Reflection.Metadata.MetadataReader.GetMethodDebugInformation(MethodDebugInformationHandle handle)
     at System.Diagnostics.StackTraceSymbols.GetSourceLineInfo(Assembly assembly, String assemblyPath, IntPtr loadedPeAddress, Int32 loadedPeSize, IntPtr inMemoryPdbAddress, Int32 inMemoryPdbSize, Int32 methodToken, Int32 ilOffset, String& sourceFile, Int32& sourceLine, Int32& sourceColumn)
     at System.Diagnostics.StackFrameHelper.InitializeSourceInfo(Int32 iSkip, Boolean fNeedFileInfo, Exception exception)
     at System.Diagnostics.StackTrace.CaptureStackTrace(Int32 skipFrames, Boolean fNeedFileInfo, Exception e)
     at System.Diagnostics.StackTrace.InitializeForException(Exception exception, Int32 skipFrames, Boolean fNeedFileInfo)
     at System.Diagnostics.StackTrace..ctor(Exception e, Boolean fNeedFileInfo)
     at System.Exception.GetStackTrace(Exception e)
     at System.Exception.get_StackTrace()
     at Xunit.Sdk.ExceptionUtility.ConvertExceptionToFailureInformation(Exception ex, Int32 parentIndex, List`1 exceptionTypes, List`1 messages, List`1 stackTraces, List`1 indices)
     at Xunit.Sdk.ExceptionUtility.ConvertExceptionToFailureInformation(Exception ex)
     at Xunit.Sdk.TestFailed..ctor(ITest test, Decimal executionTime, String output, Exception ex)
     at Xunit.Sdk.TestRunner`1.RunAsync()
```

https://github.com/dotnet/runtime/blob/afc21e51af60a4d2cb11a1081fb38b1e3a8df0a2/src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/PortablePdb/MethodDebugInformation.cs#L22-L29

**Comment by jkotas** [comment] 2020-01-12 04:42
Duplicate of https://github.com/dotnet/corefx/issues/30261

**Closed by jkotas** 2020-01-12 04:42 UTC
Labels: area-System.Reflection.Metadata, untriaged
