### ISSUE TITLE
DebuggerSupport = false crashes ILC when publishing with NativeAOT (.NET 8 P4)

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#86386] opened 2023-05-17 14:38 UTC
### Description

Was just trying .NET 8 Preview 4 on my NativeAOT sample for ComputeSharp and noticed it fails to build if `<DebuggerSupport>` is disabled. Removing it works around the issue, but this is a regression compared to .NET 7, where the option works fine.

cc. @MichalStrehovsky

### Reproduction Steps

- Checkout to https://github.com/Sergio0694/ComputeSharp/commit/2289bcc7c74b8aab899ca0a54391808bcd18841a
- Build the sample (from PowerShell):
```powershell
$env:COMPUTESHARP_SWAPCHAIN_CLI_PUBLISH_AOT='true';
dotnet publish samples\ComputeSharp.SwapChain.Cli\ComputeSharp.SwapChain.Cli.csproj -c Release -f net8.0 -r win-x64
```

### Expected behavior

Should build correctly.

### Actual behavior

ILC crashes when building:

> "C:\Users\sergiopedri\.nuget\packages\microsoft.dotnet.ilcompiler\8.0.0-preview.4.23259.5\build\Microsoft.NETCore.Native
.targets(270,5): error MSB3073: The command ""C:\Users\sergiopedri\.nuget\packages\runtime.win-x64.microsoft.dotnet.ilc
ompiler\8.0.0-preview.4.23259.5\tools\\ilc" @"obj\Release\net8.0\win-x64\native\computesharp.cli.ilc.rsp"" exited with
code 1. [C:\Users\sergiopedri\git\ComputeSharp\samples\ComputeSharp.SwapChain.Cli\ComputeSharp.SwapChain.Cli.csproj]"

### Regression?

Yes. Works fine on .NET 7.

### Known Workarounds

Not disabling debugger support, which introduces a marginal binary size regression.

### Configuration

8.0.100-preview.4.23260.5

**Comment by filipnavara** [comment] 2023-05-17 14:40
It would be nice to see full error. I remember seeing a bug where the feature flag was passed twice on the command line and it crashed early on while processing the command line.

**Comment by Sergio0694** [comment] 2023-05-17 14:47
I think that might actually be the case, I'm seeing this further up in the output:

```powershell
EXEC : error : An item with the same key has already been added. Key: System.Diagnostics.Debugger.IsSupported [C:\Users
\sergiopedri\git\ComputeSharp\samples\ComputeSharp.SwapChain.Cli\ComputeSharp.SwapChain.Cli.csproj]
  System.ArgumentException: An item with the same key has already been added. Key: System.Diagnostics.Debugger.IsSuppor
  ted
     at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException[T](T) + 0x14
     at System.Collections.Generic.Dictionary`2.TryInsert(TKey, TValue, InsertionBehavior) + 0x271
     at System.Collections.Generic.Dictionary`2.AddRange(IEnumerable`1) + 0x13b
     at ILCompiler.FeatureSwitchManager..ctor(ILProvider, Logger, IEnumerable`1) + 0x37
     at ILCompiler.Program.Run() + 0xeac
     at ILCompiler.ILCompilerRootCommand.<>c__DisplayClass206_0.<.ctor>b__0(InvocationContext context) + 0x20c
```

**Comment by jkotas** [comment] 2023-05-17 14:48
Duplicate of https://github.com/dotnet/runtime/issues/86186

**Closed by jkotas** 2023-05-17 14:48 UTC
Labels: untriaged, area-NativeAOT-coreclr
