### ISSUE TITLE
[API Proposal]: add high precision maths functions like log1p

### ISSUE THREAD

**Issue by polijp** [dotnet/runtime#64184] opened 2022-01-24 06:58 UTC
### Background and motivation

.net has been added methods for high performance computation and also methods for higher precision math functions.
In C++, you have high precision functions like log1p that computes log(1+p) with high precision.
This precision is needed is some mathematical applications including machine learning.

### API Proposal

```c#
public static class Math
{
    public double Log1p(double x) …
    public double Log1p(double x, double base) …
}

public static class MathF
{
    public float Log1p(float x) …
    public float Log1p(float x, float base) …
}
```

### API Usage

```C#
Console.WriteLine(Math.Log1p(0.001));

Console.WriteLine(MathF.Log1p(0.001f));
```

**Comment by huoyaoyuan** [comment] 2022-01-24 12:25
This is covered by #20137, `Log1P` is renamed to  `LogP1` and already approved.
Could you explain more about the overload with `base`? It seems not covered by IEEE754:2019, and it is not clear for how to implement it.

**Comment by polijp** [comment] 2022-01-24 13:42
Oh thank you, I've missed it.
The idea of the base argument is the same as in Math.Log(double x, double newBase).
If one needs to compute the logarithm of 1+x in base 2 or in base 10, it just needs to be written Math.LogP1(x, 2) instead of Math.LogP1(x)/Math.Log(2).

**Comment by Joe4evr** [comment] 2022-01-24 14:47
> Oh thank you, I've missed it. The idea of the base argument is the same as in Math.Log(double x, double newBase). If one needs to compute the logarithm of 1+x in base 2 or in base 10, it just needs to be written Math.LogP1(x, 2) instead of Math.LogP1(x)/Math.Log(2).

Do you need anything other than base 2 and 10 (which seem to be covered by `Log2P1` and `Log10P1` respectively)? Is doing this operation in arbitrary bases in accordance with the IEEE spec?

**Comment by polijp** [comment] 2022-01-24 19:53
You're right, it is mainly with base 2 or 10. It may be enough for most implementations.

**Comment by huoyaoyuan** [comment] 2022-01-25 14:21
It can be also hard to write a precise implementation for arbitrary base. The could be some tricks applicable to base 2.

**Comment by tannergooding** [comment] 2022-04-29 18:47
Closing as duplicate of #20137

**Closed by tannergooding** 2022-04-29 18:47 UTC
Labels: api-suggestion, area-System.Numerics, untriaged
