### ISSUE TITLE
[NativeAOT] System.Linq.Expressions size regression

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#89527] opened 2023-07-26 20:58 UTC
### Description

The ["Stage2" / "TodosAPI" ASP.NET benchmark app](https://github.com/aspnet/Benchmarks/tree/main/src/BenchmarksApps/TodosApi)'s NativeAOT size has regressed in recent builds.

![image](https://github.com/dotnet/runtime/assets/8291187/597f3dbb-01ad-473c-b7e9-73d16d199177)

As you can see, the size increased from `31 MB` to `41 MB`.

Looking at the mstat diffs, I see most of the size increase coming from System.Linq.Expressions. This leads me to believe this was regressed by #89308.

### Configuration

All

### Regression?

Yes

### Data

The before and after mstat files can be found in:
[MStatFiles.zip](https://github.com/dotnet/runtime/files/12177117/MStatFiles.zip)

### Analysis

Diffing the attached mstat files in sizoscope shows:

![image](https://github.com/dotnet/runtime/assets/8291187/34bbc9dd-4894-4f96-b16f-c90d470ff0a7)

cc @MichalStrehovsky @ivanpovazan

**Comment by MichalStrehovsky** [comment] 2023-07-27 05:32
Looks like we no longer trim the Ref.Emit backend or the `CanCreateArbitraryDelegates` code path. It likely is from https://github.com/dotnet/runtime/pull/89308. I think we'll need to undo removal of the other two switches and only leave the CanEmitObjectArrayDelegate change. (The two switches can/should stay as `--feature`).

**Comment by ivanpovazan** [comment] 2023-07-27 07:13
That is a bit unexpected as both:
https://github.com/dotnet/runtime/blob/bcb608e3d21344a0bb7c3399f060143504bbf475/src/libraries/System.Linq.Expressions/src/System/Linq/Expressions/LambdaExpression.cs#L29
and
https://github.com/dotnet/runtime/blob/bcb608e3d21344a0bb7c3399f060143504bbf475/src/libraries/System.Linq.Expressions/src/System/Linq/Expressions/Interpreter/CallInstruction.cs#L19
are guarded by `IsDynamicCodeSupported` which should be set to `false` in NativeAOT scenarios:
https://github.com/dotnet/runtime/blob/bcb608e3d21344a0bb7c3399f060143504bbf475/src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.targets#L41

I will try to repro and revert if needed.

**Comment by MichalStrehovsky** [comment] 2023-07-27 07:59
Dead branch removal rules are undocumented and unreliable. One needs to basically always re-test if this is shuffled. I think the problem here is that if we're in a situation where there is `if (Something()) { ... }` and `Something()` becomes obviously constant only after inspecting _that_ method body, the branch will not be removed by NativeAOT. It will be removed by ILLinker if it runs before NativeAOT because ILLinker does propagate across methods but we don't run with ILLinker outside AppleMobile.

**Comment by ivanpovazan** [comment] 2023-07-27 14:17
I have verified that the regression is introduced with: https://github.com/dotnet/runtime/pull/89308 
I will try to get a fix for this soon - targeting rc1.
If it is urgent to get steady perf reports, I can revert the change and apply a proper fix afterwards.

**Closed** 2023-07-31 02:22 UTC
Labels: tenet-performance, in-pr, area-NativeAOT-coreclr
