### ISSUE TITLE
.NET 9: Unhandled exceptions in background threads reported with empty managed frames

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/runtime#101729] opened 2024-04-30 16:55 UTC
### Description

In .NET 9 preview 3, there is a regression where the target process stops at a point where the ICorDebug stack walk interfaces report a single native chain with reason `CHAIN_THREAD_START (0x00000040)`. Previously these exceptions would go unhandled with the managed code still on the stack.

### Reproduction Steps

1. dotnet new console
2. Replace program.cs with the following code
3. Run it under a managed debugger that is NOT configured to stop when `NotImplementedException` is thrown
4. The debugger will stop when the exception goes unhandled

Program.cs:
```csharp
Thread thread = new Thread(() => {
    throw new NotImplementedException(); // should crash here
});
thread.Start();
thread.Join();
```

### Expected behavior

Call stack should have a managed frame

### Actual behavior

No managed frames

### Regression?

Definitely a regression from .NET 8. I believe it first appeared in preview 3.

### Known Workarounds

None

### Configuration

Problem appears on Windows, Mac and Linux

**Comment by tommcdon** [comment] 2024-05-06 18:54
Verified setting the `DOTNET_LegacyExceptionHandling=1` environment variable reverts to correct behavior, so this seems to be caused by the new EH in .NET 9.  Adding @janvorli

**Comment by tommcdon** [comment] 2024-05-21 14:26
Closing via https://github.com/dotnet/runtime/pull/102470

**Closed by tommcdon** 2024-05-21 14:26 UTC
Labels: area-Diagnostics-coreclr
