### ISSUE TITLE
Add a capability to C#/CLR runtime to report which variable caused Null pointer exception, similar to Java 14 "Helpful NullPointerException". https://openjdk.java.net/jeps/358

### ISSUE THREAD

**Issue by madhub** [dotnet/runtime#62596] opened 2021-12-09 18:34 UTC
### Discussed in https://github.com/dotnet/runtime/discussions/49960

<div type='discussions-op-text'>

<sup>Originally posted by **madhub** March 21, 2021</sup>
Does C#/CLR runtime has  something similar to Java 14 "[Helpful NullPointerException](https://openjdk.java.net/jeps/358)". https://openjdk.java.net/jeps/358
Very useful feature to find exact object throwing Null reference</div>

**Comment by filipnavara** [comment] 2021-12-09 19:15
This is technically duplicate of issue #3858.

**Comment by tommcdon** [comment] 2021-12-10 23:04
Closing as this is a duplicate of #3858.  
Although NullReferenceException object itself in .NET does not contain the name of the variable that was null, you can get to that information by either live debugging or opening a dump of a process that crashed with NullReferenceException in the Visual Studio: https://docs.microsoft.com/visualstudio/debugger/exception-helper?view=vs-2022.

**Closed by tommcdon** 2021-12-10 23:04 UTC
Labels: area-Diagnostics-coreclr, untriaged
