### ISSUE TITLE
Problem when adding null as "Cookie" in HttpHeaders.Add

### ISSUE THREAD

**Issue by misaqsaadat** [dotnet/runtime#102697] opened 2024-05-26 09:14 UTC
Hello.
I'm not sure if it is an issue or not.
I was working on an old library (.Net 5)
I try to update it to .Net 8. but I got an exception in this line :

content.Headers.Add("Cookie", session);
(content is HttpContent and session is null)
in .Net 5 (and 6) it works fine without exception. but in .Net 8 (and 7) it throw FormatException.
I checked .Net codes and find this commit that produce this problem.
https://github.com/dotnet/runtime/pull/67455/commits/83cbf0b7ee7ebdcd758f0a56dfc412d8b4a15dfa#diff-5c25411b2e45811bb47c6b8d884f26228ccd9a792859c31b8cd8b54c92ac329a

if parser be null no exception will thrown. but in updated code it have a parser.

It make many hours of my time to find the problem. and I fix it. but shouldn't be some alarm (like breaking change) for developers that are already using it?

this code works fine in .Net 6. but throws exception in .Net 7:

    static void Main(string[] args)

    {

        HttpContent content = new StringContent("{}", Encoding.UTF8, "application/json");

        string cookie = null;

        content.Headers.Add("Cookie", cookie);

    }

**Comment by colejohnson66** [comment] 2024-05-26 17:49
What would a null cookie value even mean?

**Comment by MihaZupan** [comment] 2024-05-26 19:33
Duplicate of #99416

**Comment by ManickaP** [comment] 2024-05-27 07:24
Closing as dupe.

**Closed by ManickaP** 2024-05-27 07:24 UTC
Labels: area-System.Net.Http, untriaged
