### ISSUE TITLE
EnC: ExecutionEngineException after edit in struct returning method

### ISSUE THREAD

**Issue by davidwengier** [dotnet/runtime#46274] opened 2020-12-20 21:30 UTC
**Version:**

CoreCLR 3.1 and Desktop CLR 4.7.1

**Steps to Reproduce:**

```cs
namespace DebuggerTest
{
    public class GenericStructReturn
    {
        public static void Main() { System.Console.WriteLine(F()); }
        public static S<object, object> F()
        {
            return new S<object, object>("Hello", "");   // Breakpoint on this line
        }
    }

    public struct S<T1, T2>
    {
        private T1 o1;
        private T2 o2;

        public S(T1 o1, T2 o2)
        {
            this.o1 = o1;
            this.o2 = o2;
        }

        public override string ToString()
        {
            return o1 + " " + o2;
        }
    }
}
```

1. In the code above, place a breakpoint inside the F() method
2. F5
3. When the breakpoint is hit, put a string in for the second constructor parameter
4. F5
5. Observe the crash

Looked into it from the Roslyn side and seems to be a CLR bug.

From feedback ticket https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1246874
/cc @tmat

**Comment by tommcdon** [comment] 2020-12-22 20:45
@davmason

**Comment by davmason** [comment] 2021-01-08 11:15
I confirmed it still reproes on 5.0.

I haven't dug in to it super far, we crash in EECodeManager::FixContextForEnC because we write off the end of an array here: https://github.com/dotnet/runtime/blob/6299cefa0365e84822a53425b1a9af1e5d70917a/src/coreclr/vm/eetwain.cpp#L1097

I will have to debug further and figure out why we are misbehaving for generic methods. It will be at least a couple days before I get back to it.

**Comment by davmason** [comment] 2021-01-09 01:09
@davidwengier  The contract here is kind of weird since Roslyn is expected to do the detection of a bad edit and the runtime does no error checking, but after some more research and discussion within the team, I think this is an [unsupported scenario](https://github.com/dotnet/roslyn/blob/master/docs/wiki/EnC-Supported-Edits.md#not-supported-edits) because of the edit to a generic. The right fix here is to block the edit on the compiler side.

**Comment by jkotas** [comment] 2021-01-09 01:13
The method being modified is not generic. This should be supported.

**Comment by jkotas** [comment] 2021-01-09 01:33
I see the same crash with non-generic `S` and same repro steps: 
```csharp
namespace DebuggerTest
{
    public class GenericStructReturn
    {
        public static void Main() { for (; ; ) { System.Console.WriteLine(F()); }  }
        public static S F()
        {
            return new S("Hello", "xxx");   // Breakpoint on this line
        }
    }

    public struct S
    {
        private string o1;
        private string o2;

        public S(string o1, string o2)
        {
            this.o1 = o1;
            this.o2 = o2;
        }

        public override string ToString()
        {
            return o1 + " " + o2;
        }
    }
}
```

**Comment by jkotas** [comment] 2021-01-09 01:37
I think that the special hidden locals (like `RETBUF_ILNUM`) are not handled correctly. This line: 

https://github.com/dotnet/runtime/blob/6299cefa0365e84822a53425b1a9af1e5d70917a/src/coreclr/vm/eetwain.cpp#L1097

should be `oldMethodVarsSorted[varNumber + unsigned(-ICorDebugInfo::UNKNOWN_ILNUM)] = *pOldVar;`. Similar for other places that index info the MethodVarsSorted arrays.

**Comment by davmason** [comment] 2021-03-03 22:16
We talked about this today during triage, since it reproes back to desktop we are moving it out to future.

**Comment by tmat** [comment] 2021-03-03 22:25
I don't understand why the fact that it reproes on desktop has any impact on scheduling of the fix. We are spending a lot of effort on improving EnC/Hot Reload experience for .NET 6. This issue is relevant to this effort.

**Comment by davmason** [comment] 2021-03-03 23:34
The reasoning was that there are broader areas we could spend engineering effort to improve the experience as a whole, and this is more of a corner case.

cc @tommcdon @noahfalk

**Comment by jkotas** [comment] 2021-03-04 00:31
- This was filled by a customer via VS feedback. 
- The customer repro actually used tuples. Tuples were not a thing in .NET Framework, but they are gaining popularity in .NET Core. It can explain why have not seen it in .NET Framework, but it showed up on the radar now.

**Comment by noahfalk** [comment] 2021-03-05 03:39
Thanks, the connection to Tuples is good context that went unnoticed during the triage meeting : ) I'm going to go ahead and return this to .NET 6, but if it turns out the fix isn't easy then we may still reach out looking for telemetry or a more specific connection to a canonical Hot Reload scenario.

> improving EnC/Hot Reload experience for .NET 6. This issue is relevant to this effort.

That wasn't too apparent in the original bug report but thanks for the clarification : ) In general I think @mikem8361 has been focusing on work needed for new Hot Reload experiences. If this bug is at all representative of a broader desire to use Hot Reload as a time to revisit pre-existing EnC bugs and fix them thats probably a good discussion to have with @mikem8361 and @tommcdon.

**Comment by noahfalk** [comment] 2021-03-05 03:43
@tommcdon @mikem8361 - Mike should this be reassigned to you? I don't recall how it landed on David : )

**Comment by stephentoub** [comment] 2021-03-05 03:49
> If this bug is at all representative of a broader desire to use Hot Reload as a time to revisit pre-existing EnC bugs and fix them thats probably a good discussion to have

I expect there will be others. ;-)

cc: @danroth27, @LyalinDotCom

**Comment by davmason** [comment] 2021-03-15 21:05
Assigning to @mikem8361 per Noah's comments above

**Comment by cosborne83** [comment] 2021-06-14 19:51
Having looked at this issue on the back of a [StackOverflow question](https://stackoverflow.com/questions/67829796/why-do-i-get-fatalexecutionengineerror-when-breakpoint-editing-parameters-to-sys/67959026), it appears to result from `varNumber` not being treated as a signed value when indexing into [`oldMethodVarsSorted`](https://github.com/dotnet/runtime/blob/17481fef502ee6aed6f9e8fc76e45bb5863c68b5/src/coreclr/vm/eetwain.cpp#L1097)/[`newMethodVarsSorted`](https://github.com/dotnet/runtime/blob/17481fef502ee6aed6f9e8fc76e45bb5863c68b5/src/coreclr/vm/eetwain.cpp#L1149).

As a result, for special vars with negative `varNumber`s, instead of placing them in the space reserved at the beginning of the corresponding `oldMethodVarsSortedBase`/`newMethodVarsSortedBase` arrays for special vars, it is treated as a large positive index way off the end of the array.

Hope this helps.

**Comment by noahfalk** [comment] 2021-06-14 20:34
@cosborne83 - thanks both for connecting this to the StackOverflow issue and doing some excellent detective work in the code! Much appreciated!

**Comment by mikem8361** [comment] 2021-07-26 19:15
I haven't tried ENC under the debugger yet, but with hot reload/dotnet watch it seems that the non-generic test case from Jan works without any failure or exceptions but the original generic struct test case doesn't register any changes at all under dotnet watch:

```
watch : File changed: c:\sd\builds\customattr\Program.cs.
watch : No deltas modified. Applying changes to clear diagnostics.
watch : No hot reload changes to apply.
watch : Hot reload change handled in 3524.0177ms.
```

/cc: @pranavkm

**Comment by mikem8361** [comment] 2021-07-26 19:23
As it turns out, the eetwain.cpp FixContextAndResume function with the indexing problem is only called for ENC under the debugger for on-stack replacement which never happens under hot-reload. 

I'll still spent the time to investigate this issue under ENC of course.

**Comment by tommcdon** [comment] 2021-08-16 21:30
This bug is specific to the on-stack replacement in EnC and does not affect Hot Reload.  Moved to .NET 7.

**Comment by davidwengier** [comment] 2021-12-08 23:10
Just duped another feedback issue against this https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1447618 just to add some weight to the tuples argument :)

**Comment by davidwengier** [comment] 2022-02-16 00:50
Tuples again :)
https://developercommunity.visualstudio.com/t/Hot-ReloadEdit-and-Continue-Unhandled-E/1662269

**Comment by tommcdon** [comment] 2022-02-16 17:25
Thanks for the feedback @davidwengier!  This issue is currently on our backlog, but there are some higher priority items in front of it at the moment.

**Comment by calgagi** [comment] 2022-03-11 19:09
Tuple issue showing up again: https://developercommunity.visualstudio.com/t/Unable-to-set-statement-in-local-functio/1672199

**Comment by mikelle-rogers** [comment] 2022-07-21 14:37
Fixed with https://github.com/dotnet/runtime/pull/72255#pullrequestreview-1040653231

**Closed by mikelle-rogers** 2022-07-21 14:37 UTC
Labels: area-Diagnostics-coreclr
