### ISSUE TITLE
ExcecutionEngineException when using StringBuilder on long strings

### ISSUE THREAD

**Issue by delmyers** [dotnet/runtime#88199] opened 2023-06-29 16:07 UTC
### Description

This issue was originally reported to Visual Studio (https://developercommunity.visualstudio.com/t/Prevent-using-precompiled-images-in-de/10363031) because it seems to only reproduce when turning off precompiled images under the debugger.

### Reproduction Steps

1) Create a simple dotnet 7 console application with the following code:

```csharp
var count = 100000;
_ = string.Join(" ", Enumerable.Range(0, count).Select(_ => "Hello world!"));
```

2) In Visual Studio, turn on the option in Tools > Options > Debugging > General > "Prevent using precompiled images..."

3) Start debugging.

### Expected behavior

The application runs to completion.

### Actual behavior

Either an ArgumentOutOfRangeException or an ExecutionEngineException is thrown.

### Configuration

Using dotnet 7.0.5, and the latest dotnet 8 preview.
Windows 11 x64

### Other information

I think that it might be due to an overflow error while computing the length of the underlying span that is being used by the StringBuilder.

This repros in both dotnet 7, and dotnet 8 preview, though the location that the error is thrown from in dotnet 8 is different. I have heap dumps of the crashing processes in dotnet 7. I can make some for dotnet 8 if necessary as well.

**Comment by stephentoub** [comment] 2023-06-29 16:44
It looks like this is hitting some kind of corruption.  Just looking at this running on a recent .NET 8 build, we get to a point where the `ValueStringBuilder`'s buffer is ~128K and we need to grow, so we call `Grow(s.Length)`, and `Grow` ends up getting called with an impossible value, e.g. `-615112336`.

**Comment by rwasef1830** [comment] 2023-06-29 17:07
Here's a little tidbit that might help @stephentoub adding ToList on the enumerable call masks / solves the issue.

**Comment by tommcdon** [comment] 2023-06-29 18:58
I am suspecting that this is a JIT/codegen issue as the issue also only reproduces if `Suppress JIT Optimization on module load (Managed only)` under Debug->Options in VS is checkboxed.  Adding @BruceForstall from the codegen team for thoughts.

![image](https://github.com/dotnet/runtime/assets/12520929/a9bc4457-73d9-4c75-8910-937a3179a0a2)

**Comment by jkotas** [comment] 2023-06-29 20:38
The crash seems to be caused by corrupted stack or invalid unwind info generated by the JIT.

Running the repro with checked runtime fails with assert in the JIT:
```
Assert failure(PID 47796 [0x0000bab4], Thread: 47852 [0xbaec]): Assertion failed 'compCanHavePatchpoints()' in 'System.String:Replace(System.String,System.String):System.String:this' during 'Importation' (IL size 353; hash 0xee849cf8; Tier0)
```

To run it with checked runtime, I have done self-contained publish of the app, overwrote the runtime .dlls with my local checked build and used `start devenv /debugexe <path to .exe>` to launch the debug session.

The crash does not repro with tiered compilation disabled.

**Comment by AndyAyersMS** [comment] 2023-06-29 22:57
This reminds me of a bug @hoyosjs was asking me about internally, which I could never repro myself.

In that case the VM appeared to be passing two conflicting flags to the JIT : `CORJIT_FLAG_TIER0` and `CORJIT_FLAG_DEBUG_CODE`. This confuses the JIT. because in one place it doesn't think patchpoints are possible, and in another it thinks they are possible.

Because of this, in release the JIT decides to put patchpoints into a method wth a localloc, which is not a supported scenario.

**Comment by AndyAyersMS** [comment] 2023-06-29 23:33
@jkotas were you able to run outside of VS? When I run in VS with 8.0 checked bits, VS itself is crashing. Did you overwrite the entire runtime or just coreclr/corjit/SPC or some other subset?

**Comment by jkotas** [comment] 2023-06-30 00:02
These are the steps:
1. Install .NET 8 Preview 5 SDK if you do not have it already
2. `dotnet new console`
3. Copy&paste the repro in Program.cs
4. `dotnet publish -c Debug --self-contained`
5. `cd bin\Debug\net8.0\win-x64\publish`
6. `copy /Y C:\runtime\artifacts\bin\coreclr\windows.x64.Checked\*` (overwrite the runtime with my local checked build
7. `set VSDebugger_ValidateDotnetDebugLibSignatures=0`
8. `start devenv /debugexe repro.exe`
9. Go to Debug / Options / Debugging / General and check "Prevent using precompiled images ..."
10. Go to Project properties and set Debugger Type to ".NET Core / .NET 5+" (Note that you can also set env variables for the program in this dialog in case you need that later)
11. Press F5
12. Observe the AF message from the JIT

**Comment by jkotas** [comment] 2023-06-30 00:05
> were you able to run outside of VS?

I have tried a bit, but I was not successful replicating the problem. I suspect we do not have all the right env variables to simulate the JIT configuration that we end up using under debugger in this configuration.

**Comment by AndyAyersMS** [comment] 2023-06-30 01:39
Right, there's currently no way to test this config outside of debugging. 

As I suspected
```
this->opts.jitFlags->m_jitFlags,x
0x0000000004080214

DEBUG_CODE
DEBUG_INFO
FROZEN_ALLOC_ALLOWED
BBINSTR_IF_LOOPS
TIER0
```
Either the jit interface should remove `TIER0` or the jit should ignore it if `DEBUG_CODE` is present.

**Comment by danmoseley** [comment] 2023-06-30 03:25
Same day fix @delmyers !

**Comment by AndyAyersMS** [comment] 2023-07-01 01:55
Fixed in main via https://github.com/dotnet/runtime/pull/88227.

@delmyers @hoyosjs since this impacted both of you: do you recommend backporting this fix to 7.0?

**Closed** 2023-07-01 01:56 UTC
Labels: area-CodeGen-coreclr

**Comment by rwasef1830** [comment] 2023-07-19 05:29
I kindly request backport of this fix to 7.x as I'm impacted by it, considering it's literally a single line fix with very low regression risk.

**Comment by AndyAyersMS** [comment] 2023-07-19 16:02
@rwasef1830 this particular crash is strongly tied to the way that VS debugging and the runtime interact.

If you are seeing crashes outside of debugging with VS you are quite possibly running into some other problem -- we'd be happy to take a look if you can get us more information.
