### ISSUE TITLE
Test failure System.Text.RegularExpressions.Tests.MonoTests.ValidateRegex

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#88888] opened 2023-07-14 02:59 UTC
**Failed in:** [runtime-coreclr libraries-jitstress 20230713.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=338141&view=ms.vss-test-web.build-test-results-tab&runId=7036112&resultId=199968&paneView=debug)

**Failed tests:**
```
net8.0-windows-Release-x64-CoreCLR_checked-jitstress2_tiered-Windows.10.Amd64.Open
    - System.Text.RegularExpressions.Tests.MonoTests.ValidateRegex
    - System.Text.RegularExpressions.Tests.RegexPcre2Tests.IsMatchTests
```

**Error message:**
```
System.AggregateException : One or more errors occurred. (Exception has been thrown by the target of an invocation.)
---- System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
-------- System.TypeInitializationException : The type initializer for 'System.Text.RegularExpressions.Generated.<RegexGenerator_g>F74B1AE921BCEFE4BA601AA541C7A23B1CA9711EA81E8FE504B5B6446748E035A__Get672_369' threw an exception.
------------ System.InvalidOperationException : Failed to compare two elements in the array.
---------------- System.NullReferenceException : Object reference not set to an instance of an object.
```

**Stack trace:**
```
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 1895
   at System.Threading.Tasks.Task`1.get_Result() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:line 440
   at System.Text.RegularExpressions.Tests.MonoTests.ValidateRegex_MemberData()+MoveNext() in /_/src/libraries/System.Text.RegularExpressions/tests/FunctionalTests/MonoRegexTests.cs:line 58
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext() in /_/src/libraries/System.Linq/src/System/Linq/Select.cs:line 143
----- Inner Stack Trace -----
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 64
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 131
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBase.cs:line 54
   at System.Text.RegularExpressions.Tests.RegexGeneratorHelper.SourceGenRegexAsync(ValueTuple`4[] regexes, CancellationToken cancellationToken) in /_/src/libraries/System.Text.RegularExpressions/tests/FunctionalTests/RegexGeneratorHelper.netcoreapp.cs:line 246
   at System.Text.RegularExpressions.Tests.RegexHelpers.GetRegexesAsync(RegexEngine engine, ValueTuple`4[] regexes) in /_/src/libraries/System.Text.RegularExpressions/tests/FunctionalTests/Regex.Tests.Common.cs:line 130
----- Inner Stack Trace -----
   at C.Get672() in System.Text.RegularExpressions.Generator\System.Text.RegularExpressions.Generator.RegexGenerator\RegexGenerator.g.cs:line 12156
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
----- Inner Stack Trace -----
   at System.Collections.Generic.ArraySortHelper`1.Sort(Span`1 keys, Comparison`1 comparer) in /_/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/ArraySortHelper.cs:line 67
   at System.Text.RegularExpressions.RegexFindOptimizations.FindFixedDistanceString(List`1 fixedDistanceSets) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexFindOptimizations.cs:line 272
   at System.Text.RegularExpressions.RegexFindOptimizations..ctor(RegexNode root, RegexOptions options) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexFindOptimizations.cs:line 147
   at System.Text.RegularExpressions.RegexTree..ctor(RegexNode root, Int32 captureCount, String[] captureNames, Hashtable captureNameToNumberMapping, Hashtable captureNumberSparseMapping, RegexOptions options, CultureInfo culture) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexTree.cs:line 80
   at System.Text.RegularExpressions.RegexParser.Parse(String pattern, RegexOptions options, CultureInfo culture) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexParser.cs:line 131
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, CultureInfo culture) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs:line 96
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options) in /_/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/Regex.cs:line 61
   at System.Text.RegularExpressions.Generated.<RegexGenerator_g>F74B1AE921BCEFE4BA601AA541C7A23B1CA9711EA81E8FE50
```

**Comment by danmoseley** [comment] 2023-07-14 03:38
@BruceForstall  this might be a rare case where it actually is caused by jitstress? These tests are normally very deterministic.

**Comment by danmoseley** [comment] 2023-07-14 03:40
Dupe of #88882

**Comment by jakobbotsch** [comment] 2023-07-14 19:44
It's likely the same situation as https://github.com/dotnet/runtime/issues/88890#issuecomment-1636331713 -- the test passed in the next run, so going to close.

**Closed by jakobbotsch** 2023-07-14 19:44 UTC
Labels: area-System.Text.RegularExpressions, os-windows, JitStress, arch-x64, untriaged
