### ISSUE TITLE
DateTime format uses a non standard space character when running in a Docker Linux container

### ISSUE THREAD

**Issue by jeffpapp** [dotnet/runtime#96022] opened 2023-12-14 15:16 UTC
### Description

When running a .NET 8 application using the standard mcr.microsoft.com/dotnet docker image and specifying the "en-US" culture the space between the time and AM/PM is a NARROW NO-BREAK SPACE (U+202F) instead of a standard ASCII space.

We ran into this issue when adding a date time value as a HTTP header which does not allow non ASCII characters

### Reproduction Steps

This simple console application demonstrates the issue.  It gets the `DateTime.Now.ToString()` value and then inspects each character.  

```csharp
var ci = new System.Globalization.CultureInfo("en-US");

Thread.CurrentThread.CurrentCulture = ci;

string s = DateTime.Now.ToString();

Console.WriteLine(s);

foreach (var c in s.ToCharArray())
{
    Console.WriteLine($"{c} : {(int)c} : IsAscii {char.IsAscii(c)}");
}
```

Using this docker file you can build a docker image and then run it to see the output

```
FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /app
COPY . ./
RUN dotnet restore
RUN dotnet publish -c Release -o out
WORKDIR /app/out
ENTRYPOINT [ "dotnet", "ConsoleApp1.dll" ]
```

### Expected behavior

I would expect that the string output from `ToString()` would be the same across operating systems when using the same culture.

### Actual behavior

The space between the time and the AM/PM designator has an int value of 8239 when running in the docker container which does not match any of the other spacing in the string or the spacing if running on Windows

### Regression?

This is a regression.  Changing the application and dockerfile above to .NET 7 results in a standard space being used

**Comment by Clockwork-Muse** [comment] 2023-12-14 17:25
Duplicate of #95620

Working as designed.

**Comment by MichalPetryka** [comment] 2023-12-14 19:24
If you need a fixed format, you have to hardcode it in the code, culture formats are provided by the OS and change from time to time.

**Comment by jeffpapp** [comment] 2023-12-14 19:27
> If you need a fixed format, you have to hardcode it in the code, culture formats are provided by the OS and change from time to time.

Good to know.  Is this a new thing in .NET where it uses the OS culture format?

**Comment by MichalPetryka** [comment] 2023-12-14 19:48
> Is this a new thing in .NET 8 where it uses the OS culture format?

No, but before .NET 5 on Windows the runtime used NLS instead of ICU which was changed less often. The move to ICU was made to unify the behaviour with other platforms that have always used it since NLS is Windows only.

**Comment by Clockwork-Muse** [comment] 2023-12-14 21:38
Note that that's "Unify behavior", not "Unify formats".

ICU is updated multiple times a year, and formats on any platform are dependent on both upstream packaging (eg, the difference in speed Ubuntu vs Debian) and whether your specific deployment actually updates itself.

**Comment by tarekgh** [comment] 2023-12-19 02:23
Closing per replies.

**Closed by tarekgh** 2023-12-19 02:23 UTC
Labels: area-System.Globalization, untriaged
