### ISSUE TITLE
[API Proposal]: `GetKeyedService` overload that takes a `System.Type`

### ISSUE THREAD

**Issue by linkdotnet** [dotnet/runtime#102816] opened 2024-05-29 12:50 UTC
### Background and motivation

The `IServiceProvider` interface knows a `GetRequiredKeyedService` in the following two shapes:
```csharp
    public static object GetRequiredKeyedService(
      this IServiceProvider provider,
      Type serviceType,
      object? serviceKey);

public static T GetRequiredKeyedService<T>(this IServiceProvider provider, object? serviceKey);
```

So a non-generic and generic version. The same doesn't apply to `GetKeyedService`. This one only has:
```csharp
public static T? GetKeyedService<T>(this IServiceProvider provider, object? serviceKey)
```

### API Proposal

```diff
namespace Microsoft.Extensions.DependencyInjection
{
  public static class ServiceProviderKeyedServiceExtensions
  {
+     public static object? GetKeyedService(this IServiceProvider provider, Type serviceType, object? serviceKey);
```

### API Usage

```csharp
IMyType? Resolve(IServiceProvider provider, Definition definition)
{
  return provider.GetKeyedService(definition.Type, "my-fancy-key") as IMyType;
}
```

**Comment by steveharter** [comment] 2024-05-30 21:49
Hmm it does exist on [ServiceProvider](https://github.com/dotnet/runtime/blob/0651ebc74e671cd000a0a0f029100551d4fd9777/src/libraries/Microsoft.Extensions.DependencyInjection/ref/Microsoft.Extensions.DependencyInjection.cs#L27) but not on [ServiceProviderKeyedServiceExtensions](https://github.com/dotnet/runtime/blob/0651ebc74e671cd000a0a0f029100551d4fd9777/src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ServiceProviderKeyedServiceExtensions.cs#L13).

Also I updated the description to return `object?` instead of `T`

**Comment by steveharter** [comment] 2024-05-30 21:49
Thoughts @benjaminpetit ?

**Comment by julealgon** [comment] 2024-05-30 22:09
Looking at the implementation hierarchy, it appears that the intention was for people to use [the `IKeyedServiceProvider` abstraction](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.ikeyedserviceprovider?view=net-8.0) instead of `IServiceProvider` to call [the `GetKeyedService(Type, Object)` method, which is defined there](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.ikeyedserviceprovider.getkeyedservice?view=net-8.0#microsoft-extensions-dependencyinjection-ikeyedserviceprovider-getkeyedservice(system-type-system-object)).

So this apparent inconsistency seems to be by design. Just use `IKeyedServiceProvider` instead in your `Resolve` method.

**Comment by linkdotnet** [comment] 2024-05-31 07:58
That is interesting and seems odd from a discoverability point of view. The `ServiceProviderKeyedServiceExtensions.GetKeyedService<T>` is even using the `GetKeyedService(Type, Object)` version.

So either it is a documentation issue pointing developers in the right direction or an API issue.
As developer I would have expected symmetry just like [`ServiceProviderServiceExtensions.GetRequiredService`](https://github.com/dotnet/runtime/blob/d0d6fed6c0eedd962ddc0f68554682064e9e11ca/src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ServiceProviderServiceExtensions.cs#L35). The same argumentation could be done here and the `GetRequiredService(Object)` could be dropped.

**Comment by julealgon** [comment] 2024-05-31 14:04
I agree this is a bit weird @linkdotnet . I assume it was done this way to avoid breaking changes to the original `IServiceProvider` interface and allow container vendors to implement keyed services "in an incremental fashion". Just a guess though, maybe someone on the team can elaborate why this design was chosen in more detail.

I do believe thought that the container is always registered with both interfaces so you _could_ just inject `IKeyedServiceProvider` instead of `IServiceProvider` in your use cases. I've not tested it though as I also just discovered this interface when looking at your issue 😅. Now... if that doesn't work, then I'd be incredibly surprised.

**Comment by radulung** [comment] 2024-07-04 15:28
And still GetKeyedServices is there with both signatures.
It should expose as well GetKeyedService in the same way
![image](https://github.com/dotnet/runtime/assets/50765443/de9efb3f-e0b3-433d-9549-97584780742c)

**Comment by steveharter** [comment] 2024-07-24 20:22
Moving to v10 since we have reached the v9 "feature complete" milestone; still in API review backlog.

**Comment by bartonjs** [comment] 2024-07-25 18:01
Looks good as proposed

```C#
namespace Microsoft.Extensions.DependencyInjection
{
  public static partial class ServiceProviderKeyedServiceExtensions
  {
    public static object? GetKeyedService(this IServiceProvider provider, Type serviceType, object? serviceKey);
  }
}
```

**Comment by martincostello** [comment] 2024-08-01 18:29
I'm happy to pick this up if no one else is planning on doing this any time soon.

**Closed** 2024-08-21 20:17 UTC
Labels: api-approved, area-Extensions-DependencyInjection, in-pr
