### ISSUE TITLE
.Net 8 -> Killing entire tree not working using Process.Kill(true)

### ISSUE THREAD

**Issue by TejasPatadiya10** [dotnet/runtime#102442] opened 2024-05-20 06:22 UTC
Below is my simple code :

static void Main(string[] args)
{
    while (true)
    {
        try
        {
            Process.Start(new ProcessStartInfo() { FileName= "ChildProcess.exe"  });
           Thread.Sleep(5000);
            Process.GetCurrentProcess().Kill(true);// this line always give exception : {"Cannot be used to terminate a process tree containing the calling process."
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.ToString());
        }
    }
}

The above code should kill the child process and the main process but it always results in exception : "Cannot be used to terminate a process tree containing the calling process."

I am not sure its BUG or anything else.

**Comment by huoyaoyuan** [comment] 2024-05-20 06:53
Duplicate of #85383

**Closed** 2024-05-20 06:54 UTC
Labels: area-System.Diagnostics.Process, untriaged
