### ISSUE TITLE
[API Proposal]: Allow adding links after activity creation

### ISSUE THREAD

**Issue by lmolkova** [dotnet/runtime#101146] opened 2024-04-16 21:38 UTC
### Background and motivation

OpenTelemetry recently added and [stabilized](https://github.com/open-telemetry/opentelemetry-specification/pull/3887) adding links after span creation.

See https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#link for the details.

This is useful:
- for messaging/event processing scenarios - when messages are pulled from the messaging system, the trace-context the carry is not known until messages are received
- associating phases of establishing connections and HTTP requests  - see https://github.com/dotnet/runtime/issues/93832 or https://github.com/open-telemetry/semantic-conventions/pull/756 for the context 

### API Proposal

Add `Activity.AddLink(ActivityLink link)` API

### API Usage

```csharp
using var activity = Source.StartActivity("Receive");

var messages = await ReceiveInternal(maxBtchSize);
foreach (var ctx in ExtractTraceContext(messages))
{
    activity.AddLink(new ActivityLink(ctx)); // this is new
}

```

**Comment by tarekgh** [comment] 2024-04-16 21:54
Duplicate of https://github.com/dotnet/runtime/issues/97680

**Closed by tarekgh** 2024-04-16 21:54 UTC
Labels: api-suggestion, area-System.Diagnostics.Tracing, untriaged
