### ISSUE TITLE
SetTcpKeepAlive() is a no-op

### ISSUE THREAD

**Issue by Epic-Santiago** [dotnet/runtime#77758] opened 2022-11-01 22:42 UTC
### Description

The following call does nothing in .NET 6:
```csharp
System.Net.ServicePointManager.SetTcpKeepAlive(true, 120, 10);
```

This call sets the TCP keep alive in .NET Framework and it works. Having a no-op API with no indication like this is an ambush awaiting those migrating from .NET Framework to .NET. It in fact created some production downtime on our first release on .NET 6.

### Reproduction Steps

You can clearly see that the method does nothing in the .NET sources:
https://source.dot.net/#System.Net.ServicePoint/System/Net/ServicePointManager.cs,218

The documentation makes no mention that this doesn't work in .NET 6:
https://learn.microsoft.com/en-us/dotnet/api/system.net.servicepointmanager.settcpkeepalive?view=net-6.0

### Expected behavior

One of these options must be applied to `SetTcpKeepAlive()` in .NET 6:
1. Implement it
2. Remove it
3. Make it clear that it is obsolete (with a plan to remove it later)

For option 3 this includes a combination of these options:
1. The method is marked as obsolete so that code using it compiles with a warning
2. The documentation is updated to say the method does nothing
3. The method throws a `NotImplementedException`

### Actual behavior

No TCP packets are sent and we only find out at runtime when things start to fail.

### Regression?

Yes. It works on .NET Framework.

### Known Workarounds

Configure the TCP keep alive via `SocketsHttpHandler` which is very painful (see https://github.com/dotnet/runtime/issues/77755).

### Configuration

1. .NET 6
2. Windows 10
3. x64
4. It is not specific to this configuration
5. Not using Blazor

**Comment by MihaZupan** [comment] 2022-11-01 22:56
> Make it clear that it is obsolete 

We agree. Closing this as a duplicate of #62770 and #71836.

**Closed by MihaZupan** 2022-11-01 22:56 UTC
Labels: area-System.Net, untriaged
