### ISSUE TITLE
ILLink takes almost 1h

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#87062] opened 2023-06-02 14:56 UTC
### Description

ILLink takes a long time.

From the binlog:

Top 10 most expensive tasks
    ILLink = 52:53.702, 1 calls.
        _RunILLink = 52:53.702, 1 calls.
   [...]

that's over 50 minutes...

### Reproduction Steps

1. Clone https://github.com/microsoftgraph/msgraph-sample-maui
2. Remove [bundle resource 'appSettings.Development.json'](https://github.com/microsoftgraph/msgraph-sample-maui/blob/cf05d8540e82e9e9c1b346a3ba8332a6b68c2a69/GraphMAUI/GraphMAUI.csproj#L87) from project
3. Run `dotnet publish -c Release -f net7.0-ios16.1 -r ios-arm64`
4. Wait ~1 hour because of https://github.com/microsoftgraph/msgraph-sample-maui/issues/68 

Note that the build will fail due to #87061, but at that point the linker has already done its work (slowly...).

### Expected behavior

Faster build

### Actual behavior

Very slow build

## Environmenet

- dotnet 7.0.100
- Microsoft.iOS.Sdk 16.2.1024

### Build Logs

[msbuild_(6).zip](https://github.com/xamarin/xamarin-macios/files/11619728/msbuild_.6.zip)

### Example Project

https://github.com/microsoftgraph/msgraph-sample-maui

### Other information

This was filed here: https://github.com/xamarin/xamarin-macios/issues/18388

**Comment by vitek-karas** [comment] 2023-06-02 16:20
This is a duplicate of https://github.com/dotnet/runtime/issues/87050.

**Closed by vitek-karas** 2023-06-02 16:20 UTC
Labels: untriaged, area-Tools-ILLink
