### ISSUE TITLE
[API Proposal]: ArgumentException.ThrowIfNullOrEmpty(string) and similar methods should return the item/string

### ISSUE THREAD

**Issue by nonwombatant** [dotnet/runtime#100870] opened 2024-04-10 15:48 UTC
### Background and motivation

This was great.

https://github.com/dotnet/runtime/issues/62628

But it would also be great if the various ThrowIf methods also returned the item in the event there is not an exception.

This is nice for assigning items in a constructor.

### API Proposal

```csharp
namespace System
{
    public class ArgumentException : SystemException
    {
        public static string ThrowIfNullOrEmpty([NotNull] string? argument, [CallerArgumentExpression("argument")] string? paramName = null)
    }
}
```

### API Usage

```csharp
public SomeConstructor() {
    this._input = ArgumentException.ThrowIfNullOrEmpty(input);
}
```

### Risks

This would be a breaking change. Since the method signatures would all change. However since it's changing from void to non void this is a low risk change. The most common usage was probably:

```csharp
ArgumentException.ThrowIfNullOrEmpty(input);
```

This would be unaffected.

**Comment by huoyaoyuan** [comment] 2024-04-10 15:59
> However since it's changing from void to non void this is a low risk change.

It's binary breaking change and will break all existing callers.

**Comment by rmsimpson** [comment] 2024-04-10 16:28
The function is designed to throw.  How would it both throw *and* return a value?  It's fundamentally impossible to do both.

**Comment by nonwombatant** [comment] 2024-04-10 22:22
> > However since it's changing from void to non void this is a low risk change.
> 
> It's binary breaking change and will break all existing callers.

This will not break anything if you are calling it like this (which almost everyone would be)

```csharp
ArgumentException.ThrowIfNullOrEmpty(input);
```

The function will simply return a value that is ignored.

**Comment by stephentoub** [comment] 2024-04-11 01:12
> This will not break anything if you are calling it like this (which almost everyone would be)

It will. It won't be "source breaking" but it will be "binary breaking". A method's return type is part of the method's identity: if you change a method's return type, existing compiled binaries referencing the old signature will end up getting a method not found exception, because the method they're referencing no longer exists.

**Comment by MichalPetryka** [comment] 2024-04-11 01:50
Technically this could be done by introducing new overloads since IL allows overloading by return type but it'd require language changes (maybe as part of `BinaryCompatibilityOnly`).

**Comment by jkotas** [comment] 2024-04-11 03:37
Duplicate of #70515

**Closed** 2024-04-11 13:25 UTC
Labels: api-suggestion, area-System.Runtime, untriaged
