### ISSUE TITLE
Add IDistributedCache:RemoveAsync overload that takes multiple keys

### ISSUE THREAD

**Issue by udlose** [dotnet/runtime#36046] opened 2020-02-26 21:34 UTC
### Problem
I see that `StackExchange.Redis.RedisDatabase` class offers an overload of `KeyDeleteAsync` that takes an array of keys.  Currently, the `IDistributedCache` only exposes a `RemoveAsync` with a single key. This means that multiple trips to the RedisDatabase are made if you need to delete more than one key.  It would be far more efficient and convenient to be able to remove multiple keys with a single trip to the RedisDatabase.

### Describe the solution you'd like
I'd like to see an overload added to `IDistributedCache` that has the following signature.  It returns a `long` with the number of keys deleted.

Declaration:
`Task<long> RemoveAsync(string[] keys, CancellationToken token = default(CancellationToken));`

Implementation could be similar to this:
```
public async Task<long> RemoveAsync(string[] keys, CancellationToken token = default(CancellationToken))
{
    if (keys == null) throw new ArgumentNullException(nameof(keys));
    if (keys.Length == 0) throw new ArgumentException($"{nameof(keys)} cannot be empty", nameof(keys));
    if (keys.Any(string.IsNullOrWhiteSpace))
        throw new ArgumentException($"{nameof(keys)} cannot contain a null or whitespace element", nameof(keys));

    token.ThrowIfCancellationRequested();

    await ConnectAsync(token);

    // TODO: Error handling
    var redisKeys = keys.Select(key => (RedisKey)key).ToArray();
    return await _cache.KeyDeleteAsync(redisKeys).ConfigureAwait(false);
}
```

### Describe alternatives you've considered
I've considered two alternatives:
1. creating an extension method to provide an overload but this does not work because I cannot access the private instance of `IDatabase`
2. Explicitly adding the nuget `StackExchange.Redis` to my app and using their API to achieve my goal.  However, even though this does work, this creates an additional "gateway" of accessing and interacting with my Redis instance.  It also creates another Redis connection which is undesirable.

### Additional context
I'd like a single API that I can leverage to achieve deleting multiple keys in a single Redis call.

Thank you for your consideration.

**Comment by eerhardt** [comment] 2020-10-07 15:40
Duplicate of #36568.

**Closed by eerhardt** 2020-10-07 15:40 UTC
Labels: area-Extensions-Caching
