### ISSUE TITLE
The behavior of GC.Collect() in .Net8 is different with .Net Framework

### ISSUE THREAD

**Issue by shaoht** [dotnet/runtime#109441] opened 2024-11-01 06:10 UTC
### Description

The unused object doesn't been released when call GC.Collect() in .Net8, but it is released in .NetFramework.

### Reproduction Steps

1. Build and run [TestWeakReferenceCore.zip](https://github.com/user-attachments/files/17596680/TestWeakReferenceCore.zip)
, show "weakRef.IsAlive: True".
2. Build and run [TestWeakReferenceFramework.zip](https://github.com/user-attachments/files/17596681/TestWeakReferenceFramework.zip)
 , show "weakRef.IsAlive: False".

### Expected behavior

For TestWeakReferenceCore.csproj, show "weakRef.IsAlive: False".

### Actual behavior

For TestWeakReferenceCore.csproj, show "weakRef.IsAlive: True".

**Comment by hez2010** [comment] 2024-11-01 06:25
This is caused by tiered compilation, which is used for speeding up startup and instrument for dynamic PGO.
In tier-0 (unoptimized) code, the lifetime of object can be extended.

Tiered compilation only promotes hot methods to tier-1 (optimized), you can observe the behavior by using this code:

```cs
while (true) Test();
Console.Read();

void Test()
{
    Object obj = new Object();
    WeakReference weakRef = new WeakReference(obj);
    obj = null;
    GC.Collect();

    Console.WriteLine($"weakRef.IsAlive: {weakRef.IsAlive.ToString()}");
}
```

If you want to turn off tiered compilation, you can add the following lines to your project file:

```xml
<PropertyGroup>
    <TieredCompilation>false</TieredCompilation>
</PropertyGroup>
```

**Comment by huoyaoyuan** [comment] 2024-11-01 06:31
Or a simpler reproduction: use the original code snippet, run with `<TieredCompilation>false</TieredCompilation>` AND Release configuration, it prints "weakRef.IsAlive: False".

Closing as answered.

**Closed by huoyaoyuan** 2024-11-01 06:31 UTC
Labels: untriaged, needs-area-label

**Comment by teo-tsirpanis** [comment] 2024-11-03 18:39
If you want to make sure an object can be collected after a specific point, you must use it inside a method marked with `[MethodImpl(MethodImplOptions.NoInlining)]`.
