### ISSUE TITLE
System.Text.Json source generator does not handle reserved words as field names

### ISSUE THREAD

**Issue by DavidLuong98** [dotnet/runtime#99054] opened 2024-02-28 16:17 UTC
### Description

The source generator has a bug where it fails to handle cases where a field name is both a valid name in C# and a reserved word in other contexts, such as 'required', 'object', and 'type'.

### Reproduction Steps

This is the minimal reproducing code. 
`required` is a valid field name, however the generated code will fail.

```
public class Foo
{
    public string? required;
}

[JsonSerializable(typeof(Foo))]
[JsonSourceGenerationOptions(IncludeFields = true, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
partial class X : JsonSerializerContext
{
}
```

### Expected behavior

Generated `g.cs` will be created successfully and the project will be able to build. 

### Actual behavior

When the `g.cs` is generated, there is a build error output : 

![runtimebug](https://github.com/dotnet/runtime/assets/23180943/091b2d13-efd7-4952-9eb2-7c4581fa7a35)

```13>SourceGenerationContext.Foo.g.cs(131,30): Error CS1002 : ; expected
13>SourceGenerationContext.Foo.g.cs(132,25): Error CS1026 : ) expected
13>SourceGenerationContext.Foo.g.cs(132,42): Error CS1002 : ; expected
13>SourceGenerationContext.Foo.g.cs(132,42): Error CS1513 : } expected
13>SourceGenerationContext.Foo.g.cs(135,61): Error CS1003 : Syntax error, ',' expected
13>SourceGenerationContext.Foo.g.cs(131,30): Error CS0103 : The name 'required' does not exist in the current context
13>SourceGenerationContext.Foo.g.cs(132,17): Error CS0029 : Cannot implicitly convert type 'string[]' to 'bool'
13>SourceGenerationContext.Foo.g.cs(132,25): Error CS0103 : The name 'required' does not exist in the current context
13>SourceGenerationContext.Foo.g.cs(135,61): Error CS0103 : The name 'required' does not exist in the current context
13>SourceGenerationContext.Foo.g.cs(132,17): Error CS0165 : Use of unassigned local variable '__value_ 
```

### Known Workarounds

Renaming this `required` field to something else, such as `_required` and using ` [JsonPropertyName("SomeOtherName")]` for that field.

### Configuration

Which version of .NET is the code running on? : `.NET8`
What OS : `Windows 11`
What is the architecture (x64, x86, ARM, ARM64)? : `ARM64`

**Comment by eiriktsarpalis** [comment] 2024-02-28 16:58
Appears to be a duplicate of https://github.com/dotnet/runtime/issues/98050. The fix was backported to .NET 8 and will be available in the upcoming servicing release.

**Closed** 2024-02-28 16:58 UTC
Labels: area-System.Text.Json, untriaged
