### ISSUE TITLE
HttpClient Support Data URLs (scheme data:)

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#97772] opened 2024-01-31 16:45 UTC
### Description

Previous issue was locked https://github.com/dotnet/runtime/issues/95838

Data urls https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs are a common embed for inline sources where a server connection is not required, however .NET has no way of decoding them.

As they are used interchangeably with http and https a string forward approach would be for HttpClient to understand them; especially since it understand the mime encodings and mime types which can be part of the data url.

### Reproduction Steps

```csharp
using HttpClient httpClient = new();
var result = await httpClient.GetStringAsync ("data:text/plain;base64,SGVsbG8sIFdvcmxkIQ==");
Console.WriteLine(result);
```

### Expected behavior

Console outputs
"Hello World!"

### Actual behavior

ArgumentException `Only 'http' and 'https' schemes are allowed. (Parameter 'requestUri')`

### Other information

Expect it to work like JavaScript

#### Via `fetch`

Expect it to work like JavaScript
```js
await (await fetch("data:text/plain;base64,SGVsbG8sIFdvcmxkIQ==")).text()

> 'Hello, World!'
```

#### Via `XMLHttpRequest`

```js
function reqListener() {
  console.log(this.responseText);
}

const req = new XMLHttpRequest();
req.addEventListener("load", reqListener);
req.open("GET", "data:text/plain;base64,SGVsbG8sIFdvcmxkIQ==");
req.send();

> 'Hello, World!'
```

**Comment by ManickaP** [comment] 2024-01-31 17:10
Duplicate of #95838

**Comment by ManickaP** [comment] 2024-01-31 17:10
I've re-opened the original.

**Closed by ManickaP** 2024-01-31 17:10 UTC
Labels: area-System.Net.Http, untriaged
