### ISSUE TITLE
R2R Crossgen2 breaks simple try catch statement with generic type

### ISSUE THREAD

**Issue by vuplea** [dotnet/runtime#66005] opened 2022-03-01 13:47 UTC
Sdk 6.0.2

Program.cs
```
try
{
    Test<InvalidOperationException>();
}
catch
{
    System.Diagnostics.Debug.Assert(false); // assertion triggered when running published version
}

static void Test<TException>() where TException : Exception
{
    try
    {
        throw new InvalidOperationException();
    }
    catch (TException)
    {
        return;
    }
}
```
csproj
```
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>true</ImplicitUsings>
		<PublishDir>published</PublishDir>
		<PublishReadyToRun>True</PublishReadyToRun>
		<RuntimeIdentifier>win8-x64</RuntimeIdentifier>
	</PropertyGroup>
	<Target Name="PublishAfterBuild" AfterTargets="Build">
		<CallTarget Targets="Publish" />
	</Target>
</Project>
```

**Comment by hez2010** [comment] 2022-03-01 16:23
I think it's a duplicate of https://github.com/dotnet/runtimelab/issues/204, but it's fine to have a tracker issue for this repo.

**Comment by vuplea** [comment] 2022-03-02 07:47
> I think it's a duplicate of https://github.com/dotnet/runtimelab/issues/204, but it's fine to have a tracker issue for this repo. 

Yet we're not using native AOT or any experimental functionality, just the  standard .NET6 SDK.

**Comment by jkotas** [comment] 2022-03-02 19:52
This bug has not much to do with the NativeAOT issue.

This bug is triggered when the only reference of the generic argument is in the `catch` clause. If there is at least one reference of the generic argument somewhere else, the bug does away:
```
static void Test<TException>() where TException : Exception
{
    Console.WriteLine(typeof(TException));
    try
    {
        throw new InvalidOperationException();
    }
    catch (TException)
    {
        return;
    }
}
```

**Comment by jkotas** [comment] 2022-03-02 19:53
I think that the problem is that `CORINFO_GENERICS_CTXT_KEEP_ALIVE` is not getting set by crossgen2.

**Closed** 2022-03-04 19:13 UTC
Labels: bug, area-ReadyToRun-coreclr, untriaged, regression-from-last-release

**Comment by mangod9** [comment] 2022-03-04 19:30
Since there appears to be a simple workaround, is a backport to 6 required for this?

**Comment by jkotas** [comment] 2022-03-04 19:38
If the bug is found in 3rd party library, it is not easy to workaround (short of disabling crossgen for the whole library).

**Comment by GSPP** [comment] 2022-03-17 07:39
I have this exact code pattern in a utility library of mine. It's a generic retry helper function. The type parameter is purely used to control the type of exception being caught for retry. Just letting you know how this pattern could arise in a real application.
