### ISSUE TITLE
Test failure:JIT/Methodical/Boxing/misc/_relenum_cs/_relenum_cs.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#55489] opened 2021-07-12 03:08 UTC
Run: [runtime-coreclr r2r-extra 20210710.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1231392&view=ms.vss-test-web.build-test-results-tab&runId=36674588&resultId=107810&paneView=debug)
Failed test:
```
R2R OSX arm64 Checked jitminopts @ OSX.1100.ARM64.Open

- JIT/Methodical/Boxing/misc/_relenum_cs/_relenum_cs.sh

```
**Error message**
```
Test Infrastructure Failure: System.IO.IOException: No space left on device
at System.IO.Strategies.Net5CompatFileStreamStrategy.WriteNative(ReadOnlySpan`1 source) in System.Private.CoreLib.dll:token 0x60059b1+0x1c
at System.IO.Strategies.Net5CompatFileStreamStrategy.FlushWriteBuffer(Boolean calledFromFinalizer) in System.Private.CoreLib.dll:token 0x60059aa+0x0
at System.IO.Strategies.Net5CompatFileStreamStrategy.Dispose(Boolean disposing) in System.Private.CoreLib.dll:token 0x60059a6+0xe7
at System.IO.Stream.Close() in System.Private.CoreLib.dll:token 0x6005589+0x7
at System.IO.StreamWriter.CloseStreamFromDispose(Boolean disposing) in System.Private.CoreLib.dll:token 0x60057af+0x36
at System.IO.StreamWriter.Dispose(Boolean disposing) in System.Private.CoreLib.dll:token 0x60057ae+0x25
at System.IO.TextWriter.Dispose() in System.Private.CoreLib.dll:token 0x6005842+0x7
at CoreclrTestLib.CoreclrTestWrapperLib.RunTest(String executable, String outputFile, String errorFile, String category, String testBinaryBase, String outputDir) in Coreclr.TestWrapper.dll:token 0x600000d+0x33e
at JIT_Methodical.Boxing_misc__relenum_cs__relenum_cs._Boxing_misc__relenum_cs__relenum_cs_sh() in JIT.Methodical.XUnitWrapper.dll:token 0x6000178+0xae
Expected: True
Actual:   False


Stack trace
   at JIT_Methodical._Boxing_misc__relenum_cs__relenum_cs_._Boxing_misc__relenum_cs__relenum_cs_sh() in JIT.Methodical.XUnitWrapper.dll:token 0x6000178+0xf0
```

**Comment by jeffhandley** [comment] 2021-07-13 06:23
Closing as a duplicate of #55163 ➡️ dotnet/core-eng#13596

**Closed by jeffhandley** 2021-07-13 06:23 UTC
Labels: arch-arm64, area-System.IO, untriaged
