### ISSUE TITLE
[Blazor] Slow startup and navigation when debugging

### ISSUE THREAD

**Issue by daniel-p-tech** [dotnet/runtime#80446] opened 2023-01-07 23:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,

After migrating my project from .NET 6 to .NET 7, there is a noticeably slower startup time of the app in Debug environment. Navigation back to the previous page using the browser back button is occasionally also much slower - sometimes there is up to a 3 second delay before the navigation event fires. As far as I can tell there is no problem with the published app.

Thank you!

### .NET Version

.NET 7

### Anything else?

Microsoft Visual Studio Community 2022 (64-bit), Version 17.4.3

**Comment by FOtto28** [comment] 2023-01-19 08:26
Have the same problem with Blazor WASM since upgrade from .net 6 to .net 7

**Comment by dev-jlb** [comment] 2023-03-28 03:51
Same issue here.  The initial startup time for a sample app went from ~25s to 55s.  In the output it gets to "Loaded xx.xx MB resources from cache" and then pauses for a long duration.  At least with my app, I narrowed it down to Microsoft.AspNetCore.Components.WebAssembly.DevServer.  If I use one of the 6.x versions, everything is fine, but when I update it to 7.0.x I see the slow behavior.

**Comment by martinlingstuyl** [comment] 2023-06-23 09:25
I've got the same behavior here: 20+ seconds of pausing. something with the ws:// browserlink (?) connection.

Reverting the `Microsoft.AspNetCore.Components.WebAssembly.DevServer` package doesn't help me.

This all is experienced when debugging in Edge.

Debugging in Firefox does not have the same problem..

**Comment by thaystg** [comment] 2023-08-05 20:28
This is already fixed on 8.0: https://github.com/dotnet/runtime/pull/86982
And also on 7.0: https://github.com/dotnet/runtime/pull/88602

**Closed by thaystg** 2023-08-05 20:28 UTC
Labels: arch-wasm, area-Debugger-mono

**Comment by dev-jlb** [comment] 2023-08-11 20:08
Has anyone confirmed the issue is fixed?  I am not able to test because of an issue w/ package versions >= 7.0.8 (https://github.com/dotnet/aspnetcore/issues/49064)

**Comment by dev-jlb** [comment] 2023-08-11 20:55
I confirmed that updating the WebAssembly & WebAssembley.DevServer packages to the latest version (7.0.10) fixed the issue for me.
