### ISSUE TITLE
[QUIC] Issue with `AcceptInboundStreamAsync()` Hanging and Failing to Accept Inbound Streams

### ISSUE THREAD

**Issue by melbasiouny** [dotnet/runtime#106938] opened 2024-08-25 16:31 UTC
### Description

`AcceptInboundStreamAsync()` causes the program to hang indefinitely, unless an **IdleTimeout** is set, in which case the method throws an exception when the timeout period elapses. This issue occurs consistently regardless of whether the method is called on the server or client side.

I am unsure whether this issue is due to a bug or an error in my code. I have tested this on both Windows 11 with .NET 8 and .NET 9, as well as on Ubuntu 22.04.4 LTS with .NET 8, the issue persisted on both environments.

### Sample Code
```cs
using System.Net;
using System.Net.Quic;
using System.Net.Security;
using System.Security.Cryptography.X509Certificates;

#pragma warning disable CA1416

if (!QuicListener.IsSupported || !QuicConnection.IsSupported)
{
    Console.WriteLine("QUIC is not supported, check for presence of libmsquic and support of TLS 1.3.");
    return;
}

var serverConnectionOptions = new QuicServerConnectionOptions
{
    DefaultCloseErrorCode = 0x0A,
    DefaultStreamErrorCode = 0x0B,
    ServerAuthenticationOptions = new SslServerAuthenticationOptions
    {
        ApplicationProtocols = [new SslApplicationProtocol("MyCustomProtocol")],
        ServerCertificate = new X509Certificate2("MsQuic.pfx", "MsQuic")
    }
};

var listener = await QuicListener.ListenAsync(new QuicListenerOptions
{
    ListenEndPoint = new IPEndPoint(IPAddress.IPv6Any, 4040),
    ApplicationProtocols = [new SslApplicationProtocol("MyCustomProtocol")],
    ConnectionOptionsCallback = (_, _, _) => ValueTask.FromResult(serverConnectionOptions)
});

var clientConnectionOptions = new QuicClientConnectionOptions
{
    RemoteEndPoint = new DnsEndPoint("localhost", 4040),
    DefaultCloseErrorCode = 0x0A,
    DefaultStreamErrorCode = 0x0B,
    MaxInboundUnidirectionalStreams = 10,
    MaxInboundBidirectionalStreams = 100,
    ClientAuthenticationOptions = new SslClientAuthenticationOptions
    {
        TargetHost = "localhost",
        ApplicationProtocols = [new SslApplicationProtocol("MyCustomProtocol")]
    }
};

ConnectClient();

Console.WriteLine("[SERVER]: Listening for incoming connections.");

var connection = await listener.AcceptConnectionAsync();
var openStream = await connection.OpenOutboundStreamAsync(QuicStreamType.Bidirectional);

Console.WriteLine($"[SERVER]: Accepted connection and opened bidirectional stream: {openStream.Id}.");

Console.ReadKey();

await listener.DisposeAsync();
return;

async void ConnectClient()
{
    Console.WriteLine("[CLIENT]: Attempting connection.");

    var client = await QuicConnection.ConnectAsync(clientConnectionOptions);
    var acceptStream =
        await client
            .AcceptInboundStreamAsync(); // Program hangs here. (this is also the case if AcceptInboundStreamAsync() is called on the server side).

    Console.WriteLine($"[CLIENT]: Connected to server and accepted inbound stream: {acceptStream.Id}.");

    await Task.Delay(TimeSpan.FromSeconds(10));

    Console.WriteLine("[CLIENT]: Closing connection.");

    await client.CloseAsync(0x0C);
    await client.DisposeAsync();
}

#pragma warning restore CA1416
```

### Expected behavior

[CLIENT]: Attempting connection.
[SERVER]: Listening for incoming connections.
[SERVER]: Accepted connection and opened bidirectional stream: 1.
[CLIENT]: Connected to server and accepted inbound stream: 1.
[CLIENT]: Closing connection.

### Without IdleTimeout
[CLIENT]: Attempting connection.
[SERVER]: Listening for incoming connections.
[SERVER]: Accepted connection and opened bidirectional stream: 1.

### With IdleTimeout
[CLIENT]: Attempting connection.
[SERVER]: Listening for incoming connections.
[SERVER]: Accepted connection and opened bidirectional stream: 1.
Unhandled exception. System.Net.Quic.QuicException: The connection timed out from inactivity.
   at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data)
   at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent)
   at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent)
--- End of stack trace from previous location ---
   at System.Net.Quic.QuicConnection.AcceptInboundStreamAsync(CancellationToken cancellationToken)
   at Program.<>c__DisplayClass0_0.<<<Main>$>g__ConnectClient|0>d.MoveNext() in Program.cs:line 67
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

### Configuration

- Windows 11 with .NET 8 and .NET 9 x64
- Ubuntu 22.04.4 LTS with .NET 8 (WSL2)

**Comment by ManickaP** [comment] 2024-08-25 17:23
This is not a bug but an intentional decision in design. Just opening the stream only reserves the stream, but doesn't send anything on the wire. You have to actually send some data to notify the peer about the stream.
I just checked the docs and haven't found this info there, so we should document it!

**Comment by melbasiouny** [comment] 2024-08-25 18:54
Thank you for the clarification, sending data after creating the outbound stream does indeed fix the problem!
I have created a pull request with the updated documentation here: #[42324](https://github.com/dotnet/docs/pull/42324#issue-2485415312).
I also revised some of the sample code to reflect the updated API.

**Comment by ManickaP** [comment] 2024-09-02 08:50
Thank you @melbasiouny !

I see the docs update is merged, so I'll close this.

**Closed by ManickaP** 2024-09-02 08:50 UTC
Labels: documentation, area-System.Net.Quic
