### ISSUE TITLE
Crash - JIT/Performance/CodeQuality/BenchmarksGame/binarytrees/binarytrees-5/binarytrees-5.sh

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#73455] opened 2022-08-05 11:19 UTC
Failures 7/5-8/5 (incl. PRs) - [Runfo last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime+name%3A%22jit%2Fperformance%2Fcodequality%2Fbenchmarksgame%2Fbinarytrees%2Fbinarytrees-5%2Fbinarytrees-5.sh%22):

Day | Run | Details
-- | -- | --
8/1 | Rolling run [1915087](https://runfo.azurewebsites.net/view/build/?number=1915087) | [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-07e3b34912ca4cfb85/JIT.1/1/console.3c3ebb9a.log?%3Fhelixlogtype%3Dresult) - mono Linux x64 Release @ Ubuntu.1804.Amd64.Open
7/25 | PR #72275 - [1901021](https://runfo.azurewebsites.net/view/build/?number=1901021) | [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72275-merge-3e0492e237404b0992/JIT.1/1/console.eaf82a43.log?%3Fhelixlogtype%3Dresult) - mono Linux x64 Release @ Ubuntu.1804.Amd64.Open
7/20 | PR #72515 - [1892419](https://runfo.azurewebsites.net/view/build/?number=1892419) | [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72515-merge-7d1f00fb7b53455082/JIT.1/1/console.48455450.log?%3Fhelixlogtype%3Dresult) - mono Linux x64 Release @ Ubuntu.1804.Amd64.Open
7/8 | PR #66304 - [1869768](https://runfo.azurewebsites.net/view/build/?number=1869768) | Console log not available anymore - mono Linux x64 Release @ Ubuntu.1804.Amd64.Open
7/8 | PR #71826 - [1867945](https://runfo.azurewebsites.net/view/build/?number=1867945) | Likely different problem - Console log not available anymore - mono Linux x64 Release @ Ubuntu.1804.Amd64.Open

```
      To run the test:
      > set CORE_ROOT=/datadisks/disk1/work/B0180A0B/p
      > /datadisks/disk1/work/B0180A0B/w/BEE50A1C/e/JIT/Performance/CodeQuality/BenchmarksGame/binarytrees/binarytrees-5/binarytrees-5.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at JIT_Performance._CodeQuality_BenchmarksGame_binarytrees_binarytrees_5_binarytrees_5_._CodeQuality_BenchmarksGame_binarytrees_binarytrees_5_binarytrees_5_sh()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by karelz** [comment] 2022-08-05 11:20
@adamsitnik would you be able to tell if it is problem with perf infra, or with the specific benchmark?
Any idea where to route it?

**Comment by adamsitnik** [comment] 2022-08-05 12:07
@karelz these particular benchmarks are used as unit tests (not to measure perf). Based on:

```log
      Got a SIGSEGV while executing native code. This usually indicates
      a fatal error in the mono runtime or one of the native libraries 
      used by your application.
```

I think it's Mono Runtime bug.

**Comment by naricc** [comment] 2022-08-12 16:51
This looks like it must be a race condition somewhere in the mono runtime. I am trying to reproduce it locally now.

**Comment by naricc** [comment] 2022-08-12 19:05
I haven't yet been able to reproduce this locally, so I think it is probably something that only happens infrequently, and apparently only one linux-arm64? I don't think its a blocker for .net7 and am putting it in the .net8 milestone.

**Comment by SamMonoRT** [comment] 2023-05-17 20:23
@karelz - do we have more recent failures to review the logs ?

@jandupej  - please follow up. Thanks

**Comment by SamMonoRT** [comment] 2023-10-25 18:11
Closing this issue. Should re-open if there are still failures.

**Closed by SamMonoRT** 2023-10-25 18:11 UTC
Labels: area-Codegen-JIT-mono, runtime-mono
