### ISSUE TITLE
How to order child property in System.json.Text to come last during serialization

### ISSUE THREAD

**Issue by KamranShahid** [dotnet/runtime#38199] opened 2020-06-21 10:05 UTC
I have following class in my .net core 3.1 application

 public class FinalsuccessResultForTransactionBase
    {
        [JsonPropertyName("auth_req_id")]
        public string AuthReqId { get; set; }

        [JsonPropertyName("correlation_id")]
        public string CorrelationId { get; set; }

        [JsonPropertyName("expires_in")]
        public int ExpiresIn { get; set; }       
    }

    public class FInalsuccessResultForPolling : FinalsuccessResultForTransactionBase
    {
        [JsonPropertyName("interval")]
        public int Interval { get; set; }
    }

when serializing i am getting it like 
{"interval":10,"auth_req_id":"LoXBka93EiBcCvbwppHA","correlation_id":null,"expires_in":1800}

I wanted it like 

{"auth_req_id":"LoXBka93EiBcCvbwppHA","correlation_id":null,"expires_in":1800,"interval":10}

What should i do

**Comment by srisuk2519** [comment] 2020-06-21 10:20
เมื่อ อา. 21 มิ.ย. 2563 เวลา 17:06 Kamran Shahid <notifications@github.com>
เขียนว่า:

**Comment by Clockwork-Muse** [comment] 2020-06-21 17:01
... Is there a particular reason you want it ordered?  JSON is explicitly unordered.

It looks like this function isn't yet implemented, this is essentially a duplicate of issue #728.  The recommendation there is to create a custom serializer.

**Comment by KamranShahid** [comment] 2020-06-22 09:56
> ... Is there a particular reason you want it ordered? JSON is explicitly unordered.
> 
> It looks like this function isn't yet implemented, this is essentially a duplicate of issue #728. The recommendation there is to create a custom serializer.

There is no big reason for ordering. In my logs i want's certain elements to come first. But it is very strange that basic order feature like newtonsoft is not there

**Comment by Clockwork-Muse** [comment] 2020-06-22 15:34
> But it is very strange that basic order feature like newtonsoft is not there

Because:

> JSON is explicitly unordered.

`System.Text.Json` is a low-level _base_ library for dealing with JSON.  While it's possible to use it to de/serialize JSON with it, it was written in such a way as to be extensible by other libraries, who might do things like provide ordering.  

If you want the items to be ordered to make your logs more readable, I'd actually recommend looking for a tool like Splunk, which can pull such data out, be able to search on it, etc.

**Closed** 2020-06-23 07:31 UTC
Labels: area-System.Text.Json, untriaged

**Comment by layomia** [comment] 2020-07-07 17:39
FWIW - this is a duplicate of https://github.com/dotnet/runtime/issues/728 and is a valid feature to be considered for built-in support.
