### ISSUE TITLE
Assertion failed 'unreached' during 'Lowering nodeinfo'

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#107324] opened 2024-09-03 22:44 UTC
```c#
// Found by Antigen
// Reduced from 60.5 KB to 2 KB.


using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.Arm;
using System.Runtime.Intrinsics.X86;
using System.Numerics;
public class TestClass
{
    public struct S1
    {
    }
    static Vector512<short> s_v512_short_40 = Vector512<short>.AllBitsSet;
    static Vector<short> s_v_short_50 = Vector.Create((short)0);
    static S1 s_s1_61 = new S1();
    bool bool_63 = false;
    Vector512<short> v512_short_100 = Vector512.Create(1, 38, 5, -1, 1, 38, -2, 5, -2, 38, 38, -1, 0, 38, -2, 38, -2, 38, -2, 2, 5, 2, 3, -2, -1, -1, -2, 3, 1, 3, 38, 38);
    Vector<short> v_short_110 = Vector.Create((short)3);
    private static List<string> toPrint = new List<string>();
    public S1 Method1(S1 p_s1_123, out Vector<short> p_v_short_124)
    {
        unchecked
        {
            byte byte_126 = 3;
            p_v_short_124 = v_short_110 | Vector.AsVectorInt16(v_short_110) + s_v_short_50^ v_short_110;
            switch (15%4)
            {
                case 5:
                {
                    break;
                }
                default:
                {
                    int __loopvar8 = 15-4;
                    for (;;)
                    {
                        __loopvar8 += 2;
                        if (__loopvar8 >= 15+4)
                            break;
                        bool_63 = Vector512.EqualsAll((15-4)* Avx512F.TernaryLogic(v512_short_100, Vector512<short>.AllBitsSet, s_v512_short_40, byte_126), v512_short_100);
                    }
                    break;
                }
            }
            return s_s1_61;
        }
    }
    public void Method0()
    {
        unchecked
        {
            s_s1_61 = Method1(s_s1_61, out s_v_short_50);
            return;
        }
    }
    public static void Main(string[] args)
    {
    }
    public static int Antigen()
    {
        new TestClass().Method0();
        return string.Join(Environment.NewLine, toPrint).GetHashCode();
    }
}
/*
Environment:

set DOTNET_JitEdgeProfiling=0
set DOTNET_JitStressEvexEncoding=1
set DOTNET_TieredCompilation=0
set DOTNET_PreferredVectorBitWidth=512
set DOTNET_JitStressRegs=2
set DOTNET_JitThrowOnAssertionFailure=1
set DOTNET_LegacyExceptionHandling=1

Debug: 28101970

Release: 0
JIT assert failed:
Assertion failed 'unreached' in 'TestClass:Method1(TestClass+S1,byref):TestClass+S1:this' during 'Lowering nodeinfo' (IL size 117; hash 0xcd0a9be8; FullOpts)

    File: D:\a\_work\1\s\src\coreclr\jit\lowerxarch.cpp Line: 11752


*/

```

**Comment by JulieLeeMSFT** [comment] 2024-09-13 19:03
@kunalspathak, this seems related or duplicate of https://github.com/dotnet/runtime/issues/107587. PTAL.

**Closed** 2024-09-16 18:40 UTC
Labels: area-CodeGen-coreclr, in-pr
