### ISSUE TITLE
StringBuilder.AppendInterpolatedStringHandler breaks backwards compatibility and violates order-of-execution expectations

### ISSUE THREAD

**Issue by Timwi** [dotnet/runtime#90885] opened 2023-08-21 19:13 UTC
### Description

Consider the following code:

```cs
public static void DoStuff()
{
    var sb = new StringBuilder();
    try
    {
        sb.Append($"X{Throw()}");
    }
    catch { }
    Console.WriteLine(sb);
}

private static string Throw()
{
    throw new NotImplementedException();
}
```

In older versions of .NET (I tried it on .NET Framework 4.8), this outputs an empty string. This is in line with my expectation, as I expect the `Throw` method to be called before `sb.Append`.

# Expected behavior

The code should output the empty string.

This is both for backwards compatibility, and to maintain the programmer’s expectation regarding the order of evaluation.

# Actual behavior

In newer versions of .NET (I tried it on .NET 7.0), this outputs `"X"`. This is because `StringBuilder` now implements the _[interpolated string handler](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/interpolated-string-handler)_ pattern, causing this code to be compiled into the following:

```cs
StringBuilder sb = new StringBuilder();
try
{
    StringBuilder sb2 = sb;
    var aish = new StringBuilder.AppendInterpolatedStringHandler(1, 1, sb2);
    aish.AppendLiteral("X");
    aish.AppendFormatted(Throw());
    sb2.Append(ref aish);
}
catch
{
}
```

Stepping through this code with the debugger reveals that `aish.AppendLiteral("X");` appends `X` to the `StringBuilder` immediately, before the exception is thrown.

**Comment by 333fred** [comment] 2023-08-21 20:51
Duplicate of https://github.com/dotnet/roslyn/issues/57006. This is an intentional breaking change in the behavior of `StringBuilder`. /cc @stephentoub.

**Closed by 333fred** 2023-08-21 20:51 UTC
Labels: untriaged, needs-area-label

**Comment by 333fred** [comment] 2023-08-21 20:53
This was also documented here: https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/stringbuilder-append-evaluation-order.

**Comment by vcsjones** [comment] 2023-08-21 20:53
This is also a documented at https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/stringbuilder-append-evaluation-order.
