### ISSUE TITLE
Test failure: Loader\\classloader\\TypeGeneratorTests\\TypeGeneratorTest24\\Generated24\\Generated24.cmd

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#34884] opened 2020-04-13 05:58 UTC
failed in job: [runtime-coreclr gcstress-extra 20200412.1](https://dev.azure.com/dnceng/public/_build/results?buildId=598025&view=ms.vss-test-web.build-test-results-tab&runId=18836346&resultId=110530&paneView=debug)

Error message
~~~
cmdLine:C:\h\w\B96409E2\w\A6F108EC\e\Loader\classloader\TypeGeneratorTests\TypeGeneratorTest24\Generated24\Generated24.cmd Timed Out
Return code: -100
Raw output file: C:\h\w\B96409E2\w\A6F108EC\e\Loader\classloader\Reports\Loader.classloader\TypeGeneratorTests\TypeGeneratorTest24\Generated24\Generated24.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\B96409E2\p\corerun.exe" Generated24.dll 
cmdLine:C:\h\w\B96409E2\w\A6F108EC\e\Loader\classloader\TypeGeneratorTests\TypeGeneratorTest24\Generated24\Generated24.cmd Timed Out
Test Harness Exitcode is : -100
To run the test:
> set CORE_ROOT=C:\h\w\B96409E2\p
> C:\h\w\B96409E2\w\A6F108EC\e\Loader\classloader\TypeGeneratorTests\TypeGeneratorTest24\Generated24\Generated24.cmd
Expected: True
Actual: False


Stack trace
   at Loader_classloader._TypeGeneratorTests_TypeGeneratorTest24_Generated24_Generated24_._TypeGeneratorTests_TypeGeneratorTest24_Generated24_Generated24_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x64.Checked\TestWrappers\Loader.classloader\Loader.classloader.XUnitWrapper.cs:line 21674
~~~

**Comment by jkotas** [comment] 2020-04-13 06:43
@fadimounir Is this duplicate of one of the GC stress issues you have been looking into?

**Comment by fadimounir** [comment] 2020-04-13 19:44
@jkotas I can't tell from the logs. I'll debug this and see where it fails, and add more details here.

**Comment by davidwrighton** [comment] 2020-08-04 00:58
I can't reproduce this issue, and there isn't enough detail here for me to examine. I recommend we close this issue.

**Comment by mangod9** [comment] 2020-08-04 05:41
Thanks @davidwrighton for investigating. Closing for now, @v-haren please reopen if this repros again.

**Closed by mangod9** 2020-08-04 05:41 UTC
Labels: GCStress, area-TypeSystem-coreclr
