### ISSUE TITLE
[Perf -32%] System.Collections.CtorFromCollection<Int32>.SortedSet

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#39037] opened 2020-07-09 22:25 UTC
### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Changes | [diff](https://github.com/dotnet/runtime/compare/a4a49f07fbf986d496ef57521e76b22caaf9bfb3...3c6656f83b01ece6af7e11eb75ec0145554b139d)

### Regressions in System.Collections.CtorFromCollection<Int32>

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier
-- | -- | -- | -- | -- | --
SortedSet | 10.04 μs | 14.72 μs | 1.47 |  | True

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_09_2020/release/3.1.1xx%20-%3E%20master_x64_Windows%2010.0.18362/System.Collections.CtorFromCollection(Int32)_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_09_2020/release/3.1.1xx%20-%3E%20master_x64_Windows%2010.0.18362/System.Collections.CtorFromCollection(Int32).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Collections.CtorFromCollection<Int32>*';
```
<details>

#### System.Collections.CtorFromCollection<Int32>.SortedSet(Size: 512)

```log
[ 9518.251 ;  9851.577) | @@@@@
[ 9851.577 ; 10317.085) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[10317.085 ; 10658.312) | @@@@@@@@@@@@@@@@@@@@
[10658.312 ; 11123.820) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[11123.820 ; 11551.479) | @@@@@@@@@@
[11551.479 ; 12016.987) | 
[12016.987 ; 12253.244) | 
[12253.244 ; 12718.752) | @
[12718.752 ; 13184.261) | 
[13184.261 ; 13649.769) | 
[13649.769 ; 14350.458) | @@@@@@@@@@@@@@@
[14350.458 ; 14813.499) | @@@
[14813.499 ; 15279.007) | 
[15279.007 ; 15744.515) | 
[15744.515 ; 16039.150) | 
[16039.150 ; 16519.120) | @@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by stephentoub** [comment] 2020-07-10 13:51
I don't see this locally.  I consistently see .NET 5.0 being a few percent faster than .NET Core 3.1:
```
dotnet run -c Release -f netcoreapp3.1 --runtimes netcoreapp3.1 netcoreapp5.0 --filter="System.Collections.CtorFromCollection<Int32>.SortedSet"
```

|    Method |        Job |       Runtime |     Toolchain | Size |     Mean |     Error |    StdDev |   Median |      Min |      Max | Ratio |  Gen 0 |  Gen 1 | Gen 2 | Allocated |
|---------- |----------- |-------------- |-------------- |----- |---------:|----------:|----------:|---------:|---------:|---------:|------:|-------:|-------:|------:|----------:|
| SortedSet | Job-YCVRUX | .NET Core 3.1 | netcoreapp3.1 |  512 | 8.550 us | 0.0783 us | 0.0695 us | 8.557 us | 8.422 us | 8.689 us |  1.00 | 3.5704 | 0.4853 |     - |  22.07 KB |
| SortedSet | Job-ODNIEW | .NET Core 5.0 | netcoreapp5.0 |  512 | 8.086 us | 0.0830 us | 0.0776 us | 8.094 us | 7.959 us | 8.221 us |  0.95 | 3.5733 | 0.4873 |     - |  22.07 KB |

**Comment by DrewScoggins** [comment] 2020-07-10 17:47
Here is what I measured on my machine, which look consistent with what the lab is producing. I wonder if this is some kind of architectural difference?

```
.\scripts\benchmarks_ci.py -f netcoreapp3.1 --bdn-arguments="--filter System.Collections.CtorFromCollection<Int32>.SortedSet"
```

|    Method | Size |     Mean |    Error |   StdDev |   Median |      Min |      Max |  Gen 0 |  Gen 1 | Gen 2 | Allocated |
|---------- |----- |---------:|---------:|---------:|---------:|---------:|---------:|-------:|-------:|------:|----------:|
| SortedSet |  512 | 14.28 us | 0.173 us | 0.154 us | 14.23 us | 14.12 us | 14.59 us | 5.3571 | 0.0576 |     - |  22.07 KB |

```
.\scripts\benchmarks_ci.py -f netcoreapp3.1 --bdn-arguments="--filter System.Collections.CtorFromCollection<Int32>.SortedSet"
```

|    Method | Size |     Mean |    Error |   StdDev |   Median |      Min |      Max |  Gen 0 |  Gen 1 | Gen 2 | Allocated |
|---------- |----- |---------:|---------:|---------:|---------:|---------:|---------:|-------:|-------:|------:|----------:|
| SortedSet |  512 | 10.73 us | 0.186 us | 0.174 us | 10.68 us | 10.50 us | 11.13 us | 5.3901 | 0.0856 |     - |  22.07 KB |

**Comment by DrewScoggins** [comment] 2020-07-10 21:51
We are also seeing this on Ubuntu x64

**Comment by DrewScoggins** [comment] 2020-07-10 21:51
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Changes | [diff](https://github.com/dotnet/runtime/compare/a4a49f07fbf986d496ef57521e76b22caaf9bfb3...3c6656f83b01ece6af7e11eb75ec0145554b139d)


### Regressions in System.Collections.CtorFromCollection<Int32>

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier
-- | -- | -- | -- | -- | --
SortedList | 5.60 μs | 8.73 μs | 1.56 |  | False

### Related Issue on x64 Windows
[[Perf -32%] System.Collections.CtorFromCollection<Int32>.SortedSet](https://github.com/DrewScoggins/performance-2/issues/874)

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_10_2020/release/3.1.1xx%20-%3E%20master_x64_ubuntu%2018.04/System.Collections.CtorFromCollection(Int32)_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_10_2020/release/3.1.1xx%20-%3E%20master_x64_ubuntu%2018.04/System.Collections.CtorFromCollection(Int32).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Collections.CtorFromCollection<Int32>*';
```
<details>

### Histogram
#### System.Collections.CtorFromCollection<Int32>.SortedList(Size: 512)

```log
[5143.234 ;  5891.826) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[5891.826 ;  6640.417) | 
[6640.417 ;  7041.291) | 
[7041.291 ;  7789.883) | @@@@@@@@@@@
[7789.883 ;  8169.993) | 
[8169.993 ;  8850.638) | @@@@@@@@@
[8850.638 ;  9599.230) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[9599.230 ; 10588.490) | @@@@@@@@@@@@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by danmosemsft** [comment] 2020-08-01 00:53
Duplicate of #39112

**Closed by danmosemsft** 2020-08-01 00:53 UTC
Labels: arch-x64, area-System.Collections, os-linux, os-windows, tenet-performance, tenet-performance-benchmarks, untriaged
