### ISSUE TITLE
Mono add support for System.Runtime.CompilerServices.IgnoresAccessChecksToAttribute

### ISSUE THREAD

**Issue by Clancey** [dotnet/runtime#48012] opened 2021-02-08 20:25 UTC
When you compile an assembly with the Attribute `[assembly: IgnoresAccessChecksTo("OtherAssembly")]` You can reference internals to the specified OtherAssembly. This works in CoreCLR, but fails in MonoVM.

**Comment by lambdageek** [comment] 2021-02-08 20:32
`IgnoresAccessChecksToAttribute` is not part of the BCL. It's an implementation detail on CoreCLR.

That said it does seem like it would be useful to bypass method access checks in some scenarios.

**Comment by lambdageek** [comment] 2021-02-08 20:54
It seems like `IgnoresAccessChecksToAttribute` is meant to be used for some SRE scenarios, but in fact it works with normal compiled assemblies too.

**Comment by lambdageek** [comment] 2021-02-16 17:51
Duplicate of https://github.com/dotnet/runtime/issues/47989 which has some runtime tests that are currently disabled on Mono.

**Closed** 2021-02-16 18:50 UTC
Labels: area-VM-meta-mono, runtime-mono
