### ISSUE TITLE
Console output no longer working dotnet run and UseWindowsForms

### ISSUE THREAD

**Issue by sipsorcery** [dotnet/runtime#41922] opened 2020-09-06 22:03 UTC
### Description

For console applications that need to display a Windows Form executing the project with `dotnet run` displayed `Console.Write*` output in the same manner as a standard console application.

With `.NET SDK (5.0.100-preview.8.20417.9)` console output is no longer displayed.

If the program is built with Visual Studio and then run from directly from the `.exe`, with the Visual Studio debugger or with `dotnet run --no-build` then console output works properly.

If the program is build and run with `dotnet run` console output does not appear.

### Configuration

.NET SDK (5.0.100-preview.8.20417.9)
Microsoft Windows 10 Pro 10.0.19041 Build 19041
x64

### Other information

Minimal project and program file to replicate:

```
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

</Project>
```

```
using System;

class Program
{
    [STAThread]
    static void Main(string[] args)
    {
        Console.WriteLine("Hello World!");
    }
}
```

 - Build and execute with `dotnet run` will not display anything on the console.
 - Rebuild with Visual Studio and execute with `dotnet run --no-build` will display console output.
 -  Build and execute again with `dotnet run` will not display anything on the console.

**Comment by jeffhandley** [comment] 2020-09-17 01:40
> With `.NET SDK (5.0.100-preview.8.20417.9)` console output is no longer displayed.

@sipsorcery Thanks for reporting this.  With your statement that "output is no longer displayed," does that imply that you saw this working with a previous version and is therefore a regression in 5.0?

**Comment by sipsorcery** [comment] 2020-09-17 07:20
>  does that imply that you saw this working with a previous version and is therefore a regression in 5.0?

Yes. I was definitely getting normal console output on this type of mixed console/forms application up until very recently.

I spent some more time trying to find a combination of `dotnet run` with `--framework` and/or `--runtime` that would work but to no avail. The best I can get is to build with the Visual Studio 2019 IDE and then use `--no-build`.

```
dotnet run --no-build
Hello World!
```

**Comment by adamsitnik** [comment] 2020-09-17 09:20
I suspect that it is a by-design change in WinForms 5.0.

@JeremyKuhne do you happen to know if writing to console has been disabled in WinForms for .NET 5?

**Comment by JeremyKuhne** [comment] 2020-09-17 17:49
> do you happen to know if writing to console has been disabled in WinForms for .NET 5?

Nothing was done in WinForms afaik, nor would we explicitly want to remove said functionality. This should be below the WinForms level.

**Comment by jkotas** [comment] 2020-09-18 15:49
This is duplicate of https://github.com/dotnet/sdk/issues/13331. https://github.com/dotnet/sdk/issues/13331#issuecomment-693002436 describes workaround you can use to get to the old behavior.

**Closed by jkotas** 2020-09-18 15:49 UTC
Labels: area-System.Console, untriaged
