### ISSUE TITLE
SystemTextJsonInputFormatter: System.FormatException message is lost when using custom serialization of array of objects

### ISSUE THREAD

**Issue by eduard-bystrov** [dotnet/runtime#51931] opened 2021-04-27 15:27 UTC
### Describe

SystemTextJsonInputFormatter loses more precise error information if a custom serializer is used.

If we use the default serializer, we get:

```json
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "00-0a745e7cd4f3a54285fd23a63ef45719-8eb8fcce60d17d4c-00",
  "errors": {
    "$[0].Value": [
      "The JSON value could not be converted to System.Int32. Path: $[0].Value | LineNumber: 0 | BytePositionInLine: 28."
    ]
  }
}
```

for custom:

```json
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "00-808695bb8f38cd4da21e2ed40e4f8a96-782fdf452d3db945-00",
  "errors": {
    "$[0]": [
      "The JSON value could not be converted to WebApplication1.Controllers.ClassName. Path: $[0] | LineNumber: 0 | BytePositionInLine: 28."
    ]
  }
}
```

Is it possible to improve this behavior?
Or should we only use Utf8JsonReader.TryGet methods and wrap the exceptions ourselves?

### To Reproduce

https://gist.github.com/eduard-bystrov/11f02d98fedb3846a92c7974c9715bc6 - aspnetcore example

https://gist.github.com/eduard-bystrov/977a02133c6273d1b493de237bb0000b - runtime example

### Further technical details

ASP.NET Core 3.1 and 5.0.5

**Comment by pranavkm** [comment] 2021-04-27 15:38
Moving to the runtime repo. The value in error message is the `JsonException` that gets thrown by the serializer.

**Comment by eiriktsarpalis** [comment] 2021-04-27 16:58
This seems related to #51537.

**Comment by eiriktsarpalis** [comment] 2021-07-21 16:06
Closing as duplicate of #51537.

**Closed by eiriktsarpalis** 2021-07-21 16:06 UTC
Labels: area-System.Text.Json, untriaged
