### ISSUE TITLE
Mixing open and closed service injections results in resolving unexpected services

### ISSUE THREAD

**Issue by NVedsted** [dotnet/runtime#76372] opened 2022-09-29 11:23 UTC
### Description

Say you have a generic service interface `S<T>`, if you inject a service implementation `A` for `S<int>` followed by a generic implementation `B<T>` for an open generic service `S<>` and you validate your service provider upon it being built, then resolving all services for `S<int>` will yield two `A`s.

On the contrary, if you disabled validation on service-provider build, you will resolve `A` and `B<int>` as one would expect. Furthermore, if you flip the registration order of `A` and `B`, it also behaves as expected.

It is hopefully unintended that validating on build can change behavior of the provider. 😄

### Reproduction Steps

The issue can be reproduced with this simple C# program:
```cs
using System;
using Microsoft.Extensions.DependencyInjection;

var services = new ServiceCollection()
	.AddTransient<S<int>, A>()
	.AddTransient(typeof(S<>), typeof(B<>));

var provider = services.BuildServiceProvider(new ServiceProviderOptions {ValidateOnBuild = true});
var resolvedServices = provider.GetServices<S<int>>();
foreach (var resolvedService in resolvedServices)
{
	Console.WriteLine(resolvedService);
}

interface S<T>
{
}

class A : S<int>
{
}

class B<T> : S<T>
{
}
```

### Expected behavior

When you resolve services for `S<int>`, I would expect to get `A` and `B<int>`.

### Actual behavior

When you resolve services for `S<int>`, you get  `A` and `A`.

### Known Workarounds

There are two workarounds:
1. Ensure you register open generic services before concrete ones.
2. Disable validation on build (Bad idea!)

### Configuration

Reproduced in .NET 6.0.4.

### Other information

I found this weird behavior by debugging deeply into the .NET internals from our application code; a place I am not familiar with so please bear with me, haha.

What I discovered was that after the validation on build when calling `GetServices` on the service provider, the internal `CallSiteFactory`'s `_callSiteCache` for the service type in slot 0 would differ from the first service descriptor it would encounter when enumerating the service descriptors. In this case, `TryCreateOpenGeneric` would be called with the correct descriptor, but the cache hit would instead return a constructor call site for the concrete implementation (i.e. not the open generic one).

I hope this can assist a bit since I am on very deep water here. 😜

**Comment by NVedsted** [comment] 2022-09-29 11:31
Now that I have put a bit of thought into it, I assume it is because validation ignores open generic types as they would be impossible to validate without type parameters and thus the cache order is messed up since they are ignored.

**Comment by eerhardt** [comment] 2022-09-29 13:06
Looks like a duplicate of https://github.com/dotnet/runtime/issues/65145

**Comment by NVedsted** [comment] 2022-09-29 13:48
Yea, seems to be the same issue. I think I missed it because I was filtering on the "bug" label which that issue does not have for some reason.

**Comment by eerhardt** [comment] 2022-09-29 14:06
>  I was filtering on the "bug" label which that issue does not have for some reason. EDIT: Neither does mine, I assume it is only for confirmed bugs?

The "bug" label is not used consistently in the repo. I wouldn't rely on it.

**Closed** 2022-09-29 14:05 UTC
Labels: untriaged, area-Extensions-DependencyInjection
