### ISSUE TITLE
Official build failed on linux-musl-arm64 due to NRE in crossgen2

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#69454] opened 2022-05-17 19:00 UTC
https://dev.azure.com/dnceng/internal/_build/results?buildId=1775666&view=logs&j=b9eb5783-a2c8-5a70-249a-67adf7218800&t=6beaa1d0-e4b4-5a1b-39b5-01b066371742

Note: this is the crossgen that is not NativeAOT'd.

**Comment by jakobbotsch** [comment] 2022-05-17 20:22
Possibly related: #69192

**Comment by mangod9** [comment] 2022-08-04 05:45
@trylek @MichalStrehovsky do you know if this is still blocking/failing within builds?

**Comment by trylek** [comment] 2022-08-04 10:28
If this is indeed a duplicate of #69192 (hard to say as the issue title doesn't include any details and the quoted run is long gone but I think I looked at it while it still existed and it did look similar) then it's a manifestation of the generic cycle problem I talked about yesterday. I'll try to attack it using the tool DavidWr described in the Crossgen2 sync-up meeting.

**Comment by mangod9** [comment] 2022-08-23 21:44
@AntonLapounov @trylek perhaps we can consolidate these arm64 related failures into a single issue. Currently there are a few open for 7 which look similar?

**Comment by AntonLapounov** [comment] 2022-08-23 22:52
No details are recorded in this issue. Closing as a duplicate.

**Closed by AntonLapounov** 2022-08-23 22:52 UTC
Labels: area-crossgen2-coreclr, blocking-official-build
