### ISSUE TITLE
Test failure JIT\\Methodical\\xxobj\\operand\\refanyval\\refanyval.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#60278] opened 2021-10-12 01:12 UTC
Run:  [runtime-coreclr outerloop 20211011.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1413911&view=ms.vss-test-web.build-test-results-tab&runId=40978524&resultId=107283&paneView=debug)

Failed test:
```
R2R-CG2 windows arm Checked @ Windows.10.Arm64v8.Open

- JIT\\Methodical\\xxobj\\operand\\refanyval\\refanyval.cmd

```
**Error message:**
```
Could Not Find D:\h\w\A5D2099F\w\ADDF09A6\e\JIT\Methodical\xxobj\operand\refanyval\IL-CG2\composite-r2r.dll
Could Not Find D:\h\w\A5D2099F\w\ADDF09A6\e\JIT\Methodical\xxobj\operand\refanyval\refanyval.dll.rsp
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
at System.Runtime.InteropServices.NativeLibrary.LoadByName(System.String, System.Runtime.CompilerServices.QCallAssembly, Boolean, UInt32, Boolean)
at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(System.String, System.Reflection.Assembly, System.Nullable1<System.Runtime.InteropServices.DllImportSearchPath>, Boolean) at System.Runtime.InteropServices.NativeLibrary.Load(System.String, System.Reflection.Assembly, System.Nullable1<System.Runtime.InteropServices.DllImportSearchPath>)
at Internal.JitInterface.JitConfigProvider+<>c__DisplayClass5_0.<Initialize>b__0(System.String, System.Reflection.Assembly, System.Nullable1<System.Runtime.InteropServices.DllImportSearchPath>) at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(System.String, System.Reflection.Assembly, Boolean, UInt32) at Internal.JitInterface.CorInfoImpl.FreeException(IntPtr) at Internal.JitInterface.CorInfoImpl.FreeException(IntPtr) at Internal.JitInterface.CorInfoImpl.CompileMethodCleanup() at Internal.JitInterface.CorInfoImpl.CompileMethod(ILCompiler.DependencyAnalysis.ReadyToRun.MethodWithGCInfo, ILCompiler.Logger) at ILCompiler.ReadyToRunCodegenCompilation.<ComputeDependencyNodeDependencies>b__35_0(ILCompiler.DependencyAnalysisFramework.DependencyNodeCore1<ILCompiler.DependencyAnalysis.NodeFactory>)
at System.Threading.Tasks.Parallel+<>c__DisplayClass33_02[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForEachWorker>b__0(Int32) at System.Threading.Tasks.Parallel+<>c__DisplayClass19_01[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef, Int32, Boolean ByRef)
at System.Threading.Tasks.TaskReplicator+Replica.Execute()
at System.Threading.Tasks.TaskReplicator+Replica+<>c.<.ctor>b__4_0(System.Object)
at System.Threading.Tasks.Task.InnerInvoke()
at System.Threading.Tasks.Task+<>c.<.cctor>b__271_0(System.Object)
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
at System.Threading.Thread.StartCallback()

Return code:      1
Raw output file:      D:\h\w\A5D2099F\w\ADDF09A6\uploads\Reports\JIT.Methodical\xxobj\operand\refanyval\refanyval.output.txt
Raw output:
BEGIN EXECUTION
refanyval.dll
1 file(s) copied.
Response file: D:\h\w\A5D2099F\w\ADDF09A6\e\JIT\Methodical\xxobj\operand\refanyval\refanyval.dll.rsp
D:\h\w\A5D2099F\w\ADDF09A6\e\JIT\Methodical\xxobj\operand\refanyval\IL-CG2\refanyval.dll
-o:D:\h\w\A5D2099F\w\ADDF09A6\e\JIT\Methodical\xxobj\operand\refanyval\refanyval.dll
--targetarch:arm
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\A5D2099F\p\System..dll
-r:D:\h\w\A5D2099F\p\Microsoft..dll
-r:D:\h\w\A5D2099F\p\mscorlib.dll
-r:D:\h\w\A5D2099F\p\netstandard.dll
-O
" "dotnet" "D:\h\w\A5D2099F\p\crossgen2\crossgen2.dll" @"D:\h\w\A5D2099F\w\ADDF09A6\e\JIT\Methodical\xxobj\operand\refanyval\refanyval.dll.rsp"   -r:D:\h\w\A5D2099


Stack trace
   at JIT_Methodical._xxobj_operand_refanyval_refanyval_._xxobj_operand_refanyval_refanyval_cmd()
```

**Comment by trylek** [comment] 2022-04-04 20:42
Closing as duplicate of: https://github.com/dotnet/runtime/issues/66570

**Closed by trylek** 2022-04-04 20:42 UTC
Labels: os-windows, area-crossgen2-coreclr, untriaged
