### ISSUE TITLE
Compiling .NET 8 into native AOT was detected as a trojan virus by antivirus software.

### ISSUE THREAD

**Issue by hbl917070** [dotnet/runtime#105959] opened 2024-08-05 16:49 UTC
### Description

Compiling a blank .NET 8 project into native AOT was detected as a trojan virus by multiple antivirus software.

### Reproduction Steps

1. Create a blank .NET 8 project.

2. Enter the code:
```C#
Console.WriteLine("Hello, World!");
````

The csproj file uses default values.
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
</Project>
```

3. Compile it into an exe using:
```
dotnet publish -r win-x64 -c Release
```

4. Upload the compiled exe to VirusTotal.
![image](https://github.com/user-attachments/assets/73ca697b-459b-4453-8a68-57aaa2eef6ca)

https://www.virustotal.com/gui/file/e9f1ff6a2b8b1ec7da4a7d61c2efa54dd5b047d20c27235359f37540cc3cbccb?nocache=1

### Expected behavior

I understand that some antivirus software may give false positives, but the probability of an exe compiled into native AOT being misidentified is too high. Even Microsoft’s own antivirus misidentifies it as a trojan virus, which is clearly unreasonable.

I tested Microsoft’s antivirus, and it does not flag an exe compiled from a blank C++ project as a trojan virus.
![2024-08-06 00-16-00](https://github.com/user-attachments/assets/0c176fac-32ba-4aa7-8173-2f2acfad2a6b)
https://www.virustotal.com/gui/file/0e1d9923cd7718c8caedaf55d13e86e520ac257e227c7c3a262aa4c9bc0dc011?nocache=1

### Actual behavior

Inspection report of a blank .NET8 native AOT project
https://www.virustotal.com/gui/file/e9f1ff6a2b8b1ec7da4a7d61c2efa54dd5b047d20c27235359f37540cc3cbccb?nocache=1

Inspection report of a blank C++ project
https://www.virustotal.com/gui/file/0e1d9923cd7718c8caedaf55d13e86e520ac257e227c7c3a262aa4c9bc0dc011?nocache=1

### Configuration

OS: Windows 10 x64 (22H2)
.NET SDK: 8.0.303

**Comment by jkotas** [comment] 2024-08-05 17:17
Related / duplicate of #33745

**Comment by MichalStrehovsky** [comment] 2024-08-06 07:33
I've submitted this at https://www.microsoft.com/en-us/wdsi/filesubmission as a false positive. There's not much else we can do.

**Closed by MichalStrehovsky** 2024-08-06 07:33 UTC
Labels: untriaged, area-NativeAOT-coreclr
