### ISSUE TITLE
Thousands of tests failed with Code generation failure for method

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#50631] opened 2021-04-02 02:50 UTC
Run: [runtime-coreclr crossgen2 20210331.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1067270&view=ms.vss-test-web.build-test-results-tab&runId=32833114&resultId=102207&paneView=debug)

**One of error message:**
```
/private/tmp/helix/working/B26409B5/w/A4060956/e/baseservices/callconvs/TestCallingConventions/TestCallingConventions.sh: line 254: -r:/private/tmp/helix/working/B26409B5/w/A4060956/e/baseservices/callconvs/TestCallingConventions/IL-CG2/.dll: No such file or directory
rm: /private/tmp/helix/working/B26409B5/w/A4060956/e/baseservices/callconvs/TestCallingConventions/CallFunctionPointers.dll.rsp: No such file or directory
rm: /private/tmp/helix/working/B26409B5/w/A4060956/e/baseservices/callconvs/TestCallingConventions/TestCallingConventions.dll.rsp: No such file or directory
Unhandled exception. System.AggregateException: One or more errors occurred. (Code generation failed for method '[TestCallingConventions]Program+<>c__DisplayClass1_0.<BlittableFunctionPointers>b__0()') (Code generation failed for method '[TestCallingConventions]Program+<>c__DisplayClass2_0.<NonblittableFunctionPointers>b__0()')
 ---> ILCompiler.CodeGenerationFailedException: Code generation failed for method '[TestCallingConventions]Program+<>c__DisplayClass1_0.<BlittableFunctionPointers>b__0()'
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
 at ILCompiler.ReadyToRunCompilationModuleGroupBase.VersionsWithType(TypeDesc typeDesc)
 at ILCompiler.DependencyAnalysis.ReadyToRun.ModuleTokenResolver.AddModuleTokenForType(TypeDesc type, ModuleToken token)
 at Internal.JitInterface.CorInfoImpl.resolveToken(CORINFO_RESOLVED_TOKEN& pResolvedToken)
 at Internal.JitInterface.CorInfoImpl._resolveToken(IntPtr thisHandle, IntPtr ppException, CORINFO_RESOLVED_TOKEN* pResolvedToken)
 --- End of inner exception stack trace ---
 at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(IMethodNode methodCodeNodeNeedingCode, MethodIL methodIL)
 at Internal.JitInterface.CorInfoImpl.CompileMethod(MethodWithGCInfo methodCodeNodeNeedingCode, Logger logger)
 at ILCompiler.ReadyToRunCodegenCompilation.<ComputeDependencyNodeDependencies>b__36_0(DependencyNodeCore1 dependency)
 at System.Threading.Tasks.Parallel.<>c__DisplayClass33_02.<ForEachWorker>b__0(Int32 i)
 at System.Threading.Tasks.Parallel.<>c__DisplayClass19_01.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
 at System.Threading.Tasks.Parallel.<>c__DisplayClass19_01.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
 at System.Threading.Tasks.TaskReplicator.Replica1.ExecuteAction(Boolean& yieldedBeforeCompletion)
 at System.Threading.Tasks.TaskReplicator.Replica.Execute()
 --- End of inner exception stack trace ---
 at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction1 action, ParallelOptions options, Boolean stopOnFirstFailure)
 at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action1 body, Action2 bodyWithState, Func4 bodyWithLocal, Func1 localInit, Action1 localFinally)
--- End of stack trace from previous location ---
 at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
 at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action1 body, Action2 bodyWithState, Func4 bodyWithLocal, Func1 localInit, Action1 localFinally)
 at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IList1 list, ParallelOptions parallelOptions, Action1 body, Action2 bodyWithState, Action3 bodyWithStateAndIndex, Func4 bodyWithStateAndLocal, Func5 bodyWithEverything, Func1 localInit, Action1 localFinally)
 at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable1 source, ParallelOptions parallelOptions, Action1 body, Action`2 bodyWi

Stack trace
   at baseservices_callconvs._TestCallingConventions_TestCallingConventions_._TestCallingConventions_TestCallingConventions_sh()

```

**Comment by BruceForstall** [comment] 2021-04-02 17:18
@dotnet/crossgen-contrib

**Comment by trylek** [comment] 2021-04-02 17:25
I believe this is a dupe of https://github.com/dotnet/runtime/issues/50520; JanK fixed it yesterday with https://github.com/dotnet/runtime/pull/50539.

**Closed** 2021-04-11 23:25 UTC
Labels: arch-arm64, arch-x64, area-crossgen2-coreclr, os-linux, os-mac-os-x, os-windows, untriaged
