### ISSUE TITLE
[API Proposal]: Add a generic overload for `SerializationInfo.GetValue(string name, Type type)`

### ISSUE THREAD

**Issue by Takym** [dotnet/runtime#65783] opened 2022-02-23 16:06 UTC
### Background and motivation

I have to write two same type names to get value from [`SerializationInfo`](https://docs.microsoft.com/dotnet/api/system.runtime.serialization.serializationinfo).
To solve this, I write an extension function with a generic parameter.
Assume I use many libraries that use `SerializationInfo`, probably have many same extension functions.
I know [`BinaryFormatter`](https://docs.microsoft.com/dotnet/api/system.runtime.serialization.formatters.binary.binaryformatter) is deprecated, but I use [`ISerializable`](https://docs.microsoft.com/dotnet/api/system.runtime.serialization.iserializable) also on [`DataContractSerializer`](https://docs.microsoft.com/dotnet/api/system.runtime.serialization.datacontractserializer) for a complicated class.

### API Proposal

```cs
namespace System.Runtime.Serialization
{
    public sealed class SerializationInfo
    {
        public T? GetValue<T>(string name);
    }
}
```

### API Usage

```cs
using System;
using System.Runtime.Serialization;

[Serializable()]
public class Fancy : ISerializable
{
    public OtherSerializableObject? GoodProperty { get; set; }

    public Fancy() { }

    protected Fancy(SerializationInfo info, StreamingContext context)
    {
        // Using the proposing API. Shorter than the current API.
        this.GoodProperty = info.GetValue<OtherSerializableObject>(nameof(GoodProperty));

        // Using the current API.
        this.GoodProperty = info.GetValue(nameof(GoodProperty), typeof(OtherSerializableObject)) as OtherSerializableObject;
    }
}
```

### Alternative Designs

Name `Get` instead of `GetValue` to be shorter more.
```cs
namespace System.Runtime.Serialization
{
    public sealed class SerializationInfo
    {
        public T? Get<T>(string name);
    }
}
```

**Comment by koszeggy** [comment] 2022-02-23 20:06
Hmm, it seems I'm not the only one who created some [extensions](https://docs.kgysoft.net/corelibraries/?topic=html/T_KGySoft_Serialization_Binary_SerializationInfoExtensions.htm) for the `SerializationInfo` class... 😁

**Comment by jkotas** [comment] 2022-02-24 05:44
This is duplicate of https://github.com/dotnet/runtime/issues/24908

We are in the process of obsoleting binary formatter: https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md . It will make the SerializationInfo type irrelevant.

**Closed by jkotas** 2022-02-24 05:44 UTC
Labels: api-suggestion, area-Serialization, untriaged
