### ISSUE TITLE
Hang in NamedPipeTest_ServerOut_ClientIn_Synchronous.ClonedServer_ActsAsOriginalServer

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#72581] opened 2022-07-21 05:04 UTC
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72553-merge-82bdef5d6910471a86/System.IO.Pipes.Tests/1/console.abbf04fb.log?helixlogtype=result

System.IO.Pipes.Tests: [Long Running Test] 'System.IO.Pipes.Tests.NamedPipeTest_ServerOut_ClientIn_Synchronous.ClonedServer_ActsAsOriginalServer', Elapsed: 00:14:06
['System.IO.Pipes.Tests' END OF WORK ITEM LOG: Command timed out, and was killed]

Console log: 'System.IO.Pipes.Tests' from job 82bdef5d-6910-471a-864b-8630d41f0e07 workitem 310b2610-912e-461d-a4af-cdc9497498ec (windows.7.amd64.open.rt) executed on machine a000BOL

Not actionable yet but starting an issue. Is this Windows 7 specific?

https://github.com/dotnet/runtime/pull/72553

**Comment by stephentoub** [comment] 2022-07-21 12:00
Duplicate of https://github.com/dotnet/runtime/issues/72585

**Closed by stephentoub** 2022-07-21 12:00 UTC
Labels: area-System.IO
