### ISSUE TITLE
API Discussion: HttpContent

### ISSUE THREAD

**Issue by stevejgordon** [dotnet/runtime#91111] opened 2023-08-25 08:57 UTC
I wanted to start a discussion before crafting a formal API proposal.

For context, I'm working on adding OpenTelemetry instrumentation to our `Elastic.Transport` library. We are using the `Activity` API. On our spans (which essentially are HTTP calls), we would like to include the `http.response.body.size` attribute as recommended in the [semantic conventions](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/http-spans.md?plain=1#L102). 

Today, when receiving a `HttpResponseMessage` via `HttpClient` from the server that is compressed, e.g. using GZip, the original `HttpContent` is [wrapped inside](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/DecompressionHandler.cs#L81) `GZipDecompressedContent`. The base `DecompressedContent` then [nulls](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/DecompressionHandler.cs#L122) the `ContentLength` header.

The problem this presents is that we lose access to the original ContentLength for the response. `DecompressedContent` and `GZipDecompressedContent` are both private, so we can cast to those types to access any other details, such as the original `HttpContent`. Are there any viable workarounds to access the required information? If not, would an API proposal be worthwhile here?

One option is for the "lost information" to be exposed on the base `HttpContent`.

A second is to consider making `DecompressedContent` public and then include a property to access the original `HttpContent`.

A third option is to not remove the `Content-Length` header in `DecompressedContent` as although its value won't match the length of the decompressed content, it's still valid as the original `Content-Length` sent over the wire.

**Comment by karelz** [comment] 2023-10-03 16:35
Duplicate of #42789

**Comment by karelz** [comment] 2023-10-03 16:35
@stevejgordon looks like generalized version of the dupe. Let's keep the discussion there.
How painful is it for you at the moment?

**Closed by karelz** 2023-10-03 16:35 UTC
Labels: area-System.Net.Http, needs-further-triage

**Comment by stevejgordon** [comment] 2023-11-10 09:30
@karelz Sounds good. It's not a major issue for us right now, but we would ideally like to be able to access the information in some form. Ideally, the .NET HttpClient code would emit the received bytes as a Span attribute when using OTel.
