### ISSUE TITLE
[Perf -26%] System.Tests.Perf_UInt64.TryParseHex

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#39110] opened 2020-07-10 21:39 UTC
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Changes | [diff](https://github.com/dotnet/installer/compare/a4a49f07fbf986d496ef57521e76b22caaf9bfb3...3c6656f83b01ece6af7e11eb75ec0145554b139d)

### Regressions in System.Tests.Perf_UInt64

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier
-- | -- | -- | -- | -- | --
TryParseHex | 21.89 ns | 27.46 ns | 1.25 | Bimodal | False

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_10_2020/release/3.1.1xx%20-%3E%20master_x64_ubuntu%2018.04/System.Tests.Perf_UInt64_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_10_2020/release/3.1.1xx%20-%3E%20master_x64_ubuntu%2018.04/System.Tests.Perf_UInt64.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Tests.Perf_UInt64*';
```
<details>

#### System.Tests.Perf_UInt64.TryParseHex(value: "FFFFFFFFFFFFFFFF")

```log
[21.493 ; 22.826) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[22.826 ; 23.926) | 
[23.926 ; 25.259) | @
[25.259 ; 26.734) | 
[26.734 ; 27.850) | @@@@@@
[27.850 ; 29.183) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[29.183 ; 30.122) | @@@@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by danmosemsft** [comment] 2020-07-12 06:53
Similar to #39119

**Comment by danmosemsft** [comment] 2020-08-06 05:49
Duplicate of #39119

**Closed by danmosemsft** 2020-08-06 05:49 UTC
Labels: arch-x64, area-System.Numerics, os-linux, tenet-performance, tenet-performance-benchmarks, untriaged
