### ISSUE TITLE
[6.0] CI failure: System.Globalization.Tests.NumberFormatInfoMiscTests.DigitSubstitutionListTest(cultureName: "prs", shape: NativeNational) expected Context

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#86338] opened 2023-05-16 16:46 UTC
### Error Blob

```json
{
  "ErrorMessage": "/_/src/libraries/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoTests.cs(110,0): at System.Globalization.Tests.NumberFormatInfoMiscTests.DigitSubstitutionListTest(String cultureName, DigitShapes shape)",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": true
}
```

### Reproduction Steps

- Affected 6.0 PR: https://github.com/dotnet/runtime/pull/86295
- Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=274862&view=results
- Queue: Libraries Test Run release coreclr windows arm64 Release
- Run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=274862&view=logs&j=a9add232-41fe-5d00-d3bc-624abd6e7259&t=ad45aa27-8e05-5f14-6180-a4bed9aa8357
- Log file: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-release-60-staging-74b27a8ab13348a28f/System.Globalization.Nls.Tests/1/console.bd393e04.log?helixlogtype=result
- Callstack:
```
  Discovering: System.Globalization.Nls.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Globalization.Nls.Tests (found 444 of 449 test cases)
  Starting:    System.Globalization.Nls.Tests (parallel test collections = on, max threads = 2)
    System.Globalization.Tests.NumberFormatInfoMiscTests.DigitSubstitutionListTest(cultureName: "prs", shape: NativeNational) [FAIL]
      Assert.Equal() Failure
      Expected: Context
      Actual:   NativeNational
      Stack Trace:
        /_/src/libraries/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoTests.cs(110,0): at System.Globalization.Tests.NumberFormatInfoMiscTests.DigitSubstitutionListTest(String cultureName, DigitShapes shape)
    System.Globalization.Tests.NumberFormatInfoPercentNegativePattern.PercentNegativePattern_Get_ReturnsExpected_ICU [SKIP]
      Condition(s) not met: "IsIcuGlobalization"
    System.Globalization.Tests.NumberFormatInfoPercentPositivePattern.PercentPositivePattern_Get_ReturnsExpected_ICU [SKIP]
      Condition(s) not met: "IsIcuGlobalization"
    System.Globalization.Tests.NumberFormatInfoCurrencyGroupSizes.CurrencyGroupSizes_Get_ReturnsExpected(format: NumberFormatInfo { CurrencyDecimalDigits = 2, CurrencyDecimalSeparator = ".", CurrencyGroupSeparator = ",", CurrencyGroupSizes = [3], CurrencyNegativePattern = 1, ... }, expected: [3, 2]) [FAIL]
      Assert.Equal() Failure
      Expected: Int32[] [3, 2]
      Actual:   Int32[] [3]
      Stack Trace:
        /_/src/libraries/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoCurrencyGroupSizes.cs(26,0): at System.Globalization.Tests.NumberFormatInfoCurrencyGroupSizes.CurrencyGroupSizes_Get_ReturnsExpected(NumberFormatInfo format, Int32[] expected)
    System.Globalization.Tests.DateTimeFormatInfoLongTimePattern.LongTimePattern_CheckReadingTimeFormatWithSingleQuotes_ICU [SKIP]
      Condition(s) not met: "IsIcuGlobalization"
    System.Globalization.Tests.CultureInfoConstructor.Ctor_String(name: "prs", expectedNames: ["prs"], expectToThrowOnBrowser: True) [FAIL]
      Assert.Contains() Failure
      Not found: fa
      In value:  String[] ["prs"]
      Stack Trace:
        /_/src/libraries/System.Globalization/tests/CultureInfo/CultureInfoCtor.cs(394,0): at System.Globalization.Tests.CultureInfoConstructor.Ctor_String(String name, String[] expectedNames, Boolean expectToThrowOnBrowser)
    System.Globalization.Tests.CultureInfoConstructor.Ctor_String(name: "prs-AF", expectedNames: ["prs-AF"], expectToThrowOnBrowser: True) [FAIL]
      Assert.Contains() Failure
      Not found: fa-AF
      In value:  String[] ["prs-AF"]
      Stack Trace:
        /_/src/libraries/System.Globalization/tests/CultureInfo/CultureInfoCtor.cs(394,0): at System.Globalization.Tests.CultureInfoConstructor.Ctor_String(String name, String[] expectedNames, Boolean expectToThrowOnBrowser)
  Finished:    System.Globalization.Nls.Tests
=== TEST EXECUTION SUMMARY ===
   System.Globalization.Nls.Tests  Total: 2561, Errors: 0, Failed: 4, Skipped: 3, Time: 5.414s
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by tarekgh** [comment] 2023-05-16 22:37
This looks a duplicate of https://github.com/dotnet/runtime/issues/79867

**Comment by tarekgh** [comment] 2023-07-18 14:53
Should be fixed now by https://github.com/dotnet/runtime/pull/89063

**Closed by tarekgh** 2023-07-18 14:53 UTC
Labels: area-System.Globalization, blocking-clean-ci, Known Build Error
