### ISSUE TITLE
ZipFile.ExtractToDirectory uses backslashes (\) for directory seperation, even on Linux

### ISSUE THREAD

**Issue by thepwrtank18** [dotnet/runtime#98247] opened 2024-02-09 22:19 UTC
### Description

When using ZipFile.ExtractToDirectory on Linux, it still uses the backslashes that Windows uses as separators. Linux reads these as just part of the filename, so every file is in the root directory specified, rather than in subdirectories that should be there as well.

### Reproduction Steps

```cs
ZipFile.ExtractToDirectory("test_zip_with_directories.zip", "test_folder");
```

### Expected behavior

The file tree will look somewhat like this:
```
test_folder
|- foo
   |- bar
      - test.txt
```

### Actual behavior

The file tree looks something like this:
```
test_folder
- foo\bar\test.txt
```

### Configuration

* Version: .NET 8
* OS: Linux (Manjaro)
* Architecture: x64

**Comment by tmds** [comment] 2024-02-11 20:18
> When using ZipFile.ExtractToDirectory on Linux, it still uses the backslashes that Windows uses as separators. Linux reads these as just part of the filename, so every file is in the root directory specified, rather than in subdirectories that should be there as well.

The issue is with the tool that creates the zip files. It should ensure only forward slashes are used as the directory separator char. So on a windows system, it needs to replace backwards slashes to forward slashes.

**Comment by dovisutu** [comment] 2024-02-13 05:07
Related with #41914 which is the creation side of the directory separator issue. That is say, dotnet itself can create a zip file that contains backslashes.

(Though technically such archives seems to be valid per zip standard?)

**Comment by tmds** [comment] 2024-02-13 08:34
See https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT:

```
       4.4.17.1 The name of the file, with optional relative path.
       The path stored MUST NOT contain a drive or
       device letter, or a leading slash.  All slashes
       MUST be forward slashes '/' as opposed to
       backwards slashes '\' for compatibility with Amiga
       and UNIX file systems etc.  If input came from standard
       input, there is no file name field.  
```

> dotnet itself can create a zip file that contains backslashes.

If the path stored in the zip file contains a backslash that backslash isn't considered a directory separator, but it is part of the name of the file or directory that is delimited by zip directory separator char (`/`).

So `ExtractToDirectory` behaves exactly as the spec requires.

> Related with https://github.com/dotnet/runtime/issues/41914

For `CreateEntryFromFile`, I agree that it may be not obvious to users they are responsible for substituting the slashes in the `entryName`. May be you could propose an overload with an argument like `normalizeDirectorySeparators`.

**Comment by tmds** [comment] 2024-02-20 13:24
I'm going to close this as the behavior of `ExtractToDirectory` matches the zip spec.

This behavior is necessary to allow extraction of filenames with backslashes on Unix, where this is not considered a directory separator.

**Closed by tmds** 2024-02-20 13:24 UTC
Labels: area-System.IO.Compression, untriaged
