### ISSUE TITLE
The frame times of my toy ray tracer increased from 24ms to 30ms

### ISSUE THREAD

**Issue by BTOdell** [dotnet/runtime#78127] opened 2022-11-09 18:43 UTC
### Description

I was encouraged to open an issue here by people on Reddit: https://www.reddit.com/r/csharp/comments/ypqn03/net_7_is_out_now/ivl99xy/

Here is the link to my repo: https://github.com/BTOdell/SharpRay

With the GA release of .NET 7, I decided to upgrade the version of my toy ray tracing project from .NET 6.0.403 to 7.0.100 in the hopes that I could get some "free" performance with the new version.
Unfortunately, the frame times of my app increased from 24ms to 30ms on my machine when I change the target framework from 6.0 to 7.0.

### Configuration

.NET versions: 6.0.403 and 7.0.100
OS: Windows x64 build 19043
CPU: Intel i9-9960X with 64GB DDR4-3600

### Regression?

The regression appears to happen when targeting a newer framework: `net6.0` to `net7.0`
If the target framework is set to `net6.0`, then the performance is the same on both versions of the runtime.

### Images

.NET 6.0.403 (target net6.0):
![image](https://user-images.githubusercontent.com/1644309/200912531-df51324a-9aaf-49f1-ae5b-78234ebf5e40.png)

.NET 7.0.100 (target net6.0):
![image](https://user-images.githubusercontent.com/1644309/200913088-59eb0379-659d-4c5f-9dd9-342d75488ae2.png)

.NET 7.0.100 (target net7.0):
![image](https://user-images.githubusercontent.com/1644309/200912231-719845ec-151f-4548-9ff8-e3a4f3e33957.png)

`dotnet restore` was used before each run to ensure the correct configuration was applied.

### Analysis

Sorry if this issue isn't related to the runtime. It might have to do with the C# language compilation to IL?

**Comment by AndyAyersMS** [comment] 2022-11-09 21:51
This is a result of the new On-Stack Replacement feature (aka OSR) in .NET 7. You can disable this feature by adding the following lines to your `csproj`
```
  <PropertyGroup>
    <TieredCompilationQuickJit>false</TieredCompilationQuickJit>
  </PropertyGroup>
```
When I do this, I see ~5% faster times for .NET 7.

FYI @dotnet/jit-contrib -- I have not yet drilled in to see where OSR is losing perf.

**Comment by AndyAyersMS** [comment] 2022-11-09 21:52
Related: https://github.com/dotnet/runtime/issues/67594.

**Comment by AndyAyersMS** [comment] 2022-11-10 02:07
Profile of 20 seconds of the app on .NET 7 (with default behavior)

I think perfview's attribution of Run as "ReadyToRun" is wrong, this is OSR code.

<img width="776" alt="image" src="https://user-images.githubusercontent.com/10121823/200981685-30149ecb-3dcb-4e7b-900a-93b72429429a.png">

Corresponding profile from .NET 6

<img width="789" alt="image" src="https://user-images.githubusercontent.com/10121823/200981868-8941bfd6-55ac-4eb2-9ff4-e70413beaa4d.png">

Looking at `Run` the inner loop codegen is actually fairly similar, except that the OSR method seems to have realized that `Vec4.One` is a constant -- but then it fails to hoist/CSE this constant and reloads it repeatedly. That might be the regression. It's possible hoisting is thrown off by lack of a preheader or something.

**Comment by AndyAyersMS** [comment] 2023-03-31 02:47
This seems to be fixed with latest .NET 8 builds (will be available in Preview 4)

```
;; 7.0
Framebuffer size: <800, 800>
Rendered in: 138.3371ms
Rendered in: 115.2097ms
Rendered in: 60.8962ms
Rendered in: 27.6196ms
Rendered in: 27.1536ms
Rendered in: 27.0591ms
Rendered in: 27.4292ms
Rendered in: 27.1339ms
Rendered in: 27.1519ms

;; 8.0 current main
Framebuffer size: <800, 800>
Rendered in: 133.7311ms
Rendered in: 108.3345ms
Rendered in: 65.7654ms
Rendered in: 24.2893ms
Rendered in: 26.8595ms
Rendered in: 24.5418ms
Rendered in: 23.7889ms
Rendered in: 24.2502ms
Rendered in: 23.6659ms
Rendered in: 23.9037ms
Rendered in: 23.8969ms
```
I' m going to close this. @BTOdell once Preview 4 is out give it a try and see if you see the same. If not, please re-open.

**Closed by AndyAyersMS** 2023-03-31 02:47 UTC
Labels: tenet-performance, area-CodeGen-coreclr, regression-from-last-release
