### ISSUE TITLE
Add Min-Max Heap collection in .NET

### ISSUE THREAD

**Issue by botdev82** [dotnet/runtime#37114] opened 2020-05-28 03:37 UTC
These days companies are hiring people by testing their coding / algorithmic / problem solving / data structures skills on platforms like leetcode, hackerrank, codility, codesignal etc. Some problems require Heap data structure and .net developers are at disadvantage there. If one uses existing collections instead of Heap where Heap is needed then there are bad performance results and other devs like Python’s win competitions / jobs.

Also during interview candidates are often given a coding problem that requires Heap. Interviewer says use any language you want. .Net devs lose again.

In general Python devs have a big advantage in such cases as the language has more features / data structures for quick problem solving. I would recommend to look wider on this issue and also implement other missing functionalities.

**Comment by eiriktsarpalis** [comment] 2020-05-28 14:10
This is probably a duplicate of #14032.

**Closed by eiriktsarpalis** 2020-05-28 14:10 UTC
Labels: api-suggestion, area-System.Collections, untriaged
