### ISSUE TITLE
System.Drawing.Common not working under PopOS 20.10

### ISSUE THREAD

**Issue by Yuri6037** [dotnet/runtime#45233] opened 2020-11-25 20:55 UTC
### Description
The library complains of missing libgdiplus but there's already a package installed with version 6.0.4+dfsg-2.

### Configuration

- Dotnet 3.1.403
- Pop! OS 20.10 (x86_64)

### Regression?

Works fine on Windows.

### Other information

```
System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libgdiplus' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibgdiplus: cannot open shared object file: No such file or directory
   at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.SafeNativeMethods.Gdip.GdipLoadImageFromDelegate_linux(StreamGetHeaderDelegate getHeader, StreamGetBytesDelegate getBytes, StreamPutBytesDelegate putBytes, StreamSeekDelegate doSeek, StreamCloseDelegate close, StreamSizeDelegate size, IntPtr& image)
   at System.Drawing.Image.InitializeFromStream(Stream stream)
   at System.Drawing.Bitmap..ctor(Stream stream, Boolean useIcm)
   at System.Drawing.Bitmap..ctor(Stream stream)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
```

**Comment by safern** [comment] 2020-11-25 21:06
@Yuri6037 could you look at where is `LD` looking for the library? You can do this with `LD Debug` http://www.bnikolic.co.uk/blog/linux-ld-debug.html

Or you could also try setting: `LD_LIBRARY_PATH` environment variable to include the location where `libgdiplus` is installed. i.e:

```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/libgdiplus/dir
```

**Comment by Yuri6037** [comment] 2020-11-25 21:47
Wait is it normal that it references `liblibgdiplus` instead of `libgdiplus`? I remember having a similar problem when interfacing with a native DLL. I ended writing my own dependency loader to give it the correct name.

**Comment by safern** [comment] 2020-11-25 22:04
> Wait is it normal that it references liblibgdiplus instead of libgdiplus? I remember having a similar problem when interfacing with a native DLL. I ended writing my own dependency loader to give it the correct name.
>
> EDIT: It does work when setting LD_LIBRARY_PATH but it's not acceptable. I cannot tell to the customer to run a script before running the software especialy when the library is under a standard system path: /usr/lib. In addition it cannot be used with my IDE

No it is not normal that it references `liblibgdiplus`... Where did you see that?

Here is our loading logic for `DllImport` hook. 

https://github.com/dotnet/runtime/blob/f48c8d581b584495079fa5f2b2789ef48546edd9/src/libraries/System.Drawing.Common/src/System/Drawing/GdiplusNative.Unix.cs#L29-L56

By the way which package version are you using for `System.Drawing.Common`?

**Comment by Yuri6037** [comment] 2020-11-25 22:18
> > Wait is it normal that it references liblibgdiplus instead of libgdiplus? I remember having a similar problem when interfacing with a native DLL. I ended writing my own dependency loader to give it the correct name.
> >
> > EDIT: It does work when setting LD_LIBRARY_PATH but it's not acceptable. I cannot tell to the customer to run a script before running the software especialy when the library is under a standard system path: /usr/lib. In addition it cannot be used with my IDE
> 
> No it is not normal that it references `liblibgdiplus`... Where did you see that?
> 
> Here is our loading logic for `DllImport` hook. 
> 
> https://github.com/dotnet/runtime/blob/f48c8d581b584495079fa5f2b2789ef48546edd9/src/libraries/System.Drawing.Common/src/System/Drawing/GdiplusNative.Unix.cs#L29-L56
> 
> By the way which package version are you using for `System.Drawing.Common`?
> 
> 
> 

I saw this name on second line of the error near the end.
I'm using the latest version currently findable on nuget for .Net Core 3.1.

**Comment by safern** [comment] 2020-11-25 22:25
> I'm using the latest version currently findable on nuget for .Net Core 3.1.

I guess that's 5.0.0? Honestly, this is the first time I've seen `PopOS`. So I'll need to repro and see what's going on. Are you able to get a `LD DEBUG` trace? 

What's is the name of the library on your local computer? Cause we probe for `libgdiplus.so` and `libgdiplus.so.0`. 

> I saw this name on second line of the error near the end.

Oh, that is because of the `NativeLibrary` probing, it will probe the name you pass down and other variations like adding `lib` to it if it didn't find it by the name you used when calling `NativeLirbary.TryLoad`.

**Comment by Yuri6037** [comment] 2020-11-25 22:31
> > I'm using the latest version currently findable on nuget for .Net Core 3.1.
> 
> I guess that's 5.0.0? Honestly, this is the first time I've seen `PopOS`. So I'll need to repro and see what's going on. Are you able to get a `LD DEBUG` trace? 
> 
> What's is the name of the library on your local computer? Cause we probe for `libgdiplus.so` and `libgdiplus.so.0`. 
> 
> > I saw this name on second line of the error near the end.
> 
> Oh, that is because of the `NativeLibrary` probing, it will probe the name you pass down and other variations like adding `lib` to it if it didn't find it by the name you used when calling `NativeLirbary.TryLoad`. 

Yes it is v5.0.0. The name of the library is the first you mentioned: libgdiplus.so in /usr/lib.
The system is based on Ubuntu 20.10 and the version of .Net Core I installed is for Ubuntu as well. I use Pop OS mainly for improved support of my GTX 650 which I use a bit for machine learning.
Currently I'm not in front of the computer so I can't give you any debug of LD.

**Comment by safern** [comment] 2020-11-25 23:59
Thanks for the info.

> Currently I'm not in front of the computer so I can't give you any debug of LD.

I'll try to repro, for this I need to set a VM with `PopOS`. If I don't post a response and before that you're able to give me the debug, that would be appreciated.

**Comment by RusKnyaz** [comment] 2020-12-24 08:06
BTW, the same issue is observed on Ubuntu 20 when dotnet sdk installed using **snap**:
`sudo snap install dotnet-sdk --channel=5.0/beta --classic`
Is it by design? Should I install libgdiplus in some specific way? I tried:
`sudo apt-get install libgdiplus`
it does not help.

**Comment by safern** [comment] 2021-01-04 18:43
Thanks for the info @RusKnyaz -- I'll try that one as well.

**Comment by safern** [comment] 2021-07-22 22:25
Given the announcement we just made on: https://github.com/dotnet/designs/blob/main/accepted/2021/system-drawing-win-only/system-drawing-win-only.md -- I will close this issue. Please let me know if you have any other questions.

**Closed by safern** 2021-07-22 22:25 UTC
Labels: area-System.Drawing
