### ISSUE TITLE
[API Proposal]: attribute for polymorphic json serialisation (not deserialisation)

### ISSUE THREAD

**Issue by AartBluestoke** [dotnet/runtime#71605] opened 2022-07-04 05:53 UTC
### Background and motivation

https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-polymorphism
says "You can get polymorphic serialization for lower-level objects if you define them as type object."
and provides an example of serializing a derived WeatherForecast via:

"instead of
```
public class WeatherForecastWithPrevious
{
    public DateTimeOffset Date { get; set; }
    public int TemperatureCelsius { get; set; }
    public string? Summary { get; set; }
    public WeatherForecast? PreviousForecast { get; set; }
}
```
you should use 'object' as the type of the child:
```
public class WeatherForecastWithPreviousAsObject
{
    public DateTimeOffset Date { get; set; }
    public int TemperatureCelsius { get; set; }
    public string? Summary { get; set; }
    public object? PreviousForecast { get; set; } //Polymorphic serialisation of some type of forecast
}
```
"

The above code doesn't produce an object capable of being deserialised. If we are making people write custom deseralisers for this event, can we at least make the serialisation easy?

### API Proposal

a new configuration option for jsonAttribute or jsonserializeroptions to allow for serialisation of objects as the type they actually are, not the type they are referenced as.

### API Usage

```csharp
public class WeatherForecastWithPrevious
{
    public DateTimeOffset Date { get; set; }
    public int TemperatureCelsius { get; set; }
    public string? Summary { get; set; }
    [JsonAttribute(PolymorphicSerialisation=True)]
    public WeatherForecast? PreviousForecast { get; set; }
}
```

### Alternative Designs

recommend custom serialisers in this situation, not just custom deserialisers.

### Risks

- a lack of action here keeps the recommendation to have objects as property types if they might be both inhereted and serialised. This is not inline with good practice.

- poor action here will lead people to implement polymorphic serialisation without polymorphic de-serialisation, with silent data loss. (polymorphic deserialisation into object isn't a supported

**Comment by Symbai** [comment] 2022-07-04 06:15
There has been a long existing issue about that #63747 and the implementation has been completed 6 days ago #71346, the article you linked to is older.

**Comment by eiriktsarpalis** [comment] 2022-07-04 11:44
Closing as duplicate of #63747. Note that the shipped API requires explicitly opting in the supported derived types.

**Closed by eiriktsarpalis** 2022-07-04 11:44 UTC
Labels: api-suggestion, area-System.Text.Json, untriaged
