### ISSUE TITLE
Deserialization does not fail when a required property is null

### ISSUE THREAD

**Issue by joseftw** [dotnet/runtime#88727] opened 2023-07-12 10:38 UTC
### Description

The JsonSerializer.Deserialize method does not behave the same way when deserializing a required property.

- If the json does not contain the required property at all -> an `JsonException` is thrown (expected).
- If the json contains the required property, but it's value is `null`, _no exception is thrown_.

I thought that the serializer would respect the `required` keyword combined with the nullability settings on the property, but that seems to not be the case?

### Reproduction Steps

Given the following class:

```csharp
namespace JOS.TipsAndTrix._03Deserialization.Required;

public class CarDto
{
    public required string Brand { get; init; }
    public required string Model { get; init; }
    public required uint Horsepower { get; init; }
    public required List<CustomPartDto> CustomParts { get; init; }
}

public class CustomPartDto
{
    public required string PartNumber { get; init; }
    public required decimal Price { get; init; }
    public required DateOnly Manufactured { get; init; }
}
```

And the following JsonSerializerOptions:
```csharp
public class CarsJsonSerializerOptions
{
    static CarsJsonSerializerOptions()
    {
        Options = new JsonSerializerOptions
        {
            PropertyNameCaseInsensitive = true,
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase
        };
    }
    public static JsonSerializerOptions Options { get; }
}
```

The following test passes (as expected since the `CustomParts` property is missing from the json)
```csharp
[Fact]
public void ShouldThrowIfRequiredPropertyIsNotSet()
{
    const string json = """
    [
          {
            "brand": "Ferrari",
            "model": "Enzo",
            "horsePower": 651
          },
          {
            "brand": "Ferrari",
            "model": "F50",
            "horsePower": 512
          },
          {
            "brand": "Ferrari",
            "model": "488 Spider",
            "horsePower": 661
          }
    ]
    """;
    var exception = Should.Throw<JsonException>(
        () => JsonSerializer.Deserialize<List<CarDto>>(json, CarsJsonSerializerOptions.Options));

    exception.Message.ShouldBe(
        "JSON deserialization for type 'JOS.TipsAndTrix._03Deserialization.Required.CarDto' was missing required " +
        "properties, including the following: customParts");
}
```

However, if we change the JSON to include the `customParts` property, but setting it's value to `null`, no exception is thrown:

```csharp
[Fact]
public void ShouldThrowIfRequiredPropertyIsNullInTheJson()
{
    const string json = """
    [
      {
        "brand": "Ferrari",
        "model": "Enzo",
        "horsePower": 651,
        "customParts": null
      },
      {
        "brand": "Ferrari",
        "model": "F50",
        "horsePower": 512,
        "customParts": null
      },
      {
        "brand": "Ferrari",
        "model": "488 Spider",
        "horsePower": 661,
        "customParts": null
      }
]
""";

    var exception = Should.Throw<JsonException>(
        () => JsonSerializer.Deserialize<List<CarDto>>(json, CarsJsonSerializerOptions.Options));

    exception.Message.ShouldBe(
        "JSON deserialization for type 'JOS.TipsAndTrix._03Deserialization.Required.CarDto' was missing required " +
        "properties, including the following: customParts");
}
```

### Expected behavior

A `JsonException` is thrown when the required property is present in the json string but set to `null`.
It should behave the same way as when the required property is missing in the json string.

### Actual behavior

No exception is thrown, `CustomParts` is set to null.

### Configuration

```
dotnet --version
8.0.100-preview.6.23330.14
```

**Comment by huoyaoyuan** [comment] 2023-07-12 10:54
Duplicate of #87472. The feature request is tracked by #1256.

**Closed by huoyaoyuan** 2023-07-12 10:54 UTC
Labels: area-System.Text.Json, untriaged
