### ISSUE TITLE
Perfomance of For Loops is worse in Net7 to Net6

### ISSUE THREAD

**Issue by jogibear9988** [dotnet/runtime#76638] opened 2022-10-04 20:43 UTC
### Description

I saw the issue on Nick Chapsas Video, but it seems nobody created an issue here until now.

See his benchmark here: https://gist.github.com/Elfocrash/eee450b37f2263040dc9ca193f9ce9fd

And his video: 
https://www.youtube.com/watch?v=LfgBm5M8eUM&t=326s

### Reproduction Steps

see his video

### Expected behavior

perfomance should be equal or better

### Actual behavior

perfomance is 30% slower

**Comment by JulieLeeMSFT** [comment] 2022-10-05 00:32
@EgorBo if the for loop perf is 30% slower in .net7, shouldn’t we port it to .net7?
Cc @dotnet/jit-contrib.

**Comment by AndyAyersMS** [comment] 2022-10-05 16:08
Can somebody add in the root cause analysis that was done here?

Also curious that we somehow never spotted this in any of our microbenchmarks -- maybe when we get the 6 vs 7 comparison we'll see more of this sort of thing?

**Comment by SingleAccretion** [comment] 2022-10-05 16:36
> Can somebody add in the root cause analysis that was done here?

The short version is that forward substitution of exception-inducing addresses exposed weaknesses in VN's exception set addition logic.

The longer explanation will require the code snippet in question:
```cs
private List<int> a; // A class member

[MethodImpl(MethodImplOptions.NoInlining)]
private void Problem()
{
    for (int i = 0; i < a.Count; i++)
    {
        _ = a[i];
    }
}
```
First, we inline `a.Count` and leave behind the argument setup statement:
```scala
Arguments setup:
STMT00010 ( 0x015[E-] ... ??? )
               [000039] -A-XG------                         *  ASG       ref   
               [000038] D------N---                         +--*  LCL_VAR   ref    V04 tmp2         
               [000005] ---XG------                         \--*  FIELD     ref    a
               [000004] -----------                            \--*  LCL_VAR   ref    V00 this         
```
Second, in .NET 6 the temporary stays. In .NET 7 it is eliminated by forward substitution:
```scala
    [000039]:  [000036] is only use of [000038] (V04)  -- fwd subbing [000005]; new next stmt is
STMT00002 ( 0x015[E-] ... ??? )
               [000009] ---XG------                         *  JTRUE     void  
               [000008] ---XG------                         \--*  LT        int   
               [000003] -----------                            +--*  LCL_VAR   int    V01 loc0         
               [000037] ---XG------                            \--*  FIELD     int    _size
               [000005] ---XG------                               \--*  FIELD     ref    a
               [000004] -----------                                  \--*  LCL_VAR   ref    V00 this         

removing useless STMT00010 ( 0x015[E-] ... ??? )
               [000039] -A-XG------                         *  ASG       ref   
               [000038] D------N---                         +--*  LCL_VAR   ref    V04 tmp2         
               [000005] ---XG------                         \--*  FIELD     ref    a
               [000004] -----------                            \--*  LCL_VAR   ref    V00 this         
```
In both cases, we duplicate the loop condition that involves what used to be `a.Count`.

Then, in 6, we CSE all appearances of it, effectively hoisting the expression. In 7, we don't because the exception sets differ (due to the aforementioned weakness in the analysis).
```scala
// .NET 6
CSE def:
N005 (  4,  4) [000075] ---XG-------                 \--*  IND       int    <l:$203, c:$202>
N004 (  2,  2) [000076] -------N----                    \--*  ADD       byref  <l:$142, c:$141>
N002 (  1,  1) [000077] ------------                       +--*  LCL_VAR   ref    V04 tmp2         u:2 (last use) <l:$1c1, c:$82>
N003 (  1,  1) [000078] ------------                       \--*  CNS_INT   long   16 field offset Fseq[_size] $101

CSE use:
N005 (  4,  4) [000024] ---XG-------                 \--*  IND       int    <l:$203, c:$209>
N004 (  2,  2) [000043] -------N----                    \--*  ADD       byref  <l:$142, c:$143>
N002 (  1,  1) [000023] ------------                       +--*  LCL_VAR   ref    V03 tmp1         u:2 <l:$1c1, c:$87>
N003 (  1,  1) [000042] ------------                       \--*  CNS_INT   long   16 field offset Fseq[_size] $101

// .NET 7
CSE def:
N008 (  7,  7) [000072] ---XG------                            \--*  IND       int    <l:$243, c:$244>
N007 (  5,  5) [000073] ---XG--N---                               \--*  ADD       byref  <l:$144, c:$143>
N005 (  4,  4) [000074] ---XG------                                  +--*  IND       ref    <l:$202, c:$203>
N004 (  2,  2) [000075] -------N---                                  |  \--*  ADD       byref  $140
N002 (  1,  1) [000076] -----------                                  |     +--*  LCL_VAR   ref    V00 this         u:1 $80
N003 (  1,  1) [000077] -----------                                  |     \--*  CNS_INT   long   8 Fseq[a] $100
N006 (  1,  1) [000078] -----------                                  \--*  CNS_INT   long   16 Fseq[_size] $101

CSE use:
N005 (  4,  4) [000024] ---XG------                            \--*  IND       int    <l:$24a, c:$24b>
N004 (  2,  2) [000044] -------N---                               \--*  ADD       byref  <l:$141, c:$145>
N002 (  1,  1) [000023] -----------                                  +--*  LCL_VAR   ref    V03 tmp1         u:2 <l:$200, c:$85>
N003 (  1,  1) [000043] -----------                                  \--*  CNS_INT   long   16 Fseq[_size] $101
```

**Comment by DrewScoggins** [comment] 2022-10-05 22:02
> Can somebody add in the root cause analysis that was done here?
> 
> Also curious that we somehow never spotted this in any of our microbenchmarks -- maybe when we get the 6 vs 7 comparison we'll see more of this sort of thing?

I will put together a report that at least covers what we have in the lab today. 

As for the second thing, do we have any tests specifically like this? Ones that access a list using an incremented counter in a for loop? I don't know for sure, but a cursory glance did not reveal anything.

**Comment by AndyAyersMS** [comment] 2022-10-06 20:51
> > Can somebody add in the root cause analysis that was done here?
> > Also curious that we somehow never spotted this in any of our microbenchmarks -- maybe when we get the 6 vs 7 comparison we'll see more of this sort of thing?
> 
> I will put together a report that at least covers what we have in the lab today.
> 
> As for the second thing, do we have any tests specifically like this? Ones that access a list using an incremented counter in a for loop? I don't know for sure, but a cursory glance did not reveal anything.

I don't know either. Just trying to assess whether this is a "narrow" issue that will only impact very simple use cases or something more widespread.

**Comment by AndyAyersMS** [comment] 2022-10-12 16:29
@DrewScoggins do we have any data to look at yet?

We can also wait for the RC2 vs 6.0 report.

**Comment by DrewScoggins** [comment] 2022-10-12 17:16
Here are the reports:
* [Ubuntu x64](<https://pvscmdupload.blob.core.windows.net/drewtest/reports/report_Weekly_ca%3Dx64_cb%3Drefs-heads-release-7.0_co%3DUbuntu1804_cr%3Ddotnetruntime_cc%3DCompliationMode%3Dtiered-RunKind%3Dmicro_Baseline_bb%3Drefs-heads-release-6.0_2022-10-12.html>)
* [Windows x64](<https://pvscmdupload.blob.core.windows.net/drewtest/reports/report_Weekly_ca%3Dx64_cb%3Drefs-heads-release-7.0_co%3DWindows1018362_cr%3Ddotnetruntime_cc%3DCompliationMode%3Dtiered-RunKind%3Dmicro_Baseline_bb%3Drefs-heads-release-6.0_2022-10-12.html>)
* [Windows x86](<https://pvscmdupload.blob.core.windows.net/drewtest/reports/report_Weekly_ca%3Dx86_cb%3Drefs-heads-release-7.0_co%3DWindows1018362_cr%3Ddotnetruntime_cc%3DCompliationMode%3Dtiered-RunKind%3Dmicro_Baseline_bb%3Drefs-heads-release-6.0_2022-10-12.html>)

From looking at the reports the interesting tests seem to be of the variety *IterateFor*

**Comment by AndyAyersMS** [comment] 2022-10-22 00:47
We merged the fix to .NET 8 via https://github.com/dotnet/runtime/pull/76639 and I didn't see any benchmark data get attached, so either we're lagging behind on our triaging of improvements, or this really is a very "narrow" perf issue. I will go check if we somehow overlooked this change.

We should add this exact scenario to the perf testing.

**Comment by jogibear9988** [comment] 2022-11-13 19:41
As this is a regression, should it be backported to a 7.x patch release?
And should I close this issue?

**Comment by AndyAyersMS** [comment] 2023-03-31 16:42
> As this is a regression, should it be backported to a 7.x patch release?
> And should I close this issue?

I'll go ahead and close this.

I don't believe we would backport this perf fix unless we knew of applications (not benchmarks) that were significantly impacted with no feasible workaround.

If you or anyone knows of any applications this, please re-open and add the details.

**Closed by AndyAyersMS** 2023-03-31 16:42 UTC
Labels: area-CodeGen-coreclr, needs-further-triage
