### ISSUE TITLE
Plans for opt-in OpenTelemetry attribute implementation and configuration?

### ISSUE THREAD

**Issue by matt-hensley** [dotnet/runtime#103302] opened 2024-06-11 19:08 UTC
*Opening this against the runtime repo as it covers ASP.NET Core and HttpClient but may have further implications, please let me know if this is the wrong location.*

For opt-in OpenTelemetry attributes, what is the strategy for implementation and configuration?

A good example is the `http.server.request.duration` metric which has two opt-in attributes: `server.address` and `server.port`.

As noted in the .NET-specific OTel semantic conventions, these [opt-in attributes are not reported](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/dotnet/dotnet-http-metrics.md#metric-httpserverrequestduration) and do not have an opt-in mechanism.

[It is possible use tag enrichment](https://learn.microsoft.com/en-us/aspnet/core/log-mon/metrics/metrics?view=aspnetcore-8.0#enrich-the-aspnet-core-request-metric) via `IHttpMetricsTagsFeature` to add both attributes. Any user interested in opt-in attributes would need to write enrichment code to populate the values.

I am interested if there are plans for the addition of opt-in OpenTelemety attributes, and if consideration has been given to a common opt-in pattern.

**Comment by cijothomas** [comment] 2024-06-11 22:58
https://github.com/open-telemetry/opentelemetry-dotnet/issues/3373#issuecomment-1204164425 This maybe a good option to consider.

**Comment by cijothomas** [comment] 2024-06-11 23:05
If https://github.com/dotnet/aspnetcore/issues/52439 is not landing in .NET9 timeframe, then probably a good idea to implement something in OTel Instrumentation libraries itself: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/1786

**Comment by ericstj** [comment] 2024-06-18 00:21
cc @tarekgh

**Comment by tarekgh** [comment] 2024-06-18 02:00
CC @antonfirsov @JamesNK @noahfalk @lmolkova

**Comment by tarekgh** [comment] 2024-06-18 02:03
CC @samsp-msft

**Comment by JamesNK** [comment] 2024-06-18 05:20
There are other things to configure, such as the list of HTTP methods.

This configuration is difficult because I don't think it should be static (yuck), but there also isn't anywhere good to place it. The http handler maybe?

It's not urgent and can be considered based on demand.

**Comment by CarnaViire** [comment] 2024-07-01 11:19
Triage: Not urgent, already marked as Future.

If you need the feature, please upvote the top post to help us prioritize. Thanks!

**Comment by antonfirsov** [comment] 2024-07-01 13:33
Weird, #94829 states that `server.port` should be Required. @lmolkova has this changed since https://github.com/open-telemetry/semantic-conventions/pull/459?

I agree with https://github.com/dotnet/runtime/issues/103302#issuecomment-2175034909. This needs an API, for that we are already too late in the release cycle.

**Comment by antonfirsov** [comment] 2024-07-01 14:00
However, if the presence of these attributes is a serious concern

**Comment by antonfirsov** [comment] 2024-07-01 14:02
> As noted in the .NET-specific OTel semantic conventions, these [opt-in attributes are not reported](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/dotnet/dotnet-http-metrics.md#metric-httpserverrequestduration)

@matt-hensley HttpClient does report them. However according to the [spec](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/http-metrics.md#metric-httpclientrequestduration).

> [8]: See [Setting server.address and server.port attributes](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/http-spans.md#setting-serveraddress-and-serverport-attributes).

> Warning Since this attribute is based on HTTP headers, opting in to it may allow an attacker to trigger cardinality limits, degrading the usefulness of the metric.


If we think this is a serious concern, we shall remove them. Putting back the issue to 9.0 to decide this.

**Comment by lmolkova** [comment] 2024-07-01 15:57
> Weird, https://github.com/dotnet/runtime/issues/94829 states that server.port should be Required. @lmolkova has this changed since https://github.com/open-telemetry/semantic-conventions/pull/459?

@antonfirsov the port used to be opt-in when .NET semconv were stabilized and then was changed to required right before OTel HTTP was stabilized.

**Comment by antonfirsov** [comment] 2024-07-01 16:04
Nevermind my https://github.com/dotnet/runtime/issues/103302#issuecomment-2200241044, I was looking at the server metric.

**Comment by antonfirsov** [comment] 2024-07-11 16:25
Duplicate of #104738 and #94829.

**Closed by antonfirsov** 2024-07-11 16:25 UTC
Labels: area-System.Net.Http
