### ISSUE TITLE
CompositionContainer is not thread safe - even when constructed as thread safe

### ISSUE THREAD

**Issue by nick-beer** [dotnet/runtime#59505] opened 2021-09-22 22:40 UTC
Our application makes extensive use of the System.ComponentModel.Composition libraries and uses the `CompositionContainer` from many different threads.  When the container is created, it is marked (via the constructor) as thread safe.

__We've successfully used the container like this in .NET Framework 4.6.2 for many many years__, but with a recent update to .NET 5, we're seeing some crashes.

Specifically, the path along `CompositionContainer.Compose()` does not look thread safe.  We eventually get to `RecompositionManager.GetAffectedParts`, and while [enumerating the alive items list](https://source.dot.net/#System.ComponentModel.Composition/Microsoft/Internal/Collections/WeakReferenceCollection.cs,ba0bb95f9621c62b,references), an exception is thrown because a different thread has modified that list.  The other thread is in the middle of satisfying a call to `GetExportedValue`.  Examination of the crashing stack reveals that there is no locking around the modified members.

Here's a snapshot of the stack that crashes:
![image](https://user-images.githubusercontent.com/1509215/134421455-2560117a-99f7-4d6f-84f6-0af415fe963e.png)

The crash has been seen against .NET 5 (runtime version 5.0.9) and .NET 6 (runtime version 6.0.0-rc.1.21451.13).

[Here](https://gist.github.com/nick-beer/308780c9502b00cd9e82a6b0bc286249) is a (relatively) simple single file c# program that will reliably reproduce the crash we're seeing.

**Comment by nick-beer** [comment] 2021-09-24 15:06
It's worth noting this is *not* a regression from .NET Framework.  I initially thought that it was, but I built the example app linked above against .NET Framework 4.7.2 (obviously modifying the code to have a `main` etc), and got the same crash.  It looked like the code along the `Compose` path hasn't really changed much - so it makes sense that the issue is in both .NET Framework and .NET.  I'm not sure why the crash is just now showing up in our .NET 5 build, but this is a significant/worrisome issue for our applications we're migrating to .NET 5.

**Comment by joperezr** [comment] 2021-09-28 17:20
Thanks for the very complete report of the issue @nick-beer! I'm also wondering why if this wasn't a regression you started seeing the issue after migrating to .NET from .NET Framework, and were not seeing this before.

**Comment by pedrobsaila** [comment] 2021-11-01 11:07
Hi.
I made a PR #61054 for this issue

**Comment by steveharter** [comment] 2021-11-10 22:46
@dsplaisted PTAL. It seems you are familiar with this per your comment on [StackOverflow](https://stackoverflow.com/questions/3246581/thread-safety-and-the-mef-compositioncontainer):
>One thing to be aware of is that even "thread-safe" composition containers aren't thread-safe for operations which can cause recomposition, such as changes to the catalogs, or calling the Compose methods on the container.

Since the test provided in this issue does a recomposition, I'm not sure this issue should be fixed. If we fix the bug for the test provided in the issue, and recompositions were not designed for thread safety even with `isThreadSafe=true`, then there may be more edge case issues to address.

However, the [doc](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.composition.hosting.compositioncontainer?view=dotnet-plat-ext-5.0) doesn't place any threading constraints when `isThreadSafe=true` constructor parameter or equivalent `CompositionOptions.IsThreadSafe` is used. In addition, looking at this comment:
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ImportEngine.cs#L14-L18
(I assume each of the 3 constraints is an OR, not an AND) implies that recompositions are not thread-safe by default, so they should be accessed by a single thread or use `isThreadSafe=true`.

**Comment by AArnott** [comment] 2021-11-11 19:03
I believe that list of conditions was meant to be AND'd together. Saying "well as long as you only call us on one thread, we're thread-safe" (from the first bullet in the list) makes no sense. That's saying that you're *not* thread safe if you require the caller to always use a single thread.

I think what this is saying is it can be thread-safe if the flag is set, but excludes (re)composition. Recomposition is a *very* complex thing that IIRC was never thread-safe and could not be made to be.

**Comment by steveharter** [comment] 2021-11-11 19:25
> Recomposition is a very complex thing that IIRC was never thread-safe and maybe could not be made to be without risking deadlocks.

Thanks that is what I was looking for.

@buyaa-n unless we hear diverging feedback, I think we can close this issue and associated PR. This particular threading issue has been around for at least 11 years based upon the StackOverflow link above.

**Comment by buyaa-n** [comment] 2021-11-11 21:50
> @buyaa-n unless we hear diverging feedback, I think we can close this issue and associated PR.

As per [above](https://github.com/dotnet/runtime/issues/59505#issuecomment-966550582) comment and the [discussions in the PR](https://github.com/dotnet/runtime/pull/61054#issuecomment-966566790) `System.ComponentModel.Composition` was never thread-safe for recomposition, and that the thread-safe flag was only to make the container thread-safe for obtaining exports across many threads. So closing the issue as we will not fix this

Please [read comments on the PR](https://github.com/dotnet/runtime/pull/61054#issuecomment-965957314) for more info

**Closed by buyaa-n** 2021-11-11 21:50 UTC
Labels: bug, area-System.Composition, up-for-grabs
