### ISSUE TITLE
In .NET 6, when ConfigureLogging SetMinimumLevel to LogLevel.Warning/Error/Critical, logger.IsEnabled(LogLevel.Warning/Error/Critical) can't get result rightly.

### ISSUE THREAD

**Issue by AwesomeYuer** [dotnet/runtime#79798] opened 2022-12-18 16:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In .NET 6, when ConfigureLogging SetMinimumLevel to LogLevel.Warning/Error/Critical, logger.IsEnabled(LogLevel.Warning/Error/Critical) can't get result rightly. These 3 results always return true.
logger.IsEnabled(checkingLogLevel) should return false when checkingLogLevel < minimumLogLevel

I think when SetMinimumLevel to  LogLevel.Error, logger.IsEnabled(LogLevel.Warning) should be false, but return true.

the Sample code as below:

```C#
// See https://aka.ms/new-console-template for more information

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

var minimumLogLevel = LogLevel.Error;
IHost host = Host
                .CreateDefaultBuilder(args)
                .ConfigureLogging
                    (
                        (logging) =>
                        {
                            logging
                                .SetMinimumLevel(minimumLogLevel);
                        }
                    )
                .Build();


var logger = host.Services.GetRequiredService<ILogger<Program>>();

var enums = Enum.GetValues(typeof(LogLevel));
foreach (LogLevel e in enums)
{ 
    Console.WriteLine($"{(e >= minimumLogLevel ? e + " >= " + minimumLogLevel : e + " < " + minimumLogLevel)}, IsEnabled: {logger.IsEnabled(e)}");
}

Console.WriteLine("===============================");

logger.LogTrace("LogTrace");
logger.LogDebug("LogDebug");
logger.LogInformation("LogInformation");

logger.LogWarning("LogWarning");
logger.LogError($"LogError");
logger.LogCritical($"LogCritical");

Console.WriteLine("Hello, World!");
await host.RunAsync();
```

### Expected Behavior

logger.IsEnabled(checkingLogLevel) should return false when checkingLogLevel < minimumLogLevel

**Comment by jodydonetti** [comment] 2022-12-18 20:19
Hi @Microshaoft , I think the issue is that you did not have configured which logger to use, but only the general min log level.
Without specifying an actual logger, it seems that by default .NET is registering 4 different loggers, all "wrapped" inside a main one.

See here, inspecting the `logger` variable:

![image](https://user-images.githubusercontent.com/1010086/208317439-c194884e-148e-4e9d-b323-16c04de166b0.png)

The actual logger used is of type `Logger<Program>` which, in turn, contains a `Loggers` (plural) property which contains 4 the 4 actual loggers. I suppose one of them is configured differently (in this case with a min level of `Warning`) so, by asking the general one _"is warning enabled?"_ it will check to see if any of the sub-loggers has a min level >= `Warning`, and returns `true`.

My 2 cents.

**Comment by tarekgh** [comment] 2022-12-18 22:39
@Microshaoft could you please configure to use specific logger and then check the behavior as @jodydonetti suggested?

**Comment by Microshaoft** [comment] 2022-12-19 03:50
@tarekgh @jodydonetti how to  configure/coding minimumLogLevel to use specific logger? thanks.
BTW: the behavior of blow codes are right，
```c#
logger.LogTrace("LogTrace");
logger.LogDebug("LogDebug");
logger.LogInformation("LogInformation");

logger.LogWarning("LogWarning");
logger.LogError($"LogError");
logger.LogCritical($"LogCritical");
```

**Comment by jodydonetti** [comment] 2022-12-19 08:39
Hi all,
by looking at the `Logger` source it seems to be confirmed that, as soon as one of the sub-loggers has it enabled for the requested `LogLevel`, the whole thing returns `true`.

Here's [the line](https://github.com/dotnet/runtime/blob/a92c5bc9d5624b3f30a09d73bb5833deb54013e9/src/libraries/Microsoft.Extensions.Logging/src/Logger.cs#L85) I'm talking about: basically it loops over all the sub-loggers and, as soon as one returns `true` for `IsEnabled(LogLevel)`, it breaks the loop. Then, if the loop index is < than the number of sub-loggers (meaning it stopped before looping over all of them), it returns `true`.

Again, my 2 cents, somebody else with more knowledge than me should confirm this.

**Comment by Microshaoft** [comment] 2022-12-22 05:11
I think the behavior of logger.IsEnabled(checkingLogLevel) is not rightly? really?
but why the  blow codes are right?, if the specific logger's checkingLogLevel < minimumLogLevel , then the logger will NOT logging anything:
```c#
logger.LogTrace("LogTrace");
logger.LogDebug("LogDebug");
logger.LogInformation("LogInformation");

logger.LogWarning("LogWarning");
logger.LogError("LogError");
logger.LogCritical("LogCritical");
```

**Comment by jodydonetti** [comment] 2022-12-22 06:58
I think the issue is that you are confronting the result for the top level logger's `IsEnabled(LogLevel)` call (which combines all the sub-loggers) with what you see in the console, which is the result of **one** specific sub-logger (the `ConsoleLogger`).

So basically with the `IsEnabled(LogLevel)` call what you are asking is "is **any** sub-logger ok with this log level?" whereas what you see in the console depends **only** on the `ConsoleLogger`.

Makes sense?

**Comment by jodydonetti** [comment] 2022-12-22 09:51
I've never had to do that programmatically, so I don't have that experience.
Based on [the docs](https://learn.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line#set-log-level-by-command-line-environment-variables-and-other-configuration) it seems it's not something that is natively supported.

But again, maybe it's better if someone from Microsoft would answer this.

**Comment by jodydonetti** [comment] 2022-12-22 09:52
Maybe playing with the initial setup and doing a `Clear()` + `AddConsole(...)` or something like that, like in [this](https://thecodeblogger.com/2021/05/15/multiple-ways-to-set-minimum-log-level-in-net-applications/) blogpost 🤷 ?

**Comment by tarekgh** [comment] 2023-01-10 17:20
If you set the default log level in the configuration (in appsettings json files), then this setting will take higher priority and calling will not have effect. You may review https://learn.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-7.0#default-log-level which states:

```
The following code sets the default log level when the default log level is not set in configuration:
```

```C#
var builder = WebApplication.CreateBuilder();
builder.Logging.SetMinimumLevel(LogLevel.Warning);
```

If you want to have `SetMinimumLevel` take effect, you'll need to remove the default logging level from the configuration. By that I am closing the issue. Feel free to send any question we may help with.

**Closed by tarekgh** 2023-01-10 17:20 UTC
Labels: area-Extensions-Logging
