### ISSUE TITLE
System.Diagnostics.Process.sln fails to build in Visual Studio

### ISSUE THREAD

**Issue by fandrei** [dotnet/runtime#51601] opened 2021-04-21 00:16 UTC
### Description

```
build -subset clr -configuration debug
build -subset libs -configuration debug -runtimeconfiguration debug
build -vs System.Diagnostics.Process
```
After this, I'm trying to build System.Diagnostics.Process.sln in Visual Studio and getting these errors:
```
Error occurred while restoring NuGet packages: Invalid restore input. Duplicate frameworks found: 'net6.0-windows7.0, net6.0, netstandard2.0, netstandard2.0, net461'. Input files: <PATH>\runtime\src\libraries\Microsoft.Win32.Registry\src\Microsoft.Win32.Registry.csproj.

CSC : error CS0006: Metadata file '<PATH>\runtime\artifacts\bin\System.Drawing.Common\net6.0-Unix-Debug\System.Drawing.Common.dll' could not be found
```

### Configuration

Windows 10 x64
.NET 6.0 Preview 2
VS 16.9.4

**Comment by ViktorHofer** [comment] 2021-04-21 16:48
Assigning @Anipik. He will take a look when he has some cycles after Preview 4 work is done.

**Comment by ericstj** [comment] 2021-07-27 17:54
The original problem here was caused by the SLN file missing `System.Drawing.Common`.  I tried to update the SLN's using SLNGen here: https://github.com/ericstj/runtime/commit/b50f32f2d5fb40a75b1841c2f2eaa9596a50caae#diff-25b59c493b7dab638637a5692c6a479434b2dfc4ebd1fc9582b7cd63b5b44b21R24

This fixed the SLN but now the build is failing as follows (in VS), which is the same thing mentioned in https://github.com/dotnet/runtime/issues/53529
```
9>C:\Users\erics\.nuget\packages\microsoft.dotnet.genfacades\6.0.0-beta.21370.12\build\Microsoft.DotNet.GenPartialFacadeSource.targets(27,5): error : Did not find type 'System.Drawing.Bitmap' in any of the seed assemblies.
9>C:\Users\erics\.nuget\packages\microsoft.dotnet.genfacades\6.0.0-beta.21370.12\build\Microsoft.DotNet.GenPartialFacadeSource.targets(27,5): error : Did not find type 'System.Drawing.BitmapSuffixInSameAssemblyAttribute' in any of the seed assemblies.
9>C:\Users\erics\.nuget\packages\microsoft.dotnet.genfacades\6.0.0-beta.21370.12\build\Microsoft.DotNet.GenPartialFacadeSource.targets(27,5): error : Did not find type 'System.Drawing.BitmapSuffixInSatelliteAssemblyAttribute' in any of the seed assemblies.
9>C:\Users\erics\.nuget\packages\microsoft.dotnet.genfacades\6.0.0-beta.21370.12\build\Microsoft.DotNet.GenPartialFacadeSource.targets(27,5): error : Did not find type 'System.Drawing.Brush' in any of the seed assemblies.
...
```

I can reproduce the same thing from the command-line if I build the project for this TargetFramework and don't build ProjectReferences:
```
dotnet msbuild /bl /p:BuildProjectReferences=false /p:TargetFramework=netcoreapp3.1
```

Dropping `/p:BuildProjectReferences=false` makes it succeed.

The difference between the two is that when project references are not built, the not-supported source isn't passed to the gen facades task. (Aside: I don't think the targets for facades and not-supported assemblies make sense together since not-supported assemblies assume that everything in the contract is not supported, which makes GenFacades irrelevant).

The reason for this difference is that `_GetGenFacadeNotSupportedCompileInputs` is not finding the sources.  This appears to have been regressed by https://github.com/dotnet/arcade/commit/516eb1e7fae3228cc7159aca3133c6c58a86c3f2#diff-36f97615b83f7a82f10b4f885cd942304f49b73cced7e809c156b0a241893d87R34

This changed the name of the Target used, but missed updating the name of that target in the condition (this codepath is *only* used during VS builds).  I'll submit a fix for that.

**Comment by ViktorHofer** [comment] 2021-07-27 17:57
Excellent find @ericstj 👍. As you can see in the change, I did update the target name in the condition but unfortunately to the wrong one :(

**Comment by FWest98** [comment] 2021-07-28 16:17
I am encountering this issue as well. I currently can't build `System.DirectoryServices.AccountManagement` (or any of the associated tests) . I got many of the `CS0006` errors (metadata not found). After updating the sln file to the entry in #56430, I get the same errors about seed assemblies as above https://github.com/dotnet/runtime/issues/51601#issuecomment-887712604...

Is there anything I can do now manually to make the builds within VS work?

**Comment by ericstj** [comment] 2021-07-28 17:29
Try updating https://github.com/dotnet/runtime/blob/a6b9a63f3521d8217c3639aefd97001287f78ae8/eng/Versions.props#L59
To 6.0.0-beta.21378.2

The fix for the seed assemblies change hasn't made it into dotnet/runtime yet.

**Comment by ViktorHofer** [comment] 2021-09-03 09:15
Fixed with the GenFacades fix in the Arcade repo.

**Closed by ViktorHofer** 2021-09-03 09:15 UTC
Labels: area-Infrastructure-libraries
