### ISSUE TITLE
Microsoft.Extensions.Configuration.ConfigurationBinder.Get<T> is too slow

### ISSUE THREAD

**Issue by czd890** [dotnet/runtime#33954] opened 2020-03-23 10:47 UTC
`Config.json` have 18k+ items, `ConfigurationBinder.Get` api is too slow. 

Microsoft.Extensions.Configuration: 3.1.2

Config.json
```json
{
    "A": {
        "B": {
            "Item1":  {"Key":{"Key":["V1","V2"]}},
            "Item2":  {"Key":{"Key":["V1","V2"]}},
            "Item3":  {"Key":{"Key":["V1","V2"]}}
        }
    }
}
```
```C#
            var sw = new System.Diagnostics.Stopwatch();
            sw.Start();
            var b = new ConfigurationBuilder();
            b.AddJsonFile("Config.json");
            Console.WriteLine("Buiding: " + sw.ElapsedMilliseconds);
            var f = b.Build();
            Console.WriteLine("Build: " + sw.ElapsedMilliseconds);
            var f2 = f.GetSection("A");
            Console.WriteLine("Section: " + sw.ElapsedMilliseconds);
            
            var a = f2.Get<A>();
            Console.WriteLine("Bind: " + sw.ElapsedMilliseconds + ", Count:" + a.B.Count);
```
```shell
Buiding: 3
Build: 285
Section: 286
Bind: 54167, Count:18507
```
@maryamariyan @safern Is there any way to improve performance?

**Comment by maryamariyan** [comment] 2020-03-24 04:24
cc: @anurse @JunTaoLuo

**Comment by permagne** [comment] 2020-05-07 19:22
Any update on this issue?

**Comment by Kahbazi** [comment] 2020-05-09 09:28
This issue (https://github.com/dotnet/runtime/issues/36130) could improve configuration binding performance.

**Comment by maryamariyan** [comment] 2020-10-02 18:19
Closing as dupe of https://github.com/dotnet/runtime/issues/36130

**Closed** 2020-10-02 18:19 UTC
Labels: area-Extensions-Configuration, tenet-performance

**Comment by davidfowl** [comment] 2020-10-02 18:35
Yep @maryamariyan we should close as dupe of https://github.com/dotnet/runtime/issues/36130
