### ISSUE TITLE
[6.0][7.0] MacCatalyst Mono - XcodeBuildApp failed moving directory

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#79859] opened 2022-12-20 16:58 UTC
## Build Information
Build:
    - 6.0: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=111127
    - 7.0: https://dev.azure.com/dnceng-public/public/_build/results?buildId=109536&view=results
Build error leg or test failing:
    - Build MacCatalyst x64 Release AllSubsets_Mono_AppSandbox / Build product
    - Build MacCatalyst x64 Release AllSubsets_Mono / Build product
Pull requests:
    - #79620
    - #79549
    - #79547

Example error on 6.0:
```
src/libraries/tests.proj(416,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Build) The "XcodeBuildApp" task failed unexpectedly.
System.IO.DirectoryNotFoundException: Could not find a part of the path '/Users/runner/work/1/s/artifacts/bundles/tests.all/NormalTestAppBundles/IcuAppLocal.Tests/AppBundle/Release-maccatalyst/IcuAppLocal.Tests.app'.
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at Xcode.BuildAppBundle(String xcodePrjPath, Boolean optimized, String devTeamProvisioning, String destination) in /_/src/tasks/AppleAppBuilder/Xcode.cs:line 529
   at XcodeBuildApp.Execute() in /_/src/tasks/AppleAppBuilder/Xcode.cs:line 108
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

Example error on 7.0:
```
src/libraries/tests.proj(745,5): error MSB4018: (NETCORE_ENGINEERING_TELEMETRY=Build) The "XcodeBuildApp" task failed unexpectedly.
System.IO.DirectoryNotFoundException: Could not find a part of the path '/Users/runner/work/1/s/artifacts/bundles/tests.all/NormalTestAppBundles/System.Runtime.Tests/AppBundle/Release-maccatalyst/System.Runtime.Tests.app'.
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath, Boolean isCaseSensitiveRename)
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
   at Xcode.BuildAppBundle(String xcodePrjPath, Boolean optimized, String devTeamProvisioning, String destination) in /_/src/tasks/AppleAppBuilder/Xcode.cs:line 533
   at XcodeBuildApp.Execute() in /_/src/tasks/AppleAppBuilder/Xcode.cs:line 108
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

## Error Message

```json
{
  "ErrorMessage": "The \"XcodeBuildApp\" task failed unexpectedly.",
  "BuildRetry": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by steveisok** [comment] 2022-12-20 17:02
@akoeplinger does the change you made in main need backported?

**Comment by akoeplinger** [comment] 2022-12-20 17:07
It's waiting for the branch to open back up: https://github.com/dotnet/runtime/pull/79098

**Comment by carlossanlop** [comment] 2023-01-04 20:33
Duplicate of https://github.com/dotnet/runtime/issues/78778

**Closed by carlossanlop** 2023-01-04 20:33 UTC
Labels: blocking-clean-ci, untriaged, area-Infrastructure-mono, runtime-mono, os-maccatalyst, Known Build Error
