### ISSUE TITLE
Async io never completes in .net 6

### ISSUE THREAD

**Issue by slav** [dotnet/runtime#69377] opened 2022-05-15 21:33 UTC
### Description

We have a console application that handles web requests. After switching from .net 5 to 6 we've noticed a memory leak that eventually led to discovery that we have async pinned handles that point to OverlappedData -> _IOCompletionCallback -> ExecutionContext -> AsyncLocal (which is where we store a lot of data and where we first saw memory leak). From logs and looking at the data in pinned AsyncLocal we can see that the request processing was completed. We can clear our data out of AsyncLocal, but pinned objects will continue to accumulate, so it's not a full solution.
* We have multiple services with a lot of shared code and only specific service leaks async handles that we observed. We're not sure what it is about specific service, but downgrading from .net 6 back to .net 5 resolved the leak with no changes to the code. We only change <TargetFramework> from net6.0 to net5.0.
* Issue happens rarely. Out of millions of requests in production we only saw around 30k handles stuck like this. In pre-production environment it was just a handful.
* We suspect that maybe async process never completes, but not sure what would lead to this. I suspect maybe it's related to handling situation when client terminates (due to timeout or for other reason) connection before response is sent back.
* We don't know the steps to reproduce, but can provide dump in private email.
* Here's an example of pinned handles in windbg
![image](https://user-images.githubusercontent.com/350987/168494420-15aafc37-0135-4242-8999-6c6bcaf2265c.png)

### Reproduction Steps

Not sure. Can only detect by checking for ExecutionContext objects held via _IOCompletionCallback

### Expected behavior

No leak of async handles.

### Actual behavior

Async handles get pinned but never released, thus preventing GC from being able to reclaim memory leading to memory leak.

### Regression?

Works in .net 5. Only broke in .net 6.

### Configuration

* .net 6.0.2 (not the latest)
* Windows Server 2012 r2 x64

### Other information

It seems to happen only on specific service. Compared to other services, this service has many more requests in parallel. I'm not sure if that's relevant. Perhaps it might be related to an interrupted client connection.

In any case, it seems that it's related to async / await and continuation never taking place.

**Comment by davidfowl** [comment] 2022-05-16 03:38
Are you using http listener? Why does your code look like?

**Comment by chris-skuvault** [comment] 2022-05-16 16:19
Hey David,

We are not using HttpListener. We use Kestrel to listen for HttpRequests. 

We do have a bit of a unique situation where we use https://github.com/NancyFx/Nancy which we have forked a while ago to handle http requests before migration to .net core. We are actively converting our services over to Web Api controllers but given that our codebase is large we still have a lot of endpoints using Nancy and not Web Api. I'm not sure that's relevant to the issue as this behavior only happens on one service we run and the others are not affected at all by this issue.

Kestrel Setup:

```c#
Host.CreateDefaultBuilder()
	.ConfigureWebHostDefaults(
		builder =>
		{
			builder.UseShutdownTimeout(TimeSpan.FromSeconds(30));
			builder.UseStartup<TStartup>()
				.ConfigureKestrel(
					options =>
					{
						options.Listen(IPAddress.Any, cfg.BindPort);
						options.AllowSynchronousIO = true;
						options.Limits.MinRequestBodyDataRate = null;
					});

		});
```
Middleware configuration:

```c#
app.UseRouting()
.UseAuthentication()
.UseAuthorization()
.UseEndpoints(
	endpoints =>
	{
		endpoints.MapDefaultControllerRoute();
		endpoints.MapControllers();
	})
.UseNancy(NancyMiddlewareRegistrationDelegate(app), Token);
```
Let me know what other information you could use that might help. 

As @slav mentioned it only happens for one of our services and the only then that is needed to reproduce it is to switch from .net5.0 to .net6.0 with no other code changes. I looked through https://docs.microsoft.com/en-us/dotnet/core/compatibility/6.0 but couldn't find something that changed that might point to this issue.

**Comment by davidfowl** [comment] 2022-05-16 19:10
I'd need to see more code to better understand this leak. Hard to tell what's wrong from the information above.

**Comment by slav** [comment] 2022-05-16 19:30
@davidfowl - we'd be happy to show more of the code, dumps, etc, but we can't share much more in public forum. Can you email me directly and we'll share more privately?

**Comment by onurkanbakirci** [comment] 2022-05-19 21:38
Is there any solution? You can share more detail with me.

**Comment by slav** [comment] 2022-05-21 14:10
So far the only solution we found is to downgrade to .net 5.

**Comment by davidfowl** [comment] 2022-05-26 03:12
@onurkanbakirci What are you experiencing?

**Comment by onurkanbakirci** [comment] 2022-05-26 06:02
Code shared above not enough to say or guess what's actually happening @davidfowl .

**Comment by stephentoub** [comment] 2022-05-29 00:27
There is a bug in https://github.com/dotnet/runtime/blob/f8229bbe7f6642367241ed1158a912d169cc1252/src/libraries/System.Private.CoreLib/src/System/IO/RandomAccess.Windows.cs#L74 and https://github.com/dotnet/runtime/blob/f8229bbe7f6642367241ed1158a912d169cc1252/src/libraries/System.Private.CoreLib/src/System/IO/RandomAccess.Windows.cs#L168.  If a synchronous read/write is issued against a file handle opened for asynchronous I/O, and if the underlying ReadFile/WriteFile operation performed in the OS fails, these will end up leaking a `NativeOverlapped`.  Is it likely your app is encountering that?  Do you see any exceptions coming from those functions that correspond to when you're seeing a leak happening?

A simple repro:
```C#
using Microsoft.Win32.SafeHandles;

using (SafeFileHandle handle = File.OpenHandle("tmp.dat", FileMode.Create, FileAccess.Write, FileShare.None, FileOptions.Asynchronous))
{
    while (true)
    {
        try
        {
            RandomAccess.Read(handle, new byte[1], 0);
            throw new Exception("should not get here");
        }
        catch (UnauthorizedAccessException)
        {
        }
    }
}
```

**Comment by davidfowl** [comment] 2022-05-29 03:21
We should also mention that RandomAccess is used indirection by FileStream.

FileStream -> BufferedFileStreamStrategy -> AsyncWindowsFileStreamStrategy -> RandomAccess

https://github.com/dotnet/runtime/blob/7aa40101f02ebaa47dfc3c3384af6a94e971817d/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/OSFileStreamStrategy.cs#L249

https://github.com/dotnet/runtime/blob/7aa40101f02ebaa47dfc3c3384af6a94e971817d/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/OSFileStreamStrategy.cs#L225

Which hits this code path. The only thing we haven't narrowed down so far is the exception theory (if your app is seeing exceptions that might be resulting in this leak).

**Comment by chris-skuvault** [comment] 2022-05-29 05:00
I don't think we saw any exceptions occurring when the memory leak was going on but will try and reproduce and confirm that next week. Looking through our code I do see that we seem do what @stephentoub mentioned above where we open an async FileStream then stream.CopyTo(fileStream) gets called which is a synchronous operation. 

The exception piece is the only one that I need to look into a bit to see if we are getting exceptions when we have this issue happening and if not why. Will work to clarify this point next week and post more information about what I found here. The issue is reproducible in our preprod env so hopefully it won't take long to track this down.

Will also try DOTNET_SYSTEM_IO_USENET5COMPATFILESTREAM=1 as a quick test to switch .net6 filestream back to .net5 and confirm the issue is for sure net6 filestream related, though I'm pretty sure we are running into the issue @stephentoub described above. 

Thanks for all the help!

**Comment by slav** [comment] 2022-05-29 22:59
@davidfowl @stephentoub just a side question, based on the bug it seems to be Windows specific? It wouldn't be an issue on Linux?

**Comment by stephentoub** [comment] 2022-05-29 23:08
Correct. If you see it on Linux, it's a different issue. Do you?

**Comment by slav** [comment] 2022-05-30 03:22
Right now we're only setup to run the service which experienced the issue on windows. If we run into it on linux, will let you know. Was just asking to confirm understanding of the scope.

**Comment by chris-skuvault** [comment] 2022-06-01 16:44
@stephentoub @davidfowl 

I had a chance to test this out and here are the results:

Setting DOTNET_SYSTEM_IO_USENET5COMPATFILESTREAM=1 does appear to cause the memory issue not to occur anymore. I debugged a bit and see that it does seem to throw inside of Random.Access.Windows.cs but what I'm seeing is a bit different that what @stephentoub showed in his reproduction steps though there is a difference as I'm writing and not reading. From what I can tell the exception I see thrown gets thrown https://github.com/dotnet/runtime/blob/7aa40101f02ebaa47dfc3c3384af6a94e971817d/src/libraries/System.Private.CoreLib/src/System/IO/RandomAccess.Windows.cs#L217.

Strange thing about this is that this IOException doesn't actually bubble up to the caller and I don't see it prevent the file from being created or has any negative impact on the operation of the filestream (Except the leak of course). So we don't see an exception in our codebase while the leak is happening but there seems to be the IOException getting thrown we just aren't able to catch or observe it outside of debugging. 

In this case the difference is that I am doing a Write were as the example is doing a read but I couldn't get a read to throw an exception either.

Here is my code which I can observe the IOException on write but don't see it bubbling up.

```c#
public void Test()
	{
		var folderPath = Path.GetTempPath();
		var filePath = Path.Combine(folderPath, Guid.NewGuid().ToString("N") + "-test.tmp");
		using var fs = new FileStream(
			filePath,
			FileMode.Create,
			FileAccess.ReadWrite,
			FileShare.None,
			10,
			true);

		var bytes = Encoding.UTF8.GetBytes("**********************************************");
		using var ms = new MemoryStream(bytes);

		try
		{
			ms.CopyTo(fs);
		}
		catch (Exception ex)
		{
			TestContext.WriteLine(ex);
		}
		
		ms.Flush();
		fs.Flush(true);
	}
```

Anything else I could try to help test this case?

**Comment by stephentoub** [comment] 2022-06-01 16:51
> what I'm seeing is a bit different that what @stephentoub showed in his reproduction steps though there is a difference as I'm writing and not reading. From what I can tell the exception I see thrown gets thrown

Yes, that's the same case; thesame issue exists on both the reading and writing sides.  Thanks for confirming.

> So we don't see an exception in our codebase while the leak is happening but there seems to be the IOException getting thrown we just aren't able to catch or observe it outside of debugging.

Can you share the stack when it occurs?  Presumably you're calling into some other library (Nancy?) that is in turn doing these writes and is eating the exception.  If you hook up an event handler to `AppDomain.CurrentDomain.FirstChanceException`, you should be able to observe them even outside of a debugger.  But regardless everything you've shared suggests the cited issue is indeed the root cause, such that https://github.com/dotnet/runtime/pull/69956 should fix it for you.

**Comment by slav** [comment] 2022-06-01 17:34
@stephentoub are you planning to backport the fix to .net 6? Or it'll only be out with .net 7?

**Comment by chris-skuvault** [comment] 2022-06-01 21:50
> > This write IOException is reproducible inside the test I created above.
> 
> I've been unable to repro using that code, unfortunately. I'm on a different version of Windows, though, so maybe specific to Windows Server 2012 r2.

Windows Server 2012 r2 is where the code runs when deployed but for this test I've reproduced it on windows 11 using Rider IDE. It doesn't seem to prevent the filestream behavior as it creates a file on the filesystem with the correct data in it. Just when stepping through the code via the debugger I see that it hits that line.

Can you reproduce the issue you mentioned about an `UnauthorizedAccessException` being thrown with the code I am testing with?

Maybe its just behavior because I've attached a debugger, without debugger I don't see it behave differently? Though the comment where it throws matches with the scenario I'm trying as I have a asynchronous handle and a synchronous write

```c#
  case Interop.Errors.ERROR_INVALID_PARAMETER:
                            // ERROR_INVALID_PARAMETER may be returned for writes
                            // where the position is too large or for synchronous writes
                            // to a handle opened asynchronously.
                            throw new IOException(SR.IO_FileTooLong);
```

Based on what you said about `UnauthorizedAccessException` it seems like you'd expect it to hit

```c#
  case Interop.Errors.ERROR_ACCESS_DENIED:
                    return new UnauthorizedAccessException(
                        string.IsNullOrEmpty(path) ? SR.UnauthorizedAccess_IODenied_NoPathName : SR.Format(SR.UnauthorizedAccess_IODenied_Path, path));
```
Case as that is the only case that throws a `UnauthorizedAccessException`. 

With the test code I've written above is that sufficient to reproduce this issue or is something not setup correctly? I wrote the test based on what the Nancy implementation is doing but I don't seem to get the expected output.

**Comment by stephentoub** [comment] 2022-06-01 22:03
> Can you reproduce the issue you mentioned about an UnauthorizedAccessException being thrown with the code I am testing with?

No, the code you shared runs successfully, without exception, i.e. I paste this into a console app:
```C#
using System.Text;

var folderPath = Path.GetTempPath();
var filePath = Path.Combine(folderPath, Guid.NewGuid().ToString("N") + "-test.tmp");
using var fs = new FileStream(
    filePath,
    FileMode.Create,
    FileAccess.ReadWrite,
    FileShare.None,
    10,
    true);

var bytes = Encoding.UTF8.GetBytes("**********************************************");
using var ms = new MemoryStream(bytes);

try
{
    ms.CopyTo(fs);
}
catch (Exception ex)
{
    Console.WriteLine(ex);
}

ms.Flush();
fs.Flush(true);
```
and run it, with `dotnet run`, with `ctrl-F5` in VS, and with `F5` in VS, and in all situations it runs successfully to completion, without exception, and the temporary file created contains the expected data.

> the only case that throws a UnauthorizedAccessException

My example with UnauthorizedAccessException was when reading, not when writing.  The repro I shared was just an example of how the leak would happen if the native I/O operation failed in the OS; for that repro I was creating the file as write-only, then trying to read from it, which triggers https://github.com/dotnet/runtime/blob/f8229bbe7f6642367241ed1158a912d169cc1252/src/libraries/System.Private.CoreLib/src/System/IO/RandomAccess.Windows.cs#L120 to translate the OS error code into an UnauthorizedAccessException.  The same thing is possible in the other direction, of course: open the file as read-only, then try to write to it:
```C#
var filePath = Path.GetTempFileName();
using var sfh = File.OpenHandle(filePath, FileMode.Open, FileAccess.Read, FileShare.None, FileOptions.Asynchronous);
while (true)
{
    try
    {
        RandomAccess.Write(sfh, new byte[1], 0);
    }
    catch (UnauthorizedAccessException)
    {
        // leak
    }
}
```

**Comment by chris-skuvault** [comment] 2022-06-02 14:50
@stephentoub @davidfowl 

I can't repro it either in a console app, only debugging do I see the IOException happening and it doesn't bubble out of the location its thrown so not sure what's going on there. I haven't gotten an exception to throw or noticed an exception ever throwing with our current implementation. The memory leak is the only indication of an issue.

Ultimately I ran some more tests and it seems like we can't fix the code to be async because NewtonSoft is used for serialization in the model binding logic in the Nancy library and that will call the sync method on the FileStream. I made the application throw an exception if a sync path was used and determined that serialization will use a sync path and we don't really have control over that other than reimplementing the serializer with System.Text.Json which we don't want to do at the moment because we are migrating to web api.

I see two options and wanted to see what was recommended, I tested both of these options and the memory leak does not happen

1. The FileStream implementation uses sync calls for the most part so it looks like we can just switch the FileStream to be sync from async
2. Use the flag DOTNET_SYSTEM_IO_USENET5COMPATFILESTREAM=1 and leave the FileStream async.

I lean toward the first option as nearly all of the operations being done with the FileStream are sync operations and there isn't a good way to switch everything to start using async. The second option isn't bad either as this is the only place in our applciatin that we use FileStream so setting the flag should be low impact but we might get some of the performance improvements of .net6 rewrite if we use sync FileStream. I'm not exactly sure. Of course once the bug is fixed we can reevaluate but would like to get our application on .net6 soon.

What do you all think is the best path forward?

**Comment by stephentoub** [comment] 2022-06-02 15:19
> What do you all think is the best path forward?

If your FileStreams are being used synchronously, option 1 is a good way to go.

**Comment by slav** [comment] 2022-06-02 18:02
> > What do you all think is the best path forward?
> 
> If your FileStreams are being used synchronously in the vast majority case, option 1 is a good way to go.

So, creating FileStream as async provides benefit only for async methods? Sync methods will work the same way with the same resources consumption regardless whether the stream is marked as async or not?

**Comment by stephentoub** [comment] 2022-06-02 18:06
> So, creating FileStream as async provides benefit only for async methods?

Yes.  File I/O on Windows requires opening the file for either overlapped I/O (aka async) or not, and all subsequent operations on the file need to be performed in that manner.  That means if you open the file for async I/O but then use the synchronous methods, we need to emulate the synchrony by using the overlapped functionality and blocking until it completes, rather than just performing synchronous I/O.  Similarly, if you open the file for sync I/O and use the async methods, we have to simulate that asynchrony by queueing work items that just perform the synchronous I/O.

> Sync methods will work the same way with the same resources consumption regardless whether the stream is marked as async or not?

Sync methods are more expensive on a FileStream created as FileOptions.Asynchronous than on FileStreams created without that flag.

**Comment by davidfowl** [comment] 2022-06-03 05:05
The most interesting thing about this bug is that the execution context capture lead me to that code 😄. Happy accident.

**Comment by adamsitnik** [comment] 2022-06-20 16:51
@slav thanks for a very detailed bug report

@stephentoub thanks for the fix!

Since both 7.0 and 6.0 PRs got merged, I am going to close the issue.

**Closed by adamsitnik** 2022-06-20 16:51 UTC
Labels: bug, area-System.IO
