### ISSUE TITLE
Stdin is redirected to stdout on Linux

### ISSUE THREAD

**Issue by cfbao** [dotnet/runtime#86851] opened 2023-05-28 21:46 UTC
### Description

On Linux, when executing a .NET console program with its stdout redirected/captured, user input is no longer displayed on screen, but appears in the redirected/captured output instead.

The same doesn't happen on Windows or other programming languages I tried.

### Reproduction Steps

On Linux, create a console program named "test" (.NET 6, 7 or 8) with the following code:

```csharp
Console.ReadLine();
Console.WriteLine("Hello, World!");
```

In the console, run `test` like so
```
> ./test > output
```
and enter "abc" when prompted by `Console.ReadLine()`

### Expected behavior

User input (e.g. "abc" in the example) is displayed on screen, and not be in the captured output.
i.e. on the console
```
> ./test > output
abc
> cat output
Hello, World!
```
This is the behaviour on Windows, but not Linux.

### Actual behavior

User input is not displayed on screen, but is present in the captured output.
i.e. on the console
```
> ./test > output
> cat output
abc
Hello, World!
```

### Regression?

No. This behaviour is present since .NET 6, maybe earlier.

### Known Workarounds

None found (so far 🤞)

### Configuration

.NET 6 & 7 & 8
Ubuntu on WSL
x64
Issue specific appears to be specific to Linux. At least it doesn't happen under Windows 10 on my machine.

### Other information

Similar behaviour happens for PowerShell 7.3 on Linux (but not Windows), but even weirder

code
```pwsh
$_ = Read-Host
Write-Output 'Hello, World!'
```

on the console
```
> pwsh test.ps1 > output
> cat output
aababc
Hello, World!
```

**Comment by adamsitnik** [comment] 2023-05-29 15:12
Hello @cfbao 

Thank you for a detailed bug report with a repro case. It's a duplicate of #22314, so I am going to close it. Please follow #22314 for updates.

@tmds is there any chance you would like to take a look at it?

**Closed by adamsitnik** 2023-05-29 15:12 UTC
Labels: area-System.Console, untriaged
