### ISSUE TITLE
Consider Implementing IDisposable in GCHandle

### ISSUE THREAD

**Issue by Gnbrkm41** [dotnet/runtime#29528] opened 2019-05-12 21:09 UTC
(Pretty much duplicate of dotnet/runtime#26854, re-opening due to reason that is to be explained)

GCHandle is supposed to be freed once it goes out of scope: [otherwise, memory leaks may occur](https://docs.microsoft.com/en-gb/dotnet/api/system.runtime.interopservices.gchandle?view=netframework-4.8). Although it has a `Free()` method which does that, it does not implement `IDisposable` and `Dispose()` method which lets it to be used in `using` blocks. Having it would be helpful since major .NET Languages such as C#, VB.NET, and F# provides syntactic sugar for using disposable types, `using` / `use`. I believe it's a pretty common practice for disposing of types that hold unmanaged resources.

The original issue, dotnet/runtime#26854, discusses about the exact same suggestion; however, [the language feature proposal](https://github.com/dotnet/csharplang/issues/1623) appear to have changed not to include this change for non-ref struct types, due to backwards-compat concerns. 

>[jcouv update:] This feature was restricted to ref structs due to backwards compatibility reasons. Also, the part about considering extension methods was split out of this feature, and it was not implemented in dev16.0 milestone.

This leaves the original problem unsolved. For that reason, I suggest that we reconsider implementing the interface on the type.

**Comment by AaronRobinsonMSFT** [comment] 2021-08-06 02:59
Closing this as a duplicate of https://github.com/dotnet/runtime/issues/54792. This one should have been used but was missed. A lot of conversation has occurred on the new issue with a referenced PR.

**Closed by AaronRobinsonMSFT** 2021-08-06 02:59 UTC
Labels: area-System.Runtime.InteropServices
