### ISSUE TITLE
Http calls failing when Debugging, works fine without Debug

### ISSUE THREAD

**Issue by nssidhu** [dotnet/runtime#43400] opened 2020-10-14 01:18 UTC
after upgrading to RC2, getting different kind of error.
Failed to load resource: net::ERR_CONNECTION_REFUSED

here is the Message handler where it fails

```
    public class MessageHandler : DelegatingHandler
    {
        ILogger<MessageHandler> _logger;
        private readonly IJSRuntime _jsRuntime;
        public MessageHandler(ILogger<MessageHandler> logger, IJSRuntime jsRuntime)
        {
            _logger = logger;
            _jsRuntime = jsRuntime;

        }

        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken ct)
        {
            var token = await _jsRuntime.InvokeAsync<string>("localStorage.getItem", "authToken");
            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
            var response = await base.SendAsync(request, ct);
            return response;
        }
    }

```
![image](https://user-images.githubusercontent.com/3267605/95932231-e7c79300-0d90-11eb-86dc-f7f9d913921d.png)

**Comment by wfurt** [comment] 2020-10-14 22:11
note that when stepping through the code, remote site may not wait and it can timeout or react to lack of timely response.

**Comment by nssidhu** [comment] 2020-10-15 17:29
its a hosted webassembly project so not calling external API. As i mentioned what i am finding out is that it just kills the IIS Express, there is no IIS express instance running neither is VS is Debug Mode any more. Looks like something is crashing IIS altogether when debugging. Things work fine when CTRL + F5 (Run withoud Debug ). Will shortly upload the Sample Source Code

**Comment by nssidhu** [comment] 2020-10-15 22:49
Here is the link to the Source code.

[(https://1drv.ms/u/s!AtHk7h6Srnk_h55iI1WNRQ4seaN-ZA?e=ohecKw)]

**Comment by thaystg** [comment] 2020-10-15 23:09
You don't need to add any breakpoint or to step over anywhere, only the debugger attached is enough to get the error?

**Comment by nssidhu** [comment] 2020-10-16 00:10
yes, just run into Debug mode, no need to set any break points

**Comment by thaystg** [comment] 2020-10-16 16:48
I could see in the video that you are using RC1. As you can see here: 
![image](https://user-images.githubusercontent.com/4503299/96284661-4751b880-0fb4-11eb-956e-c887d03db1a5.png)
Could you please try with RC2? I couldn't reproduce the bug.
I'm using Visual Studio 2019 Version 16.8.0 Preview 4.0, Microsoft.NetCore.App 5.0.0-rc.2.20475.5, Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17.

**Comment by nssidhu** [comment] 2020-10-16 17:03
Not sure, why it is using RC1, if you look at the reference in project files it is all RC2.
What could i be missing ?
![image](https://user-images.githubusercontent.com/3267605/96287447-90e7d680-0fa7-11eb-8c28-223404577b60.png)

**Comment by thaystg** [comment] 2020-10-16 17:56
I'm not sure... and I'm sorry to ask you this kind of thing, but do you have rc2 installed?
![image](https://user-images.githubusercontent.com/4503299/96292103-73bf0200-0fbf-11eb-8619-00b6b432f579.png)
When you run dotnet --version on console which version do you see?

**Comment by nssidhu** [comment] 2020-10-17 01:47
Yes, i did, after that only i started running into this problem
Here is the screen shot.
![image](https://user-images.githubusercontent.com/3267605/96325765-50607b00-0ff0-11eb-9047-99be9990d2b3.png)

Installed it from here (https://dotnet.microsoft.com/download/dotnet/5.0)

**Comment by nssidhu** [comment] 2020-10-17 02:16
OK after updating Visual Studio to Version 16.8.0 Preview 4.0 it started working.
Just installing .NET 5 RC2 was not enough.

**Comment by thaystg** [comment] 2020-10-19 14:22
Can we close the issue?

**Comment by nssidhu** [comment] 2020-10-19 14:34
Yes


Sent from Yahoo Mail for iPhone


On Monday, October 19, 2020, 9:23 AM, Thays Grazia <notifications@github.com> wrote:




Can we close the issue?

**Closed** 2020-10-19 14:35 UTC
Labels: area-System.Net.Http, untriaged
