### ISSUE TITLE
LINQ on IList<T> returning IList<T> when possible

### ISSUE THREAD

**Issue by weitzhandler** [dotnet/runtime#469] opened 2019-12-03 03:06 UTC
Hi,

`IList<T>` provides superior functionality of `IEnumerable<T>`, in the fact that it allows random access.
Some projection or conversion LINQ queries (i.e. `Select` or `Cast`, do not change the count of the items.
I was wondering if there could be another limited set of LINQ extension methods that accept an `IList<T>` such that do not change the collection count or its order, and return a readonly `IList<T>` that internally keeps track of the source collection and allows for random access.

Has this ever been discussed?

**Comment by Clockwork-Muse** [comment] 2019-12-03 07:12
It doesn't change the count of the items in the list, no.

It also doesn't change the _contents_ of the list, which means the "simple" answer to this is to just call whatever the `Func` you would have passed to `Select` directly:
``` csharp
var result = SelectFunc(originalList[listIndex]);
```

... this is primarily because the next step after this would be to do some form of transformative view:

```csharp
public class TransformativeView<TView> : IList<TOriginal> 
{
    public TransormativeView(IList<TOriginal> list, Func<TView, TOriginal> map);

    public TView this[int key]
    {
        // Setter needs an inverse function!
        get => map(list[key]);
    }
}
```
... however this is only worthwhile if the access will be _sparse_, that is, not over some (usually large) percentage of the list.  Over smaller lists, you'd likely see better performance by simply mapping the entire list and taking the copy.  Over larger lists, as the percentage of rows accessed grows, it would again be more performant to map the entire list; if you plan on randomly accessing the entire list, you're almost certainly going to be better off mapping everything up front and hitting that instead.

**Comment by weitzhandler** [comment] 2019-12-03 07:55
In my scenario I'm dealing with sheets of data-set rows, and have to extract some rows by index.

**Comment by quinmars** [comment] 2019-12-03 12:18
@weitzhandler In fact that is already done behind the scenes via type tests. For example `ilist.Skip(5).Select(x => x.Index).ToArray()` can allocate the correct array size from the beginning.

**Comment by Clockwork-Muse** [comment] 2019-12-03 16:42
@quinmars is correct though - something like 
```csharp
var result = list.Select(x => x.Whatever).ElementAt(someIndex);
```
... [will use the underlying implementation of `IList`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.elementat?view=netcore-3.0#remarks) (I completely forgot about this method existing, concentrating on the "whole" list).

Note that there is still a slight performance penalty for accessing significant percentages of lists this way (because of the repeated type tests).

**Comment by weitzhandler** [comment] 2019-12-04 00:36
You're right. Both `Select` and `ElementAt` return a wrapper against the source list.
Should I close this issue, or leave it open to discuss adding another overload like this:

```c#
public static IList<TResult> Select<TSource, TResult>(
    this IList<TSource> collection, Func<TSource, TResult> selector);

public static IList<TResult> Cast<TSource, TResult>(this IList<TSource> collection);

 public static IList<TResult> Zip<TFirst, TSecond, TResult>(this IList<TFirst> first, IList<TSecond> second, Func<TFirst, TSecond, TResult> resultSelector);       
```

The advantage is clarity of intention. It makes it obvious that the returned collection allows for _O(1)_ random access.

**Comment by eiriktsarpalis** [comment] 2020-06-04 15:52
Triage: 
I think the main issue with including a `Select` overload that returns `IList<T>` is that it will necessarily have different execution semantics compared to the regular Select method. This can result in unexpected behaviour depending on your source type. For example:

```csharp
List<int> input = Enumerable.Range(1,100).ToList();

input.Select(x => { Console.WriteLine(x); return x }); // this will print 100 lines
((IEnumerable<int>)input).Select(x => { Console.WriteLine(x); return x }); // this will print nothing
```

**Comment by eiriktsarpalis** [comment] 2020-06-26 14:53
I am going to close this issue for now.

**Closed by eiriktsarpalis** 2020-06-26 14:53 UTC
Labels: area-System.Linq
