### ISSUE TITLE
Timeout in System.Net.Http.Functional SocketsHttpHandler tests

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#101463] opened 2024-04-24 00:32 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=653747
Build error leg or test failing: Build / Libraries Test Run release coreclr linux x64 Debug / Send to Helix
Pull request: https://github.com/dotnet/runtime/pull/95830

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorPattern": ["System\\.Net\\.Http\\.Functional\\.Tests\\.SocketsHttpHandler.+ \\[FAIL\\]", "System\\.TimeoutException : The operation has timed out"],
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=653747
**Error message validated:** `[System\.Net\.Http\.Functional\.Tests\.SocketsHttpHandler.+ \[FAIL\] System\.TimeoutException : The operation has timed out`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 4/25/2024 3:07:32 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[705030](https://dev.azure.com/dnceng-public/public/_build/results?buildId=705030)|dotnet/runtime|[System.Net.Http.Functional.Tests.SyncHttpHandler_HttpClientHandler_Cancellation_Test.Expect100Continue_WaitsExpectedPeriodOfTimeBeforeSendingContent](https://dev.azure.com/dnceng-public/public/_build/results?buildId=705030&view=ms.vss-test-web.build-test-results-tab&runId=17582014&resultId=104396)||
|[701758](https://dev.azure.com/dnceng-public/public/_build/results?buildId=701758)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ServerClosesOutboundControlStream_ClientClosesConnection](https://dev.azure.com/dnceng-public/public/_build/results?buildId=701758&view=ms.vss-test-web.build-test-results-tab&runId=17469896&resultId=213067)|dotnet/runtime#102494|
|[701308](https://dev.azure.com/dnceng-public/public/_build/results?buildId=701308)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.ReadAsStreamAsync_HandlerProducesWellBehavedResponseStream](https://dev.azure.com/dnceng-public/public/_build/results?buildId=701308&view=ms.vss-test-web.build-test-results-tab&runId=17452944&resultId=219637)|dotnet/runtime#103191|
|[698071](https://dev.azure.com/dnceng-public/public/_build/results?buildId=698071)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Http11_Cancellation_Test.ConnectTimeout_TimesOutSSLAuth_Throws](https://dev.azure.com/dnceng-public/public/_build/results?buildId=698071&view=ms.vss-test-web.build-test-results-tab&runId=17366998&resultId=103950)||
|[698063](https://dev.azure.com/dnceng-public/public/_build/results?buildId=698063)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Http11_Cancellation_Test.ConnectTimeout_TimesOutSSLAuth_Throws](https://dev.azure.com/dnceng-public/public/_build/results?buildId=698063&view=ms.vss-test-web.build-test-results-tab&runId=17367418&resultId=104366)||
|[697932](https://dev.azure.com/dnceng-public/public/_build/results?buildId=697932)|dotnet/runtime|[System.Net.Http.Functional.Tests.SyncHttpHandler_HttpClientHandler_Cancellation_Test.RequestSent_HandlerDisposed_RequestIsUnaffected](https://dev.azure.com/dnceng-public/public/_build/results?buildId=697932&view=ms.vss-test-web.build-test-results-tab&runId=17362124&resultId=212493)||
|[697183](https://dev.azure.com/dnceng-public/public/_build/results?buildId=697183)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_RequestContentLengthMismatchTest_Http3.ContentLength_DoesNotMatchRequestContentLength_Throws](https://dev.azure.com/dnceng-public/public/_build/results?buildId=697183&view=ms.vss-test-web.build-test-results-tab&runId=17338526&resultId=212521)||
|[694819](https://dev.azure.com/dnceng-public/public/_build/results?buildId=694819)|dotnet/runtime|[System.Net.Http.Functional.Tests.HttpClientHandler_RemoteServerTest.GetAsync_CredentialIsCredentialCacheUriRedirect_StatusCodeOK](https://dev.azure.com/dnceng-public/public/_build/results?buildId=694819&view=ms.vss-test-web.build-test-results-tab&runId=17260306&resultId=104509)||
|[693776](https://dev.azure.com/dnceng-public/public/_build/results?buildId=693776)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test_Http2.Expect100Continue_WaitsExpectedPeriodOfTimeBeforeSendingContent](https://dev.azure.com/dnceng-public/public/_build/results?buildId=693776&view=ms.vss-test-web.build-test-results-tab&runId=17232622&resultId=103962)||
|[692420](https://dev.azure.com/dnceng-public/public/_build/results?buildId=692420)|dotnet/runtime|[System.Net.Http.Functional.Tests.SyncHttpHandler_HttpClientHandler_Cancellation_Test.Expect100Continue_WaitsExpectedPeriodOfTimeBeforeSendingContent](https://dev.azure.com/dnceng-public/public/_build/results?buildId=692420&view=ms.vss-test-web.build-test-results-tab&runId=17197170&resultId=104381)||
|[690931](https://dev.azure.com/dnceng-public/public/_build/results?buildId=690931)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.ReadAsStreamAsync_HandlerProducesWellBehavedResponseStream](https://dev.azure.com/dnceng-public/public/_build/results?buildId=690931&view=ms.vss-test-web.build-test-results-tab&runId=17163292&resultId=219454)|dotnet/runtime#102699|
|[690890](https://dev.azure.com/dnceng-public/public/_build/results?buildId=690890)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test_Http2.Expect100Continue_WaitsExpectedPeriodOfTimeBeforeSendingContent](https://dev.azure.com/dnceng-public/public/_build/results?buildId=690890&view=ms.vss-test-web.build-test-results-tab&runId=17160036&resultId=103263)||
|[689356](https://dev.azure.com/dnceng-public/public/_build/results?buildId=689356)|dotnet/runtime|[System.Net.Http.Functional.Tests.SyncHttpHandler_HttpClientHandler_Cancellation_Test.Expect100Continue_WaitsExpectedPeriodOfTimeBeforeSendingContent](https://dev.azure.com/dnceng-public/public/_build/results?buildId=689356&view=ms.vss-test-web.build-test-results-tab&runId=17124138&resultId=104374)||
|[688895](https://dev.azure.com/dnceng-public/public/_build/results?buildId=688895)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.ReadAsStreamAsync_HandlerProducesWellBehavedResponseStream](https://dev.azure.com/dnceng-public/public/_build/results?buildId=688895&view=ms.vss-test-web.build-test-results-tab&runId=17113138&resultId=219023)|dotnet/runtime#102699|
|[688109](https://dev.azure.com/dnceng-public/public/_build/results?buildId=688109)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=688109&view=ms.vss-test-web.build-test-results-tab&runId=17088042&resultId=215178)|dotnet/runtime#102699|
|[688006](https://dev.azure.com/dnceng-public/public/_build/results?buildId=688006)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_ConnectionFrame_UpgradeFrom20_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=688006&view=ms.vss-test-web.build-test-results-tab&runId=17085834&resultId=220556)|dotnet/runtime#100951|
|[688017](https://dev.azure.com/dnceng-public/public/_build/results?buildId=688017)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=688017&view=ms.vss-test-web.build-test-results-tab&runId=17085826&resultId=215843)|dotnet/runtime#102699|
|[687900](https://dev.azure.com/dnceng-public/public/_build/results?buildId=687900)|dotnet/runtime|[System.Net.Http.Functional.Tests.SyncHttpHandler_HttpClientHandler_Cancellation_Test.Expect100Continue_WaitsExpectedPeriodOfTimeBeforeSendingContent](https://dev.azure.com/dnceng-public/public/_build/results?buildId=687900&view=ms.vss-test-web.build-test-results-tab&runId=17081386&resultId=104346)||
|[687577](https://dev.azure.com/dnceng-public/public/_build/results?buildId=687577)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_ConnectionFrame_UpgradeFrom20_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=687577&view=ms.vss-test-web.build-test-results-tab&runId=17073526&resultId=220449)|dotnet/runtime#100951|
|[687479](https://dev.azure.com/dnceng-public/public/_build/results?buildId=687479)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_ConnectionFrame_UpgradeFrom20_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=687479&view=ms.vss-test-web.build-test-results-tab&runId=17070990&resultId=220556)|dotnet/runtime#100951|
|[687411](https://dev.azure.com/dnceng-public/public/_build/results?buildId=687411)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_ConnectionFrame_UpgradeFrom20_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=687411&view=ms.vss-test-web.build-test-results-tab&runId=17066842&resultId=220556)|dotnet/runtime#100951|
|[687107](https://dev.azure.com/dnceng-public/public/_build/results?buildId=687107)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=687107&view=ms.vss-test-web.build-test-results-tab&runId=17060918&resultId=219343)|dotnet/runtime#100951|
|[687009](https://dev.azure.com/dnceng-public/public/_build/results?buildId=687009)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=687009&view=ms.vss-test-web.build-test-results-tab&runId=17058770&resultId=215858)|dotnet/runtime#100951|
|[685264](https://dev.azure.com/dnceng-public/public/_build/results?buildId=685264)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test_Http2.Expect100Continue_WaitsExpectedPeriodOfTimeBeforeSendingContent](https://dev.azure.com/dnceng-public/public/_build/results?buildId=685264&view=ms.vss-test-web.build-test-results-tab&runId=17010096&resultId=103949)||
|[685210](https://dev.azure.com/dnceng-public/public/_build/results?buildId=685210)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.ReadAsStreamAsync_HandlerProducesWellBehavedResponseStream](https://dev.azure.com/dnceng-public/public/_build/results?buildId=685210&view=ms.vss-test-web.build-test-results-tab&runId=17008880&resultId=214642)|dotnet/runtime#100951|
|[685128](https://dev.azure.com/dnceng-public/public/_build/results?buildId=685128)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=685128&view=ms.vss-test-web.build-test-results-tab&runId=17006888&resultId=216080)|dotnet/runtime#100951|
|[683977](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683977)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=683977&view=ms.vss-test-web.build-test-results-tab&runId=16977694&resultId=219181)|dotnet/runtime#100951|
|[682562](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682562)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682562&view=ms.vss-test-web.build-test-results-tab&runId=16939170&resultId=104644)||
|[682569](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682569)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682569&view=ms.vss-test-web.build-test-results-tab&runId=16939132&resultId=104644)||
|[682021](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682021)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocksProxyTest_Http2.TestLoopbackAsync](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682021&view=ms.vss-test-web.build-test-results-tab&runId=16931180&resultId=213392)||
|[681987](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681987)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Http11_Cancellation_Test.GetAsync_CancelDuringResponseHeadersReceived_TaskCanceledQuickly](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681987&view=ms.vss-test-web.build-test-results-tab&runId=16928002&resultId=213537)||
|[681977](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681977)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.ReadAsStreamAsync_HandlerProducesWellBehavedResponseStream](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681977&view=ms.vss-test-web.build-test-results-tab&runId=16924226&resultId=215872)|dotnet/runtime#100951|
|[681837](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681837)|dotnet/runtime|[System.Net.Http.Functional.Tests.Http2ResponseStreamZeroByteReadTest.ZeroByteRead_BlocksUntilDataIsAvailable](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681837&view=ms.vss-test-web.build-test-results-tab&runId=16920408&resultId=211835)||
|[681508](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681508)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681508&view=ms.vss-test-web.build-test-results-tab&runId=16913688&resultId=219214)|dotnet/runtime#100951|
|[681252](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681252)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681252&view=ms.vss-test-web.build-test-results-tab&runId=16906730&resultId=104644)||
|[681245](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681245)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.PostAsyncDuplex_DisposeResponseBodyBeforeEnd_ResetsStreamAndThrowsOnRequestStreamWriteAndResponseStreamRead](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681245&view=ms.vss-test-web.build-test-results-tab&runId=16906654&resultId=104494)||
|[681226](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681226)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681226&view=ms.vss-test-web.build-test-results-tab&runId=16906622&resultId=104644)||
|[681186](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681186)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_ConnectionFrame_UpgradeFrom20_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681186&view=ms.vss-test-web.build-test-results-tab&runId=16905388&resultId=219129)|dotnet/runtime#100951|
|[680561](https://dev.azure.com/dnceng-public/public/_build/results?buildId=680561)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=680561&view=ms.vss-test-web.build-test-results-tab&runId=16880908&resultId=104299)||
|[680562](https://dev.azure.com/dnceng-public/public/_build/results?buildId=680562)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=680562&view=ms.vss-test-web.build-test-results-tab&runId=16881150&resultId=104650)||
|[680186](https://dev.azure.com/dnceng-public/public/_build/results?buildId=680186)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=680186&view=ms.vss-test-web.build-test-results-tab&runId=16868586&resultId=104650)||
|[680194](https://dev.azure.com/dnceng-public/public/_build/results?buildId=680194)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=680194&view=ms.vss-test-web.build-test-results-tab&runId=16868462&resultId=104644)||
|[679966](https://dev.azure.com/dnceng-public/public/_build/results?buildId=679966)|dotnet/runtime|[System.Net.Http.Functional.Tests.SyncHttpHandlerTest_Cookies.GetAsync_SetCookieContainer_CookieSent](https://dev.azure.com/dnceng-public/public/_build/results?buildId=679966&view=ms.vss-test-web.build-test-results-tab&runId=16864880&resultId=212529)||
|[679420](https://dev.azure.com/dnceng-public/public/_build/results?buildId=679420)|dotnet/runtime|[System.Net.Http.Functional.Tests.Http1MultiChunkResponseStreamZeroByteReadTest.ZeroByteRead_IssuesZeroByteReadOnUnderlyingStream](https://dev.azure.com/dnceng-public/public/_build/results?buildId=679420&view=ms.vss-test-web.build-test-results-tab&runId=16846488&resultId=212322)||
|[679370](https://dev.azure.com/dnceng-public/public/_build/results?buildId=679370)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_DiagnosticsTest_Http2.SendAsync_ActivityIsCreatedIfRequested](https://dev.azure.com/dnceng-public/public/_build/results?buildId=679370&view=ms.vss-test-web.build-test-results-tab&runId=16845338&resultId=219444)|dotnet/runtime#101814|
|[679003](https://dev.azure.com/dnceng-public/public/_build/results?buildId=679003)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=679003&view=ms.vss-test-web.build-test-results-tab&runId=16832064&resultId=104319)||
|[678721](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678721)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Headers_Http3.SendAsync_Expires_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678721&view=ms.vss-test-web.build-test-results-tab&runId=16826568&resultId=218810)||
|[678685](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678685)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Headers_Http3.SendAsync_Expires_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678685&view=ms.vss-test-web.build-test-results-tab&runId=16826066&resultId=218726)|dotnet/runtime#102362|
|[678603](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678603)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.ReadAsStreamAsync_HandlerProducesWellBehavedResponseStream](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678603&view=ms.vss-test-web.build-test-results-tab&runId=16824506&resultId=206582)|dotnet/runtime#102357|
|[678427](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678427)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.ReadAsStreamAsync_HandlerProducesWellBehavedResponseStream](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678427&view=ms.vss-test-web.build-test-results-tab&runId=16820686&resultId=217954)|dotnet/runtime#102351|
|[678355](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678355)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocksProxyTest_Http1_Async.TestLoopbackAsync](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678355&view=ms.vss-test-web.build-test-results-tab&runId=16816166&resultId=209929)||
|[678229](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678229)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_DiagnosticsTest_Http2.SendAsync_ActivityIsCreatedIfRequested](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678229&view=ms.vss-test-web.build-test-results-tab&runId=16813086&resultId=219272)|dotnet/runtime#101814|
|[677544](https://dev.azure.com/dnceng-public/public/_build/results?buildId=677544)|dotnet/runtime|[System.Net.Http.Functional.Tests.TelemetryTest_Http30.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue](https://dev.azure.com/dnceng-public/public/_build/results?buildId=677544&view=ms.vss-test-web.build-test-results-tab&runId=16794348&resultId=104644)||
|[677460](https://dev.azure.com/dnceng-public/public/_build/results?buildId=677460)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocksProxyTest_Http2.TestLoopbackAsync](https://dev.azure.com/dnceng-public/public/_build/results?buildId=677460&view=ms.vss-test-web.build-test-results-tab&runId=16792728&resultId=219789)|dotnet/runtime#102212|
|[676170](https://dev.azure.com/dnceng-public/public/_build/results?buildId=676170)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test_Http2.Expect100Continue_WaitsExpectedPeriodOfTimeBeforeSendingContent](https://dev.azure.com/dnceng-public/public/_build/results?buildId=676170&view=ms.vss-test-web.build-test-results-tab&runId=16762828&resultId=104488)||
|[675480](https://dev.azure.com/dnceng-public/public/_build/results?buildId=675480)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Finalization_Http2_Test.IncompleteResponseStream_ResponseDropped_CancelsRequestToServer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=675480&view=ms.vss-test-web.build-test-results-tab&runId=16747164&resultId=219667)|dotnet/runtime#101001|
|[675315](https://dev.azure.com/dnceng-public/public/_build/results?buildId=675315)|dotnet/runtime|[System.Net.Http.Functional.Tests.Http1MultiChunkResponseStreamZeroByteReadTest.ZeroByteRead_IssuesZeroByteReadOnUnderlyingStream](https://dev.azure.com/dnceng-public/public/_build/results?buildId=675315&view=ms.vss-test-web.build-test-results-tab&runId=16743704&resultId=219556)|dotnet/runtime#102181|
|[674799](https://dev.azure.com/dnceng-public/public/_build/results?buildId=674799)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=674799&view=ms.vss-test-web.build-test-results-tab&runId=16730022&resultId=219034)|dotnet/runtime#100951|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|3|58|

**Comment by carlossanlop** [comment] 2024-04-25 02:56
@dotnet/ncl can you please take a look at this failure? It has a very high impact.

**Comment by carlossanlop** [comment] 2024-04-25 15:20
Do you know if this is a duplicate of https://github.com/dotnet/runtime/issues/91757 ? They look kind of similar, but the ErrorMessage is grouping different failures.

**Comment by CarnaViire** [comment] 2024-04-25 20:04
> Do you know if this is a duplicate of https://github.com/dotnet/runtime/issues/91757 ?

Maybe, but hard to say 100%. We're investigating them together, but I'd still track them separately for the time being.

**Closed** 2024-06-13 11:20 UTC
Labels: area-System.Net.Http, blocking-clean-ci, Known Build Error
