### ISSUE TITLE
Assertion failed '(constIndexOffset % elemSize) == 0'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#67870] opened 2022-04-11 20:39 UTC
Test: JIT\Regression\JitBlue\Runtime_56953\Runtime_56953\Runtime_56953.cmd

`coreclr windows arm Checked @ Windows.10.Arm64v8.Open`

https://dev.azure.com/dnceng/public/_build/results?buildId=1710403&view=ms.vss-test-web.build-test-results-tab&runId=46520194&paneView=debug

```
    JIT\Regression\JitBlue\Runtime_56953\Runtime_56953\Runtime_56953.cmd [FAIL]
      
      Assert failure(PID 12276 [0x00002ff4], Thread: 15268 [0x3ba4]): Assertion failed '(constIndexOffset % elemSize) == 0' in 'System.Collections.Generic.Dictionary`2[__Canon,__Canon][System.__Canon,System.__Canon]:TryInsert(System.__Canon,System.__Canon,ubyte):bool:this' during 'Do value numbering' (IL size 739; hash 0x0b956994; Tier1)
      
          File: D:\a\_work\1\s\src\coreclr\jit\gentree.cpp Line: 17355
          Image: D:\h\w\A48D0941\p\corerun.exe
      
      
      Return code:      1
      Raw output file:      D:\h\w\A48D0941\w\AB94092C\uploads\Reports\JIT.Regression\JitBlue\Runtime_56953\Runtime_56953\Runtime_56953.output.txt
      Raw output:
      BEGIN EXECUTION
       "D:\h\w\A48D0941\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  Runtime_56953.dll 
      Expected: 100
      Actual: -1073740286
      END EXECUTION - FAILED
      FAILED
```

@dotnet/jit-contrib 

category:correctness
theme:value-numbering
skill-level:intermediate
cost:small
impact:small

**Comment by kunalspathak** [comment] 2022-04-11 21:17
Hit this on Antigen run as well.

```c#
// Found by Antigen
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
public class TestClass
{
    public struct S1
    {
    }
    public struct S2
    {
        public struct S2_D1_F1
        {
            public uint uint_1;
        }
    }
    static short s_short_8 = -2;
    static int s_int_9 = 2;
    static sbyte s_sbyte_11 = 5;
    static string s_string_13 = "1DW3N";
    static ushort s_ushort_14 = 5;
    static uint s_uint_15 = 83;
    static S2.S2_D1_F1 s_s2_s2_d1_f1_18 = new S2.S2_D1_F1();
    int int_26 = 2147483647;
    sbyte sbyte_28 = -2;
    ulong ulong_33 = 2;
    S1 s1_34 = new S1();
    [MethodImpl(MethodImplOptions.NoInlining)]
    public int LeafMethod6()
    {
        unchecked
        {
            return 15^4+ (s_int_9 += int_26 %= int_26+ 43* (int_26 -= s_int_9));
        }
    }
    [MethodImpl(MethodImplOptions.NoInlining)]
    public sbyte LeafMethod8()
    {
        unchecked
        {
            return sbyte_28 <<= (s_int_9 /= 15+4)- (s_sbyte_11 >>= 15^4^ s_int_9 - LeafMethod6());
        }
    }
    public sbyte Method2(out S1 p_s1_60, out S1 p_s1_61, out ulong p_ulong_62, ulong p_ulong_63, sbyte p_sbyte_64, ushort p_ushort_65, out uint p_uint_66)
    {
        unchecked
        {
            p_ulong_62 = ulong_33;
            p_uint_66 = s_s2_s2_d1_f1_18.uint_1 <<= (s_int_9 ^= LeafMethod6())| 15*4;
            return (sbyte)(LeafMethod8() | 15+4);
        }
    }
    public short Method3(ushort p_ushort_84, ref string p_string_85, float p_float_86)
    {
        unchecked
        {
            sbyte sbyte_95 = 6;
            ulong ulong_100 = 5;
            if (15<4)
            {
            }
            else
            {
                s_sbyte_11 &= (sbyte)(Method2(out s1_34, out s1_34, out ulong_100, 15+4, (sbyte)(LeafMethod8() - sbyte_95), 15+4, out s_uint_15) | 15+4);
            }
            return 15+4;
        }
    }
    public void Method0()
    {
        unchecked
        {
            s_short_8 = Method3(s_ushort_14, ref s_string_13, 15%4);
            return;
        }
    }
    public static void Main(string[] args)
    {
        new TestClass().Method0();
    }
}
/*
--------- Test ---------  

Environment:

set COMPlus_JitOptRepeat=*
set COMPlus_AltJitName=clrjit_universal_arm64_x64.dll
set COMPlus_AltJit=CalculateMetadataLocation

Unhandled exception. 
Assert failure(PID 366276 [0x000596c4], Thread: 36932 [0x9044]): Assertion failed '(constIndexOffset % elemSize) == 0' in 'System.Reflection.PortableExecutable.PEHeaders:CalculateMetadataLocation(long,byref,byref):this' during 'Do value numbering' (IL size 249; hash 0x5b6a880a; FullOpts)
    File: D:\git\runtime\src\coreclr\jit\gentree.cpp Line: 17355
    Image: D:\git\runtime\artifacts\tests\coreclr\windows.x64.Checked\tests\Core_Root\CoreRun.exe
*/

```

**Comment by JulieLeeMSFT** [comment] 2022-05-02 20:15
@SingleAccretion did you have a chance to look at this issue yet?
@jakobbotsch please disable this test until it is resolved.

**Comment by jakobbotsch** [comment] 2022-05-02 20:29
@JulieLeeMSFT Looks like it already was disabled by #67978.

**Comment by SingleAccretion** [comment] 2022-05-02 20:39
> did you have a chance to look at this issue yet?

Not yet.

For some context, we have had an identical issue for quite some time: #57856, and the root cause is that we try to deconstruct the IR to get to the index, which tends to break down when `OptRepeat` (aka CSE) gets involved, or some less common IR shapes (which I suspect is the case here) are involved. The fix is to deconstruct VNs instead.

**Comment by BruceForstall** [comment] 2022-06-05 15:51
@SingleAccretion You re-enabled this test with https://github.com/dotnet/runtime/pull/70237

Now it is failing in jitstress on arm64: https://dev.azure.com/dnceng/public/_build/results?buildId=1807505&view=ms.vss-test-web.build-test-results-tab

**Comment by JulieLeeMSFT** [comment] 2023-08-02 23:11
@AndyAyersMS PTAL if we need to enable this test in .NET 8.

**Comment by AndyAyersMS** [comment] 2023-08-03 02:46
Moving this back to 8.0 for now so I don't forget about it.

**Comment by AndyAyersMS** [comment] 2023-08-04 01:46
Ah, this is windows arm and JitOptRepeat, so will move it back out of 8.0.

**Comment by BruceForstall** [comment] 2023-10-17 00:26
I'll take this one.

**Comment by amanasifkhalid** [comment] 2024-05-08 21:46
This test was re-enabled by #100717. Looks like Bruce's `JitOptRepeat` work fixed this failure.

**Closed by amanasifkhalid** 2024-05-08 21:46 UTC
Labels: disabled-test, area-CodeGen-coreclr
