### ISSUE TITLE
[Feature Request]: Only include packages when not provided by the framework

### ISSUE THREAD

**Issue by thompson-tomo** [dotnet/runtime#97937] opened 2024-02-04 08:30 UTC
### Summary
I want System.Reflection.MetadataLoadContext to use framwork libraries wherever possible

### Proposal
If the TFM's provide's a dependency then there is no need for it to be explicitly included which means on the new frameworks there will be no dependencies. 

Note the packages are

- System.Collections.Immutable
- System.Reflection.Metadata

**Comment by huoyaoyuan** [comment] 2024-02-04 11:20
Duplicate of #95626. See the comment https://github.com/dotnet/runtime/issues/95626#issuecomment-1844876479 for the reason.

**Comment by thompson-tomo** [comment] 2024-02-04 11:39
@huoyaoyuan It would be interesting to understand where the line is drawn as to when framework is used as opposed to explicit. In the case of the mentioned Package, there has only been 1 stable release for each of net 5, 6, 7 & now 8.

Hence the idea of being more up to date doesn't apply in this case. It would be fine for me if net 8 didn't have the dependency but all other TFM had the dependency bringing those frameworks up to v8 of the package.

**Comment by huoyaoyuan** [comment] 2024-02-05 07:39
The package on NuGet may have higher patches than framework-provided assembly. We want to give user highest patches possible.

**Comment by thompson-tomo** [comment] 2024-02-05 08:14
I looked at System.Reflection.MetadataLoadContext and there has not been a patch for net 5, 6, 7 or 8 hence proposal is that it is not be included as a dependency for net 8 but others it is.

**Closed** 2024-02-07 21:07 UTC
Labels: area-System.Reflection.Metadata, untriaged
