### ISSUE TITLE
[API Proposal]: remove dependency on System.Drawing.Common from System.Windows.Extensions

### ISSUE THREAD

**Issue by abelykh0** [dotnet/runtime#62649] opened 2021-12-10 19:08 UTC
### Background and motivation

.Net 6 introduced a breaking change in the Windows compatibility (see https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only). The motivation is to make the libraries, like the following to not depend on the "not recommended" GDI+ library `System.Drawing.Common`:
System.Windows.Extensions
System.Security.Permissions
System.Configuration.ConfigurationManager
System.Runtime.Caching
etc

### API Proposal

Since so many commonly used packages depend on `System.Windows.Extensions`, such as `System.Security.Permissions`, `System.Runtime.Caching`, and even packages like `System.Security.Cryptography` and `Microsoft.SqlServer.DacFx`, it would be beneficial to remove dependency on the "not recommended" library `System.Drawing.Common` from `System.Windows.Extensions`.

### API Usage

N/A

### Alternative Designs

Maybe split  `System.Drawing.Common` into "common" and "GDI+"?

### Risks

Backward compatibility

**Comment by safern** [comment] 2021-12-10 20:54
IMHO we shouldn't do this. The compatibility pack was mostly added in order to bring compat in between .NET Framework and .NET Core, so that more apps could move to .NET Core in an easier way and it includes libraries that are only supported on Windows and that throw on non-Windows platforms/mobile platforms. I don't think the deprecation of System.Drawing.Common on non-Windows should change the meaning of the Compatibility pack and we should be giving users feedback on what is supported on which platform via the OSSupported/Unsupported attributes.

@ericstj thoughts?

**Comment by abelykh0** [comment] 2021-12-10 21:34
> IMHO we shouldn't do this. The compatibility pack was mostly added in order to bring compat in between .NET Framework and .NET Core, so that more apps could move to .NET Core in an easier way and it includes libraries that are only supported on Windows and that throw on non-Windows platforms/mobile platforms. I don't think the deprecation of System.Drawing.Common on non-Windows should change the meaning of the Compatibility pack and we should be giving users feedback on what is supported on which platform via the OSSupported/Unsupported attributes.
> 
> @ericstj thoughts?

That is OK with me as long as the libraries such as `System.Runtime.Caching` will no longer require dependency on ` System.Drawing.Common`.

**Comment by teo-tsirpanis** [comment] 2021-12-10 22:53
@abelykh0 if you don't want to reference `System.Drawing.Common` you can either directly reference the packages you want such as `System.Runtime.Caching`, or just ignore `System.Drawing.Common`'s existence. The platform compatibility analyzer will inform you if you use a Windows-only component on a cross-platform project, and if you care about your application's deployed size you can ask the trimmer to remove `System.Drawing.Common`.

**Comment by abelykh0** [comment] 2021-12-10 23:18
> @abelykh0 if you don't want to reference `System.Drawing.Common` you can either directly reference the packages you want such as `System.Runtime.Caching`, or just ignore `System.Drawing.Common`'s existence. The platform compatibility analyzer will inform you if you use a Windows-only component on a cross-platform project, and if you care about your application's deployed size you can ask the trimmer to remove `System.Drawing.Common`.

I would like to use older version of the `System.Drawing.Common` (version 4.7.3) and also `System.Runtime.Caching` version 6.0.0. Please let me know how to do this. Right now I am getting this in Visual Studio:

```
NU1605: Detected package downgrade: System.Drawing.Common from 6.0.0 to 4.7.3. Reference the package directly from the project to select a different version. 
... -> System.Runtime.Caching 6.0.0 -> System.Configuration.ConfigurationManager 6.0.0 -> System.Security.Permissions 6.0.0 -> System.Windows.Extensions 6.0.0 -> System.Drawing.Common (>= 6.0.0) 
... -> System.Drawing.Common (>= 4.7.3)
```

**Comment by abelykh0** [comment] 2021-12-10 23:24
> ...The platform compatibility analyzer will inform you if you use a Windows-only component on a cross-platform project...
By the way, this didn't happen, only happens during runtime.

**Comment by teo-tsirpanis** [comment] 2021-12-10 23:26
That seems to me as a bug. `System.Windows.Extensions` does not actually use `System.Drawing.Common`.

I will prepare a pull request. In the meantime, I think it is safe to ignore the warning.

**Comment by abelykh0** [comment] 2021-12-10 23:31
> That seems to me as a bug. `System.Windows.Extensions` does not actually use `System.Drawing.Common`.
> 
> I will prepare a pull request. In the meantime, I think it is safe to ignore the warning.

Thanks! Good news.

**Comment by abelykh0** [comment] 2021-12-10 23:32
By the way, which repository should I use to report lack of warning for compatibility analyzer not informing if I used a Windows-only component on a cross-platform project?

**Comment by teo-tsirpanis** [comment] 2021-12-10 23:34
I don't know, S.D.C is annotated. Are you targeting .NET 5+? Otherwise you can take a look at https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1416#configure-code-to-analyze.

**Comment by abelykh0** [comment] 2021-12-10 23:44
> ~I don't know, S.D.C is annotated. Are you targeting .NET 5+? Otherwise you can take a look at https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1416#configure-code-to-analyze.~
> 
> Oh wait, you are using an old version, that's why it doesn't warn you.

OK, I see. Thanks!

**Comment by teo-tsirpanis** [comment] 2021-12-10 23:46
> `System.Windows.Extensions` does not actually use `System.Drawing.Common`.

Wait, it actually uses it but only for some type forwardings. Ignoring the warning is still safe though.

BTW, why do you want to use that version of `System.Drawing.Common`? [You can still use the latest version on Unix, with an AppContext switch.](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only)

**Comment by abelykh0** [comment] 2021-12-10 23:50
> > `System.Windows.Extensions` does not actually use `System.Drawing.Common`.
> 
> Wait, it actually uses it but only for some type forwardings. Ignoring the warning is still safe though.
> 
> BTW, why do you want to use that version of `System.Drawing.Common`? [You can still use the latest version on Unix, with ~an AppContext~ a runtime configuration switch.](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only)

It doesn't work in all cases.

**Comment by abelykh0** [comment] 2021-12-10 23:52
It is not easy to "ignore the warning" as the UI doesn't let me change the reference. If you want, I can convert this to a bug "System.Windows.Extensions does not actually use System.Drawing.Common."

**Comment by abelykh0** [comment] 2021-12-10 23:56
Also, for my specific case it would be fine if you let using the old version, not sure if it goes well with your coding policies. Like:
```
-> System.Runtime.Caching 6.0.0 
-> System.Configuration.ConfigurationManager 6.0.0 
-> System.Security.Permissions 6.0.0 
-> System.Windows.Extensions 6.0.0 
-> System.Drawing.Common (>= 4.7.3)
```

**Comment by safern** [comment] 2021-12-10 23:59
@ericstj I wonder how breaking it would be to remove this dependency, it would mean removing the typeforwards that we added when we moved the types down? 

I know we would loose type unification and customers that use Sytem.Drawing.Common via this dependency would be broken if they bump any of this package versions, but I wonder if it is OK to do to avoid having any dependencies on our packages to System.Drawing.Common to let people downgrade the package if they still want to use the linux implementation (which is not recommended and we would be encouraging to do so).

**Comment by abelykh0** [comment] 2021-12-11 00:03
> @ericstj I wonder how breaking it would be to remove this dependency, it would mean removing the typeforwards that we added when we moved the types down?
> 
> I know we would loose type unification and customers that use Sytem.Drawing.Common via this dependency would be broken if they bump any of this package versions, but I wonder if it is OK to do to avoid having any dependencies on our packages to System.Drawing.Common to let people downgrade the package if they still want to use the linux implementation (which is not recommended and we would be encouraging to do so).

Exactly, why do you force using "not recommended" `System.Drawing.Common` in case if I reference `System.Runtime.Caching`?

**Comment by teo-tsirpanis** [comment] 2021-12-11 00:04
@abelykh0 it is done for some unfortunate compatibility reasons.

**Comment by abelykh0** [comment] 2021-12-11 00:08
> @abelykh0 it is done for some unfortunate compatibility reasons.

I understand. Then maybe it would be possible to turn on the "runtime configuration switch" for the `System.Drawing.Common` programmatically? We have dynamic DLLs and it makes the "runtime configuration switch" hard to use.

**Comment by teo-tsirpanis** [comment] 2021-12-11 00:11
Another solution would be to actually support `TypeForwardedFromAttribute` from the runtime. Unless it is outdated, https://www.red-gate.com/simple-talk/blogs/anatomy-of-a-net-assembly-type-forwards/ says that:

> However, unlike `TypeForwardedTo`, [`TypeForwardedFrom`] is a normal attribute, has no effect on CLR type resolution, and exists primarily for bookkeeping purposes.

Implementing it though might be complicated since the loader will have to do some more searching if it fails to find a type.

@abelykh0 what do you mean by "dynamic DLLs"? If your product is a library you can instruct its users to turn the runtime configuration switch on.

**Comment by abelykh0** [comment] 2021-12-11 00:12
> Another solution would be to actually support `TypeForwardedFromAttribute` from the runtime. Unless it is outdated, https://www.red-gate.com/simple-talk/blogs/anatomy-of-a-net-assembly-type-forwards/ says that:
> 
> > However, unlike `TypeForwardedTo`, [`TypeForwardedFrom`] is a normal attribute, has no effect on CLR type resolution, and exists primarily for bookkeeping purposes.
> 
> Implementing it though might be complicated since the loader will have to do some more searching if it fails to find a type.
> 
> @abelykh0 what do you mean by "dynamic DLLs"? If your product is a library you can instruct its users to turn the runtime configuration switch on.

Something like that https://docs.microsoft.com/en-us/dotnet/api/system.appcontext?view=net-6.0

**Comment by abelykh0** [comment] 2021-12-11 00:14
> Another solution would be to actually support `TypeForwardedFromAttribute` from the runtime. Unless it is outdated, https://www.red-gate.com/simple-talk/blogs/anatomy-of-a-net-assembly-type-forwards/ says that:
> 
> > However, unlike `TypeForwardedTo`, [`TypeForwardedFrom`] is a normal attribute, has no effect on CLR type resolution, and exists primarily for bookkeeping purposes.
> 
> Implementing it though might be complicated since the loader will have to do some more searching if it fails to find a type.
> 
> @abelykh0 what do you mean by "dynamic DLLs"? If your product is a library you can instruct its users to turn the runtime configuration switch on.

I am assuming that this is a first step before this library will be obsoleted, so I would like a long term solution.

**Comment by teo-tsirpanis** [comment] 2021-12-11 00:19
Why aren't you using an older version of `System.Runtime.Caching` as well?

**Comment by abelykh0** [comment] 2021-12-11 00:26
> Why aren't you using an older version of `System.Runtime.Caching` as well?

It is an option.

**Comment by teo-tsirpanis** [comment] 2021-12-11 00:31
You already took the option of using an older version of S.D.C,  you see that the package dependency resolver is having trouble doing exactly what you told it to do, and it looks like that your problem is unlikely to be fixed without breaking (probably few) customers.

Was there any new API introduced in `System.Runtime.Caching` 6.0.0, or perhaps a performance improvement that made you prefer the latest version only there?

**Comment by abelykh0** [comment] 2021-12-11 00:47
> You already took the option of using an older version of S.D.C, you see that the package dependency resolver is having trouble doing exactly what you told it to do, and it looks like that your problem is unlikely to be fixed without breaking (probably few) customers.
> 
> Was there any new API introduced in `System.Runtime.Caching` 6.0.0, or perhaps a performance improvement that made you prefer the latest version only there?

Not at the moment. It looks like we will probably downgrade the `System.Runtime.Caching` as a "band-aid" solution for now. Long term will need to work on moving to a different library on Linux anyway.

**Comment by abelykh0** [comment] 2021-12-11 01:33
I changed the title. Since so many things depend on `System.Windows.Extensions`, like `System.Security.Permissions`, `System.Runtime.Caching`, and even packages like `Microsoft.SqlServer.DacFx`, it would be beneficial to remove dependency on the "not recommended" library `System.Drawing.Common`.

**Comment by teo-tsirpanis** [comment] 2022-01-03 13:52
I got another idea: what if we reference packages we only need for type forwards with `PrivateAssets="all"`? Would the existing runtime(s) have a problem with encountering type forwards to an assembly they cannot resolve?

**Comment by ericstj** [comment] 2022-01-03 15:37
I would expect System.Windows.Extensions and System.Drawing.Common to be in the same state: supported on windows and discouraged elsewhere. I would expect cross platform assemblies to avoid exposing these types in surface area. Dependencies on them could be made private if that was the case.

Since these are similarly supported I don’t see any reason to do anything to break the dependency between them.

**Comment by safern** [comment] 2022-01-03 16:25
Agreed with @ericstj, I will go ahead and close the issue as by design as the dependency to System.Drawing.Common is from a Windows only package. Thanks for the request and let us know if you have any other questions/suggestions.

**Closed by safern** 2022-01-03 16:25 UTC
Labels: api-suggestion, area-System.Drawing, untriaged

**Comment by teo-tsirpanis** [comment] 2022-01-03 16:38
> Dependencies on them could be made private if that was the case.

What does that mean? Should we go forward with my idea? If that's the case I think the issue should stay open to track it.

**Comment by ericstj** [comment] 2022-01-04 17:01
If you desire to "hide" your dependency on `System.Drawing.Common` and `System.Windows.Extensions` you can make that dependency `PrivateAssets="Compile"` this will make it so the package is restored and made present for your library at runtime but your package would not expose that package to others who are consuming your package.  That behavior is transitive, so it applies to all packages included in the graph.  It has no effect if some other package outside your own reference graph brought that in without specifying private assets.
https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets

You should only do this if you do not expose API from those dependencies.  If you did, excluding them from compile assets would introduce compiler errors when consumers tried to use those APIs.

**Comment by abelykh0** [comment] 2022-01-05 21:37
Please re-open if there's something that could be done for this (like `PrivateAssets="all"`).

**Comment by ericstj** [comment] 2022-01-31 23:05
No, we cannot make that change.  Surface area that's part of the reference contract of System.Windows.Extensions is part of System.Drawing.Common.  They're also both supported on Windows.  There's no change to make here.  The recommendation was for up-stack consumers to hide the dependency if they don't want to expose it themselves.

**Comment by abelykh0** [comment] 2022-02-01 02:38
OK, trying again with https://github.com/dotnet/runtime/issues/64592. Thanks!
