### ISSUE TITLE
[API Proposal]: Extend System.Net.Mime.MediaTypeNames

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#78458] opened 2022-11-16 12:20 UTC
### Background and motivation

Currently MediaTypeNames contains a small-but-commonly-used list that was created circa 2018.

Throughout the dotnet/runtime repo, a number of other common media types have emerged.  These should be added to MediaTypeNames and the affected code refactored to take advantage of the additional values.

The following should be added:
```
MediaTypeNames.Any = */*

MediaTypeNames.Application.Grpc = application/grpc
MediaTypeNames.Application.Javascript = application/javascript
MediaTypeNames.Application.FormUrlEncoded = application/x-www-form-urlencoded
MediaTypeNames.Application.Wasm = application/wasm

MediaTypeNames.Image.Png = image/png

MediaTypeNames.Text.Css = text/css
```

### API Proposal

See Above

### API Usage

See Above

### Alternative Designs

It could just be left as-is, although this refactoring would clean things up in a lot of places.

### Risks

None.

**Comment by MSDN-WhiteKnight** [comment] 2022-11-20 17:03
Duplicate of https://github.com/dotnet/runtime/issues/1489

**Comment by MihaZupan** [comment] 2022-11-20 21:11
Duplicate of #1489

As far as I can tell, `application/wasm` and `application/grpc` are ones that haven't been mentioned in that issue thus far.

**Closed by MihaZupan** 2022-11-20 21:11 UTC
Labels: api-suggestion, area-System.Net, untriaged
