### ISSUE TITLE
Substitute of obsolete 'JsonSerializerOptions.IgnoreNullValues' about Deserialization of json property with null value

### ISSUE THREAD

**Issue by lateapexearlyspeed** [dotnet/runtime#90007] opened 2023-08-04 09:50 UTC
Previous `JsonSerializerOptions.IgnoreNullValues` handles not only serialization but also deserialization part, so that if there is json property with null value, deserializer will "ignore" null token rather than set value of null to object's property. So what is the substitute for obsolete `JsonSerializerOptions.IgnoreNullValues` for this null value deserialization case ? Thanks !

Model:
```csharp
        public class TestBody
        {
            public string? A { get; set; } = "initialValue";
        }
```

No json property case is as following, so that deserializer will do nothing for property thus not impact initial value as expected:
```csharp
            string json = @"{}";
            TestBody? testBody = JsonSerializer.Deserialize<TestBody>(json);
            // testBody.A = "initialValue";
```

Let's say there is json property with null token:

Previously we can use `JsonSerializerOptions.IgnoreNullValues` to tell don't set value for null during deserialization:
```csharp
            string json = @"{""A"": null}";
            TestBody? testBody = JsonSerializer.Deserialize<TestBody>(json, new JsonSerializerOptions { IgnoreNullValues = true });
            // testBody.A = "initialValue";
```

Now how to configure to do that without `JsonSerializerOptions.IgnoreNullValues` ? Seems as its name describes, `JsonIgnoreCondition.WhenWritingNull` handles serialization only ?
```csharp
            string json = @"{""A"": null}";
            TestBody? testBody = JsonSerializer.Deserialize<TestBody>(json, new JsonSerializerOptions { DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull });
            // testBody.A = null;
```

**Comment by eiriktsarpalis** [comment] 2023-08-04 11:22
Closing as duplicate of https://github.com/dotnet/runtime/issues/83706.

**Closed by eiriktsarpalis** 2023-08-04 11:22 UTC
Labels: area-System.Text.Json, untriaged
