### ISSUE TITLE
Why don't `DateTime` and `TimeSpan` implement the new "numeric" interfaces in C# 11/.NET 7?

### ISSUE THREAD

**Issue by aradalvand** [dotnet/runtime#78740] opened 2022-11-23 00:32 UTC
I'm not sure if this is the right repo to post this in, so let me know if it isn't.

As soon as I heard about static member (and by extension operator overloads) for interfaces (i.e. generic math) coming to C# 11, and in the introduction of things like `IComparisonOperators`, `IEqualityOperators`, `IAdditionOperators`, etc., I automatically assumed that built-in types like `DateTime` and `TimeSpan` that have always supported these "numeric" operators, would also start implementing these interfaces, and also LINQ methods like `Sum` would start to operate on `IAdditiveIdentity` or whatnot instead of individual numeric types (`int`, `byte`, etc.).

But I just started actually playing with .NET 7/C# 11 and found out that this isn't the case. `TimeSpan`, for example, doesn't implement `IAdditionOperators` even though it does have overloads for addition operators, etc.

I'm very, very surprised by this and I couldn't find any relevant information on the matter, any explanation as to why these weren't done.

I'd appreciate it if somebody enlightens me here. Thanks.

**Comment by huoyaoyuan** [comment] 2022-11-23 07:09
See the discussion in #76225

**Comment by dakersnar** [comment] 2022-11-28 20:30
Closing this as a duplicate of the above linked issue. Feel free to add your thoughts to that thread.

**Closed by dakersnar** 2022-11-28 20:30 UTC
Labels: area-System.Numerics, untriaged
