### ISSUE TITLE
System.Text.Json source generators don't preserve nullability of object types in JsonSerializable attributes

### ISSUE THREAD

**Issue by jevansaks** [dotnet/runtime#97665] opened 2024-01-29 19:57 UTC
### Description

Using JsonSerializer.Serialize methods that are AOT-friendly requires getting JsonTypeInfos that match the types you're serializing. The source generators do a good job of this except for when there are templated types whose template parameters are nullable, e.g. `List<string?>`.

### Reproduction Steps

This fails to compile because ListString is `List<string>`, not `List<string?>`.

```c#
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;

var list = new List<string?>() { "a", "b", null };
var x = JsonSerializer.Serialize(list, Repro.Default.String); // This fails to compile
var y = JsonSerializer.Serialize(list, Repro.Default.Options); // This works, but generates an AOT warning that would need to be suppressed.

Console.WriteLine(y);

[JsonSerializable(typeof(List<string?>))]
public partial class Repro : JsonSerializerContext;
```

### Expected behavior

Expected: Correct JsonTypeInfo<T> type for the nullable types.

### Actual behavior

Actual: Compile error with type mismatch.

### Regression?

Not a regression.

### Known Workarounds

Workaround is in the repro: You can call the AOT-unsafe versions of Serialize and then suppress the warnings. It seems that the generated JsonTypeInfo is perfectly suitable for serialization, it just doesn't have the right type.

**Comment by eiriktsarpalis** [comment] 2024-01-29 22:03
Duplicate of https://github.com/dotnet/runtime/issues/95083. The generator in .NET 9 has been updated to generate nullable-oblivious `JsonTypeInfo` properties, but it doesn't meet the bar for a .NET 8 backport. The workaround is to apply a suppression in callsites where nullability annotations don't match the serialized value.

**Closed by eiriktsarpalis** 2024-01-29 22:03 UTC
Labels: area-System.Text.Json, untriaged

**Comment by gregsdennis** [comment] 2024-01-29 22:58
> The workaround is to apply a suppression in callsites where nullability annotations don't match the serialized value. - @eiriktsarpalis 

@jevansaks is reporting that this is a build failure, not a warning.

**Comment by eiriktsarpalis** [comment] 2024-01-29 23:25
It probably means that the project has been configured to report warnings as errors. It can be suppressed by adding a `!` suffix at the end of the JsonTypeInfo expression.

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/null-forgiving

**Comment by eiriktsarpalis** [comment] 2024-01-29 23:26
So, in this particular case, ` JsonSerializer.Serialize(list, Repro.Default.String!);` resolves the issue.

**Comment by jevansaks** [comment] 2024-01-29 23:41
I tried that, and a simple ! did not address it. I still got the same error:
```
Program.cs(6,34,6,38): warning CS8620: Argument of type 'List<string?>' cannot be used for parameter 'value' of type 'List<string>' in 'string JsonSerializer.Serialize<List<string>>(List<string> value, JsonTypeInfo<List<string>> jsonTypeInfo)' due to differences in the nullability of reference types.
```

**Comment by jevansaks** [comment] 2024-01-29 23:42
If I put `#nullable disable` around it, that works, but is sketchy:
```
#nullable disable
var x = JsonSerializer.Serialize(list, Repro.Default.ListString); // This fails to compile
#nullable restore
```

**Comment by eiriktsarpalis** [comment] 2024-01-30 00:08
This is what happens when you propose solutions without trying them first :-) The bang should be appended to the impacted sub-expression, so in this case `list`. This should work:
```C#
JsonSerializer.Serialize(list!, Reproduction.Default.ListString);
```

**Comment by jevansaks** [comment] 2024-01-30 01:40
Thanks! That seems like a reasonable workaround.
