### ISSUE TITLE
We should be able serialize and deserialize from DOM

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#31274] opened 2019-10-23 18:53 UTC
Consider this coding snippet of JSON.NET [outlined](https://medium.com/cloudnimble/switching-to-system-text-json-in-net-core-3-0-not-so-fast-4c577a21298b) by @robertmclaws:

```C#
public async Task<bool> SomeMethod([FromBody] JObject data)
{
    var model = data.ToObject<SomeObject>();
}
```

Today, you can't do this with `System.Text.Json`. I propose we add APIs so that you can write this:

```C#
public async Task<bool> SomeMethod([FromBody] JsonElement data)
{
    var model = data.Deserialize<SomeObject>();
}
```

### API Proposal

```diff
namespace System.Text.Json
{
    public static partial class JsonSerializer
    {
+    public static TValue? Deserialize<TValue>(this JsonDocument document, JsonSerializerOptions? options = null);
+    public static object? Deserialize(this JsonDocument document, Type returnType, JsonSerializerOptions? options = null);
+    public static TValue? Deserialize<TValue>(this JsonDocument document, JsonTypeInfo<TValue> jsonTypeInfo);
+    public static object? Deserialize(this JsonDocument document, Type returnType, JsonSerializerContext context);

+    public static JsonDocument SerializeToDocument<TValue>(TValue value, JsonSerializerOptions? options = null);
+    public static JsonDocument SerializeToDocument(object? value, Type inputType, JsonSerializerOptions? options = null);
+    public static JsonDocument SerializeToDocument<TValue>(TValue value, JsonTypeInfo<TValue> jsonTypeInfo);
+    public static JsonDocument SerializeToDocument(object? value, Type inputType, JsonSerializerContext context);

+    public static TValue? Deserialize<TValue>(this JsonElement element, JsonSerializerOptions? options = null);
+    public static TValue? Deserialize<TValue>(this JsonElement element, JsonTypeInfo<TValue> jsonTypeInfo);
+    public static object? Deserialize(this JsonElement element, Type returnType, JsonSerializerOptions? options = null);
+    public static object? Deserialize(this JsonElement element, Type returnType, JsonSerializerContext context);

+    public static JsonElement SerializeToElement<TValue>(TValue value, JsonSerializerOptions? options = null);
+    public static JsonElement SerializeToElement(object? value, Type inputType, JsonSerializerOptions? options = null);
+    public static JsonElement SerializeToElement<TValue>(TValue value, JsonTypeInfo<TValue> jsonTypeInfo);
+    public static JsonElement SerializeToElement(object? value, Type inputType, JsonSerializerContext context);

+    public static TValue? Deserialize<TValue>(this JsonNode node, JsonSerializerOptions? options = null);
+    public static TValue? Deserialize<TValue>(this JsonNode node, JsonTypeInfo<TValue> jsonTypeInfo);
+    public static object? Deserialize(this JsonNode node, Type returnType, JsonSerializerOptions? options = null);
+    public static object? Deserialize(this JsonNode node, Type returnType, JsonSerializerContext context);

+    public static JsonNode? SerializeToNode<TValue>(TValue value, JsonSerializerOptions? options = null);
+    public static JsonNode? SerializeToNode(object? value, Type inputType, JsonSerializerOptions? options = null);
+    public static JsonNode? SerializeToNode<TValue>(TValue value, JsonTypeInfo<TValue> jsonTypeInfo);
+    public static JsonNode? SerializeToNode(object? value, Type inputType, JsonSerializerContext context);
    }
}
```

**Comment by robertmclaws** [comment] 2020-06-07 20:03
Any progress on this? Just ran into the issue again in one of my projects. Thanks!

**Comment by NoRelect** [comment] 2020-06-28 21:03
I propose to not only have the generics variant, but also one where the `Type` can be specified as a parameter, so use-cases involving reflection are covered as well. The new API would look like this (Also added the suggestion of @bjornen77):

### API Proposal

```cs
namespace System.Text.Json
{
    public static partial class JsonSerializer
    {
        public static TValue Deserialize<TValue>(this JsonDocument document);
        public static object Deserialize(this JsonDocument document, Type valueType);
        public static TValue Deserialize<TValue>(this JsonElement element);
        public static object Deserialize(this JsonElement element, Type valueType);

        public static JsonDocument SerializeToDocument<TValue>(TValue value);
        public static JsonDocument SerializeToDocument(object value, Type valueType);
        public static JsonElement SerializeToElement<TValue>(TValue value);
        public static JsonElement SerializeToElement(object value, Type valueType);
    }
}
```

**Comment by cluetjen** [comment] 2020-09-29 19:33
There should be an overload that allows us to pass in serializer options, e.g. custom converters.

**Comment by steveharter** [comment] 2021-02-22 16:01
The proposal should also pass `JsonSerializerOptions` as an optional parametes in order to pick up any custom converters added at runtime as well as other options such as null handling.

**Comment by wizofaus** [comment] 2021-03-03 03:12
Would also like this feature, currently using the GetRawText() hack.

**Comment by thepirat000** [comment] 2021-03-03 06:21
> Would also like this feature, currently using the GetRawText() hack.

what's the GetRawText() hack?

**Comment by wizofaus** [comment] 2021-03-03 10:14
`JsonSerializer.Deserialize<SomeObject>(element.GetRawText())`

**Comment by stonstad** [comment] 2021-03-03 21:13
Doing the same hack as described above.  Using System.Text.Json in a high throughput/performance system and it is painful having to use this hack.

**Comment by udlose** [comment] 2021-03-22 20:08
it would be nice if this had `async` versions as well

**Comment by udlose** [comment] 2021-03-22 20:10
Here is what I'm using in the meantime:

```
public static class JsonElementExtensions
{
    public static async Task<T> ToObjectAsync<T>(this JsonElement element, JsonSerializerOptions options = null,
        CancellationToken token = default)
    {
        var bufferWriter = new ArrayBufferWriter<byte>();
        await using var writer = new Utf8JsonWriter(bufferWriter);
        element.WriteTo(writer);
        
        // NOTE: call Flush on the writer before Deserializing since Dispose is called at the end of the scope of the method
        await writer.FlushAsync(token);
        
        return JsonSerializer.Deserialize<T>(bufferWriter.WrittenSpan, options);
    }

    public static async Task<T> ToObjectAsync<T>(this JsonDocument document, JsonSerializerOptions options = null,
        CancellationToken token = default)
    {
        if (document == null) throw new ArgumentNullException(nameof(document));

        return await document.RootElement.ToObjectAsync<T>(options, token: token);
    }
}
```

**Comment by ericstj** [comment] 2021-04-22 23:24
@steveharter did this get added with our DOM/dynamic feature or not yet?

**Comment by steveharter** [comment] 2021-07-08 17:14
These are mostly small extensions; I'll add samples here for now. There are many permutations to consider (to\from object, JsonElement, JsonDocument, JsonNode*) and different programming models to consider (i.e. whether to add to `JsonSerializer` as static methods, or add as instance methods to `JsonElement`, `JsonNode`, etc)

**Comment by steveharter** [comment] 2021-07-16 15:44
See also https://github.com/dotnet/runtime/issues/54158

**Comment by robertmclaws** [comment] 2021-07-16 16:15
Why did this issue get closed in when the problem is not actually solved yet?

**Comment by terrajobst** [comment] 2021-07-16 20:53
@steveharter I assume closing was an accident?

**Comment by terrajobst** [comment] 2021-07-19 16:56
@robertmclaws 

> Why did this issue get closed in when the problem is not actually solved yet?

I blame GitHub's UX

![image](https://user-images.githubusercontent.com/5169960/126197981-3eaa16a5-baad-4757-8941-dd116bd9c1e2.png)

**Comment by steveharter** [comment] 2021-07-20 13:44
Updated the API proposal to include `JsonDocument`, `JsonElement` and also `JsonNode` per https://github.com/dotnet/runtime/issues/54158.

Also all 4 permutations were included (generic + options, non-generic + options,  generic + context, non-generic + context).

The Deserialize methods are `JsonSerializer` extension methods so they can be used with an instance which may help discoverability:
```cs
using JsonDocument dom = JsonDocument.Parse(Json);

// Using the instance
MyPoco obj1 = dom.Deserialize<MyPoco>();

// Using JsonSerializer
MyPoco obj2 = JsonSerializer.Deserialize<MyPoco>(dom);
```

For V6 there are two choices:
1) Add these new APIs (special approval necessary since we are passed the Preview 7 cutoff).
2) Show samples on how to add extensions to your own helper class.  This option will not be as performant depending on the permutation: the Serialize extensions will perform unnecessary escaping for the temporary JSON needed to bridge between the CLR object and the DOM type, and Deserialize will not be as performant for `JsonNode` since temporary escaping and a buffer alloc\copy can be avoided.

**Comment by steveharter** [comment] 2021-07-20 14:23
In theory, the `JsonDocument` APIs could be removed which would force usage of the `JsonElement` APIs. However, this has some minor usability concerns:
- For serialize, the `document.RootElement` would need to be called to obtain the root element.
- For deserialize, existing user methods that take `JsonDocument` would need to be changed to take `JsonElement` since it is not possible to obtain `JsonDocument` from a `JsonElement`.

**Comment by bartonjs** [comment] 2021-07-20 17:46
Looks good as proposed.

```C#
namespace System.Text.Json
{
    public static partial class JsonSerializer
    {
     public static TValue? Deserialize<TValue>(this JsonDocument document, JsonSerializerOptions? options = null);
     public static object? Deserialize(this JsonDocument document, Type returnType, JsonSerializerOptions? options = null);
     public static TValue? Deserialize<TValue>(this JsonDocument document, JsonTypeInfo<TValue> jsonTypeInfo);
     public static object? Deserialize(this JsonDocument document, Type returnType, JsonSerializerContext context);

     public static JsonDocument SerializeToDocument<TValue>(TValue value, JsonSerializerOptions? options = null);
     public static JsonDocument SerializeToDocument(object? value, Type inputType, JsonSerializerOptions? options = null);
     public static JsonDocument SerializeToDocument<TValue>(TValue value, JsonTypeInfo<TValue> jsonTypeInfo);
     public static JsonDocument SerializeToDocument(object? value, Type inputType, JsonSerializerContext context);

     public static TValue? Deserialize<TValue>(this JsonElement element, JsonSerializerOptions? options = null);
     public static TValue? Deserialize<TValue>(this JsonElement element, JsonTypeInfo<TValue> jsonTypeInfo);
     public static object? Deserialize(this JsonElement element, Type returnType, JsonSerializerOptions? options = null);
     public static object? Deserialize(this JsonElement element, Type returnType, JsonSerializerContext context);

     public static JsonElement SerializeToElement<TValue>(TValue value, JsonSerializerOptions? options = null);
     public static JsonElement SerializeToElement(object? value, Type inputType, JsonSerializerOptions? options = null);
     public static JsonElement SerializeToElement<TValue>(TValue value, JsonTypeInfo<TValue> jsonTypeInfo);
     public static JsonElement SerializeToElement(object? value, Type inputType, JsonSerializerContext context);

     public static TValue? Deserialize<TValue>(this JsonNode node, JsonSerializerOptions? options = null);
     public static TValue? Deserialize<TValue>(this JsonNode node, JsonTypeInfo<TValue> jsonTypeInfo);
     public static object? Deserialize(this JsonNode node, Type returnType, JsonSerializerOptions? options = null);
     public static object? Deserialize(this JsonNode node, Type returnType, JsonSerializerContext context);

     public static JsonNode? SerializeToNode<TValue>(TValue value, JsonSerializerOptions? options = null);
     public static JsonNode? SerializeToNode(object? value, Type inputType, JsonSerializerOptions? options = null);
     public static JsonNode? SerializeToNode<TValue>(TValue value, JsonTypeInfo<TValue> jsonTypeInfo);
     public static JsonNode? SerializeToNode(object? value, Type inputType, JsonSerializerContext context);
    }
}
```

**Closed** 2021-07-28 01:35 UTC
Labels: api-approved, area-System.Text.Json, in pr
