### ISSUE TITLE
Test failure: System.Net.Http.Functional.Tests.HttpClientTest.GetAsync_ContentCanBeCanceled(getMode: 1, cancelMode: 2)

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#43206] opened 2020-10-09 08:28 UTC
failed in job: [runtime-libraries-coreclr outerloop 20201008.1](https://dev.azure.com/dnceng/public/_build/results?buildId=845001&view=ms.vss-test-web.build-test-results-tab&runId=26912004&resultId=103969&paneView=debug)

net6.0-Linux-Release-x64-CoreCLR_release-Debian.9.Amd64.Open

Error message
~~~
System.IO.IOException : Unable to write data to the transport connection: Broken pipe.
---- System.Net.Sockets.SocketException : Broken pipe

Stack trace
   at System.IO.StreamWriter.FlushAsyncInternal(StreamWriter _this, Boolean flushStream, Boolean flushEncoder, Char[] charBuffer, Int32 charPos, Boolean haveWrittenPreamble, Encoding encoding, Encoder encoder, Byte[] byteBuffer, Stream stream, CancellationToken cancellationToken) in /_/src/libraries/System.Private.CoreLib/src/System/IO/StreamWriter.cs:line 1065
   at System.IO.StreamWriter.WriteAsyncInternal(StreamWriter _this, String value, Char[] charBuffer, Int32 charPos, Int32 charLen, Char[] coreNewLine, Boolean autoFlush, Boolean appendNewLine) in /_/src/libraries/System.Private.CoreLib/src/System/IO/StreamWriter.cs:line 752
   at System.Net.Test.Common.LoopbackServer.Connection.SendResponseAsync(String response) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 679
   at System.Net.Test.Common.LoopbackServer.Connection.SendResponseBodyAsync(Byte[] body, Boolean isFinal, Int32 requestId) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 895
   at System.Net.Test.Common.GenericLoopbackConnection.SendResponseBodyAsync(String content, Boolean isFinal, Int32 requestId) in /_/src/libraries/Common/tests/System/Net/Http/GenericLoopbackServer.cs:line 89
   at System.Net.Http.Functional.Tests.HttpClientTest.<>c__DisplayClass26_0.<<GetAsync_ContentCanBeCanceled>b__3>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientTest.cs:line 483
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 126
   at System.Net.Http.Functional.Tests.HttpClientTest.<>c__DisplayClass26_0.<<GetAsync_ContentCanBeCanceled>b__1>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientTest.cs:line 479
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 96
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 124
   at System.Net.Test.Common.LoopbackServerFactory.<>c__DisplayClass5_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in /_/src/libraries/Common/tests/System/Net/Http/GenericLoopbackServer.cs:line 36
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 74
   at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 37
   at System.Net.Http.Functional.Tests.HttpClientTest.GetAsync_ContentCanBeCanceled(Int32 getMode, Int32 cancelMode) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientTest.cs:line 444
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 924
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendAsyncForNetworkStream(Socket socket, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 727
   at System.Net.Sockets.Socket.SendAsyncForNetworkStream(ReadOnlyMemory`1 buffer, SocketFlags socketFlags, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 299
   at System.Net.Sockets.NetworkStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/NetworkStream.cs:line 720
   at System.IO.StreamWriter.FlushAsyncInternal(StreamWriter _this, Boolean flushStream, Boolean flushEncoder, Char[] charBuffer, Int32 charPos, Boolean haveWrittenPreamble, Encoding encoding, Encoder encoder, Byte[] byteBuffer, Stream stream, CancellationToken cancellationToken) in /_/src/libraries/System.Private.CoreLib/src/System/IO/StreamWriter.cs:line 1055
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 42
   at System.IO.StreamWriter.FlushAsyncInternal(StreamWriter _this, Boolean flushStream, Boolean flushEncoder, Char[] charBuffer, Int32 charPos, Boolean haveWrittenPreamble, Encoding encoding, Encoder encoder, Byte[] byteBuffer, Stream stream, CancellationToken cancellationToken)
   at System.IO.StreamWriter.FlushAsyncInternal(Boolean flushStream, Boolean flushEncoder, Char[] sCharBuffer, Int32 sCharPos, CancellationToken cancellationToken) in /_/src/libraries/System.Private.CoreLib/src/System/IO/StreamWriter.cs:line 1028
   at System.IO.StreamWriter.WriteAsyncInternal(StreamWriter _this, String value, Char[] charBuffer, Int32 charPos, Int32 charLen, Char[] coreNewLine, Boolean autoFlush, Boolean appendNewLine) in /_/src/libraries/System.Private.CoreLib/src/System/IO/StreamWriter.cs:line 746
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 42
   at System.IO.StreamWriter.WriteAsyncInternal(StreamWriter _this, String value, Char[] charBuffer, Int32 charPos, Int32 charLen, Char[] coreNewLine, Boolean autoFlush, Boolean appendNewLine)
   at System.IO.StreamWriter.WriteAsync(String value) in /_/src/libraries/System.Private.CoreLib/src/System/IO/StreamWriter.cs:line 681
   at System.Net.Test.Common.LoopbackServer.Connection.SendResponseAsync(String response) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 678
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 42
   at System.Net.Test.Common.LoopbackServer.Connection.SendResponseAsync(String response)
   at System.Net.Test.Common.LoopbackServer.Connection.SendResponseBodyAsync(Byte[] body, Boolean isFinal, Int32 requestId) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 895
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 42
   at System.Net.Test.Common.LoopbackServer.Connection.SendResponseBodyAsync(Byte[] body, Boolean isFinal, Int32 requestId)
   at System.Net.Test.Common.GenericLoopbackConnection.SendResponseBodyAsync(String content, Boolean isFinal, Int32 requestId) in /_/src/libraries/Common/tests/System/Net/Http/GenericLoopbackServer.cs:line 89
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 42
   at System.Net.Test.Common.GenericLoopbackConnection.SendResponseBodyAsync(String content, Boolean isFinal, Int32 requestId)
   at System.Net.Http.Functional.Tests.HttpClientTest.<>c__DisplayClass26_0.<<GetAsync_ContentCanBeCanceled>b__3>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientTest.cs:line 483
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs:line 289
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 186
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs:line 327
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs:line 305
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 186
   at System.Threading.Tasks.Task.InnerInvoke() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2376
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2358
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 186
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2316
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2252
   at System.Threading.Tasks.ThreadPoolTaskScheduler.<>c.<.cctor>b__10_0(Object s) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/ThreadPoolTaskScheduler.cs:line 35
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state) in /_/src/coreclr/src/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs:line 47
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 186
   at System.Threading.ThreadHelper.ThreadStart(Object obj) in /_/src/coreclr/src/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs:line 75
--- End of stack trace from previous location ---
~~~

**Comment by karelz** [comment] 2020-11-12 17:12
Duplicate of #44003

**Closed by karelz** 2020-11-12 17:12 UTC
Labels: area-System.Net.Http, untriaged
