### ISSUE TITLE
Region.TwoLetterISORegionName can return three numerical digits

### ISSUE THREAD

**Issue by riverar** [dotnet/runtime#32753] opened 2020-02-24 18:44 UTC
On a Windows 10 system using a [customized locale](https://docs.microsoft.com/en-us/windows/win32/intl/custom-locales), `TwoLetterISORegionName` returns `"150"`. (RegionInfo also becomes unreliable for ascertaining accurate geographic region information, as needed for, say, GDPR purposes.)

# Environment
Windows 10 Version 1909 (18363.657) or Windows 10 Version 2004 (19569.1000) (pre-release)
.NET Framework 4.6.2 or .NET Core 3.1
Country: Netherlands
Regional format: English (Europe)
Short time: HH:mm tt
Long time: HH:mm:ss tt

# Samples
## .NET Framework BCL (sample1.cs)
```csharp
using System;
using System.IO;
using System.Globalization;

class A
{
  static void Main(string[] args)
  {
    Console.WriteLine(RegionInfo.CurrentRegion.TwoLetterISORegionName);
  }
}
```
1. `C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe /out:sample1.exe sample1.cs`
2. Execute `sample1.exe`
3. Observe `150` output

## WinRT (sample2.cs)
```csharp
using System;
using System.IO;

class A
{
  static void Main(string[] args)
  {
    Console.WriteLine(new Windows.Globalization.GeographicRegion().CodeTwoLetter);
  }
}
```
1. `C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe /out:sample2.exe /reference:"C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.16299.0\Windows.winmd" /reference:"C:\Windows\Microsoft.NET\Framework\v4.0.30319\System.Runtime.dll" sample2.cs`
2. Execute `sample2.exe`
3. Observe `NL` output

**Comment by tarekgh** [comment] 2020-03-12 00:38
When choosing `English (Europe)`, Windows will set the default locale to `en-150` and that will return the region's name `Europ` and TwoLetterISORegionName `150` which is correct. if you want to get the Netherlands region, you'll need to choose one of the locales:

```
English (Netherlands)
Western Frisian (Netherlands)
Low German (Netherlands)
Dutch (Netherlands)
```

Those will return `NL` as TwoLetterISORegionName.

For WinRT case, WinRT works differently as the UWP apps can have a list of default languages which is a mix from the user profile languages and app languages too. Note that  `Windows.Globalization.GeographicRegion().CodeTwoLetter` is a Windows API and not .NET API. This is by design for .NET as RegionInfo.CurrentRegion always returns the match of your Regional format setting which is the case here.

**Comment by riverar** [comment] 2020-03-12 00:54
@tarekgh I don't consider an API that returns **3 digits** from a property named *TwoLetter*ISORegionName to be correct behavior. Is this documented as errata somewhere? Does the ISO define the `150`?

From my reading, `150` seems to coorespond with all custom cultures and not just Europe, so how do .NET users retrieve Europe?

**Comment by tarekgh** [comment] 2020-03-12 01:21
@riverar we get the information from Windows. .NET doesn't carry any globalization data. When setting your default region formats to English (Europ), Windows assign this to a locale called en-150 and that will return the `150` as the 2 letters ISO region code. It looks ICU define this locale same http://www.localeplanet.com/icu/en-150/index.html. I don't think Europ by itself has region code and that is why they used 150 to point at Europ and use 001 for international (i.e. en-001). The question here, if you choose English (Europ), what code you expect to get? `NL` is the wrong answer anyway. 

If you still feel this is wrong, you may log an issue to the Windows team through the Feedback Hub on Windows 10. 

the [article ](https://www.ctrl.blog/entry/en-001.html)  maybe a useful to read too.

**Comment by riverar** [comment] 2020-03-12 01:31
@tarekgh In Windows 10, the user selected a "country" of `Netherlands` and "regional format" of `English (Europe)`. So how do you recommend .NET users retrieve the selected country if `RegionInfo.CurrentRegion` isn't correct?

Also, can we agree returning 3 digits from a property that is expected to return 2 letters is a bug, at least in its design?

**Comment by tarekgh** [comment] 2020-03-12 01:43
> In Windows 10, the user selected a "country" of Netherlands and "regional format" of English (Europe)

.NET code is written before Windows 10 introduces such settings. I'll follow up with the Windows team to see if we can leverage it. But if anyone tries to create a region for en-150, they will still get `150` as the code if this is Windows/ICU behavior.

> Also, can we agree returning 3 digits from a property that is expected to return 2 letters is a bug, at least in its design?

Well, although I agree with you in principle, my agreement wouldn't change anything here as we are getting this from Windows. So, this is the decision taken by the Windows team (and properly by the standard guys as I am seeing ICU is doing the same).

**Closed** 2020-03-21 00:49 UTC
Labels: area-System.Globalization, enhancement
