### ISSUE TITLE
Socket.Select throws ObjectDisposedException when one of the sockets is disposed

### ISSUE THREAD

**Issue by drieseng** [dotnet/runtime#34886] opened 2020-04-13 06:57 UTC
In (desktop) .NET Framework, `Socket.Select(....)` throws a **SocketException** when one of the sockets that you specify is disposed:

> System.Net.Sockets.SocketException (10038): An operation was attempted on something that is not a socket.

In .NET Core 2.1 and 3.1, this is also the exception that is thrown on Windows. On Linux, no exception is thrown.

Now in .NET 5.0 Preview 2, an **ObjectDisposedException** is thrown on both Windows and Linux:

> System.ObjectDisposedException: Safe handle has been closed.
> Object name: 'SafeHandle'.
>    at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
>    at System.Net.Sockets.SocketPal.AddToPollArray(PollEvent* arr, Int32 arrLength, IList socketList, Int32& arrOffset, PollEvents events, Int32& refsAdded)
>    at System.Net.Sockets.SocketPal.SelectViaPoll(IList checkRead, Int32 checkReadInitialCount, IList checkWrite, Int32 checkWriteInitialCount, IList checkError, Int32 checkErrorInitialCount, PollEvent* events, Int32 eventsLength, Int32 microseconds)
>    at System.Net.Sockets.SocketPal.Select(IList checkRead, IList checkWrite, IList checkError, Int32 microseconds)
>    at System.Net.Sockets.Socket.Select(IList checkRead, IList checkWrite, IList checkError, Int32 microSeconds)

To reproduce, compile and run the following code fragment:

```cs
using System.Collections.Generic;
using System.Net;
using System.Net.Sockets;

class SelectDisposed
{
    private static void Main()
    {
        var endPoint = new IPEndPoint(IPAddress.Loopback, 8080);
        var client = new Socket(endPoint.AddressFamily, SocketType.Stream, ProtocolType.Tcp);
        client.Dispose();

        Socket.Select(new List<object> { client }, null, null, -1);
    }
}
```

**Comment by tmds** [comment] 2020-04-13 14:07
This is caused by https://github.com/dotnet/corefx/pull/41763.

With the old behavior, no reference counting was performed. The `SocketException` refers to using a handle which is no longer a socket.
In a worse scenario, the handle could have been reused for a different `Socket` causing the `Select` to be performed against the wrong socket.

With the change, `Select` will require the handle to be valid. If the handle is not valid ODE is thrown.

**Comment by karelz** [comment] 2020-04-13 17:49
So it is technical breaking change in 5.0.
We should either document it as such, or wrap the `ObjectDisposedException` in `SocketException`.

@drieseng how did you discover the difference? Did you run into it in your app?

**Comment by stephentoub** [comment] 2020-04-13 18:12
> So it is technical breaking change in 5.0. We should either document it as such

It's fine to document it.  It's a bug that should have been fixed years ago when things were moved to be SafeHandle-based.  It's a handle-recycling issue.

**Comment by karelz** [comment] 2020-04-13 18:49
OK, marking as such. cc @antonfirsov

**Comment by drieseng** [comment] 2020-04-15 19:18
I'm **really** impressed by the speed at which this decision was taken and verified across all implementations (.NET, Mono, ...). Because this is how such a thing is done, right ?

**Comment by danmosemsft** [comment] 2020-04-15 20:13
It is certainly nice that the test is running on Mono automatically. It shows the value of all being in one repo.

**Comment by drieseng** [comment] 2020-04-15 21:14
That's indeed true.

**Comment by karelz** [comment] 2020-09-01 19:44
Fixed by PR https://github.com/dotnet/dotnet-api-docs/pull/4720

**Closed by karelz** 2020-09-01 19:44 UTC
Labels: area-System.Net.Sockets, breaking-change, documentation, tenet-compatibility
