### ISSUE TITLE
SEHException when free GCHandle with FieldOffset

### ISSUE THREAD

**Issue by nilan256** [dotnet/runtime#100902] opened 2024-04-11 04:40 UTC
### Description

Sorry for bad English.

When I switch the work machine from macmini with inter chip to macbook with M1 chip, some code cannot run anymore.

When free a GCHandle with FieldOffset attribute, an SEHException will be thrown.
I tried to find more information about this exception, but nothing helped.

### Reproduction Steps

```csharp
using System.Runtime.InteropServices;
class Program
{
    
    static void Main(string[] args)
    {
        TestCommonStruct(); // ok
        TestIntPtrStruct(); // ok
        TestGCHandleStruct(); // error
    }

    static void TestGCHandleStruct()
    {
        var o = new object();
        var test = new GCHandleStruct();
        var handle = GCHandle.Alloc(o);
        test.Handle = handle;
        
        Console.WriteLine(test.Handle == handle); // is True
        // I checked `_handle` field of two handles, they have same value.
        
        test.Handle.Free(); // error 
        // Exception:
        // System.Runtime.InteropServices.SEHException (0x80004005):
        // External component has thrown an exception.
        
        // test.Free(); // same error
        // handle.Free(); // but this is ok
    }
    
    [StructLayout(LayoutKind.Explicit)]
    private struct GCHandleStruct
    {
        [FieldOffset(0)]
        public byte SomeValue;
        [FieldOffset(1)]
        public GCHandle Handle;

        public void Free() => Handle.Free();
    }

    static void TestCommonStruct()
    {
        var o = new object();
        var test = new CommonStruct();
        test.Handle = GCHandle.Alloc(o);
        test.Free();
    }
    
    private struct CommonStruct
    {
        public GCHandle Handle;
        public void Free() => Handle.Free();
    }

    static void TestIntPtrStruct()
    {
        var o = new object();
        var test = new IntPtrStruct();
        var handle = GCHandle.Alloc(o);
        test.Ptr = GCHandle.ToIntPtr(handle);
        test.Free();
    }
    
    [StructLayout(LayoutKind.Explicit)]
    struct IntPtrStruct
    {
        [FieldOffset(0)]
        public byte SomeValue;
        [FieldOffset(1)]
        public IntPtr Ptr;

        public void Free() => GCHandle.FromIntPtr(Ptr).Free();
    }
}
```

Full project:

[ConsoleApp2.zip](https://github.com/dotnet/runtime/files/14941419/ConsoleApp2.zip)

### Expected behavior

The GCHandle can be free correctly.

### Actual behavior

Error message:
```
Unhandled exception. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at System.Runtime.InteropServices.GCHandle.Free()
   at Program.TestGCHandleStruct() in /Users/***/***/ConsoleApp2/Program.cs:line 59
   at Program.Main(String[] args) in /Users/***/***/ConsoleApp2/Program.cs:line 66
```

### Known Workarounds

Like I tested in example, use IntPtr looks ok.

### Configuration

Which version of .NET is the code running on?
7.0.408
What OS and version, and what distro if applicable?
macOS 14.4.1
What is the architecture (x64, x86, ARM, ARM64)?
Apple Silicon M1
Do you know whether it is specific to that configuration?
I think it is. This is not happened on my mac-mini with inter chip.

### Other information

I am not a professional Net desktop program developers, mostly used in Unity. 

I am not familiar with many debugging methods. If there is any information I need to provide, please let me know.

**Comment by huoyaoyuan** [comment] 2024-04-11 04:49
It's probably because ARM doesn't allow misaligned memory access while x86 is more tolerate. `GCHandle` must be aligned at whole-pointer boundary. Using `[FieldOffset(8)]` should probably work.

**Comment by nilan256** [comment] 2024-04-11 05:02
> It's probably because ARM doesn't allow misaligned memory access while x86 is more tolerate. `GCHandle` must be aligned at whole-pointer boundary. Using `[FieldOffset(8)]` should probably work.

It's really works, thanks!

Hope this can be resolved in the future or more helpful information can be provided.

**Comment by huoyaoyuan** [comment] 2024-04-11 05:09
In this situation, CLR should "properly" throw `TypeLoadException` indicating the layout is invalid.

Moreover, using `FieldOffset` is strongly discouraged without good knowledge of native(C++) object layout.

**Comment by jkotas** [comment] 2024-04-11 07:54
> In this situation, CLR should "properly" throw TypeLoadException indicating the layout is invalid.

This is not invalid layout. There are good reasons why one may want to create layout with misaligned fields.

The problem is that some operations on layout with misaligned fields are not permitted.

> SEHException

It would be better for this to throw `DataMisalignedException`. cc @VSadov @janvorli

**Comment by EgorBo** [comment] 2024-04-11 11:34
> It would be better for this to throw `DataMisalignedException`. cc @VSadov @janvorli

https://github.com/dotnet/runtime/issues/91662

**Comment by jkotas** [comment] 2024-04-11 19:52
Closing as duplicate of https://github.com/dotnet/runtime/issues/91662

**Closed by jkotas** 2024-04-11 19:52 UTC
Labels: area-ExceptionHandling-coreclr, untriaged
