### ISSUE TITLE
Regex Capture gives IndexOutOfRangeException on `(?:){93}`

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#62094] opened 2021-11-27 05:41 UTC
```c#
Regex regex = new("@(a*)+?");
MatchCollection mc = regex.Matches("@");

foreach (Match m in mc)
{
    Console.WriteLine($"{m.Index} .. {m.Length + m.Index}");
    Console.WriteLine(m.ToString());
}
```

On other regex engines, like PCRE, Nim, Python, Javascript, and Golang you would get `0 .. 1`

On .NET Framework this displays `1 .. 1`

On .NET 6 it gives
```
1 .. 3
Unhandled exception. System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at System.Text.RegularExpressions.Capture.get_Value()
   at System.Text.RegularExpressions.Capture.ToString()
   at Program.<Main>$(String[] args) in C:\Users\danmose\source\repos\ConsoleApp31\ConsoleApp31\Program.cs:line 191
```
@stephentoub first bug from running Nim tests.

**Comment by danmoseley** [comment] 2021-11-27 05:55
`@(a?)+?` with text of `@`will not crash, but gives `1 .. 1` whereas other engines will give `0 .. 1`

**Comment by stephentoub** [comment] 2021-11-27 11:20
> incorrect length in .NET Core, causing a crash.

Looks like a regression in .NET 5, which also exhibits this.  .NET Core 3.1 outputs 1..1 like .NET Framework does.

**Comment by stephentoub** [comment] 2021-11-27 20:23
This is actually an issue in .NET Framework 4.8 and .NET Core 3.1 as well.

The change in .NET 5 is that it recognizes that the outer loop is actually atomic (because there's nothing after it to backtrack into it).  So it effectively changes the expression to instead be:
```
"@(?>(a*)+?)"
```
Try that expression with .NET Framework, and you similarly get 1..3 and an out of range exception.

**Comment by danmoseley** [comment] 2021-11-28 01:32
When I fuzzed I believe I only used IsMatch. Next time we should enumerate the matches also.

**Comment by joperezr** [comment] 2022-07-20 23:03
I just tested with Preview 7 bits and seems like all 4 engines (including Interpreted) are correctly printing:
``` ini
0 .. 1
@
```

**Comment by danmoseley** [comment] 2022-07-21 19:20
@joperezr might be worth adding as a test case if we don't have one.

**Comment by joperezr** [comment] 2022-07-21 19:54
Good point, I'll reopen this to track that.

**Comment by stephentoub** [comment] 2022-07-21 20:07
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.RegularExpressions/tests/FunctionalTests/Regex.MultipleMatches.Tests.cs#L393-L422

**Comment by joperezr** [comment] 2022-07-21 20:11
lol, that explains why after adding it I was seeing it running elsewhere in testResults.xml. I'll fix that condition instead then.

**Comment by joperezr** [comment] 2022-07-21 20:29
so I tried re-enabling all those 3, but looks like one is still problematic:

https://github.com/dotnet/runtime/blob/f7d7b5575465adece049de53240d6dc3ca283738/src/libraries/System.Text.RegularExpressions/tests/FunctionalTests/Regex.MultipleMatches.Tests.cs#L405-L409

This is still throwing IndexOutOfRangeException. Haven't looked into all the details yet, but for now I'll probably just put up a PR to add the other two back for the interpreted engine, and won't close this issue until that last test is also fixed.

**Comment by stephentoub** [comment] 2022-08-01 15:16
@joperezr, can this be closed again now?

Or if it's tracking a disabled test, should it be moved out of 7.0 and labeled as disabled test?

**Comment by joperezr** [comment] 2022-08-01 23:37
it is tracking a disabled test, so I'll label and move as suggested.

**Comment by rhirano0715** [comment] 2024-01-09 02:23
I would like to provide a comment for reference.
When I tried changing the number of repetitions and testing it, the following results were obtained.

- net9.0
  - `@"(?:){0}"` ～ `@"(?:){25}"`: Success
  - `@"(?:){26}"`: Failure  
    IndexOutOfRangeException occurs (index is -1)  in the following code snippet of  `RegexInterpreter. TrackPush2(int i1, int i2)`   
    https://github.com/dotnet/runtime/blob/315a2a8e918c6349cf0132e8a6c0f056188aa00b/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexInterpreter.cs#L125
  - `@"(?:){27}"` ～ `@"(?:){99}"`: Failure
    Probably, failures continue from `@"(?:){100}"` onwards.
    IndexOutOfRangeException occurs (index is -1)  in the following code snippet of  `RegexInterpreter. TrackPush(int i1)`   
    https://github.com/dotnet/runtime/blob/315a2a8e918c6349cf0132e8a6c0f056188aa00b/src/libraries/System.Text.RegularExpressions/src/System/Text/RegularExpressions/RegexInterpreter.cs#L78
- (net48)
  - `@"(?:){0}"` ～ `@"(?:){16}"`: Success
  - `@"(?:){17}"` ～ `@"(?:){99}"`: Failure(IndexOutOfRangeException )
    Probably, failures continue from `@"(?:){100}"` onwards.

I insert the following into Regex.MultipleMatches.Tests.Matches_TestData() for testing.

```csharp
                for (int i = 0; i < 100; i++)
                {
                    yield return new object[]
                    {
                        engine, @"(?:){" + i + @"}", "x", RegexOptions.None, new[]
                        {
                            new CaptureData("", 0, 0),
                            new CaptureData("", 1, 0)
                        }
                    };
                }
```

**Comment by rhirano0715** [comment] 2024-02-23 07:01
The size of RegexRunner.runtrack is set to runtrackcount * 8 (runtrackcount == _code.TrackCount). 
The value of runtrackcount was as follows:

- For @"(?:){0}" ~ @"(?:){1}": 3
- For @"(?:){2}" ~ @"(?:){99}": 7

It appears that the reason the index (runtrackpos) becomes negative and causes an exception from @"(?:){26}" ~ @"(?:){99}" is because the runtrack size of 7 * 8 (== 56) is not sufficient.

**Closed** 2024-04-13 02:55 UTC
Labels: bug, area-System.Text.RegularExpressions, disabled-test, help wanted, in-pr
