### ISSUE TITLE
[HttpListener] No way to stop HttpListener from GetContext

### ISSUE THREAD

**Issue by scegg** [dotnet/runtime#35526] opened 2020-04-27 08:58 UTC
In dotnet core 3.1.201 with Windows 10 x64, after GetContext() is called from another thread, there is no way to stop it.

To test it, create a console app, and type these code:

```c#
    class Program
    {
        //NOTE: This demo need to be started with ADMINISTRATOR PRIVILEGE due to HttpListener required.

        static HttpListener listener = new HttpListener();

        static void Main(string[] args)
        {
            listener.Prefixes.Add("http://+:33355/");
            listener.Start();

            var thread = new Thread(Working);
            thread.Start();

            Thread.Sleep(2000);

            listener.Stop();
            listener.Abort();
            thread.Join();

            Console.WriteLine("done");
        }

        static void Working()
        {
            while (true)
            {
                try
                {
                    var context = listener.GetContext();
                }
                catch { break; }
            }
        }
    }
```

After listener.Stop and Abort called, thread.Join will still be blocked.

**Comment by uposledzony** [comment] 2020-05-13 23:23
I also have encountered this issue, GetContext blocks thread without throwing e.g. ObjectDisposedException, although Abort and Close methods were called. It's worth to mention that calls that use callbacks (BeginGetContext, EndGetContext) immediately throw an exception if listener calls Abort or Stop.

**Comment by karelz** [comment] 2020-06-02 19:48
Duplicate of #25497

**Comment by karelz** [comment] 2020-06-02 19:49
@uposledzony the issue is fixed in .NET 5 -- can you verify it on latest Preview builds please? Thanks!

**Closed by karelz** 2020-06-02 19:48 UTC
Labels: area-System.Net, untriaged
