### ISSUE TITLE
ShouldSerializeValue for PropertyDescriptor fails for values of underlying enum types

### ISSUE THREAD

**Issue by KlausLoeffelmann** [dotnet/runtime#52116] opened 2021-04-30 17:03 UTC
### Description

The `ShouldSerializeValue` method of the `PropertyDescriptor` fails, when - in C# - a `DefaultValue` for a Property of an enum type is not defined with the enum type, but with it's underlying type. For example:

```
    internal class Foo : Component
    {
        [DefaultValue(0)]
        public TestEnum Bar { get; set; }
    }

    internal enum TestEnum
    {
        Value1 = 0,
        Value2 = 1
    }
```

This is even more dramatic in Visual Basic, where the compiler replaces the Enum type by its underlaying type by default, which makes properties of type enum, which have been defined in Visual Basic, never succeed in a `ShouldSerializeValue` call.

```
    <DefaultValue(TestEnum.Value1)>
    Public Property Bar As TestEnum
```

becomes automatically (IL translated to C#):

```
    [DefaultValue(0)]
    public TestEnum Bar
    {
        [CompilerGenerated]
        get
        {
            return _Bar;
        }
        [CompilerGenerated]
        set
        {
            _Bar = value;
        }
    }
```
Background:
When the `DefaultValue` property of a `ReflectPropertyDescriptor` is called, e.g. by calling `ShouldSerializeProperty` of  `PropertyDescriptor`, and then the `DefaultValue` is of Type `Enum` but the value is given of the type of the underlying type, a `NullReferenceException` is thrown and the call fails.

_Making this work and most likely serviced from .NET Core 3.1 on is, amongst other scenarios, critical for the Windows Forms Designer not to crash in those scenarios._ (Which are not niche.)

### Configuration
* All .NET Core/.NET Versions.
* Windows.
* x86, x64, ARM
* No.

### Regression?
No.

### Other information

The error might be here:
https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/ReflectPropertyDescriptor.cs#L303

where `toObject` is called with `_defaultValue` instead of the local variable `defaultValue`.

(Thanks @DustinCampbell for helping tracking this down. 
Also @merriemcgaw, @RussKie, @JeremyKuhne, @Pilchie for reference.)

**Comment by merriemcgaw** [comment] 2021-04-30 19:09
Please note that this is blocking a common scenario for WinForms devs, and now that usage of the designer is increasing it's going to generate a lot of noise as people port their apps. We should consider servicing 3.1 and 5 as they are the most common targets for porting Framework apps to.

**Comment by merriemcgaw** [comment] 2021-07-14 23:54
@maryamariyan can you let us know if there is any status update on this one? It is blocking a **high** priority scenario for the WinForms designer and we need it fixed in .NET 6, probably even serviced so customers building Custom Controls are able to use their default values as they did before.

cc: @Pilchie

**Comment by safern** [comment] 2021-07-15 00:18
FYI: @ericstj

**Comment by ericstj** [comment] 2021-07-15 04:14
> use their default values as they did before.

@merriemcgaw @KlausLoeffelmann  this was not filed as a regression, did the same behavior exist on .NETFramwork?  Why is this so important to fix now if it’s not a regression?

**Comment by DustinCampbell** [comment] 2021-07-15 17:51
Yes, this is a regression from .NET Framework that occurred during some refactoring of `ReflectPropertyDescriptor` in .NET Core. The NetFx code looks like this:

```C#
defaultValue = ((DefaultValueAttribute)a).Value;
// Default values for enums are often stored as their underlying integer type:
if (defaultValue != null && PropertyType.IsEnum && PropertyType.GetEnumUnderlyingType() == defaultValue.GetType()) {
    defaultValue = Enum.ToObject(PropertyType, defaultValue);
}
```

Essentially, the NetFx version uses a field called `defaultValue` throughout. In .NET Core, this was refactored to lift the field to a local variable. However, one of the field references was missed, resulting in a null-ref:

```C#
// Default values for enums are often stored as their underlying integer type:
object defaultValue = ((DefaultValueAttribute)a).Value;
bool storedAsUnderlyingType = defaultValue != null && PropertyType.IsEnum && PropertyType.GetEnumUnderlyingType() == defaultValue.GetType();
_defaultValue = storedAsUnderlyingType ?
    Enum.ToObject(PropertyType, _defaultValue) :
    defaultValue;
```

The fix is simple. Change `Enum.ToObject(PropertyType, _defaultValue)` to `Enum.ToObject(PropertyType, defaultValue)`.

We didn't discover it until more recently because VB code is more likely to produce IL that triggers the exception, due to the fact that VB's implicit conversions and overload resolution is different from C#'s.  There are more details about that [here](https://github.com/dotnet/winforms-designer/issues/2473#issuecomment-832309046).

**Comment by ericstj** [comment] 2021-07-16 02:21
I see, it was regressed here: https://github.com/dotnet/corefx/commit/af3f34f96938931b39e229fbb618fe720b21f620#diff-4e980b410175c51d6330532288f63963ecd72513029c6954e5e862e7476e39c4R297.  Seems like an simple refactoring bug (which we should have had tests to catch)  cc @stephentoub 

Thanks for the great report, it's clear now.  I'll put up a fix.  For things like this in the future you're welcome to submit a PR.  You've done a ton of leg-work to get this far already and it might have even been less work to submit a PR than file the issue.  There's probably a lot more expertise in WinForms on this codebase too.  Thanks again for the report and a fix will go in shortly.  Let us know if you need this ported to P7 or servicing.

**Closed** 2021-07-16 16:55 UTC
Labels: area-System.ComponentModel, blocking, in pr

**Comment by KlausLoeffelmann** [comment] 2021-08-04 21:09
@merriemcgaw - considering we are getting customer reports about this, should we consider servicing?

https://github.com/dotnet/winforms/issues/2748

**Comment by merriemcgaw** [comment] 2021-08-17 22:30
If we're getting customer reports we should consider it. It doesn't seem to be a terribly edge case situation, but I'd leave the final call with @ericstj.

**Comment by ericstj** [comment] 2021-08-18 01:17
We don't proactively service and "getting customer reports" isn't sufficient for meeting the bug bar.  Could you apply the bug bar?  https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/545/NET-Servicing?anchor=bug-bar
