### ISSUE TITLE
SDSUtils.BuildDirectoryEntry("LDAP://" + dnsDomainName + "/" + GetEscapedDN(distinguishedName), this.Credentials, this.authTypes) is not disposed at the end of the function

### ISSUE THREAD

**Issue by achufistov** [dotnet/runtime#94776] opened 2023-11-15 13:57 UTC
### Description

dotnet 6.0

File: /src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/AD/ADStoreCtx_LoadStore.cs:284

Problem: SDSUtils.BuildDirectoryEntry("LDAP://" + dnsDomainName + "/" + GetEscapedDN(distinguishedName), this.Credentials, this.authTypes) is not disposed at the end of the function

### Reproduction Steps

1) Role: detected
detected
[ADStoreCtx_LoadStore.cs:[284:0]]
2) Role: tracepoint
2.1 Step 1: Condition storeObject is DirectoryEntry taking false branch
[ADStoreCtx_LoadStore.cs:[244:17]]
2.2 Step 2: Condition null != de taking any branch
[ADStoreCtx_LoadStore.cs:[258:104]]
2.3 Step 3: Condition targetIsFromGC taking true branch
[ADStoreCtx_LoadStore.cs:[273:21]]
2.4 Step 4: Condition targetIsFromGC taking true branch
[ADStoreCtx_LoadStore.cs:[276:25]]
2.5 Step 5: Condition targetIsFromGC taking true branch
[ADStoreCtx_LoadStore.cs:[282:25]]
2.6 created in method System.DirectoryServices.AccountManagement.SDSUtils.BuildDirectoryEntry(string, System.DirectoryServices.AccountManagement.NetCred, System.DirectoryServices.AuthenticationTypes)
[ADStoreCtx_LoadStore.cs:[284:35]]
2.7 assigned
[ADStoreCtx_LoadStore.cs:[284:25]]
2.8 no escape
[ADStoreCtx_LoadStore.cs:[285:25]]
2.9 Step 6: Condition de != null taking false branch
[ADStoreCtx_LoadStore.cs:[289:21]]
2.10 Step 7: Condition constructedContext is null taking false branch
[ADStoreCtx_LoadStore.cs:[297:62]]
2.11 Step 8: Condition targetIsFromGC taking true branch
[ADStoreCtx_LoadStore.cs:[298:43]]
2.12 Step 9: Condition de != null taking false branch
[ADStoreCtx_LoadStore.cs:[305:21]]
2.13 return
[ADStoreCtx_LoadStore.cs:[316:24]]
2.14 Step 10: Condition targetIsFromGC taking true branch
[ADStoreCtx_LoadStore.cs:[324:21]]
2.15 Step 11: Condition de != null taking any branch
[ADStoreCtx_LoadStore.cs:[324:39]]

3) Role: debug
3.1 System.DirectoryServices.ResultPropertyCollection.this[string].get invocation is a back edge
[ADStoreCtx_LoadStore.cs:[255:45]]
3.2 System.DirectoryServices.AccountManagement.GlobalDebug.Info.get invocation is a back edge
[ADStoreCtx_LoadStore.cs:[258:37]]
3.3 System.ComponentModel.Component.Dispose() invocation is a back edge
[ADStoreCtx_LoadStore.cs:[327:21]]
3.4 System.DirectoryServices.ResultPropertyCollection.this[string].get invocation is a back edge
[ADStoreCtx_LoadStore.cs:[309:43]]
3.5 System.ComponentModel.Component.Dispose() invocation is a back edge
[ADStoreCtx_LoadStore.cs:[327:21]]

### Expected behavior

memory leak

### Actual behavior

memory leak

### Other information

Found by Linux Verification Center (linuxtesting.org) with SVACE.

**Comment by achufistov** [comment] 2023-11-17 08:44
I would like to suggest a pull request.

**Comment by buyaa-n** [comment] 2024-01-17 19:25
Closing as duplicate of https://github.com/dotnet/runtime/issues/94775

**Closed by buyaa-n** 2024-01-17 19:25 UTC
Labels: area-System.DirectoryServices, untriaged
