### ISSUE TITLE
Test failure JIT/Performance/CodeQuality/Serialization/Deserialize/Deserialize.dll

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#93165] opened 2023-10-07 06:09 UTC
**Failed in:** [runtime-coreclr jitstress 20231004.2](https://dev.azure.com/dnceng-public/public/_build/results?buildId=428150&view=ms.vss-test-web.build-test-results-tab&runId=9446448&resultId=103222&paneView=debug)

**Failed tests:**
```
coreclr windows arm64 Checked jitstress2 @ Windows.11.Arm64.Open
    - JIT/Performance/CodeQuality/Serialization/Deserialize/Deserialize.dll
    - JIT/Performance/CodeQuality/Serialization/Serialize/Serialize.dll
coreclr linux arm64 Checked jitstress2 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
    - JIT/Performance/CodeQuality/Serialization/Deserialize/Deserialize.dll
    - JIT/Performance/CodeQuality/Serialization/Serialize/Serialize.dll
coreclr osx x64 Checked jitstress2 @ OSX.1200.Amd64.Open
    - JIT/Performance/CodeQuality/Serialization/Deserialize/Deserialize.dll
    - JIT/Performance/CodeQuality/Serialization/Serialize/Serialize.dll
coreclr windows x64 Checked jitstress2 @ Windows.10.Amd64.Open
    - JIT/Performance/CodeQuality/Serialization/Deserialize/Deserialize.dll
    - JIT/Performance/CodeQuality/Serialization/Serialize/Serialize.dll
coreclr osx arm64 Checked jitstress2 @ OSX.1200.ARM64.Open
    - JIT/Performance/CodeQuality/Serialization/Deserialize/Deserialize.dll
    - JIT/Performance/CodeQuality/Serialization/Serialize/Serialize.dll
coreclr linux x64 Checked jitstress2 @ Ubuntu.2204.Amd64.Open
    - JIT/Performance/CodeQuality/Serialization/Deserialize/Deserialize.dll
    - JIT/Performance/CodeQuality/Serialization/Serialize/Serialize.dll
```

**Error message:**
```
Object reference not set to an instance of an object.
```

**Stack trace:**
```
   at System.Uri.get_IriParsing() in /_/src/libraries/System.Private.Uri/src/System/Uri.cs:line 270
   at System.Uri.InitializeUri(ParsingError err, UriKind uriKind, UriFormatException& e) in /_/src/libraries/System.Private.Uri/src/System/UriExt.cs:line 90
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions) in /_/src/libraries/System.Private.Uri/src/System/UriExt.cs:line 38
   at System.Uri.CreateUri(Uri baseUri, String relativeUri, Boolean dontEscape) in /_/src/libraries/System.Private.Uri/src/System/Uri.cs:line 508
   at System.Runtime.Serialization.DataContracts.DataContract.GetDefaultDataContractNamespace(Type type) in /_/src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContract.cs:line 1524
   at System.Runtime.Serialization.DataContracts.DataContract.GetDCTypeXmlName(Type type, DataContractAttribute dataContractAttribute) in /_/src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContract.cs:line 1283
   at System.Runtime.Serialization.DataContracts.ClassDataContract.ClassDataContractCriticalHelper..ctor(Type type) in /_/src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/ClassDataContract.cs:line 621
   at System.Runtime.Serialization.DataContracts.DataContract.DataContractCriticalHelper.CreateDataContract(Type type) in /_/src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContract.cs:line 480
   at System.Runtime.Serialization.DataContracts.DataContract.DataContractCriticalHelper.CreateDataContract(Int32 id, RuntimeTypeHandle typeHandle, Type type) in /_/src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContract.cs:line 439
   at System.Runtime.Serialization.DataContractSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName, DataContractResolver dataContractResolver) in /_/src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializer.cs:line 468
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver) in /_/src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/XmlObjectSerializer.cs:line 356
   at Program.<<Main>$>g__TestExecutor20|0_21(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by jakobbotsch** [comment] 2023-10-07 07:42
Duplicate of #92990

**Closed by jakobbotsch** 2023-10-07 07:42 UTC
Labels: arch-arm64, area-Serialization, os-linux, os-mac-os-x, os-windows, JitStress, arch-x64, untriaged
