### ISSUE TITLE
ImageSharp produces a corrupted image on .NET 6 Preview 6

### ISSUE THREAD

**Issue by kerams** [dotnet/runtime#55866] opened 2021-07-17 10:38 UTC
### Description

Originally reported in https://github.com/SixLabors/ImageSharp/issues/1704.

Loading a PNG file and immediately saving it as Jpeg works as expected on .NET 5. However when I switch to `net6.0` in the csproj, only the top part of the image appears in the output jpeg file, the rest is black.

### Steps to Reproduce
Create s console C# application and reference ImageSharp 1.0.3. First run this with `net5.0` in the csproj, then compare the result to `net6.0`.

```csharp
using SixLabors.ImageSharp;
using System.IO;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            using var img = Image.Load("unknown.png");
            var fs = File.OpenWrite("unknown.jpeg");
            img.SaveAsJpeg(fs);
            fs.Flush();
            fs.Close();
        }
    }
}
```

Use this image
https://user-images.githubusercontent.com/5063478/126033585-4efb31ce-c231-4229-8412-68fb73950ffc.png

The result on 5.0.400-preview.21277.10 looks like the original image.

The result on 6.0.100-preview.6.21355.2 looks like this
https://user-images.githubusercontent.com/5063478/126033623-0f886133-bc0d-4449-8048-d5d29a0e377c.jpeg

### Configuration

<details>
  <summary>dotnet --info</summary>
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.6.21355.2
 Commit:    7f8e0d76c0

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.6.21355.2\

Host (useful for support):
  Version: 6.0.0-preview.7.21318.2
  Commit:  140120290a

.NET SDKs installed:
  5.0.400-preview.21277.10 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.6.21355.2 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.6.21355.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.6.21352.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.6.21353.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
</details>

### Regression?

Yes, works on 5.0.400-preview.21277.10.

**Comment by stephentoub** [comment] 2021-07-17 12:41
cc: @tannergooding

**Comment by lewing** [comment] 2021-07-19 00:12
We're looking into some mono image loading problems in ImageSharp that we bisected back to https://github.com/dotnet/runtime/pull/53644

cc @danroth27 @vargaz

**Comment by stephentoub** [comment] 2021-07-19 00:15
These looks suspect:
https://github.com/SixLabors/ImageSharp/blob/e8d39b87e4d14fcf52cac387a82f067283e6670e/src/ImageSharp/Formats/Png/PngDecoderCore.cs#L509-L514
https://github.com/SixLabors/ImageSharp/blob/e8d39b87e4d14fcf52cac387a82f067283e6670e/src/ImageSharp/Formats/Png/PngDecoderCore.cs#L580-L585

**Comment by stephentoub** [comment] 2021-07-19 00:29
> These look suspect

Indeed, if I make these changes:
```
D:\repos\ImageSharp\src\ImageSharp [master ≡]> git diff
diff --git a/src/ImageSharp/Formats/Png/PngDecoderCore.cs b/src/ImageSharp/Formats/Png/PngDecoderCore.cs
index de70a9dff..779341b1c 100644
--- a/src/ImageSharp/Formats/Png/PngDecoderCore.cs
+++ b/src/ImageSharp/Formats/Png/PngDecoderCore.cs
@@ -506,11 +506,15 @@ private void DecodePixelData<TPixel>(DeflateStream compressedStream, ImageFrame<
             while (this.currentRow < this.header.Height)
             {
                 Span<byte> scanlineSpan = this.scanline.GetSpan();
-                int bytesRead = compressedStream.Read(scanlineSpan, this.currentRowBytesRead, this.bytesPerScanline - this.currentRowBytesRead);
-                this.currentRowBytesRead += bytesRead;
-                if (this.currentRowBytesRead < this.bytesPerScanline)
+                while (this.currentRowBytesRead < this.bytesPerScanline)
                 {
-                    return;
+                    int bytesRead = compressedStream.Read(scanlineSpan, this.currentRowBytesRead, this.bytesPerScanline - this.currentRowBytesRead);
+                    if (bytesRead <= 0)
+                    {
+                        return;
+                    }
+
+                    this.currentRowBytesRead += bytesRead;
                 }

                 this.currentRowBytesRead = 0;
@@ -577,11 +581,15 @@ private void DecodeInterlacedPixelData<TPixel>(DeflateStream compressedStream, I

                 while (this.currentRow < this.header.Height)
                 {
-                    int bytesRead = compressedStream.Read(this.scanline.GetSpan(), this.currentRowBytesRead, bytesPerInterlaceScanline - this.currentRowBytesRead);
-                    this.currentRowBytesRead += bytesRead;
-                    if (this.currentRowBytesRead < bytesPerInterlaceScanline)
+                    while (this.currentRowBytesRead < bytesPerInterlaceScanline)
                     {
-                        return;
+                        int bytesRead = compressedStream.Read(this.scanline.GetSpan(), this.currentRowBytesRead, bytesPerInterlaceScanline - this.currentRowBytesRead);
+                        if (bytesRead <= 0)
+                        {
+                            break;
+                        }
+
+                        this.currentRowBytesRead += bytesRead;
                     }

                     this.currentRowBytesRead = 0;
```

Before this change, I could repro with the example in this issue.  After this issue, it appears to work correctly.

**Comment by adamsitnik** [comment] 2021-07-19 10:21
Since this was caused by a breaking change that we have introduced on purpose (https://github.com/dotnet/docs/issues/24649) and fixed by @stephentoub in https://github.com/SixLabors/ImageSharp/pull/1707, I am closing the issue.

**Closed by adamsitnik** 2021-07-19 10:21 UTC
Labels: area-System.IO

**Comment by JimBobSquarePants** [comment] 2021-07-19 10:31
Thanks for the swift diagnosis and fix!
