### ISSUE TITLE
Test failure: ArgumentValidation_ThrowsExpectedException

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#56925] opened 2021-08-05 18:47 UTC
Test: `System.Net.Quic.Tests.MsQuicQuicStreamConformanceTests.ArgumentValidation_ThrowsExpectedException`

Day | Run | OS
-----|-----|-----
8/5 | PR #56874 | ubuntu.1604.amd64.open.rt
8/2 | PR #56717 | ubuntu.1604.amd64.open.rt
7/28 | PR #56466 | ubuntu.1604.amd64.open.rt
7/26 | PR #56255 | ubuntu.1604.amd64.open.svc
7/21 | PR #56086 | ubuntu.1604.amd64.open.rt

```
System.Net.Quic.QuicException : Connection has been shutdown by transport. Error Code: CONNECTION_REFUSED
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventShutdownInitiatedByTransport(State state, ConnectionEvent& connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicConnection.cs:line 249
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.NativeCallbackHandler(IntPtr connection, IntPtr context, ConnectionEvent& connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicConnection.cs:line 684
--- End of stack trace from previous location ---
   at System.Net.Quic.Tests.QuicStreamConformanceTests.<>c__DisplayClass7_0.<<CreateConnectedStreamsAsync>b__1>d.MoveNext() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamConnectedStreamConformanceTests.cs:line 93
--- End of stack trace from previous location ---
   at System.IO.Tests.StreamConformanceTests.WhenAllOrAnyFailed(Task task1, Task task2) in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 567
   at System.Net.Quic.Tests.QuicStreamConformanceTests.CreateConnectedStreamsAsync() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamConnectedStreamConformanceTests.cs:line 78
   at System.IO.Tests.ConnectedStreamConformanceTests.ArgumentValidation_ThrowsExpectedException() in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 1605
--- End of stack trace from previous location ---
```

**Comment by MihaZupan** [comment] 2021-08-05 18:47
@wfurt I assume this is the same issue as #56875?

**Comment by wfurt** [comment] 2021-08-06 00:19
yes, very likely

**Comment by ManickaP** [comment] 2021-08-10 17:14
Triage: closing as a dupe, we can reopen if it turns out it isn't.
Duplicate of #55979

**Closed by ManickaP** 2021-08-10 17:14 UTC
Labels: test-run-core, area-System.Net.Quic

**Comment by karelz** [comment] 2021-08-13 09:23
Duplicate of #55979
