### ISSUE TITLE
ilasm generating incorrect constant value

### ISSUE THREAD

**Issue by dseefeld** [dotnet/runtime#45419] opened 2020-12-01 17:27 UTC
### Description

Assembly round-tripped with ildasm/ilasm are different than the original assembly.  A constant value is changed in round-tripping.

### Differences shown below.  

(Red is from the original assembly, green is from the round-tripped assembly)

**Nuget Package:** Microsoft.AspNETCore.App.Ref,5.0.0
   
 - Microsoft.Net.Http.Headers.dll

```diff
 {
        public static class HeaderQuality
        {
-               public const double Match = 1.0;
+               public const double Match = double.Epsilon;

                public const double NoMatch = 0.0;
        }
```

**Comment by jkotas** [comment] 2020-12-01 21:01
cc @briansull

**Comment by briansull** [comment] 2020-12-09 23:01
I believe that this was already reported two years ago and was traced back to a change in behavior the CRT.
And the risk\reward  at the time lead to it being a won't fix.

**Comment by TIHan** [comment] 2023-08-03 01:46
I'm not able to reproduce this issue. I pulled the nuget package `Microsoft.AspNETCore.App.Ref,5.0.0` specifically and did a full roundtrip on `Microsoft.Net.Http.Headers.dll` with the latest ilasm/ildasm, and the const `Match` remained as 1.0.

**Closed by TIHan** 2023-08-03 01:46 UTC
Labels: area-ILTools-coreclr, Priority:2
