### ISSUE TITLE
Misleading error message for invalid regex pattern

### ISSUE THREAD

**Issue by GSPP** [dotnet/runtime#62631] opened 2021-12-10 11:30 UTC
While debugging an error that I had made writing a regex, I encountered a slightly misleading error message for that particular error. Consider the regex `(?<a.>)`. It contains the group named `a.` which is invalid. The error message is:

    System.Text.RegularExpressions.RegexParseException: 'Invalid pattern '(?<a.>)' at offset 4. Invalid group name: Group names must begin with a word character.'

The message speaks about the beginning of that group name but the beginning is actually OK. Debugging this costs me a few minutes of trial and error because I was only looking at the beginning of that name.

Repro code:

    new Regex("(?<a.>)");

This is on .NET 5.

**Comment by stephentoub** [comment] 2021-12-10 13:58
Looks like a duplicate of https://github.com/dotnet/runtime/issues/39075 (2nd case mentioned there)

**Closed** 2021-12-10 15:56 UTC
Labels: area-System.Text.RegularExpressions, untriaged

**Comment by GSPP** [comment] 2021-12-12 10:59
I forgot to search... Sorry about that.
