### ISSUE TITLE
LDAP Pagination fails with "System.DirectoryServices.Protocols.LdapException: The LDAP server returned an unknown error" on LINUX host

### ISSUE THREAD

**Issue by samkit3198** [dotnet/runtime#52100] opened 2021-04-30 08:58 UTC
I am trying to paginate the LDAP request. The piece of code works fine on windows host but breaks on linux host. I am using v5.0.0 of System.DirectoryServices.Protocols and .NET SDK 5.0.100. Here is the source code:

           `List<SearchResponse> searchResponseResult = new List<SearchResponse>();
            Log.Information($"Executing LDAP query with server:{query.Server}, filter:{query.SearchFilter}, base:{query.SearchBase}, props:[{string.Join(";", query.Props)}, user:{query.User}, pageSize:{query.PageSize}");
            
            // LDAP search controls
            PageResultRequestControl pageRequestControl = new PageResultRequestControl(query.PageSize);
            SearchOptionsControl searchOptionsControl = new SearchOptionsControl(SearchOption.DomainScope);
            
            var searchRequest = new SearchRequest(query.SearchBase, query.SearchFilter, SearchScope.Subtree, query.Props);
            searchRequest.Controls.Add(pageRequestControl);
            searchRequest.Controls.Add(searchOptionsControl);
            
            // paginating response
            var pages = 0;
            while (true)
            {
                ++pages;
                var searchResponse = (SearchResponse) connection.SendRequest(searchRequest);
                if(!(searchResponse is SearchResponse))
                    throw new Exception($"Invalid search response: {searchResponse}");
                searchResponseResult.Add(searchResponse);
                foreach(var control in searchResponse.Controls)
                {
                    if (control is PageResultResponseControl)
                    {
                        pageRequestControl.Cookie = ((PageResultResponseControl) control).Cookie;
                        break;
                    }
                }
                
                if (pageRequestControl.Cookie.Length == 0)
                {
                    Log.Warning($"Exited ldap search with cookie = 0 and page count = {pages}");
                    break;
                }
            }
            return searchResponseResult;`

Is this a cross platform issue?

**Comment by iinuwa** [comment] 2021-06-24 20:17
@samkit3198, are you setting `SessionOptions.ProtocolVersion =3` explicitly on your `LdapConnection`? OpenLDAP, the underlying library for System.DirectoryServices.Protocols on Linux, defaults to version 2, which doesn't support extra controls like paging.

**Comment by iinuwa** [comment] 2021-06-24 21:41
I confirmed that this snippet works on .NET 5.0 with System.DirectoryServices.Protocols 5.0.0 (when using the correct values for our AD instance). Commenting out the line that sets `ProtocolVersion` causes an `LdapException`.

```csharp
using System;
using System.Collections.Generic;
using System.DirectoryServices.Protocols;
using System.Net;

var query = new {
    Server = new LdapDirectoryIdentifier("ldap.example.org", 389),
    SearchFilter = "cn=a*",
    SearchBase = "dc=example,dc=org",
    Props = new List<string>() { "cn", "mail" },
    PageSize = 15,
    User = "admin",
    Password = "password",
};

// Set up Connection
var ldapConnection = new LdapConnection(query.Server, new NetworkCredential(query.User, query.Password));
ldapConnection.SessionOptions.ProtocolVersion = 3;
List<SearchResponse> searchResponseResult = new List<SearchResponse>();
Console.WriteLine($"Executing LDAP query with server:{query.Server}, filter:{query.SearchFilter}, base:{query.SearchBase}, props:[{string.Join(";", query.Props)}, user:{query.User}, pageSize:{query.PageSize}");

// LDAP search controls
PageResultRequestControl pageRequestControl = new PageResultRequestControl(query.PageSize);
SearchOptionsControl searchOptionsControl = new SearchOptionsControl(SearchOption.DomainScope);

var searchRequest = new SearchRequest(query.SearchBase, query.SearchFilter, SearchScope.Subtree, string.Join(' ', query.Props));
searchRequest.Controls.Add(pageRequestControl);
searchRequest.Controls.Add(searchOptionsControl);

// paginating response
var pages = 0;
while (true)
{
    ++pages;
    var searchResponse = (SearchResponse) ldapConnection.SendRequest(searchRequest);
    if(!(searchResponse is SearchResponse))
        throw new Exception($"Invalid search response: {searchResponse}");
    searchResponseResult.Add(searchResponse);
    foreach(var control in searchResponse.Controls)
    {
        if (control is PageResultResponseControl)
        {
            pageRequestControl.Cookie = ((PageResultResponseControl) control).Cookie;
            break;
        }
    }

    if (pageRequestControl.Cookie.Length == 0)
    {
        Console.WriteLine($"Exited ldap search with cookie = 0 and page count = {pages}");
        break;
    }
}

foreach(var r in searchResponseResult)
{
    foreach(SearchResultEntry entry in r.Entries)
    {
        Console.WriteLine("{0}:\t{1}", ((DirectoryAttribute)entry.Attributes["cn"])?[0], ((DirectoryAttribute)entry.Attributes["mail"])?[0]);
    }
}
```

On `main`, the error message says that it's not supported, which clued me into the protocol version. Maybe we need to ensure that the protocol version gets set to 3 by default?

**Comment by joperezr** [comment] 2021-08-05 17:21
@iinuwa thanks so much for investigating this and figuring out what the problem was! Changing the default protocol version set by the library seems a significant breaking change, which I wouldn't change this late in the release cycle but we can revisit this on 7.0 if it is still desired.

Given the initial question on this issue is resolved now, I'll go ahead and close this issue for now. @samkit3198 if you are able to try @iinuwa suggestion and for some reason it doesn't work for you, please let us know and we can reopen the issue.

**Closed by joperezr** 2021-08-05 17:21 UTC
Labels: bug, area-System.DirectoryServices, os-linux
