### ISSUE TITLE
[HTTP] Metrics test fails on Mac locally

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#91721] opened 2023-09-07 10:19 UTC
**HttpMetricsTest_Http11_Async_HttpMessageInvoker.RequestDuration_ConnectionClosedWhileReceivingHeaders_Recorded**

Fails for me locally on each run. MacOS Ventura Version 13.5 (22G74) x64

```
System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async_HttpMessageInvoker.RequestDuration_ConnectionClosedWhileReceivingHeaders_Recorded [FAIL]
        Assert.Contains() Failure
        Not found: HttpRequestException
        In value:  String[] ["TaskCanceledException", "response_ended"]
        Stack Trace:
          /Users/manicka/Repositories/runtime/src/libraries/System.Net.Http/tests/FunctionalTests/MetricsTest.cs(103,0): at System.Net.Http.Functional.Tests.HttpMetricsTestBase.VerifyRequestDuration(String instrumentName, Double measurement, KeyValuePair`2[] tags, Uri uri, Version protocolVersion, Nullable`1 statusCode, String method, String[] acceptedErrorReasons)
          /Users/manicka/Repositories/runtime/src/libraries/System.Net.Http/tests/FunctionalTests/MetricsTest.cs(79,0): at System.Net.Http.Functional.Tests.HttpMetricsTestBase.VerifyRequestDuration(Measurement`1 measurement, Uri uri, Version protocolVersion, Nullable`1 statusCode, String method, String[] acceptedErrorReasons)
          /Users/manicka/Repositories/runtime/src/libraries/System.Net.Http/tests/FunctionalTests/MetricsTest.cs(817,0): at System.Net.Http.Functional.Tests.HttpMetricsTest_Http11.<>c__DisplayClass4_0.<<RequestDuration_ConnectionClosedWhileReceivingHeaders_Recorded>b__0>d.MoveNext()
          --- End of stack trace from previous location ---
          /Users/manicka/Repositories/runtime/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(120,0): at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
          --- End of stack trace from previous location ---
          /Users/manicka/Repositories/runtime/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(90,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
          /Users/manicka/Repositories/runtime/src/libraries/Common/tests/System/Net/Http/GenericLoopbackServer.cs(44,0): at System.Net.Test.Common.LoopbackServerFactory.<>c__DisplayClass6_0.<<CreateClientAndServerAsync>b__0>d.MoveNext()
          --- End of stack trace from previous location ---
          /Users/manicka/Repositories/runtime/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs(107,0): at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
          /Users/manicka/Repositories/runtime/src/libraries/System.Net.Http/tests/FunctionalTests/MetricsTest.cs(801,0): at System.Net.Http.Functional.Tests.HttpMetricsTest_Http11.RequestDuration_ConnectionClosedWhileReceivingHeaders_Recorded()
          --- End of stack trace from previous location ---
```

@antonfirsov Let me know if you need logs or anything, I can help debug this.

**Comment by wfurt** [comment] 2023-09-11 23:28
it fails for me as well. After the first request I see client kicking retry. The test works for me when executed in isolation as it would eventually get the OCE -> probably sign that it does not work as expected.

**Comment by MihaZupan** [comment] 2023-10-19 11:11
Duplicate of #93627

**Closed by MihaZupan** 2023-10-19 11:11 UTC
Labels: area-System.Net.Http
