### ISSUE TITLE
ParallelLoopState.ShouldExitCurrentIteration does not match true later than true is assigned

### ISSUE THREAD

**Issue by NikVladi** [dotnet/runtime#73607] opened 2022-08-09 02:45 UTC
### Description

ParallelLoopState.ShouldExitCurrentIteration does not match true later than true is assigned.
If you run this code many times, you may see this behavior in some cases. Is this a bug? Why does it work like this?

### Reproduction Steps

```
void MyMethod(int i, ParallelLoopState pls)
{
    Thread.Sleep(1000);
    if (i == 5)
    {     
        pls.Break();
    }
    Console.WriteLine($"{i}, {DateTime.Now}, {pls.ShouldExitCurrentIteration}");
}


try
{
    Parallel.For(1, 101, MyMethod);
}
catch
{

}

//12:29:24 True but 12:29:25 False

/*4, 2022 - 08 - 09 12:29:23, False
.................................
41, 2022 - 08 - 09 12:29:24, True
5, 2022 - 08 - 09 12:29:24, False
17, 2022 - 08 - 09 12:29:24, False
32, 2022 - 08 - 09 12:29:24, False
56, 2022 - 08 - 09 12:29:24, False
20, 2022 - 08 - 09 12:29:24, False
92, 2022 - 08 - 09 12:29:24, False
53, 2022 - 08 - 09 12:29:24, False
8, 2022 - 08 - 09 12:29:24, False
35, 2022 - 08 - 09 12:29:24, True
38, 2022 - 08 - 09 12:29:24, True
74, 2022 - 08 - 09 12:29:24, True // <<<===
3, 2022 - 08 - 09 12:29:25, False*/ // <<<===
```

### Expected behavior

Аter setting ShouldExitCurrentIteration True ShouldExitCurrentIteration should always be True.

### Actual behavior

Аter setting ShouldExitCurrentIteration True ShouldExitCurrentIteration is False.

**Comment by theodorzoulias** [comment] 2022-08-09 20:04
You could try enclosing the `Console.WriteLine` line in a `lock` block, so that each thread reports its current state in a synchronized fashion. My guess is that you won't be able to reproduce the observed behavior.

**Comment by svick** [comment] 2022-08-19 11:06
This seems to be a confusion between `Break()` and `Stop()`. [`Break()` is documented as](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.parallelloopstate.break?view=net-6.0) (emphasis mine):

> Communicates that the Parallel loop should **cease execution of iterations beyond the current iteration** at the system's earliest convenience.

So if you `Break()` when `i == 5`, it is expected that `ShouldExitCurrentIteration` reports `false` for `i == 3`, even after `Break()` has been called.

If you want to stop the whole loop, [use `Stop()`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.parallelloopstate.stop?view=net-6.0):

> Communicates that the Parallel loop should cease execution at the system's earliest convenience.

**Comment by buyaa-n** [comment] 2022-08-25 00:10
@NikVladi looks @svick's comment answers your question completely, can we close the issue? Please let us know if you have any other question/comment

**Closed** 2022-09-08 03:24 UTC
Labels: question, area-System.Threading.Tasks, no-recent-activity, needs-author-action
