### ISSUE TITLE
chrome-DebuggerTests.EvaluateOnCallFrameTests crashing in CI

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#89470] opened 2023-07-25 20:31 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=348001
Build error leg or test failing: chrome-DebuggerTests.EvaluateOnCallFrameTests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/89216

## Error Message

```json
{
  "ErrorMessage": "chrome-DebuggerTests.EvaluateOnCallFrameTests",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

Later in the log I see:
```
The active test run was aborted. Reason: Test host process crashed
```

This test seems to have a rather high failure rate: https://dev.azure.com/dnceng-public/public/_build/results?buildId=348001&view=ms.vss-test-web.build-test-results-tab&runId=7384340&resultId=100284&paneView=history

I can go as far back as we have build history and see this test failing in the same way.

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=348001
**Error message validated:** `chrome-DebuggerTests.EvaluateOnCallFrameTests`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 7/25/2023 8:32:13 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[352914](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352914)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352914&view=ms.vss-test-web.build-test-results-tab&runId=7413934&resultId=100301)|dotnet/runtime#89329|
|[352652](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352652)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352652&view=ms.vss-test-web.build-test-results-tab&runId=7408236&resultId=100283)|dotnet/runtime#89504|
|[352517](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352517)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352517&view=ms.vss-test-web.build-test-results-tab&runId=7405068&resultId=100297)|dotnet/runtime#89299|
|[352487](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352487)|dotnet/runtime|[DebuggerTests.EvaluateOnCallFrameTests.DebuggerTests.EvaluateOnCallFrameTests.EvaluateExpressionsWithDeepMemberAccesses](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352487&view=ms.vss-test-web.build-test-results-tab&runId=7403790&resultId=100246)|dotnet/runtime#89296|
|[352442](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352442)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352442&view=ms.vss-test-web.build-test-results-tab&runId=7402182&resultId=100282)|dotnet/runtime#88735|
|[352436](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352436)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352436&view=ms.vss-test-web.build-test-results-tab&runId=7402222&resultId=100265)|dotnet/runtime#88735|
|[351993](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351993)|dotnet/runtime|[DebuggerTests.EvaluateOnCallFrameTests.DebuggerTests.EvaluateOnCallFrameTests.NegativeTestsInStaticMethod](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351993&view=ms.vss-test-web.build-test-results-tab&runId=7390810&resultId=100254)|dotnet/runtime#89329|
|[351833](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351833)|dotnet/runtime|[DebuggerTests.EvaluateOnCallFrameTests.DebuggerTests.EvaluateOnCallFrameTests.EvaluateTypeInstanceMembers](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351833&view=ms.vss-test-web.build-test-results-tab&runId=7387320&resultId=100232)|dotnet/runtime#88735|
|[348001](https://dev.azure.com/dnceng-public/public/_build/results?buildId=348001)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=348001&view=ms.vss-test-web.build-test-results-tab&runId=7384340&resultId=100284)|dotnet/runtime#89216|
|[351450](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351450)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351450&view=ms.vss-test-web.build-test-results-tab&runId=7378470&resultId=100280)|dotnet/runtime#89217|
|[351409](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351409)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351409&view=ms.vss-test-web.build-test-results-tab&runId=7377668&resultId=100299)|dotnet/runtime#89441|
|[351340](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351340)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351340&view=ms.vss-test-web.build-test-results-tab&runId=7376412&resultId=100270)|dotnet/runtime#89299|
|[351270](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351270)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351270&view=ms.vss-test-web.build-test-results-tab&runId=7374934&resultId=100287)|dotnet/runtime#89432|
|[351073](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351073)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351073&view=ms.vss-test-web.build-test-results-tab&runId=7369684&resultId=100352)|dotnet/runtime#88279|
|[351024](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351024)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351024&view=ms.vss-test-web.build-test-results-tab&runId=7368622&resultId=100277)||
|[350721](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350721)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350721&view=ms.vss-test-web.build-test-results-tab&runId=7362472&resultId=100300)|dotnet/runtime#89217|
|[350621](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350621)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350621&view=ms.vss-test-web.build-test-results-tab&runId=7359648&resultId=100280)|dotnet/runtime#89387|
|[350554](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350554)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=350554&view=ms.vss-test-web.build-test-results-tab&runId=7357826&resultId=100296)|dotnet/runtime#89217|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|7|18|18|

**Comment by lewing** [comment] 2023-07-26 22:44
closing as a duplicate of https://github.com/dotnet/runtime/issues/89409 (which is more general)

**Closed by lewing** 2023-07-26 22:44 UTC
Labels: arch-wasm, blocking-clean-ci, area-Debugger-mono, Known Build Error
