### ISSUE TITLE
System.DirectoryServices.Protocols.Tests crashes sometimes on Linux

### ISSUE THREAD

**Issue by safern** [dotnet/runtime#37911] opened 2020-06-15 17:56 UTC
### Builds
|Build|Pull Request | Test Failure Count|
| --- | --- | --- |
|[#687604](https://dev.azure.com/dnceng/public/_build/results?buildId=687604)|Rolling|1|
|[#687783](https://dev.azure.com/dnceng/public/_build/results?buildId=687783)|Rolling|1|
### Configurations
- net5.0-Linux-Release-x64-CoreCLR_release-(Fedora.32.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-32-helix-20200512010618-efb9f14
- net5.0-Linux-Release-x64-CoreCLR_release-Ubuntu.1804.Amd64.Open
### Helix Logs
|Build|Pull Request|Console|Core|Test Results|Run Client|
| --- | --- | --- | --- | --- | --- |
|[#687604](https://dev.azure.com/dnceng/public/_build/results?buildId=687604)|Rolling|[console.log](https://helix.dot.net/api/2019-06-17/jobs/72981793-0721-43fc-ab94-b46a425936e4/workitems/System.DirectoryServices.Protocols.Tests/files/console.c4e0853e.log)|[core](https://helix.dot.net/api/2019-06-17/jobs/72981793-0721-43fc-ab94-b46a425936e4/workitems/System.DirectoryServices.Protocols.Tests/files/core.1000.23)||[run_client.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-72981793072143fcab/System.DirectoryServices.Protocols.Tests/1f769d72-9bce-4220-9877-9719fa1c3bcb.log?sv=2019-02-02&se=2020-07-05T09%3A45%3A45Z&sr=c&sp=rl&sig=briPC%2FpVyqtNnp%2F9Az26T7gLS%2BzpH9LjdTtZPMswoA8%3D)|
|[#687783](https://dev.azure.com/dnceng/public/_build/results?buildId=687783)|Rolling|[console.log](https://helix.dot.net/api/2019-06-17/jobs/bcf579fe-2721-470d-a987-1e906d9094fd/workitems/System.DirectoryServices.Protocols.Tests/files/console.3c8ddf1c.log)|||[run_client.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-bcf579fe2721470da9/System.DirectoryServices.Protocols.Tests/f1035557-8c34-43a6-89fa-bbb66bcdf0c3.log?sv=2019-02-02&se=2020-07-05T13%3A24%3A53Z&sr=c&sp=rl&sig=EQd13MY6Z4wU0xsNvyQ1EkKqlr6aEDoXRrX5PzUAt4w%3D)|

Doesn't seem to happen that often, but there are 2 builds on the last 100 that hit it and there is one that actually collected a dump so that might help the investigation.

**Comment by safern** [comment] 2020-06-15 17:57
cc: @joperezr

**Comment by joperezr** [comment] 2020-06-15 18:18
Thanks for logging this, I'll take a look.

**Comment by ManickaP** [comment] 2020-06-30 08:39
Hit in https://github.com/dotnet/runtime/pull/38453 [AzDO](https://dev.azure.com/dnceng/public/_build/results?buildId=709999&view=ms.vss-test-web.build-test-results-tab&runId=22007518&resultId=181216&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab)

**Comment by jkotas** [comment] 2020-07-18 12:53
Failed in https://github.com/dotnet/runtime/pull/39594

**Comment by danmosemsft** [comment] 2020-08-07 21:09
Logs are gone. Without further evidence, we can assume this is https://github.com/dotnet/runtime/issues/39009

**Comment by danmosemsft** [comment] 2020-08-07 21:10
Duplicate of https://github.com/dotnet/runtime/issues/39009

**Closed by danmosemsft** 2020-08-07 21:10 UTC
Labels: area-System.DirectoryServices, blocking-clean-ci
