### ISSUE TITLE
Expose a property in System.Net.Http.HttpResponseMessage which will give the remote ip it connects to

### ISSUE THREAD

**Issue by shine17** [dotnet/runtime#38407] opened 2020-06-25 18:37 UTC
Currently the HttpResponseMessage doesn't expose a property which tells which remote ip it gets response from. There is no way of getting the ip address when TCP connection established. It will be good if we can expose a property in HttpResponseMessage which tells about the ip it get response. Node js https library have that, I think dotnet also should have this exposed. 

```
 var http = require('https');
  http.get('https://www.google.com', function(res) {
    console.log('remote IP: ' + res.connection.remoteAddress);
    ...
  });
```

**Comment by scalablecory** [comment] 2020-07-02 16:14
@shine17 do you have a proposed API? there are a few different ways we might do this -- we're generally inclined to not introduce a new API for this as it would introduce overhead for all users, not just those who would use it. But, there may be other ways (such as using System.Net.Connections to filter on connect()).

**Comment by karelz** [comment] 2022-01-06 17:19
Duplicate of #63159

**Comment by karelz** [comment] 2022-01-06 17:19
(it has more details, so closing this issue)

**Closed by karelz** 2022-01-06 17:19 UTC
Labels: area-System.Net.Http
