### ISSUE TITLE
SPMI failing in CI

### ISSUE THREAD

**Issue by SingleAccretion** [dotnet/runtime#68137] opened 2022-04-17 19:04 UTC
Sample runs:

1) Replay: https://dev.azure.com/dnceng/public/_build/results?buildId=1722826&view=results.
2) Diffs: https://dev.azure.com/dnceng/public/_build/results?buildId=1722827&view=results (note how both the base and diff Jits are failing).

Side note: it seems suboptimal that failures like these do not show up on GH as "red CI".

@dotnet/jit-contrib

**Comment by jakobbotsch** [comment] 2022-04-18 11:20
@BruceForstall with the change made in #61699, can we remove the `shouldContinueOnError: true` that we discussed in #60594 so that the pipeline is properly marked red on failures?

**Comment by jakobbotsch** [comment] 2022-04-18 11:52
I am occasionally hitting AV inside `memcpy` in `repGetStringLiteral`, so this is probably caused by #68055. cc @EgorBo

**Comment by EgorBo** [comment] 2022-04-18 12:28
> I am occasionally hitting AV inside `memcpy` in `repGetStringLiteral`, so this is probably caused by #68055. cc @EgorBo

will file a fix in a moment, sorry

**Comment by jakobbotsch** [comment] 2022-04-19 10:35
Fixed by #68161

**Closed by jakobbotsch** 2022-04-19 10:35 UTC
Labels: area-CodeGen-coreclr
