### ISSUE TITLE
System.Uri and System.UriBuilder seems to fail with accented characters

### ISSUE THREAD

**Issue by MathieuGirard** [dotnet/runtime#36365] opened 2020-05-13 19:35 UTC
new UriBuilder {Host="", Path="/é", Scheme="file"}.Uri

In .Net frame work:
You obtain : [file:///é]

In .Net core:
You obtain : [file://%2fé/é]

Escaping the text does not work either: new Uri("file://" + Uri.EscapeUriString("/é")) also fails in .NetCore but not in framework...

**Comment by davidsh** [comment] 2020-05-13 19:40
@MihaZupan

**Comment by MihaZupan** [comment] 2020-05-13 21:33
Thanks for the report. This is a known bug that will be fixed for .NET 5.

**Comment by MihaZupan** [comment] 2020-05-13 21:33
Duplicate of #1061

**Closed by MihaZupan** 2020-05-13 21:33 UTC
Labels: area-System.Net, untriaged
