### ISSUE TITLE
[WASM][aot] System.Tests.UriCreateStringTests.Path_Query_Fragment

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [dotnet/runtime#105823] opened 2024-08-01 16:50 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=762134
Build error leg or test failing: System.Tests.UriCreateStringTests.Path_Query_Fragment
Pull request: https://github.com/dotnet/runtime/pull/105671

```
[23:21:54] info: [FAIL] System.Tests.UriCreateStringTests.Path_Query_Fragment(uriString: "http://host/path?query    \t \r \n  \t \n \r", path: "/path", query: "?query", fragment: "")
[23:21:54] info: Assert.Equal() Failure: Exception thrown during comparison
[23:21:54] info:                        ↓ (pos 0)
[23:21:54] info: Expected: <generated> [null, "path"]
[23:21:54] info: Actual:   string[]    ["/", "path"]
[23:21:54] info:                        ↑ (pos 0)
[23:21:54] info: ---- System.NullReferenceException : Object reference not set to an instance of an object.
[23:21:54] info:    at System.Object.InvokeStub_UriCreateStringTests.Path_Query_Fragment(Object , Span`1 )
[23:21:54] info:    at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object , BindingFlags , Binder , Object[] , CultureInfo )
[23:21:54] info: ----- Inner Stack Trace -----
```

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "at System.Object.InvokeStub_UriCreateStringTests.Path_Query_Fragment(Object , Span`1 )",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=762134
**Error message validated:** `[at System.Object.InvokeStub_UriCreateStringTests.Path_Query_Fragment(Object , Span`1 )`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 8/1/2024 4:52:27 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[762134](https://dev.azure.com/dnceng-public/public/_build/results?buildId=762134)|dotnet/runtime|[WasmTestOnV8-ST-System.Runtime.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=762134&view=ms.vss-test-web.build-test-results-tab&runId=19365124&resultId=109439)|dotnet/runtime#105671|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|1|

**Comment by lewing** [comment] 2024-08-01 18:32
@ilonatommy this reminds me of the other failures on v8

**Comment by ilonatommy** [comment] 2024-08-02 07:05
Yes, it looks like a duplicate of https://github.com/dotnet/runtime/issues/105362. I'll update the pattern to not to include the specific test name but the test collection (System.Tests).

**Closed** 2024-08-02 07:08 UTC
Labels: blocking-clean-ci, Known Build Error, needs-area-label
