### ISSUE TITLE
[release/7.0][wasm] `System.Diagnostics.Tracing.Tests` failing with chrome ` Expected 210 assets to be downloaded, but only finished 211`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#82271] opened 2023-02-16 23:28 UTC
[Rolling build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=173848&view=results), and [log](https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-heads-release-70-5a71e1721e634cb890/WasmTestOnBrowser-System.Diagnostics.Tracing.Tests/1/console.177a6515.log?helixlogtype=result):

```
[02:30:15] info: browser: [main] Console websocket connected.
[02:30:18] fail: [out of order message from the browser]: http://127.0.0.1:49254/managed/msdia140.dll - Failed to load resource: net::ERR_CACHE_READ_FAILURE
[02:30:27] fail: [out of order message from the browser]: http://127.0.0.1:49254/dotnet.js 4:47754 Uncaught Error: Assert failed: Expected 210 assets to be downloaded, but only finished 211
[02:30:27] fail: [out of order message from the browser]: http://127.0.0.1:49254/dotnet.js 4:47754 Uncaught Error: Assert failed: Expected 210 assets to be downloaded, but only finished 211
[02:30:27] fail: [out of order message from the browser]: http://127.0.0.1:49254/test-main.js 342:0 Uncaught Error: Assert failed: Expected 210 assets to be downloaded, but only finished 211
[02:30:27] fail: MONO_WASM: onRuntimeInitializedAsync() failed: {}
[02:30:27] fail: MONO_WASM: Stacktrace: 

[02:30:27] fail: Error: Assert failed: Expected 210 assets to be downloaded, but only finished 211
    at us (http://127.0.0.1:49254/dotnet.js:5:47755)
    at async hc (http://127.0.0.1:49254/dotnet.js:5:96851)
[02:30:27] fail: Error: Assert failed: Expected 210 assets to be downloaded, but only finished 211
    at us (http://127.0.0.1:49254/dotnet.js:5:47755)
    at async hc (http://127.0.0.1:49254/dotnet.js:5:96851)
[02:30:27] fail: Error: Assert failed: Expected 210 assets to be downloaded, but only finished 211
    at us (http://127.0.0.1:49254/dotnet.js:5:47755)
    at async hc (http://127.0.0.1:49254/dotnet.js:5:96851)
[02:30:27] fail: Error: Assert failed: Expected 210 assets to be downloaded, but only finished 211
    at us (http://127.0.0.1:49254/dotnet.js:5:47755)
    at async hc (http://127.0.0.1:49254/dotnet.js:5:96851)
[02:30:27] fail: Error: Assert failed: Expected 210 assets to be downloaded, but only finished 211
    at us (http://127.0.0.1:49254/dotnet.js:5:47755)
    at async hc (http://127.0.0.1:49254/dotnet.js:5:96851)
[02:30:27] fail: Error: Assert failed: Expected 210 assets to be downloaded, but only finished 211
    at us (http://127.0.0.1:49254/dotnet.js:5:47755)
    at async hc (http://127.0.0.1:49254/dotnet.js:5:96851)
[02:30:27] fail: Error: Assert failed: Expected 210 assets to be downloaded, but only finished 211
    at us (http://127.0.0.1:49254/dotnet.js:5:47755)
    at async hc (http://127.0.0.1:49254/dotnet.js:5:96851)
[02:30:27] info: WASM EXIT 1
```

Hit on PRs too.

cc @pavelsavara @maraf 

### Known Issue Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorPattern": ".*Error: Assert failed.*Expected.*assets to be downloaded, but only finished.*",
  "BuildRetry": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[201611](https://dev.azure.com/dnceng-public/public/_build/results?buildId=201611)|dotnet/runtime|[Workloads-Webcil-Wasm.Build.Tests.WasmTemplateTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=201611&view=ms.vss-test-web.build-test-results-tab&runId=3774324&resultId=100095)||
|[197972](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197972)|dotnet/runtime|[WasmTestOnBrowser-System.Diagnostics.Tracing.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197972&view=ms.vss-test-web.build-test-results-tab&runId=3727938&resultId=186502)|dotnet/runtime#82432|
|[197919](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197919)|dotnet/runtime|[WasmTestOnBrowser-System.Diagnostics.Tracing.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197919&view=ms.vss-test-web.build-test-results-tab&runId=3726842&resultId=186502)|dotnet/runtime#82192|
|[197634](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197634)|dotnet/runtime|[WasmTestOnBrowser-System.Diagnostics.Tracing.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197634&view=ms.vss-test-web.build-test-results-tab&runId=3724339&resultId=186502)|dotnet/runtime#82851|
|[197262](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197262)|dotnet/runtime|[WasmTestOnBrowser-System.Diagnostics.Tracing.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197262&view=ms.vss-test-web.build-test-results-tab&runId=3718745&resultId=186502)|dotnet/runtime#82208|
|[197257](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197257)|dotnet/runtime|[WasmTestOnBrowser-System.Diagnostics.Tracing.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197257&view=ms.vss-test-web.build-test-results-tab&runId=3718572&resultId=186502)|dotnet/runtime#82174|
|[197250](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197250)|dotnet/runtime|[WasmTestOnBrowser-System.Diagnostics.Tracing.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197250&view=ms.vss-test-web.build-test-results-tab&runId=3718245&resultId=186502)|dotnet/runtime#82089|
|[197231](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197231)|dotnet/runtime|[WasmTestOnBrowser-System.Diagnostics.Tracing.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=197231&view=ms.vss-test-web.build-test-results-tab&runId=3718046&resultId=186502)||
|[193598](https://dev.azure.com/dnceng-public/public/_build/results?buildId=193598)|dotnet/runtime|[WasmTestOnBrowser-System.Diagnostics.Tracing.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=193598&view=ms.vss-test-web.build-test-results-tab&runId=3677211&resultId=186502)|dotnet/runtime#82192|
|[192196](https://dev.azure.com/dnceng-public/public/_build/results?buildId=192196)|dotnet/runtime|[WasmTestOnBrowser-System.Diagnostics.Tracing.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=192196&view=ms.vss-test-web.build-test-results-tab&runId=3660424&resultId=186502)|dotnet/runtime#82921|
|[191057](https://dev.azure.com/dnceng-public/public/_build/results?buildId=191057)|dotnet/runtime|[WasmTestOnBrowser-System.Diagnostics.Tracing.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=191057&view=ms.vss-test-web.build-test-results-tab&runId=3645794&resultId=186502)|dotnet/runtime#82174|
|[188784](https://dev.azure.com/dnceng-public/public/_build/results?buildId=188784)|dotnet/runtime|[WasmTestOnBrowser-System.Diagnostics.Tracing.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=188784&view=ms.vss-test-web.build-test-results-tab&runId=3619103&resultId=186503)|dotnet/runtime#82807|
|[186414](https://dev.azure.com/dnceng-public/public/_build/results?buildId=186414)|dotnet/runtime|[WasmTestOnBrowser-System.Diagnostics.Tracing.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=186414&view=ms.vss-test-web.build-test-results-tab&runId=3590430&resultId=186502)|dotnet/runtime#82192|
|[182904](https://dev.azure.com/dnceng-public/public/_build/results?buildId=182904)|dotnet/runtime|[WasmTestOnBrowser-System.Diagnostics.Tracing.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=182904&view=ms.vss-test-web.build-test-results-tab&runId=3571828&resultId=186502)|dotnet/runtime#82572|
|[184113](https://dev.azure.com/dnceng-public/public/_build/results?buildId=184113)|dotnet/runtime|[WasmTestOnBrowser-System.Diagnostics.Tracing.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=184113&view=ms.vss-test-web.build-test-results-tab&runId=3569137&resultId=186502)|dotnet/runtime#82089|
|[182131](https://dev.azure.com/dnceng-public/public/_build/results?buildId=182131)|dotnet/runtime|[WasmTestOnBrowser-System.Diagnostics.Tracing.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=182131&view=ms.vss-test-web.build-test-results-tab&runId=3548773&resultId=186502)|dotnet/runtime#82089|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|8|16|

**Comment by pavelsavara** [comment] 2023-02-17 18:29
What is `msdia140.dll` native file doing there ?

**Comment by pavelsavara** [comment] 2023-02-17 18:31
Larry saw it [on Net7 build](https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-pull-82268-merge-cdb46527ed124343ac/WasmTestOnBrowser-System.Diagnostics.Tracing.Tests/1/console.ceb42604.log?helixlogtype=result)
So my theory I broke it last week is not valid.

**Comment by pavelsavara** [comment] 2023-02-24 17:12
So, this is caused by counting download retry multiple times, only when the download fails during `await response.arrayBuffer()` but after HTTP headers are already fetched.

**Comment by pavelsavara** [comment] 2023-03-14 13:25
Fixed by https://github.com/dotnet/runtime/pull/82617

**Closed by pavelsavara** 2023-03-14 13:25 UTC
Labels: arch-wasm, blocking-clean-ci, area-VM-meta-mono, test-failure
