### ISSUE TITLE
LibraryImport generated code feedback

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#69608] opened 2022-05-20 15:10 UTC
I spent a little time looking over the code generated for the LibraryImports in CoreLib.  Some random feedback / comments / questions...

**Performance**

1. [Addressed: #69764] Manual copy loops. For RegSetValueEx, I see this code being generated for marshaling:
```C#
                __lpData_gen_native__marshaller = new(lpData, new System.Span<byte>(__lpData_gen_native__marshaller__stackptr, 512), sizeof(ushort));
                {
                    System.ReadOnlySpan<char> __lpData_gen_native__marshaller__managedSpan = __lpData_gen_native__marshaller.GetManagedValuesSource();
                    System.Span<ushort> __lpData_gen_native__marshaller__nativeSpan = System.Runtime.InteropServices.MemoryMarshal.Cast<byte, ushort>(__lpData_gen_native__marshaller.GetNativeValuesDestination());
                    for (int __i0 = 0; __i0 < __lpData_gen_native__marshaller__managedSpan.Length; ++__i0)
                    {
                        __lpData_gen_native__marshaller__nativeSpan[__i0] = __lpData_gen_native__marshaller__managedSpan[__i0];
                    }
                }
```
That copy loop could be fairly inefficient.  Can't we use MemoryMarshal.Cast in a case like this to treat the char input as a ushort and then use the vectorized ReadOnlySpan.CopyTo?

2. [Already the case] SkipLocalsInit.  Some of the generated code emits fairly large stackallocs, e.g. `stackalloc byte[512]`.  That can add measurable overhead if the user's code hasn't set SkipLocalsInit.  Can we add [SkipLocalsInit] to the generated method if there isn't already one provided by the user at a level that would encompass the generated method?

3. GetArrayDataReference.  The GetCalendars method in corelib is being generated like this:
```C#
        internal static partial int GetCalendars(string localeName, global::System.Globalization.CalendarId[] calendars, int calendarsCapacity)
        {
            int __retVal;
            //
            // Marshal
            //
            ref global::System.Globalization.CalendarId __byref_calendars = ref (calendars == null ? ref *(global::System.Globalization.CalendarId*)0 : ref System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(calendars));
            //
            // Pin
            //
            fixed (void* __localeName_gen_native__pinned = localeName)
            {
                ushort* __localeName_gen_native = (ushort*)__localeName_gen_native__pinned;
                fixed (byte* __calendars_gen_native = &System.Runtime.CompilerServices.Unsafe.As<global::System.Globalization.CalendarId, byte>(ref __byref_calendars))
                {
                    __retVal = __PInvoke__(__localeName_gen_native, __calendars_gen_native, calendarsCapacity);
                }
            }

            return __retVal;
            //
            // Local P/Invoke
            //
            [System.Runtime.InteropServices.DllImportAttribute("System.Globalization.Native", EntryPoint = "GlobalizationNative_GetCalendars", ExactSpelling = false)]
            extern static unsafe int __PInvoke__(ushort* localeName, byte* calendars, int calendarsCapacity);
        }
```
Why is it getting a ref to the array via that complicated null check + GetArrayDataReference followed later by using fixed on an Unsafe.As cast in order to get a byte*, rather than just using fixed with the array to get a void* and then casting that pointer to byte*?

4. SafeHandle disposal.  When marshaling out a SafeHandle, the generator emits code like this:
```C#
            __retVal = new global::Microsoft.Win32.SafeHandles.SafeFindHandle();
            try
            {
                //
                // Pin
                //
                fixed (void* __lpFileName_gen_native__pinned = lpFileName)
                {
                    ushort* __lpFileName_gen_native = (ushort*)__lpFileName_gen_native__pinned;
                    fixed (global::Interop.Kernel32.WIN32_FIND_DATA* __lpFindFileData_gen_native = &lpFindFileData)
                    {
                        {
                            System.Runtime.InteropServices.Marshal.SetLastSystemError(0);
                            __retVal_gen_native = __PInvoke__(__lpFileName_gen_native, fInfoLevelId, __lpFindFileData_gen_native, fSearchOp, lpSearchFilter, dwAdditionalFlags);
                            __lastError = System.Runtime.InteropServices.Marshal.GetLastSystemError();
                        }
                    }
                }

                __invokeSucceeded = true;
            }
            finally
            {
                if (__invokeSucceeded)
                {
                    //
                    // GuaranteedUnmarshal
                    //
                    System.Runtime.InteropServices.Marshal.InitHandle(__retVal, __retVal_gen_native);
                }
            }
```
It's using a try/finally and __invokeSucceeded, so it's trying to accomodate something in that try region throwing.  But if something there does throw, the allocated SafeHandle won't be disposed, which will in turn leave it for finalization.  Should there be a catch block?
```C#
catch
{
    __retVal.Dispose();
    throw;
}
```
or potentially instead a catch with an exception filter that does the disposal and returns false to avoid interrupting the unwind?

5. [Addressed: #69619] Out initialization.  When there's an out variable, the generated code starts off by zero'ing it, e.g.
```C#
        internal static partial int CLSIDFromProgID(string lpszProgID, out global::System.Guid lpclsid)
        {
            lpclsid = default;
            ...
```
Does the built-in marshaling do this, or is this done to work around C# definite assignment errors?  If we're doing it just for the latter, we could instead use `Unsafe.SkipInit(out ...)`, and avoid the extra zero'ing / indirect write.

**Style**

1. Blank lines.  The generator currently emits code like:
```C#
            int __throwOnError_gen_native;
            int __ignoreCase_gen_native;
            //
            // Marshal
            //
            __throwOnError_gen_native = (int)(throwOnError ? 1 : 0);
            __ignoreCase_gen_native = (int)(ignoreCase ? 1 : 0);
            //
            // Pin
            //
            fixed (void* __name_gen_native__pinned = name)
            {
                ushort* __name_gen_native = (ushort*)__name_gen_native__pinned;
                {
                    __PInvoke__(assembly, __name_gen_native, __throwOnError_gen_native, __ignoreCase_gen_native, type, keepAlive, assemblyLoadContext);
                }
            }
```
Could we add a blank line, purely for readability, before each big comment block that's preceded by statements? Also, do we need the extra "//" lines, or could these just be single-line comments?  It takes up a lot of vertical real estate, and I'm not sure what it helps.

2. [Addressed: #69619] Comments. Instead of "Marshal", could we make it a bit more descriptive, e.g. "Marshal the input arguments.", and instead of "Pin", it could be "Pin the input parameters".   Similarly for "Unmarshal", which could be "Marshal the output values" or something like that.

3. [Addressed: #69638] Variable naming.  Lots of variables include "_gen_native"... presumably the "_native" part is meant to mean that's the variable that's going to be passed to the P/Invoke... what's the meaning / value-add of the "_gen"?  The variables are already prefixed with "__", presumably to differentiate them from the values being used?

4. [Addressed: #69619] Modifier ordering. IDE0036 has a preference for the order of modifiers.  Since we have to choose some ordering, it'd be nice to snap to its preference (https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0036#overview), e.g. today we might output "extern static unsafe void __PInvoke__", but following its ordering it would be "static extern unsafe void __PInvoke__"

5. [Addressed: #69638] Braces.  The actual __PInvoke__ call often ends up being surrounded by an extra level of braces, e.g.
```C#
            //
            // Pin
            //
            fixed (void* __resourceName_gen_native__pinned = resourceName)
            {
                ushort* __resourceName_gen_native = (ushort*)__resourceName_gen_native__pinned;
                {
                    __retVal = __PInvoke__(assembly, __resourceName_gen_native, assemblyRef, retFileName);
                }
            }
```
Why?

6. [Addressed: #69804] Locals for storing cast values.  As an example, the TraceResolvingHandlerInvoked method in corelib has this generated code:
```C#
            fixed (void* __assemblyName_gen_native__pinned = assemblyName)
            {
                ushort* __assemblyName_gen_native = (ushort*)__assemblyName_gen_native__pinned;
                fixed (void* __handlerName_gen_native__pinned = handlerName)
                {
                    ushort* __handlerName_gen_native = (ushort*)__handlerName_gen_native__pinned;
                    fixed (void* __alcName_gen_native__pinned = alcName)
                    {
                        ushort* __alcName_gen_native = (ushort*)__alcName_gen_native__pinned;
                        fixed (void* __resultAssemblyName_gen_native__pinned = resultAssemblyName)
                        {
                            ushort* __resultAssemblyName_gen_native = (ushort*)__resultAssemblyName_gen_native__pinned;
                            fixed (void* __resultAssemblyPath_gen_native__pinned = resultAssemblyPath)
                            {
                                ushort* __resultAssemblyPath_gen_native = (ushort*)__resultAssemblyPath_gen_native__pinned;
                                {
                                    __retVal_gen_native = __PInvoke__(__assemblyName_gen_native, __handlerName_gen_native, __alcName_gen_native, __resultAssemblyName_gen_native, __resultAssemblyPath_gen_native);
                                }
                            }
                        }
                    }
                }
            }
```
It's creating new locals just to store the void* cast to a ushort*, which is then only used as an argument.  Could it instead be:
```C#
            fixed (void* __assemblyName_gen_native = assemblyName)
                fixed (void* __handlerName_gen_native = handlerName)
                    fixed (void* __alcName_gen_native = alcName)
                        fixed (void* __resultAssemblyName_gen_native = resultAssemblyName)
                            fixed (void* __resultAssemblyPath_gen_native = resultAssemblyPath)
                            {
                                    __retVal_gen_native = __PInvoke__((ushort*)__assemblyName_gen_native, (ushort*)__handlerName_gen_native, (ushort*)__alcName_gen_native, (ushort*)__resultAssemblyName_gen_native, (ushort*)__resultAssemblyPath_gen_native);
                            }
```
or even declare __PInvoke__ to take void* instead of ushort* and then the casts wouldn't be needed at all?
```C#
            fixed (void* __assemblyName_gen_native = assemblyName)
                fixed (void* __handlerName_gen_native = handlerName)
                    fixed (void* __alcName_gen_native = alcName)
                        fixed (void* __resultAssemblyName_gen_native = resultAssemblyName)
                            fixed (void* __resultAssemblyPath_gen_native = resultAssemblyPath)
                            {
                                    __retVal_gen_native = __PInvoke__(__assemblyName_gen_native, __handlerName_gen_native, __alcName_gen_native, __resultAssemblyName_gen_native, __resultAssemblyPath_gen_native);
                            }
```

7. Simplifiable boilerplate.  Consider a method like Debugger.LaunchInternal:
```C#
        private static partial bool LaunchInternal()
        {
            bool __retVal;
            int __retVal_gen_native;
            __retVal_gen_native = __PInvoke__();
            //
            // Unmarshal
            //
            __retVal = __retVal_gen_native != 0;
            return __retVal;
            //
            // Local P/Invoke
            //
            [System.Runtime.InteropServices.DllImportAttribute("QCall", EntryPoint = "DebugDebugger_Launch", ExactSpelling = false)]
            extern static unsafe int __PInvoke__();
        }
```
If someone were writing this by hand, it would just be:
```C#
        private static partial bool LaunchInternal()
        {
            return __PInvoke__() != 0;

            [System.Runtime.InteropServices.DllImportAttribute("QCall", EntryPoint = "DebugDebugger_Launch", ExactSpelling = false)]
            extern static unsafe int __PInvoke__();
        }
```
Have we considered enabling such simplified emitted code when we can detect it?

8. [Addressed: #69619] Double underscores.  I assume we're using the `"__"` prefix to avoid conflict with user-defined names, like for arguments?  Why does the `"__PInvoke__"` also have a `"__"` suffix?

**Comment by elinor-fung** [comment] 2022-05-20 20:58
> 2. SkipLocalsInit... Can we add [SkipLocalsInit] to the generated method if there isn't already one provided by the user at a level that would encompass the generated method?

@stephentoub could you point us at an example for this? We should already be doing this (and should have tests for it), so it's definitely a bug if it is not happening. I believe most of the runtime libraries already have it set it at the module level, so we don't add it on the method.

**Comment by AaronRobinsonMSFT** [comment] 2022-05-21 01:53
@stephentoub Using `Unsafe.SkipInit` is possible except when the out is a pointer value - good idea. The remaining 5 functional statements the team is looking at - see @elinor-fung's comment above.

I appreciate the aspirational aspect of the style issues and I think we can move closer, but for our first public version we are only going to focus on the easy ones. Updated comments on the stages - good idea and will help with design and education. Modifier order is an oops on our part, good idea. The "__" suffix is superfluous and agree that we can remove it. 

The rest are really about simplifying code. This gets really complicated fast because it involves going back through the Roslyn syntax trees and updating them. I see very little practical value in this and minimizing it is going to become very tedious. For right now the rest of the style suggestions are going to be deferred/rejected.

**Comment by stephentoub** [comment] 2022-05-22 00:44
> We should already be doing this

You're right, it's behaving as I'd expect.  I'd tried it in a separate project but must have been doing something wrong.  I see it now doing what I expect it to be doing.

> The remaining 4 functional statements the team is looking at

Thanks.

> The rest are really about simplifying code.

Yes.  Though sometimes stylistic improvements also map to smaller IL and asm, e.g. here's (6) on the style list, before and after:
[SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIGYACAVwDtdsAzGBshgYQYBvGg1EMAliwwwoLbABse5JA2AQIigCpRsYGACUYuDQDdJAcwAS2FgBN5MgJIsTEANYxbACmLkADAx4uDD4wPIAngBy2PgwaEoBABY29jLRsfG+AQpg6XEJDLC4TPIYAIK4waEReZn+hUYl5ZUhYeEACtgYiQCUImLC1GLDquqKAPrjsBgAagoA3P0jElIMk9Nz8uPmMCzjchjiJjCLQ8sMAPQXSyNXDO2SN8NXT2Ic4gieDD4oAFRr4yCrRqMRg212+y6RzB4wADpIWF8ALyBFrVKKgvpnZaDc4jYh/AFA9F5cF7A7Qhgon6/HqTYltUk7clQ46TeEsRG2U544bvT62b4E/6TZJ2BxQJkQilsuEI5EMMWpSWY144tW84UApUSqUsw7HKlCv508Y6tKgsmQg0wjlcnm85b8r40onyXKW5nW6Hs+WClE5PJYx3q7Eh5Za+nuvXew3U4WmwOe6Ws21+h3hp0fF2RqaNUoVKqM5P6n1yzkKopNQvAjGxYOZ0ONx25qsFtHF2JWmXceMm9b55pFkFdr0930V7ka5sMZ2C10D4rt4cdLqJbupidco1toe1zrdBszpvHluExfVjsRA/rsepo00027mvom8bm1bzwZ0/nXE/8MDrMCjvpSKKTO0ziuB4kxePSV51mCd42vEoopLqJaxvkUYeqOKbIQCz7wTGPYoXmS57q+a4gccPTfv+wwAL7Ts2TFhjOrHscxogcecrEai8bFiHcACqLD4NgUC4Mk8j8dcgmiIBmxGopwFIZSACEKJ+HRYjEAA7ARMBAfIOmiAJeJ3AAMhAYAKPcFyQe4MCyRqADavgAHT6KwhyxB5zjSFAECwgAyjIZh6LgHkACLyPIjj4LC0DlBgGBQOIwBMNIXgAEQAIp8Ao8g5fEACiUhQB0ECSBgRo5S+xYftougGEYpgWNY4pOC4Tm2CVDClQgugYCFsIwHFFhGhwCjBD0AC6GowAggUsEoKisOwXArLV4GOdB4yugyI75Fq5oqhkPCEkmF1aoRK61Jd/x3fua60TcPGiDcNUyHIii+CoagaAwzV6IYxjyGYLBWGh3VQZ4pA+PUR0IXUSQw+dJ1I9GoKow05ENcduPPZRh43H+WYCsaIqAkRGE9kayNBlxs7ZvOuZncR94ohzqrybyc5U26OGIXhoGBNj9bM3iAsLmRl73XTXN4/LtZM3zM4y62g4E6u3TUb2yvLi9pPqz++kAhBPX7bBNMK7hpbHKRPP25hpHXSLDtYXLRskor+EXj7bRvmpNEMJpDDaTQbmed5UjiH5AUyMFYVQBFRgxXFCVJVAKVpRlWUwLlBVFf15VpVVNV1Tr0RNTooNtRDHXo3tnil0NYAjWNE1Q1NM0wPNi3LT9a3MGwnDcJXu1WzCh20zdhLOydV0S0vT3a3Pq+GxRQevd+rEMUAA)
<img width="567" alt="image" src="https://user-images.githubusercontent.com/2642209/169673609-ef7d580c-66b0-411f-9c16-f21fb6c7a3fb.png">

> This gets really complicated fast because it involves going back through the Roslyn syntax trees and updating them.

I'm curious why we're using Roslyn's syntax trees to generate the resulting code, especially if it makes it harder to generate the desired output.  We can also just write out the C# directly, which is what all of the other generators in dotnet/runtime do (the logging generator, the json generator, and the regex generator).

**Comment by jkoritzinsky** [comment] 2022-05-24 20:24
> **Performance**

> 3. GetArrayDataReference.  The GetCalendars method in corelib is being generated like this:
> 
> ```cs
>         internal static partial int GetCalendars(string localeName, global::System.Globalization.CalendarId[] calendars, int calendarsCapacity)
>         {
>             int __retVal;
>             //
>             // Marshal
>             //
>             ref global::System.Globalization.CalendarId __byref_calendars = ref (calendars == null ? ref *(global::System.Globalization.CalendarId*)0 : ref System.Runtime.InteropServices.MemoryMarshal.GetArrayDataReference(calendars));
>             //
>             // Pin
>             //
>             fixed (void* __localeName_gen_native__pinned = localeName)
>             {
>                 ushort* __localeName_gen_native = (ushort*)__localeName_gen_native__pinned;
>                 fixed (byte* __calendars_gen_native = &System.Runtime.CompilerServices.Unsafe.As<global::System.Globalization.CalendarId, byte>(ref __byref_calendars))
>                 {
>                     __retVal = __PInvoke__(__localeName_gen_native, __calendars_gen_native, calendarsCapacity);
>                 }
>             }
> 
>             return __retVal;
>             //
>             // Local P/Invoke
>             //
>             [System.Runtime.InteropServices.DllImportAttribute("System.Globalization.Native", EntryPoint = "GlobalizationNative_GetCalendars", ExactSpelling = false)]
>             extern static unsafe int __PInvoke__(ushort* localeName, byte* calendars, int calendarsCapacity);
>         }
> ```
> 
> Why is it getting a ref to the array via that complicated null check + GetArrayDataReference followed later by using fixed on an Unsafe.As cast in order to get a byte*, rather than just using fixed with the array to get a void* and then casting that pointer to byte*?

We can't use a `fixed` statement with arrays as C# normalizes an empty array to a `null` value, which breaks a lot of interop scenarios with arrays. We have the complex initialization to handle `null` arrays as a null array causes an exception in `GetArrayDataReference`. See https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/libraries/System.Private.CoreLib/src/System/Globalization/CompareInfo.Icu.cs#L733, https://github.com/dotnet/runtime/pull/52030/files#diff-4b9bcd238c75b08d184c630e8e90372464f848bbb2ed0466c0c3bafe74ee27b7R23, https://github.com/dotnet/runtimelab/issues/1051#issuecomment-830425414, https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/coreclr/vm/ilmarshalers.cpp#L3967.

> 4. SafeHandle disposal.  When marshaling out a SafeHandle, the generator emits code like this:
> 
> ```cs
>             __retVal = new global::Microsoft.Win32.SafeHandles.SafeFindHandle();
>             try
>             {
>                 //
>                 // Pin
>                 //
>                 fixed (void* __lpFileName_gen_native__pinned = lpFileName)
>                 {
>                     ushort* __lpFileName_gen_native = (ushort*)__lpFileName_gen_native__pinned;
>                     fixed (global::Interop.Kernel32.WIN32_FIND_DATA* __lpFindFileData_gen_native = &lpFindFileData)
>                     {
>                         {
>                             System.Runtime.InteropServices.Marshal.SetLastSystemError(0);
>                             __retVal_gen_native = __PInvoke__(__lpFileName_gen_native, fInfoLevelId, __lpFindFileData_gen_native, fSearchOp, lpSearchFilter, dwAdditionalFlags);
>                             __lastError = System.Runtime.InteropServices.Marshal.GetLastSystemError();
>                         }
>                     }
>                 }
> 
>                 __invokeSucceeded = true;
>             }
>             finally
>             {
>                 if (__invokeSucceeded)
>                 {
>                     //
>                     // GuaranteedUnmarshal
>                     //
>                     System.Runtime.InteropServices.Marshal.InitHandle(__retVal, __retVal_gen_native);
>                 }
>             }
> ```
> 
> It's using a try/finally and __invokeSucceeded, so it's trying to accomodate something in that try region throwing. But if something there does throw, the allocated SafeHandle won't be disposed, which will in turn leave it for finalization. Should there be a catch block?
> 
> ```cs
> catch
> {
>     __retVal.Dispose();
>     throw;
> }
> ```
> 
> or potentially instead a catch with an exception filter that does the disposal and returns false to avoid interrupting the unwind?

Our SafeHandle marshalling was designed to match the built-in marshalling as closely as possible, as SafeHandle has particular guarantees in interop that we didn't want to break. Changing this portion of the behavior seems doable, so we'll consider it.

> I'm curious why we're using Roslyn's syntax trees to generate the resulting code, especially if it makes it harder to generate the desired output. We can also just write out the C# directly, which is what all of the other generators in dotnet/runtime do (the logging generator, the json generator, and the regex generator).

As we designed our generator, we decided that using at least some of the Roslyn syntax APIs would help make our code easier to maintain as we'd know if a particular API returned a statement, expression, type name, etc. just by looking at the signature. Additionally, it handles indentation for us, which is quite a convenient feature. Honestly I feel like just using string concatenation would make our generator harder to maintain and extend as we'd have to heavily document what each method returns as the type system wouldn't be able to help us, and analyzing the syntax after generation to optimize code after generation would actually be even more difficult than using the Roslyn APIs. We don't want to special-case or overcomplicate things in our generator too much as it can quickly make the system unmaintainable (i.e. MCG).

We could probably use a speculative semantic model to do some post-generation analysis and simplification if the gains are large enough, but I don't know if it's worth the effort (or even possible with Roslyn's API).

**Comment by GSPP** [comment] 2022-05-25 06:34
Can this complex "GetArrayDataReference" expression be made into a helper method in the `CompilerServices` namespace? That would remove the need to emit this code again and again.

**Comment by jkoritzinsky** [comment] 2022-08-05 20:41
@GSPP that change was handled with the V2 marshaller design and the new `ArrayMarshaller<T, TUnmanagedElement>` type (the complex code is in the static `GetPinnableReference` method).

I've extracted performance suggestion #4 (safehandle) to https://github.com/dotnet/runtime/issues/69608 as that's the last feedback item that we plan to address. I'll close this as completed in the meantime.

**Closed by jkoritzinsky** 2022-08-05 20:41 UTC
Labels: area-System.Runtime.InteropServices, source-generator
