### ISSUE TITLE
Test failure System.Net.WebSockets.Client.Tests.MemorySendReceiveTest.ReceiveAsync_MultipleOutstandingReceiveOperations_Throws(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#58739] opened 2021-09-07 01:50 UTC
Run: [runtime-libraries-coreclr outerloop 20210906.5](https://dev.azure.com/dnceng/public/_build/results?buildId=1344598&view=ms.vss-test-web.build-test-results-tab&runId=39367852&resultId=103388&paneView=debug)

Failed test:
```
net6.0-Linux-Release-x64-CoreCLR_release-(Fedora.34.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-34-helix-20210728124700-4f64125

- System.Net.WebSockets.Client.Tests.MemorySendReceiveTest.ReceiveAsync_MultipleOutstandingReceiveOperations_Throws(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)
- System.Net.WebSockets.Client.Tests.ConnectTest.EchoTextMessage_Success(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)

net6.0-Linux-Release-x64-CoreCLR_release-(Alpine.312.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.12-helix-20200601195603-e06dc59

- System.Net.WebSockets.Client.Tests.ArraySegmentSendReceiveTest.SendReceive_PartialMessageDueToSmallReceiveBuffer_Success(server: ws://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)
- System.Net.WebSockets.Client.Tests.ConnectTest.EchoBinaryMessage_Success(server: ws://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)
```
**Error message:**
```
System.Threading.Tasks.TaskCanceledException : A task was canceled.


Stack trace
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) in /_/src/libraries/Common/src/System/Threading/Tasks/TaskCompletionSourceWithCancellation.cs:line 23
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 548
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 988
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 30
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options) in /_/src/libraries/System.Net.WebSockets.Client/src/System/Net/WebSockets/WebSocketHandle.Managed.cs:line 143
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken) in /_/src/libraries/System.Net.WebSockets.Client/src/System/Net/WebSockets/ClientWebSocket.cs:line 104
   at System.Net.WebSockets.Client.Tests.WebSocketHelper.<>c__DisplayClass4_0.<<GetConnectedWebSocket>b__0>d.MoveNext() in /_/src/libraries/System.Net.WebSockets.Client/tests/WebSocketHelper.cs:line 98
--- End of stack trace from previous location ---
   at System.Net.WebSockets.Client.Tests.WebSocketHelper.Retry[T](ITestOutputHelper output, Func`1 func)
   at System.Net.WebSockets.Client.Tests.SendReceiveTest.ReceiveAsync_MultipleOutstandingReceiveOperations_Throws(Uri server) in /_/src/libraries/System.Net.WebSockets.Client/tests/SendReceiveTest.cs:line 222
--- End of stack trace from previous location ---
```

**Comment by karelz** [comment] 2021-09-07 16:47
Duplicate of #57134

**Closed by karelz** 2021-09-07 16:47 UTC
Labels: area-System.Net, os-linux, arch-x64, untriaged
