### ISSUE TITLE
CI failures in "Libraries Test Run release coreclr windows x86 Release"

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#66125] opened 2022-03-03 02:01 UTC
The failure is unrelated to the change: https://github.com/dotnet/runtime/runs/5401001704

All the other CI legs for Libraries passed, only this one failed.

Example 1
```
Console log: 'System.IO.Compression.Tests' from job 034a7bfb-e0b8-4d76-9e4a-2c85d35b89c7 workitem b630aa89-c7d8-4f6b-bb82-036b26dccf74 (windows.7.amd64.open.rt) executed on machine a00ACYI

C:\h\w\B41D09B0\w\B44709D7\e>taskkill.exe /f /im corerun.exe 
ERROR: The process "corerun.exe" not found.

C:\h\w\B41D09B0\w\B44709D7\e>call RunTests.cmd --runtime-path C:\h\w\B41D09B0\p 
----- start Thu 03/03/2022  1:22:15.99 ===============  To repro directly: ===================================================== 
pushd C:\h\w\B41D09B0\w\B44709D7\e\
"C:\h\w\B41D09B0\p\dotnet.exe" exec --runtimeconfig System.IO.Compression.Tests.runtimeconfig.json --depsfile System.IO.Compression.Tests.deps.json xunit.console.dll System.IO.Compression.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================

C:\h\w\B41D09B0\w\B44709D7\e>"C:\h\w\B41D09B0\p\dotnet.exe" exec --runtimeconfig System.IO.Compression.Tests.runtimeconfig.json --depsfile System.IO.Compression.Tests.deps.json xunit.console.dll System.IO.Compression.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.IO.Compression.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.IO.Compression.Tests (found 247 of 257 test cases)
  Starting:    System.IO.Compression.Tests (parallel test collections = on, max threads = 2)
----- end Thu 03/03/2022  1:22:18.71 ----- exit code -1073741819 ----------------------------------------------------------
2022-03-03T01:22:19.215Z	INFO   	run.py	run(48)	main	Beginning reading of test results.
2022-03-03T01:22:19.215Z	INFO   	run.py	__init__(48)	get_log_files	Searching 'C:\h\w\B41D09B0\w\B44709D7\e\..' for log files
Found log 'C:\h\w\B41D09B0\w\B44709D7\e\..\console.8bc771b5.log'
Uri 'https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-65886-merge-034a7bfbe0b84d769e/System.IO.Compression.Tests/console.8bc771b5.log?sv=2019-07-07&se=2022-03-23T01%3A11%3A07Z&sr=c&sp=rl&sig=eIE%2Fj1BffznzHobS6c5%2BWwmJ9GA5puhG9SCiRb21MtY%3D'
2022-03-03T01:22:19.215Z	INFO   	run.py	__init__(66)	construct_log_list	Generated log list: console.8bc771b5.log:
  https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-65886-merge-034a7bfbe0b84d769e/System.IO.Compression.Tests/console.8bc771b5.log?sv=2019-07-07&se=2022-03-23T01%3A11%3A07Z&sr=c&sp=rl&sig=eIE%2Fj1BffznzHobS6c5%2BWwmJ9GA5puhG9SCiRb21MtY%3D

2022-03-03T01:22:19.215Z	INFO   	run.py	__init__(90)	read_results	Searching 'C:\h\w\B41D09B0\w\B44709D7\e' for test results files
2022-03-03T01:22:19.215Z	INFO   	run.py	__init__(90)	read_results	Searching 'C:\h\w\B41D09B0\w\B44709D7\uploads' for test results files
2022-03-03T01:22:19.215Z	WARNING	run.py	__init__(103)	read_results	No results file found in any of the following formats: xunit, junit, trx
2022-03-03T01:22:19.215Z	INFO   	run.py	packing_test_reporter(30)	report_results	Packing 0 test reports to 'C:\h\w\B41D09B0\w\B44709D7\e\__test_report.json'
2022-03-03T01:22:19.230Z	INFO   	run.py	packing_test_reporter(33)	report_results	Packed 1691 bytes
read file: C:\h\w\B41D09B0\p\debug-dump-template.md
writing output file: C:\h\w\B41D09B0\w\B44709D7\uploads\how-to-debug-dump.md
done writing debug dump information
```

Example 2
```
Console log: 'Common.Tests' from job 034a7bfb-e0b8-4d76-9e4a-2c85d35b89c7 workitem c44acf02-e12c-46ca-b51f-dabec51eb076 (windows.7.amd64.open.rt) executed on machine a00AC0P

C:\h\w\B41D09B0\w\BD8A0A4C\e>taskkill.exe /f /im corerun.exe 
ERROR: The process "corerun.exe" not found.

C:\h\w\B41D09B0\w\BD8A0A4C\e>call RunTests.cmd --runtime-path C:\h\w\B41D09B0\p 
----- start Thu 03/03/2022  1:11:23.18 ===============  To repro directly: ===================================================== 
pushd C:\h\w\B41D09B0\w\BD8A0A4C\e\
"C:\h\w\B41D09B0\p\dotnet.exe" exec --runtimeconfig Common.Tests.runtimeconfig.json --depsfile Common.Tests.deps.json xunit.console.dll Common.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================

C:\h\w\B41D09B0\w\BD8A0A4C\e>"C:\h\w\B41D09B0\p\dotnet.exe" exec --runtimeconfig Common.Tests.runtimeconfig.json --depsfile Common.Tests.deps.json xunit.console.dll Common.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: Common.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  Common.Tests (found 257 of 265 test cases)
  Starting:    Common.Tests (parallel test collections = on, max threads = 2)
----- end Thu 03/03/2022  1:11:25.52 ----- exit code -1073741819 ----------------------------------------------------------
2022-03-03T01:11:27.277Z	INFO   	run.py	run(48)	main	Beginning reading of test results.
2022-03-03T01:11:27.277Z	INFO   	run.py	__init__(48)	get_log_files	Searching 'C:\h\w\B41D09B0\w\BD8A0A4C\e\..' for log files
Found log 'C:\h\w\B41D09B0\w\BD8A0A4C\e\..\console.9795886e.log'
Uri 'https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-65886-merge-034a7bfbe0b84d769e/Common.Tests/console.9795886e.log?sv=2019-07-07&se=2022-03-23T01%3A11%3A07Z&sr=c&sp=rl&sig=eIE%2Fj1BffznzHobS6c5%2BWwmJ9GA5puhG9SCiRb21MtY%3D'
2022-03-03T01:11:27.277Z	INFO   	run.py	__init__(66)	construct_log_list	Generated log list: console.9795886e.log:
  https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-65886-merge-034a7bfbe0b84d769e/Common.Tests/console.9795886e.log?sv=2019-07-07&se=2022-03-23T01%3A11%3A07Z&sr=c&sp=rl&sig=eIE%2Fj1BffznzHobS6c5%2BWwmJ9GA5puhG9SCiRb21MtY%3D

2022-03-03T01:11:27.277Z	INFO   	run.py	__init__(90)	read_results	Searching 'C:\h\w\B41D09B0\w\BD8A0A4C\e' for test results files
2022-03-03T01:11:27.277Z	INFO   	run.py	__init__(90)	read_results	Searching 'C:\h\w\B41D09B0\w\BD8A0A4C\uploads' for test results files
2022-03-03T01:11:27.277Z	WARNING	run.py	__init__(103)	read_results	No results file found in any of the following formats: xunit, junit, trx
2022-03-03T01:11:27.277Z	INFO   	run.py	packing_test_reporter(30)	report_results	Packing 0 test reports to 'C:\h\w\B41D09B0\w\BD8A0A4C\e\__test_report.json'
2022-03-03T01:11:27.277Z	INFO   	run.py	packing_test_reporter(33)	report_results	Packed 1718 bytes
read file: C:\h\w\B41D09B0\p\debug-dump-template.md
writing output file: C:\h\w\B41D09B0\w\BD8A0A4C\uploads\how-to-debug-dump.md
done writing debug dump information
```

**Comment by jkotas** [comment] 2022-03-03 05:40
Duplicate of #65890

**Closed by jkotas** 2022-03-03 05:40 UTC
Labels: area-Infrastructure-libraries, untriaged
