### ISSUE TITLE
Cannot configure HttpHandler in DI with Azure Functions v4

### ISSUE THREAD

**Issue by nicholasamiller** [dotnet/runtime#71130] opened 2022-06-22 12:29 UTC
### Description

My aim is to configure the HttpHandler used by the IHttpClientFactory in DI an an Azure function.
I followed this documentation from https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-6.0
```
builder.Services.AddHttpClient("ConfiguredHttpMessageHandler")
    .ConfigurePrimaryHttpMessageHandler(() =>
        new HttpClientHandler
        {
            AllowAutoRedirect = false
        });
```
There handler is not injected.

### Reproduction Steps

Create an Azure function with the following Startup.cs:

```
 public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {

            builder.Services.AddHttpClient("foo")
                .ConfigurePrimaryHttpMessageHandler(() =>
                   throw new Exception("This won't actually throw because this code is not run.")
                    );
        }
    }
```

Create an Azure function with IHttpClientFactory injected, then call CreateClient("foo") on it.
You'll see the exception is not thrown.
The HttpClient uses a default http handler.

### Expected behavior

The injected IHttpClientFactory uses the delegate to create a HttpHandler as described in the documentation.

### Actual behavior

The injected IHttpClientFactory uses a default HttpHandler.

### Configuration

.NET 6.0
Windows 10.
x86
No

**Comment by nicholasamiller** [comment] 2022-06-22 12:36
Will put this is the asp.net core repo instead.

**Comment by CarnaViire** [comment] 2022-06-22 13:00
@nicholasamiller HttpClientFactory actually does belong to runtime, not to ASP.NET Core, so I will reopen it now and add a reply to your question a bit later

**Comment by CarnaViire** [comment] 2022-06-22 18:57
@nicholasamiller I cannot reproduce the behavior, I can see the exception being thrown:
```
[2022-06-22T18:47:37.698Z] Executed 'Function1' (Failed, Id=95d59f62-fd60-450e-be31-c9a460825535, Duration=437ms)
[2022-06-22T18:47:37.700Z] System.Private.CoreLib: Exception while executing function: Function1. HCFFunctionsTest: This won't actually throw because this code is not run.
```
If the problem still persists, could you please send us a complete minimal repro of the behavior? Otherwise, it is not actionable for us. Thanks!

**Comment by CarnaViire** [comment] 2022-07-13 13:57
Thanks for providing the repro @nicholasamiller and sorry it took some time to get back to you.

What's missing in your case is `FunctionsStartup` attribute in your function declaration. Because of that, the Startup class was not called at all. After putting this line above namespace, the behavior became as expected (attempting to create HttpClient started throwing as configured)

```c#
[assembly: FunctionsStartup(typeof(HttpHandlerConfigBug.Startup))]
namespace HttpHandlerConfigBug
{
    public class Function1
```

Unfortunately, I am not a Functions expert, so I don't know why default factory was available in the container even though your Startup class was not called.

I will close this issue as there's no bug in HttpClientFactory.

----

What I noticed from HttpClientFactory perspective though, is that it will give you a default HttpClient for any random name you didn't previously configure. I don't know the reasoning behind the original design, and whether it's a bug or a feature. From my point of view, it's just a source of hard-to-catch bugs, however, I am not sure we should/are able to "fix" it, as it will be a behavioral breaking change.

**Closed by CarnaViire** 2022-07-13 13:57 UTC
Labels: untriaged, area-Extensions-HttpClientFactory, needs-further-triage
