### ISSUE TITLE
Some `AppDomain` obsoletion warnings reference non-existent `AppDomainSetup` properties.

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/runtime#56677] opened 2021-07-31 23:24 UTC
`AppDomain.SetDynamicBase` and the methods at https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/AppDomain.cs#L214:L235 are marked as `[Obsolete]` with a warning of the form `AppDomain.Foo has been deprecated. Please investigate the use of AppDomainSetup.Bar instead. https://go.microsoft.com/fwlink/?linkid=14202`, but the corresponding property of `AppDomainSetup` does not exist, confusing developers that stumble upon these obsolete methods.

**Comment by jeffhandley** [comment] 2021-08-01 02:53
I'm closing this as a duplicate of #47255, but I've added the details from this issue into the description there to ensure this is covered.

Thanks for reporting this, @teo-tsirpanis.

**Closed by jeffhandley** 2021-08-01 02:53 UTC
Labels: area-System.Runtime, untriaged
