### ISSUE TITLE
From issue #65696.

### ISSUE THREAD

**Issue by MiyamuraMiyako** [dotnet/runtime#73635] opened 2022-08-09 12:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Run aspnetcore program in `windows service` and `NT Authority\NetworkService` user will crash.

### Steps To Reproduce

1. Create  AspNetCoreWebApi project.
2. Publish sample project.
3. `sc` command install windows service and set obj= "NT Authority\NetworkService".
4. Grant all permission to `NetworkService` for publish path.
5. Run windows service, then program will crash.

### .NET Version

 7.0.100-preview.6.22352.1

**Comment by daviburg** [comment] 2022-08-09 17:45
> @daviburg Because that's issue is closed and locked.

Wrong David ;-)

**Comment by MiyamuraMiyako** [comment] 2022-08-10 05:48
@davidfowl Because that's issue is closed and locked.

**Comment by MiyamuraMiyako** [comment] 2022-08-10 05:51
@daviburg Oh, sorry @ you : )

**Comment by eerhardt** [comment] 2022-08-10 14:36
@MiyamuraMiyako - can you provide a stack trace of the crash? If it is the same as https://github.com/dotnet/runtime/issues/65696, then I believe that was fixed with https://github.com/dotnet/runtime/issues/70007. That commit didn't make 7.0-preview7, but it will be in rc1. If you'd like to try a nightly rc1 build to verify it fixes the issue, that would be great.

**Comment by tarekgh** [comment] 2022-08-10 16:09
@MiyamuraMiyako could you please try install the latest build from https://github.com/dotnet/installer#table and advise if you still see the issue? you are using `7.0.100-preview.6.22352.1` while the fix is not in this build.

**Comment by MiyamuraMiyako** [comment] 2022-08-10 17:35
@eerhardt @tarekgh Yes, I use rc1 build project and issue disappear, Thanks!

**Comment by eerhardt** [comment] 2022-08-10 17:53
Closing as a dupe of https://github.com/dotnet/runtime/issues/70007

**Closed by eerhardt** 2022-08-10 17:53 UTC
Labels: area-Extensions-Hosting, needs-further-triage
