### ISSUE TITLE
Conflicting Dependency Versions for System.Runtime.CompilerServices.Unsafe

### ISSUE THREAD

**Issue by TheXenocide** [dotnet/runtime#43171] opened 2020-10-06 22:21 UTC
It seems this may apply to more than one library within the Microsoft.Extensions ecosystem, but at a minimum Microsoft.Extensions.Configuration.Json has an assembly version conflict baked in that prevents us from being able to run it in an environment where we can't use assembly binding redirects (particularly within an extension to a 3rd party codebase we don't control which performs the actual execution of code). The issue we're currently seeing is coming from the following dependency differences:

```
System.Threading.Tasks.Extensions 4.5.2 -> System.Runtime.CompilerServices.Unsafe (>= 4.5.2) (Assembly Version 4.0.4.1)

System.Text.Json 4.7.0 -> System.Runtime.CompilerServices.Unsafe (>= 4.7.0) (Assembly Version 4.0.6.0)
```

Since the assembly versions do not match, at runtime when our 3rd party software loads our assembly,  we end up with a
`Could not load the file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1 ...` error message

Is there some way besides a binding redirect or assembly resolve event handler that could be used to solve this? I'm not sure how many other libraries in the Microsoft.Extensions ecosystem this might impact, but I did see several others use System.Threading.Tasks.Extensions. Maybe it would be more appropriate for a System.Threading.Tasks.Extensions 4.7.0 release so that it can target System.Runtime.CompilerServices.Unsafe 4.7.0 and all of the 3.1/4.7 package versions can mesh together like the other ones we're using?

**Comment by joperezr** [comment] 2021-02-23 17:44
I believe this is a dupe of https://github.com/dotnet/runtime/issues/28503 which largely just covers the fact of making our OOB packages to not require binding redirects in .NET Framework. As explained above by @ericstj, that would be really hard to achieve so at least for now, it is not in our plans to do so, which means that for now using our packages in .NET Framework may still require binding redirects. I'll go ahead and close this issue as dupe for now so that we can track this request in one single issue, which will help making a case to eventually ask for this feature to ship. @TheXenocide if you don't agree with me closing or don't think this is an exact dupe, please feel free to reopen.

**Closed by joperezr** 2021-02-23 17:44 UTC
Labels: area-System.Runtime.CompilerServices, untriaged
