### ISSUE TITLE
Test failure System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Http2_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://wrong.host.badssl.com/\")

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#67475] opened 2022-04-02 02:44 UTC
Run: [runtime-libraries-coreclr outerloop 20220401.9](https://dev.azure.com/dnceng/public/_build/results?buildId=1694722&view=ms.vss-test-web.build-test-results-tab&runId=46254376&resultId=104392&paneView=debug)

Failed test:
```
net7.0-windows-Release-x64-CoreCLR_release-(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-08e8e40-20200107182504

- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Http2_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://wrong.host.badssl.com/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Http2_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://self-signed.badssl.com/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Http2_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://expired.badssl.com/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_ServerCertificates_Test.UseCallback_BadCertificate_ExpectedPolicyErrors(url: \"https://wrong.host.badssl.com/\", expectedErrors: RemoteCertificateNameMismatch)
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_ServerCertificates_Test.UseCallback_BadCertificate_ExpectedPolicyErrors(url: \"https://expired.badssl.com/\", expectedErrors: RemoteCertificateChainErrors)
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_ServerCertificates_Http2_Test.UseCallback_BadCertificate_ExpectedPolicyErrors(url: \"https://wrong.host.badssl.com/\", expectedErrors: RemoteCertificateNameMismatch)
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_ServerCertificates_Http2_Test.UseCallback_BadCertificate_ExpectedPolicyErrors(url: \"https://expired.badssl.com/\", expectedErrors: RemoteCertificateChainErrors)
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://wrong.host.badssl.com/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://self-signed.badssl.com/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://expired.badssl.com/\")

net7.0-windows-Release-x64-CoreCLR_release-Windows.11.Amd64.ClientPre.Open

- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Http2_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://wrong.host.badssl.com/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Http2_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://self-signed.badssl.com/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Http2_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://expired.badssl.com/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://wrong.host.badssl.com/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://self-signed.badssl.com/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://expired.badssl.com/\")

net7.0-windows-Release-x64-CoreCLR_release-Windows.Amd64.Server2022.Open

- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://wrong.host.badssl.com/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://self-signed.badssl.com/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://expired.badssl.com/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Http2_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://wrong.host.badssl.com/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Http2_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://self-signed.badssl.com/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Http2_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://expired.badssl.com/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_ServerCertificates_Test.UseCallback_BadCertificate_ExpectedPolicyErrors(url: \"https://wrong.host.badssl.com/\", expectedErrors: RemoteCertificateNameMismatch)
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_ServerCertificates_Test.UseCallback_BadCertificate_ExpectedPolicyErrors(url: \"https://expired.badssl.com/\", expectedErrors: RemoteCertificateChainErrors)

net7.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.2004.Amd64.Open)windows.10.amd64.server20h2.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c

- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://wrong.host.badssl.com/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://self-signed.badssl.com/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://expired.badssl.com/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_ServerCertificates_Test.UseCallback_BadCertificate_ExpectedPolicyErrors(url: \"https://wrong.host.badssl.com/\", expectedErrors: RemoteCertificateNameMismatch)
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_ServerCertificates_Test.UseCallback_BadCertificate_ExpectedPolicyErrors(url: \"https://expired.badssl.com/\", expectedErrors: RemoteCertificateChainErrors)

net7.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.Server2022.ES.Open

- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Http2_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://wrong.host.badssl.com/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Http2_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://self-signed.badssl.com/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Http2_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://expired.badssl.com/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_ServerCertificates_Http2_Test.UseCallback_BadCertificate_ExpectedPolicyErrors(url: \"https://wrong.host.badssl.com/\", expectedErrors: RemoteCertificateNameMismatch)
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_ServerCertificates_Http2_Test.UseCallback_BadCertificate_ExpectedPolicyErrors(url: \"https://expired.badssl.com/\", expectedErrors: RemoteCertificateChainErrors)

net7.0-windows-Release-x86-CoreCLR_release-Windows.11.Amd64.ClientPre.Open

- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Http2_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://wrong.host.badssl.com/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Http2_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://self-signed.badssl.com/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Http2_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://expired.badssl.com/\")

net7.0-windows-Release-x86-CoreCLR_release-Windows.Amd64.Server2022.Open

- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Http2_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://wrong.host.badssl.com/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Http2_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://self-signed.badssl.com/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Http2_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://expired.badssl.com/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://wrong.host.badssl.com/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://self-signed.badssl.com/\")
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_DangerousAcceptAllCertificatesValidator_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(url: \"https://expired.badssl.com/\")

net48-windows-Release-x64-Windows.11.Amd64.ClientPre.Open

- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_ServerCertificates_Test.UseCallback_BadCertificate_ExpectedPolicyErrors(url: \"https://wrong.host.badssl.com/\", expectedErrors: RemoteCertificateNameMismatch)
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_ServerCertificates_Test.UseCallback_BadCertificate_ExpectedPolicyErrors(url: \"https://expired.badssl.com/\", expectedErrors: RemoteCertificateChainErrors)

net48-windows-Release-x86-Windows.10.Amd64.Client21H1.Open

- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_ServerCertificates_Test.UseCallback_BadCertificate_ExpectedPolicyErrors(url: \"https://wrong.host.badssl.com/\", expectedErrors: RemoteCertificateNameMismatch)
- System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_ServerCertificates_Test.UseCallback_BadCertificate_ExpectedPolicyErrors(url: \"https://expired.badssl.com/\", expectedErrors: RemoteCertificateChainErrors)
```
**Error message:**
```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.WinHttpException : Error 12007 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The server name or address could not be resolved'.


Stack trace
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 558
   at System.Net.Http.Functional.Tests.HttpClientHandler_DangerousAcceptAllCertificatesValidator_Test.InvalidCertificateServers_CertificateValidationDisabled_Succeeds(String url) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.AcceptAllCerts.cs:line 107
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult() in /_/src/libraries/Common/src/System/Threading/Tasks/RendezvousAwaitable.cs:line 62
   at System.Net.Http.WinHttpHandler.StartRequestAsync(WinHttpRequestState state) in /_/src/libraries/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs:line 1046
```

**Comment by ManickaP** [comment] 2022-04-02 09:08
Duplicate of #63224

**Closed by ManickaP** 2022-04-02 09:08 UTC
Labels: arch-x86, area-System.Net.Http, os-windows, arch-x64, untriaged, blocking-outerloop
