### ISSUE TITLE
LINQ performance: `Count` is twice slower than `Where.Count`

### ISSUE THREAD

**Issue by DoctorKrolic** [dotnet/runtime#69405] opened 2022-05-16 19:50 UTC
I have a simple benchmark for testing LINQ performance:
```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

BenchmarkRunner.Run<Benchmarks>();

[MemoryDiagnoser]
public class Benchmarks
{
    private static readonly int[] _data = Enumerable.Range(0, 100000).OrderBy(o => Guid.NewGuid()).ToArray();

    [Benchmark]
    public int CountOfEven_WhereCount() => _data.Where(x => x % 2 == 0).Count();

    [Benchmark]
    public int CountOfEven_Count() => _data.Count(x => x % 2 == 0);
}
```

And here are the results (I believe this screenshot also contains all required versions info as well):
![VsDebugConsole_oJ42ww7G21](https://user-images.githubusercontent.com/70431552/168669808-da9600dd-f223-4451-b183-8ac16742ef46.png)

So we see that `Count` version allocates less memory, which is ofc good. However is it **twice** slower than the `Where.Count` version. I don't think that more complicated LINQ query should outperform the simplified version of the same action so much.

**Comment by hez2010** [comment] 2022-05-17 01:40
We manually devirtualize for Array and List in Where but not in Count. 
You can turn on dynamic PGO and try again.

**Comment by gfoidl** [comment] 2022-05-17 09:12
See also https://github.com/dotnet/runtime/issues/64728#issuecomment-1029206178 (and following discussion).

**Comment by eiriktsarpalis** [comment] 2022-05-17 14:08
Duplicate of #64728, please refer to the discussion in that thread. Thanks!

**Closed by eiriktsarpalis** 2022-05-17 14:08 UTC
Labels: area-System.Linq, tenet-performance
