### ISSUE TITLE
False positive trim analysis warning despite [DynamicallyAccessedMembers] when using iterator method 

### ISSUE THREAD

**Issue by roji** [dotnet/runtime#63264] opened 2022-01-02 12:46 UTC
### Description

I seem to be getting an incorrect trimming warning when the method in question is an iterator method (with `yield`), while the equivalent non-iterator method generates no warning.

### Reproduction Steps

The following method:

```c#
static IEnumerable<MemberInfo> GetProperties1(
    [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicProperties | DynamicallyAccessedMemberTypes.NonPublicProperties)]
    Type type)
{
    foreach (var propertyInfo in type.GetRuntimeProperties())
    {
        yield return propertyInfo;
    }
}
```

### Expected behavior

No warnings should be emitted, as for the following equivalent which isn't an iterator method:

```c#
static IEnumerable<MemberInfo> GetProperties2(
    [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicProperties | DynamicallyAccessedMemberTypes.NonPublicProperties)]
    Type type)
    => type.GetRuntimeProperties().ToArray();
```

### Actual behavior

GetProperties1 generates the following trim analysis warning:

```
/home/roji/projects/test/Program.cs(16,34): Trim analysis warning IL2077: Program.<<<Main>$>g__GetProperties1|0_0>d.MoveNext(): 'type' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicProperties', 'DynamicallyAccessedMemberTypes.NonPublicProperties' in call to 'System.Reflection.RuntimeReflectionExtensions.GetRuntimeProperties(Type)'. The field 'System.Type Program/<<<Main>$>g__GetProperties1|0_0>d::type' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [/home/roji/projects/test/Test.csproj]
```

### Configuration

.NET SDK 6.0.1 on Ubuntu impish x64.

**Comment by vitek-karas** [comment] 2022-01-02 19:49
This is currently expected: https://github.com/dotnet/linker/issues/2001

The linker doesn't handle compiler generated code, it can only deal with some simple cases specifically around `RequiresUnreferencedCode` attribute and warning suppressions. Data flow (annotations) is not handled right now.

Currently recommended workaround is to move the reflection call into a local function helper and suppress the warning there. So in the sample above, something like this:
```C#
static IEnumerable<MemberInfo> GetProperties1(
    [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicProperties | DynamicallyAccessedMemberTypes.NonPublicProperties)]
    Type type)
{
    foreach (var propertyInfo in TypeGetProperties(type))
    {
        yield return propertyInfo;
    }

    [UnconditionalSuppressMessage(..., Justification = "The type parameter of the parent method has the right annotation")]
    MemberInfo[] TypeGetProperties(Type type) => type.GetRuntimeProperties();
}
```

There should be no perf impact (JIT is likely to inline this). The reason for the local function is to limit the suppression to one specific line of code, so that future changes to the outer method still get analysis and warnings.

**Comment by roji** [comment] 2022-01-02 21:39
@vitek-karas thanks for the explanation and the workaround! Feel free to close this as a duplicate of dotnet/linker#2001 or to keep it open if it helps tracking.

**Comment by vitek-karas** [comment] 2022-01-03 11:49
Closing as this is basically a dupe of the dotnet/linker#2001

**Closed by vitek-karas** 2022-01-03 11:49 UTC
Labels: area-AssemblyLoader-coreclr, untriaged, linkable-framework
