### ISSUE TITLE
[API Proposal]: Add support for DuplicatePropertyNameHandling to System.Text.Json

### ISSUE THREAD

**Issue by sazeesha098** [dotnet/runtime#88536] opened 2023-07-07 19:11 UTC
### Background and motivation

To validate just body of request as valid JSON even before model binding. We need to find if json had duplicated properties.

### API Proposal

```csharp
namespace System.Text.Json;

public enum DuplicatePropertyNameHandling  { Replace = 0, Ignore = 1, Error = 2 }

public partial class JsonSerializerOptions
{
     // Global configuration
     public JsonDuplicatePropertyNameHandling DuplicatePropertyNameHandling { get; set; } = JsonDuplicatePropertyNameHandling.Ignore;
}
```

### API Usage

```csharp
[JsonDuplicatePropertyNameHandling(DuplicatePropertyNameHandling.Error)]
public class MyPoco { }
```

**Comment by gregsdennis** [comment] 2023-07-07 20:26
I suspect there will need to be done considerable changes under the hood to support this.  Current behavior for duplicate properties is an exception when the object is accessed.  It doesn't preload the document at parse time.

**Comment by eiriktsarpalis** [comment] 2023-07-08 13:41
> Current behavior for duplicate properties is an exception when the object is accessed.

I think this only impacts `JsonNode` though right? Generally speaking the default behavior is replace semantics (which suggests to me that `JsonNode` should also have replace semantics by default).

**Comment by eiriktsarpalis** [comment] 2023-07-08 13:42
cc @krwq since superficially this seems to overlap somewhat with the populate semantics feature. Is it something we could support via that feature?

**Comment by krwq** [comment] 2023-07-09 11:00
I think it might be simpler to reuse required members logic - we'd need to adjust it a bit but it works very similarly.

Possibly adjust https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/ReadStackFrame.cs#L123 to handle both required/duplicated. It will also need adjusting JsonPropertyInfo.RequiredPropertyIndex into just PropertyIndex (possibly? or just picking depending on setting). Note that this could technically be also supported per type rather than just globally without much more code but I'm not sure if that would be useful for anyone

**Comment by krwq** [comment] 2023-07-09 11:12
btw the Replace should probably be called Allow or similar since we've added https://github.com/dotnet/runtime/issues/78556

**Comment by gregsdennis** [comment] 2023-07-09 12:13
> I think this only impacts `JsonNode` though right?

Ah, yes.  But it seems they should behave similarly, right?

And, I could always just deserialize a `JsonNode`...

**Comment by eiriktsarpalis** [comment] 2023-07-10 11:54
@sazeesha098 Presumably the difference between `Replace` and `Ignore` is last write wins vs. first write wins?  In your use case is it necessary to support such a distinction or would introducing `Error` suffice?

**Comment by sazeesha098** [comment] 2023-07-10 21:07
Just Error should suffice for now.

**Comment by mehdipanjwani-ains** [comment] 2023-09-28 14:55
This JsonDuplicatePropertyNameHandlingAttribute would be also quite useful for us (Ignore & Replace enums)

**Comment by eiriktsarpalis** [comment] 2024-10-10 10:17
Closing as duplicate of https://github.com/dotnet/runtime/issues/108521#issuecomment-2404687151

**Closed by eiriktsarpalis** 2024-10-10 10:17 UTC
Labels: api-suggestion, area-System.Text.Json
