### ISSUE TITLE
Reflection Loader search has changed since 4.6, and seems wrong now

### ISSUE THREAD

**Issue by ctacke** [dotnet/runtime#81341] opened 2023-01-30 02:38 UTC
### Description

I have an application that loads plug-ins from a child folder. This worked fine in 4.x.  I'm trying to migrate it to a newer runtime and both .NET6 and .NET7 fail to find dependencies of the plug in that are clearly in the app domain root folder.

### Reproduction Steps

The folder structure is like this:
```
/App
MyApp.exe
Dependency.dll
/App/Adapters
PlugIn.dll
```

`PlugIn.dll` depends on `Dependency.dll`, but when I load `PlugIn.dll` via Reflection and attempt to GetTypes(), it fails, complaining about being unable to find `Dependency.dll`.

I can get it to work around it for *most* things with custom resolution like this:

```
private Assembly? CurrentDomain_AssemblyResolve(object? sender, ResolveEventArgs args)
{
    // check the parent folder for the reference
    var engineRoot = AppDomain.CurrentDomain.BaseDirectory;
    var checkPath = Path.Combine(engineRoot, new AssemblyName(args.Name).Name + ".dll");
    if (File.Exists(checkPath))
    {
        return Assembly.LoadFrom(checkPath);
    }
    else
    {
        // try in the `runtimes` folder (SQLite.Interop for example will be here)
    }

    return null;
}

        private void LoadDLL(string filePath)
        {
            try
            {
                AppDomain.CurrentDomain.AssemblyResolve += CurrentDomain_AssemblyResolve;

                IInstanceService instanceService = RootWorkItem.Services.Get<IInstanceService>();
                if (m_systemDLLs.Contains(Path.GetFileNameWithoutExtension(filePath), new CaselessStringComparer())) return;

                var assembly = Assembly.LoadFrom(filePath);

                var adapterTypes = from a in assembly.GetTypes()
                                   where a.GetInterfaces().Contains(typeof(IHostedAdapter))
                                   select a;
...
    }
```
However, things like Sqlite.Interop.dll, which is down in the depths of the `runtimes` sub-tree isn't found.  I'd like to not have to traverse the tree to find it.

To be clear, this all works perfectly well in 4.6 without any custom assembly loading shenanigans

### Expected behavior

Dependency assemblies in the app domain loader path should be found when loading an assembly via reflection

### Actual behavior

AssemblyNotFoundException is thrown, requireing custom code to find and load dependencies

### Regression?

This works fine in .NET 4.6 (and as far back as 3.5).  It is known broken in 6 and 7 (I haven't tried 5.0)

### Known Workarounds

Workaround is explained in the reproduction.  It is a partial workaround.

### Configuration

.NET 7
Windows 10
AMD64

90% sure I've seen this on ARM64 as well, but I'm trying to port the code base before chasing ARM platform vagaries

**Comment by huoyaoyuan** [comment] 2023-01-30 07:11
Note that assembly loading of .NET Core (and 5+) is not totally compatible with .NET Framework, by design.

**Comment by vitek-karas** [comment] 2023-01-30 11:33
As mentioned by @huoyaoyuan the difference in behavior is intentional. Assembly loading in .NET6+ does less work in the runtime, to avoid complex problems with versioning (see binding redirects). Another explicit design choice was to not "search for" assemblies using a set of paths or other rules (.NET Framework looks into GAC, app directory, ...).
The default behavior is to only resolve assemblies which were part of the application during build - SDK writes a file (`app.deps.json`) which lists all of the app's dependencies and those are the only assembly runtime will resolve on its own.
On the other hand there are more customizations possible for assembly resolution and the runtime gives the app a higher level of control of what to load from where.

Plugin scenarios need to customize the assembly resolution. If you want isolated plugins the recommendation is to use `AssemblyLoadContext` along with `AssemblyDependencyResolver`. See this guide and related sample how that is done: https://learn.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support

You can use similar technique (`AssemblyDependencyResolver`) even if you don't want isolation, in which case use the resolver directly from the `AssemblyLoadContext.Default.Resolving` event handler. The downside of loading everything into the default load context is that plugins have to agree on a common version of their dependencies.

As for the `runtime` directory - that is used by the SDK if the app is plublished as a so called "portable" application. Since .NET6+ is multi-platform, portable applications which are supposed to run across multiple platforms may need to carry different builds of some dependencies (obviously all native libraries, but sometimes even managed assemblies need to be platform specific). SDK puts these dependencies into the `runtime` directory. If you use `.deps.json` for the plugins and then `AssemblyDependencyResolver` it will handle all of that for you.
Alternatively if you need the app only for one platform, you can publish is as a RID specific app (specify the `RuntimeIdentifier` or the `-r` command line options) in which case SDK will not create `runtime` directory and just copy the right version of all the dependencies into the main application directory.

**Comment by agocke** [comment] 2023-07-24 20:19
Closing as by-design.

**Closed by agocke** 2023-07-24 20:19 UTC
Labels: area-AssemblyLoader-coreclr, untriaged
