### ISSUE TITLE
Test failure baseservices\\TieredCompilation\\BasicTestWithMcj\\BasicTestWithMcj.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#66917] opened 2022-03-21 01:46 UTC
Failed again in: [runtime-coreclr outerloop 20220320.2
](https://dev.azure.com/dnceng/public/_build/results?buildId=1672894&view=ms.vss-test-web.build-test-results-tab&runId=45913656&resultId=107722&paneView=debug)

Failed test:
```
CoreCLR windows arm Checked no_tiered_compilation @ Windows.10.Arm64v8.Open

- baseservices\\TieredCompilation\\BasicTestWithMcj\\BasicTestWithMcj.cmd
- baseservices\\TieredCompilation\\BasicTest_QuickJitForLoopsOn_R2r\\BasicTest_QuickJitForLoopsOn_R2r.cmd
- baseservices\\TieredCompilation\\BasicTest_DefaultMode_R2r\\BasicTest_DefaultMode_R2r.cmd
- baseservices\\exceptions\\generics\\TypeParameter018\\TypeParameter018.cmd

CoreCLR windows arm Checked @ Windows.10.Arm64v8.Open

- baseservices\\TieredCompilation\\BasicTestWithMcj\\BasicTestWithMcj.cmd
- baseservices\\TieredCompilation\\BasicTest_QuickJitOn_R2r\\BasicTest_QuickJitOn_R2r.cmd
- baseservices\\exceptions\\generics\\try-catch-struct08\\try-catch-struct08.cmd
- baseservices\\exceptions\\generics\\try-fault-struct03\\try-fault-struct03.cmd
- baseservices\\exceptions\\generics\\nested-try-catch01\\nested-try-catch01.cmd
- baseservices\\exceptions\\simple\\ParallelCrash\\ParallelCrash.cmd

R2R-CG2 windows arm Checked @ Windows.10.Arm64v8.Open

- baseservices\\TieredCompilation\\BasicTestWithMcj\\BasicTestWithMcj.cmd
- baseservices\\compilerservices\\RuntimeHelpers\\RuntimeHelpersTests\\RuntimeHelpersTests.cmd
- baseservices\\exceptions\\simple\\HardwareEh\\HardwareEh.cmd
- baseservices\\exceptions\\generics\\try-catch-finally02\\try-catch-finally02.cmd
- baseservices\\exceptions\\simple\\ArrayInit\\ArrayInit.cmd
- baseservices\\TieredCompilation\\TieredVtableMethodTests\\TieredVtableMethodTests.cmd
- baseservices\\threading\\threadstatic\\threadstatic08\\threadstatic08.cmd

R2R-CG2 windows arm Checked no_tiered_compilation @ Windows.10.Arm64v8.Open

- baseservices\\threading\\generics\\threadstart\\GThread07\\GThread07.cmd
- baseservices\\compilerservices\\RuntimeHelpers\\RuntimeHelpersTests\\RuntimeHelpersTests.cmd
- baseservices\\exceptions\\simple\\HardwareEh\\HardwareEh.cmd
- baseservices\\exceptions\\simple\\ArrayInit\\ArrayInit.cmd
- baseservices\\exceptions\\simple\\finally\\finally.cmd
- baseservices\\threading\\regressions\\13662\\13662-b\\13662-b.cmd
```
**Error message:**
```
Failed to load: 'D:\h\w\B7EF0A65\p\coreclr.dll'. Error: 0x000000c1
Failed to load: 'D:\h\w\B7EF0A65\p\coreclr.dll'. Error: 0x000000c1

Return code:      1
Raw output file:      D:\h\w\B7EF0A65\w\B06009B3\uploads\Reports\baseservices.TieredCompilation\BasicTestWithMcj\BasicTestWithMcj.output.txt
Raw output:
BEGIN EXECUTION
call RunBasicTestWithMcj.cmd --runCustomTest D:\h\w\B7EF0A65\w\B06009B3\e\baseservices\TieredCompilation\BasicTestWithMcj\ BasicTestWithMcj.dll
Collect profile without R2R, use profile without R2R
Expected: 100
Actual: -1
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\B7EF0A65\p
D:\h\w\B7EF0A65\w\B06009B3\e\baseservices\TieredCompilation\BasicTestWithMcj\BasicTestWithMcj.cmd
Expected: True
Actual:   False


Stack trace
   at baseservices_TieredCompilation._BasicTestWithMcj_BasicTestWithMcj_._BasicTestWithMcj_BasicTestWithMcj_cmd()
```

**Comment by jakobbotsch** [comment] 2022-03-23 23:19
Duplicate of #66969

**Closed by jakobbotsch** 2022-03-23 23:19 UTC
Labels: arch-arm32, os-windows, area-CodeGen-coreclr, blocking-outerloop
