### ISSUE TITLE
rc1: Performance regressions in CastingPerf benchmarks 

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#75537] opened 2022-09-13 14:55 UTC
Various CastingPerf benchmarks regressed in RC1, e.g.

![image](https://user-images.githubusercontent.com/523221/189934038-b5a0d001-ca51-4836-9fe7-af7d280dcc3b.png)

Namely:

- [ObjFooIsObj2](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_ubuntu%2018.04%2fPerfLabTests.CastingPerf.ObjFooIsObj2.html)
- [ObjFooIsObj](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_ubuntu%2018.04%2fPerfLabTests.CastingPerf.ObjFooIsObj.html)
- [IntObj](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_ubuntu%2018.04%2fPerfLabTests.CastingPerf.IntObj.html)
- [IFooFooIsIFoo](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_ubuntu%2018.04%2fPerfLabTests.CastingPerf.IFooFooIsIFoo.html)
- [FooObjIsNull](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_ubuntu%2018.04%2fPerfLabTests.CastingPerf.FooObjIsNull.html)
- [FooObjIsFoo2](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_ubuntu%2018.04%2fPerfLabTests.CastingPerf.FooObjIsFoo2.html)
- [FooObjIsFoo](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_ubuntu%2018.04%2fPerfLabTests.CastingPerf.FooObjIsFoo.html)
- [FooObjCastIfIsa](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_ubuntu%2018.04%2fPerfLabTests.CastingPerf.FooObjCastIfIsa.html)

Commit range: https://github.com/dotnet/runtime/compare/f58a7902a0b4fc9914494de820a7aae8045abd48...01e2521dcee2a05791228decd2951eee1b9eb757

**Comment by EgorBo** [comment] 2022-09-13 15:04
@jakobbotsch can it be https://github.com/dotnet/runtime/pull/73562? the regression exists only on x64

**Comment by jakobbotsch** [comment] 2022-09-13 15:11
> @jakobbotsch can it be #73562? the regression exists only on x64

I don't see how, that change should barely affect x64.

**Comment by mangod9** [comment] 2022-10-03 20:59
I have verified that setting `COMPlus_GCWriteBarrier=3` improves the perf here for wks. Since the precise write barrier has shown better perf for real world scenarios, we will continue to investigate this in 8.

**Comment by mrsharm** [comment] 2023-08-10 20:14
Closing - there seems to be a general improvement for these benchmarks: 

![image](https://github.com/dotnet/runtime/assets/68247673/5445c50b-3514-4ef9-a7e4-0d33cd55b9eb)
https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_ubuntu%2018.04%2fPerfLabTests.CastingPerf.ObjFooIsObj2.html

**Closed by mrsharm** 2023-08-10 20:14 UTC
Labels: tenet-performance, area-GC-coreclr

**Comment by MichalPetryka** [comment] 2023-08-11 18:55
> Closing - there seems to be a general improvement for these benchmarks:

What's that big regression at the start of the chart there?
