### ISSUE TITLE
.Net application aborts at startup with "Failed to create CoreCLR, HRESULT: 0x80004005" - .Net 7 preview 5

### ISSUE THREAD

**Issue by Webreaper** [dotnet/runtime#70758] opened 2022-06-14 22:25 UTC
### Description

I have a project here: https://github.com/Webreaper/Damselfly which I upgraded to .Net 7 preview 5 this evening, and also updated EF Core and a bunch of other dependencies (https://github.com/Webreaper/Damselfly/compare/master...develop). 

The app compiles and runs fine on my M1 Macbook (I'm using VS for Mac 2022). However, when built and deployed to a docker container, and launched on Linux (I'm using a Synology NAS) it fails with:

`Failed to create CoreCLR, HRESULT: 0x80004005`

The same app launched fine built and ran (on both OSX and Linux) against .Net 7 preview 4. 

I'll do some additional tests tomorrow to see if I can narrow down to the specific update that cause this to break (i.e., is it .Net 7 preview 5 itself, or some other dep, or a combination of the two). The app is a Blazor Server app running as a self-contained single-file executable, but since it never gets as far as initialising the CLR I don't think that Blazor or ASP.Net is relevant. I've also tried disabling trimming, but it didn't resolve the issue.

I guess my first question is - how do I go about getting additional debugging information to figure out what's causing this problem?

### Reproduction Steps

Take my app, build and run it against .Net 7 preview 4. It works. Upgrade to preview 5, it fails to start. 

### Expected behavior

App runs successfully on both OSX and Linux.

### Actual behavior

App runs successfully on OSX, but on Linux the app fails to start with `Failed to create CoreCLR, HRESULT: 0x80004005`

### Regression?

Yes, this app worked with .Net 7 preview 4.

**Comment by AaronRobinsonMSFT** [comment] 2022-06-15 05:17
@Webreaper You might start with setting the environment variable `COREHOST_TRACE=1`. Details on this can be found at https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/default-probing#how-do-i-debug-the-probing-properties-construction and https://github.com/dotnet/runtime/blob/main/docs/design/features/host-tracing.md.

/cc @elinor-fung

**Comment by agocke** [comment] 2022-06-15 06:44
Unfortunately COREHOST_TRACE doesn't tend to work well with EFAIL (that's what 0x80004005 is). That means something has gone wrong during runtime startup. @vitek-karas might have some ideas, and + @VSadov  for potential single-file issues.

**Comment by Webreaper** [comment] 2022-06-15 06:55
Okay, thanks. Any other logging I can turn on?

Just on the off-chance it yields any clues, here's the COREHOST_TRACE output for the process (had to rename to .txt, but if you rename to .html it'll render as a table of log entries, newest-first).

[damselfly_log.txt](https://github.com/dotnet/runtime/files/8906573/damselfly_log.txt)

I'll continue fiddling with some build settings to see if I can find an explicit link to something.

**Comment by am11** [comment] 2022-06-15 07:32
@Webreaper, does it still fail if you switch to daily build plan?

```diff
-         dotnet-version: '7.0.100-preview.5.22307.18'
+         dotnet-version: '7.0.100-preview.6.22314.18'
```

**Comment by Webreaper** [comment] 2022-06-15 07:50
Hey @am11, I just tried that, but it's failing to pull packages from Nuget in my Github build, e.g.:

```
/home/runner/work/Damselfly/Damselfly/Damselfly.Migrations.Sqlite/Damselfly.Migrations.Sqlite.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Runtime.linux-x64 with version (= 7.0.0-preview.6.22312.1) [/home/runner/work/Damselfly/Damselfly/Damselfly.Web/Damselfly.Web.csproj]
/home/runner/work/Damselfly/Damselfly/Damselfly.Migrations.Sqlite/Damselfly.Migrations.Sqlite.csproj : error NU1[10](https://github.com/Webreaper/Damselfly/runs/6895291025?check_suite_focus=true#step:5:11)2:   - Found 89 version(s) in nuget.org [ Nearest version: 7.0.0-preview.5.22301.12 ] [/home/runner/work/Damselfly/Damselfly/Damselfly.Web/Damselfly.Web.csproj]
```
Is there anything else I need to switch to allow me to pull that newer version (I've not used the dailies before)?

**Comment by am11** [comment] 2022-06-15 07:52
https://github.com/Webreaper/Damselfly/commit/3d3e7dd8307375c6c2d9c4eba386b9b56bf76628#r76136400

**Comment by Webreaper** [comment] 2022-06-15 07:53
Thanks, just saw that!

**Comment by Webreaper** [comment] 2022-06-15 09:03
Okay, thanks to @am11 's help, I got a build working using the daily build, but I still see the same CoreCLR failure.

**Comment by Webreaper** [comment] 2022-06-15 09:21
Okay, just to see if we can find a more simple repro, and it seems this problem happens with my other projects too. So for example, this is a pretty simple console app without much code: 

https://github.com/Webreaper/SonarrAutoImport

I cloned it, switched the framework to `net-7.0`, and the ran:

```
dotnet publish -r ubuntu.18.04-x64 -c Release /p:PublishSingleFile=true /p:PublishTrimmed=false /p:Version=1.5.0
```
Copied this to my Synology Linux box, and ran it. I get the CoreCLR failure. Next I tried removing the publish single file stuff, so ran:
```
dotnet publish -r ubuntu.18.04-x64 -c Release /p:Version=1.5.0
```
and copied the whole publish folder to the server and ran it. I also get the same CoreCLR error. So this seems something fundamentally broken with the ubuntu x64 targetting in Preview 5. :)

**Comment by am11** [comment] 2022-06-15 10:05
So far, I am unable to reproduce the crash locally.

```sh
$ docker build -t foo1 << EOF
FROM webreaper/damselfly-base:latest
ENTRYPOINT /bin/bash
EOF

$ dotnet7 --version
7.0.100-preview.6.22314.18

$ dotnet7 publish -r ubuntu.18.04-x64 -c Release /p:PublishSingleFile=true  /p:PublishTrimmed=false /p:Version=1.5.0

$ docker run -v$(pwd)/SonarrAutoImport/bin/Release/net7.0/ubuntu.18.04-x64/publish:/app1 -it foo1
root@76178c95c99c:/# /app1/SonarrAutoImport 
[10:04:07.747--INF] === QbtCleanup Log Started ===
[10:04:07.837--INF] LogLevel: Information
[10:04:07.953--ERR] Settings not found: Settings.json
```

**Comment by Webreaper** [comment] 2022-06-15 10:10
BTW, you don't need to use the damselfly-base image, that shouldn't be relevant. 

Wonder if it's something special about Synology's flavour of linux.... is there any way to get more debug info about the CLR startup failure?

**Comment by Webreaper** [comment] 2022-06-15 10:19
One other thought - it could possibly be something related to my build env etc. (M1 Mac). If you want to try the actual binary that's failing on my Synology host, you could pull it from here: https://drive.google.com/file/d/1eW-olYnbcG8L8oMfdSi1bnEvDwQsnGT4/view?usp=sharing (understand if you don't want to or can't though!).

**Comment by am11** [comment] 2022-06-15 10:32
That worked as well:
```sh
~/Downloads/autoimport$ unzip SonarrAutoImport.zip 
Archive:  SonarrAutoImport.zip
  inflating: SonarrAutoImport        l
  inflating: __MACOSX/._SonarrAutoImport  

~/Downloads/autoimport$ ls
__MACOSX  SonarrAutoImport  SonarrAutoImport.zip

~/Downloads/autoimport$ docker run -v$(pwd):/app1 -it foo1

root@cce1b05e8e65:/# cd app1
root@cce1b05e8e65:/app1# ./SonarrAutoImport 
[10:22:20.959--INF] === QbtCleanup Log Started ===
[10:22:21.060--INF] LogLevel: Information
[10:22:21.167--ERR] Settings not found: Settings.json
```

> Wonder if it's something special about Synology's flavour of linux.... is there any way to get more debug info about the CLR startup failure?

Yes there is [SOS plugin for lldb](https://github.com/dotnet/diagnostics/blob/22c9d6b6f259c45b8e1eba609eac6cf7c9aed373/documentation/installing-sos-instructions.md#installing-sos-on-linux-and-macos), which is what I was going to use to obtain the backtrace. Prerequisite is that you have dotnet and lldb (which has dependencies on llvm and clang libraries) installed. Setting up debugger in production environment is usually not ideal. Which is why I was trying to reproduce it in a (throw-away) staging environment.

**Comment by vitek-karas** [comment] 2022-06-15 10:32
Unfortunately not many ideas on my end. The one case where this happens which is easily discoverable is if `System.Private.CoreLib.dll` is missing - can you just check that it's there in the app? (I assume it is, but to be sure).

You mention that this got broken by Preview 5. Did you have a chance to try it on a different machine?
My simple attempt on a Ubuntu WSL worked just fine (hello world).

Other things to try:
* Install a private copy of the Preview5 runtime (unzip into a directory from the tar.gz on the download page) and try to run just simple `dotnet --info` - see if that works
* Can you try Preview4 (the one which used to work) on the machine where it fails now? (trying to figure out if this might be something with the machine which changed).

Out of curiosity - why do you publish for a specific version of Ubuntu? Does one of your dependencies have a Ubuntu specific asset?

**Comment by Webreaper** [comment] 2022-06-15 10:37
> That worked as well

Okay, that's a good datapoint, as it implies there's something very specific about the Synology OS that's likely to be affecting this. 

> * Can you try Preview4 (the one which used to work) on the machine where it fails now? (trying to figure out if this might be something with the machine which changed).

That's the key point here - this works fine with Preview 4 which I've been running on the same host for about 3-4 weeks now. 

> Out of curiosity - why do you publish for a specific version of Ubuntu? Does one of your dependencies have a Ubuntu specific asset?

Possibly just because that's how it worked a couple of years ago and I've never bothered to change it. 😁   I am targetting an ubuntu base docker image, and there are some platform-specific things in the build of Damselfly (I use tensorflow and some other stuff that has to run native). But I could try an alternative RID - what would you recommend, 'linux-x64' or something more generic like that?

**Comment by vitek-karas** [comment] 2022-06-15 10:43
I don't think the RID will make a difference for this issue. that said `linux-x64` should work just fine.
I was curious due to other discussions we're having around RIDs (they're way too complex, so we're trying to simplify them) and one of the theories is that distro specific RIDs are very rare (as in, you don't need them almost ever).

Could you try to run the `dotnet --info` from unzipped install? That would rule out problems with a specific app versus the runtime itself being broken on that OS.

**Comment by Webreaper** [comment] 2022-06-15 10:49
Output of preview-5 extracted 'install': 
```
./dotnet --info

global.json file:
  Not found

Host:
  Version:      7.0.0-preview.5.22301.12
  Architecture: x64
  Commit:       425fedc0fb

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 7.0.0-preview.5.22301.12 [/volume1/homes/admin/SonarrImport/dotnet7preview5/dotnet-runtime-7.0.0-preview.5.22301.12-linux-x64/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

**Comment by Webreaper** [comment] 2022-06-15 11:00
> That worked as well. 

Okay, sorry, @am11 , I think where I'm making a bunch of changes I accidentally uploaded the .Net 6 version, which also works for me. Can you try this one, which is very definitely the .Net 7 preview 5 build. /Users/markotway/LocalCloud/Development/SonarrAutoImport/SonarrAutoImport/bin/Release/net7.0/linux-x64/publish/

**Comment by am11** [comment] 2022-06-15 11:35
Works for me on Ubuntu docker as well. You can run x64 ubuntu container on M1 with `docker run -it amd64/ubuntu` and install icu `apt update && apt install -y libicu-dev`. Run this app and it should work.

**Comment by Webreaper** [comment] 2022-06-15 11:37
> Does it work if you don't publish as single-file?

I tried this earlier, so: `dotnet publish -r ubuntu.18.04-x64 -c Release /p:Version=1.5.0` and copied the whole thing across to the linux host and it still fails with the CoreCLR issue. 

It's a weird one, huh?

**Comment by Webreaper** [comment] 2022-06-15 11:38
>

**Comment by janvorli** [comment] 2022-06-15 20:45
@Webreaper can you please try to set env var `COMPlus_EnableWriteXorExecute=0` before launching your app and see if it makes a difference? This is one of the things that we've changed in preview 6 (it was disabled by default, now it is enabled by default).

**Comment by Webreaper** [comment] 2022-06-15 21:11
BOOM. That's it - setting that makes it work. Nice spot!

```
admin@PoundNAS:~/SonarrImport$ ./SonarrAutoImportPreview5 
Failed to create CoreCLR, HRESULT: 0x80004005
admin@PoundNAS:~/SonarrImport$ export COMPlus_EnableWriteXorExecute=0
admin@PoundNAS:~/SonarrImport$ ./SonarrAutoImportPreview5 
[22:10:32.717--INF] === Sonarr Auto Import Log Started ===
[22:10:33.787--INF] LogLevel: Information
```

Anything else I can check/test/investigate to help you track down why that new feature breaks it?

**Comment by janvorli** [comment] 2022-06-15 21:18
Could you please run it without the env var set using the `strace` tool as follows and share the generated `trace.log` file e.g. as a gist? This will trace all the syscalls .NET runtime has made, the arguments passed to those and their results and I should be able to see what was failing. 
```
strace -f -o trace.log ./SonarrAutoImportPreview5
```

**Comment by Webreaper** [comment] 2022-06-15 21:27
Will give that a go. The challenge is that `strace` isn't available on synology. So I've got to either figure out how to install it, or possibly add it to the Damselfly docker image and try running it there.

**Comment by janvorli** [comment] 2022-06-15 21:53
@Webreaper what is the Linux kernel version on your Synology device? If it is older than 3.17, that could explain the failure.

**Comment by Webreaper** [comment] 2022-06-15 21:57
Looks like that's it: 
```
admin@PoundNAS:~$ uname -r
3.10.108
```

**Comment by Webreaper** [comment] 2022-06-15 22:07
Sounds like we've got to the bottom of it, but just in case it helps, here's that strace log from Damselfly.

[trace.log](https://github.com/dotnet/runtime/files/8913506/trace.log)

Presumably the easy fix for this is for you to check the linux kernel version at startup and set `COMPlus_EnableWriteXorExecute=0` if it's older than 3.17?

**Comment by janvorli** [comment] 2022-06-15 23:05
Yes, the log confirms that:
```
memfd_create("doublemapper", MFD_CLOEXEC) = -1 ENOSYS (Function not implemented)
```
You are right, we can either disable the W^X when this syscall isn't implemented or possibly fall back to using `shm_open`. Given the fact that the 3.17 was released in 2015, I tend to the first option.

**Comment by Webreaper** [comment] 2022-06-16 07:03
Sounds good. Happy for you to close this issue (presuming you'll spin off a dev ticket for preview 6/7 to fix as above). I've updated my build to set the env var which will workaround the problem until then. 

Appreciate all the help, everyone!

**Comment by am11** [comment] 2022-06-16 07:28
The runtime introspection approach is better than version check. CentOS 7 (aka pretty important distro) has kernel version `3.10.0-1160.el7.x86_64` and it doesn't fail `9858  memfd_create("doublemapper", MFD_CLOEXEC) = 8`.

> COMPlus__

minor nit: the way runtime config lookup works is for a desired config XYZ, it first looks for  `DOTNET_XYZ` then fallback to "legacy" `COMPlus_XYZ`. So here, you can simply use `DOTNET_EnableWriteXorExecute` to avoid an extra probe.

**Comment by janvorli** [comment] 2022-06-16 07:41
@Webreaper I'll keep this open to track it until the fix is in.
@am11 my plan is to base it on the failed `memfd_create` rather than a version check.

**Comment by Webreaper** [comment] 2022-06-16 08:20
BTW, some additional info, in case it's of interest. My friend who tested the binary on his WIndows WSL setup got me the kernel version:
```
ngm@GAMER:~$ uname -r
4.4.0-19041-Microsoft
```
So I'm guessing that MSFT's Win10 WSL Kernel isn't versioned consistently or is built in a different way.

**Comment by janvorli** [comment] 2022-06-16 08:25
Has he verified that it fails due to the same issue? This kernel version should support this syscall, so I'd think it is some other problem here.

**Closed** 2022-06-20 07:05 UTC
Labels: area-VM-coreclr, in-pr
