### ISSUE TITLE
Process.ProcessName throws for services.exe when accessed from a non-admin user

### ISSUE THREAD

**Issue by schuettecarsten** [dotnet/runtime#70007] opened 2022-05-31 10:11 UTC
`Process.ProcessName` throws when the process is an admin process (like "services.exe") and the current app is running as a low privilege user. This is a regression from .NET 6, and it breaks `Microsoft.Extensions.Hosting.WindowsServices` when running as a non-admin user.

This could possibly be a regression from #59672.

### Repro Steps

1. Build a console app as below:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
```

```C#
using System.Diagnostics;

namespace ConsoleApp1
{
    internal class Program
    {
        const int ServicesProcessId = 756;

        static void Main(string[] args)
        {
            var services = Process.GetProcessById(ServicesProcessId);
            Console.WriteLine(services.ProcessName);
        }
    }
}
```

2. Look in Task Manager for the `services.exe` process and replace the ServiceProcessId with the process ID for your current machine.

3. Run the app as you, it prints
```
services
```

4. Run the app as a non-admin, low privilege user
```
Unhandled exception. System.InvalidOperationException: Process has exited, so the requested information is not available.
   at System.Diagnostics.Process.get_ProcessName()
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\eerhardt\source\repos\WindowsService1\ConsoleApp1\Program.cs:line 12
```

5. Change the `TargetFramework` to `net6.0`, and run as the same non-admin, low privilege user:
```
services
```

### Original Report

I come back to the issue #67093, which is closed. The error still occurs with preview.4 and todays nightly build, but only on Windows Server 2016, not on my local Windows 11 developer machine. The error is:

```
Application: CloudManagementTool.WorkerService.exe
CoreCLR Version: 7.0.22.27203
.NET Version: 7.0.0-preview.5.22272.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException: The type initializer for 'CloudManagementTool.WorkerService.WorkerService' threw an exception.
 ---> System.InvalidOperationException: Process has exited, so the requested information is not available.
   at System.Diagnostics.Process.get_ProcessName()
   at Microsoft.Extensions.Hosting.WindowsServices.WindowsServiceHelpers.IsWindowsService()
   at ConsoleApp1.Program.<Main>(String[] args) in D:\Test\Program.cs:line 13
```

A reproducing sample program is quite short, but it only crashes on Windows Server 2016 and when registered and executed as a service. Starting the same code directly from the console works fine.

```
public class Program
{
	public static async Task Main(string[] args)
	{
		var isService = WindowsServiceHelpers.IsWindowsService();
		if (isService)
		{
			// ...
```

This issue becomes critical now, because it will make the 7.0 version unsable for windows services on Windows Server 2016.

**Comment by eerhardt** [comment] 2022-05-31 19:53
@schuettecarsten - I am not able to repro this issue on my machine. Here is the winver:

![image](https://user-images.githubusercontent.com/8291187/171272594-cc46e2ab-728d-4a24-baeb-4f2c063ddd13.png)

And my project:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="7.0.0-preview.4.22229.4" />
  </ItemGroup>

</Project>
```

```C#
using Microsoft.Extensions.Hosting.WindowsServices;

namespace ConsoleApp1
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var isService = WindowsServiceHelpers.IsWindowsService();
            string logContent = "Is a service " + isService;
            logContent += Environment.NewLine + typeof(object).Assembly.Location;

            File.WriteAllText(@"C:\Users\eerhardt\source\repos\WindowsService1\ConsoleApp1\bin\Debug\log.txt", logContent);
        }
    }
}
```

I created the service using:

```
$sc.exe create ".NET Service" binpath="C:\Users\eerhardt\source\repos\WindowsService1\ConsoleApp1\bin\Debug\net7.0\ConsoleApp1.exe"
```

And the output:
```
Is a service True
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.0-preview.4.22229.4\System.Private.CoreLib.dll
```

Can you add more information to this issue? What exact Windows version? What version of .NET are you using? What's your full project and code? etc.

**Comment by schuettecarsten** [comment] 2022-05-31 20:04
This is the Windows server version that I am using:

![image](https://user-images.githubusercontent.com/1275166/171275074-d19f0256-35dc-4d6e-a57a-ad89b97bb1b8.png)

**Comment by schuettecarsten** [comment] 2022-05-31 20:23
Ok, to reproduce the exception, use a local user on your server and run the service in this user account. To register the service, use the following command:

```
sc create test binPath=C:\Tools\Test\ConsoleApp3.exe obj=<username> password=<password>
```

**Comment by eerhardt** [comment] 2022-05-31 22:04
> Ok, to reproduce the exception, use a local user on your server and run the service in this user account. 

Perfect. This was the missing information that helped me reproduce this error. I have updated the top post with a minimal reproduction app, and moved it to the appropriate area.

FYI - @SteveDunn, as the author of #59672. I didn't go as far as to revert #59672 and ensure it works, but the change that broke this scenario came after 6.0, and still exists in 7.0-preview4.

**Comment by SteveDunn** [comment] 2022-06-01 04:12
@eerhardt - I'm happy to take a look at this, although I don't have a copy of Windows Server 2016, and I probably won't get a chance to look until next week. Are there VM images on Windows Server 2016? (and were the repro's done on a VM?)

**Comment by danmoseley** [comment] 2022-06-01 04:47
Cc @jaykrell  who recommended the API change (assuming that was what regressed it) and might have an idea why Windows Server is special.

**Comment by schuettecarsten** [comment] 2022-06-01 05:51
@jaykrell, @eerhardt , @SteveDunn - I just tested, the exception also occurs on Windows 11 and my local developer machine - as long as I use a dedicated local user.

```
Application: ConsoleApp3.exe
CoreCLR Version: 7.0.22.22904
.NET Version: 7.0.0-preview.4.22229.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: Process has exited, so the requested information is not available.
   at System.Diagnostics.Process.get_ProcessName()
   at Microsoft.Extensions.Hosting.WindowsServices.WindowsServiceHelpers.IsWindowsService()
   at Program.<Main>$(String[] args) in C:\Users\CSchuette\source\repos\ConsoleApp3\Program.cs:line 6
   at Program.<Main>(String[] args)
```

```
Name der fehlerhaften Anwendung: ConsoleApp3.exe, Version: 1.0.0.0, Zeitstempel: 0x626c4e6c
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.22000.708, Zeitstempel: 0x89f799f7
Ausnahmecode: 0xe0434352
Fehleroffset: 0x000000000004474c
ID des fehlerhaften Prozesses: 0x7c3c
Startzeit der fehlerhaften Anwendung: 0x01d8757b623d30eb
Pfad der fehlerhaften Anwendung: C:\Users\CSchuette\source\repos\ConsoleApp3\bin\Release\net7.0\publish\win-x64\ConsoleApp3.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\KERNELBASE.dll
Berichtskennung: a124e10b-23dd-48b6-9996-0de115e40030
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
```

**Comment by jaykrell** [comment] 2022-06-01 06:04
Oh this is terrible, I am sorry. The new direct/efficient way, publically documented, requires certain documented access.
https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-queryfullprocessimagenamew
The old way doesn't require as much access.
Is it acceptable to try the new way, and fallback upon access denied? Or might as well just have one slower but uniform way?
Win32 is unfortunately not always what we'd like. :(

**Comment by schuettecarsten** [comment] 2022-06-01 07:19
@jayrekk - when I look into the changes of https://github.com/dotnet/runtime/pull/59672, I can see that the behaviour is changed in another way: The old code checked for a populated processInfo and returned the process name, it did not check if the process was exited when the processInfo was already filled. So it was possible to query the process name of an exited process as long as processInfo was filled earlier.

The new implementation always checks for a NonExitedId before trying to fill the processName field (https://github.com/SteveDunn/runtime/blob/a4223dc25e6c0ff7da1185f0559b40d0ae75d3da/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Windows.cs#L867). Why? If processInfo is filled, a process name is available and can be used (line 872). Only check for an exited process when kernel APIs are called (line 877).

As a solution, maybe it's a good idea to wrap the call of `ProcessManager.GetProcessName(_processId, _machineName);` (line 877) in a try/catch and fall back the old implementation - enure that processInfo is filled and return process name from there.

**Comment by eerhardt** [comment] 2022-06-01 12:15
> Windows Server

This repros on my regular Windows 10 machine as well.

**Comment by jaykrell** [comment] 2022-06-01 15:53
I believe the other difference noted is because the old code did not work on terminated processes (NtQuerySystemInformation skips them) but the new way does (when it doesn't get access denied).

**Comment by schuettecarsten** [comment] 2022-06-01 16:03
I've created a PR with my suggestion for a solution for this. Please take a look at #70073

**Comment by Jozkee** [comment] 2022-07-26 17:43
Closed by https://github.com/dotnet/runtime/issues/70007.

**Closed by Jozkee** 2022-07-26 17:43 UTC
Labels: area-System.Diagnostics.Process, regression-from-last-release
