### ISSUE TITLE
.net 9 Preview 4 NetworkInterface.GetIPProperties().GatewayAddresses is broken and always empty

### ISSUE THREAD

**Issue by philipag** [dotnet/runtime#102983] opened 2024-06-03 07:42 UTC
### Description

In .Net 9 Preview 4 NetworkInterface.GetIPProperties().GatewayAddresses is broken on Windows 11 and does not return gateways.  I THINK this was working in Preview 2 but not sure.  It does work properly in .net 8.

### Reproduction Steps

The attached sample is configured for .net 9 and shows the result "numInterfacesWithGateways: 0" in the console. If you change the csproj file to use .net 8 instead, then it shows the correct  "numInterfacesWithGateways: 1" on my test system.

[GatewayMissing.zip](https://github.com/user-attachments/files/15530406/GatewayMissing.zip)

### Expected behavior

NetworkInterface.GetIPProperties().GatewayAddresses should contain gateways for interfaces that have them.

### Actual behavior

NetworkInterface.GetIPProperties().GatewayAddresses should return correct results like it did in .Net 8.

### Regression?

Yes, the sample works properly with .Net 8, and I THINK it was working with .Net 9 preview 2.

### Known Workarounds

none

### Configuration

.Net 9 preview 4

### Other information

Looking at the .Net tests, they do not verify that the test machine has at least one gateway configured.  This should probably be added to the test in order to catch this problem moving forward.

**Comment by rzikm** [comment] 2024-06-03 08:26
Seems like duplicate of https://github.com/dotnet/runtime/issues/101710

**Comment by philipag** [comment] 2024-06-03 09:19
@rzikm  Yes sounds like the same issue.  I will close this one and wait for the next preview to see if this works properly.

**Closed** 2024-06-03 09:19 UTC
Labels: area-System.Net, untriaged
