### ISSUE TITLE
[Feature request]: Support instrumentation scope attributes on ActivitySource

### ISSUE THREAD

**Issue by lmolkova** [dotnet/runtime#93795] opened 2023-10-20 21:54 UTC
When creating a tracer (`ActivitySource`) users should be able to specify a set of instrumentation scope attributes   - https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#get-a-tracer.
See https://github.com/open-telemetry/opentelemetry-dotnet/issues/4316 for the context.

Instrumentation scope attributes can be used to reduce instrumentation overhead and reduce the over-the-wire size of attributes.

For example, Azure SDK provides Azure resource provider namespace is used by Azure Monitor (and can be used by other backends) to show icons, find corresponding resources in Azure, and allow navigating to them, etc. this value is constant for a given tracer and should be passed as an instr scope attribute rather than span attribute.

.NET does not allow to provide such attributes as of today.

**proposal added by @tarekgh**

## Proposal

```diff

namespace System.Diagnostics;

    public sealed class ActivitySource : IDisposable
    {
        public ActivitySource(string name, string? version = "") { ... }
+       public ActivitySource(string name, string? version, IEnumerable<KeyValuePair<string, object?>>? tags) { ... }

+       public IEnumerable<KeyValuePair<string, object?>>? Tags { get; }
    }
```

## Alternative Proposal

```C#
namespace System.Diagnostics;

    public class ActivitySourceOptions
    {
        public ActivitySourceOptions(string name) {    }

        public string Name { get; set; }
        public string? Version { get; set; }
        public IEnumerable<KeyValuePair<string, object?>>? Tags { get; set; }
    }

    public sealed class ActivitySource : IDisposable
    {
        ...
        public ActivitySource(ActivitySourceOptions options) { ... }
        
        public IEnumerable<KeyValuePair<string, object?>>? Tags { get; }
    }

```

**Comment by tommcdon** [comment] 2023-10-23 18:24
Assigning to @noahfalk to help coordinate

**Comment by tarekgh** [comment] 2023-10-23 18:35
This is a duplicate of https://github.com/dotnet/runtime/issues/63651. @lmolkova can we close this and continue the discussion on the other one? 

CC @cijothomas @reyang

**Comment by lmolkova** [comment] 2023-10-23 21:22
thanks @tarekgh and sorry I did not find the original issue. The original one still does not cover the instrumentation scope attributes, so I'd prefer to keep it open. I'll modify the description to scope the issue to them.

**Comment by tarekgh** [comment] 2023-10-23 21:42
Thanks @lmolkova for clarification. We already done https://github.com/dotnet/runtime/issues/84321 in .NET 8.0. Is that what you are asking for? or you want to have the same for ActivitySource too?

**Comment by lmolkova** [comment] 2023-10-23 22:12
Cool! Yes, I mean `ActivitySource`, great to know it's addressed on meters.

**Comment by terrajobst** [comment] 2024-05-21 18:03
* We should make it simpler
    - Have one method with just the required parameter (name)
    - Have one method that takes all the optional parameters
    - We can't remove methods, but we can hide them and remove all optionality to avoid ambiguity

```C#
namespace System.Diagnostics;

public partial class ActivitySource
{
    // Existing, left as-is
    // public ActivitySource(string name);

    // Existing, remove optionality and mark EB never
    [EditorBrowsable(EditorBrowsableState.Never)]
    public ActivitySource(string name, string? version);

    // New
    public ActivitySource(string name, string? version = "", IEnumerable<KeyValuePair<string, object?>>? tags = default);

    public IEnumerable<KeyValuePair<string, object?>>? Tags { get; }
}
```

**Closed** 2024-05-30 00:39 UTC
Labels: api-approved, api-suggestion, blocking, in-pr, area-System.Diagnostics.Activity
