### ISSUE TITLE
Publishing .net5 winform app gets  "Invalid input specification: Found multiple entries with the same BundleRelativePath"

### ISSUE THREAD

**Issue by xiaoyuvax** [dotnet/runtime#52671] opened 2020-11-17 09:41 UTC
# Publishing .net5 winform app to single file gets  "Found multiple entries with the same BundleRelativePath"

Seen while publishing  with options of:
.net5 
self-contained
win-x64 
single file 
ReadyToRun

... can't get a clue where multiple entries are, not a hint.

Console output:
15> “GenerateBundle” task failed unexpectedly.
15>System.ArgumentException: Invalid input specification: Found multiple entries with the same BundleRelativePath
15>   in Microsoft.NET.HostModel.Bundle.Bundler.GenerateBundle(IReadOnlyList`1 fileSpecs)
15>   in Microsoft.NET.Build.Tasks.GenerateBundle.ExecuteCore()
15>   in Microsoft.NET.Build.Tasks.TaskBase.Execute()
15>   in Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
15>   in Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

Publish without "single file" option would not produce this exception.

**Comment by vitek-karas** [comment] 2021-05-12 21:19
This is basically a duplicate of multiple issues in runtime and sdk repos. For example:
https://github.com/dotnet/runtime/issues/48112
https://github.com/dotnet/sdk/issues/10621
https://github.com/dotnet/sdk/issues/3465

In .NET 6 we improved the error message to contain the file paths which cause the problem. We also allow exact duplicates (we effectively ignore them), as that seems to be by far the most common case.

https://github.com/dotnet/runtime/pull/50476 is the change which allows duplicates when building single-file specifically. https://github.com/dotnet/sdk/issues/16576 tracks a larger SDK problem which may impact any part of the publish pipeline.

You can try to build your app with latest .NET 6 SDK - you don't need to upgrade your app to .NET 6, just use .NET 6 SDK to build it.

**Comment by xiaoyuvax** [comment] 2021-05-31 04:32
so beside building using .NET 6, there's no other workaround?

**Comment by xiaoyuvax** [comment] 2021-05-31 06:13
.NET 6 Tested OK! 
.NET 6.0.100-preview.4.21255.9 provided a list of duplicated files (but can u pls add a linefeed at the end of each path) .
In my case, an attached script file output to target folder was duplcated in a dependent library, just after deleted one copy it built successfully with Single File option.
Thanks!

**Comment by vpenades** [comment] 2021-05-31 12:00
> In .NET 6 we improved the error message...

Given this is giving so many headaches, why this was not fixed for Net5 SDK?

**Comment by codebolt** [comment] 2021-06-08 11:39
> In .NET 6 we improved the error message to contain the file paths which cause the problem. We also allow exact duplicates (we effectively ignore them), as that seems to be by far the most common case.
> (...)
> You can try to build your app with latest .NET 6 SDK - you don't need to upgrade your app to .NET 6, just use .NET 6 SDK to build it.

I installed the latest .NET 6 SDK preview and verified that it's running in the VS terminal using "dotnet --info". However, I'm still just seeing the same "Found multiple entries" error without any extra information when I tried to publish. Any idea what my problem could be?

**Comment by cliang57** [comment] 2021-06-17 12:12
Using .NET 6 SDK fixed the issue for me. I was using .NET 5 SDK previously.

**Comment by savian-net** [comment] 2021-06-30 04:03
Installing VS 2022 and publishing found the issue. In case others see it, my problem was that I had Copy always on the .NET XML documentation file in the project root. The XML was already being pushed to bin. Same file but removing the copy fixed the issue. HTH someone.

**Comment by vitek-karas** [comment] 2021-07-14 20:08
Currently we don't plan to backport this to .NET 5. If you have a .NET 5 project which needs the changes you can use latest .NET 6 SDK to build the .NET 5 project (SDKs are fully backward compatible).

**Closed by vitek-karas** 2021-07-14 20:08 UTC
Labels: area-Single-File, untriaged
