### ISSUE TITLE
Strange behavior of IntersectBy

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#102112] opened 2024-05-11 10:35 UTC
### Description

Strange behavior of IntersectBy; in theory, it should also output index3.
![image](https://github.com/dotnet/runtime/assets/61237140/671a620c-0e1e-4ee3-a821-c92625cd8b02)

### Reproduction Steps

https://sharplab.io/#gist:c1c562972a180d52794397573470d812

```
using System;
using System.Linq;
using System.Web;

    int[] array = new int[3];
    array[0] = 1;
    array[1] =2;
    array[2] =2;

    Info[] arrayTwo = new Info[3];
    arrayTwo[0] = new Info(1, "index 1");
    arrayTwo[1] = new Info(2, "index 2");
    arrayTwo[2] = new Info(2, "index 3");
  var result =   arrayTwo.IntersectBy(array,
                                      a => a.id);
    foreach(var item in result)
    {
        Console.WriteLine(item);
    }
    record Info(int id, string text);

```

### Expected behavior

-

### Actual behavior

-

### Known Workarounds

-

### Configuration

-

### Other information

-

**Comment by stephentoub** [comment] 2024-05-11 11:32
Duplicate of https://github.com/dotnet/runtime/issues/75066

**Comment by Mr0N** [comment] 2024-05-11 11:43
![image](https://github.com/dotnet/runtime/assets/61237140/fa03b812-39c5-4e19-8330-b6141e7521ce)
Why delete keys here?

**Comment by Mr0N** [comment] 2024-05-11 11:45
https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.hashset-1.contains?view=net-8.0
The Contains method is available.

**Comment by Mr0N** [comment] 2024-05-11 11:50
![image](https://github.com/dotnet/runtime/assets/61237140/ded1e25d-eb3c-4d08-8797-9477bdad73d0)
These are different elements; there is different information there.

**Comment by stephentoub** [comment] 2024-05-11 11:51
> ![image](https://private-user-images.githubusercontent.com/61237140/329778569-fa03b812-39c5-4e19-8330-b6141e7521ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0Mjg0NzEsIm5iZiI6MTcxNTQyODE3MSwicGF0aCI6Ii82MTIzNzE0MC8zMjk3Nzg1NjktZmEwM2I4MTItMzljNS00ZTE5LTgzMzAtYjYxNDFlNzUyMWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDExNDkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNWE2ZTk3Y2M3MWJmYzI1MDBhYzQ5MDM5YTkzZTk2YTNjZWU0NzEwZDY3YTZkNjg2NjdkMjI3OWUwNzEzY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lLWr01P1C7Z9GotaXmDDdIJUJ5Mqn-6JLM8JpE53E1Q) Why delete keys here?

Because it's a set operation, as noted in the duplicate I linked. It yields a set, aka no duplicates according to the comparer.

**Comment by Mr0N** [comment] 2024-05-11 11:51
Info { id = 2, text = index 2 } != Info { id = 2, text = index 3 }

**Comment by stephentoub** [comment] 2024-05-11 11:52
> These are different elements

Not according to your key and the comparer.

**Comment by Mr0N** [comment] 2024-05-11 11:53
> > ![image](https://private-user-images.githubusercontent.com/61237140/329778569-fa03b812-39c5-4e19-8330-b6141e7521ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0Mjg0NzEsIm5iZiI6MTcxNTQyODE3MSwicGF0aCI6Ii82MTIzNzE0MC8zMjk3Nzg1NjktZmEwM2I4MTItMzljNS00ZTE5LTgzMzAtYjYxNDFlNzUyMWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDExNDkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNWE2ZTk3Y2M3MWJmYzI1MDBhYzQ5MDM5YTkzZTk2YTNjZWU0NzEwZDY3YTZkNjg2NjdkMjI3OWUwNzEzY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lLWr01P1C7Z9GotaXmDDdIJUJ5Mqn-6JLM8JpE53E1Q) Why delete keys here?
> 
> Because it's a set operation, as noted in the duplicate I linked. It yields a set, aka no duplicates according to the comparer.

Well, those are unique keys, but the objects associated with those keys are different; a piece of information is being deleted.

**Comment by stephentoub** [comment] 2024-05-11 11:55
> Well, those are unique keys, but the objects associated with those keys are different; a piece of information is being deleted.

Then if you're using Intersect_By_, use a different key that encodes the difference.

**Comment by Mr0N** [comment] 2024-05-11 11:59
![image](https://github.com/dotnet/runtime/assets/61237140/4859dfd7-4c11-4d1a-8d94-f07225e73305)
Well, this contradicts the documentation.

**Comment by Mr0N** [comment] 2024-05-11 12:01
Because it doesn't mention removing duplicates there.

**Comment by Mr0N** [comment] 2024-05-11 12:06
> Member



> > Well, those are unique keys, but the objects associated with those keys are different; a piece of information is being deleted.
> 
> Then if you're using Intersect_By_, use a different key that encodes the difference.

So in my example, the issue isn't with the keys, but the problem is that it didn't select one key.

**Comment by stephentoub** [comment] 2024-05-11 12:18
> Because it doesn't mention removing duplicates there.

It produces the "set intersection". The Remove is an implementation detail to achieve those semantics.

The method is behaving as intended. If you believe the docs are lacking, we'd welcome a PR to the docs repo to try to improve them.

**Comment by Mr0N** [comment] 2024-05-11 12:23
> > Because it doesn't mention removing duplicates there.
> 
> It produces the "set intersection". The Remove is an implementation detail to achieve those semantics.
> 
> The method is behaving as intended. If you believe the docs are lacking, we'd welcome a PR to the docs repo to try to improve them.

It's better to write: The method searches for the value of the function in the sequence from which all duplicates are removed beforehand.

**Closed** 2024-05-11 12:27 UTC
Labels: untriaged, needs-area-label

**Comment by Mr0N** [comment] 2024-05-11 12:36
var result =   arrayTwo.IntersectBy(array,
                                      a => a.id == null ? 0 :a.id);
And what if that function is like this?
