### ISSUE TITLE
[API Proposal]: Provide public implementation to sort IList<T> instances in place 

### ISSUE THREAD

**Issue by vvdev** [dotnet/runtime#101883] opened 2024-05-05 13:27 UTC
### Background and motivation

.NET has a great implementations and public APIs for in place sorting of List<>, Array and Span.
Even more code used by these public APIs is internal/private.

Would be great to reuse the same algorithms (and code when possible) for in place sorting of any IList<T> implementation.

In-place sorting is needed to avoid excessive memory allocations.

Of course, resulting performance will not be as optimal as direct Span/Array sorting and will be highly dependent on concrete IList<> implementation, but at least it [in most of the cases] will be better than most of [quick] implementations made by developers in their codebases.

### API Proposal

```csharp
namespace System.Collections.Generic;

public static class IListSortExtensions<T>
{
    public static void Sort<T>(this IList<T> list) => list.Sort(Comparer<T>.Default);
    public static void Sort<T, TComparer>(this IList<T> list, TComparer comparer) where TComparer : IComparer<T>;

   // also these methods to sort struct lists without boxing
    public static void Sort<T, TList>(this ref TList list) => list.Sort(Comparer<T>.Default) where TList : IList<T>;
    public static void Sort<T, TList, TComparer>(this ref TList list, TComparer comparer) where TList : IList<T> where TComparer : IComparer<T>;
}
```

### API Usage

```csharp
private void SomeMethod(IList<int> list)
{
    list.Sort();
   // do stuff
}

public struct StructBuffer<T> : IList<T>
{
//
}

private void SomeMethod(StructBuffer<int> list)
{
    list.Sort<int, StructBuffer<int>>();
    // do stuff
}

### Alternative Designs

_No response_

### Risks

_No response_

**Comment by stephentoub** [comment] 2024-05-05 13:55
Duplicate of https://github.com/dotnet/runtime/issues/76375

**Closed by stephentoub** 2024-05-05 13:55 UTC
Labels: api-suggestion, area-System.Collections, untriaged
