### ISSUE TITLE
Test failure baseservices\exceptions\simple\ParallelCrashMainThread\ParallelCrashMainThread.cmd

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#77790] opened 2022-11-02 15:14 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=70236
Build error leg or test failing: baseservices\\exceptions\\simple\\ParallelCrashMainThread\\ParallelCrashMainThread.cmd
Pull request: https://github.com/dotnet/runtime/pull/77562

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section).

```json
{
  "ErrorMessage": "baseservices\exceptions\simple\ParallelCrashMainThread\ParallelCrashMainThread.cmd [FAIL]",
  "BuildRetry": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by jkotas** [comment] 2022-11-03 04:53
Duplicate of https://github.com/dotnet/runtime/issues/77791

**Closed by jkotas** 2022-11-03 04:53 UTC
Labels: blocking-clean-ci, untriaged, Known Build Error
