### ISSUE TITLE
Incorrect buffer size check in Convert.TryToHexString / Convert.TryToHexStringLower

### ISSUE THREAD

**Issue by alexanderkozlenko** [dotnet/runtime#110094] opened 2024-11-22 22:25 UTC
### Description

**Affected methods:**
- `Convert.TryToHexString(ReadOnlySpan<byte>, Span<char>, out int)`
- `Convert.TryToHexStringLower(ReadOnlySpan<byte>, Span<char>, out int)`

**Problem:**

The expression `destination.Length > source.Length * 2` in both implementations should have inverted comparison operator.

https://github.com/dotnet/runtime/blob/940e395337ef32782723b789e530aa4abd72b054/src/libraries/System.Private.CoreLib/src/System/Convert.cs#L3097-L3106

https://github.com/dotnet/runtime/blob/940e395337ef32782723b789e530aa4abd72b054/src/libraries/System.Private.CoreLib/src/System/Convert.cs#L3174-L3183

### Reproduction Steps

```cs
var src = new byte[] { 0xa1, 0xb2, 0xc3, 0xd4 };

var dst7u = new char[7]; var dst8u = new char[8]; var dst9u = new char[9];
var dst7l = new char[7]; var dst8l = new char[8]; var dst9l = new char[9];

var res7u = Convert.TryToHexString(src, dst7u, out var chw7u);
var res8u = Convert.TryToHexString(src, dst8u, out var chw8u);
var res9u = Convert.TryToHexString(src, dst9u, out var chw9u);
var res7l = Convert.TryToHexStringLower(src, dst7l, out var chw7l);
var res8l = Convert.TryToHexStringLower(src, dst8l, out var chw8l);
var res9l = Convert.TryToHexStringLower(src, dst9l, out var chw9l);

Console.WriteLine($"7u: {res7u}, {chw7u}, '{new(dst7u)}'");
Console.WriteLine($"8u: {res8u}, {chw8u}, '{new(dst8u)}'");
Console.WriteLine($"9u: {res9u}, {chw9u}, '{new(dst9u)}'");
Console.WriteLine($"7l: {res7l}, {chw7l}, '{new(dst7l)}'");
Console.WriteLine($"8l: {res8l}, {chw8l}, '{new(dst8l)}'");
Console.WriteLine($"9l: {res9l}, {chw9l}, '{new(dst9l)}'");
```

### Expected behavior

```txt
7u: False, 0, ''
8u: True, 8, 'A1B2C3D4'
9u: True, 8, 'A1B2C3D4'
7l: False, 0, ''
8l: True, 8, 'a1b2c3d4'
9l: True, 8, 'a1b2c3d4'
```

### Actual behavior

```txt
7u: True, 8, 'A1B2C3D'
8u: True, 8, 'A1B2C3D4'
9u: False, 0, ''
7l: True, 8, 'a1b2c3d'
8l: True, 8, 'a1b2c3d4'
9l: False, 0, ''
```

### Known Workarounds

Ensure `destination.Length == source.Length * 2` before calling the affected methods.

### Configuration

.NET Runtime 9.0.0

**Comment by KeterSCP** [comment] 2024-11-22 22:33
Duplicate of https://github.com/dotnet/runtime/issues/109807

**Comment by vcsjones** [comment] 2024-11-23 01:11
Closing as a duplicate https://github.com/dotnet/runtime/issues/109807.

**Closed by vcsjones** 2024-11-23 01:11 UTC
Labels: untriaged, needs-area-label
