### ISSUE TITLE
[API Proposal]: More customization of `DateTimeFormatInfo`

### ISSUE THREAD

**Issue by Neme12** [dotnet/runtime#91002] opened 2023-08-23 17:36 UTC
### Background and motivation

If I want to create a `CultureInfo` with a `DateTimeFormatInfo` that always prints dates and times as ISO 8601 (e.g. 2023‐08‐23T17:08:09), the closest I can get is this:
```c#
using System.Globalization;

var culture = new CultureInfo("en-001");
culture.DateTimeFormat.ShortDatePattern = "yyyy'-'MM'-'dd";
culture.DateTimeFormat.LongDatePattern = "yyyy'-'MM'-'dd";
culture.DateTimeFormat.ShortTimePattern = "HH':'mm':'ss";
culture.DateTimeFormat.LongTimePattern = "HH':'mm':'ss";

CultureInfo.CurrentCulture = culture;

Console.WriteLine(DateTime.Now);
```
However, this still prints the `DateTime` as "2023-08-23 19:16:00" - with a space between the date and the time, and there's no way to change that space into a "T". The only way to achieve this is by using reflection to set the internal `GeneralShortTimePattern` and `GeneralLongTimePattern` properties, which are hardcoded to add a space between the date and the time with no way to customize that. With `DateTimeOffset`, there's also a space between the time and the UTC offset, with no way to change that either.

https://github.com/dotnet/runtime/blob/03854e891f79b5a8194ff792f18d4f5ca3a6ea80/src/libraries/System.Private.CoreLib/src/System/Globalization/DateTimeFormatInfo.cs#L891-L904

That's why I'm proposing an API for this so that a `DateTimeFormatInfo` that always prints date times as ISO 8601 could be created.

### API Proposal

I proposed either

1) adding properties mirroring the existing internal ones that would enable customizing the full date time format:
```diff
 namespace System.Globalization;
 
 public sealed partial class DateTimeFormatInfo
 {
+    public string GeneralShortDateTimePattern { get; set; }
+    public string GeneralLongDateTimePattern { get; set; }
+    public string GeneralDateTimeOffsetPattern { get; set; }
 }
```
2) or since the only thing that is hardcoded and that needs to be changed are the separators, add properties that would enable customizing the separators:
```diff
 namespace System.Globalization;
 
 public sealed partial class DateTimeFormatInfo
 {
+    public string DateAndTimeSeparator { get; set; } = " ";
+    public string TimeAndUtcOffsetSeparator { get; set; } = " ";
 }
```

### API Usage

```csharp
using System.Globalization;

var culture = new CultureInfo("en-001");
culture.DateTimeFormat.ShortDatePattern = "yyyy'-'MM'-'dd";
culture.DateTimeFormat.LongDatePattern = "yyyy'-'MM'-'dd";
culture.DateTimeFormat.ShortTimePattern = "HH':'mm':'ss";
culture.DateTimeFormat.LongTimePattern = "HH':'mm':'ss";

culture.DateTimeFormat.GeneralShortDateTimePattern = "yyyy'-'MM'-'dd'T'HH':'mm':'ss";
culture.DateTimeFormat.GeneralLongDateTimePattern = "yyyy'-'MM'-'dd'T'HH':'mm':'ss";
culture.DateTimeFormat.GeneralDateTimeOffsetPattern = "yyyy'-'MM'-'dd'T'HH':'mm':'sszzz";
// or
culture.DateTimeFormat.DateAndTimeSeparator = "T";
culture.DateTimeFormat.TimeAndUtcOffsetSeparator = "";

CultureInfo.CurrentCulture = culture;
```

**Comment by tarekgh** [comment] 2023-08-23 17:58
I am not sure why you cannot use `O` format for that? You may look more at https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings  to learn about it. This `O` format is also supported with `DateOnly` and TimeOnly` which can format the date and time separately if needed. I don't think we need to have these APIs.

**Comment by Neme12** [comment] 2023-08-23 18:05
@tarekgh That only works if you control the formatting. I want to create a culture that *always* prints date times using this format. Let's say you have a `DateTime` hidden somewhere in an object - in a record, or a tuple. Then it's always printed using the current culture and the default format and there's no way to change that.

**Comment by Clockwork-Muse** [comment] 2023-08-23 19:42
> That only works if you control the formatting. I want to create a culture that always prints date times using this format. Let's say you have a DateTime hidden somewhere in an object - in a record, or a tuple. Then it's always printed using the current culture and the default format and there's no way to change that. Or when it's inside a class that you don't control. Or when it's formatted by a 3rd party library.

This is implying that you're relying on a formatting/output stack that isn't intended for saved output (eg, just `ToString()` output, possibly autogen).

That's a bad situation to be in in the first place, regardless of what you actually want the output to look like.  

 - If you have nested objects, you may need to write your own formatter regardless of culture concerns (But more on that in a second).
 - If you're using a third-party library for output, and they aren't correctly handling what should be culture-agnostic data (eg, dates in ISO), file issues/choose a better library.

Attempting to force formatting by setting the ambient culture is problematic and prone to error - especially in cases of culture-agnostic data like this you should be using an explicit culture/format to support that.  For clarity if nothing else.

**Comment by tarekgh** [comment] 2023-08-23 21:16
> Attempting to force formatting by setting the ambient culture is problematic and prone to error - especially in cases of culture-agnostic data like this you should be using an explicit culture/format to support that. For clarity if nothing else

This is true. I don't think we need to introduce something like that which can cause a lot of problems and surprise users with some unexpected behavior for them. I am closing this issue.

**Closed by tarekgh** 2023-08-23 21:16 UTC
Labels: api-suggestion, area-System.Globalization, needs-further-triage

**Comment by Neme12** [comment] 2023-08-23 21:19
> Attempting to force formatting by setting the ambient culture is problematic and prone to error - especially in cases of culture-agnostic data like this you should be using an explicit culture/format to support that. For clarity if nothing else.

I really don't see how that is the case. The opposite is prone to error. Changing the DateFormatInfo will make sure everything is always consistent and invariant.

> I don't think we need to introduce something like that which can cause a lot of problems and surprise users with some unexpected behavior for them.

How could this proposal cause problems or surprise? It's just adding one more customization point to DateFormatInfo.

**Comment by tarekgh** [comment] 2023-08-23 22:13
Overriding the separator between the date and time or the time and time zone can be surprising to users who don't expect to see such separator. This can be breaking for some people of parse their date/time. In your example want to override all formatting to the ISO 8601 will be surprising too and not recommended. 

In general, users who format the dates and time have some expectation and overwriting this globally is not desired. What is your scenario you need to do that and why?

**Comment by Neme12** [comment] 2023-08-23 22:25
> Overriding the separator between the date and time or the time and time zone can be surprising to users who don't expect to see such separator

Well then they won't override it.

**Comment by Neme12** [comment] 2023-08-23 22:27
> overwriting this globally is not desired

Then why does all this customization already exist on `DateTimeFormatInfo`? Being able to customize everything *except* for the separators? Because it *is* desired. You can already set your date time format to "foo" and dates will be broken and print "foo" everywhere. This is just one small missing piece in the customization.

**Comment by tarekgh** [comment] 2023-08-23 22:42
> Then why does all this customization already exist on DateTimeFormatInfo? Being able to customize everything except for the separators? Because it is desired. You can already set your date time format to "foo" and dates will be broken and print "foo" everywhere. This is just one small missing piece in the customization.

You already pointed out the problem of global customization :-). Why do we need to make it worse? We don't recommend overwriting the format globally. Customization is there for local scenarios, someone create his/her culture, customize it the way they like and then use it for their own formatting but not force it on everyone.

**Comment by Neme12** [comment] 2023-08-23 22:51
CultureInfo isn't supposed to be used locally. CurrentCulture is there for a reason, with all the possibilities of how different cultures format dates and times.

**Comment by tarekgh** [comment] 2023-08-23 23:01
> CultureInfo isn't supposed to be used locally.

This is not true, there are many scenarios that users need to format/parse with specific culture and format. Think about Invariant culture as an example. 

> You can't control it anyway when you use the current culture,

It is not required to control it but must match the user expectation. User experience is particularly important. Your scenario is not satisfying that.
