### ISSUE TITLE
System.text.json can't parse float correctly.

### ISSUE THREAD

**Issue by Andor233** [dotnet/runtime#36521] opened 2020-05-15 09:14 UTC
### Description
![image](https://user-images.githubusercontent.com/16273755/82033392-3e8c4c00-96cf-11ea-9e75-a8eec88cfbd1.png)

![image](https://user-images.githubusercontent.com/16273755/82033407-43510000-96cf-11ea-877c-46928fec181b.png)
It should be 3.0 not 3.
### Configuration

.net core 3 & .net f 4.6 in windows 10 & mono in linux

**Comment by RamType-0** [comment] 2020-05-15 11:27
`Console.WriteLine(3f)` displays "3".
It seems that `System.Text.Json.JsonSerializer` is independent.

**Comment by ANahr** [comment] 2020-05-15 13:07
"3" is valid JSON for a number.
And while "3.0" is also valid it would be inefficient to serialize it that way.

**Comment by mburbea** [comment] 2020-05-15 14:09
In your web browser, `JSON.stringify(3.0)` returns 3. So yes, this is an accurate way to serialize a number.

**Comment by layomia** [comment] 2020-05-15 15:08
This is a duplicate of https://github.com/dotnet/runtime/issues/35195.

**Closed by layomia** 2020-05-15 15:08 UTC
Labels: area-System.Text.Json
