### ISSUE TITLE
HTTP/3: QuicStream.ReadAsync ignores abort?

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#55056] opened 2021-07-02 03:18 UTC
I have a server-to-client unidirectional stream. The server aborts its stream with `AbortWrite(Error)`

The client stream then calls `ReadAsync` and it returns a read count of 0. This is unexpected. Usually, a read count of 0 indicates successfully reading to the end of the stream. I expected an aborted exception instead.

When I look at the client stream's internal state I can see that it received the error code (ReadErrorCode):

![image](https://user-images.githubusercontent.com/303201/124215416-10becc80-db48-11eb-8ed8-8b381c00458f.png)

Is this intended? I haven't tested whether this happens in other stream scenarios (client-to-server bidirectional and client-to-server unidirectional).

**Comment by JamesNK** [comment] 2021-07-02 03:32
stream.ReadAsync throws `QuicStreamAbortedException` for client-to-server unidirectional stream on AbortWrite.

Is the bug unique to server-to-client unidirectional streams?

**Comment by ManickaP** [comment] 2021-07-02 08:46
This should work as you say, we should investigate and fix that. 

Haven't we done some work in handling aborts for `ReadAsync`? cc: @CarnaViire

**Comment by wfurt** [comment] 2021-07-02 17:29
This may be fixed with #54798 as we set `_canRead` to `false` so `ReadAsync` will throw.
We should probably add explicit test and agree that the `InvalidOperationException` is good enough (or we should be smarter about exception type)

**Comment by JamesNK** [comment] 2021-07-02 22:06
This might be a duplicate of https://github.com/dotnet/runtime/issues/53530

**Comment by JamesNK** [comment] 2021-07-04 02:30
This is a race condition. The test correctly threw `QuicStreamAbortedException`. Very rare.

**Comment by ManickaP** [comment] 2021-07-06 08:52
Duplicate of #53530

**Closed by ManickaP** 2021-07-06 08:52 UTC
Labels: area-System.Net.Quic
