### ISSUE TITLE
C# Have TryGetNonEnumeratedCount check for IReadOnlyCollection<T>

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#99774] opened 2024-03-14 17:35 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/C-Have-TryGetNonEnumeratedCount-check-f/10602510)._

---
You can have a type that has a Count property and implements IEnumerable<T> but not any of the collection interfaces.
The IReadOnlyCollection<T> interface provides just that.

Currently, Enumerable.TryGetNonEnumeratedCount does not check for IReadOnlyCollection<T> and therefore these types will be fully enumerated when trying to determine the count.

---
#### Feedback Bot on 2/27/2024, 09:37 PM: 

(private comment, text removed)

**Comment by stephentoub** [comment] 2024-03-15 03:11
Duplicate of https://github.com/dotnet/runtime/issues/42254

**Closed by stephentoub** 2024-03-15 03:11 UTC
Labels: area-System.Linq, untriaged
