### ISSUE TITLE
ARM64 Vector2 multiplication breaks in .NET 8

### ISSUE THREAD

**Issue by NoelFB** [dotnet/runtime#98137] opened 2024-02-07 23:39 UTC
### Description

On Linux and MacOS, various Vector2 floating point multiplications break after running for a few hundred milliseconds.

Running this code in Release Mode on a `dotnet new console` application on ARM64 results in the Y component of the vector being zero.

```cs
using System.Numerics;

while (true)
{
    Thread.Sleep(10);
    Step(4.0f);
}

static void Step(float number)
{
    var variable = Vector2.One * number;
    if (variable.X != variable.Y)
        throw new Exception("Components don't match");
    Console.WriteLine(variable);
}
```

This does not occur in Debug Mode. If I don't wrap the code in a function (`Step`) it doesn't seem to happen. If I hard code the floating value (`Vector2.One * 4.0f`) it doesn't seem to happen.

### Reproduction Steps

Simply create a new console project in .NET 8 and run the above code in Program.cs with `dotnet run -c Release`. After running for a few hundred milliseconds the application will throw an exception.

### Expected behavior

Multiplication should always result in <4,4>

### Actual behavior

Multiplication results in <4,0> after several hundred milliseconds

### Regression?

Does not occur in .NET 7, only .NET 8

### Configuration

.NET 8, ARM64, MacOS (have had reports of this same problem on ARM64 Linux)

### Other information

This has been an issue found in our [open source game Celeste 64](https://github.com/ExOK/Celeste64/issues/70) for users running the game on ARM64 for both MacOS and Linux. I personally have only tested on MacOS.

**Comment by isadorasophia** [comment] 2024-02-07 23:43
@tannergooding could you help triaging this?

**Comment by tannergooding** [comment] 2024-02-08 03:28
This was fixed by @jakobbotsch in .NET 9 via https://github.com/dotnet/runtime/pull/94413, which was fixing a different issue caused by the types of op1/op2 mismatching for MultiplyByScalar (one is a `TYP_SIMD16`, the other a `TYP_SIMD8`).

The simple fix should be backporting this PR to .NET 8.

----

Independently, we should ensure an issue exists to ensure constant folding does work for this scenario and that the correctly typed operand is selected.

**Comment by jakobbotsch** [comment] 2024-02-08 10:00
> This was fixed by @jakobbotsch in .NET 9 via https://github.com/dotnet/runtime/pull/94413, which was fixing a different issue caused by the types of op1/op2 mismatching for MultiplyByScalar (one is a TYP_SIMD16, the other a TYP_SIMD8).

That PR fixed the type mismatch but also deliberately this particular issue, which I noticed while working on the other one (https://github.com/dotnet/runtime/pull/94413#discussion_r1383519750).

**Comment by theofficialgman** [comment] 2024-02-09 03:40
> ### Configuration
> .NET 8, ARM64, MacOS (have had reports of this same problem on ARM64 Linux)

can confirm running the testcase results in an exception after 77 iterations

**Comment by jakobbotsch** [comment] 2024-06-05 23:04
The fix is available in the current .NET 8 release.

**Closed by jakobbotsch** 2024-06-05 23:04 UTC
Labels: area-CodeGen-coreclr
