### ISSUE TITLE
ARM iOS build hung during CI

### ISSUE THREAD

**Issue by noahfalk** [dotnet/runtime#72829] opened 2022-07-26 05:28 UTC
In rolling CI build [1902723](https://runfo.azurewebsites.net/view/build/?number=1902723) the iOS ARM build made no progress for 25 minutes and then aborted with a timeout:

https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1902723/logs/2481

```
2022-07-26T00:44:09.4784780Z   [ 97%] Building C object mono/mini/CMakeFiles/monosgen-objects.dir/interp/mintops.c.o
2022-07-26T00:44:14.7982910Z   [ 97%] Building C object mono/mini/CMakeFiles/monosgen-objects.dir/interp/transform.c.o
2022-07-26T00:44:16.9734480Z   [ 97%] Building C object mono/mini/CMakeFiles/monosgen-objects.dir/interp/tiering.c.o
2022-07-26T00:44:37.7175860Z   [ 98%] Building C object mono/mini/CMakeFiles/monosgen-objects.dir/debugger-agent-external.c.o
2022-07-26T00:44:54.0624070Z   [ 98%] Building C object mono/mini/CMakeFiles/monosgen-objects.dir/Users/runner/work/1/s/artifacts/obj/_version.c.o
2022-07-26T01:10:21.5071860Z ##[error]The operation was canceled.
2022-07-26T01:10:21.6124260Z ##[section]Finishing: Build product
```

|Build|Kind|Start Time|
|---|---|---|
[1902723](https://dev.azure.com/dnceng/public/_build/results?buildId=1902723)|Rolling|2022-25-07|
[1903453](https://dev.azure.com/dnceng/public/_build/results?buildId=1903453)|Rolling|2022-26-07|

**Comment by steveisok** [comment] 2022-07-26 05:30
This seems like a dreaded slow max that pops up from time to time

**Comment by noahfalk** [comment] 2022-07-26 20:38
Another rolling build just failed for the same reason. This time the build made no progress for 55 minutes.

https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1903453/logs/2506
```
2022-07-26T11:01:02.1153340Z   System.Text.Encodings.Web -> /Users/runner/work/1/s/artifacts/bin/System.Text.Encodings.Web/Release/net7.0/System.Text.Encodings.Web.dll
2022-07-26T11:01:05.8184270Z   System.Security.Principal.Windows -> /Users/runner/work/1/s/artifacts/bin/System.Security.Principal.Windows/Release/net7.0/System.Security.Principal.Windows.dll
2022-07-26T11:01:07.4325270Z   System.Net.WebProxy -> /Users/runner/work/1/s/artifacts/bin/System.Net.WebProxy/Release/net7.0/System.Net.WebProxy.dll
2022-07-26T11:01:16.5551960Z   Microsoft.VisualBasic.Core -> /Users/runner/work/1/s/artifacts/bin/Microsoft.VisualBasic.Core/Release/net7.0/Microsoft.VisualBasic.Core.dll
2022-07-26T11:01:20.7936140Z   System.Threading.Channels -> /Users/runner/work/1/s/artifacts/bin/System.Threading.Channels/Release/net7.0/System.Threading.Channels.dll
2022-07-26T11:02:15.2687640Z ##[error]The operation was canceled.
2022-07-26T11:02:15.2760780Z ##[section]Finishing: Build product
```

**Comment by steveisok** [comment] 2022-07-26 21:53
@MattGal Looks like we're getting hit by slow build machine macs again.

**Comment by MattGal** [comment] 2022-07-26 22:08
> @MattGal Looks like we're getting hit by slow build machine macs again. I know there's probably not a lot we can do, but fyi nonetheless.

I've forwarded these along to my contact on the MMS team.  Not much we can do, for sure, but worth tracking the issue.

**Comment by noahfalk** [comment] 2022-07-26 22:25
Was there some past investigation that demonstrated the machines were just running slowly vs. the build being hung? Normally I'd expect slow machines to be somewhat evenly slow whereas these logs appear to make reasonable progress for a while then very abruptly all progress stops. Superficially I'd have guessed this was a hang rather than slowness.

**Comment by MattGal** [comment] 2022-07-26 23:05
> Was there some past investigation that demonstrated the machines were just running slowly vs. the build being hung? Normally I'd expect slow machines to be somewhat evenly slow whereas these logs appear to make reasonable progress for a while then very abruptly all progress stops. Superficially I'd have guessed this was a hang rather than slowness.

Yes, the symptoms were pretty darn clear; lines that took < 1 s apiece would take 10x+ this in various build and restore tasks.    Looking at the one you've just posted and [the most recent green main run](https://dev.azure.com/dnceng/public/_build/results?buildId=1897187&view=logs&j=a5078f86-b345-5a4a-85ee-f64916152c6f) , the symptoms definitely match "slow" not "hung" since the recent green run finished in 41 minutes and the timed out one has no major jumps in timestamp, just slow steady progress.

If it's a hang, you have a chance of debugging it.  If it's just the "slow machines" issue I'd expect it's very, very unlikely to get resolved as we still don't know the root cause (or why it reduced occurrence) from the last time.

**Comment by noahfalk** [comment] 2022-07-26 23:50
Oh the latter one was a misread on my part. I see the delay at the end was 55 seconds, not 55 minutes as I stated above. The initial log however does have a timestamp jump of 25 minutes between the last output and cancellation which still looks suspicious to me.

>  as we still don't know the root cause (or why it reduced occurrence) from the last time.

Could we do some things now to help diagnose the issue when it next occurs? For example we could include something in the build that lists all running processes and statistics on the resource usage. We might also run something that reports on the hardware and does some brief benchmarking on the disk and CPU performance.

**Comment by MattGal** [comment] 2022-07-26 23:59
Thanks @noahfalk .  Given how bad this tanks performance, I think brief benchmarking would be great in identifying/quantifying the problem but there's more to the problem.  

At least last time we hit this, without very custom instrumentation it's nearly impossible to identify which mac a given VM in a given moment was running on and look for patterns in what happened.  The MMS team lives on east coast time mostly so we'll find out in the AM if that has gotten any better.

**Comment by steveisok** [comment] 2022-07-27 00:07
Can we do something like if restore takes > 10 minutes (it was 15 in the linked build), take some measurements and then cancel the build?  Something that is an indicator early on that we're not likely to finish instead of taking 3 hours to figure it out.

**Comment by MattGal** [comment] 2022-07-27 15:18
That'd probably catch most cases, yes.  Setting a lower timeout might be the best choice if you know something normally takes 40 minutes, 60 minutes might make more sense than 180?

**Comment by steveisok** [comment] 2022-08-01 03:59
Seeing that this is sporadic and out of our control, closing.

**Comment by agocke** [comment] 2022-08-01 22:13
This is pretty impactful. If we can't find a way to make these tests reliable, can we move them out of the runtime pipeline and into runtime-extra-platforms?

**Comment by steveisok** [comment] 2022-08-02 00:13
> This is pretty impactful. If we can't find a way to make these tests reliable, can we move them out of the runtime pipeline and into runtime-extra-platforms?

I don't think this has anything to do with tests. We will get slow macs that can't even get through a build.  There's nothing we can really do except bailing earlier.

**Closed** 2022-08-02 00:52 UTC
Labels: area-Build-mono, os-ios
