### ISSUE TITLE
Dogfooding not working.

### ISSUE THREAD

**Issue by mrj001** [dotnet/runtime#37107] opened 2020-05-28 00:44 UTC
I'm trying to get the "More Advanced Scenario - Using your local CoreFx Build" working.  (Possible related  #30685)
I've built it as follows:
```
git clean -xdf
git pull upstream master
./build.cmd -c Release -allconfigurations
```
The build succeeds.
Then:
``` 
find artifacts -name Microsoft.Private\*.nupkg
```
produces the following output:
> artifacts/packages/Release/NonShipping/Microsoft.Private.CoreFx.OOB.5.0.0-dev.nupkg
> artifacts/packages/Release/NonShipping/symbols/Microsoft.Private.CoreFx.OOB.5.0.0-dev.symbols.nupkg

so the file referenced in step 1 does not exist.  Please have the documents updated.

I'm on Windows 10 Home, using git bash as the command prompt.
HEAD is at: 0c043d58ccc

```
export DOTNET_ROOT=`pwd`/.dotnet
export DOTNET_MULTILEVEL_LOOKUP=0
export PATH=$DOTNET_ROOT:$PATH
./.dotnet/dotnet --version 
```
produces the following output;
>5.0.100-preview.5.20251.2

**Comment by safern** [comment] 2020-05-28 01:04
Thanks, @mrj001 I will update the docs.

**Comment by safern** [comment] 2020-05-28 01:06
Actually closing as dupe of: #30685

**Closed by safern** 2020-05-28 01:06 UTC
Labels: area-Infrastructure-libraries, untriaged
