### ISSUE TITLE
.net7 wpf win7 64 use large memory

### ISSUE THREAD

**Issue by tianmafly** [dotnet/runtime#83628] opened 2023-03-18 00:21 UTC
.net7 wpf win7 64, system use large memory.
.net7 wpf win7 32, system use normal memory.
.net7 wpf win10 64, system use normal memory.
.net6 wpf win7 64, system use normal memory.

.net7 wpf win7 64, When run the exe, the process memory is normal, but the system memory use about 4GB.
![image](https://user-images.githubusercontent.com/38370307/226072687-15291e44-28b5-4fd6-8f80-4295de472ff8.png)

why system memory use so large with wpf .net7 win7 64 ?

**Comment by Maoni0** [comment] 2023-03-18 02:57
I don't see how this is a GC issue or even a .NET issue. 
you have other processes consuming memory in the system. you can see what they are, for example, mysqld.exe is consuming 568mb, as your picture shows.

**Comment by teo-tsirpanis** [comment] 2023-03-18 10:43
Duplicate of #79469. Starting with .NET 7 Windows 7 and 8.1 are not supported.

**Closed by teo-tsirpanis** 2023-03-18 10:43 UTC
Labels: untriaged
