### ISSUE TITLE
Base64.EncodeToUtf8 behavior changed between netcore2.1 and netcore3.0

### ISSUE THREAD

**Issue by coenm** [dotnet/runtime#31348] opened 2019-10-30 20:43 UTC
The following call

```csharp
var status = System.Buffers.Text.Base64.EncodeToUtf8(Span<byte>.Empty, new byte[42], out _, out _, isFinalBlock:false);
```

returns `OperationStatus.NeedMoreData` running netcore2.1 and `OperationStatus.Done` in netcore3.0

Is this intentionally? Is this a bug? Should this be documented?

Example can be found at:

```bash
git clone https://github.com/coenm/Base64Issue.git

dotnet test Base64Difference/Base64Difference.csproj
```
The test will pass in netcore2.1 and fail in netcore3.0

**Comment by zmj** [comment] 2020-02-09 22:32
* Done: The entire input buffer has been processed and the operation is complete.
* NeedMoreData: The input is partially processed, up to the last valid chunk of the input that could be consumed.

These definitions don't seem to provide a clear yes/no to the question "do I need to ask the pipe for more data?" That seems like a missed opportunity.

I've been using OperationStatus like this (in a PipeReader / ReadOnlySequence consumer):
* Done: progress has been made and >0 of the input buffer has been consumed. Apply the progress, slice the buffer, and call again.
* NeedsMoreData: no progress is possible with this buffer's contents, ask the pipe for more.

In my case, "apply the progress" may require some async calls, so I don't want to do that within the "inner loop" OperationStatus-returning method. Instead, I want the OpStatus return to give the caller enough information to decide whether to call again or wait for a read.

**Comment by ericstj** [comment] 2020-09-14 18:08
@GrabYourPitchforks what was your thought with moving this back to 5.0.0?  Were you planning to make a code change or just update the docs?

**Comment by GrabYourPitchforks** [comment] 2020-09-14 18:44
@ericstj This is a doc-only change. The 3.x / 5.x code is correct.

**Comment by stephentoub** [comment] 2020-10-09 16:02
Just as a point of order, what does it mean for this to be in the 5.0 milestone if the change that needs a doc update happened in 3.0?

**Comment by ericstj** [comment] 2020-10-09 19:47
We have no 3.0 milestone, we put our servicing issues in the latest milestone we are actively working on.  We ship docs, even for past releases, in the latest release.

**Comment by stephentoub** [comment] 2020-10-09 21:46
Ok, thanks.

**Comment by GrabYourPitchforks** [comment] 2020-10-10 00:19
First issue is up: https://github.com/dotnet/dotnet-api-docs/issues/4968. It discusses clarifications to the existing docs to help callers better understand under what conditions any given return value might be seen.

**Comment by GrabYourPitchforks** [comment] 2020-10-10 00:30
I'm going to close this issue out as complete. I've been looking through our breaking change docs, and those tend to track behavioral differences due to design / spec changes. This behavioral change is really a bug fix more than anything else, and we don't tend to surface bug fixes in the breaking change notifications. The doc updates I linked previously should be sufficient to explain the issue and the intended behavior.

**Closed by GrabYourPitchforks** 2020-10-10 00:30 UTC
Labels: area-System.Memory, breaking-change, documentation, needs-breaking-change-doc-created

**Comment by jeffhandley** [comment] 2020-11-02 23:34
Based on the comment above that this is a behavioral change bug fix, I've removed the `breaking-change` and `needs-breaking-change-doc-created` labels.  https://github.com/dotnet/dotnet-api-docs/issues/4968 was filed to capture the changes needed in the documentation to reflect the new behavior.
