### ISSUE TITLE
iOS: building with LLVM causes some exception catch clauses to not work

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#56100] opened 2021-07-21 16:19 UTC
### Description

See the following test code: https://gist.github.com/rolfbjarne/f5c1a3697343c5e9bb6cb8e5b796d328#file-appdelegate-cs-L23-L73

When executed on an iOS device (AOT compiled), this produces the following output:

```
TCP connection failed when selecting 'hostname': fe80::6aa3:6295:30dd:b552 and 'port': 49681. System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (65): No route to host [fe80::6aa3:6295:30dd:b552]:49681
   at System.Net.Sockets.Socket.DoConnect(EndPoint , SocketAddress ) in System.Net.Sockets.dll:token 0x6000127+0x68
   at System.Net.Sockets.Socket.Connect(EndPoint ) in System.Net.Sockets.dll:token 0x600010a+0xca
   at System.Net.Sockets.Socket.Connect(IPAddress , Int32 ) in System.Net.Sockets.dll:token 0x600010b+0x62
   at System.Net.Sockets.TcpClient.Connect(String , Int32 ) in System.Net.Sockets.dll:token 0x60001b7+0xc7
--- End of stack trace from previous location ---
   at System.Net.Sockets.TcpClient.Connect(String , Int32 ) in System.Net.Sockets.dll:token 0x60001b7+0x158
   at System.Net.Sockets.TcpClient..ctor(String , Int32 ) in System.Net.Sockets.dll:token 0x60001b4+0x56
   at MySingleView.AppDelegate.<>c__DisplayClass3_2.<SelectHostName>b__0(Object v) in /Users/rolf/work/maccore/squashed-onedotnet/xamarin-macios/tests/dotnet/MySingleView/AppDelegate.cs:line 49
[...]
Selected host name: 
```

if I enable LLVM, the following happens:

```
Unhandled managed exception: No route to host [fe80::6aa3:6295:30dd:b552]:49681 (System.Net.Internals.SocketExceptionFactory+ExtendedSocketException)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
Unhandled managed exception: No route to host [fe80::14a6:1e61:2f4e:e2c5]:49681 (System.Net.Internals.SocketExceptionFactory+ExtendedSocketException)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
```

It's a rather strange bug, because in my original test it doesn't crash this way, the `SelectHostName` code causes a lot of other test failures due to `Assert.Throws<FooException>` statements not actually catching the `FooException`, but then the general NUnit catch handler catches these exceptions, and turn them into test failures. The baffling effect was that running the tests outside of our test harness (without needing to call the `SelectHostName` method), the tests passed.

In any case, let me know if you can reproduce with this information, or I'll create a test case you can use (which will likely require building a custom branch of xamarin-macios).

**Comment by rolfbjarne** [comment] 2021-07-21 16:20
CC @SamMonoRT @lambdageek

**Comment by SamMonoRT** [comment] 2021-07-21 17:04
@imhameed should be back in office next week and can take a look then. @vargaz - any pointers ?

**Comment by vargaz** [comment] 2021-07-21 18:31
How can I reproduce this ?

**Comment by rolfbjarne** [comment] 2021-07-22 10:36
@vargaz 

> How can I reproduce this ?

1. Download & install Xcode 13 beta 3.
2. Clone my fork of xamarin-macios, and checkout the [`dotnet-llvm-exception-repro`](https://github.com/rolfbjarne/xamarin-macios/tree/dotnet-llvm-exception-repro) branch, and build it:

        git clone https://github.com/rolfbjarne/xamarin-macios
        git checkout dotnet-llvm-exception-repro
        cd xamarin-macios
        ./configure --enable-dotnet --enable-xamarin
        make reset
        make all -j8
        make install -j8

3. Connect an iOS device
4. Build & run the test project:

        make -C tests/dotnet/MySingleView run-llvm

**Comment by vargaz** [comment] 2021-07-23 14:14
I can reproduce, however the failure seems random, sometimes it works.

**Comment by vargaz** [comment] 2021-07-23 15:21
Did this ever work with .net core ?

**Comment by rolfbjarne** [comment] 2021-07-23 15:23
> Did this ever work with .net core ?

I don't know, it's the first time we've had support for LLVM (I ran into this while implementing LLVM support).

**Comment by imhameed** [comment] 2021-08-02 18:09
I tried reproducing this locally but wasn't successful. Also `make -C tests/dotnet/MySingleView run-llvm` takes a very long time for me to run locally, because it seems to rebuild MySingleView with llvm from start to finish; @vargaz when you determined that the failure was intermittent, did you rerun `make -C tests/dotnet/MySingleView run-llvm`? Or did you reuse/relaunch an already-built test app?

**Comment by imhameed** [comment] 2021-08-13 15:02
A note: if I build the repro with `/p:Configuration=Release`, this stops

**Comment by SamMonoRT** [comment] 2021-08-14 12:41
Doesn't seem like a consistent repro. @imhameed - if you determine consistent repro steps and have a low risk fix, we will consider backporting to 6.0 - For now moving to 7.0

**Comment by rolfbjarne** [comment] 2021-08-16 08:50
> Doesn't seem like a consistent repro. @imhameed - if you determine consistent repro steps and have a low risk fix, we will consider backporting to 6.0 - For now moving to 7.0

This is blocking LLVM for us. It's 100% consistent on our main test suite, where it breaks a huge number of tests. There's no way we can release LLVM support with this bug.

**Comment by SamMonoRT** [comment] 2021-08-16 12:21
Got it @rolfbjarne ---- @imhameed has been working on narrowing down the issue, so we should be able to get in a fix. @imhameed please update this with your progress

**Comment by imhameed** [comment] 2021-08-17 08:29
A smaller repro: https://gist.github.com/imhameed/cdeba5b8bb9cd879b688b97292602e58

Still fails intermittently for me, even when re-launching an already-installed copy of this via mlaunch. Exception handling ought to be deterministic, but maybe the attempt to open a socket can fail in multiple ways that all raise the same exception, and one of these failing cases has bad codegen. Haven't yet looked at the IR we're generating.

Also bad: [this code](https://gist.github.com/imhameed/9ab1bbb87a8892d7a4d46c4d47abd0e8) crashes with an "Unhandled managed exception" 100% of the time.

**Comment by imhameed** [comment] 2021-08-17 16:45
Nested try clauses ought to fall back to mini instead of LLVM: https://github.com/dotnet/runtime/blob/main/src/mono/mono/mini/mini-llvm.c#L11051

Working on getting locally-built cross-compiler shimmed into xamarin-macios right now.

**Comment by filipnavara** [comment] 2021-08-17 17:35
Ref: https://bugzilla.xamarin.com/37/37273/bug.html (since it's not obvious where the original issue was filed)

**Comment by imhameed** [comment] 2021-08-17 17:52
Also related (tracking a longer-term cleaner fix): https://github.com/dotnet/runtime/issues/54176

**Comment by vargaz** [comment] 2021-08-18 14:33
So llvm used to work with previous xam.ios versions based on the mono/mono codebase, I don't think this problem is caused by bcl changes, it seems more likely to be a change in the build system, a missing flag etc.

**Comment by imhameed** [comment] 2021-08-18 15:20
Here's a verbose log excerpt from a run of mono-aot-cross using LLVM:

Arguments:
```
--aot=mtriple=arm64-ios,data-outfile=obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/MySingleView.aotdata,static,asmonly,direct-icalls,full,nodebug,dwarfdebug,llvm-path=/Users/imhameed/ms/xammac-rolf/xamarin-macios/builds/downloads/dotnet-sdk-6.0.100-rc.1.21370.12-osx-x64/packs/Microsoft.NETCore.App.Runtime.AOT.osx-x64.Cross.ios-arm64/6.0.0-rc.1.21369.14/Sdk/../tools,outfile=obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/MySingleView.dll.s,llvm-outfile=obj/Release/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/MySingleView.dll.llvm.o --debug --llvm -O=gsharedvt /Users/imhameed/ms/xammac-rolf/xamarin-macios/tests/dotnet/MySingleView/obj/Release/net6.0-ios/ios-arm64/linked/MySingleView.dll
```
Output:
```
...
LLVM failed for 'Application.SelectHostName': nested clauses
converting method string MySingleView.Application:SelectHostName (string,int)
created temp 0 (R32) of type System.Object
creating vars
created temp 1 (R33) of type System.Object
created temp 2 (R34) of type System.Int32
	return :  arg R32 <-
	arg [0]:  arg R33 <-
	arg [1]:  arg R34 <-
creating locals
	local [0]: created temp 3 (R35) of type System.Object
	local [1]: created temp 4 (R36) of type System.Int32
locals done
method to IR MySingleView.Application:SelectHostName (string,int)
created temp 5 (R37) of type System.Object
created temp 6 (R38) of type System.Object
converting (in B5: stack: 0) IL_0000: ldnull    
converting (in B5: stack: 1) IL_0001: stloc.0   
converting (in B5: stack: 0) IL_0002: ldc.i4.0  
converting (in B5: stack: 1) IL_0003: stloc.1   
converting (in B2: stack: 0) IL_0004: ldstr     "--DEBUG: before"
converting (in B2: stack: 1) IL_0009: call      0x0a00000f
cmethod = void System.Console:WriteLine (string)
converting (in B2: stack: 0) IL_000e: call      0x06000006
cmethod = string MySingleView.Application:Raise ()
converting (in B2: stack: 1) IL_0013: pop       
converting (in B2: stack: 0) IL_0014: ldstr     "--DEBUG: after"
converting (in B2: stack: 1) IL_0019: call      0x0a00000f
cmethod = void System.Console:WriteLine (string)
converting (in B2: stack: 0) IL_001e: leave.s   IL_0032
loading 0 from temp 5
converting (in B3: stack: 1) IL_0020: pop       
converting (in B3: stack: 0) IL_0021: ldloc.1   
converting (in B3: stack: 1) IL_0022: ldc.i4.1  
converting (in B3: stack: 2) IL_0023: add       
converting (in B3: stack: 1) IL_0024: stloc.1   
converting (in B3: stack: 0) IL_0025: leave.s   IL_0032
converting (in B4: stack: 0) IL_0027: ldstr     "--DEBUG: finally!"
converting (in B4: stack: 1) IL_002c: call      0x0a00000f
cmethod = void System.Console:WriteLine (string)
converting (in B4: stack: 0) IL_0031: endfinally
converting (in B7: stack: 0) IL_0032: ldloc.0   
converting (in B7: stack: 1) IL_0033: ret       
...
```

The same without using LLVM:

Arguments:
```
--aot=mtriple=arm64-ios,data-outfile=obj/Debug/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/MySingleView.aotdata,static,asmonly,direct-icalls,full,soft-debug,dwarfdebug,no-direct-calls,outfile=obj/Debug/net6.0-ios/ios-arm64/nativelibraries/aot-output/arm64/MySingleView.dll.s --debug -O=gsharedvt /Users/imhameed/ms/xammac-rolf/xamarin-macios/tests/dotnet/MySingleView/obj/Debug/net6.0-ios/ios-arm64/linked/MySingleView.dll
```

Output:
```
...
converting method string MySingleView.Application:SelectHostName (string,int)
created temp 0 (R32) of type System.Object
creating vars
created temp 1 (R33) of type System.Object
created temp 2 (R34) of type System.Int32
	return :  arg R32 <-
	arg [0]:  arg R33 <-
	arg [1]:  arg R34 <-
creating locals
	local [0]: created temp 3 (R35) of type System.Object
	local [1]: created temp 4 (R36) of type System.Int32
	local [2]: created temp 5 (R37) of type System.Object
	local [3]: created temp 6 (R38) of type System.Object
locals done
created temp 7 (R39) of type System.IntPtr
created temp 8 (R40) of type System.IntPtr
created temp 9 (R41) of type System.IntPtr
method to IR MySingleView.Application:SelectHostName (string,int)
created temp 10 (R42) of type System.Object
created temp 11 (R43) of type System.Object
converting (in B6: stack: 0) IL_0000: nop       
converting (in B6: stack: 0) IL_0001: ldnull    
converting (in B6: stack: 1) IL_0002: stloc.0   
converting (in B6: stack: 0) IL_0003: ldc.i4.0  
converting (in B6: stack: 1) IL_0004: stloc.1   
converting (in B4: stack: 0) IL_0005: nop       
converting (in B2: stack: 0) IL_0006: nop       
converting (in B2: stack: 0) IL_0007: ldstr     "--DEBUG: before"
converting (in B2: stack: 1) IL_000c: call      0x0a00000f
cmethod = void System.Console:WriteLine (string)
converting (in B2: stack: 0) IL_0011: nop       
converting (in B2: stack: 0) IL_0012: call      0x06000006
cmethod = string MySingleView.Application:Raise ()
converting (in B2: stack: 1) IL_0017: pop       
converting (in B2: stack: 0) IL_0018: ldstr     "--DEBUG: after"
converting (in B2: stack: 1) IL_001d: call      0x0a00000f
cmethod = void System.Console:WriteLine (string)
converting (in B2: stack: 0) IL_0022: nop       
converting (in B2: stack: 0) IL_0023: nop       
converting (in B2: stack: 0) IL_0024: leave.s   IL_002f
loading 0 from temp 10
converting (in B3: stack: 1) IL_0026: stloc.2   
converting (in B3: stack: 0) IL_0027: nop       
converting (in B3: stack: 0) IL_0028: ldloc.1   
converting (in B3: stack: 1) IL_0029: ldc.i4.1  
converting (in B3: stack: 2) IL_002a: add       
converting (in B3: stack: 1) IL_002b: stloc.1   
converting (in B3: stack: 0) IL_002c: nop       
converting (in B3: stack: 0) IL_002d: leave.s   IL_002f
converting (in B8: stack: 0) IL_002f: nop       
converting (in B8: stack: 0) IL_0030: leave.s   IL_0040
converting (in B5: stack: 0) IL_0032: nop       
converting (in B5: stack: 0) IL_0033: ldstr     "--DEBUG: finally!"
converting (in B5: stack: 1) IL_0038: call      0x0a00000f
cmethod = void System.Console:WriteLine (string)
converting (in B5: stack: 0) IL_003d: nop       
converting (in B5: stack: 0) IL_003e: nop       
converting (in B5: stack: 0) IL_003f: endfinally
converting (in B9: stack: 0) IL_0040: ldloc.0   
converting (in B9: stack: 1) IL_0041: stloc.3   
converting (in B9: stack: 0) IL_0042: br.s      IL_0044
converting (in B10: stack: 0) IL_0044: ldloc.3   
converting (in B10: stack: 1) IL_0045: ret       
...
```

**Comment by imhameed** [comment] 2021-08-20 07:16
Here's the LLVM IR along with the mono-aot-cross/opt/llc flags used for compilation for [this repro](https://gist.github.com/imhameed/9ab1bbb87a8892d7a4d46c4d47abd0e8): https://gist.github.com/imhameed/bd2564d0df45c580294888eb9f4770c4

I tried rebuilding a cross compiler with LLVM 9 and rebuilding the repro using LLVM 9 opt and llc. That made no difference.

And nested clauses might not be related; https://gist.github.com/imhameed/ccd542f151624c6399bd6d5c0f74b085 also crashes. Going to trace our EH code next.

**Comment by vargaz** [comment] 2021-08-20 09:08
If you change the testcase to:
```
static int foo;

		[MethodImpl(MethodImplOptions.NoInlining)]
		static string Raise() {
                         if (foo == 0)
			throw new InvalidOperationException("okay");
		}
```
does it still fail ?

**Comment by imhameed** [comment] 2021-08-20 17:59
@vargaz Yes:
```
		static int foo;
		[MethodImpl(MethodImplOptions.NoInlining)]
		static string Raise() {
			if (foo == 0)
			throw new InvalidOperationException("okay");
			return "";
		}
```
still causes:
```
2021-08-20 11:15:24.797 MySingleView[3141:8804269] --DEBUG: before
2021-08-20 11:15:24.809 MySingleView[3141:8804269] Unhandled managed exception: okay (System.InvalidOperationException)

=================================================================
        Native Crash Reporting
=================================================================
...
```

**Comment by imhameed** [comment] 2021-08-24 02:23
Got a locally-built copy of the runtime working and I can printf debug on-device now. When built with LLVM, the runtime fails to find any associated catch instruction ranges when unwinding. I'll keep looking into why.

**Comment by filipnavara** [comment] 2021-08-29 12:22
JFYI I was able to reproduce this on maccatalyst-arm64. It may be slightly easier to debug than the iOS version.

**Comment by imhameed** [comment] 2021-08-30 18:14
@filipnavara how did you build this with the dotnet/runtime functional test framework? And which repro .cs did you use?

**Comment by filipnavara** [comment] 2021-08-30 18:35
> how did you build this with the dotnet/runtime functional test framework? And which repro .cs did you use?

So, I started with an M1 MacBook and `build.sh -os maccatalyst -arch arm64`.

Then I replaced Program.cs of the AOT-LLVM functional test with one of your codes above (doesn't matter which one but I used the first reduces repro from GIST).

Finally I compiled the sample with `dotnet build /p:TargetOS=MacCatalyst /p:TargetArchitecture=arm64`.

if you need more precise steps I can send them when I get back to my computer. It never crashed though.

I also copied the same source code into a `dotnet new console` template, changed TFM and RID to `net6.0-maccatalyst`/`maccatalyst-arm64` and it crashes in the same way as the iOS one.

**Comment by imhameed** [comment] 2021-08-31 17:15
I'll give that a shot; thanks. I'll take a look at the AOT flags we use and why the functional test has different behavior.

**Comment by filipnavara** [comment] 2021-08-31 17:16
If there's anything else I can test or help with, let me know. I am afraid I am still few steps behind you though so there's not much I can offer.

**Comment by imhameed** [comment] 2021-08-31 22:49
Unwinding directives for LLVM-compiled Raise and SelectHostName in https://gist.github.com/imhameed/ccd542f151624c6399bd6d5c0f74b085 look reasonable: https://gist.github.com/imhameed/aef3e164aa20cffe5d7e1e0ac85c149e (just a prologue stack adjustment followed by `DW_CFA_offset`s that mark where the saved registers are located relative to the frame start).

**Comment by filipnavara** [comment] 2021-09-01 08:11
I can confirm that it fails very early on in the unwinding so it's likely not a problem in the actual unwinding information.

Working unwind:
```
2021-09-01 10:08:51.490 llvmbug[20432:4362454] --DEBUG: before
M: System.Net.Sockets.Socket:DoConnect (System.Net.EndPoint,System.Net.Internals.SocketAddress) 1.
M: System.Net.Sockets.Socket:Connect (System.Net.EndPoint) 2.
M: System.Net.Sockets.Socket:Connect (System.Net.IPAddress,int) 3.
M: System.Net.Sockets.TcpClient:Connect (string,int) 4.
M: System.Net.Sockets.TcpClient:Connect (string,int) 1.
M: System.Runtime.ExceptionServices.ExceptionDispatchInfo:Throw () 1.
M: System.Net.Sockets.TcpClient:Connect (string,int) 2.
M: System.Net.Sockets.TcpClient:.ctor (string,int) 3.
M: System.Net.Sockets.TcpClient:.ctor (string,int) 1.
M: MySingleView.Application:SelectHostName (string,int) 2.
```

Non-working unwind:
```
2021-09-01 10:08:53.519 llvmbug[20433:4362488] --DEBUG: before
M: (wrapper managed-to-native) Interop/Sys:GetProcessArchitecture () 1.
M: (wrapper managed-to-native) Interop/Sys:GetProcessArchitecture () 2.
M: (wrapper managed-to-native) Interop/Sys:StrErrorR (int,byte*,int) 3.
```

**Comment by filipnavara** [comment] 2021-09-01 08:50
I've narrowed it down a bit. When looking up the very first frame`mono_jit_info_table_find_internal` is called to find `MonoJitInfo` from the `ip` address. When it works correctly it goes through the `try_aot` branch, finds correct method and unwinds stack correctly. When it fails it hits the first branch with `jit_info_table_find` and returns early with an incorrect result.

**Comment by filipnavara** [comment] 2021-09-01 09:54
It seems that it's possible to catch the corruption early on by adding this:

```
	if (code >= amodule->jit_code_start && code < amodule->jit_code_end)
		g_assert(code + code_len <= amodule->jit_code_end);
	else
		g_assert(code + code_len <= amodule->llvm_code_end);
```

to `mono_aot_find_jit_info` just before the `jinfo = decode_exception_debug_info (amodule, method, ex_info, code, code_len);` line.

**Comment by filipnavara** [comment] 2021-09-01 10:05
So, what happens is that one AOT module has both JIT code and LLVM code. When linked into final executable these sections are quite far apart and there is a different code in-between. When the last JIT method is added it (incorrectly) fills the whole gap.

**Comment by imhameed** [comment] 2021-09-01 12:54
Thank you! And it looks like the link order xamarin-macios is using now is determined here: https://github.com/xamarin/xamarin-macios/blob/4380161309528e543107ede2ea5881299495d7ef/dotnet/targets/Xamarin.Shared.Sdk.targets#L856-L866

Contrast with: https://github.com/xamarin/xamarin-macios/blob/xamarin-ios-13.18.0.21/tools/mtouch/Target.cs#L1120-L1125

**Comment by filipnavara** [comment] 2021-09-01 13:04
Thanks for explaining the missing piece of what has changed! I don't necessarily care if my PR is accepted as the final solution but I am happy to see progress on this and explanation for the behaviour.

**Closed** 2021-09-01 17:16 UTC
Labels: blocking-release, area-Codegen-LLVM-mono, os-ios, in pr
