### ISSUE TITLE
LoggerMessage source generator fails when using file scoped namespace declarations

### ISSUE THREAD

**Issue by etreff** [dotnet/runtime#59551] opened 2021-09-23 23:35 UTC
### Description

When using the [LoggerMessage] attribute on a logger method in a class declared in a file using a file scoped namespace declaration, the source code generator will fail to generate the method implementation with the following error:

`No defining declaration found for implementing declaration of partial method`

This can be reproduced using a bare minimal project.

        using Microsoft.Extensions.Logging;
        using Microsoft.Extensions.Logging.Abstractions;
          
        namespace ConsoleApp1;
          
        public static class Program
        {
            public static void Main()
            {
                var logger = NullLogger.Instance;
                var c = new TestClass(logger);
                c.SayHello();
            }
        }
          
        public partial class TestClass
        {
            private readonly ILogger _Logger;
        
            public TestClass(ILogger logger)
            {
                _Logger = logger;
            }
        
            public void SayHello()
            {
                Console.WriteLine("Hello");
            }
        
            [LoggerMessage(EventId = 1, Level = LogLevel.Information, Message = "Sample message.")]
            partial void LogMessage();
        }

The code above produces the following error on build:

`1>C:\Users\etreff\Desktop\ConsoleApp1\ConsoleApp1\Microsoft.Extensions.Logging.Generators\Microsoft.Extensions.Logging.Generators.LoggerMessageGenerator\LoggerMessage.g.cs(11,22,11,32): error CS0759: No defining declaration found for implementing declaration of partial method 'TestClass.LogMessage()'`

Changing the namespace to the old syntax (block syntax) allows the app to compile.

### Configuration

Windows 10 x64
.NET 6.0.100-rc.1.21463.6

### Other information

Workaround: Use the old namespace declaration format when making a class that contains source generated logger messages.

**Comment by danmoseley** [comment] 2021-09-24 01:02
Thanks for the report @etreff 
Is this a duplicate of https://github.com/dotnet/runtime/issues/57880 ?

Does it repro in the latest build?

**Comment by etreff** [comment] 2021-09-24 02:17
> 
> 
> Thanks for the report @etreff
> Is this a duplicate of #57880 ?
> 
> Does it repro in the latest build?

This is indeed a duplicate of #57880. My apologies for not doing a thorough enough search.

I am using the latest of whatever is available for download without needing to compile from source. This includes the .NET 6 preview, the pre-release NuGet packages for Microsoft.Extensions.Logging, and the latest version of Visual Studio 2022.

**Comment by danmoseley** [comment] 2021-09-24 02:23
No problem would rather have two reports than miss one. We welcome any and all feedback. 

There are RC2 builds in the dotnet/installer repo or you can wait for it to come out early next month. Let us know if you hit other issues or this isn't fixed!

**Closed** 2021-09-24 02:23 UTC
Labels: untriaged, area-Extensions-Logging
