### ISSUE TITLE
The output of `build.cmd -subset help` is unclear

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#34034] opened 2020-03-24 19:41 UTC
The Build help (`build.cmd -h`) states that if I want to know what are the available combintions for `-subset` and `-subsetCategory`, you can use the `help` keyword:

```
❯ .\build.cmd -h
Common settings:
  -subset                   Build a subset, print available subsets with -subset help
  -subsetCategory           Build a subsetCategory, print available subsetCategories with -subset help
...
```

But running `build.cmd -subset help` threw some confusing output, for the following reasons:

1. The fact that `dotnet-install` starts downloading something, instead of immediately displaying the requested options, makes me think that there could be a bug. I suspect there's also the possibility that the command _needs_ to download those packages in order to be able to retrieve the available subset combinations and display them to the user. Either way, it's not clear and maybe we should display a message before downloading explaining why we are performing that task.
2. At the very end of the output, I got the message `Build FAILED`. I did not request to build anything, so maybe we should not be attempting to do any build tasks. Not sure if this is possible.
3. The `Accepted Subset Values` section lists combinations divided by the pipe `|` character, which is not right. The accepted separator value is dash `-`, as in `CoreClr-Runtime`. The pipe character will attempt to create a command line pipe in any CLI: cmd, PowerShell or bash. Example:

> ```
> D:\runtime> build.cmd -subset CoreClr|Runtime
> 'Runtime' is not recognized as an internal or external command,
> operable program or batch file.
> ```

Below is the whole output I'm talking about:
```
❯ .\build.cmd -subset help
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-preview.3.20168.11/dotnet-sdk-5.0.100-preview.3.20168.11-win-x64.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-preview.3.20168.11/dotnet-sdk-5.0.100-preview.3.20168.11-win-x64.zip
dotnet-install: Adding to current process PATH: "D:\runtime\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Installation finished

Welcome to .NET 5.0!
---------------------
SDK Version: 5.0.100-preview.3.20168.11

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. The data is anonymous. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------

  Accepted Subset values:
  - RegenerateReadmeTable [only runs on demand]
      Regenerates the table of asset links in the README.md file.
  - Libraries|All
      The .NET libraries comprising the shared framework.
  - CoreClr|Runtime
      The CoreCLR .NET runtime.
  - CoreClr|LinuxDac
      The cross-OS Windows->libc-based Linux DAC. Skipped on x86.
  - CoreClr|AlpineDac [only runs on demand]
      The cross-OS Windows->musl-libc-based Linux DAC. Skipped on x86.
  - CoreClr|CoreLib
      The managed System.Private.CoreLib library for CoreCLR.
  - CoreClr|NativeCoreLib
      Run crossgen on System.Private.CoreLib library for CoreCLR.
  - CoreClr|Tools
      Managed tools that support CoreCLR development and testing.
  - CoreClr|Packages
      The projects that produce NuGet packages for the CoreCLR runtime, crossgen, and IL tools.
  - Mono|All
      The Mono .NET runtime.
  - Installer|All
      The .NET Core hosts, hosting libraries, bundles, and installers. Includes these projects' tests.
  - Installer|CoreHost
      The .NET Core hosts.
  - Installer|Managed
      The managed .NET hosting projects. This includes PlatformAbstractions, DependencyModel, and HostModel.
  - Installer|DepProj
      The dependency projects. These gather shared framework files and run crossgen on them to turn them into ready-to-run (R2R) assemblies for the current platform.
  - Installer|PkgProj
      The packaging projects. These produce NETCoreApp assets: NuGet packages, installers, zips, and Linux packages.
  - Installer|Bundle
      The shared framework bundle installer projects. Produces .exe installers for Windows.
  - Installer|Installers
      Generates additional installers. This produces the shared frameworks and their installers.
  - Installer|Test
      The test projects. Note that building this doesn't execute tests: you must also pass the '-test' argument.

D:\runtime\eng\Build.props(53,5): error : Choose a subset to use, or do not specify a subset to perform the full build.
 [C:\Users\calope\.nuget\packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20168.2\tools\Build.proj]

Build FAILED.

D:\runtime\eng\Build.props(53,5): error : Choose a subset to use, or do not specify a subset to perform the full build.
 [C:\Users\calope\.nuget\packages\microsoft.dotnet.arcade.sdk\5.0.0-beta.20168.2\tools\Build.proj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.17
Build failed.
Some builds failed:
        Configuration: Debug, Architecture: x64
```

**Comment by safern** [comment] 2020-03-26 20:11
Closing as a dupe of: https://github.com/dotnet/runtime/issues/33167

**Closed by safern** 2020-03-26 20:11 UTC
Labels: area-Infrastructure-coreclr, untriaged
