### ISSUE TITLE
Invalid pointer address during network call

### ISSUE THREAD

**Issue by mcliment** [dotnet/runtime#55010] opened 2021-07-01 12:41 UTC
### Description

We intermittently get a `The system detected an invalid pointer address in attempting to use a pointer argument in a call.` during a network call using latest .NET 5.0.7 SDK on Azure web app using .NET 5 / 32bit.

I cannot provide a snippet because I can only reproduce the error in production environment (under load, not happening in a deployment slot or in a less busy environment). The code that fails basically is a `HttpWebRequest` call to get the response (not async). So I need a running app to reproduce.

The code that fails is 99% like this: https://github.com/LordVeovis/xmlrpc/blob/master/Kveer.XmlRPC/XmlRpcClientProtocol.cs

### Configuration

* Compiled with .NET Core SDK 5.0.301
* Running on Azure Web Application
* .NET 5 / 32 bit (this seems important, unable to reproduce in 64bit)

### Regression?

The same code was running properly last week using ASP.NET 4.8 and built with .NET Sdk 3.1.404 with a 32bit configuration.

### Other information

Stack trace (IP 1.2.3.4 and domain our.server.com is rewritten):

```
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: The system detected an invalid pointer address in attempting to use a pointer argument in a call. [::ffff:1.2.3.4]:8069
  ?, in void Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
  ?, in void Socket.Connect(EndPoint remoteEP) x 5
  ?, in Stream ConnectHelper.Connect(string host, int port, CancellationToken cancellationToken)
System.Net.Http.HttpRequestException: The system detected an invalid pointer address in attempting to use a pointer argument in a call. [::ffff:13.69.121.169]:8069 (our.server.dns:8069)
  ?, in Stream ConnectHelper.Connect(string host, int port, CancellationToken cancellationToken)
  ?, in ValueTask<Stream> HttpConnectionPool.ConnectToTcpHostAsync(string host, int port, HttpRequestMessage initialRequest, bool async, CancellationToken cancellationToken)
  ?, in async ValueTask<ValueTuple<Socket, Stream, TransportContext, HttpResponseMessage>> HttpConnectionPool.ConnectAsync(HttpRequestMessage request, bool async, CancellationToken cancellationToken)
  ?, in async ValueTask<ValueTuple<HttpConnection, HttpResponseMessage>> HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, bool async, CancellationToken cancellationToken)
  ?, in async ValueTask<(HttpConnectionBase connection, bool isNewConnection, HttpResponseMessage failureResponse)> HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, bool async, CancellationToken cancellationToken)
  ?, in async ValueTask<HttpResponseMessage> HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, bool async, bool doRequestAuth, CancellationToken cancellationToken)
  ?, in async ValueTask<HttpResponseMessage> RedirectHandler.SendAsync(HttpRequestMessage request, bool async, CancellationToken cancellationToken)
  ?, in HttpResponseMessage HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
  ?, in HttpResponseMessage SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
  ?, in HttpResponseMessage DelegatingHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
  ?, in async ValueTask<HttpResponseMessage> DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, bool async, CancellationToken cancellationToken)
  ?, in HttpResponseMessage DiagnosticsHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
  ?, in HttpResponseMessage HttpClientHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
  ?, in HttpResponseMessage HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
  ?, in async ValueTask<HttpResponseMessage> HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, bool async, bool emitTelemetryStartStop, CancellationToken cancellationToken)
  ?, in HttpResponseMessage HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
  ?, in async Task<WebResponse> HttpWebRequest.SendRequest(bool async)
  ?, in WebResponse HttpWebRequest.GetResponse()
System.Net.WebException: The system detected an invalid pointer address in attempting to use a pointer argument in a call. [::ffff:1.2.3.4]:8069 (our.server.dns:8069)
  ?, in WebResponse HttpWebRequest.GetResponse()
  File "C:\**REDACTED**\XmlRpcClientProtocol.cs", line 810, col 4, in WebResponse XmlRpcClientProtocol.GetWebResponse(WebRequest request)
  File "C:\**REDACTED**\XmlRpcClientProtocol.cs", line 164, col 4, in object XmlRpcClientProtocol.Invoke(object clientObj, MethodInfo mi, params object[] parameters)
  ?, in object XmlRpcProxy8a6acf37-0e1b-4b8f-a9db-7d5a34e64031.login(in string databaseName, in string userName, in string password)
  File "C:\**REDACTED**\HealthChecks\OpenErpHealthCheck.cs", line 44, col 9, in Task<HealthCheckResult> OpenErpHealthCheck.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken)
```

I could also provide a Snapshot Dump from Azure AI but not in this channel.

I don't have any clue about what the problem can be, I tried to use `HttpClient` instead of `HttpWebRequest` but the problem persisted (also, `HttpWebRequest` uses `HttpClient` internally).

The problem only occurs in production environment (I can imagine that is due to the load) and with a 32bit configuration but we were not able to reproduce in any other environment not even in deployment slots with 100% the same configuration as the production site.

The only workaround we found was switching to 64bit.

**Comment by karelz** [comment] 2021-07-01 12:53
@mcliment this will be challenging to track down ... dump may be the only way forward ...

Did you try to generate similar load pattern in your test environment?
Did you try to simplify the app and run similar load pattern in your production environment?

**Comment by mcliment** [comment] 2021-07-01 13:13
@karelz I can provide a Snapshot from Azure App Insights but I didn't want to put it in GitHub as it may contain sensitive data.

**Comment by karelz** [comment] 2021-07-01 13:23
@mcliment let me check with others if they think it may be useful. Can you publish it somewhere privately and then send me link to my email?
It may still take us few days or couple of weeks to get to it ... just heads up ...

**Comment by antonfirsov** [comment] 2021-08-04 14:01
@mcliment first of all, apologies for the long delay.

The reported error message means we are getting a `WSAEFAULT` socket error from winsock `connect`, which might be an issue around IPV4 - IPV6 socket address mapping in the .NET Socket code, however it's very hard to tell more without seeing a repro in your environment, or at least a dump. I would be also interested about details at the `void Socket.Connect(EndPoint remoteEP) x 5` call stack line.

@karelz is on vacation now so can't ask him if he got the email with the dump, if you are still interested sharing it, maybe we can discuss it on twitter (just followed you).

Couple of things you can try:
1. Replace the host name with a string containing IP4 address of the server
2. Replace the host name with a string containing the IPv6-mapped address (`[::ffff:1.2.3.4]`)
3. With .NET 6 preview 7 (should be available in about a week):
Set the environment variable `DOTNET_SYSTEM_NET_DISABLEIPV6` to `1` before running your application. (Or set the AppContext switch `System.Net.DisableIPv6` to `true`.)

I'm curious if any of these workarounds help.

**Comment by antonfirsov** [comment] 2021-08-04 14:03
Triage: Since it's not a 5.0 -> 6.0 regression, I pushing the issue to 7.0.

**Comment by mcliment** [comment] 2021-08-04 21:20
Hi @antonfirsov, thanks for checking up.

At ths this moment, using 64bit process is working like a charm since I opened the ticket. Not sure if that gives some clues.

I contacted you over Twitter to send you the dumps that I sent to your colleague.

As for the proposed solutions, I think I tried many things, including using IP address and IPv6 address, but I'll try again when I come back from vacation with a more _scientific_ approach. The third solution may be difficult to apply as this only seems to happen on our production site and I haven't been able to reproduce in isolation or a test environment in Azure mimicking the production one.... seems to be due to resource consumption or concurrency but that's a long shot.

Let's see if you can find something in the logs.

**Comment by antonfirsov** [comment] 2021-08-05 11:51
@mcliment thank you for the dump!

I had a look, both `IPEndPoint` and `SocketAddress` seem to be valid and correct, despite `WSAConnect` failing with `WSAEFAULT`. The most sane thing I can think of is a bug in winsock DualMode sockets on 32 bit. I'm about to contact the winsock team if they are aware of any known issues. Do you know the Windows version (`[System.Environment]::OSVersion.Version`) of the Azure machine?

**Comment by mcliment** [comment] 2021-08-05 13:04
I ran the command in the current machine:

```
[System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      14393  0
```

Not sure if that was the version in the moment the bug was happening, but the web app is exactly the same.

**Comment by antonfirsov** [comment] 2021-08-05 13:52
Thanks! Let's see if the winsock folks can report back something interesting. BTW build 14393 means 1607 (Anniversary Update), which is quite old.

**Comment by mcliment** [comment] 2021-08-25 10:03
@antonfirsov The build may be old but being a managed service I can't see how to update the OS version for azure App Services.

**Comment by karelz** [comment] 2021-08-25 12:30
@mcliment let's wait for winsock team to get back to us first (we just pinged them).
If it happens only in AppService, it would be good to clarify it is not one bad VM problem, or something like that. You might have to contact AppService support to get to the bottom of that ...

**Comment by antonfirsov** [comment] 2021-09-01 13:03
We've got a reply from winsock team, and unfortunately they haven't seen this issue before. Since we don't have a repro we could investigate and hand over to them, I'm closing this as not actionable. There is a workaround (switching to 64bits) which seems to work well.

We can reopen (or open a new issue) if a repro becomes available or more users end up hitting this.

**Closed by antonfirsov** 2021-09-01 13:03 UTC
Labels: area-System.Net.Sockets, tracking-external-issue

**Comment by karelz** [comment] 2021-09-01 15:40
@mcliment you might want to try to engage Azure App Service support to see if they can help you narrow it down ...
