### ISSUE TITLE
MakeGenericMethod accepts type that violates unmanaged constraint

### ISSUE THREAD

**Issue by FstTesla** [dotnet/runtime#103035] opened 2024-06-04 13:31 UTC
### Description

The [`MethodInfo.MakeGenericMethod(Type[] typeArguments)`](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.methodinfo.makegenericmethod?view=net-8.0&devlangs=csharp) instance method should throw an `ArgumentException` if an element of `typeArguments` does not satisfy the constraints specified for the corresponding type parameter.
Anyway, is it possible to succesfully create a constructed generic method with a violation of the `unmanaged` constraint.

### Reproduction Steps

```csharp
static unsafe long GetUnmanagedSize<T>() where T : unmanaged => sizeof(T);
```

Suppose you have a `MethodInfo getUnmanagedSizeMethodDef` referencing the generic definition of the method above. Then execute the following:
```csharp
MethodInfo getUnmanagedSizeMethod = getUnmanagedSizeMethodDef.MakeGenericMethod(typeof((int, string)));
```

### Expected behavior

An `ArgumentException` is thrown, with a message similar to this:
> GenericArguments[0], 'System.ValueTuple\`2[System.Int32,System.String]', on 'Int64 GetUnmanagedSize\[T]()' violates the constraint of type 'T'.

### Actual behavior

The `getUnmanagedSizeMethod` variable contains the invalid constructed generic method.

### Known Workarounds

Before invoking `MakeGenericMethod`, one could verify that `RuntimeHelpers.IsReferenceOrContainsReferences` returns false for all type arguments with an `unmanaged` constraint.

### Configuration

.NET 8.0.5 runtime

### Other information

From my experiments, I speculate that the `unmanaged` constraint check succeeds capturing the violation if the top-level type is a reference type, but fails if it is a value type with non-unmanaged-typed fields.
In other terms, the conditions 4 and 5 in the first dotted list in the [_Unmanaged types_ specification](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/unmanaged-types) are skipped.

As a final curiosity, the `getUnmanagedSizeMethod.Invoke(null, [])` expression (where the `getUnmanagedSizeMethod` variable contains the invalid method created above) returns the value **16**.

**Comment by vcsjones** [comment] 2024-06-04 13:58
This looks like a duplicate of #102017 and #12420

**Comment by MichalStrehovsky** [comment] 2024-06-04 18:40
> This looks like a duplicate of #102017 and #12420

Yes, duplicate of https://github.com/dotnet/runtime/issues/12420

**Closed by MichalStrehovsky** 2024-06-04 18:40 UTC
Labels: area-System.Reflection, untriaged
