### ISSUE TITLE
Process.GetProcesses returns processes with truncated names on MacOS

### ISSUE THREAD

**Issue by valentiniliescu** [dotnet/runtime#69883] opened 2022-05-26 22:26 UTC
### Description

When running `Process.GetProcesses()` to get a list of processes , and then output `Process.ProcessName` for each process, the process name is truncated to 15 characters when running on MacOS.

Note that when executing the same code on Windows or on MacOS under Mono, the names are not truncated, as expected. This seems related to #28346 that was fixed, but only on Linux.

### Reproduction Steps

```
using System.Diagnostics;

foreach (var process in Process.GetProcesses())
{
    try
    {
        if (!string.IsNullOrEmpty(process.ProcessName))
        {
            Console.WriteLine(process.ProcessName);
        }
    }
    catch { }
}
```

### Expected behavior

The processes names are listed without being truncated, e.g.

ContextStoreAgent
com.apple.siri.embeddedspeech
pbs
assistantd
diagnosticextensionsd
pkd
ctkd
UsageTrackingAgent

### Actual behavior

The process names are truncated to 15 characters, e.g.

ContextStoreAge
com.apple.siri.
pbs
assistantd
diagnosticexten
pkd
ctkd
UsageTrackingAg

### Regression?

It works fine when running under Mono 6.12.0.114 on the same MacOS version listed in the configuration.

### Configuration

.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.4
 OS Platform: Darwin
 RID:         osx.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.202/

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

**Comment by vcsjones** [comment] 2022-05-26 23:22
Duplicate of #52860

**Closed by vcsjones** 2022-05-26 23:22 UTC
Labels: area-System.Diagnostics.Process, untriaged
