### ISSUE TITLE
Profiling API: Different ClassID in ClassLoad and ClassUnload callbacks

### ISSUE THREAD

**Issue by NitzanEgozy** [dotnet/runtime#13249] opened 2019-08-12 09:36 UTC
Hey all,
this is a followup of a bug we encountered in all .Net frameworks version, which was un-reproducible until recently (.Net Core < 3 didn't support class unloading).
First, I'll link to the original posts (SO and msdn forums): https://stackoverflow.com/questions/54883986/icorprofilercallbackclassunloadstarted-not-called-for-a-generic-class-even-th https://social.msdn.microsoft.com/Forums/vstudio/en-US/06f3022d-0d6e-450c-8100-9e082fb21ee1/icorprofilercallbackclassunloadstarted-not-called-for-a-generic-class-instantiation-even-though?forum=clr

We further analyzed it back then and noticed we get a different ClassID on load then we get on Unload.

I managed to reproduce in on latest .net core preview (3.0.100-preview7-012821) on Windows 10. You can find it here: https://github.com/NitzanEgozy/dotnet/tree/master/testers/Unloading (cd out, run.bat)
The important part of the output:
```
ClassLoadFinished: Plugin.PluginClass (140731382877856)
...
ClassLoadFinished: Plugin.MyGenericTest (140731382879056)
...
ClassLoadFinished: Plugin.MyGenList`1 <System.__Canon> (140731382880136)
ClassLoadFinished: Plugin.MyGenList`1 <System.String> (140731382880344)
...
ERROR - can't retrieve moduleId
ClassUnloadStarted: Plugin.MyGenList`1 <Unknown> (140731382879688)
ClassUnloadStarted: Plugin.MyGenericTest (140731382879056)
ClassUnloadStarted: Plugin.PluginClass (140731382877856)
ClassUnloadStarted: Plugin.MyGenList`1 <System.__Canon> (140731382880136)
```
As we can see, Plugin.MyGenList1 is loaded twice and unloaded twice. The load/unload for System.__Canon is fine (same ClassID). We have another Load/Unload set. The Load is for System.String, but the the unload is unknown (Can't retrieve moduleID, probably too late). They are of *different* ClassIDs. Also, the loaded ClassID (Plugin.MyGenList1 <System.String> (140731382880344)) is never unloaded, and the unloaded ClassID (Plugin.MyGenList1 <Unknown> (140731382879688)) is never loaded, nor do we get this ClassID in any other way.

This is a huge issue for profilers who rely on tracking currently loaded classes.

**Comment by davmason** [comment] 2020-11-13 20:54
Closing as by design

**Closed by davmason** 2020-11-13 20:54 UTC
Labels: area-Diagnostics-coreclr, tracking

**Comment by NitzanEgozy** [comment] 2020-11-15 07:05
What do you mean "by design"? In your previous comment, you detailed the bug and where you think the fix should take place.
This bug is a pretty big deal for any Profiler that tracks class loads/unloads in order to create a mapping.

**Comment by davmason** [comment] 2020-12-01 00:18
Sorry for the delay, I was out for a couple weeks on vacation.

"By design" isn't the best phrasing. The issue is that this involves a bunch of really low level code that hasn't changed in forever, so fixing carries some real risk that we could break something unrelated.

There is a relatively simple workaround available - instead of relying on the class unload callback, you can rely on the module unload callback and unload all classes from that module. We do that in the profiler tests here: https://github.com/dotnet/runtime/blob/9f92311867ec86a5d696b94c3c7def6060f6ef07/src/tests/profiler/native/getappdomainstaticaddress/getappdomainstaticaddress.cpp#L150-L246

Since there is a workaround and the fix has risk, this bug is unlikely to get fixed.
