### ISSUE TITLE
only on iOS: System.Text.Json: Method not found System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8

### ISSUE THREAD

**Issue by leastprivilege** [dotnet/runtime#49477] opened 2021-03-11 11:06 UTC
The above error occurs only on iOS in IdentityModel

```
System.TypeInitializationException: The type initializer for 'System.Text.Json.JsonSerializer' threw an exception. ---> 
System.MissingMethodException: Method not found: int System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8(System.ReadOnlySpan`1<byte>)
  at System.Text.Json.JsonEncodedText.EncodeHelper (System.ReadOnlySpan`1[T] utf8Value, System.Text.Encodings.Web.JavaScriptEncoder encoder) [0x00000] in <7e3a59f5e4004edbb4b17c580799cc52>:0 
  at System.Text.Json.JsonEncodedText.TranscodeAndEncode (System.ReadOnlySpan`1[T] value, System.Text.Encodings.Web.JavaScriptEncoder encoder) [0x00033] in <7e3a59f5e4004edbb4b17c580799cc52>:0 
  at System.Text.Json.JsonEncodedText.Encode (System.ReadOnlySpan`1[T] value, System.Text.Encodings.Web.JavaScriptEncoder encoder) [0x00014] in <7e3a59f5e4004edbb4b17c580799cc52>:0 
  at System.Text.Json.JsonEncodedText.Encode (System.String value, System.Text.Encodings.Web.JavaScriptEncoder encoder) [0x00014] in <7e3a59f5e4004edbb4b17c580799cc52>:0 
  at System.Text.Json.JsonSerializer..cctor () [0x00042] in <7e3a59f5e4004edbb4b17c580799cc52>:0 
```

https://www.nuget.org/packages/IdentityModel/5.1.0-preview.1

which is used here:
https://www.nuget.org/packages/IdentityModel.OidcClient/4.0.0-preview.8

here's a repo using Xamarin:
https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/tree/main/iOS_AuthenticationServices (you need to upgrade to the above OidcClient package)

this is the original issue opened in our repo:
https://github.com/IdentityModel/IdentityModel/issues/382

Let me know if I can help in any way to make diagnosing easier.

**Comment by filipnavara** [comment] 2021-03-11 11:51
This has been reported numerous times already on xamarin/xamarin-macios, mono/mono and dotnet/runtime:

https://github.com/xamarin/xamarin-macios/issues/10839
https://github.com/xamarin/xamarin-macios/issues/10548
https://github.com/xamarin/xamarin-macios/issues/10592
https://github.com/mono/mono/issues/20805
https://github.com/mono/mono/issues/20894
https://github.com/dotnet/runtime/issues/49211

**Comment by filipnavara** [comment] 2021-03-11 11:52
Workaround: https://github.com/mono/mono/issues/20805#issuecomment-791440473

**Comment by marek-safar** [comment] 2021-03-19 15:30
Duplicate of #49211

**Closed by marek-safar** 2021-03-19 15:30 UTC
Labels: area-VM-meta-mono, untriaged
