### ISSUE TITLE
[CoreCLR] Microsoft.DotNet.CoreSetup.Test.HostActivation.FrameworkResolution.RollForwardOnNoCandidateFx.RollForwardOnMinor_RollOverPreRelease Test failure HostActivation.Tests_net6.0_x86 

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#58501] opened 2021-09-01 14:39 UTC
Failure on unrelated PR https://github.com/dotnet/runtime/pull/58456
```
XUnit : error : Tests failed: D:\workspace\_work\1\s\artifacts\TestResults\Debug\HostActivation.Tests_net6.0_x86.html [net6.0|x86] [D:\workspace\_work\1\s\src\installer\tests\HostActivation.Tests\HostActivation.Tests.csproj]
##[error]XUnit(0,0): error : (NETCORE_ENGINEERING_TELEMETRY=Test) Tests failed: D:\workspace\_work\1\s\artifacts\TestResults\Debug\HostActivation.Tests_net6.0_x86.html [net6.0|x86]
```
Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1331944&view=logs&j=f827f174-7a88-54e3-54c2-8dcd28f39edd&t=5bc77b52-54d3-5da9-c79e-6dacacea45ab

Installer-coreclr-windows_x86-Debug
RollForwardOnMajor_PicksLatestReleasePatch
RollForwardToPreReleaseToClosestPreRelease_FromRelease
RollForwardOnMinor_RollOverPreRelease
RollForwardToClosestReleaseWithPreReleaseAvailable_FromRelease
RollForwardToPreReleaseOnMinor_FromRelease
RollForwardToLatestPatch_PicksLatestReleasePatch
ReconcileFrameworkReferences_InnerFrameworkReference_PreRelease
RollForwardToPreReleaseToLatestPatch_FromRelease
RollForwardOnMinor_PicksLatestReleasePatch
RollForwardToLatestPatch_WithHigherPreReleasePresent

**Comment by vitek-karas** [comment] 2021-09-02 08:27
This is very likely a duplicate of https://github.com/dotnet/runtime/issues/58228.

**Closed by vitek-karas** 2021-09-02 08:27 UTC
Labels: area-Host, untriaged
