### ISSUE TITLE
Test failure Loader/AssemblyLoadContext30Extensions/AssemblyLoadContext30Extensions/AssemblyLoadContext30Extensions.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#53403] opened 2021-05-28 02:08 UTC
Run: [runtime-coreclr gcstress0x3-gcstress0xc 20210526.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1158649&view=ms.vss-test-web.build-test-results-tab&runId=34974626&resultId=111109&paneView=debug)

Failed test:
```
CoreCLR Linux arm Checked gcstress0x3 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- Loader/AssemblyLoadContext30Extensions/AssemblyLoadContext30Extensions/AssemblyLoadContext30Extensions.sh

```
**Error message:**
```
Return code:      1
Raw output file:      /root/helix/work/workitem/Loader/AssemblyLoadContext30Extensions/Reports/Loader.AssemblyLoadContext30Extensions/AssemblyLoadContext30Extensions/AssemblyLoadContext30Extensions.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun AssemblyLoadContext30Extensions.dll ''
"Default" System.Runtime.Loader.DefaultAssemblyLoadContext #0
System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
AssemblyLoadContext30Extensions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
System.Runtime.Loader, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
System.Console, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
System.Threading, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
System.Runtime.InteropServices, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Microsoft.Win32.Primitives, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
DefaultName()
Default
System.Runtime.Loader.DefaultAssemblyLoadContext
"Default" System.Runtime.Loader.DefaultAssemblyLoadContext #0
AssemblyLoadFileName()
Assembly.LoadFile(/root/helix/work/workitem/Loader/AssemblyLoadContext30Extensions/AssemblyLoadContext30Extensions/AssemblyLoadContext30Extensions.dll)
System.Runtime.Loader.IndividualAssemblyLoadContext
"Assembly.LoadFile(/root/helix/work/workitem/Loader/AssemblyLoadContext30Extensions/AssemblyLoadContext30Extensions/AssemblyLoadContext30Extensions.dll)" System.Runtime.Loader.IndividualAssemblyLoadContext #1
CustomWOName()

My.CustomAssemblyLoadContext
"" My.CustomAssemblyLoadContext #2
CustomName()
CustomName
System.Runtime.Loader.AssemblyLoadContext
"CustomName" System.Runtime.Loader.AssemblyLoadContext #3
GetLoadContextForDynamicAssembly; isCollectible=True
FAIL! none
GetLoadContextForDynamicAssembly; isCollectible=False
FAIL! none
"Default" System.Runtime.Loader.DefaultAssemblyLoadContext #0
System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
AssemblyLoadContext30Extensions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
System.Runtime.Loader, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
System.Console, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
System.Threading, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
System.Runtime.InteropServices, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Microsoft.Win32.Primitives, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
System.Reflection.Emit, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
System.Linq, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
"Assembly.LoadFile(/root/helix/work/workitem/Loader/AssemblyLoadContext30Extensions/AssemblyLoadContext30Extensions/AssemblyLoadContext30Extensions.dll)" System.Runtime.Loader.IndividualAssemblyLoadContext #1
AssemblyLoadContext30Extensions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
"" My.CustomAssemblyLoadContext #2
"CustomName" System.Runtime.Loader.AssemblyLoadContext #3
"ALC - False" System.Runtime.Loader.AssemblyLoadContext #5
Test FAILED!
Expected: 100
Actual: 255
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/Loader/AssemblyLoadContext30Extensions/AssemblyLoadContext30Extensions/AssemblyLoadContext30Extensions.sh
Expected: True
Actual:   False


Stack trace
   at Loader_AssemblyLoadContext30Extensions._AssemblyLoadContext30Extensions_AssemblyLoadContext30Extensions_._AssemblyLoadContext30Extensions_AssemblyLoadContext30Extensions_sh()
```

**Comment by vitek-karas** [comment] 2021-05-28 15:44
Duplicate of https://github.com/dotnet/runtime/issues/53335.

**Closed by vitek-karas** 2021-05-28 15:44 UTC
Labels: GCStress, arch-arm32, area-AssemblyLoader-coreclr, os-linux, untriaged
