### ISSUE TITLE
Huge slowdowns on threaded operations when debugger attached

### ISSUE THREAD

**Issue by Mithras** [dotnet/runtime#52149] opened 2021-05-01 01:22 UTC
### Description

I'm not 100% sure but it seems to be the same as https://github.com/dotnet/runtime/issues/10605 or https://github.com/OmniSharp/omnisharp-vscode/issues/2432#issuecomment-411884014 (except it's not Docker specific and can repo on any *nix host).
Originally I noticed that a simple EF Core query like `await context.Foo.TolistAsync()` takes ~10x time in Ubuntu container compared to Windows host (both with debugger attached). Interestingly, `context.Foo.Tolist()` is only 2x slower with debugger attached. With no debugger attached performance between Windows host and Ubuntu container is within ~10% from each other.

Simple repo snippet:
```
class Program
{
    static async Task Main(string[] args)
    {
        Console.ReadLine();

        var tasks = new Task[1000];
        var sw = new Stopwatch(); sw.Start();
        for (int i = 0; i < 1000; i++)
        {
            tasks[i] = Task.Factory.StartNew(() => { }, TaskCreationOptions.LongRunning);
        }
        await Task.WhenAll(tasks);
        sw.Stop();

        Console.WriteLine(sw.ElapsedMilliseconds);
    }
}
```
Output:
1. "dotnet run" on Windows: 78
2. "dotnet run" on Ubuntu (WSL2): 101
3. "dotnet run" + "coreclr attach" on Windows: 4229  // <--- **Way slower when I would expect**
4. "dotnet run" + "coreclr attach" on Ubuntu (WSL2): 14417 // <--- **3 times slower than already slow Windows**

launch.json
```
{
  "name": ".NET Core Attach",
  "type": "coreclr",
  "request": "attach",
  "processId": "${command:pickProcess}"
}
```

### Configuration

* Which version of .NET is the code running on?
NET 5
* What OS version, and what distro if applicable?
1. Docker for Windows + https://github.com/microsoft/vscode-dev-containers/tree/v0.166.1/containers/dotnet
2. Docker for Mac + https://github.com/microsoft/vscode-dev-containers/tree/v0.166.1/containers/dotnet
3. Native Mac OS
* What is the architecture (x64, x86, ARM, ARM64)?
x64

### Regression?

Not sure. I can confirm the same on netcoreapp3.1.

**Comment by tommcdon** [comment] 2021-05-01 16:56
@hoyosjs

**Comment by Mithras** [comment] 2021-05-03 19:27
I just want to clarify that this is not about some synchetic test I came up with. Some of our APIs take about 4x time with debugger attached on *nix hosts which makes local developement frustrating.

**Comment by hoyosjs** [comment] 2021-05-03 21:43
This feels like a dupe of #47204 and #38736

**Comment by Mithras** [comment] 2021-05-03 23:17
@hoyosjs Thank you!
Are there plans to either fix it or at least provide an official workaround? Maybe a config parameter that turns NotifyOfCrossThreadDependencySlow() off?
In the mean time I'm willing to try to build a custom System.Private.CoreLib.dll with the [line](https://github.com/dotnet/runtime/blob/e4c6c4c4422b15c526642ee139e89bda4f83b242/src/coreclr/System.Private.CoreLib/src/System/Diagnostics/Debugger.cs#L50) commented out as we are trying to use dev containers for local developement and replacing a .dll should be a reasonable workaround for us.
Are there any articles/guides that might help me figure out how to build/replace a .dll in .NET? Is it as simple as it sounds?

**Comment by hoyosjs** [comment] 2021-05-03 23:29
I am planning a fix that will hopefully make .NET 6. As for building your own, it shouldn't be complicated as long as you use it only in your dev environment (and know that this might lead to deadlocks while debugging). What version are you trying to build?

**Comment by Mithras** [comment] 2021-05-04 00:19
>as long as you use it only in your dev environment

Yes, only for dev enviroment.

>What version are you trying to build?

Whatever version in the latest 5.0 variant of this: https://github.com/microsoft/vscode-dev-containers/tree/v0.166.1/containers/dotnet
`dotnet --info` shows
```
.NET SDKs installed:
  5.0.202 [/usr/share/dotnet/sdk]
.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
```

**Comment by hoyosjs** [comment] 2021-05-04 00:34
Yeah, right now it's 5.0.5. For that one, clone the runtime repo, checkout the v5.0.5 tag, make your edit, and mount that directory into this container (mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-359e48e-20200313130914). Then from the root of the repo you can get the build by running:

```
./src/coreclr/build-runtime.sh release x64  -ci -clang9 /p:OfficialBuildId=20210316.9
./build.sh -subset clr.corelib+clr.nativecorelib -arch x64  -c release /p:OfficialBuildId=20210316.9 -ci
```

Then you can copy the files in `artifacts/bin/coreclr/Linux.x64.Release/sharedFramework/` and `artifacts/bin/coreclr/Linux.x64.Release/System.Private.CoreLib.dll` to wherever your runtime is in your container (be it a self contained publish or in the global location). This will give you the closest behavior to one of our builds.

**Comment by Mithras** [comment] 2021-05-04 00:38
Thank you! I will try it when I have some time.

**Comment by hoyosjs** [comment] 2021-05-04 00:39
I'll close this as there's other issues tracking this. However, feel free to write on here as needed if you hit any bumps.

**Closed by hoyosjs** 2021-05-04 00:39 UTC
Labels: area-Diagnostics-coreclr, tenet-performance

**Comment by Mithras** [comment] 2021-05-04 03:06
I can confirm that the workaround works.

Before commentiong out `NotifyOfCrossThreadDependencySlow();`
![image](https://user-images.githubusercontent.com/2098029/116956786-02892880-ac4b-11eb-88e9-2b5e8d4d0243.png)
After:
![image](https://user-images.githubusercontent.com/2098029/116956404-108a7980-ac4a-11eb-85ae-66a9f87dbb3d.png)

Thanks @hoyosjs!
