### ISSUE TITLE
TLS RVA leads to a crash

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#63622] opened 2022-01-11 12:56 UTC
@MichalStrehovsky and @SingleAccretion reminded that `tls` can be applied to RVA fields and RyuJIT [even has](https://github.com/dotnet/runtime/blob/fe8422cdff450941bc3ba4b120576e8822459df4/src/coreclr/jit/morph.cpp#L6157-L6180) some special logic to emit an optimized access to them (only for 32bit and only on Windows) but it seems it doesn't work, minimal repro:
```IL
.assembly extern System.Private.CoreLib {}
.assembly global {}

.field static public int32 a at D_00

.method public static int32 Main()
{
  .entrypoint
  ldsfld int32 a
  ret
}

.data tls D_00 = int32(1)
```
this IL program works on both 32bit and 64bit on .NET Framework 4.8 and crashes with 
```
Fatal error. 0xC0000005
   at <Module>.Main()  
```
on .NET 6.0 32bit and `System.BadImageFormatException` on x64

**Comment by jkotas** [comment] 2022-01-11 13:15
Duplicate of #42187 ?

**Closed** 2022-01-11 13:17 UTC
Labels: area-CodeGen-coreclr, untriaged
