### ISSUE TITLE
Test failure: System.Text.Json.Serialization.Tests.PipeTests.CancelPendingFlushDuringBackpressureThrows

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#102532] opened 2024-05-22 01:19 UTC
**Failed in:** [runtime-coreclr libraries-jitstress 20240521.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=682386&view=ms.vss-test-web.build-test-results-tab&runId=16934442&resultId=208328&paneView=debug)

**Failed tests:**
```
net9.0-linux-Release-arm64-jitstress1-(Ubuntu.1804.Arm64.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
    - System.Text.Json.Serialization.Tests.PipeTests.CancelPendingFlushDuringBackpressureThrows
```

**Error message:**
```
 Assert.Equal() Failure: Values differ
Expected: 12
Actual:   13
```

**Stack trace:**
```
   at System.Text.Json.Serialization.Tests.PipeTests.CancelPendingFlushDuringBackpressureThrows()
--- End of stack trace from previous location ---
```

**Comment by eiriktsarpalis** [comment] 2024-05-22 07:59
cc @BrennanConroy. Is this a duplicate of the other test failure you fixed recently perhaps?

**Comment by BrennanConroy** [comment] 2024-05-22 16:25
Ugh, maybe I'll just remove the check since it's probably not really needed.

**Comment by v-wenyuxu** [comment] 2024-05-27 01:20
**Failed in:** [runtime-coreclr libraries-jitstressregs 20240526.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=687882&view=ms.vss-test-web.build-test-results-tab&runId=17080192&resultId=205410&paneView=debug)

**Failed tests:**
```
net9.0-linux-Release-arm-jitstressregs3-(Debian.12.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-12-helix-arm32v7
    - System.Text.Json.Serialization.Tests.PipeTests.CancelPendingFlushDuringBackpressureThrows
```

**Error message:**
```
 Assert.Equal() Failure: Values differ
Expected: 12
Actual:   13
```

**Stack trace:**
```
   at System.Text.Json.Serialization.Tests.PipeTests.CancelPendingFlushDuringBackpressureThrows()
--- End of stack trace from previous location ---
```

**Comment by v-wenyuxu** [comment] 2024-06-03 02:12
**Failed in:** [runtime-coreclr libraries-pgo 20240602.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695278&view=ms.vss-test-web.build-test-results-tab&runId=17277356&resultId=199311&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x64-fullpgo_methodprofiling-Windows.10.Amd64.Open
    - System.Text.Json.Serialization.Tests.PipeTests.CancelPendingFlushDuringBackpressureThrows
```

**Error message:**
```
 Assert.Equal() Failure: Values differ
Expected: 12
Actual:   13
```

**Stack trace:**
```
   at System.Text.Json.Serialization.Tests.PipeTests.CancelPendingFlushDuringBackpressureThrows() in /_/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/Serialization/Pipe.WriteTests.cs:line 106
--- End of stack trace from previous location ---
```

**Comment by eiriktsarpalis** [comment] 2024-06-03 10:11
@BrennanConroy could you take another look please? Seems to be failing still.

**Closed** 2024-06-05 17:10 UTC
Labels: arch-arm64, area-System.Text.Json, os-linux, JitStress, untriaged, blocking-clean-ci-optional
