### ISSUE TITLE
[WASM] Workloads-.BlazorWasmBuildPublishTests failed on Build Browser wasm Linux Release WasmBuildTests sporadically

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#66591] opened 2022-03-14 15:23 UTC
Run: [Build Browser wasm Linux Release WasmBuildTests 20220311.45](https://dnceng.visualstudio.com/public/_build/results?buildId=1659140&view=logs&j=6f051c1a-c3e7-5cde-411e-64125624a208&t=961bb5d4-39cc-55d0-23ed-82f28319785b)

Above is the link to the latest failure. I've seen it being hit 3 times during the past week.

Error message:
```
dwarf /datadisks/disk1/work/AB74096C/w/A9BC0972/e/blz_nativeref_aot_Debug/obj/Debug/net7.0/wasm/for-publish/dotnet.wasm -o /datadisks/disk1/work/AB74096C/w/A9BC0972/e/blz_nativeref_aot_Debug/obj/Debug/net7.0/wasm/for-publish/dotnet.wasm --detect-features
[] emcc : error : '/datadisks/disk1/work/AB74096C/p/dotnet-workload/packs/Microsoft.NET.Runtime.Emscripten.2.0.23.Sdk.linux-x64/7.0.0-preview.3.22128.1/tools/bin/wasm-emscripten-finalize --minimize-wasm-changes -g --dyncalls-i64 --dwarf /datadisks/disk1/work/AB74096C/w/A9BC0972/e/blz_nativeref_aot_Debug/obj/Debug/net7.0/wasm/for-publish/dotnet.wasm -o /datadisks/disk1/work/AB74096C/w/A9BC0972/e/blz_nativeref_aot_Debug/obj/Debug/net7.0/wasm/for-publish/dotnet.wasm --detect-features' failed (received SIGKILL (-9)) [/datadisks/disk1/work/AB74096C/w/A9BC0972/e/blz_nativeref_aot_Debug/blz_nativeref_aot_Debug.csproj]
```

**Comment by adamsitnik** [comment] 2022-03-21 18:02
Hit again in https://dev.azure.com/dnceng/public/_build/results?buildId=1673482&view=ms.vss-test-web.build-test-results-tab&runId=45919378&resultId=100051&paneView=debug

**Comment by radical** [comment] 2022-03-21 19:14
Closing as a dupe of https://github.com/dotnet/runtime/issues/66725 .

**Closed by radical** 2022-03-21 19:14 UTC
Labels: arch-wasm, untriaged, area-Build-mono, blocking-outerloop, in-pr
