### ISSUE TITLE
Failure to load System.Configuration.ConfigurationManager assembly during dynamic loading of assemblies

### ISSUE THREAD

**Issue by shvez** [dotnet/runtime#627] opened 2019-04-05 10:15 UTC
Hi, there
I've written a small application implementing the idea of dynamic loading and demonstrating the issue. Here is the link: https://www.dropbox.com/s/8nhftd9cy7rhv31/Loader.7z?dl=0

the application provided with binaries, so I hope all you need is open VS and start debugging

**The expected behavior** is being able to load ClientConfigSection from config.

**What get** is an exception notifying that ConfigurationManager assembly cannot be loaded although ConfigurationManager assembly already successfully loaded to context. The exception happens in Application.cs:29 - method 'Run'

What extra information should I provide?
Is this an issue in .netcore code or an issue in my understanding of how it should work?
UPD:
**Envirounment info**
.NET Core SDK (reflecting any global.json):
 Version:   2.2.202
 Commit:    8a7ff6789d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.202\

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

**Comment by ngcdev** [comment] 2019-12-09 15:22
Before I tried to update to 4.7, I noticed (in VS) that when the package System.Configuration.ConfigurationManager gets added, a reference to assembly System.Configuration.dll is also added to the project (which is not part of the package). So that got me thinking, this is something the package assumes the runtime will have.
So I did a quick search for the files and I found it under `NuGetFallbackFolder` for my older SDKs, but not for 3.x:
```
ngcdev@sirius:/usr/share/dotnet/sdk$ ls
2.1.105  2.1.802  2.2.402  3.0.101  3.1.100  NuGetFallbackFolder
ngcdev@sirius:/usr/share/dotnet/sdk$ find . -iname "System.Configuration.*"
./NuGetFallbackFolder/microsoft.netcore.app/2.1.1/ref/netcoreapp2.1/System.Configuration.dll
./NuGetFallbackFolder/microsoft.netcore.app/2.0.6/ref/netcoreapp2.0/System.Configuration.dll
./NuGetFallbackFolder/microsoft.netcore.app/2.1.0/ref/netcoreapp2.1/System.Configuration.dll
./NuGetFallbackFolder/microsoft.netcore.app/2.0.0/ref/netcoreapp2.0/System.Configuration.dll
./NuGetFallbackFolder/microsoft.netcore.app/2.2.0/ref/netcoreapp2.2/System.Configuration.dll
ngcdev@sirius:/usr/share/dotnet/sdk$ 

```
Could it be that 3.x does not include this fallback file?

**Comment by ericstj** [comment] 2019-12-10 18:39
System.Configuration.dll is part of the shared framework, that's the compatibility shim I referred to in https://github.com/dotnet/runtime/issues/627#issuecomment-562655611.  I mentioned System.dll but there is also System.Configuration.dll, mscorlib.dll, System.Xml.dll, etc. 

The reason you don't see this in that folder is that we changed the way we ship the reference assemblies (and runtime packs) in 3.0.  We still have that file and the problem is that it will reference the version of System.Configuration.ConfigurationManager.dll that we shipped with 3.1, so you need to update the package that brings that file into your application.

**Comment by ngcdev** [comment] 2019-12-10 22:51
OK after updating the .Net 4.7 library to use System.Configuration.ConfigurationManager 4.7, now .Net Core 3.1 application is working. So I don't think there's an issue any more.

**Comment by danmosemsft** [comment] 2019-12-11 19:03
OK, I'll close this again. Thanks @ngcdev for the update.

**Closed by danmosemsft** 2019-12-11 19:03 UTC
Labels: area-System.Configuration

**Comment by nmaroine** [comment] 2020-03-11 16:55
the issue is still here even with .net 3.1 and the nuget package with the System.Configuration.ConfigurationManager 4.7 version
