### ISSUE TITLE
Attempting to JIT compile method in System.Text.Json tests on iOS devices

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#58204] opened 2021-08-26 19:00 UTC
When running the System.Text.Json tests on iOS arm64 devices with full AOT we're seeing the following methods where it attempts to JIT compile them, causing an ExecutionEngineException:

```
bool System.Text.Json.Serialization.Converters.IAsyncEnumerableOfTConverter`2<System.Collections.Generic.IAsyncEnumerable`1<int>, int>:OnWriteResume (System.Text.Json.Utf8JsonWriter,System.Collections.Generic.IAsyncEnumerable`1<int>,System.Text.Json.JsonSerializerOptions,System.Text.Json.WriteStack&)
bool System.Text.Json.Serialization.Converters.IAsyncEnumerableOfTConverter`2<System.Text.Json.Serialization.Tests.CollectionTests/MockedAsyncEnumerable`1<int>, int>:OnWriteResume (System.Text.Json.Utf8JsonWriter,System.Text.Json.Serialization.Tests.CollectionTests/MockedAsyncEnumerable`1<int>,System.Text.Json.JsonSerializerOptions,System.Text.Json.WriteStack&)
void System.Text.Json.Serialization.Converters.IDictionaryOfTKeyTValueConverter`3<System.Collections.Concurrent.ConcurrentDictionary`2<int, int>, int, int>:Add (int,int modreq(System.Runtime.InteropServices.InAttribute)&,System.Text.Json.JsonSerializerOptions,System.Text.Json.ReadStack&)
void System.Text.Json.Serialization.Converters.IDictionaryOfTKeyTValueConverter`3<System.Collections.Concurrent.ConcurrentDictionary`2<string, System.Text.Json.Serialization.Tests.StreamTests/ImmutableStructWithStrings>, string, System.Text.Json.Serialization.Tests.StreamTests/ImmutableStructWithStrings>:Add (string,System.Text.Json.Serialization.Tests.StreamTests/ImmutableStructWithStrings modreq(System.Runtime.InteropServices.InAttribute)&,System.Text.Json.JsonSerializerOptions,System.Text.Json.ReadStack&)
void System.Text.Json.Serialization.Converters.IDictionaryOfTKeyTValueConverter`3<System.Collections.Concurrent.ConcurrentDictionary`2<string, int>, string, int>:Add (string,int modreq(System.Runtime.InteropServices.InAttribute)&,System.Text.Json.JsonSerializerOptions,System.Text.Json.ReadStack&)
void System.Text.Json.Serialization.Converters.IDictionaryOfTKeyTValueConverter`3<System.Collections.Concurrent.ConcurrentDictionary`2<string, ulong>, string, ulong>:Add (string,ulong modreq(System.Runtime.InteropServices.InAttribute)&,System.Text.Json.JsonSerializerOptions,System.Text.Json.ReadStack&)
void System.Text.Json.Serialization.Converters.IDictionaryOfTKeyTValueConverter`3<System.Collections.Generic.IDictionary`2<string, System.Nullable`1<System.DateTime>>, string, System.Nullable`1<System.DateTime>>:Add (string,System.Nullable`1<System.DateTime> modreq(System.Runtime.InteropServices.InAttribute)&,System.Text.Json.JsonSerializerOptions,System.Text.Json.ReadStack&)
void System.Text.Json.Serialization.Converters.IDictionaryOfTKeyTValueConverter`3<System.Collections.Generic.IDictionary`2<string, int>, string, int>:Add (string,int modreq(System.Runtime.InteropServices.InAttribute)&,System.Text.Json.JsonSerializerOptions,System.Text.Json.ReadStack&)
void System.Text.Json.Serialization.Converters.IDictionaryOfTKeyTValueConverter`3<System.Text.Json.Serialization.Tests.CollectionTests/DictionaryThatOnlyImplementsIDictionaryOfStringTValue`1<int>, string, int>:Add (string,int modreq(System.Runtime.InteropServices.InAttribute)&,System.Text.Json.JsonSerializerOptions,System.Text.Json.ReadStack&)
void System.Text.Json.Serialization.Converters.IDictionaryOfTKeyTValueConverter`3<System.Text.Json.Serialization.Tests.GenericStructIDictionaryWrapper`2<string, string>, string, string>:Add (string,string modreq(System.Runtime.InteropServices.InAttribute)&,System.Text.Json.JsonSerializerOptions,System.Text.Json.ReadStack&)
void System.Text.Json.Serialization.Converters.IDictionaryOfTKeyTValueConverter`3<System.Text.Json.Serialization.Tests.NullableTests/MyIDictionaryWrapper`1<System.Nullable`1<single>>, string, System.Nullable`1<single>>:Add (string,System.Nullable`1<single> modreq(System.Runtime.InteropServices.InAttribute)&,System.Text.Json.JsonSerializerOptions,System.Text.Json.ReadStack&)
```

It's not clear why these fail, needs to be investigated.

/cc @lambdageek

**Comment by marek-safar** [comment] 2021-08-31 18:18
@SamMonoRT who is working on this?

**Comment by SamMonoRT** [comment] 2021-08-31 18:42
@marek-safar - at the moment no one, but believe @imhameed has a PR up for fullaot and may have seen this error ?

**Comment by imhameed** [comment] 2021-09-01 14:03
I've seen this for several runtime tests https://github.com/dotnet/runtime/issues/57350, but I don't know what the cause or causes are yet.

**Comment by lambdageek** [comment] 2021-09-01 14:44
@imhameed all the STJ tests use `dynamic` in C# in some way or another.  I didn't dig into how we AOT `dynamic` function calls, yet, but it's possible we either don't support it, or we're missing some pattern that the STJ serialization is using.

**Comment by akoeplinger** [comment] 2021-09-01 15:17
@lambdageek no, the issues here are _not_ in tests using `dynamic`. They happen in "normal" System.Text.Json tests.

**Comment by BrzVlad** [comment] 2021-09-10 09:32
I wasn't able to deploy the test app to device. I'll investigate next week once I'm added to Microsoft iOS Development Team

**Comment by akoeplinger** [comment] 2021-09-11 10:24
Yup, the command for that is: `./dotnet.sh build /t:Test /p:TargetOS=iOS /p:TargetArchitecture=arm64 /p:RunAOTCompilation=true /p:DevTeamProvisioning=UBF8T346G9 /p:MonoEnableLLVM=false src/libraries/System.Collections/tests`

(note that we currently have a bug where we don't recognize that we ILStripped the binaries so if you run this a second time it'll try to AOT the stripped binaries which will fail, probably best to just comment out the `<ILStrip />` in tests.mobile.targets)

**Comment by SamMonoRT** [comment] 2021-09-15 15:16
Moving to 7.0 based on above comments.

**Comment by lambdageek** [comment] 2021-09-17 02:55
@vargaz Does #59182 seem risky overall?

@SamMonoRT @akoeplinger @layomia Are the testcases here something contrived or possibly something that real users could run into?  (@layomia it's the ones from https://github.com/dotnet/runtime/pull/58276)

**Comment by vargaz** [comment] 2021-09-17 03:29
It's somewhat risky, if this is needed for 6.0, we can create a version where the new code is ifdef ios|android, and the old code is used on wasm.

**Comment by lambdageek** [comment] 2021-09-17 16:44
> It's somewhat risky, if this is needed for 6.0, we can create a version where the new code is ifdef ios|android, and the old code is used on wasm.

I think we should hold off unless we get some customer reports that this is a problem in practice.

**Closed** 2021-09-17 19:29 UTC
Labels: disabled-test, area-Codegen-AOT-mono, in pr
