### ISSUE TITLE
System.IO.FileLoadException: Undefined resource string ID:0x80131621

### ISSUE THREAD

**Issue by Zhiyuan-Amos** [dotnet/runtime#101581] opened 2024-04-26 00:24 UTC
### Description

Observe that `client.GetAsync` errors out with the following error message: `System.IO.FileLoadException: Undefined resource string ID:0x80131621`. This issue only occurs when **both conditions are true**:

1. Using a `HttpClient` created with a custom `HttpClientHandler` overriding `SendAsync` (even though the overriding method merely calls the base method and so it should technically be equivalent to not overriding the method).

2. Specifying `<InternalsVisibleTo>` in the `.csproj` file, where the `Include` property has a value with at least 1 `/` e.g. `../ProjectMoreThanOnePathAway`.

### Reproduction Steps

```cs
// Program.cs
var client = new HttpClient(new CustomHttpClientHandler());
await client.GetAsync("https://www.google.com");

class CustomHttpClientHandler : HttpClientHandler
{
    protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) 
        => base.SendAsync(request, cancellationToken);
}

// .csproj
<InternalsVisibleTo Include="../ProjectMoreThanOnePathAway" />
```

I've created a minimal codebase to reproduce this issue: https://github.com/Zhiyuan-Amos/FileNotFoundError

### Expected behavior

HTTP Request completes successfully.

### Actual behavior

Http Request errors out with `System.IO.FileLoadException: Undefined resource string ID:0x80131621`.

### Regression?

This error did not occur in .NET 6.

### Known Workarounds

Make the Program class public using a partial class declaration (see [dn for Integration Tests](https://learn.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-8.0#basic-tests-with-the-default-webapplicationfactory)).

### Configuration

.NET Version: 8
OS & Architecture: MacOS M1, Linux x64

**Comment by ManickaP** [comment] 2024-05-21 12:41
I just re-tested this and confirmed this repros on .NET8. But it doesn't on .NET 9. I don't know the root cause of this nor what might have fixed it (or even if it's S.N.Http specific or general problem with resource strings). Either way, **this doesn't repro on .NET 9 so I'll close this. **

Note that given the rare case here, even if we knew exactly what's going on, it's highly unlikely we'd backport it to 8.0.

**Closed by ManickaP** 2024-05-21 12:41 UTC
Labels: area-System.Net.Http, untriaged
