### ISSUE TITLE
CollectionsMarshal AsSpan

### ISSUE THREAD

**Issue by SoftStoneDevelop** [dotnet/runtime#88845] opened 2023-07-13 16:17 UTC
Why AsSpan use `list._size` as length?
```C#

public static Span<T> AsSpan<T>(List<T>? list)
            => list is null ? default : new Span<T>(list._items, 0, list._size);

```

I expect:
```C#

public static Span<T> AsSpan<T>(List<T>? list)
            => list is null ? default : new Span<T>(list._items, 0, list._items.Length);

```

Now I can not filling collection like that:
```C#

var list = new List<int>(20);
//list._size equal 0
//list._items.Length equal 20
var listSpan = CollectionsMarshal.AsSpan(list);

for(int i = 0; i < 20; i++)
{
    listSpan[i] = i;//throw error because span created with length equal 0(list._size)
}

```

**Comment by SoftStoneDevelop** [comment] 2023-07-13 16:20
Or can add a parameter

```C#

public static Span<T> AsSpan<T>(List<T>? list, bool useLength = false)
            => list is null ? default : new Span<T>(list._items, 0, useLength ? list._items.Length : list._size);

```

**Comment by eiriktsarpalis** [comment] 2023-07-13 17:04
I would say this is a duplicate of https://github.com/dotnet/runtime/issues/55217. Starting with .NET 8 it should be possible to use the `CollectionsMarshal.SetCount` method to change the count of a list before any of its elements have been initialized. Calling `AsSpan` after that should give you back a buffer of the desired size.

**Closed** 2023-07-13 17:44 UTC
Labels: area-System.Collections, untriaged
