### ISSUE TITLE
.NET 6.0.1 coreclr.dll symbols unavailable

### ISSUE THREAD

**Issue by HighPerfDotNet** [dotnet/runtime#62998] opened 2021-12-19 19:28 UTC
### Description

Trying to us Intel VTune on some app and run into lack of symbols on server: specifically .NET 6.0.1 coreclr.dll doesn't have its symbol file available on the Microsoft Symbol Server, as well as a bunch of other DLLs (see attached [pdb.txt](https://github.com/dotnet/runtime/files/7741411/pdb.txt)). 

Looks like something like this happened in the past: https://github.com/dotnet/runtime/issues/52717

### Reproduction Steps

symchk.exe coreclr.dll /s SRV*output*http://msdl.microsoft.com/download/symbols

Result -

SYMCHK: coreclr.dll          FAILED  - coreclr.pdb mismatched or not found                                                                                  SYMCHK: FAILED files = 1
SYMCHK: PASSED + IGNORED files = 0            

Check all DLLs (for attached file):

symchk.exe /r *.dll /s SRV*output*http://msdl.microsoft.com/download/symbols                       

### Expected behavior

Getting PDB symbols from server and having one hell of a time debugging weekend in VTune

### Actual behavior

No symbols :(

### Configuration

Current Windows 10, .NET 6.0.1 with current Visual Studio 2022 and current Intel VTune 2022

**Comment by pgrawehr** [comment] 2021-12-19 19:36
Possible duplicate of #62955

**Comment by HighPerfDotNet** [comment] 2021-12-19 19:40
It does look like it, but also I've tried it on older releases like 6.0.0 and also getting missing symbols - 

SYMCHK: FAILED files = 123
SYMCHK: PASSED + IGNORED files = 96

So, this probably affects more than the most recent release

**Comment by pgrawehr** [comment] 2021-12-19 19:43
Uh, that sounds bad. Can you add your info to the other ticket, so there's only one?

**Comment by HighPerfDotNet** [comment] 2021-12-19 19:47
Done, thanks and glad I am not the only one who cares about these!

**Comment by tommcdon** [comment] 2021-12-30 20:19
Thanks for the feedback!  We've passed this feedback on to our infrastructure team who is investigating.

**Comment by tommcdon** [comment] 2022-01-12 04:46
@hoyosjs was this issue fixed recently and if so can it be closed?

**Comment by hoyosjs** [comment] 2022-01-12 14:12
The one for 6.0, i reindexed runtime and that why it shows partial availability only. For 6.0.1 and going forward we should see the symbol indexes with no issues.

**Closed by hoyosjs** 2022-01-12 14:12 UTC
Labels: area-Diagnostics-coreclr, area-Infrastructure-coreclr
