### ISSUE TITLE
DateTime AddUnits & TimeSpan IntervalFromDoubleTicks rounding issues

### ISSUE THREAD

**Issue by oe06** [dotnet/runtime#107092] opened 2024-08-28 15:15 UTC
### Description

Since NET7/8 all methods AddHours/AddMiniutes/... using AddUnits have floating round issue
in NET6 the DateTime Add implementation does a rounding using
double millis_double = value * scale + (value >= 0 ? 0.5 : -0.5);

when you convert a double to a long you should apply a rounding operation to avoid precision error

### Reproduction Steps

Console.WriteLine(new DateTime(2004,2,1,11,6,7).AddHours(1.2).Ticks);

### Expected behavior

ticks = 632112346870000000

### Actual behavior

ticks = 632112346869999999

### Regression?

Yes a regression comparing NET6

### Known Workarounds

[MethodImpl(MethodImplOptions.AggressiveInlining)]
private DateTime AddUnits(double value, long maxUnitCount, long ticksPerUnit)
{
    if (Math.Abs(value) > maxUnitCount)
    {
        ThrowAddOutOfRange();
    }

    double integralPart = Math.Truncate(value);
    double fractionalPart = value - integralPart;
    long ticks = (long)(integralPart) * ticksPerUnit;
    **ticks += (long)Math.Round(fractionalPart * ticksPerUnit);**

    return AddTicks(ticks);
}

private static TimeSpan IntervalFromDoubleTicks(double ticks)
{
    if ((ticks > long.MaxValue) || (ticks < long.MinValue) || double.IsNaN(ticks))
        ThrowHelper.ThrowOverflowException_TimeSpanTooLong();
    if (ticks == long.MaxValue)
        return MaxValue;
    **return new TimeSpan((long)Math.Round(ticks));**
}

### Configuration

NET8
Windows 11
x64

**Comment by tannergooding** [comment] 2024-08-28 16:48
>  have floating round issue

There is no issue here, actually. The code is actually now more correct than it was before.

The issue is that you've written the following code and then made an assumption that precisely `1.2` hours are being added:
```csharp
Console.WriteLine(new DateTime(2004,2,1,11,6,7).AddHours(1.2).Ticks);
```

However, `float` and `double` are `binary-based floating-point types` which follow the IEEE 754 standard. This means that they can only represent values that are in range and multiples of a power of 2. Since `1.2` isn't such a value, it instead becomes the nearest representable value which is `1.1999999999999999555910790149937383830547332763671875`.

So, you're not adding `1.2 hours` (which would be `4320 seconds` or `43_200_000_000 ticks`), instead you're adding approximately `43_199_999_999 ticks` instead.

-------------------

Now, there is some things that could be improved here, such as explicitly handling some values to ensure they round up instead of down. That would fix this particular case, but would inversely break other cases.

The "right" thing instead is for users to only add whole integer based amounts which will ensure that you get exact results, for example:
```csharp
Console.WriteLine(new DateTime(2004,2,1,11,6,7).AddHours(1).AddMinutes(12).Ticks);
Console.WriteLine(new DateTime(2004,2,1,11,6,7).AddMinutes(72).Ticks);
Console.WriteLine(new DateTime(2004,2,1,11,6,7).AddSeconds(4320).Ticks);
```

.NET 9 also has new overloads that take integers and which take the individual subcomponents which can allow for significantly faster computation as well:
```csharp
Console.WriteLine(new DateTime(2004,2,1,11,6,7).Add(TimeSpan.FromHours(1, minutes: 12)).Ticks);
```

**Comment by tarekgh** [comment] 2024-08-28 16:57
Closing it per @tannergooding reply.

**Closed by tarekgh** 2024-08-28 16:57 UTC
Labels: area-System.DateTime

**Comment by oe06** [comment] 2024-08-29 07:31
"So, you're not adding 1.2 hours (which would be 4320 seconds or 43_200_000_000 ticks), instead you're adding approximately 43_199_999_999 ticks instead."

Following the current code at line (898 of dateTime.cs) ticks += (long)(fractionalPart * ticksPerUnit);
(fractionalPart * ticksPerUnit)=719_999_999.999999 according to the IEEE 754 standard representation 
but you casting it directly as a long (without a correct rounding) so in this cast (long) 719_999_999.999999 gives 719_999_999
if you apply Math.Round(fractionalPart * ticksPerUnit) it gives (a "more" correct mathematic representation value) 720_000_000

What I'm trying to tell you is that the problems detected are problems of conversion from real to integer which are done without mathematically correct rounding.

**Comment by tannergooding** [comment] 2024-08-29 11:34
Responded on the newly opened issue: https://github.com/dotnet/runtime/issues/107129
