### ISSUE TITLE
FileConfigurationProvider throws FileNotFoundException without filename

### ISSUE THREAD

**Issue by mazzus** [dotnet/runtime#42337] opened 2020-07-30 11:06 UTC
When a file is not found during loading of configuration it would be helpful if the exception included the filename of the missing file.

It looks like it would be very simple to pass the `Source.Path` to the *FileNotFoundException's* constructor.

The line in question is this:
https://github.com/dotnet/extensions/blob/be18161fbed286d6fb7a7b1c7999ce70a50cf3eb/src/Configuration/Config.FileExtensions/src/FileConfigurationProvider.cs#L72

Rest of the function as reference:
https://github.com/dotnet/extensions/blob/be18161fbed286d6fb7a7b1c7999ce70a50cf3eb/src/Configuration/Config.FileExtensions/src/FileConfigurationProvider.cs#L56-L96

**Comment by ericstj** [comment] 2020-09-18 16:27
This is a duplicate of #36007

**Closed by ericstj** 2020-09-18 16:27 UTC
Labels: area-Extensions-Configuration, enhancement
