### ISSUE TITLE
Postinstall script fails on osx-arm64

### ISSUE THREAD

**Issue by mateoatr** [dotnet/runtime#59581] opened 2021-09-24 17:24 UTC
Installing the latest rc2 installer for macOS arm64 fails with the following:
```shell
~ sudo installer -pkg dotnet-sdk-osx-arm64-rc2.pkg -target /
installer: Package name is Microsoft .NET SDK 6.0.100-rc.2.21474.4 (arm64)
installer: Upgrading at base path /
installer: The upgrade failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “dotnet-sdk-osx-arm64-rc2.pkg”.)
```

Installer logs:
```shell
2021-09-24 10:04:37-07 DNCENGDEV-02 installd[345]: PackageKit: ----- Begin install -----
2021-09-24 10:04:37-07 DNCENGDEV-02 installd[345]: PackageKit: request=PKInstallRequest <7 packages, destination=/>
2021-09-24 10:04:37-07 DNCENGDEV-02 installd[345]: PackageKit: packages=(
	    "PKLeopardPackage <id=com.microsoft.dotnet.pack.targeting.6.0.0-rc.2.21470.23.component.osx.arm64, version=6.0.0-rc.2.21470.23, url=file://localhost/Users/dotnet-dev/matorre/Downloads/dotnet-sdk-osx-arm64-rc2.pkg#com.microsoft.dotnet.pack.targeting.6.0.0-rc.2.21470.23.component.osx.arm64.pkg>",
	    "PKLeopardPackage <id=com.microsoft.netstandard.pack.targeting.2.1.0.component.osx.x64, version=2.1.0, url=file://localhost/Users/dotnet-dev/matorre/Downloads/dotnet-sdk-osx-arm64-rc2.pkg#com.microsoft.standard.pack.targeting.2.1.0.component.osx.arm64.pkg>",
	    "PKLeopardPackage <id=com.microsoft.dotnet.pack.apphost.6.0.0-rc.2.21470.23.component.osx.arm64, version=6.0.0-rc.2.21470.23, url=file://localhost/Users/dotnet-dev/matorre/Downloads/dotnet-sdk-osx-arm64-rc2.pkg#com.microsoft.dotnet.pack.apphost.6.0.0-rc.2.21470.23.component.osx.arm64.pkg>",
	    "PKLeopardPackage <id=com.microsoft.dotnet.sharedframework.Microsoft.NETCore.App.6.0.0-rc.2.21470.23.component.osx.arm64, version=6.0.0-rc.2.21470.23, url=file://localhost/Users/dotnet-dev/matorre/Downloads/dotnet-sdk-osx-arm64-rc2.pkg#com.microsoft.dotnet.sharedframework.Microsoft.NETCore.App..component.osx.arm64.pkg>",
	    "PKLeopardPackage <id=com.microsoft.dotnet.hostfxr.6.0.0-rc.2.21470.23.component.osx.arm64, version=6.0.0-rc.2.21470.23, url=file://localhost/Users/dotnet-dev/matorre/Downloads/dotnet-sdk-osx-arm64-rc2.pkg#com.microsoft.dotnet.hostfxr.6.0.0-rc.2.21470.23.component.osx.arm64.pkg>",
	    "PKLeopardPackage <id=com.microsoft.dotnet.sharedhost.component.osx.arm64, version=6.0.0-rc.2.21470.23, url=file://localhost/Users/dotnet-dev/matorre/Downloads/dotnet-sdk-osx-arm64-rc2.pkg#com.microsoft.dotnet.sharedhost.6.0.0-rc.2.21470.23.component.osx.arm64.pkg>",
	    "PKLeopardPackage <id=com.microsoft.dotnet.dev.6.0.100-rc.2.21474.4.component.osx.arm64, version=6.0.100-rc.2.21474.4, url=file://localhost/Users/dotnet-dev/matorre/Downloads/dotnet-sdk-osx-arm64-rc2.pkg#com.microsoft.dotnet.dev.6.0.100-rc.2.21474.4.component.osx.arm64.pkg>"
	)
2021-09-24 10:04:37-07 DNCENGDEV-02 installd[345]: PackageKit: Set reponsibility for install to 1106
2021-09-24 10:04:37-07 DNCENGDEV-02 installd[345]: PackageKit: Will do receipt-based obsoleting for package identifier com.microsoft.netstandard.pack.targeting.2.1.0.component.osx.x64 (prefix path=usr/local/share/dotnet)
2021-09-24 10:04:38-07 DNCENGDEV-02 installd[345]: PackageKit: Extracting file://localhost/Users/dotnet-dev/matorre/Downloads/dotnet-sdk-osx-arm64-rc2.pkg#com.microsoft.dotnet.pack.targeting.6.0.0-rc.2.21470.23.component.osx.arm64.pkg (destination=/Library/InstallerSandboxes/.PKInstallSandboxManager/F40E81AF-B38D-4443-92A0-28949769EE3A.activeSandbox/Root/usr/local/share/dotnet, uid=0)
2021-09-24 10:04:38-07 DNCENGDEV-02 installd[345]: PackageKit: Extracting file://localhost/Users/dotnet-dev/matorre/Downloads/dotnet-sdk-osx-arm64-rc2.pkg#com.microsoft.standard.pack.targeting.2.1.0.component.osx.arm64.pkg (destination=/Library/InstallerSandboxes/.PKInstallSandboxManager/F40E81AF-B38D-4443-92A0-28949769EE3A.activeSandbox/Root/usr/local/share/dotnet, uid=0)
2021-09-24 10:04:38-07 DNCENGDEV-02 installd[345]: PackageKit: Extracting file://localhost/Users/dotnet-dev/matorre/Downloads/dotnet-sdk-osx-arm64-rc2.pkg#com.microsoft.dotnet.pack.apphost.6.0.0-rc.2.21470.23.component.osx.arm64.pkg (destination=/Library/InstallerSandboxes/.PKInstallSandboxManager/F40E81AF-B38D-4443-92A0-28949769EE3A.activeSandbox/Root/usr/local/share/dotnet, uid=0)
2021-09-24 10:04:38-07 DNCENGDEV-02 installd[345]: PackageKit: Extracting file://localhost/Users/dotnet-dev/matorre/Downloads/dotnet-sdk-osx-arm64-rc2.pkg#com.microsoft.dotnet.sharedframework.Microsoft.NETCore.App..component.osx.arm64.pkg (destination=/Library/InstallerSandboxes/.PKInstallSandboxManager/F40E81AF-B38D-4443-92A0-28949769EE3A.activeSandbox/Root/usr/local/share/dotnet, uid=0)
2021-09-24 10:04:38-07 DNCENGDEV-02 installd[345]: PackageKit: Extracting file://localhost/Users/dotnet-dev/matorre/Downloads/dotnet-sdk-osx-arm64-rc2.pkg#com.microsoft.dotnet.hostfxr.6.0.0-rc.2.21470.23.component.osx.arm64.pkg (destination=/Library/InstallerSandboxes/.PKInstallSandboxManager/F40E81AF-B38D-4443-92A0-28949769EE3A.activeSandbox/Root/usr/local/share/dotnet, uid=0)
2021-09-24 10:04:38-07 DNCENGDEV-02 installd[345]: PackageKit: Extracting file://localhost/Users/dotnet-dev/matorre/Downloads/dotnet-sdk-osx-arm64-rc2.pkg#com.microsoft.dotnet.sharedhost.6.0.0-rc.2.21470.23.component.osx.arm64.pkg (destination=/Library/InstallerSandboxes/.PKInstallSandboxManager/F40E81AF-B38D-4443-92A0-28949769EE3A.activeSandbox/Root/usr/local/share/dotnet, uid=0)
2021-09-24 10:04:38-07 DNCENGDEV-02 installd[345]: PackageKit: Extracting file://localhost/Users/dotnet-dev/matorre/Downloads/dotnet-sdk-osx-arm64-rc2.pkg#com.microsoft.dotnet.dev.6.0.100-rc.2.21474.4.component.osx.arm64.pkg (destination=/Library/InstallerSandboxes/.PKInstallSandboxManager/F40E81AF-B38D-4443-92A0-28949769EE3A.activeSandbox/Root/usr/local/share/dotnet, uid=0)
2021-09-24 10:04:40-07 DNCENGDEV-02 installd[345]: PackageKit: prevent user idle system sleep
2021-09-24 10:04:40-07 DNCENGDEV-02 installd[345]: PackageKit: suspending backupd
2021-09-24 10:04:40-07 DNCENGDEV-02 installd[345]: PackageKit: Using trashcan path /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/PKInstallSandboxTrash/F40E81AF-B38D-4443-92A0-28949769EE3A.sandboxTrash for sandbox /Library/InstallerSandboxes/.PKInstallSandboxManager/F40E81AF-B38D-4443-92A0-28949769EE3A.activeSandbox
2021-09-24 10:04:40-07 DNCENGDEV-02 install_monitor[1433]: Temporarily excluding: /Applications, /Library, /System, /bin, /private, /sbin, /usr
2021-09-24 10:04:40-07 DNCENGDEV-02 installd[345]: PackageKit: Shoving /Library/InstallerSandboxes/.PKInstallSandboxManager/F40E81AF-B38D-4443-92A0-28949769EE3A.activeSandbox/Root (1 items) to /
2021-09-24 10:04:40-07 DNCENGDEV-02 installd[345]: PackageKit (package_script_service): Preparing to execute script "./postinstall" in /private/tmp/PKInstallSandbox.4800RX/Scripts/com.microsoft.dotnet.sharedhost.component.osx.arm64.k0G7Oz
2021-09-24 10:04:40-07 DNCENGDEV-02 package_script_service[349]: PackageKit: Executing script "postinstall" in /tmp/PKInstallSandbox.4800RX/Scripts/com.microsoft.dotnet.sharedhost.component.osx.arm64.k0G7Oz
2021-09-24 10:04:40-07 DNCENGDEV-02 package_script_service[349]: Set responsibility to pid: 1106, responsible_path: /usr/libexec/sshd-keygen-wrapper
2021-09-24 10:04:40-07 DNCENGDEV-02 package_script_service[349]: PackageKit: *** launch path not accessible
2021-09-24 10:04:40-07 DNCENGDEV-02 package_script_service[349]: PackageKit: Failed task attributes: {
	    NSFileCreationDate = "2021-09-21 04:10:49 +0000";
	    NSFileExtensionHidden = 0;
	    NSFileGroupOwnerAccountID = 0;
	    NSFileGroupOwnerAccountName = wheel;
	    NSFileHFSCreatorCode = 0;
	    NSFileHFSTypeCode = 0;
	    NSFileModificationDate = "2021-09-21 04:10:49 +0000";
	    NSFileOwnerAccountID = 0;
	    NSFileOwnerAccountName = root;
	    NSFilePosixPermissions = 420;
	    NSFileProtectionKey = NSFileProtectionCompleteUntilFirstUserAuthentication;
	    NSFileReferenceCount = 1;
	    NSFileSize = 854;
	    NSFileSystemFileNumber = 25844066;
	    NSFileSystemNumber = 16777232;
	    NSFileType = NSFileTypeRegular;
	}
2021-09-24 10:04:40-07 DNCENGDEV-02 package_script_service[349]: Responsibility set back to self.
2021-09-24 10:04:40-07 DNCENGDEV-02 install_monitor[1433]: Re-included: /Applications, /Library, /System, /bin, /private, /sbin, /usr
2021-09-24 10:04:41-07 DNCENGDEV-02 installd[345]: PackageKit: releasing backupd
2021-09-24 10:04:41-07 DNCENGDEV-02 installd[345]: PackageKit: allow user idle system sleep
2021-09-24 10:04:41-07 DNCENGDEV-02 installd[345]: PackageKit: Cleared responsibility for install from 1432.
2021-09-24 10:04:41-07 DNCENGDEV-02 installd[345]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “dotnet-sdk-osx-arm64-rc2.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Users/dotnet-dev/matorre/Downloads/dotnet-sdk-osx-arm64-rc2.pkg#com.microsoft.dotnet.sharedhost.6.0.0-rc.2.21470.23.component.osx.arm64.pkg, PKInstallPackageIdentifier=com.microsoft.dotnet.sharedhost.component.osx.arm64, NSLocalizedDescription=An error occurred while running scripts from the package “dotnet-sdk-osx-arm64-rc2.pkg”.} {
	    NSFilePath = "./postinstall";
	    NSLocalizedDescription = "An error occurred while running scripts from the package \U201cdotnet-sdk-osx-arm64-rc2.pkg\U201d.";
	    NSURL = "file://localhost/Users/dotnet-dev/matorre/Downloads/dotnet-sdk-osx-arm64-rc2.pkg#com.microsoft.dotnet.sharedhost.6.0.0-rc.2.21470.23.component.osx.arm64.pkg";
	    PKInstallPackageIdentifier = "com.microsoft.dotnet.sharedhost.component.osx.arm64";
	}
2021-09-24 10:04:41-07 DNCENGDEV-02 installd[345]: PackageKit: Running idle tasks
2021-09-24 10:04:41-07 DNCENGDEV-02 installer[1432]: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “dotnet-sdk-osx-arm64-rc2.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Users/dotnet-dev/matorre/Downloads/dotnet-sdk-osx-arm64-rc2.pkg#com.microsoft.dotnet.sharedhost.6.0.0-rc.2.21470.23.component.osx.arm64.pkg, PKInstallPackageIdentifier=com.microsoft.dotnet.sharedhost.component.osx.arm64, NSLocalizedDescription=An error occurred while running scripts from the package “dotnet-sdk-osx-arm64-rc2.pkg”.}
2021-09-24 10:04:41-07 DNCENGDEV-02 installd[345]: PackageKit: Removing client PKInstallDaemonClient pid=1432, uid=0 (/usr/sbin/installer)
2021-09-24 10:04:41-07 DNCENGDEV-02 installd[345]: PackageKit: Done with sandbox removals
2021-09-24 10:04:41-07 DNCENGDEV-02 installer[1432]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
```

@vitek-karas @ericstj

**Comment by jkoritzinsky** [comment] 2021-09-24 17:29
cc: @ericstj

**Comment by ericstj** [comment] 2021-09-24 17:37
Duplicate of https://github.com/dotnet/installer/issues/12094.  Also mentioned to folks in email that went out this morning.

Fix is in both main and RC2 runtime branches.  I'll update the linked issue when the fix reaches installer.

**Closed by ericstj** 2021-09-24 17:37 UTC
Labels: area-Infrastructure-installer, untriaged
