### ISSUE TITLE
SYSLIB1045 The code fix removes all curly braces on single line if statements in the file

### ISSUE THREAD

**Issue by wilfriedb** [dotnet/runtime#87762] opened 2023-06-19 08:28 UTC
### Description

The "SYSLIB1045  Convert to 'GeneratedRegexAttribute'." code fixer removes curly braces elsewhere in the file on single line `if` statements.

Example:
```csharp
if (foo)
{
    DoSomething();
}
```
becomes:
```csharp
if (foo)
    DoSomething();
```

### Reproduction Steps

Take a code file with a Regex and a single line if statement:
```csharp
if (foo)
{
    DoSomething();
}
```
somewhere in the file (doesn't need to be nearby the Regex) find a `new Regex(/* regex string */)` line
Press CTRL-. somewhere on the `Regex` text.
Select Convert to 'GeneratedRegexAttribute'.

Mutliple things happens:

- The class becomes `partial`. (expected)
- A partial method with a `GeneratedRegex` attribute will be created. (expected)
- The Regex will be replaced with the method. (expected)
- All curly braces on all single line `if` statements will be removed. (NOT expected)

Note: multiple line `if` statements are unaffected.

### Expected behavior

The expected behavior is that on unrelated lines of code the curly braces stay in place.

### Actual behavior

The lines:
```csharp
if (foo)
{
    DoSomething();
}
```
becomes:
```csharp
if (foo)
    DoSomething();
```

### Regression?

Probably not, because this is a new diagnostic in NET 7.

### Known Workarounds

The work around is either leave the braces removed (and get new messages like "add curly braces"), or put the braces back manually.

### Configuration

Which version of .NET is the code running on?
NET 7
What OS and version, and what distro if applicable?
Windows 11 Enterprise 21H1
What is the architecture (x64, x86, ARM, ARM64)?
x64
Do you know whether it is specific to that configuration?
If you're using Blazor, which web browser(s) do you see this issue in?
n/a

**Comment by stephentoub** [comment] 2023-06-20 02:56
This looks like a duplicate of https://github.com/dotnet/runtime/issues/79892 that was fixed for .NET 8 in https://github.com/dotnet/runtime/pull/80126.  Thanks.

**Closed by stephentoub** 2023-06-20 02:56 UTC
Labels: area-System.Text.RegularExpressions, untriaged
