### ISSUE TITLE
Support OnXXX methods/attributes for System.Text.Json

### ISSUE THREAD

**Issue by StevenRasmussen** [dotnet/runtime#39896] opened 2020-07-24 14:19 UTC
I saw issue #29177 which is currently closed.  However, it talks about both converts and the `OnXXX` methods but only converters has been implemented. I was really hoping this was on the roadmap for completion in the .Net 5 timeframe but don't see a separate ticket for this so I apologize if there is another ticket already open for this.

Writing a custom converter for every type for which you want to be able to provide `OnXXX` methods is quite a pain.  Being able to create a base class with these methods and then being able to override them in inheriting classes has been my pattern which works quite well with Newtonsoft.Json.

**Comment by layomia** [comment] 2020-07-27 18:15
We won't get to this in 5.0, but it can be considered in the next release. See the [JSON docs](https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to#callbacks) for an example workaround for these callbacks.

**Comment by layomia** [comment] 2021-06-28 16:57
@steveharter is this issue a duplicate of https://github.com/dotnet/runtime/issues/54528?

**Comment by steveharter** [comment] 2021-07-02 14:50
@steveharter is this issue a duplicate of #54528?

Yes. Since this issue didn't propose an API I created the API issue instead.

**Closed by steveharter** 2021-07-02 14:50 UTC
Labels: api-suggestion, area-System.Text.Json
