### ISSUE TITLE
I am using smtp client for for receiving email from contact page but sender email is coming as receiver email

### ISSUE THREAD

**Issue by Muhammad2819** [dotnet/runtime#43352] opened 2020-10-13 06:35 UTC
```c#
MailAddress from = new MailAddress(email, name_arbic);
MailAddress to = new MailAddress("nouman2819@gmail.com");
MailMessage Msg = new MailMessage(from,to);
Msg.Body = sb.ToString();
Msg.Subject = "New Partner";
// SMTP server IP.
SmtpClient smtp = new SmtpClient("smtp.gmail.com", 587);
smtp.EnableSsl = true;
smtp.UseDefaultCredentials = false;
smtp.Credentials = new System.Net.NetworkCredential("nouman2819@gmail.com", "my password");
```

1)Now when I send email to nouman2819@gmail.com the sender is coming my email instead of email(get email from contact)
what is the issue here please have a look and let me know
  2)And when I use credentials and receiver email other than gmail its not sending "Showing server authentication" issue e.g I am using nouman@eatxact.com for reciever and using this email credentials that is not working plz help me to sort this out.

**Comment by Muhammad2819** [comment] 2020-10-13 13:38
> SmtpClient is [obsolete](https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient?view=netcore-3.1). You shouldn't be using it at all, because it doesn't support modern authentication methods. Please, use another mail library.

Could you please suggest me another mail library which is fulfill  the requirements of sending and receiving mails correctly

**Comment by samsosa** [comment] 2020-10-14 00:18
The incomparably good MailKit from [Jeffrey Stedfast](https://github.com/jstedfast) is the best choice:

### MailKit: **[https://github.com/jstedfast/MailKit](https://github.com/jstedfast/MailKit)**

Also available as Nugget!

**Comment by wfurt** [comment] 2020-11-11 19:52
Did you get it working @Muhammad2819? 

In case you need to debug this, good way is to look at received message source. Also not that there are two places where To/From is used and they may or may not be same. Typically To/From from the MailMessage is what mail clients would show. Then there is the SMTP information and possibly authentication. It is possible gmail does something to limit spoofing.

**Comment by karelz** [comment] 2020-11-12 16:53
Triage: We should at minimum understand why gmail does not work? Is it lack of protocol support on our side? If it is, we should consider addressing it.

**Comment by karelz** [comment] 2021-05-06 18:43
Triage: I've tried it and was able to send email via Hotmail. Gmail failed with "unable to Authenticate" -- apparently it does not work even for other clients, not just .NET Core. Looks like some extra security in gmail.

BTW: Using different `From` than the one you're logged on does not work even for Hotmail and I think it is by design.

Closing as nothing is left for us to do here.

**Closed by karelz** 2021-05-06 18:43 UTC
Labels: area-System.Net, question
