### ISSUE TITLE
`ReflectionTypeLoadException.ToString()` is as useful as a chocolate tea pot

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#53907] opened 2021-06-08 23:45 UTC
Yesterday I had to troubleshoot an issue in the WinForms designer. VS helpfully wrote a log file where it included the `ToString()` of the unhandled exception, which I would consider sensible behavior for anyone logging unhandled errors (text below).

In this case, the unhandled error happened to be `ReflectionTypeLoadException` whose `ToString()` doesn't include the actual errors, which are stored in the `ReflectionTypeLoadException.LoaderExceptions` property.

It seems we should include that information so that logged errors are easier to troubleshoot (or at least include the first N items).

<details>
<summary>Example of someone logging `ReflectionTypeLoadException`</summary>

```text
Error Information
AppInsightsEvent Name = vs/winforms/designer/create-designsurface-failure
          Description = Exception
     TelemetrySession = 'c378a8ba-87aa-471b-b2db-16e5962d3256' Started = True OptIn=True IsInitialized = True Cloned = False
      WatsonEventType = VisualStudioNonFatalErrors2
             UTC time = 2021-06-08T04:14:20

Exception:
System.Reflection.ReflectionTypeLoadException
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
System.Reflection.RuntimeAssembly.get_DefinedTypes()
System.Composition.Hosting.ContainerConfiguration.<>c.<WithAssemblies>b__16_0(Assembly a)
System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
System.Composition.Hosting.ContainerConfiguration.CreateContainer()
Microsoft.DotNet.DesignTools.Client.ClientProtocolContext.CreateCompositionHost(ILoggerFactory loggerFactory, IEnumerable`1 designTimeAssemblies, IEnumerable`1 additionalMefExportProviders)
Microsoft.DotNet.DesignTools.Client.Host.ServerHostFactory.<CreateHostAsync>d__8.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.VisualStudio.WinForms.DesignToolsService.<GetOrCreateClientAsync>d__17.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
Microsoft.VisualStudio.WinForms.WinFormsDesignSurfaceFactory.CreateRemoteDesignSurface(IServiceProvider provider)
```

</details>

**Comment by jkotas** [comment] 2021-06-08 23:48
Was this on .NET Framework?

This looks like duplicate of https://github.com/dotnet/runtime/issues/24452 . Fixed in .NET Core 2.1.

**Comment by terrajobst** [comment] 2021-06-08 23:51
Huh. I *assumed* it was on .NET Core as this happened in the designer process and Fusion Log Viewer showed no activity. Well, if we fixed that in .NET Core then it must have been on the .NET Framework side of the house.

**Closed** 2021-06-08 23:52 UTC
Labels: area-System.Reflection, enhancement, untriaged
