### ISSUE TITLE
Suspicious debug info generated for ready to run images

### ISSUE THREAD

**Issue by cshung** [dotnet/runtime#1986] opened 2020-01-22 00:22 UTC
I have discovered some suspicious properties in the debug info generated for ready to run code. They might not be wrong, but it is suspicious enough to worth some investigation.

## Case 1: Identical entries:
```
	Native Offset: 0xA, IL Offset: 0x0, Source Types: StackEmpty
	Native Offset: 0xA, IL Offset: 0x0, Source Types: StackEmpty, CallInstruction
```
The only difference is the source type, not sure what does that mean.

## Case 2: Identical native offset mapping to distinct IL offsets:
```
	Native Offset: 0x17FE, IL Offset: 0x84F, Source Types: SourceTypeInvalid
	Native Offset: 0x17FE, IL Offset: 0x850, Source Types: CallInstruction
```

## Case 3: Identical IL offset mapping to distinct native offsets:
```
	Native Offset: 0x180B, IL Offset: 0x855, Source Types: SourceTypeInvalid
	Native Offset: 0x181B, IL Offset: 0x855, Source Types: CallInstruction
```

## Case 4: Increasing native offset leading to decreasing IL offsets:
```
	Native Offset: 0x4C, IL Offset: 0x55, Source Types: StackEmpty
	Native Offset: 0x50, IL Offset: 0x41, Source Types: StackEmpty
```

Case 1 is purely wasteful if we do not care about source types, but it doesn't obscure code understanding. Case 2 and case 3 is self-contradictory and not sure what is actually right. Case 4 is probably due to code rearrangement and is fine if that is the case.

To discover these anomalies, I modified `R2RDump` so that it outputs markers in the dump as follow:

All of the above are excerpts from the `R2RDump` of `System.Private.CoreLib.dll` built using `crossgen` (not `crossgen2`).

```c#
            public static void WriteTo(this DebugInfo theThis, TextWriter writer, DumpOptions dumpOptions)
            {
                ...
                if (i > 0)
                {
                    uint nocode = unchecked((uint)-1);
                    uint prolog = unchecked((uint)-2);
                    uint epilog = unchecked((uint)-3);

                    uint previousILOffset = theThis.BoundsList[i - 1].ILOffset;
                    uint currentILOffset = theThis.BoundsList[i].ILOffset;
                    uint previousNativeOffset = theThis.BoundsList[i - 1].NativeOffset;
                    uint currentNativeOffset = theThis.BoundsList[i].NativeOffset;

                    if (currentNativeOffset == previousNativeOffset)
                    {
                        if (currentILOffset == previousILOffset)
                        {
                            // Why are emitting exactly the same mapping more than once?
                            writer.WriteLine("Ooops1");
                        }
                        else
                        {
                            // This is even more weird, why would one native offset means more than one ILOffset?
                            writer.WriteLine("Ooops2");
                        }
                    }
                    else if (currentNativeOffset < previousNativeOffset)
                    {
                        // This is not happening, the array seems to be sorted by native offset
                        writer.WriteLine("Ooops3");
                    }
                    else
                    {
                        if (currentILOffset != nocode && currentILOffset != prolog && currentILOffset != epilog)
                        {
                            if (previousILOffset != nocode && previousILOffset != prolog && previousILOffset != epilog)
                            {
                                if (currentILOffset == previousILOffset)
                                {
                                    // Why would two distinct native offset correspond to the same ILOffset?
                                    writer.WriteLine("Ooops4");
                                }
                                else if (currentILOffset < previousILOffset)
                                {
                                    // The JIT rearranged stuff so that latter IL instruction is executed earlier,
                                    // this is probably fine
                                    writer.WriteLine("Ooops5");
                                }
                            }
                        }
                    }
                }
```

The code is also available in my branch [here](https://github.com/dotnet/runtime/compare/master...cshung:dev/andrewau/debug-info-verification?expand=1) for quick reproduction of the issue.

@dotnet/dotnet-diag
@dotnet/crossgen-contrib 
@dotnet/jit-contrib

**Comment by tommcdon** [comment] 2020-01-27 19:43
@cshung do you plan on working on this?

**Comment by cshung** [comment] 2020-01-27 20:08
> @cshung do you plan on working on this?

Nope, I do not plan to fix the compiler.

However, it is a prerequisite to @BrianBohe 's work (so that we have a reasonable post-condition to verify for debug info correctness) and https://github.com/icsharpcode/ILSpy/issues/1886 which require an unambiguous interpretation of the debug info in order to produce reasonable visualization, which I wanted to do.

**Comment by tommcdon** [comment] 2020-01-28 00:27
@cshung Thank you for in depth information. Just as a data point, is the above suspicious debug info a regression? Please work with @hoyosjs to run the diagnostics tests against R2R images for debugger validation.

**Comment by tommcdon** [comment] 2020-10-14 21:01
Closing due to lack of customer impact

**Closed by tommcdon** 2020-10-14 21:01 UTC
Labels: area-Diagnostics-coreclr
