### ISSUE TITLE
AssemblyDependencyResolver throws exception if target assembly has name change in case only

### ISSUE THREAD

**Issue by Scottj1s** [dotnet/runtime#41689] opened 2020-09-01 18:14 UTC
Seen when implementing a HostFxr-based hosting shim for C#/WinRT ([PR here](https://github.com/microsoft/CsWinRT/pull/374)).

**Repro**
The repro code is simply:
`new AssemblyDependencyResolver(path);`

where `path` specifies an assembly that has been renamed, such that the dll name differs from the assembly's display name in case only.  For example, if the assembly display name is "Test" but the path contains "test.dll".  

**Actual**
In this case, an exception is thrown:
"An item with the same key has already been added."

**Expected**
Ideally, the path passed to AssemblyDependencyResolver would be case-insensitive (at least on Windows) to be robust against any inadvertent name changes

Note that Assembly.LoadFrom does not have this issue.  This is a concern for C#/WinRT clients who may inadvertently change case for assemblies that need to load into an AssemblyLoadContext.

/cc @jkoritzinsky

**Comment by vitek-karas** [comment] 2020-09-01 19:02
This is a dupe of https://github.com/dotnet/runtime/issues/37162.

**Closed by vitek-karas** 2020-09-01 19:02 UTC
Labels: area-AssemblyLoader-coreclr, untriaged
