### ISSUE TITLE
change the default of cpu group to be enabled on Windows

### ISSUE THREAD

**Issue by Maoni0** [dotnet/runtime#13465] opened 2019-09-23 22:56 UTC
historically the default has been disabled. in 3.0 by default we will use > 64 procs on linux since we got rid of the (simulated) cpu group concept there. we should change the default on windows to match this. 
this includes changing the default for both GCCpuGroup and Thread_UseAllCpuGroups. 

CC @janvorli

**Comment by AntonLapounov** [comment] 2022-03-27 23:18
In Windows 11 processes are no longer constrained to a single processor group by default. I guess that means we should consider both `GCCpuGroup` and `Thread_UseAllCpuGroups` enabled by default. See related issue #67180.

**Comment by mangod9** [comment] 2022-07-27 15:48
do we still need for tracking, given the linked issue is closed?

**Comment by mangod9** [comment] 2022-08-04 17:29
Resolving this as a dupe of https://github.com/dotnet/runtime/issues/67180. Anton is working on getting his PR: https://github.com/dotnet/runtime/pull/68639 merged in 7

**Closed by mangod9** 2022-08-04 17:29 UTC
Labels: os-windows, area-GC-coreclr
