### ISSUE TITLE
ActivatorUtilities.CreateInstance Throwing InvalidOperationException in .NET 8

### ISSUE THREAD

**Issue by eajhnsn1** [dotnet/runtime#94736] opened 2023-11-14 21:44 UTC
### Description

After upgrading to .NET 8, ActivatorUtilties.CreateInstance is throwing InvalidOperationException when the following conditions are met
1. The type being activated has multiple constructors, one of which is the default constructor
2. There are no constructor parameters passed to ActivatorUtilties.CreateInstance, ie. Type.EmptyTypes

### Reproduction Steps

```cs
    internal class Program
    {
        static void Main(string[] args)
        {
            _ = ActivatorUtilities.CreateInstance(new EmptyServiceProvider(), typeof(TestClass));
        }

        class TestClass
        {
            public TestClass()
            {
                    
            }
    
            /* Comment out this constructor and the call will succeed */
            public TestClass(int value)
            {

            }
        }

        class EmptyServiceProvider : IServiceProvider
        {
            public object? GetService(Type serviceType)
            {
                return null;
            }
        }
    }    
```

### Expected behavior

Call the default constructor.

### Actual behavior

Throwing InvalidOperationException, with message "Multiple constructors accepting all given argument types have been found in type ..."

### Regression?

Yes this worked in .NET 7 and prior.

**Comment by mikechristiansenvae** [comment] 2023-11-16 15:43
I believe you're supposed to be using `ActivatorUtilitiesConstructorAttribute` to indicate which constructor to use, if there is more than one.

Although it does seem that the behavior of this method was changed for .NET 8 in PR #75846

**Comment by eajhnsn1** [comment] 2023-11-16 16:54
I'll also add that this occurs when the container does not support using IServiceProviderIsService.  The exception is being thrown from TryFindMatchingConstructor.

**Comment by buyaa-n** [comment] 2023-11-16 16:54
CC @steveharter

**Comment by steveharter** [comment] 2023-11-16 19:31
> Although it does seem that the behavior of this method was changed for .NET 8 in PR https://github.com/dotnet/runtime/pull/75846

Correct; I verified this issue was due to the check\usage of  `IServiceProviderIsService` in [PR #75846](https://github.com/dotnet/runtime/pull/75846/files#diff-fb8d7b29b1ef5b84f9327e76355798f150b03d46d2e2595c561df1b060ca4ca7R44).

Assuming we make no changes, the workarounds are:
- The service provider must implement `IServiceProviderIsService` in order to tell whether or not a given parameter type is registered as a service.
- Use [ActivatorUtilitiesConstructor] on the appropriate preferred constructor.

The original PR  should have been marked with the `breaking-change` label.

**Comment by steveharter** [comment] 2023-11-17 16:48
Closing as by design based on the breaking change notification linked above.

**Closed by steveharter** 2023-11-17 16:48 UTC
Labels: regression-from-last-release, area-Extensions-DependencyInjection
