### ISSUE TITLE
[API Proposal]: Allow to await a SynchronizationContext or a TaskScheduler

### ISSUE THREAD

**Issue by matteo-prosperi** [dotnet/runtime#61133] opened 2021-11-02 23:41 UTC
### Background and motivation

When writing async code, switching to executing code on a given SynchornizationContext or TaskScheduler requires complicated code.
It would be great to be able to simply `await` an instance of SynchornizationContext or TaskScheduler

### API Proposal

Microsoft.VisualStudio.Threading already provides this ability for the TaskScheduler (see [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.threading.awaitextensions.getawaiter?view=visualstudiosdk-2019)).

vs-streamjsonrpc provides this ability for the SynchronizationContext (see [here](https://github.com/microsoft/vs-streamjsonrpc/blob/main/src/StreamJsonRpc/AwaitExtensions.cs)).

It would be great if these capabilities were available natively in .NET without requiring additional code or libraries.

The `GetAwaiter` method could be provided either directly on the SynchornizationContext and TaskScheduler types or as extension methods.

### API Usage

```cs
async Task DoSomethingAsync()
{
    var sc = SynchronizationContext.Current;
    await TaskScheduler.Default;
    // Do something off the main thread
    if (sc is not null)
    {
        await sc;
    }
    // Back on the original synchronization context
}
```

**Comment by Frassle** [comment] 2021-11-03 10:22
For comparison with another dotnet language, F# has `Async.SwitchToContext` which lets you do this for a SynchornizationContext.

**Comment by stephentoub** [comment] 2021-11-03 11:13
Duplicate of https://github.com/dotnet/runtime/issues/20025

**Closed by stephentoub** 2021-11-03 11:13 UTC
Labels: api-suggestion, area-System.Threading.Tasks, untriaged
