### ISSUE TITLE
Performance optimization suggestion for Enum.Value.ToString()

### ISSUE THREAD

**Issue by VladimirKhvostov** [dotnet/runtime#62976] opened 2021-12-17 23:29 UTC
### Description
Unfortunately, it is not the first time I see code like this:
```CSharp
public enum EncryptionStatus
{
    Enabled,
    Disabled
}
...

string someValue;
...
if (someValue == EncryptionStatus.Enabled.ToString())
{
}
```
instead of 
```CSharp
if (someValue == nameof(EncryptionStatus.Enabled))
{
}
```
The code generated in the first case can be optimized to generate the same code as in second case.

Example:
https://sharplab.io/#gist:88b14759ff454d97700a07c561df1e51

Alternatively, instead of optimizing code, it would be good to have a code analyzer for such code.

**Comment by svick** [comment] 2021-12-18 21:02
I think this is a duplicate of https://github.com/dotnet/runtime/issues/57748.

**Comment by buyaa-n** [comment] 2024-03-13 00:10
Closing as duplicate of #57748

**Closed by buyaa-n** 2024-03-13 00:10 UTC
Labels: area-System.Runtime, tenet-performance, code-analyzer, needs-further-triage
