### ISSUE TITLE
Test failure:JIT\\Regression\\JitBlue\\GitHub_27924\\GitHub_27924\\GitHub_27924.cmd

### ISSUE THREAD

**Issue by AriNuer** [dotnet/runtime#34316] opened 2020-03-31 03:21 UTC
Test `JIT\\Regression\\JitBlue\\GitHub_27924\\GitHub_27924\\GitHub_27924.cmd` has failed.
**Job:**
[runtime-coreclr crossgen2:20200329.1](https://dev.azure.com/dnceng/public/_build/results?buildId=579196&view=results)
**Error message:**
```
Assert failure(PID 5500 [0x0000157c], Thread: 4312 [0x10d8]): Consistency check failed: AV in clr at this callstack:
------
CORECLR! memcmp + 0x12 (0x00007ffccbc2a3a2)
CORECLR! Thread::VirtualUnwindCallFrame + 0x311 (0x00007ffccb522295)
CORECLR! EECodeManager::EnsureCallerContextIsValid + 0x1B3 (0x00007ffccb7853c7)
CORECLR! StackFrameIterator::CheckForSkippedFrames + 0x6D (0x00007ffccb51d2f9)
CORECLR! StackFrameIterator::ProcessCurrentFrame + 0x178 (0x00007ffccb521450)
CORECLR! StackFrameIterator::Init + 0x229 (0x00007ffccb51f621)
CORECLR! Thread::StackWalkFramesEx + 0x11E (0x00007ffccb521c8e)
CORECLR! Thread::HandledJITCase + 0x21A (0x00007ffccb57b6fe)
CORECLR! ThreadSuspend::SuspendRuntime + 0x46B (0x00007ffccb580cd3)
CORECLR! ThreadSuspend::SuspendEE + 0x2A3 (0x00007ffccb5804f7)
CORECLR! GCToEEInterface::SuspendEE + 0x48 (0x00007ffccbb75470)
CORECLR! WKS::gc_heap::bgc_suspend_EE + 0x1D (0x00007ffccbafe661)
CORECLR! WKS::gc_heap::background_mark_phase + 0x754 (0x00007ffccbafb8ac)
CORECLR! WKS::gc_heap::gc1 + 0x27B (0x00007ffccbb08d27)
CORECLR! WKS::gc_heap::bgc_thread_function + 0x140 (0x00007ffccbafe7b4)
CORECLR! <lambda_1379a2d48c07ab188c44504ae9ea0884>::operator() + 0xA0 (0x00007ffccbb726e4)
KERNEL32! BaseThreadInitThunk + 0x14 (0x00007ffcd6e384d4)
NTDLL! RtlUserThreadStart + 0x21 (0x00007ffcd79ce8b1)
-----
.AV on tid=0x10d8 (4312), cxr=00000059C10FD180, exr=00000059C10FD670
FAILED: false
CORECLR! CHECK::Trigger + 0x2CC (0x00007ffccb406738)
CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x26F (0x00007ffccb47f39b)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x86 (0x00007ffccb47ef1a)
CORECLR! CLRVectoredExceptionHandler + 0x1BF (0x00007ffccb47ee73)
CORECLR! CLRVectoredExceptionHandlerShim + 0x189 (0x00007ffccb47f5f9)
NTDLL! RtlInitializeCriticalSection + 0x190 (0x00007ffcd79c5ef0)
NTDLL! RtlImageNtHeaderEx + 0x17B (0x00007ffcd799fa7b)
NTDLL! KiUserExceptionDispatcher + 0x3A (0x00007ffcd7a0964a)
CORECLR! memcmp + 0x12 (0x00007ffccbc2a3a2)
CORECLR! Thread::VirtualUnwindCallFrame + 0x311 (0x00007ffccb522295)
File: F:\workspace\_work\1\s\src\coreclr\src\vm\excep.cpp Line: 7558
Image: C:\h\w\A2E50878\p\CoreRun.exe
Return code: 1
Raw output file: C:\h\w\A2E50878\w\B5FE099F\e\JIT\Regression\Reports\JIT.Regression\JitBlue\GitHub_27924\GitHub_27924\GitHub_27924.output.txt
Raw output:
BEGIN EXECUTION
1 file(s) copied.
" "C:\h\w\A2E50878\p\CoreRun.exe" "C:\h\w\A2E50878\p\crossgen2\crossgen2.dll" C:\h\w\A2E50878\w\B5FE099F\e\JIT\Regression\JitBlue\GitHub_27924\GitHub_27924\GitHub_27924.org -o:C:\h\w\A2E50878\w\B5FE099F\e\JIT\Regression\JitBlue\GitHub_27924\GitHub_27924\GitHub_27924.dll --targetarch:x64 -O --inputbubble -r:"C:\h\w\A2E50878\p\System..dll" -r:"C:\h\w\A2E50878\p\Microsoft..dll" -r:"C:\h\w\A2E50878\p\netstandard.dll" -r:"C:\h\w\A2E50878\p\mscorlib.dll" -r:C:\h\w\A2E50878\w\B5FE099F\e\JIT\Regression\JitBlue\GitHub_27924\GitHub_27924\*.dll"
Crossgen2 failed with exitcode - -1073740286
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\A2E50878\p
> C:\h\w\A2E50878\w\B5FE099F\e\JIT\Regression\JitBlue\GitHub_27924\GitHub_27924\GitHub_27924.cmd
Expected: True
Actual: False
```
**Stack trace:**
```
at JIT_Regression._JitBlue_GitHub_27924_GitHub_27924_GitHub_27924_._JitBlue_GitHub_27924_GitHub_27924_GitHub_27924_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x64.Checked\TestWrappers\JIT.Regression\JIT.Regression.XUnitWrapper.cs:line 53005
```
**Details:**
https://dev.azure.com/dnceng/public/_build/results?buildId=579196&view=ms.vss-test-web.build-test-results-tab&runId=18209170&resultId=101918&paneView=debug

**Comment by jaredpar** [comment] 2020-03-31 05:06
### Builds
|Build|Pull Request | Test Failure Count|
| --- | --- | --- |
|[#579196](https://dev.azure.com/dnceng/public/_build/results?buildId=579196)|Rolling|1|
### Configurations
- R2R-CG2 Windows_NT x64 Checked @ Windows.10.Amd64.Open
### Helix Logs
|Build|Pull Request|Console|Core|Test Results|Run Client|
| --- | --- | --- | --- | --- | --- |
|[#579196](https://dev.azure.com/dnceng/public/_build/results?buildId=579196)|Rolling|[console.log](https://helix.dot.net/api/2019-06-17/jobs/ccf10315-f331-4206-949a-c17b13375265/workitems/JIT.Regression/files/console.b81a6b4e.log)||[testResults.xml](https://helix.dot.net/api/2019-06-17/jobs/ccf10315-f331-4206-949a-c17b13375265/workitems/JIT.Regression/files/testResults.xml)|[run_client.py](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-ccf10315f331420694/JIT.Regression/db6e7131-ba3c-4d29-8331-13bca4477451.log?sv=2019-02-02&se=2020-04-09T08%3A37%3A27Z&sr=c&sp=rl&sig=Gli8OfUk9hXG3ZPHhI5LcLTBkoYnyepF6pROaQaw114%3D)|

So far this is the only failure in last 50 runs

> runfo  tests -d 674 -n GitHub_27924 -c 50 -pr -m

**Comment by v-haren** [comment] 2020-04-20 07:19
failed again in job: [runtime-coreclr crossgen2 20200418.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=607357&view=ms.vss-test-web.build-test-results-tab&runId=19080772&resultId=102008&paneView=debug)

failed test: JIT\\Regression\\JitBlue\\GitHub_27924\\GitHub_27924\\GitHub_27924.cmd


Error message
~~~
Could Not Find C:\h\w\B4020A3B\w\B3A309FC\e\JIT\Regression\JitBlue\GitHub_27924\GitHub_27924\GitHub_27924.dll.rsp

Assert failure(PID 1392 [0x00000570], Thread: 3808 [0x0ee0]): Consistency check failed: AV in clr at this callstack:
------
CORECLR! memcmp + 0x12 (0x00007ffaa1555c82)
CORECLR! Thread::VirtualUnwindCallFrame + 0x311 (0x00007ffaa0e4f291)
CORECLR! EECodeManager::EnsureCallerContextIsValid + 0x1B3 (0x00007ffaa10d2177)
CORECLR! StackFrameIterator::CheckForSkippedFrames + 0x6D (0x00007ffaa0e4a309)
CORECLR! StackFrameIterator::ProcessCurrentFrame + 0x178 (0x00007ffaa0e4e44c)
CORECLR! StackFrameIterator::Init + 0x229 (0x00007ffaa0e4c611)
CORECLR! Thread::StackWalkFramesEx + 0x11E (0x00007ffaa0e4ec8a)
CORECLR! Thread::HandledJITCase + 0x219 (0x00007ffaa0ea8535)
CORECLR! ThreadSuspend::SuspendRuntime + 0x46B (0x00007ffaa0eadb13)
CORECLR! ThreadSuspend::SuspendEE + 0x2A3 (0x00007ffaa0ead337)
CORECLR! GCToEEInterface::SuspendEE + 0x48 (0x00007ffaa14a0c30)
CORECLR! WKS::GCHeap::GarbageCollectGeneration + 0x241 (0x00007ffaa1420c8d)
CORECLR! WKS::GCHeap::StressHeap + 0x4D0 (0x00007ffaa14236c0)
CORECLR! Thread::PerformPreemptiveGC + 0x2ED (0x00007ffaa0ea9fb5)
CORECLR! Thread::RareEnablePreemptiveGC + 0x10D (0x00007ffaa0eaa839)
CORECLR! Thread::EnablePreemptiveGC + 0x12D (0x00007ffaa0d7fa8d)
CORECLR! GCHolderBase::EnterInternalPreemp<1> + 0x1B2 (0x00007ffaa0f67e92)
CORECLR! GCPreempThreadExists::GCPreempThreadExists + 0x30 (0x00007ffaa0f6816c)
CORECLR! ExternalMethodFixupWorker + 0x15F (0x00007ffaa0f7326f)
-----
.AV on tid=0xee0 (3808), cxr=000000FD56976200, exr=000000FD569766F0
FAILED: false

CORECLR! CHECK::Trigger + 0x2CC (0x00007ffaa0d36a98)
CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x26F (0x00007ffaa0dae81b)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x86 (0x00007ffaa0dae39a)
CORECLR! CLRVectoredExceptionHandler + 0x1BF (0x00007ffaa0dae2f3)
CORECLR! CLRVectoredExceptionHandlerShim + 0x189 (0x00007ffaa0daea79)
NTDLL! RtlInitializeCriticalSection + 0x190 (0x00007ffaacff5ef0)
NTDLL! RtlImageNtHeaderEx + 0x17B (0x00007ffaacfcfa7b)
NTDLL! KiUserExceptionDispatcher + 0x3A (0x00007ffaad03964a)
CORECLR! memcmp + 0x12 (0x00007ffaa1555c82)
CORECLR! Thread::VirtualUnwindCallFrame + 0x311 (0x00007ffa`a0e4f291)
 File: F:\workspace\_work\1\s\src\coreclr\src\vm\excep.cpp Line: 7556
 Image: C:\h\w\B4020A3B\p\CoreRun.exe


Return code: 1
Raw output file: C:\h\w\B4020A3B\w\B3A309FC\e\JIT\Regression\Reports\JIT.Regression\JitBlue\GitHub_27924\GitHub_27924\GitHub_27924.output.txt
Raw output:
BEGIN EXECUTION
 1 file(s) copied.
Response file: C:\h\w\B4020A3B\w\B3A309FC\e\JIT\Regression\JitBlue\GitHub_27924\GitHub_27924\\GitHub_27924.dll.rsp
--inputbubble
C:\h\w\B4020A3B\w\B3A309FC\e\JIT\Regression\JitBlue\GitHub_27924\GitHub_27924\IL\GitHub_27924.dll
-r:C:\h\w\B4020A3B\w\B3A309FC\e\JIT\Regression\JitBlue\GitHub_27924\GitHub_27924\IL\.dll
-o:C:\h\w\B4020A3B\w\B3A309FC\e\JIT\Regression\JitBlue\GitHub_27924\GitHub_27924\\GitHub_27924.dll
--targetarch:x64
-O
-r:C:\h\w\B4020A3B\p\System..dll
-r:C:\h\w\B4020A3B\p\Microsoft.*.dll
-r:C:\h\w\B4020A3B\p\mscorlib.dll
-r:C:\h\w\B4020A3B\p\netstandard.dll
" "C:\h\w\B4020A3B\p\CoreRun.exe" "C:\h\w\B4020A3B\p\crossgen2\crossgen2.dll" @"C:\h\w\B4020A3B\w\B3A309FC\e\JIT\Regression\JitBlue\GitHub_27924\GitHub_27924\\GitHub_27924.dll.rsp" "
Crossgen2 failed with exitcode - -1073740286
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\B4020A3B\p
> C:\h\w\B4020A3B\w\B3A309FC\e\JIT\Regression\JitBlue\GitHub_27924\GitHub_27924\GitHub_27924.cmd
Expected: True
Actual: False


Stack trace
   at JIT_Regression._JitBlue_GitHub_27924_GitHub_27924_GitHub_27924_._JitBlue_GitHub_27924_GitHub_27924_GitHub_27924_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x64.Checked\TestWrappers\JIT.Regression\JIT.Regression.XUnitWrapper.cs:line 53005
~~~

**Comment by trylek** [comment] 2020-05-02 21:00
New repro: https://dev.azure.com/dnceng/public/_build/results?buildId=626338&view=ms.vss-test-web.build-test-results-tab&runId=19563378&resultId=102468&paneView=attachments

<pre>
Assert failure(PID 5464 [0x00001558], Thread: 3876 [0x0f24]): Consistency check failed: AV in clr at this callstack:
------
CORECLR! memcmp + 0x12 (0x00007ff8`105c48f2)
CORECLR! Thread::VirtualUnwindCallFrame + 0x340 (0x00007ff8`0fe6d7c8)
CORECLR! EECodeManager::EnsureCallerContextIsValid + 0x1C3 (0x00007ff8`1022d8bf)
CORECLR! StackFrameIterator::CheckForSkippedFrames + 0x6D (0x00007ff8`0fe683b1)
CORECLR! StackFrameIterator::ProcessCurrentFrame + 0x178 (0x00007ff8`0fe6c788)
CORECLR! StackFrameIterator::Init + 0x1E5 (0x00007ff8`0fe6a81d)
CORECLR! Thread::StackWalkFramesEx + 0x12E (0x00007ff8`0fe6d16e)
CORECLR! Thread::HandledJITCase + 0x234 (0x00007ff8`0fec8a5c)
CORECLR! ThreadSuspend::SuspendRuntime + 0x421 (0x00007ff8`0fecdeb9)
CORECLR! ThreadSuspend::SuspendEE + 0x29B (0x00007ff8`0fecd7bf)
CORECLR! GCToEEInterface::SuspendEE + 0x48 (0x00007ff8`1050e088)
CORECLR! WKS::gc_heap::bgc_suspend_EE + 0x1D (0x00007ff8`10496b8d)
CORECLR! WKS::gc_heap::background_mark_phase + 0x71E (0x00007ff8`10493e06)
CORECLR! WKS::gc_heap::gc1 + 0x254 (0x00007ff8`104a11f4)
CORECLR! WKS::gc_heap::bgc_thread_function + 0x145 (0x00007ff8`10496ce5)
CORECLR! <lambda_ed421b834c755a19f8a9f171513da6ca>::operator() + 0xA0 (0x00007ff8`1050b2ac)
KERNEL32! BaseThreadInitThunk + 0x14 (0x00007ff8`3bb584d4)
NTDLL! RtlUserThreadStart + 0x21 (0x00007ff8`3e58e8b1)
</pre>

**Comment by v-haren** [comment] 2020-05-14 04:00
failed again in job: [runtime-coreclr crossgen2 20200512.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=642513&view=ms.vss-test-web.build-test-results-tab&runId=19954954&resultId=102125&paneView=debug)

failed test: JIT\\Regression\\JitBlue\\GitHub_27924\\GitHub_27924\\GitHub_27924.cmd


Error message
~~~
Could Not Find C:\h\w\BC700A2F\w\A313094F\e\JIT\Regression\JitBlue\GitHub_27924\GitHub_27924\GitHub_27924.dll.rsp

Assert failure(PID 5512 [0x00001588], Thread: 800 [0x0320]): Consistency check failed: AV in clr at this callstack:
------
CORECLR! memcmp + 0x12 (0x00007ffa73525642)
CORECLR! Thread::VirtualUnwindCallFrame + 0x340 (0x00007ffa72dca688)
CORECLR! EECodeManager::EnsureCallerContextIsValid + 0x1C3 (0x00007ffa7316a36f)
CORECLR! StackFrameIterator::CheckForSkippedFrames + 0x6D (0x00007ffa72dc5271)
CORECLR! StackFrameIterator::ProcessCurrentFrame + 0x178 (0x00007ffa72dc9648)
CORECLR! StackFrameIterator::Init + 0x1E5 (0x00007ffa72dc76dd)
CORECLR! Thread::StackWalkFramesEx + 0x12E (0x00007ffa72dca02e)
CORECLR! Thread::HandledJITCase + 0x234 (0x00007ffa72e2583c)
CORECLR! ThreadSuspend::SuspendRuntime + 0x421 (0x00007ffa72e2ac99)
CORECLR! ThreadSuspend::SuspendEE + 0x29B (0x00007ffa72e2a59f)
CORECLR! GCToEEInterface::SuspendEE + 0x48 (0x00007ffa7346bcf8)
CORECLR! WKS::gc_heap::bgc_suspend_EE + 0x1D (0x00007ffa733f467d)
CORECLR! WKS::gc_heap::background_mark_phase + 0x71E (0x00007ffa733f18f6)
CORECLR! WKS::gc_heap::gc1 + 0x254 (0x00007ffa733fed04)
CORECLR! WKS::gc_heap::bgc_thread_function + 0x145 (0x00007ffa733f47d5)
CORECLR! <lambda_9f752664bdd70c4edda59fe709a3c6f4>::operator() + 0xA0 (0x00007ffa73468f1c)
KERNEL32! BaseThreadInitThunk + 0x14 (0x00007ffaa1d684d4)
NTDLL! RtlUserThreadStart + 0x21 (0x00007ffaa47ce8b1)
-----
.AV on tid=0x320 (800), cxr=000000955157CB40, exr=000000955157D030
FAILED: false

CORECLR! CHECK::Trigger + 0x2C9 (0x00007ffa72cc7c65)
CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x2B2 (0x00007ffa72d2145e)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x97 (0x00007ffa72d20f1f)
CORECLR! CLRVectoredExceptionHandler + 0x215 (0x00007ffa72d20e65)
CORECLR! CLRVectoredExceptionHandlerShim + 0x1A0 (0x00007ffa72d216d0)
NTDLL! RtlInitializeCriticalSection + 0x190 (0x00007ffaa47c5ef0)
NTDLL! RtlImageNtHeaderEx + 0x17B (0x00007ffaa479fa7b)
NTDLL! KiUserExceptionDispatcher + 0x3A (0x00007ffaa480964a)
CORECLR! memcmp + 0x12 (0x00007ffa73525642)
CORECLR! Thread::VirtualUnwindCallFrame + 0x340 (0x00007ffa72dca688)
 File: F:\workspace\_work\1\s\src\coreclr\src\vm\excep.cpp Line: 7575
 Image: C:\h\w\BC700A2F\p\CoreRun.exe


Return code: 1
Raw output file: C:\h\w\BC700A2F\w\A313094F\e\JIT\Regression\Reports\JIT.Regression\JitBlue\GitHub_27924\GitHub_27924\GitHub_27924.output.txt
Raw output:
BEGIN EXECUTION
 1 file(s) copied.
Response file: C:\h\w\BC700A2F\w\A313094F\e\JIT\Regression\JitBlue\GitHub_27924\GitHub_27924\\GitHub_27924.dll.rsp
--inputbubble
C:\h\w\BC700A2F\w\A313094F\e\JIT\Regression\JitBlue\GitHub_27924\GitHub_27924\IL\GitHub_27924.dll
-r:C:\h\w\BC700A2F\w\A313094F\e\JIT\Regression\JitBlue\GitHub_27924\GitHub_27924\IL\.dll
-o:C:\h\w\BC700A2F\w\A313094F\e\JIT\Regression\JitBlue\GitHub_27924\GitHub_27924\\GitHub_27924.dll
--targetarch:x64
-O
-r:C:\h\w\BC700A2F\p\System..dll
-r:C:\h\w\BC700A2F\p\Microsoft.*.dll
-r:C:\h\w\BC700A2F\p\mscorlib.dll
-r:C:\h\w\BC700A2F\p\netstandard.dll
" "C:\h\w\BC700A2F\p\CoreRun.exe" "C:\h\w\BC700A2F\p\crossgen2\crossgen2.dll" @"C:\h\w\BC700A2F\w\A313094F\e\JIT\Regression\JitBlue\GitHub_27924\GitHub_27924\\GitHub_27924.dll.rsp" "
Crossgen2 failed with exitcode - -1073740286
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\BC700A2F\p
> C:\h\w\BC700A2F\w\A313094F\e\JIT\Regression\JitBlue\GitHub_27924\GitHub_27924\GitHub_27924.cmd
Expected: True
Actual: False


Stack trace
   at JIT_Regression._JitBlue_GitHub_27924_GitHub_27924_GitHub_27924_._JitBlue_GitHub_27924_GitHub_27924_GitHub_27924_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x64.Checked\TestWrappers\JIT.Regression\JIT.Regression.XUnitWrapper.cs:line 53102
~~~

**Comment by v-haren** [comment] 2020-06-23 05:10
failed again in job: [runtime-coreclr r2r 20200621.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=698064&view=ms.vss-test-web.build-test-results-tab&runId=21631952&resultId=108565&paneView=debug)\

failed test: JIT\\Regression\\JitBlue\\GitHub_27924\\GitHub_27924\\GitHub_27924.cmd



Error message
~~~
Assert failure(PID 1808 [0x00000710], Thread: 444 [0x01bc]): Consistency check failed: AV in clr at this callstack:


------
<no module>! <no symbol> + 0x0 (0x00000000)
-----
.AV on tid=0x1bc (444), cxr=0A19FA60, exr=0A19FC00
FAILED: false

<no module>! <no symbol> + 0x0 (0x00000000)
 File: F:\workspace\_work\1\s\src\coreclr\src\vm\excep.cpp Line: 7494
 Image: D:\h\w\B138097B\p\CoreRun.exe


Return code: 1
Raw output file: D:\h\w\B138097B\w\A2AD0916\e\JIT\Regression\Reports\JIT.Regression\JitBlue\GitHub_27924\GitHub_27924\GitHub_27924.output.txt
Raw output:
BEGIN EXECUTION
 1 file(s) copied.
" "D:\h\w\B138097B\p\crossgen.exe" /Platform_Assemblies_Paths D:\h\w\B138097B\p;D:\h\w\B138097B\w\A2AD0916\e\JIT\Regression\JitBlue\GitHub_27924\GitHub_27924 /in D:\h\w\B138097B\w\A2AD0916\e\JIT\Regression\JitBlue\GitHub_27924\GitHub_27924\GitHub_27924.org /out D:\h\w\B138097B\w\A2AD0916\e\JIT\Regression\JitBlue\GitHub_27924\GitHub_27924\\GitHub_27924.dll"


Microsoft (R) CoreCLR Native Image Generator - Version 5.0.0-ci
Copyright (c) Microsoft Corporation. All rights reserved.

Native image D:\h\w\B138097B\w\A2AD0916\e\JIT\Regression\JitBlue\GitHub_27924\GitHub_27924\\GitHub_27924.dll generated successfully.
 "D:\h\w\B138097B\p\corerun.exe" GitHub_27924.dll 
Expected: 100

Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=D:\h\w\B138097B\p
> D:\h\w\B138097B\w\A2AD0916\e\JIT\Regression\JitBlue\GitHub_27924\GitHub_27924\GitHub_27924.cmd
Expected: True

Actual: False


Stack trace
   at JIT_Regression._JitBlue_GitHub_27924_GitHub_27924_GitHub_27924_._JitBlue_GitHub_27924_GitHub_27924_GitHub_27924_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.arm.Checked\TestWrappers\JIT.Regression\JIT.Regression.XUnitWrapper.cs:line 122360
~~~

**Comment by safern** [comment] 2020-07-02 23:43
Failed again: https://dev.azure.com/dnceng/public/_build/results?buildId=715155&view=logs&j=6ffa34aa-4e0e-5e33-51b1-9621a575e196&t=2fdabd0b-7202-58e4-755d-1556a81de2e1&l=38

**Comment by mangod9** [comment] 2020-08-12 17:22
Closing since I can repro this anymore.

**Closed by mangod9** 2020-08-12 17:22 UTC
Labels: arch-x64, area-crossgen2-coreclr, os-windows
