### ISSUE TITLE
Investigate regressions of binary-trees and fannkuch on benchmarksgame site

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#40810] opened 2020-08-14 00:35 UTC
Benchmarks game site has a comparison up of 3.1 vs . 5.0 preview 7 : https://benchmarksgame-team.pages.debian.net/benchmarksgame/fastest/csharpcore-csharppreview.html

There are 4 regressions, 2 may be noise level. The other two are binary-trees (7%)  and fannkuch-redux (4%)

I'll check those two using the source of the latest submissions.

**Comment by adamsitnik** [comment] 2020-08-18 10:31
FWIW the regression is Windows-specific

## BenchmarksGame.BinaryTrees_2.RunBench

| Conclusion |         Base |         Diff | Base/Diff | Modality | Operating System       | Bit | Processor Name                              | Base Runtime    | Diff Runtime   |
| ---------- | ------------:| ------------:| ---------:| --------:| ---------------------- | --- | ------------------------------------------- | --------------- | --------------- |
| Slower     | 104517050.00 | 115141650.00 |      0.91 |          | Windows 10.0.18363.959 | X64 | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 3.1.6 | .NET Core 5.0.0|
| Same       | 121320538.00 | 126695979.00 |      0.96 |          | ubuntu 18.04           | X64 | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 3.1.6 | .NET Core 5.0.0|
| Same       | 189125801.00 | 185862914.00 |      1.02 |          | macOS Mojave 10.14.5   | X64 | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 3.1.6 | .NET Core 5.0.0|

## BenchmarksGame.FannkuchRedux_5.RunBench(n: 10, expectedSum: 38)

| Conclusion |        Base |        Diff | Base/Diff | Modality | Operating System       | Bit | Processor Name                              | Base Runtime    | Diff Runtime   |
| ---------- | -----------:| -----------:| ---------:| -------- | ---------------------- | --- | ------------------------------------------- | --------------- | --------------- |
| Slower     | 24379150.00 | 39701257.14 |      0.61 | bimodal  | Windows 10.0.18363.959 | X64 | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 3.1.6 | .NET Core 5.0.0|
| Same       | 27439371.19 | 27543953.25 |      1.00 |          | ubuntu 18.04           | X64 | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 3.1.6 | .NET Core 5.0.0|
| Same       | 82078762.25 | 87040901.88 |      0.94 |          | macOS Mojave 10.14.5   | X64 | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 3.1.6 | .NET Core 5.0.0|

**Comment by danmosemsft** [comment] 2020-08-18 14:41
They measure on Ubuntu so if there's a windows regression that's coincidental 🙂

**Comment by AndyAyersMS** [comment] 2020-08-18 18:51
Benchmarks games now uses [a slightly more up to date Ivy Bridge cpu](https://benchmarksgame-team.pages.debian.net/benchmarksgame/how-programs-are-measured.html).

> Measured on a quad-core 3.0GHz Intel® i5-3330® with 15.8 GiB of RAM and 2TB SATA disk drive; using Ubuntu™ 20.04 x86_64 GNU/Linux 5.4.0-40-generic.

**Comment by AndyAyersMS** [comment] 2020-08-28 01:19
For BinaryTrees_2, there is a small codegen diff in `bottomUpTree` at Tier1. The `lea` does not get CSE'd in 5.0 and there's an extra `mov` in the pr olog.

```asm
;; 3.1

G_M54868_IG01:
       57                   push     rdi
       56                   push     rsi
       53                   push     rbx
       4883EC20             sub      rsp, 32

G_M54868_IG02:
       85C9                 test     ecx, ecx
       7E4C                 jle      SHORT G_M54868_IG04
       8D71FF               lea      esi, [rcx-1]
       8BCE                 mov      ecx, esi
       E8E3F3FFFF           call     TreeNode:bottomUpTree(int):struct
       488BF8               mov      rdi, rax
       8BCE                 mov      ecx, esi
       E8D9F3FFFF           call     TreeNode:bottomUpTree(int):struct

;; 5.0

G_M46436_IG01:
       57                   push     rdi
       56                   push     rsi
       53                   push     rbx
       4883EC20             sub      rsp, 32
       8BF1                 mov      esi, ecx

G_M46436_IG02:
       85F6                 test     esi, esi
       7E4B                 jle      SHORT G_M46436_IG05

G_M46436_IG03:
       8D4EFF               lea      ecx, [rsi-1]
       E8EBF3FFFF           call     TreeNode:bottomUpTree(int):TreeNode
       488BF8               mov      rdi, rax
       8D4EFF               lea      ecx, [rsi-1]
       E8E0F3FFFF           call     TreeNode:bottomUpTree(int):TreeNode
```
I have not yet confirmed this is the root cause of the perf difference, will try to do that soon.

Since this is a call-crossing lifetime I wonder if this is a consequence of #1463; the PR there shows a small perf score regression so presumably also a small code size regression.

Not sure if the new heuristic takes into account that CSEing something that uses a call-crossing live var might be cheaper than it seems if the CSEs are the only crossing appearances of the var; basically we'd be trading one call crossing lifetime for another. 

cc @briansull

**Comment by AndyAyersMS** [comment] 2020-08-28 02:45
More or less the same diff in the linux version:
```asm

;; 3.1

G_M54868_IG01:
       55                   push     rbp
       4157                 push     r15
       4156                 push     r14
       53                   push     rbx
       50                   push     rax
       488D6C2420           lea      rbp, [rsp+20H]

G_M54868_IG02:
       85FF                 test     edi, edi
       7E4F                 jle      SHORT G_M54868_IG04
       8D5FFF               lea      ebx, [rdi-1]
       8BFB                 mov      edi, ebx
       E800000000           call     TreeNode:bottomUpTree(int):struct
       4C8BF0               mov      r14, rax
       8BFB                 mov      edi, ebx
       E800000000           call     TreeNode:bottomUpTree(int):struct

;; 5.0

G_M46436_IG01:
       55                   push     rbp
       4157                 push     r15
       4156                 push     r14
       53                   push     rbx
       50                   push     rax
       488D6C2420           lea      rbp, [rsp+20H]
       8BDF                 mov      ebx, edi

G_M46436_IG02:
       85DB                 test     ebx, ebx
       7E4E                 jle      SHORT G_M46436_IG05

G_M46436_IG03:
       8D7BFF               lea      edi, [rbx-1]
       E800000000           call     TreeNode:bottomUpTree(int):TreeNode
       4C8BF0               mov      r14, rax
       8D7BFF               lea      edi, [rbx-1]
       E800000000           call     TreeNode:bottomUpTree(int):TreeNode
```

**Comment by briansull** [comment] 2020-08-28 17:22
@AndyAyersMS  I will take a look

**Comment by briansull** [comment] 2020-08-28 17:31
I wouldn't expect that
` lea      edi, [rbx-1]`
to be slower than
` mov      edi, ebx`

The extra instruction in the prolog 
`mov      ebx, edi`
should be offset by the extra instruction to setup the CSE
`lea      ebx, [rdi-1]`

**Comment by briansull** [comment] 2020-08-28 17:33
CSE doesn't see this as profitable.

**Comment by AndyAyersMS** [comment] 2020-08-28 17:50
But in 3.0 it was considered profitable?

**Comment by AndyAyersMS** [comment] 2020-08-28 18:30
Locally I see a potential regression in FannkuchRedux_9 on windows x64, though the 5.0 run has high variance. But the other two versions seem to be consistently faster.

```ini
BenchmarkDotNet=v0.12.1.1405-nightly, OS=Windows 10.0.19041.450 (2004/May2020Update/20H1)
Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.100-rc.1.20407.13
  [Host]     : .NET Core 5.0.0 (CoreCLR 5.0.20.40416, CoreFX 5.0.20.40416), X64 RyuJIT
  Job-NMJCAW : .NET Core 3.1.4 (CoreCLR 4.700.20.20201, CoreFX 4.700.20.21406), X64 RyuJIT
  Job-JQYCRY : .NET Core 5.0.0 (CoreCLR 5.0.20.40416, CoreFX 5.0.20.40416), X64 RyuJIT
```

|            Type |       RT |  n | sum |      Mean |     Error |    StdDev |    Median |       Min |       Max | Ratio |
|---------------- |-------------- |--- |------------ |----------:|----------:|----------:|----------:|----------:|----------:|------:|
| FannkuchRedux_5 |  3.1 | 10 |          38 |  45.39 ms |  2.493 ms |  2.771 ms |  44.09 ms |  42.60 ms |  52.44 ms |  1.00 |
| FannkuchRedux_5 |  5.0 | 10 |          38 |  43.68 ms |  1.006 ms |  1.076 ms |  43.57 ms |  42.21 ms |  45.91 ms |  0.97 |
|                 |               |    |             |           |           |           |           |           |           |       |
| FannkuchRedux_2 |  3.1 | 10 |       73196 | 163.94 ms | 10.318 ms | 11.882 ms | 164.25 ms | 146.87 ms | 191.22 ms |  1.00 |
| FannkuchRedux_2 |  5.0 | 10 |       73196 | 146.51 ms |  4.870 ms |  5.609 ms | 146.05 ms | 139.46 ms | 160.05 ms |  0.90 |
|                 |               |    |             |           |           |           |           |           |           |       |
| FannkuchRedux_9 |  3.1 | 11 |      556355 | 404.73 ms |  8.088 ms |  7.943 ms | 404.47 ms | 392.71 ms | 421.88 ms |  1.00 |
| FannkuchRedux_9 |  5.0 | 11 |      556355 | 436.61 ms | 19.457 ms | 22.407 ms | 438.80 ms | 405.44 ms | 469.88 ms |  1.07 |

Will take a look on Ubuntu too.

**Comment by AndyAyersMS** [comment] 2020-08-28 18:53
Ubuntu looks similar for me (note older HW and RC8 vs Preview1, so not directly comparable to the above) -- FannkuchRedux_9 seems slower in 5.0.

```ini
BenchmarkDotNet=v0.12.1.1405-nightly, OS=ubuntu 18.04
Intel Core i7-2720QM CPU 2.20GHz (Sandy Bridge), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.100-preview.8.20417.9
  [Host]     : .NET Core 3.1.7 (CoreCLR 4.700.20.36602, CoreFX 4.700.20.37001), X64 RyuJIT
  Job-JHIWSX : .NET Core 3.1.7 (CoreCLR 4.700.20.36602, CoreFX 4.700.20.37001), X64 RyuJIT
  Job-CWFQLH : .NET Core 5.0.0 (CoreCLR 5.0.20.40711, CoreFX 5.0.20.40711), X64 RyuJIT

PowerPlanMode=00000000-0000-0000-0000-000000000000  Arguments=/p:DebugType=portable  IterationTime=250.0000 ms  
MaxIterationCount=20  MinIterationCount=15  WarmupCount=1  
```

|            Type |       RT |  n | sum |      Mean |    Error |   StdDev |    Median |       Min |       Max | Ratio |
|---------------- |-------------- |--- |------------ |----------:|---------:|---------:|----------:|----------:|----------:|------:|
| FannkuchRedux_5 |  3.1 | 10 |          38 |  75.09 ms | 0.745 ms | 0.660 ms |  74.92 ms |  74.34 ms |  76.77 ms |  1.00 |
| FannkuchRedux_5 |  5.0 | 10 |          38 |  76.80 ms | 1.218 ms | 1.139 ms |  76.38 ms |  75.27 ms |  79.02 ms |  1.02 |
|                 |               |    |             |           |          |          |           |           |           |       |
| FannkuchRedux_2 |  3.1 | 10 |       73196 | 317.39 ms | 0.212 ms | 0.188 ms | 317.37 ms | 317.07 ms | 317.80 ms |  1.00 |
| FannkuchRedux_2 |  5.0 | 10 |       73196 | 319.04 ms | 0.403 ms | 0.337 ms | 319.04 ms | 318.08 ms | 319.56 ms |  1.01 |
|                 |               |    |             |           |          |          |           |           |           |       |
| FannkuchRedux_9 |  3.1 | 11 |      556355 | 676.94 ms | 6.637 ms | 6.208 ms | 677.03 ms | 665.76 ms | 685.21 ms |  1.00 |
| FannkuchRedux_9 |  5.0 | 11 |      556355 | 710.44 ms | 2.657 ms | 2.218 ms | 710.34 ms | 705.68 ms | 714.14 ms |  1.05 |

**Comment by AndyAyersMS** [comment] 2020-08-28 22:34
For FannkuchRedux_9, all the key perf is in `Run`.

For windows x64 codegen from 3.1 to 5.0 is very similar. 5.0 does a few more CSEs and avoids some spills. Most CQ looks locally better, eg here is the inner loop of the last `for` in `FirstPermutation`:
```asm
;;; 3.1 (x64 win)

G_M27408_IG15:
       428D043B             lea      eax, [rbx+r15]
       458D6601             lea      r12d, [r14+1]           // loop invariant
       99                   cdq      
       41F7FC               idiv     edx:eax, r12d
       4863C2               movsxd   rax, edx
       480FBF0447           movsx    rax, word  ptr [rdi+2*rax]
       4863D3               movsxd   rdx, ebx
       66890456             mov      word  ptr [rsi+2*rdx], ax
       FFC3                 inc      ebx
       413BDE               cmp      ebx, r14d
       7EDE                 jle      SHORT G_M27408_IG15

;;; 5.0 (one fewer mov)

G_M7882_IG16:
       438D043C             lea      eax, [r12+r15]
       99                   cdq      
       41F7FD               idiv     edx:eax, r13d
       4863C2               movsxd   rax, edx
       480FBF0447           movsx    rax, word  ptr [rdi+2*rax]
       4963D4               movsxd   rdx, r12d
       66890456             mov      word  ptr [rsi+2*rdx], ax
       41FFC4               inc      r12d
       453BE6               cmp      r12d, r14d
       7EE1                 jle      SHORT G_M7882_IG16
```
Because of this loops end up aligned differently; suspect this might be the root cause for perf issues.

Similar diffs in linux x64 codegen.

**Comment by AndyAyersMS** [comment] 2020-08-29 00:07
For FannkuchRedux_9, Looking at linux perf, 5.0 has fewer instructions but higher clocks (IPC is 0.99 in 3.1; 0.94 in 5.0). Branch misses are up. So some kind of micro-architectural effect, quite possibly code alignment.

```
andy@andy-ubuntu:~/bugs/r40810$ perf stat -d dotnet exec /home/andy/bugs/r40810/f/bin/Release/net5.0/f.dll 
556355
Pfannkuchen(11) = 51

 Performance counter stats for 'dotnet exec /home/andy/bugs/r40810/f/bin/Release/net5.0/f.dll':

          5,776.17 msec task-clock                #    6.407 CPUs utilized          
               219      context-switches          #    0.038 K/sec                  
                 5      cpu-migrations            #    0.001 K/sec                  
             2,187      page-faults               #    0.379 K/sec                  
    11,369,904,249      cycles                    #    1.968 GHz                      (32.64%)
     7,166,244,393      stalled-cycles-frontend   #   63.03% frontend cycles idle     (42.47%)
     4,246,791,011      stalled-cycles-backend    #   37.35% backend cycles idle      (43.00%)
    10,734,941,194      instructions              #    0.94  insn per cycle         
                                                  #    0.67  stalled cycles per insn  (53.86%)
     1,554,131,325      branches                  #  269.059 M/sec                    (51.40%)
       202,785,963      branch-misses             #   13.05% of all branches          (52.87%)
     1,923,302,116      L1-dcache-loads           #  332.972 M/sec                    (38.33%)
         2,188,800      L1-dcache-load-misses     #    0.11% of all L1-dcache hits    (31.07%)
           699,606      LLC-loads                 #    0.121 M/sec                    (22.26%)
   <not supported>      LLC-load-misses                                             

       0.901590482 seconds time elapsed

       5.738926000 seconds user
       0.043961000 seconds sys


andy@andy-ubuntu:~/bugs/r40810$ perf stat -d dotnet exec /home/andy/bugs/r40810/f/bin/Release/netcoreapp3.1/f.dll
556355
Pfannkuchen(11) = 51

 Performance counter stats for 'dotnet exec /home/andy/bugs/r40810/f/bin/Release/netcoreapp3.1/f.dll':

          5,541.41 msec task-clock                #    6.571 CPUs utilized          
               200      context-switches          #    0.036 K/sec                  
                 8      cpu-migrations            #    0.001 K/sec                  
             1,996      page-faults               #    0.360 K/sec                  
    10,895,741,345      cycles                    #    1.966 GHz                      (33.64%)
     6,964,856,321      stalled-cycles-frontend   #   63.92% frontend cycles idle     (41.88%)
     3,964,367,855      stalled-cycles-backend    #   36.38% backend cycles idle      (43.15%)
    10,761,932,188      instructions              #    0.99  insn per cycle         
                                                  #    0.65  stalled cycles per insn  (54.04%)
     1,557,636,040      branches                  #  281.090 M/sec                    (54.03%)
       183,314,400      branch-misses             #   11.77% of all branches          (54.76%)
     1,934,439,969      L1-dcache-loads           #  349.088 M/sec                    (43.98%)
         3,206,904      L1-dcache-load-misses     #    0.17% of all L1-dcache hits    (33.38%)
           701,527      LLC-loads                 #    0.127 M/sec                    (22.60%)
   <not supported>      LLC-load-misses                                             

       0.843306468 seconds time elapsed

       5.519643000 seconds user
       0.027957000 seconds sys

```

**Comment by AndyAyersMS** [comment] 2020-08-29 00:26
Similar data for BinaryTrees_2. Here we see 5.0 has slightly better IPC but quite a few more instructions to execute;
```
andy@andy-ubuntu:~/bugs/r40810/b$ perf stat -d dotnet exec /home/andy/bugs/r40810/b/bin/Release/net5.0/b.dll

 Performance counter stats for 'dotnet exec /home/andy/bugs/r40810/b/bin/Release/net5.0/b.dll':

            499.71 msec task-clock                #    1.010 CPUs utilized          
                51      context-switches          #    0.102 K/sec                  
                 5      cpu-migrations            #    0.010 K/sec                  
             5,637      page-faults               #    0.011 M/sec                  
       938,804,171      cycles                    #    1.879 GHz                      (32.00%)
       334,250,542      stalled-cycles-frontend   #   35.60% frontend cycles idle     (43.19%)
       140,647,936      stalled-cycles-backend    #   14.98% backend cycles idle      (44.77%)
     1,576,795,897      instructions              #    1.68  insn per cycle         
                                                  #    0.21  stalled cycles per insn  (56.48%)
       346,894,682      branches                  #  694.191 M/sec                    (57.98%)
         1,670,050      branch-misses             #    0.48% of all branches          (57.25%)
       523,532,754      L1-dcache-loads           # 1047.672 M/sec                    (50.91%)
        10,172,775      L1-dcache-load-misses     #    1.94% of all L1-dcache hits    (20.91%)
         1,872,450      LLC-loads                 #    3.747 M/sec                    (20.66%)
   <not supported>      LLC-load-misses                                             

       0.494821787 seconds time elapsed

       0.452010000 seconds user
       0.052001000 seconds sys


andy@andy-ubuntu:~/bugs/r40810/b$ perf stat -d dotnet exec /home/andy/bugs/r40810/b/bin/Release/netcoreapp3.1/b.dll

 Performance counter stats for 'dotnet exec /home/andy/bugs/r40810/b/bin/Release/netcoreapp3.1/b.dll':

            466.87 msec task-clock                #    1.007 CPUs utilized          
                58      context-switches          #    0.124 K/sec                  
                 1      cpu-migrations            #    0.002 K/sec                  
             4,798      page-faults               #    0.010 M/sec                  
       885,595,535      cycles                    #    1.897 GHz                      (35.04%)
       345,941,828      stalled-cycles-frontend   #   39.06% frontend cycles idle     (47.13%)
       149,589,073      stalled-cycles-backend    #   16.89% backend cycles idle      (47.06%)
     1,464,498,744      instructions              #    1.65  insn per cycle         
                                                  #    0.24  stalled cycles per insn  (57.32%)
       328,724,263      branches                  #  704.102 M/sec                    (56.46%)
         1,478,562      branch-misses             #    0.45% of all branches          (53.65%)
       473,982,827      L1-dcache-loads           # 1015.235 M/sec                    (49.88%)
         8,932,883      L1-dcache-load-misses     #    1.88% of all L1-dcache hits    (22.16%)
         1,522,914      LLC-loads                 #    3.262 M/sec                    (22.02%)
   <not supported>      LLC-load-misses                                             

       0.463624216 seconds time elapsed

       0.416904000 seconds user
       0.055062000 seconds sys
```
Looking at profiles we spend quite a bit more time than I realized in `TreeNode:itemCheck` and looking at the code there, we no longer do the recursive inlines we used to do in 3.1.

So likely the main source of the perf difference in BinaryTrees_2 is from #35020.

Seems like we might want to reconsider the policy of not doing any recursive inlines, though suspect for the most part the beneficiary of such inlines is in microbenchmarks. Opened #41542.

**Comment by AndyAyersMS** [comment] 2020-08-29 00:28
I think this is understood and there's nothing we can or need to address in 5.0.

So unless there are any objections I propose we close this.

**Comment by AndyAyersMS** [comment] 2020-08-29 01:26
Some more data -- here's the perf history of BinaryTrees_2

![image](https://user-images.githubusercontent.com/10121823/91625320-3e9d1880-e95b-11ea-9219-c4de3c76639c.png)

Timing of the regression correlates with #35020 which merged on April 15.

Similar look for BinaryTrees_5, though somehow we recovered the perf later on, so perhaps we should look into that as well.

![image](https://user-images.githubusercontent.com/10121823/91625383-caaf4000-e95b-11ea-9a32-26d45ac900c9.png)

FannkuchRedux_9 is new, so no history to view.

**Comment by AndyAyersMS** [comment] 2020-08-29 01:31
(recovery of perf in BinaryTrees_5 may be from #38586 -- need to verify)

**Comment by AndyAyersMS** [comment] 2020-09-01 01:50
@danmosemsft per the above I am planning on closing this -- let me know if you agree.

**Comment by danmosemsft** [comment] 2020-09-01 18:59
Sounds good to me. Thanks for investigating.

**Comment by danmosemsft** [comment] 2020-09-01 19:10
5.0 will still be a clear improvement on Benchmarks game in general.

**Closed** 2020-09-01 19:10 UTC
Labels: area-CodeGen-coreclr, os-windows, tenet-performance
