### ISSUE TITLE
Debugger fails to attach to a specific application with CORDBG_E_MISSING_DEBUGGER_EXPORTS on macOS.

### ISSUE THREAD

**Issue by Dimension4** [dotnet/runtime#72603] opened 2022-07-21 13:16 UTC
### Description

The dotnet core debugger (vsdbg, using VS Code with C# extension) fails to attach to [SketchUp Pro](https://www.sketchup.com) with CORDBG_E_MISSING_DEBUGGER_EXPORTS on macOS 12.4 on a MacBook Pro M1 (2020). Unfortunately, this seems to be application specific (we were not able to reproduce this behavior when hosting the runtime from a custom native binary).

SketchUp doesn't use dotnet itself. We provide a C++ plugin for SketchUp that hosts the runtime.

More details can be found in the readme of this repro project: https://github.com/Dimension4/DotnetOsxDebuggingRepro.

### Reproduction Steps

Unfortunately, you'll need [SketchUp](https://www.sketchup.com), which is a commercial product (with a 30-day trial though).

Please check out the repro project: https://github.com/Dimension4/DotnetOsxDebuggingRepro.

### Expected behavior

Debugger attaches and breakpoints are hit.

### Actual behavior

Debugger fails to attach with CORDBG_E_MISSING_DEBUGGER_EXPORTS and the target application freezes.

### Configuration

- shared runtime .net 6.0 (see the repro project)
- macOS 12.4 (probably earlier as well)
- arm64 and x64 (translated with Rosetta, though)

I can't verify if this also happens on native x64 macOS.

### Other information

- I couldn't verify if this also happens on .net 5.0 because I wasn't able to load the 5.0 runtime for some reason.
- It doesn't seem to be an issue within Ruby. At least loading the plugin directly via a standalone ruby installation is working fine, including attaching the .net debugger.
- I tried to sign vsdbg myself (see https://github.com/OmniSharp/omnisharp-vscode/issues/4903#issuecomment-993015843), didn't help
- Maybe related #42888
- Maybe related #42311, although my system uses XCode 13.3
- Here is a log from vsdbg (names have been anonymized)
    ```json
    Waiting for communication on port 4711...
    >> accepted connection from client
    -> (C) {
        "command": "initialize",
        "arguments": {
            "clientID": "vscode",
            "clientName": "Visual Studio Code",
            "adapterID": "coreclr",
            "pathFormat": "path",
            "linesStartAt1": true,
            "columnsStartAt1": true,
            "supportsVariableType": true,
            "supportsVariablePaging": true,
            "supportsRunInTerminalRequest": true,
            "locale": "en-gb",
            "supportsProgressReporting": true,
            "supportsInvalidatedEvent": true,
            "supportsMemoryReferences": true
        },
        "type": "request",
        "seq": 1
    }
    <- (R) {
        "seq": 1,
        "type": "response",
        "request_seq": 1,
        "success": true,
        "command": "initialize",
        "body": {
            "supportsConfigurationDoneRequest": true,
            "supportsFunctionBreakpoints": true,
            "supportsConditionalBreakpoints": true,
            "supportsHitConditionalBreakpoints": true,
            "supportsEvaluateForHovers": true,
            "exceptionBreakpointFilters": [
                {
                    "filter": "all",
                    "label": "All Exceptions",
                    "description": "Break when an exception is thrown. For more information about exception settings, see: https://aka.ms/VSCode-CS-ExceptionSettings",
                    "default": false,
                    "supportsCondition": true,
                    "conditionDescription": "Comma-separated list of exception types to break on, or if the list starts with '!', a list of exception types to ignore. \nExample 1: System.NullReferenceException -- this will break on just null reference exceptions. \nExample 2: !System.Threading.Tasks.TaskCanceledException -- this will break on all exceptions except for task canceled.\n\nFor more information about exception settings, see: https://aka.ms/VSCode-CS-ExceptionSettings"
                },
                {
                    "filter": "user-unhandled",
                    "label": "User-Unhandled Exceptions",
                    "description": "Break when an exception is caught in non-user code (system code) after having passed through user code. For more information about exception settings, see: https://aka.ms/VSCode-CS-ExceptionSettings",
                    "default": true,
                    "supportsCondition": true,
                    "conditionDescription": "Comma-separated list of exception types to break on, or if the list starts with '!', a list of exception types to ignore. \nExample 1: System.NullReferenceException -- this will break on just null reference exceptions. \nExample 2: !System.Threading.Tasks.TaskCanceledException -- this will break on all exceptions except for task canceled.\n\nFor more information about exception settings, see: https://aka.ms/VSCode-CS-ExceptionSettings"
                }
            ],
            "supportsSetVariable": true,
            "supportsGotoTargetsRequest": true,
            "supportsModulesRequest": true,
            "supportedChecksumAlgorithms": [
                "MD5",
                "SHA1",
                "SHA256"
            ],
            "supportsExceptionOptions": true,
            "supportsValueFormattingOptions": true,
            "supportsExceptionInfoRequest": true,
            "supportTerminateDebuggee": true,
            "supportsSetExpression": true,
            "supportsReadMemoryRequest": true,
            "supportsCancelRequest": true,
            "supportsExceptionFilterOptions": true,
            "supportsExceptionConditions": true,
            "supportsLoadSymbolsRequest": true,
            "supportsModuleSymbolSearchLog": true,
            "supportsDebuggerProperties": true,
            "supportsSetSymbolOptions": true,
            "supportsHitBreakpointIds": true,
            "supportsVsIndividualBreakpointOperations": true,
            "supportsVsBreakpointLanguage": true,
            "supportsSetHitCount": true,
            "supportsVsCustomMessages": true,
            "supportsEvaluationOptions": true,
            "supportsExceptionStackTrace": true,
            "memoryReferencesAreAddresses": true,
            "supportsObjectFavorites": true,
            "supportsObjectId": true,
            "supportsVariableEnumerators": false
        }
    }
    -> (C) {
        "command": "initialize",
        "arguments": {
            "clientID": "vscode",
            "clientName": "Visual Studio Code",
            "adapterID": "coreclr",
            "pathFormat": "path",
            "linesStartAt1": true,
            "columnsStartAt1": true,
            "supportsVariableType": true,
            "supportsVariablePaging": true,
            "supportsRunInTerminalRequest": true,
            "locale": "en-gb",
            "supportsProgressReporting": true,
            "supportsInvalidatedEvent": true,
            "supportsMemoryReferences": true
        },
        "type": "request",
        "seq": 1
    }
    -> (C) {
        "command": "attach",
        "arguments": {
            "name": "Attach to SketchUp (manual debugger)",
            "debugServer": 4711,
            "type": "coreclr",
            "request": "attach",
            "processName": "SketchUp",
            "__configurationTarget": 5,
            "__sessionId": "94c9b474-84fd-4041-a911-40a5a718ce6e"
        },
        "type": "request",
        "seq": 2
    }
    <- (E) {
        "seq": 4,
        "type": "event",
        "event": "output",
        "body": {
            "category": "console",
            "output": "-------------------------------------------------------------------\nYou may only use the Microsoft .NET Core Debugger (vsdbg) with\nVisual Studio Code, Visual Studio or Visual Studio for Mac software\nto help you develop and test your applications.\n-------------------------------------------------------------------\n",
            "severity": "ok"
        }
    }
    <- (R) {
        "seq": 5,
        "type": "response",
        "request_seq": 2,
        "success": true,
        "command": "attach"
    }
    <- (E) {
        "seq": 6,
        "type": "event",
        "event": "initialized",
        "body": {}
    }
    -> (C) {
        "command": "setBreakpoints",
        "arguments": {
            "source": {
                "name": "sourcefile.cs",
                "path": "/Users/foo/code/sourcefile.cs",
                "checksums": [
                    {
                        "algorithm": "SHA1",
                        "checksum": "abca0ca154944610e184f5ceb8288f09a8bd75aa"
                    },
                    {
                        "algorithm": "SHA256",
                        "checksum": "8712f084e20fcce005b6cbd36fccbd2026409c731cda7ace15d92af86854487a"
                    },
                    {
                        "algorithm": "SHA1",
                        "checksum": "0ccba374b6a42d4387419044aa7f769f2fabbb40"
                    },
                    {
                        "algorithm": "SHA256",
                        "checksum": "b28f40cf26ece8e64189eb117f6837c0ff1030d7a00545599e7243d9a2b84cdc"
                    }
                ]
            },
            "lines": [
                38
            ],
            "breakpoints": [
                {
                    "line": 38
                }
            ],
            "sourceModified": false
        },
        "type": "request",
        "seq": 3
    }
    -> (C) {
        "command": "setBreakpoints",
        "arguments": {
            "source": {
                "name": "PluginHost.cpp",
                "path": "/Users/foo/code/PluginHost.cpp",
                "checksums": [
                    {
                        "algorithm": "SHA1",
                        "checksum": "02822b43869db5e074b8d1fdd7f61833c8e6127c"
                    },
                    {
                        "algorithm": "SHA256",
                        "checksum": "c993dc8ead33c7fec25bd82ce48a7674137ccdbb3987a4503589d8e80a467770"
                    },
                    {
                        "algorithm": "SHA1",
                        "checksum": "9197069d6781b188d23fb69a32c746a157aefbc1"
                    },
                    {
                        "algorithm": "SHA256",
                        "checksum": "f35b541e1f505c6549cc4b99bcb5dfa996dc312c4a966cfc78e5c7faee82ac13"
                    }
                ]
            },
            "lines": [
                35
            ],
            "breakpoints": [
                {
                    "line": 35
                }
            ],
            "sourceModified": false
        },
        "type": "request",
        "seq": 4
    }
    <- (R) {
        "seq": 7,
        "type": "response",
        "request_seq": 3,
        "success": true,
        "command": "setBreakpoints",
        "body": {
            "breakpoints": [
                {
                    "id": 1,
                    "verified": false,
                    "message": "The breakpoint is pending and will be resolved when debugging starts.",
                    "line": 38
                }
            ]
        }
    }
    <- (R) {
        "seq": 8,
        "type": "response",
        "request_seq": 4,
        "success": true,
        "command": "setBreakpoints",
        "body": {
            "breakpoints": [
                {
                    "id": 2,
                    "verified": false,
                    "message": "The breakpoint is pending and will be resolved when debugging starts.",
                    "line": 35
                }
            ]
        }
    }
    -> (C) {
        "command": "setFunctionBreakpoints",
        "arguments": {
            "breakpoints": []
        },
        "type": "request",
        "seq": 5
    }
    <- (R) {
        "seq": 9,
        "type": "response",
        "request_seq": 5,
        "success": true,
        "command": "setFunctionBreakpoints",
        "body": {
            "breakpoints": []
        }
    }
    -> (C) {
        "command": "setExceptionBreakpoints",
        "arguments": {
            "filters": [],
            "filterOptions": [
                {
                    "filterId": "user-unhandled"
                }
            ]
        },
        "type": "request",
        "seq": 6
    }
    <- (R) {
        "seq": 10,
        "type": "response",
        "request_seq": 6,
        "success": true,
        "command": "setExceptionBreakpoints",
        "body": {
            "breakpoints": [
                {
                    "verified": true
                }
            ]
        }
    }
    -> (C) {
        "command": "configurationDone",
        "type": "request",
        "seq": 7
    }
    <- (E) {
        "seq": 11,
        "type": "event",
        "event": "output",
        "body": {
            "category": "telemetry",
            "output": "VS/Diagnostics/Debugger/vsdbg/AttachFailed",
            "data": {
                "VS.Diagnostics.Debugger.vsdbg.Distribution.Version": "21.5.0",
                "VS.Diagnostics.Debugger.vsdbg.Distribution.Name": "Darwin",
                "VS.Diagnostics.Debugger.vsdbg.Version": "17.2.10512.2 commit:9347ab79400fa806261d50481ba445cc6cb0d5e0",
                "VS.Diagnostics.Debugger.vsdbg.OSFamily": "Darwin",
                "VS.Diagnostics.Debugger.vsdbg.ErrorCode": -2146231217
            }
        }
    }
    <- (E) {
        "seq": 12,
        "type": "event",
        "event": "output",
        "body": {
            "category": "stderr",
            "output": "Unable to start debugging. Failed to attach to process: Unknown Error: 0x80131c4f\n"
        }
    }
    <- (R) {
        "seq": 13,
        "type": "response",
        "request_seq": 7,
        "success": false,
        "command": "configurationDone",
        "message": "Failed to attach to process: Unknown Error: 0x80131c4f"
    }
    -> (C) {
        "command": "disconnect",
        "arguments": {
            "restart": false
        },
        "type": "request",
        "seq": 8
    }
    <- (E) {
        "seq": 14,
        "type": "event",
        "event": "output",
        "body": {
            "category": "telemetry",
            "output": "VS/Diagnostics/Debugger/vsdbg/DebugCompleted",
            "data": {
                "VS.Diagnostics.Debugger.vsdbg.AdapterId": "coreclr",
                "VS.Diagnostics.Debugger.vsdbg.Distribution.Version": "21.5.0",
                "VS.Diagnostics.Debugger.vsdbg.Distribution.Name": "Darwin",
                "VS.Diagnostics.Debugger.vsdbg.DebugCompleted.BreakCounter": 0,
                "VS.Diagnostics.Debugger.vsdbg.Version": "17.2.10512.2 commit:9347ab79400fa806261d50481ba445cc6cb0d5e0",
                "VS.Diagnostics.Debugger.vsdbg.OSFamily": "Darwin"
            }
        }
    }
    <- (R) {
        "seq": 15,
        "type": "response",
        "request_seq": 8,
        "success": true,
        "command": "disconnect"
    }
    >> client connection closed
    ```

**Comment by tommcdon** [comment] 2023-04-25 01:35
Hi @Dimension4! We have made fixes to debugging that might have resolved this issue.  Would you mind letting us know if this issue still reproduces on the latest .NET 7 (or .NET 8) builds?

**Comment by Dimension4** [comment] 2023-05-05 08:05
Hey, just tried with 8.0.0-preview.3.23174.8 and the issue seems to persist.

**Comment by tommcdon** [comment] 2023-10-09 22:38
Hi @Dimension4.  The repro steps require installing software that has a software license as well as a trial period.  Due to difficulties related to installing licensed software we won't be able to investigate this issue.  If you are able to create a small repro, please let us know!  For now we will close this issue.

**Closed by tommcdon** 2023-10-09 22:38 UTC
Labels: area-Diagnostics-coreclr
