### ISSUE TITLE
R2R causing crashes on Windows 7

### ISSUE THREAD

**Issue by vdanche** [dotnet/runtime#54440] opened 2021-06-17 07:49 UTC
Machine OS: win7 SP1
Repro steps:
1. Install .NET 6 prevew 6 SDK-6.0.100-preview.6.21315.23(runtime-6.0.0-preview.6.21306.1) from https://github.com/dotnet/installer--Main branch
2. Run "dotnet new console" in CLI .

Expected Result:
Create project successfully

Actual Result:
NET Host stop working.
![image](https://user-images.githubusercontent.com/65637796/122354245-63628b00-cf83-11eb-8f6d-39cc736cc23d.png)

Note:
Not repro on win10

dotnet --info:
C:\Users\v-danche>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.6.21315.23
 Commit:    8f09936962

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.6.21315.23\

Host (useful for support):
  Version: 6.0.0-preview.6.21306.1
  Commit:  5b8e1780ad

.NET SDKs installed:
  6.0.100-preview.6.21315.23 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-preview.6.21306.3 [C:\Program Files\dotnet\sh
ed\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-preview.6.21306.1 [C:\Program Files\dotnet\share
Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.6.21305.3 [C:\Program Files\dotne
shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by AntonLapounov** [comment] 2021-06-22 01:00
On my Win7 machine with SDK 6.0.100-preview.6.21321.7 it is crashing with Access violation - code c0000005 on the call below:
```asm
int Microsoft.Build.CommandLine.MSBuildApp.Main(string[])
    push    rbp
    push    rdi
    push    rsi
    push    rbx
    sub     rsp, 56
    lea     rbp, [rsp + 80]
    mov     qword ptr [rbp - 48], rsp
    mov     rsi, rcx
    call    qword ptr [0xa2380]   // Microsoft.Build.CommandLine.MSBuildApp (CCTOR_TRIGGER)
```

**Comment by AntonLapounov** [comment] 2021-06-22 01:34
Apparently `DIR64` relocations in `MSBuild.dll` are ignored by the OS.  Probably because the file is not marked as a DLL:
```
Dump of file dotnet-sdk-6.0.100-preview.6.21321.7-win-x64\sdk\6.0.100-preview.6.21321.7\MSBuild.dll

PE signature found

File Type: EXECUTABLE IMAGE

FILE HEADER VALUES
            8664 machine (x64)
               3 number of sections
        B7A968BC time date stamp
               0 file pointer to symbol table
               0 number of symbols
              F0 size of optional header
              22 characteristics
                   Executable
                   Application can handle large (>2GB) addresses
```

**Comment by AntonLapounov** [comment] 2021-06-22 02:11
After I set the `DLL` flag on `MSBuild.dll` and `dotnet.dll`, `dotnet new console` finished successfully.

**Comment by mangod9** [comment] 2021-06-22 18:01
@dsplaisted @richlander do you feel this requires a backport to preview6? Also @vdanche checking on what Windows versions this is failing on. You do mention it doesnt repro on 10, but how about win8/8.1 etc? 
If its win7 only we will relnote it.

**Closed** 2021-06-22 22:45 UTC
Labels: area-crossgen2-coreclr, in pr

**Comment by richlander** [comment] 2021-06-23 05:50
> do you feel this requires a backport to preview6?

No.

**Comment by mangod9** [comment] 2021-06-23 06:03
Thanks. @vdanche, if this repros on other windows versions please let us know. 

@jeffschwMSFT fyi.

**Comment by mangod9** [comment] 2021-06-23 06:35
@vdanche confirmed that this repros on 8.1 as well. We will evaluate whether to backport.

**Comment by AntonLapounov** [comment] 2021-06-23 12:05
Created #54604 in case we decide to fix this in preview6.

**Comment by richlander** [comment] 2021-06-23 16:32
Ouch. I'm happy to have others make the call. I still probably wouldn't do it. I suspect that there are very few preview users on Windows 7 and 8.1.

**Comment by mangod9** [comment] 2021-06-23 16:36
Hi @dsplaisted @marcpopMSFT what are your thoughts on this since this is affecting the sdk in preview6.

**Comment by marcpopMSFT** [comment] 2021-06-23 18:49
From CLI data, win8 and win7 make up .5% of preview usage combined. It'll likely affect a few hundred users in total which isn't great. Worth raising in tactics perhaps as we're still seeing preview 6 fixes come through.

**Comment by mangod9** [comment] 2021-06-23 18:58
Ok, thanks for the info, since the preview6 PR is ready we will ask for approval.
