### ISSUE TITLE
Error	NETSDK1045	The current .NET SDK does not support targeting .NET 8.0.  Either target .NET 7.0 or lower

### ISSUE THREAD

**Issue by OurIslam** [dotnet/runtime#82280] opened 2023-02-17 02:57 UTC
full error details
```
[Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1045	The current .NET SDK does not support targeting .NET 8.0.  Either target .NET 7.0 or lower, or use a version of the .NET SDK that supports .NET 8.0.	dotnettst	C:\Program Files\dotnet\sdk\7.0.103\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	144	](url)
```

it works if i use cmd 
dotnet publish

but it wont works if i open it by visual studio 2022 
get this error 

attached target
[dotnettst.zip](https://github.com/dotnet/runtime/files/10762804/dotnettst.zip)

**Comment by JasonWues** [comment] 2023-02-17 03:25
Maybe Visual Studio will support .NET 8 when .NET 8 preview 1 is released.

**Comment by OurIslam** [comment] 2023-02-17 03:48
another problem i face =>

if i add
`<RuntimeIdentifier>win-x64</RuntimeIdentifier>`
in <PropertyGroup> in csproj
then i get error 
C:\Users\Admin\source\repos\dotnettst\dotnettst>dotnet restore
  Determining projects to restore...
C:\Users\Admin\source\repos\dotnettst\dotnettst\dotnettst.csproj : error NU1102: Unable to find package Microsoft.AspNe
tCore.App.Runtime.win-x64 with version (= 8.0.0-preview.2.23116.1)
C:\Users\Admin\source\repos\dotnettst\dotnettst\dotnettst.csproj : error NU1102:   - Found 621 version(s) in dotnet8 [
Nearest version: 8.0.0-preview.2.23116.2 ]
C:\Users\Admin\source\repos\dotnettst\dotnettst\dotnettst.csproj : error NU1102:   - Found 112 version(s) in nuget [ Ne
arest version: 7.0.3 ]
C:\Users\Admin\source\repos\dotnettst\dotnettst\dotnettst.csproj : error NU1102:   - Found 0 version(s) in C:\Program F
iles\dotnet\library-packs
  Failed to restore C:\Users\Admin\source\repos\dotnettst\dotnettst\dotnettst.csproj (in 1.31 sec).

but if i remove 
`<RuntimeIdentifier>win-x64</RuntimeIdentifier>`
from  <PropertyGroup> in csproj
C:\Users\Admin\source\repos\dotnettst\dotnettst>dotnet restore
  Determining projects to restore...
  Restored C:\Users\Admin\source\repos\dotnettst\dotnettst\dotnettst.csproj (in 79 ms).

**Comment by janvorli** [comment] 2023-02-17 12:39
> another problem i face =>

That's because that when you specify a runtime identifier, the SDK will search for the packages on nuget servers. And the .NET 8 packages are not available on the default ones. If you added a nuget.config file e.g. to the directory where you have the .csproj file and put the following into it, it would work:
```xml
<configuration>
  <packageSources>
    <add key="dotnet8" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json" />
  </packageSources>
</configuration>
```
You can find this info on the https://github.com/dotnet/installer main page.

**Comment by OurIslam** [comment] 2023-02-17 15:28
added that line in project => .csproj directory
`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
	  <add key="dotnet8" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json" />
  </packageSources>
</configuration>
`

still seeing same error

**Comment by janvorli** [comment] 2023-02-17 15:56
I've never tried to add that to the csproj, I use a separate nuget.config file. I am not sure if that matters, but I only have experience with the separate file.

**Comment by OurIslam** [comment] 2023-02-17 16:03
wait i said i have added that line in .csproj director => C:\Users\Admin\source\repos\ConsoleApp1\ConsoleApp1\nuget.config
code =>
`
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
	  <add key="dotnet8" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json" />
  </packageSources>
</configuration>
`
still seeing same error in both side

**Comment by janvorli** [comment] 2023-02-17 16:17
Looking at it again, the issue is that you have set the RuntimeFrameworkVersion to a fixed version and that version of Microsoft.AspNetCore.App.Runtime.win-x64 is not available on the nuget servers. 
Do you have a need to put the explicit version there? If you don't put the RuntimeFrameworkVersion into the csproj, it works.

**Comment by janvorli** [comment] 2023-02-17 16:20
The problem is that when you specify a version, the restore seems to use the version for both the `Microsoft.NETCore.App`
 and `Microsoft.AspNetCore.App`. These two are often not available with the same version number in the non-official builds.

**Comment by OurIslam** [comment] 2023-02-17 17:41
is .net 8.0 support to run in visual studio 2022 ?

**Comment by OurIslam** [comment] 2023-02-21 14:56
i am getting this error in dotnet 8
![image](https://user-images.githubusercontent.com/3030547/220379438-674a773d-7d3c-4f72-bf75-b08b9cf19875.png)

**Comment by janvorli** [comment] 2023-02-21 15:57
The error message explains the problem. You cannot attach Visual Studio to a non-official release of .NET by default. The .NET 8 is still in development. The second link in the message points to a description on how to make it work. Let me share the link to the exact paragraph in that document for your convenience:
https://github.com/dotnet/runtime/blob/main/docs/workflow/debugging/coreclr/debugging-runtime.md#resolving-signature-validation-errors-in-visual-studio

See the "There are three ways to configure Visual Studio to disable signature validation:" part for a list of ways to make it work.

**Closed** 2023-02-22 03:50 UTC
Labels: area-Setup, untriaged
