### ISSUE TITLE
Finally blocks not always ran on thrown exception

### ISSUE THREAD

**Issue by ThadHouse** [dotnet/runtime#65657] opened 2022-02-21 08:55 UTC
### Description

A question got brought up on Discord on why the following code in a top level code block printed the exception and then the finally block

```
try
{
    throw new ArgumentException("Ala ma kota. A kot ma Alę.");
}
finally
{
    Console.WriteLine("Finally executing");
}
```

Their test was on windows. I tried running it on my M1 Macbook, and got an even weirder issue. The finally didn't print at all. I tried forcing Console.Out.Flush, and that didn't print the finally either. I also added a 10 second sleep, which also didn't run. That is very unexpected, as the runtime should be guaranteeing all finally blocks at least attempt to get ran. Debug or Release mode doesn't matter.

### Reproduction Steps

Run the following in a top level C# program in .NET 6 on an M1 mac.

```
try
{
    throw new ArgumentException("Ala ma kota. A kot ma Alę.");
}
finally
{
    Console.WriteLine("Finally executing");
}
```

### Expected behavior

```
thad@Thads-MacBook-Air dotnettest % dotnet run
Unhandled exception. System.ArgumentException: Ala ma kota. A kot ma Alę.
   at Program.<Main>$(String[] args) in /Users/thad/GitHub/dotnettest/Program.cs:line 3
Finally executing
```

### Actual behavior

```
thad@Thads-MacBook-Air dotnettest % dotnet run
Unhandled exception. System.ArgumentException: Ala ma kota. A kot ma Alę.
   at Program.<Main>$(String[] args) in /Users/thad/GitHub/dotnettest/Program.cs:line 3
```

### Regression?

Does not seem to be, .NET 5 also shows the same behavior.

### Configuration

.NET 6 and .NET 5 on an M1 mac running macOS 12.0.1

**Comment by hez2010** [comment] 2022-02-21 10:18
You need a catch block to catch the exception, otherwise the thread will exit abnormally so no code in the finally block will be executed.

**Comment by Joe4evr** [comment] 2022-02-21 10:23
> You need a catch block to catch the exception, otherwise the thread will exit abnormally before code in the finally block can be executed.

That's not what [the language spec](https://github.com/dotnet/csharplang/blob/main/spec/statements.md#the-try-statement) says:
> A `try` statement is executed as follows:
> [...]
> *  If an exception is propagated to the `try` statement during execution of the `try` block:
>    [...]
>    *  If the `try` statement has no `catch` clauses or if no `catch` clause matches the exception:
>       *  If the `try` statement has a `finally` block, the `finally` block is executed.
>       *  The exception is propagated to the next enclosing `try` statement.
> 
> The statements of a `finally` block are always executed when control leaves a `try` statement. This is true whether the control transfer occurs as a result of normal execution, as a result of executing a `break`, `continue`, `goto`, or `return` statement, or as a result of propagating an exception out of the `try` statement.

**Comment by hez2010** [comment] 2022-02-21 10:31
My bad. I just played it on my x64 computer, and it did print `Finally exiting`.

**Comment by jkotas** [comment] 2022-02-21 13:23
Duplicate of https://github.com/dotnet/runtime/issues/8145 ?

**Comment by 333fred** [comment] 2022-03-29 01:02
Looks like a duplicate to me.

**Closed by 333fred** 2022-03-29 01:02 UTC
Labels: area-ExceptionHandling-coreclr, untriaged
