### ISSUE TITLE
Native AOT debug info broken on MacOS

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#83038] opened 2023-03-06 17:38 UTC
It looks like debug info works differently on MacOS. The standard approach seems to be to include a map for debug info in the binary, and store the DWARF info in dSYM files.

I'm not sure how much of that we're already doing or whether it's correct. We'll need some investigation here to figure out what the right way of producing debug info is for MacOS.

**Comment by filipnavara** [comment] 2023-03-06 19:29
FWIW it did work when I was doing the macOS arm64 bringup last year. The .o files contained valid DWARF info (which I fixed on the libobjwriter side). The linker then just embeds the GUID links back to the original .o files with the DWARF info. There were some [small quirks that the linker relied on](https://github.com/dotnet/llvm-project/blob/b26c7684d47ebb0faa58690c8858caa28abbe13e/llvm/tools/objwriter/debugInfo/dwarf/dwarfGen.cpp#L978-L989).

**Comment by filipnavara** [comment] 2023-03-06 19:37
I can confirm it's broken on my test setup too. I'll do some quick checks to see what went wrong but there's always the option to bisect to find the culprit.

**Comment by filipnavara** [comment] 2023-03-06 19:45
Both `dsymutil -dump-debug-map` and `dsymutil -s` report the symbols on the main executable. That means the debug map is working, and it reduces the culprit back to the DWARF info. I briefly dumped it with `dwarfdump` and there was nothing obviously striking me as wrong but it's probably worth a second look.

**Comment by filipnavara** [comment] 2023-03-06 20:54
Interestingly, even the debugger knows the symbol paths, finds the .o file, and even part of the function lookup still works:
```
(lldb) log enable dwarf all
(lldb) image lookup -F CatchMe
 (arm64) /Users/filipnavara/Projects/exc/obj/Debug/net8.0/osx-arm64/native/exc.o: SymbolFileDWARF::FindFunctions (name="CatchMe", name_type_mask=0x38, sc_list)
 (arm64) /Users/filipnavara/Projects/exc/obj/Debug/net8.0/osx-arm64/native/exc.o: SymbolFileDWARF::FindFunctions (name="CatchMe", name_type_mask=0x38, include_inlines=1, sc_list) => 1
...
```
but it fails somewhere after that.

**Comment by filipnavara** [comment] 2023-03-06 22:33
The only reasonable explanation to what I see in LLDB is that the [RemoveFunctionsWithModuleNotEqualTo method](https://github.com/dotnet/llvm-project/blob/aa1630ee8351214be828af4f6269f655c31c269a/lldb/source/Plugins/SymbolFile/DWARF/SymbolFileDWARFDebugMap.cpp#L982-L1005) is discarding the symbol lookups that would succeed otherwise.

That points to address ranges in the DWARF info being incorrect.

The function address range looks okay:

```
0x000c1197:   DW_TAG_subprogram
                DW_AT_specification     (0x0002b74d "_exc_Program__CatchMe")
                DW_AT_low_pc    (0x00000000000f89a0)
                DW_AT_high_pc   (0x00000000000f8a0c)
                DW_AT_frame_base        (DW_OP_reg29 W29)
```

and so does the one in the compile unit:

```
0x0000000b: DW_TAG_compile_unit
              DW_AT_producer    ("CoreRT")
              DW_AT_language    (DW_LANG_C_plus_plus)
              DW_AT_name        ("IL.c")
              DW_AT_comp_dir    ("/tmp")
              DW_AT_low_pc      (0x0000000000000000)
              DW_AT_high_pc     (0x00000000002daae8)
              DW_AT_stmt_list   (0x00000000)
```

They are, however, section relative, and that's not visible in this type of a dwarfdump. This is especially important on macOS since the DWARF info is not relocated like on Linux, and the DWARF tables themselves are used for mapping the section addresses.

**Comment by tommcdon** [comment] 2023-03-06 22:45
adding @mikem8361 in case there is other information we should be aware of needed for dump debugging.

**Comment by filipnavara** [comment] 2023-03-06 23:10
I found the culprit. It's caused by something that changed in ld64. The version shipped with Xcode 12.5 works, the one in Xcode 14 does not.

The difference is in the debug map in the final executable. It can be dumped with `dsymutil -s` and searching for `N_OSO`.

Working one:
```
[  3147] 0039fcae 64 (N_SO         ) 00     0000   0000000000000000 '/tmp/'
[  3148] 0039fcb4 64 (N_SO         ) 00     0000   0000000000000000 'IL.c'
[  3149] 0039fcb9 66 (N_OSO        ) 00     0001   000000006404628c '/Users/filipnavara/Projects/exc/obj/Debug/net8.0/osx-arm64/native/exc.o'
```

Broken one:
```
[  3146] 00000001 64 (N_SO         ) 01     0000   0000000000000000
[  3147] 0039fc8e 64 (N_SO         ) 00     0000   0000000000000000 'IL.c/'
[  3148] 00000001 64 (N_SO         ) 00     0000   0000000000000000
[  3149] 0039fc94 66 (N_OSO        ) 00     0001   000000006404628c '/Users/filipnavara/Projects/exc/obj/Debug/net8.0/osx-arm64/native/exc.o'
```

We will need to tweak [this code in ObjWriter](https://github.com/dotnet/llvm-project/blob/b26c7684d47ebb0faa58690c8858caa28abbe13e/llvm/tools/objwriter/debugInfo/dwarf/dwarfGen.cpp#L978-L989) to emit full path in `DW_AT_name` attribute.

**Comment by agocke** [comment] 2023-03-06 23:16
@filipnavara Thanks for the investigation! I'll grab my mac and give it a try.

**Comment by filipnavara** [comment] 2023-03-07 21:13
So, the fix is actually swapping the order of `DW_AT_name` and `DW_AT_comp_dir`. Unfortunately Apple stopped publishing ld64 source code, so it's not obvious why it makes a difference. Should I submit a PR?

**Comment by agocke** [comment] 2023-03-07 21:58
I actually was just looking at the same thing. I'm away from my computer but was going to submit a pr shortly. I'm confused because it doesn't look like the order is reversed in c++

**Comment by filipnavara** [comment] 2023-03-07 22:01
The weird thing is that reversing the order generates viable output in the `N_SO` symbols but not a correct one like the ld64 12.x version. I'd like to understand what is going on but at least I can produce some output that happens to work.

**Comment by filipnavara** [comment] 2023-03-07 22:20
I could get the correct result if `DW_FORM_strp` was used instead of `DW_FORM_string`. That matches what the C++ compiler produces.

**Comment by agocke** [comment] 2023-03-07 23:38
You're right, `strp` is emitted by C++. But this is still bothering me because `DW_FORM_string` is listed under the appendix directly in examples of a valid `DW_TAG_compile_unit`. There must be something else wrong here...

**Closed** 2023-03-08 03:55 UTC
Labels: area-NativeAOT-coreclr
