### ISSUE TITLE
IEEE754 approximation even on very simple calculation

### ISSUE THREAD

**Issue by mdesalvo** [dotnet/runtime#80500] opened 2023-01-11 14:30 UTC
Hi,
I wrote this little code and found that IEEE754 approximation occurs even on apparently very simple calculations like this:
```csharp
double value = 5.1 * 25;
Console.Write(value);

//Prints 127.49999999999999 on .NET 5/6/7
//Prints 127.5 on .NET 4.7.2
```
Can you explain why the two programming platforms performs different on such a trivial aspect?

Regards,
Marco

**Comment by Suchiman** [comment] 2023-01-11 14:37
@mdesalvo there has been a lot of work in .NET (Core) to conform more closely to the IEEE754 spec, even very simple numbers might not be accurately representable in IEEE754: https://github.com/dotnet/runtime/issues/1640#issuecomment-573372350

**Comment by tannergooding** [comment] 2023-01-11 14:46
There is no difference in computation here, only a difference in how the string is displayed. .NET Core 3.0 and later fixed the `ToString` implementation to return a roundtrippable string by default: https://devblogs.microsoft.com/dotnet/floating-point-parsing-and-formatting-improvements-in-net-core-3-0/.

You can see that value hasn't changed by printing `BitConverter.DoubleToInt64Bits(value)` and seeing that the raw underlying bits remain `4638672431819522047` (that is, `0x405F_DFFF_FFFF_FFFF`).

--------------

`float` and `double` are binary based IEEE 754 floating-point values, they can only accurately represent numbers that are multiples of a power of two and within the precision limitations of the given format. Any value that isn't a multiple of a power of two is rounded to the nearest representable value.

In the case of your two values, `25` is exactly representable. However, `5.1` is not and the nearest representable value is actually `5.0999999999999996447286321199499070644378662109375`. It still displays as `5.1` because `5.1` is the value with the least number of significant digits that parses to the exact underlying value `5.0999999999999996447286321199499070644378662109375`.

If you take the actual value that gets represented by `5.1` and multiply it by `25` you get `127.4999999999999911182158029987476766109466552734375`. This is exact computed value is also not exactly representable, so it also rounds and becomes `127.4999999999999857891452847979962825775146484375` as it is closer to that than it is to `127.5`.

The shortest roundtrippable string for this value is then `127.49999999999999` and it is displayed as such because displaying `127.5` is an entirely different value (`127.5` has an underlying bit representation `0x405FE00000000000`, which in this case is one higher than the actual value).

**Comment by tannergooding** [comment] 2023-01-11 14:47
Closing this as answered and by design, but please feel free to ask any further questions/clarifications.

**Closed** 2023-01-11 14:46 UTC
Labels: question, area-System.Numerics
