### ISSUE TITLE
[Mono] TypeLoadException for class with variant interfaces

### ISSUE THREAD

**Issue by martinpotter** [dotnet/runtime#68033] opened 2022-04-14 18:04 UTC
### Description

Due to the changes made in https://github.com/dotnet/runtime/pull/57086, initializing a type with variant interfaces can result in a `TypeLoadException`. The exception only occurs when using the Mono version of the Microsoft.NETCore.App runtime.

### Reproduction Steps

```csharp
public abstract class Foo : IComparable<Foo>, IComparable<Bar>
{
	public abstract int CompareTo(Foo other);
	public abstract int CompareTo(Bar other);
}

public sealed class Bar : Foo
{
	public override int CompareTo(Foo other)
	{
		return 1;
	}

	public override int CompareTo(Bar other)
	{
		return 1;
	}
}
```

Test method:
```csharp
new Bar();
```

### Expected behavior

Program runs without exception.

### Actual behavior

The program throws an exception:

```
Unhandled Exception:
System.TypeLoadException: Recursive type definition detected TypeLoadExceptionBug.Bar
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Recursive type definition detected TypeLoadExceptionBug.Bar
```

### Regression?

Yes. This works as expected when using Mono for net5.0 and net472.

**Comment by lambdageek** [comment] 2022-08-10 20:06
This is the stack while we're trying to initialize `Bar`

```
bt
* thread #1, name = 'tid_103', queue = 'com.apple.main-thread', stop reason = breakpoint 1.1
  * frame #0: 0x0000000102296600 libcoreclr.dylib`mono_class_init_internal(klass=0x000000010040c0d8) at class-init.c:2881:37
    frame #1: 0x000000010228e758 libcoreclr.dylib`mono_class_is_assignable_from_general(klass=0x000000010040c1d8, oklass=0x000000010040c0d8, signature_assignment=0, result=0x000000016fdfba8c, error=0x000000016fdfba38) at class.c:3927:3
    frame #2: 0x000000010228e628 libcoreclr.dylib`mono_class_is_assignable_from_checked(klass=0x000000010040c1d8, oklass=0x000000010040c0d8, result=0x000000016fdfba8c, error=0x000000016fdfba38) at class.c:3902:2
    frame #3: 0x000000010228e5d8 libcoreclr.dylib`mono_class_is_assignable_from_internal(klass=0x000000010040c1d8, oklass=0x000000010040c0d8) at class.c:3839:2
    frame #4: 0x000000010228e1cc libcoreclr.dylib`mono_gparam_is_reference_conversible(target=0x000000010040c1d8, candidate=0x000000010040c0d8, check_for_reference_conv=0) at class.c:3606:7
    frame #5: 0x000000010228aba0 libcoreclr.dylib`mono_class_is_variant_compatible(klass=0x00000001010f4bf8, oklass=0x00000001010f4ad0, check_for_reference_conv=0) at class.c:3654:10
    frame #6: 0x00000001022a5788 libcoreclr.dylib`mono_class_setup_vtable_general(klass=0x000000010040c1d8, overrides=0x0000000000000000, onum=0, in_setup=0x0000600000258180) at class-setup-vtable.c:1811:10
    frame #7: 0x00000001022a4fc4 libcoreclr.dylib`mono_class_setup_vtable_full(klass=0x000000010040c1d8, in_setup=0x0000600000258180) at class-setup-vtable.c:930:2
    frame #8: 0x00000001022a50b8 libcoreclr.dylib`mono_class_setup_vtable(klass=0x000000010040c1d8) at class-setup-vtable.c:859:2
    frame #9: 0x0000000102296d78 libcoreclr.dylib`mono_class_init_internal(klass=0x000000010040c0d8) at class-init.c:3027:4
```

where frame 9 and frame 1 are both trying to set up `Bar`.

When we try to setup the vtable slots, we try to understand if the class directly implements an interface, or if the interface is coming from an ancestor class.  With variant generic params, the class might implement a more specific interface, which we try to understand by doing an "is assignable check" (`mono_class_is_variant_compatible` which is just `mono_class_is_assignable_from_internal`).  The "is assignable" function tries to init the classes.

The problem is that one (or the other) of the generic variants can mention the class we're currently initializing which hits our circular references protection.

I think the "is assignable" check is checking for `m_class_is_inited` and calling `mono_class_init_internal`.  Both of those are too conservative: checking `is_inited` is too strong and `init_internal` is initializing way more than we need to check assignability.

I think all that we care about are `MonoClass:supertypes` and `MonoClass:interface_bitmap`.  Supertypes are fine - we can check and call `mono_class_setup_supertypes`.

The `interface_bitmap` is more problematic - it's set up by `mono_class_setup_interface_offsets_internal` which is also computing the vtable slot offsets for each interface.  We can't really call it until the parent vtable is setup because we need to know the final vtable slot assigned to the parent class.

But for assignability we don't care about _how_ the interface is implemented - the offsets and vtable slots don't matter.  We only care about _if_ the interface is implemented.

I _think_ we can make `mono_class_setup_interface_offsets_internal` run in a mode where it only computes the `interface_bitmap`. this only requires assigning interface IDs, the slot offsets don't matter.

So `is_assignable` can do (for both `klass` and `oklass`):

```
static void
ensure_initialized_for_is_assignable (MonoClass *klass)
{
	if (!m_class_get_supertypes (klass))
		mono_class_setup_supertypes (klass);
	if (!m_class_get_interface_bitmap (klass))
		mono_class_setup_interface_offsets_internal (klass, 0, MONO_SETUP_ITF_OFFSETS_NO_OVERWRITE | MONO_SETUP_ITF_OFFSET_BITMAP_ONLY);
}
```

(we would switch the last arg from `gboolean overwrite` to a `int32_t flags`)

Possibly this will make `is_assignable` more fragile since future changes would need to only access the relevant parts of `MonoClass`

---

I think it's worth trying to fix this for net7

**Closed** 2022-08-13 19:41 UTC
Labels: blocking-release, area-VM-meta-mono, in-pr
