### ISSUE TITLE
A strange TypeLoadException

### ISSUE THREAD

**Issue by pengweiqhca** [dotnet/runtime#72930] opened 2022-07-27 10:29 UTC
I wan't implement a struct tree, but i got a TypeLoadException.

``` C#
Console.WriteLine(typeof(Node)); // throw TypeLoadException

public struct Node
{
    public StructList<Node> Sons;
}
public struct StructList<T>
{
}
```
If is class, it is no problem.

**Comment by huoyaoyuan** [comment] 2022-07-27 11:02
Looks like a duplicate of #72039

**Comment by teo-tsirpanis** [comment] 2022-07-27 11:26
Duplicate of #6924.

**Closed by teo-tsirpanis** 2022-07-27 11:26 UTC
Labels: area-TypeSystem-coreclr, untriaged
