### ISSUE TITLE
`Enumerable.CountBy` enumerates an `IEnumerable` instead of returning it directly

### ISSUE THREAD

**Issue by colejohnson66** [dotnet/runtime#107794] opened 2024-09-13 13:36 UTC
### Description

The new `Enumerable.CountBy` implementation works by building a dictionary, then enumerating the key-value pairs of it, yielding them one-by-one. This generates an unnecessary `IEnumerable` implementation that just yields the dictionary's `IEnumerable` elements. The dictionary should just be returned directly.

https://github.com/dotnet/runtime/blob/1d1bf92fcf43aa6981804dc53c5174445069c9e4/src/libraries/System.Linq/src/System/Linq/CountBy.cs#L30-L43

I would assume this is due to the `using` on the `IEnumerator`, but that could be folded into `BuildCountDictionary`. Afterwards, you can inline `BuildCountDictionary` as the iterator itself. This provides a speedup of 20-40%.

```csharp
private static IEnumerable<KeyValuePair<TKey, int>> CountByIterator<TSource, TKey>(IEnumerable<TSource> source, Func<TSource, TKey> keySelector, IEqualityComparer<TKey>? keyComparer) where TKey : notnull
{
    using IEnumerator<TSource> enumerator = source.GetEnumerator();

    if (!enumerator.MoveNext())
        return Empty<KeyValuePair<TKey, int>>();

    Dictionary<TKey, int> countsBy = new(keyComparer);

    do
    {
        TSource value = enumerator.Current;
        TKey key = keySelector(value);

        ref int currentCount = ref CollectionsMarshal.GetValueRefOrAddDefault(countsBy, key, out _);
        checked
        {
            currentCount++;
        }
    }
    while (enumerator.MoveNext());

    return countsBy;
}
```

### Benchmarks

```
BenchmarkDotNet v0.14.0, Windows 11 (10.0.26100.1591)
Intel Core i9-10900X CPU 3.70GHz, 1 CPU, 20 logical and 10 physical cores
.NET SDK 9.0.100-rc.1.24452.12
  [Host]     : .NET 8.0.8 (8.0.824.36612), X64 RyuJIT AVX-512F+CD+BW+DQ+VL
  DefaultJob : .NET 8.0.8 (8.0.824.36612), X64 RyuJIT AVX-512F+CD+BW+DQ+VL
```

| Method        | N      | Mean           | Error         | StdDev        | Ratio | RatioSD |
|-------------- |------- |---------------:|--------------:|--------------:|------:|--------:|
| DotNetCountBy | 10     |       391.4 ns |       2.34 ns |       2.19 ns |  1.00 |    0.01 |
| MyCountBy     | 10     |       237.7 ns |       1.15 ns |       1.08 ns |  0.61 |    0.00 |
|               |        |                |               |               |       |         |
| DotNetCountBy | 100    |     2,887.8 ns |      56.65 ns |     110.50 ns |  1.00 |    0.05 |
| MyCountBy     | 100    |     2,028.5 ns |      39.09 ns |      56.06 ns |  0.70 |    0.03 |
|               |        |                |               |               |       |         |
| DotNetCountBy | 1000   |    27,274.6 ns |     535.97 ns |     447.56 ns |  1.00 |    0.02 |
| MyCountBy     | 1000   |    18,145.6 ns |     355.44 ns |     563.77 ns |  0.67 |    0.02 |
|               |        |                |               |               |       |         |
| DotNetCountBy | 10000  |   476,448.3 ns |   5,709.73 ns |   5,340.89 ns |  1.00 |    0.02 |
| MyCountBy     | 10000  |   389,465.0 ns |   4,742.66 ns |   4,204.24 ns |  0.82 |    0.01 |
|               |        |                |               |               |       |         |
| DotNetCountBy | 100000 | 5,766,253.5 ns | 114,739.63 ns | 153,174.12 ns |  1.00 |    0.04 |
| MyCountBy     | 100000 | 4,851,790.7 ns |  94,113.17 ns |  96,647.30 ns |  0.84 |    0.03 |

<details><summary>Details</summary>
<p>

```csharp
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Diagnosers;
using BenchmarkDotNet.Running;
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Runtime.InteropServices;

BenchmarkRunner.Run<Benchmarks>();

public class Benchmarks
{
    [Params(10, 100, 1000, 10_000, 100_000)]
    public int N { get; set; }

    private int[] _input = null!;

    private static readonly Func<int, int> Selector = i => i;


    [GlobalSetup]
    public void Setup()
    {
        Random r = new(42);
        _input = Enumerable.Range(0, N).Select(_ => r.Next()).ToArray();
    }


    [Benchmark(Baseline = true)]
    public KeyValuePair<int, int>[] DotNetCountBy() =>
        CountByIterator(_input, Selector, null).ToArray();

    [Benchmark]
    public KeyValuePair<int, int>[] MyCountBy() =>
        MyCountByIterator(_input, Selector, null).ToArray();


    private static IEnumerable<KeyValuePair<TKey, int>> CountByIterator<TSource, TKey>(IEnumerable<TSource> source, Func<TSource, TKey> keySelector, IEqualityComparer<TKey>? keyComparer) where TKey : notnull
    {
        using IEnumerator<TSource> enumerator = source.GetEnumerator();

        if (!enumerator.MoveNext())
        {
            yield break;
        }

        foreach (KeyValuePair<TKey, int> countBy in BuildCountDictionary(enumerator, keySelector, keyComparer))
        {
            yield return countBy;
        }
    }

    private static Dictionary<TKey, int> BuildCountDictionary<TSource, TKey>(IEnumerator<TSource> enumerator, Func<TSource, TKey> keySelector, IEqualityComparer<TKey>? keyComparer) where TKey : notnull
    {
        Dictionary<TKey, int> countsBy = new(keyComparer);

        do
        {
            TSource value = enumerator.Current;
            TKey key = keySelector(value);

            ref int currentCount = ref CollectionsMarshal.GetValueRefOrAddDefault(countsBy, key, out _);
            checked
            {
                currentCount++;
            }
        }
        while (enumerator.MoveNext());

        return countsBy;
    }

    private static IEnumerable<KeyValuePair<TKey, int>> MyCountByIterator<TSource, TKey>(IEnumerable<TSource> source, Func<TSource, TKey> keySelector, IEqualityComparer<TKey>? keyComparer) where TKey : notnull
    {
        using IEnumerator<TSource> enumerator = source.GetEnumerator();

        if (!enumerator.MoveNext())
            return [];

        Dictionary<TKey, int> countsBy = new(keyComparer);

        do
        {
            TSource value = enumerator.Current;
            TKey key = keySelector(value);

            ref int currentCount = ref CollectionsMarshal.GetValueRefOrAddDefault(countsBy, key, out _);
            checked
            {
                currentCount++;
            }
        }
        while (enumerator.MoveNext());

        return countsBy;
    }
}
```

</p>
</details>

**Comment by eiriktsarpalis** [comment] 2024-09-13 13:45
This is intentional, and is there to preserve deferred semantics typical of Linq methods:

```C#
List<string> source = [];
IEnumerable<KeyValuePair<string, int>> wordCount = source.CountBy(word => word);
Console.WriteLine(wordCount.Count()); // 0

source.AddRange(["fizz", "buzz", "fizz"]);
Console.WriteLine(wordCount.Count()); // 2
```

An eager variant would probably have a different name and return type (e.g. `Dictionary<string, int> ToCountDictionary(...)`)

**Comment by eiriktsarpalis** [comment] 2024-09-13 13:49
Also, duplicate of #106110.

**Comment by colejohnson66** [comment] 2024-09-13 13:58
There are no deferred semantics in the current implementation? It eagerly collects the entire source into the dictionary before returning it. There are deferred semantics on *iterating* that dictionary, but not on invocation of `CountBy`.

**Comment by eiriktsarpalis** [comment] 2024-09-13 14:01
It's very much deferred. The fact that it has iterate over the entire source on the first `MoveNext` doesn't change that fact. This is true for any `GroupBy`-like combinator.

**Comment by colejohnson66** [comment] 2024-09-13 14:09
Wait. I see it now. The _source's_ `IEnumerator` is not stepped until the compiler-generator `IEnumerable` in `CountByIterator` is stepped, and my implementation would change that.

**Closed** 2024-09-13 14:11 UTC
Labels: area-System.Collections, tenet-performance, untriaged
