### ISSUE TITLE
HttpClient can never recover from exception in custom IHttpMessageHandlerBuilderFilter 

### ISSUE THREAD

**Issue by ChristophHornung** [dotnet/runtime#107689] opened 2024-09-11 15:40 UTC
### Description

When implementing a custom `IHttpMessageHandlerBuilderFilter` the HttpClientFactory caches any exceptions originating from the custom filter and will forever return that exception.

This is due to the `_entryFactory` in `DefaultHttpClientFactory` basically caching that exceptions without any cleanup in the `Lazy<>`. https://github.com/dotnet/runtime/blob/4267ab8b52cd4953dd563dd99ab10c5f651dccad/src/libraries/Microsoft.Extensions.Http/src/DefaultHttpClientFactory.cs#L26 and since an exception is thrown on `DefaultHttpClientFactory.CreateHandler(string name)` before `StartHandlerEntryTimer` is called this exception is never cleared. https://github.com/dotnet/runtime/blob/4267ab8b52cd4953dd563dd99ab10c5f651dccad/src/libraries/Microsoft.Extensions.Http/src/DefaultHttpClientFactory.cs#L119-L128

### Reproduction Steps

See https://github.com/ChristophHornung/HttpMesageHandlerBuilderFilterDemo for a minimal reproduction

- Create a custom `IHttpMessageHandlerBuilderFilter` that returns an exception on first call
- Register the filter
- Create a HttpClient that triggers that filter (e.g. through an injected HttpClientFactory) repeatedly.

### Expected behavior

Exception occurs only on the exception in the filter and is maybe cached for a certain time afterwards but clears on its own.

### Actual behavior

Exception repeats forever, there is no option to recover from that one-time exception.

### Configuration

.NET8
Windows+Linux (unspecific to configuration)

**Comment by CarnaViire** [comment] 2024-09-11 21:21
Thanks for the report @ChristophHornung!
This is a known issue: https://github.com/dotnet/runtime/issues/80605

It doesn't have to be IHttpMessageHandlerBuilderFilter -- it can be any configuration callback. The design expects the configuration callbacks to be _no-throw_. It aligns with the expectations that Lazy has -- the factory method should be no-throw; otherwise it's assumed that the factory method is faulty and there's no point in calling it again.

There's some discussion in the linked issue: https://github.com/dotnet/runtime/issues/80605#issuecomment-1396085516.
In my opinion, the current behavior is acceptable, but we might decide to address this in future.

As for the current issue, I'll close it as duplicate. Please upvote https://github.com/dotnet/runtime/issues/80605 so we could track the interest. Thanks!

**Comment by CarnaViire** [comment] 2024-09-11 21:21
Duplicate of #80605

**Closed by CarnaViire** 2024-09-11 21:21 UTC
Labels: untriaged, area-Extensions-HttpClientFactory
