### ISSUE TITLE
Test failure BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#67217] opened 2022-03-28 02:24 UTC
Run: [runtime-coreclr libraries-jitstress 20220327.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1684183&view=ms.vss-test-web.build-test-results-tab&runId=46093502&paneView=debug&resultId=173782)

Failed test:
```
net7.0-windows-Release-x64-CoreCLR_checked-jitstress1-Windows.10.Amd64.Open

- BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover

```
**Error message:**
```
Half-way through waiting for remote process.
Memory load: 14

Image Name                     PID Services

========================= ======== ============================================
svchost.exe                    764 BrokerInfrastructure, DcomLaunch, LSM,

PlugPlay, Power, SystemEventsBroker

svchost.exe                    824 RpcEptMapper, RpcSs

svchost.exe                    940 Appinfo, CertPropSvc, DsmSvc, gpsvc,

iphlpsvc, lfsvc, ProfSvc, sacsvr, Schedule,
SENS, SessionEnv, ShellHWDetection, Themes,
UserManager, UsoSvc, Winmgmt, wlidsvc,

WpnService, wuauserv

svchost.exe                    952 TermService

svchost.exe                    336 Dhcp, EventLog, lmhosts, NgcCtnrSvc,

TimeBrokerSvc, vmictimesync

svchost.exe                    424 NcbService, PcaSvc, TrkWks, UALSVC,

UmRdpService, vmickvpexchange,

vmicshutdown, WdiSystemHost

svchost.exe                   1084 CDPSvc, EventSystem, FontCache, netprofm,

nsi, RemoteRegistry, W32Time,

WinHttpAutoProxySvc

svchost.exe                   1100 vmicheartbeat

svchost.exe                   1140 BFE, CoreMessagingRegistrar, DPS, MpsSvc,

pla

svchost.exe                   1348 CryptSvc, Dnscache, LanmanWorkstation,

NlaSvc, WinRM

svchost.exe                   1416 Wcmsvc

svchost.exe                   2028 AppHostSvc

svchost.exe                   1408 StateRepository, tiledatamodelsvc

svchost.exe                   1892 W3SVC, WAS

svchost.exe                   1932 DiagTrack

svchost.exe                   2108 LanmanServer

svchost.exe                   3636 CDPUserSvc_4c08c, OneSyncSvc_4c08c

svchost.exe                   4036 AppReadiness

svchost.exe                   4092 ClipSVC

Timed out at 3/27/2022 8:18:29 AM after 60000ms waiting for remote process.
Wrote mini dump to: C:\h\w\B37C0968\w\A069088A\uploads\3040.vq1og4mr.ajy.dmp
Process ID: 3040
Handle: 1092
Name: dotnet
MainModule: C:\h\w\B37C0968\p\dotnet.exe
StartTime: 3/27/2022 8:17:02 AM
TotalProcessorTime: 00:00:02.3750000
Threads:
Thread #1 (OS 0xBDC)   [MTA]
[HelperMethodFrame] (System.Threading.Thread.SleepInternal)
System.Threading.Thread.Sleep(Int32)
BasicEventSourceTests.TestsManifestGeneration.<Test_EventSource_EtwManifestGenerationRollover>b__6_0()
[DebuggerU2MCatchHandlerFrame]
[HelperMethodFrame_PROTECTOBJ] (System.RuntimeMethodHandle.InvokeMethod)
System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
Microsoft.DotNet.RemoteExecutor.Program.Main(System.String[])
Thread #2 (OS 0x158C) [Finalizer] [Background]
[DebuggerU2MCatchHandlerFrame]


Stack trace
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 224
```

**Comment by tommcdon** [comment] 2022-03-29 22:58
@BruceForstall this seems to be an issue caused by JIT stress, could you do a first-level triage of the test failure?

**Comment by BruceForstall** [comment] 2022-03-30 23:47
@tommcdon I couldn't repro locally with or without stress. And the lab job didn't repro on the next two runs.

My Kusto queries aren't working to find the full test history for this, unfortunately.

Most likely, it is not JitStress related, but because JitStress runs cause tests to run much more frequently (due to a large number of JitStress variations), any existing timing or other "flakiness" in the test or system is made more visible in JitStress jobs.

**Comment by tommcdon** [comment] 2022-04-03 17:46
Closing as we were not able to repro the issue

**Closed by tommcdon** 2022-04-03 17:46 UTC
Labels: area-System.Diagnostics.Tracing, os-windows, JitStress, arch-x64, untriaged
