### ISSUE TITLE
[API Proposal]: Please add a method to the C# library to copy a directory with all its contents

### ISSUE THREAD

**Issue by aks2161989** [dotnet/runtime#61873] opened 2021-11-20 13:04 UTC
Currently C# does not have an inbuilt method to copy a directory and all its contents. To achieve this task, one needs to write code for it. [An example is given on the MSDN website](https://docs.microsoft.com/en-us/dotnet/api/system.io.directoryinfo?redirectedfrom=MSDN&view=net-6.0).

What is strange, however, is that [VB.NET already has an inbuilt method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.fileio.filesystem.copydirectory?view=net-6.0) which allows you to achieve this task in one line. Sure, one can add a reference to `Microsoft.VisualBasic` in their C# project and call the VB.NET method, but I am sure most C# developers would appreciate if such a method were to be incorporated in the language itself.

What's more is that C# has long tried to compete with Java and has succeeded in many aspects. However, [Java already has inbuilt methods to copy a directory and its contents](https://stackoverflow.com/a/1146651/6623360) and does not require extra work to achieve this. If such a feature were to be added to C#, it would definitely enhance the competitiveness of the language.

**Comment by teo-tsirpanis** [comment] 2021-11-20 14:35
Hello, adding such reference is no longer needed in C# projects that target modern .NET. You can add a `using Microsoft.VisualBasic.FileIO` in your code straight away without changing your project file.

**Comment by svick** [comment] 2021-11-20 15:46
This is a duplicate of https://github.com/dotnet/runtime/issues/60903.

**Comment by adamsitnik** [comment] 2021-11-23 08:05
@aks2161989 Thank you for your proposal. Since this is a duplicate, I am going to close the issue. Please follow #60903 for updates.

**Closed by adamsitnik** 2021-11-23 08:05 UTC
Labels: area-System.IO, untriaged
