### ISSUE TITLE
Test failure JIT\\HardwareIntrinsics\\X86\\Bmi2.X64\\Bmi2.X64_ro\\Bmi2.X64_ro.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#66048] opened 2022-03-02 01:27 UTC
Run: [runtime-coreclr outerloop 20220301.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1638161&view=ms.vss-test-web.build-test-results-tab&runId=45340328&resultId=100124&paneView=debug)

Failed test:
```
R2R-CG2 windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open

- JIT\\HardwareIntrinsics\\X86\\Bmi2.X64\\Bmi2.X64_ro\\Bmi2.X64_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Bmi2\\Bmi2_r\\Bmi2_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Bmi2\\Bmi2_ro\\Bmi2_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Bmi2.X64\\Bmi2.X64_r\\Bmi2.X64_r.cmd

```
**Error message:**
```
Could Not Find C:\h\w\AC2F0917\w\C48F0A8F\e\JIT\HardwareIntrinsics\X86\Bmi2.X64\Bmi2.X64_ro\IL-CG2\composite-r2r.dll
Could Not Find C:\h\w\AC2F0917\w\C48F0A8F\e\JIT\HardwareIntrinsics\X86\Bmi2.X64\Bmi2.X64_ro\Bmi2.X64_ro.dll.rsp
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'System.Security.Cryptography.Primitives, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The module was expected to contain an assembly manifest.
File name: 'System.Security.Cryptography.Primitives, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
at ILCompiler.CoreRTNameMangler.SanitizeNameWithHash(String literal)
at ILCompiler.CoreRTNameMangler.set_CompilationUnitPrefix(String value)
at ILCompiler.Program.RunSingleCompilation(Dictionary2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary2 unrootedInputFilePaths, HashSet`1 versionBubbleModulesHash, CompilerTypeSystemContext typeSystemContext)
at ILCompiler.Program.Run(String[] args)
at ILCompiler.Program.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\AC2F0917\w\C48F0A8F\uploads\Reports\JIT.HardwareIntrinsics\X86\Bmi2.X64\Bmi2.X64_ro\Bmi2.X64_ro.output.txt
Raw output:
BEGIN EXECUTION
Bmi2.X64_ro.dll
TestLibrary.dll
2 file(s) copied.
Response file: C:\h\w\AC2F0917\w\C48F0A8F\e\JIT\HardwareIntrinsics\X86\Bmi2.X64\Bmi2.X64_ro\Bmi2.X64_ro.dll.rsp
C:\h\w\AC2F0917\w\C48F0A8F\e\JIT\HardwareIntrinsics\X86\Bmi2.X64\Bmi2.X64_ro\IL-CG2\Bmi2.X64_ro.dll
-o:C:\h\w\AC2F0917\w\C48F0A8F\e\JIT\HardwareIntrinsics\X86\Bmi2.X64\Bmi2.X64_ro\Bmi2.X64_ro.dll
--targetarch:x64
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\AC2F0917\p\System..dll
-r:C:\h\w\AC2F0917\p\Microsoft..dll
-r:C:\h\w\AC2F0917\p\mscorlib.dll
-r:C:\h\w\AC2F0917\p\netstandard.dll
-O
" "dotnet" "C:\h\w\AC2F0917\p\crossgen2\crossgen2.dll" @"C:\h\w\AC2F0917\w\C48F0A8F\e\JIT\HardwareIntrinsics\X86\Bmi2.X64\Bmi2.X64_ro\Bmi2.X64_ro.dll.rsp"   -r:C:\h\w\AC2F0917\w\C48F0A8F\e\JIT\HardwareIntrinsics\X86\Bmi2.X64\Bmi2.X64_ro\IL-CG2*.dll"
Crossgen2 failed with exitcode - -532462766
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\AC2F0917\p
C:\h\w\AC2F0917\w\C48F0A8F\e\JIT\HardwareIntrinsics\X86\Bmi2.X64\Bmi2.X64_ro\Bmi2.X64_ro.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_HardwareIntrinsics._X86_Bmi2_X64_Bmi2_X64_ro_Bmi2_X64_ro_._X86_Bmi2_X64_Bmi2_X64_ro_Bmi2_X64_ro_cmd()
```

**Comment by tannergooding** [comment] 2022-03-04 18:31
Duplicate of https://github.com/dotnet/runtime/issues/65646

**Closed by tannergooding** 2022-03-04 18:31 UTC
Labels: os-windows, arch-x64, area-crossgen2-coreclr, untriaged, blocking-outerloop
