### ISSUE TITLE
IHost.RunAsync() does not exit on CTRL_+C

### ISSUE THREAD

**Issue by ComponentFactory** [dotnet/runtime#79851] opened 2022-12-20 12:10 UTC
### Description

I am writing a simple console application and using the GenericHost to perform setup. Then I use RunAsync so that the application runs until the user presses CTRL+C. I was intending to use a BackgroundService for actual functionality, but you can reproduce the issue without it.

### Reproduction Steps

    using Microsoft.Extensions.Hosting;

    namespace Example
    {
        class TestClass
        {
            static async Task Main(string[] args)
            {
                IHost host = Host.CreateDefaultBuilder()
                        .UseConsoleLifetime()
                        .Build();

                await host.RunAsync();
            }
        }
    }

### Expected behavior

When run it should show a console window and then when the user presses CTRL+C the application should exit.

### Actual behavior

Shows a console window but pressing CTRL+C does nothing.

### Regression?

Never tried this with previous versions. 
I found this related bug report that provides a workaround. 
That workaround also does not work and does the same thing, ignores CTRL+C.

[IHost.RunAsync() never completes #44086](https://github.com/dotnet/runtime/issues/44086)

### Known Workarounds

None.

### Configuration

.NET Version: 7.0.101
OS: Windows 11
Architecture: x64
IDE: VS Code

**Comment by tmds** [comment] 2022-12-21 07:24
This is reported against Windows. I tried to reproduce it on Linux and the application exits as expected.

**Comment by davidfowl** [comment] 2022-12-21 08:01
I can't reproduce this on windows either. Also, FYI the console lifetime is the default, so you don't need that explicit call. Do you have anymore details?

**Comment by ComponentFactory** [comment] 2022-12-21 12:01
Just discovered that if I run this under Visual Studio 2022 then it works as expected. But under Visual Studio Code it does not.  I am running it with an external terminal as show here in my settings.

`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceFolder}/bin/Debug/net7.0/Temp.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            "console": "externalTerminal",
            "stopAtEntry": false
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach"
        }
    ]
}`

**Comment by ComponentFactory** [comment] 2022-12-21 12:05
It also works if I run the executable from a command line. It seems to be only in Visual Studio Code when running as Debug. I can live with that!

**Comment by buyaa-n** [comment] 2022-12-21 17:32
Sounds like we can close it now

**Closed by buyaa-n** 2022-12-21 17:32 UTC
Labels: untriaged, area-Extensions-Hosting
