### ISSUE TITLE
Test failed: eventpipe_readevents "A callback was made on a garbage collected delegate"

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#39682] opened 2020-07-21 01:37 UTC
`Linux {x64,arm64}` x `GCStress=C` x `{JitStress=1,Jitstress=2}`

https://dev.azure.com/dnceng/public/_build/results?buildId=737350&view=ms.vss-test-web.build-test-results-tab&runId=22834098&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab&resultId=100011

e.g.,
```
export COMPlus_TieredCompilation=0
export COMPlus_DbgEnableMiniDump=1
export COMPlus_DbgMiniDumpName=$HELIX_DUMP_FOLDER/coredump.%d.dmp
export COMPlus_GCStress=0xC
export COMPlus_JitStress=2
+ sudo bash -c echo $HELIX_DUMP_FOLDER/core.%u.%p > /proc/sys/kernel/core_pattern
+ export PATH=/home/helixbot/work/AC910984/p/dotnet:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
+ export DOTNET_ROOT=/home/helixbot/work/AC910984/p/dotnet
+ export DOTNET_CLI_TELEMETRY_OPTOUT=1
+ dotnet /home/helixbot/work/AC910984/p/xunit.console.dll profiler/eventpipe/profiler.eventpipe.XUnitWrapper.dll -parallel collections -nocolor -noshadow -xml testResults.xml -trait TestGroup=profiler.eventpipe
Microsoft.DotNet.XUnitConsoleRunner v2.5.0 (64-bit .NET 5.0.0-preview.8.20361.2)
  Discovering: profiler.eventpipe.XUnitWrapper
  Discovered:  profiler.eventpipe.XUnitWrapper
  Starting:    profiler.eventpipe.XUnitWrapper
    profiler/eventpipe/eventpipe_readevents/eventpipe_readevents.sh [FAIL]
      Process terminated. A callback was made on a garbage collected delegate of type 'System.Private.CoreLib!Interop+Advapi32+EtwEnableCallback::Invoke'.
      Unhandled exception. System.Exception: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
         at Profiler.Tests.ProfilerTestRunner.LogTestFailure(String error) in /Users/runner/work/1/s/src/tests/profiler/common/ProfilerTestRunner.cs:line 136
         at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions) in /Users/runner/work/1/s/src/tests/profiler/common/ProfilerTestRunner.cs:line 90
         at EventPipeTests.EventPipe.Main(String[] args) in /Users/runner/work/1/s/src/tests/profiler/eventpipe/eventpipe_readevents.cs:line 55
      /home/helixbot/work/AC910984/w/A5BB094C/e/profiler/eventpipe/eventpipe_readevents/eventpipe_readevents.sh: line 333: 24671 Aborted                 $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      
      Return code:      1
```

**Comment by jkotas** [comment] 2020-07-21 02:28
> A callback was made on a garbage collected delegate of type 'System.Private.CoreLib!Interop+Advapi32+EtwEnableCallback::Invoke'

This looks like a bug in EtwEventProvider.

**Comment by tommcdon** [comment] 2020-07-21 02:34
@davmason

**Comment by BruceForstall** [comment] 2020-07-26 18:00
Failed again:
https://dev.azure.com/dnceng/public/_build/results?buildId=745918&view=ms.vss-test-web.build-test-results-tab&runId=23119792&resultId=100012&paneView=debug

**Comment by davmason** [comment] 2020-07-31 00:10
Looking now, fairly sure it's a duplicate of #36028

**Closed** 2020-07-31 23:48 UTC
Labels: GCStress, JitStress, area-Diagnostics-coreclr, os-linux
