### ISSUE TITLE
Invoking ReadOnlySpan's indexer from Reflection.Emit fails with MissingMethodException

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/runtime#45283] opened 2020-11-27 18:58 UTC
### Description

Consider the following piece of code:

``` csharp
using System;
using System.Reflection;
using System.Reflection.Emit;

var asmBuilder = AssemblyBuilder.DefineDynamicAssembly(
    new AssemblyName("MyDynamicAssemblyName"),
    AssemblyBuilderAccess.RunAndCollect);
var modBuilder = asmBuilder.DefineDynamicModule("MainModule");

var typeBuilder = modBuilder.DefineType("MyImplementation");
typeBuilder.AddInterfaceImplementation(typeof(IMyInterface));

var methodBuilder = typeBuilder.DefineMethod(nameof(IMyInterface.GetFirst),
    MethodAttributes.Public | MethodAttributes.Virtual,
    typeof(object), new[] { typeof(ReadOnlySpan<object>) });

var ilg = methodBuilder.GetILGenerator();
ilg.Emit(OpCodes.Ldarga_S, (byte)1);
ilg.Emit(OpCodes.Ldc_I4_0);
ilg.Emit(OpCodes.Call, typeof(ReadOnlySpan<object>).GetProperty("Item").GetGetMethod());
ilg.Emit(OpCodes.Ldind_Ref);
ilg.Emit(OpCodes.Ret);

var concreteType = typeBuilder.CreateType();

var myIntf = (IMyInterface)Activator.CreateInstance(concreteType);

ReadOnlySpan<object> xs = new object[] { "Hello", "World" };

Console.WriteLine(myIntf.GetFirst(xs));

public interface IMyInterface
{
    object GetFirst(ReadOnlySpan<object> x);
}
```

It dynamically generates the method `public object GetFirst(ReadOnlySpan<object> x) => x[0];` and executes it. The program is expected to print `Hello`.

However, it fails with the following exception at the line where our dynamic method is invoked:

```
System.MissingMethodException: Method not found: '!0 ByRef System.ReadOnlySpan`1.get_Item(Int32)'.
   at MyImplementation.GetFirst(ReadOnlySpan`1 )
   at <Program>$.<Main>$(String[] args) in Program.cs:line 30
```

### Configuration

The issue is reproduced in .NET 5, .NET Core 3.1 and .NET Framework 4.8 (with the latest version of `System.Memory` installed).

### Regression?

No

### Other information

* The issue does __not__ reproduce if we use these types instead of `ReadOnlySpan<object>`
    * `Span<object>`
    * `System.Collections.Generic.List<object>`, after appropriate adjustments to the method's IL (`ldarg` instead of `ldarga` and removing the `ldind` after the indexer call).
* It however __does__ reproduce if we use `ReadOnlySpan<int>` or `ReadOnlySpan<string>`.
* The compiler compiles the indexer call to ``call instance !0& [...] [System.Private.CoreLib]System.ReadOnlySpan`1<object>::get_Item(int32)``. I noticed that the `<object>` is absent from the method's name in the exception message. Is the `ILGenerator` not emitting the correct method for some reason?
    * After saving the dynamic assembly on .NET Framework however, the decompiled IL is identical to what the compiler would emit.

**Comment by MichalStrehovsky** [comment] 2020-11-27 20:25
`ReadOnlySpan<T>.get_Item` has a custom modifier on the return type to signify that the `ref` is `readonly` so this is likely the same issue as #45102 and related.

```
.method public hidebysig specialname 
	instance !T& modreq(System.Runtime.InteropServices.InAttribute) get_Item (
		int32 index
	) cil managed aggressiveinlining 
{
    // ...
}
```

**Comment by teo-tsirpanis** [comment] 2020-11-28 00:05
### Workaround

We can write a helper class:

``` csharp
using System;
using System.Runtime.CompilerServices;

internal static class ReadOnlySpanOfObjectIndexer {
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    internal static ref readonly object GetItem(ref ReadOnlySpan<object> span, int idx) => ref span[idx];
}
```

Now, instead of `call`ing the span's indexer, we will `call` the `GetItem` method of the helper class we just created. Its calling semantics are identical to the indexer; when the issue is fixed, we will replace it back with the indexer, without changing any IL.

---

Another workaround that worked is to use `Span`'s indexer on the `ReadOnlySpan`, but I am wary of the destroyed type safety and do not recommend it.

**Comment by krwq** [comment] 2021-03-03 13:56
@teo-tsirpanis I'll close this issue as a dup of #45102 for now. Once the issue is closed and you're still seeing the issue please reopen or recreate it.

**Closed by krwq** 2021-03-03 13:56 UTC
Labels: area-System.Reflection.Emit, untriaged
