### ISSUE TITLE
[API Proposal]: Let me define serialisation strings for enum values with AOT

### ISSUE THREAD

**Issue by ygoe** [dotnet/runtime#98188] opened 2024-02-08 21:58 UTC
### Background and motivation

When serialising enum values to JSON, they will be written as their numeric value. And also read again from the numeric value. To keep things more readable, I prefer the enum name in most cases, serialised as a string. This is supported via `JsonSerializerOptions` and `JsonStringEnumConverter(JsonNamingPolicy.CamelCase)` nicely. But it generates that nasty warning when using AOT compilation for the project. I've learned that those warnings cannot be resolved and if they appear, this is a dead end. So there is probably an attribute for each enum value required to declare its JSON value explicitly, just like for class properties.

### API Proposal

```csharp
public enum MyEnum
{
    [JsonEnumValue("valueA")]
    ValueA,
    [JsonEnumValue("valueB")]
    ValueB,
    [JsonEnumValue("whatever")]
    ValueC
}
```

### API Usage

```csharp
public class MyClass
{
    [JsonPropertyName("enum")]
    MyEnum Enum;
}

JsonSerializer.Serialize(myClass, SourceGenerationContext.Default.MyClass);
```

### Alternative Designs

Code all conversions between string and enum myself, and define the JSON structure with a string property. Needs conversions whenever the value is needed as enum value. A lot of work and needs to be updated as well every time the enum is changed.

### Risks

None. This is a new optional feature, nobody is using it yet.

**Comment by martincostello** [comment] 2024-02-08 22:13
One approach that works today is to annotate the properties with a custom converter that lets you control the behaviour.

Here's an example from an application of mine which is published using native AoT: https://github.com/martincostello/alexa-london-travel/blob/02ffba731c7d08115eded8dfd50fa0c98ddab15b/src/LondonTravel.Skill/Models/Request.cs#L34

**Comment by gregsdennis** [comment] 2024-02-08 22:43
Seems to be a duplicate of https://github.com/dotnet/runtime/issues/74385.

**Comment by eiriktsarpalis** [comment] 2024-02-09 09:46
Duplicate of #74385.

**Closed by eiriktsarpalis** 2024-02-09 09:46 UTC
Labels: api-suggestion, area-System.Text.Json, untriaged
