### ISSUE TITLE
[HTTP/3] Support NativeAOT on Windows

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#73291] opened 2022-08-03 11:11 UTC
HTTP/3 should be supported also in NativeAOT scenario on Windows.

Linux is simple as msquic is "part of OS" - external package that is prereq for HTTP/3 to work.
On Windows, we build and include msquic.dll as part of .NET Runtime.

@vitek-karas or @MichalStrehovsky can point us to what needs to happen to make it work.
cc @jkotas

Related to Single-file support in #73290

**Comment by karelz** [comment] 2022-08-03 11:12
Triage: We discussed with @vitek-karas that such work should be part of 8.0 -- it is too late for 7.0 and the usage of HTTP/3 is not that much widespread yet.

**Comment by jkotas** [comment] 2022-08-03 13:25
We do not need to a separate issue tracking this for NativeAOT. The solution and the work required to make it happen should be 95% same between singlefilehost and NativeAOT. 

Duplicate of https://github.com/dotnet/runtime/issues/73290

**Closed by jkotas** 2022-08-03 13:25 UTC
Labels: enhancement, area-System.Net.Http
