### ISSUE TITLE
[native aot] Unhandled exceptions are not printed to console

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#91298] opened 2023-08-29 23:40 UTC
Compile and run with nativeaot on current main:

```
throw new Exception("My unhandled exception");
```

## Expected result

Unhandled exception message is printed to console.

## Actual result

No message printed to console

**Comment by jkotas** [comment] 2023-08-29 23:41
Looks like a regression from https://github.com/dotnet/runtime/pull/88034. @janvorli Could you please take a look?

**Comment by janvorli** [comment] 2023-08-30 20:33
The problem is really caused by the #88034, specifically by moving the
https://github.com/dotnet/runtime/blob/fecf3eeffd3650566555e15292f9df0d3abcdfc6/src/coreclr/nativeaot/Runtime.Base/src/System/Runtime/ExceptionHandling.cs#L711-L712
from after to before the 
https://github.com/dotnet/runtime/blob/fecf3eeffd3650566555e15292f9df0d3abcdfc6/src/coreclr/nativeaot/Runtime.Base/src/System/Runtime/ExceptionHandling.cs#L716-L717

It results in call to the `UnhandledExceptionFailFastViaClasslib` with `prevOriginalPC` that's one level up the call stack, in the native `wmain`. That further causes the `InternalCalls.RhpGetClasslibFunctionFromCodeAddress` to return null, as the address is not in managed code.

I can make this part of the change specific to coreclr, that fixes the problem. However, I would like to check what was the reason for moving it, it seems that for coreclr the only place where it  matters is the arm64 code path here:
https://github.com/dotnet/runtime/blob/fecf3eeffd3650566555e15292f9df0d3abcdfc6/src/coreclr/nativeaot/Runtime.Base/src/System/Runtime/ExceptionHandling.cs#L818-L820

**Closed** 2023-09-05 02:08 UTC
Labels: in-pr, area-NativeAOT-coreclr
