### ISSUE TITLE
VerificationException with reflection, static abstract interface methods, and generic constraints

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#73658] opened 2022-08-09 22:00 UTC
This:
```C#
internal static class Program
{
    static void Main()
    {
        Type s = typeof(Program).Assembly.GetType("Outer`1+Inner");
        Type i = s.GetInterface("IStatics");
        s.GetInterfaceMap(i);
    }
}

class Outer<TOuter>
{
    struct Inner : IStatics
    {
        public static void M<TInner>() where TInner : IConstraint { }
    }

    interface IStatics
    {
        static abstract void M<TInner>() where TInner : IConstraint;
    }

    interface IConstraint { }
}
```
throws:
```
Unhandled exception. System.Security.VerificationException: Method Outer`1+Inner[TOuter].M: type argument 'TInner' violates the constraint of type parameter 'TInner'.
   at System.RuntimeType.GetInterfaceMap(Type ifaceType)
```
Is that expected?

**Comment by mangod9** [comment] 2022-08-10 03:25
@trylek / @davidwrighton if this is expected?

**Comment by trylek** [comment] 2022-08-10 19:38
I'll take a look later today once I'm done with another SVM-related bug.

**Comment by mangod9** [comment] 2022-08-15 20:46
moving to 8 to reduce churn at this point.

**Comment by danmoseley** [comment] 2022-08-15 22:11
@Silkfire you marked thumbs down. Is this issue affecting you?

**Comment by silkfire** [comment] 2022-08-16 03:49
Not directly. It was more to show support to those people who were hoping this would be fixed in the upcoming .NET version.

**Comment by aepot** [comment] 2022-08-21 15:11
> Is that expected?

> 8.0.0

@mangod9 Is it really more than one year needed to say is that expected or bug? :) Sorry if I've misinterpreted the milestone assign.

I was affected by the issue on .NET 7 (p7). Nothing serious but just curious what was that.

**Comment by trylek** [comment] 2022-08-21 15:42
I believe the issue is a bug. The milestone change just means that it's too late in .NET 7 release cycle to fix this especially as we haven't yet identified the correct fix. Once the fix is understood we may be able to fix this in a servicing release.

**Comment by cemahseri** [comment] 2022-11-07 10:47
You guys had 3 months to fix this and you just moved it to the next .NET release to keep this bug in the .NET 7 for 1 year? I hope that I am mistaken and nobody just bothered to update this issue. This bug was posted in [this](https://devblogs.microsoft.com/dotnet/announcing-dotnet-7-preview-7/#comment-16191) .NET blog by Marko Stupar 3 months ago.

**Comment by Joe4evr** [comment] 2022-11-25 19:03
Welp, I hit this today.

Not *that* big a deal for me, since this was an exploratory slab of code, but now I know this behavior is a bug and what I had expected it to do is likely what I want. Shame there's not a clear timeframe on the fix yet, but oh well.

**Closed** 2023-07-19 21:53 UTC
Labels: area-TypeSystem-coreclr, in-pr
