### ISSUE TITLE
There's gotta be a way for array to be able to store an unlimited amount of data with one final exception that say it can not, so https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Convert.cs,e54b8e5a7f9d845a doesn't have to throw an exception here for example

### ISSUE THREAD

**Issue by THATCHAPANJAIHAN** [dotnet/runtime#91450] opened 2023-09-01 04:58 UTC
There's gotta be a way for array to be able to store an unlimited amount of data with one final exception that say it can not, so https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Convert.cs,e54b8e5a7f9d845a doesn't have to throw an exception here for example

If we make byte[] to have unlimited amount of bytes it means we can use more than 2^32 bytes in 32bit system, it's possible we just gotta implement array differently

what's other people's opinion here

_Originally posted by @Xyncgas in https://github.com/dotnet/runtime/discussions/91448_

**Comment by GrabYourPitchforks** [comment] 2023-09-01 06:15
Likely dupe of https://github.com/dotnet/runtime/issues/12221. (That issue deals with arrays and this issue deals with strings, but it's going to be an identical discussion.)

**Comment by jkotas** [comment] 2023-09-03 02:57
Duplicate of #12221.

**Closed by jkotas** 2023-09-03 02:57 UTC
Labels: area-System.Runtime, untriaged
