### ISSUE TITLE
regression on binary-trees regression in 5.0

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#60659] opened 2021-10-19 22:44 UTC
Our[ current result,](https://benchmarksgame-team.pages.debian.net/benchmarksgame/fastest/csharp.html) based on 5.0 (so year old bits) is 
![image](https://user-images.githubusercontent.com/6385855/138000267-73c734fd-7251-4d5c-8fe7-939d90164270.png)

Last Aug 2020 or so I took a screenshot, and we were here
![image](https://user-images.githubusercontent.com/6385855/138000373-7a20b10e-cddf-42ae-9e8f-235737ebfde1.png)

I'm including Java here just to demonstrate the hardware hasn't changed. Our benchmark [implementation ](https://github.com/dotnet/performance/blob/c3336e92a87f52fdff336f583acfb67de6968470/src/benchmarks/micro/runtime/BenchmarksGame/binarytrees-2.cs) is essentially the same as the official one, but made single threaded.  Note that didn't change since at least 2017, the only variable is the .NET version.

Did we really regress 3.1->5.0? And did this regression persist to 6.0? 

Was there a regression that only shows up in the parallelized version? Is that stable enough to be able to include in our perf repo alongside the single threaded one?

Again using Java as a benchmark, we get the same result on Fasta and are leading on[ all other scenarios](https://benchmarksgame-team.pages.debian.net/benchmarksgame/fastest/csharp.html). binary-trees the curious outlier.

**Comment by JulieLeeMSFT** [comment] 2021-11-01 17:50
CC @mangod9 on Memory allocation regression.

**Comment by JulieLeeMSFT** [comment] 2021-11-01 17:53
CC @AndyAyersMS @kunalspathak have you seen this kind of regression in your perf triage?

**Comment by kunalspathak** [comment] 2021-11-01 19:53
This benchmark is very noisy and I don't see anything obvious from the historic graphs:
Ubuntu:
- BinaryTrees_2: https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_ubuntu%2018.04%2fBenchmarksGame.BinaryTrees_2.RunBench.html
- BinaryTrees_5: https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_ubuntu%2018.04%2fBenchmarksGame.BinaryTrees_5.RunBench.html
- BinaryTrees_6: https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_ubuntu%2018.04%2fBenchmarksGame.BinaryTrees_6.RunBench.html (this in fact shows improvement around sept 2021)

Windows:
- BinaryTrees_2: https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_Windows%2010.0.18362%2fBenchmarksGame.BinaryTrees_2.RunBench.html
- BinaryTrees_5: https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_Windows%2010.0.18362%2fBenchmarksGame.BinaryTrees_5.RunBench.html
- BinaryTrees_6: https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_Windows%2010.0.18362%2fBenchmarksGame.BinaryTrees_6.RunBench.html

**Comment by JulieLeeMSFT** [comment] 2021-11-02 16:32
@kunalspathak on windows, .NET5 is 139.6 ms and .NET6 is 584.77ms, which means .NET6 is 4 times slower? It seems like it was that way since Nov 2020. I see the same trend in Ubuntu.
We didn't compare perf between .NET 5 and .NET 6? That's why we dind't notice it?

**Comment by kunalspathak** [comment] 2021-11-02 16:52
> NET5 is 139.6 ms and .NET6 is 584.77ms, which means .NET6 is 4 times slower?

Could you confirm where you see those numbers? Are they in the graph that I pointed above?

> We didn't compare perf between .NET 5 and .NET 6? That's why we dind't notice it?

@adamsitnik did that exercise towards the end of .NET 6.

**Comment by adamsitnik** [comment] 2021-11-02 17:46
The data that I got showed no regression:

<details>

## BenchmarksGame.BinaryTrees_6.RunBench

| Result |          Base |          Diff | Ratio | Alloc Delta | Modality | Operating System        | Bit   | Processor Name                                  | Base V        | Diff V      |
| ------ | -------------:| -------------:| -----:| -----------:| -------- | ----------------------- | ----- | ----------------------------------------------- | ------------- | ------------ |
| Same   |  477487400.00 |  485109600.00 |  0.98 |          +0 | bimodal  | Windows 10.0.19043.1165 | X64   | AMD Ryzen Threadripper PRO 3945WX 12-Cores      | 5.0.921.35908 | 6.0.21.41701|
| Same   |  578757350.00 |  659284150.00 |  0.88 |          +0 | bimodal  | Windows 10.0.20348      | X64   | AMD EPYC 7452                                   | 5.0.921.35908 | 6.0.21.41701|
| Same   |  623956800.00 |  559319650.00 |  1.12 |          +0 | bimodal  | Windows 10.0.20348      | X64   | AMD EPYC 7452                                   | 5.0.921.35908 | 6.0.21.41701|
| Same   |  543432500.00 |  522932150.00 |  1.04 |          +0 | several? | Windows 10.0.18363.1621 | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz               | 5.0.921.35908 | 6.0.21.41701|
| Same   |  697091470.53 |  743406165.57 |  0.94 |          +0 | bimodal  | Windows 8.1             | X64   | Intel Core i7-3610QM CPU 2.30GHz (Ivy Bridge)   | 5.0.921.35908 | 6.0.21.45401|
| Slower |  675280400.00 |  841954750.00 |  0.80 |          +0 |          | Windows 10.0.19042.685  | X64   | Intel Core i7-5557U CPU 3.10GHz (Broadwell)     | 5.0.921.35908 | 6.0.21.41701|
| Same   |  560524200.00 |  595314050.00 |  0.94 |          +0 | several? | Windows 10.0.19043.1165 | X64   | Intel Core i7-6700 CPU 3.40GHz (Skylake)        | 5.0.921.35908 | 6.0.21.41701|
| Same   |  863393800.00 |  895129300.00 |  0.96 |       +3432 | several? | Windows 10.0.22454      | X64   | Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R)   | 5.0.921.35908 | 6.0.21.41701|
| Same   |  484466800.00 |  506583350.00 |  0.96 |       +5728 |          | Windows 10.0.22451      | X64   | Intel Core i7-8700 CPU 3.20GHz (Coffee Lake)    | 5.0.921.35908 | 6.0.21.41701|
| Same   |  539266900.00 |  540120000.00 |  1.00 |          +0 | several? | Windows 10.0.19042.1165 | X64   | Intel Core i9-9900T CPU 2.10GHz                 | 5.0.921.35908 | 6.0.21.41701|
| Slower | 1353584205.48 | 1600877594.99 |  0.85 | -1087731064 | bimodal  | Windows 7 SP1           | X64   | Intel Core2 Duo CPU T9600 2.80GHz               | 5.0.721.25508 | 6.0.21.41701|
| Same   |  493831170.50 |  510266422.00 |  0.97 |          +0 |          | centos 8                | X64   | AMD EPYC 7452                                   | 5.0.921.35908 | 6.0.21.41701|
| Same   |  490793350.00 |  496369300.00 |  0.99 |          +0 |          | debian 10               | X64   | AMD EPYC 7452                                   | 5.0.921.35908 | 6.0.21.41701|
| Same   |  357474904.50 |  360366314.50 |  0.99 |          +0 |          | rhel 7                  | X64   | AMD EPYC 7452                                   | 5.0.921.35908 | 6.0.21.41701|
| Same   |  500140648.00 |  502786327.50 |  0.99 |          +0 |          | sles 15                 | X64   | AMD EPYC 7452                                   | 5.0.921.35908 | 6.0.21.41701|
| Same   |  505722332.00 |  493255046.00 |  1.03 |          +0 |          | opensuse-leap 15.3      | X64   | AMD EPYC 7452                                   | 5.0.921.35908 | 6.0.21.41701|
| Same   |  755450989.50 |  751498813.50 |  1.01 |          +0 | bimodal  | ubuntu 18.04            | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz               | 5.0.921.35908 | 6.0.21.41701|
| Same   |  929910988.00 |  978732102.00 |  0.95 |          +0 |          | ubuntu 18.04            | X64   | Intel Core i7-2720QM CPU 2.20GHz (Sandy Bridge) | 5.0.921.35908 | 6.0.21.41701|
| Same   |  568505050.00 |  587315700.00 |  0.97 |          +0 | several? | alpine 3.13             | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      | 5.0.921.35908 | 6.0.21.41701|
| Same   |  896637348.50 |  953055162.00 |  0.94 |          +0 | bimodal  | ubuntu 16.04            | Arm64 | Unknown processor                               | 5.0.421.11614 | 6.0.21.41701|
| Same   |  695905850.00 |  760835850.00 |  0.91 |          +0 | bimodal  | Windows 10.0.19043.1165 | Arm64 | Microsoft SQ1 3.0 GHz                           | 5.0.921.35908 | 6.0.21.41701|
| Slower |  744402900.00 | 1187491450.00 |  0.63 |          +0 | bimodal  | Windows 10.0.22000      | Arm64 | Microsoft SQ1 3.0 GHz                           | 5.0.921.35908 | 6.0.21.41701|
| Same   |  472382750.00 |  452167200.00 |  1.04 |          +0 | bimodal  | Windows 10.0.19043.1165 | X86   | AMD Ryzen Threadripper PRO 3945WX 12-Cores      | 5.0.921.35908 | 6.0.21.41701|
| Same   |  513245250.00 |  513795100.00 |  1.00 |          +0 |          | Windows 10.0.18363.1621 | X86   | Intel Xeon CPU E5-1650 v4 3.60GHz               | 5.0.921.35908 | 6.0.21.41701|
| Same   |  696864850.00 |  719292200.00 |  0.97 |          +0 | several? | Windows 10.0.19043.1165 | Arm   | Microsoft SQ1 3.0 GHz                           | 5.0.921.35908 | 6.0.21.41701|
| Faster | 1277441245.00 | 1084677065.50 |  1.18 |      +13704 |          | macOS Big Sur 11.5.2    | X64   | Intel Core i5-4278U CPU 2.60GHz (Haswell)       | 5.0.921.35908 | 6.0.21.41701|
| Same   |  769302829.00 |  800307871.50 |  0.96 |          +0 |          | macOS Big Sur 11.5.2    | X64   | Intel Core i7-4870HQ CPU 2.50GHz (Haswell)      | 5.0.921.35908 | 6.0.21.41701|
| Same   |  913774369.50 |  927871350.50 |  0.98 |          +0 | several? | macOS Big Sur 11.4      | X64   | Intel Core i7-5557U CPU 3.10GHz (Broadwell)     | 5.0.921.35908 | 6.0.21.41701|

## BenchmarksGame.BinaryTrees_5.RunBench

| Result |         Base |         Diff | Ratio | Alloc Delta | Modality | Operating System        | Bit   | Processor Name                                  | Base V        | Diff V      |
| ------ | ------------:| ------------:| -----:| -----------:| -------- | ----------------------- | ----- | ----------------------------------------------- | ------------- | ------------ |
| Same   | 103783875.00 | 107741750.00 |  0.96 |          +0 |          | Windows 10.0.19043.1165 | X64   | AMD Ryzen Threadripper PRO 3945WX 12-Cores      | 5.0.921.35908 | 6.0.21.41701|
| Slower |  99638400.00 | 115035100.00 |  0.87 |          +0 | bimodal  | Windows 10.0.20348      | X64   | AMD EPYC 7452                                   | 5.0.921.35908 | 6.0.21.41701|
| Same   | 119910950.00 | 110980300.00 |  1.08 |          +0 |          | Windows 10.0.20348      | X64   | AMD EPYC 7452                                   | 5.0.921.35908 | 6.0.21.41701|
| Same   | 107363375.00 | 106249950.00 |  1.01 |          +0 |          | Windows 10.0.18363.1621 | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz               | 5.0.921.35908 | 6.0.21.41701|
| Same   | 163634233.90 | 168716797.68 |  0.97 |          +0 |          | Windows 8.1             | X64   | Intel Core i7-3610QM CPU 2.30GHz (Ivy Bridge)   | 5.0.921.35908 | 6.0.21.45401|
| Slower | 125110000.00 | 156628950.00 |  0.80 |          +0 | several? | Windows 10.0.19042.685  | X64   | Intel Core i7-5557U CPU 3.10GHz (Broadwell)     | 5.0.921.35908 | 6.0.21.41701|
| Same   | 128545600.00 | 135066650.00 |  0.95 |          +0 | several? | Windows 10.0.19043.1165 | X64   | Intel Core i7-6700 CPU 3.40GHz (Skylake)        | 5.0.921.35908 | 6.0.21.41701|
| Same   | 179104200.00 | 204246500.00 |  0.88 |       +2760 |          | Windows 10.0.22454      | X64   | Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R)   | 5.0.921.35908 | 6.0.21.41701|
| Same   | 118261375.00 | 124580600.00 |  0.95 |       +3644 |          | Windows 10.0.22451      | X64   | Intel Core i7-8700 CPU 3.20GHz (Coffee Lake)    | 5.0.921.35908 | 6.0.21.41701|
| Same   | 102816000.00 | 110271200.00 |  0.93 |          +0 |          | Windows 10.0.19042.1165 | X64   | Intel Core i9-9900T CPU 2.10GHz                 | 5.0.921.35908 | 6.0.21.41701|
| Slower | 239549703.07 | 301509256.60 |  0.79 |  -238379328 |          | Windows 7 SP1           | X64   | Intel Core2 Duo CPU T9600 2.80GHz               | 5.0.721.25508 | 6.0.21.41701|
| Same   | 113982177.00 | 109851385.00 |  1.04 |          +0 |          | centos 8                | X64   | AMD EPYC 7452                                   | 5.0.921.35908 | 6.0.21.41701|
| Same   | 112904300.00 | 113618600.00 |  0.99 |          +0 | bimodal  | debian 10               | X64   | AMD EPYC 7452                                   | 5.0.921.35908 | 6.0.21.41701|
| Same   |  79957591.63 |  79410227.13 |  1.01 |          +0 |          | rhel 7                  | X64   | AMD EPYC 7452                                   | 5.0.921.35908 | 6.0.21.41701|
| Same   | 108037429.00 | 112404193.00 |  0.96 |          +0 | several? | sles 15                 | X64   | AMD EPYC 7452                                   | 5.0.921.35908 | 6.0.21.41701|
| Same   | 115317492.00 | 110349054.50 |  1.05 |          +0 | several? | opensuse-leap 15.3      | X64   | AMD EPYC 7452                                   | 5.0.921.35908 | 6.0.21.41701|
| Same   | 185916282.50 | 189734117.00 |  0.98 |          +0 |          | ubuntu 18.04            | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz               | 5.0.921.35908 | 6.0.21.41701|
| Same   | 257345113.00 | 266436661.00 |  0.97 |          +0 |          | ubuntu 18.04            | X64   | Intel Core i7-2720QM CPU 2.20GHz (Sandy Bridge) | 5.0.921.35908 | 6.0.21.41701|
| Same   | 143980000.00 | 142181800.00 |  1.01 |          +0 |          | alpine 3.13             | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      | 5.0.921.35908 | 6.0.21.41701|
| Same   | 164382091.50 | 172262699.75 |  0.95 |          +0 | several? | ubuntu 16.04            | Arm64 | Unknown processor                               | 5.0.421.11614 | 6.0.21.41701|
| Same   | 152879200.00 | 159500200.00 |  0.96 |          +0 |          | Windows 10.0.19043.1165 | Arm64 | Microsoft SQ1 3.0 GHz                           | 5.0.921.35908 | 6.0.21.41701|
| Slower | 171793800.00 | 212239000.00 |  0.81 |          +0 |          | Windows 10.0.22000      | Arm64 | Microsoft SQ1 3.0 GHz                           | 5.0.921.35908 | 6.0.21.41701|
| Same   |  80713350.00 |  80935825.00 |  1.00 |          +0 |          | Windows 10.0.19043.1165 | X86   | AMD Ryzen Threadripper PRO 3945WX 12-Cores      | 5.0.921.35908 | 6.0.21.41701|
| Same   |  89229575.00 |  87009100.00 |  1.03 |          +0 | several? | Windows 10.0.18363.1621 | X86   | Intel Xeon CPU E5-1650 v4 3.60GHz               | 5.0.921.35908 | 6.0.21.41701|
| Same   | 128329800.00 | 125654750.00 |  1.02 |          +0 |          | Windows 10.0.19043.1165 | Arm   | Microsoft SQ1 3.0 GHz                           | 5.0.921.35908 | 6.0.21.41701|
| Faster | 249148857.00 | 215613235.00 |  1.16 |       +2808 |          | macOS Big Sur 11.5.2    | X64   | Intel Core i5-4278U CPU 2.60GHz (Haswell)       | 5.0.921.35908 | 6.0.21.41701|
| Same   | 182150547.00 | 181106082.00 |  1.01 |          +0 |          | macOS Big Sur 11.5.2    | X64   | Intel Core i7-4870HQ CPU 2.50GHz (Haswell)      | 5.0.921.35908 | 6.0.21.41701|
| Same   | 175856438.00 | 172834379.50 |  1.02 |          +0 |          | macOS Big Sur 11.4      | X64   | Intel Core i7-5557U CPU 3.10GHz (Broadwell)     | 5.0.921.35908 | 6.0.21.41701|

## BenchmarksGame.BinaryTrees_2.RunBench

| Result |         Base |         Diff | Ratio | Alloc Delta | Modality   | Operating System        | Bit   | Processor Name                                  | Base V        | Diff V      |
| ------ | ------------:| ------------:| -----:| -----------:| ---------- | ----------------------- | ----- | ----------------------------------------------- | ------------- | ------------ |
| Same   | 101398825.00 |  95175687.50 |  1.07 |          +0 |            | Windows 10.0.19043.1165 | X64   | AMD Ryzen Threadripper PRO 3945WX 12-Cores      | 5.0.921.35908 | 6.0.21.41701|
| Same   | 119087850.00 | 133709600.00 |  0.89 |          +0 |            | Windows 10.0.20348      | X64   | AMD EPYC 7452                                   | 5.0.921.35908 | 6.0.21.41701|
| Same   | 136190300.00 | 127344600.00 |  1.07 |          +0 |            | Windows 10.0.20348      | X64   | AMD EPYC 7452                                   | 5.0.921.35908 | 6.0.21.41701|
| Same   | 115322250.00 | 111622000.00 |  1.03 |          +0 |            | Windows 10.0.18363.1621 | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz               | 5.0.921.35908 | 6.0.21.41701|
| Same   | 160374967.37 | 160899399.60 |  1.00 |          +0 | several?   | Windows 8.1             | X64   | Intel Core i7-3610QM CPU 2.30GHz (Ivy Bridge)   | 5.0.921.35908 | 6.0.21.45401|
| Slower | 160557300.00 | 188765750.00 |  0.85 |          +0 |            | Windows 10.0.19042.685  | X64   | Intel Core i7-5557U CPU 3.10GHz (Broadwell)     | 5.0.921.35908 | 6.0.21.41701|
| Slower | 107883200.00 | 127435450.00 |  0.85 |          +0 |            | Windows 10.0.19043.1165 | X64   | Intel Core i7-6700 CPU 3.40GHz (Skylake)        | 5.0.921.35908 | 6.0.21.41701|
| Slower | 137892750.00 | 163439850.00 |  0.84 |        +816 | several?   | Windows 10.0.22454      | X64   | Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R)   | 5.0.921.35908 | 6.0.21.41701|
| Same   |  99755812.50 |  94449400.00 |  1.06 |        +240 |            | Windows 10.0.22451      | X64   | Intel Core i7-8700 CPU 3.20GHz (Coffee Lake)    | 5.0.921.35908 | 6.0.21.41701|
| Same   | 103560325.00 | 100185125.00 |  1.03 |          +0 |            | Windows 10.0.19042.1165 | X64   | Intel Core i9-9900T CPU 2.10GHz                 | 5.0.921.35908 | 6.0.21.41701|
| Slower | 336578092.36 | 424956957.99 |  0.79 |  -238376384 | bimodal    | Windows 7 SP1           | X64   | Intel Core2 Duo CPU T9600 2.80GHz               | 5.0.721.25508 | 6.0.21.41701|
| Same   | 173150039.50 | 170965107.00 |  1.01 |          +0 |            | centos 8                | X64   | AMD EPYC 7452                                   | 5.0.921.35908 | 6.0.21.41701|
| Same   | 169863400.00 | 166182200.00 |  1.02 |          +0 |            | debian 10               | X64   | AMD EPYC 7452                                   | 5.0.921.35908 | 6.0.21.41701|
| Same   | 171832927.00 | 183094468.00 |  0.94 |          +0 |            | rhel 7                  | X64   | AMD EPYC 7452                                   | 5.0.921.35908 | 6.0.21.41701|
| Same   | 171727886.00 | 169594506.00 |  1.01 |          +0 |            | sles 15                 | X64   | AMD EPYC 7452                                   | 5.0.921.35908 | 6.0.21.41701|
| Same   | 172567740.00 | 171048105.00 |  1.01 |          +0 |            | opensuse-leap 15.3      | X64   | AMD EPYC 7452                                   | 5.0.921.35908 | 6.0.21.41701|
| Same   | 125771659.00 | 123930044.00 |  1.01 |          +0 |            | ubuntu 18.04            | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz               | 5.0.921.35908 | 6.0.21.41701|
| Same   | 193250058.00 | 188222516.00 |  1.03 |          +0 |            | ubuntu 18.04            | X64   | Intel Core i7-2720QM CPU 2.20GHz (Sandy Bridge) | 5.0.921.35908 | 6.0.21.41701|
| Same   | 136598250.00 | 132598500.00 |  1.03 |          +0 | several?   | alpine 3.13             | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      | 5.0.921.35908 | 6.0.21.41701|
| Same   | 511255580.00 | 511352823.50 |  1.00 |          +0 |            | ubuntu 16.04            | Arm64 | Unknown processor                               | 5.0.421.11614 | 6.0.21.41701|
| Same   | 201628500.00 | 200666050.00 |  1.00 |          +0 |            | Windows 10.0.19043.1165 | Arm64 | Microsoft SQ1 3.0 GHz                           | 5.0.921.35908 | 6.0.21.41701|
| Same   | 223935400.00 | 239460500.00 |  0.94 |          +0 | several?   | Windows 10.0.22000      | Arm64 | Microsoft SQ1 3.0 GHz                           | 5.0.921.35908 | 6.0.21.41701|
| Same   | 108803100.00 | 134795450.00 |  0.81 |          +0 | multimodal | Windows 10.0.19043.1165 | X86   | AMD Ryzen Threadripper PRO 3945WX 12-Cores      | 5.0.921.35908 | 6.0.21.41701|
| Same   | 151231600.00 | 172296425.00 |  0.88 |          +0 | bimodal    | Windows 10.0.18363.1621 | X86   | Intel Xeon CPU E5-1650 v4 3.60GHz               | 5.0.921.35908 | 6.0.21.41701|
| Same   | 209044800.00 | 203458300.00 |  1.03 |          +0 |            | Windows 10.0.19043.1165 | Arm   | Microsoft SQ1 3.0 GHz                           | 5.0.921.35908 | 6.0.21.41701|
| Faster | 267009669.00 | 210462929.50 |  1.27 |       -3072 | several?   | macOS Big Sur 11.5.2    | X64   | Intel Core i5-4278U CPU 2.60GHz (Haswell)       | 5.0.921.35908 | 6.0.21.41701|
| Same   | 158118223.00 | 150985308.50 |  1.05 |          +0 |            | macOS Big Sur 11.5.2    | X64   | Intel Core i7-4870HQ CPU 2.50GHz (Haswell)      | 5.0.921.35908 | 6.0.21.41701|
| Same   | 185869409.00 | 172035965.00 |  1.08 |          +0 | bimodal    | macOS Big Sur 11.4      | X64   | Intel Core i7-5557U CPU 3.10GHz (Broadwell)     | 5.0.921.35908 | 6.0.21.41701|

</details>

**Comment by danmoseley** [comment] 2021-11-02 20:15
Well, perhaps the mystery may be resolved in a couple weeks when they replace 5.0 with 6.0 numbers. I suggest we wait a little bit for that, and if it doesn't go away it might be worth digging a bit more.

**Comment by danmoseley** [comment] 2021-12-13 23:57
Owner of CLBG has said it may be a few months before he can do another round of measurements.

meantime, we have https://programming-language-benchmarks.vercel.app/problem/binarytrees. That shows 6.0 is significantly slower than Java on this test, but doesn't compare 6.0 with 5.0

**Comment by danmoseley** [comment] 2021-12-14 00:04
Looks like the implementation in the PLB above is different to the CLBG ones. There may be room to offer an improved one.

**Comment by adamsitnik** [comment] 2022-04-11 16:33
The benchmark has regressed for the following range of commits: https://github.com/dotnet/runtime/compare/a883caa0803778084167b978281c34db8e753246...c251dbb17b76b23248d25ecca7aa99c3c280dcdc

![image](https://user-images.githubusercontent.com/6011991/162787791-90b2ab12-5a54-4d08-93c9-c92825f555f5.png)

It's very likely caused by the GC regions (cc @mangod9)

https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_Windows%2010.0.18362%2fBenchmarksGame.BinaryTrees_5.RunBench.html

**Comment by mangod9** [comment] 2022-04-11 17:20
Ok thanks, we will take a look. Should we create a separate issue for this since it appears this issue has been tracking other possible issues?

**Comment by BruceForstall** [comment] 2022-05-24 23:53
I think there's nothing left here to investigate, so closing.

**Closed by BruceForstall** 2022-05-24 23:53 UTC
Labels: tenet-performance, tenet-performance-benchmarks, area-CodeGen-coreclr
