### ISSUE TITLE
GetSpecialFolder on macOS returns incorrect folder locations

### ISSUE THREAD

**Issue by MarcoMiltenburg** [dotnet/runtime#100440] opened 2024-03-29 14:46 UTC
### Description

When calling `Environment.GetSpecialFolder()` on macOS the returned folder is incorrect for a number of special folders. The reason is that for a number of folders the special folder `SpecialFolder.Personal` is used as the home directory of the user combined with a specific value. However the folder returned for `SpecialFolder.Personal` is not the the user's home directory but the user's document directory (`CombineDocumentDirectory(string.Empty)`).

### Reproduction Steps

Get the user's desktop folder by calling:
```
var desktopFolder = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
```
This returns: `/Users/username/Documents/Desktop`
But should be: `/Users/username/Desktop`

The same is true for others, like: `SpecialFolder.MyMusic`, `SpecialFolder.MyPictures`, `SpecialFolder.MyVideos`, and `SpecialFolder.ApplicationData`.

### Expected behavior

The returned folder should have the actual user directory as the root. So instead of combining with `GetFolderPathCore(SpecialFolder.Personal, SpecialFolderOption.None)` it should be combined with `GetFolderPathCore(SpecialFolder.UserProfile, SpecialFolderOption.None)`.

### Actual behavior

The wrong folder is used as the user's home directory.

It seems there is no specific macOS implementation of this code but that the code in `Environment.iOS.cs` is used.

### Configuration

Tested on .NET 8.0 on macOS Sonoma 14.4 on an Apple Silicon MacBook Pro.

**Comment by vcsjones** [comment] 2024-03-29 15:04
> It seems there is no specific macOS implementation of this code but that the code in Environment.iOS.cs is used.

I can't reproduce this with a standard macOS application. Are you using a MAUI / Mac Catalyst application?

**Comment by MarcoMiltenburg** [comment] 2024-03-29 17:01
Yes, the target platform is `net8.0-maccatalyst`.

**Comment by am11** [comment] 2024-03-31 18:54
This seems to be by design macOS security feature.

Repro:
```c#
using static System.Environment.SpecialFolder;

Console.WriteLine($"{nameof(ApplicationData)}: {Environment.GetFolderPath(ApplicationData)}");
Console.WriteLine($"{nameof(Desktop)}: {Environment.GetFolderPath(Desktop)}");
Console.WriteLine($"{nameof(Favorites)}: {Environment.GetFolderPath(Favorites)}");
Console.WriteLine($"{nameof(Fonts)}: {Environment.GetFolderPath(Fonts)}");
Console.WriteLine($"{nameof(InternetCache)}: {Environment.GetFolderPath(InternetCache)}");
Console.WriteLine($"{nameof(MyDocuments)}: {Environment.GetFolderPath(MyDocuments)}");
Console.WriteLine($"{nameof(MyMusic)}: {Environment.GetFolderPath(MyMusic)}");
Console.WriteLine($"{nameof(MyPictures)}: {Environment.GetFolderPath(MyPictures)}");
Console.WriteLine($"{nameof(MyVideos)}: {Environment.GetFolderPath(MyVideos)}");
```

On osx-arm64 14.4.1, at first the values of Desktop and MyDocuments were empty:
```yaml
ApplicationData: /Users/am11/Library/Application Support
Desktop: 
Favorites: /Users/am11/Library/Favorites
Fonts: /Users/am11/Library/Fonts
InternetCache: /Users/am11/Library/Caches
MyDocuments: 
MyMusic: /Users/am11/Music
MyPictures: /Users/am11/Pictures
MyVideos: /Users/am11/Movies
```
Enabling Desktop and Documents in Privacy & Security for Terminal:
<img width="465" alt="image" src="https://github.com/dotnet/runtime/assets/3840695/4ec948df-38fa-47fd-9128-c8a8900f962c">
it outputs:
```yaml
ApplicationData: /Users/am11/Library/Application Support
Desktop: /Users/am11/Desktop
Favorites: /Users/am11/Library/Favorites
Fonts: /Users/am11/Library/Fonts
InternetCache: /Users/am11/Library/Caches
MyDocuments: /Users/am11/Documents
MyMusic: /Users/am11/Music
MyPictures: /Users/am11/Pictures
MyVideos: /Users/am11/Movies
```

**Comment by MarcoMiltenburg** [comment] 2024-04-03 06:35
> This seems to be by design macOS security feature.

I don't think this is related. In your output at least the directories are correct. Only when a security feature is turned on they are empty which is fine.

In my case the returned directories are incorrect and non-existent.

**Comment by am11** [comment] 2024-04-04 07:29
You are right, the values returned on macCatalyst and iOS are a bit strange:

```yaml
# net8.0-maccatalyst
ApplicationData: /Users/am11/Library/Containers/com.companyname.app1/Data/Documents/.config
Desktop: /Users/am11/Library/Containers/com.companyname.app1/Data/Documents/Desktop
Favorites: /Users/am11/Library/Containers/com.companyname.app1/Data/Library/Favorites
Fonts: /Users/am11/Library/Containers/com.companyname.app1/Data/Documents/.fonts
InternetCache: /Users/am11/Library/Containers/com.companyname.app1/Data/Library/Caches
MyDocuments: /Users/am11/Library/Containers/com.companyname.app1/Data/Documents
MyMusic: /Users/am11/Library/Containers/com.companyname.app1/Data/Documents/Music
MyPictures: /Users/am11/Library/Containers/com.companyname.app1/Data/Documents/Pictures
MyVideos: /Users/am11/Library/Containers/com.companyname.app1/Data/Documents/Videos

# net8.0-ios
ApplicationData: /Users/am11/Library/Developer/CoreSimulator/Devices/B4FD0CE9-ADEE-45C9-A97D-F74D28384BA8/data/Containers/Data/Application/7FF2BBC9-0749-4E51-92AC-3D6295C01EC6/Documents/.config
Desktop: /Users/am11/Library/Developer/CoreSimulator/Devices/B4FD0CE9-ADEE-45C9-A97D-F74D28384BA8/data/Containers/Data/Application/7FF2BBC9-0749-4E51-92AC-3D6295C01EC6/Documents/Desktop
Favorites: /Users/am11/Library/Developer/CoreSimulator/Devices/B4FD0CE9-ADEE-45C9-A97D-F74D28384BA8/data/Containers/Data/Application/7FF2BBC9-0749-4E51-92AC-3D6295C01EC6/Library/Favorites
Fonts: /Users/am11/Library/Developer/CoreSimulator/Devices/B4FD0CE9-ADEE-45C9-A97D-F74D28384BA8/data/Containers/Data/Application/7FF2BBC9-0749-4E51-92AC-3D6295C01EC6/Documents/.fonts
InternetCache: /Users/am11/Library/Developer/CoreSimulator/Devices/B4FD0CE9-ADEE-45C9-A97D-F74D28384BA8/data/Containers/Data/Application/7FF2BBC9-0749-4E51-92AC-3D6295C01EC6/Library/Caches
MyDocuments: /Users/am11/Library/Developer/CoreSimulator/Devices/B4FD0CE9-ADEE-45C9-A97D-F74D28384BA8/data/Containers/Data/Application/7FF2BBC9-0749-4E51-92AC-3D6295C01EC6/Documents
MyMusic: /Users/am11/Library/Developer/CoreSimulator/Devices/B4FD0CE9-ADEE-45C9-A97D-F74D28384BA8/data/Containers/Data/Application/7FF2BBC9-0749-4E51-92AC-3D6295C01EC6/Documents/Music
MyPictures: /Users/am11/Library/Developer/CoreSimulator/Devices/B4FD0CE9-ADEE-45C9-A97D-F74D28384BA8/data/Containers/Data/Application/7FF2BBC9-0749-4E51-92AC-3D6295C01EC6/Documents/Pictures
MyVideos: /Users/am11/Library/Developer/CoreSimulator/Devices/B4FD0CE9-ADEE-45C9-A97D-F74D28384BA8/data/Containers/Data/Application/7FF2BBC9-0749-4E51-92AC-3D6295C01EC6/Documents/Videos
```

@akoeplinger, is this by design (`Documents/Desktop` instead of `Desktop` etc.)?

**Comment by akoeplinger** [comment] 2024-04-05 16:12
Yes this is by design, or rather it was whatever Xamarin.iOS decided to use a decade ago and we tried to keep compatibility.
Mac Catalyst inherited those values because it is a special variant of iOS.

Changing these folders now would most likely break somebody, besides that there is also a difference on whether the Mac Catalyst app is enabling the `com.apple.security.app-sandbox` entitlement (which is required for App Store):

Sandbox disabled:
```
HOME env var: /Users/username
Desktop special folder: /Users/username/Documents/Desktop
```

Sandbox enabled:
```
HOME env var: /Users/username/Library/Containers/com.companyname.appname/Data
Desktop special folder: /Users/username/Library/Containers/com.companyname.appname/Data/Documents/Desktop
```

@MarcoMiltenburg as a workaround you can use this NSFileManager API but beware that this will still hit the sandbox difference:
```csharp
new NSFileManager().GetUrls(NSSearchPathDirectory.DesktopDirectory, NSSearchPathDomain.User)[0].Path
```

/cc @vitek-karas for thoughts on potentially changing the SpecialFolder return values for Mac Catalyst.

**Comment by vitek-karas** [comment] 2024-04-05 16:26
I would argue that if it returns a non-existent path, then the change to make it return something which exists is somewhat smaller breaking change. But it can break some apps for sure.
That said, if it's clearly wrong, I think we should at least consider it - otherwise we will keep wrong/broken behaviors forever. After all - exactly things like this are the reason .NET now has major version release where we do some breaking changes.

@ivanpovazan - for another opinion.

**Comment by vitek-karas** [comment] 2024-04-05 16:32
@dotnet/area-system-runtime and @dotnet/area-system-io for context and possibly opinions.

**Comment by akoeplinger** [comment] 2024-04-05 16:49
> I would argue that if it returns a non-existent path, then the change to make it return something which exists is somewhat smaller breaking change.

Yeah. I also just realized by looking at the code that we're not returning an empty string with `SpecialFolderOption.None` option (the default) when the special folder doesn't exist.

**Comment by ivanpovazan** [comment] 2024-04-08 11:01
> That said, if it's clearly wrong, I think we should at least consider it - otherwise we will keep wrong/broken behaviors forever. After all - exactly things like this are the reason .NET now has major version release where we do some breaking changes.

I agree. I believe we didn't catch the issue before as our customers were mostly targeting `net*-macos` with their desktop apps. 
However, as our customers are transitioning to MAUI, the issue got uncovered as `maccatalyst` is the only Apple "desktop" platform supported with MAUI framework, and I think we should try to address the issue in the upcoming release.

**Comment by vitek-karas** [comment] 2024-04-08 16:21
Ivan - can you please look at preparing a fix for this?

**Comment by ivanpovazan** [comment] 2024-04-08 16:33
Yes, I am on it.

**Comment by ivanpovazan** [comment] 2024-07-18 17:16
We considered aligning the `GetFolderPath` API behavior between MacCatalyst and MacOS but since:

- this would be a breaking change for MacCatalyst users, 
- it would introduce a difference between MacCatalyst and other iOS platforms, 
- and finally, the fact that we are late in the .NET 9 release cycle

we decided to keep the current behavior. 

To properly define the current behavior, we are updating our documentation and providing guidance on how to retrieve desired paths on MacCatalyst in: https://github.com/dotnet/docs-maui/pull/2371

If this still continues to cause issues for our customers we will revisit it in our next release.

I will close the issue as not planned for .NET 9.

**Closed by ivanpovazan** 2024-07-18 17:16 UTC
Labels: area-System.Runtime, os-maccatalyst
