### ISSUE TITLE
[wasi] `System.Collections.Tests` failing with `lock-free-alloc.c:374, condition 'next < LOCK_FREE_ALLOC_SB_USABLE_SIZE (desc->block_size) / desc->slot_size' not met`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#81911] opened 2023-02-09 18:32 UTC
[Build](https://dev.azure.com/dnceng-public/public/_build/results?buildId=165277&view=logs&j=f02b8cf9-dd4d-54fc-c292-2bb1d305b019&t=fd9015e5-cd94-57d7-8286-4fe749355863), and
[log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-81849-merge-0bf67e8732f44069bf/System.Collections.Tests/1/console.dd3b04d5.log?helixlogtype=result):

```
Using random seed for test cases: 412646952
Using random seed for collections: 412646952
Starting:    managed/System.Collections.Tests.dll
[MONO] error: * Assertion at /__w/1/s/src/mono/mono/utils/lock-free-alloc.c:374, condition `next < LOCK_FREE_ALLOC_SB_USABLE_SIZE (desc->block_size) / desc->slot_size' not met

Process wasmtime exited with 1
```

This happens on `main` too.

**Comment by lewing** [comment] 2023-02-09 18:34
cc @pavelsavara @vargaz

**Comment by pavelsavara** [comment] 2023-02-09 18:56
There is `src\mono\mono\utils\mono-threads-wasm.c` which is almost empty implementation. 
Because wasi doesn't have threads yet. I guess that's related to this issue.

**Comment by lewing** [comment] 2023-03-01 16:04
cc @lambdageek

**Comment by lambdageek** [comment] 2023-03-01 16:10
This lock free stuff boils down to `mono_valloc` which is `mmap` in disguise.  Does `mmap` work on WASI?

**Comment by pavelsavara** [comment] 2023-03-01 16:19
> This lock free stuff boils down to `mono_valloc` which is `mmap` in disguise. Does `mmap` work on WASI?

No it does not. Linear memory and security are the reasons I think.

**Comment by pavelsavara** [comment] 2023-03-01 16:24
There is some emulation which we link with `-lwasi-emulated-mman`. I don't know what it does.
https://github.com/WebAssembly/wasi-libc/blob/main/libc-top-half/musl/include/sys/mman.h

**Comment by vargaz** [comment] 2023-03-01 16:27
These are random failures, they are very hard to reproduce.

**Comment by lewing** [comment] 2023-07-26 18:04
from #88757 (closed as a duplicate)

```
[11:52:34] info: Discovered:  managed/System.Collections.Tests.dll (found 5666 of 7580 test cases)
[11:52:34] info: Using random seed for test cases: 59584765
[11:52:34] info: Using random seed for collections: 59584765
[11:52:34] info: Starting:    managed/System.Collections.Tests.dll
[11:54:02] info: [MONO] error: * Assertion at /__w/1/s/src/mono/mono/sgen/sgen-gc.c:1251, condition `sgen_gray_object_queue_is_empty (queue)' not met
[11:54:02] info: 
[11:54:02] info: Process wasmtime exited with 1
```

[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-88728-merge-785e2fb60ea84f0185/System.Collections.Tests/1/console.bceb98ff.log?helixlogtype=result)

**Comment by lewing** [comment] 2023-11-16 03:42
Is this still valid, it doesn't look like there has been a recent failure?

**Comment by vargaz** [comment] 2023-11-16 04:06
I couldn't reproduce it locally last time i looked.

**Comment by lewing** [comment] 2023-11-16 04:16
Closing, if someone sees it again please reopen

**Closed by lewing** 2023-11-16 04:16 UTC
Labels: arch-wasm, area-VM-meta-mono, test-failure, os-wasi
