### ISSUE TITLE
Microsoft.Extensions.DependencyInjection : add an option to control service instance created by the factory

### ISSUE THREAD

**Issue by ah1508** [dotnet/runtime#45760] opened 2020-12-08 13:59 UTC
## Background and Motivation

`System.Reflections.DispatchProxy` helps to create proxy of an object, it is helpful for cross cutting concerns (transcactions, security, performance measurement, exception handling, etc...) It would interesting if proxy application could be made on objects created by `Microsoft.Extensions.DependencyInjection`

With current version, applying a proxy on a service change the registration and the developper become responsible for creating the instance :

```souce,csharp
IServiceCollection sc = new ServiceCollection();
sc.AddSingleton<IFoo, Foo>();
```
becomes

```souce,csharp
IServiceCollection sc = new ServiceCollection();
sc.AddSingleton<IFoo>(sp => Proxy.For<IFoo>(new Foo()/*can be painful if constructor declares many arguments */));
```

With `Proxy.For` :

```csharp
public class Proxy : System.Reflection.DispatchProxy
{
    private object target;

    protected override object? Invoke(MethodInfo? targetMethod, object?[]? args)
    {
        // do something before invocation
        object? ret = targetMethod.Invoke(target, args);
        // do something after invocation
        return ret;
    }

    public static T For<T>(T target)
    {
        object proxy = System.Reflection.DispatchProxy.Create<T, Proxy>();
        ((Proxy)proxy).target = target;
        return (T)proxy;
    }
}
```

## Proposed API

The `Add*` and `TryAdd*` methods could have a `Func<TService, TService> enhancer` parameter, so it would be possible to receive the instance created by the default factory and to return something built from this instance. 

The object returned by this enhancer function would then be served by the `IServiceProvider` and used for injections.

## Usage Examples

```souce,csharp
IServiceCollection sc = new ServiceCollection();
sc.AddSingleton<IFoo, Foo>(fooInstance => Proxy.For<IFoo>(fooInstance));
```

## Alternative Designs

If it is not an option to add a parameter to the `Add*` and `TryAdd*` shortcut methods, a new parameter of type `Func<TService, TService` could be added to the `ServiceDescriptor` constructor.

**Comment by davidfowl** [comment] 2020-12-08 14:25
Dupe of https://github.com/dotnet/runtime/issues/36021

**Closed** 2020-12-09 17:39 UTC
Labels: api-suggestion, area-Extensions-DependencyInjection, untriaged
