### ISSUE TITLE
Setting ApplicationName to random value when using CreateDefaultBuilder fails in Development

### ISSUE THREAD

**Issue by AndreyTretyak** [dotnet/runtime#44467] opened 2020-11-10 15:35 UTC
If you are using `Host.CreateDefaultBuilder(args)` to create `HostBuilder`, set environment to `Development` and set application name to a value other then assembly names used in this project [following code path](https://github.com/dotnet/runtime/blob/6a5a78bec9a6e14b4aa52cd5ac558f6cf5c6a211/src/libraries/Microsoft.Extensions.Hosting/src/Host.cs#L81) will fail with `FileNotFoundException`:
```CSharp
if (env.IsDevelopment() && !string.IsNullOrEmpty(env.ApplicationName))
{
    var appAssembly = Assembly.Load(new AssemblyName(env.ApplicationName));
```

To me, it looks like it should not fail the whole host while trying to load dev secrets based on application name or if it's intended behavior then limitations in application name values should be specified clearly.

#### Code to reproduce
```CSharp
static async Task Main(string[] args)
{
	Environment.SetEnvironmentVariable("DOTNET_APPLICATIONNAME", "DummyName2");

	await Host.CreateDefaultBuilder(args)
		.UseEnvironment(Environments.Development)
		.Build()
		.RunAsync();
}
```
Or
```CSharp
static async Task Main(string[] args)
{
	await Host.CreateDefaultBuilder(args)
		.UseEnvironment(Environments.Development)
		.UseApplicationName("DummyName1")
		.Build()
		.RunAsync();
}

internal static IHostBuilder UseApplicationName(this IHostBuilder builder, string applicationName) =>
	builder.ConfigureHostConfiguration(configuration =>
	{
		configuration.AddInMemoryCollection(new[]
		{
			new KeyValuePair<string, string>(
				HostDefaults.ApplicationKey,
				applicationName)
		});
	});
```

#### Exception Information
Message:
```
System.IO.FileNotFoundException: 'Could not load file or assembly 'DummyName1, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.'
```
StackTrace:
```
at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext) in /_/src/System.Private.CoreLib/src/System/Reflection/RuntimeAssembly.cs:line 345
at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext) in /_/src/System.Private.CoreLib/src/System/Reflection/Assembly.CoreCLR.cs:line 73
at System.Reflection.Assembly.Load(AssemblyName assemblyRef) in /_/src/System.Private.CoreLib/src/System/Reflection/Assembly.CoreCLR.cs:line 55
at Microsoft.Extensions.Hosting.Host.<>c__DisplayClass1_0.<CreateDefaultBuilder>b__1(HostBuilderContext hostingContext, IConfigurationBuilder config) in /_/src/libraries/Microsoft.Extensions.Hosting/src/Host.cs:line 81
at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration() in /_/src/libraries/Microsoft.Extensions.Hosting/src/HostBuilder.cs:line 196
at Microsoft.Extensions.Hosting.HostBuilder.Build() in /_/src/libraries/Microsoft.Extensions.Hosting/src/HostBuilder.cs:line 131
at ConsoleApp1.Program.<Main>d__0.MoveNext() in D:\Projects\WebApplication4\ConsoleApp1\Program.cs:line 12
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/System.Private.CoreLib/shared/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 63
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 180
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 151
at System.Runtime.CompilerServices.TaskAwaiter.GetResult() in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 107
at ConsoleApp1.Program.<Main>(String[] args)
```

**Comment by sakno** [comment] 2020-11-10 19:32
You should not use `ApplicationName` property to define app name. [Here is the comment](https://github.com/aspnet/Hosting/issues/1179#issuecomment-323597195) from David Fowler. The value of this property is reserved by DI internals. Check [this](https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.Extensions.Hosting/src/Host.cs#L81) line of code for more details.

Related issues and PRs:
* aspnet/Hosting#1179
* aspnet/Hosting#1180

**Comment by AndreyTretyak** [comment] 2020-11-10 20:07
Thank you for the details @sakno, if it required to be an executing assembly name (I'm not sure is it the case for Asp Net Core or for all application using GenericHost but looks like all of them need it) then maybe it should in fail in all cases not only with some special preconditions like using dev environment, also using other assembly names (ex, `Newtonsoft.Json`) would work fine :)  

Maybe it should fail during `HostBuilder.Build` with a more meaningful error? What do you think? 

Also @sakno in your comment "Check this line of code for more details."
 you are pointing to the same line I was referencing in the issue is it the correct link?

**Comment by sakno** [comment] 2020-11-10 21:19
Oops, sorry for my inattention. Yes, it's the same line of code. I also tried to use this property for app name but without luck. There are many places especially in ASP.NET Core MVC utilizing its _special meaning_.

**Comment by maryamariyan** [comment] 2021-03-01 23:26
> You should not use ApplicationName property to define the app name. Here is the comment from David Fowler. The value of this property is reserved by DI internals. Check this line of code for more details.

Closing issue as by design

**Closed by maryamariyan** 2021-03-01 23:26 UTC
Labels: area-Extensions-Hosting, untriaged

**Comment by AndreyTretyak** [comment] 2021-03-02 18:52
@maryamariyan  should not docs and error message be more explicit about this problem?
