### ISSUE TITLE
httpclient Request headers must contain only ASCII characters

### ISSUE THREAD

**Issue by dashenxian** [dotnet/runtime#37386] opened 2020-06-04 02:48 UTC
When I use httpclient to simulate login, I need to keep the cookie, but there is a FriendlyName attribute in the cookie returned by the server that contains non-ascii characters, and then the second request will be wrong "Request headers must contain only ASCII characters" I saw this issue ![#32482 HttpClient not able to handle UTF8 Headers](https://github.com/dotnet/runtime/issues/32482), but I don’t know what to do, can I have more detailed operations?

.net core 3.1
win10 1909
![image](https://user-images.githubusercontent.com/18696614/83709328-d89d3f80-a650-11ea-83f1-4c8398a21ef1.png)

![无标题](https://user-images.githubusercontent.com/18696614/83708846-cbcc1c00-a64f-11ea-98e8-f871a79b1140.png)

**Comment by karelz** [comment] 2020-06-04 03:57
See https://github.com/dotnet/runtime/issues/32482#issuecomment-587590210 which explains such cookies / headers are violating RFC.
Currently such behavior is not possible on .NET Core 3.1.

That said, incidentally we had a discussion with a team earlier today, who pointed to us that this used to work on .NET Framework. There is high chance we will enable this, incl. porting to 3.1 patch. Follow #37024 and expect updates there in next few days.

**Comment by karelz** [comment] 2020-06-04 03:57
Duplicate of #37024

**Closed by karelz** 2020-06-04 03:57 UTC
Labels: area-System.Net.Http, untriaged
