### ISSUE TITLE
Provide a way to create types from the MetadataLoadContext

### ISSUE THREAD

**Issue by msedi** [dotnet/runtime#56914] opened 2021-08-05 16:13 UTC
### Discussed in https://github.com/dotnet/runtime/discussions/53415

<div type='discussions-op-text'>

<sup>Originally posted by **msedi** May 28, 2021</sup>
Currently with the `MetadataLoadContext` you can load metadata very quickly but it seems it not straightforward to create real types out of these metadata. Currently I think the approach is to load the runtime assembly in the AssemblyLoadContext and then discover the type by comparing against the AssemblyQualifiedName or the MetadataToken.

For attributes it seems that this is more complicated, you need to get the CustomAttributeData and provide your own methods to create the attribute. The problem is though, first you have to discover the underlying attribute type, find it in the AssemblyLoadContext, then all types in the CustomAttributeData (ConstructorArguments, NamedArguments) are also from the MetadataLoadContext and also need to be discoved in the AssemblyLoadContext. 

This is very cumbersome and error prone, if would be nice if some API exists that bridges this missing link.</div>

**Comment by krwq** [comment] 2021-08-06 12:39
@msedi do you have any proposition for how the APIs should look like? FYI: https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md

**Comment by teo-tsirpanis** [comment] 2021-08-07 14:43
Creating types from assemblies loaded in a `MetadataLoadContext` goes against the API's purpose. If you want to both inspect an assembly and run code from it, it would be better to load it in an `AssemblyLoadContext` in the first place.

If you want to inspect an assembly and _maybe_ run code from it so rarely that always creating an `AssemblyLoadContext` imposes an unnecessary overhead, you can create a `MetadataLoadContext` first and an `AssemblyLoadContext` next, matching the types between the contexts with either the type name or the metadata token.

These two context types cannot easily interoperate because they serve different purposes, and thus have different semantics in operations like disposal and resolving dependencies. I don't think there could be any easy way to make them work together.

However, the difficulty of using `CustomAttributeData` could be lessened with an API like the following:

``` csharp
namespace System {
    public class Attribute {
        public static Attribute Create (Type attributeType, CustomAttributeData data);
        public static T Create<T> (CustomAttributeData data) where T : Attribute;
    }
}
```

They would try to create an attribute object, regardless of the data's `AttributeType`.

What do you think?

**Comment by msedi** [comment] 2021-08-09 07:01
@teo-tsirpanis

 > Creating types from assemblies loaded in a `MetadataLoadContext` goes against the API's purpose.

Yes, I agree. Honestly, I'm not to deep in the reflection context and cannot foresee possible side effects of my propposal, so please just see this as suggestions which are open for discussion ;-)

I like your proposal, it's ind the end what I did myself, but it seems to me that there might be better (more performant) realisations:

 ```cs
       public Attribute GetAttribute()
        {
            if (RuntimeAttribute != null)
                return RuntimeAttribute;

            try
            {
                RuntimeType = MetadataBuffer.Default.GetType(ReflectionType)?.GetRuntimeType();
                if (RuntimeType == null)
                    return null;

                CustomAttributeData data = AttributeData;

                var arguments = from arg in data.ConstructorArguments select arg.Value;

                // Get the constrcutor from the runtimetype.
                var runtimeConstructor = RuntimeType.GetConstructors().FirstOrDefault(x => x.MetadataToken == data.Constructor.MetadataToken);
                var attribute = (Attribute)runtimeConstructor.Invoke(arguments.ToArray());

                foreach (var namedArgument in data.NamedArguments)
                {
                    var memberInfo = RuntimeType.GetMembers().FirstOrDefault(x => x.MetadataToken == namedArgument.MemberInfo.MetadataToken);

                    if (memberInfo is PropertyInfo propertyInfo)
                    {
                        propertyInfo.SetValue(attribute, namedArgument.TypedValue.Value, null);
                    }
                    else if (memberInfo is FieldInfo fieldInfo)
                    {
                        fieldInfo.SetValue(attribute, namedArgument.TypedValue.Value);
                    }
                }

                RuntimeAttribute = attribute;
                return attribute;
            }
            catch (Exception e)
            {
                logger.LogError(e, "Error creating a runtime attribute from a MetadataAttribute");
                return null;
            }
        }
```

**Comment by msedi** [comment] 2021-08-09 07:20
@krwq : Thanks for the answer.

> @msedi do you have any proposition for how the APIs should look like? FYI: 

Honestly no ;-) 

I'm writing a MetadataBuffer that inspects all assemblies of the application to perform 

- the necessary plugin discovery
- view model associations
- mathematical routine
- array converters, etc.

It combines the whole metainformation of the whole application in one place. The discovery is pretty easy, but what I did was that I created my own MetadataAssembly, MetadataType and MetadataAttribute to isolate the types from the MetadataLoadContext. 

What is currently a bug problem is that I cannot compare types from the MetadataLoadContext (MLC) and the AssemblyLoadContext (ALC). Even it's the same type the comparison fails. For sure there is a good reason but this makes it complicated since many times I need to lookup a type from the ALC. What I did was that I "reinvented the wheel" by creating many functions from the Type to the MetadataType and added an implicit cast so that any time I use the Type it is looked up in the MLC. Which of course is time consuming. As there is not so much docs around MLC I'm struggling a bit with the inner workings and if I'm using the things as they are intended.

Creating attributes from the MLC was the greated challenge. As @teo-tsirpanis already suggest it would be good to have "MS" made solution to at least be able to create attributes.

I can also share my current solution if necessary.

**Comment by msedi** [comment] 2021-08-09 12:55
BTW: Is comparing a Type T1 with another Type T2 for similarity with == the correct approach? Equals gives the same results, right?

If the first type comes from the MLC and the second type comes from the ALC but have the same AssemblyQualifiedName the comparison does not work, right? What would be the suggested way?

Nevertheless, if I have more of these questions, where is the right place to ask? Since its a so specific topic there are not so many places where people can answer....

**Comment by teo-tsirpanis** [comment] 2021-08-09 13:38
According to documentation, an MLC "[r]epresents a closed universe of Type objects [...]". A `Type` from another MLC or from an ALC is not a member of this "universe" of `Type`s, which means that checking it for equality with a `Type` of this MLC is meaningless since it will always return false. This behavior is by design.

Same with two types from different ALCs. I have actually encountered exceptions saying `Cannot convert a MyType to a MyType.` because I loaded a shared assembly in two ALCs.

As far as I have understood from your use case, and as I told earlier, the suggested way is to stop using MLCs and use only an ALC to load your assemblies, since you want more than just inspecting metadata.

**Comment by msedi** [comment] 2021-08-10 16:30
@teo-tsirpanis : That makes sense according to the docs that the types from different contexts are from a difference universe/context.

To clarify my situation a but more. When starting the app I'm analysing all assemblies in the MLC to find out what is available and to fill "lazy" structures that are later used to create types. It's a plugin system so I don't know in advance which items to analyze, so I scan over all assemblies and the ones that are inspectable are stored in a "cache" file so that I don't to look into them in the next run of the app. This takes ~10s in the MLC the ALC takes much longer (~ 20s) which one would think it's not such a big problem, but if you are working with the app and the startup takes so long this is really annoying and it came also to situations where customers double-clicked multiple times since there was no reaction from the app (and since it's so early in the startup I cannot even display an hourglass or a dialog). 

When storing the cache it only takes ~1s.

But until here everythings works fine. There are 2. problems though:

1. When I need to create an attribute I need to do it myself (which I solved), but I like your suggestion ;-) so that someone that knows much better than me of how to create an attribute.

2. When running the App I have types from the MLC in my cache and I need to find some correspondence of this type in the ALC. If it's not there I load the type (or better the assembly) in the ALC and retrieve the type from there. Whats happening from a higher point of view that all the types in my MLC are partially replaced by types from the ALC. For that reason I was using the TypeDelegator initially but it seemed to me it was better to have an explicit MetadataType to better distinguish which is which. Because now Type is Type and you cannot directly see where the Type comes from (MLC or ALC).

I somehow understand that == is maybe not the correct way. There is an IsEquivalentTo but internally the == operator is used. But I cannot check in the source of Type what the == operator does, but it seems that it only compares for the same reference.
because Type.Equals for example is implemented internally with Reference.Equals() where as the == operator is defined as

```cs
        [Intrinsic]
        [MethodImpl(MethodImplOptions.InternalCall)]
        public static extern bool operator ==(Type? left, Type? right);

```

I can currently solve my problems but I see already see some potential problems when it comes to comparing types from different universes. I would rater prefer that an exception is thrown when this happens instead of returning false when comparing types or checking for inheritance, like IsSubclassOf or IsAssignableTo.

What do you think?

**Comment by KalleOlaviNiemitalo** [comment] 2021-08-10 18:24
> But I cannot check in the source of Type what the == operator does

It's defined here:

<https://github.com/dotnet/runtime/blob/91ba01788d4d83475fec3aea7c830376e08585da/src/coreclr/vm/ecalllist.h#L163-L168>

<https://github.com/dotnet/runtime/blob/91ba01788d4d83475fec3aea7c830376e08585da/src/coreclr/vm/runtimehandles.cpp#L322>

**Comment by msedi** [comment] 2021-08-10 20:19
Thanks for pointing this out. I will take a look how it's implemented.

**Comment by steveharter** [comment] 2022-10-27 17:47
Closing as by design - MLC is for inspection only and does not run any code from the Types in the MLC.

The issue with attributes not being created fully is that since attributes can run code, which is not allowed in MLC, the raw attribute data must be used.

The issue with trying to find the corresponding type in the runtime can be a manual lookup approach; having a helper for this has been discussed in the past but there are too many edge cases to consider.

**Closed by steveharter** 2022-10-27 17:47 UTC
Labels: api-needs-work, api-suggestion, area-System.Reflection
