### ISSUE TITLE
Test failure: JIT/Regression/JitBlue/GitHub_11408/GitHub_11408/GitHub_11408.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#108360] opened 2024-09-29 01:37 UTC
**Failed in:** [runtime-coreclr pgostress 20240927.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=821104&view=ms.vss-test-web.build-test-results-tab&runId=21313360&resultId=118741&paneView=debug)

**Failed tests:**
```
coreclr windows x64 Checked fullpgo_random_gdv_edge @ Windows.10.Amd64.Open
    - JIT/Regression/JitBlue/GitHub_11408/GitHub_11408/GitHub_11408.cmd
```

**Error message:**
```
 
Assert failure(PID 3416 [0x00000d58], Thread: 4428 [0x114c]): Consistency check failed: AV in clr at this callstack:
------
CORECLR! TypeHandle::Verify + 0x16 (0x00007ffe`59b44d86)
CORECLR! SigPointer::HasCustomModifier + 0x1A6 (0x00007ffe`59af2c36)
CORECLR! CEEInfo::getArgType + 0xA0C (0x00007ffe`599f44ac)
CLRJIT! Compiler::lvaInitTypeRef + 0x349 (0x00007ffe`5ae30729)
CLRJIT! Compiler::compCompileHelper + 0x319 (0x00007ffe`5acfb4a9)
CLRJIT! Compiler::compCompile + 0x8F8 (0x00007ffe`5acfa988)
CLRJIT! `jitNativeCode'::`8'::__Body::Run + 0xE2 (0x00007ffe`5acf6942)
CLRJIT! jitNativeCode + 0x155 (0x00007ffe`5ad00e25)
CLRJIT! CILJit::compileMethod + 0x169 (0x00007ffe`5ad08669)
CORECLR! invokeCompileMethod + 0x203 (0x00007ffe`59a18693)
CORECLR! UnsafeJitFunction + 0x83B (0x00007ffe`599ed38b)
CORECLR! MethodDesc::JitCompileCodeLocked + 0x1D2 (0x00007ffe`59ac43f2)
CORECLR! MethodDesc::JitCompileCodeLockedEventWrapper + 0x50D (0x00007ffe`59ac4c7d)
CORECLR! MethodDesc::JitCompileCode + 0x5A9 (0x00007ffe`59ac4119)
CORECLR! MethodDesc::PrepareILBasedCode + 0x4F2 (0x00007ffe`59ac6aa2)
CORECLR! MethodDesc::PrepareCode + 0xF3 (0x00007ffe`59ac6553)
CORECLR! MethodDesc::PrepareInitialCode + 0x132 (0x00007ffe`59ac6c42)
CORECLR! MethodDesc::DoPrestub + 0xCF5 (0x00007ffe`59abefe5)
CORECLR! PreStubWorker + 0x476 (0x00007ffe`59acb846)
-----
.AV on tid=0x114c (4428), cxr=000000AE3B979E00, exr=000000AE3B97A2F0
FAILED: false

CORECLR! CHECK::Trigger + 0x1F0 (0x00007ffe`59ffd360)
CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x4BB (0x00007ffe`5997239b)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x91 (0x00007ffe`59971c71)
CORECLR! CLRVectoredExceptionHandler + 0x76C (0x00007ffe`59971bcc)
CORECLR! CLRVectoredExceptionHandlerShim + 0x181 (0x00007ffe`599725f1)
NTDLL! RtlInitializeCriticalSection + 0x190 (0x00007ffe`8a816dc0)
NTDLL! RtlImageNtHeaderEx + 0x17B (0x00007ffe`8a7e46cb)
NTDLL! KiUserExceptionDispatcher + 0x3A (0x00007ffe`8a859caa)
CORECLR! TypeHandle::Verify + 0x16 (0x00007ffe`59b44d86)
CORECLR! SigPointer::HasCustomModifier + 0x1A6 (0x00007ffe`59af2c36)
    File: D:_work1ssrccoreclrmexcep.cpp:6881
    Image: C:hwA5AC08FDpcorerun.exe


Return code:      1
Raw output file:      C:hwA5AC08FDwACBC0988uploadsJitBlueGitHub_11408GitHub_11408output.txt
Raw output:
BEGIN EXECUTION
 "C:hwA5AC08FDpcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  GitHub_11408.dll 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:cores since 9/28/2024 7:49:37 AM
Processing C:corescorerun.exe.3416.dmp
Invoking: C:Program Files (x86)Windows Kits10Debuggersdcdb.exe -c "$<C:hwA5AC08FD		mpame4gx.tmp" -z "C:corescorerun.exe.3416.dmp"
stdout: 
Microsoft (R) Windows Debugger Version 10.0.18362.1 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:corescorerun.exe.3416.dmp]
User Mini Dump File with Full Memory: Only application data is available


************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:hwA5AC08FDpPDB
Symbol search path is: C:hwA5AC08FDpPDB
Executable search path is: 
Windows 10 Version 14393 MP (4 procs) Free x64
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.6343 (rs1_release.230913-1727)
Machine Name:
Debug session time: Sat Sep 28 07:49:42.000 2024 (UTC + 0:00)
System Uptime: 0 days 0:15:58.626
Process Uptime: 0 days 0:00:05.000
..........................

************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  The system cannot find the file specified

You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.s
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor334|0_335(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by JulieLeeMSFT** [comment] 2024-09-30 18:45
@AndyAyersMS, PTAL.

**Comment by AndyAyersMS** [comment] 2024-10-04 15:25
Haven't been able to repro this so far. One of the call stacks shows a failure during jitting parsing the method sig we get from the runtime, so this may not be a codegen issue.

**Comment by AndyAyersMS** [comment] 2024-10-04 15:25
Also seen in https://github.com/dotnet/runtime/pull/108497

**Comment by AndyAyersMS** [comment] 2024-10-04 16:39
This just started recently, so not a .net 9 issue.

**Comment by AndyAyersMS** [comment] 2024-10-05 01:36
Have an intermittent local repro, took 30 runs the first time.

**Comment by jkotas** [comment] 2024-10-07 12:27
Duplicate of https://github.com/dotnet/runtime/issues/108586

**Closed by jkotas** 2024-10-07 12:27 UTC
Labels: os-windows, arch-x64, area-CodeGen-coreclr, blocking-clean-ci-optional
