### ISSUE TITLE
[System.Net.Http.Json] HttpRequestException is not thrown by HttpClient.GetFromJsonAsync when recieving a 204 No Content Response

### ISSUE THREAD

**Issue by geobmx540** [dotnet/runtime#63037] opened 2021-12-21 07:45 UTC
### Description

When using `GetFromJsonAsync` against an API call that returns a 204 No Content, the method throws an exception that loses detail of the API call, specifically that there was a status code of 204 return. 

I would expect to know that the API call was successful but there was no object at the endpoint (this might be similar to a 404)

### Reproduction Steps

```c#
try
{
    var response = await client.GetFromJsonAsync<ResponseObject>($"https://url.that.returns.204.no.content.com");
}
catch (HttpRequestException ex)
{
    // hitting here would be useful
}
catch (Exception ex)
{
    // Exception hits here, with "The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true"
   // There is no way to know that the exception was because of a 204 No Content response
}
```

### Expected behavior

I'm not sure the best expected behavior, either:

1. This would throw an `HttpRequestException` with a StatusCode of 204. In this case, it's a little weird, but could be appropriate as we are expecting to serialize an object back, and we aren't getting one; but more importantly there is no way to determine exactly what went wrong (a 200 response with invalid JSON, or some other parsing error vs this 204
2. Return a new object of type T. This would require further handling of new objections for error handling but would allow for better handling than erroring. This may hide the fact that a successful 200 response may result in an empty object anyway.

### Actual behavior

An `Exception` is thrown, losing knowledge of the API response code

### Known Workarounds

Can fall back to `client.GetAsync` and handle the response + parsing separately.

**Comment by eiriktsarpalis** [comment] 2022-02-03 10:05
The actual exception type being thrown is `JsonReaderException` emanating from `System.Text.Json` attempting to read from an empty content stream. I would say that this behavior is by design, the `GetFromJson*` wrappers [will only check if the status code is successful](https://github.com/dotnet/runtime/blob/a159132fb05bec4ac821f441fe1edbd83d539504/src/libraries/System.Net.Http.Json/src/System/Net/Http/Json/HttpClientJsonExtensions.Get.cs#L153) and then pass on the content (empty or otherwise) to the deserialization layer. We might consider wrapping exceptions emanating from the serializer with `HttpRequestException` although I'm not necessarily convinced that it's appropriate to do so, cc @dotnet/ncl @Jozkee for second opinions.

In general these wrappers only provide rudimentary support for serializing content, if your API has more complex needs my recommendation would be to author your own wrapper methods over `HttpClient.SendAsync`.

**Comment by geobmx540** [comment] 2022-02-03 16:29
@eiriktsarpalis sounds good - definitely tackled it using the SendAsync and my own wrappers - just thought it might be helpful to document the specific situation and pain point. Thanks for the response and added detail

**Comment by kathleenvv** [comment] 2022-02-12 12:17
I think this discussion contributes to a preference for **not** applying the `HttpNoContentOutputFormatter` with `TreatNullValueAsNoContent` **by default**.
I found this clearly argumented in [Rick Strahl's post](https://weblog.west-wind.com/posts/2020/Feb/24/Null-API-Responses-and-HTTP-204-Results-in-ASPNET-Core).

**Comment by eiriktsarpalis** [comment] 2022-09-02 16:32
Closing as by-design behavior.

**Closed by eiriktsarpalis** 2022-09-02 16:32 UTC
Labels: enhancement, area-System.Text.Json
