### ISSUE TITLE
[Perf -11%] [Mono] System.Net.Primitives.Tests.IPAddressPerformanceTests.Ctor_Span

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#43477] opened 2020-10-16 00:15 UTC
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Changes | [diff](https://github.com/dotnet/runtime/compare/56950ad78347dca556d5e835522ac7ee5f305bd3...f63b6f0a1b3ffd35dc1253226984a8d20bd4d91b)

### Regressions in System.Net.Primitives.Tests.IPAddressPerformanceTests

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier | Baseline ETL | Comapre ETL
-- | -- | -- | -- | -- | -- | -- | --
[Ctor_Span](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono/System.Net.Primitives.Tests.IPAddressPerformanceTests.Ctor_Span(address%3a%20%5b16%2c%2032%2c%2048%2c%2064%2c%2080%2c%20...%5d).html>) | 33.19 ns | 36.89 ns | 1.11 |  | False

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/10_12_2020/refs/heads/master_x64_ubuntu%2018.04_CompliationMode=tiered_RunKind=micro_mono/System.Net.Primitives.Tests.IPAddressPerformanceTests_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/10_12_2020/refs/heads/master_x64_ubuntu%2018.04_CompliationMode=tiered_RunKind=micro_mono/System.Net.Primitives.Tests.IPAddressPerformanceTests.html>)

<details>

#### System.Net.Primitives.Tests.IPAddressPerformanceTests.Ctor_Span(address: [16, 32, 48, 64, 80, ...])

```log
[  9.381 ;  57.933) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 57.933 ; 103.755) | 
[103.755 ; 149.577) | 
[149.577 ; 195.399) | 
[195.399 ; 235.040) | 
[235.040 ; 289.263) | @@@@@@@@@@@@@@@@@@@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by naricc** [comment] 2020-10-16 01:15
This appears to have been caused by one of hte commits in this range: https://github.com/dotnet/runtime/compare/56950ad78347dca556d5e835522ac7ee5f305bd3...f025f53481b492725cf889616315c73102b6ee58

**Comment by naricc** [comment] 2020-10-16 14:36
I believe specifically this change: https://github.com/dotnet/runtime/commit/f63b6f0a1b3ffd35dc1253226984a8d20bd4d91b

Same cause as https://github.com/dotnet/runtime/issues/43465
and
https://github.com/dotnet/runtime/issues/43463

**Comment by naricc** [comment] 2020-10-16 17:58
So Based on @lateralusX's investigation, it seems unlikely this was caused by his change after all. Relevant discord conversation:
https://discordapp.com/channels/732297728826277939/737723183397994563/766675155119243314

I'm going to see if the version bump just before his change could have caused this.

**Comment by naricc** [comment] 2020-10-16 21:28
It was pointed out to me that the above discord link is to a locked channel, so I've reproduced the relevant parts of the conversation here: 

NathanRicci: After triaging out noise, I've got five performance regression issues  that look real:

Three appear to be caused by the change this change to the Diagnostic Server Library @Johan Lorensson: https://github.com/dotnet/runtime/commit/f63b6f0a1b3ffd35dc1253226984a8d20bd4d91b

Issues: 
https://github.com/dotnet/runtime/issues/43477
https://github.com/dotnet/runtime/issues/43465
https://github.com/dotnet/runtime/issues/43463

The answer may that this is an acceptable trade off for the change, in which case we can close the issues; but at least we know what we are paying. Or we can figure out how to avoid paying that price. It effects both JIT and Interpreter.

The other two I am not sure of an exact cause, but have narrowed it down to several commits just based on the time frame:

https://github.com/dotnet/runtime/issues/43476
https://github.com/dotnet/runtime/issues/43478

I don't really see how any of those changes could have casued an issue, but there is a distinct change in the graph.
[10:56 AM] Johan Lorensson: @NathanRicci What process was used to narrow down that the evetpipe library (that is not enabled by default) was causing some of the perf regression?
[11:00 AM] NathanRicci: In any of those issues, if hit the "historical data in reporting" link, and then click on any of the graphs in the "difference" column. You can interact with the graph, and set a "Baseline, and a "Compare", and see all the commits in between. There's abig spike between October 4 and 5th (these are only run once a day).
[11:00 AM] NathanRicci: The only other change in that time frame is this, but it seems like it is test only and couldn't have caused a regression: https://github.com/dotnet/runtime/commit/bd33fc4e4a3382422bee156cd66a45a13521ec58
[11:02 AM] NathanRicci: The UI for the graphs is a little clunky.
[11:03 AM] NathanRicci: Hmm, if its not enabled by default, then maybe its not the cause. Its possible its random, but the fact that I saw it on a couple benchmarks, in both interpreter and JIT, made me think otherwise.
[11:04 AM] AlekseyK: @lateralusX looks like the only live change in there is the call to mono_set_os_args
[11:05 AM] AlekseyK: which I guess for a microbenchmark might do a lot of copying and I think it probes /proc, right?
[11:06 AM] Johan Lorensson: void
mono_set_os_args (int argc, char **argv)
{
    mini_argc = argc;
    mini_argv = argv;
}
[11:06 AM] Johan Lorensson: and only called once in driver.c
[11:07 AM] AlekseyK: oh, I misunderstood how it's related to mono_runtime_get_cmd_line.  sorry
[11:08 AM] AlekseyK: and anyway the benchmarks I think normalize for startup time, right @NathanRicci ?
[11:08 AM] NathanRicci: Yes.
[11:08 AM] AlekseyK: @nathan how do you determine the commit range from the dates?
[11:08 AM] NathanRicci: @AlekseyK Yes, that's how I did it.
[11:09 AM] NathanRicci: I mean, by setting the right dates on teh graph, it gives me the commit range.
[11:09 AM] NathanRicci: I don't have to go manually put the dates into git.
[11:10 AM] Johan Lorensson: The tests flagged above with this commit, looks like they are very JIT/BCL centric, like System.Memory.ReadOnlyMemory<Char>.ToArray
[11:15 AM] Johan Lorensson: @AlekseyK one thing we do is registering with profiler for thread stop at eventpipe init:
[11:15 AM] Johan Lorensson: MonoProfilerHandle profiler = mono_profiler_create (NULL);
    mono_profiler_set_thread_stopped_callback (profiler, profiler_eventpipe_thread_exited);
[11:16 AM] Johan Lorensson: could that trigger more profiler events to take a longer route, like JIT related events?
[11:18 AM] AlekseyK: i'm not sure.  I don't know if the profiler support has some kind of optimization for "no profilers are registered"
[11:18 AM] NathanRicci: The benchmark itself is here, if you want to know exactly what its doing: https://github.com/dotnet/performance/blob/master/src/benchmarks/micro/libraries/System.Memory/ReadOnlyMemory.cs
GitHub
dotnet/performance
This repo contains benchmarks used for testing the performance of all .NET Runtimes - dotnet/performance

[11:18 AM] Johan Lorensson: but looks like that code was there before that commit
[11:25 AM] Johan Lorensson: the profiler event was added long before, in https://github.com/dotnet/runtime/commit/c5b55f06d6d65c4673734198a87a31f7ace789c2#diff-8fa4a2213aa9c853fd1afd18bf447a57ba660d5ef23e04525c614594f8942e89, so should probably showed up much earlier in benchmarks if that was a culprint, the same goes to the majority of the eventpipe code
GitHub
Initial work of porting native diagnostic eventpipe library to C. (...
…4600)

First bulk of changes related to porting EventPipe C++ library from
CoreCLR into a C library that can be shared between Mono as well as
CoreCLR runtime.

Due to dependencies and current...

[11:26 AM] AlekseyK: @NathanRicci what config is this? mini jit?
[11:26 AM] NathanRicci: We were not even running these back then.
[11:27 AM] NathanRicci: @AlekseyK https://github.com/dotnet/runtime/issues/43463 is intepreter, https://github.com/dotnet/runtime/issues/43477, https://github.com/dotnet/runtime/issues/43465 are mini-jit.
[11:28 AM] AlekseyK: how can you tell from the report?
[11:28 AM] AlekseyK: oh click through to the historical thing again
[11:32 AM] Johan Lorensson: @NathanRicci easy to run these locally and experiment? One thing we enabled in that commit is the diagnostic server thread (same as CoreCLR does), it is started by default, but will just sit idling in background since no connections will be done,  it can be disabled using an env variable, do we have a place to test that?
[11:35 AM] AlekseyK: @Johan Lorensson why do we think that eventpipe is disabled?
[11:35 AM] AlekseyK: I only see mono.proj set --enable-minimial=...,eventpipe,... on a coupel of mobile targets
[11:36 AM] Johan Lorensson: what I meant was that its not running any sessions by default
[11:36 AM] Johan Lorensson: the code is there
[11:36 AM] Johan Lorensson: and it does init work, but that is only startup
[11:36 AM] AlekseyK: could we be getting icall calls even if there's no session?
[11:37 AM] Johan Lorensson: If you have listeners setup
[11:37 AM] Johan Lorensson: and someone generates events
[11:37 AM] AlekseyK: bcl generates events, I think
[11:37 AM] AlekseyK: maybe microbenchmarks are listening for them?
[11:37 AM] NathanRicci: The benchmarks themselves can be downloaded here: https://github.com/dotnet/performance

To run them, you would do this in src/benchmarks/micro/:

  $MYDOTNET run -c Release --framework netcoreapp5.0  MicroBenchmarks.csproj --filter <benchmarks to run> --cli $MYDOTNET


Where Mydotnet is pointing at a dotnet host that uses mono. The --cli option is what tells it to run the actual benchmark with that 'dotnet" command.
[11:38 AM] Johan Lorensson: @AlekseyK The managed code has been enabled for quite some time in Mono, so if there managed events that should have happened in the past as well
[11:39 AM] Johan Lorensson: if there are no listeners it should be filtered out very early in managed code as well
[11:39 AM] AlekseyK: I see
[11:40 AM] Johan Lorensson: I can try one of the benchmarks under debugger to see if we get anything unexpected when running those tests
[11:41 AM] AlekseyK: @NathanRicci  does this $MYDOTNET thing still work by patching an existing sdk?  maybe there was some version bump that accumulated a bunch of other changes?
[11:41 AM] NathanRicci: @AlekseyK Yes, that is how it works. But wouldn't we see a commit with the version bump in it, if that were the case?
[11:45 AM] AlekseyK: https://github.com/dotnet/runtime/commit/8cb351833ab88788e49f6017d7c7ab3823fda5be this one does some version bumps. not sure if it's relevant
GitHub
Reenable MUSL ARM tests (#42202) · dotnet/runtime@8cb3518
* Reenable MUSL ARM tests

The packages for MUSL ARM should now be available, so reenable the
libraries tests in the CI

* Update DotnetHost and DotnetHostPolicy versions

* Add Linux arm mu...

[11:53 AM] NathanRicci: Hm... Maybe its possible for that to be the cause. The graph makes it look continuous, but we are of course really just sampling...
[12:07 PM] NathanRicci: I will have to ask Drew (the engineer who works on infrastructure that makes the graphs and etc.) about that.
[12:14 PM] AlekseyK: hm. I don't see any event tracing stuff in dotnet/performance that might be relevant.  there's one EventListener microbenchmark, and some kind of EventSource that is registered (but it's in the scenarios/ folder, so maybe that's just another benchmark)
[12:15 PM] NathanRicci: Its starting a new process for every single benchmark, so the benchmarks should not effect eachother. They are also in a seperate process for the harness...
[12:15 PM] AlekseyK: could this be some kind of cache noise because our code size increased due to all the diagnostic server source code?
[12:17 PM] NathanRicci: I am not sure how to rule that out, so I'd have to say its possible.
[12:52 PM] Ryan Lucia: these are easy to run locally right? so we should be able to just bisect and find the exact commit if we aren't sure?
[1:00 PM] NathanRicci: They are easy enough to run locally. Since we have only two possible candidates I'm not even sure if a bisect is necessary.
[1:00 PM] Ryan Lucia: yeah i guess it's not a real bisect if we're sure it could only be two commits
[1:01 PM] Ryan Lucia: though either way, if they're easily run locally we should be sure of what commit it is
[1:02 PM] Ryan Lucia: i also have some questions about how these benchmarks work based on a paper i read yesterday but i'll bother you about that during the call later today
[1:21 PM] Johan Lorensson: eventpipe code is doing the same thing for all tests unless explicit invoked (using EventSource/EventListener), the above regression was only 3 tests out of how many regression tests? If that commit is the cause of perf regression wouldn’t it be expected to manifest in many more of the tests?
[1:40 PM] NathanRicci: @Johan Lorensson The suite is like 2000 benchmarks. So, yeah, we would expect it to manifest in more tests, unless it was something very specific to what that benchmark was doing.
[1:43 PM] NathanRicci: Well, I guess we can eliminate that change as a cause. Thanks.

**Comment by SamMonoRT** [comment] 2021-04-22 13:20
Closing this old issue due to a lot of code churn in this space. We will monitor future runs.

**Closed by SamMonoRT** 2021-04-22 13:20 UTC
Labels: arch-x64, area-Tracing-mono, os-linux, runtime-mono, tenet-performance, tenet-performance-benchmarks
