### ISSUE TITLE
Slow startup when publish single file with self-contained

### ISSUE THREAD

**Issue by jamieYNchan** [dotnet/runtime#79023] opened 2022-11-30 03:25 UTC
### Description

I have written the application by using .net 6 WPF.  It seems the first http client needs large response time to process if I publish with self-contained single file.  I understand for the first run may require longer waiting time to extract files to temp, but why does it need large time to process when calling GetStringAsync in httpClient for each appstart?

### Configuration
.NET version: 6.0.303
OS: Window 10: 19044.2006
Publish Tools: Visual Studio 2022 Version 17.2.6

![image](https://user-images.githubusercontent.com/56505383/204693475-dbb34e00-6f2a-4a0f-b05c-eab89d73c803.png)

### Performance (Whenever App start)

| Deployment Mode    | Response time |
| ------------------ | ------------- |
| Framwork dependent | ~1614ms       |
| Self-Contained     | ~10425ms      |

### Repro Steps
```
public MainWindow()
        {
            InitializeComponent();
            getRemoteString();
        }

        async void getRemoteString()
        {
            Stopwatch sw = new Stopwatch();
            sw.Start();
            using (var client = new HttpClient())
            {
                    client.BaseAddress = new Uri("https://httpbin.org");
                    await client.GetStringAsync("get");
            }
            sw.Stop();
            tbMsg.Text = $"Response Time:{sw.ElapsedMilliseconds}ms";
        }
```

**Comment by ManickaP** [comment] 2022-11-30 21:07
This reproduces even with console app. It seems to be caused by "SingleFile" publish (when removed, it disappears). I also tried replacing the HttpClient call with fairly big, async file write (~500MB) and it problem disappeared. 
So this seems to manifest for HttpClient with SingleFile publish, we should look into it in.

**Comment by MihaZupan** [comment] 2022-11-30 21:37
Were you testing on Windows @ManickaP?

In my case this takes 6 seconds to execute
```c#
Console.WriteLine("Hi");
```
Where the whole time is spent just waiting on Windows Defender :)
If I add the folder to the exclusion list I can't repro anything anymore.

**Comment by vitek-karas** [comment] 2022-11-30 21:44
It could be AVs as Miha suggests. I didn't see 6 second waits on Windows Defender though. Well, that's not true. On the very first run after build, it can take a really long time. But then starting the app for the second time should be reasonably fast.

That said we've seen reports from machines with other AV software where the startup is slow even on second run of the same untouched binary. Single-file makes this "Worse" because the AV is not scanning a file on disk, instead we have to report each loaded assembly as an "in memory code loaded" to the AV, and if the AV doesn't have smart caching strategies, the theory is that it may end up rescanning everything. But we don't have hard data on this.

**Comment by ManickaP** [comment] 2022-11-30 22:37
When I changed the code to do File.WriteAsync instead of HttpClient.GetStringAsync it disappeared. When I turned off SingleFile, it disappeared. I'll retest tomorrow, to be sure. BTW, in the WPF app it was almost ~40 seconds, console ~6 seconds (<1 second normally).

**Comment by ManickaP** [comment] 2022-12-02 13:16
I cannot reproduce it anymore, not even on a fresh project, not in WPF nor console, not on Windows nor Linux (for console). Everything is under 1 second.

@jamieYNchan can you reproduce the problem in a console app? Does it happen repeatedly, i.e. on second run? Could you try the recommendation with antivirus exclusion?

**Comment by jamieYNchan** [comment] 2022-12-02 16:27
My working PC already installed Trend Micro. I tried exit av and I got I nice response time ~1s. 

However, even I excluded my application path to Trend Mico.

It just improved the bundled files extraction time. I got the same results ~10s for the second run or third run of the console/WPF application.

The first GetAsync requires a large response time in self-contained Single-file publish.


Also, I tested running cmd to use curl in my bundled wpf.  The first response time is faster than GetAsync :D

**Comment by ManickaP** [comment] 2022-12-02 17:51
> I tried exit av and I got I nice response time ~1s.

Do I get this right that if you turn off your AV, the execution time (including GetAsync) is around 1 second, even with self-contained, single-file publish?

If so, then this is a problem with AV and not with HttpClient or dotnet itself.

**Comment by agocke** [comment] 2023-08-28 20:23
Closing as AV-related.

**Closed by agocke** 2023-08-28 20:23 UTC
Labels: tenet-performance, area-Single-File
