### ISSUE TITLE
The SSl connection could not be established

### ISSUE THREAD

**Issue by FrancisFYK** [dotnet/runtime#44058] opened 2020-10-30 08:26 UTC
our Intranet environment has published a self-signed IP certificate and The service prompt "The SSL Connection not Be Established "via HttpClient calls is using.net Core 3.1

![image](https://user-images.githubusercontent.com/20334266/97677083-a9d6a880-1acc-11eb-880c-04789305355b.png)

**Comment by wfurt** [comment] 2020-10-30 19:50
What platform are you running on and do you establish the trust somehow? (and do you have expected EKU in the cert)  
It seems like you are trying to register custom validation: does it get called?

Perhaps small repro with clone of the certificate would be good start for triage.

**Comment by FrancisFYK** [comment] 2020-11-03 10:30
window 10  platform the same code is fine in .net framework 4.5 but not in .net core 3.1 
can it be that the certificate is invalid ?

**Comment by wfurt** [comment] 2020-11-03 19:42
.net framework uses ServicePointManager and the defaults and settings may be different. Can you do packet capture with Wireshark for both cases and post the outcome. Since there is no repro and you did not even post the full exception, it is hard to know if this is really caused by certificate validation or by something else.

**Comment by FrancisFYK** [comment] 2020-11-04 02:06
Unhandled exception. System.AggregateException: One or more errors occurred. (Th
e SSL connection could not be established, see inner exception.)
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be esta
blished, see inner exception.
 ---> System.Net.InternalException: Exception of type 'System.Net.InternalExcept
ion' was thrown. -2146892963
   at System.Net.SecurityStatusAdapterPal.GetSecurityStatusPalFromInterop(SECURI
TY_STATUS win32SecurityStatus, Boolean attachException)
   at System.Net.Security.SslStreamPal.InitializeSecurityContext(SafeFreeCredent
ials& credentialsHandle, SafeDeleteContext& context, String targetName, ArraySeg
ment`1 input, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOp
tions)
   at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset
, Int32 count, Byte[]& output)
   at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offse
t, Int32 count)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count,
AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 cou
nt, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readByte
s, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest as
yncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncRe
sult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result
)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncRe
sult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyn
cResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar,
Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchron
ization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream strea
m, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToke
n)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream strea
m, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToke
n)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request
, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequest
Message request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessa
ge request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage r
equest, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Canc
ellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRe
questMessage request, CancellationTokenSource cts, Boolean disposeCts)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotifica
tion)
   at System.Threading.Tasks.Task`1.get_Result()


I'll use Wireshark first to see the difference
thank you！！

**Comment by wfurt** [comment] 2020-11-04 03:00
the error is SEC_E_INVALID_PARAMETER and that is curious. Is there any chance you are stil manipulating ServicePoint even for Core? Did you try that with just very small repro e.g. outside of your normal code base?

**Comment by karelz** [comment] 2020-12-02 17:07
Triage: Closing as there is not enough info. Feel free to reopen once you can answer the above questions from @wfurt. Thanks!

**Closed by karelz** 2020-12-02 17:07 UTC
Labels: area-System.Net.Http, needs more info, untriaged
