### ISSUE TITLE
CreateLogger<T> extension doesn't use supplied provider

### ISSUE THREAD

**Issue by CobusKruger** [dotnet/runtime#50427] opened 2021-03-30 14:50 UTC
### Describe the bug
According to [the documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.abstractions.nullloggerfactory?view=dotnet-plat-ext-5.0), `NullLoggerFactory` is used to create instances of `NullLogger`. That's exactly what I want.

However, if the code using the factory uses the `CreateLogger<T>` extension method, the logger created is not a `NullLogger`.

### To Reproduce
```c#
[TestMethod]
public void TestLoggerClasses()
{
    var factory = new NullLoggerFactory();
    var logger = factory.CreateLogger("SomeText");
    Assert.AreEqual(typeof(NullLogger), logger.GetType()); // Pass - expected
    var loggerExtension = factory.CreateLogger<object>();
    Assert.AreEqual(typeof(NullLogger<object>), loggerExtension.GetType()); // Fail - unexpected
}
```

### Further technical details
- ASP.NET Core version: 3.1.407
- Include the output of `dotnet --info`
```
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  3.1.407 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version
Visual Studio 2019 Version 16.9.1

**Comment by CobusKruger** [comment] 2021-03-31 07:35
But that leaves a huge inconsistency. Using `CreateLogger(string)` yields one result, but calling `CreateLogger<T>` yields another. It actually renders the extension method much less useful; If it's used at all, that code cannot be reused in a context where the `ILoggerFactory` may be replaced—something you may not know ahead of time. The simple act of using that method can cause unexpected reworks down the line.

**Comment by KalleOlaviNiemitalo** [comment] 2021-03-31 08:45
Is your app trying to find out whether the logger instance can ever become enabled, a bit like [CancellationToken.CanBeCanceled](https://docs.microsoft.com/dotnet/api/system.threading.cancellationtoken.canbecanceled?view=net-5.0)? If the app instead wants to know the current situation only, I imagine it could call [ILogger.IsEnabled(LogLevel)](https://docs.microsoft.com/dotnet/api/microsoft.extensions.logging.ilogger.isenabled?view=dotnet-plat-ext-5.0) with LogLevel.Critical, which is the highest level.

**Comment by CobusKruger** [comment] 2021-03-31 14:19
`ILoggerFactory` is abstracted exactly so you can create your own loggers using whatever logic needed. If I supply a `NullLoggerFactory`, I expect `NullLogger` instances whenever code creates a logger from that factory. Likewise, if I create a custom `ILoggerFactory`, I expect loggers to be created using the type and logic in that custom implementation. Creating them using some internal logic, makes any attempt to use a different `ILoggerFactory` completely pointless.

In my case, a shared component logs a large volume to the app service console for diagnostic purposes. Reusing that same code in a user-facing command line app now dumps all that into the console. I supplied the `NullLoggerFactory` with the reasonable expectation that it would create a `NullLogger<T>`, but that wasn't the result.

**Comment by davidfowl** [comment] 2021-03-31 14:23
I appreciate that but being an extension method that's impossible right now without more changes. Also I haven't seen the reason why this is a problem? Why does your shared component need to cast to the null logger? Is it just your test that's broken?

**Comment by CobusKruger** [comment] 2021-03-31 15:10
Well no, not a test. See my explanation in the previous message. Not that having "just the test" break would make it any less of an issue. It becomes pointless to override `ILoggerFactory` at all.

I don't see why this was added as an extension method in the first place, but being an extension method doesn't work as a reason to break the purpose of the interface it extends.

Think about the way `System.Linq` works. _Everything_ is an extension method. But those extension methods don't make assumptions about the concrete implementation of the `IEnumerable<T>` that cause surprises. For example, whether I call `Contains` on a list or array, it works on both. And calling it on an array doesn't suddenly turn my array into a list. It's not a perfect analogy, but Linq extension methods work with whatever you supply; they don't replace it.

**Comment by davidfowl** [comment] 2021-03-31 15:20
Sorry I feel like I'm being dense. Why does passing a null logger factory and calling CreateLogger\<T\> suddenly log to the console? What am I missing? 

Do you have a code sample?

**Comment by CobusKruger** [comment] 2021-03-31 15:36
@davidfowl the test I included in the initial post shows the problem. The reason the output goes to the console, is because the logger created by `CreateLogger<T>` is **not** a NullLogger. So the shared code receives an `ILoggerFactory`, which could be a `NullLoggerFactory`, but the actual logger created from it is **not** a `NullLogger`.

@KalleOlaviNiemitalo and yet, it logs to the console.

**Comment by davidfowl** [comment] 2021-03-31 15:42
@CobusKruger I think you're running into something else. The only reason something would log to the console is because the main ILoggerFactory instance has a console logger provider registered. Your test doesn't show the problem.

**Comment by davidfowl** [comment] 2021-03-31 15:43
Sorry, when I mean doesn't show the problem, it shows that a NullLogger isn't returned but it doesn't explain the console thing. That's another issue.

**Comment by CobusKruger** [comment] 2021-03-31 15:44
Right, but neither can you remove a logger provider at runtime, right? And a null logger would not be logging to the console.

**Comment by KalleOlaviNiemitalo** [comment] 2021-03-31 15:44
What is the output to the console? Your test does not call the Log method, so the output could be coming from somewhere else altogether.

**Comment by CobusKruger** [comment] 2021-03-31 15:57
The test does not log to the console. The problem is that it logs at all. A `NullLogger` should not be logging anything.

**Comment by davidfowl** [comment] 2021-03-31 16:03
A null logger doesn't log anything. When you call CreateLogger\<T\>, it just wraps the underlying NullLogger implementation in this case. It's a passthrough wrapper that preserves the behavior of the existing logger impl. As I asked in my original post, the 2 downsides are:
- Performance - We allocate another logger that wraps your logger
- Casting - Code that needs to check for specific implementations have broken expectations (like your test)

Beyond that, I don't see where the problem is.

**Comment by maryamariyan** [comment] 2021-04-23 09:22
> @KalleOlaviNiemitalo and yet, it logs to the console.

> A NullLogger should not be logging anything.

the logger we get from NullLoggerFactory does not log anything and not to console either.

Since there is no sample code, I am just going to guess maybe your issue can be illustrated as follows: 

For example with the sample code below:

```csharp
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;
using System;
using System.Threading;
using System.Threading.Tasks;


public class Program
{
    public static async Task Main(string[] args)
    {
        using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(3));
        await CreateHostBuilder(args).Build().RunAsync(cts.Token);
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureLogging((hostingContext, logging) =>
            {
                logging.ClearProviders();
                logging.AddConsole();
            })
            .ConfigureServices((hostContext, services) =>
            {
                services.AddHostedService<SomeHostedService>();
            });
}

public class SomeHostedService : BackgroundService
{
    public SomeHostedService(ILogger<SomeHostedService> logger)
    {
        var factory = NullLoggerFactory.Instance;
        Logger = logger;
        // Logger = factory.CreateLogger<SomeHostedService>(); // uncomment to contrast
    }

    private ILogger Logger { get; }

    protected override Task ExecuteAsync(CancellationToken stoppingToken)
    {
        new Thread(() => LogCriticalMessage(stoppingToken)).Start();

        return Task.CompletedTask;
    }

    private void LogCriticalMessage(CancellationToken cancellationToken)
    {
        Logger.LogCritical("Some critical message to log.");
    }
}
```

Since ConsoleLogger is responsible for logging to console, and NullLogger should noop:

then when `// Logger = factory.CreateLogger<SomeHostedService>();` gets uncommented, output would skip writing:
```
crit: SomeHostedService[0]
      Some critical message to log.
```
but other portions of the entire application should and will log messages to console because the ctor injected `ILogger<T>` is configured to write to console.

**Comment by maryamariyan** [comment] 2021-04-23 09:22
Closing issue due to https://github.com/dotnet/runtime/issues/50427#issuecomment-811183230

**Closed by maryamariyan** 2021-04-23 09:22 UTC
Labels: area-Extensions-Logging
