### ISSUE TITLE
[API Proposal]: Add additional parameter to PutAsJsonAsync to control whether to use chunked transfer encoding

### ISSUE THREAD

**Issue by abatishchev** [dotnet/runtime#94124] opened 2023-10-27 23:10 UTC
### Background and motivation

I like very much the previous version (sort of) of this extension method `ReadAsAsync<T>()` from the [Microsoft.AspNet.WebApi.Client package ](https://www.nuget.org/packages/Microsoft.AspNet.WebApi.Client/) which I continued using even after migrating away from WebApi. So I was an early adopter of its modern versions:

- [PutAsJsonAsync<T>()](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.json.httpclientjsonextensions.putasjsonasync?view=net-7.0)
- [PostAsJsonAsync<T>()](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.json.httpclientjsonextensions.postasjsonasync?view=net-7.0)
- [PatchAsJsonAsync<T>()](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.json.httpclientjsonextensions.patchasjsonasync?view=net-7.0)
 
Past ~4 years I'm actively working in the Azure Resource Manager (ARM) space, build and run my own Resource Provider (RP). integrate with other RPs, etc. [ARM REST API](https://learn.microsoft.com/en-us/rest/api/resources/) has actively been worked on, but its history dates back in 2014, so it's pretty old and mature. In my experience, it doesn't support chunked encoding and/or requests without Content-Length, would return `400 BadRequest` in one way or another.

And that's the problem with `PutAsJsonAsyn()`: it uses chunked transfer encoding without an option to change the behavior.

### API Proposal

Add an overload accepting `RequestOptions requestOptions` which also can be simply a `bool`.
 
```csharp
public static Task<HttpResponseMessage> PutAsJsonAsync<TValue>(
    this HttpClient client,
    Uri? requestUri,
    TValue value,
    RequestOptions requestOptions = default, // <-- new parameter
    JsonSerializerOptions? options = default,
    CancellationToken cancellationToken = default);

public class RequestOptions
{
    public bool DotNotSendChunked { get; set; }
}
```

### API Usage

```csharp
// setup
var httpClient = new HttpClient
{
    BaseAddress = new Uri("https://management.azure.com"),
    DefaultRequestHeaders =
    {
        Authorization = new AuthenticationHeaderValue("Bearer", "{token}")
    }
};

// usage
var requestOptions = new RequestOptions
{
    DotNotSendChunked  = true
};
var response = await httpClient.PostAsJsonAsync(url, resource, requestOptions);
```

### Alternative Designs

```csharp
var response = await httpClient.PostAsJsonAsync(url, resource, dotNotSendChunked: true);
```

### Risks

1. A `bool` parameter is more readable and discoverable, but `RequestOptions` would simplify further extension of the API's behavior.

**Comment by davidfowl** [comment] 2023-10-28 19:04
HTTP servers in 2023 that don't support chunked encoding make me very sad. Also, this distinction is gone in HTTP/2, they are just data frames as part of the request (there's no chunked vs unchunked body frames). I think instead the API should say something about content being buffered vs not. 

FYI it's possible to do this today using the lower-level JSON API:

```C#
var client = new HttpClient();
var content = JsonContent.Create(new { Name = "Test" });
await content.LoadIntoBufferAsync(); // Potentially very bad for memory
var response = await client.PostAsync("http://localhost:5000/api/Projects", content);
```

**Comment by abatishchev** [comment] 2023-10-28 19:15
> FYI it's possible to do this today using the lower-level JSON API:

Yes, I was thinking to implement the proposal exactly using this method:

```c#
public static async Task<HttpResponseMessage> PutAsJsonAsync<TValue>(
    this HttpClient client,
    Uri? requestUri,
    TValue value,
    RequestOptions requestOptions = default, // <-- new parameter
    JsonSerializerOptions? options = default,
    CancellationToken cancellationToken = default)
{
    // existing code
    var content = JsonContent.Create(value);

    if (requestOptions.DotNotSendChunked)
    {
        await content.LoadIntoBufferAsync();
    }

    // rest of existing code
}
```

or maybe instantiating a new subclass `NotChunkedJsonContent` which would call this method on itself (and make it a bit more composable and object oriented).

What's the difference (and the main benefit), you may ask - increased _inutility_ of the API.

**Comment by karelz** [comment] 2023-11-06 15:51
Chunked encoding is MUST support part of HTTP/1.1 RFC (see [7.1 Chunked Transfer Coding](https://datatracker.ietf.org/doc/html/rfc9112#section-7.1)).
If the server does not fully support HTTP/1.1 spec, then it is primarily problem of the server. Did you make them aware of the problem?

When someone runs into such misbehaving server, they will have to debug the problem first (losing time) and go "low level" anyway. Only when they understand the problem and identify it as chunked encoding is not supported by the server, then they can start to think about how to avoid it -- either via the proposed API or via the simple workaround above. I would argue, that once someone understands the root cause, they will be already "low level" enough to come up with the workaround idea.

On the other hand, if we introduce the new API, we will ask all/many developers to choose which API to use when and why -- incl. understanding what the new option means. The cognitive cost of adding new API is HUGE.

Given that this is first report in years (very rare scenario) and there is easy workaround, I recommend to not pollute our API with yet another option.

**Comment by CarnaViire** [comment] 2023-11-13 15:03
Triage: given that this is a rare corner-case of a non-RFC-compliant server, and that there is a two-liner workaround, team consensus is to close the issue. If you have any additional strong evidence that we should consider, feel free to reopen. Thanks!

**Closed by CarnaViire** 2023-11-13 15:03 UTC
Labels: api-suggestion, area-System.Net.Http, untriaged, needs-further-triage
