### ISSUE TITLE
STJ Serializer - bad serialization results

### ISSUE THREAD

**Issue by zachsaw** [dotnet/runtime#46117] opened 2020-12-16 04:03 UTC
Unit test to reproduce the problem:

```C#
        [Test]
        public async Task StjSerializerBug()
        {
            var foo = new Foo
            {
                Bars = new IBar[] {new Bar1 {Bar1Name = "FooBar1", Type = "Bar1"}}.Append(new Bar2 {Bar2Name = "FooBar2", Type = "Bar2"})
            };
            await using var stream = new MemoryStream();
            await System.Text.Json.JsonSerializer.SerializeAsync(stream, foo);

            stream.Position = 0;
            using var reader = new StreamReader(stream);
            var text = await reader.ReadToEndAsync();
            Assert.AreEqual(Newtonsoft.Json.JsonConvert.SerializeObject(foo), text); // STJ Serializer failed
        }

        public interface IBar
        {
            public string Type { get; set; }
        }

        public class Bar1 : IBar
        {
            public string Bar1Name { get; set; }
            public string Type { get; set; }
        }

        public class Bar2 : IBar
        {
            public string Bar2Name { get; set; }
            public string Type { get; set; }
        }

        public class Foo
        {
            public IEnumerable<IBar> Bars { get; set; }
        }
```

* Which version of .NET is the code running on?
.net 5.0

* What OS and version, and what distro if applicable?
mac OS Catalina and Amazon Linux 2

* What is the architecture (x64, x86, ARM, ARM64)?
x64

* Do you know whether it is specific to that configuration?
It is not specific to this config

* Do you know of any workarounds?
Yes - use Newtonsoft Serializer.

**Comment by GrabYourPitchforks** [comment] 2020-12-16 04:51
Possible duplicate of https://github.com/dotnet/runtime/issues/29937.

Can you clarify the _exact_ output you expect? _System.Text.Json_ and _Newtonsoft.Json_ are different libraries with different default policies, so it's reasonable that they'd produce different outputs.

**Comment by zachsaw** [comment] 2020-12-16 05:17
There are missing fields in the output - i.e. `Bar1Name` and `Bar2Name`. Newtonsoft faithfully serialises the objects correctly.

**Comment by layomia** [comment] 2020-12-17 22:58
Dup of https://github.com/dotnet/runtime/issues/29937. Planned for .NET 6.0.

**Closed by layomia** 2020-12-17 22:58 UTC
Labels: area-System.Text.Json
