### ISSUE TITLE
Test failure JIT/Directed/debugging/debuginfo/tester/tester.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#62173] opened 2021-11-30 01:51 UTC
Run: [runtime-coreclr r2r-extra 20211128.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1488310&view=ms.vss-test-web.build-test-results-tab&runId=42557340&paneView=debug&resultId=109646)

Failed test:
```
R2R Linux arm Checked gcstress0xf @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- JIT/Directed/debugging/debuginfo/tester/tester.sh

R2R Linux x64 Checked gcstress0xf @ Ubuntu.1804.Amd64.Open

- JIT/Directed/debugging/debuginfo/tester/tester.sh

```
**Error message:**
```
rm: cannot remove 'IL-CG2/composite-r2r.dll': No such file or directory
/root/helix/work/workitem/e/JIT/Directed/debugging/debuginfo/tester/tester.sh: line 246: -r:/root/helix/work/workitem/e/JIT/Directed/debugging/debuginfo/tester/IL-CG2/*.dll: No such file or directory
rm: cannot remove '/root/helix/work/workitem/e/JIT/Directed/debugging/debuginfo/tester/attribute.dll.rsp': No such file or directory
rm: cannot remove '/root/helix/work/workitem/e/JIT/Directed/debugging/debuginfo/tester/common.dll.rsp': No such file or directory
rm: cannot remove '/root/helix/work/workitem/e/JIT/Directed/debugging/debuginfo/tester/tester.dll.rsp': No such file or directory
rm: cannot remove '/root/helix/work/workitem/e/JIT/Directed/debugging/debuginfo/tester/tests_d.dll.rsp': No such file or directory
rm: cannot remove '/root/helix/work/workitem/e/JIT/Directed/debugging/debuginfo/tester/tests_r.dll.rsp': No such file or directory
Process terminated. Assertion failed.
at System.RuntimeType.GetMethodBase(RuntimeType reflectedType, RuntimeMethodHandleInternal methodHandle)
at DebugInfoTest.<>c__DisplayClass3_0.<ValidateMappings>b__3()
at Tracing.Tests.Common.IpcTraceTest.Validate()
at Tracing.Tests.Common.IpcTraceTest.RunAndValidateEventCounts(Dictionary2 expectedEventCounts, Action eventGeneratingAction, Nullable1 sessionConfiguration, Func`2 optionalTraceValidator)
at DebugInfoTest.Main()
/root/helix/work/workitem/e/JIT/Directed/debugging/debuginfo/tester/tester.sh: line 379:  6125 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.Directed/debugging/debuginfo/tester/tester.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/root/helix/work/workitem/e/JIT/Directed/debugging/debuginfo/tester/IL-CG2/attribute.dll
Response file: /root/helix/work/workitem/e/JIT/Directed/debugging/debuginfo/tester/attribute.dll.rsp
/root/helix/work/workitem/e/JIT/Directed/debugging/debuginfo/tester/IL-CG2/attribute.dll
-o:/root/helix/work/workitem/e/JIT/Directed/debugging/debuginfo/tester/attribute.dll
-r:/root/helix/work/correlation/System..dll
-r:/root/helix/work/correlation/Microsoft..dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--targetarch:arm
-O
Running CrossGen2:  dotnet /root/helix/work/correlation/crossgen2/crossgen2.dll @/root/helix/work/workitem/e/JIT/Directed/debugging/debuginfo/tester/attribute.dll.rsp

Emitting R2R PE file: /root/helix/work/workitem/e/JIT/Directed/debugging/debuginfo/tester/attribute.dll
/root/helix/work/workitem/e/JIT/Directed/debugging/debuginfo/tester/IL-CG2/common.dll
Response file: /root/helix/work/workitem/e/JIT/Directed/debugging/debuginfo/tester/common.dll.rsp
/root/helix/work/workitem/e/JIT/Directed/debugging/debuginfo/tester/IL-CG2/common.dll
-o:/root/helix/work/workitem/e/JIT/Directed/debugging/debuginfo/tester/common.dll
-r:/root/helix/work/correlation/System..dll
-r:/root/helix/work/correlation/Microsoft..dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--targetarch:arm
-O
Running CrossGen2:  dotnet /root/helix/work/correlation/crossgen2/crossgen2.dll @/root/helix/work/workitem/e/JIT/Directed/debugging/debuginfo/tester/common.dll.rsp

Emitting R2R PE file: /root/helix/work/workitem/e/JIT/Directed/debugging/debuginfo/tester/common.dll
/root/helix/work/workitem/e/JIT/Directed/debugging/debuginfo/tester/IL-CG2/tester.dll
Response file: /root/helix/work/workitem/e/JIT/Directed/debugging/debuginfo/tester/tester.dll.rsp
/root/helix/work/workitem/e/JIT/Directed/debugging/debuginfo/tester/IL-CG2/tester.dll
-o:/root/helix/work/workitem/e/JIT/Directed/debugging/debuginfo/tester/tester.dll
-r:/root/helix/work/correlation/System..dll
-r:/root/helix/work/correlation/Microsoft..dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--targetarch:arm
-O
Running CrossGen2:  dotnet /root/helix/work/c


Stack trace
   at JIT_Directed._debugging_debuginfo_tester_tester_._debugging_debuginfo_tester_tester_sh()
```
or
```
rm: cannot remove 'IL-CG2/composite-r2r.dll': No such file or directory
/datadisks/disk1/work/9C8B08DA/w/A08208C9/e/JIT/Directed/debugging/debuginfo/tester/tester.sh: line 246: -r:/datadisks/disk1/work/9C8B08DA/w/A08208C9/e/JIT/Directed/debugging/debuginfo/tester/IL-CG2/*.dll: No such file or directory
rm: cannot remove '/datadisks/disk1/work/9C8B08DA/w/A08208C9/e/JIT/Directed/debugging/debuginfo/tester/attribute.dll.rsp': No such file or directory
rm: cannot remove '/datadisks/disk1/work/9C8B08DA/w/A08208C9/e/JIT/Directed/debugging/debuginfo/tester/common.dll.rsp': No such file or directory
rm: cannot remove '/datadisks/disk1/work/9C8B08DA/w/A08208C9/e/JIT/Directed/debugging/debuginfo/tester/tester.dll.rsp': No such file or directory
rm: cannot remove '/datadisks/disk1/work/9C8B08DA/w/A08208C9/e/JIT/Directed/debugging/debuginfo/tester/tests_d.dll.rsp': No such file or directory
rm: cannot remove '/datadisks/disk1/work/9C8B08DA/w/A08208C9/e/JIT/Directed/debugging/debuginfo/tester/tests_r.dll.rsp': No such file or directory
Process terminated. Assertion failed.
at System.RuntimeType.GetMethodBase(RuntimeType reflectedType, RuntimeMethodHandleInternal methodHandle)
at DebugInfoTest.<>c__DisplayClass3_0.<ValidateMappings>b__3()
at Tracing.Tests.Common.IpcTraceTest.Validate()
at Tracing.Tests.Common.IpcTraceTest.RunAndValidateEventCounts(Dictionary2 expectedEventCounts, Action eventGeneratingAction, Nullable1 sessionConfiguration, Func`2 optionalTraceValidator)
at DebugInfoTest.Main()
/datadisks/disk1/work/9C8B08DA/w/A08208C9/e/JIT/Directed/debugging/debuginfo/tester/tester.sh: line 379:  1856 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /datadisks/disk1/work/9C8B08DA/w/A08208C9/uploads/Reports/JIT.Directed/debugging/debuginfo/tester/tester.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/datadisks/disk1/work/9C8B08DA/w/A08208C9/e/JIT/Directed/debugging/debuginfo/tester/IL-CG2/attribute.dll
Response file: /datadisks/disk1/work/9C8B08DA/w/A08208C9/e/JIT/Directed/debugging/debuginfo/tester/attribute.dll.rsp
/datadisks/disk1/work/9C8B08DA/w/A08208C9/e/JIT/Directed/debugging/debuginfo/tester/IL-CG2/attribute.dll
-o:/datadisks/disk1/work/9C8B08DA/w/A08208C9/e/JIT/Directed/debugging/debuginfo/tester/attribute.dll
-r:/datadisks/disk1/work/9C8B08DA/p/System..dll
-r:/datadisks/disk1/work/9C8B08DA/p/Microsoft..dll
-r:/datadisks/disk1/work/9C8B08DA/p/mscorlib.dll
--verify-type-and-field-layout
--targetarch:x64
-O
Running CrossGen2:  dotnet /datadisks/disk1/work/9C8B08DA/p/crossgen2/crossgen2.dll @/datadisks/disk1/work/9C8B08DA/w/A08208C9/e/JIT/Directed/debugging/debuginfo/tester/attribute.dll.rsp

Emitting R2R PE file: /datadisks/disk1/work/9C8B08DA/w/A08208C9/e/JIT/Directed/debugging/debuginfo/tester/attribute.dll
/datadisks/disk1/work/9C8B08DA/w/A08208C9/e/JIT/Directed/debugging/debuginfo/tester/IL-CG2/common.dll
Response file: /datadisks/disk1/work/9C8B08DA/w/A08208C9/e/JIT/Directed/debugging/debuginfo/tester/common.dll.rsp
/datadisks/disk1/work/9C8B08DA/w/A08208C9/e/JIT/Directed/debugging/debuginfo/tester/IL-CG2/common.dll
-o:/datadisks/disk1/work/9C8B08DA/w/A08208C9/e/JIT/Directed/debugging/debuginfo/tester/common.dll
-r:/datadisks/disk1/work/9C8B08DA/p/System..dll
-r:/datadisks/disk1/work/9C8B08DA/p/Microsoft..dll
-r:/datadisks/disk1/work/9C8B08DA/p/mscorlib.dll
--verify-type-and-field-layout
--targetarch:x64
-O
Running CrossGen2:  dotnet /datadisks/disk1/work/9C8B08DA/p/crossgen2/crossgen2.dll @/datadisks/disk1/work/9C8B08DA/w/A08208C9/e/JIT/Directed/debugging/debuginfo/tester/common.dll.rsp

Emitting R2R PE file: /datadisks/disk1/work/9C8B08DA/w/A08208C9/e/JIT/Directed/debugging/debuginfo/tester/common.dll
/datadisks/disk1/work/9C8B08DA/w/A08208C9/e/JIT/Directed/debugging/debuginfo/tester/IL-CG2/tester.dll
Response file: /datadisks/disk1/work/9C8B08DA/w/A08208C9/e/JIT/Directed/debugging/debuginfo/tester/tester.dll.rsp
/d


Stack trace
   at JIT_Directed._debugging_debuginfo_tester_tester_._debugging_debuginfo_tester_tester_sh()
```

**Comment by jakobbotsch** [comment] 2021-11-30 08:44
Duplicate of #62118

**Closed** 2021-11-30 08:44 UTC
Labels: arch-arm32, os-linux, GCStress, arch-x64, area-crossgen2-coreclr, untriaged
