### ISSUE TITLE
System.IO.Compression.GzipStreamUnitTests.ReadWrite_Success library test failed

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#65891] opened 2022-02-25 12:24 UTC
The `System.IO.Compression.GzipStreamUnitTests.ReadWrite_Success(mode: AsyncMemory, writeSize: 1, startWithFlush: True)` library test failed on `net7.0-Linux-Release-arm64-CoreCLR_checked-(Alpine.314.Arm64.Open)`

```
    System.IO.Compression.GzipStreamUnitTests.ReadWrite_Success(mode: AsyncMemory, writeSize: 1, startWithFlush: True) [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/libraries/Common/tests/System/IO/ConnectedStreams.cs(309,0): at System.IO.ConnectedStreams.BidirectionalStreamBufferStream.Dispose(Boolean disposing)
           at System.IO.Stream.Close()
        /_/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/DeflateStream.cs(685,0): at System.IO.Compression.DeflateStream.Dispose(Boolean disposing)
           at System.IO.Stream.Close()
        /_/src/libraries/System.IO.Compression/src/System/IO/Compression/GZipStream.cs(159,0): at System.IO.Compression.GZipStream.Dispose(Boolean disposing)
           at System.IO.Stream.Close()
        /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs(1729,0): at System.IO.Tests.ConnectedStreamConformanceTests.ReadWrite_Success(ReadWriteMode mode, Int32 writeSize, Boolean startWithFlush)
        --- End of stack trace from previous location ---
```
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1632031&view=ms.vss-test-web.build-test-results-tab&runId=45241362&paneView=debug&resultId=157993)
[Console log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-ff1e4a94729548a6b2/System.IO.Compression.Tests/1/console.e0e03d1d.log?sv=2019-07-07&se=2022-03-17T08%3A46%3A49Z&sr=c&sp=rl&sig=4Rrw1gRWXaB3M0PBj%2FF%2BsvPEo9P2Rvn%2BkWEagvpafqU%3D)

**Comment by adamsitnik** [comment] 2022-02-25 17:38
Duplicate of https://github.com/dotnet/runtime/issues/65476

**Closed by adamsitnik** 2022-02-25 17:38 UTC
Labels: area-System.IO.Compression, untriaged
