### ISSUE TITLE
System.IO.FileLoadException:  File name: 'Azure.Core, Version=1.19.0.0

### ISSUE THREAD

**Issue by ddobric** [dotnet/runtime#63396] opened 2022-01-05 13:58 UTC
We have a .NET 6 application that uses "Azure.Storage.Blobs" Version="12.10.0". This package uses implicitly  "Azure.Storage.Common" Version 12.9.0, which depends on "Azure.Core" "Version 1.19.0".

When the application starts, it all works fine.

However, when the application is published within Visual Studio it will fail with the **FileLoadException.

Following settings are used in VS to publish the single file:

![image](https://user-images.githubusercontent.com/1756871/148229107-31aea3de-3ece-471b-af25-b30c4a9ac025.png)

### To Reproduce

Create the .net6 application, reference the Azure.Storage.Blobs package and paste the following line:

~~~csharp
 var client = new BlobServiceClient(config.ConnectionString);
~~~

### Exceptions

> System.IO.FileLoadException:  File name: 'Azure.Core, Version=1.19.0.0

![image](https://user-images.githubusercontent.com/1756871/148229400-f3c68788-cc25-40dc-b280-0e06637ff24e.png)

I apologize if this issue is not the SDK issue, but rather the VS tooling or even .NET issue. 

### Workaround
If the "Enable ReadyToRun Compilation" is disabled, all works fine.

![image](https://user-images.githubusercontent.com/1756871/148232029-1f0057e2-cfbc-4ae7-bde7-aa2c20cb0049.png)

**Comment by jeffschwMSFT** [comment] 2022-01-05 15:14
@agocke and @mangod9 can y'all take a look?

**Comment by mangod9** [comment] 2022-01-05 15:42
Hi @ddobric, does the app work without singlefile or Trimming, but with R2R enabled? We will also try to repro locally. Thx.

**Comment by agocke** [comment] 2022-01-05 17:49
@mangod9 suggestion is good, but my suspicion is that trimming is not compatible with your application. When you publish, do trim warnings get produced in the output?

I would also try disabling just trimming, specifically. Your may application may work afterwards.

**Comment by vitek-karas** [comment] 2022-01-05 18:20
I have a different suspicion (based on the fact that trimmed but non-R2R works) - trimming will produce assemblies which have lot of unresolvable type-refs (and even assembly refs). If R2R changes how the runtime loads these, it can easily trigger a resolution of such a type which points to removed assembly.

Basically the "copy" mode in the trimmer is potentially problematic when combined with R2R, since it relies on the runtime to be super lazy.

**Comment by ddobric** [comment] 2022-01-07 21:41
> Hi @ddobric, does the app work without singlefile or Trimming, but with R2R enabled? We will also try to repro locally. Thx.

@mangod9 , the app runs without R2R enabled.

**Comment by mangod9** [comment] 2022-01-07 23:34
so just to clarify it fails with R2R enabled, but with trimming/singlefile disabled?

**Comment by ddobric** [comment] 2022-01-10 13:09
We will test this and post results here.

**Comment by AnhNguyenDaenet** [comment] 2022-01-10 13:38
Trimming | SingleFile | R2R | Result
--- | --- | --- | --- 
x | x |   | DOES NOT FAIL
x|||DOES NOT FAIL
| | x | |DOES NOT FAIL
|||| DOES NOT FAIL
x | x | x | FAILS
x | | x  | FAILS
| | x | x | FAILS
|||x|FAILS

The table above shows the test results with the combinations of publishing options we have chosen.

**Comment by ddobric** [comment] 2022-01-10 21:02
@mangod9 , as you see above, the failing clearly correlates to R2R.

**Comment by ddobric** [comment] 2022-04-30 13:28
Any feedback on this?

**Comment by mangod9** [comment] 2022-05-02 15:42
Sorry havent had a chance to look at this, will try to repro this.. @trylek as fyi.

**Comment by ddobric** [comment] 2022-07-02 10:25
Anything new here?

**Comment by mangod9** [comment] 2022-07-19 16:32
@ivdiazsa can you please try to repro this?

**Comment by ivdiazsa** [comment] 2022-07-19 21:12
I've been trying to repro this with simple example apps, but to no avail. What Project Template are you using @ddobric? And where does the `config` from where you're getting the `ConnectionString` come from?

**Comment by ivdiazsa** [comment] 2022-08-04 22:50
Closing for now due to no updates and I haven't been able to reproduce in my local environment. We can reopen if necessary.

**Closed by ivdiazsa** 2022-08-04 22:50 UTC
Labels: area-ReadyToRun-coreclr
