### ISSUE TITLE
Test failure: System.BadImageFormatException: The file is not a ReadyToRun image

### ISSUE THREAD

**Issue by JulieLeeMSFT** [dotnet/runtime#83409] opened 2023-03-14 17:44 UTC
Run: [runtime-outerloop 20230311.4](https://dnceng-public.visualstudio.com/public/_build/results?buildId=201699)

Failed test:
```
R2R-CG2 linux arm64 Checked no_tiered_compilation @ (Alpine.315.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.15-helix-arm64v8
- Regressions/coreclr/GitHub_42732/test42732/test42732.sh
```

Error Message:
```
        BEGIN EXECUTION
        in takeLock
        /root/helix/work/workitem/e/Regressions/coreclr/GitHub_42732/test42732/IL-CG2/TestLibrary.dll
        03:06:43
        Response file: /root/helix/work/workitem/e/Regressions/coreclr/GitHub_42732/test42732/TestLibrary.dll.rsp
        /root/helix/work/workitem/e/Regressions/coreclr/GitHub_42732/test42732/IL-CG2/TestLibrary.dll
        -o:/root/helix/work/workitem/e/Regressions/coreclr/GitHub_42732/test42732/TestLibrary.dll
        -r:/root/helix/work/correlation/System.*.dll
        -r:/root/helix/work/correlation/Microsoft.*.dll
        -r:/root/helix/work/correlation/mscorlib.dll
        --verify-type-and-field-layout
        --method-layout:random
        --targetarch:arm64
        --targetos:linux
        -O
        Running CrossGen2:  dotnet /root/helix/work/correlation/crossgen2/crossgen2.dll @/root/helix/work/workitem/e/Regressions/coreclr/GitHub_42732/test42732/TestLibrary.dll.rsp  
        [createdump] Gathering state for process 4217 dotnet
        [createdump] Crashing thread 00001079 signal 00000006
        [createdump] Writing crash report to file /home/helixbot/dotnetbuild/dumps/coredump.4217.dmp.crashreport.json
        [createdump] Crash report successfully written
        [createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.4217.dmp
        [createdump] Written 59490304 bytes (14524 pages) to core file
        [createdump] Target process is alive
        [createdump] Dump successfully written in 3071ms
        Running R2RDump:  dotnet /root/helix/work/correlation/R2RDump/R2RDump.dll --header --sc --in /root/helix/work/workitem/e/Regressions/coreclr/GitHub_42732/test42732/TestLibrary.dll --out /root/helix/work/workitem/e/Regressions/coreclr/GitHub_42732/test42732/TestLibrary.dll.r2rdump --val
        Error: System.BadImageFormatException: The file is not a ReadyToRun image
           at ILCompiler.Reflection.ReadyToRun.ReadyToRunReader.Initialize(IAssemblyMetadata metadata) in /_/src/coreclr/tools/aot/ILCompiler.Reflection.ReadyToRun/ReadyToRunReader.cs:line 470
           at R2RDump.Program.Run() in /_/src/coreclr/tools/r2rdump/Program.cs:line 447
        03:06:48
        Crossgen2 failed with exitcode: 134
        in ReleaseLock
        Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 3/12/2023 3:06:43 AM
        Processing /home/helixbot/dotnetbuild/dumps/coredump.4217.dmp.crashreport.json
        Printing stacktrace from '/home/helixbot/dotnetbuild/dumps/coredump.4217.dmp.crashreport.json'
        Invoking llvm-symbolizer --pretty-print
        Errors while running llvm-symbolizer --pretty-print
        System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'llvm-symbolizer' with working directory '/root/helix/work/workitem/e'. No such file or directory
           at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
           at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
           at CoreclrTestLib.CoreclrTestWrapperLib.TryPrintStackTraceFromCrashReport(String crashReportJsonFile, StreamWriter outputWriter)
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/root/helix/work/correlation
        > /root/helix/work/workitem/e/Regressions/coreclr/GitHub_42732/test42732/test42732.sh
```

**Comment by mangod9** [comment] 2023-03-14 18:39
@trylek @cshung is this a new test for R2RDump?

**Comment by cshung** [comment] 2023-03-14 19:03
This is the logic I added in the test harness to run r2rdump whenever crossgen2 is run. Looking at the log, it looks like crossgen2 failed, we created a dump, which is the root cause of the test failure.

It looks like in the `CLRTest.crossgen2.targets`, there is some logic to skip R2RDump execution when crossgen2 failed, but the logic was only for Windows, that's why we also see a failure stack trace for R2RDump.

> Skipping R2RDump on crossgen2 only on Windows was by design. Both native and managed binaries are DLL, the harness just calls crossgen2 regardless, so some failures are expected and therefore we let them pass, on Linux/OSX, native binaries are not DLL and therefore we do not expect crossgen2 to fail)

**Comment by trylek** [comment] 2023-04-17 18:28
I believe that Andrew's R2RDump logic is fine, its failure is just a way of saying that Crossgen2 crashed during test compilation. Maybe we can sit on the bug for a while as I believe JanK mentioned that SDK Preview 3 we have recently rolled forward to contains critical fixes for race conditions on arm64. One way or another, as there have been no recent repros on the issue, it is no longer blocking outerloop.

**Comment by trylek** [comment] 2023-05-03 22:17
Closing as no repro, IIRC JanK mentioned that critical fixes for ARM have been merged in since.

**Closed by trylek** 2023-05-03 22:17 UTC
Labels: area-crossgen2-coreclr
