### ISSUE TITLE
Test failure baseservices/exceptions/unhandled/unhandledTester/unhandledTester.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#96114] opened 2023-12-18 01:35 UTC
**Failed in:** [runtime-coreclr crossgen2 20231216.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=502265&view=ms.vss-test-web.build-test-results-tab&runId=11695616&resultId=113968&paneView=debug)

**Failed tests:**
```
R2R-CG2 osx arm64 Checked no_tiered_compilation @ OSX.1200.ARM64.Open
    - baseservices/exceptions/unhandled/unhandledTester/unhandledTester.cmd
```

**Error message:**
```
/private/tmp/helix/working/B1E20958/w/A92E0955/e/baseservices/exceptions/baseservices-exceptions/../unhandled/unhandledTester/unhandledTester.sh: line 315: -r:/private/tmp/helix/working/B1E20958/w/A92E0955/e/baseservices/exceptions/unhandled/unhandledTester/IL-CG2/*.dll: No such file or directory

cmdLine:/private/tmp/helix/working/B1E20958/w/A92E0955/e/baseservices/exceptions/baseservices-exceptions/../unhandled/unhandledTester/unhandledTester.sh Timed Out (timeout in milliseconds: 1800000 from variable __TestTimeout, start: 12/16/2023 11:12:37 PM, end: 12/16/2023 11:42:37 PM)

Return code:      -100
Raw output file:      /tmp/helix/working/B1E20958/w/A92E0955/uploads/unhandled/unhandledTester/output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/private/tmp/helix/working/B1E20958/w/A92E0955/e/baseservices/exceptions/unhandled/unhandledTester/IL-CG2/TestLibrary.dll
23:12:37
Response file: /private/tmp/helix/working/B1E20958/w/A92E0955/e/baseservices/exceptions/unhandled/unhandledTester/TestLibrary.dll.rsp
/private/tmp/helix/working/B1E20958/w/A92E0955/e/baseservices/exceptions/unhandled/unhandledTester/IL-CG2/TestLibrary.dll
-o:/private/tmp/helix/working/B1E20958/w/A92E0955/e/baseservices/exceptions/unhandled/unhandledTester/TestLibrary.dll
-r:/tmp/helix/working/B1E20958/p/System.*.dll
-r:/tmp/helix/working/B1E20958/p/Microsoft.*.dll
-r:/tmp/helix/working/B1E20958/p/xunit.*.dll
-r:/tmp/helix/working/B1E20958/p/mscorlib.dll
--verify-type-and-field-layout
--method-layout:random
--targetarch:arm64
--targetos:osx
Running CrossGen2:  dotnet /tmp/helix/working/B1E20958/p/crossgen2/crossgen2.dll @/private/tmp/helix/working/B1E20958/w/A92E0955/e/baseservices/exceptions/unhandled/unhandledTester/TestLibrary.dll.rsp  
Emitting R2R PE file: /private/tmp/helix/working/B1E20958/w/A92E0955/e/baseservices/exceptions/unhandled/unhandledTester/TestLibrary.dll
Running R2RDump:  dotnet /tmp/helix/working/B1E20958/p/R2RDump/R2RDump.dll --header --sc --in /private/tmp/helix/working/B1E20958/w/A92E0955/e/baseservices/exceptions/unhandled/unhandledTester/TestLibrary.dll --out /private/tmp/helix/working/B1E20958/w/A92E0955/e/baseservices/exceptions/unhandled/unhandledTester/TestLibrary.dll.r2rdump --val
23:12:38
/private/tmp/helix/working/B1E20958/w/A92E0955/e/baseservices/exceptions/unhandled/unhandledTester/IL-CG2/unhandled.dll
23:12:38
Response file: /private/tmp/helix/working/B1E20958/w/A92E0955/e/baseservices/exceptions/unhandled/unhandledTester/unhandled.dll.rsp
/private/tmp/helix/working/B1E20958/w/A92E0955/e/baseservices/exceptions/unhandled/unhandledTester/IL-CG2/unhandled.dll
-o:/private/tmp/helix/working/B1E20958/w/A92E0955/e/baseservices/exceptions/unhandled/unhandledTester/unhandled.dll
-r:/tmp/helix/working/B1E20958/p/System.*.dll
-r:/tmp/helix/working/B1E20958/p/Microsoft.*.dll
-r:/tmp/helix/working/B1E20958/p/xunit.*.dll
-r:/tmp/helix/working/B1E20958/p/mscorlib.dll
--verify-type-and-field-layout
--method-layout:random
--targetarch:arm64
--targetos:osx
Running CrossGen2:  dotnet /tmp/helix/working/B1E20958/p/crossgen2/crossgen2.dll @/private/tmp/helix/working/B1E20958/w/A92E0955/e/baseservices/exceptions/unhandled/unhandledTester/unhandled.dll.rsp  
Emitting R2R PE file: /private/tmp/helix/working/B1E20958/w/A92E0955/e/baseservices/exceptions/unhandled/unhandledTester/unhandled.dll
Running R2RDump:  dotnet /tmp/helix/working/B1E20958/p/R2RDump/R2RDump.dll --header --sc --in /private/tmp/helix/working/B1E20958/w/A92E0955/e/baseservices/exceptions/unhandled/unhandledTester/unhandled.dll --out /private/tmp/helix/working/B1E20958/w/A92E0955/e/baseservices/exceptions/unhandled/unhandledTester/unhandled.dll.r2rdump --val
23:12:38
/private/tmp/helix/working/B1E20958/w/A92E0955/e/baseservices/exceptions/unhandled/unhandledTester/IL-CG2/unhandledTester.dll
23:12:38
Response file: /private/tmp/helix/working/B1E20958/w/A92E0955/e/baseservices/exceptions/unhandled/unhandledTester/unhandledTester.dll.rsp
/private/tmp/helix/working/B1E20958/w/A92E09
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 128
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor16|0_17(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2023-11-01T09:14:34.267Z | runtime | Checked-no_tiered_compilation | osx.1200.arm64.open | arm64 | baseservices/exceptions/unhandled/unhandledTester/unhandledTester.cmd | Failed | {"Project":"public","System.StageAttempt":"1","Reason":"Schedule","BuildId":"457297","BuildNumber":"20231101.1","System.PhaseName":"run_test_p0_coreclr__osx_arm64_checked","AzurePipelinesTestRunId":"10298760","DefinitionId":"129","architecture":"arm64","DefinitionName":"runtime","System.PhaseAttempt":"1","System.JobId":"53d8f4c3-9599-5751-a535-e5a7f4a4a506","System.JobName":"__default","configuration":"Checked-no_tiered_compilation","System.JobAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.StageName":"Build","operatingSystem":"OSX.1200.ARM64.Open"} | Schedule

**Comment by BruceForstall** [comment] 2023-12-18 19:31
@dotnet/crossgen-contrib

**Comment by janvorli** [comment] 2023-12-18 22:56
It seems that the issue is caused by the helper process that intentionally crashes with an unhandled exception also triggers core dump creation and it somehow causes the test to timeout. I am adding a new flavor of the unhanded exception test in #96138 and I have added disabling the createdump invocation for the crashing process. I think it should fix this issue.

**Comment by JulieLeeMSFT** [comment] 2024-03-12 18:38
CC @janvorli, it failed again in [Pipelines - Runs for runtime-jit-experimental (azure.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fdnceng-public%2Fpublic%2F_build%3FdefinitionId%3D137&data=05%7C02%7CJulie.Lee%40microsoft.com%7Cb0407c0a1dc44c1b73fe08dc37b79c63%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638446508956126447%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=gBlvbqMhrppDChMs3tEyq4DXjGI5hvxswsur1bR0QSQ%3D&reserved=0)

- https://dev.azure.com/dnceng-public/public/_build/results?buildId=596952&view=ms.vss-test-web.build-test-results-tab

```
cmdLine:/private/tmp/helix/working/93D20867/w/9DAE0883/e/baseservices/exceptions/baseservices-exceptions/../unhandled/unhandledTester/unhandledTester.sh Timed Out (timeout in milliseconds: 600000 from variable __TestTimeout, start: 3/10/2024 8:01:51 PM, end: 3/10/2024 8:11:51 PM)
Printing stacktrace from '/cores/crashdump_4294.dmp.crashreport.json'
Invoking llvm-symbolizer --pretty-print
Errors while running llvm-symbolizer --pretty-print
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'llvm-symbolizer' with working directory '/private/tmp/helix/working/93D20867/w/9DAE0883/e/baseservices/exceptions/baseservices-exceptions'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs:line 496
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs:line 456
   at CoreclrTestLib.CoreclrTestWrapperLib.TryPrintStackTraceFromCrashReport(String crashReportJsonFile, TextWriter outputWriter)
Test Harness Exitcode is : -100
To run the test:
Set up CORE_ROOT and run.
> /private/tmp/helix/working/93D20867/w/9DAE0883/e/baseservices/exceptions/baseservices-exceptions/../unhandled/unhandledTester/unhandledTester.sh
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor135|0_136(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
20:14:22.674 Failed test: baseservices/exceptions/unhandled/unhandledTester/unhandledTester.cmd
20:14:23.117 Running test: baseservices/exceptions/unittests/Baadbaad/Baadbaad.cmd
```

**Comment by v-wenyuxu** [comment] 2024-06-19 01:26
**Failed in:** [runtime-coreclr jitstress 20240617.2](https://dev.azure.com/dnceng-public/public/_build/results?buildId=711164&view=ms.vss-test-web.build-test-results-tab&runId=17774310&resultId=122251&paneView=debug)

**Failed tests:**
```
coreclr windows x86 Checked tailcallstress @ Windows.10.Amd64.Open
    - GC\\Scenarios\\FinalizeTimeout\\FinalizeTimeout\\FinalizeTimeout.cmd
```

**Error message:**
```
 
cmdLine:C:\h\w\A49808EC\w\A4EA08C7\e\GC\Scenarios\FinalizeTimeout\FinalizeTimeout\FinalizeTimeout.cmd Timed Out (timeout in milliseconds: 1800000 from variable __TestTimeout, start: 6/18/2024 5:58:17 AM, end: 6/18/2024 6:28:17 AM)

Return code:      -100
Raw output file:      C:\h\w\A49808EC\w\A4EA08C7\uploads\Reports\GC.Scenarios\FinalizeTimeout\FinalizeTimeout\FinalizeTimeout.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\A49808EC\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  FinalizeTimeout.dll 
Main start
Finalizer start
Finalizer end
Main end

cmdLine:C:\h\w\A49808EC\w\A4EA08C7\e\GC\Scenarios\FinalizeTimeout\FinalizeTimeout\FinalizeTimeout.cmd Timed Out (timeout in milliseconds: 1800000 from variable __TestTimeout, start: 6/18/2024 5:58:17 AM, end: 6/18/2024 6:28:17 AM)
Test Harness Exitcode is : -100
To run the test:
> set CORE_ROOT=C:\h\w\A49808EC\p
> C:\h\w\A49808EC\w\A4EA08C7\e\GC\Scenarios\FinalizeTimeout\FinalizeTimeout\FinalizeTimeout.cmd
```

**Stack trace:**
```
   at GC_Scenarios._FinalizeTimeout_FinalizeTimeout_FinalizeTimeout_._FinalizeTimeout_FinalizeTimeout_FinalizeTimeout_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by v-wenyuxu** [comment] 2024-06-20 01:36
**Failed in:** [runtime-coreclr outerloop 20240619.3](https://dev.azure.com/dnceng-public/public/_build/results?buildId=713210&view=ms.vss-test-web.build-test-results-tab&runId=17838424&resultId=122253&paneView=debug)

**Failed tests:**
```
coreclr windows x86 Checked @ Windows.10.Amd64.Open
    - GC\\Scenarios\\FinalizeTimeout\\FinalizeTimeout\\FinalizeTimeout.cmd
```

**Error message:**
```
 
cmdLine:C:\h\w\ACB90932\w\BCDE0A0D\e\GC\Scenarios\FinalizeTimeout\FinalizeTimeout\FinalizeTimeout.cmd Timed Out (timeout in milliseconds: 600000 from variable __TestTimeout, start: 6/19/2024 8:00:16 PM, end: 6/19/2024 8:10:16 PM)

Return code:      -100
Raw output file:      C:\h\w\ACB90932\w\BCDE0A0D\uploads\Reports\GC.Scenarios\FinalizeTimeout\FinalizeTimeout\FinalizeTimeout.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\ACB90932\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  FinalizeTimeout.dll 
Main start
Finalizer start
Finalizer end
Main end

cmdLine:C:\h\w\ACB90932\w\BCDE0A0D\e\GC\Scenarios\FinalizeTimeout\FinalizeTimeout\FinalizeTimeout.cmd Timed Out (timeout in milliseconds: 600000 from variable __TestTimeout, start: 6/19/2024 8:00:16 PM, end: 6/19/2024 8:10:16 PM)
Test Harness Exitcode is : -100
To run the test:
> set CORE_ROOT=C:\h\w\ACB90932\p
> C:\h\w\ACB90932\w\BCDE0A0D\e\GC\Scenarios\FinalizeTimeout\FinalizeTimeout\FinalizeTimeout.cmd
```

**Stack trace:**
```
   at GC_Scenarios._FinalizeTimeout_FinalizeTimeout_FinalizeTimeout_._FinalizeTimeout_FinalizeTimeout_FinalizeTimeout_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by steveisok** [comment] 2024-07-02 19:07
@mangod9 is this more a GC issue?

**Comment by jkotas** [comment] 2024-07-02 19:14
There are multiple unrelated failures logged above:

- baseservices/exceptions/unhandled/unhandledTester/unhandledTester failure is duplicate of  https://github.com/dotnet/runtime/issues/100495
- GC\Scenarios\FinalizeTimeout\FinalizeTimeout failure is duplicate of https://github.com/dotnet/runtime/issues/103874 that should be fixed now.

**Closed by jkotas** 2024-07-02 19:14 UTC
Labels: arch-arm64, os-mac-os-x, area-crossgen2-coreclr, untriaged, blocking-clean-ci-optional
