### ISSUE TITLE
Regressions in Microsoft.Extensions.DependencyInjection.GetService

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#54351] opened 2021-06-17 18:52 UTC
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [a4b3772d1ada339220145843138d4c622134adeb](https://github.com/dotnet/runtime/commit/a4b3772d1ada339220145843138d4c622134adeb)
Compare | [43b1f2c165257faae4d6a4aa886b701b63d2d5c0](https://github.com/dotnet/runtime/commit/43b1f2c165257faae4d6a4aa886b701b63d2d5c0)
Diff | [Diff](https://github.com/dotnet/runtime/compare/a4b3772d1ada339220145843138d4c622134adeb...43b1f2c165257faae4d6a4aa886b701b63d2d5c0)

### Regressions in Microsoft.Extensions.DependencyInjection.GetService

Benchmark | Baseline | Test | Test/Base | Test Quality | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[ServiceScopeProvider - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04/Microsoft.Extensions.DependencyInjection.GetService.ServiceScopeProvider.html>) | 21.97 ns | 38.43 ns | 1.75 | 0.26 | | |
[ServiceScope - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04/Microsoft.Extensions.DependencyInjection.GetService.ServiceScope.html>) | 45.32 ns | 60.61 ns | 1.34 | 0.19 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/06_14_2021/refs/heads/main_x64_ubuntu%2018.04_Regression/Microsoft.Extensions.DependencyInjection.GetService_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/06_14_2021/refs/heads/main_x64_ubuntu%2018.04_Regression/Microsoft.Extensions.DependencyInjection.GetService_2.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/06_14_2021/refs/heads/main_x64_ubuntu%2018.04_Regression/Microsoft.Extensions.DependencyInjection.GetService.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'Microsoft.Extensions.DependencyInjection.GetService*'
```
<details>

### Payloads

[Baseline](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-84118154-61d2-4753-9aa5-7d91f360e7241157b74a2d847b3ac/b2fd9846-55bd-4cf9-860c-45355a1abd96.zip?sv=2019-07-07&se=2021-07-10T04%3A30%3A54Z&sr=c&sp=rl&sig=zoX4zvAgvxmYREIwvORUMSmoM9IaAq79bZTTDx%2F3zcM%3D>)
[Compare](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-258899a6-e611-44a0-bd82-487291cbd08f8f525ac29f34eb3a7/e3480ebb-9555-4c4f-837c-22604502eef3.zip?sv=2019-07-07&se=2021-07-10T17%3A43%3A16Z&sr=c&sp=rl&sig=ATa9Zh4HD3RRZ1FcpQLFrxsGseKxCvfqP7HIAKsYchg%3D>)

#### Microsoft.Extensions.DependencyInjection.GetService.ServiceScopeProvider

```log

```
#### Microsoft.Extensions.DependencyInjection.GetService.ServiceScope

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by eerhardt** [comment] 2021-06-17 19:23
Looks like it is caused by https://github.com/dotnet/runtime/pull/53325. 

cc @maryamariyan @davidfowl @pakrym

**Comment by davidfowl** [comment] 2021-06-17 19:54
bug fix > performance 😄

**Comment by pakrym** [comment] 2021-06-21 15:20
> bug fix > performance 😄

Sure, but did we expect a regression from that change? Is the regression caused by the if check? Can we make it cheaper?

**Comment by davidfowl** [comment] 2021-06-21 15:28
I did yes, it's one extra branch. We should definitely see if we can make the check cheaper but I'm not sure it's worth redesigning anything over. 

Maybe we can do a reference equals for the root scope check or stash a bool instead of service scope itself to avoid that comparison altogether

**Comment by pakrym** [comment] 2021-06-21 15:29
We should try turning IsRootScope into a readonly field.

**Comment by davidfowl** [comment] 2021-06-25 06:45
We should leave this open since the change didn't have much of an impact on this code path.

**Comment by davidfowl** [comment] 2021-06-25 06:56
Looking at the actual benchmark(s) more deeply it seems like:

```
[Benchmark]
public IServiceScopeFactory ServiceScopeProvider() => _serviceScopeFactoryProvider.GetService<IServiceScopeFactory>();

[Benchmark]
public IServiceScope ServiceScope() => _serviceScope.CreateScope();
```

IServiceScopeFactory is a singleton so I wonder if [this part of the change](https://github.com/dotnet/runtime/pull/53325/files#diff-dbe6efa663d61ffefa9c9a4a29e2298fa5aef692229278b34906de4206bd0e2a) made thing worse. I would have thought that @pakrym's change [here](https://github.com/dotnet/runtime/blob/17828d199b0794f1902611e1f2fffa72d734e489/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceProvider.cs#L152) would have been a fine replacement for this but maybe avoiding the call to the runtime resolving when the value is cached is faster.

I don't get why CreateScope is slower.

**Comment by maryamariyan** [comment] 2021-08-03 23:44
The latest charts show we gained back perf numbers after PR https://github.com/dotnet/runtime/pull/54732:

![image](https://user-images.githubusercontent.com/5897654/128099808-c696fed5-e904-45e9-910a-45e35a54ad6c.png)

![image](https://user-images.githubusercontent.com/5897654/128099795-9cc315e1-a901-4bd3-acbf-8e201ac4d749.png)

So this issue can be safely closed.

**Closed by maryamariyan** 2021-08-03 23:44 UTC
Labels: arch-arm64, arch-x64, area-Extensions-DependencyInjection, os-linux, os-windows, tenet-performance, tenet-performance-benchmarks

**Comment by pakrym** [comment] 2021-08-03 23:52
I think the regression is still there:
![image](https://user-images.githubusercontent.com/1697911/128100432-39df4ec5-7b4e-4b7b-bcbd-a288640fa84c.png)
