### ISSUE TITLE
Add testing infrastructure for illinker related changes

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#37258] opened 2020-06-01 15:58 UTC
There is no testing infrastructure and no tests available to verify changes which require add/remove/change annotation or XML descriptors for illinker to work with src/libraries. As we keep adding and modifying them it becomes harder to review such PRs with such changes.

We should come with the testing apps (no testing framework!) which each will verify the code which is supposed to keep the dynamically accessed members.

@vitek-karas @danmosemsft

**Comment by vitek-karas** [comment] 2020-06-01 16:18
@eerhardt

**Comment by eerhardt** [comment] 2020-06-01 17:03
@joperezr was starting to look at #943. Is this a duplicate of that issue? Or is #943 strictly for measuring size, and this is strictly for measuring correctness?

**Comment by marek-safar** [comment] 2020-06-01 18:21
This is not about size at all but about correctness. For example, I should get test failure for every DynamicDependency I remove from the codebase, same with every entry in linker descriptor

**Comment by joperezr** [comment] 2020-06-01 18:29
That was kind of what I thought #943 was tracking but apparently that seems to be size-specific then. This is more or less the plan we have so far on how to add testing for this feature work:

As @eerhardt outlined in his design doc(https://github.com/eerhardt/designs/blob/AddLinkingLibrariesDoc/accepted/2020/linking-libraries.md#testing) there are two major things we will want to add testing for:
1. Does the application still work? 
1. Is the application smaller?

For the first one, we can use this issue to track it. The plan we have so far is to add simple console applications that would try to use the API in question, link them, and ensuring that they can still run by ensuring the application returned some previously defined success return code. (so as to try not to depend on anything else)
We are still checking how to approach this as it will be hard to scale with thousands of simple apps checked in to the runtime repo for this, so I will update this issue once we have an actual plan.

For the second one, we plan on having some tests in the performance repo where we take full Blazor cannonical applications (as well as default template apps) and linking them to establish a baseline, and then running those in some cadence to ensure we don't regress size on disk.

**Comment by marek-safar** [comment] 2020-06-02 15:47
Yes, this is only about "Does the application still work" like scenarios, the other testing scenarios should be discussed in other issues.

Couple of things to consider for implementation. 
- One for all solution might not work here
- The apps will need to run with all illinker sensitive RIDs, most of them are supported in self-contained scenarios only.
- Be able to run the application would be nice but it might be hard in practice as that makes the isolation much harder

**Comment by marek-safar** [comment] 2020-06-03 08:41
> Not sure I fully understand this point.

The point was that in some cases to run the app which includes specific API you want to check you might need to do extra work (add more code to run successfully) and that will alter linker analysis so you will be testing different setup.

Secondly, how do you plan to run cross-compiled tests? Are you going to setup e.g. Android test environment during the build if you plan to run the apps?

**Closed** 2020-06-16 22:00 UTC
Labels: area-Infrastructure, linkable-framework
