### ISSUE TITLE
[API Proposal]: Introduce a few overloads to StringBuilder to eliminate temp allocs

### ISSUE THREAD

**Issue by geeknoid** [dotnet/runtime#68450] opened 2022-04-23 23:53 UTC
### Background and motivation

Adding a few new overloads to StringBuilder can eliminate some temp allocations

### API Proposal

```C#
// extension methods for demonstration, real use would be as instance methods on string builder
public static class StringBuilderExtensions
{
    // avoid producing a transient string
    public static StringBuilder AppendFormattable<T>(this StringBuilder sb, IFormatProvider? provider, string format, T arg)
        where T : ISpanFormattable
    {
        Span<char> buf = stackalloc char[128];
        if (arg.TryFormat(buf, out int charsWritten, format.AsSpan(), provider))
        {
            return sb.Append(buf.Slice(0, charsWritten));
        }

        return sb.Append(arg.ToString(format, provider));
    }

    // avoid boxing value types
    public static StringBuilder Append<T>(this StringBuilder sb, in T value)
        where T : struct
    {
        return sb.Append(value.ToString());
    }
}
```

Similar overloads for Insert would also make sense.

### API Usage

These work like all other StringBuilder overloads.

**Comment by svick** [comment] 2022-04-24 08:05
This is mostly a duplicate of https://github.com/dotnet/runtime/issues/58459 (note that a general `Append<T>` is also discussed there, not just an overload for `ISpanFormattable`).

**Comment by tannergooding** [comment] 2022-08-26 21:18
CC. @stephentoub, could you provide some input/insight here on if this is something you think we should move forward on?

**Comment by stephentoub** [comment] 2022-08-26 22:02
This is already supported with:
```C#
sb.Append(provider, $"{arg:format}");
```
e.g.
[SharpLab](https://sharplab.io/#v2:EYLgtghglgdgPgAQEwEYCwAoBAGABAlAOgBUBTADwBcBuTHfIgcQBsB7YCZqALwkqlYxaWAMz4kuAMK4A3plwL8YhABZcAWQAUAZUoAnWAHMAQgFcozACak9uAM7AAlPMVyMij/eCEAggAc/UhhLTUlTZkpTPVIASRgAM1ZCOIA3CAMIGEowiKjSABpcABIAIhkAET5SYigwUkIAOVYAd0JKgE8AeXiATVJ0kHIAXxLHYQ8hzCGgA===)

If we think that's not sufficiently discoverable, I don't see a huge downside to adding something like this as an additional Append overload, though I suspect it would be mostly for usability rather than enabling something significantly faster.

**Comment by tannergooding** [comment] 2022-08-26 22:35
Thanks! Going to close this for the time being. Please feel free to reopen if anyone feels like the current support isn't discoverable enough and we can discuss it further.

**Closed by tannergooding** 2022-08-26 22:35 UTC
Labels: api-suggestion, area-System.Runtime, needs-further-triage
