### ISSUE TITLE
[release/6.0] SSL and authentication failures affecting branch CI

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#67946] opened 2022-04-13 04:29 UTC
@dotnet/ncl @rzikm @wfurt @karelz There are many SSL and authentication-related failures in the 6.0 branch. Example:

- PR: https://github.com/dotnet/runtime/pull/67928
- Pipeline results: https://dev.azure.com/dnceng/public/_build/results?buildId=1713348&view=results
- Jobs: https://dev.azure.com/dnceng/public/_build/results?buildId=1713348&view=logs&j=b4344b0d-0f92-5d69-ccaf-e0b24fbf14a2&t=65a58faa-a542-5344-b5c8-897139f242cd&l=878
  - Libraries Test Run release coreclr windows x86 Release
  - Libraries Test Run release coreclr windows x86 Debug
  - Libraries Test Run release coreclr windows x64 Debug

### Callstacks

System.Net.Security.Tests.LoggingTest.EventSource_EventsRaisedAsExpected
```
System.Net.Security.Tests.LoggingTest.EventSource_EventsRaisedAsExpected [FAIL]
    Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
    Stack Trace:
      
      Child exception:
        Microsoft.DotNet.XUnitExtensions.SkipTestException: Unstable on Windows 11
      /_/src/libraries/System.Net.Security/tests/FunctionalTests/SslStreamStreamToStreamTest.cs(79,0): at System.Net.Security.Tests.SslStreamStreamToStreamTest.SslStream_StreamToStream_Authentication_Success(X509Certificate serverCert, X509Certificate clientCert)
      /_/src/libraries/System.Net.Security/tests/FunctionalTests/LoggingTest.cs(45,0): at System.Net.Security.Tests.LoggingTest.<>c.<EventSource_EventsRaisedAsExpected>b__1_1()
      /_/src/libraries/Common/tests/System/Diagnostics/Tracing/TestEventListener.cs(111,0): at System.Diagnostics.Tracing.TestEventListener.RunWithCallback(Action`1 handler, Action body)
      /_/src/libraries/System.Net.Security/tests/FunctionalTests/LoggingTest.cs(41,0): at System.Net.Security.Tests.LoggingTest.<>c.<EventSource_EventsRaisedAsExpected>b__1_0()
      
      Child process:
        System.Net.Security.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Security.Tests.LoggingTest+<>c Void <EventSource_EventsRaisedAsExpected>b__1_0()
```
System.Net.Security.Tests.ApmSslStreamSystemDefaultTest.ClientAndServer_OneOrBothUseDefault_Ok
```
System.Net.Security.Tests.ApmSslStreamSystemDefaultTest.ClientAndServer_OneOrBothUseDefault_Ok(clientProtocols: null, serverProtocols: Tls12) [FAIL]
    System.AggregateException : One or more errors occurred. (One or more errors occurred. (Authentication failed, see inner exception.)) (One or more errors occurred. (Authentication failed, see inner exception.))
    ---- System.AggregateException : One or more errors occurred. (Authentication failed, see inner exception.)
    -------- System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.
    ------------ System.ComponentModel.Win32Exception : The function requested is not supported
    ---- System.AggregateException : One or more errors occurred. (Authentication failed, see inner exception.)
    -------- System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.
    ------------ System.ComponentModel.Win32Exception : The client and server cannot communicate, because they do not possess a common algorithm.
    Stack Trace:
      /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(89,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
      /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(55,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
      /_/src/libraries/System.Net.Security/tests/FunctionalTests/SslStreamSystemDefaultsTest.cs(92,0): at System.Net.Security.Tests.SslStreamSystemDefaultTest.ClientAndServer_OneOrBothUseDefault_Ok(Nullable`1 clientProtocols, Nullable`1 serverProtocols)
      --- End of stack trace from previous location ---
      ----- Inner Stack Trace #1 (System.AggregateException) -----
      
      ----- Inner Stack Trace -----
      /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(418,0): at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
      /_/src/libraries/Common/src/System/Threading/Tasks/TaskToApm.cs(41,0): at System.Threading.Tasks.TaskToApm.End(IAsyncResult asyncResult)
      /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.cs(211,0): at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
      /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/FutureFactory.cs(544,0): at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
      --- End of stack trace from previous location ---
      /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(72,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
      ----- Inner Stack Trace -----
      
      ----- Inner Stack Trace #2 (System.AggregateException) -----
      
      ----- Inner Stack Trace -----
      /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(418,0): at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
      /_/src/libraries/Common/src/System/Threading/Tasks/TaskToApm.cs(41,0): at System.Threading.Tasks.TaskToApm.End(IAsyncResult asyncResult)
      /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.cs(250,0): at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
      /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/FutureFactory.cs(544,0): at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
      --- End of stack trace from previous location ---
      /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(64,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
      ----- Inner Stack Trace -----
```
System.Net.Security.Tests.SslStreamTls11NetworkConformanceTests.ZeroByteWrite_OtherDataReceivedSuccessfully(mode: SyncArray)
```
System.Net.Security.Tests.SslStreamTls11NetworkConformanceTests.ZeroByteWrite_OtherDataReceivedSuccessfully(mode: SyncArray) [FAIL]
    System.ComponentModel.Win32Exception : The client and server cannot communicate, because they do not possess a common algorithm.
    Stack Trace:
      /_/src/libraries/Common/src/Interop/Windows/SspiCli/SSPIWrapper.cs(138,0): at System.Net.SSPIWrapper.AcquireCredentialsHandle(ISSPIInterface secModule, String package, CredentialUse intent, SCH_CREDENTIALS* scc)
      /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs(574,0): at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(CredentialUse credUsage, SCH_CREDENTIALS* secureCredential)
      /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs(276,0): at System.Net.Security.SslStreamPal.AcquireCredentialsHandleSchCredentials(SslStreamCertificateContext certificateContext, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
      /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStreamPal.Windows.cs(126,0): at System.Net.Security.SslStreamPal.AcquireCredentialsHandle(SslStreamCertificateContext certificateContext, SslProtocols protocols, EncryptionPolicy policy, Boolean isServer)
      /_/src/libraries/System.Net.Security/src/System/Net/Security/SecureChannel.cs(606,0): at System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint)
      /_/src/libraries/System.Net.Security/src/System/Net/Security/SecureChannel.cs(782,0): at System.Net.Security.SecureChannel.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)
      /_/src/libraries/System.Net.Security/src/System/Net/Security/SecureChannel.cs(725,0): at System.Net.Security.SecureChannel.NextMessage(ReadOnlySpan`1 incomingBuffer)
      /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(352,0): at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
      /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(64,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
      /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(91,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
      /_/src/libraries/System.Net.Security/tests/FunctionalTests/SslStreamConformanceTests.cs(28,0): at System.Net.Security.Tests.SslStreamConformanceTests.CreateWrappedConnectedStreamsAsync(StreamPair wrapped, Boolean leaveOpen)
      /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs(2251,0): at System.IO.Tests.ConnectedStreamConformanceTests.ZeroByteWrite_OtherDataReceivedSuccessfully(ReadWriteMode mode)
      --- End of stack trace from previous location ---
```
System.Net.Security.Tests.ServerNoEncryptionTest.ServerNoEncryption_ClientAllowNoEncryption_ConnectWithNoEncryption
```
  System.Net.Security.Tests.ServerNoEncryptionTest.ServerNoEncryption_ClientAllowNoEncryption_ConnectWithNoEncryption [FAIL]
    System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.
    ---- System.ComponentModel.Win32Exception : The function requested is not supported
    Stack Trace:
      /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(418,0): at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
      /_/src/libraries/System.Net.Security/tests/FunctionalTests/ServerNoEncryptionTest.cs(62,0): at System.Net.Security.Tests.ServerNoEncryptionTest.ServerNoEncryption_ClientAllowNoEncryption_ConnectWithNoEncryption()
      --- End of stack trace from previous location ---
      ----- Inner Stack Trace -----
```
System.Net.Security.Tests.ServerNoEncryptionTest.ServerNoEncryption_ClientNoEncryption_ConnectWithNoEncryption
```
  System.Net.Security.Tests.ServerNoEncryptionTest.ServerNoEncryption_ClientNoEncryption_ConnectWithNoEncryption [FAIL]
    System.Security.Authentication.AuthenticationException : Authentication failed, see inner exception.
    ---- System.ComponentModel.Win32Exception : The client and server cannot communicate, because they do not possess a common algorithm.
    Stack Trace:
      /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(364,0): at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
      /_/src/libraries/System.Net.Security/tests/FunctionalTests/ServerNoEncryptionTest.cs(88,0): at System.Net.Security.Tests.ServerNoEncryptionTest.ServerNoEncryption_ClientNoEncryption_ConnectWithNoEncryption()
      --- End of stack trace from previous location ---
      ----- Inner Stack Trace -----
```
System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_IndividualServerVsAllClientSupportedProtocols_Success(serverProtocol: Tls)
```
  System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_IndividualServerVsAllClientSupportedProtocols_Success(serverProtocol: Tls) [FAIL]
    System.IO.IOException :  Received an unexpected EOF or 0 bytes from the transport stream.
    Stack Trace:
      /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(1102,0): at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|187_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
      /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(462,0): at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
      /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.Implementation.cs(381,0): at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
      /_/src/libraries/System.Net.Security/tests/FunctionalTests/ClientAsyncAuthenticateTest.cs(155,0): at System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncSslHelper(EncryptionPolicy encryptionPolicy, SslProtocols clientSslProtocols, SslProtocols serverSslProtocols, RemoteCertificateValidationCallback certificateCallback)
      /_/src/libraries/System.Net.Security/tests/FunctionalTests/ClientAsyncAuthenticateTest.cs(102,0): at System.Net.Security.Tests.ClientAsyncAuthenticateTest.ClientAsyncAuthenticate_IndividualServerVsAllClientSupportedProtocols_Success(SslProtocols serverProtocol)
      --- End of stack trace from previous location ---

**Comment by wfurt** [comment] 2022-04-13 04:58
seems like something more is missing form the server 2022 bucket. We should never shrow `SkipException ` in remote executor. This is something @MihaZupan  fixed while back. 

I think the rest mimics mainline - caused by recent changes to Helix queues.  I think I gout Windows7 under control, and I'll look at the Server 2022 next. We will probably need to push fixes down to the release branches or roll-back [Helix changes](https://github.com/dotnet/core-eng/issues/15858). (don't know if we can do it selectively per branch)

**Comment by karelz** [comment] 2022-04-19 16:41
Triage: We need to backport main fixes due to Helix changes -- @rzikm can you please cherry pick the necessary changes?

**Comment by rzikm** [comment] 2022-05-04 06:21
#68332 was merged, closing.

**Closed by rzikm** 2022-05-04 06:21 UTC
Labels: area-System.Net, test-bug, blocking-clean-ci
