### ISSUE TITLE
Test failure:GC/Scenarios/GCBase1/gc_base1/gc_base1.sh

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#105927] opened 2024-08-05 01:46 UTC
**Failed in:** [runtime-coreclr r2r-extra 20240803.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=765166&view=ms.vss-test-web.build-test-results-tab&runId=19472826&resultId=122178&paneView=debug)

**Failed tests:**
```
R2R-CG2 osx arm64 Checked jitstressregs8 @ OSX.1200.ARM64.Open
    - GC/Scenarios/GCBase1/gc_base1/gc_base1.sh
```

**Error message:**
```
 /private/tmp/helix/working/AA1A0979/w/A72E094D/e/GC/Scenarios/GCBase1/gc_base1/gc_base1.sh: line 322: -r:/private/tmp/helix/working/AA1A0979/w/A72E094D/e/GC/Scenarios/GCBase1/gc_base1/IL-CG2/*.dll: No such file or directory
Unhandled exception. ILCompiler.CodeGenerationFailedException: Code generation failed for method '[gc_base1]DefaultNamespace.BaseNode.setType(int32)'
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Internal.JitInterface.CorInfoImpl._beginInlining(IntPtr thisHandle, IntPtr* ppException, CORINFO_METHOD_STRUCT_* inlinerHnd, CORINFO_METHOD_STRUCT_* inlineeHnd) in /_/src/coreclr/tools/Common/JitInterface/CorInfoImpl_generated.cs:line 154
   --- End of inner exception stack trace ---
   at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(IMethodNode methodCodeNodeNeedingCode, MethodIL methodIL) in /_/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:line 381
   at Internal.JitInterface.CorInfoImpl.CompileMethod(MethodWithGCInfo methodCodeNodeNeedingCode, Logger logger) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs:line 810
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass50_0.<ComputeDependencyNodeDependencies>g__CompileOneMethod|5(DependencyNodeCore`1 dependency, Int32 compileThreadId) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 898
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass50_0.<ComputeDependencyNodeDependencies>g__CompileOnThread|4(Int32 compilationThreadId) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 833
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass50_0.<ComputeDependencyNodeDependencies>g__CompilationThread|3(Object objThreadId) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 811
   at System.Threading.Thread.StartCallback()
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'array')
   at System.Array.Clear(Array array, Int32 index, Int32 length)
   at Internal.JitInterface.CorInfoImpl.CompileMethodCleanup() in /_/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:line 700
   at Internal.JitInterface.CorInfoImpl.CompileMethod(MethodWithGCInfo methodCodeNodeNeedingCode, Logger logger) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs:line 826
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass50_0.<ComputeDependencyNodeDependencies>g__CompileOneMethod|5(DependencyNodeCore`1 dependency, Int32 compileThreadId) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 898
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass50_0.<ComputeDependencyNodeDependencies>g__CompileOnThread|4(Int32 compilationThreadId) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 833
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass50_0.<ComputeDependencyNodeDependencies>g__CompilationThread|3(Object objThreadId) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 811
   at System.Threading.Thread.StartCallback()
/private/tmp/helix/working/AA1A0979/w/A72E094D/e/GC/Scenarios/GCBase1/gc_base1/gc_base1.sh: line 261: 87708 Abort trap: 6           (core dumped) $__Command

Return code:      1
Raw output file:      /tmp/helix/working/AA1A0979/w/A72E094D/uploads/Reports/GC.Scenarios/GCBase1/gc_base1/gc_base1.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/private/tmp/helix/working/AA1A0979/w/A72E094D/e/GC/Scenarios/GCBase1/gc_base1/IL-CG2/gc_base1.dll
20:50:40
Response file: /private/tmp/helix/working/AA1A0979/w/A72E094D/e/GC/Scenarios/GCBase1/gc_base1/gc_base1.dll.rsp
/private/tmp/helix/working/AA1A0979/w/A72E094D/e/GC/Scenarios/GCBase1/gc_base1/IL-CG2/gc_base1.dll
-o:/private/tmp/helix/working/AA1A
```

**Stack trace:**
```
   at GC_Scenarios._GCBase1_gc_base1_gc_base1_._GCBase1_gc_base1_gc_base1_sh()

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by lambdageek** [comment] 2024-08-05 13:39
Duplicate of https://github.com/dotnet/runtime/issues/105441

**Closed by lambdageek** 2024-08-05 13:39 UTC
Labels: arch-arm64, os-mac-os-x, JitStress, area-crossgen2-coreclr, untriaged, blocking-clean-ci-optional
