### ISSUE TITLE
[API Proposal]: Lazy api

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#76403] opened 2022-09-29 20:37 UTC
### Background and motivation

I propose to maintain an interface that will be labeled Lazy api

### API Proposal

```
interface IEnumerableLazy<T>:IEnumerable<T>
{

}
```

### API Usage

```


Obj.Get<string>().Set<string>();
Obj.Get<string>().Get<string>();
interface IEnumerableLazy<T>:IEnumerable<T>
{

}

static class Obj
{
    public static IEnumerableLazy<T> Get<T>() {
        throw new NotImplementedException();
    }
}
static class MyClass
{
    public static void Get<T>(this IEnumerableLazy<T> vs) { }
    public static void Set<T>(this IEnumerable<T> vs) { }
}

```

**Comment by stephentoub** [comment] 2022-09-29 20:48
I don't understand the suggestion.  What is the purpose of this proposed interface?

**Comment by Mr0N** [comment] 2022-09-29 20:50
> 



> I don't understand the suggestion. What is the purpose of this proposed interface?

So that the user of the api method, for example IEnumerable<string> Get, understands that he returns the Lazy enumerator

**Comment by Mr0N** [comment] 2022-09-29 21:11
And so that yield supports this interface

**Comment by LeaFrock** [comment] 2022-09-30 02:36
Still confused about your purpose. It's non-sense that you give an interface without a shape or action.

```csharp

interface IEnumerableActive<T> : IEnumerable<T>;

interface IEnumerableImmediately<T> : IEnumerable<T>;

interface IEnumerableSleep<T> : IEnumerable<T>;

interface IEnumerableJava<T> : IEnumerable<T>;

```

**Comment by Clockwork-Muse** [comment] 2022-09-30 04:46
> > 
> 
> > I don't understand the suggestion. What is the purpose of this proposed interface?
> 
> So that the user of the api method, for example `IEnumerable<string> Get` , understands that he returns the Lazy enumerator

... `IEnumerable` is already understood to be lazy.  That's the default assumption people should make about it.  It's why so many classes realize a copy if they need to keep the data around.

**Comment by Mr0N** [comment] 2022-09-30 06:59
> 

```
public IEnumerable<string> GetList(){
return new List<string>();
}
```

**Comment by Mr0N** [comment] 2022-09-30 06:59
> > > 
> > 
> > 
> > > I don't understand the suggestion. What is the purpose of this proposed interface?
> > 
> > 
> > So that the user of the api method, for example `IEnumerable<string> Get` , understands that he returns the Lazy enumerator
> 
> ... `IEnumerable` is already understood to be lazy. That's the default assumption people should make about it. It's why so many classes realize a copy if they need to keep the data around.

```
public IEnumerable<string> GetList(){
return new List<string>();
}
```

**Comment by En3Tho** [comment] 2022-09-30 07:10
I guess the proposed idea is to make only lazily enumerable types under this interface?

While on one hand this might introduce some clarity (linq methods can return this new lazy interface instead to indicate there is no materialization going on) on the other it feels like a total abstraction leak.

It's hard to see any actual value in proposal. It might block usage of existing IEnumerable implementing types like array or List<T> etc but 1) is there a good reason for this? 2) interface itself does now bring any new constraints so it's actually impossible to guarantee something is "lazy" and not materialized

**Comment by Mr0N** [comment] 2022-09-30 07:17
> I guess the proposed idea is to make only lazily enumerable types under this interface?
> 
> While on one hand this might introduce some clarity (linq methods can return this new lazy interface instead to indicate there is no materialization going on) on the other it feels like a total abstraction leak.
> 
> It's hard to see any actual value in proposal. It might block usage of existing IEnumerable implementing types like array or List etc but 1) is there a good reason for this? 2) interface itself does now bring any new constraints so it's actually impossible to guarantee something is "lazy" and not materialized (and it's impossible anyway I believe)

private IEnumerableLazy<T> GetLazy<T>() => throw new Exception();
public IEnumerable<T> Get<T>() => GetLazy<T>() as IEnumerable<T>();


if(Get<string>() is EnumerableLazy<string>){

}

**Comment by Mr0N** [comment] 2022-09-30 07:19
> > I guess the proposed idea is to make only lazily enumerable types under this interface?
> > While on one hand this might introduce some clarity (linq methods can return this new lazy interface instead to indicate there is no materialization going on) on the other it feels like a total abstraction leak.
> > It's hard to see any actual value in proposal. It might block usage of existing IEnumerable implementing types like array or List etc but 1) is there a good reason for this? 2) interface itself does now bring any new constraints so it's actually impossible to guarantee something is "lazy" and not materialized (and it's impossible anyway I believe)
> 
```
private IEnumerableLazy<T> GetLazy<T>() => throw new Exception(); 
public IEnumerable<string> Get<T>() => GetLazy<string>() as IEnumerable();

if(Get<string>() is EnumerableLazy<string>){
 
 }


```

**Comment by Clockwork-Muse** [comment] 2022-09-30 08:28
> ```
> public IEnumerable<string> GetList(){
> return new List<string>();
> }
> ```

Whether the actual implementation is lazy is irrelevant - empty enumerables are pretty much never lazy, as are most single-element ones.  Rather, from a receiver point of view it should be assumed that the contents are lazy and to proceed accordingly - usually this means that if you plan to refer to the contents multiple times you're supposed to capture a copy (pretty much any time you're not using it in a `foreach`).  There are speed/size optimizations in place to prevent some spurious allocations, but that's an implementation detail.

> linq methods can return this new lazy interface instead to indicate there is no materialization going on

And given some of the optimizations employed, sometimes this would be a lie.
And that's ignoring some of the underlying practical implementation considerations.  For instance:
```cs
foreach (var n in some source.OrderBy())
{
...
}
```
... The entirety of the stream is going to be ordered before the first element is returned for enumeration.  That's pretty much the only practical way to do it.  Sure it won't be ordered until enumeration (lazy until then), but not after that.

**Comment by Mr0N** [comment] 2022-09-30 08:47
> > ```
> > public IEnumerable<string> GetList(){
> > return new List<string>();
> > }
> > ```
> 
> Whether the actual implementation is lazy is irrelevant - empty enumerables are pretty much never lazy, as are most single-element ones. Rather, from a receiver point of view it should be assumed that the contents are lazy and to proceed accordingly - usually this means that if you plan to refer to the contents multiple times you're supposed to capture a copy (pretty much any time you're not using it in a `foreach`). There are speed/size optimizations in place to prevent some spurious allocations, but that's an implementation detail.
> 
> > linq methods can return this new lazy interface instead to indicate there is no materialization going on
> 
> And given some of the optimizations employed, sometimes this would be a lie. And that's ignoring some of the underlying practical implementation considerations. For instance:
> 
> ```cs
> foreach (var n in some source.OrderBy())
> {
> ...
> }
> ```
> 
> ... The entirety of the stream is going to be ordered before the first element is returned for enumeration. That's pretty much the only practical way to do it. Sure it won't be ordered until enumeration (lazy until then), but not after that.

Well, you can mark such methods as IEnumerable, what is the problem

**Comment by En3Tho** [comment] 2022-09-30 09:31
You should also note that nothing in IEnumerable contract assumes it is lazy. IEnumerable states that type can be enumerated (has enumerator) and that's it.

**Comment by Clockwork-Muse** [comment] 2022-10-01 04:06
> https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Linq.Expressions/src/System/Linq/IQueryable.cs ![image](https://user-images.githubusercontent.com/61237140/193349702-30917d8f-20b6-469b-b460-1bbae1986fc9.png)

`IQueryable` has a shape/action, in that it has additional properties it requires you to implement.  What you've proposed so far is only a marker interface, which provide no additional API surface, and are generally frowned on (the most famous example likely being Java's `Cloneable`, although that has runtime-related issues).

Why would having a separate "this is lazy" interface be a benefit?  What concrete problem would it solve?
Note too that this would almost certainly be a return-only interface, in that there's no practical reason for it to be used for a parameter (instead of `IEnumerable`), so there's even less reason than normal to use it.

**Comment by Mr0N** [comment] 2022-10-01 07:20
> > https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Linq.Expressions/src/System/Linq/IQueryable.cs ![image](https://user-images.githubusercontent.com/61237140/193349702-30917d8f-20b6-469b-b460-1bbae1986fc9.png)
> 
> `IQueryable` has a shape/action, in that it has additional properties it requires you to implement. What you've proposed so far is only a marker interface, which provide no additional API surface, and are generally frowned on (the most famous example likely being Java's `Cloneable`, although that has runtime-related issues).
> 
> Why would having a separate "this is lazy" interface be a benefit? What concrete problem would it solve? Note too that this would almost certainly be a return-only interface, in that there's no practical reason for it to be used for a parameter (instead of `IEnumerable`), so there's even less reason than normal to use it.

   ` public static void Get<T>(this IEnumerableLazy<T> vs) { }`
this is api

**Comment by Clockwork-Muse** [comment] 2022-10-01 11:46
> ` public static void Get<T>(this IEnumerableLazy<T> vs) { }` this is api

Sure, you _can_ have a method use it for a parameter.
The problem is that there's no practical reason to do so, and in most cases would either require you provide either bifurcated methods that work on both, or some wrapper call to make it "extra lazy".

Let's take the case of `Select(...)`.  If I want to change the type of the elements I can just do:
```cs
var n = someList.Select(x => x.ToString()).To list();
```
If we had a "guaranteed lazy" interface, either we would have to double the entire surface area of LINQ, or we would have to have an `AsLazy()` method.  Neither of which are palatable.
Instead it's just way simpler to always consider `IEnumerable` (probably) lazy by default.

**Comment by Mr0N** [comment] 2022-10-01 12:06
> static class Obj
> {
>     public static IEnumerableLazy<T> Get<T>() {
>         throw new NotImplementedException();
>     }
> }
> static class MyClass
> {
>     public static void Get<T>(this IEnumerableLazy<T> vs) { }
>     public static void Set<T>(this IEnumerable<T> vs) { }
> }
```
var obj = Obj.GetInfo<string>();
if(obj is IEnumerableLazy<string>){
;
}
static class Obj
{
     public static IEnumerable<T> GetInfo<T>() {
        return Get<T>() as IEnumerable<T>;
    }
    static IEnumerableLazy<T> Get<T>() {
        throw new NotImplementedException();
    }
}
static class MyClass
{
    public static void Get<T>(this IEnumerableLazy<T> vs) { }
    public static void Set<T>(this IEnumerable<T> vs) { }
}
```

**Comment by Mr0N** [comment] 2022-10-01 12:08
> 

Why? IEnumerable Lazy<T> can always be cast to IEnumerable<T>

**Comment by Mr0N** [comment] 2022-10-01 12:08
> > ` public static void Get<T>(this IEnumerableLazy<T> vs) { }` this is api
> 
> Sure, you _can_ have a method use it for a parameter. The problem is that there's no practical reason to do so, and in most cases would either require you provide either bifurcated methods that work on both, or some wrapper call to make it "extra lazy".
> 
> Let's take the case of `Select(...)`. If I want to change the type of the elements I can just do:
> 
> ```cs
> var n = someList.Select(x => x.ToString()).To list();
> ```
> 
> If we had a "guaranteed lazy" interface, either we would have to double the entire surface area of LINQ, or we would have to have an `AsLazy()` method. Neither of which are palatable. Instead it's just way simpler to always consider `IEnumerable` (probably) lazy by default.


Why? IEnumerable Lazy can always be cast to IEnumerable

**Comment by stephentoub** [comment] 2022-10-01 12:20
I still do not understand what problem this is solving. Every method that returns an enumerable is necessarily considered lazy by the consumer, as that's what the API supports: a forward-only cursor for producing the next element one at a time... if the implementation already fully computed, as with collection types, that's an implementation detail. Consumers that want to consume it more promptly type test to see if it implements other types or abstractions, like IList. I appreciate that you're trying to solve some problem even though I don't know what that problem is, but I'll try to short-circuit this discussion that seems to be going in a circle and just say we're not going to add such a marker interface. Thanks.

**Comment by Mr0N** [comment] 2022-10-01 16:22
> I still do not understand what problem this is solving. Every method that returns an enumerable is necessarily considered lazy by the consumer, as that's what the API supports: a forward-only cursor for producing the next element one at a time... if the implementation already fully computed, as with collection types, that's an implementation detail. Consumers that want to consume it more promptly type test to see if it implements other types or abstractions, like IList. I appreciate that you're trying to solve some problem even though I don't know what that problem is, but I'll try to short-circuit this discussion that seems to be going in a circle and just say we're not going to add such a marker interface. Thanks.

Two different enumerations of the array, can there be different results?
And for example, an enumeration in which there is a Select from linq can give different results.
I don't really understand what can be called lazy, well, I think it can be called something that is created on the fly, and not read ready from an array, for example.

**Comment by stephentoub** [comment] 2022-10-01 18:04
> Two different enumerations of the array, can there be different results?

Of course.
```C#
static IEnumerable<int> GetData()
{
    int[] array = new int[4];
    Task.Run(async () =>
    {
        var r = new Random();
        while (true)
        {
            await Task.Delay(1);
            for (int i = 0; i < array.Length; i++)
            {
                array[i] = r.Next();
            }
        }
    });
    return array;
}
```

**Comment by Mr0N** [comment] 2022-10-01 18:27
> 

foreach won't throw an array changed error?

**Comment by Mr0N** [comment] 2022-10-01 18:28
> > Two different enumerations of the array, can there be different results?
> 
> Of course.
> 
> ```cs
> static IEnumerable<int> GetData()
> {
>     int[] array = new int[4];
>     Task.Run(async () =>
>     {
>         var r = new Random();
>         while (true)
>         {
>             await Task.Delay(1);
>             for (int i = 0; i < array.Length; i++)
>             {
>                 array[i] = r.Next();
>             }
>         }
>     });
>     return array;
> }
> ```


foreach won't throw an array changed error?

**Comment by Clockwork-Muse** [comment] 2022-10-01 19:00
No.
The state-change mechanisms aren't present on arrays.
And that's an implementation detail anyways - there's nothing contractually requiring such a scheme (especially since there's actually a performance cost).

**Comment by Mr0N** [comment] 2022-10-01 19:44
> ```cs
>                 array[i] = r.Next();
> ```

That's great) now we need to somehow make this method return IEnumeratorLazy so that it is clear that it changes information.)

**Comment by Mr0N** [comment] 2022-10-01 19:45
> > Two different enumerations of the array, can there be different results?
> 
> Of course.
> 
> ```cs
> static IEnumerable<int> GetData()
> {
>     int[] array = new int[4];
>     Task.Run(async () =>
>     {
>         var r = new Random();
>         while (true)
>         {
>             await Task.Delay(1);
>             for (int i = 0; i < array.Length; i++)
>             {
>                 array[i] = r.Next();
>             }
>         }
>     });
>     return array;
> }
> ```

That's great) now we need to somehow make this method return IEnumeratorLazy so that it is clear that it changes information.)

**Comment by Mr0N** [comment] 2022-10-01 19:48
Maybe someone will use this method to generate n number of numbers of random value and to create a sequence that must then be written down somewhere)

**Comment by Clockwork-Muse** [comment] 2022-10-01 20:22
> That's great) now we need to somehow make this method return IEnumeratorLazy so that it is clear that it changes information.)

That's an abuse of `IEnumerable`, you're not supposed to modify anything as part of enumeration.  There's no reason any subclass would change that, and nothing you've listed so far would justify adding that as a "feature" here.

> Maybe someone will use this method to generate n number of numbers of random value and to create a sequence that must then be written down somewhere)

.... People already do this with regular `IEnumerable`.... A new interface isn't required....

**Comment by Mr0N** [comment] 2022-10-01 20:39
> That's an abuse of `IEnumerable`, you're not supposed to modify anything as part of enumeration. There's no reason any subclass would change that, and nothing you've listed so far would justify adding that as a "feature" here.
> 
> >
int count =0;
var obj = Enumerable.Range(0,100).Select(a=>count++);
foreach(var item in obj){
Console.WriteLine(item);
} 
foreach(var item in obj){
Console.WriteLine(item);
}

**Comment by Mr0N** [comment] 2022-10-01 20:46
for example exists IAsyncEnumerator

**Comment by stephentoub** [comment] 2022-10-01 21:04
IEnumerable is already capable of this and folks already expose IEnumerables for lazy sequences. Adding a new interface that says "this is lazy" adds no value because existing usage of IEnumerable has to assume its also lazy.

I'm going to close this issue now. Of course feel free to keep discussing, but we will not be adding a marker interface for this, and thus don't need an issue tracking it. Thanks

**Closed by stephentoub** 2022-10-01 21:04 UTC
Labels: api-suggestion, untriaged
