### ISSUE TITLE
AOT+LLVM throws for `Enum.GetUnderlyingType()` on Android in .NET 7

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/runtime#68914] opened 2022-05-05 16:18 UTC
### Description

Our `Mono.Android-Tests` project crashes on startup with:
```
05-05 15:19:34.429  4929  4929 F mono-rt : [ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentException: Type provided must be an Enum. Arg_ParamName_Name, enumType
05-05 15:19:34.429  4929  4929 F mono-rt :    at System.Enum.InternalGetUnderlyingType(RuntimeType enumType)
05-05 15:19:34.429  4929  4929 F mono-rt :    at System.RuntimeType.GetEnumUnderlyingType()
05-05 15:19:34.429  4929  4929 F mono-rt :    at System.Enum.GetUnderlyingType(Type enumType)
05-05 15:19:34.429  4929  4929 F mono-rt :    at Java.Interop.JniRuntime.JniTypeManager.GetUnderlyingType(Type , Int32& )
05-05 15:19:34.429  4929  4929 F mono-rt :    at Java.Interop.JniRuntime.JniTypeManager.GetTypeSignature(Type )
05-05 15:19:34.429  4929  4929 F mono-rt :    at Java.Interop.JniPeerMembers.JniInstanceMethods..ctor(Type )
05-05 15:19:34.429  4929  4929 F mono-rt :    at Java.Interop.JniPeerMembers.JniInstanceMethods.GetConstructorsForType(Type )
05-05 15:19:34.429  4929  4929 F mono-rt :    at Java.Interop.JniPeerMembers.JniInstanceMethods.StartCreateInstance(String , Type , JniArgumentValue* )
05-05 15:19:34.429  4929  4929 F mono-rt :    at Java.Lang.Error..ctor(String )
05-05 15:19:34.429  4929  4929 F mono-rt :    at Android.Runtime.JavaProxyThrowable..ctor(Exception )
05-05 15:19:34.429  4929  4929 F mono-rt :    at Java.Lang.Throwable.FromException(Exception )
05-05 15:19:34.429  4929  4929 F mono-rt :    at Android.Runtime.AndroidEnvironment.UnhandledException(Exception e)
05-05 15:19:34.429  4929  4929 F mono-rt :    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V , IntPtr , IntPtr , IntPtr )
```

This looks oddly familiar to a related issue in mono/mono: https://github.com/xamarin/xamarin-android/issues/1842

Looking at the underlying code, I think it throws here: 

https://github.com/xamarin/java.interop/blob/61cdb40dcc8b33d400aef3fd12e0aeee72f71e35/src/Java.Interop/Java.Interop/JniRuntime.JniTypeManager.cs#L151-L152

### Reproduction Steps

Build a .NET 7 `Release` app with `-p:EnableLLVM=true`.

### Expected behavior

Use of `-p:EnableLLVM=true` on Android doesn't crash on startup.

### Actual behavior

Use of `-p:EnableLLVM=true` crashes on startup on Android.

### Regression?

This project appears to be working in .NET 6.

### Known Workarounds

Disable LLVM.

### Configuration

.NET 7.0.100-preview.4.22174.1 c7afae6936bf80239aa93bfd3b6f68513d9876d4
.NET runtime 7.0.0-preview.4.22172.7 c5d40c9e703fd257db1b26ef4fd1399bbae73ab0

**Comment by SamMonoRT** [comment] 2022-05-10 14:13
cc @vargaz  - please can you take a look.
@jonathanpeppers - do we need any related fix backported for MAUI release ?

**Comment by vargaz** [comment] 2022-05-10 20:28
Which type is passed to the method ?

**Comment by jonpryor** [comment] 2022-05-11 13:34
What's "odd" about this stack trace is that it makes no sense.

It starts with the [`JavaProxyThrowable`](https://github.com/xamarin/xamarin-android/blob/2a4c58c6162c18b86d6de9d08b27a06bef9af594/src/Mono.Android/Android.Runtime/JavaProxyThrowable.cs) constructor, which chains to the `Java.Lang.Error` constructor, which does:

```
var __r = _members.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), __args);
```

i.e. the `System.Type` instance will be `typeof(JavaProxyThrowable)`.

We then hit `JniPeerMembers.JniInstanceMethods.StartCreateInstance()`: https://github.com/xamarin/java.interop/blob/3fcce7466324c6564874fe275eac222a8970078c/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods.cs#L97-L112

which calls `GetConstructorsForType()`: https://github.com/xamarin/java.interop/blob/3fcce7466324c6564874fe275eac222a8970078c/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods.cs#L70-L82

  * `declaringType` is `typeof(JavaProxyThrowable)`.
  * `DeclaringType` is `typeof(Error)`
  * We thus hit `new JniInstanceMethods(typeof(JavaProxyThrowable))`

This brings us to the `JniInstaceMethods(Type)` constructor: https://github.com/xamarin/java.interop/blob/3fcce7466324c6564874fe275eac222a8970078c/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods.cs#L17-L29

Which calls `GetTypeSignature(typeof(JavaProxyThrowable))`: https://github.com/xamarin/java.interop/blob/3fcce7466324c6564874fe275eac222a8970078c/src/Java.Interop/Java.Interop/JniRuntime.JniTypeManager.cs#L51

Which cals `GetUnderlyingType(typeof(JavaProxyThrowable), out int _)`: https://github.com/xamarin/java.interop/blob/3fcce7466324c6564874fe275eac222a8970078c/src/Java.Interop/Java.Interop/JniRuntime.JniTypeManager.cs#L140-L155

Which is where things make no sense: *statically*, we *know* `type` is `typeof(JavaProxyThrowable)`, yet here:

https://github.com/xamarin/java.interop/blob/3fcce7466324c6564874fe275eac222a8970078c/src/Java.Interop/Java.Interop/JniRuntime.JniTypeManager.cs#L151-L152

`typeof(JavaProxyThrowable).IsEnum` *must* be `true` in order for us to hit `Enum.GetUnderlyingType(typeof(JavaProxyThrowable))`, but it *shouldn't* be `true`!

Thus, throwing the `ArgumentException` *is* correct behavior.

The bug is that `typeof(JavaProxyThrowable).IsEnum` is `true` when it should be `false`!

(Or AOT+LLVM inlining mumble something?)

**Comment by jonathanpeppers** [comment] 2022-05-12 16:47
I made some smaller repros here, building xamarin-android/main. I used `dotnet new android`, and set `-p:AndroidPackageFormat=apk`, `-p:AndroidUseAssemblyStore=false`, and `-p:AndroidEnableAssemblyCompression=false`, to simplify things and make the IL readable if needed.

`-p:EnableLLVM=false`, these launch successfully:

* `-r android-arm64`: [aot-nollvm-arm64.zip](https://github.com/dotnet/runtime/files/8681044/aot-nollvm-arm64.zip)
* `-r android-x64`: [aot-nollvm-x64.zip](https://github.com/dotnet/runtime/files/8681072/aot-nollvm-x64.zip)

`-p:EnableLLVM=true`, these fail:

* `-r android-arm64`: [aot-llvm-arm64.zip](https://github.com/dotnet/runtime/files/8681101/aot-llvm-arm64.zip)

(this one might be a different issue, it has a different crash)

* `-r android-x64`:  [aot-llvm-x64.zip](https://github.com/dotnet/runtime/files/8681083/aot-llvm-x64.zip)

I added more logging in xamarin-android to see the exception:
```
05-12 11:42:37.629  2490  2490 I MonoDroid: Android.Runtime.JavaProxyThrowable: Exception_WasThrown, Android.Runtime.JavaProxyThrowable
05-12 11:42:37.629  2490  2490 I MonoDroid:   --- End of managed Android.Runtime.JavaProxyThrowable stack trace ---
05-12 11:42:37.629  2490  2490 I MonoDroid: android.runtime.JavaProxyThrowable: System.NotSupportedException: Unable to activate instance of type foo.MainActivity from native handle 0x7ffd8e98a214 (key_handle 0x18e6dce).
05-12 11:42:37.629  2490  2490 I MonoDroid:  ---> System.MissingMethodException: No constructor found for foo.MainActivity::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership)
05-12 11:42:37.630  2490  2490 I MonoDroid:  ---> Java.Interop.JavaLocationException: Exception_WasThrown, Java.Interop.JavaLocationException
```
We believe that `Type.IsInterface` and `Type.IsEnum` might be returning values wrong for types.

**Comment by vargaz** [comment] 2022-05-19 08:36
Which aotprofile file is used to AOT these apps ?

**Comment by jonathanpeppers** [comment] 2022-05-19 13:39
It is this one, which was recorded using .NET 6:

https://github.com/xamarin/xamarin-android/blob/b250c04b09a2b725336ae6d6c5693e0b9f37e4cc/src/Xamarin.Android.Build.Tasks/dotnet.aotprofile

Working on another one, but it looks like I have to build a newer `libmono-profiler-aot.so`.

**Comment by fanyang-mono** [comment] 2022-08-03 19:03
https://github.com/dotnet/runtime/issues/73304 is also a Enum related failure. I wonder if they could have the same root cause.

**Comment by jonathanpeppers** [comment] 2022-08-03 19:26
> https://github.com/dotnet/runtime/issues/73304 is also a Enum related failure.

I think #73304  might mean "enumeration", it's this error message after the linker removed the text for it:

https://github.com/dotnet/runtime/blob/a9b3898ee4b568cba09236cc71a63faf3ec52eea/src/libraries/System.Collections.NonGeneric/src/Resources/Strings.resx#L96-L98

I think this is if you use an `Enumerator` yourself and try to move past the end?

**Comment by lambdageek** [comment] 2022-08-17 15:04
Based on the description here https://github.com/dotnet/runtime/issues/68914#issuecomment-1123770862 I'm trying to make a sample for dotnet/runtime that has the same behavior, and trying to compile it with LLVM.

Starting from this:

```csharp
using System;
using System.Runtime.CompilerServices;

public class Base {
    public Base () {
        Work (((object)this).GetType());
    }
    [MethodImpl(MethodImplOptions.NoInlining)]
    public static void Work(Type t) {
        Console.WriteLine ($"is enum: {t} - {t.IsEnum}");
    }
}

public class Child : Base {
    public Child() : base () { }
}


public class Program {
    public static void Main () {
        bool isMono = typeof(object).Assembly.GetType("Mono.RuntimeStructs") != null;
        Console.WriteLine($"Hello World {(isMono ? "from Mono!" : "from CoreCLR!")}");
        var _ = new Child ();
    }
}
```

Currently having issues building the runtime with LLVM support 🤦

**Comment by lambdageek** [comment] 2022-08-17 18:59
Nope, my naive repro doesn't ever return `True` for `IsEnum`.

**Comment by jonathanpeppers** [comment] 2022-08-17 19:12
@lambdageek this particular issue, I haven't seen last time I tested LLVM. Is it possible some change since May solved this one?

I've more recently hit these two:
* Issue during a Java.Interop unit test: https://github.com/dotnet/runtime/issues/73304
* Issue on arm64: https://github.com/dotnet/runtime/issues/73003

**Comment by lambdageek** [comment] 2022-08-17 19:19
Removing `blocking-release` and moving to 8.0 - unless you think we can close it, @jonathanpeppers ?

**Comment by jonathanpeppers** [comment] 2022-08-17 19:29
Let's just close it, and I can reopen if we hit this again.

**Closed** 2022-08-17 19:31 UTC
Labels: os-android, area-Codegen-LLVM-mono

**Comment by BrzVlad** [comment] 2022-08-30 08:21
I stumbled across an identical stacktrace while hitting various issues on android + llvmaot. https://github.com/dotnet/runtime/pull/74796 was fixing it for me.
