### ISSUE TITLE
DataSet.ReadXml() throws exception

### ISSUE THREAD

**Issue by frankwwu** [dotnet/runtime#48005] opened 2021-02-08 16:54 UTC
Following C# code throws exception for .NET Core 3.1 and 5. However, it works for .NET Framework 4.8.

```
DataSet dataSet = new DataSet();
dataSet.ReadXml("data.xml", XmlReadMode.ReadSchema);
```

[data.zip](https://github.com/dotnet/core/files/5945263/data.zip)
[data.zip](https://github.com/dotnet/core/files/5945272/data.zip)

Exception message:

**XmlSchemaException: Type 'http://schemas.microsoft.com/sqlserver/2004/sqltypes:int' is not declared, or is not a simple type.**

The input data file is attached.

Is the issue a .NET Core bug? Any workaround?

**Comment by roji** [comment] 2021-07-13 09:51
Confirmed the above.

For a minimal repro, run the following code:

```c#
var sc = new XmlSchemaSet();
sc.Add("urn:schemas-microsoft-com:sql:SqlRowSet1", "data.xsd");
sc.Compile();
```

On the following `data.xsd`:

<details>
<summary>data.xsd</summary>

```xml
<xsd:schema xmlns:schema="urn:schemas-microsoft-com:sql:SqlRowSet1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:sqltypes="http://schemas.microsoft.com/sqlserver/2004/sqltypes" targetNamespace="urn:schemas-microsoft-com:sql:SqlRowSet1" elementFormDefault="qualified">
  <xsd:import namespace="http://schemas.microsoft.com/sqlserver/2004/sqltypes" schemaLocation="http://schemas.microsoft.com/sqlserver/2004/sqltypes/sqltypes.xsd" />
  <xsd:element name="parameter">
    <xsd:complexType>
      <xsd:attribute name="date_trip_id" type="sqltypes:int" />
      <xsd:attribute name="parameter_id" type="sqltypes:int" />
      <xsd:attribute name="name">
        <xsd:simpleType>
          <xsd:restriction base="sqltypes:varchar" sqltypes:localeId="1033" sqltypes:sqlCompareOptions="IgnoreCase IgnoreKanaType IgnoreWidth" sqltypes:sqlSortId="52" />
        </xsd:simpleType>
      </xsd:attribute>
      <xsd:attribute name="value">
        <xsd:simpleType>
          <xsd:restriction base="sqltypes:varchar" sqltypes:localeId="1033" sqltypes:sqlCompareOptions="IgnoreCase IgnoreKanaType IgnoreWidth" sqltypes:sqlSortId="52" />
        </xsd:simpleType>
      </xsd:attribute>
      <xsd:attribute name="loaded" type="sqltypes:bit" />
    </xsd:complexType>
  </xsd:element>
</xsd:schema>
```
</details>

On .NET Framework 4.8 this works, but throws on .NET 5.0 (and latest .NET 6.0, SDK 6.0.100-preview.7.21362.5):

```
Unhandled exception. System.Xml.Schema.XmlSchemaException: Type 'http://schemas.microsoft.com/sqlserver/2004/sqltypes:int' is not declared, or is not a simple type.
   at System.Xml.Schema.XmlSchemaSet.InternalValidationCallback(Object sender, ValidationEventArgs e)
   at System.Xml.Schema.BaseProcessor.SendValidationEvent(XmlSchemaException e, XmlSeverityType severity)
   at System.Xml.Schema.BaseProcessor.SendValidationEvent(XmlSchemaException e)
   at System.Xml.Schema.Compiler.CompileElement(XmlSchemaElement xe)
   at System.Xml.Schema.Compiler.Compile()
   at System.Xml.Schema.Compiler.Execute(XmlSchemaSet schemaSet, SchemaInfo schemaCompiledInfo)
   at System.Xml.Schema.XmlSchemaSet.Compile()
   at <Program>$.<Main>$(String[] args) in /home/roji/projects/test/Program.cs:line 18
```

@buyaa-n @joperezr @krwq @jeffhandley can one of you confirm the above?

**Comment by ajcvickers** [comment] 2021-07-13 18:01
@AndriySvyryd @GrabYourPitchforks Is it possible this is due to the Ceres fix? Could it be that 4.8 on Shay's and the customer machine is not patched? Or did we add the SQL types to the allowed list in Framework but not Core?

**Comment by GrabYourPitchforks** [comment] 2021-07-13 18:38
That stack trace doesn't look like a Ceres stack trace. Ceres stack traces will look like this:

```txt
System.InvalidOperationException : Type '<Type Name>, Version=<n.n.n.n>, Culture=<culture>, PublicKeyToken=<token value>' is not allowed here.

Stack Trace:
    at System.Data.TypeLimiter.EnsureTypeIsAllowed(Type type, TypeLimiter capturedLimiter)
    at System.Data.DataColumn.UpdateColumnType(Type type, StorageType typeCode)
    at System.Data.DataColumn.set_DataType(Type value)
```

\[[more info](https://docs.microsoft.com/dotnet/framework/data/adonet/dataset-datatable-dataview/security-guidance)\]

So I think this is some separate XSD processing issue.

**Comment by buyaa-n** [comment] 2021-07-13 18:42
I think it is related to the schema import with an external URI, for security reasons .NET Core does not allow resolving external URIs for XML by default. You can enable using external URIs by setting the following AppContext switch on top of your code:

```csharp
AppContext.SetSwitch("Switch.System.Xml.AllowDefaultResolver", true);
```

For more information https://github.com/dotnet/runtime/issues/29346#issuecomment-485798826

**Comment by roji** [comment] 2021-07-13 20:48
Thanks @buyaa-n, that indeed fixes the issue! Closing this as by-design.

The discoverability here isn't ideal, does it make sense to throw a better-worded exception?

**Closed by roji** 2021-07-13 20:48 UTC
Labels: area-System.Data

**Comment by buyaa-n** [comment] 2021-07-13 21:40
> The discoverability here isn't ideal, does it make sense to throw a better-worded exception?

Agree it doesn't sound right, but the problem is the external schema is not added in the `ShemaSet.Add()` step, where seems by design we do not throw for unsuccessful addition, then in the `ShemaSet.Compile()` it throws that `Type 'http://schemas.microsoft.com/sqlserver/2004/sqltypes:int' is not declared` which is kind of correct message for that step, it explained more in the next comment https://github.com/dotnet/runtime/issues/29346#issuecomment-488764523

**Comment by roji** [comment] 2021-07-13 23:45
Alright @buyaa-n, thanks again for your help!
