### ISSUE TITLE
Test failure System.IO.Tests.FileStream_DeleteOnClose.OpenOrCreate_DeleteOnClose_UsableAsMutex

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#60210] opened 2021-10-09 01:16 UTC
Run: [runtime 20211008.6](https://dev.azure.com/dnceng/public/_build/results?buildId=1409599&view=ms.vss-test-web.build-test-results-tab&runId=40883062&paneView=debug&resultId=199829)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_release-Windows.7.Amd64.Open

- System.IO.Tests.FileStream_DeleteOnClose.OpenOrCreate_DeleteOnClose_UsableAsMutex

```
**Error messgae:**
```
Test cancelled
Expected: False
Actual:   True


Stack trace
   at System.IO.Tests.FileStream_DeleteOnClose.OpenOrCreate_DeleteOnClose_UsableAsMutex() in /_/src/libraries/System.IO.FileSystem/tests/FileStream/DeleteOnClose.cs:line 77
--- End of stack trace from previous location ---
```

**Comment by jeffhandley** [comment] 2021-10-09 02:31
Duplicate of #60147. Thanks for logging this!

**Closed by jeffhandley** 2021-10-09 02:31 UTC
Labels: arch-x86, area-System.IO, os-windows, untriaged
