### ISSUE TITLE
[ARM64]On Mac(Apple M1),SDK-6.0-osx-arm64 need Rosetta

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/runtime#48388] opened 2021-02-09 06:53 UTC
**Affected Mac:**
Mac OS: Big Sur(11.2) - Apple M1 chip
.NET 6 arm64: 6.0.100-preview.1.21106.4(runtime 6.0.0-preview.1.21102.12)

**Steps to reproduce:**
1.Install .NET arm64 SDK 6.0.100-preview.1.21106.4(runtime 6.0.0-preview.1.21102.12)

**Expected result:**
Native ARM 64 SDK can install without rosetta

**Actual result:** 
It need install rosetta to install .NET arm64 SDK
![image](https://user-images.githubusercontent.com/1578239/107326416-53730000-6ae6-11eb-97e4-e14b9d8cd000.png)

**Comment by sdmaclea** [comment] 2021-02-17 21:48
@richaverma1 Why do we think this is expected?

**Comment by richaverma1** [comment] 2021-02-17 23:07
@sdmaclea mybad, I misread it as x64 installer. For arm64 we don't need Rosetta.

**Comment by NicoleWang001** [comment] 2021-04-12 09:27
@sdmaclea , this is still repro with dotnet-sdk-6.0.100-preview.3.21207.34-osx-arm64 ,
![image](https://user-images.githubusercontent.com/1578239/114372567-49d44a00-9bb4-11eb-8322-07f5ed82f62e.png)

**Comment by sdmaclea** [comment] 2021-04-13 21:05
I opened the package and I see only `arm64` native files.  This leads me to believe the issue is with the meta data.

This https://scriptingosx.com/2020/12/platform-support-in-macos-installer-packages-pkg/ suggests that is the distribution package is built on an OS prior to Big Sur, Rosetta is assumed required by default.  

The fix is to add the `hostArchitectures` attribute to the `options` tag

This probably needs to be fixed in both `runtime` and `installer`

/cc @jkoritzinsky

**Comment by jkoritzinsky** [comment] 2021-04-13 21:51
I've added some work to dotnet/arcade which should enable this, but I don't have the machines to validate.

**Closed** 2021-04-15 20:42 UTC
Labels: arch-arm64, area-Setup, os-mac-os-x-big-sur
