### ISSUE TITLE
R2RDump - Fix coredistools dependency in build

### ISSUE THREAD

**Issue by nattress** [dotnet/runtime#13122] opened 2019-07-22 21:10 UTC
The architecture-specific coredistools.dll is not copied to the build output for R2RDump and has to be done manually to get disassembly. This should happen as part of the build - we should be publishing r2rdump, not just building it, since that deploys NuGet runtime dependencies.

**Comment by davidwrighton** [comment] 2020-07-30 19:14
While this would be nice, we don't need this for .NET 5. Moving to 6.0

**Comment by mangod9** [comment] 2021-07-10 00:19
@cshung believe this issue is resolved, or is there some more work required?

**Comment by cshung** [comment] 2021-07-10 01:14
> @cshung believe this issue is resolved, or is there some more work required?

I did nothing for this bug - but it appears that the issue is probably fixed in https://github.com/dotnet/runtime/pull/44490 by @echesakovMSFT

In particular, I do see `coredistools.dll` is placed in the right directory at the build output, if that is all we wanted, I think we can close this bug.

**Comment by mangod9** [comment] 2021-07-12 06:40
Ok closing for now, we can reopen if some OS/arch are still broken.

**Closed by mangod9** 2021-07-12 06:40 UTC
Labels: area-R2RDump-coreclr
