### ISSUE TITLE
[mono] GetInterfaceMap hangs on Android

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#36653] opened 2020-05-18 15:29 UTC
`System.TypeTestsExtended.GetInterfaceMap` hangs on Android 

System.Runtime.Tests.dll

**Comment by lambdageek** [comment] 2020-07-01 20:24
possible duplicate of https://github.com/dotnet/runtime/issues/34389

**Comment by MaximLipnin** [comment] 2021-07-27 10:54
The test passes locally:
```
<test name="System.Tests.TypeTestsExtended.GetInterfaceMap(interfaceType: typeof(System.Tests.TypeTestsExtended+ISimpleInterface), classType: typeof(System.Tests.TypeTestsExtended+SimpleType), expectedMap: [(Void Method(), Void Method()), (Void GenericMethod[T](), Void GenericMethod[T]())])" type="System.Tests.TypeTestsExtended" method="GetInterfaceMap" time="0.010212" result="Pass" />
<test name="System.Tests.TypeTestsExtended.GetInterfaceMap(interfaceType: typeof(System.Tests.TypeTestsExtended+ISimpleInterface), classType: typeof(System.Tests.TypeTestsExtended+AbstractSimpleType), expectedMap: [(Void Method(), Void Method()), (Void GenericMethod[T](), Void GenericMethod[T]())])" type="System.Tests.TypeTestsExtended" method="GetInterfaceMap" time="0.000164" result="Pass" />
<test name="System.Tests.TypeTestsExtended.GetInterfaceMap(interfaceType: typeof(System.Tests.TypeTestsExtended+IGenericInterface&lt;object&gt;), classType: typeof(System.Tests.TypeTestsExtended+DerivedType), expectedMap: [(Void Method(System.Object), Void Method(System.Object))])" type="System.Tests.TypeTestsExtended" method="GetInterfaceMap" time="0.000099" result="Pass" />
<test name="System.Tests.TypeTestsExtended.GetInterfaceMap(interfaceType: typeof(System.Tests.TypeTestsExtended+IGenericInterface&lt;string&gt;), classType: typeof(System.Tests.TypeTestsExtended+DerivedType), expectedMap: [(Void Method(System.String), Void Method(System.String))])" type="System.Tests.TypeTestsExtended" method="GetInterfaceMap" time="0.000098" result="Pass" />
<test name="System.Tests.TypeTestsExtended.GetInterfaceMap(interfaceType: typeof(System.Tests.TypeTestsExtended+DIMs+I1), classType: typeof(System.Tests.TypeTestsExtended+DIMs+C1), expectedMap: [(Void M(), Void M())])" type="System.Tests.TypeTestsExtended" method="GetInterfaceMap" time="0.000097" result="Pass" />
<test name="System.Tests.TypeTestsExtended.GetInterfaceMap(interfaceType: typeof(System.Tests.TypeTestsExtended+DIMs+I2), classType: typeof(System.Tests.TypeTestsExtended+DIMs+C2), expectedMap: [(Void System.Tests.TypeTestsExtended.DIMs.I1.M(), )])" type="System.Tests.TypeTestsExtended" method="GetInterfaceMap" time="0.000085" result="Pass" />
<test name="System.Tests.TypeTestsExtended.GetInterfaceMap(interfaceType: typeof(System.Tests.TypeTestsExtended+DIMs+I1), classType: typeof(System.Tests.TypeTestsExtended+DIMs+C2), expectedMap: [(Void M(), Void M())])" type="System.Tests.TypeTestsExtended" method="GetInterfaceMap" time="0.000113" result="Pass" />
<test name="System.Tests.TypeTestsExtended.GetInterfaceMap(interfaceType: typeof(System.Tests.TypeTestsExtended+DIMs+I3), classType: typeof(System.Tests.TypeTestsExtended+DIMs+C3), expectedMap: [(Void System.Tests.TypeTestsExtended.DIMs.I1.M(), Void System.Tests.TypeTestsExtended.DIMs.I1.M())])" type="System.Tests.TypeTestsExtended" method="GetInterfaceMap" time="0.000101" result="Pass" />
<test name="System.Tests.TypeTestsExtended.GetInterfaceMap(interfaceType: typeof(System.Tests.TypeTestsExtended+DIMs+I4), classType: typeof(System.Tests.TypeTestsExtended+DIMs+C4), expectedMap: [(Void System.Tests.TypeTestsExtended.DIMs.I1.M(), )])" type="System.Tests.TypeTestsExtended" method="GetInterfaceMap" time="0.000094" result="Pass" />
<test name="System.Tests.TypeTestsExtended.GetInterfaceMap(interfaceType: typeof(System.Tests.TypeTestsExtended+DIMs+I2), classType: typeof(System.Tests.TypeTestsExtended+DIMs+C4), expectedMap: [(Void System.Tests.TypeTestsExtended.DIMs.I1.M(), )])" type="System.Tests.TypeTestsExtended" method="GetInterfaceMap" time="0.000082" result="Pass" />
```

The issue seems to be fixed in https://github.com/dotnet/runtime/pull/53972.

**Closed by MaximLipnin** 2021-07-27 10:54 UTC
Labels: area-System.Reflection-mono, os-android, runtime-mono
