### ISSUE TITLE
ZipFile.ExtractToDirectory failing with "The filename, directory name, or volume label syntax is incorrect." (works in SharpZipLib)

### ISSUE THREAD

**Issue by smoothdeveloper** [dotnet/runtime#67201] opened 2022-03-27 13:27 UTC
### Description

I have some code using System.IO.Compression:

```fsharp
ZipFile.ExtractToDirectory(archive, Path.Combine(directory.FullName, "groove-v1.0.0-midionly"))
```

### Reproduction Steps

putting this in a .fsx file and running it with `dotnet fsi`:

```fsharp
#r "nuget: System.IO.Compression"
open System
open System.IO
open System.IO.Compression
open System.Net.Http
let directory = DirectoryInfo __SOURCE_DIRECTORY__
let archive = Path.Combine(__SOURCE_DIRECTORY__, "groove-v1.0.0-midionly.zip")
do
    let uri = "https://storage.googleapis.com/magentadata/datasets/groove/groove-v1.0.0-midionly.zip"
    use client = new HttpClient(Timeout = TimeSpan.FromMinutes 30)
    use resp = client.Send(new HttpRequestMessage(RequestUri=Uri uri))
    use stream = resp.Content.ReadAsStream()
    use file = File.OpenWrite(archive)
    stream.CopyTo(file)
//let fz = ICSharpCode.SharpZipLib.Zip.FastZip()
//fz.ExtractZip(archive, Path.Combine(directory.FullName, filesetName), "")
// dotnet one fails one the groove dataset.
ZipFile.ExtractToDirectory(archive, Path.Combine(directory.FullName, "groove-v1.0.0-midionly"))
```

I tried on macos, and it doesn't seem to fail, so maybe it is platform dependent.

### Expected behavior

I wish it would work, extracting without an exception.

### Actual behavior

> System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'C:\dev\src\github.com\smoothdeveloper\zcore-midi-fs\demo\groove-v1.0.0-midionly\groove\drummer8\session2\Icon
'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at System.IO.Compression.ZipFileExtensions.ExtractToDirectory(ZipArchive source, String destinationDirectoryName, Boolean overwriteFiles)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding, Boolean overwriteFiles)
   at <StartupCode$FSI_0003>.$FSI_0003.main@() in 

### Known Workarounds

I am using FastZip class from ICSharpCode.SharpZipLib.Zip to work around the issue.

### Configuration

```
Welcome to F# Interactive for .NET Core in Visual Studio. To execute code, either
  1. Use 'Send to Interactive' (Alt-Enter or right-click) from an F# script. The F# Interactive process will
     use any global.json settings associated with that script.
  2. Press 'Enter' to start. The F# Interactive process will use default settings.
> 

Microsoft (R) F# Interactive version 12.0.2.0 for F# 6.0
Copyright (c) Microsoft Corporation. All Rights Reserved.
```

* Windows 11 x64
* VS2022 preview
* dotnet 7 preview 2

**Comment by danmoseley** [comment] 2022-03-27 16:19
```
C:\dev\src\github.com\smoothdeveloper\zcore-midi-fs\demo\groove-v1.0.0-midionly\groove\drummer8\session2\Icon
'
```
Looks like there's a newline at the end of the path. That would cause this exception, too.

**Comment by danmoseley** [comment] 2022-03-27 16:54
Newlines in paths are valid in POSIX (although wierd). Looking at SharpZipLib, it does some cleaning of paths before writing them in Windows

https://github.com/icsharpcode/SharpZipLib/blob/cc8dd78ed989888f6685da4cc009c529158738b4/src/ICSharpCode.SharpZipLib/Zip/WindowsNameTransform.cs#L29-L37
https://github.com/icsharpcode/SharpZipLib/blob/cc8dd78ed989888f6685da4cc009c529158738b4/src/ICSharpCode.SharpZipLib/Zip/WindowsNameTransform.cs#L210

In our code see essentially no sanitization, which I guess would go here?

https://github.com/dotnet/runtime/blob/09a38d4807b0aa5e3ad3e69a4bf5bb50c710cd76/src/libraries/System.IO.Compression/src/System/IO/Compression/ZipArchiveEntry.cs#L1090

The fix is to do this sanitization, including adding test zip file(s) into [runtime-assets](https://github.com/dotnet/runtime-assets).

**Comment by danmoseley** [comment] 2022-03-27 16:55
@smoothdeveloper any interest in offering a PR for this?

**Comment by Danyy427** [comment] 2022-03-27 17:33
@danmoseley  I would like to help, but this is my first time. Could you point me in the right direction to start?

**Comment by danmoseley** [comment] 2022-03-27 17:38
@Danyy427 for sure, I've broken out the steps above. First thing is to make a test zip and put it in the runtime-assets repo.

Before you get started, let's just double check with the owners of this area: @dotnet/area-system-io-compression that they support this change.

**Comment by danmoseley** [comment] 2022-03-27 17:41
Meantime, you can follow the 'getting started' steps in this repo (linked from the README) to clone, build, and get tests passing for this repo without any changes.

**Comment by Danyy427** [comment] 2022-03-27 17:41
@danmoseley the original question is in F# but I may write code in C#, right? Also if I understood correctly I am going to make some tests where the characters that need sanitization are being used, upload them to runtime-assets?

**Comment by danmoseley** [comment] 2022-03-27 17:48
Yes we exclusively use C# in this repo (except when testing VB or F# scenarios.)

Yes, you will want to create a little zip file that has all the wierd characters in its file names listed here. You will need to figure out how to do that, and it may involve (if you're on Windows) using Linux (via WSL) and the Unix 'zip' utility, for example.
https://github.com/icsharpcode/SharpZipLib/blob/cc8dd78ed989888f6685da4cc009c529158738b4/src/ICSharpCode.SharpZipLib/Zip/WindowsNameTransform.cs#L29

**Comment by smoothdeveloper** [comment] 2022-03-27 17:59
@danmoseley, thanks for the feedback on confirming the issue and the reason of it surfacing, sharing great insights.

I can't help with a fix for it but thanks for the offer; I am also happy to see @Danny427 is going to give it a try based on your guidance, and confirm it doesn't matter I was using it from F# code for purpose of the fix.

Thanks all!

**Comment by Danyy427** [comment] 2022-03-27 19:02
@danmoseley I made that zip file with some test files/folders inside it. However, it is not possible to put '\0' in a filename even in Linux/UNIX. Should I attempt to write directly to my hard drive to put a null character or is it overkill/not necessary?

**Comment by danmoseley** [comment] 2022-03-27 19:57
I wouldn't bother with \0 if it isn't obvious how someone would make such things.

The concept here is that a zip that extracts successfully on Unix should extract successfully on Windows.

**Comment by Danyy427** [comment] 2022-03-27 20:00
@danmoseley Ok, then how would I go about uploading the zip. Do I make a clone of runtime-assets add the zip file and put up a pull request?

**Comment by danmoseley** [comment] 2022-03-27 20:10
@Danyy427  exactly, once you have tested it by extracting it yourself with sharpziplib and verified that it produces the same content you put in, with the expected chars replaced in the file names.

**Comment by Danyy427** [comment] 2022-03-27 20:11
@danmoseley will do, thank you!

**Comment by Danyy427** [comment] 2022-03-27 20:24
@danmoseley I have verified with SharpLibZip FastZip that the zip file results in all characters replaced with underscores. Creating a pull request now.

**Comment by danmoseley** [comment] 2022-03-27 21:06
> I wouldn't bother with \0 if it isn't obvious how someone would make such things.

Also of course that would be invalid even on Unix, so it's unlikely any mainstream tool would allow you to name streams that way, as they could never be written to a file under that name.

**Comment by Danyy427** [comment] 2022-03-27 21:31
@danmoseley How should I proceed now? Your original post suggests that I should wait for a PR and add tests. How would I go about adding tests and running them?

(I won't be able to attend to this for a few hours since I will probably have to sleep (it's late here))

**Comment by danmoseley** [comment] 2022-03-27 21:53
> How would I go about adding tests and running them?

First you need to get this repo cloned, built, and existing tests passing. Start at https://github.com/dotnet/runtime/blob/main/docs/workflow/README.md -- follow instructions for libraries.

**Comment by smoothdeveloper** [comment] 2022-03-27 21:58
@Danny427 at first measure you may:
* pull the same .zip file, to iron your testing a bit (which will be a non reg one, once adjustment is done)
* try to write a small archive with "non cross platform file names" in it with the underlying Zip infrastructure in the BCL (not sure it is doable as I never tried)

**Comment by danmoseley** [comment] 2022-03-27 22:01
@Danyy427 once he has tests passing locally (with no changes) should follow these instructions https://github.com/dotnet/runtime-assets/blob/main/README.md#optional-step-local-testing  in order to be able to add a new test that consumes his new zip file.

**Comment by danmoseley** [comment] 2022-03-28 14:23
Wierd. @steveisok  any idea?

**Comment by Danyy427** [comment] 2022-03-28 14:57
@danmoseley Just for clarification, I am talking about the base repo, I haven't changed anything, simply cloned using github desktop and ran the build command

**Comment by akoeplinger** [comment] 2022-03-28 15:05
Hmm this is very weird, we explicitly disable SYSLIB0003 in the .csproj:
https://github.com/dotnet/runtime/blob/bdbdaa8e2b4159c6839ca1c65b280fc25b0bbb82/src/tasks/MonoTargetsTasks/ILStrip/AssemblyStripper/AssemblyStripper.csproj#L7-L11

**Comment by danmoseley** [comment] 2022-03-28 15:19
BTW, the ingestion of runtime-assets is going on here https://github.com/dotnet/runtime/pull/67112

**Comment by danmoseley** [comment] 2022-03-28 15:21
Hmm, succeeds for me also. How curious. 
```
build.cmd clr+libs+libs.tests -rc Release
...
Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:15:06.92
```

**Comment by Danyy427** [comment] 2022-03-28 16:27
@danmoseley were you able to download the file?

**Comment by danmoseley** [comment] 2022-03-28 17:09
Yes. Here it is. Could it be the quoting? 
```
DisabledWarnings = ;1701;1702;1705;1591,CS8969,CS0618,CS0649,SYSLIB0003;NU5105;1701;1702
..
CommandLineArguments = D:\Runtime\runtime\.dotnet\dotnet.exe exec "C:\Users\Asus\.nuget\packages\microsoft.net.compilers.toolset\4.2.0-2.22128.1\tasks\net6.0\bincore\csc.dll" /noconfig /unsafe- /checked- /nowarn:1701,1702,1705,1591,CS8969,CS0618,CS0649,"SYSLIB0003",NU5105,1701,1702 /fullpaths /nostdlib+ /errorreport:prompt /warn:9999 /define:TRACE;DEBUG;NET;NET6_0;NETCOREAPP;NET5_0_OR_GREATER;NET6_0_OR_GREATER;NETCOREAPP1_0_OR_GREATER;NETCOREAPP1_1_OR_GREATER;NETCOREAPP2_0_OR_GREATER;NETCOREAPP2_1_OR_GREATER;NETCOREAPP2_2_OR_GREATER;NETCOREAPP3_0_OR_GREATER;NETCOREAPP3_1_OR_GREATER \es\7.0.0-beta.22171.1\contentFiles\cs\netstandard2.0\Mono.Cecil.Binary\DOSHeader.cs C:,,,,...
```
```
C:\Users\Asus\.nuget\packages\microsoft.dotnet.cilstrip.sources\7.0.0-beta.22171.1\contentFiles\cs\netstandard2.0\Mono.Cecil\SecurityDeclaration.cs(54,10): error SYSLIB0003: 'PermissionSet' is obsolete: 'Code Access Security is not supported or honored by the runtime.' [D:\Runtime\runtime\src\tasks\MonoTargetsTasks\ILStrip\AssemblyStripper\AssemblyStripper.csproj]
```

**Comment by danmoseley** [comment] 2022-03-28 17:13
Seems likely. My machine isn't quoting it:
```
Assembly = C:\Users\danmose\.nuget\packages\microsoft.net.compilers.toolset\4.2.0-2.22128.1\build\..\tasks\net6.0\Microsoft.Build.Tasks.CodeAnalysis.dll

CommandLineArguments = C:\git\runtime\.dotnet\dotnet.exe exec "C:\Users\danmose\.nuget\packages\microsoft.net.compilers.toolset\4.2.0-2.22128.1\tasks\net6.0\bincore\csc.dll" /noconfig /unsafe- /checked- /nowarn:1701,1702,1705,1591,CS8969,CS0618,CS0649,SYSLIB0003,NU5105,1701,1702 /fullpaths /nostdlib+ /errorreport:prompt /warn:9999 /define:TRACE;DEBUG;NETFRAMEWORK;NET472;NET20_OR_GREATER;NET30_OR_GREATER;NET35_OR_GREATER;NET40_OR_GREATER;NET45_OR_GREATER;NET451_OR_GREATER;NET452_OR_GREATER;NET46_OR_GREATER;NET461_OR_GREATER;NET462_OR_GREATER;NET47_OR_GREATER;NET471_OR_GREATER;NET472_OR_GREATER /highentropyva+ /nullable:disable /referen....

```

**Comment by Danyy427** [comment] 2022-03-28 17:19
@danmoseley wow that's weird, how do I fix that exactly?

**Comment by danmoseley** [comment] 2022-03-28 17:26
@Danyy427 I am psychically going to guess that your OS is set to the Turkish locale?

Therefore https://github.com/dotnet/msbuild/issues/7154 ... fix is to add "RegexOptions.CultureInvariant" here https://github.com/dotnet/msbuild/blob/6a79376cc50e5f0d829475adc418e7078776ccb7/src/Utilities/CommandLineBuilder.cs#L165 

@Danyy427 try changing your OS to another locale (eg US English) - -does it work? @Forgind is that still scheduled to fix? It's going to become more impactful as we have more warnings named like SYSLIBnnnn (ie with an "i" in)

**Comment by danmoseley** [comment] 2022-03-28 17:27
another workaround is to temporariy add `#pragma warning disable SYSLIB0003` at the top of each of the files containing thes warnings.

**Comment by Danyy427** [comment] 2022-03-28 17:33
@danmoseley Yes I am in Turkey, and yes it start the build without errors once I changed my region settings to the En (US), apparently display language was not enough.

**Comment by danmoseley** [comment] 2022-03-28 17:39
Great. I'm guessing you don't want to leave your OS set that way so you might want to do the other workaround I suggested. You can commit it locally to make your life easier -- of course when you have a PR, you would not include this change.

**Comment by Danyy427** [comment] 2022-03-28 17:49
I don't think I will change it, at least for the duration of this PR, I don't think I must have my locale settings in Turkey for any particular reason. Thank you for your concerns though. I will mess around with the repo for now and as soon as the PR is merged will try to make a PR for the fix itself.

**Comment by Danyy427** [comment] 2022-03-28 18:07
Also, the ingestion thread seems to be closed, are the assets merged or are they going to be merged with the Roslyn stuff?

**Comment by Danyy427** [comment] 2022-03-28 19:14
@danmoseley I have run all tests, to see if they pass but several don't pass and this of course tied to the locale business.

```
D:\Runtime\runtime\eng\testing\tests.targets(142,5): error : One or more tests failed while running tests from 'System.Runtime.Tests'. Please check D:\Runtime\runtime\artifacts\bin\System.Runtime.Tests\Debug\net7.0-windows\testResults.xml for details! [D:\Runtime\runtime\src\libraries\System.Runtime\tests\System.Runtime.Tests.csproj]
D:\Runtime\runtime\eng\testing\tests.targets(142,5): error : One or more tests failed while running tests from 'XsltCompiler.Tests'. Please check D:\Runtime\runtime\artifacts\bin\XsltCompiler.Tests\Debug\net7.0\testResults.xml for details! [D:\Runtime\runtime\src\libraries\System.Private.Xml\tests\Xslt\XsltCompiler\XsltCompiler.Tests.csproj]
D:\Runtime\runtime\eng\testing\tests.targets(142,5): error : One or more tests failed while running tests from 'System.Speech.Tests'. Please check D:\Runtime\runtime\artifacts\bin\System.Speech.Tests\Debug\net7.0-windows\testResults.xml for details! [D:\Runtime\runtime\src\libraries\System.Speech\tests\System.Speech.Tests.csproj]
```
The relevant lines in those xml files would be

```
<test name="System.Tests.TimeZoneInfoTests.TestNameWithInvariantCulture" type="System.Tests.TimeZoneInfoTests" method="TestNameWithInvariantCulture" time="4.2256622" result="Fail">
```

and also this one

```
<test name="System.Xml.Tests.XsltcTestSettings.Var1(param0: \&quot;/SETTİNGS:SCRİPT+ sft14.xsl\&quot;, param1: \&quot;sft14.dll\&quot;, param2: \&quot;no\&quot;, param3: \&quot;sft14\&quot;, param4: \&quot;sft14.pdb\&quot;, param5: \&quot;no\&quot;, param6: \&quot;sft14.txt\&quot;, englishOnly: True)" type="System.Xml.Tests.XsltcTestSettings" method="Var1" time="0.2884227" result="Fail">
        <traits>
          <trait name="category" value="XsltcExeRequired" />
        </traits>
        <failure exception-type="OLEDB.Test.ModuleCore.CTestFailedException">
          <message><![CDATA[OLEDB.Test.ModuleCore.CTestFailedException : Output was not as expected.\r\nExpected: `fatal error : Unrecognized option: '/SETTINGS:SCRIPT+'.\r\n`\r\nActual: `fatal error : Unrecognized option: '/SETTİNGS:SCRİPT+'.\r\n`\r\nResult: 0\r\n]]></message>
          <stack-trace><![CDATA[   at System.Xml.Tests.XsltcTestCaseBase.CompareOutput(Stream expectedStream, Stream actualStream, Int32 count) in D:\Runtime\runtime\src\libraries\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs:line 96
   at System.Xml.Tests.XsltcTestCaseBase.VerifyTest(String cmdLine, String asmName, Boolean asmCreated, String typeName, String pdbName, Boolean pdbCreated, String baselineFile, Boolean runAssemblyVerification, Boolean loadFromFile) in D:\Runtime\runtime\src\libraries\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs:line 173
   at System.Xml.Tests.XsltcTestCaseBase.VerifyTest(String cmdLine, String asmName, Boolean asmCreated, String typeName, String pdbName, Boolean pdbCreated, String baselineFile, Boolean loadFromFile) in D:\Runtime\runtime\src\libraries\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs:line 132
   at System.Xml.Tests.XsltcTestSettings.Var1(Object param0, Object param1, Object param2, Object param3, Object param4, Object param5, Object param6, Boolean englishOnly) in D:\Runtime\runtime\src\libraries\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestSettings.cs:line 67]]></stack-trace>
        </failure>
      </test>
```

I do not understand why these tests don't pass, should I also make my Region set to US? I will try to set my region as well and write the results here.

**Comment by danmoseley** [comment] 2022-03-28 19:51
@Danyy427 likely they are all related to Turkish culture. I am not sure what setting would work around that, but ultimately we need to fix them. Not here though -- for fixing this bug, simply ignore it.

Now that you have done this, you can run specifically only the tests in the libraries you care about. I think that is System.IO.Compression and/or System.IO.Compression.ZipFile. [This doc](https://github.com/dotnet/runtime/blob/4019e83878a81465f6e42e8502b53bc5d1752f81/docs/workflow/testing/libraries/testing.md#running-tests-for-a-single-library) shows how to do that.

Your next step is to make a test that consumes it and fails. You can't do this until #67189 goes in unless you do https://github.com/dotnet/runtime-assets/blob/main/README.md#optional-step-local-testing

**Comment by Danyy427** [comment] 2022-03-28 20:12
@danmoseley Yup, I get off topic easily sorry about that, once done with this I will perhaps open an issue on those.

I will try the local testing and see if I can get it to fail, will put a PR once the tests are complete, If I cannot get local testing working I'll just wait for #67189 and clone the git repo again.

**Comment by danmoseley** [comment] 2022-03-28 22:42
@Danyy427 the runtime-assets was merged so you should be good to go.

**Comment by Danyy427** [comment] 2022-03-29 05:43
@danmoseley Thank you, will get to it.

**Comment by Danyy427** [comment] 2022-03-29 13:18
@danmoseley I did write a test after cloning the repo and the file that I uploaded to runtime-assets isn't there. I also checked my local `.nuget` directory for the file and I found all the other tests cases but not the one that I require. Are we certain that the zip has been merged?

**Comment by danmoseley** [comment] 2022-03-29 16:02
@Danyy427 try cleaning (`git clean -fdx`) the repo, `git pull`, and building from the root again?

**Comment by Danyy427** [comment] 2022-03-29 16:31
@danmoseley That didn't work.

**Comment by Danyy427** [comment] 2022-03-29 18:02
@danmoseley Are we sure that #67189 includes the test data from runtime assets? the thread doesn't mention anything but Roslyn analyzers

**Comment by danmoseley** [comment] 2022-03-29 18:03
Doh - you're right. It was https://github.com/dotnet/runtime/pull/67289, which just merged.

Hopefully you can build from the root again, and it will be much faster (incremental) and get you these. I'll do the same myself.

**Comment by danmoseley** [comment] 2022-03-29 18:25
Confirmed that it is now available. You're unblocked 😄

**Comment by Danyy427** [comment] 2022-03-29 18:34
Okay, let me see if I can get those tests to fail.

**Comment by Danyy427** [comment] 2022-03-29 18:53
@danmoseley Do I add both the tests and sanitization in one go or do I first add the tests, open a pull request, see that it fails and then add the sanitization to make them pass?

**Comment by Danyy427** [comment] 2022-03-29 21:00
@danmoseley I have written the sanitization to `GetFileName_Windows` but I forgot to do it for directories. Is there a method like `GetFileName_Windows` for directories that you know of?

**Comment by danmoseley** [comment] 2022-03-29 22:27
> @danmoseley Do I add both the tests and sanitization in one go or do I first add the tests, open a pull request, see that it fails and then add the sanitization to make them pass?

It is always best to write the test(s) and verify it fails before attempting to fix anything. Primarily because that confirms you have written a useful test.

> I  have just finished the sanitization to GetFileName_Windows

I didn't look at the code very hard 😄 It seems the purpose of that method is to find the "file part" of the entry. It's then exposed eg in ZipArchiveEntry.Name. We probably shouldn't "lie" there.

My suggestion is to add the sanitization at the point the file has to be written. It looks like here, FullName is the whole relative path.
https://github.com/dotnet/runtime/blob/dbef8db7c4e1d20dab771f234441c91770f66a58/src/libraries/System.IO.Compression.ZipFile/src/System/IO/Compression/ZipFileExtensions.ZipArchiveEntry.Extract.cs#L99

One way to do this might be to add something like an "internal string SantizedFullName { get { .. }}" property (or maybe FileSystemSafeFullName?)to both ZipArchiveEntry.Windows.cs and ZipArchiveEntry.Unix.cs. On Unix it just returns FullName. On Windows it sanitizes it. Then on the line above, use SanitizedFullName instead of FullName.

**Comment by Danyy427** [comment] 2022-03-30 11:27
@danmoseley I have created a pull requests for the test. #67332

**Comment by Danyy427** [comment] 2022-03-30 15:00
@danmoseley checks are done, some tests failed as expected

**Comment by Danyy427** [comment] 2022-03-30 19:39
@danmoseley In your last post, you said

> One way to do this might be to add something like an "internal string SantizedFullName { get { .. }}" property (or maybe FileSystemSafeFullName?)to both ZipArchiveEntry.Windows.cs and ZipArchiveEntry.Unix.cs. On Unix it just returns FullName. On Windows it sanitizes it. Then on the line above, use SanitizedFullName instead of FullName.

I do not understand why `ValidFullName` shouldn't be public. Aren't we trying to reach it outside of its assembly? One is from System.IO.Compression.Zipfile the other System.IO.Compression, am I misinterpreting how `internal` works.

**Comment by Danyy427** [comment] 2022-03-30 19:52
@danmoseley Also should I build the `System.IO.Compression` again before using `ValidFullName` from [ZipFileExtensions.ZipArchiveEntry.Extract.cs](https://github.com/dotnet/runtime/blob/dbef8db7c4e1d20dab771f234441c91770f66a58/src/libraries/System.IO.Compression.ZipFile/src/System/IO/Compression/ZipFileExtensions.ZipArchiveEntry.Extract.cs#L99)? 

When `ValidFullName` is `internal` and I build the project, I still cannot use it from `ZipArchiveEntry.cs`, I am getting a `CS1061`

On the other hand if I declare `ValidFullName` as `public` the library won't build at all, 
```
C:\Users\Asus\.nuget\packages\microsoft.dotnet.apicompat\7.0.0-beta.22171.2\build\Microsoft.DotNet.ApiCompat.targets(94,5): error : Compat issues with assembly System.IO.Compression: [D:\Runtime\runtime\src\libraries\System.IO.Compression\src\System.IO.Compression.csproj]
C:\Users\Asus\.nuget\packages\microsoft.dotnet.apicompat\7.0.0-beta.22171.2\build\Microsoft.DotNet.ApiCompat.targets(94,5): error : MembersMustExist : Member 'public System.String System.IO.Compression.ZipArchiveEntry.ValidFullName.get()' does not exist in the reference but it does exist in the implementation. [D:\Runtime\runtime\src\libraries\System.IO.Compression\src\System.IO.Compression.csproj]
C:\Users\Asus\.nuget\packages\microsoft.dotnet.apicompat\7.0.0-beta.22171.2\build\Microsoft.DotNet.ApiCompat.targets(94,5): error : Compat issues with assembly System.IO.Compression: [D:\Runtime\runtime\src\libraries\System.IO.Compression\src\System.IO.Compression.csproj]
C:\Users\Asus\.nuget\packages\microsoft.dotnet.apicompat\7.0.0-beta.22171.2\build\Microsoft.DotNet.ApiCompat.targets(94,5): error : MembersMustExist : Member 'public System.String System.IO.Compression.ZipArchiveEntry.ValidFullName.get()' does not exist in the reference but it does exist in the implementation. [D:\Runtime\runtime\src\libraries\System.IO.Compression\src\System.IO.Compression.csproj]
C:\Users\Asus\.nuget\packages\microsoft.dotnet.apicompat\7.0.0-beta.22171.2\build\Microsoft.DotNet.ApiCompat.targets(94,5): error : Compat issues with assembly System.IO.Compression: [D:\Runtime\runtime\src\libraries\System.IO.Compression\src\System.IO.Compression.csproj]
C:\Users\Asus\.nuget\packages\microsoft.dotnet.apicompat\7.0.0-beta.22171.2\build\Microsoft.DotNet.ApiCompat.targets(94,5): error : MembersMustExist : Member 'public System.String System.IO.Compression.ZipArchiveEntry.ValidFullName.get()' does not exist in the reference but it does exist in the implementation. [D:\Runtime\runtime\src\libraries\System.IO.Compression\src\System.IO.Compression.csproj]
```

**Comment by danmoseley** [comment] 2022-03-30 20:11
Ah. It looks like you can't piggy back in ZipArchiveEntry.Windows.cs (which is in System.IO.Compression) because you need it in ZipFileExtensions.ZipArchiveEntry.Extract.cs (which is in System.IO.Compression.ZipFile)

Instead I suggest creating something like ZipFileExtensions.ZipArchiveEntry.Extract.Windows.cs and putting it next to ZipFileExtensions.ZipArchiveEntry.Extract.cs and editing System.IO.Compression.ZipFile.csproj so it's only used on Windows. Hmm, that csproj does not have a Windows-specific build. It would need `$(NetCoreAppCurrent)-windows` added to `<TargetFrameworks>` so you can use `Condition="'$(TargetPlatformIdentifier)' == 'windows'"` to include this new file.

I'm not familiar with all these arrangements and why bits of zip are in S.IO.C and bits are in S.IO.C.Z.. @carlossanlop do you have a suggestion?

**Comment by Danyy427** [comment] 2022-03-30 20:55
@danmoseley Instead of adding `ValidFileName` to `ZipArchiveEntry.Windows.cs` and `ZipArchiveEntry.Unix.cs` separately, could I add it to `ZipArchiveEntry.cs` directly and check for the platform inside of `get`. If it is windows I sanitize the characters, if not I sanitize `\0` or nothing at all?

**Comment by danmoseley** [comment] 2022-03-31 01:13
Ideally we don't check OS at runtime.

@ericstj  what is our base for adding a windows target to this library?

**Comment by Danyy427** [comment] 2022-03-31 05:03
@danmoseley I don't know if it would work (I cannot test it right now) but we could maybe add `_ValidFullName` to `ZipArchiveEntry.Windows.cs` and `ZipArchiveEntry.Unix.cs`, declare them as `internal`, then declare a `public` property `ValidFullName` which just returns `_ValidFullName`in ZipArchiveEntry.cs

**Comment by carlossanlop** [comment] 2022-03-31 16:55
> _Ah. It looks like you can't piggy back in ZipArchiveEntry.Windows.cs (which is in System.IO.Compression) because you need it in ZipFileExtensions.ZipArchiveEntry.Extract.cs (which is in System.IO.Compression.ZipFile)_

If I'm understanding this correctly, you're trying to consume code from `System.IO.Compression.ZipFile` in `System.IO.Compression`. Correct? One option is to put the shared code in a new file in `src/libraries/Common/System/IO/Compression`, and then include that file in both `S.IO.Compression` and `S.IO.Compression.ZipFile` csproj projects. As long as the code is `internal`, it should work for both.

A great example of this practice are the `src/libraries/Common/src/System/IO/PathInternal*.cs` files, which are [consumed in a few different assemblies](https://github.com/dotnet/runtime/search?q=extension%3Acsproj+PathInternal).

**Comment by Danyy427** [comment] 2022-03-31 17:03
@carlossanlop We are also trying to make some of the code work specifically on Windows and some of it on Unix, like `ZipArchiveEntry.Windows.cs` and `ZipArchiveEntry.Unix.cs` which should also be a common code in Compression and Compression.Zipfile

**Comment by ericstj** [comment] 2022-03-31 17:20
> @ericstj what is our base for adding a windows target to this library?

Add `$(NetCoreAppCurrent)-windows` to this 
https://github.com/dotnet/runtime/blob/631389fb941eb618fef883975ca5f4f5b03a93cf/src/libraries/System.IO.Compression.ZipFile/src/System.IO.Compression.ZipFile.csproj#L4

and make sure you condition your new files on `TargetPlatformIdentifier` like this:
https://github.com/dotnet/runtime/blob/20e8f905d05f2d8f390d0e2ef10f1a4a1289967c/src/libraries/System.IO.Compression/src/System.IO.Compression.csproj#L47-L50

**Comment by Danyy427** [comment] 2022-03-31 18:58
@danmoseley I do not know how I should be using this knowledge. I _tried_ to do _something_ but it's just errors everywhere now :)

I added two files `ZipFileValidName_Windows.cs` and `ZipFileValidName_Unix.cs` to `src/libraries/Common/System/IO/Compression`, added both of the files to their relative target platforms in the csproj files. Like this:

System.IO.Compression.sln:
```
<!-- Windows specific files -->
...
<Compile Include="$(CommonPath)System\IO\Compression\ZipFileValidName_Windows.cs"
             Link="Common\System\IO\Compression\ZipFileValidName_Windows.cs" />

<!-- Unix specific files -->
...
<Compile Include="$(CommonPath)System\IO\Compression\ZipFileValidName_Unix.cs"
             Link="Common\System\IO\Compression\ZipFileValidName_Unix.cs" />
```
and to System.IO.Compression.ZipFile I first added `$(NetCoreAppCurrent)-windows;` to `TargetFrameworks` then added the  files:

``` <!-- Windows specific files -->
  <ItemGroup Condition="'$(TargetPlatformIdentifier)' == 'windows'">
    <Compile Include="System\IO\Compression\ZipArchiveEntry.Windows.cs" />
    <Compile Include="$(CommonPath)Interop\Windows\Interop.Libraries.cs"
             Link="Common\Interop\Windows\Interop.Libraries.cs" />
    <Compile Include="$(CommonPath)System\IO\Compression\ZipFileValidName_Windows.cs"
             Link="Common\System\IO\Compression\ZipFileValidName_Windows.cs" />
  </ItemGroup>

<!-- Unix specific files -->
...
<Compile Include="$(CommonPath)System\IO\Compression\ZipFileValidName_Unix.cs"
             Link="Common\System\IO\Compression\ZipFileValidName_Unix.cs" />
```
Finally changed the `FullName` to `ValidFullName` in `ZipExtensions.ZipArchiveEntry.Extract.cs` but now every ZipArchiveEntry in the file is giving a `CS0436` error.

**Comment by Danyy427** [comment] 2022-03-31 22:43
@danmoseley I pushed my changes, note that some weird character was written at the start of the csproj files, probably something wrong with vs or notepad++, the last commit was to remove those

**Comment by Danyy427** [comment] 2022-04-01 18:30
@danmoseley did you have a chance to look at the changes?

**Comment by Danyy427** [comment] 2022-04-01 23:49
@danmoseley Actually instead of trying to add a `ValidFullName` to S.IO.C and trying to use it from S.IO.C.Z, why don’t we just write platform dependent methods to S.IO.C.Z and avoid the shared code part altogether. Is there a particular reason why we are trying to avoid writing methods to sanitize the filename?

**Comment by danmoseley** [comment] 2022-04-02 00:03
@carlossanlop  do you have a preference?

**Comment by Danyy427** [comment] 2022-04-02 16:52
@danmoseley I was going to try out writing sanitization as a method and I did do it for windows and Unix but there seem to be 4 target platforms. It seems that Unix and Browser go together but what about net7.0 without any target platform specified. Does that supposed to have sanitization or not?

**Comment by Danyy427** [comment] 2022-04-02 17:37
@danmoseley I made the test that I have written pass locally using a method to sanitize the filename. Every other test fails miserably tho

**Comment by Danyy427** [comment] 2022-04-02 17:56
@danmoseley I have pushed the changes that made the local test pass, how should I deal with tests that expect the extraction to fail when there are invalid characters in the filename?

**Comment by danmoseley** [comment] 2022-04-03 01:54
>  how should I deal with tests that expect the extraction to fail when there are invalid characters in the filename?

You'd update those tests so they expect the new behavior.

**Comment by Danyy427** [comment] 2022-04-08 18:44
@danmoseley I fixed all of the tests and they all passed on my local system. Instead of deleting the `ThrowsException` tests, I merged the entirety of them into my own test function that I have written initially so we can test all of the invalid and null zip file test cases. I have pushed the code to #67332 and if they pass here as well they should be good to go.

**Comment by danmoseley** [comment] 2022-04-13 04:20
fixed by https://github.com/dotnet/runtime/pull/67332

**Closed by danmoseley** 2022-04-13 04:20 UTC
Labels: area-System.IO.Compression, easy
