### ISSUE TITLE
WebAssembly: brotli and AOT result in assert in aot-runtime.c:2038

### ISSUE THREAD

**Issue by SeanLeitzinger** [dotnet/runtime#62806] opened 2021-12-14 18:53 UTC
### Description

Enabling AOT compilation for .NET 6 standalone WASM Blazor application and then publishing to server works as expected. Following instructions for Brotli compression causes aot error when loading application.

### Reproduction Steps

1. Publish Blazor .NET 6.0 with AOT compilation enabled.
2. Follow the instructions here https://docs.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0#compression for enabling brotli compression in Blazor standalone using the brotli decode.min.js
3. Serve application and note the brotli files are now served correctly.

![image](https://user-images.githubusercontent.com/24277209/146057509-26a51188-6d17-4a4a-9e08-81f5e0419e47.png)

4. Console throws error displayed below:
![image](https://user-images.githubusercontent.com/24277209/146057639-194eaa71-b34e-403a-94da-0b6da525f9dc.png)

### Expected behavior

Blazor App loads successfully and serves brotli files without mono AOT error.

### Actual behavior

Blazor app fails to load after enabling brotli compression according to MS documentation.

### Configuration

.NET 6, Windows Server 2019 served using Kestrel and YARP.

### Other information

Publishing with AOT enabled works without brotli compression. Failure occurs after following MS documents on enabling Brotli compression for standalone WASM Blazor.

**Comment by lambdageek** [comment] 2021-12-14 19:13
The error messsage comes from 

https://github.com/dotnet/runtime/blob/1208ca1d9b18de80897cceb4a414b4175371108b/src/mono/mono/mini/aot-runtime.c#L2038

Which means one of:
1. The runtime couldn't find the AOT image
2. The AOT image valid (too old, doesn't match the managed assembly, etc)

Note that turning on Brotli seems to be the trigger here.  The same sample with AOT but without brotli works.

**Comment by lambdageek** [comment] 2021-12-14 20:14
@SeanLeitzinger I tried `dotnet new blazorwasm` and then:

1. added `<RunAOTCompilation>true</RunAOTCompilatoin>` to the .csproj
2. Added `brotli.min.js` to `wwwroot`
3. Added the script, but modified so it will do compression even on localhost - 
   ```html
    <script type="module">
   import { BrotliDecode } from './decode.min.js';
   Blazor.start({
     loadBootResource: function (type, name, defaultUri, integrity) {
       if (type !== 'dotnetjs' /*&& location.hostname !== 'localhost'*/) {
         return (async function () {
           const response = await fetch(defaultUri + '.br', { cache: 'no-cache' });
           if (!response.ok) {
             throw new Error(response.statusText);
           }
           const originalResponseBuffer = await response.arrayBuffer();
           const originalResponseArray = new Int8Array(originalResponseBuffer);
           const decompressedResponseArray = BrotliDecode(originalResponseArray);
           const contentType = type === 
             'dotnetwasm' ? 'application/wasm' : 'application/octet-stream';
           return new Response(decompressedResponseArray, 
             { headers: { 'content-type': contentType } });
         })();
       }
     }
   });
    </script>
   ```
4. Ran `dotnet publish -p:PublishDir=pub`
5. Ran `cd pub/wwwroot && python3 -m http.server`
6. Opened `localhost:8000` in a browser
7. In Chrome Dev Tools, deleted the cached blazor files 
<img width="492" alt="Screen Shot 2021-12-14 at 15 12 04" src="https://user-images.githubusercontent.com/480437/146072368-c27713f2-6562-4c7e-baf1-6f8f064c854e.png">
8. On the Chrome Dev Tools, "Network" tab, disabled the cache and then reloaded the page.
9. I see `.br` files being served, and the "Counter" and "Fetch Data" both appear to work.


Is there something else I need to do to reproduce the issue?

**Comment by SeanLeitzinger** [comment] 2021-12-14 20:49
No. I ended up turning off AOT compilation on my publish and turned on Brotli and it worked. There is possibly something in my project specifically that isn't working properly?

**Comment by SeanLeitzinger** [comment] 2021-12-14 21:25
@lambdageek I decided to try AOT with brotli once again. Deleted everything, and also upgraded to 6.0.1 on everything. I'm not sure if it just magically started working because of the complete delete and redeploy (again) or if the upgrade to 6.0.1 just now had an effect.

**Comment by lambdageek** [comment] 2021-12-14 21:36
> @lambdageek I decided to try AOT with brotli once again. Deleted everything, and also upgraded to 6.0.1 on everything. I'm not sure if it just magically started working because of the complete delete and redeploy (again) or if the upgrade to 6.0.1 just now had an effect.

I wonder if you were getting stale assemblies or a stale dotnet.wasm from the browser cache.  one of the cases where that assert would hit is if the AOT images (which end up all linked together with the runtime into dotnet.wasm) encode a different module GUID (MVID) than their corresponding assembly dlls.

**Comment by lambdageek** [comment] 2021-12-14 21:56
> Not sure. Is there a way to get the full error message in the future when these kinds of AOT errors occur?

@kg @lewing do we have some way to drop in a wasm build that has full assertion messages into a blazor project?  Even (especially) for the AOT case?

**Comment by radical** [comment] 2021-12-14 22:29
> do we have some way to drop in a wasm build that has full assertion messages into a blazor project? Even (especially) for the AOT case?

I don't think we have an easy way to do that. You could build `dotnet/runtime` with `-p:MonoEnableAssertMessages=true`, and use the runtime pack from there - `artifacts/bin/microsoft.netcore.app.runtime.browser-wasm/Release/runtimes/browser-wasm/native`.

Maybe it would be useful to have such a build added to the runtime pack, and use that when debugging.

btw, building with `-p:WasmNativeStrip=false` should give you better stack trace.

**Comment by SeanLeitzinger** [comment] 2021-12-14 23:11
Thanks. I'll keep it in mind for the future. @lambdageek Thanks for help.

**Comment by kg** [comment] 2021-12-18 03:11
If you do a full build of the runtime in debug mode i.e. ```./build.sh --os Browser -c debug```, the resulting runtime pack appears to be usable with Blazor via a blob like this in your csproj:

```xml
    <Target Name="UpdateRuntimePack"
            AfterTargets="ResolveFrameworkReferences">
        <ItemGroup>
            <ResolvedRuntimePack PackageDirectory="your-source-checkout/artifacts/bin/microsoft.netcore.app.runtime.browser-wasm/Debug"
                                 Condition="'%(ResolvedRuntimePack.FrameworkName)' == 'Microsoft.NETCore.App'" />
        </ItemGroup>
    </Target>
```

I haven't tested this extensively, but I was able to run a debug build with debug symbols for troubleshooting via this method, so it should be possible to get assertion messages this way too. For assertions in release mode you should be able to use the suggestion above about `MonoEnableAssertMessages` when building your runtime pack. Combining this with AOT is not something I've figured out how to do though.

**Comment by kg** [comment] 2022-06-14 08:37
Closing because I believe the issue was resolved, please feel free to reopen if you hit this issue again and I can work with you to troubleshoot.

**Closed by kg** 2022-06-14 08:37 UTC
Labels: arch-wasm, area-Codegen-AOT-mono
