### ISSUE TITLE
[wasm][aot] build tries to cross compile unrelated dlls from the publish folder

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#46856] opened 2021-01-12 15:08 UTC
In effort to run library tests with AOT compilation on CI https://github.com/dotnet/runtime/issues/46633, there are a number of failures arising from https://github.com/dotnet/runtime/pull/46651.

Test suite `System.Diagnostics.FileVersionInfo/tests/System.Diagnostics.FileVersionInfo.Tests/System.Diagnostics.FileVersionInfo.Tests.csproj` fails on MonoAOTCompiler task with
```
/Users/mdhwang/runtime_wasm_clean/src/mono/wasm/build/WasmApp.targets(43,5): error : Can not open image /Users/mdhwang/runtime_wasm_clean/artifacts/bin/System.Diagnostics.FileVersionInfo.Tests/net6.0-Browser-Release/browser-wasm/publish/NativeLibrary.dll [/Users/mdhwang/runtime_wasm_clean/src/libraries/System.Diagnostics.FileVersionInfo/tests/System.Diagnostics.FileVersionInfo.Tests/System.Diagnostics.FileVersionInfo.Tests.csproj]
/Users/mdhwang/runtime_wasm_clean/src/mono/wasm/build/WasmApp.targets(43,5): error : Precompiling failed for /Users/mdhwang/runtime_wasm_clean/artifacts/bin/System.Diagnostics.FileVersionInfo.Tests/net6.0-Browser-Release/browser-wasm/publish/NativeLibrary.dll: Error: Can not open image /Users/mdhwang/runtime_wasm_clean/artifacts/bin/System.Diagnostics.FileVersionInfo.Tests/net6.0-Browser-Release/browser-wasm/publish/NativeLibrary.dll [/Users/mdhwang/runtime_wasm_clean/src/libraries/System.Diagnostics.FileVersionInfo/tests/System.Diagnostics.FileVersionInfo.Tests/System.Diagnostics.FileVersionInfo.Tests.csproj]
/Users/mdhwang/runtime_wasm_clean/src/mono/wasm/build/WasmApp.targets(43,5): error :  [/Users/mdhwang/runtime_wasm_clean/src/libraries/System.Diagnostics.FileVersionInfo/tests/System.Diagnostics.FileVersionInfo.Tests/System.Diagnostics.FileVersionInfo.Tests.csproj]
/Users/mdhwang/runtime_wasm_clean/src/mono/wasm/build/WasmApp.targets(43,5): error :  [/Users/mdhwang/runtime_wasm_clean/src/libraries/System.Diagnostics.FileVersionInfo/tests/System.Diagnostics.FileVersionInfo.Tests/System.Diagnostics.FileVersionInfo.Tests.csproj]
```
[System_diagnostics_fileversioninfo_fail.txt](https://github.com/dotnet/runtime/files/5802934/System_diagnostics_fileversioninfo_fail.txt)

## Repro
Check out changes in https://github.com/dotnet/runtime/pull/46651
`./build.sh -os Browser -arch wasm -c Release`
Remove https://github.com/dotnet/runtime/blob/f7f50465ee2c23f8a59753027af4f84b73737f52/eng/testing/ILLink.Descriptor.xunit.xml#L15-L20
Modify https://github.com/dotnet/runtime/blob/9538bee0fc1fb24993217071e954d9597385485f/src/libraries/System.Private.CoreLib/src/System/IO/FileStream.Unix.cs#L256  to be an empty catch
```
catch
{
}
```
`./dotnet.sh build /t:Test /p:TargetOS=Browser /p:TargetArchitecture=wasm /p:Configuration=Release /p:EnableAggressiveTrimming=true /p:RunAOTCompilation=true src/libraries/System.Diagnostics.FileVersionInfo/tests/System.Diagnostics.FileVersionInfo.Tests/System.Diagnostics.FileVersionInfo.Tests.csproj`

**Comment by radical** [comment] 2021-01-12 19:08
This depends on a native library, which is why `MonoAOTCompiler` fails with it. Are these tests supported, or should be supported on wasm? These were disabled in https://github.com/dotnet/runtime/commit/c72d522e91a91a5122de82deaed38727a4d6612f .

What is the expected behavior?

**Comment by lambdageek** [comment] 2021-05-18 17:56
The problem is that `NativeLibrary.dll` is a win32 dll, not a .NET assembly.  So when we pass it to `MonoAOTCompiler`, it can't open it and fails.

We should either:
1. change the `Content` line in this test file to include some metadata that will tell the build infrastructure not to pass this assembly to the AOT compiler, or
2. just skip this test

**Comment by lambdageek** [comment] 2021-05-18 17:57
It also affects https://github.com/dotnet/runtime/pull/52848.  And probably ios device testing, too.  basically anything that needs the AOT compiler

**Comment by steveisok** [comment] 2021-05-21 00:58
In https://github.com/dotnet/runtime/pull/52848 I defined a `<NativeLibraries>` itemgroup.  That ends up being part of the items that are excluded from the aot compiler. If there's a better way, I'm all ears.  

https://github.com/dotnet/runtime/blob/227847cb6b1ea703d7f4ac27d30422245022df7a/eng/testing/tests.mobile.targets#L169-L175

**Comment by lewing** [comment] 2021-07-31 19:31
@radical what is your plan here?

**Comment by radical** [comment] 2021-08-01 00:10
Currently, we pick up all the files from the publish folder, where this assembly also ends up because it is in `@(Content)`. I expect this to be fixed once we have the wasm targets taking the relevant list of referenced assemblies from earlier targets (eg. `ResolveAssemblyReferences`).

**Comment by radical** [comment] 2021-09-08 17:14
This needs some more work (a bit involved) to integrate with Publish at a more granular level.

**Comment by radical** [comment] 2022-06-14 15:42
> @radical, any progress?

No. We should keep this for 7.0 milestone for now, but I'm not sure if we'll actually be able to get to it. This is dependent on better integration with `publish`.

**Comment by radical** [comment] 2022-07-28 21:04
The original issue here - that of `MonoAOTCompiler` task trying to compile unmanaged dlls is fixed, as we skip those now.

https://github.com/dotnet/runtime/blob/d7c8bc10ac00fe330daa633f8a2b16ba208e6e56/src/tasks/AotCompilerTask/MonoAOTCompiler.cs#L603-L607

The broader issue of handling publish assets better, is separate from this.

**Closed by radical** 2022-07-28 21:04 UTC
Labels: arch-wasm, area-Build-mono
