### ISSUE TITLE
`JsonIgnoreAttribute` isn't honored in init-only properties.

### ISSUE THREAD

**Issue by N0D4N** [dotnet/runtime#89365] opened 2023-07-23 15:13 UTC
### Description

When using `JsonIgnoreAttribute` on property with `init` setter, source generator doesn't honor ignoring such property

### Reproduction Steps

See the code below
```cs
using System.Text.Json.Serialization;
using System.Text.Json;

const string json = """{"Prop1": "sample"}""";
Console.WriteLine(JsonSerializer.Deserialize<Example>(json).Prop2);
Console.WriteLine(JsonSerializer.Deserialize<Example>(json, MyContext.Default.Example).Prop2);

public class Example
{
	private string p1Value;

	public string Prop1
	{
		get => p1Value;
		init
		{
			p1Value = value;
			Prop2 = value.Substring(1) + "123";
		}
	}

	[JsonIgnore]
	public string Prop2 { get; init; }
}

[JsonSourceGenerationOptions(GenerationMode = JsonSourceGenerationMode.Metadata)]
[JsonSerializable(typeof(Example))]
public partial class MyContext : JsonSerializerContext
{ }
```

### Expected behavior

`JsonSerializer` honors `JsonIgnoreAttribute` and doesn't try to set the value to the property.

In terms of provided sample it would be seeing following text as console output
```
ample123
ample123
```

### Actual behavior

`JsonSerializer` does not honor JsonIgnoreAttribute on a property and tries to set its value

In terms of provided sample it is
```
ample123

```

### Regression?

Not, since as far as i am aware, source-generation support for init-only properties was introduced in one of .NET 8 previews

### Known Workarounds

Replace `init` with `set` if applicable

### Configuration

dotnet --info
```
.NET SDK:
 Version:   8.0.100-preview.6.23330.14
 Commit:    ba97796b8f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.6.23330.14\
```

### Other information

It seems, issue comes from source generator trying to set ALL properties in `ObjectWithParameterizedConstructorCreator`, even if they are marked with `JsonIgnore`

With provided sample it is
```cs
var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::Example>
{
	ObjectCreator = null,
    ObjectWithParameterizedConstructorCreator = static args => new global::Example(){ Prop1 = (string)args[0], Prop2 = (string)args[1] },
    PropertyMetadataInitializer = _ => ExamplePropInit(options),
    ConstructorParameterMetadataInitializer = ExampleCtorParamInit,
    SerializeHandler = null
};
```

**Comment by eiriktsarpalis** [comment] 2023-07-24 11:14
This is a duplicate of https://github.com/dotnet/runtime/issues/84484.

**Closed by eiriktsarpalis** 2023-07-24 11:14 UTC
Labels: area-System.Text.Json, untriaged
