### ISSUE TITLE
Type 'Program' can be sealed because it has no subtypes in its containing assembly and is not externally visible

### ISSUE THREAD

**Issue by Romfos** [dotnet/runtime#78270] opened 2022-11-12 17:27 UTC
### Description
Diagnostic CA1852 throw warning\error for Program.cs with top level statement code.
From my point of view program.cs should be sealed by default for top level statement or this diagnostic should ignore it for this specific type

### Reproduction Steps

1) Create new c# project (with top level statement)
2) create .editorconfig with dotnet_diagnostic.CA1852.severity = error
3) Try to build

### Expected behavior

No errors\warnings

### Actual behavior

Error:
Type 'Program' can be sealed because it has no subtypes in its containing assembly and is not externally visible

### Known Workarounds

n\a

### Configuration

.NET SDK 7.0.100
Visual Studio 2022 17.4

**Comment by Romfos** [comment] 2022-11-12 17:32
This is related to https://github.com/dotnet/runtime/issues/49944

**Comment by stephentoub** [comment] 2022-11-12 17:40
Duplicate of https://github.com/dotnet/roslyn-analyzers/issues/6141

**Closed by stephentoub** 2022-11-12 17:40 UTC
Labels: untriaged

**Comment by nietras** [comment] 2022-11-29 10:20
Putting the following at top of `Program.cs` can disable the CA in that file for a work around:
```csharp
// CA1852 Type 'Program' can be sealed because it has no subtypes in its containing assembly and is not externally visible
#pragma warning disable CA1852
```
more CA issues in https://github.com/dotnet/sdk/issues/29164
