### ISSUE TITLE
How are we doing in the repo -- spot check

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#92377] opened 2023-09-20 21:25 UTC
![image](https://github.com/dotnet/runtime/assets/6385855/bd3fe7e2-61e5-477f-af0f-980a62ab3d04)

It's midyear between our surveys and we'd like to hear from you how we're doing.

https://www.surveymonkey.com/r/TPJKJWW

If you are reading this, we'd welcome your input. There's only one question so it should take just seconds (unless you want to write something)

-- dotnet/runtime maintainers

**Comment by teo-tsirpanis** [comment] 2023-09-20 23:03
Duplicate of #92378.

**Closed by teo-tsirpanis** 2023-09-20 23:03 UTC
Labels: area-Meta, untriaged
