### ISSUE TITLE
KB4560960 cannot print certain images

### ISSUE THREAD

**Issue by Ravenheart** [dotnet/runtime#38434] opened 2020-06-26 10:08 UTC
### Description

After installing Windows10 update KB4560960 printing certain documents hang when printed from .NET code. Specifically I have a .rtf file loaded with a DevExpress winforms control. 

After investigation by them the problem was reproduced outside their controls, the problem appears to be in System.Printing and it occurs when printing specific images. Applying hotfix KB4567512 does not solve the problem.

Repo: https://github.com/Ravenheart/KB4560960
The repo is attempting to print to pdf, after entering the save file it will hang on printing "Page 1 of Document".

### Configuration

.NET Framework 4.8
Windows 10 Pro x64
Installed updates: KB4560960 & KB4567512 

### Regression?

If you uninstall update KB4560960 it works again.

### Other information
[broken.png](https://github.com/Ravenheart/KB4560960/raw/master/KB4560960PrintProblem/broken.png)
```csharp
using System.Drawing;
using System.Drawing.Printing;

namespace KB4560960PrintProblem
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var printDocument = new PrintDocument())
            {
                printDocument.PrinterSettings = new PrinterSettings { PrinterName = "Microsoft Print to PDF" };
                printDocument.PrintPage += PrintDocument_PrintPage;
                printDocument.Print();
            }
        }

        private static void PrintDocument_PrintPage(object sender, PrintPageEventArgs e)
        {
            e.HasMorePages = false;
            using (var bmp = Image.FromFile(@"broken.png"))
            {
                e.Graphics.DrawImage(bmp, new PointF());
            }
        }
    }
}

```

**Comment by safern** [comment] 2020-06-26 21:06
This is happening in .NET Framework, @Ravenheart does this reproduce in .NET Core 5.0 Preview 5?

**Comment by Ravenheart** [comment] 2020-06-27 06:38
.NET 5 preview works, but our application is targeting .NET Framework 4.7.2. Should I file the bug somewhere else?

**Comment by Ravenheart** [comment] 2020-07-07 09:53
Any status updates on this, is there a public bug report I can track for changes?

**Comment by safern** [comment] 2020-07-07 17:00
@Ravenheart thanks for confirming this works on .NET 5. The reason why I wanted to know if it worked fine there is because in .NET 5 we changed the GDI+ we use from 1.0 to 1.1. So it seems like this is definitely a regression from GDI+ 1.0. I'll contact the GDI+ team to see if we can get this fixed.

**Comment by safern** [comment] 2020-07-07 19:47
@Ravenheart I've reached out the Windows team and they confirmed that there is a known regression that this happens when image size is > 1MB. The sample image you shared is ~2MBs so that falls into that category. Did you see this issue happen with images < 1MB? 

They said the fix will be shipped soon. I will close the issue given that this is Windows bug but we can keep the discussion open and I can update the issue whenever they confirm the fix is shipped. Thanks for reaching out.

**Closed by safern** 2020-07-07 19:47 UTC
Labels: area-System.Drawing
