### ISSUE TITLE
While sampling geometric distribution, there is a problem at x=54

### ISSUE THREAD

**Issue by Kri-Ol** [dotnet/runtime#40490] opened 2020-08-06 20:22 UTC
### Description

While following up with https://stackoverflow.com/questions/63276505/why-is-the-pseudo-random-number-generator-less-likely-to-generate-54-big-numbers, I've confirmed problem exists for x=54 in both .NET Core 5 preview 7 and .NET Core 3.1.400.
Trying to generate what amounts to [geometric distribution](https://en.wikipedia.org/wiki/Geometric_distribution), it was discovered that at x=54 there is an unnatural dip in the distribution.

### Configuration

- .NET Core 5 Preview 7
- .NET Core 3.1.400
- Windows 10 2004 x64, Intel I7 6820HQ
- dotnet cmdline tools running in Windows Terminal app

### Regression?

No, original author found this problem on .NET 4.7.2

### Other information

Code sample

    using System;

    namespace Random54
    {
        class Program
        {
            static void Main(string[] args)
            {
                int C = 512;

                var hist = new int [C];

                int N = 100000000;
                double p = 1.0 / 32.0;

                Random rand = new Random(1);

                for (int k = 0; k != N; ++k)
                {
                    int count = 0; // this is a bit naive way to sample geometric distribution
                    while (!(rand.NextDouble() < p))
                        ++count;

                    hist[Math.Clamp(count, 0, C - 1)] += 1;
                }

                for (int i = 0; i != C; ++i)
                {
                    Console.WriteLine($"{i} {hist[i]}");
                }
            }
        }
    }

Output around x = 54, shall be exponent-like function

    51 618189
    52 600671
    53 581831
    54 290146  NB!
    55 563490
    56 544739
    57 527011
    58 510480

Potential source of the problem is random numbers generator.

**Comment by danmosemsft** [comment] 2020-08-06 20:25
Thanks for this issue. We don't plan to modify the algorithm of Random (at least when a seed is provided) because it would break folks.  There is some discussion here which you are welcome to contribute to : https://github.com/dotnet/runtime/issues/23198

**Comment by danmosemsft** [comment] 2020-08-06 20:25
Duplicate of https://github.com/dotnet/runtime/issues/23198

**Closed by danmosemsft** 2020-08-06 20:25 UTC
Labels: untriaged
