### ISSUE TITLE
[API Proposal] A way to force load assembly pdbs on assemblies loaded with Assembly.LoadFrom()

### ISSUE THREAD

**Issue by AraHaan** [dotnet/runtime#44743] opened 2020-11-16 17:45 UTC
## Background and Motivation

Let's say for example, you got a program, that targets Any CPU, it has support dlls that helps provide a plugin interface, then a plugin creator thinks it's a great idea to write an plugin using c++ with the ``/clr`` switch with it targeting net5.0. Now in that program it will load the assembly, however in my assembly it minidumps itself every time any sort of stack trace is generated which is not captured by any of my ``try``, ``catch`` blocks for reasons that include:
- possible changes in the libraries where they now throw more exeptions.
- other reasons that causes them to throw things not caught in them.

My program then has a setting to then force load the pdbs for the entire program's execution time for the event this happens to help ``MiniDumpWriteDump`` do it's job from an p/invoke on the Exception Handler on the program.

This all works fine, pdbs can be force loaded for the plugins on my program that *are* written in c# like the program itself, however the same is not done for the other assemblies (or even the runtime itself really it would be great if my program could instruct the runtime to load it's pdbs in case of crash for more accurate dumps as well based on my programs configuration settings I have my program present to the user).

## Proposed API

```diff
namespace System.Reflection
{
    public abstract class Assembly : ICustomAttributeProvider, ISerializable
    {
+        public static Assembly LoadFrom(string assemblyFile, string pdbFile);
    }
}
```

## Usage Examples

This might not be the best of examples but it basically explains the gist of things without 100 lines of code.
``` C#
// some lines of code here
namespace example
{
    using System.Reflection;

    public class Program
    {
        public void Main(string[] argc)
        {
            // set up exception handling and stuff that generates minidumps to avoid the windows problem reporting stuff.
            var assembly = Assembly.LoadFrom("MyCLRPlugin.dll", "MyCLRPlugin.pdb");
            // load types from the assembly then call stuff from it.
        }
    }
}
```

## Alternative Designs

Maybe an arg to UnsafeLoadFrom that takes in the pdb path and loads the pdb forcefully somehow but, not sure if that is even needed since LoadFrom exists and can load the stuff fine maybe?

## Risks

I think the only risk is trying to figure out how to force load the pdbs for the clr assemblies (like how c# ones can be loaded with byte arrays), perhaps more if an option to force load them using some apis on the runtime is added or not either as much as they would be helpful to my program if crashes do happen because as a developer I basically want to know what the heck happened and all the right details as to *why* something went wrong.

**Comment by vitek-karas** [comment] 2020-11-16 18:17
Just so that I understand the intent fully:
You're experiencing "incomplete" dumps if the runtime is not told about PDBs for managed assemblies? How does that show up - what information is missing?
AFAIK creation of dumps should not rely on PDBs at all - @noahfalk  should know for sure though.

Also - this would only work on managed assemblies (whether they're written in C# or C++ should not make a difference). So I guess I don't understand the comment about the runtime itself which is native code.

You also seem to imply that you can already force-load symbols for assemblies compiled from C# - how do you do that? (`LoadFromStream`?).

I think basically the only thing in .NET Core Framework which is affected by having (or not) PDBs is stack trace generation in exceptions and similar places and then managed debuggers for cases where code is loaded from memory. @noahfalk is there a way to influence the automatic PDB loading which happens when generating stack traces for example?

As for this particular API, if we were to add functionality like this, I think it should go to `AssemblyLoadContext.LoadFromAssemblyPath`. `Assembly.LoadFrom` is problematic already because it always loads into the default load context (but the fact it does that is not obvious), which can lead to unexpected behaviors if used from libraries and similar. For this reason we're trying to encourage people to use the `AssemblyLoadContext.LoadFromAssemblyPath` instead which is explicit in which load context it works on - at least it makes people think about load contexts when loading assemblies.

**Comment by noahfalk** [comment] 2020-11-16 19:20
I'll admit I am having some trouble understanding the initial request but hopefully we can do a little Q&A to understand better. 

> My program then has a setting to then force load the pdbs

I'm not sure what you mean by this. Is there a particular API you are calling or memory mapping that you are doing that 'force loads' a PDB?

> AFAIK creation of dumps should not rely on PDBs at all - @noahfalk should know for sure though

I'm also not aware of any logic in the dump creation code that should depend on the presence of a PDB, at least not directly. I could imagine indirect effects such as if the runtime loaded the pdb as part of formatting an exception string then those bytes are now in memory and capturable in the content of a dump. However I believe the debugger still distinguishes between a module with 'in memory symbols' (symbols loaded via [Assembly.Load(byte[],byte[])](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.load?view=net-5.0#System_Reflection_Assembly_Load_System_Byte___System_Byte___)) and symbols that happened to be mapped into memory somewhere as part of the runtime parsing an on-disk pdb. In the former case the debugger knows where to look in the runtime data structures in the dump, in the latter the memory mapping is some implementation detail of a symbol parsing library. 

> @noahfalk is there a way to influence the automatic PDB loading which happens when generating stack traces for example?

The runtime looks for symbols in memory (as in embedded inside the assembly image or loaded by byte array at the time the assembly was loaded) and it looks for symbols adjacent to the binary on disk. I don't recall that the search policies look anywhere else nor any option for the app code to influence the search path.

**Comment by AraHaan** [comment] 2020-11-16 22:32
I do admit, I do load my plugins in a way that they do get loaded in the default context, I probably should not so that way if there are plugin updates they can be as simple as unloading that context for that plugin and then loading it in a new context instead of needing to restart the program,

How I do all of the plugin loading is actually from a wrapper library I made to cut down and so I can share it between all of my programs (using generic interfaces to load all dlls implementing said interface as plugins) So take for example ``IPlugin`` as the interface, then I do ``GenericPluginLoader<IPlugin>("the path to search for plugins", saveToZip: false, loadPDBFile: true)`` and then it does the hard work basically doing the loading of the plugins from a zip file or from disc, those projects for more details linked: [here](https://github.com/Elskom/GenericPluginLoader), and it's dependency [here](https://github.com/Elskom/ZipAssembly).

**Comment by vitek-karas** [comment] 2021-01-26 11:56
I must admit I'm still struggling to understand how force-loading PDBs helps anything. Mini dump creation should not rely on PDBs (otherwise it's fundamentally broken - since it needs to work in production scenarios where PDBs are almost never present). You also mention that you want to be able to force-load PDBs for native libraries - like `coreclr.dll`.  That's not a .NET thing - it would have to be a Windows API change to do that. But again, I don't see how doing so will help with anything.

Can you please describe in which case the code you already have to force-load PDBs (how does that work - you use the `LoadFromStream` APIs to do that?) helps with something around the mini dumps?

**Comment by AraHaan** [comment] 2021-01-26 12:29
Currently I force load pdbs based on the program's configuration settings then those settings get passed to the plugin loaders which then in turn loads the pdbs.
https://github.com/Elskom/Sdk/blob/main/GenericPluginLoader/GenericPluginLoader/GenericPluginLoader.cs

I also done where a setting where optionally it would pass in if they also want them loaded from a zip file as well (however with any failures (native dlls) then they get extracted to a temporary file and then loaded (https://github.com/Elskom/Sdk/blob/main/ZipAssembly/ZipAssembly/ZipAssembly.cs#L59-L165).

Then at the entrypoint of the program I basically apply this to the method / class https://github.com/Elskom/Sdk/blob/main/MiniDump/MiniDump/MiniDumpAttribute.cs#L35-L43 which then when there is any unhandled exceptions would trigger:
https://github.com/Elskom/Sdk/blob/main/MiniDump/MiniDump/MiniDump.cs#L26-L98 which then p/invokes into MiniDumpWriteDump here: https://github.com/Elskom/Sdk/blob/main/MiniDump/MiniDump/SafeNativeMethods.cs#L17-L28
using the input minidump type on the attribute.

Now there is a problem sometimes, it is that for some reason on some of the types [here](https://github.com/Elskom/Sdk/blob/main/MiniDump/MiniDump/MinidumpTypes.cs#L18-L145) it fails  on dump even with admin mode with error code 87 but that is not relevant here in this issue.

**Comment by vitek-karas** [comment] 2021-01-26 13:31
Sorry if I wasn't clear enough asking the main question: What is the reason to force-load the PDBs? What behavior do you see that requires this step? As far as we know mini dump generation should not be really affected by PDBs in any meaningful way.

**Comment by vitek-karas** [comment] 2021-01-26 13:33
As a side note: Loading all assemblies first into memory and then loading them from memory will have some negative effects:
* It's slower (more memory consumed, memory copy, ...)
* It won't work well on assemblies which were precompiled with Ready 2 Run (crossgen) - those will be loaded as pure IL and the precompiled code will be discarded.
* There are potential compatibility problems - some code relies on things like `Assembly.Location` which won't work the same. This is similar to the compat problem we're facing in .NET 5 with single-file deployments (those also load assemblies "as if from memory").

**Comment by AraHaan** [comment] 2021-01-26 22:09
I guess I could *have* made a mistake by adding the option to load pdbs instead of just forcing them to exist so that way when they are run in a debuger that they would get loaded I guess I *could* make the code only load them when such a debugger is attached.

Also I tried to overload the Location property to basically copy with how zipimport in python basically works in .NET with assemblies from a zip file.

**Comment by vitek-karas** [comment] 2021-01-27 14:51
It's up to your scenario if it requires PDBs to exist. I still don't see how is that relevant to minidump generation. Opening the minidump will definitely benefit from having PDBs for as much as possible, but that may happen on a different machine.

About the original concern of this issue - do you still think a new API is needed?

**Comment by AraHaan** [comment] 2021-01-27 20:52
Yes, I think a new api even if there needs to be done on Windows itself to add it would be helpful for debugging things like this as it would help with debugging minidumps (especially with pdbs with sourcelink so then you can see the embedded source code).

**Comment by noahfalk** [comment] 2021-01-28 02:11
For the scenario you are describing I think most developers handle it via PDB embedding. When you build the binary you specify <DebugType>Embedded</DebugType> and the pdb will be inserted inside the assembly. https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2019. After that point anywhere you have the assembly (in memory, in a dump, in the VS debugger) you will also have access to the PDB data. Does that sound like it would handle your case or you have a need to keep the assembly and PDB separate on disk?

**Comment by AraHaan** [comment] 2021-01-28 03:27
Well it's not always possible to embed them though, for starters what if you load something using reflection and that something is programmed using c++ with /clr:netcore for example? In that case how will the pdbs be embeded for those and for the vcruntime dlls that the compiled assembly would directly depend on (since you cannot static link the crt atm with c++ /clr:netcore, or at least have it to where if you only use .NET types that it would not require the crt dlls just to compile).

In that case it becomes a complicated mess of things.

**Comment by noahfalk** [comment] 2021-01-28 07:26
Apologies if this makes me the bearer of bad news - to the best of my knowledge assemblies with C++ and managed code are a rare case and not an area where the our team is prioritizing new improvements.

**Comment by vitek-karas** [comment] 2021-01-28 14:06
I'm sorry if I'm being slow - but I still don't understand what's the value of force loading the PDBs at runtime? Normally users want to ship applications without any PDBs, if it fails collect a dump and then debug the dump on a separate machine which has access to all the necessary PDBs (either by downloading them or by having access to the source).

If you want to force load PDBs it means they have to be present at runtime - so all code in your application would have to ship with PDBs next to it, or embedded. For managed code embedding PDBs is typically a good strategy for this. But for native code there's no such option, you would need to carry them as separate files. And that's for component you "own". For example .NET Core doesn't ship PDBs with the runtime (for size reasons), you would have to download those separately and somehow "pair" them up at runtime. Debuggers have logic to do this and more (like download them from symbol servers and so on), but runtime typically doesn't.

I would really like to understand what's the scenario which you're trying to solve for which you think force-loading PDBs is the right solution... and again sorry, if I'm just being slow to understand this.

**Comment by AraHaan** [comment] 2021-01-28 16:52
Force loading pdbs is good when you load assemblies implementing a specific interface using reflection and let’s say one of those assemblies cause a crash, withthe pdbs it will tell you the file and line of said issue (if crash was related to an exception).
A real issue is that even with c# dlls if referenced directly can be used even in c++ which then opens an even bigger can of worms because then I would want to force load those pdbs to dlls using c++ with CoreCLR as a target and then also manage to load the pdbs to the crt that those asseblies loaded using reflection might depend on.

**Comment by vitek-karas** [comment] 2021-01-28 21:16
Thanks - the desire for detailed stack traces makes sense. I'm not sure if the solution to that should be force-loading PDBs, or just a way to help the runtime find the PDB on disk though. On the other hand as you mention, if native code is involved there's very little which CoreCLR can do - the stack traces as viewed from managed will not contain native code. And even debugger like code which might be able to provide those will need the native PDBs to work reliably. I'm not aware of a way to tell Windows (or the other OSes) to associate a PDB with loaded module.

**Closed** 2021-07-09 14:00 UTC
Labels: api-suggestion, area-AssemblyLoader-coreclr, needs more info, untriaged
