### ISSUE TITLE
[API Proposal]: Add Enumerable.WhereNotNull to System.Linq

### ISSUE THREAD

**Issue by sandervanteinde** [dotnet/runtime#85054] opened 2023-04-19 17:40 UTC
### Background and motivation

When we are writing code in the nullable context, we might encounter collections like `IEnumerable<Type?>` where `Type` is a class.

When we are writing Linq statements on this collection and filtering these by doing a not null check, we still get an `IEnumerable<Type?>` as a result while we have checked whether it's a null reference or not.

A framework like Entity Framework could also benefit from this, because it could distinguish a `.Where` from a `.WhereNotNull` invocation.

### API Proposal

```csharp
namespace System.Linq;

namespace System.Linq
{
    public static partial class Enumerable
    {
        public static IEnumerable<T> WhereNotNull(this IEnumerable<T?> source)
            where T : class
        {
            // implementation for reference types
        }

        public static IEnumerable<T> WhereNotNull(this IEnumerable<T?> source)
            where T : struct
        {
            // implementation for struct types          
        }
    }
}
```

### API Usage

```csharp
var listOfIntegers = new List<int?>
{
    1,
    null,
    2
};

var result = listOfIntegers.WhereNotNull(); // results in [1, 2]

var listOfObjects = new List<object>
{
    new object(),
    null,
    new object()
}
var result2 = listOfObjects.WhereNotNull(); // results in [object, object]
```

### Alternative Designs

Preferably it would be 1 extension method, however I do not see a possibility to handle both nullable structs and reference types in one signature

### Risks

As it is a new API, I do not see any risk other than that it might add some confusion as to what to use. But I believe the signature of the proposal is clear enough to any developer.

**Comment by eiriktsarpalis** [comment] 2023-04-19 17:51
Duplicate of https://github.com/dotnet/runtime/issues/30381 and https://github.com/dotnet/runtime/issues/41363. We feel that this should be solved at the compiler level rather than adding yet another linq method.

**Closed by eiriktsarpalis** 2023-04-19 17:51 UTC
Labels: api-suggestion, area-System.Linq, untriaged
