### ISSUE TITLE
Required Members doesn't work on .NET 6.0

### ISSUE THREAD

**Issue by KUTlime** [dotnet/runtime#80346] opened 2023-01-08 16:24 UTC
### Description

The [required members](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-11.0/required-members) feature does not work on .NET 6.

The feature is misinterpreted as a language feature, but it is dependent on the target framework. There is no documentation about it.

.NET 6 is missing `System.Runtime.CompilerServices.RequiredMemberAttribute` & `System.Runtime.CompilerServices.CompilerFeatureRequiredAttribute`.

![image](https://user-images.githubusercontent.com/8374320/211207529-51dbb842-f7b7-4534-8ebc-0c7d2bcc7ae6.png)

### Reproduction Steps

Create a console application with this code:

```csharp
Console.WriteLine("Hello, World!");

class User
{
    public required string Name { get; set; }
}
```

and this CSProj settings

```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

</Project>
```

### Expected behavior

The project would compile as usually.

### Actual behavior

The project won't compile due to missing RequiredMemberAttribute & CompilerFeatureRequiredAttribute errors.

### Regression?

It works on `<TargetFramework>net6.0</TargetFramework>`

### Known Workarounds

Use .NET 7.

### Configuration

6.0.404 - does not work
7.0.101 - does work
Windows 11
x64

### Other information

It is kinda obvious where the problem is. The feature should either be backported to .NET 6, or the documentation should explicitly set that the feature is **framework dependent**.

**Comment by MichalPetryka** [comment] 2023-01-08 17:23
Running C#11 with frameworks older than .Net 7 is not officially supported, as such the documentation does not describe such usecases.

**Comment by teo-tsirpanis** [comment] 2023-01-08 18:05
Closing as by design. You can use https://github.com/Sergio0694/PolySharp/ to automatically generate the missing attributes.

**Closed by teo-tsirpanis** 2023-01-08 18:05 UTC
Labels: untriaged

**Comment by KUTlime** [comment] 2023-01-08 20:07
> Running C#11 with frameworks older than .Net 7 is not officially supported

Could you give me some link where this is officially stated?

**Comment by teo-tsirpanis** [comment] 2023-01-08 20:09
[Here.](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version#override-a-default:~:text=C%23%2011%20is%20supported%20only%20on%20.NET%207%20and%20newer%20versions.%20C%23%2010%20is%20supported%20only%20on%20.NET%206%20and%20newer%20versions.%20C%23%209%20is%20supported%20only%20on%20.NET%205%20and%20newer%20versions.)

**Comment by KUTlime** [comment] 2023-01-08 20:14
@teo-tsirpanis I'm asking about where it is written _C# 11 with frameworks older than .NET 7 is not officially supported_, not how to override the default. If you look on my bug report, it is clear that I did override the default.

**Comment by teo-tsirpanis** [comment] 2023-01-08 20:15
In the second paragraph:

> C# 11 is supported only on .NET 7 and newer versions. C# 10 is supported only on .NET 6 and newer versions. C# 9 is supported only on .NET 5 and newer versions.

**Comment by KUTlime** [comment] 2023-01-08 20:19
Oh, I see. The link above was pointing to a sub chapter.
