### ISSUE TITLE
ILC crash in CI - NullReferenceException in XPath while processing substitution XML

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#108743] opened 2024-10-10 08:28 UTC
Occurred in https://dev.azure.com/dnceng-public/public/_build/results?buildId=836362&view=results - windows-x64 Checked NativeAOT

```
     ---> ILCompiler.CodeGenerationFailedException: Code generation failed for method '[S.P.Reflection.Execution]Internal.Runtime.CompilerHelpers.LibraryInitializer.InitializeLibrary()'
     ---> ILCompiler.NativeAotFatalErrorException: ILC: error IL1013: Error processing 'name'.
     ---> System.NullReferenceException: Object reference not set to an instance of an object.
       at System.Xml.XPath.XNodeNavigator.MoveToFirstChild() + 0x22
       at MS.Internal.Xml.XPath.XPathChildIterator.MoveNext() + 0x19
       at System.Xml.XPath.XPathNodeIterator.Enumerator.MoveNext() + 0xd6
       at ILCompiler.ProcessLinkerXmlBase.ProcessAssemblies(XPathNavigator) + 0x157
       at ILCompiler.ProcessLinkerXmlBase.ProcessXml(Boolean) + 0xfa
       --- End of inner exception stack trace ---
       at ILCompiler.ProcessLinkerXmlBase.ProcessXml(Boolean) + 0x1d9
       at ILCompiler.SubstitutionProvider.AssemblyFeatureInfo..ctor(EcmaModule, Logger, IReadOnlyDictionary`2, BodyAndFieldSubstitutions) + 0x1ce
       at ILCompiler.SubstitutionProvider.FeatureSwitchHashtable.CreateValueFromKey(EcmaModule) + 0x4e
       at Internal.TypeSystem.LockFreeReaderHashtable`2.CreateValueAndEnsureValueIsInTable(TKey) + 0x18
       at ILCompiler.SubstitutionProvider.GetSubstitution(MethodDesc) + 0x77
       at ILCompiler.SubstitutedILProvider.GetMethodIL(MethodDesc) + 0x1b
```

**Comment by jkotas** [comment] 2024-10-10 09:36
Duplicate of #108031. It should get fixed by updating the LKG toolset to .NET 9 RC2 any day now.

**Comment by agocke** [comment] 2024-10-14 20:20
Closing as duplicate

**Closed by agocke** 2024-10-14 20:20 UTC
Labels: untriaged, area-NativeAOT-coreclr
