### ISSUE TITLE
JsonSerializer does not populate a property value if used as typeDescriminator

### ISSUE THREAD

**Issue by ryan-morris** [dotnet/runtime#94949] opened 2023-11-18 04:41 UTC
### Description

When using the `JsonPolymorphic` attribute, a property with the same `JsonPropertyName` never has it's value set.

### Reproduction Steps

This code results in an exception because the `Type` value is never set.

```c#
    internal class Program
    {
        static void Main(string[] args)
        {
            var json = """{ "type": "sample_a", "id": 1, "details": "sample_a_details" }""";
            var result = JsonSerializer.Deserialize<SampleEvent>(json);
        }
    }

    [JsonPolymorphic(TypeDiscriminatorPropertyName = "type", UnknownDerivedTypeHandling = JsonUnknownDerivedTypeHandling.FallBackToBaseType)]
    [JsonDerivedType(typeof(EventA), typeDiscriminator: "sample_a")]
    [JsonDerivedType(typeof(EventB), typeDiscriminator: "sample_b")]
    public class SampleEvent
    {
        [JsonPropertyName("type")]
        public required string Type { get; init; }

        [JsonPropertyName("id")]
        public required int Id { get; init; }
    }

    public class EventA : SampleEvent
    {
        [JsonPropertyName("details")]
        public required string Details { get; init; }
    }

    public class EventB : SampleEvent
    {
        [JsonPropertyName("details")]
        public required int Details { get; init; }
    }
```

Exception:

```
System.Text.Json.JsonException: 'JSON deserialization for type 'BenchmarkJsonSerialization.EventA' was missing required properties, including the following: type'
```

### Expected behavior

A property value should be set even if it doubles as a typeDescriminator

### Actual behavior

Either the value will be null, or an exception will occur if the property is marked as `required`

### Known Workarounds

Use a custom JsonConverter, or make the field nullable and set the value after deserialization.

**Comment by eiriktsarpalis** [comment] 2023-11-18 12:26
Duplicate of https://github.com/dotnet/runtime/issues/72170#issuecomment-1439773918. It's not a supported scenario for the built-in serializer. I would recommend using a custom converter instead.

**Closed by eiriktsarpalis** 2023-11-18 12:26 UTC
Labels: area-System.Text.Json, untriaged
