### ISSUE TITLE
error CS0121 when trying to publish outside of Visual Studio (building in VS works fine)

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#100727] opened 2024-04-06 13:38 UTC
### Description

The following line throws an exception when I try to publish via terminal, works fine when I build (not publish) in VS

`var parts = s.Split(['+', '-'], StringSplitOptions.RemoveEmptyEntries);` throws with `error CS0121: The call does not clearly distinguish between the following methods or properties: "string.Split(char[]?, StringSplitOptions)" and "string.Split(string?, StringSplitOptions)"`

I publish it with `dotnet publish abc.csproj -c Release -v q --self-contained -r win-x64`. This is a .NET 8 WPF application

### Reproduction Steps

`var parts = s.Split(['+', '-'], StringSplitOptions.RemoveEmptyEntries);`

### Expected behavior

Publish succeeds

### Actual behavior

Publish fails

### Configuration

Host:
  Version:      8.0.2
  Architecture: x64
  Commit:       1381d5ebd2

.NET SDKs installed:
  6.0.100-preview.5.21302.13 [C:\Program Files\dotnet\sdk]
  6.0.128 [C:\Program Files\dotnet\sdk]
  8.0.200 [C:\Program Files\dotnet\sdk]

**Comment by stephentoub** [comment] 2024-04-06 14:23
Duplicate of https://github.com/dotnet/roslyn/issues/70831

**Closed by stephentoub** 2024-04-06 14:23 UTC
Labels: needs-area-label
