### ISSUE TITLE
Blazor Wasm dotnet 8 preview 6 doesn't work on chrome android phone

### ISSUE THREAD

**Issue by sake402** [dotnet/runtime#89028] opened 2023-07-15 20:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When running even the default blazorwasm template, it work on desktop browser, but when accessed from a chrome brwoser on android, error

### Steps To Reproduce

Create a default project, dont edit anything
``dotnet new blazorwasm``

Run it
``dotnet run``

Open in desktop browser, everything is fine
``https://localhost:5001``

Ngrok to the same pc
``ngrok http localhost:5001``

Access ngrok url from same desktop, everything works fine
``https://5fb8-41-217-56-136.ngrok-free.app/``

Access the same ngrok url from chrom on android, doesnt work
``https://5fb8-41-217-56-136.ngrok-free.app/``

```
blazor.webassembly.js:1  instantiate_wasm_module() failed: {}
Et @ blazor.webassembly.js:1
blazor.webassembly.js:1  Stacktrace: 

Et @ blazor.webassembly.js:1
blazor.webassembly.js:1  CompileError: WebAssembly.instantiateStreaming(): Compiling function dotnet/aspnetcore#112:"mono_wasm_load_runtime" failed: Invalid opcode 0xfd (enable with --experimental-wasm-simd) @+32189
Et @ blazor.webassembly.js:1
2dotnet.js:3  CompileError: WebAssembly.instantiateStreaming(): Compiling function dotnet/aspnetcore#112:"mono_wasm_load_runtime" failed: Invalid opcode 0xfd (enable with --experimental-wasm-simd) @+32189
U @ dotnet.js:3
dotnet.js:3  Error in mono_download_assets: CompileError: WebAssembly.instantiateStreaming(): Compiling function dotnet/aspnetcore#112:"mono_wasm_load_runtime" failed: Invalid opcode 0xfd (enable with --experimental-wasm-simd) @+32189
(anonymous) @ dotnet.js:3
dotnet.js:3  CompileError: WebAssembly.instantiateStreaming(): Compiling function dotnet/aspnetcore#112:"mono_wasm_load_runtime" failed: Invalid opcode 0xfd (enable with --experimental-wasm-simd) @+32189
U @ dotnet.js:3
blazor.webassembly.js:1  Error: Failed to start platform. Reason: CompileError: WebAssembly.instantiateStreaming(): Compiling function dotnet/aspnetcore#112:"mono_wasm_load_runtime" failed: Invalid opcode 0xfd (enable with --experimental-wasm-simd) @+32189
    at zt (blazor.webassembly.js:1:54482)
    at async Gt (blazor.webassembly.js:1:56202)
(anonymous) @ blazor.webassembly.js:1
4dotnet.js:3  Uncaught (in promise) CompileError: WebAssembly.instantiateStreaming(): Compiling function dotnet/aspnetcore#112:"mono_wasm_load_runtime" failed: Invalid opcode 0xfd (enable with --experimental-wasm-simd) @+32189
dotnet.runtime.8.0.0-preview.6.23329.7.uvxzzeohdi.js:3  Uncaught (in promise) CompileError: WebAssembly.instantiateStreaming(): Compiling function dotnet/aspnetcore#112:"mono_wasm_load_runtime" failed: Invalid opcode 0xfd (enable with --experimental-wasm-simd) @+32189
25fb8-41-217-56-136.ngrok-free.app/:1  Uncaught (in promise) CompileError: WebAssembly.instantiateStreaming(): Compiling function dotnet/aspnetcore#112:"mono_wasm_load_runtime" failed: Invalid opcode 0xfd (enable with --experimental-wasm-simd) @+32189
```

![image](https://github.com/dotnet/aspnetcore/assets/20999608/ec893efc-d930-4ec8-9e41-b1f7c2461515)

### .NET Version

8.0.100-preview.6.23330.14

**Comment by hankovich** [comment] 2023-07-17 17:44
Facing the same issue on Safari on macOS 12.1 and macOS 12.5.1. Setting `<WasmEnableSIMD>false</WasmEnableSIMD>` doesn't work

![image](https://github.com/dotnet/runtime/assets/22914850/00575c42-a2f2-454d-adf2-d247714db31d)

---

Possible duplicate: #83161

**Comment by radical** [comment] 2023-07-17 18:13
cc @pavelsavara @maraf @kg

**Comment by kg** [comment] 2023-07-17 21:59
For various reasons it's not straightforward to detect whether SIMD is available on your device and handle it being unavailable. Chrome and Firefox have had WASM SIMD support for a very long time now, and Safari has had it for a few releases as well. That's why we made the decision to turn it on. Support should be even wider by the time the final 8.0 release comes out.

If there are specific scenarios where you are unable to update your devices or need to use an old browser, can you explain them to us? We have time to evaluate whether we need to change our plans on this, but we'd need data to be able to make an informed decision on whether we need to roll back SIMD support before 8.0's release.

Thanks for reporting the issue, please keep us informed if you have more details to share or if you encounter any new SIMD-related problems.

**Comment by lewing** [comment] 2023-07-18 00:35
What versions of safari are installed on the macOS/iOS machines that are failing?  Safari >= 16.4 should work and that is current on macOS 12.x.

Chrome has supported the vector extensions for even longer, what version is failing for you?

**Comment by lewing** [comment] 2023-07-18 00:40
The current default settings require Exception Handling and Fixed Width SIMD, the version matrix is here https://webassembly.org/roadmap/ for the major browsers

**Comment by lanedirt** [comment] 2023-07-18 08:42
Firstly, I appreciate the hard work you're doing on this project!

I encountered the error I posted above while trying to access the application on iOS 16.3.1, utilizing both the built-in Safari browser and Google Chrome version 114.0.5735.1254.

To provide you with a bit more context, I have been running a .NET 7.0 WebAssembly application in production since February. The application is publicly accessible and is used across a variety of devices, which, understandably, are not within my control. Interestingly, my analytics data suggest that many of my visitors are still using older iOS devices and browser versions - there's a significant number of iOS 15.x devices, with some using iOS 13 and 14 as well.

So far, the application has been functioning smoothly on these devices with .NET 7.0. However, I'm concerned that the WASM SIMD requirement in .NET 8.0 may render the application inaccessible for those using older iOS versions.

Would it be possible to make the SIMD requirement configurable? So we would have the flexibility to decide whether we wish to require SIMD in our .NET 8.0 applications or instead fallback to the previous approach employed in .NET 7.0.

**Update:** I wanted to add that after updating my iPhone to the latest available version, iOS 16.5.1, I was able to use the WASM components without any issues on both browsers. However, as I noted earlier, there's a significant proportion of users still operating on older iOS versions, and unfortunately, their update cycles aren't something we can control.

I hope this feedback is helpful and I look forward to your thoughts.

**Comment by sake402** [comment] 2023-07-18 10:44
So far I can confirm now that this issue is related to old version of chrome being used.
Perhaps blazorwasm can detect this non-simd support or even browser version and prompt the user/developer to update their browser.

Having updated chrome to latest though we have another chrome android runtime error, with AOT publish

![image](https://github.com/dotnet/runtime/assets/20999608/2c1284e7-5c57-4614-bda2-4838c78b314c)

**Comment by hankovich** [comment] 2023-07-18 13:01
I can't force customers to update their browsers, I don't know the reason for using outdaed versions.

@kg Could you please explain how to disable SIMD at all for Blazor? `<WasmEnableSIMD>false</WasmEnableSIMD>` doesn't work

**Comment by tn-5** [comment] 2023-07-19 04:41
It does not only affect users with older browsers. It also affects users with the latest browsers running on very old hardware where the CPU does not support SIMD. In our Blazor line of business app we have several thousand users of which a couple of hundred are affected by this. For now we had to revert to the server side version for them but obviously it is not feasible in the long run to do this. We either need:
* A way to completely disable SIMD in our builds; or
* To dynamically detect SIMD support properly and to not use SIMD in those cases

**Comment by maraf** [comment] 2023-07-19 08:28
@hankovich A second property `WasmBuildNative` needs to be set to `true`, it triggers rebuild of native code. It happens automatically when you publish the app.

@tn-5 You probably can publish your app twice and than use [loadBootResource](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/startup?view=aspnetcore-7.0#load-boot-resources) in combination with SIMD detection mentioned here https://github.com/dotnet/runtime/issues/84574#issuecomment-1634603894 you can choose between published versions

**Comment by tn-5** [comment] 2023-07-19 12:25
Many different settings have  been mentioned, none seem to have any effect. The question is, is it possible with net8 preview 6 to publish a Blazor Webassembly app with SIMD disabled completely? If so, how?

**Comment by maraf** [comment] 2023-07-19 15:58
```xml
<WasmEnableSIMD>false</WasmEnableSIMD>
<WasmBuildNative>true</WasmBuildNative>
```

- The `WasmBuildNative=true` forces recompilation of `dotnet.native.wasm` (without SIMD)
- The `WasmEnableSIMD=false` disables SIMD

**Comment by tn-5** [comment] 2023-07-20 15:03
@maraf Those settings may have some effect, but there is some other simd related change that means even with those settings the app crashes on loading on a platform where simd is not supported. 

The error changes from a relatively clear (with SIMD enabled):
```
Error: Failed to start platform. Reason: CompileError: wasm validation error: at offset 50472: unrecognized opcode: fd c
```

to something like the following (with above settings to attempt to disable SIMD):
```
instantiate_wasm_module() failed: {}
...
Error in mono_download_assets: CompileError: wasm validation error: at offset 10956: unknown section before code section
```


Another interesting thing is that with those settings on an IIS publish a `dotnet.native.wasm` file appears in the root folder (in the folder where the `web.config` is deployed.

**Comment by maraf** [comment] 2023-07-21 08:05
@tn-5 It could be second feature enabled by default in .NET 8 and that is exception handling. Can you try adding this one as well?

```xml
<WasmEnableExceptionHandling>false</WasmEnableExceptionHandling>
```

> Another interesting thing is that with those settings on an IIS publish a dotnet.native.wasm file appears in the root folder (in the folder where the web.config is deployed.

This one was fixed in https://github.com/dotnet/runtime/pull/89079

**Comment by tn-5** [comment] 2023-07-21 09:35
Tried with various settings. Following on preview 6:
```
	<WasmEnableExceptionHandling>False</WasmEnableExceptionHandling>
	<WasmEnableSIMD>False</WasmEnableSIMD>
	<WasmBuildNative>True</WasmBuildNative>
```

Fails on Firefox v88 (last one without SIMD support)
Passes on Firefox v89 (first one to support SIMD)

From what it seems there is no way to run or publish any webassembly application without using SIMD.

**Comment by maraf** [comment] 2023-07-21 11:20
@radekdoulik Verified with FF v88 on both blazor and wasmbrowser templates. After setting

```
<WasmEnableSIMD>false</WasmEnableSIMD>
<WasmEnableExceptionHandling>false</WasmEnableExceptionHandling>
<WasmBuildNative>true</WasmBuildNative>
```

- wasm-opt is run with `--enable-simd`
- `emcc-default.rsp` contains `-msimd128`

**Comment by kg** [comment] 2023-07-21 12:37
I'm not sure why wasm-opt is getting that option - it looks conditional in the msbuild to me - but the msimd128 is non-conditional in the CMakeLists, which is probably my fault, iirc. wasm-opt getting that switch makes me wonder whether WasmEnableSIMD is not flowing through.

**Comment by radekdoulik** [comment] 2023-07-21 13:18
I looked into it and opened https://github.com/dotnet/runtime/issues/89302 to describe what to fix.

**Comment by alexandrereyes** [comment] 2023-11-29 14:42
Guys, the option `<WasmEnableSIMD>false</WasmEnableSIMD>` doesn't work when build using Docker.

The error:
```
docker build --no-cache -f "Abacato.Blazor.WebAssembly.Host/Dockerfile" -t abacatoblazorwebassemblyhost .
[+] Building 36.9s (18/18) FINISHED                                                                                                                docker:default
 => [internal] load .dockerignore                                                                                                                            0.0s
 => => transferring context: 382B                                                                                                                            0.0s
 => [internal] load build definition from Dockerfile                                                                                                         0.0s
 => => transferring dockerfile: 1.44kB                                                                                                                       0.0s
 => [internal] load metadata for mcr.microsoft.com/dotnet/sdk:8.0                                                                                            0.0s
 => [build  1/14] FROM mcr.microsoft.com/dotnet/sdk:8.0                                                                                                      0.0s
 => [internal] load build context                                                                                                                            0.1s
 => => transferring context: 152.74kB                                                                                                                        0.1s
 => CACHED [build  2/14] WORKDIR /src                                                                                                                        0.0s
 => [build  3/14] COPY [Abacato.Blazor.WebAssembly.Host/Abacato.Blazor.WebAssembly.Host.csproj, Abacato.Blazor.WebAssembly.Host/]                            0.0s
 => [build  4/14] COPY [Abacato.Blazor.WebAssembly/Abacato.Blazor.WebAssembly.csproj, Abacato.Blazor.WebAssembly/]                                           0.0s
 => [build  5/14] COPY [Abacato.Blazor/Abacato.Blazor.csproj, Abacato.Blazor/]                                                                               0.0s
 => [build  6/14] COPY [Abacato.Common/Abacato.Common.csproj, Abacato.Common/]                                                                               0.0s
 => [build  7/14] COPY [Util/Util.csproj, Util/]                                                                                                             0.0s
 => [build  8/14] COPY [Util.AspNet/Util.AspNet.csproj, Util.AspNet/]                                                                                        0.0s
 => [build  9/14] COPY [Util.Blazor/Util.Blazor.csproj, Util.Blazor/]                                                                                        0.0s
 => [build 10/14] RUN dotnet workload restore "Abacato.Blazor.WebAssembly.Host/Abacato.Blazor.WebAssembly.Host.csproj"                                      20.3s
 => [build 11/14] RUN dotnet restore "Abacato.Blazor.WebAssembly.Host/Abacato.Blazor.WebAssembly.Host.csproj"                                                6.7s
 => [build 12/14] COPY . .                                                                                                                                   0.2s
 => [build 13/14] WORKDIR /src/Abacato.Blazor.WebAssembly.Host                                                                                               0.0s
 => ERROR [build 14/14] RUN dotnet build "Abacato.Blazor.WebAssembly.Host.csproj" -c Release -o /app/build                                                   9.3s
------
 > [build 14/14] RUN dotnet build "Abacato.Blazor.WebAssembly.Host.csproj" -c Release -o /app/build:
0.531 MSBuild version 17.8.3+195e7f5a3 for .NET
0.809   Determining projects to restore...
1.743   All projects are up-to-date for restore.
3.520   Util.AspNet -> /app/build/Util.AspNet.dll
3.536   Util -> /app/build/Util.dll
4.014   Util.Blazor -> /app/build/Util.Blazor.dll
4.157   Abacato.Common -> /app/build/Abacato.Common.dll
6.438   Abacato.Blazor -> /app/build/Abacato.Blazor.dll
9.226   Compiling native assets with emcc with -Oz. This may take a while ...
9.236 /usr/share/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/8.0.0/Sdk/WasmApp.Native.targets(366,5): error : Failed to compile /usr/share/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.browser-wasm/8.0.0/runtimes/browser-wasm/native/src/pinvoke.c -> /src/Abacato.Blazor.WebAssembly/obj/Release/net8.0/wasm/for-build/pinvoke.o [/src/Abacato.Blazor.WebAssembly/Abacato.Blazor.WebAssembly.csproj]
9.236 /usr/share/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/8.0.0/Sdk/WasmApp.Native.targets(366,5): error : unable to find python in $PATH [took 0.00s] [/src/Abacato.Blazor.WebAssembly/Abacato.Blazor.WebAssembly.csproj]
9.236 /usr/share/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/8.0.0/Sdk/WasmApp.Native.targets(366,5): error : Failed to compile /usr/share/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.browser-wasm/8.0.0/runtimes/browser-wasm/native/src/driver.c -> /src/Abacato.Blazor.WebAssembly/obj/Release/net8.0/wasm/for-build/driver.o [/src/Abacato.Blazor.WebAssembly/Abacato.Blazor.WebAssembly.csproj]
9.236 /usr/share/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/8.0.0/Sdk/WasmApp.Native.targets(366,5): error : unable to find python in $PATH [took 0.00s] [/src/Abacato.Blazor.WebAssembly/Abacato.Blazor.WebAssembly.csproj]
9.236 /usr/share/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/8.0.0/Sdk/WasmApp.Native.targets(366,5): error : Failed to compile /usr/share/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.browser-wasm/8.0.0/runtimes/browser-wasm/native/src/corebindings.c -> /src/Abacato.Blazor.WebAssembly/obj/Release/net8.0/wasm/for-build/corebindings.o [/src/Abacato.Blazor.WebAssembly/Abacato.Blazor.WebAssembly.csproj]
9.236 /usr/share/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/8.0.0/Sdk/WasmApp.Native.targets(366,5): error : unable to find python in $PATH [took 0.00s] [/src/Abacato.Blazor.WebAssembly/Abacato.Blazor.WebAssembly.csproj]
9.245
9.246 Build FAILED.
9.246
9.246 /usr/share/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/8.0.0/Sdk/WasmApp.Native.targets(366,5): error : Failed to compile /usr/share/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.browser-wasm/8.0.0/runtimes/browser-wasm/native/src/pinvoke.c -> /src/Abacato.Blazor.WebAssembly/obj/Release/net8.0/wasm/for-build/pinvoke.o [/src/Abacato.Blazor.WebAssembly/Abacato.Blazor.WebAssembly.csproj]
9.246 /usr/share/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/8.0.0/Sdk/WasmApp.Native.targets(366,5): error : unable to find python in $PATH [took 0.00s] [/src/Abacato.Blazor.WebAssembly/Abacato.Blazor.WebAssembly.csproj]
9.246 /usr/share/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/8.0.0/Sdk/WasmApp.Native.targets(366,5): error : Failed to compile /usr/share/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.browser-wasm/8.0.0/runtimes/browser-wasm/native/src/driver.c -> /src/Abacato.Blazor.WebAssembly/obj/Release/net8.0/wasm/for-build/driver.o [/src/Abacato.Blazor.WebAssembly/Abacato.Blazor.WebAssembly.csproj]
9.246 /usr/share/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/8.0.0/Sdk/WasmApp.Native.targets(366,5): error : unable to find python in $PATH [took 0.00s] [/src/Abacato.Blazor.WebAssembly/Abacato.Blazor.WebAssembly.csproj]
9.246 /usr/share/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/8.0.0/Sdk/WasmApp.Native.targets(366,5): error : Failed to compile /usr/share/dotnet/packs/Microsoft.NETCore.App.Runtime.Mono.browser-wasm/8.0.0/runtimes/browser-wasm/native/src/corebindings.c -> /src/Abacato.Blazor.WebAssembly/obj/Release/net8.0/wasm/for-build/corebindings.o [/src/Abacato.Blazor.WebAssembly/Abacato.Blazor.WebAssembly.csproj]
9.246 /usr/share/dotnet/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/8.0.0/Sdk/WasmApp.Native.targets(366,5): error : unable to find python in $PATH [took 0.00s] [/src/Abacato.Blazor.WebAssembly/Abacato.Blazor.WebAssembly.csproj]
9.246     0 Warning(s)
9.246     3 Error(s)
9.247
9.247 Time Elapsed 00:00:08.62
------
Dockerfile:21
--------------------
  19 |     COPY . .
  20 |     WORKDIR "/src/Abacato.Blazor.WebAssembly.Host"
  21 | >>> RUN dotnet build "Abacato.Blazor.WebAssembly.Host.csproj" -c Release -o /app/build
  22 |     #
  23 |     #FROM build AS publish
--------------------
ERROR: failed to solve: process "/bin/sh -c dotnet build \"Abacato.Blazor.WebAssembly.Host.csproj\" -c Release -o /app/build" did not complete successfully: exit code: 1
```

Here is the Dockerfile of the blazor wasm project:
```
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["Abacato.Blazor.WebAssembly.Host/Abacato.Blazor.WebAssembly.Host.csproj", "Abacato.Blazor.WebAssembly.Host/"]
COPY ["Abacato.Blazor.WebAssembly/Abacato.Blazor.WebAssembly.csproj", "Abacato.Blazor.WebAssembly/"]
COPY ["Abacato.Blazor/Abacato.Blazor.csproj", "Abacato.Blazor/"]
COPY ["Abacato.Common/Abacato.Common.csproj", "Abacato.Common/"]
COPY ["Util/Util.csproj", "Util/"]
COPY ["Util.AspNet/Util.AspNet.csproj", "Util.AspNet/"]
COPY ["Util.Blazor/Util.Blazor.csproj", "Util.Blazor/"]
RUN dotnet workload restore "Abacato.Blazor.WebAssembly/Abacato.Blazor.WebAssembly.csproj"
RUN dotnet restore "Abacato.Blazor.WebAssembly.Host/Abacato.Blazor.WebAssembly.Host.csproj"
COPY . .
WORKDIR "/src/Abacato.Blazor.WebAssembly.Host"
RUN dotnet build "Abacato.Blazor.WebAssembly.Host.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Abacato.Blazor.WebAssembly.Host.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Abacato.Blazor.WebAssembly.Host.dll"]
```

This is very easy to reproduce, just create a blazor wasm standalone project, add a dockerfile and try to build the image.

I'm stuck on dotnet 7 because of this, any help?

**Comment by c4l3b** [comment] 2023-12-21 02:10
@alexandrereyes I've experienced the same issue and found that you just need to install a couple packages before the build.

I use the ubuntu flavored images, but I added the line:
`RUN apt-get update -y && apt-get install python3 libatomic1 -y && dotnet workload install wasm-tools` to the build stage. 

Working like a champ again.

**Comment by paulguz-datapa** [comment] 2024-01-09 11:47
How much of a performance hit would be experience by disabling SIMD?

**Comment by LostBeard** [comment] 2024-02-07 17:02
@paulguz-datapa 
I have created demonstration projects showing how to build Blazor WASM apps with both SIMD enabled and disabled. And then loading the appropriate build at runtime based on the environment.

Blazor Web App SIMD Detect Example  
[BlazorWebAppSIMDDetectExample](https://github.com/LostBeard/BlazorWebAppSIMDDetectExample)

Blazor WebAssembly Standalone SIMD Detect Example
[BlazorWASMSIMDDetectExample](https://github.com/LostBeard/BlazorWASMSIMDDetectExample)

**Comment by lewing** [comment] 2024-02-09 05:47
I believe this is fixed in .NET 8+ please open a new issue with specific versions if you are still experiencing the issue with the most recent version.

**Closed by lewing** 2024-02-09 05:47 UTC
Labels: arch-wasm, area-VM-meta-mono

**Comment by LostBeard** [comment] 2024-02-09 11:54
@lewing This is not "fixed" in any sense of the word. 

A default build of a .Net 8 Blazor WASM app has SIMD enabled and will fail on any device that does not support SIMD, either by the device or the browser.

Output from a Blazor WASM 8.0.1 standalone app in a current version of Chrome running on one of my test devices lacking SIMD support.
```
Uncaught (in promise) Error: Assert failed: This browser/engine doesn't support WASM SIMD. Please use a modern version. See also https://aka.ms/dotnet-wasm-features
```

My comment gives info on how to test and workaround this so that you can have SIMD enabled on devices that support it and not enabled on devices that don't.
