### ISSUE TITLE
Uri gives surprising result when given a relativeUri that looks absolute

### ISSUE THREAD

**Issue by jez9999** [dotnet/runtime#74869] opened 2022-08-31 13:19 UTC
### Description

When the `Uri` class is instantiated, there are two constructors allowing a relative URI to be joined to a base URI:

```c#
        public Uri(Uri baseUri, string? relativeUri);
        public Uri(Uri baseUri, Uri relativeUri);
```

In both cases, when the `relativeUri` "looks like" an absolute URI, the `baseUri` is discarded and only the `relativeUri` is used.

### Reproduction Steps

For first constructor:

```c#
var resultUri = new Uri(
    new Uri("http://localhost:3000/"),
    "//hello/world"); // Gives Uri: http://hello/world
```

For second constructor:

```c#
var relativeUri = new Uri("//hello/world", UriKind.Relative);
var resultUri = new Uri(
    new Uri("http://localhost:3000/"),
    relativeUri); // Gives Uri: http://hello/world
```

### Expected behavior

As this is intended to take 2 params, one a "relative URI", the "relative URI" param should *always* be considered relative, no matter how it looks.  The base path should not be discarded, and the resulting URI should be `http://localhost:3000//foo/bar`.

This behaviour is even more surprising/incorrect for the second constructor example, where the relative URI has been *explicitly* initialized with `UriKind.Relative`, which should be telling the `Uri` class that this is a relative URI no matter how it "looks".  If one wants to join the following two requests together, for example:

```
http://localhost:3000/
http://localhost:51515//foo/bar
```

Using the path from the second, `Uri` will not allow it.  The second is a legal path, and `Uri` should be able to treat it as a legal relative path beginning with 2 slashes.

### Actual behavior

The `Uri` class always treats "relative URIs" that "look absolute" as absolute.

### Other information

I would suggest two fixes.  For the constructor `public Uri(Uri baseUri, string? relativeUri);`, either `relativeUri` should always be considered relative, or an overload should be added with a `bool` allowing it to be always treated as relative.

For the constructor `public Uri(Uri baseUri, Uri relativeUri);`, the `relativeUri` property `IsAbsoluteUri` should be checked.  If it's false, this `Uri` should *always* be treated as relative and its path added to the base URI.

**Comment by svick** [comment] 2022-08-31 13:59
As far as I can tell, this behaves correctly according to [RFC 1808](https://datatracker.ietf.org/doc/html/rfc1808#section-5.1). When the relative URL starts with `//`, it's considered to be a protocol-relative URL, which in effect means only the protocol portion of the absolute URL (`http:`) is preserved.

**Comment by MihaZupan** [comment] 2022-08-31 14:21
Strings starting with `//` are interpreted as absolute UNC file paths.
If you want to make sure it's interpreted as a relative Uri, specify that in the constructor.

> There should be a way to force that to be interpreted as relative.

`new Uri(uriString, UriKind.Relative)`

**Comment by jez9999** [comment] 2022-08-31 14:22
> Strings starting with `//` are interpreted as absolute UNC file paths. If you want to make sure it's interpreted as a relative Uri, specify that in the constructor.
> 
> > There should be a way to force that to be interpreted as relative.
> 
> `new Uri(uriString, UriKind.Relative)`

Indeed.  And I pointed out that the `Uri` overload that takes a second `Uri` ignores that.

**Comment by svick** [comment] 2022-08-31 16:29
> Regardless of that RFC, in the real world, there are scenarios where you're just going to want a double-slash at the beginning to be treated as relative.

You can do that by adding a period at the start of the relative URL. E.g. `new Uri(new Uri("http://localhost:3000/"), ".//hello/world")` produces `http://localhost:3000//hello/world`.

> That RFC is also extremely dated (1995) and doesn't seem to really describe the way URLs are parsed in the real world today. It states, for example, that "a relative URL may appear in any context that could hold an absolute URL". That makes no sense to me. A URL bar can't just have a relative URL typed into it (well it can, but it sure won't be parsed as a URL).

I think that interpretation already didn't make sense in 1995, so I'd consider that to be awkward phrasing.

Though you're right that that RFC is outdated, my bad. The current one seems to be [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986#section-5.4.1) from 2005. But I don't think that changes how double slashes in relative URLs are treated.

**Comment by jez9999** [comment] 2022-08-31 16:41
> > Regardless of that RFC, in the real world, there are scenarios where you're just going to want a double-slash at the beginning to be treated as relative.
> 
> You can do that by adding a period at the start of the relative URL. E.g. `new Uri(new Uri("http://localhost:3000/"), ".//hello/world")` produces `http://localhost:3000//hello/world`.

Fair enough, the dot does seem to work.  Not something I would've expected necessary, though.  Especially when you pass in a `Uri` with `UriKind.Relative`.  That kind should be the equivalent of the dot prefix for the string version of the constructor IMHO.

**Comment by MihaZupan** [comment] 2022-09-01 14:59
> For the record, they're not treated as UNC file paths. You're probably thinking of \\\\.

They have always been treated as UNC on Windows, and since .NET 5.0, also on Linux.

Do you have a scenario where you actually care about two leading slashes, or did you open this issue more so due to unexpected behavior?

The current RFC still defines this relative reference format: https://datatracker.ietf.org/doc/html/rfc3986#section-4.2

```ABNF
relative-ref  = relative-part [ "?" query ] [ "#" fragment ]

relative-part = "//" authority path-abempty
              / path-absolute
              / path-noscheme
              / path-empty
```

[Section 5.2.2](https://datatracker.ietf.org/doc/html/rfc3986#section-5.2.2) describes how base+relative references should be merged, and it also supports this case (given that the ABNF defines the `authority` in `relative-path`).

And in [section 5.4](https://datatracker.ietf.org/doc/html/rfc3986#section-5.4) ("Reference Resolution Examples"), this case is explicitly listed:

```
"http://a/b/c/d;p?q" + "//g" = "http://g"
```

If you want different behavior, you are always free to do your own manipulations over strings before parsing the value with `Uri`.


Given the above, I believe Uri is behaving according to the spec in this case, and we are unlikely to make changes here even if the behavior may not be obvious.

**Comment by jez9999** [comment] 2022-09-01 15:08
There's a bug in the ASP.NET SPA proxying where this behaviour wasn't predicted (probably because it's surprising) and where, therefore, `http://localhost:1234//foo/bar` causes an error.  That seems indicative to me that this is likely to cause the odd problem.  What exactly is the point of being able to specify `UriKind.Relative` explicitly if it's then going to be treated as an absolute URI in cases like this?

**Comment by MihaZupan** [comment] 2022-09-01 15:36
> There's a bug in the ASP.NET SPA proxying where this behaviour wasn't predicted

A bug in your application code, or are you referring to something ASP.NET itself is doing wrong here?

With this specific case, you have the added misfortune that these are also seemingly valid UNC paths in the absolute form, so you have to specify `UriKind.Relative`.
If you do, it's not treated as absolute. It is treated as a relative reference that also contains the `Authority` component.
I agree with you that the behavior is odd, but for better or worse it is what the Uri RFCs have defined for the past few decades.

**Comment by jez9999** [comment] 2022-09-01 15:43
A bug in ASP.NET itself, where it joins a `PathAndQuery` to a base URI; obviously when the former starts with `//` the base URI is discarded and unintended results arise.

As I mentioned, even if you do specify `UriKind.Relative`, the constructor that takes 2 overloads ignores this for the second arg.  Surely it should force it to be treated a relative if you've specified that for the second `Uri`?

**Comment by jez9999** [comment] 2022-09-01 16:16
> You mean that the server itself is parsing a request that starts with two slashes? That's not a bug. `http://host///path` is valid - the issue we're describing is only about how merging of base+relative is defined.

No, it's proxying incorrectly because of that path, replacing the intended hostname with the string after the double-slash; see https://github.com/dotnet/aspnetcore/issues/43662

> > As I mentioned, even if you do specify UriKind.Relative, the constructor that takes 2 overloads ignores this for the second arg. Surely it should force it to be treated a relative if you've specified that for the second Uri?
> 
> It's not ignored, it is treated as relative according to the spec.

Just for clarity; this is a spec that says "even when we explicitly pass a `Uri` as an argument named `relativeUri` whose kind has been explicitly specified as `Relative`, it can be magically transformed into an absolute URI, thus rendering `UriKind` worthless?

**Comment by MihaZupan** [comment] 2022-09-01 16:20
> Just for clarity; this is a spec that says "even when we explicitly pass a Uri as an argument named relativeUri whose kind has been explicitly specified as Relative, it can be magically transformed into an absolute URI, thus rendering UriKind worthless"?

No :) This is the accepted URI RFC that says that a relative Uri can still contain an Authority.
Even if you are convinced that it is absolute, I am telling you that it is not. It *is* relative, it just also contains the authority.

**Comment by jez9999** [comment] 2022-09-01 16:25
So what's it relative to, then?

**Comment by MihaZupan** [comment] 2022-09-01 16:28
The scheme. See https://stackoverflow.com/a/9646435/6845657

**Comment by Tratcher** [comment] 2022-09-01 18:15
> Regardless of that RFC, in the real world, there are scenarios where you're just going to want a double-slash at the beginning to be treated as relative. `https://www.youtube.com//feed/subscriptions` is acceptable to all browsers I know of, and the YouTube web server.

Can you give an example where the double-slash is functional/required? In the youtube example the server redirects to `https://www.youtube.com/feed/subscriptions` to drop the double slashes. There's a difference between tolerating oddities and actually making use of them.

I'd recommend against making any changes to Uri without a clear use case that's blocked.

**Comment by MihaZupan** [comment] 2022-09-06 15:58
ASP.NET will fix the erroneous use in `SpaProxy`, but we don't have any plans to change the behavior of `Uri` unless we see this being a common pain point for many users in the future.

**Closed by MihaZupan** 2022-09-06 15:58 UTC
Labels: area-System.Net, untriaged
