### ISSUE TITLE
Breaking change with DateTime

### ISSUE THREAD

**Issue by MarioZ** [dotnet/runtime#79956] opened 2022-12-18 08:05 UTC
### Description

There are some breaking changes after introducing the `DateTime.Microsecond` and `DateTime.Nanosecond` properties.
I was able to reproduce this with the `AddDays` and `AddMilliseconds` methods, but it's probably true for other Add methods as well.

### Configuration

.NET 7.0.1 on Windows 10.

### Regression?

```cs
DateTime date = new DateTime(1902, 1, 15);
double value = 15.6;
DateTime result = date.AddDays(value);
```
In .NET 6 the result was `30:01:1902 14:24:00`, but now in .NET 7, it is `30:01:1902 14:23:59.9999999`.
As you may notice, it is smaller by 100 nanoseconds.
Also just as an FYI, the [DateTime.AddDays method remarks](https://learn.microsoft.com/en-us/dotnet/api/system.datetime.adddays#remarks) specify:
> The value parameter is rounded to the nearest millisecond.

**Comment by Clockwork-Muse** [comment] 2022-12-24 19:46
Duplicate of #78452

The [PR with fixes to the documentation](https://github.com/dotnet/dotnet-api-docs/pull/8641) isn't in yet.

**Comment by danmoseley** [comment] 2022-12-25 01:10
@MarioZ  your feedback on the docs PR would be welcome. How can it be most helpful?

**Comment by MarioZ** [comment] 2022-12-27 08:23
@danmoseley I think it's fine to just add something like:
> in .NET 6 and before the value is rounded to the nearest millisecond, in .NET 7 and after it is rounded to the nearest tick (100 ns).

But besides that, I think it would be useful to have some statement about this in [Breaking changes in .NET 7](https://learn.microsoft.com/en-us/dotnet/core/compatibility/7.0).

**Comment by tarekgh** [comment] 2023-01-11 20:28
I have filed the breaking change https://github.com/dotnet/docs/issues/33492 and we already have a [PR](https://github.com/dotnet/dotnet-api-docs/pull/8641) for updating the docs.

Per that, I am closing this issue. Let's know if you have any more questions.

**Closed by tarekgh** 2023-01-11 20:28 UTC
Labels: untriaged, area-System.DateTime
