### ISSUE TITLE
Test failure System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_ServerCertificates_Http2_Test.NoCallback_BadCertificate_ThrowsException(url: \"https://wrong.host.badssl.com/\")

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#49185] opened 2021-03-05 02:54 UTC
Run: [runtime-libraries-coreclr outerloop 20210304.5](https://dev.azure.com/dnceng/public/_build/results?buildId=1022622&view=ms.vss-test-web.build-test-results-tab&runId=31809430&resultId=103882&paneView=debug)

Failed test:
```
net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c
 -System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_ServerCertificates_Http2_Test.NoCallback_BadCertificate_ThrowsException(url: \"https://wrong.host.badssl.com/\")
```

**Error message:**
```
Assert.Throws() Failure
Expected: typeof(System.Net.Http.HttpRequestException)
Actual:   (No exception was thrown)


Stack trace
   at System.Net.Http.Functional.Tests.HttpClientHandler_ServerCertificates_Test.NoCallback_BadCertificate_ThrowsException(String url) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.ServerCertificates.cs:line 222
--- End of stack trace from previous location ---
```

**Comment by antonfirsov** [comment] 2021-03-05 10:34
Most likely duplicate of #49028, which has been fixed in #49130, but the mentioned failure happened after the merge of that PR, which I don't understand. Let's watch for a while if it happens again, and close if it doesn't.

**Comment by ManickaP** [comment] 2021-03-11 17:14
Triage: this should be already fixed. We need to check Kusto data.

**Comment by antonfirsov** [comment] 2021-03-11 17:17
No new failures since `2021-03-04`, closing.

**Closed by antonfirsov** 2021-03-11 17:17 UTC
Labels: arch-x64, area-System.Net.Http, os-windows
