### ISSUE TITLE
ToString("n") returns different decimal places on net5.0 vs netcoreapp3.1

### ISSUE THREAD

**Issue by schotime** [dotnet/runtime#44587] opened 2020-11-12 12:16 UTC
Below you will find a simple example that illustrates the issue. 
The below code prints `21.000` in `net5.0`
If I replace the TargetFramework with `netcoreapp3.1` it returns `21.00`
I'm running 16.8 VS community.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <!--<TargetFramework>netcoreapp3.1</TargetFramework>-->
  </PropertyGroup>

</Project>
```

```cs
using System;
using System.Globalization;

namespace ConsoleApp12
{
    class Program
    {
        static void Main(string[] args)
        {
            CultureInfo.CurrentCulture = new CultureInfo("en-US");
            Console.WriteLine(21.ToString("n"));
        }
    }
}
```
![image](https://user-images.githubusercontent.com/202923/98939893-41f97680-253e-11eb-80ea-7a555a058b92.png)

Let me know if you need any more info or I'm doing something wrong.

**Comment by tannergooding** [comment] 2020-11-12 15:56
I am not currently able to repro:
![image](https://user-images.githubusercontent.com/10487869/98962235-4e88bb00-24bb-11eb-91cd-be2d3724535a.png)

In the screenshot above, I also printed the framework version as part of the first line, but I also tested without that addition.

The actual logic gets the number of decimal digits from `NumberFormatInfo.GetInstance(null).NumberDecimalDigits` (or passing in the user given `provider` in place of `null`), so I would expect that printing that returns `2` vs `3` on your box while it returns `2` both times for me.

@GrabYourPitchforks, could this be an NLS related change?

**Comment by KalleOlaviNiemitalo** [comment] 2020-11-12 16:13
@tannergooding, if I replace `new CultureInfo("en-US")` with `new CultureInfo("en-US", true)`, then the program outputs `21.000` with .NET 5.0 on Windows 10 20H2; but if I also [define `DOTNET_SYSTEM_GLOBALIZATION_USENLS=1`](https://docs.microsoft.com/dotnet/standard/globalization-localization/globalization-icu#use-nls-instead-of-icu), then it outputs `21.00`. This seems a difference between Windows NLS data and CLDR.

**Comment by danmosemsft** [comment] 2020-11-12 16:48
Marking regression as it's an unexpected behavior change, if we believe it's correct we can remove the label (but it could possibly use a note in the ICU doc)

**Comment by tarekgh** [comment] 2020-11-12 17:46
This is how the [Unicode standard CLDR data](https://github.com/unicode-org/icu/blob/master/icu4c/source/data/locales/en.txt#L24) define it. So this is expected change. Windows is converging to CLDR too as indicated in this [blog](https://docs.microsoft.com/en-us/archive/blogs/shawnste/locale-data-in-windows-10-cldr) too. The benefit here is now we are conforming with Unicode standard and will have consistent behavior across platforms and OS's. 

@schotime could you please elaborate what issue you are running into because if that?

**Comment by schotime** [comment] 2020-11-12 21:56
@tarekgh It was only used in a test here https://github.com/schotime/NPoco/blob/v5/test/NPoco.Tests/FluentTests/QueryTests/QueryProviderTests.cs#L349 to test out the query provider handling it, so it's not that big of a deal, as long as the currency one hasn't changed.

But nonetheless it broke the build right before I was about to release, so thought I'd mention it here. Especially when the doco says its 2 decimal places in its example.

![image](https://user-images.githubusercontent.com/202923/99000898-169e7800-258e-11eb-8a74-41bb4cf883c7.png)

**Comment by tarekgh** [comment] 2020-11-12 22:13
@schotime Thanks for the info. 

In general it is not right to assume such formatting will not change. This is happen most of the time with many cultures and would be good to not take any dependency on that. Usually we recommend users to immune themselves from such breaks either by using like Invariant culture which we keep it not changing. Or to use specific format when formatting. In your case example, using "N2" would be more reliable to do. I home you can do the same with the currency format too  

The doc examples are just examples showing different format and not intended to say this never change. We try to fix our docs in such old existed examples. but thanks for pointing to that.

Do you have any more questions or is it ok to close this issue?

**Closed** 2020-11-12 22:31 UTC
Labels: area-System.Numerics, regression-from-last-release, untriaged
