### ISSUE TITLE
`HostApplicationBuilder` does not update configuration file path.

### ISSUE THREAD

**Issue by kmcclellan** [dotnet/runtime#93145] opened 2023-10-06 18:38 UTC
### Description

`ConfigurationManager` does not reset the file providers for its configuration sources when the base path changes. Consequently, setting the path on a `HostApplicationBuilder` has no effect on the default sources.

### Reproduction Steps

```csharp
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;

var configDir = Directory.CreateTempSubdirectory();
var configFile = Path.Join(configDir.FullName, "appsettings.json");

File.WriteAllText(configFile, "{\"ConfigWorks\": \"Yes!\"}");

var builder = Host.CreateApplicationBuilder(args);
builder.Configuration.SetBasePath(configDir.FullName);

Console.WriteLine("Does config work? {0}", builder.Configuration["ConfigWorks"] ?? "No.");

File.Delete(configFile);
configDir.Delete();
```

### Expected behavior

Program outputs "Does config work? Yes!"

### Actual behavior

Program outputs "Does config work? No."

### Known Workarounds

I can manually force the sources to reset their file providers by adding the following code prior to setting the base path:

```csharp
foreach (var source in builder.Configuration.Sources.OfType<FileConfigurationSource>())
{
    if (source.FileProvider == builder.Configuration.GetFileProvider())
    {
        source.FileProvider = null;
    }
}
```

This causes the program to work as expected.

### Configuration

.NET 7.0.11
Windows 10

**Comment by tarekgh** [comment] 2023-10-06 19:15
This is a duplicate of https://github.com/dotnet/runtime/issues/85068. Feel free to comment there with any additional information. Thanks for your report.

**Closed by tarekgh** 2023-10-06 19:15 UTC
Labels: untriaged, area-Extensions-Configuration
