### ISSUE TITLE
WASM: Satellite resources not read as expected in .net9.0 preview7

### ISSUE THREAD

**Issue by dczuo** [dotnet/runtime#106456] opened 2024-08-15 12:34 UTC
### Description

[wba1.zip](https://github.com/user-attachments/files/16625089/wba1.zip)

### Reproduction Steps

Run wba1

### Expected behavior

Console output: TestChinese

### Actual behavior

Console output: TestInvariant

### Regression?

Yes, preview6 is fine

**Comment by lewing** [comment] 2024-08-19 16:38
duplicate of https://github.com/dotnet/runtime/issues/105937

**Comment by lewing** [comment] 2024-08-19 16:38
cc @maraf

**Closed by lewing** 2024-08-19 16:38 UTC
Labels: arch-wasm, area-System.Globalization, untriaged, needs-area-label
