### ISSUE TITLE
Getting exception DllNotFoundException: Unable to load DLL 'gdiplus.dll' in windows docker container

### ISSUE THREAD

**Issue by pankajarav** [dotnet/runtime#42499] opened 2020-09-20 07:53 UTC
Below command is working with Linux docker container but I did not get any proper command to install gdiplus dll in windows docker container.

	# install libgdiplus for System.Drawing
RUN apt-get update && \
    apt-get install -y --allow-unauthenticated libgdiplus libc6-dev

# install x11 for System.Drawing
RUN apt-get update && \
    apt-get install -y --allow-unauthenticated libx11-dev

**Comment by safern** [comment] 2020-09-22 15:47
Unfortunately on Windows we depend on GDI+ to be available and that is part of the OS binaries. Some Windows SKUs like Server Core and Nano, don't include this binary as part of Windows. 

I believe there is no way on getting GDI+ install on Windows if the OS doesn't provide it.

I will close this issue as by design, but feel free to re-open if you disagree and think this is something we should discuss further.

**Comment by jkotas** [comment] 2020-09-22 16:13
@safern Do we need to add a note about this to documentation?

**Comment by safern** [comment] 2020-09-22 16:17
> @safern Do we need to add a note about this to documentation?

Hmm, that's a good idea. Thanks for the suggestion.

**Comment by danmosemsft** [comment] 2020-10-16 16:05
@safern do you believe you'll have time to do this in the next couple days? It is one of the last bugs left in the 5.0 milestone in our repo so it would be good to close.

**Comment by safern** [comment] 2020-10-16 16:06
Yeah I'll do it today.

**Closed** 2020-10-22 19:26 UTC
Labels: area-System.Drawing, documentation
