### ISSUE TITLE
Test failure System.IO.Compression.BrotliStreamUnitTests.ReadWrite_Success

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#65821] opened 2022-02-24 01:20 UTC
Run: [runtime-coreclr libraries-jitstress 20220222.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1627567&view=ms.vss-test-web.build-test-results-tab&runId=45178844&paneView=debug&resultId=126368)

Failed test:
```
net7.0-windows-Release-arm64-CoreCLR_checked-jitstress2-Windows.10.Arm64v8.Open

- System.IO.Compression.BrotliStreamUnitTests.ReadWrite_Success(mode: AsyncMemory, writeSize: 1, startWithFlush: False)

```
**Error message:**
```
System.ArgumentException : Stream does not support reading. (Parameter 'stream')


Stack trace
   at System.IO.Compression.BrotliStream..ctor(Stream stream, CompressionMode mode, Boolean leaveOpen) in /_/src/libraries/System.IO.Compression.Brotli/src/System/IO/Compression/BrotliStream.cs:line 38
   at System.IO.Compression.BrotliStreamUnitTests.CreateStream(Stream stream, CompressionMode mode) in /_/src/libraries/System.IO.Compression.Brotli/tests/CompressionStreamUnitTests.Brotli.cs:line 12
   at System.IO.Compression.CompressionStreamTestBase.CreateConnectedStreamsAsync() in /_/src/libraries/Common/tests/System/IO/Compression/CompressionStreamTestBase.cs:line 46
   at System.IO.Tests.ConnectedStreamConformanceTests.ReadWrite_Success(ReadWriteMode mode, Int32 writeSize, Boolean startWithFlush) in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 1727
--- End of stack trace from previous location ---
```

**Comment by adamsitnik** [comment] 2022-02-24 07:56
Duplicate of https://github.com/dotnet/runtime/issues/65650

**Closed by adamsitnik** 2022-02-24 07:56 UTC
Labels: arch-arm64, area-System.IO.Compression, os-windows, JitStress, untriaged
