### ISSUE TITLE
How can we get all KVP from MemoryCache(Microsoft.Extensions.Caching.Memory) ?

### ISSUE THREAD

**Issue by Naidile-P-N** [dotnet/runtime#55020] opened 2021-07-01 16:06 UTC
I want to check the memory usage by the application and how much space each key in the cache is consuming.
Is there a way to evaluate this?

**Comment by eerhardt** [comment] 2021-07-01 16:14
See https://github.com/dotnet/runtime/issues/36554.

Closing as a duplicate of that issue.

**Closed by eerhardt** 2021-07-01 16:14 UTC
Labels: area-Extensions-Caching, untriaged
