### ISSUE TITLE
Microsoft.Extensions.Hosting.WindowsServices.WindowsServiceHelpers.IsWindowsService crashes when started as service

### ISSUE THREAD

**Issue by schuettecarsten** [dotnet/runtime#67093] opened 2022-03-24 11:27 UTC
### Description

`IsWindowsService` fails when an App is started as a service from `services.msc` MMC plugin.

```
 ---> System.InvalidOperationException: Process has exited, so the requested information is not available.
   at System.Diagnostics.Process.get_ProcessName()
   at Microsoft.Extensions.Hosting.WindowsServices.WindowsServiceHelpers.IsWindowsService()
```

### Reproduction Steps

Create an executable, call `Microsoft.Extensions.Hosting.WindowsServices.WindowsServiceHelpers.IsWindowsService()` and register this app as a Windows Service. Start this service from the `services.msc` MMC plugin. It will fail.

### Expected behavior

Should work and return true or false...

### Actual behavior

Exception

### Regression?

Yes, worked with preview.1

### Known Workarounds

No workaround.

### Configuration

CoreCLR Version: 7.0.22.15202
.NET Version: 7.0.0-preview.2.22152.2

### Other information

CoreCLR Version: 7.0.22.15202
.NET Version: 7.0.0-preview.2.22152.2

 ---> System.InvalidOperationException: Process has exited, so the requested information is not available.
   at System.Diagnostics.Process.get_ProcessName()
   at Microsoft.Extensions.Hosting.WindowsServices.WindowsServiceHelpers.IsWindowsService()

**Comment by schuettecarsten** [comment] 2022-03-24 11:38
It looks like this is a regression caused by https://github.com/dotnet/runtime/commit/36bf84fc4a89209f4fdbc1fc201e81afd8be49b0#diff-cad6ac7588b79c6ec328914f3260db532273d769cf2c608d1d60eeb3d22a40d4, as it worked with preview.1 and this is the only change in that code .

**Comment by MiyamuraMiyako** [comment] 2022-04-12 03:52
```
000000910DD7E588 00007ffde3ca42a4 [HelperMethodFrame: 000000910dd7e588] 
000000910DD7E680 00007ffdb9fb4c7f Microsoft.AspNetCore.Builder.ConfigureHostBuilder.ConfigureHostConfiguration(System.Action`1<Microsoft.Extensions.Configuration.IConfigurationBuilder>) [/_/src/DefaultBuilder/src/ConfigureHostBuilder.cs @ 81]
000000910DD7E720 00007ffca8885f45 Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.UseContentRoot(Microsoft.Extensions.Hosting.IHostBuilder, System.String)
000000910DD7E770 00007ffca8880984 Program.$(System.String[]) [C:\Users\zgxlt\source\repos\T\T\Program.cs @ 9]
```

![图片](https://user-images.githubusercontent.com/10345361/162876794-1fa195bb-0c0b-48e0-921d-76c026e39e7d.png)

@eerhardt  Exception throw  on line 9.

**Comment by maryamariyan** [comment] 2022-04-12 21:18
Did you try changing the recommendation in the exception message to use `WebApplication.CreateBuilder(WebApplicationOptions)` instead?

**Comment by MiyamuraMiyako** [comment] 2022-04-13 03:43
> Did you try changing the recommendation in the exception message to use `WebApplication.CreateBuilder(WebApplicationOptions)` instead?

But I can't change `builder.Host.UseWindowsService();` logic.

**Comment by MiyamuraMiyako** [comment] 2022-04-14 09:51
@eerhardt 

![图片](https://user-images.githubusercontent.com/10345361/163360221-d1f049f2-9544-4420-8fd6-74a4c8431083.png)

I change `ContentRootPath`'s value to `AppContext.BaseDirectory` but still throw exception.

**Comment by eerhardt** [comment] 2022-04-14 17:33
I am unable to repro the issue you are seeing @MiyamuraMiyako. Can you add a minimal repro app that reproduces the problem?

Here is my .csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="7.0.0-preview.3.22175.4" />
    <PackageReference Include="Serilog.AspNetCore" Version="6.0.0-dev-00265" />
  </ItemGroup>

</Project>
```
and my Program.cs:

```C#
using Serilog;

var ops = new WebApplicationOptions()
{
    Args = args,
    ContentRootPath = AppContext.BaseDirectory
};
var builder = WebApplication.CreateBuilder(ops);
builder.Host.ConfigureLogging(logging =>
{
 logging.ClearProviders();
 logging.SetMinimumLevel(LogLevel.Trace);
})
.UseWindowsService()
.UseSerilog();

var app = builder.Build();

app.MapGet("/", () => "Hello World!");

app.Run();
```

I publish:

`$ dotnet publish -c Release -r win-x64`

and create the service:

`⚡ $ sc.exe create "Eric Test" binpath="C:\DotNetTest\AspNet\bin\Release\net6.0\win-x64\publish\AspNet.exe"`

And the service starts successfully.

**Comment by MiyamuraMiyako** [comment] 2022-04-17 12:34
Interesting, my minimal program run in windows service successfully.
but my origin program run and throw exception.

WinDbg:
        Child SP               IP Call Site
000000FAB6B7AE48 00007ff92e1301c4 [HelperMethodFrame: 000000fab6b7ae48] 
000000FAB6B7AF40 00007ff89d582578 
000000FAB6B7DA48 00007ff8fd0e70bc [HelperMethodFrame: 000000fab6b7da48] 
000000FAB6B7DB40 00007ff8ffb8cebc System.Diagnostics.Process.get_ProcessName() [/_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Windows.cs @ 885]
000000FAB6B7DB80 00007ff89d58a8de Microsoft.Extensions.Hosting.WindowsServices.WindowsServiceHelpers.IsWindowsService() [/_/src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceHelpers.cs @ 32]
000000FAB6B7DBD0 00007ff89d58a72c Microsoft.Extensions.Hosting.WindowsServiceLifetimeHostBuilderExtensions.UseWindowsService(Microsoft.Extensions.Hosting.IHostBuilder, System.Action`1<Microsoft.Extensions.Hosting.WindowsServiceLifetimeOptions>) [/_/src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetimeHostBuilderExtensions.cs @ 47]
000000FAB6B7DC50 00007ff89d58a5ff Microsoft.Extensions.Hosting.WindowsServiceLifetimeHostBuilderExtensions.UseWindowsService(Microsoft.Extensions.Hosting.IHostBuilder) [/_/src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceLifetimeHostBuilderExtensions.cs @ 31]
000000FAB6B7DCB0 00007ff89d58097e 

System event viewer:
Application: SayedKioskHub.exe
CoreCLR Version: 7.0.22.17504
.NET Version: 7.0.0-preview.3.22175.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: Process has exited, so the requested information is not available.
   at System.Diagnostics.Process.get_ProcessName()
   at Microsoft.Extensions.Hosting.WindowsServices.WindowsServiceHelpers.IsWindowsService()
   at Microsoft.Extensions.Hosting.WindowsServiceLifetimeHostBuilderExtensions.UseWindowsService(IHostBuilder hostBuilder, Action`1 configure)
   at Microsoft.Extensions.Hosting.WindowsServiceLifetimeHostBuilderExtensions.UseWindowsService(IHostBuilder hostBuilder)
   at Program.<Main>$(String[] args) in D:\SayedKioskHub\Program.cs:line 49

**Comment by schuettecarsten** [comment] 2022-04-17 16:27
> Interesting, my minimal program run in windows service successfully. but my origin program run and throw exception.

This might be a timing issue. When the initialization of the app takes too long, the parent process is no longer available and get_ProcessName() runs into an exception.

**Comment by MiyamuraMiyako** [comment] 2022-04-18 05:03
@schuettecarsten Is there anything I can do to fix this problem?

**Comment by eerhardt** [comment] 2022-04-18 22:25
@MiyamuraMiyako without more information (for example a reproduction app) we can't really help. What does your .csproj look like? What .NET version are you using? What version of `Microsoft.Extensions.Hosting.WindowsServices`? etc.

**Comment by maryamariyan** [comment] 2022-04-19 21:16
Closing as is, please reopen if you were able to provide a minimal repro.

**Closed by maryamariyan** 2022-04-19 21:16 UTC
Labels: area-Extensions-Hosting, needs-further-triage
