### ISSUE TITLE
Test failure: profiler\\unittest\\releaseondetach\\releaseondetach.cmd

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#45335] opened 2020-11-30 03:41 UTC
failed in job: https://dev.azure.com/dnceng/public/_build/results?buildId=902349&view=ms.vss-test-web.build-test-results-tab&runId=28814280&resultId=103889&paneView=debug

CoreCLR windows x86 Checked gcstress0x3 @ Windows.10.Amd64.Open

Error message
~~~
Assert failure(PID 8268 [0x0000204c], Thread: 3432 [0x0d68]): !CREATE_CHECK_STRING(!"Detected use of a corrupted OBJECTREF. Possible GC hole.")

CORECLR! Object::ValidateInner + 0x58A (0x702b8e8a)
CORECLR! Object::Validate + 0xF5 (0x702b88c5)
CORECLR! WKS::GCHeap::Relocate + 0x39 (0x706323c9)
CORECLR! TransitionFrame::PromoteCallerStackUsingGCRefMap + 0x11D (0x7022ec85)
CORECLR! ExternalMethodFrame::GcScanRoots + 0x93 (0x7022c5e3)
CORECLR! GcStackCrawlCallBack + 0x1EA (0x703def3a)
CORECLR! Thread::MakeStackwalkerCallback + 0x48 (0x702ec212)
CORECLR! Thread::StackWalkFramesEx + 0x178 (0x702ed8ab)
CORECLR! Thread::StackWalkFrames + 0x159 (0x702ed6b3)
CORECLR! ScanStackRoots + 0x195 (0x703de1a6)
    File: F:\workspace\_work\1\s\src\coreclr\src\vm\object.cpp Line: 593
    Image: C:\h\w\AE8D094B\p\CoreRun.exe


Return code:      1
Raw output file:      C:\h\w\AE8D094B\w\997D0893\e\profiler\unittest\Reports\profiler.unittest\releaseondetach\releaseondetach.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\AE8D094B\p\corerun.exe" releaseondetach.dll 
Profiler path: C:\h\w\AE8D094B\w\997D0893\e\profiler\unittest\releaseondetach\Profiler.dll
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\AE8D094B\p
> C:\h\w\AE8D094B\w\997D0893\e\profiler\unittest\releaseondetach\releaseondetach.cmd
Expected: True
Actual:   False

Stack trace
   at profiler_unittest._releaseondetach_releaseondetach_._releaseondetach_releaseondetach_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\windows.x86.Checked\TestWrappers\profiler.unittest\profiler.unittest.XUnitWrapper.cs:line 367
~~~

**Comment by GrabYourPitchforks** [comment] 2020-11-30 09:19
Likely dupe of https://github.com/dotnet/runtime/issues/45317, fixed by https://github.com/dotnet/runtime/pull/45320

**Closed by GrabYourPitchforks** 2020-11-30 09:19 UTC
Labels: untriaged
