### ISSUE TITLE
`JsonSerializerContext` in System.Text.Json doesn't support the same inheritor class name in different namespaces

### ISSUE THREAD

**Issue by seclerp** [dotnet/runtime#110931] opened 2024-12-24 19:56 UTC
### Description

Currently, the source generation of serialization classes is impossible if the project has 2 `JsonSerializerContext` classes with equal names but laying in different namespaces. 

### Reproduction Steps

Create .NET 9 project with such content:

```csharp

// Namespace1/SourceGenerationContext
namespace ConsoleApp2.Namespace1;

[JsonSourceGenerationOptions(WriteIndented = true)]
[JsonSerializable(typeof(int))]
internal partial class SourceGenerationContext : JsonSerializerContext
{
}

// Namespace2/SourceGenerationContext
namespace ConsoleApp2.Namespace2;

[JsonSourceGenerationOptions(WriteIndented = true)]
[JsonSerializable(typeof(int))]
internal partial class SourceGenerationContext : JsonSerializerContext
{
}
```

### Expected behavior

STJ will generate 2 separate partial implementations for both contexts.

### Actual behavior

Build output:

```
0>CSC: Warning CS8785 : Generator 'JsonSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'The hintName 'SourceGenerationContext.Int32.g.cs' of the added source file must be unique within a generator. (Parameter 'hintName')'.
```

### Known Workarounds

Rename one of the contexts, as it makes output generated class names unique again.

### Configuration

.NET 9.0.101

**Comment by eiriktsarpalis** [comment] 2024-12-25 08:45
Essentially a duplicate of https://github.com/dotnet/runtime/issues/72671

**Closed by eiriktsarpalis** 2024-12-25 08:45 UTC
Labels: area-System.Text.Json, untriaged
