### ISSUE TITLE
System.Linq.Except violates Linq lazy iteration paradigm

### ISSUE THREAD

**Issue by KeilFelix** [dotnet/runtime#49478] opened 2021-03-11 11:09 UTC
The second Enumerable is always completely iterated and not lazy iterated!

See the current implementation of ExceptIterator:

```
Set<TSource> set = new Set<TSource>(comparer);
set.UnionWith(second);

foreach (TSource element in first)
{
    if (set.Add(element))
    {
        yield return element;
    }
}
```

to fix the implementation it should look something like this (of my mind & untested):

```
if(comparer == null) comparer = EqualityComparer<TSource>.Default;
Set<TSource> set = new Set<TSource(comparer);

using(IEnumerator<TSource> e2 = second.GetEnumerator())
{
    foreach(TSource element = first)
    {
        if(set.Contains(element)) continue;

        while(e2.MoveNext() && !comparer.Equals(element, e2.Current))
        {
            set.Add(e2.Current);
        }

        if(set.Add(element)) yield return element;
    }
}
```

As an offtopic humble side note request:  Please add Memoize()-functionality to .Net because Linq-starters don't know the importance of this concept, that it even exists and that they actually need it.

**Comment by canton7** [comment] 2021-03-11 11:50
I don't think Linq has ever promised to lazy-iterate all inputs in all cases? `OrderBy`, `GroupBy`, etc, all iterate an input in one go (although they defer that until the first element is requested). I can't see any advantage in `Except` incrementally iterating one of its inputs, especially as doing so is more expensive.

**Comment by KeilFelix** [comment] 2021-03-11 12:50
@canton7 Of course it is impossible to make your mentioned example lazy. However where it is possible, it is a convention that it is designed lazy, e.g. Where, Select, SelectMany. My proposed implementation just enumerates what is needed and is thus cheaper and not more expensive. Your last sentence really irritates me and unsettles me in my computional knowledge. Can you please elaborate?

As a second argument:
I don't think users expect any enumeration on the second-Enumerable to happen if  first-Enumerable is empty.

**Comment by eiriktsarpalis** [comment] 2021-03-11 13:24
The current implementation is still "lazy" in the sense that `second` is evaluated inside the body of the iterator. I'm not sure what the proposed change would achieve other than making the code slower for the sake of potentially avoiding a full enumeration of `second`. It is highly unlikely we would support such a change.

I'm going to close this issue. Thank you for the contribution.

**Closed by eiriktsarpalis** 2021-03-11 13:24 UTC
Labels: area-System.Linq, untriaged

**Comment by canton7** [comment] 2021-03-11 13:29
> My proposed implementation just enumerates what is needed and is thus cheaper and not more expensive. Your last sentence unsettles me in my computional knowledge. Can you please elaborate why this should be more expensive? Do other forms of iteration exist on enumerables?

My assumption is that the majority of uses of `Except` will yield at least one element. In this case, you need to iterate `second` in its entirety anyway. Doing this upfront is cheaper. In your implementation,  if `element` isn't a member of `set`, then you need to do:

1. `set.Contains(element)` (which fails)
2. Any number of `Equals` calls
3. `set.Add(element)` (which effectively does `set.Contains(element)` again, internally)

The current implementation just does `set.Add(element)`, so your implementation has added on `set.Contains(element)`, plus a number of calls to `Equals`. Hence, higher cost.

> I don't think users expect any enumeration on the second-Enumerable if first-Enumerable is empty.

I buy that: I'm surprised the currently implementation doesn't do this already.

**Comment by eiriktsarpalis** [comment] 2021-03-11 13:33
>> I don't think users expect any enumeration on the second-Enumerable if first-Enumerable is empty.
>
>I buy that: I'm surprised the current implementation doesn't do this already.

We generally try to avoid baking in optimizations for corner cases, since they always incur a cost in the common scenaria.

**Comment by KeilFelix** [comment] 2021-03-11 13:50
@canton7 
Thank you very much for the elaboration. I just thought of the pure algorithm complexity. I am really unsure what weighs more. So I buy that too and trust in the knowledge of your team. :)
Just a short note: For the cases where the majority of elements are filtered out by the first few elements in second, I think my proposed implementation is also faster. But please think of it twice if it really is just an optimization for corner cases.

@eiriktsarpalis We had a bug in production code, because the assumption was, that second Enumerable is not enumerated if the first is empty. It was fixed with if(first.Any())  :( 
Maybe you should think of reopening the issue for this argument?

**Comment by eiriktsarpalis** [comment] 2021-03-11 14:00
> We had a bug in production code, because the assumption was, that second Enumerable is not enumerated if the first is empty. It was fixed with if(first.Any()) :(
Maybe you should think of reopening the issue for this argument?

Why were you making this assumption? Has the implementation regressed from earlier releases? If anything this could be turned into an argument that changing it would break code that assumes (correctly) that the second enumerable will always be consumed.

As a general note, code that breaks because of how enumerables are evaluated may rely on some form of side-effect in the enumeration. I would strongly recommend against doing this, since we occasionally apply optimizations that may change the evaluation strategy of Linq methods.

**Comment by KeilFelix** [comment] 2021-03-11 14:25
@eiriktsarpalis 
The assumption was made because of LINQs lazy conventions and I am really suprised that you don't think that this was not a natural and rightful assumption.

I know there are better Linq ways to do this. But this is a really highly reduced sample of the bug:
`sample.Except(Enumerable.Repeat(test.First(), 1));`
As you can see the bug is not introduced by relying on some form of side effect of the enumeration.

I can accept the closure of this issue but I am really suprised how fast the decision was made. Did you also read the arguments in my last reply to @canton7 ?

I really question if you properly evaluated my arguments.

**Comment by canton7** [comment] 2021-03-11 14:28
> So I buy that too and trust in the knowledge of your team

(Just to set the record straight: I'm a random member of the public, and not affiliated with Microsoft in any way. You get lots of members of the public in these repos, so it's worth hovering over someone's name to see whether they're a member of Microsoft or not)

**Comment by eiriktsarpalis** [comment] 2021-03-11 14:40
> The assumption was made because of LINQs lazy conventions and I am really suprised that you don't think that this was a natural and rightful assumption.

As mentioned, the existing implemention doesn't violate "lazy conventions". This can be seen via the following example:
```csharp
int enumerationCount = 0;
IEnumerable<int> Test(int count)
{
    for (int i = 0; i < count; i++)
    {
        enumerationCount++;
        yield return i;
    }
}

var enumerable = Enumerable.Range(1, 100).Except(Test(42));
Assert.Equal(0, enumerationCount); // no enumeration has occurred, in line with IEnumerable deferred execution

enumerable.GetEnumerator();
Assert.Equal(42, enumerationCount); // creating an enumerator forces enumeration of `second` argument
```

**Comment by eiriktsarpalis** [comment] 2021-03-11 14:53
> I can accept the closure of this issue but I am really suprised how fast the decision was made. Did you also read the arguments in my last reply to @canton7 ?
>
> I really question if you properly evaluated my arguments.

I have considered your arguments, but I can elaborate a bit more on my thoughts, if you wish:

1. As mentioned the current implementation does not violate IEnumerable deferred execution semantics.
2. Your proposed optimization would only have a perceivable difference in cases where elements in `first` appear in the same order as elements in `second`. That's an implicit assumption that `Except` does not make, it is a general-purpose set-difference operation.
3. It would make performance worse in all cases, since the hashset is constructed suboptimally and adds more branching in the main loop.

Please do not regard my closing of the issue as an attempt to shut down the conversation. It merely reflects our own backlog management and we are always happy to reopen issues in face of new evidence :-)

**Comment by masonwheeler** [comment] 2021-03-11 15:05
The Intersect and Except operations eagerly enumerating the second set has been a well-understood principle for at least a decade.  (See Jon Skeet's "Edulinq" blog posts on the subject from 2010.)  Changing that would likely surprise people who are depending on it working that way.

**Comment by KeilFelix** [comment] 2021-03-11 15:31
@eiriktsarpalis 
Cool, thank you :)
My last sample was wrong because it throws to early, I adapted it.
 
I called it **lazy conventions** and not just **lazy execution** because I thought it is also a goal of LINQ to avoid iteration when unnecessary or whenever possible?! E.g. see implementation of Count().

I think highest performance is gained by avoiding enumeration?! -> The performance cost of an enumeration cannot be estimated and might be very high e.g. IO operations.

My proposal was just the best readable form to illustrate the assumed behavior. I think it can be optimized so that it is just as efficient as current algorithm.

@masonwheeler 
I found the blog post to the Except algorithm explanation. But I cannot see that it is a principle to eagerly enumerate the second-Enumerable or that it had any other good reasoning than easy implementation?!

**Comment by Clockwork-Muse** [comment] 2021-03-11 16:35
The problem is that in the average case you have to iterate over about half the elements in the exclusion set before you can return the first one (and in the worst case you must iterate them all).  Additionally, it's likely that most uses will have smaller exclusionary sets than source sets, which is going to have the effect of iterating over all the elements in the exclusionary set long before that in the source set.

> var sample = Enumerable.Empty<int>();
> 
> IEnumerable<int> ExceptFromSample()
> {
>     yield return sample.First();
> }
> 
> var badExceptUsage = sample.Except(ExceptFromSample());
> 
> badExceptUsage.GetEnumerator();

This code generates no exception.  Iterating over the iterator does, however the exception this code generates is due to `sample.First()` complaining about not having an element to return (not due to `Except`), and would have occurred with your version as well.  Essentially, this is an enumerator issue.  
This is a poison pill - when (or if) it occurs is outside your control for many operators.  If this is the actual issue you're running into in your real code, either fix your enumerator, or let the exception bubble through.
