### ISSUE TITLE
Use Vector512 in BinaryPrimitives.ReverseEndianness

### ISSUE THREAD

**Issue by colejohnson66** [dotnet/runtime#108887] opened 2024-10-15 13:14 UTC
### Description

Currently, `BinaryPrimitives.ReverseEndianness` only uses `Vector128` and `Vector256` for acceleration. With `Vector512` being added in .NET 8 (two years ago), `Vector512` acceleration should be added.

https://github.com/dotnet/runtime/blob/87a35d6bf48fb418bf53630cd346781b349148f3/src/libraries/System.Private.CoreLib/src/System/Buffers/Binary/BinaryPrimitives.ReverseEndianness.cs#L366-L371

### "API" Proposal

```csharp
namespace System.Buffers.Binary;

public static class BinaryPrimitives
{
    private interface IEndiannessReverser<T> where T : struct
    {
        static abstract Vector512<T> Reverse(Vector512<T> vector);
    }
}
```

**Comment by MihaZupan** [comment] 2024-10-15 13:21
Duplicate of #108204

**Closed by MihaZupan** 2024-10-15 13:21 UTC
Labels: tenet-performance, needs-area-label
