### ISSUE TITLE
string.StartsWith("\0") always returns true on Linux.

### ISSUE THREAD

**Issue by Tomkaa** [dotnet/runtime#474] opened 2019-12-03 08:25 UTC
`string.StartsWith("\0")` returns different values on Linux and Windows environments. I believe incorrect value is returned in Linux env.

Version tested 3.0.101

On Windows `"asd".StartsWith("\0")` returns `False`.
On Linux `"asd".StartsWith("\0")` returns `True`.

Linux OS tested on: Fedora 31 with 5.3.13-300.fc31.x86_64 kernel build.

This issue doesn't seem to present on Linux containers running in Windows Docker.

**Comment by gfoidl** [comment] 2019-12-03 12:29
Related to this is https://github.com/dotnet/coreclr/issues/2051

**Comment by GrabYourPitchforks** [comment] 2020-01-29 02:51
By design - dupe of https://github.com/dotnet/coreclr/issues/2051. If you want to perform an ordinal (non-linguistic) comparison, pass `StringComparison.Ordinal` or `StringComparison.OrdinalIgnoreCase` to one of the `string.StartsWith` overloads.

**Closed by GrabYourPitchforks** 2020-01-29 02:51 UTC
Labels: area-System.Runtime, untriaged
