### ISSUE TITLE
Mutiple Calls to Microsoft.Extensions.Hosting.BackgroundService StartAsync will leave unstoppable tasks

### ISSUE THREAD

**Issue by bsagal** [dotnet/runtime#36943] opened 2020-05-24 09:02 UTC
### Description

If I an `BackgroundService` object and call `StartAsync` multiple time i get left with unstoppable services.  

The following code shows the problem

```C#
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Hosting;

public class Program
{
    public static async Task Main()
    {
        var service = new TestService();
        await service.StartAsync(default);
        await service.StartAsync(default);
        Console.WriteLine("-----");
        await service.StopAsync(default);
        Console.WriteLine("-----");
        await service.StopAsync(default);
        Console.WriteLine("-----");
        await Task.Delay(1000);
    }
}

public class TestService : BackgroundService
{
    private int _count;

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        var id = _count++;
        Console.WriteLine("Starting " + id);
        try
        {
            await Task.Delay(Timeout.Infinite, stoppingToken);
        }
        catch (TaskCanceledException)
        {
            //IGNORE
        }
        Console.WriteLine("Finished " + id);
    }
}
```

Will Output:
```
Starting 0
Starting 1
-----
Finished 1
-----
-----
```

### Configuration

The problem is reproducible with `Microsoft.Extensions.Hosting.Abstractions` Version `5.0.0-preview.4.20251.6`

### Regression?

With `Microsoft.Extensions.Hosting.Abstractions` Version `3.1.4` the output was:
```
Starting 0
Starting 1
-----
Finished 1
Finished 0
-----
-----
```

While this is also not ideal (both tasks are finished together) at least no unstoppable tasks are left.

I believe the regressions was introduced by dotnet/extensions#2823 

### Other information

I found this problem writing a manager witch starts and stops IHostedServices.
I would like to be able to start a IHostedServices then stop it, then at a later point be able to start it again.

While i see this that `BackgroundService` does not support this I would have preferred a second call to  `StartAsync` on a running service to throw an error.

**Comment by eerhardt** [comment] 2020-08-18 22:06
Since this is a regression in 5.0, I've put this in the 5.0 milestone. We should decide what to do here.

@Tratcher @davidfowl - does it make sense to allow for the same `BackgroundService` to be started multiple times without being stopped? I know this worked in 3.1, but the linked PR https://github.com/dotnet/extensions/pull/2823 regressed this scenario. But my initial thinking is that this shouldn't be a valid scenario. If you want 2 background services running, you should create 2 instances and Start them both. `StartAsync` should throw if the service is already running and hasn't been stopped.

Thoughts?

**Comment by Tratcher** [comment] 2020-08-18 22:10
Agreed, this scenario conflicts with the intended design. Background services weren't intended to be run by themselves. The host creates the service, starts it, stops it, and disposes it.

**Comment by maryamariyan** [comment] 2020-08-20 20:52
Moving to 6.0 as it is not critical to fix for 5.0. 
The fix involves throwing an exception the second time `StartAsync` is called

**Comment by maryamariyan** [comment] 2020-10-08 15:54
> Background services weren't intended to be run by themselves. The host creates the service, starts it, stops it, and disposes it.

The expected result: do not allow StartAsync to be called twice, on second call throw an exception.

**Comment by davidfowl** [comment] 2020-10-08 16:00
> The expected result: do not allow StartAsync to be called twice, on second call throw an exception.

I'm not sure we have to do anything here. The above code is manually invoking the IHostedService

**Comment by davidfowl** [comment] 2021-02-25 06:55
I think this should be closed. The code example above is calling into a background service without the host. That's not something we need to support.

**Closed** 2021-02-25 19:11 UTC
Labels: area-Extensions-Hosting, up-for-grabs
