### ISSUE TITLE
[tvOS] System.Drawing.PrimitivesTest.RectangleTests.RectangleFConversionTest failed

### ISSUE THREAD

**Issue by MaximLipnin** [dotnet/runtime#60172] opened 2021-10-08 12:37 UTC
```
      <test name="System.Drawing.PrimitivesTest.RectangleTests.RectangleFConversionTest(x: 3.4028235E+38, y: -3.4028235E+38, width: 3.4028235E+38, height: -3.4028235E+38)" type="System.Drawing.PrimitivesTest.RectangleTests" method="RectangleFConversionTest" time="0.006278" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\nExpected: {X=2147483647,Y=-2147483648,Width=2147483647,Height=-2147483648}\nActual:   {X=2147483647,Y=-2147483648,Width=-1,Height=0}]]></message>
          <stack-trace><![CDATA[   at System.Drawing.PrimitivesTest.RectangleTests.RectangleFConversionTest(Single x, Single y, Single width, Single height)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]></stack-trace>
        </failure>
      </test>
      <test name="System.Drawing.PrimitivesTest.RectangleTests.RectangleFConversionTest(x: -3.4028235E+38, y: 3.4028235E+38, width: -3.4028235E+38, height: 3.4028235E+38)" type="System.Drawing.PrimitivesTest.RectangleTests" method="RectangleFConversionTest" time="0.0005553" result="Fail">
        <failure exception-type="Xunit.Sdk.EqualException">
          <message><![CDATA[Assert.Equal() Failure\nExpected: {X=-2147483648,Y=2147483647,Width=-2147483648,Height=2147483647}\nActual:   {X=-2147483648,Y=2147483647,Width=0,Height=-1}]]></message>
          <stack-trace><![CDATA[   at System.Drawing.PrimitivesTest.RectangleTests.RectangleFConversionTest(Single x, Single y, Single width, Single height)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)]]></stack-trace>
        </failure>
      </test>
```

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-59503-merge-82a08e0bf78247ad85/System.Drawing.Primitives.Tests/1/testResults.xml?sv=2019-07-07&se=2021-10-27T21%3A20%3A15Z&sr=c&sp=rl&sig=l6x81ojLuccAHXezeNAnngaxlFWwA%2FvquAUqBhREPyM%3D

https://github.com/dotnet/runtime/pull/59503

cc @steveisok

**Comment by pavelsavara** [comment] 2023-03-13 15:34
Duplicate of https://github.com/dotnet/runtime/issues/60585

**Closed by pavelsavara** 2023-03-13 15:34 UTC
Labels: area-System.Drawing, os-tvos
