### ISSUE TITLE
Add System.Net.Http.JsonContent for System.Net.Http.HttpClient

### ISSUE THREAD

**Issue by GitAntoinee** [dotnet/runtime#1754] opened 2020-01-15 09:46 UTC
Recently, the namespace `System.Text.Json` is added, it serialize / deserialize json.
I am working a lot with json and `System.Net.Http.HttpClient`. And I am bored to always have to do è `new StringContent(JsonSerializer.Serialize(content))`.
A new class `System.Net.Http.JsonContent` who extend `System.Net.Http.HttpContent` or `System.Net.Http.StringContent` is a good idea.

**Comment by GitAntoinee** [comment] 2020-01-15 09:46
I'll use it like `new JsonContent(content)`

**Comment by GitAntoinee** [comment] 2020-01-15 10:07
It could also automatically set the `Content-Type` header to `application/json`

**Comment by scalablecory** [comment] 2020-01-15 15:39
It isn't finalized but we've got an internal group looking at this right now. CC @terrajobst @rynowak

**Comment by mariusGundersen** [comment] 2020-01-31 13:18
This is something I'm forced to implement in almost all my applications, usually like this:

```csharp
public class JsonContent : StringContent
    {
        public JsonContent(object data) : base(JsonSerializer.Serialize(data), Encoding.UTF8, "application/json")
        {
        }

        public JsonContent(object data, JsonSerializerOptions options) : base(JsonSerializer.Serialize(data, options), Encoding.UTF8, "application/json")
        {
        }
    }
```

**Comment by karelz** [comment] 2020-02-28 02:51
Duplicate of #32937

**Closed by karelz** 2020-02-28 02:51 UTC
Labels: api-suggestion, area-System.Net.Http
