### ISSUE TITLE
System.Diagnostics.DiagnosticSource Causing Error Evaluating the function timedout

### ISSUE THREAD

**Issue by b3hdad** [dotnet/runtime#44503] opened 2020-11-11 01:30 UTC
### Description
When I upgrade the package System.Diagnostics.DiagnosticSource from 4.7.1 to 5.0.0, I get the error saying:

Evaluating the function 'System.Diagnostics.TraceInternal.Listeners.get' timedout and needed to be aborted in a unsafe way. This may have corrupted the target process.

I undertand that [this page](https://docs.microsoft.com/en-us/visualstudio/debugger/error-evaluating-the-function-function-timed-out-and-needed-to-be-aborted-in-an-unsafe-way?view=vs-2019) shows how to disable the error but I still thought report it.

Currently I have stopped upgrading this package. Thank you for following up.

### Configuration

.Net Framework 4.8
Windows 10
x64

**Comment by b3hdad** [comment] 2020-11-11 22:50
Just wanted to add a bit more to this. I tried step 3, in the [workaround link](https://docs.microsoft.com/en-us/visualstudio/debugger/error-evaluating-the-function-function-timed-out-and-needed-to-be-aborted-in-an-unsafe-way?view=vs-2019) and still get the pop up error when I run the project. Only step 4 seems to prevent this error.

**Comment by tarekgh** [comment] 2020-11-11 22:59
CC @noahfalk

**Comment by tommcdon** [comment] 2020-11-13 08:23
@b3hdad To investigate help us investigate the expression evaluation timeout, it would be useful if you could send us a dump of the debuggee and debugger when the timeout occurs. These dumps can be automatically collected by enabling a VS specific regkey.

From an admin command prompt (while VS is closed), navigate to the Common7\IDE folder under your VS installation and run:

vsregedit set local HKCU AD7Metrics\Engine\{FB0D4648-F776-4980-95F8-BB7F36EBC1EE} FuncEvalAbortLoggingLevel dword 1
This should cause dumps of the debugger and the debuggee to be created in your temp directory, and if you share those dumps with us we can use them to investigate why the timeout is occurring. The dump collection can be disabled by rerunning the same command, but using "dword 0" instead of "dword 1".

One important note: that regkey will only enable dump collection for desktop framework applications. To enable collection for .NET Core applications replace "FB0D4648-F776-4980-95F8-BB7F36EBC1EE" with "2E36F1D4-B23C-435D-AB41-18E608940038"

To send the dumps to us, feel free to open a [Visual studio feedback item](https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019) and then attach the files to it and then send paste a link to the feedback item.

**Comment by fcorbeil** [comment] 2020-11-13 14:35
The problem is related to ApplicationInsightsTraceListener.  Removing it from the web.config "fixes" the problem...
```
<configuration>
  <system.diagnostics>
    <trace autoflush="true" indentsize="0">
      <listeners>
        <add name="myAppInsightsListener" type="Microsoft.ApplicationInsights.TraceListener.ApplicationInsightsTraceListener, Microsoft.ApplicationInsights.TraceListener" />
      </listeners>
    </trace>
  </system.diagnostics>
</configuration>
```

**Comment by b3hdad** [comment] 2020-11-13 21:33
@fcorbeil, yes, thank you, that fixed the issue. Will this affect my application insights? Should I put this back later on?

Also thanks to everyone following it up.

**Comment by fcorbeil** [comment] 2020-11-13 22:02
@b3hdad, I confirm it'll disable your Application Insights...   This is the reason why I added quotation marks on "fixes".

**Comment by b3hdad** [comment] 2020-11-13 22:04
@fcorbeil, I see, thank you. Its early morning here on Saturday. Sorry, missed the quotation marks meaning. :)

**Comment by panuoksala** [comment] 2020-11-17 11:17
Experiencing same problem when updated .NET Framework 4.6.1 project to use the latest AI nuget. Step #4 in the workaround link works for me too.

**Comment by b3hdad** [comment] 2020-11-17 21:42
@panuoksala, will you be able to create the debug information for @tommcdon please? Working in environment subject to some regulations, I may not be able to get permissions soon enough to produce and post what is required.

**Comment by shirhatti** [comment] 2020-11-17 22:20
cc @cijothomas

**Comment by panuoksala** [comment] 2020-11-18 10:57
What those dump should look like?
Got directories called like this after running the debug dia: Report.5918B293-AF6E-4B98-8028-8529BFF53A6F, 5918b293-af6e-4b98-8028-8529bff53a6f.PackageExtraction, VSTelem and VSTelemOut

**Comment by tommcdon** [comment] 2020-11-20 00:41
@panuoksala Whenever an evaluation is aborted a message will shown with the location and name of the dump files.

**Comment by karelkrivanek** [comment] 2020-11-22 22:46
@tommcdon > One important note: that regkey will only enable dump collection for desktop framework applications. To enable collection for .NET Core applications replace "FB0D4648-F776-4980-95F8-BB7F36EBC1EE" with "2E36F1D4-B23C-435D-AB41-18E608940038"

Should there be different guid for webforms?

**Comment by tommcdon** [comment] 2020-11-25 01:16
@karelkrivanek  I believe "FB0D4648-F776-4980-95F8-BB7F36EBC1EE" is the right guid, assuming that webforms is running on .NET Framework 4.x.

**Comment by gavinbarron** [comment] 2020-11-26 01:52
When you say Temp directory do you mean the one at `C:\Windows\Temp`?

I have a .Net 4.7.2 WebApi project (not MVC) that has the same issue and I'm trying to get you some dumps to help diagnose this but can't find the dumps, or they were not created.

**Comment by panuoksala** [comment] 2020-11-26 06:42
I think they are in %temp% folder, but still no idea about the file/folder names.

**Comment by panuoksala** [comment] 2020-11-26 06:49
> @panuoksala Whenever an evaluation is aborted a message will shown with the location and name of the dump files.

This is the message:
![image](https://user-images.githubusercontent.com/15687235/100316979-32f5d800-2fc4-11eb-8bec-c6d6d655ba4f.png)

**Comment by tiaan-lg** [comment] 2020-11-26 08:43
I experienced the issue when I updated Application insights nuget to 2.16 and it auto-updated this nuget to 5.0.0 as a dependency.

I can replicate the issue, but I'm also not sure where the dump files are located

**Comment by gavinbarron** [comment] 2020-11-26 20:42
Not sure who posted and then removed the comment that the dumps are in `%temp%` but thanks to that person I have submitted a dump through the Visual Studio feedback tool.

**Comment by panuoksala** [comment] 2020-11-27 05:47
> Not sure who posted and then removed the comment that the dumps are in `%temp%` but thanks to that person I have submitted a dump through the Visual Studio feedback tool.

It was me. I tried to search for actual filenames, but wasn't able to find them, glad you got it and hopefully we can get this fixed now. I have the same reason for update as @tiaan-lg.

**Comment by tommcdon** [comment] 2020-11-29 02:31
> Not sure who posted and then removed the comment that the dumps are in `%temp%` but thanks to that person I have submitted a dump through the Visual Studio feedback tool.

Thanks! Would it be possible to share a link to the community item?

For others commenting on the location of the dump.  VS should show a dialog similar to this which contains the path to the dump:

![image](https://user-images.githubusercontent.com/12520929/100530385-3c3e9a80-31a6-11eb-814b-a74bbe5035de.png)

**Comment by gavinbarron** [comment] 2020-11-29 05:16
Here's the link: https://developercommunity2.visualstudio.com/t/Upgrading-to-SystemDiagnosticsDiagnost/1270524?port=1025&fsid=248584ff-4927-4143-a95c-37d3cd710d93&entry=myfeedback

FWIW: I didn't get the dialog you're showing here @tommcdon, I got the dialog that @panuoksala shows above.

**Comment by tommcdon** [comment] 2020-12-02 19:12
> Here's the link: https://developercommunity2.visualstudio.com/t/Upgrading-to-SystemDiagnosticsDiagnost/1270524?port=1025&fsid=248584ff-4927-4143-a95c-37d3cd710d93&entry=myfeedback
> 
> FWIW: I didn't get the dialog you're showing here @tommcdon, I got the dialog that @panuoksala shows above.

Thanks for opening the community issue!  Unfortunately it doesn't have the dump of the debuggee (iisexpress.exe or dotnet.exe).  When setting the reg key, 1) double check that the curly braces are around the guid, 2) vsregedit is running in the right instance of VS (if you have multiple installations), 3) try closing VS first, run vsregedit, then restart VS.  

```vsregedit set local HKCU AD7Metrics\Engine\{FB0D4648-F776-4980-95F8-BB7F36EBC1EE} FuncEvalAbortLoggingLevel dword 1```

Alternatively, if there is a small, reproducible test project, please feel free to send that along.

**Comment by fcorbeil** [comment] 2020-12-31 13:43
This issue prevents me from doing the following updates :

Microsoft.Extensions.Logging.3.1.10 -> Microsoft.Extensions.Logging.5.0.0
Microsoft.ApplicationInsights.Web.2.15.0 -> Microsoft.ApplicationInsights.Web.2.16.0
Microsoft.ApplicationInsights.WindowsServer.2.15.0 -> Microsoft.ApplicationInsights.WindowsServer.2.16.0
Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.2.15.0 -> Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.2.16.0
Microsoft.ApplicationInsights.TraceListener.2.15.0 -> Microsoft.ApplicationInsights.TraceListener.2.16.0
Microsoft.ApplicationInsights.PerfCounterCollector.2.15.0 -> Microsoft.ApplicationInsights.PerfCounterCollector.2.16.0
Microsoft.ApplicationInsights.DependencyCollector.2.15.0 -> Microsoft.ApplicationInsights.DependencyCollector.2.16.0
Microsoft.ApplicationInsights.2.15.0 -> Microsoft.ApplicationInsights.2.16.0
System.Diagnostics.DiagnosticSource.4.7.1 -> System.Diagnostics.DiagnosticSource.5.0.0

I will try to generate the dump on my side today.

**Comment by fcorbeil** [comment] 2020-12-31 14:04
I generated the dump and sent it using the "Reconsider" button at https://developercommunity2.visualstudio.com/t/Upgrading-to-SystemDiagnosticsDiagnost/1270524?port=1025&fsid=248584ff-4927-4143-a95c-37d3cd710d93&entry=myfeedback.

![image](https://user-images.githubusercontent.com/13508843/103413217-98e6f980-4b46-11eb-8b4c-52772c4486ce.png)

**Comment by fcorbeil** [comment] 2020-12-31 14:49
Just let you know I have created a new Visual Studio feedback item : https://developercommunity2.visualstudio.com/t/SystemDiagnosticsTraceInternalListen/1299563?entry=myfeedback

Note 1 : I did this because sending a "Reconsider" feedback was done in less than a second with about 1.5GB of dump!?
Note 2 : Sending a new Visual Studio feedback item also took less than a second, I doubt it worked...  :(

**Comment by tommcdon** [comment] 2021-01-04 23:33
> Just let you know I have created a new Visual Studio feedback item : https://developercommunity2.visualstudio.com/t/SystemDiagnosticsTraceInternalListen/1299563?entry=myfeedback

Thank you!  I have received the dumps and we are investigating.

**Comment by parikshitsehgal** [comment] 2021-01-08 05:54
![image](https://user-images.githubusercontent.com/24611079/103979583-11a01400-514c-11eb-9a73-8bca95f797d0.png)
VS 2019 - 4.7.1 - Getting this error after upgrading packages to latest

**Comment by panuoksala** [comment] 2021-01-22 09:03
Still active and dumps are posted.

**Comment by MKGNZ** [comment] 2021-01-25 21:19
> @b3hdad, I confirm it'll disable your Application Insights... This is the reason why I added quotation marks on "fixes".

Still happening but I found out that it is only when debugging.
So I have removed the <listeners> in web.config and then in Web.Realease.config I have:
`    <system.diagnostics>
        <trace autoflush="true" indentsize="0" xdt:Transform="InsertIfMissing">
            <listeners xdt:Transform="InsertIfMissing">
                <add name="myAppInsightsListener" type="Microsoft.ApplicationInsights.TraceListener.ApplicationInsightsTraceListener, Microsoft.ApplicationInsights.TraceListener" xdt:Transform="InsertIfMissing" xdt:Locator="Match(name)"/>
            </listeners>
        </trace>
    </system.diagnostics>
`

**Comment by MKGNZ** [comment] 2021-01-25 21:27
> Just wanted to add a bit more to this. I tried step 3, in the [workaround link](https://docs.microsoft.com/en-us/visualstudio/debugger/error-evaluating-the-function-function-timed-out-and-needed-to-be-aborted-in-an-unsafe-way?view=vs-2019) and still get the pop up error when I run the project. Only step 4 seems to prevent this error.

Step 4 worked for me also but I lost the ability to Debug with "Edit & Continue" and the "Diagnostic Tools". So I removed it from the web.config and I did the above.

**Comment by cijothomas** [comment] 2021-01-25 21:29
Given its only occurring with ApplicationInsights enabled, please report this in https://github.com/Microsoft/ApplicationInsights-dotnet repo too. (ApplicationInsights team already have access to the dumps shared earlier.)

**Comment by panuoksala** [comment] 2021-01-26 05:16
Done https://github.com/microsoft/ApplicationInsights-dotnet/issues/2161

**Comment by Zapnologica** [comment] 2021-02-02 08:28
I am also having this issue, is there any eta on the fix?

**Comment by fcorbeil** [comment] 2021-02-16 14:23
Who is the ApplicationInsights team representative here?

**Comment by vijayrkn** [comment] 2021-02-22 22:12
@cijothomas - Since there is an issue already created on the App Insights SDK GitHub repo with the information, do you need anything else to proceed with this? https://github.com/microsoft/ApplicationInsights-dotnet/issues/2161

We have a developer community issue on the VS side - https://developercommunity2.visualstudio.com/t/SystemDiagnosticsTraceInternalListen/1299563, Should we just dupe it to the SDK issue?

**Comment by vijayrkn** [comment] 2021-03-01 22:04
@cijothomas - Ping on this. Is it okay to close the devcommunity ticket in favor of the sdk issue? microsoft/ApplicationInsights-dotnet#2161

**Comment by cijothomas** [comment] 2021-03-01 22:07
@vijayrkn Yes.

**Closed** 2021-03-23 07:01 UTC
Labels: area-System.Diagnostics.Tracing, needs author feedback, no recent activity
