### ISSUE TITLE
[API Proposal]: Attribute on Types to opt-out of default Serialization/Binding behavior when they implement Collection Interfaces

### ISSUE THREAD

**Issue by fitdev** [dotnet/runtime#61354] opened 2021-11-09 07:15 UTC
### Background and motivation

I have come across at least 2 cases in DotNet 6 where Serialization and Deserialization in `System.Text.Json` as well as `Microsoft.Extensions.Configuration.Binder` were producing incorrect results by treating in a special way types that implement various collection interfaces (`IList<T>` and `IEnumerable<T>`) in my case.

While the current behavior is absolutely fine for most cases, in some situations where user types implement the aforementioned interfaces, this behavior is wrong. For example, if a type implements `IList<T>` but has some _additional public properties_, it will still be serialized by `System.Text.Json` effectively as a `List<T>` without the additional properties.

[My other case](https://github.com/dotnet/runtime/issues/61202) was the incorrect treatment of my custom type by `Microsoft.Extensions.Configuration.Binder` because it implemented  `IEnumerable<T>`, which was fixed fortunately, but still highlights the importance of this issue for other current and future binding / (de)serialization scenarios.

### API Proposal

I cannot recommend anything particular at this point. But ideally an attribute with/without some options would suffice:

```cs
[AttributeUsage(AttributeTargets.Type | AttributeTargets.Module | AttributeTargets.Assembly, AllowMultiple = false, Inherited = true)]
public class OptOutOfDefaultCollectionSerializationAndBindingBehavior : Attribute {

}
```

### API Usage

```C#
[OptOutOfDefaultCollectionSerializationAndBindingBehavior]
public class MyFancyType : IList<string> {

}
```

**Comment by eiriktsarpalis** [comment] 2021-11-09 16:54
Duplicate of #1808.

We likely won't be using an opt-out attribute, instead we'd let users opt in to different converter strategies using the `JsonConverterAttribute`.

**Closed by eiriktsarpalis** 2021-11-09 16:54 UTC
Labels: api-suggestion, area-System.Text.Json, untriaged

**Comment by fitdev** [comment] 2021-11-09 17:22
It's not about just `System.Text.Json` though, as I mentioned at the beginning. It relates to `Microsoft.Extensions.Configuration.Binder` and very likely other binders and serializers too. So having a single attribute that alerts various Binders/Serializers to how types implementing Collection interfaces should be handled may be a better option.

**Comment by eiriktsarpalis** [comment] 2021-11-09 17:35
From the System.Text.Json perspective, we are intentionally not honoring any of the common `System.Runtime.Serialization` attributes, using bespoke attribute declarations instead (cf. #29975). So it's unlikely STJ would honor a new common attribute, and even more unlikely that any of the older serializers would honor it either, given that many of them are relegated to maintenance mode.

**Comment by fitdev** [comment] 2021-11-09 17:38
Right, but there are many common _binding_ scenarios (there was even some talk of unifying binder story between ASP.NET, Configuration, CommandLine, etc., and in there such an attribute, or generalized version of it would still be useful. SO it is not just about Serializers either.
