### ISSUE TITLE
[Perf] Regressions in TryParseInt64

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#56020] opened 2021-07-20 17:29 UTC
### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Baseline | [f280419a07a9445e1c6724e5717b3da7bdc5be7d](https://github.com/dotnet/runtime/commit/f280419a07a9445e1c6724e5717b3da7bdc5be7d)
Compare | [7b19ccefccb4d116a64bf09c9bb1db3dd1df35e8](https://github.com/dotnet/runtime/commit/7b19ccefccb4d116a64bf09c9bb1db3dd1df35e8)
Diff | [Diff](https://github.com/dotnet/runtime/compare/f280419a07a9445e1c6724e5717b3da7bdc5be7d...7b19ccefccb4d116a64bf09c9bb1db3dd1df35e8)

### Regressions in System.Buffers.Text.Tests.Utf8ParserTests

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
[TryParseInt64 - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Buffers.Text.Tests.Utf8ParserTests.TryParseInt64(value%3a%20-9223372036854775808).html>) | 23.23 ns | 27.85 ns | 1.20 | 0.02 | False | | |
[TryParseInt64 - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Buffers.Text.Tests.Utf8ParserTests.TryParseInt64(value%3a%209223372036854775807).html>) | 23.37 ns | 27.23 ns | 1.17 | 0.02 | False | | |
[TryParseUInt64 - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Buffers.Text.Tests.Utf8ParserTests.TryParseUInt64(value%3a%2018446744073709551615).html>) | 16.33 ns | 29.67 ns | 1.82 | 0.06 | True | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_13_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Buffers.Text.Tests.Utf8ParserTests_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_13_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Buffers.Text.Tests.Utf8ParserTests_2.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_13_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Buffers.Text.Tests.Utf8ParserTests_3.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_13_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Buffers.Text.Tests.Utf8ParserTests.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Buffers.Text.Tests.Utf8ParserTests*'
```
<details>

### Payloads

[Baseline](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-f6834c7f-ae24-4251-82d8-3c1f7a16769abf8cf3ad9644579ab/2e2b5ec7-b94c-4c35-92c6-b8160d91d224.zip?sv=2019-07-07&se=2021-08-11T22%3A09%3A53Z&sr=c&sp=rl&sig=Fq8QvGUgAgQem%2FNwEeUNy15PuQOl7F3MWksly54fI2Q%3D>)
[Compare](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-c3a40da4-de8a-495f-aa10-2ce61f79e7e63fa9dd9fe0a4d1aa9/94ca193d-532a-491f-bc48-80fcd1da2b06.zip?sv=2019-07-07&se=2021-08-12T06%3A21%3A27Z&sr=c&sp=rl&sig=TagEPbxsECzquollG9pqOwgk8x%2F6lVIrIAuy6J459KM%3D>)

#### System.Buffers.Text.Tests.Utf8ParserTests.TryParseInt64(value: -9223372036854775808)

```log

```
#### System.Buffers.Text.Tests.Utf8ParserTests.TryParseInt64(value: 9223372036854775807)

```log

```
#### System.Buffers.Text.Tests.Utf8ParserTests.TryParseUInt64(value: 18446744073709551615)

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by DrewScoggins** [comment] 2021-07-20 17:29
Seems related to https://github.com/dotnet/runtime/pull/52423

**Comment by stephentoub** [comment] 2021-07-20 18:02
cc: @GrabYourPitchforks

**Comment by GrabYourPitchforks** [comment] 2021-07-20 21:02
@DrewScoggins Do we know what processor this test was running on? The benchmarks I gave in https://github.com/dotnet/runtime/pull/52423 were from my personal box (Ryzen 3950X), and I saw similar results on my work desktop (6th gen Intel).

If these optimizations ended up being too sensitive to the particular processors I tested against then we can easily revert, no harm done.

**Comment by GrabYourPitchforks** [comment] 2021-07-20 21:08
Another interesting consideration here is that the regression only seems to be for the extremes, where things like overflow checks start to kick in. According to https://github.com/DrewScoggins/performance-2/issues/7394 and https://github.com/DrewScoggins/performance-2/issues/7395 the original PR actually improved performance for more typical inputs.

Still need to understand why the extremes saw a regression here, especially since my own benchmarking doesn't match what our labs are showing. But it makes me feel a bit better about the original PR not being bad across the board.

**Comment by kunalspathak** [comment] 2021-07-22 15:31
Arm64 regression - https://github.com/DrewScoggins/performance-2/issues/7611

**Comment by GrabYourPitchforks** [comment] 2021-07-22 18:09
@DrewScoggins @kunalspathak @stephentoub How important is it that _this particular input_ (`long.MinValue` / `long.MaxValue` / `ulong.MaxValue`) not regress? Per earlier comments this change appears to have benefited the common case where we're parsing more typical numbers, and it's only once we start going down edge cases that the perf lab is flagging things.

On a related note, I've seen numerous times during this release incidents where we mix and match typical and atypical inputs within a single perf benchmark, and while improving typical inputs we regress atypical inputs (see `StringSegment` for some examples, and I know Steve has one coming up in https://github.com/dotnet/runtime/pull/55792). Do we need a mechanism to flag certain test cases as "uncommon" so that the perf infrastructure doesn't auto-file issues if there's a regression in them? Should we consider removing such edge cases from the perf benchmark code entirely?

**Comment by stephentoub** [comment] 2021-07-22 18:41
It's a balancing act.

If we care at all about the edge cases, I think it's still worth having representative examples of them harnessed in the perf tests; if we made parsing long.MaxValue 10,000x times slower, we'd want to know about it and that would likely outweigh other improvements that made most parsing 5% faster, since there are legitimate cases where that value might manifest and be parsed, e.g. when used as a sentinel to indicate data isn't available.

But it seems Levi's change made parsing of common values 10% faster and of less common values up to 2x slower.  If the common values are parsed 10x more frequently, that's a win; if not, it's not.  It'd be helpful to understand what causes the regression to know how much of the spectrum it impacts and why.

**Comment by DrewScoggins** [comment] 2021-07-26 17:26
Yeah, I agree with @stephentoub here. The way that we think about it is we want to make sure that for the tests that we have we file issues when we see real regressions in the product. We intentionally do not make value judgements on the a regression before we file it. The goal being that when a regression occurs we should have a discussion with the area owner so we can understand what the correct response is to the issue. Our goal is not necessarily to ensure that we get back the time lost in a regression, but to weigh the costs and the benefits of the change so that make an informed performance decision.

**Comment by danmoseley** [comment] 2021-09-02 02:32
A regression for unusual inputs is unlikely to meet the bar now.

**Comment by jeffhandley** [comment] 2022-07-09 07:25
Closing this as we concluded we made the right tradeoffs.

**Closed by jeffhandley** 2022-07-09 07:25 UTC
Labels: area-System.Runtime, os-windows, tenet-performance, tenet-performance-benchmarks, arch-x64
