### ISSUE TITLE
TypeLoadException when attempting to create an instance of a struct of particular type

### ISSUE THREAD

**Issue by wienski** [dotnet/runtime#84999] opened 2023-04-18 18:41 UTC
### Description

Consider the following snippet:

```
var x = new A();

public struct A {
    private B<A> Field;
}

public struct B<T> {}
```

Attempting to run this program results in a TypeLoadException.

Note that `T` is a phantom type parameter and `B<A>` depends on `A` in name only.

Changing either `struct` to `class` allows the type to be loaded successfully. However, this is not a satisfactory workaround since it changes memory behaviour.

### Reproduction Steps

```
var x = new A();

public struct A {
    private B<A> Field;
}

public struct B<T> {}
```

### Expected behavior

Instance is successfully created.

Or at least the error is generated at compile time.

### Actual behavior

At runtime, a TypeLoadException is thrown.

### Known Workarounds

The problem does not occur when either of the types is changed to class.

### Configuration

It is indubitably not configuration-specific. Tested with .NET 6 and 7 on Arch Linux.

### Other information

I'm not that familliar with the innards of .NET, but it seems that type loader cannot handle structs that mention themselves since usually they are impossible as they would have infinite size.

However, phantom type parameters allow to create perfectly valid structs whose definitions are recursive, which is probably was not accounted for in the type loader.

**Comment by KeterSCP** [comment] 2023-04-18 19:06
Duplicate of https://github.com/dotnet/runtime/issues/6924 ?

**Comment by lambdageek** [comment] 2023-04-19 16:10
(works with mono.  Repro: `dotnet run --self-contained -p:UseMonoRuntime=true -r osx-arm64`)

**Comment by am11** [comment] 2023-12-16 18:21
> Duplicate of https://github.com/dotnet/runtime/issues/6924 ?

Yes, and it's fixed in .NET 8.

**Closed by am11** 2023-12-16 18:21 UTC
Labels: area-TypeSystem-coreclr
