### ISSUE TITLE
[browser] TensorPrimitivesTests.ConvertToHalf_SpecialValues `-Infinity`

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#92885] opened 2023-10-02 12:34 UTC
### Error Blob

```json
{
  "ErrorMessage": "[FAIL] System.Numerics.Tensors.Tests.TensorPrimitivesTests.ConvertToHalf_SpecialValues",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=424283&view=results

### Reproduction Steps

[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-92871-merge-34417cc5806d46a084/normal-System.Numerics.Tensors.Tests/1/console.c43b761f.log?helixlogtype=result)

```
fail: [FAIL] System.Numerics.Tensors.Tests.TensorPrimitivesTests.ConvertToHalf_SpecialValues(tensorLength: 15)
info: Assert.Equal() Failure
info: Expected: NaN
info: Actual:   -Infinity
info:    at System.Numerics.Tensors.Tests.TensorPrimitivesTests.ConvertToHalf_SpecialValues(Int32 tensorLength)
info:    at System.Object.InvokeStub_TensorPrimitivesTests.ConvertToHalf_SpecialValues(Object , Span`1 )
info:    at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object , BindingFlags , Binder , Object[] , CultureInfo )
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=424283
**Error message validated:** `[FAIL] System.Numerics.Tensors.Tests.TensorPrimitivesTests.ConvertToHalf_SpecialValues`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 10/2/2023 12:36:04 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[425496](https://dev.azure.com/dnceng-public/public/_build/results?buildId=425496)|dotnet/runtime|[normal-System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=425496&view=ms.vss-test-web.build-test-results-tab&runId=9373512&resultId=162338)||
|[425041](https://dev.azure.com/dnceng-public/public/_build/results?buildId=425041)|dotnet/runtime|[normal-System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=425041&view=ms.vss-test-web.build-test-results-tab&runId=9351792&resultId=162338)||
|[424643](https://dev.azure.com/dnceng-public/public/_build/results?buildId=424643)|dotnet/runtime|[normal-System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=424643&view=ms.vss-test-web.build-test-results-tab&runId=9340484&resultId=162338)|dotnet/runtime#92226|
|[424283](https://dev.azure.com/dnceng-public/public/_build/results?buildId=424283)|dotnet/runtime|[normal-System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=424283&view=ms.vss-test-web.build-test-results-tab&runId=9331020&resultId=162338)|dotnet/runtime#92871|
|[424272](https://dev.azure.com/dnceng-public/public/_build/results?buildId=424272)|dotnet/runtime|[normal-System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=424272&view=ms.vss-test-web.build-test-results-tab&runId=9330908&resultId=162338)||
|[423892](https://dev.azure.com/dnceng-public/public/_build/results?buildId=423892)|dotnet/runtime|[normal-System.Numerics.Tensors.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=423892&view=ms.vss-test-web.build-test-results-tab&runId=9322378&resultId=162338)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|6|

**Comment by pavelsavara** [comment] 2023-10-02 12:35
cc @stephentoub

**Comment by stephentoub** [comment] 2023-10-02 12:42
Thanks, @pavelsavara. This test should be deterministic. Is this from a leg that's not normally run during CI, and if so, how do I trigger it?

**Comment by pavelsavara** [comment] 2023-10-02 12:52
It's wasm AOT, you can trigger it with `/azp run runtime-wasm` comment in a PR

I guess our LLVM settings prefer speed over behavioral consistency. 

@vargaz may know more.

**Comment by vargaz** [comment] 2023-10-02 13:45
Can't reproduce this. Is it reproducible on CI ?

**Comment by pavelsavara** [comment] 2023-10-02 13:46
> Can't reproduce this. Is it reproducible on CI ?

Yes, see https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-92871-merge-34417cc5806d46a084/normal-System.Numerics.Tensors.Tests/1/console.c43b761f.log?helixlogtype=result

**Comment by vargaz** [comment] 2023-10-03 01:15
@radekdoulik

**Comment by vargaz** [comment] 2023-10-03 01:19
The generated code is:
```
  %7 = phi float [ 0.000000e+00, %BB5 ], [ 6.552000e+04, %BB4 ]
  %8 = insertelement <4 x float> zeroinitializer, float %7, i32 0
  %9 = shufflevector <4 x float> %8, <4 x float> undef, <4 x i32> zeroinitializer
  %10 = fcmp ule <4 x float> %9, <float 0xFFF8000000000000, float 0xFFF8000000000000, float 0xFFF8000000000000, float 0xFFF8000000000000>
  %11 = select <4 x i1> %10, <4 x float> %9, <4 x float> <float 0xFFF8000000000000, float 0xFFF8000000000000, float 0xFFF8000000000000, float 0xFFF8000000000000>
```

**Comment by SamMonoRT** [comment] 2023-10-03 09:15
Assigning to @radekdoulik for accurate tracking

**Comment by radical** [comment] 2023-10-03 18:07
Opened https://github.com/dotnet/runtime/pull/92953 to disable the test till this gets fixed.

**Closed** 2023-10-17 09:08 UTC
Labels: bug, arch-wasm, disabled-test, in-pr, Known Build Error, area-Codegen-Intrinsics-mono, os-browser
