### ISSUE TITLE
.NET 7: Tiered compilation causes high memory usage and slowdown

### ISSUE THREAD

**Issue by atarz** [dotnet/runtime#73324] opened 2022-08-03 19:23 UTC
Hello, first of all apologies for my bad english. 

As a civil engineer and software developer, we can work with very large unknown numbers in building analysis.

I wanted to test the new gc region in net 7 with a simple loop like the one below. It's not real code but I wanted to see how it would work in LOH.

        for (int i = 0; i < 1000; i++)
            {
                double[] bak = new double[10000000];

                for (int j = 0; j < bak.Length; j++)
                {
                    var tut = bak[j];
                }
            }

dotnet-sdk-7.0.100-rc.1.22378.2-win-x64
ServerGarbageCollection  enable

net 7 is twice as slow as net 6

peak memory on net 6=40-60 mb
peak memory on net 7 =1.2 gb

I follow your work with admiration, thank you very much in advance.

**Comment by mangod9** [comment] 2022-08-03 20:03
we had a recent regression in this with servergc enabled. @mrsharm could you please verify that your latest fix resolves this? Thx!

**Comment by mrsharm** [comment] 2022-08-04 21:41
Hi @atarz, 

I am unable to repro this issue. Could you please provide the commit hash for the runtime version you used i.e., dotnet-sdk-7.0.100-rc.1.22378.2-win-x64? Also, could you please collect a trace with the issue? 

To repro this, I created a console app with the aforementioned code using the bits from the latest main branch of the runtime, enabled server GC and observed the peak working set via Task Manager and it was stagnant on my machine at 25KB. 

Thanks in advance!

**Comment by atarz** [comment] 2022-08-04 23:02
Hi [mrsharm](https://github.com/mrsharm)

•Runtime Version: V 7.0.22.40210

The trace I obtained is attached. I don't have much experience, I hope I succeeded.

I tested it on wpf. Today I tested it in the console application with the last main branch. Nothing changed.

In addition to high memory usage, with or without server GC enabled, net 7 completes the process much slower than net 6.
On my computer, net 7 completes the process in 7.5 seconds and net 6 in 4.7 seconds.

I'm getting similar results on different computers. 

[trace.zip](https://github.com/dotnet/runtime/files/9263831/trace.zip)

**Comment by mrsharm** [comment] 2022-08-11 04:23
Hi @atarz,

I am still taking a look at this issue and have made a couple of observations based on taking a look at your trace and my attempt at repro'ing: 

1. Since we are specifically allocating on the LOH, we aren't compacting and all the GCs are Background GCs which could explain the high increase in memory. 
2. In my repro and the trace provided, I am observing a low GC pause time based on the total duration of the trace implying that the GC : 

![image](https://user-images.githubusercontent.com/68247673/184063647-17fc9e0a-1281-4263-a381-781dea1670e7.png)

My repro comparing .NET 6 and .NET 7: 

![image](https://user-images.githubusercontent.com/68247673/184063527-468f9cae-88b2-42d0-87f6-1582d3095081.png)

3. I am observing pretty comparable numbers between 6 and 7 in terms of: 

1. Allocations 
2. Total GC Pause MSec
3. Max Heap Size 

And a better time in .NET 7 for the % Time Paused for GC'ing.  

4. Taking a look further at the Thread Time Stacks to discern what's consuming the most CPU, I notice that work done on the UI thread that could influence the overall time of the application: 

![image](https://user-images.githubusercontent.com/68247673/184064067-b72f0aad-0d81-4075-a759-463078d07564.png)

To further help with this, could you please provide the following: 

1. A similar trace for the baseline i.e. for your repro for .NET 6. 
2. Any information about any other GC configurations you are running for both the .NET 6 and .NET 7 run.
    - As an interesting exercise to see if your memory decreases, you can try setting ``COMPLUS_GCConserveMemory`` to 8 or 9 that'll force compaction for the LOH. 
3. Any information about your machine such as the memory. 

Thanks in advance!

**Comment by atarz** [comment] 2022-08-11 08:14
Hi @mrsharm 
I think I found the source of the problem. When I disable TieredCompilation everything goes back to normal and I get faster and less memory usage than net 6.

I've tried this on many different machines. 8 cores 4 cores, 16gb 32gb memory, i7 , i5 i9 processor. I got similar results on all of them.

net 7
TieredCompilation:true
ServerGarbageCollection:true
Max peek memory:2.4 gb
Process time:5.3 second

net 7
TieredCompilation:false
ServerGarbageCollection:true
Max peek memory:23 mb
Process time:2.1 second

net 6  TieredCompilation:true  or false
ServerGarbageCollection:true
Max peek memory:30 mb
Process time:2.9 second

Thank you very much for your trouble.

**Comment by mrsharm** [comment] 2022-08-11 08:17
@atarz, thanks for confirming this is fixed! Will close this issue.

**Comment by jkotas** [comment] 2022-08-11 08:40
It is not expected for tiered compilation to cause regressions in memory usage of this magnitude.

**Comment by En3Tho** [comment] 2022-08-11 08:47
@atarz can you confirm that enabling tiered compilation regresses both wpf and console runs please? Could this be somehow tied to wpf? And how complex was that wpf app you collected traces from?

**Comment by atarz** [comment] 2022-08-11 09:02
Yes, I get the same result in console applications. 
wpf application only consists of the following codes

    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        
        private void Button_Click(object sender, RoutedEventArgs e)
        {
            int baş = Environment.TickCount;

            for (int i = 0; i < 1000; i++)
            {
                double[] bak = new double[10000000];

                for (int j = 0; j < bak.Length; j++)
                {
                    var tut = bak[j];
                }
            }

            this.Title = (Environment.TickCount - baş).ToString();
        }

       
    }

**Comment by En3Tho** [comment] 2022-08-11 11:32
![image](https://user-images.githubusercontent.com/37334640/184124006-f1b26296-89b3-418f-8ffe-725a8d8c186e.png)

Tiered compilation is on the right. Seems like I can''t go further though to see what exactly causes those page faults.

These are from 7.0.100-preview.6.22352.1

**Comment by En3Tho** [comment] 2022-08-11 11:51
``` csharp
using System.Runtime;

Console.WriteLine(GCSettings.IsServerGC);

int baş = Environment.TickCount;

for (int i = 0; i < 1000; i++)
{
    double[] bak = new double[10000000];

    for (int j = 0; j < bak.Length; j++)
    {
        bak[j] = Random.Shared.NextDouble();
    }

    Console.WriteLine(bak[Random.Shared.Next(0, 10000000)]);
}

Console.WriteLine((Environment.TickCount - baş).ToString());


// Not-tiered - 64235
// Tiered - 64609
```

I changed code to this so it does some real work and there is no difference between tiered and non-tiered.
Basically that test above was just showing that Jit is smart and can erase code that does nothing :)

**Comment by En3Tho** [comment] 2022-08-11 11:55
I'm still interested what was happening inside that loop because it still showed about 2.5 seconds of running. So maybe that was some kind of alloc only once and reuse array optimization? I can only wonder.

**Comment by MichalPetryka** [comment] 2022-08-11 12:02
@En3Tho The only issue is that iirc @EgorBo made the JIT remove unused array allocations in .Net 7, which means that .Net 6 should have the same issue. Worth to note that in .Net 6, methods with loops aren't tiered by default, this was changed in .Net 7.

**Comment by En3Tho** [comment] 2022-08-11 12:10
I've rerun with Net6 and got: 

My example:
not tiered: 85203
tiered: 83844
But fun thing is that memory was jumping from 40 mb to 2gb so it consumed much less memory (vs constant almost 5 gigs) but GC pauses were like really noticeable even in console.

Original example:
tiered: 2609
non-tiered: 2562

I can't see difference between tiered and non-tiered with 6.0.302

**Comment by MichalPetryka** [comment] 2022-08-11 12:23
You can enable the .Net 7 behaviour on .Net 6 with `DOTNET_TC_QuickJitForLoops=1` and `DOTNET_TC_OnStackReplacement=1`.

**Comment by En3Tho** [comment] 2022-08-11 12:30
Ii'm unable to see any difference with Net6 with DOTNET_TC_QuickJitForLoops=1 and DOTNET_TC_OnStackReplacement=1 enabled

**Comment by MichalPetryka** [comment] 2022-08-11 12:36
Try also with `DOTNET_TieredCompilation=1` and `DOTNET_ReadyToRun=0`, if it still won't be there then this seems like a .Net 7 regression.

**Comment by atarz** [comment] 2022-08-11 13:23
@En3Tho  I agree with you. I think there are differences due to optimization.

> Basically that test above was just showing that Jit is smart and can erase code that does nothing :)


Here are the results I get when I change the code a little more and make it actually work. 
In this case, the tiered compilation has no effect.

        static int  dispnumber = 20000000;

        double[] tut = new double[dispnumber];
        private void Button_Click(object sender, RoutedEventArgs e)
        {
            int baş = Environment.TickCount;

            for (int i = 0; i < 1000; i++)
            {
                double[] bak = new double[dispnumber];

                for (int j = 0; j < bak.Length; j++)
                {
                    tut[j] = bak[j];
                }
            }

            this.Title = (Environment.TickCount - baş).ToString();
        }

net 7
ServerGarbageCollection:true
time:25 second
peek memory:5gb

net 7
ServerGarbageCollection:false
time:25 second
peek memory:1gb

net 6
ServerGarbageCollection:true
time:54 second
peek memory:2.5gb

net 6
ServerGarbageCollection:false
time:54 second
peek memory:800mb

**Comment by mangod9** [comment] 2022-08-11 18:11
so appears to be a non-issue. Ok to close?

**Closed** 2022-08-11 19:29 UTC
Labels: tenet-performance, area-TieredCompilation-coreclr, untriaged

**Comment by MichalPetryka** [comment] 2022-08-11 20:56
Is double the memory usage with server GC not an issue?

**Comment by EgorBo** [comment] 2022-08-11 21:01
> Is double the memory usage with server GC compared to .Net 6 not an issue?

In Server GC mode, GC reserves "CPU core number * L3 cache size * 3/4" amount of memory by design

**Comment by EgorBo** [comment] 2022-08-11 21:05
@mangod9 was the increased memory usage fixed after we enabled GC regions? Afair I saw a spike in TE benchmarks but didn't see it fixed after

**Comment by mangod9** [comment] 2022-08-11 22:06
hmm.. we havent noticed doubling on the working set for such scenarios. We have seen an increased working set (~60mb) on linux with large memory machines.
