### ISSUE TITLE
Unbox null thrown NullReferenceException

### ISSUE THREAD

**Issue by Cricle** [dotnet/runtime#54079] opened 2021-06-11 19:52 UTC
### Description

When unbox null, always thrown NullReferenceException

### Configuration

|Name|Value|
|:-:|:-:|
|dotnet cli|6.0.100-preview.4.21255.9|
|dotnet runtime|Microsoft.NETCore.App 5.0.6|

### Regression?

Never normal

### Other information

When run this code

```csharp
static void Main(string[] args)
{
  Convert<int>();
}
static T Convert<T>()
{
  return (T)(object)null;
}
```

Always thrown NullReferenceException

<img width="730" alt="a" src="https://user-images.githubusercontent.com/26201412/121741675-70215200-cb31-11eb-87f5-d9d41b45abad.PNG">

**Comment by EgorBo** [comment] 2021-06-11 20:38
Pretty correct behavior, according to the spec III.4.32 unbox – convert boxed value type to its raw form: 
```
System.NullReferenceException is thrown if obj is null and valuetype is a non-nullable value
type
```

**Comment by stephentoub** [comment] 2021-06-11 21:14
Closing as by design. Thanks.

**Closed by stephentoub** 2021-06-11 21:14 UTC
Labels: untriaged
