### ISSUE TITLE
Binary Xml format broken on big-endian machines

### ISSUE THREAD

**Issue by uweigand** [dotnet/runtime#74494] opened 2022-08-24 10:52 UTC
The binary format used by `XmlDictionaryReader` and `XmlDictionaryWriter` is supposed to be always little-endian.

However, the current code does not implement this correctly when running on big-endian systems.   These pre-existing problems were recently exposed by additional and updated test cases added here:
https://github.com/dotnet/runtime/pull/73332  (XmlDictionaryReader)
https://github.com/dotnet/runtime/pull/71478  (XmlDictionaryWriter)

See https://github.com/dotnet/runtime/pull/73332#issuecomment-1218118189 for more details.

@jkotas @Daniel-Svensson

**Comment by StephenMolloy** [comment] 2022-08-24 23:33
@uweigand - I think the fix for this should be pretty straightforward as we do account for endian-ness for most types. The problem is that I don't have any big-endian hardware to test with. We would welcome a PR if you want to create one and verify it on your s390x.

And as @jkotas said in the original comment thread that spurred this issue - serialized representation ("on the wire" if you will) should always be little-endian for DataContractSerializer.

**Comment by uweigand** [comment] 2022-08-25 09:08
> @uweigand - I think the fix for this should be pretty straightforward as we do account for endian-ness for most types. The problem is that I don't have any big-endian hardware to test with. We would welcome a PR if you want to create one and verify it on your s390x.
> 
> And as @jkotas said in the original comment thread that spurred this issue - serialized representation ("on the wire" if you will) should always be little-endian for DataContractSerializer.

@StephenMolloy OK, I'll work on coming up with a PR to fix this, hopefully within the next few days.  Thanks!

**Closed** 2022-09-09 18:38 UTC
Labels: area-Serialization, in-pr
