### ISSUE TITLE
System.Threading.ThreadPools.Tests.ThreadPoolTests.CooperativeBlockingCanCreateThreadsFaster has failed

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#66755] opened 2022-03-17 08:24 UTC
Failing in rolling build: Libraries Test Run release coreclr OSX x64 Release, but not every time. In [20220315.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1664004&view=logs&j=05e92ac1-194e-59cf-664a-fa72d1cdd19b&t=caea1d4b-c90c-5be1-e57d-c4635079c333) and [20220315.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1665195&view=logs&j=05e92ac1-194e-59cf-664a-fa72d1cdd19b&t=caea1d4b-c90c-5be1-e57d-c4635079c333) it failed, then in [20220316.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1666244&view=logs&j=05e92ac1-194e-59cf-664a-fa72d1cdd19b&t=caea1d4b-c90c-5be1-e57d-c4635079c333) it passed and in [20220316.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1667233&view=logs&j=05e92ac1-194e-59cf-664a-fa72d1cdd19b&t=caea1d4b-c90c-5be1-e57d-c4635079c333) it failed again.

The error:
```
Unhandled exception. Xunit.Sdk.TrueException: Assert.True() Failure
Expected: True
Actual:   False
   at System.Threading.ThreadPools.Tests.ThreadPoolTests.<>c.<CooperativeBlockingCanCreateThreadsFaster>b__38_0() in /_/src/libraries/System.Threading.ThreadPool/tests/ThreadPoolTests.cs:line 953
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 94
    System.Threading.ThreadPools.Tests.ThreadPoolTests.CooperativeBlockingCanCreateThreadsFaster [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:
        
        Child exception:
          Xunit.Sdk.TrueException: Assert.True() Failure
        Expected: True
        Actual:   False
        /_/src/libraries/System.Threading.ThreadPool/tests/ThreadPoolTests.cs(953,0): at System.Threading.ThreadPools.Tests.ThreadPoolTests.<>c.<CooperativeBlockingCanCreateThreadsFaster>b__38_0()
        
        Child process:
          System.Threading.ThreadPool.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Threading.ThreadPools.Tests.ThreadPoolTests+<>c Void <CooperativeBlockingCanCreateThreadsFaster>b__38_0()

```

**Comment by ilonatommy** [comment] 2022-03-17 08:25
@kouvel, any ideas what might have caused it?

**Comment by ilonatommy** [comment] 2022-03-18 07:41
@kouvel, thank you for looking into it but even on the https://github.com/dotnet/runtime/pull/66765 the check failed so it seems it's not the fix we're looking for. How else can we get rid of this error?

**Comment by kouvel** [comment] 2022-03-18 07:53
All of those failures appear to be crashes on Mono. Maybe the in-proc event listener is not fully implemented there. I'll file an issue and disable the test on Mono for now.

**Comment by kouvel** [comment] 2022-03-19 04:21
Closing as a duplicate of https://github.com/dotnet/runtime/issues/66852, which seems to be tracking failures of this test elsewhere by a bot

**Closed by kouvel** 2022-03-19 04:21 UTC
Labels: area-System.Threading, in-pr, test-failure
