### ISSUE TITLE
Test failure: System.BadImageFormatException: Could not load file or assembly

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#65646] opened 2022-02-21 01:45 UTC
Run: [runtime-coreclr r2r-extra 20220219.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1623130&view=ms.vss-test-web.build-test-results-tab&runId=45103358&resultId=100137&paneView=debug)

Failed test:
```
R2R windows x64 Checked jitstressregs0x1000 @ Windows.10.Amd64.Open

- JIT\\HardwareIntrinsics\\X86\\Sse3\\LoadDquVector128_r\\LoadDquVector128_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse3\\MoveHighAndDuplicate_r\\MoveHighAndDuplicate_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse3\\LoadAndDuplicateToVector128_r\\LoadAndDuplicateToVector128_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse3\\MoveAndDuplicate_r\\MoveAndDuplicate_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse3\\MoveAndDuplicate_ro\\MoveAndDuplicate_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse3\\Sse3_ro\\Sse3_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse3\\MoveLowAndDuplicate_r\\MoveLowAndDuplicate_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse3\\LoadDquVector128_ro\\LoadDquVector128_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse3\\MoveLowAndDuplicate_ro\\MoveLowAndDuplicate_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse3\\MoveHighAndDuplicate_ro\\MoveHighAndDuplicate_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse3\\Sse3_r\\Sse3_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse3\\LoadAndDuplicateToVector128_ro\\LoadAndDuplicateToVector128_ro.cmd
```
**Error message:**
```
Could Not Find C:\h\w\A56F08E3\w\A2C40920\e\JIT\HardwareIntrinsics\X86\Sse3\LoadDquVector128_r\IL-CG2\composite-r2r.dll
Could Not Find C:\h\w\A56F08E3\w\A2C40920\e\JIT\HardwareIntrinsics\X86\Sse3\LoadDquVector128_r\LoadDquVector128_r.dll.rsp
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'System.Security.Cryptography.Primitives, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The module was expected to contain an assembly manifest.
File name: 'System.Security.Cryptography.Primitives, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
at ILCompiler.CoreRTNameMangler.SanitizeNameWithHash(String literal)
at ILCompiler.CoreRTNameMangler.set_CompilationUnitPrefix(String value)
at ILCompiler.Program.RunSingleCompilation(Dictionary2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary2 unrootedInputFilePaths, HashSet`1 versionBubbleModulesHash, CompilerTypeSystemContext typeSystemContext)
at ILCompiler.Program.Run(String[] args)
at ILCompiler.Program.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\A56F08E3\w\A2C40920\uploads\Reports\JIT.HardwareIntrinsics\X86\Sse3\LoadDquVector128_r\LoadDquVector128_r.output.txt
Raw output:
BEGIN EXECUTION
LoadDquVector128_r.dll
TestLibrary.dll
2 file(s) copied.
Response file: C:\h\w\A56F08E3\w\A2C40920\e\JIT\HardwareIntrinsics\X86\Sse3\LoadDquVector128_r\LoadDquVector128_r.dll.rsp
C:\h\w\A56F08E3\w\A2C40920\e\JIT\HardwareIntrinsics\X86\Sse3\LoadDquVector128_r\IL-CG2\LoadDquVector128_r.dll
-o:C:\h\w\A56F08E3\w\A2C40920\e\JIT\HardwareIntrinsics\X86\Sse3\LoadDquVector128_r\LoadDquVector128_r.dll
--targetarch:x64
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\A56F08E3\p\System..dll
-r:C:\h\w\A56F08E3\p\Microsoft..dll
-r:C:\h\w\A56F08E3\p\mscorlib.dll
-r:C:\h\w\A56F08E3\p\netstandard.dll
-O
" "dotnet" "C:\h\w\A56F08E3\p\crossgen2\crossgen2.dll" @"C:\h\w\A56F08E3\w\A2C40920\e\JIT\HardwareIntrinsics\X86\Sse3\LoadDquVector128_r\LoadDquVector128_r.dll.rsp"   -r:C:\h\w\A56F08E3\w\A2C40920\e\JIT\HardwareIntrinsics\X86\Sse3\LoadDquVector128_r\IL-CG2*.dll"
Crossgen2 failed with exitcode - -532462766
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\A56F08E3\p
C:\h\w\A56F08E3\w\A2C40920\e\JIT\HardwareIntrinsics\X86\Sse3\LoadDquVector128_r\LoadDquVector128_r.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_HardwareIntrinsics._X86_Sse3_LoadDquVector128_r_LoadDquVector128_r_._X86_Sse3_LoadDquVector128_r_LoadDquVector128_r_cmd()
```

**Comment by VincentBu** [comment] 2022-03-04 01:10
Failed again in: [runtime-coreclr outerloop 20220303.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1643242&view=ms.vss-test-web.build-test-results-tab&runId=45433432&resultId=100091&paneView=debug)

Failed test:
```
R2R-CG2 windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open

- JIT\\HardwareIntrinsics\\X86\\Sse3\\Sse3_ro\\Sse3_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse3\\MoveHighAndDuplicate_r\\MoveHighAndDuplicate_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse3\\LoadAndDuplicateToVector128_r\\LoadAndDuplicateToVector128_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse3\\MoveHighAndDuplicate_ro\\MoveHighAndDuplicate_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse3\\LoadAndDuplicateToVector128_ro\\LoadAndDuplicateToVector128_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse3\\MoveAndDuplicate_r\\MoveAndDuplicate_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse3\\MoveLowAndDuplicate_r\\MoveLowAndDuplicate_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse3\\Sse3_r\\Sse3_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse3\\MoveAndDuplicate_ro\\MoveAndDuplicate_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse3\\MoveLowAndDuplicate_ro\\MoveLowAndDuplicate_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse3\\LoadDquVector128_r\\LoadDquVector128_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse3\\LoadDquVector128_ro\\LoadDquVector128_ro.cmd

```
**Error message:**
```
Could Not Find C:\h\w\9D6408CF\w\B1840998\e\JIT\HardwareIntrinsics\X86\Sse3\Sse3_ro\IL-CG2\composite-r2r.dll
Could Not Find C:\h\w\9D6408CF\w\B1840998\e\JIT\HardwareIntrinsics\X86\Sse3\Sse3_ro\Sse3_ro.dll.rsp
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'System.IO.Compression, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. An attempt was made to load a program with an incorrect format.
File name: 'System.IO.Compression, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
at System.Reflection.PortableExecutable.PEReader.DecodeEmbeddedPortablePdbDebugDirectoryData(AbstractMemoryBlock block)
at System.Reflection.PortableExecutable.PEReader.ReadEmbeddedPortablePdbDebugDirectoryData(DebugDirectoryEntry entry)
at Internal.TypeSystem.Ecma.PortablePdbSymbolReader.TryOpenEmbedded(PEReader peReader, MetadataStringDecoder stringDecoder)
at ILCompiler.CompilerTypeSystemContext.AddModule(String filePath, String expectedSimpleName, Boolean useForBinding, ModuleData oldModuleData)
at ILCompiler.CompilerTypeSystemContext.GetOrAddModuleFromPath(String filePath, Boolean useForBinding)
at ILCompiler.Program.Run(String[] args)
at ILCompiler.Program.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\9D6408CF\w\B1840998\uploads\Reports\JIT.HardwareIntrinsics\X86\Sse3\Sse3_ro\Sse3_ro.output.txt
Raw output:
BEGIN EXECUTION
Sse3_ro.dll
TestLibrary.dll
2 file(s) copied.
Response file: C:\h\w\9D6408CF\w\B1840998\e\JIT\HardwareIntrinsics\X86\Sse3\Sse3_ro\Sse3_ro.dll.rsp
C:\h\w\9D6408CF\w\B1840998\e\JIT\HardwareIntrinsics\X86\Sse3\Sse3_ro\IL-CG2\Sse3_ro.dll
-o:C:\h\w\9D6408CF\w\B1840998\e\JIT\HardwareIntrinsics\X86\Sse3\Sse3_ro\Sse3_ro.dll
--targetarch:x64
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\9D6408CF\p\System..dll
-r:C:\h\w\9D6408CF\p\Microsoft..dll
-r:C:\h\w\9D6408CF\p\mscorlib.dll
-r:C:\h\w\9D6408CF\p\netstandard.dll
-O
" "dotnet" "C:\h\w\9D6408CF\p\crossgen2\crossgen2.dll" @"C:\h\w\9D6408CF\w\B1840998\e\JIT\HardwareIntrinsics\X86\Sse3\Sse3_ro\Sse3_ro.dll.rsp"   -r:C:\h\w\9D6408CF\w\B1840998\e\JIT\HardwareIntrinsics\X86\Sse3\Sse3_ro\IL-CG2*.dll"
Crossgen2 failed with exitcode - -532462766
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\9D6408CF\p
C:\h\w\9D6408CF\w\B1840998\e\JIT\HardwareIntrinsics\X86\Sse3\Sse3_ro\Sse3_ro.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_HardwareIntrinsics._X86_Sse3_Sse3_ro_Sse3_ro_._X86_Sse3_Sse3_ro_Sse3_ro_cmd()
```

**Comment by tannergooding** [comment] 2022-03-04 18:20
This looks unrelated to the hardware intrinsics and possibly is a bitness mismatch or something similar.

**Comment by JulieLeeMSFT** [comment] 2022-03-04 19:57
@mangod9 PTAL.

**Comment by tannergooding** [comment] 2022-03-11 17:25
Closed several more dupes that are flagged related to hardware intrinsics.

Notably there are many failures that are completely unrelated to hardware intrinsics as well: https://github.com/dotnet/runtime/issues?q=is%3Aissue+is%3Aopen+BadImageFormatException

**Comment by BruceForstall** [comment] 2022-03-22 21:42
cc @trylek

**Comment by BruceForstall** [comment] 2022-04-27 00:02
@trylek Did this get fixed? Or stop happening? Or is it still happening but nobody's updated this bug?

**Comment by trylek** [comment] 2022-04-27 18:50
I haven't seen any single instance of the bug in the last three weeks, for now I assume it was caused by some temporary infra hiccup, closing as no repro.

**Closed by trylek** 2022-04-27 18:50 UTC
Labels: os-windows, JitStress, arch-x64, area-VM-coreclr, blocking-outerloop
