### ISSUE TITLE
[API Proposal]: Task.WhenEach

### ISSUE THREAD

**Issue by JustNrik** [dotnet/runtime#97355] opened 2024-01-23 00:27 UTC
### Background and motivation

There are cases in which we have multiple tasks, and we have to process them as they complete. Currently, the only approach we have is either `Task.WhenAll`, which requires **all** tasks to complete, and `Task.WhenAny` that will return when any task complete but ignoring the rest unless tracked in other way.

At least myself I have a real use case when I have to process a bunch of algorithms for backtesting, but each backtest can take from few milliseconds or even 15 full seconds depending on how big the algorithm is, so I don't like waiting for them all to finish to begin processing them but instead, process them as they finish.

So I came up with this solution for myself and now I share it as I think it should be part of .net, I'm sure many people at some point may have had encoutered themselves with similar problems and made similar work-arounds.

### API Proposal

```csharp
namespace System.Threading.Tasks;

public partial class Task
{
    // example of implementation, actual implementation would probably be much more elaborated 
    // with actual internal logic that returns the tasks a they complete, kinda like WhenAny 
    // already does but as an asynchronous enumeration
    // There could also be a ordered version if someone has the use-case of needing the tasks to be executed sequentially.
    public static async IAsyncEnumerable<T> WhenEach(this IEnumerable<Task<T>> source)
    {
        var tasks = source.ToList();

        while (tasks.Count > 0)
        {
            var task = await Task.WhenAny(tasks);
            tasks.Remove(task);
            yield return task.Result;
        }
    }
}
```

### API Usage

```csharp
var someExpensiveProcesses = Task.WhenEach(GetTasks());

await foreach (var process in someExpensiveProcesses)
{
    DoStuff(process);
}
```

### Risks

None that I know

**Comment by stephentoub** [comment] 2024-01-23 03:50
Thanks. This is a duplicate of https://github.com/dotnet/runtime/issues/61959.

**Closed by stephentoub** 2024-01-23 03:50 UTC
Labels: api-suggestion, area-System.Threading.Tasks, untriaged
