### ISSUE TITLE
Inconsistent "Error while reaping child" when running multiple instances of Tesseract concurrently in Ubuntu via Process

### ISSUE THREAD

**Issue by 36PopTarts** [dotnet/runtime#33297] opened 2020-03-06 18:39 UTC
I have been wrangling with this issue for a week and a half now. I have a .NET Core 2.1 (I have tried updating to 3.1, but it did not change the behavior) service that runs on an Ubuntu 18.04 VM which calls Tesseract as an external process. This service worked in the past, and I have a working version in production. However, apparently something I have done has caused this to stop working consistently, and I am unable to determine what. The service splits document files and calls Tesseract to OCR the pages individually so that multiple pages can be processed concurrently, then pieces them back together at the end. I have a configurable thread limit on this service -- if I set it to 1, the process takes roughly twice as long but it works. If I set it to 8 (our usual value), I will randomly get this error, which is not handle-able due to being raised by a Process event:
```
dotnet[16899]: Error while reaping child. errno = 10
dotnet[16899]:    at System.Environment.FailFast(System.String, System.Exception)
dotnet[16899]:    at System.Environment.FailFast(System.String)
dotnet[16899]:    at System.Diagnostics.ProcessWaitState.TryReapChild()
dotnet[16899]:    at System.Diagnostics.ProcessWaitState.CheckChildren(Boolean)
dotnet[16899]:    at System.Diagnostics.Process.OnSigChild(Boolean)
```
It could happen on the first or last page of a document. It could happen on a document with 3 blank pages, or a faxed document with 133 pages. There is, from what I can discern, no pattern to this error. I was convinced that this was an error in my code, due to the fact that it is not happening in production, but the more I test this the more it seems like it might be an issue with the way .NET Core handles processes in Unix-based OSes. I'm welcome to any suggestions to change my code or server settings (I don't know very much about server configuration, admittedly) because that would be a lot easier to fix than the alternative.

Here is what the code looks like. 
```
public string AddTextLayerToDocumentFile(string inputFilePath, string outputFilePath, object instanceId, string outputLogPath = null)
        {
            // pages are formatted and written to individual files so they can be fed to Tesseract ...
            // no issues with that part of the code as far as I can tell

            var exceptionCounter = 0L;
            var exceptionalPageNumber = 0;
            Parallel.ForEach(pagePaths, parallelOptions, (pagePath) =>
            {
                var pageNumber = Convert.ToInt32(Path.GetFileNameWithoutExtension(pagePath).Split("_")[1]);

                _pdfProcessor.AddTextLayerToPage(
                    pagePath,
                    instanceId,
                    ref exceptionCounter,
                    ref exceptionalPageNumber);
            });

            if (exceptionCounter > 0L)
                throw new Exception($"[Thread {instanceId}] Unable to process [{exceptionalPageNumber}] of document [{Path.GetDirectoryName(inputFilePath)}].");

            // ... get the list of processed pages and join them back into one, then return the path to that file
        }
```
```
public bool AddTextLayerToPage(string pagePath, object instanceId, ref long exceptionCounter, ref int exceptionalPageNumber)
        {
            // ... variable initialization and filename parsing stuff

            result = ProcessOcrPage(pagePath, pageCounter, instanceId))
            // ... some formatting of the post-OCR'd page
        }
```
```
private bool ProcessOcrPage(string inputPageImagePath, int pageNumber, object instanceId)
        {
            StringBuilder output = new StringBuilder();
            StringBuilder error = new StringBuilder();
            int exitCode;
            string outputPageFilePathWithoutExt = Path.Combine(_fileOps.GetThreadOutputDirectory(instanceId),
                    $"pg_{pageNumber.ToString().PadLeft(3, '0')}");

            var cmdArgs = $"\"{inputPageImagePath}\" \"{outputPageFilePathWithoutExt}\" --oem 1 -l eng pdf";

            _logger.LogStatement($"[Thread {instanceId}.{pageNumber}] Executing the following command:{Environment.NewLine}tesseract {cmdArgs}", LogLevel.Debug);

                try
                {
                    using (var process = new Process())
                    {
                        process.StartInfo = new ProcessStartInfo
                        {
                            WindowStyle = ProcessWindowStyle.Hidden,
                            FileName = "tesseract", 
                            RedirectStandardOutput = true,
                            RedirectStandardError = true,
                            UseShellExecute = false,
                            CreateNoWindow = true,
                            Arguments = cmdArgs
                        };

                        process.StartInfo.EnvironmentVariables.Add("TESSDATA_PREFIX", _config.TesseractTrainingDataPath);
                        if (_config.TesseractThreadLimit > 0)
                            process.StartInfo.EnvironmentVariables.Add("OMP_THREAD_LIMIT", _config.TesseractThreadLimit.ToString());

                        process.OutputDataReceived += (sender, e) =>
                        {
                            if (e.Data != null)
                                output.AppendLine(e.Data);
                        };
                        process.ErrorDataReceived += (sender, e) =>
                        {
                            if (e.Data != null)
                                error.AppendLine(e.Data);
                        };

                        process.Start();

                        process.BeginOutputReadLine();
                        process.BeginErrorReadLine();

                        process.WaitForExit();

                        exitCode = process.ExitCode;
                        _logger.LogStatement($"[Thread {instanceId}.{pageNumber}] Tesseract exited with code [{exitCode}]", LogLevel.Trace, nameof(ProcessOcrPage));

                        var standardOut = output.ToString();
                        var standardErr = error.ToString();
                        if (!string.IsNullOrEmpty(standardOut))
                            _logger.LogStatement($"[Thread {instanceId}.{pageNumber}] Tesseract stdOut:\n{standardOut}", LogLevel.Debug, nameof(ProcessOcrPage));
                        if (!string.IsNullOrEmpty(standardErr))
                            _logger.LogStatement($"[Thread {instanceId}.{pageNumber}] Tesseract stdErr:\n{standardErr}", LogLevel.Debug, nameof(ProcessOcrPage));

                        process.Close();

                        return exitCode == 0 ? true : false;
                    }
                }
            catch (Exception e)
                {
                    _logger.LogException(e, instanceId);

                    return false;
                }
            }
        }
```

**Comment by freddyrios** [comment] 2021-02-05 09:37
@36PopTarts did you find any work arounds for this?

I faced similar running unrelated simple commands from different threads on a pi. I will likely do a single child process at a time and move on, but it would be great not to have such limitations.

I also think this looks like a bug in how processes are handled, but one that might be caused by limitations down the stack. Here is a python bug where they talk a lot about an issue that looks very similar: https://bugs.python.org/issue1731717

**Comment by amsoedal** [comment] 2021-02-05 15:36
Running into this issue as well. Would be interested in a fix and/or workaround

**Comment by freddyrios** [comment] 2021-02-09 13:21
@amsoedal I ended up making sure we don't run processes in parallel.

Not just that, as I first tried with a lock() around the whole method running the child process. Even that was not enough, had to set it so that the next process starts after 10+ ms from the previous process's exit.

**Comment by freddyrios** [comment] 2021-02-09 14:15
@amsoedal if it helps, you can check the linked PR above for how I worked around the issue in our case. Specifically changes to DULutil.

**Comment by amsoedal** [comment] 2021-02-09 14:20
@freddyrios thanks! I'll see if we can try this approach. Much appreciated (y)

**Comment by freddyrios** [comment] 2021-02-19 09:05
@amsoedal did you end up trying it? 

When upgrading to dotnet 5 we had increase the delay to 20+ms as the 10+ms was no longer enough. Probably something got faster :D

**Comment by tmds** [comment] 2021-02-19 16:33
How can I reproduce this issue?
Does it happen on .NET 5?

**Comment by freddyrios** [comment] 2021-02-19 16:41
@tmds yes, it happens on .net 5. I am using a self contained - single file deployed application deployed to a raspberry pi's with raspbian lite.

Unfortunately I don't have an isolated reprod right now, but if it is about to get attention I could look into attempting to isolate a reprod. Specially because although the code we have to run the child processes is open source for my case is OSS, the deployments we run tend to have much more than that.

**Comment by tmds** [comment] 2021-02-22 08:44
@freddyrios can you trace your program as follows until it terminates with the `Error while reaping child. errno = 10` message?

```
$ strace -qq -f -e wait4,waitpid,waitid,execve <app commandline>
```

If we look at something simple like:
```cs
Process p = Process.Start("echo", "hello world");
p.WaitForExit();
```
The output of strace is this:
```
$ strace -qq -f -e wait4,waitpid,waitid,execve bin/Debug/net5.0/console 
execve("bin/Debug/net5.0/console", ["bin/Debug/net5.0/console"], 0x7fff2c1da2d0 /* 60 vars */) = 0
[pid 48698] execve("/usr/bin/echo", ["echo", "hello", "world"], 0x55671acb2250 /* 60 vars */) = 0
hello world
[pid 48688] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=48698, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
[pid 48697] waitid(P_ALL, 0, {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=48698, si_uid=1000, si_status=0, si_utime=0, si_stime=0}, WNOHANG|WEXITED|WNOWAIT, NULL) = 0
[pid 48697] wait4(48698, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], WNOHANG, NULL) = 48698
[pid 48697] waitid(P_ALL, 0, 0x7fa1951b5c70, WNOHANG|WEXITED|WNOWAIT, NULL) = -1 ECHILD (No child processes)
```
You can see the child process being started (`execve`) with the pid 48698.
When it exits there is a `SIGCHLD`, and .NET goes looking for any child that terminated using `waitid`.
When a child is found (`waitid` returns `0`, child pid in `si_pid`), then it reaps the process using `wait4`.
The final call to `waitid` is .NET checking if there are other children that terminated. There are none (return value is `ECHILD`).

The error message `Error while reaping child. errno = 10` probably means the `wait4` call returns `ECHILD`. We should see that in your trace.

**Comment by freddyrios** [comment] 2021-02-23 08:41
@tmds trying to read it now, but here is the output:

```
execve("./LoopControl", ["./LoopControl"], 0xbebef6d0 /* 22 vars */) = 0
[pid 23587] execve("/bin/bash", ["/bin/bash", "-c", "ls -1a /dev/USB*"], 0xb0902ea8 /* 22 vars */) = 0
[pid 23587] execve("/usr/bin/ls", ["ls", "-1a", "/dev/USB*"], 0x1cd4c40 /* 22 vars */) = 0
[pid 23577] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=23587, si_uid=1000, si_status=2, si_utime=0, si_stime=2} ---
[pid 23586] waitid(P_ALL, 0, {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=23587, si_uid=1000, si_status=2, si_utime=0, si_stime=0}, WNOHANG|WEXITED|WNOWAIT, NULL) = 0
[pid 23586] wait4(23587, [{WIFEXITED(s) && WEXITSTATUS(s) == 2}], WNOHANG, NULL) = 23587
[pid 23586] waitid(P_ALL, 0, 0xab65abf8, WNOHANG|WEXITED|WNOWAIT, NULL) = -1 ECHILD (No child processes)
[pid 23591] execve("/bin/bash", ["/bin/bash", "-c", "vcgencmd measure_temp"], 0xab701ce0 /* 22 vars */) = 0
[pid 23591] execve("/usr/bin/vcgencmd", ["vcgencmd", "measure_temp"], 0x10a0c48 /* 22 vars */) = 0
[pid 23590] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=23591, si_uid=1000, si_status=0, si_utime=0, si_stime=1} ---
[pid 23586] waitid(P_ALL, 0, {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=23591, si_uid=1000, si_status=0, si_utime=0, si_stime=0}, WNOHANG|WEXITED|WNOWAIT, NULL) = 0
[pid 23586] wait4(23591, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], WNOHANG, NULL) = 23591
[pid 23586] waitid(P_ALL, 0, 0xab65abf8, WNOHANG|WEXITED|WNOWAIT, NULL) = -1 ECHILD (No child processes)
[pid 23593] execve("/bin/bash", ["/bin/bash", "-c", "cat /sys/class/thermal/thermal_z"...], 0xab7033b8 /* 22 vars */) = 0
[pid 23593] execve("/usr/bin/cat", ["cat", "/sys/class/thermal/thermal_zone0"...], 0x1e1ec58 /* 22 vars */) = 0
[pid 23577] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=23593, si_uid=1000, si_status=0, si_utime=0, si_stime=1} ---
[pid 23586] waitid(P_ALL, 0, {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=23593, si_uid=1000, si_status=0, si_utime=0, si_stime=0}, WNOHANG|WEXITED|WNOWAIT, NULL) = 0
[pid 23586] wait4(23593, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], WNOHANG, NULL) = 23593
[pid 23586] waitid(P_ALL, 0, 0xab65abf8, WNOHANG|WEXITED|WNOWAIT, NULL) = -1 ECHILD (No child processes)
[pid 23596] execve("/bin/bash", ["/bin/bash", "-c", "vcgencmd measure_temp"], 0xaad05730 /* 23 vars */) = 0
[pid 23596] execve("/usr/bin/vcgencmd", ["vcgencmd", "measure_temp"], 0x9d7cd8 /* 23 vars */) = 0
[pid 23577] wait4(-1,  <unfinished ...>
[pid 23597] execve("/usr/bin/gpio", ["gpio", "edge", "4", "both"], 0xbeec86fc /* 22 vars */) = 0
[pid 23590] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=23596, si_uid=1000, si_status=0, si_utime=1, si_stime=2} ---
[pid 23577] <... wait4 resumed> NULL, 0, NULL) = 23596
[pid 23586] waitid(P_ALL, 0, {}, WNOHANG|WEXITED|WNOWAIT, NULL) = 0
gpio: Must be root to run. Program should be suid root. This is an error.
[pid 23584] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=23597, si_uid=1000, si_status=1, si_utime=0, si_stime=0} ---
[pid 23586] waitid(P_ALL, 0, {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=23597, si_uid=1000, si_status=1, si_utime=0, si_stime=0}, WNOHANG|WEXITED|WNOWAIT, NULL) = 0
[pid 23586] wait4(23596, 0xab65ac20, WNOHANG, NULL) = -1 ECHILD (No child processes)
Process terminated. Error while reaping child. errno = 10
   at System.Environment.FailFast(System.String)
   at System.Diagnostics.ProcessWaitState.TryReapChild()
   at System.Diagnostics.ProcessWaitState.CheckChildren(Boolean)
   at System.Diagnostics.Process.OnSigChild(Boolean)
[pid 23586] --- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=23577, si_uid=1000} ---
[pid 23594] +++ killed by SIGABRT +++
[pid 23595] +++ killed by SIGABRT +++
[pid 23590] +++ killed by SIGABRT +++
[pid 23589] +++ killed by SIGABRT +++
[pid 23588] +++ killed by SIGABRT +++
[pid 23585] +++ killed by SIGABRT +++
[pid 23584] +++ killed by SIGABRT +++
[pid 23583] +++ killed by SIGABRT +++
[pid 23582] +++ killed by SIGABRT +++
[pid 23581] +++ killed by SIGABRT +++
[pid 23580] +++ killed by SIGABRT +++
[pid 23579] +++ killed by SIGABRT +++
[pid 23578] +++ killed by SIGABRT +++
[pid 23586] +++ killed by SIGABRT +++
+++ killed by SIGABRT +++
Aborted
```

**Comment by freddyrios** [comment] 2021-02-23 08:44
@tmds that weird line from gpio "gpio: Must be root to run. Program should be suid root. This is an error." is from a library we use. Its not in the program output when running normally without the trace, but I can confirm that the line is there also when the program does not crash.

**Comment by freddyrios** [comment] 2021-02-23 09:07
@tmds note sure what it means, but did a few runs and the events leading to the crash look like this:
```
[pid 23596] execve("/bin/bash", ["/bin/bash", "-c", "vcgencmd measure_temp"], 0xaad05730 /* 23 vars */) = 0
[pid 23596] execve("/usr/bin/vcgencmd", ["vcgencmd", "measure_temp"], 0x9d7cd8 /* 23 vars */) = 0
[pid 23577] wait4(-1,  <unfinished ...>
[pid 23597] execve("/usr/bin/gpio", ["gpio", "edge", "4", "both"], 0xbeec86fc /* 22 vars */) = 0
[pid 23590] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=23596, si_uid=1000, si_status=0, si_utime=1, si_stime=2} ---
[pid 23577] <... wait4 resumed> NULL, 0, NULL) = 23596
[pid 23586] waitid(P_ALL, 0, {}, WNOHANG|WEXITED|WNOWAIT, NULL) = 0
gpio: Must be root to run. Program should be suid root. This is an error.
[pid 23584] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=23597, si_uid=1000, si_status=1, si_utime=0, si_stime=0} ---
[pid 23586] waitid(P_ALL, 0, {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=23597, si_uid=1000, si_status=1, si_utime=0, si_stime=0}, WNOHANG|WEXITED|WNOWAIT, NULL) = 0
[pid 23586] wait4(23596, 0xab65ac20, WNOHANG, NULL) = -1 ECHILD (No child processes)
```

The command just before `wait4(-1,  <unfinished ...>` is not always the same, but the gpio command just after seems to be always the gpio. Running the trace with sudo still crashes and does not log the gpio error I mentioned in my last comment. The crash seems to be very time sensitive, so there is a chance gpio is just what happens to run with the right timing in the system I am running the trace on.

My guess something goes wrong with that `wait4(-1,  <unfinished ...>` that on resume picks up the stopped process `<... wait4 resumed> NULL, 0, NULL) = 23596`, and then the process is gone when it checks again later `wait4(23596, 0xab65ac20, WNOHANG, NULL) = -1 ECHILD`. Alternatively it could be this wait without a target: `waitid(P_ALL, 0, {}, WNOHANG|WEXITED|WNOWAIT, NULL) = 0`.

**Comment by freddyrios** [comment] 2021-02-23 10:09
@tmds running that trace has been greatly helpful to get more what's going on.

Here is what was called:
- Our code called into the [GpioPin.RegisterInterruptCallback](https://github.com/unosquare/wiringpi-dotnet/blob/cc941da8989223a880b2e7a4d4b1e98489e05d0c/src/Unosquare.WiringPi/GpioPin.cs#L614-L640) from [Unosquare.WiringPI library](https://github.com/WiringPi/WiringPi). We used Unosquare's high level APIs with inocent looking code:
                Pi.Init<BootstrapWiringPi>();
                _pin = Pi.Gpio[P1.Pin07];
                _pin.PinMode = GpioPinDriveMode.Input;
                _pin.RegisterInterruptCallback(EdgeDetection.FallingEdge, MyCallback);
- The above calls into [wiringPiISR](https://github.com/WiringPi/WiringPi/blob/e9821abdb4b4fe46a2ea9243471d339435fa7bde/wiringPi/wiringPi.c#L1993-L2081) from [wiringPi](https://github.com/WiringPi/WiringPi). Note I am using the official build rather than the unofficial mirror, but I can't see how that area is not basically the same.
- The above runs some processes and calls `wait (NULL)`.

Should that library be doing that wait differently and that's causing the crash? Or is more like an unsupported mix of natively ran child processes with .net's started/tracked child processes? 

@amsoedal, @36PopTarts you might want to run the trace like I did, as chances are you have something different.

**Comment by tmds** [comment] 2021-02-23 15:09
> Should that library be doing that wait differently and that's causing the crash? Or is more like an unsupported mix of natively ran child processes with .net's started/tracked child processes?

Yes, the native library reaps a child process that was started by .NET, and .NET doesn't like that.

The native library can wait for the specific child it started using `waitpid` (instead of `wait`).

.NET won't reap the child processes started by the native library.

**Comment by freddyrios** [comment] 2021-02-24 07:15
@tmds thanks again, the input not only helped us solve the real root cause for our case but also ended as a PR to another OSS project: https://github.com/WiringPi/WiringPi/pull/101.

**Comment by tmds** [comment] 2021-02-24 12:18
@freddyrios great! you're welcome.

@amsoedal @36PopTarts are you still running into this issue?

**Comment by tmds** [comment] 2021-03-11 09:32
@adamsitnik @eiriktsarpalis there are no more cases to investigate, we can close this issue.

**Comment by amsoedal** [comment] 2021-03-11 12:48
@tmds the above helped us get unblocked also (we were also using waitpid to reap processes started by .NET). Thanks!

**Comment by adamsitnik** [comment] 2021-03-12 07:44
@tmds thank you!

**Closed by adamsitnik** 2021-03-12 07:44 UTC
Labels: area-System.Diagnostics.Process
