### ISSUE TITLE
api container is getting shut down

### ISSUE THREAD

**Issue by bilalmalik777** [dotnet/runtime#49579] opened 2021-03-13 14:38 UTC
API container is shut down after every some days, I have no idea why it is getting shut down. I also attached the logs in the issue please help me to sort out the problem. Api is developed in dotnet core 3.1 and running over ubuntu in docker
[_api_logs(1).txt](https://github.com/dotnet/runtime/files/6134954/_api_logs.1.txt)

**Comment by danmoseley** [comment] 2021-03-13 15:24
The log you attached seems to be a bunch of queries, was that what you intended?
Can you give more info, are you seeing your dotnet process suddenly exit?

**Comment by bilalmalik777** [comment] 2021-03-13 15:30
Yes i see container in exit state.To up the container again, i have to completely remove the containe and then i run the docker-compse up command to up the container.This time i only have these logs. Please let me know if you need more information

**Comment by davidfowl** [comment] 2021-03-14 16:03
I see this at the bottom of the logs:

```
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]

      Executed action TT.Core.Api.Controllers.TelemetryController.GetEquipmentTrend (TT.Core.Api) in 107.5897ms

info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]

      Executed endpoint 'TT.Core.Api.Controllers.TelemetryController.GetEquipmentTrend (TT.Core.Api)'

info: Microsoft.AspNetCore.Hosting.Diagnostics[2]

      Request finished in 114.3733ms 200 application/json; charset=utf-8

info: Microsoft.Hosting.Lifetime[0]

      Application is shutting down...
```

Does anything in your app trigger app shutdown? Is anything triggering a SIGTERM on the container causing it to shutdown? Can you reproduce this consistently?

**Comment by bilalmalik777** [comment] 2021-03-15 18:58
no, I cannot reproduce it consistently, it happens randomly. Neither I have any idea how to reproduce nor when the app shutdown. Even it is running without the container over iis perfectly.  There are some other containers out which some are webjobs and two are portals, nothing happens to these containers.

**Comment by davidfowl** [comment] 2021-03-16 16:08
You should be able to do something like this:

```C#
namespace WebApplication41
{
    public class Startup
    {
        // ... Stuff here

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env, IHostApplicationLifetime lifetime)
        {
            lifetime.ApplicationStopping.Register(() =>
            {
                Console.WriteLine(Environment.StackTrace);
            });

            // ... Stuff here
        }
    }
}
```

That will dump out the stack trace for who is calling StopApplication. Here's what it looks like for CTRL+C:

````
at System.Environment.get_StackTrace()
   at WebApplication41.Startup.<>c.<Configure>b__1_0() in C:\Users\david\source\repos\WebApplication41\WebApplication41\Startup.cs:line 26
   at System.Threading.CancellationToken.<>c.<Register>b__12_0(Object obj)
   at System.Threading.CancellationTokenSource.Invoke(Delegate d, Object state, CancellationTokenSource source)
   at System.Threading.CancellationTokenSource.CallbackNode.<>c.<ExecuteCallback>b__9_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.CancellationTokenSource.CallbackNode.ExecuteCallback()
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at System.Threading.CancellationTokenSource.NotifyCancellation(Boolean throwOnFirstException)
   at System.Threading.CancellationTokenSource.Cancel(Boolean throwOnFirstException)
   at Microsoft.Extensions.Hosting.Internal.ApplicationLifetime.StopApplication()
   at Microsoft.Extensions.Hosting.Internal.ConsoleLifetime.OnCancelKeyPress(Object sender, ConsoleCancelEventArgs e)
   at System.Console.HandleBreakEvent(ConsoleSpecialKey controlKey)
   at System.ConsolePal.ControlCHandlerRegistrar.BreakEvent(Int32 controlType)
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
````

Try running with that in production and checking the logs when shutdown happens and it should give some clues.

**Comment by davidfowl** [comment] 2021-03-16 16:09
You might want to change the Console.WriteLine to a call into the logging system (whatever you're capturing).

**Comment by bilalmalik777** [comment] 2021-03-17 11:59
i have deployed the container with these changes, once reproduce, I will share with you here

**Comment by sathish-akasapu** [comment] 2021-11-10 05:17
Hi @bilalmalik777 , did you find any solution to this issue.

As I am also facing same issue. I have hosted a dotnet core api with nginx as reverse proxy and used docker compose. the application runs fine for some days and shuts down automatically which I can see in the logs.

Any help would be great!

**Comment by davidfowl** [comment] 2021-11-10 05:28
Looks like it happened from the outside if you see this stack. Something is killing the process

**Comment by sathish-akasapu** [comment] 2021-11-10 07:49
Ok, may be I will also add that code to record what exactly happening... but for me it took around 45 days to shutdown.

**Comment by bilalmalik777** [comment] 2021-11-10 08:31
@davidfowl  i am using docker-compose as orchestration tool, and there is not such configuration to restart containers,
it happens once in a while. 
@sathish-akasapu still looking for the answer, if you find any solution please share with me

**Comment by hamed-nasrollahi** [comment] 2021-12-17 09:18
I have same issue when I publish ,net core API with docker

**Comment by esune** [comment] 2021-12-17 19:16
I just hit the same issue: container starts fine in k8s (AKS), but gets killed after a short while.

In my case it was due to the `AllowedHosts` and `AllowedOrigins` settings preventing the k8s API to hit the pods and read the health endpoints successfully.

I have not (yet) figured out which hosts I need to set to allow successful communication, but using a wildcard to troubleshoot fixed the issue for me.

**Comment by ericstj** [comment] 2022-01-04 22:02
I believe that everything that folks have shown so far indicates that an external process is closing the running application.  @davidfowl if tracing the process-exit isn't sufficient to identify the cause of the exit can we capture something else?  Would adding more logging hosting help identify the cause or do folks need to look at additional logging outside the process?

**Comment by eerhardt** [comment] 2022-01-04 22:18
The bottom of the stack says `AppContext.OnProcessExit()` is being called. This gets called from the runtime here:

https://github.com/dotnet/runtime/blob/4da6b9a8d55913c0ea560d63590d35dc942425be/src/coreclr/vm/appdomain.cpp#L3954-L3969

Which only gets called from the FinalizerThread when `fQuitFinalizer` is TRUE. The only way that gets set to TRUE is from:

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/coreclr/vm/finalizerthread.h#L51-L54

which is called from

https://github.com/dotnet/runtime/blob/9472bfe8ceb58f8097e48f7e271db8e99903eba1/src/coreclr/vm/ceemain.cpp#L1166-L1267

See also this comment:

https://github.com/dotnet/runtime/blob/9472bfe8ceb58f8097e48f7e271db8e99903eba1/src/coreclr/vm/ceemain.cpp#L1605-L1626

So either `Main` is exiting, or something outside of the process is killing the process

**Comment by davidfowl** [comment] 2022-01-06 18:42
I don't think there's much we can do. My guess is that the orchestrator is shutting the app down via SIGTERM and the causes are completely external to the application (like a failing health check).

**Comment by ericstj** [comment] 2022-01-14 17:38
Closing this since there's not sufficient actionable information.  If anyone can provide more data that identifies the actual problem feel free to open an issue with that.

**Closed by ericstj** 2022-01-14 17:38 UTC
Labels: area-Extensions-Hosting

**Comment by bilalmalik777** [comment] 2022-02-10 12:50
Now, I am facing the same issue with AWS Elastic container service, even there are many background jobs and react web portal is running fine

**Comment by eerhardt** [comment] 2022-02-15 22:21
@bilalmalik777 - unfortunately there isn't anything we can do. You will need to gather some more information in your environment. All signs point to an external process that is closing your app. You need to figure out who is doing that, and why. From inside the .NET process we can't tell who or what is sending SIGTERM.

One idea is to handle SIGTERM yourself in your app and log some information about the current state. See https://github.com/dotnet/runtime/issues/50527#issuecomment-825858901 for some new APIs that were added in .NET 6 to make it easier to handle signals.
