### ISSUE TITLE
VBCodeProvider not working - Operation is not supported on this platform

### ISSUE THREAD

**Issue by Monsterknuddel** [dotnet/runtime#48155] opened 2021-02-11 10:48 UTC
### Description

I want to run VBScript via VB on a .NET 5 project. Trying to call the VBCodeProvider and CompileAssemblyFromSource

Dim vbCompiler As New Microsoft.VisualBasic.VBCodeProvider
Dim compilerParams As New System.CodeDom.Compiler.CompilerParameters
compilerParams.GenerateExecutable = False 
compilerParams.GenerateInMemory = True
compilerParams.IncludeDebugInformation = False

`Call compilerParams.ReferencedAssemblies.Add("mscorlib.dll")
Call compilerParams.ReferencedAssemblies.Add("System.dll")
Call compilerParams.ReferencedAssemblies.Add("System.Data.dll")
Call compilerParams.ReferencedAssemblies.Add("System.Core.dll") ' LINQ support Classes
Call compilerParams.ReferencedAssemblies.Add("System.Linq.dll") ' LINQ Classes
Call compilerParams.ReferencedAssemblies.Add("System.Drawing.dll")
Call compilerParams.ReferencedAssemblies.Add("System.Xml.dll")
Call compilerParams.ReferencedAssemblies.Add("System.Windows.Forms.dll")
Dim cRes As System.CodeDom.Compiler.CompilerResults = vbCompiler.CompileAssemblyFromSource(compilerParams, MyScriptCode)`

CompileAssemblyFromSource is not working. 

ErrorMessage:

System.PlatformNotSupportedException
  HResult=0x80131539
  Message=Operation is not supported on this platform.
  Source=System.CodeDom
  StackTrace:
   at Microsoft.VisualBasic.VBCodeGenerator.FromFileBatch(CompilerParameters options, String[] fileNames)
   at System.CodeDom.Compiler.CodeCompiler.FromSourceBatch(CompilerParameters options, String[] sources)
   at System.CodeDom.Compiler.CodeCompiler.System.CodeDom.Compiler.ICodeCompiler.CompileAssemblyFromSourceBatch(CompilerParameters options, String[] sources)
   at System.CodeDom.Compiler.CodeDomProvider.CompileAssemblyFromSource(CompilerParameters options, String[] sources)
   at WinFormsApp1.Form1.Button1_Click(Object sender, EventArgs e) in C:\Users\chris\source\repos\WinFormsApp1\WinFormsApp1\Form1.vb:line 36
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

### Configuration

Running on .NET 5, Windows 10, Visual Studio 2019

### Regression

It works on .NET Framework, but not on .NET Core or .NET 5

**Comment by stephentoub** [comment] 2021-02-11 14:27
This is by design.  On .NET Framework, CompileAssemblyFromSource shells out to the Visual Basic command-line compiler (vbc.exe), which is included as part of the framework redistributable.  With .NET Core, the compiler is not part of the shared framework, and thus there's nothing always available for the implementation to invoke.  Hence, it throws the PlatformNotSupportedException you're seeing.  There are currently no plans to change that, though there is an open issue tracking it: https://github.com/dotnet/runtime/issues/18768.  Hope that helps; closing as a dup of #18768.

**Closed by stephentoub** 2021-02-11 14:27 UTC
Labels: untriaged
