### ISSUE TITLE
x64-hosted crossgen.exe missing in Microsoft.NETCore.App.Runtime.win-arm64 package

### ISSUE THREAD

**Issue by AntonLapounov** [dotnet/runtime#50979] opened 2021-04-08 23:51 UTC
Might be caused by #49906. @jkoritzinsky
```
D:\workspace\_work\1\s\src\Framework\App.Runtime\src\Microsoft.AspNetCore.App.Runtime.csproj(399,5): error : Could not find crossgen D:\workspace\_work\1\s\.packages\microsoft.netcore.app.runtime.win-arm64\6.0.0-preview.4.21208.6\tools\x64_arm64\crossgen.exe
```

**Comment by sebastienros** [comment] 2021-04-08 23:53
Marking as blocking since aspnet can't ingest new runtimes

**Comment by jkoritzinsky** [comment] 2021-04-08 23:53
I'm investigating now.

**Comment by jkoritzinsky** [comment] 2021-04-09 00:06
This failure is not caused by #49906. The native build still correctly outputs crossgen.exe to the expected location.

**Comment by AntonLapounov** [comment] 2021-04-09 00:09
I just built ARM64 and `artifacts\obj\coreclr\windows.x64.*` and `artifacts\obj\coreclr\Linux.x64.*` directories are completely missing.

**Comment by jkoritzinsky** [comment] 2021-04-09 00:31
I just built `./build.cmd clr.runtime -a arm64` and the cross-built crossgen is outputted to `artifacts/bin/coreclr/windows.arm64.Debug/x64/crossgen.exe`, which is where the cross-targetting crossgen has always been output to.

**Comment by AntonLapounov** [comment] 2021-04-09 00:37
You are right, I do have `artifacts/bin/coreclr/windows.arm64.Debug/x64/crossgen.exe`. I guess the issue is in packaging then. I will try to debug packaging unless you have better ideas.

**Comment by jkoritzinsky** [comment] 2021-04-09 00:44
Packaging was my next thing to look at. Since you've touched it more recently, if you want to take a look that'd be good.

**Comment by AntonLapounov** [comment] 2021-04-09 01:28
@jkoritzinsky Packing the x64-hosted `crossgen.exe` is controlled by `@(CoreCLRCrossTargetFiles)`, which is populated from `$(CoreCLRCrossTargetComponentDir)` directory in `eng\liveBuilds.targets`.  For debug ARM64 build that directory is `artifacts\bin\coreclr\windows.arm64.Debug\x64\sharedFramework\`.  Before the recent changes we had the `crossgen.exe` executable and related DLLs in _both_ of these locations (not sure why):
```
artifacts\bin\coreclr\windows.arm64.Debug\x64\crossgen.exe
artifacts\bin\coreclr\windows.arm64.Debug\x64\sharedFramework\crossgen.exe
```
However, now we have them only at the former location.  If that change was intended, should we remove `'sharedFramework'` from the path for `CoreCLRCrossTargetComponentDir`?
https://github.com/dotnet/runtime/blob/98038888bfb4215a44002b2046eae9ff166087f5/eng/liveBuilds.targets#L65-L66

**Comment by jkoritzinsky** [comment] 2021-04-09 01:41
I did not realize we pulled from the sharedFramework directory. I’ll put out a fix tomorrow to push clrjit and crossgen into the sharedFramework directory even for cross building.

**Comment by AntonLapounov** [comment] 2021-04-09 02:16
FWIW, removing `sharedFramework\` from the path assigned to the `CoreCLRCrossTargetComponentDir` property produced the following error:
```
error NU5100: The assembly 'runtime\x64_arm64\native\jitinterface_x64.dll' is not inside the 'lib' folder and hence it won't be added as a reference when the package is installed into a project. Move it into the 'lib' folder if it needs to be referenced.
```
because the `sharedFramework` subdirectory did not contain `jitinterface_x64.dll`; however, its parent directory does contain that file.

**Closed** 2021-04-10 01:15 UTC
Labels: area-CrossGen/NGEN-coreclr, blocking, in pr, untriaged
