### ISSUE TITLE
JSImportGenerator renders VS completely unusable when making edits in large projects

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#88215] opened 2023-06-29 21:00 UTC
### Description

Thanks to help from @CyrusNajmabadi, we noticed that the JSImportGenerator takes about 80% of the time spent in the IDE. As a result, trying to make edits in very large projects makes VS become effectively unusable, with eg. quick info taking upwards of a minute to even show up at all. You can see the generator in this trace:

![image](https://github.com/dotnet/runtime/assets/10199417/0a97f581-14ca-4622-9bea-62e3afcc8ce3)

You can grab the full ETW trace [here](https://microsofteur-my.sharepoint.com/:u:/g/personal/sergiopedri_microsoft_com/EakGl2SO5VVPvT9ehtlLthgBzjOt6jAR_5dKVqZinHRkYg?e=HwkRpa).

### Repro steps

- Clone https://github.com/terrafx/terrafx.interop.windows
- Open a file (eg. `ComPtr<T>`)
- Make any code edits
- Observe VS taking ages to react

### Regression?

Not entirely sure.

### Configuration

- 17.6.3
- .NET SDK 7.0.304

**Comment by jkoritzinsky** [comment] 2023-06-29 21:03
@Sergio0694 could this have been fixed by https://github.com/dotnet/runtime/pull/84936?

It looks like the code in the trace was removed in that PR.

**Comment by tannergooding** [comment] 2023-06-29 21:10
For `TerraFX.Interop.Windows` building with:
```
7.0.400-preview.23274.1
MSBuild version 17.7.0-preview-23273-06+7d65cb31c for .NET
```

The binlog shows there are 5 default analyzers:
```
Microsoft.Interop.JavaScript.JSImportGenerator
Microsoft.Interop.LibraryImportGenerator
Microsoft.Interop.SourceGeneration
System.Text.Json.SourceGeneration
System.Text.RegularExpressions.Generator
```

Disabling Microsoft.Interop.JavaScript.JSImportGenerator saves a bit over 33% build time (takes `38s` rather than `64s`)
Disabling the others saves no additional build time

**Comment by tannergooding** [comment] 2023-06-29 21:17
Looks like The 7.0.400-preview.23274.1 SDK (which comes with VS 17.7.0 Preview 2) is on v7.0.5

While the stable v7.0.305 SDK is on v7.0.8.

**Comment by tannergooding** [comment] 2023-06-29 21:24
Explicitly targeting:
```
7.0.305
MSBuild version 17.6.3+07e294721 for .NET
```

Makes the end to end build `46s` which is a significant improvement, but there is still a non-trivial overhead to the `JSImportGenerator` and disabling it still saves around `9s` (around 20% of the new build time), bringing it down to `37s`.

Disabling the other 4 source generators brings it down to `34s` so only saves `3s` additional. That's still a significant penalty for the `JSImportGenerator` which is really only used for Blazor scenarios, afaik.

**Comment by jkoritzinsky** [comment] 2023-06-29 21:43
JSImportGenerator is used for any WASM-in-Browser scenarios, Blazor or otherwise. And we don't ship separate ref packs per target, so we don't have a good vehicle to split it out via anyway.

As mentioned on Discord, this might be related to a possible regression in Roslyn that was being discussed around `ISymbol.Name` for named types. Also, the PR #80646 may provide a fix that would avoid this regression due to how it changes how it does the environment calculations. Depending on what a trace shows as the cause, it might be worth backporting that fix.

**Comment by radical** [comment] 2023-07-03 18:50
cc @pavelsavara

**Comment by lewing** [comment] 2024-02-21 05:35
I think this can be closed now @pavelsavara

**Closed** 2024-12-09 17:53 UTC
Labels: tenet-performance, area-System.Runtime.InteropServices.JavaScript, source-generator
