### ISSUE TITLE
Provide a method  to send  PosixSignal to the Process.

### ISSUE THREAD

**Issue by moh-hassan** [dotnet/runtime#99506] opened 2024-03-10 22:33 UTC
There is a new feature in net6 and above that enable handling of  [PosixSignal](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.posixsignal?view=net-8.0)
like:

```
 using (var intHandler = PosixSignalRegistration.Create(PosixSignal.SIGINT, HandleSignal))
 {
     Console.WriteLine("Press Ctrl+C to trigger handler.");
     LongRunning();
 }
 
 void HandleSignal(PosixSignalContext posixSignalContext)
{
    Console.WriteLine($"Received signal: {posixSignalContext.Signal}");
}

```
There is example in stackoverflow (https://stackoverflow.com/a/35809358) that use  mono package to send SIGINT but it is not compatible with net6 PosixSignal.

It is nice if dotnet provide API to send  [SIGINt/SIGTERM/..signal ](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.posixsignal?view=net-8.0)  to the process to enable graceful stopping/shutdown process. 

something like:
```
SendSignal(int processId, PosixSignal signal)

``
The method can be part of Process class.

**Comment by jkotas** [comment] 2024-03-10 23:07
Duplicate of https://github.com/dotnet/runtime/issues/59746

**Comment by jeffhandley** [comment] 2024-03-22 04:35
Closing as duplicate.

**Closed by jeffhandley** 2024-03-22 04:35 UTC
Labels: area-System.Diagnostics.Process, untriaged
