### ISSUE TITLE
[wasm] BrowserHttpHandler to support large/streaming requests via ReadableStream

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#64333] opened 2022-01-26 14:14 UTC
Currently `PostAsync_CancelDuringRequestContentSend_TaskCanceledQuickly` test fails with `OutOfMemoryException`

We should instead allow streaming requests
```js
const stream = new ReadableStream({
  async start(controller) {
    await wait(1000);
    controller.enqueue('This ');
    await wait(1000);
    controller.enqueue('is ');
    await wait(1000);
    controller.enqueue('a ');
    await wait(1000);
    controller.enqueue('slow ');
    await wait(1000);
    controller.enqueue('request.');
    controller.close();
  },
}).pipeThrough(new TextEncoderStream());

fetch(url, {
  method: 'POST',
  headers: { 'Content-Type': 'text/plain' },
  body: stream,
});
```
See https://web.dev/fetch-upload-streaming/

**Comment by campersau** [comment] 2022-01-26 21:09
Might be a duplicate of https://github.com/dotnet/runtime/issues/36634 ?

**Closed** 2022-01-27 08:31 UTC
Labels: arch-wasm, area-System.Net.Http, untriaged
