### ISSUE TITLE
DateTime.ToString -> DateTime.Parse with culture fr-CA throws FormatException : was not recognized as a valid DateTime using fr-CA culture on Linux OS

### ISSUE THREAD

**Issue by CurlyFire** [dotnet/runtime#34594] opened 2020-04-06 14:14 UTC
I replicated those problems on github at 
[https://github.com/CurlyFire/testcultureconvert](url)

I have boiled down the problem to it's simplest form.  In a console app,  I am taking the ToString value of a DateTime and directlty converting it back to a DateTime and I get a format exception.  

I tried 2 different methods:
using the cultureinfo directly in ToString and Parse:
```cs
var cultureInfo = CultureInfo.GetCultureInfo("fr-CA");
var stringRepresentation = DateTime.Now.ToString(cultureInfo);
var date = DateTime.Parse(stringRepresentation, cultureInfo); // THROWS
```

Or setting the DefaultThreadCurrentCulture and DefaultThreadCurrentUICulture:
```cs
var cultureInfo = CultureInfo.GetCultureInfo("fr-CA");
CultureInfo.DefaultThreadCurrentCulture = cultureInfo;
CultureInfo.DefaultThreadCurrentUICulture = cultureInfo;

var stringRepresentation = DateTime.Now.ToString();
var date = DateTime.Parse(stringRepresentation); // THROWS
```

It throws for example FormatException : 'String '2020-04-06 08 h55 min09 s' was not recognized as a valid DateTime.'.

**On Linux:**
sdk 3.1.201 + Ubuntu 18.04 : **Throws**

**On Linux Docker:**
mcr.microsoft.com/dotnet/core/aspnet:3.1-bionic : **Throws**
mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine with icu-libs : **Throws**

**On Windows:**
sdk 3.1.201 + Windows 10 : **Works**

 The kicker is if I execute the exact same code, but from an NUnit TestFixture, the conversion using the cultureinfo directly inToString and Parse passes... huh ?

In this solution there's a Console entry point and an NUnitEntryPoint, both are pointing at the same library that executes the conversions.

Could someone correct this ?  I iterated over all the specific cultures defined, and only fr-CA and a bunch of ar-xx have this problem.  However, I need fr-CA to work :)

.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /home/curlyfire/.dotnet/sdk/3.1.201/

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [/home/curlyfire/.dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.3 [/home/curlyfire/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.3 [/home/curlyfire/.dotnet/shared/Microsoft.NETCore.App]

**Comment by tarekgh** [comment] 2020-04-06 16:23
@CurlyFire this is a duplicate of https://github.com/dotnet/runtime/issues/1340 which we already fixed it in 5.0. Also, there is a way to work around this by passing the format pattern to the DateTime.ToString. Something like:

```C#

var stringRepresentation = DateTime.Now.ToString("HH 'h' mm 'min' ss 's'", cultureInfo);

``` 

Please advise if the workaround is ok to you and if you can try 5.0 too which has the fix. I am closing the issue here but feel free to respond back and I'll be happy to help more as needed. Thanks for reporting the issue.

CC @danmosemsft

**Closed by tarekgh** 2020-04-06 16:23 UTC
Labels: area-System.Globalization, bug

**Comment by CurlyFire** [comment] 2020-04-06 17:03
@tarekgh I tried searching for something similar, but I wasn't sure where to look.  I didn't know dotnet core used that repo (runtime).

However, I can't use this workaround as the problem I'm having is with asp.net core mvc's model binder.  When I bind a model to a razor view with a datetime property and then post back that value to the controller, that date cannot be bound.

I used the following code in startup to setup the localization of my application and therefore setup also the modelbinder's parse method:

```cs
            var cultureInfo = CultureInfo.GetCultureInfo("fr-CA");

            var supportedCultures = new[]
            {
                cultureInfo
            };

            app.UseRequestLocalization(new RequestLocalizationOptions
            {
                DefaultRequestCulture = new RequestCulture("fr-CA"),
                // Formatting numbers, dates, etc.
                SupportedCultures = supportedCultures,
                // UI strings that we have localized.
                SupportedUICultures = supportedCultures
            });
```

Could I override some property in the CultureInfo that is used here ?

**Comment by tarekgh** [comment] 2020-04-06 17:09
> Could I override some property in the CultureInfo that is used here ?

Yes, you can override the default format patterns on CultureInfo.DateTimeFormat. Here is the doc which has some sample https://docs.microsoft.com/en-us/dotnet/api/system.globalization.datetimeformatinfo.longdatepattern?view=netframework-4.8

**Comment by CurlyFire** [comment] 2020-04-06 18:15
@tarekgh I won't be able to use ParseExact, as this code is in the ModelBinder.  So I thought I would override the incorrect LongTimePattern in a custom CultureInfo based on fr-CA and set the DefaultThreadCurrentCulture and DefaultThreadCurrentUICulture to that custom culture in the hopes that I would be able to affect the parsing code of the ModelBinder:

```cs
var cultureInfo = new CultureInfo("fr-CA");
cultureInfo.DateTimeFormat.LongTimePattern = "HH 'h' mm 'min' ss 's'";
CultureInfo.DefaultThreadCurrentCulture = cultureInfo;
CultureInfo.DefaultThreadCurrentUICulture = cultureInfo;

var stringRepresentation = DateTime.Now.ToString();
var date = DateTime.Parse(stringRepresentation);
```
Or

```cs
var cultureInfo = new CultureInfo("fr-CA");
cultureInfo.DateTimeFormat.LongTimePattern = "HH 'h' mm 'min' ss 's'";

var stringRepresentation = DateTime.Now.ToString(cultureInfo);
var date = DateTime.Parse(stringRepresentation, cultureInfo);
```

I can see the stringRepresentation is fixed, however the parse doesn't take into account the fixed LongTimePattern.

Any ideas on how I could make this work with the ModelBinder in an MVC setting ?

Thanks again for all of your help!

**Comment by tarekgh** [comment] 2020-04-06 19:45
@CurlyFire could you please try setting the current culture too and look if this can reflect on ModelBinder?

```C#
CultureInfo.CurrentCulture = cultureInfo;
```

**Comment by CurlyFire** [comment] 2020-04-07 12:31
@tarekgh It didn't have any positive effects.

**Comment by tarekgh** [comment] 2020-04-07 16:52
@CurlyFire is it possible you can format the date with different patterns that make the parser succeed in the ModelBinder? I mean use something like `hh:mm:ss tt` for the long time pattern.

**Comment by tarekgh** [comment] 2020-04-07 17:35
> I tried to build my own docker image using Centos 7, and I don't have the problem anymore. I have no idea why, but I'll take it.

It depends on the ICU version used in the system. I am pretty sure the version used in Centos 7 is different than the one used in Ubuntu 18.04

**Comment by CurlyFire** [comment] 2020-04-08 11:56
@tarekgh I will check what ICU version is used in both systems.  Thanks
