### ISSUE TITLE
Stream.Read - document 0-byte reads

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#89233] opened 2023-07-20 09:29 UTC
`Stream` does not have 0-byte reads documented clearly, which is causing confusion - see #88792

Affected APIs:
- [Stream.Read](https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.read)
- [Stream.ReadAsync](https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.readasync)

**Comment by svick** [comment] 2023-07-20 12:13
I think this is a duplicate of https://github.com/dotnet/dotnet-api-docs/issues/9155.

**Closed** 2023-07-20 12:32 UTC
Labels: documentation, area-System.IO, untriaged
