### ISSUE TITLE
[8.0] Build failure in Workloads-NoWebcil-Wasm.Build.NativeRebuild.Tests.OptimizationFlagChangeTests

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#106663] opened 2024-08-19 21:32 UTC
## Build Information

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=779736
Build error leg or test failing: Workloads-NoWebcil-Wasm.Build.NativeRebuild.Tests.OptimizationFlagChangeTests

## Error Message

```json
{
  "ErrorMessage" : ["WasmApp.Native.targets(388,5): error : Failed to compile /root/helix/work/workitem/e/wbt artifacts/.*/obj/Release/net8.0/browser-wasm/wasm/for-publish/aot-instances.dll.bc"]
  "BuildRetry" : false,
  "ExcludeConsoleLog" : false
}
```

- PR: https://github.com/dotnet/runtime/pull/106502
- Queue: `browser-wasm linux Release WasmBuildTests`
- Job result: https://dev.azure.com/dnceng-public/public/_build/results?buildId=779736&view=logs&j=a5b3a236-4f50-5d87-59f6-074d4cc4b60f&t=ea8f710d-80f2-5ccb-3945-2d3edaadc5f8&l=142
- Log file: https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-pull-106502-merge-9333e26441e44662aa/Workloads-NoWebcil-Wasm.Build.NativeRebuild.Tests.OptimizationFlagChangeTests/1/console.e294f30a.log?helixlogtype=result
- Output:
```
============== DELETING THE BUILDS =============
    Wasm.Build.NativeRebuild.Tests.OptimizationFlagChangeTests.OptimizationFlagChange(buildArgs: BuildArgs { ProjectName = placeholder, Config = Release, AOT = True, ProjectFileContents = placeholder, ExtraBuildArgs =  }, cflags: "", ldflags: "/p:EmccLinkOptimizationFlag=-O0", host: Chrome, id: "5goorc3q_p2h") [FAIL]
       Expected 0 exit code but got 1: /root/helix/work/workitem/e/dotnet-latest/dotnet publish -bl:/root/helix/work/workitem/uploads/xharness-output/logs/5goorc3q_p2h/5goorc3q_p2h-publish.binlog -p:Configuration=Release -nr:false /p:_WasmDevel=false   /p:EmccLinkOptimizationFlag=-O0 
      Standard Output:
      [] MSBuild version 17.8.3+195e7f5a3 for .NET
      []   Determining projects to restore...
      []   All projects are up-to-date for restore.
      []   rebuild_flags_Release -> /root/helix/work/workitem/e/wbt artifacts/5goorc3q_p2h/bin/Release/net8.0/browser-wasm/rebuild_flags_Release.dll
      []   ** MicrosoftNetCoreAppRuntimePackDir : '/root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NETCore.App.Runtime.Mono.browser-wasm/8.0.9'
      []   rebuild_flags_Release -> /root/helix/work/workitem/e/wbt artifacts/5goorc3q_p2h/bin/Release/net8.0/browser-wasm/publish/
      []   rebuild_flags_Release -> /root/helix/work/workitem/e/wbt artifacts/5goorc3q_p2h/bin/Release/net8.0/browser-wasm/rebuild_flags_Release.dll
      []   ** MicrosoftNetCoreAppRuntimePackDir : '/root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NETCore.App.Runtime.Mono.browser-wasm/8.0.9'
      []   rebuild_flags_Release -> /root/helix/work/workitem/e/wbt artifacts/5goorc3q_p2h/bin/Release/net8.0/browser-wasm/publish/
      []   AOT'ing 3 assemblies
      []   Everything is up-to-date, nothing to precompile
      []   Compiling assembly bitcode files with -O0 ...
      []   [1/4] rebuild_flags_Release.dll.bc -> rebuild_flags_Release.dll.o [took 0.191s]
      []   [2/4] System.Runtime.InteropServices.JavaScript.dll.bc -> System.Runtime.InteropServices.JavaScript.dll.o [took 0.405s]
      []   [3/4] System.Private.CoreLib.dll.bc -> System.Private.CoreLib.dll.o [took 14.567s]
      [] /root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/8.0.9/Sdk/WasmApp.Native.targets(388,5): error : Failed to compile /root/helix/work/workitem/e/wbt artifacts/5goorc3q_p2h/obj/Release/net8.0/browser-wasm/wasm/for-publish/aot-instances.dll.bc -> /root/helix/work/workitem/e/wbt artifacts/5goorc3q_p2h/obj/Release/net8.0/browser-wasm/wasm/for-publish/aot-instances.dll.o [/root/helix/work/workitem/e/wbt artifacts/5goorc3q_p2h/rebuild_flags_Release.csproj]
      [] /root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/8.0.9/Sdk/WasmApp.Native.targets(388,5): error : emcc: warning: linker setting ignored during compilation: 'EXPORT_ES6' [-Wunused-command-line-argument] [/root/helix/work/workitem/e/wbt artifacts/5goorc3q_p2h/rebuild_flags_Release.csproj]
      [] /root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/8.0.9/Sdk/WasmApp.Native.targets(388,5): error : Killed [/root/helix/work/workitem/e/wbt artifacts/5goorc3q_p2h/rebuild_flags_Release.csproj]
      [] /root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/8.0.9/Sdk/WasmApp.Native.targets(388,5): error : emcc: error: '/root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NET.Runtime.Emscripten.3.1.34.Sdk.linux-x64/8.0.9/tools/bin/clang++ -target wasm32-unknown-emscripten -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -wasm-enable-sjlj -mllvm -disable-lsr -DEMSCRIPTEN --sysroot=/root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NET.Runtime.Emscripten.3.1.34.Cache.linux-x64/8.0.9/tools/emscripten/cache/sysroot -Xclang -iwithsysroot/include/fakesdl -Xclang -iwithsysroot/include/compat -msimd128 -O0 -fwasm-exceptions -c "/root/helix/work/workitem/e/wbt artifacts/5goorc3q_p2h/obj/Release/net8.0/browser-wasm/wasm/for-publish/aot-instances.dll.bc" -o /tmp/tmp1MP2wI.tmp' failed (returned 137) [took 262.185s] [/root/helix/work/workitem/e/wbt artifacts/5goorc3q_p2h/rebuild_flags_Release.csproj]
      [] 
      [] Workload updates are available. Run `dotnet workload list` for more information.
      
      Stack Trace:
        /_/src/mono/wasm/Wasm.Build.Tests/Common/CommandResult.cs(44,0): at Wasm.Build.Tests.CommandResult.EnsureExitCode(Int32 expectedExitCode, String messagePrefix, Boolean suppressOutput)
        /_/src/mono/wasm/Wasm.Build.Tests/Common/CommandResult.cs(28,0): at Wasm.Build.Tests.CommandResult.EnsureSuccessful(String messagePrefix, Boolean suppressOutput)
        /_/src/mono/wasm/Wasm.Build.Tests/BuildTestBase.cs(165,0): at Wasm.Build.Tests.BuildTestBase.BuildProjectWithoutAssert(String id, String config, BuildProjectOptions buildProjectOptions, String[] extraArgs)
        /_/src/mono/wasm/Wasm.Build.Tests/TestMainJsTestBase.cs(66,0): at Wasm.Build.Tests.TestMainJsTestBase.BuildProject(BuildArgs buildArgs, String id, BuildProjectOptions options)
        /_/src/mono/wasm/Wasm.Build.Tests/NativeRebuildTests/NativeRebuildTestsBase.cs(86,0): at Wasm.Build.NativeRebuild.Tests.NativeRebuildTestsBase.Rebuild(Boolean nativeRelink, Boolean invariant, BuildArgs buildArgs, String id, String extraProperties, String extraBuildArgs, String verbosity)
        /_/src/mono/wasm/Wasm.Build.Tests/NativeRebuildTests/OptimizationFlagChangeTests.cs(63,0): at Wasm.Build.NativeRebuild.Tests.OptimizationFlagChangeTests.OptimizationFlagChange(BuildArgs buildArgs, String cflags, String ldflags, RunHost host, String id)
           at InvokeStub_OptimizationFlagChangeTests.OptimizationFlagChange(Object, Span`1)
           at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
      Output:
        
        ** -------- publish -------- **
        
        Binlog path: /root/helix/work/workitem/uploads/xharness-output/logs/5goorc3q_p2h/5goorc3q_p2h-publish.binlog
        [] Executing (Captured Output) - /root/helix/work/workitem/e/dotnet-latest/dotnet publish -bl:/root/helix/work/workitem/uploads/xharness-output/logs/5goorc3q_p2h/5goorc3q_p2h-publish.binlog -p:Configuration=Release -nr:false /p:_WasmDevel=false  -  in pwd /root/helix/work/workitem/e/wbt artifacts/5goorc3q_p2h
        	[DOTNET_ROOT] = /root/helix/work/workitem/e/dotnet-latest
        	[DOTNET_INSTALL_DIR] = /root/helix/work/workitem/e/dotnet-latest
        	[DOTNET_MULTILEVEL_LOOKUP] = 0
        	[DOTNET_SKIP_FIRST_TIME_EXPERIENCE] = 1
        	[PATH] = /root/helix/work/workitem/e/dotnet-latest:./dotnet-latest:/__w/1/s/artifacts/bin/chromedriver/chromedriver_linux64:/root/helix/work/correlation/dotnet-latest:/root/helix/work/correlation/xharness-cli:/root/helix/work/correlation/dotnet-cli:/root/helix/work/correlation/chrome-linux:/root/helix/work/correlation/chromedriver_linux64:/home/helixbot/.jsvu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        	[EM_WORKAROUND_PYTHON_BUG_34780] = 1
        	[WasmEnableWebCil] = false
        	[NUGET_PACKAGES] = /root/helix/work/workitem/e/wbt artifacts/nuget/5goorc3q_p2h
        [] MSBuild version 17.8.3+195e7f5a3 for .NET
        []   Determining projects to restore...
        []   Restored /root/helix/work/workitem/e/wbt artifacts/5goorc3q_p2h/rebuild_flags_Release.csproj (in 686 ms).
        []   rebuild_flags_Release -> /root/helix/work/workitem/e/wbt artifacts/5goorc3q_p2h/bin/Release/net8.0/browser-wasm/rebuild_flags_Release.dll
        []   ** MicrosoftNetCoreAppRuntimePackDir : '/root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NETCore.App.Runtime.Mono.browser-wasm/8.0.9'
        []   Optimizing assemblies for size. This process might take a while.
        []   rebuild_flags_Release -> /root/helix/work/workitem/e/wbt artifacts/5goorc3q_p2h/bin/Release/net8.0/browser-wasm/publish/
        []   rebuild_flags_Release -> /root/helix/work/workitem/e/wbt artifacts/5goorc3q_p2h/bin/Release/net8.0/browser-wasm/rebuild_flags_Release.dll
        []   ** MicrosoftNetCoreAppRuntimePackDir : '/root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NETCore.App.Runtime.Mono.browser-wasm/8.0.9'
        []   rebuild_flags_Release -> /root/helix/work/workitem/e/wbt artifacts/5goorc3q_p2h/bin/Release/net8.0/browser-wasm/publish/
        []   AOT'ing 3 assemblies
        []   [1/4] rebuild_flags_Release.dll -> rebuild_flags_Release.dll.bc
        []   [2/4] System.Runtime.InteropServices.JavaScript.dll -> System.Runtime.InteropServices.JavaScript.dll.bc
        []   [3/4] System.Private.CoreLib.dll -> System.Private.CoreLib.dll.bc
        []   [4/4] aot-instances.dll -> aot-instances.dll.bc
        []   Compiling native assets with emcc with -Oz. This may take a while ...
        []   [1/3] pinvoke.c -> pinvoke.o [took 0.250s]
        []   [2/3] driver.c -> driver.o [took 0.375s]
        []   [3/3] corebindings.c -> corebindings.o [took 0.183s]
        []   Compiling assembly bitcode files with -O2 ...
        []   [1/4] rebuild_flags_Release.dll.bc -> rebuild_flags_Release.dll.o [took 0.266s]
        []   [2/4] System.Runtime.InteropServices.JavaScript.dll.bc -> System.Runtime.InteropServices.JavaScript.dll.o [took 0.896s]
        []   [3/4] System.Private.CoreLib.dll.bc -> System.Private.CoreLib.dll.o [took 42.563s]
        []   [4/4] aot-instances.dll.bc -> aot-instances.dll.o [took 47.452s]
        []   Linking for initial memory $(EmccInitialHeapSize)=16777216 bytes. Set this msbuild property to change the value.
        []   Linking with emcc with -O2. This may take a while ...
        []   Stripping symbols from dotnet.native.wasm ...
        []   Generated app bundle at /root/helix/work/workitem/e/wbt artifacts/5goorc3q_p2h/bin/Release/net8.0/browser-wasm/AppBundle/
        [] 
        [] Workload updates are available. Run `dotnet workload list` for more information.
        Skipping asserting symbols file
        ============== wasm test-browser =============
        
        ---------- Running with wasm test-browser ---------
```

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

**Comment by ilonatommy** [comment] 2024-08-27 10:10
It never hit anything, I cannot find an error in the pattern, though.

**Comment by jkurdek** [comment] 2024-09-09 11:34
Hit very similar error on Wasm.Build.Tests.SatelliteAssembliesTests.CheckThatSatelliteAssembliesAreNotAOTed


```
   Wasm.Build.Tests: [Long Running Test] 'Wasm.Build.Tests.SatelliteAssembliesTests.CheckThatSatelliteAssembliesAreNotAOTed', Elapsed: 00:02:14
============== DELETING THE BUILDS =============
    Wasm.Build.Tests.SatelliteAssembliesTests.CheckThatSatelliteAssembliesAreNotAOTed(buildArgs: BuildArgs { ProjectName = placeholder, Config = Release, AOT = True, ProjectFileContents = placeholder, ExtraBuildArgs =  }, id: "500pjwur_uxt") [FAIL]
       Expected 0 exit code but got 1: /root/helix/work/workitem/e/dotnet-latest/dotnet publish -bl:/root/helix/work/workitem/uploads/xharness-output/logs/500pjwur_uxt/500pjwur_uxt-publish.binlog -p:Configuration=Release -nr:false  
      Standard Output:
      [] MSBuild version 17.8.3+195e7f5a3 for .NET
      []   Determining projects to restore...
      []   Restored /root/helix/work/workitem/e/wbt artifacts/500pjwur_uxt/check_sat_asm_not_aot.csproj (in 731 ms).
      []   check_sat_asm_not_aot -> /root/helix/work/workitem/e/wbt artifacts/500pjwur_uxt/bin/Release/net8.0/browser-wasm/check_sat_asm_not_aot.dll
      []   ** MicrosoftNetCoreAppRuntimePackDir : '/root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NETCore.App.Runtime.Mono.browser-wasm/8.0.9'
      []   Optimizing assemblies for size. This process might take a while.
      []   check_sat_asm_not_aot -> /root/helix/work/workitem/e/wbt artifacts/500pjwur_uxt/bin/Release/net8.0/browser-wasm/publish/
      []   check_sat_asm_not_aot -> /root/helix/work/workitem/e/wbt artifacts/500pjwur_uxt/bin/Release/net8.0/browser-wasm/check_sat_asm_not_aot.dll
      []   ** MicrosoftNetCoreAppRuntimePackDir : '/root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NETCore.App.Runtime.Mono.browser-wasm/8.0.9'
      []   check_sat_asm_not_aot -> /root/helix/work/workitem/e/wbt artifacts/500pjwur_uxt/bin/Release/net8.0/browser-wasm/publish/
      []   AOT'ing 4 assemblies
      []   [1/5] check_sat_asm_not_aot.dll -> check_sat_asm_not_aot.dll.bc
      []   [2/5] System.Console.dll -> System.Console.dll.bc
      []   [3/5] System.Runtime.InteropServices.JavaScript.dll -> System.Runtime.InteropServices.JavaScript.dll.bc
      []   [4/5] System.Private.CoreLib.dll -> System.Private.CoreLib.dll.bc
      []   [5/5] aot-instances.dll -> aot-instances.dll.bc
      []   Compiling native assets with emcc with -O0. This may take a while ...
      []   [1/3] pinvoke.c -> pinvoke.o [took 0.369s]
      []   [2/3] driver.c -> driver.o [took 0.443s]
      []   [3/3] corebindings.c -> corebindings.o [took 0.178s]
      []   Compiling assembly bitcode files with -O0 ...
      []   [1/5] check_sat_asm_not_aot.dll.bc -> check_sat_asm_not_aot.dll.o [took 0.194s]
      []   [2/5] System.Console.dll.bc -> System.Console.dll.o [took 0.310s]
      []   [3/5] System.Runtime.InteropServices.JavaScript.dll.bc -> System.Runtime.InteropServices.JavaScript.dll.o [took 0.396s]
      []   [4/5] System.Private.CoreLib.dll.bc -> System.Private.CoreLib.dll.o [took 13.814s]
      [] /root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/8.0.9/Sdk/WasmApp.Native.targets(388,5): error : Failed to compile /root/helix/work/workitem/e/wbt artifacts/500pjwur_uxt/obj/Release/net8.0/browser-wasm/wasm/for-publish/aot-instances.dll.bc -> /root/helix/work/workitem/e/wbt artifacts/500pjwur_uxt/obj/Release/net8.0/browser-wasm/wasm/for-publish/aot-instances.dll.o [/root/helix/work/workitem/e/wbt artifacts/500pjwur_uxt/check_sat_asm_not_aot.csproj]
      [] /root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/8.0.9/Sdk/WasmApp.Native.targets(388,5): error : emcc: warning: linker setting ignored during compilation: 'EXPORT_ES6' [-Wunused-command-line-argument] [/root/helix/work/workitem/e/wbt artifacts/500pjwur_uxt/check_sat_asm_not_aot.csproj]
      [] /root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/8.0.9/Sdk/WasmApp.Native.targets(388,5): error : Killed [/root/helix/work/workitem/e/wbt artifacts/500pjwur_uxt/check_sat_asm_not_aot.csproj]
      [] /root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/8.0.9/Sdk/WasmApp.Native.targets(388,5): error : emcc: error: '/root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NET.Runtime.Emscripten.3.1.34.Sdk.linux-x64/8.0.8/tools/bin/clang++ -target wasm32-unknown-emscripten -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -wasm-enable-sjlj -mllvm -disable-lsr -DEMSCRIPTEN --sysroot=/root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NET.Runtime.Emscripten.3.1.34.Cache.linux-x64/8.0.8/tools/emscripten/cache/sysroot -Xclang -iwithsysroot/include/fakesdl -Xclang -iwithsysroot/include/compat -msimd128 -O0 -fwasm-exceptions -c "/root/helix/work/workitem/e/wbt artifacts/500pjwur_uxt/obj/Release/net8.0/browser-wasm/wasm/for-publish/aot-instances.dll.bc" -o /tmp/tmpNbho3X.tmp' failed (returned 137) [took 221.634s] [/root/helix/work/workitem/e/wbt artifacts/500pjwur_uxt/check_sat_asm_not_aot.csproj]
      [] 
      [] Workload updates are available. Run `dotnet workload list` for more information.
      
      Stack Trace:
        /_/src/mono/wasm/Wasm.Build.Tests/Common/CommandResult.cs(44,0): at Wasm.Build.Tests.CommandResult.EnsureExitCode(Int32 expectedExitCode, String messagePrefix, Boolean suppressOutput)
        /_/src/mono/wasm/Wasm.Build.Tests/Common/CommandResult.cs(28,0): at Wasm.Build.Tests.CommandResult.EnsureSuccessful(String messagePrefix, Boolean suppressOutput)
        /_/src/mono/wasm/Wasm.Build.Tests/BuildTestBase.cs(165,0): at Wasm.Build.Tests.BuildTestBase.BuildProjectWithoutAssert(String id, String config, BuildProjectOptions buildProjectOptions, String[] extraArgs)
        /_/src/mono/wasm/Wasm.Build.Tests/TestMainJsTestBase.cs(66,0): at Wasm.Build.Tests.TestMainJsTestBase.BuildProject(BuildArgs buildArgs, String id, BuildProjectOptions options)
        /_/src/mono/wasm/Wasm.Build.Tests/SatelliteAssembliesTests.cs(141,0): at Wasm.Build.Tests.SatelliteAssembliesTests.CheckThatSatelliteAssembliesAreNotAOTed(BuildArgs buildArgs, String id)
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
      Output:
        
        ** -------- publish -------- **
        
        Binlog path: /root/helix/work/workitem/uploads/xharness-output/logs/500pjwur_uxt/500pjwur_uxt-publish.binlog
        [] Executing (Captured Output) - /root/helix/work/workitem/e/dotnet-latest/dotnet publish -bl:/root/helix/work/workitem/uploads/xharness-output/logs/500pjwur_uxt/500pjwur_uxt-publish.binlog -p:Configuration=Release -nr:false   -  in pwd /root/helix/work/workitem/e/wbt artifacts/500pjwur_uxt
        	[DOTNET_ROOT] = /root/helix/work/workitem/e/dotnet-latest
        	[DOTNET_INSTALL_DIR] = /root/helix/work/workitem/e/dotnet-latest
        	[DOTNET_MULTILEVEL_LOOKUP] = 0
        	[DOTNET_SKIP_FIRST_TIME_EXPERIENCE] = 1
        	[PATH] = /root/helix/work/workitem/e/dotnet-latest:./dotnet-latest:/__w/1/s/artifacts/bin/chromedriver/chromedriver_linux64:/root/helix/work/correlation/dotnet-latest:/root/helix/work/correlation/xharness-cli:/root/helix/work/correlation/dotnet-cli:/root/helix/work/correlation/chrome-linux:/root/helix/work/correlation/chromedriver_linux64:/home/helixbot/.jsvu/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        	[EM_WORKAROUND_PYTHON_BUG_34780] = 1
        	[WasmEnableWebCil] = false
        	[NUGET_PACKAGES] = /root/helix/work/workitem/e/wbt artifacts/nuget/500pjwur_uxt
        [] MSBuild version 17.8.3+195e7f5a3 for .NET
        []   Determining projects to restore...
        []   Restored /root/helix/work/workitem/e/wbt artifacts/500pjwur_uxt/check_sat_asm_not_aot.csproj (in 731 ms).
        []   check_sat_asm_not_aot -> /root/helix/work/workitem/e/wbt artifacts/500pjwur_uxt/bin/Release/net8.0/browser-wasm/check_sat_asm_not_aot.dll
        []   ** MicrosoftNetCoreAppRuntimePackDir : '/root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NETCore.App.Runtime.Mono.browser-wasm/8.0.9'
        []   Optimizing assemblies for size. This process might take a while.
        []   check_sat_asm_not_aot -> /root/helix/work/workitem/e/wbt artifacts/500pjwur_uxt/bin/Release/net8.0/browser-wasm/publish/
        []   check_sat_asm_not_aot -> /root/helix/work/workitem/e/wbt artifacts/500pjwur_uxt/bin/Release/net8.0/browser-wasm/check_sat_asm_not_aot.dll
        []   ** MicrosoftNetCoreAppRuntimePackDir : '/root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NETCore.App.Runtime.Mono.browser-wasm/8.0.9'
        []   check_sat_asm_not_aot -> /root/helix/work/workitem/e/wbt artifacts/500pjwur_uxt/bin/Release/net8.0/browser-wasm/publish/
        []   AOT'ing 4 assemblies
        []   [1/5] check_sat_asm_not_aot.dll -> check_sat_asm_not_aot.dll.bc
        []   [2/5] System.Console.dll -> System.Console.dll.bc
        []   [3/5] System.Runtime.InteropServices.JavaScript.dll -> System.Runtime.InteropServices.JavaScript.dll.bc
        []   [4/5] System.Private.CoreLib.dll -> System.Private.CoreLib.dll.bc
        []   [5/5] aot-instances.dll -> aot-instances.dll.bc
        []   Compiling native assets with emcc with -O0. This may take a while ...
        []   [1/3] pinvoke.c -> pinvoke.o [took 0.369s]
        []   [2/3] driver.c -> driver.o [took 0.443s]
        []   [3/3] corebindings.c -> corebindings.o [took 0.178s]
        []   Compiling assembly bitcode files with -O0 ...
        []   [1/5] check_sat_asm_not_aot.dll.bc -> check_sat_asm_not_aot.dll.o [took 0.194s]
        []   [2/5] System.Console.dll.bc -> System.Console.dll.o [took 0.310s]
        []   [3/5] System.Runtime.InteropServices.JavaScript.dll.bc -> System.Runtime.InteropServices.JavaScript.dll.o [took 0.396s]
        []   [4/5] System.Private.CoreLib.dll.bc -> System.Private.CoreLib.dll.o [took 13.814s]
        [] /root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/8.0.9/Sdk/WasmApp.Native.targets(388,5): error : Failed to compile /root/helix/work/workitem/e/wbt artifacts/500pjwur_uxt/obj/Release/net8.0/browser-wasm/wasm/for-publish/aot-instances.dll.bc -> /root/helix/work/workitem/e/wbt artifacts/500pjwur_uxt/obj/Release/net8.0/browser-wasm/wasm/for-publish/aot-instances.dll.o [/root/helix/work/workitem/e/wbt artifacts/500pjwur_uxt/check_sat_asm_not_aot.csproj]
        [] /root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/8.0.9/Sdk/WasmApp.Native.targets(388,5): error : emcc: warning: linker setting ignored during compilation: 'EXPORT_ES6' [-Wunused-command-line-argument] [/root/helix/work/workitem/e/wbt artifacts/500pjwur_uxt/check_sat_asm_not_aot.csproj]
        [] /root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/8.0.9/Sdk/WasmApp.Native.targets(388,5): error : Killed [/root/helix/work/workitem/e/wbt artifacts/500pjwur_uxt/check_sat_asm_not_aot.csproj]
        [] /root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NET.Runtime.WebAssembly.Sdk/8.0.9/Sdk/WasmApp.Native.targets(388,5): error : emcc: error: '/root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NET.Runtime.Emscripten.3.1.34.Sdk.linux-x64/8.0.8/tools/bin/clang++ -target wasm32-unknown-emscripten -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -wasm-enable-sjlj -mllvm -disable-lsr -DEMSCRIPTEN --sysroot=/root/helix/work/workitem/e/dotnet-latest/packs/Microsoft.NET.Runtime.Emscripten.3.1.34.Cache.linux-x64/8.0.8/tools/emscripten/cache/sysroot -Xclang -iwithsysroot/include/fakesdl -Xclang -iwithsysroot/include/compat -msimd128 -O0 -fwasm-exceptions -c "/root/helix/work/workitem/e/wbt artifacts/500pjwur_uxt/obj/Release/net8.0/browser-wasm/wasm/for-publish/aot-instances.dll.bc" -o /tmp/tmpNbho3X.tmp' failed (returned 137) [took 221.634s] [/root/helix/work/workitem/e/wbt artifacts/500pjwur_uxt/check_sat_asm_not_aot.csproj]
        [] 
        [] Workload updates are available. Run `dotnet workload list` for more information.
    Wasm.Build.Tests.SatelliteAssembliesTests.CheckThatSatelliteAssembliesAreNotAOTed(buildArgs: BuildArgs { ProjectName = placeholder, Config = Release, AOT = True, ProjectFileContents = placeholder, ExtraBuildArgs =  }, id: "500pjwur_uxt") [FINISHED] Time: 249.5415096s
  Finished:    Wasm.Build.Tests

```

**Comment by ilonatommy** [comment] 2024-09-09 12:10
It is a duplicate of https://github.com/dotnet/runtime/issues/104827.

**Closed by ilonatommy** 2024-09-09 12:10 UTC
Labels: arch-wasm, os-linux, Known Build Error, area-Workloads, os-browser
