### ISSUE TITLE
Unable to load DLL 'libgdiplus': The specified module could not be found M1 mac

### ISSUE THREAD

**Issue by kssharma9** [dotnet/runtime#63135] opened 2021-12-25 20:35 UTC
### Description

Unhandled exception. System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libgdiplus' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibgdiplus, 1): image not found
   at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.SafeNativeMethods.Gdip.GdipLoadImageFromDelegate_linux(StreamGetHeaderDelegate getHeader, StreamGetBytesDelegate getBytes, StreamPutBytesDelegate putBytes, StreamSeekDelegate doSeek, StreamCloseDelegate close, StreamSizeDelegate size, IntPtr& image)
   at System.Drawing.Image.InitializeFromStream(Stream stream)
   at System.Drawing.Bitmap..ctor(Stream stream, Boolean useIcm)
   at System.Drawing.Bitmap..ctor(Stream stream)

### Reproduction Steps

Code I am working with:
public ActionResult generateCaptcha()
        {
            System.Drawing.FontFamily family = new System.Drawing.FontFamily("Arial");
            CaptchaImage img = new CaptchaImage(150, 50, family);            
            string text = img.CreateRandomText(4) + " " + img.CreateRandomText(3);
            img.SetText(text);
            img.GenerateImage();
            img.Image.SaveAsPng(_env.ContentRootPath + "/uploads/" + HttpContext.Session.Id.ToString() + ".png");
            HttpContext.Session.SetObjectAsJson("captchaText",text);
            return Json(HttpContext.Session.Id.ToString() + ".png?t=" + DateTime.Now.Ticks);
        }

### Expected behavior

The method should return the captcha image file

### Actual behavior

System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libgdiplus' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibgdiplus, 0x0001): tried: 'liblibgdiplus' (no such file), '/usr/local/lib/liblibgdiplus'

### Other information

I tried linking the library but it didn't work:

sudo ln -s /opt/homebrew/Cellar/mono-libgdiplus/6.1/lib/libgdiplus.dylib /usr/local/share/dotnet/shared/Microsoft.NETCore.App/6.0.101

**Comment by EgorBo** [comment] 2021-12-25 23:12
Looks like gdiplus is not available on osx-arm64:
https://github.com/mono/libgdiplus/issues/725
https://github.com/mono/libgdiplus/issues/696
the one you see is likely osx-x64 (rosetta)

**Comment by kssharma9** [comment] 2021-12-25 23:31
Ah okay. Yeah, I am on osx-arm64. Will have to find a workaround. Thanks for the input.

**Comment by EgorBo** [comment] 2021-12-26 11:54
> Ah okay. Yeah, I am on osx-arm64. Will have to find a workaround. Thanks for the input. Any plans to port it on osx-arm64?

https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only

**Comment by zxzhuty** [comment] 2021-12-28 06:10
Because was designed to be a thin wrapper over Windows technologies, its cross-platform implementation is subpar.System.Drawing.Common.
The usages we see of in non-Windows environments are typically well supported with SkiaSharp and ImageSharp.

**Comment by safern** [comment] 2022-01-10 23:38
Your best bet right now would be to build libgdiplus yourself for arm64 and install it on your machine: https://github.com/mono/libgdiplus/issues/696

Unfortunately we are not investing on more cross platform support for `System.Drawing.Common` as explained on the docs shared earlier on the issue. For those reasons I'll close the issue.

**Closed by safern** 2022-01-10 23:38 UTC
Labels: area-System.Drawing, untriaged
