### ISSUE TITLE
System.Runtime.CompilerServices.Unsafe is not obey .NET Standard 2.0 (it should support .NET Core 2.1 App)

### ISSUE THREAD

**Issue by doggy8088** [dotnet/runtime#77367] opened 2022-10-24 07:21 UTC
### Description

A picture is worth a thousand words.

![image](https://user-images.githubusercontent.com/88981/197469102-a849ac66-ba53-4b0c-9d99-14c76eb54687.png)

### Reproduction Steps

1. Create a Console project with **.NET Core 2.1**.
2. Install System.Net.Http.Json 6.0.0 package
3. Build project

### Expected behavior

Build successfully.

### Actual behavior

It shows:

```txt
Severity	Code	Description	Project	File	Line	Suppression State
Error		System.Runtime.CompilerServices.Unsafe doesn't support netcoreapp2.1. Consider updating your TargetFramework to netcoreapp3.1 or later.	ConsoleApp2	C:\Users\user\.nuget\packages\system.runtime.compilerservices.unsafe\6.0.0\buildTransitive\netcoreapp2.0\System.Runtime.CompilerServices.Unsafe.targets	4	
```

### Regression?

I'm not sure.

### Known Workarounds

Downgrade to System.Net.Http.Json 5.0.0 

### Configuration

N/A

### Other information

N/A

**Comment by martincostello** [comment] 2022-10-24 07:27
.NET Core 2.1 has been out of support [since August 2021](https://devblogs.microsoft.com/dotnet/net-core-2-1-will-reach-end-of-support-on-august-21-2021/), which was before .NET 6 was released.

**Comment by doggy8088** [comment] 2022-10-24 07:33
@martincostello Yes, I know. But it's truly a bug in System.Runtime.CompilerServices.Unsafe. It's not about .NET Core 2.1. It's a commitment on .NET Standard 2.0. Change it's CI pipeline can easily solve this issue.

**Comment by huoyaoyuan** [comment] 2022-10-24 08:01
> But it's truly a bug in System.Runtime.CompilerServices.Unsafe. It's not about .NET Core 2.1.

By policy, the compatibility with EOL platforms is not considered at all.

However, .NET Core 2.1 should be able to consume .NET Standard 2.0, which is supported by `System.Runtime.CompilerServices.Unsafe`.

**Comment by doggy8088** [comment] 2022-10-24 08:16
I know it "should be", but ... You can see my screenshot.

![image](https://user-images.githubusercontent.com/88981/197469102-a849ac66-ba53-4b0c-9d99-14c76eb54687.png)

I'm totally understanding the policy. But I'm talking about the commitment of the .NET Standard. It's a open-source project. It was committed it will support .NET Core 2.1 forever. At least, buildable.  I just want this package can be built successfully. I don't think it's a big deal to fix this issue. I really hope there is a way to contribute to this issue.

If Microsoft is really don't have the resource to fix this issue, then I will suggest remove **.NETStandard 2.0** target claim on the NuGet.

![image](https://user-images.githubusercontent.com/88981/197479649-3c6348e1-1a18-41a7-878a-64f7f26c8ad7.png)

**Comment by Sergio0694** [comment] 2022-10-24 08:50
FWIW `System.Runtime.CompilerServices.Unsafe` does work just fine both on .NET Frameworks and UWP (both on .NETCore.Uwp and .NET Native), via its .NET Standard 2.0 target. For the same reason, it can also be used just fine in .NET Standard 2.0 libraries. This just seems like some issue with .NET Core 2.1 in particular 🤷‍♂️

**Comment by teo-tsirpanis** [comment] 2022-10-24 10:01
@doggy8088 you can suppress this error by adding `<SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>` to your project file.

And you should really not be using .NET Core 2.1.

**Comment by jkotas** [comment] 2022-10-24 10:21
https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/libraries-packaging.md#netstandard-compatibility-error-infrastructure describes how this block for EOL runtimes works.

**Comment by doggy8088** [comment] 2022-10-24 11:04
@teo-tsirpanis Thanks for the workaround! 👍

**Comment by ViktorHofer** [comment] 2022-11-25 11:09
Please see https://github.com/dotnet/runtime/discussions/78550#discussioncomment-4195535 in which this was just recently discussed and which links to the broader discussion in the [open-telemetry issue](https://github.com/open-telemetry/opentelemetry-dotnet/issues/3448).

Note that since then, the msbuild error got downgraded to a warning and the message was revised to provide more information and clearly indicate that the usage of the `netstandard2.0` asset on an out-of-support runtime is unsupported territory and either not work or come with a long tail of issue (on a library-to-library basis). That change is part of .NET 7 (7.0.x nuget packages).

That said, I want to re-empathize that you shouldn't be using an out-of-support runtime. I'm closing this issue as by design and encourage everyone to contribute to the open-telemetry issue which contains all the details.

**Closed by ViktorHofer** 2022-11-25 11:09 UTC
Labels: area-Infrastructure-libraries
