### ISSUE TITLE
MemoryStream should be serializable in .NET Core 3

### ISSUE THREAD

**Issue by koszeggy** [dotnet/runtime#13349] opened 2019-09-01 14:41 UTC
**Releated Issue:** [This one](https://github.com/dotnet/coreclr/issues/17460) complains about broken WCF services but was closed as will not be fixed.

Now here is another issue if `MemoryStream` is not serializable: The .NET Framework serializes `MemoryStream` instances for embedded binary resources. Now the unit tests of my custom [ResXResourceReader](http://docs.kgysoft.net/corelibraries/?topic=html/T_KGySoft_Resources_ResXResourceReader.htm) class are failing in .NET Core because the binary resources cannot be deserialized from .resx files anymore.

> Note: Only the embedded resources are affected, the file references are returned as a `MemoryStream` without any issue.

_This could be relevant for .NET Core 3 where the WinForms version of `ResXResourceReader` will be available again._

Instead of arguing that serializing a `byte[]` is more reasonable (which I basically agree with) wouldn't it just possible to reintroduce the `[Serializable]` attribute for `MemoryStream`? It is essentially a `byte[]` along with a few integers so nothing as dangerous as a delegate or something.

> Note 2: `ResourceManager` is able to deserialize the affected resource from compiled resources as an `UnmanagedMemoryStreamWrapper`. ~Only the direct .resx processing fails~
**Edit:** For embedded resources also the `ResourceManager` fails in .NET Core saying _"Cannot read resources that depend on serialization."_. Only the file references are returned as `UnmanagedMemoryStreamWrapper` (a generic binary file is usually added as `byte[]` while sound resources are added as `MemoryStream`).

Of course, I could use a prepared `ISurrogateSelector` in my [deserializer](https://github.com/koszeggy/KGySoft.CoreLibraries/blob/f9429d7022849ad0cbfca04466dcbebdf952a154/KGySoft.CoreLibraries/Resources/ResXDataNode.cs#L1411) but that would not cure the same issue in the system version. But I prefer compatibility over nasty hacks. Especially when the fix is that simple.

**Comment by GrabYourPitchforks** [comment] 2020-07-21 01:53
The current [plan of record](https://github.com/dotnet/designs/pull/141) is to not mark any more inbox .NET types as `[Serializable]`, including types that were marked as such in Full Framework.

@ericstj Should this work item be instead used for tracking an arbitrary binary blob storage mechanism in .resx files? Otherwise I'll close the issue as a dupe of https://github.com/dotnet/runtime/issues/10106.

**Comment by koszeggy** [comment] 2020-07-21 07:19
From my side the issue can be closed.

In the meantime I implemented the needed workarounds to provide compatibility between the Framework and .NET Core. It's just a bit odd that one needs 3rd party solutions for it.

For anyone who struggles with such issues:
* The [ResXResourceManager](https://docs.kgysoft.net/corelibraries/?topic=html/T_KGySoft_Resources_ResXResourceManager.htm) can be used to access resources directly from .resx files.
* If you have a stream serialized by `BinaryFormatter` in .NET Framework, which cannot be deserialized in .NET Core, the [CustomSerializerSurrogateSelector](https://docs.kgysoft.net/corelibraries/?topic=html/T_KGySoft_Serialization_Binary_CustomSerializerSurrogateSelector.htm), [WeakAssemblySerializationBinder](https://docs.kgysoft.net/corelibraries/?topic=html/T_KGySoft_Serialization_Binary_WeakAssemblySerializationBinder.htm) or [ForwardedTypesSerializationBinder](https://docs.kgysoft.net/corelibraries/?topic=html/T_KGySoft_Serialization_Binary_ForwardedTypesSerializationBinder.htm) types may help you. Though using a binary serialization is typically not recommended across platforms...
* If you really need to use binary serialization in a new project for some reason, then instead of `BinaryFormatter` you can use the [BinarySerializationFormatter](https://docs.kgysoft.net/corelibraries/?topic=html/T_KGySoft_Serialization_Binary_BinarySerializationFormatter.htm), which is more robust and produces a much more [compact stream](https://dotnetfiddle.net/T7BUyB).

The project is open source and is available on [GitHub](https://github.com/koszeggy/KGySoft.CoreLibraries)

**Closed** 2020-08-11 22:34 UTC
Labels: area-System.Resources, question
