### ISSUE TITLE
 System.Net.Sockets.Tests.SocketOptionNameTest.MulticastInterface_Set_IPv6_XXXXX_Succeeds failing

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#90491] opened 2023-08-13 17:40 UTC
These are failing on my Windows 11 22H2 machine, even elevated

the failing code is
```c#
            Socket receiveSocket = new Socket(AddressFamily.InterNetworkV6, SocketType.Dgram, ProtocolType.Udp);

            // sending a message will bind the socket to an available port
            string sendMessage = "dummy message";
            int port = 54320;
            IPAddress multicastAddress = IPAddress.Parse("ff11::1:1");
            receiveSocket.SendTo(Encoding.UTF8.GetBytes(sendMessage), new IPEndPoint(multicastAddress, port)); // <<<<<
```

```
 System.Net.Sockets.Tests.SocketOptionNameTest.MulticastInterface_Set_IPv6_Loopback_Succeeds [FAIL]
        System.Net.Sockets.SocketException : A socket operation was attempted to an unreachable network.
        Stack Trace:
          C:\git\0runtime\src\libraries\System.Net.Sockets\src\System\Net\Sockets\Socket.cs(3626,0): at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
          C:\git\0runtime\src\libraries\System.Net.Sockets\src\System\Net\Sockets\Socket.cs(1292,0): at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
          C:\git\0runtime\src\libraries\System.Net.Sockets\src\System\Net\Sockets\Socket.cs(1320,0): at System.Net.Sockets.Socket.SendTo(Byte[] buffer, EndPoint remoteEP)
          C:\git\0runtime\src\libraries\System.Net.Sockets\tests\FunctionalTests\SocketOptionNameTest.cs(304,0): at System.Net.Sockets.Tests.SocketOptionNameTest.CreateBoundUdpIPv6Socket(Int32& localPort)
          C:\git\0runtime\src\libraries\System.Net.Sockets\tests\FunctionalTests\SocketOptionNameTest.cs(199,0): at System.Net.Sockets.Tests.SocketOptionNameTest.MulticastInterface_Set_IPv6_Helper(Int32 interfaceIndex)
          C:\git\0runtime\src\libraries\System.Net.Sockets\tests\FunctionalTests\SocketOptionNameTest.cs(190,0): at System.Net.Sockets.Tests.SocketOptionNameTest.MulticastInterface_Set_IPv6_Loopback_Succeeds()
          --- End of stack trace from previous location ---
      System.Net.Sockets.Tests.SocketOptionNameTest.MulticastInterface_Set_IPv6_AnyInterface_Succeeds [FAIL]
        System.Net.Sockets.SocketException : A socket operation was attempted to an unreachable network.
        Stack Trace:
          C:\git\0runtime\src\libraries\System.Net.Sockets\src\System\Net\Sockets\Socket.cs(3626,0): at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
          C:\git\0runtime\src\libraries\System.Net.Sockets\src\System\Net\Sockets\Socket.cs(1292,0): at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
          C:\git\0runtime\src\libraries\System.Net.Sockets\src\System\Net\Sockets\Socket.cs(1320,0): at System.Net.Sockets.Socket.SendTo(Byte[] buffer, EndPoint remoteEP)
          C:\git\0runtime\src\libraries\System.Net.Sockets\tests\FunctionalTests\SocketOptionNameTest.cs(304,0): at System.Net.Sockets.Tests.SocketOptionNameTest.CreateBoundUdpIPv6Socket(Int32& localPort)
          C:\git\0runtime\src\libraries\System.Net.Sockets\tests\FunctionalTests\SocketOptionNameTest.cs(199,0): at System.Net.Sockets.Tests.SocketOptionNameTest.MulticastInterface_Set_IPv6_Helper(Int32 interfaceIndex)
          C:\git\0runtime\src\libraries\System.Net.Sockets\tests\FunctionalTests\SocketOptionNameTest.cs(135,0): at System.Net.Sockets.Tests.SocketOptionNameTest.MulticastInterface_Set_IPv6_AnyInterface_Succeeds()
          --- End of stack trace from previous location ---
```

**Comment by wfurt** [comment] 2023-08-14 17:30
Do you have global IPv6 configured @danmoseley ? 
(route print && ifconfig /all) 

We should probably make the test conditional as basic loopback `::1` is probably not good enough.

**Comment by danmoseley** [comment] 2023-10-27 06:08
just saw this @wfurt. 

```
IPv6 Route Table
===========================================================================
Active Routes:
 If Metric Network Destination      Gateway
 14    331 ::/0                     On-link
  1    331 ::1/128                  On-link
 14    331 2001::/32                On-link
 14    331 2001:0:349e:d136:34b6:1b01:4758:effd/128
                                    On-link
 16   5256 fe80::/64                On-link
 49   5256 fe80::/64                On-link
 14    331 fe80::/64                On-link
 49   5256 fe80::2e3e:ca42:a51f:bb32/128
                                    On-link
 14    331 fe80::34b6:1b01:4758:effd/128
                                    On-link
 16   5256 fe80::f2df:5f94:e0f7:c15b/128
                                    On-link
  1    331 ff00::/8                 On-link
 16   5256 ff00::/8                 On-link
 49   5256 ff00::/8                 On-link
 14    331 ff00::/8                 On-link
```
and `ipconfig /all` only shows an ipv6 address under "Tunnel adapter Teredo Tunneling Pseudo-Interface" not under eg "Wireless LAN adapter Wi-Fi:"

happy to try conditionalizing it if you can suggest how.

**Comment by wfurt** [comment] 2023-10-27 18:31
I tried on several machines and I could not reproduce the failure. Even if I disable IPv6 on the Ethernet the tests are still  passing. 
Now, neither of the systems I have access to have "Tunnel adapter Teredo Tunneling Pseudo-Interface"  or any kind of VPN. We already had some magic in tests to skip certain adapters as they don't seem to function null as "normal" interface. 

I see few options here. We can catch this specific Socket error and mark the test as "Skip".
We can possibly get list of interfaces and look for Ethernet(WIFI) with IPv6 global addresses. 
While this may be too restrictive it would IMHO cover CI and most developers. 

any more thoughts on this  @dotnet/ncl ?

**Comment by wfurt** [comment] 2024-06-14 23:00
can you still reproduce it @danmoseley? I did several tries but no luck so far. This seems highly environmental, moving to Future.

**Closed** 2024-07-13 01:58 UTC
Labels: area-System.Net.Sockets, test-run-core, no-recent-activity, needs-author-action
