### ISSUE TITLE
Is value for ThreadPool DispatchQuantum correct?

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#36622] opened 2020-05-18 01:56 UTC
`DispatchQuantum` is set to 30ms

https://github.com/dotnet/runtime/blob/bacef403fbfce0d9e3d49368bfd36dec6dea01fc/src/coreclr/src/System.Private.CoreLib/src/System/Threading/ThreadPool.CoreCLR.cs#L192-L200

However the default value on Linux is 100ms and can be queried with `sched_rr_get_interval` [man7](http://man7.org/linux/man-pages/man2/sched_rr_get_interval.2.html)

> The default quantum is 0.1 seconds

On Windows, not sure what it is, though saw [this table](https://www.javamex.com/tutorials/threads/thread_scheduling_2.shtml)

![image](https://user-images.githubusercontent.com/1142958/82167050-612a8a80-98b2-11ea-9463-3d24ea8addf9.png)

Which suggests for Windows Server it's 120+ms and for desktop 90+ms for foreground process and 30+ms for background process.

So is the current dispatch time set for a Windows desktop background process; and should be much higher for Server and Linux?

Additionally I'd imagine spin time should never go above the thread quantum; but I'm not sure how that's calculated.

/cc @kouvel @stephentoub

**Comment by benaadams** [comment] 2020-05-18 14:33
The 30ms value is from the initial CoreClr dotnet-bot commit on 30 Jan 2015 and hasn't been adjusted since.

**Comment by stephentoub** [comment] 2020-05-18 14:39
Functionally this value isn't related to the OS' quantum.  Are you suggesting it should be?

**Comment by benaadams** [comment] 2020-05-18 15:05
> Functionally this value isn't related to the OS' thread-scheduling quantum. 

Comment seems to suggest it is?
```csharp
// Time in ms for which ThreadPoolWorkQueue.Dispatch keeps executing work items
// before returning to the OS 
```

> Are you suggesting it should be?

Perhaps worth investigating; it the quantum is 100ms and the Dispatch is set to 30ms; it will do 3 outerloops per quantum and finish or start midway through another? An the outerloop isn't without its own costs.

**Comment by benaadams** [comment] 2020-05-18 15:10
Can always give it a try? https://github.com/dotnet/runtime/pull/36652

**Comment by stephentoub** [comment] 2020-05-18 15:54
> Comment seems to suggest it is?

I don't know what the "before returning to the OS" is referring to.  This is about how much time the thread is allowed to process work items before it goes back to do other thread-pool maintenance-related stuff, like seeing whether the thread should be temporarily set aside due to hill-climbing (or in the old days switched to service a different appdomain).

**Comment by kouvel** [comment] 2020-05-18 16:43
When `Dispatch` leaves due to the quantum it may run work items queued from the native side, currently those are the tiering background work callback and the initial timer callback. The `Dispatch` quantum would affect the latency for those native work items to run.

For timers the initial callback that goes to `TimerQueue.FireNextTimers()` may queue other timer callbacks and those would go into the global queue, but it also processes one timer callback inline. It may make sense to handle those native work items (and perhaps all timer callbacks) somewhat similarly to IO completions (without adding more threads), if something like that could be done then the dispatch quantum could be removed.

**Comment by kouvel** [comment] 2020-05-18 16:45
When hill climbing wants to remove a thread from the active pool `NotifyWorkItemComplete()` would return false, I don't think it would be affected by the dispatch quantum

**Comment by stephentoub** [comment] 2020-05-18 16:47
> I don't think it would be affected by the dispatch quantum

Hmm, ok.

**Comment by stephentoub** [comment] 2020-05-18 16:50
@kouvel, so with no appdomains and with this apparently not being related to hill-climbing, is the only reason this quantum exists now to run work items queued on the native side?  If so, have you considered changing the queueing mechanism to queue them into the global queue?  Even if it adds a small amount of expense for such work items, I'd guess that's less than having to repeatedly check in the dispatch loop and forcefully exit out.

**Comment by kouvel** [comment] 2020-05-18 17:06
Yea in my current changes to switch to the portable thread pool `Dispatch` doesn't actually exit due to the quantum but currently it still uses the quantum to check a separate `time-sensitive` work item queue. That was mainly to preserve current behavior, as theoretically the latency of those work items could be relatively high if they go into the global queue. When a tiering or timer callback is queued it would take processing all previously-queued local and global work items, and local work items queued by those global work items, before the native callback is handled. Depending on how the thread pool is used, if global work queue is heavily backed up it may be an issue.

**Comment by benaadams** [comment] 2020-05-18 18:50
Could that be added straight to the dispatch loop? e.g. if time was increased to 100ms, then check the timers when 0ms (i.e. immediately), 30ms, 60ms and 90ms have passed, and otherwise do normal queue processing

**Comment by kouvel** [comment] 2020-05-18 19:07
> if time was increased to 100ms, then check the timers when 0ms (i.e. immediately), 30ms, 60ms and 90ms

I'm not sure I'm following, what is the significance of the 100 ms when things are being checked in 30 ms intervals?

**Comment by benaadams** [comment] 2020-05-18 19:32
Yeah realised that after posting :) So drop that too (or rather repurpose as the timer check threshold)

**Comment by benaadams** [comment] 2020-05-18 19:33
Yeah realised that after posting :) So drop that too (or rather repurpose as the timer check threshold)

But it sounds like you are already doing this?

**Comment by kouvel** [comment] 2020-05-18 19:42
To me it's a long-term goal, I agree the dispatch quantum should ideally not be there, but I think there are good reasons currently why it's there, though at at the same time it is not a sufficient enough mechanism to accomplish the intended goal. Accomplishing that same goal a different but better way may involve tradeoffs in overhead, I don't think it would be for free without making some sacrifices. Certainly more thinking to do there, but even currently I don't think the dispatch quantum has much to do with perf, it's granular enough to be lost in noise.

**Comment by kouvel** [comment] 2020-05-18 19:53
In cases where I have previously seen overhead in the outer parts of `Dispatch` and native code portions of that path, they have occurred in highly bursty scenarios where threads exit `Dispatch` due to not seeing any work items, I have not seen the dispatch quantum to be a reason for it.

**Comment by benaadams** [comment] 2020-05-18 20:07
> , they have occurred in highly bursty scenarios 

Which is why I was interested in "threadpool-drained-count" as counter https://github.com/dotnet/runtime/pull/35823 as currently for Json can see the queue length going up and the items per second dropping; but it doesn't indicate whether its bursty which that would give an indicator of (how many times is the queue cleared, even though the length is high)

![image](https://user-images.githubusercontent.com/1142958/82254689-3a6c6280-994b-11ea-94a4-7be177662535.png)

**Comment by mangod9** [comment] 2021-07-09 23:06
from the discussion appears this is not something we will change for 6?

**Comment by kouvel** [comment] 2021-07-10 02:13
The dispatch quantum would probably go away eventually. The effect it has on perf is probably negligible. Closing for now, please reopen if I missed something else the issue is tracking.

**Closed by kouvel** 2021-07-10 02:13 UTC
Labels: area-System.Threading, tenet-performance
