### ISSUE TITLE
Flags enum ToString breaking change in .NET 8?

### ISSUE THREAD

**Issue by CodeBlanch** [dotnet/runtime#95617] opened 2023-12-05 00:40 UTC
We have a unit test in OTel which just started failing when we added `net8.0` to the project: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/17264f0f8b7dab3baa54f4aaa2449c7575611655/test/OpenTelemetry.Instrumentation.StackExchangeRedis.Tests/Implementation/RedisProfilerEntryToActivityConverterTests.cs#L131

Seems related to this strange flags enum used by StackExchange.Redis: https://github.com/StackExchange/StackExchange.Redis/blob/main/src/StackExchange.Redis/Enums/CommandFlags.cs#L34

Below is some code which I used to reproduce the issue via .NET Fiddle.

When run on .NET 7 it writes out:

`PreferMaster, FireAndForget, NoRedirect`

When run on .NET 8 it writes out:

`FireAndForget, NoRedirect`

Opening this issue to figure out if this was intentional or what.

```csharp
using System;
					
public class Program
{
	public static void Main()
	{
		Console.WriteLine((CommandFlags.FireAndForget | CommandFlags.NoRedirect).ToString());
	}
	
[Flags]
public enum CommandFlags
{
    //
    // Summary:
    //     Default behaviour.
    None = 0,
    //
    // Summary:
    //     From 2.0, this flag is not used
    [Obsolete("From 2.0, this flag is not used", false)]
    HighPriority = 1,
    //
    // Summary:
    //     The caller is not interested in the result; the caller will immediately receive
    //     a default-value of the expected return type (this value is not indicative of
    //     anything at the server).
    FireAndForget = 2,
    //
    // Summary:
    //     This operation should be performed on the master if it is available, but read
    //     operations may be performed on a replica if no master is available. This is the
    //     default option.
    PreferMaster = 0,
    //
    // Summary:
    //     This operation should only be performed on the master.
    DemandMaster = 4,
    //
    // Summary:
    //     This operation should be performed on the replica if it is available, but will
    //     be performed on a master if no replicas are available. Suitable for read operations
    //     only.
    [Obsolete("Starting with Redis version 5, Redis has moved to 'replica' terminology. Please use PreferReplica instead.")]
    PreferSlave = 8,
    //
    // Summary:
    //     This operation should be performed on the replica if it is available, but will
    //     be performed on a master if no replicas are available. Suitable for read operations
    //     only.
    PreferReplica = 8,
    //
    // Summary:
    //     This operation should only be performed on a replica. Suitable for read operations
    //     only.
    DemandReplica = 0xC,
    //
    // Summary:
    //     This operation should only be performed on a replica. Suitable for read operations
    //     only.
    [Obsolete("Starting with Redis version 5, Redis has moved to 'replica' terminology. Please use DemandReplica instead.")]
    DemandSlave = 0xC,
    //
    // Summary:
    //     Indicates that this operation should not be forwarded to other servers as a result
    //     of an ASK or MOVED response
    NoRedirect = 0x40,
    //
    // Summary:
    //     Indicates that script-related operations should use EVAL, not SCRIPT LOAD + EVALSHA
    NoScriptCache = 0x200
}
}
```

**Comment by stephentoub** [comment] 2023-12-05 01:29
This is by design.  Enum.ToString doesn't make any guarantees about which names will be included in the output when multiple names have the same values.  See the "Notes to Callers" section of https://learn.microsoft.com/en-us/dotnet/api/system.enum.tostring.  Thanks, though.

**Comment by skyoxZ** [comment] 2023-12-05 09:28
The behavior of .NET 7 seems to be a bug when multiple names have the value of 0:
```csharp
using System;

Console.WriteLine(CustomFlags.Value1 | CustomFlags.Value2); 
// .NET 7 output: 
// None2, None3, Value1, Value2

[Flags]
public enum CustomFlags
{
    None1 = 0,
    None2 = 0,
    None3 = 0,
    Value1 = 1,
    Value2 = 2
}
```

**Comment by stephentoub** [comment] 2024-07-02 13:00
Closing as by design: https://github.com/dotnet/runtime/issues/95617#issuecomment-1839846006

**Closed by stephentoub** 2024-07-02 13:00 UTC
Labels: area-System.Runtime, untriaged

**Comment by skyoxZ** [comment] 2024-07-03 01:28
> The behavior of .NET 7 seems to be a bug when multiple names have the value of 0:
> 
> ```cs
> using System;
> 
> Console.WriteLine(CustomFlags.Value1 | CustomFlags.Value2); 
> // .NET 7 output: 
> // None2, None3, Value1, Value2
> 
> [Flags]
> public enum CustomFlags
> {
>     None1 = 0,
>     None2 = 0,
>     None3 = 0,
>     Value1 = 1,
>     Value2 = 2
> }
> ```

@stephentoub Is it by design that there's no guarantee to filter out all names of value 0 in my case?

**Comment by stephentoub** [comment] 2024-07-03 18:02
> > The behavior of .NET 7 seems to be a bug when multiple names have the value of 0:
> > using System;
> > 
> > Console.WriteLine(CustomFlags.Value1 | CustomFlags.Value2); 
> > // .NET 7 output: 
> > // None2, None3, Value1, Value2
> > 
> > [Flags]
> > public enum CustomFlags
> > {
> >     None1 = 0,
> >     None2 = 0,
> >     None3 = 0,
> >     Value1 = 1,
> >     Value2 = 2
> > }
> 
> [@stephentoub](https://github.com/stephentoub) Is it by design that there's no guarantee to filter out all names of value 0 in my case?

Behavior when there are multiple named values with the same value is undefined. Per the docs:
https://learn.microsoft.com/en-us/dotnet/api/system.enum.tostring?view=net-8.0#system-enum-tostring
"If multiple enumeration members have the same underlying value and you attempt to retrieve the string representation of an enumeration member's name based on its underlying value, your code should not make any assumptions about which name the method will return."

As part of the rewrite for .NET 8, the changes tried to bring a bit more consistency to the cited case, such that it avoids outputting any zero values if any other value was included. But it's still undefined either way.

**Comment by julealgon** [comment] 2024-07-03 18:09
A flags enum where an entry with value `0` is treated as a meaningful flag itself is such a terrible design anyways.... Nobody should expect the `0` value to show up in the string since it is a no-op in terms of generating the final enum value.

If one expects some default behavior when a flags enum is used, that default behavior should be one of the valid flags and the parameter should be defaulted to that instead.
