### ISSUE TITLE
System.Guid N format deserialization

### ISSUE THREAD

**Issue by fleed** [dotnet/runtime#1567] opened 2019-08-11 06:06 UTC
Is the `N` format for `System.Guid` not supported during deserialization?

The following test fails (.net core 3 preview 7) with a **System.FormatException : The JSON value is not in a supported Guid format**:

```
public class TestGuid
{
    [JsonPropertyName("id")]
    public Guid Id { get; set; }
}

[Fact]
public void TestGuidSerialization()
{
    var s = "{\"id\":\"00000000000000000000000000000000\"}";
    //var y = Newtonsoft.Json.JsonConvert.DeserializeObject<TestGuid>(s);
    var x = JsonSerializer.Deserialize<TestGuid>(s);
}
```

The commented **Newtonsoft.Json** version works as expected

**Comment by layomia** [comment] 2020-02-21 23:30
Closing as duplicate of https://github.com/dotnet/runtime/issues/30692.

**Closed by layomia** 2020-02-21 23:30 UTC
Labels: area-System.Text.Json
