### ISSUE TITLE
[API Proposal]: More granular control over properties during (de)serialization with System.Text.Json

### ISSUE THREAD

**Issue by pebezo** [dotnet/runtime#87875] opened 2023-06-21 18:47 UTC
### Background and motivation

A common pattern that involves JSON is to read from source A, de-serialize into an object, modify that object, and then pass the same object to B. The issue is when there are few properties that have to de-serialize as `foo` but serialize as `bar`, or when one property should be ignored during serialization, but not during de-serialization (or vice versa).

The overall request is to give us attribute-level control (without having to write converters or policies) to customize properties (their names or if they should be ignored or not) for both serialization and de-serialization.

### API Proposal

```csharp
public class MyEntity
{
    // It should de-serialize from `full_name`, but when serializing it should output as `fullName`
    [JsonPropertyName("full_name", "fullName")]
    public string? Name { get; set; }

    // This should be ignored during de-serialization, but should be written when serializing
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenReading)]
    public string? OnlyWrite { get; set; }
    
    // Similar, but should be ignored when serializing
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWriting)]
    public string? OnlyRead { get; set; }
}
```

### API Usage

```csharp
var entity = JsonSerializer.Deserialize<MyEntity>("""{ "full_name": "First Last", "onlyRead": "read" }""");
entity.OnlyWrite = "written";
var after = JsonSerializer.Serialize(entity);
// Expected value for `after`: { "fullName": "First Last", "onlyWrite": "written" }
```

### Risks

Special care should be given to not alter the current behavior. For JsonPropertyName if only one name is given it should be used for both serialization and de-serialization (current behavior).

**Comment by eiriktsarpalis** [comment] 2023-06-21 19:41
Duplicate of https://github.com/dotnet/runtime/issues/66490.

**Closed by eiriktsarpalis** 2023-06-21 19:41 UTC
Labels: api-suggestion, area-System.Text.Json, untriaged

**Comment by pebezo** [comment] 2023-06-21 21:34
@eiriktsarpalis I see the JsonIgnore bits, but that issue does not have the property name in it. Should I update this ticket to include only the JsonPropertyName?

**Comment by eiriktsarpalis** [comment] 2023-06-22 12:47
@pebezo I missed the `JsonPropertyName` proposal. Unfortunately, I don't think we could support this easily since the underlying `JsonPropertyInfo` infrastructure assumes a unique property name per instance. You might be able to add support for such a custom attribute though using [contract customization](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/custom-contracts), although you would need to duplicate `JsonPropertyInfo` instances for every alternative name that you specify.

**Comment by pebezo** [comment] 2023-06-22 13:27
I'm really looking for a way to handle this via attributes because a lot of times I don't have control over the (de)serialization pipeline (not something I can change). I could take a stab at it if this is something you'd consider accepting.

**Comment by eiriktsarpalis** [comment] 2023-06-22 13:31
Unfortunately this is not something we could consider due to the aforementioned constraints.
