### ISSUE TITLE
Test failure JIT\\SIMD\\VectorDot_r\\VectorDot_r.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#74913] opened 2022-09-01 07:58 UTC
Run: [runtime-coreclr outerloop 20220831.5](https://dev.azure.com/dnceng/public/_build/results?buildId=1980597&view=ms.vss-test-web.build-test-results-tab&runId=50637318&resultId=100706&paneView=debug)

Failed test:
```
R2R-CG2 windows x86 Checked @ Windows.10.Amd64.Open

- JIT\\SIMD\\VectorDot_r\\VectorDot_r.cmd
```
**Error message:**
```
Fatal error. Internal CLR error. (0x80131506)
at System.Collections.Generic.Stack1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]..ctor() at Internal.JitInterface.CorInfoImpl..ctor() at Internal.JitInterface.CorInfoImpl..ctor(ILCompiler.ReadyToRunCodegenCompilation) at ILCompiler.ReadyToRunCodegenCompilation.<ComputeDependencyNodeDependencies>b__38_6(System.Threading.Thread) at System.Runtime.CompilerServices.ConditionalWeakTable2[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetValueLocked(System.__Canon, CreateValueCallback<System.__Canon,System.__Canon>)
at System.Runtime.CompilerServices.ConditionalWeakTable2[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetValue(System.__Canon, CreateValueCallback<System.__Canon,System.__Canon>) at ILCompiler.ReadyToRunCodegenCompilation.<ComputeDependencyNodeDependencies>g__CompileOneMethod|38_3(ILCompiler.DependencyAnalysisFramework.DependencyNodeCore1<ILCompiler.DependencyAnalysis.NodeFactory>)
at System.Threading.Tasks.Parallel+<>c__DisplayClass33_02[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForEachWorker>b__0(Int32) at System.Threading.Tasks.Parallel+<>c__DisplayClass19_01[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef, Int32, Boolean ByRef)
at System.Threading.Tasks.TaskReplicator+Replica.Execute()
at System.Threading.Tasks.TaskReplicator+Replica+<>c.<.ctor>b__4_0(System.Object)
at System.Threading.Tasks.Task.InnerInvoke()
at System.Threading.Tasks.Task+<>c.<.cctor>b__273_0(System.Object)
at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
at System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(System.Threading.Tasks.Task, Boolean)
at System.Threading.Tasks.TaskScheduler.TryRunInline(System.Threading.Tasks.Task, Boolean)
at System.Threading.Tasks.Task.InternalRunSynchronously(System.Threading.Tasks.TaskScheduler, Boolean)
at System.Threading.Tasks.Task.RunSynchronously(System.Threading.Tasks.TaskScheduler)
at System.Threading.Tasks.TaskReplicator.Run[[System.Threading.Tasks.RangeWorker, System.Threading.Tasks.Parallel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](ReplicatableUserAction1<System.Threading.Tasks.RangeWorker>, System.Threading.Tasks.ParallelOptions, Boolean) at System.Threading.Tasks.Parallel.ForWorker[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Int32, Int32, System.Threading.Tasks.ParallelOptions, System.Action1<Int32>, System.Action2<Int32,System.Threading.Tasks.ParallelLoopState>, System.Func4<Int32,System.Threading.Tasks.ParallelLoopState,System.__Canon,System.__Canon>, System.Func1<System.__Canon>, System.Action1<System.__Canon>)
at System.Threading.Tasks.Parallel.ForEachWorker[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Ge


Stack trace
   at JIT_SIMD._VectorDot_r_VectorDot_r_._VectorDot_r_VectorDot_r_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by AntonLapounov** [comment] 2022-09-05 23:13
Duplicate of #75041.
```
00  coreclr!DacEnumerableHashTable<InstMethodHashTable,InstMethodHashEntry,4>::BaseFindNextEntryByHash+0x12
01  coreclr!InstMethodHashTable::FindMethodDesc+0x253
02  coreclr!InstantiatedMethodDesc::FindLoadedInstantiatedMethodDesc+0xdc
03  coreclr!MethodDesc::FindOrCreateAssociatedMethodDesc+0x11a5
04  coreclr!ZapSig::DecodeMethod+0x3bf
05  coreclr!ZapSig::DecodeMethod+0x59
06  coreclr!ExternalMethodFixupWorker+0x2fc
07  coreclr!DelayLoad_MethodCall+0x23
```

**Closed by AntonLapounov** 2022-09-05 23:13 UTC
Labels: arch-x86, area-System.Threading.Tasks, os-windows, blocking-outerloop
