### ISSUE TITLE
Add Pure-attribute to Tuple types

### ISSUE THREAD

**Issue by stidsborg** [dotnet/runtime#64141] opened 2022-01-22 09:37 UTC
### Description

I noticed when reviewing some code that there was no IDE warning for the following code:
`Tuple.Create(1,2)`

It would be nice if the Pure-attribute could be added to the Tuple types thereby allowing the IDE to issue a warning in such cases.

Many thanks in advance,
/stidsborg

### Reproduction Steps

`Tuple.Create(1)`

### Expected behavior

IDE warning: 'Return value of pure method is not used'

### Actual behavior

No warning

**Comment by Wraith2** [comment] 2022-01-22 11:14
See https://github.com/dotnet/runtime/issues/63570#issuecomment-1009094149 for recent discussion on the topic of Pure annotations.

**Comment by stephentoub** [comment] 2022-01-22 12:58
Thanks. Closing as a duplicate of https://github.com/dotnet/runtime/issues/34098#issuecomment-604439020.

**Closed by stephentoub** 2022-01-22 12:58 UTC
Labels: area-System.Runtime, untriaged
