### ISSUE TITLE
Test failure JIT\\Generics\\ConstrainedCall\\vt1_il_d\\vt1_il_d.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#65170] opened 2022-02-11 01:14 UTC
Run: [runtime-coreclr r2r 20220209.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1604195&view=ms.vss-test-web.build-test-results-tab&runId=44761570&resultId=100723&paneView=debug)

Failed test:
```
R2R windows arm Checked @ Windows.10.Arm64v8.Open

- JIT\\Generics\\ConstrainedCall\\vt1_il_d\\vt1_il_d.cmd

```
**Error message:**
```
Could Not Find D:\h\w\AFCC0967\w\AE720918\e\JIT\Generics\ConstrainedCall\vt1_il_d\IL-CG2\composite-r2r.dll
Could Not Find D:\h\w\AFCC0967\w\AE720918\e\JIT\Generics\ConstrainedCall\vt1_il_d\vt1_il_d.dll.rsp
Fatal error. Internal CLR error. (0x80131506)
at System.SZArrayHelper.GetEnumerator[[Internal.JitInterface.CorJitFlag, ILCompiler.ReadyToRun, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null]](https://dev.azure.com/dnceng/public/_build/results?buildId=1604195&view=ms.vss-test-web.build-test-results-tab&runId=44761570&resultId=100723&paneView=debug)
at Internal.JitInterface.CorInfoImpl.getJitFlags(Internal.JitInterface.CORJIT_FLAGS ByRef, UInt32)
at Internal.JitInterface.CorInfoImpl._getJitFlags(IntPtr, IntPtr*, Internal.JitInterface.CORJIT_FLAGS*, UInt32)
at Internal.JitInterface.CorInfoImpl.JitCompileMethod(IntPtr ByRef, IntPtr, IntPtr, IntPtr, Internal.JitInterface.CORINFO_METHOD_INFO ByRef, UInt32, IntPtr ByRef, UInt32 ByRef)
at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(ILCompiler.DependencyAnalysis.IMethodNode, Internal.IL.MethodIL)
at Internal.JitInterface.CorInfoImpl.CompileMethod(ILCompiler.DependencyAnalysis.ReadyToRun.MethodWithGCInfo, ILCompiler.Logger)
at ILCompiler.ReadyToRunCodegenCompilation.<ComputeDependencyNodeDependencies>b__35_0(ILCompiler.DependencyAnalysisFramework.DependencyNodeCore1<ILCompiler.DependencyAnalysis.NodeFactory>) at System.Threading.Tasks.Parallel+<>c__DisplayClass33_02[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForEachWorker>b__0(Int32)
at System.Threading.Tasks.Parallel+<>c__DisplayClass19_0`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef, Int32, Boolean ByRef)
at System.Threading.Tasks.TaskReplicator+Replica.Execute()
at System.Threading.Tasks.TaskReplicator+Replica+<>c.<.ctor>b__4_0(System.Object)
at System.Threading.Tasks.Task.InnerInvoke()
at System.Threading.Tasks.Task+<>c.<.cctor>b__271_0(System.Object)
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
at System.Threading.Thread.StartCallback()

Return code:      1
Raw output file:      D:\h\w\AFCC0967\w\AE720918\uploads\Reports\JIT.Generics\ConstrainedCall\vt1_il_d\vt1_il_d.output.txt
Raw output:
BEGIN EXECUTION
vt1_il_d.dll
1 file(s) copied.
Response file: D:\h\w\AFCC0967\w\AE720918\e\JIT\Generics\ConstrainedCall\vt1_il_d\vt1_il_d.dll.rsp
D:\h\w\AFCC0967\w\AE720918\e\JIT\Generics\ConstrainedCall\vt1_il_d\IL-CG2\vt1_il_d.dll
-o:D:\h\w\AFCC0967\w\AE720918\e\JIT\Generics\ConstrainedCall\vt1_il_d\vt1_il_d.dll
--targetarch:arm
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\AFCC0967\p\System..dll
-r:D:\h\w\AFCC0967\p\Microsoft..dll
-r:D:\h\w\AFCC0967\p\mscorlib.dll
-r:D:\h\w\AFCC0967\p\netstandard.dll
-O
" "dotnet" "D:\h\w\AFCC0967\p\crossgen2\crossgen2.dll" @"D:\h\w\AFCC0967\w\AE720918\e\JIT\Generics\ConstrainedCall\vt1_il_d\vt1_il_d.dll.rsp"   -r:D:\h\w\AFCC0967\w\AE720918\e\JIT\Generics\ConstrainedCall\vt1_il_d\IL-CG2*.dll"
Crossgen2 failed with exitcode - -1073741819
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\AFCC0967\p
D:\h\w\AFCC0967\w\AE720918\e\JIT\Generics\ConstrainedCall\vt1_il_d\vt1_il_d.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_Generics._ConstrainedCall_vt1_il_d_vt1_il_d_._ConstrainedCall_vt1_il_d_vt1_il_d_cmd()
```

**Comment by trylek** [comment] 2022-04-04 20:34
Closing as duplicate of: https://github.com/dotnet/runtime/issues/66183

**Closed by trylek** 2022-04-04 20:34 UTC
Labels: os-windows, area-crossgen2-coreclr, untriaged
