### ISSUE TITLE
[Bug] MAUI templates crashing on iOS (Foundation.NSMutableData:AppendBytes)

### ISSUE THREAD

**Issue by PureWeen** [dotnet/runtime#61153] opened 2021-10-29 15:06 UTC
### Description
Application is failing to start
```
=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at ObjCRuntime.Messaging:void_objc_msgSend_IntPtr_UIntPtr <0x0006e>
	  at Foundation.NSMutableData:AppendBytes <0x0004a>
	  at Foundation.NSData:FromStream <0x000dc>
	  at Microsoft.Maui.EmbeddedFontLoader:LoadFont <0x0006a>
	  at Microsoft.Maui.FontRegistrar:LoadEmbeddedFont <0x000a0>
	  at Microsoft.Maui.FontRegistrar:LoadNativeAppFont <0x0003a>
	  at Microsoft.Maui.FontRegistrar:GetFont <0x0011a>
	  at Microsoft.Maui.FontManager:CleanseFontName <0x00022>
	  at Microsoft.Maui.FontManager:CreateFont <0x0015e>
	  at System.Collections.Concurrent.ConcurrentDictionary`2:GetOrAdd <0x000e2>
	  at Microsoft.Maui.FontManager:GetFont <0x00074>
	  at Microsoft.Maui.FontManager:GetFont <0x00032>
	  at Microsoft.Maui.LabelExtensions:UpdateFont <0x0002a>
	  at Microsoft.Maui.LabelExtensions:UpdateFont <0x0001c>
	  at Microsoft.Maui.Handlers.LabelHandler:MapFont <0x0003e>
	  at Microsoft.Maui.Controls.Label:MapFont <0x0002e>
	  at <>c__DisplayClass5_0:<Add>b__0 <0x00048>
	  at Microsoft.Maui.PropertyMapper:UpdatePropertyCore <0x00036>
	  at Microsoft.Maui.PropertyMapper:UpdateProperties <0x0005e>
```
### Steps to Reproduce
- Install the latest main bits https://github.com/dotnet/maui/blob/main/.github/DEVELOPMENT.md

```
dotnet workload install maui `
   --from-rollback-file https://aka.ms/dotnet/maui/preview.10.json `
   --source https://aka.ms/dotnet6/nuget/index.json `
   --source https://api.nuget.org/v3/index.json
```

- dotnet new maui
- launch the iOS app

### Expected Behavior
doesn't crash

### Actual Behavior
crashes

### Basic Information

- Version with issue: main
- Last known good version: p10

This is acting like an issue with the iOS workloads.  If you change the version of MAUI to be p.10 but still use the p.11 iOS workloads the app still crashes.

**Comment by rolfbjarne** [comment] 2021-11-03 14:45
CC @akoeplinger @steveisok 

This is breaking the default MAUI template, so it's a rather high priority.

It's rather obnoxious to reproduce, because of other breaking changes in later commits that hides this problem, but I believe it should be possible by installing .NET 6 (RTM), and then this package: https://bosstoragemirror.blob.core.windows.net/wrench/main/40db84a71e10a549cdcd3dab746120dba3f84554/5378878/package/notarized/Microsoft.iOS.Bundle.15.0.101-preview.11.279.pkg

**Comment by SamMonoRT** [comment] 2021-11-22 14:05
Closed by mistake -- reopening again

**Comment by filipnavara** [comment] 2021-12-18 11:51
I am not quite sure how it's possible but this bug exists in the Hot Restart code in VS 2022 when running legacy Xamarin code. I'd expect the prebuilt app to use legacy Mono and behave identically to VS 2019 but that's not the case. It crashes with a similar stack trace for the same underlying reasons:

<details>
<summary>Stack trace</summary>
```
	  at <unknown> <0xffffffff>
	  at ObjCRuntime.Messaging:void_objc_msgSend_IntPtr_UIntPtr <0x00022>
	  at Foundation.NSMutableData:AppendBytes <0x00054>
	  at Foundation.NSData:FromStream <0x0010c>
	  at <LoadImageAsync>d__1:MoveNext <0x00160>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x00052>
	  at Xamarin.Forms.Platform.iOS.StreamImagesourceHandler:LoadImageAsync <0x00062>
	  at <GetNativeImageAsync>d__10:MoveNext <0x000c4>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x00052>
	  at Xamarin.Forms.Platform.iOS.ImageElementManager:GetNativeImageAsync <0x00052>
	  at <SetImage>d__8:MoveNext <0x00530>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start <0x00052>
	  at Xamarin.Forms.Platform.iOS.ImageElementManager:SetImage <0x0005c>
	  at <SetImage>d__6:MoveNext <0x00034>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start <0x00052>
	  at Xamarin.Forms.Platform.iOS.ImageRenderer:SetImage <0x0004e>
	  at <TrySetImage>d__5:MoveNext
 <0x0002c>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start <0x00052>
	  at Xamarin.Forms.Platform.iOS.ImageRenderer:TrySetImage <0x0004e>
	  at <OnElementChanged>d__3:MoveNext <0x000a4>
	  at System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start <0x00052>
	  at Xamarin.Forms.Platform.iOS.ImageRenderer:OnElementChanged <0x0004a>
	  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1:SetElement <0x002a2>
	  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1:Xamarin.Forms.Platform.iOS.IVisualElementRenderer.SetElement <0x00010>
	  at Xamarin.Forms.Platform.iOS.Platform:CreateRenderer <0x00080>
	  at Xamarin.Forms.Platform.iOS.VisualElementPackager:OnChildAdded <0x00084>
	  at Xamarin.Forms.Platform.iOS.VisualElementPackager:Load <0x0005a>
	  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1:SetElement <0x00228>
	  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1:Xamarin.Forms.Platform.iOS.IVisualElementRenderer.SetElement <0x00010>
	  at Xamarin.Forms.Platform.iOS.Platform
:CreateRenderer <0x00080>
	  at Xamarin.Forms.Platform.iOS.VisualElementPackager:OnChildAdded <0x00084>
	  at Xamarin.Forms.Platform.iOS.VisualElementPackager:Load <0x0005a>
	  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1:SetElement <0x00228>
	  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1:Xamarin.Forms.Platform.iOS.IVisualElementRenderer.SetElement <0x00010>
	  at Xamarin.Forms.Platform.iOS.Platform:CreateRenderer <0x00080>
	  at Xamarin.Forms.Platform.iOS.VisualElementPackager:OnChildAdded <0x00084>
	  at Xamarin.Forms.Platform.iOS.VisualElementPackager:Load <0x0005a>
	  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1:SetElement <0x00228>
	  at Xamarin.Forms.Platform.iOS.VisualElementRenderer`1:Xamarin.Forms.Platform.iOS.IVisualElementRenderer.SetElement <0x00010>
	  at Xamarin.Forms.Platform.iOS.Platform:CreateRenderer <0x00080>
	  at Xamarin.Forms.Platform.iOS.VisualElementPackager:OnChildAdded <0x00084>
	  at Xamarin.Forms.Platform.iOS.VisualElementPackager:Load <0x0005a>
	  at Xa
marin.Forms.Platform.iOS.PageRenderer:ViewDidLoad <0x0010c>
	  at System.Object:runtime_invoke_direct_void__this__ <0x0008e>
	  at <unknown> <0xffffffff>
	  at ObjCRuntime.Messaging:IntPtr_objc_msgSendSuper <0x0001a>
	  at UIKit.UIViewController:get_View <0x0006c>
	  at Xamarin.Forms.Platform.iOS.PageRenderer:get_NativeView <0x00016>
	  at Xamarin.Forms.Platform.iOS.PageRenderer:SetElement <0x00096>
	  at Xamarin.Forms.Platform.iOS.Platform:CreateRenderer <0x00080>
	  at MailClient.Mobile.iOS.Renderers.CustomNavigationRenderer:CreateViewControllerForPage <0x00030>
	  at <OnPushAsync>d__53:MoveNext <0x00050>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x0004a>
	  at MailClient.Mobile.iOS.Renderers.CustomNavigationRenderer:OnPushAsync <0x00062>
	  at MailClient.Mobile.iOS.Renderers.CustomNavigationRenderer:PushPageAsync <0x00018>
	  at MailClient.Mobile.iOS.Renderers.CustomNavigationRenderer:OnPushRequested <0x0006c>
	  at System.EventHandler`1:invoke_void_object_TEventArgs <0x00080>
	
  at <PushAsyncInner>d__88:MoveNext <0x00224>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start <0x0004a>
	  at MailClient.Mobile.UI.Navigation.CustomNavigationPage:PushAsyncInner <0x00066>
	  at <PushAsync>d__65:MoveNext <0x0029a>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start <0x0004a>
	  at MailClient.Mobile.UI.Navigation.CustomNavigationPage:PushAsync <0x00066>
	  at NavigationImpl:OnPushAsync <0x0001e>
	  at Xamarin.Forms.Internals.NavigationProxy:PushAsync <0x00038>
	  at Xamarin.Forms.Internals.NavigationProxy:OnPushAsync <0x00064>
	  at Xamarin.Forms.Internals.NavigationProxy:PushAsync <0x00038>
	  at <ComposeButton_Clicked>d__52:MoveNext <0x0005a>
	  at System.Runtime.CompilerServices.AsyncVoidMethodBuilder:Start <0x0004a>
	  at MailClient.Mobile.UI.Pages.MailsPage:ComposeButton_Clicked <0x00062>
	  at <Module>:invoke_void_object_EventArgs <0x00080>
	  at Xamarin.Forms.ImageButton:PropagateUpClicked <0x00028>
	  at Xamarin.Forms.ButtonElement:ElementClicked <0x000
5e>
	  at Xamarin.Forms.ImageButton:SendClicked <0x0000a>
	  at Xamarin.Forms.Platform.iOS.ButtonElementManager:OnButtonTouchUpInside <0x0002e>
	  at Xamarin.Forms.Platform.iOS.ButtonElementManager:TouchUpInside <0x00032>
	  at <Module>:invoke_void_object_EventArgs <0x000a6>
	  at UIKit.UIControlEventProxy:Activated <0x00030>
	  at System.Object:runtime_invoke_direct_void__this__ <0x0003a>
	  at <unknown> <0xffffffff>
	  at UIKit.UIApplication:UIApplicationMain <0x000b8>
	  at UIKit.UIApplication:Main <0x000b2>
	  at MailClient.Mobile.iOS.Application:Main <0x00012>
	  at <Module>:runtime_invoke_direct_void_string[] <0x00092>
	  at <unknown> <0xffffffff>
	  at System.Reflection.RuntimeMethodInfo:InternalInvoke <0x00030>
	  at System.Reflection.RuntimeMethodInfo:Invoke <0x000fc>
	  at System.Reflection.MethodBase:Invoke <0x0001a>
	  at Xamarin.iOS.HotRestart.Application:Run <0x001fa>
	  at Xamarin.PreBuilt.iOS.Applications:Main <0x0005a>
	  at <Module>:runtime_invoke_direct_void_string[] <0x00092>
```
</details>

The Mono backport (https://github.com/mono/mono/pull/21317) was closed without an explanation. I assumed it's just not needed because the changes in runtime/X.iOS should not be affecting it but apparently some change did affect it.

**Comment by filipnavara** [comment] 2021-12-18 12:43
The X.iOS 15.0.0.6 release from 23/09/2021 still used `void_objc_msgSend_IntPtr_nuint` prototype at the P/Invoke code. Some change later unified it with .NET 6 code path and it started using `void_objc_msgSend_IntPtr_UIntPtr`. This triggered the interpreter bug both in MonoVM and legacy Mono. Hence, the backport to legacy Mono is necessary or the change in X.iOS has to be conditionally reverted.

cc @BrzVlad @rolfbjarne

**Closed** 2022-01-24 15:06 UTC
Labels: area-Codegen-Interpreter-mono, os-ios
