### ISSUE TITLE
API Proposal: IPNetwork to support CIDR notation

### ISSUE THREAD

**Issue by alrz** [dotnet/runtime#64033] opened 2022-01-20 08:23 UTC
### Background and motivation

An implementation is exposed through HttpOverrides middleware package at https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/HttpOverrides/src/IPNetwork.cs

This proposal is to promote it under `System.Net` namespace for a built-in support.

> 

### API Proposal

```C#
namespace System.Net
{
    public struct IPNetwork
    {
        // eg: "192.168.0.0/16"
        public static IPNetwork Parse(string);
        public IPNetwork(IPAddress, IPAddress);
        public IPNetwork(IPAddress, int);
        public bool Contains(IPAddress);
        // ..
    }
}
```

### API Usage

```C#
var range = IPNetwork.Parse(cidr);
bool result = range.Contains(address);
```

**Comment by alrz** [comment] 2022-01-20 08:24
Relates to https://github.com/dotnet/runtime/issues/42845

**Comment by pinkfloydx33** [comment] 2022-01-20 10:28
Would this also include support for a built-in type converter (or similar) that would allow binding configuration containing such values?

At the moment we rely on a custom type converter to bind configuration containing such values (primarily for forwarded headers and ip whitelisting). We add the converters using `TypeDescriptor.AddAttributes` via a module Initializer in our shared library, but it's my understanding that it may not necessarily be safe to rely upon and only by chance has continued to work.

It would be nice to not need to do this and just have it work out of the box.

**Comment by scalablecory** [comment] 2022-02-03 16:47
We previously rejected a CIDR proposal due to lack of customer demand: #36428

**Comment by karelz** [comment] 2022-02-15 17:35
Triage: Still not high enough demand. Other libraries exist that solve it. Not desperately needed in BCL.

**Comment by karelz** [comment] 2022-02-15 17:35
Duplicate of #36428

**Closed by karelz** 2022-02-15 17:35 UTC
Labels: api-suggestion, area-System.Net, untriaged
