### ISSUE TITLE
IOptions<T> should support C# records

### ISSUE THREAD

**Issue by ddrinka** [dotnet/runtime#46996] opened 2021-01-14 18:03 UTC
With PR [#2169](https://github.com/dotnet/extensions/pull/2169) in place, there is no longer a compiler restriction on using records with `IOptions<T>`.  However the [default OptionsFactory implementation](https://github.com/dotnet/runtime/blob/54953538be9e7e20eccc90b271edfd01210cf6a8/src/libraries/Microsoft.Extensions.Options/src/OptionsFactory.cs) still requires a parameterless constructor.

We should be able to use fully-defaulted records with the IOptions pattern.  The following builds but throws:
```csharp
record MyConfiguration(string value = "default");
MyConstructor(IOptions<MyConfiguration> configuration) { }
```

**Comment by christiannagel** [comment] 2021-01-14 19:10
Feature request is already here: #43359

**Comment by ddrinka** [comment] 2021-01-15 07:39
@christiannagel Ok, looks like this is on the radar.  Thanks for pointing me to that existing feature request.

**Comment by maryamariyan** [comment] 2021-01-19 20:51
Closing as dupe of https://github.com/dotnet/runtime/issues/43359, thanks.

**Closed by maryamariyan** 2021-01-19 20:51 UTC
Labels: area-Extensions-Options, untriaged
