### ISSUE TITLE
Provide workflow to automatically port API docs to dotnet-api-docs

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#41419] opened 2020-08-26 22:34 UTC
During each release cycle we add new APIs and documentation for them. Currently, the process of moving docs over from the triple-slash comments in dotnet/runtime to the API docs on https://docs.dot.net has a number of manual steps.

I propose that we add a GitHub Action (preferable) or manually-triggered Azure DevOps Pipeline to auto-port the doc comments per-assembly to PRs opened against the dotnet/dotnet-api-docs repository.

**Comment by safern** [comment] 2020-08-26 22:50
Cc: @carlossanlop

**Comment by safern** [comment] 2020-08-26 22:50
Marking as 6.0.0

**Comment by ViktorHofer** [comment] 2022-08-01 16:39
cc @carlossanlop @jeffhandley

**Comment by ViktorHofer** [comment] 2023-07-12 16:47
Duplicate of https://github.com/dotnet/runtime/issues/44969

**Closed by ViktorHofer** 2023-07-12 16:47 UTC
Labels: area-Infrastructure-libraries
