### ISSUE TITLE
[iOS/macOS] Time zone APIs don't reflect system time zone change

### ISSUE THREAD

**Issue by tipa** [dotnet/runtime#97010] opened 2024-01-15 22:44 UTC
### Description

It appears that the app is "stuck" in the time zone that was set as system time zone at the time of app launch.
Later changes to the system time zone (in the macOS/iOS system settings) don't seem to affect the .NET APIs that depend on a time zone (e.g. `DateTime.Now`)

### Reproduction Steps

- Launch app
- Switch to other time zone in (iOS/macOS) system settings
- call `DateTime.Now` or `TimeZoneInfo.Local`

### Expected behavior

Correct time and time zone (according to the current time zone set in the system settings)

### Actual behavior

Wrong time and time zone. The app is "stuck" in the old time zone that was set in the system at the time the app launched

### Configuration

.NET8, iOS 17.2.1, macOS 14.2.1

**Comment by filipnavara** [comment] 2024-01-15 22:59
That’s actually documented to some extent. You can call `TimeZoneInfo.ClearCachedData` to reload the system information.

**Comment by tarekgh** [comment] 2024-01-15 23:33
Duplicate of https://github.com/dotnet/runtime/issues/31043.

We don't have a cheap way to listen for the TZ changes as this will require creating some listener threads. I think the offered workaround for the apps is reasonable if they care about this scenario. The apps can listen to TZ change event and then they can call TimeZoneInfo.ClearCachedData. This way we are not putting the burden on all apps.

**Closed by tarekgh** 2024-01-15 23:33 UTC
Labels: untriaged, area-System.DateTime
