### ISSUE TITLE
The configuration values are inconsistent

### ISSUE THREAD

**Issue by Varorbc** [dotnet/runtime#81680] opened 2023-02-06 08:19 UTC
### Description

The configuration values are inconsistent

### 6.0

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="6.0.0" />
  </ItemGroup>

</Project>


using Microsoft.Extensions.Configuration;
using System.Text;

MemoryStream memoryStream = new MemoryStream(Encoding.UTF8.GetBytes(
    """
    {
        "Test": {
            "Name": null,
            "IsAdmin": null
        }
    }
    """));

ConfigurationBuilder builder = new ConfigurationBuilder();
builder.AddJsonStream(memoryStream);
IConfigurationRoot configuration = builder.Build();
var testOptions = configuration.Get<Test1Options>();
Console.WriteLine(testOptions.Test.Name);
Console.WriteLine(testOptions.Test.IsAdmin);

public class Test1Options
{
    public Test2Options Test { get; set; } = new Test2Options();
}

public class Test2Options
{
    public string? Name { get; set; } = "Test";

    public bool? IsAdmin { get; set; } = true;
}
```

### 7.0

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="7.0.0" />
  </ItemGroup>

</Project>


using Microsoft.Extensions.Configuration;
using System.Text;

MemoryStream memoryStream = new MemoryStream(Encoding.UTF8.GetBytes(
    """
    {
        "Test": {
            "Name": null,
            "IsAdmin": null
        }
    }
    """));

ConfigurationBuilder builder = new ConfigurationBuilder();
builder.AddJsonStream(memoryStream);
IConfigurationRoot configuration = builder.Build();
var testOptions = configuration.Get<Test1Options>();
Console.WriteLine(testOptions.Test.Name);
Console.WriteLine(testOptions.Test.IsAdmin);

public class Test1Options
{
    public Test2Options Test { get; set; } = new Test2Options();
}

public class Test2Options
{
    public string? Name { get; set; } = "Test";

    public bool? IsAdmin { get; set; } = true;
}
```

### 6.0 and 7.0

`Name` is "Test"
`IsAdmin` is `true`

### 6.0

`Name` is ""
`IsAdmin` is `true`

### 7.0

`Name` is ""
`IsAdmin` is `null`

**Comment by tarekgh** [comment] 2023-02-06 16:35
Duplicate of https://github.com/dotnet/runtime/issues/79904. The fix will be released with 7.0.3.

**Closed by tarekgh** 2023-02-06 16:35 UTC
Labels: untriaged, area-Extensions-Configuration

**Comment by tarekgh** [comment] 2023-02-07 01:03
@Varorbc first, we have the issue https://github.com/dotnet/runtime/issues/36510 which is about reading `null` values from the configuration. Currently we read it as empty string. second, I am not sure why you expect to get the `Name` value as `Test`? regardless of if we read the value as `null` or empty string, this value is going to be set to the `Name` property. It doesn't matter what the old value of the configuration was. So currently we set it to empty string because we read the null as empty string. If you expect us to read the `null` value, then `Name` will be set to `null`. and you shouldn't end up with `Test` value at all anyway.

**Comment by tarekgh** [comment] 2023-02-08 23:48
> Because of the IsAdmin value is true.Now the setting behavior of the two properties is inconsistent, one is set with the default value, and the other is set with an empty string

The default value of the Boolean is `false` and not `true`. So, it is not setting it to the default.

**Comment by tarekgh** [comment] 2023-02-09 00:07
> Name sets the default value to Test.IsAdmin sets the default value to true.When they all read null values, one sets the default value and one sets an empty string

This is because the `null` configuration value is read as empty string. Cannot convert the empty string to a Boolean value, which is why couldn't change the `IsAdmin` property value. For the `Name` property, we read the `null` configuration value as empty string and set it to the property of type `string`.  Does this answer your question?

**Comment by tarekgh** [comment] 2023-02-09 00:54
> I think, like https://github.com/dotnet/runtime/issues/36510, should be set to null

What should be set to null? You cannot set null to Boolean property.

**Comment by tarekgh** [comment] 2023-02-09 01:21
Let me explain. Currently we read the `null` values from the configurations as empty string. That is what the issue https://github.com/dotnet/runtime/issues/36510 is tracking to fix this behavior. Because is https://github.com/dotnet/runtime/issues/36510 still not fixed, we are currently reading the value as empty string. Then we try to bind the empty string value to the property `public bool? IsAdmin { get; set; } = true;` . Meaning we need to convert the empty string to the type `bool?`. This conversion will just fail because cannot convert string type to the `bool?` type. Then we'll not set anything to this property. 

When we fix https://github.com/dotnet/runtime/issues/36510, this should work as we'll be able to read the configuration value as `null` and then assign it to the property. In other word, you have the same issue mentioned in https://github.com/dotnet/runtime/issues/36510.
