### ISSUE TITLE
Test failure JIT\\jit64\\localloc\\eh\\eh03_small\\eh03_small.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#65883] opened 2022-02-25 08:16 UTC
Run: [runtime-coreclr outerloop 20220224.5](https://dev.azure.com/dnceng/public/_build/results?buildId=1631558&view=ms.vss-test-web.build-test-results-tab&runId=45235942&resultId=101213&paneView=debug)

Failed test:
```
R2R-CG2 windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open

- JIT\\jit64\\localloc\\eh\\eh03_small\\eh03_small.cmd
- JIT\\jit64\\gc\\misc\\fgtest1\\fgtest1.cmd
- JIT\\jit64\\gc\\misc\\struct4_2\\struct4_2.cmd
- JIT\\jit64\\gc\\misc\\struct3_5\\struct3_5.cmd
- JIT\\jit64\\localloc\\eh\\eh03_large\\eh03_large.cmd
- JIT\\jit64\\gc\\misc\\structref1_1\\structref1_1.cmd
- JIT\\jit64\\localloc\\zeroinit\\zeroInit01_small\\zeroInit01_small.cmd
- JIT\\jit64\\verif\\sniff\\fg\\ver_fg_13\\ver_fg_13.cmd
- JIT\\jit64\\regress\\vsw\\524070\\test1\\test1.cmd
- JIT\\jit64\\gc\\misc\\9_and_alloca2\\9_and_alloca2.cmd
- JIT\\jit64\\regress\\vsw\\528315\\simple-repro\\simple-repro.cmd
- JIT\\jit64\\eh\\FinallyExec\\noJIT\\jit64\\regress\\vsw\\539509\\test1\\test1.cmd
- JIT\\jit64\\regress\\vsw\\539509\\test1\\test1.cmd
- JIT\\jit64\\regress\\ndpw\\14888\\objectusedonlyinhandler\\objectusedonlyinhandler.cmd
- JIT\\jit64\\gc\\misc\\structret6_3\\structret6_3.cmd
- JIT\\jit64\\regress\\vsw\\404708\\test\\test.cmd
- JIT\\jit64\\localloc\\unwind\\unwind02_large\\unwind02_large.cmd
- JIT\\jit64\\gc\\misc\\**
- JIT\\jit64\\regress\\**
- JIT\\jit64\\localloc\\**
```
**One of error message:**
```
Could Not Find C:\h\w\B8160A6E\w\97EF089A\e\JIT\jit64\localloc\eh\eh03_small\IL-CG2\composite-r2r.dll
Could Not Find C:\h\w\B8160A6E\w\97EF089A\e\JIT\jit64\localloc\eh\eh03_small\eh03_small.dll.rsp
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'System.Diagnostics.Tracing, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The module was expected to contain an assembly manifest.
File name: 'System.Diagnostics.Tracing, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
at ILCompiler.Program.Run(String[] args)
at ILCompiler.Program.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\B8160A6E\w\97EF089A\uploads\Reports\JIT.jit64\localloc\eh\eh03_small\eh03_small.output.txt
Raw output:
BEGIN EXECUTION
eh03_small.dll
localloc_common.dll
2 file(s) copied.
Response file: C:\h\w\B8160A6E\w\97EF089A\e\JIT\jit64\localloc\eh\eh03_small\eh03_small.dll.rsp
C:\h\w\B8160A6E\w\97EF089A\e\JIT\jit64\localloc\eh\eh03_small\IL-CG2\eh03_small.dll
-o:C:\h\w\B8160A6E\w\97EF089A\e\JIT\jit64\localloc\eh\eh03_small\eh03_small.dll
--targetarch:x64
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\B8160A6E\p\System..dll
-r:C:\h\w\B8160A6E\p\Microsoft..dll
-r:C:\h\w\B8160A6E\p\mscorlib.dll
-r:C:\h\w\B8160A6E\p\netstandard.dll
-O
" "dotnet" "C:\h\w\B8160A6E\p\crossgen2\crossgen2.dll" @"C:\h\w\B8160A6E\w\97EF089A\e\JIT\jit64\localloc\eh\eh03_small\eh03_small.dll.rsp"   -r:C:\h\w\B8160A6E\w\97EF089A\e\JIT\jit64\localloc\eh\eh03_small\IL-CG2*.dll"
Crossgen2 failed with exitcode - -532462766
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\B8160A6E\p
C:\h\w\B8160A6E\w\97EF089A\e\JIT\jit64\localloc\eh\eh03_small\eh03_small.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_jit64._localloc_eh_eh03_small_eh03_small_._localloc_eh_eh03_small_eh03_small_cmd()
```

**Comment by trylek** [comment] 2022-04-04 20:27
Closing as duplicate of: https://github.com/dotnet/runtime/issues/65646

**Closed by trylek** 2022-04-04 20:27 UTC
Labels: os-windows, arch-x64, area-crossgen2-coreclr, blocking-outerloop
