### ISSUE TITLE
Regex CaptureCollection.CopyTo throwing ArrayTypeMismatchException

### ISSUE THREAD

**Issue by GSPP** [dotnet/runtime#41143] opened 2020-08-21 07:51 UTC
It is possible to get `CaptureCollection.CopyTo` to throw an `ArrayTypeMismatchException`. I believe this is one of the "forbidden" exception types that should not be thrown from public APIs.

        public static void RegexGroupRepro()
        {
            var match = Regex.Match("x", "(?<g>(.*))(?<g>(.*))");
            var captureCollection = match.Groups[3].Captures;
            captureCollection.CopyTo((Capture[])new Group[captureCollection.Count], 0);
        }

This alternative code can throw an `InvalidCastException`:

            captureCollection.CopyTo((Array)new Group[captureCollection.Count], 0);

The problem is that, due to array variance, an incompatible target array can be accepted. In my view, this is an API usage error and should throw `ArgumentException`. Currently, the exception is encountered only when there are elements to copy. It should be thrown consistently even for zero-length copies.

I had trouble minimizing the repro because I do not fully understand the `Regex` object model. I do not understand the design.

**Comment by eerhardt** [comment] 2020-09-10 23:06
I'm moving this issue to the `System.Collections` area, since this is a larger issue - not specific to `System.Text.RegularExpressions`.

I'm not sure where it is documented that `ArrayTypeMismatchException` is a "forbidden" exception type. Looking at https://docs.microsoft.com/en-us/dotnet/api/system.arraytypemismatchexception it says:

> ArrayTypeMismatchException is thrown when the system cannot convert the element to the type declared for the array. For example, an element of type String cannot be stored in an Int32 array because conversion between these types is not supported. It is generally unnecessary for applications to throw this exception.

Basically this means "don't create and throw this exception yourself".  But it doesn't mean this exception can never occur. It can occur when you use the wrong array type. So I have a feeling this issue will get resolved as "By Design".

**Comment by eiriktsarpalis** [comment] 2020-11-09 20:03
This is a known problem of array covariance that is not specific to C#. I'm closing as by-design.

**Closed by eiriktsarpalis** 2020-11-09 20:03 UTC
Labels: area-System.Collections
