### ISSUE TITLE
GetGenericParameterConstraints() method changes on Net8

### ISSUE THREAD

**Issue by bifacil** [dotnet/runtime#107832] opened 2024-09-14 18:18 UTC
### Description

I'm migrating a project from Net6 to Net8 and I've found a breaking change...

The correct behavior is on Net6 (I believe)

### Reproduction Steps

This VB test pass on Net6, but does not in Net8

```
<TestMethod> Public Sub TestGetGenericTypeDefinitionMethod()
      Dim parameterConstraint = GetType(Nullable(Of)).GetGenericArguments.Single.GetGenericParameterConstraints.SingleOrDefault
      Assert.IsNotNull(parameterConstraint)
      Assert.AreEqual(GetType(System.ValueType), parameterConstraint)
End Sub
```
### Expected behavior

The test should pass.

I believe GetGenericParameterConstraints() should return  `GetType(System.ValueType)` since this is the type definition:

```
public partial struct Nullable<T> where T : struct
{
   [...]
}
```

### Actual behavior

The test fails.

It retuns Null.

### Regression?

Yes. It worked on Net6

### Configuration

8.0.304

### Other information

I've not found any remark on "GetGenericParameterConstraints" method documentation, so I expect the same behaviour on Net6 and Net8.

**Comment by jkotas** [comment] 2024-09-15 06:07
Thank you for reporting this issue. It is duplicate of https://github.com/dotnet/runtime/issues/96336 that was fixed by https://github.com/dotnet/runtime/pull/96358 for .NET 9.

How difficult is to work around this issue in your project that targets .NET 8?

**Comment by bifacil** [comment] 2024-09-15 09:24
Ok. Thanks.

Yes. I will find a workaround.

**Closed** 2024-09-15 14:09 UTC
Labels: area-ReadyToRun-coreclr, untriaged
