### ISSUE TITLE
Linq generation issue

### ISSUE THREAD

**Issue by OliverAcosta** [dotnet/runtime#100827] opened 2024-04-09 16:57 UTC
### Description

Suppose having this code, you take the first element and search for it in the collection, this must return true, but it return false,
LinQ generate a code when one of those methods is called [First, FirstOrDefault]
and other code when the contains method is called,
for that reason differents results are storage in memory
and the last code returns false instead of true
the problem is solved calling the method To List or toArray

 var strings = Enumerable.Range(1, 100).Select(m => $"{ Convert.ToChar(Random.Shared.Next(97, 122))}{Convert.ToChar(Random.Shared.Next(97, 122))}{Convert.ToChar(Random.Shared.Next(97, 122))}");
 var str = strings.FirstOrDefault();
 Console.WriteLine(strings.Contains(str));

### Reproduction Steps

 var strings = Enumerable.Range(1, 100).Select(m => $"{ Convert.ToChar(Random.Shared.Next(97, 122))}{Convert.ToChar(Random.Shared.Next(97, 122))}{Convert.ToChar(Random.Shared.Next(97, 122))}");
 var str = strings.FirstOrDefault();
 Console.WriteLine(strings.Contains(str));
// prints False but waited result must be True

### Expected behavior

Must prints true when code is executed

### Actual behavior

prints false when code is executed

### Known Workarounds

using method, like ToArray or ToList

### Configuration

Any cpu | AMD 64

**Comment by huoyaoyuan** [comment] 2024-04-09 17:45
LINQ expressions are lazy, it only runs when you ask for its result. Since your expression contains `Random`, it's expected that every run returns different result. Calling `FirstOrDefault` multiple times will return different results too.

**Comment by CyrusNajmabadi** [comment] 2024-04-10 00:17
Closing out as by design.  As you mentioned, the workaround is:

> using method, like ToArray or ToList

That's the *expected* behavior here as it now realizes all the elements and makes an unchanging list where they are stored in.  If you do not do this, you have a lazy IEnumerable that will run the .Range and .Select each time the enumeration is enumerated.

**Closed by CyrusNajmabadi** 2024-04-10 00:17 UTC
Labels: area-System.Linq, untriaged
