### ISSUE TITLE
[Mono] Fix detection of static readonly field re-initialization via reflection

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#37899] opened 2020-06-15 12:22 UTC
Port https://github.com/dotnet/runtime/pull/37849 to Mono and re-enable the test

**Comment by lambdageek** [comment] 2020-06-22 16:00
Duplicate of https://github.com/dotnet/runtime/issues/37903

**Closed** 2020-06-22 16:00 UTC
Labels: area-System.Reflection, runtime-mono, untriaged
