### ISSUE TITLE
System Management aka WMI isn't working on ARM64

### ISSUE THREAD

**Issue by AathifMahir** [dotnet/runtime#63137] opened 2021-12-26 13:25 UTC
Hi,

I have been in the process of Rewriting my UWP App that Runs Fulltrust process to Windows App SDK .Net 6 App but the issue here is ARM64 Support, Currently System Management that comes with .NET 6 doesn't work on ARM64 but I know instead of System Management aka WMI, we can use MMI but that also isn't updated in years and needs .Net Framework handle some loads as well, I don't know what way I need to go regards to Management Access, And also Windows 11 removed WMIC Tool from it's core as well.

Now, I need an answer on What way to choose and what are alternatives to WMI and MMI, if there's any and also is there plans to extend the support of built in System Management on . Net to Support ARM64?

For a extra context, My App is an System Diagnostics and Monitoring App

**Comment by ericstj** [comment] 2022-01-05 16:42
This is a duplicate of https://github.com/dotnet/runtime/issues/45143 and https://github.com/dotnet/runtime/issues/59844.  We aren't really experts of WMI, the APIs were developed by the PowerShell team and have been ported by folks here from .NETFramework for compatibility.  They rely on some .NETFramework components that weren't ported so as a result System.Management only works on systems where .NETFramework is present.

Powershell wrote a new set of APIs to access WMI on .NETCore (and cross platform) which is MMI, Microsoft.Management.Infrstructure.  You can see [here](https://github.com/PowerShell/PowerShell/blob/2e8009bf721f3997bbcf710a8c683f94778f97c5/src/System.Management.Automation/System.Management.Automation.csproj#L30) that PowerShell does still rely on MMI even in the latest builds, despite it not being changed in many years: https://github.com/PowerShell/PowerShell#readme has a link to the latest PowerShell for ARM64 which uses MMI and contains the same version from the 2.0.0 package on NuGet.org.

**Closed by ericstj** 2022-01-05 16:42 UTC
Labels: area-System.Management, untriaged
