### ISSUE TITLE
[mono/wasm] NullReferenceException in System.Xml tests

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#39150] opened 2020-07-12 03:02 UTC
Failed in https://github.com/dotnet/runtime/pull/39148. From https://helix.dot.net/api/2019-06-17/jobs/1bd94844-5dbb-42f8-9adb-c581eb8ce25f/workitems/System.Xml.RW.XmlWriterApi.Tests/console:

```
[01:45:37] dbug: test[0]
      [PASS] System.Xml.Tests.TCNamespaceHandling.NS_Handling_19a(utils: XmlWriterUtils { Async = False, WriterType = CharCheckingWriter }, nsHandling: Default, prefix: "xmlns", name: "xml", isAttr: False)
      
[01:45:37] dbug: test[0]
      [FAIL] System.Xml.Tests.TCNamespaceHandling.NS_Handling_19a(utils: XmlWriterUtils { Async = False, WriterType = WrappedWriter }, nsHandling: Default, prefix: "xmlns", name: "xml", isAttr: False)
      
[01:45:37] dbug: test[0]
      System.NullReferenceException : Object reference not set to an instance of an object.
      
[01:45:37] dbug: test[0]
         at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
      
[01:45:37] dbug: test[0]
      [PASS] System.Xml.Tests.TCNamespaceHandling.NS_Handling_19a(utils: XmlWriterUtils { Async = False, WriterType = UTF8Writer }, nsHandling: OmitDuplicates, prefix: "xmlns", name: "xml", isAttr: False)
```

**Comment by akoeplinger** [comment] 2020-07-24 11:05
This looks like a duplicate of https://github.com/dotnet/runtime/issues/39473

**Closed by akoeplinger** 2020-07-24 11:05 UTC
Labels: arch-wasm, area-VM-meta-mono
