### ISSUE TITLE
System.IO.Ports.SerialPort in NET 6 randomly scrambles the byte order of an input stream

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#65080] opened 2022-02-09 15:31 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/SystemIOPortsSerialPort-in-NET-6-rand/1642173)._

---
[severity:I'm unable to use this version]
Reading a known string received periodically, SerialPort randomly misplaces a character out of sequence like this:

[The quick brown fox jumps over the lazy Dog - 13456789]
**2**[The quick brown fox jumps over the lazy Dog - 123456789]
[The quick brown fox jumps over the lazy Dog - 123456789] 
[The quick brown fox jumps over the lazy Dog - 123456789]
[The quick brown fox jumps over he lazy Dog - 1**t**23456789]
[The quick brown fox jumps over the lazy Dog - **123456789]

The above lines were sent on the same CPU from one phisical port (COM4) to another (COM3) every 20ms @ 203400 bauds, using a short NULL modem cable.

Opening the port with the stream already running the problem is more evident. The first thre words of the first line appeard before the third line:

 <-- port open with transmission already running -->
 fox jumps over the lazy Dog - 123456789]
[The quick brown fox jumps over the lazy Dog - 123456789]
**[The quick brown**[The quick brown fox jumps over the lazy Dog - 123456789]
[The quick brown fox jumps over the lazy Dog - 123456789]

After this only one byte (char) is randomly out of place 15 bytes behid its correct position. 
Im using the same SerialPort code to send and receive in both applications. The older one was built with NET Framework 4.7.2 and the new one written with NET 6.
The terminal app using NET Framework 4.7.2 can send and receive without errors. I use that serial port code for many years in my projects.

This is not a new problem. I've seen references to it in other forums ging back to 2012!, and it is amply discussed in [StackOverflow](https://stackoverflow.com/questions/41777981/serialport-basestream-readasync-drops-or-scrambles-bytes-when-reading-from-a-usb/70779632#70779632).
One of the suggestions there is to use ReadAsync() directly from the SerialPort BaseStream, but in my case it doesn't make any difference. In NET 6 SerialPort was moved to a platform extension nugget: **System.IO.Ports.dll**. Is it possible that old code with this bug was used there by mistake?

---
#### Feedback Bot on 1/20/2022, 08:11 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by Jozkee** [comment] 2022-04-01 22:01
From the SO post linked:
> Unfortunatelly after intensive testing, it turns out that my good old terminal program implemented with SerialPort in Net Framework 4.7.2 it ALSO SCRAMBLES characters, but not as nearly as grotesque as the samples above.

So this is not a regression after all.

cc @krwq @wfurt

**Comment by gmgallo** [comment] 2022-04-02 15:32
Yes, that's unfortunately the case. It seems that it has been there forever but, only show up under certain circumstances like continuous streaming, like I did for real time data logging. It won't show up for light use of terminal send and receive, that's why I didn't notice it with my terminal program until recently.  To work around this issue I ended up doing my own SerialComCLR class in C++/CLR that uses native Win32 overlapped I/O.  I'll make it available to anyone who wants it. C++/CLR is more efficient than C# Marshal interfaces to native Win32 system calls.

**Comment by doingnz** [comment] 2022-11-13 02:12
Does it make a difference if hardware flow control used to manage the data flow? Allocation of larger buffers in the .Net application?

**Comment by gmgallo** [comment] 2022-11-16 01:50
I can't tell if that makes a difference.  In my case I don't use flow control, the baud rates I use are 115,200 and higher. But if there is a data overrun I would expect missing bytes, not out of order ones. By default Win32 uses 4kb buffers. You can modify that using Win32 system calls, but I suspect that NET uses double buffering and that is where things go wrong. My C++/CLR implementation present a C# interface to the application program. I haven't experienced any drop or out of order bytes in a continuous stream @ 230400 bauds from an external device. They must fix SerilalCom.

**Comment by quicoli** [comment] 2022-12-01 13:18
@gmgallo could you share your implementation? I'm having issues in my scenario too.... 👍🏻

**Comment by gmgallo** [comment] 2022-12-01 23:42
Hi @quicoli , I have included here a DLL project. Create a solution with this and another C# project to use it. In the C# project add a reference to the DLL project to have access to it. As this was stripped out of a larger project I don't have a simple console project that shows how to use it, but it should be easy to figure out looking at the interface class in SerialComCLR.h file. This is not a commercial grade implementation, it has only the basic functionality that I need. It can be improved in many ways for sure. Let me know if you find any bugs.
[SerialComCLI.zip](https://github.com/dotnet/runtime/files/10136930/SerialComCLI.zip)

**Comment by gmgallo** [comment] 2022-12-01 23:47
.NET 7 is out now. Have MS finally fixed this class?,  Otherwise is the source available somewhere?

**Comment by doingnz** [comment] 2022-12-02 00:13
source: https://github.com/dotnet/runtime/tree/main/src/libraries/System.IO.Ports

**Comment by gmgallo** [comment] 2022-12-02 00:18
Thanks!, I'll have a look at it.

**Comment by jwilo** [comment] 2023-01-15 16:20
> Does it make a difference if hardware flow control used to manage the data flow? Allocation of larger buffers in the .Net application?

No, I'm experiencing the same issue right now in .NET 6, with RTS/CTS flow control. My application is using USB-CDC virtual COM ports (multiple different devices), and I currently have no access to hardware with physical COM ports, but this issue certainly still seems to be present.

**Comment by krwq** [comment] 2023-01-19 15:09
I'd be curious to see if this also repros with simple C/C++ app, at least we could tell if this is windows driver issue or something in our implementation. Then perhaps start modifying simple app to be more and more similar to what we do on Windows and see at which point it starts misbehaving (not exactly most efficient but I don't have other ideas for now). This is not particularly easy to debug given it requires hardware, it's relatively rare and you can't tell if you have a repro until after you already got some random garbage...

Possibly @raffaeler might have some clues (he's working on new implementation in [dotnet/iot repo](https://github.com/dotnet/iot)).

**Comment by jwilo** [comment] 2023-01-19 15:22
Unfortunately/fortunately, I'm going to rescind my previous note. Over the last 24 hours, we have in fact found in this case that the issue was in our hardware driver for new hardware design (on the embedded side of the link, our end) - **not** an issue with System.IO.PortsSerialPlot.

Since resolving said issue, for the avoidance of doubt we are continuously streaming ~23kB/sec at 921600bps - and have run for several hours this morning with **zero** CRC mismatches reported by our protocol, and confirmed by a continuously capturing logic analyser, **and** by mirroring the stream output to a second UART and capturing this as raw hex data and post-processing it to search for errors.

In addition, contrary to so much information on the web stating that the DataReceived event handler is unusable, the handler functions well if one accepts it's limitations. We have the handler configured to raise per received byte, with the handler including a while loop to read more than 1 byte, if there is actually more than 1 byte available, and a separate timing mechanism to perform an explicit read not within the handler, in the case that no event has been raised after x mSec from the last received byte, if a complete frame has not been received.

**Comment by raffaeler** [comment] 2023-01-19 15:29
Thank you for the feedback @jwilo, you saved me a huge amount of time.

We are well aware of the usability issues in the current `SerialPort` class and this is the reason why, [in the dotnet/iot repo](https://github.com/dotnet/iot/issues/1832), we planned to revisit entirely the serial port API.

FYI As I am just a community member and not a MS employee, I can spend a small amount of time in this porting, but it's going on.

**Comment by jwilo** [comment] 2023-01-19 15:34
No problem, it'll be interesting to see how you get on with a new API - I'll keep an eye on progress over there.

Unfortunately, this isn't my issue to close - I just tagged along to @gmgallo's original ticket.

**Comment by krwq** [comment] 2023-01-19 16:18
In that case we'll need more info in this issue seems given above comment from @jwilo it sounds hardware driver issue is more likely the root cause of the original issue than bug on our side but if this is in fact issue with Windows driver or our implementation we will some help to pinpoint the root cause

**Closed** 2023-02-17 06:01 UTC
Labels: no-recent-activity, needs-author-action, area-System.IO.Ports
