### ISSUE TITLE
OOME in RegexIgnoreCaseTests.Unicode_IgnoreCase_Tests on osx-arm64

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#68545] opened 2022-04-26 11:31 UTC
console logs: https://helix.dot.net/api/2019-06-17/jobs/52f72296-9fe2-4b47-b578-43af71d24964/workitems/System.Text.RegularExpressions.Tests/console

noticed in PR: https://github.com/dotnet/runtime/pull/68541

```
/private/tmp/helix/working/A2C008CC/w/AF78093A/e /private/tmp/helix/working/A2C008CC/w/AF78093A/e
  Discovering: System.Text.RegularExpressions.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Text.RegularExpressions.Tests (found 25 of 313 test cases)
  Starting:    System.Text.RegularExpressions.Tests (parallel test collections = on, max threads = 8)
    System.Text.RegularExpressions.Tests.RegexIgnoreCaseTests.Unicode_IgnoreCase_Tests(engine: Compiled, culture: "tr-TR", options: None) [FAIL]
      System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.
      Stack Trace:
           at Regex9773_TryFindNextPossibleStartingPosition(RegexRunner, ReadOnlySpan`1)
           at Regex9773_Scan(RegexRunner, ReadOnlySpan`1)
           at System.Text.RegularExpressions.CompiledRegexRunner.Scan(ReadOnlySpan`1 text)
           at System.Text.RegularExpressions.Regex.ScanInternal(RegexRunnerMode mode, Boolean reuseMatchObject, String input, Int32 beginning, RegexRunner runner, ReadOnlySpan`1 span, Boolean returnNullIfReuseMatchObject)
           at System.Text.RegularExpressions.Regex.RunSingleMatch(RegexRunnerMode mode, Int32 prevlen, String input, Int32 beginning, Int32 length, Int32 startat)
           at System.Text.RegularExpressions.Regex.IsMatch(String input)
           at System.Text.RegularExpressions.Tests.RegexIgnoreCaseTests.<>c__DisplayClass9_0.<<Unicode_IgnoreCase_Tests>g__ValidateMatch|0>d.MoveNext()
        --- End of stack trace from previous location ---
           at System.Text.RegularExpressions.Tests.RegexIgnoreCaseTests.Unicode_IgnoreCase_Tests(RegexEngine engine, String culture, RegexOptions options)
        --- End of stack trace from previous location ---
  Finished:    System.Text.RegularExpressions.Tests
=== TEST EXECUTION SUMMARY ===
   System.Text.RegularExpressions.Tests  Total: 862, Errors: 0, Failed: 1, Skipped: 0, Time: 216.093s
/private/tmp/helix/working/A2C008CC/w/AF78093A/e
----- end Tue Apr 26 04:21:22 PDT 2022 ----- exit code 1 ----------------------------------------------------------
```

**Comment by joperezr** [comment] 2022-05-04 16:53
Closing as a dupe of https://github.com/dotnet/runtime/issues/67793

**Closed by joperezr** 2022-05-04 16:53 UTC
Labels: area-System.Text.RegularExpressions, untriaged
