### ISSUE TITLE
libhostfxr.so is not linked to libpthread and libdl.so

### ISSUE THREAD

**Issue by suihan0104** [dotnet/runtime#86940] opened 2023-05-31 08:45 UTC
### Description

![image](https://github.com/dotnet/runtime/assets/25574734/624aa4d2-005d-4055-9a73-7c63e8f3e21a)

### Reproduction Steps

none

### Expected behavior

![image](https://github.com/dotnet/runtime/assets/25574734/f502641a-4134-432d-8873-e04ae0232c03)

### Actual behavior

none

**Comment by vitek-karas** [comment] 2023-05-31 10:26
This is a duplicate of https://github.com/dotnet/runtime/issues/43036.

**Closed by vitek-karas** 2023-05-31 10:26 UTC
Labels: area-Host, untriaged
