### ISSUE TITLE
Test failure: Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#105926] opened 2024-08-05 01:40 UTC
**Failed in:** [runtime-coreclr jitstress-isas-x86 20240803.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=765128&view=ms.vss-test-web.build-test-results-tab&runId=19471544&resultId=122035&paneView=debug)

**Failed tests:**
```
coreclr windows x86 Checked jitstress_isas_x86_noavx @ Windows.10.Amd64.Open
    - Loader/binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.cmd
```

**Error message:**
```
cmdLine:C:hwC2730A45wA2D108F9eLoaderLoader../binding/tracing/BinderTracingTest.ResolutionFlow/BinderTracingTest.ResolutionFlow.cmd Timed Out (timeout in milliseconds: 1800000 from variable __TestTimeout, start: 8/3/2024 9:48:42 PM, end: 8/3/2024 10:18:42 PM)

Return code:      -100
Raw output file:      C:hwC2730A45wA2D108F9uploadsinding	racingBinderTracingTest.ResolutionFlowoutput.txt
Raw output:
BEGIN EXECUTION
 "C:hwC2730A45pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  BinderTracingTest.ResolutionFlow.dll 
[9:48:43 PM] Running AssemblyLoadContextResolving_ReturnNull...
[9:48:44 PM] Invoking AssemblyLoadContextResolving_ReturnNull...
[9:48:45 PM] Validating bind operation for AssemblyToLoad_Subdirectory...
Waiting for bind events for AssemblyToLoad_Subdirectory (0ms waited) Sleeping for 50ms
Waiting for bind events for AssemblyToLoad_Subdirectory (50ms waited) Sleeping for 50ms
ValidateBindOperation Started
ValidateBindOperation Finished
Test AssemblyLoadContextResolving_ReturnNull finished.
[9:48:45 PM] Running AssemblyLoadContextResolving_LoadAssembly...
[9:48:45 PM] Invoking AssemblyLoadContextResolving_LoadAssembly...
[9:48:45 PM] Validating bind operation for AssemblyToLoad_Subdirectory...
Waiting for bind events for AssemblyToLoad_Subdirectory (0ms waited) Sleeping for 50ms
ValidateBindOperation Started
ValidateBindOperation Started
ValidateBindOperation Finished
ValidateBindOperation Finished
Test AssemblyLoadContextResolving_LoadAssembly finished.
[9:48:45 PM] Running AssemblyLoadContextResolving_NameMismatch...
[9:48:45 PM] Invoking AssemblyLoadContextResolving_NameMismatch...
[9:48:46 PM] Validating bind operation for AssemblyToLoad_Subdirectory...
Waiting for bind events for AssemblyToLoad_Subdirectory (0ms waited) Sleeping for 50ms
ValidateBindOperation Started
ValidateBindOperation Started
ValidateBindOperation Finished
ValidateBindOperation Finished
Test AssemblyLoadContextResolving_NameMismatch finished.
[9:48:46 PM] Running AssemblyLoadContextResolving_MultipleHandlers...
[9:48:46 PM] Invoking AssemblyLoadContextResolving_MultipleHandlers...
[9:48:46 PM] Validating bind operation for AssemblyToLoad_Subdirectory...
ValidateBindOperation Started
ValidateBindOperation Started
ValidateBindOperation Finished
ValidateBindOperation Finished
Test AssemblyLoadContextResolving_MultipleHandlers finished.
[9:48:46 PM] Running AppDomainAssemblyResolve_ReturnNull...
[9:48:46 PM] Invoking AppDomainAssemblyResolve_ReturnNull...
[9:48:46 PM] Validating bind operation for AssemblyToLoad_Subdirectory...
Waiting for bind events for AssemblyToLoad_Subdirectory (0ms waited) Sleeping for 50ms
ValidateBindOperation Started
ValidateBindOperation Finished
Test AppDomainAssemblyResolve_ReturnNull finished.
[9:48:46 PM] Running AppDomainAssemblyResolve_LoadAssembly...
[9:48:46 PM] Invoking AppDomainAssemblyResolve_LoadAssembly...
[9:48:46 PM] Validating bind operation for AssemblyToLoad_Subdirectory...
Waiting for bind events for AssemblyToLoad_Subdirectory (0ms waited) Sleeping for 50ms
ValidateBindOperation Started
ValidateBindOperation Started
ValidateBindOperation Finished
ValidateBindOperation Finished
Test AppDomainAssemblyResolve_LoadAssembly finished.
[9:48:46 PM] Running AppDomainAssemblyResolve_NameMismatch...
[9:48:46 PM] Invoking AppDomainAssemblyResolve_NameMismatch...
[9:48:46 PM] Validating bind operation for AssemblyToLoad_Subdirectory...
Waiting for bind events for AssemblyToLoad_Subdirectory (0ms waited) Sleeping for 50ms
ValidateBindOperation Started
ValidateBindOperation Started
ValidateBindOperation Finished
ValidateBindOperation Finished
Test AppDomainAssemblyResolve_NameMismatch finished.
[9:48:46 PM] Running AppDomainAssemblyResolve_MultipleHandlers...
[9:48:46 PM] Invoking AppDomainAssemblyResolve_MultipleHandlers...
[9:48:46 PM] Validating bind operation for AssemblyToLoad_Subdirectory...
Wai
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor65|0_66(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by jakobbotsch** [comment] 2024-08-05 11:05
Duplicate of #104670

**Closed by jakobbotsch** 2024-08-05 11:05 UTC
Labels: arch-x86, os-windows, JitStress, area-AssemblyLoader-coreclr, untriaged, blocking-clean-ci-optional
