### ISSUE TITLE
AssemblyName.GetPublicKeyToken() may return byte[160] instead of byte[8]

### ISSUE THREAD

**Issue by AArnott** [dotnet/runtime#69153] opened 2022-05-10 19:16 UTC
This is a regression in .NET 7, possibly due to #62866.
This only repros when the `AssemblyName` is obtained from `AssemblyName.GetAssemblyName` when passed the path to an ILMerge output assembly.

Consider the following test:

```cs
string assemblyPath = Environment.ExpandEnvironmentVariables("ILmergeProduced.dll");
Assert.Equal(8, AssemblyName.GetAssemblyName(this.assemblyPath).GetPublicKeyToken()?.Length)
```

That test passes on net472 and net6.0, but fails on net7.0 with:

```
Assert.Equal() Failure
Expected: 8
Actual:   160
```

Consider this [full repro](https://microsoft-my.sharepoint.com/:u:/p/andarno/EdYoRNBPGwVAiWT3E2oKMiIBtn-RC11UMLaJX2R46Uwogw?e=gAQ5nS).
Just open in VS and run tests in Test Explorer (assuming .NET 7 Preview 5 is installed).

**Comment by danmoseley** [comment] 2022-05-10 19:40
Pasting in from chat.
[RuntimeAssembly.cs](https://github.com/dotnet/runtime/blob/main/src/coreclr/System.Private.CoreLib/src/System/Reflection/RuntimeAssembly.cs#L359)
compare
[AssemblyName.cs](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Reflection/AssemblyName.cs#L205)

from
https://github.com/dotnet/runtime/commit/3535e0769f202ae4cd820bea24afd20cee313966#diff-19d4690f1692b70f1b999a94225f396aaa4f7574bd53f0189b83333ee10da4bfL325
seems it was `&= ~` in the original native code.

**Comment by VSadov** [comment] 2022-05-10 19:55
@AArnott - thanks for reporting. I will take a look. 
I wonder if there could be a smaller repro - so that I could put it into a testcase.

**Comment by jkotas** [comment] 2022-05-10 22:51
Related to or duplicate of https://github.com/dotnet/runtime/issues/66785

**Comment by AArnott** [comment] 2022-05-10 23:14
@VSadov the repro is just two lines of code, plus the assembly to be loaded. Maybe check in the assembly?

**Comment by VSadov** [comment] 2022-05-11 00:13
This is not related to https://github.com/dotnet/runtime/issues/66785 . That is a matter of visualizing missing PublicKeyToken - whether we write out `PublicKeyToken=null` or not if the key is missing.

It looks like 6.0 prints that and we should too, but I wonder if that is always the case or there are other hints to consider on whether to print this or not.

**Comment by VSadov** [comment] 2022-05-11 00:15
I assume https://github.com/dotnet/runtime/pull/69157 fixed this.

**Comment by jkotas** [comment] 2022-05-11 00:20
#69157 did not fix this. #69157 affected `Assembly.Load` only. This bug is in `AssemblyName.GetAssemblyName`

**Comment by jkotas** [comment] 2022-05-11 00:25
> This is not related to https://github.com/dotnet/runtime/issues/66785 . That is a matter of visualizing missing PublicKeyToken - whether we write out PublicKeyToken=null or not if the key is missing.

I think you meant to add this comment to #66785 . 

I believe that the problem in both #66785 and #69153 (this issue) is that the `AssemblyName.GetAssemblyName` is setting the flags on `AssemblyName` differently from how they used to be set by internal runtime `GetAssemblyName`.

**Comment by VSadov** [comment] 2022-05-11 01:29
I thought #66785 was an issue similar to the one that was fixed in

https://github.com/dotnet/runtime/blob/215b39abf947da7a40b0cb137eab4bceb24ad3e3/src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/MetadataReader.netstandard.cs#L16

just like with culture name we expect empty instead of `null` when metadata has Nil handle for the token

but maybe this is an issue with flags.

**Comment by jkotas** [comment] 2022-05-11 02:42
> AssemblyName.GetPublicKeyToken() may return byte[160] instead of byte[8]

The runtime unconditionally sets `afPublicKey` on the name read from assembly definition: https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/baseassemblyspec.inl#L310-L311 . Notice that this quirk is only applied to name read from assembly definition, but it is not applied to name read from assembly reference.

`System.Reflection.Metadata` does not have this quirk that compensates for mall-formed assemblies with missing `afPublicKey` bit.

**Comment by AArnott** [comment] 2022-05-11 21:34
@vsadov Yes, check out my full repro (linked from the issue description) to get an actual repro that includes the dll.

**Comment by VSadov** [comment] 2022-05-12 03:08
With @AArnott help I was able to reproduce the bug.   @jkotas  is right, https://github.com/dotnet/runtime/pull/69157 does not fix it. 

The fix in https://github.com/dotnet/runtime/pull/69169 (i.e. forcing PublicKey bit in definitions) is not sufficient either, but having a consistent repro definitely helps.

**Closed** 2022-05-13 02:40 UTC
Labels: area-AssemblyLoader-coreclr, in-pr
