### ISSUE TITLE
Hang in Http1CloseResponseStreamConformanceTests.ReadAsync_CancelPendingTask_ThrowsCancellationException

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#72582] opened 2022-07-21 05:11 UTC
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72553-merge-30e4aed09fae4614b8/System.Net.Http.Functional.Tests/1/console.4c77e0ba.log?helixlogtype=result
```
System.Net.Http.Functional.Tests: [Long Running Test] 'System.Net.Http.Functional.Tests.Http1CloseResponseStreamConformanceTests.ReadAsync_CancelPendingTask_ThrowsCancellationException', Elapsed: 00:13:03

...

Console log: 'System.Net.Http.Functional.Tests' from job 30e4aed0-9fae-4614-b81e-a355a33a0996 (ubuntu.1804.amd64.open.rt) using docker image mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64-20210910135833-1848e19 on a001NDQ
running $HELIX_CORRELATION_PAYLOAD/scripts/7c734ec756dd4f6a854f5070af6b195e/execute.sh in /datadisks/disk1/work/B47B096D/w/B91409D7/e max 900 seconds
...
[EXECUTION TIMED OUT]
Exit Code:-3Executor timed out
```
Not actionable until we get dumps for hangs, but beginning to gather data.

https://github.com/dotnet/runtime/pull/72553

**Comment by stephentoub** [comment] 2022-07-21 11:59
Duplicate of https://github.com/dotnet/runtime/issues/72586

**Closed by stephentoub** 2022-07-21 11:59 UTC
Labels: area-System.Net.Http
