### ISSUE TITLE
No longer able to debug Blazor WebAssembly application after update to 16.10.3

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#55516] opened 2021-07-09 20:27 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/No-longer-able-to-debug-Blazor-WebAssemb/1468962)._

---
[regression] [worked-in:16.10.1]
Created a Blazor WebAssembly app in the version prior to 16.10.3 and was able to debug the application. After updating to 16.10.3, I can no longer debug the application. Process times-out and produces "Failed to launch debug adapter... Promise was canceled".

---
#### Feedback Bot on 7/7/2021, 00:33 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment] 2021-07-12 16:39
@lewing can you please assign someone to help the customer and/or investigate the debugging related issue? Thanks!

**Comment by thaystg** [comment] 2021-07-12 19:05
@Jcparkyn are you using .net5 or .net6?

**Comment by cmanners** [comment] 2021-07-12 21:11
I believe I'm experiencing the same issue. If there is any information I can provide that would be useful to your investigation, please let me know.

**Comment by thaystg** [comment] 2021-07-12 21:12
@cmanners are you using .net5 or .net6?

**Comment by cmanners** [comment] 2021-07-12 21:13
@thaystg I'm using .Net 5.0.

**Comment by thaystg** [comment] 2021-07-12 21:14
Are you creating a Blazor WebAssemblyApp, and what options are you choosing in the creation dialog? HTTPS? What else?

**Comment by cmanners** [comment] 2021-07-12 21:20
I'm creating a Blazor WebAssembly application. I am using IIS Express with SSL disabled, anonymous authentication enabled, and Windows authentication disabled. I remember creating the project with PWA enable.

I created the project some time ago so if you want more specifics, I may need to you steer me to what you're looking for.

**Comment by cmanners** [comment] 2021-07-12 21:43
Here are the verbose logs ([visualstudio-js-debugger.txt](https://github.com/dotnet/runtime/files/6804521/visualstudio-js-debugger.txt)); I'm seeing quite a few messages that read "connect ECONNREFUSED". I tried to connect to the erroring addresses (http://localhost:1039/json/version and http://localhost:1039/json/list) with the browser from using a browser and they returned a result.

Result of call to http://localhost:1039/json/list:
```
[ {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:1039/devtools/page/EA8C7D2A4B50701B616E6C3D34E90B2E",
   "id": "EA8C7D2A4B50701B616E6C3D34E90B2E",
   "title": "about:blank",
   "type": "page",
   "url": "about:blank",
   "webSocketDebuggerUrl": "ws://localhost:1039/devtools/page/EA8C7D2A4B50701B616E6C3D34E90B2E"
}, {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:1039/devtools/page/FE66E29CD874C066F2A2297377223041",
   "id": "FE66E29CD874C066F2A2297377223041",
   "title": "about:blank",
   "type": "page",
   "url": "about:blank",
   "webSocketDebuggerUrl": "ws://localhost:1039/devtools/page/FE66E29CD874C066F2A2297377223041"
} ]
```

**Comment by cmanners** [comment] 2021-07-12 21:46
I created a new Blazor WebAssembly project and the debugger was able to connect without issue.

![image](https://user-images.githubusercontent.com/251596/125359918-4887fa00-e328-11eb-80ef-05d1aa098ccc.png)

![image](https://user-images.githubusercontent.com/251596/125359931-4de54480-e328-11eb-8a97-e252c7ff4ec0.png)

**Comment by thaystg** [comment] 2021-07-12 21:48
Could you share the project that you are getting issues to debug?

**Comment by cmanners** [comment] 2021-07-12 21:56
Unfortunately, without seeking authorization from my employer, I am unable to share the project as a whole at this time.

**Comment by Jcparkyn** [comment] 2021-07-12 22:56
I have the problem when debugging on the master branch of [this project](https://github.com/Jcparkyn/nodexr). It's been a while since I worked on it, so I can't confirm exactly which version of VS it was working on.

**Comment by thaystg** [comment] 2021-07-13 02:37
Could you please paste all the output that is in the Output Window?
Right below: `Verbose logs are written to:`

**Comment by Jcparkyn** [comment] 2021-07-13 08:07
The problem is solved for me after deleting the `debuggerConfiguration-...json` files (of which I had two, not sure why) from the hidden `.vs/ProjectName/config` folder.

**Comment by thaystg** [comment] 2021-07-13 12:42
@cmanners, can you check if you also have more than one `debuggerConfiguration-...json` files ?

**Comment by cmanners** [comment] 2021-07-13 14:10
I only had one file `debuggerConfiguration-...json` file. Removing it resolved my issue.

Examining the files, the only difference between [the old file](https://github.com/dotnet/runtime/files/6809457/debuggerConfiguration-cb028a36-0363-4e61-84fc-858991aa5c1e.json.txt) and [the new file](https://github.com/dotnet/runtime/files/6809460/debuggerConfiguration-cb028a36-0363-4e61-84fc-858991aa5c1e.json.txt) is that the port changed from 1039 to 1050.

**Comment by thaystg** [comment] 2021-07-15 08:35
Closing this issue as we have already reopened the issue for VS team.

**Closed by thaystg** 2021-07-15 08:35 UTC
Labels: arch-wasm, area-Debugger-mono
