### ISSUE TITLE
Assertion failed. Unexpected exception type for connection failure when some Http tests time out

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#62508] opened 2021-12-07 23:04 UTC
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-60463-merge-10bbcef170ed43c99b/System.Net.Http.Functional.Tests/1/console.7b1c1af9.log?sv=2019-07-07&se=2021-12-27T18%3A04%3A53Z&sr=c&sp=rl&sig=YIYBmg5O5Ky4P%2BHh2%2F20%2BBsk3PjbIjjNc76CpQElyms%3D
Console log: 'System.Net.Http.Functional.Tests' from job 10bbcef1-70ed-43c9-9b54-832f9e0c0483 workitem cf4bd566-1f04-4967-b878-0ee69afd7544 (windows.10.amd64.server19h1.es.open.rt) executed on machine a002FTP

For whatever reason, some operation timed out and the assertion does not handle that

https://github.com/danmoseley/runtime/blob/6e470dc03000aecb0ac88cc8c45cbf4f149b4f80/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L2147

```
    System.Net.Http.Functional.Tests.Http1RawResponseStreamZeroByteReadTest.ZeroByteRead_IssuesZeroByteReadOnUnderlyingStream(readMode: AsyncAPM, useSsl: True) [FAIL]
      System.TimeoutException : The operation has timed out.
      Stack Trace:
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/ResponseStreamZeroByteReadTests.cs(117,0): at System.Net.Http.Functional.Tests.Http1ResponseStreamZeroByteReadTestBase.ZeroByteRead_IssuesZeroByteReadOnUnderlyingStream(ReadWriteMode readMode, Boolean useSsl)
        --- End of stack trace from previous location ---
    System.Net.Http.Functional.Tests.Http1ContentLengthResponseStreamZeroByteReadTest.ZeroByteRead_IssuesZeroByteReadOnUnderlyingStream(readMode: AsyncAPM, useSsl: False) [FAIL]
      System.TimeoutException : The operation has timed out.
      Stack Trace:
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/ResponseStreamZeroByteReadTests.cs(125,0): at System.Net.Http.Functional.Tests.Http1ResponseStreamZeroByteReadTestBase.ZeroByteRead_IssuesZeroByteReadOnUnderlyingStream(ReadWriteMode readMode, Boolean useSsl)
        --- End of stack trace from previous location ---
Process terminated. Assertion failed.
Unexpected exception type for connection failure
   at System.Net.Http.HttpConnectionPool.RequestQueue`1.TryFailNextRequest(Exception e) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 2148
   at System.Net.Http.HttpConnectionPool.HandleHttp11ConnectionFailure(Exception e) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1589
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 454
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncMethodBuilderCore.cs:line 38
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Net.Http.HttpConnectionPool.<>c__DisplayClass74_0.<CheckForHttp11ConnectionInjection>b__0() in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 489
   at System.Threading.Tasks.Task`1.InnerInvoke() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:line 503
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 268
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2337
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 715
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.WorkerThread.cs:line 77
   at System.Threading.Thread.StartCallback() in /_/src/coreclr/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs:line 105
```

**Comment by geoffkizer** [comment] 2021-12-07 23:16
This is likely just a bogus assert that should be updated.

**Comment by karelz** [comment] 2021-12-09 16:53
Triage: We expect different exception in the Assert - we should adjust it.

**Comment by DobrovAlexey** [comment] 2022-02-01 07:08
Hi, please specify what kind of exception we should catch? Did I understand correctly that this is a `TimeoutException`?
Thanks.

**Comment by wfurt** [comment] 2022-02-01 18:22
It seems like first step would be adjusting the Assert message to actually show it. I personally doubt it is `TimeoutException `. It would be clear from core dump but it seems like the link above expired so all evidence is done. 

From quick look, it looks like we expect exceptions to be wrapped as `HttpRequestException` but we probably leak some IOException directly. 

It may not be "easy" but we can try to reproduce by adding load to the system & shortening timeous to get local repro.

**Comment by DobrovAlexey** [comment] 2022-02-03 07:10
I found that in `dotnet/runtime` in the `main` branch this code is already missing, and `TryDequeueWaiterForSpecificRequest` no longer accepts `Exception` as input:

https://github.com/dotnet/runtime/blob/7550df8b58452abf4f45518335914070f4f4f54f/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L2228-L2239

These changes were made by this commit:
https://github.com/dotnet/runtime/commit/b4dfd7d067a8523ec5fb9c3247daaffb2dde5341#diff-bc2faad6c76ecb9b115e305763eb55ebfde74de1eee27ed549e5edaabb097a99L2146-R2234

Did I understand correctly that `danmoseley/runtime` is the old version?
https://github.com/danmoseley/runtime/blob/6e470dc03000aecb0ac88cc8c45cbf4f149b4f80/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L2147


Where can I learn more about your release policy?
Thanks

**Comment by wfurt** [comment] 2022-05-26 11:06
did we see any recent failures @rzikm ? If not, we should perhaps close this per notes above.

**Comment by rzikm** [comment] 2022-07-21 12:33
I don't see any recent occurrences of this failure in past 2 months and we don't store console outputs for older failures.

**Comment by karelz** [comment] 2022-07-21 12:37
Triage: The code changed, no occurrences. Closing.

**Closed by karelz** 2022-07-21 12:37 UTC
Labels: area-System.Net.Http, easy, test-bug, test-run-core, up-for-grabs
