### ISSUE TITLE
net core2.1 datatable select Occasionally you don't get the right value

### ISSUE THREAD

**Issue by dengyantao** [dotnet/runtime#33572] opened 2020-03-11 08:19 UTC
net core2.1 datatable select Occasionally you don't get the right value
example：
DataTable dttaxpayable =new DataTable ();
dttaxpayable .Select("idnumber = '" + item.Idnumber + "' ")

**Comment by Wraith2** [comment] 2020-03-13 21:10
duplicate of https://github.com/dotnet/runtime/issues/33466

**Comment by danmosemsft** [comment] 2020-03-15 04:17
Duplicate

**Closed by danmosemsft** 2020-03-15 04:17 UTC
Labels: area-System.Data, untriaged
