### ISSUE TITLE
Modify HttpClientFactory based HttpClient request logging

### ISSUE THREAD

**Issue by johnkors** [dotnet/runtime#44411] opened 2020-11-09 15:37 UTC
Hi,

I saw [this issue for overriding the default logging / altering the log statements](https://github.com/aspnet/HttpClientFactory/issues/141) emitted when doing requests using a HttpClientFactory based HttpClient, which recommends re-implementing the `IHttpMessageHandlerBuilderFilter` for this.

I wanted 2 alterations from the default logging, to reduce the logs:

1) Don't emit 2 log statements for each request, but only one (the default logging emits a start-req, and a end-req log statement)
2) In the single emitted log statement, include the request url.

So reducing [this](https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.Extensions.Http/src/Logging/LoggingHttpMessageHandler.cs#L85):

```
- "Sending HTTP request {HttpMethod} {Uri}");
- "Received HTTP response headers after {ElapsedMilliseconds}ms - {StatusCode}"
```

to 

```
- $"{HttpMethod} {Uri} - {StatusCode} in {ElapsedMilliseconds}ms"
```

I was surprised by [the amount of code I had to write](https://gist.github.com/johnkors/edd89546994ccf5b1a860b0161e06ddb#file-reducedhttpclientfactorylogging-cs-L69) to be able to do this. Is there no easier way to just modify the default log statements..?

**Comment by CarnaViire** [comment] 2021-06-02 15:13
Triage: the solution for that could be to introduce a switch to turn off the default logging. In that case you wouldn't need to write your own `IHttpMessageHandlerBuilderFilter` to remove it, you would be able to just turn it off and add a new custom one. This is a direction we should consider in Future. If you run into this, please upvote the top post to help us prioritize. Thanks!

**Comment by timba** [comment] 2021-09-01 17:18
I also would like to give an example why we need to have possibility to change the default logging output. HTTP logging of `Information` level exposes full `Uri` to logs. Many web APIs accept sensitive information via query string (passwords, tokens, usernames, etc). This means that `Information` level HTTP logs may expose sensitive information which is a potential risk. The only option here for developers is to remove default logging handler, implement custom one and add it to the handlers list, which is quite annoying, as @johnkors mentioned.

Also, I'd propose to look at the HTTP logging from another perspective. If we look into HTTP protocol, TLS secured (HTTPS) messages don't expose query string, only domain is opened, the rest is encrypted (including query string). Taking into account that HTTP logging of `Information` level may be considered as HTTP messaging logging, I'd suggest to remove query string from this level at all in case of HTTPS messages.

**Comment by johnkors** [comment] 2021-12-08 14:59
Decided to create a nuget for what I want. A better API for replacing the default logger sounds interesting, at least if you cannot make the default logging more configurable than it is today.

 https://github.com/johnkors/MinimalHttpLogger

**Comment by CarnaViire** [comment] 2023-06-30 16:08
Duplicate of https://github.com/dotnet/runtime/issues/77312

**Closed by CarnaViire** 2023-06-30 16:08 UTC
Labels: api-suggestion, area-Extensions-HttpClientFactory
