### ISSUE TITLE
Test failure: JIT/Regression/VS-ia64-JIT/V2.0-RTM/b539509/b539509/b539509.dll

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#86263] opened 2023-05-15 18:18 UTC
Regression_4 Work Item
coreclr windows x86 Checked jitstress2_jitstressregs0x1000 @ Windows.10.Amd64.Open

https://dev.azure.com/dnceng-public/public/_build/results?buildId=272907&view=ms.vss-test-web.build-test-results-tab&runId=5390828&paneView=debug

```
set DOTNET_TieredCompilation=0
set DOTNET_JitStress=2
set DOTNET_JitStressRegs=0x1000
```

```
18:47:24.904 Running test: JIT/Regression/VS-ia64-JIT/V2.0-RTM/b539509/b539509/b539509.dll
Testing AA::Method1
Exception handled: System.InvalidCastException: Unable to cast object of type 'BB' to type 'AA`6[System.SByte,System.Byte,System.UInt32,System.UInt32,System.Int64,System.Boolean]'.
   at App.TestEntryPoint()
Testing AA::Static1
Exception handled: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at AA`6.Static1(TF param1)
   at App.TestEntryPoint()
Testing AA::Static2
Exception handled: System.InvalidCastException: Unable to cast object of type 'AA`6[System.SByte,System.Byte,System.UInt32,System.UInt32,System.Int64,System.Boolean]' to type 'System.SByte[][,,,]'.
   at AA`6.Static2(UInt64 param1, Int16 param2, UInt32& param3, TA& param4)
   at App.TestEntryPoint()
Testing AA::Static3
Exception handled: System.NullReferenceException: Object reference not set to an instance of an object.
   at AA`6.Static3(TestEnum param1, Int16 param2)
   at App.TestEntryPoint()
Testing AA::Static4
Testing AA::Static5
App Exit Code: 3
Expected: 100
Actual: 3
END EXECUTION - FAILED
FAILED
```

**Comment by BruceForstall** [comment] 2023-05-15 18:19
@markples This test was recently merged. Maybe it needs RequiresProcessIsolation?

**Comment by BruceForstall** [comment] 2023-05-15 18:23
Also failing: JIT/jit64/regress/vsw/539509/test1_539509/test1_539509.dll

with:
```
et DOTNET_TieredCompilation=0
set DOTNET_JitStress=2
set DOTNET_JitStressRegs=8
```

This is almost exactly the same test, in a different part of the tree.

https://dev.azure.com/dnceng-public/public/_build/results?buildId=273272&view=ms.vss-test-web.build-test-results-tab&runId=5400218&resultId=120126&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by markples** [comment] 2023-05-15 20:40
JIT/Regression was merged a while ago, though I did just change the groups around. It seems unlikely that the group change is important since the test is failing in the other location as well. My guess is that it is an actual failure. I'd be very interested in knowing if it was merged group specific since we haven't seen that with JitStress before.

**Comment by markples** [comment] 2023-05-18 22:22
Duplicate of #86265

**Comment by markples** [comment] 2023-05-18 22:22
Same assertion `sc->stack_limit != 0`, same intermittent repro nature

**Closed** 2023-05-19 17:25 UTC
Labels: JitStress, area-CodeGen-coreclr, blocking-clean-ci-optional
