### ISSUE TITLE
Azure Function Project's `func start` results in Could not load file or assembly 'System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

### ISSUE THREAD

**Issue by eat-sleep-code** [dotnet/runtime#78161] opened 2022-11-10 15:52 UTC
I am attempting to update an existing Azure Function to use .NET 7 (which according to [this post](https://devblogs.microsoft.com/dotnet/dotnet-7-comes-to-azure-functions/) should be supported).

- I installed the latest SDK on my Intel-based Macbook running macOS Ventura, and it appears to have installed correctly.

   ```
   dotnet --list-sdks
   7.0.100 [/usr/local/share/dotnet/sdk]
   ```

  ```
  dotnet --list-runtimes
  Microsoft.AspNetCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  ```
- I updated my .csproj file:
  ```
  <Project Sdk="Microsoft.NET.Sdk">
	  <PropertyGroup>
		  <TargetFramework>net7.0</TargetFramework>
		  <AzureFunctionsVersion>v4</AzureFunctionsVersion>
	  </PropertyGroup>
	  <ItemGroup>
		  <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.OpenApi" Version="1.4.0" />
		  <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.1.3" />
	  </ItemGroup>
	  <ItemGroup>
		  <None Update="host.json">
			  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  </None>
		  <None Update="local.settings.json">
			  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			  <CopyToPublishDirectory>Never</CopyToPublishDirectory>
		  </None>
	  </ItemGroup>
  </Project>
  ```

- I updated references to `net6.0` to be `net7.0` in **.vscode/settings.json** and **.vscode/tasks.json**
- I deleted the existing **/bin** and **/obj** folders
- I ran `dotnet restore` and all projects are up-to-date.
- I ran `dotnet build` and the project builds without issue.
  ```
  MSBuild version 17.4.0+18d5aef85 for .NET
    Determining projects to restore...
    All projects are up-to-date for restore.
    Functions.LeadCapture -> /Volumes/Data/SRC/Functions.LeadCapture/bin/Debug/net7.0/Functions.LeadCapture.dll
  
  Build succeeded.
      0 Warning(s)
      0 Error(s)
  
  Time Elapsed 00:00:02.60
  ```
- **I then attempt to run `func start` and this is where things fall apart**
  ```
  MSBuild version 17.4.0+18d5aef85 for .NET
    Determining projects to restore...
    All projects are up-to-date for restore.
    Functions.LeadCapture -> /Volumes/Data/SRC/Functions.LeadCapture/bin/output/Functions.LeadCapture.dll
  
  Build succeeded.
      0 Warning(s)
      0 Error(s)
  
  Time Elapsed 00:00:02.91
  
  
  
  Azure Functions Core Tools
  Core Tools Version:       4.0.4829 Commit hash: N/A  (64-bit)
  Function Runtime Version: 4.11.2.19273
  
  [2022-11-10T15:49:40.532Z] Found /Volumes/Data/SRC/Functions.LeadCapture/Functions.LeadCapture.csproj. Using for user secrets file configuration.
  [2022-11-10T15:49:41.751Z] The 'Get' function is in error: Unable to load one or more of the requested types.
  [2022-11-10T15:49:41.751Z] Could not load file or assembly 'System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
  [2022-11-10T15:49:41.751Z] 
  [2022-11-10T15:49:41.751Z] Could not load file or assembly 'System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
  [2022-11-10T15:49:41.751Z] 
  [2022-11-10T15:49:41.751Z] Could not load file or assembly 'System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
  [2022-11-10T15:49:41.751Z] 
  [2022-11-10T15:49:41.751Z] Could not load file or assembly 'System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
  [2022-11-10T15:49:41.751Z] .
  [2022-11-10T15:49:41.751Z] The 'Upsert' function is in error: Unable to load one or more of the requested types.
  [2022-11-10T15:49:41.751Z] Could not load file or assembly 'System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
  [2022-11-10T15:49:41.752Z] 
  [2022-11-10T15:49:41.752Z] Could not load file or assembly 'System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
  [2022-11-10T15:49:41.752Z] 
  [2022-11-10T15:49:41.752Z] Could not load file or assembly 'System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
  [2022-11-10T15:49:41.752Z] 
  [2022-11-10T15:49:41.752Z] Could not load file or assembly 'System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
  [2022-11-10T15:49:41.752Z] .
  
  Functions:
  
          RenderOAuth2Redirect: [GET] http://localhost:7071/api/oauth2-redirect.html
  
          RenderOpenApiDocument: [GET] http://localhost:7071/api/openapi/{version}.{extension}
  
          RenderSwaggerDocument: [GET] http://localhost:7071/api/swagger.{extension}
  
          RenderSwaggerUI: [GET] http://localhost:7071/api/swagger/ui
  
  For detailed output, run func with --verbose flag.
  [2022-11-10T15:49:46.529Z] Host lock lease acquired by instance ID '0000000000000000000000003D3311EF'.
  ```

- I attempt ` func start --target-framework net7.0` and got the same result.   I attempted restarting the entire computer and still get the same result.

**Comment by davidfowl** [comment] 2022-11-13 07:12
Maybe file an issue here https://github.com/Azure/azure-functions-host/issues

**Comment by eat-sleep-code** [comment] 2022-11-14 16:29
@davidfowl  I am not sure it is related to Azure Functions, or if that is just a coincidence.    It is the only .NET 7 project I have thus far that relies on System.Net

**Comment by davidfowl** [comment] 2022-11-14 17:43
@eat-sleep-code easy to verify by trying to reproduce the issue outside of azure functions. If you can then we should dig in, if you can't then I'd suggest asking on the functions repository.

**Comment by eat-sleep-code** [comment] 2022-11-14 19:32
@davidfowl  well, you may be right.   Just spun up an empty web project and made a reference to System.Net.Http.HttpClient and get no build error.   I will open the ticket over there.

**Comment by ManickaP** [comment] 2022-11-21 10:29
@eat-sleep-code I'll close this issue for now, since it looks like an azure function problem. If this proves to be a runtime problem, please feel free to re-open, thanks.

**Closed by ManickaP** 2022-11-21 10:29 UTC
Labels: area-System.Net.Http, untriaged
