### ISSUE TITLE
`RequestReJITWithInliners` silently fails for debug modules if `COMPLUS_ForceEnc` is enabled

### ISSUE THREAD

**Issue by schmittjoseph** [dotnet/runtime#91963] opened 2023-09-12 21:48 UTC
### Description

If an application launches with `COMPLUS_ForceEnc=1` set, `ICorProfilerInfo10::RequestReJITWithInliners` silently fails for any methods that belong to a debug module.
- `RequestReJITWithInliners` will return `S_OK`.
- Neither `GetReJITParameters` nor `ReJITError` will be called.
- If `RequestReJITWithInliners` is called with multiple methods, some in debug modules and others in release modules, the ones in release modules will work as expected.

### Reproduction Steps

1. Set `COMPLUS_ForceEnc=1` before launching an application with debug modules.
2. Call `RequestReJITWithInliners` on one or more methods that belong to a debug module.

### Expected behavior

Any of the following:
1. A rejit is triggered.
2. `RequestReJITWithInliners ` returns a non-success HRESULT.
3. The `ReJITError` callback is invoked for the method(s).

### Actual behavior

- The rejit doesn't occur, and no errors are reported.

### Configuration

Tested on .net 7+

**Comment by BruceForstall** [comment] 2023-09-13 00:10
@tommcdon Looks like a diag issue?

**Comment by davmason** [comment] 2023-10-24 23:02
@schmittjoseph EnC and ReJIT use different methods to version code, it is expected that they won't work together. Is there a scenario where you need EnC and ReJIT on the same module? We would have to do some non trivial feature work to light that scenario up

**Comment by schmittjoseph** [comment] 2023-10-25 21:59
>  EnC and ReJIT use different methods to version code, it is expected that they won't work together. Is there a scenario where you need EnC and ReJIT on the same module?

We don't expect EnC and ReJIT to work together -- rather the ask is for the ReJIT APIs to fail for modules with EnC enabled instead of the current behavior of returning success but having no effect. This way the profiler isn't expecting a ReJIT to occur and can act accordingly.

In our case another piece of tooling was incorrectly always setting `COMPLUS_ForceEnc` on applications even if it didn't intend to use EnC, resulting in our profiler silently failing.

There are workarounds, such as a profiler checking `COMPLUS_ForceEnc` first, but it seems reasonable to guard this at the API level.

**Comment by davmason** [comment] 2024-02-16 09:09
@schmittjoseph I opened a fix for this in #98546, would you be able to verify it fixes your scenario?

**Comment by weltkante** [comment] 2024-02-16 09:40
> Reproduction Steps [...]

Note that there's an easy way to reproduce when starting the process from a VS project, since VS sets these flags when hot reload is enabled in the options, and even does so when not attaching a debugger. See [this](https://github.com/microsoft/CLRInstrumentationEngine/issues/572#issuecomment-1796848839) for the relevant options,  and I have a standalone repro in  #95172 that can be cloned and executed in debugger.

Just FYI in case it helps testing the fix. I'm not used to building my own runtime/sdk so I can't easily test myself, will have to wait until it flows into the daily builds.

**Closed** 2024-02-17 08:08 UTC
Labels: enhancement, area-Diagnostics-coreclr, in-pr
