### ISSUE TITLE
PushRange empty Array throws exception

### ISSUE THREAD

**Issue by jtleaming** [dotnet/runtime#68228] opened 2022-04-19 18:59 UTC
### Description

When using `PushRange(T[] Items)`, if the array is empty an exception is thrown. 

However, the logic in `PushRange(T[] items, int startIndex, int count)` suggests an empty array should return from the function with no adverse effects.

### Reproduction Steps

```C#
var conStack = new ConcurrentStack<string>();
var anArray = Array.Empty<string>();

conStack.PushRange(anArray); //currently this would throw an exception

conStack.PushRange(anArray, 0, anArray.Length); //currently this also throw an exception

```

### Expected behavior

I would expect no exception to be thrown, and the function to just return, as shown in the example below.

The code below is taken from  `public class ConcurrentStack<T>`, except currently `if(count == 0)` happens after `ValidatePushPopRangeInput`. 

 public void PushRange(T[] items, int startIndex, int count)
        {
            if (count == 0)
                return;

            ValidatePushPopRangeInput(items, startIndex, count);
            Node head, tail;
            head = tail = new Node(items[startIndex]);
            for (int i = startIndex + 1; i < startIndex + count; i++)
            {
                Node node = new Node(items[i]);
                node._next = head;
                head = node;
            }

            tail._next = _head;
            if (Interlocked.CompareExchange(ref _head, head, tail._next) == tail._next)
            {
                return;
            }

            // If we failed, go to the slow path and loop around until we succeed.
            PushCore(head, tail);
        }

### Actual behavior

Adding empty array with `PushRange` results in a `ArgumentOutOfRangeException`. 

### Known Workarounds

You can check the array before calling `PushRange`, but this is already a check in the `PushRange` function.

### Configuration

.net 6.0.1
Windows 11
x86
No config specific
No Blazor

### Other information

I wasn't sure if I should submit this as an API proposal, but that seems like it's used for new APIs.

**Comment by danmoseley** [comment] 2022-04-20 01:27
I agree, this is clearly unintentional given the comment
```c#
            // No op if the count is zero
            if (count == 0)
                return;
```
and it's also more useful to save the caller having to check for zero.

Thanks for pointing it out. Do you want to offer a PR, with a small test?

**Comment by stephentoub** [comment] 2022-04-20 01:34
This is a duplicate of https://github.com/dotnet/runtime/issues/62121, which was fixed by https://github.com/dotnet/runtime/pull/62126.

**Closed by stephentoub** 2022-04-20 01:34 UTC
Labels: area-System.Collections, untriaged
