### ISSUE TITLE
Ensure that the ref/*.cs files are consistent with what tooling produces

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#83166] opened 2023-03-08 23:13 UTC
The various `ref/*.cs` files are meant to be generated via the arcade tooling, such as `GenApi`.

However, several files, such as `ref/System.Runtime.cs` are out of sync with the tooling and can have non-trivial diffs if you try to add new APIs via said tooling.

We should take care of resolving these diffs so that adding new APIs isn't problematic.

**Comment by tannergooding** [comment] 2023-03-08 23:13
CC. @ericstj - Is there an easy way to run the tooling for "everything" to try and find out what is actually out of sync?

**Comment by ViktorHofer** [comment] 2023-03-09 08:48
Duplicate of https://github.com/dotnet/runtime/issues/26187. Closing.

**Closed by ViktorHofer** 2023-03-09 08:48 UTC
Labels: area-Infrastructure-libraries, untriaged
