### ISSUE TITLE
Obsolete unused static ServicePointManager members

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#62770] opened 2021-12-14 13:15 UTC
To avoid extra warnings for users migrating from .NET Framework, only the factory methods like `FindServicePoint` were marked as obsolete.

We should either obsolete the whole class or also mark unused static members like `ReusePort`, `SetTcpKeepAlive` as `[Obsolete]`.
dotnet/dotnet-api-docs#6867

**Comment by karelz** [comment] 2021-12-14 17:51
Triage:
- We should identify all places where it is used in .NET Core code base -- e.g. [`TlsStream`](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Common/src/System/Net/TlsStream.cs)
    - Then decide what to do about all the places. If they are already obsolete, all should be fine.
- Statics could be mistakenly used in combo with `HttpClient`, so they should be obsoleted (as they don't do anything to HttpClient on .NET Core).
- We should aim to obsolete the entire class (and check that nothing uses it in our code base). Hopefully we can just extend the existing obsoletion.

We should clean it up in 7.0.

**Comment by karelz** [comment] 2023-01-31 17:42
Duplicate of #71836

**Closed by karelz** 2023-01-31 17:42 UTC
Labels: bug, area-System.Net.Http
