### ISSUE TITLE
QuicListener.AcceptConnectionAsync rethrowing exceptions

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#75115] opened 2022-09-06 07:00 UTC
`QuicListener.AcceptConnectionAsync` throws in the following scenarios (that I know of):

1. `QuicException` with `QuicError.OperationAborted`. Happens when the listener is disposed while waiting for a connection.
2. `ObjectDisposedException`. Happens when `AcceptConnectionAsync` is called after disposing the listener.
3. `AuthenticationException`. Happens when the client and server fail to negotiate a connection, e.g. server has an invalid certificate and the client rejects it.
4. `ArgumentException`. Happens when the options returned from the callback are invalid. e.g. a server certificate isn't configured in the callback.
5. Any exception is thrown in the callback. Happens when an exception is thrown in the callback and is then rethrown from `AcceptConnectionAsync`.

I think 5 is very broad. There should be a way to disambiguate a rethrown exception from important exceptions that are used to signal the health of the listener. e.g. someone could accidentally throw an ODE in the callback, which the code that calls the listener interprets as the listener is shut down and to stop listening for connections.

I think the exception from 5, and maybe also 3 and 4, should be wrapped in another exception that says an attempt to accept a connection failed. The inner exception then provides more detail.

**Comment by karelz** [comment] 2022-09-06 07:05
Split from discussion: https://github.com/dotnet/aspnetcore/pull/43730#issuecomment-1236922210

It sounds reasonable to me. @ManickaP @rzikm @CarnaViire @wfurt any thoughts?
If we agree, we should try to do it in 7.0 to prevent breaking changes in 8.0 ... even though QUIC APIs are preview, so we will be allowed to make them.

**Comment by JamesNK** [comment] 2022-09-06 07:10
Currently, aspnetcore has to assume any exception thrown from `AcceptConnectionAsync` can be retried, unless it is OperationAborted or ODE.

```cs
while (true)
{
    try
    {
        var connection = _listener.AcceptConnectionAsync();
    }
    catch (ObjectDisposedException)
    {
        return null;
    }
    catch (QuicException ex) when (ex.QuicError == QuicError.OperationAborted)
    {
        return null;
    }
    catch (Exception)
    {
        // retry
    }
}
```
This feels a little dangerous. What happens if a bug causes `AcceptConnectionAsync` to break and throw for another reason? We'd be stuck in this loop.

It would be nice if there was a known exception type (or QuicError type) for failed accepting of connections to check for. Unexpected exceptions could then be logged and exit this loop.

**Comment by karelz** [comment] 2022-09-06 16:41
Triage: We should look at how we deal with these things in `HttpClient` and `SslStream` callbacks.
- `HttpClient` wraps it with `HttpWebRequest` exception (per @MihaZupan).

Note: We might still decide to wrap exceptions in QUIC APIs.

**Comment by karelz** [comment] 2022-09-07 10:56
Duplicate of #75184

**Comment by karelz** [comment] 2023-07-18 12:43
@wfurt why did you open it? @ManickaP thinks it should be closed with your last 2 PRs merged yesterday.

**Comment by wfurt** [comment] 2023-07-18 14:01
mostly. We still should look at #1 IMHO e.g. Disposing listener should throw ODE. The changes addressed $5 e.g. we wrap callback exceptions now.

**Comment by ManickaP** [comment] 2023-07-18 17:04
It's a one-liner in here https://source.dot.net/#System.Net.Quic/System/Net/Quic/QuicListener.cs,376
And the same thing applies to QuicConnection and AcceptStream: https://source.dot.net/#System.Net.Quic/System/Net/Quic/QuicConnection.cs,645
==> 2 liner change

**Comment by wfurt** [comment] 2023-07-19 01:43
do you want to do it and write test @ManickaP? I will not get to it this week.

**Comment by ManickaP** [comment] 2023-07-20 07:52
Yep, that's why I assigned myself. I already have something in progress.

**Closed** 2023-09-20 10:28 UTC
Labels: bug, area-System.Net.Quic
