### ISSUE TITLE
CI failure: `Installer-coreclr-Linux_x64-Release` `Microsoft.NET.HostModel.ComHost.Tests`- Constructor parameters did not have matching fixture data: SharedTestState fixture

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#75491] opened 2022-09-12 22:42 UTC
```json
{
  "ErrorMessage": "The following constructor parameters did not have matching fixture data: SharedTestState fixture",
  "BuildRetry": false
}
```

- Seen in this release/7.0 backport PR: https://github.com/dotnet/runtime/pull/75461
- Job tests: https://dev.azure.com/dnceng-public/public/_build/results?buildId=13115&view=ms.vss-test-web.build-test-results-tab
- Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=13115
- Callstack:

Error message
```
System.AggregateException : One or more errors occurred. (Command failed with exit code 1: /root/runtime/.dotnet/dotnet build /bl:BuildProject.binlog --no-restore --framework net7.0 /p:TestTargetRid=linux-x64 /p:MNAVersion=7.0.0-ci -o /root/runtime/artifacts/tests/Release/hmc/cmve425d.wqo/ComLibrary/bin) (The following constructor parameters did not have matching fixture data: SharedTestState fixture)
---- Microsoft.DotNet.Cli.Build.Framework.BuildFailureException : Command failed with exit code 1: /root/runtime/.dotnet/dotnet build /bl:BuildProject.binlog --no-restore --framework net7.0 /p:TestTargetRid=linux-x64 /p:MNAVersion=7.0.0-ci -o /root/runtime/artifacts/tests/Release/hmc/cmve425d.wqo/ComLibrary/bin
---- The following constructor parameters did not have matching fixture data: SharedTestState fixture
```
Stack trace
```
----- Inner Stack Trace #1 (Microsoft.DotNet.Cli.Build.Framework.BuildFailureException) -----
   at Microsoft.DotNet.Cli.Build.Framework.CommandResult.EnsureSuccessful(Boolean suppressOutput) in /_/src/installer/tests/TestUtils/CommandResult.cs:line 46
   at Microsoft.DotNet.CoreSetup.Test.TestProjectFixture.BuildProject(DotNetCli dotnet, String runtime, String framework, String outputDirectory, Boolean restore) in /_/src/installer/tests/TestUtils/TestProjectFixture.cs:line 177
   at Microsoft.NET.HostModel.ComHost.Tests.ClsidMapTests.SharedTestState..ctor() in /_/src/installer/tests/Microsoft.NET.HostModel.Tests/Microsoft.NET.HostModel.ComHost.Tests/ClsidMapTests.cs:line 156
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```

- Affected tests:

  - Microsoft.NET.HostModel.ComHost.Tests.ClsidMapTests.NonPublicTypeNotAdded
  - Microsoft.NET.HostModel.ComHost.Tests.ClsidMapTests.PublicComVisibleTypeWithGuidAdded
  - Microsoft.NET.HostModel.ComHost.Tests.ClsidMapTests.ExplicitProgIdUsed
  - Microsoft.NET.HostModel.ComHost.Tests.ClsidMapTests.PublicNestedTypeOfNonPublicTypeNotAdded
  - Microsoft.NET.HostModel.ComHost.Tests.ClsidMapTests.PublicNestedTypeOfPublicTypeAdded
  - Microsoft.NET.HostModel.ComHost.Tests.ClsidMapTests.DefaultProgIdIsTypeName
  - Microsoft.NET.HostModel.ComHost.Tests.ClsidMapTests.ExplicitlyEmptyProgIdNotInClsidMap
  - Microsoft.NET.HostModel.ComHost.Tests.ClsidMapTests.PublicComVisibleTypeWithDuplicateGuidThrows
  - Microsoft.NET.HostModel.ComHost.Tests.ClsidMapTests.PublicComVisibleTypeWithoutGuidThrows
  - Microsoft.NET.HostModel.Tests.AppHostUsedWithSymbolicLinks.Put_satellite_assembly_behind_symlink
  - Microsoft.NET.HostModel.Tests.AppHostUsedWithSymbolicLinks.Run_apphost_behind_transitive_symlinks
  - Microsoft.NET.HostModel.Tests.AppHostUsedWithSymbolicLinks.Put_app_directory_behind_symlink
  - Microsoft.NET.HostModel.Tests.AppHostUsedWithSymbolicLinks.Put_app_directory_behind_symlink_and_use_dotnet
  - Microsoft.NET.HostModel.Tests.AppHostUsedWithSymbolicLinks.Put_dotnet_behind_symlink
  - Microsoft.NET.HostModel.Tests.AppHostUsedWithSymbolicLinks.Run_apphost_behind_symlink

**Comment by jkoritzinsky** [comment] 2022-09-12 22:46
We don't upload the binlog from these builds inside the installer tests, so this is extremely difficult to diagnose the underlying intermittent issue as the info above is all we have to go on.

**Comment by joeloff** [comment] 2022-09-12 22:53
None of that seem related to the workload changes itself, but I suppose it could be caused by the Arcade update. There were a lot of changes that got pulled in that I'm not 100% sure about. The changes under `eng` all came from updating Arcade, other than getting the new task DLL, none of the Arcade changes are related to the workload change either.

**Comment by jkotas** [comment] 2022-09-12 22:59
Duplicate of https://github.com/dotnet/runtime/issues/75429 and https://github.com/dotnet/runtime/issues/74328

**Closed by jkotas** 2022-09-12 22:59 UTC
Labels: area-Infrastructure-installer, untriaged
