### ISSUE TITLE
ThrowIfNull and ThrowIfNullOrEmpty could return a value

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#79691] opened 2022-12-15 04:42 UTC
The code:
```c#
    public sealed class TypeForwardedFromAttribute : Attribute
    {
        public TypeForwardedFromAttribute(string assemblyFullName)
        {
            ArgumentException.ThrowIfNullOrEmpty(assemblyFullName);
            AssemblyFullName = assemblyFullName;
        }
 
        public string AssemblyFullName { get; }
    }
```
could be:
```c#
    public sealed class TypeForwardedFromAttribute : Attribute
    {
        public TypeForwardedFromAttribute(string assemblyFullName)
        {
            AssemblyFullName = ArgumentException.ThrowIfNullOrEmpty(assemblyFullName);
        }
 
        public string AssemblyFullName { get; }
    }
```

Or for arguments (especially if there are a lot of them):
```c#
Directory.Update(path ?? throw new ArgumentNullException(nameof(path));
```
converted to:
```c#
Directory.Update(ArgumentException.ThrowIfNull(assemblyFullName));
```

**Comment by jkotas** [comment] 2022-12-15 05:38
Duplicate of https://github.com/dotnet/runtime/issues/70515

**Closed by jkotas** 2022-12-15 05:38 UTC
