### ISSUE TITLE
[Perf -152%] System.IO.Tests.Perf_Path.GetRandomFileName

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#39122] opened 2020-07-10 22:06 UTC
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Changes | [diff](https://github.com/dotnet/installer/compare/a4a49f07fbf986d496ef57521e76b22caaf9bfb3...3c6656f83b01ece6af7e11eb75ec0145554b139d)

### Regressions in System.IO.Tests.Perf_Path

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier
-- | -- | -- | -- | -- | --
GetRandomFileName | 695.30 ns | 1.76 μs | 2.54 |  | False

### Related Issue on x86 Windows
[[Perf -15%] System.IO.Tests.Perf_Path.GetPathRoot](https://github.com/DrewScoggins/performance-2/issues/917)

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_10_2020/release/3.1.1xx%20-%3E%20master_x64_ubuntu%2018.04/System.IO.Tests.Perf_Path_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_10_2020/release/3.1.1xx%20-%3E%20master_x64_ubuntu%2018.04/System.IO.Tests.Perf_Path.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.IO.Tests.Perf_Path*';
```
<details>

#### System.IO.Tests.Perf_Path.GetRandomFileName

```log
[ 607.180 ;  641.303) | @@@
[ 641.303 ;  706.017) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 706.017 ;  763.521) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 763.521 ;  828.235) | 
[ 828.235 ;  892.949) | 
[ 892.949 ;  957.663) | 
[ 957.663 ; 1022.377) | 
[1022.377 ; 1087.091) | 
[1087.091 ; 1151.805) | 
[1151.805 ; 1216.519) | 
[1216.519 ; 1281.233) | 
[1281.233 ; 1345.947) | 
[1345.947 ; 1410.660) | 
[1410.660 ; 1475.374) | 
[1475.374 ; 1540.088) | 
[1540.088 ; 1604.802) | 
[1604.802 ; 1669.516) | 
[1669.516 ; 1741.583) | 
[1741.583 ; 1828.164) | @@
[1828.164 ; 1893.916) | @@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by danmosemsft** [comment] 2020-07-10 23:23
@DrewScoggins  the diff link does not work. Can you please share the diff bracketing this jump?

**Comment by DrewScoggins** [comment] 2020-07-10 23:47
Yeah, there seems to be a bug here if the points you are trying to diff go across the switch to the runtime repo. You can use the report to generate a tight diff, again as long as the comparison you are trying to do is after the switch to the runtime repo. To do this 

1. Click on this link [Historical Data in Reporting System](https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_10_2020/release/3.1.1xx%20-%3E%20master_x64_ubuntu%2018.04/System.Tests.Perf_UInt32.html)
2. Find the point before the regression and click on that point
![image](https://user-images.githubusercontent.com/9439069/87210963-601f4380-c2cc-11ea-9c29-a35440d0f58f.png)
3. Click the Set Baseline button then close the flyout by clicking on the red X.
4. Find the point after the regression and click on that point
![image](https://user-images.githubusercontent.com/9439069/87211057-a1afee80-c2cc-11ea-95b0-e0c4148f63f1.png)
5. Click Set Compare and then you will see links that should lead to a comparison of the changes in the runtime repo.
![image](https://user-images.githubusercontent.com/9439069/87211103-c4da9e00-c2cc-11ea-9d5a-fce6b552c11e.png)

By following these steps I generated this link https://github.com/dotnet/runtime/compare/4a4e347b964a2c8d2216ec382e4fb481965bb2fc...d0889f1159b6ea044b5e491921b7a37a688ce465, which should be able to give you the bounds that you want. Sorry again for the bug in the diff link, I will fix that to link to the installer repo which is what we are actually generating the hashes for, but hopefully this helps you track down diffs going forward 😄

**Comment by danmosemsft** [comment] 2020-07-11 04:44
Thanks for the info.

> will fix that to link to the installer repo which is what we are actually generating the hashes for,

I don't think that's the diff we want for the microbenchmarks. The issues sounds have diff across runtime repo commits surely?

**Comment by stephentoub** [comment] 2020-07-11 19:27
I can't repro this locally (on Ubuntu 18.04).  I've run the benchmark multiple times, and each time I get results like this:

```
dotnet run -c Release -f netcoreapp3.1 --runtimes netcoreapp3.1 netcoreapp5.0 --join --filter *System.IO.Tests.Perf_Path.GetRandomFileName*
```

|            Method |        Job |       Runtime |     Toolchain |     Mean |   Error |  StdDev |   Median |      Min |      Max | Ratio |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------ |----------- |-------------- |-------------- |---------:|--------:|--------:|---------:|---------:|---------:|------:|-------:|------:|------:|----------:|
| GetRandomFileName | Job-CSKPPR | .NET Core 3.1 | netcoreapp3.1 | 756.1 ns | 3.65 ns | 3.41 ns | 757.6 ns | 747.9 ns | 758.6 ns |  1.00 | 0.0061 |     - |     - |      48 B |
| GetRandomFileName | Job-APGSLT | .NET Core 5.0 | netcoreapp5.0 | 744.8 ns | 1.59 ns | 1.41 ns | 745.0 ns | 741.3 ns | 747.1 ns |  0.99 | 0.0060 |     - |     - |      48 B |

**Comment by jkotas** [comment] 2020-07-12 03:34
Duplicate of https://github.com/dotnet/runtime/issues/39114 . Both NewGuid and GetRandomFileName use the same underlying OS random number generator.

**Closed by jkotas** 2020-07-12 03:34 UTC
Labels: arch-x64, area-System.IO, os-linux, tenet-performance, tenet-performance-benchmarks, untriaged
