### ISSUE TITLE
Application that targets .NET 4.8 does not support System.Data.SqlClient that targets .NET Standard 2.0

### ISSUE THREAD

**Issue by tdGreat** [dotnet/runtime#107523] opened 2024-09-09 04:48 UTC
I have a dll (say TestLib.dll) that targets .NET Standard 2.0, which uses System.Data.SqlClient dll (this also targets .NET Standard 2.0).

Now I'm using the TestLib.dll in an application (say TestApp) that targets .NET 4.8. Running the application results in an exception

System.Data.SqlClient is not supported on this platform

It is because TestApp was loading the System.Data.SqlClient.dll that targets .NET Standard.

If I give the reference to the the System.Data.SqlClient.dll that targets .NET 4.6.1, it works.

To reproduce the issue:

1. Create a class library that targets .NET Standard 2.0 (TestLibrary)
2. In the TestLibrary, reference and use SqlClient (which targets .NET Standard 2.0) latest version (4.8.6) and create a function to query something from the database
3. Build/publish the TestLibrary
4. Create a console application (TestApp) with .NET 4.8 as target framework and use that class library
5. Invoke the function that is querying the database
Note: make sure TestApp is referencing SqlClient that targets .NET Standard 2.0.
When it tries to create a connection object, the exception occurs.

What is the reason for .NET 4.8 not supporting the SqlClient dll that targets .NET Standard 2.0?

**Comment by huoyaoyuan** [comment] 2024-09-09 05:29
> It is because TestApp was loading the System.Data.SqlClient.dll that targets .NET Standard.
> 
> If I give the reference to the the System.Data.SqlClient.dll that targets .NET 4.6.1, it works.

How are you referencing System.Data.SqlClient?

With NuGet mechanism, the dll used at runtime is decided by the framework of entry application, not the framework of transitive projects.

**Comment by huoyaoyuan** [comment] 2024-09-09 06:32
> Hi @huoyaoyuan, im giving the hintpath for the System.Data.SqlClinet.

It's incorrect to install a NuGet package in that way.
With new `PackageReference` format, NuGet will pick the correct dll on the fly for the application.
With the old `packages.config` format, you need to install the package on the entry application.

> Isn't System.Data.SqlClient that targets netstandard2.0 is supposed to work for .net framework4.8?

The dlls under `lib/netstandardX` are dummies without implementation. They shouldn't be used on .NET Framework. The error message indicates that you are using the package incorrectly.

**Comment by tdGreat** [comment] 2024-09-09 11:17
> The dlls under lib/netstandardX are dummies without implementation. 
- Other packages works fine(Netwonsoft.Json, Serilog) but only the SqlClient does not work.

**Comment by huoyaoyuan** [comment] 2024-09-09 12:06
> * Other packages works fine(Netwonsoft.Json, Serilog) but only the SqlClient does not work.

Because they are simple and doesn't need to polyfill differences between frameworks.

Extracting NuGet package in incorrect way is not supported. You need to depend on NuGet, or manipulate things in the exact same way.

**Comment by huoyaoyuan** [comment] 2024-09-09 12:14
Note that packages contains contents that are in-box on some platforms is very likely to break for such usage. Many `System.*` packages are in this category.

**Comment by huoyaoyuan** [comment] 2024-09-25 04:35
See also https://github.com/dotnet/SqlClient/issues/2475 .
`<PackageReference>` is the correct way to use NuGet package. Closing as by design.

**Closed by huoyaoyuan** 2024-09-25 04:35 UTC
Labels: area-System.Data.SqlClient, untriaged
