### ISSUE TITLE
SmtpClientTest.SendMail_SendQUITOnDispose timeout on OSX

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#41687] opened 2020-09-01 17:31 UTC
### Test case
`System.Net.Mail.Tests.SmtpClientTest.SendMail_SendQUITOnDispose(asyncSend: True)`
`System.Net.Mail.Tests.SmtpClientTest.SendMail_SendQUITOnDispose(asyncSend: False)`

### Failed on
`net5.0-OSX-Debug-x64-CoreCLR_release-OSX.1014.Amd64.Open`
https://dev.azure.com/dnceng/public/_build/results?buildId=796625&view=ms.vss-test-web.build-test-results-tab&runId=25205974&paneView=debug&resultId=167484

### With
`System.TimeoutException : Task timed out after 00:00:30`

### Stack trace

```
at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 41
   at System.Net.Mail.Tests.SmtpClientTest.SendMail_SendQUITOnDispose(Boolean asyncSend) in /_/src/libraries/System.Net.Mail/tests/Functional/SmtpClientTest.cs:line 512
```

**Comment by wfurt** [comment] 2020-09-01 19:32
I hit that as well. I'm wondering if this is related to  #41508. We did not see that before AFAIK. 

cc: @tmds

**Comment by wfurt** [comment] 2020-09-01 20:07
4 failures in last 4 days and nothing before in 90 days. This looks like regression @karelz

**Comment by tmds** [comment] 2020-09-02 02:59
This is the test that fails, for `asyncSend=true`.

```cs
        [Theory]
        [InlineData(false)]
        [InlineData(true)]
        public async Task SendMail_SendQUITOnDispose(bool asyncSend)
        {
            bool quitMessageReceived = false;
            using ManualResetEventSlim quitReceived = new ManualResetEventSlim();
            using var server = new LoopbackSmtpServer();
            server.OnQuitReceived += _ =>
            {
                quitMessageReceived = true;
                quitReceived.Set();
            };

            using (SmtpClient client = server.CreateClient())
            {
                client.Credentials = new NetworkCredential("Foo", "Bar");
                MailMessage msg = new MailMessage("foo@example.com", "bar@example.com", "hello", "howdydoo");
                if (asyncSend)
                {
                    await client.SendMailAsync(msg).TimeoutAfter((int)TimeSpan.FromSeconds(30).TotalMilliseconds);
                }
                else
                {
                    client.Send(msg);
                }
                Assert.False(quitMessageReceived, "QUIT received");
            }

            // There is a latency between send/receive.
            quitReceived.Wait(TimeSpan.FromSeconds(30));
            Assert.True(quitMessageReceived, "QUIT message not received");
        }
```
From the exception, it seems it is throwing on `TimeoutAfter`.

> 4 failures in last 4 days and nothing before in 90 days. This looks like regression @karelz

https://github.com/dotnet/runtime/pull/41508 matches the timing. https://github.com/dotnet/runtime/pull/41508 should only be changing behaviour when the `Socket` gets cleaned up by the finalizer. I don't think that happens in this test.

This was reported against macOS, has it occurred on Linux? I will try to reproduce it on Linux.

Maybe we need to increase the timeout used?

**Comment by wfurt** [comment] 2020-09-02 03:22
All cases I saw were on OSX 10.14. I don't see direct correlation either but it is suspicious that the test verifies dispose behavior. I'm wondering if all this is timing....? But I don't know why it would be much? slower.

**Comment by antonfirsov** [comment] 2020-09-02 11:54
What I see in Kusto, querying for `Method == "SendMail_SendQUITOnDispose"`:
- There are 5 failures since **2020-08-28**, 2 with `asyncSend: true` and 3 with `asyncSend: false`. The test did not fail before.
- The sync variant fails in `client.Send(msg)`, the async variant fails in `quitReceived.Wait(TimeSpan.FromSeconds(30))`
- The following 2 failures happened before merging #41508 (which happened around 2020-09-01 12:00 UTC):
![image](https://user-images.githubusercontent.com/6835152/91978017-bedcc880-ed23-11ea-8b98-1a397dc2a8cf.png)

**Comment by karelz** [comment] 2020-09-03 16:28
Triage: Check if it was 1 machine? Or if there are more random test failures on the OSX 10.14.

**Comment by wfurt** [comment] 2020-09-03 22:08
I did 1000+ runs locally and I did not see any failure.

**Comment by CarnaViire** [comment] 2020-09-04 14:56
I also wasn't able to repro it locally.
And we didn't have any additional failures for this test since 2020-09-01 18:56.

Also, querying for long timeouted tests in last month shows me that this number is pretty high for `osx.1014.amd64.open` (it took the first place)

QueueName  | Count
------------ | -------------
osx.1014.amd64.open | 1819
windows.10.amd64.open | 634
ubuntu.1604.amd64.open | 480
... | ...


[link to Kusto](https://dataexplorer.azure.com/clusters/engsrvprod/databases/engineeringdata?query=H4sIAAAAAAAAA22OwUoDQRBE735F3TYBA0P04GVzMQRWSEARPE92GtNJpkemexDFj7fNgl48FV316KpnUnsibWdTXH3hWFhwYkk9i1DFS6mnwSgrivweQ/oPfSj7C+U6JM/fD1QJGxbWAyWseqRoZJxptgzLsAh3i3A7R5SELanGV8JYxCKLovvBSrPuEk/70PfoNpHPk7luNRp73wo3weu05RwrfxLuSxOn/ZvrbI79Bx4bNdrFTA6WmnytmxOXSEd332o50mh/5PWUfwMlexaFIAEAAA==)

Query that I ran
<details>

```
TestResults 
| join kind=inner WorkItems on WorkItemId 
| join kind=inner Jobs on JobId
| where Finished >= datetime(2020-08-04) and Message contains 'timeout' and Result == 'Fail' and Duration > 30
| summarize Count = count() by QueueName
| order by Count desc
| project QueueName, Count
```

</details>

It makes me think that it might be CI overload for Mac machines...

**Comment by CarnaViire** [comment] 2020-09-07 16:46
As of today, there are still no additional failures for this test. I'm closing it for now, and will reopen if the failures re-appear.

**Closed by CarnaViire** 2020-09-07 16:46 UTC
Labels: area-System.Net
