### ISSUE TITLE
[API Proposal]: CollectionsMarshal.GetValueRef with ReadOnlySpan<char> key

### ISSUE THREAD

**Issue by pCYSl5EDgo** [dotnet/runtime#63827] opened 2022-01-15 05:10 UTC
### Background and motivation

Currently `System.ReadOnlySpan<char>` is used more and more.
`System.Collections.Generic.Dictionary<string, TValue>` requires `string` key.
`ReadOnlySpan<char>` to `string` conversion causes allocation.

### API Proposal

```C#
using System.Collections.Generic;

namespace System.Runtime.InteropServices
{
    public static class CollectionsMarshal
    {
        public static ref TValue GetValueRefOrNullRef<TValue>(Dictionary<string, TValue> dictionary, ReadOnlySpan<char> key);
        public static ref TValue? GetValueRefOrAddDefault<TValue>(Dictionary<string, TValue> dictionary, ReadOnlySpan<char> key, out bool exists)
    }
}
```

The method signatures should be kept similar to the original ones.

### API Usage

```C#
Dictionary<string, MyType> dictionary; // initialized

System.Text.SpanLineEnumerator enumerator = System.IO.File.ReadAllText(somePath).AsSpan().EnumerateLines();
while (enumerator.MoveNext())
{
    ReadOnlySpan<char> key = enumerator.Current;
    ref MyType value = CollectionsMarshal.GetValueRefOrAddDefault(dictionary, key, out bool exists);
    if (exists)
    {
            ProcessSomething(ref value);
    }
}


```

**Comment by Sergio0694** [comment] 2022-01-15 10:09
We were just about discussing this yesterday 😄
I personally love the idea, but if I remember correctly one of the main concerns with this API, when it was proposed in the past, was: what should the behavior be if the dictionary has a custom comparer for the keys?

**Comment by Joe4evr** [comment] 2022-01-15 10:16
See prior discussion in #27229.

**Comment by pCYSl5EDgo** [comment] 2022-01-15 11:47
Oh... I've missed it...

**Comment by pCYSl5EDgo** [comment] 2022-01-15 12:03
> We were just about discussing this yesterday 😄 I personally love the idea, but if I remember correctly one of the main concerns with this API, when it was proposed in the past, was: what should the behavior be if the dictionary has a custom comparer for the keys?

The `Dictionary<string, TValue>` has already been specially treated
I propose that new interface.

```C#
public or internal interface IStringSpanEqualityComparer : IEqualityComparer<string>
{
    int GetHashCode(ReadOnlySpan<char> value);
    bool Equals(ReadOnlySpan<char> arg0, ReadOnlySpan<char> arg1);
}
```

`StringComparer` will implement the above.
The custom comparer must implement it or throws a runtime exception.

**Comment by stephentoub** [comment] 2022-01-15 12:28
Closing as a duplicate of #27229. Please continue any discussion there. Thanks.

**Closed by stephentoub** 2022-01-15 12:28 UTC
Labels: api-suggestion, area-System.Collections, untriaged
