### ISSUE TITLE
WriteEntry_LongFileSize tests failing in CI

### ISSUE THREAD

**Issue by wfurt** [dotnet/runtime#79773] opened 2022-12-16 20:53 UTC
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-79652-merge-27087af8ec1f4aff89/System.Formats.Tar.Tests/1/console.cd22a1da.log?helixlogtype=result
```
Console log: 'System.Formats.Tar.Tests' from job 27087af8-ec1f-4aff-892a-6fd1e194d10f workitem e517f5c3-9055-4180-9ce9-66e030f775ce (windows.10.amd64.server2022.es.open.rt) executed on machine a000XZB running Windows-10-10.0.20348-SP0

C:\h\w\B47409DF\w\A21E08F7\e>taskkill.exe /f /im corerun.exe 
ERROR: no se encontr� el proceso "corerun.exe".

C:\h\w\B47409DF\w\A21E08F7\e>call RunTests.cmd --runtime-path C:\h\w\B47409DF\p 
----- start 14/12/2022 18:33:03,84 ===============  To repro directly: ===================================================== 
pushd C:\h\w\B47409DF\w\A21E08F7\e\
"C:\h\w\B47409DF\p\dotnet.exe" exec --runtimeconfig System.Formats.Tar.Tests.runtimeconfig.json --depsfile System.Formats.Tar.Tests.deps.json xunit.console.dll System.Formats.Tar.Tests.dll -xml testResults.xml -nologo -nocolor -trait category=OuterLoop -notrait category=IgnoreForCI -notrait category=failing 
popd
===========================================================================================================

C:\h\w\B47409DF\w\A21E08F7\e>"C:\h\w\B47409DF\p\dotnet.exe" exec --runtimeconfig System.Formats.Tar.Tests.runtimeconfig.json --depsfile System.Formats.Tar.Tests.deps.json xunit.console.dll System.Formats.Tar.Tests.dll -xml testResults.xml -nologo -nocolor -trait category=OuterLoop -notrait category=IgnoreForCI -notrait category=failing  
  Discovering: System.Formats.Tar.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Formats.Tar.Tests (found 2 of 625 test cases)
  Starting:    System.Formats.Tar.Tests (parallel test collections = on, max threads = 2)
   System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntry_LongFile_Tests.WriteEntry_LongFileSize', Elapsed: 00:04:00
   System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntry_LongFile_Tests.WriteEntry_LongFileSize', Elapsed: 00:06:00
   System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntry_LongFile_Tests.WriteEntry_LongFileSize', Elapsed: 00:08:00
   System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntry_LongFile_Tests.WriteEntry_LongFileSize', Elapsed: 00:10:00
   System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntry_LongFile_Tests.WriteEntry_LongFileSize', Elapsed: 00:12:00
   System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntry_LongFile_Tests.WriteEntry_LongFileSize', Elapsed: 00:14:00
['System.Formats.Tar.Tests' END OF WORK ITEM LOG: Command timed out, and was killed]
```

This is somewhat related to #77012. I run the test locally on my MacBook:
```
  ===========================================================================================================
  ~/github/wfurt-runtime/artifacts/bin/System.Formats.Tar.Tests/Debug/net7.0-unix ~/github/wfurt-runtime/src/libraries/System.Formats.Tar/tests
    Discovering: System.Formats.Tar.Tests (method display = ClassAndMethod, method display options = None)
    Discovered:  System.Formats.Tar.Tests (found 635 test cases)
    Starting:    System.Formats.Tar.Tests (parallel test collections = on, max threads = 16)
      System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.Add_BlockDevice [SKIP]
        Condition(s) not met: "IsRemoteExecutorSupportedAndPrivilegedProcess"
      System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.Add_CharacterDevice [SKIP]
        Condition(s) not met: "IsRemoteExecutorSupportedAndPrivilegedProcess"
      System.Formats.Tar.Tests.TarWriter_WriteEntry_File_Tests.Add_Fifo [SKIP]
        Condition(s) not met: "IsRemoteExecutorSupportedAndPrivilegedProcess"
      System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_File_Tests.Add_BlockDevice_Async [SKIP]
        Condition(s) not met: "IsRemoteExecutorSupportedAndPrivilegedProcess"
      System.Formats.Tar.Tests.TarEntry_ExtractToFile_Tests_Unix.Extract_SpecialFiles_Async [SKIP]
        Condition(s) not met: "IsRemoteExecutorSupportedAndPrivilegedProcess"
      System.Formats.Tar.Tests.TarEntry_ExtractToFile_Tests_Unix.Extract_SpecialFiles [SKIP]
        Condition(s) not met: "IsRemoteExecutorSupportedAndPrivilegedProcess"
      System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_File_Tests.Add_Fifo_Async [SKIP]
        Condition(s) not met: "IsRemoteExecutorSupportedAndPrivilegedProcess"
      System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_File_Tests.Add_CharacterDevice_Async [SKIP]
        Condition(s) not met: "IsRemoteExecutorSupportedAndPrivilegedProcess"
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntry_LongFile_Tests.WriteEntry_LongFileSize', Elapsed: 00:02:01
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntry_LongFile_Tests.WriteEntry_LongFileSize', Elapsed: 00:04:01
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntry_LongFile_Tests.WriteEntry_LongFileSize', Elapsed: 00:06:01
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntry_LongFile_Tests.WriteEntry_LongFileSize', Elapsed: 00:08:01
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_LongFile_Tests.WriteEntry_LongFileSizeAsync', Elapsed: 00:02:01
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_LongFile_Tests.WriteEntry_LongFileSizeAsync', Elapsed: 00:04:01
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_LongFile_Tests.WriteEntry_LongFileSizeAsync', Elapsed: 00:06:01
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_LongFile_Tests.WriteEntry_LongFileSizeAsync', Elapsed: 00:08:01
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_LongFile_Tests.WriteEntry_LongFileSizeAsync', Elapsed: 00:10:01
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_LongFile_Tests.WriteEntry_LongFileSizeAsync', Elapsed: 00:12:01
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_LongFile_Tests.WriteEntry_LongFileSizeAsync', Elapsed: 00:14:01
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_LongFile_Tests.WriteEntry_LongFileSizeAsync', Elapsed: 00:16:01
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_LongFile_Tests.WriteEntry_LongFileSizeAsync', Elapsed: 00:18:01
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_LongFile_Tests.WriteEntry_LongFileSizeAsync', Elapsed: 00:20:01
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_LongFile_Tests.WriteEntry_LongFileSizeAsync', Elapsed: 00:22:01
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_LongFile_Tests.WriteEntry_LongFileSizeAsync', Elapsed: 00:24:01
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_LongFile_Tests.WriteEntry_LongFileSizeAsync', Elapsed: 00:26:01
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_LongFile_Tests.WriteEntry_LongFileSizeAsync', Elapsed: 00:28:02
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_LongFile_Tests.WriteEntry_LongFileSizeAsync', Elapsed: 00:30:02
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_LongFile_Tests.WriteEntry_LongFileSizeAsync', Elapsed: 00:32:02
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_LongFile_Tests.WriteEntry_LongFileSizeAsync', Elapsed: 00:34:02
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_LongFile_Tests.WriteEntry_LongFileSizeAsync', Elapsed: 00:36:02
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_LongFile_Tests.WriteEntry_LongFileSizeAsync', Elapsed: 00:38:02
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_LongFile_Tests.WriteEntry_LongFileSizeAsync', Elapsed: 00:40:02
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_LongFile_Tests.WriteEntry_LongFileSizeAsync', Elapsed: 00:42:02
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_LongFile_Tests.WriteEntry_LongFileSizeAsync', Elapsed: 00:44:02
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_LongFile_Tests.WriteEntry_LongFileSizeAsync', Elapsed: 00:46:02
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_LongFile_Tests.WriteEntry_LongFileSizeAsync', Elapsed: 00:48:02
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_LongFile_Tests.WriteEntry_LongFileSizeAsync', Elapsed: 00:50:02
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_LongFile_Tests.WriteEntry_LongFileSizeAsync', Elapsed: 00:52:02
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_LongFile_Tests.WriteEntry_LongFileSizeAsync', Elapsed: 00:54:02
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_LongFile_Tests.WriteEntry_LongFileSizeAsync', Elapsed: 00:56:02
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_LongFile_Tests.WriteEntry_LongFileSizeAsync', Elapsed: 00:58:02
     System.Formats.Tar.Tests: [Long Running Test] 'System.Formats.Tar.Tests.TarWriter_WriteEntryAsync_LongFile_Tests.WriteEntry_LongFileSizeAsync', Elapsed: 01:00:02
    Finished:    System.Formats.Tar.Tests
  === TEST EXECUTION SUMMARY ===
     System.Formats.Tar.Tests  Total: 5286, Errors: 0, Failed: 0, Skipped: 8, Time: 4229.782s
```

it seems like it takes more than hour for test to finish ... and that is pretty crazy IMHO. 
We should either disable this or at least consider `IgnoreForCI `.

**Comment by adamsitnik** [comment] 2022-12-19 10:55
@Jozkee PTAL

**Comment by Jozkee** [comment] 2022-12-21 00:38
I do agree that the test takes too long, it is already marked as `OuterLoop`. Is the next step for tests prone to hang to just annotate them with `IgnoreForCI`?

**Comment by akoeplinger** [comment] 2022-12-21 10:23
@Jozkee I think a test which takes more than an hour to finish is too long even for OuterLoop.

It should be ran manually only, we have that pattern for other cases already, e.g.
- https://github.com/dotnet/runtime/blob/main/src/libraries/System.IO.FileSystem/tests/ManualTests/ManualTests.cs
- https://github.com/dotnet/runtime/blob/main/src/libraries/System.Console/tests/ManualTests/ManualTests.cs

**Comment by akoeplinger** [comment] 2022-12-21 10:45
Hmm though judging from your comment in https://github.com/dotnet/runtime/issues/77012#issuecomment-1360573179 the test took just ~8 minutes on your machine apparently, weird.

**Comment by wfurt** [comment] 2022-12-21 17:47
That may depend on the filesystem. Some systems may have `/tmp` as ramfs. My MacBook is corporate machine and I suspect that AV or some other security functions may be involved. For one, disco encryption is forced by policy.

**Comment by akoeplinger** [comment] 2022-12-22 10:31
On CI we're also seeing it fail on Linux and I don't think there's any AV/security thing there though.

**Comment by akoeplinger** [comment] 2022-12-22 10:59
I tried running the test locally (after https://github.com/dotnet/runtime/pull/79899) on my Mac using Mono and Release config and it took just about 8 minutes too.

**Comment by akoeplinger** [comment] 2022-12-22 11:16
I'm also seeing the test not cleaning up the test file right away so it takes more space then necessary even after https://github.com/dotnet/runtime/pull/79899, sent a PR: https://github.com/dotnet/runtime/pull/79907

**Comment by carlossanlop** [comment] 2023-02-01 22:44
The issue isn't reproing anymore. I'm not seeing the failure again in Kusto. I'll close this.

**Closed by carlossanlop** 2023-02-01 22:44 UTC
Labels: test-run-core, untriaged, blocking-clean-ci-optional, area-System.Formats.Tar
