### ISSUE TITLE
ARM64 - Test failure `Interop/COM/ComWrappers/API/ComWrappersTests/ComWrappersTests.sh`

### ISSUE THREAD

**Issue by TIHan** [dotnet/runtime#85721] opened 2023-05-03 17:08 UTC
[Link](https://dev.azure.com/dnceng-public/public/_build/results?buildId=258903&view=ms.vss-test-web.build-test-results-tab&runId=5058936&resultId=106835&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab)

**linux arm64 Checked**
**runtime-coreclr jitstress-random**

```
Console log: 'Interop' from job bf182522-2a19-4e68-861a-d4b97930f385 (ubuntu.1804.armarch.open) using docker image mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8 on a004IN3
running $HELIX_CORRELATION_PAYLOAD/scripts/2ef74017bdec4115ac004e712908e48a/execute.sh in /datadisks/disk1/work/A2DA08C1/w/B4E90A6B/e max 7200 seconds

Output:
[BEGIN EXECUTION]
+ sudo python -m pip install --disable-pip-version-check -r /root/helix/scripts/runtime_python_requirements.txt
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
WARNING: The directory '/home/helixbot2/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: certifi>=2021.10.8 in /usr/local/lib/python3.6/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 1)) (2022.12.7)
Requirement already satisfied: ndg-httpsclient==0.5.1 in /usr/local/lib/python3.6/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 2)) (0.5.1)
Requirement already satisfied: psutil==5.9.3 in /usr/local/lib/python3.6/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 3)) (5.9.3)
Requirement already satisfied: pyasn1==0.4.5 in /usr/local/lib/python3.6/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 4)) (0.4.5)
Requirement already satisfied: pyopenssl==19.0.0 in /usr/local/lib/python3.6/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 5)) (19.0.0)
Requirement already satisfied: six>=1.11.0 in /usr/lib/python3/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 6)) (1.11.0)
Requirement already satisfied: cryptography<=3.4.6,>=2.8 in /usr/local/lib/python3.6/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 8)) (3.4.6)
Requirement already satisfied: asn1crypto==0.24.0 in /usr/lib/python3/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 9)) (0.24.0)
Requirement already satisfied: idna==2.8 in /usr/local/lib/python3.6/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 10)) (2.8)
Requirement already satisfied: cffi==1.15.1 in /usr/local/lib/python3.6/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 11)) (1.15.1)
Requirement already satisfied: pycparser==2.19 in /usr/local/lib/python3.6/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 12)) (2.19)
Requirement already satisfied: docker==3.7.2 in /usr/local/lib/python3.6/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 14)) (3.7.2)
Requirement already satisfied: docker-pycreds==0.4.0 in /usr/local/lib/python3.6/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 15)) (0.4.0)
Requirement already satisfied: websocket-client==0.56.0 in /usr/local/lib/python3.6/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 16)) (0.56.0)
Requirement already satisfied: requests<=2.28.1,>=2.21.0 in /usr/local/lib/python3.6/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 18)) (2.27.1)
Requirement already satisfied: urllib3==1.24.3 in /usr/local/lib/python3.6/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 19)) (1.24.3)
Requirement already satisfied: azure-storage-blob==12.5.0 in /usr/local/lib/python3.6/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 21)) (12.5.0)
Requirement already satisfied: azure-core==1.7.0 in /usr/local/lib/python3.6/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 22)) (1.7.0)
Requirement already satisfied: azure-devops==5.0.0b9 in /usr/local/lib/python3.6/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 23)) (5.0.0b9)
Requirement already satisfied: msrest==0.6.10 in /usr/local/lib/python3.6/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 24)) (0.6.10)
Requirement already satisfied: isodate==0.6.0 in /usr/local/lib/python3.6/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 25)) (0.6.0)
Requirement already satisfied: requests-oauthlib==1.2.0 in /usr/local/lib/python3.6/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 26)) (1.2.0)
Requirement already satisfied: oauthlib==3.1.0 in /usr/local/lib/python3.6/dist-packages (from -r /root/helix/scripts/runtime_python_requirements.txt (line 27)) (3.1.0)
Requirement already satisfied: charset-normalizer~=2.0.0; python_version >= "3" in /usr/local/lib/python3.6/dist-packages (from requests<=2.28.1,>=2.21.0->-r /root/helix/scripts/runtime_python_requirements.txt (line 18)) (2.0.12)
+ export PYTHONPATH=/root/helix/scripts:
+ cd /root/helix/work/workitem/e
+ mkdir -p /home/helixbot/dotnetbuild/dumps/
+ /root/helix/work/correlation/scripts/2ef74017bdec4115ac004e712908e48a/execute.sh
+ export CORE_ROOT=/root/helix/work/correlation
+ export __TestEnv=/root/helix/work/workitem/u/SetStressModes_jitstress_random_2.sh
+ export __TestTimeout=1800000
+ export __TestCollectionTimeoutMins=120
+ export __CollectDumps=1
+ export __CrashDumpFolder=/home/helixbot/dotnetbuild/dumps
+ set __TestArchitecture=arm64
+ cat /root/helix/work/workitem/u/SetStressModes_jitstress_random_2.sh
#!/usr/bin/env bash
export DOTNET_TieredCompilation=0
export DOTNET_DbgEnableMiniDump=1
export DOTNET_EnableCrashReport=1
export DOTNET_DbgMiniDumpName=$HELIX_DUMP_FOLDER/coredump.%d.dmp
export DOTNET_JitStress=199
+ export PATH=/root/helix/work/correlation/dotnet-cli:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ export DOTNET_ROOT=/root/helix/work/correlation/dotnet-cli
+ export DOTNET_CLI_TELEMETRY_OPTOUT=1
+ export DOTNET_CLI_HOME=/root/helix/work/workitem/e/.dotnet
+ export NUGET_PACKAGES=/root/helix/work/workitem/e/.nuget
+ dotnet /root/helix/work/correlation/xunit/xunit.console.dll Interop/StringMarshalling/Interop.StringMarshalling.XUnitWrapper.dll Interop/UnmanagedCallersOnly/Interop.UnmanagedCallersOnly.XUnitWrapper.dll Interop/SuppressGCTransition/Interop.SuppressGCTransition.XUnitWrapper.dll Interop/PrimitiveMarshalling/Interop.PrimitiveMarshalling.XUnitWrapper.dll Interop/UnmanagedCallersOnlyBasic/Interop.UnmanagedCallersOnlyBasic.XUnitWrapper.dll Interop/MonoAPI/Interop.MonoAPI.XUnitWrapper.dll Interop/SimpleStruct/Interop.SimpleStruct.XUnitWrapper.dll Interop/ICustomMarshaler/Interop.ICustomMarshaler.XUnitWrapper.dll Interop/FuncPtrAsDelegateParam/Interop.FuncPtrAsDelegateParam.XUnitWrapper.dll Interop/BestFitMapping/Interop.BestFitMapping.XUnitWrapper.dll Interop/ArrayMarshalling/Interop.ArrayMarshalling.XUnitWrapper.dll Interop/MarshalAPI/Interop.MarshalAPI.XUnitWrapper.dll Interop/DllImportAttribute/Interop.DllImportAttribute.XUnitWrapper.dll Interop/LayoutClass/Interop.LayoutClass.XUnitWrapper.dll Interop/COM/Interop.COM.XUnitWrapper.dll Interop/IDynamicInterfaceCastable/Interop.IDynamicInterfaceCastable.XUnitWrapper.dll Interop/NativeLibrary/Interop.NativeLibrary.XUnitWrapper.dll Interop/RefCharArray/Interop.RefCharArray.XUnitWrapper.dll Interop/DisabledRuntimeMarshalling/Interop.DisabledRuntimeMarshalling.XUnitWrapper.dll Interop/StructPacking/Interop.StructPacking.XUnitWrapper.dll Interop/DllImportSearchPaths/Interop.DllImportSearchPaths.XUnitWrapper.dll Interop/ICastable/Interop.ICastable.XUnitWrapper.dll Interop/StructMarshalling/Interop.StructMarshalling.XUnitWrapper.dll Interop/PInvoke/Interop.PInvoke.XUnitWrapper.dll Interop/UnmanagedCallConv/Interop.UnmanagedCallConv.XUnitWrapper.dll -parallel collections -nocolor -noshadow -xml testResults.xml
Microsoft.DotNet.XUnitConsoleRunner v2.5.0 (64-bit .NET 8.0.0-preview.3.23174.8)
  Discovering: Interop.StringMarshalling.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  Interop.StringMarshalling.XUnitWrapper (found 5 test cases)
  Starting:    Interop.StringMarshalling.XUnitWrapper (parallel test collections = on, max threads = 2)
  Finished:    Interop.StringMarshalling.XUnitWrapper
  Discovering: Interop.UnmanagedCallersOnly.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  Interop.UnmanagedCallersOnly.XUnitWrapper (found 1 test case)
  Starting:    Interop.UnmanagedCallersOnly.XUnitWrapper (parallel test collections = on, max threads = 2)
  Finished:    Interop.UnmanagedCallersOnly.XUnitWrapper
  Discovering: Interop.SuppressGCTransition.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  Interop.SuppressGCTransition.XUnitWrapper (found 1 test case)
  Starting:    Interop.SuppressGCTransition.XUnitWrapper (parallel test collections = on, max threads = 2)
  Finished:    Interop.SuppressGCTransition.XUnitWrapper
  Discovering: Interop.PrimitiveMarshalling.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  Interop.PrimitiveMarshalling.XUnitWrapper (found 3 test cases)
  Starting:    Interop.PrimitiveMarshalling.XUnitWrapper (parallel test collections = on, max threads = 2)
  Finished:    Interop.PrimitiveMarshalling.XUnitWrapper
  Discovering: Interop.UnmanagedCallersOnlyBasic.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  Interop.UnmanagedCallersOnlyBasic.XUnitWrapper (found 1 test case)
  Starting:    Interop.UnmanagedCallersOnlyBasic.XUnitWrapper (parallel test collections = on, max threads = 2)
  Finished:    Interop.UnmanagedCallersOnlyBasic.XUnitWrapper
  Discovering: Interop.MonoAPI.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  Interop.MonoAPI.XUnitWrapper (found 0 test cases)
  Discovering: Interop.SimpleStruct.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  Interop.SimpleStruct.XUnitWrapper (found 1 test case)
  Starting:    Interop.SimpleStruct.XUnitWrapper (parallel test collections = on, max threads = 2)
  Finished:    Interop.SimpleStruct.XUnitWrapper
  Discovering: Interop.ICustomMarshaler.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  Interop.ICustomMarshaler.XUnitWrapper (found 3 test cases)
  Starting:    Interop.ICustomMarshaler.XUnitWrapper (parallel test collections = on, max threads = 2)
  Finished:    Interop.ICustomMarshaler.XUnitWrapper
  Discovering: Interop.FuncPtrAsDelegateParam.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  Interop.FuncPtrAsDelegateParam.XUnitWrapper (found 1 test case)
  Starting:    Interop.FuncPtrAsDelegateParam.XUnitWrapper (parallel test collections = on, max threads = 2)
  Finished:    Interop.FuncPtrAsDelegateParam.XUnitWrapper
  Discovering: Interop.BestFitMapping.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  Interop.BestFitMapping.XUnitWrapper (found 1 test case)
  Starting:    Interop.BestFitMapping.XUnitWrapper (parallel test collections = on, max threads = 2)
  Finished:    Interop.BestFitMapping.XUnitWrapper
  Discovering: Interop.ArrayMarshalling.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  Interop.ArrayMarshalling.XUnitWrapper (found 1 test case)
  Starting:    Interop.ArrayMarshalling.XUnitWrapper (parallel test collections = on, max threads = 2)
  Finished:    Interop.ArrayMarshalling.XUnitWrapper
  Discovering: Interop.MarshalAPI.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  Interop.MarshalAPI.XUnitWrapper (found 1 test case)
  Starting:    Interop.MarshalAPI.XUnitWrapper (parallel test collections = on, max threads = 2)
  Finished:    Interop.MarshalAPI.XUnitWrapper
  Discovering: Interop.DllImportAttribute.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  Interop.DllImportAttribute.XUnitWrapper (found 2 test cases)
  Starting:    Interop.DllImportAttribute.XUnitWrapper (parallel test collections = on, max threads = 2)
  Finished:    Interop.DllImportAttribute.XUnitWrapper
  Discovering: Interop.LayoutClass.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  Interop.LayoutClass.XUnitWrapper (found 1 test case)
  Starting:    Interop.LayoutClass.XUnitWrapper (parallel test collections = on, max threads = 2)
  Finished:    Interop.LayoutClass.XUnitWrapper
  Discovering: Interop.COM.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  Interop.COM.XUnitWrapper (found 4 test cases)
  Starting:    Interop.COM.XUnitWrapper (parallel test collections = on, max threads = 2)
    Interop/COM/ComWrappers/API/ComWrappersTestsBuiltInComDisabled/ComWrappersTestsBuiltInComDisabled.sh [FAIL]
      
      Return code:      1
      Raw output file:      /root/helix/work/workitem/uploads/Reports/Interop.COM/ComWrappers/API/ComWrappersTestsBuiltInComDisabled/ComWrappersTestsBuiltInComDisabled.output.txt
      Raw output:
      BEGIN EXECUTION
      /root/helix/work/correlation/corerun -p System.Runtime.InteropServices.BuiltInComInterop.IsSupported=false -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true ComWrappersTestsBuiltInComDisabled.dll ''
      Running ValidateComInterfaceCreation...
      Running ValidateComInterfaceCreationRoundTrip...
      Running ValidateComObjectExtendsManagedLifetime...
      Test Failure: Xunit.Sdk.EqualException: Assert.Equal() Failure
      Expected: 0
      Actual:   2
         at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 96
         at ComWrappersTests.Program.ValidateComObjectExtendsManagedLifetime()
         at ComWrappersTests.Program.Main()
      Expected: 100
      Actual: 101
      END EXECUTION - FAILED
      Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 5/2/2023 6:14:41 AM
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/root/helix/work/correlation
      > /root/helix/work/workitem/e/Interop/COM/ComWrappers/API/ComWrappersTestsBuiltInComDisabled/ComWrappersTestsBuiltInComDisabled.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at Interop_COM._ComWrappers_API_ComWrappersTestsBuiltInComDisabled_ComWrappersTestsBuiltInComDisabled_._ComWrappers_API_ComWrappersTestsBuiltInComDisabled_ComWrappersTestsBuiltInComDisabled_sh()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
      Output:
        
        Return code:      1
        Raw output file:      /root/helix/work/workitem/uploads/Reports/Interop.COM/ComWrappers/API/ComWrappersTestsBuiltInComDisabled/ComWrappersTestsBuiltInComDisabled.output.txt
        Raw output:
        BEGIN EXECUTION
        /root/helix/work/correlation/corerun -p System.Runtime.InteropServices.BuiltInComInterop.IsSupported=false -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true ComWrappersTestsBuiltInComDisabled.dll ''
        Running ValidateComInterfaceCreation...
        Running ValidateComInterfaceCreationRoundTrip...
        Running ValidateComObjectExtendsManagedLifetime...
        Test Failure: Xunit.Sdk.EqualException: Assert.Equal() Failure
        Expected: 0
        Actual:   2
           at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 96
           at ComWrappersTests.Program.ValidateComObjectExtendsManagedLifetime()
           at ComWrappersTests.Program.Main()
        Expected: 100
        Actual: 101
        END EXECUTION - FAILED
        Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 5/2/2023 6:14:41 AM
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/root/helix/work/correlation
        > /root/helix/work/workitem/e/Interop/COM/ComWrappers/API/ComWrappersTestsBuiltInComDisabled/ComWrappersTestsBuiltInComDisabled.sh
    Interop/COM/ComWrappers/API/ComWrappersTests/ComWrappersTests.sh [FAIL]
      
      Return code:      1
      Raw output file:      /root/helix/work/workitem/uploads/Reports/Interop.COM/ComWrappers/API/ComWrappersTests/ComWrappersTests.output.txt
      Raw output:
      BEGIN EXECUTION
      /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true ComWrappersTests.dll ''
      Running ValidateComInterfaceCreation...
      Running ValidateComInterfaceCreationRoundTrip...
      Running ValidateComObjectExtendsManagedLifetime...
      Test Failure: Xunit.Sdk.EqualException: Assert.Equal() Failure
      Expected: 0
      Actual:   2
         at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 96
         at ComWrappersTests.Program.ValidateComObjectExtendsManagedLifetime()
         at ComWrappersTests.Program.Main()
      Expected: 100
      Actual: 101
      END EXECUTION - FAILED
      Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 5/2/2023 6:14:41 AM
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/root/helix/work/correlation
      > /root/helix/work/workitem/e/Interop/COM/ComWrappers/API/ComWrappersTests/ComWrappersTests.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at Interop_COM._ComWrappers_API_ComWrappersTests_ComWrappersTests_._ComWrappers_API_ComWrappersTests_ComWrappersTests_sh()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
      Output:
        
        Return code:      1
        Raw output file:      /root/helix/work/workitem/uploads/Reports/Interop.COM/ComWrappers/API/ComWrappersTests/ComWrappersTests.output.txt
        Raw output:
        BEGIN EXECUTION
        /root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true ComWrappersTests.dll ''
        Running ValidateComInterfaceCreation...
        Running ValidateComInterfaceCreationRoundTrip...
        Running ValidateComObjectExtendsManagedLifetime...
        Test Failure: Xunit.Sdk.EqualException: Assert.Equal() Failure
        Expected: 0
        Actual:   2
           at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 96
           at ComWrappersTests.Program.ValidateComObjectExtendsManagedLifetime()
           at ComWrappersTests.Program.Main()
        Expected: 100
        Actual: 101
        END EXECUTION - FAILED
        Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 5/2/2023 6:14:41 AM
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/root/helix/work/correlation
        > /root/helix/work/workitem/e/Interop/COM/ComWrappers/API/ComWrappersTests/ComWrappersTests.sh
  Finished:    Interop.COM.XUnitWrapper
  Discovering: Interop.IDynamicInterfaceCastable.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  Interop.IDynamicInterfaceCastable.XUnitWrapper (found 1 test case)
  Starting:    Interop.IDynamicInterfaceCastable.XUnitWrapper (parallel test collections = on, max threads = 2)
  Finished:    Interop.IDynamicInterfaceCastable.XUnitWrapper
  Discovering: Interop.NativeLibrary.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  Interop.NativeLibrary.XUnitWrapper (found 5 test cases)
  Starting:    Interop.NativeLibrary.XUnitWrapper (parallel test collections = on, max threads = 2)
  Finished:    Interop.NativeLibrary.XUnitWrapper
  Discovering: Interop.RefCharArray.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  Interop.RefCharArray.XUnitWrapper (found 1 test case)
  Starting:    Interop.RefCharArray.XUnitWrapper (parallel test collections = on, max threads = 2)
  Finished:    Interop.RefCharArray.XUnitWrapper
  Discovering: Interop.DisabledRuntimeMarshalling.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  Interop.DisabledRuntimeMarshalling.XUnitWrapper (found 5 test cases)
  Starting:    Interop.DisabledRuntimeMarshalling.XUnitWrapper (parallel test collections = on, max threads = 2)
  Finished:    Interop.DisabledRuntimeMarshalling.XUnitWrapper
  Discovering: Interop.StructPacking.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  Interop.StructPacking.XUnitWrapper (found 1 test case)
  Starting:    Interop.StructPacking.XUnitWrapper (parallel test collections = on, max threads = 2)
  Finished:    Interop.StructPacking.XUnitWrapper
  Discovering: Interop.DllImportSearchPaths.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  Interop.DllImportSearchPaths.XUnitWrapper (found 1 test case)
  Starting:    Interop.DllImportSearchPaths.XUnitWrapper (parallel test collections = on, max threads = 2)
  Finished:    Interop.DllImportSearchPaths.XUnitWrapper
  Discovering: Interop.ICastable.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  Interop.ICastable.XUnitWrapper (found 1 test case)
  Starting:    Interop.ICastable.XUnitWrapper (parallel test collections = on, max threads = 2)
  Finished:    Interop.ICastable.XUnitWrapper
  Discovering: Interop.StructMarshalling.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  Interop.StructMarshalling.XUnitWrapper (found 4 test cases)
  Starting:    Interop.StructMarshalling.XUnitWrapper (parallel test collections = on, max threads = 2)
  Finished:    Interop.StructMarshalling.XUnitWrapper
  Discovering: Interop.PInvoke.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  Interop.PInvoke.XUnitWrapper (found 29 test cases)
  Starting:    Interop.PInvoke.XUnitWrapper (parallel test collections = on, max threads = 2)
  Finished:    Interop.PInvoke.XUnitWrapper
  Discovering: Interop.UnmanagedCallConv.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  Interop.UnmanagedCallConv.XUnitWrapper (found 1 test case)
  Starting:    Interop.UnmanagedCallConv.XUnitWrapper (parallel test collections = on, max threads = 2)
  Finished:    Interop.UnmanagedCallConv.XUnitWrapper
=== TEST EXECUTION SUMMARY ===
   Interop.ArrayMarshalling.XUnitWrapper            Total:  1, Errors: 0, Failed: 0, Skipped: 0, Time:  0.209s
   Interop.BestFitMapping.XUnitWrapper              Total:  1, Errors: 0, Failed: 0, Skipped: 0, Time:  0.397s
   Interop.COM.XUnitWrapper                         Total:  4, Errors: 0, Failed: 2, Skipped: 0, Time:  1.611s
   Interop.DisabledRuntimeMarshalling.XUnitWrapper  Total:  5, Errors: 0, Failed: 0, Skipped: 0, Time:  0.912s
   Interop.DllImportAttribute.XUnitWrapper          Total:  2, Errors: 0, Failed: 0, Skipped: 0, Time:  0.337s
   Interop.DllImportSearchPaths.XUnitWrapper        Total:  1, Errors: 0, Failed: 0, Skipped: 0, Time:  0.250s
   Interop.FuncPtrAsDelegateParam.XUnitWrapper      Total:  1, Errors: 0, Failed: 0, Skipped: 0, Time:  0.263s
   Interop.ICastable.XUnitWrapper                   Total:  1, Errors: 0, Failed: 0, Skipped: 0, Time:  0.291s
   Interop.ICustomMarshaler.XUnitWrapper            Total:  3, Errors: 0, Failed: 0, Skipped: 0, Time:  0.647s
   Interop.IDynamicInterfaceCastable.XUnitWrapper   Total:  1, Errors: 0, Failed: 0, Skipped: 0, Time:  0.485s
   Interop.LayoutClass.XUnitWrapper                 Total:  1, Errors: 0, Failed: 0, Skipped: 0, Time:  0.309s
   Interop.MarshalAPI.XUnitWrapper                  Total:  1, Errors: 0, Failed: 0, Skipped: 0, Time:  0.400s
   Interop.MonoAPI.XUnitWrapper.dll                 Total:  0
   Interop.NativeLibrary.XUnitWrapper               Total:  5, Errors: 0, Failed: 0, Skipped: 0, Time:  1.019s
   Interop.PInvoke.XUnitWrapper                     Total: 29, Errors: 0, Failed: 0, Skipped: 0, Time:  5.600s
   Interop.PrimitiveMarshalling.XUnitWrapper        Total:  3, Errors: 0, Failed: 0, Skipped: 0, Time:  0.359s
   Interop.RefCharArray.XUnitWrapper                Total:  1, Errors: 0, Failed: 0, Skipped: 0, Time:  0.284s
   Interop.SimpleStruct.XUnitWrapper                Total:  1, Errors: 0, Failed: 0, Skipped: 0, Time:  0.328s
   Interop.StringMarshalling.XUnitWrapper           Total:  5, Errors: 0, Failed: 0, Skipped: 0, Time:  0.805s
   Interop.StructMarshalling.XUnitWrapper           Total:  4, Errors: 0, Failed: 0, Skipped: 0, Time:  1.312s
   Interop.StructPacking.XUnitWrapper               Total:  1, Errors: 0, Failed: 0, Skipped: 0, Time:  3.175s
   Interop.SuppressGCTransition.XUnitWrapper        Total:  1, Errors: 0, Failed: 0, Skipped: 0, Time:  0.364s
   Interop.UnmanagedCallConv.XUnitWrapper           Total:  1, Errors: 0, Failed: 0, Skipped: 0, Time:  0.336s
   Interop.UnmanagedCallersOnly.XUnitWrapper        Total:  1, Errors: 0, Failed: 0, Skipped: 0, Time:  0.311s
   Interop.UnmanagedCallersOnlyBasic.XUnitWrapper   Total:  1, Errors: 0, Failed: 0, Skipped: 0, Time:  0.301s
                                                           --          -          -           -        -------
                                              GRAND TOTAL: 75          0          2           0        20.304s (20.637s)
+ export _commandExitCode=1
+ python /root/helix/work/correlation/reporter/run.py https://dev.azure.com/dnceng-public/ public 5058936 eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im9PdmN6NU1fN3AtSGpJS2xGWHo5M3VfVjBabyJ9.eyJuYW1laWQiOiJjNzczZjJjMi01MTIwLTQyMDctYWZlMi1hZmFmMzVhOGJjMGEiLCJzY3AiOiJhcHBfdG9rZW4iLCJhdWkiOiI1ZGM2ZDdjNS0yNmFmLTQzMTgtODc0Ny1hYTAwYzMzMWU3MDUiLCJzaWQiOiI0MmFkYjVjYS0wZGU2LTQ5OWItYjFhOS1iODZiNGI3MWRkMmUiLCJCdWlsZElkIjoiY2JiMTgyNjEtYzQ4Zi00YWJiLTg2NTEtOGNkY2I1NDc0NjQ5OzI1ODkwMyIsImpvYnJlZiI6IjYxMDU2ZDJiLWRmM2QtNDU1Mi05YTA5LTZjNTM2NDQxNDQ1MTozNGIyZjUzYi1hZGQxLTVlNzQtN2EzOS01YTExNDgzMjk3ZmMiLCJwcGlkIjoidnN0ZnM6Ly8vQnVpbGQvQnVpbGQvMjU4OTAzIiwib3JjaGlkIjoiNjEwNTZkMmItZGYzZC00NTUyLTlhMDktNmM1MzY0NDE0NDUxLmJ1aWxkLnJ1bl90ZXN0X3AxX19saW51eF9hcm02NF9jaGVja2VkLl9fZGVmYXVsdCIsInJlcG9JZHMiOiIiLCJpc3MiOiJhcHAudnN0b2tlbi52aXN1YWxzdHVkaW8uY29tIiwiYXVkIjoiYXBwLnZzdG9rZW4udmlzdWFsc3R1ZGlvLmNvbXx2c286NmZjYzkyZTUtNzNhNy00Zjg4LThkMTMtZDkwNDViNDVmYjI3IiwibmJmIjoxNjgzMDA0ODc0LCJleHAiOjE2ODMwMjk0NzR9.02h_qTUWCm6yluuhVlD5pM8YOleg3LR5ZeR2HJbSWMNkuFoTjh50pSe6qqOoRXeexJNwC2dKxK83zwRJJ2rLPdcgXVmwo4GXcUy0mGAAYGQUCaPxZc6xUGGOIojFmMXzKVbE-dcmVbYc58yit4m7Gxo7nNTARumtqNixKZZlGzZciKnlLTccxCJs9kp4v4oT7rFuSb7QO8Faj95QRfAuG6vNbZfPrd0ZyW8MCX-AAVgG-UF8-MKFdk4x1P0fQDgN_Qjl6FLXJxbd2a0gEUj6FG6agGCK6Zra2R2FIuO4ZacyzxRAh0qBCy090U0eyJZ7rOTETQ-arXLuY5VZuoIiCg
2023-05-02T06:14:57.035Z	INFO   	run.py	run(48)	main	Beginning reading of test results.
2023-05-02T06:14:57.035Z	INFO   	run.py	__init__(42)	read_results	Searching '/root/helix/work/workitem/e' for test results files
2023-05-02T06:14:57.036Z	INFO   	run.py	__init__(48)	read_results	Found results file /root/helix/work/workitem/e/testResults.xml with format xunit
2023-05-02T06:14:57.046Z	INFO   	run.py	__init__(42)	read_results	Searching '/root/helix/work/workitem/uploads' for test results files
2023-05-02T06:14:57.050Z	INFO   	run.py	packing_test_reporter(30)	report_results	Packing 75 test reports to '/root/helix/work/workitem/e/__test_report.json'
2023-05-02T06:14:57.051Z	INFO   	run.py	packing_test_reporter(33)	report_results	Packed 31497 bytes
+ exit 1
+ export _commandExitCode=1
+ chmod -R 777 /home/helixbot/dotnetbuild/dumps
+ exit 1

[END EXECUTION]
Exit Code:1
```

**Comment by BruceForstall** [comment] 2023-05-05 21:08
@dotnet/interop-contrib

**Comment by AaronRobinsonMSFT** [comment] 2023-05-06 08:00
@jkoritzinsky Is it possible that changing this to the source generated xUnit style caused a regression?

**Comment by jkoritzinsky** [comment] 2023-05-06 15:18
I guess it's possible, but I'm not sure how.

**Comment by AaronRobinsonMSFT** [comment] 2023-05-08 08:37
Duplicate of https://github.com/dotnet/runtime/issues/85262

**Closed by AaronRobinsonMSFT** 2023-05-08 08:37 UTC
Labels: arch-arm64, os-linux, area-CodeGen-coreclr, untriaged, blocking-clean-ci-optional, test-failure
