### ISSUE TITLE
Test failure JIT\\Performance\\CodeQuality\\Benchstones\\BenchF\\NewtE\\NewtE\\NewtE.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#60238] opened 2021-10-11 01:09 UTC
Run: [runtime-coreclr outerloop 20211010.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1412533&view=ms.vss-test-web.build-test-results-tab&runId=40947192&resultId=106507&paneView=debug)

Failed test:
```

R2R-CG2 windows arm Checked @ Windows.10.Arm64v8.Open

- JIT\\Performance\\CodeQuality\\Benchstones\\BenchF\\NewtE\\NewtE\\NewtE.cmd

```
**Error message:**
```
Could Not Find D:\h\w\A8120961\w\BE2E0A5C\e\JIT\Performance\CodeQuality\Benchstones\BenchF\NewtE\NewtE\IL-CG2\composite-r2r.dll
Could Not Find D:\h\w\A8120961\w\BE2E0A5C\e\JIT\Performance\CodeQuality\Benchstones\BenchF\NewtE\NewtE\NewtE.dll.rsp
Fatal error. Internal CLR error. (0x80131506)
at System.SZArrayHelper.GetEnumerator[Internal.JitInterface.CorJitFlag, ILCompiler.ReadyToRun, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null]
at Internal.JitInterface.CorInfoImpl.getJitFlags(Internal.JitInterface.CORJIT_FLAGS ByRef, UInt32)
at Internal.JitInterface.CorInfoImpl._getJitFlags(IntPtr, IntPtr*, Internal.JitInterface.CORJIT_FLAGS*, UInt32)
at Internal.JitInterface.CorInfoImpl.JitCompileMethod(IntPtr ByRef, IntPtr, IntPtr, IntPtr, Internal.JitInterface.CORINFO_METHOD_INFO ByRef, UInt32, IntPtr ByRef, UInt32 ByRef)
at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(ILCompiler.DependencyAnalysis.IMethodNode, Internal.IL.MethodIL)
at Internal.JitInterface.CorInfoImpl.CompileMethod(ILCompiler.DependencyAnalysis.ReadyToRun.MethodWithGCInfo, ILCompiler.Logger)
at ILCompiler.ReadyToRunCodegenCompilation.<ComputeDependencyNodeDependencies>b__35_0(ILCompiler.DependencyAnalysisFramework.DependencyNodeCore1<ILCompiler.DependencyAnalysis.NodeFactory>) at System.Threading.Tasks.Parallel+<>c__DisplayClass33_02[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForEachWorker>b__0(Int32)
at System.Threading.Tasks.Parallel+<>c__DisplayClass19_0`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef, Int32, Boolean ByRef)
at System.Threading.Tasks.TaskReplicator+Replica.Execute()
at System.Threading.Tasks.TaskReplicator+Replica+<>c.<.ctor>b__4_0(System.Object)
at System.Threading.Tasks.Task.InnerInvoke()
at System.Threading.Tasks.Task+<>c.<.cctor>b__271_0(System.Object)
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
at System.Threading.Thread.StartCallback()

Return code:      1
Raw output file:      D:\h\w\A8120961\w\BE2E0A5C\uploads\Reports\JIT.Performance\CodeQuality\Benchstones\BenchF\NewtE\NewtE\NewtE.output.txt
Raw output:
BEGIN EXECUTION
NewtE.dll
1 file(s) copied.
Response file: D:\h\w\A8120961\w\BE2E0A5C\e\JIT\Performance\CodeQuality\Benchstones\BenchF\NewtE\NewtE\NewtE.dll.rsp
D:\h\w\A8120961\w\BE2E0A5C\e\JIT\Performance\CodeQuality\Benchstones\BenchF\NewtE\NewtE\IL-CG2\NewtE.dll
-o:D:\h\w\A8120961\w\BE2E0A5C\e\JIT\Performance\CodeQuality\Benchstones\BenchF\NewtE\NewtE\NewtE.dll
--targetarch:arm
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\A8120961\p\System..dll
-r:D:\h\w\A8120961\p\Microsoft..dll
-r:D:\h\w\A8120961\p\mscorlib.dll
-r:D:\h\w\A8120961\p\netstandard.dll
-O
" "dotnet" "D:\h\w\A8120961\p\crossgen2\crossgen2.dll" @"D:\h\w\A8120961\w\BE2E0A5C\e\JIT\Performance\CodeQuality\Benchstones\BenchF\NewtE\NewtE\NewtE.dll.rsp"   -r:D:\h\w\A8120961\w\BE2E0A5C\e\JIT\Performance\CodeQuality\Benchstones\BenchF\NewtE\NewtE\IL-CG2*.dll"
Crossgen2 failed with exitcode - -1073741819
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\A8120961\p
D:\h\w\A8120961\w\BE2E0A5C\e\JIT\Performance\CodeQuality\Benchstones\BenchF\NewtE\NewtE\NewtE.cmd
Expected: True
Actual:


Stack trace
   at JIT_Performance._CodeQuality_Benchstones_BenchF_NewtE_NewtE_NewtE_._CodeQuality_Benchstones_BenchF_NewtE_NewtE_NewtE_cmd()
```

**Comment by trylek** [comment] 2022-04-04 20:43
Closing as duplicate of: https://github.com/dotnet/runtime/issues/66183

**Closed by trylek** 2022-04-04 20:43 UTC
Labels: os-windows, area-crossgen2-coreclr, untriaged
