### ISSUE TITLE
Test failure JIT/Regression/JitBlue/GitHub_13910/GitHub_13910/GitHub_13910.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#95713] opened 2023-12-07 01:09 UTC
**Failed in:** [runtime-coreclr r2r 20231205.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=490096&view=ms.vss-test-web.build-test-results-tab&runId=11342674&resultId=117710&paneView=debug)

**Failed tests:**
```
R2R-CG2 osx arm64 Checked @ OSX.1200.ARM64.Open
    - JIT/Regression/JitBlue/GitHub_13910/GitHub_13910/GitHub_13910.cmd
```

**Error message:**
```
/private/tmp/helix/working/B03509AF/w/ACD2094A/e/JIT/Regression/Regression_3/../JitBlue/GitHub_13910/GitHub_13910/GitHub_13910.sh: line 315: -r:/private/tmp/helix/working/B03509AF/w/ACD2094A/e/JIT/Regression/JitBlue/GitHub_13910/GitHub_13910/IL-CG2/*.dll: No such file or directory
/private/tmp/helix/working/B03509AF/w/ACD2094A/e/JIT/Regression/Regression_3/../JitBlue/GitHub_13910/GitHub_13910/GitHub_13910.sh: line 254:  5983 Abort trap: 6           (core dumped) $__R2RDumpCommand

Return code:      1
Raw output file:      /tmp/helix/working/B03509AF/w/ACD2094A/uploads/JitBlue/GitHub_13910/GitHub_13910/output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/private/tmp/helix/working/B03509AF/w/ACD2094A/e/JIT/Regression/JitBlue/GitHub_13910/GitHub_13910/IL-CG2/GitHub_13910.dll
23:04:23
Response file: /private/tmp/helix/working/B03509AF/w/ACD2094A/e/JIT/Regression/JitBlue/GitHub_13910/GitHub_13910/GitHub_13910.dll.rsp
/private/tmp/helix/working/B03509AF/w/ACD2094A/e/JIT/Regression/JitBlue/GitHub_13910/GitHub_13910/IL-CG2/GitHub_13910.dll
-o:/private/tmp/helix/working/B03509AF/w/ACD2094A/e/JIT/Regression/JitBlue/GitHub_13910/GitHub_13910/GitHub_13910.dll
-r:/tmp/helix/working/B03509AF/p/System.*.dll
-r:/tmp/helix/working/B03509AF/p/Microsoft.*.dll
-r:/tmp/helix/working/B03509AF/p/xunit.*.dll
-r:/tmp/helix/working/B03509AF/p/mscorlib.dll
--verify-type-and-field-layout
--method-layout:random
--targetarch:arm64
--targetos:osx
Running CrossGen2:  dotnet /tmp/helix/working/B03509AF/p/crossgen2/crossgen2.dll @/private/tmp/helix/working/B03509AF/w/ACD2094A/e/JIT/Regression/JitBlue/GitHub_13910/GitHub_13910/GitHub_13910.dll.rsp  
Emitting R2R PE file: /private/tmp/helix/working/B03509AF/w/ACD2094A/e/JIT/Regression/JitBlue/GitHub_13910/GitHub_13910/GitHub_13910.dll
Running R2RDump:  dotnet /tmp/helix/working/B03509AF/p/R2RDump/R2RDump.dll --header --sc --in /private/tmp/helix/working/B03509AF/w/ACD2094A/e/JIT/Regression/JitBlue/GitHub_13910/GitHub_13910/GitHub_13910.dll --out /private/tmp/helix/working/B03509AF/w/ACD2094A/e/JIT/Regression/JitBlue/GitHub_13910/GitHub_13910/GitHub_13910.dll.r2rdump --val
[createdump] Gathering state for process 5983 
[createdump] Crashing thread 877b20 signal 6 (0006)
[createdump] Writing crash report to file /cores/coredump.5983.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /cores/coredump.5983.dmp
[createdump] Written 346607768 bytes (21155 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 1240ms
23:04:34
R2RDump failed with exitcode: 134
in ReleaseLock
Test failed. Trying to see if dump file was created in /cores since 12/5/2023 11:04:23 PM
Processing /cores/coredump.5983.dmp.crashreport.json
Printing stacktrace from '/cores/coredump.5983.dmp.crashreport.json'
Invoking llvm-symbolizer --pretty-print
Errors while running llvm-symbolizer --pretty-print
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'llvm-symbolizer' with working directory '/private/tmp/helix/working/B03509AF/w/ACD2094A/e/JIT/Regression/Regression_3'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs:line 498
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs:line 456
   at System.Diagnostics.Process.Start() in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs:line 1282
   at CoreclrTestLib.CoreclrTestWrapperLib.TryPrintStackTraceFromCrashReport(String crashReportJsonFile, TextWriter outputWr
```
**Stack trace:**
```
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor335|0_336(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2023-12-06T06:47:53.55Z | runtime-coreclr r2r | Checked | osx.1200.arm64.open | arm64 | JIT/Regression/JitBlue/GitHub_13910/GitHub_13910/GitHub_13910.cmd | Failed | {"operatingSystem":"OSX.1200.ARM64.Open","DefinitionId":"120","architecture":"arm64","System.JobAttempt":"1","System.PhaseAttempt":"1","BuildNumber":"20231205.1","DefinitionName":"runtime-coreclr r2r","Project":"public","System.PhaseName":"run_test_p1_R2R_osx_arm64_checked","System.JobId":"99f15f99-448d-5593-a271-dbdf553789a6","configuration":"Checked","Reason":"Schedule","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.StageName":"Build","AzurePipelinesTestRunId":"11342674","BuildId":"490096","System.JobName":"__default"} | Schedule
2023-12-06T06:47:53.55Z | runtime-coreclr r2r | Checked | osx.1200.arm64.open | arm64 | JIT/Regression/JitBlue/GitHub_13910/GitHub_13910/GitHub_13910.cmd | Failed | {"operatingSystem":"OSX.1200.ARM64.Open","DefinitionId":"120","architecture":"arm64","System.JobAttempt":"1","System.PhaseAttempt":"1","BuildNumber":"20231205.1","DefinitionName":"runtime-coreclr r2r","Project":"public","System.PhaseName":"run_test_p1_R2R_osx_arm64_checked","System.JobId":"99f15f99-448d-5593-a271-dbdf553789a6","configuration":"Checked","Reason":"Schedule","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.StageName":"Build","AzurePipelinesTestRunId":"11342674","BuildId":"490096","System.JobName":"__default"} | Schedule
2023-12-06T06:47:53.55Z | runtime-coreclr r2r | Checked | osx.1200.arm64.open | arm64 | JIT/Regression/JitBlue/GitHub_13910/GitHub_13910/GitHub_13910.cmd | Failed | {"operatingSystem":"OSX.1200.ARM64.Open","DefinitionId":"120","architecture":"arm64","System.JobAttempt":"1","System.PhaseAttempt":"1","BuildNumber":"20231205.1","DefinitionName":"runtime-coreclr r2r","Project":"public","System.PhaseName":"run_test_p1_R2R_osx_arm64_checked","System.JobId":"99f15f99-448d-5593-a271-dbdf553789a6","configuration":"Checked","Reason":"Schedule","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.StageName":"Build","AzurePipelinesTestRunId":"11342674","BuildId":"490096","System.JobName":"__default"} | Schedule
2023-12-06T06:47:53.55Z | runtime-coreclr r2r | Checked | osx.1200.arm64.open | arm64 | JIT/Regression/JitBlue/GitHub_13910/GitHub_13910/GitHub_13910.cmd | Failed | {"operatingSystem":"OSX.1200.ARM64.Open","DefinitionId":"120","architecture":"arm64","System.JobAttempt":"1","System.PhaseAttempt":"1","BuildNumber":"20231205.1","DefinitionName":"runtime-coreclr r2r","Project":"public","System.PhaseName":"run_test_p1_R2R_osx_arm64_checked","System.JobId":"99f15f99-448d-5593-a271-dbdf553789a6","configuration":"Checked","Reason":"Schedule","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.StageName":"Build","AzurePipelinesTestRunId":"11342674","BuildId":"490096","System.JobName":"__default"} | Schedule

**Comment by BruceForstall** [comment] 2023-12-07 17:36
@dotnet/crossgen-contrib

**Comment by steveisok** [comment] 2024-06-21 15:38
@ivdiazsa is this still an issue?

**Comment by ivdiazsa** [comment] 2024-07-02 22:02
Closing since this test is no longer around the codebase.

**Comment by ivdiazsa** [comment] 2024-07-02 22:19
My mistake, it is there. Will try to reproduce.

**Comment by ivdiazsa** [comment] 2024-07-03 17:14
Closing since could not reproduce and hasn't shown up in the pipelines in recent times.

**Closed by ivdiazsa** 2024-07-03 17:14 UTC
Labels: arch-arm64, os-mac-os-x, area-crossgen2-coreclr, blocking-clean-ci-optional
