### ISSUE TITLE
iOS: NullReferenceException in HttpConnectionPool when using HttpWebRequest

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#49201] opened 2021-03-05 07:43 UTC
### Description

Test case:

* Checkout and build the `httpclient-testcase` branch of my fork of xamarin-macios (https://github.com/rolfbjarne/xamarin-macios/commits/httpclient-testcase): 

```
git clone https://github.com/rolfbjarne/xamarin-macios
cd xamarin-macios
git checkout httpclient-testcase
./configure --enable-dotnet
make reset
make all -j8 && make install -j8
```

* Run the test app:

```
make -C tests/dotnet run-test
```

Result:

```
[...]
Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
   at System.Net.Http.HttpConnectionPool..ctor(HttpConnectionPoolManager poolManager, HttpConnectionKind kind, String host, Int32 port, String sslHostName, Uri proxyUri, Int32 maxConnections)
   at System.Net.Http.HttpConnectionPoolManager.SendAsyncCore(HttpRequestMessage request, Uri proxyUri, Boolean async, Boolean doRequestAuth, Boolean isProxyConnect, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPoolManager.SendAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.SocketsHttpHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.HttpWebRequest.SendRequest(Boolean async)
   at System.Net.HttpWebRequest.GetResponse()
   at MySingleView.AppDelegate.FinishedLaunching(UIApplication app, NSDictionary options) in /Users/rolf/work/maccore/main/xamarin-macios/tests/dotnet/MySingleView/AppDelegate.cs:line 22
--- End of stack trace from previous location ---
   at UIKit.UIApplication.Main(String[] args, IntPtr principal, IntPtr delegate)
   at UIKit.UIApplication.Main(String[] args, String principalClassName, String delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at MySingleView.Application.Main(String[] args) in /Users/rolf/work/maccore/main/xamarin-macios/tests/dotnet/MySingleView/Main.cs:line 12
```

I tried reproing on desktop (https://gist.github.com/rolfbjarne/f1cb38aab4ba58b49b2ec244e45d1a70), but it worked just fine.

### Regression?

Yes, this is a regression between `preview.2.21114.3` and `preview.2.21153.28`.

CC @steveisok

**Comment by marek-safar** [comment] 2021-03-05 09:17
@karelz We don't believe this is ios specific as it crashes with normal SocketsHttpHandler handler. Could someone investigate why is `HttpConnectionPool..ctor` crashing with NRE when we have nullable types enabled?

**Comment by marek-safar** [comment] 2021-03-05 09:22
Likely duplicate of #49201

**Comment by stephentoub** [comment] 2021-03-05 14:56
>  We don't believe this is ios specific

Have you seen it on any other OS?

> when we have nullable types enabled

What do you mean by this?  Are you referring to nullable reference types?  The only thing NRT influences in a compiled binary are the attributes that are emitted; it doesn't change the IL for member bodies at all.

**Comment by marek-safar** [comment] 2021-03-05 15:15
> Have you seen it on any other OS?

I didn't try but there does not seem to be anything ios specific on the stack.

>What do you mean by this? 

In spot-checking HttpConnectionPool..ctor I didn't see any `!` so it's a bit surprising to have no compiler warning and crash with NRE.

**Comment by stephentoub** [comment] 2021-03-05 15:19
Are the binaries in use trimmed?

**Comment by stephentoub** [comment] 2021-03-05 15:26
For example, @marek-safar, in https://github.com/dotnet/runtime/pull/48480 you removed the System.Net.Quic build for iOS, but this method calls into that assembly:
https://github.com/dotnet/runtime/blob/b76f17e0a270818a2795f91661c0d0ec8ffca97a/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L122
What happens in that case?

**Comment by rolfbjarne** [comment] 2021-03-05 15:26
Here's the binlog and the .app zipped up:

[msbuild.rename-extension-to-binlog.zip](https://github.com/dotnet/runtime/files/6091464/msbuild.rename-extension-to-binlog.zip)
[MySingleView.zip](https://github.com/dotnet/runtime/files/6091466/MySingleView.zip)

**Comment by stephentoub** [comment] 2021-03-05 15:27
That's the problem:
![image](https://user-images.githubusercontent.com/2642209/110136187-62736800-7d9d-11eb-8028-2eb9b8244003.png)

**Comment by ManickaP** [comment] 2021-03-05 15:28
> I tried reproing on desktop (https://gist.github.com/rolfbjarne/f1cb38aab4ba58b49b2ec244e45d1a70), but it worked just fine.

I assumed iOS from this in the OP.

**Comment by marek-safar** [comment] 2021-03-05 15:40
Yeah, this will fail only with PNSE versions of System.Net.Quic. Though I'm not sure why the generator  didn't rewrite the body to PNSE. The only difference I see is that it's a static class.

**Comment by ericstj** [comment] 2021-03-12 20:51
> Yeah, this will fail only with PNSE versions of System.Net.Quic. Though I'm not sure why the generator didn't rewrite the body to PNSE. The only difference I see is that it's a static class and we'd get an analyzer warning.

It looks to me like it's due using expression bodies in the reference source.  The PNSE generator isn't transforming those.  As a simple workaround, just run /t:GenerateReferenceAssemblySource on System.Net.Quic to update its reference source to a format understood by the rewriter.  We'll still fix the rewriter.

**Closed** 2021-04-15 15:26 UTC
Labels: area-System.Net.Http, in pr, os-android, os-ios
