### ISSUE TITLE
SocketsHttpHandler rejects certificate with RemoteCertificateNameMismatch .Net Core 3.1 linux

### ISSUE THREAD

**Issue by pcchannz** [dotnet/runtime#33609] opened 2020-03-15 21:10 UTC
Refer to this: https://github.com/dotnet/runtime/issues/26494

If I use .net core 2.2 without setting DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0, certificate validation is good. So i guess the fix were there.

But on .net core 3.1 app, the error RemoteCertificateNameMismatch is back. There is no chainstatus and I have to disable default socket http to get it working again.

**Comment by scalablecory** [comment] 2020-03-16 12:09
Do you have a small sample app that demonstrates this behavior?

**Comment by shachar-clinch** [comment] 2020-04-02 08:52
Happens to me as well, works on windows but fails on linux with .net core 3.1.3. I have a sample app with 3 lines of code:
`       var httpClient = new HttpClient();
        var response = await httpClient.GetAsync(args[0]); // -> throws exception on linux
        Console.WriteLine($"{response.StatusCode} - {response.Content.Headers.ContentLength}");
`
I am trying that against amazon S3 subdomain

the certificate information:
openssl s_client -connect 52.216.230.123:443
CONNECTED(00000005)
depth=2 C = IE, O = Baltimore, OU = CyberTrust, CN = Baltimore CyberTrust Root
verify return:1
depth=1 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Baltimore CA-2 G2
verify return:1
depth=0 C = US, ST = Washington, L = Seattle, O = "Amazon.com, Inc.", CN = *.s3.amazonaws.com
verify return:1
---
Certificate chain
 0 s:C = US, ST = Washington, L = Seattle, O = "Amazon.com, Inc.", CN = *.s3.amazonaws.com
   i:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Baltimore CA-2 G2
 1 s:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Baltimore CA-2 G2
   i:C = IE, O = Baltimore, OU = CyberTrust, CN = Baltimore CyberTrust Root
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIG3DCCBcSgAwIBAgIQCC32junGkxW+v3IHmzgQ/TANBgkqhkiG9w0BAQsFADBk
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMSMwIQYDVQQDExpEaWdpQ2VydCBCYWx0aW1vcmUgQ0Et
MiBHMjAeFw0xOTExMDkwMDAwMDBaFw0yMTAzMTIxMjAwMDBaMGwxCzAJBgNVBAYT
AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdTZWF0dGxlMRkwFwYD
VQQKExBBbWF6b24uY29tLCBJbmMuMRswGQYDVQQDDBIqLnMzLmFtYXpvbmF3cy5j
b20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDJW86RuSlYnitcFHiQ
298DPDFqEaC10ttw23m1Y+20aHic+GM9iUD+r2XO7LavEoZ0LORnEF5jM6bjt4aH
oXqZ6rB9fj6oMhtlQ8M7w72+WdM7aJ/6ZcqO3+NB+RB56pitqSQjukvSI88mjY6k
Mk/Qg2ZEABA3a/DwMfVS1Mcznqaw/yt+t+r+e33/WFTAZ3A0jmyXMCTIVrcpWulv
kza70D/oiF5Peiwlc8oey4x+A/QDfrmQHv/wu7sJegFj0hlQ96LqfjdHu48t6que
2yE2S8Ae6+2QXMrvloR9jOKK0EarN5bxSOpU1HriwiNwO3/bGEYjSnL0xLkpTKv/
eGHzAgMBAAGjggOAMIIDfDAfBgNVHSMEGDAWgBTAErIodGhGZ+lwJXQaAEVbBn1c
RDAdBgNVHQ4EFgQU3fImAGS3yvdcppam16zL4ScVDBMwLwYDVR0RBCgwJoISKi5z
My5hbWF6b25hd3MuY29tghBzMy5hbWF6b25hd3MuY29tMA4GA1UdDwEB/wQEAwIF
oDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwgYEGA1UdHwR6MHgwOqA4
oDaGNGh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEJhbHRpbW9yZUNB
LTJHMi5jcmwwOqA4oDaGNGh0dHA6Ly9jcmw0LmRpZ2ljZXJ0LmNvbS9EaWdpQ2Vy
dEJhbHRpbW9yZUNBLTJHMi5jcmwwTAYDVR0gBEUwQzA3BglghkgBhv1sAQEwKjAo
BggrBgEFBQcCARYcaHR0cHM6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzAIBgZngQwB
AgIweQYIKwYBBQUHAQEEbTBrMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdp
Y2VydC5jb20wQwYIKwYBBQUHMAKGN2h0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNv
bS9EaWdpQ2VydEJhbHRpbW9yZUNBLTJHMi5jcnQwDAYDVR0TAQH/BAIwADCCAX0G
CisGAQQB1nkCBAIEggFtBIIBaQFnAHYApLkJkLQYWBSHuxOizGdwCjw1mAT5G9+4
43fNDsgN3BAAAAFuTXY7MAAABAMARzBFAiEAifHUKVkZIWkFHtFhj/67xabxyzSu
d6PCFBt38GXC6XkCIDMPF2N2mKzbst5SXda23BFBufDKzr65+2FfwBi/kAbuAHYA
RJRlLrDuzq/EQAfYqP4owNrmgr7YyzG1P9MzlrW2gagAAAFuTXY7KAAABAMARzBF
AiEArv1CKeorl1PX81umtl6pGG1EHBMmMutjOBoqy/uRtDcCIEKX1COA9LAdsGba
c+OaQuDJ6NgVI21BJvp1+tp2nkMLAHUAu9nfvB+KcbWTlCOXqpJ7RzhXlQqrUuga
kJZkNo4e0YUAAAFuTXY7NQAABAMARjBEAiAbg6xfQS9eHRVZuZJWoA+B8ppvSsIj
wmuCOOsVEGZEagIgQcPbXr7jb+KbF7vZGOUNsRUwOU+BFrIVFmRFZ1i4S7EwDQYJ
KoZIhvcNAQELBQADggEBAAyJqLR4IsJWivGmNp4NrBQyQJCHDeHkhCrINnG+kwKl
8Z+YtkNT37eghIQtnpu1Pf8TZXAB19hW/Pqc9hHUTflDocABgr3NQAQky3nIa6xG
P6x2yyYoBTxOBsLXD2Hfb9uy5MOZCWnJxi+OjlE4SyterDtrODalRruhsZLFclcf
68pfpR0+jrIDM4px3FRjrdIdf2wV2iT/gxRmeDCiO4kE3ClbzwDt3oPJxGZfzrKI
/jBUKommu5hnhLgdvOA8dXuaGLOT98kd8jgvNr7xwB/FIvAPyEoZMzgI6R5AICXd
S+ZudBk1TeOZGidtNVBrxg93SBwwGsP/Wgva0PQtmmM=
-----END CERTIFICATE-----
subject=C = US, ST = Washington, L = Seattle, O = "Amazon.com, Inc.", CN = *.s3.amazonaws.com

issuer=C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Baltimore CA-2 G2

---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 3395 bytes and written 442 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: 39D6EE36B4A70E42D69CBD5B9AD1F4A6DEE8D381C2664461EB7A0332921E43F2
    Session-ID-ctx:
    Master-Key: CBD8B75A6CCE343FCB1E966C42C87402CDC64FABE4BE45C9A3A6CEED3060B934318185E8135EF825B305EF94EEE8A01C
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1585816782
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
---
closed

**Comment by karelz** [comment] 2020-05-06 23:30
@shachar-clinch we need a repro that we can ideally run locally. Is it something you could provide?

**Comment by wfurt** [comment] 2020-05-07 05:00
What name do you connect to? e.g. what is arg0? I tried to connect to reverse name of 52.216.230.123 and I get 403 without any ssl error on Ubuntu18.

**Comment by shachar-clinch** [comment] 2020-05-10 06:42
I would rather not disclose that in a public thread. can I send it to you directly?

**Comment by wfurt** [comment] 2020-05-10 06:44
sure. you can use my GH address tweinfurt at yahoo.

**Comment by wfurt** [comment] 2020-05-10 06:52
oh. This is dup of https://github.com/dotnet/runtime/issues/35880
cc: @bartonjs

**Comment by karelz** [comment] 2020-05-10 07:38
Duplicate of #35880

**Closed by karelz** 2020-05-10 07:38 UTC
Labels: area-System.Net.Http, needs more info, tenet-compatibility
