### ISSUE TITLE
[HTTP/3] WinHttpHandler

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#56957] opened 2021-08-06 03:00 UTC
What is the plan for HTTP/3 and WinHttpHandler?

It would be kind of useful to have another HTTP/3 implementation to compare against.

**Comment by filipnavara** [comment] 2021-08-06 14:05
I don't think WinHTTP even has support HTTP/3 at the API level. The flags suggest only HTTP/2 to be supported (https://docs.microsoft.com/en-us/windows/win32/winhttp/option-flags).

**Comment by JamesNK** [comment] 2021-08-06 20:38
It may be supported on Insider builds, and not yet publically documented.

🤷

**Comment by ManickaP** [comment] 2021-08-09 07:42
@nibanks do you know anything about WinHTTP supporting H/3 in near or distant future? I assume it would be based on msquic as well, but I might be wrong here...

**Comment by nibanks** [comment] 2021-08-09 11:02
Eventually. I don't think anything is exposed in Insider builds yet though. You'll have to contact the Windows HTTP folks to confirm.

**Comment by JamesNK** [comment] 2021-08-10 01:02
Lets talk to WinHTTP folks post-.NET 6 and figure out where they are at.

**Comment by liveans** [comment] 2024-06-18 08:53
Duplicate of #103561

**Closed by liveans** 2024-06-18 08:53 UTC
Labels: enhancement, area-System.Net.Http, tracking-external-issue
