### ISSUE TITLE
[Perf -6%] System.Collections.CreateAddAndRemove<Int32>.SortedList

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#37801] opened 2020-06-12 17:28 UTC
### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Changes | [diff](https://github.com/dotnet/installer/compare/a4a49f07fbf986d496ef57521e76b22caaf9bfb3...ccd701fe23f236755650af3ce3d9ab6bdd8a4af9)

### Regressions in System.Collections.CreateAddAndRemove<Int32>

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier
-- | -- | -- | -- | -- | --
SortedList | 126.74 μs | 134.04 μs | 1.06 |  | False

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/06_12_2020/release/3.1.1xx%20-%3E%20master_x64_Windows%2010.0.18362/System.Collections.CreateAddAndRemove(Int32)_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/06_12_2020/release/3.1.1xx%20-%3E%20master_x64_Windows%2010.0.18362/System.Collections.CreateAddAndRemove(Int32).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Collections.CreateAddAndRemove<Int32>*';
```
<details>

#### System.Collections.CreateAddAndRemove<Int32>.SortedList(Size: 512)

```log
[124732.826 ; 127426.459) | @@@@@@@@@@@
[127426.459 ; 130051.050) | @@@@@@@@@@@@@@@@@@@@@@@@
[130051.050 ; 133750.686) | @@@@
[133750.686 ; 138403.785) | @@@@@@@@@@@@@@@@@@@
[138403.785 ; 143874.037) | @
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by DrewScoggins** [comment] 2020-06-12 17:29
@adamsitnik

**Comment by danmosemsft** [comment] 2020-08-01 00:54
Duplicate of #39112

**Closed by danmosemsft** 2020-08-01 00:54 UTC
Labels: arch-x64, area-System.Collections, os-windows, tenet-performance, tenet-performance-benchmarks
