### ISSUE TITLE
JSON Deserialization does not work with C#9 records when using PascalCase-Properties

### ISSUE THREAD

**Issue by Unknown6656** [dotnet/runtime#41915] opened 2020-09-05 14:40 UTC
### Description
The following code works flawlessly:
```csharp
record TEST(int mynumber, string helloworld);

string json = JsonSerializer.Serialize(new TEST(1234, "hello"));
TEST data = JsonSerializer.Deserialize<TEST>(json);
```
Now change the properties of the record as follows:
```csharp
record TEST(int MyNumber, string HelloWorld);
```
And the runtime will complain about parameter names not matching the expected casing in the last line (`JsonSerializer.Deserialize(...)`).

### Configuration

Microsoft Visual Studio Community 2019 Version 16.7.2+30413.136
C# Tools   3.7.0-6.20412.3+d3c3a44a4e7ad31cc75c59be0d3df4a19ff33878
.NET SDK 5.0.100-preview.7.20366.6

------------------------------

This should behaviour be either fixed or documented somewhere.
Furthermore, one should have the possibility to configure this behaviour (e.g. via the SerializationOptions)

**Comment by huoyaoyuan** [comment] 2020-09-05 15:52
It should work in Preview 8

**Comment by am11** [comment] 2020-09-06 09:44
With [`5.0.100-rc.1.20426.10`](https://github.com/dotnet/installer#installers-and-binaries),

```c#
using System;
using System.Text.Json;

namespace Foo
{
    record TEST(int MyNumber, string HelloWorld);

    class Program
    {
        static void Main()
        {
            string json = JsonSerializer.Serialize(new TEST(1234, "hello"));
            TEST data = JsonSerializer.Deserialize<TEST>(json);

            Console.WriteLine("{0}: {1}, {2}: {3}",
                nameof(TEST.MyNumber), data.MyNumber,
                nameof(TEST.HelloWorld), data.HelloWorld);
        }
    }
}
```
prints:

```sh
MyNumber: 1234, HelloWorld: hello
```

**Comment by layomia** [comment] 2020-09-08 18:26
Fixed in https://github.com/dotnet/runtime/pull/38959.

**Closed by layomia** 2020-09-08 18:26 UTC
Labels: area-System.Text.Json, untriaged

**Comment by danmosemsft** [comment] 2020-09-08 18:36
@Unknown6656 please pick up an RC1 build from https://github.com/dotnet/installer#installers-and-binaries and let us know if you have other feedback.

**Comment by Unknown6656** [comment] 2020-09-09 10:14
@danmosemsft I will do that as soon as possible. Thank you in advance for all the work!

**Comment by huoyaoyuan** [comment] 2020-09-09 10:16
Note: If you are unable to use latest preview SDK (because they rejects VS16.7), you can still consume the preview8 nuget package of `System.Text.Json`. I've confirmed that Preview7SDK+Preview8Package works.
