### ISSUE TITLE
[5.0.100-rc.2.20464.10] Single File Publish issue on PixiEditorDotNetCore3 App after retarget .NET5

### ISSUE THREAD

**Issue by jiangzeng01** [dotnet/runtime#42305] opened 2020-09-16 08:09 UTC
**Application Name:** PixiEditorDotNetCore3
**OS:** Windows 10 RS5
**CPU:** X64
.NET Build Number: 5.0.100-rc.2.20464.10
**App Location:** \\appcompatsrv\Appcompat\DotNetCore\AppSource\SingleFileP0AppsTarget5\Apps\PixiEditorDotNetCore3
**App Source:** \\appcompatsrv\Appcompat\DotNetCore\AppSource\SingleFileP0AppsTarget5\AppSources\PixiEditorDotNetCore3
**DevDiv bug:** https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1214886

**Repro steps:**
Retarget .NET 5
Single File exe was created by
dotnet publish -r win-x64 -p:PublishSingleFile=true --self-contained true
using 5.0.100-rc.2.20464.10 SDK

Copy '\\appcompatsrv\Appcompat\DotNetCore\AppSource\SingleFileP0AppsTarget5\Apps\PixiEditorDotNetCore3' to local machine.
Double-click on PixiEditor.exe

**Expected Result:**
Open PixiEditor successful.

**Actual Result:**
The PixiEditor cannot be launched successful.

**Findings:**
The Self-contained and Framework-Dependency app can be launched. Only the Single file unable to launch.

**Exception from Event View :**
```
Application: PixiEditor.exe
CoreCLR Version: 5.0.20.46205
.NET Version: 5.0.0-rc.2.20462.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Windows.Markup.XamlParseException: Provide value on 'System.Windows.Markup.StaticExtension' threw an exception.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'Xceed.Wpf.Toolkit.Zoombox.ZoomboxCursors' threw an exception.
 ---> System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   at System.Reflection.RuntimeModule.GetFullyQualifiedName()
   at System.Reflection.RuntimeModule.get_Name()
   at Xceed.Wpf.Toolkit.Core.Utilities.ResourceHelper.LoadResourceStream(Assembly assembly, String resId)
   at Xceed.Wpf.Toolkit.Zoombox.ZoomboxCursors..cctor()
   --- End of inner exception stack trace ---
   at Xceed.Wpf.Toolkit.Zoombox.ZoomboxCursors.get_Zoom()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Windows.Markup.StaticExtension.GetFieldOrPropertyValue(Type type, String name, Object& value)
   at System.Windows.Markup.StaticExtension.ProvideValue(IServiceProvider serviceProvider)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at PixiEditor.App.Main()
```

cc @dotnet-actwx-bot

**Comment by agocke** [comment] 2020-09-16 21:18
@jiangzeng01 Module.FullyQualifiedName when compiled as single-file in .NET 5 will return either `<Unknown>` or throw, depending on your platform.

You can return to the behavior from .NET Core 3.1 by setting the property `IncludeAllContentForSelfExtract` to true, or change your app to no longer use `Module.FullyQualifiedName`.

**Comment by jiangzeng01** [comment] 2020-09-17 09:16
@agocke Thanks Andy for your update!

**Comment by jiangzeng01** [comment] 2020-09-24 09:19
> @jiangzeng01 Module.FullyQualifiedName when compiled as single-file in .NET 5 will return either `<Unknown>` or throw, depending on your platform.
> 
> You can return to the behavior from .NET Core 3.1 by setting the property `IncludeAllContentForSelfExtract` to true, or change your app to no longer use `Module.FullyQualifiedName`.

@agocke We tried to added the following code to project file, but the same issue still happens after retarget 5.0 & Single-File.
```
<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
```
Is there any other change we need to do?

**Comment by agocke** [comment] 2020-09-25 22:48
In testing this ourselves we found the fall back functionality is broken. We're working on a change now that hopefully fixes the issue.

**Comment by jiangzeng01** [comment] 2020-09-27 02:42
> In testing this ourselves we found the fall back functionality is broken. We're working on a change now that hopefully fixes the issue.

@agocke Thanks for update!

**Comment by Junjun-zhao** [comment] 2021-05-18 02:37
@agocke Is there any update for this issue?

**Comment by agocke** [comment] 2021-05-18 03:23
@Junjun-zhao This should be fixed in the latest patch updates to 5.0. What version are you still seeing this in?

**Comment by agocke** [comment] 2021-05-18 04:17
Duplicate of https://github.com/dotnet/runtime/issues/40103

**Closed by agocke** 2021-05-18 04:17 UTC
Labels: area-Single-File, customer assistance

**Comment by Junjun-zhao** [comment] 2021-05-18 06:53
@agocke  Thanks for your update.  We have verified it on the latest patch build dotnet-sdk-5.0.204-win-x64, this issue has been fixed.
