### ISSUE TITLE
[mono][tests] CustomGeneratedAttributes test fails on linux-bionic

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#93723] opened 2023-10-19 11:58 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=443717&view=logs&j=f29299c2-76db-5d02-ce4e-182614f08c53&t=432a9214-fb3e-532e-a18b-a74d735bc83e
Build error leg or test failing: linux_bionic-x64 Release AllSubsets_Mono

```
info: An error occurred running Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.sh
dbug: Exit code: 1
      Std out:
        Discovering: Microsoft.Extensions.Options.SourceGeneration.Unit.Tests (method display = ClassAndMethod, method display options = None)
        Discovered:  Microsoft.Extensions.Options.SourceGeneration.Unit.Tests (found 56 test cases)
        Starting:    Microsoft.Extensions.Options.SourceGeneration.Unit.Tests (parallel test collections = on, max threads = 8)
            Assert.Equal() Failure: Collections differ
                                                                                             ↓ (pos 1)
            Expected: string[]     ["P0: The field OptionsUsingGeneratedAttributes.P0 m"···, "P11: The field OptionsUsingGeneratedAttributes.P11"···, "P12: The field OptionsUsingGeneratedAttributes.P12"···, "P13: The field OptionsUsingGeneratedAttributes.P13"···, "P14: The field OptionsUsingGeneratedAttributes.P14"···, ···]
            Actual:   List<string> ["P0: The field OptionsUsingGeneratedAttributes.P0 m"···, "P11: The field OptionsUsingGeneratedAttributes.P11"···, "P12: The field OptionsUsingGeneratedAttributes.P12"···, "P13: The field OptionsUsingGeneratedAttributes.P13"···, "P14: The field OptionsUsingGeneratedAttributes.P14"···, ···]
                                                                                             ↑ (pos 1)
            Stack Trace:
              /_/src/libraries/Microsoft.Extensions.Options/tests/SourceGeneration.Unit.Tests/OptionsRuntimeTests.cs(361,0): at Microsoft.Gen.OptionsValidation.Unit.Test.OptionsRuntimeTests.TestCustomGeneratedAttributes()
              /_/src/mono/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.Mono.cs(22,0): at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
              /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(57,0): at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
        Finished:    Microsoft.Extensions.Options.SourceGeneration.Unit.Tests
      === TEST EXECUTION SUMMARY ===
         Microsoft.Extensions.Options.SourceGeneration.Unit.Tests  Total: 67, Errors: 0, Failed: 1, Skipped: 0, Time: 45.770s
      
      
      Std err:
          Microsoft.Gen.OptionsValidation.Unit.Test.OptionsRuntimeTests.TestCustomGeneratedAttributes [FAIL]
```

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Microsoft.Gen.OptionsValidation.Unit.Test.OptionsRuntimeTests.TestCustomGeneratedAttributes [FAIL]",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[444074](https://dev.azure.com/dnceng-public/public/_build/results?buildId=444074)|dotnet/runtime|[Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=444074&view=ms.vss-test-web.build-test-results-tab&runId=9923948&resultId=182705)|dotnet/runtime#93594|
|[443974](https://dev.azure.com/dnceng-public/public/_build/results?buildId=443974)|dotnet/runtime|[Microsoft.Gen.OptionsValidation.Unit.Test.OptionsRuntimeTests.TestCustomGeneratedAttributes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=443974&view=ms.vss-test-web.build-test-results-tab&runId=9922272&resultId=154008)|dotnet/runtime#93724|
|[443717](https://dev.azure.com/dnceng-public/public/_build/results?buildId=443717)|dotnet/runtime|[Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=443717&view=ms.vss-test-web.build-test-results-tab&runId=9914604&resultId=181208)||
|[443533](https://dev.azure.com/dnceng-public/public/_build/results?buildId=443533)|dotnet/runtime|[Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=443533&view=ms.vss-test-web.build-test-results-tab&runId=9905434&resultId=182520)||
|[443348](https://dev.azure.com/dnceng-public/public/_build/results?buildId=443348)|dotnet/runtime|[Microsoft.Gen.OptionsValidation.Unit.Test.OptionsRuntimeTests.TestCustomGeneratedAttributes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=443348&view=ms.vss-test-web.build-test-results-tab&runId=9900426&resultId=155154)||
|[443125](https://dev.azure.com/dnceng-public/public/_build/results?buildId=443125)|dotnet/runtime|[Microsoft.Extensions.Options.SourceGeneration.Unit.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=443125&view=ms.vss-test-web.build-test-results-tab&runId=9890066&resultId=182705)||
|[442968](https://dev.azure.com/dnceng-public/public/_build/results?buildId=442968)|dotnet/runtime|[Microsoft.Gen.OptionsValidation.Unit.Test.OptionsRuntimeTests.TestCustomGeneratedAttributes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=442968&view=ms.vss-test-web.build-test-results-tab&runId=9886894&resultId=115613)||
|[442747](https://dev.azure.com/dnceng-public/public/_build/results?buildId=442747)|dotnet/runtime|[Microsoft.Gen.OptionsValidation.Unit.Test.OptionsRuntimeTests.TestCustomGeneratedAttributes](https://dev.azure.com/dnceng-public/public/_build/results?buildId=442747&view=ms.vss-test-web.build-test-results-tab&runId=9877094&resultId=140630)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|7|8|8|

**Comment by akoeplinger** [comment] 2023-10-19 17:45
this is a duplicate of https://github.com/dotnet/runtime/issues/93592

**Closed by akoeplinger** 2023-10-19 17:45 UTC
Labels: os-linux, area-Codegen-meta-mono, Known Build Error
