### ISSUE TITLE
NullReferenceException in GetHttp11ConnectionAsync

### ISSUE THREAD

**Issue by whoaskedfrfr** [dotnet/runtime#90317] opened 2023-08-10 14:08 UTC
### Description

Our app under circumstances which I don't fully understand can throw a `NullReferenceException` on `SendAsync`

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
```

I tried looking into `GetHttp11ConnectionAsync` but it seems to have been removed from modern runtime versions. Is there a known use-case that can trigger this?

### Reproduction Steps

N/A - it happens sporadically

### Expected behavior

Do not throw `NullReferenceException`

### Actual behavior

Throws exception

### Configuration

.NET 6 running on Windows

**Comment by MihaZupan** [comment] 2023-08-10 14:16
You likely hit https://github.com/dotnet/runtime/issues/77434, which was fixed in .NET 8.0

**Comment by karelz** [comment] 2023-08-14 16:35
Duplicate of #77434

**Closed by karelz** 2023-08-14 16:35 UTC
Labels: area-System.Net.Http, untriaged
