### ISSUE TITLE
An error occurred when linking a static library ".lib" compiled using NativeAOT with a C++ project.

### ISSUE THREAD

**Issue by dadavadd** [dotnet/runtime#96298] opened 2023-12-24 19:31 UTC
Compiled NativeAOT libraries:

![image](https://github.com/dotnet/runtime/assets/111659964/23ec6054-a1a9-4482-a2e0-cf9100bcb21e)

The C# method before compiling to Native AOT:

![image](https://github.com/dotnet/runtime/assets/111659964/5db88456-1d85-4e60-b1a1-6b8499a0f83a)

Errors when linking the ".lib" file to my CPP project:

![image](https://github.com/dotnet/runtime/assets/111659964/2cbc0277-ec88-4b65-a664-ed0c69ffa8b9)

**Comment by jkotas** [comment] 2023-12-24 19:56
https://github.com/dotnet/samples/tree/main/core/nativeaot/NativeLibrary#building-static-libraries

Static linking requires additional runtime libraries to be linked as well. You can find the list of all required libraries by publishing the project as shared library (/p:NativeLib=Shared) with detailed verbosity (-v d), and looking at the output generated by the LinkNative target. 

We have https://github.com/dotnet/runtime/issues/70277 opened on improving this experience.

Duplicate of #70277 .

**Closed by jkotas** 2023-12-24 19:56 UTC
Labels: untriaged, area-NativeAOT-coreclr

**Comment by dadavadd** [comment] 2023-12-24 23:10
> https://github.com/dotnet/samples/tree/main/core/nativeaot/NativeLibrary#building-static-libraries
> 
> Static linking requires additional runtime libraries to be linked as well. You can find the list of all required libraries by publishing the project as shared library (/p:NativeLib=Shared) with detailed verbosity (-v d), and looking at the output generated by the LinkNative target.
> 
> We have #70277 opened on improving this experience.
> 
> Duplicate of #70277 .

![image](https://github.com/dotnet/runtime/assets/111659964/11c13ecc-a9e6-408f-bada-0c3e9ee1d946)


I get the error: LNK1241 Cooler-Native.lib resource file(Cooler-Native.obj) already specified.

Here are all the dependencies:

![image](https://github.com/dotnet/runtime/assets/111659964/d487259a-eae4-4b12-ab2f-559f9b5d38dc)

**Comment by jkotas** [comment] 2023-12-25 03:03
> error: LNK1241 Cooler-Native.lib resource file(Cooler-Native.obj) already specified.

This is known issue in .NET 8 - https://github.com/dotnet/runtime/issues/95100#issuecomment-1822130573 has workaround.

**Comment by dadavadd** [comment] 2023-12-25 09:40
> > error: LNK1241 Cooler-Native.lib resource file(Cooler-Native.obj) already specified.
> 
> This is known issue in .NET 8 - [#95100 (comment)](https://github.com/dotnet/runtime/issues/95100#issuecomment-1822130573) has workaround.

Everything works. Thank you. But there was another problem. When adding #include iostream, compilation errors appear. Without using this "#include", compilation completes without errors.
![image](https://github.com/dotnet/runtime/assets/111659964/99d2c576-5be6-496b-bb4d-0f6f893b2547)


Before applying #include iostream:
![image](https://github.com/dotnet/runtime/assets/111659964/c2a1e03d-ab5c-475d-b62c-08aef1dcb7dd)

Before applying #include iostream:
![image](https://github.com/dotnet/runtime/assets/111659964/116f747c-b68c-4237-8352-44f5f7a09c23)

**Comment by dadavadd** [comment] 2023-12-25 09:48
Sorry. I have solved the problem. I set the "Multithreaded /MT" setting in "code generation" and added "#pragma comment(lib, "libcmt.lib")".
