### ISSUE TITLE
nativeAOT whether to support winform or wpf programs?

### ISSUE THREAD

**Issue by fenginsc** [dotnet/runtime#79166] opened 2022-12-02 18:44 UTC
If it's not currently supported, is it possible that it will be supported in the future? Or will MAUI's nativeAOT be supported in the future?

**Comment by agocke** [comment] 2022-12-02 19:01
Only console apps are supported in .NET 7. You'll have to go to individual repos to see their status and roadmaps. WinForms in particular has been adding a lot of trimming and ComWrappers improvements -- those should make it much more likely that you could AOT a WinForms app. See https://github.com/dotnet/winforms/issues/5163 for more info.

For WPF, there has not been as much progress. WPF uses a lot more reflection, so it's a much bigger task https://github.com/dotnet/wpf/issues/3811

**Comment by kant2002** [comment] 2022-12-03 03:15
If you will consider community supported solution, you may take a look at my library https://github.com/kant2002/winformscominterop#getting-started which allow you to run your WinForms app even now. There some limitations regarding localization/ResX files support, but that's more of NativeAOT solution. WinForms working on improving support for NativeAOT and [some work](https://devblogs.microsoft.com/dotnet/winforms-enhancements-in-dotnet-7/#comwrappers-and-native-aot) already in .NET 7. I would say WinForms apps can be AOT-ed right now.

Regarding WPF that's still doable, but require you to take controlled risks. There [experimental fork](https://github.com/dotnet/wpf/issues/5305#issuecomment-1148121102) from which you can build (really trivial) WPF and use that version for applying NativeAOT for your app. If somebody interested enough to try that variant on their small app, let me know. I can try improving that work.

**Comment by MichalPetryka** [comment] 2022-12-03 14:20
> If you will consider community supported solution

And in such cases you might want to consider community UI frameworks with official NativeAOT support like [Avalonia](https://github.com/AvaloniaUI/Avalonia) instead.

**Comment by jkotas** [comment] 2022-12-03 22:05
Duplicate of https://github.com/dotnet/winforms/issues/5163 and https://github.com/dotnet/wpf/issues/3811

**Closed by jkotas** 2022-12-03 22:05 UTC
Labels: untriaged, area-NativeAOT-coreclr
