### ISSUE TITLE
PerfLabTests.StackWalk.Walk has regressed on arm64

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#67971] opened 2022-04-13 17:38 UTC
`PerfLabTests.StackWalk.Walk` has regressed on arm64. By +- 20% on Linux and +- 50% on Windows.

[Reporting System](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_arm64_ubuntu%2018.04%2fPerfLabTests.StackWalk.Walk.html)

![image](https://user-images.githubusercontent.com/6011991/163238117-68f1cd6d-c69e-4d89-9e64-c84482693a37.png)

Moving average makes it easier to spot the moment it has regressed:

![image](https://user-images.githubusercontent.com/6011991/163238239-97126c9c-adf8-43fb-8fb9-d8aedc7961ee.png)

Looking at the [diff](https://github.com/dotnet/runtime/compare/2575ce5f513c8f5cd37f935ba70b87cbd787c8df...4fc085622a582dc26a9811f210c8cb2c5223427b) it seems that it's #64688 (cc @mangod9)

Repro:

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_monthly.py net7.0-preview2 net7.0-preview3 --filter PerfLabTests.StackWalk.Walk --architecture arm64
```

<details>

## PerfLabTests.StackWalk.Walk

| Result | Ratio | Operating System      | Bit   | Processor Name                                  |
| ------ | -----:| --------------------- | ----- | ----------------------------------------------- |
| Slower |  0.80 | alpine 3.12           | Arm64 | Unknown processor                               |
| Same   |  0.81 | debian 11             | Arm64 | Unknown processor                               |
| Slower |  0.82 | ubuntu 18.04          | Arm64 | Unknown processor                               |
| Slower |  0.51 | Windows 10            | Arm64 | Microsoft SQ1 3.0 GHz                           |
| Slower |  0.53 | Windows 11            | Arm64 | Microsoft SQ1 3.0 GHz                           |
| Slower |  0.51 | Windows 11            | Arm64 | Unknown processor                               |
| Faster |  2.27 | macOS Monterey 12.3   | Arm64 | Apple M1 Max                                    |
| Same   |  0.85 | Windows 10            | X64   | Intel Xeon Platinum 8272CL CPU 2.60GHz          |
| Same   |  0.92 | Windows 10            | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz               |
| Same   |  0.94 | Windows 11            | X64   | AMD Ryzen Threadripper PRO 3945WX 12-Cores      |
| Slower |  0.78 | Windows 11            | X64   | AMD Ryzen 9 5900X                               |
| Slower |  0.73 | Windows 11            | X64   | Intel Core i5-4300U CPU 1.90GHz (Haswell)       |
| Same   |  0.71 | Windows 11            | X64   | Unknown processor                               |
| Slower |  0.79 | Windows 11            | X64   | Intel Core i7-8700 CPU 3.20GHz (Coffee Lake)    |
| Same   |  0.86 | Windows 11            | X64   | Intel Core i9-9900T CPU 2.10GHz                 |
| Same   |  0.76 | alpine 3.13           | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      |
| Same   |  0.95 | centos 7              | X64   | Intel Xeon CPU E5530 2.40GHz                    |
| Same   |  1.14 | debian 11             | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      |
| Same   |  0.78 | opensuse-leap 15.3    | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      |
| Slower |  0.79 | pop 20.04             | X64   | Intel Core i7-6600U CPU 2.60GHz (Skylake)       |
| Same   |  0.96 | ubuntu 18.04          | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz               |
| Same   |  0.91 | ubuntu 18.04          | X64   | Intel Core i7-2720QM CPU 2.20GHz (Sandy Bridge) |
| Same   |  0.89 | ubuntu 20.04          | X64   | Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R)   |
| Same   |  0.97 | Windows 10            | Arm   | Microsoft SQ1 3.0 GHz                           |
| Same   |  0.87 | ubuntu 18.04          | Arm   | ARMv7 Processor rev 3 (v7l)                     |
| Same   |  0.99 | Windows 10            | X86   | Intel Xeon CPU E5-1650 v4 3.60GHz               |
| Same   |  0.97 | Windows 11            | X86   | AMD Ryzen Threadripper PRO 3945WX 12-Cores      |
| Same   |  1.03 | Windows 11            | X86   | Intel Core i7-10510U CPU 1.80GHz                |
| Same   |  1.00 | Windows 7 SP1         | X86   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      |
| Same   |  1.03 | macOS Monterey 12.2.1 | X64   | Intel Core i7-5557U CPU 3.10GHz (Broadwell)     |
| Same   |  0.99 | macOS Monterey 12.3.1 | X64   | Intel Core i7-4870HQ CPU 2.50GHz (Haswell)      |

</details>

**Comment by mrsharm** [comment] 2022-07-23 18:39
Seems to be another case where there was a regression but was followed by an improvement that resulted in the microbenchmark getting to the same level as before. Closing this - please reopen if you feel that this assessment is incorrect.

![image](https://user-images.githubusercontent.com/68247673/180618611-67c0fab7-b098-4bff-9019-ad5004d8818c.png)

**Closed by mrsharm** 2022-07-23 18:39 UTC
Labels: arch-arm64, tenet-performance, area-GC-coreclr
