### ISSUE TITLE
Package Native AOT C++ sources for separate compilation on customer machines

### ISSUE THREAD

**Issue by agocke** [dotnet/runtime#102586] opened 2024-05-22 22:49 UTC
In some cases, users might want to compile for platforms that .NET doesn't support. Providing the sources (and CMake build files) for external compilation would allow for broader platform builds without increased cost on the runtime side.

**Comment by jkoritzinsky** [comment] 2024-05-22 22:55
For this scenario, we should produce simple and straightforward CMake files that have the minimal information required to define the CMake targets necessary to build the libraries. Right now we have a decent amount of logic that's shared with the rest of the runtime repo (functions, shared definitions), and I don't think we want to ship our eng/native directory.

**Comment by MichalStrehovsky** [comment] 2024-05-23 07:51
Is this a duplicate of #83611?

I've looked at this in the past, and yeah, the shared CMake files don't make it easy to disconnect from our engineering system. But if we don't use the same files that we use to build the product, it's super easy to forget switches/ifdefs and end up with a different runtime, that could be different in very subtle ways. It also doesn't help that CoreLib relies on files we generate as part of native build and who knows if they could be different.

**Comment by jkotas** [comment] 2024-05-23 11:32
Yes, this is duplicate of https://github.com/dotnet/runtime/issues/83611

**Closed** 2024-05-23 11:33 UTC
Labels: area-NativeAOT-coreclr
