### ISSUE TITLE
.RemoveAt(Index)

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#48415] opened 2021-02-17 19:38 UTC
## Background and Motivation
Sometimes you want to remove items based on their position from the end.

## Proposed API
```MyList.RemoveAt(^1)```

## Usage Examples
```MyList.RemoveAt(^1)```

## Alternative Designs
```MyList.RemoveAt(MyList.Count - 1)```

## Risks
None.

**Comment by eiriktsarpalis** [comment] 2021-02-18 12:02
Duplicate of https://github.com/dotnet/runtime/issues/321. Feel free to continue the conversation in the other issue.

**Closed by eiriktsarpalis** 2021-02-18 12:02 UTC
Labels: api-suggestion, area-System.Collections, untriaged
