### ISSUE TITLE
Blazor WebAssembly .net 5 TimeZoneInfo.GetSystemTimeZones() not returning full list

### ISSUE THREAD

**Issue by nssidhu** [dotnet/runtime#45195] opened 2020-11-25 04:44 UTC
I am using Blazor WebAssembly .net 5.
timeZones = TimeZoneInfo.GetSystemTimeZones();
return 14 zone only
How do i get the full list ?

**Comment by mkArtakMSFT** [comment] 2020-11-25 07:32
@lewing  FYI

**Comment by kjpou1** [comment] 2020-11-25 12:20
This looks to be a duplicate of https://github.com/dotnet/runtime/issues/44840.  This is being tracked there.

**Closed by kjpou1** 2020-11-25 12:20 UTC
Labels: arch-wasm, area-System.Globalization
