### ISSUE TITLE
Test failure GC\\API\\GC\\GetTotalPauseDuration\\GetTotalPauseDuration.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#75504] opened 2022-09-13 02:11 UTC
Run: [runtime-coreclr ilasm 20220910.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=11691&view=ms.vss-test-web.build-test-results-tab&runId=233458&resultId=109738&paneView=debug)

Failed test:
```
coreclr windows arm64 Checked ilasmroundtrip @ Windows.10.Arm64v8.Open

- GC\\API\\GC\\GetTotalPauseDuration\\GetTotalPauseDuration.cmd
```
**Error message:**
```
Return code:      1
Raw output file:      D:\h\w\AF7209E6\w\A715095B\uploads\Reports\GC.API\GC\GetTotalPauseDuration\GetTotalPauseDuration.output.txt
Raw output:
BEGIN EXECUTION
D:\h\w\AF7209E6\p\ildasm.exe /raweh /unicode /out=GetTotalPauseDuration.dasm.il GetTotalPauseDuration.dll
D:\h\w\AF7209E6\p\ilasm.exe /output=GetTotalPauseDuration.asm.dll  GetTotalPauseDuration.dasm.il

.NET IL Assembler.  Version 8.0.0-ci
Copyright (c) Microsoft Corporation.  All rights reserved.
Assembling 'GetTotalPauseDuration.dasm.il'  to EXE --> 'GetTotalPauseDuration.asm.dll'
Source file is UNICODE

Assembled method Test_Collect::Main
Assembled method Test_Collect::.ctor
Creating PE file

Emitting classes:
Class 1:Test_Collect

Emitting fields and methods:
Global
Class 1Methods: 2;

Emitting events and properties:
Global
Class 1
Writing PE file
Operation completed successfully
"D:\h\w\AF7209E6\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  GetTotalPauseDuration.asm.dll
END EXECUTION OF IL{D}ASM BINARY - FAILED 101 vs 100
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\AF7209E6\p
D:\h\w\AF7209E6\w\A715095B\e\GC\API\GC\GetTotalPauseDuration\GetTotalPauseDuration.cmd
Expected: True
Actual:   False


Stack trace
   at GC_API._GC_GetTotalPauseDuration_GetTotalPauseDuration_._GC_GetTotalPauseDuration_GetTotalPauseDuration_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by jakobbotsch** [comment] 2022-09-13 10:10
Duplicate of #74631

**Closed by jakobbotsch** 2022-09-13 10:10 UTC
Labels: arch-arm64, os-windows, area-GC-coreclr, untriaged, blocking-clean-ci-optional
