### ISSUE TITLE
FTP Upload Issue After Updating to  .Net Core 3.1

### ISSUE THREAD

**Issue by d-daniel-de-sousa** [dotnet/runtime#46950] opened 2020-12-30 18:20 UTC
# Issue Title

FTP Upload Issue After Updating to  .Net Core 3.1

# General

Version: .Net Core 3.1
OS: Windows
Solution Deployed: Web App Azure
Using Swagger.
Vnet

After Updating the Net Core Version from 2.1 to 3.1 the method to upload a file just stop working after deployed on Azure Web App.

If I Deploy it with a later version (2.1) it starts to work again.

## Exception/error
Exception thrown: 'System.Net.WebException' in System.Net.Requests.dll
Unable to connect to remote server

![image](https://user-images.githubusercontent.com/64017468/103372969-54aa1980-4ab2-11eb-8466-d4a087993f34.png)
![image](https://user-images.githubusercontent.com/64017468/103372982-6390cc00-4ab2-11eb-9e64-85233b1bf41d.png)

## Code
```c#
        public async Task<string> UploadFileFTP(string file)
        {
             FtpConfig ftpConfig = LightConfigurator.Config<FtpConfig>("FtpConfig");           

            FileInfo fileInfo = new FileInfo(file);
            Uri serverUri = new Uri(ftpConfig.Server + ":" + ftpConfig.Port + ftpConfig.Folder + fileInfo.Name);
            FtpWebRequest request = (FtpWebRequest)WebRequest.Create(serverUri);
            request.Method = WebRequestMethods.Ftp.UploadFile;
            request.Credentials = new NetworkCredential(ftpConfig.User, ftpConfig.Password);
            request.Proxy = null;
            request.UseBinary = true;
            request.ContentLength = fileInfo.Length;
            using (FileStream fs = fileInfo.OpenRead())
            {
                byte[] buffer = new byte[2048];
                int bytesSent = 0;
                int bytes = 0;
                using (Stream stream = request.GetRequestStream())
                {
                    while (bytesSent < fileInfo.Length)
                    {
                        bytes = fs.Read(buffer, 0, buffer.Length);
                        stream.Write(buffer, 0, bytes);
                        bytesSent += bytes;
                    }
                }
            }

            RegisterEvents.Register(ActionEnum.FPT_UPLOADING, "UploadFileFTP", $"Concluída a subida no FTP.");

            return "success";
        }
```

**Comment by wfurt** [comment] 2021-01-14 19:07
I think we switched to dual mode sockets in 3.x @scalablecory. This feels like dup of https://github.com/dotnet/runtime/issues/44686. 
I would suggest too try it with the WEBSITE_VNET_SUPPORT_DUAL_STACK_SOCKETS = 1.

**Comment by karelz** [comment] 2021-01-15 12:26
@wfurt the linked bug is regression between 3.1 and 5.0. This report is about regression between 2.1 and 3.1, so it won't be likely the same.

Are you able to minimize the repro (ideally HelloWorld style) such that we can try it ourselves as well?
Is your problem specific to Azure WebApps deploymnet? Or are you able to reproduce it also locally?

**Comment by wfurt** [comment] 2021-01-15 19:03
this is because HTTP switched to dual mode socket in 5.0. Same happened to TcpClient in 3.0 and that impacted FTP in 3.0 as well. Can you reproduce it outside of VNET @d-daniel-de-sousa?

**Comment by karelz** [comment] 2021-01-21 17:30
Triage: Seems to be Azure Web Apps problem, which should be shortly fixed. Closing.

**Closed by karelz** 2021-01-21 17:30 UTC
Labels: area-System.Net, needs more info, untriaged
