### ISSUE TITLE
Test failure readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#93643] opened 2023-10-18 02:02 UTC
**Failed in:** [runtime-coreclr jitstress 20231016.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=440585&view=ms.vss-test-web.build-test-results-tab&runId=9814828&resultId=107023&paneView=debug)

**Failed tests:**
```
coreclr linux arm64 Checked jitstress1 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
    - readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.cmd
```

**Error message:**
```
Process terminated. Assertion failed.
   at System.Text.StringBuilder.AssertInvariants()
   at System.Text.StringBuilder.ExpandByABlock(Int32 minBlockCharCount)
   at System.Text.StringBuilder.AppendWithExpansion(Char& value, Int32 valueCount)
   at System.Text.StringBuilder.Append(String value)
   at System.Text.StringBuilder.AppendLine(String value)
   at ProcessRunner.StandardOutputEventHandler(Object sender, DataReceivedEventArgs eventArgs) in /_/src/coreclr/tools/r2rtest/ProcessRunner.cs:line 286
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/AsyncStreamReader.cs:line 237
   at System.Diagnostics.AsyncStreamReader.ReadBufferAsync() in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/AsyncStreamReader.cs:line 123
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
   at System.IO.Pipes.PipeStream.ReadAsyncCore(Memory`1 destination, CancellationToken cancellationToken) in /_/src/libraries/System.IO.Pipes/src/System/IO/Pipes/PipeStream.Unix.cs:line 313
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.SignalCompletion()
   at System.Net.Sockets.SocketAsyncEventArgs.TransferCompletionCallbackCore(Int32 bytesTransferred, Memory`1 socketAddress, SocketFlags receivedFlags, SocketError socketError) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Unix.cs:line 102
   at System.Net.Sockets.SocketAsyncContext.BufferMemoryReceiveOperation.InvokeCallback(Boolean allowPooling) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 501
   at System.Net.Sockets.SocketAsyncEngine.System.Threading.IThreadPoolWorkItem.Execute() in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEngine.Unix.cs:line 242
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
apply_reg_state: ip and cfa unchanged; stopping here (ip=0xff955aecfe78)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0xff955aecfe78)
waitpid() returned successfully (wstatus 00000000) WEXITSTATUS 0 WTERMSIG 0

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/coreroot_determinism/output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true coreroot_determinism.dll ''
================================== Compiling with seed 1 ==================================
Locating output folder /root/helix/work/workitem/e/readytorun/coreroot_determinism/coreroot_determinism/seed1
Deleting 0 output folders
Successfully deleted 0 output folders in 95 msecs
Using dotnet: /root/helix/work/correlation/corerun
1 / 1 (0%, 0 failed): launching: /root/helix/work/correlation/corerun /root/helix/work/correlation/crossgen2/crossgen2.dll @/root/helix/work/workitem/e/readytorun/coreroot_determinism/coreroot_determ
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/xunit.assert/Asserts/BooleanAsserts.cs:line 132
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor1|0_2(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2023-10-17T05:43:01.947Z | runtime-coreclr jitstress | Checked-jitstress2_tiered | osx.1200.amd64.open | x64 | readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.cmd | Failed | {"System.JobAttempt":"1","architecture":"x64","DefinitionId":"109","System.StageAttempt":"1","System.JobName":"__default","System.PhaseName":"run_test_p1__osx_x64_checked","AzurePipelinesTestRunId":"9815420","BuildNumber":"20231016.1","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","BuildId":"440585","configuration":"Checked-jitstress2_tiered","System.StageName":"Build","DefinitionName":"runtime-coreclr jitstress","Project":"public","CollectionUri":"https://dev.azure.com/dnceng-public/","operatingSystem":"OSX.1200.Amd64.Open","System.PhaseAttempt":"1","Reason":"Schedule"} | Schedule
2023-10-17T05:42:59.118Z | runtime-coreclr jitstress | Checked-jitstress2 | osx.1200.amd64.open | x64 | readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.cmd | Failed | {"BuildId":"440585","DefinitionId":"109","System.JobAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20231016.1","configuration":"Checked-jitstress2","System.PhaseName":"run_test_p1__osx_x64_checked","AzurePipelinesTestRunId":"9815416","DefinitionName":"runtime-coreclr jitstress","architecture":"x64","operatingSystem":"OSX.1200.Amd64.Open","Project":"public","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","System.JobName":"__default","Reason":"Schedule","System.PhaseAttempt":"1","System.StageAttempt":"1","System.StageName":"Build"} | Schedule
2023-10-17T05:42:57.009Z | runtime-coreclr jitstress | Checked-jitstress1 | osx.1200.amd64.open | x64 | readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.cmd | Failed | {"System.JobAttempt":"1","BuildId":"440585","Reason":"Schedule","Project":"public","System.PhaseName":"run_test_p1__osx_x64_checked","architecture":"x64","AzurePipelinesTestRunId":"9815426","DefinitionName":"runtime-coreclr jitstress","System.PhaseAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionId":"109","operatingSystem":"OSX.1200.Amd64.Open","System.StageName":"Build","BuildNumber":"20231016.1","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","System.JobName":"__default","configuration":"Checked-jitstress1","System.StageAttempt":"1"} | Schedule
2023-10-17T05:42:54.492Z | runtime-coreclr jitstress | Checked-jitstress1_tiered | osx.1200.amd64.open | x64 | readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.cmd | Failed | {"BuildNumber":"20231016.1","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionId":"109","Reason":"Schedule","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","System.JobAttempt":"1","System.JobName":"__default","configuration":"Checked-jitstress1_tiered","System.StageName":"Build","operatingSystem":"OSX.1200.Amd64.Open","AzurePipelinesTestRunId":"9815424","System.PhaseAttempt":"1","Project":"public","System.StageAttempt":"1","architecture":"x64","System.PhaseName":"run_test_p1__osx_x64_checked","DefinitionName":"runtime-coreclr jitstress","BuildId":"440585"} | Schedule
2023-10-17T05:27:23.318Z | runtime-coreclr jitstress | Checked-jitstress2 | osx.1200.arm64.open | arm64 | readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.cmd | Failed | {"Reason":"Schedule","AzurePipelinesTestRunId":"9815054","operatingSystem":"OSX.1200.ARM64.Open","BuildNumber":"20231016.1","System.JobAttempt":"1","System.PhaseAttempt":"1","System.StageAttempt":"1","System.JobName":"__default","System.PhaseName":"run_test_p1__osx_arm64_checked","Project":"public","CollectionUri":"https://dev.azure.com/dnceng-public/","configuration":"Checked-jitstress2","BuildId":"440585","architecture":"arm64","System.StageName":"Build","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","DefinitionId":"109","DefinitionName":"runtime-coreclr jitstress"} | Schedule
<details>
<summary>More failures</summary>

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2023-10-17T05:27:20.347Z | runtime-coreclr jitstress | Checked-jitstress2_tiered | osx.1200.arm64.open | arm64 | readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.cmd | Failed | {"AzurePipelinesTestRunId":"9815032","System.PhaseName":"run_test_p1__osx_arm64_checked","operatingSystem":"OSX.1200.ARM64.Open","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","DefinitionId":"109","System.JobName":"__default","System.StageAttempt":"1","BuildId":"440585","Reason":"Schedule","configuration":"Checked-jitstress2_tiered","Project":"public","System.StageName":"Build","BuildNumber":"20231016.1","System.PhaseAttempt":"1","DefinitionName":"runtime-coreclr jitstress","System.JobAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","architecture":"arm64"} | Schedule
2023-10-17T05:27:19.182Z | runtime-coreclr jitstress | Checked-jitstress1_tiered | osx.1200.arm64.open | arm64 | readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.cmd | Failed | {"configuration":"Checked-jitstress1_tiered","System.PhaseAttempt":"1","Reason":"Schedule","Project":"public","DefinitionId":"109","DefinitionName":"runtime-coreclr jitstress","architecture":"arm64","System.JobName":"__default","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20231016.1","BuildId":"440585","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","AzurePipelinesTestRunId":"9815030","System.StageAttempt":"1","System.StageName":"Build","System.PhaseName":"run_test_p1__osx_arm64_checked","operatingSystem":"OSX.1200.ARM64.Open","System.JobAttempt":"1"} | Schedule
2023-10-17T05:27:18.206Z | runtime-coreclr jitstress | Checked-jitstress1 | osx.1200.arm64.open | arm64 | readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.cmd | Failed | {"Reason":"Schedule","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","System.StageName":"Build","configuration":"Checked-jitstress1","System.JobName":"__default","System.JobAttempt":"1","DefinitionId":"109","BuildId":"440585","System.PhaseAttempt":"1","System.StageAttempt":"1","System.PhaseName":"run_test_p1__osx_arm64_checked","Project":"public","DefinitionName":"runtime-coreclr jitstress","AzurePipelinesTestRunId":"9815034","operatingSystem":"OSX.1200.ARM64.Open","architecture":"arm64","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20231016.1"} | Schedule
2023-10-02T07:24:59.077Z | coreclr-release-outerloop-nightly | Release-no_tiered_compilation | ubuntu.1804.armarch.open | arm | readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.sh | Failed | {"AzurePipelinesTestRunId":"9328590","operatingSystem":"(Alpine.315.Arm32.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.15-helix-arm32v7","System.PhaseName":"run_test_p1_R2R_linux_musl_arm_release","DefinitionName":"coreclr-release-outerloop-nightly","Project":"public","System.StageAttempt":"1","BuildNumber":"20231001.1","architecture":"arm","System.JobName":"__default","configuration":"Release-no_tiered_compilation","System.PhaseAttempt":"1","Reason":"Schedule","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobId":"c8f31202-1062-5d6a-be4d-45312a30ae25","BuildId":"424226","DefinitionId":"135","System.JobAttempt":"1","System.StageName":"Build"} | Schedule
2023-10-02T07:24:59.077Z | coreclr-release-outerloop-nightly | Release-no_tiered_compilation | ubuntu.1804.armarch.open | arm | readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.sh | Failed | {"AzurePipelinesTestRunId":"9328590","operatingSystem":"(Alpine.315.Arm32.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.15-helix-arm32v7","System.PhaseName":"run_test_p1_R2R_linux_musl_arm_release","DefinitionName":"coreclr-release-outerloop-nightly","Project":"public","System.StageAttempt":"1","BuildNumber":"20231001.1","architecture":"arm","System.JobName":"__default","configuration":"Release-no_tiered_compilation","System.PhaseAttempt":"1","Reason":"Schedule","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobId":"c8f31202-1062-5d6a-be4d-45312a30ae25","BuildId":"424226","DefinitionId":"135","System.JobAttempt":"1","System.StageName":"Build"} | Schedule
2023-10-02T07:24:59.077Z | coreclr-release-outerloop-nightly | Release-no_tiered_compilation | ubuntu.1804.armarch.open | arm | readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.sh | Failed | {"AzurePipelinesTestRunId":"9328590","operatingSystem":"(Alpine.315.Arm32.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.15-helix-arm32v7","System.PhaseName":"run_test_p1_R2R_linux_musl_arm_release","DefinitionName":"coreclr-release-outerloop-nightly","Project":"public","System.StageAttempt":"1","BuildNumber":"20231001.1","architecture":"arm","System.JobName":"__default","configuration":"Release-no_tiered_compilation","System.PhaseAttempt":"1","Reason":"Schedule","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobId":"c8f31202-1062-5d6a-be4d-45312a30ae25","BuildId":"424226","DefinitionId":"135","System.JobAttempt":"1","System.StageName":"Build"} | Schedule
2023-10-02T07:24:59.077Z | coreclr-release-outerloop-nightly | Release-no_tiered_compilation | ubuntu.1804.armarch.open | arm | readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.sh | Failed | {"AzurePipelinesTestRunId":"9328590","operatingSystem":"(Alpine.315.Arm32.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.15-helix-arm32v7","System.PhaseName":"run_test_p1_R2R_linux_musl_arm_release","DefinitionName":"coreclr-release-outerloop-nightly","Project":"public","System.StageAttempt":"1","BuildNumber":"20231001.1","architecture":"arm","System.JobName":"__default","configuration":"Release-no_tiered_compilation","System.PhaseAttempt":"1","Reason":"Schedule","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobId":"c8f31202-1062-5d6a-be4d-45312a30ae25","BuildId":"424226","DefinitionId":"135","System.JobAttempt":"1","System.StageName":"Build"} | Schedule
2023-10-02T07:24:59.077Z | coreclr-release-outerloop-nightly | Release-no_tiered_compilation | ubuntu.1804.armarch.open | arm | readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.sh | Failed | {"AzurePipelinesTestRunId":"9328590","operatingSystem":"(Alpine.315.Arm32.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.15-helix-arm32v7","System.PhaseName":"run_test_p1_R2R_linux_musl_arm_release","DefinitionName":"coreclr-release-outerloop-nightly","Project":"public","System.StageAttempt":"1","BuildNumber":"20231001.1","architecture":"arm","System.JobName":"__default","configuration":"Release-no_tiered_compilation","System.PhaseAttempt":"1","Reason":"Schedule","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobId":"c8f31202-1062-5d6a-be4d-45312a30ae25","BuildId":"424226","DefinitionId":"135","System.JobAttempt":"1","System.StageName":"Build"} | Schedule
2023-10-02T07:24:59.077Z | coreclr-release-outerloop-nightly | Release-no_tiered_compilation | ubuntu.1804.armarch.open | arm | readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.sh | Failed | {"AzurePipelinesTestRunId":"9328590","operatingSystem":"(Alpine.315.Arm32.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.15-helix-arm32v7","System.PhaseName":"run_test_p1_R2R_linux_musl_arm_release","DefinitionName":"coreclr-release-outerloop-nightly","Project":"public","System.StageAttempt":"1","BuildNumber":"20231001.1","architecture":"arm","System.JobName":"__default","configuration":"Release-no_tiered_compilation","System.PhaseAttempt":"1","Reason":"Schedule","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobId":"c8f31202-1062-5d6a-be4d-45312a30ae25","BuildId":"424226","DefinitionId":"135","System.JobAttempt":"1","System.StageName":"Build"} | Schedule
2023-10-02T07:24:59.077Z | coreclr-release-outerloop-nightly | Release-no_tiered_compilation | ubuntu.1804.armarch.open | arm | readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.sh | Failed | {"AzurePipelinesTestRunId":"9328590","operatingSystem":"(Alpine.315.Arm32.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.15-helix-arm32v7","System.PhaseName":"run_test_p1_R2R_linux_musl_arm_release","DefinitionName":"coreclr-release-outerloop-nightly","Project":"public","System.StageAttempt":"1","BuildNumber":"20231001.1","architecture":"arm","System.JobName":"__default","configuration":"Release-no_tiered_compilation","System.PhaseAttempt":"1","Reason":"Schedule","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobId":"c8f31202-1062-5d6a-be4d-45312a30ae25","BuildId":"424226","DefinitionId":"135","System.JobAttempt":"1","System.StageName":"Build"} | Schedule
2023-10-02T07:24:59.077Z | coreclr-release-outerloop-nightly | Release-no_tiered_compilation | ubuntu.1804.armarch.open | arm | readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.sh | Failed | {"AzurePipelinesTestRunId":"9328590","operatingSystem":"(Alpine.315.Arm32.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.15-helix-arm32v7","System.PhaseName":"run_test_p1_R2R_linux_musl_arm_release","DefinitionName":"coreclr-release-outerloop-nightly","Project":"public","System.StageAttempt":"1","BuildNumber":"20231001.1","architecture":"arm","System.JobName":"__default","configuration":"Release-no_tiered_compilation","System.PhaseAttempt":"1","Reason":"Schedule","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobId":"c8f31202-1062-5d6a-be4d-45312a30ae25","BuildId":"424226","DefinitionId":"135","System.JobAttempt":"1","System.StageName":"Build"} | Schedule
2023-10-02T07:24:59.077Z | coreclr-release-outerloop-nightly | Release-no_tiered_compilation | ubuntu.1804.armarch.open | arm | readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.sh | Failed | {"AzurePipelinesTestRunId":"9328590","operatingSystem":"(Alpine.315.Arm32.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.15-helix-arm32v7","System.PhaseName":"run_test_p1_R2R_linux_musl_arm_release","DefinitionName":"coreclr-release-outerloop-nightly","Project":"public","System.StageAttempt":"1","BuildNumber":"20231001.1","architecture":"arm","System.JobName":"__default","configuration":"Release-no_tiered_compilation","System.PhaseAttempt":"1","Reason":"Schedule","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobId":"c8f31202-1062-5d6a-be4d-45312a30ae25","BuildId":"424226","DefinitionId":"135","System.JobAttempt":"1","System.StageName":"Build"} | Schedule
2023-10-01T19:51:38.315Z | runtime-coreclr jitstress-random | Checked-jitstress_random_1 | osx.1200.arm64.open | arm64 | readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.sh | Failed | {"configuration":"Checked-jitstress_random_1","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","Reason":"Schedule","System.StageName":"Build","DefinitionId":"159","DefinitionName":"runtime-coreclr jitstress-random","operatingSystem":"OSX.1200.ARM64.Open","AzurePipelinesTestRunId":"9324632","Project":"public","System.JobName":"__default","System.PhaseAttempt":"1","architecture":"arm64","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20231001.1","System.StageAttempt":"1","System.JobAttempt":"1","System.PhaseName":"run_test_p1__osx_arm64_checked","BuildId":"424103"} | Schedule
2023-10-01T19:51:38.315Z | runtime-coreclr jitstress-random | Checked-jitstress_random_1 | osx.1200.arm64.open | arm64 | readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.sh | Failed | {"configuration":"Checked-jitstress_random_1","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","Reason":"Schedule","System.StageName":"Build","DefinitionId":"159","DefinitionName":"runtime-coreclr jitstress-random","operatingSystem":"OSX.1200.ARM64.Open","AzurePipelinesTestRunId":"9324632","Project":"public","System.JobName":"__default","System.PhaseAttempt":"1","architecture":"arm64","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20231001.1","System.StageAttempt":"1","System.JobAttempt":"1","System.PhaseName":"run_test_p1__osx_arm64_checked","BuildId":"424103"} | Schedule
2023-10-01T19:51:38.315Z | runtime-coreclr jitstress-random | Checked-jitstress_random_1 | osx.1200.arm64.open | arm64 | readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.sh | Failed | {"configuration":"Checked-jitstress_random_1","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","Reason":"Schedule","System.StageName":"Build","DefinitionId":"159","DefinitionName":"runtime-coreclr jitstress-random","operatingSystem":"OSX.1200.ARM64.Open","AzurePipelinesTestRunId":"9324632","Project":"public","System.JobName":"__default","System.PhaseAttempt":"1","architecture":"arm64","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20231001.1","System.StageAttempt":"1","System.JobAttempt":"1","System.PhaseName":"run_test_p1__osx_arm64_checked","BuildId":"424103"} | Schedule
2023-10-01T19:51:38.315Z | runtime-coreclr jitstress-random | Checked-jitstress_random_1 | osx.1200.arm64.open | arm64 | readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.sh | Failed | {"configuration":"Checked-jitstress_random_1","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","Reason":"Schedule","System.StageName":"Build","DefinitionId":"159","DefinitionName":"runtime-coreclr jitstress-random","operatingSystem":"OSX.1200.ARM64.Open","AzurePipelinesTestRunId":"9324632","Project":"public","System.JobName":"__default","System.PhaseAttempt":"1","architecture":"arm64","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20231001.1","System.StageAttempt":"1","System.JobAttempt":"1","System.PhaseName":"run_test_p1__osx_arm64_checked","BuildId":"424103"} | Schedule
2023-10-01T19:51:38.315Z | runtime-coreclr jitstress-random | Checked-jitstress_random_1 | osx.1200.arm64.open | arm64 | readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.sh | Failed | {"configuration":"Checked-jitstress_random_1","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","Reason":"Schedule","System.StageName":"Build","DefinitionId":"159","DefinitionName":"runtime-coreclr jitstress-random","operatingSystem":"OSX.1200.ARM64.Open","AzurePipelinesTestRunId":"9324632","Project":"public","System.JobName":"__default","System.PhaseAttempt":"1","architecture":"arm64","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20231001.1","System.StageAttempt":"1","System.JobAttempt":"1","System.PhaseName":"run_test_p1__osx_arm64_checked","BuildId":"424103"} | Schedule
2023-10-01T19:51:38.315Z | runtime-coreclr jitstress-random | Checked-jitstress_random_1 | osx.1200.arm64.open | arm64 | readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.sh | Failed | {"configuration":"Checked-jitstress_random_1","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","Reason":"Schedule","System.StageName":"Build","DefinitionId":"159","DefinitionName":"runtime-coreclr jitstress-random","operatingSystem":"OSX.1200.ARM64.Open","AzurePipelinesTestRunId":"9324632","Project":"public","System.JobName":"__default","System.PhaseAttempt":"1","architecture":"arm64","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20231001.1","System.StageAttempt":"1","System.JobAttempt":"1","System.PhaseName":"run_test_p1__osx_arm64_checked","BuildId":"424103"} | Schedule

</details>

**Comment by jakobbotsch** [comment] 2023-10-18 08:25
Going to assume this is a duplicate of #93639 even though the message is different.

**Closed by jakobbotsch** 2023-10-18 08:25 UTC
Labels: arch-arm64, os-linux, JitStress, area-CodeGen-coreclr, untriaged
