### ISSUE TITLE
Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while server offers only version fallback

### ISSUE THREAD

**Issue by SLavaLL** [dotnet/runtime#56217] opened 2021-07-23 14:26 UTC
Hello,

Initially, the problem was that I could not connect the gRPC client application (.Net 5) to the gRPC server.
I asked questions in the grpc-dotnet project - [First link](https://github.com/grpc/grpc-dotnet/issues/1252)
[Second link](https://github.com/grpc/grpc-dotnet/issues/1321)
From there, I was directed here.

I have created three projects that are not related to gRPC.
Server 
[WebApplication1.zip](https://github.com/dotnet/runtime/files/6869253/WebApplication1.zip)

```c#
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.ConfigureKestrel(options =>
                    {
                        options.ConfigureEndpointDefaults(lo =>
                        {
                            lo.Protocols = HttpProtocols.Http2;
                            lo.UseHttps("testGrpc.pfx");
                        }
                        );
                    });
                    webBuilder.UseStartup<Startup>();
                });
    }

    public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapGet("/", async context =>
                {
                    await context.Response.WriteAsync("Hello World!");
                });
            });
        }
    }

```

Client.Net 5
[ConsoleApp11.zip](https://github.com/dotnet/runtime/files/6869254/ConsoleApp11.zip)

```c#
    class Program
    {
        static void Main(string[] args)
        {
            try
            {                
                var url = "https://webhost-virt-2:5001/";             

                var handler = new HttpClientHandler
                {
                    ServerCertificateCustomValidationCallback = (request, cert, chain, errors) => { return true; },
                    SslProtocols = SslProtocols.Tls12,
                    UseProxy = false                     
                };

                var client = new HttpClient(handler)
                {
                    DefaultRequestVersion = HttpVersion.Version20,
                    DefaultVersionPolicy = HttpVersionPolicy.RequestVersionOrHigher
                };                

                var resp = client.GetAsync(url).Result;

                var answer = resp.Content.ReadAsStringAsync().Result;
                Console.WriteLine(answer);
                Console.ReadKey();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                var iex = ex.InnerException;
                while (iex != null)
                {
                    Console.WriteLine("Inner:" + iex.Message);
                    iex = iex.InnerException;
                }
                Console.ReadKey();
            }
        }
    }
```

Client.Net Framework 4.8
[ConsoleApp13.zip](https://github.com/dotnet/runtime/files/6869255/ConsoleApp13.zip)

```c#
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                var url = "https://webhost-virt-2:5001";

                ServicePointManager.ServerCertificateValidationCallback = delegate (Object obj, X509Certificate certificate, X509Chain chain, SslPolicyErrors errors)
                {
                    return (true);
                };

                var handler = new WinHttpHandler();
                handler.ServerCertificateValidationCallback = delegate { return true; };

                var message = new HttpRequestMessage(HttpMethod.Get, url)
                {
                    Version = new Version(2, 0)
                };

                var client = new HttpClient(handler);
                var resp = client.SendAsync(message).Result;

                var answer = resp.Content.ReadAsStringAsync().Result;

                Console.WriteLine(answer);
                Console.ReadKey();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                var iex = ex.InnerException;
                while (iex != null)
                {
                    Console.WriteLine("Inner:" + iex.Message);
                    iex = iex.InnerException;
                }
                Console.ReadKey();
            }
        }
    }
```

When I start the client .Net 5 application on my computer (Windows 10), I get an error:

> Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while server offers only version fallback

On other computers with Windows 10 and Windows 2016 Server, everything works fine.

I decided that there are not enough Windows components to work over the HTTP/2 protocol, but, the client application .NetFramework 4.8 also works fine on my computer.

On the gprs-dotnet project page, I was prompted that there is no ALPN section in the Client Hello message (for .Net Framework there is such a section).
I attach the packages collected using Wireshark:
[Net5.zip](https://github.com/dotnet/runtime/files/6869371/Net5.zip)
[NetFramework48.zip](https://github.com/dotnet/runtime/files/6869373/NetFramework48.zip)

But, why there is no ALPN section, and whether this is really a problem, and what needs to be done to make the project work on .Net 5, unclear.

**Comment by karelz** [comment] 2021-07-27 19:44
Triage: Already present in 5.0. Pushing to 7.0.
How impactful is it for you?

**Comment by SLavaLL** [comment] 2021-07-27 20:50
> Triage: Already present in 5.0. Pushing to 7.0.
> How impactful is it for you?

If I understood correctly, I can't use gRPC with TLS on .Net 5, and this problem will be solved only by the 7th version?
This is upsetting, we will have to think about whether it is worth using this technology, or consider alternative options.

**Comment by karelz** [comment] 2021-07-27 21:17
@SLavaLL why cannot you use gRPC with .NET 5? Tons of people use it successfully?
What is unique on your scenario that it does not work?
Perhaps we just misunderstood your report ...

cc @JamesNK

**Comment by SLavaLL** [comment] 2021-07-27 21:51
> @SLavaLL why cannot you use gRPC with .NET 5? Tons of people use it successfully?
> What is unique on your scenario that it does not work?
> Perhaps we just misunderstood your report ...
> 
> cc @JamesNK

I have given the errors that I get when trying to establish a connection between the gRPC client and the server.
This problem is happening on my computer. Everything works fine on other computers.
I do not know why this is happening, and what needs to be done to fix it.
And, I can't launch a technology in production that causes problems that I don't know how to solve.
I thought that I was doing something wrong, or I needed to install something on my Windows, so I asked questions here.

**Comment by JamesNK** [comment] 2021-07-27 22:11
Something about the TLS ALPN negotiation is preventing the .NET gRPC client from connecting to the server. There is no logic specific to gRPC involved.

`HttpRequestMessage.Version` = 2 +
`HttpRequestMessage.VersionPolicy` = RequestVersionOrHigher

**Comment by wfurt** [comment] 2021-07-27 22:17
As @SLavaLL , ALPN is missing in the hello for some reason. 
As @JamesNK suggested, try to set it explicitly on the request as you do in the 4.8 case. 
That may give us some clues. (and possibly enable tracing for HttpClient)

**Comment by SLavaLL** [comment] 2021-07-27 23:18
> As @SLavaLL , ALPN is missing in the hello for some reason.
> As @JamesNK suggested, try to set it explicitly on the request as you do in the 4.8 case.
> That may give us some clues. (and possibly enable tracing for HttpClient)

I ran this code - nothing has changed.
```
                    var message = new HttpRequestMessage(HttpMethod.Get, url)
                    {
                        Version = new Version(2, 0),
                        VersionPolicy = HttpVersionPolicy.RequestVersionOrHigher
                    };
                    var resp = client.SendAsync(message).Result;
```
How can I trace HttpClient.
Above, I applied packets received using Wireshark.

**Comment by karelz** [comment] 2021-07-28 08:52
> This problem is happening on my computer. Everything works fine on other computers.

This is concerning. Debugging one machine problem which we cannot reproduce ourselves is super hard and time consuming.
Did you consider debugging the code side-by-side on working and failing machine to see where is the difference?

Typical suspects would be corrupted OS/.NET installation, or some weird configuration.
Here are some options you might want to try:
- .NET 6 latest Preview or .NET 5 self-contained app (compiled on another computer).
- Reinstall the failing machine to see if it starts working, or if it is related to HW setup.

**Comment by SLavaLL** [comment] 2021-07-28 11:45
> Did you consider debugging the code side-by-side on working and failing machine to see where is the difference?

Yes, I can debug the application on different computers, where the application is running, and where it gives an error.
 
> Typical suspects would be corrupted OS/.NET installation, or some weird configuration.
> Here are some options you might want to try:
> 
> * .NET 6 latest Preview or .NET 5 self-contained app (compiled on another computer).
> * Reinstall the failing machine to see if it starts working, or if it is related to HW setup.

An application built on another computer, in self-contained mode, gives the same error.

An application built for Visual Studio 2022, .Net 6 (Preview) returns an error:

> Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while unable to establish HTTP/2 connection.

Of course, I can reinstall Windows on my computer, but I'm worried that if I start distributing the application to customers, and they start getting the same errors, I'm unlikely to be able to ask them to reinstall Windows on their computers.

**Comment by karelz** [comment] 2021-07-28 12:30
> Yes, I can debug the application on different computers, where the application is running, and where it gives an error.

Great, that should tell us best what is different on the working and failing machine ...

> Of course, I can reinstall Windows on my computer, but I'm worried that if I start distributing the application to customers, and they start getting the same errors, I'm unlikely to be able to ask them to reinstall Windows on their computers.

I understand what you mean. However, try to look at it also from another point -- right now there is no evidence it is more than one machine problem (which may be corrupted installation, HW problems and other "magic"). As such, we will be happy to help and support you, but realistically it is not something we can prioritize on our side ourselves -- especially because we are unable to reproduce it and debug it ourselves.

Out of curiosity, does anything change when you drop the VersionPolicy? If you leave it just to 2.0?

**Comment by SLavaLL** [comment] 2021-07-28 14:00
> Out of curiosity, does anything change when you drop the VersionPolicy? If you leave it just to 2.0?

This code:
```
                    var message = new HttpRequestMessage(HttpMethod.Get, url)
                    {
                        Version = new Version(2, 0)                        
                    };
                    var resp = client.SendAsync(message).Result;
```

returns this error:

> The response ended prematurely

**Comment by SLavaLL** [comment] 2021-08-03 19:57
> Great, that should tell us best what is different on the working and failing machine ...

Interesting, I got to this point in the debugger (SslStream.ForceAuthenticationAsync):

![image](https://user-images.githubusercontent.com/15767627/128076181-07321f36-bb35-4534-8458-69f2151240a2.png)

The message in the debugger is quite correct (TLS 1.2 and ALPN section) - like this:

![image](https://user-images.githubusercontent.com/15767627/128076873-0c56de48-233d-48df-af3a-588f43a8c08b.png)

But, a completely different message is displayed in Wireshark (TLS 1.0 without ALPN)

![image](https://user-images.githubusercontent.com/15767627/128077139-c145d797-ccff-4267-ae67-01e747abb5e6.png)

On the computer where everything is working fine, the message in the debugger corresponds to the message in Wireshark.
Such a suspicion that someone intercepts the message and replaces it with another one.
I wonder who it could be besides the antivirus.
We have an antivirus installed on all the company's computers - there are no problems on other computers.

**Comment by wfurt** [comment] 2021-08-03 20:01
Can you check the response and see if the server certificate is _exactly_ the same e.g. key, hash and everything?

**Comment by SLavaLL** [comment] 2021-08-03 20:16
> Can you check the response and see if the server certificate is _exactly_ the same e.g. key, hash and everything?

When I turned on logging, I saw the following differences in the certificates.
On the left is the protocol where the application is running, on the right with an error.
For some reason, on the left, CN = TestGrpc is from the certificate, and on the right, CN = webhost-virt-2 is the host name on which the server application is running.

![image](https://user-images.githubusercontent.com/15767627/128080174-116b6375-f21c-4883-af19-ae152016ba2a.png)

**Comment by wfurt** [comment] 2021-08-03 21:11
That may be cause by differences in SNI e.g. server_name in the hello. The reason why I asked that IT or or somebody else can deploy transparent SSL proxy and that can change the handshake. Typically you would see that the certificate was re-signed by something trusted by your machine.

**Comment by SLavaLL** [comment] 2021-08-04 07:36
In safe mode with network support, everything works well

**Comment by SLavaLL** [comment] 2021-08-04 13:21
Thanks for the help. 
As it turned out, our security guards installed a DLP system to control information leakage.
Apparently, the system incorrectly intercepts and replaces packets...

**Comment by wfurt** [comment] 2021-08-04 16:18
ok. I know some of this is difficult to diagnose. Depending how they hook up, VPN or local container may help.
closing now as root cause was identified.

**Closed by wfurt** 2021-08-04 16:18 UTC
Labels: area-System.Net.Http, bug, needs more info
