### ISSUE TITLE
Internal CLR error when editing code while debugging step by step.

### ISSUE THREAD

**Issue by Kuinox** [dotnet/runtime#72689] opened 2022-07-22 17:53 UTC
### Description

If I edit code in a specific function while debugging stet by step, the process crash with a Internal CLR error.
I do not use Hot Reload, I simply edit the code, like adding a new line.

### Reproduction Steps

- In a CLI:
```
git clone https://github.com/signature-opensource/CK-MQTT/
cd CK-MQTT
git checkout ee9cd13c79b22e602d1b142240b4433a950c14f0
```

- Open the repository sln, then in `CK.MQTT.DefaultMQTTDemiServer\DynamicallyConfiguredChannelFactory.cs` add a breakpoint line 173.

- Start ConsoleApp1 project (this is a MQTT Server Test Console App, if you go further than the breakpoint without triggering the bug, the app will start to listen on port 1883)
- When the breakpoint is hit, add a new line on the next line (174 should be the new line)
- Press F10(Step Over).

### Expected behavior

Process crash don't crash, or VS displaying the prompt to undo change or stopping the process.

### Actual behavior

The process crash with the following message in the console: 
```
Fatal error. Internal CLR error. (0x80131506)
   at CK.MQTT.Server.DynamicallyConfiguredChannelFactory.CreateAsync(System.Threading.CancellationToken)
   at CK.MQTT.Server.MqttListenerBase+<AcceptLoopAsync>d__15.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at CK.MQTT.Server.MqttListenerBase.AcceptLoopAsync(System.Threading.CancellationToken)
   at CK.MQTT.Server.MqttListenerBase.StartListening()
   at CK.MQTT.Server.DefaultMQTTDemiServer.StartAsync(System.Threading.CancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host+<StartAsync>d__12.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.Extensions.Hosting.Internal.Host+<StartAsync>d__12, Microsoft.Extensions.Hosting, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<StartAsync>d__12 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.Extensions.Hosting.Internal.Host+<StartAsync>d__12, Microsoft.Extensions.Hosting, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<StartAsync>d__12 ByRef)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(System.Threading.CancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions+<RunAsync>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions+<RunAsync>d__4, Microsoft.Extensions.Hosting.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<RunAsync>d__4 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions+<RunAsync>d__4, Microsoft.Extensions.Hosting.Abstractions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]](<RunAsync>d__4 ByRef)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(Microsoft.Extensions.Hosting.IHost, System.Threading.CancellationToken)
   at ConsoleApp1.Program.Main(System.String[])
   at ConsoleApp1.Program.<Main>(System.String[])
```

### Regression?

Not tested any other version.

### Known Workarounds

Don't edit the file :D

### Configuration

Environement.Version => "6.0.7
Version 17.3.0 Preview 2.0

**Comment by Kuinox** [comment] 2022-07-22 19:41
I tested with the latest .NET 7 SDK and it now display 
![image](https://user-images.githubusercontent.com/18743295/180505107-3d0c523f-1d35-4aa5-9121-71d7666d0709.png)

**Comment by tommcdon** [comment] 2022-07-22 19:45
@Kuinox Is there any useful information in the Error List Window or the Output window?

**Comment by Kuinox** [comment] 2022-07-22 20:02
Mhhhh, sadly I can't reproduce anymore, the changes are applied without issues.  

I think my last test ran on a previous .NET 7 SDK preview because... VS cache ? (I'm speculating, I rebooted after the SDK has been installed and led to this).

**Comment by jakobbotsch** [comment] 2022-07-22 20:22
If this is fixed after using the latest preview from dotnet/installer then it is likely a duplicate of #70834. The source code in this case looks to be on a return instruction that is similarly going to use return buffer as in that example.

**Comment by Kuinox** [comment] 2022-07-22 20:33
Then I close this issue ?

**Comment by tommcdon** [comment] 2022-07-22 20:35
> Then I close this issue ?

Yes if we can confirm this is a duplicate.

**Comment by jakobbotsch** [comment] 2022-07-22 20:36
I can repro this on .NET 6 and .NET 7 preview 6, but if I replace bits with latest bits from main it no longer repros. So I think it's pretty safe to say this is the same problem as in #70834.

**Comment by jakobbotsch** [comment] 2022-07-22 20:37
It is a little curious that we had two reports of this issue so close to each other, but since it repros in .NET 6 that seems like a coincidence. I'll close this as a duplicate, thanks for the report.

**Closed by jakobbotsch** 2022-07-22 20:37 UTC
Labels: area-Diagnostics-coreclr

**Comment by tommcdon** [comment] 2022-07-22 20:40
Thank you @jakobbotsch!
