### ISSUE TITLE
System.IO.FileSystem.Net5Compat.Tests failed on Android  due to lowmemorykiller

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#55691] opened 2021-07-14 23:51 UTC
net6.0-Android-Release-x86-Mono_Release-Ubuntu.1804.Amd64.Android.Open

`65 E lowmemorykiller: Kill 'net.dot.System.IO.FileSystem.Net5Compat.Tests' (7383), uid 10115, oom_adj 0 to free 2107432kB`

Logs can be gotten from Work Item System.IO.FileSystem.Net5Compat.Tests in job 1db68265-e405-4d05-9dd7-cb05a69b84ff

in particular https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-46417-merge-1db68265e4054d059d/System.IO.FileSystem.Net5Compat.Tests/adb-logcat-net.dot.System.IO.FileSystem.Net5Compat.Tests-net.dot.MonoRunner.log?sv=2019-07-07&se=2021-08-03T20%3A09%3A04Z&sr=c&sp=rl&sig=NYCkCCBJSiwncQMds3ExUXcQiYOEFx3Ki%2BjTO5vv65I%3D

hit in https://github.com/dotnet/runtime/pull/46417

**Comment by danmoseley** [comment] 2021-07-15 15:35
@steveisok if there are other candidates for terminating perhaps we could use oom_score_adj to protect the test process (if that works on Android)? It can't make anything worse than terminating the test process?

If the test is simply using too much memory then I guess we need a dump to find out which test is the problem.

**Comment by danmoseley** [comment] 2021-07-15 15:37
I was looking at https://android.googlesource.com/kernel/common.git/+/d4fe84dd6eebc11774808f2eb094ed0826fa3c33/drivers/staging/android/lowmemorykiller.c#12

**Comment by adamsitnik** [comment] 2021-07-22 07:22
Is this the only test project that fails with OOM on Android? I am asking because we plan to remove it in .NET 7 (https://github.com/dotnet/runtime/issues/55196)

**Comment by steveisok** [comment] 2021-07-22 07:32
No, there are others and it's pretty random.  I don't think this test is necessarily the cause.

**Comment by steveisok** [comment] 2022-07-20 14:35
Closing as the suite is no longer in .NET 7 and I haven't seen lowmem errors in emulators for a while.

**Closed by steveisok** 2022-07-20 14:35 UTC
Labels: os-android, area-Infrastructure-mono
