### ISSUE TITLE
Test failure JIT\\HardwareIntrinsics\\X86\\Fma_Vector128\\Fma_r\\Fma_r.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#66926] opened 2022-03-21 03:18 UTC
Run: [runtime-coreclr r2r-extra 20220319.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1672469&view=ms.vss-test-web.build-test-results-tab&runId=45907284&resultId=100109&paneView=debug)

Failed test:
```
R2R windows x86 Checked jitstressregs0x10 @ Windows.10.Amd64.Open

- JIT\\HardwareIntrinsics\\X86\\Fma_Vector128\\Fma_r\\Fma_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Fma_Vector128\\Fma_ro\\Fma_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Fma_Vector256\\Fma_r\\Fma_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Fma_Vector256\\Fma_ro\\Fma_ro.cmd
- profiler\\unittest\\getappdomainstaticaddress\\getappdomainstaticaddress.cmd
- profiler\\unittest\\inlining\\inlining.cmd
- profiler\\unittest\\releaseondetach\\releaseondetach.cmd
- profiler\\unittest\\metadatagetdispenser\\metadatagetdispenser.cmd

R2R windows x64 Checked jitminopts @ Windows.10.Amd64.Open

- JIT\\HardwareIntrinsics\\X86\\Regression\\GitHub_21666\\GitHub_21666_r\\GitHub_21666_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Regression\\GitHub_17957\\GitHub_17957_ro\\GitHub_17957_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Regression\\GitHub_17435\\GitHub_17435\\GitHub_17435.cmd
- JIT\\HardwareIntrinsics\\X86\\Regression\\GitHub_23438\\GitHub_23438_ro\\GitHub_23438_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Regression\\GitHub_21899\\GitHub_21899_r\\GitHub_21899_r.cmd

R2R windows x86 Checked jitstressregs1 @ Windows.10.Amd64.Open

- JIT\\HardwareIntrinsics\\X86\\Bmi2.X64\\Bmi2.X64_ro\\Bmi2.X64_ro.cmd
```
**Error message:**
```
Could Not Find C:\h\w\B8780A30\w\AC34097D\e\JIT\HardwareIntrinsics\X86\Fma_Vector128\Fma_r\IL-CG2\composite-r2r.dll
Could Not Find C:\h\w\B8780A30\w\AC34097D\e\JIT\HardwareIntrinsics\X86\Fma_Vector128\Fma_r\Fma_r.dll.rsp
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'System.Diagnostics.Tracing, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The module was expected to contain an assembly manifest.
File name: 'System.Diagnostics.Tracing, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
at ILCompiler.Program.Run(String[] args)
at ILCompiler.Program.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\B8780A30\w\AC34097D\uploads\Reports\JIT.HardwareIntrinsics\X86\Fma_Vector128\Fma_r\Fma_r.output.txt
Raw output:
BEGIN EXECUTION
Fma_r.dll
TestLibrary.dll
2 file(s) copied.
Response file: C:\h\w\B8780A30\w\AC34097D\e\JIT\HardwareIntrinsics\X86\Fma_Vector128\Fma_r\Fma_r.dll.rsp
C:\h\w\B8780A30\w\AC34097D\e\JIT\HardwareIntrinsics\X86\Fma_Vector128\Fma_r\IL-CG2\Fma_r.dll
-o:C:\h\w\B8780A30\w\AC34097D\e\JIT\HardwareIntrinsics\X86\Fma_Vector128\Fma_r\Fma_r.dll
--targetarch:x86
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\B8780A30\p\System..dll
-r:C:\h\w\B8780A30\p\Microsoft..dll
-r:C:\h\w\B8780A30\p\mscorlib.dll
-r:C:\h\w\B8780A30\p\netstandard.dll
-O
" "dotnet" "C:\h\w\B8780A30\p\crossgen2\crossgen2.dll" @"C:\h\w\B8780A30\w\AC34097D\e\JIT\HardwareIntrinsics\X86\Fma_Vector128\Fma_r\Fma_r.dll.rsp"   -r:C:\h\w\B8780A30\w\AC34097D\e\JIT\HardwareIntrinsics\X86\Fma_Vector128\Fma_r\IL-CG2*.dll"
Crossgen2 failed with exitcode - -532462766
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\B8780A30\p
C:\h\w\B8780A30\w\AC34097D\e\JIT\HardwareIntrinsics\X86\Fma_Vector128\Fma_r\Fma_r.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_HardwareIntrinsics._X86_Fma_Vector128_Fma_r_Fma_r_._X86_Fma_Vector128_Fma_r_Fma_r_cmd()
```

**Comment by JulieLeeMSFT** [comment] 2022-03-21 19:17
cc @BruceForstall.

**Comment by BruceForstall** [comment] 2022-03-22 00:19
@trylek @mangod9 This looks like the same issue as https://github.com/dotnet/runtime/issues/66690

**Comment by trylek** [comment] 2022-03-22 00:27
For sure, while the issue has relatively low repro rate, less than 1% of Helix work items, it's obviously still ongoing. I have worked with Matt Galbraith and I am running instrumented lab runs that should upload the offending assemblies to Helix as dumps so that I can diff them to the payloads and see whether the PE images have been somehow malformed (as was my original speculation) or whether there's some bug in runtime assembly load logic.

**Comment by tannergooding** [comment] 2022-03-22 20:34
This is a dupe of https://github.com/dotnet/runtime/issues/65646

**Closed** 2022-04-04 20:20 UTC
Labels: arch-x86, os-windows, JitStress, arch-x64, area-crossgen2-coreclr
