### ISSUE TITLE
Half type Max/Min value is different from documentation

### ISSUE THREAD

**Issue by Gavin-Williams** [dotnet/runtime#82508] opened 2023-02-23 01:24 UTC
Documentation reads...
> The [Half](https://learn.microsoft.com/en-us/dotnet/api/system.half?view=net-7.0) value type represents a half-precision 16-bit number with values ranging from negative 65,504 to positive 65,504

But printing the types min/max values gives : -65500,65500

**Comment by tannergooding** [comment] 2023-02-23 02:36
This is effectively a duplicate of https://github.com/dotnet/runtime/issues/75204

The premise is that `ToString`, [since .NET Core 3.0](https://devblogs.microsoft.com/dotnet/floating-point-parsing-and-formatting-improvements-in-net-core-3-0/), returns the "shortest roundtrippable string".

"shortest" here is effectively defined as the least number of significant digits that will round to the exact represented value.

The exact represented value of `Half.MaxValue` is indeed `65504`, which in scientific notation is `6.5504 * 10^4` (or `6.5504E4` in exponential notation). However, this is not the shortest scientific notation that rounds to the value. Due to how binary floating-point numbers work, the shortest roundtrippable number is `6.55 * 10^4` (or `6.55E4` or `65500`).

The "G" format is supposed to pick the "more compact of fixed-point or scientific notation" and `65500` vs `6.55E4` are the same length. The existing behavior (which ends up better for integrals, but "worse" for `Half`) is that the fixed-point string `65500` is the preferred for "same length".

**Comment by tannergooding** [comment] 2023-02-23 02:45
There are several blogs and docs that go more in depth on how floating-point works.  A recent one that's been going around is https://jvns.ca/blog/2023/01/13/examples-of-floating-point-problems/

I've likewise given several explanations here on GitHub, but also on Twitter, Mastodon, various blog posts, etc.

In this case, for values between `2^15` and `2^16`, the distance between values is `32` and so only multiples of 32 can be exactly represented.

**Comment by tannergooding** [comment] 2023-02-23 02:51
@Gavin-Williams, I noticed you reacted with the "confused" emoji.

Please let me know if there is anything I can do to help elaborate or make this clearer.

**Comment by Gavin-Williams** [comment] 2023-02-23 05:18
@tannergooding Your explanation is fine - I think. But it touches on a concept that I've never had to consider, and I would argue - shouldn't have to. I would bet that most people would say that MaxValue should give the maximum value for the type, not the value that is easiest to determine. Or one of the possible high values. 

I guess I am confused about why different values can be produced. I can't really remember how floating point works - I did it at uni and forget it a week later. And I don't remember anything about being able to interpret values in different ways. There was a range of possible values, and each range had a minimum and maximum.

**Closed** 2023-02-27 17:08 UTC
Labels: question, area-System.Numerics, needs-further-triage
