### ISSUE TITLE
Dispose not called on exception on linux-arm runtime

### ISSUE THREAD

**Issue by raffaeler** [dotnet/runtime#82941] opened 2023-03-03 13:27 UTC
### Description

In an IoT scenario on a Raspberry PI, I can see the Dispose method not being called for an unhandled exception (see the repro code).
This only happens on `linux-arm` runtime and not on Windows 10.

Since the application accesses the Gpio mapped on the file system, when it crashes, the process does not restore the correct Gpio state and it requires the OS to be rebooted.

This issue derives from an issue raised on the `dotnet/iot` repo here: https://github.com/dotnet/iot/issues/1992
I am just trying to understand whether:
- there is a problem specific to this runtime
or
- the behavior is by design. In this case we need a workaround to restore a stable state (closing the Gpio)

### Reproduction Steps

```
internal class Program
{
    static void Main(string[] args)
    {
        using var c = new MyClass();
        throw new Exception("Boom");
    }
}


public class MyClass : IDisposable
{
    public void Dispose()
        => Console.WriteLine("MyClass.Dispose is called");
}

```

### Expected behavior

I expect Dispose method to be called

### Actual behavior

On a Raspberry PI (Raspbian): `Linux piraf10 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux`
```
pi@piraf10:~/test/plain $ dotnet run
Unhandled exception. System.Exception: Boom
   at Program.Main(String[] args) in /home/pi/test/plain/Program.cs:line 7
pi@piraf10:~/test/plain $
```

### Configuration

```
pi@piraf10:~/test/plain $ dotnet --info
.NET SDK:
 Version:   7.0.201
 Commit:    68f2d7e7a3

Runtime Environment:
 OS Name:     raspbian
 OS Version:  10
 OS Platform: Linux
 RID:         linux-arm
 Base Path:   /home/pi/.dotnet/sdk/7.0.201/

Host:
  Version:      7.0.3
  Architecture: arm
  Commit:       0a2bda10e8

.NET SDKs installed:
  7.0.201 [/home/pi/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.3 [/home/pi/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.3 [/home/pi/.dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/home/pi/.dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by stephentoub** [comment] 2023-03-03 13:29
Thanks. Duplicate of https://github.com/dotnet/runtime/issues/79155#issuecomment-1344566456.

**Closed by stephentoub** 2023-03-03 13:29 UTC
Labels: untriaged
