### ISSUE TITLE
Array enhancements

### ISSUE THREAD

**Issue by juliusfriedman** [dotnet/runtime#39562] opened 2020-07-17 23:12 UTC
## Proposed API

```diff
public class Array{
   //Indicates if the array is null or empty (length == 0), outputs the length to len in the success case.
+ public static bool IsNullOrEmpty(Array array, out int len);
+ public static ToArray(params Object objects); //ToArray('',"",0)
+ public static ToArray<TElement>(params TElement elements); /// ToArray(1,2,3)
}
```

## Usage Examples

```cs
if(!Array.IsNullOrEmpty(someArray) && len >= 4){
}else{
Array.ToArray(0,0,0,0)
}
```

## Alternative Designs

Extension methods

cc @scalablecory

**Comment by danmosemsft** [comment] 2020-07-17 23:27
My comments in #39560 also apply to this one.

**Comment by danmosemsft** [comment] 2020-07-17 23:29
Also, what value does `Array.ToArray(1, 2, 3)` add over `new[] { 1, 2, 3 }` ? The latter will also cause the compiler to verify you assign it.

**Comment by danmosemsft** [comment] 2020-07-17 23:30
`Array.IsNullOrEmpty` is a duplicate of https://github.com/dotnet/runtime/issues/16359

**Comment by juliusfriedman** [comment] 2020-07-17 23:43
> Also, what value does `Array.ToArray(1, 2, 3)` add over `new[] { 1, 2, 3 }` ? The latter will also cause the compiler to verify you assign it.

it could be an intrinsic. I used a template array or a pool to pull from and then returned in the finalizer or dispose.

**Comment by juliusfriedman** [comment] 2020-07-17 23:44
> `Array.IsNullOrEmpty` is a duplicate of #16359

How? I read it twice and didn't see a method proposal there.

**Comment by danmosemsft** [comment] 2020-07-17 23:47
> How? I read it twice and didn't see a method proposal there.

It's not in the right format (this was 4 years ago) but the top comment literally says "In corefx the method string.IsNullOrEmpty as a replacement to checking if a string is null and has a length of 0.. Maybe we should have a similar API for Array that is implemented in the exact same way for string"

It's also a dupe of https://github.com/dotnet/runtime/issues/32642 as well.

**Comment by danmosemsft** [comment] 2020-07-17 23:49
> it could be an intrinsic. I used a template array or a pool to pull from and then returned in the finalizer or dispose.

I don't follow. Do you mean a JIT intrinsic? Couldn't the JIT generate the same code for either?

**Comment by juliusfriedman** [comment] 2020-07-17 23:52
> > it could be an intrinsic. I used a template array or a pool to pull from and then returned in the finalizer or dispose.
> 
> I don't follow. Do you mean a JIT intrinsic? Couldn't the JIT generate the same code for either?

I don't think so, one is a pattern and the other is free for the caller to do as they choose, the JIT should be able to do both, we already need so many cast hacks and hints.

**Comment by danmosemsft** [comment] 2020-07-18 00:06
Either the JIT can recognize the pattern or it can't. If it can - that is better than a new API, as all code gets better without source changes or even recompilation.

Let's say we have the new API and it's specially recognized. What how would you improve the codegen? [Here is what it does today](https://sharplab.io/#v2:C4LghgzgtgPgAgJgIwFgBQcDMACR2DC2A3utmbjnACzYCyAFNgJYB2wz2AlMaeX73zIA3MACdsAD2wBebCwCmAdwDaAXWLYkAGmwIdTbAF8A3AKNmzWXDQBy9TmZJpB5EeKmyFK9UU0692DgmZi5kZobohkA)

**Comment by juliusfriedman** [comment] 2020-07-18 00:16
[By making case O like case M or better](https://sharplab.io/#gist:6ae614cab9f68f830b5006f3efb7ff48)

**Comment by danmosemsft** [comment] 2020-07-18 00:24
I do not follow. In your example, O does not improve on M or N. 

It doesn't matter -- you still have not offered evidence of measurable performance improvements in real code.

**Comment by juliusfriedman** [comment] 2020-07-18 00:26
Explain,

```
  L0000: mov eax, ecx
    L0002: ret
```

is the smallest the JIT can get it cause it created the array, hence an intrinsic is already doing this... just not enough

**Comment by danmosemsft** [comment] 2020-07-18 00:41
I do not follow. In your example, `M(1, 2, 3)` is nothing but overhead you have created. The method M is doing all the work.. If you look at the size of that, it's the same as the others. Sure, you could imagine a built-in method that creates the array, but you're swapping a method call to create the array for a method call to a method that creates the array. Either way, the cost is negligible, in any real app, that should ideally not be creating huge numbers of arrays in hot paths.

**Comment by juliusfriedman** [comment] 2020-07-18 00:52
Okay well don't take it if you don't wan it, the IsNullOrEmpty is just about the same type of thing as for String in the other proposal.

**Comment by danmosemsft** [comment] 2020-07-18 01:40
In the string case it’s to save typing an extremely common pattern.

**Closed by danmosemsft** 2020-07-18 01:40 UTC
Labels: api-suggestion, area-System.Runtime, untriaged

**Comment by juliusfriedman** [comment] 2020-07-18 04:48
> In the string case it’s to save typing an extremely common pattern.

And an string is not an array of chars?
