### ISSUE TITLE
Test failure JIT/opt/OSR/synchronized/synchronized.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#96600] opened 2024-01-08 01:50 UTC
**Failed in:** [runtime-coreclr jitstress-random 20240107.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=517364&view=ms.vss-test-web.build-test-results-tab&runId=12142014&resultId=113912&paneView=debug)

**Failed tests:**
```
coreclr windows arm64 Checked jitstress_random_2 @ Windows.11.Arm64.Open
    - JIT/opt/OSR/synchronized/synchronized.cmd
```

**Error message:**
```
 
Return code:      1
Raw output file:      C:hwAC88094AwAAB7094FuploadsOSRsynchronizedoutput.txt
Raw output:
BEGIN EXECUTION
 "C:hwAC88094Apcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  synchronized.dll 
EXCEPTION
FAILURE
Xunit.Sdk.EqualException: Assert.Equal() Failure: Values differ
Expected: 100
Actual:   -1
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 139
   at Xunit.Assert.Equal[T](T expected, T actual) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 83
   at __GeneratedMainWrapper.Main()
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:cores since 1/7/2024 7:50:10 PM
Finished looking for *.dmp. No new files created.
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> C:hwAC88094AwAAB7094FeJIToptJIT.opt../OSR/synchronized/synchronized.cmd
```

**Stack trace:**
```
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor327|0_328(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

This was using 
```
DOTNET_TieredCompilation=0
DOTNET_JitStress=32e
```

**Comment by BruceForstall** [comment] 2024-01-08 21:10
@AndyAyersMS PTAL

**Comment by v-wenyuxu** [comment] 2024-01-29 01:19
**Failed again in:** [runtime-coreclr jitstress-random 20240128.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=543777&view=ms.vss-test-web.build-test-results-tab&runId=12898572&resultId=110262&paneView=debug)

**Failed tests:**
```
coreclr windows arm64 Checked jitstress_random_1 @ Windows.11.Arm64.Open
    - JIT/opt/OSR/synchronized/synchronized.cmd
```

**Error message:**
```
 Return code:      1
Raw output file:      C:hwB4C209D5wC38E0A34uploadsOSRsynchronizedoutput.txt
Raw output:
BEGIN EXECUTION
 "C:hwB4C209D5pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  synchronized.dll 
EXCEPTION
FAILURE
Xunit.Sdk.EqualException: Assert.Equal() Failure: Values differ
Expected: 100
Actual:   -1
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 168
   at Xunit.Assert.Equal[T](T expected, T actual) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 90
   at __GeneratedMainWrapper.Main()
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:cores since 1/28/2024 7:48:15 PM
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> C:hwB4C209D5wC38E0A34eJIToptJIT.opt../OSR/synchronized/synchronized.cmd
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor327|0_328(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by AndyAyersMS** [comment] 2024-02-26 16:29
Hasn't failed this way again in the past month (though with jit stress random that doesn't necessarily mean the issue is gone). Wasn't able to repro this locally. Am going to have to wait for it to fail again and see if the lab artifacts prove useful.

**Comment by AndyAyersMS** [comment] 2024-04-05 00:55
No failures in past 30 days. Going to clear the blocking label but leave open for now.

**Comment by AndyAyersMS** [comment] 2024-05-03 20:41
Still no recent failures. I'm going to close this, we can revisit if we ever get a repro.

**Closed by AndyAyersMS** 2024-05-03 20:41 UTC
Labels: arch-arm64, os-windows, JitStress, area-CodeGen-coreclr
