### ISSUE TITLE
Disable slow Regex test on debug CLR

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#87363] opened 2023-06-10 12:24 UTC
System.Text.RegularExpressions.Tests.RegexMatchTests.StressTestDeepNestingOfLoops(engine: NonBacktracking, begin: "(", inner: "a", end: ")*", input: "a", pattern_repetition: 2000, input_repetition: 1000) [FAIL]

https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-87311-merge-fca2cf4dbf2740dc98/System.Text.RegularExpressions.Tests/1/console.964f483f.log?helixlogtype=result

**Comment by stephentoub** [comment] 2023-06-10 12:28
Duplicate of https://github.com/dotnet/runtime/issues/84188

**Closed** 2023-06-10 12:45 UTC
Labels: area-System.Text.RegularExpressions, untriaged
