### ISSUE TITLE
Internal PRs broken for runtime

### ISSUE THREAD

**Issue by mmitche** [dotnet/runtime#56162] opened 2021-07-22 16:19 UTC
Internal PRs are broken for the runtime repo see https://dev.azure.com/dnceng/internal/_build/results?buildId=1253092&view=results for an example. My guess is that there is some inconsistent usage of YAML conditionalization based on whether the build is running on the internal project or PR/not-PR

**Comment by hoyosjs** [comment] 2021-07-23 03:40
Dupe of #47328

**Closed** 2021-07-23 03:40 UTC
Labels: untriaged
