### ISSUE TITLE
BDN randomly crashes on Linux?

### ISSUE THREAD

**Issue by EgorBo** [dotnet/runtime#90691] opened 2023-08-16 19:52 UTC
Filing a tracking issue for the bug @stephentoub noticed on Linux-x64, minimal repro:
```cs
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

BenchmarkSwitcher.FromAssembly(typeof(Tests).Assembly).Run(args);

[DisassemblyDiagnoser]
public class Tests
{
    IEnumerable<int> _source = Enumerable.Repeat(0, 1024);
    Random _rand = new();

    [Benchmark]
    public bool Any() => _rand.NextDouble() < 1.0 ?
        _source.Any(i => i == 42) :
        _source.Any(i => i == 43);
}
```
Run with:
```
dotnet run -c Release -f net8.0 -- -j short --filter "*" --iterationTime 50
```
(`--iterationTime 50` is just to make crash faster, it reproduces without it as well)

When we run - it randomly just quits silently in the middle of benchmarking (it doesn't happen for all benchmarks, but so far it looks like it's not PGO, TieredCompilation, AVX512 and Stephen even managed to repro it on .NET 7.0).

Presumably, the culprit is `[DisassemblyDiagnoser]` and ClrMD behind it.

cc @adamsitnik

**Comment by AndyAyersMS** [comment] 2023-08-16 20:18
I have seen this too, and removing `[DissasemblyDiagnoser]` has fixed things.

**Comment by stephentoub** [comment] 2023-08-16 21:01
> removing [DissasemblyDiagnoser] has fixed things

Yeah, but unfortunately I need it :)

**Comment by AndyAyersMS** [comment] 2023-08-16 21:18
Profiling (or other knowledge of the methods of interest matter) plus a suitably crafted `DOTNET_JitDisasm` and `DOTNET_JitStdOutFile` might get you something you could use instead.

**Comment by stephentoub** [comment] 2023-08-16 21:33
> Profiling (or other knowledge of the methods of interest matter) plus a suitably crafted `DOTNET_JitDisasm` and `DOTNET_JitStdOutFile` might get you something you could use instead.

Yes, it just doesn't work well for my blog post. As written, everyone will get crashes.

**Comment by adamsitnik** [comment] 2023-08-17 06:37
It may be caused by something similar to https://github.com/dotnet/runtime/pull/79846 which got fixed by @janvorli. 

> it randomly just quits silently in the middle of benchmarking

BDN attaches the disassembler after all iterations (to not affect the results), so I am not 100% sure.

**Comment by janvorli** [comment] 2023-08-17 17:00
The  `BenchmarkDotNet.Disassemblers.ClrMdV2Disassembler.TryTranslateAddressToName` is being passed address with value `0xffffffffffffffff`

**Comment by janvorli** [comment] 2023-08-18 12:59
I am trying a fix now

**Comment by janvorli** [comment] 2023-08-18 13:38
The fix worked, I'll create a PR shortly.

**Closed** 2023-08-22 18:29 UTC
Labels: area-Diagnostics-coreclr, in-pr

**Comment by AndyAyersMS** [comment] 2023-08-22 19:17
Should we port this to RC1?
