### ISSUE TITLE
JIT/Regression/JitBlue/Runtime_34587 crashes Crossgen2 compilation with an assertion failure

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#63818] opened 2022-01-14 23:18 UTC
OS: all (observed on Windows and Linux)
Architecture: all (observed on x86 and x64, arm runs are somewhat flaky these days)
Example run: https://dev.azure.com/dnceng/public/_build/results?buildId=1552238&view=ms.vss-test-web.build-test-results-tab

Diagnostics:

<pre>
  Starting:    JIT.Regression.XUnitWrapper (parallel test collections = on, max threads = 4)
    JIT\Regression\JitBlue\Runtime_34587\Runtime_34587\Runtime_34587.cmd [FAIL]
      Could Not Find C:\h\w\A2A20899\w\C2860A5B\e\JIT\Regression\JitBlue\Runtime_34587\Runtime_34587\IL-CG2\composite-r2r.dll
      Could Not Find C:\h\w\A2A20899\w\C2860A5B\e\JIT\Regression\JitBlue\Runtime_34587\Runtime_34587\Runtime_34587.dll.rsp
      Process terminated. Assertion failed.
         at ILCompiler.DependencyAnalysis.SortableDependencyNode.ObjectNodeComparer.Compare(DependencyNodeCore`1 x1, DependencyNodeCore`1 y1)
         at ILCompiler.Sorting.Implementation.MergeSortCore`5.Merge(T[] localCopyOfHalfOfArray, TDataStructure arrayToSort, Int32 index, Int32 halfLen, Int32 length, TComparer comparer)
         at ILCompiler.Sorting.Implementation.MergeSortCore`5.MergeSortHelper(TDataStructure arrayToSort, Int32 index, Int32 length, TComparer comparer, T[] scratchSpace)
         at ILCompiler.Sorting.Implementation.MergeSortCore`5.ParallelSortApi(TDataStructure arrayToSort, TComparer comparer)
         at ILCompiler.MergeSortApi.MergeSortAllowDuplicates[T](List`1 listToSort, IComparer`1 comparer)
         at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes()
         at ILCompiler.ReadyToRunCodegenCompilation.Compile(String outputFile)
         at ILCompiler.Program.RunSingleCompilation(Dictionary`2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary`2 unrootedInputFilePaths, HashSet`1 versionBubbleModulesHash, CompilerTypeSystemContext typeSystemContext)
         at ILCompiler.Program.Run(String[] args)
         at ILCompiler.Program.Main(String[] args)
      
      Return code:      1
</pre>

This got broken after @tannergooding's change

https://github.com/dotnet/runtime/commit/4f89b79d842ece91d04a47d5483c7b34abd2e954

but the change itself isn't to blame, it just uncovered a pre-existing bug in Crossgen2 regarding unstable ordering - we create two instances of ReadyToRunInstructionSetSupportSignature, one of which is the "baseline instruction set support" and the other is a PerMethodInstructionSetSupportFixup (for the method [Runtime_34587]Runtime_34587.<ValidateArm>g__ValidateVector256|1_11()) - both of which have the same key, "X86Base+Sse+Sse2,". The reason we need the instruction set fixup is the second loop (over _actualInstructionSetUnsupported) where the conditional block in the loop body is entered for the instruction set "ARM64_Rdm_Arm64" (while building for Windows x64 release):

https://github.com/dotnet/runtime/blob/2692407f03ce8b648c54daa4d3a3eb534132edc9/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs#L450

I have consulted @davidwrighton w.r.t. triage of this issue and we are in agreement that the proximate bug is in Crossgen2 that shouldn't generate a per-method instruction set fixup considering the instruction set is the same as the baseline. It's however unclear whether the root cause is truly in Crossgen2 or whether it might be caused by erroneous, imprecise or misinterpreted JIT reporting by means of the <code>notifyInstructionSetUsage</code> JitInterface API.

Thanks

Tomas

/cc @dotnet/crossgen-contrib @dotnet/jit-contrib

**Comment by MichalStrehovsky** [comment] 2022-01-14 23:24
Duplicate of #63716?

**Comment by trylek** [comment] 2022-01-14 23:29
For sure, thanks @MichalStrehovsky for pointing that out. I'm about to close the item 63716 as a duplicate of this one because I believe this item contains more triage details.

**Comment by tannergooding** [comment] 2022-01-15 00:44
@trylek anything needed from me here or that I can assist with?

**Comment by trylek** [comment] 2022-01-16 19:48
@tannergooding - I don't think so, your change just hit a previously unseen code path in Crossgen2. I think it would be ideal if David Wrighton could look into the issue as he originally implemented the instruction set manipulation in Crossgen2 so he probably has the best context regarding the exact semantics.

**Closed** 2022-02-18 19:35 UTC
Labels: area-crossgen2-coreclr, in-pr
