### ISSUE TITLE
HtmlEncoder manual configuration does not work for some symbols. 

### ISSUE THREAD

**Issue by Aleksej-Shherbak** [dotnet/runtime#66728] opened 2022-03-16 09:33 UTC
### Describe the bug

I have the following `HtmlEncoder` configuration:

```C#
builder.Services.AddSingleton<HtmlEncoder>(
    HtmlEncoder.Create(allowedRanges: new[] { UnicodeRanges.BasicLatin, UnicodeRanges.Cyrillic }));

```

And the following view: 

```cshtml
@{
    var test = "Тест +"; 
}

<h1>@test</h1>

```

As you can see, I have mixed Cyrillic symbols and `+` symbol. If you check the Unicode table [website](https://unicode-table.com/en/002B/) you will see that `+` is from `Basic Latin` block that I used in my configuration. 

It looks like perfectly in browser:
![image](https://user-images.githubusercontent.com/12964099/158557764-832aee8f-5b2e-4cf6-a257-d651efb58df2.png)

### Expected Behavior

But I have a lot of issues from me SEO department about how it looks like on the View Source browser section:

![image](https://user-images.githubusercontent.com/12964099/158558128-2745b9d9-2cfc-48bb-bfe3-daf8a9698f71.png)

As you can see, plus symbol has not been decoded, and it seems  `UnicodeRanges.BasicLatin` does not work. Why? Have I done something wrong? 

### Steps To Reproduce

My repo with the example project is here: https://github.com/Aleksej-Shherbak/Razor_plus_symbol_issue_example_project/tree/master/WebApplication3
Just run it and open View source tab in your browser dev tools.

**Comment by filipnavara** [comment] 2022-03-17 11:00
I suppose this is duplicate of https://github.com/dotnet/runtime/issues/65130.

**Comment by bartonjs** [comment] 2022-03-18 17:22
I agree with @filipnavara's duplicate-suggestion.  It's not that BasicLatin isn't being honored, it's that `+` is on the "always escape" list.

https://github.com/dotnet/runtime/issues/65130#issuecomment-1040871368 discusses it in more detail.

**Closed by bartonjs** 2022-03-18 17:22 UTC
Labels: area-System.Text.Encoding, untriaged, area-runtime
