### ISSUE TITLE
Blazor WASM Error on iOS Safari - RangeError: Out of Memory

### ISSUE THREAD

**Issue by kyletinsley** [dotnet/runtime#79909] opened 2022-12-22 15:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When loading Blazor WASM apps in iOS Safari, the following error is encountered, causing all apps to fail to load:
RangeError: Out of memory

I've encountered this error in every app I've written.  To ensure the issue was not within my code, I created a new project using the standard WASM template in VS (counter/weather) and made **no modifications**.  
![image](https://user-images.githubusercontent.com/2884619/209173072-bba42fa2-30f9-4ebd-8d93-c1c5d679ea12.png)

I then deployed the default/unmodified app to Azure and repeated my testing.  The error is encountered randomly when refreshing Safari on iOS (about every 5th refresh).  I've experienced this on multiple iPhones and verified on BrowserStack using several iOS devices and Safari versions.

Here's the deployed base app:
[https://blazor7-test.azurewebsites.net](https://blazor7-test.azurewebsites.net)

This is s screenshot I took from BrowserStack:
![2022-12-22_10-08-30](https://user-images.githubusercontent.com/2884619/209168721-43cfd230-68ff-4fe9-b58e-b7205e0144a2.png)

### Expected Behavior

App should load successfully, as it does in other browsers.

### Steps To Reproduce

1. Using the standard .NET7 Blazor WebAssembly project template, create a new project.
2. Deploy that app to Azure app services.

### Exceptions (if any)

RangeError: Out of Memory

### .NET Version

7.0.100

**Comment by pavelsavara** [comment] 2023-01-16 09:46
@kyletinsley 
What does your `dotnet workload list` print ?

**Comment by kyletinsley** [comment] 2023-01-16 21:07
![image](https://user-images.githubusercontent.com/2884619/212765818-633b5a5c-c559-42d5-ae2d-77b99d2a2fe5.png)

**Comment by pavelsavara** [comment] 2023-01-17 10:33
@kyletinsley 
could you please build/publish your project with `-bl` and share with me the binlog ?
Also please check what value INITIAL_MEMORY has, search inside your `dotnet*.js`

I'm trying to understand what triggers the `re-link` for you. 
I could not reproduce it on vanilla blazor template.
Are you passing some MSBuild switches on commandline ? Or adding them to the .csproj in your real project ?

Thanks!

**Comment by pavelsavara** [comment] 2023-01-17 10:43
Now I understand, just the installation of the `wasm-tools` workload always triggers re-link and you get.
```
Compiling native assets with emcc with -Oz. This may take a while ...
...
Linking for initial memory $(EmccInitialHeapSize)=536870912 bytes
```

**Comment by pavelsavara** [comment] 2023-01-17 10:51
> Now I understand, just the installation of the `wasm-tools` workload always triggers re-link and you get.

@radical @lewing 
I think we should not change behavior of the build just by installing the workload. 
I would rather have people also opt in via some msbuild property.
What do you think ?

**Comment by pavelsavara** [comment] 2023-02-24 13:43
Fixed by https://github.com/dotnet/runtime/pull/80849

**Closed by pavelsavara** 2023-02-24 13:43 UTC
Labels: arch-wasm, area-VM-meta-mono
