### ISSUE TITLE
deserializing to DataSet returns 0 tables

### ISSUE THREAD

**Issue by bkbartje** [dotnet/runtime#31795] opened 2020-02-05 12:36 UTC
when I use this method
var ds = System.Text.Json.JsonSerializer.Deserialize<DataSet>(json);
the dataset has gets no tables and stays empty.

**Comment by vcsjones** [comment] 2020-02-05 18:22
Related to https://github.com/dotnet/runtime/issues/29959#issuecomment-503876056. "DataTable and related types" are not supported currently. I would assume that since `DataTable` is not supported, then `DataSet` is not either.

**Comment by etghanibahman** [comment] 2020-02-20 07:26
There are some kind of serializations that do not exist in system.text.json by default. you should add them manually , and for this there are two patterns : the basic pattern and the factory pattern
There are two patterns for creating a custom converter: the basic pattern and the factory pattern. 
The one that you need is a basic pattern for Dataset. The following works well for me, I hope it helps you too.

public class DataSetConverter : JsonConverter<DataSet>
    {
        public override DataSet Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            using var jsonDoc = JsonDocument.ParseValue(ref reader);
            var rootElement = jsonDoc.RootElement;
            var dataSet = rootElement.JsonElementToDataSet();
            return dataSet;

        }
        public override void Write(Utf8JsonWriter jsonWriter, DataSet value, JsonSerializerOptions options)
        {
            jsonWriter.WriteStartArray();
            //DataTableConverter _DataTableConverter = new DataTableConverter();
            foreach (DataTable source in value.Tables)
            {

                foreach (DataRow dr in source.Rows)
                {
                    jsonWriter.WriteStartObject();
                    foreach (DataColumn col in source.Columns)
                    {
                        var key = col.ColumnName.Trim();
                        var valueString = dr[col].ToString();
                        switch (col.DataType.FullName)
                        {
                            case "System.Guid":
                                jsonWriter.WriteString(key, valueString);
                                break;
                            case "System.Char":
                            case "System.String":
                                jsonWriter.WriteString(key, valueString);
                                break;
                            case "System.Boolean":
                                Boolean.TryParse(valueString, out bool boolValue);
                                jsonWriter.WriteBoolean(key, boolValue);
                                break;
                            case "System.DateTime":
                                if (DateTime.TryParse(valueString, out DateTime dateValue))
                                {
                                    jsonWriter.WriteString(key, dateValue);
                                }
                                else
                                {
                                    jsonWriter.WriteString(key, "");
                                }
                                break;
                            case "System.TimeSpan":
                                if (DateTime.TryParse(valueString, out DateTime timeSpanValue))
                                {
                                    jsonWriter.WriteString(key, timeSpanValue.ToString());
                                }
                                else
                                {
                                    jsonWriter.WriteString(key, "");
                                }
                                break;
                            case "System.Byte":
                            case "System.SByte":
                            case "System.Decimal":
                            case "System.Double":
                            case "System.Single":
                            case "System.Int16":
                            case "System.Int32":
                            case "System.Int64":
                            case "System.UInt16":
                            case "System.UInt32":
                            case "System.UInt64":
                                if (long.TryParse(valueString, out long intValue))
                                {
                                    jsonWriter.WriteNumber(key, intValue);
                                }
                                else
                                {
                                    double.TryParse(valueString, out double doubleValue);
                                    jsonWriter.WriteNumber(key, doubleValue);
                                }
                                break;
                            default:
                                jsonWriter.WriteString(key, valueString);
                                break;
                        }
                    }
                    jsonWriter.WriteEndObject();
                }

            }
            jsonWriter.WriteEndArray();
        }
    }

**Comment by layomia** [comment] 2020-02-21 00:35
Closing as duplicate of https://github.com/dotnet/runtime/issues/29959.

**Closed by layomia** 2020-02-21 00:35 UTC
Labels: area-System.Text.Json, untriaged
