### ISSUE TITLE
Static getter Encoding.BigEndianUTF32 is private

### ISSUE THREAD

**Issue by PatVax** [dotnet/runtime#99903] opened 2024-03-18 13:19 UTC
### Description

The static getter is private while similar ones for other Unicode encodings are public. This seems like a simple typo.

### Reproduction Steps

Try calling the following outside of declaring assembly:
```csharp
Encoding encoding = Encoding.BigEndianUTF32;
```

### Expected behavior

I think this should just work. The only other place where it is referenced is in GetEncoding(int codepage) function.

### Actual behavior

CS0117: 'Encoding' does not contain a definition for 'BigEndianUTF32'
Cannot resolve symbol 'BigEndianUTF32'

### Known Workarounds

```csharp
Encoding encoding = Encoding.GetEncoding(12001);
```
Internally GetEncoding will actually call the private getter.

**Comment by skyoxZ** [comment] 2024-03-18 14:02
Duplicate of #29388

**Comment by PatVax** [comment] 2024-03-18 14:39
If it really is intended then I guess this issue may be closed. It is still weird that one has to do the GetEncoding(12001) workaround.

**Closed** 2024-03-19 10:06 UTC
Labels: area-System.Text.Encoding, untriaged
