### ISSUE TITLE
[7.0] Test failure in JIT_HardwareIntrinsics._X86_Sse2_LoadLow_ro_LoadLow_ro_._X86_Sse2_LoadLow_ro_LoadLow_ro_sh()

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#82633] opened 2023-02-24 18:10 UTC
- Affected PR: https://github.com/dotnet/runtime/pull/82554/
- Queue: `Build Browser wasm Linux Release AllSubsets_Mono_RuntimeTests`
- Job result: https://dev.azure.com/dnceng-public/public/_build/results?buildId=182544&view=logs&j=190ad6c8-5950-568c-cadd-f2dfb7d5a79f&t=c0f6fdc1-ac5d-583c-8ae1-a18de0846552&l=41
- Log file: https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-pull-82554-merge-7130257ad20d4e91a0/JIT.HardwareIntrinsics.X86.Sse2/1/console.da0383d5.log?helixlogtype=result

```
Microsoft.DotNet.XUnitConsoleRunner v2.5.0 (64-bit .NET 7.0.3)
  Discovering: JIT.HardwareIntrinsics.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  JIT.HardwareIntrinsics.XUnitWrapper (found 50 of 362 test cases)
  Starting:    JIT.HardwareIntrinsics.XUnitWrapper (parallel test collections = on, max threads = 2)
    JIT/HardwareIntrinsics/X86/Sse2/LoadLow_ro/LoadLow_ro.sh [FAIL]
      System.IO.IOException: The system cannot open the device or file specified. : 'NuGet-Migrations'
         at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
         at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
         at NuGet.Common.Migrations.MigrationRunner.Run()
         at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
         at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean isDotnetBeingInvokedFromNativeInstaller, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider, Dictionary`2 performanceMeasurements)
         at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
         at Microsoft.DotNet.Cli.Program.Main(String[] args)
      
      Return code:      1
      Raw output file:      /datadisks/disk1/work/A5FD0965/w/B26909EB/uploads/Reports/JIT.HardwareIntrinsics/X86/Sse2/LoadLow_ro/LoadLow_ro.output.txt
      Raw output:
      BEGIN EXECUTION
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/datadisks/disk1/work/A5FD0965/p
      > /datadisks/disk1/work/A5FD0965/w/B26909EB/e/JIT/HardwareIntrinsics/X86/Sse2/LoadLow_ro/LoadLow_ro.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at JIT_HardwareIntrinsics._X86_Sse2_LoadLow_ro_LoadLow_ro_._X86_Sse2_LoadLow_ro_LoadLow_ro_sh()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
      Output:
        System.IO.IOException: The system cannot open the device or file specified. : 'NuGet-Migrations'
           at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
           at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
           at NuGet.Common.Migrations.MigrationRunner.Run()
           at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
           at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean isDotnetBeingInvokedFromNativeInstaller, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider, Dictionary`2 performanceMeasurements)
           at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
           at Microsoft.DotNet.Cli.Program.Main(String[] args)
        
        Return code:      1
        Raw output file:      /datadisks/disk1/work/A5FD0965/w/B26909EB/uploads/Reports/JIT.HardwareIntrinsics/X86/Sse2/LoadLow_ro/LoadLow_ro.output.txt
        Raw output:
        BEGIN EXECUTION
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/datadisks/disk1/work/A5FD0965/p
        > /datadisks/disk1/work/A5FD0965/w/B26909EB/e/JIT/HardwareIntrinsics/X86/Sse2/LoadLow_ro/LoadLow_ro.sh
  Finished:    JIT.HardwareIntrinsics.XUnitWrapper
=== TEST EXECUTION SUMMARY ===
   JIT.HardwareIntrinsics.XUnitWrapper  Total: 50, Errors: 0, Failed: 1, Skipped: 0, Time: 47.729s
```

```json
{
  "ErrorMessage": "JIT_HardwareIntrinsics._X86_Sse2_LoadLow_ro_LoadLow_ro_._X86_Sse2_LoadLow_ro_LoadLow_ro_sh()",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by lewing** [comment] 2023-02-24 18:18
https://github.com/dotnet/runtime/issues/80619

**Comment by lewing** [comment] 2023-02-24 18:26
@carlossanlop this is the nuget-migrations logic failing in the script that runs the test, not the test

**Comment by radical** [comment] 2023-02-28 17:20
Closing as dupe of https://github.com/dotnet/runtime/issues/80619 .

**Closed by radical** 2023-02-28 17:20 UTC
Labels: arch-wasm, arch-x86, os-linux, area-Infrastructure, test-failure, Known Build Error
