### ISSUE TITLE
New rules related to "pure" methods

### ISSUE THREAD

**Issue by Evangelink** [dotnet/runtime#38860] opened 2020-07-07 10:47 UTC
### Describe the problem you are trying to solve

I would like to suggest 2 related new rules related to "pure" state of methods. The first rule would report an issue if the method is marked with `PureAttribute` but changes some states. The second rule would suggest to apply the `PureAttribute` when the method doesn't have any side-effect.

### Describe suggestions on how to achieve the rule

I think that we could assume that a method is pure if it only calls pure methods and doesn't set any field or property. 

The rule might be a little noisy when used in a context where the `PureAttribute` is not widely used as this behaves a little like nullable or async through a "contamination" (not sure what the right word) process.

### Additional context

It seems that in `dotnet/runtime` there is a trend to stop using the `PureAttribute` (see https://github.com/dotnet/runtime/issues/33414) but I am wondering if having an analyzer would help having it used more.

We could also think about introducing some user-option to somehow change the rule strictness, for example, writing to a stream (log, console...) is theoretically a sign of "impurity" as there is an actual modification to the global state but some people think that's ok.

**Comment by Evangelink** [comment] 2020-07-07 12:09
@mavasani @stephentoub Thanks!

**Comment by AmrAlSayed0** [comment] 2020-07-07 13:27
> I think that we could assume that a method is pure if it only calls pure methods and doesn't set any field or property.

I think that any use of a property of any kind, getter or setter, should be considered non-pure because they're effectively functions. Getters are often used as lazy initializers of a field which changes state. I don't have a case where setters could be used without changing state but it is possible albeit extremely rare.

So both getters and setters should be treated as non-pure unless they're marked with a `PureAttribute`.

**Comment by stephentoub** [comment] 2022-03-14 14:15
Closing as a duplicate of https://github.com/dotnet/runtime/issues/34098

**Closed by stephentoub** 2022-03-14 14:15 UTC
Labels: api-suggestion, area-System.Runtime, code-analyzer
