### ISSUE TITLE
Test failure: WasmTestOnBrowser-System.IO.MemoryMappedFiles - Memory access out of bounds

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#75465] opened 2022-09-12 17:30 UTC
Frequency [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime+name%3A%22wasmtestonbrowser-system.io.memorymappedfiles.tests+work+item%22) in Runfo as 9/12:

Day | Run | Details
-- | -- | --
9/11 | Rolling run [12016](https://runfo.azurewebsites.net/view/build/?number=12016) | net7.0-Browser-Release-wasm-Mono_Release-WasmTestOnBrowser-Ubuntu.1804.Amd64.Open
8/25 | PR [1966882](https://runfo.azurewebsites.net/view/build/?number=1966882) | net7.0-Browser-Release-wasm-Mono_Release-WasmTestOnBrowser-Ubuntu.1804.Amd64.Open
8/25-26 | ~2x PR [1966436](https://runfo.azurewebsites.net/view/build/?number=1966436)~ | Different error - specific to the PR
8/25 | ~PR [1965131](https://runfo.azurewebsites.net/view/build/?number=1965131)~ | Different error
8/22 | PR [1958433](https://runfo.azurewebsites.net/view/build/?number=1958433) | net7.0-Browser-Release-wasm-Mono_Release-WasmTestOnBrowser-Ubuntu.1804.Amd64.Open

Error example (from [Console log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-30d232de713f4aa383/WasmTestOnBrowser-System.IO.MemoryMappedFiles.Tests/1/console.8998763f.log?%3Fhelixlogtype%3Dresult)):
```
[21:25:30] info: Starting:    System.IO.MemoryMappedFiles.Tests.dll
[21:25:30] fail: RuntimeError: memory access out of bounds
                     at dlfree (dlfree (http://127.0.0.1:37767/dotnet.wasm:wasm-function[9152]:0x1e0b6c))
                     at __munmap (__munmap (http://127.0.0.1:37767/dotnet.wasm:wasm-function[9054]:0x1d7166))
                     at SystemNative_MUnmap (SystemNative_MUnmap (http://127.0.0.1:37767/dotnet.wasm:wasm-function[8863]:0x1cb132))
                     at wasm_invoke_iil (wasm_invoke_iil (http://127.0.0.1:37767/dotnet.wasm:wasm-function[176]:0xc2a3))
                     at interp_exec_method (interp_exec_method (http://127.0.0.1:37767/dotnet.wasm:wasm-function[222]:0xe776))
                     at interp_runtime_invoke (interp_runtime_invoke (http://127.0.0.1:37767/dotnet.wasm:wasm-function[221]:0xceb8))
                     at mono_jit_runtime_invoke (mono_jit_runtime_invoke (http://127.0.0.1:37767/dotnet.wasm:wasm-function[8113]:0x1a1f59))
                     at do_runtime_invoke (do_runtime_invoke (http://127.0.0.1:37767/dotnet.wasm:wasm-function[2054]:0x85989))
                     at mono_runtime_invoke_checked (mono_runtime_invoke_checked (http://127.0.0.1:37767/dotnet.wasm:wasm-function[2052]:0x858ff))
                     at ves_icall_InternalInvoke_raw (ves_icall_InternalInvoke_raw (http://127.0.0.1:37767/dotnet.wasm:wasm-function[1395]:0x68457))
[21:25:30] fail: RuntimeError: memory access out of bounds
                     at dlfree (dlfree (http://127.0.0.1:37767/dotnet.wasm:wasm-function[9152]:0x1e0b6c))
                     at __munmap (__munmap (http://127.0.0.1:37767/dotnet.wasm:wasm-function[9054]:0x1d7166))
                     at SystemNative_MUnmap (SystemNative_MUnmap (http://127.0.0.1:37767/dotnet.wasm:wasm-function[8863]:0x1cb132))
                     at wasm_invoke_iil (wasm_invoke_iil (http://127.0.0.1:37767/dotnet.wasm:wasm-function[176]:0xc2a3))
                     at interp_exec_method (interp_exec_method (http://127.0.0.1:37767/dotnet.wasm:wasm-function[222]:0xe776))
                     at interp_runtime_invoke (interp_runtime_invoke (http://127.0.0.1:37767/dotnet.wasm:wasm-function[221]:0xceb8))
                     at mono_jit_runtime_invoke (mono_jit_runtime_invoke (http://127.0.0.1:37767/dotnet.wasm:wasm-function[8113]:0x1a1f59))
                     at do_runtime_invoke (do_runtime_invoke (http://127.0.0.1:37767/dotnet.wasm:wasm-function[2054]:0x85989))
                     at mono_runtime_invoke_checked (mono_runtime_invoke_checked (http://127.0.0.1:37767/dotnet.wasm:wasm-function[2052]:0x858ff))
                     at ves_icall_InternalInvoke_raw (ves_icall_InternalInvoke_raw (http://127.0.0.1:37767/dotnet.wasm:wasm-function[1395]:0x68457))
[21:25:30] fail: RuntimeError: memory access out of bounds
                     at dlfree (dlfree (http://127.0.0.1:37767/dotnet.wasm:wasm-function[9152]:0x1e0b6c))
                     at __munmap (__munmap (http://127.0.0.1:37767/dotnet.wasm:wasm-function[9054]:0x1d7166))
                     at SystemNative_MUnmap (SystemNative_MUnmap (http://127.0.0.1:37767/dotnet.wasm:wasm-function[8863]:0x1cb132))
                     at wasm_invoke_iil (wasm_invoke_iil (http://127.0.0.1:37767/dotnet.wasm:wasm-function[176]:0xc2a3))
                     at interp_exec_method (interp_exec_method (http://127.0.0.1:37767/dotnet.wasm:wasm-function[222]:0xe776))
                     at interp_runtime_invoke (interp_runtime_invoke (http://127.0.0.1:37767/dotnet.wasm:wasm-function[221]:0xceb8))
                     at mono_jit_runtime_invoke (mono_jit_runtime_invoke (http://127.0.0.1:37767/dotnet.wasm:wasm-function[8113]:0x1a1f59))
                     at do_runtime_invoke (do_runtime_invoke (http://127.0.0.1:37767/dotnet.wasm:wasm-function[2054]:0x85989))
                     at mono_runtime_invoke_checked (mono_runtime_invoke_checked (http://127.0.0.1:37767/dotnet.wasm:wasm-function[2052]:0x858ff))
                     at ves_icall_InternalInvoke_raw (ves_icall_InternalInvoke_raw (http://127.0.0.1:37767/dotnet.wasm:wasm-function[1395]:0x68457))
[21:25:30] info: WASM EXIT 1
```

**Comment by karelz** [comment] 2022-09-12 17:31
@lewing @steveisok can you please help route it to the right folks? Not blocking CI yet, but close ...

**Comment by lewing** [comment] 2022-09-14 14:24
cc @vargaz

**Comment by vargaz** [comment] 2022-09-14 14:40
Same as:
https://github.com/dotnet/runtime/issues/74723

**Comment by adamsitnik** [comment] 2022-09-15 08:17
Closing since it's a duplicate of #74723

**Closed by adamsitnik** 2022-09-15 08:17 UTC
Labels: arch-wasm, area-System.IO
