### ISSUE TITLE
Test failure: baseservices\\threading\\paramthreadstart\\ThreadStartObject_2\\ThreadStartObject_2.cmd

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#46281] opened 2020-12-21 06:57 UTC
failed in job: [runtime-coreclr ilasm 20201219.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=927585&view=ms.vss-test-web.build-test-results-tab&runId=29408838&resultId=100327&paneView=debug)

CoreCLR windows x86 Checked ilasmroundtrip @ Windows.10.Amd64.Open

Error message
~~~
Return code:      1
Raw output file:      C:\h\w\AAED0946\w\ACFB095F\e\baseservices\threading\Reports\baseservices.threading\paramthreadstart\ThreadStartObject_2\ThreadStartObject_2.output.txt
Raw output:
BEGIN EXECUTION
 cmd /c ..\ThreadStartObject\ThreadStartObject.cmd
BEGIN EXECUTION
C:\h\w\AAED0946\p\ildasm.exe /raweh /out=ThreadStartObject.dasm.il ThreadStartObject.dll
C:\h\w\AAED0946\p\ilasm.exe /output=ThreadStartObject.asm.dll  ThreadStartObject.dasm.il

Microsoft (R) .NET IL Assembler.  Version 6.0.0-ci
Copyright (c) Microsoft Corporation.  All rights reserved.
Assembling 'ThreadStartObject.dasm.il'  to EXE --> 'ThreadStartObject.asm.dll'
Could not open ThreadStartObject.dasm.il

***** FAILURE ***** 
EXECUTION OF ILASM - FAILED 1
Expected: 0
Actual: 1
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\AAED0946\p
> C:\h\w\AAED0946\w\ACFB095F\e\baseservices\threading\paramthreadstart\ThreadStartObject_2\ThreadStartObject_2.cmd
Expected: True
Actual:   False


Stack trace
   at baseservices_threading._paramthreadstart_ThreadStartObject_2_ThreadStartObject_2_._paramthreadstart_ThreadStartObject_2_ThreadStartObject_2_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\windows.x86.Checked\TestWrappers\baseservices.threading\baseservices.threading.XUnitWrapper.cs:line 31932
~~~

**Comment by JulieLeeMSFT** [comment] 2020-12-23 22:39
@briansull please triage the Ilasm error on threading.

**Comment by briansull** [comment] 2021-01-04 18:24
Looks like a duplicate of #44139

**Comment by briansull** [comment] 2021-01-04 18:32
We have a lot of similar issues:

@BruceForstall 
> Most likely some kind of infrastructure issue due to file locking.

**Comment by BruceForstall** [comment] 2021-01-04 19:42
Yes, looks like a dup

**Closed by BruceForstall** 2021-01-04 19:42 UTC
Labels: area-CodeGen-coreclr, needs further triage
