### ISSUE TITLE
The result of full-width string comparison with InvariantCultureIgnoreCase has changed in .NET 5

### ISSUE THREAD

**Issue by Nukepayload2** [dotnet/runtime#44789] opened 2020-11-17 09:54 UTC
### Description

The result of `String.Equals("ＡＥ", "ａｅ", StringComparison.InvariantCultureIgnoreCase)` has changed to `False` in .NET 5 .

**Steps:**
1. Create a new .NET Core 3.1 or .NET Framework 4.8 VB console project
2. Run the following code. The output is `True` .
```vbnet
Module Program
    Sub Main()
        Console.WriteLine(String.Equals("ＡＥ", "ａｅ", StringComparison.InvariantCultureIgnoreCase))
    End Sub
End Module
```
3. Set target framework to .NET 5.0, and run the project again.

**Expected behavior**
The output is `True`

**Actual behavior**
The output is `False`

### Configuration

.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

### Regression?

Yes. This problem doesn't exist in .NET Framework 4.8 and .NET Core 3.1 .

### Other information

Probably caused by switching to ICU. But [this documentation](https://docs.microsoft.com/en-us/dotnet/standard/base-types/string-comparison-net-5-plus) didn't mention string comparison behavior changes for full-width strings.

We switched back to NLS because of this problem.
```xml
<ItemGroup>
  <RuntimeHostConfigurationOption Include="System.Globalization.UseNls" Value="true" />
</ItemGroup>
```

**Comment by tarekgh** [comment] 2020-11-18 00:08
@Nukepayload2 thanks for reporting the issue. I think you analysis is correct that this happen because switching using ICU but the issue is not ICU itself but how we internally handle this full-width range. we'll work on fixing this issue.

**Comment by tarekgh** [comment] 2020-11-20 00:21
@Nukepayload2 just to mention the workaround for this issue is do something like:

```C#
string.Compare("ＡＥ", "ａｅ", CultureInfo.InvariantCulture, CompareOptions.IgnoreWidth | CompareOptions.IgnoreCase) == 0
```

This should gives you the desired behavior and you don't have to switch back to NLS.

**Comment by Nukepayload2** [comment] 2020-11-23 06:02
> @Nukepayload2 just to mention the workaround for this issue is do something like:
> 
> ```cs
> string.Compare("ＡＥ", "ａｅ", CultureInfo.InvariantCulture, CompareOptions.IgnoreWidth | CompareOptions.IgnoreCase) == 0
> ```
> 
> This should gives you the desired behavior and you don't have to switch back to NLS.

@tarekgh 
Thanks for providing the workaround. However, we still need to switch back to NLS. Because the comparison result of Japanese Hiragana and Katakana strings has changed.

```vbnet
Console.WriteLine(String.Compare("まりお", "マリオ", StringComparison.InvariantCultureIgnoreCase))
```
.NET Framework output: 1
.NET 5 output: -1

**Comment by tarekgh** [comment] 2020-11-23 19:15
@Nukepayload2 thanks again for the feedback.

> However, we still need to switch back to NLS. Because the comparison result of Japanese Hiragana and Katakana strings has changed.

Could you please elaborate more about your scenario? I mean why comparing `まりお` and `マリオ` new results will be broken to you? I understand it will change the sort order but why this break you?

**Comment by Nukepayload2** [comment] 2020-11-24 06:06
@tarekgh 
> I understand it will change the sort order but why this break you?
Because our Japanese end users expect the same order as Excel when sorting Japanese strings.

**Comment by ewfian** [comment] 2020-11-24 11:48
> @tarekgh
> 
> > I understand it will change the sort order but why this break you?
> 
> Because our Japanese end users expect the same order as Excel when sorting Japanese strings.

FYI.
![image](https://user-images.githubusercontent.com/12423122/100089516-258e0000-2e95-11eb-876c-f0c046d8ba9f.png)
Refs:
- http://kikakurui.com/x4/X4061-1996-01.html
- http://www.unicode.org/reports/tr10/#Tertiary_Assignments_Table

**Comment by tarekgh** [comment] 2020-11-24 16:45
> Because our Japanese end users expect the same order as Excel when sorting Japanese strings.

@Nukepayload2 do you expect this order with all cultures? or with Japanese cultures only?

@ewfian thanks for the references. The second one is from Unicode which is what ICU implementing and that is the behavior I guess the complaint is about. no? could you elaborate more about what you are trying to point at from these references?

**Comment by ewfian** [comment] 2020-12-01 03:18
@tarekgh The new behavior base on ICU is what I expected. Just provide some references about Japanese sort order.

**Comment by tarekgh** [comment] 2021-01-04 19:44
Closing this one per the PR https://github.com/dotnet/runtime/pull/45079

**Closed by tarekgh** 2021-01-04 19:44 UTC
Labels: area-System.Globalization, bug
