### ISSUE TITLE
CLR Exception when running in Kubernetes Linux environment at random times on startup

### ISSUE THREAD

**Issue by seiggy** [dotnet/runtime#34021] opened 2020-03-24 15:45 UTC
We're seeing this problem in nearly all of our .NET Core apps in linux. Randomly on startup, the apps will just start throwing a CLR exception for every request. If we bounce the container, it runs just fine. It happens about 1 out of every 100 startups of the applications. Here's a stack trace from the logs of this occuring. We've not been able to replicate this on any developer machine.

`[40m[1m[33mwarn[39m[22m[49m: 
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
[15:22:27 ERR] Unexpected error occurred
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at VTS.Shared.Api.Middleware.Exceptions.ExceptionMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
[41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLUG0NTPANGU", Request id "0HLUG0NTPANGU:00000001": An unhandled exception was thrown by the application.
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at VTS.Shared.Api.Middleware.Exceptions.ExceptionMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at VTS.Shared.Api.Middleware.ValidateRouteEntityIds.ValidateRouteEntityIdsMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at VTS.Shared.Api.Middleware.Authorization.AuthorizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at SimpleInjector.Integration.AspNetCore.RequestScopingStartupFilter.<ConfigureRequestScoping>b__3_0(HttpContext context, Func`1 next)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[15:22:44 ERR] Unexpected error occurred
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at VTS.Shared.Api.Middleware.Exceptions.ExceptionMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
[41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLUG0NTPANGV", Request id "0HLUG0NTPANGV:00000001": An unhandled exception was thrown by the application.
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at VTS.Shared.Api.Middleware.Exceptions.ExceptionMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at VTS.Shared.Api.Middleware.ValidateRouteEntityIds.ValidateRouteEntityIdsMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at VTS.Shared.Api.Middleware.Authorization.AuthorizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at SimpleInjector.Integration.AspNetCore.RequestScopingStartupFilter.<ConfigureRequestScoping>b__3_0(HttpContext context, Func`1 next)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[15:22:44 ERR] Unexpected error occurred
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at VTS.Shared.Api.Middleware.Exceptions.ExceptionMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
[41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLUG0NTPANGU", Request id "0HLUG0NTPANGU:00000002": An unhandled exception was thrown by the application.
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at VTS.Shared.Api.Middleware.Exceptions.ExceptionMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at VTS.Shared.Api.Middleware.ValidateRouteEntityIds.ValidateRouteEntityIdsMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at VTS.Shared.Api.Middleware.Authorization.AuthorizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at SimpleInjector.Integration.AspNetCore.RequestScopingStartupFilter.<ConfigureRequestScoping>b__3_0(HttpContext context, Func`1 next)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[15:22:44 ERR] Unexpected error occurred
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at VTS.Shared.Api.Middleware.Exceptions.ExceptionMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
[41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLUG0NTPANH0", Request id "0HLUG0NTPANH0:00000001": An unhandled exception was thrown by the application.
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at VTS.Shared.Api.Middleware.Exceptions.ExceptionMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at VTS.Shared.Api.Middleware.ValidateRouteEntityIds.ValidateRouteEntityIdsMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at VTS.Shared.Api.Middleware.Authorization.AuthorizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at SimpleInjector.Integration.AspNetCore.RequestScopingStartupFilter.<ConfigureRequestScoping>b__3_0(HttpContext context, Func`1 next)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[15:28:39 ERR] Unexpected error occurred
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at VTS.Shared.Api.Middleware.Exceptions.ExceptionMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
[41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLUG0NTPANH3", Request id "0HLUG0NTPANH3:00000001": An unhandled exception was thrown by the application.
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at VTS.Shared.Api.Middleware.Exceptions.ExceptionMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at VTS.Shared.Api.Middleware.ValidateRouteEntityIds.ValidateRouteEntityIdsMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at VTS.Shared.Api.Middleware.Authorization.AuthorizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at SimpleInjector.Integration.AspNetCore.RequestScopingStartupFilter.<ConfigureRequestScoping>b__3_0(HttpContext context, Func`1 next)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[15:28:39 ERR] Unexpected error occurred
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at VTS.Shared.Api.Middleware.Exceptions.ExceptionMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
[41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLUG0NTPANH4", Request id "0HLUG0NTPANH4:00000001": An unhandled exception was thrown by the application.
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at VTS.Shared.Api.Middleware.Exceptions.ExceptionMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at VTS.Shared.Api.Middleware.ValidateRouteEntityIds.ValidateRouteEntityIdsMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at VTS.Shared.Api.Middleware.Authorization.AuthorizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at SimpleInjector.Integration.AspNetCore.RequestScopingStartupFilter.<ConfigureRequestScoping>b__3_0(HttpContext context, Func`1 next)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
[15:30:27 ERR] Unexpected error occurred
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at VTS.Shared.Api.Middleware.Exceptions.ExceptionMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
[41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLUG0NTPANH5", Request id "0HLUG0NTPANH5:00000001": An unhandled exception was thrown by the application.
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at VTS.Shared.Api.Middleware.Exceptions.ExceptionMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at VTS.Shared.Api.Middleware.ValidateRouteEntityIds.ValidateRouteEntityIdsMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at VTS.Shared.Api.Middleware.Authorization.AuthorizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at SimpleInjector.Integration.AspNetCore.RequestScopingStartupFilter.<ConfigureRequestScoping>b__3_0(HttpContext context, Func`1 next)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
`

**Comment by BruceForstall** [comment] 2020-04-02 18:24
@jkotas What do you think this is a codegen issue?

@jkotas @seiggy Is there a way to repro this? Or maybe a crash dump?

**Comment by jkotas** [comment] 2020-04-02 18:28
`InvalidProgramException` is typically thrown due the JIT failing to JIT the method.

It is possible that the root cause is somewhere else (e.g. the JIT gets a bad IL).

**Comment by jeremymclain** [comment] 2020-04-14 21:04
I just had an occurance of this with .NET Core 2.0. What's the likelihood

**Comment by seiggy** [comment] 2020-04-16 13:24
@BruceForstall I've not been able to reproduce this. Keep trying. It's completely random. Is there a way to trigger a crash dump from linux CLI for a running app? If so, next time I spot this happening, I'll trigger a crash dump and collect it before killing the container.

**Comment by seiggy** [comment] 2020-04-16 13:26
@jeremymclain Good question, all of our apps are still on 2.1 as well.

**Comment by BruceForstall** [comment] 2020-04-16 17:14
Enabling Linux core dumps varies by distro, I believe. here's an article that I found searching the web on how to do it: https://linux-audit.com/understand-and-configure-core-dumps-work-on-linux/.

**Comment by AndyAyersMS** [comment] 2020-04-29 19:22
@seiggy is your app using any third-party profilers by any chance?  If so, perhaps this is related to issues seen in #10459.

**Comment by seiggy** [comment] 2020-04-29 20:23
@AndyAyersMS - good catch, we do have Datadog running in the container which would be similar to AppInsights. Might be related.

**Comment by BruceForstall** [comment] 2020-06-02 00:51
This doesn't appear to be actionable, so I'm going to close this. Feel free to re-open if there is additional information, such as a dump, stack trace showing CLR on top of the stack, etc.

**Closed by BruceForstall** 2020-06-02 00:51 UTC
Labels: area-CodeGen-coreclr
