### ISSUE TITLE
NuGet restore failing with NullReferenceException

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#103823] opened 2024-06-21 15:50 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=715438
Build error leg or test failing: Build / windows-x64 release CrossDac / Build product
Pull request: https://github.com/dotnet/runtime/pull/103806

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorPattern": "NuGet.RestoreEx.targets.*: error : Object reference not set to an instance of an object.",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=715438
**Error message validated:** `[NuGet.RestoreEx.targets.*: error : Object reference not set to an instance of an object.`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 6/21/2024 3:51:17 PM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[2529303](https://dev.azure.com/dnceng/internal/_build/results?buildId=2529303)|dotnet-runtime|Build product|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2529303/logs/471)||
|[775106](https://dev.azure.com/dnceng-public/public/_build/results?buildId=775106)|dotnet/runtime|Build native test components|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/775106/logs/441)|dotnet/runtime#106218|
|[771952](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771952)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/771952/logs/795)|dotnet/runtime#106037|
|[771634](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771634)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/771634/logs/768)|dotnet/runtime#105771|
|[771585](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771585)|dotnet/runtime|Build managed test components|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/771585/logs/248)|dotnet/runtime#100294|
|[770038](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770038)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/770038/logs/893)|dotnet/runtime#106153|
|[769492](https://dev.azure.com/dnceng-public/public/_build/results?buildId=769492)|dotnet/runtime|Copy native test components to test output folder|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/769492/logs/664)|dotnet/runtime#106118|
|[769435](https://dev.azure.com/dnceng-public/public/_build/results?buildId=769435)|dotnet/runtime|Generate test wrappers|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/769435/logs/2106)||
|[767757](https://dev.azure.com/dnceng-public/public/_build/results?buildId=767757)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/767757/logs/312)|dotnet/runtime#105783|
|[767236](https://dev.azure.com/dnceng-public/public/_build/results?buildId=767236)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/767236/logs/1296)|dotnet/runtime#99596|
|[767175](https://dev.azure.com/dnceng-public/public/_build/results?buildId=767175)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/767175/logs/719)|dotnet/runtime#106013|
|[767109](https://dev.azure.com/dnceng-public/public/_build/results?buildId=767109)|dotnet/runtime|Generate test wrappers|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/767109/logs/822)|dotnet/runtime#106010|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|12|

**Comment by jkotas** [comment] 2024-06-21 19:45
Likely duplicate of https://github.com/dotnet/runtime/issues/103526

**Comment by jkotas** [comment] 2024-06-21 19:54
Stacktrace of the crash:
```
 Object reference not set to an instance of an object. [D:\a\_work\1\s\Build.proj]
    at System.Collections.Generic.Dictionary`2.FindValue(TKey key) [D:\a\_work\1\s\Build.proj]
    at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value) [D:\a\_work\1\s\Build.proj]
    at System.ComponentModel.ReflectTypeDescriptionProvider.GetTypeData(Type type, Boolean createIfNeeded) [D:\a\_work\1\s\Build.proj]
    at System.ComponentModel.TypeDescriptor.DefaultTypeDescriptor.GetAttributes() [D:\a\_work\1\s\Build.proj]
    at System.ComponentModel.TypeDescriptor.GetAttributes(Type componentType) [D:\a\_work\1\s\Build.proj]
    at System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetAttributes() [D:\a\_work\1\s\Build.proj]
    at System.ComponentModel.TypeDescriptor.DefaultTypeDescriptor.GetAttributes() [D:\a\_work\1\s\Build.proj]
    at System.ComponentModel.TypeDescriptor.GetAttributes(Type componentType) [D:\a\_work\1\s\Build.proj]
    at System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetConverter(Object instance, Boolean verifyIsRegisteredType) [D:\a\_work\1\s\Build.proj]
    at System.ComponentModel.TypeDescriptor.DefaultTypeDescriptor.GetConverter() [D:\a\_work\1\s\Build.proj]
    at System.ComponentModel.TypeDescriptor.GetConverter(Type type) [D:\a\_work\1\s\Build.proj]
    at Newtonsoft.Json.Serialization.JsonTypeReflector.CanTypeDescriptorConvertString(Type type, TypeConverter& typeConverter) [D:\a\_work\1\s\Build.proj]
    at Newtonsoft.Json.Serialization.DefaultContractResolver.CanConvertToString(Type type) [D:\a\_work\1\s\Build.proj]
    at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType) [D:\a\_work\1\s\Build.proj]
    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory) [D:\a\_work\1\s\Build.proj]
    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) [D:\a\_work\1\s\Build.proj]
    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) [D:\a\_work\1\s\Build.proj]
    at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader) [D:\a\_work\1\s\Build.proj]
    at NuGet.Packaging.NupkgMetadataFileFormat.Read(TextReader reader, ILogger log, String path) [D:\a\_work\1\s\Build.proj]
    at NuGet.Packaging.NupkgMetadataFileFormat.Read(TextReader reader, ILogger log, String path) [D:\a\_work\1\s\Build.proj]
    at NuGet.Packaging.NupkgMetadataFileFormat.Read(Stream stream, ILogger log, String path) [D:\a\_work\1\s\Build.proj]
    at NuGet.Packaging.NupkgMetadataFileFormat.<>c__DisplayClass6_0.<Read>b__0(FileStream stream, String nupkgMetadataFilePath) [D:\a\_work\1\s\Build.proj]
    at NuGet.Common.FileUtility.SafeRead[T](String filePath, Func`3 read) [D:\a\_work\1\s\Build.proj]
    at NuGet.Packaging.NupkgMetadataFileFormat.Read(String filePath, ILogger log) [D:\a\_work\1\s\Build.proj]
    at NuGet.Packaging.NupkgMetadataFileFormat.Read(String filePath) [D:\a\_work\1\s\Build.proj]
    at NuGet.Protocol.LocalPackageFileCache.<>c__DisplayClass9_0.<GetOrAddSha512>b__1() [D:\a\_work\1\s\Build.proj]
    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode) [D:\a\_work\1\s\Build.proj]
 --- End of stack trace from previous location --- [D:\a\_work\1\s\Build.proj]
    at System.Lazy`1.CreateValue() [D:\a\_work\1\s\Build.proj]
    at NuGet.Commands.LockFileBuilder.CreateLockFile(LockFile previousLockFile, PackageSpec project, IEnumerable`1 targetGraphs, IReadOnlyList`1 localRepositories, RemoteWalkContext context, LockFileBuilderCache lockFileBuilderCache) [D:\a\_work\1\s\Build.proj]
    at NuGet.Commands.RestoreCommand.BuildAssetsFile(LockFile existingLockFile, PackageSpec project, IEnumerable`1 graphs, IReadOnlyList`1 localRepositories, RemoteWalkContext contextForProject) [D:\a\_work\1\s\Build.proj]
    at NuGet.Commands.RestoreCommand.ExecuteAsync(CancellationToken token) [D:\a\_work\1\s\Build.proj]
    at NuGet.Commands.RestoreRunner.ExecuteAsync(RestoreSummaryRequest summaryRequest, CancellationToken token) [D:\a\_work\1\s\Build.proj]
    at NuGet.Commands.RestoreRunner.ExecuteAndCommitAsync(RestoreSummaryRequest summaryRequest, IRestoreProgressReporter progressReporter, CancellationToken token) [D:\a\_work\1\s\Build.proj]
    at NuGet.Commands.RestoreRunner.ExecuteAndCommitAsync(RestoreSummaryRequest summaryRequest, IRestoreProgressReporter progressReporter, CancellationToken token) [D:\a\_work\1\s\Build.proj]
    at NuGet.Commands.RestoreRunner.CompleteTaskAsync(List`1 restoreTasks) [D:\a\_work\1\s\Build.proj]
    at NuGet.Commands.RestoreRunner.RunAsync(IEnumerable`1 restoreRequests, RestoreArgs restoreArgs, CancellationToken token) [D:\a\_work\1\s\Build.proj]
    at NuGet.Commands.RestoreRunner.RunAsync(RestoreArgs restoreContext, CancellationToken token) [D:\a\_work\1\s\Build.proj]
    at NuGet.Build.Tasks.BuildTasksUtility.RestoreAsync(DependencyGraphSpec dependencyGraphSpec, Boolean interactive, Boolean recursive, Boolean noCache, Boolean ignoreFailedSources, Boolean disableParallel, Boolean force, Boolean forceEvaluate, Boolean hideWarningsAndErrors, Boolean restorePC, Boolean cleanupAssetsForUnsupportedProjects, ILogger log, CancellationToken cancellationToken) [D:\a\_work\1\s\Build.proj]
```
cc @steveharter

**Comment by jkotas** [comment] 2024-07-02 21:46
Hit again in: https://dev.azure.com/dnceng-public/public/_build/results?buildId=728032&view=logs&j=a1e5d03d-3f6b-54a5-7792-bf65a0588cb6&t=67e8736e-0339-547f-63a6-bb9e4e553d48&l=104

**Comment by jkotas** [comment] 2024-07-02 21:49
@steveharter Could you please take a look? It is hit multiple times per day in the CI

**Comment by steveharter** [comment] 2024-07-08 17:08
Re-opening for a few days to track any new hits after the fix went in.

**Comment by stephentoub** [comment] 2024-07-23 21:10
> Re-opening for a few days to track any new hits after the fix; this fix needs to be available on the build machines. [@ViktorHofer](https://github.com/ViktorHofer)

We're still getting hits, but that appears to be from older SDK versions, e.g. `.dotnet\sdk\9.0.100-preview.5.24307.3\NuGet.RestoreEx.targets`. What needs to be updated where for the fix to propagate everywhere it's needed?

**Comment by ericstj** [comment] 2024-08-06 15:51
We are on the Preview6 SDK in main now for 2 weeks: https://github.com/dotnet/runtime/commit/4a8aca8bc748888423686beeccd233ee2f6a9f76

I do see some folks still hitting this on preview6
https://dev.azure.com/dnceng-public/public/_build/results?buildId=767175&view=logs&j=f979b8ec-ebd4-511f-1076-61f8eccd76f8&t=4539cfc2-b7a3-5dcb-c27b-36c97fdb9947&l=5649

I see @steveharter's change https://github.com/dotnet/runtime/commit/670d11f4d30d16153a3f5a667b1bb5b5ced9e0c9 only went into Preview7.

We should try updating to Preview7 to see if that resolves these issues.

**Comment by steveharter** [comment] 2024-08-13 16:01
Preview7 PR: https://github.com/dotnet/runtime/pull/106333

**Comment by steveharter** [comment] 2024-09-03 14:05
Closing; the 7-day hit count had one [hit](https://dev.azure.com/dnceng/internal/_build/results?buildId=2529303), but appears unrelated:
```
2024-09-02T11:45:39.4477530Z   Restored /Users/runner/work/1/s/src/libraries/Microsoft.Extensions.Caching.Memory/src/Microsoft.Extensions.Caching.Memory.csproj (in 255 ms).
2024-09-02T11:45:39.4763880Z   Restored /Users/runner/work/1/s/src/libraries/Microsoft.Bcl.TimeProvider/src/Microsoft.Bcl.TimeProvider.csproj (in 272 ms).
2024-09-02T11:45:39.4951230Z   Restored /Users/runner/work/1/s/src/libraries/Microsoft.Extensions.Caching.Abstractions/src/Microsoft.Extensions.Caching.Abstractions.csproj (in 301 ms).
2024-09-02T11:45:39.5382380Z   Restored /Users/runner/work/1/s/src/libraries/Microsoft.Bcl.Numerics/src/Microsoft.Bcl.Numerics.csproj (in 296 ms).
2024-09-02T11:45:39.5402710Z   Restored /Users/runner/work/1/s/src/libraries/Microsoft.Bcl.AsyncInterfaces/src/Microsoft.Bcl.AsyncInterfaces.csproj (in 263 ms).
2024-09-02T11:45:39.5813560Z   Restored /Users/runner/work/1/s/src/libraries/Microsoft.Bcl.Cryptography/src/Microsoft.Bcl.Cryptography.csproj (in 311 ms).
2024-09-02T11:45:39.6105820Z /Users/runner/work/1/s/.dotnet/sdk/9.0.100-preview.7.24407.12/NuGet.RestoreEx.targets(19,5): error : Object reference not set to an instance of an object. [/Users/runner/work/1/s/Build.proj]
2024-09-02T11:45:39.6107360Z /Users/runner/work/1/s/.dotnet/sdk/9.0.100-preview.7.24407.12/NuGet.RestoreEx.targets(19,5): error :    at NuGet.NoAllocEnumerateExtensions.OptimisticallyNonAllocatingEnumerable`1.Enumerator..ctor(IEnumerable`1 source) [/Users/runner/work/1/s/Build.proj]
2024-09-02T11:45:39.6109290Z /Users/runner/work/1/s/.dotnet/sdk/9.0.100-preview.7.24407.12/NuGet.RestoreEx.targets(19,5): error :    at NuGet.Commands.PackageSpecificWarningProperties.AddRangeOfCodes(IEnumerable`1 codes, String libraryId, NuGetFramework framework) [/Users/runner/work/1/s/Build.proj]
2024-09-02T11:45:39.6110610Z /Users/runner/work/1/s/.dotnet/sdk/9.0.100-preview.7.24407.12/NuGet.RestoreEx.targets(19,5): error :    at NuGet.Commands.PackageSpecificWarningProperties.CreatePackageSpecificWarningProperties(PackageSpec packageSpec) [/Users/runner/work/1/s/Build.proj]
2024-09-02T11:45:39.6111680Z /Users/runner/work/1/s/.dotnet/sdk/9.0.100-preview.7.24407.12/NuGet.RestoreEx.targets(19,5): error :    at NuGet.Commands.RestoreCommand..ctor(RestoreRequest request) [/Users/runner/work/1/s/Build.proj]
2024-09-02T11:45:39.6112540Z /Users/runner/work/1/s/.dotnet/sdk/9.0.100-preview.7.24407.12/NuGet.RestoreEx.targets(19,5): error :    at NuGet.Commands.RestoreRunner.ExecuteAsync(RestoreSummaryRequest summaryRequest, CancellationToken token) [/Users/runner/work/1/s/Build.proj]
2024-09-02T11:45:39.6113010Z /Users/runner/work/1/s/.dotnet/sdk/9.0.100-preview.7.24407.12/NuGet.RestoreEx.targets(19,5): error :    at NuGet.Commands.RestoreRunner.ExecuteAndCommitAsync(RestoreSummaryRequest summaryRequest, IRestoreProgressReporter progressReporter, CancellationToken token) [/Users/runner/work/1/s/Build.proj]
2024-09-02T11:45:39.6113570Z /Users/runner/work/1/s/.dotnet/sdk/9.0.100-preview.7.24407.12/NuGet.RestoreEx.targets(19,5): error :    at NuGet.Commands.RestoreRunner.CompleteTaskAsync(List`1 restoreTasks) [/Users/runner/work/1/s/Build.proj]
2024-09-02T11:45:39.6114010Z /Users/runner/work/1/s/.dotnet/sdk/9.0.100-preview.7.24407.12/NuGet.RestoreEx.targets(19,5): error :    at NuGet.Commands.RestoreRunner.RunAsync(IEnumerable`1 restoreRequests, RestoreArgs restoreArgs, CancellationToken token) [/Users/runner/work/1/s/Build.proj]
2024-09-02T11:45:39.6114520Z /Users/runner/work/1/s/.dotnet/sdk/9.0.100-preview.7.24407.12/NuGet.RestoreEx.targets(19,5): error :    at NuGet.Commands.RestoreRunner.RunAsync(RestoreArgs restoreContext, CancellationToken token) [/Users/runner/work/1/s/Build.proj]
2024-09-02T11:45:39.6115210Z /Users/runner/work/1/s/.dotnet/sdk/9.0.100-preview.7.24407.12/NuGet.RestoreEx.targets(19,5): error :    at NuGet.Build.Tasks.BuildTasksUtility.RestoreAsync(DependencyGraphSpec dependencyGraphSpec, Boolean interactive, Boolean recursive, Boolean noCache, Boolean ignoreFailedSources, Boolean disableParallel, Boolean force, Boolean forceEvaluate, Boolean hideWarningsAndErrors, Boolean restorePC, Boolean cleanupAssetsForUnsupportedProjects, ILogger log, CancellationToken cancellationToken) [/Users/runner/work/1/s/Build.proj]
2024-09-02T11:45:39.6116010Z /Users/runner/work/1/s/.dotnet/sdk/9.0.100-preview.7.24407.12/NuGet.RestoreEx.targets(19,5): error :    at NuGet.Build.Tasks.Console.MSBuildStaticGraphRestore.RestoreAsync(String entryProjectFilePath, IDictionary`2 globalProperties, IReadOnlyDictionary`2 options) [/Users/runner/work/1/s/Build.proj]
2024-09-02T11:45:39.6207600Z ##[error].dotnet/sdk/9.0.100-preview.7.24407.12/NuGet.RestoreEx.targets(19,5): error : (NETCORE_ENGINEERING_TELEMETRY=Restore) Object reference not set to an instance of an object.
   at NuGet.NoAllocEnumerateExtensions.OptimisticallyNonAllocatingEnumerable`1.Enumerator..ctor(IEnumerable`1 source)
   at NuGet.Commands.PackageSpecificWarningProperties.AddRangeOfCodes(IEnumerable`1 codes, String libraryId, NuGetFramework framework)
   at NuGet.Commands.PackageSpecificWarningProperties.CreatePackageSpecificWarningProperties(PackageSpec packageSpec)
   at NuGet.Commands.RestoreCommand..ctor(RestoreRequest request)
   at NuGet.Commands.RestoreRunner.ExecuteAsync(RestoreSummaryRequest summaryRequest, CancellationToken token)
   at NuGet.Commands.RestoreRunner.ExecuteAndCommitAsync(RestoreSummaryRequest summaryRequest, IRestoreProgressReporter progressReporter, CancellationToken token)
   at NuGet.Commands.RestoreRunner.CompleteTaskAsync(List`1 restoreTasks)
   at NuGet.Commands.RestoreRunner.RunAsync(IEnumerable`1 restoreRequests, RestoreArgs restoreArgs, CancellationToken token)
   at NuGet.Commands.RestoreRunner.RunAsync(RestoreArgs restoreContext, CancellationToken token)
   at NuGet.Build.Tasks.BuildTasksUtility.RestoreAsync(DependencyGraphSpec dependencyGraphSpec, Boolean interactive, Boolean recursive, Boolean noCache, Boolean ignoreFailedSources, Boolean disableParallel, Boolean force, Boolean forceEvaluate, Boolean hideWarningsAndErrors, Boolean restorePC, Boolean cleanupAssetsForUnsupportedProjects, ILogger log, CancellationToken cancellationToken)
   at NuGet.Build.Tasks.Console.MSBuildStaticGraphRestore.RestoreAsync(String entryProjectFilePath, IDictionary`2 globalProperties, IReadOnlyDictionary`2 options)
2024-09-02T11:45:39.6582770Z 
2024-09-02T11:45:39.6587500Z Build FAILED.
2024-09-02T11:45:39.6587570Z 
2024-09-02T11:45:39.6588000Z /Users/runner/work/1/s/.dotnet/sdk/9.0.100-preview.7.24407.12/NuGet.RestoreEx.targets(19,5): error : Object reference not set to an instance of an object. [/Users/runner/work/1/s/Build.proj]
2024-09-02T11:45:39.6588560Z /Users/runner/work/1/s/.dotnet/sdk/9.0.100-preview.7.24407.12/NuGet.RestoreEx.targets(19,5): error :    at NuGet.NoAllocEnumerateExtensions.OptimisticallyNonAllocatingEnumerable`1.Enumerator..ctor(IEnumerable`1 source) [/Users/runner/work/1/s/Build.proj]
2024-09-02T11:45:39.6589160Z /Users/runner/work/1/s/.dotnet/sdk/9.0.100-preview.7.24407.12/NuGet.RestoreEx.targets(19,5): error :    at NuGet.Commands.PackageSpecificWarningProperties.AddRangeOfCodes(IEnumerable`1 codes, String libraryId, NuGetFramework framework) [/Users/runner/work/1/s/Build.proj]
2024-09-02T11:45:39.6589670Z /Users/runner/work/1/s/.dotnet/sdk/9.0.100-preview.7.24407.12/NuGet.RestoreEx.targets(19,5): error :    at NuGet.Commands.PackageSpecificWarningProperties.CreatePackageSpecificWarningProperties(PackageSpec packageSpec) [/Users/runner/work/1/s/Build.proj]
2024-09-02T11:45:39.6590060Z /Users/runner/work/1/s/.dotnet/sdk/9.0.100-preview.7.24407.12/NuGet.RestoreEx.targets(19,5): error :    at NuGet.Commands.RestoreCommand..ctor(RestoreRequest request) [/Users/runner/work/1/s/Build.proj]
2024-09-02T11:45:39.6590510Z /Users/runner/work/1/s/.dotnet/sdk/9.0.100-preview.7.24407.12/NuGet.RestoreEx.targets(19,5): error :    at NuGet.Commands.RestoreRunner.ExecuteAsync(RestoreSummaryRequest summaryRequest, CancellationToken token) [/Users/runner/work/1/s/Build.proj]
2024-09-02T11:45:39.6590920Z /Users/runner/work/1/s/.dotnet/sdk/9.0.100-preview.7.24407.12/NuGet.RestoreEx.targets(19,5): error :    at NuGet.Commands.RestoreRunner.ExecuteAndCommitAsync(RestoreSummaryRequest summaryRequest, IRestoreProgressReporter progressReporter, CancellationToken token) [/Users/runner/work/1/s/Build.proj]
2024-09-02T11:45:39.6591400Z /Users/runner/work/1/s/.dotnet/sdk/9.0.100-preview.7.24407.12/NuGet.RestoreEx.targets(19,5): error :    at NuGet.Commands.RestoreRunner.CompleteTaskAsync(List`1 restoreTasks) [/Users/runner/work/1/s/Build.proj]
2024-09-02T11:45:39.6591770Z /Users/runner/work/1/s/.dotnet/sdk/9.0.100-preview.7.24407.12/NuGet.RestoreEx.targets(19,5): error :    at NuGet.Commands.RestoreRunner.RunAsync(IEnumerable`1 restoreRequests, RestoreArgs restoreArgs, CancellationToken token) [/Users/runner/work/1/s/Build.proj]
2024-09-02T11:45:39.6592660Z /Users/runner/work/1/s/.dotnet/sdk/9.0.100-preview.7.24407.12/NuGet.RestoreEx.targets(19,5): error :    at NuGet.Commands.RestoreRunner.RunAsync(RestoreArgs restoreContext, CancellationToken token) [/Users/runner/work/1/s/Build.proj]
2024-09-02T11:45:39.6593900Z /Users/runner/work/1/s/.dotnet/sdk/9.0.100-preview.7.24407.12/NuGet.RestoreEx.targets(19,5): error :    at NuGet.Build.Tasks.BuildTasksUtility.RestoreAsync(DependencyGraphSpec dependencyGraphSpec, Boolean interactive, Boolean recursive, Boolean noCache, Boolean ignoreFailedSources, Boolean disableParallel, Boolean force, Boolean forceEvaluate, Boolean hideWarningsAndErrors, Boolean restorePC, Boolean cleanupAssetsForUnsupportedProjects, ILogger log, CancellationToken cancellationToken) [/Users/runner/work/1/s/Build.proj]
2024-09-02T11:45:39.6594560Z /Users/runner/work/1/s/.dotnet/sdk/9.0.100-preview.7.24407.12/NuGet.RestoreEx.targets(19,5): error :    at NuGet.Build.Tasks.Console.MSBuildStaticGraphRestore.RestoreAsync(String entryProjectFilePath, IDictionary`2 globalProperties, IReadOnlyDictionary`2 options) [/Users/runner/work/1/s/Build.proj]
2024-09-02T11:45:39.6594860Z     0 Warning(s)
2024-09-02T11:45:39.6594940Z     1 Error(s)
```

**Closed by steveharter** 2024-09-03 14:05 UTC
Labels: bug, area-Infrastructure-libraries, blocking-clean-ci, Known Build Error

**Comment by steveharter** [comment] 2024-09-04 17:03
Created this issue to track the above NuGet issue for `OptimisticallyNonAllocatingEnumerable`1.Enumerator..ctor`: https://github.com/dotnet/runtime/issues/107361
