### ISSUE TITLE
[API Proposal]: Code analyse rule that require passing of cancellation token

### ISSUE THREAD

**Issue by jarlef** [dotnet/runtime#82889] opened 2023-03-02 12:25 UTC
### Background and motivation

The rule `CA2016` checks that any in scope cancellation token must be forwarded, but if the current method does not have a cancellation token there rule does result in a violation

```csharp
public async Task Foo(CancellationToken token) 
{
  await SomeMethodThatAcceptsCancellationToken(); // CA2016 violation
}

public async Task Bar() 
{
  await SomeMethodThatAcceptsCancellationToken(); // no violation
}
```

This can be hard to identify that the cancellation token is not forwarded down the stack as it should have been since the second method does not accept a token as a input parameter. There should be a even more strict rule that requires the forwarding of the cancellation token or to use `CancellationToken.None` if the cancellation token is not need / available. 

```csharp
public async Task Bar() 
{
  await SomeMethodThatAcceptsCancellationToken(CancellationToken.None);
}
```

This will make it easier to maintain the code and also perform code reviews on the use of cancellation tokens if the code base.

### API Proposal

```csharp
public async Task Bar() 
{
  await SomeMethodThatAcceptsCancellationToken(); // CA20XX violation
}
```

### API Usage

```csharp
public async Task Bar() 
{
  await SomeMethodThatAcceptsCancellationToken(); // CA20XX violation
}
```

**Comment by stephentoub** [comment] 2023-03-02 12:29
Thanks. This is largely a duplicate of https://github.com/dotnet/runtime/issues/78397, which proposes a rule that async methods should accept a token. I'm less inclined to have a rule about calls that aren't passed a token and don't have one to pass, as that's really just a stylistic choice as to whether to use the implicit default token or the explicit default token with None.

**Comment by Pentadome** [comment] 2023-03-02 13:53
[This rule already exists.](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2016)

```editorconfig
# CA2016: Forward the 'CancellationToken' parameter to methods
dotnet_diagnostic.CA2016.severity = warning
```

**Closed** 2023-06-07 11:32 UTC
Labels: api-suggestion, area-System.Threading.Tasks, untriaged
