### ISSUE TITLE
[3.1] [Linux] Writing a file that takes you over the storage quota in Azure file storage silently fails

### ISSUE THREAD

**Issue by flin-8** [dotnet/runtime#42360] opened 2020-09-17 01:59 UTC
### Description

When using `File.Copy()` in Linux to write a file that takes you over the storage quota in Azure file storage, the write silently fails while leaving behind a truncated file.

- Repeating this on Windows throws an IOException (as expected) and doesn't leave a file behind. Stack trace:
```
System.IO.IOException: There is not enough space on the disk. : '\\xxx.file.core.windows.net\test\ReproFile'
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
```

- Copying the file via `cp` in Linux also errors with `failed to close 'xxx': No space left on device`

This problem only occurs in dotnet on Linux (reproduced on Debian 10, Ubuntu 18 & 20).

A related issue is that when running on this container `mcr.microsoft.com/dotnet/core/runtime-deps:3.1` in Azure Kubernetes Service (AKS) and Ubuntu 18.04, the length of the file reported by `FIleInfo` is the untruncated size, which is wrong.

![image](https://user-images.githubusercontent.com/2888279/93410018-8a4c3d80-f8db-11ea-9aa5-683b9f07b197.png)

### Reproduction

I have a console app at https://github.com/OctopusDeploy/AzureFileStorageRepro which will help with a minimal reproduction. 

### Configuration

Dotnet: v3.1.401
Windows 10: v10.0.19041.508
Linux distro's: Debian 10, Ubuntu 18.04, Ubuntu 20.04
Architecture: x64

### Regression?

Unknown

### Other information

I've previously logged an issue with Azure, which is suggesting that the problem might be closer to the dotnet runtime.
![image](https://user-images.githubusercontent.com/2888279/93409718-d64ab280-f8da-11ea-94a5-14d44c5582f3.png)

Screenshot of an Azure storage file share:
![image](https://user-images.githubusercontent.com/2888279/93409471-54f32000-f8da-11ea-93a1-c560aff6c767.png)

**Comment by danmosemsft** [comment] 2020-09-17 02:10
This looks like it may be https://github.com/dotnet/runtime/pull/38742 
Can you please try with 5.0 RC1?

**Comment by flin-8** [comment] 2020-09-17 03:49
Hi @danmosemsft ,

Yes 5.0 RC1 does fix this - thank you for the pointer. 

Is there any appetite to backport this fix to 3.1? This is hurting us as we are now getting corrupt files randomly.

**Comment by danmosemsft** [comment] 2020-09-17 04:10
Thanks for the info. We were waiting for customer evidence (I think). ... thoughts about risk here @carlossanlop ?

**Comment by danmosemsft** [comment] 2020-09-17 04:12
Just curious @flin-8 are you likely to update to 5.0 when it ships in 2 months?

**Comment by flin-8** [comment] 2020-09-17 06:22
> Just curious @flin-8 are you likely to update to 5.0 when it ships in 2 months?

@danmosemsft the short answer is no.

The long answer is we will need to plan for the update and dedicate some time to stabilize and address any regressions arising from it. We only upgraded to 3.1 at the start of the year, so there's no definite timeframe for that at the moment.

**Comment by danmosemsft** [comment] 2020-09-17 06:27
@flin-8 i fully understand. We’ll evaluate a port

**Comment by carlossanlop** [comment] 2020-09-17 18:38
I think we can get this ported, I'll work on this today.

The involved code did not change between 5.0 and 3.1 (`FileStream.Dispose` and `SafeFileHandle.ReleaseHandle`). The only difference is that the fix lives in coreclr, and the manual tests in corefx, so I would have to submit two changes.

**Comment by carlossanlop** [comment] 2020-09-17 22:43
@flin-8 I have a local fix for 3.1, see attached zip file.
Would you mind testing the DLL in your Linux x64 environment and letting us know if it worked?

Backup the original System.Private.CoreLib.dll located in this folder: `$DOTNETINSTALL/shared/Microsoft.NETCore.App/3.1.0/System.Private.CoreLib.dll`

Then extract the one in the zip file into that location.

[System.Private.CoreLib.dll.zip](https://github.com/dotnet/runtime/files/5242275/System.Private.CoreLib.dll.zip)

**Comment by flin-8** [comment] 2020-09-17 23:03
> @flin-8 I have a local fix for 3.1, see attached zip file.
> Would you mind testing the DLL in your Linux x64 environment and letting us know if it worked?
> 
> Backup the original System.Private.CoreLib.dll located in this folder: `$DOTNETINSTALL/shared/Microsoft.NETCore.App/3.1.0/System.Private.CoreLib.dll`
> 
> Then extract the one in the zip file into that location.
> 
> [System.Private.CoreLib.dll.zip](https://github.com/dotnet/runtime/files/5242275/System.Private.CoreLib.dll.zip)

Yes the repro program is now throwing
![image](https://user-images.githubusercontent.com/2888279/93536916-87118a00-f98d-11ea-965c-bc1c28f0d1d8.png)

One more thing I'm not sure about: is `File.Copy()` meant to clean up when it sees an error? It's leaving the file behind in Linux (running in Windows doesn't leave the file behind)

**Comment by carlossanlop** [comment] 2020-09-17 23:09
No, the fix is not expected to delete the file if the exception is thrown. This is also the expected behavior in 5.0. The user should capture the exception and decide what to do with the file.

**Comment by carlossanlop** [comment] 2020-09-18 18:29
Since this is already fixed in 5.0 and master, and we just need to backport to 3.1, I'll add the `Future` label.

**Comment by danmosemsft** [comment] 2020-09-24 04:55
@carlossanlop i guess we can close now?

**Comment by carlossanlop** [comment] 2020-09-28 18:07
Closing. It's been backported to 3.1: https://github.com/dotnet/corefx/pull/42988

**Closed by carlossanlop** 2020-09-28 18:07 UTC
Labels: area-System.IO

**Comment by flin-8** [comment] 2020-09-28 23:56
Thanks guys, appreciate it!

**Comment by flin-8** [comment] 2020-10-29 03:29
@danmosemsft Do you know roughly when the 3.1 patch will be released?

**Comment by danmosemsft** [comment] 2020-10-29 03:34
It should be in 3.1.9, which was released earlier this month. https://github.com/dotnet/core/blob/master/release-notes/3.1/3.1.9/3.1.9.md
