### ISSUE TITLE
if using System.Numerics.Vector.IsHardwareAccelerated return false but the code into if statement 

### ISSUE THREAD

**Issue by tangyanzhi** [dotnet/runtime#87537] opened 2023-06-14 01:12 UTC
### Description

using System.Numerics;
static void Main(string[] args)
 {
      if (Vector.IsHardwareAccelerated)
      {
            int a = 10;
      }
      else
      {
          int b =10;
      }
}

when if Vector.IsHardwareAccelerated return false, But inside Visual Studio 2022 debug or run this code ,It will go into if statement inside，Instead of go into else statement.

### Reproduction Steps

See description above.

### Expected behavior

  if (Vector.IsHardwareAccelerated) == false You should jump to else instead of executing it directly inside if

### Actual behavior

  if (Vector.IsHardwareAccelerated) == false It was executed directly inside the if

### Regression?

No response

### Known Workarounds

应该是Visual Studio 2022的问题，但是不确定，看汇编代码它返回的是1，但是VS2022调试上，它则是false。

### Configuration

..NET SDK:
 Version:   8.0.100-preview.3.23178.7
 Commit:    e300b0e1e6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.3.23178.7\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.0-preview.3.23174.8
  Architecture: x64
  Commit:       47bad717bd

.NET SDKs installed:
  7.0.100 [C:\Program Files\dotnet\sdk]
  7.0.302 [C:\Program Files\dotnet\sdk]
  8.0.100-preview.3.23178.7 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.3.23177.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.3.23174.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.3.23178.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by huoyaoyuan** [comment] 2023-06-14 03:02
![image](https://github.com/dotnet/runtime/assets/5644458/2a880697-4e9e-4e72-a169-867b79f065ee)

You are right that debugger can't correctly inspect the value of `IsHardwareAccelerated`.

**Comment by tannergooding** [comment] 2023-06-14 15:49
This was meant to be fixed with https://github.com/dotnet/runtime/pull/69578 very early in .NET 8 and does not reproduce in .NET 8 Preview 5.

I'd guess its showing up in .NET 8 Preview 3 for `Vector<T>` due to a quirk in the crossgen handling that was recently fixed.

**Closed** 2023-06-26 00:27 UTC
Labels: area-System.Numerics, needs-author-action

**Comment by tangyanzhi** [comment] 2023-06-26 21:27
> This was meant to be fixed with #69578 very early in .NET 8 and does not reproduce in .NET 8 Preview 5.
> 
> I'd guess its showing up in .NET 8 Preview 3 for `Vector<T>` due to a quirk in the crossgen handling that was recently fixed.


Ok, thanks for the answer. It turns out that this problem has long existed
