### ISSUE TITLE
[API Proposal]: Consider support for `\U` escape sequence in `Regex`

### ISSUE THREAD

**Issue by dahlia** [dotnet/runtime#98341] opened 2024-02-13 06:53 UTC
### Background and motivation

Currently, the grammar of `System.Text.RegularExpressions.Regex` supports nearly all [escape sequences supported by C# string literals][1] (e.g., `\r`, `\n`, <code>\x<var>HH</var></code>, <code>\u<var>HHHH</var></code>), except for the <code>\U00<var>HHHHHH</var></code> notation for representing code points in the UTF-32 area. It would be nice to support the <code>\U00<var>HHHHHH</var></code> notation to represent a wider range of character classes and more.

[1]: https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/strings/#string-escape-sequences

### API Proposal

Follow the capitalized `\U` notation within C# string literals. The first three digits are fixed to zero, so that they can represent code points between U+00000 and U+10FFFF. The hexadecimal digits following the `\U` is case-insensitive.

### API Usage

```csharp
new System.Text.RegularExpressions.Regex(@"[\U00010000-\U000effff]")
```

**Comment by stephentoub** [comment] 2024-02-13 12:37
This isn't really something that can be done on its own. Regex only looks at one System.Char at a time and doesn't consider the possibility that multiple chars represent a single value. Addressing that more broadly is tracked by https://github.com/dotnet/runtime/issues/16922. This issue can't really stand alone from that, eg your character class example wouldn't work today even if the syntax were understood and expanded to be the resulting chars.

**Comment by steveharter** [comment] 2024-02-14 21:07
Closing as duplicate, or at least partial duplicate of https://github.com/dotnet/runtime/issues/16922.

**Closed by steveharter** 2024-02-14 21:07 UTC
Labels: api-suggestion, area-System.Text.RegularExpressions
