### ISSUE TITLE
Memory leaks when reverse P/Invoke is called from unmanaged thread

### ISSUE THREAD

**Issue by AkiSakurai** [dotnet/runtime#64509] opened 2022-01-30 10:35 UTC
### Description

The  function below is creating native threads to call managed function.
The memory consumption is increasing steadily.
``` c#
using System.Runtime.InteropServices;

namespace Leak {
    class Leak
    {
        [DllImport("libpthread.so.0")]
        public static extern int pthread_create(out nuint thread, IntPtr attr, IntPtr start_routine, IntPtr arg);
        
        [DllImport("libpthread.so.0")]
        public static extern int pthread_join(nuint thread, IntPtr retval);

        [UnmanagedCallersOnly]
        static private IntPtr Callback(IntPtr arg)
        {
            return IntPtr.Zero;
        }

        static void Main(string[] args)
        {
            unsafe {
                var count = 0;
                while(true) 
                {
                    var n = 2000;
                    for(int i = 0; i < n ; i++) 
                    {
                        nuint thread;
                        delegate* unmanaged <IntPtr, IntPtr> fp = &Callback;
                        pthread_create(out thread, IntPtr.Zero, (IntPtr)fp, IntPtr.Zero);
                        pthread_join(thread, IntPtr.Zero);
                    }
                    count += n;
                    Console.WriteLine($"{count} calls");
                    GC.Collect();
                }
            }
        }
    }
}

```

### Configuration

Ubuntu 21.10
dotnet core 6.0.1

### Data
![leak](https://user-images.githubusercontent.com/75532970/151695967-10a3d11e-5076-43c6-9974-352cbb92dc5f.png)

**Comment by jkotas** [comment] 2022-01-30 13:08
This looks like a regression introduced by https://github.com/dotnet/runtime/pull/43423 . Duplicate of https://github.com/dotnet/runtime/issues/60566.

@janvorli root caused it in https://github.com/dotnet/runtime/pull/43423#issuecomment-950035547 . 

We need to explicitly touch `tls_destructionMonitor` when the new thread gets attached to the runtime, similar to how it is done in NativeAOT  https://github.com/dotnet/runtime/blob/d4f06a9c524819dfd1345745a17b3cc6e060ba8b/src/coreclr/nativeaot/Runtime/unix/PalRedhawkUnix.cpp#L479 .

@VSadov We will need to get a fix for this pushed to .NET 6 servicing. Could you please take care of it?

**Comment by VSadov** [comment] 2022-01-31 02:52
Will take a look. Yes, most likely touching `tls_destructionMonitor` will fix this.

**Comment by VSadov** [comment] 2022-03-09 19:55
Fixed in https://github.com/dotnet/runtime/pull/65406

**Closed by VSadov** 2022-03-09 19:55 UTC
Labels: bug, tenet-performance, area-Interop-coreclr, regression-from-last-release
