### ISSUE TITLE
JsonSerializer.Deserialize doesn't handle UTF8 BOM for strings or byte[]

### ISSUE THREAD

**Issue by ChrisHimsworth** [dotnet/runtime#37327] opened 2020-06-02 22:24 UTC
### Description
I came across an issue when subscribing to Azure Service Bus messages and passing the Message.Body into `System.Text.Json.JsonSerializer.Deserialize`.

The exception thrown is:
`System.Text.Json.JsonException : '0xEF' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.`

If you refer to [JsonSerializerTests.cs](https://github.com/ChrisHimsworth/DotNetCoreJsonSerializer/blob/master/JsonSerializerTests.cs), there are 2 failing tests, _DeserializeFromStringWithBOM_ and _DeserializeFromBytesWithBOM_, which show how to reproduce the issue.

I would expect that the `System.Text.Json.JsonSerializer.Deserialize` would handle a `string` or `byte[]` with or without a Byte Order Mark as per `System.Text.Json.JsonSerializer.DeserializeAsync(Stream)`.

### Configuration
- .NET Core version: 3.1.300
- OS version: Windows 10 Enterprise, version 1909 (build 18363.836)
- Architecture: x64
- Configuration-specific: No

### Other information
Workaround is to remove the Byte Order Mark before passing it into `System.Text.Json.JsonSerializer.Deserialize`.
I also tried converting it to a string first using `Encoding.UTF8.GetBytes()`, but this resulted in the same exception.
I have commented out the code that is used in the .NET Framework application that publishes the Azure Service Bus message as reference. 

Full stack trace:
```
System.Text.Json.JsonException : '0xEF' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
---- System.Text.Json.JsonReaderException : '0xEF' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, JsonReaderException ex)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ParseCore(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 utf8Json, JsonSerializerOptions options)
   at UTF8BOMJsonSerializerTests.JsonSerializerTests.DeserializeFromBytesWithBOM() in JsonSerializerTests.cs:line 49
----- Inner Stack Trace -----
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
```

**Comment by GrabYourPitchforks** [comment] 2020-06-02 23:20
I think this is a dupe of https://github.com/dotnet/runtime/issues/29838. Per the discussion in that issue, its by design that the `Stream`-consuming APIs look for the BOM, while the `byte[]` and `string`-consuming APIs don't. The general idea behind this is that the BOM is a marker that says "the rest of the data after this BOM is UTF-xx text". Once you have a `ROS<byte>` or a `string` that is that text, any U+FEFF that occurs _is part of the text itself_ and shouldn't be stripped.

**Comment by layomia** [comment] 2020-06-09 23:39
As mentioned, this is by design and a dupe of https://github.com/dotnet/runtime/issues/29838.

> Workaround is to remove the Byte Order Mark before passing it into System.Text.Json.JsonSerializer.Deserialize

If you need to use the `byte`/`string`-consuming APIs, this is indeed the workaround.

**Closed by layomia** 2020-06-09 23:39 UTC
Labels: area-System.Text.Json, untriaged
