### ISSUE TITLE
Uri constructor cannot parse http://hostname:port/  when hostname is * or +

### ISSUE THREAD

**Issue by chuacw** [dotnet/runtime#77464] opened 2022-08-03 08:35 UTC
### Description

* The Uri constructor cannot parse http://hostname:port/ when hostname is * or +, ie, http://*:9999/ or http://+:9999 will cause an exception to be thrown.

```
            httpListener = new HttpListener(); 
            string url = "http://*:1234/"; 
            Uri uri = new Uri(url);  
            // do something here... then pass the url (not uri) to the httpListener 
            httpListener.Prefixes.Add(url); 

```
* On the "new Uri(url)" line, the following exception occurred
System.UriFormatException
  HResult=0x80131537
  Message=Invalid URI: The hostname could not be parsed.
  Source=System.Private.Uri
  StackTrace:
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at HttpListenerSegments.Program..ctor() in K:\Development\CSharp\HttpListenerSegments\Program.cs:line 18
   at HttpListenerSegments.Program.Main(String[] args) in K:\Development\CSharp\HttpListenerSegments\Program.cs:line 79

* The Uri constructor should parse * or + into the DnsSafeHost, Host and IdnHost properties/fields (and whatever fields that currently holds the hostname).

* .NET Core 2.1
* Windows 11
* x64

**Comment by GrabYourPitchforks** [comment] 2022-10-26 01:08
Feature request for System.Uri area owners.

**Comment by MihaZupan** [comment] 2022-11-01 13:06
We've seen similar requests to relax the hostname parsing restrictions in the past (#36595).

It is worth noting that [RFC 3986](https://tools.ietf.org/html/rfc3986#section-3.2.2) allows such hostnames under the `reg-name` syntax definition, it is `System.Uri` that chooses to use a stricter DNS-like validation for hostnames.

We would be open to relaxing these requirements if there is enough interest in this.
Please upvote the original issue/this comment to let us gauge community interest in this and prioritize accordingly.

**Comment by MihaZupan** [comment] 2023-08-03 12:53
Duplicate of #64707

**Closed by MihaZupan** 2023-08-03 12:53 UTC
Labels: area-System.Net, feature-request
