### ISSUE TITLE
Inconsitency for Danish DateTime using MMM formatter

### ISSUE THREAD

**Issue by renemadsen** [dotnet/runtime#38423] opened 2020-06-23 13:17 UTC
If you have a DateTime object for any given date in May and using the Danish culture, the result of the following code will render "maj"

`DateTime dateTime = new DateTime(2020, 5, 1, 0, 0, 0);`
`Console.WriteLine($"{dateTime:MMM}");`

But do the same for any other date in any of the other moths will render the following output:

jan. feb. mar. apr. jun. jul. aug. sep. okt. nov. dec. 

Why this inconsistency?

This is created on Ubuntu 20.04 in dotnet core 2.2.402

**Comment by safern** [comment] 2020-06-26 05:01
Yeah this is by design because of what @joeloff said. We use ICU which uses the CLDR data, you can see here for the danish culture, how the “maj” is the same format for short and long. 


https://icu4c-demos-7hxm2n5zgq-uc.a.run.app/icu-bin/locexp?d_=en&_=da_DK

The `.` is to show that it is a short form.

Closing the issue since it is by design, of course feel free to re-open or continue the discussion.

**Closed by safern** 2020-06-26 05:01 UTC
Labels: area-System.Globalization, untriaged
