### ISSUE TITLE
The response ended prematurely

### ISSUE THREAD

**Issue by g1336** [dotnet/runtime#62963] opened 2021-12-17 13:12 UTC
I have a system running and making thousands of http requests to multiple providers every day. For one of the specific providers, every few hundred requests, I get the following exception. So everything looks like they are dropping the connection before sending a full response, since I don't get this exception with any of the other providers I call. However, I **never got this error before migrating from .NET Framework 4.7 to .NET 5**.

I can't provide a snippet to reproduce the error since the code works correctly 99% of the time, and only fails randomly with a private provider, but is just an HttpClient call. 

Is there anyway to find a deeper error message that may reveal some additional information?
```
at lambda_method1680(Closure , Object )\r\n
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask1 actionResultValueTask)\r\n
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n
 **The response ended prematurely** .\r\n
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken,"StackTrace":"
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken, Boolean async, Boolean doRequestAuth, CancellationToken, Boolean async, CancellationToken, Boolean async, CancellationToken, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken, Dictionary2 parameters)
```

**Comment by wfurt** [comment] 2021-12-17 22:26
Is this GET request or something else @g1336?  The stack trace end detailed exceptions may be useful.

**Comment by g1336** [comment] 2021-12-21 12:32
> Is this GET request or something else @g1336? The stack trace end detailed exceptions may be useful.

Yes, it is a GET request. The stack trace continues with some path to the files containing the classes and then this:

` at lambda_method3162(Closure , Object )\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask1 actionResultValueTask)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)","TimeGenerated":"2021-12-19T13:55:41.4846113+00:00"}`

**Comment by karelz** [comment] 2021-12-21 15:05
The Mvc.Infrastructure callstack looks like it is coming from server.
Are you able to look at the failed request via Wireshark or Fiddler? I'd be curious if the problem is on client side or server side.

**Comment by g1336** [comment] 2021-12-21 18:40
> The Mvc.Infrastructure callstack looks like it is coming from server. Are you able to look at the failed request via Wireshark or Fiddler? I'd be curious if the problem is on client side or server side.

![image](https://user-images.githubusercontent.com/6524225/146980763-1ffd8eb8-f984-4d56-a0c3-1c1fba772391.png)

This is what I found at some Wireshark logs from a time where the error happened. I see a lot of those `TCP Dup ACK `throughout our logs, could that be related? 

One thing that may be worth mentioning: the endpoint that returns this error on our provider is hit in a parallel fashion in our code, in order to fetch information as quickly as possible.

**Comment by wfurt** [comment] 2021-12-22 02:01
the DUP ACK is pretty normal. What you looking for is whole TCP session from SYN to the end. What we want is to determine who closes the TCP first and when. 
In theory each session is independent - but it can certainly impact timing.

**Comment by g1336** [comment] 2021-12-22 13:30
> the DUP ACK is pretty normal. What you looking for is whole TCP session from SYN to the end. What we want is to determine who closes the TCP first and when. In theory each session is independent - but it can certainly impact timing.

Ok so here are some different TCP sessions marked by colors around the time the error happened. Please let me know if this helps.

![01](https://user-images.githubusercontent.com/6524225/147100164-1011025a-8579-4004-821f-5caad7aa9166.png)
![02](https://user-images.githubusercontent.com/6524225/147100178-8dc71469-6cc6-45bd-9166-1c0749a37702.png)
![03](https://user-images.githubusercontent.com/6524225/147100195-873dfeb6-37c1-4070-aa9e-937e9811e6df.png)
![04](https://user-images.githubusercontent.com/6524225/147100201-1418cc4f-f6eb-414f-9ccc-b1f1908d82a6.png)

**Comment by wfurt** [comment] 2022-01-05 00:06
I did not see anything suspicious in the capture. It is still difficult to pin the specific connection. (I was looking for any time gaps or indications of network problem)

Did you try to enable tracing and look at the logs? It _may_ have some clue. 
Alternatively, you can look at something like https://github.com/wfurt/PcapStream. That allows you to record exchange from within the SSL e.g. you would see the actual HTTP. From the picture it is also not clear if you use HTTP 1 or 2. 

Last resort would be setting up some kind of man-in-the-middle. Setting like Fiddler can possibly decrypt and peak inside if the stream and it may also provide some insight.

**Comment by g1336** [comment] 2022-01-05 16:14
Thanks, we'll look into setting up fiddler to check the stream and let you know what we find.

**Comment by karelz** [comment] 2022-01-25 17:42
@g1336 any update on the Fiddler logs?

**Comment by karelz** [comment] 2022-02-10 17:21
Triage: Not enough info to make it actionable in last 4+ weeks. Closing.
Feel free to reopen if there is more info available.

**Closed by karelz** 2022-02-10 17:21 UTC
Labels: area-System.Net.Http, untriaged, no-recent-activity, needs-author-action
