### ISSUE TITLE
TimeSpan.FromSeconds

### ISSUE THREAD

**Issue by ScrawnySackboy** [dotnet/runtime#93831] opened 2023-10-22 19:13 UTC
### Description

We are using .NET 7.0 and have started to come across some issues as we migrate away from the .NET Framework. The issue is that relatively simple doubles (only to 3d.p.) seem to result in incorrect TimeSpan values.

### Reproduction Steps

```
var actual = TimeSpan.FromSeconds(101.832);
var expected = new TimeSpan(0, 0, 0, 101, 823);
Assert.AreEqual(expected, actual);
```

### Expected behavior

`00:01:41.8320000`

### Actual behavior

`00:01:41.8319999`

### Known Workarounds

Looking into the code, it appears the conversion from seconds to ticks takes place with the following code
```
private static TimeSpan IntervalFromDoubleTicks(double ticks)
{
    if ((ticks > long.MaxValue) || (ticks < long.MinValue) || double.IsNaN(ticks))
        ThrowHelper.ThrowOverflowException_TimeSpanTooLong();
    if (ticks == long.MaxValue)
        return TimeSpan.MaxValue;
    return new TimeSpan((long)ticks);
}
```

The issue in this case appears to be with the `(long)` cast, as if instead we run the same code with `Convert.ToInt64` it seems to work just fine. TLDR; the following code works.

```
var actual = TimeSpan.FromTicks(Convert.ToInt64(101.832 * TimeSpan.TicksPerSecond));
var expected = new TimeSpan(0, 0, 0, 101, 832);
Assert.AreEqual(expected, actual);
```

### Configuration

x64 .NET 7.0 on Windows 10

### Other information

I'm aware there have been a few issues raised about this topic but I'm still unsure on how to proceed as this behaviour seems odd to me.

As of .NET 7.0, the comment on the method as well as the documentation also mention rounding to the nearest millisecond, which does not appear to be the case.

**Comment by tarekgh** [comment] 2023-10-22 20:15
`Convert.ToInt64` is doing rounding which may be working in this case but may not work in other cases. @tannergooding do you have any thoughts around what is better, just casting `double` to `long` or rounding the `double` to `long`?

**Comment by tarekgh** [comment] 2023-10-22 20:23
https://github.com/dotnet/coreclr/pull/24279/files
https://github.com/dotnet/runtime/issues/27461

**Comment by tannergooding** [comment] 2023-10-23 01:44
This is "by design". `101.832` isn't `101 seconds` and `832 milliseconds`, it's `101.8319999999999936335370875895023345947265625`, or rather `101 seconds` and `831.999999999993... milliseconds`

The rounding direction for `(long)someDouble` is "towards zero" (truncation) while the rounding direction for `Convert.ToInt64(someDouble)` is "to nearest, ties to even" (it effectively just calls `(long)Round(someDouble)`). Neither of this is, strictly speaking, more or less correct than the other and both will introduce their own problematic behavior in different edge cases.

That being said, truncation better fits the default behavior for integer operations (in general) and that's why it is the default behavior in many cases like this for languages like C or C#.

If you want to avoid rounding issues like this, don't use `double`.

--------------------------------

@tarekgh, it might be beneficial to have something like `FromSeconds(int seconds)` and `FromSeconds(int seconds, int milliseconds)`.

These would allow less work to be done, as compared to `new TimeSpan(int days, int hours, int minutes, int seconds, int milliseconds)` and would avoid the errors that using `double` frequently introduce. It would likewise often be faster than using `double`, particularly if the inputs are frequently constant.

**Comment by colejohnson66** [comment] 2023-10-23 11:59
I've long (no pun intended) wondered why the API forces inputs to be floats. Sure, I can use the constructor to pass integers, but `new TimeSpan(0, 0, 0, 0, a)` (to get `a` seconds) doesn't show what I'm actually doing. "Why are there a bunch of zeros?"

Sure, all 32-bit integers are perfectly representable as a `double`, but then you're forcing the CPU to (1) convert your integer to a float, then (2) round that float back to an integer. It's needless work.

[Using SharpLab (.NET 7)](https://sharplab.io/#v2:C4LghgzgtgPgAgJgIwFgBQ6AqBLKBTAZQAcwA7AAgDEAnAeygLwGNbSATCACm1OHImasOASnIBeAHzpyM8jnzEyAOhr1GLdlwEaRAbiA), we indeed see an x86 `cvtsi2sd` instruction that could be avoided.

**Comment by Clockwork-Muse** [comment] 2023-10-23 12:34
I'm on mobile, so search is limited for me, but I thought this came up before?  Not that I'm opposed (frankly, I find the use of floats here somewhat appaling).

**Comment by tarekgh** [comment] 2023-10-23 15:22
> Would the team be amenable to an API proposal to introduce such overloads?

Yes. This is what @tannergooding was proposing in https://github.com/dotnet/runtime/issues/93831#issuecomment-1774304266

**Comment by tarekgh** [comment] 2023-10-23 15:48
I am closing this issue. We can track the new proposal in a separate issue.

**Closed by tarekgh** 2023-10-23 15:48 UTC
Labels: area-System.DateTime

**Comment by ScrawnySackboy** [comment] 2023-10-23 17:05
Thanks @tarekgh @tannergooding we'll work around it by handling the rounding we expect until the new overloads are available.

**Comment by tannergooding** [comment] 2023-10-23 17:55
Opened https://github.com/dotnet/runtime/issues/93890 as a tentative API suggestion. It is ultimately up to the area owners on whether this is a desired direction.
