### ISSUE TITLE
Exception not being thrown when null value encountered for non-nullable type

### ISSUE THREAD

**Issue by heron1** [dotnet/runtime#81007] opened 2023-01-23 00:34 UTC
I'm considering migrating from Newtonsoft to System.Text.Json because in the documentation it specifically states:
"Newtonsoft.Json doesn't throw an exception in the following scenario:

NullValueHandling is set to Ignore, and
During deserialization, the JSON contains a null value for a non-nullable value type.
In the same scenario, [System.Text.Json](https://learn.microsoft.com/en-us/dotnet/api/system.text.json) does throw an exception. (The corresponding null-handling setting in System.Text.Json is [JsonSerializerOptions.IgnoreNullValues](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.ignorenullvalues#system-text-json-jsonserializeroptions-ignorenullvalues) = true.)"

I want an exception to be thrown if a null value is encountered without polluting my types with any attributes, because this is a form of coupling I don't want in my business logic. How come no exception is being thrown? My type has a "string" field, and not a "string?" field, so going by the documentation, I'm expecting an exception to be thrown? Instead null is being set without any exception.

**Comment by gregsdennis** [comment] 2023-01-23 00:45
Related to #68128 and #1256

`IgnoreNullValues` is a serialization (not deserialization) config.  It tells the serializer whether to write a property that contains a null value.  Moreover, it looks to be obsolete in the newest versions of .net.  ([Ref](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.ignorenullvalues?view=net-7.0))

**Comment by eiriktsarpalis** [comment] 2023-01-27 10:50
Dupe of #1256.

**Closed by eiriktsarpalis** 2023-01-27 10:50 UTC
Labels: area-System.Text.Json, untriaged
