### ISSUE TITLE
Test failure in gcstress: Loader\\ContextualReflection\\ContextualReflection\\ContextualReflection

### ISSUE THREAD

**Issue by josalem** [dotnet/runtime#56554] opened 2021-07-29 16:08 UTC
Failed again in [runtime-coreclr gcstress0x3-gcstress0xc 20210727.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1262301&view=ms.vss-test-web.build-test-results-tab&runId=37404074&resultId=109138&paneView=debug)

Failed test:
```
CoreCLR windows x86 Checked gcstress0xc @ Windows.10.Amd64.Open

- Loader\\ContextualReflection\\ContextualReflection\\ContextualReflection.cmd

```
**Error message:**
```
Assert failure(PID 5432 [0x00001538], Thread: 3704 [0x0e78]): ptrManagedAssemblyLoadContext != NULL

CORECLR! AssemblyNative::GetLoadContextForAssembly + 0xF3 (0x70f85e73)
SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x6fee0332)
SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x6fee214b)
<no module>! <no symbol> + 0x0 (0x08ba96b9)
<no module>! <no symbol> + 0x0 (0x08ba85a3)
<no module>! <no symbol> + 0x0 (0x087beeb8)
<no module>! <no symbol> + 0x0 (0x087bba48)
CORECLR! CallDescrWorkerInternal + 0x34 (0x71294ba1)
CORECLR! CallDescrWorker + 0xAA (0x70f969f9)
CORECLR! CallDescrWorkerWithHandler + 0xDE (0x70f96b37)
File: D:\workspace_work\1\s\src\coreclr\vm\assemblynative.cpp Line: 1317
Image: C:\h\w\A59D098B\p\corerun.exe

Return code:      1
Raw output file:      C:\h\w\A59D098B\w\A7D90961\uploads\Reports\Loader.ContextualReflection\ContextualReflection\ContextualReflection.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\A59D098B\p\corerun.exe"  ContextualReflection.dll
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\A59D098B\p
C:\h\w\A59D098B\w\A7D90961\e\Loader\ContextualReflection\ContextualReflection\ContextualReflection.cmd
Expected: True
Actual:   False


Stack trace
   at Loader_ContextualReflection._ContextualReflection_ContextualReflection_._ContextualReflection_ContextualReflection_cmd() in Loader.ContextualReflection.XUnitWrapper.dll:token 0x6000004+0x284
```

_Originally posted by @VincentBu in https://github.com/dotnet/runtime/issues/54801#issuecomment-888755586_

**Comment by buyaa-n** [comment] 2021-08-05 06:03
Looks duplicate of https://github.com/dotnet/runtime/issues/55518

**Comment by vitek-karas** [comment] 2021-08-13 15:35
#55518 which is very likely the same issue has been fixed. Closing this - if we see it again, please reopen..

**Closed by vitek-karas** 2021-08-13 15:35 UTC
Labels: arch-x86, os-windows, GCStress, area-AssemblyLoader-coreclr, untriaged
