### ISSUE TITLE
Test failure readytorun\\fieldlayout\\fieldlayout\\fieldlayout.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#83431] opened 2023-03-15 01:10 UTC
Failed in Run: [runtime-coreclr jitstress 20230313.1](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=203308)
 
 **Failed tests:**
 ```
 coreclr windows x86 Checked jitstress2 @ Windows.10.Amd64.Open
     - readytorun\\fieldlayout\\fieldlayout\\fieldlayout.cmd
 ```
 
 **Error message:**
 ```
 
Assert failure(PID 8484 [0x00002124], Thread: 5376 [0x1500]): Assertion failed 'node->OperIsLIR()' in 'AutoTest:Test()' during 'Rationalize IR' (IL size 533; hash 0x4d20fff1; FullOpts)

    File: D:\a\_work\1\s\src\coreclr\jit\lir.cpp Line: 1616
    Image: C:\h\w\B91109E4\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\B91109E4\w\B2720994\uploads\Reports\readytorun.fieldlayout\fieldlayout\fieldlayout.output.txt
Raw output:
BEGIN EXECUTION
fieldlayout.dll
        1 file(s) copied.
 5:39:05.44
Response file: C:\h\w\B91109E4\w\B2720994\e\readytorun\fieldlayout\fieldlayout\\composite-r2r.dll.rsp
C:\h\w\B91109E4\w\B2720994\e\readytorun\fieldlayout\fieldlayout\IL-CG2\*.dll
-o:C:\h\w\B91109E4\w\B2720994\e\readytorun\fieldlayout\fieldlayout\\composite-r2r.dll
--targetarch:x86
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\B91109E4\p\System.*.dll
-r:C:\h\w\B91109E4\p\Microsoft.*.dll
-r:C:\h\w\B91109E4\p\mscorlib.dll
-r:C:\h\w\B91109E4\p\netstandard.dll
-O
" "dotnet" "C:\h\w\B91109E4\p\crossgen2\crossgen2.dll" @"C:\h\w\B91109E4\w\B2720994\e\readytorun\fieldlayout\fieldlayout\\composite-r2r.dll.rsp"   --composite"
Emitting R2R PE file: C:\h\w\B91109E4\w\B2720994\e\readytorun\fieldlayout\fieldlayout\\composite-r2r.dll
Emitting R2R PE file: C:\h\w\B91109E4\w\B2720994\e\readytorun\fieldlayout\fieldlayout\fieldlayout.dll
" "dotnet" "C:\h\w\B91109E4\p\r2rdump\r2rdump.dll" --header --sc --in C:\h\w\B91109E4\w\B2720994\e\readytorun\fieldlayout\fieldlayout\\composite-r2r.dll --out C:\h\w\B91109E4\w\B2720994\e\readytorun\fieldlayout\fieldlayout\\composite-r2r.dll.r2rdump --val"
 5:39:07.53
 "C:\h\w\B91109E4\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  fieldlayout.dll 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:\cores since 3/14/2023 5:39:05 AM
Processing C:\cores\corerun.exe.8484.dmp
Invoking: C:\Program Files (x86)\Windows Kits\10\Debuggers\x86\cdb.exe -c "$<C:\h\w\B91109E4\t\tmpua1cy0.tmp" -z "C:\cores\corerun.exe.8484.dmp"
stdout: 
Microsoft (R) Windows Debugger Version 10.0.18362.1 X86
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:\cores\corerun.exe.8484.dmp]
User Mini Dump File with Full Memory: Only application data is available


************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:\h\w\B91109E4\p\PDB
Symbol search path is: C:\h\w\B91109E4\p\PDB
Executable search path is: 
Windows 10 Version 14393 MP (4 procs) Free x86 compatible
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.5125 (rs1_release.220429-1732)
Machine Name:
Debug session time: Tue Mar 14 05:39:08.000 2023 (UTC + 0:00)
System Uptime: 0 days 6:49:03.647
Process Uptime: 0 days 0:00:01.000
............................

************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  The system cannot find the file specified

You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.sympath) is correct.
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(2124.1500): Unknown exception - code c0000602 (first/second chance not available)
For analysis of this file, run !analyze -v
*** WARNING: Unable to verify checksum for coreclr.dll
eax=00b794f8 ebx=00000000 ecx=00000000 edx=00000000 esi=00b794a8 edi=00b794f8
eip=7026d092 esp=00b797dc ebp=00b7a874 iopl=0         nv up ei pl nz ac pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00000216
coreclr!FailFastOnAssert+0x21:
7026d092 5e          
 ```
 
 **Stack trace:**
 ```
   at readytorun_fieldlayout._fieldlayout_fieldlayout_._fieldlayout_fieldlayout_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
 ```

**Comment by EgorBo** [comment] 2023-03-15 01:37
Presumably fixed via https://github.com/dotnet/runtime/pull/83360 cc @jakobbotsch

**Comment by jakobbotsch** [comment] 2023-03-15 09:05
Yeah, duplicate of #83360. This test run is from before that was merged and I don't see the failure in the latest run.

**Closed by jakobbotsch** 2023-03-15 09:05 UTC
Labels: arch-x86, os-windows, JitStress, area-CodeGen-coreclr, untriaged
