### ISSUE TITLE
System.Net.Sockets.SocketException (10042) - SetMulticastOption

### ISSUE THREAD

**Issue by epasinetti** [dotnet/runtime#81507] opened 2023-02-01 21:39 UTC
Running this code on windows 10/11 using .NET 7.0 or any previous framework I got exception on line  :

```
s.SetSocketOption(SocketOptionLevel.IP, SocketOptionName.AddMembership, new MulticastOption(ip, IPAddress.Any));
```
```
Unhandled exception. System.Net.Sockets.SocketException (10042): An unknown, invalid, or unsupported option or level was specified in a getsockopt or setsockopt call.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
   at System.Net.Sockets.Socket.SetMulticastOption(SocketOptionName optionName, MulticastOption MR)
   at MainClass.Main(String[] args)
```

```
string IpGroup = "224.0.224.1";
string sPort = "2405";

Socket s = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp);

IPEndPoint ipep = new IPEndPoint(IPAddress.Any, int.Parse(sPort));
s.Bind(ipep);

IPAddress ip = IPAddress.Parse(IpGroup);

try
{
//Error HERE    
s.SetSocketOption(SocketOptionLevel.IP, SocketOptionName.AddMembership, new MulticastOption(ip, IPAddress.Any));
    Console.WriteLine("Joined: " + IpGroup + ":" + sPort);
    while (true)
    {

	byte[] b = new byte[100];

	s.Receive(b);
	string str = System.Text.Encoding.ASCII.GetString(b, 0, b.Length);

	Console.WriteLine("RX: " + str.Trim());

    }
}
catch (Exception err)
{
    Console.WriteLine("ERR:" + err.Message);
}
```

Same code running on Windows 7 or on Linux arm 32 run without problem.

Someone can help me ?

**Comment by antonfirsov** [comment] 2023-02-02 17:18
Triage: we should check if there is an easy fix, and do it if yes.

**Comment by pedrobsaila** [comment] 2023-02-14 22:27
Hey @epasinetti  I tried the code on my Windows 11 machine and didn't get the error with .NET 7.0 nor .NET 6.0. What you had is [WSAENOPROTOOPT|https://learn.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2] error which is linked to including [bad winsock header files|https://learn.microsoft.com/en-us/troubleshoot/windows/win32/header-library-requirement-socket-ipproto-ip] so maybe the issue is in the interop calls.

@antonfirsov did it fail for you too ?

**Comment by antonfirsov** [comment] 2023-02-15 13:22
I wasn't able to repro this either.

> including [bad winsock header files](https://learn.microsoft.com/en-us/troubleshoot/windows/win32/header-library-requirement-socket-ipproto-ip)

Linking happens when the runtime is built, so if it's broken, it should be broken for every user of .NET.

@epasinetti can you repro this in native C WinSock code?

**Comment by epasinetti** [comment] 2023-02-15 20:24
I solved the problem resetting all parameters of my network interfaces and edited some keys in windows registry. 
I tried many ways but I can't say what is the cause and how it is solved.
I have replied the same issue on different machines. On my laptop I have installed lot of VPN clients of different vendor I suppose one of them put some parameters wrong but it is just a supposition.

**Comment by antonfirsov** [comment] 2023-02-16 14:06
Thanks @epasinetti! I'm closing this for now, since the issue turned out to be environmental, and the `Socket` class was most likely forwarding whatever it got from WinSock `setsockopt`. Feel free to reopen if you disagree, or you think there is something .NET could do better.

**Closed by antonfirsov** 2023-02-16 14:06 UTC
Labels: area-System.Net.Sockets, help wanted
