### ISSUE TITLE
Enhance EmailAddressAttribute to validate email address correctly

### ISSUE THREAD

**Issue by mo-esmp** [dotnet/runtime#45670] opened 2020-12-07 08:22 UTC
In the `EmailAddressAttribute` implementation, only `@` is checked for email validity and if the user enters an email like `someone@outlookcom`, it is considered a valid email.

https://github.com/dotnet/runtime/blob/a9009db46e315d0eb862c6925cca19798b947163/src/libraries/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/EmailAddressAttribute.cs#L34

**Comment by ChristianHoe** [comment] 2020-12-07 10:17
Correct email validation is not as simple as it looks.
Did you know `user@[198.51.100.10]` (using IP4/IP6 addresses) is a perfectly valid email address? Even `user@localsever` is perfectly valid.

But I think, even this implementation has its flaws. It looks, like it is not handling quotations marks well. `"@"` should not be a valid address even if `"...@..."@localhost`would be.

**Comment by mo-esmp** [comment] 2020-12-07 10:48
So what percentage of users have an email like `user@localsever`? And what percentage of users use popular email service providers like Google and Microsoft? What is clear is that `EmailAddressAttribute` does not perform correct validation for common email addresses.

**Comment by ChristianHoe** [comment] 2020-12-07 11:17
I have seen _crazy_ email like `user@localsever` or `user@mail.company.local` in company environments. If you are really really sure what your users email addresses looks like, write your own validator. But it does not help with other mistakes users can do like `user@mirosoft.com` or similar... Even if the email is valid one, it does not has to be the one of the user.
Just be warned.

**Comment by mo-esmp** [comment] 2020-12-07 11:26
I would not be surprised if validation did not work for `user@localsever`, but it is really strange that validation does not work for regular emails and everyone has to implement their own version to validate `user@domain.com`. just ignoring 99%  `user@domain.com` and supporting 1% (user@localsever)

**Comment by canton7** [comment] 2020-12-07 13:58
For info, [this is the RFC822 email validation regex](https://www.ex-parrot.com/pdw/Mail-RFC822-Address.html). 

The prevailing wisdom (see e.g. [here](https://medium.com/hackernoon/the-100-correct-way-to-validate-email-addresses-7c4818f24643)) is that email validation is 1) hard, and 2) pointless. It's worth trying to catch the case where the user misunderstood what the field _was_ and entered the wrong bit of information (and checking for `@` does this), but there's no point in trying to validate that they entered a syntactically-correct email address. Either you accidentically reject someone's valid email address (and annoy them), or you force someone who's making up an email address to spend a second trying slightly harder.

What you normally actually care about is whether the user entered an email address _which they can access_. To do this, you need to send them an email and get them to confirm that they received it.

**Comment by ajcvickers** [comment] 2020-12-07 16:55
Duplicate of #27592

**Closed** 2020-12-07 16:55 UTC
Labels: area-System.ComponentModel.DataAnnotations
