### ISSUE TITLE
Test failure:System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.SendAsync_ConcurentSendReceive_Ok

### ISSUE THREAD

**Issue by AriNuer** [dotnet/runtime#34356] opened 2020-04-01 03:19 UTC
**Job:**
[runtime-libraries outerloop:20200331.1](https://dev.azure.com/dnceng/public/_build/results?buildId=581202&view=results)
**Error message:**
```
System.NullReferenceException : Object reference not set to an instance of an object.
```
**Stack trace:**
```
  at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.DuplexContent.SerializeToStreamAsync(Stream stream, TransportContext context) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 1929
   at System.Net.Http.HttpContent.CopyToAsyncCore(ValueTask copyTask) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpContent.cs:line 376
   at System.Net.Http.Http2Connection.Http2Stream.SendRequestBodyAsync(CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs:line 184
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs:line 1771
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 739
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 33
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts, CancellationToken callerToken, Int64 timeoutTime) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 605
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.SendAsync_ConcurentSendReceive_Ok(Boolean shouldWaitForRequestBody, HttpStatusCode responseCode) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs:line 2722
--- End of stack trace from previous location ---
```
**Details:**
https://dev.azure.com/dnceng/public/_build/results?buildId=581202&view=ms.vss-test-web.build-test-results-tab&runId=18274716&resultId=102834&paneView=debug

**Comment by ManickaP** [comment] 2020-04-01 10:41
Probably race condition between [HttpClientHandlerTest.Http2.cs#L2711](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs#L2711) and the line of exception [HttpClientHandlerTest.Http2.cs#L1929](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs#L1929) since the `_waitForCompletion` is being nulled in `Complete`.

**Comment by karelz** [comment] 2020-04-03 18:44
Duplicate of #33141

**Closed by karelz** 2020-04-03 18:44 UTC
Labels: arch-x64, area-System.Net.Http, os-linux, untriaged
