### ISSUE TITLE
Rename System.Drawing.Common

### ISSUE THREAD

**Issue by JeremyCaron** [dotnet/runtime#63330] opened 2021-12-29 23:06 UTC
System.Drawing.Common should be renamed if it's no longer common across all OSes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fa60e1c-9c9a-ce16-2e47-c41857fc8c48
* Version Independent ID: c3b792d7-50ab-ff45-09bf-37a7550f0e09
* Content: [Breaking change: System.Drawing.Common only supported on Windows - .NET](https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only)
* Content Source: [docs/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only.md](https://github.com/dotnet/docs/blob/main/docs/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only.md)
* Product: **dotnet-fundamentals**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by danmoseley** [comment] 2022-01-04 06:12
I'm not entirely sure that the Common part of the name was intended to mean it would later include Unix support. We just needed a name distinct from System.Drawing.

Whatever the reason I see little or no value in changing the name and just cost and risk. Assembly names should not often be important. Most people consume this via the windows compatibility package, and don't see the name. 

I'll close this.

**Closed** 2022-01-04 06:13 UTC
Labels: area-System.Drawing, untriaged
