### ISSUE TITLE
System.Drawing classes are using windows-only TypeConverters

### ISSUE THREAD

**Issue by toady** [dotnet/runtime#663] opened 2019-12-07 18:37 UTC
While `System.Drawing.Common` library is portable, most of it's entities have a `TypeConverter` attribute which references `System.Windows.Extensions` library, thus resulting in `PlatformNotSupportedException` on Unix systems when used.

This is only the case for netcoreapp builds.

Some examples:
https://github.com/dotnet/runtime/blob/master/src/libraries/System.Drawing.Common/src/System/Drawing/Image.cs#L22
https://github.com/dotnet/runtime/blob/master/src/libraries/System.Drawing.Common/src/System/Drawing/Font.cs#L18

Maybe those attributes should be moved to associated `*.Windows.cs` files instead?

**Comment by mastoj** [comment] 2019-12-07 21:07
I guess this is the reason why I can't use it on OSX at the moment?

**Comment by lil-Toady** [comment] 2019-12-08 01:40
Had a quick look at the converters belonging to `System.Drawing` namespace in the `System.Windows.Extensions` assembly, and it seems they could be safely moved to `System.Drawing.Common`, as they don't rely on any Windows specific API. This way they we can lose the platform restriction completely.

**Comment by ericstj** [comment] 2020-04-20 17:32
This is a duplicate of https://github.com/dotnet/runtime/issues/1011.

Originally we did this to avoid adding a dependency from System.Drawing.Common on TypeConverter but I think we can roll-back that decision.

**Closed by ericstj** 2020-04-20 17:32 UTC
Labels: area-System.Drawing, untriaged
