### ISSUE TITLE
System.Text.Json serialization bug on virtual/override properties.

### ISSUE THREAD

**Issue by nodew** [dotnet/runtime#107273] opened 2024-09-03 02:56 UTC
### Description

Dotnet SDK: 8.0.400.

When there's custom JsonPropertyName attribute on virtual property of parent class, and at the same time, there's override on derived class, it renders the property twice with default name and custom name.

### Reproduction Steps

Consider there're two classes, TestClassA has a virtual property, TestClassB extends TestClassA and override the property.

```csharp
class TestClassA
{
    [JsonPropertyName("xname")]
    public virtual string Name => "A";

    public int Age { get; set; }
}

class TestClassB : TestClassA
{
    public override string Name => "X";
}
```

Then serialize the instance of TestClassB

```csharp
var options = new JsonSerializerOptions
{
    WriteIndented = true,
};

var json = JsonSerializer.Serialize(new TestClassB(), options);
```

### Expected behavior

Output:
```bash
{
  "xname": "X",
  "Age": 0
}
```

### Actual behavior

Output:
```bash
{
  "Name": "X",
  "xname": "X",
  "Age": 0
}
```

**Comment by Xor-el** [comment] 2024-09-05 23:35
This seems to be a duplicate of #92780 or at least very similar to it.

**Comment by eiriktsarpalis** [comment] 2024-09-09 10:00
Duplicate of #92780.

**Closed by eiriktsarpalis** 2024-09-09 10:00 UTC
Labels: area-System.Text.Json, untriaged
