### ISSUE TITLE
BlockingCollection should properly cancel pending consumers when disposed

### ISSUE THREAD

**Issue by tcostin** [dotnet/runtime#39904] opened 2020-07-24 18:23 UTC
### Description

If a thread is blocked inside BlockingCollection.Take(), and the collection is disposed, I would expect the Take() method to end with an exception. Instead, the call never returns, and the caller thread is permanently blocked. This can be worked around by calling CompleteAdding() first (causing the call to Take() to end with InvalidOperationEx), but I would expect the Dispose() method to do this on its own. See attached source file for a simple demo.

### Configuration

.Net core 3.1.latest running on x64

### Regression?

I am unaware of any version where this worked as I would expect. In fact,  this behavior is even worse in the desktop .Net framework, where calling CompleteAdding() results in Take() throwing an ArgumentNullException from an internal method (which is not part of that method's list of possible exceptions).

```
System.ArgumentNullException: Value cannot be null.
   at System.Threading.SemaphoreSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Collections.Concurrent.BlockingCollection`1.TryTakeWithNoTimeValidation(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken, CancellationTokenSource combinedTokenSource)
   at System.Collections.Concurrent.BlockingCollection`1.TryTake(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Collections.Concurrent.BlockingCollection`1.Take()
   at TestBlockingCollectionDisposal.Program.TakeFromCollection(Object b) in C:\Users\Tudor\source\repos\Perforce\TeamCity\TestBlockingCollectionDisposal\Program.cs:line 28
```

**Comment by tcostin** [comment] 2020-07-24 18:24
[TestBlockingCollectionDisposalCore.zip](https://github.com/dotnet/runtime/files/4973687/TestBlockingCollectionDisposalCore.zip)

**Comment by tcostin** [comment] 2020-07-24 18:25
[TestBlockingCollectionDisposalCore.zip](https://github.com/dotnet/runtime/files/4973694/TestBlockingCollectionDisposalCore.zip)

**Comment by Clockwork-Muse** [comment] 2020-07-24 18:45
`Dispose` is almost never threadsafe (including here), so calling it at all on a shared collection is a bug in your application.  Having it call `CompleteAdding()` won't necessarily resolve all potential issues, because the rest of the cleanup code could produce race conditions.  You're going to need to ensure only one thread has access before you can call `Dispose`.  If you only have one consumer, it should probably manually perform the call after it detects adding is complete and the collection has been drained.

**Comment by tcostin** [comment] 2020-07-24 19:39
In that case, BlockingCollection may not be the API I'm looking for.

I use a BlockingCollection shared between the main/UI thread and a worker thread to do background work in my app. The user queues certain work items via the GUI (i.e. the UI thread). The work items are added to the BlockingCollection, and the worker thread calls Take() to obtain work items, processes them, then posts updates to the UI thread when it finishes the work. When the user closes the window (which does not end the app itself), I can be sure there will be no more work items, and I want to clean up the associated resources, including the collection itself and the background thread. Only the UI thread will know when to do this cleanup, and the background thread is almost certainly blocked inside Take() at this point, so it's impossible by design that "only one thread has access", or that the consumer does the cleanup.

I'm not sure what you mean by being threadsafe in this context. I fully expect that Take() will behave badly when the underlying collection is disposed - I just think it should throw an exception to its caller(s) instead of letting them hang.

**Comment by Clockwork-Muse** [comment] 2020-07-24 20:29
The GUI can signal to the background thread to clean itself up by calling `CompleteAdding` - that's what it's there for.  Calling it will cause `Take` to unblock with an exception, so you can check that and the status of the collection with respect to adding to deal with this.  At that point, the background thread knows the GUI thread has been shut down, and so can clean itself up, including disposing the collection.

However, if closing the GUI doesn't kill the app, I'm a little surprised that you can't open it back up again, at which point you'd have to recreate the background thread/collection.  Are you sure you don't want to keep them around until the app itself closes?

> I'm not sure what you mean by being threadsafe in this context. I fully expect that Take() will behave badly when the underlying collection is disposed - I just think it should throw an exception to its caller(s) instead of letting them hang.

The problem isn't just with `Take` - for one thing, it's likely that whatever is being used for a lock is getting thrown out too, which can cause other problems.  Calling _any_ method on an object being disposed by another thread is inherently unsafe, because some part of its internal state is just... gone, but the current thread code may have already passed the relevant checks for disposal status.  You're **lucky** if you get an exception when you call such a method, it's not a guarantee.

**Comment by tcostin** [comment] 2020-07-24 20:52
That makes sense actually. I was just experimenting with the above approach, and it resulted in an orderly shutdown and cleanup. It's a bit odd to dispose an object on a different thread than the one that created it, but it seems to be required in this case.

This works well for my scenario of a single consumer. I can see the potential for race conditions if multiple consumers exist, but Dispose() is indeed clearly documented as not thread safe, so I suppose it would be up to the app to synchronize the final cleanup in such a case.

As for keeping the collection/thread around: if the user revisits that particular window (actually a page in a multi step wizard), the previous state would almost certainly not apply. I considered keeping them around if the cleanup cannot be resolved. Spinning up the thread again is _probably_ more costly than keeping it, but the bulk of wait time comes from the database querying anyway.

This issue can be closed now. Thanks everyone for their time.

**Closed** 2020-07-24 20:59 UTC
Labels: area-System.Collections, untriaged

**Comment by Clockwork-Muse** [comment] 2020-07-25 00:31
> It's a bit odd to dispose an object on a different thread than the one that created it, but it seems to be required in this case.

"Created" isn't the important criteria, "Owner" is.  Due to a number of factors, that isn't really a thing in C# - if you haven't looked at it yet, take a quick spin through the Rust language.  Or, the `std::unique_ptr` in C++ is somewhat similar.

There's a couple of ways to deal with the disconnect you're feeling here:
 - Have the background thread create the blocking collection, and expose it as a property, which the GUI then reads.  Background thread is then both owner and creator.  Requires a single consumer.
 - Have the GUI thread wait until the background thread(s) completes, then dispose of the blocking collection.  GUI stays owner of the collection.  Supports multiple consumers.
