### ISSUE TITLE
System.Formats.Asn1 8.0.1 - The located assembly's manifest definition does not match the assembly reference

### ISSUE THREAD

**Issue by BartNSTCL** [dotnet/runtime#105248] opened 2024-07-22 14:41 UTC
### Description

After installing Oracle.ManagedDataAccess 23.5.0 on a Netframework 4.8.1 website and publishing, the site was crashing with the error, The located assembly's manifest definition does not match the assembly reference for System.Formats.Asn1 8.0.1. I tried adding the dependency info to web.config, but I have found that sometimes, that requires some strange versions that's not very intuitive to me. I've rolled back to System.Formats.Asn1 to 8.0.0 for now.

### Reproduction Steps

Not sure if just adding System.Formats.Asn1 8.0.1 would trigger the error, but adding Oracle.ManagedDataAccess 23.5.0 and updating System.Formats.Asn1  to 8.0.1 should do it.

### Expected behavior

At least the web.config Dependency data would be updated with the correct version.

### Actual behavior

Its updated, with the lines below, but the error still occurs.
     <dependentAssembly>
       <assemblyIdentity name="System.Formats.Asn1" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
       <bindingRedirect oldVersion="0.0.0.0-8.0.0.1" newVersion="8.0.0.1" />
     </dependentAssembly>

### Regression?

Its works fine with System.Formats.Asn1 8.0.0.

### Known Workarounds

Roll System.Formats.Asn1 8.0.1 back to System.Formats.Asn1 8.0.0

### Configuration

NetFramework 4.8.1
Windows Server 2022 x64
All web browsers.

**Comment by BartNSTCL** [comment] 2024-07-22 14:49
It seems after deleting the BIN folder and republishing, it seems to be working now. However, I'm not sure why it was failing the first time around.

**Comment by huoyaoyuan** [comment] 2024-07-22 17:27
Sounds like a `BindingRedirect` issue. On .NET Framework, the version of dependency assemblies are matched exactly. Building the project would generate a redirect instruction that redirects the dependency of 8.0.0 to 8.0.1.

> It seems after deleting the BIN folder and republishing

Seems that the publishing process is not clean as it needs to be.

**Comment by adamsitnik** [comment] 2024-08-01 12:48
> It seems after deleting the BIN folder and republishing, it seems to be working now. However, I'm not sure why it was failing the first time around.

Closing as the issue is solved and does not seem to be related to the library itself.

**Closed by adamsitnik** 2024-08-01 12:48 UTC
Labels: area-System.Formats.Asn1, needs-further-triage
