### ISSUE TITLE
"Invalid argument" exception when setting Socket.ReceiveTimeout on macOS ARM64

### ISSUE THREAD

**Issue by cheenamalhotra** [dotnet/runtime#81378] opened 2023-01-30 20:01 UTC
### Description

I received an issue internally where customer is experiencing below error on macOS arm64 when Microsoft.Data.SqlClient is setting 'ReceiveTimeout' on Socket:

```
System.Net.Sockets.SocketException (22): Invalid argument
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at System.Net.Sockets.Socket.set_ReceiveTimeout(Int32 value)
   at Microsoft.Data.SqlClient.SNI.SNITCPHandle.Receive(SNIPacket& packet, Int32 timeoutInMilliseconds)
   at Microsoft.Data.SqlClient.SNI.TdsParserStateObjectManaged.ReadSyncOverAsync(Int32 timeoutRemaining, UInt32& error)
```

The driver sets timeout (default is 30 seconds) or 0 if infinite timeout is specified. I'm still waiting on info whether they changed the property value, but its unlikely.

Is this a known issue from `osx-arm64`?

### Reproduction Steps

Set 'ReceiveTimeout' to a value on OSX-ARM64 with .NET 6.0.403

### Expected behavior

Exception should not occur

### Actual behavior

Exception is thrown as mentioned above.

### Regression?

Not sure

### Known Workarounds

Not available

### Configuration

	macOS : Ventura 13.0

	NET SDK Version:   6.0.403
	 Commit:    2bc18bf292
	
	Runtime Environment:
	 OS Name:     Mac OS X
	 OS Version:  13.0
	 OS Platform: Darwin
	 RID:         osx-arm64
	 Base Path:   /usr/local/share/dotnet/sdk/6.0.403/
	
	Host:
	  Version:      6.0.11
	  Architecture: arm64
	  Commit:       943474ca16

**Comment by antonfirsov** [comment] 2023-01-30 21:13
@cheenamalhotra looks like `Microsoft.Data.SqlClient` is setting a value for the `ReceiveTimeout` socket option that the native OS layer considers to be invalid on that platform, this is likely a bug to be addressed by https://github.com/dotnet/SqlClient maintainers. Have you considered opening an issue in that repo?

**Comment by cheenamalhotra** [comment] 2023-01-30 21:31
Hi @antonfirsov 

I'm one of the maintainers, and the value is likely correct, since this is not a new change, and the code has been working successfully on various platforms over many years.

One thing I learnt recently is that we're running x64 arch runtime on arm64 platform.. is it possible that's a concern?

**Comment by antonfirsov** [comment] 2023-01-30 22:24
Personally I don't know much about arm64 and x64 emulation, so I would need a repro to start investigating this. Maybe @wfurt has some better ideas?

Any chance you can create a minimal repro for us?  (Small console app trying to set the `ReceiveTimeout` on a socket + steps to run it in an Arm64 environment). This would greatly help the investigation.

**Comment by cheenamalhotra** [comment] 2023-01-31 18:14
Hi @wfurt 

Thanks for chiming in. This is a customer reported issue where they're running into this (consistently) with Azure Data Studio (via Microsoft.Data.SqlClient). We haven't been able to reproduce it at our end yet. 

Also to mention, I ran test with .NET 6.0.404 with Rid: osx.13-arm64. I'm going to try downgrading to 6.0.403 (as used by customer) to see if that makes a diff, but not sure if I'll get the RID: osx-arm64 as user.

Will keep you posted as I get a repro.

**Comment by antonfirsov** [comment] 2023-02-02 17:13
Triage: we should make sure this is not a bug.

**Closed** 2023-03-03 00:02 UTC
Labels: area-System.Net.Sockets, os-mac-os-x, no-recent-activity, needs-author-action
