### ISSUE TITLE
Test failure JIT/Directed/nullabletypes/Desktop/boxunboxvaluetype_do/boxunboxvaluetype_do.sh

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#77706] opened 2022-11-01 01:36 UTC
Run: [runtime-coreclr gcstress-extra 20221030.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=67446&view=ms.vss-test-web.build-test-results-tab&runId=1374084&resultId=110909&paneView=debug)

Failed test:
```
coreclr Linux arm64 Checked gcstress0xc_jitstress2 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20220824230426-06f234f

- JIT/Directed/nullabletypes/Desktop/boxunboxvaluetype_do/boxunboxvaluetype_do.sh
- JIT/Directed/nullabletypes/Desktop/boxunboxvaluetype_ro/boxunboxvaluetype_ro.sh

coreclr windows arm64 Checked gcstress0xc_jitstress2 @ Windows.10.Arm64v8.Open

- JIT\\Directed\\nullabletypes\\Desktop\\boxunboxvaluetype_do\\boxunboxvaluetype_do.cmd
- JIT\\Directed\\nullabletypes\\Desktop\\boxunboxvaluetype_ro\\boxunboxvaluetype_ro.cmd

coreclr windows arm64 Checked gcstress0xc_zapdisable_jitstress2 @ Windows.10.Arm64v8.Open

- JIT\\Directed\\nullabletypes\\Desktop\\boxunboxvaluetype_ro\\boxunboxvaluetype_ro.cmd

coreclr OSX arm64 Checked gcstress0xc_jitstress2 @ OSX.1200.ARM64.Open

- JIT/Directed/nullabletypes/Desktop/boxunboxvaluetype_ro/boxunboxvaluetype_ro.sh
```
**Error message:**
```
Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.Directed/nullabletypes/Desktop/boxunboxvaluetype_do/boxunboxvaluetype_do.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false boxunboxvaluetype_do.dll ''
--- char? s = Helper.Create(default(char)) ---
--- char? s = null ---
--- char u = Helper.Create(default(char)) ---
--- bool? s = Helper.Create(default(bool)) ---
--- bool? s = null ---
--- bool u = Helper.Create(default(bool)) ---
--- byte? s = Helper.Create(default(byte)) ---
--- byte? s = null ---
--- byte u = Helper.Create(default(byte)) ---
--- sbyte? s = Helper.Create(default(sbyte)) ---
--- sbyte? s = null ---
--- sbyte u = Helper.Create(default(sbyte)) ---
--- short? s = Helper.Create(default(short)) ---
--- short? s = null ---
--- short u = Helper.Create(default(short)) ---
--- ushort? s = Helper.Create(default(ushort)) ---
--- ushort? s = null ---
--- ushort u = Helper.Create(default(ushort)) ---
--- int? s = Helper.Create(default(int)) ---
--- int? s = null ---
--- int u = Helper.Create(default(int)) ---
--- uint? s = Helper.Create(default(uint)) ---
--- uint? s = null ---
--- uint u = Helper.Create(default(uint)) ---
--- long? s = Helper.Create(default(long)) ---
--- long? s = null ---
--- long u = Helper.Create(default(long)) ---
--- ulong? s = Helper.Create(default(ulong)) ---
--- ulong? s = null ---
--- ulong u = Helper.Create(default(ulong)) ---
--- float? s = Helper.Create(default(float)) ---
--- float? s = null ---
--- float u = Helper.Create(default(float)) ---
--- double? s = Helper.Create(default(double)) ---
--- double? s = null ---
--- double u = Helper.Create(default(double)) ---
--- decimal? s = Helper.Create(default(decimal)) ---
--- decimal? s = null ---
--- decimal u = Helper.Create(default(decimal)) ---
--- IntPtr? s = Helper.Create(default(IntPtr)) ---
--- IntPtr? s = null ---
--- IntPtr u = Helper.Create(default(IntPtr)) ---
--- UIntPtr? s = Helper.Create(default(UIntPtr)) ---
--- UIntPtr? s = null ---
--- UIntPtr u = Helper.Create(default(UIntPtr)) ---
--- Guid? s = Helper.Create(default(Guid)) ---
--- Guid? s = null ---
--- Guid u = Helper.Create(default(Guid)) ---
--- GCHandle? s = Helper.Create(default(GCHandle)) ---
--- GCHandle? s = null ---
--- GCHandle u = Helper.Create(default(GCHandle)) ---
--- ByteE? s = Helper.Create(default(ByteE)) ---
--- ByteE? s = null ---
--- ByteE u = Helper.Create(default(ByteE)) ---
--- IntE? s = Helper.Create(default(IntE)) ---
--- IntE? s = null ---
--- IntE u = Helper.Create(default(IntE)) ---
--- LongE? s = Helper.Create(default(LongE)) ---
--- LongE? s = null ---
--- LongE u = Helper.Create(default(LongE)) ---
--- EmptyStruct? s = Helper.Create(default(EmptyStruct)) ---
--- EmptyStruct? s = null ---
--- EmptyStruct u = Helper.Create(default(EmptyStruct)) ---
--- NotEmptyStruct? s = Helper.Create(default(NotEmptyStruct)) ---
--- NotEmptyStruct? s = null ---
--- NotEmptyStruct u = Helper.Create(default(NotEmptyStruct)) ---
--- NotEmptyStructQ? s = Helper.Create(default(NotEmptyStructQ)) ---
--- NotEmptyStructQ? s = null ---
--- NotEmptyStructQ u = Helper.Create(default(NotEmptyStructQ)) ---
--- NotEmptyStructA? s = Helper.Create(default(NotEmptyStructA)) ---
--- NotEmptyStructA? s = null ---
--- NotEmptyStructA u = Helper.Create(default(NotEmptyStructA)) ---
--- NotEmptyStructQA? s = Helper.Create(default(NotEmptyStructQA)) ---
--- NotEmptyStructQA? s = null ---
--- NotEmptyStructQA u = Helper.Create(default(NotEmptyStructQA)) ---
--- EmptyStructGen<int>? s = Helper.Create(default(EmptyStructGen<int>)) ---
--- EmptyStructGen<int>? s = null ---
--- EmptyStructGen<int> u = Helper.Create(default(EmptyStructGen<int>)) ---
--- NotEmptyStructGen<int>? s = Helper.Create(default(NotEmptyStructGen<int>)) ---
--- NotEmptyStructGen<int>? s = null ---
--- NotEmptyStructGen<int> u = Helper.Create(default(NotEmptyStructGen<int>)) ---
--- NotEmptyS


Stack trace
   at JIT_Directed._nullabletypes_Desktop_boxunboxvaluetype_do_boxunboxvaluetype_do_._nullabletypes_Desktop_boxunboxvaluetype_do_boxunboxvaluetype_do_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Queued | OS | Arch | Column1
-- | -- | -- | --
2022-10-31T00:45:49.601Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr gcstress-extra   Checked-gcstress0xc_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=67446&view=ms.vss-test-web.build-test-results-tab&runId=1374084&resultId=110909&paneView=debug)
2022-09-27T21:28:00.087Z | osx.1015.amd64.open | x64 | [runtime-staging   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=32186&view=ms.vss-test-web.build-test-results-tab&runId=650398&resultId=100364&paneView=debug)
2022-09-23T06:53:56.591Z | osx.1200.amd64.open | x64 | [runtime-coreclr jitstress   Checked-jitstress2_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=27197&view=ms.vss-test-web.build-test-results-tab&runId=545628&resultId=104769&paneView=debug)
2022-09-21T21:30:34.502Z | osx.1015.amd64.open | x64 | [runtime-staging   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=25335&view=ms.vss-test-web.build-test-results-tab&runId=513594&resultId=100348&paneView=debug)
2022-09-21T06:09:57.685Z | osx.1200.amd64.open | x64 | [runtime-coreclr jitstress   Checked-jitstress1_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=24515&view=ms.vss-test-web.build-test-results-tab&runId=493404&resultId=104723&paneView=debug)
2022-09-05T10:07:05.729Z | ubuntu.1804.armarch.open | arm64 | [runtime-extra-platforms   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=4698&view=ms.vss-test-web.build-test-results-tab&runId=81638&resultId=100760&paneView=debug)
2022-10-31T08:17:03.923Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr crossgen2-composite gcstress   Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=67694&view=ms.vss-test-web.build-test-results-tab&runId=1378114&resultId=110788&paneView=debug)
2022-10-31T00:45:49.601Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr gcstress-extra   Checked-gcstress0xc_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=67446&view=ms.vss-test-web.build-test-results-tab&runId=1374084&resultId=110580&paneView=debug)
2022-10-31T00:09:11.85Z | osx.1200.arm64.open | arm64 | [runtime-coreclr gcstress-extra   Checked-gcstress0xc_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=67446&view=ms.vss-test-web.build-test-results-tab&runId=1373766&resultId=110918&paneView=debug)
2022-10-30T00:34:12.895Z | osx.1200.arm64.open | arm64 | [runtime-coreclr gcstress-extra   Checked-gcstress0xc_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=67178&view=ms.vss-test-web.build-test-results-tab&runId=1368242&resultId=110288&paneView=debug)
2022-09-27T21:28:00.087Z | osx.1015.amd64.open | x64 | [runtime-staging   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=32186&view=ms.vss-test-web.build-test-results-tab&runId=650398&resultId=100366&paneView=debug)
2022-09-23T06:53:56.591Z | osx.1200.amd64.open | x64 | [runtime-coreclr jitstress   Checked-jitstress2_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=27197&view=ms.vss-test-web.build-test-results-tab&runId=545628&resultId=104801&paneView=debug)
2022-09-21T21:30:34.502Z | osx.1015.amd64.open | x64 | [runtime-staging   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=25335&view=ms.vss-test-web.build-test-results-tab&runId=513594&resultId=100350&paneView=debug)
2022-09-21T06:09:57.685Z | osx.1200.amd64.open | x64 | [runtime-coreclr jitstress   Checked-jitstress1_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=24515&view=ms.vss-test-web.build-test-results-tab&runId=493404&resultId=105110&paneView=debug)
2022-09-05T10:07:05.729Z | ubuntu.1804.armarch.open | arm64 | [runtime-extra-platforms   Release](https://dev.azure.com/dnceng/public/_build/results?buildId=4698&view=ms.vss-test-web.build-test-results-tab&runId=81638&resultId=100872&paneView=debug)

**Comment by jakobbotsch** [comment] 2022-11-01 09:05
Duplicate of #77661

**Closed by jakobbotsch** 2022-11-01 09:05 UTC
Labels: arch-arm64, os-linux, os-mac-os-x, os-windows, GCStress, JitStress, area-CodeGen-coreclr, untriaged, blocking-clean-ci-optional
