### ISSUE TITLE
`initblk` Performance Degradation in `.NET 5+` compared to `.NET Framework`

### ISSUE THREAD

**Issue by ekfvoddl3536** [dotnet/runtime#93825] opened 2023-10-22 05:56 UTC
### Description

The recent implementation of `initblk` in `.NET 5+` is significantly slower than in `.NET Framework`.   
Is this intentional?  
  
In [this repository](https://github.com/ekfvoddl3536/initblk-issue), there's a small repository where you can test a program built with the same algorithm in `.NET 7.0` and `.NET Framework 4.8.1.`   
  
Upon execution, you can observe the following results:  
| Test # | `.NET 7.0` | `.NET Framework 4.8.1` |
| :-- | :--: | :--: |
| 1 | 1846.7471 ms | 1208.8673 ms |
| 2 | 1842.3441 ms | 1166.4357 ms |

### Configuration

OS: Windows 11 Pro (22H2, build: 22621.2428)  
Arch: x64  
CPU: 12th Gen Intel(R) Core(TM) i9-12900K  
RAM: DDR4 3200MHz 128.0GB  

### Data
  
The benchmark results below measure the time (ms) taken to zero memory approximately `11.11GiB` of data using a function with `initblk`.   
The source code used can be seen [here](https://github.com/ekfvoddl3536/initblk-issue/blob/master/InitblkPerformanceIssue/Program.cs#L50).  

| Test # | `.NET 7` (ms) | `.NET Framework 4.8.1` (ms) |
| ------ | -------------- | ------------------------------- |
| 1        | 2031.4894     | 1208.7394                             |
| 2        | 2055.606       | 1249.5666                             |
| 3        | 2032.1173     | 1271.1066                             |
| 4        | 1977.1216     | 1260.5579                             |
| 5        | 2012.8338     | 1252.7514                             |
| 6        | 1956.0654     | 1274.5913                             |
| 7        | 1953.4732     | 1259.7462                             |
| 8        | 1956.4205     | 1264.3926                             |
| 9        | 1963.82         | 1271.273                               |
| 10      | 1968.2378     | 1289.7236                             |
  
Adjusted size to `1.0GiB` and obtained additional data from `1,000` iterations:  
|        | `.NET 7` | `.NET Framework 4.8.1` |
| ------ | ----------- | ---------------  |
| Average (ms) |  181.64514889999995 | 118.045418 |
| Slowest (ms) | 307.6322 | 224.0306 |
| Fastest (ms) | 155.6197 | 101.1675 |
  
53.81% slower in the latest `.NET 7`.  

### Analysis

Most of the execution time is spent in the CLR implementation source code for `initblk`.   
I inferred this from the actual insertion of the call code.   
I wish this instruction worked as fast as or faster than before in the recent versions of `.NET 5+`.

**Comment by stephentoub** [comment] 2023-10-22 10:40
Doing microbenchmarks with DateTime and a single iteration is insufficient; even with a warmup iteration, things like tiered compilation will impact the results. When I put your code into a benchmarkdotnet benchmark, I don't see such degradation; performance for me is effectively the same across all the versions.

**Comment by ekfvoddl3536** [comment] 2023-10-22 11:30
I agree with your opinion.   
There's a lot to consider with just a single iteration. In my environment, even when benchmarking with benchmarkdotnet, .NET 7.0 still has a Mean of `145.6ms`, while .NET Framework 4.8.1 has `51.96ms`.  
I may not know the proper way to use benchmarkdotnet, so I ran it in separate projects (projects built in .NET 7 and .NET 4.8.1 respectively).  
  
I've attached the results:  
[Net70.md](https://github.com/dotnet/runtime/files/13063067/Net70.md)  
[Net481.md](https://github.com/dotnet/runtime/files/13063071/Net481.md)  
  
It still seems off. When I run it with benchmarkdotnet, the results show it's nearly 3 times slower.

**Comment by ekfvoddl3536** [comment] 2023-10-22 11:47
I've gathered additional data.   
With a size of 2GiB, .NET 7 is slower. It's nearly 3 times slower.  
  
I removed the Clear loop and modified the code to only execute initblk.  
I've attached the code used here.  
  
```csharp
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Jobs;
using BenchmarkDotNet.Running;

namespace InitblkPerformanceIssue
{
    [SimpleJob(RuntimeMoniker.Net481, baseline: true)]
    [SimpleJob(RuntimeMoniker.Net70)]
    [MarkdownExporter]
    [MinColumn, MaxColumn]
    public class Program
    {
        public const long NUMBER_OF_BYTES = 0x8000_0000; // 2GiB

        [Params(0x80_0000, NUMBER_OF_BYTES)]
        public static long Bytes;

        private static IntPtr Array;

        [GlobalSetup]
        public void Setup() => Array = Marshal.AllocHGlobal(new IntPtr(Bytes));

        [GlobalCleanup]
        public void Cleanup() => Marshal.FreeHGlobal(Array);

        [Benchmark]
        public unsafe void Initblk() => Unsafe.InitBlock((byte*)Array, 0, (uint)Bytes);

        public static void Main() => BenchmarkRunner.Run<Program>();
    }
}
```
results:  
[Net70 (3).md](https://github.com/dotnet/runtime/files/13063115/Net70.3.md)  
[Net481 (3).md](https://github.com/dotnet/runtime/files/13063116/Net481.3.md)

**Comment by EgorBo** [comment] 2023-10-22 12:14
```
| Method  | Job                  | Runtime              | Bytes      | Mean         |
|-------- |--------------------- |--------------------- |----------- |-------------:|
| Initblk | .NET 7.0             | .NET 7.0             | 2147483648 | 30,567.88 us |
| Initblk | .NET 8.0             | .NET 8.0             | 2147483648 | 30,031.37 us |
| Initblk | .NET Framework 4.8.1 | .NET Framework 4.8.1 | 2147483648 | 32,568.97 us |

| Initblk | .NET 7.0             | .NET 7.0             | 8388608    |     98.85 us |
| Initblk | .NET 8.0             | .NET 8.0             | 8388608    |     98.46 us |
| Initblk | .NET Framework 4.8.1 | .NET Framework 4.8.1 | 8388608    |    122.84 us |
```

I can't repro it locally, initblk is just a memset call.

**Comment by ekfvoddl3536** [comment] 2023-10-22 12:17
Given the advice on data cherry-picking, I've attached test data ranging from 128 bytes to 2GiB. Based on the results, up to 67108864 bytes, .NET 7 is either ahead or similar in performance. However, beyond 67108864 bytes, .NET 7 suddenly starts to underperform compared to .NET 4.8.1.  
[Net70 128b-2gib.md](https://github.com/dotnet/runtime/files/13063197/Net70.128b-2gib.md)
[Net481 128b-2gib.md](https://github.com/dotnet/runtime/files/13063198/Net481.128b-2gib.md)

**Comment by ekfvoddl3536** [comment] 2023-10-22 12:20
It's possible that something in my environment is influencing the results.   
I'll gather more data and revisit this later.  
  
 Thank you for your attention.

**Comment by ekfvoddl3536** [comment] 2023-10-23 02:58
The `initblk` instruction performs faster on netfx than on the latest .NET when handling segments larger than `64.0MiB`.  

According to the data I've collected, there's no issue on the Intel Skylake microarchitecture. In fact, on CPUs based on the Skylake microarchitecture, the latest .NET still outperforms.  

However, on more recent microarchitectures than Skylake, such as Intel Sunny Cove and Intel Golden Cove, netfx seems to be faster than .NET.  

I am making efforts to gather more data, and I do not believe that the data I currently have holds significant weight to back my claim. I will continue to upload the results to [this repository](https://github.com/ekfvoddl3536/initblk-issue) as I obtain more data.  

I hope this helps with the analysis.

**Comment by MichalPetryka** [comment] 2023-10-23 20:05
> initblk is just a memset call

Like @EgorBo said, both on .Net Framework and .Net 5+ `initblk` just calls into the CRT `memset`. Things like memory alignment are more likely to cause difference here than what runtime calls the mentioned API.

**Comment by Wraith2** [comment] 2023-10-23 22:35
What is the cause of wanting to zero this much memory at once? is this a specific use-case for a certain class of software? if so what is that software doing?

**Comment by ekfvoddl3536** [comment] 2023-10-24 04:02
@MichalPetryka 
Thank you. I understand your point about `initblk` calling CRT's `memset`. However, based on the data I've collected, I've observed performance differences between .NET Framework and .NET 5+ under certain conditions.

Specifically, on processors based on the Skylake microarchitecture, .NET Framework is slower than .NET regardless of the memory size. However, on processors based on Sunny Cove, Golden Cove, and Golden Cove + Gracemont, .NET Framework starts to show a faster pattern than .NET from 32 or 64 MiB.

What I find important is the common pattern in this data.
This pattern was not observed only in the Skylake-based 8168 processor.
I still find that peculiar.

**Comment by jeffhandley** [comment] 2024-07-27 22:21
@EgorBo / @stephentoub -- I'm closing this as not planned with it this observed performance difference being acceptable. Please reopen if you think we would take action on this.

Thank you for the data collection and reporting this nonetheless, @ekfvoddl3536.

**Closed by jeffhandley** 2024-07-27 22:21 UTC
Labels: area-System.Runtime, tenet-performance, needs-further-triage

**Comment by EgorBo** [comment] 2024-07-27 22:48
We've made some changes to `initblk` handling in .NET 9.0 so you might want to try that. I agree that we can close it
