### ISSUE TITLE
Environment.SetEnvironmentVariables() creates REG_SZ instead of REG_EXPAND_SZ

### ISSUE THREAD

**Issue by htcfreek** [dotnet/runtime#89695] opened 2023-07-30 16:59 UTC
### Description

Using `Environment.SetEnvironmentVariables(EnvironmentVariableTarget.Machine/User)` creates a `REG_SZ` value instead of a `REG_EXPAND_SZ` value in the registry. This happens on creating new variables and on updating existing ones.

The problem is that these variables can't be expanded on reading them because the value is not saved in a `REG_EXPAND_SZ`.

### Reproduction Steps

My POC code:

```CSHARP
using System;

namespace htcfreek
{
    class EnvVarTest {

        // Main Method
        static public void Main(String[] args)
        {

            Console.WriteLine("--- Test 'Set var' start ---");

            Console.WriteLine("- Set user vars -");
            Environment.SetEnvironmentVariable("TestVar1", "123", EnvironmentVariableTarget.User);
            Environment.SetEnvironmentVariable("TestVar2", "%TestVar1%", EnvironmentVariableTarget.User);

            Console.WriteLine("--- Test 'Set var' end ---");

            Console.ReadLine();
        }
    }
}
```

### Expected behavior

Calling the method for target user or target machine always creates `REG_EXPAND_SZ` value in the Registry like when using the ui dialog in Windows.

### Actual behavior

- **For new variables**: Calling the method for target user or target machine creates a `REG_SZ` value in the Registry.
- **For existing variables**: Calling the method for target user or target machine deletes the existing registry value and creates a `REG_SZ` value in the Registry.

### Regression?

Don't know this.

### Known Workarounds

No.

### Configuration

- Windows 10 21H1 (19044.3086)
- `.Net FX 4.8.1` as well as `.Net 7.0`
- OS arch: x64
- Build arch: Any CPU

**Comment by htcfreek** [comment] 2023-07-30 17:06
@crutkas, @stefansjfw
This .Net bug might be a problem for the `PowerToys Environment Variable Editor` (microsoft/PowerToys/issues/16424).

**Comment by jkotas** [comment] 2023-07-30 21:35
This is related to or duplicate of https://github.com/dotnet/runtime/issues/1442 . 

`Environment.SetEnvironmentVariable(s)` creates `REG_SZ` keys and `Environment.GetEnvironmentVariable(s)` always expands against current process environment. This policy choice may not work well for you, but it is not a bug. Changing this policy would be a breaking change.

If you want to have full control over the types of registry keys and how they get expanded, you can use the registry APIs directly.

**Comment by tannergooding** [comment] 2023-08-07 21:36
Closing as per Jan's comment above.

**Closed by tannergooding** 2023-08-07 21:36 UTC
Labels: area-System.Runtime, untriaged
