### ISSUE TITLE
Why System.Diagnostics.Process.MainWindowTitle returns empty string on Linux?

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#31658] opened 2020-02-03 14:29 UTC
System.Diagnostics.Process.MainWindowTitle is empty for all processes on Linux, even when the application has root rights. Tested on Ubuntu 19.10 64bit with .NET Core 3.1 console application.

## Repro
`sudo ./ConsoleApp2`
```
class Program
    {
        static void Main(string[] args)
        {
            var procs = Process.GetProcesses();
            foreach (var proc in procs)
            {
                Console.WriteLine($"Process: {proc.ProcessName}, MainWindowTitle: {(string.IsNullOrEmpty(proc.MainWindowTitle) ? "<EMPTY>" : proc.MainWindowTitle)}");
            }
        }
    }
```

## Result:
![image](https://user-images.githubusercontent.com/14368203/73660921-0e292080-4691-11ea-9531-d6d2bf0659df.png)

**Comment by stephentoub** [comment] 2020-02-03 15:02
> ?

From where do you recommend Process get the MainWindowTitle?

By design it is currently hardcoded to return string.Empty for lack of something better and general enough:
https://github.com/dotnet/runtime/blob/5b3052937b6f16d9e9dfdb642e006dfc2d0cc778/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs#L1001
If you can suggest something better, it can be changed accordingly.

**Comment by Entomy** [comment] 2020-02-03 15:08
Would this be helpful?

https://stackoverflow.com/questions/45625222/c-get-windows-title-using-process-name

**Comment by stephentoub** [comment] 2020-02-03 15:10
> Would this be helpful?

Thank you, but no, that's about Windows, and we already have a solution for Windows:
https://github.com/dotnet/runtime/blob/5b3052937b6f16d9e9dfdb642e006dfc2d0cc778/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Win32.cs#L205

**Comment by Entomy** [comment] 2020-02-03 15:11
That's what I get for trying to read C++ code 😅

**Comment by Entomy** [comment] 2020-02-03 15:25
I think you should be able to get it using [`XFetchName()`](https://code.woboq.org/data/symbol.html?root=../qt5/&ref=XFetchName) with the caveat that it requires the WM be [EWMH](https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#idm45384480109680) compliant and support `_NET_WM_VISIBLE_NAME` and `_NET_WM_NAME`. Most WM's are, and the ones that aren't are unlikely to be used by the same crowd that'd be using .NET.

**Comment by Symbai** [comment] 2020-02-03 15:27
> 
> 
> By design it is currently hardcoded to return string.Empty for lack of something better and general enough:
> 

Then you should update the docs to reflect that? https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.mainwindowtitle?view=netcore-3.1

**Comment by stephentoub** [comment] 2020-02-03 15:30
> I think you should be able to get it using XFetchName() 

That depends on X11.  If we could do it without taking an additional statically-linked dependency / light-up only if it's available at run-time, and if it would address the issue for enough consumers, it's an option.

> Then you should update the docs to reflect that?

This is following suit with the docs stating `If the associated process does not have a main window (so that MainWindowHandle is zero), MainWindowTitle is an empty string ("")`.  But they could certainly be augmented to say that on some platforms we may not be able to determine this and so similarly return an empty string. The docs are open source at https://github.com/dotnet/dotnet-api-docs.  You are welcome and encouraged to submit an issue and/or PR.  Thanks.

**Comment by Entomy** [comment] 2020-02-03 15:40
> If the associated process does not have a main window (so that MainWindowHandle is zero), MainWindowTitle is an empty string ("").

My conclusion from this is that if you get an empty string, there shouldn't be a main window. I don't believe this is "following suit with the docs". I put in a PR for the docs.

**Comment by Entomy** [comment] 2020-02-03 15:41
> That depends on X11. If we could do it without taking an additional statically-linked dependency / light-up only if it's available at run-time, and if it would address the issue for enough consumers, it's an option.

Maybe there's something available in `/proc`? I've never done a deep dive into that though.

**Comment by stephentoub** [comment] 2020-02-03 15:46
> My conclusion from this is that if you get an empty string, there shouldn't be a main window. I don't believe this is "following suit with the docs".

Now we're arguing over semantics, but my point was that it's currently saying string.Empty is returned if there isn't a main window, and the difference between platforms is how it determines that.

> Maybe there's something available in /proc?

Windowing information is not surfaced in procfs.

**Comment by Entomy** [comment] 2020-02-03 16:08
> That depends on X11. If we could do it without taking an additional statically-linked dependency / light-up only if it's available at run-time, and if it would address the issue for enough consumers, it's an option.

And now thinking about this, it only solves the problem for a subset of Unix users, and an ever decreasing subset at that. Between whatever macOS is calling their windowing system now, Wayland, Mir, and TWIN, there's a lot of competing systems in that space, and no clear way to universally get the window title.

I don't envy you.

**Comment by stephentoub** [comment] 2020-02-03 16:09
>  it only solves the problem for a subset of Unix users, and an ever decreasing subset at that.

Right :-(

**Comment by wfurt** [comment] 2020-02-03 19:44
cc: @tmds

**Comment by Symbai** [comment] 2020-02-03 21:43
> 
> 
> This is following suit with the docs stating `If the associated process does not have a main window (so that MainWindowHandle is zero), MainWindowTitle is an empty string ("")`. 

If I have two windows with two window titles on Windows and Linux and in one it returns an empty string and in the other the window title, then my first assumption is that it is a bug. Then I go check the docs and the docs say, you quoted it yourself `does not have a main window` [...] my assumption stays. Because the Linux process clearly has a main window, just like the Windows process.

In order to know it is not a bug but a design choice I would either:
- Be a Linux expert knowing there is no such native API to retreive the window title
- Be a C# runtime expert knowing that the source simply returns string.empty for all processes in all cases when running on linux.

But most people are not and it is not clear for us at first place and it doesn't hurt to add a single additional line to the docs, thank you.

**Comment by stephentoub** [comment] 2020-02-03 21:45
>  it doesn't hurt to add a single additional line to the docs

That's why I suggested a PR could be submitted to the docs repo, which @Entomy kindly did.

**Comment by Entomy** [comment] 2020-02-03 21:45
Yup, Stephen and I put it together [here](https://github.com/dotnet/dotnet-api-docs/pull/3844).

**Comment by adamsitnik** [comment] 2020-06-25 18:05
The docs have been updated in https://github.com/dotnet/dotnet-api-docs/pull/3844, closing.

**Closed by adamsitnik** 2020-06-25 18:05 UTC
Labels: area-System.Diagnostics.Process, os-linux, question
