### ISSUE TITLE
blazor: `Assertion at /__w/1/s/src/mono/mono/metadata/assembly.c:1374`

### ISSUE THREAD

**Issue by weibaohui** [dotnet/runtime#54446] opened 2021-06-19 04:21 UTC
Web Browse:
Assertion at /__w/1/s/src/mono/mono/metadata/assembly.c:1374, condition `<disabled>' not met  6.0.0-preview.5.21301.17

C# Code
```c#
public partial class FetchData:ComponentBase
    {
         WeatherForecast[] forecasts;
        [Inject]
        private HttpClient Http  { get; set; }

        protected override async Task  OnInitializedAsync()
        {
            forecasts = await Http.GetFromJsonAsync<WeatherForecast[]>("https://localhost:4001/WeatherForecast");
        }
}
```

using netcore 6.0.0-preview.5.21301.17

**Comment by pavelsavara** [comment] 2021-06-22 13:57
I was not able to reproduce it with simple [unit test](https://github.com/pavelsavara/runtime/commit/9cf5d591d06d467b63dfcf78c24b95bab1752171)

It seems to me that it's trying to load some assembly and the callback failed. See
https://github.com/dotnet/runtime/blob/3782e6e41cfaf76ec9ae4117722f835596026b1a/src/mono/mono/metadata/assembly.c#L1374

This is not network related issue in my opinion.

@weibaohui, could you please share more complete stack trace ? 
Also information on what callback or what library was loaded if you could get it.  Thanks!

**Comment by pavelsavara** [comment] 2021-07-14 11:57
@steveisok @akoeplinger what would be proper error handling for the assembly load hook failure ? Should we throw exception to user code ?
What would be the WASM scenario under which this could happen ? 
Since we don't have the stack trace, my guess is corrupt/incomplete/missing assembly download. Or maybe corrupt preview AOT image ?
But I don't understand the workflow here yet. Does assembly download happen in the hook ? Or it was already in memory and valid when the hooks are triggered ?

**Comment by lambdageek** [comment] 2021-07-16 16:44
I'm assuming this is using `dotnet watch`. If so, this is a duplicate of https://github.com/dotnet/aspnetcore/issues/33152.  The workaround was in https://github.com/dotnet/aspnetcore/pull/33263 in .net 6 preview 6.  A fix of the underlying issue in Mono is in https://github.com/dotnet/runtime/pull/55202 and will be in .net 6 preview 7

**Comment by pavelsavara** [comment] 2021-07-26 13:30
@lambdageek could this be closed now ?

**Closed** 2021-07-27 13:47 UTC
Labels: arch-wasm, area-AssemblyLoader-mono
