### ISSUE TITLE
Unable to load Analyzer assembly in .NET 6.0

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/runtime#53476] opened 2021-05-30 04:50 UTC
Suddenly I am receiving the following warning and error:

Warning: 

> Unable to load Analyzer assembly C:\Users\TanvirArjel\\.nuget\packages\microsoft.extensions.logging\5.0.0\analyzers\dotnet\cs\Microsoft.Extensions.Logging.Generators.dll: Could not find a part of the path 'C:\Users\TanvirArjel\\.nuget\packages\microsoft.extensions.logging\5.0.0\analyzers\dotnet\cs\Microsoft.Extensions.Logging.Generators.dll'.

Error: 

> CSC : error CS0006: Metadata file 'C:\Users\TanvirArjel\\.nuget\packages\microsoft.extensions.logging\5.0.0\analyzers\dotnet\cs\Microsoft.Extensions.Logging.Generators.dll' could not be found [D:\GitHub\EFCore.GenericRepository\src\TanvirArjel.EFCore.GenericRepository.csproj]

Project files is:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;netcoreapp3.1;net5.0;net6.0</TargetFrameworks>
    <LangVersion>8.0</LangVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>-->
    <AssemblyName>TanvirArjel.EFCore.GenericRepository</AssemblyName>
    <RootNamespace>TanvirArjel.EFCore.GenericRepository</RootNamespace>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="6.0.0-*" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net5.0'">
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="5.0.*" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp3.1'">
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="3.1.*" />
  </ItemGroup>
  
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="5.0.*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.333">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.2.*" />
  </ItemGroup>

</Project>
```

**If I remove `.NET 6.0` from TargetFrameworks then both warning and error go away.**

However, How can I fix the issue right now without removing .NET 6.0 support?

**Comment by SimonCropp** [comment] 2021-06-02 00:02
more context: here is the repo https://github.com/TanvirArjel/EFCore.GenericRepository and here is the commit that should fail https://github.com/TanvirArjel/EFCore.GenericRepository/commit/0323871b35e5a49c197a83e1869ccf74c7a7a110

as for the bug, it is weird.  so only v6 of `microsoft.extensions.logging` has analyzers. ie earlier versions do not. so it seems to be conflating "v6 has analyzers" with "the microsoft.extensions.logging nuget has analyzers"

@TanvirArjel as for a solution for you....  the current assumption of `TanvirArjel.EFCore.GenericRepository is that: wanting to consume a certain version of the runtime implies someone wants to ref a corresponding version of ef. this is not correct. eg i might want to use ef 3 on net 6.  So i recommend wither only supporting one version of ef, or (if u want to keep supporting many) release named nugets that correspond to the ef version eg `TanvirArjel.EFCore6.GenericRepository` and `TanvirArjel.EFCore5.GenericRepository` etc

**Comment by SimonCropp** [comment] 2021-06-02 00:09
i think this is a duplicate of https://github.com/dotnet/runtime/issues/53297

**Comment by krwq** [comment] 2021-07-12 18:07
Is this a dup of https://github.com/dotnet/sdk/issues/18148 ?

**Comment by TanvirArjel** [comment] 2021-07-12 18:12
@krwq What! Why it is in `Milestone 7.0.0`? Then how shall we update our packages to support `v6.0.0`. Currently, adding to support for the .NET 6.0 in our NuGet packages does not work due to this blocking issue.

**Comment by TanvirArjel** [comment] 2021-07-12 18:16
@krwq This is a blocking issue. Download this [this](https://github.com/TanvirArjel/EFCore.GenericRepository) repository and enable .NET 6.0 support and build. You will see the build failed.

**Comment by TanvirArjel** [comment] 2021-07-12 18:23
@krwq 
> Is this a dup of dotnet/sdk#18148

Yes! Seems like so.

**Comment by safern** [comment] 2021-07-27 18:22
Closing this issue as a dup of: https://github.com/dotnet/sdk/issues/18148 which was fixed and the fix should be available on the Preview7 SDK.

**Closed by safern** 2021-07-27 18:22 UTC
Labels: area-Meta
