### ISSUE TITLE
Test failure:baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#56950] opened 2021-08-06 01:26 UTC
Run: [runtime-coreclr gcstress-extra 20210803.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1274221&view=ms.vss-test-web.build-test-results-tab&runId=37705790&resultId=110463&paneView=debug)

Failed test:
```
CoreCLR Linux arm64 Checked gcstress0xc_jitminopts_heapverify1 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh

```
**Error message:**
```
Process terminated. Parallel crash in main thread
at System.Environment.FailFast(System.String)
at ParallelCrash.Main(System.String[])
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f7a78a2e8)

cmdLine:/root/helix/work/workitem/baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh Timed Out (timeout in milliseconds: 5400000 from variable __TestTimeout, start: 8/4/2021 2:25:23 AM, end: 8/4/2021 3:55:23 AM)

Return code:      -100
Raw output file:      /root/helix/work/workitem/uploads/Reports/baseservices.exceptions/simple/ParallelCrash/ParallelCrash.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun ParallelCrash.dll ''
Gathering state for process 1596 corerun
Crashing thread 0000063c signal 00000006
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.1596.dmp
Written 138706944 bytes (33864 pages) to core file
Dump successfully written

cmdLine:/root/helix/work/workitem/baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh Timed Out (timeout in milliseconds: 5400000 from variable __TestTimeout, start: 8/4/2021 2:25:23 AM, end: 8/4/2021 3:55:23 AM)
Test Harness Exitcode is : -100
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh
Expected: True
Actual:   False


Stack trace
   at baseservices_exceptions._simple_ParallelCra_ParallelCra_._simple_ParallelCrash_ParallelCrash_sh() in baseservices.exceptions.XUnitWrapper.dll:token 0x60000ea+0x295
```

**Comment by VincentBu** [comment] 2021-09-22 01:37
Failed again in：[runtime-coreclr gcstress-extra 20210919.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1371559&view=ms.vss-test-web.build-test-results-tab&runId=40016028&resultId=111144&paneView=debug)

Failed test:
```
CoreCLR Linux arm64 Checked gcstress0xc_tailcallstress @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh

```
**Error message:**
```
Process terminated. Parallel crash in main thread
at System.Environment.FailFast(System.String)
at ParallelCrash.Main(System.String[])
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7faf367808)

cmdLine:/root/helix/work/workitem/e/baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh Timed Out (timeout in milliseconds: 5400000 from variable __TestTimeout, start: 9/19/2021 11:46:45 PM, end: 9/20/2021 1:16:45 AM)

Return code:      -100
Raw output file:      /root/helix/work/workitem/uploads/Reports/baseservices.exceptions/simple/ParallelCrash/ParallelCrash.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false ParallelCrash.dll ''
Gathering state for process 5867 corerun
Crashing thread 000016eb signal 00000006
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.5867.dmp
Written 138813440 bytes (33890 pages) to core file
Dump successfully written

cmdLine:/root/helix/work/workitem/e/baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh Timed Out (timeout in milliseconds: 5400000 from variable __TestTimeout, start: 9/19/2021 11:46:45 PM, end: 9/20/2021 1:16:45 AM)
Test Harness Exitcode is : -100
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/e/baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh
Expected: True
Actual:   False


Stack trace
   at baseservices_exceptions._simple_ParallelCra_ParallelCra_._simple_ParallelCrash_ParallelCrash_sh()
```

**Comment by VincentBu** [comment] 2021-12-20 01:11
Failed again in: [runtime-coreclr outerloop  20211218.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1519672&view=ms.vss-test-web.build-test-results-tab&runId=43204780&paneView=debug&resultId=110352)

Failed test:
```
CoreCLR OSX x64 Checked @ OSX.1014.Amd64.Open

- baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh

```
**Error message:**
```
Process terminated. Parallel crash in main thread
at System.Environment.FailFast(System.String)
at ParallelCrash.Main(System.String[])
task_for_pid(21890) FAILED 5 (os/kern) failure

cmdLine:/private/tmp/helix/working/A5E6096E/w/9D7D08E7/e/baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh Timed Out (timeout in milliseconds: 600000 from variable __TestTimeout, start: 12/18/2021 3:11:26 AM, end: 12/18/2021 3:21:26 AM)

Return code:      -100
Raw output file:      /tmp/helix/working/A5E6096E/w/9D7D08E7/uploads/Reports/baseservices.exceptions/simple/ParallelCrash/ParallelCrash.output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/A5E6096E/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false ParallelCrash.dll ''

cmdLine:/private/tmp/helix/working/A5E6096E/w/9D7D08E7/e/baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh Timed Out (timeout in milliseconds: 600000 from variable __TestTimeout, start: 12/18/2021 3:11:26 AM, end: 12/18/2021 3:21:26 AM)
Test Harness Exitcode is : -100
To run the test:

set CORE_ROOT=/tmp/helix/working/A5E6096E/p
/private/tmp/helix/working/A5E6096E/w/9D7D08E7/e/baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh
Expected: True
Actual:   False


Stack trace
   at baseservices_exceptions._simple_ParallelCra_ParallelCra_._simple_ParallelCrash_ParallelCrash_sh()
```

**Comment by VincentBu** [comment] 2021-12-28 01:25
Failed again in: [runtime-coreclr gcstress-extra 20211226.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1527021&view=ms.vss-test-web.build-test-results-tab&runId=43342066&paneView=debug&resultId=111046)

Failed test:
```
CoreCLR Linux arm64 Checked gcstress0xc_jitstress2 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- baseservices/exceptions/simple/ParallelCrashMainThread/ParallelCrashMainThread.sh

```
**Error message:**
```
Process terminated. Parallel crash in main thread
at System.Environment.FailFast(System.String)
at ParallelCrash.Main(System.String[])

cmdLine:/root/helix/work/workitem/e/baseservices/exceptions/simple/ParallelCrashMainThread/ParallelCrashMainThread.sh Timed Out (timeout in milliseconds: 5400000 from variable __TestTimeout, start: 12/26/2021 11:56:20 PM, end: 12/27/2021 1:26:20 AM)

Return code:      -100
Raw output file:      /root/helix/work/workitem/uploads/Reports/baseservices.exceptions/simple/ParallelCrashMainThread/ParallelCrashMainThread.output.txt
Raw output:
BEGIN EXECUTION
export CDPATH=/root/helix/work/workitem/e/baseservices/exceptions/simple/ParallelCrashMainThread
/usr/bin/env bash ../ParallelCrash/ParallelCrash.sh '1'
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false ParallelCrash.dll '1'
Gathering state for process 5268 corerun
Crashing thread 00001494 signal 00000006
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.5268.dmp
Written 138477568 bytes (33808 pages) to core file
Dump successfully written

cmdLine:/root/helix/work/workitem/e/baseservices/exceptions/simple/ParallelCrashMainThread/ParallelCrashMainThread.sh Timed Out (timeout in milliseconds: 5400000 from variable __TestTimeout, start: 12/26/2021 11:56:20 PM, end: 12/27/2021 1:26:20 AM)
Test Harness Exitcode is : -100
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/e/baseservices/exceptions/simple/ParallelCrashMainThread/ParallelCrashMainThread.sh
Expected: True
Actual:   False


Stack trace
   at baseservices_exceptions._simple_ParallelCraMainThread_ParallelCraMainThread_._simple_ParallelCrashMainThread_ParallelCrashMainThread_sh()
```

**Comment by VincentBu** [comment] 2022-01-17 04:10
Failed again in: [runtime-coreclr gcstress-extra 20220115.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1555331&view=ms.vss-test-web.build-test-results-tab&runId=43858716&paneView=debug&resultId=111011)

Failed test:
```
CoreCLR Linux arm64 Checked gcstress0xc_zapdisable @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh

CoreCLR Linux x64 Checked gcstress0xc_zapdisable_jitstress2 @ Ubuntu.1804.Amd64.Open

- baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh

```
**Error message:**
```
Process terminated. Parallel crash in main thread
at System.Environment.FailFast(System.String)
at ParallelCrash.Main(System.String[])

cmdLine:/root/helix/work/workitem/e/baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh Timed Out (timeout in milliseconds: 5400000 from variable __TestTimeout, start: 1/15/2022 11:15:51 PM, end: 1/16/2022 12:45:51 AM)

Return code:      -100
Raw output file:      /root/helix/work/workitem/uploads/Reports/baseservices.exceptions/simple/ParallelCrash/ParallelCrash.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false ParallelCrash.dll ''
Gathering state for process 5482 corerun
Crashing thread 0000156a signal 00000006
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.5482.dmp
Written 217366528 bytes (53068 pages) to core file
Dump successfully written

cmdLine:/root/helix/work/workitem/e/baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh Timed Out (timeout in milliseconds: 5400000 from variable __TestTimeout, start: 1/15/2022 11:15:51 PM, end: 1/16/2022 12:45:51 AM)
Test Harness Exitcode is : -100
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/e/baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh
Expected: True
Actual:   False


Stack trace
   at baseservices_exceptions._simple_ParallelCra_ParallelCra_._simple_ParallelCrash_ParallelCrash_sh()
```

**Comment by VincentBu** [comment] 2022-03-15 01:20
Failed again in: [runtime-coreclr gcstress-extra 20220313.1
](https://dev.azure.com/dnceng/public/_build/results?buildId=1661320&view=ms.vss-test-web.build-test-results-tab&runId=45724288&resultId=110109&paneView=debug)

Failed test:
```
CoreCLR OSX arm64 Checked gcstress0xc_jitminopts_heapverify1 @ OSX.1200.ARM64.Open

- baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh

```
**Error message:**
```
/private/tmp/helix/working/A4B2094E/w/A1EC0928/e/baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh: line 370: 16727 Trace/BPT trap: 5       (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /tmp/helix/working/A4B2094E/w/A1EC0928/uploads/Reports/baseservices.exceptions/simple/ParallelCrash/ParallelCrash.output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/A4B2094E/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false ParallelCrash.dll ''
Expected: 134
Actual: 133
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/tmp/helix/working/A4B2094E/p
/private/tmp/helix/working/A4B2094E/w/A1EC0928/e/baseservices/exceptions/simple/ParallelCrash/ParallelCrash.sh
Expected: True
Actual:   False


Stack trace
   at baseservices_exceptions._simple_ParallelCra_ParallelCra_._simple_ParallelCrash_ParallelCrash_sh()
```

**Comment by AntonLapounov** [comment] 2022-08-13 00:15
Closing as a duplicate of #72755.

**Closed by AntonLapounov** 2022-08-13 00:15 UTC
Labels: arch-arm64, os-linux, GCStress, area-VM-coreclr
