### ISSUE TITLE
Test time out for global::Test_refarg_f8_cs.App.TestEntryPoint() in gcstress0x3-gcstress0xc

### ISSUE THREAD

**Issue by JulieLeeMSFT** [dotnet/runtime#104319] opened 2024-07-02 18:35 UTC
Pipeline: [runtime-coreclr gcstress0x3-gcstress0xc](https://dev.azure.com/dnceng-public/public/_build?definitionId=112&_a=summary): [20240630.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=725436)

coreclr linux x64 Checked gcstress0x3 @ Ubuntu.2204.Amd64.Open
Methodical_d1.0.1
Methodical_do.0.1 
Methodical_r1.0.1
Methodical_ro.0.1
coreclr osx arm64 Checked gcstress0x3 @ OSX.1200.ARM64.Open
Methodical_d1.0.1

[Log](https://[helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-008af1b59f89402fbf/Methodical_d1.0.1/1/console.ce62eda4.log?helixlogtype=result](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-008af1b59f89402fbf/Methodical_d1.0.1/1/console.ce62eda4.log?helixlogtype=result)): 
```
15:03:47.792 Running test: global::Test_refarg_f8_cs.App.TestEntryPoint()
Child process took too long. Timed out... Exiting...
App Exit Code: 110
Expected: 100
Actual: 110
END EXECUTION - FAILED
```

**Comment by janvorli** [comment] 2024-07-08 14:46
This should be fixed by #103738. The timeout was caused by WaitForPendingFinalizers never returning as the finalizer thread kept generating finalizable garbage forever.

**Closed by janvorli** 2024-07-08 14:46 UTC
Labels: area-CodeGen-coreclr, blocking-clean-ci-optional, Priority:2
