### ISSUE TITLE
IConfiguration with TimeSpan

### ISSUE THREAD

**Issue by GoldenUA** [dotnet/runtime#93850] opened 2023-10-23 09:12 UTC
### Description

Strange behavior when serializing TimeSpan

### Reproduction Steps

If you specify TimeSpan in the config for 23 hours, then everything works correctly

"duration": "23:00:00"

![image](https://github.com/dotnet/runtime/assets/46490664/48ba16e8-845e-4a9d-8e1d-a3e4c0bdb245)

But if you specify 24, it turns into a day with this notation, which is an unexpected surprise

"duration": "24:00:00"

![image](https://github.com/dotnet/runtime/assets/46490664/778f18ee-f844-408d-9b9f-9616532574b6)

### Expected behavior

It is expected that this will also be serialized in 24 hours or 1 day

### Actual behavior

Now it turns into 24 days

**Comment by huoyaoyuan** [comment] 2023-10-23 10:03
Duplicate of #40316

**Closed** 2023-10-23 15:25 UTC
Labels: untriaged, area-System.DateTime
