### ISSUE TITLE
Test failure JIT\\Methodical\\MDArray\\GaussJordan\\plainarr_cs_d\\plainarr_cs_d.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#64362] opened 2022-01-27 01:12 UTC
Run: [runtime-coreclr outerloop 20220126.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1573034&view=ms.vss-test-web.build-test-results-tab&runId=44176292&paneView=debug&resultId=106583)

Failed test:
```
R2R-CG2 windows arm Checked @ Windows.10.Arm64v8.Open

- JIT\\Methodical\\MDArray\\GaussJordan\\plainarr_cs_d\\plainarr_cs_d.cmd

R2R-CG2 Linux arm64 Checked @ (Alpine.314.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm64v8-20210910135810-8a6f4f3

- JIT/HardwareIntrinsics/General/Vector64_1/Vector64_1_ro/Vector64_1_ro.sh

```

**Error message:**
```
Could Not Find D:\h\w\B010096B\w\AA7E0938\e\JIT\Methodical\MDArray\GaussJordan\plainarr_cs_d\IL-CG2\composite-r2r.dll
Could Not Find D:\h\w\B010096B\w\AA7E0938\e\JIT\Methodical\MDArray\GaussJordan\plainarr_cs_d\plainarr_cs_d.dll.rsp
Fatal error. Internal CLR error. (0x80131506)
at System.SZArrayHelper.GetEnumerator[Internal.JitInterface.CorJitFlag, ILCompiler.ReadyToRun, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null]
at Internal.JitInterface.CorInfoImpl.getJitFlags(Internal.JitInterface.CORJIT_FLAGS ByRef, UInt32)
at Internal.JitInterface.CorInfoImpl._getJitFlags(IntPtr, IntPtr*, Internal.JitInterface.CORJIT_FLAGS*, UInt32)
at Internal.JitInterface.CorInfoImpl.JitCompileMethod(IntPtr ByRef, IntPtr, IntPtr, IntPtr, Internal.JitInterface.CORINFO_METHOD_INFO ByRef, UInt32, IntPtr ByRef, UInt32 ByRef)
at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(ILCompiler.DependencyAnalysis.IMethodNode, Internal.IL.MethodIL)
at Internal.JitInterface.CorInfoImpl.CompileMethod(ILCompiler.DependencyAnalysis.ReadyToRun.MethodWithGCInfo, ILCompiler.Logger)
at ILCompiler.ReadyToRunCodegenCompilation.<ComputeDependencyNodeDependencies>b__35_0(ILCompiler.DependencyAnalysisFramework.DependencyNodeCore1<ILCompiler.DependencyAnalysis.NodeFactory>) at System.Threading.Tasks.Parallel+<>c__DisplayClass33_02[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForEachWorker>b__0(Int32)
at System.Threading.Tasks.Parallel+<>c__DisplayClass19_0`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef, Int32, Boolean ByRef)
at System.Threading.Tasks.TaskReplicator+Replica.Execute()
at System.Threading.Tasks.TaskReplicator+Replica+<>c.<.ctor>b__4_0(System.Object)
at System.Threading.Tasks.Task.InnerInvoke()
at System.Threading.Tasks.Task+<>c.<.cctor>b__271_0(System.Object)
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
at System.Threading.Thread.StartCallback()

Return code:      1
Raw output file:      D:\h\w\B010096B\w\AA7E0938\uploads\Reports\JIT.Methodical\MDArray\GaussJordan\plainarr_cs_d\plainarr_cs_d.output.txt
Raw output:
BEGIN EXECUTION
plainarr_cs_d.dll
1 file(s) copied.
Response file: D:\h\w\B010096B\w\AA7E0938\e\JIT\Methodical\MDArray\GaussJordan\plainarr_cs_d\plainarr_cs_d.dll.rsp
D:\h\w\B010096B\w\AA7E0938\e\JIT\Methodical\MDArray\GaussJordan\plainarr_cs_d\IL-CG2\plainarr_cs_d.dll
-o:D:\h\w\B010096B\w\AA7E0938\e\JIT\Methodical\MDArray\GaussJordan\plainarr_cs_d\plainarr_cs_d.dll
--targetarch:arm
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\B010096B\p\System..dll
-r:D:\h\w\B010096B\p\Microsoft..dll
-r:D:\h\w\B010096B\p\mscorlib.dll
-r:D:\h\w\B010096B\p\netstandard.dll
-O
" "dotnet" "D:\h\w\B010096B\p\crossgen2\crossgen2.dll" @"D:\h\w\B010096B\w\AA7E0938\e\JIT\Methodical\MDArray\GaussJordan\plainarr_cs_d\plainarr_cs_d.dll.rsp"   -r:D:\h\w\B010096B\w\AA7E0938\e\JIT\Methodical\MDArray\GaussJordan\plainarr_cs_d\IL-CG2*.dll"
Crossgen2 failed with exitcode - -1073741819
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\B010096B\p
D:\h\w\B010096B\w\AA7E0938\e\JIT\Methodical\MDArray\GaussJordan\plainarr_cs_d\plainarr_cs_d.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_Methodical._MDArray_GaussJordan_plainarr_cs_d_plainarr_cs_d_._MDArray_GaussJordan_plainarr_cs_d_plainarr_cs_d_cmd()
```

**Comment by trylek** [comment] 2022-04-04 20:36
Closing as duplicate of: https://github.com/dotnet/runtime/issues/65170

**Closed by trylek** 2022-04-04 20:36 UTC
Labels: arch-arm64, os-linux, os-windows, area-crossgen2-coreclr, untriaged
