### ISSUE TITLE
Calling DllImported method in bass.dll crashes application with exception code 0xc0000409 in .NET 9 on Windows

### ISSUE THREAD

**Issue by DavidZidar** [dotnet/runtime#109377] opened 2024-10-30 17:00 UTC
### Describe the bug
I am developing an application that is using the well known native BASS audio library and it's working fine on .NET 8. However when I try to update to .NET 9 my application can't call even the simplest method in this library because it crashes with exception code 0xc0000409 regardless if I use `DllImport` or `LibraryImport`.

### To Reproduce
Use the latest `bass.dll` from https://www.un4seen.com/ (direct download link: https://www.un4seen.com/files/bass24.zip, the zip contains both x86 and x64 dlls) and the following code in a .NET 9 console project:

```csharp
using System.Runtime.InteropServices;

Console.WriteLine(NativeMethods.BASS_GetVersion());

public class NativeMethods
{
	[DllImport("bass")]
	public static extern int BASS_GetVersion();
}
```

This runs fine in .NET 8 and prints the version 33820928 but in .NET 9 it crashes.

I didn't create a repro project as it requires an external third party DLL, but I can prepare a repo and upload binaries if you want.

#### Windows Event Log
```
Faulting application name: net9bass.exe, version: 1.0.0.0, time stamp: 0x66f10000
Faulting module name: KERNELBASE.dll, version: 10.0.22621.4391, time stamp: 0x7433a115
Exception code: 0xc0000409
Fault offset: 0x0000000000061eae
Faulting process id: 0x0xD560
Faulting application start time: 0x0x1DB2AEAC2E07C3A
Faulting application path: D:\code\test\net9bass\bin\Debug\net9.0\net9bass.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 7f9f420f-d3fb-4c8a-bda4-158ba32435c1
Faulting package full name: 
Faulting package-relative application ID: 
```

#### WinDbg output
```
(7420.d7b0): Security check failure or stack buffer overrun - code c0000409 (!!! second chance !!!)
Subcode: 0x39 FAST_FAIL_CONTROL_INVALID_RETURN_ADDRESS Shadow stack violation
KERNELBASE!VirtualFree+0x7e:
00007ffc`b6e81eae c3              ret
0:000> !analyze
*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************


PROCESS_NAME:  apphost.exe

ERROR_CODE: (NTSTATUS) 0xc0000409 - The system detected an overrun of a stack-based buffer in this application. This overrun could potentially allow a malicious user to gain control of this application.

SYMBOL_NAME:  bass+1e104

MODULE_NAME: bass

IMAGE_NAME:  bass.DLL

FAILURE_BUCKET_ID:  FAIL_FAST_CONTROL_INVALID_RETURN_ADDRESS_c0000409_bass.DLL!Unknown

FAILURE_ID_HASH:  {82c4efc9-7250-7408-42ce-b7c12ede119a}

Followup:     MachineOwner
---------
```

### Further technical details
I'm using .NET 9.0.100-rc.2.24474.11 on Windows 11 23H2 64-bit.

**Comment by DavidZidar** [comment] 2024-10-30 17:09
I've been considering if this might be a bug in the BASS library but I don't think so, it is a well known library that has been working well with .NET for many years in .NET Framework and in .NET 6 through 8 as well.

**Comment by MichalPetryka** [comment] 2024-10-30 17:30
Does it work with `<CETCompat>false</CETCompat>`?

**Comment by AndyAyersMS** [comment] 2024-10-30 17:32
More details here: https://learn.microsoft.com/en-us/dotnet/core/compatibility/interop/9.0/cet-support

**Comment by mangod9** [comment] 2024-10-30 17:38
Correct, this is a dupe of https://github.com/dotnet/runtime/issues/107993. Possible workaround is to disable CET, since the native library is not compliant.

**Closed** 2024-10-30 17:41 UTC
Labels: area-VM-coreclr, needs-area-label

**Comment by DavidZidar** [comment] 2024-10-30 18:09
Oh interesting, I must have missed that in the release notes, it does work with `<CETCompat>false</CETCompat>`.

Thank you!
