### ISSUE TITLE
[API Proposal]: Allow segmented raw writes for Utf8JsonWriter.WriteBase64StringValue

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/runtime#95186] opened 2023-11-23 19:43 UTC
### Background and motivation

To avoid extra allocations, it would be nice to able to write segmented data to [Utf8JsonWriter.WriteBase64StringValue](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter.writebase64stringvalue).

### API Proposal

```csharp
public sealed class Utf8JsonWriter : IAsyncDisposable, IDisposable
{
    public void WriteBase64StringValue (ReadOnlySequence<byte> bytes);
}
```

### API Usage

```csharp
public class Dto
{
    public ReadOnlyMemory<byte> Data { get; set; }

    public ReadOnlySequenceOfByteWrapper Wrapper { get; set; }
}

[JsonConverter(typeof(ReadOnlySequenceOfByteWrapperJsonConverter))]
public readonly struct ReadOnlySequenceOfByteWrapper(ReadOnlySequence<byte> data)
{
    [JsonIgnore]
    public ReadOnlySequence<byte> Data { get; } = data;
}

[JsonSerializable(typeof(Dto))]
public partial class Class1JsonSerializationContext : JsonSerializerContext
{
}

public class ReadOnlySequenceOfByteWrapperJsonConverter : JsonConverter<ReadOnlySequenceOfByteWrapper>
{
    public override ReadOnlySequenceOfByteWrapper Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        throw new NotImplementedException();
    }

    public override void Write(Utf8JsonWriter writer, ReadOnlySequenceOfByteWrapper value, JsonSerializerOptions options)
    {
        writer.WriteBase64StringValue(value.Data);
    }
}
```

**Comment by eiriktsarpalis** [comment] 2023-11-24 10:12
Duplicate of #67337.

**Closed by eiriktsarpalis** 2023-11-24 10:12 UTC
Labels: api-suggestion, area-System.Text.Json, untriaged
