### ISSUE TITLE
[ios-arm64] Keychain 'signing-certs.keychain-db' was not found

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#101551] opened 2024-04-25 14:40 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=655074&view=results
Build error leg or test failing: ios-arm64 Release AllSubsets_Mono

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "Keychain 'signing-certs.keychain-db' was not found",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=655074
**Error message validated:** `[Keychain 'signing-certs.keychain-db' was not found`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 4/25/2024 2:41:40 PM UTC

**Comment by ivanpovazan** [comment] 2024-04-25 15:02
Closing as duplicate of https://github.com/dotnet/runtime/issues/101502

**Closed by ivanpovazan** 2024-04-25 15:02 UTC
Labels: area-Infrastructure-mono, os-ios, Known Build Error
