### ISSUE TITLE
JsonElement.ToString() returns invalid json: "True"/"False"

### ISSUE THREAD

**Issue by jelliott-MS** [dotnet/runtime#107998] opened 2024-09-18 20:50 UTC
### Description

The `JsonElement.ToString()` method returns `Boolean.TrueString` and `Boolean.FalseString` if the `JsonValueKind` is True/False.
https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonelement.tostring?view=net-8.0#remarks

`Boolean.TrueString` and `Boolean.FalseString` evaluate to `"True"` and `"False"` respectively
https://learn.microsoft.com/en-us/dotnet/api/system.boolean.truestring?view=net-8.0#remarks

According to Json.org, the valid json values are `"true"` and `"false"`
https://www.json.org/json-en.html

Recommend to update this to return the correct `"true"`/`"false"` values.

### Reproduction Steps

```
public class ThingValueConverter : JsonConverter<string>
{
    public override string Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        using var jsonDocument = JsonDocument.ParseValue(ref reader);
        return jsonDocument.RootElement.ToString();
    }

    public override void Write(Utf8JsonWriter writer, string value, JsonSerializerOptions options)
    {
        writer.WriteStringValue(value);
    }
}
```

```
internal class Thing
{
    [JsonConverter(typeof(ThingValueConverter))]
    public string Prop { get; set; }
}
```
```
[Fact]
public void Test()
{
    var json = @"{""Prop"":true}";
    var deserialized = System.Text.Json.JsonSerializer.Deserialize<Thing>(json);

    deserialized.Prop.Should().Be("true");
}
```

### Expected behavior

The test should pass because the value should be "true"

### Actual behavior

The test returns "True"

**Comment by gregsdennis** [comment] 2024-09-18 20:58
Duplicate of https://github.com/dotnet/runtime/issues/42502 (yet the issue persists).

`JsonElement.ToString()` just spits out the original JSON text it was given, including the original whitespace that was there.

If you serialize the element, you get what you expect, but I think that's overkill.

**Comment by jelliott-MS** [comment] 2024-09-18 22:50
Another thing I noticed is the JsonElement.ToString() outputs correct json syntax for objects and arrays. This makes things even more confusing that the boolean outputs incorrect json.

**Comment by elgonzo** [comment] 2024-09-19 08:39
@jelliott-MS It's not just boolean values, JsonElement.ToString() doesn't output the correct json syntax for json string values and json null either.

**Comment by eiriktsarpalis** [comment] 2024-09-19 11:00
I find this behaviour to be unintuitive as well, but it seems to be very much by-design behavior. It would be a breaking change to alter now.

**Comment by jelliott-MS** [comment] 2024-09-19 15:55
> @jelliott-MS It's not just boolean values, JsonElement.ToString() doesn't output the correct json syntax for json string values and json null either.

@elgonzo I'm aware of null, what does the toString() output for valuekind of string that isn't valid?

**Comment by jelliott-MS** [comment] 2024-09-19 15:56
@eiriktsarpalis Unfortunately I think you're correct about the breaking change. Thanks anyways, we have a workaround implemented

```
           using var jsonDocument = JsonDocument.ParseValue(ref reader);
            JsonElement jsonElement = jsonDocument.RootElement;
            return jsonElement.ValueKind switch
            {
                // Text.Json's ValueKind.Boolean.ToString() returns "True"/"False"
                JsonValueKind.True => "true",
                JsonValueKind.False => "false",
                JsonValueKind.Null or JsonValueKind.Undefined => null,
                _ => jsonElement.ToString(),
            };
```

**Comment by elgonzo** [comment] 2024-09-19 16:05
> @elgonzo I'm aware of null, what does the toString() output for valuekind of string that isn't valid?

@jelliott-MS not including the surrounding double-quotes as required by the json syntax nor escaping back-slash characters in the value as also required by the json syntax.

If you don't like ToString() returning `True` for not being json syntax, should you not also _not_ like for example ToString() returning `Hello`, which isn't valid json syntax either...?

**Comment by eiriktsarpalis** [comment] 2024-09-19 16:26
> we have a workaround implemented

How about using `JsonElement.GetRawText()`? Alternatively, if you want to apply your own formatting/indentation rules you can just pass it into `JsonSerializer.Serialize`.

**Comment by jelliott-MS** [comment] 2024-09-19 16:33
Are you suggesting GetRawText for the fallthrough or to use in place of the original ToString call? Will GetRawText return the correct json data for all types?

**Comment by eiriktsarpalis** [comment] 2024-09-19 16:34
`GetRawText()` should always return the underlying JSON used to construct the element, although like I said it might still preserve the original formatting.

**Comment by eiriktsarpalis** [comment] 2024-09-20 09:10
Closing as duplicate of https://github.com/dotnet/runtime/issues/42502.

**Closed by eiriktsarpalis** 2024-09-20 09:10 UTC
Labels: area-System.Text.Json, untriaged
