### ISSUE TITLE
Add ReadMe to NuGet packages

### ISSUE THREAD

**Issue by clairernovotny** [dotnet/runtime#64342] opened 2022-01-26 16:09 UTC
NuGet has supported displaying a `ReadMe.md` file contained in a package since last May. The .NET libraries should set an example and contain a ReadMe.md file in the packages. The readme would likely contain links to other resources we aleady have on getting started, support, etc. 

See https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/ for details on how to add the ReadMe.md file to a package.

/cc @chgill-MSFT

**Comment by madelson** [comment] 2022-01-26 18:38
This would be great so long as the content is package-specific and not just generic .net content/links.

**Comment by carlossanlop** [comment] 2022-02-03 22:36
Duplicate of https://github.com/dotnet/runtime/issues/59630

**Closed by carlossanlop** 2022-02-03 22:36 UTC
Labels: area-Infrastructure-libraries, untriaged
