### ISSUE TITLE
[System.Reflection.MetadataLoadContext] Add a method to load specific assembly attributes

### ISSUE THREAD

**Issue by ps-weber** [dotnet/runtime#108746] opened 2024-10-10 10:12 UTC
I am developing a program that needs to check for the existence of a specific attribute with a specific parameter in an assembly.

# Current Approaches
Currently, I see three potential solutions, each with its own limitations:

1. Loading the assembly: This can lead to issues with incompatible assemblies.
2. Using `System.Reflection.PortableExecutable.PELoader`: This allows reading attributes but does not support parsing constructor parameters.
3. Using `System.Reflection.Metadata.MetadataReader` + `Assembly.GetCustomAttributeData()`: This can read attributes with constructor parameters but fails if **any** attribute types are not found.

# Proposal
Since I only need an attribute that is included in the core library, these exceptions could be avoided if there was a method like `Assembly.GetCustomAttributeData(string attributeTypeName)`, similar to `Assembly.GetCustomAttribute<T>()`. The latter method does not work for assemblies loaded via `MetadataReader`.

# Questions
1. Am I missing something in the current API that could help achieve this?
2. Is there any plan to introduce an API that allows loading specific attributes by name?

**Comment by steveharter** [comment] 2024-10-14 17:36
`GetCustomAttributeData()` works with MLC- why doesn't that work?

`GetCustomAttribute()` doesn't work with MLC since it will invoke the constructor on the attribute, which causes code to run, which is not supported in MLC as it is designed to be inspection-only so that, for example, it can load assemblies that are from a different runtime or with missing dependencies.

**Comment by ps-weber** [comment] 2024-10-21 10:49
Thats what I wanted to address in the third point: `GetCustomAttributeData()` instantiates **all** attributes. This fails if the dependencies for **any** Attribute is missing. Since I only need one Attribute which is included in the core library, I would like to avoid instantiating all the other attributes. This would save me the work of needing to find all possible dependent assemblies and would also be faster. 

I'm pretty sure this is technically possible since I can read specific Attributes with `PELoader` without loading any dependencies. However, this does not get me the parameters of the attribute, and deserializing these manually seems pretty complex.

**Comment by jkotas** [comment] 2024-10-21 12:33
#96371 is related or duplicate.

Reflection APIs are not designed to be robust in the presence of missing dependencies.

**Comment by steveharter** [comment] 2024-10-21 15:58
> Thats what I wanted to address in the third point: GetCustomAttributeData() instantiates all attributes.

I see - I didn't see the link on that point to MLC. MLC does have lazy reference resolution but doesn't have a way to not resolve once the reference is needed.

Closing as duplicate of https://github.com/dotnet/runtime/issues/96371.

**Closed by steveharter** 2024-10-21 15:58 UTC
Labels: area-System.Reflection, needs-further-triage
