### ISSUE TITLE
[API Proposal]: Add `bool TryGetElementAt<T>(this IEnumerable<T>, out T element)`

### ISSUE THREAD

**Issue by alrz** [dotnet/runtime#110338] opened 2024-12-02 23:28 UTC
### Background and motivation

This as opposed to checking for bounds each time performing an unguaranteed random access.

Note this could help with any enumerables e.g. arrays, list, so there could be more optimized overloads available.

### API Proposal

```csharp
class Enumerable
{
+  public static bool TryGetElementAt<T>(this IEnumerable<T> source, out T element);
}
```

### API Usage

```csharp
if (seq.TryGetElementAt(2, out var item)) {

}
```

**Comment by PranavSenthilnathan** [comment] 2024-12-03 01:08
Closing as a duplicate of #16362. Please continue the conversation there.

Just a note, if your enumerable doesn't have default values, then [ElementAtOrDefault](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.elementatordefault?view=net-9.0) could work for your use case.

**Closed by PranavSenthilnathan** 2024-12-03 01:08 UTC
Labels: api-suggestion, needs-area-label
