### ISSUE TITLE
Feature request: expose strongly typed ExecutionContext.RunInternal

### ISSUE THREAD

**Issue by dmitriyse** [dotnet/runtime#31984] opened 2020-02-09 01:54 UTC
From the BCL source code:
```CSharp
        // Direct copy of the above RunInternal overload, except that it passes the state into the callback strongly-typed and by ref.
        internal static void RunInternal<TState>(ExecutionContext? executionContext, ContextCallback<TState> callback, ref TState state)
        {
            // Note: ExecutionContext.RunInternal is an extremely hot function and used by every await, ThreadPool execution, etc.
```
Please expose this method.
 
This will help Non-BCL developers also optimize their libraries.
Also an implementation of the ```IValueTaskSource``` suggests usage of the ```ExecutionContext.Run``` and without the typed version most probably additional GC allocation will be required.

**Comment by davidfowl** [comment] 2020-02-09 01:58
Dupe of https://github.com/dotnet/runtime/issues/30867. Feel free to send a PR!

**Closed** 2020-02-09 02:04 UTC
Labels: untriaged
