### ISSUE TITLE
Right-shift of certain negative BigIntegers incorrectly results in 0

### ISSUE THREAD

**Issue by slozier** [dotnet/runtime#43396] opened 2020-10-14 15:45 UTC
### Description

It appears that right shifting certain negative `BigInteger` values by 32 incorrectly results in 0.

```C#
var a = BigInteger.Parse("-18446744073709543424");
Debug.Assert(a >> 32 == (a >> 31) >> 1);
```

I've seen this occur for -18446744073709543424 and -79228162514264337593543917568. Appears to be related to the underlying array representation since it's possible to construct the same values in a way that the shift works.

### Configuration

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\

Host (useful for support):
  Version: 5.0.0-rc.2.20475.5
  Commit:  c5a3f49c88

### Regression?

Appears to occur on .NET Framework as well so probably a bug that's been there for a long time?

**Comment by tannergooding** [comment] 2020-10-14 22:32
Will look into this more, I'm guessing there is a bug in the sign propagation logic.: https://source.dot.net/#System.Runtime.Numerics/System/Numerics/BigInteger.cs,1926

**Comment by wzchua** [comment] 2021-06-18 00:13
This is a dupe of https://github.com/dotnet/runtime/issues/27358

**Closed** 2021-06-18 00:15 UTC
Labels: area-System.Numerics, bug, duplicate, up-for-grabs
