### ISSUE TITLE
[Perf] Triage backlog

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#92164] opened 2023-09-15 22:47 UTC
# 7.0 -> 8.0-rc1 performance comparison

### Regressions

* SocketsHttpHandler - https://github.com/dotnet/perf-autofiling-issues/issues/18138
* Hoisting - https://github.com/dotnet/perf-autofiling-issues/issues/9533
* Convert_double_ulong - https://github.com/dotnet/perf-autofiling-issues/issues/16674
* ArrayPool - https://github.com/dotnet/runtime/issues/87180
* MDArray2 - https://github.com/dotnet/perf-autofiling-issues/issues/19290
* GUIDParse - https://github.com/dotnet/perf-autofiling-issues/issues/19565

### Regressions

* Regex_OneNodeBacktracking - https://github.com/dotnet/runtime/pull/84370
* BigInteger.Parse - https://github.com/dotnet/perf-autofiling-issues/issues/12910
* SeekUnroll - https://github.com/dotnet/perf-autofiling-issues/issues/18579

### Regressions

* Span.IndexerBench.WriteViaIndexer - https://github.com/dotnet/perf-autofiling-issues/issues/19464
* GetMethod* - https://github.com/dotnet/perf-autofiling-issues/issues/17230 and https://github.com/dotnet/perf-autofiling-issues/issues/19200
* IndexerSet<Int32>.Dictionary - https://github.com/dotnet/perf-autofiling-issues/issues/16589
System.Collections.Tests.DictionarySequentialKeys.ContainsValue_17_Int_Int, Perf_Dictionary.Clone - https://github.com/dotnet/perf-autofiling-issues/issues/16587
* Vector*.GetHashCodeBenchmark - https://github.com/dotnet/runtime/compare/a4cd3224726e97bd5fa2a1303fde584931e707d3...d4dbcc64f6f62ce023bb917d7c4fd0678004deeb
* System.Reflection - https://github.com/dotnet/perf-autofiling-issues/issues/20306
* SemaphoreSlim - https://github.com/dotnet/perf-autofiling-issues/issues/20572
*Interpolate_MultipleArgs - https://github.com/dotnet/perf-autofiling-issues/issues/14539
* Interpol_Scalar - https://github.com/dotnet/perf-autofiling-issues/issues/20273
* System.Collections.Tests.Perf_PriorityQueue<Int32, Int32>.HeapSort(Size: 100) - https://github.com/dotnet/runtime/issues/76887
* System.Collections.CtorFromCollection<String>.SortedDictionaryDeepCopy(Size: 512), IfStatements.AndOr - https://github.com/dotnet/runtime/issues/87194
* System.Text.RegularExpressions.Tests.Perf_Regex_Industry_Leipzig.Count(Pattern: &quot;.{2,4}(Tom|Sawyer|Huckleberry|Finn)&quot;, Options: NonBacktracking) - https://github.com/dotnet/runtime/issues/75549
* BenchMrk.Test - https://github.com/dotnet/perf-autofiling-issues/issues/13173

### Regressions

* System.Memory.Constructors.* - https://github.com/dotnet/perf-autofiling-issues/issues/16072
* Perf_BigInteger.Remainder - https://github.com/dotnet/perf-autofiling-issues/issues/17680

### Regressions
  
* RandomAccess.WriteGatherAsync - https://github.com/dotnet/perf-autofiling-issues/issues/12357
* LoopGoto - https://github.com/dotnet/perf-autofiling-issues/issues/20499

### Regressions

* Perf_MemoryMappedFile.Read - https://github.com/dotnet/perf-autofiling-issues/issues/17567
* WriteAllBytes and Other File Ops - https://github.com/dotnet/perf-autofiling-issues/issues/12761

### Regressions

* BlockCopyPerf.CallBlockCopy & StaticMethod5 & Perf_Version.Ctor2/3/4 Parse2/Parse4 TryParse2/3/4 & EncodeUtf16 - https://github.com/dotnet/perf-autofiling-issues/issues/11829
* BubbleSortSpan - https://github.com/dotnet/perf-autofiling-issues/issues/19514
* System.Buffers.Text.Tests.Utf8FormatterTests.* & Perf_DateTime/Offset.ToString - https://github.com/dotnet/perf-autofiling-issues/issues/17024
* Dictionary operations - https://github.com/dotnet/perf-autofiling-issues/issues/17024
* Perf_File.* and Perf_FileStream.* - https://github.com/dotnet/perf-autofiling-issues/issues/17567 and https://github.com/dotnet/perf-autofiling-issues/issues/19514
* Perf_RandomAccess.* - https://github.com/dotnet/perf-autofiling-issues/issues/14020
* Perf.Random.Next_int - https://github.com/dotnet/perf-autofiling-issues/issues/12123
* MemoeryMappedFile.Create* - https://github.com/dotnet/perf-autofiling-issues/issues/17567
* Burgers1/2 - https://github.com/dotnet/perf-autofiling-issues/issues/15037

### Regressions

* IPAddressPerformance - https://github.com/dotnet/perf-autofiling-issues/issues/8856
* Matrix3x2, Perf_Vector - https://github.com/dotnet/perf-autofiling-issues/issues/11829
* Quaternion - https://github.com/dotnet/perf-autofiling-issues/issues/12956
* Perf_String - https://github.com/dotnet/perf-autofiling-issues/issues/11147
* Trim - https://github.com/dotnet/perf-autofiling-issues/issues/15769

**Comment by jeffschwMSFT** [comment] 2023-09-18 16:03
adding additional folks, as this issue covers a lot of areas: @jeffhandley @ericstj @karelz

**Comment by ericstj** [comment] 2023-09-18 19:22
What's the goal of this issue?  I thought there was already a triage process in place to look at these issues and move the meaningful ones over to dotnet/runtime: https://github.com/dotnet/runtime/issues/created_by/app/performanceautofiler

**Comment by jeffhandley** [comment] 2023-09-19 17:07
@DrewScoggins Is the perf triage v-team doing the initial investigation on these to determine which ones need to be transferred into dotnet/runtime?

My understanding is this report was produced as a means for comparing preview-to-rc all-up as another lens over the perf lab data that generally only auto-files issues on rolling build comparisons. Since we're not doing a manual perf run report this year, this preview-to-rc comparison is helpful for ensuring we didn't have gradual regressions go undetected. Is that correct, @DrewScoggins?

**Comment by DrewScoggins** [comment] 2023-09-20 17:41
The goal of this issue is to centralize all of the issues that during 8.0 for whatever reason didn't appear to be triaged. These were found by doing a 7.0 to 8.0-rc1 comparison and all regressions found checked against filed issues. 

> @DrewScoggins Is the perf triage v-team doing the initial investigation on these to determine which ones need to be transferred into dotnet/runtime?

This seems like the right way to handle working through these remaining issues.

> My understanding is this report was produced as a means for comparing preview-to-rc all-up as another lens over the perf lab data that generally only auto-files issues on rolling build comparisons. Since we're not doing a manual perf run report this year, this preview-to-rc comparison is helpful for ensuring we didn't have gradual regressions go undetected. Is that correct, @DrewScoggins?

That is the main goal, yes. The other was to ensure that we had a final roll-up, and that we were sure that everything that we filed during 8.0 had been triaged.

**Comment by jeffhandley** [comment] 2023-10-24 20:22
Moving to 9.0.0 for further consideration of remaining unaddressed regressions.

**Closed** 2024-07-28 04:52 UTC
Labels: area-Meta
