### ISSUE TITLE
System.Text.Json settings not being applied

### ISSUE THREAD

**Issue by BrunoBlanes** [dotnet/runtime#34357] opened 2020-04-01 05:30 UTC
I am using **Blazor WebAssembly 3.2 Preview 3** and `System.Text.Json 5.0.0-preview.1.20120.5` configured as below:
```  C#
services.AddMvc().AddJsonOptions(options =>
{
	options.JsonSerializerOptions.WriteIndented = true;
	options.JsonSerializerOptions.IgnoreNullValues = true;
	options.JsonSerializerOptions.PropertyNameCaseInsensitive = true;
	options.JsonSerializerOptions.ReferenceHandling = ReferenceHandling.Preserve;
	options.JsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
});
```

This is the data I am requesting.
``` C#
[DataContract(IsReference = true)]
public class State
{
	public int Id { get; set; }

	[DataMember]
	public string Name { get; set; }

	[DataMember]
	public List<Region> Regions { get; }

	public State()
	{
		Name = string.Empty;
		Regions = new List<Region>();
	}

	public State(string name)
	{
		Name = name;
		Regions = new List<Region>();
	}
}
```

This is the api method.
``` C#
[HttpGet]
public async Task<ActionResult<List<State>>> GetReportsAsync()
{
	return await context.States.Include(x => x.Regions).ToListAsync() is IList<State> states
		? Ok(states)
		: (ActionResult<List<State>>)NoContent();
}
```

This is the response.
``` json
[
  {
    "id": 1,
    "name": "Espírito Santo",
    "regions": []
  }
]
```

When I do a request to an api method, it returns as if it had just ignored all of the configuration code. Property names aren't camel cased and EF Core's `Include()` method isn't working, which I am guessing it is related to reference handling at this point.

**Comment by Jozkee** [comment] 2020-04-01 19:05
@BrunoBlanes Can you share what is the JSON that you would expect?

>  it returns as if it had just ignored all of the configuration code.

Potentially same issue as https://github.com/dotnet/runtime/issues/30820#issuecomment-594799031, and will be fixed once https://github.com/dotnet/runtime/issues/30445 is in.

**Comment by BrunoBlanes** [comment] 2020-04-01 20:12
Sure, so I went through the trouble of implementing Json.NET with the same settings, except for camel casing:

``` C#
services.AddMvc().AddNewtonsoftJson(options =>
{
	options.SerializerSettings.Formatting = Formatting.Indented;
	options.SerializerSettings.NullValueHandling = NullValueHandling.Ignore;
	options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
});
```

And here is the expected output which I did get from Json.NET:
```
[
  {
    "$id": "1",
    "name": "Espírito Santo",
    "regions": [
      {
        "$id": "2",
        "name": "Sul",
        "counties": [],
        "reports": [
          {
            "$id": "3",
            "number": 5,
            "date": "0001-01-01T00:00:00",
            "region": {
              "$ref": "2"
            },
            "confirmed": 0,
            "discarded": 0,
            "suspected": 0,
            "deaths": 0,
            "cured": 0
          },
          {
            "$id": "4",
            "number": 6,
            "date": "0001-01-01T00:00:00",
            "region": {
              "$ref": "2"
            },
            "confirmed": 0,
            "discarded": 0,
            "suspected": 0,
            "deaths": 0,
            "cured": 0
          },
[...]
        ]
      }
    ]
  }
]
```

I also wonder why the EF Core's `Include()` method only works when I call the `GetReportsAsync()` from within another method from this same controller. If I do a direct GET request to it, it doesn't include anything...

**Comment by Jozkee** [comment] 2020-04-01 20:45
Well, you are defining `ReferenceLoopHandling = Ignore`, that is not the option that preserves the duplicate objects, also I don't understand how you get above json without specifying `PreserveReferencesHandling = PreserveReferencesHandling.All`, which is the option that writes the $id and $ref properties.

> If I do a direct GET request to it, it doesn't include anything...

Can you try using these options instead?
```cs
services.AddMvc().AddNewtonsoftJson(options =>
{
	options.SerializerSettings.Formatting = Formatting.Indented;
	options.SerializerSettings.NullValueHandling = NullValueHandling.Ignore;
        options.PreserveReferencesHandling = PreserveReferencesHandling.All;
});
```

**Comment by BrunoBlanes** [comment] 2020-04-01 21:08
Not much changed really... I could provide you with the project if you want. It is on my GitHub.
```
{
  "$id": "1",
  "$values": [
    {
      "$id": "2",
      "name": "Espírito Santo",
      "regions": [
        {
          "$id": "3",
          "name": "Sul",
          "counties": [],
          "reports": [
            {
              "$id": "4",
              "number": 5,
              "date": "0001-01-01T00:00:00",
              "region": {
                "$ref": "3"
              },
              "confirmed": 0,
              "discarded": 0,
              "suspected": 0,
              "deaths": 0,
              "cured": 0
            },
            {
              "$id": "5",
              "number": 6,
              "date": "0001-01-01T00:00:00",
              "region": {
                "$ref": "3"
              },
              "confirmed": 0,
              "discarded": 0,
              "suspected": 0,
              "deaths": 0,
              "cured": 0
            },
[...]
          ]
        }
      ]
    }
  ]
}
```

**Comment by Jozkee** [comment] 2020-04-01 23:31
> If I do a direct GET request to it, it doesn't include anything...

I cloned your repo https://github.com/BrunoBlanes/Covid19Tracker and tried to duplicate the error but no luck, doing a GET through the browser works fine for me. 

I just replaced the code that queries to the Db for objects created on the fly.
```
[HttpGet]
public async Task<ActionResult<List<State>>> GetReportsAsync()
{
	// Dummy data;
	var state = new State { Name = "State 1" };
	var region = new Region { Name = "Region 1", State = state };

	state.Regions.Add(region);
	state.Regions.Add(region);

	var states = new List<State> { state, state };

	return states;

	//return await context.States.Include(x => x.Regions).ToListAsync() is IList<State> states
	//	? Ok(states)
	//	: (ActionResult<List<State>>)NoContent();
}
```

This means that the issue is not on the ASP.NET side, perhaps you might be missing some entity save in the Db side?

**Comment by BrunoBlanes** [comment] 2020-04-02 01:03
> This means that the issue is not on the ASP.NET side, perhaps you might be missing some entity save in the Db side?

That's odd, with Json.NET I do get a proper answer after populating the database through another method. But when I do a direct call it doesn't include children objects. I don't know what could be the reason for that.

But I did change back to `System.Text.Json` and even with the dummy data I still don't think it is working as intended, since I'm getting this exception:
`JsonException: A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 32. Consider using ReferenceHanlding.Preserve on JsonSerializerOptions to support cycles.`

Wasn't cyclic reference handling added to preview 1?

I have set `options.JsonSerializerOptions.ReferenceHandling = ReferenceHandling.Preserve;` just like the way I showed on my first comment here.

**Comment by Jozkee** [comment] 2020-04-02 01:19
Yes, but as I mentioned earlier, there is currently an issue that prevents Asp.Net from using preview features https://github.com/dotnet/runtime/issues/30445.

They need to create a copy of the options which means that they manually copy properties, to a new JsonSerializerOptions instance, and that causes that recently added options are neglected from the new options.

**Comment by Jozkee** [comment] 2020-04-02 01:27
As a workaround to use System.Text.Json, set an Encoder on the options; something like  `options.JsonSerializerOptions.Encoder = JavaScriptEncoder.Default` on `AddJsonOptions`.

```cs
services.AddMvc().AddJsonOptions(options =>
{
	options.JsonSerializerOptions.WriteIndented = true;
	options.JsonSerializerOptions.IgnoreNullValues = true;
	options.JsonSerializerOptions.PropertyNameCaseInsensitive = true;
	options.JsonSerializerOptions.ReferenceHandling = ReferenceHandling.Preserve;
	options.JsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
	options.JsonSerializerOptions.Encoder = JavaScriptEncoder.Default;
});
```

**Comment by BrunoBlanes** [comment] 2020-04-02 01:41
Yeah, the workaround does the trick, not for camel casing though. I'll keep an eye out for when that issue will be closed. Thanks for your time and help!

**Comment by Jozkee** [comment] 2020-04-02 01:43
What's the issue with camel casing?

**Comment by BrunoBlanes** [comment] 2020-04-02 01:47
This is the output I am getting:
```
{
  "$id": "1",
  "$values": [
    {
      "$id": "2",
      "id": 1,
      "name": "Espírito Santo",
      "regions": {
        "$id": "3",
        "$values": []
      }
    }
  ]
}
```

I hope I am not wrong about this, but shouldn't setting `options.JsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;` change the output to this?
```
{
  "$id": "1",
  "$values": [
    {
      "$id": "2",
      "Id": 1,
      "Name": "Espírito Santo",
      "Regions": {
        "$id": "3",
        "$values": []
      }
    }
  ]
}
```

**Comment by Jozkee** [comment] 2020-04-02 01:59
The default `JsonNamingPolicy` on Asp.Net is camel case, that's why regardless of setting `PropertyNamingPolicy = null`, it still does use camel case.

What you can do here is create a `JsonNamingPolicy` that enforces not converting the property name:
```cs
public class JsonUnchangedNamingPolicy : JsonNamingPolicy
{
	public override string ConvertName(string name)
	{
		return name;
	}
}
```

And using that in your options:

```cs
services.AddMvc().AddJsonOptions(options =>
{
	options.JsonSerializerOptions.PropertyNamingPolicy = new JsonUnchangedNamingPolicy();
});
```

@pranavkm @rynowak, is there any other way to opt-out from camel case policy?

**Comment by Jozkee** [comment] 2020-04-02 02:07
What you can do here is create a naming policy that avoids changing the property name:
```cs
internal class JsonDefaultNamingPolicy : JsonNamingPolicy
{
    public override string ConvertName(string name) => name;
}
```

And set that in your options:
```cs
services.AddMvc().AddJsonOptions(options =>
{
	options.JsonSerializerOptions.PropertyNamingPolicy = new DefaultNamingpolicy();
});
```

@rynowak @pranavkm, is there any other way to opt-out from camel case policy on Asp.Net?

**Comment by BrunoBlanes** [comment] 2020-04-02 02:15
Thanks, that did it too. If there is another way to opt-out of camel casing I'd like to know for future reference, but other than that, I think this is it. Thanks a lot for all your help!

**Comment by Jozkee** [comment] 2020-04-02 02:31
No worries, reach out to us any time you think you have issues/suggestions on the `System.*` APIs. 
If you have blazor-related concerns, you can create an issue on https://github.com/dotnet/aspnetcore.

if you have more questions feel free to comment or open a new issue.

**Closed by Jozkee** 2020-04-02 02:31 UTC
Labels: area-System.Text.Json

**Comment by rynowak** [comment] 2020-04-03 06:43
> That is because the default naming policy for Asp.Net is JsonCamelCaseNamingPolicy when the current PropertyNamingPolicy in options is null.

This statement doesn't really make sense. The options setup for MVC is ordered, so we should not be overwriting anything the user configured.

**Comment by rynowak** [comment] 2020-04-03 06:43
I'll see if I can reproduce this.

**Comment by Jozkee** [comment] 2020-04-03 06:58
@rynowak Oh you are right, setting `PropertyNamingPolicy = null` makes that the properties remain unchanged, so we are not really overwriting the user-configured options as you mentioned.
