### ISSUE TITLE
WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests time out

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#97112] opened 2024-01-17 21:12 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=530541
Build error leg or test failing: WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/97045

## Error Message
[ERROR] FATAL UNHANDLED EXCEPTION: System.OperationCanceledException: The operation was canceled.

[EXECUTION TIMED OUT]
Exit Code:-3Executor timed out after 1800 seconds and was killed
['WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests' END OF WORK ITEM LOG: Command timed out, and was killed]

```json
{
  "ErrorMessage": "'WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests' END OF WORK ITEM LOG: Command timed out",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=530541
**Error message validated:** `'WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests' END OF WORK ITEM LOG: Command timed out`
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 1/17/2024 9:13:04 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[612613](https://dev.azure.com/dnceng-public/public/_build/results?buildId=612613)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=612613&view=ms.vss-test-web.build-test-results-tab&runId=14959394&resultId=176858)|dotnet/runtime#98492|
|[611731](https://dev.azure.com/dnceng-public/public/_build/results?buildId=611731)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=611731&view=ms.vss-test-web.build-test-results-tab&runId=14936634&resultId=100604)|dotnet/runtime#100076|
|[609762](https://dev.azure.com/dnceng-public/public/_build/results?buildId=609762)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=609762&view=ms.vss-test-web.build-test-results-tab&runId=14924676&resultId=100604)|dotnet/runtime#99371|
|[610384](https://dev.azure.com/dnceng-public/public/_build/results?buildId=610384)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=610384&view=ms.vss-test-web.build-test-results-tab&runId=14900288&resultId=191005)|dotnet/runtime#96332|
|[610365](https://dev.azure.com/dnceng-public/public/_build/results?buildId=610365)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=610365&view=ms.vss-test-web.build-test-results-tab&runId=14898704&resultId=100604)|dotnet/runtime#100032|
|[606762](https://dev.azure.com/dnceng-public/public/_build/results?buildId=606762)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=606762&view=ms.vss-test-web.build-test-results-tab&runId=14790612&resultId=186262)|dotnet/runtime#98492|
|[602129](https://dev.azure.com/dnceng-public/public/_build/results?buildId=602129)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=602129&view=ms.vss-test-web.build-test-results-tab&runId=14624146&resultId=100604)|dotnet/runtime#99705|
|[601483](https://dev.azure.com/dnceng-public/public/_build/results?buildId=601483)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=601483&view=ms.vss-test-web.build-test-results-tab&runId=14599322&resultId=187307)|dotnet/runtime#98761|
|[579259](https://dev.azure.com/dnceng-public/public/_build/results?buildId=579259)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=579259&view=ms.vss-test-web.build-test-results-tab&runId=13919148&resultId=100601)|dotnet/runtime#98905|
|[577436](https://dev.azure.com/dnceng-public/public/_build/results?buildId=577436)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=577436&view=ms.vss-test-web.build-test-results-tab&runId=13852440&resultId=100601)|dotnet/runtime#98754|
|[576927](https://dev.azure.com/dnceng-public/public/_build/results?buildId=576927)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=576927&view=ms.vss-test-web.build-test-results-tab&runId=13838466&resultId=185589)|dotnet/runtime#98492|
|[575624](https://dev.azure.com/dnceng-public/public/_build/results?buildId=575624)|dotnet/runtime|[WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=575624&view=ms.vss-test-web.build-test-results-tab&runId=13805686&resultId=187064)|dotnet/runtime#98492|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|2|6|12|

**Comment by pavelsavara** [comment] 2024-03-22 11:16
closing as duplicate of https://github.com/dotnet/runtime/issues/99888

**Closed by pavelsavara** 2024-03-22 11:16 UTC
Labels: arch-wasm, blocking-clean-ci, area-System.Runtime.InteropServices.JavaScript, Known Build Error, os-browser
