### ISSUE TITLE
Test failure: Interop\\COM\\NativeClients\\Events\\Events.cmd

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#35476] opened 2020-04-26 09:09 UTC
failed in job: [runtime-coreclr gcstress0x3-gcstress0xc 20200425.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=617310&view=ms.vss-test-web.build-test-results-tab&runId=19345618&resultId=103911&paneView=debug)

Error message
~~~

Return code: 1
Raw output file: C:\h\w\A9AE08C8\w\BC58099E\e\Interop\COM\Reports\Interop.COM\NativeClients\Events\Events.output.txt
Raw output:
BEGIN EXECUTION
Copying 'C:\h\w\A9AE08C8\p\CoreShim.dll'...
 1 file(s) copied.
 "C:\h\w\A9AE08C8\p\corerun.exe" Events.dll 
Searching for exe to launch in C:\h\w\A9AE08C8\w\BC58099E\e\Interop\COM\NativeClients\Events...
Launching 'C:\h\w\A9AE08C8\w\BC58099E\e\Interop\COM\NativeClients\Events\COMClientEvents.exe'...


Expected: 100
Actual: -1073741819
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\A9AE08C8\p
> C:\h\w\A9AE08C8\w\BC58099E\e\Interop\COM\NativeClients\Events\Events.cmd
Expected: True
Actual: False


Stack trace
   at Interop_COM._NativeClients_Events_Events_._NativeClients_Events_Events_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x86.Checked\TestWrappers\Interop.COM\Interop.COM.XUnitWrapper.cs:line 722
~~~

**Comment by BruceForstall** [comment] 2020-04-26 15:53
This is Windows x86, both `COMPlus_GCStress=3` and `COMPlus_GCStress=C`

**Comment by v-haren** [comment] 2020-05-11 05:09
failed again in job: [runtime-coreclr gcstress0x3-gcstress0xc 20200510.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=638720&view=ms.vss-test-web.build-test-results-tab&runId=19856664&resultId=103502&paneView=debug)

failed test: Interop\\COM\\NativeClients\\Events\\Events.cmd


Error message
~~~

Return code: 1
Raw output file: C:\h\w\B285091D\w\BB3509FC\e\Interop\COM\Reports\Interop.COM\NativeClients\Events\Events.output.txt
Raw output:
BEGIN EXECUTION
Copying 'C:\h\w\B285091D\p\CoreShim.dll'...
 1 file(s) copied.
 "C:\h\w\B285091D\p\corerun.exe" Events.dll 
Searching for exe to launch in C:\h\w\B285091D\w\BB3509FC\e\Interop\COM\NativeClients\Events...
Launching 'C:\h\w\B285091D\w\BB3509FC\e\Interop\COM\NativeClients\Events\COMClientEvents.exe'...

Expected: 100
Actual: -1073741819
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\B285091D\p
> C:\h\w\B285091D\w\BB3509FC\e\Interop\COM\NativeClients\Events\Events.cmd
Expected: True
Actual: False


Stack trace
   at Interop_COM._NativeClients_Events_Events_._NativeClients_Events_Events_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x86.Checked\TestWrappers\Interop.COM\Interop.COM.XUnitWrapper.cs:line 916
~~~

**Comment by AaronRobinsonMSFT** [comment] 2020-05-11 21:16
I am unable to reproduce this locally.

I have tried both Debug and Checked builds locally. I also pulled down the CoreCLR from last night and was also unable to reproduce the issue. I subsequently tried running the application under AppVerifier with both `COMPlus_GCStress=0x3` and `COMPlus_GCStress=0xC` with no failure cases. I am going to close this for now. Please reopen if this reproduces again.

**Closed** 2020-05-11 21:16 UTC
Labels: GCStress, arch-x86, area-Interop-coreclr
