### ISSUE TITLE
Using dotnet counters results in excessive GCHandle allocations and pinning

### ISSUE THREAD

**Issue by davidfowl** [dotnet/runtime#49422] opened 2021-03-10 09:02 UTC
### Description

While diagnosing a memory scenario I ran a gc trace and noticed that handles GC handles were being created and destroyed repeatedly. After some digging I noticed that this was because I was running dotnet counters and the event counter stack.

### Regression?

No

### Data

SetGCHandle

![image](https://user-images.githubusercontent.com/95136/110603609-0a8d8600-813c-11eb-822e-21bb72a1b1f3.png)

DestroyGCHandle

![image](https://user-images.githubusercontent.com/95136/110603499-edf14e00-813b-11eb-82f4-8accb72674ea.png)

### Analysis

https://github.com/dotnet/runtime/blob/e341abfa627bb33538bb62ce0c6d51a3d42936f2/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/TraceLogging/DataCollector.cs#L23

This is the type doing the pinning. 

cc @noahfalk

**Comment by noahfalk** [comment] 2021-03-10 10:55
What counts as excessive? Writing a string via EventSource pins the string to avoid an extra copy of the string data - so yes we could get rid of the pinning but that isn't necessarily going to perform better. Is there some sign that the handles were problematic?

**Comment by davidfowl** [comment] 2021-03-10 11:03
I have a problem with the diagnostics stack potentially contributing to heap fragmentation. A copy might be better in this case but I don't have enough data about why the code does what it does today to know.

**Comment by noahfalk** [comment] 2021-03-10 11:12
The pin is very short lived, just long enough to copy the string into other event buffers within the native code that is called immediately afterwards. My understanding is that long lived pins are the typical ones that cause fragmentation but adding @Maoni0 in case I misunderstand the implications.

**Comment by benaadams** [comment] 2021-03-10 13:07
It does allocate a Pin in `PinArray`

https://github.com/dotnet/runtime/blob/e341abfa627bb33538bb62ce0c6d51a3d42936f2/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/TraceLogging/DataCollector.cs#L333

But doesn't Free them in that class?

**Comment by davidfowl** [comment] 2021-03-10 16:17
It's freed here https://github.com/dotnet/runtime/blob/e341abfa627bb33538bb62ce0c6d51a3d42936f2/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/TraceLogging/TraceLoggingEventSource.cs#L746

**Comment by Maoni0** [comment] 2021-03-11 05:24
> I have a problem with the diagnostics stack potentially contributing to heap fragmentation.

@davidfowl, are you actually observing this is causing high fragmentation? it's true this case can be optimized - I looked the call stack a bit and indeed the polling counter's implementation can be optimized - essentially it's pinning a string that the polling counter constructs from a couple of numbers. so you could just reuse the same buffer every time to format that string into. however this means it can't use the convenient EventSource API so it has to be worth the effort to do this optimization. if the pins are short lived as @noahfalk pointed out it shouldn't be causing fragmentation problems.

**Comment by davidfowl** [comment] 2021-03-11 06:59
> @davidfowl, are you actually observing this is causing high fragmentation?

I don't know if the fragmentation was due to this pinning, very unlikely.

**Comment by noahfalk** [comment] 2021-07-21 07:35
We haven't connected this to any end-user performance problem and the short lived pinning is by design, closing this issue.

**Closed by noahfalk** 2021-07-21 07:35 UTC
Labels: area-System.Diagnostics.Tracing, tenet-performance
