### ISSUE TITLE
Empty while loop never reevaluates value from function in release mode

### ISSUE THREAD

**Issue by gurustron** [dotnet/runtime#35762] opened 2020-05-03 00:42 UTC
Inspired by [this stackoverflow question](https://stackoverflow.com/questions/61567091/websocket-only-receives-messages-if-console-write-is-present-why-is-this)

Repro: 

TargetFramework: netcoreapp3.1
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362

```
        public static void Main(string[] args)
        {
            var c = new Container();
            c.SetNumber();

            Console.WriteLine("Before");
            while (c.NumerProp != 1)
            {
                //Console.WriteLine("in");
            }

            Console.WriteLine("Success!");
           
            
            Console.ReadLine();
        }

        class Container
        {
            public void SetNumber()
            {
                Task.Run(() =>
                {
                    Thread.Sleep(100);
                    NumerProp = 1;
                });
            }

            public int NumerProp { get; set; }

        }
```

Never prints "Success!" with empty while loop in **Release** mode. Uncommenting Console.WriteLine or switching out to Debug fixes the issue.

Disassembly shows the next code:
```
            Console.WriteLine("Before");
00007FFA92B60F6F  mov         rcx,21213A530C0h  
00007FFA92B60F79  mov         rcx,qword ptr [rcx]  
00007FFA92B60F7C  call        00007FFA92B60660  
00007FFA92B60F81  mov         ecx,dword ptr [rsi+8]  
00007FFA92B60F84  cmp         ecx,1  
00007FFA92B60F87  jne         00007FFA92B60F84  
            {
                //Console.WriteLine("in");
            }

            Console.WriteLine("Success!");
``` 
With  _jne_ instruction pointing to just previous _cmp_  instruction.

**Comment by stephentoub** [comment] 2020-05-03 02:14
This is by design. The backing field for NumerProp isn't volatile.

**Comment by jkotas** [comment] 2020-05-03 02:17
The JIT has hoisted field load out of the loop and the loop is now infinite. The fields is not marked as volatile so the JIT is correct in doing this transformation.

This is documented in https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/volatile 

Duplicate of e.g. https://github.com/dotnet/runtime/issues/8602

**Closed by jkotas** 2020-05-03 02:17 UTC
Labels: area-CodeGen-coreclr, untriaged

**Comment by gurustron** [comment] 2020-05-03 06:50
@stephentoub @jkotas ,

Thank you for explanation. Misleading behaviour was that uncommenting the inner code in the loop made the code working on my machine.

**Comment by stephentoub** [comment] 2020-05-03 10:23
> Misleading behaviour was that uncommenting the inner code in the loop made the code working on my machine.

The JIT needs to assume that the code in that called function may update the relevant field, and this it can't hoist the read.
