### ISSUE TITLE
Shouldn't a JsonIgnore property be included in JsonExtensionData property during deserialzation? 

### ISSUE THREAD

**Issue by SilentCC** [dotnet/runtime#81521] opened 2023-02-02 02:27 UTC
According to the definition of JsonExtensionData:
>When placed on a property of type [IDictionary<TKey,TValue>](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.idictionary-2?view=net-7.0), any properties that do not have a matching member are added to that dictionary during deserialization and written during serialization.

When deserializing a property with JsonIgnore attribute, shouldn't it be a mismatching member because we ignore the property? 

Currently, System.Text.Json doesn't fill the JsonExtensionData property with a JsonIngore property:
This is the unit test function in [ExtensionDataTest](https://github.com/dotnet/runtime/blob/20dd6ea921028b3a2cc660654b65112077671fb5/src/libraries/System.Text.Json/tests/Common/ExtensionDataTests.cs)

```csharp
public class ClassWithIgnoredData
{
    [JsonExtensionData]
    public Dictionary<string, object> MyOverflow { get; set; }

    [JsonIgnore]
    public int MyInt { get; set; }
}

[Fact]
public async Task IgnoredDataShouldNotBeExtensionData()
{
    ClassWithIgnoredData obj = await Serializer.DeserializeWrapper<ClassWithIgnoredData>(@"{""MyInt"":1}");

    Assert.Equal(0, obj.MyInt);
    Assert.Null(obj.MyOverflow);
}
```

**Comment by krwq** [comment] 2023-02-02 10:45
I agree this seems counter intuitive (at least to me). I'd expect whatever is not being used to go to extension data but at the same time:
- changing that will be a breaking change and will require documenting that in multiple place (although IMO there will be very little people if any at all relying on that)
- most likely if we change JsonIgnore-d properties to be completely ignored by parser we should do the same for parametrized ctors - ignored properties should not be matched with parameters on ctor

**Comment by gregsdennis** [comment] 2023-02-02 11:34
To voice a contrary opinion, I would expect `MyInt` _not_ to appear in the extension data as it's been explicitly ignored.

**Comment by krwq** [comment] 2023-02-02 13:07
Closing as duplicate of https://github.com/dotnet/runtime/issues/68895

@gregsdennis fair but currently contract model doesn't expose IsIgnored and IsIgnored was supposed to mean the same as not present in the model. I can see translating ignored as properties without getter or setter which would be equivalent to current behavior. The problem starts appearing when we have properties with same name on the derived class but not ignoring the property. Let's continue discussion in the other issue if needed

**Closed by krwq** 2023-02-02 13:07 UTC
Labels: question, area-System.Text.Json
