### ISSUE TITLE
`MissingMethodException` created with class+method name constructor has incorrect HRESULT

### ISSUE THREAD

**Issue by PathogenDavid** [dotnet/runtime#73750] opened 2022-08-11 07:49 UTC
### Description

`MissingMethodException` is [documented](https://docs.microsoft.com/en-us/dotnet/api/system.missingmethodexception) as having an HResult of `COR_E_MISSINGMETHOD` (0x80131513).

However, a `MissingMethodException` created via the [`string? className, string? methodName` constructor](https://docs.microsoft.com/en-us/dotnet/api/system.missingmethodexception.-ctor?view=net-7.0#system-missingmethodexception-ctor(system-string-system-string)) will have an HResult of `COR_E_MISSINGMEMBER` (0x80131512) -- the HResult of its base type.

### Reproduction Steps

Run the snippet below ([SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoayPAZwwAIBLPZgYQHkAlAfQCifALIBJAMrjRAOQDiwgQBUAElwAiTALxN8YABYwwAaxgATABTm2GAJQAGBAA47ZAMxkArG5sBuakTIATnM8GAB3JmEWeno2AHNhGAw9CFMBBDAYAAcMFgg8cwAiROTUpgBbaNi8OIBCQpsAOmUeGHocABtmTW1ufiExSRl5JVU1X38gkPDIqviSlLSM7Nz8osUATyyYQrQmYqTFhubW9q6tXt5BEQkpOQUVdQmqIA===))

```csharp
using System;

const int COR_E_MISSINGMETHOD = unchecked((int)0x80131513);
Console.WriteLine(new MissingMethodException("Method missing!").HResult == COR_E_MISSINGMETHOD);
Console.WriteLine(new MissingMethodException("Type", "Method").HResult == COR_E_MISSINGMETHOD);
```

### Expected behavior

Expected output:

```
True
True
```

### Actual behavior

Actual output:

```
True
False
```

### Regression?

No, it seems like the issue has existed since this API was introduced in .NET Framework 1.1.

### Known Workarounds

Don't trust the HResult.

### Configuration

Definitely not specific to this configuration since [the missing `HResult` assignment is pretty evident](https://github.com/dotnet/runtime/blob/e71a9583b4d6c9bd97edd87cda7f98f232f63530/src/libraries/System.Private.CoreLib/src/System/MissingMethodException.cs#L39-L43), but:

* .NET 7 Preview 7
* Windows 10 21H2
* x64

### Other information

Stumbled upon this while improving the error logging around calls to `hdt_get_function_pointer` in our custom host. (Which is internally implemented by `Internal.Runtime.InteropServices.ComponentActivator.GetFunctionPointer` which surfaces exceptions by [returning their HResult](https://github.com/dotnet/runtime/blob/e71a9583b4d6c9bd97edd87cda7f98f232f63530/src/libraries/System.Private.CoreLib/src/Internal/Runtime/InteropServices/ComponentActivator.cs#L160-L163).)

**Comment by jeffhandley** [comment] 2022-08-15 05:30
Thanks for the detailed issue details, @PathogenDavid. Since this isn't a regression, we won't fix it in .NET 7 (with where we are on the schedule), but we'll keep it open in our backlog. Would you be interested in digging deep into it to see if you can find where the bug is, and perhaps send a PR if there is an apparent fix?

**Comment by PathogenDavid** [comment] 2022-08-15 16:39
@jeffhandley No worries, definitely didn't expect it for .NET 7.

PR here! https://github.com/dotnet/runtime/pull/73948

**Closed** 2022-08-15 23:19 UTC
Labels: area-System.Runtime, in-pr
