### ISSUE TITLE
JsonSerializer.Deserialize<T>() not work

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/runtime#82016] opened 2023-02-12 19:29 UTC
### Description

The `JsonSerializer.Deserialize<T>` not fill properties of `Settings`.

### JSON file content:

![image](https://user-images.githubusercontent.com/4510984/218332390-a63c73dd-adb3-456f-8f42-3a4d07ec6cbc.png)

### Code:

```cs
public record ApiConfig {
    public string AppUrl { get; init; } = string.Empty;

    public string AuthenticationEndPoint { get; init; } = string.Empty;

    public string TokenEndPoint { get; init; } = string.Empty;

    public string AppKey { get; init; } = string.Empty;

    public string OpenApiBaseUrl { get; init; } = string.Empty;

    public string StreamingUrl { get; set; } = string.Empty;
}

public class Settings {
    public ApiConfig OpenApiConfig { get; } = new();
}
```

```cs
var text = ... // json content as above
// Why settings all properties are empty?
var settings = JsonSerializer.Deserialize<Settings>(text) ?? throw new InvalidDataException(...);
```

![image](https://user-images.githubusercontent.com/4510984/218332661-7ec20db5-0302-4eb2-9b18-47699e8bc98e.png)

### Reproduction Steps

As my code.

### Expected behavior

The `settings` returned by `JsonSerializer.Deserialize<T>` be filled.

### Actual behavior

The `settings` properties all keep empty.

### Configuration

.NET: `7.0.2`
OS: `10.0.22621.0`

**Comment by Clockwork-Muse** [comment] 2023-02-12 20:09
... If these settings are for _your own_ application, there are existing [libraries for binding configuration](https://learn.microsoft.com/en-us/dotnet/core/extensions/configuration).

That said, this is because `Settings.OpenApiConfig` is `get` only.  If you change it to [at least `init` it will work](https://dotnetfiddle.net/GG1wc6):
```csharp
public class Settings {
    public ApiConfig OpenApiConfig { get; init; } = new();
}
```

**Comment by GF-Huang** [comment] 2023-02-12 20:12
God, there is still a gap between `Systen.Text.Json` and `Newtonsoft.Json` even in .NET 7.

**Comment by eiriktsarpalis** [comment] 2023-02-13 15:56
This is because System.Text.Json doesn't support populate behavior yet, but we're working on it.

Duplicate of https://github.com/dotnet/runtime/issues/78556.

cc @krwq

**Closed by eiriktsarpalis** 2023-02-13 15:56 UTC
Labels: area-System.Text.Json, untriaged
