### ISSUE TITLE
Test failure global::JIT.HardwareIntrinsics.X86._Fma_Vector128.Program.MultiplyAddSubtractSingle()

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#78299] opened 2022-11-14 01:40 UTC
Failed in Run: [runtime-coreclr jitstress-isas-x86 20221112.1](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=81571)
 
 **Failed tests:**
 ```
coreclr Linux x64 Checked jitstress_isas_x86_nopclmulqdq @ Ubuntu.1804.Amd64.Open

- global::JIT.HardwareIntrinsics.X86._Fma_Vector128.Program.MultiplyAddSubtractSingle()
 ```
 
 **Error message:**
 ```
 One or more scenarios did not complete as expected.
 ```
 
 **Stack trace:**
 ```
    at JIT.HardwareIntrinsics.X86._Fma_Vector128.Program.MultiplyAddSubtractSingle() in /__w/1/s/src/tests/JIT/HardwareIntrinsics/X86/Fma_Vector128/MultiplyAddSubtract.Single.cs:line 118
   at Program.<<Main>$>g__TestExecutor92|0_91(<>c__DisplayClass0_0&)
 ```

**Comment by jakobbotsch** [comment] 2022-11-14 16:29
Likely a duplicate/same issue as #78079?

**Comment by tannergooding** [comment] 2022-11-14 17:06
Yes. The test is using `MathF.Round` when it should be using `MathF.FusedMultiplyAdd`

**Comment by tannergooding** [comment] 2022-11-14 17:07
Closing as dupe of #78079

**Closed by tannergooding** 2022-11-14 17:07 UTC
Labels: os-linux, JitStress, arch-x64, area-CodeGen-coreclr, blocking-clean-ci-optional
