### ISSUE TITLE
`JsonTypeInfoResolver` doesn't populate inherited properties in interface hierarchy

### ISSUE THREAD

**Issue by captainsafia** [dotnet/runtime#77276] opened 2022-10-20 15:58 UTC
### Description

Using the `DefaultJsonTypeInfoResolver` API to identify the properties for an interface in a type hierarchy does not populate inherited properties in `JsonTypeInfo.Properties`.

### Reproduction Steps

```csharp
using System.Text.Json;
using System.Text.Json.Serialization.Metadata;

GetPropertiesFromType(typeof(IBaseInterface));
GetPropertiesFromType(typeof(ISubInterface1));
GetPropertiesFromType(typeof(ISubInterface2));
GetPropertiesFromType(typeof(IMultiSubInterface));


static void GetPropertiesFromType(Type type)
{
    var typeInfoResolver = new DefaultJsonTypeInfoResolver();
    var jsonType = typeInfoResolver.GetTypeInfo(type, JsonSerializerOptions.Default);

    if (jsonType.Kind == JsonTypeInfoKind.Object)
    {
        Console.WriteLine(string.Join(", ", jsonType.Properties.Select(property => property.Name)));
    }
}

interface IBaseInterface
{
    string BaseProperty { get; set; }
}

interface ISubInterface1 : IBaseInterface
{
    int Property1 { get; set; }
}

interface ISubInterface2 : IBaseInterface
{
    int Property2 { get; set; }
}

interface IMultiSubInterface : ISubInterface1, ISubInterface2
{
    int Property3 { get; set; }
}
```

### Expected behavior

```
$ dotnet run
BaseProperty
Property1, BaseProperty
Property2, BaseProperty
Property3, Property2, Property1, BaseProperty
```

### Actual behavior

```
$ dotnet run
BaseProperty
Property1
Property2
Property3
```

### Configuration

```
dotnet --info
.NET SDK:
 Version:   7.0.100-rtm.22478.4
 Commit:    9624df5579

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.6
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /Users/captainsafia/.dotnet/sdk/7.0.100-rtm.22478.4/

Host:
  Version:      7.0.0-rtm.22476.12
  Architecture: arm64
  Commit:       915dc27235
```

**Comment by eiriktsarpalis** [comment] 2022-10-20 16:12
Duplicate of #41749. We were hoping to address this in .NET 7 but ran into design questions regarding handling of [diamond ambiguities](https://github.com/dotnet/runtime/pull/73121#issuecomment-1201352790) that arise in interface hierarchies.

**Comment by eiriktsarpalis** [comment] 2022-10-20 16:13
cc @krwq @layomia we should prioritize this fix given a partner team is impacted by the bug.

**Closed by eiriktsarpalis** 2022-10-20 16:13 UTC
Labels: area-System.Text.Json, untriaged
