### ISSUE TITLE
[WebSockets] How to send Ping/Pong control frames, events for Ping frame sent by client.

### ISSUE THREAD

**Issue by ArjunVachhani** [dotnet/runtime#35473] opened 2020-04-26 07:20 UTC
WebSockets protocol provides mechanism to check the responsiveness of the other endpoint using ping and pong control frames. There is no API exposed to send ping/pong control frames. I hope it is handled by asp.net middleware internally, As there is `KeepAliveInterval` property to specify it. There should be API exposed for sending control frames, also events for pong/ping frames sent by clients.

**Having below API may help.**
- Sending Ping control frames.
- Events for Ping/Pong control frames sent by clients.

**This API may help in the various scenarios.**
- Identify unresponsive clients and disconnect.
- Keep the connection keep-alive.

**Comment by davidfowl** [comment] 2020-04-26 07:22
The Websocket API is defined in the BCL and it doesn’t expose a way to send or receive ping pong frames but it does handle them automatically (though that doesn’t help your scenario)

**Comment by stephentoub** [comment] 2020-04-26 10:21
> it doesn’t expose a way to send or receive ping pong frames but it does handle them automatically

It sends ping frames based on the specified keep-alive time, and sends pong frames in response to received ping frames.

**Comment by karelz** [comment] 2020-04-28 16:30
What is the advantage of having explicit APIs vs. relying on `KeepAliveInterval`? Which kind of scenarios are not possible to achieve today?

**Comment by davidsh** [comment] 2020-04-28 16:35
>It sends ping frames based on the specified keep-alive time, and sends pong frames in response to received ping frames.

@stephentoub 
I thought we sent "pong" frames and not "ping" frames for keep-alive. Sending unsolicited "pong" frames is usual because we then don't have to wait/keep-track of when we received a matching "pong" frame.

It is true that we also send "pong" frames in response to receiving a "ping" frame.

**Comment by stephentoub** [comment] 2020-04-28 16:37
> I thought we sent "pong" frames and not "ping" frames for keep-alive.

Nope:
https://github.com/dotnet/runtime/blob/7cbf0a7011813cb84c6c858ef19acb770daa777e/src/libraries/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L518

**Comment by davidsh** [comment] 2020-04-28 16:40
>We don't actually keep track of whether we receive a pong in response.

Interesting. I was probably remembering our other implementations of WebSocket (such as WinHTTP and .NET Framework).

But looking at these comments in the code:

```
// This exists purely to keep the connection alive; don't wait for the result, and ignore any failures.
// The call will handle releasing the lock.
``

we should actually be sending unsolicited pong frames as a keep-alive mechanism.  Sending a ping frame and not waiting for the pong return is sort of a violation of the WebSocket RFC.

**Comment by stephentoub** [comment] 2020-04-28 16:41
> Sending a ping frame and not waiting for the pong return is sort of a violation of the WebSocket RFC.

Interesting.  Can you point to where?  I don't have a strong opinion here; we can do whichever makes more sense.

**Comment by davidsh** [comment] 2020-04-28 16:48
Well, I just looked at the spec again.  And it seems to be missing that specific recommendation.

Reading sections 5.5.2 and 5.5.3 regarding Ping and Pong:
https://tools.ietf.org/html/rfc6455#page-37

>NOTE: A Ping frame may serve either as a keepalive or as a means to verify that the remote endpoint is still responsive.

> A Pong frame MAY be sent unsolicited.  This serves as a unidirectional heartbeat.  A response to an unsolicited Pong frame is not expected.

But I do remember several years ago when we were discussing this in the RFC (draft at the time). The assumption was that if you were going to send a ping and a pong didn't come then you needed to assume that the connection went bad and return a possible error.

That's why we selected the "unsolicited pong" mechanism as the keep-alive for WinHTTP/WinINet and .NET Framework. This reduced the complexity of tracking waiting for a pong to be returned from sending a ping.

**Comment by ArjunVachhani** [comment] 2020-04-29 12:13
> What is the advantage of having explicit APIs vs. relying on `KeepAliveInterval`? Which kind of scenarios are not possible to achieve today?

probably disconnect when client fails to respond pong for ping 3 times in a row

**Comment by karelz** [comment] 2020-06-02 19:39
Triage: @ArjunVachhani it is still not clear to us what kind of scenario explicit API for sending Pings and receiving Poings enables that is interesting.
Do you have something specific in mind, or is it just "it would be nice to have it"?

**Comment by halter73** [comment] 2020-06-02 20:51
@karelz This could help gRPC streaming scenarios. See https://github.com/grpc/grpc-dotnet/issues/770.

If a gRPC stream goes idle for long enough, and it's the only active stream over the HTTP/2 connection, the entire TCP connection will become completely idle. The client might never observe a lost connection it if it never sends more data to the server (e.g. a pure server-to-client streaming scenario). I've also seen proxies terminate idle TCP connections.

**Comment by karelz** [comment] 2020-06-02 20:55
@halter73 this is We sockets ;)

**Comment by ArjunVachhani** [comment] 2020-06-03 05:32
@karelz it is nice to have feature.

**Comment by karelz** [comment] 2020-06-03 18:29
Thanks @ArjunVachhani, in that case I recommend to close this issue.
The key scenario is to make sure the Ping/Pong frames are sent, received and confirmed. To our best knowledge it is the case today based on [`KeepAliveInterval`](https://apisof.net/catalog/System.Net.WebSockets.ClientWebSocketOptions.KeepAliveInterval) (if not, please open a new issue tracking that). Adding additional APIs would confuse developers and encourage them to handle things manually when they are not needed.

If there are advanced scenarios demonstrated in real world, where current solution is not sufficient, we could reopen the discussion and wait for additional demand to consider it in future. It does not seem to be the case at this moment though.

**Closed by karelz** 2020-06-03 18:29 UTC
Labels: api-suggestion, area-System.Net, needs more info
