### ISSUE TITLE
CI failure in JIT.HardwareIntrinsics WASM test Vector64_ro: SDK Microsoft.Build.NoTargets/3.5.0 could not be found

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#75714] opened 2022-09-15 20:37 UTC
Found in this unrelated `release/7.0-rc2` PR: https://github.com/dotnet/runtime/pull/75698

Please help determine if this issue needs a fix backported to the 7.0-rc2 branch.

Queue: Build Browser wasm Linux Release AllSubsets_Mono_RuntimeTests
Job results: https://dev.azure.com/dnceng-public/public/_build/results?buildId=18608&view=logs&j=190ad6c8-5950-568c-cadd-f2dfb7d5a79f&t=c0f6fdc1-ac5d-583c-8ae1-a18de0846552&l=37
Log: https://helix.dot.net/api/2019-06-17/jobs/f4aec578-e234-4f34-9dd0-ddd86550d4e9/workitems/JIT.HardwareIntrinsics.General.Vector64/console
Callstack:
```
Microsoft.DotNet.XUnitConsoleRunner v2.5.0 (64-bit .NET 7.0.0-rc.1.22423.16)
  Discovering: JIT.HardwareIntrinsics.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  JIT.HardwareIntrinsics.XUnitWrapper (found 4 of 362 test cases)
  Starting:    JIT.HardwareIntrinsics.XUnitWrapper (parallel test collections = on, max threads = 2)
    JIT/HardwareIntrinsics/General/Vector64/Vector64_ro/Vector64_ro.sh [FAIL]
      
      Return code:      1
      Raw output file:      /datadisks/disk1/work/B5A309B6/w/9DD308FF/uploads/Reports/JIT.HardwareIntrinsics/General/Vector64/Vector64_ro/Vector64_ro.output.txt
      Raw output:
      BEGIN EXECUTION
      
      Welcome to .NET 7.0!
      ---------------------
      SDK Version: 7.0.100-rc.1.22431.11
      
      ----------------
      Installed an ASP.NET Core HTTPS development certificate.
      To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
      Learn about HTTPS: https://aka.ms/dotnet-https
      ----------------
      Write your first app: https://aka.ms/dotnet-hello-world
      Find out what's new: https://aka.ms/dotnet-whats-new
      Explore documentation: https://aka.ms/dotnet-docs
      Report issues and find source on GitHub: https://github.com/dotnet/core
      Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
      --------------------------------------------------------------------------------------
      MSBuild version 17.4.0-preview-22416-02+5d102ae37 for .NET
      /datadisks/disk1/work/B5A309B6/p/wasm-test-runner/WasmTestRunner.proj : error : Failed to resolve SDK 'Microsoft.Build.NoTargets/3.5.0'. Package restore was successful but a package with the ID of "Microsoft.Build.NoTargets" was not installed.
      /datadisks/disk1/work/B5A309B6/p/wasm-test-runner/WasmTestRunner.proj : error MSB4236: The SDK 'Microsoft.Build.NoTargets/3.5.0' specified could not be found.
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/datadisks/disk1/work/B5A309B6/p
      > /datadisks/disk1/work/B5A309B6/w/9DD308FF/e/JIT/HardwareIntrinsics/General/Vector64/Vector64_ro/Vector64_ro.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at JIT_HardwareIntrinsics._General_Vector64_Vector64_ro_Vector64_ro_._General_Vector64_Vector64_ro_Vector64_ro_sh()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
           at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
      Output:
        
        Return code:      1
        Raw output file:      /datadisks/disk1/work/B5A309B6/w/9DD308FF/uploads/Reports/JIT.HardwareIntrinsics/General/Vector64/Vector64_ro/Vector64_ro.output.txt
        Raw output:
        BEGIN EXECUTION
        
        Welcome to .NET 7.0!
        ---------------------
        SDK Version: 7.0.100-rc.1.22431.11
        
        ----------------
        Installed an ASP.NET Core HTTPS development certificate.
        To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
        Learn about HTTPS: https://aka.ms/dotnet-https
        ----------------
        Write your first app: https://aka.ms/dotnet-hello-world
        Find out what's new: https://aka.ms/dotnet-whats-new
        Explore documentation: https://aka.ms/dotnet-docs
        Report issues and find source on GitHub: https://github.com/dotnet/core
        Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
        --------------------------------------------------------------------------------------
        MSBuild version 17.4.0-preview-22416-02+5d102ae37 for .NET
        /datadisks/disk1/work/B5A309B6/p/wasm-test-runner/WasmTestRunner.proj : error : Failed to resolve SDK 'Microsoft.Build.NoTargets/3.5.0'. Package restore was successful but a package with the ID of "Microsoft.Build.NoTargets" was not installed.
        /datadisks/disk1/work/B5A309B6/p/wasm-test-runner/WasmTestRunner.proj : error MSB4236: The SDK 'Microsoft.Build.NoTargets/3.5.0' specified could not be found.
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/datadisks/disk1/work/B5A309B6/p
        > /datadisks/disk1/work/B5A309B6/w/9DD308FF/e/JIT/HardwareIntrinsics/General/Vector64/Vector64_ro/Vector64_ro.sh
  Finished:    JIT.HardwareIntrinsics.XUnitWrapper
=== TEST EXECUTION SUMMARY ===
   JIT.HardwareIntrinsics.XUnitWrapper  Total: 4, Errors: 0, Failed: 1, Skipped: 0, Time: 11.399s
```

**Comment by lewing** [comment] 2022-09-16 02:22
duplicate of https://github.com/dotnet/runtime/issues/75391

**Closed by lewing** 2022-09-16 02:22 UTC
Labels: arch-wasm, untriaged, test-failure
