### ISSUE TITLE
Test failure: JIT/Methodical/Invoke/fptr/_il_dbgvalftn_t/_il_dbgvalftn_t.sh

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#34002] opened 2020-03-24 06:12 UTC
failed in job: [runtime-coreclr jitstress 20200323.1](https://dev.azure.com/dnceng/public/_build/results?buildId=569982&view=ms.vss-test-web.build-test-results-tab&runId=17887870&resultId=107777&paneView=debug)

Error message
~~~
Assert failure(PID 3229 [0x00000c9d], Thread: 3229 [0x0c9d]): SanityCheck()
File: /__w/1/s/src/coreclr/src/vm/methodtable.cpp Line: 9822
Image: /root/helix/work/correlation/corerun
/root/helix/work/workitem/JIT/Methodical/Invoke/fptr/_il_dbgvalftn_t/_il_dbgvalftn_t.sh: line 275: 3229 Aborted $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
Return code: 1
Raw output file: /root/helix/work/workitem/JIT/Methodical/Reports/JIT.Methodical/Invoke/fptr/_il_dbgvalftn_t/_il_dbgvalftn_t.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun _il_dbgvalftn_t.dll ''
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.3229.dmp
Written 51908608 bytes (12673 pages) to core file
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/JIT/Methodical/Invoke/fptr/_il_dbgvalftn_t/_il_dbgvalftn_t.sh
Expected: True
Actual: False


Stack trace
   at JIT_Methodical._Invoke_fptr__il_dbgvalftn_t__il_dbgvalftn_t_._Invoke_fptr__il_dbgvalftn_t__il_dbgvalftn_t_sh() in /__w/1/s/artifacts/tests/coreclr/Linux.arm.Checked/TestWrappers/JIT.Methodical/JIT.Methodical.XUnitWrapper.cs:line 131575
~~~

category:correctness
theme:testing
skill-level:expert
cost:medium

**Comment by BruceForstall** [comment] 2020-03-24 17:04
Looks like this is `COMPlus_ZapDisable=1`

**Comment by BruceForstall** [comment] 2020-03-24 17:05
@janvorli This isn't a GCStress case, but it is Linux/arm. Maybe the same issue as https://github.com/dotnet/runtime/issues/33366?

**Comment by janvorli** [comment] 2020-03-24 17:08
@BruceForstall basically anything that shows assert somewhere in MethodTable is most likely caused by a GC hole. So I would put it into the same bucket as #33366

**Comment by v-haren** [comment] 2020-04-14 05:29
failed again in job: [runtime-coreclr jitstress 20200412.1](https://dev.azure.com/dnceng/public/_build/results?buildId=598080&view=ms.vss-test-web.build-test-results-tab&runId=18860850&resultId=107264&paneView=debug)


Error message
~~~
Assert failure(PID 2095 [0x0000082f], Thread: 2095 [0x082f]): SanityCheck()
File: /__w/1/s/src/coreclr/src/vm/methodtable.cpp Line: 9822
Image: /root/helix/work/correlation/corerun
/root/helix/work/workitem/JIT/Methodical/Invoke/fptr/_il_dbgvalftn_t/_il_dbgvalftn_t.sh: line 275: 2095 Aborted $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
Return code: 1
Raw output file: /root/helix/work/workitem/JIT/Methodical/Reports/JIT.Methodical/Invoke/fptr/_il_dbgvalftn_t/_il_dbgvalftn_t.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun _il_dbgvalftn_t.dll ''
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.2095.dmp
Written 51769344 bytes (12639 pages) to core file
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/JIT/Methodical/Invoke/fptr/_il_dbgvalftn_t/_il_dbgvalftn_t.sh
Expected: True
Actual: False


Stack trace
   at JIT_Methodical._Invoke_fptr__il_dbgvalftn_t__il_dbgvalftn_t_._Invoke_fptr__il_dbgvalftn_t__il_dbgvalftn_t_sh() in /__w/1/s/artifacts/tests/coreclr/Linux.arm.Checked/TestWrappers/JIT.Methodical/JIT.Methodical.XUnitWrapper.cs:line 131575
~~~

**Comment by BruceForstall** [comment] 2020-06-22 22:51
I don't see any recent failures, so closing.

**Closed by BruceForstall** 2020-06-22 22:51 UTC
Labels: JitStress, arch-arm32, area-CodeGen-coreclr, os-linux
