### ISSUE TITLE
Missing methods in MethodBuild

### ISSUE THREAD

**Issue by Hitmasu** [dotnet/runtime#30559] opened 2019-08-10 22:16 UTC
Hi,

I was looking for some way to create a method in runtime and i realized [MethodBuilder](https://docs.microsoft.com/pt-br/dotnet/api/system.reflection.emit.methodbuilder?view=netframework-4.8) is partially implemented. Methods like [CreateMethodBody](https://docs.microsoft.com/pt-br/dotnet/api/system.reflection.emit.methodbuilder.createmethodbody?view=netframework-4.8) and [SetMethodBody](https://docs.microsoft.com/pt-br/dotnet/api/system.reflection.emit.methodbuilder.setmethodbody?view=netframework-4.8) are missing.

Do you have any plans on implementing those methods in a near future?

**Comment by steveharter** [comment] 2020-04-01 21:49
Treating this as a duplicate of https://github.com/dotnet/runtime/issues/7636

@Hitmasu what scenario are you trying to solve and by `MethodBuilder.GetIlGenerator` can't be used?

**Closed** 2020-04-01 21:49 UTC
Labels: area-System.Reflection.Emit, question
