### ISSUE TITLE
[mono] [android] System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_DomainName_ReturnsEmptyStringWhenNotSet fails

### ISSUE THREAD

**Issue by jkurdek** [dotnet/runtime#109280] opened 2024-10-28 13:39 UTC
`android_arm64_release_allsubsets_mono`. Also `arm`, `x64`, `x86`.

Stack trace
```
10-28 05:55:04.448 11762 11805 I DOTNET  : Failed tests:
10-28 05:55:04.448 11762 11805 I DOTNET  : 1) 	[FAIL] System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_DomainName_ReturnsEmptyStringWhenNotSet   Test name: System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_DomainName_ReturnsEmptyStringWhenNotSet
10-28 05:55:04.448 11762 11805 I DOTNET  :    Assembly:  [System.Net.NetworkInformation.Functional.Tests, Version=10.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]
10-28 05:55:04.448 11762 11805 I DOTNET  :    Exception messages: Assert.Equal() Failure: Strings differ
10-28 05:55:04.448 11762 11805 I DOTNET  : Expected: ""
10-28 05:55:04.448 11762 11805 I DOTNET  : Actual:   "localdomain"
10-28 05:55:04.448 11762 11805 I DOTNET  :            Γåæ (pos 0)   Exception stack traces:    at System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_DomainName_ReturnsEmptyStringWhenNotSet() in /_/src/libraries/System.Net.NetworkInformation/tests/FunctionalTests/IPGlobalPropertiesTest.cs:line 215
10-28 05:55:04.448 11762 11805 I DOTNET  :    at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
10-28 05:55:04.448 11762 11805 I DOTNET  :    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)

```

## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=850434
Build error leg or test failing: System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_DomainName_ReturnsEmptyStringWhenNotSet

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_DomainName_ReturnsEmptyStringWhenNotSet",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=850434
**Error message validated:** `[System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_DomainName_ReturnsEmptyStringWhenNotSet`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 10/28/2024 1:39:53 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[881982](https://dev.azure.com/dnceng-public/public/_build/results?buildId=881982)|dotnet/runtime|[System.Net.NetworkInformation.Tests.IPGlobalPropertiesTest.IPGlobalProperties_DomainName_ReturnsEmptyStringWhenNotSet](https://dev.azure.com/dnceng-public/public/_build/results?buildId=881982&view=ms.vss-test-web.build-test-results-tab&runId=23056774&resultId=152813)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|1|

**Comment by matouskozak** [comment] 2024-11-15 11:03
The range for regression is https://github.com/dotnet/runtime/compare/a09ad529...10ee2b11. Possibly related to https://github.com/dotnet/runtime/pull/107241, @wfurt could you please check it out?

**Comment by wfurt** [comment] 2024-11-16 10:00
it is likely @matouskozak. At least the test was added there. It seems like Android injects something there. I guess one option would be to simply skip this test on Android. Any thoughts on this @simonrozsival ?

**Comment by simonrozsival** [comment] 2024-11-18 12:14
@matouskozak @wfurt this seems to be the default value on Android. I am not sure if this is the default/fallback value in the bionic libc or if Android calls `setdomainname("localdomain")` and it is a valid value. I think we should just skip this test because Android.

**Comment by wfurt** [comment] 2024-11-21 16:49
I look at the test again @antonfirsov and I think we should update the assert to expect the `localdomain` on Android. I think I would prefer that over disabling the test.

**Comment by matouskozak** [comment] 2024-12-27 08:22
Fixed in https://github.com/dotnet/runtime/pull/110070

**Closed by matouskozak** 2024-12-27 08:22 UTC
Labels: arch-arm64, area-System.Net, arch-x64, os-android, Known Build Error
