### ISSUE TITLE
MultipleOperationsOverSingleHandle_CompletedWorkItemCountTest failed in CI

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#48236] opened 2021-02-12 19:29 UTC
Failed on coreclr windows x86 Debug leg of https://github.com/dotnet/runtime/pull/48181.

See logs

https://dev.azure.com/dnceng/public/_build/results?buildId=992107&view=logs&j=9d8498d2-c5b7-54d8-6df7-a2ce7e14e68c&t=34b459a3-e64e-5ccc-0adc-77ebca2601a8&l=71

https://helix.dot.net/api/2019-06-17/jobs/38c5fe46-1522-4e22-b980-c873a017f3b7/workitems/System.Threading.Overlapped.Tests/console

```
C:\h\w\A3C008E7\w\B5AD09D1\e>"C:\h\w\A3C008E7\p\dotnet.exe" exec --runtimeconfig System.Threading.Overlapped.Tests.runtimeconfig.json --depsfile System.Threading.Overlapped.Tests.deps.json xunit.console.dll System.Threading.Overlapped.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Threading.Overlapped.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Threading.Overlapped.Tests (found 61 of 62 test cases)
  Starting:    System.Threading.Overlapped.Tests (parallel test collections = on, max threads = 2)
    ThreadPoolBoundHandleTests.MultipleOperationsOverSingleHandle_CompletedWorkItemCountTest [FAIL]
      Assert.InRange() Failure
      Range:  (0 - 30000)
      Actual: 30016
      Stack Trace:
        /_/src/libraries/Common/tests/System/Threading/ThreadTestHelpers.cs(147,0): at System.Threading.Tests.ThreadTestHelpers.WaitForConditionWithCustomDelay(Func`1 condition, Action delay)
        /_/src/libraries/Common/tests/System/Threading/ThreadTestHelpers.cs(117,0): at System.Threading.Tests.ThreadTestHelpers.WaitForCondition(Func`1 condition)
        /_/src/libraries/System.Threading.Overlapped/tests/ThreadPoolBoundHandle_IntegrationTests.netcoreapp.cs(16,0): at ThreadPoolBoundHandleTests.MultipleOperationsOverSingleHandle_CompletedWorkItemCountTest()
  Finished:    System.Threading.Overlapped.Tests
=== TEST EXECUTION SUMMARY ===
   System.Threading.Overlapped.Tests  Total: 61, Errors: 0, Failed: 1, Skipped: 0, Time: 30.445s
```

**Comment by danmoseley** [comment] 2021-02-13 00:49
We should probably just change 30s to 60s for all these tests.

**Comment by VincentBu** [comment] 2021-03-08 01:53
Failed again in [runtime 20210306.40](https://dev.azure.com/dnceng/public/_build/results?buildId=1026190&view=ms.vss-test-web.build-test-results-tab&runId=31885854&resultId=147164&paneView=debug)

Failed test:
```
net6.0-windows-Release-x64-CoreCLR_checked-Windows.10.Amd64.Open
 -ThreadPoolBoundHandleTests.MultipleOperationsOverSingleHandle_CompletedWorkItemCountTest
```

**Error message:**
```
Assert.InRange() Failure
Range:  (0 - 30000)
Actual: 30016


Stack trace
   at System.Threading.Tests.ThreadTestHelpers.WaitForConditionWithCustomDelay(Func`1 condition, Action delay) in /_/src/libraries/Common/tests/System/Threading/ThreadTestHelpers.cs:line 147
   at System.Threading.Tests.ThreadTestHelpers.WaitForCondition(Func`1 condition) in /_/src/libraries/Common/tests/System/Threading/ThreadTestHelpers.cs:line 117
   at ThreadPoolBoundHandleTests.MultipleOperationsOverSingleHandle_CompletedWorkItemCountTest() in /_/src/libraries/System.Threading.Overlapped/tests/ThreadPoolBoundHandle_IntegrationTests.netcoreapp.cs:line 16
```

**Comment by danmoseley** [comment] 2021-03-09 18:36
I'm going to close this optimistically. If the timeout increase isn't enough, we should reopen.

**Comment by VincentBu** [comment] 2021-03-11 01:45
Failed again in [runtime 20210310.56](https://dev.azure.com/dnceng/public/_build/results?buildId=1031698&view=ms.vss-test-web.build-test-results-tab&runId=32023496&resultId=181007&paneView=debug)

Failed test:
```
net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c
 -ThreadPoolBoundHandleTests.MultipleOperationsOverSingleHandle_CompletedWorkItemCountTest
```

**Error message:**
```
Assert.InRange() Failure
Range:  (0 - 60000)
Actual: 60016


Stack trace
   at System.Threading.Tests.ThreadTestHelpers.WaitForConditionWithCustomDelay(Func`1 condition, Action delay) in /_/src/libraries/Common/tests/System/Threading/ThreadTestHelpers.cs:line 147
   at System.Threading.Tests.ThreadTestHelpers.WaitForCondition(Func`1 condition) in /_/src/libraries/Common/tests/System/Threading/ThreadTestHelpers.cs:line 117
   at ThreadPoolBoundHandleTests.MultipleOperationsOverSingleHandle_CompletedWorkItemCountTest() in /_/src/libraries/System.Threading.Overlapped/tests/ThreadPoolBoundHandle_IntegrationTests.netcoreapp.cs:line 16
```

**Comment by danmoseley** [comment] 2021-03-11 02:12
There's our answer, it is very likely a true hang. @kouvel  could you please take a look?

**Comment by benaadams** [comment] 2021-03-11 14:56
Seen in https://github.com/dotnet/runtime/pull/49388
```
Assert.InRange() Failure\r\nRange:  (0 - 60000)\r\nActual: 60016


Stack trace
   at System.Threading.Tests.ThreadTestHelpers.WaitForConditionWithCustomDelay(Func`1 condition, Action delay) in /_/src/libraries/Common/tests/System/Threading/ThreadTestHelpers.cs:line 147
   at System.Threading.Tests.ThreadTestHelpers.WaitForCondition(Func`1 condition) in /_/src/libraries/Common/tests/System/Threading/ThreadTestHelpers.cs:line 117
   at ThreadPoolBoundHandleTests.MultipleOperationsOverSingleHandle_CompletedWorkItemCountTest() in /_/src/libraries/System.Threading.Overlapped/tests/ThreadPoolBoundHandle_IntegrationTests.netcoreapp.cs:line 16
```

**Comment by danmoseley** [comment] 2021-03-11 15:59
@kouvel @mangod9 is there instrumentation that might help root cause this?

**Comment by danmoseley** [comment] 2021-03-11 16:00
Hits above seem to be all windows, but at least one is release.

**Comment by mangod9** [comment] 2021-03-11 16:57
Will try to repro this.

**Comment by mangod9** [comment] 2021-07-26 15:55
Havent been able to repro this recently. Closing for now, please reactivate if its still an issue.

**Closed by mangod9** 2021-07-26 15:55 UTC
Labels: area-System.Threading, blocking-clean-ci
