### ISSUE TITLE
Inconsistent `ParamName` for `ArgumentException`s

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/runtime#36517] opened 2020-05-15 06:51 UTC
This small piece of code:

```csharp
using System;
using System.Net;

public class Program
{
  public static void Main()
  {
    var client = new WebClient();
    try
    {
      client.Encoding = null;
    }
    catch (ArgumentException e)
    {
      Console.WriteLine(e.ParamName);
    }

    try
    {
      client.BaseAddress = "invalid address";
    }
    catch (ArgumentException e)
    {
      Console.WriteLine(e.ParamName);
    }
    
  }
}
```

prints the following output:

```csharp
Encoding
value
```

The expected output is either:

```
value
value
```

or

```
Encoding
BaseAddress
```

**Comment by danmosemsft** [comment] 2020-07-06 18:49
I believe @bartonjs indicated that these should be `value` - although this feels wrong to me, as it's strictly less helpful, I defer to the rules. Not sure it's worth going through and trying to consistentify though.

**Comment by Youssef1313** [comment] 2020-07-06 18:53
@danmosemft, I'd at least have consistency in the same class (if it's hard to be through the whole repo).

If you'd want to have consistency through the repo, perhaps it's a candidate for a configurable analyzer.

**Comment by bartonjs** [comment] 2020-07-06 19:01
"DO use `value` for the name of the implicit value parameter of property setters." was already the guideline from the second edition of .NET Framework Design Guidelines (and probably the first, but I'd have to go grab a copy off a shelf to verify that, and the book doesn't respond to Ctrl+F), with regard to the proper name of `paramName` values in the `ArgumentException` family of exceptions.

So, yeah, `value`/`value` is the expected result, per FDG.

**Comment by danmosemsft** [comment] 2020-07-06 19:11
@bartonjs do you think that is the right guidance - after all, we have the power to change FDG if we don't think it's doing the right thing. It sounds like this pre-dates you. What is/was their reasoning, do you know? Is there a consideration other than diagnosability?

**Comment by bartonjs** [comment] 2020-07-06 19:20
The guideline, effectively, is "use the name of the parameter that was invalid, and nothing else".  So don't report that "something.SomeProp" was invalid, instead report that "something" was invalid (and use the message to report what the context was) (yeah, this is a differently contentious issue).  The one for properties is remind you "the name of the parameter is `value`, the name of the current method is context, so it's part of the message (or just the call stack) not the paramName value."

It's not something that I'd personally fight hard to change if we already said "DO use the name of the property", but I do (ceteris paribus) believe that `value` is more correct than the name of the property.  Property sets are just syntactic sugar around calling a method named `public Encoding set_Encoding(Encoding value)`, and the correct behavior for that method is to report parameter errors as an error in the `value` parameter.

Reporting against the name of the parameter (in this case `value`) and not complex evaluation strings (like the name of the property or "something.SomeProp") would theoretically allow for debuggers to highlight expressions at the callsite for "this is what the called method reported as invalid", without special casing property sets.

(Per sharplab.io, the compiler turns property sets (and gets) into method calls, so from IL there wasn't a property:

```C#
using System;
public class C {
    public bool P { get; set; }
    
    public void M() {
        var x = P = false;
    }
}
```

```MSIL
    .method public hidebysig 
        instance void M () cil managed 
    {
        // Method begins at RVA 0x2064
        // Code size 14 (0xe)
        .maxstack 3
        .locals init (
            [0] bool x,
            [1] bool
        )

        IL_0000: nop
        IL_0001: ldarg.0
        IL_0002: ldc.i4.0
        IL_0003: dup
        IL_0004: stloc.1
        IL_0005: call instance void C::set_P(bool)
        IL_000a: nop
        IL_000b: ldloc.1
        IL_000c: stloc.0
        IL_000d: ret
    } // end of method C::M
```

**Comment by danmosemsft** [comment] 2020-07-06 20:44
OK fair enough (and I learned a new phrase `ceteris paribus`). Thoughts about taking fixes where we don't use `value` today? I could see this generating quite a few PR's if it was done bits at a time. If we care about regularization (I'm assuming it's not a high priority but we'd take community changes) presumably we'd ask for a small number of PR's, perhaps starting by writing an analyzer.

**Comment by danmosemsft** [comment] 2020-07-06 20:44
That assumes that this isn't already part of @buyaa-n 's analyzer.

**Comment by bartonjs** [comment] 2020-07-06 22:11
It... should be covered by that analyzer. Since I feel like that was the last place this conversation came up.  Not sure why this one didn't get caught in the cleanup.

The PR that already got opened at least makes the WebClient type self-consistent.  "Area-sweeps" or "library-sweeps" seem like the right size for me, but I don't think we'd say no to a PR that at least took care of everything in a single type.

**Comment by buyaa-n** [comment] 2020-07-07 18:41
That property calling a private helper method where the exception is thrown correctly (with one of the parameters):
```csharp
        private static void ThrowIfNull(object argument, string parameterName)
        {
            if (argument == null)
            {
                throw new ArgumentNullException(parameterName);
            }
        }
```
Also we have configured it to apply only for public members because of too much noise caused by throw helpers

**Comment by louis-z** [comment] 2020-10-07 01:38
The issue appears to have been fixed:

https://github.com/dotnet/runtime/blob/1be890714a7dc5fb2de5da4ab72475e0f2d6a0e5/src/libraries/System.Net.WebClient/src/System/Net/WebClient.cs#L147

**Comment by Youssef1313** [comment] 2020-10-07 01:50
@louis-z The specific example is fixed. But not ensured (through an analyzer or something) across the codebase

**Comment by buyaa-n** [comment] 2020-10-07 06:12
> But not ensured (through an analyzer or something) across the codebase

The argument exception analyzer would warn if any other `name` is used instead of `value` parameter name, (by default for public APIs only), Wondering what else you want to make ensured @Youssef1313

**Comment by Youssef1313** [comment] 2020-10-07 10:19
It would be better if the analyzer is using data flow to work well for throw helper methods. But I'm also okay to use the existing analyzer as is.

**Comment by louis-z** [comment] 2020-10-07 16:59
> @louis-z The specific example is fixed. But not ensured (through an analyzer or something) across the codebase

Right. 🤦‍♂️ 

If you're in no hurry, @Youssef1313,  I might be interested in taking a stab at it. Would you have a few pointers? I've never used data flow, but I'm guessing it comes from the semantic model.

**Comment by Youssef1313** [comment] 2020-10-07 17:14
I think writing an analyzer (or updating the existing one) to do this using data flow would be a little bit hard. You can use the existing analyzer.

**Comment by buyaa-n** [comment] 2020-10-07 17:47
@louis-z the data flow analysis could help with this scenario is [interprocedural analysis](https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Writing%20dataflow%20analysis%20based%20analyzers.md#interprocedural-dataflow-analysis)

If you want to work on it here is some suggestions:
- I believe we don't need new analyzer for this, it should be an improvement to the [existing analyzer ](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2208)
- As analyzers are in different repo, so please file an issue into [roslyn-analyzers](https://github.com/dotnet/roslyn-analyzers). 
- Instruction for [getting started]( https://github.com/dotnet/roslyn-analyzers/blob/master/docs/NetCore_GettingStarted.md) with NetCore analyzers
- The existing analyzer code is [here](https://github.com/dotnet/roslyn-analyzers/blob/master/src/NetAnalyzers/Core/Microsoft.NetCore.Analyzers/Runtime/InstantiateArgumentExceptionsCorrectly.cs)
- Data flow analysis is expensive, i believe we wouldn't like it enabled by default, you might need to make the existing analyzer configurable with [interprocedural analysis](https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md#interprocedural-analysis-kind)

With that being said as the issue mentioned here is fixed and the remaining question is related to [roslyn-analyzer](https://github.com/dotnet/roslyn-analyzers) we could close this issue, what you think @Youssef1313

**Comment by Youssef1313** [comment] 2020-10-07 18:00
@buyaa-n Given that the analyzer is enabled in the repo, I think yes we can close. Any enhancements of the analyzer will get reflected here when it's updated.

**Closed** 2020-10-07 18:00 UTC
Labels: area-System.Runtime, bug, up-for-grabs

**Comment by louis-z** [comment] 2020-10-07 20:28
Thank you both @Youssef1313 and @buyaa-n.
Using the aforementioned links, I will definitely look further into the matter.
