### ISSUE TITLE
System.IO.FileSystem.Tests crashing on CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#54615] opened 2021-06-23 16:37 UTC
```
  Discovering: System.IO.FileSystem.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.IO.FileSystem.Tests (found 3232 of 3745 test cases)
  Starting:    System.IO.FileSystem.Tests (parallel test collections = on, max threads = 4)
    System.IO.Tests.FileStream_SafeFileHandle.ThrowWhenHandlePositionIsChanged_async [SKIP]
      Condition(s) not met: "IsNet5CompatFileStreamEnabled"
    System.IO.Tests.FileStream_SafeFileHandle.ThrowWhenHandlePositionIsChanged_sync [SKIP]
      Condition(s) not met: "IsNet5CompatFileStreamEnabled"
    System.IO.Tests.Directory_CreateDirectory.PathWithReservedDeviceNameAsPath_ThrowsDirectoryNotFoundException [SKIP]
      Condition(s) not met: "ReservedDeviceNamesAreBlocked"
    System.IO.Tests.Directory_CreateDirectory.PathWithReservedDeviceNameAsExtendedPath [SKIP]
      Condition(s) not met: "ReservedDeviceNamesAreBlocked"
    System.IO.Tests.Directory_CreateDirectory.RootPath_AppContainer [SKIP]
      Condition(s) not met: "IsInAppContainer"
    System.IO.Tests.File_GetSetTimes.TimesIncludeMillisecondPart_LowTempRes [SKIP]
      Condition(s) not met: "LowTemporalResolution"
    System.IO.Tests.DirectoryInfo_GetSetTimes.TimesIncludeMillisecondPart_LowTempRes [SKIP]
      Condition(s) not met: "LowTemporalResolution"
    System.IO.Tests.DirectoryInfo_Create.RootPath_AppContainer [SKIP]
      Condition(s) not met: "IsInAppContainer"
    System.IO.Tests.DirectoryInfo_Create.PathWithReservedDeviceNameAsPath_ThrowsDirectoryNotFoundException [SKIP]
      Condition(s) not met: "ReservedDeviceNamesAreBlocked"
    System.IO.Tests.DirectoryInfo_Create.PathWithReservedDeviceNameAsExtendedPath [SKIP]
      Condition(s) not met: "ReservedDeviceNamesAreBlocked"
    System.IO.Tests.Directory_GetSetTimes.TimesIncludeMillisecondPart_LowTempRes [SKIP]
      Condition(s) not met: "LowTemporalResolution"
    System.IO.Tests.FileInfo_GetSetTimes.CopyToMillisecondPresent_LowTempRes [SKIP]
      Condition(s) not met: "LowTemporalResolution"
    System.IO.Tests.FileInfo_GetSetTimes.MoveToMillisecondPresent_LowTempRes [SKIP]
      Condition(s) not met: "LowTemporalResolution"
    System.IO.Tests.FileInfo_GetSetTimes.CopyToNanosecondsPresent_LowTempRes [SKIP]
      Condition(s) not met: "LowTemporalResolution"
    System.IO.Tests.FileInfo_GetSetTimes.TimesIncludeMillisecondPart_LowTempRes [SKIP]
      Condition(s) not met: "LowTemporalResolution"
{0x4c-0xeb303935} ASSERT [DEBUG  ] at /__w/1/s/src/coreclr/pal/src/debug/debug.cpp.766: write failed: errno is 9 (Bad file descriptor)
./RunTests.sh: line 162:    58 Aborted                 (core dumped) "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.IO.FileSystem.Tests.runtimeconfig.json --depsfile System.IO.FileSystem.Tests.deps.json xunit.console.dll System.IO.FileSystem.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
/root/helix/work/workitem
----- end Wed Jun 23 15:19:39 UTC 2021 ----- exit code 134 ----------------------------------------------------------
exit code 134 means SIGABRT Abort. Managed or native assert, or runtime check such as heap corruption, caused call to abort(). Core dumped.
```

Dump: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54544-merge-50ee15c3b1884514b8/System.IO.FileSystem.Tests/core.1001.58?sv=2019-07-07&se=2021-07-13T15%3A08%3A51Z&sr=c&sp=rl&sig=WCevmxsRkctupTJ9hCJHn%2FHH8yW2Uhmip7h%2FBxaf%2Bb0%3D

Console: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54544-merge-50ee15c3b1884514b8/System.IO.FileSystem.Tests/core.1001.58?sv=2019-07-07&se=2021-07-13T15%3A08%3A51Z&sr=c&sp=rl&sig=WCevmxsRkctupTJ9hCJHn%2FHH8yW2Uhmip7h%2FBxaf%2Bb0%3D

Configuration: `net6.0-Linux-Release-arm-CoreCLR_checked-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440`

cc @jkotas for the crash

**Comment by jkotas** [comment] 2021-06-23 16:43
Given the high recent churn in System.IO.FileSystem, it is likely a bug in libraries.

**Comment by jkotas** [comment] 2021-06-23 16:46
cc @adamsitnik

**Comment by carlossanlop** [comment] 2021-06-23 22:11
Might be related to: https://github.com/dotnet/runtime/issues/54589 (bad file descriptor)

**Comment by jkotas** [comment] 2021-06-24 00:13
Yes, it is almost certainly a duplicate of #54589

**Closed by jkotas** 2021-06-24 00:13 UTC
Labels: area-System.IO, bug, untriaged
