### ISSUE TITLE
Unexpectedly high latency of string utility functions on Linux (about 3 times higher than the same function on windows)

### ISSUE THREAD

**Issue by dmeytin** [dotnet/runtime#37919] opened 2020-06-15 19:06 UTC
# Issue Title
Unexpected latency of string utility functions on Linux
# General
I have used https://github.com/dotnet/BenchmarkDotNet  to test String.IndexOf on Windows and on Linux and the results below reveal almost 3 times latency difference for the function invocation on the random string of sizes 200 ... 1000, small constant pattern of the size 4 and OrdinalIgnoreCase culture

Latency of 1K executions are as following:
Linux: Avg : 3.151195819999976ms; Mean: 3.0258999999999796ms; Percentile_95: 3.8338250000000005ms
Windows: Avg : 1.136806029999999ms; Mean: 1.0643499999999961ms; Percentile_95: 1.5009250000000038ms

Here is the benchmark code:

<pre><code>
public class StringUtils
    {
        string randomString;
        string toSearch = " -p ";
        char[] pattern;

        [Params(200, 300, 400, 500, 600, 700, 800, 900, 1000)]
        public int N;

        public StringUtils()
        {
            pattern = toSearch.ToLower().ToCharArray();
        }

        [IterationSetup]
        public void BeforeEachStep()
        {
            randomString = GenerateRandomString(N);
        }
        
        [Benchmark]
        public void IndexOf()
        {
            randomString.IndexOf(toSearch, StringComparison.OrdinalIgnoreCase);
        } 

        private string GenerateRandomString(int length)
        {
            Random random = new Random();
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 -abcdefghijklmnopqrstuvwxyz!#@";
            return new string(Enumerable.Repeat(chars, length)
              .Select(s => s[random.Next(s.Length)]).ToArray());
        }
    }
</code></pre>

Although both VMs are created with the same Azure SKU (Standard_D2s_v3), the actual hardware is a bit different, but not significantly. 

BenchmarkDotNet=v0.12.1, OS=ubuntu 18.04
Intel Xeon CPU E5-2673 v4 2.30GHz, 1 CPU, 2 logical cores and 1 physical core
.NET Core SDK=3.1.301
  [Host]     : .NET Core 3.1.5 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.27001), X64 RyuJIT
  Job-YVSZZG : .NET Core 3.1.5 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.27001), X64 RyuJIT

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.14393.3750 (1607/AnniversaryUpdate/Redstone1)
Intel Xeon Platinum 8171M CPU 2.60GHz, 1 CPU, 2 logical cores and 1 physical core
.NET Core SDK=3.1.301
  [Host]     : .NET Core 3.1.5 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.27001), X64 RyuJIT
  Job-BSDYRT : .NET Core 3.1.5 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.27001), X64 RyuJIT

InvocationCount=1  UnrollFactor=1

And detailed results are as following:

|  OS   |           Method |    N |      Mean |     Error |    StdDev |    Median |
|------:|-----------------|----- |---------- |---------:|-----------|---------:|
| Linux|          IndexOf  |  200 | 5.329 us | 0.1135 us | 0.3145 us |  5.300 us |
|Windows|          IndexOf |  200 | 3.159 us | 0.1491 us | 0.4303 us | 3.200 us |
| Linux|          IndexOf |  300 |  7.700 us | 0.1570 us | 0.1927 us |  7.700 us |
|Windows|          IndexOf |  300 | 4.096 us | 0.1676 us | 0.4915 us | 4.100 us |
|Linux|          IndexOf |  400 |  8.800 us | 0.1714 us | 0.1519 us |  8.800 us |
|Windows|          IndexOf |  400 | 4.886 us | 0.2148 us | 0.6334 us | 5.050 us |
|Linux|          IndexOf |  500 | 11.604 us | 0.3069 us | 0.8192 us | 11.500 us |
|Windows|         IndexOf |  500 | 5.679 us | 0.2132 us | 0.6220 us | 5.650 us |
|Linux|          IndexOf |  600 | 12.933 us | 0.2662 us | 0.7107 us | 12.601 us |
|Windows|          IndexOf |  600 | 6.604 us | 0.2407 us | 0.7058 us | 6.700 us |
|Linux|          IndexOf |  700 | 14.443 us | 0.2824 us | 0.2504 us | 14.450 us |
|Windows|          IndexOf |  700 | 7.204 us | 0.1426 us | 0.2045 us | 7.100 us |
|Linux|          IndexOf |  800 | 17.629 us | 0.3564 us | 0.9575 us | 17.500 us |
|Windows|          IndexOf |  800 | 8.074 us | 0.3290 us | 0.9385 us | 8.200 us |
|Linux|          IndexOf |  900 | 19.018 us | 0.5516 us | 1.5194 us | 18.700 us |
|Windows|          IndexOf |  900 | 8.852 us | 0.3884 us | 1.1328 us | 9.050 us |
|Linux|          IndexOf | 1000 | 20.609 us | 0.4151 us | 0.8194 us | 20.350 us |
|Windows|          IndexOf | 1000 | 9.607 us | 0.3468 us | 1.0060 us | 9.700 us |

#Expected results
Linux latency should be at least as good as Windows

**Comment by GrabYourPitchforks** [comment] 2020-06-15 19:19
This is almost certainly an ICU / NLS behavior. ICU has a different philosophy for `IndexOf` than does NLS. For ICU, the typical calling pattern is that you create a _pattern_ object which represents the target substring you want to locate within the search space, and you invoke the pattern matcher over and over again to keep finding instances of the target substring. ICU's tradeoff is that the initial setup is a little expensive, but subsequent checks are fast assuming you use the same pattern object. On the managed side, since each call to `IndexOf` necessarily creates a new pattern matcher, we're paying for this overhead on every method invocation.

Related: https://github.com/dotnet/runtime/issues/37815, which proposes that we special-case `IndexOf(..., OrdinalIgnoreCase)` for ASCII inputs to avoid calling into ICU / NLS at all.

**Comment by dmeytin** [comment] 2020-06-15 19:50
@GrabYourPitchforks, thanks for your response.
Do we have any possible workaround to improve the performance?

**Comment by tarekgh** [comment] 2020-06-15 20:34
This is properly duplicate of https://github.com/dotnet/runtime/issues/26054 and https://github.com/dotnet/runtime/issues/37819

**Comment by tarekgh** [comment] 2020-06-15 20:36
> Do we have any possible workaround to improve the performance?

The best would be to avoid using ignore casing for now.

**Comment by weltkante** [comment] 2020-06-16 06:58
> The best would be to avoid using ignore casing for now.

So you propose workarounds like comparing ToUpper/ToLower normalized strings?

**Comment by dmeytin** [comment] 2020-06-16 07:50
Interestingly that setting Globalization Culture to invariant didn't helped...

**Comment by stephentoub** [comment] 2020-06-16 11:25
> Interestingly that setting Globalization Culture to invariant didn't helped...

Do you mean setting CultureInfo.CurrentCulture to CultureInfo.InvariantCulture, or do you mean enabling https://docs.microsoft.com/en-us/dotnet/core/run-time-config/globalization#invariant-mode? The names may be confusing, but I'd expect the latter to help and the former not to help.

**Comment by dmeytin** [comment] 2020-06-16 12:26
Actually I tried both approaches and did get any improvements.

**Comment by tarekgh** [comment] 2020-06-16 16:29
Using invariant culture wouldn't help much as we'll still need to call ICU at that time too. But if you use Invariant Globalization mode, that should be much faster (with losing globalization support with non-ASCII strings). are you sure you tried  Invariant Globalization mode and you didn't notice any difference?

**Comment by dmeytin** [comment] 2020-06-16 18:03
<PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

**Comment by tarekgh** [comment] 2020-06-16 18:11
You need to have the following in your csproj to enable the globalization invariant mode: 

```XML
<ItemGroup>
  <RuntimeHostConfigurationOption Include="System.Globalization.Invariant" Value="true" />
</ItemGroup>
```

The [link](https://github.com/safern/runtime/blob/c592559b25de2bcc2ddf8adcb94a9a37fe1d10ce/docs/design/features/globalization-invariant-mode.md) should have more details.

**Comment by dmeytin** [comment] 2020-06-16 19:00
Hey Tarek,
I've tried PropertyGroup and ItemGroup as you suggested, but the results are persistent. 
Do you have any idea why?

**Comment by tarekgh** [comment] 2020-06-16 19:11
@dmeytin if you can share a sample project I can try that will be helpful to tell. 

> the results are persistent.

When do you say that you mean the perf didn't change at all? or you mean something else?

**Comment by dmeytin** [comment] 2020-06-17 11:12
The issue was solved by setting environment variable DOTNET_SYSTEM_GLOBALIZATION_INVARIANT to 1

**Comment by tarekgh** [comment] 2020-06-17 17:10
Thanks for the update @dmeytin. I want to point that enabling the globalization invariant mode will cause losing globalization support. So it will depend on your scenario if this is the right thing to do here. But anyway, in .NET 5.0 we are going to look at your scenario (ordinal with ignoring casing) and try to optimize it.

**Comment by mjsabby** [comment] 2020-08-17 01:55
While this issue talks about Linux, I just wanted to note that one of reasons for regression is the fact that OrdinalIgnoreCase for NLS has a call to `kernel32!FindStringOrdinal` in the jitted code vs in the ICU case, the call is to `GlobalizationNative_IndexOfOrdinalIgnoreCase` which has an indirect call ICU's toupper functions. So, there is no Control Flow Guard impact in the NLS case vs. the ICU one has CFG impact.

It's not the most pressing issue in this situation (since it impacts Linux too) but just something to consider as we figure out a fix for this.

**Comment by tarekgh** [comment] 2020-08-17 16:20
https://github.com/dotnet/runtime/pull/40910

**Comment by tarekgh** [comment] 2020-08-18 18:32
Closing this per https://github.com/dotnet/runtime/pull/40962 & https://github.com/dotnet/runtime/pull/40910

@dmeytin would be good idea if you can migrate to 5.0 without using Globalization Invariant mode. That will give better functionality and the performance should be acceptable too.

**Closed by tarekgh** 2020-08-18 18:32 UTC
Labels: area-System.Globalization, tenet-performance
