### ISSUE TITLE
ArgumentNullException in System.Text.Json.Serialization.Metadata.JsonTypeInfo

### ISSUE THREAD

**Issue by JakenVeina** [dotnet/runtime#58690] opened 2021-09-05 06:10 UTC
### Description

I am receiving an `ArgumentNullException` from `JsonSerializer.Serialize<T>(Utf8JsonWriter, T value, JsonSerializerOptions options)` that appears to be the result of a faulty null-check-override within `JsonTypeInfo`.

https://github.com/dotnet/runtime/blob/804a933e2b699e10391e7f8b4ccbbbfad41bfefc/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs#L526

```
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.OrdinalIgnoreCaseComparer.GetHashCode(String obj)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.ParameterLookupKey.GetHashCode()
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.InitializeConstructorParameters(ConstructorInfo constructorInfo)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo..ctor(Type type, JsonConverter converter, Type runtimeType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.<RootBuiltInConvertersAndTypeInfoCreator>g__CreateJsonTypeInfo|107_0(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.GetTypeInfo(Type runtimeType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](Utf8JsonWriter writer, TValue& value, Type runtimeType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](Utf8JsonWriter writer, TValue value, JsonSerializerOptions options)
   at Modix.Host.EntryPoint.EndpointWriteOnlyJsonConverter.Write(Utf8JsonWriter writer, Endpoint value, JsonSerializerOptions options) in D:\Projects\JakenVeina\MODiX\MODiX.Host\EntryPoint.cs:line 90
```

The `null` value in question is coming from `System.Reflection.ParameterInfo.Name`, retrieved from the constructor of `System.Runtime.CompilerServices.NullableContextAttribute`.

The `NullableContextAttribute` instance is coming from `Microsoft.AspNetCore.Http.Endpoint` which is being passed to `Microsoft.Extensions.Logging.ILogger.Log` calls as `TState state`.

`NullableContextAttribute` is an `internal` and compiler-generated type, so it's been proving difficult to implement a workaround where I just skip or customize serialization of the type. It also strikes me as a slight design defect that all this work is being done to analyze this type for deserialization, when I am only attempting to serialize it, and have no intention of ever deserializing it.

### Configuration

.NET SDK 6.0.100-preview.7.21379.14
System.Text.Json 6.0.0-preview.7.21377.19

**Comment by eiriktsarpalis** [comment] 2021-09-07 13:03
Hi @JakenVeina, would it be possible to provide a minimal app that reproduces the issue? Thanks.

**Comment by JakenVeina** [comment] 2021-09-08 01:57
It looks like a "minimal" reproduction might not be possible. I have replicated the scenario in a simple console program, using the same runtime and package versions, and the exception does not occur. I.E...
```cs
JsonSerializer.Serialize(writer, value, options);
```
...where `value` is a `NullableContextAttribute` object, which, when reflected upon, produces a `ParameterInfo` object with a `Name` value of `null`. This line throws in the full solution, but not in the console program. The `options` object is not meaningfully different between the two. I noticed there's a decent amount of `static` caching of `JsonTypeInfo` objects going on, so perhaps that's somehow the culprit?

I will attempt to clone my full application and trim as much out of it as possible, without affecting the exception that throws.

**Comment by JakenVeina** [comment] 2021-09-09 03:18
Here we go: https://github.com/JakenVeina/DotnetRuntimeIssue58690

I identified the issue with reproducing it locally: I was inadvertently calling `.Serialize<Attribute>()` instead of `.Serialize()`, resulting in the library reflecting upon `System.Attribute` instead of `System.Runtime.CompilerServices.NullableContextAttribute`.

**Comment by eiriktsarpalis** [comment] 2021-09-10 14:35
I can reproduce. Minimal reproduction:
```csharp
using System;
using System.Reflection;
using System.Text.Json;

Type type = Assembly.GetExecutingAssembly().GetType("System.Runtime.CompilerServices.NullableContextAttribute")!;
object value = Activator.CreateInstance(type, (byte)0)!;
JsonSerializer.Serialize(value);

// Force generation of a NullableContextAttribute in this assembly
static string? MethodWithNullableAnnotations() => throw new NotImplementedException();
```
Throws
```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'obj')
   at System.OrdinalIgnoreCaseComparer.GetHashCode(String obj)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.ParameterLookupKey.GetHashCode()
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.InitializeConstructorParameters(JsonParameterInfoValues[] jsonParameters)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo..ctor(Type type, JsonConverter converter, Type runtimeType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.<InitializeForReflectionSerializer>g__CreateJsonTypeInfo|112_0(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetClassFromContextOrCreate(Type type)
   at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type type)
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type runtimeType)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
```
I did not deduce the root cause -- for some reason attempting to replicate the implementation of `NullableContextAttribute` in source resulted in a different type of failure much later in the implementation. We should still investigate and at least attempt to fail more gracefully if this scenario cannot be supported.

This seems like a very niche use case. Moving to 7.0.0.

**Comment by eiriktsarpalis** [comment] 2022-04-18 15:48
Moving to Future, as we won't have time to work on this.

**Comment by eiriktsarpalis** [comment] 2022-08-01 21:11
Root cause appears to be IL https://github.com/dotnet/runtime/issues/73188#issuecomment-1201720842 containing parameters with stripped names. Given that the linker can trim parameter names to save size we might want to add detection logic for `ParameterInfo` with null `Name` properties (and either fail gracefully or use a placeholder name like ILSpy is doing).

**Closed** 2022-08-03 14:04 UTC
Labels: bug, area-System.Text.Json, linkable-framework, Priority:3, in-pr
