### ISSUE TITLE
[6.0.100-alpha.1.21068.2] System.InvalidOperationException: Enumeration already finished error in giphy app

### ISSUE THREAD

**Issue by jiangzeng01** [dotnet/runtime#47146] opened 2021-01-19 05:41 UTC
**Application Name:**  Giphy global tool app
**OS:** Windows 10 RS5
**CPU:** X64
**.NET Build Number:** 6.0.100-alpha.1.21068.2
**DevDiv bug:** [https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1267242](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1267242)

 **Verify Scenarios:**
1). Windows 10 RS5 X64 + .NET Core SDK build 6.0.100-alpha.1.21068.2: Fail
2). Windows 10 RS5 X64 + .NET Core SDK build 6.0.100-alpha.1.21066.3: Fail
3). Windows 10 RS5 X64 + .NET Core SDK build 6.0.100-alpha.1.21064.27: Pass
4). Windows 10 RS5 X64 + .NET Core SDK build 5.0.101 : Pass
5). Windows 10 RS5 X64 + .NET Core SDK build 3.1.300  Pass

**Repo Machine Environment Info:**
C:\h\w\ADA609AF\p>dotnet --info 
.NET SDK (reflecting any global.json):
 Version:   6.0.100-alpha.1.21068.2
 Commit:    985f46e793

**Runtime Environment:**
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-alpha.1.21068.2\

**Host (useful for support):**
  Version: 6.0.0-alpha.1.21066.5
  Commit:  c7fda3b94a

**.NET SDKs installed:**
  6.0.100-alpha.1.21068.2 [C:\Program Files\dotnet\sdk]

**.NET runtimes installed:**
  Microsoft.AspNetCore.App 6.0.0-alpha.1.21067.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-alpha.1.21066.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0-alpha.1.21066.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
 
**Minimal Sample Code to Repro :** 
```c#
HttpWebRequest request = WebRequest.Create("https://www.bing.com/") as HttpWebRequest;
HttpWebResponse response = (HttpWebResponse)request.GetResponse();
Console.WriteLine(response.ContentEncoding);
```
In .net5, response.ContentEncoding returns string.empty
In .net6, System.InvalidOperationException thrown : 

**Repro steps for giphy**
1) On CMD, install app with : dotnet tool install -g GiphyCli
2) Run this command : giphy cheeseburger

**Expected Result:**
It should search files

**Actual Result:**
```
Unhandled exception. System.ApplicationException: Error retrieving response. Check inner details for more info.
 ---> System.InvalidOperationException: Enumeration already finished.
   at System.SZGenericArrayEnumerator`1.get_Current()
   at System.Net.HttpWebResponse.GetHeaderValueAsString(IEnumerable`1 values)
   at System.Net.HttpWebResponse.get_ContentEncoding()
   at RestSharp.Http.ExtractResponseData(HttpWebResponse webResponse)
   at RestSharp.Http.ExecuteRequest(String httpMethod, Action`1 prepareRequest)
   --- End of inner exception stack trace ---
   at GiphyCli.GiphyApi.Execute[T](RestRequest request) in /home/runner/work/giphy-cli/giphy-cli/src/GiphyApi.cs:line 55
   at GiphyCli.GiphyApi.Search(String search) in /home/runner/work/giphy-cli/giphy-cli/src/GiphyApi.cs:line 27
   at GiphyCli.Program.OnExecute() in /home/runner/work/giphy-cli/giphy-cli/src/Program.cs:line 40
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](IConsole console, String[] args)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](String[] args)
   at GiphyCli.Program.Main(String[] args) in /home/runner/work/giphy-cli/giphy-cli/src/Program.cs:line 18
```

**Findings :**
Error comes from a RestSharp library used by giphy.
In this file : [RestSharp/Http.cs](https://github.com/restsharp/RestSharp/blob/dev/src/RestSharp/Http.cs)
Inside ExtractResponseData method, when HttpResponse constructor is initializing,  webResponse.ContentEncoding gives this error.

**Minimal Sample Code to Repro :** 
```c#
HttpWebRequest request = WebRequest.Create("https://www.bing.com/") as HttpWebRequest;
HttpWebResponse response = (HttpWebResponse)request.GetResponse();
Console.WriteLine(response.ContentEncoding);
```
In .net5, response.ContentEncoding returns string.empty
In .net6, System.InvalidOperationException thrown : 
```
Unhandled exception. System.InvalidOperationException: Enumeration already finished.
   at System.SZGenericArrayEnumerator`1.get_Current()
   at System.Net.HttpWebResponse.GetHeaderValueAsString(IEnumerable`1 values)
   at System.Net.HttpWebResponse.get_ContentEncoding()
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\v-altunc\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 13
```
@dotnet-actwx-bot

**Comment by jiangzeng01** [comment] 2021-01-19 05:45
buildnotification app also failed with the same issue "Enumeration already finished"

**Comment by karelz** [comment] 2021-01-19 15:52
@stephentoub could it be regression from your recent PR #47010?

**Comment by geoffkizer** [comment] 2021-01-19 17:19
Yeah, it looks like a regression caused by #47010.

I am concerned that we don't have a test for this. Is this issue specific to ContentEncoding? If so why? If not, that means we don't have tests for any empty collection properties like this??

**Comment by stephentoub** [comment] 2021-01-19 17:20
> could it be regression from your recent PR #47010?

Sort of, in that it's the cause of the symptom but not the cause of the problem.

This code in HttpWebResponse:
https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/System.Net.Requests/src/System/Net/HttpWebResponse.cs#L390-L394
is assuming that enumerator.MoveNext will always return true and then proceeds to call Current without checking that's actually the case... with the supplied repro, on .NET 5, in a debug build it asserts, but in a release build it doesn't.

My change in #47010 now causes such an erroneous Current access to throw.  The actual problem, though, is that the enumerable being passed in here:
https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/System.Net.Requests/src/System/Net/HttpWebResponse.cs#L128
is empty and the comment at:
https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/System.Net.Requests/src/System/Net/HttpWebResponse.cs#L389
is simply wrong.  Previously that Current access was returning null (also btw violating the stated contract of the method), and ContentEncoding would end up returning null (not empty string as stated in the issue description).

The proper fix is in HttpWebRequest, to fix GetHeaderValueAsString to behave correctly.

**Comment by geoffkizer** [comment] 2021-01-19 17:26
Doesn't this mean that the IEnumerable being returned from `_httpResponseMessage.Content.Headers.ContentEncoding` is and was broken? i.e. it's returning a single `null`? This seems super weird.

**Comment by stephentoub** [comment] 2021-01-19 18:04
> Doesn't this mean that the IEnumerable being returned from _httpResponseMessage.Content.Headers.ContentEncoding is and was broken? i.e. it's returning a single null? This seems super weird.

No, the enumerable being returned from ContentEncoding was and is an empty enumerable.  HttpWebResponse was then enumerating it without regard for the return value of its MoveNext.

**Comment by geoffkizer** [comment] 2021-01-19 18:09
> with the supplied repro, on .NET 5, in a debug build it asserts

Wow. That's bad.

**Comment by stephentoub** [comment] 2021-01-19 18:11
(To be clear, I meant in a debug build of the runtime, not a debug build of the app)

**Comment by geoffkizer** [comment] 2021-01-19 18:13
I get that -- I'm just kinda baffled that we have no test code that ever hit this assert.

**Comment by stephentoub** [comment] 2021-01-19 18:13
Yup.  Our test coverage for HttpWebRequest/Response is not good.

**Closed** 2021-01-20 03:54 UTC
Labels: area-System.Net, in pr

**Comment by jiangzeng01** [comment] 2021-01-25 10:17
Verified passed with 6.0.100-preview.1.21074.2
