### ISSUE TITLE
Unlimited SSL connections for the site with invalid certificate

### ISSUE THREAD

**Issue by qrknx** [dotnet/runtime#47726] opened 2021-02-01 22:20 UTC
### Description

```csharp
var client = new HttpClient();
await client.GetAsync("https://v3bl.goszakup.gov.kz");
```
This resource has invalid SSL certificate. **On Windows this request works as expected. It throws:**
```
Inner Exception 1:
AuthenticationException: The remote certificate is invalid according to the validation procedure.
```
**But on Linux I get a lot of connections and their number is increased approximately by one per second**:
```
> netstat -anp | grep 15216
...
tcp    0   0 92.42.15.118:36794   195.12.123.41:443       ESTABLISHED 15216/Project   <-- such connections are spawning
tcp    0   0 92.42.15.118:36622   195.12.123.41:443       ESTABLISHED 15216/Project
tcp   58   0 92.42.15.118:57774   89.218.65.137:443       CLOSE_WAIT  15216/Project   <-- "root" request
tcp    0   0 92.42.15.118:36592   195.12.123.41:443       ESTABLISHED 15216/Project
tcp    0   0 92.42.15.118:36638   195.12.123.41:443       ESTABLISHED 15216/Project
...
```
```
> netstat -anp | grep 15216 | wc -l
132
```
And after about ten minutes:
```
> netstat -anp | grep 15216 | wc -l
885
```
I expect to see similar exception to one that is thrown on Windows. I also tested this issue (some time ago though) on .NET5 and got a StackOverflow exception there.

### Configuration

.NET: .NET Core SDK (3.1.101) .
OS:
```
> cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)
```

### Other information

The problem occurs during handshake procedure. I analyzed dump and saw that threads are waiting infinitely during building certificate chain. Each thread tries to find the end of the chain but in fact starts new similar thread instead and waits when it finishes. I haven't found the exact place where is an error.

**Comment by vcsjones** [comment] 2021-02-01 22:47
This appears to be a duplicate of https://github.com/dotnet/runtime/issues/45010.

**Comment by karelz** [comment] 2021-02-16 20:52
Duplicate of #45010

**Closed by karelz** 2021-02-16 20:52 UTC
Labels: area-System.Net, untriaged
