### ISSUE TITLE
Access Violation starting with .NET 8.0.0 when debugging console application with Visual Studio on Windows x64

### ISSUE THREAD

**Issue by kpreisser** [dotnet/runtime#96322] opened 2023-12-26 18:44 UTC
### Description

Hi, I noticed that after upgrading from .NET 7.0.14 to **8.0.0**, debugging the following simple console application on Windows x64 with Visual Studio 17.8.3 causes an access violation, when setting a break point at the `client.Connect(...)` line, and then stepping over with F10.

However, this seems to happen only when debugging, so maybe it's a debugger-related issue only.

### Reproduction Steps

Create the following two files:
- `TestProject.csproj`
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
```
- `Program.cs`
```cs
using System.Net.Sockets;
using System.Threading;

class Program
{
    private static readonly string serverName = "localhost";
    private static readonly int serverPort = 12345;

    private static long x;
    private static long y;

    static void Main()
    {
        var updateConsoleThread = new Thread(() =>
        {
            long localX = x;
            long localY = y;
        });

        updateConsoleThread.Start();

        var senderThread = new Thread(() => RunSenderThread());
        senderThread.Start();

        senderThread.Join();
        updateConsoleThread.Join();
    }

    private static void RunSenderThread()
    {
        using var client = new TcpClient();

        try
        {
            client.Connect(serverName, serverPort);
        }
        catch (SocketException)
        {
            // Ignore
        }
    }
}
```
- Open the project in **Visual Studio 2022 Version 17.8.3**.
- Set a breakpoint at the `client.Connect(serverName, serverPort);` line:
![grafik](https://github.com/dotnet/runtime/assets/13289184/d2fe4542-c854-4f70-a500-47c4069ded59)
- Start debugging with <kbd>F5</kbd>.
- Notice that the breakpoint is reached normally:
![grafik](https://github.com/dotnet/runtime/assets/13289184/b1608599-afce-45c2-ae70-5515dba121aa)
- Now try to continue by pressing <kbd>F10</kbd> (Step-Over).
- Instead of continuing, an access violation occurs in most of the cases:
```
The program '[6492] TestProject.exe' has exited with code 3221225477 (0xc0000005) 'Access violation'.
```

#### Video

This video shows the reproduction steps I used on an empty Windows Server 2022 VM (Build 20348.2113). Note that the first time running the application, the AV doesn't happen but an unexpected `ArgumentOutOfRangeException` occurs (which suggests an out-of-range port number would be specified). When trying again, the AV occurs.

https://github.com/dotnet/runtime/assets/13289184/be373caa-083a-43af-bed8-36690e916ad5

### Expected behavior

No access violation occurs when pressing <kbd>F10</kbd> after reaching the breakpoint.

### Actual behavior

An access violation occurs in most cases when pressing <kbd>F10</kbd> after reaching the breakpoint.

### Regression?

Yes, this doesn't happen when running with .NET 7.0.14 instead of 8.0.0 (by changing the `TargetFramework` to `net7.0`).

### Configuration

- .NET 8.0.0, .NET SDK 8.0.100
- Visual Studio 17.8.3
- Windows 10 Version 22H2, x64 (Build 19045.3803)

**Comment by Fabi** [comment] 2023-12-27 08:38
Hmm. tested it 10 times (on mac and windows) and I always reach the SocketException

**Comment by kpreisser** [comment] 2023-12-27 12:28
Hi @Fabi,
thanks for your reply! On which hardware platform on Windows did you test this? I could reproduce the AV on two different physical machines (both running Windows 10 Version 22H2 x64 on different Intel Core i5/i7 CPUs).

Additionally, I have now uploaded a video (in the original post) showing the reproduction steps on a clean Windows Server 2022 VM (Build 20348.2113), hope this helps! Thanks!

**Comment by Fabi** [comment] 2023-12-27 18:50
Hmm. Im on latest Win11 & macOS. But I'm already confused by your first port related exception :D

**Comment by tommcdon** [comment] 2023-12-28 01:51
Regression caused by #96339

**Comment by tommcdon** [comment] 2023-12-28 01:55
Hi @kpreisser, would you mind try setting DOTNET_EnableAVX=0?  That would help to confirm my suspicion that the issue is caused by #96339.

**Comment by danmoseley** [comment] 2023-12-28 06:01
@tommcdon  is that the right ID?

**Comment by kpreisser** [comment] 2023-12-28 18:45
Hi @tommcdon,
thanks for your reply!

I tried setting the `DOTNET_EnableAVX` environment variable to `0` (using the Launch Profiles dialog), but it doesn't seem to make any difference; the Access Violation still happens when debugging with the set breakpoint. I modified the code to verify the variable is correctly set:
```cs
    private static void RunSenderThread()
    {
        using var client = new TcpClient();

        try
        {
            Debug.WriteLine($"DOTNET_EnableAVX: '{Environment.GetEnvironmentVariable("DOTNET_EnableAVX")}'");
            client.Connect(serverName, serverPort);
        }
        catch (SocketException)
        {
            // Ignore
        }
    }
```

However, when debugging with the breakpoint and then continuing, the AV still happens:
```
DOTNET_EnableAVX: '0'
'TestProject.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\PrivateAssemblies\Runtime\Microsoft.VisualStudio.Debugger.Runtime.NetCoreApp.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'TestProject.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.0\netstandard.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The program '[19592] TestProject.exe' has exited with code 3221225477 (0xc0000005) 'Access violation'.
```

Thanks!

**Comment by tommcdon** [comment] 2023-12-29 15:40
> @tommcdon is that the right ID?

The ID was indeed incorrect.  The correct PR that caused the regression is #89705

**Comment by tommcdon** [comment] 2023-12-29 15:53
@kpreisser I have found the source of the regression and have a candidate fix: #96352.  The issue is that we are not skipping AMD64 instruction prefixes and are treating the prefix as the opcode when single-stepping over the breakpoint patch table.   I can provide a private 8.0 build for testing purposes.  Please let me know if you would be willing to try it out to help verify the fix.

**Comment by kpreisser** [comment] 2023-12-29 21:44
Hi @tommcdon,
thank you! Yes, I would be willing to try out the 8.0 test build.

**Comment by tommcdon** [comment] 2023-12-30 00:31
Hi @kpreisser!  Please unzip the 5 DLL's from https://github.com/tommcdon/runtime/releases/tag/8.0_x64_stepping_fix and copy them into your .NET 8 install directory (e.g. `%ProgramFiles%\dotnet\shared\Microsoft.NETCore.App\8.0.0`) and back up the original files.  Note .NET Runtime Debugger library signature checks will need to be disabled as well: https://aka.ms/vs/unsigned-dotnet-debugger-lib.

**Comment by kpreisser** [comment] 2023-12-30 18:00
Hi @tommcdon,
thanks for fixing the issue and providing the test binaries! I can confirm that with using these binaries, I'm no longer able to reproduce the access violation.

**Comment by tommcdon** [comment] 2024-01-04 19:16
Servicing approved the 8.0 backport PR, so closing this issue

**Closed by tommcdon** 2024-01-04 19:16 UTC
Labels: os-windows, area-Diagnostics-coreclr
