### ISSUE TITLE
[Test Failure] System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed

### ISSUE THREAD

**Issue by rzikm** [dotnet/runtime#92649] opened 2023-09-26 15:15 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=409004
Build error leg or test failing: System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed
Pull request: https://github.com/dotnet/runtime/pull/92183

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=409004
**Error message validated:** `System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 9/26/2023 3:19:11 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[409004](https://dev.azure.com/dnceng-public/public/_build/results?buildId=409004)|dotnet/runtime|[System.Net.Quic.Tests.QuicStreamTests.ReadsWritesClosedFinish_StreamDisposed](https://dev.azure.com/dnceng-public/public/_build/results?buildId=409004&view=ms.vss-test-web.build-test-results-tab&runId=8888594&resultId=194863)|dotnet/runtime#92183|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|1|

**Comment by ManickaP** [comment] 2023-09-27 08:21
This hasn't happened since I merged my PR.

Duplicate of #92350

**Closed by ManickaP** 2023-09-27 08:21 UTC
Labels: blocking-clean-ci, untriaged, area-System.Net.Quic, Known Build Error
