### ISSUE TITLE
JIT: Assertion failed '(ssize_t)emitCurStackLvl >= argSize'

### ISSUE THREAD

**Issue by amanasifkhalid** [dotnet/runtime#106140] opened 2024-08-08 16:11 UTC
Hit by Antigen on Windows x86. Even after running Trimmer, the repro is quite large: [gist](https://gist.github.com/amanasifkhalid/9c511caa9f715d084a2013aa2e14859a).

cc @dotnet/jit-contrib

**Comment by jakobbotsch** [comment] 2024-08-08 16:17
Here's a small example:
```csharp
// Generated by Fuzzlyn v2.2 on 2024-08-06 15:18:34
// Run on X86 Windows
// Seed: 3643678108487993466-vectort,vector128,vector256,x86aes,x86avx,x86avx2,x86avx512bw,x86avx512bwvl,x86avx512cd,x86avx512cdvl,x86avx512dq,x86avx512dqvl,x86avx512f,x86avx512fvl,x86bmi1,x86bmi2,x86fma,x86lzcnt,x86pclmulqdq,x86popcnt,x86sse,x86sse2,x86sse3,x86sse41,x86sse42,x86ssse3,x86x86base
// Reduced from 55.7 KiB to 0.5 KiB in 00:02:02
// Hits JIT assert in Release:
// Assertion failed '(ssize_t)emitCurStackLvl >= argSize' in 'Program:Main(Fuzzlyn.ExecutionServer.IRuntime)' during 'Generate code' (IL size 32; hash 0xade6b36b; FullOpts)
// 
//     File: D:\a\_work\1\s\src\coreclr\jit\emitxarch.cpp Line: 9937
// 
using System;
using System.Runtime.CompilerServices;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;

public struct S1
{
    public double F0;
    public Vector256<short> F1;
    public S1(bool f3) : this()
    {
    }
}

public class Program
{
    public static void Main()
    {
        S1[][, ] vr0 = new S1[][, ]
        {
            new S1[, ]
            {
                {
                    new S1(false)
                }
            }
        };
    }
}
```

**Comment by JulieLeeMSFT** [comment] 2024-08-09 01:10
@TIHan, PTAL. Assert in Generate Code.

**Comment by TIHan** [comment] 2024-08-12 22:14
Able to reproduce the issue, am looking into it.

**Comment by kunalspathak** [comment] 2024-09-04 22:53
Keeping it assigned to @TIHan because he already has a PR out.

**Comment by JulieLeeMSFT** [comment] 2024-09-09 18:16
Moving to .NET 10 because we need to look into it further. 
Assigning to @BruceForstall because it is related to multidimensional loop.

**Closed** 2024-10-15 05:13 UTC
Labels: arch-x86, os-windows, area-CodeGen-coreclr, blocking-clean-ci-optional, Priority:2, in-pr
