### ISSUE TITLE
[API Proposal]: Improve some reflection types - add not-null DeclaringType properties

### ISSUE THREAD

**Issue by TahirAhmadov** [dotnet/runtime#86987] opened 2023-05-31 23:32 UTC
### Background and motivation

The `MemberInfo.DeclaringType` property is nullable, because `Type`, `FieldInfo`, `MethodInfo` and `ConstructorInfo` inherit from `MemberInfo`. This has a bad effect on `PropertyInfo` and `EventInfo` - for those, `DeclaringType` is never null.

### API Proposal

```csharp
namespace System.Reflection;

public class PropertyInfo : ...
{
  // ...
  public Type DeclaringType => base.DeclaringType!;
}
// ditto for EventInfo
```

### API Usage

```csharp
string Foo(PropertyInfo propertyInfo)
{
  return propertyInfo.DeclaringType.Name; // no NRT warning
}
```

**Comment by koszeggy** [comment] 2023-06-10 10:06
Actually it [can](https://stackoverflow.com/q/35266010/5114784) be `null`.

**Comment by steveharter** [comment] 2023-06-28 14:16
Closing as by design. PropertyInfo\EventInfo.DeclaringType can be `null` in VB or when using [PropertyBuilder ](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.emit.propertybuilder.declaringtype?view=net-7.0#system-reflection-emit-propertybuilder-declaringtype). Basically the property\event belongs to a module, not a class. In C#, however, it is not possible.

**Closed by steveharter** 2023-06-28 14:16 UTC
Labels: api-suggestion, area-System.Reflection, untriaged
