### ISSUE TITLE
Test failure `TestRuntimeEventCounter`: InvalidOperationException

### ISSUE THREAD

**Issue by TIHan** [dotnet/runtime#105503] opened 2024-07-25 17:17 UTC
https://dev.azure.com/dnceng-public/public/_build/results?buildId=754814&view=ms.vss-test-web.build-test-results-tab&runId=19134700&resultId=114627&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

```
BEGIN EXECUTION
/tmp/helix/working/A4A40908/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true runtimecounters.dll ''
Saw cpu-usage
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.Dictionary`2.KeyCollection.Enumerator.MoveNext()
   at RuntimeEventCounterTests.RuntimeCounterListener.Verify()
   at RuntimeEventCounterTests.TestRuntimeEventCounter.TestEntryPoint()
   at __GeneratedMainWrapper.Main()
Expected: 100
Actual: 101
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /cores since 7/25/2024 6:26:35 AM
Test Harness Exitcode is : 1
```

**Comment by ViktorHofer** [comment] 2024-07-25 19:25
Not sure which label is appropriate here but definitely not infra-libraries.

**Comment by jkotas** [comment] 2024-07-25 20:40
Duplicate of #105443

**Closed by jkotas** 2024-07-25 20:40 UTC
Labels: area-Infrastructure-coreclr, untriaged
