### ISSUE TITLE
Scalability of System.Text.Json

### ISSUE THREAD

**Issue by WenningQiu** [dotnet/runtime#97649] opened 2024-01-29 15:55 UTC
My application currently uses NewtonSoft.Json to process large volume of JSON data. I am not satisfied with the processing speed so I am looking for alternative JSON serializers.

What puzzles me is that my application appears to be running slower with System.Text.Json even though System.Text.Json produces good result in my simple performance test (single-thread serialization and deserialization). I was able to reproduce the symptom with a simplified test case.

The test deserializes a collection of JSON strings with different level of parallelism:

```
        [Test]
        public void ActivityRecordParallelPerformance()
        {
            const int count = 1000;

            var jsonData = new List<string>();

            for (var i = 0; i < count; i++)
#pragma warning disable CS0618 // Type or member is obsolete
                jsonData.Add(string.Copy(_activitiesJson));
#pragma warning restore CS0618 // Type or member is obsolete

            // Warm up
            _activitiesJson.FromJson<ActivityRecord[]>().ToJson();
            _activitiesJson.FromJson2<ActivityRecord[]>().ToJson2();

            for (var parallelism = 1; parallelism <= 16; parallelism+=1)
            {
                Console.WriteLine($"*** NewtonSoft.Json (parallelism={parallelism}) ***");
                ParallelExecutor.ForEach(jsonData, parallelism, x => ParallelExecutor.RunTest(() => x.FromJson<ActivityRecord[]>()));

                Console.WriteLine($"*** System.Text.Json (parallelism={parallelism}) ***");
                ParallelExecutor.ForEach(jsonData, parallelism, x => ParallelExecutor.RunTest(() => x.FromJson2<ActivityRecord[]>()));

                Console.WriteLine();
            }
        }
```
```
    public static class ParallelExecutor
    {
        internal static long TotalProcessingTimeMs = 0;
        internal static long JsonDeserializationTimeMs = 0;

        public static void RunTest(Action action)
        {
            var sw = Stopwatch.StartNew();

            action();

            sw.Stop();
            Interlocked.Add(ref JsonDeserializationTimeMs, sw.ElapsedMilliseconds);
        }

        public static void ForEach<T>(IEnumerable<T> source, int degreeOfParallelism, Action<T> action)
        {
            var tasks = new List<Task>();

            TotalProcessingTimeMs = 0;
            JsonDeserializationTimeMs = 0;

            var sw = Stopwatch.StartNew();

            foreach (var item in source)
            {
                var newTask = Task.Run(() => action(item))
                    .ContinueWith(t =>
                    {
                        if (t.IsFaulted)
                        {
                            Console.WriteLine($"An error was encountered during processing: {t.Exception?.Message}");
                        }
                        else if (t.IsCanceled)
                        {
                            Console.WriteLine($"A task was canceled...");
                        }
                    });

                tasks.Add(newTask);

                if (tasks.Count < degreeOfParallelism)
                    continue;

                var completedTask = Task.WhenAny(tasks).Result;
                tasks.Remove(completedTask);
            }

            Task.WhenAll(tasks).Wait();

            sw.Stop();
            TotalProcessingTimeMs = sw.ElapsedMilliseconds;
            
            Console.WriteLine($"Total processing time: {TotalProcessingTimeMs}ms");
            Console.WriteLine($"JSON deserialization time: {JsonDeserializationTimeMs}ms");
        }
    }
```
Below is the test result on my 8-core machine (Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz, 2304 Mhz, 8 Core(s), 16 Logical Processor(s)). We can see that:

- System.Text.json is close to 50% more efficient than NewtonSoft.Json in single-threaded mode (parallelism=1)
- System.Text.json scales poorly compared to NewtonSoft.Json - it only cuts about 24% of the total processing time of single task with 8 tasks.
- With more cores used, System.Text.json is actually out-performed by NewtonSoft.json.

I am curious what might be preventing System.Text.json from scaling. Are there any parameters that I can use to improve its scalability?

```
*** NewtonSoft.Json (parallelism=1) ***
Total processing time: 6960ms
JSON deserialization time: 6332ms
*** System.Text.Json (parallelism=1) ***
Total processing time: 3729ms
JSON deserialization time: 3341ms

*** NewtonSoft.Json (parallelism=2) ***
Total processing time: 3161ms
JSON deserialization time: 5789ms
*** System.Text.Json (parallelism=2) ***
Total processing time: 2348ms
JSON deserialization time: 4153ms

*** NewtonSoft.Json (parallelism=3) ***
Total processing time: 2644ms
JSON deserialization time: 7325ms
*** System.Text.Json (parallelism=3) ***
Total processing time: 2214ms
JSON deserialization time: 6060ms

*** NewtonSoft.Json (parallelism=4) ***
Total processing time: 2576ms
JSON deserialization time: 9726ms
*** System.Text.Json (parallelism=4) ***
Total processing time: 2113ms
JSON deserialization time: 7825ms

*** NewtonSoft.Json (parallelism=5) ***
Total processing time: 2183ms
JSON deserialization time: 10299ms
*** System.Text.Json (parallelism=5) ***
Total processing time: 2659ms
JSON deserialization time: 12593ms

*** NewtonSoft.Json (parallelism=6) ***
Total processing time: 2450ms
JSON deserialization time: 14084ms
*** System.Text.Json (parallelism=6) ***
Total processing time: 2883ms
JSON deserialization time: 16570ms

*** NewtonSoft.Json (parallelism=7) ***
Total processing time: 2618ms
JSON deserialization time: 17660ms
*** System.Text.Json (parallelism=7) ***
Total processing time: 2935ms
JSON deserialization time: 19943ms

*** NewtonSoft.Json (parallelism=8) ***
Total processing time: 2646ms
JSON deserialization time: 20531ms
*** System.Text.Json (parallelism=8) ***
Total processing time: 2833ms
JSON deserialization time: 21960ms

*** NewtonSoft.Json (parallelism=9) ***
Total processing time: 2824ms
JSON deserialization time: 24832ms
*** System.Text.Json (parallelism=9) ***
Total processing time: 3070ms
JSON deserialization time: 26920ms

*** NewtonSoft.Json (parallelism=10) ***
Total processing time: 2708ms
JSON deserialization time: 26423ms
*** System.Text.Json (parallelism=10) ***
Total processing time: 3282ms
JSON deserialization time: 31835ms

*** NewtonSoft.Json (parallelism=11) ***
Total processing time: 2986ms
JSON deserialization time: 32070ms
*** System.Text.Json (parallelism=11) ***
Total processing time: 3332ms
JSON deserialization time: 35854ms

*** NewtonSoft.Json (parallelism=12) ***
Total processing time: 2733ms
JSON deserialization time: 32145ms
*** System.Text.Json (parallelism=12) ***
Total processing time: 3304ms
JSON deserialization time: 38678ms

*** NewtonSoft.Json (parallelism=13) ***
Total processing time: 2758ms
JSON deserialization time: 35007ms
*** System.Text.Json (parallelism=13) ***
Total processing time: 3510ms
JSON deserialization time: 44769ms

*** NewtonSoft.Json (parallelism=14) ***
Total processing time: 2965ms
JSON deserialization time: 40599ms
*** System.Text.Json (parallelism=14) ***
Total processing time: 3233ms
JSON deserialization time: 44248ms

*** NewtonSoft.Json (parallelism=15) ***
Total processing time: 3022ms
JSON deserialization time: 44000ms
*** System.Text.Json (parallelism=15) ***
Total processing time: 3454ms
JSON deserialization time: 50649ms

*** NewtonSoft.Json (parallelism=16) ***
Total processing time: 2942ms
JSON deserialization time: 43776ms
*** System.Text.Json (parallelism=16) ***
Total processing time: 3369ms
JSON deserialization time: 50406ms
```

**Comment by eiriktsarpalis** [comment] 2024-01-29 16:06
The reproduction appears to be missing components, for example the serialization routines being used are not given.

> What puzzles me is that my application appears to be running slower with System.Text.Json even though System.Text.Json produces good result in my simple performance test (single-thread serialization and deserialization).

I would be very surprised if STJ had a perf bottleneck in parallel applications, since it is being used in the [aspnetcore TechEmpower benchmarks](https://github.com/aspnet/Benchmarks?tab=readme-ov-file) -- it is very likely we would have noticed it. It might be caused by issues in the benchmark itself, e.g. because the serialized type does its own synchronization or because of `JsonSerializer` is being invoked.  Obviously, without access to a standalone repro this is pure speculation

**Comment by WenningQiu** [comment] 2024-01-29 16:16
I omitted the logic that is related to my application. Let me try to get a full repro code ready.

**Comment by WenningQiu** [comment] 2024-01-29 22:03
I am attaching the complete repro code. Below is the result from my local run:

```
C:\temp\Repro\bin\Release\net6.0>Repro.exe
*** NewtonSoft.Json (parallelism=1) ***
Total processing time: 4189ms
JSON deserialization time: 3556ms
*** System.Text.Json (parallelism=1) ***
Total processing time: 3101ms
JSON deserialization time: 2489ms

*** NewtonSoft.Json (parallelism=2) ***
Total processing time: 2457ms
JSON deserialization time: 4421ms
*** System.Text.Json (parallelism=2) ***
Total processing time: 2325ms
JSON deserialization time: 3962ms

*** NewtonSoft.Json (parallelism=3) ***
Total processing time: 1856ms
JSON deserialization time: 5033ms
*** System.Text.Json (parallelism=3) ***
Total processing time: 2391ms
JSON deserialization time: 6505ms

*** NewtonSoft.Json (parallelism=4) ***
Total processing time: 1654ms
JSON deserialization time: 6001ms
*** System.Text.Json (parallelism=4) ***
Total processing time: 2077ms
JSON deserialization time: 7759ms

*** NewtonSoft.Json (parallelism=5) ***
Total processing time: 1557ms
JSON deserialization time: 7214ms
*** System.Text.Json (parallelism=5) ***
Total processing time: 2023ms
JSON deserialization time: 9499ms

*** NewtonSoft.Json (parallelism=6) ***
Total processing time: 1443ms
JSON deserialization time: 8085ms
*** System.Text.Json (parallelism=6) ***
Total processing time: 2175ms
JSON deserialization time: 12321ms

*** NewtonSoft.Json (parallelism=7) ***
Total processing time: 1744ms
JSON deserialization time: 11661ms
*** System.Text.Json (parallelism=7) ***
Total processing time: 2310ms
JSON deserialization time: 15574ms

*** NewtonSoft.Json (parallelism=8) ***
Total processing time: 1684ms
JSON deserialization time: 12868ms
*** System.Text.Json (parallelism=8) ***
Total processing time: 2224ms
JSON deserialization time: 17081ms

*** NewtonSoft.Json (parallelism=9) ***
Total processing time: 1699ms
JSON deserialization time: 14714ms
*** System.Text.Json (parallelism=9) ***
Total processing time: 2258ms
JSON deserialization time: 19655ms

*** NewtonSoft.Json (parallelism=10) ***
Total processing time: 2105ms
JSON deserialization time: 20376ms
*** System.Text.Json (parallelism=10) ***
Total processing time: 2467ms
JSON deserialization time: 24027ms

*** NewtonSoft.Json (parallelism=11) ***
Total processing time: 2071ms
JSON deserialization time: 22118ms
*** System.Text.Json (parallelism=11) ***
Total processing time: 2392ms
JSON deserialization time: 25694ms

*** NewtonSoft.Json (parallelism=12) ***
Total processing time: 1923ms
JSON deserialization time: 22294ms
*** System.Text.Json (parallelism=12) ***
Total processing time: 2059ms
JSON deserialization time: 23963ms

*** NewtonSoft.Json (parallelism=13) ***
Total processing time: 1948ms
JSON deserialization time: 24595ms
*** System.Text.Json (parallelism=13) ***
Total processing time: 2093ms
JSON deserialization time: 26507ms

*** NewtonSoft.Json (parallelism=14) ***
Total processing time: 1944ms
JSON deserialization time: 26466ms
*** System.Text.Json (parallelism=14) ***
Total processing time: 2120ms
JSON deserialization time: 28890ms

*** NewtonSoft.Json (parallelism=15) ***
Total processing time: 1987ms
JSON deserialization time: 28871ms
*** System.Text.Json (parallelism=15) ***
Total processing time: 2257ms
JSON deserialization time: 32934ms

*** NewtonSoft.Json (parallelism=16) ***
Total processing time: 1880ms
JSON deserialization time: 28944ms
*** System.Text.Json (parallelism=16) ***
Total processing time: 2286ms
JSON deserialization time: 35089ms
```

**Comment by WenningQiu** [comment] 2024-01-29 22:12
Not sure why the previous upload was not successful. Here it is: [Repro.tar.gz](https://github.com/dotnet/runtime/files/14090264/Repro.tar.gz)

**Comment by eiriktsarpalis** [comment] 2024-01-29 23:23
I would second @huoyaoyuan's comment that the benchmarking harness looks problematic, for example it seems to be calling `Task.WhenAny` every single time the degree of parallelism is reached, which adds coordination overhead. When the degree of parallelism exceeds the CPU core count then each `StopWatch` isn't necessarily measuring what you think it is.

I adapted your code to use BenchmarkDotNet instead, which is a harness specifically designed to measure workloads like the ones you're evaluating:
```C#
public class Benchmarks
{
    private readonly string _jsonData = File.ReadAllText("activities.json"); 

    [Benchmark]
    public ActivityRecord[] Newtonsoft() => _jsonData.FromJson<ActivityRecord[]>();
    
    [Benchmark]
    public ActivityRecord[] SystemTextJson() => _jsonData.FromJson2<ActivityRecord[]>();
}
```

Which when run gave me the following results:

| Method                 | Mean     | Error     | StdDev    |
|----------------------- |---------:|----------:|----------:|
| Newtonsoft             | 4.768 ms | 0.0945 ms | 0.2603 ms |
| SystemTextJson         | 3.939 ms | 0.1045 ms | 0.3033 ms |

**Comment by huoyaoyuan** [comment] 2024-01-30 03:31
For scalability, it needs a method to measure the performance under different degree of parallelism. The result can be unstable comparing to single-threaded. Can BDN finely support that?

**Comment by zlatanov** [comment] 2024-01-30 11:16
There are a few things being deserialized differently when using STJ vs Newtonsoft. The repro should be investigated further to see why there is such a big disparity between the results.

However, one thing I noticed is that deserializing `Dictionary<string, object>` in STJ is always slower.
Here is a simple benchmark showing this:

```c#
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using System.Collections.Generic;

public class Program
{
    static void Main(string[] args)
    {
        BenchmarkSwitcher.FromAssembly(typeof(Program).Assembly).Run(args);
    }

    private const string JSON =
"""
        {
          "ProcessingCVP": "True",
          "fwNetVer": "4.8",
          "FRAMEWORK_PRODUCTNAME": "ACPxOrder",
          "fwRelease": "23.3"
        }
""";


    [Benchmark]
    public void NJ()
    {
        Newtonsoft.Json.JsonConvert.DeserializeObject<Dictionary<string, object>>(JSON);
    }

    [Benchmark]
    public void STJ()
    {
        System.Text.Json.JsonSerializer.Deserialize<Dictionary<string, object>>(JSON);
    }
}
```

```
BenchmarkDotNet v0.13.10, Windows 11 (10.0.22621.3085/22H2/2022Update/SunValley2)
11th Gen Intel Core i7-11700 2.50GHz, 1 CPU, 16 logical and 8 physical cores
.NET SDK 8.0.200-preview.23624.5
  [Host]     : .NET 8.0.1 (8.0.123.58001), X64 RyuJIT AVX2
  DefaultJob : .NET 8.0.1 (8.0.123.58001), X64 RyuJIT AVX2

```
| Method | Mean     | Error    | StdDev   |
|------- |---------:|---------:|---------:|
| NJ     | 908.1 ns | 17.74 ns | 26.55 ns |
| STJ    | 934.4 ns | 18.15 ns | 20.18 ns |

**Comment by vonzshik** [comment] 2024-01-30 12:29
Looking at the repro, it seems the main reason for the scalability regression is that STJ allocates quite a bit more compared to NewtonsoftJson. For example, deserializing 1000 objects with NewtonsoftJson allocates about 1.3GB while STJ allocates 2.2GB.

![image](https://github.com/dotnet/runtime/assets/14861420/0802302e-6a9c-469c-8977-d123c82abe27)

![image](https://github.com/dotnet/runtime/assets/14861420/b8c08bc0-dd40-46e7-afe0-34d5289fe4e3)

Most of these allocations seems to be from here:

https://github.com/dotnet/runtime/blob/28ad7e970c61896ab210e2be605efb76a7bdad50/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs#L461-L466

I'm not an expert in STJ so can't say for certain if this path can be avoided.

**Comment by WenningQiu** [comment] 2024-01-30 13:55
> I would second @huoyaoyuan's comment that the benchmarking harness looks problematic, for example it seems to be calling `Task.WhenAny` every single time the degree of parallelism is reached, which adds coordination overhead. When the degree of parallelism exceeds the CPU core count then each `StopWatch` isn't necessarily measuring what you think it is.
> 
> I adapted your code to use BenchmarkDotNet instead, which is a harness specifically designed to measure workloads like the ones you're evaluating:
> 
> ```cs
> public class Benchmarks
> {
>     private readonly string _jsonData = File.ReadAllText("activities.json"); 
> 
>     [Benchmark]
>     public ActivityRecord[] Newtonsoft() => _jsonData.FromJson<ActivityRecord[]>();
>     
>     [Benchmark]
>     public ActivityRecord[] SystemTextJson() => _jsonData.FromJson2<ActivityRecord[]>();
> }
> ```
> 
> Which when run gave me the following results:
> 
> Method	Mean	Error	StdDev
> Newtonsoft	4.768 ms	0.0945 ms	0.2603 ms
> SystemTextJson	3.939 ms	0.1045 ms	0.3033 ms

Thanks @eiriktsarpalis, BDN is a great tool for benchmarking; but it just measures single-thread performance in the example that you provided, right?

I tweaked Repro a bit that probably demos the scalability bottleneck in a more straight-forward way. I made it only run STJ deserialization at parallelism level of 8, but it only take a little over one CPU on my 8-core machine.

![image](https://github.com/dotnet/runtime/assets/4291622/bd853168-5959-424b-8056-ff9a009eaa35)

![image](https://github.com/dotnet/runtime/assets/4291622/4449f5a8-a294-42c7-aa1d-4911fc9e6ec0)

**Comment by WenningQiu** [comment] 2024-01-30 16:04
@eiriktsarpalis @zlatanov, thanks for identifying the bottleneck. With your suggested changes, STJ does beat NewtonSoft consistently. 

However, CPU usage still does not show significant improvement (the CPU usage below is with 8 tasks). I expect JSON deserialization to be CPU intensive and the CPU usage to be higher. (NewtonSoft.Json behaves the same way) 

![image](https://github.com/dotnet/runtime/assets/4291622/dd35c941-855b-4482-a018-ec8dbdc8edc9)

**Comment by eiriktsarpalis** [comment] 2024-01-30 16:17
I think this is due to aforementioned issues in the parallelism harness (e.g. the multiple `Task.WhenAny`). I would recommend using `Parallel.Foreach` instead which has been designed for this type of workload.

**Comment by WenningQiu** [comment] 2024-01-30 16:29
It turns out that the ConcurrentDictionary storage used by AmbientData is a major bottleneck. I see improved CPU usage and much better scalability with ConcurrentDictionary replaced by a plain dictionary. There should be no contention on individual AmbientData objects during deserialization. It probably has to do with the implementation of ConcurrentDictionary. 

![image](https://github.com/dotnet/runtime/assets/4291622/e1f45daf-aaf0-4b61-9067-ff0fd901368a)


```
*** NewtonSoft.Json (parallelism=1) ***
Total processing time: 3989ms
JSON deserialization time: 3382ms
*** System.Text.Json (parallelism=1) ***
Total processing time: 2025ms
JSON deserialization time: 1357ms

*** NewtonSoft.Json (parallelism=2) ***
Total processing time: 2107ms
JSON deserialization time: 3512ms
*** System.Text.Json (parallelism=2) ***
Total processing time: 1145ms
JSON deserialization time: 1588ms

*** NewtonSoft.Json (parallelism=3) ***
Total processing time: 1543ms
JSON deserialization time: 3968ms
*** System.Text.Json (parallelism=3) ***
Total processing time: 1031ms
JSON deserialization time: 2348ms

*** NewtonSoft.Json (parallelism=4) ***
Total processing time: 1316ms
JSON deserialization time: 4698ms
*** System.Text.Json (parallelism=4) ***
Total processing time: 893ms
JSON deserialization time: 2825ms

*** NewtonSoft.Json (parallelism=5) ***
Total processing time: 1211ms
JSON deserialization time: 5507ms
*** System.Text.Json (parallelism=5) ***
Total processing time: 873ms
JSON deserialization time: 3632ms

*** NewtonSoft.Json (parallelism=6) ***
Total processing time: 1226ms
JSON deserialization time: 6858ms
*** System.Text.Json (parallelism=6) ***
Total processing time: 813ms
JSON deserialization time: 4135ms

*** NewtonSoft.Json (parallelism=7) ***
Total processing time: 1237ms
JSON deserialization time: 8119ms
*** System.Text.Json (parallelism=7) ***
Total processing time: 867ms
JSON deserialization time: 5327ms

*** NewtonSoft.Json (parallelism=8) ***
Total processing time: 1388ms
JSON deserialization time: 10557ms
*** System.Text.Json (parallelism=8) ***
Total processing time: 782ms
JSON deserialization time: 5492ms

*** NewtonSoft.Json (parallelism=9) ***
Total processing time: 1294ms
JSON deserialization time: 11069ms
*** System.Text.Json (parallelism=9) ***
Total processing time: 821ms
JSON deserialization time: 6621ms

*** NewtonSoft.Json (parallelism=10) ***
Total processing time: 1263ms
JSON deserialization time: 12020ms
*** System.Text.Json (parallelism=10) ***
Total processing time: 868ms
JSON deserialization time: 7859ms

*** NewtonSoft.Json (parallelism=11) ***
Total processing time: 1357ms
JSON deserialization time: 14328ms
*** System.Text.Json (parallelism=11) ***
Total processing time: 771ms
JSON deserialization time: 7888ms

*** NewtonSoft.Json (parallelism=12) ***
Total processing time: 1604ms
JSON deserialization time: 18609ms
*** System.Text.Json (parallelism=12) ***
Total processing time: 774ms
JSON deserialization time: 8710ms

*** NewtonSoft.Json (parallelism=13) ***
Total processing time: 1759ms
JSON deserialization time: 22039ms
*** System.Text.Json (parallelism=13) ***
Total processing time: 802ms
JSON deserialization time: 9802ms

*** NewtonSoft.Json (parallelism=14) ***
Total processing time: 1471ms
JSON deserialization time: 19930ms
*** System.Text.Json (parallelism=14) ***
Total processing time: 823ms
JSON deserialization time: 10939ms

*** NewtonSoft.Json (parallelism=15) ***
Total processing time: 1594ms
JSON deserialization time: 22894ms
*** System.Text.Json (parallelism=15) ***
Total processing time: 805ms
JSON deserialization time: 11218ms

*** NewtonSoft.Json (parallelism=16) ***
Total processing time: 1605ms
JSON deserialization time: 24468ms
*** System.Text.Json (parallelism=16) ***
Total processing time: 796ms
JSON deserialization time: 11837ms
```

**Comment by eiriktsarpalis** [comment] 2024-01-30 16:31
Yep. Generally speaking don't use concurrent collections in your DTOs if you care about serialization performance.

**Comment by eiriktsarpalis** [comment] 2024-01-30 16:31
Closing as asnwered.

**Closed by eiriktsarpalis** 2024-01-30 16:31 UTC
Labels: area-System.Text.Json, untriaged
