### ISSUE TITLE
Private enumeration type can not be recognized when converted to dynamic

### ISSUE THREAD

**Issue by anranruye** [dotnet/runtime#79045] opened 2022-11-30 16:29 UTC
### Description

Consider that we want to build a common method to perform `|` (bitwise or) operation for any enumeration type.
The simplest way could be converting the enum value to `dynamic`:
```C#
    class HelperClass
    {
        // notice that the constraint here doesn't help to allow bitwise operator, still need to use dynamic keyword
        public static T BitwiseOr<T>(T a, T b) where T : Enum
        {
            return (dynamic)a | (dynamic)b;
        }
    }
```
This works well when the enum type is visible for `HelperClass`, but if the enum tupe is private, then the dynamic bitwise operation fails.
```C#
internal class Program
    {
        public static void Main(string[] args)
        {
            MyEnum1 a1 = MyEnum1.A;
            MyEnum1 b1 = MyEnum1.B;
            MyEnum2 a2 = MyEnum2.A;
            MyEnum2 b2 = MyEnum2.B;
            HelperClass.PrintType<MyEnum1>();
            HelperClass.PrintType<MyEnum2>(); // can get the full name of MyEnum2 type
            Console.WriteLine(HelperClass.BitwiseOr(a1, b1)); // ok
            Console.WriteLine(HelperClass.BitwiseOr(a2, b2)); // failed
        }

        public enum MyEnum1 : int
        {
            A = 1,
            B = 2,
            C = 4,
        }

        enum MyEnum2 : int
        {
            A = 1,
            B = 2,
            C = 4,
        }
    }

    class HelperClass
    {
        public static T BitwiseOr<T>(T a, T b) where T : Enum
        {
            return (dynamic)a | (dynamic)b;
        }

        public static void PrintType<T>()
        {
            Console.WriteLine(typeof(T));
        }
    }
```

### Reproduction Steps

run the code above

### Expected behavior

no excetion throwed

### Actual behavior

```
Unhandled exception. Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Operator '|' cannot be applied to operands of type 'System.Enum' and 'System.Enum'
```

### Known Workarounds

use lambda expression to dynamiclly build a method for each enum type. This method converts the enum values to underlying numeric type, do bitwise operation, then converts the numeric value back to enum value.

This approach is complex and need advanced skills for the developer to implement.

### Configuration

.NET 7
Windows 11
x64
I don't think so

**Comment by cston** [comment] 2022-12-16 23:25
@anranruye, thanks for reporting this issue and for providing a clear repro.

It looks like this is existing behavior (rather than a regression) since the behavior is the same with .NET Framework 4.7.2.

Unfortunately, the Microsoft.CSharp library is effectively archived, and we are only taking changes that address significant bugs or regressions, or changes needed to continue shipping - see [README.md](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.CSharp/README.md).

**Comment by anranruye** [comment] 2022-12-22 18:13
@cston then how about considering `Enum` type implicitly as `IBitwiseOperators<T, T, T>`? which makes `where T : Enum` or `where T : IBitwiseOperators<T, T, T>` help in this scenario.

**Comment by cston** [comment] 2024-07-29 13:15
Closing since the library is effectively archived and this is not a regression.

**Closed by cston** 2024-07-29 13:15 UTC
Labels: area-Microsoft.CSharp, untriaged
