### ISSUE TITLE
Slow flock on nfs file share

### ISSUE THREAD

**Issue by miegir** [dotnet/runtime#93207] opened 2023-10-09 11:34 UTC
We are experiencyng poor performance when reading files that are located at nfs file share under astralinux. We are testing file access with the following code (C# 7.0):

``` C#
using System.Diagnostics;

if (args.Length < 1)
{
    Console.Error.WriteLine("A path is required.");
    return;
}

var path = args[0];

for (var i = 0; i < 3; i++)
{
    if (i > 0)
    {
        Console.WriteLine();
    }

    Console.WriteLine("Iteration {0}:", i + 1);

    var stopwatch = Stopwatch.StartNew();
    var info = new FileInfo(path);
    var length = info.Length;
    var lastWriteTimeUtc = info.LastWriteTimeUtc;
    Console.WriteLine("  Read stats in {0:N0} ms.", stopwatch.ElapsedMilliseconds);

    stopwatch.Restart();
    Console.WriteLine("  Length: {0}", length);
    Console.WriteLine("  LastWriteTimeUtc: {0}", lastWriteTimeUtc);
    Console.WriteLine("  Output stats in {0:N0} ms.", stopwatch.ElapsedMilliseconds);

    stopwatch.Restart();
    using var source = info.OpenRead();
    using var target = new MemoryStream();
    await source.CopyToAsync(target);
    Console.WriteLine("  Read [binary] in {0:N0} ms.", stopwatch.ElapsedMilliseconds); // this is slow
}
```

For local files, all times reported are several ms, but when the file is locates on nfs share, the read time can be 6 seconds or higher:
```
Iteration 1:
  Read stats in 1 ms.
  Length: 3870
  LastWriteTimeUtc: 05.09.2023 09:09:17
  Output stats in 2 ms.
  Read [binary] in 6 168 ms.

Iteration 2:
  Read stats in 0 ms.
  Length: 3870
  LastWriteTimeUtc: 05.09.2023 09:09:17
  Output stats in 0 ms.
  Read [binary] in 6 138 ms.

Iteration 3:
  Read stats in 0 ms.
  Length: 3870
  LastWriteTimeUtc: 05.09.2023 09:09:17
  Output stats in 0 ms.
  Read [binary] in 6 142 ms.
```

Our investigation shows that the problem is in the `flock` call which is performed in the following line of code:
https://github.com/dotnet/runtime/blob/4001e074ee648506d64277729a7cce089a4996e2/src/libraries/System.Private.CoreLib/src/Microsoft/Win32/SafeHandles/SafeFileHandle.Unix.cs#L360

When we hack `CanLockTheFile` to return `false` through the environment variable `DOTNET_SYSTEM_IO_DISABLEFILELOCKING=true`, the problem is gone and the file read completes in 0 ms.

Googling the problem shows that calling `flock` on nfs is generally known to be extremely slow and considered as bad practice. Because of this, it can be good to allow the caller to omit the lock when accessing certain files (the caller will decide if the file is on the nfs or not), or some other possibility to selectively disable the lock while still attempting to lock local files.

**Comment by miegir** [comment] 2023-10-12 12:43
As our system administrator said, using local_lock=all with nfs v3 results in error during mount ("mount.nfs: an incorrect mount option was specified").

**Comment by Jozkee** [comment] 2023-10-12 22:30
1. Could you try mounting the NFS share with `-o nolock`? 

2. Judging by [this code](https://github.com/dotnet/runtime/blob/946c5245aea149d9ece53fd0debc18328c29083b/src/libraries/System.Private.CoreLib/src/Microsoft/Win32/SafeHandles/SafeFileHandle.Unix.cs#L360-L371), `FileInfo.OpenRead` will ask for a shared lock. Can you try with an exclusive lock?
```cs
info.Open(FileMode.Open, FileAccess.Read, FileShare.None);
```

3. This other suggestion is kind of hacky: .NET does not emit shared locks on NFS if the file is opened with write permissions. You could abuse that to avoid locking NFS files without disabling locking on other filesystems.

**Comment by miegir** [comment] 2023-10-13 07:27
1. The same error with `-o nolock`.
2. As I understand from [lines 473-480](https://github.com/dotnet/runtime/blob/946c5245aea149d9ece53fd0debc18328c29083b/src/libraries/System.Private.CoreLib/src/Microsoft/Win32/SafeHandles/SafeFileHandle.Unix.cs#L473C13-L480C14), the lock will always be tried despite of `lockOperation` when `access` is not `FileAccess.Write`. The only way to skip the lock in such situation is forcing [`DisableFileLocking`](https://github.com/dotnet/runtime/blob/946c5245aea149d9ece53fd0debc18328c29083b/src/libraries/System.Private.CoreLib/src/Microsoft/Win32/SafeHandles/SafeFileHandle.Unix.cs#L469) to be `true`. As I said earlier, we tried this with `DOTNET_SYSTEM_IO_DISABLEFILELOCKING=true` and this mitigates the issue. The only problem here is that forcing `DisableFileLocking` to be `true` affects all files, not only those located in nfs.
3. Interesting suggestion. But I think that this will require write permission on the file which is not normally needed.

It is ideal if there be the way to check `unixFileSystemType` earlier than `lockOperation` and `access` (through some other option like `DisableFileLocking` maybe for compatibility).

**Comment by Jozkee** [comment] 2023-10-13 15:15
We might as well consider extending DisableFileLocking to specify which filesystems should affect.
e.g: `export DOTNET_SYSTEM_IO_DISABLEFILELOCKING=nfs,otherfs`.

**Comment by danmoseley** [comment] 2023-10-13 15:21
At that point why not expose an API, eg a static property? Env variables are usually for diagnostic type settings or where it relates to the runtime.

**Comment by tmds** [comment] 2023-10-13 20:08
We looked at a similar issue in the past. This was the summary: https://github.com/dotnet/runtime/issues/48757#issuecomment-1041277707.

> The same error with -o nolock.

Can you take a closer look to understand why the nolock option isn't accepted?

Maybe it helps if you explicitly set the version to 3.

**Comment by Jozkee** [comment] 2023-10-16 20:19
Thanks @tmds, will close this issue as duplicate of https://github.com/dotnet/runtime/issues/48757. Conversations can continue here to help you @miegir.

**Closed by Jozkee** 2023-10-16 20:19 UTC
Labels: area-System.IO, os-linux
