### ISSUE TITLE
System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_MultipleConnectionsEnabled_IdleConnectionTimeoutExpired_ConnectionRemovedAndNewCreated functional test failed on Linux (debug coreclr)

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#41507] opened 2020-08-28 10:26 UTC
console logs: https://helix.dot.net/api/2019-06-17/jobs/f786bae8-80c4-4c84-83df-d872dd175167/workitems/System.Net.Http.Functional.Tests/console

```sh
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_MultipleConnectionsEnabled_IdleConnectionTimeoutExpired_ConnectionRemovedAndNewCreated [FAIL]
      Assert.Equal() Failure
      Expected: 2
      Actual:   1
      Stack Trace:
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.cs(2242,0): at System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_MultipleConnectionsEnabled_IdleConnectionTimeoutExpired_ConnectionRemovedAndNewCreated()
        --- End of stack trace from previous location ---
  Finished:    System.Net.Http.Functional.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.Http.Functional.Tests  Total: 2122, Errors: 0, Failed: 1, Skipped: 16, Time: 90.554s
~/work/B29B095F/w/A3B809C6/e
----- end Fri Aug 28 09:53:37 UTC 2020 ----- exit code 1 ----------------------------------------------------------
Waiting a few seconds for any dump to be written..
Looking around for any Linux dump..
... found no dump in /home/helixbot/work/B29B095F/w/A3B809C6/e
+ export _commandExitCode=1
+ _commandExitCode=1
+ /bin/sh /home/helixbot/work/B29B095F/p/reporter/run.sh https://dev.azure.com/dnceng/ public 25006658 eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im9PdmN6NU1fN3AtSGpJS2xGWHo5M3VfVjBabyJ9.eyJuYW1laWQiOiJlNDI4NWM4Yy0zZmQ1LTQyNjctOWIxYy00MjE5NWM0N2E1NTMiLCJzY3AiOiJMb2NhdGlvblNlcnZpY2UuQ29ubmVjdCBQaXBlbGluZUNhY2hlLlJlYWRXcml0ZVJvb3RBY2Nlc3MgUmVhZEFuZFB1Ymxpc2hUZXN0OjllZTZkNDc4LWQyODgtNDdmNy1hYWNjLWY2ZTZkMDgyYWU2ZCBSZWFkQW5kVXBkYXRlQnVpbGRCeVVyaTo5ZWU2ZDQ3OC1kMjg4LTQ3ZjctYWFjYy1mNmU2ZDA4MmFlNmQvZG90bmV0L3J1bnRpbWUvNjg2OkJ1aWxkL0J1aWxkLzc5MTY4MCIsImF1aSI6Ijc4ZjA2MjVmLWQ2MTgtNGMwMC1iNjM5LTJmYTU1MmJkNDcxYyIsInNpZCI6ImIyNjM1MjEyLTc4NjktNDU2ZC04MTBkLWE4MTM3ZTdiM2FiOSIsIkJ1aWxkSWQiOiI5ZWU2ZDQ3OC1kMjg4LTQ3ZjctYWFjYy1mNmU2ZDA4MmFlNmQ7NzkxNjgwIiwib3JjaGlkIjoiOTE1NmIyMWEtNzA3Yi00M2I5LWIxMDItMTc3ZjRhMzdmYzUxLmxpYnJhcmllc190ZXN0X3J1bl9yZWxlYXNlX2NvcmVjbHJfbGludXhfeDY0X2RlYnVnLl9fZGVmYXVsdCIsImlzcyI6ImFwcC52c3Rva2VuLnZpc3VhbHN0dWRpby5jb20iLCJhdWQiOiJhcHAudnN0b2tlbi52aXN1YWxzdHVkaW8uY29tfHZzbzpiNTVkZTRlZC00YjVhLTQyMTUtYThlNC0wYTBhNWY3MWU3ZDgiLCJuYmYiOjE1OTg2MDcxNjYsImV4cCI6MTU5ODYxNzM2Nn0.l5EEDXNO1N9vE5yDzMg_g2OULWUII7U97fgQfUbsqevu3htTGw8KYqTQQG1M4XCLfYnZTA4TcAIRQFWxXAuYnrjRelqBQk2hZQx_pT2i1q9zMXDpZbEy6-F1icGUoIM8gNYG7J-ZQ23izpxVKpH93X1rY24XIgCs3xhWeTz2IonR63uEscS2sd9oWo1eCh31ElX6KNiKC9h2Mj7SaGfNmz43J0t4Iys_mKDR1d6zoFA0MWz1so3YL5WrrSRywGUcpbDUAn_Ty9Vrv07CULX4DrHQCGxGRttMP2FFJRwibIL2CvRQap5mTlk00KPYfFnQVldLpnqMIttqIv-ahsb5hA
++ whoami
+ '[' helixbot = root ']'
+ exec sudo -E /home/helixbot/work/B29B095F/p/reporter/run.sh https://dev.azure.com/dnceng/ public 25006658 eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Im9PdmN6NU1fN3AtSGpJS2xGWHo5M3VfVjBabyJ9.eyJuYW1laWQiOiJlNDI4NWM4Yy0zZmQ1LTQyNjctOWIxYy00MjE5NWM0N2E1NTMiLCJzY3AiOiJMb2NhdGlvblNlcnZpY2UuQ29ubmVjdCBQaXBlbGluZUNhY2hlLlJlYWRXcml0ZVJvb3RBY2Nlc3MgUmVhZEFuZFB1Ymxpc2hUZXN0OjllZTZkNDc4LWQyODgtNDdmNy1hYWNjLWY2ZTZkMDgyYWU2ZCBSZWFkQW5kVXBkYXRlQnVpbGRCeVVyaTo5ZWU2ZDQ3OC1kMjg4LTQ3ZjctYWFjYy1mNmU2ZDA4MmFlNmQvZG90bmV0L3J1bnRpbWUvNjg2OkJ1aWxkL0J1aWxkLzc5MTY4MCIsImF1aSI6Ijc4ZjA2MjVmLWQ2MTgtNGMwMC1iNjM5LTJmYTU1MmJkNDcxYyIsInNpZCI6ImIyNjM1MjEyLTc4NjktNDU2ZC04MTBkLWE4MTM3ZTdiM2FiOSIsIkJ1aWxkSWQiOiI5ZWU2ZDQ3OC1kMjg4LTQ3ZjctYWFjYy1mNmU2ZDA4MmFlNmQ7NzkxNjgwIiwib3JjaGlkIjoiOTE1NmIyMWEtNzA3Yi00M2I5LWIxMDItMTc3ZjRhMzdmYzUxLmxpYnJhcmllc190ZXN0X3J1bl9yZWxlYXNlX2NvcmVjbHJfbGludXhfeDY0X2RlYnVnLl9fZGVmYXVsdCIsImlzcyI6ImFwcC52c3Rva2VuLnZpc3VhbHN0dWRpby5jb20iLCJhdWQiOiJhcHAudnN0b2tlbi52aXN1YWxzdHVkaW8uY29tfHZzbzpiNTVkZTRlZC00YjVhLTQyMTUtYThlNC0wYTBhNWY3MWU3ZDgiLCJuYmYiOjE1OTg2MDcxNjYsImV4cCI6MTU5ODYxNzM2Nn0.l5EEDXNO1N9vE5yDzMg_g2OULWUII7U97fgQfUbsqevu3htTGw8KYqTQQG1M4XCLfYnZTA4TcAIRQFWxXAuYnrjRelqBQk2hZQx_pT2i1q9zMXDpZbEy6-F1icGUoIM8gNYG7J-ZQ23izpxVKpH93X1rY24XIgCs3xhWeTz2IonR63uEscS2sd9oWo1eCh31ElX6KNiKC9h2Mj7SaGfNmz43J0t4Iys_mKDR1d6zoFA0MWz1so3YL5WrrSRywGUcpbDUAn_Ty9Vrv07CULX4DrHQCGxGRttMP2FFJRwibIL2CvRQap5mTlk00KPYfFnQVldLpnqMIttqIv-ahsb5hA
```

**Comment by ManickaP** [comment] 2020-08-28 11:38
Duplicate of #41494

**Closed by ManickaP** 2020-08-28 11:38 UTC
Labels: area-System.Net.Http, untriaged
