### ISSUE TITLE
How to cancel StreamReader.ReadLineAsync with a CancellationToken or set timeout to stop reading?

### ISSUE THREAD

**Issue by shahinjabbar** [dotnet/runtime#42976] opened 2020-10-02 12:34 UTC
I am getting an HTTP stream and reading it until it sends some data but I need to figure out how to set a timeout in case of not receiving data from the stream which I'm reading using StreamReader class.

This stream sends me data every 50-80 seconds and I wanna handle it when it does not send any data in this timestamp.I am reading http stream and sometimes they just closes stream but code is not breaking while statement and I need to figure out how to break while and stop reading stream after not getting any data from stream inside 2 minutes.

Sample code is below :

```cs
using (HttpClient client = new HttpClient())
{
    client.BaseAddress = new Uri(_configuration.GetSection("COnfig").GetValue<string>("Url"));
    var streamresponse = await client.GetStreamAsync("stream");
    using (StreamReader reader = new StreamReader(streamresponse))
    {
        //reader.BaseStream.ReadTimeout = 2000;
        while (true)
        {
            string line = await reader.ReadLineAsync();
            if (!string.IsNullOrWhiteSpace(line))
            {
                string decoded = HttpUtility.UrlDecode(line, Encoding.GetEncoding("UTF-8")); ;
                //some logic
            }
        }
    }
}
```

**Comment by Jozkee** [comment] 2023-11-21 22:24
Duplicate of https://github.com/dotnet/runtime/issues/42733. See conclusion on https://github.com/dotnet/runtime/issues/42733#issuecomment-1287108107.

**Closed by Jozkee** 2023-11-21 22:24 UTC
Labels: question, area-System.IO
