### ISSUE TITLE
running AOT on a Blazor WASM app Error on .net Standard 2.0 dll

### ISSUE THREAD

**Issue by dkboon01** [dotnet/runtime#60612] opened 2021-10-18 21:04 UTC
### Describe the bug
I'm have a dll that is .net standard 2.0 it uses a package Microsoft.SqlServer.TransactSql.ScriptDOM it say it could not load file or assembly. I have cleaned and rebuild the project several times
![Screenshot 2021-10-18 170332](https://user-images.githubusercontent.com/11353230/137806382-b919db43-0acb-42e9-b391-b87eca8ba1b9.png)

### Further technical details
- ASP.NET Core version:
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version:
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```

```

</details>

**Comment by dkboon01** [comment] 2021-10-19 11:37
I don't know if the dll needs to be at .net 6 or will .net standard 2.0 be able to use with AOT.

**Comment by radical** [comment] 2021-10-19 23:25
This could be trimming related too. If you can build from the command line, then it build it with `dotnet publish -bl -p:RunAOTCompilation=true`, and share the generated `msbuild.binlog`. But make sure that you remove `bin`, `obj` folders before that, so we get a clean build.

**Comment by dkboon01** [comment] 2021-10-20 12:46
ES.CommonServices package is a custom package that is developed in house. It is at .net standard 2.0. Will this cause any problems being at .net standard 2.0 instead of being at .net 6?

**Comment by radical** [comment] 2021-10-21 17:57
> So I put this Microsoft.SqlServer.TransactSql.ScriptDom, into the ABCServices project to make sure the AOT would run and successfully publish.

Ok, so the `ES.CommonServices` nuget needs to add this as a dependency.

What's the size of `Microsoft.SqlServer.TransactSql.Scriptdom.dll`? You should see two of them, one in a `linked/` folder in `obj`, and another in the nuget.

Bigger assemblies can be slow to compile.

**Comment by radical** [comment] 2021-11-01 20:14
> > So I put this Microsoft.SqlServer.TransactSql.ScriptDom, into the ABCServices project to make sure the AOT would run and successfully publish.
> 
> Ok, so the `ES.CommonServices` nuget needs to add this as a dependency.

Are you able to build, and run the app with AOT now?

**Comment by dkboon01** [comment] 2021-11-02 09:58
Yes, it builds it but now my download to load the application takes 4 minutes. 
![MicrosoftTeams-image (12)](https://user-images.githubusercontent.com/11353230/139825466-0f9dce2e-0f7b-4046-83d7-031b60540472.png)

**Comment by dkboon01** [comment] 2021-11-02 09:58
I don't know what to try next.

**Comment by radical** [comment] 2021-11-02 17:05
You could try asking on `GitHub.com/dotnet/aspnetcore` for ideas. Maybe tweaking trimming might help.

Closing this as the issue is resolved.

**Closed by radical** 2021-11-02 17:05 UTC
Labels: arch-wasm, area-AssemblyLoader-mono
