### ISSUE TITLE
LINQ Chunk method in .NET 6 performance

### ISSUE THREAD

**Issue by silkfire** [dotnet/runtime#53478] opened 2021-05-30 09:16 UTC
I was curious to try out the performance of the newly introduced `Chunk` method in .NET 6 Preview 4 and how it compared to some of the implementations that have existed since before.

Sadly I was a bit appointed regarding its performance. There is room to improve it further, at least using a fully LINQ-based implementation.

```
|           Method | PartitionSize |      Mean |     Error |    StdDev |    Ratio | RatioSD |  Gen 0 | Allocated |
|----------------- |-------------- |----------:|----------:|----------:|---------:|--------:|-------:|----------:|
|    PartitionLinq |           100 |  5.933 ns | 0.0310 ns | 0.0290 ns | baseline |         | 0.0067 |      56 B |
| PartitionClassic |           100 |  6.109 ns | 0.0363 ns | 0.0322 ns |      +3% |    0.9% | 0.0086 |      72 B |
| PartitionJodrell |           100 |  6.161 ns | 0.0249 ns | 0.0233 ns |      +4% |    0.6% | 0.0077 |      64 B |
|     ChunkDotNet6 |           100 |  6.574 ns | 0.0230 ns | 0.0215 ns |     +11% |    0.6% | 0.0076 |      64 B |
|    PartitionNeo2 |           100 |  6.686 ns | 0.0626 ns | 0.0585 ns |     +13% |    0.6% | 0.0096 |      80 B |
|    MoreLinqBatch |           100 | 46.628 ns | 0.2286 ns | 0.2138 ns |    +686% |    0.4% | 0.0153 |     128 B |
|                  |               |           |           |           |          |         |        |           |
|    PartitionLinq |           200 |  5.961 ns | 0.0175 ns | 0.0163 ns | baseline |         | 0.0067 |      56 B |
| PartitionJodrell |           200 |  6.148 ns | 0.0201 ns | 0.0188 ns |      +3% |    0.3% | 0.0077 |      64 B |
| PartitionClassic |           200 |  6.303 ns | 0.0586 ns | 0.0548 ns |      +6% |    1.0% | 0.0086 |      72 B |
|     ChunkDotNet6 |           200 |  6.601 ns | 0.1055 ns | 0.0987 ns |     +11% |    1.6% | 0.0076 |      64 B |
|    PartitionNeo2 |           200 |  6.791 ns | 0.0751 ns | 0.0702 ns |     +14% |    1.2% | 0.0096 |      80 B |
|    MoreLinqBatch |           200 | 47.837 ns | 0.2013 ns | 0.1784 ns |    +702% |    0.4% | 0.0153 |     128 B |
|                  |               |           |           |           |          |         |        |           |
|    PartitionLinq |           500 |  5.944 ns | 0.0084 ns | 0.0074 ns | baseline |         | 0.0067 |      56 B |
| PartitionJodrell |           500 |  6.204 ns | 0.0312 ns | 0.0291 ns |      +4% |    0.5% | 0.0077 |      64 B |
| PartitionClassic |           500 |  6.310 ns | 0.1068 ns | 0.0999 ns |      +6% |    1.6% | 0.0086 |      72 B |
|     ChunkDotNet6 |           500 |  6.623 ns | 0.0949 ns | 0.0887 ns |     +11% |    1.4% | 0.0076 |      64 B |
|    PartitionNeo2 |           500 |  6.773 ns | 0.0299 ns | 0.0265 ns |     +14% |    0.4% | 0.0096 |      80 B |
|    MoreLinqBatch |           500 | 47.720 ns | 0.0886 ns | 0.0786 ns |    +703% |    0.2% | 0.0153 |     128 B |
|                  |               |           |           |           |          |         |        |           |
|    PartitionLinq |          1000 |  5.957 ns | 0.0166 ns | 0.0147 ns | baseline |         | 0.0067 |      56 B |
| PartitionJodrell |          1000 |  6.161 ns | 0.0143 ns | 0.0119 ns |      +3% |    0.3% | 0.0077 |      64 B |
| PartitionClassic |          1000 |  6.301 ns | 0.0977 ns | 0.0914 ns |      +6% |    1.5% | 0.0086 |      72 B |
|     ChunkDotNet6 |          1000 |  6.590 ns | 0.0881 ns | 0.0781 ns |     +11% |    1.2% | 0.0076 |      64 B |
|    PartitionNeo2 |          1000 |  6.723 ns | 0.0921 ns | 0.0862 ns |     +13% |    1.3% | 0.0096 |      80 B |
|    MoreLinqBatch |          1000 | 48.034 ns | 0.1234 ns | 0.1154 ns |    +706% |    0.3% | 0.0153 |     128 B |
```

Results with enumeration (both outer and inner):

```
|                 Method | PartitionSize |     Mean |    Error |   StdDev |    Ratio | RatioSD | Rank |   Gen 0 |  Gen 1 | Gen 2 | Allocated |
|----------------------- |-------------- |---------:|---------:|---------:|---------:|--------:|-----:|--------:|-------:|------:|----------:|
|    PartitionLinqToList |           100 | 31.04 us | 0.483 us | 0.452 us | baseline |         |    1 |  6.8359 | 0.9766 |     - |     56 KB |
|    PartitionNeo2ToList |           100 | 36.49 us | 0.356 us | 0.315 us |     +17% |    1.4% |    2 | 15.9912 | 3.9673 |     - |    131 KB |
|     ChunkDotNet6ToList |           100 | 63.49 us | 0.705 us | 0.625 us |    +104% |    1.8% |    3 | 10.7422 | 1.4648 |     - |     88 KB |
| PartitionJodrellToList |           100 | 68.40 us | 0.325 us | 0.304 us |    +120% |    1.5% |    4 | 10.7422 | 1.4648 |     - |     89 KB |
| PartitionClassicToList |           100 | 69.42 us | 0.596 us | 0.528 us |    +123% |    1.3% |    4 | 11.2305 | 1.5869 |     - |     92 KB |
|    MoreLinqBatchToList |           100 | 76.15 us | 0.297 us | 0.277 us |    +145% |    1.7% |    5 | 10.7422 | 1.5869 |     - |     88 KB |
|                        |               |          |          |          |          |         |      |         |        |       |           |
|    PartitionLinqToList |           200 | 26.41 us | 0.152 us | 0.119 us | baseline |         |    1 |  5.8289 | 0.7935 |     - |     48 KB |
|    PartitionNeo2ToList |           200 | 33.64 us | 0.248 us | 0.232 us |     +27% |    0.7% |    2 | 15.2588 | 3.7231 |     - |    125 KB |
|     ChunkDotNet6ToList |           200 | 60.72 us | 0.579 us | 0.542 us |    +130% |    1.0% |    3 | 10.1318 | 1.3428 |     - |     83 KB |
| PartitionClassicToList |           200 | 64.09 us | 0.381 us | 0.318 us |    +143% |    0.6% |    4 | 10.3760 | 1.4648 |     - |     86 KB |
| PartitionJodrellToList |           200 | 65.31 us | 0.632 us | 0.591 us |    +147% |    0.9% |    5 | 10.2539 | 1.2207 |     - |     84 KB |
|    MoreLinqBatchToList |           200 | 72.62 us | 1.114 us | 1.042 us |    +175% |    1.7% |    6 | 10.1318 | 1.4648 |     - |     83 KB |
|                        |               |          |          |          |          |         |      |         |        |       |           |
|    PartitionLinqToList |           500 | 24.03 us | 0.384 us | 0.320 us | baseline |         |    1 |  5.2185 | 0.6409 |     - |     43 KB |
|    PartitionNeo2ToList |           500 | 32.05 us | 0.158 us | 0.147 us |     +33% |    1.4% |    2 | 14.8926 | 3.6621 |     - |    122 KB |
|     ChunkDotNet6ToList |           500 | 56.97 us | 0.651 us | 0.578 us |    +137% |    1.8% |    3 |  9.8267 | 1.3428 |     - |     80 KB |
| PartitionJodrellToList |           500 | 63.44 us | 0.525 us | 0.491 us |    +164% |    1.9% |    4 | 10.0098 | 1.2207 |     - |     82 KB |
| PartitionClassicToList |           500 | 64.14 us | 1.282 us | 1.798 us |    +170% |    2.8% |    4 | 10.1318 | 1.5869 |     - |     83 KB |
|    MoreLinqBatchToList |           500 | 70.28 us | 0.660 us | 0.617 us |    +193% |    1.0% |    5 |  9.7656 | 1.3428 |     - |     80 KB |
|                        |               |          |          |          |          |         |      |         |        |       |           |
|    PartitionLinqToList |          1000 | 23.66 us | 0.473 us | 0.791 us | baseline |         |    1 |  5.0049 | 0.6409 |     - |     41 KB |
|    PartitionNeo2ToList |          1000 | 31.19 us | 0.278 us | 0.260 us |     +32% |    3.7% |    2 | 14.9536 | 3.7231 |     - |    123 KB |
|     ChunkDotNet6ToList |          1000 | 58.13 us | 0.378 us | 0.316 us |    +145% |    3.9% |    3 |  9.7046 | 1.4038 |     - |     79 KB |
| PartitionJodrellToList |          1000 | 64.71 us | 1.239 us | 1.522 us |    +174% |    3.9% |    4 | 10.1318 | 1.3428 |     - |     83 KB |
| PartitionClassicToList |          1000 | 65.64 us | 1.311 us | 1.402 us |    +177% |    3.9% |    4 | 10.1318 | 1.5869 |     - |     84 KB |
|    MoreLinqBatchToList |          1000 | 70.03 us | 0.474 us | 0.421 us |    +196% |    3.9% |    5 |  9.6436 | 1.3428 |     - |     79 KB |
```

See this project for benchmarks: https://github.com/silkfire/PartitionIEnumerableBenchmarks

@inputfalken

**Comment by stephentoub** [comment] 2021-05-30 10:51
> See this project for benchmarks

Your benchmark isn't measuring the real costs.  Your benchmarks look like this:
```C#
        [Benchmark]
        public void ChunkDotNet6()
        {
            var partitionedData = IEnumerable.Chunk(PartitionSize);
        }
```
You're measuring the cost of invoking the Chunk method, but that just produces the `IEnumerable<T>`... it doesn't enumerate it, which means you're not actually measuring most of these implementations, just whatever error checking is done as part of the call to produce the IEnumerable.  That's why your mean values are so small... there's no way any of these could chunk 10,000 items in 6ns.

**Comment by silkfire** [comment] 2021-05-30 15:18
@stephentoub If you uncomment the lower part of the benchmark file, I've also appended code where I iterate the `IEnumerable` by use of `ToList`. The results were very similar.

**Comment by stephentoub** [comment] 2021-05-30 15:47
I haven't tried running those,  but they're comparing apples to oranges. The .NET 6 implementation, by design, is creating a new array for each chunk,  whereas the other implementations are reusing and overwriting the contents of the same mutable list or array.  That design choice means any consumer that holds on to the instances and uses them subsequently will find themselves with corrupted data.

**Comment by silkfire** [comment] 2021-05-30 20:17
I'm not sure I'm following. The Linq implementation is immutable and does not affect the original nor any following collections chunked by it.

**Comment by stephentoub** [comment] 2021-05-30 20:40
> I'm not sure I'm following. The Linq implementation is immutable and does not affect the original nor any following collections chunked by it.

Just looked at the code again.  When I quickly glanced at it earlier on my phone, I was seeing it reuse the list/array it was yielding, but on re-review I see it's only doing so for the last iteration, which is fine.  So ignore my previous comment.

That said, I finally sat down at my computer and ran your benchmarks (the ones that actually enumerate).  I see results like this:

|                 Method | PartitionSize |      Mean |    Error |   StdDev |    Ratio | RatioSD | Rank |   Gen 0 |  Gen 1 | Gen 2 | Allocated |
|----------------------- |-------------- |----------:|---------:|---------:|---------:|--------:|-----:|--------:|-------:|------:|----------:|
|    PartitionLinqToList |           100 |  38.49 us | 0.749 us | 0.735 us | baseline |         |    1 |  9.1553 | 1.2207 |     - |     56 KB |
|    PartitionNeo2ToList |           100 |  41.00 us | 0.364 us | 0.323 us |      +6% |    2.1% |    2 | 21.2402 | 5.2490 |     - |    131 KB |
|     ChunkDotNet6ToList |           100 |  73.23 us | 0.503 us | 0.471 us |     +90% |    2.0% |    3 | 14.2822 | 1.9531 |     - |     88 KB |
| PartitionJodrellToList |           100 |  78.17 us | 0.447 us | 0.396 us |    +103% |    2.0% |    4 | 14.4043 | 2.0752 |     - |     89 KB |
|    MoreLinqBatchToList |           100 |  80.43 us | 0.441 us | 0.390 us |    +109% |    2.2% |    5 | 14.4043 | 2.0752 |     - |     88 KB |
| PartitionClassicToList |           100 | 102.06 us | 2.019 us | 2.625 us |    +166% |    3.5% |    6 | 14.8926 | 1.9531 |     - |     92 KB |

The .NET 6 implementation does as well as all of them except for PartitionLinqToList and PartitionNeo2ToList; makes sense, since it's essentially the same as all the others (albeit less code / simpler in how its constructed).  However, note that  PartitionNeo2ToList allocates almost twice as much... that's because it's optimizing for throughput by first copying everything into a new list, and then divvying that up into individual lists.  That's very far from optimal if you care at all about memory (especially since in your example the resulting array under that list will be on the large-object heap due to its size).  So we're really just talking about PartitionLinqToList, and that one's only fast for this particular input because the input is a `List<T>`, and so the repeated `Take`/`Skip` operators used in that implementation are optimized to directly index under the covers.  Let's change your benchmark slightly, changing the source from `Enumerable.Range(0, 10_000).ToList()` to instead be `Iterate()`, where that's defined as:
```C#
private static IEnumerable<int> Iterate()
{
    for (int i = 0; i < 10_000; i++) yield return i;
}
```
Now we get a very different story:

|                 Method | PartitionSize |        Mean |    Error |   StdDev |    Ratio | RatioSD | Rank |   Gen 0 |  Gen 1 | Gen 2 | Allocated |
|----------------------- |-------------- |------------:|---------:|---------:|---------:|--------:|-----:|--------:|-------:|------:|----------:|
|     ChunkDotNet6ToList |           100 |    51.71 us | 0.252 us | 0.236 us |     -98% |    0.5% |    1 | 14.3433 | 2.0142 |     - |     88 KB |
| PartitionJodrellToList |           100 |    54.27 us | 0.472 us | 0.442 us |     -98% |    0.9% |    2 | 14.4653 | 2.1362 |     - |     89 KB |
|    MoreLinqBatchToList |           100 |    55.21 us | 0.320 us | 0.300 us |     -98% |    0.6% |    3 | 14.4043 | 1.9531 |     - |     88 KB |
| PartitionClassicToList |           100 |    75.13 us | 0.322 us | 0.286 us |     -97% |    0.4% |    4 | 14.8926 | 2.1973 |     - |     92 KB |
|    PartitionNeo2ToList |           100 |    88.71 us | 0.339 us | 0.283 us |     -97% |    0.4% |    5 | 35.6445 | 8.9111 |     - |    220 KB |
|    PartitionLinqToList |           100 | 2,658.88 us | 6.938 us | 6.151 us | baseline |         |    6 | 19.5313 |      - |     - |    135 KB |

Note that the .NET 6 implementation now comes out on top, with not only the best throughput but also tied for the least memory allocation.

You can't conclude that an implementation is faster based on the one input.

**Comment by silkfire** [comment] 2021-05-30 22:21
That is certainly an impressive presentation of support! Thanks for the thorough explanation. And yes, in hindsight I should've tested with other collection types.

So I tested with `Enumerable.Range(10_000)` (without `ToList`):

```
|                 Method | PartitionSize |     Mean |    Error |   StdDev |    Ratio | RatioSD | Rank |   Gen 0 |  Gen 1 | Gen 2 | Allocated |
|----------------------- |-------------- |---------:|---------:|---------:|---------:|--------:|-----:|--------:|-------:|------:|----------:|
|    PartitionLinqToList |           100 | 23.80 us | 0.136 us | 0.113 us | baseline |         |    1 |  6.6528 | 0.9460 |     - |     55 KB |
|     ChunkDotNet6ToList |           100 | 49.25 us | 0.144 us | 0.128 us |    +107% |    0.5% |    2 | 10.7422 | 1.4648 |     - |     88 KB |
| PartitionJodrellToList |           100 | 49.57 us | 0.406 us | 0.380 us |    +108% |    0.6% |    2 | 10.8032 | 1.5259 |     - |     89 KB |
|    PartitionNeo2ToList |           100 | 54.28 us | 0.163 us | 0.153 us |    +128% |    0.5% |    3 | 15.9912 | 3.9673 |     - |    131 KB |
| PartitionClassicToList |           100 | 54.57 us | 0.155 us | 0.137 us |    +129% |    0.6% |    3 | 11.2305 | 1.5869 |     - |     92 KB |
|    MoreLinqBatchToList |           100 | 54.83 us | 0.096 us | 0.085 us |    +130% |    0.6% |    3 | 10.8032 | 1.7090 |     - |     88 KB |
```

And `Enumerable.Range(10_000).ToArray`:

```
|                 Method | PartitionSize |     Mean |    Error |   StdDev |    Ratio | RatioSD | Rank |   Gen 0 |  Gen 1 | Gen 2 | Allocated |
|----------------------- |-------------- |---------:|---------:|---------:|---------:|--------:|-----:|--------:|-------:|------:|----------:|
|    PartitionLinqToList |           100 | 36.35 us | 0.340 us | 0.318 us | baseline |         |    1 |  6.8359 | 0.9766 |     - |     56 KB |
|    PartitionNeo2ToList |           100 | 39.17 us | 0.104 us | 0.097 us |      +8% |    1.0% |    2 | 15.9912 | 3.9673 |     - |    131 KB |
|     ChunkDotNet6ToList |           100 | 50.00 us | 0.076 us | 0.071 us |     +38% |    0.9% |    3 | 10.7422 | 1.5259 |     - |     88 KB |
| PartitionJodrellToList |           100 | 52.28 us | 0.384 us | 0.300 us |     +44% |    0.6% |    4 | 10.8032 | 1.5869 |     - |     89 KB |
|    MoreLinqBatchToList |           100 | 55.00 us | 0.046 us | 0.043 us |     +51% |    0.9% |    5 | 10.8032 | 1.5869 |     - |     88 KB |
| PartitionClassicToList |           100 | 56.92 us | 0.230 us | 0.215 us |     +57% |    0.8% |    6 | 11.2305 | 1.5869 |     - |     92 KB |
```

And `Enumerable.Range(10_000).ToHashSet`:

```
|                 Method | PartitionSize |        Mean |     Error |    StdDev |    Ratio | RatioSD | Rank |   Gen 0 |  Gen 1 | Gen 2 | Allocated |
|----------------------- |-------------- |------------:|----------:|----------:|---------:|--------:|-----:|--------:|-------:|------:|----------:|
|    PartitionNeo2ToList |           100 |    48.18 us |  0.127 us |  0.113 us |     -99% |    1.2% |    1 | 15.9912 | 3.9673 |     - |    131 KB |
|     ChunkDotNet6ToList |           100 |    66.22 us |  0.733 us |  0.685 us |     -98% |    1.1% |    2 | 10.7422 | 1.4648 |     - |     88 KB |
| PartitionJodrellToList |           100 |    71.26 us |  0.601 us |  0.533 us |     -98% |    0.9% |    3 | 10.7422 | 1.4648 |     - |     89 KB |
| PartitionClassicToList |           100 |    74.18 us |  0.177 us |  0.166 us |     -98% |    1.2% |    4 | 11.2305 | 1.5869 |     - |     92 KB |
|    MoreLinqBatchToList |           100 |    78.73 us |  0.462 us |  0.409 us |     -98% |    1.3% |    5 | 10.7422 | 1.5869 |     - |     88 KB |
|    PartitionLinqToList |           100 | 3,641.75 us | 46.105 us | 43.126 us | baseline |         |    6 | 15.6250 |      - |     - |    137 KB |
```

As you can see I got some mixed results there. Can it still be presumed that `PartitionLinqToList` has an advantage when used with arrays / lists?

**Comment by stephentoub** [comment] 2021-05-31 01:15
> As you can see I got some mixed results there. Can it still be presumed that PartitionLinqToList has an advantage when used with arrays / lists?

Take / Skip are both optimized for `IList<T>`.  If there was good reason to, Chunk could be as well.  We've just not seen compelling enough reason to do so (and if we were, there are much more efficient ways to do it than is being done in PartitionLinqToList), having more code that needs to be maintained and whatnot.  Chunk as designed is fundamentally not a high-performance API, e.g. allocating a new array for every chunk.  Someone who really cared about getting the best performance shouldn't use any of these implementations.

**Comment by eiriktsarpalis** [comment] 2021-05-31 13:16
Copying elements into separately allocated buffers per chunk is by-design behaviour, and this is largely reflected by the method's type signature. This is unlike the `PartitionLinq` method where each chunk is wrapping the source enumerable. 

If we were to apply any `IList<T>` optimizations in `Chunk` they would probably only serve to avoid resizing of the final buffer (and perhaps take advantage of `IList<T>.CopyTo`) but I'm not particularly convinced this would result in dramatic performance improvements.

I'm going to close this issue as by-design.

**Closed by eiriktsarpalis** 2021-05-31 13:16 UTC
Labels: area-System.Linq, tenet-performance

**Comment by stephentoub** [comment] 2021-06-01 03:19
> If we were to apply any IList<T> optimizations in Chunk they would probably only serve to avoid resizing of the final buffer

FWIW, I expect the main benefit would be that iterating through the contents would entail one interface dispatch per element (IList's indexer) rather than two (MoveNext + Current).  For long sources, those interface calls often end up being a dominant cost.  It's also why various operators special-case arrays and `List<T>`, as then direct (and potentially inlineable) calls can be made rather than having any interface access.

I'm not saying we should do so, just pointing out that's likely where the 2x difference in some of the previous examples is coming from, making half the interface calls.
