### ISSUE TITLE
Unable to resolve default generic interface method with constraints

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#13588] opened 2019-10-15 15:22 UTC
...if the constraints reference generic parameters.

Reported in dotnet/roslyn#39219. Simplified repro without async goo.

```csharp
using System.Collections.Generic;
using System.Threading.Tasks;

class Program
{
    interface IApiControllerCRUD<IEntity>
    {
        IEnumerable<T> GetAsync<T>() where T : IEntity
        {
            return new List<T>();
        }
    }

    class MyApiController : IApiControllerCRUD<IMyEntity> { }
        
    interface IMyEntity { }
    class MyEntityViewModel : IMyEntity { }

    static void Main(string[] args)
    {
        IApiControllerCRUD<IMyEntity> api = new MyApiController();
        IEnumerable<MyEntityViewModel> sadFace = api.GetAsync<MyEntityViewModel>();
    }
}
```

Callstack:

```
 	coreclr.dll!RealCOMPlusThrow(RuntimeExceptionKind reKind, unsigned int resID, const wchar_t * wszArg1, const wchar_t * wszArg2, const wchar_t * wszArg3, const wchar_t * wszArg4, const wchar_t * wszArg5, const wchar_t * wszArg6) Line 12926	C++
 	coreclr.dll!MethodDesc::SatisfiesMethodConstraints(TypeHandle thParent, int fThrowIfNotSatisfied) Line 1684	C++
 	coreclr.dll!InstantiatedMethodDesc::NewInstantiatedMethodDesc(MethodTable * pExactMT, MethodDesc * pGenericMDescInRepMT, MethodDesc * pWrappedMD, Instantiation methodInst, int getWrappedCode) Line 464	C++
 	coreclr.dll!MethodDesc::FindOrCreateAssociatedMethodDesc(MethodDesc * pDefMD, MethodTable * pExactMT, int forceBoxedEntryPoint, Instantiation methodInst, int allowInstParam, int forceRemotableMethod, int allowCreate, ClassLoadLevel level) Line 1184	C++
 	coreclr.dll!MethodTable::FindDefaultInterfaceImplementation(MethodDesc * pInterfaceMD, MethodTable * pInterfaceMT, MethodDesc * * ppDefaultMethod, int allowVariance, int throwOnConflict) Line 7107	C++
 	coreclr.dll!MethodTable::FindDispatchImpl(unsigned int typeID, unsigned int slotNumber, DispatchSlot * pImplSlot, int throwOnConflict) Line 6848	C++
 	coreclr.dll!MethodTable::FindDispatchSlot(unsigned int typeID, unsigned int slotNumber, int throwOnConflict) Line 7243	C++
 	coreclr.dll!VirtualCallStubManager::Resolver(MethodTable * pMT, DispatchToken token, OBJECTREF * protectedObj, unsigned __int64 * ppTarget, int throwOnConflict) Line 2208	C++
 	coreclr.dll!VirtualCallStubManager::GetTarget(DispatchToken token, MethodTable * pMT, int throwOnConflict) Line 2547	C++
 	coreclr.dll!MethodTable::GetMethodDescForInterfaceMethod(TypeHandle ownerType, MethodDesc * pInterfaceMD, int throwOnConflict) Line 2070	C++
 	coreclr.dll!MethodTable::GetMethodDescForInterfaceMethodAndServer(TypeHandle ownerType, MethodDesc * pItfMD, OBJECTREF * pServer) Line 780	C++
 	coreclr.dll!MethodDesc::ResolveGenericVirtualMethod(OBJECTREF * orThis) Line 1967	C++
 	coreclr.dll!MethodDesc::GetMultiCallableAddrOfVirtualizedCode(OBJECTREF * orThis, TypeHandle staticTH) Line 2063	C++
 	coreclr.dll!JIT_VirtualFunctionPointer_Framed(Object * objectUNSAFE, CORINFO_CLASS_STRUCT_ * classHnd, CORINFO_METHOD_STRUCT_ * methodHnd) Line 4047	C++
 	coreclr.dll!JIT_VirtualFunctionPointer(Object * objectUNSAFE, CORINFO_CLASS_STRUCT_ * classHnd, CORINFO_METHOD_STRUCT_ * methodHnd) Line 4197	C++
```

The problem seems to be that the first thing `MethodDesc::ResolveGenericVirtualMethod` does is that it strips the method instantiation away. `MethodTable::FindDefaultInterfaceImplementation` then tries to find a `MethodDesc` with `allowInstParam: FALSE` for this. Doing that triggers constraint validation on a `MethodDesc` that doesn't have enough generic context to resolve the variable.

I experimentally tried to make `allowInstParam: TRUE`, but that hit other problems when `MethodDesc::ResolveGenericVirtualMethod` tries to make the owning type concrete again.

**Comment by mangod9** [comment] 2020-04-15 15:27
Yeah dupe of https://github.com/dotnet/runtime/issues/1674, which has been fixed.

**Closed by mangod9** 2020-04-15 15:27 UTC
Labels: area-TypeSystem-coreclr
