### ISSUE TITLE
MemoryStream that works with Memory<T>

### ISSUE THREAD

**Issue by lcsondes** [dotnet/runtime#40764] opened 2020-08-13 10:31 UTC
## Background and Motivation

I needed to wrap a `Memory<byte>` as a `Stream`, so I went to everyone's old friend, `MemoryStream` to see if it has an overload. It doesn't. I looked for related classes to see if there was something named similarly. I couldn't find any. I ended up writing my own but I feel like this should be part of the standard toolkit, especially given that everything these days is getting `Memory` and `Span` overloads.

## Proposed API

Either a `MemoryStream` constructor overload or a new class that does something similar to `MemoryStream(byte[])` but with `Memory<byte>` instead of `byte[]`.

## Usage Examples

``` C#
async Task Foo()
{
    var memory = await SomethingThatReturnsMemoryAsync();
    var ms = new MemoryStream(myMemory);
    await SomethingThatTakesAStreamAsync(ms);
}
```

## Alternative Designs

Pretty much the two above. It would be nicer if this was still `MemoryStream` itself and a new overload than introducing a new class. The existing name ironically fits this functionality better than what it does today.

## Risks

There's the general risk of changing/adding anything, if any existing wacky code reflected into mscorlib or wherever the BCL lives nowadays and expected to find exactly some layout of classes and their internals, that could break.

If `Memory<byte>` has an overhead compared to `byte[]` then that could affect performance depending on JIT, also if the overload solution gets chosen this could lead to extra complexity dealing with the array and memory cases in one class (although `Memory` can wrap an array so this could be a non-issue).

I can't see any extra risks to introducing `ReallyMemoryStream` (good name pending) other than the ongoing maintenance cost.

**Comment by jkotas** [comment] 2020-08-13 15:31
Duplicate of https://github.com/dotnet/runtime/issues/22838

**Closed by jkotas** 2020-08-13 15:31 UTC
Labels: api-suggestion, untriaged

**Comment by skrysmanski** [comment] 2020-10-04 07:03
@jkotas Are you sure this is a duplicate of #22838? It sound to me that #22838 wants to introduce **new `Stream` classes** instead of supporting `Memory<byte>` in the existing `MemoryStream` class (which is what this issue is about).

**Comment by jkotas** [comment] 2020-10-05 03:01
#22838 is discussing different options to address the "wrap a Memory<byte> as a Stream" scenario. It mentions reimplementing MemoryStream on top of Memory<byte> as one of the options. From #22838: "It’s possible we could get away with reimplementing MemoryStream on top of Memory<byte>..."
