### ISSUE TITLE
Test failure : System.Numerics.Tests.ComplexTests.Pow

### ISSUE THREAD

**Issue by AriNuer** [dotnet/runtime#13615] opened 2019-10-21 03:01 UTC
**Job:**
[coreclr-corefx-jitstressregs:20191020.1](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=394941)

**Details:**
https://helix.dot.net/api/2019-06-17/jobs/f0c1a15f-48eb-40e9-a2b1-a9a6077cda59/workitems/System.Runtime.Numerics.Tests/console

**OS & Arch:**
Windows x64

**Note:**

- There are no `MicrosoftPrivateCoreFxNETCoreAppVersion` in eng\Versions.props in coreclr repo, but `MicrosoftPrivateCoreFxNETCoreAppPackageVersion`
- This failure **doesn't repro** on our windows x64 machine with `MicrosoftPrivateCoreFxNETCoreAppPackageVersion`.

**Log:**
```
===========================================================================================================

C:\dotnetbuild\work\f0c1a15f-48eb-40e9-a2b1-a9a6077cda59\Work\646a12f5-c82f-47bb-aee2-b5f8851693eb\Exec>"C:\dotnetbuild\work\f0c1a15f-48eb-40e9-a2b1-a9a6077cda59\Payload\dotnet.exe" exec --runtimeconfig System.Runtime.Numerics.Tests.runtimeconfig.json xunit.console.dll System.Runtime.Numerics.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=nonnetcoreapptests -notrait category=nonwindowstests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing @C:\dotnetbuild\work\f0c1a15f-48eb-40e9-a2b1-a9a6077cda59\Payload\CoreFX.issues.rsp 
  Discovering: System.Runtime.Numerics.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Runtime.Numerics.Tests (found 219 of 225 test cases)
  Starting:    System.Runtime.Numerics.Tests (parallel test collections = on, max threads = 2)
    System.Numerics.Tests.ComplexTests.Pow(real: 1.7976931348623157E+308, imaginary: 0) [FAIL]
      Failure at line 1303. Expected real: 0. Actual real: 1.7976931348623157E+308
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1951,0): at System.Numerics.Tests.ComplexTests.VerifyRealImaginaryProperties(Complex complex, Double real, Double imaginary, Int32 lineNumber)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1304,0): at System.Numerics.Tests.ComplexTests.VerifyPow_Complex_Complex(Double realValue, Double imaginaryValue, Double realPower, Double imaginaryPower)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1275,0): at System.Numerics.Tests.ComplexTests.Pow_Complex_Complex(Double real, Double imaginary)
    System.Numerics.Tests.ComplexTests.Pow(real: -1.7976931348623157E+308, imaginary: 0) [FAIL]
      Failure at line 1303. Expected real: 0. Actual real: -1.7976931348623157E+308
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1951,0): at System.Numerics.Tests.ComplexTests.VerifyRealImaginaryProperties(Complex complex, Double real, Double imaginary, Int32 lineNumber)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1304,0): at System.Numerics.Tests.ComplexTests.VerifyPow_Complex_Complex(Double realValue, Double imaginaryValue, Double realPower, Double imaginaryPower)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1275,0): at System.Numerics.Tests.ComplexTests.Pow_Complex_Complex(Double real, Double imaginary)
    System.Numerics.Tests.ComplexTests.Pow(real: 1, imaginary: 0) [FAIL]
      Failure at line 1303. Expected real: 0. Actual real: 1
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1951,0): at System.Numerics.Tests.ComplexTests.VerifyRealImaginaryProperties(Complex complex, Double real, Double imaginary, Int32 lineNumber)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1304,0): at System.Numerics.Tests.ComplexTests.VerifyPow_Complex_Complex(Double realValue, Double imaginaryValue, Double realPower, Double imaginaryPower)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1275,0): at System.Numerics.Tests.ComplexTests.Pow_Complex_Complex(Double real, Double imaginary)
    System.Numerics.Tests.ComplexTests.Pow(real: -1, imaginary: 0) [FAIL]
      Failure at line 1303. Expected real: 0. Actual real: -1
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1951,0): at System.Numerics.Tests.ComplexTests.VerifyRealImaginaryProperties(Complex complex, Double real, Double imaginary, Int32 lineNumber)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1304,0): at System.Numerics.Tests.ComplexTests.VerifyPow_Complex_Complex(Double realValue, Double imaginaryValue, Double realPower, Double imaginaryPower)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1275,0): at System.Numerics.Tests.ComplexTests.Pow_Complex_Complex(Double real, Double imaginary)
  Finished:    System.Runtime.Numerics.Tests
=== TEST EXECUTION SUMMARY ===
   System.Runtime.Numerics.Tests  Total: 2086, Errors: 0, Failed: 4, Skipped: 0, Time: 105.001s
----- end Sun 10/20/2019 12:21:42.12 ----- exit code 1 ----------------------------------------------------------
```

**Comment by tannergooding** [comment] 2020-03-05 20:01
@BruceForstall, do you know if this is still an issue in current runs? I'm not sure which jobs to check after the repo migration 😄

**Comment by BruceForstall** [comment] 2020-03-05 20:59
We're currently not running jit stress on libraries tests. That's still a "to do".

I would generally suggest closing any old bug that was occurring on old CI infra, if you can't easily repro it locally by just setting the env vars.

**Comment by tannergooding** [comment] 2020-03-05 21:03
Closing as I am not able to reproduce the bug. Please feel free to reopen if you have a repro case or if it is continuing to fail on current runs.

**Closed by tannergooding** 2020-03-05 21:03 UTC
Labels: arch-x64, area-System.Numerics, os-windows, test-corefx
