### ISSUE TITLE
 Assertion failed '(tree->gtFlags & GTF_GLOB_REF) || ((obj != nullptr) && (obj->gtOper == GT_LCL_VAR))' during 'Morph - Structs/AddrExp' (IL size 36)

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#62815] opened 2021-12-14 21:57 UTC
While trying to play around with https://github.com/dotnet/runtime/issues/60330, hit this assert

```c#
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Threading;

class MainClass
{
    public static void Main(string[] args)
    {
        MainClass m = new MainClass();
        m.Foo();
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    private void Foo()
    {
        Vector3 val = new Vector3(0.0f, 0.0f, 0.0f);
        Bar(val, Vector3.Zero);
    }

    private bool Bar(Vector3 input, Vector3 input2)
    {
        return input.X == input2.Y;
    }
}
```

```
TestEnvironment:
COMPlus_TieredCompilation=0

Assert failure(PID 41684 [0x0000a2d4], Thread: 19924 [0x4dd4]): Assertion failed '(tree->gtFlags & GTF_GLOB_REF) || ((obj != nullptr) && (obj->gtOper == GT_LCL_VAR))' in 'MainClass:Foo():this' during 'Morph - Structs/AddrExp' (IL size 36)

    File: D:\git\runtime\src\coreclr\jit\morph.cpp Line: 16864
    Image: D:\git\runtime\artifacts\tests\coreclr\windows.x64.Checked\tests\Core_Root\corerun.exe

**Comment by kunalspathak** [comment] 2021-12-14 21:57
@dotnet/jit-contrib

**Comment by SingleAccretion** [comment] 2021-12-20 13:28
I have checked, and #62883 did indeed fix the issue (the reproduction is no more, and it was caused by the forward substitution in the first place). As such, closing.

**Closed by SingleAccretion** 2021-12-20 13:28 UTC
Labels: area-CodeGen-coreclr, untriaged
