### ISSUE TITLE
DI : add support to eager load a singleton service

### ISSUE THREAD

**Issue by ah1508** [dotnet/runtime#43149] opened 2020-10-07 09:51 UTC
This adds a mechanism to register services to be activated during startup of a host instead of on first access.

It leverages the new `IHostedLifecycleService.StartingAsync()` in https://github.com/dotnet/runtime/issues/86511 to do this as early as possible, although for backwards compat it can also hook into the `IHostedService.StartAsync()` if the new StartingAsync() was not called.

It supports both a simple way to activate a service by type and an advanced case that calls an async callback which is encapsulated in the host's `IHost.StartAsync()`.

It is located in the hosting abstractions assembly and requires no additional work for hosts other than to support `IHostedService` and optionally the new `IHostedLifecycleService` interface.

## API Proposal
In the hosting abstractions assembly:
```diff
namespace Microsoft.Extensions.DependencyInjection;

public static partial class ServiceCollectionHostedServiceExtensions
{
    // Simply activates the service by type
+    public static IServiceCollection AddStartupActivation<TService>
+        (this IServiceCollection services) where TService : class;
    
    // Support the new keyed services feature
+    public static IServiceCollection AddKeyedStartupActivation<TService>
+        (this IServiceCollection services, object? serviceKey) where TService : class;

    // Activates the service by type and calls an async method that allows access to the service
+    public static IServiceCollection AddStartupActivation<TService>
+        (this IServiceCollection services,
+        Func<IServiceProvider, TService, CancellationToken, Task> activatorFunc)
+        where TService : class;

    // Support the new keyed services feature
+    public static IServiceCollection AddKeyedStartupActivation<TService>
+        (this IServiceCollection services, object? serviceKey,
+        Func<IServiceProvider, TService, CancellationToken, Task> activatorFunc)
+        where TService : class;
}
```
## Usage examples
```cs
[Fact]
public async void ActivateByType()
{
    var hostBuilder = CreateHostBuilder(services =>
    {
        services
            .AddSingleton<ActivateByType_Impl>()
            .AddStartupActivation<ActivateByType_Impl>();
    });

    using (IHost host = hostBuilder.Build())
    {
        await host.StartAsync();
        Assert.True(ActivateByType_Impl.Activated);
    }
}

public class ActivateByType_Impl
{
    public static bool Activated = false;
    public ActivateByType_Impl()
    {
        Activated = true;
    }
}

[Fact]
public async void ActivateByTypeWithCallback()
{
    var hostBuilder = CreateHostBuilder(services =>
    {
        services
            .AddSingleton<ActivateByTypeWithCallback_Impl>()
            .AddStartupActivation<ActivateByTypeWithCallback_Impl>(async (service, sp, cancellationToken) =>
        {
            await service.DoSomethingAsync(cancellationToken);
        });
    });

    using (IHost host = hostBuilder.Build())
    {
        await host.StartAsync();
        Assert.True(ActivateByTypeWithCallback_Impl.Activated);
        Assert.True(ActivateByTypeWithCallback_Impl.DidSomethingAsync_Before);
        Assert.True(ActivateByTypeWithCallback_Impl.DidSomethingAsync_After);
    }
}

public class ActivateByTypeWithCallback_Impl
{
    public static bool Activated = false;
    public static bool DidSomethingAsync_Before = false;
    public static bool DidSomethingAsync_After = false;

    public ActivateByTypeWithCallback_Impl()
    {
        Activated = true;
    }

    public async Task DoSomethingAsync(CancellationToken cancellationToken)
    {
        DidSomethingAsync_Before = true;
        await Task.Delay(10, cancellationToken);
        DidSomethingAsync_After = true;
    }
}
```

Prototype at https://github.com/steveharter/runtime/tree/SingletonWarmup.

## Original issue description
[AB#1244417](https://devdiv.visualstudio.com/10e66e43-9645-4201-b128-0fdc3769cc17/_workitems/edit/1244417)
Until now a service is created when `GetService` method is called on the service provider, or when the service must be injected in a controller responsible for the coming http request.

A first limitation : a service whose instance is never injected or never asked (`GetService`) will be never instantiated. If this service do some init work (fill a memory cache for instance), this work will never be done.

Even if this service is required somewhere, we should have the option to force eager creation of the instance (when `BuildServiceProvider` method is called) and not when the service is required for the first time. startup != first use.

Second limitation : if the init work takes 3 seconds, I will have the the "cold start" problem.

It also has consequences on the context in which the initialization work his done. Example :

```csharp
public class Foo : IFoo 
{
    public Foo() 
    {
        DoSomeInitWork();
    }

    private void DoSomeInitWork()
    {
        // code
    }
}
```
Somewhere in my application :

```csharp
using(var tx = new TransactionScope())
{
    IFoo foo = serviceProvider.GetService<IFoo>();
    // use foo
}
```
Here, `Foo` will be instantiated inside the transaction. Let's say I cannot receive `Foo` by injection because the service I need must be obtained dynamically.  

In `FooTest` : 

```csharp
public class FooTest
{
    private IFoo foo;

    public FooTest()
    {
       // service provider initialization
       this.foo = serviceProvider.GetService<IFoo>();
    }
}
```
Here, `Foo` will be instantiated outside of  the transaction.

If the `DoSomeInitWork()` method requires a transaction, it should first check if a transaction is ongoing before creating one.

Suggestion : add a property in the `ServiceDescriptor` class and a parameter for the `AddSingleton` méthods.

**Comment by pinkfloydx33** [comment] 2020-10-08 08:05
> when BuildServiceProvider method is called

That's potentially dangerous. While there's an analyzer that warns about incorrectly calling `BuildServiceProvider` just to grab some intermediate values, many library authors, [including Microsoft](https://github.com/microsoft/ApplicationInsights-Kubernetes/blob/4838ed97a556ebfd0400eebd6ff2fba0780b0c87/src/ApplicationInsights.Kubernetes/Extensions/ApplicationInsightsExtensions.cs#L174) currently follow this pattern. 

Eager loading of a dependency this way could end up being performed multiple times without you, the user, being aware and then it becoming difficult to track down.

**Comment by ah1508** [comment] 2020-10-17 08:45
Dear all,

Using a `IStartupFilter` does not respect the "separation of concern" best practice because the ASP.NET app would be responsible for triggering the creation of an object it does not even need. And creating a `IStartupFilter` implementation is not enough, it also has to be registered as a service. Too much responsibility for the asp.net layer.

In my case, the `DoSomeInitWork` method is in the data access layer, and fills a second level cache for Nhibernate. But it could something else, it is a very generic case.  And the data access layer cannot contain a `IStartupFilter` implementation because it is a classlib which has no relation to asp.net.

And the `IStartupFilter` would not work in unit tests.

How about adding a boolean 'eagerLoading` in the `ServiceDescriptor` ? Then , when `BuildServiceProvider` is called, services registered with `eagerLoading` would be created (just by calling `GetService`). Calling `BuildServiceProvider` for the same service collection seems a anti pattern to me, but even 

@pinkfloydx33 : Calling `BuildServiceProvider` several times for the same service collection seems an antipattern to me as well, but to prevent several eager loadings how about adding a flag in the service collection (false only if `BuildServiceProvider` has not been called yet).

**Comment by davidfowl** [comment] 2020-10-17 13:17
We already have an options object, and that's where something like this would like this would go. We already have prior art here with various validations (scoped and a dependency check). Eager loading would fit here as well and isn't a bad idea.

There would of course be caveats as this would only work for closed generics and non-generic singletons. Today we do a similar validation but don't actually resolve the service because that could have side effects.

**Comment by ah1508** [comment] 2020-12-08 09:43
@davidfowl : are you talking about the `ServiceProviderOptions` object ?

Indeed, it would be interesting to enable eager loading for all services at once but I think it should come in addition to a setting at the `ServiceDescriptor` level.

**Comment by davidfowl** [comment] 2020-12-08 12:32
There shouldn't a per service descriptor setting. Object graphs aren't per descriptor but that's not the only problem. Changes to 
the service descriptor require other container authors to react to any new feature service descriptors have. This change is eagerly resolving the dependency graph and I think something like this should be a bool on the `ServiceProviderOptions`

**Comment by dazinator** [comment] 2021-07-25 12:24
Im missing something. Why not:
```
var instance = new Foo();
services.AddSingleton(instance);
```

If its because you want the container to own the instance then this comes back to having an isExternallyOwned (or equivalent) option:

```
services.AddSingleton(instance, isExternallyOwned: false)
```

The use case mentions:

```
If this service do some init work (fill a memory cache for instance), this work will never be done.
```

Why would you want init work - that could quite possibly be async, to be done in the construction of a dependency like this? Isn't the better pattern to:-
1. Resolve the dependency synchronously at the point you need it in the application.
2. Invoke some method on it like `myservice.PrimeCacheAsync()`

That way this work isn't within the constructor of the dependency.

This removes the need to create the instance ahead of time, but puts the emphasis back on having the right place to do any async init work after the container is built and before serving http requests I.e we need the opportunity to do this async init work:

```
var sp = BuildServiceProvider();
await DoInitWorkAsybc(sp);
StartAcceptingHttpRequests();

```

**Comment by Timovzl** [comment] 2021-11-01 10:54
@ah1508 The following might be a "less custom" way to achieve that:

```cs
var hostBuilder = new HostBuilder();
hostBuilder.ConfigureServices(services =>
    services.AddMyStuff()); // Or BuildServiceProvider(...), as you have named it
using var host = hostBuilder.Build();
await host.StartAsync();
```

The scenario you describe is what I would call an integration test: it tests code _in context_, i.e. as it integrates with other code.

For integration tests, it makes perfect sense to me to use and start an `IHost`. Doing so implies starting every potential `IHostedService`, which happens to be precisely what you want.

Any background service that we might _not_ want to start - say, a periodic archiving process - we would simply mock away, by overwriting the dependency with a mock instance, in `ConfigureServices()`.

**Comment by steveharter** [comment] 2023-07-12 13:37
Note the original description was updated to include an API proposal:
- Supports per-service-type activation (does not activate all services)
- Supports service activation during startup with optional async callback
- Located in hosting abstractions assembly with no extra work from other hosts as long as they implement `IHostedService`

**Comment by rafal-mz** [comment] 2023-07-12 23:21
```csharp
[Fact]
public async void ActivateByType()
{
    var hostBuilder = CreateHostBuilder(services =>
    {
        services
            .AddSingleton<ActivateByType_Impl>()
            .AddStartupActivation<ActivateByType_Impl>();
    });

    using (IHost host = hostBuilder.Build())
    {
        await host.StartAsync();
        Assert.True(ActivateByType_Impl.Activated);
    }
}
```

Do we need to have two calls? I think that you need to know that you will want to instantiate your class at the design time, so I don't see a reason for separation.

I would expect something like:

```csharp
services.AddActivatedSingleton<TImplementation>(...)
```

Personally, I don't really like the word `Activation`, since it is not very precise about what does it mean to activate a class. I would call it somehow, that points directly that the instance will be created eagerly not lazily. Maybe something like `AddStartupCreatedSingleton<TImplementation>`?

IMHO adding async overload for factory is turbo strange, since there is no parity for this functionality for other lifetimes. I would add it for Scoped and Transient or not add at all.


```csharp
namespace Microsoft.Extensions.DependencyInjection;

public static partial class StartupCreatedServiceCollectionExtensions
{
+    public static IServiceCollection AddStartupCreatedSingleton<TService>
+        (this IServiceCollection services) where TService : class;

+    public static IServiceCollection TryAddStartupCreatedSingleton<TService>
+        (this IServiceCollection services) where TService : class;

+    public static IServiceCollection AddStartupCreatedTransient<TService>
+        (this IServiceCollection services) where TService : class;

+    public static IServiceCollection AddKeyedStartupActivatedSingleton<TService>
+        (this IServiceCollection services, object? serviceKey) where TService : class;
```

- I would expect more overloads, that accept function factory, 'Try*' semantics for adding items,  two generics and so on.
-  No async. Strange.

**Comment by Timovzl** [comment] 2023-07-17 16:57
From the perspective of not introducing too many ways to do the same thing, I'm still curious what the proposal truly adds that isn't already perfectly available.

```cs
// We can implement IHostedService
services
   .AddSingleton<MyService>()
   .AddSingleton<IHostedService>(serviceProvider => serviceProvider.GetRequiredService<MyService>());

// In the rare case where we cannot or should not change MyService to implement IHostedService,
// we can delegate that responsibility to an accompanying starter class
services
   .AddSingleton<MyService>()
   .AddSingleton<IHostedService, MyServiceStarter>();
```

I believe the proposed API introduces a non-negligible amount of confusion, in return for features that we already have a clean and concise API for.

What's more, the examples I've shown here also work as expected when we use assembly scanning (such as provided by Scrutor). This allows us to omit these manual registrations altogether. The proposed API, on the other hand, encourages manual and customized registrations.

I dread a scenario where half the services are started because they implement `IHostedService` and the other half because the registration says so.

**Comment by ah1508** [comment] 2023-07-17 17:36
@Timovzl : I see two problem with `IHostedService` : 

1: the class must implement this interface.

But after all why not, even if it requires a requires a Nuget package.

2: this code is not intuitive:

```csharp
services
   .AddSingleton<MyService>()
   .AddSingleton<IHostedService>(serviceProvider => serviceProvider.GetRequiredService<MyService>());
```

It is even worse if `MyService` must be visible as `IMyService` the declaration in the service collection looks like that:

```csharp
services
   .AddSingleton<IMyService, MyService>()
   .AddSingleton<IHostedService>(serviceProvider => serviceProvider.GetRequiredService<IMyService>() as MyService);
```

Hack or best practice ? Maybe the second registration could be built-in if implementation type implements `IHostedService`

**Comment by Timovzl** [comment] 2023-07-17 18:46
Declaring a type both as itself (or its representative interface) _and_ as `IHostedService` _by requesting the former_, I would consider best practice.

I agree that the way to do it is not obvious. One has to learn that, for scoped or singleton, registering one thing under multiple types requires some care rather than two naive, unrelated registrations. I'd love to see a way to express _that_ more neatly. Admittedly, it's tough to come up with a sensible overload to do so. `AddSingleton<T1, T2>` already means that `T2` is to be _constructed_, not resolved from the service provider, so we can't use that.

On a practical note, in application code, I stick to assembly scanning as much as possible:

```cs
// Using Scrutor
services.Scan(scanner => scanner
	.FromAssemblies(this.GetType().Assembly)
	.AddClasses(c => c.Where(type => /* Snip: constraints */), publicOnly: false) // Services only
	.AsSelfWithInterfaces()
	.WithSingletonLifetime());
```

This takes correctly registering a type under multiple types out of our hands, and it avoids the general maintenance work of manual registrations.

**Comment by steveharter** [comment] 2023-07-17 20:34
Changing to API-suggestion based on feedback above until there is more consensus.

> I would expect something like: services.AddActivatedSingleton<TImplementation>(...)

> adding async overload for factory is turbo strange, since there is no parity for this functionality for other lifetimes

That was added based on other feedback in this issue requesting async support. The proposal also works on an existing service without having to change it to implement IHostedService.

> I would expect more overloads, that accept function factory, 'Try*' semantics for adding items, two generics and so on.

If we combine with the AddSingleton* version then yes there would need to be more overloads.

> I'm still curious what the proposal truly adds that isn't already perfectly available.

Like existing extensions methods in DI, these essentially wrap existing 1-3 lines that can be manually written as well.

**Comment by steveharter** [comment] 2023-07-20 17:54
Closing this issue as a duplicate of #86075

**Closed by steveharter** 2023-07-20 17:54 UTC
Labels: api-suggestion, feature-request, area-Extensions-DependencyInjection, partner-impact
