### ISSUE TITLE
macOS build instructions fail

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#1700] opened 2020-01-13 23:51 UTC
Somewhat related to #1461.

I'm following our documentation for building on Mac:

https://github.com/dotnet/runtime/blob/master/docs/workflow/README.md

plus the prerequisites here:

https://github.com/dotnet/runtime/blob/master/docs/workflow/requirements/macos-requirements.md

I simply run `./build.sh` from the root, and it fails in the "Commencing build of corefx native components for OSX.x64.Debug" phase with:

```
  -- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_INCLUDE_DIR) 
  CMake Error at System.Security.Cryptography.Native/CMakeLists.txt:17 (message):
    !!! Cannot find libssl and System.Security.Cryptography.Native cannot build
    without it.  Try installing libssl-dev (or the appropriate package for your
    platform) !!!
```

When I do:
```
brew install openssl
```
I get:
```
Warning: openssl@1.1 1.1.1d is already installed and up-to-date
To reinstall 1.1.1d, run `brew reinstall openssl@1.1`
```

What documentation needs to be added to explain to users what is necessary to install, to allow the build to succeed?

@bartonjs @danmosemsft

**Comment by bartonjs** [comment] 2020-01-13 23:58
Duplicate of #1461.

It's probably

```
# We need to make the runtime libraries discoverable, as well as make
# pkg-config be able to find the headers and current ABI version.
#
# Ensure the paths we will need exist
mkdir -p /usr/local/lib/pkgconfig

# The rest of these instructions assume a default Homebrew path of
# /usr/local/opt/<module>, with /usr/local being the answer to
# `brew --prefix`.
#
# Runtime dependencies
ln -s /usr/local/opt/openssl/lib/libcrypto.1.1.dylib /usr/local/lib/
ln -s /usr/local/opt/openssl/lib/libssl.1.1.dylib /usr/local/lib/

# Compile-time dependencies (for pkg-config)
ln -s /usr/local/opt/openssl/lib/pkgconfig/libcrypto.pc /usr/local/lib/pkgconfig/
ln -s /usr/local/opt/openssl/lib/pkgconfig/libssl.pc /usr/local/lib/pkgconfig/
ln -s /usr/local/opt/openssl/lib/pkgconfig/openssl.pc /usr/local/lib/pkgconfig/
```

Taking into account the switch from 1.0.2 to 1.1.  But I haven't verified that.  Wanna be the guinea pig (and update the existing issue)?

**Closed by bartonjs** 2020-01-13 23:58 UTC
Labels: area-Meta, documentation, untriaged
