### ISSUE TITLE
`DateTime.Now` on Linux has wrong timezone

### ISSUE THREAD

**Issue by ivan7wl** [dotnet/runtime#60469] opened 2021-10-15 14:46 UTC
### Description

When use `DateTime.Now` on my Linux machine, dotnet assume the timezone is UTC.

### Reproduction Steps

Using Ubuntu 20.04:
```
$ timedatectl status
               Local time: 五 2021-10-15 21:07:22 CST
           Universal time: 五 2021-10-15 13:07:22 UTC
                 RTC time: 五 2021-10-15 13:07:22    
                Time zone: Asia/Shanghai (CST, +0800)
System clock synchronized: yes                       
              NTP service: active                    
          RTC in local TZ: no
```

However the code:
```c#
DateTime localNow = DateTime.Now;
DateTime utcNow = DateTime.UtcNow;
Console.WriteLine($"localNow: {localNow}, {localNow.Kind}, utcNow: {utcNow}, {utcNow.Kind}");
Console.WriteLine($"TimeZoneInfo.Local: {TimeZoneInfo.Local}");
```
Produces output:
```
localNow: 10/15/2021 13:07:25, Local, utcNow: 10/15/2021 13:07:25, Utc
TimeZoneInfo.Local: (UTC) Coordinated Universal Time
```

### Expected behavior

`DateTime.Now` has the proper local time.

### Actual behavior

`DateTime.Now` always equal to UTC time, no matter what the system timezone is.

### Configuration

Using dotnet sdk 6.0.100-rc.1.21463.6 on Linux (Ubuntu 20.04).
```
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.1.21463.6
 Commit:    e627d556a1

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /opt/dotnet/sdk/6.0.100-rc.1.21463.6/

Host (useful for support):
  Version: 6.0.0-rc.1.21451.13
  Commit:  d7619cd4b1

.NET SDKs installed:
  5.0.401 [/opt/dotnet/sdk]
  6.0.100-rc.1.21463.6 [/opt/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.10 [/opt/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [/opt/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.10 [/opt/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [/opt/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### Other information
~~UPDATE:~~
~~I found this issue may relate to RTC settings:~~
```
$ timedatectl set-local-rtc 1 --adjust-system-clock
$ sudo reboot
...
$ timedatectl status
               Local time: 五 2021-10-15 23:25:15 CST
           Universal time: 五 2021-10-15 15:25:15 UTC
                 RTC time: 五 2021-10-15 15:25:16    
                Time zone: Asia/Shanghai (CST, +0800)
System clock synchronized: yes                       
              NTP service: active                    
          RTC in local TZ: yes                       

Warning: The system is configured to read the RTC time in the local time zone.
         This mode cannot be fully supported. It will create various problems
         with time zone changes and daylight saving time adjustments. The RTC
         time is never updated, it relies on external facilities to maintain it.
         If at all possible, use RTC in UTC by calling
         'timedatectl set-local-rtc 0'.
$ dotnet run
localNow: 10/15/2021 23:25:25, Local, utcNow: 10/15/2021 15:25:25, Utc
TimeZoneInfo.Local: (UTC+08:00) CST
```

~~But this is weird, when I use `timedatectl set-local-rtc 0 --adjust-system-clock` to set it back, this issue cannot be reproduced anymore.~~

**Comment by ivan7wl** [comment] 2021-10-15 16:02
I don't know why but things are get more and more complicated, I can now reproduce this on 6.0.100-rc.2.21505.57, but cannot reproduce on 5.0.401.
```
test_project_50$ dotnet run
localNow: 10/15/2021 23:59:19, Local, utcNow: 10/15/2021 15:59:19, Utc
TimeZoneInfo.Local: (UTC+08:00) CST
test_project_50$ cd ../test_project_60/
test_project_60$ dotnet run
localNow: 10/15/2021 15:59:28, Local, utcNow: 10/15/2021 15:59:28, Utc
TimeZoneInfo.Local: (UTC) Coordinated Universal Time
```

**Comment by tarekgh** [comment] 2021-10-16 01:31
ok, thanks. This issue should be fixed in the release build already. If you are interested to try it, you may try installing the 6.0 release build from https://github.com/dotnet/installer. I am closing the issue but feel free to send any question if you have any. Thanks for your report.

**Comment by ivan7wl** [comment] 2021-10-16 03:56
@tarekgh Thanks for your reply, I tried .NET 6.0.0-rtm.21515.9 and it works. However `SelfContained` publish currently not working on this version. Waiting for the official release.

**Comment by ivan7wl** [comment] 2021-10-17 14:37
> > SelfContained publish currently not working on this version
> 
> Is that a known issue? What is the output? @agocke

Hi @danmoseley , maybe this is an unreleased version, the output is:
```
$ dotnet publish
Microsoft (R) Build Engine version 17.0.0-preview-21515-03+d66a44095 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
/home/ivan_wl/devel/dotnet/test_project_60/test_project.csproj : error NU1102: Unable to find package Microsoft.NETCore.App.Runtime.linux-x64 with version (= 6.0.0-rtm.21515.9)
/home/ivan_wl/devel/dotnet/test_project_60/test_project.csproj : error NU1102:   - Found 63 version(s) in nuget.org [ Nearest version: 6.0.0-rc.2.21480.5 ]
/home/ivan_wl/devel/dotnet/test_project_60/test_project.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.App.Runtime.linux-x64 with version (= 6.0.0-rtm.21515.15)
/home/ivan_wl/devel/dotnet/test_project_60/test_project.csproj : error NU1102:   - Found 65 version(s) in nuget.org [ Nearest version: 6.0.0-rc.2.21480.10 ]
  Failed to restore /home/ivan_wl/devel/dotnet/test_project_60/test_project.csproj (in 1.2 sec).
```

**Comment by richlander** [comment] 2023-02-13 00:01
I re-opened this since I was seeing unexpected behavior. After a code review, I saw that my code was wrong. Oops!

Working on some samples at https://github.com/dotnet/dotnet-docker/pull/4414

**Closed by richlander** 2023-02-13 00:01 UTC
Labels: needs-further-triage, area-System.DateTime
