### ISSUE TITLE
Test Failure SetOut.SetOutReadToEnd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#59008] opened 2021-09-13 01:40 UTC
Run: [runtime 20210912.16](https://dev.azure.com/dnceng/public/_build/results?buildId=1358036&view=ms.vss-test-web.build-test-results-tab&runId=39694154&resultId=115571&paneView=debug)

Failed test:
```
net7.0-Linux-Release-x64-mono_interpreter_release-(Debian.10.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-amd64-20210304164434-56c6673

- SetOut.SetOutReadToEnd

```
**Error message:**
```
Assert.Equal() Failure
↓ (pos 4)
Expected: Test
Actual:   Test      Condition(s) not met: "TermIsSet"\n
↑ (pos 4)


Stack trace
   at Helpers.SetAndReadHelper(Action`1 setHelper, Func`1 getHelper, Func`2 readHelper) in /_/src/libraries/System.Console/tests/Helpers.cs:line 30
   at SetOut.SetOutReadToEnd() in /_/src/libraries/System.Console/tests/SetOut.cs:line 34
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 370
```

Runfo Tracking Issue: [setout.setoutreadtoend](https://runfo.azurewebsites.net/tracking/issue/172)
|Build|Definition|Kind|Run Name|Console|Core Dump|Test Results|Run Client|
|---|---|---|---|---|---|---|---|
|[1393532](https://dev.azure.com/dnceng/public/_build/results?buildId=1393532)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 59773](https://github.com/dotnet/runtime/pull/59773)|net7.0-Linux-Debug-x64-Mono_release-(Centos.8.Amd64.Open)Ubuntu.1604.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:centos-8-helix-20201229003624-c1bf759|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-59773-merge-d9e500b6bad14ed7a7/System.Console.Tests/1/console.7f6bd49a.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-10-19T21%25253A17%25253A23Z%2526sr%253Dc%2526sp%253Drl%2526sig%253Dt3G0YndDYAi6iROSvUhi1i40imENurj0XxSeTbThuX8%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-59773-merge-d9e500b6bad14ed7a7/System.Console.Tests/be7539d9-798f-46c1-85ba-7028bf012ce7.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-10-19T21%25253A17%25253A23Z%2526sr%253Dc%2526sp%253Drl%2526sig%253Dt3G0YndDYAi6iROSvUhi1i40imENurj0XxSeTbThuX8%25253D)|
|[1388364](https://dev.azure.com/dnceng/public/_build/results?buildId=1388364)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 59658](https://github.com/dotnet/runtime/pull/59658)|net7.0-Linux-Debug-x64-Mono_release-(Debian.10.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-amd64-20210304164434-56c6673|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-59658-merge-7f9ac3a0e56e412696/System.Console.Tests/1/console.f9a0d53f.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-10-17T19%25253A59%25253A31Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DOrkv1ZOJuKxN0E1eB%25252FlHNMcy0MEMz5S9cnpgOs9H3C8%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-59658-merge-7f9ac3a0e56e412696/System.Console.Tests/f26a1542-2541-40aa-91a2-ad4434244f31.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-10-17T19%25253A59%25253A31Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DOrkv1ZOJuKxN0E1eB%25252FlHNMcy0MEMz5S9cnpgOs9H3C8%25253D)|
|[1387605](https://dev.azure.com/dnceng/public/_build/results?buildId=1387605)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|[PR 59543](https://github.com/dotnet/runtime/pull/59543)|net7.0-OSX-Debug-x64-Mono_release-OSX.1015.Amd64.Open|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-59543-merge-10921119376842fdb0/System.Console.Tests/1/console.db406b92.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-10-17T13%25253A43%25253A13Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DE292c0eEtMr%25252B29HsG2Y18j1SZ8h89XEFt9hmKIzVC%25252Bo%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-59543-merge-10921119376842fdb0/System.Console.Tests/ba8b60d9-8209-46fd-b5eb-00f76aefcf67.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-10-17T13%25253A43%25253A13Z%2526sr%253Dc%2526sp%253Drl%2526sig%253DE292c0eEtMr%25252B29HsG2Y18j1SZ8h89XEFt9hmKIzVC%25252Bo%25253D)|
|[1386588](https://dev.azure.com/dnceng/public/_build/results?buildId=1386588)|[runtime](https://dnceng.visualstudio.com/public/_build?definitionId=686)|Rolling|net7.0-Linux-Release-x64-mono_interpreter_release-(Debian.10.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-amd64-20210304164434-56c6673|[console.log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-1c8a598e92f6473393/System.Console.Tests/1/console.a967c9af.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-10-15T23%25253A36%25253A32Z%2526sr%253Dc%2526sp%253Drl%2526sig%253Dn3a3dFxUXMBqSupnOXo15X%25252BO58XblPIy3sC7brMBIZA%25253D)|||[runclient.py](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-1c8a598e92f6473393/System.Console.Tests/74b222c6-f178-42db-8e1c-936edb3ec1f4.log?%3F%253Fsv%253D2019-07-07%2526se%253D2021-10-15T23%25253A36%25253A32Z%2526sr%253Dc%2526sp%253Drl%2526sig%253Dn3a3dFxUXMBqSupnOXo15X%25252BO58XblPIy3sC7brMBIZA%25253D)|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|0|1|4|

**Comment by ViktorHofer** [comment] 2021-09-28 13:15
@dotnet/area-system-console apparently this test is failing multiple times per week. Can you please take a look and eventually disable the test?

**Comment by krwq** [comment] 2021-10-05 09:20
is this a dup of https://github.com/dotnet/runtime/issues/57935 ?

**Comment by carlossanlop** [comment] 2021-10-05 14:09
Duplicate of #57935

**Closed by carlossanlop** 2021-10-05 14:09 UTC
Labels: area-System.Console, os-linux, arch-x64, blocking-clean-ci, runtime-mono
