### ISSUE TITLE
[iOS][tvOS] Generic math IntPtr SByte and Int16 test failures

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#61920] opened 2021-11-22 16:02 UTC
The following generic math tests fail on iOS/tvOS devices:

IntPtrTests:
- CreateSaturatingFromSByteTest
- CreateSaturatingFromInt16Test
- CreateTruncatingFromSByteTest
- CreateTruncatingFromInt16Test
- TryCreateFromSByteTest
- TryCreateFromInt16Test

Each failure is due to actual results being positive when it's expected they are negative.

For example:
```
TryCreateFromSByteTest()

Expected: -128
Actual: 128
```

**Comment by vargaz** [comment] 2021-11-24 10:24
Are these failures with AOT ?

**Comment by steveisok** [comment] 2021-11-24 11:26
> Are these failures with AOT ?
> 
> 

Yes

**Comment by vargaz** [comment] 2022-02-10 20:08
I couldn't reproduce these.

**Comment by imhameed** [comment] 2022-02-11 07:37
I was able to repro this on arm64 Linux (running in the "VMware Fusion for Apple Silicon Public Tech Preview - Fall 2021" on an M1 Mac Mini), so this isn't Apple-specific.

Here's the repro: https://gist.github.com/imhameed/f6ba5663ef2c13dd12fc57f608e1de3d

I built gmath.exe (and System.Private.CoreLib.dll, System.Console.dll, System.Collections.dll, System.Runtime.InteropServices.dll) with `MONO_ENV_OPTIONS="--aot=full,llvm,llvm-path=/put/your/llc/path/here,keep-temps,temp-path=intermediate"`

**Comment by lambdageek** [comment] 2022-04-04 16:43
Tried a draft PR #67542 to see if this is already fixed by #66739

**Closed** 2022-04-05 20:45 UTC
Labels: arch-arm64, area-Codegen-meta-mono, in-pr
