### ISSUE TITLE
`System.Text.Json.Tests` failing due to `Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe'`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#66231] opened 2022-03-05 02:29 UTC
Failing for `Libraries Build windows net48 x86 Release`, hit on unrelated PR https://github.com/dotnet/runtime/pull/66042 .

[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1645913&view=logs&j=79ebbb2e-07f2-5457-c5e5-132dd7ee4ba8&t=160ce0e3-a8e8-5ac5-8623-55bee3c49b38&l=53), and 
[log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-66042-merge-0eb6dd0f84774a4483/System.Text.Json.Tests/1/console.a56fc067.log?sv=2019-07-07&se=2022-03-24T21%3A42%3A07Z&sr=c&sp=rl&sig=qNwd5zi0eVxquRAqCjnkFYQvwiq6eEQkwZCuHA1Y00I%3D).

`System.Text.Json.Serialization.Tests.CustomConverterTests.GetConverter_Poco_WriteThrowsNotSupportedException`:

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.Span`1..ctor(T[] array, Int32 start, Int32 length)
   at System.Text.Json.PooledByteBufferWriter.Dispose()
   at System.Text.Json.JsonSerializer.WriteStringUsingSerializer[TValue](TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Tests.CustomConverterTests.<>c.<GetConverter_Poco_WriteThrowsNotSupportedException>b__321_0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args)
    System.Text.Json.Serialization.Tests.CustomConverterTests.GetConverter_Poco_WriteThrowsNotSupportedException [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:
        
        Child exception:
          System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
        File name: 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
           at System.Span`1..ctor(T[] array, Int32 start, Int32 length)
           at System.Text.Json.PooledByteBufferWriter.Dispose()
           at System.Text.Json.JsonSerializer.WriteStringUsingSerializer[TValue](TValue& value, JsonTypeInfo jsonTypeInfo)
           at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
           at System.Text.Json.Serialization.Tests.CustomConverterTests.<>c.<GetConverter_Poco_WriteThrowsNotSupportedException>b__321_0()
        
        WRN: Assembly binding logging is turned OFF.
        To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
        Note: There is some performance penalty associated with assembly bind failure logging.
        To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
        
        
        Child process:
          System.Text.Json.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Text.Json.Serialization.Tests.CustomConverterTests+<>c Void <GetConverter_Poco_WriteThrowsNotSupportedException>b__321_0()
```

Same failure for `System.Text.Json.Serialization.Tests.CacheTests.JsonSerializerOptions_ReuseConverterCaches` too.

**Comment by jkotas** [comment] 2022-03-05 06:49
Duplicate of #66232

**Closed by jkotas** 2022-03-05 06:49 UTC
Labels: area-System.Text.Json, blocking-clean-ci, untriaged
