### ISSUE TITLE
ARM32-linux: JIT/Directed/tailcall/more_tailcalls/more_tailcalls times out in GCStress runs.

### ISSUE THREAD

**Issue by VSadov** [dotnet/runtime#100464] opened 2024-03-30 23:39 UTC
It also could be the main reason why stress runs take so long. 
Everything is waiting for this test to time out.

A typical failure looks like:
(https://[helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-ae08ee236d7a4991a9/Directed_3.0.1/1/console.93df1637.log?helixlogtype=result](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-ae08ee236d7a4991a9/Directed_3.0.1/1/console.93df1637.log?helixlogtype=result))

```
> /root/helix/work/workitem/e/JIT/Directed/Directed_3/../StructABI/StructABI/StructABI.sh
22:53:28.932 Passed test: JIT/Directed/StructABI/StructABI/StructABI.cmd
22:53:28.987 Running test: JIT/Directed/tailcall/more_tailcalls/more_tailcalls.cmd
Invoking: sudo ls -l /home/helixbot/dotnetbuild/dumps/coredump.228.dmp.crashreport.json
stdout: -rw------- 1 helixbot2 adm 24755 Mar 23 22:53 /home/helixbot/dotnetbuild/dumps/coredump.228.dmp.crashreport.json

=========================================
+ test_exit_code=1
+ dotnet /root/helix/work/correlation/XUnitLogChecker/XUnitLogChecker.dll --results-path JIT/Directed/Directed_3 --test-wrapper Directed_3 --dumps-path /home/helixbot/dotnetbuild/dumps
Child process took too long. Timed out... Exiting...
App Exit Code: 110
Expected: 100
Actual: 110
END EXECUTION - FAILED
[XUnitLogChecker]: 03:50:11.03: The full run will be done.
[XUnitLogChecker]: 03:50:11.13: Item 'Directed_3' did not finish running. Checking and fixing the log...
[XUnitLogChecker]: 03:50:11.25: XUnit log file has been fixed!

```

Notice the timing. Started at 22:53:28.987,  timed out at 03:50:11.03

It is possible that the test takes this long with `GCStress=0xC` for a valid reason, then it should be excluded.

**Comment by VSadov** [comment] 2024-03-30 23:53
Without stress `more_tailcalls` seems to run as fast as many other JIT tests. 
< 0.1 second on a fast machine

**Comment by AndyAyersMS** [comment] 2024-04-01 17:20
@jakobbotsch should we exempt this from gc stress?

**Comment by jakobbotsch** [comment] 2024-04-02 12:10
Duplicate of #99410? According to Bruce this started recently, so we should investigate.

**Comment by VSadov** [comment] 2024-04-02 17:54
Yes, looks like a duplicate. It is pretty annoying though that it is not a fail, but a time out. A run that could complete in an hour or two now takes 6 hours.

**Comment by VSadov** [comment] 2024-04-02 17:59
I think the first failure was seen on March 3. The previous run of `gcstress0x3-gcstress0xc` (on Feb 10) was completely green. Something got broken in between.

**Comment by jakobbotsch** [comment] 2024-04-02 18:00
I opened #100540 to disable the test under GC stress for now to remove the blocking status.

**Comment by jakobbotsch** [comment] 2024-04-02 18:06
> I think the first failure was seen on March 3. The previous run of `gcstress0x3-gcstress0xc` (on Feb 10) was completely green. Something got broken in between.

According to Bruce in #99410 the first failure was on March 2nd. Note that we don't have history more than a month back. He tagged @janvorli so maybe this particular run was the first after new EH was enabled? Do you remember why you tagged Jan @BruceForstall?

**Comment by janvorli** [comment] 2024-04-02 19:09
The enabling of the new EH was merged on March 12, so it is not related to it being enabled.

**Comment by BruceForstall** [comment] 2024-04-03 21:38
> Do you remember why you tagged Jan @BruceForstall?

I tag Jan for many non-obvious Linux arm32 gcstress because of his expertise in the area.

**Comment by jakobbotsch** [comment] 2024-04-04 08:44
Duplicate of #99410

**Closed by jakobbotsch** 2024-04-04 08:44 UTC
Labels: area-CodeGen-coreclr
