### ISSUE TITLE
Problem with Program build in Visual Studio for ARM

### ISSUE THREAD

**Issue by jogibear9988** [dotnet/runtime#103685] opened 2024-06-19 07:42 UTC
### Description

We have a Program wich runs TT templates wich is forked from Mono (Cause the one delivered with Visual Studio still does not use NetCore) (https://github.com/dotnetprojects/SubSonic.Core.TextTemplating).
The Problem now is, if we build it on Windows X64, we can use it to Parse the Templates on Windows, but not on Windows fro ARM. Same is true for Windows for ARM, If we build it there, it is not usable on WIndows.
As we build for "Any CPU" the Files should work on both (I think), but they do not.

I've compared the exe files via: [Info](https://penet.io/)
I've created a small Tool to compare the DLL headers: https://github.com/dotnetprojects/DotNetFileInfo

The DLLs seem to be the same, but the exe's are different:

See the Screenshots with the differences:

The Visual Studio X64 Build:
<img width="1155" alt="image" src="https://github.com/dotnet/runtime/assets/364896/19dd951f-cd84-4cca-8812-cb6da555cade">

The Visual Studio for ARM Build:
<img width="1177" alt="image" src="https://github.com/dotnet/runtime/assets/364896/d031f74c-567c-430a-822f-1ef62f7a3115">

### Reproduction Steps

Compile the Project in Visual Studio X64 and compile another one in Visual Studio ARM.

### Expected behavior

The Projects should be the same

### Actual behavior

The Projects are different

**Comment by huoyaoyuan** [comment] 2024-06-19 07:55
Looks similar to #63144

The screen shot you are showing are about executable files, not the managed assembly. In .NET Core there's no longer AnyCPU exe.

**Comment by jogibear9988** [comment] 2024-06-19 08:06
I know that they are of exe files: "The DLLs seem to be the same, but the exe's are different".

yes seams to be the same issue...

**Comment by vitek-karas** [comment] 2024-06-19 17:46
This is a duplicate of https://github.com/dotnet/runtime/issues/63144.

.NET 6+ doesn't have the ability to produce an executable which works on multiple architectures, unlike .NET Framework.

**Closed by vitek-karas** 2024-06-19 17:46 UTC
Labels: area-Host, untriaged, needs-area-label
