### ISSUE TITLE
System.Text.Json The JSON property name for collides with another property.

### ISSUE THREAD

**Issue by dracos1993** [dotnet/runtime#37769] opened 2020-06-11 21:24 UTC
I am migrating from using Newtonsoft to the native Json library in .Net Core 3.1. One of my objects has two properties with same name but different casing, as below.

"City": "Pittsburgh",
"city": "Pittsburgh"

While serializing, I am getting the "The JSON property name for collides with another property." error. Newtonsoft seems to be handling this fine or at the very least it seems to be serializing it as it is. Is this possible in System.Text.Json? I am using v4.7.0

Edit: It looks like explicitly setting PropertyNameCaseInsensitive to false solved the issue for me, but I thought this was the default setting.

**Comment by bbartels** [comment] 2020-06-12 04:48
It's intentional behaviour, see https://github.com/dotnet/runtime/issues/34255

**Comment by dracos1993** [comment] 2020-06-13 15:56
Not sure how you say it's intentional based on #34255.  Just to reiterate, I want the PropertyNameCaseInsensitive setting to be false, and both the docs and #34255 suggest that, that should be the default value.

I have no issues when I serialize something inside my code, like below

`var address = JsonSerializer.Deserialize<Address>(content);`

I am getting the JSON error when I try to serialize my object when returning a response from my controller action, like below

`return Ok(address)`

To rectify this, I'm having to set PropertyNameCaseInsensitive to false in my startup file, like below

`services.AddControllers().AddJsonOptions(options =>
{
        options.JsonSerializerOptions.PropertyNamingPolicy = null;
        options.JsonSerializerOptions.PropertyNameCaseInsensitive = false;
});`

Why am I having to set it to false explicitly, when it should be false by default?

**Comment by Clockwork-Muse** [comment] 2020-06-13 16:21
.... as a side note, _why_ do you have two properties only different by casing?  As a personal preference, I'd consider that erroneous in some fashion, and try to remove it...

**Comment by dracos1993** [comment] 2020-06-13 16:36
I agree @Clockwork-Muse, but unfortunately I can't do that as I am working on an API migration and everything needs to be the same as the old one, and that includes models.

**Comment by bbartels** [comment] 2020-06-14 08:27
Ah I see, I misunderstood. 
Looking at the implementation it seems like the default is indeed false if the JsonSerializerDefaults parameter is not set to `Web`. https://github.com/dotnet/runtime/blob/67d74fca70d4670ad503e23dba9d6bc8a1b5909e/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs#L96-L98 . Seems to be intended as the comment suggests.(https://github.com/dotnet/runtime/blob/master/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerDefaults.cs#L19-L25)
Not sure about motivation though.

**Comment by dracos1993** [comment] 2020-06-14 11:00
Ah, thanks @bbartels, that explains it. https://github.com/dotnet/runtime/blob/67d74fca70d4670ad503e23dba9d6bc8a1b5909e/src/libraries/System.Text.Json/docs/ParameterizedCtorSpec.md has the following line in it, 

"ASP.NET default settings of camelCase casing (and case-insensitivity) will work fine without needing extra configuration."

which seems to suggest that is the default for asp.net. Not sure where I can find the documentation for that. Anyway I guess this can be closed then. Not sure if there is a case to update the tooltip text that Visual Studio shows for the `PropertyNameCaseInsensitive` property

**Comment by layomia** [comment] 2020-06-19 00:04
> which seems to suggest that is the default for asp.net. Not sure where I can find the documentation for that.

There is some documentation about this here: https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to#case-insensitive-deserialization.

JsonSerializer defaults (Pascal-case property naming policy, and case-sensitive property name matching): optimized for conformance with C# property naming guidelines, and performance. FWIW - there used to be a wide performance gulf between sensitive and insensitive matching, but it's minimal now following https://github.com/dotnet/runtime/pull/35848.

ASP.NET defaults (Camel-case property naming policy, and case-insensitive property name matching): optimized for common JSON formatting patterns in the .NET ecosystem. 

---

@dracos1993, can you share the type (sanitized if needed) that you are trying to serialize, along with any attributes, and what the call to the serializer looks like?

**Comment by layomia** [comment] 2020-07-07 17:51
Closing as the issue here was because of property name conflicts due to case-insensitve matching, which is the expected behavior. Please follow up if you still face issues with this.

**Closed by layomia** 2020-07-07 17:51 UTC
Labels: area-System.Text.Json
