### ISSUE TITLE
BrotliEncoder.GetMaxCompressedLength returns invalid value

### ISSUE THREAD

**Issue by TechPizzaDev** [dotnet/runtime#35142] opened 2020-04-17 23:06 UTC
![image](https://user-images.githubusercontent.com/23627133/79620471-4d9fce80-8110-11ea-9577-cb3112dc165b.png)
Project target: netcoreapp3.1

<details>
<summary>Test code</summary>

```csharp
using System;
using System.IO.Compression;

namespace Sandbox
{
    class Program
    {
        static void Main(string[] args)
        {
            const int quality = 5;
            const int window = 10;

            byte[] source = new byte[256000];
            var rng = new Random(1234);
            rng.NextBytes(source);

            int maxLength = BrotliEncoder.GetMaxCompressedLength(source.Length);
            var resultBuffer = new byte[maxLength + 10];

            if (!BrotliEncoder.TryCompress(
                source, resultBuffer, out int written1, quality, window))
                throw new Exception();

            if (!BrotliEncoder.TryCompress(
                source, resultBuffer.AsSpan(0, maxLength), out int written2, quality, window))
                throw new Exception();
        }
    }
}
```
</details>

<details>
<summary>dotnet --info</summary>

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
</details>

**Comment by lcsondes** [comment] 2020-08-14 14:15
Just hit this one in my code, can confirm. I'm getting a compressed buffer (using `new BrotliEncoder(9, 22).Compress(...)`) of 0x0040000c length (the input is exactly 0x00400000 bytes) when the expected maximum is 0x00400007.

**Comment by danmosemsft** [comment] 2020-08-14 14:47
Interested in debugging some @lcsondes ?

**Comment by lcsondes** [comment] 2020-08-14 14:55
@danmosemsft What do you need?

**Comment by danmosemsft** [comment] 2020-08-14 15:12
@lcsondes it may be some time before someone can take a look, so sometimes I ask folks whether they’re interested in investigating to figure out the root cause.

**Comment by lcsondes** [comment] 2020-08-14 15:25
From skimming the source my best guess is [this line](https://github.com/dotnet/runtime/blob/master/src/libraries/System.IO.Compression.Brotli/src/System/IO/Compression/enc/BrotliEncoder.cs#L105) hardcoding the largest possible large block size while the BrotliEncoder constructor lets you select any window size. The guesswork here is whether the two are related, RFC 7932 doesn't seem to talk about large blocks but it does mention meta-blocks that have a variable size which just so happens to range between 0 and 16M and its header contains the size of the window so there could be a connection.

On the other hand if I take my input size which is 4M, 4M>>24 is 0 (which also looks incorrect BTW, surely there must be at least one block if the input is meaningful?) but that only explains 4 bytes of difference. The most I've observed was 6.

**Comment by neuecc** [comment] 2022-12-08 07:37
I've encounted same issue.
brotli/encode.c has `BrotliEncoderMaxCompressedSize` method, that returns different value of current C# impl.
https://github.com/google/brotli/blob/3914999fcc1fda92e750ef9190aa6db9bf7bdb07/c/enc/encode.c#L1200
I've port this code to C# and compare result.

```csharp
int BrotliEncoderMaxCompressedSize(int input_size)
{
    var num_large_blocks = input_size >> 14;
    var overhead = 2 + (4 * num_large_blocks) + 3 + 1;
    var result = input_size + overhead;
    if (input_size == 0) return 2;
    return (result < input_size) ? 0 : result;
}
```

My test data,

|  |  |
|----|---- |
| Input |                                                  10000005 byte |
| GetMaxCompressedLength         |      10000012 byte |
| BrotliEncoderMaxCompressedSize |      10002451 byte |
| Compressed                                   |    10000021 byte|

I think this is critical issue of compression library, could you fix it?

**Comment by neuecc** [comment] 2023-07-23 19:32
@carlossanlop 
.NET 8 doesn't seem to have any changes, should this remain a TODO?

**Comment by lcsondes** [comment] 2023-07-31 15:23
For the poor souls who are still affected by this, I recommend switching over to zstd, which is unaffected by this bug, and generally has a better runtime performance and compression ratio.

It's unlikely that this one will be fixed in anytime soon, it's been open for more than 3 years.

**Comment by neuecc** [comment] 2024-09-12 10:33
.NET 9 RC1 supports new BrotliCompressionOptions in #105430 , however this bug is not cared,
I've tested in latest VS-preview but still exists.
@buyaa-n , @carlossanlop , @stephentoub (mentioned to #105430 reviewers)

**Comment by buyaa-n** [comment] 2024-09-16 16:15
> .NET 9 RC1 supports new BrotliCompressionOptions in https://github.com/dotnet/runtime/pull/105430 , however this bug is not cared,

That was not about for fixing this issue.

Anyway the managed implementation of `GetMaxCompressedLength(int inputSize)` was the same as the native implementation until [Update brotli to v1.0.5](https://github.com/dotnet/corefx/pull/30751/files#diff-5c26c35d7c01b641d78bdf9e3541140819598c2c7f5c4b7ad28db70c06f3fa99R1388-R1394). Wonder why did not use the native implementation directly, anyway this is a regression happened a few years back. 

Question is how to fix it:
- Should we just apply the native changes to the managed implementation
- Or should we update it to call native method directly (it could prevent from similar issue happen again) 

CC @carlossanlop @ericstj @stephentoub

**Comment by stephentoub** [comment] 2024-09-16 16:26
> Should we just apply the native changes to the managed implementation
> Or should we update it to call native method directly (it could prevent from similar issue happen again)

Let's just P/Invoke to the native implementation, since it's the source of truth, and this size needs to remain in sync with what the encoder actually does.

**Comment by ericstj** [comment] 2024-09-17 16:38
@buyaa-n you marked this as `regression-from-last-release` - is this bug tracking a regression made in .NET 9.0?

**Comment by buyaa-n** [comment] 2024-09-17 17:32
> @buyaa-n you marked this as `regression-from-last-release` - is this bug tracking a regression made in .NET 9.0?

No, it's regression from several releases, just there were no other label with `regression`

**Comment by TechPizzaDev** [comment] 2024-09-17 19:04
It was introduced with .NET Core 3.0 judging by the mentioned brotli 1.0.5 update in *2018*.

I'm also surprised the milestone was set to .NET 10 considering this is a fix, not a new feature. 
.NET 9 should still receive it even if it's in RC phase now, but maybe it's too low priority considering no one asked for a backport to previous LTS versions.

**Comment by buyaa-n** [comment] 2024-09-19 23:41
> I'm also surprised the milestone was set to .NET 10 considering this is a fix, not a new feature.

Currently all PRs should go to main (10.0), based on the customer feedback and the risk of the fix management will decide if we port the fix to previous versions and which versions will get fixed

**Closed** 2024-10-08 16:54 UTC
Labels: area-System.IO.Compression, in-pr
