### ISSUE TITLE
[API Proposal]: Add JsonOptional attribute for properties that may or may not be present when serialized/deserialized.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/runtime#74285] opened 2022-08-19 23:51 UTC
### Background and motivation

I did not see this proposed before but I feel like there should be an JsonOptional attribute for data in the json that may not be provided at all in some situations (like web requests for example might contain some optional json response fields in the json response).

Web based API services that I know of that do this:
- Discord (yes the Discord API does this)
- GitHub? (I am not sure on github's api but I assume they probably do it as well)
- etc (there is more I cant think of from the top of my head that I might use on a daily basis)

Why this and not an converter?

- Well it was discovered that the converters used in Remora.Discord are not great in terms of memory usage and performance, unlike a version that could have been implemented into System.Text.Json itself.
- Converters are not supported when using the System.Text.Json source generator (even more reason for this proposal when you need something like this).
- Simplicity, In terms of maintainability, an attribute is more maintainable than an custom converter is due to all the goes into them.

### API Proposal

```csharp
namespace System.Text.Json.Serialization;

/// <summary>
/// Prevents a property or field from being serialized or deserialized when it's not provided in the json.
/// </summary>
[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field, AllowMultiple = false)]
public sealed class JsonOptionalAttribute : JsonAttribute
{
    /// <summary>
    /// Initializes a new instance of <see cref="JsonOptionalAttribute"/>.
    /// </summary>
    public JsonOptionalAttribute() { }
}
```

### API Usage

```csharp
public class JsonExample
{
    [JsonPropertyName(nameof(Required))]
    public string Required { get; set; }

    // a value in the json that is optional, that is the entire item might not appear in the
    // json itself vs json that provides it but sets it to null or default.
    // This is why JsonIgnore is not enough for this as it is unclear if it would work for such a case.
    [JsonPropertyName(nameof(Optional))]
    [JsonOptional]
    public Optional<string?> Optional { get; set; }
}
```

### Alternative Designs

Converters, however that is not an option when using source generation and so this would be an better option instead.

### Risks

Minimal, I think that is.

**Comment by eiriktsarpalis** [comment] 2022-08-20 07:38
What would be the expected behavior of such an attribute? By default, STJ treats all properties as optional. In other words, if I tried to deserialize `{}` with your `JsonExample` class it would succeed and both `Required` and `Optional` would be null.

.NET 7 will incorporate a `JsonRequiredAttribute` (and support for the new `required` C# keyword), but I don't see why there might be a need for an "optional" setting, since that's the default.

**Comment by AraHaan** [comment] 2022-08-20 07:46
I see, well for Discord optional, and ``null`` are different values where ``null`` means to remove something, while the not-present side means to ``do nothing``.

**Comment by eiriktsarpalis** [comment] 2022-08-20 11:27
I see. I'm still not sure how the proposed attribute is meant to help in such a case, a more detailed example might be in order.

From a property binding perspective, the serializer does not distinguish between an explicit `null` in the JSON and a missing property, but it should be possible to do it using a custom converter for a hypothetical `Optional<T>` type:
```C#
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

var options = new JsonSerializerOptions { Converters = { new OptionalConverterFactory()} };

MyPoco result = JsonSerializer.Deserialize<MyPoco>("{}", options);
Console.WriteLine(result.Value is null);
result = JsonSerializer.Deserialize<MyPoco>("{ \"Value\" : null}", options);
Console.WriteLine(result.Value is None<string>);
result = JsonSerializer.Deserialize<MyPoco>("{ \"Value\" : \"string\"}", options);
Console.WriteLine(result.Value is Some<string>);

public class MyPoco
{
	public Optional<string> Value {get;set;}
}
					
public abstract record Optional<T>();
public sealed record None<T>() : Optional<T>();
public sealed record Some<T>(T value) : Optional<T>();

public sealed class OptionalConverterFactory : JsonConverterFactory
{
    public override bool CanConvert(Type t) => t.IsGenericType && typeof(Optional<>) == t.GetGenericTypeDefinition();
	public override JsonConverter CreateConverter(Type t, JsonSerializerOptions options)
	{
	     Type convType = typeof(OptionalConverter<>).MakeGenericType(t.GetGenericArguments()[0]);
		 return (JsonConverter)Activator.CreateInstance(convType)!;
	}
}

public sealed class OptionalConverter<T> : JsonConverter<Optional<T>>
{
    public override bool HandleNull => true;
	
    public override void Write(Utf8JsonWriter writer, Optional<T> value, JsonSerializerOptions options)
	{
	    switch (value)
		{
		    case null:
			case None<T>:
			    writer.WriteNullValue();
				break;
			case Some<T> { value : T val }:
				JsonSerializer.Serialize(writer, val, options);
				break;
		}
	}
	
	public override Optional<T> Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
	{
	    switch (reader.TokenType)
		{
		    case JsonTokenType.Null:
				return new None<T>();
			default:
				return new Some<T>(JsonSerializer.Deserialize<T>(ref reader, options));
		}
	}
}
```

**Comment by AraHaan** [comment] 2022-08-20 23:55
> I see. I'm still not sure how the proposed attribute is meant to help in such a case, a more detailed example might be in order.
> 
> From a property binding perspective, the serializer does not distinguish between an explicit `null` in the JSON and a missing property, but it should be possible to do it using a custom converter for a hypothetical `Optional<T>` type:
> 
> ```cs
> using System;
> using System.Text.Json;
> using System.Text.Json.Serialization;
> 
> var options = new JsonSerializerOptions { Converters = { new OptionalConverterFactory()} };
> 
> MyPoco result = JsonSerializer.Deserialize<MyPoco>("{}", options);
> Console.WriteLine(result.Value is null);
> result = JsonSerializer.Deserialize<MyPoco>("{ \"Value\" : null}", options);
> Console.WriteLine(result.Value is None<string>);
> result = JsonSerializer.Deserialize<MyPoco>("{ \"Value\" : \"string\"}", options);
> Console.WriteLine(result.Value is Some<string>);
> 
> public class MyPoco
> {
>     public Optional<string> Value {get;set;}
> }
>                     
> public abstract record Optional<T>();
> public sealed record None<T>() : Optional<T>();
> public sealed record Some<T>(T value) : Optional<T>();
> 
> public sealed class OptionalConverterFactory : JsonConverterFactory
> {
>     public override bool CanConvert(Type t) => t.IsGenericType && typeof(Optional<>) == t.GetGenericTypeDefinition();
>     public override JsonConverter CreateConverter(Type t, JsonSerializerOptions options)
>     {
>          Type convType = typeof(OptionalConverter<>).MakeGenericType(t.GetGenericArguments()[0]);
>          return (JsonConverter)Activator.CreateInstance(convType)!;
>     }
> }
> 
> public sealed class OptionalConverter<T> : JsonConverter<Optional<T>>
> {
>     public override bool HandleNull => true;
>     
>     public override void Write(Utf8JsonWriter writer, Optional<T> value, JsonSerializerOptions options)
>     {
>         switch (value)
>         {
>             case null:
>             case None<T>:
>                 writer.WriteNullValue();
>                 break;
>             case Some<T> { value : T val }:
>                 JsonSerializer.Serialize(writer, val, options);
>                 break;
>         }
>     }
>     
>     public override Optional<T> Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
>     {
>         switch (reader.TokenType)
>         {
>             case JsonTokenType.Null:
>                 return new None<T>();
>             default:
>                 return new Some<T>(JsonSerializer.Deserialize<T>(ref reader, options));
>         }
>     }
> }
> ```

And that won't conflict with the source generator at all?

**Comment by eiriktsarpalis** [comment] 2022-08-21 09:40
I wouldn't think so, the source generator does honor custom converters.

**Comment by AraHaan** [comment] 2022-08-21 09:49
So it’s docs about it not supporting them in the optimized mode is wrong then?

**Comment by eiriktsarpalis** [comment] 2022-08-21 09:55
I would need to double check with fast path serialization, metadata mode should work just fine though.

**Comment by eiriktsarpalis** [comment] 2022-08-21 09:56
I'd be inclined to close this, still not sure I understand what the proposed behavior of `JsonOptionalAttribute` should be compared to the default.

**Comment by AraHaan** [comment] 2022-08-22 02:35
For some things in S.T.J it might consider optional to be 2 states ``null`` or ``not null``. However many people might need 3 states, null, not present, and not null. Where not present makes people know that "the previous value was not changed, but to minimize network usage we did not provide it at all." vs "The previous value is no longer valid and so we send you null for it to clear it out in your cache.", etc.

I guess another option would be to propose this type of ``Optional<T>`` into System.dll for .NET 8+ for users who need to use this for special cases (I could see S.T.J being a special case on this as well too).

**Comment by eiriktsarpalis** [comment] 2022-08-22 08:26
> For some things in S.T.J it might consider optional to be 2 states null or not null. However many people might need 3 states, null, not present, and not null. Where not present makes people know that "the previous value was not changed, but to minimize network usage we did not provide it at all." vs "The previous value is no longer valid and so we send you null for it to clear it out in your cache.", etc.

I do get that, what I don't understand is how might an attribute influence the differentiation between the two states (explicit null vs missing property)? How would it change behavior vs a property without the attribute? Can you share an example?

> I guess another option would be to propose this type of Optional<T> into System.dll for .NET 8+ for users who need to use this for special cases (I could see S.T.J being a special case on this as well too). It could provide an optional converter by default in that case.

Most optional types that I know of don't differentiate between explicit null and missing values (e.g. this is true with how Json.NET or this library handle `Nullable<T>` or F#'s optional type). So I don't think this is something we could hardcode for popular types, you would still need to write your own converter.

**Comment by krwq** [comment] 2022-08-22 09:29
FYI if you use (.NET 7 preview 7 or latest preview NuGet package required):

```csharp
using System.Text.Json;
using System.Text.Json.Serialization.Metadata;

namespace JsonExplicitNullVsNothing
{
    internal class Program
    {
        static void Main(string[] args)
        {
            JsonSerializerOptions options = new()
            {
                TypeInfoResolver = new DefaultJsonTypeInfoResolver()
                {
                    Modifiers = { DistinguishExplicitSetForMyClassValueModifier }
                }
            };

            string json = "{\"Value\":null}";
            MyClass obj = JsonSerializer.Deserialize<MyClass>(json, options)!;
            Console.WriteLine($"Value = {(obj.Value ?? "<null>")}, ExplicitlySet? = {obj.ValueIsExplicitlySet}");
            // Value = <null>, ExplicitlySet? = True

            json = "{}";
            obj = JsonSerializer.Deserialize<MyClass>(json, options)!;
            Console.WriteLine($"Value = {(obj.Value ?? "<null>")}, ExplicitlySet? = {obj.ValueIsExplicitlySet}");
            // Value = <null>, ExplicitlySet? = False
        }

        static void DistinguishExplicitSetForMyClassValueModifier(JsonTypeInfo typeInfo)
        {
            if (typeInfo.Type == typeof(MyClass))
            {
                // note: we assume typeInfo.Properties has exactly one property (Value) from JSON perspective
                JsonPropertyInfo property = typeInfo.Properties[0];
                property.Set = (obj, val) =>
                {
                    MyClass myClass = (MyClass)obj;
                    myClass.Value = (string?)val;
                    myClass.ValueIsExplicitlySet = true;
                };
            }
        }
    }

    public class MyClass
    {
        internal bool ValueIsExplicitlySet { get; set; }

        public string? Value { get; set; }
    }
}
```

you might be possibly achieve what you want but I agree with @eiriktsarpalis that you'd need to clarify what would JsonOptionalAttribute do.

**Comment by krwq** [comment] 2022-08-22 10:07
Here is more generic solution, example `Optional<T>` implementation:

```csharp
using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization.Metadata;

namespace JsonExplicitNullVsNothing
{
    internal class Program
    {
        static void Main(string[] args)
        {
            JsonSerializerOptions options = new()
            {
                TypeInfoResolver = new DefaultJsonTypeInfoResolver()
                {
                    Modifiers = { OptionalSupportModifier }
                }
            };

            string json = "{\"Value\":null,\"OtherValue\":null}";
            MyClass obj = JsonSerializer.Deserialize<MyClass>(json, options)!;
            Console.WriteLine($"Value = {(obj.Value.Value ?? "<null>")}, ExplicitlySet? = {obj.Value.IsAssigned}; OtherValue = {(obj.OtherValue ?? "<null>")}");
            // Value = <null>, ExplicitlySet? = True

            json = "{\"OtherValue\":\"test\"}";
            obj = JsonSerializer.Deserialize<MyClass>(json, options)!;
            Console.WriteLine($"Value = {(obj.Value.Value ?? "<null>")}, ExplicitlySet? = {obj.Value.IsAssigned}; OtherValue = {(obj.OtherValue ?? "<null>")}");
            // Value = <null>, ExplicitlySet? = False

            json = "{\"Value\":\"asd\"}";
            obj = JsonSerializer.Deserialize<MyClass>(json, options)!;
            Console.WriteLine($"Value = {(obj.Value.Value ?? "<null>")}, ExplicitlySet? = {obj.Value.IsAssigned}; OtherValue = {(obj.OtherValue ?? "<null>")}");
            // Value = <null>, ExplicitlySet? = True
        }

        static void OptionalSupportModifier(JsonTypeInfo typeInfo)
        {
            if (typeInfo.Kind == JsonTypeInfoKind.Object)
            {
                for (int i = 0; i < typeInfo.Properties.Count; i++)
                {
                    JsonPropertyInfo property = typeInfo.Properties[i];
                    if (property.CustomConverter == null && property.PropertyType.IsGenericType && property.PropertyType.GetGenericTypeDefinition() == typeof(Optional<>))
                    {
                        PropertyInfo propertyInfo = property.PropertyType.GetProperty(nameof(Optional<int>.Value))!;
                        Type[] args = property.PropertyType.GetGenericArguments();

                        JsonPropertyInfo newProperty = typeInfo.CreateJsonPropertyInfo(args[0], property.Name);
                        
                        if (property.Get != null)
                        {
                            if (property.Set == null)
                            {
                                throw new Exception("Optional<T> must be settable, otherwise we will always operate on the copy");
                            }

                            Func<object, object?> originalGetter = property.Get;
                            Action<object, object?> originalSetter = property.Set;
                            newProperty.Get = (obj) => propertyInfo.GetValue(originalGetter(obj));
                            newProperty.Set = (obj, val) =>
                            {
                                object optionalValue = originalGetter(obj);
                                propertyInfo.SetValue(optionalValue, val);
                                originalSetter(obj, optionalValue);
                            };
                        }

                        newProperty.Order = property.Order;
                        // rewrite whatever else stuff you need or throw if something is not compatible

                        typeInfo.Properties[i] = newProperty; 
                    }
                }
            }
        }
    }

    public class MyClass
    {
        public Optional<string?> Value { get; set; }

        // this will produce error:
        // public Optional<string?> ValueWithoutSetter { get; }
        public string? OtherValue { get; set; }
    }

    public struct Optional<T>
    {
        public bool IsAssigned { get; private set; }

        private T _value;
        public T Value
        {
            get => _value;
            set
            {
                _value = value;
                IsAssigned = true;
            }
        }
    }
}
```

**Closed** 2022-08-23 12:27 UTC
Labels: api-suggestion, area-System.Text.Json
