### ISSUE TITLE
TimeSpanConverter should support converting without seconds (hh:mm)

### ISSUE THREAD

**Issue by mvonck** [dotnet/runtime#84405] opened 2023-04-06 08:33 UTC
### Description

When working with a frontend application html input time can be hh:mm when using it in chrome. When the value '10:00' gets deserialized by `System.Text.Json -> TimeSpanConverter`  you will get an error: 'The JSON value could not be converted to System.TimeSpan'.

It should be possible to deserialize a timespan that has no seconds.

### Reproduction Steps

Deserialize '06:00' to TimeSpan leads to error. 

If you add extend the `TimeSpanConverter` unit test you will get this behavior.

src/libraries/System.ComponentModel.TypeConverter/tests/TimeSpanConverterTests.cs
``` csharp
 public override IEnumerable<ConvertTest> ConvertFromTestData()
        {
            yield return ConvertTest.Valid("  1000.00:00:00  ", new TimeSpan(1000, 0, 0, 0, 0), CultureInfo.InvariantCulture);
            yield return ConvertTest.Valid("1000", new TimeSpan(1000, 0, 0, 0, 0));

            // Start extra test cases
            yield return ConvertTest.Valid("10:00," new new TimeSpan(0, 10, 0, 0));
            yield return ConvertTest.Valid("10:01", new new TimeSpan(0, 10, 1, 0));
            // End extra test cases

            yield return ConvertTest.Throws<FormatException>("invalid");
            yield return ConvertTest.Throws<FormatException>("  ");
            yield return ConvertTest.Throws<FormatException>(string.Empty);

            yield return ConvertTest.CantConvertFrom(1);
            yield return ConvertTest.CantConvertFrom(new object());
        }
```

### Expected behavior

Deserialize 10:00 should work with timespan

### Actual behavior

Deserializing 10:00 should lead to `new TimeSpan( 0, 10, 0, 0)`

**Comment by gregsdennis** [comment] 2023-04-06 09:33
`TimeSpan.Parse()` already supports this behavior. Is the serializer not already using this?

**Comment by eiriktsarpalis** [comment] 2023-04-06 09:36
The serializer is intentionally pegging the OOB converter to the ['c' format](https://learn.microsoft.com/en-us/dotnet/standard/base-types/standard-timespan-format-strings). For other formats I would recommend writing a custom converter that suits your requirements.

**Comment by gregsdennis** [comment] 2023-04-06 09:48
Why enforce a specific format? JSON doesn't prescribe anything.

**Comment by eiriktsarpalis** [comment] 2023-04-06 11:07
There's nothing JSON specific about serializing date or time formats, however at the converter level we made the decision to use strict enforcement out of performance and simplicity considerations. This is similar to how the various datetime converters [enforce ISO-8601](https://learn.microsoft.com/en-us/dotnet/standard/datetime/system-text-json-support?pivots=dotnet-7-0#support-for-the-iso-8601-12019-format) when handling dates.

Duplicate of https://github.com/dotnet/runtime/issues/83863

**Closed** 2023-04-11 10:44 UTC
Labels: area-System.Text.Json, untriaged
