### ISSUE TITLE
Linux arm 5.0 launch fails with CORDBG_E_MISSING_DEBUGGER_EXPORTS

### ISSUE THREAD

**Issue by gregg-miskelly** [dotnet/runtime#44745] opened 2020-11-16 17:52 UTC
This issue is from https://github.com/OmniSharp/omnisharp-vscode/issues/4210. Bug report is from @profix898

## Issue Description ##
After deploying a .NET 5 linux-arm app to a Raspberry Pi 4, debugging fails with CORDBG_E_MISSING_DEBUGGER_EXPORTS (0x80131c4f). This doesn't happen with 3.1.

## Steps to Reproduce ##
1. I have created a minimal console project with the following content:

RPiDemo.csproj
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
</Project>
```

Program.cs
```
using System;

namespace RPiDemo
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello RPi!");
        }
    }
}
```
The project is successfully compiled in VS Code on Win 10 x64 using the locally installed .NET 5 SDK. The project is published for 'linux-arm' and copied to the Raspberry Pi 4 (with Raspian 10, latest version as of today) with the following command:

`dotnet publish -c Release -r linux-arm -o ./publish/linux-arm ${workspaceFolder} ; scp -rp -P 2222 ./publish/linux-arm/ root@192.168.81.129:/opt/RPiDemo`

I'm essentially following the instructions at https://github.com/OmniSharp/omnisharp-vscode/wiki/Remote-Debugging-On-Linux-Arm (or similar tutorials on the internet).

The project is then launched on the RPi with the 'vsdbg' remote debugger. My launch.json looks like this:
```
{
    "configurations": [        
        {
            "name": "Launch LOCAL",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceFolder}/bin/Debug/net5.0/RPiDemo.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            "stopAtEntry": false,
            "console": "internalConsole"
        }, 
        {
            "name": "Launch REMOTE",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "BuildPublishCopyLinuxARM",
            "program": "/usr/bin/dotnet",
            "args": [
                "/opt/RPiDemo/RPiDemo.dll"
            ],
            "cwd": "/opt/RPiDemo",
            "stopAtEntry": false,
            "console": "internalConsole",
            "pipeTransport": {
                "pipeCwd": "${workspaceRoot}",
                "pipeProgram": "ssh",
                "pipeArgs": [
                    "-T",
                    "-p", "2222",
                    "root@192.168.81.129"
                ],
                "quoteArgs": true,
                "debuggerPath": "/usr/bin/vsdbg/vsdbg"
            },
            "logging": {
                "engineLogging": true,
                "programOutput": true,
                "exceptions": true
            }
        },
    ]
}
```

## Expected Behavior ##
Debugger should launch and attach to the process on the RPi and provide debug information to VS Code.

## Actual Behavior ##
Debugger prints the following error message: `Unable to attach to CoreCLR. Unknown Error: 0x80131c4f`.
I have then enabled logging via `"engineLogging": true,` to obtain more details (as shown in the log below).

I'd like to note, that the console project works perfectly both locally on the Win 10 x64 host and also **when being launched manually on the RPi via the `dotnet RPiDemo.dll` command (directly in the published directory '/opt/RPiDemo')**.

**Comment by tommcdon** [comment] 2020-11-17 16:51
@hoyosjs

**Comment by krwq** [comment] 2020-11-23 10:22
should this be considered for servicing fix? I'm hearing users not wanting to move to 5.0 because of this

**Comment by Ellerbach** [comment] 2020-11-23 10:36
+1, would be great to see it fixed, debugging is one of the key value of .NET on devices like Raspberry Pi running Linux arm based OS.

**Comment by hoyosjs** [comment] 2020-11-23 10:56
> should this be considered for servicing fix? I'm hearing users not wanting to move to 5.0 because of this

@krwq Do you know if this is just arm linux customers? I was looking at it this past week, but had to prioritize other work. I'll continue this week then.

**Comment by profix898** [comment] 2020-11-23 12:46
From my experience, it is **just Linux ARM**. Even Linux ARM64 works fine.
I switched to the beta version of Raspian 64-bit (and tried Ubuntu 64-bit for Raspberry Pi), on both platforms the debugger works as expected. Note, however, that the 32-bit version is the default/stable branch for RPi.

**Comment by wsad4ryba** [comment] 2020-11-23 13:07
I also encountered this problem. In fact, it's a bit annoying because after the update it turns out that the best solution is to stay with the old version.

**Comment by janvorli** [comment] 2020-11-23 14:25
@hoyosjs just a quick idea. Since it is ARM only, I wonder if it could be yet another case of the address conversion issue that we've hit in the past. I can see that all cases that can fail with that error call GetDacTableAddress that ends up calling TryGetSymbol  in the elfreader.cpp with m_globalBase passed as the base address parameter. That variable is set here:
https://github.com/dotnet/runtime/blob/e8c4f227a31294504cfd51cac3be7cfb900717d5/src/coreclr/src/debug/daccess/daccess.cpp#L5594
I wonder if the problem could be caused by the TO_TADDR being used instead of CLRDATA_ADDRESS to do that conversion.

**Comment by janvorli** [comment] 2020-11-23 14:28
Or the base being already incorrectly sign extended.

**Comment by hoyosjs** [comment] 2020-11-25 22:48
I haven't forgotten this. I just can't seem to repro this. All my remote attaches have been working on a RPi running Raspbian 10.

**Comment by jefflill** [comment] 2020-11-29 01:12
We're seeing the same issue with our Visual Studio [Raspberry Debugger](https://marketplace.visualstudio.com/items?itemName=neonFORGE-LLC.RaspberryDebugger) extension.  We're seeing the same error: **0x80131c4f**

It should be pretty quick for you to install and configure the extension because it handles installing the .NET SDK and vsdbg on the Raspberry and also configures the SSH key pair for you.  Here's our repo and getting started instructions:

https://github.com/nforgeio/RaspberryDebugger

It would be really nice to get this working.

**Comment by hoyosjs** [comment] 2020-11-30 00:19
![image](https://user-images.githubusercontent.com/19413848/100557485-6489d000-325e-11eb-8820-76763c07a4f1.png)

I just tested this again and I am able to attach on 5.0 with no issues on both a RPi 2 and RPi 3 running raspbian 10. However, given this many reports of things failing, there's definitely something that's not working. I copied the programs from the original issue. The files I used in VS Code for the attach are:

<details>
<summary>launch.json</summary>

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch REMOTE",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "BuildPublishCopyLinuxARM",
            "program": "/home/pi/juhoyosa/opt/RPiDemo/RPiDemo",
            "args": [],
            "cwd": "/home/pi/juhoyosa/opt/RPiDemo",
            "stopAtEntry": true,
            "console": "internalConsole",
            "justMyCode": false,
            "pipeTransport": {
                "pipeCwd": "${workspaceRoot}",
                "pipeProgram": "ssh.exe",
                "pipeArgs": [
                    "-T",
                    "pi@diag-pi3"
                ],
                "quoteArgs": true,
                "debuggerPath": "/home/pi/vsdbg/vsdbg"
            },
            "logging": {
                "engineLogging": true,
                "programOutput": true,
                "exceptions": true
            }
        },
    ]
}
```
</details>


<details>
<summary>tasks.json</summary>

```json
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "PublishForRPi",
            "command": "dotnet",
            "type": "shell",
            "args": [
                "publish",
                "-c", "Release",
                "-r", "linux-arm",
                "-o", "./publish/linux-arm",
                "${workspaceFolder}"
            ],
            "group": "build",
            "problemMatcher": "$msCompile"
        },
        {
            "label": "Deploy",
            "type": "shell",
            "command": "scp.exe",
            "args": [
                "-rp",
                "./publish/linux-arm/",
                "pi@diag-pi3:/home/pi/juhoyosa/opt/RPiDemo",
            ],
            "group": "build",
            "presentation": {
                "reveal": "silent"
            },
            "problemMatcher": "$msCompile"
        },
        {
            "label": "BuildPublishCopyLinuxARM",
            "dependsOrder": "sequence",
            "dependsOn": ["PublishForRPi", "Deploy"]
        }
    ]
}
```
</details>

@gregg-miskelly one thing I did notice is that I have to use `justMyCode` for `stopAtEntry` to work. Is this a known issue?

**Comment by gregg-miskelly** [comment] 2020-11-30 04:00
You need to disable justMyCode because you used release confirmation. Publish debug instead for better results (though no idea if that will help making the problem reproduce).

**Comment by gregg-miskelly** [comment] 2020-11-30 04:28
@profix898 looking more closely at your launch.json, are these guesses correct?
1. You are building and running `dotnet publish` on your VS Code machine
2. You have the ARM .NET Runtime installed on your Pi

Is that correct?
When you publish, do you specify, `"-r", "linux-arm"`, or are you publishing your app as framework-dependent?
Does the problem go away if you try Juan's approach of publishing a [self-contained](https://github.com/OmniSharp/omnisharp-vscode/wiki/Remote-Debugging-On-Linux-Arm#self-contained-deployment) project? (note that you want to swap out the `program` in your launch.json if you do this)

**Comment by hoyosjs** [comment] 2020-11-30 05:54
@gregg-miskelly the original post you shared indicated this was a self-contained publish that gets deployed. I had also tried with a fx dependent one, and it worked too. Is it possible that the deployed debugger bits are stale? Or does this one also auto-update? I know if does update under the VS extension, but I don't know what happens when deployed like this. Even with this, I can't think of a recent change in dbgshim that would cause this.

**Comment by janvorli** [comment] 2020-11-30 09:52
@hoyosjs the fact that it works for some people and doesn't work for others might really indicate that it is the address conversion issue I've mentioned above. Maybe that on your device, libcoreclr.so is located at a VA < 0x80000000 while on the failing ones it is >= 0x80000000.

**Comment by hoyosjs** [comment] 2020-11-30 12:45
@janvorli i did consider your comments, sorry. At a quick look i didn't see anything particularly obvious. I can't recall if 5.0 is when we made ensured PIE/PIC on Linux arm. If I can't force to load at a higher address later (need to research it there's some way to achieve this), I'll probably instrument the runtime and request for someone to help here.

**Comment by janvorli** [comment] 2020-11-30 12:58
I'll give it a try on my local device where I have hit the address related issues in the past.
Also, if you are testing it when running the runtime under lldb or gdb, please note that address space randomization is disabled by default under the debugger and you need to explicitly enable it. For lldb, the command is `settings set target.disable-aslr false`

**Comment by hoyosjs** [comment] 2020-11-30 13:16
I did not check if ASLR is disabled OS-wide, though I'd be surprised. I tested this without a native debugger attached. Thanks for checking this @janvorli

**Comment by gregg-miskelly** [comment] 2020-11-30 17:02
@hoyosjs The log that profix898 posted indicates that he is using vsdbg 16.8.11013.1, which is the current shipping version.

**Comment by gregg-miskelly** [comment] 2020-11-30 17:11
@hoyosjs profix898's launch.json has `"program": "/usr/bin/dotnet"` which is a bit odd for a self-contained app, so that is why I was asking to make sure he really was really using a self-contained app.

**Comment by janvorli** [comment] 2020-11-30 17:32
I've tried locally to debug a test app on Linux arm32 using lldb + SOS. I would expect the same problem to occur, as it loads mscordaccore  and accesses libcoreclr symbols. In my case, all code was at addresses >= 0x80000000 including libcoreclr.so, so it seems to invalidate my theory. 
I wonder if it is somehow possible that the debugger tries to load a wrong (outdated) mscordaccore.

**Comment by janvorli** [comment] 2020-11-30 19:20
I will try the original repro steps on my Odroid XU4 ARM32 device and see if I can repro the issue.

**Comment by jefflill** [comment] 2020-12-02 19:04
Is it possible that we're not installing a required Linux package?

The **Raspberry Debugger** only installs **unzip** for its own use (to unzip the program being debugged), but we don't install anything else. There no mention of any required packages in the manual install instructions dor Debian based distros:

https://docs.microsoft.com/en-us/dotnet/core/install/linux-debian#manual-install

**Comment by janvorli** [comment] 2020-12-02 20:15
I was helping @hoyosjs to investigate it yesterday and we have found that it is a bug in our code that occurs only when debugger attempts to get certain data structures from the target process at addresses >= 2GB. For some reason lost in the past even before .NET Core was ported to Linux, we were undefining the _FILE_OFFSET_BITS in the file where the method to read from the remote process is located. That causes the pread function to have 32 bit signed integer as the offset argument (the address is passed in there). So addresses above 2GB were passed in as negative values. Internally, the pread function converts that value to signed 64 bit value that is further passed to the actual pread syscall. So instead of e.g. 0xf75c7000 that our function was passing to pread function, the actual pread syscall was getting 0xfffffffff75c7000, which is a nonsense.
I believe that just keeping the _FILE_OFFSET_BITS defined to 64 as we do for all other parts of our PAL should fix the problem. But @hoyosjs is currently verifying that everything works with that setting.

**Comment by jefflill** [comment] 2020-12-02 20:19
OK, that makes sense.  I'm testing on a Raspberry 4 with 4GiB RAM, so addresses can be > 2GB.

**Comment by microhobby** [comment] 2020-12-07 19:04
I can confirm this by working with Toradex Hardware. .NET 5 projects running in an iMX8QM arm64v8 the debugger attaches without issues, however, using the same source code in an iMX6D arm32v7 (with   2GB RAM) I got:

```
Unable to attach to CoreCLR. Unknown Error: 0x80131c4f
```

We were about to update some templates for our hardware so that customers can switch to .NET 5, but that will have to wait.

**Comment by bjorg** [comment] 2020-12-10 05:23
I take it there are no work arounds for Raspberry Pi 4 w/ 2GB users?

**Comment by hoyosjs** [comment] 2020-12-10 09:03
Sorry, but there's no work around. This is a compile time issue. It's been there for years. The problem is we added a new code path and it hits it very easily on such systems. The change is simple but I've had trouble testing this. I've prepared the PR and the port to 5.0 so I can expedite the process.

**Comment by bjorg** [comment] 2020-12-10 14:47
Happy to help test if it's not too involved since I'm running the affected hardware.

**Comment by hoyosjs** [comment] 2020-12-11 01:46
This has been merged both into master and 5.0. It will be available in the next release.

**Comment by hoyosjs** [comment] 2020-12-11 02:24
> Happy to help test if it's not too involved since I'm running the affected hardware.

Thanks @bjorg. I was doing manual testing, I wanted to load some tests I can't share but was hitting some issues with the loader being unable to find the right libdl, and couldn't find a combination of LD_LIBRARY_PATH and LD_DEBUG that worked or gave me enough info as to why things failed to load. I used the manual testing as enough proof for now and will investigate doing a more comprehensive testing pass.

**Comment by microhobby** [comment] 2020-12-14 06:53
@hoyosjs is this already in the daily installer? Or is there a daily that we can use to test?

**Comment by hoyosjs** [comment] 2020-12-14 07:06
It's not going to be officially released at least until next month. There might be a build which you could use to test things out. How do you build/deploy your app? A shared framework deployment (where the runtime is installed for all apps in the machine)? A self contained app deployment (dotnet publish with a specific runtime identifier)?

**Comment by microhobby** [comment] 2020-12-14 07:08
For debugging we usually run with the shared framework @hoyosjs

**Comment by hoyosjs** [comment] 2020-12-14 07:32
Let me ask if I can share a nightly build of the rolling release and answer tomorrow.

**Comment by hoyosjs** [comment] 2020-12-14 20:54
There's this https://dotnetcli.blob.core.windows.net/dotnet/Runtime/5.0.2-servicing.20611.21/dotnet-runtime-5.0.2-linux-arm.tar.gz. You can extract it and you'll have a shared framework. On the debugger side, you can set the environment variable `DOTNET_ROOT` pointing to that folder and use that `dotnet` executable to ensure you use it. Given that the extracted folder will be called 5.0.2, be really careful to delete it and actually install the release once it actually comes out. This is not a complete release - it's a nightly build and you should use it with caution, there might be bugs as it hasn't gone through all the exit validation processes. It should at least unblock you on debugging as it has the bits that fixed the issue.

**Comment by microhobby** [comment] 2020-12-15 02:57
@hoyosjs ok, got it, thanks

**Comment by microhobby** [comment] 2020-12-16 05:23
@hoyosjs I try to debug with the framework shared but I'm having the same issue:

```
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
Unable to attach to CoreCLR. Unknown Error: 0x80131c4f

```

Return from `dotnet --info`

```

Host (useful for support):
  Version: 5.0.2
  Commit:  988fa3b75f

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 5.0.2 [/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by hoyosjs** [comment] 2020-12-16 05:26
@microhobby let me test that particular build.

**Comment by microhobby** [comment] 2020-12-16 05:40
@hoyosjs ok, a quick look on the commits and the https://github.com/dotnet/runtime/commit/131a30a3262f22059ce9cc4b08b7099231e83d8c is there before the 988fa3b75f 🤷‍♂️

**Comment by hoyosjs** [comment] 2020-12-16 07:04
hmm @microhobby I just tried attaching to my repro with the provided sample, and I am able to attach.

**Closed** 2020-12-16 07:05 UTC
Labels: area-Diagnostics-coreclr

**Comment by microhobby** [comment] 2020-12-16 14:37
@hoyosjs I added the snippet on the `.csproj` and yes it still runs, with the same behavior

**Comment by microhobby** [comment] 2020-12-16 16:29
@hoyosjs it's working!

![image](https://user-images.githubusercontent.com/2633321/102376639-9ad78700-3fa2-11eb-8f6c-eb8a5d78ca93.png)

I put the `--no-self-contained` on my build command and now it's using the shared framework.
Thanks!
