### ISSUE TITLE
Regression in HTTP/1.1 stress tests: ObjectDisposedException ('SslStream')

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#56159] opened 2021-07-22 15:08 UTC
Since ~last Sunday (July 18)~, every HTTP 1.1 Linux CI stress run has at least one occurrence of the following new failure type:

https://dev.azure.com/dnceng/public/_build/results?buildId=1248255&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=45b31e99-b18c-506f-46cf-7d3a4d5140a9

<details>
<summary>Stack Trace</summary>

```
System.Net.Http.HttpRequestException: An error occurred while sending the request.
client_1  |  ---> System.ObjectDisposedException: Cannot access a disposed object.
client_1  | Object name: 'SslStream'.
client_1  |    at System.Net.Security.SslStream.<ThrowIfExceptional>g__ThrowExceptional|138_0(ExceptionDispatchInfo e) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.cs:line 849
client_1  |    at System.Net.Security.SslStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Security/src/System/Net/Security/SslStream.cs:line 817
client_1  |    at System.Net.Http.HttpConnection.WriteToStreamAsync(ReadOnlyMemory`1 source, Boolean async) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs:line 1447
client_1  |    at System.Net.Http.HttpConnection.FlushAsync(Boolean async) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs:line 1422
client_1  |    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs:line 503
client_1  |    --- End of inner exception stack trace ---
client_1  |    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs:line 817
client_1  |    at System.Net.Http.HttpConnectionPool.SendUsingHttp11Async(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 981
client_1  |    at System.Net.Http.HttpConnectionPool.DetermineVersionAndSendAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1015
client_1  |    at System.Net.Http.HttpConnectionPool.SendAndProcessAltSvcAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1028
client_1  |    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 1038
client_1  |    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 30
client_1  |    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 553
client_1  |    at HttpStress.RequestContext.SendAsync(HttpRequestMessage request, HttpCompletionOption httpCompletion, Nullable`1 token) in /app/ClientOperations.cs:line 95
client_1  |    at HttpStress.ClientOperations.<>c.<<get_Operations>b__1_4>d.MoveNext() in /app/ClientOperations.cs:line 349
client_1  | --- End of stack trace from previous location ---
client_1  |    at HttpStress.StressClient.<>c__DisplayClass17_0.<<StartCore>g__RunWorker|0>d.MoveNext() in /app/StressClient.cs:line 204
```

</details>

~After a quick naive look at recently merged `System.Net.Http` and `System.Net.Security` PR-s, #55772 seems to be the only one that matches the timing. Http PRs seem to be either test fixes, or unrelated to HTTP/ 1.1~

/cc @wfurt @Tratcher @geoffkizer @alnikola 

**Edit 1:** Less frequently, but it also seems to [happen on Windows](https://dev.azure.com/dnceng/public/_build/results?buildId=1257744&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=ac0b0b0f-051f-52f7-8fb3-a7e384b0dde9).

**Edit 2:** First occurrence seems to be on [7/15](https://dev.azure.com/dnceng/public/_build/results?buildId=1239846&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=45b31e99-b18c-506f-46cf-7d3a4d5140a9)

**Comment by wfurt** [comment] 2021-07-22 15:55
This was also reported from field and happens rarely. I don't think it is recent regression.

**Comment by antonfirsov** [comment] 2021-07-22 16:37
Maybe it's not entirely new, but we haven't seen it in the stress runs before, and after 7/18 it suddenly started to impact literally every stress run.

**Comment by antonfirsov** [comment] 2021-07-22 16:45
@MattGal are you aware of any recent changes around `BuildPool.Ubuntu.1804.Amd64.Open`?

**Comment by alnikola** [comment] 2021-08-03 14:17
The issue seems to be caused by a lack of  `HttpConnection._disposed` check on the code path starting from assigning an `HttpConnection` to the next request in [HttpConnectionPool.ReturnHttp11Connection](https://github.com/dotnet/runtime/blob/9be8c6249e5276caf42141a1539495c267ff7bf2/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs#L1733), down to `HttpConnection.SendAsyncCore` [writing data to SslStream](https://github.com/dotnet/runtime/blob/9be8c6249e5276caf42141a1539495c267ff7bf2/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L506). The lack of this check makes possible an attempt to write to a disposed stream. Specifically, this issue manifests itself in `Get Aborted` stress scenario where the [server aborts the connection](https://github.com/dotnet/runtime/blob/28ce2cc5e487f504c8fc91515c41a5fb0e86552c/src/libraries/System.Net.Http/tests/StressTests/HttpStress/StressServer.cs#L243) on each request. Thus, if there is more than 1 request in the `HttpConnectionPool._http11RequestQueue` (which is true for stress tests), `HttpConnectionPool` can try to send a request over an aborted connection.

**Comment by geoffkizer** [comment] 2021-08-03 14:37
In general we shouldn't be calling ReturnHttp11Connection if the connection is already disposed. Do you know when this is happening?

**Comment by alnikola** [comment] 2021-08-03 14:38
@geoffkizer I realized that my theory is wrong.

**Comment by geoffkizer** [comment] 2021-08-03 14:39
Ok. Let me know if I can help.

**Comment by antonfirsov** [comment] 2021-08-06 16:21
No idea why did this error start surfacing only now, but looks like the problem is that we are not passing `cancellationToken` to `FlushAsync`. Two places from the CI stack traces, but there are more:

https://github.com/dotnet/runtime/blob/bc7b910144d1f2b62de05540b9df1bb90f3729b9/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L525

https://github.com/dotnet/runtime/blob/bc7b910144d1f2b62de05540b9df1bb90f3729b9/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L915

In rare cases when `HttpConnection` disposal is faster in it's race with `SendAsyncCore` code, we end up calling into an already disposed stream, throwing `HttpRequestExcetption` with inner `ObjectDisposedException` instead of `OperationCanceledException`.

**Comment by antonfirsov** [comment] 2021-08-06 16:55
Looks like `SslStream` will still throw `ObjectDisposedException` if the stream is disposed, even if we pass a pre-cancelled token.

@geoffkizer @ManickaP shouldn't we check our tokens manually in a very aggressive manner? I'm surprised we don't have more issues around cancellation.

**Comment by wfurt** [comment] 2021-08-06 17:21
From the trace, we are trying to `WriteAsync`. So the question is why do we do that on disposed Stream.
It feels like we should either swallow the exception if we intentionally despised the stream e.g. Disposed/Cancellation/error  or we should delay disposal if we have pending operations.

**Comment by ManickaP** [comment] 2021-08-09 07:36
That we don't pass in `cancellationToken` is normal, we register to it and tear down the connection if it fires:
https://github.com/dotnet/runtime/blob/7a799ce4d21bf0777ca08f4fbf7981a233bb1d0c/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L403-L403
But we should be then able to recognize the exception coming from the cancellation and properly map it:
https://github.com/dotnet/runtime/blob/7a799ce4d21bf0777ca08f4fbf7981a233bb1d0c/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L815-L818

I've seen something similar last year when investigating stress and fixing it: https://github.com/dotnet/runtime/pull/41800 but it manifested only in 100-continue.

Also on 15.7. the big request queuing change was merged: https://github.com/dotnet/runtime/pull/53851. It doesn't seem to touch the relevant code but it might have changed the timing and surface a race here.

Interestingly, the failed calls in HTTP stress are **not cancelled**:
```
client_1  | 	 4: GET Aborted               Fail: 1	Timestamps: 14:51:34.3754360, Duration: 00:00:00.0035326, Cancelled: False
client_1  | 	 5: POST                      Fail: 2	Timestamps: 14:54:22.4029921, Duration: 00:00:00.0012125, Cancelled: False, Timestamps: 15:03:44.4705660, Duration: 00:00:00.0015315, Cancelled: False
client_1  | 	    TOTAL                     Fail: 3
```

What lead you to believe this is caused by cancellation?

**Comment by antonfirsov** [comment] 2021-08-09 09:00
[client_250.log](https://github.com/dotnet/runtime/files/6953143/client_250.log)

Line 1746 says:

```
15:11:23.4917562[HandlerMessage] poolId: 3429838, workerId: 49526251, requestId: 11394055, memberName: RegisterCancellation, message: Cancellation requested. Disposing of the connection.
```

Line 1839 is where the exception happens:

```
15:11:23.4920609[HandlerMessage] poolId: 3429838, workerId: 49526251, requestId: 11394055, memberName: SendAsyncCore, message: Error sending request: System.ObjectDisposedException: Cannot access a disposed object.
```

No idea why doesn't the HttpStress code recognize that the request has been cancelled.

**Comment by ManickaP** [comment] 2021-08-09 11:36
Are you 100% sure those log messages belong to the errors reported by the stress test?
If the cancellation was triggered ('Cancellation requested. Disposing of the connection.') the token would be cancelled and `MapSendException` would map it to OCE.

If you're able to repro it locally, could you try to run it with cancellation rate 0?

**Comment by antonfirsov** [comment] 2021-08-09 15:34
@ManickaP you are right the lines in my https://github.com/dotnet/runtime/issues/56159#issuecomment-895059412 have nothing to do with the error, `SslStream` must be disposed some other way, will keep investigating.

**Comment by geoffkizer** [comment] 2021-08-10 16:57
What cancellation token is firing specifically, and what action is it taking?

**Comment by MattGal** [comment] 2021-08-10 17:06
> @MattGal are you aware of any recent changes around `BuildPool.Ubuntu.1804.Amd64.Open`?

Apologies, I didn't see the original tag until Geoff commented.  Nothing interesting has changed on that image in some time, sounds like the right conversations are happening though.

**Comment by geoffkizer** [comment] 2021-08-10 17:14
> @geoffkizer my diagnosis would be that although CancellationTokenRegistration should not be dead long time before ReturnHttp11Connection is invoked, that doesn't prevent an already fired callback to finish and race with the request completion code (including ReturnHttp11Connection). But I may be terribly wrong, any other ideas?

We are disposing the cancellation registration on line 706, before we create the response stream and start to process it.

Dispose on the cancellation registration will not return until the cancellation registration is either cancelled without firing, or until the cancellation callback we give it completes. In other words, by the time the Dispose returns, the cancellation callback can't be running anymore -- it's either already run and completed, or never will.

**Comment by geoffkizer** [comment] 2021-08-10 17:16
> Also: why do we see log lines from FillAsync, when a previous line reported that the response has been received for that request?

FillAsync is also used while reading the response body. 

RegisterCancellation is called from a bunch of places, specifically when reading the response body. So I'm assuming that one of the response body reads is getting cancelled, which is disposing the connection; yet somehow we are still returning the connection to the pool? Weird.

It certainly seems likely that my connection pooling PR introduced this somehow, but I'm not sure how...

**Comment by geoffkizer** [comment] 2021-08-10 17:28
It's very interesting that DrainOnDisposeAsync is getting called. This indicates that the response stream is getting disposed, and we think it's still valid so we are trying to drain it so we can continue to use the connection.

It seems like perhaps there's a race here between the cancellation token for a read operation firing and the stream's Dispose logic?

I'm not sure how my PR would have caused this, though...

**Comment by geoffkizer** [comment] 2021-08-10 17:31
Note also that the drain happens asynchronously... if there is still an outstanding read at this point, that would be really bad.

What does the test code here look like? Is it possible that the stream is getting Disposed while there is still an outstanding read operation?

**Comment by antonfirsov** [comment] 2021-08-10 18:12
> What does the test code here look like? 

https://github.com/dotnet/runtime/blob/8bf8030e24c75818c901d9c4d4674938aff3a28e/src/libraries/System.Net.Http/tests/StressTests/HttpStress/ClientOperations.cs#L497-L506

Where `SendAsync` most likely triggers this path and `httpCompletion = HttpCompletionOption.ResponseContentRead`:

https://github.com/dotnet/runtime/blob/8bf8030e24c75818c901d9c4d4674938aff3a28e/src/libraries/System.Net.Http/tests/StressTests/HttpStress/ClientOperations.cs#L68-L90

Will add some more logging to get a proof, and more details about the call stack.

**Comment by kedia990** [comment] 2021-08-10 22:38
I wanted to quickly chime in here to note that we're facing this (or at least a very similar variant of this) issue with a production service in our organization. This became apparent during our efforts to migrate our applications which depend on said service to .NET Core / PowerShell Core (which have now stalled; with any luck, a fix for this will ship with .NET 6). Here are the characteristics of the issue (relevant stack traces provided at the end):

* It's consistently reproducible against the service in question. API calls fail 100% of the time with `ObjectDisposedException`.
* The service uses HTTP/1.1 and Kerberos authentication. Hitting an unauthenticated endpoint on the service works fine, but most endpoints it serves require authentication.
* TLS doesn't appear to be a factor. Hitting the HTTPS endpoint results in an ODE from `SslStream`; hitting HTTP results in an ODE from `NetworkStream`. Both stack traces have been provided below.
* This issue is confined to `SocketsHttpHandler`; switching to `WinHttpHandler` (in .NET Core 3.1, since the knob to toggle it has been removed in .NET 5) fixes the issue.
* This issue affects .NET 5, .NET Core 3.1 and .NET Core 2.1 in our environment. It does not affect .NET Framework (obviously).

Having reviewed the discussion so far, I realize that there are a couple of differences - (a) authentication doesn't seem to feature in your discussions / stack trace, and (b) the timing of #53851, as a candidate for the cause, wouldn't explain this for us if we're able to repro the issue as far back as .NET Core 2.1.

That said, given that the manifestation of the bug appears to be identical _and_ we have a reliable reproducer, I figured I'd provide the data point here. If there's anything I can try on our end / do to help debug this issue, I'm happy to help (and probably learn a little something too, perhaps). (OTOH, if you think this is completely unrelated and we should be tracking this elsewhere, I'll stop bothering you folks here :) .)

<details>
<summary><b>Expand for Stack Traces</b></summary>

```powershell
PS C:\Users\redact> $httpClient.GetStringAsync('https://redact').GetAwaiter().GetResult()
MethodInvocationException: Exception calling "GetResult" with "0" argument(s): "An error occurred while sending the request."

PS C:\Users\redact> $Error[0].Exception.ToString()
System.Management.Automation.MethodInvocationException: Exception calling "GetResult" with "0" argument(s): "An error occurred while sending the request."
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.
   at System.Net.Security.SslStream.<ThrowIfExceptional>g__ThrowExceptional|137_0(ExceptionDispatchInfo e)
   at System.Net.Security.SslStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.WriteToStreamAsync(ReadOnlyMemory`1 source, Boolean async)
   at System.Net.Http.HttpConnection.FlushAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at CallSite.Target(Closure , CallSite , Object )
   --- End of inner exception stack trace ---
   ...

PS C:\Users\redact> $httpClient.GetStringAsync('http://redact').GetAwaiter().GetResult()
MethodInvocationException: Exception calling "GetResult" with "0" argument(s): "An error occurred while sending the request."

PS C:\Users\redact> $Error[0].Exception.ToString()
System.Management.Automation.MethodInvocationException: Exception calling "GetResult" with "0" argument(s): "An error occurred while sending the request."
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.<ThrowIfDisposed>g__ThrowObjectDisposedException|63_0()
   at System.Net.Sockets.NetworkStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.WriteToStreamAsync(ReadOnlyMemory`1 source, Boolean async)
   at System.Net.Http.HttpConnection.FlushAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at CallSite.Target(Closure , CallSite , Object )
   --- End of inner exception stack trace ---
   ...
```
</details>

**Comment by ManickaP** [comment] 2021-08-11 07:01
Hi @kedia990, yeah I think the cause of your problem will be very different, what we track here is a recent regression in 6.0 preview versions. Could migrate your comment to a new issue? We can continue discussion from there.
Also if you have a repro, it would be great if you shared it, so we can look at it a test it on our own.

**Comment by geoffkizer** [comment] 2021-08-11 16:32
@stephentoub Any thoughts here? It looks like somehow the connection is getting disposed by the cancellation registration callback, but also getting returned to the pool via CompleteResponse...

**Comment by antonfirsov** [comment] 2021-08-12 14:20
More (more accurate) details:
- Cancellation is triggered and finished in `ChunkedEncodingReadStream.CopyToAsyncCore`, disposing the connection. 
- [`HttpConnectionResponseContent.SerializeToStreamAsync` disposes `ChunkedEncodingReadStream`](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionResponseContent.cs#L61-L65)
- `HttpContentReadStream.Dispose(true)` [starts draining the connection](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpContentReadStream.cs#L54).
- `ChunkedEncodingReadStream.DrawinAsync` will eventually return the connection to the pool.

**Closed** 2021-08-16 13:59 UTC
Labels: bug, area-System.Net.Http, in pr
