### ISSUE TITLE
[CoreCLR] System.InvalidCastException thrown in tests

### ISSUE THREAD

**Issue by jashook** [dotnet/runtime#84] opened 2019-11-18 05:38 UTC
https://dev.azure.com/dnceng/public/_build/results?buildId=430455&view=ms.vss-test-web.build-test-results-tab

```
Native image C:\dotnetbuild\work\98963201-3865-458b-88b5-5b6d501560e9\Work\1a4c26fd-5901-45fb-b120-fcc1643ad599\Exec\Loader\classloader\generics\Variance\Methods\Method003\\Method003.dll generated successfully.
 "C:\dotnetbuild\work\98963201-3865-458b-88b5-5b6d501560e9\Payload\corerun.exe" Method003.dll 
Unexpected Exception System.InvalidCastException: Unable to cast object of type 'E' to type 'IMinusT[System.Object[]]'.
   at A7.method1[M](Object t) in F:\workspace.1\_work\1\s\src\coreclr\tests\src\Loader\classloader\generics\Variance\Methods\Method003.cs:line 37
   at TestClass.LoadTypeInternal(String testType) in F:\workspace.1\_work\1\s\src\coreclr\tests\src\Loader\classloader\generics\Variance\Methods\Method003.cs:line 96
   at TestClass.LoadType(String testType, Boolean expected) in F:\workspace.1\_work\1\s\src\coreclr\tests\src\Loader\classloader\generics\Variance\Methods\Method003.cs:line 114
Test Failed at location: Test103 @ count 3 
Total test cases: 3  Failed test cases: 1
```

**Comment by mangod9** [comment] 2020-08-03 17:12
Hey @jashook, do you have context on this failure. Looking through the test it appears it might have been failing on 3.1 too, so checking if this was a new test possibly?

**Comment by mangod9** [comment] 2020-08-06 02:18
Dont believe this test failure is a regression. Appears to be failing since 2.0

**Comment by mangod9** [comment] 2021-07-09 23:17
Closing since this appears to be re-enabled?

**Closed by mangod9** 2021-07-09 23:17 UTC
Labels: area-VM-coreclr, disabled-test
