### ISSUE TITLE
Test failure: Assertion failed 'likelihood <= 1.0'

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#108100] opened 2024-09-21 14:32 UTC
```
  Starting:    System.Text.RegularExpressions.Tests (parallel test collections = on [2 threads], stop on fail = off)

Assert failure(PID 21 [0x00000015], Thread: 30 [0x001e]): Assertion failed 'likelihood <= 1.0' in 'Microsoft.CodeAnalysis.CSharp.Syntax.InternalSyntax.Lexer:LexXmlWhitespaceAndNewLineTrivia(byref):this' during 'Recognize Switch' (IL size 152; hash 0x82b23354; Tier1)

    File: /__w/1/s/src/coreclr/jit/block.cpp:81
    Image: /root/helix/work/correlation/dotnet
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=814658
Build error leg or test failing: System.Collections.Concurrent.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/108048

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "likelihood <= 1.0",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=814658
**Error message validated:** `[likelihood <= 1.0`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 9/21/2024 2:32:34 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[816686](https://dev.azure.com/dnceng-public/public/_build/results?buildId=816686)|dotnet/runtime|[System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=816686&view=ms.vss-test-web.build-test-results-tab&runId=21179250&resultId=212353)||
|[816522](https://dev.azure.com/dnceng-public/public/_build/results?buildId=816522)|dotnet/runtime|[System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=816522&view=ms.vss-test-web.build-test-results-tab&runId=21174654&resultId=212103)|dotnet/runtime#108171|
|[816072](https://dev.azure.com/dnceng-public/public/_build/results?buildId=816072)|dotnet/runtime|[System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=816072&view=ms.vss-test-web.build-test-results-tab&runId=21160536&resultId=215055)|dotnet/runtime#107709|
|[815290](https://dev.azure.com/dnceng-public/public/_build/results?buildId=815290)|dotnet/runtime|[System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=815290&view=ms.vss-test-web.build-test-results-tab&runId=21134716&resultId=211958)|dotnet/runtime#108117|
|[815210](https://dev.azure.com/dnceng-public/public/_build/results?buildId=815210)|dotnet/runtime|[Microsoft.Extensions.Logging.Generators.Roslyn3.11.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=815210&view=ms.vss-test-web.build-test-results-tab&runId=21130684&resultId=212252)|dotnet/runtime#108104|
|[815034](https://dev.azure.com/dnceng-public/public/_build/results?buildId=815034)|dotnet/runtime|[System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=815034&view=ms.vss-test-web.build-test-results-tab&runId=21125418&resultId=211752)|dotnet/runtime#107863|
|[814912](https://dev.azure.com/dnceng-public/public/_build/results?buildId=814912)|dotnet/runtime|[System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=814912&view=ms.vss-test-web.build-test-results-tab&runId=21120078&resultId=211924)|dotnet/runtime#106599|
|[814853](https://dev.azure.com/dnceng-public/public/_build/results?buildId=814853)|dotnet/runtime|[Microsoft.Extensions.Logging.Generators.Roslyn4.8.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=814853&view=ms.vss-test-web.build-test-results-tab&runId=21117476&resultId=212236)|dotnet/runtime#107772|
|[814658](https://dev.azure.com/dnceng-public/public/_build/results?buildId=814658)|dotnet/runtime|[System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=814658&view=ms.vss-test-web.build-test-results-tab&runId=21108276&resultId=211924)|dotnet/runtime#108048|
|[814398](https://dev.azure.com/dnceng-public/public/_build/results?buildId=814398)|dotnet/runtime|[System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=814398&view=ms.vss-test-web.build-test-results-tab&runId=21102864&resultId=211813)|dotnet/runtime#108083|
|[813801](https://dev.azure.com/dnceng-public/public/_build/results?buildId=813801)|dotnet/runtime|[System.Text.RegularExpressions.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=813801&view=ms.vss-test-web.build-test-results-tab&runId=21087064&resultId=211748)|dotnet/runtime#108049|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|3|11|

**Comment by AndyAyersMS** [comment] 2024-09-21 15:24
@EgorBo likely related to #107831

**Comment by amanasifkhalid** [comment] 2024-09-23 18:14
#108125 looks related. #108124 was probably caused by #107831, too -- to fix the latter, I think we might just need to move the `fgRenumberBlocks` call up in `Compiler::optSwitchRecognition`.

**Comment by EgorBo** [comment] 2024-09-23 20:51
Regressed by 10.0 PR

**Comment by JulieLeeMSFT** [comment] 2024-09-30 16:39
Closing because the original code that caused the issue is reverted.

**Closed by JulieLeeMSFT** 2024-09-30 16:39 UTC
Labels: area-CodeGen-coreclr, blocking-clean-ci, in-pr, Known Build Error
