### ISSUE TITLE
[Perf -50%] System.Numerics.Tests.Perf_Vector2.LengthSquaredBenchmark

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#37425] opened 2020-06-04 16:54 UTC
### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Changes | [diff](https://github.com/dotnet/runtime/compare/0c043d58ccce29e1d22acd4f77b0e0b352579ac5...f253b4a6f078585328d388c8a6feb1bbcd11bc2b)

### Regressions in System.Numerics.Tests.Perf_Vector2

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier
-- | -- | -- | -- | -- | --
LengthSquaredBenchmark | 0.34 ns | 0.51 ns | 1.50 |  | False

[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereports/06_03_2020/Windows 10.0.18362_x64/System.Numerics.Tests.Perf_Vector2.html?st=2020-05-29T20%3A16%3A18Z&se=2021-05-30T20%3A16%3A00Z&sp=racwl&sv=2018-03-28&sr=c&sig=GG7E%2BwEH6Ve9y9KSKwKfRJOTP7rXSR0ce8wQGTJwmek%3D>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Numerics.Tests.Perf_Vector2*';
```
<details>

#### LengthSquaredBenchmark

```log
[0.305 ; 0.369) | @@@@@@@@@@@@@@@
[0.369 ; 0.434) | @
[0.434 ; 0.510) | @@@@@@@@@@@@@@@@@@@@@@@
[0.510 ; 0.539) | 
[0.539 ; 0.604) | @@@@@@@@@@@@@@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

category:cq
theme:vector-codegen
skill-level:intermediate
cost:medium

**Comment by EgorBo** [comment] 2020-06-04 18:49
```csharp
public float Test1(Vector2 vec) => vec.LengthSquared();

// same, but inlined by hands:
public float Test2(Vector2 v) => v.X * v.X + v.Y * v.Y;
```

```asm
; Method Foo:Test1(System.Numerics.Vector2):float:this
G_M49664_IG01:
       vzeroupper 
       mov      qword ptr [rsp+10H], rdx
G_M49664_IG02:
       lea      rax, bword ptr [rsp+10H]
       vmovss   xmm0, dword ptr [rax]
       vmovss   xmm1, dword ptr [rax+4]
       lea      rax, bword ptr [rsp+10H]
       vmovss   xmm2, dword ptr [rax]
       vmovss   xmm3, dword ptr [rax+4]
       vmulss   xmm0, xmm0, xmm2
       vmulss   xmm1, xmm1, xmm3
       vaddss   xmm0, xmm0, xmm1
G_M49664_IG03:
       ret      
; Total bytes of code: 49



; Method Foo:Test2(System.Numerics.Vector2):float:this
G_M29891_IG01:
       vzeroupper 
       mov      qword ptr [rsp+10H], rdx
G_M29891_IG02:
       vmovss   xmm0, dword ptr [rsp+10H]
       vmulss   xmm0, xmm0, xmm0
       vmovss   xmm1, dword ptr [rsp+14H]
       vmulss   xmm1, xmm1, xmm1
       vaddss   xmm0, xmm0, xmm1
G_M29891_IG03:
       ret      
; Total bytes of code: 33

```

**Comment by tannergooding** [comment] 2020-06-04 19:07
The regression is due to `DPPS` not being a `SimdAsHWIntrinsic` yet and so there is some register shuffling when transitioning from the legacy `GT_SIMD` to the newer `GT_HWINTRINSIC` as the RMW and VEX support between them isn't the same.

**Comment by AndyAyersMS** [comment] 2020-06-22 21:18
@tannergooding is this covered by the PR above?

Marking this as codegen.

**Comment by tannergooding** [comment] 2020-06-22 21:21
Yes. This was due to some, but not all, of the System.Numerics intrinsics being transitioned to use HWIntrinsic internally.

The GT_HWINTRINSIC nodes are VEX aware while the GT_SIMD nodes are not, which caused a few additional moves to be inserted. The above PR transitions `Dot` and the other big functions to also use HWIntrinsics which allows the additional moves to be elided.

**Comment by BruceForstall** [comment] 2020-07-29 01:06
@tannergooding Was this fixed by https://github.com/dotnet/runtime/pull/37882? Or does the issue need to remain open?

**Comment by tannergooding** [comment] 2020-07-29 20:55
Yes, it looks to be resolved. The actual test is quite noisy but it is much closer to the original timing now: https://pvscmdupload.blob.core.windows.net/reports/07_01_2020/SIMD/report_Monthly_ca=x64_cb=refs-heads-master_co=Windows1018362_cr=dotnetruntime_cf=SIMD_cc=CompliationMode=tiered-RunKind=micro_2020-07-01.html

**Closed by tannergooding** 2020-07-29 20:55 UTC
Labels: arch-x64, area-CodeGen-coreclr, os-windows, tenet-performance, tenet-performance-benchmarks
