### ISSUE TITLE
Assertion failed in test `Interop\\UnmanagedCallersOnly\\UnmanagedCallersOnlyTest\\UnmanagedCallersOnlyTest.cmd`: bIsRealStartFrameUnchanged

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#47395] opened 2021-01-25 02:11 UTC
Run: [runtime-coreclr gcstress-extra 20210123.1](https://dev.azure.com/dnceng/public/_build/results?buildId=963544&view=ms.vss-test-web.build-test-results-tab&runId=30347974&paneView=debug&resultId=102086)

Failed tests:
```
CoreCLR windows x86 Checked gcstress0xc_zapdisable_jitstress2 @ Windows.10.Amd64.Open
        - Interop\\UnmanagedCallersOnly\\UnmanagedCallersOnlyTest\\UnmanagedCallersOnlyTest.cmd
```

Error message:
```
Assert failure(PID 1760 [0x000006e0], Thread: 1380 [0x0564]): bIsRealStartFrameUnchanged

CORECLR! StackFrameIterator::IsValid + 0x102 (0x70762f2a)
CORECLR! StackFrameIterator::ProcessCurrentFrame + 0x135 (0x707640e7)
CORECLR! StackFrameIterator::NextRaw + 0x9DF (0x70763b44)
CORECLR! StackFrameIterator::Filter + 0x110 (0x70761d34)
CORECLR! StackFrameIterator::Next + 0x53 (0x7076312e)
CORECLR! Thread::StackWalkFramesEx + 0x18A (0x7076472b)
CORECLR! Thread::StackWalkFrames + 0x159 (0x70764521)
CORECLR! ScanStackRoots + 0x195 (0x7082fa16)
CORECLR! GCToEEInterface::GcScanRoots + 0xE4 (0x7082e04a)
CORECLR! WKS::gc_heap::background_mark_phase + 0x3D6 (0x70a855f9)
    File: F:\workspace\_work\1\s\src\coreclr\vm\stackwalk.cpp Line: 1522
    Image: C:\h\w\ADC409E3\p\CoreRun.exe


Return code:      1
Raw output file:      C:\h\w\ADC409E3\w\AD230945\e\Interop\UnmanagedCallersOnly\Reports\Interop.UnmanagedCallersOnly\UnmanagedCallersOnlyTest\UnmanagedCallersOnlyTest.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\ADC409E3\p\corerun.exe" UnmanagedCallersOnlyTest.dll 
Running TestUnmanagedCallersOnlyValid...
Running TestUnmanagedCallersOnlyValid_OnNewNativeThread...
Running TestUnmanagedCallersOnlyValid_PrepareMethod...
Running TestUnmanagedCallersOnlyMultipleTimesValid...
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\ADC409E3\p
> C:\h\w\ADC409E3\w\AD230945\e\Interop\UnmanagedCallersOnly\UnmanagedCallersOnlyTest\UnmanagedCallersOnlyTest.cmd

stack trace:
   at Interop_UnmanagedCallersOnly._UnmanagedCallersOnlyTest_UnmanagedCallersOnlyTest_._UnmanagedCallersOnlyTest_UnmanagedCallersOnlyTest_cmd()
```

**Comment by VincentBu** [comment] 2021-02-02 06:48
Failed again in run : [runtime-coreclr gcstress-extra 20210131.1](https://dev.azure.com/dnceng/public/_build/results?buildId=973314&view=ms.vss-test-web.build-test-results-tab&runId=30564144&resultId=101160&paneView=debug)

Failed test : `Interop\\UnmanagedCallersOnly\\UnmanagedCallersOnlyTest\\UnmanagedCallersOnlyTest.cmd`

CoreCLR windows x86 Checked gcstress0xc_zapdisable @ Windows.10.Amd64.Open

**Error message:**
```
Assert failure(PID 2776 [0x00000ad8], Thread: 5020 [0x139c]): bIsRealStartFrameUnchanged

CORECLR! StackFrameIterator::IsValid + 0x102 (0x7004755a)
CORECLR! StackFrameIterator::ProcessCurrentFrame + 0x135 (0x70048717)
CORECLR! StackFrameIterator::NextRaw + 0x9DF (0x70048174)
CORECLR! StackFrameIterator::Filter + 0x110 (0x70046364)
CORECLR! StackFrameIterator::Next + 0x53 (0x7004775e)
CORECLR! Thread::StackWalkFramesEx + 0x18A (0x70048d5b)
CORECLR! Thread::StackWalkFrames + 0x159 (0x70048b51)
CORECLR! ScanStackRoots + 0x195 (0x70113cf6)
CORECLR! GCToEEInterface::GcScanRoots + 0xE4 (0x7011232a)
CORECLR! WKS::gc_heap::background_mark_phase + 0x3D6 (0x7036a01b)
 File: F:\workspace\_work\1\s\src\coreclr\vm\stackwalk.cpp Line: 1522
 Image: C:\h\w\B12B0939\p\CoreRun.exe


Return code: 1
Raw output file: C:\h\w\B12B0939\w\B87009A8\e\Interop\UnmanagedCallersOnly\Reports\Interop.UnmanagedCallersOnly\UnmanagedCallersOnlyTest\UnmanagedCallersOnlyTest.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\B12B0939\p\corerun.exe" UnmanagedCallersOnlyTest.dll 
Running TestUnmanagedCallersOnlyValid...
Running TestUnmanagedCallersOnlyValid_OnNewNativeThread...
Running TestUnmanagedCallersOnlyValid_PrepareMethod...
Running TestUnmanagedCallersOnlyMultipleTimesValid...
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\B12B0939\p
> C:\h\w\B12B0939\w\B87009A8\e\Interop\UnmanagedCallersOnly\UnmanagedCallersOnlyTest\UnmanagedCallersOnlyTest.cmd
Expected: True
Actual: False

Stack trace
   at Interop_UnmanagedCallersOnly._UnmanagedCallersOnlyTest_UnmanagedCallersOnlyTest_._UnmanagedCallersOnlyTest_UnmanagedCallersOnlyTest_cmd()

```

**Comment by VincentBu** [comment] 2021-02-09 01:53
Failed again in run [runtime-coreclr gcstress-extra 20210207.1](https://dev.azure.com/dnceng/public/_build/results?buildId=982567&view=ms.vss-test-web.build-test-results-tab&runId=30792416&resultId=102075&paneView=debug)

Failed test:
```
CoreCLR windows x86 Checked gcstress0xc_zapdisable_jitstress2 @ Windows.10.Amd64.Open

  -Interop\\UnmanagedCallersOnly\\UnmanagedCallersOnlyTest\\UnmanagedCallersOnlyTest.cmd
```

**Error message:**
```

Assert failure(PID 1072 [0x00000430], Thread: 5136 [0x1410]): bIsRealStartFrameUnchanged

CORECLR! StackFrameIterator::IsValid + 0x102 (0x7021848a)
CORECLR! StackFrameIterator::ProcessCurrentFrame + 0x135 (0x70219647)
CORECLR! StackFrameIterator::NextRaw + 0x9DF (0x702190a4)
CORECLR! StackFrameIterator::Filter + 0x110 (0x70217294)
CORECLR! StackFrameIterator::Next + 0x53 (0x7021868e)
CORECLR! Thread::StackWalkFramesEx + 0x18A (0x70219c8b)
CORECLR! Thread::StackWalkFrames + 0x159 (0x70219a81)
CORECLR! ScanStackRoots + 0x195 (0x702e5069)
CORECLR! GCToEEInterface::GcScanRoots + 0xE4 (0x702e369c)
CORECLR! WKS::gc_heap::background_mark_phase + 0x3D6 (0x7053b587)
 File: D:\workspace\_work\1\s\src\coreclr\vm\stackwalk.cpp Line: 1522
 Image: C:\h\w\A70C092A\p\CoreRun.exe


Return code: 1
Raw output file: C:\h\w\A70C092A\w\ABEE0992\e\Interop\UnmanagedCallersOnly\Reports\Interop.UnmanagedCallersOnly\UnmanagedCallersOnlyTest\UnmanagedCallersOnlyTest.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\A70C092A\p\corerun.exe" UnmanagedCallersOnlyTest.dll 
Running TestUnmanagedCallersOnlyValid...
Running TestUnmanagedCallersOnlyValid_OnNewNativeThread...
Running TestUnmanagedCallersOnlyValid_PrepareMethod...
Running TestUnmanagedCallersOnlyMultipleTimesValid...
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\A70C092A\p
> C:\h\w\A70C092A\w\ABEE0992\e\Interop\UnmanagedCallersOnly\UnmanagedCallersOnlyTest\UnmanagedCallersOnlyTest.cmd
Expected: True
Actual: False

Stack trace
   at Interop_UnmanagedCallersOnly._UnmanagedCallersOnlyTest_UnmanagedCallersOnlyTest_._UnmanagedCallersOnlyTest_UnmanagedCallersOnlyTest_cmd()


```

**Comment by VincentBu** [comment] 2021-02-22 02:25
Failed again in [runtime-coreclr gcstress-extra 20210220.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1004691&view=ms.vss-test-web.build-test-results-tab&runId=31375844&resultId=100915&paneView=debug)

Failed test:
```
CoreCLR windows x86 Checked gcstress0xc_zapdisable @ Windows.10.Amd64.Open
 -Interop\\UnmanagedCallersOnly\\UnmanagedCallersOnlyTest\\UnmanagedCallersOnlyTest.cmd
```

**Error message:**
```
Assert failure(PID 5328 [0x000014d0], Thread: 5288 [0x14a8]): bIsRealStartFrameUnchanged

CORECLR! StackFrameIterator::IsValid + 0x102 (0x70179d0a)
CORECLR! StackFrameIterator::ProcessCurrentFrame + 0x135 (0x7017aeca)
CORECLR! StackFrameIterator::NextRaw + 0x9DF (0x7017a924)
CORECLR! StackFrameIterator::Filter + 0x110 (0x70178b14)
CORECLR! StackFrameIterator::Next + 0x53 (0x70179f0e)
CORECLR! Thread::StackWalkFramesEx + 0x18A (0x7017b50e)
CORECLR! Thread::StackWalkFrames + 0x159 (0x7017b304)
CORECLR! ScanStackRoots + 0x195 (0x70246c76)
CORECLR! GCToEEInterface::GcScanRoots + 0xE4 (0x702452ac)
CORECLR! WKS::gc_heap::background_mark_phase + 0x3D6 (0x7049deb9)
 File: D:\workspace\_work\1\s\src\coreclr\vm\stackwalk.cpp Line: 1522
 Image: C:\h\w\A14408A4\p\CoreRun.exe


Return code: 1
Raw output file: C:\h\w\A14408A4\w\A0E408C7\e\Interop\UnmanagedCallersOnly\Reports\Interop.UnmanagedCallersOnly\UnmanagedCallersOnlyTest\UnmanagedCallersOnlyTest.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\A14408A4\p\corerun.exe" UnmanagedCallersOnlyTest.dll 
Running TestUnmanagedCallersOnlyValid...
Running TestUnmanagedCallersOnlyValid_OnNewNativeThread...
Running TestUnmanagedCallersOnlyValid_PrepareMethod...
Running TestUnmanagedCallersOnlyMultipleTimesValid...
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\A14408A4\p
> C:\h\w\A14408A4\w\A0E408C7\e\Interop\UnmanagedCallersOnly\UnmanagedCallersOnlyTest\UnmanagedCallersOnlyTest.cmd
Expected: True
Actual: False

Stack trace
   at Interop_UnmanagedCallersOnly._UnmanagedCallersOnlyTest_UnmanagedCallersOnlyTest_._UnmanagedCallersOnlyTest_UnmanagedCallersOnlyTest_cmd()

```

**Comment by VincentBu** [comment] 2021-03-08 02:35
Failed again in [runtime-coreclr gcstress-extra 20210306.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1026058&view=ms.vss-test-web.build-test-results-tab&runId=31884996&resultId=101052&paneView=debug)

Failed test:
```
CoreCLR windows x86 Checked gcstress0xc_zapdisable @ Windows.10.Amd64.Open
 -Interop\\UnmanagedCallersOnly\\UnmanagedCallersOnlyTest\\UnmanagedCallersOnlyTest.cmd
```

**Error message:**
```
Assert failure(PID 5304 [0x000014b8], Thread: 3280 [0x0cd0]): bIsRealStartFrameUnchanged

CORECLR! StackFrameIterator::IsValid + 0x102 (0x70169d7a)
CORECLR! StackFrameIterator::ProcessCurrentFrame + 0x135 (0x7016af37)
CORECLR! StackFrameIterator::NextRaw + 0x9DF (0x7016a994)
CORECLR! StackFrameIterator::Filter + 0x110 (0x70168b84)
CORECLR! StackFrameIterator::Next + 0x53 (0x70169f7e)
CORECLR! Thread::StackWalkFramesEx + 0x18A (0x7016b57b)
CORECLR! Thread::StackWalkFrames + 0x159 (0x7016b371)
CORECLR! ScanStackRoots + 0x195 (0x70236976)
CORECLR! GCToEEInterface::GcScanRoots + 0xE4 (0x70234fac)
CORECLR! WKS::gc_heap::background_mark_phase + 0x3D6 (0x7048dc37)
 File: D:\workspace\_work\1\s\src\coreclr\vm\stackwalk.cpp Line: 1522
 Image: C:\h\w\B4D5099F\p\CoreRun.exe


Return code: 1
Raw output file: C:\h\w\B4D5099F\w\984B08C0\e\Interop\UnmanagedCallersOnly\Reports\Interop.UnmanagedCallersOnly\UnmanagedCallersOnlyTest\UnmanagedCallersOnlyTest.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\B4D5099F\p\corerun.exe" UnmanagedCallersOnlyTest.dll 
Running TestUnmanagedCallersOnlyValid...
Running TestUnmanagedCallersOnlyValid_OnNewNativeThread...
Running TestUnmanagedCallersOnlyValid_PrepareMethod...
Running TestUnmanagedCallersOnlyMultipleTimesValid...
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\B4D5099F\p
> C:\h\w\B4D5099F\w\984B08C0\e\Interop\UnmanagedCallersOnly\UnmanagedCallersOnlyTest\UnmanagedCallersOnlyTest.cmd
Expected: True
Actual: False

Stack trace
   at Interop_UnmanagedCallersOnly._UnmanagedCallersOnlyTest_UnmanagedCallersOnlyTest_._UnmanagedCallersOnlyTest_UnmanagedCallersOnlyTest_cmd()

```

**Comment by VincentBu** [comment] 2021-03-22 07:05
Failed again in [runtime-coreclr gcstress-extra 20210320.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1049449&view=ms.vss-test-web.build-test-results-tab&runId=32437416&resultId=101735&paneView=debug)

Failed test:
```
CoreCLR windows x86 Checked gcstress0xc_zapdisable @ Windows.10.Amd64.Open
 -Interop\\UnmanagedCallersOnly\\UnmanagedCallersOnlyTest\\UnmanagedCallersOnlyTest.cmd
```

**Error message:**
```
Assert failure(PID 3324 [0x00000cfc], Thread: 9120 [0x23a0]): bIsRealStartFrameUnchanged

CORECLR! StackFrameIterator::IsValid + 0x102 (0x704aa85a)
CORECLR! StackFrameIterator::ProcessCurrentFrame + 0x135 (0x704aba17)
CORECLR! StackFrameIterator::NextRaw + 0x9DF (0x704ab474)
CORECLR! StackFrameIterator::Filter + 0x110 (0x704a9664)
CORECLR! StackFrameIterator::Next + 0x53 (0x704aaa5e)
CORECLR! Thread::StackWalkFramesEx + 0x18A (0x704ac05b)
CORECLR! Thread::StackWalkFrames + 0x159 (0x704abe51)
CORECLR! ScanStackRoots + 0x195 (0x70577496)
CORECLR! GCToEEInterface::GcScanRoots + 0xE4 (0x70575acc)
CORECLR! WKS::gc_heap::background_mark_phase + 0x3D6 (0x707ce627)
 File: D:\workspace\_work\1\s\src\coreclr\vm\stackwalk.cpp Line: 1522
 Image: C:\h\w\A68D0976\p\corerun.exe


Return code: 1
Raw output file: C:\h\w\A68D0976\w\A1D008CA\e\Interop\UnmanagedCallersOnly\Reports\Interop.UnmanagedCallersOnly\UnmanagedCallersOnlyTest\UnmanagedCallersOnlyTest.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\A68D0976\p\corerun.exe" UnmanagedCallersOnlyTest.dll 
Running TestUnmanagedCallersOnlyValid...
Running TestUnmanagedCallersOnlyValid_OnNewNativeThread...
Running TestUnmanagedCallersOnlyValid_PrepareMethod...
Running TestUnmanagedCallersOnlyMultipleTimesValid...
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\A68D0976\p
> C:\h\w\A68D0976\w\A1D008CA\e\Interop\UnmanagedCallersOnly\UnmanagedCallersOnlyTest\UnmanagedCallersOnlyTest.cmd
Expected: True
Actual: False

Stack trace
   at Interop_UnmanagedCallersOnly._UnmanagedCallersOnlyTest_UnmanagedCallersOnlyTest_._UnmanagedCallersOnlyTest_UnmanagedCallersOnlyTest_cmd()

```

**Comment by AaronRobinsonMSFT** [comment] 2021-04-01 21:43
The assert that is failing here has a reference to https://github.com/dotnet/runtime/issues/11678. I'm unclear if the two are in any way related but the comments do indicate a race condition is possible. I am unable to reproduce this issue locally. I've been running the test in a loop for over an hour (approximate 1200 iterations) - no failures yet. I am inclined to break apart the large assert to perhaps narrow down which invariant is failing here.

**Comment by AaronRobinsonMSFT** [comment] 2021-04-02 02:30
@VincentBu I am going to close this for now. I've not fixed this at all but did update the failing assert so hopefully it will shed some more light on the issue - see https://github.com/dotnet/runtime/pull/50620. Please open this when it inevitably fails again.

**Closed by AaronRobinsonMSFT** 2021-04-02 02:30 UTC
Labels: GCStress, JitStress, arch-x86, area-Interop-coreclr, os-windows, untriaged
