### ISSUE TITLE
Couldn't create Hyperlinks when working with MS.Office.Interop.Excel using .Net Core

### ISSUE THREAD

**Issue by MMW-RobinTaba** [dotnet/runtime#43425] opened 2020-10-06 11:27 UTC
Specs:
- WPF Solution working under .NET Core 3.1 with VS2019.

Since moving to .NET Core, i cannot fully use the MS.Office.Interop dll-s. When i try to create a Hyperlink in an Excel Cell, it always gives me that Error:

![image](https://user-images.githubusercontent.com/69900041/95195767-4c09b600-07d7-11eb-98ed-a98cebd9f87f.png)

Does anybody know a solution for that Issue?

**Comment by AaronRobinsonMSFT** [comment] 2020-10-14 23:57
@MMW-RobinTaba Thanks for reporting this issue. I am unable to reproduce this locally, however I assume because I am not using the API correctly - I am not familiar with the Office API so a small snippet of code that should work would be appreciated. Generally screenshots of code aren't very helpful because they are (a) difficult to copy/paste to retry and (b) are missing too much context to be able to see the issue.

Could you please provide a snippet of code that I can use to reproduce this issue locally? I am starting from https://github.com/dotnet/samples/tree/master/core/extensions/ExcelDemo.

**Comment by AaronRobinsonMSFT** [comment] 2020-10-15 03:02
@MMW-RobinTaba I finally got to the bottom of the `PlatformNotSupported` exception. This appears to be an oversight that was fixed in .NET 5.0. Support for marshalling `IDispatch` wasn't properly implemented and as such some Office scenarios don't work. Moving over to .NET 5, the above error doesn't occur, but there is something awry with the returned values from Excel. A hyperlink is created as expected but Excel returns an error code regarding something bad. It isn't clear what is wrong because the operation is successful. I am attempting to get to the bottom of this issue. Can you try your scenario on .NET 5 and see if the behavior is the same for you?

**Comment by AaronRobinsonMSFT** [comment] 2020-10-15 03:59
@MMW-RobinTaba I may need to retract my statement about 3.1. I don't fully understand the code above. Please provide a full repo because the code above is attempting to set the result of the `Hyperlinks.Add()` function to the worksheets `UsedRange` property which seems to be readonly - https://docs.microsoft.com/office/vba/api/excel.worksheet.usedrange.

As mentioned, I am not familiar with the Office API so I could be wrong, but that part doesn't look correct. In general I am able to create a Hyperlink without issues on .NET 5.0 for sure. I will go back tomorrow and try 3.1, but since the creation of the hyperlink does work in .ENT 5.0 I am going to close this for now.

**Comment by AaronRobinsonMSFT** [comment] 2020-10-15 06:36
I misunderstood this code. The `UsedRange` is using the property indexers which are `get`/`set` and so the code does make sense in the .NET sense. Will continue to investigate from the Office sense. Reproduction would be helpful to confirm.

**Comment by AaronRobinsonMSFT** [comment] 2020-10-15 18:51
Having debugged through Excel and verified we are not involved at the failure point - see small repro below. This appears to be an issue with the setting of a `Hyperlink` instance on the `UsedRange`. During my investigation it is during the `Hyperlink` instance query prior to updating the `Range` that appears to be causing the issue. I would recommend sending feedback through the "Send a Frown" mechanism in Excel. Feel free to reference this issue and provide my email (github profile) as reference.

Starting from https://github.com/dotnet/samples/tree/master/core/extensions/ExcelDemo.
``` CSharp
Excel.Application excel;
Excel.Workbook workbook;
Excel.Worksheet sheet;
Excel.Range range;

excel = new Excel.Application();
excel.Visible = true;

workbook = excel.Workbooks.Add(Missing.Value);
sheet = (Excel.Worksheet)workbook.ActiveSheet;

//Console.WriteLine("Press 'return' to continue");
//Console.ReadLine();

Excel.Range rng = sheet.Range["A1"];
Excel.Hyperlinks hyperlinks = sheet.Hyperlinks;
var hyperlink = hyperlinks.Add(rng, "http://bing.com");
sheet.UsedRange[2, 2] = hyperlink; // Will fail in Excel process
```

**Closed by AaronRobinsonMSFT** 2020-10-15 18:51 UTC
Labels: area-Interop-coreclr, needs more info, untriaged

**Comment by MMW-RobinTaba** [comment] 2020-10-15 18:56
Thank you very much! 

I solved it with a workaround with the NPOI package. But i will investigate as you said!
