### ISSUE TITLE
System.IO.Compression.ZipFile tests failing on iOS / tvOS

### ISSUE THREAD

**Issue by steveisok** [dotnet/runtime#52471] opened 2021-05-07 20:52 UTC
System.IO.Compression.Tests.ZipFile_ZipArchive_Extract.ExtractToDirectoryExtension_Unicode

https://github.com/dotnet/runtime/blob/d3a72e51641c0bc935bbb3e313df33fe1d9a839a/src/libraries/System.IO.Compression.ZipFile/tests/ZipFileExtensions.ZipArchive.Extract.cs#L24-L33

```
Assert.True() Failure
Expected: True
Actual:   False
```

System.IO.Compression.Tests.ZipFile_Extract.ExtractToDirectoryUnicode

https://github.com/dotnet/runtime/blob/d3a72e51641c0bc935bbb3e313df33fe1d9a839a/src/libraries/System.IO.Compression.ZipFile/tests/ZipFile.Extract.cs#L36-L46

```
Assert.True() Failure
Expected: True
Actual:   False
```

**Comment by filipnavara** [comment] 2021-05-07 22:01
The weird thing is the test was passing when I re-enabled it and it is also consistently passing locally. Could there be some unclean state of the simulators left from some interrupted build?

**Comment by premun** [comment] 2021-05-10 09:50
What is this state? Some files in some directory? Can the test could verify this state?

There is a way to reset the simulator to a completely blank state but it takes several minutes so might add quite a lot of build time.

Or maybe when we have the DevWF enabled and we see something like this, we can reset the simulator in some cases. I will check with the dev wf guys

Can the test verify the state of the directory it is writing into?

**Comment by akoeplinger** [comment] 2021-05-10 15:15
Theoretically if you uninstall an iOS app the files should get cleaned up as well.

**Comment by premun** [comment] 2021-05-10 15:17
mlaunch currently doesn't support uninstallation from simulators. It is a thing I am unsure how it works because when I check the phones they don't have all of the apps on them. I will ask Xamarin how this works.

**Comment by premun** [comment] 2021-05-11 15:04
@akoeplinger I tried to run the test suite several times on the same Helix machine where I saw it failing and couldn't repro.

I tried to also install the app and then call `just-test` and run it several times too without re-install, also no luck.

However, I was checking the implementation of `TempDirectory` which is used in the test and it seems to assume things like max path length and other. I think the filesystem of the simulator is mounted from your own filesystem so maybe we also get issues from things like that?

**Comment by steveisok** [comment] 2021-05-11 17:53
Should we disable the tests for now?

**Comment by premun** [comment] 2021-05-12 11:45
@steveisok @akoeplinger I was asked by @imhameed today why our apps stay open even after XHarness finishes and I said that the BCL apps quit. He said that he noticed they stayed up even after calling the "exit()".

Is it possible we have some regression where in some cases the app won't kill itself and stays running? Maybe it then would leave things behind and fail on re-run and see these issues we have occasionally?

**Comment by steveisok** [comment] 2021-05-12 12:10
If that were the case, I would expect to see random tests fail and then ones logged in this issue occasionally pass.

**Comment by premun** [comment] 2021-05-12 12:16
I suppose you're right.

I meant more if it stays hanging in case it crashed and relies on file system state, maybe it stays behind?
Which wouldn't be true for other apps maybe but doesn't sound plausible...

**Comment by premun** [comment] 2021-05-12 14:10
I pulled the Application folder of a Simulator of one of the Helix machines. There seems to be a folder for every application (there are 251 items). Each has just few kB of some metadata.

[Simulator.tar.gz](https://github.com/dotnet/runtime/files/6466668/Simulator.tar.gz)

The `21AC061F-0299-4598-ABCC-8270C10B9D07` seems to belong to `System.IO.Compression.Tests`.

Furthermore, the apps seem to disappear from the Simulator as I don't see 200 icons there but we do not uninstall them. We however delete the `.app` itself together with the Helix job folder. I suspect that it keeps the metadata only and references the .app folder.
The only app that stayed on the Simulator is `System.Numerics.Vectors.Tests` which we used for validation when installing Xcode so I presume it is still somewhere in the file system (I cannot find where but will try to delete it later).

Further, I found out, that one app had a file created from this line:
https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/libraries/Common/src/System/IO/PathInternal.CaseSensitivity.cs#L44
and it can be found inside of the application's folder in tmp/.

I don't see any files in the Compression app but maybe it never crashed on this particular Simulator and didn't leave anything behind.

**Comment by premun** [comment] 2021-05-12 14:20
Oh, my bad, I just found the app bundles under a different directory inside of the Simulator. So our Simulators are growing and we should definitely reset them every now and then.

**Comment by premun** [comment] 2021-05-12 14:39
I connected to Helix and checked the files belonging to a simulator there. There was **12 GB** worth of files there (251 app bundles).

I checked folder belonging to **System.IO.Compression.Tests.app** and it's 108 MB large with all the files produced during testing:
![image](https://user-images.githubusercontent.com/7013027/117993975-7ceb3400-b340-11eb-9fea-c141b47c950c.png)

**Comment by filipnavara** [comment] 2021-05-13 17:12
I suppose it would be difficult to modify mlaunch to add option to uninstall app before reinstalling (ie. calling `AMDeviceSecureUninstallApplication` before the call to `AMDeviceSecureUninstallApplication`), right?

**Comment by premun** [comment] 2021-05-13 18:06
I don't think `mlaunch` can uninstall Simulator apps at the moment. If it could, we would just do it at the end of the run like we do for devices.

**Comment by filipnavara** [comment] 2021-05-13 18:08
It looks like it cannot do it now but it would likely be fairly trivial to add the support. If it was open source I would whip up a prototype...

**Comment by premun** [comment] 2021-05-13 18:14
I feel like someone told me they don't have the capability because they just didn't need it but I might be wrong.
@rolfbjarne do you know the reason why mlaunch can't uninstall Simulator apps?

I know that they definitely do clean up periodically their simulators so maybe they would benefit from this too.

**Comment by rolfbjarne** [comment] 2021-05-13 18:44
> @rolfbjarne do you know the reason why mlaunch can't uninstall Simulator apps?

We've never needed it, so I've never looked into whether it's possible or not.

We routinely delete all simulators on the bots to make sure we start from a pristine state:

https://github.com/xamarin/xamarin-macios/blob/2b7dc07d20fc06344d7f164af8934f5e755572c2/tools/devops/automation/scripts/bash/clean-bot.sh#L15-L16

I don't think I've seen this take minutes to execute (with a reasonable amount of simulators of course - if it hasn't been run in years who knows how long it takes).

**Comment by filipnavara** [comment] 2021-05-13 18:46
Ah, the code I had in mind was device-only. Then again, the CoreSimulator frameworks has `uninstallApplication:withOptions:error` method on `SimDevice` with the similar signature as the `installApplication` method (`NSString bundleId, NSDictionary options, NSError *error`).

**Comment by steveisok** [comment] 2021-05-13 18:58
Even if it adds a small amount of time, why can't we clean the simulator after each run?

**Comment by imhameed** [comment] 2021-05-13 19:00
For what it's worth, cleaning the simulator with `--reset-simulator` after every test run in my draft PR for the runtime tests adds like 30-40+ minutes to the lane's end-to-end time.

**Comment by steveisok** [comment] 2021-05-13 20:04
What I meant by "each run" is at the end of a given work item.

**Comment by premun** [comment] 2021-05-14 05:59
@steveisok cleaning the simulator is fast. Booting a new one after it's been deleted takes time.

I will check whether we can just erase it and see what data it removes.

**Comment by premun** [comment] 2021-05-14 06:47
@steveisok we could just tag several of the BCL test projects that rely on some file system state with a flag and they would clean the state before they run. This would only clean one machine per build, always different one, and the other work items wouldn't care much since they are passing still. The flagged suites would also then take longer but predictably but we wouldn't slow down every work item and lower the capacity that much.

With the amount of builds we run every day it would clean many machines daily. I pulled some numbers for `osx.1015.amd64.open`:
- We have 60 machines
- We run 60 000 work items per day
- 1 particular suite runs almost 300 times a day

I will still need to explore various ways of cleaning - from erasing data to removing the simulator and adding it back.

**Comment by filipnavara** [comment] 2021-05-14 07:08
Have you considered `xcrun simctl uninstall ...` for the affected apps?

**Comment by premun** [comment] 2021-05-14 07:38
Oh, I didn't know about that! I added it here: https://github.com/dotnet/xharness/pull/598

No idea why it wasn't used

**Comment by premun** [comment] 2021-05-14 10:46
I will purge all simulators on Monday morning when there's no traffic and together with this new change, we should get into a better shape.

**Comment by premun** [comment] 2021-05-18 14:46
New version of XHarness + a purge I did today already seem to improve the situation.

I will give it another few days for the version of XHarness that does the uninstall on Simulators get to every branch and I will do one more purge and we should be good again.

**Comment by premun** [comment] 2021-05-24 15:00
@steveisok can we close this? I went through some of the latest builds and they seem in a good shape.

No signs of these failures anymore

**Comment by steveisok** [comment] 2021-05-24 15:06
The tests are still being skipped.  I'll throw up a PR to run them and we'll see if they pass.

**Comment by steveisok** [comment] 2021-05-24 15:12
https://github.com/dotnet/runtime/pull/53176

**Closed** 2021-05-24 21:20 UTC
Labels: area-System.IO.Compression, os-ios, os-tvos, untriaged
