### ISSUE TITLE
[API Proposal]: `System.Boolean` should implement `System.IFormattable`

### ISSUE THREAD

**Issue by colejohnson66** [dotnet/runtime#79942] opened 2022-12-23 19:55 UTC
### Background and motivation

As the title implies, `bool` should implement `IFormattable`. Even if it ignores the `format` parameter, it would add consistency to the BCL.

Our program uses a settings system with two types called `Setting`:

```csharp
// uses `object` for storage to allow hiding generics
public class Setting
{
    public object Value { get; set; } // actual code enforces type safety
}

public class Setting<T> : Setting
    where T : IFormattable, IParsable<T>
{
    public new T Value
    {
        get => (T)base.Value;
        set => base.Value = value;
    }
}
```

We can use them as so:

```csharp
public Setting<int> MyIntSetting = new(nameof(MyIntSetting), @default: 5);
```

Currently, we are forced to add a `BoolWrapper` type to provide the necessary functionality for boolean settings:

```csharp
public struct BoolWrapper : IFormattable, IParsable<BoolWrapper>
{
    public bool Value { get; }

    public BoolWrapper(bool value)
    {
        Value = value;
    }

    public static implicit operator bool(BoolWrapper rhs) =>
        rhs.Value;

    public static implicit operator BoolWrapper(bool rhs) =>
        new(rhs);

    public static BoolWrapper Parse(string s, IFormatProvider? provider) =>
        new(bool.Parse(s)); // handles exceptions for us

    public static bool TryParse(string? s, IFormatProvider? provider, out BoolWrapper result)
    {
        if (bool.TryParse(s, out bool parsed))
        {
            result = new(parsed);
            return true;
        }

        result = default;
        return false;
    }

    public override string ToString() =>
        Value.ToString();

    public string ToString(string? format, IFormatProvider? formatProvider) =>
        Value.ToString(formatProvider);
}
```

### API Proposal

```csharp
namespace System;

public readonly struct Boolean : IFormattable
{
    public string ToString(string? format, IFormatProvider? formatProvider) =>
        m_value.ToString(formatProvider);
}
```

### API Usage

See above.

### Alternative Designs

Currently, the alternative is to provide a boolean wrapper as stated above.

### Risks

None.

**Comment by vcsjones** [comment] 2022-12-23 20:00
This appears to be a duplicate of https://github.com/dotnet/runtime/issues/67388. That issue should be used for discussion on implementing IFormattable for Boolean.

**Closed** 2022-12-23 20:01 UTC
Labels: api-suggestion, untriaged
