### ISSUE TITLE
msbuild Publish fails with Error: Invalid directory size.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#72425] opened 2022-07-19 02:27 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/msbuild-Publish-fails-with-Error:-Invali/10090912)._

---
[severity:I'm unable to use this version] [regression] [worked-in:16 to 17]
We are switching from VS 2019/.NET 5 to VS 2022/.NET 6 in our projects. Unfortunately, we now get an exception with the publish target. The build target works fine and the application works normally.
When publishing with the following pubxml

  
    Release
    x64
    ..\bin\Release\publish\
    FileSystem
    net6.0-windows
    win-x64
    true
    False
    True
    False
  

you end up in the exception

...
3>--out:"obj\x64\Release\win-x64\R2R\ActiproSoftware.Shared.Wpf.dll"
3>C:\Program Files (x86)\Actipro Software\WPF-Controls\v14.1.0601\Assemblies\ActiproSoftware.Shared.Wpf.dll
3>
3>Error: Invalid directory size.
3>System.BadImageFormatException: Invalid directory size.
3>   at System.Reflection.PortableExecutable.PEReader.ReadDebugDirectory()
3>   at Internal.TypeSystem.Ecma.PortablePdbSymbolReader.TryOpenEmbedded(PEReader peReader, MetadataStringDecoder stringDecoder)
3>   at ILCompiler.CompilerTypeSystemContext.AddModule(String filePath, String expectedSimpleName, Boolean useForBinding, ModuleData oldModuleData)
3>   at ILCompiler.CompilerTypeSystemContext.GetOrAddModuleFromPath(String filePath, Boolean useForBinding)
3>   at ILCompiler.CompilerTypeSystemContext.GetModuleFromPath(String filePath)
3>   at ILCompiler.Program.Run(String[] args)
3>   at ILCompiler.Program.Main(String[] args)
3>C:\Users\wolfgang\.nuget\packages\microsoft.netcore.app.crossgen2.win-x64\6.0.6\tools\crossgen2.exe --targetos:windows
3>--targetarch:x64
3>-O
...

This old third-party DLL from 2014 is included in the project as a reference
    
      C:\Program Files (x86)\Actipro Software\WPF-Controls\v14.1.0601\Assemblies\ActiproSoftware.Shared.Wpf.dll

---
#### Wolfgang Kordts on 7/9/2022, 01:48 AM: 

(private comment, text removed)
#### Feedback Bot on 7/10/2022, 07:20 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 7/12/2022, 08:48 PM: 

(private comment, text removed)
#### Wolfgang Kordts on 7/14/2022, 00:47 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 7/12/2022, 08:48 PM: 

(private comment, text removed)
#### Wenwen Fan [MSFT] on 7/14/2022, 07:51 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by wolfkor** [comment] 2022-07-19 19:55
the move has really changed the description ;-) I hope you got the attached zip file to reproduce it.

**Comment by ivdiazsa** [comment] 2022-07-25 17:43
Hi @wolfkor, unfortunately your zip was lost somewhere in the move. Do you think you could post it again here? Thanks!

**Comment by wolfkor** [comment] 2022-07-26 16:11
[R2RProblem.zip](https://github.com/dotnet/runtime/files/9191495/R2RProblem.zip)

**Comment by AntonLapounov** [comment] 2022-08-04 19:48
The Debug Directory size in the `ActiproSoftware.Shared.Wpf.dll` binary is corrupted (which might be caused by running some old obfuscation tool).  You can fix it by opening the file in a hex editor and changing the byte at offset `0x12c` from `0x96` to `0x1c`.

**Comment by wolfkor** [comment] 2022-08-05 07:57
That's not really a solution. It is a third-party dll installed on many build agents. And why does it work with .NET 5?

**Comment by AntonLapounov** [comment] 2022-08-06 20:16
By default, .NET 5 used a different ReadyToRun compiler, which would produce the diagnostic message below and ignore the invalid debug directory:
```
IMAGE_DIRECTORY_ENTRY_DEBUG size (150) should be a multiple of 28
Native image obj\x64\Debug\net5.0-windows\win-x64\R2R\ActiproSoftware.Shared.Wpf.dll generated successfully.
```
Here is the compiler code that performed the check: https://github.com/dotnet/runtime/blob/4aadfea70082ae23e6c54a449268341e9429434e/src/coreclr/src/zap/zapheaders.cpp#L586-L588
We might want to do the same in the new compiler.  Given that .NET 6 was released in November 2021 and this is the first report of the issue (as far as I know), only few old assemblies may be affected.  Here is the list of your options:
* Exclude the assembly from ReadyToRun compilation by adding the following lines to the project file:
```
<ItemGroup>
  <PublishReadyToRunExclude Include="ActiproSoftware.Shared.Wpf.dll" />
</ItemGroup>
```
* Fix the invalid byte in the assembly as mentioned above.
* Upgrade the assembly to any recent version.  I verified that [recent versions](https://www.nuget.org/packages/ActiproSoftware.Controls.WPF.Shared/) have a correct debug directory.
* Continue using .NET 5 and wait until the issue is fixed in .NET 7.

Note that using an invalid PE file may crash other tools that read the debug directory, such as debuggers and profilers.  For instance, `link.exe /dump /headers ActiproSoftware.Shared.Wpf.dll` crashes the linker when it tries to dump the content of the debug directory.

**Comment by wolfkor** [comment] 2022-08-10 17:52
Going back to .NET 5 or waiting for .NET 7 isn't currently an option. So I tried to use the PublishReadyToRunExclude variant. Unfortunately this doesn't work because I get the invalid directory size error now with self-built DLLs that use ActiproSoftware DLLs.
We plan to upgrade ActiproSoftware but it will take longer due to massive changes since 2014. Until then I have no reasonable solution.

**Comment by wolfkor** [comment] 2022-08-12 23:55
I hope you seriously consider fixing this in .NET 6 as well.

**Closed** 2022-08-15 16:29 UTC
Labels: os-windows, area-crossgen2-coreclr, in-pr
