### ISSUE TITLE
Add LINQ methods SelectMin() and SelectMax()

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#40406] opened 2020-08-05 19:58 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1086036/add-linq-methods-selectmin-and-selectmax.html)._

---
<p>Let's say you have a list of objects and you want to get the object / entry with the highest or lowest value. At the moment there are no direct methods for this.</p><p>There are only the methods Min() and Max() which return the actual highest or lowest value, but not the object of it.</p><p>Therefore I'd suggest the LINQ methods <strong>SelectMin</strong><strong>()</strong> and <strong>SelectMax</strong><strong>().<br></strong></p><p>Both are pretty straightforward. It selects the item with the lowest (min) or highest (max) value.</p><p>Example:</p><pre>internal class Program
{
    private static void Main(string[] args)
    {
        var weapons = new List&lt;Weapon&gt;
        {
            new Weapon { Name = &quot;Test1&quot;, Description = &quot;test desc1&quot;, Power = 11},
            new Weapon { Name = &quot;Test2&quot;, Description = &quot;test desc2&quot;, Power = 22},
            new Weapon { Name = &quot;Test3&quot;, Description = &quot;test desc3&quot;, Power = 33},
            new Weapon { Name = &quot;Test4&quot;, Description = &quot;test desc4&quot;, Power = 44},
            new Weapon { Name = &quot;Test5&quot;, Description = &quot;test desc5&quot;, Power = 55},
        };

        var highestPower = weapons.Max(x =&gt; x.Power); // returns 55
        var mostPowerfulWeapon = weapons.SelectMax(x =&gt; x.Power); // Should return the last weapon object with Power == 55
        var noobyWeapon = weapons.SelectMin(x =&gt; x.Power); // should return the first weapon with Power == 11
    }
}

internal class Weapon
{
    public string Name { get; set; }
    public string Description { get; set; }
    public int Power { get; set; }
}
</pre><p>At the moment, you could use Max() before and then use the result for a First() call or use the method Aggregate(). Both solutions have overhead and are harder to read than my suggested solution.</p>

---
#### Feedback Bot on 6/22/2020, 00:04 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.
#### Dean Goddard on 6/26/2020, 05:23 AM: 

It&#39;s one of the hardest things to do with normal SQL getting access to the rest of the row that where a column has the highest/lowest value.  So I support this idea for LINQ.

**Comment by Clockwork-Muse** [comment] 2020-08-05 20:23
AKA `MinBy`/`MaxBy`.
Duplicate of:
#14753
#19522
#27687
#32471

**Comment by tthiery** [comment] 2020-08-06 14:15
Is not `Select` / `GroupBy` / ... more applicable to "map" style operations while `Where` / `First` / ... are focused on the "filter" style operations? With the use case above I would understand that this is more a `FirstMax` situation?

**Comment by Clockwork-Muse** [comment] 2020-08-06 15:30
@tthiery - Which is why this operation is often named `MaxBy`.  (Due to implementation details it may consistently return first/last, but that maybe shouldn't be relied upon, and can't if implemented for PLINQ).

**Comment by Clockwork-Muse** [comment] 2020-08-06 15:34
Dean Goddard - while this isn't necessarily easy to do currently in LINQ-to-SQL, there's a number of easy ways to do this in raw SQL, depending on your exact needs (and which specific RDBMS you're using).  Note that LINQ-to-SQL would have to be set up to return the optimized SQL anyways, which may not always be possible.

**Comment by Zerotask** [comment] 2020-08-06 22:11
> Is not Select / GroupBy / ... more applicable to "map" style operations while Where / First / ... are focused on the "filter" style operations? With the use case above I would understand that this is more a FirstMax situation?

I suggested this addition and you are right, FirstMax() and FirstMin() would be a better naming for that. I named it after a natural speaking perspective, where you want to select an entry with the highest or lowest value, which suggest, that there is only **one** entry (=first).

>  there's a number of easy ways to do this in raw SQL

Sure, you can always work with raw SQL, but personally I like the concept of LINQ and would prefer a simple method for that use case.

**Comment by hez2010** [comment] 2020-08-07 02:56
Actually you can `OrderBy` then `Select`.

**Comment by Clockwork-Muse** [comment] 2020-08-07 15:48
@hez2010 - A better workaround would be `OrderBy(<whatever>).First()`, especially since we optimized that internally to avoid the otherwise necessary `O(n log n)` time and `O(n)` additional space.

**Comment by NetMage** [comment] 2020-09-25 21:22
> I suggested this addition and you are right, FirstMax() and FirstMin() would be a better naming for that. I named it after a natural speaking perspective, where you want to select an entry with the highest or lowest value, which suggest, that there is only **one** entry (=first).

I disagree - what would `LastMax()` and `LastMin()` be, and how would they differ from `FirstMax()` and `FirstMin()`? I think `MaxBy` and `MinBy` are best.

**Comment by Zerotask** [comment] 2020-09-25 21:32
@NetMage I disagree with you. FirstMin() is related to the First() method which intends that there is only 1 result. MinBy() and MaxBy() are possible alternative names but it's a personal preference. I think MinBy() rather intends that you get the lowest value and not 1 result with a lowest value.

**Comment by Clockwork-Muse** [comment] 2020-09-25 22:46
@Zerotask - In pretty much all of computer programming, `max` and `min` operations are always understood as "a max" and "a min", because there can always be duplicate values.  Whether it returns first/last of the duplicates is a (rarely important) implementation detail.  Getting "all results with the minimum value" is a much more difficult operation.

**Comment by ilelann** [comment] 2020-10-05 08:59
> 
> 
> @hez2010 - A better workaround would be `OrderBy(<whatever>).First()`, especially since we optimized that internally to avoid the otherwise necessary `O(n log n)` time and `O(n)` additional space.

From the code https://github.com/microsoft/referencesource/blob/3b1eaf5203992df69de44c783a3eda37d3d4cd10/System.Core/System/Linq/Enumerable.cs#L2547 it is not obvious to me. What am I missing ?

**Comment by Clockwork-Muse** [comment] 2020-10-05 16:00
@ilelann - I've been bitten by that too, especially since search engines seem to index the reference source, but not the git repository (as much) - for obvious reasons.

**Comment by eiriktsarpalis** [comment] 2020-10-13 13:28
Duplicate of #27687.

**Closed by eiriktsarpalis** 2020-10-13 13:28 UTC
Labels: api-suggestion, area-System.Linq
