### ISSUE TITLE
How to jitdump inlining behavior?

### ISSUE THREAD

**Issue by L2** [dotnet/runtime#52722] opened 2021-05-13 19:51 UTC
I'm running the dotnet/performance benchmark `System.Collections.ContainsTrue<Int32>.SortedSet(Size: 512)` using both Release and Debug configurations. Among other things happening, there is a call to `Compare` inside `FindNode`.

In the Release config, `Compare` gets inlined inside `FindNode`.
In the Debug config, it does not. It's a separate call to `Compare`.

How would I go about viewing how the JIT does inlining? I take it that Jitdumps are only available in Debug config, so attempting the following doesn't show any inlining information:
```
Using the Debug build:
$env:COMPlus_JitDump="FindNode"
$env:COMPlus_JitDisasm="FindNode"
$env:COMPlus_JitDiffableDasm=1
$env:COMPlus_JitDumpASCII=0
$env:COMPlus_JitPrintInlinedMethods=1
$env:COMPlus_TieredCompilation=0
```

Is there a way to view Jitdumps of the Release config?

I ask because I noticed a change in how a method is inlined in this benchmark for two different .NET builds and I'd like to view what steps the JIT took to make the inline happen.

Thanks

**Comment by SingleAccretion** [comment] 2021-05-13 20:10
> Is there a way to view Jitdumps of the Release config?

Not the full dump, but I believe you can still see the inlining information that the Jit emits via ETW (so, PerfView). However, I would personally utilize the `--coreroot` argument to point the runner at a Checked build of CoreCLR and get the full dump with the usual environment variables. [See here](https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md#dotnet-runtime-prerequisites).

> In the Debug config, it does not. It's a separate call to Compare.

Note that the Jit does very little if any optimizations for Debug code, so I would think that's expected?

**Comment by AndyAyersMS** [comment] 2021-05-21 01:54
`JitPrintInlinedMethods` is now a methodset config, so you will want to use:
```
$env:COMPlus_JitPrintInlinedMethods=*
```
As @SingleAccretion has noted, running against debug builds of assemblies will disable all inlining.

Also those `ContainsTrue` benchmarks seem to be finicky, eg recent history on windows x64 (intel):

![newplot (25)](https://user-images.githubusercontent.com/10121823/119070273-83ab2400-b99c-11eb-8b6a-8b87ea60f517.png)

and linux (x64)

![newplot (26)](https://user-images.githubusercontent.com/10121823/119070373-b8b77680-b99c-11eb-9fe1-0d1c253212a7.png)

**Comment by danmoseley** [comment] 2021-05-21 03:04
@DrewScoggins do you think those graphs show a regression in April? I don't see an issue so maybe you determined it's not?

**Comment by DrewScoggins** [comment] 2021-05-21 16:50
Given the general instability of these tests, the fact that neither regressed to a new global maximum, and that there does not seem to be any commit in the range where the jump occurred we decided that these were not regressions. We almost certainly looked at them in triage though.

**Comment by BruceForstall** [comment] 2021-06-02 17:07
Since this was a question that appears to be answered, I'm going to close the issue.

**Closed by BruceForstall** 2021-06-02 17:07 UTC
Labels: area-CodeGen-coreclr, untriaged
