### ISSUE TITLE
[.NET 6] CultureInfo constructor does not throw CultureNotFoundException for unknown culture name

### ISSUE THREAD

**Issue by danylofitel** [dotnet/runtime#57310] opened 2021-08-12 19:31 UTC
### Description

In .NET 5 and older versions of .NET Core and Framework this code throws `CultureNotFoundException` ("Culture is not supported" message).

`CultureInfo culture = new CultureInfo("broken");`

In .NET 6 it does not throw and creates a `CultureInfo` instance with "broken" name.

![image](https://user-images.githubusercontent.com/3258785/129255853-57b8a248-71bf-4b0d-8a94-bc02832dfeb0.png)

When adding an unknown region component, the constructor still succeeds, but `CompareInfo` property starts throwing `CultureNotFoundException`.

`CultureInfo culture = new CultureInfo("broken-CULTURE");`

The resulting culture's name is "broken--CULTURE".

![image](https://user-images.githubusercontent.com/3258785/129256804-48f97b30-2e5d-48af-be10-e171e48a7ad2.png)

### Configuration
.NET versions: .NET 6 preview 6 and 7. Did not test earlier previews.
OS: latest versions of Windows 10 and 11 with OS language set to English (United States).
Architecture: x64.
All other parameters are set to default, this reproes on a new console app on a fresh Windows installation.

### Regression?

I did not find any breaking change notifications in public documentation for `CultureInfo` in .NET 6.

**Comment by safern** [comment] 2021-08-17 05:21
This was a regression from 5.0. This was caused by: https://github.com/dotnet/runtime/commit/805e288baff174a3d8cdd4bf4c7f1bc9985f4767

@tarekgh and I started looking at it and the fix isn't that simple as we are seeing some other issues fallout. Will mark as blocking and will assign @tarekgh as I'll be gone starting tomorrow.

**Comment by tarekgh** [comment] 2021-08-20 22:18
fixed by the PR https://github.com/dotnet/runtime/pull/57853

**Closed by tarekgh** 2021-08-20 22:18 UTC
Labels: area-System.Globalization, blocking-release, regression-from-last-release
