### ISSUE TITLE
localized resource assembly does not work due to change in fallback of zh-* cultures

### ISSUE THREAD

**Issue by chenyj796** [dotnet/runtime#44502] opened 2020-11-11 00:58 UTC
### Description
In .NET 5.0, the localized resource assembly does not work.
When run the ConsoleApp16, it will show an english string although has a zh-Hans resource.
[ConsoleApp16.zip](https://github.com/dotnet/runtime/files/5520956/ConsoleApp16.zip)

**Comment by tarekgh** [comment] 2020-11-12 00:02
@chenyj796 I downloaded your project and I cannot reproduce the problem. I just updated the code a little bit to ensure the UI culture is set correctly before the lookup. something like:

```C#
namespace ConsoleApp16
{
    class Program
    {
        private static void DumpString(string s)
        {
            Console.Write($"{s}: ");
            foreach (char c in s)
            {
                Console.Write($"{(int)c:x4}, ");
            }
            Console.WriteLine();
        }

        static void Main(string[] args)
        {
            CultureInfo.CurrentUICulture = CultureInfo.GetCultureInfo("zh-Hans");
            DumpString(Properties.Resources.String1);

            CultureInfo.CurrentUICulture = CultureInfo.GetCultureInfo("en-US");
            DumpString(Properties.Resources.String1);
        }
    }
}
```

Then when I run it, I am getting the following results as expected:

```
中文: 4e2d, 6587, 
English: 0045, 006e, 0067, 006c, 0069, 0073, 0068,
```

Please double check the following when you run your app:

- After compiling and publishing, ensure the file `zh-Hans\ConsoleApp16.resources.dll` is exist under the app published root folder.
- Ensure `CultureInfo.CurrentUICulture` have the correct culture you want the resource lookup performed with.

**Comment by tarekgh** [comment] 2020-11-12 00:18
I think I understand what was wrong, I believe your default UI culture is something like `zh-CN` and you are creating a resources with `zh-CHS`. The `zh-CHS` is not a parent to `zh-CN` now and that is why cannot find the resource for `zh-Hans`. 

You can solve this problem by having `zh` resources instead of `zh-Hans`. I mean just rename the file `Resources.zh-Hans.resx` to `Resources.zh.resx`. Or you can in the code do 

```C#
CultureInfo.CurrentUICulture = CultureInfo.GetCultureInfo("zh-Hans");
```

**Comment by chenyj796** [comment] 2020-11-12 00:31
@tarekgh If I set the TargetFramework to netcoreapp3.1 in csproj file, it works fine. Is there anything changed?

**Comment by tarekgh** [comment] 2020-11-12 00:40
@chenyj796 yes some change done in 5.0 when switched to use ICU library for globalization instead of NLS Win32 APIs. That changed the parent chain for cultures like `zh-CN`. the parent of `zh-CN` used to be `zh-Hans` and now it is `zh`. I have provided a workaround that I hope will work for you. meanwhile I'll try to restore the old behavior in first servicing release `5.0.1` to avoid such issue. 

Also, you have the option to switch back using NLS to get the old behavior. You can do that by adding the following config switch to your csproj file:

```Xml
  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.Globalization.UseNls" Value="true" />
  </ItemGroup>
```

**Comment by chenyj796** [comment] 2020-11-12 02:00
@tarekgh Thanks, I got it.

**Comment by tarekgh** [comment] 2020-11-18 00:13
This should be fixed by https://github.com/dotnet/runtime/pull/44620.

**Closed by tarekgh** 2020-11-18 00:13 UTC
Labels: area-System.Resources, question, regression-from-last-release
