### ISSUE TITLE
The built-in CCW/RCW system on .NET 5 should return E_NOINTERFACE for C#/WinRT interfaces

### ISSUE THREAD

**Issue by smourier** [dotnet/runtime#46264] opened 2020-12-20 10:31 UTC
### Description

My real project is more complex than this but I have managed to extract a reproducing smaller one.

Here is a C# console app, using C#/WinRT projection.

	<Project Sdk="Microsoft.NET.Sdk">

	  <PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net5.0-windows10.0.17763.0</TargetFramework>
	  </PropertyGroup>

	</Project>

Program.cs:
	
	using System;
	using System.Runtime.InteropServices;
	using Windows.Data.Xml.Dom;

	namespace ConsoleApp1
	{
		class Program
		{
			static void Main()
			{
				var n = new Node();
				Node(n);
			}

			// calling a native Dll using interop
			[DllImport(@"..\..\..\..\x64\Debug\Dll1.dll")]
			private static extern int Node([MarshalAs(UnmanagedType.IUnknown)] object punk);
		}

		// I used IXmlNodeSelector as an example, other WinRT interfaces create the same issue.
		public class Node : IXmlNodeSelector
		{
			// we won't even get to the throws
			public XmlNodeList SelectNodes(string xpath) => throw new NotImplementedException();
			public IXmlNode SelectSingleNodeNS(string xpath, object namespaces) => throw new NotImplementedException();
			public XmlNodeList SelectNodesNS(string xpath, object namespaces) => throw new NotImplementedException();
			public IXmlNode SelectSingleNode(string xpath) => throw new NotImplementedException();
		}
	}

In my C++ native "Dll1.dll" , I just have this code:
	
	extern "C" __declspec(dllexport) HRESULT __stdcall Node(IUnknown * unk)
	{
		IXmlNodeSelector* selector; // from ABI::Windows::Data::Xml::Dom
		HRESULT hr = unk->QueryInterface(IID_PPV_ARGS(&selector));
		if (SUCCEEDED(hr))
		{
			// This is where the crash happens
			hr = selector->SelectSingleNode(NULL, NULL);
			selector->Release();
		}
		return S_OK;
	}

This is what I see on the console when SelectSingleNode is called.

		Fatal error. Internal CLR error. (0x80131506)
		Repeat 2 times:
		--------------------------------
		   at ConsoleApp1.Program.Node(System.Object)
		--------------------------------
		   at ConsoleApp1.Program.Main()

### Configuration

.NET 5.0.1, Windows 10 20H2 19042.686 64bits. Visual Studio 2019 16.8.3.

### Regression?

All this works fine with .NET Framework (and I think it also worked with .NET Core 3.1) with the "old" *Microsoft.Windows.SDK.Contracts* nuget.

### Other information

This is what I see in WinDBG, I think for some reason the CCW is called on its IDispatch vtable implementation (?) and crashes on IID comparison (of course). Looks like the wrong vtable is returned when inheritance tree is complex?

![winrtcomcore](https://user-images.githubusercontent.com/5328574/102710888-f3b26280-42b5-11eb-8cb4-539910e622b1.png)

There's a reproducing project and solution, just build it in X64 and run.
[WinRTComCore.zip](https://github.com/dotnet/runtime/files/5720782/WinRTComCore.zip)

**Comment by janvorli** [comment] 2020-12-21 16:33
cc: @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment] 2020-12-21 18:07
@smourier This is "by-design". The reason it is "by-design" is that the `Node` interop code isn't being generated for the WinRT interface in question. There is [no longer built-in knowledge of the WinRT](https://github.com/dotnet/runtime/issues/37672) inheritance (i.e. `IInspectable` et al) in the CLR. What this means is that the managed type (i.e. `Node`) is laid out as if it were being exposed to COM (i.e. `IUnknown` and `IDispatch`), but as pointed out it is a WinRT type that has much more going on. Note that the built-in CCW/RCW system is no longer used for WinRT so in order to acquire the interop code one much use [C#/WinRT](https://github.com/microsoft/CsWinRT/) to generate that.

I assume the desire here is to implement a WinRT interface in C#. That support is something the C#/WinRT team is working on and can be followed at: https://github.com/microsoft/CsWinRT/issues/309.

**Comment by smourier** [comment] 2020-12-21 18:24
It's by design that .NET 5 doesn't work where it's predecessors did? And when I say doesn't work, it doesn't just raise some "not supported exception" or "invalid cast" / E_NOINTERFACE, no, instead it just crashes badly because it poorly implements COM interfaces.

This is very disappointing and is a showstopper for .NET 5 in some interop scenarios that used to work fine with .NET Core 3 and .NET Framework for ages. And we can't even use the old Microsoft.Windows.SDK.Contracts nuget.

**Comment by AaronRobinsonMSFT** [comment] 2020-12-21 19:10
>It's by design that .NET 5 doesn't work where it's predecessors did?

In this case yes. That is why the referenced issue is marked "Breaking change".

>And when I say doesn't work, it doesn't just raise some "not supported exception" or "invalid cast" / E_NOINTERFACE, no, instead it just crashes badly because it poorly implements COM interfaces.

That is a fair point. We might be able to detect this actually. It would require some investigation to realize that an interface isn't a pure `IUnknown` and handle that differently.

I will reopen this and update the title to reflect the possible fix for this scenario.

**Comment by AaronRobinsonMSFT** [comment] 2020-12-22 17:42
@scottj1s @jkoritzinsky Any thoughts on the best way to detect the implemented interface (e.g. `IXmlNodeSelector`) is a WinRT interface?

**Comment by smourier** [comment] 2021-02-10 17:20
Is the new version of C#/WinRT https://blogs.windows.com/windowsdeveloper/2021/02/09/c-winrt-authoring-preview-and-updates/ (with "authoring" support) supposed to allow me to implement a WinRT interface in C# and fix that issue?

**Comment by AaronRobinsonMSFT** [comment] 2021-02-10 17:37
@smourier I honestly don't know. All WinRT support in .NET is now handled by the C#/WinRT team and tracked in that repo. The .NET runtime team has no direct ownership of WinRT support anymore as it is being driven by the [Microsoft organization](https://github.com/microsoft). This isn't to say the .NET runtime team doesn't play a role but all [WinRT specific code](https://github.com/dotnet/runtime/issues/37672) has been excised from the .NET runtime code base and as such how WinRT APIs are projected and work within .NET is now in the purview of the WinRT API owners (i.e. the Microsoft organization).

I believe your specific question is tracked by https://github.com/microsoft/CsWinRT/issues/309.

**Comment by smourier** [comment] 2021-02-10 17:42
@AaronRobinsonMSFT - ok thanks, at least you answer my questions quickly :-)

**Comment by AaronRobinsonMSFT** [comment] 2021-02-10 17:47
@smourier Feel free to tag me on these sorts of questions in the C#/WinRT repo. I can poke people internally if need be - even though another team does own this experience I accept I am likely much closer to them than non-Microsoft employees :-)

**Comment by AaronRobinsonMSFT** [comment] 2021-04-13 05:01
@smourier I've looked at this again and it is really hard to see how the runtime can do the right thing in this case. The issue is entirely around how the built-in system degrades to the point of "do something at all costs". The declaration of `IXmlNodeSelector` doesn't indicate [`ComInterfaceType`](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.cominterfacetype) which means it defaults to `Dual` and that indicates the interface inherits from `IDispatch` &ndash; which is what is being observed above. We could attempt to interrogate the type further and see if it is a C#/WinRT type but that would require reading custom attributes which is very expensive and not something we would want to do on every `QueryInterface`. Alternatively, during type load we can see if it has some C#/WinRT attribute and store it, but then that couples the runtime to an external source generator and would violate a goal of the entire `ComWrappers` approach. The only thing I can think of is the C#/WinRT tool could mark all WinRT interfaces as follows:

```csharp
[InterfaceTypeAttribute(ComInterfaceType.InterfaceIsIInspectable)]
interface ISomeWinRTInterface { ... }
```

This would effectively tell the built-in system the type isn't supported &ndash; which seems like the right thing to do because it would fail as you would've expected. However, I'm not sure of the side effects of that because the built-in system tries very hard and threading that needle is non-trivial. I've checked that the code paths that check for this enum appear reasonable but we would need to do a fair bit of validation to ensure there aren't unintended consequences to adding that enum to the types.

I am going to close this issue since I don't think this is something that will be much of an issue in 2 to 3 years. Given that timeframe, creating some fancy solution in the runtime doesn't appear appropriate. I will however bring this up at the next C#WinRT sync and ask about exploring the above option. It might also be beneficial, if this is still a priority for you, to file an issue in the [C#/WinRT repo](https://github.com/microsoft/CsWinRT) and reference this thread so I can demonstrate some real user impact.

**Closed by AaronRobinsonMSFT** 2021-04-13 05:01 UTC
Labels: area-Interop-coreclr

**Comment by Scottj1s** [comment] 2021-04-13 21:47
Sorry I missed this conversation while it was happening.  @AaronRobinsonMSFT, could InterfaceTypeAttribute be modified to apply to assemblies as well?  It would lessen the impact to apply it to projection assemblies and winrt.runtime.dll once.

**Comment by AaronRobinsonMSFT** [comment] 2021-04-13 21:52
>could InterfaceTypeAttribute be modified to apply to assemblies as well? It would lessen the impact to apply it to projection assemblies and winrt.runtime.dll once.

I think that would be a reasonable request if we can validate marking these interfaces with `ComInterfaceType.InterfaceIsIInspectable` enables a graceful failure. I thought the vast majority of types are autogenerated, is it that bad to add the attribute to them?

**Comment by Scottj1s** [comment] 2021-04-13 21:56
fair question - we can add the attribute to each interface and measure the overehad
