### ISSUE TITLE
The `JsonIgnoreCondition.WhenWritingDefault` in code summary comment misleading

### ISSUE THREAD

**Issue by GF-Huang** [dotnet/runtime#81881] opened 2023-02-09 11:29 UTC
![image](https://user-images.githubusercontent.com/4510984/217800482-f81c3144-0823-4e81-b87a-906937b6e071.png)

![image](https://user-images.githubusercontent.com/4510984/217800620-54a6fe35-668c-4779-9219-84c849e75a15.png)

refer: https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonignorecondition?view=net-6.0

**Comment by eiriktsarpalis** [comment] 2023-02-09 12:17
I can reproduce this using SourceLink in .NET 6 applications:

![image](https://user-images.githubusercontent.com/2813363/217810333-e2adf71c-d1ee-4b5d-a4fc-f43f4fa1be7a.png)

Curiously enough, there's nothing wrong with the XML comments in release/6.0:

https://github.com/dotnet/runtime/blob/a7442889903910e6a44082386ea9ae463673ba8b/src/libraries/System.Text.Json/Common/JsonIgnoreCondition.cs#L28

And it doesn't look like these have been changed since the feature got introduced. @ViktorHofer any clue what might be causing this?

**Comment by GF-Huang** [comment] 2023-02-09 12:20
May be caused by localization. I am using VS2022 in Simplified Chinese environment. 
```
Microsoft Visual Studio Community 2022 (64 bit) - Current 17.4.4
```

**Comment by ViktorHofer** [comment] 2023-02-09 12:38
The source of truth for API documentation in runtime isn't in-code triple slash xml. Instead that documentation lives in a completely different repository. It has been like this for years. We are currently working on fixing that. cc @carlossanlop

In this case, we would probably need a new intellisense package for release/6.0 with the change.

**Comment by eiriktsarpalis** [comment] 2023-02-09 12:46
It looks this particular piece of documentation got fixed recently with https://github.com/dotnet/dotnet-api-docs/pull/8416.

> we would probably need a new intellisense package for release/6.0

Would this change meet the bar for servicing? It wouldn't seem so to me.

**Comment by eiriktsarpalis** [comment] 2023-02-10 11:24
Closing since this has been addressed in .NET 7.

**Closed by eiriktsarpalis** 2023-02-10 11:24 UTC
Labels: documentation, area-System.Text.Json
