### ISSUE TITLE
JsonSerializer allocates too much memory when serializing html strings

### ISSUE THREAD

**Issue by lichutin-st** [dotnet/runtime#62900] opened 2021-12-16 12:42 UTC
### Description

I've just encountered a strange behavior of `System.Text.Json.JsonSerializer.Serialize(...)` for objects that contain html strings.

Code sample:

```
using System;
using System.Text;
using System.Text.Json;

namespace SystemTextJson_LargeStrings
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var sb = new StringBuilder();
            for (int i = 0; i < 1_000_000; i++)
            {
                sb.Append(@"<p>some text goes there</p><p>some text goes there</p>");
            }

            var someObject = new {
                StringField = sb.ToString()
            };
            var json = JsonSerializer.Serialize(someObject);

            Console.WriteLine("Hello World!");
        }
    }
}

```

The string length is about 54.000.000. Surprisingly, calling `JsonSerializer.Serialize(someObject);` allocates about 2 GB of memory which doesn't look right.

Serializing to a stream allocates the same amount of memory.

BTW, If I remove html tags from the string (by replacing them with another chars to preserve the string length), code above allocates only 650 MB (which is also a large amount of memory though)

### Configuration

.net6.0, windows, x64  

### Data

![image](https://user-images.githubusercontent.com/68215827/146373228-e3fa64f3-cbce-4e0b-8d31-2d2dff477ae4.png)

### Analysis

I tried .NET Object Allocation Tracking profiler and it shows that large char and byte arrays are allocated (array length is ~ 537.000.000)
![image](https://user-images.githubusercontent.com/68215827/146373942-abdf8f0a-281c-4f32-bc64-58c7f4723600.png)

**Comment by EgorBo** [comment] 2021-12-16 13:32
You need to pass
```csharp
new JsonSerializerOptions { Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping }
```
if you don't want it to escape `<` and `>` characters and waste performance there

**Comment by lichutin-st** [comment] 2021-12-16 14:04
Yeah, that improves performance but the code still allocates a lot of objects/memory.
E.g. 
```
Type	                        Bytes
 System.Byte[268435456]	 	268 435 480
```

**Comment by krwq** [comment] 2021-12-16 15:02
for .NET 5 it seems it allocates only 183MB which seems acceptable, with the switch from @EgorBo on .NET 5 I'm seeing 105.5MB. Seems like possible regression to me... @layomia?

**Comment by krwq** [comment] 2021-12-16 15:04
I'll bump the priority given this seems like 2-10x larger allocation

**Comment by ericstj** [comment] 2021-12-16 15:48
Cc @steveharter

**Comment by standsed** [comment] 2023-04-21 13:54
Could this be the cause [ Investigate writing large string values in 4 KB chunks within Utf8JsonWriter instead all at once #29293 ](https://github.com/dotnet/runtime/issues/29293)

Referenced in number of TODOs, e.g.,
https://github.com/dotnet/runtime/blob/f107b4b53e831ac631ab91cc9cee0200d96a7eee/src/libraries/System.Text.Json/src/System/Text/Json/Writer/Utf8JsonWriter.WriteValues.String.cs#L115

**Comment by eiriktsarpalis** [comment] 2023-11-22 21:30
Duplicate of https://github.com/dotnet/runtime/issues/67337

**Closed by eiriktsarpalis** 2023-11-22 21:30 UTC
Labels: bug, area-System.Text.Json, tenet-performance
