### ISSUE TITLE
Request for Manual Object Release Method in C#

### ISSUE THREAD

**Issue by Dx-hualuo** [dotnet/runtime#93007] opened 2023-10-04 14:29 UTC
I have encountered an issue when using Godot with C# as the programming language. In GDScript, there is an API for manually releasing objects. However, I have not found a corresponding method in C#. Waiting for objects to be released by the GC can cause unknown performance issues. Please provide a method to manually release unused objects in C#.

**Comment by Dx-hualuo** [comment] 2023-10-04 14:31
我正在寻找一种在C#中提供类似于C++中delete关键字的功能的方法。这将允许手动释放未使用的对象，类似于在C++中使用delete来释放内存

**Comment by Dx-hualuo** [comment] 2023-10-04 14:32
I am looking for a method in C# that can provide similar functionality to the 'delete' keyword in C++. This would allow for manual release of unused objects, similar to how 'delete' is used in C++ to deallocate memory.

**Comment by KatPurpy** [comment] 2023-10-04 15:21
we serve ~~food~~ garbage collection here, sir

**Comment by jkotas** [comment] 2023-10-04 15:45
This is duplicate of https://github.com/dotnet/runtime/discussions/73991 .

Pools like `System.ArrayPool<T>` are there for situations where the manual memory management is needed for performance reasons.

**Closed by jkotas** 2023-10-04 15:45 UTC
Labels: untriaged, needs-area-label
