### ISSUE TITLE
Some incorrect NRT annotations in System.CodeDom

### ISSUE THREAD

**Issue by MaceWindu** [dotnet/runtime#78036] opened 2022-11-08 17:07 UTC
### Description

Looks like `System.CodeDom` 7.0.0 enabled or updated NRT annotations and now we get build errors:
- [`CodePrimitiveExpression.ctor(object)`](https://github.com/dotnet/runtime/blob/main/src/libraries/System.CodeDom/src/System/CodeDom/CodePrimitiveExpression.cs#L10) should be `CodePrimitiveExpression.ctor(object?)`, [test](https://github.com/dotnet/runtime/blob/main/src/libraries/System.CodeDom/tests/System/CodeDom/CodePrimitiveExpressionTests.cs#L20)
- [`object CodePrimitiveExpression.Value`](https://github.com/dotnet/runtime/blob/main/src/libraries/System.CodeDom/src/System/CodeDom/CodePrimitiveExpression.cs#L10) should be `object? CodePrimitiveExpression.Value`, [test](https://github.com/dotnet/runtime/blob/main/src/libraries/System.CodeDom/tests/System/CodeDom/CodePrimitiveExpressionTests.cs#L15)
- set of [`Executor. ExecWaitWithCapture`](https://github.com/dotnet/runtime/blob/main/src/libraries/System.CodeDom/src/System/CodeDom/Compiler/Executor.cs#L24-L48) methods with `ref string` parameters which should be `ref string?`, [test](https://github.com/dotnet/runtime/blob/main/src/libraries/System.CodeDom/tests/System/CodeDom/Compiler/ExecutorTests.cs#L60)

Could be more, but that's all we encountered during build of our code. I see tests already check for `null` values so it is possible to use NRT warnings from test code to detect more issues in this area.

### Reproduction Steps

see referenced existing tests that test affected APIs with `null`

### Expected behavior

No NRT errors

### Actual behavior

CS8601, CS8604 errors on build

**Comment by stephentoub** [comment] 2022-11-08 17:28
I'm surprised you're getting warnings... the ref assembly for System.CodeDom explicitly disables nullable reference types:
https://github.com/dotnet/runtime/blob/2a65e07a9cd2eb588c59a8d2b7d373de6fef4b8e/src/libraries/System.CodeDom/ref/System.CodeDom.csproj#L4
and does not contain any annotations:
https://github.com/dotnet/runtime/blob/release/7.0/src/libraries/System.CodeDom/ref/System.CodeDom.cs

@ViktorHofer, do we have a package authoring problem here?  It looks like the nuget package doesn't contain a ref assembly, only the library, which hasn't been fully annotated yet and isn't ready for it to have its annotations consumed.

**Comment by ViktorHofer** [comment] 2022-11-08 17:40
>@ViktorHofer, do we have a package authoring problem here? It looks like the nuget package doesn't contain a ref assembly, only the library, which hasn't been fully annotated yet and isn't ready for it to have its annotations consumed.

@stephentoub dotnet/runtime libraries packages don't contain reference assemblies anymore since [.NET 6 RC1](https://www.nuget.org/packages/System.CodeDom/6.0.0-rc.1.21451.13). I wasn't involved in that change directly, but @ericstj can for sure enumerate the reasons for it.

I called this specific issue out in March 2022, https://github.com/dotnet/runtime/issues/66090:

> Since .NET 6, reference assemblies aren't part of our out-of-band packages anymore. That means that our customers when consuming our packages, bind/compile against the package's implementation assembly and not its reference assembly. Therefore, the API surface area that we carefully maintain via the reference source files isn't the actual API surface area that our customers target.

**Comment by stephentoub** [comment] 2022-11-08 17:44
> dotnet/runtime libraries packages don't contain reference assemblies anymore since [.NET 6 RC1](https://www.nuget.org/packages/System.CodeDom/6.0.0-rc.1.21451.13).

Then we have a real problem here that likely extend beyond codedom. The annotations currently in the src are haphazard and not intended for consumption.

**Comment by ViktorHofer** [comment] 2022-11-08 18:04
Agreed that this should be fixed. These are the libraries that have a different nullable reference type compiler setting between the non-shipping contract and the implementation:
- System.CodeDom
- System.Diagnostics.EventLog
- System.Diagnostics.PerformanceCounter
- System.DirectoryServices.AccountManagement
- System.Management

**Comment by eerhardt** [comment] 2022-11-08 20:20
> seems to be a result of https://github.com/dotnet/runtime/pull/68102, was there a reason why we left NRT enabled for these src assemblies?

This wasn't the result of #68102. Before that change, the `ref\System.CodeDom.csproj` and the `src\System.CodeDom.csproj` projects differed in their nullable settings. Using the [parent commit](8b6830ae2c6a8f8ae2f2aaae61e1a58707808003) of that change to view the settings:

(note before that change, not having `Nullable` in the .csproj meant `disable`):

https://github.com/dotnet/runtime/blob/8b6830ae2c6a8f8ae2f2aaae61e1a58707808003/src/libraries/System.CodeDom/ref/System.CodeDom.csproj#L1-L6

https://github.com/dotnet/runtime/blob/8b6830ae2c6a8f8ae2f2aaae61e1a58707808003/src/libraries/System.CodeDom/src/System.CodeDom.csproj#L2-L6

**Comment by eerhardt** [comment] 2022-11-08 20:51
Comparing the 6.0.0 and the 7.0.0 version, I see this difference in IL:

![image](https://user-images.githubusercontent.com/8291187/200672678-433f2994-89e1-4db6-8851-cf20c3953dc1.png)

I'm trying to figure out exactly why that got added.

**Comment by stephentoub** [comment] 2022-11-08 20:59
I assume it was my https://github.com/dotnet/runtime/commit/896eb15477d111b74643bdf6c2d2e8e8f858d279 and my not realizing at the time we didn't ship the ref.

**Comment by eerhardt** [comment] 2022-11-08 21:09
> I assume it was my https://github.com/dotnet/runtime/commit/896eb15477d111b74643bdf6c2d2e8e8f858d279 and my not realizing at the time we didn't ship the ref.

Yes, I think you're right there. I saw that change in the blame - but since it was August 2021, I assumed that was already in 6.0. Looking again, that commit didn't make 6.0.

**Comment by jeffhandley** [comment] 2023-08-05 20:26
We should fix this in .NET 8 since it is a build time regression. I've moved this over to infrastructure though since this and a few other libraries behave differently from expected regarding the src vs. ref assemblies.

**Comment by ViktorHofer** [comment] 2023-08-06 15:41
> I've moved this over to infrastructure though since this and a few other libraries behave differently from expected regarding the src vs. ref assemblies.

@jeffhandley all dotnet/runtime nuget packages ship implementation assemblies only. Reference assemblies have been removed from packages between .NET 5 and .NET 6. This bug tracks improving the nullable annotations in System.CodeDom and potentially in other assemblies (see list above). I don't see an infrastructure fault here (please let me know if you disagree).

**Comment by stephentoub** [comment] 2023-08-06 17:26
It depends what we want the fix to be. A valid option is adding back a reference assembly. It's not the only option, obviously.

**Comment by jeffhandley** [comment] 2023-08-07 06:30
Yeah -- I'd like to get infrastructure guidance here on the best way to resolve this. If the resolution is to fix up the annotations, so be it, and we'll bounce this back to the CodeDom area (after confirming other areas aren't also in a bad state). But if we think (through the infrastructure perspective) that we should reintroduce a reference assembly, then we might need more infrastructure help resolving it.

**Comment by ViktorHofer** [comment] 2023-08-07 07:45
> But if we think (through the infrastructure perspective) that we should reintroduce a reference assembly, then we might need more infrastructure help resolving it.

From an infrastructure perspective, we don't want to bring back reference assemblies in our nuget packages. IIRC some tools didn't work well with them which ultimately led to their removal. @ericstj can you please provide more context on why reference assemblies were removed?

**Comment by stephentoub** [comment] 2023-08-07 13:48
> we'll bounce this back to the CodeDom area (after confirming other areas aren't also in a bad state)

There's a 0% chance that the others are all fine.

All of these src projects use `<Nullable>annotations</Nullable>`:
```xml
d:\repos\runtime\src\libraries\Microsoft.Extensions.Hosting.Systemd\src\Microsoft.Extensions.Hosting.Systemd.csproj(9):<Nullable>annotations</Nullable>
d:\repos\runtime\src\libraries\System.CodeDom\src\System.CodeDom.csproj(6):<Nullable>annotations</Nullable>
d:\repos\runtime\src\libraries\System.Diagnostics.EventLog\src\System.Diagnostics.EventLog.csproj(5):<Nullable>annotations</Nullable>
d:\repos\runtime\src\libraries\System.Diagnostics.PerformanceCounter\src\System.Diagnostics.PerformanceCounter.csproj(5):<Nullable>annotations</Nullable>
d:\repos\runtime\src\libraries\System.DirectoryServices.AccountManagement\src\System.DirectoryServices.AccountManagement.csproj(8):<Nullable>annotations</Nullable>
d:\repos\runtime\src\libraries\System.DirectoryServices.Protocols\src\System.DirectoryServices.Protocols.csproj(7):<Nullable>annotations</Nullable>
d:\repos\runtime\src\libraries\System.IO.Ports\src\System.IO.Ports.csproj(7):<Nullable>annotations</Nullable>
d:\repos\runtime\src\libraries\System.Management\src\System.Management.csproj(7):<Nullable>annotations</Nullable>
d:\repos\runtime\src\libraries\System.Runtime.Caching\src\System.Runtime.Caching.csproj(5):<Nullable>Annotations</Nullable>
d:\repos\runtime\src\libraries\System.Speech\src\System.Speech.csproj(9):<Nullable>annotations</Nullable>
```
`<Nullable>annotations</Nullable>` is dangerous... it says "my annotations are all correct; use them but don't validate them". That's ok as a stopgap if the library won't be directly referenced, but if it is, it means every reference type showing up as a return type is a potential false negative (because reference types become non-nullable and the compiler won't warn you if you're returning null) and every reference type showing up as a parameter is a potential false positive (because reference types become non-nullable so a consumer passing null will get warnings even if null is actually permitted by the API). It's trivial to find cases where that happens, e.g. `MemoryCache`'s indexer returns null if the key isn't in the cache, yet it's annotated as returning the non-nullable `object`, so there's no warning when trying to dereference it even though it'll null ref at run-time:
```C#
using System.Reflection;
using System.Runtime.Caching;

var nc = new NullabilityInfoContext();
NullabilityInfo ni = nc.Create(typeof(MemoryCache).GetProperty("Item")!);
Console.WriteLine(ni.ReadState); // prints "NotNull"

var cache = new MemoryCache("something");
object result = cache["item"];
Console.WriteLine(result.GetHashCode()); // NRE

```

I see four reasonable fixes here for .NET 8:
1. Correctly annotate all of these libraries. This is the right fix, but it would also take a small army to get it done correctly for .NET 8. It'd be the same process we previously employed for annotating libraries, doing so for each of these 10.
2. Ship the reference assemblies for these. Most of the refs here also have an incorrect context set, either implicitly defaulting to `enable` or explicitly having `annotations`, and all of those would need to switch to `disable` as part of this.
3. Mark all of the src projects explicitly as `<Nullable>disable</Nullable>` and make the code compile with liberal use of `#pragma warning disable/restore`.
4. Some combination of (1)/(3), doing (1) where it's easy to get it done and (3) for the rest.

**Comment by ViktorHofer** [comment] 2023-08-07 15:27
> Ship the reference assemblies for these. Most of the refs here also have an incorrect context set, either implicitly defaulting to enable or explicitly having annotations, and all of those would need to switch to disable as part of this.

To expand a little bit on this, we would also need to change the [resolveContract build infrastructure](https://github.com/dotnet/runtime/blob/38166fba8921a572e82c6ac3342ef0e2afa7b73e/eng/resolveContract.targets#L12-L22) in dotnet/runtime to make sure that projects which reference one of these ten projects, bind against the reference assembly, instead of the implementation assembly. But if we would do that, we would probably re-introduce https://github.com/dotnet/runtime/issues/63467, in some form.

**Comment by ericstj** [comment] 2023-08-07 15:53
Things like the Workflow compiler, SGEN, and other design time tools in VS load references with reflection - which loads assemblies for execution and fails with reference assemblies.   Numerous reports about broken tools here are what led us to eventually just remove reference assemblies from packages.   We also previously discussed with Roslyn/Nuget if it ever makes sense to make a public way to include reference assemblies in packages and the conclusion was no.  IMO it doesn't make sense to add back shipping reference assemblies here - they've been gone for multiple releases and the regressions we'd bring to design time experiences are worse than whatever nullable problems it might fix.

I agree with @stephentoub's suggestion to go with option 4.  That seems like the best way to get us back to what we shipped in 7.0 while still adding some incremental value.

**Comment by elachlan** [comment] 2023-08-07 22:35
Winforms has been blocked a few times by this but I think it won't be until .Net9 until we are fully annotated at best. Mostly because it has been a community initiative.

I imagine the people working on winforms annotations will be willing to put in a bit of effort to help annotate the libraries we make use of.

**Comment by jeffhandley** [comment] 2023-08-08 22:58
I'm unsure we have sufficient justification to try to go correctly annotate these 10 libraries right now. My recommendation would be for us to proceed with @stephentoub's Option 3 ("Mark all of the src projects explicitly as <Nullable>disable</Nullable> and make the code compile with liberal use of #pragma warning disable/restore"). That looks like the quickest path to get us back to where we were when we shipped net7.0.

Then we can consider whether or not #41720 for annotating other remaining libraries should be in scope for .NET 9 (right now it's in Future).

**Comment by stephentoub** [comment] 2023-08-09 03:23
I think (3) is trivial... just add:
```xml
  <!-- TODO https://github.com/dotnet/runtime/issues/78036: Until this project is annotated, disable NRT -->
  <PropertyGroup>
    <Nullable>disable</Nullable>
    <NoWarn>$(NoWarn);nullable</NoWarn>
  </PropertyGroup>
```
to each project (instead of whatever `<Nullable/>` it may already have.

**Comment by elachlan** [comment] 2023-08-09 03:51
Related: #41720

**Comment by halgab** [comment] 2023-08-11 08:17
I've just started the work to fully annotate the System.CodeDom library. Would the team be interested in such a contribution?

**Comment by stephentoub** [comment] 2023-08-11 13:41
That'd be very welcome, @halgab, thanks.

**Comment by steveharter** [comment] 2023-08-11 17:24
> I've just started the work to fully annotate the System.CodeDom library

For v8, I don't think there is enough time to fully annotate and review a fully annotate `System.CodeDom` - RC1 snap is in 3 days. However, a fully annotated CodeDom would be welcome in v9.

I assume that https://github.com/dotnet/runtime/pull/90393 is not needed for v8 if when https://github.com/dotnet/runtime/pull/90401 is in.

**Closed** 2023-08-12 03:41 UTC
Labels: bug, area-System.CodeDom, blocking-release, in-pr
