### ISSUE TITLE
System.Text.Json serialisation should include all public fields in a struct by default

### ISSUE THREAD

**Issue by jessicah** [dotnet/runtime#44007] opened 2020-10-29 04:00 UTC
### Description

Serializing a struct with the System.Text.Json serializer should serialize all public fields by default, and only exclude fields by default for classes.

### Other information

I haven't tested out record types in C# 9, but would expect the behaviour there to be the same as serializing a struct.

**Comment by Symbai** [comment] 2020-10-29 07:35
And can you tell us WHY it should do that?

**Comment by GrabYourPitchforks** [comment] 2020-10-29 19:07
Possible dupe of https://github.com/dotnet/runtime/issues/876.

**Comment by layomia** [comment] 2020-10-29 20:07
Closing as a dupe of https://github.com/dotnet/runtime/issues/876. When designing field support in `JsonSerializer`, we decided to not include fields when serializing and deserializing by default to avoid a breaking change from .NET 3.1 where fields were ignored. See https://github.com/dotnet/runtime/pull/2192#issuecomment-582224804 for more info. You can opt into field support by setting `JsonSerializerOptions.IncludeFields` to `true` or by annotating each field to include with `JsonIncludeAttribute`.

---

What's the rationale for including fields by default for structs, but not classes. I think this behavior would be very confusing.

**Closed by layomia** 2020-10-29 20:07 UTC
Labels: area-System.Text.Json
