### ISSUE TITLE
Add a ReadOnlySpan<byte> version of GetManifestResourceStream

### ISSUE THREAD

**Issue by ThadHouse** [dotnet/runtime#42084] opened 2020-09-10 19:20 UTC
## Background and Motivation

ReadOnlySpan provides a great way to access unmanaged memory, which can include memory embedded in an assembly. The Roslyn compiler already does this in certain cases. A way to get an ROS from an embedded resource would be super helpful, and likely would be a relatively simple change too. Doing this would allow using ROS API's with embedded resource, rather then only Stream API's, or assuming the Stream is an UnmanagedMemoryStream, and just casting to that to manually create an ROS.

## Proposed API

```diff
namespace System.Reflection
{
    public class Assembly {
+       public ReadOnlySpan<byte> GetManifestResourceAsSpan(Type, String);
+       public ReadOnlySpan<byte> GetManifestResourceAsSpan(String);
    }
}
```

These API's would throw if the resource isn't found. A missing file usually doesn't happen except for error cases.

## Usage Examples

``` C#
ReadOnlySpan<byte>? FileToExtract = typeof(MyClass).Assembly.GetManifestResourceAsSpan("MyResource);
File.WriteAllBytes("MyFile", FileToExtract.Value);
```

## Alternative Designs

Could use a Try with out parameter pattern rather then throwing.

## Risks

There should be no risks to doing this, similar things are already performed by the compiler, and an UnmanagedMemoryStream as currently used should have the same lifetime requirements as a ReadOnlySpan.

**Comment by john-h-k** [comment] 2020-09-10 19:34
The only risk I can think of is if an assembly was unloaded while the span is alive. However, not sure if this is possible

**Comment by GrabYourPitchforks** [comment] 2020-09-10 20:07
@jkotas @Maoni0 Would having a managed pointer to the address space of a loaded module be GC tracked and prevent the Assembly from being unloaded?

**Comment by jkotas** [comment] 2020-09-10 20:39
> Would having a managed pointer to the address space of a loaded module be GC tracked and prevent the Assembly from being unloaded?

It would not in all cases today. It is why the existing API returns private `ManifestResourceStream` that is keeping the Assembly alive.

Related / duplicate of https://github.com/dotnet/runtime/issues/26101 .

I do not think that this API is very useful. Retrieving Span from metadata would be relatively slow operation and the Span cannot be cached. I think it is more useful to work on better ways to get span out of UnmanagedMemoryStream. It can be done today using unsafe code.

**Comment by GrabYourPitchforks** [comment] 2020-09-10 22:16
Closing as dupe.

**Closed by GrabYourPitchforks** 2020-09-10 22:16 UTC
Labels: api-suggestion, area-System.Memory, untriaged
