### ISSUE TITLE
FileSystemWatcher Does Not Detect 'Rename' On Linux

### ISSUE THREAD

**Issue by RobPaulson** [dotnet/runtime#36282] opened 2020-05-12 15:39 UTC
I'm using the exact same code; but when I run it on Linux it does not fire a 'Rename' event. On Windows it does. I believe this is an issue and that the behavior should be the same. 

**Output On Windows:**
> FileWatcher Reports: sample.txt renamed to sample2.txt

**Output On Linux:**
> FileWatcher Reports: sample2.txt Created
FileWatcher Reports: sample.txt Deleted

**Sample code**
```cs
using System;
using System.IO;
using System.Threading;

namespace ConsoleApp6
{
    internal static class Program
    {
        private static void Main()
        {
            Console.WriteLine("Running from " + Environment.CurrentDirectory);

            var watcher = new FileSystemWatcher
            {
                Path = Environment.CurrentDirectory,
                NotifyFilter = NotifyFilters.LastAccess | NotifyFilters.LastWrite | NotifyFilters.FileName |
                               NotifyFilters.DirectoryName,
                Filter = "*.txt"
            };
            
            watcher.Changed += OnChanged;
            watcher.Created += OnChanged;
            watcher.Deleted += OnChanged;
            watcher.Renamed += OnRenamed;
            
            watcher.EnableRaisingEvents = true;

            var file = Path.Combine(Environment.CurrentDirectory, "sample.txt");
            var newFile = Path.Combine(Environment.CurrentDirectory, "sample2.txt");

            Console.WriteLine($"Renaming '{file}' to '{newFile}'");
            
            File.Move(file, newFile);
            Thread.Sleep(1000);
            
            Console.Read();
        }
        
        private static void OnChanged(object source, FileSystemEventArgs e)
        {
            // Specify what is done when a file is changed, created, or deleted.
            Console.WriteLine("FileWatcher Reports: " +  e.FullPath + " " + e.ChangeType);
        }

        private static void OnRenamed(object source, RenamedEventArgs e)
        {
            // Specify what is done when a file is renamed.
            Console.WriteLine("FileWatcher Reports: {0} renamed to {1}", e.OldFullPath, e.FullPath);
        }
    }
}
```
(Running on 3.1.201)

**Comment by danmosemsft** [comment] 2020-05-12 21:31
related https://github.com/dotnet/runtime/issues/32376

**Comment by carlossanlop** [comment] 2020-05-15 23:43
The issue is indeed a duplicate of #32376, so closing this in favor of the other issue.

**Closed by carlossanlop** 2020-05-15 23:43 UTC
Labels: area-System.IO, untriaged
