### ISSUE TITLE
LNK2038 mismatch detected in NativeAOT

### ISSUE THREAD

**Issue by AhmedZero** [dotnet/runtime#85517] opened 2023-04-28 12:14 UTC
### Description

I build the C# ObjectArx library using NativeAOT for Cad programs like C++, but the library needs two export APIs "ACRXEntryPoint" and "acrxGetApiVersion".

### Reproduction Steps

in c++ uses 

```c++
#if !defined(_WIN64) && !defined (_AC64)
#pragma comment(linker, "/export:_acrxGetApiVersion,PRIVATE")
#else
#pragma comment(linker, "/export:acrxGetApiVersion,PRIVATE")
#endif

```
I want to make it like C++ in C#
```C#
  [DllImport("rxapi", EntryPoint = "acrxGetApiVersionImpl", CallingConvention = CallingConvention.Cdecl)]
        private static extern ulong acrxGetApiVersionImpl();
        [UnmanagedCallersOnly(EntryPoint = "acrxGetApiVersion")]
        public static ulong acrxGetApiVersion()
        {
            return acrxGetApiVersionImpl();
        }
```

### Expected behavior

it should be build successfully.

### Actual behavior

```
rxapi.lib(libinit.obj) : warning LNK4099: PDB '' was not found with 'rxapi.lib(libinit.obj)' or at ''; linking object as if no debug info [N:\My_Projects\asdkmgPoly\asdkmgPoly\asdkmgPoly.csproj]
msvcprt.lib(nothrow.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in Runtime.WorkstationGC.lib(thread.cpp.obj) [N:\My_Projects\asdkmg
Poly\asdkmgPoly\asdkmgPoly.csproj]
```

### Configuration

i use .NET 7.
Windows 11 X64.

**Comment by jkotas** [comment] 2023-04-28 15:07
> error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease'

The pre-built .NET runtime libraries that are included in native AOT package are built as "static link" (https://learn.microsoft.com/en-us/cpp/c-runtime-library/crt-library-features?view=msvc-170#c-standard-library-stl-lib-files).

The error is caused by ObjectArx library built as "dynamic link" that leads to the mismatch.

Are you able to rebuild the ObjectArx library as "static link"? If you are using Visual Studio, set Properties / C/C++ / CodeGeneration / RuntimeLibrary to "Multi-threaded (/MT)" in your project file properties.

**Comment by AhmedZero** [comment] 2023-04-28 15:15
there is no source code for ObjectArx.

**Comment by jkotas** [comment] 2023-04-28 16:10
We do not have a great solution for this today. The potential workarounds that I can think of are:
- Link ObjectArx into a separate .dll library that will get dynamically loaded using standard DllImport by your native AOT compiled .dll.
- or, build this repo to create your own version of AOT package with matching C++ compiler options (the relevant C++ options are set here https://github.com/dotnet/runtime/blob/5eeb91f5501e52aca089b24f37478b7d8e537a58/eng/native/configurecompiler.cmake#L770).

https://github.com/dotnet/runtime/issues/83611 tracks adding an option for compiling the unmanaged runtime with custom C++ compiler options that would help here.

**Comment by AhmedZero** [comment] 2023-04-28 16:24
> * Link ObjectArx into a separate .dll library that will get dynamically loaded using standard DllImport by your native AOT compiled .dll.
there is no DLL for `rxapi`.

> * or, build this repo to create your own version of AOT package with matching C++ compiler options (the relevant C++ options are set here

That solution is only available.

I hope we get a great solution in the future.

**Comment by jkotas** [comment] 2023-04-28 16:51
> there is no DLL for rxapi.

You can build it yourself.

> I hope we get a great solution in the future.

+1. Resolving as duplicate of https://github.com/dotnet/runtime/issues/83611

**Closed by jkotas** 2023-04-28 16:51 UTC
Labels: untriaged, area-NativeAOT-coreclr

**Comment by AhmedZero** [comment] 2023-04-28 16:56
I hope can build rxapi but there is no source code for rxapi. it's just headers and static library.

**Comment by jkotas** [comment] 2023-04-28 17:09
You can build it from the static library:
- Create a empty .dll project
- Add .def file to the project that list the entrypoints to export from .dll (e.g. `acrxGetApiVersionImpl`)
- Add the rxapi static library to the linker inputs of this project.

**Comment by AhmedZero** [comment] 2023-04-28 17:18
I understand, thanks.
