### ISSUE TITLE
Different behavior after refactoring to `ArgumentNullException.ThrowIfNull()`

### ISSUE THREAD

**Issue by samtrion** [dotnet/runtime#80516] opened 2023-01-11 20:25 UTC
### Description

We have recently decided that we want to change our codebase regarding the newly provided API functions `ArgumentNullException.ThrowIfNull()` and `ArgumentException.ThrowIfNullOrEmpty()`. During the tests, we noticed differences in the content of the stack trace.

### Reproduction Steps

Replacement of all null checks with `ArgumentNullException.ThrowIfNull()`

### Expected behavior

```
   at Test1.Program.Main(String[] args) in C:\sources\GitHub\Test1\Program.cs:line 9
```

### Actual behavior

```
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at Test1.Program.Main(String[] args) in C:\sources\GitHub\Test1\Program.cs:line 9
```

### Known Workarounds

Marking the following methods with the [StackTraceHiddenAttribute ](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Diagnostics/StackTraceHiddenAttribute.cs) maybe?

- https://github.com/dotnet/runtime/blob/153284a0605d5c07bdf8168573aa64afd3356beb/src/libraries/System.Private.CoreLib/src/System/ArgumentNullException.cs#L59
- https://github.com/dotnet/runtime/blob/153284a0605d5c07bdf8168573aa64afd3356beb/src/libraries/System.Private.CoreLib/src/System/ArgumentNullException.cs#L71
- https://github.com/dotnet/runtime/blob/153284a0605d5c07bdf8168573aa64afd3356beb/src/libraries/System.Private.CoreLib/src/System/ArgumentNullException.cs#L82
- https://github.com/dotnet/runtime/blob/153284a0605d5c07bdf8168573aa64afd3356beb/src/libraries/System.Private.CoreLib/src/System/ArgumentNullException.cs#L91
- https://github.com/dotnet/runtime/blob/153284a0605d5c07bdf8168573aa64afd3356beb/src/libraries/System.Private.CoreLib/src/System/ArgumentException.cs#L108
- https://github.com/dotnet/runtime/blob/153284a0605d5c07bdf8168573aa64afd3356beb/src/libraries/System.Private.CoreLib/src/System/ArgumentException.cs#L117

**Comment by stephentoub** [comment] 2023-01-11 21:20
The "difference of behavior" you're concerned about is additional frames in the stack trace of the exception?  Can you elaborate on why this is a problem for you?

**Comment by samtrion** [comment] 2023-01-11 22:02
It only came to our attention via a "coincidence", since we normally do not evaluate the StackTrace within a test.

However, we were forced to use the following implementation within a part of the application (due to multiple TargetFrameworks), which at the same time encountered one of these rare cases in the tests.

```csharp
#if NET6_0_OR_GREATER
    ArgumentNullException.ThrowIfNull(value, parameterName);
#else
    if (value is null)
    {
        throw new ArgumentNullException(parameterName);
    }
#endif
```

I am aware that this is only a minor impact. Which will certainly not have a serious impact on productive code, but it does represent a minor inconsistency. Since other `ThrowHelper` are already provided with this attribute.

For example, 
https://github.com/dotnet/runtime/blob/153284a0605d5c07bdf8168573aa64afd3356beb/src/libraries/System.Runtime.Numerics/src/System/ThrowHelper.cs#L9-L10
https://github.com/dotnet/runtime/blob/153284a0605d5c07bdf8168573aa64afd3356beb/src/libraries/System.Private.CoreLib/src/System/ObjectDisposedException.cs#L53-L54
https://github.com/dotnet/runtime/blob/153284a0605d5c07bdf8168573aa64afd3356beb/src/libraries/System.Private.CoreLib/src/System/ObjectDisposedException.cs#L66-L67

More examples - [//grep.app [StackTraceHidden]](https://grep.app/search?q=%5BStackTraceHidden%5D&filter[repo.pattern][0]=dotnet/)

When I look at '[//grep.app void\s+Throw\w+](https://grep.app/search?q=void%5Cs%2BThrow%5Cw%2B&regexp=true&filter[lang][0]=C%23&filter[repo][0]=dotnet/runtime)', I get a lot of `ThrowHelper` methods without attribute. I'm not sure myself if there should be a guideline for this to ensure consistent implementation.

**Comment by dakersnar** [comment] 2023-02-17 19:54
Closing due to above explanations. This change is by design, but if there is enough feedback, we might consider adding `[StackTraceHidden]` in the future.

**Closed by dakersnar** 2023-02-17 19:54 UTC
Labels: area-System.Runtime, untriaged
