### ISSUE TITLE
Public properties and events of Process, BackgroudWorker and FileSystemWatcher classes don't have DescriptionAttribute

### ISSUE THREAD

**Issue by Tanya-Solyanik** [dotnet/runtime#48183] opened 2021-02-11 20:18 UTC
### Description
This issue is ported from https://github.com/dotnet/winforms-designer/issues/2876
WInforms Designer does not show description of events and properties for Process, FileSystemWatcher and BackgroundWorker objects in the property browser. This is  a regression from the .NET Framework designer.

Repro. steps:
1. Create a .NET Core winforms project in the VS
2. Add a process control to the form designer.
3. Go to Properties window and click Events button, observe the description for events of process control in properties window.

Result:
The description is blank for events of Process control in properties window.
![image](https://user-images.githubusercontent.com/15823268/107692700-06b43400-6c62-11eb-8623-dc3dee914fe7.png)

Expected(can be observed in the Classic WinForms designer):
![image](https://user-images.githubusercontent.com/15823268/107692738-159ae680-6c62-11eb-8f87-8bf042c65f04.png)

### Configuration
.NET version 3.0+, any Windows
VisualStudio 16.9.4 or newer

### Other information
.NET Framework used to have [DescriptionAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.descriptionattribute?view=net-5.0) decorating public events and properties in these 3 classes - https://referencesource.microsoft.com/#System/services/monitoring/system/diagnosticts/Process.cs,1118
These attributes were removed due to layering issues from the .NET classes- https://github.com/dotnet/runtime/blob/acdb8696b02f18f2dc34286fb4ba3bd26ad14db4/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs#L76-L77

**Comment by danmoseley** [comment] 2021-02-11 23:38
Duplicate of https://github.com/dotnet/runtime/issues/39375 except perhaps any missing Process ones need mentioning there.

Perhaps you'd be interested in offering a PR.

**Closed by danmoseley** 2021-02-11 23:38 UTC
Labels: area-System.Diagnostics.Process
