### ISSUE TITLE
Test failure: JIT/Methodical/xxobj/sizeof/sizeof32_Target_64Bit_and_arm_d/sizeof32_Target_64Bit_and_arm_d.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#106307] opened 2024-08-13 01:47 UTC
**Failed in:** [runtime-coreclr outerloop 20240812.2](https://dev.azure.com/dnceng-public/public/_build/results?buildId=773108&view=ms.vss-test-web.build-test-results-tab&runId=19767288&resultId=116224&paneView=debug)

**Failed tests:**
```
R2R-CG2 linux arm64 Checked no_tiered_compilation @ (Alpine.317.Arm64.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.17-helix-arm64v8
    - JIT/Methodical/xxobj/sizeof/sizeof32_Target_64Bit_and_arm_d/sizeof32_Target_64Bit_and_arm_d.cmd
```

**Error message:**
```
 /root/helix/work/workitem/e/JIT/Methodical/Methodical_d2/../xxobj/sizeof/sizeof32_Target_64Bit_and_arm_d/sizeof32_Target_64Bit_and_arm_d.sh: line 315: -r:/root/helix/work/workitem/e/JIT/Methodical/xxobj/sizeof/sizeof32_Target_64Bit_and_arm_d/IL-CG2/*.dll: No such file or directory
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'array')
   at System.Array.Clear(Array array, Int32 index, Int32 length)
   at Internal.JitInterface.CorInfoImpl.CompileMethodCleanup() in /_/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:line 699
   at Internal.JitInterface.CorInfoImpl.CompileMethod(MethodWithGCInfo methodCodeNodeNeedingCode, Logger logger) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs:line 826
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass50_0.<ComputeDependencyNodeDependencies>g__CompileOneMethod|5(DependencyNodeCore`1 dependency, Int32 compileThreadId) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 898
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass50_0.<ComputeDependencyNodeDependencies>g__CompileOnThread|4(Int32 compilationThreadId) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 833
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass50_0.<ComputeDependencyNodeDependencies>g__CompilationThread|3(Object objThreadId) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 811
/root/helix/work/workitem/e/JIT/Methodical/Methodical_d2/../xxobj/sizeof/sizeof32_Target_64Bit_and_arm_d/sizeof32_Target_64Bit_and_arm_d.sh: line 254:  4287 Aborted                 (core dumped) $__Command

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/xxobj/sizeof/sizeof32_Target_64Bit_and_arm_d/output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/root/helix/work/workitem/e/JIT/Methodical/xxobj/sizeof/sizeof32_Target_64Bit_and_arm_d/IL-CG2/TestLibrary.dll
19:59:23
Response file: /root/helix/work/workitem/e/JIT/Methodical/xxobj/sizeof/sizeof32_Target_64Bit_and_arm_d/TestLibrary.dll.rsp
/root/helix/work/workitem/e/JIT/Methodical/xxobj/sizeof/sizeof32_Target_64Bit_and_arm_d/IL-CG2/TestLibrary.dll
-o:/root/helix/work/workitem/e/JIT/Methodical/xxobj/sizeof/sizeof32_Target_64Bit_and_arm_d/TestLibrary.dll
-r:/root/helix/work/correlation/System.*.dll
-r:/root/helix/work/correlation/Microsoft.*.dll
-r:/root/helix/work/correlation/xunit.*.dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--method-layout:random
--targetarch:arm64
--targetos:linux
Running CrossGen2:  dotnet /root/helix/work/correlation/crossgen2/crossgen2.dll @/root/helix/work/workitem/e/JIT/Methodical/xxobj/sizeof/sizeof32_Target_64Bit_and_arm_d/TestLibrary.dll.rsp  
[createdump] Gathering state for process 4287 dotnet
[createdump] Crashing thread 10cb signal 6 (0006)
[createdump] Writing crash report to file /home/helixbot/dotnetbuild/dumps/coredump.4287.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.4287.dmp
[createdump] Written 58433536 bytes (14266 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 198ms
Running R2RDump:  dotnet /root/helix/work/correlation/R2RDump/R2RDump.dll --header --sc --in /root/helix/work/workitem/e/JIT/Methodical/xxobj/sizeof/sizeof32_Target_64Bit_and_arm_d/TestLibrary.dll --out /root/helix/work/workitem/e/JIT/Methodical/xxobj/sizeof/sizeof32_Target_64Bit_and_arm_d/TestLibrary.dll.r2rdump --val
Error: System.BadImageFormatException: The file is not a ReadyToRun image
   at ILCompiler.Reflection.ReadyToRun.ReadyToRunReader.Initialize(IAssemblyMetadata metadata) in /_/src/coreclr/tools/aot/ILCompiler.Reflection.ReadyToRun/ReadyToRunReader.cs:line 467
   at R2RDump.Program.Run() in /_/src/coreclr/tool
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 128
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor207|0_208(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by jakobbotsch** [comment] 2024-08-13 08:43
Duplicate of #105441

**Closed by jakobbotsch** 2024-08-13 08:43 UTC
Labels: arch-arm64, os-linux, area-crossgen2-coreclr, untriaged, blocking-outerloop
