### ISSUE TITLE
system.text.json ignores [JsonConverter(..)] on [FromQuery] in ASP.NET

### ISSUE THREAD

**Issue by jamalabo1** [dotnet/runtime#38939] opened 2020-07-08 16:50 UTC
```c#
    public class MyClass
    {
        [JsonConverter(typeof(CustomBreakConverter))] 
        public IEnumerable<MyRange<DateTimeOffset>> Break { get; set; }
    }
```
Custom converter: 
```c#
    public class CustomBreakConverter : JsonConverter<IEnumerable<MyRange<DateTimeOffset>>>
    {
        public override IEnumerable<MyRange<DateTimeOffset>> Read(ref Utf8JsonReader reader,
            Type typeToConvert,
            JsonSerializerOptions options)
        {
            ...
        }

        public override void Write(Utf8JsonWriter writer, IEnumerable<MyRange<DateTimeOffset>> value,
            JsonSerializerOptions options)
        {
           ...
        }
    }
```
Controller
```c#
        [HttpGet]
        [Route("route")]
        public async Task<IActionResult> Get([FromQuery] MyClass data)
        {
           ...
        }
```

when the request is `GET` it ignores the custom converter, (throws an error (cannot deserialize) and does not reach the code (debugged))
 
```c#
        [HttpPost]
        [Route("route")]
        public async Task<IActionResult> Get([FromBody] MyClass data)
        {
           ...
        }
```
when the controller is this it works

**Comment by layomia** [comment] 2020-07-10 05:37
Duplicate of https://github.com/dotnet/runtime/issues/33112. We want to understand how this affects polymorphic (de)serialization before we address this: https://github.com/dotnet/runtime/issues/30083, https://github.com/dotnet/runtime/issues/29937.

**Comment by layomia** [comment] 2020-07-10 05:38
Duplicate of #33112.

**Comment by jamalabo1** [comment] 2020-07-11 15:23
but the "interface" works with POST requests, is it part of the unexpected behavior?

**Comment by layomia** [comment] 2020-07-31 19:18
@jamalabo1, can you share a small project that highlights the issue? This would include the implementation of the custom converter.

**Comment by layomia** [comment] 2020-08-15 22:34
@jamalabo1 - I couldn't repro any errors on .NET Core 3.1 or .NET 5.0 here given the issue description and the provided code samples. Please take a look at my repro to see if it correctly captures the scenario you have - https://dotnetfiddle.net/rm05JE.

I'm going to move this issue to future since it is not actionable as currently reported. We can triage again if needed. If your issue is not solved, please provide a simple console/ASP.NET Core project that shows a repro so that we can determine if there's a problem with System.Text.Json or with [ASP.NET Core](https://github.com/dotnet/aspnetcore).

**Closed** 2021-11-17 06:01 UTC
Labels: area-System.Text.Json, needs more info, no recent activity
