### ISSUE TITLE
Add method String.TrimAll() to remove all whitespaces from a string

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#45786] opened 2020-12-08 21:46 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/1096524/add-method-stringtrimall-to-remove-all-whitespaces.html)._

---
<p>Very often you have to remove whitespaces from a string, especially when working with user inputs, e. g. telephone numbers, postal codes, credit card / bank numbers etc.<br>
For example: “ab1234 5678 9999” and you want just “ab123456789999”.<br>
There are Trim() methods, but they only consider the start and the end (TrimStart(), TrimEnd() or Trim() for both). It would be very handy if there would be a <strong>TrimAll()</strong> method which just removes all whitespaces (at the start, at the end and in between).</p><p>Example:</p>
<pre>var testString = &quot;+49(0) 1234 5678 999 10&quot;;

// Expected: &quot;+49(0)1234567899910&quot;
// Current way 
var newString = testString.Replace(&quot; &quot;, String.Empty);

// Suggestion
var newString2 = testString.TrimAll();
</pre>

---
#### Feedback Bot on 7/1/2020, 01:00 AM: 

Thank you for taking the time to provide your suggestion.&nbsp; We will do some preliminary checks to make sure we can proceed further.&nbsp; We'll provide an update once the issue has been triaged by the product team.
#### Patrick Hintermayer on 9/3/2020, 11:38 AM: 

<p>I created a GitHub issue for it here:</p><p><a target='_blank' href="https://github.com/dotnet/runtime/issues/41822">https://github.com/dotnet/runtime/issues/41822</a></p>

**Comment by jkotas** [comment] 2020-12-09 00:12
Duplicate of #41822

**Closed by jkotas** 2020-12-09 00:12 UTC
Labels: untriaged
