### ISSUE TITLE
Regression in .NET 8.0-preview.5: dependent assembly is not included in TPA list when running fxdependent pwsh build with preview.5 dotnet.exe

### ISSUE THREAD

**Issue by daxian-dbw** [dotnet/runtime#86713] opened 2023-05-24 17:20 UTC
### Description

This is root cause of the PowerShell issue [Microsoft.Management.Infrastructure can't be loaded in latest .NET 8 Preview 5 build](https://github.com/PowerShell/PowerShell/issues/19679).

My investigation shows it’s a regression in .NET 8-preview.5.

The `Microsoft.Management.Infrastructure.dll` (MMI.dll) can be loaded in preview.5 without a problem by `Assembly.LoadFrom`. However, when running a fxdependent build of pwsh with the _.NET 8.0-preview.5 SDK_ (through `....\dotnet.exe  ....\pwsh.dll`), the MMI.dll doesn’t get included in the `Trusted_Platform_Assemblies` (TPA) list, and thus it cannot be found when the loading is requested. As a comparison, when running the same fxdependent build of pwsh with the _.NET 8-preview.4 SDK_, the MMI.dll is included in the TPA list and hence the loading works as expected at pwsh startup.

The startup tracing logs for using the preview.5 (p5-trace.txt) and preview.4 (p4-trace.txt) SDKs are attached. The traces were generated by setting `COREHOST_TRACE = 1`. The build produced `pwsh.deps.json` file for the fxdependent build is also attached for your reference.

I want to call out that the `Microsoft.Management.Infrastructure` NuGet package ships `netstandard1.6` managed assemblies (MMI.dll). Maybe the regression in .NET 8 preview.5 is related to the `netstandard1.6` TFM? Just a guess.

[p5-trace.txt](https://github.com/dotnet/runtime/files/11557271/p5-trace.txt)
[p4-trace.txt](https://github.com/dotnet/runtime/files/11557272/p4-trace.txt)
[pwsh.deps.json.txt](https://github.com/dotnet/runtime/files/11557279/pwsh.deps.json.txt)

The .NET 8.0-preview.5 build I'm using is `8.0.100-preview.5.23269.4`.

### Reproduction Steps

See the repro steps in https://github.com/PowerShell/PowerShell/issues/19679.
Also, the tracing logs should provide lots of information about the issue.

### Expected behavior

The fxdependent pwsh build works as expected when using with the .NET 8.0-preview.5 build.

### Actual behavior

Crash at startup because the MMI.dll cannot be found -- it's not included in the TPA list.

### Regression?

Yes. it's a regression from .NET 8.0-preview.4.

### Known Workarounds

N/A

### Configuration

```
PS:13> ..\dotnet8-p5\dotnet.exe --version
8.0.100-preview.5.23269.4
```
Win10-x64 platform

**Comment by mthalman** [comment] 2023-05-24 17:26
@agocke - This is Preview 5 related and blocking our ability to ship PowerShell in the official Docker images for that release.

**Comment by agocke** [comment] 2023-05-24 18:00
@elinor-fung Could you take a look? Maybe related to the RID changes?

**Comment by vitek-karas** [comment] 2023-05-24 18:26
It's very likely the RID changes (the package is 3 years old on NuGet, but it used on-portable RIDs back then).

@daxian-dbw could you please try to modify the powershell `runtimeconfig.json` with the workaround mentioned in here: https://github.com/dotnet/docs/issues/35398

Specifically add a runtime property `System.Runtime.Loader.UseRidGraph: true`.

**Comment by daxian-dbw** [comment] 2023-05-24 18:47
@vitek-karas I tried it, but it results in the same crash.

![image](https://github.com/dotnet/runtime/assets/127450/01e2d3e0-26be-45b2-b450-73ef664a1040)

**Comment by elinor-fung** [comment] 2023-05-24 19:25
Can you try `"System.Host.Resolution.ReadRidGraph": true`? We recently renamed the setting to `System.Runtime.Loader.UseRidGraph`, so the build you are on might not have the new name.

**Comment by daxian-dbw** [comment] 2023-05-24 21:27
@elinor-fung Sure. I tried it again and this time it works, the crash is gone after adding `"System.Host.Resolution.ReadRidGraph": true` to `pwsh.runtimeconfig.json`.

**Comment by elinor-fung** [comment] 2023-05-25 10:21
Thanks @daxian-dbw. That is the fallback/compat switch we have for packages that currently use non-portable RIDs. The recommendation for packages is to more to portable RIDs - and if any assets are truly version/distro specific, handle custom loading logic through existing .NET APIs. We can work with powershell to transition `Microsoft.Management.Infrastructure.Win` - are you the right person (and if not, could you point me at them)?

**Comment by mthalman** [comment] 2023-05-25 13:01
It looks like @elinor-fung has [offered a long-term plan to resolve this](https://github.com/dotnet/runtime/issues/86713#issuecomment-1562655819).

But in the short term, we need to figure out what to do so we can ship the Preview 5 Docker images. 

@elinor-fung, is the use of this config property something that should be acceptable for shipping PowerShell in this configuration to customers in this Preview release?

@daxian-dbw, are we able to get a new release of PowerShell in time for the .NET 8 Preview 5 release (June 13)? If not, would it be acceptable for us to modify the `C:\Program Files\powershell\.store\powershell.windows.x64\7.4.0-preview.3\powershell.windows.x64\7.4.0-preview.3\tools\net8.0\any\pwsh.runtimeconfig.json` file as part of our installation logic in our Dockerfile so that it includes this property?

**Comment by elinor-fung** [comment] 2023-05-25 14:26
Yes, we should be able to use the config to unblock shipping the Docker images.

**Comment by daxian-dbw** [comment] 2023-05-25 16:54
@mthalman I don't think we will be able to have a new release before June 13. Feel free to make the necessary changes in your docker build to unblock the .NET 8 preview.5 release.

@elinor-fung We own the [Microsoft.Management.Infrastructure](https://www.nuget.org/packages/Microsoft.Management.Infrastructure) package but we don't own the corresponding code. It's legacy code that only builds in Windows build. Loop in @adityapatwardhan who I believe did the packaging work for the 2.0 version.

Can you please share some pointers for us to better understand what "portable" and "non-portable" RID means?
Also, if this is an intentional breaking change, is there a way to opt-out it in the build (_I'm aware that `runtimeconfig.template.json` can be used during build to pre-define runtime configuration options, but will there be a build property that can be used in .csproj file to disable this feature?_)

**Comment by daxian-dbw** [comment] 2023-05-25 17:12
Just want to call out on the impact -- applications that host PowerShell 7+ (i.e. using the 7.2+ version PowerShell NuGet packages) will run into the same crash when they update to .NET 8 due to this breaking change. PowerShell Azure Function is an example of those applications.

**Comment by elinor-fung** [comment] 2023-05-25 18:14
The [`RuntimeHostConfigurationOption`](https://learn.microsoft.com/dotnet/core/runtime-config/#msbuild-properties) is the build project equivalent of using that template. For example:
```
<RuntimeHostConfigurationOption Include="System.Runtime.Loader.UseRidGraph" Value="true" />
```

By 'portable' RIDs, we mean the non-version-specific, non-distribution-specific RIDs (sorry, 'portable' is rather overloaded). Those RIDs are the ones we are referring to in the [RID doc](https://learn.microsoft.com/dotnet/core/rid-catalog#using-rids) with:
> RIDs that aren't tied to a specific version or OS distribution are the preferred choice

In that same doc's list of examples for different systems, the 'portable' RIDs are the ones described as 'not version-specific' or 'not distribution-specific'.

'Non-portable' refers to all the other RIDs that are version-specific and/or distribution-specific.

**Comment by agocke** [comment] 2023-05-25 18:21
So in this case, would adding a `win-x64` section be good enough?

**Comment by elinor-fung** [comment] 2023-05-25 18:58
Yeah, if those same assets were `"rid": "win-x64"` (instead of `"rid": "win10-x64"`), we would use them. From the package authoring side, that would be putting them in a `runtimes/win-x64` subfolder.

**Comment by adityapatwardhan** [comment] 2023-05-25 19:24
Unfortunately, the native DLLs in each of the RIDs are specific to the Windows OS version. 

`runtimes/win10-x64/native/mi.dll`  depends on the following:

```
  Dump of file C:\Users\adityap\Downloads\microsoft.management.infrastructure.runtime.win.2.0.0\runtimes\win10-x64\native\mi.dll
  
  File Type: DLL
  
    Image has the following dependencies:
  
      msvcrt.dll
      api-ms-win-core-heap-l1-1-0.dll
      api-ms-win-core-processthreads-l1-1-0.dll
      api-ms-win-security-base-l1-1-0.dll
      api-ms-win-core-errorhandling-l1-1-0.dll
      api-ms-win-core-handle-l1-1-0.dll
      api-ms-win-core-interlocked-l1-1-0.dll
      api-ms-win-core-libraryloader-l1-2-0.dll
      api-ms-win-core-string-l1-1-0.dll
      api-ms-win-core-localization-l1-2-0.dll
      api-ms-win-core-heap-l2-1-0.dll
      api-ms-win-core-synch-l1-2-0.dll
      api-ms-win-core-profile-l1-1-0.dll
      api-ms-win-core-sysinfo-l1-1-0.dll
      api-ms-win-core-rtlsupport-l1-1-0.dll
      ntdll.dll
      miutils.dll
``` 
  
`runtimes/win7-x64/native/mi.dll` - depends on the following:

```
Dump of file C:\Users\adityap\Downloads\microsoft.management.infrastructure.runtime.win.2.0.0\runtimes\win7-x64\native\mi.dll

File Type: DLL

  Image has the following dependencies:

    msvcrt.dll
    KERNEL32.dll
    ADVAPI32.dll
    USER32.dll
    ntdll.dll
    miutils.dll
```

**Comment by agocke** [comment] 2023-05-25 20:16
`win7-x64` is the same as `win-x64` for .NET 8, so at minimum you could just rename `win7` to `win`.

**Comment by agocke** [comment] 2023-06-21 17:00
Actually, win7 and win81 are no longer supported in .NET 8 (https://github.com/dotnet/core/issues/7556) -- you can just move the win10 DLL to the win-x64 TFM folder and everything should work.

**Comment by jaredpar** [comment] 2023-06-22 23:36
Note: this bug is blocking razor's ability to adopt .NET 8 Preview 5 as we use `pwsh` in our build pipelines.

**Comment by agocke** [comment] 2023-06-22 23:58
@daxian-dbw Where you able to make the changes I suggested? Note that this is an intentional breaking change, specified in Closing as this is an intentional breaking change, defined in https://learn.microsoft.com/en-us/dotnet/core/compatibility/deployment/8.0/rid-asset-list.

**Comment by daxian-dbw** [comment] 2023-06-23 00:11
We cannot make the changes because 1) we don't own the sources and can no longer build those assemblies 2) we cannot use the existing assemblies in that package to repackage due to compliance issue.

In fact, that package itself has compliance issue and our team is currently looking into feasibility to remove dependency on it. @adityapatwardhan and @SeeminglyScience may have more details to share.

**Comment by agocke** [comment] 2023-06-23 00:15
You shouldn't need to rebuild any assemblies -- my suggestion is just to move the win10-x64 assembly to the `win-x64` folder. It will be functionally identical to the current layout for .NET 8+. For .NET 6 you can use the win7-x64 assembly.

**Comment by daxian-dbw** [comment] 2023-06-23 00:17
> 2) we cannot use the existing assemblies in that package to repackage due to compliance issue.

We cannot repackaging the existing assemblies without a build pipeline. It violates the compliance as far as I know.

**Comment by mthalman** [comment] 2023-06-23 00:24
@daxian-dbw - At a minimum, you should be able to make the [runtimeconfig change with the `UseRidGraph` setting](https://github.com/dotnet/runtime/issues/86713#issuecomment-1561740014), right?

**Comment by daxian-dbw** [comment] 2023-06-23 00:29
We can, for the PowerShell packages. @adityapatwardhan is working on the next preview release, so he can share more about the plan.

However, for any application out there that host PowerShell by using the PowerShell NuGet packages (e.g. [System.Management.Automation](https://www.nuget.org/packages/System.Management.Automation)), they will need to explicitly add this runtime config too, otherwise, they will run into the same problem.

**Comment by agocke** [comment] 2023-07-24 20:17
Closing as this is not a bug in runtime -- the behavior is expected in .NET 8.

**Closed by agocke** 2023-07-24 20:17 UTC
Labels: area-AssemblyLoader-coreclr, untriaged
