### ISSUE TITLE
GZipStream.ReadAsync blocks with a zero-length buffer

### ISSUE THREAD

**Issue by qmfrederik** [dotnet/runtime#52009] opened 2021-04-28 20:45 UTC
### Description

Calling `GZipStream.ReadAsync` with a zero-length buffer seemingly never returns. The sync equivalent, `GZipStream.Read`, correctly returns `0`.

The following snippet reproduces the problem:

```csharp
public async static Task Main(string[] args)
{
    using (var stream = new MemoryStream())
    {
        using (var output = new GZipStream(stream, CompressionMode.Compress, leaveOpen: true))
        {
            output.Write(new byte[] { 1, 2, 3, 4 }, 0, 4);
            output.Flush();
        }

        stream.Position = 0;

        using (var gzip = new GZipStream(stream, CompressionMode.Decompress, leaveOpen: true))
        {
            gzip.Read(Array.Empty<byte>());
            await gzip.ReadAsync(Array.Empty<byte>(), default);
        }
    }
}
```

### Configuration

.NET 5.0.202, on x64 Windows 10.

**Comment by manandre** [comment] 2021-05-05 17:35
Hello,
* I have reproduced your issue on .NET runtime 5.0.5.
    - The `ReadAsync` call is blocked as the internal [DeflateStream.FinishReadAsyncMemory](https://github.com/dotnet/runtime/blob/155406c308609b92f94e444e4e7ddf9ad80b269c/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/DeflateStream.cs#L443) is stucked in an infinite (CPU-burning) loop.
    - IMHO, it must be fixed!
* The issue is not reproducible on .NET runtime 6.0.0-preview.3.
    - It has been unintentionally fixed by [an heavy refactoring action](https://github.com/dotnet/runtime/commit/0acbafe06130149028c353c8aade702d6777edd5#diff-a076647d6d5119e4e3b482835f098318b585fc7fd9cb16116c45395721c61c3dR407) led by @stephentoub 
    - I do not know whether such an heavy "fix" can be backported or if we should work on a "local fix" in the `release/5.0` branch...

**Comment by stephentoub** [comment] 2021-05-23 10:46
> It has been unintentionally fixed

It wasn't unintentional ;-)

**Comment by Jozkee** [comment] 2021-08-31 04:34
Fixed in https://github.com/dotnet/runtime/pull/52520.

**Closed by Jozkee** 2021-08-31 04:34 UTC
Labels: area-System.IO.Compression
