### ISSUE TITLE
Add a console read function: Console.ReadLine(char delim)

### ISSUE THREAD

**Issue by Akarinnnnn** [dotnet/runtime#35063] opened 2020-04-04 15:28 UTC
Here is a simple implementation.
```CSharp
public static string ReadLine(char delim = '\n')
{
    var data = new StringBuilder(80);
    for (char ch = (char)Console.Read(); ch != delim; ch = (char)Console.Read())
        data.Append(ch);

    return data.ToString();
}
```
and an example:
```CSharp
string datajson = ReadLine('\0');

**Comment by adamsitnik** [comment] 2020-06-24 12:43
Hello @Akarinnnnn 

It looks like it's a duplicate of #800 Could you please take a look at #800 and specify your requirements there?

Thank you!

**Closed by adamsitnik** 2020-06-24 12:43 UTC
Labels: area-System.Console, untriaged
