### ISSUE TITLE
System.DirectoryServices.Protocols - Cannot use SecureSocketLayer on linux

### ISSUE THREAD

**Issue by null-d3v** [dotnet/runtime#41619] opened 2020-08-31 18:25 UTC
### Description
On linux, setting `LdapSessionOptions.SecureSocketLayer` to `true` will result in the following:
```
System.PlatformNotSupportedException: Operation is not supported on this platform.
    at System.DirectoryServices.Protocols.LdapSessionOptions.set_SecureSocketLayer(Boolean value)
```

Sample:
```
var connection = new LdapConnection(
    new LdapDirectoryIdentifier(
        LdapOptions.Server),
    new NetworkCredential(
        LdapOptions.Username,
        LdapOptions.Password),
    AuthType.Negotiate);

connection.SessionOptions.ProtocolVersion = 3;
connection.SessionOptions.SecureSocketLayer = true;
connection.Bind();
```

### Configuration
* .NET 5.0.0-preview.820414.8
* aspnet:5.0-alpine docker image
* x86_64
* libldap 2.4
* Windows Server 2019 DC

### Regression
The exact code is functional when executing from the docker container's Windows host.

**Comment by ericstj** [comment] 2020-09-09 20:06
It looks like this is currently intentionally not supported:
https://github.com/dotnet/runtime/blob/c0b87c70e42c98b03c3148a3a84eb6898ae3eb1c/src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapSessionOptions.Linux.cs#L10-L14

On windows this uses `LDAP_OPT_SSL` but it looks like OpenLDAP doesn't support this option.

@joperezr did you look into this when you added this?  Should folks using this option just stop using it, or is there some missing functionality in OpenLDAP?

**Comment by iinuwa** [comment] 2021-04-19 20:55
Duplicate of #43890.

**Comment by buyaa-n** [comment] 2021-04-29 00:01
Closing as duplicate of #43890.

**Closed by buyaa-n** 2021-04-29 00:01 UTC
Labels: area-System.DirectoryServices, enhancement, needs further triage, os-linux
