### ISSUE TITLE
Possible optimisation for derefencing a span pointer

### ISSUE THREAD

**Issue by hamarb123** [dotnet/runtime#80086] opened 2022-12-31 22:37 UTC
### Description

Dereferencing a pointer to a span seems to be unoptimised, see the codegen for `M2` vs `M1` https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAJI8YUCAAcAymIBuvMDFwBuGjWIBmBt1zYAZjCakGAYRoBvGg2tMtzJAykTsXADy8eAPgYBZcgAonF3cvACoGbABKKxtLahsEpgB2Xxh8aABPH2woXAALbAAbFhNYbAwYIK5/WD1U9KgsnPyilgBxGAw2GANYLkV/UKi0CLhPABkYLgBzDDzI1XibAF8Y600mcgcqkIxvH1JA5zcPPfCotYY4xJtiFKHFhNXqZ6A=== (thanks @tannergooding for this code, it was not obvious to me this would result in better codegen)

Clearly, it could be theoretically as good as `M1` since they do the same thing, but it's not.

There are valid reasons for taking a pointer to a span (and other ref structs), e.g. calling `string.Create` with some span data, since it can't be used as the `TState` generic parameter, the only real choice is to pass it by pointer or to copy the data (which is obviously much slower).

### Regression?

No afaik

### Analysis

I've been informed that the `call 0x00007ffaff64e850` (address may vary) is a write barrier (thanks @SingleAccretion).

Apparently this is a known issue, but there is no open issue for it.

The same poor codegen doesn't seem to exist for reference types and normal value types: https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKBuIGYACAVwDtdsAzGRsxgYRoBvGozG8mxckkYBlAA7ZWAHgCWrDAD5GAWXIAKAEoxsAEwDyrADYBPBUrUbt2AJSjxI6uO+8A7IwAqfXsVdS0AlwAybABudzEAX3iJXmlUgAZdUn0IYAArGDAMRldkzx9xYn8gqXSI6LivcSSmsQZUmWYw3Xp9btLWxnKKv0D9Lo162OSWlqA=== and https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKBuIGYACAVwDtdsAzGRsxgYRoBvGozG8mxckkYBlAA7ZWAHgCWrDAD5GAWXIAKBUrUbNAKkbYAlKPEjq4x7wDsjM9gDctsQF9vE3mlGCGAAKxgwDF1SfRDwyItrf3sncWJXdy8HcT9ssQZAmWZ1KJ16fWKNRJs8xhTUlzdPf1zcoA===

**Comment by SingleAccretion** [comment] 2022-12-31 22:45
The core of the issue is the use of write barriers to assign `TYP_BYREF` slots, which is not necessary because `TYP_BYREF`s always live on the stack. It should be straightforward to fix ([x86/x64 code that does this](https://github.com/dotnet/runtime/blob/92e8eab1bae0487be0405102be33d0e36d59a9e4/src/coreclr/jit/codegenxarch.cpp#L3925)).

**Comment by jkotas** [comment] 2023-01-01 05:25
> use of write barriers to assign TYP_BYREF slots, which is not necessary 

This is not just unnecessary. It is actually functionally wrong, and it may cause subtle GC-related bugs.

Write barrier assumes that the value being assigned is `TYP_REF`. It is not guaranteed to work for assignment of `TYP_BYREF` values.

**Comment by hamarb123** [comment] 2023-01-01 05:31
> This is not just unnecessary. It is actually functionally wrong, and it may cause subtle GC-related bugs.

Would this also be the case for .NET 6 `ByReference<T>`? If so, should the fix be backported to 6 & 7 once we write it for .NET 8?

**Comment by hamarb123** [comment] 2023-01-19 12:19
`static Span<int> T(Span<int> s) => s;` also seems to cause this somehow? That seems bad to me.

https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKBuIGYACAVwDtdsAzGRsxgYRoBvGozG9ySRgGUADtlYAeAJasMAPkYAVABRyFKtZtwBKRgF5jAbhoBfGkA==

**Comment by JulieLeeMSFT** [comment] 2023-04-13 17:56
@markples PTAL.

**Comment by markples** [comment] 2023-05-19 18:12
@jakobbotsch In #85987 you made a reference to "Even with #80086 fixed". Do you have this done already?

**Comment by jakobbotsch** [comment] 2023-05-19 19:18
@markples Sorry, I meant to leave a comment here but I forgot.

The change I have is https://github.com/dotnet/runtime/pull/86246/commits/2ed28c22bfe5730a82c7ec88c42595c5623f11fa. However, I'm not sure it's a sufficient fix -- I think we need to optimize the strategy used by the xarch backend as part of the fix.
To reiterate the comment in that issue: the change fixes the correctness bug, but it means we end up with `movsq` instead of write barrier call. This instruction turns out to be very slow, even slower than the write barrier call it replaces. To make things worse, this measurement was done on a checked build where write barriers are slower than expected, so I would expect the regression to be higher for release builds.
The fix should be ok for non-xarch -- there we just use normal stores/loads (with post-increments for arm64). But I think we want to/should align xarch to use normal stores/loads with explicit pointer increments/decrements as part of the fix. It will be a size regression but seemingly with a large perf benefit.

**Comment by markples** [comment] 2023-05-22 21:46
Thanks @jakobbotsch.  I had several observations I wanted to run by you before proceeding much further:

- There are three spots in codegenxarch.cpp that have the "if under limit, emit N movs, else emit rep movs" logic.  They can be combined.  (Additionally, there is more than one spot that scans for non-gc pointers that could be combined as well, but perhaps that can be done separately.)
- We do need to watch out for odd-sized structs where we might copy extra bytes past the end (even with movs).  However, if the movement amount is the same as GC pointer size and we have a GC pointer in the struct, then the GC pointer alignment requirements will satisfy this.
- There's a possible optimization where we can omit write barriers for GC refs in structs with GC byrefs.
- genCodeForCpBlkUnroll contains the logic that we want for this, so my next step would be to figure out how to generalize it past its GenTreeBlk* parameter. (or maybe just look at the cases that have one of these at first)

**Comment by jakobbotsch** [comment] 2023-05-22 22:19
> * There's a possible optimization where we can omit write barriers for GC refs in structs with GC byrefs.
> * genCodeForCpBlkUnroll contains the logic that we want for this, so my next step would be to figure out how to generalize it past its GenTreeBlk* parameter. (or maybe just look at the cases that have one of these at first)

:+1:

I think this will just entail updating the heuristic `LowerBlockStore` uses to allow unrolled copy blocks when GC pointers are involved. Currently it is only allowed if the destination is clearly stack (in which case it can turn off GC and use SSE instructions to copy GC pointers).

It should be simple enough to generalize `isDstAddrLocal` in that method to also take into account that structs with byrefs in them are on stack. (And IIRC the memory model does not allow pointers to locals on stacks of other threads that could be problematic?)

It would still be nice to improve `genCodeForCpObj` for the general struct-containing-GC-ref case. Perhaps by utilizing the logic in `genCodeForCpBlkUnroll` as a primitive for the segments between GC pointers? (Maybe that's what you meant)

**Comment by markples** [comment] 2023-05-26 22:36
Ah.. I see how the "whole struct" and "holes-between-GC-pointer" cases are separate cases.  #86820 has a draft of this that handles these Span cases (though locally I'm seeing a regression in those `MemoryMarshal` functions not being inlined, but that seems separate.

I think my plan will be to (1) wait for testing to verify this initial change, (2) look at arch-parity for the byref opt, (3) leave the "sub-struct" cases for another day since it will be require more changes to lowering/codegen.

**Comment by markples** [comment] 2023-05-26 23:14
inlining issue looks like user error on my part

**Comment by markples** [comment] 2023-05-30 08:38
inital numbers:

linux x64
Diffs are based on 1,574,841 contexts (617,368 MinOpts, 957,473 FullOpts).

MISSED contexts: 355,649 (22.58%)

<html>
<body>
<summary style="box-sizing: border-box;">Overall (<span style="box-sizing: border-box; color: green;">-2,771</span><span> </span>bytes)</summary><slot id="details-content" style="color: rgb(0, 0, 0); font-family: &quot;Segoe UI VSS (Regular)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div style="box-sizing: border-box; margin-left: 1em;">

Collection | Base size (bytes) | Diff size (bytes)
-- | -- | --
benchmarks.run.linux.x64.checked.mch | 7,918,693 | -29
benchmarks.run_pgo.linux.x64.checked.mch | 47,362,746 | -683
benchmarks.run_tiered.linux.x64.checked.mch | 44,982,052 | -673
coreclr_tests.run.linux.x64.checked.mch | 443,955,214 | -410
libraries.crossgen2.linux.x64.checked.mch | 18,784,425 | -845
libraries.pmi.linux.x64.checked.mch | 27,031,874 | -89
libraries_tests.pmi.linux.x64.checked.mch | 60,271,663 | -42

</div></slot>
</body>
</html>

<html>
<body>
<summary style="box-sizing: border-box;">MinOpts (<span style="box-sizing: border-box; color: green;">-1,439</span><span> </span>bytes)</summary><slot id="details-content" style="color: rgb(0, 0, 0); font-family: &quot;Segoe UI VSS (Regular)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div style="box-sizing: border-box; margin-left: 1em;">

Collection | Base size (bytes) | Diff size (bytes)
-- | -- | --
benchmarks.run_pgo.linux.x64.checked.mch | 25,938,966 | -635
benchmarks.run_tiered.linux.x64.checked.mch | 23,579,564 | -625
coreclr_tests.run.linux.x64.checked.mch | 357,572,464 | -179

</div></slot>
</body>
</html>

<html>
<body>
<summary style="box-sizing: border-box;">FullOpts (<span style="box-sizing: border-box; color: green;">-1,332</span><span> </span>bytes)</summary><slot id="details-content" style="color: rgb(0, 0, 0); font-family: &quot;Segoe UI VSS (Regular)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div style="box-sizing: border-box; margin-left: 1em;">

Collection | Base size (bytes) | Diff size (bytes)
-- | -- | --
benchmarks.run.linux.x64.checked.mch | 6,882,202 | -29
benchmarks.run_pgo.linux.x64.checked.mch | 21,423,780 | -48
benchmarks.run_tiered.linux.x64.checked.mch | 21,402,488 | -48
coreclr_tests.run.linux.x64.checked.mch | 86,382,750 | -231
libraries.crossgen2.linux.x64.checked.mch | 18,783,222 | -845
libraries.pmi.linux.x64.checked.mch | 25,641,880 | -89
libraries_tests.pmi.linux.x64.checked.mch | 55,249,423 | -42

</div></slot>
</body>
</html>

windows x64
Diffs are based on 1,459,279 contexts (468,516 MinOpts, 990,763 FullOpts).

MISSED contexts: 348,755 (23.90%)

<html>
<body>
<summary style="box-sizing: border-box;">Overall (<span style="box-sizing: border-box; color: green;">-11,614</span><span> </span>bytes)</summary><slot id="details-content" style="color: rgb(0, 0, 0); font-family: &quot;Segoe UI VSS (Regular)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div style="box-sizing: border-box; margin-left: 1em;">

Collection | Base size (bytes) | Diff size (bytes)
-- | -- | --
aspnet.run.windows.x64.checked.mch | 28,035,374 | -2,382
benchmarks.run.windows.x64.checked.mch | 4,258,082 | -166
benchmarks.run_pgo.windows.x64.checked.mch | 22,905,244 | -1,987
benchmarks.run_tiered.windows.x64.checked.mch | 22,805,376 | -1,909
coreclr_tests.run.windows.x64.checked.mch | 354,957,497 | -1,061
libraries.crossgen2.windows.x64.checked.mch | 20,924,908 | -2,508
libraries.pmi.windows.x64.checked.mch | 27,676,126 | -1,091
libraries_tests.pmi.windows.x64.checked.mch | 64,514,110 | -510

</div></slot>
</body>
</html>

<html>
<body>
<summary style="box-sizing: border-box;">MinOpts (<span style="box-sizing: border-box; color: green;">-6,129</span><span> </span>bytes)</summary><slot id="details-content" style="color: rgb(0, 0, 0); font-family: &quot;Segoe UI VSS (Regular)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div style="box-sizing: border-box; margin-left: 1em;">

Collection | Base size (bytes) | Diff size (bytes)
-- | -- | --
aspnet.run.windows.x64.checked.mch | 14,405,495 | -1,654
benchmarks.run_pgo.windows.x64.checked.mch | 10,830,744 | -1,917
benchmarks.run_tiered.windows.x64.checked.mch | 10,743,409 | -1,918
coreclr_tests.run.windows.x64.checked.mch | 273,552,624 | -640

</div></slot>
</body>
</html>

<html>
<body>
<summary style="box-sizing: border-box;">FullOpts (<span style="box-sizing: border-box; color: green;">-5,485</span><span> </span>bytes)</summary><slot id="details-content" style="color: rgb(0, 0, 0); font-family: &quot;Segoe UI VSS (Regular)&quot;, &quot;Segoe UI&quot;, -apple-system, BlinkMacSystemFont, Roboto, &quot;Helvetica Neue&quot;, Helvetica, Ubuntu, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div style="box-sizing: border-box; margin-left: 1em;">

Collection | Base size (bytes) | Diff size (bytes)
-- | -- | --
aspnet.run.windows.x64.checked.mch | 13,629,879 | -728
benchmarks.run.windows.x64.checked.mch | 3,884,760 | -166
benchmarks.run_pgo.windows.x64.checked.mch | 12,074,500 | -70
benchmarks.run_tiered.windows.x64.checked.mch | 12,061,967 | +9
coreclr_tests.run.windows.x64.checked.mch | 81,404,873 | -421
libraries.crossgen2.windows.x64.checked.mch | 20,923,719 | -2,508
libraries.pmi.windows.x64.checked.mch | 26,162,513 | -1,091
libraries_tests.pmi.windows.x64.checked.mch | 59,198,444 | -510

</div></slot>
</body>
</html>

**Comment by JulieLeeMSFT** [comment] 2023-07-28 16:49
@markples, Is your PR almost ready to close this issue?

**Comment by markples** [comment] 2023-08-08 21:48
There are 3 possible pieces of work here, and I will open separate work items for each.

1. Improve the codegen for copying span. That was done in #86820.
2. Fully stop calling the write barrier for byrefs. This is a correctness fix, but (A) it obviously hasn't triggered problems since it's been like that for a very long time - presumably the write barrier exits when it sees the stack before hitting any trouble, (B) the fix (as discussed above) leads to more `movs` on x64, which has questionable performance characteristics. #89064 is this fix and can be merged (if perf change is acceptable) or depends on (3).
3. Rewrite the code for copying structs with gc pointers to not use `movs` (if needed).

Note that the way that JIT codegen works is that if an entire struct has no GC pointers (or more specifically has no need for write barriers, so copies to the stack count even if they contain GC pointers), then a different codegen code path is used than if the struct has GC pointers (even if it the struct has a large contiguous region without GC pointers that looks like the first case).  Therefore, (1) works well by moving into the first code path, but (2) triggers the second.  Note also that the optimization in 1 has a size limit on the struct (eventually `movs` is -much- smaller code than an unrolled copy), so that is something else to consider.

**Comment by markples** [comment] 2023-08-08 21:54
now closing the span optimization since the other two issues are open

**Closed by markples** 2023-08-08 21:54 UTC
Labels: bug, tenet-performance, area-CodeGen-coreclr, Priority:2
