### ISSUE TITLE
How to get the socket information from HttpClient request?

### ISSUE THREAD

**Issue by pengweiqhca** [dotnet/runtime#63159] opened 2021-12-28 03:15 UTC
How to get the socket information(such as source ip address and target ip address) from **HttpResponseMessage** or related exception?

If it is not currently supported, can it be provided in the next version?

**Comment by zxzhuty** [comment] 2021-12-28 06:02
e.g:

        [HttpGet]
        public string Get()
        {

            var feature = Request.HttpContext.Features.Get<IHttpConnectionFeature>();
            //return feature.LocalIpAddress.ToString();
            return feature.RemoteIpAddress.ToString();

        }

Good luck.

**Comment by pengweiqhca** [comment] 2021-12-28 06:25
> e.g:
> 
> ```
>     [HttpGet]
>     public string Get()
>     {
> 
>         var feature = Request.HttpContext.Features.Get<IHttpConnectionFeature>();
>         //return feature.LocalIpAddress.ToString();
>         return feature.RemoteIpAddress.ToString();
> 
>     }
> ```
> 
> Good luck.

Is http client request, not asp.net/asp.net core.

**Comment by geoffkizer** [comment] 2021-12-28 06:49
Can you explain why you care about this information?

**Comment by zxzhuty** [comment] 2021-12-28 08:58
.Net 6
```
using System.Net.Sockets;

SocketsHttpHandler handler = new SocketsHttpHandler();
handler.ConnectCallback = async (context, cancellationToken) =>
{
    Socket socket = new Socket(SocketType.Stream, ProtocolType.Tcp);
    socket.NoDelay = true;

    try
    {
        await socket.ConnectAsync(context.DnsEndPoint, cancellationToken).ConfigureAwait(false);
        Console.WriteLine(context.DnsEndPoint);
        Console.WriteLine(socket.RemoteEndPoint.ToString()); //IP Address 
        return new NetworkStream(socket, true);
    }
    catch
    {
        socket.Dispose();
        throw;
    }
};
using (var httpClient = new HttpClient(handler))
{
    var result = await httpClient.GetAsync("https://www.google.com");
}
```

**Comment by pengweiqhca** [comment] 2021-12-28 09:04
> Can you explain why you care about this information?
> 
> edit: To answer the original question, there's no way to get this info from HttpResponseMessage currently.
> 
> We could consider adding this in the future, but to do so we need to understand the motivation for it.

Some hosts hava many ip, I need to know which ip failed when accessing.

**Comment by pengweiqhca** [comment] 2021-12-28 09:09
> 

Not only cannot connect, but also should get the infomation when status code 4XX, 5XX

**Comment by pengweiqhca** [comment] 2021-12-28 09:09
> .Net 6
> 
> ```
> using System.Net.Sockets;
> 
> SocketsHttpHandler handler = new SocketsHttpHandler();
> handler.ConnectCallback = async (context, cancellationToken) =>
> {
>     Socket socket = new Socket(SocketType.Stream, ProtocolType.Tcp);
>     socket.NoDelay = true;
> 
>     try
>     {
>         await socket.ConnectAsync(context.DnsEndPoint, cancellationToken).ConfigureAwait(false);
>         Console.WriteLine(context.DnsEndPoint);
>         Console.WriteLine(socket.RemoteEndPoint.ToString()); //IP Address 
>         return new NetworkStream(socket, true);
>     }
>     catch
>     {
>         socket.Dispose();
>         throw;
>     }
> };
> using (var httpClient = new HttpClient(handler))
> {
>     var result = await httpClient.GetAsync("https://www.google.com");
> }
> ```

Not only cannot connect, but also should get the infomation when status code 4XX, 5XX

**Comment by wfurt** [comment] 2021-12-28 19:15
audit logs was big one I have seen in the past @geoffkizer. Either for regulatory reasons or for troubleshooting.

**Comment by zxzhuty** [comment] 2021-12-29 02:32
I used other methods to achieve it.There may be additional performance loss and danger.Use caution.

.NET 6 `Program.cs`
```
using System.Net.Sockets;

SocketsHttpHandler handler = new SocketsHttpHandler();
handler.ConnectCallback = async (context, cancellationToken) =>
{
    Socket socket = new Socket(SocketType.Stream, ProtocolType.Tcp);
    socket.NoDelay = true;

    try
    {
        await socket.ConnectAsync(context.DnsEndPoint, cancellationToken).ConfigureAwait(false);
        context.InitialRequestMessage.Options.TryAdd("IP", socket.RemoteEndPoint);
        return new NetworkStream(socket, true);
    }
    catch
    {
        socket.Dispose();
        throw;
    }
};


ResponseHandler responseHandler = new ResponseHandler();
responseHandler.InnerHandler = handler;


using (var httpClient = new HttpClient(responseHandler))
{
    var result = await httpClient.GetAsync("https://www.google.com");
    Console.WriteLine(result.StatusCode);
    if (result.StatusCode == System.Net.HttpStatusCode.OK)// or other
    {
        Console.WriteLine(result.RequestMessage.Options.FirstOrDefault(x => x.Key == "IP").Value.ToString());
    }
}

public class ResponseHandler : DelegatingHandler
{
    public ResponseHandler()
    {
        InnerHandler = new HttpClientHandler();
    }
    protected async override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {

        var response = await base.SendAsync(request, cancellationToken);
        response.RequestMessage.Options.TryAdd("IP", request.Options.Where(x => x.Key == "IP").FirstOrDefault());
        return response;
    }
}
```

**Comment by pengweiqhca** [comment] 2021-12-29 03:09
> using System.Net.Sockets;
> 
> SocketsHttpHandler handler = new SocketsHttpHandler();
> handler.ConnectCallback = async (context, cancellationToken) =>
> {
>     Socket socket = new Socket(SocketType.Stream, ProtocolType.Tcp);
>     socket.NoDelay = true;
> 
>     try
>     {
>         await socket.ConnectAsync(context.DnsEndPoint, cancellationToken).ConfigureAwait(false);
>         context.InitialRequestMessage.Options.TryAdd("IP", socket.RemoteEndPoint);
>         return new NetworkStream(socket, true);
>     }
>     catch
>     {
>         socket.Dispose();
>         throw;
>     }
> };
> 
> 
> ResponseHandler responseHandler = new ResponseHandler();
> responseHandler.InnerHandler = handler;
> 
> 
> using (var httpClient = new HttpClient(responseHandler))
> {
>     var result = await httpClient.GetAsync("https://www.google.com");
>     Console.WriteLine(result.StatusCode);
>     if (result.StatusCode == System.Net.HttpStatusCode.OK)// or other
>     {
>         Console.WriteLine(result.RequestMessage.Options.FirstOrDefault(x => x.Key == "IP").Value.ToString());
>     }
> }
> 
> public class ResponseHandler : DelegatingHandler
> {
>     public ResponseHandler()
>     {
>         InnerHandler = new HttpClientHandler();
>     }
>     protected async override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>     {
> 
>         var response = await base.SendAsync(request, cancellationToken);
>         response.RequestMessage.Options.TryAdd("IP", request.Options.Where(x => x.Key == "IP").FirstOrDefault());
>         return response;
>     }
> }

👍👍👍But only the first request works.

**Comment by zxzhuty** [comment] 2021-12-29 03:40
> > using System.Net.Sockets;
> > SocketsHttpHandler handler = new SocketsHttpHandler();
> > handler.ConnectCallback = async (context, cancellationToken) =>
> > {
> > Socket socket = new Socket(SocketType.Stream, ProtocolType.Tcp);
> > socket.NoDelay = true;
> > ```
> > try
> > {
> >     await socket.ConnectAsync(context.DnsEndPoint, cancellationToken).ConfigureAwait(false);
> >     context.InitialRequestMessage.Options.TryAdd("IP", socket.RemoteEndPoint);
> >     return new NetworkStream(socket, true);
> > }
> > catch
> > {
> >     socket.Dispose();
> >     throw;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > };
> > ResponseHandler responseHandler = new ResponseHandler();
> > responseHandler.InnerHandler = handler;
> > using (var httpClient = new HttpClient(responseHandler))
> > {
> > var result = await httpClient.GetAsync("https://www.google.com");
> > Console.WriteLine(result.StatusCode);
> > if (result.StatusCode == System.Net.HttpStatusCode.OK)// or other
> > {
> > Console.WriteLine(result.RequestMessage.Options.FirstOrDefault(x => x.Key == "IP").Value.ToString());
> > }
> > }
> > public class ResponseHandler : DelegatingHandler
> > {
> > public ResponseHandler()
> > {
> > InnerHandler = new HttpClientHandler();
> > }
> > protected async override Task SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
> > {
> > ```
> >     var response = await base.SendAsync(request, cancellationToken);
> >     response.RequestMessage.Options.TryAdd("IP", request.Options.Where(x => x.Key == "IP").FirstOrDefault());
> >     return response;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> 
> 👍👍👍But only the first request works.

Can you elaborate on that? I tried a few links.it work well,The console prints the information I want

**Comment by wfurt** [comment] 2021-12-29 04:38
As @geoffkizer mentioned, there is no good way how to associate response with given connection. The code above always works for first request since it is passed in. Then later connection can be reused for other requests unless `Connection: close' is used (or server does it). Or new connection can be created if request is still pending and the old one may or may not be used in the future.

**Comment by pengweiqhca** [comment] 2021-12-29 05:10
> > > using System.Net.Sockets;
> > > SocketsHttpHandler handler = new SocketsHttpHandler();
> > > handler.ConnectCallback = async (context, cancellationToken) =>
> > > {
> > > Socket socket = new Socket(SocketType.Stream, ProtocolType.Tcp);
> > > socket.NoDelay = true;
> > > ```
> > > try
> > > {
> > >     await socket.ConnectAsync(context.DnsEndPoint, cancellationToken).ConfigureAwait(false);
> > >     context.InitialRequestMessage.Options.TryAdd("IP", socket.RemoteEndPoint);
> > >     return new NetworkStream(socket, true);
> > > }
> > > catch
> > > {
> > >     socket.Dispose();
> > >     throw;
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > };
> > > ResponseHandler responseHandler = new ResponseHandler();
> > > responseHandler.InnerHandler = handler;
> > > using (var httpClient = new HttpClient(responseHandler))
> > > {
> > > var result = await httpClient.GetAsync("https://www.google.com");
> > > Console.WriteLine(result.StatusCode);
> > > if (result.StatusCode == System.Net.HttpStatusCode.OK)// or other
> > > {
> > > Console.WriteLine(result.RequestMessage.Options.FirstOrDefault(x => x.Key == "IP").Value.ToString());
> > > }
> > > }
> > > public class ResponseHandler : DelegatingHandler
> > > {
> > > public ResponseHandler()
> > > {
> > > InnerHandler = new HttpClientHandler();
> > > }
> > > protected async override Task SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
> > > {
> > > ```
> > >     var response = await base.SendAsync(request, cancellationToken);
> > >     response.RequestMessage.Options.TryAdd("IP", request.Options.Where(x => x.Key == "IP").FirstOrDefault());
> > >     return response;
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > }
> > 
> > 
> > 👍👍👍But only the first request works.
> 
> Can you elaborate on that? I tried a few links.it work well,The console prints the information I want

``` C#
using var httpClient = new HttpClient(responseHandler);

var result = await httpClient.GetAsync("https://www.bing.com");

Console.WriteLine(result.StatusCode);
Console.WriteLine(result.RequestMessage.Options.First(x => x.Key == "IP").Value.ToString());
result = await httpClient.GetAsync("https://www.bing.com");

Console.WriteLine(result.StatusCode);
Console.WriteLine(result.RequestMessage.Options.First(x => x.Key == "IP").Value.ToString());
```

Console output:
```
OK
[::ffff:202.89.233.101]:443
OK
[, ]
```

**Comment by zxzhuty** [comment] 2021-12-29 06:10
> > > > using System.Net.Sockets;
> > > > SocketsHttpHandler handler = new SocketsHttpHandler();
> > > > handler.ConnectCallback = async (context, cancellationToken) =>
> > > > {
> > > > Socket socket = new Socket(SocketType.Stream, ProtocolType.Tcp);
> > > > socket.NoDelay = true;
> > > > ```
> > > > try
> > > > {
> > > >     await socket.ConnectAsync(context.DnsEndPoint, cancellationToken).ConfigureAwait(false);
> > > >     context.InitialRequestMessage.Options.TryAdd("IP", socket.RemoteEndPoint);
> > > >     return new NetworkStream(socket, true);
> > > > }
> > > > catch
> > > > {
> > > >     socket.Dispose();
> > > >     throw;
> > > > }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > };
> > > > ResponseHandler responseHandler = new ResponseHandler();
> > > > responseHandler.InnerHandler = handler;
> > > > using (var httpClient = new HttpClient(responseHandler))
> > > > {
> > > > var result = await httpClient.GetAsync("https://www.google.com");
> > > > Console.WriteLine(result.StatusCode);
> > > > if (result.StatusCode == System.Net.HttpStatusCode.OK)// or other
> > > > {
> > > > Console.WriteLine(result.RequestMessage.Options.FirstOrDefault(x => x.Key == "IP").Value.ToString());
> > > > }
> > > > }
> > > > public class ResponseHandler : DelegatingHandler
> > > > {
> > > > public ResponseHandler()
> > > > {
> > > > InnerHandler = new HttpClientHandler();
> > > > }
> > > > protected async override Task SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
> > > > {
> > > > ```
> > > >     var response = await base.SendAsync(request, cancellationToken);
> > > >     response.RequestMessage.Options.TryAdd("IP", request.Options.Where(x => x.Key == "IP").FirstOrDefault());
> > > >     return response;
> > > > }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > }
> > > 
> > > 
> > > 👍👍👍But only the first request works.
> > 
> > 
> > Can you elaborate on that? I tried a few links.it work well,The console prints the information I want
> 
> ```cs
> using var httpClient = new HttpClient(responseHandler);
> 
> var result = await httpClient.GetAsync("https://www.bing.com");
> 
> Console.WriteLine(result.StatusCode);
> Console.WriteLine(result.RequestMessage.Options.First(x => x.Key == "IP").Value.ToString());
> result = await httpClient.GetAsync("https://www.bing.com");
> 
> Console.WriteLine(result.StatusCode);
> Console.WriteLine(result.RequestMessage.Options.First(x => x.Key == "IP").Value.ToString());
> ```
> 
> Console output:
> 
> ```
> OK
> [::ffff:202.89.233.101]:443
> OK
> [, ]
> ```

@wfurt I guess he's right .

`httpClient.DefaultRequestHeaders.Add("Connection", "close");`

**Comment by karelz** [comment] 2022-01-04 17:49
Triage:
- Complication: Socket information is not always available - we might be operating on general Stream that wraps the information.
- It would be nice to expose something, but it seems very similar to Connection Abstraction which we will likely not do.
- @scalablecory does your current work (parts of LLHTTP) help here in any way?

**Comment by samsp-msft** [comment] 2022-01-04 17:54
@karelz - exposing the source and destination IP on the Response for logging purposes would probably make sense. If the info is not available, then return null. I am less concerned about doing that than providing the socket that people then may want to muck with.
One thing to consider is with Http/2 the IP may change mid connection.

**Comment by scalablecory** [comment] 2022-01-04 18:13
This will be solved with LLHTTP (unpooled HTTP) APIS.

However, I've seen this requested a few times now. It seems reasonable to also look at how we could provide this data in an API, or a broader callback that gives access to the socket at one or more points in a request.

It seems very trivial for HTTP/1, but HTTP/2's multiplexing and HTTP/3 using QUIC raise some questions.

- Would your use case make sense if there are 100 concurrent requests all using the same socket?
- If not, would you only ever use HTTP/1? Some things like gRPC are starting to require HTTP/2 for full feature set.
- What are you after from the socket? A callback would be more flexible, but maybe a specific API could be made for e.g. metrics.

**Comment by wfurt** [comment] 2022-01-05 00:52
While I feel StreamID would be nice, basic IP info would be sufficient for debugging with upstream firewalls/servers and it would allow to find relevant data easily with lot for concurrency. 
That should be probably also sufficient for audit logs if you want to associate user with particular connection. 
I know the transport may not be TCP/NetworkStream. We can either return nothing since the user was responsible for creating it. Or we _could_ return transport stream itself. While that may expose some misuse, it would be easy and generic. And callers already may have hands on the socket - as the example above.

**Comment by wfurt** [comment] 2022-01-05 01:34
BTW  #38407 seems to dup of this.

**Comment by karelz** [comment] 2022-01-06 17:30
Triage: It is reasonable to ask for this and we have seen occasionally customers to ask for it.
Biggest value would be in ability to process it programmatically or log it in app.

We should likely expose the transport Stream or add some callback? Prototyping would be useful.
Needs more thoughts. And should work also for https.
QUIC in HTTP/3 would be another problem.

Another idea: Expose ConnectionInfo for diagnostics.

**Comment by mortengc** [comment] 2023-01-04 19:03
Please prioritize this feature.

I’m working on improving the logs for my service. Basically, I would like to understand to what IP address my request was sent both in situations where the requests got a response and for cases were the request doesn’t. The destination host name is supported by a hierarchy of Azure Traffic Managers (ATM) that load balances traffic to a list (+50) of Classic Cloud Services (CCS) and I would like to be able to pinpoint issues for a specific CCS.

Since I own the down stream service I'm appending customer headers to successful responses, but this provides little help when requests are timed out or in any cases where a response is not provided.

If an ETA exists can you please provide it or maybe provide a temporary workaround here until the fix is in. 
Thanks in advance.

**Comment by MihaZupan** [comment] 2023-01-04 19:44
Here's a temporary workaround for how to do this sort of correlation reliably, limited to HTTP/1.X: https://gist.github.com/MihaZupan/8f28566fdc4b8e20491221ed84362fcf

Due to how HTTP/2 multiplexing works, the same approach doesn't work there.

**Comment by wfurt** [comment] 2023-01-04 19:59
Would this work for parallel requests and cases when the connection is already established e.g. used from the ConnectionPool @MihaZupan ?

**Comment by MihaZupan** [comment] 2023-01-04 20:01
Yes, but only for HTTP/1. The code is looking at which stream is seeing `WriteAsync` calls in the scope of a given request.

**Comment by davidfowl** [comment] 2023-01-04 20:05
No async locals please 😢

**Comment by karelz** [comment] 2023-01-04 21:01
Triage: Moving to 8.0 as multiple customers run into this with very ugly workaround.

**Comment by MihaZupan** [comment] 2023-01-09 12:17
Worth noting is that we shouldn't forget about the failure scenario where you don't even get a response message object. This likely means including information on the exception as well.

**Comment by antonfirsov** [comment] 2023-01-11 22:31
Another aspect worth discussing: If we add new information (properties?) to `HttpResponseMessage` and `HttpRequestException`, how should we deal with them in case of handlers other than `SocketsHttpHandler`? If we don't fill the new properties, that might be unexpected for code that aims to be handler-agnostic or cross-platform. (Eg. uses `BrowserHttpHandler` on Blazor.)

**Comment by davidfowl** [comment] 2023-01-14 07:33
Isnt; that why propeties is a bag? ASP.NET Core deals with this via the feature collection model. General features can be agnostic of the underlying transport, and transports can influence features that flow from connection -> request. We should do something similar here. The transport (Connect callback), needs to a bag that flows from connection to request.

**Comment by mortengc** [comment] 2023-01-23 17:11
Please consider that IP information is also important in cases where connection was not established, but only attempted. If the information was appended to e.g. the options dictionary this would provide an opportunity to back port to previous .NET versions.

**Comment by antonfirsov** [comment] 2023-04-19 21:52
We had several rounds of offline discussions on this topic, involving @MihaZupan, @karelz and @zxzhuty. Unfortunately our conclusion is that we can only provide a limited solution for this feature request.

Starting with .NET 6.0, connection pooling has been reworked so that requests and connection attempts are decoupled. Even though a request may initiate a new connection attempt, it might be served by a different connection that becomes available in the meanwhile. The exact logic is an implementation detail, and may change between releases. This means that - by design - *there is no way to associate a remote IP endpoints with an `HttpRequestMessage` or `HttpRequestException` for failed connection attempts. Request-bound IP information is only available when a successful connection is assigned to a request.*

Considering the above limitation, and the fact this is a diagnostic concern, we do not think that exposing an API would be a good idea. We should instead consider extending our telemetry with connection-level information, eg. in the way proposed in #83734:

```diff
- ConnectionEstablished(byte versionMajor, byte versionMinor)
+ ConnectionEstablished(byte versionMajor, byte versionMinor, long connectionId, string scheme, string host, int port, string? remoteEndPoint)

- ConnectionClosed(byte versionMajor, byte versionMinor)
+ ConnectionClosed(byte versionMajor, byte versionMinor, long connectionId)

- RequestHeadersStart()
+ RequestHeadersStart(long connectionId)
```

This extension would enable tracking connections together with their `remoteEndPoint`, and their association with requests thanks to the `connectionId` passed to the `RequestHeadersStart` event, making it possible to do IP diagnostics for requests with successful connections by consuming [networking telemetry](https://learn.microsoft.com/en-us/dotnet/fundamentals/networking/networking-telemetry).

Users who would want to log IP information together outgoing `HttpClient` send calls, could do it [by implementing an `EventListener`](https://gist.github.com/antonfirsov/c565ede5947c5552193f5a80c9993560). This solution depends on async locals, but note that it's much simpler (and thus less prone to mistakes) than the workaround suggested in https://github.com/dotnet/runtime/issues/63159#issuecomment-1371345312. Once again, this would only dispatch remote endpoint values for successful connections.

To log remote endpoints for *failed* connection attempts, we don't think there is a need for new telemetry extensions. Existing events from the `System.Net.NameResolution` and the `System.Net.Sockets` telemetry providers already contain enough information, when linked together with their `ActivityId`-s.

Users who don't want to use telemetry and/or need tighter control on their logging can override `ConnectCallback` and implement manual DNS resolution and IP logging there. Note that this should be connection-level logging where connection attempts should not be associated with requests, even though it's technically possible to do so by using `SocketsHttpConnectionContext.InitialRequestMessage`. That property is not reliable, and will be obsoleted in .NET 8.0, see #66989.

**Comment by antonfirsov** [comment] 2023-05-11 16:54
Triage:
- We agreed to improve our support to this scenario by implementing https://github.com/dotnet/runtime/issues/63159#issuecomment-1515432131 / #85729
- Eventually, an API-based solution would be nice to make consumption simpler (related: #78070)

**Comment by antonfirsov** [comment] 2023-07-10 20:23
@dotnet/ncl in the discussion resulting to the proposal in https://github.com/dotnet/runtime/issues/63159#issuecomment-1515432131, for some reason we assumed connections already have a `long` id-s associated which are used by our internal diagnostics, which seems to be wrong after looking at the code or example `Private.InternalDiagnostics` trace outputs.

Since we generally prefer "pay for play" and likely don't want to penalize the majority of the use-cases which have telemetry events turned off, I recommend to proceed with the first idea from #85729 emitting data on `RequestHeadersStart` directly.

```diff
-void RequestHeadersStart();
+void RequestHeadersStart(string scheme, string host, int port, string pathAndQuery, byte versionMajor, byte versionMinor, string? remoteEndPoint);
```

**Comment by antonfirsov** [comment] 2023-07-10 20:48
> or are there other costs involved

No, that's all. TBH the second option seems to be much cleaner from telemetry perspective, and I like it better, if we don't need to stick to the "pay for play" rule strictly.

**Closed** 2023-07-18 11:03 UTC
Labels: enhancement, area-System.Net.Http, in-pr
