### ISSUE TITLE
Test failure System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#85751] opened 2023-05-04 08:29 UTC
**Failed in:**[ runtime-coreclr libraries-jitstress 20230503.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260461&view=ms.vss-test-web.build-test-results-tab&runId=5100588&resultId=168248&paneView=debug)

**Failed tests:**
```
net8.0-windows-Release-x86-CoreCLR_checked-jitstress1_tiered-Windows.10.Amd64.Open
    - System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken
net8.0-windows-Release-x86-CoreCLR_checked-jitstress1-Windows.10.Amd64.Open
    - System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken
net8.0-windows-Release-x86-CoreCLR_checked-tailcallstress-Windows.10.Amd64.Open
    - System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken
net8.0-windows-Release-x86-CoreCLR_checked-no_tiered_compilation-Windows.10.Amd64.Open
    - System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken
net8.0-windows-Release-x64-CoreCLR_checked-tailcallstress-Windows.10.Amd64.Open
    - System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken
net8.0-windows-Release-x86-CoreCLR_checked-zapdisable-Windows.10.Amd64.Open
    - System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken
net8.0-windows-Release-x64-CoreCLR_checked-zapdisable-Windows.10.Amd64.Open
    - System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken
net8.0-windows-Release-x64-CoreCLR_checked-jitstress1_tiered-Windows.10.Amd64.Open
    - System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken
net8.0-windows-Release-x64-CoreCLR_checked-no_tiered_compilation-Windows.10.Amd64.Open
    - System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken
net8.0-windows-Release-x64-CoreCLR_checked-jitstress1-Windows.10.Amd64.Open
    - System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken
```

**Error message:**
```
 System.Net.Mail.SmtpException : Failure sending mail.
---- System.NullReferenceException : Object reference not set to an instance of an object.
```

**Stack trace:**
```
    at System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken() in /_/src/libraries/System.Net.Mail/tests/Functional/SmtpClientTest.cs:line 485
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Mail.CheckCommand.EndSend(IAsyncResult result, String&amp; response) in /_/src/libraries/System.Net.Mail/src/System/Net/Mail/SmtpCommands.cs:line 49
   at System.Net.Mail.HelloCommand.EndSend(IAsyncResult result) in /_/src/libraries/System.Net.Mail/src/System/Net/Mail/SmtpCommands.cs:line 432
   at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.SendHello() in /_/src/libraries/System.Net.Mail/src/System/Net/Mail/SmtpConnection.cs:line 636
   at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.HandshakeCallback(IAsyncResult result) in /_/src/libraries/System.Net.Mail/src/System/Net/Mail/SmtpConnection.cs:line 516
--- End of stack trace from previous location ---
   at System.Net.Mail.SmtpConnection.ConnectAndHandshakeAsyncResult.End(IAsyncResult result) in /_/src/libraries/System.Net.Mail/src/System/Net/Mail/SmtpConnection.cs:line 409
   at System.Net.Mail.SmtpTransport.EndGetConnection(IAsyncResult result) in /_/src/libraries/System.Net.Mail/src/System/Net/Mail/SmtpTransport.cs:line 146
   at System.Net.Mail.SmtpClient.ConnectCallback(IAsyncResult result) in /_/src/libraries/System.Net.Mail/src/System/Net/Mail/SmtpClient.cs:line 946
```

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2023-05-03T08:47:43.86Z | runtime | Release | windows.81.amd64.open.rt | x64 | System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken | Failed | {"System.PhaseName":"libraries_test_run_release_coreclr_windows_x64_Release","System.JobName":"__default","BuildNumber":"20230503.4","BuildId":"260501","operatingSystem":"Windows.81.Amd64.Open","AzurePipelinesTestRunId":"5101848","System.PhaseAttempt":"1","Reason":"Schedule","System.StageName":"Build","runtimeFlavor":"coreclr","DefinitionName":"runtime","System.StageAttempt":"1","Project":"public","DefinitionId":"129","configuration":"Release","System.JobAttempt":"1","architecture":"x64","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobId":"cb76e204-ba8f-557d-eba6-9896b4f24865"} | Schedule
2023-05-03T07:34:51.35Z | runtime-coreclr libraries-jitstress | Release | ubuntu.1804.amd64.open.rt | x64 | System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken | Failed | {"AzurePipelinesTestRunId":"5100440","DefinitionId":"138","System.JobName":"__default","BuildNumber":"20230503.1","System.JobAttempt":"1","DefinitionName":"runtime-coreclr libraries-jitstress","System.PhaseAttempt":"1","System.StageAttempt":"1","configuration":"Release","scenario":"jitstress1","operatingSystem":"Ubuntu.1804.Amd64.Open","BuildId":"260461","System.PhaseName":"libraries_test_run_checked_coreclr_linux_x64_Release","architecture":"x64","Reason":"Schedule","Project":"public","runtimeFlavor":"coreclr","System.StageName":"Build","System.JobId":"fe27627b-bd13-56b8-97c3-9bb28451d0b9","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2023-05-02T09:55:24.02Z | runtime-extra-platforms | Release | windows.10.amd64.serverrs5.open.rt | x64 | System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken | Failed | {"System.JobName":"__default","System.JobId":"cb76e204-ba8f-557d-eba6-9896b4f24865","BuildNumber":"20230502.1","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionId":"154","configuration":"Release","AzurePipelinesTestRunId":"5062614","System.StageName":"Build","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","runtimeFlavor":"coreclr","architecture":"x64","Project":"public","Reason":"Schedule","System.JobAttempt":"1","System.PhaseName":"libraries_test_run_release_coreclr_windows_x64_Release","System.PhaseAttempt":"1","BuildId":"258971","operatingSystem":"(Windows.10.Amd64.ServerRS5.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-ltsc2019-helix-amd64"} | Schedule
2023-05-02T08:49:28.548Z | runtime | Release | windows.amd64.server2022.open.rt | x64 | System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken | Failed | {"System.StageName":"Build","BuildNumber":"20230502.2","CollectionUri":"https://dev.azure.com/dnceng-public/","Project":"public","runtimeFlavor":"coreclr","System.StageAttempt":"1","System.PhaseName":"libraries_test_run_release_coreclr_windows_x64_Release","BuildId":"258946","operatingSystem":"Windows.Amd64.Server2022.Open","System.JobName":"__default","architecture":"x64","configuration":"Release","AzurePipelinesTestRunId":"5060184","System.PhaseAttempt":"1","System.JobAttempt":"1","Reason":"Schedule","DefinitionId":"129","System.JobId":"cb76e204-ba8f-557d-eba6-9896b4f24865","DefinitionName":"runtime"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule

<details>
<summary>More failures</summary>

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T22:32:23.011Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken | Failed | {"BuildId":"253841","DefinitionId":"154","System.JobName":"__default","System.PhaseAttempt":"1","configuration":"Release","DefinitionName":"runtime-extra-platforms","System.StageAttempt":"1","System.StageName":"Build","System.JobAttempt":"1","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230426.5","runtimeFlavor":"mono","Project":"public","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","AzurePipelinesTestRunId":"4935554","architecture":"arm64","operatingSystem":"OSX.13.Amd64.AppleTV.Open","Reason":"Schedule"} | Schedule
2023-04-26T09:49:52.647Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken | Failed | {"BuildId":"252922","DefinitionId":"154","operatingSystem":"OSX.13.Amd64.AppleTV.Open","architecture":"arm64","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","BuildNumber":"20230426.1","System.PhaseAttempt":"1","DefinitionName":"runtime-extra-platforms","AzurePipelinesTestRunId":"4911256","Reason":"Schedule","System.StageName":"Build","System.JobAttempt":"1","System.JobName":"__default","configuration":"Release","runtimeFlavor":"mono","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","Project":"public"} | Schedule
2023-04-26T09:49:52.647Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken | Failed | {"BuildId":"252922","DefinitionId":"154","operatingSystem":"OSX.13.Amd64.AppleTV.Open","architecture":"arm64","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","BuildNumber":"20230426.1","System.PhaseAttempt":"1","DefinitionName":"runtime-extra-platforms","AzurePipelinesTestRunId":"4911256","Reason":"Schedule","System.StageName":"Build","System.JobAttempt":"1","System.JobName":"__default","configuration":"Release","runtimeFlavor":"mono","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","Project":"public"} | Schedule
2023-04-26T09:49:52.647Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken | Failed | {"BuildId":"252922","DefinitionId":"154","operatingSystem":"OSX.13.Amd64.AppleTV.Open","architecture":"arm64","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","BuildNumber":"20230426.1","System.PhaseAttempt":"1","DefinitionName":"runtime-extra-platforms","AzurePipelinesTestRunId":"4911256","Reason":"Schedule","System.StageName":"Build","System.JobAttempt":"1","System.JobName":"__default","configuration":"Release","runtimeFlavor":"mono","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","Project":"public"} | Schedule
2023-04-26T09:49:52.647Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken | Failed | {"BuildId":"252922","DefinitionId":"154","operatingSystem":"OSX.13.Amd64.AppleTV.Open","architecture":"arm64","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","BuildNumber":"20230426.1","System.PhaseAttempt":"1","DefinitionName":"runtime-extra-platforms","AzurePipelinesTestRunId":"4911256","Reason":"Schedule","System.StageName":"Build","System.JobAttempt":"1","System.JobName":"__default","configuration":"Release","runtimeFlavor":"mono","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","Project":"public"} | Schedule
2023-04-25T22:37:03.213Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken | Failed | {"System.PhaseAttempt":"1","System.JobAttempt":"1","architecture":"arm64","AzurePipelinesTestRunId":"4897396","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","BuildId":"252256","System.StageAttempt":"1","System.JobName":"__default","Reason":"Schedule","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","Project":"public","runtimeFlavor":"mono","System.StageName":"Build","BuildNumber":"20230425.3","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.13.Amd64.AppleTV.Open","configuration":"Release","DefinitionId":"154","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2023-04-25T22:37:03.213Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken | Failed | {"System.PhaseAttempt":"1","System.JobAttempt":"1","architecture":"arm64","AzurePipelinesTestRunId":"4897396","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","BuildId":"252256","System.StageAttempt":"1","System.JobName":"__default","Reason":"Schedule","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","Project":"public","runtimeFlavor":"mono","System.StageName":"Build","BuildNumber":"20230425.3","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.13.Amd64.AppleTV.Open","configuration":"Release","DefinitionId":"154","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2023-04-25T22:37:03.213Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken | Failed | {"System.PhaseAttempt":"1","System.JobAttempt":"1","architecture":"arm64","AzurePipelinesTestRunId":"4897396","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","BuildId":"252256","System.StageAttempt":"1","System.JobName":"__default","Reason":"Schedule","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","Project":"public","runtimeFlavor":"mono","System.StageName":"Build","BuildNumber":"20230425.3","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.13.Amd64.AppleTV.Open","configuration":"Release","DefinitionId":"154","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2023-04-25T22:37:03.213Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken | Failed | {"System.PhaseAttempt":"1","System.JobAttempt":"1","architecture":"arm64","AzurePipelinesTestRunId":"4897396","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","BuildId":"252256","System.StageAttempt":"1","System.JobName":"__default","Reason":"Schedule","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","Project":"public","runtimeFlavor":"mono","System.StageName":"Build","BuildNumber":"20230425.3","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.13.Amd64.AppleTV.Open","configuration":"Release","DefinitionId":"154","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2023-04-25T22:37:03.213Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken | Failed | {"System.PhaseAttempt":"1","System.JobAttempt":"1","architecture":"arm64","AzurePipelinesTestRunId":"4897396","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","BuildId":"252256","System.StageAttempt":"1","System.JobName":"__default","Reason":"Schedule","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","Project":"public","runtimeFlavor":"mono","System.StageName":"Build","BuildNumber":"20230425.3","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.13.Amd64.AppleTV.Open","configuration":"Release","DefinitionId":"154","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2023-04-25T22:37:03.213Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken | Failed | {"System.PhaseAttempt":"1","System.JobAttempt":"1","architecture":"arm64","AzurePipelinesTestRunId":"4897396","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","BuildId":"252256","System.StageAttempt":"1","System.JobName":"__default","Reason":"Schedule","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","Project":"public","runtimeFlavor":"mono","System.StageName":"Build","BuildNumber":"20230425.3","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.13.Amd64.AppleTV.Open","configuration":"Release","DefinitionId":"154","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
2023-04-25T22:37:03.213Z | runtime-extra-platforms | Release | osx.13.amd64.appletv.open | arm64 | System.Net.Mail.Tests.SmtpClientTest.SendMailAsync_CanBeCanceled_CancellationToken | Failed | {"System.PhaseAttempt":"1","System.JobAttempt":"1","architecture":"arm64","AzurePipelinesTestRunId":"4897396","System.JobId":"acac6bf3-3edd-5022-4e45-3362a02520b1","BuildId":"252256","System.StageAttempt":"1","System.JobName":"__default","Reason":"Schedule","System.PhaseName":"build_tvos_arm64_Release_AllSubsets_Mono","Project":"public","runtimeFlavor":"mono","System.StageName":"Build","BuildNumber":"20230425.3","DefinitionName":"runtime-extra-platforms","operatingSystem":"OSX.13.Amd64.AppleTV.Open","configuration":"Release","DefinitionId":"154","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule
</details>

**Comment by jakobbotsch** [comment] 2023-05-04 14:22
Duplicate of #85637

**Closed by jakobbotsch** 2023-05-04 14:22 UTC
Labels: arch-x86, os-windows, JitStress, arch-x64, untriaged, needs-area-label
