### ISSUE TITLE
Q: Can ::LoadLibrary load a managed .NET Core assembly with 'DllExports'?

### ISSUE THREAD

**Issue by obiwanjacobi** [dotnet/runtime#37791] opened 2020-06-12 13:44 UTC
I am researching an idea where a managed .NET core assembly is given unmanaged exported functions (think win32 exported dll function) using a 3rd party library/tool that rewrites the IL of the assembly. I have this working in that a tool like `dumpbin /exports` sees the exported functions.

The next step I want to accomplish is to load this managed assembly into an unmanaged native host that uses `::LoadLibrary` to load the module and `::GetProcAddress` to call the exported function.

Q: Is there a thing -like 'ijwhost.dll'?- that will make this scenario work?

**Comment by jkotas** [comment] 2020-06-12 18:41
> Q: Is there a thing -like 'ijwhost.dll'?- that will make this scenario work?

There is not today. This is duplicate of https://github.com/dotnet/runtime/issues/12611 where the details of what it would take to make this work on Windows are discussed.

You may want to take a look at https://github.com/AaronRobinsonMSFT/DNNE that is a cross-platform solution for this problem.

**Closed by jkotas** 2020-06-12 18:41 UTC
Labels: area-Host, untriaged

**Comment by jkotas** [comment] 2020-06-12 18:44
cc @AaronRobinsonMSFT
