### ISSUE TITLE
ConfigurationBinder.Bind is not linker friendly

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#41658] opened 2020-09-01 06:43 UTC
If `Configuration.Bind` is called on a type an it is the only method of setting its properties all the properties will be removed at link time and the configuration then will not set for bind

https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs#L107

Repo, link with `<TrimMode>Link</TrimMode>`
```csharp
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

var config = new ConfigurationBuilder()
            .AddInMemoryCollection(new[]
            {
                KeyValuePair.Create("Value", "100")
            })
            .Build();
var poco = new Poco();
config.Bind(poco);

Console.WriteLine(poco.Value);

public class Poco
{
    public int Value { get; set; }
}
```
Will output `0` rather than `100`

This issue currently occurs for certificates in Kestrel https://github.com/dotnet/aspnetcore/issues/25482 meaning https certs cannot be set via config if ASP.NET Core is trimmed; also for `IdentityServer.Configuration.KeyDefinition` as they both use `.Bind(value)`

**Comment by campersau** [comment] 2020-09-01 07:16
Similar to https://github.com/dotnet/runtime/issues/40551

**Comment by davidfowl** [comment] 2020-09-01 16:01
cc @eerhardt

**Comment by eerhardt** [comment] 2020-09-01 16:17
Duplicate of #40551. Closing.

**Closed by eerhardt** 2020-09-01 16:17 UTC
Labels: area-Microsoft.Extensions, linkable-framework, untriaged

**Comment by davidfowl** [comment] 2020-09-01 16:35
Similar but not the same. The other issue there's a type parameter, this is an object parameter.

**Comment by eerhardt** [comment] 2020-09-01 16:58
The other issue covers that the whole assembly isn't linker-safe.

**Comment by davidfowl** [comment] 2020-09-01 23:12
It doesn't call out this problem in the description of the issue. Basically anything that uses config binding is busted in a very specific way (recursive properties it's not).

**Comment by eerhardt** [comment] 2020-09-01 23:29
The second paragraph of #40551 states:

> The linker could decide to trim property setters and constructors which would cause the binder to not set properties correctly.

And the title of the issue is "Microsoft.Extensions.Configuration.Binder is not linker-safe".

I don't see any reason why we would need to keep 2 issues open to track the same problem.
