### ISSUE TITLE
Test failure: JIT/jit64/mcc/interop/mcc_i61/mcc_i61.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#108638] opened 2024-10-08 02:11 UTC
**Failed in:** [runtime-coreclr r2r-extra 20241006.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=828908&view=ms.vss-test-web.build-test-results-tab&runId=21561180&resultId=117527&paneView=debug)

**Failed tests:**
```
R2R-CG2 windows x86 Checked jitstress1_tiered @ Windows.10.Amd64.Open
    - JIT/jit64/mcc/interop/mcc_i61/mcc_i61.cmd
```

**Error message:**
```
 
Return code:      1
Raw output file:      C:hw9E7208EDwB0F509AEuploadsmccinteropmcc_i61output.txt
Raw output:
BEGIN EXECUTION
mcc_i61.dll
native_i0c.dll
native_i0s.dll
native_i1c.dll
native_i1s.dll
native_i3c.dll
native_i3s.dll
native_i5c.dll
native_i5s.dll
native_i6c.dll
native_i6s.dll
native_i7c.dll
native_i7s.dll
native_i8c.dll
native_i8s.dll
       15 file(s) copied.
 4:12:14.55
Response file: C:hw9E7208EDwB0F509AEeJITjit64mccinteropmcc_i61mcc_i61.dll.rsp
C:hw9E7208EDwB0F509AEeJITjit64mccinteropmcc_i61IL-CG2mcc_i61.dll
-o:C:hw9E7208EDwB0F509AEeJITjit64mccinteropmcc_i61mcc_i61.dll
--targetarch:x86
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:hw9E7208EDpSystem.*.dll
-r:C:hw9E7208EDpMicrosoft.*.dll
-r:C:hw9E7208EDp\xunit.*.dll
-r:C:hw9E7208EDpmscorlib.dll
-r:C:hw9E7208EDp
etstandard.dll
"Running CrossGen2:  "C:hw9E7208EDpcrossgen2crossgen2.exe" @"C:hw9E7208EDwB0F509AEeJITjit64mccinteropmcc_i61mcc_i61.dll.rsp"   -r:C:hw9E7208EDwB0F509AEeJITjit64jit64_2IL-CG2*.dll  -r:C:hw9E7208EDwB0F509AEeJITjit64mccinteropmcc_i61IL-CG2*.dll"
Emitting R2R PE file: C:hw9E7208EDwB0F509AEeJITjit64mccinteropmcc_i61mcc_i61.dll
"Running R2RDump:  "dotnet" "C:hw9E7208EDp
2rdump
2rdump.dll" --header --sc --in C:hw9E7208EDwB0F509AEeJITjit64mccinteropmcc_i61mcc_i61.dll --out C:hw9E7208EDwB0F509AEeJITjit64mccinteropmcc_i61mcc_i61.dll.r2rdump --val"
 4:12:15.31
 4:12:15.33
Response file: C:hw9E7208EDwB0F509AEeJITjit64mccinteropmcc_i61
ative_i0c.dll.rsp
C:hw9E7208EDwB0F509AEeJITjit64mccinteropmcc_i61IL-CG2
ative_i0c.dll
-o:C:hw9E7208EDwB0F509AEeJITjit64mccinteropmcc_i61
ative_i0c.dll
--targetarch:x86
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:hw9E7208EDpSystem.*.dll
-r:C:hw9E7208EDpMicrosoft.*.dll
-r:C:hw9E7208EDp\xunit.*.dll
-r:C:hw9E7208EDpmscorlib.dll
-r:C:hw9E7208EDp
etstandard.dll
"Running CrossGen2:  "C:hw9E7208EDpcrossgen2crossgen2.exe" @"C:hw9E7208EDwB0F509AEeJITjit64mccinteropmcc_i61
ative_i0c.dll.rsp"   -r:C:hw9E7208EDwB0F509AEeJITjit64jit64_2IL-CG2*.dll  -r:C:hw9E7208EDwB0F509AEeJITjit64mccinteropmcc_i61IL-CG2*.dll"
No input files are loadable
 4:12:15.37
 4:12:15.37
Response file: C:hw9E7208EDwB0F509AEeJITjit64mccinteropmcc_i61
ative_i0s.dll.rsp
C:hw9E7208EDwB0F509AEeJITjit64mccinteropmcc_i61IL-CG2
ative_i0s.dll
-o:C:hw9E7208EDwB0F509AEeJITjit64mccinteropmcc_i61
ative_i0s.dll
--targetarch:x86
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:hw9E7208EDpSystem.*.dll
-r:C:hw9E7208EDpMicrosoft.*.dll
-r:C:hw9E7208EDp\xunit.*.dll
-r:C:hw9E7208EDpmscorlib.dll
-r:C:hw9E7208EDp
etstandard.dll
"Running CrossGen2:  "C:hw9E7208EDpcrossgen2crossgen2.exe" @"C:hw9E7208EDwB0F509AEeJITjit64mccinteropmcc_i61
ative_i0s.dll.rsp"   -r:C:hw9E7208EDwB0F509AEeJITjit64jit64_2IL-CG2*.dll  -r:C:hw9E7208EDwB0F509AEeJITjit64mccinteropmcc_i61IL-CG2*.dll"
No input files are loadable
 4:12:15.42
 4:12:15.44
Response file: C:hw9E7208EDwB0F509AEeJITjit64mccinteropmcc_i61
ative_i1c.dll.rsp
C:hw9E7208EDwB0F509AEeJITjit64mccinteropmcc_i61IL-CG2
ative_i1c.dll
-o:C:hw9E7208EDwB0F509AEeJITjit64mccinteropmcc_i61
ative_i1c.dll
--targetarch:x86
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:hw9E7208EDpSystem.*.dll
-r:C:hw9E7208EDpMicrosoft.*.dll
-r:C:hw9E7208EDp\xunit.*.dll
-r:C:hw9E7208EDpmscorlib.dll
-r:C:hw9E7208EDp
etstandard.dll
"Running CrossGen2:  "C:hw9E7208EDpcrossgen2crossgen2.exe" @"C:hw9E7208EDwB0F509AEeJITjit64mccinteropmcc_i61
ative_i1c.dll.rsp"   -r:C:hw9E7208EDwB0F509AEeJITjit64jit64_2IL-CG2*.dll  -r:C:hw9E7208EDwB0F509AEeJITjit64mccinteropmcc_i61IL-CG2*.dll"
No input files are loadable
 4:12:15.50
 4:12:15.50
Response file: C:hw9E7208EDwB0F509AEeJITjit64mccinteropmcc_i61
ative_i1s.dll.rsp
C:hw9E7208EDwB0F509AEeJITjit64mccinteropmcc_i61IL-CG2
ative_i1s.dll
-o:C:hw9E7208EDwB0F509AEeJITjit64mccinteropmcc_i61
ative_i1s.dll
--targetarch:x86
--targetos:windows
--verify-type-and-field-layout
--method-layout:random
-r:C:hw9E7208EDpSystem.*.dll
-r:C:hw
```

**Stack trace:**
```
   at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 128
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor34|0_35(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by JulieLeeMSFT** [comment] 2024-10-08 17:18
@jakobbotsch, PTAL.  
Duplicate of https://github.com/dotnet/runtime/issues/108640 ?

**Comment by jakobbotsch** [comment] 2024-10-10 13:39
Duplicate of #108640

**Closed by jakobbotsch** 2024-10-10 13:39 UTC
Labels: arch-x86, os-windows, JitStress, area-CodeGen-coreclr, blocking-clean-ci-optional
