### ISSUE TITLE
Some pipelines have no 'Test' view because build fail

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#33036] opened 2020-03-02 02:14 UTC
Here are those pipeline:
[runtime-coreclr jitstressregs 20200301.1](https://dev.azure.com/dnceng/public/_build/results?buildId=542095&view=results)
[runtime-coreclr jitstress-isas-arm 20200229.1](https://dev.azure.com/dnceng/public/_build/results?buildId=541875&view=results)
[runtime-coreclr gcstress0x3-gcstress0xc 20200229.1](https://dev.azure.com/dnceng/public/_build/results?buildId=541652&view=results)
[runtime-coreclr gcstress-extra 20200301.1](https://dev.azure.com/dnceng/public/_build/results?buildId=542374&view=results)
[runtime-coreclr r2r-extra 20200229.1](https://dev.azure.com/dnceng/public/_build/results?buildId=541975&view=results)

**Comment by sandreenko** [comment] 2020-03-02 02:28
They all fail with `##[error]largeexceptiontest.cs(12,5): error CS0246: (NETCORE_ENGINEERING_TELEMETRY=) The type or namespace name 'LargeObject' could not be found (are you missing a using directive or an assembly reference?)
`.

I do not see any warning about that in the previous builds and these files have not been changed last 4 months.

**Comment by v-haren** [comment] 2020-03-02 02:53
also failed in:
[ runtime-coreclr outerloop 20200301.2](https://dev.azure.com/dnceng/public/_build/results?buildId=542295&view=results)
[runtime-coreclr jitstress 20200229.1](https://dev.azure.com/dnceng/public/_build/results?buildId=542011&view=results)
[runtime-coreclr jitstress2-jitstressregs 20200301.1](https://dev.azure.com/dnceng/public/_build/results?buildId=542318&view=results)
[runtime-coreclr jitstress-isas-x86 20200229.1](https://dev.azure.com/dnceng/public/_build/results?buildId=541887&view=results)
[runtime-coreclr jitstressregs-x86 20200301.1](https://dev.azure.com/dnceng/public/_build/results?buildId=542349&view=results)
[runtime-coreclr r2r 20200229.1](https://dev.azure.com/dnceng/public/_build/results?buildId=542017&view=results)

**Comment by sandreenko** [comment] 2020-03-02 02:54
PTAL @dotnet/runtime-infrastructure

**Comment by sandreenko** [comment] 2020-03-02 03:27
duplicate of #32966

**Closed by sandreenko** 2020-03-02 03:27 UTC
Labels: area-Infrastructure-coreclr, blocking-clean-ci-optional, untriaged
