### ISSUE TITLE
Test failure Microsoft.Extensions.FileSystemGlobbing.Tests.FunctionalTests.VerifyInMemoryDirectoryInfo_IsNotEmpty

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#50542] opened 2021-04-01 06:17 UTC
Run: [runtime-coreclr libraries-jitstress 20210331.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1065105&view=ms.vss-test-web.build-test-results-tab&runId=32786784&resultId=102350&paneView=debug)

Failed test:
```
net6.0-windows-Release-arm64-CoreCLR_checked-jitstress1-Windows.10.Arm64v8.Open
 -Microsoft.Extensions.FileSystemGlobbing.Tests.FunctionalTests.VerifyInMemoryDirectoryInfo_IsNotEmpty
```

**Error message:**
```
Assert.Equal() Failure
Expected: 1
Actual:   0


Stack trace
   at Microsoft.Extensions.FileSystemGlobbing.Tests.FunctionalTests.VerifyInMemoryDirectoryInfo_IsNotEmpty() in /_/src/libraries/Microsoft.Extensions.FileSystemGlobbing/tests/FunctionalTests.cs:line 858
```

**Comment by Jozkee** [comment] 2023-11-22 19:22
Dupe of https://github.com/dotnet/runtime/issues/50648.

**Closed by Jozkee** 2023-11-22 19:22 UTC
Labels: arch-arm64, os-windows, JitStress, area-Extensions-FileSystem
