### ISSUE TITLE
Replace strings with resources in Mono corelib

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#34056] opened 2020-03-25 04:13 UTC
In src\mono\netcore\System.Private.CoreLib the pattern `Exception\s\("` has 340 hits. All these strings should instead come from src\libraries\System.Private.CoreLib\src\Resources\Strings.resx somewhere. In most cases there are already equivalent strings that can be determined by brief inspection of equivalent code in src\coreclr\src\System.Private.CoreLib or possibly src\libraries\System.Private.CoreLib. 

Sometimes the strings need adjustment eg `throw new ArgumentException ("type is not TypeBuilder but " + type.GetType (), "type");` vs `throw new ArgumentException(SR.Argument_MustBeTypeBuilder);`. 

Some strings are in native code in coreclr eg `throw new SynchronizationLockException ("Object is not synchronized");` is not thrown in Monitor.cs in coreclr. In this case it can just be `throw new SynchronizationLockException()`

A (very?) few may need new strings.

There are also a few trivial cases where the string should be replaced with `nameof` eg `throw new ArgumentException("className")` -> `throw new ArgumentException(nameof(className))`

**Comment by danmosemsft** [comment] 2020-03-25 04:40
Also some are grandfathered in, as in coreclr. Eg., `throw new ArgumentOutOfRangeException("requiredLength", SR.ArgumentOutOfRange_SmallCapacity);` in StringBuilder is "requiredLength" forever presumably.

**Comment by am11** [comment] 2020-03-25 06:16
With a slightly relaxed pattern, it also captures the cases where the first argument is `nameof()` followed by a hard-coded string:

```sh
$ git grep "Exception.*\""  :/src/mono/netcore/System.Private.CoreLib/src/*.cs | wc -l

443
```

**Comment by danmosemsft** [comment] 2020-03-25 06:19
@am11 thanks.

I did a few -- I can put up a PR when the base change is in: https://github.com/stephentoub/runtime/compare/enablemonoanalyzers...danmosemsft:dan.on.stephen

You are welcome to do more, if you like.

**Comment by jkotas** [comment] 2020-03-25 06:22
> StringBuilder is "requiredLength" forever presumably

Is there a reason for it? We have fixed many similar bugs over the years, I do not see a reason why not to fix this one.

**Comment by danmosemsft** [comment] 2020-03-25 06:45
If you do not recall this kind of change breaking things, lets do it.

**Comment by marek-safar** [comment] 2020-03-25 07:36
I am not sure this is a step in right direction. We'll probably have to do work in the opposite direction and remove all resources overhead to cut on the size on workloads where English support is enough.

**Comment by stephentoub** [comment] 2020-03-25 11:08
Every other assembly as well as the coreclr corelib build uses resources, as does 95% of the mono corelib via shared sources. Plus we want error messages to be the same across builds and not have to update them in many places when they change. I agree it'd be valid for the linker to optionally inline resource strings (or some other build step doing it), but that would be in addition to rather than instead of consistency in this last mile.

**Comment by marek-safar** [comment] 2020-03-25 12:11
>Every other assembly as well as the coreclr corelib build uses resources, as does 95% of the mono corelib via shared sources.
I am aware of that and that would be unfortunate size regression if we had to ship with that (made tracking issue for that as #34057 a bit earlier).

**Comment by danmosemsft** [comment] 2020-03-25 13:27
@marek-sa are thanks for pointing this out. Would you have any reason for concern if your https://github.com/dotnet/runtime/issues/34057 is completed? It seems like these strings would be a small issue in comparison so that work likely is inevitable.

**Comment by stephentoub** [comment] 2020-03-25 13:29
> I am aware of that and that would be unfortunate size regression if we had to ship with that (made tracking issue for that as #34057 a bit earlier).

Understood, and not disagreeing.  That's why I said such work "would be in addition to rather than instead of" this.

**Comment by marek-safar** [comment] 2020-03-25 15:14
@danmosemsft I am not against someone doing the work

**Comment by danmosemsft** [comment] 2020-03-25 18:50
@eerhardt @vitek-karas is it safe to assume that the linker work will include #34057  ?

**Comment by weltkante** [comment] 2020-03-26 19:40
> I am not sure this is a step in right direction. We'll probably have to do work in the opposite direction and remove all resources overhead to cut on the size on workloads where English support is enough.

Just for the record, UI validation usually requires localized exception texts, at least on WinForms and WPF frameworks, but probably other frameworks as well. No idea if thats relevant in Mono, just thought I'd mention it to make people aware if they aren't.

**Comment by danmoseley** [comment] 2021-11-02 20:26
> In src\mono\netcore\System.Private.CoreLib the pattern Exception\s\(" has 340 hits. 

fwiw `Exception\s*\(` in src\mono\System.Private.CoreLib is down to 205 hits as of now.

**Comment by tudoranghelina91** [comment] 2022-04-20 22:18
Hi @danmoseley. I want to start bringing my contribution to the dotnet runtime too. See that  this is marked with easy label. I'd love to take a shot at it if it's still up for grabs.

**Comment by danmoseley** [comment] 2022-04-20 23:10
Hi @tudoranghelina91 . Great! Since this issue is a little old now, let me ask @marek-safar to confirm this is still good to go. @marek-safar ?

**Comment by marek-safar** [comment] 2022-04-21 08:03
Please go ahead, we still have some places that need fixing.

**Comment by tudoranghelina91** [comment] 2022-04-21 16:53
Okay @danmoseley and @marek-safar , if it's okay with you, may this issue be assigned to me?

**Comment by tudoranghelina91** [comment] 2022-04-21 17:33
@danmoseley @marek-safar, I see that there are some exception that contain certain keywords related to time units (e.g. ticks, milliseconds, etc.) in System.DateTime. Should these be added to the resource dictionary too?

**Comment by danmoseley** [comment] 2022-04-21 17:58
@tudoranghelina91 the strings (the exception messages) should be in the resources, yes. Those messages would include words like "ticks" and localizers can decide how to translate them.

If you mean the "parameter name" parameter to ArgumentExceptions-- those are not localized and do not go in resources. They should match the API.

**Comment by tudoranghelina91** [comment] 2022-04-21 19:10
Hey @danmoseley Sorry to bother you again. I am a bit confused regarding ArgumentExceptions. Which prefix to use? Argument or ArgumentException? is Argument prefix the same as ArgumentException prefix?

**Comment by danmoseley** [comment] 2022-04-21 19:34
Hello, I'm not sure what you're referring to. Could you give me some links into the places in the code?

**Comment by tudoranghelina91** [comment] 2022-04-21 20:19
https://github.com/dotnet/runtime/blob/e09903f9b1bee58e5def96007e9fd743685ef8e2/src/libraries/System.Private.CoreLib/src/Resources/Strings.resx#L190

https://github.com/dotnet/runtime/blob/e09903f9b1bee58e5def96007e9fd743685ef8e2/src/libraries/System.Private.CoreLib/src/Resources/Strings.resx#L1531

https://github.com/dotnet/runtime/blob/e09903f9b1bee58e5def96007e9fd743685ef8e2/src/libraries/System.Private.CoreLib/src/Resources/Strings.resx#L1528

What's the difference between the prefixes of these 3 lines?

**Comment by jkotas** [comment] 2022-04-21 20:52
Yes, we are not consistent in using prefixes for resource strings. Pick the one that makes the most sense to you.

**Comment by databunks** [comment] 2022-11-08 17:00
Hi @danmoseley Ive just been working on this issue ive managed to reduce all of the hits to about 29
the remaining hits are those which involve concatenating indexing with strings, 
should i leave them or how should i include them?
Thanks!

![image](https://user-images.githubusercontent.com/58254277/200628461-6e60d7df-a285-42a6-89bd-de610cbc698d.png)

**Comment by tudoranghelina91** [comment] 2022-11-20 18:50
I know I haven't opened a PR on this one yet, but it seems that two people have been working on the same item, despite the assignee... I could merge the changes I did, but I think that might cause merge conflicts.

Shall I unassign myself from this one?

**Comment by jkotas** [comment] 2022-11-20 22:19
> it seems that two people have been working on the same item, despite the assignee...

Sorry about that.

> I could merge the changes I did, but I think that might cause merge conflicts.

For reference, would you mind sharing the branch with the changes that you have done?

You can also comment on the opened PR in case you see places that you have handled in your changes in a better way.

cc @databunks

**Comment by databunks** [comment] 2022-11-21 12:56
> > it seems that two people have been working on the same item, despite the assignee...
> 
> Sorry about that.
> 
> > I could merge the changes I did, but I think that might cause merge conflicts.
> 
> For reference, would you mind sharing the branch with the changes that you have done?
> 
> You can also comment on the opened PR in case you see places that you have handled in your changes in a better way.
> 
> cc @databunks



@tudoranghelina91 Sorry i assumed that the status of the project was idle as it had been since April,
if you have made any changes you feel should be added do tag me and we will just compare them,
here is the PR im tryna resolve: https://github.com/dotnet/runtime/pull/78341

**Closed** 2023-03-23 10:59 UTC
Labels: good first issue, help wanted, area-CoreLib-mono, in-pr
