### ISSUE TITLE
Test failure: System.NullReferenceException : Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#39615] opened 2020-07-20 02:04 UTC
failed in job: [runtime 20200718.40 ](https://dev.azure.com/dnceng/public/_build/results?buildId=737083&view=ms.vss-test-web.build-test-results-tab&runId=22828620&resultId=122456&paneView=debug)

failed tests:
System.Text.Json.Tests.Utf8JsonReaderTests.InvalidJsonWhenPartial
System.Xml.Tests.TCGetExpectedParticles.CallForExtendedSequence_Before_After_ValidatingSeqOrAllBaseElements

Error message
~~~
System.NullReferenceException : Object reference not set to an instance of an object.


Stack trace
   at System.Reflection.CustomAttributeTypedArgument.CanonicalizeValue(Object value)
   at System.Reflection.CustomAttributeTypedArgument..ctor(Type argumentType, Object value)
   at System.Reflection.CustomAttributeData.ResolveArguments()
   at System.Reflection.CustomAttributeData.get_ConstructorArguments()
   at ReflectionAbstractionExtensions.GetCustomAttributes(IMethodInfo methodInfo, Type attributeType)
~~~

**Comment by safern** [comment] 2020-07-20 21:24
Dupe of: https://github.com/dotnet/runtime/issues/39473

**Closed by safern** 2020-07-20 21:24 UTC
Labels: area-System.Text.Json, untriaged
