### ISSUE TITLE
Test failure: GC/API/GC/GetTotalAllocatedBytes/GetTotalAllocatedBytes.sh

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#106305] opened 2024-08-13 01:29 UTC
**Failed in:** [runtime-coreclr crossgen2 20240811.2](https://dev.azure.com/dnceng-public/public/_build/results?buildId=772414&view=ms.vss-test-web.build-test-results-tab&runId=19740514&resultId=115530&paneView=debug)

**Failed tests:**
```
R2R-CG2 osx arm64 Checked @ OSX.1200.ARM64.Open
    - GC/API/GC/GetTotalAllocatedBytes/GetTotalAllocatedBytes.sh
```

**Error message:**
```
 /private/tmp/helix/working/B4220A30/w/B21A09B6/e/GC/API/GC/GetTotalAllocatedBytes/GetTotalAllocatedBytes.sh: line 322: -r:/private/tmp/helix/working/B4220A30/w/B21A09B6/e/GC/API/GC/GetTotalAllocatedBytes/IL-CG2/*.dll: No such file or directory
Unhandled exception. ILCompiler.CodeGenerationFailedException: Code generation failed for method '[GetTotalAllocatedBytes]Test_GetTotalAllocatedBytes.CallGetTotalAllocatedBytes(Counts)'
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Internal.JitInterface.CorInfoImpl._beginInlining(IntPtr thisHandle, IntPtr* ppException, CORINFO_METHOD_STRUCT_* inlinerHnd, CORINFO_METHOD_STRUCT_* inlineeHnd) in /_/src/coreclr/tools/Common/JitInterface/CorInfoImpl_generated.cs:line 154
   --- End of inner exception stack trace ---
   at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(IMethodNode methodCodeNodeNeedingCode, MethodIL methodIL) in /_/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:line 381
   at Internal.JitInterface.CorInfoImpl.CompileMethod(MethodWithGCInfo methodCodeNodeNeedingCode, Logger logger) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs:line 810
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass50_0.<ComputeDependencyNodeDependencies>g__CompileOneMethod|5(DependencyNodeCore`1 dependency, Int32 compileThreadId) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 898
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass50_0.<ComputeDependencyNodeDependencies>g__CompileOnThread|4(Int32 compilationThreadId) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 833
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass50_0.<ComputeDependencyNodeDependencies>g__CompilationThread|3(Object objThreadId) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 811
   at System.Threading.Thread.StartCallback()
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'array')
   at System.Array.Clear(Array array, Int32 index, Int32 length)
   at Internal.JitInterface.CorInfoImpl.CompileMethodCleanup() in /_/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs:line 699
   at Internal.JitInterface.CorInfoImpl.CompileMethod(MethodWithGCInfo methodCodeNodeNeedingCode, Logger logger) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/JitInterface/CorInfoImpl.ReadyToRun.cs:line 826
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass50_0.<ComputeDependencyNodeDependencies>g__CompileOneMethod|5(DependencyNodeCore`1 dependency, Int32 compileThreadId) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 898
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass50_0.<ComputeDependencyNodeDependencies>g__CompileOnThread|4(Int32 compilationThreadId) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 833
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass50_0.<ComputeDependencyNodeDependencies>g__CompilationThread|3(Object objThreadId) in /_/src/coreclr/tools/aot/ILCompiler.ReadyToRun/Compiler/ReadyToRunCodegenCompilation.cs:line 811
   at System.Threading.Thread.StartCallback()
/private/tmp/helix/working/B4220A30/w/B21A09B6/e/GC/API/GC/GetTotalAllocatedBytes/GetTotalAllocatedBytes.sh: line 261: 77276 Abort trap: 6           (core dumped) $__Command

Return code:      1
Raw output file:      /tmp/helix/working/B4220A30/w/B21A09B6/uploads/Reports/GC.API/GC/GetTotalAllocatedBytes/GetTotalAllocatedBytes.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/private/tmp/helix/working/B4220A30/w/B21A09B6/e/GC/API/GC/GetTotalAllocatedBytes/IL-CG2/GetTotalAllocatedBytes.dll
00:04:00
Response file: /private/tmp/helix/working/B4220A30/w/B21A09B6/e/GC/API/GC/GetTotalAllocatedBytes/GetTotalAllocatedBytes.dll.rsp
/private/
```

**Stack trace:**
```
   at GC_API._GC_GetTotalAllocatedBytes_GetTotalAllocatedBytes_._GC_GetTotalAllocatedBytes_GetTotalAllocatedBytes_sh()

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by jakobbotsch** [comment] 2024-08-13 08:43
Duplicate of #105441

**Closed by jakobbotsch** 2024-08-13 08:43 UTC
Labels: arch-arm64, os-mac-os-x, area-crossgen2-coreclr, untriaged, blocking-clean-ci-optional
