### ISSUE TITLE
"Common Language Runtime detected an invalid program." Exception encountered - on "(dynamic)" method call for overload resolution

### ISSUE THREAD

**Issue by sean-bloch** [dotnet/runtime#82239] opened 2023-02-16 16:40 UTC
### Description

**"detected an invalid program"** is encountered when using `(dynamic)` on a method parameter, in attempt to select proper concrete method overload.

It seems to be related to some specific cases, as the repro example uses generics and static abstract interfaces; meanwhile, a simple working program does not throw the error. 

This is on dotnet 7.0.2

### Reproduction Steps

**Repro Description:** This is a simplified console app that exhibited the same behavior as originally encountered. In expected behavior, most other language features are removed and the "dynamic overload" works. 

The "invalid program" error is encountered in a case where 
- `record` types are used to attempt to avoid "primitive obsession" (ref. Andrew Lock) with string values
-  operator overloads are used to convert to string
-  ToString() is a sealed override to default record behavior in interpolated strings
-  aliases are used to reduce typing a longer `ReadOnlySpan<char>` 
-  generics and static abstract interfaces are used to try and provide business logic type validation
-  stongly typed implementations of an abstract class are used to create type checking around a set of values.
-  private classes are used to keep logic within the bounds of a business logic class

**Code for reproduction example:**
```csharp
using stringSpan = System.ReadOnlySpan<char>; //because the original source did it.

namespace ReproAttempt_InvalidProgram_DynamicOverload;

internal class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine("Hello, World! // let's try to repro!!");

        //Command:
        Console.Error.WriteLine("Create ExistingCommand...");
        var del = new SampleCommandDefinition(SampleCommandType.Delete);
        var ins = new SampleCommandDefinition(SampleCommandType.Create);

        var etc = new ExistingCommandDefinition(del,(FilePath) @"A:\FloppyLogic\" );
        Console.Error.Write($" .. okay!{Environment.NewLine}");

        //Worker:
        Console.Error.WriteLine("Attempt TheThing...");

        SampleWorker processor = new SampleWorker(etc);
        Console.Error.Write($" .. working ..");

        string txt = processor.SomeConstructedText; //spoiler: this fails, even if changed to a method "SomeConstructedText()"
        Console.Out.WriteLine($"[out::]  {txt}");

        Console.Error.Write($" .. okay!{Environment.NewLine}"); 
    }
}

#region references repro

//Carried over from the initially impacted project as an example. 
//Inspired by Andrew.Lock "strongly typed id's"
public record TypedString (string AsString) { public static implicit operator string(TypedString ts) => ts.AsString;
        public static explicit operator TypedString(string s) => new TypedString(s); 
        public override sealed string ToString() => (string)this;
    };

//represents a type that already exists. 
//command types are separated by an enum value.
//we want to attempt to create a strongly type container
//that is a projection of the enumerated type value.
public enum SampleCommandType
{
    Create,
    Delete
}

public readonly record struct SampleCommandDefinition ( SampleCommandType CommandType )
{
    public string CommandName => $"{this.CommandType}";
}

//e.g., FilePath tempdir = (FilePath)@"C:\Temp\"; @"C:\Temp\" == tempdir.AsString; @"C:\Temp\" == (string)tempdir;
public partial record FilePath : TypedString { public FilePath(string path) : base(path) { } }
public partial record FilePath
{ public static explicit operator FilePath(string s) => new FilePath(s); }

//in this example, consider a "File Command" that has a "Path" and an "Operation"
public record struct ExistingCommandDefinition (SampleCommandDefinition Command, FilePath Path);
    
#endregion references repro

#region container repro

//e.g. "''Base'' Functionality File"
public partial class SampleWorker
{ 
    private FileActionContainer ActionItem;

    //now see here:
    public string SomeConstructedText => SomeConstructedInformation((dynamic) this.ActionItem);

    public SampleWorker(ExistingCommandDefinition actionItem) => this.ActionItem = FileActionContainer.Create(actionItem);

    //One capability of the SampleWorker, may be to generate textual information about the instance's ActionItem
    //(dynamic) is used to select the method overload based on the runtime type created
    private stringSpan SomeConstructedInformation(object fallbackItem)
    {
        return $"/// {nameof(fallbackItem)}";
    }

    //should always "fall back" to this if concrete method implementation is not provided. ''(object)'' overload is more of a sanity check
    private stringSpan SomeConstructedInformation(FileActionContainer itemContainer)
    {
        return $"/// default unimplemented information for {itemContainer.CommandItem.Command.CommandName} , {itemContainer.CommandItem.Path}";
    }

    //classes are used by an instance of a SampleWorker. 
    //partial classes are used for adding functionality in additional template generated files
    private interface IActionContainerTypeGuard<K> where K : FileActionContainer
    {
        //all implementations will return the associated underlying CommandType
        static abstract SampleCommandType Command { get; }
    }

    //Create generic constructor logic that checks the projected concrete type
    // against the property of the object being wrapped. 
    private abstract class CommandTypeGuard<T,K> : FileActionContainer
        where T : IActionContainerTypeGuard<K>
        where K : FileActionContainer
    {
        public CommandTypeGuard(ExistingCommandDefinition commandItem)
        {
            if(commandItem.Command.CommandType != T.Command)
            {
                throw new ArgumentException($"{nameof(commandItem)} must be {T.Command}");
            }
            this.CommandItem = commandItem;
        }
    }

    //Inspired by "keyed dictionary". Create a container of concrete type based on property of contained object
    private abstract class FileActionContainer
    {
        public ExistingCommandDefinition CommandItem { get;init; }
        
        public static FileActionContainer Create(ExistingCommandDefinition commandItem) =>
            //the idea is that after this, dynamic type checking can "Filter" based on method overloading, for example. (''one switch to rule them all'')
            commandItem.Command.CommandType switch
            {
                SampleCommandType.Create => new FileCreateActionContainer(commandItem)
              , SampleCommandType.Delete => new FileDeleteActionContainer(commandItem)
              , _ => throw new NotImplementedException()
            };

        public sealed class FileCreateActionContainer : CommandTypeGuard<FileCreateActionContainer,FileCreateActionContainer>,IActionContainerTypeGuard<FileCreateActionContainer>
        {
            public FileCreateActionContainer(ExistingCommandDefinition commandItem_Create) : base(commandItem_Create) {  }
            public static SampleCommandType Command => SampleCommandType.Create; //''Type Guard'' will validate the property on commandItem_Create 
        }
            
        public sealed class FileDeleteActionContainer : CommandTypeGuard<FileDeleteActionContainer,FileDeleteActionContainer>,IActionContainerTypeGuard<FileDeleteActionContainer>
        {
            public FileDeleteActionContainer(ExistingCommandDefinition commandItem_Delete) : base(commandItem_Delete) {  }
            public static SampleCommandType Command => SampleCommandType.Delete; //''Type Guard'' will validate the property on commandItem_Delete 
        } 
    }

}

//e.g. "''Create'' Functionality File"
public partial class SampleWorker
{ 
    //logic for "Create" Actions
    private stringSpan SomeConstructedInformation(FileActionContainer.FileCreateActionContainer itemContainer)
    {
        return $"CREATE (plus, Lorem Ipsum info, etc) {itemContainer.CommandItem.Path} , zz123abc....";
    }
}

//e.g. "''Delete'' Functionality File"
public partial class SampleWorker
{ 
    //logic for "Create" Actions
    private stringSpan SomeConstructedInformation(FileActionContainer.FileDeleteActionContainer itemContainer)
    {
        return $"DELETE (minus, Lorem Ipsum info, etc) {itemContainer.CommandItem.Path} , zz123abc....";
    }
}
#endregion container repro

```

### Expected behavior

**Expected Behavior Description:** The following sample shows the expected behavior of the `(dynamic)` method overload. Language feature usage is reduced and classes are declared as public without the use of generics, while still making use of:
- strongly typed implementations of an abstract base class
- a `Create()` method returns a concrete class based on an input value
- `(dynamic)` method overload calls the concrete implementation of a method at runtime;

**Code for expected behavior example:**
```csharp
namespace ReproAttempt_WorkingProgram_SimpleDynamicOverload;

internal class Program
{
    SimpleBase NumberSample;
    
    internal Program(int x)
    {
        this.NumberSample = SimpleBase.Create(x);
    }

    static void Main(string[] args)
    {
        Console.WriteLine("Hello, World! // let's see if this works!");

        Program program = new(8);

        string success = program.DynamicNumber();
        Console.WriteLine($"test: {success}"); //spoiler: it does :-)
    }

    public string DynamicNumber() => WriteNumber((dynamic) this.NumberSample);

    public string WriteNumber(ConcretePositive num) => $"+ {num.Text}";
    public string WriteNumber(ConcreteNegative num) => $"- {num.Text}";
    public string WriteNumber(ConcreteZero     num) => $"_ {num.Text}";
    public string WriteNumber(object           num) => $"??{nameof(num)}??";
}

public abstract class SimpleBase
{
    private int NumberValue;

    public SimpleBase(int numberValue)
    {
        this.NumberValue = numberValue;
    }

    public static SimpleBase Create(int x)
    {
        if (x == 0)
            return new ConcreteZero(x);
        if (x  > 0)
            return new ConcretePositive(x);
        else
            return new ConcreteNegative(x);
    }

    public string Text => $"[{this.NumberValue}]";
}

public sealed class ConcretePositive : SimpleBase
{
    public ConcretePositive(int positiveNumber) : base(positiveNumber) { }
}
public sealed class ConcreteNegative : SimpleBase
{
    public ConcreteNegative(int negativeNumber) : base(negativeNumber) { }

}public sealed class ConcreteZero : SimpleBase
{
    public ConcreteZero(int zeroValue) : base(zeroValue) { }
}
```

### Actual behavior

Debugger breaks at the dynamic method call with the following information from

Microsoft Visual Studio Professional 2022 (2) (64-bit) - Current
Version 17.4.4

#### HResult

   -2146233030

#### Stack Trace , ($exception).StackTrace

```
   at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType, Object target)
    at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
    at System.Linq.Expressions.Expression`1.Compile()
    at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
    at ReproAttempt_InvalidProgram_DynamicOverload.SampleWorker.get_SomeConstructedText() in C:\Code\notes\record_repro\RecordTest\ReproAttempt_InvalidProgram_DynamicOverload\Program.cs:line 74
    at ReproAttempt_InvalidProgram_DynamicOverload.Program.Main(String[] args) in C:\Code\notes\record_repro\RecordTest\ReproAttempt_InvalidProgram_DynamicOverload\Program.cs:line 25
```
    
#### Message 

   Common Language Runtime detected an invalid program.
   
#### Source

   System.Private.CoreLib
   
###### AssemblyQualifiedName

   `System.Reflection.Emit.DynamicMethod, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e`

### Known Workarounds

The workaround was to not attempt dynamic method overloads, and to define additional type checking logic to call a specific method. 

As shown in the "Expected Behavior", workarounds may also involve avoiding some language features, if possible.

### Configuration

OS: Windows 10 19045

Visual Studio: 17.4.4

Tested on different built configurations, debug / release / x86 / "Windows" target vs "None"

Output from `dotnet --list-runtimes` : 
```


.NET SDKs:
Version      Status
----------------------------------------
3.1.425      .NET 3.1 is out of support.
6.0.400      Patch 6.0.406 is available.
6.0.401      Patch 6.0.406 is available.
7.0.102      Patch 7.0.103 is available.

Try out the newest .NET SDK features with .NET 7.0.200.

.NET Runtimes:
Name                              Version      Status
--------------------------------------------------------------------------
Microsoft.AspNetCore.App          3.1.9        .NET 3.1 is out of support.
Microsoft.NETCore.App             3.1.9        .NET 3.1 is out of support.
Microsoft.AspNetCore.App          3.1.31       .NET 3.1 is out of support.
Microsoft.NETCore.App             3.1.31       .NET 3.1 is out of support.
Microsoft.WindowsDesktop.App      3.1.31       .NET 3.1 is out of support.
Microsoft.AspNetCore.App          3.1.32       .NET 3.1 is out of support.
Microsoft.NETCore.App             3.1.32       .NET 3.1 is out of support.
Microsoft.WindowsDesktop.App      3.1.32       .NET 3.1 is out of support.
Microsoft.AspNetCore.App          6.0.8        Patch 6.0.14 is available.
Microsoft.NETCore.App             6.0.8        Patch 6.0.14 is available.
Microsoft.WindowsDesktop.App      6.0.8        Patch 6.0.14 is available.
Microsoft.AspNetCore.App          6.0.9        Patch 6.0.14 is available.
Microsoft.NETCore.App             6.0.9        Patch 6.0.14 is available.
Microsoft.WindowsDesktop.App      6.0.9        Patch 6.0.14 is available.
Microsoft.AspNetCore.App          6.0.13       Patch 6.0.14 is available.
Microsoft.NETCore.App             6.0.13       Patch 6.0.14 is available.
Microsoft.WindowsDesktop.App      6.0.13       Patch 6.0.14 is available.
Microsoft.AspNetCore.App          7.0.2        Patch 7.0.3 is available.
Microsoft.NETCore.App             7.0.2        Patch 7.0.3 is available.
Microsoft.WindowsDesktop.App      7.0.2        Patch 7.0.3 is available.
```

**Comment by cston** [comment] 2024-09-04 20:56
@sean-bloch, thanks for reporting this issue.

It looks like the repro depends on static abstract members in interfaces which is not a supported scenario with dynamic.

**Comment by cston** [comment] 2024-09-04 21:00
Unfortunately, the Microsoft.CSharp library is effectively archived, and we are only taking changes that address significant bugs or regressions, or changes needed to continue shipping - see [README.md](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.CSharp/README.md).

Closing since this is not a supported scenario.

**Closed by cston** 2024-09-04 21:00 UTC
Labels: area-Microsoft.CSharp, untriaged
