### ISSUE TITLE
[API Proposal]: Support ref struct as generic parameter of a generic ref struct type

### ISSUE THREAD

**Issue by simonferquel** [dotnet/runtime#64197] opened 2022-01-24 09:58 UTC
### Background and motivation

Twitter discussion here: https://twitter.com/sferquel/status/1485547279205478407?s=20
In Unity, I am experimenting with a native refcounted string type to avoid repetitive utf8 <-> utf16 conversions, as well as being able to pass strings from/to native code in a p/invoke compatible way, without extra-copies. 

So in native code, I have a refcounted type, and in managed code I have:
- a `class NativeString` that increment the refcount on construction / decrement on finalizer
- a `ref struct NativeStringRef` allowing to pass a native string from native code safely without having to increment/decrement the refcount. 

The problem I have, is that I can't pass a `Span<NativeStringRef>` from native to managed (because ref struct can't be used as generic parameter) and thus I have to choose between:
- the safetyness of ref struct that prevents dangling pointers to live in managed code
- the type-safetyness of passing a strongly typed `Span<NativeStringRef>` instead of `Span<IntPtr>` from native to managed code.

### API Proposal

Add a "ref struct" generic parameter constraint, which would make the compiler enforce ref struct limitations for the generic parameter. eg:

```C#
public class SomeGenericType<T> where T: ref struct
{
   T value; // compilation fails, T is a ref struct, can't be a field of a non-ref struct type
   void SomeMethod(T); // ok: ref struct can be used as a method parameter
}

public ref struct SomeGenericRefStruct<T> where T: ref struct
{
   T value; // ok: T is a ref struct, but as SomeGenericRefStruct`1 is a ref struct as well, it is allowed
}

SomeGenericRefStruct<string> someVariable; // ok: string is not a ref struct, but in that case the restriction don't apply to the 
   // type parameter itself, but to the usage of this type withing the generic method 
   // or type
```
Also, change Span<T> and ReadOnlySpan<T> to consider T like a ref struct. (Span / ReadOnlySpan are already ref structs, so they should be ok with exposing a collection of ref struct as well)

### API Usage

Main goal would be to support things like:

```C#
public ref struct NativeStringRef 
{
   private readonly IntPtr _nativeStringPointer;
   <... some methods allowing to do string operations with that ...>
}

public void SomeApi(ReadOnlySpan<NativeStringRef> strings)
{
 ...
}
```

**Comment by KalleOlaviNiemitalo** [comment] 2022-01-24 11:02
`where T: ref struct` is <https://github.com/dotnet/csharplang/issues/1148>.

> change Span and ReadOnlySpan to consider T like a ref struct.

That might be more difficult because it would need more complex ref safety rules.

**Comment by stephentoub** [comment] 2022-01-24 12:02
Closing as duplicate of https://github.com/dotnet/csharplang/issues/1148. cc: @jaredpar.  Support here involves both language and runtime changes, but that issue represents the overall effort.

**Closed by stephentoub** 2022-01-24 12:02 UTC
Labels: api-suggestion, untriaged
