### ISSUE TITLE
Consider adding System.ReadOnlySpan<char>.Replace()

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#1927] opened 2020-01-19 22:48 UTC
There has been a couple of string extensions adopted for System.ReadOnlySpan<char> such as Trim(), IsWhitespace(), ToUpper(), ToLower() but an often used extension Replace() is missing. Working with spans devs currently have to either create their own extension or using ToString() which adds unnecessary allocations.

```
public static ReadOnlySpan<char> Replace(this ReadOnlySpan<char> source, ReadOnlySpan<char> oldValue, ReadOnlySpan<char> newValue, StringComparison comparison);
```

**Comment by vcsjones** [comment] 2020-01-19 23:17
`Trim{End,Start}` can be implemented in such a way that they do not require mutating the data in the underlying span - it can simply return a `Slice` of the original span at the correct bounds.

`Replace` on the other hand mutates the underlying data, and/or increases/decreases the length. I think then the API would need to accept a destination buffer, like the `To{Upper,Lower}` APIs:

```csharp
public static int Replace(
    this ReadOnlySpan<char> source,
    ReadOnlySpan<char> oldValue,
    ReadOnlySpan<char> newValue,
    Span<char> destination,
    StringComparison comparison);
```

**Comment by Tornhoof** [comment] 2020-01-19 23:18
In the original discussion this API quickly ran into the problem of longer replacement strings and then the API would need to silently allocate. 
See https://github.com/dotnet/corefx/issues/38192 for more discussion.

**Comment by GrabYourPitchforks** [comment] 2020-01-19 23:58
Hi all - I'm going to close this issue as a dupe of https://github.com/dotnet/corefx/issues/38192. There's already a proposed API there, so feel free to +1 it or to make further recommendations in that thread. If there's general consensus of "move this forward" in that thread then we can move things forward from there.

**Closed by GrabYourPitchforks** 2020-01-19 23:58 UTC
Labels: area-System.Memory, untriaged
