### ISSUE TITLE
Improve allocations in `ConfigurationBinder`

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/runtime#67566] opened 2022-04-05 00:37 UTC
`BindingPoint` class was added recently in this PR https://github.com/dotnet/runtime/pull/66723. This could cause extra unwanted allocation when using `BindInstance`. Would be good to change it to struct instead.

The reason we care about this is `BindInstance` could occur once per request when using `IOptionsSnapshot` (somewhat related to https://github.com/dotnet/runtime/issues/53793).

Would be good to run some benchmarks for this, see before/after with adding `BindingPoint`. Would be good to reduce further allocations in `ConfigurationBinder`.

cc @madelson

**Comment by heathbm** [comment] 2022-04-05 02:11
I have some time to work on this

**Comment by maryamariyan** [comment] 2022-04-05 16:03
@heathbm sure!

**Comment by madelson** [comment] 2022-04-06 11:01
@maryamariyan 

`BindingPoint` could definitely be a struct. A few callouts:
* Would need to be passed as `ref` since it is mutable
* To eliminate all associated allocations we'd need to also use a state arg pattern to avoid allocating closures
* Another option would be to keep using a `class`, but make the object re-usable and avoid creating a fresh one for each loop instance.

When implementing originally I considered this but went with `class` since it was simpler and `ConfigurationBinder` as a whole did not seem to be making an effort to avoid allocations / be hyper-efficient.

Just some examples (I imagine folks are already aware of these, but calling them out anyway):
* Lots of `foreach` loops over non-struct enumerators
* A good amount of LINQ
* Calls to reflection methods like `GetProperties()` and `GetInterfaces()` which allocate arrays
* Loops that call collection.add/dictionary indexer via reflection, allocating arrays
* All scalar values end up boxed
* Every call to `GetSection(string)` seems to allocate once if we're calling it on `ConfigurationRoot`, twice if we're calling it on `ConfigurationSection`. Every call to `GetChildren()` also seems like it should allocate if we're using `ConfigurationRoot`. I suppose concerned users could use a different `IConfiguration` implementation that avoids this.
* Various lambdas that create closures
* General use of reflection without creating delegates / using reflection emit to reduce overhead
* Different options structures (e. g. nested vs. not, collections vs. not, property types) will probably result in very different allocation profiles.

Anyway, I agree that it makes sense to benchmark the impact of the `BindingPoint` change and possibly look into some of above as well. 

Looks like @heathbm has jumped on this but I'd also be happy to help out if there is something I can add.

**Comment by heathbm** [comment] 2022-04-06 17:09
@madelson If you would like to take this please go ahead, as you are already be aware of the changes required. I was just in the exploratory phase of this issue. I would be happy to still provide help if I can.

**Comment by tarekgh** [comment] 2022-04-06 17:28
@madelson thanks again for willing to help. 

>  I agree that it makes sense to benchmark the impact of the BindingPoint change and possibly look into some of above as well.

can you do that?

**Comment by madelson** [comment] 2022-04-06 21:44
@tarekgh sure; probably will be later this week or this weekend. 

I’m imagining capturing a before/after count of allocated bytes for a *warm* bind (since the concern is repeated calls).

**A key question I have** is what sort of options type you care about. Just a poco with scalar fields? Nested Pocos? Large collections? Small collections? Each will hit pretty different code.

**Comment by tarekgh** [comment] 2022-04-06 22:23
> A key question I have is what sort of options type you care about. Just a poco with scalar fields? Nested Pocos? Large collections? Small collections? Each will hit pretty different code.

You can have a perf test case for each type you listed so we can know the cost with different scenarios.

> Also, is the goal here just to avoid allocation regression or to make the binder as allocation-free as possible?

Per @maryamariyan, this configuration binding is happening occur once per request. So, we are trying to calculate the extra allocation happening per request.  If we can try to avoid the extra allocations, that will be fantastic. Otherwise, at least we need to know how much overhead we added with this change.

**Comment by madelson** [comment] 2022-04-08 19:57
@tarekgh ok I ran a quick benchmark (https://gist.github.com/madelson/a00d163d6aa3b6add4f01f206f4fbde2). The `Options` object here is based on `MvcOptions` in terms of field count and types. The results were surprising:

Results are `(scalar fill factor, collection size) -> bytes (ratio)`

BEFORE BindingPoint change:
```
(0.5, 2) -> 57,832
(0.5, 20) -> 2,323,496
(1, 2) -> 58,216
(1, 20) -> 2,326,336
```

AFTER BindingPoint change:
```
  (0.5, 2) -> 46,304
  (0.5, 20) -> 749,992
  (1, 2) -> 42,808
  (1, 20) -> 745,424
```
In ratio form (1.0 is before):
```
  (0.5, 2) -> 0.8
  (0.5, 20) -> 0.32
  (1, 2) -> 0.74
  (1, 20) -> 0.32
```

Unless I'm doing something wrong, this is showing at, at least for the examples tested, **the `BindingPoint` code allocates fewer bytes than before**.

Like I said, this surprises me. The changes do have some allocation-improvements (e. g. we used to wastefully call `PropertyInfo.GetValue()` twice for primitive type properties, which would result in boxing. On the other hand, the new code has to allocate `BindingPoint` instances and sometimes delegates/closures to go along with those instances.

@heathbm or @tarekgh it would be great if someone can try to replicate my results (just copy the benchmark file into the ConfigurationBinder tests project and run the tests) and/or review the benchmark to make sure I'm not doing something silly.

**Comment by eerhardt** [comment] 2022-04-08 20:17
Can you try using BenchmarkDotNet and a MemoryDiagnoser? https://adamsitnik.com/the-new-Memory-Diagnoser/

**Comment by madelson** [comment] 2022-04-09 17:28
@eerhardt sure. For my understanding, can you explain why you expect the memory results will be different with BenchmarkDotNet? From the link you sent, it also uses `GC.GetAllocatedBytesForCurrentThread()` to measure memory allocations.

**Comment by eerhardt** [comment] 2022-04-09 18:02
> why you expect the memory results will be different

I don't necessarily expect them to be different. But I trust the BenchmarkDotNet MemoryDiagnoser since I've used it in the past. If it comes out with the same results, then we know your hand-written code is correct.

**Comment by madelson** [comment] 2022-04-10 13:34
Ok I had the chance to make a dotnet/performance benchmark for this (https://github.com/dotnet/performance/pull/2360) and run a comparison against a branch before the recent changes and main. I used [this workflow](https://github.com/dotnet/performance/blob/main/docs/benchmarking-workflow-dotnet-runtime.md).

The results are consistent with what I found with my manual measurement:

## BEFORE

|     Method | ScalarFillFactor | CollectionSize |       Mean |     Error |    StdDev |     Median |        Min |         Max |    Gen 0 |  Allocated |
|----------- |----------------- |--------------- |-----------:|----------:|----------:|-----------:|-----------:|------------:|---------:|-----------:|
| GetOptions |              0.5 |              1 |   168.2 us |   2.82 us |   2.20 us |   168.7 us |   163.6 us |    171.1 us |  10.9536 |   34.91 KB |
| GetOptions |              0.5 |             20 | 9,223.7 us | 305.25 us | 326.62 us | 9,208.8 us | 8,775.3 us | 10,015.9 us | 727.2727 | 2276.51 KB |
| GetOptions |                1 |              1 |   158.7 us |   1.32 us |   1.23 us |   158.7 us |   156.0 us |    160.8 us |  12.1561 |   37.33 KB |
| GetOptions |                1 |             20 | 9,281.4 us | 787.61 us | 907.01 us | 8,829.1 us | 8,390.8 us | 11,259.3 us | 714.2857 | 2277.58 KB |

## AFTER

|     Method | ScalarFillFactor | CollectionSize |        Mean |       Error |      StdDev |      Median |        Min |         Max |    Gen 0 | Allocated |
|----------- |----------------- |--------------- |------------:|------------:|------------:|------------:|-----------:|------------:|---------:|----------:|
| GetOptions |              0.5 |              1 |    148.5 us |    16.75 us |    19.29 us |    145.1 us |   124.1 us |    187.2 us |   9.5694 |  30.94 KB |
| GetOptions |              0.5 |             20 |  8,398.2 us |   278.65 us |   273.67 us |  8,368.7 us | 8,007.2 us |  9,035.1 us | 210.5263 | 734.39 KB |
| GetOptions |                1 |              1 |    138.1 us |     6.79 us |     7.54 us |    136.7 us |   127.5 us |    153.4 us |   9.0395 |  28.04 KB |
| GetOptions |                1 |             20 | 10,673.2 us | 1,582.77 us | 1,822.72 us | 10,830.4 us | 8,210.1 us | 14,752.7 us | 214.2857 | 731.69 KB |

The one thing this doesn't rule out is that some other change deeper in the runtime is responsible for these improvements (e. g. if someone eliminated some allocations in System.Reflection around the same time). Even so, it does feel like things are better than they were prior to the `BindingPoint` change.

Thoughts on where to go next? Should we try to further eliminate allocations here?

**Comment by tarekgh** [comment] 2022-04-10 20:26
@madelson Looks we are good then. There is no regression even if the improvement comes from the runtime.  If you are interested in measuring only your changes (without the runtime factor), you can build the main (which includes the runtime changes and your changes) then run the BDN tests using these bits. Then revert only your commit changes and rebuild and rerun the BDN on these built bits again. This can give you accurate numbers without the runtime factor. Here is the link how to run against the private bits https://benchmarkdotnet.org/articles/configs/toolchains.html#corerun.

```
build.cmd -c Release -subset clr+libs
dotnet run -c Release -f net7.0 --corerun c:\oss\runtime\artifacts\bin\testhost\net7.0-windows-Release-x64\shared\Microsoft.NETCore.App\7.0.0\corerun.exe --filter **  
```

Just ensure you install `net7.0` bits from https://github.com/dotnet/installer.

But in general, I see we are good here and we can close this issue.

**Closed** 2022-04-12 21:19 UTC
Labels: up-for-grabs, area-Extensions-Configuration
