### ISSUE TITLE
Unable to bind dictionary with int key type from appsettings.json to options class

### ISSUE THREAD

**Issue by mat-kul** [dotnet/runtime#36044] opened 2020-02-28 10:36 UTC
### Describe the bug
When options class has a dictionary with key of int type is not possible to bind this dictionary into options class.

### To Reproduce
Create Asp.Net core web application
Add options class

``` C#
    public class MyOptions
    {
        public string Name { get; set; }
        public Dictionary<int, string> TestDictionary { get; set; }
    }
```

Then modify appsettings.json
``` json
{
    "MyOptions": {
        "Name": "test",
        "TestDictionary": {
            "1": "abc",
            "2": "def" 
        } 
    },
    "Logging": {
        "LogLevel": {
            "Default": "Information",
            "Microsoft": "Warning",
            "Microsoft.Hosting.Lifetime": "Information"
        }
    },
    "AllowedHosts": "*"
}

```

Then in Startup.ConfigureServices add
``` C#
services.Configure<MyOptions>(options => Configuration.GetSection("MyOptions").Bind(options));
```

Finally inject IOptionsSnapshot somewhere, you will see that dictionary inside these options is empty.

Binding works correctly when key of this dictionary is string type 

### Further technical details
 .NET Core SDK
 Version:   3.1.101
 Commit:    b377529961
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

The IDE
Visual Studio Enterprise 2019 version 16.4.3

**Comment by ericstj** [comment] 2020-07-07 19:52
@beppemarazzi  suggested a PR to fix this.  I think we'd need to consider what this means for existing configuration providers.  Would they break if they start seeing non-string/enum keys?

**Comment by thorgeirk11** [comment] 2021-01-07 16:16
Should this not be fixed with the release of .net 5? 
System.Text.Json now supports this by default...

We are running into this problem aswell

**Comment by ericstj** [comment] 2021-01-07 16:47
No, the issue is still opened and it is not fixed: https://github.com/dotnet/runtime/blob/9538bee0fc1fb24993217071e954d9597385485f/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs#L393-L397

This seems like a reasonable feature but it needs to be discussed and folks need to consider what the implications are for other existing configuration providers.  Will this cause any compatibility issues?  Does everyone need to change to adopt this or can it be done solely in the binder?

**Comment by dpomBF** [comment] 2021-07-23 16:35
This is an important feature! Please consider and deliver.
Is there also a possibility to support class types? For ex: Dictionary<T, string>
Where T is the generic of any class.
Thanks!

**Comment by CleanCodeX** [comment] 2021-11-30 11:00
What's the status here? I would need to have various dictionary key types such as System.Type or int

**Comment by czd890** [comment] 2022-05-19 11:06
What's the status here? I would need 😥

**Comment by terryjbutler** [comment] 2022-06-30 15:17
Just came across this issue in a project myself.

**Comment by Blackclaws** [comment] 2022-08-24 13:16
Came across this issue when using strongly typed strings. Apparently this is fixed for int types in the upcoming version. I would like a general fix where there is a conversion from string to a type.

**Comment by tarekgh** [comment] 2022-08-24 21:11
We already supported the integer types in the PR #71609. We don't have any plan for supporting conversion from string to a type in near future. If you still want to track that feel free to open a new issue for that.

**Closed by tarekgh** 2022-08-24 21:11 UTC
Labels: feature-request, area-Extensions-Configuration
