### ISSUE TITLE
[Perf] Regression in Xml_ToStream Serializers

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#56016] opened 2021-07-20 17:15 UTC
### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Baseline | [71d0d2b275efa091f235c569f01869f39bfb7638](https://github.com/dotnet/runtime/commit/71d0d2b275efa091f235c569f01869f39bfb7638)
Compare | [e983168f871dcba090ff6ec08c0d2c7d4353fb8e](https://github.com/dotnet/runtime/commit/e983168f871dcba090ff6ec08c0d2c7d4353fb8e)
Diff | [Diff](https://github.com/dotnet/runtime/compare/71d0d2b275efa091f235c569f01869f39bfb7638...e983168f871dcba090ff6ec08c0d2c7d4353fb8e)

### Regressions in MicroBenchmarks.Serializers.Xml_ToStream&lt;MyEventsListerViewModel&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
[XmlSerializer_ - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/MicroBenchmarks.Serializers.Xml_ToStream(MyEventsListerViewModel).XmlSerializer_.html>) | 392.35 μs | 491.84 μs | 1.25 | 0.46 | False | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/MicroBenchmarks.Serializers.Xml_ToStream(MyEventsListerViewModel)_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/MicroBenchmarks.Serializers.Xml_ToStream(MyEventsListerViewModel).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'MicroBenchmarks.Serializers.Xml_ToStream&lt;MyEventsListerViewModel&gt;*'
```
<details>

### Payloads

[Baseline](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-7d96a373-9131-4df3-9ea4-1e6bc2bdef3f87e362253ea47aa9d/236c43da-4ed7-4b74-944d-bc1614d07b3a.zip?sv=2019-07-07&se=2021-08-14T17%3A40%3A44Z&sr=c&sp=rl&sig=I0Pui6Ea0enoivtEZHPGSoougHqlosZHQxEkGWjksqY%3D>)
[Compare](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-9e52a93f-cf09-4cd4-b5f0-234af4397a9f5ddd6b22baa435689/8459eac3-cea1-4233-8fad-57c02ee1e6d4.zip?sv=2019-07-07&se=2021-08-14T23%3A38%3A50Z&sr=c&sp=rl&sig=C46Mu4CDKDIJaLIXy%2B7vexGuT%2BWWsaDBxtvNTonGu38%3D>)

#### MicroBenchmarks.Serializers.Xml_ToStream&lt;MyEventsListerViewModel&gt;.XmlSerializer_

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>
### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Baseline | [71d0d2b275efa091f235c569f01869f39bfb7638](https://github.com/dotnet/runtime/commit/71d0d2b275efa091f235c569f01869f39bfb7638)
Compare | [e983168f871dcba090ff6ec08c0d2c7d4353fb8e](https://github.com/dotnet/runtime/commit/e983168f871dcba090ff6ec08c0d2c7d4353fb8e)
Diff | [Diff](https://github.com/dotnet/runtime/compare/71d0d2b275efa091f235c569f01869f39bfb7638...e983168f871dcba090ff6ec08c0d2c7d4353fb8e)

### Regressions in MicroBenchmarks.Serializers.Xml_ToStream&lt;IndexViewModel&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
[XmlSerializer_ - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/MicroBenchmarks.Serializers.Xml_ToStream(IndexViewModel).XmlSerializer_.html>) | 40.90 μs | 49.20 μs | 1.20 | 0.13 | False | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/MicroBenchmarks.Serializers.Xml_ToStream(IndexViewModel)_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/MicroBenchmarks.Serializers.Xml_ToStream(IndexViewModel).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'MicroBenchmarks.Serializers.Xml_ToStream&lt;IndexViewModel&gt;*'
```
<details>

### Payloads

[Baseline](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-7d96a373-9131-4df3-9ea4-1e6bc2bdef3f87e362253ea47aa9d/236c43da-4ed7-4b74-944d-bc1614d07b3a.zip?sv=2019-07-07&se=2021-08-14T17%3A40%3A44Z&sr=c&sp=rl&sig=I0Pui6Ea0enoivtEZHPGSoougHqlosZHQxEkGWjksqY%3D>)
[Compare](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-9e52a93f-cf09-4cd4-b5f0-234af4397a9f5ddd6b22baa435689/8459eac3-cea1-4233-8fad-57c02ee1e6d4.zip?sv=2019-07-07&se=2021-08-14T23%3A38%3A50Z&sr=c&sp=rl&sig=C46Mu4CDKDIJaLIXy%2B7vexGuT%2BWWsaDBxtvNTonGu38%3D>)

#### MicroBenchmarks.Serializers.Xml_ToStream&lt;IndexViewModel&gt;.XmlSerializer_

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by DrewScoggins** [comment] 2021-07-20 17:15
Seems related to https://github.com/dotnet/runtime/pull/55101

**Comment by DrewScoggins** [comment] 2021-07-20 17:20
Improvement:

### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Baseline | [71d0d2b275efa091f235c569f01869f39bfb7638](https://github.com/dotnet/runtime/commit/71d0d2b275efa091f235c569f01869f39bfb7638)
Compare | [e983168f871dcba090ff6ec08c0d2c7d4353fb8e](https://github.com/dotnet/runtime/commit/e983168f871dcba090ff6ec08c0d2c7d4353fb8e)
Diff | [Diff](https://github.com/dotnet/runtime/compare/71d0d2b275efa091f235c569f01869f39bfb7638...e983168f871dcba090ff6ec08c0d2c7d4353fb8e)


### Improvemnts in MicroBenchmarks.Serializers.Xml_FromStream&lt;MyEventsListerViewModel&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
[XmlSerializer_ - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/MicroBenchmarks.Serializers.Xml_FromStream(MyEventsListerViewModel).XmlSerializer_.html>) | 1.17 ms | 895.25 μs | 0.77 | 0.01 | True | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Improvement/MicroBenchmarks.Serializers.Xml_FromStream(MyEventsListerViewModel)_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Improvement/MicroBenchmarks.Serializers.Xml_FromStream(MyEventsListerViewModel).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'MicroBenchmarks.Serializers.Xml_FromStream&lt;MyEventsListerViewModel&gt;*'
```
<details>

### Payloads

[Baseline](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-7d96a373-9131-4df3-9ea4-1e6bc2bdef3f87e362253ea47aa9d/236c43da-4ed7-4b74-944d-bc1614d07b3a.zip?sv=2019-07-07&se=2021-08-14T17%3A40%3A44Z&sr=c&sp=rl&sig=I0Pui6Ea0enoivtEZHPGSoougHqlosZHQxEkGWjksqY%3D>)
[Compare](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-9e52a93f-cf09-4cd4-b5f0-234af4397a9f5ddd6b22baa435689/8459eac3-cea1-4233-8fad-57c02ee1e6d4.zip?sv=2019-07-07&se=2021-08-14T23%3A38%3A50Z&sr=c&sp=rl&sig=C46Mu4CDKDIJaLIXy%2B7vexGuT%2BWWsaDBxtvNTonGu38%3D>)

### Histogram
#### MicroBenchmarks.Serializers.Xml_FromStream&lt;MyEventsListerViewModel&gt;.XmlSerializer_

```log

```


### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>
### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Baseline | [71d0d2b275efa091f235c569f01869f39bfb7638](https://github.com/dotnet/runtime/commit/71d0d2b275efa091f235c569f01869f39bfb7638)
Compare | [e983168f871dcba090ff6ec08c0d2c7d4353fb8e](https://github.com/dotnet/runtime/commit/e983168f871dcba090ff6ec08c0d2c7d4353fb8e)
Diff | [Diff](https://github.com/dotnet/runtime/compare/71d0d2b275efa091f235c569f01869f39bfb7638...e983168f871dcba090ff6ec08c0d2c7d4353fb8e)


### Improvemnts in MicroBenchmarks.Serializers.Xml_FromStream&lt;IndexViewModel&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Edge Detector | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
[XmlSerializer_ - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/MicroBenchmarks.Serializers.Xml_FromStream(IndexViewModel).XmlSerializer_.html>) | 102.70 μs | 88.16 μs | 0.86 | 0.01 | False | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Improvement/MicroBenchmarks.Serializers.Xml_FromStream(IndexViewModel)_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_19_2021/refs/heads/main_x64_Windows%2010.0.18362_Improvement/MicroBenchmarks.Serializers.Xml_FromStream(IndexViewModel).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'MicroBenchmarks.Serializers.Xml_FromStream&lt;IndexViewModel&gt;*'
```
<details>

### Payloads

[Baseline](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-7d96a373-9131-4df3-9ea4-1e6bc2bdef3f87e362253ea47aa9d/236c43da-4ed7-4b74-944d-bc1614d07b3a.zip?sv=2019-07-07&se=2021-08-14T17%3A40%3A44Z&sr=c&sp=rl&sig=I0Pui6Ea0enoivtEZHPGSoougHqlosZHQxEkGWjksqY%3D>)
[Compare](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-9e52a93f-cf09-4cd4-b5f0-234af4397a9f5ddd6b22baa435689/8459eac3-cea1-4233-8fad-57c02ee1e6d4.zip?sv=2019-07-07&se=2021-08-14T23%3A38%3A50Z&sr=c&sp=rl&sig=C46Mu4CDKDIJaLIXy%2B7vexGuT%2BWWsaDBxtvNTonGu38%3D>)

### Histogram
#### MicroBenchmarks.Serializers.Xml_FromStream&lt;IndexViewModel&gt;.XmlSerializer_

```log

```


### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by mconnew** [comment] 2021-07-20 17:57
@DrewScoggins, #55101 wouldn't have caused a regression unless the types being serialized contain DateTimeOffset properties. If that's the case, then the regression is okay as we're doing more work as we're now actually serializing DateTimeOffset now. If there's no DateTimeOffset properties involved, then the problem was somewhere else.

**Comment by DrewScoggins** [comment] 2021-07-20 18:19
OK, those types do have DateTimeOffset.

**Comment by mconnew** [comment] 2021-07-20 18:25
Yes, that is exactly the case. Previously it would serialize as an empty XML element. Now it will output an XML format date time, and will deserialize it too.

**Comment by stephentoub** [comment] 2021-07-21 02:30
Closing as expected / by-design. Thanks.

**Closed by stephentoub** 2021-07-21 02:30 UTC
Labels: arch-x64, os-windows, tenet-performance, tenet-performance-benchmarks, untriaged
