### ISSUE TITLE
Test failure:JIT/IL_Conformance/Convert/TestConvertFromIntegral/TestConvertFromIntegral.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#56882] opened 2021-08-05 01:28 UTC
Run: [runtime-coreclr jitstress 20210803.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1275253&view=ms.vss-test-web.build-test-results-tab&runId=37718152&paneView=debug&resultId=101801)

Failed test:
```
CoreCLR Linux arm Checked jitstress1 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
JIT/IL_Conformance/Convert/TestConvertFromIntegral/TestConvertFromIntegral.sh
```
**Error message:**
```
Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/JIT.IL_Conformance/Convert/TestConvertFromIntegral/TestConvertFromIntegral.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun TestConvertFromIntegral.dll ''
No exception in DynamicConvertFromSystem.SingleToSystem.UInt640Opconv.ovf.u8
No exception in DynamicConvertFromSystem.SingleToSystem.UInt640Opconv.ovf.u8.un
The number of failed tests: 2
Expected: 100
Actual: 101
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/JIT/IL_Conformance/Convert/TestConvertFromIntegral/TestConvertFromIntegral.sh
Expected: True
Actual:   False


Stack trace
   at JIT_IL_Conformance._Convert_TestConvertFromIntegral_TestConvertFromIntegral_._Convert_TestConvertFromIntegral_TestConvertFromIntegral_sh() in JIT.IL_Conformance.XUnitWrapper.dll:token 0x6000004+0x295
```

**Comment by kunalspathak** [comment] 2021-08-05 23:18
Duplicate of https://github.com/dotnet/runtime/issues/56522.
cc: @sandreenko , @briansull , @janvorli

**Closed by kunalspathak** 2021-08-05 23:18 UTC
Labels: os-linux, JitStress, area-CodeGen-coreclr
