### ISSUE TITLE
MAX_CONNECTION_STRING_LENGTH = 1024 too short for Azure OAuth Token 

### ISSUE THREAD

**Issue by RichardSchulte** [dotnet/runtime#64940] opened 2022-02-07 21:05 UTC
### Description

ODBC Connection String length of 1024 cannot handle Azure OAuth tokens  

We generate a Azure OAuth Token at run time (expires 1 hour ) for scheduling and the value is passed to the ODBC connection. OAuth Token length is 1650 and connection fails as the ODBC Connection string only handles 1024. Because of this limitation we are struggling for an alternate solutions. I believe this limitation only exist on ODBC and not in OleDb and .Net

Is it possible to change 1024 to a larger value i.e. +2048 ?  I've looked a the Solution Code and there are only a few references to 1024     
    

### Reproduction Steps

just copy this into you connection string  - it will fail

DSN=TEST;authenticator=oauth;TOKEN=AiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik1yNS1BVWliZkJpaTdOZDFqQmViYXhib1hXMCIsImtpZCI6Ik1yNS1BVWliZkJpaTdOZDFqQmViYXhib1hXMCJ9.eyJhdWQiOiI1YTMzOWY4Mi0yMjZkLTQ0MmMtYjBjNi03YzYxNzZlMGM3ZjEiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC82YzdlYzU3NC01OTA0LTRkNDktYmQxOC02YWIzZDQzMmFkMmQvIiwiaWF0IjoxNjQzNjQ4NTYyLCJuYmYiOjE2NDM2NDg1NjIsImV4cCI6MTY0MzY1MzIyNSwiYWNyIjoiMSIsImFpbyI6IkFUUUF5LzhUQUFBQURrOHltTk9vVXhUZWhYSHpXTmxDVGVjbU1KaHZkTERtczZxK01FN2RwRHVOeERRMFBsMnRERHltWVczVkkxQVYiLCJhbXIiOlsicHdkIl0sImFwcGlkIjoiYTYyZTdmOW0YTQ0LTljY2ItZDYyY2ZhYTY2Y2M1Iiwib25wcmVtX3NpZCI6IlMtMS01LTIxLTg2MTU2NzUwMS0xNTQ3MTYxNjQyLTE4MDE2NzQ1MzEtMzEwMjA4IiwicmgiOiIwLkFSTUFkTVYtYkFSWlNVMjlHR3F6MURLdExaeF9McWJfczBGTHJSeE5EZ2FRVjVFVEFEUS4iLCJzY3AiOiJzZXNzaW9uOnJvbGUtYW55Iiwic3ViIjoiaTA5a3ROTkhmNXhZUWpjVVdRN2VxWXhJWFotT1BLNFA4ZE8wTHppeVN0YyIsInRpZCI6IjZjN2VjNTc0LTU5MDQtNGQ0OS1iZDE4LTZhYjNkNDMyYWQyZCIsInVuaXF1ZV9uYW1lIjoiUmljaGFyZF9KX1NjaHVsdGVAUHJvZ3Jlc3NpdmUuY29tIiwidXBuIjoiUmljaGFyZF9KX1NjaHVsdGVAUHJvZ3Jlc3NpdmUuY29tIiwidXRpIjoiQktXV1hmeEViazY1dWdrbTYxLWJBQSIsInZlciI6IjEuMCIsImN1aWQiOiJBMDgzMjA2In0.tmNUwXic_xcYu3vYEOMX6-dKf0f2gozkjmoeXeyCrfHvxeG7BA7MAYWWu__2-zgo8KnFtsDpQaEZaSkNa3tIPgo_YAYb-o6utWykfF_Crv3m7I2rkCqiCAoq2niCJ0iYNz4Bzy8gVkzSf13KjxaxCrAe5CaYFbw_rNETjBsMnCKQMufJybYLz-hXu68lWihIkoQIlxUeh9DcSnK64R0kSQe3dgyrciRWFoVrHVlvd2mq_itOtZgiwe7r_PEU_msgxw2US8UynUNcV1BynCc4g2XcygCOHGS_X1rfL3esws23VI2L0PP45RzGvPL7i0

### Expected behavior

ODBC connection accept a long TOKEN for Azure Authetication 

### Actual behavior

Connection string exceeds maximum allowed length of 1024.

### Regression?

yes I tried old and new releases  

### Known Workarounds

We have no workaround with ODBC - putting it in the DSN is not an option as the TOKEN only last 1 hour and need to be generated at runtime 

### Configuration

I just tested with the latest .Net Core 6. and  the latest System.Data.Odbc  6.0
used .Net framework 4X for most of my testing

Win 10 /Win server 2019 etc

both x64 & x32 

issue is related to a value = 1024 in the code 

### Other information

This would be huge if we can expand the length!

**Comment by RichardSchulte** [comment] 2022-02-07 22:19
This issue is for System.Data.Odbc please add a label for them

**Comment by Wraith2** [comment] 2022-02-08 02:31
area owner is @ajcvickers

**Comment by roji** [comment] 2022-02-08 08:15
Duplicate of #63630

**Comment by roji** [comment] 2022-02-08 08:16
@RichardSchulte may I ask which exact Azure database service you're connecting to? We've received reports of this happening for Databricks (#63630), but we'd like to know if there are other services where this is affecting users.

**Comment by RichardSchulte** [comment] 2022-02-08 13:09
This is for Snowflake

**Comment by RichardSchulte** [comment] 2022-02-08 16:54
Thank you for Responding! 

Most reporting and analytic tools use ODBC as primary/only way to connect to a data sources. Every data source has a ODBC driver. Very few can use .Net provider. We see OAuth becoming more prevalent as more data moves to the cloud. 

Yes Snowflake has a .Net Driver which I use. However the .Net driver has limitations as it cannot integrate it with our tools.  As an example I cannot get SSIS to recognize the Snowflake .Net Driver. There is no installer and manually trying to configure it (machine & SSIS config) didn't not work. Documentation to do this does not exist(?)  Reverting back to ODBC, SSIS uses System.Data.Odbc and our OAuth Token fails.

**Comment by am11** [comment] 2022-02-08 19:12
The following code comment suggests that the length validation is not 100% accurate for all cases (there is a tricky workaround to get by it): https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Data.Odbc/src/System/Data/Odbc/OdbcConnectionString.cs#L27
Deleting this whole conditional block (L25-L32) might break someone relying on this validation from an unreliable source, in theory, but risk of real world breakage due to its removal seems pretty low.

**Comment by RichardSchulte** [comment] 2022-02-08 19:54
Wow, that's very interesting could you make that change in a System.Data.Odbc.dll that I could quickly test?

**Comment by RichardSchulte** [comment] 2022-02-10 15:27
is that possible a dll to test?

**Comment by roji** [comment] 2022-05-23 08:58
Closing as duplicate of #63630

**Closed by roji** 2022-05-23 08:58 UTC
Labels: area-System.Data.Odbc, duplicate
