### ISSUE TITLE
JIT: Assertion failed '!m_VariableLiveRanges->back().m_EndEmitLocation.Valid()' when compiling SSE heavy code targeting ARM64

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#58861] opened 2021-09-09 10:07 UTC
#57752 fixed one assert like this, but @davidwrighton identified another: https://github.com/dotnet/runtime/issues/57752#issuecomment-910769048

The issue looks to be the same as a previous one: https://github.com/dotnet/runtime/pull/38894#issuecomment-655199226
It happens while compiling this function when targeting ARM64:
https://github.com/dotnet/runtime/blob/243ce20d10a64cc1e2d4fe3bac1a4ac827a52f5f/src/libraries/System.Private.CoreLib/src/System/Numerics/Matrix4x4.cs#L1389

It seems crossgen2 is compiling the function targeting ARM64 but `Sse.IsSupported` is not reported as false, which probably makes this test case a stress test for the ABI more than anything, so I think the impact is low because of this. Marking it as .NET 7.0 for now, @davidwrighton feel free to set this to .NET 6 if you think the impact is higher.

category:correctness
theme:liveness

**Comment by kunalspathak** [comment] 2022-07-19 00:20
Moving to .NET 8

**Comment by BrianBohe** [comment] 2022-12-14 18:12
I think this might be solved. How do you reproduce it?

I was trying to crossgen private corelib with `--print-repro-instructions ` on a windows x64 checked build but it seemed that `SseImpl` is not getting crossgen2ed. Then try to crossgen private corelib `--targetarch ARM64` but failed, although it is not hitting the assert. The full command is:
`.\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\crossgen2\crossgen2.exe --jitpath .\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\clrjit.dll --reference .\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\*.dll --out prueba.ni.dll --optimize .\artifacts\tests\coreclr\windows.x64.Checked\Tests\Core_Root\System.Private.Xml.dll --parallelism 1 --print-repro-instructions --targetarch ARM64`

And the stack trace looks like this:
```
To repro, add following arguments to the command line:
--singlemethodtypename "MS.Internal.Xml.XPath.AbsoluteQuery,System.Private.Xml" --singlemethodname "Evaluate" --singlemethodindex 1
Unhandled exception. ILCompiler.CodeGenerationFailedException: Code generation failed for method '[S.P.Xml]MS.Internal.Xml.XPath.AbsoluteQuery.Evaluate(XPathNodeIterator)'
   at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(IMethodNode methodCodeNodeNeedingCode, MethodIL methodIL) in C:\runtimes\runtime3\src\coreclr\tools\Common\JitInterface\CorInfoImpl.cs:line 411
   at Internal.JitInterface.CorInfoImpl.CompileMethod(MethodWithGCInfo methodCodeNodeNeedingCode, Logger logger) in C:\runtimes\runtime3\src\coreclr\tools\aot\ILCompiler.ReadyToRun\JitInterface\CorInfoImpl.ReadyToRun.cs:line 659
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass46_0.<ComputeDependencyNodeDependencies>g__CompileOneMethod|5(DependencyNodeCore`1 dependency, Int32 compileThreadId) in C:\runtimes\runtime3\src\coreclr\tools\aot\ILCompiler.ReadyToRun\Compiler\ReadyToRunCodegenCompilation.cs:line 841
   at ILCompiler.ReadyToRunCodegenCompilation.<>c__DisplayClass46_0.<ComputeDependencyNodeDependencies>g__CompileMethodList|2(IEnumerable`1 methodList) in C:\runtimes\runtime3\src\coreclr\tools\aot\ILCompiler.ReadyToRun\Compiler\ReadyToRunCodegenCompilation.cs:line 717
   at ILCompiler.ReadyToRunCodegenCompilation.ComputeDependencyNodeDependencies(List`1 obj) in C:\runtimes\runtime3\src\coreclr\tools\aot\ILCompiler.ReadyToRun\Compiler\ReadyToRunCodegenCompilation.cs:line 659
   at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeDependencies(List`1 deferredStaticDependencies) in C:\runtimes\runtime3\src\coreclr\tools\aot\ILCompiler.DependencyAnalysisFramework\DependencyAnalyzer.cs:line 177
   at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes() in C:\runtimes\runtime3\src\coreclr\tools\aot\ILCompiler.DependencyAnalysisFramework\DependencyAnalyzer.cs:line 316
...
```

**Comment by jakobbotsch** [comment] 2022-12-14 22:27
@BrianBohe You take the crossgen2 command used for crossgenning System.Private.CoreLib (output whenever you `build.cmd clr`) and replace x64 with arm64:
```powershell
❯ C:\dev\dotnet\runtime\dotnet.cmd C:\dev\dotnet\runtime\artifacts\bin\coreclr\windows.x64.Checked\crossgen2\crossgen2.dll -o:C:\dev\dotnet\runtime\artifacts\bin\coreclr\windows.x64.Checked\System.Private.CoreLib.dll -r:C:\dev\dotnet\runtime\artifacts\bin\coreclr\windows.x64.Checked\IL\*.dll --targetarch:arm64 -m:C:\dev\dotnet\runtime\artifacts\bin\coreclr\windows.x64.Checked\StandardOptimizationData.mibc --embed-pgo-data -O --verify-type-and-field-layout C:\dev\dotnet\runtime\artifacts\bin\coreclr\windows.x64.Checked\IL\System.Private.CoreLib.dll --pdb --pdb-path:C:\dev\dotnet\runtime\artifacts\bin\coreclr\windows.x64.Checked\PDB
C:\Program Files\dotnet
C:\dev\dotnet\runtime\src\coreclr\jit\codegencommon.cpp:8800
Assertion failed '!m_VariableLiveRanges->back().m_EndEmitLocation.Valid()' in 'System.Numerics.Matrix4x4:<Invert>g__SseImpl|68_0(System.Numerics.Matrix4x4,byref):bool' during 'Generate code' (IL size 1464; hash 0xb8fd39db; FullOpts)
```

**Comment by BrianBohe** [comment] 2022-12-16 20:36
The dump with the assert ends like this:
```
Generating: N3239 (  1,  1) [000860] ----------Z                  t860 =    LCL_VAR   simd16<System.Runtime.Intrinsics.Vector128`1> V21 loc19        u:3 d9 (last use) REG d9 $56a
Generating: N001 (  1,  1) [007597] -----------                 t7597 =    LCL_VAR   simd16<System.Runtime.Intrinsics.Vector128`1> V21 loc19         d9 REG d9
                                                                        /--*  t7597  simd16 
Generating: N002 (  2,  2) [007598] ----------z                 t7598 = *  SIMD      simd16 float UpperRestore Internal REG d16
IN0709:                           ldr     d16, [fp, #0x178]	// [V21 loc19+0x08]
IN070a:                           mov     v9.d[1], v16.d[0]
                                                                        /--*  t860   simd16 
Generating: N3241 (???,???) [005725] -----------                 t5725 = *  PUTARG_REG simd16 REG d0
							V21 in reg d9 is becoming dead  [000860]
							Live regs: F80000 {x19 x20 x21 x22 x23 d8 d9 d12 d13} => F80000 {x19 x20 x21 x22 x23 d8 d12 d13}
							Live vars: {V01 V02 V21 V22 V23 V24 V26 V27 V28 V364 V365 V366 V367} => {V01 V02 V22 V23 V24 V26 V27 V28 V364 V365 V366 V367}
Closing debug range.
IN070b:                           str     q9, [fp, #0x170]	// [V21 loc19]
							V21 in reg d9 is becoming dead  [000860]
							Live regs: (unchanged) F80000 {x19 x20 x21 x22 x23 d8 d12 d13}
C:\runtimes\runtime3\src\coreclr\jit\codegencommon.cpp:8800
Assertion failed '!m_VariableLiveRanges->back().m_EndEmitLocation.Valid()' in 'System.Numerics.Matrix4x4:<Invert>g__SseImpl|68_0(System.Numerics.Matrix4x4,byref):bool' during 'Generate code' (IL size 1464; hash 0xb8fd39db; FullOpts)
```

Generating code for 005725, the operand 000860 is consumed first. genProduceReg first calls to [genUpdateLife](https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/codegenlinear.cpp#L1512-L1513), which triggers the closing live range in [UpdateLifeVar](https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/treelifeupdater.cpp#L411), but a few lines below [in UpdateLifeVar also](https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/treelifeupdater.cpp#L423), the variable is being spilled and then an update on its liverange occurs, which tries to close the existing live range and open a new one from stack.

Seems to me like we should not update the live range on spill if it is dying.

**Comment by jakobbotsch** [comment] 2022-12-16 20:41
@BrianBohe you may want to read the comment I linked above, Andy posted an investigation of the issue already and it looks like there's a bit more to it.

**Comment by BrianBohe** [comment] 2022-12-26 15:33
> @BrianBohe you may want to read the comment I linked above ([#38894 (comment)](https://github.com/dotnet/runtime/pull/38894#issuecomment-655669351)), Andy posted an investigation of the issue already and it looks like there's a bit more to it.

Yes, it seems we have to deal with the scenario where the upper and lower part of a variable value may be moved separately (while being manipulated), which has never been taken into account.

**Comment by kunalspathak** [comment] 2023-06-05 18:23
I don't seem to repro this when running the following command.

`D:\git\runtime\src\coreclr\jit>D:\git\runtime\dotnet.cmd D:\git\runtime\artifacts\bin\coreclr\windows.x64.Checked\crossgen2\crossgen2.dll -o:D:\git\runtime\artifacts\bin\coreclr\windows.x64.Checked\System.Private.CoreLib.dll -r:D:\git\runtime\artifacts\bin\coreclr\windows.x64.Checked\IL\*.dll --targetarch:arm64 --targetos:windows -m:D:\git\runtime\artifacts\bin\coreclr\windows.x64.Checked\StandardOptimizationData.mibc --embed-pgo-data -O --verify-type-and-field-layout D:\git\runtime\artifacts\bin\coreclr\windows.x64.Checked\IL\System.Private.CoreLib.dll --pdb --pdb-path:D:\git\runtime\artifacts\bin\coreclr\windows.x64.Checked\PDB`

**Closed by kunalspathak** 2023-06-05 18:23 UTC
Labels: area-CodeGen-coreclr
