### ISSUE TITLE
Finding Microsoft.Extensions.Hosting service provider with using IDesignTimeDbContextFactory

### ISSUE THREAD

**Issue by kostazol** [dotnet/runtime#88485] opened 2023-07-06 18:39 UTC
### Description

Why EF Core Finding Microsoft.Extensions.Hosting service provider, where I using IDesignTimeDbContextFactory for working with migrations?  Migrations works, but I have warnings...

### Reproduction Steps

Run somesing on start up. I try to call gRPC service.

### Expected behavior

Apply migrations without warnings.

### Actual behavior

Apply migrations with warnings.

### Configuration

Windows 10 x64, NET7, EF Core tools 7.0.8

### Other information

```
dotnet ef database update -v --project Inventory\Inventory.csproj --
startup-project Inventory\Inventory.csproj --context Inventory.DataAccess.InventoryContext

Using project 'C:\Inventory\Inventory.csproj'.
Using startup project 'C:\Inventory\Inventory.csproj'.
Writing 'C:\Inventory\obj\Inventory.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\user\AppData\Local\Temp\tmp1B9B.tmp /verbosity:quiet /nologo
C:\Inventory\Inventory.csproj
Writing 'C:\Inventory\obj\Inventory.csproj.EntityFrameworkCore.targets'...
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=C:\Users\user\AppData\Local\Temp\tmp1DAF.tmp /verbosity:quiet /nologo
C:\Inventory\Inventory.csproj
Build started...
dotnet build C:\Inventory\Inventory.csproj /verbosity:quiet /nologo

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:10.09
Build succeeded.
dotnet exec --depsfile C:\Inventory\bin\Debug\net7.0\Inventory.deps.json --
additionalprobingpath C:\Users\user\.nuget\packages --runtimeconfig C:\Invent
ory\bin\Debug\net7.0\Inventory.runtimeconfig.json C:\Users\user\.dotnet\tools\.store\dotnet-ef\7.0.8\dotnet-ef\7.0.8\tools\net6.0\any\tools\ne
tcoreapp2.0\any\ef.dll database update --context Inventory.DataAccess.InventoryContext --assembly C:\Users\user\Documents\1_git_repositories\m
arketplace-backend-v2\Inventory\bin\Debug\net7.0\Inventory.dll --project C:
\Inventory\Inventory.csproj --startup-assembly C:\Inventory\bin\Debug\n
et7.0\Inventory.dll --startup-project C:\Inventory\Inventory.csproj --p
roject-dir C:\Inventory\ --root-namespace Inventory --language C# --framewo
rk net7.0 --nullable --working-dir C: --verbose
Using assembly 'Inventory'.
Using startup assembly 'Inventory'.
Using application base 'C:\Inventory\bin\Debug\net7.0'.
Using working directory 'C:\Inventory'.
Using root namespace 'Inventory'.
Using project directory 'C:\Inventory\'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Found IDesignTimeDbContextFactory implementation 'InventoryContextFactory'.
Found DbContext 'InventoryContext'.
Finding application service provider in assembly 'Inventory'...
Finding Microsoft.Extensions.Hosting service provider...
Using environment 'Development'.
Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="Error connecting to subchannel.", DebugException="System.Net.Sockets.SocketExceptio
n: No connection could be made because the target machine actively refused it.")
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, Can
cellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport.TryConnectAsync(ConnectContext context)
   --- End of inner exception stack trace ---
   at Grpc.Net.Client.Balancer.Internal.ConnectionManager.PickAsync(PickContext context, Boolean waitForReady, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)
   at Grpc.Net.Client.Internal.Retry.RetryCallBase`2.GetResponseAsync()
   at Grpc.Net.Client.Internal.HttpClientCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TReque
st request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, Client
InterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TReque
st request)
   at Mdm.ReferencesService.ReferencesServiceClient.AddReference(AddReferenceRequest request, CallOptions options) in C:\Mdm\obj\Debug\net7.0\ram\mdm\ReferencesGrpc.cs:line 305
   at Mdm.ReferencesService.ReferencesServiceClient.AddReference(AddReferenceRequest request, Metadata headers, Nullable`1 deadline, Cancellatio
nToken cancellationToken) in C:\Mdm\obj\Debug\net7.0\ram\mdm\ReferencesGrpc.cs:
line 294
   at Mdm.AddReferencesExtension.AddReferences(IServiceCollection services, ReferencesServiceClient client, Assembly[] assemblies) in C:\Mdm\AddReferencesExtension.cs:line 146
   at Program.<Main>$(String[] args) in C:\Inventory\Program.cs:line 203
   at Program.<Main>(String[] args)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.CreateHost()
   at Microsoft.Extensions.Hosting.HostFactoryResolver.<>c__DisplayClass10_0.<ResolveHostFactory>b__0(String[] args)
   at Microsoft.Extensions.Hosting.HostFactoryResolver.<>c__DisplayClass13_0.<ResolveServiceProviderFactory>b__3(String[] args)
   at Microsoft.EntityFrameworkCore.Design.Internal.AppServiceProviderFactory.CreateFromHosting(String[] args)
An error occurred while accessing the Microsoft.Extensions.Hosting services. Continuing without the application service provider. Error: Status(Stat
usCode="Unavailable", Detail="Error connecting to subchannel.", DebugException="System.Net.Sockets.SocketException: No connection could be made beca
use the target machine actively refused it.")
No application service provider was found.
Finding DbContext classes in the project...
Using DbContext factory 'InventoryContextFactory'.
Using context 'InventoryContext'.
Finding design-time services referenced by assembly 'Inventory'...
Finding design-time services referenced by assembly 'Inventory'...
No referenced design-time services were found.
Finding design-time services for provider 'Npgsql.EntityFrameworkCore.PostgreSQL'...
Using design-time services from provider 'Npgsql.EntityFrameworkCore.PostgreSQL'.
Finding IDesignTimeServices implementations in assembly 'Inventory'...
Using design-time services from class 'MyDesignTimeServices'.
Creating DbConnection.
Created DbConnection. (25ms).
Migrating using database 'ram_inventory' on server ''.
Opening connection to database 'ram_inventory' on server ''.
Opened connection to database 'ram_inventory' on server 'tcp://dev-ser.test.com:5432'.
Closing connection to database 'ram_inventory' on server 'tcp://dev-ser.test.com:5432'.
Closed connection to database 'ram_inventory' on server '' (3ms).
Creating DbCommand for 'ExecuteScalar'.
Created DbCommand for 'ExecuteScalar' (2ms).
Initialized DbCommand for 'ExecuteScalar' (5ms).
Opening connection to database 'ram_inventory' on server ''.
Opened connection to database 'ram_inventory' on server 'tcp://dev-ser.test.com:5432'.
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT EXISTS (SELECT 1 FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='v2' AND c.relname='_Migra
tion');
Executed DbCommand (70ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT EXISTS (SELECT 1 FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='v2' AND c.relname='_Migra
tion');
Closing connection to database 'ram_inventory' on server 'tcp://dev-ser.test.com:5432'.
Closed connection to database 'ram_inventory' on server '' (0ms).
Opening connection to database 'ram_inventory' on server ''.
Opened connection to database 'ram_inventory' on server 'tcp://dev-ser.test.com:5432'.
Closing connection to database 'ram_inventory' on server 'tcp://dev-ser.test.com:5432'.
Closed connection to database 'ram_inventory' on server '' (0ms).
Creating DbCommand for 'ExecuteScalar'.
Created DbCommand for 'ExecuteScalar' (0ms).
Initialized DbCommand for 'ExecuteScalar' (0ms).
Opening connection to database 'ram_inventory' on server ''.
Opened connection to database 'ram_inventory' on server 'tcp://dev-ser.test.com:5432'.
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT EXISTS (SELECT 1 FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='v2' AND c.relname='_Migra
tion');
Executed DbCommand (55ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT EXISTS (SELECT 1 FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='v2' AND c.relname='_Migra
tion');
Closing connection to database 'ram_inventory' on server 'tcp://dev-ser.test.com:5432'.
Closed connection to database 'ram_inventory' on server '' (0ms).
Creating DbCommand for 'ExecuteReader'.
Created DbCommand for 'ExecuteReader' (0ms).
Initialized DbCommand for 'ExecuteReader' (0ms).
Opening connection to database 'ram_inventory' on server ''.
Opened connection to database 'ram_inventory' on server 'tcp://dev-ser.test.com:5432'.
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT "MigrationId", "ProductVersion"
FROM v2."_Migration"
ORDER BY "MigrationId";
Executed DbCommand (56ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT "MigrationId", "ProductVersion"
FROM v2."_Migration"
ORDER BY "MigrationId";
Closing data reader to 'ram_inventory' on server 'tcp://dev-ser.test.com:5432'.
A data reader for 'ram_inventory' on server 'tcp://dev-ser.test.com:5432' is being disposed after spending 4ms reading results.
Closing connection to database 'ram_inventory' on server 'tcp://dev-ser.test.com:5432'.
Closed connection to database 'ram_inventory' on server '' (0ms).
No migrations were applied. The database is already up to date.
'InventoryContext' disposed.
Disposing connection to database 'ram_inventory' on server ''.
Disposed connection to database 'ram_inventory' on server '' (0ms).
Done.
```

**Comment by SamMonoRT** [comment] 2024-06-21 14:07
@AndriySvyryd - this seems Migrations related. Moving to your queue, and adding 9.0 milestone. Lets triage this in a few weeks.

**Comment by AndriySvyryd** [comment] 2024-06-21 20:39
Duplicate of https://github.com/dotnet/efcore/issues/27322

**Closed by AndriySvyryd** 2024-06-21 20:39 UTC
Labels: area-System.Data
