### ISSUE TITLE
Performance regressions on EF scenarios

### ISSUE THREAD

**Issue by sebastienros** [dotnet/runtime#36292] opened 2020-05-12 14:45 UTC
Most probably due to threadpool/epoll changes on the same commit.

https://github.com/dotnet/aspnetcore/issues/21593
https://github.com/dotnet/aspnetcore/issues/21596
https://github.com/dotnet/aspnetcore/issues/21634
https://github.com/dotnet/aspnetcore/issues/21640
https://github.com/dotnet/aspnetcore/issues/21650
https://github.com/dotnet/aspnetcore/issues/21688

The lines that are up are either ADO.NET or Dapper. The ones that are down are EF.

![image](https://user-images.githubusercontent.com/1165805/81705953-791e8c00-9424-11ea-925c-890fc2ef0468.png)

/cc @adamsitnik @roji

**Comment by danmosemsft** [comment] 2020-05-12 17:59
@kouvel @adamsitnik

**Comment by davidfowl** [comment] 2020-05-12 18:01
@sebastienros didn't you say it was from @adamsitnik 's change (single epoll thread?). We have diffs to show what changes affect the graph right?

**Comment by stephentoub** [comment] 2020-05-12 18:01
EF looks like it went up for a day or two and then went back down to what it was.  Were the few measurements showing a temporary increase legit?  Just making sure.

**Comment by sebastienros** [comment] 2020-05-12 18:55
Here are the actual runtime versions that regressed, and links to commits. I can't more precise that that as it's based on the availble successful runtiem builds.

Scenario: DbFortunesEF

`5.0.0-preview.5.20253.4` 154K RPS
`5.0.0-preview.5.20253.5` 170K RPS
https://github.com/dotnet/runtime/compare/82eff518113a7c38064aa20bfe2fb8f81641f323...2d29378067acfb4b4607d22f527838076863293e (contains @kouvel 's changes)


`5.0.0-preview.5.20253.7` 166K RPS
`5.0.0-preview.5.20257.11` 151K RPS
https://github.com/dotnet/runtime/compare/8527a991b91cabc9bec6f6abe57a52b5bb5e154d...93344266685c75ebcd293f171b3033432909a60a (contains @adamsitnik 's changes)

Command line:

```
dotnet run -- --server http://asp-citrine-lin:5001 --client http://asp-citrine-load:5002 -j ..\Benchmarks\benchmarks.html.json -n DbFortunesEF --database PostgresQL --warmup 15 --duration 30 --self-contained --aspnetcoreversion 5.0.0-preview.5.20253.1 --runtimeversion 5.0.0-preview.5.20257.11 
```

Pinned ASP.NET version across runs.
To collect traces add `--collect-trace`.
Change the runtime version accordingly.

**Comment by mangod9** [comment] 2020-07-06 17:19
Moving to sockets area, since this is related to epoll changes.

**Comment by scalablecory** [comment] 2020-07-07 19:52
Triage: worth an investigation. @antonfirsov @adamsitnik can you help here?

**Comment by adamsitnik** [comment] 2020-08-04 13:22
From the numbers provided here, it looks like https://github.com/dotnet/runtime/pull/35330 has improved the performance compared to 3.1 and https://github.com/dotnet/runtime/pull/35800 has brought it back to the previous level (for these particular benchmarks). The goal of the first PR was to allow us to switch to a single epoll thread (second PR), which gave us BIG wins in all platform benchmarks. I would say that it was an unplanned improvement which was simply reverted by the other PR that gave us very important wins elsewhere.

@sebastienros Do we have a `.yml` config file for these benchmarks so I could run them with Driver2 and compare 3.1 vs 5.0?

I am going to set it to the future for now (it does not look like a regression compared to previous release)

**Comment by geoffkizer** [comment] 2020-08-04 14:34
I think pushing this out is fine.

That said, while the issue is still fresh in our minds, any ideas what might have caused this @adamsitnik?

**Comment by sebastienros** [comment] 2020-08-04 14:43
@adamsitnik https://github.com/aspnet/Benchmarks/tree/master/scenarios#database-benchmarks

Use the crank cli now

**Comment by adamsitnik** [comment] 2020-08-04 15:59
@sebastienros thanks for the link, it was exactly what I needed!

I've run the benchmarks for 3.1.5 vs 5.0 using perf machine (12 cores, close to real life scenarios) and Citrine (TechEmpower, 28 cores):

Machine | Benchmark | 3.1 | 5.0 | "(5.0/3.1) - 1"
-- | -- | -- | -- | --
perf | fortunes (ADO.NET) | 97,615 | 110,035 | +12.72%
  | fortunes_ef (EF) | 67,787 | 70,534 | +4.05%
citrine | fortunes (ADO.NET) | 233,312 | 266,329 | +14.15%
  | fortunes_ef (EF) | 151,918 | 145,658 | -4.12%

 there are improvements for ADO.NET and one regression for EF for a machine with a high number of cores

> any ideas what might have caused this

@geoffkizer If ADO.NET did not improve, I would say that we can't keep the ThreadPool busy with a single epoll thread. But since only EF has regressed for a machine with a high number of cores I **guess** that something which was not a bottleneck so far, became a bottleneck (lock contention?). We need to run a full investigation to find out (and hopefully change something in EF).

**Comment by wfurt** [comment] 2022-12-15 16:59
triage: this was open for 5.0 and all the linked issues are closed. Not clear if this is really actionable. We should investigate perf improvements separately.

**Closed by wfurt** 2022-12-15 16:59 UTC
Labels: area-System.Net.Sockets, tenet-performance
