### ISSUE TITLE
Microsoft.Extensions.Hosting 6 incorrectly resolves multiple instances of the same service type

### ISSUE THREAD

**Issue by cfbao** [dotnet/runtime#55407] opened 2021-07-09 16:08 UTC
### Description

minimal repro repo: https://github.com/cfbao/net6-host-di-bug-repro

* set up a worker app using generic host
* use version 6.0.0-preview.5.21301.5 of Microsoft.Extensions.Hosting
* make a dummy service
```csharp
public class Dummy {
	public int Id { get; }
	public Dummy( int id ) => Id = id;
}
```
* register this dummy service multiple times in DI using different IDs
```csharp
Host.CreateDefaultBuilder( args )
	.ConfigureServices( ( hostContext, services ) => {
		foreach( int i in Enumerable.Range( 0, 10 ) ) {
			services.AddSingleton<Dummy>( new Dummy( id: i ) );
		}
		services.AddHostedService<Worker>();
	} );
```
* request all these services from DI, and log their ids
```csharp
public class Worker : BackgroundService {
	private readonly IEnumerable<Dummy> _dummies;
	private readonly ILogger<Worker> _logger;

	public Worker( IEnumerable<Dummy> dummies, ILogger<Worker> logger ) {
		_dummies = dummies;
		_logger = logger;
	}

	protected override async Task ExecuteAsync( CancellationToken stoppingToken ) {
		while( !stoppingToken.IsCancellationRequested ) {
			_logger.LogInformation( string.Join( ", ", _dummies.Select( d => d.Id ) ) );
			try {
				await Task.Delay( TimeSpan.FromSeconds( 1 ), stoppingToken );
			} catch( OperationCanceledException ) {
				return;
			}
		}
	}
}
```
* run the app using `dotnet run`, and see this
```
info: Net6HostDIBugRepro.Worker[0]
      0, 4, 5, 6, 7, 8, 9, 7, 8, 9
```
but it should be
```
info: Net6HostDIBugRepro.Worker[0]
      0, 1, 2, 3, 4, 5, 6, 7, 8, 9
```

Note: this bug only occurs when using `dotnet run` (or start debug from VS), but it doesn't occur when running the published executable.

### Configuration

.NET SDK
 Version:   6.0.100-preview.5.21302.13
 Commit:    d6380bcae7

.NET runtimes: 5.0.7 &  6.0.0-preview.5.21301.5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64

Host (useful for support):
  Version: 6.0.0-preview.5.21301.5
  Commit:  ec3e0b276b

### Regression?

Yes. Using Microsoft.Extensions.Hosting 5.0.0 (even when running on .NET 6) doesn't have this bug.

**Comment by cfbao** [comment] 2021-07-09 16:30
BTW, this bug also impacts any ASP.NET Core 6 projects, and AFAICS there's no easy workaround there.

**Comment by davidfowl** [comment] 2021-07-09 17:24
Dupe of https://github.com/dotnet/runtime/issues/54407 and yes there's an easy work around.

**Closed by davidfowl** 2021-07-09 17:24 UTC
Labels: area-Extensions-Hosting, untriaged
