### ISSUE TITLE
Test failure System.IO.Tests.NamedPipeFileStreamConnectedConformanceTests.ReadWrite_Success_Large

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#65475] opened 2022-02-17 01:09 UTC
Run: [runtime-libraries-coreclr outerloop 20220216.5](https://dev.azure.com/dnceng/public/_build/results?buildId=1615839&view=ms.vss-test-web.build-test-results-tab&runId=44964300&paneView=debug&resultId=102976)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_release-Windows.Amd64.Server2022.Open

- System.IO.Tests.NamedPipeFileStreamConnectedConformanceTests.ReadWrite_Success_Large(mode: SyncSpan, writeSize: 10485760, startWithFlush: True)
- System.IO.Tests.AnonymousPipeFileStreamConnectedConformanceTests.ReadWrite_Success_Large(mode: AsyncMemory, writeSize: 10485760, startWithFlush: False)
- System.IO.Tests.UnidirectionalConnectedStreamsTests.ReadWrite_Success_Large(mode: AsyncAPM, writeSize: 10485760, startWithFlush: False)
```
**Error message:**
```
Showing first 10 differences
Total number of differences: 0 out of 10485760


Stack trace
   at System.AssertExtensions.SequenceEqual[T](ReadOnlySpan`1 expected, ReadOnlySpan`1 actual) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 473
   at System.IO.Tests.ConnectedStreamConformanceTests.ReadWrite_Success(ReadWriteMode mode, Int32 writeSize, Boolean startWithFlush) in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 1765
   at System.IO.Tests.ConnectedStreamConformanceTests.ReadWrite_Success_Large(ReadWriteMode mode, Int32 writeSize, Boolean startWithFlush) in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 1719
--- End of stack trace from previous location ---
```

**Comment by adamsitnik** [comment] 2022-02-17 09:18
Duplicate of https://github.com/dotnet/runtime/issues/65292

**Closed by adamsitnik** 2022-02-17 09:18 UTC
Labels: arch-x86, area-System.IO, os-windows, untriaged, blocking-outerloop
