### ISSUE TITLE
DOTNET_ROLL_FORWARD=Major ignores in new builds of .net 6 since preview 7

### ISSUE THREAD

**Issue by grinay** [dotnet/runtime#58837] opened 2021-09-05 09:50 UTC
Hi. I'm using the global environment variable DOTNET_ROLL_FORWARD=Major and I'm able to run .net 3,5 projects on my Mac machines with m1 CPU. But since preview 7 this variable seems to be ignored and I'm unable to run .net 3,5 projects with new versions. 
The version which I using currently dotnet-sdk-6.0.100-preview.6.21355.2-osx-arm64.pkg , but after update  to 
dotnet-sdk-6.0.100-rc.2.21454.3-osx-arm64 or dotnet-sdk-6.0.100-preview.7.21379.14-osx-arm64.pkg  project builds correct but it can't be run anymore and fails with error 

Failed to load /usr/local/share/dotnet/host/fxr/6.0.0-rc.2.21454.1/libhostfxr.dylib, error: dlopen(/usr/local/share/dotnet/host/fxr/6.0.0-rc.2.21454.1/libhostfxr.dylib, 1): no suitable image found.  Did find:
        /usr/local/share/dotnet/host/fxr/6.0.0-rc.2.21454.1/libhostfxr.dylib: mach-o, but wrong architecture
        /usr/local/share/dotnet/host/fxr/6.0.0-rc.2.21454.1/libhostfxr.dylib: mach-o, but wrong architecture
The library libhostfxr.dylib was found, but loading it from /usr/local/share/dotnet/host/fxr/6.0.0-rc.2.21454.1/libhostfxr.dylib failed
  - Installing .NET prerequisites might help resolve this problem.

**Comment by agocke** [comment] 2021-09-08 22:29
By "cannot be run" you mean, fails when you write `dotnet run`?

**Comment by vitek-karas** [comment] 2021-09-09 07:32
This is a dupe of https://github.com/dotnet/runtime/issues/58754.

**Closed by vitek-karas** 2021-09-09 07:32 UTC
Labels: area-Host, untriaged
