### ISSUE TITLE
ProcessName returns truncated 15 char string on MacOS

### ISSUE THREAD

**Issue by ldy985** [dotnet/runtime#69726] opened 2022-05-24 16:31 UTC
### Description

A simple application such as 
```
Process currentProcess = Process.GetCurrentProcess();
Console.WriteLine(currentProcess.ProcessName);
```
truncates the process name to be 15 char long string.

### Reproduction Steps

1. Create a simple console project on MacOS
2. Ensure the output executable name is longer than 15 characters.
3. Add the code from the description
4. Run the project

### Expected behavior

I would expect the full process name to be returned. Like the activity monitor on MacOS return.

### Actual behavior

A truncated version of the process name is returned. The name is truncated to 15 characters.

### Configuration

Tested on MacOS Catalina (10.15.7)

### Other information

See this issue that was reported long ago https://github.com/dotnet/runtime/issues/28346. A fix was only implemented for Linux.

**Comment by stephentoub** [comment] 2022-05-24 20:35
Duplicate of https://github.com/dotnet/runtime/issues/52860

**Closed** 2022-05-26 10:58 UTC
Labels: area-System.Diagnostics.Process, untriaged
