### ISSUE TITLE
Test failure: Dispose_WithPendingAcceptAndConnect_PendingAndSubsequentThrowOperationAbortedException

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#56875] opened 2021-08-04 22:42 UTC
Test: `System.Net.Quic.Tests.QuicConnectionTests_MsQuicProvider.Dispose_WithPendingAcceptAndConnect_PendingAndSubsequentThrowOperationAbortedException`

Day | Run | OS
-----|-----|-----
8/4 | PR #56719 | ubuntu.1604.amd64.open.rt
8/1 | PR #55353 | ubuntu.1604.amd64.open.rt
7/30 | PR #56531 | ubuntu.1604.amd64.open.rt

```
System.Net.Quic.QuicException : Connection has been shutdown by transport. Error Code: CONNECTION_REFUSED
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventShutdownInitiatedByTransport(State state, ConnectionEvent& connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicConnection.cs:line 248
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.NativeCallbackHandler(IntPtr connection, IntPtr context, ConnectionEvent& connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicConnection.cs:line 669
--- End of stack trace from previous location ---
   at System.Net.Quic.Tests.QuicTestBase`1.<>c__DisplayClass32_0.<<RunClientServer>b__1>d[[System.Net.Quic.Tests.MsQuicProviderFactory, System.Net.Quic.Functional.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].MoveNext() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 178
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 64
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 91
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 55
   at System.Net.Quic.Tests.QuicTestBase`1.<RunClientServer>d__32[[System.Net.Quic.Tests.MsQuicProviderFactory, System.Net.Quic.Functional.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].MoveNext() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 157
   at System.Net.Quic.Tests.QuicConnectionTests`1.<Dispose_WithPendingAcceptAndConnect_PendingAndSubsequentThrowOperationAbortedException>d__5[[System.Net.Quic.Tests.MsQuicProviderFactory, System.Net.Quic.Functional.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].MoveNext() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicConnectionTests.cs:line 102
--- End of stack trace from previous location ---
```

**Comment by wfurt** [comment] 2021-08-04 23:19
seems like symptoms of #55979. It feels like the test even did not start executing the test body.

**Comment by ManickaP** [comment] 2021-08-10 17:14
Triage: closing as a dupe, we can reopen if it turns out it isn't.
Duplicate of #55979

**Closed by ManickaP** 2021-08-10 17:14 UTC
Labels: test-run-core, area-System.Net.Quic

**Comment by karelz** [comment] 2021-08-13 09:35
Duplicate of #55979
