### ISSUE TITLE
Test failure System.Text.Json.SourceGeneration.Tests.ConstructorTests_Default_String.MultipleThreadsLooping

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#71520] opened 2022-07-01 06:22 UTC
Run: [runtime-libraries-coreclr outerloop 20220630.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1854457&view=ms.vss-test-web.build-test-results-tab&runId=48804506&resultId=102598&paneView=debug)

Failed test:
```
net7.0-Linux-Release-arm-CoreCLR_release-(Debian.11.Arm32.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-11-helix-arm32v7-20210304164347-5a7c380

- System.Text.Json.SourceGeneration.Tests.ConstructorTests_Default_String.MultipleThreadsLooping

```
**Error message:**
```
Assert.Equal() Failure
Expected: 11
Actual:   0


Stack trace
   at System.Text.Json.Serialization.Tests.ObjWCtorMixedParams.Verify() in /_/src/libraries/System.Text.Json/tests/Common/TestClasses/TestClasses.Constructor.cs:line 1068
   at System.Text.Json.Serialization.Tests.Parameterized_Class_With_ComplexTuple.Verify() in /_/src/libraries/System.Text.Json/tests/Common/TestClasses/TestClasses.Constructor.cs:line 1980
   at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__DeserializeObjectAsync|12_0(String json, Type type, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.Cache.cs:line 34
   at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__DeserializeObjectNormalAsync|12_3(Type type, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.Cache.cs:line 52
   at System.Text.Json.Serialization.Tests.ConstructorTests.<MultipleThreads>g__RunTestAsync|12_5(Type type) in /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.Cache.cs:line 81
   at System.Text.Json.Serialization.Tests.ConstructorTests.MultipleThreads() in /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.Cache.cs:line 86
   at System.Text.Json.Serialization.Tests.ConstructorTests.MultipleThreadsLooping() in /_/src/libraries/System.Text.Json/tests/Common/ConstructorTests/ConstructorTests.Cache.cs:line 20
--- End of stack trace from previous location ---
```

**Comment by karelz** [comment] 2022-07-22 14:08
Duplicate of #65418

**Closed by karelz** 2022-07-22 14:08 UTC
Labels: area-System.Text.Json, os-linux, untriaged, blocking-outerloop
