### ISSUE TITLE
C# 9 positional records - support for Microsoft.Extensions.Configuration.ConfigurationBinder

### ISSUE THREAD

**Issue by iSeiryu** [dotnet/runtime#46299] opened 2020-12-21 19:54 UTC
### Description

appsettings.json
```json
{
  "Azure": {
    "BaseUrl": "https://azure.com",
    "TenantId": "Id"
  }
}
```

record
```csharp
public sealed record AzureInfo(string BaseUrl, string TenantId);
```

Startup.cs
```csharp
var appInfo = configuration.GetSection("Azure").Get<AzureInfo>();
```

Getting exception
```shell
System.InvalidOperationException: Cannot create instance of type 'AzureInfo' because it is missing a public parameterless constructor.
   at Microsoft.Extensions.Configuration.ConfigurationBinder.CreateInstance(Type type)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Get(IConfiguration configuration, Type type, Action`1 configureOptions)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Get[T](IConfiguration configuration, Action`1 configureOptions)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Get[T](IConfiguration configuration)
```

### Configuration

mcr.microsoft.com/dotnet/sdk:latest

### Other information

The extension is located here: https://github.com/dotnet/runtime/blob/0fad9d646359c71f4d5e9443500fd9248ce10aa4/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs

### Workaround
If I change my record to this it works
```csharp
public sealed record AzureInfo {
    public string BaseUrl { get; init; }
    public string TenantId { get; init; }
}
```

**Comment by davidfowl** [comment] 2020-12-21 20:12
Dupe of https://github.com/dotnet/runtime/issues/43662

**Closed by davidfowl** 2020-12-21 20:12 UTC
Labels: area-Extensions-Configuration, untriaged
