### ISSUE TITLE
[API Proposal]: Vectorized BitArray.IsAnyBitSet

### ISSUE THREAD

**Issue by deiruch** [dotnet/runtime#80518] opened 2023-01-11 21:12 UTC
### Background and motivation

While using BitArray to implement an iterative algorithm, I wanted to see whether any bits were set in the `BitArray`. If no bits are set, I can stop the iterations. The code looks like this:

```cs
var bitArray = new BitArray(10000);
bitArray[5000] = true;
while(bitArray.Any()) //<--- using LINQ as work-around
{
    //modify bitArray contents here
    //...
}
```

This has the problem that the check is obviously not efficient, because it is not vectorized and tests each bit separately. Other users have asked for this as well (https://stackoverflow.com/questions/969435/how-check-bitarray-contains-any-true-or-any-false-value or https://stackoverflow.com/questions/35383280/fastest-way-to-check-c-sharp-bitarray-for-non-zero-value).

## Implementation
The implementation should obviously be vectorized, along the lines of
```cs
    public void IsAnyBitSet
    {
        get
        {
            int arrayLength = GetInt32ArrayLengthFromBitLength(Length);
            for (var i = 0; i < arrayLength; i++)
                if (m_array[i] != 0)
                    return true;

            return false;
        }
    }
```

Better implementations would include SIMD code paths for common CPUs. If you'd like I can prepare a PR.

### API Proposal

```diff
namespace System.Collections;

public sealed class BitArray : ICloneable, System.Collections.ICollection
{
    //...

+   public bool IsAnyBitSet { get; }

    //...
}
```

### API Usage

```cs
var bitArray = new BitArray(10000);
bitArray[5000] = true;

while(bitArray.IsAnyBitSet)
{
    //modify the bitarray with any algorithm
    bitArray[Random.Shared.Next(bitArray.Length)] = false;
}
```

or

```cs
var someObject = new BitArray(...);
var background = new BitArray(...);

if(someObject.And(background).IsAnyBitSet)
{
     //we have a collision!
}
else
{
    //there is no collision of object and background
}
```

### Alternative Designs

- LINQ could be improved to such a degree that `bitArray.Cast<bool>().Any()` is performant.
- Make `m_array` public, so users can add arbitrary vectorized operations on their own.
- Use `Equals` to compare to an all-zero BitArray.

### Risks

None, as far as I can think.

**Comment by stephentoub** [comment] 2023-01-11 21:15
This is a duplicate of https://github.com/dotnet/runtime/issues/72999. Thanks.

**Closed** 2023-01-11 21:15 UTC
Labels: api-suggestion, area-System.Collections, untriaged
