### ISSUE TITLE
-0.1.ToString(“0”) is “-0” in .NET Core and “0” in .NET Framework

### ISSUE THREAD

**Issue by nikolayDemirev** [dotnet/runtime#32458] opened 2020-02-17 16:20 UTC
.NET Core version is 3.1.200
Windows 10 Version 1803 Build 17134.1246
Visual Studio Pro 2019 Preview Version 16.5.0 Preview 2.0

--------------------------------------------------------------------------------------------------------------

```
(-0.1).ToString("0")
```
evaluates to "-0" in .NET Core and "0" in .NET Framework when value is double or float. On the other hand when value is decimal:

```
(-0.1M).ToString("0")
```
it evaluates to "0" in both frameworks.

**Comment by GrabYourPitchforks** [comment] 2020-02-17 23:59
@tannergooding Probably related to the floating point improvements you made for 3.0? I assume the double / float output is now correct and that decimal remains the outlier.

**Comment by tannergooding** [comment] 2020-02-18 00:44
This is the same as https://github.com/dotnet/runtime/issues/32237

This change is by design and was done for IEEE 754 compliance. This blog post goes into more detail about the range of changes that occurred: https://devblogs.microsoft.com/dotnet/floating-point-parsing-and-formatting-improvements-in-net-core-3-0/

**Comment by nikolayDemirev** [comment] 2020-02-18 09:12
If that is by design, is decimal going to preserve its current behavior, because we need it?

We are implementing Excel-like number formatting and this behavior differs from Excel because Excel does not have the concept for -0. The implementation in .NET Framework was convenient for us because we didn't have to implement the number formatting.

**Comment by tannergooding** [comment] 2020-02-18 16:23
> in math, there are positive numbers, negative numbers and zero?

That depends on how high in Mathematics you go. It does exist as a concept in various fields: <https://en.wikipedia.org/wiki/Signed_zero> and with regards to `double`/`float` can be impactful on things like whether you get a `+Infinity` or `-Infinity` (among other results).

> If that is by design, is decimal going to preserve its current behavior

Yes it will maintain its current behavior. `System.Decimal` (`decimal` keyword in C#) doesn't expose concepts like `+/-Infinity` and so exposing `-0` doesn't make sense.
If you go this route, you just have to be aware of the differences between `decimal` and `float`/`double` and how printed strings may differ.

It might be simpler to just create a [custom numeric format string](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-numeric-format-strings) which handles zero or to normalize the value to `+0` before formatting.

**Comment by nikolayDemirev** [comment] 2020-02-18 17:00
Thank you for the information. You are right, that part of the math didn't cross my mind :smile:

I will research if I can use decimal instead of double because my team works on an Excel-like software, where you can set a value -0.01 in a cell and apply numeric format string "0". Excel complies partially with IEEE 754 and the result of that format is 0. Our software behaves the same for .NET Framework, but for .NET Core, the result is -0. So the custom numeric format strings are currently not an option.

**Comment by charlesroddie** [comment] 2020-02-18 19:14
Can we consolidate discussion on the other thread as it was first?

**Comment by tannergooding** [comment] 2020-02-18 22:01
Going to close this as the individual issue seems to have been resolved and any remaining discussion can happen on the other thread: https://github.com/dotnet/runtime/issues/32237

**Closed by tannergooding** 2020-02-18 22:01 UTC
Labels: area-System.Runtime, untriaged
