### ISSUE TITLE
[JsonConstructor] should not be required on readonly structs with a single parameterized constructor

### ISSUE THREAD

**Issue by jnm2** [dotnet/runtime#59309] opened 2021-09-18 19:24 UTC
Currently, System.Text.Json happily fills things with default instances of structs when the structs are readonly. This is surprising in all cases, and there's not even a warning even though there's no way that this can be useful or intended.

`[JsonConstructor]` should only be required on immutable types if there is more than one constructor.

```cs
var s = JsonSerializer.Deserialize<S>(JsonSerializer.Serialize(new S(1, "2")));
Console.WriteLine(s.A); // 0, but should be 1
Console.WriteLine(s.B); // null, but should be 2

public struct S
{
    public S(int a, string b)
    {
        this.A = a;
        this.B = b;
    }

    public int A { get; }
    public string B { get; }
}
```

I agree strongly with @xsoheilalizadeh at https://github.com/dotnet/runtime/issues/38102#issuecomment-646447565:

> @layomia Is there any way to do this without `[JsonConstructorAttribute]`? I won't couple a JSON API to my struct, it could be a ValueObject in a domain model.

**Comment by eiriktsarpalis** [comment] 2021-09-19 20:39
I came across this issue when working to add support for F# struct records. It's by design and this is the relevant logic that [forces structs to fall back to the default constructor if they have not been annotated explicitly](https://github.com/dotnet/runtime/blob/e4b8d35ec7ed630fa3ed7a6b516a9151748fc881/src/libraries/System.Text.Json/Common/ReflectionExtensions.cs#L304). Had a conversation with @layomia about this but I cannot recall the motivation behind the feature.

**Comment by layomia** [comment] 2021-09-20 23:36
In the first release of System.Text.Json in .NET Core 3.0, structs were always deserialized using their default ctors since they are always present. When we implemented parameterized ctor support in 5.0, it would have been a breaking change to defer to a non-annotated public parameterized ctor on structs, even if there is only one and the struct in question is considered immutable. Also, for non-owned types and framework types, it could still be ambiguous which ctor is intended for deserialization. In API review we took a consistent approach of leaving 3.0 semantics as-is & requiring the attribute if a parameterized ctor is needed to deserialize a struct.

**Comment by layomia** [comment] 2021-09-22 17:56
Closing this issue - STJ parameterized ctor support is consistent within classes and structs respectively, and we shouldn't change/break this behavior.

**Closed by layomia** 2021-09-22 17:56 UTC
Labels: enhancement, area-System.Text.Json

**Comment by jnm2** [comment] 2021-09-22 18:19
Should there not be at least a warning rather than filling collections with defaulted struct instances? STJ can tell for sure that 0 of the available fields are being mapped.

**Comment by jnm2** [comment] 2021-09-22 18:21
Also, maybe I pidgeonholed the issue by saying the word "struct." This applies equally between immutable structs and immutable classes; the only subtlety being that in the struct case, you can't get rid of the default constructor even though it is always the worst outcome if STJ picks the default constructor when mapping data to an immutable struct.
