### ISSUE TITLE
double with value 0 ToString() can return "-0"

### ISSUE THREAD

**Issue by tl-cristian-bordean** [dotnet/runtime#32975] opened 2020-02-27 16:14 UTC
# Issue Title

double with the value 0 ToString() can return "-0"

# General

If you have a variable of type double with the value 0, multiply it by -1 and do a ToString on the result you will get "-0".

`var val = 0d
val *= -1;

var result = val.ToString()`

// result = "-0";

The issue only seems to occur with variables of type double and doesn't occurs on the latest version of .Net Framework.

**Comment by scalablecory** [comment] 2020-02-28 19:57
Duplicate of #32237

**Closed by scalablecory** 2020-02-28 19:57 UTC
Labels: area-System.Runtime, untriaged
