### ISSUE TITLE
Test failure System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_DeleteCategory

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#94395] opened 2023-11-06 01:35 UTC
**Failed in:** [runtime-coreclr libraries-pgo 20231105.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=460357&view=ms.vss-test-web.build-test-results-tab&runId=10396552&resultId=110777&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x64-CoreCLR_checked-fullpgo_methodprofiling-Windows.10.Amd64.Open
    - System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_DeleteCategory
```

**Error message:**
```
System.ComponentModel.Win32Exception : The process cannot access the file because it is being used by another process.
```

**Stack trace:**
```
   at System.Diagnostics.PerformanceCounterLib.RegisterFiles(String arg0, Boolean unregister) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs:line 1234
   at System.Diagnostics.PerformanceCounterLib.RegisterCategory(String categoryName, PerformanceCounterCategoryType categoryType, String categoryHelp, CounterCreationDataCollection creationData) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs:line 1184
   at System.Diagnostics.PerformanceCounterCategory.Create(String categoryName, String categoryHelp, PerformanceCounterCategoryType categoryType, CounterCreationDataCollection counterData) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs:line 237
   at System.Diagnostics.PerformanceCounterCategory.Create(String categoryName, String categoryHelp, PerformanceCounterCategoryType categoryType, String counterName, String counterHelp) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs:line 202
   at System.Diagnostics.Tests.Helpers.CreateCategory(String categoryName, String counterName, PerformanceCounterCategoryType categoryType) in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/Helpers.cs:line 33
   at System.Diagnostics.Tests.Helpers.CreateCategory(String categoryName, PerformanceCounterCategoryType categoryType) in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/Helpers.cs:line 23
   at System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_DeleteCategory() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterCategoryTests.cs:line 210
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "System.Diagnostics.PerformanceCounterLib.RegisterFiles",
  "ErrorPattern": "",
  "BuildRetry": true,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=460357
**Error message validated:** `System.Diagnostics.PerformanceCounterLib.RegisterFiles`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 11/10/2023 4:11:15 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by ericstj** [comment] 2024-08-06 16:37
Duplicate of https://github.com/dotnet/runtime/issues/105925

**Closed by ericstj** 2024-08-06 16:37 UTC
Labels: os-windows, arch-x64, blocking-clean-ci-optional, area-System.Diagnostics.PerformanceCounter, Known Build Error
