### ISSUE TITLE
[Proposal]: [Extension Method for Add seconds on TimeOnly]

### ISSUE THREAD

**Issue by drigovz** [dotnet/runtime#103020] opened 2024-06-04 01:38 UTC
# EXTENSION METHOD FOR ADD SECONDS ON TIMEONLY

* [x] Proposed
* [ ] Prototype: Not Started
* [ ] Implementation: Not Started
* [ ] Specification: Not Started

## Summary
[summary]: #summary

Would be possible to add a extension method for TimeOnly that add seconds to an existente TimeOnly object?

## Motivation
[motivation]: #motivation
To facility add seconds on TimeOnly.

## Detailed design
I suggest a extension method like this for example:

![image](https://github.com/dotnet/csharplang/assets/40927605/58c616aa-c5a2-4210-bb28-bb2eb3c57c9f)

And usage would be like this:

![image](https://github.com/dotnet/csharplang/assets/40927605/94fefa22-ed41-44de-a989-d57be98d9ac9)

**Comment by huoyaoyuan** [comment] 2024-06-04 05:34
Covered by #62413

**Comment by tarekgh** [comment] 2024-06-04 15:35
Yes it is duplicate of https://github.com/dotnet/runtime/issues/62413

**Closed by tarekgh** 2024-06-04 15:35 UTC
Labels: untriaged, area-System.DateTime
