### ISSUE TITLE
User Secrets file is required, even when it's excluded in conditional compile

### ISSUE THREAD

**Issue by johnkwaters** [dotnet/runtime#62320] opened 2021-12-03 04:44 UTC
### Description

In .net 6., i get the error 

2021-12-03 04:36:12.891 +00:00 [FTL] Host terminated unexpectedly.
System.IO.FileNotFoundException: The configuration file 'secrets.json' was not found and is not optional. The expected physical path was 'D:\home\site\wwwroot\secrets.json'.

Even though I don't load secrets when RELEASE compiled...

The project has a secretsid

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
	  <UserSecretsId>7764e302-f133-4687-89e9-268ac0d76b83</UserSecretsId>
  </PropertyGroup>

Here is the #IF DEBUG

                    webBuilder.ConfigureAppConfiguration((context, cfgBuilder) =>
                    {
                        _configurationRoot = cfgBuilder.Build();
                        // note CreateDefaultBuilder does a lot of work, see https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.webhost.createdefaultbuilder?view=aspnetcore-2.2
#if DEBUG
                        cfgBuilder.AddUserSecrets<Startup>();
                        _configurationRoot = cfgBuilder.Build();
#endif
                        var vault = _configurationRoot["Vault"];
                        if (!string.IsNullOrEmpty(vault))
                        {
                            var azureServiceTokenProvider = new AzureServiceTokenProvider();
                            var keyVaultClient = new KeyVaultClient(
                                new KeyVaultClient.AuthenticationCallback(
                                    azureServiceTokenProvider.KeyVaultTokenCallback));
                            var keyVaultEndpoint = $"https://{vault}.vault.azure.net";
                            cfgBuilder.AddAzureKeyVault(
                                keyVaultEndpoint, keyVaultClient, new DefaultKeyVaultSecretManager());
                        }
                        _configurationRoot = cfgBuilder.Build();
                    })

### Reproduction Steps

Add secrets to the project, and conditionally use them

#if DEBUG
                        cfgBuilder.AddUserSecrets<Startup>();
                        _configurationRoot = cfgBuilder.Build();
#endif

### Expected behavior

Should not be required to have a secrets file when release compiled

### Actual behavior

Requires secrets.json

**Comment by martincostello** [comment] 2021-12-03 07:44
Dupe of #61418?

**Comment by johnkwaters** [comment] 2021-12-03 16:27
@martincostello it seems related - I added this info to there too.

**Comment by eerhardt** [comment] 2021-12-03 16:56
Closing as a dupe of #61418.

**Closed by eerhardt** 2021-12-03 16:56 UTC
Labels: untriaged, area-Extensions-Configuration
