### ISSUE TITLE
IEnumerable<T>.TakeLast behave wrong

### ISSUE THREAD

**Issue by feiyun0112** [dotnet/runtime#55975] opened 2021-07-20 00:19 UTC
```
var numbers = new List<int>(Enumerable.Range(1, 10));
var last5 = numbers.TakeLast(5);
Console.WriteLine(last5.Count());
//print 5

numbers.AddRange(new[] { 11, 12, 13, 14, 15 });
Console.WriteLine(last5.Count());
//print 6
```

why last5 count is not correct after change numbers?

is it right behave?

**Comment by wzchua** [comment] 2021-07-20 00:32
I believe this is fixed in NET6.0 already. dupe of https://github.com/dotnet/runtime/issues/39864

**Closed** 2021-07-20 00:49 UTC
Labels: area-System.Linq, untriaged
