### ISSUE TITLE
Test failure JIT\\Regression\\JitBlue\\GitHub_18522\\GitHub_18522_2\\GitHub_18522_2.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#65348] opened 2022-02-15 01:09 UTC
Run: [runtime-coreclr r2r 20220213.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1610805&view=ms.vss-test-web.build-test-results-tab&runId=44870348&paneView=debug&resultId=102204)

Failed test:
```
R2R windows x64 Checked @ Windows.10.Amd64.Open

- JIT\\Regression\\JitBlue\\GitHub_18522\\GitHub_18522_2\\GitHub_18522_2.cmd
- JIT\\Regression\\JitBlue\\GitHub_3449\\GitHub_3449\\GitHub_3449.cmd
- JIT\\Regression\\JitBlue\\GitHub_18144\\GitHub_18144\\GitHub_18144.cmd
- JIT\\Regression\\JitBlue\\GitHub_14784\\GitHub_14784\\GitHub_14784.cmd
- JIT\\HardwareIntrinsics\\X86\\Regression\\GitHub_21899\\GitHub_21899_ro\\GitHub_21899_ro.cmd
- JIT\\Regression\\JitBlue\\GitHub_12949\\GitHub_12949_3\\GitHub_12949_3.cmd
- JIT\\Regression\\JitBlue\\**

```
**Error message:**
```
Could Not Find C:\h\w\BCDF0A0D\w\B5FB0A15\e\JIT\Regression\JitBlue\GitHub_18522\GitHub_18522_2\IL-CG2\composite-r2r.dll
Could Not Find C:\h\w\BCDF0A0D\w\B5FB0A15\e\JIT\Regression\JitBlue\GitHub_18522\GitHub_18522_2\GitHub_18522_2.dll.rsp
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'System.Diagnostics.Tracing, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The module was expected to contain an assembly manifest.
File name: 'System.Diagnostics.Tracing, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
at ILCompiler.Program.Run(String[] args)
at ILCompiler.Program.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\BCDF0A0D\w\B5FB0A15\uploads\Reports\JIT.Regression\JitBlue\GitHub_18522\GitHub_18522_2\GitHub_18522_2.output.txt
Raw output:
BEGIN EXECUTION
GitHub_18522_2.dll
1 file(s) copied.
Response file: C:\h\w\BCDF0A0D\w\B5FB0A15\e\JIT\Regression\JitBlue\GitHub_18522\GitHub_18522_2\GitHub_18522_2.dll.rsp
C:\h\w\BCDF0A0D\w\B5FB0A15\e\JIT\Regression\JitBlue\GitHub_18522\GitHub_18522_2\IL-CG2\GitHub_18522_2.dll
-o:C:\h\w\BCDF0A0D\w\B5FB0A15\e\JIT\Regression\JitBlue\GitHub_18522\GitHub_18522_2\GitHub_18522_2.dll
--targetarch:x64
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\BCDF0A0D\p\System..dll
-r:C:\h\w\BCDF0A0D\p\Microsoft..dll
-r:C:\h\w\BCDF0A0D\p\mscorlib.dll
-r:C:\h\w\BCDF0A0D\p\netstandard.dll
-O
" "dotnet" "C:\h\w\BCDF0A0D\p\crossgen2\crossgen2.dll" @"C:\h\w\BCDF0A0D\w\B5FB0A15\e\JIT\Regression\JitBlue\GitHub_18522\GitHub_18522_2\GitHub_18522_2.dll.rsp"   -r:C:\h\w\BCDF0A0D\w\B5FB0A15\e\JIT\Regression\JitBlue\GitHub_18522\GitHub_18522_2\IL-CG2*.dll"
Crossgen2 failed with exitcode - -532462766
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\BCDF0A0D\p
C:\h\w\BCDF0A0D\w\B5FB0A15\e\JIT\Regression\JitBlue\GitHub_18522\GitHub_18522_2\GitHub_18522_2.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_Regression._JitBlue_GitHub_18522_GitHub_18522_2_GitHub_18522_2_._JitBlue_GitHub_18522_GitHub_18522_2_GitHub_18522_2_cmd()
```

**Comment by trylek** [comment] 2022-04-04 20:33
Closing as duplicate of: https://github.com/dotnet/runtime/issues/65646

**Closed by trylek** 2022-04-04 20:33 UTC
Labels: os-windows, arch-x64, area-crossgen2-coreclr
