### ISSUE TITLE
Failure test: JIT\\Performance\\CodeQuality\\Roslyn\\CscBench\\CscBench.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#56195] opened 2021-07-23 02:55 UTC
Run: [runtime-coreclr jitstress 20210721.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1252387&view=ms.vss-test-web.build-test-results-tab&runId=37176054&resultId=109603&paneView=debug)

Failed test:
```
CoreCLR windows x64 Checked jitstress1 @ Windows.10.Amd64.Open

- JIT\\Performance\\CodeQuality\\Roslyn\\CscBench\\CscBench.cmd
- managed\\Compilation\\Compilation\\Compilation.cmd

CoreCLR windows x64 Checked jitstress1_tiered @ Windows.10.Amd64.Open

- JIT\\Performance\\CodeQuality\\Roslyn\\CscBench\\CscBench.cmd
- managed\\Compilation\\Compilation\\Compilation.cmd

```
**One of error message:**
```
Assert failure(PID 5756 [0x0000167c], Thread: 4996 [0x1384]): Assertion failed 'kind == Overwrite' in 'Microsoft.CodeAnalysis.CodeGen.ILBuilder:RealizeBlocks():this' during 'Do value numbering' (IL size 537)

File: D:\workspace\_work\1\s\src\coreclr\jit\jithashtable.h Line: 238
Image: C:\h\w\B6800977\p\corerun.exe
Return code:      1
Raw output file:      C:\h\w\B6800977\w\AC94096B\uploads\Reports\JIT.Performance\CodeQuality\Roslyn\CscBench\CscBench.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\B6800977\p\corerun.exe"  CscBench.dll
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\B6800977\p
C:\h\w\B6800977\w\AC94096B\e\JIT\Performance\CodeQuality\Roslyn\CscBench\CscBench.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_Performance._CodeQuality_Roslyn_CscBench_CscBench_._CodeQuality_Roslyn_CscBench_CscBench_cmd() in JIT.Performance.XUnitWrapper.dll:token 0x6000096+0x284
```

**Comment by JulieLeeMSFT** [comment] 2021-07-23 16:34
@jakobbotsch PTAL.

**Comment by jakobbotsch** [comment] 2021-07-23 16:45
Duplicate of #56174

**Closed by jakobbotsch** 2021-07-23 16:45 UTC
Labels: JitStress, arch-x64, area-CodeGen-coreclr, os-windows
