### ISSUE TITLE
ComInterfaceGenerator warns twice on some warnings: once when generating the managed wrapper and another when making the native wrapper

### ISSUE THREAD

**Issue by jtschuster** [dotnet/runtime#88540] opened 2023-07-07 22:18 UTC
Some warnings are made by the generator twice, once for each stub the generator makes (native, managed). The generator should only warn once.

**Comment by jtschuster** [comment] 2023-07-10 22:52
This is also causing some different warnings to appear, not just the same ones twice. For instance, for [In, Out] attributes, `int[] param` will warn as an `int[]` when generating a managed to unmanaged stub, but `int*` in the unmanaged to managed stub. This causes it to think `[In]` is not supported one case, and is the default behavior in another.

**Comment by jkoritzinsky** [comment] 2023-07-13 22:08
The first part of this issue (the duplication) has been fixed. I don't think we can fix the "two different diagnostics" case as that's by design. We want to give valid diagnostics for the managed-to-unmanaged scenario as well as the other way, and sometimes the diagnostics are different because the scenarios are different.

I'm going to close this as completed as the remaining references to this issue will be removed in #88856

**Closed by jkoritzinsky** 2023-07-13 22:08 UTC
Labels: area-System.Runtime.InteropServices, source-generator
