### ISSUE TITLE
System.Private.Corelib R2R PDB is not included in runtime pack

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/runtime#92456] opened 2023-09-22 02:34 UTC
Profilers can't get information about R2R methods without this.

**Comment by mangod9** [comment] 2023-10-04 00:34
@hoyosjs is this a regression or always been this way? Adding @trylek @davidwrighton

**Comment by hoyosjs** [comment] 2023-10-04 03:10
It's a regression in packaging. The PDB itself is still getting produced.

**Comment by mangod9** [comment] 2023-10-04 04:33
Ok adding @ivdiazsa as well. Perhaps he can investigate a fix.

**Comment by ivdiazsa** [comment] 2023-10-04 16:51
Hmmm... I find this regression interesting. By packaging are we referring to the `packs` subset?

**Comment by ivdiazsa** [comment] 2023-10-04 22:31
Upon further investigation, we found out the issue was fixed at some point in time because the missing `System.Private.CoreLib.ni.pdb` is actually there in the current builds, so closing this issue now.

**Closed by ivdiazsa** 2023-10-04 22:31 UTC
Labels: blocking-release, area-Infrastructure-coreclr
