### ISSUE TITLE
Can't use [JsonSerializable] with [Cloneable] source gen

### ISSUE THREAD

**Issue by DevronB** [dotnet/runtime#65361] opened 2022-02-15 05:28 UTC
### Description

I'm using another source generator for marking classes as  [Cloneable](https://github.com/mostmand/Cloneable). But when I annotate my class with this I get the following (unhelpful) errors for my JsonSerializerContext class.

```cs
using System.Text.Json.Serialization;
using Cloneable;

[JsonSerializable(typeof(jTest))]
internal partial class MyJsonContext : JsonSerializerContext
{
}

[Cloneable]
public partial class jTest
{
    [JsonPropertyName("xxx")]
    public string pTest { get; set; } = "blah";

    [JsonIgnore]
    public static string StoreExt => ".act.json";

    public bool IsNotStarted => false;
}
```
```
class MyJsonContext
'MyJsonContext' does not implement inherited abstract member 'JsonSerializerContext.GeneratedSerializerOptions.get' [GTCore]csharp(CS0534)
'MyJsonContext' does not implement inherited abstract member 'JsonSerializerContext.GetTypeInfo(Type)' [GTCore]csharp(CS0534)
There is no argument given that corresponds to the required formal parameter 'options' of 'JsonSerializerContext.JsonSerializerContext(JsonSerializerOptions?)' [GTCore]csharp(CS7036)
```

Are these generators conflicting somehow, is there a way around this so I can use both?

I'm wanting to use this on Wear OS net6.0-android as default serialization/deserialization is very slow. I guess if I could get some speed using JsonSerializerContext I could use it for cloning, but the issue still exists.

Any advice appreciated.

### Reproduction Steps

As above

### Expected behavior

don't know, merging of source gen results?

### Actual behavior

as above

### Known Workarounds

none

### Configuration

tests above on  net6.0 console app.

**Comment by layomia** [comment] 2022-03-07 17:23
Might be a dup of https://github.com/dotnet/runtime/issues/62937.

**Comment by eiriktsarpalis** [comment] 2022-07-19 12:20
Moving to the .NET 8 milestone.

**Comment by eiriktsarpalis** [comment] 2022-09-28 16:29
Source generator throwing the following error:
```
CSC : warning CS8785: Generator 'JsonSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'InvalidOperationException' with message 'Operation is not valid due to the current state of the object.'
```
Need to debug the source generator to root cause the underlying issue.

**Comment by eiriktsarpalis** [comment] 2023-06-15 20:18
Can confirm this has been fixed by https://github.com/dotnet/runtime/pull/87383

**Closed by eiriktsarpalis** 2023-06-15 20:18 UTC
Labels: bug, area-System.Text.Json, help wanted, source-generator
