### ISSUE TITLE
Add support for R2R tail calls with helpers in crossgen/crossgen2

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/runtime#35423] opened 2020-04-24 19:45 UTC
This is a follow-up to #341, which introduced a new mechanism with portable tail call helpers.
Corresponds to https://github.com/dotnet/corert/issues/1683 .

**Comment by davidwrighton** [comment] 2020-08-03 20:44
@mangod9 I don't think we're likely to get to this in .NET 5.0. Do you think we need to implement this? It blocks use of Crossgen2 in some F# scenarios.

**Comment by mangod9** [comment] 2020-08-03 20:56
yeah should be ok to move to 6.

**Comment by davidwrighton** [comment] 2021-07-21 00:23
Moving to 7.0 This is a feature request.

**Comment by davidwrighton** [comment] 2022-07-08 18:15
This is a duplicate of #5857

**Closed by davidwrighton** 2022-07-08 18:15 UTC
Labels: area-crossgen2-coreclr
