### ISSUE TITLE
.NET 6 reading standard output blocks on Linux

### ISSUE THREAD

**Issue by ACanisLupus** [dotnet/runtime#74402] opened 2022-08-23 07:26 UTC
### Description

I have a .NET 6 process **prog1** which starts a .NET 6 process **prog2**, redirects its standard output and waits for all output. **prog2** starts a .NET 6 process **prog3** without redirecting its output and shuts down. **prog3** runs forever.
That works just fine on Windows. First **prog2** stops, then **prog1** stops, while **prog3** keeps running.
On Linux however, **prog1** hangs forever while waiting for all output. It only stops when **prog3** stops. 

### Reproduction Steps

```csharp
// prog1:
using System.Diagnostics;

var process = new Process
{
    StartInfo =
    {
        FileName = "prog2", // Or the full path, depending if prog2 is in the PATH or not
        RedirectStandardOutput = true,
        UseShellExecute = false
    }
};
process.Start();
process.WaitForExit();

Console.WriteLine(process.StandardOutput.ReadToEnd());

// prog2:
using System.Diagnostics;

using var process = new Process
{
    StartInfo =
    {
        FileName = "prog3", // Or the full path, depending if prog3 is in the PATH or not
        UseShellExecute = true
    }
};
process.Start();
Console.WriteLine("prog3 started successfully.");

// prog3:
Thread.Sleep(Timeout.Infinite);
```

### Expected behavior

Since **prog2** does not redirect the output of **prog3**, **prog1** is supposed to stop after **prog2** stops.

### Actual behavior

**prog1** stops on Windows but not on Linux.

### Regression?

I observed the same issue with .net core 3.1.

**Comment by tmds** [comment] 2022-08-23 07:34
> On Linux however, prog1 hangs forever while waiting for all output. It only stops when prog3 stops.

`prog3` is keeping standard output open. The .NET program (`prog1`) can't distinguish between standard output from `prog2` and that of its child `prog3`. This causes the standard output read to block until both `prog2` and `prog3` have finished.

If `prog3` is not producing output that is meant for `prog1` then `prog2` should redirect `prog2`'s output.

**Comment by Jozkee** [comment] 2022-08-24 16:00
So the solution/workaround is to `RedirectStandardOutput = true` from prog3 in prog2's code. @tmds do you know why this behaves different on Windows?

**Comment by tmds** [comment] 2022-08-30 12:25
> @tmds do you know why this behaves different on Windows?

You can reproduce this using `Tmds.ExecFunction` in a single application.

```cs
using System.Diagnostics;
using Tmds.Utils; // dotnet add package Tmds.ExecFunction

if (ExecFunction.IsExecFunctionCommand(args))
{
    return ExecFunction.Program.Main(args);
}
else
{
    Console.WriteLine("prog 2 Start");
    Process p = ExecFunction.Start(() =>
    {
        // Start prog3 and don't wait for it.
        ExecFunction.Start(() =>
        {
            System.Threading.Thread.Sleep(TimeSpan.FromSeconds(10));
            Console.WriteLine("Finished sleeping.");
        });
    }, opt => opt.StartInfo.RedirectStandardOutput = true);

    p.WaitForExit();
    Console.WriteLine("prog 2 WaitForExit done");

    string output = p.StandardOutput.ReadToEnd();
    Console.WriteLine("prog 2 ReadToEnd done");
    System.Console.WriteLine("output is: " + output);

    return 0;
}
```

When I run this, I get:
```
$ dotnet run
prog 2 Start
prog 2 WaitForExit done
prog 2 ReadToEnd done
Finished sleeping.
output is: Finished sleeping.
```
As you can see, prog1 can't distinguish between prog2 and prog3 output.

I'm surprised this behaves different on Windows.

**Comment by tmds** [comment] 2022-09-06 12:44
The behavior is as expected on Linux.

@Jozkee you can see how this behaves on Windows using the code from my previous comment. I am surprised it behaves different on Windows than Linux.

**Comment by tmds** [comment] 2022-09-20 11:12
I'm closing the issue since the behavior on Linux is the expected one.

**Closed by tmds** 2022-09-20 11:12 UTC
Labels: area-System.Diagnostics.Process
