### ISSUE TITLE
JsonCamelCaseNamingPolicy weird behavior

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#38437] opened 2020-06-26 11:20 UTC
### Description

System.Text.Json.JsonCamelCaseNamingPolicy does very weird conversion of strings with non-literal chars.
Example https://github.com/dotnet/runtime/blob/0f7a938c6ed5a2009d401a4e3c5cb467c96dc498/src/libraries/System.Text.Json/tests/Serialization/CamelCaseUnitTests.cs#L36

Here I'd expect `shouting_CASE`. 

The converter considers only a space as special case: `SHOUTING CASE` is expectedly converted to `shouting CASE`.
https://github.com/dotnet/runtime/blob/bd6cbe3642f51d70839912a6a666e5de747ad581/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonCamelCaseNamingPolicy.cs#L40-L50

My expectation is that the converter should consider all non-literals (@#$%^&*()_-+<>,.?/\~ , digits and controls) as well as a space:
`SHOUTING CASE` -> `shouting CASE`
`SHOUTING_CASE` -> `shouting_CASE`
`SHOUTING#CASE` -> `shouting#CASE`

### Configuration

Tested on 5.0 Preview6

### Regression?

Fixing this will be a breaking change but I'd speculate that the API is not still broadly used and we could accept such change (and maybe backport to 3.1 LTS).

### Other information

I have played a bit with the code and found that the code could work faster if the change will be approved.

**Comment by ahsonkhan** [comment] 2020-07-16 01:59
Though I can understand that the current behavior could be surprising, it was intentionally done this way to be compatible with the semantics of `Newtonsoft.Json` when it comes to camel casing to avoid subtle breaks in the serialized JSON when folks coming from `Newtonsoft` use S.T.J.

See
https://github.com/JamesNK/Newtonsoft.Json/blob/666d9760719e5ec5b2a50046f7dbd6a1267c01c6/Src/Newtonsoft.Json/Utilities/StringUtils.cs#L155
https://github.com/JamesNK/Newtonsoft.Json/blob/ff6f51b667b7bb05b7f595c331074ecb6c93bd56/Src/Newtonsoft.Json.Tests/Utilities/StringUtilsTests.cs#L64

> Fixing this will be a breaking change but I'd speculate that the API is not still broadly used and we could accept such change (and maybe backport to 3.1 LTS).

Since it would be a breaking change between versions of S.T.J. and introduce another discrepancy between it and Newtonsoft.Json, I don't think the benefits outweigh the concerns. It is also relatively straight forward to override the camel case naming policy with your own custom definition of camel case and hook-in the simplified implementation that meets your expectation.

There is an extremely high bar to back-port such potentially breaking changes, especially for an LTS release, and especially since this would change the output JSON format, which could be persisted long-term to databases/etc.

I recommend we close this issue, as by design.

**Comment by iSazonov** [comment] 2020-07-16 03:22
@ahsonkhan Thanks for the explanation! 
I am trying to migrate PowerShell Core from `Newtonsoft.Json` to the new API and for compatibility reasons the behavior is ok.
But I opened the issue because I'd expect that users will catch the behavior from time to time and ask about "standard" implementation.
So I think your explanation could be moved to .Net documentation as well as the workaround.

**Closed** 2021-10-16 06:04 UTC
Labels: question, area-System.Text.Json
