### ISSUE TITLE
[Proposal]: [String.SplitAsSpan]

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/runtime#63497] opened 2022-01-07 07:07 UTC
### Background and motivation

Currently string.split returns string array which might cause allocation.
instead it can return a span, sliced from the last position as parameter passed

### API Proposal

```C#
namespace System.string
{
    public class string
    {
        public Span<char> SplitAsSpan();
    }
}
```

### API Usage

```C#
string a;
(string str, int pos) cache;
while((cache = a.SplitAsSpan("\n", cache.pos, cache.str.length) != default)
{
    //do something with cache.string
}
```

**Comment by Sergio0694** [comment] 2022-01-07 09:29
It seems to me here you just want to enumerate the `ReadOnlySpan<char>` values in a `string` after splitting it over a single `char`, correct? If that's the case, may I also suggest trying out [`string.Tokenize(char)`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.toolkit.highperformance.extensions.stringextensions.tokenize) that does exactly that, with an easier to use syntax too:

```csharp
foreach (ReadOnlySpan<char> slice in text.Tokenize('\n'))
{
}
```

Alternatively, if you don't want to actually slice over a single arbitrary character here, but specifically just want to enumerate lines, there's the built-in [`ReadOnlySpan<char>.EnumerateLines()`](https://docs.microsoft.com/en-us/dotnet/api/system.memoryextensions.enumeratelines?view=net-6.0#system-memoryextensions-enumeratelines(system-readonlyspan((system-char)))) now in .NET 6 🙂

**Comment by koszeggy** [comment] 2022-01-07 11:01
Until a solution is introduced in the runtime you can use [this](https://github.com/koszeggy/KGySoft.CoreLibraries#useful-extensions) library (disclaimer: written by me) and its [`StringSegment`](https://docs.kgysoft.net/corelibraries/?topic=html/T_KGySoft_CoreLibraries_StringSegment.htm) type.

Its [`Split`](https://docs.kgysoft.net/corelibraries/?topic=html/Overload_KGySoft_CoreLibraries_StringSegment_Split.htm) methods work the same way as regular `String.Split` (therefore, they use at least one allocation as the result is a collection):

```cs
// the result is IList<StringSegment> so there is one allocation
var segments = str.AsSegment().Split(Environment.NewLine);
```

But if you want to 'split' a string completely allocation free you can use the [`Read*`](https://docs.kgysoft.net/corelibraries/?topic=html/Methods_T_KGySoft_CoreLibraries_StringSegmentExtensions.htm) extension methods:

```cs
StringSegment text = str; // implicit conversion, same as str.AsSegment()
while (text.Length > 0)
{
    // Though StringSegment is readonly, it is passed by ref to ReadLine so it acts just like a text reader
    StringSegment line = text.ReadLine();

    // TODO: process line. It can be cast to [ReadOnly]Span/Memory<char> so you can pass it to any usual API
}
```

You can find some examples and performance comparisons [here](https://dotnetfiddle.net/Byk0YM).

**Comment by Xyncgas** [comment] 2022-01-07 11:41
Ohhhhh. I will try it out thanks.
I knew you were my brothers right away

**Comment by stephentoub** [comment] 2022-01-07 14:22
Duplicate of https://github.com/dotnet/runtime/issues/934

**Closed by stephentoub** 2022-01-07 14:22 UTC
Labels: api-suggestion, untriaged
