### ISSUE TITLE
LoggingScopeHttpMessageHandler should not log unredacted Uri

### ISSUE THREAD

**Issue by evgenyfedorov2** [dotnet/runtime#74339] opened 2022-08-22 11:56 UTC
### Description

[LoggingScopeHttpMessageHandler](https://github.com/dotnet/runtime/blob/215b39abf947da7a40b0cb137eab4bceb24ad3e3/src/libraries/Microsoft.Extensions.Http/src/Logging/LoggingScopeHttpMessageHandler.cs) logs HttpMethod and Uri [here](https://github.com/dotnet/runtime/blob/215b39abf947da7a40b0cb137eab4bceb24ad3e3/src/libraries/Microsoft.Extensions.Http/src/Logging/LoggingScopeHttpMessageHandler.cs#L86). While `HttpMethod` is safe to log, `Uri` is not, it often contains sensitive information which is a huge risk.

### Reproduction Steps

Use HttpClient to send a request:

```
using var httpRequestMessage = new HttpRequestMessage
{
    Method = HttpMethod.Post,
    RequestUri = new("http://localhost/images/12345"),
};
_ = await _httpClient.SendAsync(httpRequestMessage, cancellationToken).ConfigureAwait(false);
```

### Expected behavior

Either of those:

- An option to redact the URI which is enabled by default, so that by default the output would be:
```
HttpMethod:POST
Uri:http://localhost/images/<this was redacted>
{OriginalFormat}:HTTP {HttpMethod} {Uri} 
```
- Remove Uri from logging

### Actual behavior

ILogger's scope contains this:

```
HttpMethod:POST
Uri:http://localhost/images/12345
{OriginalFormat}:HTTP {HttpMethod} {Uri} 
```

where 12345 is my privacy information

### Known Workarounds

The only way is `services.RemoveAll<IHttpMessageHandlerBuilderFilter>();` which is harsh. I need logging, but don't want to be exposed to a risk of leaking sensitive information

**Comment by CarnaViire** [comment] 2022-08-22 12:03
Thank you @evgenyfedorov2
This is a dupe of https://github.com/dotnet/runtime/issues/68675, so I'm going to close this one.
Please upvote #68675 if you need this feature, it would help us prioritize. Thanks!

**Comment by CarnaViire** [comment] 2022-08-22 12:04
Duplicate of #68675

**Closed** 2022-08-22 12:04 UTC
Labels: area-System.Net.Http, untriaged

**Comment by xakep139** [comment] 2022-08-22 12:15
Hey @CarnaViire, isn't #68675 only about query parameters?

**Comment by CarnaViire** [comment] 2022-08-22 12:36
@xakep139 oh right, thanks for pointing that out. But let's gather all additional requirements in one place.
