### ISSUE TITLE
SequenceReader, TryReadLittleEndian analyzer error issue

### ISSUE THREAD

**Issue by Phylum123** [dotnet/runtime#94172] opened 2023-10-30 13:25 UTC
### Description

When trying to use an 'in' SequenceReader<byte> parameter, and the TryReadLittleEndian method, I get an error

### Reproduction Steps

```
		public bool TryReadMessage(in SequenceReader<byte> reader)
		{

			if (!reader.TryRead(out byte messageTypeByte))
				return false;

			if (!reader.TryReadLittleEndian(out int bodyLength))
				return false;
               }
```

This must be a bug in the analyzer, because as you can see, the 'TryRead' above is perfectly valid and is doing the exact same thing.

### Expected behavior

I shouldn't get an error

### Actual behavior

I get an error:
CS8329: Cannot use variable 'reader' as a ref or out value because it is a readonly variable

### Known Workarounds

If I change the reader parameter to 'ref', it works, but I lose the 'in' readonlyness.

**Comment by reflectronic** [comment] 2023-10-30 21:41
The source of the error here is that `TryReadLittleEndian` is an extension method that takes `ref this` rather than `in this`:
https://github.com/dotnet/runtime/blob/d58dd91b1b0dc64214ce0a825c0a278449b0431e/src/libraries/System.Memory/src/System/Buffers/SequenceReaderExtensions.Binary.cs#L99

However, `TryRead` is an instance method, so instead of failing to bind to an applicable member, the C# compiler performs `TryRead` on a silent copy of the `reader` object. 

Critically, this means that the call to `TryRead` in your example does not actually advance the `reader` object. I suspect you did not intend this. The solution is to use a `ref` parameter instead of an `in` parameter.

For the same reason, it is not correct to change the signature of the extension method, since it would result in the extension method also not advancing the reader.

**Comment by huoyaoyuan** [comment] 2023-10-31 06:43
`SequenceReader` is a mutable struct with state hold. It should be passed with `ref`, instead of `in` or by value.

The CSxxxx errors are from compiler, not analyzer. An analyzer should warn on implicit copy for `TryRead` instead.

**Comment by jeffhandley** [comment] 2024-03-22 01:07
Thanks for the notes on this, @reflectronic and @huoyaoyuan. Closing this out as not a bug.

**Closed by jeffhandley** 2024-03-22 01:07 UTC
Labels: area-System.Buffers, untriaged
