### ISSUE TITLE
XmlSerializerTests fail in NativeAOT runs

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#76018] opened 2022-09-22 14:36 UTC
See https://github.com/dotnet/runtime/pull/75943/checks?check_run_id=8486625348

error : (NETCORE_ENGINEERING_TELEMETRY=Test) Test XmlSerializerTests.Xml_ValidateExceptionOnUnspecifiedRootSerializationType has failed. Check the Test tab or this console log: https://helix.dot.net/api/2019-06-17/jobs/dd7a1b39-038a-40fe-9a1a-edc657632668/workitems/System.Private.Xml.Tests/console

```
[FAIL] XmlSerializerTests.Xml_ValidateExceptionOnUnspecifiedRootSerializationType
System.InvalidOperationException : There is an error in XML document (2, 2).
---- System.NotSupportedException : 'System.Xml.Serialization.ReflectionXmlSerializationReaderHelper.GetSetMemberValueDelegateWithType[SerializationTypes.UnspecifiedRootSerializationType,System.Int32](System.Reflection.MemberInfo)' is missing native code. MethodInfo.MakeGenericMethod() is not compatible with AOT compilation. Inspect and fix AOT related warnings that were generated when the app was published. For more information see https://aka.ms/nativeaot-compatibility
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) + 0x291
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream) + 0x9c
   at XmlSerializerTests.SerializeAndDeserialize[T](T value, String baseline, Func`1 serializerFactory, Boolean skipStringCompare, XmlSerializerNamespaces xns) + 0x21b
   at XmlSerializerTests.Xml_ValidateExceptionOnUnspecifiedRootSerializationType() + 0x7c
   at System.Private.Xml.Tests!<BaseAddress>+0x1261abf
   at System.Reflection.DynamicInvokeInfo.Invoke(Object thisPtr, IntPtr methodToCall, Object[] parameters, BinderBundle binderBundle, Boolean wrapInTargetInvocationException) + 0xcf
----- Inner Stack Trace -----
   at System.Reflection.Runtime.MethodInfos.RuntimeNamedMethodInfo`1.GetUncachedMethodInvoker(RuntimeTypeInfo[] methodArguments, MemberInfo exceptionPertainant) + 0x2f
   at System.Reflection.Runtime.MethodInfos.RuntimeNamedMethodInfo`1.MakeGenericMethod(Type[] typeArguments) + 0x18e
   at System.Xml.Serialization.ReflectionXmlSerializationReader.GetSetMemberValueDelegate(Object o, String memberName) + 0x1a2
   at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteLiteralStructMethod(StructMapping structMapping, Boolean isNullable, Boolean checkType, String defaultNamespace) + 0xa6c
   at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteElement(ElementAccessor element, Boolean checkSpecified, Boolean checkForNull, Boolean readOnly, String defaultNamespace, Int32 fixupIndex, Int32 elementIndex, XmlSerializationReader.Fixup fixup, ReflectionXmlSerializationReader.Member member) + 0x4b8
   at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElementsIf(ReflectionXmlSerializationReader.Member[] expectedMembers, ReflectionXmlSerializationReader.Member anyElementMember, UnknownNodeAction elementElseAction, XmlSerializationReader.Fixup fixup, ReflectionXmlSerializationReader.CheckTypeSource checkTypeSource) + 0x2e0
   at System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateTypeElement(XmlTypeMapping xmlTypeMapping) + 0x1a7
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) + 0x132
[FAIL] XmlSerializerTests.Xml_Soap_Nullable
System.InvalidOperationException : There is an error in XML document (2, 2).
---- System.NotSupportedException : 'System.Xml.Serialization.ReflectionXmlSerializationReaderHelper.GetSetMemberValueDelegateWithType[SerializationTypes.SomeStruct,System.Int32](System.Reflection.MemberInfo)' is missing native code. MethodInfo.MakeGenericMethod() is not compatible with AOT compilation. Inspect and fix AOT related warnings that were generated when the app was published. For more information see https://aka.ms/nativeaot-compatibility
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) + 0x291
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream) + 0x9c
   at XmlSerializerTests.SerializeAndDeserialize[T](T value, String baseline, Func`1 serializerFactory, Boolean skipStringCompare, XmlSerializerNamespaces xns) + 0x251
   at XmlSerializerTests.Xml_Soap_Nullable() + 0x1b0
   at System.Private.Xml.Tests!<BaseAddress>+0x1261abf
   at System.Reflection.DynamicInvokeInfo.Invoke(Object thisPtr, IntPtr methodToCall, Object[] parameters, BinderBundle binderBundle, Boolean wrapInTargetInvocationException) + 0xcf
----- Inner Stack Trace -----
   at System.Reflection.Runtime.MethodInfos.RuntimeNamedMethodInfo`1.GetUncachedMethodInvoker(RuntimeTypeInfo[] methodArguments, MemberInfo exceptionPertainant) + 0x2f
   at System.Reflection.Runtime.MethodInfos.RuntimeNamedMethodInfo`1.MakeGenericMethod(Type[] typeArguments) + 0x18e
   at System.Xml.Serialization.ReflectionXmlSerializationReader.GetSetMemberValueDelegate(Object o, String memberName) + 0x1a2
   at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteEncodedStructMethod(StructMapping structMapping) + 0x1d2
   at System.Xml.Serialization.XmlSerializationReader.ReadReferencingElement(String name, String ns, Boolean elementCanBeType, String& fixupReference) + 0x22b
   at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteElement(ElementAccessor element, Boolean checkSpecified, Boolean checkForNull, Boolean readOnly, String defaultNamespace, Int32 fixupIndex, Int32 elementIndex, XmlSerializationReader.Fixup fixup, ReflectionXmlSerializationReader.Member member) + 0x3b7
   at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteNullableMethod(NullableMapping nullableMapping, Boolean checkType, String defaultNamespace) + 0xb0
   at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteElement(ElementAccessor element, Boolean checkSpecified, Boolean checkForNull, Boolean readOnly, String defaultNamespace, Int32 fixupIndex, Int32 elementIndex, XmlSerializationReader.Fixup fixup, ReflectionXmlSerializationReader.Member member) + 0xb7
   at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElementsIf(ReflectionXmlSerializationReader.Member[] expectedMembers, ReflectionXmlSerializationReader.Member anyElementMember, UnknownNodeAction elementElseAction, XmlSerializationReader.Fixup fixup, ReflectionXmlSerializationReader.CheckTypeSource checkTypeSource) + 0x2e0
   at System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateTypeElement(XmlTypeMapping xmlTypeMapping) + 0x1a7
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) + 0x132
[FAIL] XmlSerializerTests.Xml_TypeWithEnumFlagPropertyHavingDefaultValue
System.InvalidOperationException : There is an error in XML document (2, 2).
---- System.NotSupportedException : 'System.Xml.Serialization.ReflectionXmlSerializationReaderHelper.GetSetMemberValueDelegateWithType[SerializationTypes.TypeWithEnumFlagPropertyHavingDefaultValue,SerializationTypes.EnumFlags](System.Reflection.MemberInfo)' is missing native code. MethodInfo.MakeGenericMethod() is not compatible with AOT compilation. Inspect and fix AOT related warnings that were generated when the app was published. For more information see https://aka.ms/nativeaot-compatibility
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) + 0x291
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream) + 0x9c
   at XmlSerializerTests.SerializeAndDeserialize[T](T value, String baseline, Func`1 serializerFactory, Boolean skipStringCompare, XmlSerializerNamespaces xns) + 0x21b
   at XmlSerializerTests.Xml_TypeWithEnumFlagPropertyHavingDefaultValue() + 0x48
   at System.Private.Xml.Tests!<BaseAddress>+0x1261abf
   at System.Reflection.DynamicInvokeInfo.Invoke(Object thisPtr, IntPtr methodToCall, Object[] parameters, BinderBundle binderBundle, Boolean wrapInTargetInvocationException) + 0xcf
----- Inner Stack Trace -----
   at System.Reflection.Runtime.MethodInfos.RuntimeNamedMethodInfo`1.GetUncachedMethodInvoker(RuntimeTypeInfo[] methodArguments, MemberInfo exceptionPertainant) + 0x2f
   at System.Reflection.Runtime.MethodInfos.RuntimeNamedMethodInfo`1.MakeGenericMethod(Type[] typeArguments) + 0x18e
   at System.Xml.Serialization.ReflectionXmlSerializationReader.GetSetMemberValueDelegate(Object o, String memberName) + 0x1a2
   at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteLiteralStructMethod(StructMapping structMapping, Boolean isNullable, Boolean checkType, String defaultNamespace) + 0xa6c
   at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteElement(ElementAccessor element, Boolean checkSpecified, Boolean checkForNull, Boolean readOnly, String defaultNamespace, Int32 fixupIndex, Int32 elementIndex, XmlSerializationReader.Fixup fixup, ReflectionXmlSerializationReader.Member member) + 0x4b8
   at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElementsIf(ReflectionXmlSerializationReader.Member[] expectedMembers, ReflectionXmlSerializationReader.Member anyElementMember, UnknownNodeAction elementElseAction, XmlSerializationReader.Fixup fixup, ReflectionXmlSerializationReader.CheckTypeSource checkTypeSource) + 0x2e0
   at System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateTypeElement(XmlTypeMapping xmlTypeMapping) + 0x1a7
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) + 0x132
[FAIL] XmlSerializerTests.Xml_TypeWithTimeSpanProperty
System.InvalidOperationException : There is an error in XML document (2, 2).
---- System.NotSupportedException : 'System.Xml.Serialization.ReflectionXmlSerializationReaderHelper.GetSetMemberValueDelegateWithType[TypeWithTimeSpanProperty,System.TimeSpan](System.Reflection.MemberInfo)' is missing native code. MethodInfo.MakeGenericMethod() is not compatible with AOT compilation. Inspect and fix AOT related warnings that were generated when the app was published. For more information see https://aka.ms/nativeaot-compatibility
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) + 0x291
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream) + 0x9c
   at XmlSerializerTests.SerializeAndDeserialize[T](T value, String baseline, Func`1 serializerFactory, Boolean skipStringCompare, XmlSerializerNamespaces xns) + 0x21b
   at XmlSerializerTests.Xml_TypeWithTimeSpanProperty() + 0x4a
   at System.Private.Xml.Tests!<BaseAddress>+0x1261abf
   at System.Reflection.DynamicInvokeInfo.Invoke(Object thisPtr, IntPtr methodToCall, Object[] parameters, BinderBundle binderBundle, Boolean wrapInTargetInvocationException) + 0xcf
----- Inner Stack Trace -----
   at System.Reflection.Runtime.MethodInfos.RuntimeNamedMethodInfo`1.GetUncachedMethodInvoker(RuntimeTypeInfo[] methodArguments, MemberInfo exceptionPertainant) + 0x2f
   at System.Reflection.Runtime.MethodInfos.RuntimeNamedMethodInfo`1.MakeGenericMethod(Type[] typeArguments) + 0x18e
   at System.Xml.Serialization.ReflectionXmlSerializationReader.GetSetMemberValueDelegate(Object o, String memberName) + 0x1a2
   at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteLiteralStructMethod(StructMapping structMapping, Boolean isNullable, Boolean checkType, String defaultNamespace) + 0xa6c
   at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteElement(ElementAccessor element, Boolean checkSpecified, Boolean checkForNull, Boolean readOnly, String defaultNamespace, Int32 fixupIndex, Int32 elementIndex, XmlSerializationReader.Fixup fixup, ReflectionXmlSerializationReader.Member member) + 0x4b8
   at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElementsIf(ReflectionXmlSerializationReader.Member[] expectedMembers, ReflectionXmlSerializationReader.Member anyElementMember, UnknownNodeAction elementElseAction, XmlSerializationReader.Fixup fixup, ReflectionXmlSerializationReader.CheckTypeSource checkTypeSource) + 0x2e0
   at System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateTypeElement(XmlTypeMapping xmlTypeMapping) + 0x1a7
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) + 0x132
[FAIL] XmlSerializerTests.XML_TypeWithFieldsOrdered
System.InvalidOperationException : There is an error in XML document (2, 2).
---- System.NotSupportedException : 'System.Xml.Serialization.ReflectionXmlSerializationReaderHelper.GetSetMemberValueDelegateWithType[SerializationTypes.TypeWithFieldsOrdered,System.Int32](System.Reflection.MemberInfo)' is missing native code. MethodInfo.MakeGenericMethod() is not compatible with AOT compilation. Inspect and fix AOT related warnings that were generated when the app was published. For more information see https://aka.ms/nativeaot-compatibility
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) + 0x291
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream) + 0x9c
   at XmlSerializerTests.SerializeAndDeserialize[T](T value, String baseline, Func`1 serializerFactory, Boolean skipStringCompare, XmlSerializerNamespaces xns) + 0x21b
   at XmlSerializerTests.XML_TypeWithFieldsOrdered() + 0x6b
   at System.Private.Xml.Tests!<BaseAddress>+0x1261abf
   at System.Reflection.DynamicInvokeInfo.Invoke(Object thisPtr, IntPtr methodToCall, Object[] parameters, BinderBundle binderBundle, Boolean wrapInTargetInvocationException) + 0xcf
----- Inner Stack Trace -----
   at System.Reflection.Runtime.MethodInfos.RuntimeNamedMethodInfo`1.GetUncachedMethodInvoker(RuntimeTypeInfo[] methodArguments, MemberInfo exceptionPertainant) + 0x2f
   at System.Reflection.Runtime.MethodInfos.RuntimeNamedMethodInfo`1.MakeGenericMethod(Type[] typeArguments) + 0x18e
   at System.Xml.Serialization.ReflectionXmlSerializationReader.GetSetMemberValueDelegate(Object o, String memberName) + 0x1a2
   at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteLiteralStructMethod(StructMapping structMapping, Boolean isNullable, Boolean checkType, String defaultNamespace) + 0xa6c
   at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteElement(ElementAccessor element, Boolean checkSpecified, Boolean checkForNull, Boolean readOnly, String defaultNamespace, Int32 fixupIndex, Int32 elementIndex, XmlSerializationReader.Fixup fixup, ReflectionXmlSerializationReader.Member member) + 0x4b8
   at System.Xml.Serialization.ReflectionXmlSerializationReader.WriteMemberElementsIf(ReflectionXmlSerializationReader.Member[] expectedMembers, ReflectionXmlSerializationReader.Member anyElementMember, UnknownNodeAction elementElseAction, XmlSerializationReader.Fixup fixup, ReflectionXmlSerializationReader.CheckTypeSource checkTypeSource) + 0x2e0
   at System.Xml.Serialization.ReflectionXmlSerializationReader.GenerateTypeElement(XmlTypeMapping xmlTypeMapping) + 0x1a7
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) + 0x132
```

**Comment by filipnavara** [comment] 2022-09-22 16:23
Duplicate of https://github.com/dotnet/runtime/issues/75699#issuecomment-1249930017

**Closed** 2022-09-22 16:29 UTC
Labels: area-Serialization, untriaged
