### ISSUE TITLE
Loading of XML files fails when using prefix for long paths

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#59122] opened 2021-09-14 23:57 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Loading-of-XML-files-fails-when-using-pr/1517831)._

---
Hi!
When I try to load a XML file using a long path prefix (\\?\) an exception is thrown (Invalid URI: The hostname could not be parsed).
This happens with .NET framework 4.7.2 and 5.0. I asssume that this also happend with other versions of the framework.
Steps to reproduce:
XmlDocument doc = new XmlDocument();
doc. Load(@"\\?\d:\test.xml");

There are workarounds, but this problem should be fixed in all frameworks.
Cheers
Alex

---
#### Feedback Bot on 8/31/2021, 02:28 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by icnocop** [comment] 2022-01-20 01:19
The long path string should be prefixed with a double back slash.

For example, `var path = @"\\?\C:\long\paht\to\file\myxml.xml";`

If that still doesn't work, you can also try the work-around mentioned [here](https://stackoverflow.com/a/66062886/90287):
```
var path = @"\\?\C:\long\paht\to\file\myxml.xml";
var xmlDoc = new System.Xml.XmlDocument();
FileStream fs = File.Open(path, FileMode.Open);
xmlDoc.Load(fs);
```

**Comment by krwq** [comment] 2022-02-17 12:26
I'm closing this as by design. Please open a new issue in this repo if there is some more information (answering on closed issue might potentially get missed)

**Closed by krwq** 2022-02-17 12:26 UTC
Labels: area-System.Xml
