### ISSUE TITLE
For polymorphic deserialization, the type discriminator property cannot be set to required.

### ISSUE THREAD

**Issue by aetos382** [dotnet/runtime#110248] opened 2024-11-28 17:18 UTC
### Description

When using `JsonSerializer` to perform polymorphic deserialization, an exception will be thrown if the type discriminator property is required.

### Reproduction Steps

```cs
using System.Text.Json;
using System.Text.Json.Serialization;

const string json = """
                    { "type": "derived" }
                    """;

try
{
    var data = JsonSerializer.Deserialize(json, DataSerializerContext.Default.Base);
    Console.WriteLine(data);
}
catch (Exception ex)
{
    Console.Error.WriteLine(ex);
}

[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(Derived), "derived")]
abstract class Base
{
    [JsonRequired]
    public DataType Type { get; init; }
}

sealed class Derived : Base
{
}

enum DataType
{
    Derived
}

[JsonSourceGenerationOptions(JsonSerializerDefaults.Web)]
[JsonSerializable(typeof(Base))]
[JsonSerializable(typeof(Derived))]
sealed partial class DataSerializerContext : JsonSerializerContext;
```

### Expected behavior

Can be deserialized successfully.

### Actual behavior

An exception has occurred.

```
System.Text.Json.JsonException: JSON deserialization for type 'Derived' was missing required properties including: 'type'.
   at System.Text.Json.ThrowHelper.ThrowJsonException_JsonRequiredPropertyMissing(JsonTypeInfo parent, BitArray requiredPropertiesSet)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.OnTryReadAsObject(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, Object& value)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, T& value, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Deserialize(Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonTypeInfo`1 jsonTypeInfo)
   at Program.<Main>$(String[] args) in D:\Source\Repos\ConsoleApp1\ConsoleApp1\Program.cs:line 10
```

### Known Workarounds

Deserialization will be successful if changed as follows.

Specify a concrete type.
```cs
var data = JsonSerializer.Deserialize(json, DataSerializerContext.Default.Derived);
```

Or, remove the `[JsonRequired]` attribute from `Type`.
```cs
// [JsonRequired]
public DataType Type { get; init; }
```

There is also the following method for determining the actual type in code.

```cs
[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(Derived), "derived")]
abstract class Base
{
    [JsonIgnore]
    public abstract DataType Type { get; }
}

sealed class Derived : Base
{
    public override DataType Type => DataType.Derived;
}
```
Or
```cs
[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(Derived), "derived")]
abstract class Base
{
    // remove Type
}

sealed class Derived : Base
{
}

if (data is Derived d) { ... }
```

### Configuration

.NET 9.0
Windows 11 24H2
x64

**Comment by pinkfloydx33** [comment] 2024-11-28 19:46
I'm pretty sure that treating the discriminator as a proper property is still not a supported scenario, meaning you can't customize it (which is what JsonRequired would do). Though I might be wrong. 

https://github.com/dotnet/runtime/issues/79933#issuecomment-1823524599

I believe it's treated as a metadata property.  You end up with a real property (on your class) and a metadata property with the same name, the latter taking priority. I think it used to be the case that it wouldn't even deserialize into the object (see my comment in link, we had to come up with all sorts of workarounds)

**Comment by aetos382** [comment] 2024-11-29 01:42
> The fact it has a setter implies you can change the underlying type by changing the value, which wouldn't make sense.
(from https://github.com/dotnet/runtime/issues/79933#issuecomment-1363976026)

It is true that the type discriminator property should be read-only. But that can be achieved by making the property get-only or init-only, which is a separate issue from the deserializer not supporting it.

However, if I want to identify the type, I can do it like this, so the importance of this problem is not high.

```cs
[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(Derived), "derived")]
abstract class Base
{
    [JsonIgnore]
    public abstract DataType Type { get; }
}

sealed class Derived : Base
{
    public override DataType Type => DataType.Derived;
}
```
OR
```cs
if (data is Derived d) { ... }
```

**Comment by eiriktsarpalis** [comment] 2024-11-29 12:42
Essentially a duplicate of https://github.com/dotnet/runtime/issues/72170. Reusing type discriminator property names for object properties isn't supported, yet the STJ doesn't validate for this. What you're observing is undefined behaviour because this validation is not taking place.

**Closed by eiriktsarpalis** 2024-11-29 12:42 UTC
Labels: area-System.Text.Json, untriaged
