### ISSUE TITLE
Test failure profiler\\transitions\\transitions\\transitions.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#66049] opened 2022-03-02 01:27 UTC
Run: [runtime-coreclr outerloop 20220301.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1638161&view=ms.vss-test-web.build-test-results-tab&runId=45340328&resultId=100159&paneView=debug)

Failed test:
```
R2R-CG2 windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open

- profiler\\transitions\\transitions\\transitions.cmd
```
**Error message:**
```
Could Not Find C:\h\w\AC2F0917\w\ACF809D6\e\profiler\transitions\transitions\IL-CG2\composite-r2r.dll
Could Not Find C:\h\w\AC2F0917\w\ACF809D6\e\profiler\transitions\transitions\common.dll.rsp
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'System.Security.Cryptography.Primitives, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The module was expected to contain an assembly manifest.
File name: 'System.Security.Cryptography.Primitives, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
at ILCompiler.CoreRTNameMangler.SanitizeNameWithHash(String literal)
at ILCompiler.CoreRTNameMangler.set_CompilationUnitPrefix(String value)
at ILCompiler.Program.RunSingleCompilation(Dictionary2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary2 unrootedInputFilePaths, HashSet`1 versionBubbleModulesHash, CompilerTypeSystemContext typeSystemContext)
at ILCompiler.Program.Run(String[] args)
at ILCompiler.Program.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\AC2F0917\w\ACF809D6\uploads\Reports\profiler.transitions\transitions\transitions.output.txt
Raw output:
BEGIN EXECUTION
common.dll
Profiler.dll
profiler_common.dll
TestLibrary.dll
transitions.dll
5 file(s) copied.
Response file: C:\h\w\AC2F0917\w\ACF809D6\e\profiler\transitions\transitions\common.dll.rsp
C:\h\w\AC2F0917\w\ACF809D6\e\profiler\transitions\transitions\IL-CG2\common.dll
-o:C:\h\w\AC2F0917\w\ACF809D6\e\profiler\transitions\transitions\common.dll
--targetarch:x64
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\AC2F0917\p\System..dll
-r:C:\h\w\AC2F0917\p\Microsoft..dll
-r:C:\h\w\AC2F0917\p\mscorlib.dll
-r:C:\h\w\AC2F0917\p\netstandard.dll
-O
" "dotnet" "C:\h\w\AC2F0917\p\crossgen2\crossgen2.dll" @"C:\h\w\AC2F0917\w\ACF809D6\e\profiler\transitions\transitions\common.dll.rsp"   -r:C:\h\w\AC2F0917\w\ACF809D6\e\profiler\transitions\transitions\IL-CG2*.dll"
Crossgen2 failed with exitcode - -532462766
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\AC2F0917\p
C:\h\w\AC2F0917\w\ACF809D6\e\profiler\transitions\transitions\transitions.cmd
Expected: True
Actual:   False


Stack trace
   at profiler_transitions._transitions_transitions_._transitions_transitions_cmd()
```

**Comment by trylek** [comment] 2022-04-04 20:27
Closing as duplicate of: https://github.com/dotnet/runtime/issues/65646

**Closed by trylek** 2022-04-04 20:27 UTC
Labels: os-windows, arch-x64, area-crossgen2-coreclr, untriaged, blocking-outerloop
