### ISSUE TITLE
TimeZoneInfo.FindSystemTimeZoneById() doesn't always return correct UTC time offset  

### ISSUE THREAD

**Issue by KostaVlev** [dotnet/runtime#79860] opened 2022-12-20 17:15 UTC
I have API application hosted on Azure where we convert time to UTC using specified time zone with the following code

```
_ = DateTime.TryParse("2022-12-23T00:00:00", out DateTime result);
var timeZoneInfo = TimeZoneInfo.FindSystemTimeZoneById("Central Standard Time");

var utcTime = TimeZoneInfo.ConvertTimeToUtc(DateTime.SpecifyKind(result, DateTimeKind.Unspecified), timeZoneInfo);
```

I expect the `utcTime` to be `2022-12-23T06:00:00Z` but randomly we get back  `2022-12-23T05:00:00Z` 

The azure app service has not specified time zone and it's using the default UTC, the app location is East US.

I have tried other time zones and it is randomly returning   `2022-12-23T05:00:00Z`. I expected always to get back the specified time zone UTC offset

**Comment by tarekgh** [comment] 2023-01-11 19:10
Will be hard to tell without some repro or more data. I suspect the time zone data on the running machine somehow is not correct or not updated. I suggest if you can add more logging info when the problem is happening. Something like, the OS version, and the dump of the time zone data. Here is some code that may help get the information.

By that, I am closing the issue but feel free ping back when you have more information, and we can reopen the issue.

```C#
        public static void DumpTimeZoneRules(TimeZoneInfo tzi)
        {
            Console.WriteLine($" ------------- Id: {tzi.Id} ");
            Console.WriteLine($" ------------- DisplayName: {tzi.DisplayName}");
            Console.WriteLine($" ------------- BaseUtcOffset: {tzi.BaseUtcOffset} -----------------------");

            Console.WriteLine(" ------------- Public Rules   -----------------------");
            foreach (var rule in tzi.GetAdjustmentRules())
            {
                DumpAdjustmentRule(rule);
            }
            Console.WriteLine(" ------------- Internal Rules -----------------------");
            foreach (TimeZoneInfo.AdjustmentRule rule in (TimeZoneInfo.AdjustmentRule[])tzi.GetType().GetField("_adjustmentRules", BindingFlags.Instance | BindingFlags.NonPublic)!.GetValue(tzi)!)
            {
                DumpAdjustmentRule(rule);
            }
        }

        public static void DumpAdjustmentRule(TimeZoneInfo.AdjustmentRule rule)
        {
            Console.WriteLine($"DateStart                  : {rule.DateStart} ({rule.DateStart.Kind})");
            Console.WriteLine($"DateEnd                    : {rule.DateEnd} ({rule.DateEnd.Kind})");
            Console.WriteLine($"DaylightDelta              : {rule.DaylightDelta}");

            Console.WriteLine($"DaylightTransitionStart    : M:{rule.DaylightTransitionStart.Month}, D:{rule.DaylightTransitionStart.Day}, W:{rule.DaylightTransitionStart.Week}, DoW:{rule.DaylightTransitionStart.DayOfWeek}, Time:{rule.DaylightTransitionStart.TimeOfDay}, FixedDate:{rule.DaylightTransitionStart.IsFixedDateRule}");
            Console.WriteLine($"DaylightTransitionEnd      : M:{rule.DaylightTransitionEnd.Month}, D:{rule.DaylightTransitionEnd.Day}, W:{rule.DaylightTransitionEnd.Week}, DoW:{rule.DaylightTransitionEnd.DayOfWeek}, Time:{rule.DaylightTransitionEnd.TimeOfDay}, FixedDate:{rule.DaylightTransitionEnd.IsFixedDateRule}");

            // Console.WriteLine($"BaseUtcOffsetDelta         : {rule.BaseUtcOffsetDelta}");
            Console.WriteLine($"BaseUtcOffsetDelta         : {rule.GetType().GetProperty("BaseUtcOffsetDelta", BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)!.GetValue(rule)!}");
            Console.WriteLine($"NoDaylightTransitions      : {rule.GetType().GetProperty("NoDaylightTransitions", BindingFlags.Instance | BindingFlags.NonPublic)!.GetValue(rule)!}");
            Console.WriteLine($"------------------------------------------------------------------------------------------------------------------------------------------------------------");
        }
```

**Closed by tarekgh** 2023-01-11 19:10 UTC
Labels: untriaged, area-System.DateTime
