### ISSUE TITLE
Environment Variables not in IConfiguration

### ISSUE THREAD

**Issue by devhl-labs** [dotnet/runtime#67434] opened 2022-03-28 19:19 UTC
### Description

When I run this program in Visual Studio, the secrets are loaded from environment variables just fine. When running Entity Framework database update, then the secrets are not loaded from environment variables. I'm not positive where this issue belongs, but I reported a similar issue here regarding user secrets not always loading. 

https://github.com/devhl-labs/EF-EnvVar-Test

### Reproduction Steps

Create an environment variable called ConnectionStrings__Fizz with any value.

Restart Visual Studio to ensure the environment variable is populated. 

Run the program in Visual Studio. Notice that variables connection and connection2 are populated. 

Comment out connection2
Then run `dotnet ef database update --verbose` and notice that connection is not null. There will be an error here, but it is expected since our connection string is not valid.

Comment out connection, uncomment connection2
Then run `dotnet ef database update --verbose` and notice that connection2 is null.

### Expected behavior

connection2 is not null when running database update command.

### Actual behavior

connection2 is null when running database update command.

**Comment by eerhardt** [comment] 2022-04-06 21:40
I can't reproduce this issue. Setting the environment variable and running `dotnet ef database update --verbose` produces:

```
System.ArgumentException: Format of the initialization string does not conform to specification starting at index 0.
   at System.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer, Boolean useOdbcRules, String& keyname, String& keyvalue)
   at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey)
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms, Boolean useOdbcRules)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
```

Are you sure you are running the command from a command prompt with the environment variable set?

I'm going to close this issue as "no repro". If you find more information, please let us know and reopen.

**Closed by eerhardt** 2022-04-06 21:40 UTC
Labels: untriaged, area-Extensions-Configuration
