### ISSUE TITLE
The dynamic type created is thrown FileLoadException when using the GetCustomAttributes method

### ISSUE THREAD

**Issue by kwkaiwang** [dotnet/runtime#67802] opened 2022-04-09 12:14 UTC
Which version of .NET you have tested on: Version: 6.0.3;  Commit:  c24d9a9c91
Which OS and architecture were you using: Windows 11 x64
Expected result: System.Reflection.CustomAttribute.GetCustomAttributes works with dynamic Type (AssemblyBuilder/ModuleBuilder).
Actual result: FileLoadException

The issue seems related to System.Reflection.Emit.AssemblyBuilder.Location

~~~cs
       // System.Reflection.Emit.AssemblyBuilder
	public override string Location
	{
		get
		{
			throw new NotSupportedException(SR.NotSupported_DynamicAssembly);
		}
	}
~~~

The Location property was being used by System.Reflection.Assembly.LoadFromResolveHandler which triggers FileLoadException

~~~cs
// System.Reflection.Assembly
private static Assembly LoadFromResolveHandler(object sender, ResolveEventArgs args)
{
	//...
	string fullPath = Path.GetFullPath(requestingAssembly.Location);
	//...
}
~~~

Call Stack
```
System.IO.FileLoadException
  HResult=0x80131515
  Message=Could not load file or assembly 'ODataExtensionec551e7e1c3540a1b486e4be222060dc, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Operation is not supported. (0x80131515)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
   at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, RuntimeType type, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, Boolean inherit)
   at System.Reflection.RuntimeMethodInfo.GetCustomAttributes(Boolean inherit)
   at Microsoft.AspNetCore.Mvc.ApplicationModels.DefaultApplicationModelProvider.CreateActionModel(TypeInfo typeInfo, MethodInfo methodInfo)
   at Microsoft.AspNetCore.Mvc.ApplicationModels.DefaultApplicationModelProvider.OnProvidersExecuting(ApplicationModelProviderContext context)
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelFactory.CreateApplicationModel(IEnumerable`1 controllerTypes)
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.UpdateCollection()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.Initialize()
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.<>c__DisplayClass11_0.<Subscribe>b__0()
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.Subscribe()
   at Microsoft.AspNetCore.Mvc.Routing.ControllerActionEndpointDataSource..ctor(ControllerActionEndpointDataSourceIdProvider dataSourceIdProvider, IActionDescriptorCollectionProvider actions, ActionEndpointFactory endpointFactory, OrderedEndpointsSequenceProvider orderSequence)
   at Microsoft.AspNetCore.Builder.ControllerEndpointRouteBuilderExtensions.GetOrCreateDataSource(IEndpointRouteBuilder endpoints)
   at Microsoft.AspNetCore.Builder.ControllerEndpointRouteBuilderExtensions.MapControllers(IEndpointRouteBuilder endpoints)
   at Program.Main(String[] args) in C:\src\herbalife\hlfdmp\api\DataPlatform.Api\Program.cs:line 71

  This exception was originally thrown at this call stack:
    System.Reflection.Emit.InternalAssemblyBuilder.Location.get()
    System.Reflection.Assembly.LoadFromResolveHandler(object, System.ResolveEventArgs)
    System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(System.ResolveEventHandler, System.Reflection.RuntimeAssembly, string)
    System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(System.Reflection.RuntimeAssembly, string)

Inner Exception 1:
NotSupportedException: The invoked member is not supported in a dynamic assembly.

```

Related issue: https://github.com/dotnet/runtime/issues/26912

**Comment by am11** [comment] 2022-04-09 12:21
@kwkaiwang, please provide additional details:
* which version of .NET you have tested on
* which OS and architecture were you using
* Expected result
* Actual result

**Comment by jkotas** [comment] 2022-04-09 15:40
> System.Reflection.Emit.InternalAssemblyBuilder.Location.get()
> NotSupportedException: The invoked member is not supported in a dynamic assembly.

This was likely fixed by #64662 that deleted `InternalAssemblyBuilder`. Any chance you can try this on [.NET 7 preview](https://dotnet.microsoft.com/en-us/download/dotnet/7.0)?

**Comment by kwkaiwang** [comment] 2022-04-10 02:14
.NET 6 is expected, the fix/workaround is needed for production environment.

**Comment by jkotas** [comment] 2022-04-10 05:43
Where is the event handler that is responsible for resolving `ODataExtensionec551e7e1c3540a1b486e4be222060dc` assembly registered? The simplest workaround may be to register this event handler before the `LoadFromResolveHandler` event handler.

**Comment by kwkaiwang** [comment] 2022-04-10 08:16
The event handler seems inside CLR runtime:

System.Reflection.CustomAttribute._CreateCaObjec (C++ method)
  --> ...
  --> System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve
  --> ... System.Reflection.Assembly.LoadFromResolveHandler
  --> System.Reflection.Emit.InternalAssemblyBuilder.Location

~~~cs
// System.Reflection.Assembly
public static Assembly LoadFrom(string assemblyFile)
{	//...
	if (!s_loadFromHandlerSet)
	{
		lock (s_loadFromAssemblyList)
		{
			if (!s_loadFromHandlerSet)
			{
				AssemblyLoadContext.AssemblyResolve += LoadFromResolveHandler;
				s_loadFromHandlerSet = true;
			}
		}
	}
	//...
}
~~~

The dynamic types were already built in memory with AssemblyBuilder/ModuleBuilder, I am curious on why assembly resolve was called again.

### More background about dynamic assembly ODataExtension{guid}

This dynamic assembly will:
1. Build dynamic EF Core types by reading SQL database schemas (table/view). For example, `NorthwindDbContext` with `DbSet<Product>` , `DbSet<Customer>`  included.
2. Build dynamic REST/OData API controllers like `ProductController`, `CustomerControllers `.
3. Build dynamic 'Get' method with customize arributes:
- Succeeded: [HttpGetAttrobite("{id}")]
- Succeeded: [EnableQueryAttribute]
- Failed: `[ProducesResponseType(`modelType`, StatusCodes.Status200OK)]`(related to this bug). Here `modelType`is a dynamic type built from step 1.

Code fragment:
~~~cs
var attributeCtor = typeof(ProducesResponseTypeAttribute).GetConstructor(new Type[] { typeof(Type), typeof(int) });
CustomAttributeBuilder producesResponseTypeAttribute = new CustomAttributeBuilder(attributeCtor, new object[] { modelType), 200 }); 
methodBuilder.SetCustomAttribute(producesResponseTypeAttribute);
~~~

**Comment by jkotas** [comment] 2022-04-10 15:59
> The dynamic types were already built in memory with AssemblyBuilder/ModuleBuilder, I am curious why OnAssemblyResolve was called this case.

Yes, it does not look right that OnAssemblyResolve was called in this case. 

My guess is that the problem is caused by mixing types from different assembly load contexts.

**Comment by kwkaiwang** [comment] 2022-04-11 03:21
Tried .NET 7 Preview, got ArgumentException: The path is empty. (Parameter 'path') 

~~~txt
System.IO.FileLoadException
  HResult=0x80070057
  Message=Could not load file or assembly 'DynamicDbContext4184e98c13f74b89bea9e6a3422ab675, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The parameter is incorrect. (0x80070057 (E_INVALIDARG))
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
   at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, RuntimeType type, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, Boolean inherit)
   at Microsoft.AspNetCore.Mvc.ApplicationModels.DefaultApplicationModelProvider.CreateActionModel(TypeInfo typeInfo, MethodInfo methodInfo)
   at Microsoft.AspNetCore.Mvc.ApplicationModels.DefaultApplicationModelProvider.OnProvidersExecuting(ApplicationModelProviderContext context)
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ApplicationModelFactory.CreateApplicationModel(IEnumerable`1 controllerTypes)
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.UpdateCollection()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.Initialize()
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.<>c__DisplayClass11_0.<Subscribe>b__0()
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.Subscribe()
   at Microsoft.AspNetCore.Builder.ControllerEndpointRouteBuilderExtensions.GetOrCreateDataSource(IEndpointRouteBuilder endpoints)
   at Microsoft.AspNetCore.Builder.ControllerEndpointRouteBuilderExtensions.MapControllers(IEndpointRouteBuilder endpoints)
   at Program.Main(String[] args) in C:\src\herbalife\hlfdmp\api\DataPlatform.Api\Program.cs:line 71

  This exception was originally thrown at this call stack:
    System.IO.Path.GetFullPath(string)
    System.Reflection.Assembly.LoadFromResolveHandler(object, System.ResolveEventArgs)
    System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(System.ResolveEventHandler, System.Reflection.RuntimeAssembly, string)

Inner Exception 1:
ArgumentException: The path is empty. (Parameter 'path')
~~~

**Closed** 2022-04-12 12:59 UTC
Labels: area-System.Reflection.Emit, needs-further-triage, in-pr
