### ISSUE TITLE
Access checks in JIT interface methods

### ISSUE THREAD

**Issue by nattress** [dotnet/runtime#13392] opened 2019-07-22 20:29 UTC
The final section of `CEEInfo::getCallInfo` (https://github.com/dotnet/coreclr/blob/5f93d3b1c48ba6916d5f31d79cb7c17d564eecef/src/vm/jitinterface.cpp#L5597) deals with access checks validating the declarative authority of a given caller to call the callee. This is currently missing in the CPAOT compiler. Similar checks needed in `CEEInfo::getFieldInfo`.

**Comment by davidwrighton** [comment] 2020-07-10 22:39
This isn't needed for the 5.0 release.

**Comment by trylek** [comment] 2021-02-07 21:10
I believe we need to either address this for the .NET 6 shipping release or at least convince ourselves that we don't need to. I think we do because silently violating access rights while emitting the R2R native image violates the principle of R2R vs. JIT equivalence. @jkotas, could you please correct me if I'm wrong?

**Comment by jkotas** [comment] 2021-02-08 05:55
Violating visibility rules is invalid IL. In general, invalid IL can lead to observable behavior difference between AOT and JIT, or between optimization levels. These differences are by design.

I think that this is nice-to-fix. We should look at it together with all other types of invalid IL detection we can be doing. I think it would be fine to implement these additional checks reactively, only once somebody reports them as a problem.

**Comment by mangod9** [comment] 2021-07-10 00:25
moving to 7 based on the discussion above.

**Comment by davidwrighton** [comment] 2022-07-06 17:03
We don't need these.

**Closed by davidwrighton** 2022-07-06 17:03 UTC
Labels: area-crossgen2-coreclr
