### ISSUE TITLE
`System.Text.Json.SourceGeneration.Roslyn3.11.Tests` crashes due to an assertion on linux/arm64/debug

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#65817] opened 2022-02-24 01:05 UTC
Hit this on https://github.com/dotnet/runtime/pull/65752 .[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1628957&view=logs&jobId=e975a271-b4f2-514d-430d-2bcd66f2ec79&j=3f95ca23-483b-5dc9-4b05-6bd24fb925c2&t=0c1dd9d1-4ef7-54d5-2d62-e4ab330605ca).

```
=================================================================
	Native stacktrace:
=================================================================
	0x7f9518ccbc - Unknown

Unhandled Exception:
System.Diagnostics.DebugProvider+DebugAssertException:    at System.Diagnostics.DebugProvider.Fail(String message, String detailMessage) in /_/src/libraries/System.Private.CoreLib/src/System/Diagnostics/DebugProvider.cs:line 22
   at System.Diagnostics.Debug.Fail(String message, String detailMessage) in /_/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Debug.cs:line 131
   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage) in /_/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Debug.cs:line 95
   at System.Diagnostics.Debug.Assert(Boolean condition) in /_/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Debug.cs:line 80
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.InitializePropCache() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.Cache.cs:line 574
...
```

**Comment by radical** [comment] 2022-03-05 02:37
Hit this again for [System.Text.Json.SourceGeneration.Roslyn4.0.Tests](https://dev.azure.com/dnceng/public/_build/results?buildId=1645913&view=logs&j=3f95ca23-483b-5dc9-4b05-6bd24fb925c2&t=0c1dd9d1-4ef7-54d5-2d62-e4ab330605ca).

**Comment by krwq** [comment] 2022-03-07 10:46
Note this is about `Debug.Assert(PropertyCache == null);` in `InitializePropCache`

I think this assert is just bogus and should be removed. I assume scenario of re-using same options on multiple threads is a valid one and that could create such problem. The worst case scenario we will double initialize PropertyCache. I'm not sure it makes sense to lock it - at least cannot immediately see anything which could break. Same goes for the similar assert in the `InitializeParameterCache`

@eiriktsarpalis @layomia?

**Comment by eiriktsarpalis** [comment] 2022-03-07 14:36
I think we should make sure that the instance is initialized before it can be shared across multiple threads.

**Comment by radical** [comment] 2022-03-25 21:31
Hit again - https://dev.azure.com/dnceng/public/_build/results?buildId=1682418&view=logs&jobId=3f95ca23-483b-5dc9-4b05-6bd24fb925c2&j=3f95ca23-483b-5dc9-4b05-6bd24fb925c2&t=0c1dd9d1-4ef7-54d5-2d62-e4ab330605ca

**Comment by eiriktsarpalis** [comment] 2022-03-28 16:20
Duplicate of #60962

**Closed by eiriktsarpalis** 2022-03-28 16:20 UTC
Labels: bug, area-System.Text.Json, blocking-clean-ci
