### ISSUE TITLE
BadImageFormatException when calling both C++\CLI on .NET FW 4.8 and C++\CLI on .NET 5 from same C++ project

### ISSUE THREAD

**Issue by bairog** [dotnet/runtime#65604] opened 2022-02-18 11:49 UTC
Preambula:
Our product is written on C++ and C# so we have to widely use C++\CLI to interop between languages.
We have migrated most of our code from .NET Framework 4.8 to .NET 5 but some projects cannot be migrated because of third-party controls that exist only for .NET Framework 4.x. So one part of our code targets .NET Framework 4.8, some other part - .NET 5.
And sometimes it is both called from C++ code.

I have a test solution with the following structure:

- **Crosscutting_C++CLI_NFW48.dll** - .NET Framework 4.8 C++\CLI wrapper that get some configuration data from C++. Compiled  as **x86, Multi-byte Character Set, wchar_t-**.
- **ClassLibrary_NFW48.dll** (references **Crosscutting_C++CLI_NFW48.dll**) - .NET Framework 4.8 class library , compiled as **x86**.
- **ClassLibrary_NFW48_Interop.dll** (references **ClassLibrary_NFW48.dll**) - .NET Framework 4.8 C++\CLI wrapper. Compiled  as **x86, Multi-byte Character Set, wchar_t-**.  Exports a function via `extern "C" __declspec(dllexport)`.
- **ClassLibrary_NET5.dll** (references **Crosscutting_C++CLI_NFW48.dll**) - .NET 5.0.14 class library , compiled as **x86**.
- **ClassLibrary_NET5_Interop.dll** (references **ClassLibrary_NET5.dll**) - .NET 5.0.14 C++\CLI wrapper. Compiled  as **x86, Multi-byte Character Set, wchar_t-**. Exports a function via `extern "C" __declspec(dllexport)`.
- **C++CLI_NFW48_and_NET5_Mix_Test.exe** - C++ console test application. Compiled  as **x86, Multi-byte Character Set, wchar_t-**. Performs `LoadLibrary`, then `GetProcAdress` and finally calls functions from **ClassLibrary_NFW48_Interop.dll** and after that **ClassLibrary_NET5_Interop.dll**. I perform `FreeLibrary` after each function call.

When I debug **ClassLibrary_NET5.dll** (by starting **C++CLI_NFW48_and_NET5_Mix_Test.exe**) it throws an exception:

> System.BadImageFormatException: 'Could not load file or assembly 'Crosscutting_C++CLI_NFW48, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. 

**NB!** If I change call order (first load **ClassLibrary_NET5_Interop.dll** and then **ClassLibrary_NFW48_Interop.dll**) - the problem goes away

Sample repo - https://github.com/bairog/C-CLI_NFW48_and_NET5_Mix_Test
Compile it and start debugging **ClassLibrary_NET5** project (it starts **C++CLI_NFW48_and_NET5_Mix_Test** in project Debug settings)

### Version information
Target framework: .NET 5.0.14
Operating system: Windows 10 x64 21H2
IDE: Visual Studio 2019 16.11.10 REL Community

**Comment by AaronRobinsonMSFT** [comment] 2022-02-24 20:02
@bairog There are likely a myriad of issues here. The loading of .NET Framework and .NET Core 3.1/.NET 5+ into the same process is not supported. See https://github.com/dotnet/runtime/issues/53729.

**Comment by vitek-karas** [comment] 2022-02-25 10:58
> But I perform FreeLibrary after each function call (and that should unload runtime)

This is not true for CoreCLR (.NET 5) - the .NET 5 runtime can't be unloaded from a process right now. But this is definitely not the reason for the `BadImageFormatException`. It's just a reason for overall "unsupported" on the scenario.

> So it's ok that ClassLibrary_NET5.dll reference Crosscutting_C++CLI_NFW48.dll - right?

This is very likely a problem - I would have to dig into this, but C++/CLI assembly acts both as managed and native library. The native part has direct native dependency on either .NET 5 or .NET48 (depending on how it was built). So I would expect, that loading .NET48 C++/CLI assembly into .NET 5 also brings in the .NET Framework runtime - in any case, as far as I know this is not something which is meant to work. But I'm no C++/CLI expert - @AaronRobinsonMSFT will probably know better.

**Comment by AaronRobinsonMSFT** [comment] 2022-02-28 03:44
In .NET Core 3.1/.NET 5 any module load failures resulting in a `BadImageFormatException`. This was fixed early in .NET 6 but was mostly a quality of life fix rather than something functionally incorrect. @vitek-karas's statement about dependencies is likely the issue and that should be discoverable using a tool like [ProcMon](https://docs.microsoft.com/sysinternals/downloads/procmon).

I'm going to close this issue since it is relying on SxS behavior that is known to not be supported and the root cause for the `BadImageException` is related to a missing dependency issue that can be resolved using the aforementioned tool. Please let us know if you have additional questions or issues.

**Closed by AaronRobinsonMSFT** 2022-02-28 03:44 UTC
Labels: area-AssemblyLoader-coreclr, untriaged
