### ISSUE TITLE
Very basic findall against list literal is broken.

### ISSUE THREAD

**Issue by affenkonig11b** [dotnet/runtime#59358] opened 2021-09-20 03:25 UTC
The following code is a mock to produce fake data for front-end testing. The service is registered as singleton (irl this is an api) and injected into another client side cache handling singleton service.  The AnimalMocks list shows has having a _size of 6, but 8 _items, 2 of which are null. The .FindAll() returns all 8 _items, but with a _size of 5  (when all 6 are requested). When this is returned to the client side service, it silently fails when converting the response to a dictionary, I believe because of the null items.

Any tips?

```
   public async Task<GenericResponseModel<List<amAnimal>>> GetShallowAnimals(List<int> animalIds, Guid userId)
        {
            await Task.Delay(1000);
            return new GenericResponseModel<List<amAnimal>>(AnimalMocks.FindAll(x => animalIds.Contains(x.AnimalId)));
        }

        private List<amAnimal> AnimalMocks => new List<amAnimal>()
        {
                new amAnimal()
                {
                    AnimalId = 1,
                    BirthDate = DateTime.UtcNow.AddMonths(-32),
                    InitSex = Sex.female,
                    Name = new amAnimalNameInfo() { PrimaryEarTag = GenerateRandomTag() }
                },
                new amAnimal()
                {
                    AnimalId = 2,
                    BirthDate = DateTime.UtcNow.AddMonths(-3),
                    InitSex = Sex.female,
                    Name = new amAnimalNameInfo() { Name = GenerateRandomTag() }
                },
                new amAnimal()
                {
                    AnimalId = 3,
                    BirthDate = DateTime.UtcNow.AddMonths(-9),
                    InitSex = Sex.female,
                    Name = new amAnimalNameInfo() { PrimaryEarTag = GenerateRandomTag() }
                }
                ,
                new amAnimal()
                {
                    AnimalId = 4,
                    BirthDate = DateTime.UtcNow.AddYears(-10),
                    InitSex = Sex.female,
                    Name = new amAnimalNameInfo() { SecondaryEaryTag = GenerateRandomTag() }
                },
                new amAnimal()
                {
                    AnimalId = 5,
                    BirthDate = DateTime.UtcNow.AddMonths(-18),
                    InitSex = Sex.male,
                    Name = new amAnimalNameInfo() { PrimaryEarTag = GenerateRandomTag() }
                },
                new amAnimal()
                {
                    AnimalId = 6,
                    BirthDate = DateTime.UtcNow.AddYears(-1),
                    InitSex = Sex.male,
                    CastrationDate = DateTime.UtcNow.AddDays(-30),
                    Name = new amAnimalNameInfo() { SecondaryEaryTag = GenerateRandomTag() }
                }
        };
```

**Comment by eiriktsarpalis** [comment] 2021-09-20 20:10
> The AnimalMocks list shows has having a _size of 6, but 8 _items, 2 of which are null. The .FindAll() returns all 8 _items

The number 8 here is incidental and really just reflects [the growth function](https://github.com/dotnet/runtime/blob/f807a6bae3eb414fe743f51edcb4cfcfdeead416/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/List.cs#L425) used by `List<T>`. Basically any list between 5 and 8 elements will have a backing array of size 8 (unless a custom capacity is explicitly specified).

> but with a _size of 5 (when all 6 are requested).

This most likely indicates that there might be an issue with your predicate. Could it be that your request does not specify the correct set of id's?

> When this is returned to the client side service, it silently fails when converting the response to a dictionary, I believe because of the null items.

I would dispute that this is caused by uninhabited elements of the `List<T>` backing array. This is implementation detail that does not leak to the public APIs of `List<T>` unless this is somehow accessed using private reflection.

In order to better understand the issue you are facing, we would need a minimal reproduction of the issue. This would require a standalone console application as well as a description of the expected vs. actual behavior of the app.

**Comment by krwq** [comment] 2021-09-27 08:07
@affenkonig11b can you please provide repro showing the issue without using any external components? otherwise we'll need to close the issue as by design as it's not actionable at the moment

**Closed** 2021-11-17 06:01 UTC
Labels: area-System.Collections, needs more info, no recent activity
