### ISSUE TITLE
[API Proposal]: bool System.Reflection.MetadataReader.TryGetString(StringHandle handle, Span<char> span, out int length);

### ISSUE THREAD

**Issue by AArnott** [dotnet/runtime#103169] opened 2024-06-07 16:44 UTC
### Background and motivation

System.Reflection.Metadata is a high performance, low allocation library. Almost everything can be read without allocating memory except for two operations:

1. Decoding signatures
2. Getting strings (e.g. names of identifiers).

This API proposal focuses on eliminating the requirement to allocate memory when obtaining strings.

### API Proposal

```csharp
namespace System.Reflection.Metadata;

public partial class MetadataReader
{
    /// <summary>
    /// Copies the content for a given string into a given buffer.
    /// </summary>
    /// <param name="handle">The handle to the string to obtain.</param>
    /// <param name="span">The buffer to copy the value of the string into.</param>
    /// <param name="length">Receives the length of the string referenced by <paramref name="handle"/>.</param>
    /// <returns><see langword="true" /> if the length of the <paramref name="span"/> is sufficient to contain the entire string; <see langword="false" /> otherwise.</returns>
    /// <remarks>
    /// When <paramref name="span"/> is too small to contain the entire string, the method will return <see langword="false"/> and no part of the string will be copied.
    /// Use the output value of <paramref name="length"/> to allocate a span of sufficient length to contain the entire string and retry.
    /// </remarks>
    public bool TryGetString(StringHandle handle, Span<char> span, out int length);

    /// <inheritdoc cref="TryGetString(StringHandle, Span{char}, out int)"/>
    public bool TryGetString(DocumentNameBlobHandle handle, Span<char> span, out int length);

    /// <inheritdoc cref="TryGetString(StringHandle, Span{char}, out int)"/>
    public bool TryGetString(NamespaceDefinitionHandle handle, Span<char> span, out int length);
}
```

### API Usage

```csharp
using FileStream assemblyStream = File.OpenRead(Assembly.GetExecutingAssembly().Location);
using PEReader peReader = new(this.assemblyStream);
MetadataReader reader = peReader.GetMetadataReader();

StringBuilder allTheNames = new();

Span<char> name = stackalloc char[500];
foreach (TypeDefinitionHandle tdh in reader.TypeDefinitions)
{
    TypeDefinition typeDef = reader.GetTypeDefinition(tdh);
    if (reader.TryGetString(typeDef.Name, name, out int length))
    {
        allTheNames.Append(name[..length]);
    }
    else 
    {
        char[] rented = ArrayPool<char>.Shared.Rent(length);
        reader.TryGetString(typeDef.Name, rented, out length);
        allTheNames.Append(rented[..length]);
        ArrayPool<char>.Shared.Return(rented);
    }
    allTheNames.AppendLine();
}
```

### Alternative Designs

Instead of `TryGetString` *copying* the string value into a given buffer, a `GetStringSpan` method could _return_ the `ReadOnlySpan<char>` (or `ReadOnlyMemory<char>`) backing the original memory that contains the string.

However this depends on a few things:
1. The PE metadata must itself be encoded the same as `char` (UTF-16).
2. The memory must be contiguous (seems like a safe bet).
3. The memory must not move before the caller has had a chance to copy it out (seems like a safe bet).

In cases like the example API usage, this would eliminate an extra copy of the string buffer.

**Comment by teo-tsirpanis** [comment] 2024-06-07 22:13
Duplicate of #85280.

**Closed** 2024-06-08 15:19 UTC
Labels: api-suggestion, area-System.Reflection.Metadata
