### ISSUE TITLE
Test failure System.Net.Http.Functional.Tests.SyncHttpHandler_HttpClientHandler_Decompression_Tests.GetAsync_SetAutomaticDecompression_ContentDecompressed_Deflate(uri: \"https://httpbin.org/deflate\", expectedContent: \"\\\"deflated\\\": true\")

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#52889] opened 2021-05-18 07:25 UTC
Run: [runtime-libraries-coreclr outerloop 20210517.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1141570&view=ms.vss-test-web.build-test-results-tab&runId=34604580&resultId=100216&paneView=debug)

Failed test:
```
net6.0-OSX-Release-arm64-CoreCLR_release-OSX.1100.ARM64.Open

- System.Net.Http.Functional.Tests.SyncHttpHandler_HttpClientHandler_Decompression_Tests.GetAsync_SetAutomaticDecompression_ContentDecompressed_Deflate(uri: \"https://httpbin.org/deflate\", expectedContent: \"\\\"deflated\\\": true\")

```

**Error message:**
```
System.Net.Http.HttpRequestException : Response status code does not indicate success: 504 (Gateway Time-out).


Stack trace
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode() in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpResponseMessage.cs:line 171
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 224
   at System.Net.Http.Functional.Tests.HttpClientHandler_Decompression_Test.GetAsync_SetAutomaticDecompression_ContentDecompressed_Deflate(String uri, String expectedContent) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.Decompression.cs:line 220
--- End of stack trace from previous location ---
```

**Comment by karelz** [comment] 2021-05-18 11:26
Only 1 failure (this one) during 3/18-5/17 (incl. PRs).

**Comment by karelz** [comment] 2021-08-24 17:39
Duplicate of #58018

**Closed by karelz** 2021-08-24 17:39 UTC
Labels: arch-arm64, area-System.Net.Http, os-mac-os-x
