### ISSUE TITLE
Reverse P/Invoke marshaling can drop the first method parameter

### ISSUE THREAD

**Issue by 0xC0000054** [dotnet/runtime#46479] opened 2020-12-31 04:32 UTC
### Description

The reverse P/Invoke marshaler can drop the first method parameter when working with callback methods in some native libraries.
This appears to be an edge case that only occurs when interfacing with certain methods.

I encountered this issue with the `write` callback in the `heif_writer` structure when writing a managed interface for [libheif](https://github.com/strukturag/libheif), but I was unable to reproduce it with a new C++ library that uses an identical reverse P/Invoke delegate signature.

I have a repo for this issue in the following repository:

https://github.com/0xC0000054/heif-reverse-pinvoke-bug

That repository uses the libheif v1.9.1 binaries from Vcpkg.

### Configuration

* Which version of .NET is the code running on?
    * .NET Core 3.1.10 

* What OS and version, and what distro if applicable?
    * Windows 10 x64 version 2004.

* What is the architecture (x64, x86, ARM, ARM64)?
    * x86
    
* Do you know whether it is specific to that configuration?
	* It looks that way, the issue does not appear on .NET 5.0 or the x64 version of .NET Core 3.1.10.

### Regression?

Yes, the parameters are marshaled correctly on .NET Framework version 4.8.

### Other information

It appears to be a regression in the reverse P/Invoke (stub?) marshaler.

**Comment by AaronRobinsonMSFT** [comment] 2021-01-01 01:31
@0xC0000054 Thanks for reporting this. We will consider this issue for servicing of .NET 3.x in the .NET 6 timeframe.

@jkoritzinsky @elinor-fung we should root cause this and then add a test if the scenario exercises a unique code path in the current implementation. I am going to assume the work that @jkoritzinsky did with the marshallers fixed this.

**Comment by AaronRobinsonMSFT** [comment] 2021-01-01 01:41
@0xC0000054 I haven't run the linked scenario only looked at the code. I did notice that the [`WriteDelegate` delegate](https://github.com/0xC0000054/libheif-sharp/blob/de4545eb7643c3e3f53ee123c96defb74316b961/src/Interop/LibHeif/IO/heif_writer.cs#L28) is not marked with the [`UnmanagedFunctionPointerAttribute`](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.unmanagedfunctionpointerattribute) to indicate the `cdecl` calling convention. Can you please verify that doesn't change the behavior. We will of course look at this eventually but that may be part of the issue.

**Comment by 0xC0000054** [comment] 2021-01-01 01:57
> Can you please verify that doesn't change the behavior. We will of course look at this eventually but that may be part of the issue.

I linked to the wrong revision in the readme, the latest version does have the UnmanagedFunctionPointerAttribute to indicate the cdecl calling convention.

Adding the UnmanagedFunctionPointerAttribute does not change this issue, the repo version of the [WriteDelegate delegate](https://github.com/0xC0000054/heif-reverse-pinvoke-bug/blob/b6befaf4b7a174c3a73ca75f8dffc0427534d124/LibHeifSharp/Interop/LibHeif/heif_writer.cs#L29) is marked with it.

**Comment by jkoritzinsky** [comment] 2021-01-12 22:29
I think this has the same underlying issue as https://github.com/dotnet/runtime/issues/45637. I'm taking a closer look.

**Comment by AaronRobinsonMSFT** [comment] 2021-02-01 20:38
@jkoritzinsky Can we close this now that #45637 is fixed?

**Closed** 2021-02-01 20:39 UTC
Labels: area-Interop-coreclr
