### ISSUE TITLE
Default constructor trimmed for generic argument

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/runtime#81720] opened 2023-02-06 20:24 UTC
### Description

In EF https://github.com/dotnet/efcore/blob/main/src/EFCore/Diagnostics/Internal/DiagnosticsLogger.cs is registered in DI as https://github.com/dotnet/efcore/blob/main/src/EFCore/Diagnostics/IDiagnosticsLogger`.cs

### Reproduction Steps

See attached
[DITest.zip](https://github.com/dotnet/runtime/files/10668883/DITest.zip)

### Expected behavior

No exceptions thrown

### Actual behavior

When `IDiagnosticsLogger<`[ChangeTracking](https://github.com/dotnet/efcore/blob/main/src/EFCore/DbLoggerCategory.cs#L110)`>` is resolved the following exception is thrown in NativeAOT mode:
<details>
<summary>Stack trace</summary>
Unhandled Exception: System.ArgumentException: 'Microsoft.EntityFrameworkCore.DbLoggerCategory+ChangeTracking', on 'Microsoft.EntityFrameworkCore.Diagnostics.Internal.DiagnosticsLogger`1[TLoggerCategory]' violates the constraint of type 'TLoggerCategory'.
   at Internal.Reflection.Execution.ConstraintValidator.EnsureSatisfiesClassConstraints(Type[], Type[], Object, ConstraintValidator.SigTypeContext) + 0x121
   at Internal.Reflection.Execution.ConstraintValidator.EnsureSatisfiesClassConstraints(Type, Type[]) + 0x44
   at Internal.Reflection.Execution.ExecutionEnvironmentImplementation.TryGetConstructedGenericTypeForComponents(RuntimeTypeHandle, RuntimeTypeHandle[], RuntimeTypeHandle&) + 0x136
   at System.Reflection.Runtime.TypeInfos.RuntimeConstructedGenericTypeInfo.GetRuntimeTypeHandleIfAny(RuntimeTypeInfo, RuntimeTypeInfo[]) + 0xaa
   at System.Reflection.Runtime.TypeInfos.RuntimeTypeInfo.MakeGenericType(Type[]) + 0x24a
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateOpenGeneric(ServiceDescriptor, Type, CallSiteChain, Int32, Boolean) + 0x199
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateOpenGeneric(Type, CallSiteChain) + 0xae
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain) + 0x10d
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type, CallSiteChain) + 0x51
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type, CallSiteChain, ParameterInfo[], Boolean) + 0x70
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache, Type, Type, CallSiteChain) + 0xcf
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor, Type, CallSiteChain, Int32) + 0x180
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type, CallSiteChain) + 0x82
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain) + 0xf7
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type, CallSiteChain) + 0x51
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type, CallSiteChain, ParameterInfo[], Boolean) + 0x70
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache, Type, Type, CallSiteChain) + 0xcf
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor, Type, CallSiteChain, Int32) + 0x180
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type, CallSiteChain) + 0x82
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain) + 0xf7
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type, CallSiteChain) + 0x51
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType) + 0x6a
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey, Func`2) + 0x85
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type, ServiceProviderEngineScope) + 0x2e
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider, Type) + 0x50
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider) + 0x29
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies() + 0x32
   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices() + 0x13a
   at Program.<Main>$(String[] args) + 0x5c
</details>

### Regression?

No

### Known Workarounds

Annotating the generic parameter solves this issue
```C#
public interface IDiagnosticsLogger<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicParameterlessConstructor)] TLoggerCategory> : IDiagnosticsLogger
    where TLoggerCategory : LoggerCategory<TLoggerCategory>, new()
```

### Configuration

SDK: 8.0.100-alpha.1.23073.1
Runtime: 8.0.0-preview.2.23081.5

**Comment by vitek-karas** [comment] 2023-02-06 22:41
This sounds a lot like a duplicate of https://github.com/dotnet/runtime/issues/80037.
Although it might be a bit more complicated due to it going through DI, so probably also related to https://github.com/dotnet/runtime/issues/81358

**Comment by vitek-karas** [comment] 2023-02-06 22:48
Confirmed that this is NativeAOT only issue. Trimming alone works fine (since linker correctly handles the new constraint).
This is obviously something we need to fix - I'll look into this next.

**Closed** 2023-03-08 13:11 UTC
Labels: untriaged, in-pr, area-NativeAOT-coreclr
