### ISSUE TITLE
Undo revert of Arcade update to ingest Workload Manifest task

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/runtime#71150] opened 2022-06-22 17:01 UTC
Basically, undo https://github.com/dotnet/runtime/pull/71110 (but don't undo the SDK update), and fix up the publish task as described below (copy/pasted from the PR):

```
Runtime will have to take an arcade update, a llvm-project update, and Jacques' change next month, plus a fix to the publish stage invoked here: https://github.com/dotnet/runtime/blob/cd19e8bf35d18cef6f30d896313cbeb1be2a06dd/eng/pipelines/official/jobs/prepare-signed-artifacts.yml#L48-L57. The problem seems to be that you're trying to upload all blobs to `blobArtifacts`, but there are now .msi's with duplicate names. From @joeloff:

> [7:52 PM] Jacques Eloff
it organizes builds by feature band for VS insertions, so MSIs can be duplicated in multiple folders. Copying them the same location won't work.

> because in staging, each sets of files for each feature band is published to a separate VSDROP container and there can be overlap, but not all blobbies have the same files.

Wanted to make sure this was on your radar. The failure happens during the AzDO artifact upload task that happens at the end of that step:

> Async Command Start: Upload Artifact
> ...
> Fail to upload 'D:\a\_work\1\s\artifacts\PackageDownload\IntermediateArtifacts\workloads-vs\Insertion\6.0.300\Microsoft.AOT.win-x64.Cross.android-arm.6.0.7.msi' due to 'Blob is incomplete (missing block). Blob: af95b7c0d1f1ec11b656501ac504b8de, Expected Offset: 0, Actual Offset: 4194304'.
```

The root cause of this was the change to the workload manifest tasks in Arcade: https://github.com/dotnet/arcade/pull/8645

This requires reaction in runtime's usage of those tasks: https://github.com/dotnet/runtime/blob/6212eabc5efa507ee0ca2fc21dfdc327abc73c0a/src/workloads/workloads.csproj#L113-L133

We tried to react with https://github.com/dotnet/runtime/pull/71046, but that caused us to try to publish multiple .msi's with the same name to the same place. Basically we need to publish the output of the new task & preserve its output folder structure, rather than flattening.

**Comment by ericstj** [comment] 2022-06-22 18:10
@directhex @steveisok can you prioritize a change to workloads.csproj to fix this and help get Arcade flowing again in 6.0?

**Comment by joeloff** [comment] 2022-06-22 18:28
Some details. The workload outputs will be organized by feature band to facilitate publishing the specific content for the VS versions being targeted. There's some automation tasks that we have in staging that we haven't been able to use.

artifacts\VSSetup\Debug\Insertion\6.0.100
artifacts\VSSetup\Debug\Insertion\6.0.200
artifacts\VSSetup\Debug\Insertion\6.0.300

Because workload packs can be the same, it's likely there will be overlap in these folders and it seems that publishing was pushing the content to the same blob container

**Comment by directhex** [comment] 2022-06-30 14:20
Hi @wtgodbe, do logs still exist for one of the builds which failed due to the Arcade bump?

**Comment by wtgodbe** [comment] 2022-06-30 15:39
https://dev.azure.com/dnceng/internal/_build/results?buildId=1837162&view=logs&j=138e5e17-b2cd-527a-2da4-df51693fdead&t=7c441ab8-f67c-56a1-1eef-407c16f44b55&s=fbeceea2-8819-56cc-d4aa-12918796648b

**Comment by directhex** [comment] 2022-07-01 22:17
This is increasingly looking like an annoying problem to resolve.

`PushToAzureDevOpsArtifacts`, part of Arcade, is apparently where things are going wrong. If the Items have a `PublishFlatContainer=false` property attached, then directory structure is not flattened... but the task will fail for non-nupkg files (e.g. json files). If `PublishFlatContainer=true` then we run into the observed behaviour with `System.InvalidOperationException: Blob is incomplete (missing block).` and non-zero offsets.

So I need to pull Arcade apart to try and fix it (and really need to set up a minimal repro case so I'm not waiting hours for every attempt)

**Comment by directhex** [comment] 2022-07-05 18:58
I can confirm my analysis from a simple repro case. https://github.com/directhex/arcade-repro runs on https://dev.azure.com/joshield/testing/_build?definitionId=1&_a=summary and behaves in exactly the same way as runtime.git: `PublishFlatContainer=false` _only_ supports NuPkg files, and `RelativeBlobPath` is thrown away during the upload. `PublishToAzureDevOpsArtifacts` just doesn't support folders in the general case.

For small files (smaller than the upload chunk size), the last uploaded file simply overwrites older files of the same name. For files larger than the chunk size, you get the `Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Bad Request` which is largely typified by `Blob is incomplete (missing block)`.

Should I open an issue against Arcade for this?

**Comment by joeloff** [comment] 2022-07-05 19:01
Yeah,. might be worth to pull them in and see if there's a good solution. Right now we have duplicated packs, but the idea was always that workloads for different feature bands can diverge and we want to upload clean drops for VS for each feature band.

**Comment by joeloff** [comment] 2022-08-30 15:28
No, we should close this. Let me link the PRs for this.

**Comment by joeloff** [comment] 2022-08-30 15:30
Fixed with https://github.com/dotnet/runtime/pull/73981

**Closed by joeloff** 2022-08-30 15:30 UTC
Labels: blocking-servicing, area-Infrastructure-mono
