### ISSUE TITLE
[5.0.100-rc.2.20464.10] Single File Publish issue on Greenshot App after retarget .NET5

### ISSUE THREAD

**Issue by jiangzeng01** [dotnet/runtime#42304] opened 2020-09-16 08:03 UTC
**Application Name:** Greenshot
**OS:** Windows 10 RS5
**CPU:** X64
**.NET Build Number:** 5.0.100-rc.2.20464.10
**App Location:** \\appcompatsrv\Appcompat\DotNetCore\AppSource\SingleFileP0AppsTarget5\Apps\greenshot
**App Source:** \\appcompatsrv\Appcompat\DotNetCore\AppSource\SingleFileP0AppsTarget5\AppSources\greenshot
**DevDiv bug:** [https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1214883](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1214883)

**Repro steps:**
Retarget .NET 5
Single File exe was created by
dotnet publish -r win-x64 -p:PublishSingleFile=true --self-contained true
using 5.0.100-rc.2.20464.10 SDK

Copy '\\appcompatsrv\Appcompat\DotNetCore\AppSource\SingleFileP0AppsTarget5\Apps\greenshot' to local machine.
Double-click on Greenshot.exe

**Expected Result:**
Open Greenshot successful.

**Actual Result:**
The Greenshot cannot be launched successful.

**Findings:**
The Greenshot process is displayed in Task Manager, but it doesn't show the app screen.
The Self-contained and Framework-Dependency app can be launched. Only the Single file unable to launch.

**Exception from Event View:**
```
Application: Greenshot.exe
CoreCLR Version: 5.0.20.46205
.NET Version: 5.0.0-rc.2.20462.5
Description: The process was terminated due to an unhandled exception.
Exception Info: Autofac.Core.DependencyResolutionException: An error occurred while attempting to automatically activate registration 'Activator = GreenshotFormatReader (ReflectionActivator), Services = [Greenshot.Gfx.Formats.IImageFormatReader, AutoActivate], Lifetime = Autofac.Core.Lifetime.RootScopeLifetime, Sharing = Shared, Ownership = OwnedByLifetimeScope'. See the inner exception for information on the source of the failure.
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while activating Greenshot.Addons.Core.GreenshotFormatReader.
 ---> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Greenshot.Addons.Core.GreenshotFormatReader' can be invoked with the available services and parameters:
Cannot resolve parameter 'System.Func`1[Greenshot.Addons.Interfaces.ISurface] surfaceFactory' of constructor 'Void .ctor(System.Func`1[Greenshot.Addons.Interfaces.ISurface])'.
   at Autofac.Core.Activators.Reflection.ReflectionActivator.GetValidConstructorBindings(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters, Object& decoratorTarget)
   at Autofac.Core.Resolving.InstanceLookup.<>c__DisplayClass6_0.<Execute>b__0()
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Container.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Builder.StartableManager.StartStartableComponents(IComponentContext componentContext)
   --- End of inner exception stack trace ---
   at Autofac.Builder.StartableManager.StartStartableComponents(IComponentContext componentContext)
   at Autofac.ContainerBuilder.Build(ContainerBuildOptions options)
   at Dapplo.Addons.Bootstrapper.ApplicationBootstrapper.InitializeAsync(CancellationToken cancellationToken)
   at Dapplo.CaliburnMicro.Dapp.Dapplication.OnStartup(StartupEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at Interop.User32.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.RunDialog(Form form)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at System.Windows.Forms.Form.ShowDialog()
   at Greenshot.Startup.ShowInstances()
   at Greenshot.Startup.Main(String[] arguments)
```

CC @dotnet-actwx-bot

**Comment by LakshanF** [comment] 2020-09-16 13:18
The call stack is very helpful! It seems like this self-contained SingleFile app doesn't have all the dependent assemblies for it to run successfully. Autofac seems to be a DI component and will not play well with SingleFiles.

In which case, this behavior would be by design. We need to explore more the diagnostics information we provide for apps like these.

**Comment by agocke** [comment] 2020-09-28 20:03
Should be fixed by https://github.com/dotnet/runtime/issues/42352

**Comment by agocke** [comment] 2020-10-05 18:06
Fixed in https://github.com/dotnet/runtime/issues/42352

**Comment by jiangzeng01** [comment] 2020-10-09 07:52
@agocke  We are going to verify the bug, which .Net 5 release will the fix be located?
We tried both latest RC2 & RTM daily build, see failing logs below:

**Published with .NET 5 RC2: 5.0.100-rc.2.20480.7:** the same error as this ticket reported. It seems like the fix is not ported to RC2?

**Published with .NET 5 RTM: 5.0.100-rtm.20508.12:** The following files are existing, but it failed with "could not find file".
```
C:\SingleFileApps\AppSource\greenshot\src\Greenshot.Addons\obj\Debug\net5.0-windows\win-x64\Views\ExportNotificationView.g.cs(49,18): error CS1504: Source file '..\..\..\..Views\ExportNotificationView.xaml' could not be opened -- Could not find file. [C:\SingleFileApps\AppSource\greenshot\src\Greenshot.Addons\Greenshot.Addons.csproj]
C:\SingleFileApps\AppSource\greenshot\src\Greenshot.Addons\obj\Debug\net5.0-windows\win-x64\Views\ExportNotificationView.g.cs(70,21): error CS1504: Source file '..\..\..\..Views\ExportNotificationView.xaml' could not be opened -- Could not find file. [C:\SingleFileApps\AppSource\greenshot\src\Greenshot.Addons\Greenshot.Addons.csproj]
C:\SingleFileApps\AppSource\greenshot\src\Greenshot.Addons\obj\Debug\net5.0-windows\win-x64\Views\FileConfigPartView.g.cs(45,18): error CS1504: Source file '..\..\..\..Views\FileConfigPartView.xaml' could not be opened -- Could not find file. [C:\SingleFileApps\AppSource\greenshot\src\Greenshot.Addons\Greenshot.Addons.csproj]
C:\SingleFileApps\AppSource\greenshot\src\Greenshot.Addons\obj\Debug\net5.0-windows\win-x64\Views\FileConfigPartView.g.cs(66,21): error CS1504: Source file '..\..\..\..Views\FileConfigPartView.xaml' could not be opened -- Could not find file. [C:\SingleFileApps\AppSource\greenshot\src\Greenshot.Addons\Greenshot.Addons.csproj]
C:\SingleFileApps\AppSource\greenshot\src\Greenshot.Addons\obj\Debug\net5.0-windows\win-x64\Views\UploadView.g.cs(58,21): error CS1504: Source file '..\..\..\..Views\UploadView.xaml' could not be opened -- Could not find file. [C:\SingleFileApps\AppSource\greenshot\src\Greenshot.Addons\Greenshot.Addons.csproj]
```

**Comment by jiangzeng01** [comment] 2020-10-10 07:08
@agocke  We tried to publish this app with `-p:IncludeAllContentForSelfExtract=true` for SingleFile, but another error happens when we publish, so we are not able to verify this issue:

**Published with .NET 5 RTM: 5.0.100-rtm.20508.12:** The following files are existing, but it failed with "could not find file".
```
C:\SingleFileApps\AppSource\greenshot\src\Greenshot.Addons\obj\Debug\net5.0-windows\win-x64\Views\ExportNotificationView.g.cs(49,18): error CS1504: Source file '..\..\..\..Views\ExportNotificationView.xaml' could not be opened -- Could not find file. [C:\SingleFileApps\AppSource\greenshot\src\Greenshot.Addons\Greenshot.Addons.csproj]
C:\SingleFileApps\AppSource\greenshot\src\Greenshot.Addons\obj\Debug\net5.0-windows\win-x64\Views\ExportNotificationView.g.cs(70,21): error CS1504: Source file '..\..\..\..Views\ExportNotificationView.xaml' could not be opened -- Could not find file. [C:\SingleFileApps\AppSource\greenshot\src\Greenshot.Addons\Greenshot.Addons.csproj]
C:\SingleFileApps\AppSource\greenshot\src\Greenshot.Addons\obj\Debug\net5.0-windows\win-x64\Views\FileConfigPartView.g.cs(45,18): error CS1504: Source file '..\..\..\..Views\FileConfigPartView.xaml' could not be opened -- Could not find file. [C:\SingleFileApps\AppSource\greenshot\src\Greenshot.Addons\Greenshot.Addons.csproj]
C:\SingleFileApps\AppSource\greenshot\src\Greenshot.Addons\obj\Debug\net5.0-windows\win-x64\Views\FileConfigPartView.g.cs(66,21): error CS1504: Source file '..\..\..\..Views\FileConfigPartView.xaml' could not be opened -- Could not find file. [C:\SingleFileApps\AppSource\greenshot\src\Greenshot.Addons\Greenshot.Addons.csproj]
C:\SingleFileApps\AppSource\greenshot\src\Greenshot.Addons\obj\Debug\net5.0-windows\win-x64\Views\UploadView.g.cs(58,21): error CS1504: Source file '..\..\..\..Views\UploadView.xaml' could not be opened -- Could not find file. [C:\SingleFileApps\AppSource\greenshot\src\Greenshot.Addons\Greenshot.Addons.csproj]
```

It seems like it failed with the xaml files, the files are actually existing in project.

**Comment by jiangzeng01** [comment] 2020-10-10 07:32
@agocke Reopen this issue as the app failed with another publish issue when we publish singlefile with `-p:IncludeAllContentForSelfExtract=true`

**Published with .NET 5 RTM: 5.0.100-rtm.20508.12:** The following files are existing, but it failed with "could not find file".
```
C:\SingleFileApps\AppSource\greenshot\src\Greenshot.Addons\obj\Debug\net5.0-windows\win-x64\Views\ExportNotificationView.g.cs(49,18): error CS1504: Source file '..\..\..\..Views\ExportNotificationView.xaml' could not be opened -- Could not find file. [C:\SingleFileApps\AppSource\greenshot\src\Greenshot.Addons\Greenshot.Addons.csproj]
C:\SingleFileApps\AppSource\greenshot\src\Greenshot.Addons\obj\Debug\net5.0-windows\win-x64\Views\ExportNotificationView.g.cs(70,21): error CS1504: Source file '..\..\..\..Views\ExportNotificationView.xaml' could not be opened -- Could not find file. [C:\SingleFileApps\AppSource\greenshot\src\Greenshot.Addons\Greenshot.Addons.csproj]
C:\SingleFileApps\AppSource\greenshot\src\Greenshot.Addons\obj\Debug\net5.0-windows\win-x64\Views\FileConfigPartView.g.cs(45,18): error CS1504: Source file '..\..\..\..Views\FileConfigPartView.xaml' could not be opened -- Could not find file. [C:\SingleFileApps\AppSource\greenshot\src\Greenshot.Addons\Greenshot.Addons.csproj]
C:\SingleFileApps\AppSource\greenshot\src\Greenshot.Addons\obj\Debug\net5.0-windows\win-x64\Views\FileConfigPartView.g.cs(66,21): error CS1504: Source file '..\..\..\..Views\FileConfigPartView.xaml' could not be opened -- Could not find file. [C:\SingleFileApps\AppSource\greenshot\src\Greenshot.Addons\Greenshot.Addons.csproj]
C:\SingleFileApps\AppSource\greenshot\src\Greenshot.Addons\obj\Debug\net5.0-windows\win-x64\Views\UploadView.g.cs(58,21): error CS1504: Source file '..\..\..\..Views\UploadView.xaml' could not be opened -- Could not find file. [C:\SingleFileApps\AppSource\greenshot\src\Greenshot.Addons\Greenshot.Addons.csproj]
```

**Comment by agocke** [comment] 2020-10-10 09:09
Agreed, it looks like it's not a single-file issue any more. I'd rather close this issue if you don't mind. Changing the title breaks email threading, so I think it's better to start fresh with a new issue if it's necessary to also track this on the runtime side.

**Closed by agocke** 2020-10-10 09:09 UTC
Labels: area-Single-File

**Comment by jiangzeng01** [comment] 2020-10-16 02:23
@agocke The WPF issue [https://github.com/dotnet/wpf/issues/3628](https://github.com/dotnet/wpf/issues/3628) was fixed, and we came back to verify this app, passed, no new issues
