### ISSUE TITLE
Test failure System.Net.Tests.HttpWebRequestTest_Sync.GetResponseAsync_ParametersAreCachableButDifferent_CreateNewClient

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#85436] opened 2023-04-27 01:43 UTC
**Failed in:** [runtime-coreclr libraries-jitstress 20230426.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=252833&view=ms.vss-test-web.build-test-results-tab&runId=4908050&resultId=173750&paneView=debug)

**Failed tests:**
```
net8.0-linux-Release-arm64-CoreCLR_checked-jitstress2-(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
    - System.Net.Tests.HttpWebRequestTest_Sync.GetResponseAsync_ParametersAreCachableButDifferent_CreateNewClient
net8.0-windows-Release-arm64-CoreCLR_checked-jitstress2-Windows.11.Arm64.Open
    - System.Net.Http.Tests.CacheControlHeaderValueTest.ToString_NegativeValues_UsesMinusSignRegardlessOfCurrentCulture
```

**Error message:**
```
 Exit code was 134 but it should have been 42
Expected: True
Actual:   False
```

**Stack trace:**
```
    at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 239
   at System.Net.Tests.HttpWebRequestTest.GetResponseAsync_ParametersAreCachableButDifferent_CreateNewClient() in /_/src/libraries/System.Net.Requests/tests/HttpWebRequestTest.cs:line 1758
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
```

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2023-04-26T07:51:19.523Z | runtime-coreclr libraries-jitstress | Release | windows.11.arm64.open | arm64 | System.Net.Http.Tests.CacheControlHeaderValueTest.ToString_NegativeValues_UsesMinusSignRegardlessOfCurrentCulture | Failed | {"Reason":"Schedule","architecture":"arm64","System.JobName":"__default","System.StageName":"Build","operatingSystem":"Windows.11.Arm64.Open","runtimeFlavor":"coreclr","Project":"public","configuration":"Release","System.JobId":"f9affed7-8d82-5c58-eb09-b33088a0b629","scenario":"jitstress2","DefinitionId":"138","System.PhaseAttempt":"1","DefinitionName":"runtime-coreclr libraries-jitstress","BuildNumber":"20230426.1","System.StageAttempt":"1","AzurePipelinesTestRunId":"4908292","CollectionUri":"https://dev.azure.com/dnceng-public/","System.PhaseName":"libraries_test_run_checked_coreclr_windows_arm64_Release","System.JobAttempt":"1","BuildId":"252833"} | Schedule

**Comment by JulieLeeMSFT** [comment] 2023-05-01 18:58
@jakobbotsch PTAL.

**Comment by jakobbotsch** [comment] 2023-05-15 09:31
This was a duplicate of #85403

**Closed by jakobbotsch** 2023-05-15 09:31 UTC
Labels: arch-arm64, os-linux, os-windows, JitStress, area-CodeGen-coreclr, blocking-clean-ci-optional
