### ISSUE TITLE
Activity.SetParentId does not change RootId and Id

### ISSUE THREAD

**Issue by narcis-sy** [dotnet/runtime#60078] opened 2021-10-06 18:36 UTC
Setting a parentless activity a parent via Activity.SetParentId() does not update the Activity.Id and Activity.RootId.

```
var originalId = Activity.Current.Id; // "00-{TraceId}-{SpanId}-00"
var originalRootId = Activity.Current.RootId; // "{RootId}"

// {TraceId} should and does equal {RootId}, there is no parent.

var newActivity = Activity.Current?.SetParentId("{TraceIdParent}", "{SpanIdParent}");

// Expected
var newId= newActivity Id; // "00-{TraceIdParent}-{SpanId}-00"
var newRootId = newActivity.RootId; // "{TraceIdParent}"

// Actual
var newId= newActivity Id; // "00-{TraceId}-{SpanId}-00" -- TraceId remains the same, should have been updated to TraceIdParent
var newRootId = newActivity.RootId; // "{RootId}"   -- remains the same

```
`Activity.ParentId` is set correctly by the `Id` and `RootId` are not updated accordingly.

I've tracked it down Id proeprty not recomputing the _id field value when traceId changes

https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L184

When SetParentId is called, it correctly updates the traceId, but the _id field remain the same

https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/Activity.cs#L545

**Comment by tarekgh** [comment] 2021-10-06 19:33
Thanks @narcis-sy for your report.

**Comment by noahfalk** [comment] 2021-10-08 21:41
Can you set the parent id before the Activity is started? That is the intended design. For example:

```C#
using (Activity a = myActivitySource.StartActivity("foo", ActivityKind.Server, parentContext)
{
   // do work here
}
```

Or the older API that didn't facilitate sampling:
```C#
Activity a = new Activity("foo");
a.SetParentId(parentId);
a.Start();
// do work here
a.Stop();
```

 Based on how the feature is intended to work there is a bug in SetParentId, but the expected behavior was this:

```C#
try
{
    var newActivity = Activity.Current?.SetParentId("{TraceIdParent}", "{SpanIdParent}");
}
catch(InvalidOperationException e)
{
    Debug.Assert(e.Message == "Activity is already started")
}
```

Distributing tracing provides listeners a sampling callback and start notification for each activity. The runtime makes a promise to those listeners that the TraceID and SpanID observable in those callbacks will be fixed for the lifetime of the Activity. A common approach to sampling is to do it based on the value of the TraceID so anything that changed the ID after sampling had occured would invalidate the sampling decision. This prevents us from offering any API that would change TraceID after the Activity is started.

If there is a broader scenario you are trying to solve and you feel stuck we can certainly try to help in another way, just let us know. Hope that helps!

**Comment by tarekgh** [comment] 2021-11-11 23:39
We added the doc remarks in the PR https://github.com/dotnet/dotnet-api-docs/pull/7382

**Closed by tarekgh** 2021-11-11 23:39 UTC
Labels: documentation, area-System.Diagnostics.Activity

**Comment by noahfalk** [comment] 2021-11-12 10:44
Thanks @tarekgh!
