### ISSUE TITLE
APPCRASH System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by DarkLite1** [dotnet/runtime#95781] opened 2023-12-08 09:48 UTC
### Description

We use PowerShell 7.4 together with the module `Posh-SSH` to work with an SFTP server. This [PowerShell script](https://github.com/DarkLite1/Get-or-send-SFTP-file) works fine but once in a while the PowerShell process just quits and throws this error:

> The background process reported an error with the following message: Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index').

Checking the Windows Event Viewer we see a log entry every time this happens:

> Application: pwsh.exe
> CoreCLR Version: 8.0.23.53103
> .NET Version: 8.0.0
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
>    at System.Collections.Generic.List`1.get_Item(Int32 index)
>    at System.Management.Automation.PSDataCollection`1.get_Item(Int32 index)
>    at System.Management.Automation.ServerPowerShellDriver.HandleProgressAdded(Object sender, DataAddedEventArgs eventArgs)
>    at System.Management.Automation.PSDataCollection`1.RaiseEvents(Guid psInstanceId, Int32 index)
>    at System.Management.Automation.PSDataCollection`1.InternalAdd(Guid psInstanceId, T item)
>    at System.Management.Automation.Internal.Host.InternalHostUserInterface.WriteProgress(Int64 sourceId, ProgressRecord record)
>    at SSH.OperationProgressHelper.<>c__DisplayClass9_0.<.ctor>b__1(UInt64 bytes)
>    at Renci.SshNet.SftpClient.<>c__DisplayClass99_1.<InternalUploadFile>b__1()
>    at Renci.SshNet.Abstractions.ThreadAbstraction.<>c__DisplayClass2_0.<ExecuteThread>b__0(Object o)
>    at System.Threading.QueueUserWorkItemCallback.Execute()
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
>    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

We opened an issue with the [Posh-SSH team](https://github.com/darkoperator/Posh-SSH/issues/556) and with the [PowerShell 7 team](https://github.com/PowerShell/PowerShell/issues/20860). However, given the raised errors we assume this is more related to .NET 8.

Sorry for not being able to be more precise as this happens only every 2 hours and in very strange circumstances that we can't seem to replicate. It does seem to be related to something that `Set-SFTPItem` triggers within .NET. 

We don't have .NET skills to analyse the dump files so any help is highly appreciated.

Please find in attachment the log files and the PowerShell crash dump files. 
[Event log errors.zip](https://github.com/dotnet/runtime/files/13612483/Event.log.errors.zip)
[pwsh.exe.23908.zip](https://github.com/dotnet/runtime/files/13612485/pwsh.exe.23908.zip)

### Reproduction Steps

See repro [here](https://github.com/PowerShell/PowerShell/issues/20860).

### Expected behavior

No .NET error in the event log and PowerShell not unexpectedly quitting. 

### Actual behavior

The PowerShell job is just killed. The complete pwsh.exe process is stopped. No native PowerShell error handling like `try{}catch{}` is possible.

### Regression?

We tested with PowerShell 5.1, which probably uses .NET 4, and the issue is there too. 

### Known Workarounds

Can't find a proper workaround for this.

**Comment by jkotas** [comment] 2023-12-08 16:25
I do not see a problem in .NET runtime related. The Powershell code is trying to access List with invalid index.

> The PowerShell job is just killed. The complete pwsh.exe process is stopped. No native PowerShell error handling like try{}catch{} is possible.

Right. The crash is on a background thread. It is not possible to handle exceptions on background threads via try/catch performed on foreground thread.

> We tested with PowerShell 5.1, which probably uses .NET 4, and the issue is there too.

According to https://github.com/PowerShell/PowerShell/issues/16894#issuecomment-1092004148, this is very old code so it is not surprising that the bug is in Powershell 5.1.

My guess is that this is a race condition in the Powershell code.

Duplicate of https://github.com/PowerShell/PowerShell/issues/16894

**Closed by jkotas** 2023-12-08 16:25 UTC
Labels: untriaged, needs-area-label

**Comment by DarkLite1** [comment] 2023-12-11 12:54
Thank you for clearing this up. So it's clearly not .NET at fault but a piece of old PowerShell code within the PowerShell code base. Got it, thank you :)
