### ISSUE TITLE
HttpClient should allow schemes to be restricted (for AllowAutoRedirect)

### ISSUE THREAD

**Issue by pbiggar** [dotnet/runtime#57644] opened 2021-08-18 14:36 UTC
### Description

I'm porting some code that was using Curl to .NET. curl has an option to limit the schemes that client will connect to - this is great, I don't want to support `ftp` or `file` schemes.

It is currently possible to control what schemes the httpclient can call by first checking the scheme of the URL, and then not making that call. However, in the case of automatic redirects, there is no way to enable this. As a result, I am not using automatic redirects, which is a hassle.

### Regression?

I haven't used .NET framework, but it seems like a HttpWebRequest only worked on http/https.

### Other information

* Do you know of any workarounds?

I worked around this by reimplementing the follow logic myself.

### My code
[Checking the scheme](https://github.com/darklang/dark/blob/2a1f3ab464700536cb9f513d785ed622f119bb8f/fsharp-backend/src/LibBackend/HttpClient.fs#L301)
[The manually implemented redirection logic](https://github.com/darklang/dark/blob/2a1f3ab464700536cb9f513d785ed622f119bb8f/fsharp-backend/src/LibBackend/HttpClient.fs#L471)

**Comment by am11** [comment] 2021-08-18 16:25
> However, in the case of automatic redirects, there is no way to enable this. As a result, I am not using automatic redirects, which is a hassle.

Typically HttpClient is customized using HttpRequestHandler in .NET. We can also derive HttpRequestHandler and override its Get/Send methods. However, that is not required in most cases.

e.g. this method will prevent unwanted schemes even in case of a redirect (untested, but it will give you an idea):

```C#
using System;
using System.Diagnostics;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;

static class X
{
    private static readonly string[] sm_invalidSchemes = new[] { "file", "ftp" };

    private static async Task<byte[]> DownloadAsync(Uri uri)
    {
        using var request = new HttpRequestMessage(HttpMethod.Get, uri);

        if (Array.IndexOf(sm_invalidSchemes, uri.Scheme) >= 0)
            throw new InvalidOperationException("{uri.Scheme} scheme is not allowed.");

        using var handler = new HttpClientHandler { AllowAutoRedirect = false };
        using var client = new HttpClient(handler);

       try
       {
            using HttpResponseMessage response = await client.SendAsync(request).ConfigureAwait(false);

            response.EnsureSuccessStatusCode();
            var status = (int)response.StatusCode;
            if (status >= 300 /* HttpStatusCode.MultipleChoices */ && status < 400 /* HttpStatusCode.BadRequest */)
            {
                var redirectUri = response.Headers.Location;
                if (!redirectUri.IsAbsoluteUri)
                {
                    redirectUri = new Uri(request.RequestUri.GetLeftPart(UriPartial.Authority) + redirectUri);
                }

                return await DownloadAsync(redirectUri).ConfigureAwait(false);
            }

            using HttpContent content = response.Content;
            byte[] rawBytes = await content.ReadAsByteArrayAsync().ConfigureAwait(false);
            Debug.Assert(rawBytes.Length > 0, "Got empty response!");
            return rawBytes;
       }
       catch(HttpRequestException)
       {
           Console.Error.WriteLine("Bad news from the server!");
           throw;
       }
    }
}
```

**Comment by pbiggar** [comment] 2021-08-18 17:08
Right, we cannot use the built-in `AllowAutoRedirect` if we wish to restrict the schemes. The feature request is to allow a developer to use AllowAutoRedirect safely. I've renamed the issue for clarity on that.

**Comment by karelz** [comment] 2021-08-18 18:39
@pbiggar this is the first time we hear about request like this. The workaround you found to disable AutoRedirect is the best option I know about.
There is similar more frequent ask to support https -> http redirects, which we do not support on .NET Core intentionally -- see #28039.
Personally I feel this is too narrow scenario to support, but perhaps it could be +1 on more general solution of AutoRedirect filters? -- see #45364

**Comment by pbiggar** [comment] 2021-08-18 19:59
Yes, I think autoredirect filters would be a great solution!

**Comment by karelz** [comment] 2021-08-19 16:58
Duplicate of #45364

**Closed by karelz** 2021-08-19 16:58 UTC
Labels: area-System.Net.Http, untriaged
