### ISSUE TITLE
Field assignment perf regression in 7.0-rc2

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/runtime#77346] opened 2022-10-22 19:16 UTC
### Description

```C#
    [Benchmark]
    public void CopyViaDirectAccess()
    {
        for (int i = 0; i < iterations; i++)
        {
            targetUri.Host0 = testUri.Host0;
            targetUri.Host1 = testUri.Host1;
            targetUri.Host2 = testUri.Host2;
            targetUri.Host3 = testUri.Host3;
            targetUri.Host4 = testUri.Host4;
            targetUri.Host5 = testUri.Host5;
            targetUri.Host6 = testUri.Host6;
            targetUri.Host7 = testUri.Host7;
            targetUri.Host8 = testUri.Host8;
            targetUri.Host9 = testUri.Host9;
        }
    }
```
Full benchmark code at https://gist.github.com/AndriySvyryd/ec423aaed01070087f499f2f16f3a2f2

### Configuration

Windows 10 x64

### Regression?

Yes, from 6.0

### Data

.NET 6:

|                          Method |       Mean |     Error |   StdDev | Ratio | RatioSD |   Gen0 | Allocated |
|-------------------------------- |-----------:|----------:|---------:|------:|--------:|-------:|----------:|
|            CloneViaDirectAccess |   160.1 ns |   0.92 ns |  0.86 ns |  1.00 |    0.00 | 0.0918 |     960 B |
|                  CloneViaMethod |   158.8 ns |   0.92 ns |  0.86 ns |  0.99 |    0.01 | 0.0918 |     960 B |
|                  CloneViaLambda |   172.5 ns |   0.94 ns |  0.88 ns |  1.08 |    0.01 | 0.0918 |     960 B |
| CloneViaCompiledExpressionTrees |   163.0 ns |   1.27 ns |  1.12 ns |  1.02 |    0.01 | 0.0918 |     960 B |
|   CloneViaReflectionWithCaching | 4,950.7 ns |  16.15 ns | 13.48 ns | 30.95 |    0.19 | 0.2899 |    3040 B |
|             CopyViaDirectAccess |   121.1 ns |   0.24 ns |  0.22 ns |  0.76 |    0.00 |      - |         - |
|                   CopyViaMethod |   120.9 ns |   0.33 ns |  0.30 ns |  0.76 |    0.00 |      - |         - |
|                   CopyViaLambda |   124.5 ns |   0.30 ns |  0.28 ns |  0.78 |    0.00 |      - |         - |
|  CopyViaCompiledExpressionTrees |   129.9 ns |   0.54 ns |  0.45 ns |  0.81 |    0.00 |      - |         - |
|    CopyViaReflectionWithCaching | 5,105.7 ns | 100.71 ns | 94.21 ns | 31.89 |    0.58 |      - |         - |

.NET 7-rc2:

|                          Method |       Mean |   Error |  StdDev | Ratio | RatioSD |   Gen0 | Allocated |
|-------------------------------- |-----------:|--------:|--------:|------:|--------:|-------:|----------:|
|            CloneViaDirectAccess |   159.1 ns | 1.03 ns | 0.96 ns |  1.00 |    0.00 | 0.0918 |     960 B |
|                  CloneViaMethod |   157.0 ns | 2.32 ns | 2.06 ns |  0.99 |    0.02 | 0.0918 |     960 B |
|                  CloneViaLambda |   177.7 ns | 1.19 ns | 1.11 ns |  1.12 |    0.01 | 0.0918 |     960 B |
| CloneViaCompiledExpressionTrees |   165.9 ns | 1.64 ns | 1.37 ns |  1.04 |    0.01 | 0.0918 |     960 B |
|   CloneViaReflectionWithCaching | 3,862.4 ns | 9.07 ns | 8.48 ns | 24.28 |    0.16 | 0.2899 |    3040 B |
|             CopyViaDirectAccess |   187.4 ns | 0.07 ns | 0.05 ns |  1.18 |    0.01 |      - |         - |
|                   CopyViaMethod |   181.3 ns | 0.18 ns | 0.16 ns |  1.14 |    0.01 |      - |         - |
|                   CopyViaLambda |   199.3 ns | 0.37 ns | 0.33 ns |  1.25 |    0.01 |      - |         - |
|  CopyViaCompiledExpressionTrees |   188.8 ns | 0.18 ns | 0.15 ns |  1.19 |    0.01 |      - |         - |
|    CopyViaReflectionWithCaching | 5,265.2 ns | 3.71 ns | 3.29 ns | 33.09 |    0.20 |      - |         - |

**Comment by EgorBo** [comment] 2022-10-22 19:34
I assume codegen is the same and the benchmark just measures write barriers, hence the gc label.

**Comment by EgorBo** [comment] 2022-10-22 19:36
Ah, judging by the benchmark it's NativeAOT only?

**Comment by AndriySvyryd** [comment] 2022-10-22 19:46
> Ah, judging by the benchmark it's NativeAOT only?

The numbers above are from JIT. I also tried NativeAOT, the results are the same.

**Comment by Maoni0** [comment] 2022-10-24 16:59
could you please try the workaround mentioned [here](https://maoni0.medium.com/write-barrier-optimizations-in-regions-984bde6c0ffc#389f), ie, set the DOTNET_GCWriteBarrier env var to 3?

**Comment by AndriySvyryd** [comment] 2022-10-24 22:50
Setting  DOTNET_GCWriteBarrier to 3 makes the regression disappear and these cases actually run ~25% faster than on .NET 6.

However, these cases don't represent code that is currently used by EF Core, so this issue isn't high priority from our point-of-view.

**Comment by Maoni0** [comment] 2022-10-25 04:34
just to make it clear - we are not planning to fix this - this is a tradeoff we made. as explained in my blog post, we changed the default because it benefits the vast majority of scenarios. and for the very small percentage of scenarios that would show a regression (mostly microbenchmarks) they would use the env var workaround.

**Comment by EgorBo** [comment] 2023-01-18 22:08
Closing as non-actionable

**Closed by EgorBo** 2023-01-18 22:08 UTC
Labels: tenet-performance, area-GC-coreclr, untriaged
