### ISSUE TITLE
Deserialization of a SortedSet works incorrectly after publishing Blazor webassembly

### ISSUE THREAD

**Issue by egeorg** [dotnet/runtime#78776] opened 2022-11-23 18:29 UTC
### Description

Create a Blazor WebAssembly application using a Blazor WebAssembly App Empty template.
Use a JsonSerializer.Deserialize<SortedSet<_>>(...) without using JsonSerializer.Serialize(SortedSet<_>) before. Below is an example of index.razor.
Publish it with the following settings:
Target framework: 6.0
Deployment mode: self-contained
Target runtime: browser-wasm
AoT compilation: off

Host it. I assume that any server would yield the same result, but I observer it at GitHub pages.

index.razor:

```
@page "/"

<button onclick="@Deserialize">Deserialize</button>
<br />Message: @message

@code
{
    private string message = "Nothing happened yet";

    private void Deserialize()
    {
        try
        {
            SortedSet<int> sortedSet = JsonSerializer.Deserialize<SortedSet<int>>("[1,2,3]");
            message = $"Deserialized SortedSet: {string.Join(",", sortedSet)}";
        }
        catch (Exception e)
        {
            message = $"Deserialization ended up in an exception: {e}";
        }
    }
}
```

Result:

An exception during deserialization:
```
System.NotSupportedException: DeserializeNoConstructor, JsonConstructorAttribute,
  System.Collections.Generic.SortedSet`1[System.Int32] 
  Path: $ | LineNumber: 0 | BytePositionInLine: 1.
 ---> System.NotSupportedException: DeserializeNoConstructor,
      JsonConstructorAttribute,
      System.Collections.Generic.SortedSet`1[System.Int32]
Exception_EndOfInnerExceptionStack 
at System.Text.Json.ThrowHelper.ThrowNotSupportedException(ReadStack& , Utf8JsonReader& , NotSupportedException ) 
at System.Text.Json.ThrowHelper.ThrowNotSupportedException_DeserializeNoConstructor(Type , Utf8JsonReader& , ReadStack& ) 
at System.Text.Json.Serialization.Converters.ISetOfTConverter`2[[System.Collections.Generic.SortedSet`1[[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Collections, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].CreateCollection(Utf8JsonReader& , ReadStack& , JsonSerializerOptions ) 
at System.Text.Json.Serialization.JsonCollectionConverter`2[[System.Collections.Generic.SortedSet`1[[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Collections, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , SortedSet`1& ) 
at System.Text.Json.Serialization.JsonConverter`1[[System.Collections.Generic.SortedSet`1[[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Collections, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].TryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , SortedSet`1& ) 
at System.Text.Json.Serialization.JsonConverter`1[[System.Collections.Generic.SortedSet`1[[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Collections, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].ReadCore(Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
at System.Text.Json.JsonSerializer.ReadFromSpan[SortedSet`1](ReadOnlySpan`1 , JsonTypeInfo , Nullable`1 )
at System.Text.Json.JsonSerializer.ReadFromSpan[SortedSet`1](ReadOnlySpan`1 , JsonTypeInfo ) 
at System.Text.Json.JsonSerializer.Deserialize[SortedSet`1](String , JsonSerializerOptions ) 
at SortedSetDeserializationDemo.Pages.Index.Deserialize()
```

### Configuration

x64, .NET 6.0.11, Windows 11 Pro 10.0.22000, Visual Studio Community 2022 17.4.1
Chrome 107.0.5304.107/Edge 107.0.1418.56
Did not check on other configurations of .NET

### Other information

There is no error if I add a serialization of a SortedSet before deserialization.

After a small discussion on StackOverflow ([https://stackoverflow.com/questions/74538875/why-sortedset-cannot-be-deserialized-using-blazor-webassembly-on-github-pages]), I've found out that different System.Collections.dll is published with serialization and without it. 8.5 Kb without serialization and 13 Kb with serialization. If I replace System.Collections.dll by 13 Kb version and replace its hash in blazor.boot.json, the error disappears. It looks like publish works incorrectly and trims code that is actually used.

I stumbled upon such behavior when I tried to use call an HTTP API from a Blazor page. In this case you may need to deserialize the JSON response without serializing anything before the call.

**Comment by MichalStrehovsky** [comment] 2022-11-23 21:27
This is likely caused by trimming. Blazor WASM enables trimming by default.

System.Text.Json can only reliably work when trimming is enabled if you use source generators: https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation

**Comment by eerhardt** [comment] 2022-11-23 21:59
Related: https://github.com/dotnet/runtime/issues/53256. We purposefully don't "root" all collection types in System.Text.Json "just in case" you might be deserializing them.

As @MichalStrehovsky says above - you need to use the source generator in a trimmed app in order to reliably trim/publish your app.

You can also do various workarounds to get the constructors of the collections you use to not be trimmed (like you have above by serializing the SortedSet before deserializing). However, that is not recommended because you can run into the same issue with a new collection type in the future.

I'm going to close this, as this has been answered.

**Closed by eerhardt** 2022-11-23 21:59 UTC
Labels: area-System.Text.Json, untriaged, linkable-framework

**Comment by egeorg** [comment] 2022-11-24 05:13
I would not expect to "root" all collection types in System.Text.Json "just in case". I assume that it's an issue if using Serialize leads to all the necessary methods untrimmed, but Deserialize does not, why is there such asymmetry?

**Comment by MichalStrehovsky** [comment] 2022-11-24 07:34
> why is there such asymmetry?

You don't even need to serialize first - just add a `new SortedSet<int>()` call somewhere in your app.

What you're seeing is a side effect - because the code calls the constructor, it will not (currently) be trimmed because there's a reference. Then reflection succeeds because the constructor was kept due to the reference from the other part of your program.

If you don't have a call, trimming will remove the unused method and reflection will not find it.

Note that relying on this side effect is super fragile. Trimming can sometimes remove even methods that are called because it will e.g. inline them into the callsite. Trimming is only reliable with source generated version of System.Text.Json. It is very fragile otherwise.

**Comment by egeorg** [comment] 2022-11-24 07:53
Thank you, for a clarification, Michal! Now it makes sense for me
