### ISSUE TITLE
Review skipped test case for regex scanner with \c[ pattern

### ISSUE THREAD

**Issue by jeffhandley** [dotnet/runtime#65931] opened 2022-02-27 20:02 UTC
[Cleanup Issue-URLs in Code · Issue #63902 · dotnet/runtime](https://github.com/dotnet/runtime/issues/63902) identified a test case that is being skipped, but the referenced issue has been fixed. The PR with the fix indicates that a different approach might have been possible, but the applied fix has been accepted for some time now.

- The original issue was: [Regex fails to accept pattern that it probably should. · Issue #24759 · dotnet/runtime](https://github.com/dotnet/runtime/issues/24759)
- The PR that applied the fix was: [Fix regex scanner for `\c[` by danmoseley · Pull Request #26828 · dotnet/corefx](https://github.com/dotnet/corefx/pull/26828)

https://github.com/dotnet/runtime/blob/f04a24249835096eea1a1a66e4af03cfec5ed32b/src/libraries/System.Text.RegularExpressions/tests/Regex.Groups.Tests.cs#L391-L395

The skipped test case should be evaluated to determine if the fix made allows the test to pass. With the findings we should either enable the test case or update the code comment to reference this open issue for tracking.

/cc @deeprobin

**Comment by joperezr** [comment] 2022-02-27 21:37
Thanks for opening this @jeffhandley . By quickly skimming the code, seems like the issue was fixed in .Net (Core) but the comment indicates that the test case is skipped in .net framework since the fix wouldn’t be present there. I will still check to see if we can add the testcase, but from the comment it seems like we are skipping the test by design.

**Comment by jeffhandley** [comment] 2022-02-27 23:17
Thanks, @joperezr; that makes sense. I can update the comment as part of #65932 to address this then.

**Closed** 2022-02-28 03:21 UTC
Labels: area-System.Text.RegularExpressions, disabled-test, in-pr
