### ISSUE TITLE
.NET SDK new "Logging analyzers" report dozens of new errors in build with Visual Studio 2022

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#65085] opened 2022-02-09 17:26 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Roslyn-analyzers-report-dozens-of-new-er/1603450)._

---
[severity:I'm unable to use this version]
We have a Solution (".sln") with roslyn analyzers, which are configured using a .ruleset file. With Visual Studio 2019, the solution builds without errors.  With Visual Studio 2022, I receive dozens of errors, for example the following two:

error CA1848: For improved performance, use the LoggerMessage delegates instead of calling 'LoggerExtensions.LogWarning(ILogger, string, params object[])'

error CA2254: The logging message template should not vary between calls to 'LoggerExtensions.LogWarning(ILogger, string, params object[])'

A text search in the .ruleset files shows that neither "1848" nor "2254" are configured. Of course, I can fix all those rule violations in order to be able to build, or provide explicit configuration for those rules. But I wish to understand why Visual Studio 2022 behaves differently from Visual Studio 2019. The roslyn analyzers come as a nuget package after all.

---
#### Feedback Bot on 12/6/2021, 03:47 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/21/2022, 06:46 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at: <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq">https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#faq</a>. In case you need answers to common questions or need assisted support, be sure to use <a target='_blank' href="https://visualstudio.microsoft.com/vs/support/">https://visualstudio.microsoft.com/vs/support/</a>. We’ll keep you posted on any updates to this feedback.</p>

#### Feedback Bot on 1/21/2022, 06:46 PM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Feedback Bot on 1/21/2022, 07:25 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Feedback Bot on 1/21/2022, 07:26 PM: 

Thank you for reporting this issue to us. We have changed the title to better describe the problem so others can find and engage with it.

#### Hermann Gruber on 2/9/2022, 10:30 AM: 

<p><a target='_blank' href="https://developercommunity2.visualstudio.com/user/2068f5a9-4cbb-61c1-8966-27c698d72e3b/profile">maariyan [MSFT]</a> Thanks a lot - this completely answers my question.</p>

---
#### maariyan [MSFT] solved on 2/9/2022, 02:00 AM, 1 votes: 

<p>The ask here is about why there is a difference in behavior between VS2019 vs VS2022.</p>
<p>The reason is the CA2254 and CA1848 analyzers only target compiler version that’s shipped for VS2022</p>

#### Hermann Gruber solved on 12/20/2021, 05:35 PM, 0 votes: 

<p>[Workaround]<br>
We worked around this issue by a) fixing the issues that trigger the new warnings where it made sense to us and b) configuring the rules to suppress the warnings in those cases where the issues didn’t affect the business value of our product. I’m still puzzled how this can be caused by the Visual Studio Version (as explained above), but this no longer blocks our team from moving to Visual Studio 2022.</p>

**Comment by eerhardt** [comment] 2022-02-09 17:51
I believe @maryamariyan addressed the VS feedback ticket yesterday with https://developercommunity.visualstudio.com/t/Roslyn-analyzers-report-dozens-of-new-er/1603450#T-N1657362 and that resolved the feedback ticket.

I'm going to close this issue as I believe the question has been addressed. Please re-open if this is not the case.

**Closed by eerhardt** 2022-02-09 17:51 UTC
Labels: untriaged, area-Extensions-Logging

**Comment by HermannGruber** [comment] 2022-02-10 07:58
Thanks, the issue is fixed for me with the abovementioned workaround, and my question is answered as well. For the sake of completeness, I add in @maryamariyan 's answer also here: 
_The ask here is about why there is a difference in behavior between VS2019 vs VS2022.
The reason is the CA2254 and CA1848 analyzers only target compiler version that’s shipped for VS2022_
