### ISSUE TITLE
Generic attributes: Attribute.GetCustomAttributes returns null when passed an unbound generic type

### ISSUE THREAD

**Issue by canton7** [dotnet/runtime#64335] opened 2022-01-26 15:11 UTC
### Description

`Attribute.GetCustomAttributes` normally returns an empty array when no attributes are found (or throws an exception if the parameters don't make sense).

However,  `Attribute.GetCustomAttributes(someType, typeof(SomeGenericAttribute<>))` returns `null`. This is unexpected, particularly as the nullable annotations say that it doesn't return `null`.

It's worth noting that this wasn't previously possible: it was simply not possible to create a generic type which derived from `Attribute`, and if you passed a type which wasn't derived from `Attribute` to `Attribute.GetCustomAttributes`, you got an exception telling you that. So I suspect this is an unhandled case which just fell through the cracks.

### Reproduction Steps

```cs
Test.M();

public class Test
{
    public static void M()
    {
        var attrs = Attribute.GetCustomAttributes(typeof(Test), typeof(TestAttribute<>));
        Console.WriteLine(attrs == null); // true
    }
}

public class TestAttribute<T> : Attribute { }
```

[SharpLab](https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQHMIDsIIJYDGqsM+wcMKANDCAnFlQCYgDUAPgAIBMAjALAAoIQBUUMAHQBZABQBKANxChnAMwACHurHIYQgN5D1xzRs68AbJoAs62XKMnDgk6/UA3KAnUkEydQC86gCCMKR45JQSAOIQMADCcLoA9gC2oeGRKDIwAJ4ADhDJYDI6MHJU6nmFxaXiGWQUEAA8AHxyio5umrwAnDK+/gFBWHAANmOK6gD001X0EF3qAL5Cq8KCaprc2vVhjZTNIq3qICH7EU3q+itAA===)

### Expected behavior

`Attribute.GetCustomAttributes` either returns an array, or throws an exception. It should not return `null`.

### Actual behavior

`Attribute.GetCustomAttributes` returns `null` in this case.

### Regression?

No. It was not previously possible to pass an unbound generic attribute type to `Attribute.GetCustomAttributes`.

**Comment by VBAndCs** [comment] 2022-01-26 15:34
I have asked to accept the open generic form and return all generic attributes of this type https://github.com/dotnet/runtime/issues/64169

**Comment by CyrusNajmabadi** [comment] 2022-01-26 15:39
@VBAndCs you didn't address teh question i asked you there.  :)

**Comment by jkotas** [comment] 2022-01-26 18:01
The bug is caused by `!` at this line https://github.com/dotnet/runtime/blob/03e0187a1a912f38e718c00614201dd20fa1bff1/src/coreclr/System.Private.CoreLib/src/System/Attribute.CoreCLR.cs#L486:

`element.GetCustomAttributes` returns an empty `object[]` since it is not possible to create array with open generic element type. Casting `object[]` to `Attribute[]` using `as` is producing `null`.

**Comment by VBAndCs** [comment] 2022-01-26 18:07
@jkotas 
> since it is not possible to create array with open generic element type

You can return an Attrubute array containing all the generic versions of this open generic attribute.

**Comment by Joe4evr** [comment] 2022-01-31 20:45
So I took a look at this, and I think the best solution would be down around here:
https://github.com/dotnet/runtime/blob/03e0187a1a912f38e718c00614201dd20fa1bff1/src/coreclr/System.Private.CoreLib/src/System/Reflection/RuntimeCustomAttributeData.cs#L931-L932

While my gut reaction is to possibly rethink some parts of this implementation, there's probably more involved that I can't see and may end up breaking assumptions elsewhere. In which case, the most effective fix here might be to add a check whether or not `caType.IsAssignableTo(typeof(Attribute))` and if so, set `arrayType = (RuntimeType)typeof(Attribute)` for the array creation.

Effectively:
```diff
             bool useObjectArray = (caType.IsValueType || caType.ContainsGenericParameters);
+            bool useAttributeArray = (caType.ContainsGenericParameters && caType.IsAssignableTo(typeof(Attribute)));
-            RuntimeType arrayType = useObjectArray ? (RuntimeType)typeof(object) : caType;
+            RuntimeType arrayType = useAttributeArray ? (RuntimeType)typeof(Attribute) : useObjectArray ? (RuntimeType)typeof(object) : caType;
```
(and there's a total of 3 places in the file for this.)

**Comment by madelson** [comment] 2022-02-11 09:12
@Joe4evr / @buyaa-n I'd be interested in fixing this if it is still up for grabs.

**Comment by buyaa-n** [comment] 2022-02-11 17:48
@Joe4evr are working on the fix? if not i will assign to @madelson, thanks!

**Comment by Joe4evr** [comment] 2022-02-11 21:26
@buyaa-n I was trying to, but I just ran out of time over the past week, so it's cool.

**Comment by stephentoub** [comment] 2022-03-11 21:13
Reopening as https://github.com/dotnet/runtime/pull/65237 was reverted in https://github.com/dotnet/runtime/pull/66508 due to https://github.com/dotnet/runtime/issues/66496.

**Closed** 2022-03-14 22:08 UTC
Labels: bug, area-System.Reflection
