### ISSUE TITLE
IsContainer method

### ISSUE THREAD

**Issue by sefacan** [dotnet/runtime#1822] opened 2020-01-15 12:19 UTC
It can be a good help for container applications other than development mode. The application can be in both development mode and container. Both may be needed. 
The ``DOTNET_RUNNING_IN_CONTAINER = true`` can be used for this.

**Comment by anurse** [comment] 2020-01-16 18:04
Transferred to dotnet/runtime. The ask here is for an API that detects if the process is running in a container.

**Comment by jkotas** [comment] 2020-01-16 18:59
> API that detects if the process is running in a container.

This is not a well defined property. There are number of different types of containers (ie Docker is not the only container tech on the planet), and even docker can be setup in number of different ways.

> The DOTNET_RUNNING_IN_CONTAINER = true can be used for this.

There is nothing that guarantees that this environment variable is set when dotnet process is running in a container. The official dotnet images have this variable set by default, but nothing prevents somebody publish their own (e.g. with self-contained app) that won't have this environment variable set.

If you are fine with depending on this environment variable, you can get it using `Environment.GetEnvironmentVariable` yourself. No need for a runtime API that gets it for you.

**Comment by jkotas** [comment] 2020-01-16 19:04
Duplicate of https://github.com/dotnet/corefx/issues/30246

**Closed by jkotas** 2020-01-16 19:04 UTC
Labels: api-suggestion, area-System.Runtime.Extensions, untriaged
