### ISSUE TITLE
System.IO.Path.GetFileName doesn't work in client-side Blazor wasm

### ISSUE THREAD

**Issue by julienGrd** [dotnet/runtime#49294] opened 2021-03-08 08:11 UTC
Hello guys, i reopen this one https://github.com/dotnet/aspnetcore/issues/19141 because it seem still the case (im actually in .NET 5.0).

On the side of Mono, everything seem closed and merge, so i don't know if its "normal" to still have this bug

https://github.com/mono/mono/issues/18933

thanks !

**Comment by jkotas** [comment] 2021-03-08 15:49
Looks like duplicate of #44744

**Comment by CoffeeFlux** [comment] 2021-06-14 18:17
Quoting from Jan:

> All APIs on System.IO.Path and elsewhere follow the rules of the OS that the program is running on. I do not think it would make sense to add an overload that activates some other OS simulator to all these APIs.

We do not intend to add a Browser-specific workaround for this. Given we've had this come up multiple times, it's probably worth improving the documentation around the change. I'll leave this issue open for now until we decide how to handle that aspect.

cc: @lewing

**Comment by SamMonoRT** [comment] 2021-07-09 14:48
Closing per comment in https://github.com/dotnet/runtime/issues/44744#issuecomment-731517311

**Closed by SamMonoRT** 2021-07-09 14:48 UTC
Labels: area-VM-meta-mono
