### ISSUE TITLE
Test failure JIT\\HardwareIntrinsics\\X86\\Sse1\\ConvertToInt32_ro\\ConvertToInt32_ro.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#66052] opened 2022-03-02 01:43 UTC
Run: [runtime-coreclr r2r 20220228.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1637337&view=ms.vss-test-web.build-test-results-tab&runId=45318820&paneView=debug&resultId=100215)

Failed test:
```
R2R windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open

- JIT\\HardwareIntrinsics\\X86\\Sse1\\ConvertToInt32_ro\\ConvertToInt32_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse1\\UnpackLow_r\\UnpackLow_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse1\\LoadAlignedVector128_r\\LoadAlignedVector128_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse1\\MoveHighToLow_ro\\MoveHighToLow_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse1\\ReciprocalScalar_ro\\ReciprocalScalar_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse1\\StoreLow_r\\StoreLow_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse1\\MoveMask_r\\MoveMask_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse1\\MoveMask_ro\\MoveMask_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse1\\StoreFence_ro\\StoreFence_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse1\\UnpackLow_ro\\UnpackLow_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse1\\Reciprocal_r\\Reciprocal_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse1\\**

R2R windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open

- JIT\\HardwareIntrinsics\\General\\Vector128\\Vector128_r\\Vector128_r.cmd
- JIT\\HardwareIntrinsics\\General\\Vector128_1\\Vector128_1_r\\Vector128_1_r.cmd
- JIT\\HardwareIntrinsics\\General\\Vector128\\Vector128_ro\\Vector128_ro.cmd
- JIT\\HardwareIntrinsics\\General\\Vector128_1\\Vector128_1_ro\\Vector128_1_ro.cmd
- profiler\\elt\\slowpatheltenter\\slowpatheltenter.cmd
- profiler\\elt\\slowpatheltleave\\slowpatheltleave.cmd

R2R windows x64 Checked @ Windows.10.Amd64.Open

- JIT\\Generics\\ConstrainedCall\\vt1_cs_r\\vt1_cs_r.cmd
- JIT\\Generics\\ConstrainedCall\\vt1_il_d\\vt1_il_d.cmd
- JIT\\Generics\\Constraints\\call_instance01\\call_instance01.cmd
- JIT\\Generics\\Conversions\\Reference\\gentonongen03\\gentonongen03.cmd
- JIT\\Generics\\Instantiation\\delegates\\Delegate014\\Delegate014.cmd
- JIT\\Generics\\Arrays\\ConstructedTypes\\Jagged\\struct03\\struct03.cmd
- JIT\\Generics\\Instantiation\\delegates\\Delegate002\\Delegate002.cmd
- JIT\\Generics\\Conversions\\Reference\\nongentogen01\\nongentogen01.cmd
- JIT\\Generics\\**
```
**One of error message:**
```
Could Not Find C:\h\w\A6010966\w\BF3709C4\e\JIT\HardwareIntrinsics\X86\Sse1\ConvertToInt32_ro\IL-CG2\composite-r2r.dll
Could Not Find C:\h\w\A6010966\w\BF3709C4\e\JIT\HardwareIntrinsics\X86\Sse1\ConvertToInt32_ro\ConvertToInt32_ro.dll.rsp
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'System.Security.Cryptography.Primitives, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. An attempt was made to load a program with an incorrect format.
File name: 'System.Security.Cryptography.Primitives, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
at ILCompiler.CoreRTNameMangler.SanitizeNameWithHash(String literal)
at ILCompiler.CoreRTNameMangler.set_CompilationUnitPrefix(String value)
at ILCompiler.Program.RunSingleCompilation(Dictionary2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary2 unrootedInputFilePaths, HashSet`1 versionBubbleModulesHash, CompilerTypeSystemContext typeSystemContext)
at ILCompiler.Program.Run(String[] args)
at ILCompiler.Program.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\A6010966\w\BF3709C4\uploads\Reports\JIT.HardwareIntrinsics\X86\Sse1\ConvertToInt32_ro\ConvertToInt32_ro.output.txt
Raw output:
BEGIN EXECUTION
ConvertToInt32_ro.dll
TestLibrary.dll
2 file(s) copied.
Response file: C:\h\w\A6010966\w\BF3709C4\e\JIT\HardwareIntrinsics\X86\Sse1\ConvertToInt32_ro\ConvertToInt32_ro.dll.rsp
C:\h\w\A6010966\w\BF3709C4\e\JIT\HardwareIntrinsics\X86\Sse1\ConvertToInt32_ro\IL-CG2\ConvertToInt32_ro.dll
-o:C:\h\w\A6010966\w\BF3709C4\e\JIT\HardwareIntrinsics\X86\Sse1\ConvertToInt32_ro\ConvertToInt32_ro.dll
--targetarch:x64
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\A6010966\p\System..dll
-r:C:\h\w\A6010966\p\Microsoft..dll
-r:C:\h\w\A6010966\p\mscorlib.dll
-r:C:\h\w\A6010966\p\netstandard.dll
-O
" "dotnet" "C:\h\w\A6010966\p\crossgen2\crossgen2.dll" @"C:\h\w\A6010966\w\BF3709C4\e\JIT\HardwareIntrinsics\X86\Sse1\ConvertToInt32_ro\ConvertToInt32_ro.dll.rsp"   -r:C:\h\w\A6010966\w\BF3709C4\e\JIT\HardwareIntrinsics\X86\Sse1\ConvertToInt32_ro\IL-CG2*.dll"
Crossgen2 failed with exitcode - -532462766
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\A6010966\p
C:\h\w\A6010966\w\BF3709C4\e\JIT\HardwareIntrinsics\X86\Sse1\ConvertToInt32_ro\ConvertToInt32_ro.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_HardwareIntrinsics._X86_Sse1_ConvertToInt32_ro_ConvertToInt32_ro_._X86_Sse1_ConvertToInt32_ro_ConvertToInt32_ro_cmd()
```

**Comment by tannergooding** [comment] 2022-03-04 18:32
CC. @echesakovMSFT/@JulieLeeMSFT  closing this as a duplicate of https://github.com/dotnet/runtime/issues/65646

**Comment by tannergooding** [comment] 2022-03-04 18:32
Noting that it's a different test, but this and others are all failing with the same general error.

> Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'System.Security.Cryptography.Primitives, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. An attempt was made to load a program with an incorrect format.
File name: 'System.Security.Cryptography.Primitives, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

and something similar to
> Crossgen2 failed with exitcode - -532462766
Test Harness Exitcode is : 1

**Closed by tannergooding** 2022-03-04 18:32 UTC
Labels: arch-x86, os-windows, arch-x64, area-CodeGen-coreclr
