### ISSUE TITLE
Enum.Format change in behavior between .Net Framework and .Net 5

### ISSUE THREAD

**Issue by ChrisVicary** [dotnet/runtime#56200] opened 2021-07-22 23:31 UTC
Repro:
```csharp
using System;

class Test
{
    [Flags]
    public enum TestEnum { None = 0, Item1 = 1, Item2 = 2, }

    static void Main()
    {
        Console.WriteLine(Enum.Format(typeof(TestEnum), (int)3, "G"));
    }
}
```
.NET Framework: `Item1, Item2`
.NET Core: `3`

---
### Description

While upgrading a project from .Net Framework 4.7.2 to .Net 5 and I noticed a difference in behavior of the EnumConverter.ConvertToString() method when passing an integer value that could represent a combination of flags enum values. Here is some code that reproduces the problem:

	class Program
	{
		[Flags]
		public enum TestEnum { None = 0, Item1 = 1, Item2 = 2, }
                
		static void Main(string[] args)
		{
			var none = TestEnum.None;
			var single = TestEnum.Item1;
			var multiple = TestEnum.Item1 | TestEnum.Item2;

			Console.WriteLine(none);
			Console.WriteLine(single);
			Console.WriteLine(multiple);

			var converter = new EnumConverter(typeof(TestEnum));
			Console.WriteLine(converter.ConvertToString(none));
			Console.WriteLine(converter.ConvertToString(single));
			Console.WriteLine(converter.ConvertToString(multiple));

			Console.WriteLine(converter.ConvertToString((int)none));
			Console.WriteLine(converter.ConvertToString((int)single));
			Console.WriteLine(converter.ConvertToString((int)multiple));
			Console.ReadLine();
		}
	}

Creating a simple console app with the code above, if I compile and run the app against .Net Framework 4.8 the last line outputs: 
`Item1, Item 2`
If I compile and run against .Net 5 the last line outputs:
`3`

I tried to have a look through the code here, compared to reference source and I see quite a few differences in there, but couldn't quite nail down the path that the code is taking to just return the int value as a string rather than calculating the enum value and converting that.

**Comment by KalleOlaviNiemitalo** [comment] 2021-07-23 05:32
IIUC, both versions of EnumConverter call `Enum.Format(type, value, "G")`, where `type` is the enum type and `value` is (Int32)3:

<https://github.com/dotnet/runtime/blob/35964c9215613d66a687ebcb2d7fcd9496390ee7/src/libraries/System.ComponentModel.TypeConverter/src/System/ComponentModel/EnumConverter.cs#L132>

<https://github.com/microsoft/referencesource/blob/5697c29004a34d80acdaf5742d7e699022c64ecd/System/compmod/system/componentmodel/EnumConverter.cs#L170>

In .NET 5.0.8, because value.GetType() is the underlying type rather than the enum type, Enum.Format calls GetEnumName, which returns null, and then falls back to `value.ToString()`, i.e. "3":

<https://github.com/dotnet/runtime/blob/35964c9215613d66a687ebcb2d7fcd9496390ee7/src/libraries/System.Private.CoreLib/src/System/Enum.cs#L866-L868>

In Reference Source, Enum.Format instead calls InternalFormat, which checks for FlagsAttribute:

<https://github.com/microsoft/referencesource/blob/5697c29004a34d80acdaf5742d7e699022c64ecd/mscorlib/system/enum.cs#L661-L663>\
<https://github.com/microsoft/referencesource/blob/5697c29004a34d80acdaf5742d7e699022c64ecd/mscorlib/system/enum.cs#L138>

AFAIK, TypeConverter.ConvertTo is not generally expected to support conversions from types other than the type for which the TypeConverter was constructed. EnumConverter however has deliberately supported conversions from the underlying type of the enum. (It has also supported conversions from other types that implement IConvertible.ToType to the underlying type of the enum, but I don't know whether that has been deliberate.)

I think Enum.Format was broken by <https://github.com/dotnet/coreclr/pull/6645>. It is a public method, so the misbehaviour should be reproducible also as `Enum.Format(typeof(TestEnum), 3, CultureInfo.InvariantCulture)` without involving EnumConverter. From the [Enum.Format documentation](https://docs.microsoft.com/en-us/dotnet/api/system.enum.format?view=net-5.0), this use seems to be valid.

**Comment by KalleOlaviNiemitalo** [comment] 2021-07-23 05:39
Enum.Format was partially fixed in <https://github.com/dotnet/coreclr/pull/10610> for <https://github.com/dotnet/runtime/issues/20845> but that fix does not check for FlagsAttribute.

**Comment by ChrisVicary** [comment] 2021-07-24 04:52
From the comments by @KalleOlaviNiemitalo it looked like a pretty straight forward fix, so I've gone ahead and taken a stab at it. Added an extra test that failed without my change, ran the tests afterwards. This is my first PR for .net stuff, I've tried to follow all the guidelines, but please let me know if there is anything that I've missed or should be doing.

**Closed** 2021-07-28 13:37 UTC
Labels: area-System.Runtime, in pr
