### ISSUE TITLE
System.Exception: Exception of type 'System.Exception' was thrown.

### ISSUE THREAD

**Issue by HASSEN-MEDDEB-ATOS** [dotnet/runtime#41301] opened 2020-08-24 23:03 UTC
Hello,

i used httpClient to import contract from Webservices, but after 3 minutes i get error 
```
System.Exception: Exception of type 'System.Exception' was thrown.
25/08/2020 00:44:15   | Unexpected error! :
System.AggregateException: One or more errors occurred. (Exception of type 'System.Exception' was thrown.)
 ---> System.Exception: Exception of type 'System.Exception' was thrown.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
```
Platform : .NET Core 3.1

this is my code 

```c#
namespace PROJECT_Contracts
{
    public static class CTR_WS_Connection
    {
      
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;

                CustomDelegatingHandler customDelegatingHandler = new CustomDelegatingHandler();
                HttpClient client = HttpClientFactory.Create(customDelegatingHandler);
				string urlAppelWS = URL + "&startDate=" + startDate + "&endDate=" + EndDate + "&count=100";

                while (!string.IsNullOrEmpty(urlAppelWS)) //appel du web service en boucle (pour le parcours de la pagination) jusqu'à ce que l'on ait plus de page suivante
                {

                    HttpResponseMessage response = await client.GetAsync(urlAppelWS);
					if (response.StatusCode != HttpStatusCode.OK)
                        throw new Exception();

                    string responsedata = await response.Content.ReadAsStringAsync();

                    Contract Contrats = JsonConvert.DeserializeObject<Contract>(responsedata);
                    if (Contrats.results.Length == 0)
                    {
                        break;
                    }
                    urlAppelWS = string.IsNullOrEmpty(Contrats.nextResults) ? string.Empty : URL + Contrats.nextResults.Split('?')[1];
                    Console.WriteLine("Nouvelle page de contrats : {0} contrats", Contrats.results.Length);
                }
                LogHelper.Writer(string.Format("Temps d'extraction des contrats depuis le web service : {0} ms soit {1} s", elapsedMs, elapsedMs / 1000));

                            
            
        

        public class CustomDelegatingHandler : DelegatingHandler
        {
           

            public static string UpperCaseUrlEncode(string s)
            {
                char[] temp = HttpUtility.UrlEncode(s).ToCharArray();
                for (int i = 0; i < temp.Length - 2; i++)
                {
                    if (temp[i] == '%')
                    {
                        temp[i + 1] = char.ToUpper(temp[i + 1]);
                        temp[i + 2] = char.ToUpper(temp[i + 2]);
                    }
                }
                return new string(temp);
            }

            protected async override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
            {
                
                HttpResponseMessage response = null;

                _applicationId = PROJECT_Settings.DocumentElement.SelectSingleNode("//PROJECT_Contracts_Settings//HmacID").InnerText;
                _secretKey = PROJECT_Settings.DocumentElement.SelectSingleNode("//PROJECT_Contracts_Settings//HmacSecret").InnerText;

                var _secretKeyUTF8 = UTF8Encoding.UTF8.GetBytes(_secretKey);
                string nonce = Guid.NewGuid().ToString("N");

                var gbCulture = new CultureInfo("en-GB");
                // Get current UTC time.   
                var utcDate = DateTime.UtcNow;

                var utcFormattedDate = utcDate.ToString("ddd, dd MMM yyyy HH:mm:ss", gbCulture)+" GMT";


                //string Date = "date:" + UpperCaseUrlEncode(str);
                string Date = "date: " + utcFormattedDate;
                //Date = "date:Thu%2C+21+Apr+2016+13%3A32%3A18+UTC";
                using (HMACSHA1 hmac = new HMACSHA1(_secretKeyUTF8))
                {
                    byte[] Datebytes = Encoding.UTF8.GetBytes(Date);
                    byte[] hashedValue = hmac.ComputeHash(Datebytes);
                    string Signature = Convert.ToBase64String(hashedValue);
                    string Url_Encoded_Signature = UpperCaseUrlEncode(Signature);

                    request.Headers.Add("Authorization", string.Format("Signature keyId=\"{0}\",algorithm=\"{1}\",signature=\"{2}\"", _applicationId, "hmac-sha1", Url_Encoded_Signature));
                    var field = typeof(System.Net.Http.Headers.HttpRequestHeaders)
                                .GetField("invalidHeaders", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static)
                              ?? typeof(System.Net.Http.Headers.HttpRequestHeaders)
                                .GetField("s_invalidHeaders", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static);
                    if (field != null)
                    {
                        var invalidFields = (HashSet<string>)field.GetValue(null);
                        invalidFields.Remove("Content-Type");
                    }
                    request.Headers.Add("Date", utcFormattedDate);
                    request.Headers.TryAddWithoutValidation("Content-Type", "application/json;charset=UTF-8");
                    
                    
                }
                response = await base.SendAsync(request, cancellationToken)
                         .ContinueWith<HttpResponseMessage>(task =>
                         {
                             return task.Result;
                         }).ConfigureAwait(false);
                return response;
            }
        }
    }
}

```
Thanks for any suggestion

Cordially

**Comment by danmosemsft** [comment] 2020-08-25 00:11
Hello, can you please reduce to a short set of code that reproduces the problem? Say, less than 100 lines ideally that I can run on its own? 

There is not enough info here to know where to route the issue.

**Comment by halter73** [comment] 2020-08-25 19:39
While there isn't a ton to go on in this issue, it's not common for the framework to directly throw an `Exception` instead of a derived type, so I'd be highly suspicious of the following:

```
					if (response.StatusCode != HttpStatusCode.OK)
                        throw new Exception();
```

`response.EnsureSuccessStatusCode()` will throw a more helpful exception if the status code isn't in the 200-299 range.

I'd have to see how the exception is being logged to understand why the stack trace is so unhelpful, but the stack trace can probably be improved using ExceptionDispatchInfo.

**Comment by karelz** [comment] 2021-01-15 11:31
Looks like the problem is likely caused by the user code (see above comment). Closing.

**Closed by karelz** 2021-01-15 11:31 UTC
Labels: area-System.Net.Http, needs more info
