### ISSUE TITLE
Reusing SmtpClient hangs in net50

### ISSUE THREAD

**Issue by chrisaut** [dotnet/runtime#49340] opened 2021-03-08 23:32 UTC
Calling `SendMailAsync` multiple times on the same `SmtpClient` instance fails under some circumstances in net50.

### Description

The following test succeeds when running under netcoreapp3.1, but fails by timing out in net50

```C#
[Fact(Timeout = 10000)]
public async Task Net50Repo()
{
    var config = Configuration.Configure();
    using var server = SimpleSmtpServer.Start(config.WithRandomPort().Port);
    var inst = new SmtpClient
    {
        Host = "localhost",
        Port = server.Configuration.Port,
        EnableSsl = false
    };

    for (int messageNo = 0; messageNo < 2; messageNo++)
    {
        var mailMessage = new MailMessage("one@example.com", "two@example.com");

        await inst.SendMailAsync(mailMessage);

        Assert.Equal(messageNo + 1, server.ReceivedEmailCount);
    }
}
```
The issue seems to be reusing the `SmtpClient`, the first `SendMailAsync` succeeds, but the second call always just hangs indefinitely.

Works in 3.1. Newing up a new client for each call also works. Testing against a different Smtp server (eg. Papercut) also works.

netDumpster just ends up waiting inside `SmtpContext` on this line:

`count = this.socket.Receive(byteBuffer);`
It's like if the socket remains open it cannot be reused anymore for some reason. Any idea what changed?

### Configuration

We are able to reproduce with netdumpster in unit tests, production is not yet running in net50 for us (partly because of this), so I'm unsure if other smtp server are effected, we are nervous about this.

### Regression?

Yes, regression from 3.1 to 5

### Other information

I originally raised the issue on [netdumpster](https://github.com/cmendible/netDumbster/issues/30), there is some more discussion there, although not much.

I am aware that other issues mention `SmtpClient` is not under active development, and it seems MS recommends migrating to MailKit, but it would still be nice if existing functionality would not break.

@cmendible @scalablecory

**Comment by ManickaP** [comment] 2021-03-11 17:27
Triage: we should investigate here. Potentially improve our tests to cover this.

**Comment by wfurt** [comment] 2021-03-11 18:04
I did quick check and I cannot reproduce it @chrisaut. Tested on Ubuntu18 agains Postfix. 

What OS do you use? Can you do packet captures with Wireshark? Perhaps we can see more there.

**Comment by chrisaut** [comment] 2021-03-12 09:24
> I did quick check and I cannot reproduce it @chrisaut. Tested on Ubuntu18 agains Postfix.

I/we are on windows testing against netdumpster. Easiest to repro with this: https://github.com/cmendible/netDumbster/tree/dotnet5
The test called "Reusing_Smtp_Client_Should_Not_Fail" succeeds in 3.1 and fails in 5.0

> What OS do you use? Can you do packet captures with Wireshark? Perhaps we can see more there.

Windows. I can probably get some captures if needed, but you should be able to repro with the branch above.

Just to be clear again, we originally thought this was a netdumpster (a fake smtp server for tests) issue, however it functions perfectly in older frameworks, and against other smtp clients. Upgrading t onet50 breaks using SmtpClient.

Like mentioned before, there was a bit of discussion earlier [here](https://github.com/cmendible/netDumbster/issues/30)

**Comment by cmendible** [comment] 2021-03-12 09:36
@wfurt if needed I can modify the code in the branch removing everything that is not needed to repro the issue. Just let me know

**Comment by wfurt** [comment] 2021-03-12 18:33
I'll try it next week on Windows. If I can reproduce triage should not be too hard IMHO. Part of it is also impact and that drives priority.

**Comment by karelz** [comment] 2021-03-18 16:24
Triage: If we have simple repro and idea what to fix, we should invest. If it proves difficult, I would punt it to Future.

**Comment by karelz** [comment] 2021-11-05 05:33
The needs more info was bogus. Reopening.

**Comment by BrunoJuchli** [comment] 2022-05-17 19:00
FYI because possibly connected:

I'm reusing the same `SmtpClient` instance to send multiple e-mails via synchronous `Send(MailMessage)` method.

- on .net Framework 4.7.2 and 4.8 this works without issue
- on .net 6 same code results in the server closing the socket  and reporting a timeout:
  >SmtpException: Service not available, closing transmission channel. The server response was: Timeout. Try talking faster next time
   at System.Net.Mail.MailCommand.CheckResponse(SmtpStatusCode statusCode, String response)
   at System.Net.Mail.MailCommand.Send(SmtpConnection conn, Byte[] command, MailAddress from, Boolean allowUnicode)
   at System.Net.Mail.SmtpTransport.SendMail(MailAddress sender, MailAddressCollection recipients, String deliveryNotify, Boolean allowUnicode, SmtpFailedRecipientException& exception)
   at System.Net.Mail.SmtpClient.Send(MailMessage message)

I'll change the implementation to use a new instance for every e-mail and report back if this has remedied the issue.

**Comment by BrunoJuchli** [comment] 2022-05-30 18:51
I finally got around deploying this to production. And yes, once I've moved to disposing the `SmtpClient` every time I send, [my timeout exceptions](https://github.com/dotnet/runtime/issues/49340#issuecomment-1129214691) vanished magically.
Also note, that the timeout exceptions happened on .net 6 on Windows as well as on Linux nodes (we moved to Linux in the meantime but this didn't change anything. Then adding the `Dispose()` helped).

**Comment by vonzshik** [comment] 2022-05-31 09:01
I've done a small investigation, and the problem was introduced with #683. Or, to be precise, it was uncovered by it. The main problem is the fact that SmptClient attempts to open another connection every time `SendAsync` is called, even if the connection is open.

https://github.com/dotnet/runtime/blob/265988529080aa6e88f1d2ea12d9c080c93465e4/src/libraries/System.Net.Mail/src/System/Net/Mail/SmtpClient.cs#L651-L653

https://github.com/dotnet/runtime/blob/265988529080aa6e88f1d2ea12d9c080c93465e4/src/libraries/System.Net.Mail/src/System/Net/Mail/SmtpTransport.cs#L119-L132

And compare this to `Send`.

https://github.com/dotnet/runtime/blob/265988529080aa6e88f1d2ea12d9c080c93465e4/src/libraries/System.Net.Mail/src/System/Net/Mail/SmtpClient.cs#L499-L507

https://github.com/dotnet/runtime/blob/265988529080aa6e88f1d2ea12d9c080c93465e4/src/libraries/System.Net.Mail/src/System/Net/Mail/SmtpClient.cs#L982-L988

Unlike sync implementation, async doesn't check whether `_transport.IsConnected` is `true` or not.

**Comment by wfurt** [comment] 2022-05-31 11:54
do you want to contribute PR @vonzshik ?

**Comment by vonzshik** [comment] 2022-05-31 12:41
@wfurt sure, though it might take a bit of time (hopefully, building the runtime shouldn't be too hard 😄)

**Closed** 2022-06-29 10:25 UTC
Labels: bug, area-System.Net, in-pr
