### ISSUE TITLE
AssemblyLoadContext.Load/.LoadUnmanagedDll  default fallback

### ISSUE THREAD

**Issue by John0King** [dotnet/runtime#37231] opened 2020-06-01 04:55 UTC
In my project of using the `AssemblyLoadContext` ,  I want to do multiple level of isolation of the AssemblyLoad, so it need to fallbak to **parent** `AssemblyLoadContext`   instead of `AssemblyLoadContext.Default` ,

but the method `LoadUmanagedDll` is a `protected` method , so I can not access it, and I think the 
`base.LoadUmanagedDll()`  method should do this for me , by using the `AssemblyLoadContext.CurrentContextualReflectionContext` ,  and I search the code from github and I can not find that method,  so will the `base.LoadUmanagedDll(), base.Load`  fallback to parent AssemblyLoadContext?

here is my code 
https://github.com/John0King/LazyMan.ModularLoader/blob/4a0ce58623a25a93ea2082da62410993fbc784bd/src/LazyMan.ModularLoader/Internal/PluginAssemblyLoadContext.cs#L117-L129

and there is a question about `CurrentContextualReflectionContext` : 
  `CurrentContextualReflectionContext`  is  null by default  or for the "Default" `AssemblyLoadContext` is null , and newly created is  current AssemblyLoadContext ?

**Comment by vitek-karas** [comment] 2020-06-01 09:51
This is basically a duplicate of https://github.com/dotnet/runtime/issues/13472.
If you control the ALC in question you can expose the method by providing a public version which calls the protected one. You don't need to call `LoadUmanagedDll` on Default ALC as that will always return `IntPtr.Zero`, just like base also returns `IntPtr.Zero` (that's exactly what `AssemblyLoadContext.LoadUmanagedDll` does). This falls back to the default resolution logic in the runtime - which is the behavior you get in Default ALC.

Regarding `CurretContextualReflectionContext`: Short version - don't use this unless you need to. Long version - https://github.com/dotnet/runtime/blob/master/docs/design/features/AssemblyLoadContext.ContextualReflection.md.
Please note that the value of this property does NOT change automatically and it definitely won't help with implementing ALC itself. It's meant as a workaround for code which is not ALC aware, but should be.

**Closed by vitek-karas** 2020-06-01 09:51 UTC
Labels: area-AssemblyLoader-coreclr, untriaged
