### ISSUE TITLE
Missing dependency of Microsoft.Windows.Compatibility 6.0.0-preview.6.21352.12

### ISSUE THREAD

**Issue by adityapatwardhan** [dotnet/runtime#55952] opened 2021-07-16 23:48 UTC
Microsoft.Windows.Compatibility 6.0.0-preview.6.21352.12 nuget package depends on System.Data.SqlClient 4.8.2-preview.6.21352.12 which is not available on nuget.org.

![image](https://user-images.githubusercontent.com/12820925/126018333-ed5df8a7-6377-4e66-9eb1-bf31057278a5.png)

Latest version on nuget.org as of 07/16/2021

![image](https://user-images.githubusercontent.com/12820925/126018354-793f77e8-ca4d-4906-b4c0-23773054afdf.png)

**Comment by ericstj** [comment] 2021-07-19 19:07
This was regressed in https://github.com/dotnet/runtime/commit/663c40dbc4ccedf82e38e96391c28695da0e418f#diff-1ea18ff65faa2ae6fed570b83747086d0317f5e4bc325064f6c14319a9c4ff67R82.

Issue tracking test gap is: https://github.com/dotnet/runtime/issues/27503

**Comment by safern** [comment] 2021-07-19 19:14
@ericstj I believe the version was already 4.8.2 before that change: https://github.com/dotnet/runtime/commit/663c40dbc4ccedf82e38e96391c28695da0e418f#diff-09672eb44efbabed67d14b36b7527147631443f94bcf00b7ea6fe7992e4f1669L55

I believe the problem is that we are setting `System.Data.SqlClient` as an `IndexedDependency` and the `packageIndex.json` is not up to date, it is missing the `4.8.2` stable version so we are treating it as a prerelease. That's why it has the prerelease label on the dependency version.

I believe the right fix is to make that library an `ExternalDependency` just as the service model ones so that we don't depend on the index being up to date.

I can submit a fix for this one and port it to Preview7

**Comment by ericstj** [comment] 2021-07-19 21:06
Do you think we should fix the Preview6 build of the package as well, perhaps by manually building & signing it?

**Comment by Anipik** [comment] 2021-07-19 21:19
I think we should do it as the package is currently in broken state and the next release a month away. we should also see if we run any package testing here. we have hit similar issues with this package before.

**Comment by ericstj** [comment] 2021-07-19 21:21
I just prepared a sample fix for package testing, haven't tried it yet.  Let's keep that part of the discussion in https://github.com/dotnet/runtime/issues/27503.

**Comment by safern** [comment] 2021-07-19 21:31
> Do you think we should fix the Preview6 build of the package as well, perhaps by manually building & signing it?

Yes we could try doing that... maybe merging it to Preview6 so that it goes through the internal official builds?

**Comment by ericstj** [comment] 2021-07-19 21:43
Preview6 is already published on nuget.org.  I'd say just do a minor fixup and manual resign.  I believe we've done this before for nuspec issues.

**Comment by ericstj** [comment] 2021-07-19 23:13
> I believe the version was already 4.8.2 before that change

Ahh, right it was https://github.com/dotnet/runtime/commit/6ccbbdeca83e64420051af41419ec393f62580a8

**Closed** 2021-07-20 19:13 UTC
Labels: area-Infrastructure-libraries, in pr, untriaged

**Comment by ericstj** [comment] 2021-07-21 16:42
> Do you think we should fix the Preview6 build of the package as well, perhaps by manually building & signing it?

I did this: https://www.nuget.org/packages/Microsoft.Windows.Compatibility/6.0.0-preview.6.21352.13

**Comment by safern** [comment] 2021-07-21 17:23
Thanks! I was about to reach out to do it.
