### ISSUE TITLE
Http/2 Post With Large Message Size Hangs Until Timeout

### ISSUE THREAD

**Issue by zmhh** [dotnet/runtime#48736] opened 2021-02-25 01:54 UTC
### Description

Our testing regarding .NET 5 HTTP/2 showed bad performance relative to HTTP/1.1 for large message sizes combined with high latency. I suspected it was related to #43086.

In order to investigate and report the issue I wanted to create a benchmark which reproduces the issue. However, my benchmark has an issue where it is hanging with large message sizes. Please see the Reproduction section below.

### Configuration

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.18362.900 (1903/May2019Update/19H1)
Intel Core i9-9880H CPU 2.30GHz, 1 CPU, 16 logical and 8 physical cores
.NET Core SDK=5.0.102
[Host] : .NET Core 5.0.2 (CoreCLR 5.0.220.61120, CoreFX 5.0.220.61120), X64 RyuJIT
Job-VXCWEG : .NET Core 5.0.2 (CoreCLR 5.0.220.61120, CoreFX 5.0.220.61120), X64 RyuJIT

### Reproduction

When running the code below, note that `Http1_Post_LargeRequest` works fine, `Http2_Post_MediumRequest` works fine, but `Http2_Post_LargeRequest` hangs until timing out. Note that the actual message size is larger than the byte arrays, because converting the random byte arrays to UTF8 string makes it larger.

To run, add the code below to `Program.cs` in a project called `BenchmarkApplication.csproj` and run the following commands:
`dotnet run -c Release BenchmarkApplication.csproj -f net5.0 --runtimes netcoreapp50 --filter *Http1_Post_LargeRequest*`
`dotnet run -c Release BenchmarkApplication.csproj -f net5.0 --runtimes netcoreapp50 --filter *Http2_Post_MediumRequest*`
`dotnet run -c Release BenchmarkApplication.csproj -f net5.0 --runtimes netcoreapp50 --filter *Http2_Post_LargeRequest*`

Code:

```c#
using System;
using System.Net;
using System.Net.Http;
using System.Net.Security;
using System.Security.Authentication;
using System.Text;
using System.Threading.Tasks;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Server.Kestrel.Core;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace BenchmarkApplication
{
    public class Program
    {
        static void Main(string[] args)
        {
            BenchmarkSwitcher.FromAssembly(typeof(Program).Assembly).Run(args);
        }
    }

    [MemoryDiagnoser]
    public class Benchmark
    {
        private IHost _host;
        private HttpClient _http1Client;
        private HttpClient _https1Client;
        private HttpClient _http2Client;
        private HttpClient _https2Client;
        private string _smallText;
        private string _mediumText;
        private string _largeText;

        [GlobalSetup]
        public void Setup()
        {
#if NETCOREAPP3_1
            AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);
#endif

            var smallBytes = new byte[1000];
            new Random().NextBytes(smallBytes);
            _smallText = Encoding.UTF8.GetString(smallBytes);

            var mediumBytes = new byte[50000];
            new Random().NextBytes(mediumBytes);
            _mediumText = Encoding.UTF8.GetString(mediumBytes);

            var largeBytes = new byte[65000];
            new Random().NextBytes(largeBytes);
            _largeText = Encoding.UTF8.GetString(largeBytes);

            var certPath = "C:\\src\\devcert.pfx";
            var certPassword = "password";
            _host = Host.CreateDefaultBuilder()
                .ConfigureWebHostDefaults(builder =>
                {
                    builder.UseStartup<Startup>();
                    builder.UseKestrel(options =>
                    {
                        options.ListenAnyIP(5000, listenOptions =>
                        {
                            listenOptions.Protocols = HttpProtocols.Http1;
                        });
                        options.ListenAnyIP(5001, listenOptions =>
                        {
                            listenOptions.Protocols = HttpProtocols.Http1;
                            listenOptions.UseHttps(certPath, certPassword);
                        });
                        options.ListenAnyIP(5002, listenOptions =>
                        {
                            listenOptions.Protocols = HttpProtocols.Http2;
                        });
                        options.ListenAnyIP(5003, listenOptions =>
                        {
                            listenOptions.Protocols = HttpProtocols.Http2;
                            listenOptions.UseHttps(certPath, certPassword);
                        });
                    });
                })
                .Build();
            _host.Start();

            var handler = new SocketsHttpHandler
            {
                SslOptions = new SslClientAuthenticationOptions
                {
                    EnabledSslProtocols = SslProtocols.Tls12,
                    RemoteCertificateValidationCallback = delegate { return true; },
                },
#if NET5_0
                EnableMultipleHttp2Connections = true,
#endif
            };
            _http1Client = new HttpClient(handler)
            {
                BaseAddress = new Uri("http://localhost:5000"),
                DefaultRequestVersion = HttpVersion.Version11,
            };
            _https1Client = new HttpClient(handler)
            {
                BaseAddress = new Uri("https://localhost:5001"),
                DefaultRequestVersion = HttpVersion.Version11
            };
            _http2Client = new HttpClient(handler)
            {
                BaseAddress = new Uri("http://localhost:5002"),
                DefaultRequestVersion = HttpVersion.Version20
            };
            _https2Client = new HttpClient(handler)
            {
                BaseAddress = new Uri("https://localhost:5003"),
                DefaultRequestVersion = HttpVersion.Version20
            };
        }

        [GlobalCleanup]
        public void Cleanup()
        {
            _host.Dispose();
            _http1Client.Dispose();
            _https1Client.Dispose();
            _http2Client.Dispose();
            _https2Client.Dispose();
        }

        [Benchmark]
        public async Task Http1_Get_SmallRequest()
        {
            await MakeSmallGetRequest(_http1Client);
        }

        [Benchmark]
        public async Task Https1_Get_SmallRequest()
        {
            await MakeSmallGetRequest(_https1Client);
        }

        [Benchmark]
        public async Task Http2_Get_SmallRequest()
        {
            await MakeSmallGetRequest(_http2Client);
        }

        [Benchmark]
        public async Task Https2_Get_SmallRequest()
        {
            await MakeSmallGetRequest(_https2Client);
        }

        [Benchmark]
        public async Task Http1_Get_MediumRequest()
        {
            await MakeMediumGetRequest(_http1Client);
        }

        [Benchmark]
        public async Task Https1_Get_MediumRequest()
        {
            await MakeMediumGetRequest(_https1Client);
        }

        [Benchmark]
        public async Task Http2_Get_MediumRequest()
        {
            await MakeMediumGetRequest(_http2Client);
        }

        [Benchmark]
        public async Task Https2_Get_MediumRequest()
        {
            await MakeMediumGetRequest(_https2Client);
        }

        [Benchmark]
        public async Task Http1_Get_LargeRequest()
        {
            await MakeLargeGetRequest(_http1Client);
        }

        [Benchmark]
        public async Task Https1_Get_LargeRequest()
        {
            await MakeLargeGetRequest(_https1Client);
        }

        [Benchmark]
        public async Task Http2_Get_LargeRequest()
        {
            await MakeLargeGetRequest(_http2Client);
        }

        [Benchmark]
        public async Task Https2_Get_LargeRequest()
        {
            await MakeLargeGetRequest(_https2Client);
        }

        [Benchmark]
        public async Task Http1_Post_SmallRequest()
        {
            await MakeSmallPostRequest(_http1Client);
        }

        [Benchmark]
        public async Task Https1_Post_SmallRequest()
        {
            await MakeSmallPostRequest(_https1Client);
        }

        [Benchmark]
        public async Task Http2_Post_SmallRequest()
        {
            await MakeSmallPostRequest(_http2Client);
        }

        [Benchmark]
        public async Task Https2_Post_SmallRequest()
        {
            await MakeSmallPostRequest(_https2Client);
        }

        [Benchmark]
        public async Task Http1_Post_MediumRequest()
        {
            await MakeMediumPostRequest(_http1Client);
        }

        [Benchmark]
        public async Task Https1_Post_MediumRequest()
        {
            await MakeMediumPostRequest(_https1Client);
        }

        [Benchmark]
        public async Task Http2_Post_MediumRequest()
        {
            await MakeMediumPostRequest(_http2Client);
        }

        [Benchmark]
        public async Task Https2_Post_MediumRequest()
        {
            await MakeMediumPostRequest(_https2Client);
        }

        [Benchmark]
        public async Task Http1_Post_LargeRequest()
        {
            await MakeLargePostRequest(_http1Client);
        }

        [Benchmark]
        public async Task Https1_Post_LargeRequest()
        {
            await MakeLargePostRequest(_https1Client);
        }

        [Benchmark]
        public async Task Http2_Post_LargeRequest()
        {
            await MakeLargePostRequest(_http2Client);
        }

        [Benchmark]
        public async Task Https2_Post_LargeRequest()
        {
            await MakeLargePostRequest(_https2Client);
        }

        private async Task MakeSmallGetRequest(HttpClient client)
        {
            using var request = new HttpRequestMessage(HttpMethod.Get, new Uri(client.BaseAddress, "/smallTest"))
            {
                Version = client.DefaultRequestVersion,
#if NET5_0
                VersionPolicy = HttpVersionPolicy.RequestVersionExact,
#endif
            };
            using var response = await client.SendAsync(request);
        }

        private async Task MakeMediumGetRequest(HttpClient client)
        {
            using var request = new HttpRequestMessage(HttpMethod.Get, new Uri(client.BaseAddress, "/mediumTest"))
            {
                Version = client.DefaultRequestVersion,
#if NET5_0
                VersionPolicy = HttpVersionPolicy.RequestVersionExact,
#endif
            };
            using var response = await client.SendAsync(request);
        }

        private async Task MakeLargeGetRequest(HttpClient client)
        {
            using var request = new HttpRequestMessage(HttpMethod.Get, new Uri(client.BaseAddress, "/largeTest"))
            {
                Version = client.DefaultRequestVersion,
#if NET5_0
                VersionPolicy = HttpVersionPolicy.RequestVersionExact,
#endif
            };
            using var response = await client.SendAsync(request);
        }

        private async Task MakeSmallPostRequest(HttpClient client)
        {
            using var request = new HttpRequestMessage(HttpMethod.Post, new Uri(client.BaseAddress, "/smallTest"))
            {
                Version = client.DefaultRequestVersion,
#if NET5_0
                VersionPolicy = HttpVersionPolicy.RequestVersionExact,
#endif
                Content = new StringContent(_smallText)
            };
            using var response = await client.SendAsync(request);
        }

        private async Task MakeMediumPostRequest(HttpClient client)
        {
            using var request = new HttpRequestMessage(HttpMethod.Post, new Uri(client.BaseAddress, "/mediumTest"))
            {
                Version = client.DefaultRequestVersion,
#if NET5_0
                VersionPolicy = HttpVersionPolicy.RequestVersionExact,
#endif
                Content = new StringContent(_mediumText)
            };
            using var response = await client.SendAsync(request);
        }

        private async Task MakeLargePostRequest(HttpClient client)
        {
            using var request = new HttpRequestMessage(HttpMethod.Post, new Uri(client.BaseAddress, "/largeTest"))
            {
                Version = client.DefaultRequestVersion,
#if NET5_0
                VersionPolicy = HttpVersionPolicy.RequestVersionExact,
#endif
                Content = new StringContent(_largeText)
            };
            using var response = await client.SendAsync(request);
        }
    }

    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddLogging(
                builder =>
                {
                    builder.AddFilter("Microsoft", LogLevel.Warning)
                        .AddFilter("System", LogLevel.Warning);
                });
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseRouting();
            app.UseEndpoints(endpoints =>
            {
                var smallBytes = new byte[1000];
                new Random().NextBytes(smallBytes);
                var smallText = Encoding.UTF8.GetString(smallBytes);

                var mediumBytes = new byte[50000];
                new Random().NextBytes(mediumBytes);
                var mediumText = Encoding.UTF8.GetString(mediumBytes);

                var largeBytes = new byte[65000];
                new Random().NextBytes(largeBytes);
                var largeText = Encoding.UTF8.GetString(largeBytes);

                endpoints.MapGet("/smallTest", context => context.Response.WriteAsync(smallText));
                endpoints.MapGet("/mediumTest", context => context.Response.WriteAsync(mediumText));
                endpoints.MapGet("/largeTest", context => context.Response.WriteAsync(largeText));

                endpoints.MapPost("/smallTest", context => context.Response.WriteAsync(smallText));
                endpoints.MapPost("/mediumTest", context => context.Response.WriteAsync(mediumText));
                endpoints.MapPost("/largeTest", context => context.Response.WriteAsync(largeText));
            });
        }
    }
}
```

**Comment by ManickaP** [comment] 2021-03-04 17:06
Triage: we should investigate, try to confirm the problem.

**Comment by karelz** [comment] 2021-05-06 17:51
@zmhh is there any chance you can create a smaller repro? (there is lots of benchmarks above) Thanks!

**Comment by zmhh** [comment] 2021-05-06 20:34
Hi @karelz , `Http2_Post_LargeRequest` is the only one that hangs, so you can try deleting everything except that.

**Comment by zmhh** [comment] 2021-05-06 21:56
If uanble to repro it seems fine to close, since work on #43086 may resolve it anyway.

**Comment by karelz** [comment] 2021-05-07 09:15
Duplicate of #43086

**Closed by karelz** 2021-05-07 09:15 UTC
Labels: area-System.Net.Http
