### ISSUE TITLE
Environment variable is not set when running published desktop app

### ISSUE THREAD

**Issue by sam-wheat** [dotnet/runtime#71104] opened 2022-06-21 23:36 UTC
### Description

When an executable is published, no equivalent of `launchSettings.json` is deployed alongside to ensure an environment variable such as `DOTNET_ENVIRONMENT` is set correctly prior to program execution.

### Reproduction Steps

Create a publish profile.
Add environment information as shown:

    <Project>
        <PropertyGroup>
	        <ASPNETCORE_ENVIRONMENT>qa</ASPNETCORE_ENVIRONMENT>
        </PropertyGroup>
      <PropertyGroup>
        <Configuration>Release</Configuration>
        <Platform>Any CPU</Platform>
        <PublishDir>bin\Release\net6.0-windows\publish\</PublishDir>
        <PublishProtocol>FileSystem</PublishProtocol>
      </PropertyGroup>
    </Project>

Publish the project and run the .exe.  

### Expected behavior

Environment variable is set prior to program execution.  Environment info is stored in some file such as `app.runtimeconfig.json`.
This behavior would be consistent with the development workflow defined by Visual Studio i.e. `launchSettings.json`

### Actual behavior

`DOTNET_ENVIRONMENT` is not set and the program runs as if it is configured for Production (default if environment variable is not set).

### Known Workarounds

None.  The only way set the environment variable on behalf of the user is to write a batch file.

### Configuration

dotnet 6, Windows 10, Visual Studio 2022.

**Comment by eerhardt** [comment] 2022-06-22 00:30
What is your scenario for wanting an environment set for the application? If you just want some settings to be deployed with your app, you can use appsettings.json and read it from the IConfiguration.

**Comment by sam-wheat** [comment] 2022-06-22 02:40
> you can use appsettings.json and read it from the IConfiguration

We don't the name of the config until we know the environment name i.e. appsetings.{environment}.json
We like the Visual Studio workflow i.e. environment is set/maintained external to code.  
What I am asking for is basically carrying forward the VS workflow to the deployment environment.

**Comment by eerhardt** [comment] 2022-06-22 03:49
Are you deploying to “production”?

In general, you wouldn’t deploy the other environment’s appsettings.json files with your app. You would just deploy the settings that are relevant for the deployment you are publishing for.

> What I am asking for is basically carrying forward the VS workflow to the deployment environment.

in order to do that, you would need some other app to launch your app with the environment variables set - or a batch file like you said above.

**Comment by sam-wheat** [comment] 2022-06-22 05:00
Why do I need another app to launch my app? Can the publish process do that for me and why is the workflow different than the one in visual studio.  It seems like a big disconnect.

**Comment by eerhardt** [comment] 2022-06-22 12:48
> Why do I need another app to launch my app? 

In your expected behavior above you say “ Environment variable is set prior to program execution.” How else do you propose getting that env var set?

> Can the publish process do that for me 

No. That isn’t available in the publish process. The publish process isn’t contained in this repo, so if you’d like it changed, you would need to log an issue in dotnet/sdk.

> why is the workflow different than the one in visual studio.

VS is simulating your real hosting environment. A real hosting environment (cloud provider, hosted web site, etc.) will have its own ways to set environment variables. If you aren’t developing a web app, but instead a client app, your apps installer can set environment variables. If your app is an xcopy app with no installer, then there is no other way than a batch file or a launcher app that sets the env var.

You could have your own logic at the beginning of the app that reads whatever file it wants and sets the env var before any other logic in your app runs. But that doesn’t meet your expected behavior.

In the end, the visual studio behavior of reading the launchsettings.json file and setting env vars for the process is a development time only solution for simulating what a real hosted deployed app runs under. Where the env vars for the real deployed app are loaded from depends on where the app is deployed to. The point of making them environment variables is so you don’t need to change the apps files to change the behavior of the app. But if you want the setting to be deployed with your app, you can put the settling in a file and read it from there.

**Comment by eerhardt** [comment] 2022-06-22 14:46
I think we are talking past each other.

Can you explain your scenario/situation from end-to-end? I don't understand what you are trying to accomplish.

**Comment by eerhardt** [comment] 2022-06-22 16:09
The `launchSettings.json` file is only used at development time by Visual Studio. That file doesn't affect your published app. It is by design that file doesn't affect your published app.

> Please tell me the steps I need to do to accomplish this.

You have a few options (that I know of) that you pick from:

1. Tell your QA testers to set the environment variable `DOTNET_ENVIRONMENT=qa` on their machines or command prompt before launching the app.
2. Publishing a batch file that sets the env var and then launches your app. Tell the QA testers to use that batch file to launch the app.
3. Change Program.cs to have 
```C#
#if DEBUG
Environment.SetEnvironmentVariable("DOTNET_ENVIRONMENT", "qa");
#endif
```
And publish your app with the `Debug` configuration.

Closing since what is being asked for here is not possible to fix in dotnet/runtime.

**Closed by eerhardt** 2022-06-22 16:09 UTC
Labels: untriaged, area-Extensions-Configuration

**Comment by eerhardt** [comment] 2022-06-22 16:43
What you are asking for cannot be fixed in dotnet/runtime. dotnet/runtime contains the code that runs inside your app's process (the CLR and core .NET libraries). You are asking for an environment variable to be set prior to your app being executed, which is not possible in the code that is running in your application.

> I would like to see a more seamless solution

Feel free to send feedback in Visual Studio (Help -> Send Feedback -> Suggest a Feature) to suggest that VS publish support this scenario.
