### ISSUE TITLE
TarFile fails to extract even when symbolic link references into the output directory

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#77303] opened 2022-10-21 06:37 UTC
I already have an open issue about TarFile not wanting to create symbolic links that point outside the output directory: https://github.com/dotnet/runtime/issues/74140. 

Triggered by https://github.com/dotnet/runtime/issues/77096, I was curious to see if `podman` would have the same issue as `docker`.

I did:
```
$ podman pull hello-world
$ podman save hello-world -o hello-world.tar # uncompressed when saving a local image
```

The resulting archive fails to extract:
```
Unhandled exception. System.IO.IOException: Extracting the Tar entry '../8e128b102ca8161cb297e3aa73240b8e537af67422fd4c22bf43c296c91d13ad.tar' would have resulted in a link target outside the specified destination directory: '/tmp/bca4a72dc384466ab6abd59cc585bd5a'
   at System.Formats.Tar.TarEntry.GetDestinationAndLinkPaths(String destinationDirectoryPath)
   at System.Formats.Tar.TarEntry.ExtractRelativeToDirectoryAsync(String destinationDirectoryPath, Boolean overwrite, SortedDictionary`2 pendingModes, CancellationToken cancellationToken)
   at System.Formats.Tar.TarFile.ExtractToDirectoryInternalAsync(Stream source, String destinationDirectoryPath, Boolean overwriteFiles, Boolean leaveOpen, CancellationToken cancellationToken)
   at System.Formats.Tar.TarFile.ExtractToDirectoryInternalAsync(Stream source, String destinationDirectoryPath, Boolean overwriteFiles, Boolean leaveOpen, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in /tmp/console/Program.cs:line 6
   at Program.<Main>(String[] args)
```

The symbolic link it considers problematic is actually still pointing inside the output directory.
These are the archive entries:
```
8e128b102ca8161cb297e3aa73240b8e537af67422fd4c22bf43c296c91d13ad.tar(RegularFile) -> 
c0e8b50899a56dcd91634bfbb7a8336f2c0f6f6a9bbb5ad9b747dc1547aaa9f4.json(RegularFile) -> 
00335d90e4f471aae0fdbae54765dd7a5a1cb276c55c2fc75bf64ab20c5c97d1/layer.tar(SymbolicLink) -> ../8e128b102ca8161cb297e3aa73240b8e537af67422fd4c22bf43c296c91d13ad.tar
00335d90e4f471aae0fdbae54765dd7a5a1cb276c55c2fc75bf64ab20c5c97d1/VERSION(RegularFile) -> 
00335d90e4f471aae0fdbae54765dd7a5a1cb276c55c2fc75bf64ab20c5c97d1/json(RegularFile) -> 
manifest.json(RegularFile) -> 
repositories(RegularFile) -> 
```

cc @carlossanlop @Jozkee @am11

**Comment by am11** [comment] 2022-10-21 08:48
This is a duplicate of https://github.com/dotnet/runtime/issues/74140, right? `podman-hello-world.tar` can be used as a test asset when we have the fix.

**Comment by tmds** [comment] 2022-10-21 08:52
> This is a duplicate of https://github.com/dotnet/runtime/issues/74140, right?

In that case, the symbolic link points outside the output directory.
Here, the symbolic target is still in the output directory.

**Comment by am11** [comment] 2022-10-21 08:52
Ok, I see. It is a bug where we fail to recognize that symlink is in fact pointing to path inside the destination directory (`../8e128b102ca8161cb297e3aa73240b8e537af67422fd4c22bf43c296c91d13ad.tar`) and throw `IOException`.

**Closed** 2022-11-11 21:46 UTC
Labels: area-System.IO, untriaged, in-pr
