### ISSUE TITLE
Codegen generates code referencing RuntimeType for `__Canon[]`

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#101175] opened 2024-04-17 10:26 UTC
This may have a repro with JIT, but I hit this with PublishAot:

```csharp
Activator.CreateInstance(typeof(Foo<>).MakeGenericType(typeof(object)));

class Foo<T>
{
    public Foo() { new T[0].ToString(); }
}
```

Codegen for `Foo..ctor` is:

```
00007FF77E6791D0  push        rbx  
00007FF77E6791D1  sub         rsp,30h  
00007FF77E6791D5  mov         qword ptr [rsp+28h],rcx  
00007FF77E6791DA  mov         rbx,rcx  
00007FF77E6791DD  mov         rcx,qword ptr [rbx]  
00007FF77E6791E0  lea         rcx,[__RuntimeType___Array<System___Canon> (07FF77E6AC918h)]  
00007FF77E6791E7  call        System.RuntimeType__ToString (07FF77E5DF220h)  
00007FF77E6791EC  nop  
00007FF77E6791ED  add         rsp,30h  
00007FF77E6791F1  pop         rbx  
00007FF77E6791F2  ret  
```

Notice an attempt to do a runtime lookup but then codegen changing it's mind and overwriting rcx with a const frozen object for `__Canon[]` `RuntimeType` (which is non-sensical and will crash at runtime).

I'm making the compiler assert on this #101173.

Cc @EgorBo

**Comment by EgorBo** [comment] 2024-04-17 10:33
I don't see any issues in the codegen for CoreCLR here, I think the issue is in the NAOT's implementation for `getRuntimeTypePointer` API, e.g. in CoreCLR it filters out all shared types: https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/jitinterface.cpp#L6191-L6215

Because it's fine for VM internally to allocate cannonical type objects on FOH, isn't? it's just that JIT should never see them

**Comment by MichalStrehovsky** [comment] 2024-04-17 10:41
Why does codegen even attempt to do this if there is a runtime lookup? Is it difficult to abort this if there is a runtime lookup? The `typeHnd.IsCanonicalSubtype()` honestly feels like something that should be an assert, unless it's difficult for RyuJIT to know this requires a runtime lookup.

(In theory, on native AOT side it would be easy to allow embedding these into generic dictionaries, so one could actually have a runtime lookup for a frozen RuntimeType instance.)

**Comment by EgorBo** [comment] 2024-04-17 10:54
> Why does codegen even attempt to do this if there is a runtime lookup? Is it difficult to abort this if there is a runtime lookup

I think it happens just because JIT doesn't expect EE for `getRuntimeTypePointer` to return cannonical type so it doesn't bother checking. It can be fixed on all uses of `getRuntimeTypePointer` in JIT to check CLS for being `info.compCompHnd->getClassAttribs(handle) & CORINFO_FLG_SHAREDINST) == 0`, but I think it's better to do on VM side (less changes, less chances for future bugs).

Here is the place where we create it for this case: https://github.com/dotnet/runtime/blob/3e569f5696ddf6c93e56eeaaf1703bb64e561f1b/src/coreclr/jit/valuenum.cpp#L11915-L11922

**Comment by MichalStrehovsky** [comment] 2024-04-17 10:57
OK, I'll add this on the VM side then.

Can you quickly point me to where are the tests for these?

**Comment by EgorBo** [comment] 2024-04-17 11:02
> Can you quickly point me to where are the tests for these?

I don't think there are dedicated tests for RuntimeType being frozen, but there are a lot of typeof(T) related tests in runtime tests. Typically, for bugs, we add new tests under https://github.com/dotnet/runtime/tree/main/src/tests/JIT/Regression/JitBlue with github Id as a name

**Closed** 2024-04-18 19:51 UTC
Labels: untriaged, area-NativeAOT-coreclr
