### ISSUE TITLE
System.Diagnostics.Eventing.Reader.EventBookmark is internal

### ISSUE THREAD

**Issue by wokis** [dotnet/runtime#49866] opened 2021-03-19 12:27 UTC
### Description

_System.Diagnostics.Eventing.Reader.EventBookmark_ is marked internal. This makes it impossible to get the bookmark XML or to create a _EventBookmark_ object from XML. The win32 API claims that it's exactly why bookmarks exists, to save for later use in a file or registry (https://docs.microsoft.com/en-us/windows/win32/wes/bookmarking-events).

I propose _System.Diagnostics.Eventing.Reader.EventBookmark_ is made public so that it can be used to persist the bookmark.

### Configuration

* .NET 5
* Windows 10
* x64

### Regression?
No

**Comment by tommcdon** [comment] 2021-03-21 15:29
@Anipik

**Comment by dhhoang** [comment] 2021-08-02 07:13
Hi,  
We have a need to persist the event bookmark (in XML string) and use it again later. This is a supported use case in Win32 app: https://docs.microsoft.com/en-us/windows/win32/wes/bookmarking-events.  
Right now we have to use reflection to read the XML from the `EventBookmark` class.   
The `EventBookmark` should have a constructor that accepts XML string and method to retrieve the XML string. (similar to `EvtCreateBookmark` https://docs.microsoft.com/en-us/windows/win32/api/winevt/nf-winevt-evtcreatebookmark).

**Comment by Anipik** [comment] 2021-08-02 17:14
@ericstj do we need to get through api-approval process for this ?

**Comment by eerhardt** [comment] 2021-08-09 14:41
> do we need to get through api-approval process for this ?

Yes. Moving to 7.0, since it is too late to get new API approved for 6.0.

Note: `EventBookmark` is a public class. It just has an internal constructor, and no public methods/properties. It is meant to be an opaque object that you get from an `EventRecord` and you can pass into an `EventLogReader`:

https://github.com/dotnet/runtime/blob/895c99cc502913fd7393b95af7cae5b9e6fbdea3/src/libraries/System.Diagnostics.EventLog/ref/System.Diagnostics.EventLog.cs#L182

https://github.com/dotnet/runtime/blob/895c99cc502913fd7393b95af7cae5b9e6fbdea3/src/libraries/System.Diagnostics.EventLog/ref/System.Diagnostics.EventLog.cs#L429-L433

https://github.com/dotnet/runtime/blob/895c99cc502913fd7393b95af7cae5b9e6fbdea3/src/libraries/System.Diagnostics.EventLog/ref/System.Diagnostics.EventLog.cs#L302-L315

@dhhoang @wokis - can you fully describe the scenario you are trying to achieve? I can make a few assumptions given your comments above, but I'd like to get the full scenario.

**Comment by dhhoang** [comment] 2021-08-09 15:05
@eerhardt we have an agent program that send Windows Events to a backend. The agent process is expected to start/stop regularly. We need to persist the Windows Event bookmark data so we know where to continue when the process starts up.

**Comment by dhhoang** [comment] 2022-03-21 21:33
Hi, I am just checking on this thread to see if there's any updates.   
Now that .NET 7 preview is out with NativeAOT, I guess we need to get rid of our reflection hack in order to use NativeAOT.  
Could we submit a PR to make this feature available?

**Comment by ViktorHofer** [comment] 2022-07-13 17:00
@dhhoang sorry for not responding earlier. If you would like to work on this, please update the initial post or add an comment below with the information required, according to https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md.

**Comment by ViktorHofer** [comment] 2022-07-13 17:02
cc @dotnet/area-system-diagnostics-eventlog

**Comment by dhhoang** [comment] 2022-07-14 17:30
@ViktorHofer  please see my proposal below
**[API Proposal]: `EventBookmark.Create()` and `EventBookmark.GetBookmarkXml()`**
## API proposal
```csharp
namespace System.Diagnostics.Eventing.Reader;

public class EventBookmark
{
    /// <summary>
    /// Gets the XML string that represents the bookmark.
    /// </summary>
    /// <returns>The bookmark's XML string.</returns>
    public string GetBookmarkXml();

    /// <summary>
    /// Creates a bookmark that identifies an event in a channel.
    /// </summary>
    /// <param name="bookmarkXml">An XML string that contains the bookmark.</param>
    /// <returns>The created <see cref="EventBookmark"/> instance.</returns>
    public static EventBookmark Create(string bookmarkXml);
}
```
## API usage
```csharp
// create a bookmark and event reader from existing XML
var bookmark = EventBookmark.Create(bookmarkXmlString);
using var eventReader = new EventLogReader(query, bookmark);

// query for event
var record = eventReader.ReadEvent();

// retrieve the bookmark XML (for storing elsewhere)
var recordBookmark = record.Bookmark.GetBookmarkXml();
```

## Alternative Designs
Another way to achieve the same functionality is to change the `EventBookmark` constructor and `BookmarkText` property from `internal` to public. However, that might break compatibility with existing code that uses reflection to access these members, so I opted to create new methods instead.

## Risk
* No breaking change.
* Shouldn't cause performance regression.

**Comment by dhhoang** [comment] 2022-07-19 17:53
@ViktorHofer  is this API proposal ok for review? Let me know if you think it needs more work and I could work on it.

**Comment by terrajobst** [comment] 2022-07-26 18:14
* Let's make this type a pure data holder
    - We can seal it because the existing constructor isn't public

```C#
namespace System.Diagnostics.Eventing.Reader;

public sealed class EventBookmark
{
    public EventBookmark(string bookmarkXml);
    public string BookmarkXml { get; }
}
```

**Comment by ViktorHofer** [comment] 2022-07-26 18:38
@dhhoang the API got just approved. Feel free to send a PR with the implementation according to the agreed on API surface (post above).

**Comment by danmoseley** [comment] 2022-08-12 19:35
@ViktorHofer is this intended for .NET 7? if so the PR isn't quite finished.

**Comment by ViktorHofer** [comment] 2022-08-12 19:38
It would be nice to get it into NET 7 but not a must. If what's left is making sure that the API is only exposed on .NETCoreApp, then I can help with that.

**Comment by dhhoang** [comment] 2022-08-12 19:46
We'd really appreciate it if this can get into NET 7. I can work on amending the PR asap.

**Comment by ericstj** [comment] 2022-08-15 22:54
Fixed in https://github.com/dotnet/runtime/pull/73548, thank you @dhhoang

**Closed by ericstj** 2022-08-15 22:54 UTC
Labels: api-approved, help wanted, area-System.Diagnostics.EventLog
