### ISSUE TITLE
AddEventLog settings silently disappear

### ISSUE THREAD

**Issue by qidydl** [dotnet/runtime#51899] opened 2021-04-26 23:46 UTC
### Description

If you call `EventLoggerFactoryExtensions.AddEventLog(this ILoggingBuilder builder, EventLogSettings settings)` on a service collection that already contains Event Log support (e.g. one created using `Host.CreateDefaultBuilder()`), the provided settings are silently ignored. This is because that method uses `TryAddEnumerable()`, which does nothing if the service is already present.

### Configuration

.NET 5.0 (latest as of report date)
Windows 10 x64
Specific to Windows (Event Log is Windows-only)

### Regression?

This worked in .NET Core 2.1 because the default builder did not add Event Log support by default, thus `TryAddEnumerable()` did in fact add the new logging provider with the specified settings. I'm not sure about the .NET Core 3.1 behavior; we are skipping past it.

### Other information

This could be treated as a documentation error; `EventLoggerFactoryExtensions.AddEventLog(this ILoggingBuilder builder, Action<EventLogSettings> configure)` does not have the issue because it always registers the provided callback. [The ASP.NET Core documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0#windows-eventlog) and/or the method comments could be updated to indicate this behavior clearly.

**Comment by maryamariyan** [comment] 2021-04-29 02:24
Do you have sample code to reproduce this issue also?

**Comment by qidydl** [comment] 2021-04-29 13:16
Replace `logging.AddEventLog(eventLogSettings => ...` in your sample with:

```csharp
logging.AddEventLog(new EventLogSettings
{
  SourceName = "MyLogs"
})
```

And that should reproduce the issue.

**Comment by maryamariyan** [comment] 2021-04-29 18:42
Thanks for the report. The logic in [EventLoggerFactoryExtensions.cs](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Logging.EventLog/src/EventLoggerFactoryExtensions.cs#L51) Looks a bit off from similar extension methods for console (in [ConsoleLoggerExtensions.cs](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Logging.Console/src/ConsoleLoggerExtensions.cs)).

What I would do here next is to compare similar logic in [EventLoggerFactoryExtensions.cs](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Logging.EventLog/src/EventLoggerFactoryExtensions.cs#L51) against console logger extension methods in (in [ConsoleLoggerExtensions.cs](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Logging.Console/src/ConsoleLoggerExtensions.cs)) to help solve the issue. Some helpful tests are available in [ConsoleLoggerExtensionsTests.cs](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Logging.Console/tests/Microsoft.Extensions.Logging.Console.Tests/ConsoleLoggerExtensionsTests.cs) worth adding to `EventLogLoggerTest`.

**Comment by EatsLemons** [comment] 2021-05-24 22:14
Looks like it should be ``` builder.AddProvider(new EventLogLoggerProvider(settings)); ``` instead of ``` builder.Services.TryAddEnumerable(...); ```

I have tried to make PR, but don't know how to create test project in proper way. If there are some guides or advices, I would like to make a PR

**Comment by maryamariyan** [comment] 2021-05-25 06:24
@EatsLemons let me know if [this docs page](https://github.com/dotnet/runtime/blob/main/docs/workflow/testing/libraries/testing.md#running-tests-on-the-command-line) helps

**Comment by wrzucher** [comment] 2021-08-18 04:33
I just created PR. but I think that use AddProvider instead of TryAddEnumerable is not the correct, because we add new ILoggerProvider with new settings. I am checking how it make in other ILoggerProvider and see, that should be only one ILoggerProvider of added type. For example nobody create several ConsoleLoggerProvider.

So, maybe we have to do something like this:
`
builder.AddEventLog();
builder.Services.Configure<EventLogSettings>(options =>
{
       options.LogName = settings.LogName;
// and rewrite other options
});
`
But rewriting old settings maybe not obious behaivor.

Other solutions is add new setting when old settings is empty and throw exeption when old settings is not empty.

**Comment by maryamariyan** [comment] 2022-01-17 22:23
Closing issue as won't fix. Please refer to comment in https://github.com/dotnet/runtime/pull/57567#issuecomment-1014923916

**Closed by maryamariyan** 2022-01-17 22:23 UTC
Labels: up-for-grabs, area-Extensions-Logging
