### ISSUE TITLE
Test failure Loader\\classloader\\generics\\Instantiation\\Negative\\Type_ofT_Inherit_FromT\\Type_ofT_Inherit_FromT.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#65349] opened 2022-02-15 01:24 UTC
Run: [runtime-coreclr r2r-extra 20220213.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1610717&view=ms.vss-test-web.build-test-results-tab&runId=44869332&paneView=debug&resultId=101895)

Failed test:
```
R2R windows x86 Checked jitstressregs8 @ Windows.10.Amd64.Open

- Loader\\classloader\\generics\\Instantiation\\Negative\\Type_ofT_Inherit_FromT\\Type_ofT_Inherit_FromT.cmd
- Loader\\classloader\\generics\\Instantiation\\Negative\\param02\\param02.cmd
- Loader\\classloader\\generics\\Instantiation\\Positive\\MultipleInterface13\\MultipleInterface13.cmd
- Loader\\classloader\\generics\\Variance\\IL\\InterfaceInheritanceTest2\\InterfaceInheritanceTest2.cmd
- Loader\\classloader\\generics\\Statics\\Regressions\\524571\\StaticsProblem1\\StaticsProblem1.cmd
- Loader\\classloader\\generics\\regressions\\vsw514968\\vsw514968\\vsw514968.cmd
- Loader\\classloader\\generics\\Layout\\General\\struct02_seq\\struct02_seq.cmd
- Loader\\classloader\\generics\\Instantiation\\Positive\\NestedStruct01\\NestedStruct01.cmd
- Loader\\classloader\\generics\\**

R2R windows x64 Checked forcerelocs @ Windows.10.Amd64.Open

- Loader\\binding\\assemblies\\assemblyversion\\EmbedStringVersions\\EmbedStringVersions.cmd
- Loader\\CollectibleAssemblies\\Statics\\CollectibleStatics\\CollectibleStatics.cmd
- Loader\\lowlevel\\regress\\105736\\Exception\\Exception.cmd
- Loader\\binding\\assemblies\\assemblybugs\\203962w\\client\\client.cmd
- Loader\\binding\\assemblies\\generics\\arilistienum\\methods\\methods\\methods.cmd
- Loader\\binding\\tracing\\BinderTracingTest.ResolutionFlow\\BinderTracingTest.ResolutionFlow.cmd
- Loader\\binding\\assemblies\\generics\\arilistienum\\methods\\exceptions\\exceptions.cmd
- Loader\\regressions\\polyrec\\Polyrec\\Polyrec.cmd
- Loader\\ContextualReflection\\ContextualReflection\\ContextualReflection.cmd
- Loader\\binding\\assemblies\\assemblybugs\\102140\\test\\test.cmd

```
**One of error message:**
```
Could Not Find C:\h\w\AAAE0916\w\A2F808A4\e\Loader\classloader\generics\Instantiation\Negative\Type_ofT_Inherit_FromT\IL-CG2\composite-r2r.dll
Could Not Find C:\h\w\AAAE0916\w\A2F808A4\e\Loader\classloader\generics\Instantiation\Negative\Type_ofT_Inherit_FromT\Type_ofT_Inherit_FromT.dll.rsp
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'System.Security.Cryptography.Primitives, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. An attempt was made to load a program with an incorrect format.
File name: 'System.Security.Cryptography.Primitives, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
at ILCompiler.CoreRTNameMangler.SanitizeNameWithHash(String literal)
at ILCompiler.CoreRTNameMangler.set_CompilationUnitPrefix(String value)
at ILCompiler.Program.RunSingleCompilation(Dictionary2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary2 unrootedInputFilePaths, HashSet`1 versionBubbleModulesHash, CompilerTypeSystemContext typeSystemContext)
at ILCompiler.Program.Run(String[] args)
at ILCompiler.Program.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\AAAE0916\w\A2F808A4\uploads\Reports\Loader.classloader\generics\Instantiation\Negative\Type_ofT_Inherit_FromT\Type_ofT_Inherit_FromT.output.txt
Raw output:
BEGIN EXECUTION
Type_ofT_Inherit_FromT.dll
1 file(s) copied.
Response file: C:\h\w\AAAE0916\w\A2F808A4\e\Loader\classloader\generics\Instantiation\Negative\Type_ofT_Inherit_FromT\Type_ofT_Inherit_FromT.dll.rsp
C:\h\w\AAAE0916\w\A2F808A4\e\Loader\classloader\generics\Instantiation\Negative\Type_ofT_Inherit_FromT\IL-CG2\Type_ofT_Inherit_FromT.dll
-o:C:\h\w\AAAE0916\w\A2F808A4\e\Loader\classloader\generics\Instantiation\Negative\Type_ofT_Inherit_FromT\Type_ofT_Inherit_FromT.dll
--targetarch:x86
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\AAAE0916\p\System..dll
-r:C:\h\w\AAAE0916\p\Microsoft..dll
-r:C:\h\w\AAAE0916\p\mscorlib.dll
-r:C:\h\w\AAAE0916\p\netstandard.dll
-O
" "dotnet" "C:\h\w\AAAE0916\p\crossgen2\crossgen2.dll" @"C:\h\w\AAAE0916\w\A2F808A4\e\Loader\classloader\generics\Instantiation\Negative\Type_ofT_Inherit_FromT\Type_ofT_Inherit_FromT.dll.rsp"   -r:C:\h\w\AAAE0916\w\A2F808A4\e\Loader\classloader\generics\Instantiation\Negative\Type_ofT_Inherit_FromT\IL-CG2*.dll"
Crossgen2 failed with exitcode - -532462766
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\AAAE0916\p
C:\h\w\AAAE0916\w\A2F808A4\e\Loader\classloader\generics\Instantiation\Negative\Type_ofT_Inherit_FromT\Type_ofT_Inherit_FromT.cmd
Expected: True
Actual:   False


Stack trace
   at Loader_classloader._generics_Instantiation_Negative_Type_ofT_Inherit_FromT_Type_ofT_Inherit_FromT_._generics_Instantiation_Negative_Type_ofT_Inherit_FromT_Type_ofT_Inherit_FromT_cmd()
```

**Comment by trylek** [comment] 2022-04-04 20:32
Closing as duplicate of: https://github.com/dotnet/runtime/issues/65646

**Closed by trylek** 2022-04-04 20:32 UTC
Labels: arch-x86, os-windows, JitStress, arch-x64, area-crossgen2-coreclr, untriaged
