### ISSUE TITLE
Be able to set HexConverter.Casing.Upper on Convert.ToHexString

### ISSUE THREAD

**Issue by Mrgaton** [dotnet/runtime#97397] opened 2024-01-23 15:49 UTC
### Background and motivation

I just want to use the native API

### API Usage

```csharp
      Convert.ToHexString(hashAlg.ComputeHash(data),HexConverter.Casing.Lowwer;
```

### Alternative Designs

idk

### Risks

Any

**Comment by vcsjones** [comment] 2024-01-23 16:45
This appears to be a duplicate of https://github.com/dotnet/runtime/issues/60393 which is implemented for .NET 9. It [will have `Convert.ToHexStringLower`](https://github.com/dotnet/runtime/pull/92483).

**Comment by tannergooding** [comment] 2024-01-23 17:09
Closing as duplicate

**Closed by tannergooding** 2024-01-23 17:09 UTC
Labels: api-suggestion, area-System.Runtime, untriaged
