### ISSUE TITLE
[mono] Windows CI failures in BackwardsCompatibility_DowngradeToHttp11

### ISSUE THREAD

**Issue by matouskozak** [dotnet/runtime#103811] opened 2024-06-21 12:01 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=713848
Build error leg or test failing: System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11
Affected CI: `windows-x64 Release AllSubsets_Mono` (`runtime-extra-platforms`)
Range of commits: https://github.com/dotnet/runtime/compare/6d838df6...9e57de2b

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11 [FAIL]",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=713848
**Error message validated:** `[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11 [FAIL]`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 6/21/2024 12:02:05 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[713848](https://dev.azure.com/dnceng-public/public/_build/results?buildId=713848)|dotnet/runtime|[System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.BackwardsCompatibility_DowngradeToHttp11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=713848&view=ms.vss-test-web.build-test-results-tab&runId=17856870&resultId=185734)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|1|

**Comment by rzikm** [comment] 2024-06-21 13:13
Duplicate of https://github.com/dotnet/runtime/issues/103754

**Closed by rzikm** 2024-06-21 13:13 UTC
Labels: area-System.Net.Http, os-windows, arch-x64, untriaged, Known Build Error
