### ISSUE TITLE
Remove duplicates From the TargetFrameworks while doing restore.

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#32205] opened 2020-02-13 00:14 UTC
When we build a libraries project in VS, it tries to due a restore. In our new config system, we remove the oSGroup from tfms just before restore. So for projects with ```<TargetFrameworks>netcoreapp5.0-Windows_NT;netcoreapp5.0-Unix<TargetFrameworks>```
ends with just
```
<TargetFrameworks>netcoreapp5.0;netcoreapp5.0</TargetFrameworks>
```
which is not a valid input for restore task. It wont effect the build in VS, but we should fix it becuase it would show as an error on the output pane in the vs and it would be required for enabling the restore on ref and srcs

The error looks like this 
```
Error occurred while restoring NuGet packages: Invalid restore input. Duplicate frameworks found: 'netcoreapp5.0, netcoreapp5.0'. Input files: C:\git\runtime\src\libraries\System.IO.FileSystem\tests\System.IO.FileSystem.Tests.csproj.
```

 cc @ViktorHofer @ericstj  @safern @danmosemsft

**Comment by ViktorHofer** [comment] 2020-02-13 17:08
@Anipik why is the Distinct operation not working which runs before Restore? https://github.com/dotnet/arcade/blob/f50767f96246063f33a6565d318f3adf9058bace/src/Microsoft.DotNet.Build.Tasks.TargetFramework.Sdk/src/build/Microsoft.DotNet.Build.Tasks.TargetFramework.Sdk.targets#L55

**Comment by Anipik** [comment] 2020-02-13 19:14
If I remember is correctly, it was because these .Distinct only removes identical items and these items would have different originalSpec metadata(with the OSGroup). but I can verify again as well.

**Comment by Anipik** [comment] 2020-02-13 22:41
you are right, its getting removed. I will debug the reason behind the failure

**Comment by ViktorHofer** [comment] 2020-02-13 22:42
So the distinct operation actually works but there is another failure during restore?

**Comment by Anipik** [comment] 2020-02-13 22:44
yes it seems that way. i checked the binlog and duplicates are getting removed.

**Comment by Anipik** [comment] 2020-02-13 22:46
It fails only in the VS, restore is successful from the command line.

**Comment by ericstj** [comment] 2020-02-24 19:12
Is this still happening?

**Comment by alexvy86** [comment] 2020-04-09 01:12
It is still happening, I just ran into it.

**Comment by ericstj** [comment] 2020-04-09 01:50
I believe Viktor made a fix for this but you need to make sure you have the latest VS preview and SDK.  I know @safern hit this too and was able to get past it with an update.

**Comment by safern** [comment] 2020-04-09 03:20
> I know @safern hit this too and was able to get past it with an update.

I tried to  update but actually didn't go passed it, I mentioned it to @Anipik in the morning.

**Comment by eerhardt** [comment] 2020-04-14 17:32
I just hit this as well in System.Utf8String.Experimental.sln.

Visual Studio Version 16.6.0 Preview 2.1

.NET SDK - 5.0.100-preview.4.20213.14

**Comment by shoter** [comment] 2020-06-12 00:25
I also had the same problem with System.IO.FileSystem

Visual Studio Version 16.5.4
.NET SDK - 5.0.100-preview.6.20311.12

**Comment by ViktorHofer** [comment] 2020-06-12 14:56
This happens inside VS because NuGet reads from `TargetFramework` and `TargetFrameworks` properties which they shouldn't: https://github.com/NuGet/Home/issues/5154.

See my response in that issue for a more detailed explanation.

cc @nkolev92 @zkat

**Comment by ericstj** [comment] 2020-09-22 17:24
This is still reproducing today and I tried to restore up front outside of VS and it doesn't workaround it.  @Anipik @ViktorHofer can you have a look and see why our previous workarounds are broken?

**Comment by ViktorHofer** [comment] 2020-09-26 08:25
@ericstj I shared workaround in https://github.com/dotnet/runtime/issues/20411#issuecomment-698381392.

**Comment by ViktorHofer** [comment] 2020-11-15 15:48
As an update, the issue has been largely mitigated but will remain for any projects that multi-targets on netcoreapp2.x, netcoreapp3.x, netstandard or netframework.

**Comment by eerhardt** [comment] 2020-11-20 22:40
> will remain for any projects that multi-targets on netcoreapp2.x, netcoreapp3.x, netstandard or netframework.

Does that mean all `Microsoft.Extensions` projects will still have this issue?

**Comment by Anipik** [comment] 2020-11-21 03:31
> Does that mean all Microsoft.Extensions projects will still have this issue?

only if they target netcoreapp2.x-Platform, only netcoreapp2.x should be fine.

**Comment by ericstj** [comment] 2020-11-23 17:12
Yeah, none of extensions should be impacted.  Runtime targeting isn't something that should be super prevalent.

**Closed** 2020-12-02 22:18 UTC
Labels: area-Infrastructure-libraries, tracking-external-issue
