### ISSUE TITLE
Custom JsonConverter is ignored on [FromQuery] action parameter in ASP.NET

### ISSUE THREAD

**Issue by madmox** [dotnet/runtime#63677] opened 2022-01-12 10:43 UTC
### Description

I have an enum type using a custom `JsonConverter` which uses `EnumMember` attributes to serialize/deserialize enum values. When I pass a parameter of this type directly in an MVC controller action using `FromQuery`, the custom converter is ignored.

### Reproduction Steps

```csharp
public class JsonStringEnumMemberConverter : JsonConverterFactory
{
    public override bool CanConvert(Type typeToConvert) => typeToConvert.IsEnum;

    public override JsonConverter CreateConverter(Type typeToConvert, JsonSerializerOptions options)
    {
        Type converterType = typeof(JsonStringEnumMemberConverterImpl<>).MakeGenericType(typeToConvert);
        var converter = (JsonConverter)Activator.CreateInstance(
            converterType, BindingFlags.Instance | BindingFlags.Public, binder: null, args: null, culture: null
        );
        return converter;
    }

    private class JsonStringEnumMemberConverterImpl<T> : JsonConverter<T> where T : Enum
    {
        public override T Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            try { return EnumHelper.Parse<T>(reader.GetString()); }
            catch (Exception ex) { throw new JsonException(ex.Message, ex); }
        }

        public override void Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
        {
            string strValue = value.ToEnumString();
            writer.WriteStringValue(strValue);
        }
    }
}
```
```csharp
[JsonConverter(typeof(JsonStringEnumMemberConverter))]
public enum LanguageCode
{
    [EnumMember(Value = "en-US")] EN_US,
    [EnumMember(Value = "fr-FR")] FR_FR
}
```
```csharp
[ApiController]
public class TestController : ControllerBase
{
    [HttpGet, Route("test")]
    public IActionResult Get([FromQuery(Name = "lang")] LanguageCode lang = LanguageCode.EN_US)
        => new OkObjectResult();
}
```

### Expected behavior

Calling the `/test?lang=fr-FR` endpoint should succeed and `/test?lang=FR_FR` should fail.

### Actual behavior

Calling the `/test?lang=fr-FR` endpoint fails with the following message:
> The value 'fr-FR' is not valid.

Whereas calling the endpoint `/test?lang=FR_FR` succeeds.

### Known Workarounds

Use a string as input parameter, and parse it manually to enum type from within the controller action.

### Configuration

* .NET version: 3.1.22 (not tested with .NET 5+)
* OS: Windows 11 x64

**Comment by krwq** [comment] 2022-01-14 11:29
@madmox I've tried your sample modified to just use System.Text.Json on net6.0 and both serialization and deserialization with default options work correct for me. I don't believe we are planning to fix this on older version. My recommendation would be to try to upgrade your app to latest (6.0) and see if that works as intended. If still not I'd redirect this to ASP.NET and show them the standalone sample works

Here is what I exactly tried:

```csharp
using System.Reflection;
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;

public class JsonStringEnumMemberConverter : JsonConverterFactory
{
    public override bool CanConvert(Type typeToConvert) => typeToConvert.IsEnum;

    public override JsonConverter CreateConverter(Type typeToConvert, JsonSerializerOptions options)
    {
        Type converterType = typeof(JsonStringEnumMemberConverterImpl<>).MakeGenericType(typeToConvert);
        var converter = (JsonConverter)Activator.CreateInstance(
            converterType, BindingFlags.Instance | BindingFlags.Public, binder: null, args: null, culture: null
        )!;
        return converter;
    }

    private class JsonStringEnumMemberConverterImpl<T> : JsonConverter<T> where T : Enum
    {
        public override T Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            try { return EnumHelper.Parse<T>(reader.GetString()); }
            catch (Exception ex) { throw new JsonException(ex.Message, ex); }
        }

        public override void Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
        {
            string strValue = value.ToEnumString();
            writer.WriteStringValue(strValue);
        }
    }
}

[JsonConverter(typeof(JsonStringEnumMemberConverter))]
public enum LanguageCode
{
    [EnumMember(Value = "en-US")] EN_US,
    [EnumMember(Value = "fr-FR")] FR_FR
}

public static class EnumHelper
{
    public static string ToEnumString<T>(this T value) where T : Enum
    {
        var enumType = typeof(T);
        var name = Enum.GetName(enumType, value);
        var enumMemberAttribute = ((EnumMemberAttribute[])enumType.GetField(name)!.GetCustomAttributes(typeof(EnumMemberAttribute), true)).Single();
        return enumMemberAttribute.Value ?? throw new Exception($"Member `{name}` in type `{enumType.FullName}` does not define `EnumMember.Value`");
    }

    public static T Parse<T>(string str)
    {
        var enumType = typeof(T);
        foreach (var name in Enum.GetNames(enumType))
        {
            var enumMemberAttribute = ((EnumMemberAttribute[])enumType.GetField(name).GetCustomAttributes(typeof(EnumMemberAttribute), true)).Single();
            if (enumMemberAttribute.Value == str) return (T)Enum.Parse(enumType, name);
        }
        throw new Exception ($"Cannot parse `{str}` for type `{enumType.FullName}`");
    }
}

public class MyClassWithLanguageCodes
{
    public LanguageCode MyLanguageCode { get; set; }
}

public class Program
{
    public static void Main()
    {
        MyClassWithLanguageCodes o = new MyClassWithLanguageCodes() { MyLanguageCode = LanguageCode.FR_FR };
        string jsonString = JsonSerializer.Serialize(o);
        Console.WriteLine(jsonString);

        var deserialized = JsonSerializer.Deserialize<MyClassWithLanguageCodes>(jsonString)!;
        Console.WriteLine(deserialized.MyLanguageCode);
    }
}
```

**Comment by krwq** [comment] 2022-01-14 11:32
I'll close this for now since we're likely not going to service this. Please re-open if you strongly feel we should service this bug and we will reconsider.

**Closed by krwq** 2022-01-14 11:32 UTC
Labels: area-System.Text.Json, untriaged

**Comment by madmox** [comment] 2022-01-14 12:12
There's no problem when deserializing the way you did, even in .NET 3.1. It really only happens with ASP.NET controller action parameters using `[FromQuery]` attribute. Here is a complete sample for reproduction in .NET 6, you just have to create a project with the template `ASP.NET Core Empty` and replace the generated `Program.cs` file with this:

```csharp
using Microsoft.AspNetCore.Mvc;
using System.Reflection;
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;

WebApplicationBuilder builder = WebApplication.CreateBuilder(args);
builder.Services.AddControllers();
WebApplication app = builder.Build();
app.UseRouting();
app.UseEndpoints(endpoints =>
{
    endpoints.MapControllers();
});
app.Run();

[ApiController]
public class TestController : ControllerBase
{
    [HttpGet, Route("test")]
    public IActionResult Get([FromQuery(Name = "lang")] LanguageCode lang = LanguageCode.EN_US)
    {
        return new OkObjectResult(lang);
    }
}

[JsonConverter(typeof(JsonStringEnumMemberConverter))]
public enum LanguageCode
{
    [EnumMember(Value = "en-US")] EN_US,
    [EnumMember(Value = "fr-FR")] FR_FR
}

public class JsonStringEnumMemberConverter : JsonConverterFactory
{
    public override bool CanConvert(Type typeToConvert) => typeToConvert.IsEnum;

    public override JsonConverter CreateConverter(Type typeToConvert, JsonSerializerOptions options)
    {
        Type converterType = typeof(JsonStringEnumMemberConverterImpl<>).MakeGenericType(typeToConvert);
        var converter = (JsonConverter)Activator.CreateInstance(
            converterType, BindingFlags.Instance | BindingFlags.Public, binder: null, args: null, culture: null
        );
        return converter;
    }

    private class JsonStringEnumMemberConverterImpl<T> : JsonConverter<T> where T : Enum
    {
        public override T Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            try { return EnumHelper.Parse<T>(reader.GetString()); }
            catch (Exception ex) { throw new JsonException(ex.Message, ex); }
        }

        public override void Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
        {
            string strValue = value.ToEnumString();
            writer.WriteStringValue(strValue);
        }
    }
}

public static class EnumHelper
{
    public static T Parse<T>(string input) where T : Enum
    {
        foreach (T value in Enum.GetValues(typeof(T)).Cast<T>())
        {
            string valueStr = value.ToEnumString();
            if (string.Equals(input, valueStr, StringComparison.Ordinal))
            {
                return value;
            }
        }

        throw new ArgumentOutOfRangeException($"Cannot parse value {input} as enum type {typeof(T).FullName}");
    }
}

public static class EnumExtensions
{
    public static string ToEnumString(this Enum value)
    {
        Type enumType = value.GetType();
        string name = Enum.GetName(enumType, value);
        if (name == null)
        {
            throw new ArgumentOutOfRangeException($"The value {value} does not exist in the enum {enumType.FullName}");
        }

        var enumMemberAttribute = (EnumMemberAttribute)enumType
            .GetField(name)
            .GetCustomAttributes(typeof(EnumMemberAttribute), inherit: true)
            .FirstOrDefault();
        return enumMemberAttribute?.Value ?? name;
    }
}
```

Maybe it would have been more appropriate to report this in the ASP.NET repo indeed, but I found a similar bug already reported [here](https://github.com/dotnet/runtime/issues/38939) (but closed due to lack of activity), so I thought it was the right place.
