### ISSUE TITLE
A published blazor wasm app throws a serialization error "Unhandled exception rendering component: ConstructorContainsNullParameterNames"

### ISSUE THREAD

**Issue by Stamo-Gochev** [dotnet/runtime#95409] opened 2023-11-15 13:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

An error is thrown when making a JS interop call in a **published** blazor wasm app that should serialize a `KeyValuePair` [value](https://github.com/Stamo-Gochev/blazor-issue-wasm-serialization/blob/master/BlazorissueWasmSerialization/BlazorissueWasmSerialization.Client/Pages/Home.razor#L29).

This seems to be related to trimming as running this with things like `dotnet run --configuration Release` works as expected, but publishing the app starts the trimmer by default.

In addition, using an [anonymous type instead](https://github.com/Stamo-Gochev/blazor-issue-wasm-serialization/blob/master/BlazorissueWasmSerialization/BlazorissueWasmSerialization.Client/Pages/Home.razor#L35-L48) of `KeyValuePair` works without any errors.

> [!NOTE]
> I tried to [disable the trimming](https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-7-0#enable-trimming), but the error is still present. Any suggestions on how to do that will be helpful - this might turn out to be another issue though.

![blazor-issue-wasm-serialization](https://github.com/dotnet/aspnetcore/assets/1857705/b96574f5-7e82-44bc-b408-9f39b0c5e810)

### Expected Behavior

No error is thrown.

### Steps To Reproduce

1. Clone https://github.com/Stamo-Gochev/blazor-issue-wasm-serialization
2. Change directory to https://github.com/Stamo-Gochev/blazor-issue-wasm-serialization/tree/master/BlazorissueWasmSerialization/BlazorissueWasmSerialization
3. Run `dotnet publish --configuration Release`
4. Go to `BlazorissueWasmSerialization/BlazorissueWasmSerialization/bin/Release/net8.0/publish`
5. Run `dotnet BlazorissueWasmSerialization.dll`
6. [Click the "Show issue button"](https://github.com/Stamo-Gochev/blazor-issue-wasm-serialization/blob/master/BlazorissueWasmSerialization/BlazorissueWasmSerialization.Client/Pages/Home.razor#L19-L33)

### Exceptions (if any)

<details>

<summary>Exception</summary>

```bash
blazor.web.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: ConstructorContainsNullParameterNames, System.Collections.Generic.KeyValuePair`2[System.String,System.String] SerializationNotSupportedParentType, System.Object Path: $.
System.NotSupportedException: ConstructorContainsNullParameterNames, System.Collections.Generic.KeyValuePair`2[System.String,System.String] SerializationNotSupportedParentType, System.Object Path: $.
 ---> System.NotSupportedException: ConstructorContainsNullParameterNames, System.Collections.Generic.KeyValuePair`2[System.String,System.String]
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_ConstructorContainsNullParameterNames(Type )
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.PopulateParameterInfoValues(JsonTypeInfo )
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.CreateTypeInfoCore(Type , JsonConverter , JsonSerializerOptions )
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.CreateJsonTypeInfo(Type , JsonSerializerOptions )
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.GetTypeInfo(Type , JsonSerializerOptions )
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoNoCaching(Type )
   at System.Text.Json.JsonSerializerOptions.CachingContext.CreateCacheEntry(Type type, CachingContext context)
--- End of stack trace from previous location ---
   at System.Text.Json.JsonSerializerOptions.CachingContext.CacheEntry.GetResult()
   at System.Text.Json.JsonSerializerOptions.CachingContext.GetOrAddTypeInfo(Type , Boolean )
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type , Boolean , Nullable`1 , Boolean , Boolean )
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureSynchronized|172_0()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.EnsureConfigured()
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type , Boolean , Nullable`1 , Boolean , Boolean )
   at System.Text.Json.WriteStackFrame.InitializePolymorphicReEntry(Type , JsonSerializerOptions )
   at System.Text.Json.Serialization.JsonConverter.ResolvePolymorphicConverter(Object , JsonTypeInfo , JsonSerializerOptions , WriteStack& )
   at System.Text.Json.Serialization.JsonConverter`1[[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryWrite(Utf8JsonWriter , Object& , JsonSerializerOptions , WriteStack& )
   at System.Text.Json.Serialization.Converters.DictionaryOfTKeyTValueConverter`3[[System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnWriteResume(Utf8JsonWriter , Dictionary`2 , JsonSerializerOptions , WriteStack& )
   at System.Text.Json.Serialization.JsonDictionaryConverter`3[[System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnTryWrite(Utf8JsonWriter , Dictionary`2 , JsonSerializerOptions , WriteStack& )
   at System.Text.Json.Serialization.JsonConverter`1[[System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryWrite(Utf8JsonWriter , Dictionary`2& , JsonSerializerOptions , WriteStack& )
   at System.Text.Json.Serialization.JsonConverter`1[[System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryWriteAsObject(Utf8JsonWriter , Object , JsonSerializerOptions , WriteStack& )
   at System.Text.Json.Serialization.JsonConverter`1[[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryWrite(Utf8JsonWriter , Object& , JsonSerializerOptions , WriteStack& )
   at System.Text.Json.Serialization.Converters.ArrayConverter`2[[System.Object[], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnWriteResume(Utf8JsonWriter , Object[] , JsonSerializerOptions , WriteStack& )
   at System.Text.Json.Serialization.JsonCollectionConverter`2[[System.Object[], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].OnTryWrite(Utf8JsonWriter , Object[] , JsonSerializerOptions , WriteStack& )
   at System.Text.Json.Serialization.JsonConverter`1[[System.Object[], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryWrite(Utf8JsonWriter , Object[]& , JsonSerializerOptions , WriteStack& )
   at System.Text.Json.Serialization.JsonConverter`1[[System.Object[], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].WriteCore(Utf8JsonWriter , Object[]& , JsonSerializerOptions , WriteStack& )
   Exception_EndOfInnerExceptionStack
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(WriteStack& , NotSupportedException )
   at System.Text.Json.Serialization.JsonConverter`1[[System.Object[], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].WriteCore(Utf8JsonWriter , Object[]& , JsonSerializerOptions , WriteStack& )
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1[[System.Object[], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Serialize(Utf8JsonWriter , Object[]& , Object )
   at System.Text.Json.JsonSerializer.WriteString[Object[]](Object[]& , JsonTypeInfo`1 )
   at System.Text.Json.JsonSerializer.Serialize[Object[]](Object[] , JsonSerializerOptions )
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[IJSVoidResult](Int64 , String , CancellationToken , Object[] )
   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[Microsoft.JSInterop.Infrastructure.IJSVoidResult, Microsoft.JSInterop, Version=8.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext()
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime , String , Object[] )
   at BlazorissueWasmSerialization.Client.Pages.Home.OnButtonShowIssueClick()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )

```

</details>

### .NET Version

8.0.100

**Comment by eiriktsarpalis** [comment] 2023-11-29 16:33
Duplicate of #74141, https://github.com/dotnet/runtime/issues/94806 and https://github.com/dotnet/runtime/issues/81709. 

The reason this error shows up on serialization traces as well as deserialization is because of [this breaking change](https://learn.microsoft.com/en-us/dotnet/core/compatibility/serialization/8.0/metadata-resolving). I would recommend either switching to the source generator or applying a `DynamicDependency` attribute on the affected types (see  https://github.com/passwordless-lib/fido2-net-lib/commit/1fbfb25cb9f53a8795ab952698dcc6493df1add3 for an example).

**Closed by eiriktsarpalis** 2023-11-29 16:33 UTC
Labels: bug, area-System.Text.Json, untriaged

**Comment by eiriktsarpalis** [comment] 2023-11-29 17:11
> > The reason this error shows up on serialization traces as well as deserialization is because of [this breaking change](https://learn.microsoft.com/en-us/dotnet/core/compatibility/serialization/8.0/metadata-resolving).
> 
> Does this mean that system.text.json doesn't support de/serializing `KeyValuePair`? Since this is what this issue is about.

No. It means that using reflection-based serialization in trimmed applications is not reliable and can result in multiple failures like the one reported here. This is a problem inherent to using dynamic member access via reflection in trimmed applications and there's not much that can be done about it other than adding manual annotations to work around the issues that pop up. Our recommendation is to switch to the source generator if you must use a trimmed app, see [this article](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/reflection-vs-source-generation?pivots=dotnet-8-0) for more details.

**Comment by hoangdovan** [comment] 2023-12-12 08:24
@eiriktsarpalis I have same problem after upgrade to .Net 8. As you explained, we need to handle this problem by changing our code, and .Net will not support anymore like previous .Net 7 version?

**Comment by hoangdovan** [comment] 2023-12-12 08:25
@SaifAqqad @Stamo-Gochev any work around for this matter? I have same problem! Thanks!

**Comment by eiriktsarpalis** [comment] 2023-12-12 09:14
@hoangdovan The fundamental issue is that trimming and reflection are fundamentally incompatible. There's nothing that we can do about this in the System.Text.Json layer other than recommend switching to the source generator which is trimming-safe.

**Comment by Stamo-Gochev** [comment] 2023-12-13 08:37
[hoangdovan](https://github.com/hoangdovan)
> @SaifAqqad @Stamo-Gochev any work around for this matter? I have same problem! Thanks!

It still requires changing your code though and whether you need to serialize a `KeyValuePair` in several places or if you can replace it with another type. 

One option is to create a custom serializer, another one is to map it to something like:
```csharp
someKeyValuePair.Select(x => new { key = x.Key, value = x.Value })...
```
which follows the structure of a JSON-serialized `KeyValuePair`.

**Comment by hoangdovan** [comment] 2023-12-13 10:20
@Stamo-Gochev Thank you. In my case, I create a custom class replace for .Net KeyPairValue to fix this error!

**Comment by mguinness** [comment] 2023-12-18 19:04
> I tried to [disable the trimming](https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-7-0#enable-trimming), but the error is still present. Any suggestions on how to do that will be helpful - this might turn out to be another issue though.

@eiriktsarpalis @krwq Others are experiencing this issue at [blazor wasm throwing deserialization exception when published](https://stackoverflow.com/questions/77544981/).

**Comment by mguinness** [comment] 2023-12-20 01:51
> This seems to be a regression in the linker in fact.

@javiercn Can this issue be reopened?  Multiple people are getting this exception when trimming is disabled.

```xml
<PropertyGroup>
    <PublishTrimmed>false</PublishTrimmed>
    <BlazorWebAssemblyEnableLinking>false</BlazorWebAssemblyEnableLinking>
</PropertyGroup>
```

**Comment by eiriktsarpalis** [comment] 2023-12-20 12:08
> Multiple people are getting this exception when trimming is disabled.

That is very surprising. A minimal reproduction (including the project configuration) would help here.

**Comment by mguinness** [comment] 2023-12-21 04:36
It's straightforward to repro.  Details below performed using SDK 8.0.100 on Windows 11:

```cmd
mkdir NullParameterNames
cd NullParameterNames
dotnet new blazor --interactivity WebAssembly
```

Replace contents of `Counter.razor` in client with the following:

```razor
@page "/counter"
@rendermode InteractiveWebAssembly
@using System.Text.Json

<PageTitle>Counter</PageTitle>

<h1>Counter</h1>

<dl>
    @foreach (var item in @items!)
    {
        <dt>@item.Key</dt>
        <dd>@item.Value</dd>
    }
</dl>

@code {
    private List<KeyValuePair<string, string>>? items;

    protected override void OnInitialized()
    {
        string data = "[ { \"key\" : \"key 1\", \"value\" : \"value 1\" }, { \"key\" : \"key 2\", \"value\" : \"value 2\" } ]";

        JsonSerializerOptions options = new() { PropertyNameCaseInsensitive = true };

        items = JsonSerializer.Deserialize<List<KeyValuePair<string, string>>>(data, options)!;

        foreach (KeyValuePair<string, string> item in items)
        {
            Console.WriteLine($"Key: {item.Key}, Value: {item.Value}");
        }
    }
}
```

If you run server and visit counter page it will work as expected:

```cmd
cd NullParameterNames
dotnet run --configuration Release
```

Afterwards publish the app and run the exe:

```cmd
dotnet publish --configuration Release -p:PublishTrimmed=false
cd bin\Release\net8.0\publish
NullParameterNames.exe
```

On visiting counter page you will get `System.NotSupportedException` as detailed by OP.

If you look at `wwwroot\_framework` folder it has 604 files (34.6 MB).  If I republish with trimming it will have 109 files (12.8 MB).

**Comment by eiriktsarpalis** [comment] 2023-12-21 15:28
> Afterwards publish the app and run the exe:

Why would disabling trimming on the server app have any bearing on what happens to the client project? 

I also notice that the reproduction is using reflection-based serialization APIs directly which to my knowledge isn't well supported in wasm. I'm actually surprised that this doesn't give out any warnings. Have you tried using the source generator instead? This would involve including a declaration as follows:
```C#
[JsonSerializable(typeof(List<KeyValuePair<string, string>>)]
partial class MyContext : JsonSerializerContext {}
```
and passing that into the serializer APIs.

From the STJ perspective this is by-design behavior per https://github.com/dotnet/runtime/issues/95409#issuecomment-1832286887. The constructor parameters for KeyValuePair have been trimmed away so we can't build a serialization contract for the type. There's nothing the serializer can really do about that.

I can try re-transfering the issue back to Blazor in case they can provide recommendations that are more specific than what we can provide.
