### ISSUE TITLE
.NET 8 Runtime Bad Signature / Certificate for MacOS arm64

### ISSUE THREAD

**Issue by nagilson** [dotnet/runtime#100413] opened 2024-03-28 16:43 UTC
Over on the DevKit side, we have a number of users on MacOS reporting this error:
https://github.com/microsoft/vscode-dotnettools/issues/1002

This appears to be an issue with the runtime signatures for the local .zip runtimes shipped out and installed via the install scripts. Surprisingly, it is not just a problem with the 8.0.1 arm64 runtime but also the 8.0.3 arm64 runtime, at minimum. I imagine the same can be said for the 8.0.2 one as users would have temporarily been relieved of this issue via an automatic update.

```
.NET server STDERR: Failed to load /opt/homebrew/Cellar/dotnet/8.0.1/libexec/host/fxr/8.0.1/libhostfxr.dylib, error: dlopen(/opt/homebrew/Cellar/dotnet/8.0.1/libexec/host/fxr/8.0.1/libhostfxr.dylib, 0x0001): tried: '/opt/homebrew/Cellar/dotnet/8.0.1/libexec/host/fxr/8.0.1/libhostfxr.dylib' (code signature in <D9F7F506-1864-386E-9591-E9805FDE7F6C> '/opt/homebrew/Cellar/dotnet/8.0.1/libexec/host/fxr/8.0.1/libhostfxr.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/dotnet/8.0.1/libexec/host/fxr/8.0.1/libhostfxr.dylib' (no such file), '/opt/homebrew/Cellar/dotnet/8.0.1/libexec/host/fxr/8.0.1/libhostfxr.dylib' (code signature in <D9F7F506-1864-386E-9591-E9805FDE7F6C> '/opt/homebrew/Cellar/dotnet/8.0.1/libexec/host/fxr/8.0.1/libhostfxr.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs)
```

cc @jeffschwMSFT

**Comment by jeffschwMSFT** [comment] 2024-03-28 16:46
@mmitche / @agocke thoughts on who is the best to look at a potential signing issue on .NET Core native component?

**Comment by agocke** [comment] 2024-03-28 17:04
> local .zip runtimes shipped out and installed via the install scripts.

FYI, that error is from someone installing via homebrew, not directly via the install scripts. So there may be some homebrew stuff going on in between

**Comment by nagilson** [comment] 2024-03-28 17:07
One install is via homebrew, the other is via the install script. Presumably they hit the error on both given their messages, but they never actually 100% confirmed that.

**Comment by vcsjones** [comment] 2024-03-28 17:22
I can hit this installing nightlies, too, since those are not signed.

**Comment by joeloff** [comment] 2024-03-28 23:50
Runtime either signs during the build, like in 7+ or post build during staging. If signatures are missing or incorrect then it's likely an infra issue, or someone didn't add a file to a list to be signed. Either way, I'd start with engineering. We're supposed to be validating the signatures.

Has anyone diff'd the file in the tar.gz and .pkg to see if it's the same file?

**Comment by nagilson** [comment] 2024-04-01 20:27
@agocke, @joeloff is responsible for a lot of SDK and workload signatures but we dont know much about the runtime signing and validation process. Do you know who would manage the infra @joeloff suggested above so they can take a look?

**Comment by agocke** [comment] 2024-04-03 04:57
I just downloaded the 8.0.3 tar.gz and the files all seem to pass the signing scan with correct signatures.

**Comment by vcsjones** [comment] 2024-04-03 16:18
The binaries from Homebrew are ad-hoc signed, not signed by Microsoft. You can reproduce this issue by

1. Completely uninstall all of .NET.
2. Install .NET with Homebrew on Apple Silicon (`brew install dotnet`)
3. Start VS Code and activate DevKit

```
codesign -dv /opt/homebrew/Cellar/dotnet/8.0.3/libexec/host/fxr/8.0.3/libhostfxr.dylib
Executable=/opt/homebrew/Cellar/dotnet/8.0.3/libexec/host/fxr/8.0.3/libhostfxr.dylib
Identifier=libhostfxr-55554944e079e2218f4232fcbc25de741b71ed09
Format=Mach-O thin (arm64)
CodeDirectory v=20400 size=3020 flags=0x2(adhoc) hashes=88+2 location=embedded
Signature=adhoc
Info.plist=not bound
TeamIdentifier=not set
Sealed Resources=none
Internal requirements count=0 size=12
```

The DevKit process is signed with Team ID: UBF8T346G9

```
Library Validation failed: Rejecting '/opt/homebrew/Cellar/dotnet/8.0.3/libexec/host/fxr/8.0.3/libhostfxr.dylib' (Team ID: none, platform: no) for process 'Microsoft.Visual(59918)' (Team ID: UBF8T346G9, platform: no), reason: mapping process and mapped file (non-platform) have different Team IDs
```

A process that is signed with one Apple Code Signing Identity cannot load libraries that are signed by a different team, or in this case, no team (ad-hoc).

**Comment by vcsjones** [comment] 2024-04-03 16:22
Note that nightlies from `dotnet/installer` are also not signed, which is why I have this problem with nightly builds.

**Comment by vcsjones** [comment] 2024-04-03 16:26
I think the only solution here would be for Dev Kit to not consider installations of the Framework / Runtime / SDK that are unsigned.

**Comment by agocke** [comment] 2024-04-04 20:52
Closing as a dev kit issue

**Closed by agocke** 2024-04-04 20:52 UTC
Labels: area-Host, untriaged
