### ISSUE TITLE
Fix System.Text.Json source code annotation RequiresUnreferencedCodeAttribute by moving it to class level

### ISSUE THREAD

**Issue by LakshanF** [dotnet/runtime#67536] opened 2022-04-04 14:51 UTC
### Description

As mentioned in [this](https://github.com/dotnet/linker/issues/1742#issuecomment-875036480) comment, there is a desire to revisit some source in the [annotation ](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/FSharp/FSharpTypeConverterFactory.cs#L13-L14)in System.Text.Json namespace to hoist it to class level once issue is fixed. Its done [now](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Diagnostics/CodeAnalysis/RequiresUnreferencedCodeAttribute.cs#L16).

### Reproduction Steps

No observable behavioral change with the issue but only impacts code hygiene 

### Expected behavior

RequiresUnreferencedCodeAttribute to be moved up to the class header

### Actual behavior

RequiresUnreferencedCodeAttribute is at many members in the class

### Regression?

No

**Comment by eiriktsarpalis** [comment] 2022-09-02 14:42
I previously attempted making that change, but it turned out that adding RUC annotations on the type level introduced other complications, for example it was triggering linker warnings when consuming const or static members on that class even though it shouldn't.

Keeping the annotations on the constructors should be fine until annotation issues have been ironed out, so I don't think we need to track this via an open issue. I'm going to close this.

**Closed by eiriktsarpalis** 2022-09-02 14:42 UTC
Labels: enhancement, area-System.Text.Json, linkable-framework

**Comment by vitek-karas** [comment] 2022-09-02 18:13
> for example it was triggering linker warnings when consuming const or static members on that class even though it shouldn't.

This is by design - putting the RUC on class means that everything about the class is dangerous. It is functionally equivalent to
* putting RUC on all .ctors
* putting RUC on all static methods and fields

If the class is only dangerous when instantiated, then you should put RUC on .ctors alone.
