### ISSUE TITLE
Escape analysis inconsistency

### ISSUE THREAD

**Issue by hypeartist** [dotnet/runtime#65463] opened 2022-02-16 22:10 UTC
.NET 6.0.200

![image](https://user-images.githubusercontent.com/3519388/154365765-00c18858-c829-4ff8-a161-c549435ce753.png)

**Comment by teo-tsirpanis** [comment] 2022-02-16 22:27
Hello @hypeartist, this is a known limitation of the language done for safety reasons. The problem is that you pass the string by reference. If you remove the `in` from the first two methods it should compile. Strings themselves are reference types and there is no benefit in passing them with an `in`.

Regardless of the compile error, there is a GC hole around your use of pointers that might lead to abrupt crashes at runtime. My suggestion is to remove `GetPointerToFirstChar` and `GetCharAt1` and replace `GetCharReference` with the following:

``` csharp
static ref char GetCharReference(string s, nint index) =>
    ref Unsafe.Add(ref Unsafe.AsRef(in s.GetPinnableReference()), index);
```

**Comment by teo-tsirpanis** [comment] 2022-02-17 00:35
I am going to close this issue since it is related to the C# language and not the .NET platform. I hope I solved your problem, let me know if it persists.

**Closed by teo-tsirpanis** 2022-02-17 00:35 UTC
Labels: untriaged
