### ISSUE TITLE
MemoryMappedFile slow program termination

### ISSUE THREAD

**Issue by carlo-cs** [dotnet/runtime#69365] opened 2022-05-15 06:03 UTC
I'm using memory mapped files for read-only access to (potentially very large) text files. But regardless of file size I noticed, that program termination is very slow. The delay happens after the last closing curly brace of Main function. I tried measuring it with Performance Analysis, but without success. The resulting graph shows a flat line for about 2.5 seconds after the last measured statement. I'm using Visual Studio 2022 and framework 6, latest update. All related elements are properly disposed before the end (MemoryMappedFile, MemoryMappedViewStream, SafeMemoryMappedViewHandle). There is no delay while disposing these, but, as said before, at the end of the program.

The initialization and cleanup code looks like this:

	//
	//
	public void Dispose() {
		if ( null != _handle ) {
			_handle.Dispose();
		}
		if ( null != _stream ) {
			_stream.Dispose();
		}
		if ( null != _mmf ) {
			_mmf.Dispose();
		}
		_mmf = null;
		_stream = null;
		_handle = null;
		_length = 0;
		_begin = null;
		_current = null;
		_b16 = false;
		_wrap = 0;
	}
	//
	//
	//
	public bool Initialize( string filename, bool b16, int wrap ) {
		Dispose();
		// Get MMF and keep it open.
		_mmf = MemoryMappedFile.CreateFromFile( filename,
			FileMode.Open, "LogVw", 0, MemoryMappedFileAccess.Read );
		if ( null != _mmf ) {
			// Try to get the accessor stream
			_stream = _mmf.CreateViewStream( 0, 0, MemoryMappedFileAccess.Read );
			if ( null != _stream ) {
				_length = _stream.Length;
				// Get the view handle
				_handle = _stream.SafeMemoryMappedViewHandle;
				if ( null != _handle ) {
					// Get the pointer
					_handle.AcquirePointer( ref _begin );
					if ( null != _begin ) {
						_current = _begin;
						// Initialization complete
						_b16 = b16;
						_wrap = wrap;
						return true;
					}
				}
			}
		}
		Dispose();
		return false;
	}

**Comment by adamsitnik** [comment] 2022-05-16 12:42
Hi @carlo-cs 

I suspect that you might be hitting #62768, which I've fixed in #63794.

Could you please use latest .NET 7 Preview and see if the problem is gone? You should also get some benefits from #63754 and  #63790.

**Closed** 2022-06-13 18:02 UTC
Labels: area-System.IO, no-recent-activity, needs-author-action
