### ISSUE TITLE
System.Text.Json: Class JsonSerializable source generation

### ISSUE THREAD

**Issue by styris-ame** [dotnet/runtime#96762] opened 2024-01-10 07:20 UTC
Currently Json source generation works as follows:
```C#
[JsonSerializable(typeof(ExampleClass))]
internal partial class SourceGenerationContext : JsonSerializerContext { }

public class ExampleClass
{
    public string Text { get; set; }
}
```

This requires a `JsonSerializable(Type)` attribute to be added when you create a new serializable class. However I don't believe this is ideal since you have to navigate to your context definition each time you want to add a new serializable class.

A solution I propose is allowing the use of an empty `JsonSerializable` attribute on the serializable class itself:
```C#
// Automatically adds classes with the JsonSerializable attribute upon build
internal partial class SourceGenerationContext : JsonSerializerContext { }

[JsonSerializable]
public class ExampleClass
{
    public string Text { get; set; }
}
```

YamlDotNet allows for this functionality:
```C#
[YamlStaticContext]
public partial class StaticContext : YamlDotNet.Serialization.StaticContext { }

[YamlSerializable]
public class ExampleClass
{
    public string Text { get; set; }
}
```

See [this comment](https://github.com/aaubry/YamlDotNet/issues/740#issuecomment-1379101017) for further details, and [YamlDotNet.Core7AoTCompileTest](https://github.com/aaubry/YamlDotNet/tree/master/YamlDotNet.Core7AoTCompileTest) for a full example.

**Comment by eiriktsarpalis** [comment] 2024-01-10 13:42
Couple of remarks:

1. How would the source generator understand what context type to append the type to? What if there are two contexts defined in the assembly?
2. You still need to navigate to the context class to obtain the `JsonTypeInfo` to be able to serialize the type. We've been discussing two possible approaches that would render `JsonSerializerContext` obsolete, namely https://github.com/dotnet/runtime/issues/90787#issuecomment-1852070124 and https://github.com/dotnet/runtime/issues/91495.

Closing as duplicate of https://github.com/dotnet/runtime/issues/90787#issuecomment-1852070124

**Closed by eiriktsarpalis** 2024-01-10 13:42 UTC
Labels: area-System.Text.Json, untriaged
