### ISSUE TITLE
Building runtime on ARM64 uses x86 tools?

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#96141] opened 2023-12-18 17:33 UTC
When I build the runtime on an ARM64 Windows machine using `.\build.cmd -rc release -s clr` (and cleaning artifacts first), I noticed it using native compilation tools from `C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\Hostx86\arm64`.

According to the task manager, the compiler and linker tooling in this directory is x86, so it's using emulation.

I would expect the build to use tools in the directory `C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\Hostarm64\arm64`

Which contains native ARM64 build tools.

When I forced the build to use the native ARM64 tooling, there is a non-trivial performance improvement in compilation speed. The ARM64 tooling takes 8m52s whereas the x86 tooling takes 13m21s.

**Comment by jkotas** [comment] 2023-12-18 20:19
Related #76516

**Comment by jkotas** [comment] 2024-07-11 17:48
Duplicate of #104674 where we are making progress towards fixing it.

**Closed by jkotas** 2024-07-11 17:48 UTC
Labels: area-Infrastructure
