### ISSUE TITLE
[API Proposal]: Add collection builders for frozen collection types

### ISSUE THREAD

**Issue by thinker227** [dotnet/runtime#92190] opened 2023-09-17 12:35 UTC
### Background and motivation

Most collection types in the standard library as of now have associated collection builders for collection expressions in the current .NET 8 previews/prereleases. However, `FrozenSet<T>` and `FrozenDictionary<TKey, TValue>` do not. This is particularly inconvenient if one wishes to use these types as static "constants", eg. 
```cs
public static FrozenSet<TokenKind> CanBeginDeclaration { get; } = new[]
{
    TokenKind.FunctionKeyword,
    TokenKind.TypeKeyword,
}.ToFrozenSet();
```
Currently the above (or similar) is the only API to create a frozen set/dictionary for this kind of purpose, however it would be nice to be able to use collection expressions to initialize frozen sets/dictionaries.

### API Proposal

```diff
namespace System.Collections.Frozen;

+ [System.Runtime.CompilerServices.CollectionBuilder(typeof(FrozenSet)), nameof(FrozenSet.Create)]
public abstract class FrozenSet<T> : ISet<T>, IReadOnlySet<T>, IReadOnlyCollection<T>, ICollection
{
    // ...
}

public static class FrozenSet
{
+    public static FrozenSet<T> Create<T>(params ReadOnlySpan<T> source);
+    public static FrozenSet<T> Create<T>(IEqualityComparer<T>? equalityComparer, params ReadOnlySpan<T> source);
    // ...
}
```

### API Usage

```cs
public static FrozenSet<TokenKind> CanBeginDeclaration { get; } =
[
    TokenKind.FunctionKeyword,
    TokenKind.TypeKeyword,
];
```

### Alternative Designs

If collection expressions had natural types then calling `.ToFrozenSet()` directly on an untyped collection expression could potentially work, however this is currently not feasible.

### Risks

I'm unfortunately not knowledgeable enough about the runtime and core libraries to know what the risks of this API could be, if any. If anyone brings up concerns, I'll add them here.

**Comment by eiriktsarpalis** [comment] 2023-09-17 15:40
I don't recall `FrozenSet` support specifically being discussed, but I would guess the presence of the `optimizeForReads` parameter in earlier versions of the frozen collection factory methods probably made collection literal support unsuitable for `FrozenSet`. That's been since removed, perhaps though there's another reason? cc @stephentoub

**Comment by stephentoub** [comment] 2023-09-18 02:57
> perhaps though there's another reason?

The problem is ambiguity.

We wouldn't add a "Create" method; we'd add a "ToFrozenSet" overload to go with the one already there. This is a natural thing to want anyway, to be able to turn a span into a frozen set. But if we just add:
```C#
public static FrozenSet<T> ToFrozenSet<T>(this ReadOnlySpan<T> source);
```
it begs the question "what if I need to control the comparer", at which point you need:
```C#
public static FrozenSet<T> ToFrozenSet<T>(this ReadOnlySpan<T> source, IEqualityComparer<T> comparer = null);
```
and that results in ambiguity errors if you try to do:
```C#
int[] arr = ...;
FrozenSet.ToFrozenSet(arr, EqualityComparer<T>.Default);
```
as the compiler doesn't know whether to prefer the implicit conversion from `int[]` to `ReadOnlySpan<int>` or `IEnumerable<int>`.

It's the same reason we didn't add a `new HashSet<int>(ReadOnlySpan<int>)` constructor.

We can address all of these once the language is able to disambiguate them, hopefully in C# 13.

**Comment by eiriktsarpalis** [comment] 2023-09-18 08:50
I see, so we'd rather have the compiler address that ambiguity in the future than author a bespoke method group or class just to support collection literals?

**Comment by stephentoub** [comment] 2023-09-18 10:22
Yes

**Comment by eiriktsarpalis** [comment] 2023-09-18 13:33
If I'm honest having a "ToCollection" extension method defined over span types seems a little odd to me. It doesn't sound like a particularly common API you'd want to call when using spans, so having it show up in intellisense would be somewhat of a visual distraction. So perhaps it would have to be a different method group (i.e. `Create`) anyways?

**Comment by stephentoub** [comment] 2023-09-18 13:45
It doesn't need to be an extension method; it can just be a `ToFrozenSet` non-extension. Having two distinctly named methods that do the exact same thing (add all of the items from the input into a new FrozenSet) is confusing.

**Comment by eiriktsarpalis** [comment] 2023-09-18 13:51
I guess I'm conditioned to think of `To` methods as only making sense when invoked as instance or extension methods, whereas static methods should start with `Create` or `From`.

**Comment by TonyValenti** [comment] 2024-01-31 14:56
I'm posting here as I'm interested in FrozenSet supporting collection literals.

**Comment by stephentoub** [comment] 2024-03-20 22:03
> I guess I'm conditioned to think of `To` methods as only making sense when invoked as instance or extension methods, whereas static methods/factories should start with `Create` or `From`.

Yeah, it took me a little while, but I've come around to this. Especially with `params ReadOnlySpan<T>`.

I've updated the top post with `params` and an additional overload taking a comparer (following the same ordering as is used by the immutable collections) and marked it as ready for review.

**Comment by bartonjs** [comment] 2024-05-14 18:50
Looks good as proposed

```diff
namespace System.Collections.Frozen;

+ [System.Runtime.CompilerServices.CollectionBuilder(typeof(FrozenSet)), nameof(FrozenSet.Create)]
public abstract class FrozenSet<T> : ISet<T>, IReadOnlySet<T>, IReadOnlyCollection<T>, ICollection
{
    // ...
}

public static class FrozenSet
{
+    public static FrozenSet<T> Create<T>(params ReadOnlySpan<T> source);
+    public static FrozenSet<T> Create<T>(IEqualityComparer<T>? equalityComparer, params ReadOnlySpan<T> source);
    // ...
}
```

**Closed** 2024-05-20 23:59 UTC
Labels: api-approved, area-System.Collections, in-pr
