### ISSUE TITLE
PipeReader.CopyToAsync hangs

### ISSUE THREAD

**Issue by TheLever** [dotnet/runtime#52044] opened 2021-04-29 10:15 UTC
This issue seems very similar to [this](https://github.com/dotnet/runtime/issues/29606), but I am not sure the underlying issue is the same.

### Description

Had the need to read the contents of a HTTP request into a pipe, and used CopyToAsync. It seems to hang, however, stalling in the reading of the buffer. Repro code below.

This reproduces with .net core 3.1 and 5.0, System.IO.Pipelines 5.0.1.

            // srcPipe is used to mimic HttpRequest.BodyReader
            var srcPipe = new Pipe();

            // Issue may be reproducible with other sizes, this is the
            // content length we saw it with first
            var input = ArrayPool<byte>.Shared.Rent(126690);
            await srcPipe.Writer.WriteAsync(input);
            await srcPipe.Writer.CompleteAsync();

            var mainPipe = new Pipe();
            // This line below will hang
            await srcPipe.Reader.CopyToAsync(mainPipe.Writer);

I have debugged my way down, and I think the issue comes from here in CopyToAsyncCore:

            // The TryGet is what hangs
            while (buffer.TryGet(ref position, out ReadOnlyMemory<byte> memory))
            {
               FlushResult flushResult = await writeAsync(destination, memory, cancellationToken).ConfigureAwait(false);

               if (flushResult.IsCanceled)
               {
                 ThrowHelper.ThrowOperationCanceledException_FlushCanceled();
               }

### Configuration

This has been reproduced on:

- .net core 3.1 on Linux/Windows, .net core 5.0 on Windows, all x64

### Regression?

Not sure.

### Other information

Not aware of any workarounds - still looking for such one.

**Comment by davidfowl** [comment] 2021-04-29 10:23
This needs more details to be actionable Do you have a repro?

**Comment by TheLever** [comment] 2021-04-29 10:24
Yes, see the repro in the code above.

**Comment by davidfowl** [comment] 2021-04-29 15:08
That code will hang here:

```
await srcPipe.Writer.WriteAsync(input);
```

Because of the PauseWriterThreshold, which by default is 32K. That's by design, and you can read about it here https://docs.microsoft.com/en-us/dotnet/standard/io/pipelines#backpressure-and-flow-control.

**Comment by TheLever** [comment] 2021-04-29 18:37
No, it does not hang there (at least on my machine), and as mentioned in the code, this is just a small repro which illustrates the issue. You are welcome set up a repro with a HTTP request and see that it happens there also. I needed a way to get data into the pipe in order for me to read from it later on. As mentioned in the snippet, srcPipe is used to mimic HttpRequest.BodyReader.

The code hangs in CopyToAsyncCore.

**Comment by davidfowl** [comment] 2021-04-29 18:48
The HttpRequest.BodyReader isn't a Pipe so you might be running into something else? If you could provide a reproduction of that problem it would help.

As for the code above, it definitely doesn't hang on `CopyToAsync`, it hangs on `WriteAsync`

**Comment by TheLever** [comment] 2021-05-03 09:02
You are absolutely right! I don't know why I thought it wasn't hanging on WriteAsync - I am guessing it was my frantic search for a simple repro. I do humbly apologize for the inconvinience. I have now created a more realistic one. Steps are below:

1) Create a default .net core Web API - it should create the proverbial weatherforecast service
2) Add a POST method like this one:
```
        [HttpPost]
        public async Task Execute()
        {
            var pipe = new Pipe();
            // Write the request into the pipe. This next line will stall
            await this.Request.BodyReader.CopyToAsync(pipe.Writer);
            await pipe.Writer.CompleteAsync();
        }
```
3) Hit the endpoint with a large json using, for instance, postman. I used the [this](https://www.json-generator.com/#) to generate about 150 Kb input.

I can attach the repro project if needed - it should be simple enough to create.

**Comment by davidfowl** [comment] 2021-05-03 09:16
It's likely the same problem. CopyToAsync is copying data from the coming request stream and writing it into the pipe writer. Your Pipe.Writer ([as mentioned above](https://github.com/dotnet/runtime/issues/52044#issuecomment-829318253)) has a  default PauseWriterThreshold that stops you from blowing up memory. Nothing is consuming Pipe.Reader so the CopyToAsync operation will halt until the threshold is released:

```C#
[HttpPost]
public async Task Execute()
{
    var pipe = new Pipe();
    var task  = pipe.Reader.CopyToAsync(this.Response.Writer); // Copy the pipe.Reader to the response
    await this.Request.BodyReader.CopyToAsync(pipe.Writer); // Copy the request to the pipe.Writer
    await task;
    await pipe.Reader.CompleteAsync();
    await pipe.Writer.CompleteAsync();
}
```

The pipe is like an in memory network stream. It wants somebody to read as you are writing to it, it's not a memory stream meant to buffer the entire contents at once.

**Comment by BrennanConroy** [comment] 2021-05-05 20:23
Closing as answered.

**Closed by BrennanConroy** 2021-05-05 20:23 UTC
Labels: area-System.IO.Pipelines, untriaged
