### ISSUE TITLE
Self Contained Publish does not work in .NET 5 Preview 8

### ISSUE THREAD

**Issue by ThadHouse** [dotnet/runtime#41917] opened 2020-09-05 17:50 UTC
Attempting to run `dotnet publish -c Release -r win-x64` fails with the following errors. `dotnet publish` by itself works just fine.

```
Microsoft (R) Build Engine version 16.8.0-preview-20414-02+a55ce4fbb for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app.runtime.win-x64/index.json'.
  The SSL connection could not be established, see inner exception.
     Received an unexpected EOF or 0 bytes from the transport stream.
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.windowsdesktop.app.runtime.win-x64/index.json'.
  The SSL connection could not be established, see inner exception.
     Received an unexpected EOF or 0 bytes from the transport stream.
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.app.runtime.win-x64/index.json'.
  The SSL connection could not be established, see inner exception.
     Received an unexpected EOF or 0 bytes from the transport stream.
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.windowsdesktop.app.runtime.win-x64/index.json'.
  The SSL connection could not be established, see inner exception.
     Received an unexpected EOF or 0 bytes from the transport stream.
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.app.runtime.win-x64/index.json'.
  The SSL connection could not be established, see inner exception.
     Received an unexpected EOF or 0 bytes from the transport stream.
  Retrying 'FindPackagesByIdAsync' for source 'https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app.runtime.win-x64/index.json'.
  The SSL connection could not be established, see inner exception.
     Received an unexpected EOF or 0 bytes from the transport stream.
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\NuGet.targets(128,5): error : Failed to retrieve information about 'Microsoft.NETCore.App.Runtime.win-x64' from remote source 'https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app.runtime.win-x64/index.json'. [C:\Users\thadh\Documents\GitHub\thadhouse\WPILibInstaller-Avalonia\WPILibInstaller-Avalonia.sln]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\NuGet.targets(128,5): error :   The SSL connection could not be established, see inner exception. [C:\Users\thadh\Documents\GitHub\thadhouse\WPILibInstaller-Avalonia\WPILibInstaller-Avalonia.sln]
C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\NuGet.targets(128,5): error :    Received an unexpected EOF or 0 bytes from the transport stream. [C:\Users\thadh\Documents\GitHub\thadhouse\WPILibInstaller-Avalonia\WPILibInstaller-Avalonia.sln]
```

This happens with any project, even a fresh created console app.

Currently have only tested on Windows 10.

This worked before in previous versions.

.NET SDK version 5.0.100-preview.8.20417.9

**Comment by eriawan** [comment] 2020-09-05 20:32
This issue is better fit in dotnet/sdk instead of dotnet/runtime. 
Could someone from dotnet runtime team transfer this issue to dotnet/sdk?

cc @terrajobst @livarcocc

**Comment by jkotas** [comment] 2020-09-05 21:13
This is duplicate of https://github.com/dotnet/runtime/issues/40679 . Try upgrading to newer Windows insider build, or apply registry key workaround mentioned in #40679 .

**Closed by jkotas** 2020-09-05 21:13 UTC
Labels: untriaged
