### ISSUE TITLE
If a program is terminated by unhandled exception, its OS process remains

### ISSUE THREAD

**Issue by wsy** [dotnet/runtime#102568] opened 2024-05-22 15:20 UTC
### Description

If a program gets terminated by unhandled exception, the underlying OS process will not be terminated as expected.

### Reproduction Steps

1. Write a simple dotnet program which throws an exception. Then compile it as "sample.exe".
```
// Sample.csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
</Project>
```
```
// Program.cs
using System;

Console.WriteLine("Hello, World!");
// Application is terminated by exception,
// process will (but should not)
// remain in taskmgr.exe
throw new Exception();
```
2. Execute "sample.exe".
3. In taskmgr.exe, see if "sample.exe" has disappeared.
4. Try to delete "sample.exe".

### Expected behavior

2. "sample.exe" should be terminated by "Unhandled exception".
3. "sample.exe" should disappear from taskmgr.exe
4. Delete operation should be successful.

### Actual behavior

2. "sample.exe" is terminated by "Unhandled exception" as expected.
3. "sample.exe" still exists in taskmgr.exe with status "Suspended" and "Commit size" almost same as it was when the program was running.
4. Delete operation failed with error message "File In Use"

![image](https://github.com/dotnet/runtime/assets/2684991/6e9d709e-63e0-416d-b0dd-25cb21dc3392)

# Further operation:
1. If you try to kill process "sample.exe", you will "succeed" for the first time.
2. However, the process "sample.exe" is still shown in taskmgr.exe with "Commit Size" of "84K". (No matter how much memory was requested before program exited.)
3. If you try to kill process "sample.exe" again, you will get "Access denied" error.
![image](https://github.com/dotnet/runtime/assets/2684991/9732241f-925f-4a55-b157-a0b0772a7ede)

4. If you try to delete "sample.exe" at this time, file delete operation will succeed. However, the process still remains in taskmgr.exe
![image](https://github.com/dotnet/runtime/assets/2684991/43bf01c9-1df9-466c-9143-b5e21306fa32)

### Configuration

.NET version: 8.x, 7.x, 6.x
OS: Windows 11 22621.3593
Architecture: x64

### Other information

I tried this in Windows Sandbox, which should be a clean environment.
I first noticed this bug with .Net 8. However, when I was taking screenshots for this bug report, I tried with .Net7 and .Net6 and this bug can still be re-produced.

**Comment by wsy** [comment] 2024-05-24 22:59
I tried this on another Windows 11 machine and I got same result.

I also tried this on Windows Server 2022, and this problem does not exist.

Another detail that I noticed: I saw two processes in Task Manager and one of them (with state 'Running') exited normally while another one (with state 'Suspend') remained in Task Manager.

**Comment by danmoseley** [comment] 2024-05-25 00:09
Can you try with .NET Framework as well?

**Comment by wsy** [comment] 2024-05-25 11:45
Hi @danmoseley ,
I tried and this bug can be re-produced with .NET Framework.
Same result, and I saw two "Program.exe" processes in Task Manager.
![image](https://github.com/dotnet/runtime/assets/2684991/bcd0207c-7c94-4d72-9958-3e12fdff7ce7)

**Comment by wsy** [comment] 2024-05-25 14:28
I tried Windows 11 21H2 ver 22000.675 with built-in .NET Framework 4.8.4161.
I can see when exception is thrown, a second process showed in Task Manager with state "Suspended". This is same as my Windows 11 22H2 ver 22621.3593. But the second process would exit alongside with the original process.

**Comment by tommcdon** [comment] 2024-06-05 14:33
Hi @wsy!  The "suspended" process is likely an artifact of Windows Error Reporting (WER) collecting a dump of the process after the unhandled exception.  In task manager, please determine if there is a `werfault.exe` running at the same time as the suspended process exists.  After WER completes, the secondary process should go away.  Hope this helps, and please let us know if this answers the question!

**Comment by wsy** [comment] 2024-06-12 08:55
> Hi @wsy! The "suspended" process is likely an artifact of Windows Error Reporting (WER) collecting a dump of the process after the unhandled exception. In task manager, please determine if there is a `werfault.exe` running at the same time as the suspended process exists. After WER completes, the secondary process should go away. Hope this helps, and please let us know if this answers the question!

Hi @tommcdon ,
Sorry for the delay. Today I tried in my Windows Sandbox with dotnet 8.0.
After the exception has been thrown, the second process showed up in Task Manager together with werfault.exe.
However, werfault.exe quickly disappeared while the second process remained.

**Comment by CyrusNajmabadi** [comment] 2024-06-12 18:09
FWIW, i've been running into this a lot.  Processes left behind int eh suspended state, never fully closing down.  Perhaps it's a werfault issue?  They do some reporting, but then don't properly clean up once done?

**Comment by wsy** [comment] 2024-06-13 13:22
> FWIW, i've been running into this a lot. Processes left behind int eh suspended state, never fully closing down. Perhaps it's a werfault issue? They do some reporting, but then don't properly clean up once done?

Hi,
If this is werfault issue, how do we report this issue? And to whom shall we report this issue to?

**Comment by wsy** [comment] 2024-06-13 13:35
Hi @CyrusNajmabadi ,
I tried with a C program (code below).
And this program can re-produce this bug. When this program exited, a process with suspended state remained in Task Manager.
Now I think it's very likely a werfault issue.
``` c
int main()
{
  int *p = 0;
  int e = *p;
  return 0;
}
```

**Comment by tommcdon** [comment] 2024-06-14 17:18
> Hi, If this is werfault issue, how do we report this issue? And to whom shall we report this issue to?

I'll be happy to report it to the WER team.  Doing some quick [research ](https://superuser.com/questions/1840266/windows-error-logging-werfault-leaves-unkillable-suspended-process) it seems that the suspended process might caused by leaving task manager open.  @wsy would you mind trying to close task manager, then re-open it to see if the suspended/defunct process is still there?

**Comment by wsy** [comment] 2024-06-15 01:27
> > Hi, If this is werfault issue, how do we report this issue? And to whom shall we report this issue to?
> 
> 
> 
> I'll be happy to report it to the WER team.  Doing some quick [research ](https://superuser.com/questions/1840266/windows-error-logging-werfault-leaves-unkillable-suspended-process) it seems that the suspended process might caused by leaving task manager open.  @wsy would you mind trying to close task manager, then re-open it to see if the suspended/defunct process is still there?

Hi,
I tried this just now.
The suspended process disappeared after I close taskmgr.
So, is this a taskmgr issue or werfault issue?
It seems I will have to suspend my habit of 'keeping taskmgr open forever' until Windows team fix this?

**Comment by wsy** [comment] 2024-06-15 01:35
By the way, I have to say, the new taskmgr is really far away from the word 'stable'.
I have a habit of opening taskmgr all the time (minimized to system tray) while my computer is running. I have had this habit since Windows XP.
And since Windows 11, the new taskmgr is significantly slower than its Windows 10 ancestor. Also, it would become unresponsive after running for days.

**Comment by tommcdon** [comment] 2024-06-17 15:57
@wsy I suggest reporting the task manager issue using the Feedback Hub tool in Windows - https://go.microsoft.com/fwlink/?linkid=760672.  This will help ensure the problem will be routed to the right team and will be tracked properly.  Since this is not a dotnet specific problem, I will close this issue.

**Closed by tommcdon** 2024-06-17 15:57 UTC
Labels: area-Diagnostics-coreclr, needs-further-triage
