### ISSUE TITLE
Test failure profiler/multiple/multiple/multiple.sh

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#81324] opened 2023-01-29 01:31 UTC
Run: [runtime-coreclr jitstress-isas-arm 20230128.1](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=151740)
 
 **Failed tests:**
 ```
 coreclr linux arm64 Checked jitstress_isas_nohwintrinsic_nosimd @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
     - profiler/multiple/multiple/multiple.sh
 ```
 
 **Error message:**
 ```
 Unhandled exception. System.Exception: Profilee returned exit code 139 instead of expected exit code 100.
   at Profiler.Tests.ProfilerTestRunner.FailFastWithMessage(String error)
   at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions, Dictionary`2 envVars, String reverseServerName, Boolean loadAsNotification, Int32 notificationCopies)
   at Profiler.Tests.MultiplyLoaded.Main(String[] args)
/root/helix/work/workitem/e/profiler/multiple/multiple/multiple.sh: line 423:    38 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/profiler.multiple/multiple/multiple.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false multiple.dll ''
Profiler path: /root/helix/work/workitem/e/profiler/multiple/multiple/libProfiler.so
Profiler path: /root/helix/work/workitem/e/profiler/multiple/multiple/libProfiler.so
Profiler.dll!DllGetClassObject
Profiler.dll!Profiler::Initialize
Setting exception mask
Profiler.dll!DllGetClassObject
Profiler.dll!Profiler::Initialize
Profiler path: /root/helix/work/workitem/e/profiler/multiple/multiple/libProfiler.so
Setting exception mask
MultiplyLoaded::ExceptionThrown, number seen = 0
MultiplyLoaded::ExceptionThrown, number seen = 1
Requesting detach!!
RequestProfilerDetach hr=0x0
Requesting detach!!
ProfilerDetachSucceeded _detachCount=1
Profiler.dll!DllGetClassObject
RequestProfilerDetach hr=0x0
ProfilerDetachSucceeded _detachCount=2
PROFILER TEST PASSES
Profiler.dll!Profiler::Initialize
Throwing exception
Exception caught
Waiting for profilers to all detach
Setting exception mask
MultiplyLoaded::ExceptionThrown, number seen = 2
Profiler.dll!Profiler::Shutdown

Test failed: Profilee returned exit code 139 instead of expected exit code 100.
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 1/28/2023 8:52:42 PM
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/e/profiler/multiple/multiple/multiple.sh
Expected: True
Actual:   False
 ```
 
 **Stack trace:**
 ```
   at profiler_multiple._multiple_multiple_._multiple_multiple_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
 ```

**Comment by tommcdon** [comment] 2023-02-08 15:42
@davmason  would you mind taking a look?

**Comment by davmason** [comment] 2023-04-08 00:02
Closing as dupe of #82690

**Closed by davmason** 2023-04-08 00:02 UTC
Labels: os-linux, JitStress, area-Diagnostics-coreclr, blocking-clean-ci-optional
