### ISSUE TITLE
Incorrect COMReference entries when including Office interop

### ISSUE THREAD

**Issue by JohnyL** [dotnet/runtime#796] opened 2019-12-12 16:53 UTC
To include Excel interop libraries, I do the following: `Dependencies -> Add Reference -> COM -> Microsoft Excel 14.0 Object Library`. When I do this, I get the following `ItemGroup`:
```
<ItemGroup>
    <COMReference Include="Microsoft.Office.Excel.dll">
        <Guid>00020813-0000-0000-c000-000000000046</Guid>
        <VersionMajor>1</VersionMajor>
        <VersionMinor>7</VersionMinor>
        <WrapperTool>tlbimp</WrapperTool>
        <Lcid>0</Lcid>
        <Isolated>false</Isolated>
    </COMReference>
</ItemGroup>
```
However, I get the following error:
> Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'office, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c'. The system cannot find the file specified.

In order to work, I have created .NET Framework app, added COM reference there and copied its COMReference - and **it works**:
```
<ItemGroup>
    <COMReference Include="Microsoft.Office.Interop.Excel">
        <Guid>{00020813-0000-0000-C000-000000000046}</Guid>
        <VersionMajor>1</VersionMajor>
	<VersionMinor>7</VersionMinor>
	<Lcid>0</Lcid>
	<WrapperTool>primary</WrapperTool>
	<Isolated>False</Isolated>
	<EmbedInteropTypes>True</EmbedInteropTypes>
    </COMReference>
</ItemGroup>
```

**Comment by 0xd4d** [comment] 2019-12-12 20:32
Looks like a dupe of https://github.com/dotnet/sdk/issues/3993 and https://github.com/dotnet/runtime/issues/707

**Comment by AaronRobinsonMSFT** [comment] 2019-12-12 20:55
@JohnyL Is this a run time or build time error? It seems like a run time error and is because of the missing types. The fix would be to deploy the PIA or add the `<EmbedInteropTypes>True</EmbedInteropTypes>`.

**Comment by JohnyL** [comment] 2019-12-13 06:07
@AaronRobinsonMSFT Yes, it's run time error. Adding `<EmbedInteropTypes>True</EmbedInteropTypes>` did work! This means that this COMReference lacks this entry.

**Comment by AaronRobinsonMSFT** [comment] 2019-12-13 17:20
@rainersigwald I don't have access to the MSBuild repo, but this work is going to happen in there. I believe that contains the logic for adding the `ComReference` node? This might actually be in the VS side of things, but I am not entirely sure.

@Pilchie Does VS handle the updating of the `.csproj` file when adding a COM reference? If so, would it be possible to move this issue to a VS repo or should I create an internal issue for defaulting to `EmbedInteropTypes` when adding a COM reference to a .NET Core project?

**Comment by Pilchie** [comment] 2019-12-13 17:39
I'm not on the project system team anymore, so tagging @jjmew, but you can use https://github.com/dotnet/project-system for issues there.

**Comment by drewnoakes** [comment] 2019-12-16 06:46
This can be closed in lieu of https://github.com/dotnet/project-system/issues/5735

**Comment by AaronRobinsonMSFT** [comment] 2019-12-16 18:40
@drewnoakes Thanks!

**Closed** 2019-12-16 18:40 UTC
Labels: area-Interop, untriaged
