### ISSUE TITLE
Assert failure: !PreemptiveGCDisabled()

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#70307] opened 2022-06-06 20:40 UTC
https://dev.azure.com/dnceng/public/_build/results?buildId=1808413&view=ms.vss-test-web.build-test-results-tab&runId=48117444&paneView=debug

net7.0-windows-Release-x86-CoreCLR_checked-no_tiered_compilation-Windows.10.Amd64.Open,
System.Xml.RW.FactoryReader.Tests

```
C:\h\w\A070095E\w\BB7109B8\e>call C:\h\w\A070095E\p\SetStressModes_no_tiered_compilation.cmd 

C:\h\w\A070095E\w\BB7109B8\e>set COMPlus_TieredCompilation=0 

C:\h\w\A070095E\w\BB7109B8\e>set COMPlus 
COMPlus_TieredCompilation=0

C:\h\w\A070095E\w\BB7109B8\e>call RunTests.cmd --runtime-path C:\h\w\A070095E\p 
----- start Mon 06/06/2022  8:20:19.50 ===============  To repro directly: ===================================================== 
pushd C:\h\w\A070095E\w\BB7109B8\e\
"C:\h\w\A070095E\p\dotnet.exe" exec --runtimeconfig System.Xml.RW.FactoryReader.Tests.runtimeconfig.json --depsfile System.Xml.RW.FactoryReader.Tests.deps.json xunit.console.dll System.Xml.RW.FactoryReader.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================

C:\h\w\A070095E\w\BB7109B8\e>"C:\h\w\A070095E\p\dotnet.exe" exec --runtimeconfig System.Xml.RW.FactoryReader.Tests.runtimeconfig.json --depsfile System.Xml.RW.FactoryReader.Tests.deps.json xunit.console.dll System.Xml.RW.FactoryReader.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Xml.RW.FactoryReader.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Xml.RW.FactoryReader.Tests (found 1 test case)
  Starting:    System.Xml.RW.FactoryReader.Tests (parallel test collections = on, max threads = 4)

Assert failure(PID 4708 [0x00001264], Thread: 5164 [0x142c]): !PreemptiveGCDisabled()

CORECLR! GetCLRRuntimeHost + 0x140B08 (0x72458d18)
CORECLR! GetCLRRuntimeHost + 0x5CF37C (0x728e758c)
CORECLR! coreclr_shutdown_2 + 0x9C76 (0x728f8ac6)
NTDLL! RtlDecompressBuffer + 0xDE (0x7763ea4e)
NTDLL! LdrShutdownThread + 0x386 (0x7760eeb6)
NTDLL! WinSqmEventWrite + 0x1052A (0x77663c6a)
NTDLL! LdrShutdownProcess + 0x15F (0x77622d7f)
NTDLL! RtlExitUserProcess + 0x96 (0x77623886)
KERNEL32! ExitProcess + 0x13 (0x7570b3e3)
CORECLR! coreclr_shutdown_2 + 0x43F78 (0x72932dc8)
    File: D:\a\_work\1\s\src\coreclr\vm\threads.cpp Line: 986
    Image: C:\h\w\A070095E\p\dotnet.exe
```

**Comment by janvorli** [comment] 2022-06-21 00:38
The CI run was missing a dump, but I was able to repro it locally in a couple of runs. The failure stack is as follows:
```
  Discovering: System.Xml.RW.FactoryReader.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Xml.RW.FactoryReader.Tests (found 1 test case)
  Starting:    System.Xml.RW.FactoryReader.Tests (parallel test collections = on, max threads = 20)

Assert failure(PID 47568 [0x0000b9d0], Thread: 4184 [0x1058]): !PreemptiveGCDisabled()

CORECLR! Thread::DetachThread + 0xCF (0x5e23e5cb)
CORECLR! TlsDestructionMonitor::~TlsDestructionMonitor + 0x8F (0x5e6b69f6)
CORECLR! _dyn_tls_dtor + 0x86 (0x5e6c7c86)
NTDLL! LdrHotPatchNotify + 0x24E9 (0x7772bef9)
NTDLL! LdrDeleteEnclave + 0x1A6 (0x77714bb6)
NTDLL! RtlDeactivateActivationContextUnsafeFast + 0x13E (0x776df0fe)
NTDLL! RtlDeactivateActivationContextUnsafeFast + 0x293 (0x776df253)
NTDLL! LdrShutdownProcess + 0x148 (0x776dc648)
NTDLL! RtlExitUserProcess + 0xB5 (0x7770ab65)
KERNEL32! ExitProcess + 0x13 (0x75778643)
    File: F:\git\runtime7\src\coreclr\vm\threads.cpp Line: 985
    Image: F:\git\runtime7\artifacts\bin\testhost\net7.0-windows-Release-x86\dotnet.exe
```
So we are detaching a thread during process shutdown and the assert fires because the thread was not in GC cooperative mode.

Adding @VSadov as he's implemented the `TlsDestructionMonitor` related change

**Comment by mangod9** [comment] 2022-08-04 05:38
@VSadov do you plan to investigate this soon as its marked for 7?

**Comment by VSadov** [comment] 2022-08-04 06:51
I'd like to figure why this happens and it is a stress nuisance. 
It might be just an assert though. We have seen no crashes or deadlocks due to this.

**Comment by mangod9** [comment] 2022-08-09 16:38
Are you able to repro it locally as Jan was able to a few weeks ago?

**Comment by VSadov** [comment] 2022-08-09 18:03
It does not reproduce for me right now, but I saw this begore. 
It is fairly rare and happens on process exit. Maybe it is just a matter of making the assert aware of process shutdown.

**Comment by VSadov** [comment] 2022-08-13 02:34
The original code, prior the TLS change also had the same assert and did not switch modes. It is reasonable to expect that a thread that is exiting has left coop mode by the time the tls monitor is destroyed. 

In this particular case we see this as a result of `ExitProcess`, which must be PInvoked. I am not sure how we can be in coop mode in a PInvoke.

**Comment by VSadov** [comment] 2022-08-13 02:45
Basically, nothing is happening to the thread past this point as it is effectively dead and will not run managed code. 
I think the assert itself is ignorable, but the state of the thread is suspicious. 

I wonder if it was a result of some other corruption, that could be gone and that is why it is not reproducing.

**Comment by VSadov** [comment] 2022-08-13 02:46
If we do not see this happening in CI any more, perhaps we can just close this?

**Comment by mangod9** [comment] 2022-08-15 15:41
Ok closing for now, we can reopen if this reoccurs.

**Comment by BrianBohe** [comment] 2022-12-13 19:27
It seems it is happening again on [pipeline runtime-coreclr pgostress](https://dev.azure.com/dnceng-public/public/_build?definitionId=230&_a=summary) on its last run from last friday 12/09:
```
JIT\opt\Vectorization\UnrollEqualsStartsWIth\UnrollEqualsStartsWIth.cmd [FAIL]
      
      Assert failure(PID 5484 [0x0000156c], Thread: 5832 [0x16c8]): !PreemptiveGCDisabled()
      
      CORECLR! Thread::DetachThread + 0xCF (0x709f86e6)
      CORECLR! TlsDestructionMonitor::~TlsDestructionMonitor + 0x8F (0x70e5ef81)
      CORECLR! _dyn_tls_dtor + 0x86 (0x70e71536)
      NTDLL! RtlDecompressBuffer + 0xDE (0x77b0ea4e)
      NTDLL! LdrShutdownThread + 0x386 (0x77adeeb6)
      NTDLL! LdrSetAppCompatDllRedirectionCallback + 0x1052A (0x77b33c6a)
      NTDLL! LdrShutdownProcess + 0x15F (0x77af2d7f)
      NTDLL! RtlExitUserProcess + 0x96 (0x77af3886)
      KERNEL32! ExitProcess + 0x13 (0x7783b3e3)
      CORECLR! exit_or_terminate_process + 0x38 (0x70eab9a8)
          File: D:\a\_work\1\s\src\coreclr\vm\threads.cpp Line: 979
          Image: C:\h\w\B8970A6E\p\corerun.exe
```
[full log ](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-fb34d63862ff48f0be/JIT.1/1/console.bbee2ac8.log?helixlogtype=result)

**Comment by VSadov** [comment] 2022-12-13 21:20
Just to confirm that I saw that the issue was reactivated. Did not have time to look at it yet.

**Comment by mangod9** [comment] 2024-07-03 21:33
Closing since this is an old issue.

**Closed by mangod9** 2024-07-03 21:33 UTC
Labels: area-VM-coreclr, blocking-clean-ci-optional
