### ISSUE TITLE
Test failure JIT\\jit64\\opt\\rngchk\\ArrayWithThread_o\\ArrayWithThread_o.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#65687] opened 2022-02-22 01:32 UTC
Run: [runtime-coreclr crossgen2 20220220.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1624033&view=ms.vss-test-web.build-test-results-tab&runId=45115586&resultId=100377&paneView=debug)

Failed test:
```
R2R-CG2 windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open
- JIT\\jit64\\opt\\rngchk\\ArrayWithThread_o\\ArrayWithThread_o.cmd
- JIT\\jit64\\opt\\inl\\caninline_ro\\caninline_ro.cmd
- JIT\\jit64\\opt\\regress\\vswhidbey\\223862\\mul_exception_dbg\\mul_exception_dbg.cmd
- JIT\\jit64\\opt\\cg\\cgstress\\CgStress2_ro\\CgStress2_ro.cmd
- JIT\\jit64\\opt\\cse\\staticFieldExprUnchecked1_r_loop\\staticFieldExprUnchecked1_r_loop.cmd
- JIT\\jit64\\opt\\cse\\staticFieldExprUnchecked1_r\\staticFieldExprUnchecked1_r.cmd
- JIT\\jit64\\opt\\cse\\staticFieldExprUnchecked1_d_loop_try\\staticFieldExprUnchecked1_d_loop_try.cmd
- JIT\\jit64\\opt\\cse\\staticFieldExprUnchecked1_r_try\\staticFieldExprUnchecked1_r_try.cmd
- JIT\\jit64\\opt\\rngchk\\JaggedArray_o\\JaggedArray_o.cmd
- JIT\\jit64\\opt\\rngchk\\RngchkStress3\\RngchkStress3.cmd
- JIT\\jit64\\opt\\rngchk\\RngchkStress1_o\\RngchkStress1_o.cmd
- JIT\\jit64\\opt\\rngchk\\ArrayBound_o\\ArrayBound_o.cmd
- JIT\\jit64\\opt\\rngchk\\ArrayWithFunc_o\\ArrayWithFunc_o.cmd
- JIT\\jit64\\opt\\**
```
**Error message:**
```
Could Not Find C:\h\w\A0E608E4\w\C0650A57\e\JIT\jit64\opt\rngchk\ArrayWithThread_o\IL-CG2\composite-r2r.dll
Could Not Find C:\h\w\A0E608E4\w\C0650A57\e\JIT\jit64\opt\rngchk\ArrayWithThread_o\ArrayWithThread_o.dll.rsp
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'System.Diagnostics.Tracing, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The module was expected to contain an assembly manifest.
File name: 'System.Diagnostics.Tracing, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
at ILCompiler.Program.Run(String[] args)
at ILCompiler.Program.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\A0E608E4\w\C0650A57\uploads\Reports\JIT.jit64\opt\rngchk\ArrayWithThread_o\ArrayWithThread_o.output.txt
Raw output:
BEGIN EXECUTION
ArrayWithThread_o.dll
1 file(s) copied.
Response file: C:\h\w\A0E608E4\w\C0650A57\e\JIT\jit64\opt\rngchk\ArrayWithThread_o\ArrayWithThread_o.dll.rsp
C:\h\w\A0E608E4\w\C0650A57\e\JIT\jit64\opt\rngchk\ArrayWithThread_o\IL-CG2\ArrayWithThread_o.dll
-o:C:\h\w\A0E608E4\w\C0650A57\e\JIT\jit64\opt\rngchk\ArrayWithThread_o\ArrayWithThread_o.dll
--targetarch:x64
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\A0E608E4\p\System..dll
-r:C:\h\w\A0E608E4\p\Microsoft..dll
-r:C:\h\w\A0E608E4\p\mscorlib.dll
-r:C:\h\w\A0E608E4\p\netstandard.dll
-O
" "dotnet" "C:\h\w\A0E608E4\p\crossgen2\crossgen2.dll" @"C:\h\w\A0E608E4\w\C0650A57\e\JIT\jit64\opt\rngchk\ArrayWithThread_o\ArrayWithThread_o.dll.rsp"   -r:C:\h\w\A0E608E4\w\C0650A57\e\JIT\jit64\opt\rngchk\ArrayWithThread_o\IL-CG2*.dll"
Crossgen2 failed with exitcode - -532462766
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\A0E608E4\p
C:\h\w\A0E608E4\w\C0650A57\e\JIT\jit64\opt\rngchk\ArrayWithThread_o\ArrayWithThread_o.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_jit64._opt_rngchk_ArrayWithThread_o_ArrayWithThread_o_._opt_rngchk_ArrayWithThread_o_ArrayWithThread_o_cmd()
```

**Comment by trylek** [comment] 2022-04-04 20:27
Closing as duplicate of: https://github.com/dotnet/runtime/issues/65646

**Closed by trylek** 2022-04-04 20:27 UTC
Labels: os-windows, arch-x64, area-crossgen2-coreclr, untriaged
