### ISSUE TITLE
Test failure in CreateDefaultBuilder_ConfigJsonDoesReload on Fedora 34 arm64

### ISSUE THREAD

**Issue by omajid** [dotnet/runtime#57139] opened 2021-08-10 15:52 UTC
### Description

Building and running runtime tests on Fedora 34 on arm64 leads to this unit test failing, sometimes.

For example, building dotnet/runtime at 1dfe32adcb30c18a617bb8870589cae225d522f0:

```text
+ ./build.sh --subset clr+libs+libs.tests --test --runtimeconfiguration Release --librariesConfiguration Debug /p:WithoutCategories=IgnoreForCI /p:NoPgoOptimize=true
__DistroRid: linux-arm64
...
System.IO.DirectoryNotFoundException : Could not find a part of the path '/tmp/ddmqdpcu.whx/src'.
at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound) in /home/tester/runtime/src/libraries/System.Private.CoreLib/src/System/IO/Enumeration/FileSystemEnumerator.Unix.cs:line 79
   at System.IO.Enumeration.FileSystemEnumerator`1.Init() in /home/tester/runtime/src/libraries/System.Private.CoreLib/src/System/IO/Enumeration/FileSystemEnumerator.Unix.cs:line 39
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options) in /home/tester/runtime/src/libraries/System.Private.CoreLib/src/System/IO/Enumeration/FileSystemEnumerator.cs:line 44
   at System.IO.Enumeration.FileSystemEnumerable`1.DelegateEnumerator..ctor(FileSystemEnumerable`1 enumerable, Boolean isNormalized) in /home/tester/runtime/src/libraries/System.Private.CoreLib/src/System/IO/Enumeration/FileSystemEnumerable.cs:line 66
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized) in /home/tester/runtime/src/libraries/System.Private.CoreLib/src/System/IO/Enumeration/FileSystemEnumerable.cs:line 38
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options) in /home/tester/runtime/src/libraries/System.Private.CoreLib/src/System/IO/Enumeration/FileSystemEnumerable.cs:line 26
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options) in /home/tester/runtime/src/libraries/System.Private.CoreLib/src/System/IO/Enumeration/FileSystemEnumerableFactory.cs:line 138
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options) in /home/tester/runtime/src/libraries/System.Private.CoreLib/src/System/IO/Directory.cs:line 184
   at System.IO.Directory.EnumerateDirectories(String path, String searchPattern, EnumerationOptions enumerationOptions) in /home/tester/runtime/src/libraries/System.Private.CoreLib/src/System/IO/Directory.cs:line 198
   at System.IO.Directory.EnumerateDirectories(String path) in /home/tester/runtime/src/libraries/System.Private.CoreLib/src/System/IO/Directory.cs:line 190
   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName) in /home/tester/runtime/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Linux.cs:line 440
   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName) in /home/tester/runtime/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Linux.cs:line 442
   at System.IO.FileSystemWatcher.RunningInstance.AddDirectoryWatchUnlocked(WatchedDirectory parent, String directoryName) in /home/tester/runtime/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Linux.cs:line 442
   at System.IO.FileSystemWatcher.RunningInstance..ctor(FileSystemWatcher watcher, SafeFileHandle inotifyHandle, String directoryPath, Boolean includeSubdirectories, NotifyFilters notifyFilters, CancellationToken cancellationToken) in /home/tester/runtime/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Linux.cs:line 293
   at System.IO.FileSystemWatcher.StartRaisingEvents() in /home/tester/runtime/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.Linux.cs:line 62
   at System.IO.FileSystemWatcher.StartRaisingEventsIfNotDisposed() in /home/tester/runtime/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.cs:line 638
   at System.IO.FileSystemWatcher.set_EnableRaisingEvents(Boolean value) in /home/tester/runtime/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.cs:line 151
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.TryEnableFileSystemWatcher() in /home/tester/runtime/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PhysicalFilesWatcher.cs:line 416
   at Microsoft.Extensions.FileProviders.Physical.PhysicalFilesWatcher.CreateFileChangeToken(String filter) in /home/tester/runtime/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PhysicalFilesWatcher.cs:line 153
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider.Watch(String filter) in /home/tester/runtime/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PhysicalFileProvider.cs:line 359
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.<.ctor>b__1_0() in /home/tester/runtime/src/libraries/Microsoft.Extensions.Configuration.FileExtensions/src/FileConfigurationProvider.cs:line 33
   at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, TState state) in /home/tester/runtime/src/libraries/Microsoft.Extensions.Primitives/src/ChangeToken.cs:line 71
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer) in /home/tester/runtime/src/libraries/Microsoft.Extensions.Primitives/src/ChangeToken.cs:line 32
   at Microsoft.Extensions.Configuration.FileConfigurationProvider..ctor(FileConfigurationSource source) in /home/tester/runtime/src/libraries/Microsoft.Extensions.Configuration.FileExtensions/src/FileConfigurationProvider.cs:line 32
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider..ctor(JsonConfigurationSource source) in /home/tester/runtime/src/libraries/Microsoft.Extensions.Configuration.Json/src/JsonConfigurationProvider.cs:line 20
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationSource.Build(IConfigurationBuilder builder) in /home/tester/runtime/src/libraries/Microsoft.Extensions.Configuration.Json/src/JsonConfigurationSource.cs:line 21
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build() in /home/tester/runtime/src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationBuilder.cs:line 51
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration() in /home/tester/runtime/src/libraries/Microsoft.Extensions.Hosting/src/HostBuilder.cs:line 230
   at Microsoft.Extensions.Hosting.HostBuilder.Build() in /home/tester/runtime/src/libraries/Microsoft.Extensions.Hosting/src/HostBuilder.cs:line 146
   at Microsoft.Extensions.Hosting.Tests.HostTests.CreateDefaultBuilder_ConfigJsonDoesReload() in /home/tester/runtime/src/libraries/Microsoft.Extensions.Hosting/tests/UnitTests/HostTests.cs:line 240
```
This isn't 100% reproducible. Sometimes it works.

The same test asses on Fedora 34 x64, so it's likely arm64 related?

### Configuration

* Which version of .NET is the code running on? Commit 1dfe32adcb30c18a617bb8870589cae225d522f0
* What OS and version, and what distro if applicable? Fedora 34
* What is the architecture (x64, x86, ARM, ARM64)? arm64
* Do you know whether it is specific to that configuration? Yes, probably. Test failure doesn't reproduce on x64

### Regression?

Maybe? The same test sometimes fails in the release/5.0 branch on Fedora 34/arm64 too, but it's less frequent.

**Comment by adamsitnik** [comment] 2021-08-11 07:59
@omajid big thanks for providing a very detailed bug report!

@carlossanlop @Jozkee Since this is not a regression I am moving it to 7.0, but if you have some time now it would be great to take a look in 6.0.

**Comment by omajid** [comment] 2021-08-23 22:30
Quick update: I just observed this error on x64 as well. This isn't arm64 specific as I initially suspected.

```
  /home/tester/runtime/artifacts/bin/testhost/net6.0-Linux-Debug-x64/dotnet exec --runtimeconfig Microsoft.Extensions.Hosting.Unit.Tests.runtimeconfig.json --depsfile Microsoft.Extensions.Hosting.Unit.Tests.deps.json xunit.console.dll Microsoft.Extensions.Hosting.Unit.Tests.dll -xml testResults.xml -nologo -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 

      Microsoft.Extensions.Hosting.Tests.HostTests.CreateDefaultBuilder_ConfigJsonDoesReload [FAIL]
  [31;1m[m[37m      Assert.Equal() Failure
  [m[37m                                    ↓ (pos 20)
  [m[37m      Expected: Hello ASP.NET Core: dff1e5f3eb4e4f458d53dbf6459c4af3
  [m[37m      Actual:   Hello ASP.NET Core: 22c0bf5583fe4351a9f11aa6ba914db5
  [m[37m                                    ↑ (pos 20)
  [m[30;1m      Stack Trace:
  [m[37m        /home/tester/runtime/src/libraries/Microsoft.Extensions.Hosting/tests/UnitTests/HostTests.cs(265,0): at Microsoft.Extensions.Hosting.Tests.HostTests.CreateDefaultBuilder_ConfigJsonDoesReload()
  [m[37m        --- End of stack trace from previous location ---
```

**Closed** 2022-02-18 07:49 UTC
Labels: bug, area-System.IO, needs-further-triage, in-pr
