### ISSUE TITLE
Installed .NET 6.0 and RuntimeInformation.FrameworkDescription property  is returning incorrect version.

### ISSUE THREAD

**Issue by speed2048** [dotnet/runtime#61330] opened 2021-11-08 22:52 UTC
### Description

I installed GA of .net 6.0 and the I returned the   RunTimeInformation.FramworkDescription  property and  contains the incorrect rtm version of the runtime. This issue occurs on other platforms as well.

### Reproduction Steps

Console.WriteLine($"Runtime = {RuntimeInformation.FrameworkDescription}");

### Expected behavior

Should return .NET 6.0.0

### Actual behavior

Api call returned : .NET 6.0.0-rtm.21522.10

### Regression?

Worked correctly in rc1 and rc2 of .net 6

### Known Workarounds

no workaround.

### Configuration

dotnet --info returned... 
Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by jkotas** [comment] 2021-11-09 00:31
Thank you for reporting this. It is scheduled to be fixed in 6.0.1 update (https://github.com/dotnet/runtime/pull/61240).

Duplicate of https://github.com/dotnet/runtime/issues/45812

**Closed by jkotas** 2021-11-09 00:31 UTC
Labels: untriaged
