### ISSUE TITLE
Blazor: Uncaught (in promise) RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#38117] opened 2020-06-18 20:42 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1077360/blazor-uncaught-in-promise-runtimeerror-memory-acc.html)._

---
This happens everytime.  Just run project to recreate.

I created a sample project [here(https://github.com/bfmsoft/WasmCrash) to show.  Just run project it happens everytime.  It is when it tries to access the AppState Object.  

This happens in Shared/NavMenu.razor line 17 - **@if (!AppState.IsLoggedIn)**
```
blazor Loaded 17.00 MB resourcesThis application was built with linking (tree shaking) disabled. Published applications will be significantly smaller.
**0075def2:1 Uncaught (in promise) RuntimeError: memory access out of bounds**
    at malloc (<anonymous>:wasm-function[359]:0xa5ab)
    at monoeg_malloc (<anonymous>:wasm-function[161]:0x3c6a)
    at stack_frag_new (<anonymous>:wasm-function[2019]:0x5b82c)
    at add_frag (<anonymous>:wasm-function[1430]:0x3edc6)
    at interp_exec_method (<anonymous>:wasm-function[1120]:0x316a3)
    at interp_runtime_invoke (<anonymous>:wasm-function[5654]:0xf944e)
    at mono_jit_runtime_invoke (<anonymous>:wasm-function[5108]:0xdfbfa)
    at do_runtime_invoke (<anonymous>:wasm-function[1410]:0x3db59)
    at mono_runtime_invoke_checked (<anonymous>:wasm-function[331]:0x969b)
    at mono_runtime_try_invoke_array (<anonymous>:wasm-function[2333]:0x68cfa)
malloc @ 0075def2:1
monoeg_malloc @ 0075def2:1
stack_frag_new @ 0075def2:1
add_frag @ 0075def2:1
interp_exec_method @ 0075def2:1
interp_runtime_invoke @ 0075def2:1
mono_jit_runtime_invoke @ 0075def2:1
do_runtime_invoke @ 0075def2:1
mono_runtime_invoke_checked @ 0075def2:1
mono_runtime_try_invoke_array @ 0075def2:1
ves_icall_InternalInvoke @ 0075def2:1
ves_icall_InternalInvoke_raw @ 0075def2:1
do_icall @ 0075def2:1
do_icall_wrapper @ 0075def2:1
interp_exec_method @ 0075def2:1
interp_runtime_invoke @ 0075def2:1
mono_jit_runtime_invoke @ 0075def2:1
do_runtime_invoke @ 0075def2:1
mono_runtime_try_invoke @ 0075def2:1
mono_runtime_invoke @ 0075def2:1
mono_wasm_invoke_method @ 0075def2:1
Module._mono_wasm_invoke_method @ dotnet.3.2.0-rc1.20222.2.js:1
call_method @ dotnet.3.2.0-rc1.20222.2.js:1
set_task_result @ dotnet.3.2.0-rc1.20222.2.js:1
(anonymous) @ dotnet.3.2.0-rc1.20222.2.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.3.2.0-rc1.20222.2.js:1
f.preRun.push.window.Blazor._internal.getSatelliteAssemblies @ blazor.webassembly.js:1
_mono_wasm_invoke_js_unmarshalled @ dotnet.3.2.0-rc1.20222.2.js:1
do_icall @ 0075def2:1
do_icall_wrapper @ 0075def2:1
interp_exec_method @ 0075def2:1
interp_runtime_invoke @ 0075def2:1
mono_jit_runtime_invoke @ 0075def2:1
do_runtime_invoke @ 0075def2:1
mono_runtime_try_invoke @ 0075def2:1
mono_runtime_invoke @ 0075def2:1
mono_wasm_invoke_method @ 0075def2:1
Module._mono_wasm_invoke_method @ dotnet.3.2.0-rc1.20222.2.js:1
call_method @ dotnet.3.2.0-rc1.20222.2.js:1
(anonymous) @ dotnet.3.2.0-rc1.20222.2.js:1
callEntryPoint @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
i @ blazor.webassembly.js:1
Promise.then (async)
s @ blazor.webassembly.js:1
i @ blazor.webassembly.js:1
Promise.then (async)
s @ blazor.webassembly.js:1
i @ blazor.webassembly.js:1
Promise.then (async)
s @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
r @ blazor.webassembly.js:1
v @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
n @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
0075def2:1 Uncaught RuntimeError: invalid index into function table
    at mono_background_exec (<anonymous>:wasm-function[5405]:0xed6ab)
    at Module._mono_background_exec (https://localhost:44399/_framework/wasm/dotnet.3.2.0-rc1.20222.2.js:1:203028)
    at pump_message (https://localhost:44399/_framework/wasm/dotnet.3.2.0-rc1.20222.2.js:1:123271)
mono_background_exec @ 0075def2:1
Module._mono_background_exec @ dotnet.3.2.0-rc1.20222.2.js:1
pump_message @ dotnet.3.2.0-rc1.20222.2.js:1
setTimeout (async)
_schedule_background_exec @ dotnet.3.2.0-rc1.20222.2.js:1
mono_threads_schedule_background_job @ 0075def2:1
ves_icall_System_Threading_ThreadPool_RequestWorkerThread @ 0075def2:1
ves_icall_System_Threading_ThreadPool_RequestWorkerThread_raw @ 0075def2:1
do_icall @ 0075def2:1
do_icall_wrapper @ 0075def2:1
interp_exec_method @ 0075def2:1
interp_runtime_invoke @ 0075def2:1
mono_jit_runtime_invoke @ 0075def2:1
do_runtime_invoke @ 0075def2:1
mono_runtime_invoke_checked @ 0075def2:1
mono_runtime_try_invoke_array @ 0075def2:1
ves_icall_InternalInvoke @ 0075def2:1
ves_icall_InternalInvoke_raw @ 0075def2:1
do_icall @ 0075def2:1
do_icall_wrapper @ 0075def2:1
interp_exec_method @ 0075def2:1
interp_runtime_invoke @ 0075def2:1
mono_jit_runtime_invoke @ 0075def2:1
do_runtime_invoke @ 0075def2:1
mono_runtime_try_invoke @ 0075def2:1
mono_runtime_invoke @ 0075def2:1
mono_wasm_invoke_method @ 0075def2:1
Module._mono_wasm_invoke_method @ dotnet.3.2.0-rc1.20222.2.js:1
call_method @ dotnet.3.2.0-rc1.20222.2.js:1
set_task_result @ dotnet.3.2.0-rc1.20222.2.js:1
(anonymous) @ dotnet.3.2.0-rc1.20222.2.js:1
Promise.then (async)
js_to_mono_obj @ dotnet.3.2.0-rc1.20222.2.js:1
f.preRun.push.window.Blazor._internal.getSatelliteAssemblies @ blazor.webassembly.js:1
_mono_wasm_invoke_js_unmarshalled @ dotnet.3.2.0-rc1.20222.2.js:1
do_icall @ 0075def2:1
do_icall_wrapper @ 0075def2:1
interp_exec_method @ 0075def2:1
interp_runtime_invoke @ 0075def2:1
mono_jit_runtime_invoke @ 0075def2:1
do_runtime_invoke @ 0075def2:1
mono_runtime_try_invoke @ 0075def2:1
mono_runtime_invoke @ 0075def2:1
mono_wasm_invoke_method @ 0075def2:1
Module._mono_wasm_invoke_method @ dotnet.3.2.0-rc1.20222.2.js:1
call_method @ dotnet.3.2.0-rc1.20222.2.js:1
(anonymous) @ dotnet.3.2.0-rc1.20222.2.js:1
callEntryPoint @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
i @ blazor.webassembly.js:1
Promise.then (async)
s @ blazor.webassembly.js:1
i @ blazor.webassembly.js:1
Promise.then (async)
s @ blazor.webassembly.js:1
i @ blazor.webassembly.js:1
Promise.then (async)
s @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
r @ blazor.webassembly.js:1
v @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
n @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
dotnet.3.2.0-rc1.20222.2.js:1 >>>mono_wasm_get_loaded_files
```
---
#### Visual Studio Feedback System on 6/15/2020, 02:37 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by fanyang-mono** [comment] 2020-06-24 23:57
I am not able to reproduce this crash either on MacOS using .NET SDK 5.0.100-preview.5.20279.10 + Microsoft.AspNetCore.Components.WebAssembly.Templates 3.2.0-rc1.20223.4, or on Windows 10 using the same step up from command line or using visual studio 16.7 Preview 3.

@mkArtakMSFT were you able to reproduce this crash?

**Comment by SamMonoRT** [comment] 2020-06-26 20:22
Add the same comment to the VS feedback ticket, maybe the user has more information / repro steps 
https://developercommunity.visualstudio.com/content/problem/1077360/blazor-uncaught-in-promise-runtimeerror-memory-acc.html

**Comment by SamMonoRT** [comment] 2020-07-06 20:04
Closing the issue, please re-open if this still reproes.

**Comment by tranpl** [comment] 2020-09-14 19:56
Getting this same error using .NET 5 SDK 5.0.100-rc.1
Tried to create a cascading dropdown for three dropdown. 
`
                                        <Select TValue="int" @bind-SelectedValue="SelectedTierOne">
                                            <SelectItem Value="0">Select tier one..</SelectItem>
                                            @foreach (var tierOne in TierOne)
                                            {
                                                <SelectItem Value="@tierOne.Id">@tierOne.Name (@tierOne.Description) </SelectItem>
                                            }
                                        </Select>
`
`                                            <Select TValue="int" @bind-SelectedValue="SelectedTierTwo">
                                                <SelectItem Value="0">Select tier two..</SelectItem>
                                                @foreach (var tierTwo in TierTwo)
                                                {
                                                    <SelectItem Value="@tierTwo.Id">@tierTwo.Name (@tierTwo.Description) </SelectItem>
                                                }
                                            </Select>`
`                                            <Select TValue="int">
                                                <SelectItem Value="0">Select tier three..</SelectItem>
                                                @foreach (var iteThree in TierThree)
                                                {
                                                    <SelectItem Value="@iteThree.Id">@iteThree.Name (@iteThree.Description) </SelectItem>
                                                }
                                            </Select>`
Tried using @bind-Value instead of the Blazorise specific callbacks.
 
Uncaught RuntimeError: memory access out of bounds
    at dlmalloc (https://localhost:5001/_framework/dotnet.wasm:wasm-function[398]:0xc52a)
    at dlcalloc (https://localhost:5001/_framework/dotnet.wasm:wasm-function[698]:0x145ef)
    at monoeg_g_calloc (https://localhost:5001/_framework/dotnet.wasm:wasm-function[2598]:0x61f77)
    at monoeg_malloc0 (https://localhost:5001/_framework/dotnet.wasm:wasm-function[131]:0x5e64)
    at monoeg_g_hash_table_new (https://localhost:5001/_framework/dotnet.wasm:wasm-function[177]:0x69be)
    at mono_class_from_name_checked (https://localhost:5001/_framework/dotnet.wasm:wasm-function[825]:0x17f07)
    at mono_class_load_from_name (https://localhost:5001/_framework/dotnet.wasm:wasm-function[174]:0x6966)
    at mono_set_timeout_exec (https://localhost:5001/_framework/dotnet.wasm:wasm-function[7092]:0x10d69b)
    at Module._mono_set_timeout_exec (https://localhost:5001/_framework/dotnet.5.0.0-rc.1.20451.14.js:1:213865)
    at https://localhost:5001/_framework/dotnet.5.0.0-rc.1.20451.14.js:1:150505
dlmalloc	@	dotnet.wasm:0xc52a
dlcalloc	@	dotnet.wasm:0x145ef
monoeg_g_calloc	@	dotnet.wasm:0x61f77
monoeg_malloc0	@	dotnet.wasm:0x5e64
monoeg_g_hash_table_new	@	dotnet.wasm:0x69be
mono_class_from_name_checked	@	dotnet.wasm:0x17f07
mono_class_load_from_name	@	dotnet.wasm:0x6966
mono_set_timeout_exec	@	dotnet.wasm:0x10d69b
Module._mono_set_timeout_exec	@	dotnet.5.0.0-rc.1.20451.14.js:1
(anonymous)	@	dotnet.5.0.0-rc.1.20451.14.js:1
setTimeout (async)		
_mono_set_timeout	@	dotnet.5.0.0-rc.1.20451.14.js:1
mono_wasm_set_timeout	@	dotnet.wasm:0x108045
do_icall	@	dotnet.wasm:0x1943b6
do_icall_wrapper	@	dotnet.wasm:0x79894
interp_exec_method	@	dotnet.wasm:0x4442c
interp_runtime_invoke	@	dotnet.wasm:0x12e8ab
mono_jit_runtime_invoke	@	dotnet.wasm:0x118342
do_runtime_invoke	@	dotnet.wasm:0x797dd
mono_runtime_try_invoke	@	dotnet.wasm:0x13aa6
mono_runtime_invoke	@	dotnet.wasm:0x10e12a
mono_wasm_invoke_method	@	dotnet.wasm:0x1084ab
Module._mono_wasm_invoke_method	@	dotnet.5.0.0-rc.1.20451.14.js:1
call_method	@	dotnet.5.0.0-rc.1.20451.14.js:1
(anonymous)	@	dotnet.5.0.0-rc.1.20451.14.js:1
endInvokeJSFromDotNet	@	blazor.webassembly.js:1
(anonymous)	@	blazor.webassembly.js:1
Promise.then (async)		
beginInvokeJSFromDotNet	@	blazor.webassembly.js:1
w	@	blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor	@	dotnet.5.0.0-rc.1.20451.14.js:1
do_icall	@	dotnet.wasm:0x1944fd
do_icall_wrapper	@	dotnet.wasm:0x79894
interp_exec_method	@	dotnet.wasm:0x4442c
interp_runtime_invoke	@	dotnet.wasm:0x12e8ab
mono_jit_runtime_invoke	@	dotnet.wasm:0x118342
do_runtime_invoke	@	dotnet.wasm:0x797dd
mono_runtime_try_invoke	@	dotnet.wasm:0x13aa6
mono_runtime_invoke	@	dotnet.wasm:0x10e12a
mono_wasm_invoke_method	@	dotnet.wasm:0x1084ab
Module._mono_wasm_invoke_method	@	dotnet.5.0.0-rc.1.20451.14.js:1
call_method	@	dotnet.5.0.0-rc.1.20451.14.js:1
(anonymous)	@	dotnet.5.0.0-rc.1.20451.14.js:1
endInvokeJSFromDotNet	@	blazor.webassembly.js:1
(anonymous)	@	blazor.webassembly.js:1
Promise.then (async)		
beginInvokeJSFromDotNet	@	blazor.webassembly.js:1
w	@	blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor	@	dotnet.5.0.0-rc.1.20451.14.js:1
do_icall	@	dotnet.wasm:0x1944fd
do_icall_wrapper	@	dotnet.wasm:0x79894
interp_exec_method	@	dotnet.wasm:0x4442c
interp_runtime_invoke	@	dotnet.wasm:0x12e8ab
mono_jit_runtime_invoke	@	dotnet.wasm:0x118342
do_runtime_invoke	@	dotnet.wasm:0x797dd
mono_runtime_try_invoke	@	dotnet.wasm:0x13aa6
mono_runtime_invoke	@	dotnet.wasm:0x10e12a
mono_wasm_invoke_method	@	dotnet.wasm:0x1084ab
Module._mono_wasm_invoke_method	@	dotnet.5.0.0-rc.1.20451.14.js:1
call_method	@	dotnet.5.0.0-rc.1.20451.14.js:1
set_task_result	@	dotnet.5.0.0-rc.1.20451.14.js:1
(anonymous)	@	dotnet.5.0.0-rc.1.20451.14.js:1
Promise.then (async)		
js_to_mono_obj	@	dotnet.5.0.0-rc.1.20451.14.js:1
f.preRun.push.window.Blazor._internal.getSatelliteAssemblies	@	blazor.webassembly.js:1
w	@	blazor.webassembly.js:1
_mono_wasm_invoke_js_blazor	@	dotnet.5.0.0-rc.1.20451.14.js:1
do_icall	@	dotnet.wasm:0x1944fd
do_icall_wrapper	@	dotnet.wasm:0x79894
interp_exec_method	@	dotnet.wasm:0x4442c
interp_runtime_invoke	@	dotnet.wasm:0x12e8ab
mono_jit_runtime_invoke	@	dotnet.wasm:0x118342
do_runtime_invoke	@	dotnet.wasm:0x797dd
mono_runtime_invoke_checked	@	dotnet.wasm:0xfee2
mono_runtime_try_invoke_array	@	dotnet.wasm:0x10dd31
ves_icall_InternalInvoke	@	dotnet.wasm:0xecc38
ves_icall_InternalInvoke_raw	@	dotnet.wasm:0xec6fe
do_icall	@	dotnet.wasm:0x19448a
do_icall_wrapper	@	dotnet.wasm:0x79894
interp_exec_method	@	dotnet.wasm:0x4442c
interp_runtime_invoke	@	dotnet.wasm:0x12e8ab
mono_jit_runtime_invoke	@	dotnet.wasm:0x118342
do_runtime_invoke	@	dotnet.wasm:0x797dd
mono_runtime_try_invoke	@	dotnet.wasm:0x13aa6
mono_runtime_invoke	@	dotnet.wasm:0x10e12a
mono_wasm_invoke_method	@	dotnet.wasm:0x1084ab
Module._mono_wasm_invoke_method	@	dotnet.5.0.0-rc.1.20451.14.js:1
call_method	@	dotnet.5.0.0-rc.1.20451.14.js:1
(anonymous)	@	dotnet.5.0.0-rc.1.20451.14.js:1
callEntryPoint	@	blazor.webassembly.js:1
(anonymous)	@	blazor.webassembly.js:1
(anonymous)	@	blazor.webassembly.js:1
(anonymous)	@	blazor.webassembly.js:1
a	@	blazor.webassembly.js:1
Promise.then (async)		
u	@	blazor.webassembly.js:1
a	@	blazor.webassembly.js:1
Promise.then (async)		
u	@	blazor.webassembly.js:1
a	@	blazor.webassembly.js:1
Promise.then (async)		
u	@	blazor.webassembly.js:1
(anonymous)	@	blazor.webassembly.js:1
r	@	blazor.webassembly.js:1
g	@	blazor.webassembly.js:1
(anonymous)	@	blazor.webassembly.js:1
n	@	blazor.webassembly.js:1
(anonymous)	@	blazor.webassembly.js:1
(anonymous)	@	blazor.webassembly.js:1

**Comment by BiskitBone** [comment] 2020-09-23 07:08
I commonly see this error with a circular reference.

e.g. The return value of property A depends on Property B whose return value depends on Property A.

Yes I did this. Don't judge me!

**Comment by fanyang-mono** [comment] 2020-09-23 13:35
It seems to be reproducible again. Reopen the issue now.

**Comment by lewing** [comment] 2020-09-23 16:29
looking at https://github.com/bfmsoft/WasmCrash/blob/ec97191b45799e76a6d6be0283985317aac57180/WasmCrash/Shared/AppState.cs#L12 the code seems to be the problem.  The property getter is returning itself.  You'll need to to make a backing field to store the values and return that.

**Comment by lewing** [comment] 2020-09-23 16:35
The code needs to be changed to something like 

```
    string emailAddress;
    public string EmailAddress
        {
            get
            {
                return emailAddress;
            }
            set
            {
                emailAddress = value;
                NotifyStateChanged();
            }
        }
```

for both EmailAddress and PasswordHash, then IsLoggedIn should function.

**Closed by lewing** 2020-09-23 16:35 UTC
Labels: arch-wasm, area-Codegen-Interpreter-mono
