### ISSUE TITLE
Enable relevant thread pool events in Windows

### ISSUE THREAD

**Issue by LakshanF** [dotnet/runtime#87020] opened 2023-06-01 17:41 UTC
It seems like some IO `threadpool `events (`IOPack, IOEnqueue, and IODequeue`) can be enabled for windows in [NativeRuntimeEventSource.PortableThreadPool](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/NativeRuntimeEventSource.Threading.NativeSinks.cs). Given that `NativeAOT `now has `EventPipe`, we should do this work to help customers with their diagnostics scenarios.

cc @eduardo-vp, @kouvel

**Comment by kouvel** [comment] 2023-07-20 21:28
The portable thread pool implementation should already be raising the events on Windows and Unixes (though last I checked a while back, they weren't working yet). https://github.com/dotnet/runtime/pull/88894 is adding the raising of some events for the Windows thread pool implementation.

**Comment by kouvel** [comment] 2023-07-20 21:44
Aside from `IOPack`, which seemingly is not raised currently on NativeAOT Windows

**Comment by LakshanF** [comment] 2024-07-12 11:45
[ThreadPoolIOWork](https://github.com/LakshanF/runtime/blob/e2260fe4ef1d56f36d04c8cf27498a51bc9e6b23/src/coreclr/vm/ClrEtwAll.man#L3305) event is not yet working in Windows (either with the `UseWindowsThreadPool `property set to false or not). 

[NativeRuntimeEventSourceTest](https://github.com/dotnet/runtime/blob/61f08d36ac9d92a2c93a5478bf22f3fc82a0b7e8/src/tests/tracing/runtimeeventsource/NativeRuntimeEventSourceTest.cs#L49) can be used to validate this.

**Comment by MichalStrehovsky** [comment] 2024-07-12 12:51
I assume we don't want this in the 8.0 milestone that nobody is looking at anymore, so marked this untriaged.

**Comment by eduardo-vp** [comment] 2024-08-27 20:37
The cause of this issue is the same as this one https://github.com/dotnet/runtime/issues/105556 and was fixed by https://github.com/dotnet/runtime/pull/106641.

 I also verified the test fails before the fix and passes after.

**Closed by eduardo-vp** 2024-08-27 20:37 UTC
Labels: untriaged, area-NativeAOT-coreclr
