### ISSUE TITLE
Inconsistent behavior of DataRow.Field<T> with nullable enum type between .NET Framework and .NET Core

### ISSUE THREAD

**Issue by madelson** [dotnet/runtime#46597] opened 2021-01-05 20:00 UTC
### Description

The following code behaves differently when run on .NET Framework (I'm targeting net472) and .NET Core (I'm targeting netcoreapp3.1):

```
var table = new DataTable();
var row = table.NewRow();
table.Columns.Add("x", typeof(int));
row["x"] = (int)StringSplitOptions.RemoveEmptyEntries;
Console.WriteLine(row.Field<StringSplitOptions>("x"));
Console.WriteLine(row.Field<StringSplitOptions?>("x")); // DIFFERENCE HERE
```

In .NET Framework, the last line prints `RemoveEmptyEntries` to the console.

In .NET Core, the last line fails with an exception:
```
System.InvalidCastException : Unable to cast object of type 'System.Int32' to type 'System.Nullable`1[System.StringSplitOptions]'.
   at System.Data.DataRowExtensions.UnboxT`1.ReferenceOrNullableField(Object value)
   at System.Data.DataRowExtensions.Field[T](DataRow row, String columnName)
```

I'm not sure which behavior is desired, but I thought I'd report the discrepancy in case it was not intentional.

### Configuration

I'm running Visual Studio 16.8.3 on Windows 10 x64.

### Regression?

Worked in .NET Framework.

**Comment by madelson** [comment] 2021-03-11 11:48
@roji @ajcvickers any thoughts here?

**Comment by ajcvickers** [comment] 2021-03-11 23:28
@madelson Not yet; we still need to investigate.

**Comment by ajcvickers** [comment] 2021-07-13 17:18
I  am not able to reproduce this. I ran the following code on .NET Core 3.1 and .NET Core 5.0, and there was no exception.


```C#
public class Program
{
    public static void Main()
    {
        var table = new DataTable();
        var row = table.NewRow();
        table.Columns.Add("x", typeof(int));
        row["x"] = (int) StringSplitOptions.RemoveEmptyEntries;
        Console.WriteLine(row.Field<StringSplitOptions>("x"));
        Console.WriteLine(row.Field<StringSplitOptions?>("x"));
    }
}
```

Output
```
RemoveEmptyEntries
RemoveEmptyEntries
```

Please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by madelson** [comment] 2021-07-16 11:12
I just tried this again and I now see the framework behavior on .NET 5. Perhaps this was fixed by some unrelated patch between when I filed this and now?

**Comment by roji** [comment] 2021-07-16 11:15
That's somewhat unlikely (as we this part of the code is rarely touched), but it's possible.

Thanks for confirming that this works now, I'll go ahead and close the issue. Please don't hesitate to post back if you hit other issues.

**Closed by roji** 2021-07-16 11:15 UTC
Labels: area-System.Data
