### ISSUE TITLE
Test failure System.IO.Compression.GzipStreamUnitTests.ReadAsync_ContinuesOnCurrentTaskSchedulerIfDesired

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#65873] opened 2022-02-25 01:31 UTC
Run: [runtime-coreclr libraries-jitstress 20220223.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1629873&view=ms.vss-test-web.build-test-results-tab&runId=45214420&resultId=146733&paneView=debug)

Failed test:
```
net7.0-Linux-Release-arm64-CoreCLR_checked-jitstress2-(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- System.IO.Compression.GzipStreamUnitTests.ReadAsync_ContinuesOnCurrentTaskSchedulerIfDesired(flowExecutionContext: True, continueOnCapturedContext: False)

```
**Error message:**
```
System.NullReferenceException : Object reference not set to an instance of an object.


Stack trace
   at System.IO.ConnectedStreams.BidirectionalStreamBufferStream.Dispose(Boolean disposing) in /_/src/libraries/Common/tests/System/IO/ConnectedStreams.cs:line 299
   at System.IO.Stream.Close()
   at System.IO.Compression.DeflateStream.Dispose(Boolean disposing) in /_/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/DeflateStream.cs:line 645
   at System.IO.Stream.Close()
   at System.IO.Compression.GZipStream.Dispose(Boolean disposing) in /_/src/libraries/System.IO.Compression/src/System/IO/Compression/GZipStream.cs:line 159
   at System.IO.Stream.Close()
   at System.IO.Tests.ConnectedStreamConformanceTests.ReadAsync_ContinuesOnCurrentTaskSchedulerIfDesired(Boolean flowExecutionContext, Nullable`1 continueOnCapturedContext) in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 2079
--- End of stack trace from previous location ---
```

**Comment by adamsitnik** [comment] 2022-02-25 17:39
Duplicate of https://github.com/dotnet/runtime/issues/65476

**Closed by adamsitnik** 2022-02-25 17:39 UTC
Labels: arch-arm64, area-System.IO.Compression, os-linux, JitStress, untriaged
