### ISSUE TITLE
Regression on static initialization using STJ

### ISSUE THREAD

**Issue by sebastienros** [dotnet/runtime#49826] opened 2021-03-18 15:11 UTC
Can be reproduced on the build after these changes:
https://github.com/dotnet/runtime/compare/2d552be28782f3ff7e50c90d272c1b77d5c7db16...7efce05745322d722e3effac4f0859c554ad7ec0

With this code in a static class:

```
private readonly static uint _jsonPayloadSize = (uint)JsonSerializer.SerializeToUtf8Bytes(new JsonMessage { message = "Hello, World!" }, SerializerOptions).Length;
```

The following exception is thrown at runtime:

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'PlatformBenchmarks.BenchmarkApplication' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.Text.Json.JsonSerializerOptions' threw an exception.
 ---> System.InvalidOperationException: Could not execute the method because either the method itself or the containing type is not fully instantiated.
   at System.Text.Json.Serialization.JsonConverter`1.get_TypeToConvert()
   at System.Text.Json.JsonSerializerOptions.GetDefaultSimpleConverters()
   at System.Text.Json.JsonSerializerOptions..cctor()
   --- End of inner exception stack trace ---
   at System.Text.Json.JsonSerializerOptions.GetConverter(Type typeToConvert)
   at System.Text.Json.JsonSerializerOptions.DetermineConverter(Type parentClassType, Type runtimePropertyType, MemberInfo memberInfo)
   at System.Text.Json.JsonClassInfo.GetConverter(Type type, Type parentClassType, MemberInfo memberInfo, Type& runtimeType, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type type)
   at System.Text.Json.JsonSerializerOptions.GetOrAddClassForRootType(Type type)
   at System.Text.Json.WriteStack.Initialize(Type type, JsonSerializerOptions options, Boolean supportContinuation)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, Type inputType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.WriteCoreBytes[TValue](TValue& value, Type inputType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.SerializeToUtf8Bytes[TValue](TValue value, JsonSerializerOptions options)
   at PlatformBenchmarks.BenchmarkApplication..cctor() in /tmp/benchmarks-agent/benchmarks-server-1/2yox3r1x.25e/benchmarks/src/BenchmarksApps/Kestrel/PlatformBenchmarks/BenchmarkApplication.Json.cs:line 12
```

/cc @eerhardt

**Comment by davidfowl** [comment] 2021-03-18 15:12
Marked as blocking because it's currently breaking the benchmarks.

**Comment by eerhardt** [comment] 2021-03-18 15:26
Looking....

**Comment by eerhardt** [comment] 2021-03-18 16:36
I can reproduce the issue locally.

`Could not execute the method because either the method itself or the containing type is not fully instantiated.`

That message comes from:

https://github.com/dotnet/runtime/blob/79ae74f5ca5c8a6fe3a48935e85bd7374959c570/src/coreclr/vm/prestub.cpp#L2086-L2089

When stepping through the code, the exception is coming from:

![image](https://user-images.githubusercontent.com/8291187/111661396-fea96000-87dc-11eb-9cd6-df34b9799cbb.png)

The call right before this goes into the `DateTimeConverter()` constructor. And then when it comes out of the constructor, the next F11 is what throws, i.e. the call to `Add`:

```C#
            void Add(JsonConverter converter) =>
                converters.Add(converter.TypeToConvert, converter);
```

Looking at the exception, the SerializationStackTraceString says:

```
   at System.Text.Json.Serialization.JsonConverter`1.get_TypeToConvert()
   at System.Text.Json.JsonSerializerOptions.GetDefaultSimpleConverters()
```

So it is the call to ``JsonConverter`1.get_TypeToConvert()`` that is throwing, which is:

https://github.com/dotnet/runtime/blob/fa7e11c910337676993f44b9bbf64f45f3040963/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.cs#L477

And for `DateTimeConverter`, `typeof(T)` is `DateTime`.

I tried comparing the IL of `DateTimeConverter`, `JsonConverter<T>`, and `DateTime` using the before and after commits above, and nothing in the IL looks to have changed, but I could have missed something.

@jkotas - any idea clues/leads on when this runtime exception can occur? `Could not execute the method because either the method itself or the containing type is not fully instantiated.` It's odd to me that 4 types that derive from `JsonConverter<T>` were successfully created and added to the dictionary before we hit this DateTime converter. That leads me to believe that the base `JsonConverter<T>` should be fine. But maybe something with `DateTimeConverter`, or `DateTime` is the problem.

**Comment by jkotas** [comment] 2021-03-18 16:38
Does it repro with `COMPlus_ReadyToRun=0` ?

**Comment by eerhardt** [comment] 2021-03-18 16:50
I can't reproduce this with my locally built libraries (that aren't crossgen'd). And when I diff the IL, nothing has changed in this area.

Given those 2 things, my current assumption is this is a crossgen issue. It looks like 2 crossgen changes came in that commit range.

cc @trylek

**Comment by eerhardt** [comment] 2021-03-18 16:51
> Does it repro with COMPlus_ReadyToRun=0 ?

No, I set that env var and the issue goes away.

**Comment by jkotas** [comment] 2021-03-18 16:55
cc @mangod9 Blocking regression from crossgen2 switch

Have we run the libraries tests on crossgen2 compiled libraries?

**Comment by mangod9** [comment] 2021-03-18 16:58
+@trylek and @davidwrighton. Yeah the libraries tests from CI should be running. It appears this is failing only in perf tests?

**Comment by trylek** [comment] 2021-03-18 18:06
Well, I believe we've actually only been running libraries tests on top of Crossgen2 framework on ad hoc basis, in fact the CI infrastructure doesn't currently even support that unless I'm mistaken, the framework CG2 change only affects the installer build, not library test legs. I agree that's something we should improve on but I don't think anything changed in contrast to Crossgen1. One way or another this looks similar to the bug I was fixing in

https://github.com/dotnet/runtime/pull/43054

I'll look into the issue in about an hour once I'm out of meetings.

**Comment by trylek** [comment] 2021-03-18 19:58
@eerhardt - I'm trying to create a regression test in the coreclr subrepo demonstrating this but I have some trouble getting it to actually fail. Could you please advise me in more detail how you're reproing this failure?

**Comment by eerhardt** [comment] 2021-03-18 20:10
Could you please advise me in more detail how you're reproing this failure?

I got this offline from @sebastienros 

```
git clone https://github.com/aspnet/benchmarks
cd benchmarks
git checkout 616aeae700ecac0162c54a6197df09d483aa43bf
cd src\BenchmarksApps\Kestrel\PlatformBenchmarks
// change tfm in PlatformBenchmarks.csproj to net6.0
dotnet run
```

Using the latest runtime

**Closed** 2021-03-19 15:51 UTC
Labels: area-crossgen2-coreclr, blocking, in pr, untriaged

**Comment by mangod9** [comment] 2021-03-19 19:07
@sebastienros please let us know when a successful perf run is complete after picking up this fix.

**Comment by sebastienros** [comment] 2021-03-19 19:18
I confirm the latest build, which includes the fix, fixes all scenarios that were broken. Thanks!

**Comment by sebastienros** [comment] 2021-03-19 19:19
Tested with 6.0.0-preview.3.21169.6+76954b4ed7b5cd48ace16fefb1209fe56779b247

**Comment by mangod9** [comment] 2021-03-19 19:23
Ok nice. Thanks for the update! Please let us know if you hit any other issues. Would be interesting to see if the publish size has increased/decreased with the cg2 compilation of libraries.
