### ISSUE TITLE
TimeZoneInfo.BaseUtcOffset.TotalMinutes is wrong for "Morocco Standard Time". Expected: 60; Actual: 0.

### ISSUE THREAD

**Issue by langgriki** [dotnet/runtime#63164] opened 2021-12-28 10:18 UTC
### Description

If we execute following two lines of code on **Windows** machine:

`TimeZoneInfo moroccoTimezone = TimeZoneInfo.FindSystemTimeZoneById("Morocco Standard Time");`
`Console.WriteLine(moroccoTimezone.BaseUtcOffset.TotalMinutes);`

We will see 0 as an output.
But in fact timezone for "Morocco Standard Time" is 60 minutes. (At least it's display name is (UTC+01:00) Casablanca and according to some resources(Like tzdb) Casablanca is in UTC+01:00 timezone)

### Reproduction Steps

`TimeZoneInfo moroccoTimezone = TimeZoneInfo.FindSystemTimeZoneById("Morocco Standard Time");`
`Console.WriteLine(moroccoTimezone.BaseUtcOffset.TotalMinutes);`

### Expected behavior

I would expect:

- Match of display name and BaseUtcOffset.TotalMinutes result.
- Correlation with tzdb database.

### Actual behavior

- Display name and BaseUtcOffset.TotalMinutes result differs
- BaseUtcOffset.TotalMinutes result does not correlate with tzdb database information.

### Configuration

.NET 6.0.100, Console application. (Actually any application aswell, problem does not stick to console app)

**Comment by filipnavara** [comment] 2021-12-28 11:21
Morocco observes permanent Daylight Savings Time with the exception of Ramadan month. Thus it's base _standard_ offset is really zero.

**Comment by langgriki** [comment] 2021-12-28 11:38
Sorry, but I did not clearly get your proposal (or there was not any ..?). In case of it's base standard offset is zero -> display name should correlate with it, shouldn't it? @filipnavara 

And yeah, sorry for disinformation, it's true that it has zero offset as standard, my bad.

**Comment by filipnavara** [comment] 2021-12-28 12:44
I am just suggesting it may be correct as is. The display name suggests what is the observed time for most of the year, which happens to be a daylight time. The structured information is always standard time with daylight offsets in `AdjustmentRule`s (and occasionally standard offsets if the time zone changed to observe different standard time which is not the case here).

**Comment by tarekgh** [comment] 2021-12-28 23:55
@langgriki 

[TimeZoneInfo.BaseUtcOffset](https://docs.microsoft.com/en-us/dotnet/api/system.timezoneinfo.baseutcoffset?view=net-6.0) is defined as `Gets the time difference between the current time zone's standard time and Coordinated Universal Time (UTC).`. That means it is the UTC offset during the standard time and is not reporting the offset during the daylight saving time. 

```
The government of Morocco announced that effective October 27, 2018 the country would observe daylight saving time year-round. Morocco observes year-round daylight-saving time GMT/UTC+1 except during the month of Ramadan. 
Sunday April 11, 2021, Morocco will temporarily end Daylight Saving Time at 3:00 AM local time.
Sunday May 16, 2021, Morocco will resume Daylight Saving Time at 2:00 AM local time.
```

That means the current time (during December 2021) is a daylight-saving time which would be UTC+1. And that is why the display name is showing UTC+1 as expected.  

So, both the BaseUtcOffset and DisplayName reported correctly.

If you want to get the offset of the current time, you'll need to do something like:

```C#
       TimeZoneInfo zone = TimeZoneInfo.FindSystemTimeZoneById("Morocco Standard Time");
       Console.WriteLine($"UTC Offset Now: {zone.GetUtcOffset(DateTime.Now)}"); // Should print "UTC Offset Now: 01:00:00" for dates during December 2021.
``` 

I am closing the issue but feel free to send any follow up question we may help with. Thanks for your report.

**Closed by tarekgh** 2021-12-28 23:55 UTC
Labels: area-System.Runtime, untriaged

**Comment by langgriki** [comment] 2022-01-10 04:57
Hello, @tarekgh. Sorry for late response, had not work on this issue since your answer. 
I am really confused about how all this stuff works, so asking for your support. 
You've mentioned that display name and reall CURRENT offset of timezone should be the same. In example of Morocco - Base offset is zero, but current is +1 hour. So display name with (UTC+01:00) is right and corresponds with it. 
In case I got your point correctly - it looks like we have several issues: 

1. Microsoft documentation says that display name describes **base** offset to UTC. Link -> https://docs.microsoft.com/en-us/dotnet/api/system.timezoneinfo.displayname?view=net-6.0#system-timezoneinfo-displayname.
2. There are timezones which does not have the same display name and real current offset. In example: 
     - Paraguay Standard Time (Has -04:00 in display name, -03:00 in current offset and -04:00 in base offset)
     - Tasmania Standard Time (Has +10:00 in display name, +11:00 in current offset and +10:00 in base offset)
     - Volgograd Standard Time (Has +04:00 in display name and +03:00 in current offset), but maybe Volgograd is some different case, because it's base utc offset is 03:00 as well, looks strange,  

I'm trying to understand what is actually wrong. In case microsoft documentation is the source of truth - Morocco time zone display name should have UTC time (It will correlate with base offset), but in case display name should be the same as the current timezone offset (which could be changed because of DST) -> there are some problems which I desribed above. 

So what is the actual expected behavior of display name property? 
Does it change with DST switch or should be the same for both variants? 
Maybe the answer to all of my questioins is the same - the actual behavior of display name string.

**Comment by filipnavara** [comment] 2022-01-10 09:36
> Does it change with DST switch or should be the same for both variants?

It does not.

It's simply capturing what is observed for the majority of the year, or standard time, which is largely country specific decision based on local conventions.

The confusion comes from the historical perspective where some countries adopted the DST (daylight savings time) as their new standard time.

The code properties (`BaseUtcOffset` and adjustmemt rules along with `BaseUtcOffsetDelta`) try to capture the true reality which is much more complex than what meets the eye. The standard offset to UTC can change over the years (eg. Russia adjusted time zones at least twice in my life time for Moscow). Daylight offset can be different every year, or it could even be the one that is observed majority of the time (if the county historically observed DST and the decided to switch to it permanently).

The documentation can be improved of course.

**Comment by tarekgh** [comment] 2022-01-11 03:58
@langgriki I misspoke about the display name. Sorry about that and for causing this confusion. I confirmed the documentation is correct and the offset shown in the display name should be the base UTC offset of the zone and not the DST offset.

Going back to the original issue, why the Morocco display name showing `(UTC+01:00)` while the base UTC offset is `00:00`. The reason is .NET pick the display names from Windows (we don't carry the display names). This looks like a bug in Windows. I'll try to contact them about that. Thanks for the report.

**Comment by langgriki** [comment] 2022-01-11 08:16
Thank you for your quick response. But please notice, that Volgograd has the same issue as Morocco has.

**Comment by tarekgh** [comment] 2022-01-11 15:01
On my machine `Microsoft Windows 10.0.22000` I am seeing the Volgograd display name `(UTC+03:00) Volgograd`
