### ISSUE TITLE
Registry-free COM that works with .NET Core 3.1.9 fails in .NET 5 RC2

### ISSUE THREAD

**Issue by gcaughey** [dotnet/runtime#43959] opened 2020-10-28 18:38 UTC
If I target 3.1.5 for the COM server, the client loads it fine. If I target .NET 5 without changing the versions or manifests, the client can no longer load the COM server. There are no errors in the Event Log as you'd expect with side-by-side COM failures. The client just reports failure loading the server.

I don't know if there are any subtle changes I should make to the manifests from .NET Core 3.1.9 since I'm not able to find where this is breaking. I didn't see anything in breaking changes that would apply: https://docs.microsoft.com/en-us/dotnet/core/compatibility/3.1-5.0 

Both .NET Core 3.1.9 and .NET Core 5 desktop runtimes are installed.

**Comment by janvorli** [comment] 2020-11-10 18:27
cc: @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment] 2020-11-10 23:13
@gcaughey This is odd. There have been no changes in our COM support in .NET 5. Can you try this without Registry-free COM to help determine which part of the system may be at fault.

**Comment by gcaughey** [comment] 2020-11-11 14:11
I can build and register the COM server fine, but the client app reports a failure when it tries to access it. (This is with .NET 5.0 from yesterday.)

It’s really just an academic exercise for me at this point since my goal is to completely eliminate the legacy win32 app that is the COM client. I am mostly done replacing it with a .NET 5.0 WPF app (a yearlong project) so I can keep the COM server at .NET Core 3.1.9, which continues to work great using reg-free COM, until I’m completely done.

If there’s anything else you’d like me to try, just let me know. I don’t know if it matters, but the win32 app is x86 so everything is built targeting x86.

Ginny

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by dlucik** [comment] 2020-11-12 17:06
We have similar problem:

https://github.com/xarial/xcad/issues/45

**Comment by gcaughey** [comment] 2020-11-12 17:14
I doubt Regasm is the (only) issue for me since I'm trying to use reg-free COM as well, but the issues could well be related.

**Comment by AaronRobinsonMSFT** [comment] 2020-11-12 17:14
@dlucik The reference issue doesn't seem to be related to RegFree COM. That issue is related to using RegAsm on .NET 5 which isn't the appropriate tooling for .NET COM server registration in .NET Core. The RegAsm tool is exclusively for .NET Framework build binaries.

**Comment by AaronRobinsonMSFT** [comment] 2020-11-12 17:38
I have verified this is a regression in .NET 5 using https://github.com/dotnet/samples/tree/master/core/extensions/COMServerDemo.

/cc @elinor-fung @jkoritzinsky

**Comment by AaronRobinsonMSFT** [comment] 2020-11-12 18:24
Okay. This has been an issue for a while and it appears to not have been fully appreciated - see https://github.com/dotnet/runtime/issues/41309.

The problem is during the merging of manifests in the app host scenario. This is a big regression from .NET 3.1. Basically the supplied application manifest in a project isn't being merged with what is pushed into the app host. The below results are from using the sample at https://github.com/dotnet/samples/tree/master/core/extensions/COMServerDemo.

This is fundamental issue with supplying a custom application manifest and nothing specifically to do with COM. The application manifest is merely an implementation detail of RegFree COM.

Embedded manifest in .NET Core 3.1
```XML
<?xml version="1.0" encoding="utf-8"?>
<!-- https://docs.microsoft.com/windows/desktop/sbscs/assembly-manifests -->
<assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1">
  <assemblyIdentity
    type="win32" 
    name="COMClient"
    version="1.0.0.0" />

  <dependency>
    <dependentAssembly>
      <!-- RegFree COM matching the registration of the generated managed COM server -->
      <assemblyIdentity
          type="win32"
          name="COMServer.X"
          version="1.0.0.0"/>
    </dependentAssembly>
  </dependency>

</assembly>
```

Embedded manifest in .NET 5
```XML
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <assemblyIdentity version="1.0.0.0" name="MyApplication.app"/>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v2">
    <security>
      <requestedPrivileges xmlns="urn:schemas-microsoft-com:asm.v3">
        <requestedExecutionLevel level="asInvoker" uiAccess="false"/>
      </requestedPrivileges>
    </security>
  </trustInfo>
</assembly>
```

**Comment by gcaughey** [comment] 2020-11-12 18:58
Thanks for this. Should I create my own manifest, or would it just be overwritten with the incorrect one?

**Comment by AaronRobinsonMSFT** [comment] 2020-11-12 19:07
@gcaughey The behavior you are observing, that I have reproduced locally (I am on .NET RTM), can't be obviously worked around. @elinor-fung is also looking into this but the scenario works for her using .NET 5 RC2 - she is upgrading presently.

Can you also confirm that if your client is managed that it and the server are both targeting .NET 5?

**Comment by gcaughey** [comment] 2020-11-12 19:11
The client is not managed - it's a legacy win32 app. The server is now on 5.0 RTM.

**Comment by elinor-fung** [comment] 2020-11-12 19:12
Ah, okay. The manifest that @AaronRobinsonMSFT pointed out is for a managed client, so that should not be the issue either.

**Comment by AaronRobinsonMSFT** [comment] 2020-11-12 19:14
@gcaughey Would you mind sharing the manifest being embedded in the native application?

**Comment by gcaughey** [comment] 2020-11-12 19:21
This is the unmanaged client manifest. It is named WasteworksSQL.exe.manifest:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
 <assemblyIdentity version="1.6.6.8" name="WasteworksSQL.exe" type="win32" />
  <dependency>
    <dependentAssembly>
      <assemblyIdentity name="WWCoreHelper.X"
			type="win32"
                        version="1.6.6.7">
      </assemblyIdentity>
    </dependentAssembly>
  </dependency>
</assembly>

And this is the generated managed server manifest, named WWCoreHelper.X.manifest:
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<assembly manifestVersion="1.0" 
xmlns="urn:schemas-microsoft-com:asm.v1">
<assemblyIdentity type="win32" name="WWCoreHelper.X" version="1.6.6.7" />
<file name="WWCoreHelper.comhost.dll">
<comClass clsid="{28eabe34-8b71-40ca-93d1-af5902379248}" 
threadingModel="Both" progid="WWCoreHelper.WWCoreHelperClass" />
</file>
</assembly>

This combination works fine with .NET Core 3.1.9.

**Comment by gcaughey** [comment] 2020-11-12 19:24
Looks like the files didn't make it in the previous comment. Trying again.
[WasteworksSQL.exe.manifest.txt](https://github.com/dotnet/runtime/files/5532793/WasteworksSQL.exe.manifest.txt)
[WWCoreHelper.X.manifest.txt](https://github.com/dotnet/runtime/files/5532802/WWCoreHelper.X.manifest.txt)

I had to rename both files with a .txt extension to paste them.

**Comment by elinor-fung** [comment] 2020-11-12 21:10
Could you try setting some some environment variables to collect some logs:
- `COREHOST_TRACE=1`
- `COREHOST_TRACEFILE=<pathToFile>`

And then run the (failing) scenario?

That should produce a file at `<pathToFile>` with information from the `*.comhost.dll` about how we tried to load the managed COM server. Note that the directory of `<pathToFile>` has to exist (the file does not).

**Comment by gcaughey** [comment] 2020-11-12 21:26
Sorry but I've tried this several times and I'm not getting a trace file generated.

**Comment by elinor-fung** [comment] 2020-11-12 21:31
Hmm, can you check that `WWCoreHelper.comhost.dll` gets loaded at all?

**Comment by gcaughey** [comment] 2020-11-12 22:10
How would I tell?

**Comment by AaronRobinsonMSFT** [comment] 2020-11-12 22:32
@gcaughey For me, the easiest way to verify this would be using [ProcMon](https://docs.microsoft.com/sysinternals/downloads/procmon) to monitor the client process. Typically it could also be done by simply attaching a native debugger to the process to see what is loaded. However, COM will unload the server if it fails to activate an instance. What @elinor-fung is trying to understand is if the failure to activate is because of an issue in creating the managed class that is the COM server, the runtime is failing to activate (indicated by not having logs), or if there is some issue with the SxS manifest.

I am betting on the SxS manifest at this point because from the runtime's point of view Registered vs RegFree COM is the same thing - the server implementation does care on how it is registered with COM. Which means the problem is likely in the registration part, but we want to verifying that first by understanding if  `WWCoreHelper.comhost.dll` is even loaded. If it is loaded then the registration is good, otherwise the problem is with the registration part.

**Comment by elinor-fung** [comment] 2020-11-13 06:44
One more thing to check: what are the file/product versions of `WWCoreHelper.comhost.dll`? We did have a bad bug in comhost in previews of 5.0, so I want to make sure it is not somehow using that version.

The product version should have a commit hash (e.g. `5.0.0 @Commit: cf258a14b70ad9069470a108f13765e0e5988f51`) so that we'll know exactly what it maps to.

**Comment by gcaughey** [comment] 2020-11-13 14:16
Interestingly WWCoreHelper.comhost.dll still shows Product version 5.0.0-rc2 although I just rebuilt it. I'm running the latest version of Visual Studio Preview and additionally directly installed the .NET 5.0.0 release SDK.

**Comment by gcaughey** [comment] 2020-11-13 14:34
I deleted the older files and rebuilt everything. WWCoreHelper.comhost.dll now shows a product version of 5.0.0 - not the rc2 version anymore. But still it doesn't appear to even load. Hope that helps!

**Comment by gcaughey** [comment] 2020-11-13 15:14
I deleted and rebuilt everything and WWCoreHelper.dll now shows product version 5.0.0 without the rc-2.  WWCoreHelper.dll does show Load Image event in Procmon followed by load of coreclr.dll. The product version of coreclr.dll is 5.0.20.47505. Hope that helps!

**Comment by elinor-fung** [comment] 2020-11-14 07:16
Thanks for all the information so far - really appreciate it. Unfortunately, I haven't figured out a local repro. I created a simple managed server with a native client targeting x86 and was able to successfully activate via reg-free COM on .NET 5.0 RTM, so I must have a different configuration for the server/client or a different machine environment setup.

This is what I was able to successfully run: [COMTest.zip](https://github.com/dotnet/runtime/files/5540327/COMTest.zip)

> followed by load of coreclr.dll

I'm pretty confused by the `COREHOST_TRACE` logs not working then, since the tracing is all around locating/loading the runtime. But it looks like that is not the point of failure / we must be successfully doing that if we're getting to the point of loading `coreclr.dll`.

A couple more requests:

1. What is the error/HRESULT returned when your native client tries to activate the COM server?
2. Could you share the .runtimeconfig.json for the COM server (should be `WWCoreHelper.runtimeconfig.json`, right next to the dlls)?
    - The 5.0.20.47505 version for `coreclr.dll` would be RC2, not RTM, so I'm wondering if the config is pointing at RC2 for some reason.
3. Clarification about the images you saw loaded through ProcMon: did you see your managed library loaded as well? i.e was it `WWCoreHelper.comhost.dll`, `coreclr.dll`, __and__ `WWCoreHelper.dll` (your managed library, non-comhost)?
    - I would expect the (succesful) sequence to be something like:
    ```
    […]\WWCoreHelper.comhost.dll
    C:\Program Files (x86)\dotnet\host\fxr\5.0.0\hostfxr.dll
    C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App\5.0.0\hostpolicy.dll
    C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App\5.0.0\coreclr.dll
    C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App\5.0.0\System.Private.CoreLib.dll
    C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App\5.0.0\clrjit.dll
    […]\WWCoreHelper.dll
    ```
4. Can you share the output of `dotnet --info`? I'm specifically interested in the x86 one, since that is what your scenario is targeting - depending on what you have installed, that may not be the first one on your path, so you might need to run it directly (default location is `C:\Program Files (x86)\dotnet`)

Thanks again for fielding all our questions as we try to understand what is going wrong here.

**Comment by gcaughey** [comment] 2020-11-15 20:30
Here's dotnet --info results:

C:\Users\gcaug>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.20257
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.1.109 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.302 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

It doesn't show x86, so I ran the x86 SDK installer again but got the same result from dotnet --info.

I looked at Program Files (x86) and both .NET 5.0 rc-2 and .NET 5.0 are there.

My WWCoreHelp.dll is not loaded after the coreclr.dll.

WWCoreHelper.runtimeconfig.json looks like this:

{
  "runtimeOptions": {
    "tfm": "net5.0",
    "rollForward": "LatestMinor",
    "framework": {
      "name": "Microsoft.WindowsDesktop.App",
      "version": "5.0.0"
    }
  }
}

I don't know why Visual Studio is using the older version of coreclr.dll when I build WWCoreHelper.dll, but I was surprised that .NET 5.0 rc-2 wasn't uninstalled when .NET 5.0.0 release version was installed.

**Comment by elinor-fung** [comment] 2020-11-16 20:16
I think you'll have to directly run the x86 dotnet - `C:\Program Files (x86)\dotnet\dotnet.exe --info` - to show the x86 information.

Would you be willing to collect/share a [time travel trace](https://devblogs.microsoft.com/dotnet/debugging-net-apps-with-time-travel-debugging-ttd/) of the failed activation?

**Comment by gcaughey** [comment] 2020-11-16 20:40
Here's the output from dotnet --info

C:\Program Files (x86)\dotnet>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.20257
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.1.109 [C:\Program Files (x86)\dotnet\sdk]
  5.0.100 [C:\Program Files (x86)\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.0-preview2.19528.8 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.0-preview2.19525.6 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview2.19525.6 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.2.20475.6 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

I manually deleted the RC-2 runtime, but the behavior of the app doesn't change.

Since any time I spend trying to debug this broken scenario just takes away from the time I could be spending getting off the legacy unmanaged code altogether, I'm not eager to take on anything else that isn't likely to be helpful. Until I can get off this reg-free COM issue, I can continue to target .NET Core 3.1.9, which works perfectly with not code or manifest changes.

**Comment by elinor-fung** [comment] 2020-11-16 21:00
Definitely understood - thanks again for all the effort you have put into helping us try to find the issue.

**Comment by AndrewMD5** [comment] 2020-12-25 05:18
This might also be related to #41309.

In order to build registration free COM application and avoid runtime registration we had to:
    1. turn DLL isolation ON, build
    2. open target folder and extract XML text from .manifest output, which belongs to the DLL file
    3. turn DLL isolation back OFF
    4. edit application manifest file and merge extracted XML
    5. build (including single file host) application

**Comment by AaronRobinsonMSFT** [comment] 2021-08-13 17:19
@gcaughey I am going to close this for now as we've not had any other reports of the issue and we are close to shipping .NET 6. Please do let us know if this behavior is observed in future releases.

**Closed by AaronRobinsonMSFT** 2021-08-13 17:19 UTC
Labels: area-Interop-coreclr, regression-from-last-release
