### ISSUE TITLE
Strange behavior, Encoding.UTF8.GetString has different results in dotnet core and dotnet framewrok.

### ISSUE THREAD

**Issue by li-zhixin** [dotnet/runtime#51204] opened 2020-11-26 13:12 UTC
```c#
var bytes = new List<byte>()
{
     170,
     224,
     146,
     82,
     213,
     34,
     33,
     102,
     246,
     66,
     208,
     221,
     138,
     170,
     2,
     135,
     70,
     191,
     58,
     194,
     2
};
Console.WriteLine(Encoding.UTF8.GetString(bytes.ToArray()));
```

|        |                             |                          |
|--------|-----------------------------|--------------------------|
|        | dotnet franework\(4\.7\.2\) | dotnet core\(3\.1\.403\) |
| result | ��R�\\"\!f�B�݊��F�:�      | ���R�\\"\!f�B�݊��F�:�  |

You can see that the two results begin with a difference of one � and what should I do if I want to eliminate the difference?  If this is not possible, can you tell me what is causing the difference?

**Comment by ufcpp** [comment] 2021-04-14 01:59
https://github.com/dotnet/runtime/issues/29017#issuecomment-475110887

**Comment by tarekgh** [comment] 2021-04-14 16:11
@GrabYourPitchforks, I think this was the intentional change we did in .NET Core.

**Comment by GrabYourPitchforks** [comment] 2021-04-14 16:21
Duplicate of https://github.com/dotnet/standard/issues/1679. See also https://docs.microsoft.com/en-us/dotnet/core/compatibility/corefx#replacing-ill-formed-utf-8-byte-sequences-follows-unicode-guidelines.

**Comment by eiriktsarpalis** [comment] 2021-04-15 11:49
Closing as duplicate of dotnet/standard#1679.

**Closed by eiriktsarpalis** 2021-04-15 11:49 UTC
Labels: area-System.Text.Encoding, untriaged
