### ISSUE TITLE
Make Utf8JsonWriter.WriteNumberValue(ReadOnlySpan<byte>) public

### ISSUE THREAD

**Issue by ghord** [dotnet/runtime#30194] opened 2019-07-09 07:52 UTC
I have a use case where I want to copy exising `ReadOnlySpan<byte>` directly to `Utf8JsonWriter` as a number (it comes from `Utf8JsonReader.ValueSpan`). I don't want to deal with converting the value to some arbitrary number representation and then back.
Since there already is an internal api for writing raw bytes as a number it would be ideal for my use case. Can we make `Utf8JsonWriter.WriteNumberValue` and `Utf8JsonWriter.WriteNumber` overloads that take `ReadOnlySpan<byte>` parameter public instead of internal?

**Comment by olivier-spinelli** [comment] 2021-06-10 15:48
Same here, except that I also need the corresponding read methods. I'm working on a Json serialization using Code Generation: I'm using Utf8JsonReader/Writer directly (not the JsonSerializer level). My goal is (very) simple: I just want to correctly handle "big integers" (without data loss).

JSON format defines no limitation on numeric values. 64 bits integer and [BigInteger](https://docs.microsoft.com/en-us/dotnet/api/system.numerics.biginteger) can be write and read without loss in JSON.

- Unfortunately (n°1), ECMAScript only handles [64 bits floats](https://en.wikipedia.org/wiki/Double-precision_floating-point_format): 64 bits integer (and larger) cannot be write and read back safely. Only integer values between [Number.MIN_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MIN_SAFE_INTEGER) and [Number.MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER) (53 bits) are safe on the ECMAScript side.
Among the basic types, the long (Int64), ulong (UInt64) and Decimal representations are not ECMAScript compliant. They must use a string representation, just like [JsonNumberHandling.WriteAsString](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonnumberhandling) specifies it.
- Unfortunately (n°2), this option is NOT available on the Utf8JsonWriter API. It is reserved for the "Serialization" layer.
- Unfortunately (n°3), the APIs to [write (WriteNumberValueAsString(ulong))](https://source.dot.net/#System.Text.Json/System/Text/Json/Writer/Utf8JsonWriter.WriteValues.UnsignedNumber.cs,112) or [read (GetUInt64WithQuotes)](https://source.dot.net/#System.Text.Json/System/Text/Json/Reader/Utf8JsonReader.TryGet.cs,383) quoted long or unsigned long (same for Decimal) are not publicly exposed on the Utf8Writer/Reader.

I won't duplicate the whole Utf8JsonReader/Writer code nor use reflection. it seems that my only way to do it is to implement this "externally" (by awful calls to Parse/ToString)...

**Comment by layomia** [comment] 2021-06-10 16:42
@olivier-spinelli I consider this issue a duplicate of https://github.com/dotnet/runtime/issues/1784 since that issue satisfies the requirement here. I'll close this issue. Please feel free to open a new issue to address your `Read` requirements. Thanks!

**Closed by layomia** 2021-06-10 16:42 UTC
Labels: area-System.Text.Json
