### ISSUE TITLE
Blazor WASM application migration from dotNet7 to dotNet8

### ISSUE THREAD

**Issue by cesare-marasco** [dotnet/runtime#94806] opened 2023-11-15 20:28 UTC
Hi All,
@steveisok @SamMonoRT

Yesterday i migrated my Blazor Wasm Application (That consume a BE Api using JWT Auth) from dotNet7 to dotNet8 following the Microsoft official guide.

https://learn.microsoft.com/en-us/aspnet/core/migration/70-80?view=aspnetcore-8.0&tabs=visual-studio#update-the-net-sdk-version-in-globaljson

and using the suggested steps:

Update a Blazor WebAssembly app

Follow the guidance in the first three sections of this article:

1- [Update the .NET SDK version in global.json](https://learn.microsoft.com/en-us/aspnet/core/migration/70-80?view=aspnetcore-8.0&tabs=visual-studio#update-the-net-sdk-version-in-globaljson)
2 - [Update the target framework](https://learn.microsoft.com/en-us/aspnet/core/migration/70-80?view=aspnetcore-8.0&tabs=visual-studio#update-the-target-framework)
3 - [Update package references](https://learn.microsoft.com/en-us/aspnet/core/migration/70-80?view=aspnetcore-8.0&tabs=visual-studio#update-package-references)

The migrated application works perfectly locally with visual studio in debug mode. Publish and deploy goes well. The application start correctly but when i try to log in using BE api I receive following error

` Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: ConstructorContainsNullParameterNames, System.Collections.Generic.KeyValuePair`2[System.Int32,System.String]
System.NotSupportedException: ConstructorContainsNullParameterNames, System.Collections.Generic.KeyValuePair`2[System.Int32,System.String]
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_ConstructorContainsNullParameterNames(Type )
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.PopulateParameterInfoValues(JsonTypeInfo )
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.CreateTypeInfoCore(Type , JsonConverter , JsonSerializerOptions )
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.CreateJsonTypeInfo(Type , JsonSerializerOptions )
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.GetTypeInfo(Type , JsonSerializerOptions )
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoNoCaching(Type )
   at System.Text.Json.JsonSerializerOptions.CachingContext.CreateCacheEntry(Type type, CachingContext context)
--- End of stack trace from previous location ---
   at System.Text.Json.JsonSerializerOptions.CachingContext.CacheEntry.GetResult()
   at System.Text.Json.JsonSerializerOptions.CachingContext.GetOrAddTypeInfo(Type , Boolean )
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type , Boolean , Nullable`1 , Boolean , Boolean )
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureSynchronized|172_0()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.EnsureConfigured()
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type , Boolean , Nullable`1 , Boolean , Boolean )
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo.Configure()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.ConfigureProperties()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureSynchronized|172_0()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.EnsureConfigured()
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type , Boolean , Nullable`1 , Boolean , Boolean )
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo.Configure()`

This error occur for any kind of compilation

RunAOTCompilation -> True or False

Previously my application was published using AOT compilation enabled, working perfectly.

The application is built  and deployed using a CI/CD Azure DevOps Pipeline that produce a docker image for Azure Container Registry and deployed as Azure Container Instance. 

This is a frustrating and blocking problem. I hope to receive support ASAP.

I put some configs:

Blazor Wasm Project
`<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
		<ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
		<AssemblyName>XXXX</AssemblyName>
		<RootNamespace>XXXX</RootNamespace>
		<RunAOTCompilation>true</RunAOTCompilation>
	</PropertyGroup>.....`

Thanks in advance

**Comment by GerardSmit** [comment] 2023-11-15 20:44
This looks like a System.Text.Json + Trimming issue. Since I don't know the code in step:

> The application start correctly but when i try to log in using BE api I receive following error

I assume that you're doing a HTTP request and deserializing the JSON response. When using trimming, you should use a source generated JSON Context, docs can be found here: https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation

**Comment by eiriktsarpalis** [comment] 2023-11-15 20:55
Duplicate of https://github.com/dotnet/runtime/issues/74141 and https://github.com/dotnet/runtime/issues/81709. Using the source generator is advised when using trimmed applications. You could always try to work around the specific issue using the `DynamicDependencyAttribtue`  (example: https://github.com/passwordless-lib/fido2-net-lib/commit/1fbfb25cb9f53a8795ab952698dcc6493df1add3) but it's likely you'll face other reliability issues.

**Comment by cesare-marasco** [comment] 2023-11-15 20:55
But,
Why the same code works with perfectly using the previous dotNet7 ? The code is exactly the same .. to be honest everything it's as previous .. was change only SDK in the project, in the docker file of the CI pipeline..that's all... I assume that something it's changed in the json deser/ser process

**Closed by eiriktsarpalis** 2023-11-15 20:55 UTC
Labels: arch-wasm, area-System.Text.Json, untriaged

**Comment by GerardSmit** [comment] 2023-11-15 20:59
I assume because the default TrimMode has been changed in .NET 8.
This is documented here: https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/8.0/trimmode-full

**Comment by eiriktsarpalis** [comment] 2023-11-15 21:03
Correct, it's not the serializer per se that has changed here, rather serialization is failing because the trimmer has removed essential information from the IL required to drive reflection-based serialization.
