### ISSUE TITLE
Weird issue with stale File.GetCreationTimeUtc (Windows only)

### ISSUE THREAD

**Issue by Zastai** [dotnet/runtime#70830] opened 2022-06-16 15:04 UTC
### Description

Creating a new file after a file with the same name has been recently deleted or moved results in a file with the old file's creation time (at least, as reported by `File.GetCreationTimeUtc`).

Seeing this on Windows, but _not_ with the same SDK/Runtime versions under WSL on the same machine.

### Reproduction Steps

Given the following console program's `Program.cs`:

```cs
Console.WriteLine("Framework                              : {0}", RuntimeInformation.FrameworkDescription);
Console.WriteLine("Current Time                           : {0:u}", DateTimeOffset.UtcNow);
const string File1 = "foo.txt";
const string File2 = "bar.txt";
Console.WriteLine("Creation Time of {0} At Start      : {1:u}", File1, File.GetCreationTimeUtc(File1));
Console.WriteLine("Creation Time of {0} At Start      : {1:u}", File2, File.GetCreationTimeUtc(File2));
if (File.Exists(File1)) {
  File.Delete(File1);
}
Console.WriteLine("Creation Time of {0} After Deletion: {1:u}", File1, File.GetCreationTimeUtc(File1));
if (File.Exists(File2)) {
  File.Delete(File2);
}
Console.WriteLine("Creation Time of {0} After Deletion: {1:u}", File2, File.GetCreationTimeUtc(File2));
File.CreateText(File1).Close();
Console.WriteLine("Creation Time of {0} After Creation: {1:u}", File1, File.GetCreationTimeUtc(File1));
File.Move(File1, File2);
Console.WriteLine("Creation Time of {0} After Move    : {1:u}", File1, File.GetCreationTimeUtc(File1));
Console.WriteLine("Creation Time of {0} After Move    : {1:u}", File2, File.GetCreationTimeUtc(File2));
File.CreateText(File1).Close();
Console.WriteLine("Creation Time of {0} After Creation: {1:u}", File1, File.GetCreationTimeUtc(File1));

File.Delete(File1);
File.Delete(File2);
```

then on Windows, running this a few times in succession shows the exact same creation time for foo.txt (that of the first run in the sequence).

For example:

```
> rm -r bin, obj; dotnet run -f:netcoreapp3.1 -c:Release
Framework                              : .NET Core 3.1.26
Current Time                           : 2022-06-16 14:49:43Z
Creation Time of foo.txt At Start      : 1601-01-01 00:00:00Z
Creation Time of bar.txt At Start      : 1601-01-01 00:00:00Z
Creation Time of foo.txt After Deletion: 1601-01-01 00:00:00Z
Creation Time of bar.txt After Deletion: 1601-01-01 00:00:00Z
Creation Time of foo.txt After Creation: 2022-06-16 14:49:43Z
Creation Time of foo.txt After Move    : 1601-01-01 00:00:00Z
Creation Time of bar.txt After Move    : 2022-06-16 14:49:43Z
Creation Time of foo.txt After Creation: 2022-06-16 14:49:43Z
> rm -r bin, obj; dotnet run -f:netcoreapp3.1 -c:Release
Framework                              : .NET Core 3.1.26
Current Time                           : 2022-06-16 14:49:48Z
Creation Time of foo.txt At Start      : 1601-01-01 00:00:00Z
Creation Time of bar.txt At Start      : 1601-01-01 00:00:00Z
Creation Time of foo.txt After Deletion: 1601-01-01 00:00:00Z
Creation Time of bar.txt After Deletion: 1601-01-01 00:00:00Z
Creation Time of foo.txt After Creation: 2022-06-16 14:49:43Z
Creation Time of foo.txt After Move    : 1601-01-01 00:00:00Z
Creation Time of bar.txt After Move    : 2022-06-16 14:49:43Z
Creation Time of foo.txt After Creation: 2022-06-16 14:49:43Z
> rm -r bin, obj; dotnet run -f:net5.0 -c:Release
Framework                              : .NET 5.0.17
Current Time                           : 2022-06-16 14:49:54Z
Creation Time of foo.txt At Start      : 1601-01-01 00:00:00Z
Creation Time of bar.txt At Start      : 1601-01-01 00:00:00Z
Creation Time of foo.txt After Deletion: 1601-01-01 00:00:00Z
Creation Time of bar.txt After Deletion: 1601-01-01 00:00:00Z
Creation Time of foo.txt After Creation: 2022-06-16 14:49:43Z
Creation Time of foo.txt After Move    : 1601-01-01 00:00:00Z
Creation Time of bar.txt After Move    : 2022-06-16 14:49:43Z
Creation Time of foo.txt After Creation: 2022-06-16 14:49:43Z
> rm -r bin, obj; dotnet run -f:net5.0 -c:Release
Framework                              : .NET 5.0.17
Current Time                           : 2022-06-16 14:49:57Z
Creation Time of foo.txt At Start      : 1601-01-01 00:00:00Z
Creation Time of bar.txt At Start      : 1601-01-01 00:00:00Z
Creation Time of foo.txt After Deletion: 1601-01-01 00:00:00Z
Creation Time of bar.txt After Deletion: 1601-01-01 00:00:00Z
Creation Time of foo.txt After Creation: 2022-06-16 14:49:43Z
Creation Time of foo.txt After Move    : 1601-01-01 00:00:00Z
Creation Time of bar.txt After Move    : 2022-06-16 14:49:43Z
Creation Time of foo.txt After Creation: 2022-06-16 14:49:43Z
> rm -r bin, obj; dotnet run -f:net6.0 -c:Release
Framework                              : .NET 6.0.6
Current Time                           : 2022-06-16 14:50:00Z
Creation Time of foo.txt At Start      : 1601-01-01 00:00:00Z
Creation Time of bar.txt At Start      : 1601-01-01 00:00:00Z
Creation Time of foo.txt After Deletion: 1601-01-01 00:00:00Z
Creation Time of bar.txt After Deletion: 1601-01-01 00:00:00Z
Creation Time of foo.txt After Creation: 2022-06-16 14:49:43Z
Creation Time of foo.txt After Move    : 1601-01-01 00:00:00Z
Creation Time of bar.txt After Move    : 2022-06-16 14:49:43Z
Creation Time of foo.txt After Creation: 2022-06-16 14:49:43Z
> rm -r bin, obj; dotnet run -f:net6.0 -c:Release
Framework                              : .NET 6.0.6
Current Time                           : 2022-06-16 14:50:03Z
Creation Time of foo.txt At Start      : 1601-01-01 00:00:00Z
Creation Time of bar.txt At Start      : 1601-01-01 00:00:00Z
Creation Time of foo.txt After Deletion: 1601-01-01 00:00:00Z
Creation Time of bar.txt After Deletion: 1601-01-01 00:00:00Z
Creation Time of foo.txt After Creation: 2022-06-16 14:49:43Z
Creation Time of foo.txt After Move    : 1601-01-01 00:00:00Z
Creation Time of bar.txt After Move    : 2022-06-16 14:49:43Z
Creation Time of foo.txt After Creation: 2022-06-16 14:49:43Z
```

If I wait a bit between runs, it does reset, so there seems to be some time-based caching going in.

### Expected behavior

Calling `File.GetCreationTimeUtc()` on a newly-created file returns the date/time at which the file was created, even when an older file previously existed.

### Actual behavior

An older creation time is returned when the file was recently recreated.

This completely breaks log rotation, for example - an old log file is detected, it gets moved out of the way, and a new log file is created. But then that new log file is detected as "old" again, and gets rotated again, etc.

### Regression?

I doubt it; issue occurs with the 3.1.26, 5.0.17 and 6.0.6 runtimes.
It seems to be OS/Hardware dependent. I get the issue on my personal laptop (with an M.2 SSD, which may or may not factor into it), but not on my work laptop when I place the self-contained published app there.

### Known Workarounds

None

### Configuration

Issue machine, Windows:
```
.NET SDK (reflecting any global.json):
 Version:   6.0.301
 Commit:    43f9b18481

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.301\

Host (useful for support):
  Version: 6.0.6
  Commit:  7cca709db2

.NET SDKs installed:
  3.1.420 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.301 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

Issue machine, WSL:
```
.NET SDK (reflecting any global.json):
 Version:   6.0.301
 Commit:    43f9b18481

Runtime Environment:
 OS Name:     debian
 OS Version:  11
 OS Platform: Linux
 RID:         debian.11-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.301/

Host (useful for support):
  Version: 6.0.6
  Commit:  7cca709db2

.NET SDKs installed:
  6.0.301 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by rhuijben** [comment] 2022-06-16 15:59
There is some support in Windows itself, that might cause what you are seeing, so I'm not sure this is really a DotNet issue.

**Comment by Zastai** [comment] 2022-06-16 19:56
Mainly wondering whether there might be any flags the runtime might be able to pass to the windows API to ask not to cache or something.

**Comment by HJLeee** [comment] 2022-06-16 22:47
Calling File.SetCreationTimeUtc() right after file creation might be helpful for defensive code.

**Comment by Zastai** [comment] 2022-06-17 08:53
That only seems to partially help; I added such a call after the initial creation, but before the rename:

```
Framework                              : .NET 6.0.6
Current Time                           : 2022-06-17 08:43:49Z
Creation Time of foo.txt At Start      : 1601-01-01 00:00:00Z
Creation Time of bar.txt At Start      : 1601-01-01 00:00:00Z
Creation Time of foo.txt After Deletion: 1601-01-01 00:00:00Z
Creation Time of bar.txt After Deletion: 1601-01-01 00:00:00Z
Creation Time of foo.txt After Creation: 2022-06-17 08:43:45Z
Creation Time of foo.txt After SetTime : 2022-06-17 08:43:49Z
Creation Time of foo.txt After Move    : 1601-01-01 00:00:00Z
Creation Time of bar.txt After Move    : 2022-06-17 08:43:45Z
Creation Time of foo.txt After Creation: 2022-06-17 08:43:49Z
```

So now foo.txt indeed has the right time at the end, but when it gets renamed to bar.txt, that ends up with the old timestamp from before the create+set-time. This just feels extremely buggy to me.

I do see that `File.CreationTime`'s [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.io.filesysteminfo.creationtime) mentions "NTFS-formatted drives may cache file meta-info, such as file creation time, for a short period of time. This process is known as file tunneling. As a result, it may be necessary to explicitly set the creation time of a file if you are overwriting or replacing an existing file." - so I guess it's documented, although that doesn't really explain why I don't have the same issue on every Windows machine (which all use NTFS).

**Comment by Zastai** [comment] 2022-06-17 09:03
One assumes that these days, non-LFN aware software is no longer a real concern. Would it then be safe to disable file tunneling?

**Comment by adamsitnik** [comment] 2022-06-20 17:30
Hi @Zastai 

> Mainly wondering whether there might be any flags the runtime might be able to pass to the windows API to ask not to cache or something.

The sys-call that is being used is `GetFileAttributesEx`:

https://github.com/dotnet/runtime/blob/df53937aaac84a73253ac8a9dbf49803ee7e95a1/src/libraries/System.Private.CoreLib/src/System/IO/File.cs#L190-L191

https://github.com/dotnet/runtime/blob/df53937aaac84a73253ac8a9dbf49803ee7e95a1/src/libraries/System.Private.CoreLib/src/System/IO/FileSystem.Windows.cs#L120-L123

https://github.com/dotnet/runtime/blob/df53937aaac84a73253ac8a9dbf49803ee7e95a1/src/libraries/Common/src/System/IO/FileSystem.Attributes.Windows.cs#L59

I have checked the [docs](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfileattributesexw) and it does not expose a possibility to bypass the cache. So I am afraid that we don't have an alternative and this is by design.

cc @JeremyKuhne who might know more about it.

**Comment by JeremyKuhne** [comment] 2022-06-20 20:03
On the Windows side, you might be seeing differences based on whether or not 8.3 file names are turned on for the volume where you are testing. By default they are for the boot drive, but not for any others (afaik). You can check by running `fsutil 8dot3name query C:` from an admin prompt.

I don't know if it matters, but the way deleted files are handled changed in Windows 10 about 2 years ago, if you see a pattern based on Windows versions.

You might want to try to change the tunneling defaults. See the following two links for more details.

https://devblogs.microsoft.com/oldnewthing/20050715-14/?p=34923
https://web.archive.org/web/20050206140653/http://support.microsoft.com/?kbid=172190

**Comment by adamsitnik** [comment] 2022-06-22 09:14
@JeremyKuhne thanks for providing more information! Since we can't do anything from .NET level about it, I am going to close the issue.

**Closed by adamsitnik** 2022-06-22 09:14 UTC
Labels: area-System.IO
