### ISSUE TITLE
Test failure JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#93164] opened 2023-10-07 06:05 UTC
**Failed in:** [runtime-coreclr jitstress2-jitstressregs 20231001.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=424100&view=ms.vss-test-web.build-test-results-tab&runId=9323882&resultId=101436&paneView=debug)

**Failed tests:**
```
coreclr linux x64 Checked jitstress2_jitstressregs4 @ Ubuntu.2204.Amd64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr windows arm64 Checked jitstress2_jitstressregs1 @ Windows.11.Arm64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr linux arm64 Checked jitstress2_jitstressregs0x2000 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr linux arm64 Checked jitstress2_jitstressregs8 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr windows arm64 Checked jitstress2_jitstressregs0x80 @ Windows.11.Arm64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr linux x64 Checked jitstress2_jitstressregs0x1000 @ Ubuntu.2204.Amd64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr windows arm64 Checked jitstress2_jitstressregs8 @ Windows.11.Arm64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr windows arm64 Checked jitstress2_jitstressregs0x2000 @ Windows.11.Arm64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr linux arm64 Checked jitstress2_jitstressregs0x80 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr windows arm64 Checked jitstress2_jitstressregs4 @ Windows.11.Arm64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr linux arm64 Checked jitstress2_jitstressregs0x1000 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr linux arm64 Checked jitstress2_jitstressregs0x10 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr linux arm64 Checked jitstress2_jitstressregs4 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr osx arm64 Checked jitstress2_jitstressregs8 @ OSX.1200.ARM64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr linux x64 Checked jitstress2_jitstressregs1 @ Ubuntu.2204.Amd64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr linux x64 Checked jitstress2_jitstressregs8 @ Ubuntu.2204.Amd64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr osx x64 Checked jitstress2_jitstressregs8 @ OSX.1200.Amd64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr osx x64 Checked jitstress2_jitstressregs0x80 @ OSX.1200.Amd64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr linux arm64 Checked jitstress2_jitstressregs1 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr linux x64 Checked jitstress2_jitstressregs0x2000 @ Ubuntu.2204.Amd64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr linux arm64 Checked jitstress2_jitstressregs3 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr windows x64 Checked jitstress2_jitstressregs1 @ Windows.10.Amd64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr linux arm64 Checked jitstress2_jitstressregs2 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr windows x64 Checked jitstress2_jitstressregs0x80 @ Windows.10.Amd64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr windows x64 Checked jitstress2_jitstressregs4 @ Windows.10.Amd64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr osx x64 Checked jitstress2_jitstressregs4 @ OSX.1200.Amd64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr windows x64 Checked jitstress2_jitstressregs0x10 @ Windows.10.Amd64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr windows x64 Checked jitstress2_jitstressregs3 @ Windows.10.Amd64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr linux x64 Checked jitstress2_jitstressregs3 @ Ubuntu.2204.Amd64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr linux x64 Checked jitstress2_jitstressregs2 @ Ubuntu.2204.Amd64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr osx arm64 Checked jitstress2_jitstressregs0x1000 @ OSX.1200.ARM64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr windows x64 Checked jitstress2_jitstressregs2 @ Windows.10.Amd64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr osx x64 Checked jitstress2_jitstressregs2 @ OSX.1200.Amd64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr osx x64 Checked jitstress2_jitstressregs0x2000 @ OSX.1200.Amd64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr linux x64 Checked jitstress2_jitstressregs0x10 @ Ubuntu.2204.Amd64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr osx arm64 Checked jitstress2_jitstressregs1 @ OSX.1200.ARM64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr linux x64 Checked jitstress2_jitstressregs0x80 @ Ubuntu.2204.Amd64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr windows x64 Checked jitstress2_jitstressregs0x2000 @ Windows.10.Amd64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr osx arm64 Checked jitstress2_jitstressregs3 @ OSX.1200.ARM64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr windows x64 Checked jitstress2_jitstressregs0x1000 @ Windows.10.Amd64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr osx x64 Checked jitstress2_jitstressregs0x10 @ OSX.1200.Amd64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr osx arm64 Checked jitstress2_jitstressregs4 @ OSX.1200.ARM64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr windows arm64 Checked jitstress2_jitstressregs2 @ Windows.11.Arm64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr osx x64 Checked jitstress2_jitstressregs0x1000 @ OSX.1200.Amd64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr osx x64 Checked jitstress2_jitstressregs3 @ OSX.1200.Amd64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr osx x64 Checked jitstress2_jitstressregs1 @ OSX.1200.Amd64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr osx arm64 Checked jitstress2_jitstressregs0x10 @ OSX.1200.ARM64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr windows x64 Checked jitstress2_jitstressregs8 @ Windows.10.Amd64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr windows arm64 Checked jitstress2_jitstressregs0x10 @ Windows.11.Arm64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr osx arm64 Checked jitstress2_jitstressregs2 @ OSX.1200.ARM64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr osx arm64 Checked jitstress2_jitstressregs0x2000 @ OSX.1200.ARM64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr windows arm64 Checked jitstress2_jitstressregs3 @ Windows.11.Arm64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr windows arm64 Checked jitstress2_jitstressregs0x1000 @ Windows.11.Arm64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr osx arm64 Checked jitstress2_jitstressregs0x80 @ OSX.1200.ARM64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
```

**Error message:**
```
 
Return code:      1
Raw output file:      /datadisks/disk1/work/A8DE092E/w/9C8B08CD/uploads/JitBlue/DevDiv_461649/DevDiv_461649/output.txt
Raw output:
BEGIN EXECUTION
/datadisks/disk1/work/A8DE092E/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true DevDiv_461649.dll ''
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Uri.get_IriParsing() in /_/src/libraries/System.Private.Uri/src/System/Uri.cs:line 270
   at System.Uri.InitializeUri(ParsingError err, UriKind uriKind, UriFormatException& e) in /_/src/libraries/System.Private.Uri/src/System/UriExt.cs:line 90
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions) in /_/src/libraries/System.Private.Uri/src/System/UriExt.cs:line 38
   at System.Uri..ctor(String uriString, UriKind uriKind) in /_/src/libraries/System.Private.Uri/src/System/Uri.cs:line 416
   at System.Xml.XmlResolver.ResolveUri(Uri baseUri, String relativeUri) in /_/src/libraries/System.Private.Xml/src/System/Xml/XmlResolver.cs:line 45
   at System.Xml.XmlUrlResolver.ResolveUri(Uri baseUri, String relativeUri) in /_/src/libraries/System.Private.Xml/src/System/Xml/XmlUrlResolver.cs:line 61
   at System.Xml.Xsl.Xslt.XsltLoader.Load(Compiler compiler, Object stylesheet, XmlResolver xmlResolver, XmlResolver origResolver) in /_/src/libraries/System.Private.Xml/src/System/Xml/Xsl/Xslt/XsltLoader.cs:line 75
   at XSLTest.Program.TestEntryPoint()
   at __GeneratedMainWrapper.Main()
Expected: 100
Actual: 101
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 10/1/2023 6:49:56 PM
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> /datadisks/disk1/work/A8DE092E/w/9C8B08CD/e/JIT/Regression/Regression_3/../JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.sh
Expected: True
Actual:   False
```
**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/xunit.assert/Asserts/BooleanAsserts.cs:line 132
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor331|0_332(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by jakobbotsch** [comment] 2023-10-07 07:40
Duplicate of #92990

**Closed by jakobbotsch** 2023-10-07 07:40 UTC
Labels: arch-arm64, os-linux, os-mac-os-x, os-windows, JitStress, arch-x64, area-CodeGen-coreclr, untriaged
