### ISSUE TITLE
conv.i4 with NaN returns 0 on macOS M1 

### ISSUE THREAD

**Issue by aoli-al** [dotnet/runtime#86980] opened 2023-05-31 22:01 UTC
### Description

conv.i4 with NaN as input returns 0 on macOS M1

### Reproduction Steps

Run the following code on macOS M1

```
Console.WriteLine($"{(int) Math.Log(-1)}")
```

### Expected behavior

On an X86 machine it prints -2147483648 

### Actual behavior

Prints 0

### Other information

I understand casting NaN to integer is unspecified behaviour. However, I'm wondering if the runtime should produce the same output on different architectures.

**Comment by tannergooding** [comment] 2023-06-01 00:14
This is a complex issue because it can't be done without harming performance on one of the two target platforms.

There is an approved, but NYI, issue covering us fixing this and making it deterministic; but it hasn't bubbled up yet due to the complexity and all the areas that need to be fixed/tested first. Not to mention that it will likely cause some regressions and behavioral breaks for some users who are depending (even unknowingly) on the current behavior.

**Comment by tannergooding** [comment] 2023-06-01 00:15
https://github.com/dotnet/runtime/issues/61885, for reference

**Comment by aoli-al** [comment] 2023-06-01 00:22
Thanks for pointing that out! The explanation sounds reasonable, so please feel free to close this issue if you have been tracking it.

**Comment by tannergooding** [comment] 2023-06-01 00:53
Thanks! I'll close this as a dupe then and will hopefully be able to get this addressed nearer rather than later term.

**Closed by tannergooding** 2023-06-01 00:53 UTC
Labels: area-System.Numerics
