### ISSUE TITLE
Built-in self repair fails on .NET 5.0 Desktop Environment (.exe) - Process.Start()

### ISSUE THREAD

**Issue by dynamicons** [dotnet/runtime#45542] opened 2020-12-03 13:31 UTC
### Description

Hello!

There seems to be an issue with the .NET self-repair stub that is built into every Executable (.exe) file.

Reproduction:
Create a simple Windows Forms Application for the .NET 5.0 Desktop Environment. 

In the bin/x86/Release/net5.0-windows folder, you'll find your Application.exe file. 
With every Application.exe, there is automatically generated an Application.dll file.

Copy Application.exe and Application.dll to your desktop. Double-Click on Application.exe

A small MessageBox appears:

----------------------------------------------------
| To run this application, you must install .NET.
| Would you like to download it now?
|
|                                               [Yes]         [No]
----------------------------------------------------
 
Now whether you click on Yes or No, nothing happens at all.

Desired behavior is to download the required .NET 5.0 Desktop Environment, Win32 (x86) version.
So that this component can be used to repair (or even automatically deploy) the given application.

### Configuration

Windows 10 Home or Professional, Version 20H2
Visual Studio 2019 (v16.8.2)
.NET 5.0 Desktop Environment for Windows Forms
(Win32/x86) version => may also appear on 64-bit

### Regression?

The default for UseShellExecute has been changed to false with .NET 5.0, because that's more conform with Linux, Mac etc.
However, due to this change in default behaviour, Process.Start() fails silently on a traditional PC Windows Desktop now.

So maybe that's a hint what goes wrong.

So if the Application's built-in Self-Repair stub tries to call the .NET 5.0 download weblink, now it would fail instantly because of an incompatible change in Process.Start() that was introduced with .NET 5.0:

// .NET 4.0: start the external Weblink in a new Windows System Process (Thread):
Process.Start( "https://dotnet.microsoft.com/download/dotnet/5.0" );

// .NET 5.0:  start the external Weblink in a new Windows System Process (Thread):
Process.Start( new ProcessStartInfo { FileName = "https://dotnet.microsoft.com/download/dotnet/5.0", UseShellExecute = true } );

So here we see that Process.Start(), just given the straight weblink as before, would now fail silently on Windows 10 Home.

Desired behaviour is of course to lead the user to a download location and install .NET 5.0 in the correct version.

Apart from that, i have no insight whatsoever into this - seemingly automated - Startup message. It seems to be added by the Visual Studio compiler itself. So the above Process.Start() description is only a guess of what might go wrong.

### Other information

The idea of an - automatically built-in - Self-Repair showing such a MessageBox Installation Requester is really good.
However, since the Application will itself be compiled within .NET 5.0, there is no possible fix on the user side.

The message is automatic and since .NET 5.0 is missing, Your own Sourcecode is never reached.
That's what i can observe at least. Here's a Screenshot of my own reproduction.

https://dynamions.files.wordpress.com/2020/11/iotdeveloper.exe-built-in-.net-5.0-detector.png

Should it not be possible to detect automatically the correct self-repair download (for any other reason), please introduce the possibility to supply the Installer Weblink manually within .csproj, .vdproj and/or AppxManifest.xml file for Windows 10 Store.

<PreconditionInstaller> Weblink </PreconditionInstaller>

All in all, i conclude that issue should be fixed right within Visual Studio development enviroment, or .NET 5.0 core.

Thank you for considering,

Martin Bernhardt, Founder
www.dynamic-applications.org

**Comment by eiriktsarpalis** [comment] 2020-12-03 14:45
I can reproduce the problem:

![image](https://user-images.githubusercontent.com/2813363/101043250-c744d980-3586-11eb-9802-210806faedc2.png)

@danmosemsft not sure what the right area label for this issue might be?

**Comment by vitek-karas** [comment] 2020-12-03 15:35
Thanks for reporting this - I'll look into it.

That said, in .NET 5, having just the `.exe` and `.dll` is not enough to run the app. The `.runtimeconfig.json` and `.deps.json` are also required to run the app.

Even if the dialog worked and it would make you install the .NET 5 runtime, the app would still not run.

**Comment by vitek-karas** [comment] 2020-12-03 15:45
The problem is that the host doesn't actually fail with "You need to install .NET" type of error - but it failed with "Can't run self-contained app" type of error. So there's no URL which is stored internally to point to once the "Yes" is clicked. This will need a change to show a different UI in this case.

That said - if I try to do the same with console app I get the original error:
```console
Cannot use file stream for [carep.deps.json]: No such file or directory
A fatal error was encountered. The library 'hostpolicy.dll' required to execute the application was not found in 'C:\Program Files\dotnet'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because 'carep.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the 'carep.runtimeconfig.json' file and specify the appropriate framework.
```

This error is still not ideal:
* The failure to open `.deps.json` should not be part of the error message
* The lookup of `hostpolicy.dll` in `C:\Program FIles\dotnet` is wrong - and that should not be part of the error message
* The error message should state that it can't find `hostpolicy.dll` in the app itself

But the last part of the message is correct - since the app is missing `.runtimeconfig.json` it is executed as a "self-contained" application - and that failed, because required files are missing (`hostpolicy.dll` in this case).

**Comment by vitek-karas** [comment] 2020-12-03 21:53
Things to do to improve the experience:
* For GUI apps, we always show the same UI "Please install .NET" even if the failure is not about missing framework. We need to change the logic to detect the "missing framework" cases and keep the current behavior and for everything else use a different UI (probably with just an OK button) which will include some generic "It failed" message, followed by the detailed error.
* For console apps, improve the error behavior around missing `.runtimeconfig.json` - this is relatively tricky due to how host works, but we should optimize the error for the most common scenario (FDD app which is missing `.runtimeconfig.json` or corrupted SCD app).

**Comment by dynamicons** [comment] 2020-12-04 10:53
Dear Vitek,

thank you for reproducing this issue properly. 

Interestingly, here the App.runtimeconfig.json file points to the correct .NET Release.

{
  "runtimeOptions": {
    "tfm": "net5.0",
    "framework": {
      "name": "Microsoft.WindowsDesktop.App",
      "version": "5.0.0"
    }
}}


The question remains do we really need that additional .json file, or could that information be put into the Executable? - well, i guess that's been decided, so in that case you are right and the Message should show that the json file is missing.

My suggestion would be to still use this information and download the correct version of .NET 5.0 Desktop Runtime.

The solution should be able to detect whether it's been compiled for x86, x64 or AnyCPU.
I would therefore recommend to test the solution with AnyCPU, x86 and x64 compiler Setting.

To provide a small Executable with a few DLLs and then .NET installs itself on first usage should be a great achievement.

**Comment by vitek-karas** [comment] 2020-12-04 13:46
.NET 5 (or .NET Core) can't create "anycpu" executable. That was a trick which was possible only in .NET Framework because of direct integration of .NET Framework and Windows OS (there was a bit of code in the OS Process loader which detected managed .exe and redirected it to .NET Framework). .NET 5 doesn't have any OS integration (that's why it's possible to install it SxS and without rebooting and so on...).

So if the app needs both x86 and x64, it has to produce two builds - x86 and x64. No different from a native application.

As for the rest, to get a single executable which will ask to install .NET if it's not already present, that's actually possible even today.

```console
dotnet new winforms
dotnet publish -r win-x64 --self-contained false /p:PublishSingleFile=true
```

This produces one `app.exe` (and a `.pdb` but that's not important) - if that executable is run on a machine which doesn't have .NET installed it will popup the dialog as shown above. In this case the "yes" button works and will open the download page for the runtime.

Please note that currently there's some work left to be done on the server side for this experience to be really good - right now the app sends all of the version and architecture information to the server in the URL, but the server basically ignores most of it and only offers the right version - but no specific architecture.

**Comment by dynamicons** [comment] 2020-12-16 15:10
Hmm... ok, Thank you, Vitek. Fair enough. Another hint to try.
my best suggestion then is to keep providing 2-3 variants, each, in the long run:

(Win32 or Win64)
(compact or all-in-one)
(with or without .NET 5 installer)

for each of these, there should be a fine implementation. what we definitely won't need - from the developer side - is to be able to select Win32, and then in Debug settings again say "x86 only code" and then it won't work on my machine anyways ;-)

So in the best case, the developer can select CPU architecture (should really be called 32/64 bit), then decide for compact exe with DLLs, or all-in-one executable, and finally decide whether .NET 5 shall be included as well (superone DLLL exe).

From our position, Transparency (clarity and understandability and safety/warranty) is of major importance.
of same importance we see Privacy Protection, House and Home considerations (your work .. our work/money .. my work), 
and finally Participation (same chances for all, same rights for all, democracy and online voting). 

I am pretty sure that there's gonna be as well demand for small Executables, as far and where ever we are.

So of course, here's the question who pays the bill of rights. Yes. Clarity helps against of 'hey, got another XML Tag'...
But i think that's 50/50, 40%/60%, 30%/70% or 25%/75% really, as long as we talk about an App Store Economy model.

So that's why we've (i've) decided for Microsoft:  
The Software once started from crap, with excellent business conditions ;-)

Here's a small outlook to what challenge we are focussing with Dynamic Applications.

https://dynamic-applications.org/downloads/key-account-manager/

A small Startup Finance Product, at its best a Toolkit, based on a few Excel Tables and PDF.
An idea was born, you know. That's where we all begin, if you want to see what came from it...

Read the Website ;-)

In 21st century, it's our Culture that's gonna define our Success over time. Laptops we got all.

Merry Christmas to everyone.
Keep me posted in 2021.

Thank you for supporting us!

best regards,


Martin Bernhardt, Founder
www.dynamic-applications.org

**Comment by vitek-karas** [comment] 2021-07-09 12:35
Closing this as there's no apparent issue to fix/explain. If I'm wrong please feel free to reopen or create a new issue.

**Closed by vitek-karas** 2021-07-09 12:35 UTC
Labels: area-Host, untriaged

**Comment by dynamicons** [comment] 2021-07-22 08:48
Dear Vitek,

from our perspective, the issue described above is not fixed. Again we have seen reported that the Test of Dynamic Applications failed - this was even reported by the MS Windows 10 Store App Team Testers - because of lack of installation .NET 5.0 Desktop.

So as it was reproduced correctly by your collegue, there is an automatic check included with .NET 5.0 (probably from 4.0) but it seems to be dysfunctional. As it is beyond our control to foresee which is the suitable, current release of .NET 5.0.x aye would ask the MS Store Team to kindly provide a means to automatically pre-install the required Desktop Environment.

You can download the traditional Setup.exe that we've built with the traditional Setup.exe Installer Project Addon as a reference on how you do it correctly. So all it takes would be a means to provide an XML Tag with AppxManifest.xml description where we can enter requirement and set it to the correct location where you want people to download .NET 5.0 Desktop Environment. 

To bind the installation with all DLLs required from .NET 5.0 Desktop Environment would produce an unnecessary huge download. That is not acceptable as many poor people in the 3rd world have to pay with Mobile Quota for the download.

So we need a way to install the requirement on first download and then to deploy Updates as small as possible.
From my perspective, that's a fair enough demandment by Millions of People with not so much money in the pocket.

Thank you for considering,

Martin Bernhardt, Founder
www.dynamic-applications.org

**Comment by vitek-karas** [comment] 2021-07-22 09:08
I don't think we will ever have the same seamless experience which .NET Framework provides. Mainly because .NET Framework is integrated into the Windows OS, which .NET Core/.NET 5 is not (and we don't plan to do that going forward either).

There are discussions on improving the experience when this happens:
There are several existing issues covering this topic:
https://github.com/dotnet/runtime/issues/36765 is about the target page the link goes to
https://github.com/dotnet/runtime/issues/3811 discusses improvements to the console output in the case of the same error
https://github.com/dotnet/runtime/issues/3816 discusses using better UI in this case

We hope to improve some of this in .NET 6. But all these plans require some end user interaction. We don't think that just running a .NET application should directly trigger an installer. The problem in that flow which I see is that the installer would ask for elevation and that would be at the very least confusing for the end user (I think it's worse - it effectively acts like a virus - I run an app and it tries to get into my system).

If you provide an installer for your application, it should be pretty straightforward to chain the msi packages we provide for the runtime.

I must admit that I don't know what is the deployment story for Windows Store apps. @richlander might know.
