### ISSUE TITLE
ValueTask.ConfigureAwait(false) may resume execution on a random synchronization context

### ISSUE THREAD

**Issue by noseratio** [dotnet/runtime#71313] opened 2022-06-27 01:39 UTC
### Description

The behavior of `ConfiguredValueTaskAwaitable` is different from that of a full-featured `Task`'s `ConfiguredTaskAwaitable`.

Unlike the latter, `ConfiguredValueTaskAwaitable` does not push continuations to the thread pool when its `ValueTask` is completed on a thread with a random synchronization context, different from the synchronization context at the call site of `await SomeValueTaskFunc().ConfigureAwait(false)`.

### Reproduction Steps

Example (can be copy-pasted into `Program.cs` of a `dotnet new console` project):

```c#
#nullable enable
using System;
using System.Diagnostics;
using System.Threading;
using System.Threading.Tasks;
using System.Threading.Tasks.Sources;

const string SCA = $"{nameof(TestSyncContext)}A";
const string SCB = $"{nameof(TestSyncContext)}B";

Trace.Listeners.Add(new ConsoleTraceListener());

AppDomain.CurrentDomain.UnhandledException += (s, e) =>
    Trace.TraceError(e.ToString());

static void TraceSyncContext() => Trace.WriteLine($"{nameof(SynchronizationContext)}: {SynchronizationContext.Current}");

await TestValueTaskSource();
await TestTaskCompletionSource();

// TestValueTaskSource
async Task TestValueTaskSource()
{
    Trace.WriteLine(nameof(TestValueTaskSource));
    Trace.Indent();
    try
    {
        var sca = new TestSyncContext(SCA);
        var scb = new TestSyncContext(SCB);

        ValueTaskSource<bool> vts = new();

        async Task TestA()
        {
            if (SynchronizationContext.Current != sca)
                throw new Exception($"Expect {sca}");

            // we are on SyncContextA here
            TraceSyncContext();
            await vts.GetTask().ConfigureAwait(false);

            // we are on SyncContextB here, because of the ConfigureAwait(false)
            // above and ManualResetValueTaskSourceCore.SetResult
            // being invoked on SyncContextB
            TraceSyncContext();

            if (SynchronizationContext.Current != scb)
                throw new Exception($"Expect {scb}");
        }

        async Task TestB()
        {
            await Task.Delay(TimeSpan.FromSeconds(1));

            if (SynchronizationContext.Current != scb)
                throw new Exception($"Expect {scb}");

            vts.SetResult(true);

            await Task.Delay(TimeSpan.FromSeconds(1));
        }

        await Task.WhenAll(sca.Run(TestA), scb.Run(TestB));
        Trace.WriteLine("Completed succesfully");
    }
    finally
    {
        Trace.Unindent();
    }
}

// TestTaskCompletionSource
async Task TestTaskCompletionSource()
{
    Trace.WriteLine(nameof(TestTaskCompletionSource));
    Trace.Indent();
    try
    {
        var sca = new TestSyncContext(SCA);
        var scb = new TestSyncContext(SCB);

        TaskCompletionSource<bool> tcs = new();

        async Task TestA()
        {
            if (SynchronizationContext.Current != sca)
                throw new Exception($"Expect {sca}");

            // we are on SyncContextA here
            TraceSyncContext();
            await tcs.Task.ConfigureAwait(false);

            // we are on no sync context here, because of the ConfigureAwait(false) above
            // and TaskCompletionSource.SetResult being invoked on SyncContextB,
            TraceSyncContext();

            if (SynchronizationContext.Current is not null)
                throw new Exception($"Expect no sync context");

            await Task.Delay(TimeSpan.FromSeconds(1));
        }

        async Task TestB()
        {
            await Task.Delay(TimeSpan.FromSeconds(1));

            if (SynchronizationContext.Current != scb)
                throw new Exception($"Expect {scb}");

            tcs.SetResult(true);

            await Task.Delay(TimeSpan.FromSeconds(1));
        }

        await Task.WhenAll(sca.Run(TestA), scb.Run(TestB));
        Trace.WriteLine("Completed succesfully");
    }
    finally
    {
        Trace.Unindent();
    }
}

/// <summary>
/// ValueTaskSource
/// </summary>
class ValueTaskSource<T> : IValueTaskSource<T>
{
    private ManualResetValueTaskSourceCore<T> _mrvtsc = default;

    T IValueTaskSource<T>.GetResult(short token) => _mrvtsc.GetResult(token);

    ValueTaskSourceStatus IValueTaskSource<T>.GetStatus(short token) => _mrvtsc.GetStatus(token);

    void IValueTaskSource<T>.OnCompleted(Action<object?> continuation, object? state, short token, ValueTaskSourceOnCompletedFlags flags) =>
        _mrvtsc.OnCompleted(continuation, state, token, flags);

    public void SetResult(T value) => _mrvtsc.SetResult(value);

    public void Reset() => _mrvtsc.Reset();

    public ValueTask<T> GetTask() => new(this, _mrvtsc.Version);
}


/// <summary>
/// TestSyncContext
/// </summary>
class TestSyncContext : SynchronizationContext
{
    private readonly string _name;
    private readonly TaskScheduler _taskScheduler;

    public TestSyncContext(string name)
    {
        _name = name;
        var tcs = new TaskCompletionSource<TaskScheduler>();
        this.Post(_ => tcs.SetResult(TaskScheduler.FromCurrentSynchronizationContext()), null);
        _taskScheduler = tcs.Task.GetAwaiter().GetResult();
    }

    public Task Run(Func<Task> func) =>
        Task.Factory.StartNew<Task>(
            function: static s => ((Func<Task>)s!)(),
            state: func,
            cancellationToken: CancellationToken.None,
            TaskCreationOptions.None,
            scheduler: _taskScheduler).Unwrap();

    public override void Post(SendOrPostCallback d, object? state) =>
        ThreadPool.UnsafeQueueUserWorkItem<(SynchronizationContext sc, SendOrPostCallback callback, object? state)>(
            static s =>
            {
                var oldSc = SynchronizationContext.Current;
                SynchronizationContext.SetSynchronizationContext(s.sc);
                try
                {
                    s.callback(s.state);
                }
                finally
                {
                    SynchronizationContext.SetSynchronizationContext(oldSc);
                }
            }, 
            (this, d, state), 
            preferLocal: true);

    public override string ToString() => _name;
}
```

### Expected behavior

Expected output:

```text
TestValueTaskSource
    SynchronizationContext: TestSyncContextA
    SynchronizationContext: 
    Completed succesfully
TestTaskCompletionSource
    SynchronizationContext: TestSyncContextA
    SynchronizationContext:
    Completed succesfully
```

### Actual behavior

Note `TestSyncContextB`:

```text
TestValueTaskSource
    SynchronizationContext: TestSyncContextA
    SynchronizationContext: TestSyncContextB
    Completed succesfully
TestTaskCompletionSource
    SynchronizationContext: TestSyncContextA
    SynchronizationContext:
    Completed succesfully
```

### Configuration

.NET 6.0.6 / Windows x64

### Other information

I personally like this behavior of `ValueTask`, I find it less nuanced than that of its older sibling `Task` (where it may lead to unexpected and redundant [context switches](https://dev.to/noseratio/why-i-no-longer-use-configureawait-false-3pne#:~:text=redundant%20context%20switches)).

That said, I'd like to know if this is a bug which may get eventually fixed, or a by-design-behavior. 

Whatever the expected behavior is, I think there should be consistency between `ValueTask.ConfigureAwait` and `Task.ConfigureAwait`. 

OTOH, I think there also should be a way to execute a `ValueTask` continuation immediately regardless of the context (that's what `Task.ContinueWith` with `TaskContinuationOptions.ExecuteSynchronously` does for `Task`, but `ValueTask` doesn't seem to have any official feature to achieve that).

**Comment by huoyaoyuan** [comment] 2022-06-27 03:58
By contract, `ConfigureAwait(false)` doesn't restore the synchronization context. This should be by-design.

It would be interesting to identify the reason of behavior difference.

**Comment by noseratio** [comment] 2022-06-27 04:07
> By contract, `ConfigureAwait(false)` doesn't restore the synchronization context. This should be by-design.

The docs say:

> `true` to attempt to marshal the continuation back to the original context captured; otherwise, false.

So technically, it means "do not attempt to resume on the _original_ context", but it doesn't mean "do not resume on any other context". 

The fact that `ConfiguredTaskAwaitable` doesn't resume on any other context is an implementation detail, which doesn't mean that `ConfiguredValueTaskAwaitable` has to do the same (although it could be a logical thing to do). 

I personally prefer the current behavior of `ConfiguredValueTaskAwaitable`, which is similar to `Task.ContinueWith` with `TaskContinuationOptions.ExecuteSynchronously`.

**Comment by noseratio** [comment] 2022-06-27 23:40
Whetever the expected by-design behavior is, I think there should be consistency between `ValueTask.ConfigureAwait` and `Task.ConfigureAwait`. 

OTOH, I think there also should be a way to execute a `ValueTask` continuation immediately regardless of the context (that's what `Task.ContinueWith` with `TaskContinuationOptions.ExecuteSynchronously` does for `Task`, but `ValueTask` doesn't seem to have any official feature for this). 

I hope @stephentoub could have a look into this.

**Comment by joperezr** [comment] 2022-07-11 21:37
cc: @stephentoub

**Comment by stephentoub** [comment] 2022-12-09 03:12
This isn't about ConfiguredTaskAwaitable; ValueTask doesn't actually have its own behavior here.  It just delegates to the thing it wraps.  If it wraps a Task, it delegates to the Task.  If it wraps an IValueTaskSource, it delegates to the IValueTaskSource.  The implementation of how the continuation is invoked is entirely up to the thing being wrapped, which in your repro is your own custom IValueTaskSource implementation.  That implementation is in turn using ManualResetValueTaskSourceCore, and it's by design that ManualResetValueTaskSourceCore's OnCompleted isn't doing that additional check that Task is doing (if we had it to do over, I don't think we'd have had Task do it either).

**Comment by stephentoub** [comment] 2023-01-20 23:04
Closing as answered.

**Closed by stephentoub** 2023-01-20 23:04 UTC
Labels: area-System.Threading.Tasks

**Comment by noseratio** [comment] 2023-01-21 01:01
Belated thanks for answering, Stephen! It does makes sense and as long as this behavior is defined and documented (as it is now here in this thread), I'm on board with it.
