### ISSUE TITLE
Incorrect FileVersion with .NET 6.0 Preview 4

### ISSUE THREAD

**Issue by schillc** [dotnet/runtime#54120] opened 2021-06-13 10:21 UTC
I am developing a single file application with .NET 6 and deploy it to a webserver.

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType> 
    <TargetFramework>net6.0-windows</TargetFramework>
    <InformationalVersion>21.9</InformationalVersion>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
    <RuntimeIdentifier>win10-x64</RuntimeIdentifier>
  </PropertyGroup>
</Project>
```
`dotnet publish C:\Projekte\Application1\src\Client\Client.csproj -c Release`

For auto-updating I use a php script to get the application's meta information including file version.

I am using this method since several years and it always returned the correct values.
However since .NET preview 4 single file distribution those values are incorrect.

Function for reading meta information: https://stackoverflow.com/questions/41228319/extract-internal-exe-info

.NET 6 Preview 2 result:
```
{
    "CompanyName": "MyCompany",
    "FileDescription": "",
    "FileVersion": "1.0.0.0",
    "InternalName": "Application1.dll",
    "LegalCopyright": " ",
    "OriginalFilename": "Application1.dll",
    "ProductName": "Application1",
    "ProductVersion": "21.9",
    "Assembly Version": "1.0.0.0"
}
```

.NET 6 Preview 4 result:
```
{
    "CompanyName": "Microsoft Corporation",
    "FileDescription": "Microsoft .NET External Data Access Support",
    "FileVersion": "6,0,21,25307 @Commit: bfd6048a605e9a0bebced7171a98bc3f04c78192",
    "InternalName": "mscordaccore.dll",
    "LegalCopyright": "© Microsoft Corporation. All rights reserved.",
    "OriginalFilename": "mscordaccore.dll",
    "ProductName": "Microsoft® .NET",
    "ProductVersion": "6,0,21,25307 @Commit: bfd6048a605e9a0bebced7171a98bc3f04c78192",
    "Comments": "Flavor=Retail"
}
```
I also tried another function (https://stackoverflow.com/a/6748010) to get the file version but it still returns "6,0,21,25307 @Commit: bfd6048a605e9a0bebced7171a98bc3f04c78192".

**Comment by hoyosjs** [comment] 2021-06-14 17:14
Looking at both methods, they are doing things that are usually fine, except that they are not correct. In this case, they search for a string in the file, and when they find it they assume that's the place where the metadata structure is. The problem is single-file has other embedded images, and as such it hits that part of the metadata before the one that you were looking for. Probably for this you'd need a package that can open and read the PE format to be truly resilient to issues like this.

I checked this with the explorer and it works fine: 
![image](https://user-images.githubusercontent.com/19413848/121931187-22a31180-ccf8-11eb-99a6-cc4543676095.png)

**Comment by vitek-karas** [comment] 2021-07-14 15:21
Closing as there doesn't seem to be a product problem. Feel free to reopen or create new issue if needed.

**Closed by vitek-karas** 2021-07-14 15:21 UTC
Labels: area-Single-File, customer assistance
