### ISSUE TITLE
System.Text.Json and docker image with unicode encoder issue

### ISSUE THREAD

**Issue by jan-johansson-mr** [dotnet/runtime#62152] opened 2021-11-29 19:11 UTC
Hi,

I'm building a docker image based on `mcr.microsoft.com/dotnet/aspnet:6.0-focal` (Ubuntu 20.04) and want to serialize a string in Swedish language, containing the localized letters å, ä and ö. This works great when I'm running the image in Visual Studio 2022 in debugging mode.

However, when I build the docker image and run the image outside of debugging mode and serialize the same string, then I get the character `FFFD` in place of å, ä and ö.

## What I did to try to resolve the issue

I've been doing localization setup with `JsonSerializerOptions`, e.g.
```
private readonly JsonSerializerOptions _jsonSerializerOptions = new()
{
    Encoder = JavaScriptEncoder.Create(UnicodeRanges.All),
};
```
Adding all the ranges to the encoder, but I still get the same issue.

To go further I've also added localization support as a step to build the docker image, as
```
FROM mcr.microsoft.com/dotnet/aspnet:6.0-focal AS base
RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 \
    && localedef -i sv_SE -c -f UTF-8 -A /usr/share/locale/locale.alias sv_SE.UTF-8
ENV LANG sv_SE.utf8
```
But it's not helping. I still get the `FFFD` as replacement for the characters å, ä and ö.

## As a bonus

If I do not build the container with the `locales` as above, e.g. the image is built with
```
FROM mcr.microsoft.com/dotnet/aspnet:6.0-focal AS base
```
And serialize with JsonSerializer when I'm debugging (with VS 2022), then I get the characters å, ä and ö.

If I do not specify the `Encoder` with the `JsonSerializerOptions`, then the characters are unicode escaped, e.g. ä is translated to `00E4` by the serializer when debugging (with VS 2022).

## How to resolve the issue

I have no idea. It would be great to get some help with this issue.

**Comment by GrabYourPitchforks** [comment] 2021-11-29 22:35
To folks investigating: `U+FFFD` means that the input data was not well-formed. It's possible that when the string was materialized inside the application, the string itself contained literal `\uFFFD` characters (because the byte data feeding the string couldn't be understood?), and the encoder just passed this through as-is.

**Comment by jan-johansson-mr** [comment] 2021-11-30 19:22
Hi @GrabYourPitchforks, 

I've investigated the issue and here is what I've found out so far...

I've built two applications, one console app and one web app, form the templates in VS 2022.

The code in both is a one liner (I've replaced all setup code and so on in the web app)

`Console.WriteLine("åäöÅÄÖ");`

After that I simply (release) build the container images (one for console app and one for web app), and run the containers with the following result:

From the console app: **åäöÅÄÖ**
From the web app: **U+FFFD U+FFFD U+FFFD U+FFFD U+FFFD U+FFFD** (I've inserted spaces for readability).

I've searched a lot on the net for the difference, but nothing pops up.

There is a fundamental difference if I use the debug version of the containers, my whole nuget repository is copied into a nuget folder in root as a nuget fallback. When I run both containers in debug, then both display the same characters **åäöÅÄÖ**.

What is needed for the web app container to use the correct localization when release built? I still have no idea.

**Comment by eiriktsarpalis** [comment] 2021-12-01 13:57
Hi @jan-johansson-mr, would it be possible to share a repo containing the full configuration of your docker application? Ideally it should be a minimal reproduction (removing any unnecessary components or dependencies) and include instructions to build and run the docker image.

**Comment by jan-johansson-mr** [comment] 2021-12-01 18:31
Hi @eiriktsarpalis,

I have reach a solution to the issue, and it is a quite interesting one! Please take a look at the issue I opened at [aspnetcore)(https://github.com/dotnet/aspnetcore/issues/38743), and see for yourself!

Thanks! :-)

**Comment by eiriktsarpalis** [comment] 2021-12-02 09:01
Got it, if the other issue answered your question I guess we can close this one. Let me know if there is anything else that remains to be addressed on our side.

**Closed by eiriktsarpalis** 2021-12-02 09:01 UTC
Labels: area-System.Text.Json, needs further triage
