### ISSUE TITLE
[ProfilerAPI] No more ModuleLoadFinished callbacks for dynamic modules

### ISSUE THREAD

**Issue by ww898** [dotnet/runtime#76016] opened 2022-09-22 14:03 UTC
Hi there,

.NET 7.0 rc1 doesn't send `ICorProfilerCallback::ModuleLoadFinished` for dynamic modules any more. .NET 6.0.9 works properly.

Example:
```csharp
using System;
using System.Reflection;
using System.Reflection.Emit;

namespace DynamicAssemblyTestProgram
{
  internal static class DynamicAssemblyTestProgram
  {
    internal static void Main()
    {
      var type = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName("TestAssembly"), AssemblyBuilderAccess.Run)
        .DefineDynamicModule("TestModule")
        .DefineType("TestClass", TypeAttributes.Public)
        .CreateType();
      var obj = Activator.CreateInstance(type);
      if (obj == null)
        throw new NullReferenceException();

      Console.WriteLine("Done!");
      Console.ReadKey();
      GC.KeepAlive(obj);
    }
  }
}
```

Profiler log, see `00007FFC14200110`:
```
...
0000E598 1 00000217541FB1C0 MProf::ModuleLoadStarted mid=00007FFC13D34000
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadStarted mid=00007FFC13D34000
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadStarted mid=00007FFC13D34000 res=ok mdi=1
0000E598 1 00000217541FB1C0 MProf::ModuleLoadFinished mid=00007FFC13D34000 hr=00000000
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadFinished mid=00007FFC13D34000 hr=00000000 addr=00007FFC72D60000 flags=Dnycrfw mname='C:\Users\Mikhail.Pilin\Downloads\DynamicAssemblyTestProgram\DynamicAssemblyTestProgram\bin\Release\net7.0\win-x64\publish\System.Private.CoreLib.dll'
0000E598 1 00000217541FB1C0 MDG2::CollectIds mid=00007FFC13D34000 res=ok_root_module
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadFinished mid=00007FFC13D34000 res=ok_reuse mdi=1
0000E598 1 00000217541FB1C0 MDG2::Map mid=00007FFC13D34000 res=ok_memory mname='C:\Users\Mikhail.Pilin\Downloads\DynamicAssemblyTestProgram\DynamicAssemblyTestProgram\bin\Release\net7.0\win-x64\publish\System.Private.CoreLib.dll'
0000E598 1 00000217541FB1C0 MDG2::TryWrite mid=00007FFC13D34000 mdi=1 res=image
0000E598 1 00000217541FB1C0 BProf::ModuleAttachedToAssembly mid=00007FFC13D34000 aid=00000217541F6B50
0000E598 1 00000217541FB1C0 GCCQ::Activate
0000D378 1 0000021757E18880 MDG2::FlushMetadata
0000D378 1 0000021757E18880 MDG2::FlushMetadata res=ok
0000E598 1 00000217541FB1C0 MProf::ModuleLoadStarted mid=00007FFC13FF10B0
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadStarted mid=00007FFC13FF10B0
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadStarted mid=00007FFC13FF10B0 res=ok mdi=2
0000E598 1 00000217541FB1C0 MProf::ModuleLoadFinished mid=00007FFC13FF10B0 hr=00000000
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadFinished mid=00007FFC13FF10B0 hr=00000000 addr=00000257ECA70000 flags=Dnycrfw mname='C:\Users\Mikhail.Pilin\Downloads\DynamicAssemblyTestProgram\DynamicAssemblyTestProgram\bin\Release\net7.0\win-x64\publish\DynamicAssemblyTestProgram.dll'
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadFinished mid=00007FFC13FF10B0 res=ok_reuse mdi=2
0000E598 1 00000217541FB1C0 MDG2::Map mid=00007FFC13FF10B0 res=ok_memory mname='C:\Users\Mikhail.Pilin\Downloads\DynamicAssemblyTestProgram\DynamicAssemblyTestProgram\bin\Release\net7.0\win-x64\publish\DynamicAssemblyTestProgram.dll'
0000E598 1 00000217541FB1C0 MDG2::TryWrite mid=00007FFC13FF10B0 mdi=2 res=image
0000E598 1 00000217541FB1C0 BProf::ModuleAttachedToAssembly mid=00007FFC13FF10B0 aid=00000217541F82F0
0000E598 1 00000217541FB1C0 MProf::ModuleLoadStarted mid=00007FFC13FF2BE8
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadStarted mid=00007FFC13FF2BE8
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadStarted mid=00007FFC13FF2BE8 res=ok mdi=3
0000E598 1 00000217541FB1C0 MProf::ModuleLoadFinished mid=00007FFC13FF2BE8 hr=00000000
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadFinished mid=00007FFC13FF2BE8 hr=00000000 addr=00000257ECA80000 flags=Dnycrfw mname='C:\Users\Mikhail.Pilin\Downloads\DynamicAssemblyTestProgram\DynamicAssemblyTestProgram\bin\Release\net7.0\win-x64\publish\System.Runtime.dll'
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadFinished mid=00007FFC13FF2BE8 res=ok_reuse mdi=3
0000E598 1 00000217541FB1C0 MDG2::Map mid=00007FFC13FF2BE8 res=ok_memory mname='C:\Users\Mikhail.Pilin\Downloads\DynamicAssemblyTestProgram\DynamicAssemblyTestProgram\bin\Release\net7.0\win-x64\publish\System.Runtime.dll'
0000E598 1 00000217541FB1C0 MDG2::TryWrite mid=00007FFC13FF2BE8 mdi=3 res=image
0000E598 1 00000217541FB1C0 BProf::ModuleAttachedToAssembly mid=00007FFC13FF2BE8 aid=00000217541F7F30
0000E598 1 00000217541FB1C0 MProf::ModuleLoadStarted mid=00007FFC141B5B18
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadStarted mid=00007FFC141B5B18
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadStarted mid=00007FFC141B5B18 res=ok mdi=4
0000E598 1 00000217541FB1C0 MProf::ModuleLoadFinished mid=00007FFC141B5B18 hr=00000000
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadFinished mid=00007FFC141B5B18 hr=00000000 addr=00000257ECAF0000 flags=Dnycrfw mname='C:\Users\Mikhail.Pilin\Downloads\DynamicAssemblyTestProgram\DynamicAssemblyTestProgram\bin\Release\net7.0\win-x64\publish\System.Reflection.Emit.dll'
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadFinished mid=00007FFC141B5B18 res=ok_reuse mdi=4
0000E598 1 00000217541FB1C0 MDG2::Map mid=00007FFC141B5B18 res=ok_memory mname='C:\Users\Mikhail.Pilin\Downloads\DynamicAssemblyTestProgram\DynamicAssemblyTestProgram\bin\Release\net7.0\win-x64\publish\System.Reflection.Emit.dll'
0000E598 1 00000217541FB1C0 MDG2::TryWrite mid=00007FFC141B5B18 mdi=4 res=image
0000E598 1 00000217541FB1C0 BProf::ModuleAttachedToAssembly mid=00007FFC141B5B18 aid=00000257ECF0E780
0000E598 1 00000217541FB1C0 MProf::ModuleLoadStarted mid=00007FFC141B6678
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadStarted mid=00007FFC141B6678
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadStarted mid=00007FFC141B6678 res=ok mdi=5
0000E598 1 00000217541FB1C0 MProf::ModuleLoadFinished mid=00007FFC141B6678 hr=00000000
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadFinished mid=00007FFC141B6678 hr=00000000 addr=00007FFCECEB0000 flags=Dnycrfw mname='C:\Users\Mikhail.Pilin\Downloads\DynamicAssemblyTestProgram\DynamicAssemblyTestProgram\bin\Release\net7.0\win-x64\publish\System.Console.dll'
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadFinished mid=00007FFC141B6678 res=ok_reuse mdi=5
0000E598 1 00000217541FB1C0 MDG2::Map mid=00007FFC141B6678 res=ok_memory mname='C:\Users\Mikhail.Pilin\Downloads\DynamicAssemblyTestProgram\DynamicAssemblyTestProgram\bin\Release\net7.0\win-x64\publish\System.Console.dll'
0000E598 1 00000217541FB1C0 MDG2::TryWrite mid=00007FFC141B6678 mdi=5 res=image
0000E598 1 00000217541FB1C0 BProf::ModuleAttachedToAssembly mid=00007FFC141B6678 aid=00000257ECF0D520
0000E598 1 00000217541FB1C0 MProf::ModuleLoadStarted mid=00007FFC14200110
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadStarted mid=00007FFC14200110
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadStarted mid=00007FFC14200110 res=ok mdi=6
0000E598 1 00000217541FB1C0 MProf::ModuleLoadStarted mid=00007FFC14205710
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadStarted mid=00007FFC14205710
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadStarted mid=00007FFC14205710 res=ok mdi=7
0000E598 1 00000217541FB1C0 MProf::ModuleLoadFinished mid=00007FFC14205710 hr=00000000
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadFinished mid=00007FFC14205710 hr=00000000 addr=00007FFCCAC10000 flags=Dnycrfw mname='C:\Users\Mikhail.Pilin\Downloads\DynamicAssemblyTestProgram\DynamicAssemblyTestProgram\bin\Release\net7.0\win-x64\publish\System.Threading.dll'
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadFinished mid=00007FFC14205710 res=ok_reuse mdi=7
0000E598 1 00000217541FB1C0 MDG2::Map mid=00007FFC14205710 res=ok_memory mname='C:\Users\Mikhail.Pilin\Downloads\DynamicAssemblyTestProgram\DynamicAssemblyTestProgram\bin\Release\net7.0\win-x64\publish\System.Threading.dll'
0000E598 1 00000217541FB1C0 MDG2::TryWrite mid=00007FFC14205710 mdi=7 res=image
0000E598 1 00000217541FB1C0 BProf::ModuleAttachedToAssembly mid=00007FFC14205710 aid=00000257ECF0DE20
0000E598 1 00000217541FB1C0 MProf::ModuleLoadStarted mid=00007FFC14208FF8
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadStarted mid=00007FFC14208FF8
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadStarted mid=00007FFC14208FF8 res=ok mdi=8
0000E598 1 00000217541FB1C0 MProf::ModuleLoadFinished mid=00007FFC14208FF8 hr=00000000
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadFinished mid=00007FFC14208FF8 hr=00000000 addr=00000257ECB20000 flags=Dnycrfw mname='C:\Users\Mikhail.Pilin\Downloads\DynamicAssemblyTestProgram\DynamicAssemblyTestProgram\bin\Release\net7.0\win-x64\publish\System.Text.Encoding.Extensions.dll'
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadFinished mid=00007FFC14208FF8 res=ok_reuse mdi=8
0000E598 1 00000217541FB1C0 MDG2::Map mid=00007FFC14208FF8 res=ok_memory mname='C:\Users\Mikhail.Pilin\Downloads\DynamicAssemblyTestProgram\DynamicAssemblyTestProgram\bin\Release\net7.0\win-x64\publish\System.Text.Encoding.Extensions.dll'
0000E598 1 00000217541FB1C0 MDG2::TryWrite mid=00007FFC14208FF8 mdi=8 res=image
0000E598 1 00000217541FB1C0 BProf::ModuleAttachedToAssembly mid=00007FFC14208FF8 aid=00000257ECF0D340
0000E598 1 00000217541FB1C0 MProf::ModuleLoadStarted mid=00007FFC1420A0E0
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadStarted mid=00007FFC1420A0E0
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadStarted mid=00007FFC1420A0E0 res=ok mdi=9
0000E598 1 00000217541FB1C0 MProf::ModuleLoadFinished mid=00007FFC1420A0E0 hr=00000000
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadFinished mid=00007FFC1420A0E0 hr=00000000 addr=00007FFD00FC0000 flags=Dnycrfw mname='C:\Users\Mikhail.Pilin\Downloads\DynamicAssemblyTestProgram\DynamicAssemblyTestProgram\bin\Release\net7.0\win-x64\publish\System.Runtime.InteropServices.dll'
0000E598 1 00000217541FB1C0 MDG2::ModuleLoadFinished mid=00007FFC1420A0E0 res=ok_reuse mdi=9
0000E598 1 00000217541FB1C0 MDG2::Map mid=00007FFC1420A0E0 res=ok_memory mname='C:\Users\Mikhail.Pilin\Downloads\DynamicAssemblyTestProgram\DynamicAssemblyTestProgram\bin\Release\net7.0\win-x64\publish\System.Runtime.InteropServices.dll'
0000E598 1 00000217541FB1C0 MDG2::TryWrite mid=00007FFC1420A0E0 mdi=9 res=image
0000E598 1 00000217541FB1C0 BProf::ModuleAttachedToAssembly mid=00007FFC1420A0E0 aid=00000257ECF0D5E0
0000E598 1 00000217541FB1C0 BProf::Shutdown

...
```

**Comment by tommcdon** [comment] 2022-09-22 15:07
@davmason

**Comment by ww898** [comment] 2022-10-12 09:19
Hi, there,
It there any news? Can we expect that the fix will be in the release 7.0? It's critical for any profiler.

**Comment by davmason** [comment] 2022-10-14 23:35
I opened #77068 to fix this issue, once it is checked in I will open a servicing request for 7.0.

**Closed** 2022-10-17 20:10 UTC
Labels: area-Diagnostics-coreclr, in-pr

**Comment by davmason** [comment] 2022-10-28 08:47
@alanwest @kolesnikovae not sure if you are subscribed to the profiler interest group, but wanted to make sure you saw https://github.com/dotnet/runtime/issues/9305#issuecomment-1294707542 since we have chatted about ICorProfiler and it may impact you

**Comment by pellared** [comment] 2022-10-30 12:32
> It is currently scheduled to go in the first servicing update in January
> [...]
> If you have questions or concerns please comment in https://github.com/dotnet/runtime/issues/76016 or file a new issue to not spam everyone on this thread.

Can it be sooner than January? It is not even November and I think runtime bugs should not be threated lightly 😉

**Comment by kolesnikovae** [comment] 2022-10-31 11:44
Thank you for letting me know @davmason, I joined the group. Indeed, we noticed [some symptoms](https://github.com/pyroscope-io/pyroscope/issues/1493) of the problem while testing compatibility of our integration (uses EventPipe) with .NET 7 Preview. I think I should have reported this issue, but I was sure the problem is somewhere on our side.

**Comment by davmason** [comment] 2022-11-05 23:10
> Can it be sooner than January? It is not even November and I think runtime bugs should not be treated lightly 😉

Unfortunately January is our first servicing release, we do not ship any updates in December.
