### ISSUE TITLE
ServiceProvider: InvalidOperationException not thrown for circular dependencies at runtime

### ISSUE THREAD

**Issue by angelaki** [dotnet/runtime#71489] opened 2022-06-30 13:25 UTC
### Description

This actually isn't a real bug but more an unexpected behavior (at least for me). When registering services with a circular dependency the ServiceProvider recognizes it when the service is created (or `ValidateOnBuild` set to `true`).

But when such a circular dependency is executed on runtime you just get a deadlock. This sure can happen in some _Framework scenarios_. Sure creating a lazy service in the constructor is pretty useless but, tbh, it happened to me some times in testing scenarios. And always takes me a while to figure out what is just happening.

Is this by design to improve performance? If so, this issue surely can be closed immediatelly.

### Reproduction Steps

```
using Microsoft.Extensions.DependencyInjection;

new ServiceCollection()
    .AddScoped<IA, A>()

    // System.InvalidOperationException: "A circular dependency was detected for the service of type 'IB'.
    // IB(B)->IA(A)->IB"

    //.AddScoped<IB, B>()

    .AddScoped<IB, BB>()
    .BuildServiceProvider()
    .GetService<IB>();

interface IA { }
class A : IA { public A(IB b) { } }

interface IB { }
class B : IB { public B(IA a) { } }
class BB : IB
{
    static int cnt = 0;

    public BB(IServiceProvider sp)
    {
        Console.WriteLine($"... and again ... {++cnt}");
        sp.GetService<IA>();
    }
}
```

### Expected behavior

`System.InvalidOperationException` being thrown.

### Actual behavior

Some sort of weird deadlock, where the execution just stops at some point without an exception at all.

### Configuration

.NET 6.0

**Comment by deeprobin** [comment] 2022-06-30 17:10
I can verify this behavior for .NET 6 & 7.
In any case, it is not documented that an `InvalidOperationException` will be thrown. Nevertheless, I find this a good diagnostic feature.
However, one must also note that this would be a `breaking-change`.

**Comment by angelaki** [comment] 2022-07-01 07:34
With right now the runtime being stuck and CPU usage at maximum it'd more feel like an `unbreaking-change`. Actually it is broken right now, so I don't think it is a breaking-change, is it?

**Comment by deeprobin** [comment] 2022-07-01 08:20
@angelaki Breaking-change means that something could break code of API consumers. For ex. people don't expect a `InvalidOperationException` even if it makes sense.

**Comment by maryamariyan** [comment] 2022-07-05 21:20
Closing as dupe of https://github.com/dotnet/runtime/issues/36458

**Closed by maryamariyan** 2022-07-05 21:20 UTC
Labels: untriaged, area-Extensions-DependencyInjection
