### ISSUE TITLE
SIGTSTP and SIGCONT handlers do not maintain default behavior

### ISSUE THREAD

**Issue by tnishimura** [dotnet/runtime#64511] opened 2022-01-30 12:10 UTC
### Description

.NET 6 added PosixSignalRegistration. When a handler leaves the `Cancel` attribute of `PosixSignalContext` at false (the default value), the default behavior of the signal should run. Instead, adding a TSTP and CONT handler breaks process suspension. 

### Reproduction Steps

Here is an F# script:

    open System.Threading
    open System.Runtime.InteropServices

    let mutable tstpReceived = false
    let mutable contReceived = false

    PosixSignalRegistration.Create(PosixSignal.SIGTSTP, fun context -> 
        tstpReceived <- true )
    |> ignore

    PosixSignalRegistration.Create(PosixSignal.SIGCONT, fun context -> 
        contReceived <- true)
    |> ignore

    // just some busy work so the app doesn't naturally close immediately
    for i in 1 .. 30 do
        printfn "%d %A %A" i tstpReceived contReceived
        Thread.Sleep 1000 |> ignore

### Expected behavior

If you run the F# script below, which should be basically the same thing as above, and suspend it with Ctrl-Z, it will behave properly and as any other unix application. 

    open System.Threading

    for i in 1 .. 30 do
        printfn "%d" i 
        Thread.Sleep 1000 |> ignore

### Actual behavior

When you run the F# script in the Reproduction Steps above with dotnet fsi, pressing Ctrl-Z *does* seem to background the process but does *not* suspend it... the script keeps printing to screen:

```
    $ fsi sigtstp.fsx                         # I start the script...
    1 false false
    2 false false
    3 false false
    [1]  + 72269 suspended  fsi sigtstp.fsx   # I pressed Ctrl-z
    $ 4 true false                            # and it keeps printing...
    fg                                        # I run 'fg'
    [1]  + 72269 continued  fsi sigtstp.fsx   # it foregrounds as expected
    5 true true                               # and the "true"s here indicate 
    6 true true                               # both handlers actually ran
    7 true true
    ...
```

### Regression?

This is all new in .NET 6, so no. 

### Known Workarounds

None.

### Configuration

I'm on Linux (Ubuntu 20.04 equivalent). Don't know if this would be a problem with MacOS or WSL. 
```
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     pop
 OS Version:  20.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.101/

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  6.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

### Other information

Glad to see Posix functionality is making it into .NET!

**Comment by alexrp** [comment] 2022-01-30 17:41
See: #62706

**Comment by jkotas** [comment] 2022-01-30 18:14
Duplicate of #62706

**Closed by jkotas** 2022-01-30 18:14 UTC
Labels: area-System.Runtime.InteropServices, untriaged
