### ISSUE TITLE
Receive Error while trying to use: System.Management throw System.PlatformNotSupportedException: 'System.Management currently is only supported for Windows desktop applications.'

### ISSUE THREAD

**Issue by naftulr** [dotnet/runtime#78464] opened 2022-11-16 13:31 UTC
1) Using Library project .NET Standard 2.1 and System.Management Nuget v7.0.0
2) Trying to call any object of System.Management from WPF application .NET Core 3.1 and receive the error:
System.Management throw System.PlatformNotSupportedException: 'System.Management currently is only supported for Windows desktop applications.'

**Comment by naftulr** [comment] 2022-11-16 13:37
Issue not occur with Nuget v6.0.0, only with 7.0.0

**Comment by ViktorHofer** [comment] 2022-11-16 16:56
@naftulr thanks for reaching out. What you describe is intentional as .NET 7 packages don't support .NET Core 3.1. Please refer to https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/7.0/old-framework-support for more details.

You should have also seen a build warning indicating that:

> System.Management 7.0.0 doesn't support netcoreapp3.1 and has not been tested with it. Consider upgrading your TargetFramework to net6.0 or later. You may also set &lt;SuppressTfmSupportBuildWarnings&gt;true&lt;/SuppressTfmSupportBuildWarnings&gt; in the project file to ignore this warning and attempt to run in this unsupported configuration at your own risk.

For this specific package, the .NET Standard 2.0 assembly throws PlatformNotSupportedExceptions for any API invoked as it doesn't have a loadable implementation at all and hence the unsupported `SuppressTfmSupportBuildWarnings` escape hatch doesn't apply.

Is it possible for your project to upgrade to net6.0 (.NET 6) or later? .NET Core 3.1 is going to be out-of-support next month: https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core.

**Comment by naftulr** [comment] 2022-11-17 12:16
@ViktorHofer thank you for your fast reply! I can't unfortunately upgrade to .NET 6 for now, so I will work with System.Management Nuget v6.0.0 which supporting .Net Core 3.1.
It will be nice if you can update to Nuget to be backward compatible to older frameworks.
10x!

**Comment by ViktorHofer** [comment] 2022-11-17 19:08
> so I will work with System.Management Nuget v6.0.0 which supporting .Net Core 3.1.

Sounds good. When you are able to upgrade to a newer target framework (which is in support for the next years), you can make use of the latest package version and its features. In the case of System.Management, I don't think that much changed between 6.0.x and 7.0.x.

> It will be nice if you can update to Nuget to be backward compatible to older frameworks.
10x!

We don't have any plans to do that as .NET Core 3.1 is going to be out of support next month.

Thanks for reaching out @naftulr. I'm closing this issue now as by design.

**Closed by ViktorHofer** 2022-11-17 19:08 UTC
Labels: area-System.Management, needs-further-triage

**Comment by naftulr** [comment] 2022-11-20 08:12
Thank you @ViktorHofer . I'm closing it now.
