### ISSUE TITLE
Improve error message for unexpected hardware exceptions in managed code with new EH

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#107145] opened 2024-08-29 17:20 UTC
```csharp
using System;
using System.Numerics;
using System.Runtime.Intrinsics;
using System.Runtime.Intrinsics.X86;

public class Program
{
    public static float[] s_24 = new float[100];
    public static Vector256<sbyte> s_25;
    public static sbyte[] s_26 = new sbyte[100];
    public static Vector256<byte> s_29;
    public static void Main()
    {
        for (int vr15 = 0; vr15 < 2; vr15++)
        {
            s_26[0] = 0;
            float vr16 = s_24[0]--;
            System.Console.WriteLine(s_25);
            System.Console.WriteLine(System.BitConverter.SingleToUInt32Bits(vr16));
            var vr17 = (byte)Popcnt.PopCount(1);
            var vr18 = Vector256.Create<byte>(vr17);
            var vr19 = Vector256.Create<byte>(1);
            s_29 = Avx512BW.VL.CompareLessThan(vr18, vr19);
        }
    }
}
```

With `DOTNET_LegacyExceptionHandling=1` this prints
```
Fatal error. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Program.Main()
```

However, with `DOTNET_LegacyExceptionHandling=0` it prints
```
Process terminated. InternalError
   at System.Environment.FailFast(System.Runtime.CompilerServices.StackCrawlMarkHandle, System.String, System.Runtime.CompilerServices.ObjectHandleOnStack, System.String)
   at System.Environment.FailFast(System.Threading.StackCrawlMark ByRef, System.String, System.Exception, System.String)
   at System.Environment.FailFast(System.String)
   at System.Runtime.EH.FallbackFailFast(System.Runtime.RhFailFastReason, System.Object)
   at System.Runtime.EH.RhThrowHwEx(UInt32, ExInfo ByRef)
   at Program.Main()
```

It would be nice if the message printed would offer a bit more clarity around why the fail fast occurred -- when I first saw this message I thought this was an internal logic error in the EH, when in reality it is because of an unexpected hardware exception in the jitted code. So a message like "Unexpected hardware exception \<error code\> in managed code" would be more descriptive.

The example needs an AVX512 machine.

cc @janvorli

**Comment by jakobbotsch** [comment] 2024-08-29 20:44
Makes sense.

> It would be even better if the error message mentioned invalid instruction or exception code.

Yeah, I wouldn't have opened the issue if the error message was instead something like "Unexpected hardware exception <error code> in managed code".

**Comment by jakobbotsch** [comment] 2024-08-29 20:54
I repurposed this issue for improving the error message

**Comment by janvorli** [comment] 2024-08-30 15:53
@jakobbotsch I cannot repro it. You've mentioned that it needs AVX512 capable machine to repro, which I have. At least the core i9 9900X is documented to support it. So I wonder if you actually meant the opposite.
When I run it, I get this:
```
<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>
0
<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>
3212836864
```

**Comment by jakobbotsch** [comment] 2024-08-30 17:09
@janvorli I forgot to mention that you also need `DOTNET_TieredCompilation=0`

**Comment by janvorli** [comment] 2024-08-30 17:25
It still doesn't repro for me with that (I don't get any exception / crash neither with the new nor the old exception handling)

**Comment by EgorBo** [comment] 2024-08-30 17:54
Just checked this example again on today's Main (Checked runtime), crashes for me on my Ryzen 7950x windows11-x64 with:
```
<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>
0
Process terminated. InternalError
   at System.Environment.FailFast(System.Runtime.CompilerServices.StackCrawlMarkHandle, System.String, System.Runtime.CompilerServices.ObjectHandleOnStack, System.String)
   at System.Environment.FailFast(System.Threading.StackCrawlMark ByRef, System.String, System.Exception, System.String)
   at System.Environment.FailFast(System.String)
   at System.Runtime.EH.FallbackFailFast(System.Runtime.RhFailFastReason, System.Object)
   at System.Runtime.EH.RhThrowHwEx(UInt32, ExInfo ByRef)
   at Program.Main()
```
`DOTNET_LegacyExceptionHandling=1` converts it to
```
<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>
0
Fatal error. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at Program.Main()
```

**Comment by janvorli** [comment] 2024-08-30 20:48
I was finally able to repro it - it needed Release build of the repro test, otherwise it didn't repro.

**Comment by EgorBo** [comment] 2024-08-30 20:58
note: the actual source of the SEHException is an invalid encoding for `kxorp` instruction (fixed via https://github.com/dotnet/runtime/pull/107210)

**Comment by janvorli** [comment] 2024-08-30 21:26
The issue was caused by the fact that the invalid instruction error code was not one of the ones recognized in the ExceptionHandling.cs. After just adding that, it prints:

```
<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>
0
Fatal error. System.InvalidOperationException: Illegal instruction
   at Program.Main()
```

Does the InvalidOperationException sound good enough or should we use a different exception class?

**Comment by jkotas** [comment] 2024-08-30 21:45
`InvalidOperationException` indicates a problem in the calling code. It is the case here.

I think it should be either `Fatal error. Illegal instruction` or `Fatal error. System.ExecutionEngineException: Illegal instruction

**Closed** 2024-09-21 07:29 UTC
Labels: area-ExceptionHandling-coreclr, in-pr
