### ISSUE TITLE
WindowsIdentity.RunImpersonated sending wrong credentials

### ISSUE THREAD

**Issue by koikin** [dotnet/runtime#38414] opened 2020-06-25 06:41 UTC
Hi all!
I'm using windows authentication to  impersonate my request to the api like this:

```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddRazorPages();
    services.AddServerSideBlazor();
    services.AddHttpClient<ApiRequests>(c =>
    {
        c.BaseAddress = new Uri(Configuration.GetSection("ApiUrl").Value);
        c.DefaultRequestHeaders.Add("Accept", "application/vnd.github.v3+json");
        c.DefaultRequestHeaders.Add("User-Agent", "HttpClientFactory-Sample");
    })
    .ConfigurePrimaryHttpMessageHandler(() =>
    {
        return new HttpClientHandler()
        {
            UseDefaultCredentials = true
        };
    });

    services.AddHttpContextAccessor();
    services.AddAuthentication();
}
```
On the API side I just get the identity with HttpContextAccessor.
```c#
public int GetUser()
{
    return _context.User.SingleOrDefault(e => e.Name == _httpContextAccessor.HttpContext.User.Identity.Name);
}
```

This works fine as long as only one user is signed in and makes the calls to the API.
But when two users are making calls.
User 1 is sometime receive user 1 data and sometime user 2 data same with User 2.
Debugging inside RunImpersonated with WindowsIdentity.GetCurrent() shows always the correct user. 
But the API is not always receiving the correct user.
```c#
public async Task<User> GetUser()
{
    return await WindowsIdentity.RunImpersonated(_identity.AccessToken, async () =>
    {
        var user = new User();
        string url = "api/User";
    
        var response = await client.GetAsync(url);
        if (response.IsSuccessStatusCode)
        {
            string responseStream = await response.Content.ReadAsStringAsync();
            user = JsonConvert.DeserializeObject<User>(responseStream);
        }
        return user;
    });
}
```
Creating and disposing HttpClient for each api call works as expected but not recommended.
```c#
using (var client = new HttpClient(new HttpClientHandler() { UseDefaultCredentials = true }))
{
    client.DefaultRequestHeaders.Add("Accept", "application/vnd.github.v3+json");
    client.DefaultRequestHeaders.Add("User-Agent", "HttpClientFactory-Sample");

    var response = await client.GetAsync(url);
    if (response.IsSuccessStatusCode)
    {
        string responseStream = await response.Content.ReadAsStringAsync();
        user = JsonConvert.DeserializeObject<User>(responseStream);
    }
};
```
I'm running the api and blazor web on the same server but on different app pool.
Both are using .NetCore 3.1
Is this a bug or am I doing it the wrong way?

**Comment by danmosemsft** [comment] 2020-06-26 00:09
@scalablecory any thoughts about which area this should go?

**Comment by scalablecory** [comment] 2020-06-26 01:31
@koikin can you please try with a .NET 5 preview? This was fixed in https://github.com/dotnet/runtime/pull/303. Thanks.

**Comment by scalablecory** [comment] 2020-06-26 01:33
Duplicate of #30307

**Comment by koikin** [comment] 2020-06-26 11:45
Thanks for the quick reply.

I upgraded to v5.0.0-preview.6

And got the following error when impersonating with
`_identity = (WindowsIdentity)httpContextAccessor.HttpContext.User.Identity;`
or
`_identity = WindowsIdentity.GetCurrent()`

Error: System.ComponentModel.Win32Exception (0x80090308): The token supplied to the function is invalid

Any ideas?

**Comment by scalablecory** [comment] 2020-06-26 12:40
@koikin can you give a full stack trace? I can't reproduce that.

**Comment by koikin** [comment] 2020-06-26 12:52
```
blazor.server.js:19 [2020-06-26T12:51:42.778Z] Error: System.ComponentModel.Win32Exception (0x80090308): The token supplied to the function is invalid
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatusPal& statusCode)
   at System.Net.NTAuthentication.GetOutgoingBlob(String incomingBlob)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts, CancellationToken callerToken, Int64 timeoutTime)
   at AppDeployBlazor.StaticCalls.ApiRequests.<>c__DisplayClass6_0.<<MakeRequest>b__0>d.MoveNext() in C:\Repositories\Git\VitecAppDeploy\src\AppDeplayBlazor\StaticCalls\ApiRequests.cs:line 48
--- End of stack trace from previous location ---
   at AppDeployBlazor.StaticCalls.ApiRequests.MakeRequest(String url) in C:\Repositories\Git\VitecAppDeploy\src\AppDeplayBlazor\StaticCalls\ApiRequests.cs:line 46
   at AppDeployBlazor.StaticCalls.ApiRequests.GetPinnedCustomer() in C:\Repositories\Git\VitecAppDeploy\src\AppDeplayBlazor\StaticCalls\ApiRequests.cs:line 128
   at AppDeployBlazor.Components.IndexLogic.OnInitializedAsync() in C:\Repositories\Git\VitecAppDeploy\src\AppDeplayBlazor\Data\IndexLogic.cs:line 43
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

**Comment by alnikola** [comment] 2020-07-30 15:08
@koikin Is there any proxies between the client and the server? To use Windows authentication, you need a strong client to server connection affinity which can get broken by a proxy. Please take a look at very similar issue #13160

@karelz @Tratcher That similar issue with Windows auth failing to go through proxy was [closed as "by design"](https://github.com/dotnet/aspnetcore/issues/13160#issuecomment-521710206). The justification there seems reasonable, so if we confirm the proxy presence here as well, should it be also closed due to the same reason?

>Well, given that kerberos/Windows authentication is meant for INTRANETS and you don't really ever want kerberos tokens going wild over the internet due to security concerns you shouldn't be needing a proxy or load balancer at all.
>
>(I'm now aware we need to call this out in the docs. I had just assumed this was common knowledge.)

>That's an architectural discussion outside of our control or knowledge I'm afraid. Either the load balancer does the authentication and then passes the user details down in a header which you then pick apart (custom code for custom configurations), or you switch to ADFS 2019 and OIDC, and bounce people through that. Bonus here is that'd work with cloud migrations too.

**Comment by alnikola** [comment] 2020-08-05 15:16
@koikin Could you please comment on the above question? We need additional information to proceed with this issue.

**Comment by karelz** [comment] 2020-08-10 09:56
Looks like external problem, not something we can change. Closing.
Feel free to reopen if there is evidence we misunderstood the scenario / root cause.

**Closed by karelz** 2020-08-10 09:56 UTC
Labels: area-System.Net.Http, needs more info
