### ISSUE TITLE
Test failure: System.Xml.Tests.TwoTextNodeTests.Text_SignificantWhitespace

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#45324] opened 2020-11-30 00:41 UTC
failed in job: https://dev.azure.com/dnceng/public/_build/results?buildId=902210&view=ms.vss-test-web.build-test-results-tab&runId=28811558&resultId=134452&paneView=debug

net6.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.ServerRS5.Open

Error message
~~~
System.NullReferenceException : Object reference not set to an instance of an object.

Stack trace
   at System.Reflection.IntrospectionExtensions.GetTypeInfo(Type type) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/IntrospectionExtensions.cs:line 13
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext() in /_/src/libraries/System.Linq/src/System/Linq/Select.cs:line 186
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext() in /_/src/libraries/System.Linq/src/System/Linq/Where.cs:line 391
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer) in /_/src/libraries/System.Linq/src/System/Linq/Contains.cs:line 23
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value) in /_/src/libraries/System.Linq/src/System/Linq/Contains.cs:line 11
   at System.Xml.Tests.TestHelper.VerifySiblings(XmlNode refChild, XmlNode newChild, InsertType insertType) in /_/src/libraries/System.Private.Xml/tests/XmlDocument/XmlNodeTests/InsertTests/TestHelper.cs:line 169
   at System.Xml.Tests.TwoTextNodeTests.TwoTextNodeBase(XmlDocument xmlDocument, InsertType insertType, XmlNodeType nodeType) in /_/src/libraries/System.Private.Xml/tests/XmlDocument/XmlNodeTests/InsertTests/TwoTextNodeTests.cs:line 41
   at System.Xml.Tests.TwoTextNodeTests.TwoTextNodeBase(XmlNodeType[] nodeTypes, InsertType insertType, XmlNodeType nodeType) in /_/src/libraries/System.Private.Xml/tests/XmlDocument/XmlNodeTests/InsertTests/TwoTextNodeTests.cs:line 62
   at System.Xml.Tests.TwoTextNodeTests.Text_SignificantWhitespace() in /_/src/libraries/System.Private.Xml/tests/XmlDocument/XmlNodeTests/InsertTests/TwoTextNodeTests.cs:line 114
~~~

**Comment by danmosemsft** [comment] 2020-11-30 01:16
dupe of https://github.com/dotnet/runtime/issues/45317

**Closed by danmosemsft** 2020-11-30 01:16 UTC
Labels: area-System.Xml, untriaged
