### ISSUE TITLE
Decompression Streams reading beyond compressed data.

### ISSUE THREAD

**Issue by Grille** [dotnet/runtime#84299] opened 2023-04-04 13:50 UTC
### Description

Firstly I’m not sure if this is a bug or by design, either way its bad.

I have the problem that the Built-in compression stream are reading over the actual compressed data.
this makes it impossible to know where further data behind the compressed block begins.
It’s about DeflateStream, GZipStream and BrotliStream.

### Reproduction Steps

```
using System.IO.Compression;
// Deflate is interchangeable with GZip and Brotli
// setup
var data = new byte[] { 1, 2, 3, 4, 5, 6 };
var stream = new MemoryStream();
void printpos() => Console.WriteLine($"len: {stream.Length} pos: {stream.Position}");

// write
printpos();
stream.Write(data, 0, 2);
printpos(); // pos 2
using (var compressor = new DeflateStream(stream, CompressionMode.Compress, true))
    compressor.Write(data, 2, 2);
printpos(); // DeflateStream writes 4 bytes here, pos is 6;
stream.Write(data, 4, 2);
printpos(); // pos 8

// reset
stream.Seek(0, SeekOrigin.Begin);
Array.Clear(data, 0, data.Length);

// read
printpos();
stream.Read(data, 0, 2);
printpos(); // pos 2
using (var decompresser = new DeflateStream(stream, CompressionMode.Decompress, true))
    decompresser.Read(data, 2, 2);
printpos(); // DeflateStream reads 6 bytes here, pos is 8 (end of stream); <---------------- bad
stream.Read(data, 4, 2);
printpos(); // reads empty

// result { 1, 2, 3, 4, 0, 0 };
for (int i = 0; i < data.Length; i++)
    Console.WriteLine(data[i]);
```

### Expected behavior

The decompression stream either stops advancing the base stream after reaching the end of compressed data, or it exposes a property that says how much bytes where actually read & decompressed, so you can seek the point to continue yourself.

### Actual behavior

Decompressor reads/advances base-stream beyond compressed data.

### Regression?

Same in all versions as far as im aware.

### Known Workarounds

A workaround I have is to prefix the compressed section with the number of bytes.
That way I can later copy just the compressed bytes to the decompressor, or calculate the position to continue.
But that’s only works for data formats, I’m writing myself.
If I want to read an deflate block from a file that don’t specify the size and also has data behind the compressed data I’m out of luck.

### Configuration

tested with Net4.5, NetStandard2.1 and Net7

### Other information

I came across this:
https://stackoverflow.com/questions/46238944/read-a-deflate-stream-until-adler32-checksum

Here Mark Adler himself says in a comment that it looks like deflate doesn’t stops as soon as it reaches the adler32 checksum as its supossed to, and is as such useless (at least as long not the whole file is compressed).

**Comment by stephentoub** [comment] 2023-04-04 14:19
Thanks. Duplicate of https://github.com/dotnet/runtime/issues/73770

**Comment by carlossanlop** [comment] 2023-05-03 17:02
Duplicate of https://github.com/dotnet/runtime/issues/73770

**Closed by carlossanlop** 2023-05-03 17:02 UTC
Labels: area-System.IO.Compression, untriaged
