### ISSUE TITLE
System.MissingMethod.Exception when using static abstract method

### ISSUE THREAD

**Issue by jdbruner** [dotnet/runtime#63411] opened 2022-01-05 21:01 UTC
### Description

Attempting to access an interface that contains a (6.0 preview feature) static abstract method and some other static member (such as a string field) causes System.MissingMethod.Exception to be thrown for the abstract method when the program starts up.

### Reproduction Steps

IXyzzy foo = new Xyzzy();
Xyzzy.Plugh();

interface IXyzzy
{
    static string plugh = "plugh";
    static abstract void Plugh();
}

class Xyzzy : IXyzzy
{
    public static void Plugh() =>
        Console.WriteLine($"a hollow voice says \\"{IXyzzy.plugh}\\"");
}

### Expected behavior

Expected behavior is that the class that implements the interface can be converted to the interface type and the program will run successfully to completion.

### Actual behavior

Unhandled exception. System.MissingMethodException: Method not found: 'Void IXyzzy.Plugh()'.
   at Program.\<Main\>$(String[] args)

It works as expected if IXyzzy.plugh is redefined as a "const string" instead of a "static string".

### Regression?

This is a new (preview) feature, so this is not a regression.

### Configuration

.NET 6.0 (EnablePreviewFeatures is true)
Windows 11 - x64

**Comment by wzchua** [comment] 2022-01-06 04:23
Dupe of https://github.com/dotnet/runtime/issues/59432

**Comment by AaronRobinsonMSFT** [comment] 2022-04-24 21:05
@trylek Is it possible this has regressed since #59432 was fixed?

**Comment by trylek** [comment] 2022-04-25 18:00
@AaronRobinsonMSFT - according to the issue description and considering the timeline I would rather guess that the author of this issue was testing a .NET 6 preview without my fix. Please note that I fixed the bug by the end of last September i.e. after .NET 6 shipped and, as it's more or less a corner case in a preview feature, it was never considered for porting to .NET 6 servicing. Please also note that I merged in a regression test for the issue as part of the fix and according to my knowledge it's still passing.

@jdbruner, could you please comment whether you've been able to get rid of the bug by switching over to .NET 7 Preview 1? I believe the fix has been there since the first preview.

**Comment by trylek** [comment] 2022-06-20 19:58
There has been no traffic on this PR for almost two months. According to my response I believe the issue has been fixed in .NET 7, the only problem is that, in .NET 6, static virtual methods only shipped as a preview so the fix hasn't met the bar for backporting to .NET 6. At this point I'm not aware of any indication that this bug still persists in .NET 7, closing this until proven otherwise.

**Closed by trylek** 2022-06-20 19:58 UTC
Labels: area-TypeSystem-coreclr
