### ISSUE TITLE
Performance regression with System.Numerics.Vector when retargeting from .NET 7 to .NET 8

### ISSUE THREAD

**Issue by pkulikov** [dotnet/runtime#94920] opened 2023-11-17 13:57 UTC
We're observing performance regression when retargeting one of our apps from .NET 7 to .NET 8. Screenshot is of the test app:
![image](https://github.com/dotnet/runtime/assets/15279990/c8f016c2-d2cc-4568-8e37-192861c562e6)

The processing logic sits in the project that targets .NET 6 and **uses SIMD** (in the form of `System.Numerics.Vector`) for the essential calculations. The client app has been retargeted from .NET 7 to .NET 8.

The archive with the test app to reproduce the behavior is attached (or you can check the code snippets below):
[PerformanceRegression.zip](https://github.com/dotnet/runtime/files/13392131/PerformanceRegression.zip)

<details><summary>Code of the test app</summary>
<p>

The processing logic targets .NET 6.
*Lib.csproj*:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
```

Processing is essentially a calculation of the maximum of absolute piecewise differences between two arrays (**important:** the results are shown for the case of `Vector.IsHardwareAccelerated` being `true`).

*Calculator.cs*:
```csharp
using System.Numerics;

namespace Lib;

public static class Calculator
{
    public static IEnumerable<double> CalculatePairwiseMaxDifferences(double[][] data)
    {
        var result = new List<double>(capacity: data.Length * data.Length);

        for (int i = 0; i < data.Length; i++)
        {
            var one = data[i];
            for (int j = 0; j < data.Length; j++)
            {
                var another = data[j];
                var r = CalculateMaximumAbsoluteDifference(one, another);
                result.Add(r);
            }
        }

        return result;
    }

    private static double CalculateMaximumAbsoluteDifference(double[] one, double[] another)
    {
        if (Vector.IsHardwareAccelerated)
        {
            Vector<double> maxes = Vector<double>.Zero;

            int i = 0;
            int lastBlockIndex = another.Length - (another.Length % Vector<double>.Count);

            while (i < lastBlockIndex)
            {
                maxes = Vector.Max(
                    maxes,
                    Vector.Abs(Vector.Subtract(
                        left: new Vector<double>(another, i),
                        right: new Vector<double>(one, i))));

                i += Vector<double>.Count;
            }

            var result = 0.0;
            for (int n = 0; n < Vector<double>.Count; n++)
            {
                if (maxes[n] > result)
                {
                    result = maxes[n];
                }
            }

            while (i < another.Length)
            {
                var abs = Math.Abs(another[i] - one[i]);
                if (abs > result)
                {
                    result = abs;
                }
                i += 1;
            }

            return result;
        }
        else
        {
            var result = 0.0;
            for (int i = 0; i < another.Length; i++)
            {
                var abs = Math.Abs(another[i] - one[i]);
                if (abs > result)
                {
                    result = abs;
                }
            }
            return result;
        }
    }
}
```

The client app targets .NET 7 and .NET 8 (for comparison). (When running without server GC, the performance regression is still present.)
*MyApp.csproj*:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net7.0;net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lib\Lib.csproj" />
  </ItemGroup>

</Project>
```

*Program.cs*:
```csharp
using System.Diagnostics;
using Lib;

namespace MyApp;

internal class Program
{
    static void Main(string[] args)
    {
        var warmup = GenerateData(count: 10);
        var throwaway = Calculator.CalculatePairwiseMaxDifferences(warmup);

        var data = GenerateData(count: 1600);

        Console.WriteLine("Starting calculations...");
        var sw = Stopwatch.StartNew();

        var result = Calculator.CalculatePairwiseMaxDifferences(data);

        Console.WriteLine($"Calculations took: {sw.Elapsed.TotalMilliseconds:F0} ms");
        Console.ReadLine();
    }

    private static double[][] GenerateData(int count)
    {
        const int Length = 3600;
        const double Radius = 320.0;
        var rand = Random.Shared;

        var data = new double[count][];
        for (int i = 0; i < count; i++)
        {
            var row = new double[Length];
            for (int j = 0; j < Length; j++)
            {
                row[j] = Radius + 2 * (rand.NextDouble() - 0.5);
            }
            data[i] = row;
        }
        return data;
    }
}
```

</p>
</details> 

Looks like this is related to `System.Numerics.Vector` operations. When I replace the following line:
```csharp
if (Vector.IsHardwareAccelerated)
```
with 
```csharp
if (false)
```
that is, effectively switching to the naïve `for` loop, results turn around:
![image](https://github.com/dotnet/runtime/assets/15279990/7944edbc-8de2-419b-ade2-4379d83220be)

Comparing with the first screenshot, we're getting one more observation. The effect of using SIMD is significantly greater in .NET 7 (10.5 sec -> 4.4 sec) than in .NET 8 (7.3 sec -> 5.2 sec)

Is this expected or there is an issue with the test app?

<details><summary>System info</summary>
<p>

Information about the runtimes (all runtimes are installed by Visual Studio 2022):
```text
.NET 7.0 : .NET 7.0.14 (7.0.1423.51910), X64 RyuJIT AVX2
.NET 8.0 : .NET 8.0.0 (8.0.23.53103), X64 RyuJIT AVX2
```

Presented results are obtained on a laptop with Windows:
![image](https://github.com/dotnet/runtime/assets/15279990/e4bcbe15-e953-46e0-a67c-edbe99cbb2fe)
![image](https://github.com/dotnet/runtime/assets/15279990/020b73be-1361-4c5b-beed-8ec2235e1efd)
![image](https://github.com/dotnet/runtime/assets/15279990/d21f991d-503a-42dc-8190-099aa07fd221)

</p>
</details>

**Comment by tannergooding** [comment] 2023-11-17 15:57
Notably a single invocation isn't enough to guarantee warmup. You should really use something like [dotnet/Benchmarkdotnet](https://github.com/dotnet/BenchmarkDotNet) to ensure that all aspects of tiering are properly accounted for, especially across versions of .NET

It doesn't look to be impactful in this particular case, but it can in others and so it's a recommendation we always try to call out

---------------

The codegen for `CalculatePairwiseMaxDifferences` hasn't changed. The exact registers used have, but the codegen is otherwise identical

The codegen for `CalculateMaximumAbsoluteDifference` has changed, however. This is most notably because the last of the legacy SIMD handling was removed, including the specialized importation of `new Vector<T>(T[] values, int index)`.

In .NET 7, this was handled [here](https://github.com/dotnet/runtime/blob/v7.0.14/src/coreclr/jit/simd.cpp#L2084-L2223) as `SIMDInitArrayX` which required some very complex and verbose manual IR creation to represent the full operations.

In .NET 8, the API is no longer considered intrinsic and just directly imports the equivalent C# code: https://github.com/dotnet/runtime/blob/479df4792daa147e9b51757b0fabc248df21264f/src/libraries/System.Private.CoreLib/src/System/Numerics/Vector_1.cs#L76-L86
```csharp
public Vector(T[] values, int index)
{
    // We explicitly don't check for `null` because historically this has thrown `NullReferenceException` for perf reasons

    if ((index < 0) || ((values.Length - index) < Count))
    {
        ThrowHelper.ThrowArgumentOutOfRange_IndexMustBeLessOrEqualException();
    }

    this = Unsafe.ReadUnaligned<Vector<T>>(ref Unsafe.As<T, byte>(ref values[index]));
}
```

This results in quite a bit larger codegen as the JIT can't recognize that `values[index]` is definitely in range and so it emits what is effectively double bounds checks.

This pessimization could somewhat be mitigated by using something like the following instead, as it manually bypasses the bounds checks:
`return Unsafe.ReadUnaligned<Vector<T>>(ref Unsafe.As<T, byte>(ref Unsafe.Add(ref MemoryMarshal.GetArrayDataReference(values), index)));`

However, it doesn't' entirely solve the problem as the JIT still doesn't recognize the general condition as being equivalent to a `GT_BOUNDS_CHECK` and so it doesn't trigger the same overall optimization set.

In general this higher level issue (manual bounds checks being less efficient) is tracked by https://github.com/dotnet/runtime/issues/80256.

---------------

Notably the emitted code, in general, has bounds checks in other places as well and you'd likely see significantly better perf by manually handling things. This does involve writing "unsafe" code and using either pointers or byrefs, however.

Current:
```
.NET 7: 3045 ms
.NET 8: 3367 ms
```

After (switching to use `Vector.LoadUnsafe(ref readonly T source, nuint index)` or equivalent):
```
.NET 7: 2911 ms
.NET 8: 2863 ms
```

**Comment by tannergooding** [comment] 2023-11-17 15:59
CC. @AndyAyersMS, this issue is a good representation of where unsafe code currently feels "necessary" for performance

If we were to resolve https://github.com/dotnet/runtime/issues/80256 and correspondingly be able to recognize the general pattern that `new Vector(T[] values, int index)` is using without needing to treat it as intrinsic, then it would be much more viable for users to write the natural and safe equivalent.

**Comment by pkulikov** [comment] 2023-11-20 15:55
@tannergooding thank you for the explanations and recommendations

**Comment by tannergooding** [comment] 2024-02-04 04:26
Closing this, as the issue is tracked by other existing issues.

**Closed by tannergooding** 2024-02-04 04:26 UTC
Labels: area-System.Numerics, tenet-performance, untriaged
