### ISSUE TITLE
one thread allocate too many object will effect other threads work

### ISSUE THREAD

**Issue by egmkang** [dotnet/runtime#34863] opened 2020-04-12 08:56 UTC
![5](https://user-images.githubusercontent.com/65175/79064577-a587a100-7cdc-11ea-80a0-867b55eefcab.png)

in this thread, a lot of **mongodb writing operation** will be executed. it seems like mongodb C# driver is not a well design library, it allocate too many objects.

and this cause computation intensive part (of my application) runs very slow.

my appliance has many Producer Consumer Work, such as sending a message over DotNetty, writing to mongodb over DBWorkerThread.

if the worker thread allocate many object inescapably(i cannot rewrite mongodb's client driver, and dotnetty), and effect the other threads. it seems like i cannot use .net core writing complex system, or i can only use it writing light loading application.

I look forward to your help. thanks a lot.

**Comment by danmosemsft** [comment] 2020-04-12 19:02
It seems this is a bug report for the mongodb driver? @roji thoughts?

**Comment by roji** [comment] 2020-04-12 19:23
@egmkang thanks for submitting this. If I'm understanding you correctly, you're saying that your usage of the MongoDB driver creates an unexpectedly huge amount of allocations, leading to very high CPU usage? And that this slows down your other threads which are attempting to do computation?

If so, this indeed sounds like an issue to be raised with the MongoDB people, but are you able to reproduce this MongoDB behavior with a minimal code sample? This would assist us (and them) to understand exactly what's going on.

/cc @vincentkam from MongoDB, does this ring any bells?

**Comment by egmkang** [comment] 2020-04-13 02:42
@roji I mean, not all libraries are well designed, can GC make some improvements in this case? there are a lot object that used for only one time, in C++/Rust they have RAII and libc's object pool, objects allocated on the heap is a little problem.

but in .net, we can only rely on GC, or rewite library using ArrayPool or something, that is hard and a lot of work.

**Comment by davidfowl** [comment] 2020-04-13 03:47
Well the GC can only do so much, sometimes libraries need to do the work. We should improve both but it would be better to improve the mongodb library so that everyone wins (esp older platforms that don’t have those GC improvements)

**Comment by egmkang** [comment] 2020-04-13 06:21
@davidfowl 
thanks to reply. 
my application have 24 logic thread  processing game message, and 16-32 thread writing MongoDB operation. the writing operation is using `block api`, not async's, the most is `IMongoCollection.UpdateOne`.  i used UpdateMany, it seems not fix this problem.

![6](https://user-images.githubusercontent.com/65175/79096784-a2e68380-7d90-11ea-9f0d-3eff85f0cf93.png)

now, i'm not sure the real problem is allocate too much object or block api. but it looks like when writing qps > 2500, the problem appears. now i can make writing smoothly.

i will try to find the real problem when i have some space time. already worked for 15 days to fix the performance problems(there is other problem).

thanks

**Comment by egmkang** [comment] 2020-04-13 07:54
i change the gc mode to ServerGC, it looks like better now.  up to 4700 qps writing looks good. 

workstation gc is not good. in my complex case, it cannot work well.

**Comment by vincentkam** [comment] 2020-04-16 20:05
Thanks @roji  for looping me in!
Hello @egmkang,

I'm one of the maintainers of the MongoDB C#/.NET Driver, and I'm sorry to hear that you're experiencing performance issues while using the driver.

As @roji noted, a reproduction with a minimal code sample would be very helpful! :) Without more details, I'm unable to offer a theory as to why your application might be seeing a spike in allocations at around 2500 queries per second, other than to offer the general observation that as the number of queries executed per second grows, the number of objects the driver needs to create to execute those queries will also grow.

I'm glad to hear that you've found a workaround by using server GC, which to my limited understanding is designed for higher throughput.

**Comment by stephentoub** [comment] 2020-04-17 20:31
Thanks, @vincentkam.  What's the best repo for @egmkang to open an issue in for MongoDB?

**Comment by vincentkam** [comment] 2020-04-17 20:53
@stephentoub @egmkang 
The MongoDB .NET/C# Driver GitHub repo can be found [here](https://github.com/mongodb/mongo-csharp-driver), and the best place to open an issue would in the [CSHARP](https://jira.mongodb.org/browse/csharp) project on MongoDB's [Jira](https://jira.mongodb.org)! 😸

**Comment by stephentoub** [comment] 2020-04-17 20:54
Thanks.  I'll close this and it can be tracked there.  If there turns out to be a dotnet/runtime issue, this can be re-opened with the additional details.

**Closed by stephentoub** 2020-04-17 20:54 UTC
Labels: area-System.Threading, tenet-performance, tracking-external-issue
