### ISSUE TITLE
[API Proposal]: Expand data validation attributes

### ISSUE THREAD

**Issue by geeknoid** [dotnet/runtime#77402] opened 2022-10-24 20:38 UTC
### Background and motivation

Our project features hundreds of different option types against which we perform data validation operations. We've introduced a number of new data validation attributes which capture essential scenarios in our code. As these are general-purpose in nature, it would be great to add those to the core set of supported attributes.

### API Proposal

```diff
namespace System.ComponentModel.Annotations;

public partial class RangeAttribute : ValidationAttribute
{
+    public bool IsLowerBoundExclusive { get; set; } = false;
+    public bool IsUpperBoundExclusive { get; set; } = false;
}

public partial class RequiredAttribute : ValidationAttribute
{
     // Fail validation for structs that equal the default value for the type
+    public bool DisallowDefaultValues { get; set; } = false;
}

// Validates that the specified string uses Base64 encoding
+[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter, AllowMultiple = false)]
+public class Base64StringAttribute : ValidationAttribute
+{
+}

// Specifies length ranges for string/IEnumerable
+[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter, AllowMultiple = false)]
+public class LengthAttribute : ValidationAttribute
+{
+    public LengthAttribute(int minLength = 0, int maxLength = -1);
+
+    public int MinLength { get; }
+    public int? MaxLength { get; }
+}

// Validation using allow and deny lists
+[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter, AllowMultiple = false)]
+public class AllowedValuesAttribute : ValidationAttribute
+{
+    public AllowedValuesAttribute (params object[] allowedValues);
+    public object[] AllowedValues { get; }
+}
+
+[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter, AllowMultiple = false)]
+public class DeniedValuesAttribute : ValidationAttribute
+{
+    public DeniedValuesAttribute(params object[] deniedValues);
+    public object[] DeniedValues { get; }
+}
```

<details>
<summary>Original API proposal</summary>

```csharp
namespace System.ComponentModel.Annotations;

/// <summary>
/// Marks a property to be validated as <see href="https://en.wikipedia.org/wiki/Base64">Base64</see> string.
/// </summary>
[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter, AllowMultiple = false)]
public sealed class Base64StringAttribute : ValidationAttribute
{
}

/// <summary>
/// Provides exclusive boundary validation for <see cref="long"/> or <see cref="double"/> values.
/// </summary>
[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter, AllowMultiple = false)]
public sealed class ExclusiveRangeAttribute : ValidationAttribute
{
    /// <summary>
    /// Gets the minimum value for the range.
    /// </summary>
    public object Minimum { get; }

    /// <summary>
    /// Gets the maximum value for the range.
    /// </summary>
    public object Maximum { get; }

    /// <summary>
    /// Initializes a new instance of the <see cref="ExclusiveRangeAttribute"/> class.
    /// </summary>
    /// <param name="minimum">The minimum value, exclusive.</param>
    /// <param name="maximum">The maximum value, exclusive.</param>
    public ExclusiveRangeAttribute(int minimum, int maximum);

    /// <summary>
    /// Initializes a new instance of the <see cref="ExclusiveRangeAttribute"/> class.
    /// </summary>
    /// <param name="minimum">The minimum value, exclusive.</param>
    /// <param name="maximum">The maximum value, exclusive.</param>
    public ExclusiveRangeAttribute(double minimum, double maximum);
}

/// <summary>
/// Specifies the minimum length of any <see cref="IEnumerable"/> or <see cref="string"/> objects.
/// </summary>
/// <remarks>
/// The standard <see cref="MinLengthAttribute" /> supports only non generic <see cref="Array"/> or <see cref="string"/> typed objects
/// on .Net Framework, while <see cref="ICollection{T}"/> type is supported only on .Net Core.
/// See issue here <see href="https://github.com/dotnet/runtime/issues/23288"/>.
/// This attribute aims to allow validation of all these objects in a consistent manner across target frameworks.
/// </remarks>
[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter, AllowMultiple = false)]
public sealed class LengthAttribute : ValidationAttribute
{
    /// <summary>
    /// Gets the minimum allowed length of the collection or string.
    /// </summary>
    public int MinimumLength { get; }

    /// <summary>
    /// Gets the maximum allowed length of the collection or string.
    /// </summary>
    public int? MaximumLength { get; }

    /// <summary>
    /// Gets or sets a value indicating whether the length validation should exclude the <see cref="MinimumLength"/> and <see cref="MaximumLength"/> values.
    /// </summary>
    /// <remarks>
    /// By default the property is set to <c>false</c>.
    /// </remarks>
    public bool Exclusive { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="LengthAttribute"/> class.
    /// </summary>
    /// <param name="minimumLength">
    /// The minimum allowable length of array/string data.
    /// Value must be greater than or equal to zero.
    /// </param>
    public LengthAttribute(int minimumLength);

    /// <summary>
    /// Initializes a new instance of the <see cref="LengthAttribute"/> class.
    /// </summary>
    /// <param name="minimumLength">
    /// The minimum allowable length of array/string data.
    /// Value must be greater than or equal to zero.
    /// </param>
    /// <param name="maximumLength">
    /// The maximum allowable length of array/string data.
    /// Value must be greater than or equal to zero.
    /// </param>
    public LengthAttribute(int minimumLength, int maximumLength);
}

/// <summary>
/// Provides a way of requiring a value that is not default(T) for a property of value type.
/// </summary>
/// <remarks>Only to be used with value type properties.</remarks>
[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field, AllowMultiple = false)]
public sealed class NonDefaultValueRequiredAttribute : ValidationAttribute
{
}

/// <summary>
/// Provides a way of not accepting specific values for a property/field/parameter.
/// </summary>
[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter, AllowMultiple = false)]
public sealed class RejectedValuesAttribute : ValidationAttribute
{
    /// <summary>
    /// Gets the values which are not accepted.
    /// </summary>
    public ICollection<object> RejectedValues { get; }

    /// <summary>
    /// Initializes a new instance of the <see cref="RejectedValuesAttribute"/> class.
    /// </summary>
    /// <param name="rejectedValues">Values which should not be accepted.</param>
    public RejectedValuesAttribute(params object[] rejectedValues);
}

/// <summary>
/// Provides a way of accepting only specific values for a property/field/parameter.
/// </summary>
[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter, AllowMultiple = false)]
public sealed class AcceptedValuesAttribute : ValidationAttribute
{
    /// <summary>
    /// Gets the values which are accepted.
    /// </summary>
    public ICollection<object> AcceptedValues { get; }

    /// <summary>
    /// Initializes a new instance of the <see cref="AcceptedValuesAttribute"/> class.
    /// </summary>
    /// <param name="acceptedValues">Values which should be accepted.</param>
    public AcceptedValuesAttribute(params object[] acceptededValues);
}

/// <summary>
/// Provides boundary validation for <see cref="TimeSpan"/>.
/// </summary>
[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter, AllowMultiple = false)]
public sealed class TimeSpanAttribute : ValidationAttribute
{
    /// <summary>
    /// Gets the lower bound for time span.
    /// </summary>
    public TimeSpan Minimum { get; }

    /// <summary>
    /// Gets the upper bound for time span.
    /// </summary>
    public TimeSpan? Maximum { get; }

    /// <summary>
    /// Gets or sets a value indicating whether the time span validation should exclude the minimum and maximum values.
    /// </summary>
    /// <remarks>
    /// By default the property is set to <c>false</c>.
    /// </remarks>
    public bool Exclusive { get; set; }

    /// <summary>
    /// Initializes a new instance of the <see cref="TimeSpanAttribute"/> class.
    /// </summary>
    /// <param name="minMs">Minimum in milliseconds.</param>
    public TimeSpanAttribute(int minMs);

    /// <summary>
    /// Initializes a new instance of the <see cref="TimeSpanAttribute"/> class.
    /// </summary>
    /// <param name="minMs">Minimum in milliseconds.</param>
    /// <param name="maxMs">Maximum in milliseconds.</param>
    public TimeSpanAttribute(int minMs, int maxMs);

    /// <summary>
    /// Initializes a new instance of the <see cref="TimeSpanAttribute"/> class.
    /// </summary>
    /// <param name="min">Minimum represented as time span string.</param>
    public TimeSpanAttribute(string min);

    /// <summary>
    /// Initializes a new instance of the <see cref="TimeSpanAttribute"/> class.
    /// </summary>
    /// <param name="min">Minimum represented as time span string.</param>
    /// <param name="max">Maximum represented as time span string.</param>
    public TimeSpanAttribute(string min, string max);
}
```

### API Usage

```csharp
class Options
{
    // require a valid base-64 string
    [Base64String]
    public string EncodedBinaryData { get; set; } = string.Empty;

    // a value between specific exclusive boundaries
    [ExclusiveRange(0, 1.0)]
    public double BetweenZeroAndOne { get; set; } = .5;

    // 1 to 5 items
    [Length(1, 5)]
    public int[] ArrayOfStuff { get; set; }

    // anything but these
    [RejectValues("Red")]
    public string Color { get; set; }

    // 10ms to 100ms
    [TimeSpan(10, 100)]
    public TimeSpan Timeout { get; set; }
}
```

</details>

**Comment by ericstj** [comment] 2022-10-24 21:51
@geeknoid can you include the code samples that demonstrate where validation would happen?

**Comment by rafal-mz** [comment] 2022-10-24 22:01
@ericstj There is another issue that shows our source generated validators, which are using attributes mentioned in this issue:
https://github.com/dotnet/runtime/issues/77412

It would be also helpful to create an X509Certificate2 validation attribute. We have it in our backlog but unfortunately had no capacity to create it.

**Comment by ericstj** [comment] 2022-10-24 22:03
I see, it looks like that calls back into the validation infrastructure in System.ComponentModel.Annotations - so this isn't proposing any new consumers/entry-points for this validation - just some new attributes that use the existing mechanisms.

**Comment by ajcvickers** [comment] 2022-10-25 12:06
Validation attributes are not something we plan to invest any time in going forward. It is unlikely we will accept any changes in this area.

**Comment by danmoseley** [comment] 2022-10-25 18:27
@ajcvickers can you say more -- how did we end up with that perspective, was it resources, usefulness, or lack of adoption?

**Comment by danmoseley** [comment] 2022-10-25 18:30
Also, can you say more about the cost of additions like these? What are the costs beyond the attribute itself (including the validation method)?

**Comment by ajcvickers** [comment] 2022-10-26 09:13
@danmoseley Attributes in `System.ComponentModel.Annotations` (aka "Data Annotations") are used in two ways:

1. As validation attributes, through inheritance of `ValidationAttribute`, which, if implemented correctly can be used by any code that understands validation attributes without that code needing to be updated to consume the new attributes.
2. As directives to consuming code as to the semantics of the annotated member. So, for example U.I. components may look for the `KeyAttribute` and choose to make input read-only, or look at `StringLength` and restrict the U.I. from allowing more characters than specified. This is independent of the attribute's use for validation and relies on the consuming code understanding the semantics of the attribute.

Use in validation has a few problems:

1. The validation for any given attribute can never be changed without it breaking any application that uses it. So, for example, the behavior for allowing empty strings with `Required` is problematic in many cases, but can never be changed. Similarly, the attributes don't do recursive validation, which people often want, but can't be added by default without breaking.
2. Validation is not performed in places where people expect it to be. For example, people expect `JObject` to be validated, but it never is, and we can never change that without breaking existing applications.
3. The localization story for validation messages is not great.

The problems are worse when the attributes are consumed directly:

1. Different consumers have different interpretations of what the attributes mean. This leads to a situation where `MaxLength` is applied to a property, and one consumer interprets this as number of bytes in the string, while another interprets it as number of characters. This leads to, sometimes subtle, behavioral differences in the consumers which means using an attribute for one thing can easily break code somewhere else.
2. Some consumers respect (in whatever way they think that should be) some attributes but not others. This is again very confusing, because users can't understand why an attribute is working on one place but not another, or assume it is working somewhere it is not.
4. After a new attribute is added, consumers must react to add support for it. Legacy code that uses these attributes will never react, and code still under active development may or may not react, further fragmenting the story for application developers. 

It would be great for .NET to have a modern validation system that does not suffer from these issues. However, that has never been high enough priority to be funded, and last time I checked nobody is really interested in taking on and owning such a thing, since experience has shown the existing system to be such as can of worms. Beyond that, it doesn't seem wise to further add to the current system, beyond maintaining behavior that already exists.

**Comment by danmoseley** [comment] 2022-10-26 15:42
Thanks for writing all that up - I think it will be useful in future. @geeknoid I assume functionally everything works fine if you keep these attributes where you have them today.

**Comment by geeknoid** [comment] 2022-10-26 18:16
@danmoseley Unfortunately, no this is somewhat of a deal-breaker for the project we're on.

As we want to move many of our components into the core libraries, these components depend on all these attributes. If the attributes don't make it to the core of the platform, then we would need to rewrite our components to not depend on the attributes, which would be a lot of busy work leading to likely lower quality experience of our customers.

**Comment by geeknoid** [comment] 2022-10-26 18:21
@ajcvickers So if I'm reading your response correctly, you're basically saying that the current attribute-based validation model is broken in many ways, and you don't want to invest in expanding its feature set?

For our project, we have a lot of option types, and they are validated systematically using a code generator option validator, which leverages all the validation attributes in a reliable and predictable way. It has worked very well for us, and leads to high-quality state coming into our code, and high-quality errors being presented to the user.

**Comment by ajcvickers** [comment] 2022-10-26 18:26
> So if I'm reading your response correctly, you're basically saying that the current attribute-based validation model is broken in many ways, and you don't want to invest in expanding its feature set?

Yes.

> For our project, we have a lot of option types, and they are validated systematically using a code generator option validator, which leverages all the validation attributes in a reliable and predictable way. It has worked very well for us, and leads to high-quality state coming into our code, and high-quality errors being presented to the user.

That's great for a system used in a well-defined way by a private group of consumers. It's a different thing to add new attributes to the BCL where they will be available to all consumers of .NET who will have many different expectations and come up with many different ways of consuming the code. And especially since there is history around how this code should be consumed that goes beyond what you are doing.

**Comment by jeffhandley** [comment] 2022-10-28 00:16
> I know the libraries folks are currently adding README.md to each library indicating the kinds of changes they take. This one could probably benefit from one. @jeffhandley could you maybe point @ajcvickers at an example in the recommended format?

Yes, we've been adding them to lots of libraries the last couple weeks. The XML libraries is a good example: #77401

**Comment by jeffhandley** [comment] 2022-11-24 03:48
We have some updates on this that have been discussed via email--capturing them here too:

* We are going to invest in DataAnnotations during .NET 8
  * We are going to review these proposed attributes during the early stages of .NET 8
  * We will also reconsider past attribute proposals that have been punted or closed
  * There are some other DataAnnotations shortcomings and modernization opportunities we're discussing more, such as localization and possible source-generator based validation execution

Regarding these proposed attributes, I have some notes on the API shapes.

1. `Base64StringAttribute`
    * This would generally not be used for end-user UI scenarios, which makes it a bit unusual for DataAnnotations validator attributes
    * We should discuss if we want to be open to scenarios where the models being validated are not UI-oriented
    * There are plenty of other non-validation attributes in the namespace that are not UI-oriented
    * If we do open the door for those though, where will we draw the line? If we have a Base64String validator, would that inviteWellFormedJsonString or WellFormedXmlString?
2. `ExclusiveRangeAttribute`
    * This doesn't cover the scenario of only one of the minimum or maximum being exclusive
    * We should consider expanding `RangeAttribute` to enable the minimum and/or maximum to be exclusive
3. `LengthAttribute`
    * Other validation libraries I've implemented have supported attributes that are validator factories such that a single attribute can result in 0-N validators from being composed, even conditionally based on validation context
    * I've long wished we had taken that approach with DataAnnotations too, as `LengthAttribute` could literally just compose `MinLengthAttribute` and `MaxLengthAttribute`
    * Assuming we still don't pursue validator factories though, this seems like a reasonable attribute to add
    * We should consider adding `Exclusive` to `MinLengthAttribute` and `MaxLengthAttribute` too
4. `NonDefaultValueRequiredAttribute`
    * This should likely get special treatment like `RequiredAttribute` does, where it's validated in the first pass of validation before other value validators are invoked
    * `RequiredAttribute` already has `AllowEmptyStrings`; `AllowDefaultValue` (or something like it) could be considered as well
5. `RejectValuesAttribute`
    * This is essentially a "block list" validator; since block lists are often anti-patterns, I want to be cautious about this as a first-class validator
    * @geeknoid Can you elaborate on the scenarios for this one please?
    * I could imagine a different approach where we have something like `CompareValidator` but instead of comparing against another property, it compares against hard-coded value(s) with a comparison operator provided; we could also entertain expanding `CompareValidator` to allow the operator to be specified
6. `TimeSpanAttribute`
    * This can already be achieved with `[Range(typeof(TimeSpan), "<min-timespan-string>", "<max-timespan-string>")]`
    * If `RangeAttribute` offered properties for exclusive min/max, would that be sufficient?

With any changes to the existing attributes, such as adding properties to them, we do run the risk of incompatibility with app models that iterate over objects/properties/attributes and directly perform validation without going through `Validator` to do so. We will also need to think this through, do some discovery around where knowledge of these attributes has been baked in, and understand what that impact would be.

**Comment by En3Tho** [comment] 2022-11-24 06:55
Just my 2 cents but the thing that really prevents me from liking attribute approach is that there are no types to solidify this validation. After validation it's just a string. No context attached.

I believe it's better to invest in roles or other kind of cheap flexible types and their support in mappers. Maybe some kind of IValidatable<TValue, TValidator> ?

Other thing is full fledged contracts.

I wouldn't personally want to see BCL introduce more of these as they are now and push people in a wrong (in my opinion) direction.

**Comment by geeknoid** [comment] 2022-11-24 15:17
@jeffhandley Why is a block list an anti-pattern? Do they cause inherent problems? "Everything but X" can be substantially more concise than explicitly enumerating all values so it seems generally useful.

Regarding TimeSpanAttribute, I didn't realize this kind of thing was possible with the Range attribute. In our source base, we have a few uses of the overloads that accept an integer millisecond count, and a few uses of the Exclusive feature (so we can say "any timespan > 0"). We could easily convert the millisecond case to use the string form of the constructor. For the Exclusive case, if you expand Range attribute to support exclusive mode, then we'd be all set there.

**Comment by jeffhandley** [comment] 2022-12-01 02:47
> Why is a block list an anti-pattern? Do they cause inherent problems? "Everything but X" can be substantially more concise than explicitly enumerating all values so it seems generally useful.

Block Lists often connote that there's a finite list of possible values and some of those values are not permitted because they violate a business rule or can lead to unexpected behavior. In many contexts, this can lead to a false sense of security/safety, while a different value/permutation can just as easily lead to that unexpected state. With a finite list of possible values, an Allow List ensures only the known good states are permitted in the system, ensuring expected behavior. In any security-sensitive context, block lists are incredibly dangerous for this reason.

For a hypothetical scenario in a different context, we can imagine service configurations. A block list could be used to forbid a configuration of "development", "dev", "staging", etc. into a Production environment. But what would really be intended is to have an allow list of "production" or "prod" such that a configuration of "develop" or "local" would not be identified as valid.

This is clearly very context sensitive though, and there are certainly valid domain-specific block list scenarios. Allow lists should be used when feasible, and for those reasonable, domain-specific block list scenarios, I would recommend a domain-specific validator attribute. Such an approach encapsulates the business logic within the attribute by containing the allow-list/block-list approach and values within the validator without propagating the approach and values out to every reference site.

**Comment by geeknoid** [comment] 2022-12-05 14:37
@geeknoid I see your point, but I disagree.

To flip your argument around, imagine I have a feature that must never be used in production, but can be used anywhere else since it's for diagnostics. Applying a black list that says "anything goes except production" is a perfectly reasonable thing to do.

**Comment by jeffhandley** [comment] 2022-12-12 17:33
I worry that "anything goes except production" is even more dangerous than the scenario I listed out. If an environment was named "prod" instead of "production," then that could lead to diagnostics being turned on in production when not intended. Instead, an allow-list of environments within which diagnostics are allowed to be captured is much less likely to have a false-positive.

**Comment by geeknoid** [comment] 2022-12-12 20:40
A new use case came up lately which is a white list. A specification of the explicit set of values allowed. Kinda like Range, but for discrete values. I'd love to see an attribute for that too.

**Comment by eiriktsarpalis** [comment] 2022-12-13 19:14
@geeknoid would it be possible to include an API shape for that attribute in the original post. Just a rough sketch or link to an equivalent implementation would suffice.

**Comment by tekian** [comment] 2022-12-13 21:48
`[Range(typeof(TimeSpan), "<min-timespan-string>", "<max-timespan-string>")]`

This works. However it is arguably uglier to use and its internal implementation is playing [a guessing game](https://source.dot.net/#System.ComponentModel.Annotations/System/ComponentModel/DataAnnotations/RangeAttribute.cs,167) of how to compare a TimeSpan.

[R9's implementation](https://domoreexp.visualstudio.com/R9/_git/SDK?path=/src/Extensions/Data.Validation/TimeSpanAttribute.cs) works directly with the type and so the implementation can be more efficient.

**Comment by roji** [comment] 2022-12-13 22:50
Note that C# now supports [generic attributes](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-11.0/generic-attributes), so a generic Range attribute could be constrained to accept IComparable and simply accept two instances.

**Comment by roji** [comment] 2022-12-14 00:22
Thanks @svick, I missed that restriction..

**Comment by eiriktsarpalis** [comment] 2022-12-14 14:52
I held an offline conversation with @ajcvickers regarding the concerns that he expressed in https://github.com/dotnet/runtime/issues/77402#issuecomment-1291737278, namely the potential for extensions in existing attributes to break downstream consumers that provide their own validation implementations. We think that even though consumers would need to be updated so that the new configuration can be recognized, we don't believe this should manifest as a breaking change for annotations using the current configuration space. 

This means that we could add `ExclusiveRangeAttribute` functionality by exposing two new properties to the existing `RangeAttribute`:

```diff
public partial class RangeAttribute
{
+    public bool IsLowerBoundInclusive { get; set; } = true;
+    public bool IsUpperBoundInclusive { get; set; } = true;
}
```

Similarly, `NonDefaultValueRequiredAttribute` could be exposed as a property in `RequiredAttribute`:

```diff
public partial class RequiredAttribute
{
+    public bool DisallowDefaultValues { get; set; } = false;
}
```

**Comment by eiriktsarpalis** [comment] 2022-12-14 14:54
@geeknoid regarding the proposed `LengthAttribute`, shouldn't there be provision for the `MinimumLength` also being optional? It is conceivable that somebody might want to require string lengths up to a given upper bound.

**Comment by geeknoid** [comment] 2022-12-14 16:15
@eiriktsarpalis Yes, it would be conceivable to make minimum length optional. It just makes the constructors a tad more complicated.

**Comment by eiriktsarpalis** [comment] 2022-12-14 16:32
How about using just one ctor like so?
```C#
public LengthAttribute(int minLength = 0, int maxLength = -1)
{
      MinLength = minLength;
      MaxLength = maxLength < 0 ? null : maxLength;
}
```
Then you might be able to use it like so:
```C#
[LengthAttribute(5, 10)]
[LengthAttribute(minLength: 5)]
[LengthAttribute(maxLength:10)]
```

**Comment by eiriktsarpalis** [comment] 2022-12-20 15:29
Based on the conversation above, I was thinking we could make the following API additions:

```diff
namespace System.ComponentModel.Annotations;

public partial class RangeAttribute : ValidationAttribute
{
+    public bool IsLowerBoundInclusive { get; set; } = true;
+    public bool IsUpperBoundInclusive { get; set; } = true;
}

public partial class RequiredAttribute : ValidationAttribute
{
     // Fail validation for structs that equal the default value for the type
+    public bool DisallowDefaultValues { get; set; } = false;
}

// Validates that the specified string uses Base64 encoding
+[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter, AllowMultiple = false)]
+public sealed class Base64StringAttribute : ValidationAttribute
+{
+}

// Specifies length ranges for string/IEnumerable
+[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter, AllowMultiple = false)]
+public sealed class LengthAttribute : ValidationAttribute
+{
+    public LengthAttribute(int minLength = 0, int maxLength = -1);
+
+    public int MinLength { get; }
+    public int? MaxLength { get; }
+}

// Validation using allow and deny lists
+[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter, AllowMultiple = false)]
+public sealed class AllowedValuesAttribute : ValidationAttribute
+{
+    public AllowedValuesAttribute (params object[] allowedValues);
+    public object[] AllowedValues { get; }
+}
+
+[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter, AllowMultiple = false)]
+public sealed class DeniedValuesAttribute : ValidationAttribute
+{
+    public DeniedValuesAttribute(params object[] deniedValues);
+    public object[] DeniedValues { get; }
+}
```

@geeknoid @jeffhandley if this looks good we can put it up API review.

**Comment by geeknoid** [comment] 2022-12-20 18:22
A few comments:

* Can LengthAttribute support strings, arrays, and collections?

* How about the dedicated attribute for timespans? We use this a lot.

Thanks.

**Comment by eiriktsarpalis** [comment] 2022-12-20 19:24
> Can LengthAttribute support strings, arrays, and collections?

Yes, I would expect this to work with anything implementing IEnumerable, so strings, arrays, and collections.

> How about the dedicated attribute for timespans? We use this a lot.

The particular example seems limited to use cases where timespans are measurable in milliseconds, but doesn't afford a lot flexibility when they need to be measured in terms of other units such as hours, days or years. It seems like this functionality could be easily subclassed by users, roughly:
```C#
public class TimeSpanMillisecondRange : RangeAttribute
{
     public TimeSpanMillisecondRange(int minMs, int maxMs) :
          base(typeof(TimeSpan), TimeSpan.FromMilliSeconds(minMs).ToString(), TimeSpan.FromMilliSeconds(maxMs).ToString())
     { }
}
```

**Comment by geeknoid** [comment] 2022-12-20 21:09
Will the Range attribute gain support for comparing arbitrary objects with IComparable so that it can compare time spans? How will it handle exclusive boundary conditions? "Anything more than 0" or "anything less than 10ms"?

**Comment by eiriktsarpalis** [comment] 2022-12-21 12:45
> Will the Range attribute gain support for comparing arbitrary objects with IComparable so that it can compare time spans?

I believe it [does so already](https://github.com/dotnet/runtime/issues/77402#issuecomment-1349797903), although it does force users to express upper and lower bounds as strings for types that do not support literals. 

> How will it handle exclusive boundary conditions? "Anything more than 0" or "anything less than 10ms"?

If I'm understanding the question correctly, in the `IComparer` contract `x.CompareTo(y) <= 0` means `x <= y` and `x.CompareTo(y) < 0` means `x < y`. We can use that to enforce exclusivity depending on user configuration.

**Comment by KieranDevvs** [comment] 2023-01-16 17:18
> 1. `Base64StringAttribute`
>    
>    * This would generally not be used for end-user UI scenarios, which makes it a bit unusual for DataAnnotations validator attributes
>    * We should discuss if we want to be open to scenarios where the models being validated are not UI-oriented
>    * There are plenty of other non-validation attributes in the namespace that are not UI-oriented
>    * If we do open the door for those though, where will we draw the line? If we have a Base64String validator, would that inviteWellFormedJsonString or WellFormedXmlString?

IMO the validation namespace is already generic / non-UI specific and I wouldn't see any need to impose a scope limit to just UI now. I use data validation attributes in all kinds of applications (console, web desktop and mobile, services). Data validation isn't UI specific.

> If we do open the door for those though, where will we draw the line? If we have a Base64String validator, would that inviteWellFormedJsonString or WellFormedXmlString?

IMO I wouldn't restrict the scope of potential validators purely based on what they logically do, but rather judge them on a case by case basis on their effort required to introduce and their level of impact to customers.

**Comment by eiriktsarpalis** [comment] 2023-01-17 18:08
I'm marking the issue as `api-needs-work` since it has come up that there is desired to use the new functionality in .NET framework. Even though `DataAnnotations` are not part of `netstandard2.0`, they do have implementations in .NET framework so adding new members to existing types becomes challenging from a type forwarding perspective.

**Comment by terrajobst** [comment] 2023-02-07 03:25
@geeknoid @stephentoub 

It’s marked as blocking. For tomorrow, we were planning to review interop; is this urgent? If so, I’ll update the agenda and reserve 10-15 min for it.

Otherwise it’s Tuesday next week.

**Comment by stephentoub** [comment] 2023-02-07 03:30
The sooner the better, but if we can't get to it for another week, that's ok.

**Comment by terrajobst** [comment] 2023-02-07 03:35
Then I suggest we push it to next week so we don’t have to time box too much. My gut feel is that interop stuff will take a while, probably even two rounds of reviews.

**Closed** 2023-02-23 18:59 UTC
Labels: api-approved, area-System.ComponentModel.DataAnnotations, in-pr, partner-impact

**Comment by eiriktsarpalis** [comment] 2023-05-10 14:12
> "Exclusive" is more commonly used to describe "something special, limited, or unique that anyone can get, but only from one source". Like "exclusive content" that a media company might generate, or an "exclusive story" that a journalist may write about (but that everyone can access). In this attribute you intend to mean some strict mathematical usage that is something like the opposite of that. By using "Exclusive" there is an easy point of confusion with an everyday English word.

The terms "exclusive" and "inclusive" are fairly standard when it comes to upper bounds and ranges. A quick web search on "exclusive range" should illuminate this. The reason why we went with "exclusive" over "inclusive" is that inclusive ranges are the default for `RangeAttribute`.

**Comment by StingyJack** [comment] 2023-05-11 12:50
> The terms "exclusive" and "inclusive" are fairly standard when it comes to upper bounds and ranges

@eiriktsarpalis - Keep in mind that the person saying this is someone who has studied mathematics extensively (at some very prestigious universities) and for whom the notions of Inclusive/Exclusive are probably something understood as naturally as breathing. There's nothing wrong with that perspective, but it is rather unique and rare. Many in our profession have a degree in a different field of study (Phd Biology, MS Communication, etc), some have taken no college classes, some didn't complete high school.  We read "exclusive" and have to cognate for a few moments or stop and look it up.  If the word were "Included", that impediment to reading the code would not happen.

> A quick web search on "exclusive range" should illuminate this.

There are also 71 Million web search results for "exclusive range is confusing" XD  

Do most English speakers recognize the word "bounds" as in "Leaps and bounds" or "out of bounds"? I dont know, but it could be either. Getting rid of the word "bounds" from the name was a good move. "Exclusive" needs the same treatment.  Even changing it to "Excluded" would be better than "Exclusive". 

When there is a more common, more easily understood, or less ambiguous naming alterative, that should be what is used.

**Comment by StingyJack** [comment] 2023-05-25 02:20
> there are examples of this in [C#](https://learn.microsoft.com/en-us/dotnet/api/system.range?view=net-8.0), [Rust](https://web.mit.edu/rust-lang_v1.25/arch/amd64_ubuntu1404/share/doc/rust/html/std/ops/struct.Range.html), [Scala](https://www.scala-lang.org/api/2.13.x/scala/collection/immutable/Range$.html), [Ruby](https://rubyapi.org/3.2/o/range), [Java](https://guava.dev/releases/19.0/api/docs/com/google/common/collect/Range.html) and the list goes on.

I read that and these phrases were ringing in my head...
> "everyone else is doing it"  

> "Nobody get fired for choosing IBM"  

if you do the same thing as everyone else, it's not improving or adding value. That's like repeating a pattern from existing code for the reason of consistency when you know a better pattern. You have a chance to set a better precedent, don't waste it

**Comment by eiriktsarpalis** [comment] 2023-05-25 08:33
> when you know a better pattern.

We're talking about terminology here, so what is "better" here is really a matter of established convention. I've shown beyond reasonable doubt that inclusive/exclusive is the established terminology, both in the context of mathematics and in the context of programming.

**Comment by StingyJack** [comment] 2023-05-26 05:14
> That's _like_

Keyword there is "like" - I'm giving a similar situation where you would likely choose the opposite.  "Better" in this case has nothing to do with convention, and everything to do with readability and less defects.  

If you dont want to use a more common, more easily understood, and less ambiguous naming alterative, thats up to you.
