### ISSUE TITLE
Dotnet Runtime Issue 12520 (Linux Path.GetDirectoryName with UNC paths)

### ISSUE THREAD

**Issue by mikebollandajw** [dotnet/runtime#110834] opened 2024-12-19 09:15 UTC
### Description

Hello i am experiencing the exact same issue as described in https://github.com/dotnet/runtime/issues/12520 with Dotnet 8.0 which forwards to dotnet/corefx#37026. However, when visiting dotnet/corefx it refers you back to this repository

This was not detected in development as all tests pass locally in Visual Studio but on running in a AWS Lambda environment it became apparent that Path.GetDirectoryName does not function on UNC paths in linux

### Reproduction Steps
```
[TestMethod]
public void PathGetDirectoryName_PassSmbPathWithSubDirectory_ReturnsJustSubDirectory()
{
    // ARRANGE
    var expectedResult = @"\\myserver\myshare$\parent";
    var smbPath = @$"{expectedResult}\testfile.csv";
    // ACT
    var directoryName = Path.GetDirectoryName(smbPath);
    // ASSERT
    Assert.AreEqual(expectedResult, directoryName);
}
```
### Expected behavior

expectedResult = @"\\myserver\myshare$\parent";

### Actual behavior

empty string on linux only

### Regression?

no

### Known Workarounds

write your own path.getdirectoryname

### Configuration

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
Microsoft (R) Test Execution Command Line Tool Version 17.8.0 (x64)
Microsoft.NETCore.App 8.0.11 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

**Comment by huoyaoyuan** [comment] 2024-12-19 09:28
According to the original issue, it's by design. The referenced issue dotnet/corefx#37026 is now #29317, which is a separated issue about `Uri`.

The path functions are using OS native semantics. Native Linux io methods would interpret `\\myserver\myshare$\parent` as a single file name. UNC path on Linux must use `/` instead of `\`.

Closing as by design.

**Closed by huoyaoyuan** 2024-12-19 09:28 UTC
Labels: area-System.IO, untriaged
