### ISSUE TITLE
[wasm][aot] `mono-aot-cross` fails on windows to compile MessagePack.dll

### ISSUE THREAD

**Issue by IvanCherkasov07** [dotnet/runtime#53314] opened 2021-05-26 09:58 UTC
Publish fails with error after enabling &lt;RunAOTCompilation&gt;true&lt;/RunAOTCompilation&gt; if Microsoft.AspNetCore.SignalR.Protocols.MessagePack.dll is referenced.

### To Reproduce

Add reference to WASM client
PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" Version="6.0.0-preview.4.21253.5" 
Publish App: dotnet publish -c:release

### Exceptions 

C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\6.0.0-preview.4.21253.7\Sdk\WasmApp.targets(137,5): error : Precompiling failed for D:\projects\BlazorSRNet5\BlazorSRNet5\Client\obj\Release\net6.0\linked\MessagePack.dll: Error:  [D:\projects\BlazorSRNet5\BlazorSRNet5\Client\BlazorSRNet5.Client.csproj]
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\6.0.0-preview.4.21253.7\Sdk\WasmApp.targets(137,5): error :  [D:\projects\BlazorSRNet5\BlazorSRNet5\Client\BlazorSRNet5.Client.csproj]

### Further technical details
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.4.21255.9
 Commit:    950e4949a7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.4.21255.9\

Host (useful for support):
  Version: 6.0.0-preview.4.21253.7
  Commit:  bfd6048a60

.NET SDKs installed:
  3.1.401 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]
  5.0.300-preview.21258.4 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.4.21255.9 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.4.21253.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.4.21253.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20452.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.4.21254.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by radical** [comment] 2021-06-01 18:18
No execute permission on `/usr/local/share/dotnet/packs/microsoft.netcore.app.runtime.aot.osx-x64.cross.browser-wasm/6.0.0-preview.4.21253.7/Sdk/../tools/mono-aot-cross `

```
                     Running: /usr/local/share/dotnet/packs/microsoft.netcore.app.runtime.aot.osx-x64.cross.browser-wasm/6.0.0-preview.4.21253.7/Sdk/../tools/mono-aot-cross --debug --llvm "--aot=no-opt,static,direct-icalls,determi
                     Using working directory: /private/tmp/bl0/obj/release/net6.0/linked (TaskId:149)
                     Setting environment variables for execution: (TaskId:149)
                        MONO_PATH = /private/tmp/bl0/obj/release/net6.0/linked:/Users/radical/.nuget/packages/microsoft.netcore.app.runtime.mono.browser-wasm/6.0.0-preview.4.21253.7/runtimes/browser-wasm/native/:/Users/radical/.nu
                        MONO_ENV_OPTIONS =  (TaskId:149)
                     System.ComponentModel.Win32Exception (13): Permission denied
                        at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UIn
                        at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) in System.Diagnostics.Process.dll:token 0x6000105+0x1aa
                        at System.Diagnostics.Process.Start() in System.Diagnostics.Process.dll:token 0x60000de+0xab
                        at System.Diagnostics.Process.Start(ProcessStartInfo startInfo) in System.Diagnostics.Process.dll:token 0x60000e2+0x1b
                        at Utils.RunProcess(String path, String args, IDictionary`2 envVars, String workingDir, Boolean ignoreErrors, Boolean silent, MessageImportance outputMessageImportance, MessageImportance debugMessageImporta
                        at MonoAOTCompiler.PrecompileLibrary(ITaskItem assemblyItem, String monoPaths) in MonoAOTCompiler.dll:token 0x600002b+0x436 (TaskId:149)
```

**Comment by radical** [comment] 2021-06-01 18:21
Actually, the file is owned by `root`, because I installed the packs with `sudo`, and running it with a regular user, it doesn't have the execute permission.

`-rwxr--r--  1 root  wheel  12062648 May  3 14:42 /usr/local/share/dotnet/packs/microsoft.netcore.app.runtime.aot.osx-x64.cross.browser-wasm/6.0.0-preview.4.21253.7/Sdk/../tools/mono-aot-cross*`

**Comment by radical** [comment] 2021-06-01 18:26
`/usr/local/share/dotnet/dotnet` has `-rwxr-xr-x`, so we should probably have the same for `mono-aot-cross`.

**Comment by radical** [comment] 2021-06-01 18:53
And on windows:

```
                     Running: C:\Program Files\dotnet\packs\microsoft.netcore.app.runtime.aot.win-x64.cross.browser-wasm\6.0.0-preview.4.21222.10\Sdk\..\tools\mono-aot-cross.exe --debug --llvm "--aot=no-opt,static,direct-icalls,deterministic,nodebug,llvm-path=C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.Emscripten.2.0.12.Sdk.win-x64\6.0.0-preview.4.21220.1\tools\bin\,llvmonly,interp,asmonly,llvm-outfile=C:\dev\bl0\obj\release\net6.0\wasm\MessagePack.dll.bc" MessagePack.dll (TaskId:134)
                     Using working directory: C:\dev\bl0\obj\release\net6.0\linked (TaskId:134)
                     Setting environment variables for execution: (TaskId:134)
                        MONO_PATH = C:\dev\bl0\obj\release\net6.0\linked;C:\Users\Ankit Jain\.nuget\packages\microsoft.netcore.app.runtime.mono.browser-wasm\6.0.0-preview.4.21253.7\runtimes\browser-wasm\native\;C:\Users\Ankit Jain\.nuget\packages\microsoft.netcore.app.runtime.mono.browser-wasm\6.0.0-preview.4.21253.7\runtimes\browser-wasm\\lib\net6.0 (TaskId:134)
                        MONO_ENV_OPTIONS =  (TaskId:134)
                     Exit code: -1073740940 (TaskId:134)
                     System.Exception: Error:

                        at Utils.RunProcess(String path, String args, IDictionary`2 envVars, String workingDir, Boolean ignoreErrors, Boolean silent, MessageImportance outputMessageImportance, MessageImportance debugMessageImportance) in MonoAOTCompiler.dll:token 0x600002f+0x1fd
                        at MonoAOTCompiler.PrecompileLibrary(ITaskItem assemblyItem, String monoPaths) in MonoAOTCompiler.dll:token 0x600002b+0x436 (TaskId:134)
```

**Comment by radical** [comment] 2021-07-21 23:14
I can't reproduce this anymore with `6.0.100-rc.1.21370.2`. It builds fine for me now.
@IvanCherkasov07 could you please try this with a recent build?

**Comment by IvanCherkasov07** [comment] 2021-07-22 10:39
> 6.0.100-rc.1.21370.2

Hi, @radical thx for help, can you please send a link to that build or later. I can't find it on my own.

**Comment by radical** [comment] 2021-07-22 16:54
Try the `Release/6.0.1XX-preview7 (6.0.x Runtime)` builds from https://github.com/dotnet/installer, scroll down to find them.

**Comment by radical** [comment] 2021-07-23 21:59
@rajeshaz09 is getting the same crash with `6.0.100-preview.7.21372.19` (https://github.com/neuecc/MessagePack-CSharp/issues/1287).

**Comment by radical** [comment] 2021-07-23 22:02
Closing this in favor of https://github.com/dotnet/runtime/issues/53546 (which was based on this issue).

**Closed by radical** 2021-07-23 22:02 UTC
Labels: arch-wasm, area-Codegen-AOT-mono, needs more info
