### ISSUE TITLE
System.Uri .AbsoluteUri duplicates paths

### ISSUE THREAD

**Issue by TylerLeonhardt** [dotnet/runtime#1031] opened 2019-12-18 21:38 UTC
Pass in a file path with ASCII characters into the `Uri` constructor and get the `AbsoluteUri`:
```
> new Uri("/Users/tyleonha/Code/PowerShell/Misc/foo.ps1").AbsoluteUri
file:///Users/tyleonha/Code/PowerShell/Misc/foo.ps1
```

Everything looks great. Now pass in a path with non-ASCII characters:
```
> new Uri("/Users/tyleonha/Code/PowerShell/Misc/测试.ps1").AbsoluteUri
file:///Users/tyleonha/Code/PowerShell/Misc/%E6%B5%8B%E8%AF%95.ps1/Users/tyleonha/Code/PowerShell/Misc/%E6%B5%8B%E8%AF%95.ps1
```
The file is url encoded correctly but the file path is duplicated.

Same happens if I pass in the path a Uri string:
```
new Uri("file:///Users/tyleonha/Code/PowerShell/Misc/%E6%B5%8B%E8%AF%95.ps1").AbsoluteUri
file:///Users/tyleonha/Code/PowerShell/Misc/%E6%B5%8B%E8%AF%95.ps1/Users/tyleonha/Code/PowerShell/Misc/%E6%B5%8B%E8%AF%95.ps1
```

If I add a drive letter, this no longer repros:
```
> new Uri("C:/Users/tyleonha/Code/PowerShell/Misc/测试.ps1").AbsoluteUri
file:///C:/Users/tyleonha/Code/PowerShell/Misc/%E6%B5%8B%E8%AF%95.ps1
```

We know that the path passed in is absolute... so I'm a bit confused as to why this duplication is happening.

I'm running this on macOS Mojave with .NET Core 3.1 (via PowerShell).

**Comment by TylerLeonhardt** [comment] 2019-12-18 21:44
Related possibly... the `ToString()` method shows similar (but worse) behavior:

```
> new Uri("/Users/tyleonha/Code/PowerShell/Misc/测试.ps1").ToString()
file:///Users/tyleonha/Code/PowerShell/Misc/%E6%B5%8B%E8%AF%95.ps1/Users/tyleonha/Code/PowerShell/Misc/测试.ps1
```

Some of the characters are decoded, some are left as is...

**Comment by TylerLeonhardt** [comment] 2019-12-19 04:30
I went as deep as I could with the [AbsoluteUri codepath](https://github.com/dotnet/runtime/blob/5ef367a888fa8a25ce157cf340bd271efd36c72f/src/libraries/System.Private.Uri/src/System/Uri.cs#L657-L679) but got to [this method](https://github.com/dotnet/runtime/blob/5ef367a888fa8a25ce157cf340bd271efd36c72f/src/libraries/System.Private.Uri/src/System/Uri.cs#L2652-L2687) (ran with reflection) still gave me the same results... so it's deeper but what this is method is doing is over my head, I'm afraid.

**Comment by MihaZupan** [comment] 2019-12-19 17:25
Duplicate of #1061

**Closed by MihaZupan** 2019-12-19 17:25 UTC
Labels: area-System.Net, untriaged
