### ISSUE TITLE
CI System.Windows.Extensions.Test failure in "Libraries Test Run release mono Windows_NT x64 Debug" leg

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#41676] opened 2020-09-01 15:21 UTC
https://helix.dot.net/api/2019-06-17/jobs/fdb7cf22-9e0c-41c1-bdca-414b01510861/workitems/System.Windows.Extensions.Tests/console

```
C:\h\w\BDF7098A\w\AC850976\e>call RunTests.cmd --runtime-path C:\h\w\BDF7098A\p 
----- start 01/09/2020 14:51:52,56 ===============  To repro directly: ===================================================== 
pushd C:\h\w\BDF7098A\w\AC850976\e\
"C:\h\w\BDF7098A\p\dotnet.exe" exec --runtimeconfig System.Windows.Extensions.Tests.runtimeconfig.json --depsfile System.Windows.Extensions.Tests.deps.json xunit.console.dll System.Windows.Extensions.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================

C:\h\w\BDF7098A\w\AC850976\e>"C:\h\w\BDF7098A\p\dotnet.exe" exec --runtimeconfig System.Windows.Extensions.Tests.runtimeconfig.json --depsfile System.Windows.Extensions.Tests.deps.json xunit.console.dll System.Windows.Extensions.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Windows.Extensions.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Windows.Extensions.Tests (found 32 of 43 test cases)
  Starting:    System.Windows.Extensions.Tests (parallel test collections = on, max threads = 2)
    System.Security.Cryptography.X509Certificates.Tests.X509Certificate2UIManualTests.DisplayCertificateTest [SKIP]
      Condition(s) not met: "ManualTestsEnabled"
    System.Security.Cryptography.X509Certificates.Tests.X509Certificate2UIManualTests.SelectCertificateSingleSelectionTest [SKIP]
      Condition(s) not met: "ManualTestsEnabled"
    System.Media.Test.SoundPlayerTests.LoadAsync_CancelDuringLoad_CompletesAsCanceled(cancellationCause: 0) [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/libraries/System.Windows.Extensions/tests/System/Media/SoundPlayerTests.cs(493,0): at System.Media.Test.SoundPlayerTests.LoadAsync_CancelDuringLoad_CompletesAsCanceled(Int32 cancellationCause)
        --- End of stack trace from previous location ---
  Finished:    System.Windows.Extensions.Tests
=== TEST EXECUTION SUMMARY ===
   System.Windows.Extensions.Tests  Total: 49, Errors: 0, Failed: 1, Skipped: 2, Time: 0,443s
```

**Comment by danmoseley** [comment] 2021-09-10 02:49
dupe of https://github.com/dotnet/runtime/issues/41676

**Closed by danmoseley** 2021-09-10 02:49 UTC
Labels: area-Microsoft.Win32, disabled-test, runtime-mono
