### ISSUE TITLE
Generic Attributes

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#40761] opened 2020-08-13 10:01 UTC
Please allow attributes to be generic.  For example:
````
public class GA<T> : Attribute {

    }

````

**Comment by tomrus88** [comment] 2020-08-13 10:24
https://github.com/dotnet/csharplang/issues/124

**Comment by jkotas** [comment] 2020-08-13 15:25
Runtime support this. This is C# limitation. Resolving as duplicate of dotnet/csharplang#124

**Closed by jkotas** 2020-08-13 15:25 UTC
Labels: untriaged
