### ISSUE TITLE
Nit: Non-short-circuiting OR in Linq

### ISSUE THREAD

**Issue by scovetta** [dotnet/runtime#33587] opened 2020-03-14 05:33 UTC
In [Linq/Select.cs:180](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Linq/src/System/Linq/Select.cs#L180):

```
public override bool MoveNext()
{
    if (_state < 1 | _state == _source.Length + 1)
...
```
This looks to me like it should be a `||` operator instead, but a tiny part of me thinks that perhaps the TSource could implement .Length as a property and the getter could mutate the object in some important way.

Happy to submit a PR for this, but wanted to ask if this was a known pattern first, or if this was just a typo.

**Comment by svick** [comment] 2020-03-14 08:16
According to the PR that introduced this change (https://github.com/dotnet/corefx/pull/11841), this was intentional, to avoid a branch instruction.

**Comment by stephentoub** [comment] 2020-03-14 11:29
Also _source here is an array; its Length is immutable.

**Comment by stephentoub** [comment] 2020-03-14 11:30
Closing as by design. Thanks.

**Closed by stephentoub** 2020-03-14 11:30 UTC
Labels: area-System.Linq, untriaged
