### ISSUE TITLE
Test failure: System.Net.Http.Functional.Tests.HttpClientTest.GetAsync_ContentCanBeCanceled(getMode: 0, cancelMode: 2)

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#43210] opened 2020-10-09 08:56 UTC
failed in job:[runtime-libraries-coreclr outerloop 20201008.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=845001&view=ms.vss-test-web.build-test-results-tab&runId=26906848&paneView=debug&resultId=103443)

net6.0-Windows_NT-Release-x64-CoreCLR_release-Windows.10.Amd64.ServerRS5.Open

Error message
~~~
System.IO.IOException : Unexpected EOF trying to read request header

Stack trace
   at System.Net.Test.Common.LoopbackServer.Connection.ReadRequestHeaderBytesAsync() in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 670
   at System.Net.Test.Common.LoopbackServer.Connection.ReadRequestDataAsync(Boolean readBody) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 716
   at System.Net.Http.Functional.Tests.HttpClientTest.<>c__DisplayClass26_0.<<GetAsync_ContentCanBeCanceled>b__3>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientTest.cs:line 481
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 126
   at System.Net.Http.Functional.Tests.HttpClientTest.<>c__DisplayClass26_0.<<GetAsync_ContentCanBeCanceled>b__1>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientTest.cs:line 479
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 96
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 124
   at System.Net.Test.Common.LoopbackServerFactory.<>c__DisplayClass5_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in /_/src/libraries/Common/tests/System/Net/Http/GenericLoopbackServer.cs:line 36
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 74
   at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 37
   at System.Net.Http.Functional.Tests.HttpClientTest.GetAsync_ContentCanBeCanceled(Int32 getMode, Int32 cancelMode) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientTest.cs:line 444
--- End of stack trace from previous location ---
~~~

**Comment by v-haren** [comment] 2020-10-26 03:13
failed again in job: [runtime-libraries-coreclr outerloop 20201025.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=865290&view=ms.vss-test-web.build-test-results-tab&runId=27710510&paneView=debug&resultId=104288)

failed test: System.Net.Http.Functional.Tests.HttpClientTest.GetAsync_ContentCanBeCanceled(getMode: 0, cancelMode: 2)

net6.0-Windows_NT-Release-x86-CoreCLR_release-Windows.10.Amd64.Server19H1.Open


Error message
~~~
System.IO.IOException : Unexpected EOF trying to read request header


Stack trace
   at System.Net.Test.Common.LoopbackServer.Connection.ReadRequestHeaderBytesAsync() in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 670
   at System.Net.Test.Common.LoopbackServer.Connection.ReadRequestDataAsync(Boolean readBody) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 716
   at System.Net.Http.Functional.Tests.HttpClientTest.<>c__DisplayClass26_0.<<GetAsync_ContentCanBeCanceled>b__3>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientTest.cs:line 484
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.AcceptConnectionAsync(Func`2 funcAsync) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 126
   at System.Net.Http.Functional.Tests.HttpClientTest.<>c__DisplayClass26_0.<<GetAsync_ContentCanBeCanceled>b__1>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientTest.cs:line 482
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 96
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 124
   at System.Net.Test.Common.LoopbackServerFactory.<>c__DisplayClass5_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in /_/src/libraries/Common/tests/System/Net/Http/GenericLoopbackServer.cs:line 36
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 74
   at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 37
   at System.Net.Http.Functional.Tests.HttpClientTest.GetAsync_ContentCanBeCanceled(Int32 getMode, Int32 cancelMode) in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientTest.cs:line 447
--- End of stack trace from previous location ---
~~~

**Comment by antonfirsov** [comment] 2020-10-26 12:14
Hit in #43409

**Comment by karelz** [comment] 2020-11-12 17:13
Duplicate of #44003

**Closed by karelz** 2020-11-12 17:13 UTC
Labels: area-System.Net.Http, untriaged
