### ISSUE TITLE
system.text.json + azure functios + cosmos db

### ISSUE THREAD

**Issue by drma-dev** [dotnet/runtime#47712] opened 2021-02-01 01:02 UTC
In the cosmos, the date is being saved in the following format:
`"birthDate": "2003-01-29T20:11:07.218-02:00"`

but this format does not work with the cosmos functions (DateTimeDiff), because it is waiting in UTC format.

I tried to use this configuration at startup:
```
builder.Services.AddMvcCore (). AddJsonOptions (options =>
             {
                 options.SerializerSettings.DateFormatHandling = Newtonsoft.Json.DateFormatHandling.IsoDateFormat;
                 options.SerializerSettings.DateParseHandling = Newtonsoft.Json.DateParseHandling.DateTimeOffset;
                 options.SerializerSettings.DateTimeZoneHandling = Newtonsoft.Json.DateTimeZoneHandling.RoundtripKind;
             });
```

but it seems that it no longer works in .net core 3

what can I do to solve this?

**Comment by javiercn** [comment] 2021-02-01 16:44
@drma-dev this doesn't seem to be related to ASP.NET Core.

I've transferred your issue to the runtime repo since they can give you a faster and better answer.

**Comment by danmosemsft** [comment] 2021-02-01 16:57
This is Newtonsoft, not S.T.Json. It seems it's a question about the date formats above changing between 3.1 and 5.0.

**Comment by drma-dev** [comment] 2021-02-01 17:11
@danmosemsft

im not using Newtonsoft

**Comment by eiriktsarpalis** [comment] 2021-02-01 17:16
@drma-dev the configuration settings you shared would only concern Newtonsoft though. So perhaps your code only configures Newtonsoft but then uses S.T.J?

**Comment by drma-dev** [comment] 2021-02-01 17:24
I'm not using that setting, because it doesn't work. I showed it only as an example of an attempt I made.

**Comment by eiriktsarpalis** [comment] 2021-02-01 17:26
Could you share a minimal reproduction that demonstrates the issue?

**Comment by drma-dev** [comment] 2021-02-01 17:42
I'm not sure if it's really an issue or normal behavior.

There's nothing special:

```
public class newclass
{
    public DateTimeOffset Date1 { get; set; } = DateTimeOffset.Now;
    public DateTimeOffset Date2 { get; set; } = DateTimeOffset.UtcNow;
    public DateTime Date3 { get; set; } = DateTime.Now;
    public DateTime Date4 { get; set; } = DateTime.UtcNow;
}
```
then I send it to the cosmos:

```
public CosmosRepository(IConfiguration config)
  {
      var connString = config.GetValue<string>("RepositoryOptions:CosmosConnectionString");
      var databaseId = config.GetValue<string>("RepositoryOptions:DatabaseId");
      var containerId = config.GetValue<string>("RepositoryOptions:ContainerId");

      var _client = new CosmosClient(connString, new CosmosClientOptions()
      {
          SerializerOptions = new CosmosSerializationOptions()
          {
              PropertyNamingPolicy = CosmosPropertyNamingPolicy.CamelCase
          }
      });

      Container = _client.GetContainer(databaseId, containerId);
  }
```
```
public async Task<T> Add<T>(T item, CancellationToken cancellationToken) where T : CosmosBase
  {
      var response = await Container.CreateItemAsync(item, new PartitionKey(item.Key), null, cancellationToken);

      return response.Resource;
  }
```

**Comment by eiriktsarpalis** [comment] 2021-02-01 17:44
Which version of the CosmosDB sdk are you using?

**Comment by drma-dev** [comment] 2021-02-01 17:47
```
<PropertyGroup>
  <TargetFramework>netcoreapp3.1</TargetFramework>
  <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  <EnableNETAnalyzers>true</EnableNETAnalyzers>
</PropertyGroup>
```
```
<PackageReference Include="Microsoft.Azure.Cosmos" Version="3.16.0" />
<PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
```

**Comment by eiriktsarpalis** [comment] 2021-02-01 18:00
I've never worked with the v3 cosmos sdk but on quick inspection the library seems to define [its own serialization abstractions wrapping Newtonsoft.Json](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/9e51de53b3f10e20846b7fdb86837b1cccd4efae/Microsoft.Azure.Cosmos/src/Serializer/CosmosJsonDotNetSerializer.cs#L16). It seems possible to use this class as a template to construct a custom "CosmosSerializer", but I would suggest going to https://github.com/Azure/azure-cosmos-dotnet-v3 and asking the team for their recommended solution.

Since this is a question not related to dotnet/runtime or System.Text.Json, I'm going to close this issue.

**Closed by eiriktsarpalis** 2021-02-01 18:00 UTC
Labels: area-System.Runtime, question
