### ISSUE TITLE
[wasm] Regression in `System.Text.Json` tests with AOT

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#80179] opened 2023-01-04 14:40 UTC
[Rolling build](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-7e17919f92db418b85/normal-System.Text.Json.Tests/1/console.53d71e01.log?helixlogtype=result):

```
[10:10:47] fail: [FAIL] System.Text.Json.Tests.JsonDocumentTests.ParseJson_UnseekableStream(compactData: True, type: ProjectLockJson, jsonString: "{  \"locked\": false,  \"version\": 1,  \"targets\"...)
[10:10:47] info: System.ObjectDisposedException : Cannot access a disposed object.
[10:10:47] info: Object name: 'JsonDocument'.
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.DepthFirstAppend(StringBuilder buf, JsonElement element)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.DepthFirstAppend(StringBuilder buf, JsonElement element)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.DepthFirstAppend(StringBuilder buf, JsonElement element)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.DepthFirstAppend(StringBuilder buf, JsonElement element)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.DepthFirstAppend(StringBuilder buf, JsonElement element)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.PrintJson(JsonElement element, Int32 sizeHint)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.PrintJson(JsonDocument document, Int32 sizeHint)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.ParseJsonAsync(Boolean compactData, TestCaseType type, String jsonString, Func`2 stringDocBuilder, Func`2 bytesDocBuilder)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.DepthFirstAppend(StringBuilder buf, JsonElement element)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.DepthFirstAppend(StringBuilder buf, JsonElement element)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.DepthFirstAppend(StringBuilder buf, JsonElement element)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.DepthFirstAppend(StringBuilder buf, JsonElement element)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.DepthFirstAppend(StringBuilder buf, JsonElement element)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.PrintJson(JsonElement element, Int32 sizeHint)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.PrintJson(JsonDocument document, Int32 sizeHint)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.ParseJson_UnseekableStream(Boolean compactData, TestCaseType type, String jsonString)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.DepthFirstAppend(StringBuilder buf, JsonElement element)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.DepthFirstAppend(StringBuilder buf, JsonElement element)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.DepthFirstAppend(StringBuilder buf, JsonElement element)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.DepthFirstAppend(StringBuilder buf, JsonElement element)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.DepthFirstAppend(StringBuilder buf, JsonElement element)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.PrintJson(JsonElement element, Int32 sizeHint)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.PrintJson(JsonDocument document, Int32 sizeHint)
[10:10:47] info: --- End of stack trace from previous location ---
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.DepthFirstAppend(StringBuilder buf, JsonElement element)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.DepthFirstAppend(StringBuilder buf, JsonElement element)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.DepthFirstAppend(StringBuilder buf, JsonElement element)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.DepthFirstAppend(StringBuilder buf, JsonElement element)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.DepthFirstAppend(StringBuilder buf, JsonElement element)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.PrintJson(JsonElement element, Int32 sizeHint)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.PrintJson(JsonDocument document, Int32 sizeHint)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.DepthFirstAppend(StringBuilder buf, JsonElement element)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.DepthFirstAppend(StringBuilder buf, JsonElement element)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.DepthFirstAppend(StringBuilder buf, JsonElement element)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.DepthFirstAppend(StringBuilder buf, JsonElement element)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.DepthFirstAppend(StringBuilder buf, JsonElement element)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.PrintJson(JsonElement element, Int32 sizeHint)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.PrintJson(JsonDocument document, Int32 sizeHint)
```

```
[10:10:47] fail: [FAIL] System.Text.Json.Tests.JsonDocumentTests.ParseJson_UnseekableStream(compactData: True, type: Json40KB, jsonString: "[\n  {\n    \"_id\": \"5671eb0737b18866984067ac\","...)
[10:10:47] info: Assert.Equal() Failure
[10:10:47] info:           ↓ (pos 0)
[10:10:47] info: Expected: _id, 5671eb0737b18866984067ac, index, 0, ···
[10:10:47] info: Actual:
[10:10:47] info:           ↑ (pos 0)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.ParseJsonAsync(Boolean compactData, TestCaseType type, String jsonString, Func`2 stringDocBuilder, Func`2 bytesDocBuilder)
[10:10:47] info:    at System.Text.Json.Tests.JsonDocumentTests.ParseJson_UnseekableStream(Boolean compactData, TestCaseType type, String jsonString)
[10:10:47] info: --- End of stack trace from previous location ---
```

These failures appeared with the [rolling build 20221218.2](https://dev.azure.com/dnceng-public/public/_build/results?buildId=115677&view=logs&j=6c05861b-5acf-5a94-8135-27551ca7dfc6&t=27de4c1b-a8cc-57d6-8983-2ba8073338b5), and [log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-680908dca0f343948a/normal-System.Text.Json.Tests/1/console.b751008a.log?helixlogtype=result).

The only commit between this, and the [previous rolling build - 20221218.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=115574&view=logs&j=6c05861b-5acf-5a94-8135-27551ca7dfc6) was 200a90aae4905567e79aafe49380a899a8f2b0c7 (https://github.com/dotnet/runtime/pull/79215).
cc @BrzVlad @vargaz 

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by lewing** [comment] 2023-01-04 17:32
looks like https://github.com/dotnet/runtime/issues/79943

**Comment by BrzVlad** [comment] 2023-01-04 18:03
https://github.com/dotnet/runtime/pull/80186 fixes a regression reported in the microbenchmarks.

Are all tests still enabled so we can see if that PR is also a fix for this ?

**Comment by BrzVlad** [comment] 2023-01-04 18:07
This failure was fully deterministic ?

**Comment by radical** [comment] 2023-01-04 18:08
We have been hitting it on every rolling build, AFAICS.

**Closed** 2023-01-04 23:42 UTC
Labels: arch-wasm, blocking-clean-ci, area-Codegen-Interpreter-mono, in-pr, test-failure
