### ISSUE TITLE
[API Proposal]: Return implementation for IEnumerable<T>

### ISSUE THREAD

**Issue by Gotcha7770** [dotnet/runtime#62097] opened 2021-11-27 12:33 UTC
### Background and motivation

To create enumeration from a simple object, C # introduced the **yield** keyword. Unfortunately, it has some limitations: you can not use yield like this:

```C#
IEnumerable<int> enumerable = yield 0;
```

It would be very convenient, for example in a similar case:

```C#
return number switch
{
   0 => Enumerable.Empty<int>(),
   1 => yield 1,
   _ => SomeEnumerableFactory(number)
};
```

The **System.Interactive** library has a special method similar to **Task.FromResult()**: [Enumerable.Return()](https://github.com/dotnet/reactive/blob/main/Ix.NET/Source/System.Interactive/System/Linq/Operators/Return.cs)

I use this method a lot as I like the functional paradigm style, where anonymous delegates and IEnumerable interface are often mixed. It seems like overkill using an entire library for the sake of one method (in fact, not one, I also used methods **DistinctBy**, **MaxBy** and **MinBy**, but they were just added to .NET 6), and it would be convenient to have it in a standard assembly.

### API Proposal

```C#
namespace System.Linq
{
    public static partial class Enumerable
    {
        /// <summary>
        /// Returns a sequence with a single element.
        /// </summary>
        /// <typeparam name="TSource">Result sequence element type.</typeparam>
        /// <param name="value">Single element of the resulting sequence.</param>
        /// <returns>Sequence with a single element.</returns>
        public static IEnumerable<TSource> Return<TSource>(TSource value)
        {
            yield return value;
        }
    }
}
```

### API Usage

```C#
return number switch
{
   0 => Enumerable.Empty<int>(),
   1 => Enumerable.Return(1),
   _ => SomeEnumerableFactory(number)
};

or

Func<bool, IEnumerable<int>> x => x ? Enumerable.Range(0, 10) : Enumerable.Return(0);
```

**Comment by bbartels** [comment] 2021-11-27 13:20
Duplicate of https://github.com/dotnet/runtime/issues/15136

Looked over the thread a long time ago, so not sure if I remember correctly. But I think the conclusion was something like, just use `new T[] { item} `.

**Comment by eiriktsarpalis** [comment] 2021-11-29 11:52
Closing per feedback in #15136.

**Closed by eiriktsarpalis** 2021-11-29 11:52 UTC
Labels: api-suggestion, area-System.Linq, untriaged
