### ISSUE TITLE
Most CoreCLR tests not running in CI.

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/runtime#35798] opened 2020-05-04 16:43 UTC
There are several issues currently.

The most significant is that the `targetGeneric` tests are not currently running in CI.

The root cause of this is the unzipping of the `targetSpecific` and `targetGeneric` tests into the same directory is broken, because the second download clean the directory removing the `targetGeneric` tests.  The draft fix is #35699.

It also turns out that #35645 fix to eliminate the `targetSpecific` build legs would also fix the directory cleaning issue.

However #35699 & #35645 both demonstrates another set of issues.  
+ The generic tests include Linux specific tests. When run on Windows these fail.
+ The specific tests are missing WIndows specific tests.

So in general 
+ any test which doesn't run on OSX is not being built in the `targetGeneric` phase.  
+ any test which doesn't run on every target cannot be treated as `targetGeneric`

The current proposed solution is #35783.  This test allows tests for all targets to be build on any platform.  It builds all tests on `OSX` and removes obsolete build legs and cleans up residue.

/cc @dotnet/runtime-infrastructure

**Comment by sdmaclea** [comment] 2020-05-06 03:24
Being fixed by #35868

**Comment by sdmaclea** [comment] 2020-05-06 03:26
The following tests regressed during the coverage gap.

```diff
commit b2ce1e017170b26a9cb32bff5c869972d63d55b3
Author: Steve MacLean <Steve.MacLean@Microsoft.com>
Date:   Tue May 5 17:12:44 2020 -0400

    Add issues related to CI coverage outage

diff --git a/src/coreclr/tests/issues.targets b/src/coreclr/tests/issues.targets
index ce48665..c6c55eb 100644
--- a/src/coreclr/tests/issues.targets
+++ b/src/coreclr/tests/issues.targets
@@ -11,6 +11,25 @@
         <ExcludeList Include="$(XunitTestBinBase)/Regressions/coreclr/GitHub_22888/test22888/*">
             <Issue>https://github.com/dotnet/runtime/issues/13703</Issue>
         </ExcludeList>
+        <!-- Test regressions during CI coverage outage -->
+        <ExcludeList Include="$(XunitTestBinBase)/baseservices/exceptions/stackoverflow/*">
+            <Issue>https://github.com/dotnet/runtime/issues/35798</Issue>
+        </ExcludeList>
+        <ExcludeList Include="$(XunitTestBinBase)/JIT/SIMD/Vector3Interop_r/*">
+            <Issue>https://github.com/dotnet/runtime/issues/35798</Issue>
+        </ExcludeList>
+        <ExcludeList Include="$(XunitTestBinBase)/JIT/SIMD/Vector3Interop_ro/*">
+            <Issue>https://github.com/dotnet/runtime/issues/35798</Issue>
+        </ExcludeList>
+        <ExcludeList Include="$(XunitTestBinBase)/Interop/StructMarshalling/ReversePInvoke/MarshalSeqStruct/Reverse/*">
+            <Issue>https://github.com/dotnet/runtime/issues/35798</Issue>
+        </ExcludeList>
+        <ExcludeList Include="$(XunitTestBinBase)/Interop/PInvoke/Vector2_3_4/Vector2_3_4/*">
+            <Issue>https://github.com/dotnet/runtime/issues/35798</Issue>
+        </ExcludeList>
+        <ExcludeList Include="$(XunitTestBinBase)/Interop/UnmanagedCallersOnly/UnmanagedCallersOnlyTest/*">
+            <Issue>https://github.com/dotnet/runtime/issues/35798</Issue>
+        </ExcludeList>
     </ItemGroup>
 
     <!-- All OS/Arch CoreCLR excludes -->

```

**Comment by sdmaclea** [comment] 2020-05-06 03:30
The regressions were found while testing 96268f3ef5867
The CI coverage was introduced by #35378 so untested coverage began around commit d56f849515de

**Comment by sdmaclea** [comment] 2020-05-06 04:00
/cc @janvorli for the regressing `stackoverflowtester` test

/cc @BruceForstall @tannergooding @echesakovMSFT 
for the regressing  `SIMD/Vector3Interop*` tests

/cc @AaronRobinsonMSFT for the regressing `InterOp` tests.

**Comment by jashook** [comment] 2020-05-06 18:13
Closing, we are now back to 29 workitems.

```
[
    {
        "DetailsUrl": "https://helix.dot.net/api/2019-06-17/jobs/b3373b29-ba30-42f2-b978-d42b410eb1b1/workitems/HelixController%20Work%20Queueing",
        "Job": "b3373b29-ba30-42f2-b978-d42b410eb1b1",
        "Name": "HelixController Work Queueing",
        "State": "Finished"
    },
    {
        "DetailsUrl": "https://helix.dot.net/api/2019-06-17/jobs/b3373b29-ba30-42f2-b978-d42b410eb1b1/workitems/Interop",
        "Job": "b3373b29-ba30-42f2-b978-d42b410eb1b1",
        "Name": "Interop",
        "State": "Finished"
    },
    {
        "DetailsUrl": "https://helix.dot.net/api/2019-06-17/jobs/b3373b29-ba30-42f2-b978-d42b410eb1b1/workitems/JIT",
        "Job": "b3373b29-ba30-42f2-b978-d42b410eb1b1",
        "Name": "JIT",
        "State": "Finished"
    },
    {
        "DetailsUrl": "https://helix.dot.net/api/2019-06-17/jobs/b3373b29-ba30-42f2-b978-d42b410eb1b1/workitems/JIT.CodeGenBringUpTests",
        "Job": "b3373b29-ba30-42f2-b978-d42b410eb1b1",
        "Name": "JIT.CodeGenBringUpTests",
        "State": "Finished"
    },
    {
        "DetailsUrl": "https://helix.dot.net/api/2019-06-17/jobs/b3373b29-ba30-42f2-b978-d42b410eb1b1/workitems/JIT.Directed",
        "Job": "b3373b29-ba30-42f2-b978-d42b410eb1b1",
        "Name": "JIT.Directed",
        "State": "Finished"
    },
    {
        "DetailsUrl": "https://helix.dot.net/api/2019-06-17/jobs/b3373b29-ba30-42f2-b978-d42b410eb1b1/workitems/JIT.Generics",
        "Job": "b3373b29-ba30-42f2-b978-d42b410eb1b1",
        "Name": "JIT.Generics",
        "State": "Finished"
    },
    {
        "DetailsUrl": "https://helix.dot.net/api/2019-06-17/jobs/b3373b29-ba30-42f2-b978-d42b410eb1b1/workitems/JIT.HardwareIntrinsics",
        "Job": "b3373b29-ba30-42f2-b978-d42b410eb1b1",
        "Name": "JIT.HardwareIntrinsics",
        "State": "Finished"
    },
    {
        "DetailsUrl": "https://helix.dot.net/api/2019-06-17/jobs/b3373b29-ba30-42f2-b978-d42b410eb1b1/workitems/JIT.IL_Conformance",
        "Job": "b3373b29-ba30-42f2-b978-d42b410eb1b1",
        "Name": "JIT.IL_Conformance",
        "State": "Finished"
    },
    {
        "DetailsUrl": "https://helix.dot.net/api/2019-06-17/jobs/b3373b29-ba30-42f2-b978-d42b410eb1b1/workitems/JIT.Methodical",
        "Job": "b3373b29-ba30-42f2-b978-d42b410eb1b1",
        "Name": "JIT.Methodical",
        "State": "Finished"
    },
    {
        "DetailsUrl": "https://helix.dot.net/api/2019-06-17/jobs/b3373b29-ba30-42f2-b978-d42b410eb1b1/workitems/JIT.Methodical.a-dA-D",
        "Job": "b3373b29-ba30-42f2-b978-d42b410eb1b1",
        "Name": "JIT.Methodical.a-dA-D",
        "State": "Finished"
    },
    {
        "DetailsUrl": "https://helix.dot.net/api/2019-06-17/jobs/b3373b29-ba30-42f2-b978-d42b410eb1b1/workitems/JIT.Methodical.e-iE-I",
        "Job": "b3373b29-ba30-42f2-b978-d42b410eb1b1",
        "Name": "JIT.Methodical.e-iE-I",
        "State": "Finished"
    },
    {
        "DetailsUrl": "https://helix.dot.net/api/2019-06-17/jobs/b3373b29-ba30-42f2-b978-d42b410eb1b1/workitems/JIT.Methodical.eh",
        "Job": "b3373b29-ba30-42f2-b978-d42b410eb1b1",
        "Name": "JIT.Methodical.eh",
        "State": "Finished"
    },
    {
        "DetailsUrl": "https://helix.dot.net/api/2019-06-17/jobs/b3373b29-ba30-42f2-b978-d42b410eb1b1/workitems/JIT.Regression",
        "Job": "b3373b29-ba30-42f2-b978-d42b410eb1b1",
        "Name": "JIT.Regression",
        "State": "Finished"
    },
    {
        "DetailsUrl": "https://helix.dot.net/api/2019-06-17/jobs/b3373b29-ba30-42f2-b978-d42b410eb1b1/workitems/JIT.Regression.CLR-x86-JIT.V1-M09-M11",
        "Job": "b3373b29-ba30-42f2-b978-d42b410eb1b1",
        "Name": "JIT.Regression.CLR-x86-JIT.V1-M09-M11",
        "State": "Finished"
    },
    {
        "DetailsUrl": "https://helix.dot.net/api/2019-06-17/jobs/b3373b29-ba30-42f2-b978-d42b410eb1b1/workitems/JIT.Regression.CLR-x86-JIT.V1-M12-M13",
        "Job": "b3373b29-ba30-42f2-b978-d42b410eb1b1",
        "Name": "JIT.Regression.CLR-x86-JIT.V1-M12-M13",
        "State": "Finished"
    },
    {
        "DetailsUrl": "https://helix.dot.net/api/2019-06-17/jobs/b3373b29-ba30-42f2-b978-d42b410eb1b1/workitems/JIT.Stress",
        "Job": "b3373b29-ba30-42f2-b978-d42b410eb1b1",
        "Name": "JIT.Stress",
        "State": "Finished"
    },
    {
        "DetailsUrl": "https://helix.dot.net/api/2019-06-17/jobs/b3373b29-ba30-42f2-b978-d42b410eb1b1/workitems/JIT.jit64",
        "Job": "b3373b29-ba30-42f2-b978-d42b410eb1b1",
        "Name": "JIT.jit64",
        "State": "Finished"
    },
    {
        "DetailsUrl": "https://helix.dot.net/api/2019-06-17/jobs/b3373b29-ba30-42f2-b978-d42b410eb1b1/workitems/JIT.jit64.hfa",
        "Job": "b3373b29-ba30-42f2-b978-d42b410eb1b1",
        "Name": "JIT.jit64.hfa",
        "State": "Finished"
    },
    {
        "DetailsUrl": "https://helix.dot.net/api/2019-06-17/jobs/b3373b29-ba30-42f2-b978-d42b410eb1b1/workitems/JIT.jit64.mcc",
        "Job": "b3373b29-ba30-42f2-b978-d42b410eb1b1",
        "Name": "JIT.jit64.mcc",
        "State": "Finished"
    },
    {
        "DetailsUrl": "https://helix.dot.net/api/2019-06-17/jobs/b3373b29-ba30-42f2-b978-d42b410eb1b1/workitems/JIT.jit64.opt",
        "Job": "b3373b29-ba30-42f2-b978-d42b410eb1b1",
        "Name": "JIT.jit64.opt",
        "State": "Finished"
    },
    {
        "DetailsUrl": "https://helix.dot.net/api/2019-06-17/jobs/b3373b29-ba30-42f2-b978-d42b410eb1b1/workitems/JIT.jit64.valuetypes",
        "Job": "b3373b29-ba30-42f2-b978-d42b410eb1b1",
        "Name": "JIT.jit64.valuetypes",
        "State": "Finished"
    },
    {
        "DetailsUrl": "https://helix.dot.net/api/2019-06-17/jobs/b3373b29-ba30-42f2-b978-d42b410eb1b1/workitems/Loader.classloader",
        "Job": "b3373b29-ba30-42f2-b978-d42b410eb1b1",
        "Name": "Loader.classloader",
        "State": "Finished"
    },
    {
        "DetailsUrl": "https://helix.dot.net/api/2019-06-17/jobs/b3373b29-ba30-42f2-b978-d42b410eb1b1/workitems/Loader.classloader.generics",
        "Job": "b3373b29-ba30-42f2-b978-d42b410eb1b1",
        "Name": "Loader.classloader.generics",
        "State": "Finished"
    },
    {
        "DetailsUrl": "https://helix.dot.net/api/2019-06-17/jobs/b3373b29-ba30-42f2-b978-d42b410eb1b1/workitems/PayloadGroup0",
        "Job": "b3373b29-ba30-42f2-b978-d42b410eb1b1",
        "Name": "PayloadGroup0",
        "State": "Finished"
    },
    {
        "DetailsUrl": "https://helix.dot.net/api/2019-06-17/jobs/b3373b29-ba30-42f2-b978-d42b410eb1b1/workitems/baseservices.threading",
        "Job": "b3373b29-ba30-42f2-b978-d42b410eb1b1",
        "Name": "baseservices.threading",
        "State": "Finished"
    },
    {
        "DetailsUrl": "https://helix.dot.net/api/2019-06-17/jobs/b3373b29-ba30-42f2-b978-d42b410eb1b1/workitems/profiler.eventpipe",
        "Job": "b3373b29-ba30-42f2-b978-d42b410eb1b1",
        "Name": "profiler.eventpipe",
        "State": "Finished"
    },
    {
        "DetailsUrl": "https://helix.dot.net/api/2019-06-17/jobs/b3373b29-ba30-42f2-b978-d42b410eb1b1/workitems/profiler.gc",
        "Job": "b3373b29-ba30-42f2-b978-d42b410eb1b1",
        "Name": "profiler.gc",
        "State": "Finished"
    },
    {
        "DetailsUrl": "https://helix.dot.net/api/2019-06-17/jobs/b3373b29-ba30-42f2-b978-d42b410eb1b1/workitems/profiler.rejit",
        "Job": "b3373b29-ba30-42f2-b978-d42b410eb1b1",
        "Name": "profiler.rejit",
        "State": "Finished"
    },
    {
        "DetailsUrl": "https://helix.dot.net/api/2019-06-17/jobs/b3373b29-ba30-42f2-b978-d42b410eb1b1/workitems/profiler.unittest",
        "Job": "b3373b29-ba30-42f2-b978-d42b410eb1b1",
        "Name": "profiler.unittest",
        "State": "Finished"
    }
]
```

**Closed** 2020-05-06 18:13 UTC
Labels: area-Infrastructure-coreclr

**Comment by tannergooding** [comment] 2020-05-06 20:35
> /cc @BruceForstall @tannergooding @echesakovMSFT
for the regressing SIMD/Vector3Interop* tests

This looks to be for @AaronRobinsonMSFT as well. They are all related to `Non-blittable parameter types are invalid for UnmanagedCallersOnly methods.`, which I wouldn't expect for `Vector2`, `Vector3`, or `Vector4` which should all be blittable and classified as "user-defined" structs for ABI and marshaling purposes.

**Comment by AaronRobinsonMSFT** [comment] 2020-05-06 21:52
@tannergooding The issue is related to returned `ValueTypes` for delegates marked with `UnmanagedCallersOnlyAttributes` - which is now done automatically.

https://github.com/dotnet/runtime/blob/f4a67dfe8528126ef4330eb433a433f7b8713759/src/coreclr/src/vm/dllimport.cpp#L3506-L3520

I will update the location where we implicitly mark reverse P/Invokes with `UnmanagedCallersOnlyAttributes`.

https://github.com/dotnet/runtime/blob/f4a67dfe8528126ef4330eb433a433f7b8713759/src/coreclr/src/vm/ilstubcache.cpp#L296-L305

/cc @jkotas

**Comment by AaronRobinsonMSFT** [comment] 2020-05-06 21:56
>I will update the location where we implicitly mark reverse P/Invokes with UnmanagedCallersOnlyAttributes.

Hmm can't do that it seems... I will need to dig more into this.
