### ISSUE TITLE
JsonSerializer.Serialize fails in Xamarin Forms iOS

### ISSUE THREAD

**Issue by stesvis** [dotnet/runtime#49395] opened 2021-03-09 23:10 UTC
I am trying to serialize and deserialize an object in the .NET Standard project of a Xamarin Forms app, in the iOS platform. and it throws an exception if my object class inherits from [ReactiveObject](https://www.reactiveui.net/api/reactiveui/reactiveobject/).

### Description

I have an object like this:
```cs
private IEnumerable<SystemSettingDTO> data {get; set; }
```
Where **SystemSettingDTO** is:
```cs
    public class SystemSettingDTO : ReactiveObject
    {
        public int Id { get; set; }
        public DateTime CreatedAt { get; set; }
        [Reactive] public string Name { get; set; }
        [Reactive] public object Value { get; set; }
        public string Status { get; set; }
    }
```

`data` contains these values:
```json
[
  {
    "Name": "DefaultSearchRange",
    "Value": 500,
    "Status": "A",
    "Id": 1,
    "CreatedAt": "2021-03-08T22:19:09.2465295"
  },
  {
    "Name": "MaxSearchRange",
    "Value": 500,
    "Status": "A",
    "Id": 2,
    "CreatedAt": "2021-03-08T22:19:09.2466545"
  }
]
```

I am trying to serialize `data` to a string:
```cs
var json = System.Text.Json.JsonSerializer.Serialize(data);
```
But I get this exception:

> System.TypeInitializationException: The type initializer for 'System.Text.Json.JsonSerializer' threw an exception. ---> System.MissingMethodException: Method not found: int System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8(System.ReadOnlySpan1<byte>)

**NOTE**
The serialization works perfectly in Android.
The serialization also works in iOS if I don't inherit from ReactiveObject, so, if SystemSettingDTO is like this, everything works:
```cs
    public class SystemSettingDTO
    {
        public int Id { get; set; }
        public DateTime CreatedAt { get; set; }
        public string Name { get; set; }
        public object Value { get; set; }
        public string Status { get; set; }
    }
```

But unfortunately I do need that inheritance.

### Configuration

> Microsoft Visual Studio Community 2019
> Version 16.9.0
> VisualStudio.16.Release/16.9.0+31025.194
> Microsoft .NET Framework
> Version 4.8.03752
> 
> Installed Version: Community
> 
> Visual C++ 2019 00435-60000-00000-AA518
> Microsoft Visual C++ 2019
> 
> ASP.NET and Web Tools 2019 16.9.687.37626
> ASP.NET and Web Tools 2019
> 
> ASP.NET Core Razor Language Services 16.1.0.2107702+c4adaa061f13292143de82a96c71341e50bc4032
> Provides languages services for ASP.NET Core Razor.
> 
> ASP.NET Web Frameworks and Tools 2019 16.9.687.37626
> For additional information, visit https://www.asp.net/
> 
> Azure App Service Tools v3.0.0 16.9.687.37626
> Azure App Service Tools v3.0.0
> 
> Azure Functions and Web Jobs Tools 16.9.687.37626
> Azure Functions and Web Jobs Tools
> 
> C# Tools 3.9.0-6.21124.20+db94f4cc8c78a7cd8cf9cfdae091158d2ba9d974
> C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
> 
> CleanBinAndObjCommand Extension 1.1.1
> CleanBinAndObjCommand Visual Studio Extension Detailed Info
> 
> CodeMaid 11.2.231
> CodeMaid is an open source Visual Studio extension to cleanup and simplify our C#, C++, F#, VB, PHP, PowerShell, R, JSON, XAML, XML, ASP, HTML, CSS, LESS, SCSS, JavaScript and TypeScript coding.
> 
> CommandJSON2CSharp Extension 1.0
> CommandJSON2CSharp Visual Studio Extension Detailed Info
> 
> Common Azure Tools 1.10
> Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
> 
> Extensibility Message Bus 1.2.6 (master@34d6af2)
> Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.
> 
> IntelliCode Extension 1.0
> IntelliCode Visual Studio Extension Detailed Info
> 
> Microsoft Azure Tools 2.9
> Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40218.1
> 
> Microsoft Continuous Delivery Tools for Visual Studio 0.4
> Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.
> 
> Microsoft JVM Debugger 1.0
> Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines
> 
> Microsoft Library Manager 2.1.113+g422d40002e.RR
> Install client-side libraries easily to any web project
> 
> Microsoft MI-Based Debugger 1.0
> Provides support for connecting Visual Studio to MI compatible debuggers
> 
> Microsoft Visual C++ Wizards 1.0
> Microsoft Visual C++ Wizards
> 
> Microsoft Visual Studio Tools for Containers 1.1
> Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.
> 
> Microsoft Visual Studio VC Package 1.0
> Microsoft Visual Studio VC Package
> 
> Mono Debugging for Visual Studio 16.9.7 (df23ba6)
> Support for debugging Mono processes with Visual Studio.
> 
> NuGet Package Manager 5.9.0
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/
> 
> PowerShell Pro Tools for Visual Studio 1.0
> A set of tools for developing and debugging PowerShell scripts and modules in Visual Studio.
> 
> Productivity Power Tools 2017/2019 16.0
> Installs the individual extensions of Productivity Power Tools 2017/2019
> 
> ProjectServicesPackage Extension 1.0
> ProjectServicesPackage Visual Studio Extension Detailed Info
> 
> SQL Server Data Tools 16.0.62102.01130
> Microsoft SQL Server Data Tools
> 
> StylerPackage Extension 1.0
> StylerPackage Visual Stuido Extension Detailed Info
> 
> Syncfusion Xamarin Project Templates 13.4.0.53
> A multi-project template for building iOS, Android, and Windows apps using Syncfusion Xamarin components.
> 
> Syncfusion Xamarin Toolbox 16.2.0.19
> Syncfusion Essential Studio for Xamarin Toolbox Visual Studio extension.
> 
> SyncfusionMenu Extension 1.0
> SyncfusionMenu Visual Studio Extension Detailed Info
> 
> TGit 1.0
> Control TortoiseGit from within Visual Studio
> 
> TypeScript Tools 16.0.30201.2001
> TypeScript Tools for Microsoft Visual Studio
> 
> Visual Basic Tools 3.9.0-6.21124.20+db94f4cc8c78a7cd8cf9cfdae091158d2ba9d974
> Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
> 
> Visual F# Tools 16.9.0-beta.21102.9+7ce7132f1459095e635194d09d6f73265352029a
> Microsoft Visual F# Tools
> 
> Visual Studio Code Debug Adapter Host Package 1.0
> Interop layer for hosting Visual Studio Code debug adapters in Visual Studio
> 
> Visual Studio Container Tools Extensions 1.0
> View, manage, and diagnose containers within Visual Studio.
> 
> Visual Studio Tools for Containers 1.0
> Visual Studio Tools for Containers
> 
> VisualStudio.DeviceLog 1.0
> Information about my package
> 
> VisualStudio.Foo 1.0
> Information about my package
> 
> VisualStudio.Mac 1.0
> Mac Extension for Visual Studio
> 
> VSColorOutput 2.73
> Color output for build and debug windows - https://mike-ward.net/vscoloroutput
> 
> Xamarin 16.9.000.271 (d16-9@863670b)
> Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.
> 
> Xamarin Designer 16.9.0.316 (remotes/origin/d16-9@fdbf64026)
> Visual Studio extension to enable Xamarin Designer tools in Visual Studio.
> 
> Xamarin Templates 16.9.68 (8e9b569)
> Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.
> 
> Xamarin.Android SDK 11.2.0.21 (d16-9/93eab59)
> Xamarin.Android Reference Assemblies and MSBuild support.
> Mono: 5e9cb6d
> Java.Interop: xamarin/java.interop@d6d86b2
> ProGuard: Guardsquare/proguard@912d149
> SQLite: xamarin/sqlite@daff8f4
> Xamarin.Android Tools: xamarin/xamarin-android-tools@9d8924d
> 
> Xamarin.iOS and Xamarin.Mac SDK 14.14.2.5 (3836759d4)
> Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Regression?

I never tried it before.

### Other information
Full exception:
> System.TypeInitializationException: The type initializer for 'System.Text.Json.JsonSerializer' threw an exception. ---> System.MissingMethodException: Method not found: int System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8(System.ReadOnlySpan1<byte>) at System.Text.Json.JsonEncodedText.EncodeHelper (System.ReadOnlySpan1[T] utf8Value, System.Text.Encodings.Web.JavaScriptEncoder encoder) [0x00000] in <7e3a59f5e4004edbb4b17c580799cc52>:0
> at System.Text.Json.JsonEncodedText.TranscodeAndEncode (System.ReadOnlySpan1[T] value, System.Text.Encodings.Web.JavaScriptEncoder encoder) [0x00033] in <7e3a59f5e4004edbb4b17c580799cc52>:0 at System.Text.Json.JsonEncodedText.Encode (System.ReadOnlySpan1[T] value, System.Text.Encodings.Web.JavaScriptEncoder encoder) [0x00014] in <7e3a59f5e4004edbb4b17c580799cc52>:0
> at System.Text.Json.JsonEncodedText.Encode (System.String value, System.Text.Encodings.Web.JavaScriptEncoder encoder) [0x00014] in <7e3a59f5e4004edbb4b17c580799cc52>:0
> at System.Text.Json.JsonSerializer..cctor () [0x00042] in <7e3a59f5e4004edbb4b17c580799cc52>:0

**Comment by eiriktsarpalis** [comment] 2021-03-10 12:18
The fact that it's a `MissingMethodException` makes me suspect there might be an issue with the project setup. It would be interesting to find out the versions of both `System.Text.Json.dll` and `System.Text.Encodings.Web.dll`. Would it be possible to share a minimal project that reproduces the issue?

**Comment by stesvis** [comment] 2021-03-10 16:49
@eiriktsarpalis Sure I'll try to make one that can reproduce it.

**Comment by stesvis** [comment] 2021-03-11 15:43
@eiriktsarpalis I made a sample repo where i can "partially" reproduce it.
https://github.com/stesvis/SerializationTest

In this sample:

- System.Text.Json works with/without inheriting from ReactiveObject. Not sure why, as I use the same class with the same properties as in my real project
- Newtonsoft does not work if I inherit from ReactiveObject

Take this code as a reference: https://github.com/stesvis/SerializationTest/blob/master/BlankApp1/ViewModels/MainPageViewModel.cs#L41

`Json2` uses Newtonsoft and it returns `[{}, {}]`.
If you remove `:ReactiveObject` from 
```
    public partial class BaseDTO : ReactiveObject
    {
        public int Id { get; set; }
    }
```
then also Newtonsoft works.

Like I said, i am not able to reproduce the `Method not found` exception here. Could it depend on other packages that I have in the real app?

**Comment by KernelGamut32** [comment] 2021-03-11 15:50
I was seeing the same issue and found a link to another issue that includes an explanation and workaround (in the thread and sub-thread) that fixed mine (https://github.com/mono/mono/issues/20894). Don't know if it will help you with yours as well but sending along just in case.

**Comment by stesvis** [comment] 2021-03-11 16:15
> I was seeing the same issue and found a link to another issue that includes an explanation and workaround (in the thread and sub-thread) that fixed mine ([mono/mono#20894](https://github.com/mono/mono/issues/20894)). Don't know if it will help you with yours as well but sending along just in case.

Unfortunately that gives me a build error:

> error CS0012: The type 'ReadOnlySpan<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

And Visual Studio higlights this line:
`System.Text.Json.JsonSerializer.Deserialize`

**Comment by eiriktsarpalis** [comment] 2021-03-11 16:29
> Like I said, I am not able to reproduce the Method not found exception here. Could it depend on other packages that I have in the real app?

Unfortunately, this is not something we could work with from a System.Text.Json perspective. Next steps for you would be to either attempt to share a minimal reproduction or pursue https://github.com/mono/mono/issues/20894 which seems to be reporting an identical issue.

**Comment by stesvis** [comment] 2021-03-11 19:07
> Using [mono/mono#20894](https://github.com/mono/mono/issues/20894) and this linked issue --> [mono/mono#20805 (comment)](https://github.com/mono/mono/issues/20805#issuecomment-791440473)), I was able to get it working by adding the following to my Xamarin.iOS executable .csproj file:
> 
> ![image](https://user-images.githubusercontent.com/25084145/110821806-6fd99800-825e-11eb-89b6-ec63373f5488.png)
> 
> This pulled in the necessary references I needed and fixed my "missing method exception". Hope it helps!

@KernelGamut32 That worked!
I initially added that to the "PCL" project too but it threw errors. Adding it to **iOS only**, worked.

**Comment by eiriktsarpalis** [comment] 2021-03-11 19:22
I'm going to close this issue, in favor of the report in https://github.com/mono/mono/issues/20894. We can re-evaluate if more information comes to light.

**Closed by eiriktsarpalis** 2021-03-11 19:22 UTC
Labels: area-System.Text.Json, needs more info, untriaged
