### ISSUE TITLE
.NET SDK 7.0.401 and msquic 2.2.0 break HTTP/3 on Linux

### ISSUE THREAD

**Issue by alexandrehtrb** [dotnet/runtime#92617] opened 2023-09-26 01:16 UTC
### Description

On Arch Linux x64, HttpClient with RequestVersionExact, app published with:
Configuration = Release
PublishSingleFile = false
PublishReadyToRun = true

MsQuic installed using AUR makepkg and pacman -U ([repo](https://aur.archlinux.org/packages/msquic))

| .NET SDK version | msquic version | HTTP/3 to localhost | HTTP/3 to outside (cloudflare-quic.com) |
|--------------------------|----------------------|----------------------------|-------------------------------------------------------|
| 7.0.306 | 2.1.8 | OK | OK |
| 7.0.306 | 2.2.2 | OK | timeout |
| 7.0.401 | 2.1.8 | unable | unable |
| 7.0.401 | 2.2.2 |  OK | timeout |

Exception that happens with .NET SDK 7.0.401 and msquic 2.1.8:

```
System.Net.Http.HttpRequestException: Requesting HTTP version 3.0 with version policy RequestVersionExact while unable to establish HTTP/3 connection.
   at System.Net.Http.HttpConnectionPool.ThrowGetVersionException(HttpRequestMessage request, Int32 desiredVersion, Exception inner)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Pororoca.Infrastructure.Features.Requester.PororocaRequester.RequestAsync(IPororocaVariableResolver variableResolver, PororocaHttpRequest req, Boolean disableSslVerification, CancellationToken cancellationToken) in /home/alexandre/Projetos/Pororoca/src/Pororoca.Infrastructure/Features/Requester/PororocaRequester.cs:line 39
```

Timeout exception that happens with msquic 2.2.2:
```
System.Net.Http.HttpRequestException: The connection timed out from inactivity. (cloudflare-quic.com:443)
 ---> System.Net.Quic.QuicException: The connection timed out from inactivity.
   at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data)
   at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent)
   at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent)
--- End of stack trace from previous location ---
   at System.Net.Quic.ValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Quic.QuicConnection.FinishConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken)
   at System.Net.Quic.QuicConnection.ConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken)
   at System.Net.Quic.QuicConnection.ConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectQuicAsync(HttpRequestMessage request, DnsEndPoint endPoint, TimeSpan idleTimeout, SslClientAuthenticationOptions clientAuthenticationOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectQuicAsync(HttpRequestMessage request, DnsEndPoint endPoint, TimeSpan idleTimeout, SslClientAuthenticationOptions clientAuthenticationOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp3ConnectionAsync(HttpRequestMessage request, HttpAuthority authority, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Pororoca.Infrastructure.Features.Requester.PororocaRequester.RequestAsync(IPororocaVariableResolver variableResolver, PororocaHttpRequest req, Boolean disableSslVerification, CancellationToken cancellationToken) in /home/alexandre/Projetos/Pororoca/src/Pororoca.Infrastructure/Features/Requester/PororocaRequester.cs:line 39
```

### Reproduction Steps

-

### Expected behavior

-

### Actual behavior

-

**Comment by ManickaP** [comment] 2023-09-26 12:35
I cannot reproduce your timeout, it works for me, also on Arch Linux:
```
StatusCode: 200, ReasonPhrase: 'OK', Version: 3.0, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Date: Tue, 26 Sep 2023 12:18:53 GMT
  Server: cloudflare
  cf-ray: 80cb73bc58bd4119-PRG
  Alt-Svc: h3=":443"
  Content-Type: text/html
  Content-Length: 125959
}
7.0.11
```
This corresponds to 7.0.401 SDK and my MsQuic is 2.2.2+

As for `7.0.401 | 2.1.8 | unable | unable`, that is on purpose due to a security patch. We now require libmsquic 2.2.2+.

**Comment by ManickaP** [comment] 2023-09-27 08:19
I hope I answered this, newer MsQuic is required due to a security patch. Connecting to `cloudflare-quic.com` works for me as well. I'll close this now, feel free to re-open if you find more problems.

**Closed by ManickaP** 2023-09-27 08:19 UTC
Labels: untriaged, area-System.Net.Quic
