### ISSUE TITLE
[Perf -22%] System.Xml.Linq.Perf_XDocument.GetRootElement

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#40088] opened 2020-07-29 17:00 UTC
### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Changes | [diff](https://github.com/dotnet/runtime/compare/90989b46a1f3791dd57d6ae87578fe22d699c106...6ca600396ee2e80e8bf93c72c2b5439aadc86073)

### Regressions in System.Xml.Linq.Perf_XDocument

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier
-- | -- | -- | -- | -- | --
GetRootElement | 7.85 ns | 9.55 ns | 1.22 |  | True

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_28_2020/refs/heads/master_x64_Windows%2010.0.18362/System.Xml.Linq.Perf_XDocument_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_28_2020/refs/heads/master_x64_Windows%2010.0.18362/System.Xml.Linq.Perf_XDocument.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Xml.Linq.Perf_XDocument*';
```
<details>

#### System.Xml.Linq.Perf_XDocument.GetRootElement

```log
[7.284 ; 7.567) | @@@@@@@
[7.567 ; 7.953) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[7.953 ; 8.238) | @@@@@@@
[8.238 ; 8.671) | @@@@@@@@@@@
[8.671 ; 9.057) | @@@@@@@@@@@@@@
[9.057 ; 9.250) | @
[9.250 ; 9.636) | @@@@@@@@@@@@@@@@@@@@@@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by danmosemsft** [comment] 2020-07-29 18:35
See discussion in #40094

**Comment by danmosemsft** [comment] 2020-07-29 20:58
assuming dupe https://github.com/dotnet/runtime/issues/40094

**Comment by danmosemsft** [comment] 2020-07-29 20:58
Let's try the github feature:

Duplicate of #40094

**Comment by danmosemsft** [comment] 2020-07-29 20:59
Duplicate of #40094

**Closed by danmosemsft** 2020-07-29 20:59 UTC
Labels: arch-x64, area-System.Xml, os-windows, tenet-performance, tenet-performance-benchmarks, untriaged

**Comment by krwq** [comment] 2020-07-30 05:45
neat
