### ISSUE TITLE
IComparable<T>.CompareTo<T> inconsistencies

### ISSUE THREAD

**Issue by rwv37** [dotnet/runtime#99722] opened 2024-03-13 21:27 UTC
### Description

The [documentation for ```IComparable<T>``` ](https://learn.microsoft.com/en-us/dotnet/api/system.icomparable-1?view=net-8.0) says, in part:

>If you implement ```IComparable<T>```, you should overload the ```op_GreaterThan```, ```op_GreaterThanOrEqual```, ```op_LessThan```, and ```op_LessThanOrEqual``` operators to return values that are consistent with```CompareTo(T)```

And the [documentation for CompareTo(T)](https://learn.microsoft.com/en-us/dotnet/api/system.icomparable-1.compareto?view=net-8.0#system-icomparable-1-compareto(-0)) in turn says, in part:

>By definition, any object compares greater than null

The example given in the IComparable<T> documentation is consistent with these two things:

```
public int CompareTo(Temperature other)
{
    // If other is not a valid object reference, this instance is greater.
    if (other == null) return 1;

    // The temperature comparison depends on the comparison of
    // the underlying Double values.
    return m_value.CompareTo(other.m_value);
}

// Define the is greater than operator.
public static bool operator >  (Temperature operand1, Temperature operand2)
{
    return operand1.CompareTo(operand2) > 0;
}
```

However, these seem to contradict [the documentation for compiler warning CS0464](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0464?f1url=%3FappId%3Droslyn%26k%3Dk%28CS0464%29), which says, in part:

>A comparison like i == null can be either true of false. A comparison like i > null is always false.

Side note: There's a little typo in that documentation, which maybe you'd want to fix - "true of false" rather than "true or false". Anyway:

I tried it out with a very common class (```Int32```) just to see what it does. At least for that class, for the > and >= operators:

1. The ```CompareTo<T>```` "any object compares greater than null" is correct, and
2. The CS0464 "A comparison like i > null is always false", is correct, and
3. Put those together and the ```IComparer<T>``` "you should overload the ```op_GreaterThan```, ```op_GreaterThanOrEqual```, ```op_LessThan```, and ```op_LessThanOrEqual``` operators to return values that are consistent with```CompareTo(T)```" is necessarily broken.

I guess the word "should" in there doesn't imply "must", but... the whole ```IComparable```/```IEquatable```/```op_Whatever```/```GetHashCode```/```Equals<T>```/```Equals<Object>```/```Object.Equals```/whatever-else-I-am-missing stuff is notoriously difficult, with lots of people confused over exactly what should be implemented and how, and this sure doesn't help.

### Reproduction Steps

Note: ```>``` is demonstrated here, but ```>=``` behaves the same way:

```
Console.WriteLine($"nonnull > null: {new Int32() > null}");
Console.WriteLine($"nonnull.CompareTo(null) > 0: {(new Int32()).CompareTo(null) > 0}");
```

### Expected behavior

LOL, I don't know. That's a big part of the problem. According to ```IComparable<T>``` and ```CompareTo<T>``` (i.e. "consistent operator/CompareTo behavior" plus "objects CompareTo greater than null"), it seems it should output:

```
nonnull > null: True
nonnull.CompareTo(null) > 0: True
```

Whereas according to ```CompareTo<T>``` and CS0464 (i.e., "objects CompareTo greater than null" plus "operators other than == and != are always false for null") it seems like it should output:

```
nonnull > null: False
nonnull.CompareTo(null) > 0: True
```

And according to ```IComparable<T>``` and CS0464 (i.e. ""consistent operator/CompareTo behavior" plus "operators other than == and != are always false for null"), it seems like it should be:

```
nonnull > null: False
nonnull.CompareTo(null) > 0: False
```

### Actual behavior

At least in the case of ```Int32```:

```
nonnull > null: False
nonnull.CompareTo(null) > 0: True
```

### Configuration

* version of .NET: 8.0
* OS and version: Windows 11
* architecture: x64
* specific to that configuration: I don't know. I doubt it.
* If you're using Blazor: I'm not.

**Comment by huoyaoyuan** [comment] 2024-03-14 03:31
`CS0464` is only applicable to **nullable value type**, e.g. `int?`. The `IComparable` contract with null applies to reference type and untyped `object`.

When invoking comparison between `int` and `null`, the operator isn't really implemented by `int`. It's synthesized by the compiler.

Note that the operators and `IComparable<T>`/`IEquatable<T>` have different in contract. It's more observable with floating point types, for example comparing `NaN` with anything produces `false`, even with itself. In contrast, `IComparable` gives anything an order, because it's the implementation to sort a list.

Strictly speaking, this is not a runtime question, since the comparison operators of **nullable value type** doesn't exist at runtime. They are totally synthesized by C#/VB compiler.

**Comment by tannergooding** [comment] 2024-06-24 18:17
Closing as by design as per the explanation above. The exact interplay between value types and null, especially in relation to nullable value types, tends to be a bit special.

**Closed by tannergooding** 2024-06-24 18:17 UTC
Labels: area-System.Runtime, untriaged
