### ISSUE TITLE
Unified IAsyncQueryable, IAsyncQueryableProvider support

### ISSUE THREAD

**Issue by yruson** [dotnet/runtime#1225] opened 2019-12-31 04:24 UTC
.net's support for asynchronous programming is great. We keep the asynchronous programming model as much as possible during development. However, I encountered a tricky thing when using IQueryable <T> for operation.

Entity Framework / MongoDB Driver and other extensions such as FirstOrDefaultAsync (), ToListAsync (), etc., but each class library is its own independent implementation, I have to reference all class libraries and judgments in the infrastructure layer to achieve uniformity API.

It is expected to unify the asynchronous programming model of Queryable <T> from the framework level, and other third-party class libraries can implement this interface. Application developers do not need to pay attention to details.

**Comment by eiriktsarpalis** [comment] 2020-11-27 10:56
Duplicate of https://github.com/dotnet/roslyn/issues/32569.

**Closed by eiriktsarpalis** 2020-11-27 10:56 UTC
Labels: api-suggestion, area-System.Linq
