### ISSUE TITLE
ConfigurationBuilder - Configuration.Json: Binding a Dictionary<string,string> error when Key contains an string url like http://www.google.es

### ISSUE THREAD

**Issue by ghost** [dotnet/runtime#42643] opened 2020-09-21 18:19 UTC
### Describe the bug

Im reading a json file to a dictionary<string,string> like:

```json
{
  "auths": {
    "https://www.google.es": {
      "uri": "https://www.google.es"
    }
  }
}
```
having the POCO class
```csharp
public class MyClass
{
        [ConfigurationProperty("auths", IsRequired = false)]
        public Dictionary<string, OtherObject> Auths { get; set; }
}
```

When i load it using ConfigurationRoot like
```csharp
public MyClass Read()
        {
            IConfigurationRoot configuration =
                new ConfigurationBuilder()
                    .AddJsonFile("path_to_json_file", optional: true, reloadOnChange: true)
                .Build();

            // Try Parse and return (if will exception in case of binding error)
            var _settings= new MyClass();
            configuration.Bind(_settings);

            return _settings;
        }
```

The issue is that the Dictionary item contains https only on the Key property. Looks like it's ignoring or having issues with https://.....

Not sure if it's an intended feature or a bug.

### To Reproduce
1. Using version '3.1.8' of package 'Microsoft.Extensions.Configuration.Json'
2. Run this code 'with files in description'
4. See error in the screenshot attached

### Expected behavior
Dictionary Key Item should contains https://www.google.es

### Screenshots

![image](https://user-images.githubusercontent.com/3371798/93805226-b6ebb680-fc47-11ea-9573-5de86bb4d4f0.png)

**Comment by BrennanConroy** [comment] 2020-09-23 20:34
Maybe we want to have an escape sequence for json config so this is allowed? Or a flag to disable the ':' behavior just for Json?

If any change is made, we should port it to the Newtonsoft.Json config provider in Extensions.

**Comment by JunTaoLuo** [comment] 2020-09-23 20:37
Looks like this issue has been encountered previously, e.g. https://github.com/aspnet/Configuration/issues/792 https://github.com/dotnet/extensions/issues/782. Sounds like something we should address instead of our usual answer that `:` is a reserved character and this issue is by design.

**Comment by SteveDunn** [comment] 2022-03-19 18:52
I had a quick look at this. By replacing `:` with a backtick `\``, we end up with this from `JsonConfigurationFileParser`:
![image](https://user-images.githubusercontent.com/263416/159133922-f823bde7-a837-4f99-9965-5c7e96eedd8a.png)

Then, I think we'd need to override:
```csharp
public virtual IEnumerable<string> ConfigurationProvider::GetChildKeys(
            IEnumerable<string> earlierKeys,
            string? parentPath)
```

... because that expects `:` delimited values - as can be seen here:

![image](https://user-images.githubusercontent.com/263416/159134523-276bb52f-7082-4ab3-9320-9000dd86bf94.png)

**Comment by SteveDunn** [comment] 2022-03-19 19:12
I'm happy to look at this one. I did a quick work-in-progress PR here: https://github.com/dotnet/runtime/pull/66886
Note that it doesn't work and breaks lots of other tests, but might act as a good starting point to get this Issue complete.

**Comment by SteveDunn** [comment] 2022-03-22 06:45
> The separator char does not look easy to change at run time: https://github.com/dotnet/extensions/blob/1774c15ac24c65513fa9fc1f4fbb69be9a2a4e25/src/Configuration/Config.Abstractions/src/ConfigurationPath.cs#L14-L17

I've had a go here: https://github.com/dotnet/runtime/pull/66886

**Comment by AraHaan** [comment] 2022-03-22 10:04
I do not see the reason for ``:``'s in json keys due to how everything gets messed up at runtime with them in the keys. Also it seems to make the json more verbose. I would think this should be by design.

**Comment by tebeco** [comment] 2022-03-23 07:01
also, changing to a backtick would just prevent someone using backtick just like you're blocked now

you're describing an array, but you're writing object.
Here is a configuration with array:
```json
{
  "auths": [
    {
      "name": "http://google",
      "uri": "https://www.google.es"
    },
    {
      "name": "http://microsoft",
      "uri": "https://www.microsoft.es"
    }
  ]
}
```

```cs
public record AuthEntry(string Name, Uri Uri);
public class AuthsOptions
{
  public const string SectionName = "auths";
  public AuthEntry[] Auths {get;set;}
}

public static class AuthsServiceCollectionExtensions
{
  public static IServiceCollection AddAuths(this IServiceCollection services)
  {
    services
      .AddOptions<AuthsOptions>()
      .Configure<IConfiguration>((options, configuration) => configuration.Bind(AuthsOptions.SectionName, options)
      //.Validate(...............)
    ;

    return services;
  }

  public static IServiceCollection AddAuths(this IServiceCollection services, Action<AuthsOptions> 
  configure) =>
    services
      .AddAuths()
      .Configure(configure)
    ;
```

**Comment by eerhardt** [comment] 2022-07-14 21:38
We will consider this in a future release. Moving this issue out of the 7.0 milestone.

**Comment by SteveDunn** [comment] 2022-10-31 21:38
This is the motivation behind https://github.com/dotnet/runtime/issues/67616

**Comment by rjgotten** [comment] 2023-04-26 09:50
> you're describing an array, but you're writing object.

Many times you _have_ to use objects by necessity as arrays are completely useless for everything but the most basic configuration needs when you use environment-specific configuration overrides. This is because arrays use positional (index) based merging across environment-specific config files which is an absolute pain to manage and slip-ups in it are many times impossible to detect. 

Basically; you're telling people: "You're doing it wrong. You're _supposed_ to step into this minefield here."

**Comment by rjgotten** [comment] 2023-04-26 09:58
> Looks like this issue has been encountered previously, e.g. [aspnet/Configuration#792](https://github.com/aspnet/Configuration/issues/792) [dotnet/extensions#782](https://github.com/dotnet/extensions/issues/782). Sounds like something we should address instead of our usual answer that `:` is a reserved character and this issue is by design.

There was never any technical need for the `:` to be a reserved character to begin with.
That problem stems from the fact that the initial design for the internal storage of the configuration data in `Microsoft.Extensions.Configuration` was thought out poorly and stores everything in a flat dictionary by fully composed key, rather than use an appropriate tree-based data structure.

There are multiple other issues where this ill-thought out design is the root of the problem.
For instance; the performance problems with the ConfigurationBinder, when binding collection types. Because it has to loop over the entire collection of keys every time to determine which full keys are children of the collection key.

That was reported in #65885 as well, but ultimately wasn't acted upon (yet) because of fear of breaking existing implementations as well. At least _that_ had a decent workaround.

**Comment by layomia** [comment] 2023-07-21 19:33
Collapsing this into https://github.com/dotnet/runtime/issues/67616 since that would be the fundamental change to enable this scenario.

**Closed by layomia** 2023-07-21 19:33 UTC
Labels: enhancement, api-needs-work, area-Extensions-Configuration
