### ISSUE TITLE
Assertion failed: 'isRegAvailable(reg, physRegRecord->registerType)'

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#47095] opened 2021-01-18 02:05 UTC
Job : [runtime-coreclr jitstressregs 20210117.1](https://dev.azure.com/dnceng/public/_build/results?buildId=954707&view=ms.vss-test-web.build-test-results-tab)

Failed tests:
```
CoreCLR Linux arm Checked jitstressregs0x80 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
        - JIT/Methodical/fp/exgen/10w5d_cs_do/10w5d_cs_do.sh
        - JIT/superpmi/superpmicollect/10w5d_cs_do/10w5d_cs_do.sh
```

Error message:
```
Assert failure(PID 3703 [0x00000e77], Thread: 3703 [0x0e77]): Assertion failed 'isRegAvailable(reg, physRegRecord->registerType)' in 'testout1:Func_0_5_2_4():float' during 'LSRA build intervals' (IL size 212)

    File: /__w/1/s/src/coreclr/jit/lsra.cpp Line: 5474
    Image: /root/helix/work/correlation/corerun

/root/helix/work/workitem/JIT/superpmi/superpmicollect/10w5d_cs_do/10w5d_cs_do.sh: line 388:  3703 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/JIT/superpmi/Reports/JIT.superpmi/superpmicollect/10w5d_cs_do/10w5d_cs_do.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun 10w5d_cs_do.dll ''
Func_0_6_5_6_3: != true
Func_0_6_5_4_6: <= true
Func_0_6_5_4_5: > true
Func_0_6_5_4_3: == false
Func_0_6_4_6_2: != true
Func_0_6_4_5_4: < true
Func_0_6_4_5_1: < true
Func_0_6_4_4: <= true
Func_0_6_3_6_5: == false
Func_0_6_3_4_4: <= true
Func_0_6_3_4_3: < true
Func_0_6_3_3: < true
Func_0_6_3_2_3: >= true
Func_0_6_3_1_5: < true
Func_0_6_3_1: <= false
Func_0_6_3: != true
Func_0_6_2_5: != true
Func_0_6_2_1: > false
Func_0_6_1_6_4: < false
Func_0_6_1_6_3: > false
Func_0_6_1_5_4: > true
Func_0_6_1_3: == false
Func_0_5_6_6_6: <= true
Func_0_5_6_6_1: > true
Func_0_5_6_4_6: <= false
Func_0_5_6_4_2: >= false
Func_0_5_6_3_6: < false
Func_0_5_6_3_1: == false
Func_0_5_6_3: <= true
Func_0_5_6_2_1: >= false
Func_0_5_6_1_3: > true
Func_0_5_6_1: <= false
Func_0_5_5_6: != true
Func_0_5_5_5_6: != true
Func_0_5_5_5_4: == false
Func_0_5_5_5_2: == false
Func_0_5_5_4_5: < true
Func_0_5_5_4: > true
Func_0_5_5_3_4: != true
Func_0_5_5_3_2: <= true
Func_0_5_5_3_1: > true
Func_0_5_5_1: < false
Func_0_5_4_5: >= false
Func_0_5_4_1_3: <= false
Func_0_5_4_1_2: == false
Func_0_5_4: != true
Func_0_5_3_6: != true
Func_0_5_3_5_3: < true
Func_0_5_3_4_2: == false
Func_0_5_3_4_1: >= true
Func_0_5_3_4: <= true
Func_0_5_3_1_2: < true
Func_0_5_3: >= false
Func_0_5_2_6_6: != true
Func_0_5_2_6_3: != true
Func_0_5_2_5_6: != true
Func_0_5_2_5_4: == false
Func_0_5_2_5_3: <= true
Func_0_5_2_5_2: != true
Gathering state for process 3703 corerun
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.3703.dmp
Written 63623168 bytes (15533 pages) to core file
Dump successfully written
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/JIT/superpmi/superpmicollect/10w5d_cs_do/10w5d_cs_do.sh

stack trace:
at JIT_Methodical._fp_exgen_10w5d_cs_do_10w5d_cs_do_._fp_exgen_10w5d_cs_do_10w5d_cs_do_sh()
```

**Comment by VincentBu** [comment] 2021-01-18 02:24
Also failed:
Job: [runtime-coreclr jitstress2-jitstressregs 20210117.1](https://dev.azure.com/dnceng/public/_build/results?buildId=954780&view=ms.vss-test-web.build-test-results-tab)

Failed Tests:
```
CoreCLR Linux arm Checked jitstress2_jitstressregs0x80 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
        - JIT/Regression/CLR-x86-JIT/V1.2-M01/b16570/b16570/b16570.sh
```

Error message:
```
Assert failure(PID 325 [0x00000145], Thread: 325 [0x0145]): Assertion failed 'isRegAvailable(reg, physRegRecord->registerType)' in 'test:Func():double' during 'LSRA build intervals' (IL size 395)

    File: /__w/1/s/src/coreclr/jit/lsra.cpp Line: 5474
    Image: /root/helix/work/correlation/corerun

/root/helix/work/workitem/JIT/Regression/CLR-x86-JIT/V1.2-M01/b16570/b16570/b16570.sh: line 388:   325 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/JIT/Regression/Reports/JIT.Regression/CLR-x86-JIT/V1.2-M01/b16570/b16570/b16570.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun b16570.dll ''
Gathering state for process 325 corerun
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.325.dmp
Written 49741824 bytes (12144 pages) to core file
Dump successfully written
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
> /root/helix/work/workitem/JIT/Regression/CLR-x86-JIT/V1.2-M01/b16570/b16570/b16570.sh
```

**Comment by kunalspathak** [comment] 2021-01-19 21:11
This is a duplicate of https://github.com/dotnet/runtime/issues/46085 and I have https://github.com/dotnet/runtime/pull/46939 to fix it.

**Closed by kunalspathak** 2021-01-19 21:11 UTC
Labels: JitStress, arch-arm32, area-CodeGen-coreclr, os-linux
