### ISSUE TITLE
dotnet-counters stuck at "Waiting for initial payload..." for hostfxr-hosted application

### ISSUE THREAD

**Issue by ladenedge** [dotnet/runtime#44910] opened 2020-09-10 03:13 UTC
I have a .NET 5.0 application I would like to analyze with **dotnet-counters**.  Following [Debug a memory leak in .NET Core][1], I am able to list its PID in the normal ways:

```dos
C:\MyServer>dotnet-counters ps
      1164 myserver C:\MyServer\Debug\myserver.exe

C:\MyServer>dotnet-trace ps
      1164 myserver C:\MyServer\Debug\myserver.exe
```

However, when I try to monitor its counters, it just hangs:

```dos
C:\MyServer>dotnet-counters monitor --refresh-interval 1 -p 1164

Press p to pause, r to resume, q to quit.
    Status: Waiting for initial payload...
```

My application is special in that it is hosted inside a native 64-bit EXE using [the hostfxr_* API](https://docs.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting#create-a-host-using-nethosth-and-hostfxrh).

Otherwise, the application is working fine. I'm on Windows 10, using SDK **v5.0.100-preview.8.20417.9.** All of the dotnet-* tools are the latest versions from **dotnet tool install**.

Is there something special required to enable counters?

  [1]: https://docs.microsoft.com/en-us/dotnet/core/diagnostics/debug-memory-leak

**Comment by tommcdon** [comment] 2020-12-09 23:34
Closing since we were not able to repro the issue. Please let us know if the issue is still reproducing and we will re-activate it.

**Closed by tommcdon** 2020-12-09 23:34 UTC
Labels: area-Diagnostics-coreclr
