### ISSUE TITLE
Failing test `System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#87039] opened 2023-06-02 01:10 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=293100
Build error leg or test failing: System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue
Pull request: https://github.com/dotnet/runtime/pull/86048

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step).

```json
{
  "ErrorMessage": "System.Net.Quic.Tests.MsQuicPlatformDetectionTests.SupportedLinuxPlatforms_IsSupportedIsTrue [FAIL]",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by jkotas** [comment] 2023-06-02 03:56
Duplicate of https://github.com/dotnet/runtime/issues/87038

**Closed by jkotas** 2023-06-02 03:56 UTC
Labels: area-Infrastructure-libraries, blocking-clean-ci, untriaged, area-System.Net.Quic, Known Build Error
