### ISSUE TITLE
DllImport from libc should support loading symbols from the global relocation table

### ISSUE THREAD

**Issue by ddrinka** [dotnet/runtime#65165] opened 2022-02-10 23:33 UTC
### Description

I'm attempting to use a kernel-bypass network tool, OpenOnload, with .Net on Linux.  The tool uses LD_PRELOAD to swap calls to libc socket functions with its own implementation.  This works fine for the CLR-provided `Socket` functionality.  However I also need to `DllImport` a number of functions from libc to manage things like hardware timestamps.

When I DllImport from libc, the LD_PRELOAD-swapped socket functions are bypassed and the native libc implementations are used instead.

I believe the solution to this is to provide `RTLD_DEFAULT` as the handle to a call to `dlsym`.  This would search the global relocation table for the first-registered symbol name, which OpenOnload provides, or else the default libc symbol.  I thought perhaps a custom `DllImportResolver` could return that handle for libc lookups.  Sadly, `RTLD_DEFAULT = 0`, and so all the handle-not-null checks that assume zero is an error will not allow this handle to be utilized.

### Reproduction Steps

- LD_PRELOAD a library that "overloads" default libc functions.
- DllImport one of the overloaded functions from "libc".

### Expected behavior

The imported function is the overloaded function.

### Actual behavior

The imported function is not the overloaded function.  It is instead the base libc implementation.

### Known Workarounds

Use a custom DllImportResolver to redirect loads of libc to the LD_PRELOADed library.

The danger of this solution is that it breaks the connection between the CLR-provided implementation and the DllImported implementation.  For my scenario, if `LD_PRELOAD` is not utilized to load OpenOnload for the CLR, but the library is detected on the system and the DllImport calls do point to OpenOnload, socket handles cannot be passed back and forth between the CLR and the DllImport functions.  It would be a better solution for LD_PRELOAD to work.

### Other information

- https://github.com/dotnet/runtime/blob/d603356dfbf09616e55bd99ed840aa20468a9e57/src/coreclr/vm/nativelibrary.cpp#L816 restricts 0 return from custom DllImportResolver
- https://github.com/dotnet/runtime/blob/d603356dfbf09616e55bd99ed840aa20468a9e57/src/coreclr/vm/nativelibrary.cpp#L275 checks for non-null handle

**Comment by jkoritzinsky** [comment] 2022-02-11 00:46
This is a duplicate of https://github.com/dotnet/runtime/issues/56331 and is being implemented with https://github.com/dotnet/runtime/pull/57610

**Closed by jkoritzinsky** 2022-02-11 00:46 UTC
Labels: area-Interop-coreclr, untriaged
