### ISSUE TITLE
Add method bool TryGetCount(out int) to IEnumerable<T>

### ISSUE THREAD

**Issue by linknoid** [dotnet/runtime#41965] opened 2020-09-08 14:34 UTC
## Background and Motivation

Frequently code uses Linq or Linq-like methods to perform operations on collections.  Even though you may know the size of the original collection, and there is a 1-to-1 mapping between that original collection and the output sequence, the size of the output sequence gets lost along the way.  This proposal would allow that count to be propagated along with the elements of the sequence to methods which consume the sequence and would benefit from knowing the count up front.

## Proposed API

IEnumerable<T> should have a bool TryGetCount(out int count) method with a default implementation.  The default implementation should return false and assign 0 to count.  ICollection<T> should override this implementation to return true and set count to the collection count.  Things which implement IEnumerable<T> could then decide on a case-by-case basis whether they can provide an accurate count or not.  If getting the count is a cheap operation, that count should be assigned and return true, but if it involves actual enumerating, it should return false.

By making it a default implementation, existing code can ignore the change or implement the method to take advantage of this functionality.

This count could be propagated and used by many different Linq methods to avoid allocating an enumerator when unnecessary.  Select(), OrderBy() Reverse(), AsEnumerable() and Cast() could simply be pass-throughs.  Append(), Prepend(), Concat(), DefaultIfEmpty(), Range(), Skip(), Take(), SkipLast(), and TakeLast() could trivially calculate the count if their source does.  Many other methods would be able to propagate a 0 if it's known to be 0 and false for anything else.  Distinct() could propagate a 1 or 0, and false for anything else. This value could then be used (if available) by Count(), Any(), All(), SequenceEquals(), ToArray(), ToList(), ToDictionary(), and other user-defined methods.

If this is added, it may be possible in the future to add a C# language feature to "yield count" at the beginning of a method which contains yield returns.  But this is not part of the current proposal.

```diff
namespace System.Collections.Generic
{
    public interface IEnumerable<out T> : System.Collections.IEnumerable
    {
+        bool TryGetCount(out int count) { count = 0; return false; }

```

## Usage Examples

``` C#
    var list = new List<int>();
    list.AddRange(Enumerable.Range(1, 500));
    DoSomething( list.Select( i => 1.0 / i ) );

    private void DoSomething(IEnumerable<double> values)
    {
        if (values.Any()) // Any() would check the count without having to create an Enumerator
        {
            double[] x = values.ToArray();  // ToArray() could pre-determine the size of array to allocate
        }
    }

```

## Alternative Designs

Another option would be to implement it using void TryGetCount(out int minCount, out int maxCount) to provide a range.  This would allow methods like .Where() to propagate the max count while providing a 0 for the min count.  In exchange, it would make the whole implementation quite a bit messier.  Presumably in this implementation, a negative number would be returned if either bound could not be established.

Adding this to the non-generic System.Collections.IEnumerable could be considered, but cases where a class implements multiple IEnumerable<T> with different meanings would not be able to provide different TryGetCounts.  This may or may not be acceptable, but it would force that class to fail on TryGetCount.

If a new interface were introduced to support this method, it would be less likely to break existing code, but it would mean having to cast each object to that interface to see if it supports this method.  TryGetCount() is implicitly tied to the thing you are enumerating, and it is optional to implement.

Using a return value, such as "int Count" method or property, on a different interface would not allow flexibility in whether a class can retrieve the count, even if the count is only available under certain situations.  If you call Any() and you know the count up front, there's no need to enumerate.  But if you call Any() and don't know the count, making it call Count() would be a major performance loss.  It would mean you would need 2 types returned from Select(), one if the parent knows the count, and one if it doesn't, etc.

Making count a long instead of int could be considered.  But cases where a count overflows an int would be an exceptionally unusual situation, and those cases are probably better handled with other code.  It would be simpler to make TryGetCount fail to return a value in those cases.

## Risks

The big risk I see is if client code already implements TryGetCount with a different meaning, the methods would conflict.  This would force them to provide an explicit implementation of TryGetCount for IEnumerable.  This gets messy if they're compiling against an older framework version but running in a newer version.

**Comment by eiriktsarpalis** [comment] 2020-09-08 16:02
Typically one could do this by writing the following:

```csharp
static bool TryGetCount<T>(this IEnumerable<T> seq, out int count)
{
    if (seq is ICollection<T> collection)
    {
        count = collection.Count;
        return true;
    }

    count = 0;
    return false;
}
```

Sure, this wouldn't work for `Select` IEnumerables, but I don't see why this would justify the added signature complexity.

**Comment by SingleAccretion** [comment] 2020-09-08 17:42
> IEnumerable should have a bool TryGetCount(out int count) method with a default implementation. The default implementation should return false and assign 0 to count. ICollection should override this implementation to return true and set count to the collection count.

I can see you have put a lot of effort into this proposal, @linknoid, but I am afraid this part makes it exceedingly unlikely to be accepted in its current form. The issue is that interfaces implementing methods from their parents are a source of a diamonds. For example, let's say people have this interface today and we implement the proposal as is:
```C#
interface IMyCollection<T> : IEnumerable<T>, ICollection<T>, IReadOnlyList<T> { ... }
```
In .NET 6, everything is fine as `ICollection<T>`'s `TryGetCount` override is chosen as the most specific. However, let's say we add `TryGetCount` implementation to `IReadOnlyList<T>` in .NET 7. Now people upgrading from 6 to 7 will get a runtime error. This is a very simplistic example, but I hope it gets the point across.

In general, any proposals to the runtime repo have to have a high enough benfit/cost ratio to be accepted. Proposals involving DIMs can be safely expected to have the required ratio be a few orders of magnitude greater than usual (it is (half-seriously) said that an optimistic timeline for getting DIMs into the BCL is 2027).

**Comment by NetMage** [comment] 2020-09-15 21:51
I am thinking a simpler addition of `ICollection<T>` to `SelectArrayIterator`, `SelectListIterator` and `SelectIListIterator` might cover many of this proposal's advantages easier?

**Comment by linknoid** [comment] 2020-09-16 01:21
I guess you could split every Linq IEnumerable<T> into 2 concrete classes, one that implements IReadOnlyCollection<T> and the other one that doesn't, and then return the appropriate one depending on the collection it's working on.  It's not as flexible (since sometimes you might be able to determine the count in some situations and not in others), but that seems far less likely to break things.

**Comment by eiriktsarpalis** [comment] 2020-09-16 15:11
Thank you for taking the time to file the proposal @linknoid, but it is unlikely we would accept such a change for the reasons stated previously. I'm going to close this issue cc @adamsitnik @stephentoub

**Closed by eiriktsarpalis** 2020-09-16 15:11 UTC
Labels: api-suggestion, area-System.Linq
