### ISSUE TITLE
JIT.Methodical.eE failed on CoreCLR windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#46459] opened 2020-12-30 00:18 UTC
https://dev.azure.com/dnceng/public/_build/results?buildId=932668&view=ms.vss-test-web.build-test-results-tab&runId=29530724&resultId=102819&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-45941-merge-2c9d9a926eac40899e/JIT.Methodical.eE/console.489f3de2.log?sv=2019-07-07&se=2021-01-17T10%3A46%3A25Z&sr=c&sp=rl&sig=5cAj%2FHVzvC0uE9lrP3kCsrK1J%2FmDVoqKVyYcj345o1k%3D
Console log: 'JIT.Methodical.eE' from job 2c9d9a92-6eac-4089-9ea7-4f61068629da (windows.10.arm64v8.open) executed on machine DDARM64-063

Per query below, the exit code was -1073741502 == STATUS_DLL_INIT_FAILED and this has only happened on Windows10 ARM64. There is essentially no console output - just one line. @mattgal does this indicate a workload failure, or infra?

https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAEAGWRX0%2fCMBTF30n4DldehKRjpS7ITOaD%2fxJMNBowPF%2faq6uwlrRdcMYP7wYER%2bxDm7T3nPu7pwvrVtNAhYduJ45%2fYJuTI3jQRvucFGQZKAwUdEF9wQWPRiIaXQJProS4SvhQXCS8XoNu55%2f0Gozd9qMLrgZwau40GbWunrEg8AFd8FsdcujNKl%2bTDHsts3ZpzdJ7nM6HTxRyq7TE9ZDue23n%2by8dbq0iOMuAtx9mAUPpG4fzG1RN2XnT5NNqAyttVKaNIQePdunBmuacqra%2bvjgiCJmqFFMRjQlllPBJGqWEl1HyPh7x8WQsUoUnVDcOjcx3WkfvPs4JlY8LrId1h8KNs58kA7yWVFLTiR1nYTCvNvXejoIdU2Zwa423a3pzmu25GSwOf9rM8AP0FWohTP2LgwxmtnTyNPaNizflcq3lLnhfFgU6%2fU0gbWlCf8AATdX%2fazOAZdUG3eM19gzurFyRm%2bNHm38f%2fs7butCoD9%2bBXrI%2fJ1DkZbfT7fwCSCEKNpMCAAA%3d&web=0
```
WorkItems 
| where Finished > now(-30d)  
| where FriendlyName == "JIT.Methodical.eE"
| join kind=inner Jobs on JobId
| extend IsPr = Source startswith "pr/public"
| summarize count(), any(ConsoleUri) by QueueName, Type, IsPr, DockerTag, ExitCode, Status
| sort by Status asc, QueueName desc
```
```
QueueName	Type	IsPr	DockerTag	ExitCode	Status	count_
windows.10.arm64v8.open	test/functional/cli/	1		-1073741502	BadExit	3
windows.10.arm64v8.open	test/functional/cli/	0		-1073741502	BadExit	2
windows.10.arm64v8.open	test/functional/r2r/cli/	1		-1073741502	BadExit	1
...
```

**Comment by jkotas** [comment] 2020-12-30 05:14
See https://github.com/dotnet/runtime/pull/46449#issuecomment-752155078

Duplicate of https://github.com/dotnet/core-eng/issues/11777

**Closed by jkotas** 2020-12-30 05:14 UTC
Labels: area-Infrastructure, tracking-external-issue, untriaged
