### ISSUE TITLE
Expression doesn't think ImmutableArray<T> is compatible with an IEnumerable<T> parameter

### ISSUE THREAD

**Issue by NetMage** [dotnet/runtime#41716] opened 2020-09-01 23:31 UTC
### Description

When using an `Expression` tree to create a call to a method that takes an `IEnumerable<T>` parameter, the argument validation calls `TypeUtils.AreReferenceAssignable` which assumes that value types can't be reference assignable to non-value types, so if the type is a value type that implements `IEnumerable<T>` like `ImmutableArray<T>`, the validation fails.

This can be easily seen in code like the following, using [System.Linq.Dynamic.Core](https://github.com/StefH/System.Linq.Dynamic.Core) which builds an `Expression` tree:

    var a = ImmutableArray.Create(1, 2, 3, 4);
    var b1 = a.AsQueryable().OrderBy("it desc").ToList();

This causes an argument exception: ``"Expression of type 'System.Collections.Immutable.ImmutableArray`1[System.Int32]' cannot be used for parameter of type 'System.Collections.Generic.IEnumerable`1[System.Int32]' of method 'System.Linq.IOrderedEnumerable`1[System.Int32] OrderByDescending[Int32,Int32](System.Collections.Generic.IEnumerable`1[System.Int32], System.Func`2[System.Int32,System.Int32])' (Parameter 'arg0')"``

but the equivalent static code accepts `ImmutableArray<T>` as the first argument without issue:

    var b2 = a.OrderByDescending(n => n).ToList();

I suggest the `&& !src.IsValueType` should be removed from the test in `TypeUtils.AreReferenceAssignable`.

### Configuration

This was tested on .Net Core 3.1 on Windows 10 v1909 x64 but the issues appears to be in the code for .Net Framework as well.

**Comment by cston** [comment] 2021-08-11 18:42
Closing as "by design".

**Closed by cston** 2021-08-11 18:42 UTC
Labels: area-System.Linq.Expressions
