### ISSUE TITLE
Cookies loaded from a file are not sent via HttpClientHandler

### ISSUE THREAD

**Issue by DJREMiX6** [dotnet/runtime#90031] opened 2023-08-02 13:13 UTC
### Description

For a better description of the process you can find my answer on StackOverflow [here](https://stackoverflow.com/questions/76790445/save-cookiescollection-to-file-and-read-from-it-in-dot-net-maui-c-sharp).

I created a server in ASP and added authentication to it, when started developing the Android app in MAUI, I wanted to save cookies to a file so whenever I reopen the app, the cookies will be loaded and I can persist the authentication.
I found a problem after loading them from the file, the cookies where loaded correctly but when sending the request through a HttpClient, the cookies loaded from the file were not sent but if I injected a new Cookie in a hard-coded way, it is sent.

After debugging I found that the problem derives from the **Port** property that does something I don't know that makes the cookies not to be sent.

### Steps to Reproduce

- Create a MAUI project.
- Create a class that inherits from HttpClient.

```c#
public class ApiHttpClient : HttpClient
{
    private readonly IUriService _uriService;

    public ApiHttpClient(IUriService uriService, HttpClientHandler httpClientHandler) : base(httpClientHandler)
    {
        _uriService = uriService;
    }

    public async Task SignInAsync(ILoginUserInfo loginUserInfo, CancellationToken? cancellationToken = null)
    {
        var uri = _uriService.AuthenticationSignInPath();
        var httpResponseMessage = await this.PostAsJsonAsync(uri, loginUserInfo,
            cancellationToken ?? new CancellationToken(false));

        //HANDLE RESPONSE
    }
}
```

- Create a class that inherits from CookieContainer.

```c#
public class CookiesService : CookieContainer
{
    private const string COOKIES_FILE_NAME = "biscuits.json";

    private string? _cookiesFilePath;

    public CookiesService()
    {
        _cookiesFilePath = Path.Combine(FileSystem.CacheDirectory, COOKIES_FILE_NAME);
        LoadCookies();
    }

   public void LoadCookies()
    {
        if (!File.Exists(_cookiesFilePath))
        {
            return;
        }

        var cookieFileContent = File.ReadAllText(_cookiesFilePath);
        if (string.IsNullOrWhiteSpace(cookieFileContent))
            return;
        var deserializedCookies = JsonSerializer.Deserialize<CookieCollection>(cookieFileContent);

        if (deserializedCookies != null)
            Add(deserializedCookies);

        var cookies = GetAllCookies();
    }

    public void SaveCookies()
    {
        var cookies = GetAllCookies();

        if (cookies.Count <= 0) return;

        var serializedCookies = JsonSerializer.Serialize(cookies);
        File.WriteAllText(_cookiesFilePath, serializedCookies);
    }
}
```

- Create a class that inherits from HttpClientHandler.

```c#
public class ApiHttpClientHandler : HttpClientHandler
{
    private readonly CookiesService.CookiesService _cookiesService;

    public ApiHttpClientHandler(CookiesService.CookiesService cookiesService)
    {
        _cookiesService = cookiesService;

        UseCookies = true;
        CookieContainer = _cookiesService;
    }

    protected override HttpResponseMessage Send(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        var response = base.Send(request, cancellationToken);
        _cookiesService.SaveCookies();
        return response;
    }

    protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        var response = await base.SendAsync(request, cancellationToken);
        _cookiesService.SaveCookies();
        return response;
    }

}
```

Now when you receive a cookie with no specified port (the port value is **""**) and then its stored, if a request is sent without closing the application, the cookie is sent but if you close and open the application and load the cookies from the file, the cookie is not sent.

### Link to public reproduction project repository

StackOverflow:
https://stackoverflow.com/questions/76790445/save-cookiescollection-to-file-and-read-from-it-in-dot-net-maui-c-sharp

GitHub Repo:
https://github.com/DJREMiX6/-MAUI-BUG-CookiesNotSentAfterBeingLoadedFromAFile

### Version with bug

7.0.86

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 11

### Did you find any workaround?

The only workaround I found that is working is not to set the **Port** property when loading the Cookies from the file:

```c#
public void LoadCookies()
    {
        if (!File.Exists(_cookiesFilePath))
        {
            return;
        }

        var cookieFileContent = File.ReadAllText(_cookiesFilePath);
        if (string.IsNullOrWhiteSpace(cookieFileContent))
            return;
        var deserializedCookies = JsonSerializer.Deserialize<CookieCollection>(cookieFileContent);

        if (deserializedCookies == null) return;

        foreach(var cookie in deserializedCookies.ToArray())
        {
            var cookieCopy = new Cookie(cookie.Name, cookie.Value, cookie.Path, cookie.Domain)
            {
                HttpOnly = cookie.HttpOnly,
                Comment = cookie.Comment,
                CommentUri = cookie.CommentUri,
                Discard = cookie.Discard,
                Expired = cookie.Expired,
                Expires = cookie.Expires,
                Secure = cookie.Secure,
                Version = cookie.Version,
                /* If set, this property is not making the
                     * HttpClientHandler to send the cookie loaded from the cookies file */
                /* Port = cookie.Port,*/
            };
            Add(cookieCopy);
        }
    }
```

**Comment by wfurt** [comment] 2023-08-04 15:58
Is same code working for you on other platforms @DJREMiX6 ?

**Comment by karelz** [comment] 2023-08-04 18:01
@DJREMiX6 is it perhaps difference in passing empty string vs. null string? Your workaround suggests that.
If that is the case, the problem is that your serialization is lossy and needs to keep null vs. "" information somehow.

**Comment by DJREMiX6** [comment] 2023-08-07 09:27
> @DJREMiX6 is it perhaps difference in passing empty string vs. null string? Your workaround suggests that. If that is the case, the problem is that your serialization is lossy and needs to keep null vs. "" information somehow.

It does not work if I assign to it a null or empty string value.

**Comment by DJREMiX6** [comment] 2023-08-07 10:14
> Member

I tried running the project in windows machine but it throws an error at startup that says that i have an attached debugger to it that can't handle the exception.

**Comment by MihaZupan** [comment] 2023-08-07 11:44
@DJREMiX6 are you able to reproduce this issue with a recent preview of .NET 8.0?
You might be running into #70227, which was fixed early in 8.0.

**Comment by DJREMiX6** [comment] 2023-08-07 12:07
> Hi @DJREMiX6. We have added the "s/needs-repro" label to this issue, which indicates that we require steps and sample code to reproduce the issue before we can take further action. Please try to create a minimal sample project/solution or code samples which reproduce the issue, ideally as a GitHub repo that we can clone. See more details about creating repros here: https://github.com/dotnet/maui/blob/main/.github/repro.md
> 
> This issue will be closed automatically in 7 days if we do not hear back from you by then - please feel free to re-open it if you come back to this issue after that time.



> @DJREMiX6 are you able to reproduce this issue with a recent preview of .NET 8.0? You might be running into #70227, which was fixed early in 8.0.

I've edited the issue adding a new link of a github repo with a sample code that is working with the same bug if you want to look up for it, i've described the steps to operate on it in the README.md file

**Comment by MihaZupan** [comment] 2023-08-07 12:23
Since you already have the repro setup, can you try running it on a preview of 8.0? :)
https://dotnet.microsoft.com/en-us/download/dotnet/8.0

**Comment by MihaZupan** [comment] 2023-08-07 13:20
You can edit the `<TargetFramework>` in your `csproj` file from `net7.0` to `net8.0`

**Comment by DJREMiX6** [comment] 2023-08-07 13:43
`
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net7.0-android33.0</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net8.0-windows10.0.22621.0</TargetFrameworks>
		
		
		<OutputType>Exe</OutputType>
		<RootNamespace>MAUICookiesNotSentBug</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>

		
		<ApplicationTitle>MAUICookiesNotSentBug</ApplicationTitle>

		
		<ApplicationId>com.companyname.mauicookiesnotsentbug</ApplicationId>
		<ApplicationIdGuid>69a90d0f-4890-4e74-84fc-9c2213b0b686</ApplicationIdGuid>

		
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">30.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net7.0-android33.0|AnyCPU'">
	  <AndroidPackageFormat>apk</AndroidPackageFormat>
	  <Debugger>Xamarin</Debugger>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net7.0-android33.0|AnyCPU'">
	  <Debugger>Xamarin</Debugger>
	</PropertyGroup>

	<ItemGroup>
		
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

		
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

		
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.svg" BaseSize="168,208" />

		
		<MauiFont Include="Resources\Fonts\*" />

		
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="7.0.0" />
	</ItemGroup>

</Project>
`

This is the csproj file content but it gives me this error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1045	The current .NET SDK does not support targeting .NET 8.0.  Either target .NET 7.0 or lower, or use a version of the .NET SDK that supports .NET 8.0.	MAUICookiesNotSentBug.UI	C:\Program Files\dotnet\sdk\7.0.306\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	151

**Comment by DJREMiX6** [comment] 2023-08-07 13:44
I installed the SDK, ASP.NET Core runtime, .NET Desktop Runtime and the .NET Runtime

**Comment by DJREMiX6** [comment] 2023-08-07 13:52
> Is same code working for you on other platforms @DJREMiX6 ?

I tested it right now on windows 11 with .net 7 and it has the same behaviour.

**Comment by MihaZupan** [comment] 2023-08-07 23:25
Confirmed in a local repro that this is the same issue as #70227 -- it is fixed in .NET 8.0.

**Closed by MihaZupan** 2023-08-07 23:25 UTC
Labels: area-System.Net, untriaged

**Comment by DJREMiX6** [comment] 2023-08-08 10:56
Thank you for your time, have a great day.
