### ISSUE TITLE
[wasm] Perf pipeline (`dotnet-runtime-perf`) completely broken for `main`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#78575] opened 2022-11-18 21:24 UTC
[Failing build - 20221118.2](https://dev.azure.com/dnceng/internal/_build/results?buildId=2048387&view=logs&j=10348dd7-5cd6-5c42-fc55-e890e0795f10&t=3fe50c48-466c-5f5d-0411-aa33700b2a9d):

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.PlatformNotSupportedException: System.Diagnostics.FileVersionInfo is not supported on this platform.
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String )
   at BenchmarkDotNet.Portability.RuntimeInformation.GetNetCoreVersion()
   at BenchmarkDotNet.Portability.RuntimeInformation.GetRuntimeVersion()
   at BenchmarkDotNet.Environments.BenchmarkEnvironmentInfo..ctor()
   at BenchmarkDotNet.Environments.BenchmarkEnvironmentInfo.GetCurrent()
   at BenchmarkDotNet.Autogenerated.Runnable_0.Run(IHost host, String benchmarkName)
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object , IntPtr* )
   at System.Reflection.MethodInvoker.Invoke(Object , IntPtr* , BindingFlags )
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object , IntPtr* , BindingFlags )
   at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args)
```

- The previous working build was [20221118.1](https://dev.azure.com/dnceng/internal/_build/results?buildId=2048237&view=logs&j=10348dd7-5cd6-5c42-fc55-e890e0795f10).
- The only new commit in `20221118.2` was 82054d0a71622a22fdfd278d957019a3d69c4040 from https://github.com/dotnet/runtime/pull/78534 .
- both used dotnet installer `8.0.100-alpha.1.22567.28`

cc @am11 @akoeplinger @jkotas 

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by am11** [comment] 2022-11-18 21:35
toolchain.cmake is not used in wasm, so i'm not sure how it can break main.

**Comment by radical** [comment] 2022-11-18 21:38
I'll try to reproduce this locally.

**Comment by am11** [comment] 2022-11-18 21:39
I cannot access the internal CI link, so I'll wait for more info.

**Comment by radical** [comment] 2022-11-18 21:41
There are multiple parts that can be different between two runs.
- The first suspect is the `runtime` commit changes. (not applicable, like you said)
- dotnet sdk version difference - they ran with the same one
- Different performance repo branch HEADs - I'm checking this now
- v8 version - shouldn't be relevant here

**Comment by jkotas** [comment] 2022-11-18 21:42
> Different performance repo branch HEADs - I'm checking this now

Yes, that would be my guess. Likely caused by https://github.com/dotnet/performance/pull/2741

**Comment by radical** [comment] 2022-11-18 22:01
> Yes, that would be my guess. Likely caused by [dotnet/performance#2741](https://github.com/dotnet/performance/pull/2741)

Indeed it is. That bumped BDN from `0.13.2.1950` to `0.13.2.2007`, and reverting that changes fixes the issue.
These were the BDN changes in that bump - https://github.com/dotnet/BenchmarkDotNet/compare/eda1a412...9c32a878 .

**Comment by radical** [comment] 2022-11-18 22:02
cc @LoopedBard3 @adamsitnik

**Comment by adamsitnik** [comment] 2022-11-18 22:18
I won't be able to test it today, but I've merged a change that should solve the problem: https://github.com/dotnet/BenchmarkDotNet/pull/2201

@radical [this](https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/builds/45428788) build should get green within an hour and publish `0.13.2.2009` version

Explanation: https://github.com/dotnet/BenchmarkDotNet/pull/2142 has changed the way we detect Mono runtime to also support MonoVM on .NET 6+:

```diff
- public static bool IsMono { get; } = Type.GetType("Mono.Runtime") != null;
+ public static bool IsMono { get; } = Type.GetType("Mono.RuntimeStructs") != null
```

This affects the code flow in https://github.com/dotnet/BenchmarkDotNet/blob/ad8e9b26ef22aa77abff2469f7668986e1449127/src/BenchmarkDotNet/Portability/RuntimeInformation.cs#L166-L196 (IsMono was before IsWasm) and caused the call to not supported API.

**Comment by radical** [comment] 2022-11-18 22:20
Thank you for the super quick fix! I can test this out later today.

**Comment by radical** [comment] 2022-11-19 00:19
@LoopedBard3 could you publish the new package to the internal feeds? https://ci.appveyor.com/project/dotnetfoundation/benchmarkdotnet/builds/45428788

**Comment by LoopedBard3** [comment] 2022-11-19 00:34
Pushed! @radical

**Closed** 2022-11-19 02:12 UTC
Labels: arch-wasm, blocking-clean-ci, perf-pipeline

**Comment by adamsitnik** [comment] 2022-11-21 13:27
We need to avoid introducing similar breaking changes in the future. 

@radical I've created https://github.com/dotnet/BenchmarkDotNet/issues/2203 PTAL and add your thoughts.
