### ISSUE TITLE
ConfigurationManager is not trim compatible

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#49062] opened 2021-03-03 16:29 UTC
Using the latest 6.0 SDK

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="6.0.0-preview.3.21153.4" />
  </ItemGroup>

</Project>
```

```C#
using System;
using System.Configuration;

namespace ConsoleApp7
{
    class Program
    {
        static void Main(string[] args)
        {
            string sAttr = ConfigurationManager.AppSettings.Get("Key0");
            Console.WriteLine("hello" + sAttr);
        }
    }
}
```

```
❯ dotnet publish -c Release -r win-x64 -p:PublishTrimmed=true -p:TrimMode=link
❯ C:\Users\eerhardt\source\repos\ConsoleApp7\ConsoleApp7\bin\Release\net6.0\win-x64\publish\ConsoleApp7.exe
Unhandled exception. System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize
 ---> System.MissingMethodException: Cannot dynamically create an instance of type 'System.Configuration.ClientConfigurationHost'. Reason: No parameterless constructor defined.
   at System.RuntimeType.ActivatorCache..ctor(RuntimeType rt)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Configuration.TypeUtil.CreateInstance(Type type)
   at System.Configuration.Internal.ConfigSystem.System.Configuration.Internal.IConfigSystem.Init(Type typeConfigHost, Object[] hostInitParams)
   at System.Configuration.ClientConfigurationSystem..ctor()
   at System.Configuration.ConfigurationManager.EnsureConfigurationSystem()
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationManager.EnsureConfigurationSystem()
   at System.Configuration.ConfigurationManager.PrepareConfigSystem()
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.get_AppSettings()
   at ConsoleApp7.Program.Main(String[] args) in C:\Users\eerhardt\source\repos\ConsoleApp7\ConsoleApp7\Program.cs:line 12
```

______

Because https://github.com/dotnet/runtime/pull/48428 marked all assemblies building from `dotnet/runtime` as `IsTrimmable=true`, System.Configuration.ConfigurationManager is now getting aggressively trimmed. However, since we haven't addressed the ILLink warnings in the assembly, it is not trim compatible.

We should probably remove `IsTrimmable` from this assembly until we have addressed its warnings.

cc @marek-safar @sbomer

**Comment by marek-safar** [comment] 2021-03-03 16:40
@eerhardt I don't see any linker suppressions in System.Configuration.ConfigurationManager, is that because it's OOB package?

**Comment by eerhardt** [comment] 2021-03-03 17:00
> is that because it's OOB package?

Yes. We only run the linker analysis on the shared framework / runtimepack assemblies currently. https://github.com/dotnet/runtime/issues/48488 tracks adding analysis for OOB libraries.

**Comment by HermanSchoenfeld** [comment] 2022-12-01 05:26
This issue is still occurring in .NET 7:

# Exception
```
Unhandled exception. System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize
 ---> System.MissingMethodException: Cannot dynamically create an instance of type 'System.Configuration.ClientConfigurationHost'. Reason: No parameterless constructor defined.
   at System.RuntimeType.ActivatorCache..ctor(RuntimeType)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean, Boolean)
   at System.Configuration.Internal.ConfigSystem.System.Configuration.Internal.IConfigSystem.Init(Type, Object[] )
   at System.Configuration.ClientConfigurationSystem..ctor()
   at System.Configuration.ConfigurationManager.EnsureConfigurationSystem()
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationManager.EnsureConfigurationSystem()
   at System.Configuration.ConfigurationManager.PrepareConfigSystem()
   at System.Configuration.ConfigurationManager.GetSection(String)
   at Program.<Main>$(String[]) in D:\Development\Sphere10\LocalNotion\ConsoleApp1\Program.cs:line 1
   ```

# Steps to reproduce
1. Create a Console App targeting .NET 7
2. Add package  `System.Configuration.ConfigurationManager`  (version 7.0.0)
3. Create a publishing profile 
![image](https://user-images.githubusercontent.com/2360504/204972437-838c7964-519b-4225-be23-e25e2715a837.png)
4. Publish & Run

# Environment Details

## Visual Studio 
```
Microsoft Visual Studio Community 2022
Version 17.5.0 Preview 1.0
VisualStudio.17.Preview/17.5.0-pre.1.0+33103.201
Microsoft .NET Framework
Version 4.8.04084
```

**Comment by ericstj** [comment] 2023-08-10 19:44
This assembly isn't close to working with the linker given all it's use of runtime described types from user config files.  

The latest version doesn't have the `IsTrimmable` attribute and works with `net6.0`.  It is, however, broken on `net6.0` and `net7.0` - because the default changed to trim everything.

I chatted with @eerhardt and he let me know there is not a great way (other than an rd.xml) for the assembly itself to tell the linker to root the entire assembly.

For now you can workaround this with the following in the application:
```xml
  <ItemGroup>
    <TrimmerRootAssembly Include="System.Configuration.ConfigurationManager" />
  </ItemGroup>
```

That works on `net6.0` - `net8.0`.  If we ever wanted to do better we'd need to give this assembly linker annotations, but I'm not seeing a need to do that right now.  This assembly and its type closure is _very_ large (5.3 MB in my test) and unlikely to be something that folks want to use in a linked application.  Moving this to future.

**Comment by jkotas** [comment] 2023-08-10 19:53
> For now you can workaround this with the following in the application:

This is not a reliable workaround. There are still going to be situations when the trimmed app is going to be broken, even with this workaround.

**Comment by jkotas** [comment] 2023-08-10 19:57
I think it should be fine to close this issue. This assembly is not compatible with trimming by design, due to heavy dependency on `Type.GetType(string)`. There is no good way to fix that, without changing the programming model significantly.

**Comment by HermanSchoenfeld** [comment] 2023-08-15 04:15
The notion that this assembly is unlikely to be used in a linked application is basically saying that linked applications are unlikely to use configuration. In my 20 years of .NET development, I don't think I've ever encountered a single production application, desktop, web, mobile that didn't rely on or use configuration of some sort. The idea that a non-trivial app would not use this assembly I think is the correct assessment. If you can't like this assembly then it's going to fail for almost all real-world use-cases.

**Comment by jkotas** [comment] 2023-08-15 04:29
There are several different configuration systems available in .NET. Some are compatible with trimming and AOT and others are not.

ASP.NET Core uses `Microsoft.Extensions.Configuration` system that is trim and AOT compatible starting with .NET 8 (https://github.com/dotnet/runtime/issues/44493). If you need compatibility with trimming and AOT, `Microsoft.Extensions.Configuration` would be the configuration system to use.

**Comment by steveharter** [comment] 2023-08-15 16:12
Closing as by design; not investing in ConfigurationManager.

**Closed by steveharter** 2023-08-15 16:12 UTC
Labels: bug, area-System.Configuration, linkable-framework

**Comment by HermanSchoenfeld** [comment] 2023-08-17 10:52
> 



> There are several different configuration systems available in .NET. Some are compatible with trimming and AOT and others are not.
> 
> ASP.NET Core uses `Microsoft.Extensions.Configuration` system that is trim and AOT compatible starting with .NET 8 (#44493). If you need compatibility with trimming and AOT, `Microsoft.Extensions.Configuration` would be the configuration system to use.

Thanks for the info, that seems like a reasonable alternative approach and something I'll invest in. For those looking at native apps, it would be helpful to have a compiled list of "never going to support" assemblies so that we don't waste endless hours trying to get something that supposedly should work to work when it's not going to work "by design".


1. System.Configuration.ConfigurationManager
2. ??

**Comment by steveharter** [comment] 2023-08-18 19:23
> so that we don't waste endless hours trying to get something that supposedly should work to work when it's not going to work "by design".

Note most of the libraries provide an indication of the investment level through a `README.md` file located in their `src` folder. 

System.Configuration.ConfigurationManager has a [`We only consider fixes to maintain or improve quality` bar]( https://github.com/dotnet/runtime/tree/main/src/libraries/System.Configuration.ConfigurationManager/README.md).

Microsoft.Extensions.Configuration has a [`We consider new features, new APIs, bug fixes, and performance changes` bar](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Configuration/README.md)

**Comment by jkotas** [comment] 2023-08-20 04:55
> For those looking at native apps, it would be helpful to have a compiled list of "never going to support" assemblies so that we don't waste endless hours trying to get something that supposedly should work to work when it's not going to work "by design".

Thank you for the feedback. I like this idea. Submitted doc updates in https://github.com/dotnet/docs/pull/36769 . Please take a look.
