### ISSUE TITLE
UseStartup with IHostBuilder rather than IWebHostBuilder

### ISSUE THREAD

**Issue by MoienTajik** [dotnet/runtime#36000] opened 2020-01-30 07:47 UTC
### Is your feature request related to a problem? Please describe.
At this time, there's no possibility to use the `UseStartup` method in applications other than `Microsoft.NET.Sdk.Web` because `ConfigureWebHostDefaults` doesn't exist in them.

This means that we cannot have a separate **Startup** class to use in projects like [Worker SDK ](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.1)because `UseStartup` is now written as an extension on top of `IWebHostBuilder` in **[WebHostExtensions.cs](https://github.com/dotnet/aspnetcore/blob/master/src/Hosting/Hosting/src/WebHostBuilderExtensions.cs)** rather than `IHostBuilder`, thus we cannot have a separate Startup class in other types of applications.

So, we have to write all the stuff related to configuring services directly in `Program.cs` and accordingly, we'll don't have features like _IConfiguration_ automatic injection and so on.

### Describe the solution you'd like
Being able to use **UseStartup** in all different project types by writing `UseStartup` on top of `IHostBuilder` rather than `IWebHostBuilder`.

**Comment by maryamariyan** [comment] 2020-10-01 15:49
Closing as dupe of https://github.com/dotnet/runtime/issues/42364

**Closed by maryamariyan** 2020-10-01 15:49 UTC
Labels: area-Extensions-Hosting
