### ISSUE TITLE
Added HttpMessageHandler but ports are still in TIME_WAIT

### ISSUE THREAD

**Issue by datacruze** [dotnet/runtime#70855] opened 2022-06-05 21:39 UTC
Following this https://github.com/dotnet/wcf/issues/3230 I've managed to inject my own HttpMessageHandler from IHttpMessageHandlerFactory into the WCF client.

My EndpointBehavior looks like this:
```cs
        public class CustomEndpointBehavior : IEndpointBehavior
        {
            private readonly Func<HttpMessageHandler> _httpHandler;

            public CustomEndpointBehavior(IHttpMessageHandlerFactory factory) => _httpHandler = () => factory.CreateHandler("ClientName");

            public void AddBindingParameters(ServiceEndpoint endpoint, BindingParameterCollection bindingParameters) => bindingParameters.Add(new Func<HttpClientHandler, HttpMessageHandler>(handler => _httpHandler()));

            public void ApplyClientBehavior(ServiceEndpoint endpoint, ClientRuntime clientRuntime) { }

            public void ApplyDispatchBehavior(ServiceEndpoint endpoint, EndpointDispatcher endpointDispatcher) { }

            public void Validate(ServiceEndpoint endpoint) { }
        }
```

In Startup.cs
`services.AddHttpClient("ClientName");`

And this is how I use the httpHandler:
```cs
            WcfResponseDto response;
            var binding = CreateHttpBinding();  //Basic HTTP Binding
            binding.Security.Message.ClientCredentialType = BasicHttpMessageCredentialType.Certificate;

            var factory = new ChannelFactory<MyWcfChannel>(binding, new EndpointAddress(url));
            IHttpMessageHandlerFactory httpMessageHandler = _serviceProvider.GetService(typeof(IHttpMessageHandlerFactory)) as 
            IHttpMessageHandlerFactory;
              factory.Endpoint.EndpointBehaviors.Add(new CustomEndpointBehavior(httpMessageHandler));
            factory.Credentials.ClientCertificate.Certificate = GetCertificate();  //returns a x509 certificate
           var serviceProxy = factory.CreateChannel();

            try
            {

                ((ICommunicationObject)serviceProxy).Open();
                response = await
                    serviceProxy.EnterpriseGetCountyDetailsAsync(requestDto).ConfigureAwait(false);
            }
            catch (Exception ex)
            {
                ((ICommunicationObject)serviceProxy).Abort();
                factory.Abort();
                throw new FaultException(ex.Message);
            }
            finally
            {
                ((ICommunicationObject)serviceProxy).Close();
                factory.Close();
            }

            return response;
        }
```

When I use SOAP UI load test, I still see the ports open in TIME_WAIT after the application is done executing the load test. Is the HttpMessagehandler not working as it should or am I implementing it wrong? I am using the latest System.ServiceModel* dll (4.9.0)
![172071553](https://user-images.githubusercontent.com/6946608/172091715-94587350-9791-4a62-bcdb-cc84438d67d8.png)

**Comment by HongGit** [comment] 2022-06-16 20:55
Transfer to runtime, this is a question of behavior of IHttpMessageHandlerFactory.

**Comment by wfurt** [comment] 2022-06-16 21:03
That will go away: https://docs.microsoft.com/en-us/answers/questions/230227/time-wait-from-netstat.html

**Comment by karelz** [comment] 2022-06-21 16:57
Triage: This is by design behavior of the OS when we close Socket. As @wfurt mentions above, it will disappear.
If you are trying to limit the max number of connections, you can use `MaxConnectionsPerServer` to limit that.
Closing as resolved. Let us know if we misunderstood what you need.

**Closed by karelz** 2022-06-21 16:57 UTC
Labels: untriaged, area-Extensions-HttpClientFactory
