### ISSUE TITLE
Assert failure: arrayBaseRef->GetArrayElementType() == ELEMENT_TYPE_OBJECT

### ISSUE THREAD

**Issue by JulieLeeMSFT** [dotnet/runtime#105279] opened 2024-07-22 20:44 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=749673&view=ms.vss-test-web.build-test-results-tab&runId=18975226&resultId=122356&paneView=debug
Build error leg or test failing: JIT/IL_Conformance/Convert/TestConvertFromIntegral/TestConvertFromIntegral.dll
[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-8affbd33027949bfbb/IL_Conformance/1/console.e6063c77.log?helixlogtype=result)

**IL_Conformance work Item failed in below configs:**
![image](https://github.com/user-attachments/assets/c54ca2c9-6d2a-4c0c-9bf7-98c102a2df91)

![image](https://github.com/user-attachments/assets/5fadd600-2600-4b0e-9ce8-97d4742f04fd)

```
11:20:21.504 Running test: JIT/IL_Conformance/Convert/TestConvertFromIntegral/TestConvertFromIntegral.dll

Assert failure(PID 29317 [0x00007285], Thread: 29317 [0x7285]): arrayBaseRef->GetArrayElementType() == ELEMENT_TYPE_OBJECT
    File: /__w/1/s/src/coreclr/vm/comutilnative.cpp:438
    Image: /datadisks/disk1/work/BE910A65/p/corerun

[createdump] Gathering state for process 29317 corerun
[createdump] Crashing thread 7285 signal 6 (0006)
[createdump] Writing crash report to file /home/helixbot/dotnetbuild/dumps/coredump.29317.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.29317.dmp
[createdump] Written 99807232 bytes (24367 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 540ms
waitpid() returned successfully (wstatus 00000000) WEXITSTATUS 0 WTERMSIG 0
App Exit Code: 22
Expected: 100
Actual: 22
END EXECUTION - FAILED
+ test_exit_code=1
+ dotnet /datadisks/disk1/work/BE910A65/p/XUnitLogChecker/XUnitLogChecker.dll --results-path JIT/IL_Conformance/IL_Conformance --test-wrapper IL_Conformance --dumps-path /home/helixbot/dotnetbuild/dumps
[XUnitLogChecker]: 11:20:25.54: The full run will be done.
[XUnitLogChecker]: 11:20:25.57: Item 'IL_Conformance' did not finish running. Checking and fixing the log...
[XUnitLogChecker]: 11:20:25.58: XUnit log file has been fixed!

398/406 tests run.
* 398 tests passed.
* 0 tests failed.
* 0 tests skipped.

[XUnitLogChecker]: 11:20:25.59: Checking for dumps...
[XUnitLogChecker]: 11:20:25.61: Reading crash report '/home/helixbot/dotnetbuild/dumps/coredump.29317.dmp.crashreport.json'...
[XUnitLogChecker]: 11:20:25.61: Stack Trace Found:

Invoking: sudo ls -l /home/helixbot/dotnetbuild/dumps/coredump.29317.dmp.crashreport.json
stdout: -rw------- 1 helixbot helixbot 26422 Jul 22 11:20 /home/helixbot/dotnetbuild/dumps/coredump.29317.dmp.crashreport.json

=========================================
Invoking: sudo chown helixbot /home/helixbot/dotnetbuild/dumps/coredump.29317.dmp.crashreport.json
=========================================
Invoking: sudo ls -l /home/helixbot/dotnetbuild/dumps/coredump.29317.dmp.crashreport.json
stdout: -rw------- 1 helixbot helixbot 26422 Jul 22 11:20 /home/helixbot/dotnetbuild/dumps/coredump.29317.dmp.crashreport.json

=========================================
Invoking: ls -l /home/helixbot/dotnetbuild/dumps/coredump.29317.dmp.crashreport.json
stdout: -rw------- 1 helixbot helixbot 26422 Jul 22 11:20 /home/helixbot/dotnetbuild/dumps/coredump.29317.dmp.crashreport.json

Printing stacktrace from '/home/helixbot/dotnetbuild/dumps/coredump.29317.dmp.crashreport.json'
Invoking llvm-symbolizer --pretty-print
Stack trace:
----------------------------------
Thread Id: 0x7285
      Child SP               IP Call Site
 0x7ffc634584f0 0x7e33ec2ea42f libc.so.6!wait4
 0x7ffc63458520 0x7e33ebf0d9c1 libcoreclr.so!PROCCreateCrashDump(std::vector<char const*, std::allocator<char const*> >&, char*, int, bool) at /__w/1/s/src/coreclr/pal/src/thread/process.cpp:2308:22
 0x7ffc63458590 0x7e33ebf0ecf1 libcoreclr.so!PROCCreateCrashDumpIfEnabled at /__w/1/s/src/coreclr/pal/src/thread/process.cpp:0:9
 0x7ffc63458610 0x7e33ebf0b92d libcoreclr.so!PROCAbort at /__w/1/s/src/coreclr/pal/src/thread/process.cpp:2559:5
 0x7ffc63458630 0x7e33ebf0b82b libcoreclr.so!?? at ??:0:0
 0x7ffc63458650 0x7e33ebd4edf0 libcoreclr.so!_DbgBreakCheckNoThrow(char const*, int, char const*, int) at /__w/1/s/src/coreclr/utilcode/debug.cpp:300:0
 0x7ffc634598a0 0x7e336c7c3838 0x7e336c7c3838
 0x7ffc63459950 0x7e336c7c38b9 System.Private.CoreLib.dll!System.Exception.get_TargetSite()
 0x7ffc63459970 0x7e336c7c3f65 System.Private.CoreLib.dll!System.Exception.get_Source()
 0x7ffc63459990 0x7e336c7c38fa System.Private.CoreLib.dll!System.Exception.InternalPreserveStackTrace()
 0x7ffc634599b0 0x7e33ebcb8870 0x7e33ebcb8870
 0x7ffc634599d0 0x7e33eba5328b libcoreclr.so!NativeExceptionHolderBase::~NativeExceptionHolderBase() at /__w/1/s/src/coreclr/pal/inc/pal.h:4237:13
 (inlined by) CallDescrWorkerWithHandler(CallDescrData*, int) at /__w/1/s/src/coreclr/vm/callhelpers.cpp:65:5
 0x7ffc63459a20 0x7e33eba53d42 libcoreclr.so!MethodDescCallSite::CallTargetWorker(unsigned long const*, unsigned long*, int) at /__w/1/s/src/coreclr/vm/callhelpers.cpp:557:22
 0x7ffc63459c10 0x7e33eb90c4e2 libcoreclr.so!ExceptionPreserveStackTrace(OBJECTREF) at /__w/1/s/src/coreclr/vm/callhelpers.h:0:9
 0x7ffc63459d60 0x7e33ebbd6d40 libcoreclr.so!DispatchManagedException(OBJECTREF, _CONTEXT*, bool) at /__w/1/s/src/coreclr/vm/exceptionhandling.cpp:5655:9
 0x7ffc6345ca30 0x7e33ebbd6a3b libcoreclr.so!DispatchManagedException(PAL_SEHException&, bool) at /__w/1/s/src/coreclr/vm/exceptionhandling.cpp:0:9
 0x7ffc6345d6b0 0x7e33ebb5dbc1 libcoreclr.so!RuntimeMethodHandle::InvokeMethod(Object*, void**, SignatureNative*, bool) at /__w/1/s/src/coreclr/vm/reflectioninvocation.cpp:0:5
 0x7ffc6345dab0 0x7e336c978eae System.Private.CoreLib.dll!System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(System.Object, System.Reflection.BindingFlags)
 0x7ffc6345daf0 0x7e336c9a86d6 System.Private.CoreLib.dll!System.Reflection.Emit.DynamicMethod.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
 0x7ffc6345db70 0x7e336eef9bbc TestConvertFromIntegral.dll!TestCasts.Program.GenerateTest[[System.Int32, System.Private.CoreLib],[System.SByte, System.Private.CoreLib]](Int32, System.Reflection.Emit.OpCode, System.Reflection.Emit.OpCode, Boolean, SByte, Boolean)
 0x7ffc6345dc00 0x7e336eef97e3 TestConvertFromIntegral.dll!TestCasts.Program.TestConvertFromInt4ToI1()
 0x7ffc6345dc20 0x7e336eef95ca TestConvertFromIntegral.dll!TestCasts.Program.TestConvertFromInt4()
 0x7ffc6345dc30 0x7e336eef954a TestConvertFromIntegral.dll!TestCasts.Program.TestEntryPoint()
 0x7ffc6345dc40 0x7e336eef92d7 IL_Conformance.dll!Program.<<Main>$>g__TestExecutor399|0_400(System.IO.StreamWriter, System.IO.StreamWriter, <>c__DisplayClass0_0 ByRef)
 0x7ffc6345dcd0 0x7e336de738ba IL_Conformance.dll!Program.<Main>$(System.String[])
----------------------------------
Thread Id: 0x7286
      Child SP               IP Call Site
 0x7e336c60ece0 0x7e33ec318bcf libc.so.6!__poll
 0x7e336c60ed10 0x7e33ebeff01e libcoreclr.so!CorUnix::CPalSynchronizationManager::ThreadPrepareForShutdown() at /__w/1/s/src/coreclr/pal/src/synchmgr/synchmanager.cpp:3251:13
 (inlined by) CorUnix::CPalSynchronizationManager::WorkerThread(void*) at /__w/1/s/src/coreclr/pal/src/synchmgr/synchmanager.cpp:1989:9
 0x7e336c60eda0 0x7e33ebf1191f libcoreclr.so!CorUnix::CPalThread::ThreadEntry(void*) at /__w/1/s/src/coreclr/pal/src/thread/thread.cpp:1746:5
 0x7e336c60ee60 0x7e33ec294ac3 libc.so.6!
 0x7e336c60ef00 0x7e33ec326850 libc.so.6!
----------------------------------
Thread Id: 0x7287
      Child SP               IP Call Site
 0x7e336be0db90 0x7e33ec318bcf libc.so.6!__poll
 0x7e336be0dbc0 0x7e33ebdaee3c libcoreclr.so!ipc_retry_syscall(int) at /__w/1/s/src/native/eventpipe/ds-ipc-pal-socket.c:283:16
 (inlined by) ipc_poll_fds(pollfd*, unsigned long, unsigned int) at /__w/1/s/src/native/eventpipe/ds-ipc-pal-socket.c:486:11
 (inlined by) ds_ipc_poll(_DiagnosticsIpcPollHandle*, unsigned long, unsigned int, void (*)(char const*, unsigned int)) at /__w/1/s/src/native/eventpipe/ds-ipc-pal-socket.c:1105:16
 0x7e336be0dc00 0x7e33ebcf3fb3 libcoreclr.so!ds_ipc_stream_factory_get_next_available_stream(void (*)(char const*, unsigned int)) at /__w/1/s/src/native/eventpipe/ds-ipc.c:404:15
 0x7e336be0dd30 0x7e33ebcf9cf6 libcoreclr.so!server_thread(void*) at /__w/1/s/src/native/eventpipe/ds-server.c:130:8
 0x7e336be0dda0 0x7e33ebf1191f libcoreclr.so!CorUnix::CPalThread::ThreadEntry(void*) at /__w/1/s/src/coreclr/pal/src/thread/thread.cpp:1746:5
 0x7e336be0de60 0x7e33ec294ac3 libc.so.6!
 0x7e336be0df00 0x7e33ec326850 libc.so.6!
----------------------------------
Thread Id: 0x7288
      Child SP               IP Call Site
 0x7e336b60be80 0x7e33ec3145b4 libc.so.6!__open64
 0x7e336b60bf00 0x7e33ebdae5d2 libcoreclr.so!TwoWayPipe::WaitForConnection() at /__w/1/s/src/coreclr/debug/debug-pal/unix/twowaypipe.cpp:87:19
 0x7e336b60bf30 0x7e33ebda73a7 libcoreclr.so!DbgTransportSession::TransportWorker() at /__w/1/s/src/coreclr/debug/ee/../shared/dbgtransportsession.cpp:1315:17
 0x7e336b60cd80 0x7e33ebda5f95 libcoreclr.so!DbgTransportSession::TransportWorkerStatic(void*) at /__w/1/s/src/coreclr/debug/ee/../shared/dbgtransportsession.cpp:1235:5
 0x7e336b60cda0 0x7e33ebf1191f libcoreclr.so!CorUnix::CPalThread::ThreadEntry(void*) at /__w/1/s/src/coreclr/pal/src/thread/thread.cpp:1746:5
 0x7e336b60ce60 0x7e33ec294ac3 libc.so.6!
 0x7e336b60cf00 0x7e33ec326850 libc.so.6!
----------------------------------
Thread Id: 0x7289
      Child SP               IP Call Site
 0x7e336ae0b8a0 0x7e33ec291117 libc.so.6!
 0x7e336ae0b8e0 0x7e33ec293a41 libc.so.6!pthread_cond_wait
 0x7e336ae0b9c0 0x7e33ebefb6eb libcoreclr.so!CorUnix::CPalSynchronizationManager::ThreadNativeWait(CorUnix::_ThreadNativeWaitData*, unsigned int, CorUnix::ThreadWakeupReason*, unsigned int*) at /__w/1/s/src/coreclr/pal/src/synchmgr/synchmanager.cpp:0:28
 0x7e336ae0ba20 0x7e33ebefac70 libcoreclr.so!CorUnix::CPalSynchronizationManager::BlockThread(CorUnix::CPalThread*, unsigned int, bool, bool, CorUnix::ThreadWakeupReason*, unsigned int*) at /__w/1/s/src/coreclr/pal/src/synchmgr/synchmanager.cpp:302:22
 0x7e336ae0ba80 0x7e33ebf04629 libcoreclr.so!CorUnix::InternalWaitForMultipleObjectsEx(CorUnix::CPalThread*, unsigned int, void* const*, int, unsigned int, int, int) at /__w/1/s/src/coreclr/pal/src/synchmgr/wait.cpp:637:45
 0x7e336ae0bc30 0x7e33ebf04ebb libcoreclr.so!WaitForMultipleObjectsEx at /__w/1/s/src/coreclr/pal/src/synchmgr/wait.cpp:201:13
 0x7e336ae0bc80 0x7e33ebda2f15 libcoreclr.so!DebuggerRCThread::MainLoop() at /__w/1/s/src/coreclr/debug/ee/rcthread.cpp:927:14
 0x7e336ae0bd30 0x7e33ebda2cfd libcoreclr.so!BaseHolder<Debugger*, FunctionBase<Debugger*, &(Debugger::AcquireDebuggerLock(Debugger*)), &(Debugger::ReleaseDebuggerLock(Debugger*))>, 0ul, &(int CompareDefault<Debugger*>(Debugger*, Debugger*))>::Release() at /__w/1/s/src/coreclr/inc/holder.h:285:13
 (inlined by) BaseHolder<Debugger*, FunctionBase<Debugger*, &(Debugger::AcquireDebuggerLock(Debugger*)), &(Debugger::ReleaseDebuggerLock(Debugger*))>, 0ul, &(int CompareDefault<Debugger*>(Debugger*, Debugger*))>::~BaseHolder() at /__w/1/s/src/coreclr/inc/holder.h:256:9
 (inlined by) DebuggerRCThread::ThreadProc() at /__w/1/s/src/coreclr/debug/ee/rcthread.cpp:731:1
 0x7e336ae0bd80 0x7e33ebda27a0 libcoreclr.so!DebuggerRCThread::ThreadProcStatic(void*) at /__w/1/s/src/coreclr/debug/ee/rcthread.cpp:1321:5
 0x7e336ae0bda0 0x7e33ebf1191f libcoreclr.so!CorUnix::CPalThread::ThreadEntry(void*) at /__w/1/s/src/coreclr/pal/src/thread/thread.cpp:1746:5
 0x7e336ae0be60 0x7e33ec294ac3 libc.so.6!
 0x7e336ae0bf00 0x7e33ec326850 libc.so.6!
----------------------------------
Thread Id: 0x728a
      Child SP               IP Call Site
 0x7e336a60a540 0x7e33ec291117 libc.so.6!
 0x7e336a60a580 0x7e33ec293e9b libc.so.6!pthread_cond_timedwait
 0x7e336a60a660 0x7e33ebefb6c8 libcoreclr.so!CorUnix::CPalSynchronizationManager::ThreadNativeWait(CorUnix::_ThreadNativeWaitData*, unsigned int, CorUnix::ThreadWakeupReason*, unsigned int*) at /__w/1/s/src/coreclr/pal/src/synchmgr/synchmanager.cpp:0:0
 0x7e336a60a6c0 0x7e33ebefac70 libcoreclr.so!CorUnix::CPalSynchronizationManager::BlockThread(CorUnix::CPalThread*, unsigned int, bool, bool, CorUnix::ThreadWakeupReason*, unsigned int*) at /__w/1/s/src/coreclr/pal/src/synchmgr/synchmanager.cpp:302:22
 0x7e336a60a720 0x7e33ebf04629 libcoreclr.so!CorUnix::InternalWaitForMultipleObjectsEx(CorUnix::CPalThread*, unsigned int, void* const*, int, unsigned int, int, int) at /__w/1/s/src/coreclr/pal/src/synchmgr/wait.cpp:637:45
 0x7e336a60a8d0 0x7e33ebf04ebb libcoreclr.so!WaitForMultipleObjectsEx at /__w/1/s/src/coreclr/pal/src/synchmgr/wait.cpp:201:13
 0x7e336a60a920 0x7e33ebab7071 libcoreclr.so!FinalizerThread::WaitForFinalizerEvent(CLREvent*) at /__w/1/s/src/coreclr/vm/finalizerthread.cpp:232:9
 0x7e336a60a960 0x7e33ebab74a9 libcoreclr.so!GCHeapUtilities::GetGCHeap() at /__w/1/s/src/coreclr/vm/gcheaputilities.h:74:9
 (inlined by) FinalizerThread::FinalizerThreadWorker(void*) at /__w/1/s/src/coreclr/vm/finalizerthread.cpp:321:36
 0x7e336a60abc0 0x7e33eba0993e libcoreclr.so!ManagedThreadBase_DispatchMiddle(ManagedThreadCallState*) at /__w/1/s/src/coreclr/vm/threads.cpp:0:5
 (inlined by) ManagedThreadBase_DispatchOuter(ManagedThreadCallState*)::$_0::operator()(ManagedThreadBase_DispatchOuter(ManagedThreadCallState*)::TryArgs*) const::'lambda'(Param*)::operator()(Param*) const at /__w/1/s/src/coreclr/vm/threads.cpp:7317:13
 (inlined by) ManagedThreadBase_DispatchOuter(ManagedThreadCallState*)::$_0::operator()(ManagedThreadBase_DispatchOuter(ManagedThreadCallState*)::TryArgs*) const at /__w/1/s/src/coreclr/vm/threads.cpp:7319:9
 (inlined by) ManagedThreadBase_DispatchOuter(ManagedThreadCallState*) at /__w/1/s/src/coreclr/vm/threads.cpp:7343:5
 0x7e336a60ad10 0x7e33eba09fad libcoreclr.so!ManagedThreadBase::FinalizerBase(void (*)(void*)) at /__w/1/s/src/coreclr/vm/threads.cpp:7407:1
 0x7e336a60ad40 0x7e33ebab7c38 libcoreclr.so!FinalizerThread::FinalizerThreadStart(void*) at /__w/1/s/src/coreclr/vm/finalizerthread.cpp:462:22
 0x7e336a60ada0 0x7e33ebf1191f libcoreclr.so!CorUnix::CPalThread::ThreadEntry(void*) at /__w/1/s/src/coreclr/pal/src/thread/thread.cpp:1746:5
 0x7e336a60ae60 0x7e33ec294ac3 libc.so.6!
 0x7e336a60af00 0x7e33ec326850 libc.so.6!
----------------------------------
Thread Id: 0x7292
      Child SP               IP Call Site
 0x7df2bcbfede0 0x7e33ec31481c libc.so.6!read
 0x7df2bcbfee10 0x7e33ec53178f libSystem.Native.so!
 0x7df2bcbfee60 0x7e33ec294ac3 libc.so.6!
 0x7df2bcbfef00 0x7e33ec326850 libc.so.6!

[XUnitLogChecker]: 11:20:35.94: Finished!
```

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorPattern": "Assert failure.*arrayBaseRef->GetArrayElementType\\(\\) == ELEMENT_TYPE_OBJECT",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=749673
**Error message validated:** `[Assert failure.*arrayBaseRef->GetArrayElementType\(\) == ELEMENT_TYPE_OBJECT`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/22/2024 8:44:59 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[749673](https://dev.azure.com/dnceng-public/public/_build/results?buildId=749673)|dotnet/runtime|[IL_Conformance.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=749673&view=ms.vss-test-web.build-test-results-tab&runId=18975406&resultId=123437)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|1|1|1|

**Comment by JulieLeeMSFT** [comment] 2024-07-22 20:45
@TIHan, PTAL this outerloop failure.

**Comment by jakobbotsch** [comment] 2024-07-22 22:13
Duplicate of #105186

**Closed by jakobbotsch** 2024-07-22 22:13 UTC
Labels: os-linux, os-mac-os-x, area-VM-coreclr, blocking-outerloop, Priority:1, Known Build Error
