### ISSUE TITLE
tracing/eventactivityidcontrol/eventactivityidcontrol  test always failing locally on Linux / macOS

### ISSUE THREAD

**Issue by janvorli** [dotnet/runtime#47634] opened 2021-01-29 15:41 UTC
This test always fails in my local coreclr test runs on Linux and macOS:
```
System.Exception: Values for 'activityId' are not equal! Left='00000015-0000-0000-0000-000041989d59' Right='00000000-0000-0000-0000-000000000000'
   at Tracing.Tests.Common.Assert.Equal[T](String name, T left, T right) in /home/janvorli/git/runtime2/src/tests/tracing/common/Assert.cs:line 33
   at Tracing.Tests.EventActivityIdControlTest.TestThreadProc() in /home/janvorli/git/runtime2/src/tests/tracing/eventactivityidcontrol/EventActivityIdControl.cs:line 76
System.Exception: Values for 'activityId' are not equal! Left='00000011-0000-0000-0000-00003d989d59' Right='00000000-0000-0000-0000-000000000000'
   at Tracing.Tests.Common.Assert.Equal[T](String name, T left, T right) in /home/janvorli/git/runtime2/src/tests/tracing/common/Assert.cs:line 33
   at Tracing.Tests.EventActivityIdControlTest.TestThreadProc() in /home/janvorli/git/runtime2/src/tests/tracing/eventactivityidcontrol/EventActivityIdControl.cs:line 76
System.Exception: Values for 'activityId' are not equal! Left='00000013-0000-0000-0000-000043989d59' Right='00000000-0000-0000-0000-000000000000'
   at Tracing.Tests.Common.Assert.Equal[T](String name, T left, T right) in /home/janvorli/git/runtime2/src/tests/tracing/common/Assert.cs:line 33
   at Tracing.Tests.EventActivityIdControlTest.TestThreadProc() in /home/janvorli/git/runtime2/src/tests/tracing/eventactivityidcontrol/EventActivityIdControl.cs:line 76
System.Exception: Values for 'activityId' are not equal! Left='00000018-0000-0000-0000-000046989d59' Right='00000000-0000-0000-0000-000000000000'
   at Tracing.Tests.Common.Assert.Equal[T](String name, T left, T right) in /home/janvorli/git/runtime2/src/tests/tracing/common/Assert.cs:line 33
   at Tracing.Tests.EventActivityIdControlTest.TestThreadProc() in /home/janvorli/git/runtime2/src/tests/tracing/eventactivityidcontrol/EventActivityIdControl.cs:line 76
System.Exception: Values for 'activityId' are not equal! Left='00000014-0000-0000-0000-000042989d59' Right='00000000-0000-0000-0000-000000000000'
   at Tracing.Tests.Common.Assert.Equal[T](String name, T left, T right) in /home/janvorli/git/runtime2/src/tests/tracing/common/Assert.cs:line 33
   at Tracing.Tests.EventActivityIdControlTest.TestThreadProc() in /home/janvorli/git/runtime2/src/tests/tracing/eventactivityidcontrol/EventActivityIdControl.cs:line 76
System.Exception: Values for 'activityId' are not equal! Left='00000017-0000-0000-0000-000047989d59' Right='00000000-0000-0000-0000-000000000000'
   at Tracing.Tests.Common.Assert.Equal[T](String name, T left, T right) in /home/janvorli/git/runtime2/src/tests/tracing/common/Assert.cs:line 33
   at Tracing.Tests.EventActivityIdControlTest.TestThreadProc() in /home/janvorli/git/runtime2/src/tests/tracing/eventactivityidcontrol/EventActivityIdControl.cs:line 76
System.Exception: Values for 'activityId' are not equal! Left='00000012-0000-0000-0000-00003c989d59' Right='00000000-0000-0000-0000-000000000000'
   at Tracing.Tests.Common.Assert.Equal[T](String name, T left, T right) in /home/janvorli/git/runtime2/src/tests/tracing/common/Assert.cs:line 33
   at Tracing.Tests.EventActivityIdControlTest.TestThreadProc() in /home/janvorli/git/runtime2/src/tests/tracing/eventactivityidcontrol/EventActivityIdControl.cs:line 76
System.Exception: Values for 'activityId' are not equal! Left='00000016-0000-0000-0000-000040989d59' Right='00000000-0000-0000-0000-000000000000'
   at Tracing.Tests.Common.Assert.Equal[T](String name, T left, T right) in /home/janvorli/git/runtime2/src/tests/tracing/common/Assert.cs:line 33
   at Tracing.Tests.EventActivityIdControlTest.TestThreadProc() in /home/janvorli/git/runtime2/src/tests/tracing/eventactivityidcontrol/EventActivityIdControl.cs:line 76
System.Exception: Values for 'activityId' are not equal! Left='00000015-0000-0000-0000-000041989d59' Right='00000000-0000-0000-0000-000000000000'
   at Tracing.Tests.Common.Assert.Equal[T](String name, T left, T right) in /home/janvorli/git/runtime2/src/tests/tracing/common/Assert.cs:line 33
   at Tracing.Tests.EventActivityIdControlTest.TestThreadProc() in /home/janvorli/git/runtime2/src/tests/tracing/eventactivityidcontrol/EventActivityIdControl.cs:line 76
System.Exception: Values for 'activityId' are not equal! Left='00000012-0000-0000-0000-00003c989d59' Right='00000000-0000-0000-0000-000000000000'
   at Tracing.Tests.Common.Assert.Equal[T](String name, T left, T right) in /home/janvorli/git/runtime2/src/tests/tracing/common/Assert.cs:line 33
   at Tracing.Tests.EventActivityIdControlTest.TestThreadProc() in /home/janvorli/git/runtime2/src/tests/tracing/eventactivityidcontrol/EventActivityIdControl.cs:line 76
System.Exception: Values for 'activityId' are not equal! Left='00000018-0000-0000-0000-000046989d59' Right='00000000-0000-0000-0000-000000000000'
   at Tracing.Tests.Common.Assert.Equal[T](String name, T left, T right) in /home/janvorli/git/runtime2/src/tests/tracing/common/Assert.cs:line 33
   at Tracing.Tests.EventActivityIdControlTest.TestThreadProc() in /home/janvorli/git/runtime2/src/tests/tracing/eventactivityidcontrol/EventActivityIdControl.cs:line 76
System.Exception: Values for 'activityId' are not equal! Left='00000013-0000-0000-0000-000043989d59' Right='00000000-0000-0000-0000-000000000000'
   at Tracing.Tests.Common.Assert.Equal[T](String name, T left, T right) in /home/janvorli/git/runtime2/src/tests/tracing/common/Assert.cs:line 33
   at Tracing.Tests.EventActivityIdControlTest.TestThreadProc() in /home/janvorli/git/runtime2/src/tests/tracing/eventactivityidcontrol/EventActivityIdControl.cs:line 76
System.Exception: Values for 'activityId' are not equal! Left='00000016-0000-0000-0000-000040989d59' Right='00000000-0000-0000-0000-000000000000'
   at Tracing.Tests.Common.Assert.Equal[T](String name, T left, T right) in /home/janvorli/git/runtime2/src/tests/tracing/common/Assert.cs:line 33
   at Tracing.Tests.EventActivityIdControlTest.TestThreadProc() in /home/janvorli/git/runtime2/src/tests/tracing/eventactivityidcontrol/EventActivityIdControl.cs:line 76
System.Exception: Values for 'activityId' are not equal! Left='00000012-0000-0000-0000-00003c989d59' Right='00000000-0000-0000-0000-000000000000'
   at Tracing.Tests.Common.Assert.Equal[T](String name, T left, T right) in /home/janvorli/git/runtime2/src/tests/tracing/common/Assert.cs:line 33
   at Tracing.Tests.EventActivityIdControlTest.TestThreadProc() in /home/janvorli/git/runtime2/src/tests/tracing/eventactivityidcontrol/EventActivityIdControl.cs:line 76
System.Exception: Values for 'activityId' are not equal! Left='00000015-0000-0000-0000-000041989d59' Right='00000000-0000-0000-0000-000000000000'
   at Tracing.Tests.Common.Assert.Equal[T](String name, T left, T right) in /home/janvorli/git/runtime2/src/tests/tracing/common/Assert.cs:line 33
   at Tracing.Tests.EventActivityIdControlTest.TestThreadProc() in /home/janvorli/git/runtime2/src/tests/tracing/eventactivityidcontrol/EventActivityIdControl.cs:line 76
System.Exception: Values for 'activityId' are not equal! Left='00000016-0000-0000-0000-000040989d59' Right='00000000-0000-0000-0000-000000000000'
   at Tracing.Tests.Common.Assert.Equal[T](String name, T left, T right) in /home/janvorli/git/runtime2/src/tests/tracing/common/Assert.cs:line 33
   at Tracing.Tests.EventActivityIdControlTest.TestThreadProc() in /home/janvorli/git/runtime2/src/tests/tracing/eventactivityidcontrol/EventActivityIdControl.cs:line 76
System.Exception: Values for 'activityId' are not equal! Left='00000014-0000-0000-0000-000042989d59' Right='00000000-0000-0000-0000-000000000000'
   at Tracing.Tests.Common.Assert.Equal[T](String name, T left, T right) in /home/janvorli/git/runtime2/src/tests/tracing/common/Assert.cs:line 33
   at Tracing.Tests.EventActivityIdControlTest.TestThreadProc() in /home/janvorli/git/runtime2/src/tests/tracing/eventactivityidcontrol/EventActivityIdControl.cs:line 76
System.Exception: Values for 'activityId' are not equal! Left='00000013-0000-0000-0000-000043989d59' Right='00000000-0000-0000-0000-000000000000'
   at Tracing.Tests.Common.Assert.Equal[T](String name, T left, T right) in /home/janvorli/git/runtime2/src/tests/tracing/common/Assert.cs:line 33
   at Tracing.Tests.EventActivityIdControlTest.TestThreadProc() in /home/janvorli/git/runtime2/src/tests/tracing/eventactivityidcontrol/EventActivityIdControl.cs:line 76
System.Exception: Values for 'activityId' are not equal! Left='00000011-0000-0000-0000-00003d989d59' Right='00000000-0000-0000-0000-000000000000'
   at Tracing.Tests.Common.Assert.Equal[T](String name, T left, T right) in /home/janvorli/git/runtime2/src/tests/tracing/common/Assert.cs:line 33
   at Tracing.Tests.EventActivityIdControlTest.TestThreadProc() in /home/janvorli/git/runtime2/src/tests/tracing/eventactivityidcontrol/EventActivityIdControl.cs:line 76
System.Exception: Values for 'activityId' are not equal! Left='00000018-0000-0000-0000-000046989d59' Right='00000000-0000-0000-0000-000000000000'
   at Tracing.Tests.Common.Assert.Equal[T](String name, T left, T right) in /home/janvorli/git/runtime2/src/tests/tracing/common/Assert.cs:line 33
   at Tracing.Tests.EventActivityIdControlTest.TestThreadProc() in /home/janvorli/git/runtime2/src/tests/tracing/eventactivityidcontrol/EventActivityIdControl.cs:line 76
Expected: 100
Actual: 0

```

**Comment by janvorli** [comment] 2021-01-29 15:42
cc: @dotnet/dotnet-diag

**Comment by hoyosjs** [comment] 2021-07-28 03:51
There's something odd here - this test isn't disabled but I can't find any runs of it on main in the last 30 days... I can see eventcounter and eventpipe getting run. I can't see any of: "eventlistener" "runtimeeventsource" or "eventactivityidcontrol". I can see some of them ran against 5.0.

**Comment by hoyosjs** [comment] 2021-07-28 09:21
Indeed. #56447 modified the test and no failures were seen, even though the test priority is 0 @josalem

**Comment by josalem** [comment] 2021-07-28 18:08
That's bizarre. Why would a test not be running? Looking in issues.targets I see it's disabled for Unix ARM and Windows ARM, but not other platforms. How far back can you see in the history? When was the last time this test was run on main? If you put a more obvious failure like an `Assert(false)` in #56447, so you see it fail?

**Comment by noahfalk** [comment] 2021-07-28 21:00
Fwiw I noticed [this test](https://github.com/dotnet/runtime/blob/9d9b465f0be92a0d7584c4b8ad6b873be7f0dbc9/src/libraries/System.Diagnostics.Tracing/tests/BasicEventSourceTest/TestsWriteEventToListener.cs#L455) appears like it would have caught the issue that @MihaZupan recently found and [fixed](https://github.com/dotnet/runtime/pull/56232). When I run it without Miha's changes I see it fail locally. I am quite suspicious it may be another example of a not running test that let us have an unintended regression in the product.

**Comment by josalem** [comment] 2021-07-28 23:51
I ran this locally and it is passing on my mac. Juan also assuaged my fears of the test not running. He created a test PR #56447 where he explicitly set this test to fail and it _does_ show up as a failure in CI.

I'm going to close this for now. @janvorli if this is still failing for you locally, please let me know and we can reopen this.

**Closed by josalem** 2021-07-28 23:51 UTC
Labels: area-Tracing-coreclr

**Comment by MihaZupan** [comment] 2021-07-30 11:42
@noahfalk I don't know about the other issues discussed here, but that specific test is new (I added it as part of the fix).

**Comment by janvorli** [comment] 2021-07-30 13:14
@josalem, @noahfalk This test now passes for me locally too. Now the tracing/eventpipe/eventsourceerror is failing instead - but only if I execute all the tests. Running that test alone works. But the error is different, I'll create a separate issue for it.

**Comment by josalem** [comment] 2021-07-30 16:20
Thanks @janvorli! Please CC me on the new issue.

**Comment by noahfalk** [comment] 2021-07-30 22:16
Ah thanks @MihaZupan, I didn't remember it from the PR but clearly I shouldn't trust my memory : )
