### ISSUE TITLE
System.Text.Json serializes both parent and child properties when using inheritance, even when new or override is used in the child class.

### ISSUE THREAD

**Issue by sakitA** [dotnet/runtime#108890] opened 2024-10-15 15:34 UTC
### Description

When serializing a class that inherits from an abstract or virtual base class using System.Text.Json, both the properties from the parent class and the child class are serialized, even when the child class overrides or hides the parent properties using the new or override keywords. This behavior leads to duplicate entries for the same property in the serialized JSON output, which is undesirable and unexpected.

#### **Example Code**:

```csharp
using System;
using System.Text.Json;
using System.Text.Json.Serialization;

public abstract class Parent
{
    public string Name { get; set; }

    public int Age { get; set; }
}

public class Child : Parent
{
    [JsonPropertyName("full_name")]
    public new string Name { get; set; } // Hides the parent property

    [JsonPropertyName("child_age")]
    public override int Age { get; set; } // Overrides the parent property
}

class Program
{
    static void Main(string[] args)
    {
        Child child = new Child
        {
            Name = "John Doe",
            Age = 10
        };

        var options = new JsonSerializerOptions
        {
            WriteIndented = true
        };

        string json = JsonSerializer.Serialize(child, options);
        Console.WriteLine(json);
    }
}
```

### Reproduction Steps

**Steps to Reproduce:**

1. Create an abstract base class (Parent) with properties.
2. Create a child class (Child) that inherits from the base class and either:
     - Uses the new keyword to hide the base class properties.
     - Uses the override keyword to override base class properties.
3. Apply the [JsonPropertyName] attribute to the properties in the child class to customize their names in the JSON output.
4. Serialize an instance of the Child class using System.Text.Json.

### Expected behavior

Only the properties from the **child class** should be serialized, with the custom names provided by the `[JsonPropertyName]` attribute. The parent properties should not be serialized if they are hidden or overridden by the child class.

Expected JSON output:

```json
{
  "full_name": "John Doe",  // Only the child property should be serialized
  "child_age": 10           // Only the child property should be serialized
}
```

### Actual behavior

The JSON output contains **both** the parent and child properties, leading to duplication:

```json
{
  "full_name": "John Doe",  // From child class (expected)
  "Name": "John Doe",       // From parent class (unexpected)
  "child_age": 10,          // From child class (expected)
  "Age": 10                 // From parent class (unexpected)
}
```

### Configuration

Using .NET8 on Windows 11

### Other information

It is simple app, but in our case we want to use JsonPropertyName to rename our properties during the serialization. But because of back compatibility we can't touch or ignore parent properties, that is why we trying to override the properties in new version child class so both can work at the same time.

**Comment by gregsdennis** [comment] 2024-10-16 05:29
I think the current behavior of serializing all properties is generally expected.  This is the purpose of using inheritance on models.

**Comment by sakitA** [comment] 2024-10-16 06:35
Having difference property understandable, but why override properties duplicate? Without using jsonpropertyname there is no duplicate because both has the same key name. Json property name cause having different name and serialization use both name and duplicate the property with different name. And I don't think this expected behavior.

**Comment by eiriktsarpalis** [comment] 2024-10-16 09:35
Duplicate of https://github.com/dotnet/runtime/issues/51165.

**Closed by eiriktsarpalis** 2024-10-16 09:35 UTC
Labels: area-System.Text.Json, untriaged
