### ISSUE TITLE
Mono builds failing with file not found error

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#103677] opened 2024-06-18 23:57 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=710920
Build error leg or test failing: Build / windows-x64 Release AllSubsets_Mono_Minijit_RuntimeTests minijit / Build product
Pull request: https://github.com/dotnet/runtime/pull/103604

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "Could not copy the file "D:\a\_work\1\s\artifacts\bin\win-x64.Release\corehost\hostfxr.dll.pdb" because it was not found",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by jkotas** [comment] 2024-06-19 00:05
Duplicate of https://github.com/dotnet/runtime/issues/103642.

**Closed by jkotas** 2024-06-19 00:05 UTC
Labels: blocking-clean-ci, area-Infrastructure-mono, Known Build Error
