### ISSUE TITLE
Behaviour of exceptions in `List<T>.LastIndexOf` doesn't match with documentation

### ISSUE THREAD

**Issue by Enderlook** [dotnet/runtime#109054] opened 2024-10-20 15:14 UTC
### Description

`index` and `count` parameters in `List<T>.LastIndexOf(T, int, int)` and `List<T>.LastIndexOf(T, int)` are not correctly validated (according to documentation) when the collection is empty.

According to  [documentation](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.lastindexof?view=net-8.0#system-collections-generic-list-1-lastindexof(-0-system-int32)):

>Exceptions
>[ArgumentOutOfRangeException](https://learn.microsoft.com/en-us/dotnet/api/system.argumentoutofrangeexception?view=net-8.0)
index is outside the range of valid indexes for the [List<T>](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1?view=net-8.0).
>
>-or-
>
>count is less than 0.
>
>-or-
>
>index and count do not specify a valid section in the [List<T>](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1?view=net-8.0).

### Reproduction Steps

```cs
List<int> list = new();
Console.WriteLine(list.LastIndexOf(9, -3));
Console.WriteLine(list.LastIndexOf(9, 3));
Console.WriteLine(list.LastIndexOf(9, -3, -3));
Console.WriteLine(list.LastIndexOf(9, 0, -3));
Console.WriteLine(list.LastIndexOf(9, -3, 0));
Console.WriteLine(list.LastIndexOf(9, 3, 3));
Console.WriteLine(list.LastIndexOf(9, -3, 3));
Console.WriteLine(list.LastIndexOf(9, 3, -3));

list = new() { 1 };
Console.WriteLine(list.LastIndexOf(9, -3));
Console.WriteLine(list.LastIndexOf(9, 3));
Console.WriteLine(list.LastIndexOf(9, -3, -3));
Console.WriteLine(list.LastIndexOf(9, 0, -3));
Console.WriteLine(list.LastIndexOf(9, -3, 0));
Console.WriteLine(list.LastIndexOf(9, 3, 3));
Console.WriteLine(list.LastIndexOf(9, -3, 3));
Console.WriteLine(list.LastIndexOf(9, 3, -3));
```

### Expected behavior

```cs
List<int> list = new();
Console.WriteLine(list.LastIndexOf(9, -3));  // Throws ArgumentOutOfRangeException.
Console.WriteLine(list.LastIndexOf(9, 3)); // Throws ArgumentOutOfRangeException.
Console.WriteLine(list.LastIndexOf(9, -3, -3)); // Throws ArgumentOutOfRangeException.
Console.WriteLine(list.LastIndexOf(9, 0, -3)); // Throws ArgumentOutOfRangeException.
Console.WriteLine(list.LastIndexOf(9, -3, 0)); // Throws ArgumentOutOfRangeException.
Console.WriteLine(list.LastIndexOf(9, 3, 3)); // Throws ArgumentOutOfRangeException.
Console.WriteLine(list.LastIndexOf(9, -3, 3)); // Throws ArgumentOutOfRangeException.
Console.WriteLine(list.LastIndexOf(9, 3, -3)); // Throws ArgumentOutOfRangeException.

list = new() { 1 };
Console.WriteLine(list.LastIndexOf(9, -3)); // Throws ArgumentOutOfRangeException.
Console.WriteLine(list.LastIndexOf(9, 3)); // Throws ArgumentOutOfRangeException.
Console.WriteLine(list.LastIndexOf(9, -3, -3)); // Throws ArgumentOutOfRangeException.
Console.WriteLine(list.LastIndexOf(9, 0, -3)); // Throws ArgumentOutOfRangeException.
Console.WriteLine(list.LastIndexOf(9, -3, 0)); // Throws ArgumentOutOfRangeException.
Console.WriteLine(list.LastIndexOf(9, 3, 3)); // Throws ArgumentOutOfRangeException.
Console.WriteLine(list.LastIndexOf(9, -3, 3)); // Throws ArgumentOutOfRangeException.
Console.WriteLine(list.LastIndexOf(9, 3, -3)); // Throws ArgumentOutOfRangeException.
```

### Actual behavior

```cs
List<int> list = new();
Console.WriteLine(list.LastIndexOf(9, -3));  // Doesn't Throw.
Console.WriteLine(list.LastIndexOf(9, 3)); // Throws ArgumentOutOfRangeException.
Console.WriteLine(list.LastIndexOf(9, -3, -3)); // Doesn't Throw.
Console.WriteLine(list.LastIndexOf(9, 0, -3)); // Doesn't Throw.
Console.WriteLine(list.LastIndexOf(9, -3, 0)); // Doesn't Throw.
Console.WriteLine(list.LastIndexOf(9, 3, 3)); // Doesn't Throw.
Console.WriteLine(list.LastIndexOf(9, -3, 3)); // Doesn't Throw.
Console.WriteLine(list.LastIndexOf(9, 3, -3)); // Doesn't Throw.

list = new() { 1 };
Console.WriteLine(list.LastIndexOf(9, -3)); // Throws ArgumentOutOfRangeException.
Console.WriteLine(list.LastIndexOf(9, 3)); // Throws ArgumentOutOfRangeException.
Console.WriteLine(list.LastIndexOf(9, -3, -3)); // Throws ArgumentOutOfRangeException.
Console.WriteLine(list.LastIndexOf(9, 0, -3)); // Throws ArgumentOutOfRangeException.
Console.WriteLine(list.LastIndexOf(9, -3, 0)); // Throws ArgumentOutOfRangeException.
Console.WriteLine(list.LastIndexOf(9, 3, 3)); // Throws ArgumentOutOfRangeException.
Console.WriteLine(list.LastIndexOf(9, -3, 3)); // Throws ArgumentOutOfRangeException.
Console.WriteLine(list.LastIndexOf(9, 3, -3)); // Throws ArgumentOutOfRangeException.
```

### Regression?

No idea.

### Known Workarounds

Manually validate the parameters before calling the method.

### Configuration

I did this tests in `Sharplab` using `Default` configuration.
Also tested in target framework `net8.0`.

### Other information

The first two checks are directly ignored if `Count` is 0.
Then an early return check is done if `_size == 0`, but there are still more checks.
This causes this inconsistency between empty lists and non-empty ones.

https://github.com/dotnet/runtime/blob/dfc2b85a00f3baf5ac52d7615bf857e6217011c8/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/List.cs#L908-L936

If this doesn't count as a bug, I would like to know why it doesn't, and why this unusual behaviour was chosen for this method as I find it very curious.

Thanks

**Comment by eiriktsarpalis** [comment] 2024-10-21 10:40
Duplicate of #44353

**Closed by eiriktsarpalis** 2024-10-21 10:40 UTC
Labels: area-System.Collections, untriaged
