### ISSUE TITLE
Test failure System.Text.Json.Serialization.Tests.WriteValueTests.SerializeExceedMaximumBufferSize

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#66487] opened 2022-03-11 01:17 UTC
Run: [runtime-libraries-coreclr outerloop 20220310.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1656016&view=ms.vss-test-web.build-test-results-tab&runId=45637978&resultId=103979&paneView=debug)

Failed test:
```
net7.0-OSX-Release-x64-CoreCLR_release-OSX.1200.Amd64.Open

- System.Text.Json.Serialization.Tests.WriteValueTests.SerializeExceedMaximumBufferSize

```
**Error message:**
```
Assert.Throws() Failure
Expected: typeof(System.OutOfMemoryException)
Actual:   typeof(System.NullReferenceException): Object reference not set to an instance of an object.
---- System.NullReferenceException : Object reference not set to an instance of an object.


Stack trace
   at System.Text.Json.JsonSerializerOptions.GetJsonTypeInfoFromContextOrCreate(Type type) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs:line 614
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory) in /_/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs:line 1146
   at System.Text.Json.JsonSerializerOptions.CachingContext.GetOrAddJsonTypeInfo(Type type) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Caching.cs:line 104
   at System.Text.Json.JsonSerializerOptions.GetOrAddJsonTypeInfo(Type type) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Caching.cs:line 34
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type runtimeType) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Helpers.cs:line 26
   at System.Text.Json.JsonSerializer.Serialize(Object value, Type inputType, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.String.cs:line 63
   at System.Text.Json.Serialization.Tests.WriteValueTests.<>c__DisplayClass16_0.<SerializeExceedMaximumBufferSize>b__0() in /_/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/Serialization/WriteValueTests.cs:line 394
----- Inner Stack Trace -----
   at System.Text.Json.JsonSerializerOptions.GetJsonTypeInfoFromContextOrCreate(Type type) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs:line 614
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory) in /_/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs:line 1146
   at System.Text.Json.JsonSerializerOptions.CachingContext.GetOrAddJsonTypeInfo(Type type) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Caching.cs:line 104
   at System.Text.Json.JsonSerializerOptions.GetOrAddJsonTypeInfo(Type type) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Caching.cs:line 34
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type runtimeType) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Helpers.cs:line 26
   at System.Text.Json.JsonSerializer.Serialize(Object value, Type inputType, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.String.cs:line 63
   at System.Text.Json.Serialization.Tests.WriteValueTests.<>c__DisplayClass16_0.<SerializeExceedMaximumBufferSize>b__0() in /_/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/Serialization/WriteValueTests.cs:line 394
```

**Comment by fanyang-mono** [comment] 2022-03-11 21:14
I've seen this same error message hit by multiple tests in multiple rolling builds starting from #20220308.49
System.Text.Json.Nodes.Tests.JsonArrayTests.ConvertJSONArrayToJsonArray
System.Text.Json.Nodes.Tests.JsonObjectTests.CaseSensitivity_ReadMode
System.Text.Json.Serialization.Tests.StreamTests_Async.SerializeEmptyCollection
System.Text.Json.Serialization.Tests.DictionaryTests+DictionaryPolymorphicKeyUnsupported.ThrowUnsupported_SerializeAsync

**Comment by eiriktsarpalis** [comment] 2022-03-14 13:14
Duplicate of #66469.

**Closed by eiriktsarpalis** 2022-03-14 13:14 UTC
Labels: area-System.Text.Json, os-mac-os-x, arch-x64, untriaged, blocking-outerloop
