### ISSUE TITLE
Binding collection is not working for options in .net 7.0.1 - it is working in version 7.0.0 and below

### ISSUE THREAD

**Issue by msmolka** [dotnet/runtime#79904] opened 2022-12-22 10:03 UTC
### Description

I have following code for options:
https://github.com/msmolka/ZNetCS.AspNetCore.IPFiltering/blob/c4f6d097351e2d40126cd4be67d506e4fae6b1b3/src/ZNetCS.AspNetCore.IPFiltering/OptionBase.cs

Above code works properly in version  7.0.0 and below

However after applying 7.0.1 patch it stopped working.
We had to change code to following:

https://github.com/msmolka/ZNetCS.AspNetCore.IPFiltering/blob/4434801b441d3d8ba93c00649be148df52b43ed5/src/ZNetCS.AspNetCore.IPFiltering/OptionBase.cs

### Reproduction Steps

Grab repo at point:
 https://github.com/msmolka/ZNetCS.AspNetCore.IPFiltering/tree/f60a40de740681ed58cbd9906dcf46466f7513e6

2 test are failing for .net 7.0 (only after applying patch). They are passing before applying 7.0.1 patch

### Expected behavior

There are no braking changes in patch version

### Actual behavior

Breaking changes in patch version

### Regression?

it is working on version 7.0.0. and below

### Known Workarounds

https://github.com/msmolka/ZNetCS.AspNetCore.IPFiltering/blob/master/src/ZNetCS.AspNetCore.IPFiltering/OptionBase.cs

**Comment by jeffschwMSFT** [comment] 2022-12-31 19:12
@msmolka thanks for providing the code with tests.  Can you provide a small repro that highlights what is happening and what you would expect to happen?

**Comment by gao-artur** [comment] 2023-01-04 13:23
I am hitting the same issue. The setter will be executed only when the corresponding property exists in the configuration source.
For example:
```csharp
public class MyOptions
{
    private int _numOfRetries;
    public int NumOfRetries
    {
        get => _numOfRetries;
        set => _numOfRetries = value != 0 ? value : 5;
    }
}

var myOptions = configuration.GetSection("MyOptions").Get<MyOptions>();
```
In .NET 6, when the `MyOptions:NumOfRetries` is not defined in any configuration source, the setter is executed and `NumOfRetries = 5`. In .NET 7.0.1 the setter is not executed and `NumOfRetries = 0`

**Comment by tarekgh** [comment] 2023-01-06 02:47
@msmolka @gao-artur could you please provide a complete sample reproduce the issue? Thanks!

Also, could you try the same repo with the following version of the library and let me know?

```Xml
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.0-alpha.1.22578.1" />
```

from the nuget feed:

```Xml
    <add key="dotnet8" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json" />
```

**Comment by gao-artur** [comment] 2023-01-06 14:00
Hey @tarekgh, here is the test to reproduce the breaking change/regression:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;net7.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net6.0' ">
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net7.0' ">
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.4.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.0.2" />
    <PackageReference Include="MSTest.TestFramework" Version="3.0.2" />
  </ItemGroup>

</Project>
```

```csharp
using System.Collections.Generic;
using Microsoft.Extensions.Configuration;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace TestProject2;

[TestClass]
public class UnitTest1
{
    [TestMethod]
    public void TestMethod1()
    {
        var configuration = new ConfigurationBuilder()
            .AddInMemoryCollection(new Dictionary<string, string>
            {
                ["MyOptions:Option1"] = "3"
            })
            .Build();

        var myOptions = configuration.GetSection("MyOptions").Get<MyOptions>();

        Assert.IsNotNull(myOptions);

        // exists in configuration and properly sets the property
        Assert.AreEqual(3, myOptions.Option1);

        // doesn't exist in configuration. In net6.0 the setter sets default value '2' but not in net7.0
        Assert.AreEqual(2, myOptions.Option2);
    }
}

public class MyOptions
{
    private int _option1;
    private int _option2;

    public int Option1
    {
        get => _option1;
        set => _option1 = value == 0 ? 1 : value;
    }

    public int Option2
    {
        get => _option2;
        set => _option2 = value == 0 ? 2 : value;
    }
}
```

`dotnet test` result
```
Test run for C:\github\junk\TestProject2\TestProject2\bin\Debug\net6.0\TestProject2.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.4.0 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.

Passed!  - Failed:     0, Passed:     1, Skipped:     0, Total:     1, Duration: 28 ms - TestProject2.dll (net6.0)
Test run for C:\github\junk\TestProject2\TestProject2\bin\Debug\net7.0\TestProject2.dll (.NETCoreApp,Version=v7.0)
Microsoft (R) Test Execution Command Line Tool Version 17.4.0 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed TestMethod1 [20 ms]
  Error Message:
   Assert.AreEqual failed. Expected:<2>. Actual:<0>.
  Stack Trace:
     at TestProject2.UnitTest1.TestMethod1() in C:\github\junk\TestProject2\TestProject2\UnitTest1.cs:line 28
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)


Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration: 31 ms - TestProject2.dll (net7.0)
```

`dotnet --list-sdks` result
```
6.0.404 [C:\Program Files\dotnet\sdk]
7.0.101 [C:\Program Files\dotnet\sdk]
```

**Comment by gao-artur** [comment] 2023-01-06 14:04
The issue also persists in the `8.0.0-alpha.1.22578.1`.

**Comment by tarekgh** [comment] 2023-01-09 15:54
@gao-artur thanks for providing the repro. I see your repro code is failing on .NET `7.0.0` and `7.0.1` too. That is different than what @msmolka claimed that the problem was not happening on `7.0.0`. @msmolka could you please provide a complete sample code to demonstrate your issue just in case it is different than what @gao-artur reported here?

**Comment by msmolka** [comment] 2023-01-09 20:09
Hi, here is working repo, but during creation I found that bug is in fact in **Microsoft.Extensions.Configuration.Binder** package.

When package is 7.0.0 and below all is working. 7.0.1 and above not.

Repo will throw exception in v 7.0.1 and will work below.


[ConfigBinding.zip](https://github.com/dotnet/runtime/files/10376527/ConfigBinding.zip)

**Comment by tarekgh** [comment] 2023-01-09 20:56
Thanks @msmolka I'll try your repo too. I already created a local fix for @gao-artur issue.

**Comment by tarekgh** [comment] 2023-01-13 17:16
Fixed by https://github.com/dotnet/runtime/pull/80562

**Closed by tarekgh** 2023-01-13 17:16 UTC
Labels: area-Extensions-Options, needs-further-triage
