### ISSUE TITLE
Builds targeting rid win7-x64 don't actually target win7-x64

### ISSUE THREAD

**Issue by jhudsoncedaron** [dotnet/runtime#80304] opened 2023-01-06 18:45 UTC
### Description

Builds targeting rid win7-x64 don't actually target win7-x64 -- the required api-ms-win-* dlls are not output by the package step

Also, builds targeting rid win81-x64 don't target win8.1 for the same reason. Upgrading from win7-x64 to win81-x64 does not help.

The actual target is Windows Server 2012 R2

Demonstration of the package difference:

```
C:\Users\jhudson\dev\src\WebAPI\bin\Release\net6.0\win7-x64>c:\cygwin64\bin\grep api-ms-win *.dll
/usr/bin/grep: Microsoft.AspNetCore.Server.HttpSys.dll: binary file matches
/usr/bin/grep: Microsoft.AspNetCore.Server.IIS.dll: binary file matches
/usr/bin/grep: System.IO.Compression.Native.dll: binary file matches
/usr/bin/grep: api-ms-win-core-console-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-core-console-l1-2-0.dll: binary file matches
/usr/bin/grep: api-ms-win-core-datetime-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-core-debug-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-core-errorhandling-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-core-fibers-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-core-file-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-core-file-l1-2-0.dll: binary file matches
/usr/bin/grep: api-ms-win-core-file-l2-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-core-handle-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-core-heap-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-core-interlocked-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-core-libraryloader-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-core-localization-l1-2-0.dll: binary file matches
/usr/bin/grep: api-ms-win-core-memory-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-core-namedpipe-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-core-processenvironment-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-core-processthreads-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-core-processthreads-l1-1-1.dll: binary file matches
/usr/bin/grep: api-ms-win-core-profile-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-core-rtlsupport-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-core-string-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-core-synch-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-core-synch-l1-2-0.dll: binary file matches
/usr/bin/grep: api-ms-win-core-sysinfo-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-core-timezone-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-core-util-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-crt-conio-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-crt-convert-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-crt-environment-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-crt-filesystem-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-crt-heap-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-crt-locale-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-crt-math-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-crt-multibyte-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-crt-private-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-crt-process-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-crt-runtime-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-crt-stdio-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-crt-string-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-crt-time-l1-1-0.dll: binary file matches
/usr/bin/grep: api-ms-win-crt-utility-l1-1-0.dll: binary file matches
/usr/bin/grep: aspnetcorev2_inprocess.dll: binary file matches
/usr/bin/grep: clrjit.dll: binary file matches
/usr/bin/grep: coreclr.dll: binary file matches
/usr/bin/grep: dbgshim.dll: binary file matches
/usr/bin/grep: hostfxr.dll: binary file matches
/usr/bin/grep: hostpolicy.dll: binary file matches
/usr/bin/grep: mscordaccore.dll: binary file matches
/usr/bin/grep: mscordaccore_amd64_amd64_6.0.422.16404.dll: binary file matches
/usr/bin/grep: mscordbi.dll: binary file matches
/usr/bin/grep: sni.dll: binary file matches
/usr/bin/grep: ucrtbase.dll: binary file matches

C:\Users\jhudson\dev\src\WebAPI\bin\Release\net7.0\win7-x64>c:\cygwin64\bin\grep api-ms-win *.dll
/usr/bin/grep: Microsoft.AspNetCore.Server.HttpSys.dll: binary file matches
/usr/bin/grep: Microsoft.AspNetCore.Server.IIS.dll: binary file matches
/usr/bin/grep: System.IO.Compression.Native.dll: binary file matches
/usr/bin/grep: aspnetcorev2_inprocess.dll: binary file matches
/usr/bin/grep: clrgc.dll: binary file matches
/usr/bin/grep: clrjit.dll: binary file matches
/usr/bin/grep: coreclr.dll: binary file matches
/usr/bin/grep: hostfxr.dll: binary file matches
/usr/bin/grep: hostpolicy.dll: binary file matches
/usr/bin/grep: mscordaccore.dll: binary file matches
/usr/bin/grep: mscordaccore_amd64_amd64_7.0.122.56804.dll: binary file matches
/usr/bin/grep: mscordbi.dll: binary file matches
/usr/bin/grep: sni.dll: binary file matches

C:\Users\jhudson\dev\src\WebAPI\bin\Release\net7.0\win7-x64>c:\cygwin64\bin\grep api-ms-win-core-memory-l1-1-0 *.dll

C:\Users\jhudson\dev\src\WebAPI\bin\Release\net7.0\win7-x64>c:\cygwin64\bin\grep api-ms-win-crt-heap-l1-1-0 *.dll
/usr/bin/grep: System.IO.Compression.Native.dll: binary file matches
/usr/bin/grep: aspnetcorev2_inprocess.dll: binary file matches
/usr/bin/grep: clrgc.dll: binary file matches
/usr/bin/grep: clrjit.dll: binary file matches
/usr/bin/grep: coreclr.dll: binary file matches
/usr/bin/grep: hostfxr.dll: binary file matches
/usr/bin/grep: hostpolicy.dll: binary file matches
/usr/bin/grep: mscordaccore.dll: binary file matches
/usr/bin/grep: mscordaccore_amd64_amd64_7.0.122.56804.dll: binary file matches
/usr/bin/grep: mscordbi.dll: binary file matches
/usr/bin/grep: sni.dll: binary file matches
```

### Reproduction Steps

Build and package an executable image targeting win7-x64 ; observe the api-ms-win-*.dlls are not present in the package output.

Binaries are working on my test machine because the dlls are present in C:\Windows\System32 due to some other package installation; but they won't work out of the box because those dlls weren't always there.

### Expected behavior

Either win7-x64 RID produces a package with all its dependencies or the a compile error

Other rids likely to be affected:

win7-x86
win81-x64 (known)
win81-x86
win81-arm

### Actual behavior

Packaging the rid produces an incorrect package

### Regression?

Yes; from NET 6.0

### Known Workarounds

Not yet

### Configuration

NET 7.0.101 (toolchain version) ; build machine is Windows 11 x64; target machine is Windows Server 2012 R2 x64

**Comment by teo-tsirpanis** [comment] 2023-01-06 19:08
@jhudsoncedaron Windows Server 2012 R2 is using the `win81-x64` RID. Can you update your issue to remove references to `win7-x64` to avoid confusion?

(I was going to summarily close it until I realized that Windows Server 2012 R2 is still supported on an ESU)

**Comment by jhudsoncedaron** [comment] 2023-01-06 19:32
@teo-tsirpanis : Not really; changing to win81 is not trivial for reasons I'd rather not get into and doesn't actually fix the problem. (If it did fix the problem I would change it.) I suppose I could update the title but that's even more confusing.

**Comment by jkotas** [comment] 2023-01-06 23:39
> Binaries are working on my test machine because the dlls are present in C:\Windows\System32 due to some other package installation;

These .dlls are installed by the documented prerequisites: https://learn.microsoft.com/en-us/dotnet/core/install/windows?tabs=net70#additional-deps

**Closed by jkotas** 2023-01-06 23:39 UTC
Labels: os-windows, area-Host

**Comment by MichalPetryka** [comment] 2023-01-07 21:13
> > Binaries are working on my test machine because the dlls are present in C:\Windows\System32 due to some other package installation;
> 
> These .dlls are installed by the documented prerequisites: https://learn.microsoft.com/en-us/dotnet/core/install/windows?tabs=net70#additional-deps

That table seems to be wrong because Windows 8.1 (and probably Server 2012 R2) require a separate update for those to be present too.

**Comment by jkotas** [comment] 2023-01-07 21:32
> a separate update ([KB2999226](https://support.microsoft.com/en-us/topic/update-for-universal-c-runtime-in-windows-c0514201-7fe6-95a3-b0a5-287930f3560c)) for those to be present too.

This KB is same as "Microsoft Visual C++ 2015-2019 Redistributable" listed in the table, no?

**Comment by teo-tsirpanis** [comment] 2023-01-07 21:34
It seems not, the C++ redist does not have a KB.

**Comment by jkotas** [comment] 2023-01-07 21:40
It should be same bits, just packaged differently.

**Comment by MichalPetryka** [comment] 2023-01-07 21:42
> > a separate update ([KB2999226](https://support.microsoft.com/en-us/topic/update-for-universal-c-runtime-in-windows-c0514201-7fe6-95a3-b0a5-287930f3560c)) for those to be present too.
> 
> This KB is same as "Microsoft Visual C++ 2015-2019 Redistributable" listed in the table, no?

It's not, we had to separately ensure our users installed it even after we installed the VC++ Redist for them.

**Comment by jkotas** [comment] 2023-01-07 23:15
What were the missing files that did not get installed by VCRedist?

VCRedist should install the Universal CRT. It is documented in https://learn.microsoft.com/en-us/cpp/windows/universal-crt-deployment: "The Visual C++ Redistributable (VCRedist) installs the initial version of the Universal CRT (version 10.0.10240) on machines that don't already have one installed".

**Comment by MichalPetryka** [comment] 2023-01-07 23:19
`API-MS-WIN-CRT-MATH-L1-1-0.dll` was the file we were checking for in our warning.

**Comment by jkotas** [comment] 2023-01-09 04:56
I was not able to reproduce this. All Win8 and Server2012 machines that I was able to get access to had ucrtbase installed already (ucrtbase is recommended update, so it installs by default).

If you believe that the documentation is wrong or incomplete, feel free to suggest doc updates by opening issue or sending PR in the docs repo.

**Comment by jhudsoncedaron** [comment] 2023-01-09 15:09
@jkotas : You wouldn't happen to have the powershell command to install the update with ucrtbase in it?

**Comment by jkotas** [comment] 2023-01-09 16:33
I do not.
