### ISSUE TITLE
[NativeAOT] Support InlineArray larger than 1Mb

### ISSUE THREAD

**Issue by lucabol** [dotnet/runtime#98024] opened 2024-02-06 09:18 UTC
### Description

I am trying to create large static arrays in the .bss sector as in C `char _bigBuffer[2000000];`. I am using `InlineArray` for  that, but they fail `dotnet publish` if bigger than 1MB (see repro).

They don't seem to have this limit if not using AOT.

### Reproduction Steps

1. Publish the code below
```csharp
[System.Runtime.CompilerServices.InlineArray(2_000_000)]
public struct Big_Buffer{ private byte _element0; }

class Program
{
    static Big_Buffer _bigBuffer;
    static void Main(string[] args)
    {
        System.Console.WriteLine(_bigBuffer[0]);
    }
}
```

### Expected behavior

No error.

### Actual behavior

```console
EXEC : error : Array of type 'Big_Buffer' from assembly 'Test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' cannot be created because base value type is too large [C:\Users\lucabol\source\
repos\Test\Test.csproj]
```

### Regression?

New feature.

### Known Workarounds

I think the best workaround is the `unsafe` code below, but perhaps there are others ... Generally, `C#` syntactic sugar would be nice for this scenario IMO.

```csharp
    public unsafe struct HugeBuffer<T> where T: unmanaged
    {
        fixed byte _buf[2_000_000];

        public ref T this[int index]
        {
            get {
                return ref Unsafe.Add(ref Unsafe.As<byte, T>(ref _buf[0]), index);
            }
        }
        public static implicit operator System.Span<T>(HugeBuffer<T> buffer)
            => MemoryMarshal.CreateSpan(ref Unsafe.As<byte,T>(ref buffer._buf[0]), M8 / sizeof(T)); 
        public int Length => 2_000_000 / sizeof(T);
    }

```

### Configuration

.net 8, win11 x64

**Comment by SingleAccretion** [comment] 2024-02-06 10:53
Fixed in #97403, there was some discussion about backporting in #97533.

**Comment by MichalStrehovsky** [comment] 2024-02-06 10:56
> Fixed in #97403, there was some discussion about backporting in #97533.

Cc @VSadov

**Comment by MichalStrehovsky** [comment] 2024-03-25 07:26
> Fixed in #97403, there was some discussion about backporting in #97533.

@VSadov what are your thoughts on backporting a fix for this? This is the second customer report if we count me hitting this in non-work-related work as "customer". We currently enforce a limit that is too low, and only on native AOT.

**Comment by MichalStrehovsky** [comment] 2024-03-26 21:38
> This was discussed for backporting last time, but we did not pursue it, eventually, as it was not expected to meet the servicing bar. The fix is low-risk, but there are many low-risk fixes. Servicing demands crashes, blocked functionality, no workarounds and the like. The bar is intentionally high.

We discussed backporting the change that fixes this, but also enforces a limit on CoreCLR side. The enforcing of the limit is a breaking change and would not meet servicing bar (we cannot break stuff in servicing). Can't backport that PR, we need a new PR.

This is a customer report reporting a broken behavior after dotnet publish because this is something that works on CoreCLR but throws on native AOT. The part of the bar this could apply to is "Broken or significantly incomplete 8.0 scenario" of the bar.

If you don't intend to work on this, please close. I don't know what to do with this bug other than fixing or won't fixing and I leave the call on you.

**Comment by agocke** [comment] 2024-04-22 21:04
Closing as it sounds like we do not plan to backport this change.

The issue is fixed in .NET 9.

**Closed by agocke** 2024-04-22 21:04 UTC
Labels: untriaged, area-NativeAOT-coreclr
