### ISSUE TITLE
Test failure System.IO.Compression.DeflateStreamUnitTests.Parallel_ReadWriteMultipleStreamsConcurrently

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#65538] opened 2022-02-18 01:19 UTC
Run: [runtime-libraries-coreclr outerloop 20220217.7](https://dev.azure.com/dnceng/public/_build/results?buildId=1618405&view=ms.vss-test-web.build-test-results-tab&runId=45014574&resultId=103134&paneView=debug)

Failed test:
```
net7.0-Linux-Release-arm64-CoreCLR_release-(Ubuntu.1804.ArmArch.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-helix-arm64v8-20210106155927-56c6673

- System.IO.Compression.DeflateStreamUnitTests.Parallel_ReadWriteMultipleStreamsConcurrently

```
**Error message:**
```
System.NullReferenceException : Object reference not set to an instance of an object.


Stack trace
   at System.IO.Compression.DeflateStream..ctor(Stream stream, CompressionMode mode, Boolean leaveOpen, Int32 windowBits, Int64 uncompressedSize) in /_/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/DeflateStream.cs:line 58
   at System.IO.Compression.DeflateStreamUnitTests.CreateStream(Stream stream, CompressionMode mode) in /_/src/libraries/System.IO.Compression/tests/CompressionStreamUnitTests.Deflate.cs:line 14
   at System.IO.Compression.CompressionStreamTestBase.CreateConnectedStreamsAsync() in /_/src/libraries/Common/tests/System/IO/Compression/CompressionStreamTestBase.cs:line 46
   at System.IO.Tests.ConnectedStreamConformanceTests.CopyToAsync_AllDataCopied(Int32 byteCount, Boolean useAsync) in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 2404
   at System.IO.Tests.ConnectedStreamConformanceTests.<Parallel_ReadWriteMultipleStreamsConcurrently>b__47_1() in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 2434
   at System.IO.Tests.ConnectedStreamConformanceTests.Parallel_ReadWriteMultipleStreamsConcurrently() in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 2432
--- End of stack trace from previous location ---

```

**Comment by adamsitnik** [comment] 2022-02-18 07:26
I am moving it to codegen as it's most likely caused by the same issue as https://github.com/dotnet/runtime/issues/65476#issuecomment-1042760755

**Comment by JulieLeeMSFT** [comment] 2022-02-18 17:46
@BruceForstall PTAL. This is blocking outerloop.

**Comment by stephentoub** [comment] 2022-03-01 13:12
> This has only failed once, across many different architectures this test is run on in the "runtime-libraries-coreclr outerloop" job; that makes it very unlikely to be a codegen issue.

@BruceForstall, seems likely it was the same issue as https://github.com/dotnet/runtime/pull/65916?

**Comment by BruceForstall** [comment] 2022-03-01 18:17
> @BruceForstall, seems likely it was the same issue as #65916?

Yes. I'll close this and we'll see if it comes back.

**Closed by BruceForstall** 2022-03-01 18:17 UTC
Labels: arch-arm64, os-linux, area-CodeGen-coreclr, blocking-outerloop
