### ISSUE TITLE
System.Text.Json API Enhancement: Serialize to stream synchronized methods

### ISSUE THREAD

**Issue by CodeBlanch** [dotnet/runtime#31669] opened 2020-02-03 18:23 UTC
# Proposed API
The current System.Text.Json API supports these two methods:

```csharp
Task SerializeAsync<TValue>(Stream utf8Json, TValue value, JsonSerializerOptions? options = null, CancellationToken cancellationToken = default);
Task SerializeAsync(Stream utf8Json, object? value, Type inputType, JsonSerializerOptions? options = null, CancellationToken cancellationToken = default);
```

I'm proposing we add:

```csharp
void Serialize<TValue>(Stream utf8Json, TValue value, JsonSerializerOptions? options = null);
void Serialize(Stream utf8Json, object? value, Type inputType, JsonSerializerOptions? options = null);
```

Which are basically overloads for synchronized writing to a Stream.

# Rationale & Usage
I have a logging library that maintains its own dedicated thread for pumping messages to a file via FileStream. The current API does not provide an efficient way to handle this.

Using the existing async API:

```csharp
		private void DrainMessagesThreadBody()
		{
			Stream LogFile = _LogFileManager.FindCurrentLogFile();

			while (true)
			{
				if (!_Messages.TryDequeue(out Message Message))
					break;

				SerializeMessageToJson(LogFile, Message).GetAwaiter().GetResult();
			}
		}

		private async Task SerializeMessageToJson(Stream stream, Message message)
		{
			await JsonSerializer.SerializeAsync(stream, message, _JsonOptions).ConfigureAwait(false);

			await stream.WriteAsync(s_NewLine, 0, s_NewLine.Length).ConfigureAwait(false);

			await stream.FlushAsync().ConfigureAwait(false);
		}
```

This is the "Sync over Async" anti-pattern. There is a dedicated thread but it has to use the pool to do its work.

Using the existing sync API:

```csharp
		private void DrainMessagesThreadBody()
		{
			Stream LogFile = _LogFileManager.FindCurrentLogFile();

			while (true)
			{
				if (!_Messages.TryDequeue(out Message Message))
					break;

				SerializeMessageToJson(LogFile, Message);
			}
		}

		private void SerializeMessageToJson(Stream stream, Message message)
		{
			BufferWriter BufferWriter = new BufferWriter();
			using (Utf8JsonWriter Writer = new Utf8JsonWriter(BufferWriter))
			{
				JsonSerializer.Serialize(Writer, message, _JsonOptions);
			}
			BufferWriterr.WriteToStream(stream);
			stream.Write(s_NewLine, 0, s_NewLine.Length);
			stream.Flush();
		}
```

Works fine, but the problem is `BufferWriter` doesn't exist. I had to roll that based on the System.Text.Json `PooledByteBufferWriter`, which is internal. That is a lot of heavy lifting in order to make the usage efficent via buffer reuse. What I really wanted to do is reuse the pooling buffer code already in the lib (used by SerializeAsync calls).

Here's how it would look using the proposed API:

```csharp
		private void DrainMessagesThreadBody()
		{
			Stream LogFile = _LogFileManager.FindCurrentLogFile();

			while (true)
			{
				if (!_Messages.TryDequeue(out Message Message))
					break;

				SerializeMessageToJson(LogFile, Message);
			}
		}

		private void SerializeMessageToJson(Stream stream, Message message)
		{
			JsonSerializer.Serialize(stream, message, _JsonOptions);
			stream.Write(s_NewLine, 0, s_NewLine.Length);
			stream.Flush();
		}
```

With the new API caller doesn't need to worry about correct usage (buffer pooling), it just happens under the hood as it does with SerializeAsync calls.

**Comment by ahsonkhan** [comment] 2020-02-21 00:22
This is a duplicate of https://github.com/dotnet/runtime/issues/1574.

**Closed by ahsonkhan** 2020-02-21 00:22 UTC
Labels: api-suggestion, area-System.Text.Json, untriaged
