### ISSUE TITLE
Test failure: System.Threading.Channels.Tests.BoundedChannelTests.ManyProducerConsumer_ConcurrentReadWrite_WithBufferedCapacity_Success - NullReferenceException

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#71035] opened 2022-06-21 01:02 UTC
Affected test:
- ManyProducerConsumer_ConcurrentReadWrite_WithBufferedCapacity_Success - `System.Threading.Channels.Tests.BoundedChannelTests.ManyProducerConsumer_ConcurrentReadWrite_WithBufferedCapacity_Success`

Failures:
- [1833880](https://runfo.azurewebsites.net/view/build/?number=1833880) (6/20 AM)
    - net7.0-Linux-Release-arm-CoreCLR_release-(Debian.10.Arm32.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-arm32v7-20210304164340-6616c63

Failures frequency:
- 6/20 -- 1x failure in [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime-extra-platforms+name%3A%22system.threading.channels.tests.boundedchanneltests.manyproducerconsumer_concurrentreadwrite_withbufferedcapacity_success%22) and also in [last 120 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E120+definition%3Aruntime-extra-platforms+name%3A%22system.threading.channels.tests.boundedchanneltests.manyproducerconsumer_concurrentreadwrite_withbufferedcapacity_success%22)

Error:
```
      System.AggregateException : One or more errors occurred. (Object reference not set to an instance of an object.)
      ---- System.NullReferenceException : Object reference not set to an instance of an object.

      Stack Trace:
        /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs(4896,0): at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
        /_/src/libraries/System.Threading.Channels/tests/BoundedChannelTests.cs(593,0): at System.Threading.Channels.Tests.BoundedChannelTests.ManyProducerConsumer_ConcurrentReadWrite_WithBufferedCapacity_Success(Int32 bufferedCapacity)
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs(64,0): at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
        ----- Inner Stack Trace -----
        /_/src/libraries/System.Threading.Channels/tests/BoundedChannelTests.cs(566,0): at System.Threading.Channels.Tests.BoundedChannelTests.<>c__DisplayClass23_0.<<ManyProducerConsumer_ConcurrentReadWrite_WithBufferedCapacity_Success>b__0>d.MoveNext()
```

**Comment by stephentoub** [comment] 2022-06-21 01:04
This looks like a duplicate of https://github.com/dotnet/runtime/issues/70061.

**Comment by joperezr** [comment] 2022-06-29 17:06
Closing as a dupe for now. @karelz feel free to reopen if this is not a dupe.

**Closed by joperezr** 2022-06-29 17:06 UTC
Labels: area-System.Threading.Channels, untriaged

**Comment by karelz** [comment] 2022-06-30 19:49
Not sure, why GH search didn't find the previous error - I think it is rather picky :(
