### ISSUE TITLE
Please consider letting a user set `MaxPayloadLength` (or, adhere to HTTP/2 spec)

### ISSUE THREAD

**Issue by gjtorikian** [dotnet/runtime#56542] opened 2021-07-29 12:41 UTC
### Description

I'm working on tracking down a solution for https://github.com/alpacahq/alpaca-trade-api-csharp/issues/348, which occurs when an HTTP 2 request with a large payload is made. Inevitably, the request crashes:

```
Unhandled exception. System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The request was aborted.
 ---> System.IO.IOException: The response ended prematurely while waiting for the next frame from the server.
   at System.Net.Http.Http2Connection.<ReadFrameAsync>g__ThrowMissingFrame|48_1()
   at System.Net.Http.Http2Connection.ReadFrameAsync(Boolean initialFrame)
   at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders()
   at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.Wrap.AsyncPolicyWrapEngine.<>c__DisplayClass2_0`1.<<ImplementationAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.Wrap.AsyncPolicyWrapEngine.ImplementationAsync[TResult](Func`3 func, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext, IAsyncPolicy outerPolicy, IAsyncPolicy`1 innerPolicy)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Alpaca.Markets.ThrottleParameters.CustomHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson](HttpMessageInvoker httpClient, HttpRequestMessage request, CancellationToken cancellationToken)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson](HttpMessageInvoker httpClient, HttpMethod method, Uri endpointUri, CancellationToken cancellationToken)
   at Alpaca.Markets.HttpClientExtensions.GetAsync[TKeyApi,TValueApi,TKeyJson,TValueJson](HttpClient httpClient, UriBuilder uriBuilder, IEqualityComparer`1 comparer, Func`2 elementSelector, CancellationToken cancellationToken)
   at Alpaca.Markets.AlpacaDataClient.GetSnapshotsAsync(IEnumerable`1 symbols, CancellationToken cancellationToken)
   ```
   
This same request, however, passes when using plain curl. From the original issue:

> * The curl always sends an URL and headers in the single HTTP/2 headers frame. The buffer size is big enough to take 64K of data and only if the frame size exceeds 60K bytes you'll see the warning in the curl error output.
> * The .NET instead sends this data in a sequence of HTTP/2 frames because it split the big payload using [this threshold](https://github.com/dotnet/runtime/blob/04a8f5e01dd78646e574f07573b9787b3caade51/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L1809) value.

 This is the line of code setting the payload threshold value:
  https://github.com/dotnet/runtime/blob/04a8f5e01dd78646e574f07573b9787b3caade51/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L1809

I ran through git blame, and found https://github.com/dotnet/runtime/commit/39b260caba5e81972f07a55bcf8f9a40f1b15a87#diff-9298431bc1e112a1f903a5925772830dbf50be69a8e2da20f31496ee19c414b2R443 as the commit four years ago which first added the max value. However, there's no indication of _why_ such a low number was chosen. Except...

[In the original HTTP2 RFC](https://datatracker.ietf.org/doc/html/rfc7540#section-6.5.2), the following is written:

```
SETTINGS_MAX_FRAME_SIZE (0x5):  Indicates the size of the largest
      frame payload that the sender is willing to receive, in octets.

      The initial value is 2^14 (16,384) octets.  The value advertised
      by an endpoint **MUST** be between this initial value and the maximum
      allowed frame size (2^24-1 or 16,777,215 octets), inclusive.
      Values outside this range MUST be treated as a connection error
      (Section 5.4.1) of type PROTOCOL_ERROR.
```

It seems that the maximum payload size threshold to the _lowest_ possible value, according to the spec. I think the maximum value should change to either the actual maximum (2^24-1), or at least, allow the user to set a payload size that permits any value within the range specified in the spec.

**Comment by karelz** [comment] 2021-07-29 12:56
@gjtorikian it should be perfectly legal to send HEADERS in multiple frames. There is no need to send them in 1 frame.
I assume that unless the server sent SETTINGS_MAX_FRAME_SIZE with larger number, we even can't send larger frames.

I wonder if this isn't a problem of server -- is it behaving correctly? Which server is it? Are you able to test against different server?
Can you look at packet capture traces to see what is happening?

**Comment by OlegRa** [comment] 2021-07-29 13:28
@karelz As a person who investigated this issue from the client side I agree - it's not a .NET problem itself. Sending requests in multiply frames is standard-conforming and better from the memory usage perspective. I think @gjtorikian just wants to have the ability to tune this behavior. Not all servers are under developers' control and in this case NGNIX server used by the API provider configured badly - it just drops connection in case of chunked request instead of responding with 400 or 414 error codes. Ironically, the Windows-only .NET Framework workaround version with WinHttpHandler works fine on my Windows 10 box :)

**Comment by geoffkizer** [comment] 2021-07-29 16:20
Agreed, this is not a .NET issue. What we are sending is legal per RFC and the server should accept it.

That said, if this is a common interop issue, we can certainly look at adjusting our behavior here to deal better with nonconforming servers.

**Comment by karelz** [comment] 2021-07-29 17:07
@OlegRa do you know which exact version of server it was? Did you find out what is misconfigured there?

**Comment by OlegRa** [comment] 2021-07-29 22:43
@karelz Unfortunately, not. I'm just developing/supporting the OSS SDK for this API. I've checked the NGNIX bug tracker and found several issues related to this behavior. In the case of HTTP/1.1 NGNIX returns proper responses but in the case of HTTP/2 sometimes it just drops the connecitons.

**Comment by karelz** [comment] 2021-07-30 09:04
I am curious if NGINX takes it as a bug on their side which they will fix eventually. If that is true, perhaps it is not worth addressing on our side.
We should not take action until we have more details and see more customers falling into this.

Otherwise, we would have to compensate for any bug of evert HTTP/2 server out there, which doesn't make much sense ...

**Comment by gjtorikian** [comment] 2021-07-30 13:58
One thing I'm not understanding is why `curl` succeeds at making the call, but a DotNet program doesn't. Server misconfigurations not withstanding, what explains the differences in the client responses?

**Comment by OlegRa** [comment] 2021-07-31 18:34
@gjtorikian The `curl` tool sends only one frame with a full URL, the `HttpClient` sends several frames (at least two in your case). The behavior is different because NGNIX handles these cases differently. I've found at least 10 different bug reports related to this strange behavior in the NGNIX bug tracker ([this issue is a good root point](https://trac.nginx.org/nginx/ticket/1520) with a list of related issues).

The most interesting and relevant to our discussion [answer](https://trac.nginx.org/nginx/ticket/793) is authored by NGNIX creator Valentin V. Bartenev (@VBart here on GitHub):

> Regarding the error message, there is no way to return HTTP response in case of HTTP/2 connection-level error.

I don't have enough knowledge to comment on this but most probably it means this behavior of NGNIX will be never changed. Unfortunately, I don't have access to the NGNIX configuration for this server and am unable to provide real config values.

**Comment by gjtorikian** [comment] 2021-08-01 22:25
> The curl tool sends only one frame with a full URL, the HttpClient sends several frames (at least two in your case). The behavior is different because NGNIX handles these cases differently.

What I’m asking is: what defines how many frames a client (curl, `HttpClient`, etc) sends, given the same URL? I understand that nginx behaves differently based on the frame count. But could/should there be some configuration available for clients to work around that? 

Nginx is crazy popular, but if they won’t address the issue, and if two clients behave differently, it seems to me that there _can_ be a solution depending on how a client makes its request.

**Comment by OlegRa** [comment] 2021-08-03 09:59
@gjtorikian In most cases, NGNIX setup is balancing between speed, performance, and security. The huge requests can be a signal of a DDoS attack based on OOM conditions on the server-side. In our case - the Alpaca IT guys increased the buffer sizes and the problem is now solved.
@karelz I think we can close this issue - the .NET implementation conforms to the standard and handles the connection drop (in case of "misconfigured" NGNIX) correctly.

**Comment by geoffkizer** [comment] 2021-08-03 15:02
Are we sure that this is an NGINX issue? I looked through the linked issues, and I see a lot of stuff about header size limits, but I don't see anything specifically about not supporting headers being sent in multiple frames. Did I miss it?

It's possible the issue is in how we are sending the headers across multiple frames. Seems like we should confirm that this works with other servers. I think we have tests that do this, but it's possible we missed something here.

**Comment by geoffkizer** [comment] 2021-08-03 15:10
> What I’m asking is: what defines how many frames a client (curl, HttpClient, etc) sends, given the same URL?

The client is allowed to send the headers in as many frames as it wants to; see https://httpwg.org/specs/rfc7540.html#HeaderBlock.

**Comment by gjtorikian** [comment] 2021-08-03 16:16
> The client is allowed to send the headers in as many frames as it wants to; see https://httpwg.org/specs/rfc7540.html#HeaderBlock.

That's partially what I mean: shouldn't this `HttpClient` allow me to set that value?

**Comment by OlegRa** [comment] 2021-08-03 16:35
@geoffkizer It's definitely an NGNIX issue - after increasing buffer sizes all works as expected with the current `HttpClient` implementation.

AFAIU the `curl` uses Huffman compression for headers and most probably this particular request is well compressed and fits into the single frame. The NGNIX has several configuration values for incoming buffers and some of them related to raw data only and others for unpacked data only. And most of these configuration values are deprecated since the 1.19.7 (this February) release in favor of the single `large_client_header_buffers` setting that is used by both HTTP/1.1 and HTTP/2 modules and applied for both packed/raw data.

**Comment by karelz** [comment] 2021-08-20 11:22
Closing as per suggestion above https://github.com/dotnet/runtime/issues/56542#issuecomment-891710599

If we see more instances or servers having problem with this, we can reconsider alternative solutions.
If you find this issue, please create a new one and link it. Thanks!

**Closed by karelz** 2021-08-20 11:22 UTC
Labels: enhancement, area-System.Net.Http, needs more info
