### ISSUE TITLE
Test failure System.Net.Quic.Tests.QuicListenerTests.AcceptConnectionAsync_ListenerDisposed_Throws

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#85371] opened 2023-04-26 01:34 UTC
**Failed in:** runtime-coreclr libraries-jitstress 20230425.1

**Failed tests:**
```
net8.0-linux-Release-arm64-CoreCLR_checked-jitstress1_tiered-(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
    - System.Net.Quic.Tests.QuicListenerTests.AcceptConnectionAsync_ListenerDisposed_Throws

net8.0-linux-Release-arm64-CoreCLR_checked-jitstress1_tiered-(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
    - System.Net.Quic.Tests.QuicListenerTests.AcceptConnectionAsync_ClientConnects_CancelIgnored
    - System.Net.Quic.Tests.QuicListenerTests.Listener_BacklogLimitRefusesConnection_ClientThrows
    - System.Net.Quic.Tests.QuicStreamConformanceTests.Timeout_Roundtrips
    - System.Net.Quic.Tests.QuicStreamConformanceTests.ReadWriteByte_Success
    - System.Net.Quic.Tests.QuicStreamConformanceTests.Flush_ValidOnWriteableStreamWithNoData_Success
    - System.Net.Quic.Tests.QuicStreamConformanceTests.ArgumentValidation_ThrowsExpectedException
    - System.Net.Quic.Tests.QuicStreamTests.TestStreams
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_GracefulShutdown_Success
    - System.Net.Quic.Tests.QuicStreamTests.AbortAfterDispose_ProperlyOpenedStream_Success
    - System.Net.Quic.Tests.QuicStreamTests.GetStreamIdWithoutStartWorks
    - System.Net.Quic.Tests.QuicStreamTests.MultipleReadsAndWrites
    - System.Net.Quic.Tests.QuicStreamTests.WaitForReadsClosedAsync_ConnectionClosed_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_ConnectionClosed_Throws
    - System.Net.Quic.Tests.QuicStreamTests.MultipleConcurrentStreamsOnSingleConnection
    - System.Net.Quic.Tests.QuicStreamTests.AbortAfterDispose_StreamCreationFlushedByDispose_Success
    - System.Net.Quic.Tests.QuicStreamTests.BasicTest
    - System.Net.Quic.Tests.QuicStreamTests.Read_SynchronousCompletion_Success
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_ServerWriteAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.LargeDataSentAndReceived
    - System.Net.Quic.Tests.QuicStreamTests.WriteCanceled_NextWriteThrows
    - System.Net.Quic.Tests.QuicStreamTests.ReadAbortedWithoutReading_WriteThrows
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_ClientReadAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WaitForReadsClosedAsync_GracefulShutdown_Success
    - System.Net.Quic.Tests.QuicStreamTests.WaitForReadsClosedAsync_ClientWriteAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.MultipleStreamsOnSingleConnection
```

**Error message:**
```
 Assert.Throws() Failure
Expected: typeof(System.Security.Authentication.AuthenticationException)
Actual:   typeof(System.Net.Quic.QuicException): The connection timed out from inactivity.
---- System.Net.Quic.QuicException : The connection timed out from inactivity.
```

**Stack trace:**
```
    at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct&amp; data) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 470
   at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT&amp; connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 569
   at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 598
--- End of stack trace from previous location ---
   at System.Net.Quic.ValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ValueTaskSource.cs:line 176
   at System.Net.Quic.QuicConnection.FinishConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 312
   at System.Net.Quic.QuicConnection.ConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 68
   at System.Net.Quic.QuicConnection.ConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 73
   at System.Net.Quic.Tests.QuicListenerTests.&lt;&gt;c__DisplayClass7_0.&lt;&lt;AcceptConnectionAsync_ListenerDisposed_Throws&gt;b__3&gt;d.MoveNext() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicListenerTests.cs:line 162
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct&amp; data) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 470
   at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT&amp; connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 569
   at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 598
--- End of stack trace from previous location ---
   at System.Net.Quic.ValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ValueTaskSource.cs:line 176
   at System.Net.Quic.QuicConnection.FinishConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 312
   at System.Net.Quic.QuicConnection.ConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 68
   at System.Net.Quic.QuicConnection.ConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 73
   at System.Net.Quic.Tests.QuicListenerTests.&lt;&gt;c__DisplayClass7_0.&lt;&lt;AcceptConnectionAsync_ListenerDisposed_Throws&gt;b__3&gt;d.MoveNext() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicListenerTests.cs:line 162
--- End of stack trace from previous location ---
```

**Comment by ManickaP** [comment] 2023-04-26 08:44
Probably fallout from the MsQuic test hack: https://github.com/dotnet/runtime/pull/83687
I don't know if this is a direct result of the change or whether this is just another problem that was masked by MsQuic refusing connection. Anyway, if the test duration is 10s, it's us killing the handshake for timeout. We might count on this within the tests and ignore these errors, we might attempt to raise the 10s timeouts for tests, or we might disable testing on "slow" platforms - probably the least desirable.

**Comment by wfurt** [comment] 2023-04-26 15:45
"slow"+ jitstress -> super-slow probably. At some point we should measure the time difference on normal runs. Also if there is massive failure it can be also environmental.

**Comment by karelz** [comment] 2023-08-14 16:58
Ttiage: JitStress only - not critical for 8.0, moving to 9.0.

**Comment by v-wenyuxu** [comment] 2023-08-16 01:22
**Failed again in:** [runtime-coreclr libraries-jitstressregs 20230814.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=373885&view=ms.vss-test-web.build-test-results-tab&runId=7943880&resultId=168787&paneView=debug)

**Failed tests:**
```
net8.0-linux-Release-arm-CoreCLR_checked-jitstressregs0x10-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - System.Net.Quic.Tests.QuicStreamConformanceTests.ArgumentValidation_ThrowsExpectedException
    - System.Net.Quic.Tests.QuicStreamTests.TestStreams
    - System.Net.Quic.Tests.QuicStreamTests.GetStreamIdWithoutStartWorks
    - System.Net.Quic.Tests.QuicStreamTests.ReadOutstanding_ReadAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.MultipleConcurrentStreamsOnSingleConnection
    - System.Net.Quic.Tests.QuicStreamTests.Read_SynchronousCompletion_Success
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_ServerShutdown_Success
    - System.Net.Quic.Tests.QuicStreamTests.WaitForReadsClosedAsync_GracefulShutdown_Success
    - System.Net.Quic.Tests.QuicStreamTests.WaitForReadsClosedAsync_ClientWriteAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_GracefulShutdown_Success
    - System.Net.Quic.Tests.QuicStreamTests.Read_WriteAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.AbortAfterDispose_ProperlyOpenedStream_Success
    - System.Net.Quic.Tests.QuicStreamTests.MultipleReadsAndWrites
    - System.Net.Quic.Tests.QuicStreamTests.WaitForReadsClosedAsync_ConnectionClosed_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_ConnectionClosed_Throws
    - System.Net.Quic.Tests.QuicStreamTests.AbortAfterDispose_StreamCreationFlushedByDispose_Success
    - System.Net.Quic.Tests.QuicStreamTests.BasicTest
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_ServerWriteAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.LargeDataSentAndReceived
    - System.Net.Quic.Tests.QuicStreamTests.WaitForReadsClosedAsync_ServerReadAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WriteAsync_LocalAbort_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WriteAbortedWithoutWriting_ReadThrows
    - System.Net.Quic.Tests.QuicStreamTests.WriteCanceled_NextWriteThrows
    - System.Net.Quic.Tests.QuicStreamTests.ReadAbortedWithoutReading_WriteThrows
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_ClientReadAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWriteCompletionAsync_ClientReadAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WritePreCanceled_Throws
    - System.Net.Quic.Tests.QuicStreamTests.MultipleStreamsOnSingleConnection
```

**Error message:**
```
System.Net.Quic.QuicException : The connection timed out from inactivity.
```

**Stack trace:**
```
   at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 476
   at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 538
   at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 572
--- End of stack trace from previous location ---
   at System.Net.Quic.QuicConnection.AcceptInboundStreamAsync(CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 416
   at System.Net.Quic.Tests.QuicStreamConformanceTests.<>c__DisplayClass12_0.<<CreateConnectedStreamsAsync>b__1>d.MoveNext() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamConnectedStreamConformanceTests.cs:line 84
--- End of stack trace from previous location ---
   at System.IO.Tests.StreamConformanceTests.WhenAllOrAnyFailed(Task task1, Task task2) in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 564
   at System.Net.Quic.Tests.QuicStreamConformanceTests.CreateConnectedStreamsAsync() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamConnectedStreamConformanceTests.cs:line 80
   at System.Net.Quic.Tests.QuicStreamConformanceTests.CreateConnectedStreamsAsync() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamConnectedStreamConformanceTests.cs:line 137
   at System.IO.Tests.ConnectedStreamConformanceTests.ArgumentValidation_ThrowsExpectedException() in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 1621
--- End of stack trace from previous location ---
```

**Comment by v-wenyuxu** [comment] 2023-09-20 01:17
**Failed again in:** [runtime-coreclr libraries-jitstress 20230919.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=411093&view=ms.vss-test-web.build-test-results-tab&runId=8947652&resultId=168996&paneView=debug)

**Failed tests:**
```
net9.0-linux-Release-arm-CoreCLR_checked-jitstress2-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - System.Net.Quic.Tests.QuicStreamConformanceTests.ArgumentValidation_ThrowsExpectedException
    - System.Net.Quic.Tests.QuicStreamTests.TestStreams
    - System.Net.Quic.Tests.QuicStreamTests.GetStreamIdWithoutStartWorks
    - System.Net.Quic.Tests.QuicStreamTests.ReadOutstanding_ReadAborted_Throws
net9.0-linux-Release-arm-CoreCLR_checked-jitstress2-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - System.Net.Quic.Tests.QuicStreamTests.MultipleConcurrentStreamsOnSingleConnection
net9.0-linux-Release-arm-CoreCLR_checked-jitstress2-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - System.Net.Quic.Tests.QuicStreamTests.Read_SynchronousCompletion_Success
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_ClientReadAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WaitForReadsClosedAsync_GracefulShutdown_Success
net9.0-linux-Release-arm-CoreCLR_checked-jitstress2-(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_GracefulShutdown_Success
    - System.Net.Quic.Tests.QuicStreamTests.Read_WriteAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.AbortAfterDispose_ProperlyOpenedStream_Success
    - System.Net.Quic.Tests.QuicStreamTests.MultipleReadsAndWrites
    - System.Net.Quic.Tests.QuicStreamTests.WaitForReadsClosedAsync_ConnectionClosed_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_ConnectionClosed_Throws
    - System.Net.Quic.Tests.QuicStreamTests.AbortAfterDispose_StreamCreationFlushedByDispose_Success
    - System.Net.Quic.Tests.QuicStreamTests.BasicTest
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_ServerShutdown_Success
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_ServerWriteAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.LargeDataSentAndReceived
    - System.Net.Quic.Tests.QuicStreamTests.WaitForReadsClosedAsync_ServerReadAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WriteAsync_LocalAbort_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WriteAbortedWithoutWriting_ReadThrows
    - System.Net.Quic.Tests.QuicStreamTests.WriteCanceled_NextWriteThrows
    - System.Net.Quic.Tests.QuicStreamTests.ReadAbortedWithoutReading_WriteThrows
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWriteCompletionAsync_ClientReadAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WritePreCanceled_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WaitForReadsClosedAsync_ClientWriteAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.MultipleStreamsOnSingleConnection
```

**Error message:**
```
System.Net.Quic.QuicException : The connection timed out from inactivity.
```

**Stack trace:**
```
   at System.Net.Quic.ResettableValueTaskSource.TryComplete(Exception exception, Boolean final) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ResettableValueTaskSource.cs:line 180
   at System.Net.Quic.QuicStream.HandleEventShutdownComplete(_SHUTDOWN_COMPLETE_e__Struct& data) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs:line 614
   at System.Net.Quic.QuicStream.HandleStreamEvent(QUIC_STREAM_EVENT& streamEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs:line 636
   at System.Net.Quic.QuicStream.NativeCallback(QUIC_HANDLE* stream, Void* context, QUIC_STREAM_EVENT* streamEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs:line 665
--- End of stack trace from previous location ---
   at System.Net.Quic.ResettableValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ResettableValueTaskSource.cs:line 256
   at System.Net.Quic.QuicStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs:line 307
   at System.Net.Quic.Tests.QuicStreamConformanceTests.<>c__DisplayClass12_0.<<CreateConnectedStreamsAsync>b__1>d.MoveNext() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamConnectedStreamConformanceTests.cs:line 85
--- End of stack trace from previous location ---
   at System.IO.Tests.StreamConformanceTests.WhenAllOrAnyFailed(Task task1, Task task2) in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 554
   at System.Net.Quic.Tests.QuicStreamConformanceTests.CreateConnectedStreamsAsync() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamConnectedStreamConformanceTests.cs:line 80
   at System.Net.Quic.Tests.QuicStreamConformanceTests.CreateConnectedStreamsAsync() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamConnectedStreamConformanceTests.cs:line 137
   at System.IO.Tests.ConnectedStreamConformanceTests.ArgumentValidation_ThrowsExpectedException() in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 1617
--- End of stack trace from previous location ---
```

**Comment by v-wenyuxu** [comment] 2024-03-28 01:35
**Failed in:** [runtime-coreclr libraries-jitstress 20240327.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=620388&view=ms.vss-test-web.build-test-results-tab&runId=15176320&resultId=163808&paneView=debug)

**Failed tests:**
```
net9.0-linux-Release-arm-disabler2r-(Ubuntu.1804.Arm32.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - System.Net.Quic.Tests.QuicStreamConformanceTests.Timeout_Roundtrips
    - System.Net.Quic.Tests.QuicStreamConformanceTests.ReadWriteAsync_PrecanceledOperations_ThrowsCancellationException
    - System.Net.Quic.Tests.QuicStreamConformanceTests.ReadWriteByte_Success
    - System.Net.Quic.Tests.QuicStreamConformanceTests.Flush_ValidOnWriteableStreamWithNoData_Success
    - System.Net.Quic.Tests.QuicStreamConformanceTests.ReadTimeout_Expires_Throws
    - System.Net.Quic.Tests.QuicStreamConformanceTests.ConcurrentBidirectionalReadsWrites_Success
    - System.Net.Quic.Tests.QuicStreamConformanceTests.Flush_ValidOnReadableStream_Success
    - System.Net.Quic.Tests.QuicStreamConformanceTests.Disposed_ThrowsObjectDisposedException
    - System.Net.Quic.Tests.QuicStreamConformanceTests.ReadAsync_DuringReadAsync_ThrowsIfUnsupported
    - System.Net.Quic.Tests.QuicStreamConformanceTests.ArgumentValidation_ThrowsExpectedException
    - System.Net.Quic.Tests.QuicStreamTests.TestStreams
    - System.Net.Quic.Tests.QuicStreamTests.GetStreamIdWithoutStartWorks
    - System.Net.Quic.Tests.QuicStreamTests.ReadOutstanding_ReadAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.MultipleReadsAndWrites
    - System.Net.Quic.Tests.QuicStreamTests.WaitForReadsClosedAsync_ConnectionClosed_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_ConnectionClosed_Throws
    - System.Net.Quic.Tests.QuicStreamTests.MultipleConcurrentStreamsOnSingleConnection
    - System.Net.Quic.Tests.QuicStreamTests.AbortAfterDispose_StreamCreationFlushedByDispose_Success
    - System.Net.Quic.Tests.QuicStreamTests.BasicTest
    - System.Net.Quic.Tests.QuicStreamTests.Read_SynchronousCompletion_Success
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_ServerShutdown_Success
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_ServerWriteAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.LargeDataSentAndReceived
    - System.Net.Quic.Tests.QuicStreamTests.WaitForReadsClosedAsync_ServerReadAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WriteAsync_LocalAbort_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WriteAbortedWithoutWriting_ReadThrows
    - System.Net.Quic.Tests.QuicStreamTests.WriteCanceled_NextWriteThrows
    - System.Net.Quic.Tests.QuicStreamTests.ReadAbortedWithoutReading_WriteThrows
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_ClientReadAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWriteCompletionAsync_ClientReadAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WritePreCanceled_Throws
    - System.Net.Quic.Tests.QuicStreamTests.WaitForReadsClosedAsync_GracefulShutdown_Success
    - System.Net.Quic.Tests.QuicStreamTests.WaitForReadsClosedAsync_ClientWriteAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.MultipleStreamsOnSingleConnection
    - System.Net.Quic.Tests.QuicStreamTests.Read_WriteAborted_Throws
    - System.Net.Quic.Tests.QuicStreamTests.AbortAfterDispose_ProperlyOpenedStream_Success
    - System.Net.Quic.Tests.QuicStreamTests.WaitForWritesClosedAsync_GracefulShutdown_Success
```

**Error message:**
```
 System.Net.Quic.QuicException : The connection timed out from inactivity.
```

**Stack trace:**
```
   at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 526
   at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 594
   at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 628
--- End of stack trace from previous location ---
   at System.Net.Quic.QuicConnection.AcceptInboundStreamAsync(CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 462
   at System.Net.Quic.Tests.QuicStreamConformanceTests.<>c__DisplayClass12_0.<<CreateConnectedStreamsAsync>b__1>d.MoveNext() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamConnectedStreamConformanceTests.cs:line 85
--- End of stack trace from previous location ---
   at System.IO.Tests.StreamConformanceTests.WhenAllOrAnyFailed(Task task1, Task task2) in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 560
   at System.Net.Quic.Tests.QuicStreamConformanceTests.CreateConnectedStreamsAsync() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamConnectedStreamConformanceTests.cs:line 81
   at System.Net.Quic.Tests.QuicStreamConformanceTests.CreateConnectedStreamsAsync() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamConnectedStreamConformanceTests.cs:line 138
   at System.IO.Tests.ConnectedStreamConformanceTests.Timeout_Roundtrips() in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 2495
--- End of stack trace from previous location ---
```

**Comment by liveans** [comment] 2024-06-05 10:09
I think we can close this as duplicate of #91757 
/cc @ManickaP

**Comment by ManickaP** [comment] 2024-06-05 11:38
Dupe of #91757

**Closed by ManickaP** 2024-06-05 11:38 UTC
Labels: arch-arm64, os-linux, JitStress, area-System.Net.Quic

**Comment by liveans** [comment] 2024-06-05 11:47
Duplicate of #91757
