### ISSUE TITLE
ResourceManager.GetResourceSet returns different results if GetString is used

### ISSUE THREAD

**Issue by hudecekd** [dotnet/runtime#58855] opened 2021-09-09 07:28 UTC
### Description
I have resx files. I am trying to get all available resources for application by iterating through all cultures and trying to get ResourceSet for each culture.
Problem is that for cultures "en", "en-US" `GetResourceSet` behaves differently if `GetString` is or is not called.

If `GetString` IS NOT called before `GetResourceSet` then it returns null.
If `GetString` IS called before `GetResourceSet` then it returns resource set.

I would expect that GetResourceSet returns same value even if GetString is/is not called.

### Configuration

I tested it on NET 5.
Windows 10
x64

### Other information

[ConsoleApp42.zip](https://github.com/dotnet/runtime/files/7134413/ConsoleApp42.zip)

**Comment by joperezr** [comment] 2021-09-09 17:50
Seems like this is an undocumented behavior by briefly looking at https://docs.microsoft.com/en-us/dotnet/api/system.resources.resourcemanager?view=net-5.0 . I'm curious if this behavior also repros with .NET Framework. In any case, given it is not documented that you need to call GetString before the other calls work correctly, I would either document or fix the behavior. @tarekgh do you have any opinion here?

**Comment by tarekgh** [comment] 2021-09-21 17:45
@hudecekd this is by design. You are using `ResourceManager` object which can have some state depending on the operation you have performed using it. When calling `ResourceManager.GetString`, the resource lookup will try to find resources for the UI culture (which I assume it is `en-US` in your case). The resource lookup will not find resources and will fall back to the parent chain (`en` then Invariant) which will find the neutral resources. Then will cache the found resources to the UI languages (`en` and `en-US`) used in the lookup. Any future resource lookup will not repeat this process and instead will just use the cached result. 

For your case, to get consistent results either, you create a new ResourceManager object to do the ResourceSet lookup to ensure no cached state there. Or you can just call `resourceManager.ReleaseAllResources()` to clean the old state. 

Would be good to tag your embedded resources with the culture you want to associate with. e.g. us the following attribute to set the default neutral resource language:

```C#
[assembly:NeutralResourcesLanguageAttribute("en")]
```

Also, you may just try find the ResourceSet with enabling the fallback to get the same behavior as GetString. 

```
    x = resourceManager.GetResourceSet(new CultureInfo("en"), true, true); // passing true for last parameter
```

**Comment by hudecekd** [comment] 2021-09-22 07:45
Hi @tarekgh ,
so it means that I cannot actually get "all available resources" by iterating throug all cultures and checking whether resource set is available as I tried in `GetAvailableCultures` in example, am I correct? Since it depends on current thread culture, whether I have used `GetString` and other things possibly?

**Comment by tarekgh** [comment] 2021-09-22 16:37
Hi @hudecekd

> so it means that I cannot actually get "all available resources" by iterating throug all cultures and checking whether resource set is available as I tried in GetAvailableCultures in example, am I correct? Since it depends on current thread culture, whether I have used GetString and other things possibly?

No, you have the option to call `resourceManager.ReleaseAllResources()` before doing the enumeration. That will remove any cached data and behave as if GetString not called at all.

**Comment by joperezr** [comment] 2021-09-28 18:16
Thanks for the reply @tarekgh. Given this is by design, and that the question has been answered, I'll go ahead and close this issue for now. @hudecekd feel free to reopen if you have any follow up questions/comments.

**Closed by joperezr** 2021-09-28 18:16 UTC
Labels: area-System.Resources, needs further triage

**Comment by hudecekd** [comment] 2021-09-29 08:08
Thanks for help. I will try to use recommended approach.
