### ISSUE TITLE
HttpClientFactory open many connections

### ISSUE THREAD

**Issue by gsGabriel** [dotnet/runtime#43764] opened 2020-10-23 13:53 UTC
I'm using .net core 2.2 and microsoft/dotnet:2.2-aspnetcore-runtime-alpine docker image and used AddHttpClient to create a typed HttpClient

The problem is several open socket connections, even using the factory
I replicated the problem in an application for testing in the following repository: [https://github.com/gsGabriel/httpclient-factory/](url)

the connections listed
![image](https://user-images.githubusercontent.com/8701768/96885818-57a4e000-1459-11eb-9efe-05f556fda3d2.png)

Could someone tell me what is wrong with my implementation? I can't currently upgrade to .net core 3.0

_Originally posted by @gsGabriel in https://github.com/dotnet/runtime/issues/28842#issuecomment-714532985_

**Comment by ClementeGao** [comment] 2020-10-23 14:12
watching

**Comment by MCCshreyas** [comment] 2020-10-25 06:33
I have opened PR for this, please let me know the outcome!

**Comment by gsGabriel** [comment] 2020-10-26 13:06
> I have opened PR for this, please let me know the outcome!

@MCCshreyas Thank You

The reason I used the code snippet below

```csharp
            for (int i = 0; i < 100; i++)
            {
                using (var scope = service.CreateScope())
                {
                    var gitHubService = scope.ServiceProvider.GetService<IGitHubService>();
                    tasks.Add(gitHubService.GetAspNetDocsIssues());
                }
            }
```
it is to simulate the life-cycle of a request, at each request we take an instance of the injection container, so the use of the service provider as it is an endpoint to simulate the problem.

Maybe it's not the best way to test, but I simulate the error only when many requests are made at the endpoint, if the controller has a typed http client, it generates many open socket connections

so I think your PR didn't solve the problem...

**Comment by MCCshreyas** [comment] 2020-10-26 13:14
The thing is like all Tasks are getting executed asynchronously at the same time, so everyone started creating socket at very first time, because it's not available at very first time, because of which you get this many sockets open at same time.

**Comment by gsGabriel** [comment] 2020-10-26 14:09
> The thing is like all Tasks are getting executed asynchronously at the same time, so everyone started creating socket at very first time, because it's not available at very first time, because of which you get this many sockets open at same time.

Okay, you're right ...

but in an application that has a high number of requests per second, wouldn't that be a problem? I believe that the factory should do the control even in a simultaneous scenario

**Comment by MCCshreyas** [comment] 2020-10-27 04:13
> > The thing is like all Tasks are getting executed asynchronously at the same time, so everyone started creating socket at very first time, because it's not available at very first time, because of which you get this many sockets open at same time.
> 
> Okay, you're right ...
> 
> but in an application that has a high number of requests per second, wouldn't that be a problem? I believe that the factory should do the control even in a simultaneous scenario

How come factory even know that there is an instance if everything started at once asynchronously! And also the code that you have written its not a good practice as well, you should directly use your injected service because you have already add it to DI in startup rather than service provider which is OK, but not needed in this example, as the required service is already present in DI.

**Comment by CarnaViire** [comment] 2020-10-27 11:39
@gsGabriel thanks for reporting this! I confirm that I am able to reproduce the issue.

However, it seems that the problem is not on the HttpClientFactory's side. You may observe the same behavior even if you use a single instance of a plain HttpClient.

```c#
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;

namespace httpclienthandler_many_connections
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var client = new HttpClient();
            client.BaseAddress = new Uri("https://api.github.com/");
            client.DefaultRequestHeaders.Add("Accept", "application/vnd.github.v3+json");
            client.DefaultRequestHeaders.Add("User-Agent", "httpclienthandler_many_connections");

            var tasks = new List<Task>();
            for (int i = 0; i < 10; i++)
            {
                tasks.Add(GetZenAsync(client));
            }
            await Task.WhenAll(tasks.ToArray());

            Console.ReadKey();
        }

        private static async Task<string> GetZenAsync(HttpClient httpClient)
        {
            var response = await httpClient.GetAsync("/zen");
            var result = await response.Content.ReadAsStringAsync();
            Console.WriteLine(result);
            return result;
        }
    }
}
```

![image](https://user-images.githubusercontent.com/3184057/97295869-c910d400-1847-11eb-9305-b67bac5da1a3.png)

I wasn't able to find an open issue for that. We will investigate this further.
cc @karelz @dotnet/ncl

**Comment by gsGabriel** [comment] 2020-10-27 13:07
@CarnaViire but this is a known issue of HttpClient, the HttpClientFactory documentation mentioned this.

Shouldn't HttpClientFactory prevent this?

**Comment by CarnaViire** [comment] 2020-10-27 13:54
@gsGabriel this is a known issue when using *multiple* HttpClients, because its default constructor will create a new HttpMessageHandler instance. What HttpClientFactory does is, it ensures that HttpMessageHandlers are pooled and reused between HttpClients. But a single HttpClient would have a single HttpMessageHandler inside, which in theory should also prevent socket exhaustion.

If you are interested, you may see the guidelines for using HttpClient instead of HttpClientFactory here https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-3.1#alternatives-to-ihttpclientfactory

**Comment by gsGabriel** [comment] 2020-10-27 14:28
Ah, ok, I understand, thank you very much @CarnaViire :D

**Comment by CarnaViire** [comment] 2020-10-27 21:13
So what I discovered is:

1) Having one `HttpMessageHandler` does not guarantee by default that only one connection per server will be used. In order to guarantee it, you have to set `MaxConnectionsPerServer` property either in [HttpClientHandler](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.maxconnectionsperserver?view=netcore-3.1) or in [SocketsHttpHandler](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.maxconnectionsperserver?view=netcore-3.1)

2) Docs for `HttpClientFactory` also didn't seem to mention using one connection. What I see there in the docs it that it "avoids resource exhaustion problems by pooling HttpMessageHandler instances", so the behavior is compliant with the docs. If there are places that I missed that said about using one connection, please point me to them.

@gsGabriel Did you just wonder why there are several connections open or are you truly experiencing problems with socket exhaustion?

**Comment by gsGabriel** [comment] 2020-10-28 00:19
@CarnaViire 

Yes, I had the error "too many open files in system" in my linux containers when my application had a high requests per second. In my investigation the reason was the high number of open sockets connections from my http clients, we changed the ulimit of the containers to the maximum value ... solved the problem, but it generated discomfort with the infrastructure team since this does not happen in applications with the same number of requests per second from other technologies.

In my interpretation of the text in relation to the `HttpClient` life cycle described in [httpclient-lifetimes](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#httpclient-lifetimes) it was understood that it would be reused whenever `HttpMessageHandler` was available, so I believed that it would not have so many open connections because it would always be reusing.

I will follow your suggestion and use the `MaxConnectionsPerServer`...

**Comment by CarnaViire** [comment] 2020-10-28 13:00
Thanks @gsGabriel and sorry the docs caused misinterpretation!
I am closing the issue then.

**Comment by davidfowl** [comment] 2020-10-28 13:13
You shouldn't run out of connections using the IHttpClientFactory normally. I'd like to better understand why you ended up in this situation.

**Comment by CarnaViire** [comment] 2020-10-29 11:36
@gsGabriel could you please check and share the following for your application:

1) Whether setting MaxConnectionsPerServer helped with the problem;
2) If you don't set MaxConnectionsPerServer but use a **single static instance** of HttpClient for the whole application, whether the problem persists.

**Comment by gsGabriel** [comment] 2020-10-29 14:53
@CarnaViire 

I made several attempts with different implementations. I believe there is a problem with the asynchronous context, perhaps that context requires multiple connections to be opened for task management. Follow my attempts

1. I tried to set MaxConnectionsPerServer, doesn`t work
``` csharp
            services.AddHttpClient<IGitHubService, GitHubService>(client =>
            {
                client.BaseAddress = new Uri("https://api.github.com/");
            })
            .ConfigureHttpMessageHandlerBuilder((c) =>
                new HttpClientHandler
                {
                    MaxConnectionsPerServer = 1
                }
            );
```
and
``` csharp
            services.AddHttpClient<IGitHubService, GitHubService>(client =>
            {
                client.BaseAddress = new Uri("https://api.github.com/");
            })
            .ConfigureHttpMessageHandlerBuilder((c) =>
                new SocketsHttpHandler 
                {
                    MaxConnectionsPerServer = 1
                }
            );
```
1.1 work without set MaxConnectionPerServer if i await operation by operation


2. I tried to use a static class of HttpClient, doesn`t work. 
       2.1 work if i await operation by operation


3. I tried to use singleton, doesn`t work
       3.1 work if i await operation by operation

**The mention for it to work is if not many connections have been opened**

**Comment by CarnaViire** [comment] 2020-10-29 15:12
@gsGabriel if you look closely you may notice that when you do 
```c#
            .ConfigureHttpMessageHandlerBuilder((c) =>
                new SocketsHttpHandler 
                {
                    MaxConnectionsPerServer = 1
                }
            );
```
you are not actually changing anything -- the ConfigureHttpMessageHandlerBuilder method accepts an action on a builder. To change the handler, you need to use ConfigurePrimaryHttpMessageHandler
```c#
services.AddHttpClient<...>(...)
    .ConfigurePrimaryHttpMessageHandler(sp => new SocketsHttpHandler(){ MaxConnectionsPerServer = 1 });
```


Also, did I understand it right, that you confirm that if you use single static HttpClient, you still get socket exhaustion?

**Comment by gsGabriel** [comment] 2020-10-29 15:36
@CarnaViire 

Now, following your suggestion, set MaxConnectionsPerServer  work`s...
About static HttpClient, yes, i still get socket exhaustion.

**Comment by CarnaViire** [comment] 2020-10-29 15:50
Glad to hear MaxConnectionsPerServer works

**Closed by CarnaViire** 2020-10-29 15:50 UTC
Labels: area-System.Net.Http, untriaged

**Comment by gsGabriel** [comment] 2020-10-29 16:04
@CarnaViire Wouldn't it be interesting to add a default to avoid failures?

**Comment by CarnaViire** [comment] 2020-10-29 22:21
@gsGabriel What do you think the default should be, so that it satisfies ALL customers? Is 100 a good value, 1K, 10K, 100K, INF? and if yes, why?

**Comment by gsGabriel** [comment] 2020-10-29 22:42
@CarnaViire I plan on preventing more connections than the server allows. Linux has a default limit value for simultaneous connections, it opens a file for each connection and if this value is exceeded, it starts to generate errors in the following connections. The default value would be the limit imposed by the server, which is what I believe would serve all customers.

**Comment by CarnaViire** [comment] 2020-10-30 18:06
By server you mean the server you make a request to, or the machine you are running your application on?
