### ISSUE TITLE
[QUIC] Finalize QUIC stream abort model

### ISSUE THREAD

**Issue by scalablecory** [dotnet/runtime#32075] opened 2020-02-10 23:46 UTC
QUIC supports aborting the read or write side of a stream independently from the other side of the stream.

We should determine how to allow a user to do an "abortive dispose" such that all pending I/Os in both directions are aborted.

https://github.com/dotnet/runtime/blob/65587ba7b402411b62ce877ee044aef2c2c71dfd/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicStream.cs#L313-L315

https://github.com/dotnet/runtime/blob/65587ba7b402411b62ce877ee044aef2c2c71dfd/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicStream.cs#L364-L381

**Comment by geoffkizer** [comment] 2020-11-17 07:36
Isn't this captured already by #756? What's not captured there?

**Comment by ManickaP** [comment] 2021-04-15 13:36
Should we close this as a dupe of #756?

**Comment by CarnaViire** [comment] 2021-04-15 15:15
I believe we wanted to split #756 into several issues instead https://github.com/dotnet/runtime/issues/756#issuecomment-816132960

**Comment by scalablecory** [comment] 2021-04-22 18:19
Triage: we think the abort APIs will look like this:

```c#
class QuicStream
{
    // abortive -- causing any unsent data to be discarded.
    // one direction can be aborted while leaving the other direction open.
    // should cause any outstanding ops to throw StreamAbortedException.
    public void Abort(long errorCode, QuicAbortDirection direction = QuicAbortDirection.Both);
}

[Flags]
enum QuicAbortDirection
{
   Read = 1,
   Write = 2,
   Both = 3
}
```

**Comment by ManickaP** [comment] 2021-07-15 17:29
Coverd by #756

**Closed by ManickaP** 2021-07-15 17:29 UTC
Labels: area-System.Net.Quic, enhancement
