### ISSUE TITLE
Hang issue found when using TaskCompletionSource in PowerShell script with System.Windows.Forms.Form loaded.

### ISSUE THREAD

**Issue by EmmaZhu** [dotnet/runtime#57104] opened 2021-08-04 08:58 UTC
Hi,

We found a hang issue in our production, and made a simple repro here: [https://github.com/EmmaZhu/HangWithTaskRepro](url).

To repro the issue:
1. Build project `TaskHangTest` in the repro repository
2. Update following line in script `HangReproScript.ps1` in the repro repository to add `TaskHangTest`'s dll path to the script:
  `Add-Type -Path ".\TaskHangTest\bin\Debug\netstandard2.0\TaskHangTest.dll"`
3. Run the script.

It will hang at 
```
$t = [TaskHangTest.TaskTest]::RunTask();
$t.Wait();
```

If you comment out following lines in the script, it won't hang anymore: 
```
[void][System.Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms")

$UserAdminForm = New-Object System.Windows.Forms.Form
```

Could you help to take a look:

- Whether there's anything we can do in the C# project to avoid this kind of issue.  The hang happens when invoking `TaskCompletionSource.SetResult` in separate thread. I think it's a typical scenario to call `TaskCompletionSource.SetResult` in different thread.

Thanks
Emma

**Comment by svick** [comment] 2021-08-10 09:48
The problem is that your code is creating a deadlock. Specifically:

1. Creating a `Form` installs a WinForms `SynchronizationContext` on the "main" thread ("Pipeline Execution Thread").
2. Executing `await source.Task;` on this thread means that `RunTaskInternal` can only complete on the main thread.
3. Executing `$t.Wait();` blocks the main thread and so it cannot continue executing `RunTaskInternal`, resulting in a deadlock.

To fix this specific issue, either change the line from `await source.Task;` to `await source.Task.ConfigureAwait(false);`, or make the method non-async and then `return source.Task;`.

**Comment by mangod9** [comment] 2021-08-16 16:56
assume the fix needs to be in winforms? Does it need to be transferred over?

**Comment by stephentoub** [comment] 2021-08-16 17:17
> assume the fix needs to be in winforms? Does it need to be transferred over?

No, there's no product bug here, at least not with the specified repro.  The issue is in the repro.

**Closed by stephentoub** 2021-08-16 17:17 UTC
Labels: area-System.Threading, untriaged
