### ISSUE TITLE
Service Collection does not allow Type Generic Classes with fewer open Generic Types to be used, even if all Types missing Open Generic Types are provided as Compile Constants

### ISSUE THREAD

**Issue by Link9001** [dotnet/runtime#87746] opened 2023-06-18 15:18 UTC
### Description

I'm currently writing an Assembly Scanner which registers some Open Generic Types in the Service Collection. After some testing of my Scanner, I ran into an exception which for me doesn't make much sense.
`System.ArgumentException: Cannot instantiate implementation type 'Test`1[TTest]' for service type 'ITest`2[TTest,System.Exception]'.`
I have provided all necessary open generic Arguments and provided the missing Open Generic Argument as a Compile Constant Type Parameter. I also have tried to find in the Documentation a section that describes that this is not possible, which I didn't find. Therefor I assumed that this should be possible but currently isn't.

### Reproduction Steps

Paste the following Code into a .Net7.0 project and install the "Microsoft.Extensions.DependencyInjection" Package with the Version "7.0". Just let it run and you will get the above-mentioned exception.

`Program.cs`
```
using Microsoft.Extensions.DependencyInjection;

var serviceColl = new ServiceCollection();

serviceColl.AddSingleton(typeof(Test<>).GetInterface(typeof(ITest<,>).Name)!, typeof(Test<>));

serviceColl.BuildServiceProvider();
```
`Test.cs`
```
class Test<TTest> : ITest<TTest>
{
}
```
`ITest.cs`
```
interface ITest<T> : ITest<T, Exception>
{
}

interface ITest<T, T2>
{
}
```

### Expected behavior

I would expect the service collection to be able to register a type mapping like that and the provider to be able to resolve such mapping.

### Actual behavior

It throws an exception which also doesn't make much sense.
StackTrace:
```
Unhandled exception. System.ArgumentException: Cannot instantiate implementation type 'Test`1[TInt]' for service type 'ITest`2[TInt,System.Exception]'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.Populate()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory..ctor(ICollection`1 descriptors)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services)
   at Program.<Main>$(String[] args) in C:\Users\Link\source\repos\TestApp\TestApp\Program.cs:line 7

```

**Comment by davidfowl** [comment] 2023-06-19 04:24
The DI container doesn't support partially open generic types. There's an explicit check for matching generic artity of the service type and the implementation type. It might be possible to support this, but it hasn't come up in the past.

**Comment by steveharter** [comment] 2023-06-28 14:10
Closing as by design

**Closed by steveharter** 2023-06-28 14:10 UTC
Labels: untriaged, area-Extensions-DependencyInjection
