### ISSUE TITLE
Bug in IntersectBy, ExceptBy, ... :only gives the first element of the source collection

### ISSUE THREAD

**Issue by 3sRykaert** [dotnet/runtime#107338] opened 2024-09-04 07:32 UTC
### Description

Linq methods IntersectBy, ExceptBy (probably other also) only gives the first element of the source collection that satisfices the condition.

### Reproduction Steps

```
    public void SomeRandomMethod()
    {
        var source = new[]
        {
            ("one", 1, "a"),
            ("one", 1, "b"),
            ("two", 2, "a"),
            ("two", 2, "b")
        };
        var filter = new[] { 1 };

        var i = source
            .IntersectBy(filter, x => x.Item2)
            .ToList();
        var e = source
            .ExceptBy(filter, x => x.Item2)
            .ToList();
    }
```

### Expected behavior

expected i to be:
```
("one", 1, "a"),
("one", 1, "b")
```
expected e to be:
```
("two", 2, "a"),
("two", 2, "b")
```

### Actual behavior

i is:
`("one", 1, "a")`
e is:
`("two", 2, "a")`

### Known Workarounds

This gives the correct result:
```
        var ii = source
            .Where(x => filter.Contains(x.Item2))
            .ToList();

        var ee = source
            .Where(x => !filter.Contains(x.Item2))
            .ToList();
```

### Configuration

Same behaviour in .net 6, 7, 8

**Comment by huoyaoyuan** [comment] 2024-09-04 08:28
Duplicate of #75066 and #102112 .

This is by design. Intersect/Except are set operators, they use set semantics where items with the same key are considered identical and not duplicated.

**Closed** 2024-09-04 16:38 UTC
Labels: area-System.Linq
