### ISSUE TITLE
dotnet --list-sdks and --info don't show all versions (dotnet version 6.0.100 arm64)

### ISSUE THREAD

**Issue by alfnielsen** [dotnet/runtime#61400] opened 2021-11-10 07:38 UTC
### Description

I installed the new arm64 version.
It had some problem with running "dotnet" (something pointed at version 5 libs),
so I uninstalled all version, then installed version 6.0.100  (arm64)

Then I installed version 5 again, but now "dotnet --list-runtimes" dont show version 5,
but I can see it with the "dotnet-core-uninstall list"

-----
CONSOLE OUTPUT:

### **% ./dotnet-core-uninstall list**

This tool cannot uninstall versions of the runtime or SDK that are installed using zip/scripts. The versions that can be uninstalled with this tool are:

.NET Core SDKs:
  6.0.100  (arm64)  [Used by Visual Studio for Mac. Specify individually or use —-force to remove]
  5.0.403  (x64)                                                                                  

.NET Core Runtimes:
  6.0.0  (arm64)  [Used by Visual Studio for Mac or SDKs. Specify individually or use —-force to remove]
  6.0.0  (x64)                                        
                                                  
### **% dotnet --list-sdks**
6.0.100 [/usr/local/share/dotnet/sdk]

### % dotnet --info        
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.0
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  6.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

------
When I look into the /usr/local/share/dotnet folder,
its clear that the dotnet 5 is placed under a x64 folder,
And when I run "./dotnet --info" with in this folder, it show only version 5.

So there seems to be some problems with version 6 Arm64 and x64 version running together ?

And version 5 are not in any of the other folder (like the sdk-manifest folder)

(So this could also be a problem with the installer ??)

### Reproduction Steps

On a Mac Air M1:
Uninstall all dotnet version using the "dotnet-uninstall" then go into "/usr/local/share/"
and remove the "dotnet" folder (total removal)

Then install dotnet MacOS Arm64 with Installers from https://dotnet.microsoft.com/download/dotnet/6.0
Then install dotnet MacOs x64 with Installers from https://dotnet.microsoft.com/download/dotnet/5.0

Restart (or logout and ind again with your user)

Open Terminal and run: dotnet --list-sdks

### Expected behavior

Show both version versions:

6.0.100 [/usr/local/share/dotnet/sdk]
5.0.403 [/usr/local/share/dotnet/sdk]

### Actual behavior

It only show:

6.0.100 [/usr/local/share/dotnet/sdk]

### Regression?

yes

### Known Workarounds

you can see the list with "dotnet-uninstall list"

### Configuration

Dotnet versions:
  6.0.100  (arm64) 
  5.0.403  (x64) 

On a Mac Air  M1 (Arm64)

**Comment by alfnielsen** [comment] 2021-11-10 07:38
Image of the folder structure in /usr/local/share/dotnet folder:

<img width="265" alt="Screenshot 2021-11-10 at 08 37 11" src="https://user-images.githubusercontent.com/1725755/141070123-22c56a24-40d3-4aac-948f-0eb28446cd69.png">

**Comment by vitek-karas** [comment] 2021-11-10 11:59
This is a duplicate of https://github.com/dotnet/runtime/issues/51101.
Unfortunately this is currently expected behavior, we simply didn't have enough time in 6.0 to fix this.

The larger multi-arch support tracking issue is here:

**Closed by vitek-karas** 2021-11-10 11:59 UTC
Labels: area-Host, untriaged
