### ISSUE TITLE
[TO VALIDATE WITH RC1] - [net7.0][mono][iOS] AOT fails for CommunityToolkit.WinUI.UI.dll 

### ISSUE THREAD

**Issue by jbtdevgit** [dotnet/runtime#91444] opened 2023-09-01 03:00 UTC
### Description

AOT compilation fails when running for assembly `CommunityToolkit.WinUI.UI.dll` for net7-ios
Packages used : 
- https://www.nuget.org/packages/Uno.CommunityToolkit.WinUI.UI.Controls/
- https://www.nuget.org/packages/Uno.CommunityToolkit.WinUI.UI.Behaviors
```
<PackageVersion Include="Uno.CommunityToolkit.WinUI.UI.Behaviors" Version="7.1.100" />
<PackageVersion Include="Uno.CommunityToolkit.WinUI.UI.Controls" Version="7.1.100" />
```

Running the command dotnet publish -f net7.0-ios -c Release
gives the following error:
`error : Failed to AOT compile CommunityToolkit.WinUI.UI.dll, the AOT compiler exited with code 134`

I think this is somewhat similar to the issue https://github.com/dotnet/runtime/issues/90032 but i've tried the workaround in the issue and it did not worked.

Upgrading to .NET8.0 preview 7 did not work as well.
Below are my workloads 
![image](https://github.com/dotnet/runtime/assets/44351076/7bbc954b-1fcd-46cb-a247-e81a4396f6be)

### Reproduction Steps

Pull down the sample repo

Update `.csproj` and `info.plist` with your apple profiles 
https://github.com/jbtdevgit/UnoApp1_Test
Run dotnet publish -f net7.0-ios -c Release

### Expected behavior

Build Succeeds

### Actual behavior

`error : Failed to AOT compile CommunityToolkit.WinUI.UI.dll, the AOT compiler exited with code 134`

**Comment by ivanpovazan** [comment] 2023-09-04 15:45
I have confirmed locally that this has been fixed via: https://github.com/dotnet/runtime/commit/ecb3b2003c624ae1f116915e9f0f0b11ae264094 and will become available in .NET8 RC1 release.

@jbtdevgit I will keep the issue open until we confirm that your issue has been resolved when the official .NET8 RC1 release becomes publicly available.

**Comment by ivanpovazan** [comment] 2023-09-20 15:25
@jbtdevgit 
Since .NET8 RC1 became publicly available at: https://dotnet.microsoft.com/en-us/download/dotnet/8.0 could you try it out to see if it resolves your problem - so we can close this issue?

**Comment by jbtdevgit** [comment] 2023-09-28 02:33
> @jbtdevgit Since .NET8 RC1 became publicly available at: https://dotnet.microsoft.com/en-us/download/dotnet/8.0 could you try it out to see if it resolves your problem - so we can close this issue?

Hi, I do not think I will be able to try this, we've opted out working with UNO and would not want to upgrade our current environment to .NET8 RC1 since we do not need it yet. Can this be verified by anyone in the UNO platform team?

**Comment by SamMonoRT** [comment] 2023-09-28 17:40
Closing this based on local testing. Please re-open if you still hit it.

**Closed by SamMonoRT** 2023-09-28 17:40 UTC
Labels: area-Codegen-AOT-mono, needs-further-triage
