### ISSUE TITLE
Proposed API: `RemoveAll(int startIndex, Predicate<T> match)`

### ISSUE THREAD

**Issue by xtqqczze** [dotnet/runtime#54797] opened 2021-06-27 20:34 UTC
## Background and Motivation

Prototype: d9640948197

## Proposed API

```diff
namespace System.Collections.Generic
{
+    public int List<T>.RemoveAll(Predicate<T> match) => RemoveAll(0, match);  
-    public int List<T>.RemoveAll(Predicate<T> match) {
+    public int List<T>.RemoveAll(int startIndex, Predicate<T> match) {
     }
```

We already have the following APIs:
* `FindIndex(int startIndex, Predicate<T> match)`
* `FindLastIndex(int startIndex, Predicate<T> match)`

## Usage Examples

``` C#
var list = new List<int> { 0, 1, 2, 3, 4 };
list.RemoveAll(startIndex: 1, match: i => i % 2 == 0);
```

```output
0
1
3
```

## Alternative Designs

Without this API, it would be easy to write inefficient code like the following, which unnecessarily allocates a new list to track the items to keep:

``` C#
public static void NaiveRemoveAll<T>(this List<T> input, int startIndex, Predicate<T> match)
{
  var output = new List<T>(input.Count);
  foreach (T item in input)
  {
    if (i <= startIndex || !match(item))
    output.Add(input[i]);
  }
  
  input.Clear();
  input.AddRange(output);
}
```

For example of this pattern in existing code, see: https://github.com/PowerShell/PowerShell/blob/b77bbf8640b7e5f43af719878edce3c2617e6ec9/src/System.Management.Automation/engine/Modules/ModuleIntrinsics.cs#L1448

## References

https://docs.microsoft.com/dotnet/api/system.collections.generic.list-1.removeall

**Comment by GrabYourPitchforks** [comment] 2021-06-27 21:00
Might be more useful to embrace the new `Range` type and use that as a parameter? That would allow you to specify a start index _and_ an end index. Everything after the end of the range would be shifted down.

```cs
public int List<T>.RemoveAll(Predicate<T> match, Range range);
```

**Comment by xtqqczze** [comment] 2021-06-27 21:06
Could also consider:
```csharp
public int List<T>.RemoveAll(int startIndex, int count, Predicate<T> match) { }
```

**Comment by KalleOlaviNiemitalo** [comment] 2021-06-27 22:54
The PowerShell use case is not very convincing.

If you want to rewrite the duplicate removal loop in PowerShell by using a RemoveAll method that takes a predicate, then it is easiest to include the first element so that the predicate can store the key of that as `previousKey`:

```csharp
bool firstItem = true;
string previousKey = null;
input.RemoveAll(ShouldRemove);
bool ShouldRemove(T item)
{
    string currentKey = keyGetter(item);
    bool match = !firstItem && currentKey.Equals(previousKey, StringComparison.OrdinalIgnoreCase);
    previousKey = currentKey;
    firstItem = false;
    return match;
}
```

A RemoveAll method that takes an additional `int startIndex` or Range parameter would not help here. Also, although the existing duplicate removal loop costs some memory allocations and CPU time, this cost may be insignificant compared to the sorting that happens just before.

**Comment by Wraith2** [comment] 2021-06-28 09:16
duplicate of https://github.com/dotnet/runtime/issues/53980 ?

**Comment by KalleOlaviNiemitalo** [comment] 2021-06-28 11:10
> duplicate of https://github.com/dotnet/runtime/issues/53980 ?

No, that one proposed a method that would not take a startIndex parameter; rather, it would return an IEnumerable\<T> that contains the removed items and their original indexes.

**Comment by eiriktsarpalis** [comment] 2021-06-28 13:06
> Without this API, it would be easy to write inefficient code like the following, which unnecessarily allocates a new list to track the items to keep

What prevents you from writing something like
```csharp
    public static int RemoveAll<T>(this List<T> list, int startIndex, Predicate<T> predicate)
    {
        int index = 0;
        bool StartIndexPredicate(T t) => index++ >= startIndex && predicate(t);
        return list.RemoveAll(StartIndexPredicate);
    }
```
Granted, this allocates a new closure on each invocation but it is definitely more efficient than the workaround you were proposing.

I can't escape the thought that this could be addressed in the general case by passing the element index to the predicate, i.e.
```csharp
public int List<T>.RemoveAll(Func<int, T, bool> match);

list.RemoveAll((i,t) => i >= startIndex && predicate(t));
```
which is similar to what this [Enumerable.Where](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.where?view=net-5.0#System_Linq_Enumerable_Where__1_System_Collections_Generic_IEnumerable___0__System_Func___0_System_Int32_System_Boolean__) overload is doing.

That being said, per my comments in #53980 there's a runtime cost to adding new methods in `List<T>`, so it's unlikely we would ever consider additions for niche use cases.

**Closed by eiriktsarpalis** 2021-06-28 13:06 UTC
Labels: api-suggestion, area-System.Collections, untriaged
