### ISSUE TITLE
Trimmed System.Text.Json size for Blazor regression

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#51314] opened 2021-04-15 16:36 UTC
System.Text.Json size in Blazor regressed recently by about 15K uncompressed. 
<img width="676" alt="Screen Shot 2021-04-15 at 11 13 27" src="https://user-images.githubusercontent.com/250852/114905566-61f8d300-9e19-11eb-83fe-ecee11b0ed3b.png">

@eerhardt suggested that these 2 changes are possible offenders

#50778
#51025

@layomia @steveharter

**Comment by eerhardt** [comment] 2021-04-15 17:53
Duplicate of https://github.com/dotnet/runtime/issues/51311.

**Closed by eerhardt** 2021-04-15 17:53 UTC
Labels: area-System.Text.Json, size-reduction, untriaged
