### ISSUE TITLE
Under Linux, System.IO.Ports.SerialPort leaks memory when timeout occurs

### ISSUE THREAD

**Issue by sylvainouel** [dotnet/runtime#64768] opened 2022-02-03 21:16 UTC
Consider the following code:
```c#
using System.IO.Ports;

var serial = new SerialPort();
var buf = new byte[10];

serial.PortName = args[0];
serial.ReadTimeout = 10;

serial.Open();
while (true)
{
    try
    {
        serial.Read(buf, 0, buf.Length);
    }
    catch (TimeoutException)
    {
        Console.WriteLine("timeout");
    }
}

```

If you don't receive anything on the port, SerialStreamReadRequest accumulates (this is after just a few minutes):
![image](https://user-images.githubusercontent.com/10534561/152426946-cfd78f4c-1934-48fd-812c-b36b1e72f15f.png)

from looking at the code (https://github.com/dotnet/runtime/blob/main/src/libraries/System.IO.Ports/src/System/IO/Ports/SerialStream.Unix.cs)
I think that what happens is we enqueue a read request https://github.com/dotnet/runtime/blob/c99b3c7e7664a2880e9aa0f5477739f150e3c177/src/libraries/System.IO.Ports/src/System/IO/Ports/SerialStream.Unix.cs#L435
from the ReadAsync, but since there is no bytes coming in, PollEvent never returns PollEvents.POLLIN and the request is never dequeued.

**Comment by ActualIntelligence** [comment] 2022-02-17 21:11
Seems related to issue [#55146](https://github.com/dotnet/runtime/issues/55146).

**Comment by sylvainouel** [comment] 2022-02-18 19:06
I agree, it's the same as the referenced issue.

**Comment by Jozkee** [comment] 2022-04-01 21:54
Duplicate of https://github.com/dotnet/runtime/issues/55146

**Closed by Jozkee** 2022-04-01 21:54 UTC
Labels: area-System.IO, untriaged
