### ISSUE TITLE
SyndicationFeed_Write_RSS_Atom test failing with "IOException : The file '/tmp/' already exists."

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#78454] opened 2022-11-16 11:13 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=84790
Build error leg or test failing: System.ServiceModel.Syndication.Tests.BasicScenarioTests.SyndicationFeed_Write_RSS_Atom
Pull request: https://github.com/dotnet/runtime/pull/78424

Stack trace:
```
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Interop.CheckIo(Int64 result, String path, Boolean isDirError)
   at Interop.CheckIo(IntPtr result, String path, Boolean isDirError)
   at System.IO.Path.GetTempFileName()
   at System.ServiceModel.Syndication.Tests.BasicScenarioTests.SyndicationFeed_Write_RSS_Atom()
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)
```

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section).

```json
{
  "ErrorMessage": "System.IO.IOException : The file '/tmp/' already exists.",
  "BuildRetry": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[112560](https://dev.azure.com/dnceng-public/public/_build/results?buildId=112560)|dotnet/runtime|[WasmTestOnBrowser-System.ServiceModel.Syndication.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=112560&view=ms.vss-test-web.build-test-results-tab&runId=2391060&resultId=180350)|dotnet/runtime#79669|
|[112553](https://dev.azure.com/dnceng-public/public/_build/results?buildId=112553)|dotnet/runtime|[WasmTestOnBrowser-System.ServiceModel.Syndication.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=112553&view=ms.vss-test-web.build-test-results-tab&runId=2390960&resultId=180350)|dotnet/runtime#79672|
|[112315](https://dev.azure.com/dnceng-public/public/_build/results?buildId=112315)|dotnet/runtime|[WasmTestOnBrowser-System.ServiceModel.Syndication.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=112315&view=ms.vss-test-web.build-test-results-tab&runId=2387184&resultId=180350)|dotnet/runtime#79659|
|[111843](https://dev.azure.com/dnceng-public/public/_build/results?buildId=111843)|dotnet/runtime|[WasmTestOnBrowser-System.ServiceModel.Syndication.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=111843&view=ms.vss-test-web.build-test-results-tab&runId=2376302&resultId=180373)|dotnet/runtime#79334|
|[108189](https://dev.azure.com/dnceng-public/public/_build/results?buildId=108189)|dotnet/runtime|[WasmTestOnBrowser-System.ServiceModel.Syndication.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=108189&view=ms.vss-test-web.build-test-results-tab&runId=2305990&resultId=180328)|dotnet/runtime#79472|
|[106860](https://dev.azure.com/dnceng-public/public/_build/results?buildId=106860)|dotnet/runtime|[WasmTestOnBrowser-System.ServiceModel.Syndication.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=106860&view=ms.vss-test-web.build-test-results-tab&runId=2283296&resultId=180305)|dotnet/runtime#79427|
|[106356](https://dev.azure.com/dnceng-public/public/_build/results?buildId=106356)|dotnet/runtime|[WasmTestOnBrowser-System.ServiceModel.Syndication.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=106356&view=ms.vss-test-web.build-test-results-tab&runId=2274394&resultId=180304)|dotnet/runtime#79385|
|[105443](https://dev.azure.com/dnceng-public/public/_build/results?buildId=105443)|dotnet/runtime|[WasmTestOnBrowser-System.ServiceModel.Syndication.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=105443&view=ms.vss-test-web.build-test-results-tab&runId=2255908&resultId=180294)|dotnet/runtime#79339|
|[105198](https://dev.azure.com/dnceng-public/public/_build/results?buildId=105198)|dotnet/runtime|[WasmTestOnBrowser-System.ServiceModel.Syndication.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=105198&view=ms.vss-test-web.build-test-results-tab&runId=2253062&resultId=180306)|dotnet/runtime#75012|
|[102113](https://dev.azure.com/dnceng-public/public/_build/results?buildId=102113)|dotnet/runtime|[WasmTestOnBrowser-System.ServiceModel.Syndication.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=102113&view=ms.vss-test-web.build-test-results-tab&runId=2214458&resultId=180286)|dotnet/runtime#79215|
|[101941](https://dev.azure.com/dnceng-public/public/_build/results?buildId=101941)|dotnet/runtime|[WasmTestOnBrowser-System.ServiceModel.Syndication.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=101941&view=ms.vss-test-web.build-test-results-tab&runId=2185800&resultId=180274)|dotnet/runtime#76500|
|[98594](https://dev.azure.com/dnceng-public/public/_build/results?buildId=98594)|dotnet/runtime|[WasmTestOnBrowser-System.ServiceModel.Syndication.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=98594&view=ms.vss-test-web.build-test-results-tab&runId=2103720&resultId=180265)|dotnet/runtime#79048|
|[96704](https://dev.azure.com/dnceng-public/public/_build/results?buildId=96704)|dotnet/runtime|[WasmTestOnBrowser-System.ServiceModel.Syndication.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=96704&view=ms.vss-test-web.build-test-results-tab&runId=2052810&resultId=180250)||
|[96495](https://dev.azure.com/dnceng-public/public/_build/results?buildId=96495)|dotnet/runtime|[WasmTestOnBrowser-System.ServiceModel.Syndication.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=96495&view=ms.vss-test-web.build-test-results-tab&runId=2046234&resultId=180250)|dotnet/runtime#78888|
|[94682](https://dev.azure.com/dnceng-public/public/_build/results?buildId=94682)|dotnet/runtime|[WasmTestOnBrowser-System.ServiceModel.Syndication.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=94682&view=ms.vss-test-web.build-test-results-tab&runId=1997434&resultId=180249)|dotnet/runtime#78888|
|[93017](https://dev.azure.com/dnceng-public/public/_build/results?buildId=93017)|dotnet/runtime|[WasmTestOnBrowser-System.ServiceModel.Syndication.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=93017&view=ms.vss-test-web.build-test-results-tab&runId=1958718&resultId=180245)|dotnet/runtime#78817|
|[92390](https://dev.azure.com/dnceng-public/public/_build/results?buildId=92390)|dotnet/runtime|[WasmTestOnBrowser-System.ServiceModel.Syndication.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=92390&view=ms.vss-test-web.build-test-results-tab&runId=1945750&resultId=180247)|dotnet/runtime#76436|
|[91316](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91316)|dotnet/runtime|[WasmTestOnBrowser-System.ServiceModel.Syndication.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91316&view=ms.vss-test-web.build-test-results-tab&runId=1923836&resultId=180242)|dotnet/runtime#78725|
|[91016](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91016)|dotnet/runtime|[WasmTestOnBrowser-System.ServiceModel.Syndication.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=91016&view=ms.vss-test-web.build-test-results-tab&runId=1917904&resultId=180242)|dotnet/runtime#78591|
|[90961](https://dev.azure.com/dnceng-public/public/_build/results?buildId=90961)|dotnet/runtime|[WasmTestOnBrowser-System.ServiceModel.Syndication.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=90961&view=ms.vss-test-web.build-test-results-tab&runId=1916606&resultId=180242)|dotnet/runtime#78562|
|[89671](https://dev.azure.com/dnceng-public/public/_build/results?buildId=89671)|dotnet/runtime|[WasmTestOnBrowser-System.ServiceModel.Syndication.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=89671&view=ms.vss-test-web.build-test-results-tab&runId=1892272&resultId=180243)|dotnet/runtime#76462|
|[89555](https://dev.azure.com/dnceng-public/public/_build/results?buildId=89555)|dotnet/runtime|[WasmTestOnBrowser-System.ServiceModel.Syndication.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=89555&view=ms.vss-test-web.build-test-results-tab&runId=1889094&resultId=180241)|dotnet/runtime#78637|
|[88571](https://dev.azure.com/dnceng-public/public/_build/results?buildId=88571)|dotnet/runtime|[WasmTestOnBrowser-System.ServiceModel.Syndication.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=88571&view=ms.vss-test-web.build-test-results-tab&runId=1865004&resultId=179626)|dotnet/runtime#78557|
|[86376](https://dev.azure.com/dnceng-public/public/_build/results?buildId=86376)|dotnet/runtime|[WasmTestOnBrowser-System.ServiceModel.Syndication.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=86376&view=ms.vss-test-web.build-test-results-tab&runId=1810340&resultId=179563)|dotnet/runtime#78446|
|[85957](https://dev.azure.com/dnceng-public/public/_build/results?buildId=85957)|dotnet/runtime|[WasmTestOnBrowser-System.ServiceModel.Syndication.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=85957&view=ms.vss-test-web.build-test-results-tab&runId=1798330&resultId=179563)|dotnet/runtime#70944|
|[85690](https://dev.azure.com/dnceng-public/public/_build/results?buildId=85690)|dotnet/runtime|[WasmTestOnBrowser-System.ServiceModel.Syndication.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=85690&view=ms.vss-test-web.build-test-results-tab&runId=1793338&resultId=179826)|dotnet/runtime#76642|
|[85275](https://dev.azure.com/dnceng-public/public/_build/results?buildId=85275)|dotnet/runtime|[WasmTestOnBrowser-System.ServiceModel.Syndication.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=85275&view=ms.vss-test-web.build-test-results-tab&runId=1784674&resultId=179538)||
|[84790](https://dev.azure.com/dnceng-public/public/_build/results?buildId=84790)|dotnet/runtime|[WasmTestOnBrowser-System.ServiceModel.Syndication.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=84790&view=ms.vss-test-web.build-test-results-tab&runId=1773054&resultId=179538)|dotnet/runtime#78424|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|4|8|28|

**Comment by radical** [comment] 2022-11-16 23:30
@akoeplinger did you see this for non-wasm case too? I thought this might be https://github.com/dotnet/runtime/issues/73721 .

**Comment by akoeplinger** [comment] 2022-11-17 16:21
@radical I _thought_ I saw this outside of wasm but looks like I just looked at the wrong job. It does seem to show only on wasm.

**Comment by lewing** [comment] 2022-11-17 16:41
My guess is that it is https://github.com/dotnet/runtime/pull/74855 because the assumption about failing and isDirError doesn't apply on wasm

**Comment by danmoseley** [comment] 2022-12-15 02:57
@lewing I think you're saying that it's https://github.com/dotnet/runtime/issues/73721 and #74855 simply changed the error, right? this is a dupe of #73721.

**Comment by danmoseley** [comment] 2022-12-15 02:59
and I think this can be closed as a dupe of that.

**Closed by danmoseley** 2022-12-15 02:59 UTC
Labels: arch-wasm, area-System.ServiceModel.Syndication, blocking-clean-ci, Known Build Error
