### ISSUE TITLE
HttpStress fails to build within docker on Windows -- Internal CLR error (0x80131506)

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#53026] opened 2021-05-20 14:03 UTC
Looks like a problem with the SDK using a locally-built runtime within docker. According to build history, the regression happened around 13/05.

Results in build failure with HttpStress:
https://dev.azure.com/dnceng/public/_build/results?buildId=1143571&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=8ca65746-3bfa-57bf-9141-d805b5d39db5

Also applies to SslStress, it fails at runtime:
https://dev.azure.com/dnceng/public/_build/results?buildId=1141136&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=e0810b27-de1e-5f7f-0df7-1a1042e925c2

In both cases, it seems like an (otherwise succesful) dotnet process fails with `Internal CLR error. (0x80131506)` right before exiting.

@jkotas @mangod9 since this might be a runtime error impacting docker use cases, any chance someone in the runtime team is willing to investigate this based on the repro below?

/cc @ViktorHofer 

### Repro

- Install Docker Desktop 
- Switch to Windows Containers
- Start with a clean runtime repo
- From PowerShell prompt in the runtime repo root:

Build the clr+libraries, and pack the runtime from the TESTHOST location into into a container image `dotnet-sdk-libraries-current`, copying it to `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.0` inside the container:

```
.\eng\docker\build-docker-sdk.ps1 -t repro -c Release 
```

Build the HttpStress project within a container from the `dotnet-sdk-libraries-current` as defined in `src\libraries\System.Net.Http\tests\StressTests\HttpStress\windows.Dockerfile`:

```
cd .\src\libraries\System.Net.Http\tests\StressTests\HttpStress\
docker build --file .\windows.Dockerfile --build-arg SDK_BASE_IMAGE=repro .
```

**Comment by antonfirsov** [comment] 2021-05-20 14:07
I really don't know what label to apply here 😞 

Strictly speaking it's @dotnet/ncl, but we are not doing anything special in these test projects. Something outside of our control regressed our tests.

**Comment by mangod9** [comment] 2021-05-20 14:58
Adding under VM area for now. So if I understand correctly the build is actually completing except for the sdk process returning an error during exit? Adding @AntonLapounov  since there was a change which might affect windows containers recently, not sure if its related to this issue though, but we can try to repro.

**Comment by antonfirsov** [comment] 2021-05-20 15:22
Thanks!

> So if I understand correctly the build is actually completing except for the sdk process returning an error during exit?

Most likely yes, since we see the same behavior with [SSL Stress test runs](https://dev.azure.com/dnceng/public/_build/results?buildId=1145707&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3&t=e0810b27-de1e-5f7f-0df7-1a1042e925c2) consistently. After 30 minutes of execution, it prints the final report, then fails with 0x80131506.

**Comment by AntonLapounov** [comment] 2021-05-20 20:07
@antonfirsov Have you tried to collect a crash dump?
```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps]
"DumpFolder"="C:\\Dumps"
"DumpType"=dword:00000002
```

**Comment by antonfirsov** [comment] 2021-06-08 12:37
This seems to be gone since Thursday (Jun 3):
https://dev.azure.com/dnceng/public/_build?definitionId=695

@AntonLapounov any explanation?

**Comment by AntonLapounov** [comment] 2021-06-08 18:46
It might be some intermittent failure. If you can reproduce on your machine, I suggest collecting the crash dump.

**Comment by antonfirsov** [comment] 2021-06-08 19:50
I'm not super experienced with docker, so it wasn't trivial for me to collect the dump from within a container. Do containers virtualize registry keys? If I change it within the container, does it guarantee to enable dump collection the same way it does outside?

**Comment by AntonLapounov** [comment] 2021-06-09 02:49
By default Windows containers use Hyper-V isolation mode, which means they are run in a lightweight VM with its own registry.  I have not tried collecting crash dumps this way before, but I think it should work provided the base docker image contains required components.  If you can reproduce the issue with process isolation (`--isolation=process`), then you just need to modify the registry on the host machine.

**Comment by mangod9** [comment] 2021-07-06 06:18
since this no longer repros, closing it for now.

**Closed by mangod9** 2021-07-06 06:18 UTC
Labels: area-VM-coreclr, untriaged
