### ISSUE TITLE
ios test run on simulator got cancelled

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#45516] opened 2020-12-03 01:52 UTC
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-603733d0cf4e42a98b/System.Xml.RW.WrappedReader.Tests/console.e3c83457.log?sv=2019-07-07&se=2020-12-22T16%3A36%3A36Z&sr=c&sp=rl&sig=XX0uc%2FCJFVBrK3ZaOzU1Ol8CSC%2B4oiJ0v5fldTAFmmU%3D

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=905807&view=ms.vss-test-web.build-test-results-tab&runId=28905840&resultId=142068&paneView=attachments

```
[08:37:02] dbug: 08:37:02.6697240 Found simulator: iPhone X (iOS 13.5) - created by XHarness D7AB34D3-6855-4ECC-B691-B276F307A4C6
[08:37:02] dbug: 08:37:02.6783230 Test log server listening on: 0.0.0.0:50164
[08:37:02] dbug: 08:37:02.6962390 *** Executing 'System.Xml.RW.WrappedReader.Tests' on ios-simulator-64 'iPhone X (iOS 13.5) - created by XHarness' ***
[08:37:02] dbug: 08:37:02.7065270 System log for the 'iPhone X (iOS 13.5) - created by XHarness' simulator is: /private/var/root/Library/Logs/CoreSimulator/D7AB34D3-6855-4ECC-B691-B276F307A4C6/system.log
[08:37:02] dbug: 08:37:02.7486000 Starting test run
[08:37:02] dbug: 08:37:02.7492070 /private/tmp/helix/working/A4CA08E5/p/microsoft.dotnet.xharness.cli/1.0.0-prerelease.20601.1/tools/netcoreapp3.1/any/../../../runtimes/any/native/mlaunch/bin/mlaunch --sdkroot /Applications/Xcode115.app -argument=-connection-mode -argument=none -argument=-app-arg:-autostart -setenv=NUNIT_AUTOSTART=true -argument=-app-arg:-autoexit -setenv=NUNIT_AUTOEXIT=true -argument=-app-arg:-enablenetwork -setenv=NUNIT_ENABLE_NETWORK=true -setenv=DISABLE_SYSTEM_PERMISSION_TESTS=1 -v -v -v -v -v -v -setenv=NUNIT_ENABLE_XML_OUTPUT=true -setenv=NUNIT_ENABLE_XML_MODE=wrapped -setenv=NUNIT_XML_VERSION=xUnit -argument=-app-arg:-transport:Tcp -setenv=NUNIT_TRANSPORT=TCP -argument=-app-arg:-hostport:50164 -setenv=NUNIT_HOSTPORT=50164 -argument=-app-arg:-hostname:127.0.0.1 -setenv=NUNIT_HOSTNAME=127.0.0.1 --device=:v2:udid=D7AB34D3-6855-4ECC-B691-B276F307A4C6 --launchsim /tmp/helix/working/A4CA08E5/w/B74D0982/e/System.Xml.RW.WrappedReader.Tests.app
[08:37:03] dbug: 08:37:03.1170080 Using Xcode 11.5 found in /Applications/Xcode115.app
[08:37:03] dbug: 08:37:03.1220380 Xamarin.Hosting: Xamarin.Hosting
[08:37:03] dbug: 08:37:03.1229150 Xamarin.Hosting:     Version: e6eed65b74 (xcode12)
[08:37:03] dbug: 08:37:03.1234890 Xamarin.Hosting:     Xcode: /Applications/Xcode115.app
[08:37:03] dbug: 08:37:03.1257990 Xamarin.Hosting:     Xcode Version: 11.5
[08:37:03] dbug: 08:37:03.1267300 Xamarin.Hosting:     Verbosity: 6
[08:37:03] dbug: 08:37:03.1433270 Xamarin.Hosting: Loaded /Applications/Xcode115.app/Contents/SharedFrameworks/DVTFoundation.framework/Versions/A/DVTFoundation
[08:37:03] dbug: 08:37:03.1507040 Xamarin.Hosting: Loaded /Applications/Xcode115.app/Contents/SharedFrameworks/DVTiPhoneSimulatorRemoteClient.framework/DVTiPhoneSimulatorRemoteClient
[08:37:03] dbug: 08:37:03.1514080 Xamarin.Hosting: Loaded /Library/Developer/PrivateFrameworks/CoreSimulator.framework/CoreSimulator
[08:37:03] dbug: 08:37:03.1518630 Xamarin.Hosting: Loaded /Applications/Xcode115.app/Contents/SharedFrameworks/DTDeviceKitBase.framework/DTDeviceKitBase
[08:37:03] dbug: 08:37:03.1741360 Xamarin.Hosting: Loaded /Applications/Xcode115.app/Contents/SharedFrameworks/DVTKit.framework/DVTKit
[08:37:03] dbug: 08:37:03.1751280 Xamarin.Hosting: Loaded /Applications/Xcode115.app/Contents/SharedFrameworks/DTDeviceKit.framework/DTDeviceKit
[08:37:03] dbug: 08:37:03.1756250 Xamarin.Hosting: Loaded /Applications/Xcode115.app/Contents/SharedFrameworks/DTXConnectionServices.framework/DTXConnectionServices
[08:37:03] dbug: 08:37:03.1771510 Xamarin.Hosting: Loaded /Applications/Xcode115.app/Contents/SharedFrameworks/DVTSourceControl.framework/DVTSourceControl
[08:37:03] dbug: 08:37:03.1776250 Xamarin.Hosting: Loaded /Applications/Xcode115.app/Contents/SharedFrameworks/DVTServices.framework/DVTServices
[08:37:03] dbug: 08:37:03.1780860 Xamarin.Hosting: Loaded /Applications/Xcode115.app/Contents/SharedFrameworks/DVTPortal.framework/DVTPortal
[08:37:03] dbug: 08:37:03.1965310 Xamarin.Hosting: Loaded /Applications/Xcode115.app/Contents/SharedFrameworks/DVTDocumentation.framework/DVTDocumentation
[08:37:03] dbug: 08:37:03.1983770 Xamarin.Hosting: Loaded /Applications/Xcode115.app/Contents/SharedFrameworks/DVTAnalyticsClient.framework/DVTAnalyticsClient
[08:37:03] dbug: 08:37:03.2006820 Xamarin.Hosting: Loaded /Applications/Xcode115.app/Contents/SharedFrameworks/DVTAnalytics.framework/DVTAnalytics
[08:37:03] dbug: 08:37:03.2046040 Xamarin.Hosting: Loaded /Applications/Xcode115.app/Contents/SharedFrameworks/SourceKit.framework/SourceKit
[08:37:03] dbug: 08:37:03.2399820 Xamarin.Hosting: Loaded /Applications/Xcode115.app/Contents/Frameworks/IDEFoundation.framework/IDEFoundation
[08:37:03] dbug: 08:37:03.2416260 Xamarin.Hosting: Loaded /Applications/Xcode115.app/Contents/SharedFrameworks/IDEProducts.framework/IDEProducts
[08:37:03] dbug: 08:37:03.6119110 Xamarin.Hosting: Simulator watchdogs are already disabled for 'iOS 13.5 (17F61) - iPhone X'.
[08:37:03] dbug: 08:37:03.6266010 Xamarin.Hosting: Launching simulator application 'com.apple.iphonesimulator'
[09:06:49] dbug: 09:06:49.6363600 Killing process 1967 as it was cancelled
[09:06:49] dbug: 09:06:49.6416550 Process mlaunch exited with 137
[09:06:49] dbug: 09:06:49.6422710 Test run failed
[09:06:49] dbug: 09:06:49.6493100 Could not find pid in mtouch output.
[09:06:49] dbug: 09:06:49.6519740 Test run started
[09:06:50] dbug: 09:06:50.7948090 Test run failed to launch
[09:06:50] dbug: 09:06:50.7990330 No crash reports, waiting a second to see if the crash report service just didn't complete in time (4)
[09:06:51] dbug: 09:06:51.8799490 No crash reports, waiting a second to see if the crash report service just didn't complete in time (3)
[09:06:52] dbug: 09:06:52.9013850 No crash reports, waiting a second to see if the crash report service just didn't complete in time (2)
[09:06:54] dbug: 09:06:54.0513630 No crash reports, waiting a second to see if the crash report service just didn't complete in time (1)
[09:06:55] dbug: 09:06:55.1875670 No crash reports, waiting a second to see if the crash report service just didn't complete in time (0)
[09:06:56] fail: Failed to launch the application:
                 Launch failure
                 
                 Check logs for more information.
XHarness exit code: 83
+ exit_code=83
+ '[' 83 -eq 80 ']'
+ '[' 83 -eq 83 ']'
+ sudo pkill -9 -f /Applications/Xcode115.app/Contents/Developer/Applications/Simulator.app
+ chmod 0644 /tmp/helix/working/A4CA08E5/w/B74D0982/uploads/run-ios-simulator-64.log
++ ls '/tmp/helix/working/A4CA08E5/w/B74D0982/uploads/xunit-*.xml'
ls: /tmp/helix/working/A4CA08E5/w/B74D0982/uploads/xunit-*.xml: No such file or directory
```

cc @akoeplinger @steveisok

**Comment by premun** [comment] 2020-12-03 08:39
This is an issue I am working on and should have a fix today or tomorrow hopefully:
https://github.com/dotnet/xharness/issues/305

It is caused by a simulator getting really slow until it won't be able to install things. It doesn't get cancelled, it hangs for 30 minutes actually (see the time difference):
```
[08:37:03] dbug: 08:37:03.6266010 Xamarin.Hosting: Launching simulator application 'com.apple.iphonesimulator'
[09:06:49] dbug: 09:06:49.6363600 Killing process 1967 as it was cancelled
```

**Comment by premun** [comment] 2020-12-03 08:41
I have disabled the machine to unblock the pipeline (it's always machine bound)

**Comment by premun** [comment] 2020-12-03 10:24
I noticed that the yesterday's rollout rebooted the machine and it was completing jobs fine after that.

Fix is here: https://github.com/dotnet/arcade/pull/6639

**Comment by premun** [comment] 2020-12-03 10:25
The pool is now in a good shape, I tested this - we could close this @ViktorHofer

**Comment by premun** [comment] 2020-12-03 18:52
Arcade Helix SDK `6.0.0-beta.20603.2` has the fix

**Comment by directhex** [comment] 2021-03-03 16:29
Marking resolved, as per Premek's comments

**Closed by directhex** 2021-03-03 16:29 UTC
Labels: area-Infrastructure-mono, blocking-clean-ci
