### ISSUE TITLE
ConditionalFact And ConditionalTheory attributes are not working in the VS

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#32628] opened 2020-02-20 23:57 UTC
Helpers.NotElevatedAndSupportsEventLogs is false for eventlog tests but still following test is getting run in the vs test explorer

 [ConditionalFact(typeof(Helpers), nameof(Helpers.NotElevatedAndSupportsEventLogs))]
 public void SetProperties_SaveChanges_NotAdmin_Throws()

cc @ViktorHofer @ericstj @safern

**Comment by safern** [comment] 2020-02-21 00:26
This is a duplicate of: https://github.com/dotnet/runtime/issues/1161

**Closed by safern** 2020-02-21 00:26 UTC
Labels: area-Infrastructure-libraries, untriaged
