### ISSUE TITLE
.NET 5.0.5 SortedSet(IComparer).GetViewBetween(X,Y).Max returns invalid value

### ISSUE THREAD

**Issue by lAnubisl** [dotnet/runtime#59640] opened 2021-09-27 09:33 UTC
### Description

    class Program
    {
        static void Main(string[] args)
        {
            var store = new SortedSet<int[]>(new MyComp());
            store.Add(new int[] { 24 });
            store.Add(new int[] { 43 });
            var view = store.GetViewBetween(new int[] { -1 }, new int[] { 25 });
            Console.WriteLine(view.Count);    // 1
            Console.WriteLine(view.Max[0]);   // 43 (this should be 24)
            Console.WriteLine(view.Last()[0]); // 24
        }
    }

    public class MyComp : IComparer<int[]>
    {
        public int Compare(int[] x, int[] y)
        {
            return x[0] - y[0];
        }
    }

### Configuration

* .NET 5.0.5
* Windows 10
* x64
* Works correctly in .NET Framework 4.7.2

### Regression?

Yes. Works correctly in .NET Framework 4.7.2

### Other information

Workaround is to implement IComparer to return -1, 0 1 but not sure 100% that is will work for all cases.

**Comment by Joe4evr** [comment] 2021-09-27 10:59
Duplicate of #54834.

**Comment by danmoseley** [comment] 2021-09-27 13:55
@lAnubisl could you please confirm this is fixed in .NET 6 RC1?

**Closed** 2021-11-17 06:01 UTC
Labels: area-System.Collections, needs more info, untriaged, no recent activity
