### ISSUE TITLE
String Comparation Globalization Not Working in Blazor WebAssembly

### ISSUE THREAD

**Issue by taoyouh** [dotnet/runtime#66899] opened 2022-03-20 11:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In zh-CN locale, the strings should be compared by pinyin. For example, the following strings are in the expected order:

> 啊
> 波
> 次
> 得

While a .NET console app does follow this behavior, the minimal testing on Blazor Assembly gives incorrect sorting result.

### Expected Behavior

The sorting result given by Blazor WebAssembly should be:

> 啊 (a)
> 波 (bo)
> 次 (ci)
> 得 (de)

### Steps To Reproduce

Use the repro project here: https://github.com/taoyouh/BlazorApp1

The project is the default Blazor WebAssembly template with only Index.razor changed.

1. Set the browser locale to zh-CN (Chinese - China)
2. Launch the Blazor project (BlazorApp1) in Visual Studio
3. The incorrect sorting result will be shown on the home page:

> 啊 (a)
> 得 (de)
> 次 (ci)
> 波 (bo)

The console project (ConsoleApp1) shows the correct sorting result in zh-CN locale:

> 啊 (a)
> 波 (bo)
> 次 (ci)
> 得 (de)

### Exceptions (if any)

None

### .NET Version

6.2.201

### Anything else?

ASP.NET Core version: 6.0.3

VS version: 17.1.1

> .NET SDK (反映任何 global.json):
>  Version:   6.0.201
>  Commit:    ef40e6aa06
> 
> 运行时环境:
>  OS Name:     Windows
>  OS Version:  10.0.22000
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\6.0.201\
> 
> Host (useful for support):
>   Version: 6.0.3
>   Commit:  c24d9a9c91
> 
> .NET SDKs installed:
>   3.1.417 [C:\Program Files\dotnet\sdk]
>   5.0.404 [C:\Program Files\dotnet\sdk]
>   5.0.406 [C:\Program Files\dotnet\sdk]
>   6.0.201 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
> 
> To install additional .NET runtimes or SDKs:
>   https://aka.ms/dotnet-download

**Comment by mkArtakMSFT** [comment] 2022-03-20 15:47
@lewing FYI

**Comment by lewing** [comment] 2022-03-30 01:59
This is a result of the way we reduce the culture data to save size, can you explain your use case to help a prioritize a fix for this?

**Comment by taoyouh** [comment] 2022-03-30 02:11
@lewing
If I build an app to serve Chinese users and provide some string-based sorting function, e.g. sorting some files by their names, the strings need to be sorted in a localized way. For CJK users, the current result is in a random order. The documents didn't say this important feature is trimmed and didn't mention how to enable it.

Btw, I see that my `dotnet build` produced a `icudt_CJK.dat` file, but it is not loaded by the browser as shown in the F12 developer console. What is this file used for?

**Comment by taoyouh** [comment] 2022-03-30 02:13
@lewing In conclusion, this feature is necessary to support A-Z sorting in CJK, and A-Z sorting is necessay in many kinds of applications.

**Comment by taoyouh** [comment] 2022-04-30 04:45
> This is a result of the way we reduce the culture data to save size, can you explain your use case to help a prioritize a fix for this?

If this is intended, what is the `icudt_CJK.dat` file in the build artifact used for?

**Comment by ilonatommy** [comment] 2022-06-23 15:01
Thank you 

> > This is a result of the way we reduce the culture data to save size, can you explain your use case to help a prioritize a fix for this?
> 
> If this is intended, what is the `icudt_CJK.dat` file in the build artifact used for?

Thank you, as far as I know the filtered data files (in your situation `CJK`) should be loaded but you're right that they are not. We're looking into it.

**Comment by ilonatommy** [comment] 2022-12-20 12:19
The issue was most probably caused by corrupted ICU file and is now resolved.

1) icudt_CJK not present in the Broswer's memory when running Blazor app is fixed. When running the project I am fist opening a browser, cleaning cache, setting language to Chineese and then connecting to the port where the app is running. Result:
![image](https://user-images.githubusercontent.com/32700855/208664408-36ee17fb-e9d9-4054-a6ae-da7f23e7029e.png)

2) Wrong collation is fixed as well. For all the tested cases: in dotnet 7 

Console App:
啊 得 次 波

Blazor WASM:
啊 得 次 波

Blazor WASM with `<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>`, so icudt.dat:
啊 得 次 波

WASM Browser with icudt_CJK.dat:
啊 得 次 波

**Comment by lewing** [comment] 2022-12-20 17:25
I think we still remove some of the extra CJK collation options from the Wasm icu build, @ilonatommy can you check the filters?

**Comment by ilonatommy** [comment] 2022-12-21 10:29
Theoretically adding `"+/collations/pinyin",` to filters fixes the issue, however:
- it increases the size from 1491 to 1654
- it should have been loaded with current filters because we are already adding `"+/collations/default"`, where "default" is an alias for "pinyin" in `zh.txt`: 
https://github.com/dotnet/icu/blob/641b393af47306c44f666803058545857bf10f07/icu/icu4c/source/data/coll/zh.txt#L14

I will investigate further.

**Closed** 2023-03-27 15:09 UTC
Labels: arch-wasm, area-System.Globalization
