### ISSUE TITLE
In .NET5, the JSON file is read using StreamReader, Chinese is garbled, winFrom reads normally.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#50459] opened 2021-03-30 23:54 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/在NET5使用StreamReader读取JSON文件，中文乱码，winFro/1373856)._

---
[severity:Other]
In the case of the same computer, the same JSON file, json file also tried ASCII, UTF8 two encoding formats to save, in the .NET5 WebApi using StreamReader to read garbled code, winFrom read normal.

Here's .NET 5 plus C plus WebApi, with StreamReader
```
StreamReader streamReader s new StreamReader (path, Encoding.UTF8); //UTF8 has tried ASCII, Default, or the second argument is not filled in here
string jsonStr = streamReader.ReadToEnd();
Console.WriteLine (Encoding.Default.EncodingName); //Output Unicode (UTF-8)
Console.WriteLine (streamReader.CurrentEncoding); // Output system. Text.UTF8Encoding+UTF8EncodingSealed
Console.WriteLine (jsonStr); //Output "ok": "errcode": 0, "errmsg": "?????", where the Chinese is garbled
```

Here's .NET Framework 4 plus C plus WinFrom, with StreamReader

```
StreamReader streamReader = new StreamReader(path,Encoding.UTF8);
string jsonStr = streamReader.ReadToEnd();
Console.WriteLine (Encoding.Default.EncodingName); //Chinese Simplified (GB2312)
Console.WriteLine (streamReader.CurrentEncoding); / Output System.Text.UTF8Encoding
Console.WriteLine (jsonStr); //Output "ok": "errcode": 0, "errmsg": "Success", where the Chinese is normal
```

The following is JSON data

```
{
    "ok": "errcode": 0, "errmsg": "Success"
}
```

---
#### Feedback Bot on 3/18/2021, 01:12 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by danmoseley** [comment] 2021-03-31 00:49
cc @GrabYourPitchforks who may immediately know why.

**Comment by Jozkee** [comment] 2021-05-20 17:46
Triage: this could be related to the console output encoding.
Also tagging @tarekgh who is more familiar with encoding.

**Comment by Jozkee** [comment] 2021-05-20 17:49
https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding.default?view=net-5.0#the-default-property-in-net-framework
> On .NET Core, the Default property always returns the UTF8Encoding. UTF-8 is supported on all the operating systems (Windows, Linux, and macOS) on which .NET Core applications run.

This is by design, you need to manually set the output encoding explicitly. Closing.

**Closed by Jozkee** 2021-05-20 17:49 UTC
Labels: area-System.IO, needs further triage
