### ISSUE TITLE
[9.0] System.Net.Quic.Tests.QuicStreamConformanceTests.ConcurrentBidirectionalReadsWrites_Success is hanging

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#107762] opened 2024-09-12 20:22 UTC
## Build Information

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=805750
Build error leg or test failing: `System.Net.Quic.Functional.Test`

## Error Message

```json
{
  "ErrorMessage" : 
  [
    "'System.Net.Quic.Tests.QuicStreamConformanceTests.ConcurrentBidirectionalReadsWrites_Success', Elapsed",
    "['System.Net.Quic.Functional.Tests' END OF WORK ITEM LOG: Command timed out, and was killed]"
  ],
  "BuildRetry" : false,
  "ExcludeConsoleLog" : false
}
```

- Unrelated 9.0 PR: https://github.com/dotnet/runtime/pull/107724
- Queue: `Libraries Test Run checked coreclr osx x64 Debug`
- Job result: https://dev.azure.com/dnceng-public/public/_build/results?buildId=805750&view=logs&j=69b60b53-a417-56e9-d4e0-3a40344d5e67&t=5193bee0-1c28-53bc-a56d-6d396c4c4a0d&l=68
- Log file: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-107724-merge-670b66ae06e54b5392/System.Net.Quic.Functional.Tests/1/console.819c34d5.log?helixlogtype=result
- Output:
```
===========================================================================================================
/private/tmp/helix/working/A7D00979/w/ACE20948/e /private/tmp/helix/working/A7D00979/w/ACE20948/e
  Discovering: System.Net.Quic.Functional.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Quic.Functional.Tests (found 138 of 152 test cases)
  Starting:    System.Net.Quic.Functional.Tests (parallel test collections = on [12 threads], stop on fail = off)
MsQuic supported and using 'libmsquic.dylib 2.4.0.0 (e0385b047d7bd622319e9f6c4c00184a1294eea8)'.
    System.Net.Quic.Tests.MsQuicPlatformDetectionTests.UnsupportedPlatforms_ThrowsPlatformNotSupportedException [SKIP]
      Condition(s) not met: "IsQuicUnsupported"
   System.Net.Quic.Functional.Tests: [Long Running Test] 'System.Net.Quic.Tests.QuicStreamConformanceTests.ConcurrentBidirectionalReadsWrites_Success', Elapsed: 00:02:06
   System.Net.Quic.Functional.Tests: [Long Running Test] 'System.Net.Quic.Tests.QuicStreamConformanceTests.ConcurrentBidirectionalReadsWrites_Success', Elapsed: 00:04:07
   System.Net.Quic.Functional.Tests: [Long Running Test] 'System.Net.Quic.Tests.QuicStreamConformanceTests.ConcurrentBidirectionalReadsWrites_Success', Elapsed: 00:06:09
   System.Net.Quic.Functional.Tests: [Long Running Test] 'System.Net.Quic.Tests.QuicStreamConformanceTests.ConcurrentBidirectionalReadsWrites_Success', Elapsed: 00:08:10
   System.Net.Quic.Functional.Tests: [Long Running Test] 'System.Net.Quic.Tests.QuicStreamConformanceTests.ConcurrentBidirectionalReadsWrites_Success', Elapsed: 00:10:12
   System.Net.Quic.Functional.Tests: [Long Running Test] 'System.Net.Quic.Tests.QuicStreamConformanceTests.ConcurrentBidirectionalReadsWrites_Success', Elapsed: 00:12:13
['System.Net.Quic.Functional.Tests' END OF WORK ITEM LOG: Command timed out, and was killed]
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=805750
**Error message validated:** `['System.Net.Quic.Tests.QuicStreamConformanceTests.ConcurrentBidirectionalReadsWrites_Success', Elapsed ['System.Net.Quic.Functional.Tests' END OF WORK ITEM LOG: Command timed out, and was killed]`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 9/12/2024 8:23:09 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[805750](https://dev.azure.com/dnceng-public/public/_build/results?buildId=805750)|dotnet/runtime|[System.Net.Quic.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=805750&view=ms.vss-test-web.build-test-results-tab&runId=20823898&resultId=211854)|dotnet/runtime#107724|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|1|

**Comment by ManickaP** [comment] 2024-09-13 08:06
Duplicate of #103482

**Closed by ManickaP** 2024-09-13 08:06 UTC
Labels: os-mac-os-x, arch-x64, runtime-coreclr, area-System.Net.Quic, test-failure, Known Build Error
