### ISSUE TITLE
Microsoft.DotNet.CoreSetup.Test.HostActivation tests failing in CI

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#75429] opened 2022-09-12 00:46 UTC
Hit in #75408. Full log: https://dev.azure.com/dnceng-public/public/_build/results?buildId=11824&view=ms.vss-test-web.build-test-results-tab&runId=235664&resultId=100162&paneView=debug

```
[EXEC       <] [FAIL] [00:01:38.800] /root/runtime/artifacts/tests/Release/ha/sdornqub.dxh/AppWithCustomEntryPoints> /root/runtime/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --framework net7.0 /p:NetCoreAppCurrent=net7.0 --self-contained true --runtime linux-musl-x64 -o /root/runtime/artifacts/tests/Release/ha/sdornqub.dxh/AppWithCustomEntryPoints/bin /p:TestTargetRid=linux-musl-x64 /p:MNAVersion=7.0.0-ci exited with 1
[xUnit.net 00:01:42.81]     Microsoft.DotNet.CoreSetup.Test.HostActivation.NativeHosting.GetFunctionPointer.CallDelegateOnApplicationContext_UnhandledException [FAIL]
[xUnit.net 00:01:42.81]       System.AggregateException : One or more errors occurred. (Command failed with exit code 1: /root/runtime/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --framework net7.0 /p:NetCoreAppCurrent=net7.0 --self-contained true --runtime linux-musl-x64 -o /root/runtime/artifacts/tests/Release/ha/sdornqub.dxh/AppWithCustomEntryPoints/bin /p:TestTargetRid=linux-musl-x64 /p:MNAVersion=7.0.0-ci
[xUnit.net 00:01:42.81]       Standard Output:
[xUnit.net 00:01:42.81]       MSBuild version 17.4.0-preview-22416-02+5d102ae37 for .NET
[xUnit.net 00:01:42.81]       /root/runtime/.dotnet/sdk/7.0.100-rc.1.22425.9/MSBuild.dll -maxcpucount -property:_IsPublishing=true --property:NetCoreAppCurrent=net7.0 --property:TestTargetRid=linux-musl-x64 --property:MNAVersion=7.0.0-ci -property:PublishDir=/root/runtime/artifacts/tests/Release/ha/sdornqub.dxh/AppWithCustomEntryPoints/bin -property:SelfContained=True -property:_CommandLineDefinedSelfContained=true -property:TargetFramework=net7.0 -property:RuntimeIdentifier=linux-musl-x64 -property:_CommandLineDefinedRuntimeIdentifier=true -target:Publish -verbosity:m /bl:PublishProject.binlog ./AppWithCustomEntryPoints.csproj
[xUnit.net 00:01:42.81]       /root/runtime/.dotnet/sdk/7.0.100-rc.1.22425.9/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(219,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/root/runtime/artifacts/tests/Release/ha/sdornqub.dxh/AppWithCustomEntryPoints/AppWithCustomEntryPoints.csproj]
[xUnit.net 00:01:42.81]         AppWithCustomEntryPoints -> /root/runtime/artifacts/tests/Release/ha/sdornqub.dxh/AppWithCustomEntryPoints/bin/Debug/net7.0/linux-musl-x64/AppWithCustomEntryPoints.dll
[xUnit.net 00:01:42.81]       
[xUnit.net 00:01:42.81]       ) (The following constructor parameters did not have matching fixture data: SharedTestState sharedTestState)
[xUnit.net 00:01:42.81]       ---- Microsoft.DotNet.Cli.Build.Framework.BuildFailureException : Command failed with exit code 1: /root/runtime/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --framework net7.0 /p:NetCoreAppCurrent=net7.0 --self-contained true --runtime linux-musl-x64 -o /root/runtime/artifacts/tests/Release/ha/sdornqub.dxh/AppWithCustomEntryPoints/bin /p:TestTargetRid=linux-musl-x64 /p:MNAVersion=7.0.0-ci
[xUnit.net 00:01:42.81]       Standard Output:
[xUnit.net 00:01:42.81]       MSBuild version 17.4.0-preview-22416-02+5d102ae37 for .NET
[xUnit.net 00:01:42.81]       /root/runtime/.dotnet/sdk/7.0.100-rc.1.22425.9/MSBuild.dll -maxcpucount -property:_IsPublishing=true --property:NetCoreAppCurrent=net7.0 --property:TestTargetRid=linux-musl-x64 --property:MNAVersion=7.0.0-ci -property:PublishDir=/root/runtime/artifacts/tests/Release/ha/sdornqub.dxh/AppWithCustomEntryPoints/bin -property:SelfContained=True -property:_CommandLineDefinedSelfContained=true -property:TargetFramework=net7.0 -property:RuntimeIdentifier=linux-musl-x64 -property:_CommandLineDefinedRuntimeIdentifier=true -target:Publish -verbosity:m /bl:PublishProject.binlog ./AppWithCustomEntryPoints.csproj
[xUnit.net 00:01:42.81]       /root/runtime/.dotnet/sdk/7.0.100-rc.1.22425.9/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(219,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/root/runtime/artifacts/tests/Release/ha/sdornqub.dxh/AppWithCustomEntryPoints/AppWithCustomEntryPoints.csproj]
[xUnit.net 00:01:42.81]         AppWithCustomEntryPoints -> /root/runtime/artifacts/tests/Release/ha/sdornqub.dxh/AppWithCustomEntryPoints/bin/Debug/net7.0/linux-musl-x64/AppWithCustomEntryPoints.dll
[xUnit.net 00:01:42.81]       
[xUnit.net 00:01:42.82]       
[xUnit.net 00:01:42.82]       ---- The following constructor parameters did not have matching fixture data: SharedTestState sharedTestState
[xUnit.net 00:01:42.82]       Stack Trace:
[xUnit.net 00:01:42.82]         
[xUnit.net 00:01:42.82]         ----- Inner Stack Trace #1 (Microsoft.DotNet.Cli.Build.Framework.BuildFailureException) -----
[xUnit.net 00:01:42.82]         /_/src/installer/tests/TestUtils/CommandResult.cs(46,0): at Microsoft.DotNet.Cli.Build.Framework.CommandResult.EnsureSuccessful(Boolean suppressOutput)
[xUnit.net 00:01:42.82]         /_/src/installer/tests/TestUtils/TestProjectFixture.cs(333,0): at Microsoft.DotNet.CoreSetup.Test.TestProjectFixture.PublishProject(DotNetCli dotnet, String runtime, String framework, Nullable`1 selfContained, String outputDirectory, Boolean singleFile, Boolean restore, String[] extraArgs)
[xUnit.net 00:01:42.82]         /_/src/installer/tests/HostActivation.Tests/NativeHosting/GetFunctionPointer.cs(240,0): at Microsoft.DotNet.CoreSetup.Test.HostActivation.NativeHosting.GetFunctionPointer.SharedTestState..ctor()
[xUnit.net 00:01:42.82]            at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
[xUnit.net 00:01:42.82]            at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
[xUnit.net 00:01:42.82]         ----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
[xUnit.net 00:01:42.82]         
[EXEC       >] [....] [00:01:38.834] /root/runtime/artifacts/tests/Release/ha/nativeHosting/1/nativehost resolve_component_dependencies run_app_and_resolve 
```

```json
{
   "ErrorMessage":"The following constructor parameters did not have matching fixture data: SharedTestState fixture"
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by jkotas** [comment] 2022-09-12 00:48
Failed again in https://github.com/dotnet/runtime/pull/75407

Full log: https://dev.azure.com/dnceng-public/public/_build/results?buildId=11802&view=ms.vss-test-web.build-test-results-tab&runId=235336&resultId=100032&paneView=debug
```
System.AggregateException : One or more errors occurred. (Command failed with exit code 1: /root/runtime/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --framework net7.0 /p:NetCoreAppCurrent=net7.0 -o /root/runtime/artifacts/tests/Release/ha/k0ufkmfh.z0w/StartupHookWithMultipleIncorrectSignatures/bin /p:TestTargetRid=linux-x64 /p:MNAVersion=7.0.0-ci
Standard Output:
MSBuild version 17.4.0-preview-22416-02+5d102ae37 for .NET
/root/runtime/.dotnet/sdk/7.0.100-rc.1.22425.9/MSBuild.dll -maxcpucount -property:_IsPublishing=true --property:NetCoreAppCurrent=net7.0 --property:TestTargetRid=linux-x64 --property:MNAVersion=7.0.0-ci -property:PublishDir=/root/runtime/artifacts/tests/Release/ha/k0ufkmfh.z0w/StartupHookWithMultipleIncorrectSignatures/bin -property:TargetFramework=net7.0 -target:Publish -verbosity:m /bl:PublishProject.binlog ./StartupHookWithMultipleIncorrectSignatures.csproj
/root/runtime/.dotnet/sdk/7.0.100-rc.1.22425.9/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(219,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/root/runtime/artifacts/tests/Release/ha/k0ufkmfh.z0w/StartupHookWithMultipleIncorrectSignatures/StartupHookWithMultipleIncorrectSignatures.csproj]
StartupHookWithMultipleIncorrectSignatures -> /root/runtime/artifacts/tests/Release/ha/k0ufkmfh.z0w/StartupHookWithMultipleIncorrectSignatures/bin/Debug/net7.0/StartupHookWithMultipleIncorrectSignatures.dll
StartupHookWithMultipleIncorrectSignatures -> /root/runtime/artifacts/tests/Release/ha/k0ufkmfh.z0w/StartupHookWithMultipleIncorrectSignatures/bin/

) (The following constructor parameters did not have matching fixture data: SharedTestState fixture)
---- Microsoft.DotNet.Cli.Build.Framework.BuildFailureException : Command failed with exit code 1: /root/runtime/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --framework net7.0 /p:NetCoreAppCurrent=net7.0 -o /root/runtime/artifacts/tests/Release/ha/k0ufkmfh.z0w/StartupHookWithMultipleIncorrectSignatures/bin /p:TestTargetRid=linux-x64 /p:MNAVersion=7.0.0-ci
Standard Output:
MSBuild version 17.4.0-preview-22416-02+5d102ae37 for .NET
/root/runtime/.dotnet/sdk/7.0.100-rc.1.22425.9/MSBuild.dll -maxcpucount -property:_IsPublishing=true --property:NetCoreAppCurrent=net7.0 --property:TestTargetRid=linux-x64 --property:MNAVersion=7.0.0-ci -property:PublishDir=/root/runtime/artifacts/tests/Release/ha/k0ufkmfh.z0w/StartupHookWithMultipleIncorrectSignatures/bin -property:TargetFramework=net7.0 -target:Publish -verbosity:m /bl:PublishProject.binlog ./StartupHookWithMultipleIncorrectSignatures.csproj
/root/runtime/.dotnet/sdk/7.0.100-rc.1.22425.9/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(219,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/root/runtime/artifacts/tests/Release/ha/k0ufkmfh.z0w/StartupHookWithMultipleIncorrectSignatures/StartupHookWithMultipleIncorrectSignatures.csproj]
StartupHookWithMultipleIncorrectSignatures -> /root/runtime/artifacts/tests/Release/ha/k0ufkmfh.z0w/StartupHookWithMultipleIncorrectSignatures/bin/Debug/net7.0/StartupHookWithMultipleIncorrectSignatures.dll
StartupHookWithMultipleIncorrectSignatures -> /root/runtime/artifacts/tests/Release/ha/k0ufkmfh.z0w/StartupHookWithMultipleIncorrectSignatures/bin/

---- The following constructor parameters did not have matching fixture data: SharedTestState fixture
```

**Comment by vitek-karas** [comment] 2022-09-12 13:45
I looked at the logs of both of those failures and it's weird. The test log says something like (simplified):
```Console
Command failed with exit code 1: /root/runtime/.dotnet/dotnet publish ...
Standard output: 
... MSBuild startup and so on ...
StartupHookWithMultipleIncorrectSignatures -> /root/runtime/artifacts/tests/Release/ha/k0ufkmfh.z0w/StartupHookWithMultipleIncorrectSignatures/bin/
```

There's no stderr printed out. The two failures are on a different test assets but otherwise look very similar.

Looking into the logs, the msbuild binlog for the publish command says that the command succeeded in both case.

So it's happening for different test assets, on different targets (one is linux_x64, the other one is linux_x64_musl) and rarely.

@elinor-fung as FYI and for possible ideas.

**Comment by carlossanlop** [comment] 2022-09-12 17:10
Seen also in this other release/7.0 PR: https://github.com/dotnet/runtime/pull/75407

Please help determine if this test failure need a fix to get backported to that branch, or if the test can get disabled.

**Comment by elinor-fung** [comment] 2022-09-12 17:50
Seems like this is only happening in release/7.0 right now?

The tests run the SDK used by the repo to publish test projects/assets. Potential difference I see is that release/7.0 is using RC1
https://github.com/dotnet/runtime/blob/cd483c16cc23b99c303c83f73c69a8fcde99abf6/global.json#L7-L8

while main is using Preview 7
https://github.com/dotnet/runtime/blob/467fef4a77a44d68b7062ebb5ad77a50fa7f78ba/global.json#L7-L8

Maybe this is actually exposing a bug in RC1?

As @vitek-karas pointed out, it looks like the publish succeeds - or at least does not log any errors. But the exit code is 1. This is the binlog for the project in https://github.com/dotnet/runtime/issues/75429#issuecomment-1243088361 (renamed extension): [PublishProject.binlog.log](https://github.com/dotnet/runtime/files/9550412/PublishProject.binlog.log).

**Comment by vitek-karas** [comment] 2022-09-12 18:22
This looks basically identical to https://github.com/dotnet/runtime/issues/74328
The symptoms of that bug:  publish returns 1 on success

**Comment by vitek-karas** [comment] 2022-09-12 20:13
Closing this as dupe of #74328 since it has the exact same behavior.

**Comment by jkotas** [comment] 2022-10-24 03:23
> Closing this as dupe of https://github.com/dotnet/runtime/issues/74328 since it has the exact same behavior.

#74328 is not being hit by the CI anymore.

`The following constructor parameters did not have matching fixture data: SharedTestState fixture` error is still hit in CI frequently. Reopening to get accurate known build error accounting.

**Comment by carlossanlop** [comment] 2022-11-03 18:11
The following release/7.0 backport PR hit the 3 symlink failures: https://github.com/dotnet/runtime/pull/77501

Put_app_directory_behind_symlink
```
Microsoft.NET.HostModel.Tests.AppHostUsedWithSymbolicLinks.Put_app_directory_behind_symlink
System.AggregateException : One or more errors occurred. (Command failed with exit code 1: /Users/runner/work/1/s/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --framework net7.0 /p:NetCoreAppCurrent=net7.0 -o /Users/runner/work/1/s/artifacts/tests/Release/hma/y0ebud3x.nhx/PortableApp/bin /p:TestTargetRid=osx-x64 /p:MNAVersion=7.0.0
Standard Output:
MSBuild version 17.4.0-preview-22416-02+5d102ae37 for .NET
/Users/runner/work/1/s/.dotnet/sdk/7.0.100-rc.1.22431.11/MSBuild.dll -maxcpucount -property:_IsPublishing=true --property:NetCoreAppCurrent=net7.0 --property:TestTargetRid=osx-x64 --property:MNAVersion=7.0.0 -property:PublishDir=/Users/runner/work/1/s/artifacts/tests/Release/hma/y0ebud3x.nhx/PortableApp/bin -property:TargetFramework=net7.0 -target:Publish -verbosity:m /bl:PublishProject.binlog ./PortableApp.csproj
/Users/runner/work/1/s/.dotnet/sdk/7.0.100-rc.1.22431.11/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(219,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/Users/runner/work/1/s/artifacts/tests/Release/hma/y0ebud3x.nhx/PortableApp/PortableApp.csproj]
  PortableApp -> /Users/runner/work/1/s/artifacts/tests/Release/hma/y0ebud3x.nhx/PortableApp/bin/Debug/net7.0/PortableApp.dll
  PortableApp -> /Users/runner/work/1/s/artifacts/tests/Release/hma/y0ebud3x.nhx/PortableApp/bin/

) (The following constructor parameters did not have matching fixture data: SharedTestState fixture)
---- Microsoft.DotNet.Cli.Build.Framework.BuildFailureException : Command failed with exit code 1: /Users/runner/work/1/s/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --framework net7.0 /p:NetCoreAppCurrent=net7.0 -o /Users/runner/work/1/s/artifacts/tests/Release/hma/y0ebud3x.nhx/PortableApp/bin /p:TestTargetRid=osx-x64 /p:MNAVersion=7.0.0
Standard Output:
MSBuild version 17.4.0-preview-22416-02+5d102ae37 for .NET
/Users/runner/work/1/s/.dotnet/sdk/7.0.100-rc.1.22431.11/MSBuild.dll -maxcpucount -property:_IsPublishing=true --property:NetCoreAppCurrent=net7.0 --property:TestTargetRid=osx-x64 --property:MNAVersion=7.0.0 -property:PublishDir=/Users/runner/work/1/s/artifacts/tests/Release/hma/y0ebud3x.nhx/PortableApp/bin -property:TargetFramework=net7.0 -target:Publish -verbosity:m /bl:PublishProject.binlog ./PortableApp.csproj
/Users/runner/work/1/s/.dotnet/sdk/7.0.100-rc.1.22431.11/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(219,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/Users/runner/work/1/s/artifacts/tests/Release/hma/y0ebud3x.nhx/PortableApp/PortableApp.csproj]
  PortableApp -> /Users/runner/work/1/s/artifacts/tests/Release/hma/y0ebud3x.nhx/PortableApp/bin/Debug/net7.0/PortableApp.dll
  PortableApp -> /Users/runner/work/1/s/artifacts/tests/Release/hma/y0ebud3x.nhx/PortableApp/bin/


---- The following constructor parameters did not have matching fixture data: SharedTestState fixture
```

and 

Put_dotnet_behind_symlink
```
Microsoft.NET.HostModel.Tests.AppHostUsedWithSymbolicLinks.Put_dotnet_behind_symlink
System.AggregateException : One or more errors occurred. (Command failed with exit code 1: /Users/runner/work/1/s/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --framework net7.0 /p:NetCoreAppCurrent=net7.0 -o /Users/runner/work/1/s/artifacts/tests/Release/hma/y0ebud3x.nhx/PortableApp/bin /p:TestTargetRid=osx-x64 /p:MNAVersion=7.0.0
Standard Output:
MSBuild version 17.4.0-preview-22416-02+5d102ae37 for .NET
/Users/runner/work/1/s/.dotnet/sdk/7.0.100-rc.1.22431.11/MSBuild.dll -maxcpucount -property:_IsPublishing=true --property:NetCoreAppCurrent=net7.0 --property:TestTargetRid=osx-x64 --property:MNAVersion=7.0.0 -property:PublishDir=/Users/runner/work/1/s/artifacts/tests/Release/hma/y0ebud3x.nhx/PortableApp/bin -property:TargetFramework=net7.0 -target:Publish -verbosity:m /bl:PublishProject.binlog ./PortableApp.csproj
/Users/runner/work/1/s/.dotnet/sdk/7.0.100-rc.1.22431.11/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(219,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/Users/runner/work/1/s/artifacts/tests/Release/hma/y0ebud3x.nhx/PortableApp/PortableApp.csproj]
  PortableApp -> /Users/runner/work/1/s/artifacts/tests/Release/hma/y0ebud3x.nhx/PortableApp/bin/Debug/net7.0/PortableApp.dll
  PortableApp -> /Users/runner/work/1/s/artifacts/tests/Release/hma/y0ebud3x.nhx/PortableApp/bin/

) (The following constructor parameters did not have matching fixture data: SharedTestState fixture)
---- Microsoft.DotNet.Cli.Build.Framework.BuildFailureException : Command failed with exit code 1: /Users/runner/work/1/s/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --framework net7.0 /p:NetCoreAppCurrent=net7.0 -o /Users/runner/work/1/s/artifacts/tests/Release/hma/y0ebud3x.nhx/PortableApp/bin /p:TestTargetRid=osx-x64 /p:MNAVersion=7.0.0
Standard Output:
MSBuild version 17.4.0-preview-22416-02+5d102ae37 for .NET
/Users/runner/work/1/s/.dotnet/sdk/7.0.100-rc.1.22431.11/MSBuild.dll -maxcpucount -property:_IsPublishing=true --property:NetCoreAppCurrent=net7.0 --property:TestTargetRid=osx-x64 --property:MNAVersion=7.0.0 -property:PublishDir=/Users/runner/work/1/s/artifacts/tests/Release/hma/y0ebud3x.nhx/PortableApp/bin -property:TargetFramework=net7.0 -target:Publish -verbosity:m /bl:PublishProject.binlog ./PortableApp.csproj
/Users/runner/work/1/s/.dotnet/sdk/7.0.100-rc.1.22431.11/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(219,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/Users/runner/work/1/s/artifacts/tests/Release/hma/y0ebud3x.nhx/PortableApp/PortableApp.csproj]
  PortableApp -> /Users/runner/work/1/s/artifacts/tests/Release/hma/y0ebud3x.nhx/PortableApp/bin/Debug/net7.0/PortableApp.dll
  PortableApp -> /Users/runner/work/1/s/artifacts/tests/Release/hma/y0ebud3x.nhx/PortableApp/bin/


---- The following constructor parameters did not have matching fixture data: SharedTestState fixture
```

and

Put_satellite_assembly_behind_symlink
```
Microsoft.NET.HostModel.Tests.AppHostUsedWithSymbolicLinks.Put_satellite_assembly_behind_symlink
System.AggregateException : One or more errors occurred. (Command failed with exit code 1: /Users/runner/work/1/s/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --framework net7.0 /p:NetCoreAppCurrent=net7.0 -o /Users/runner/work/1/s/artifacts/tests/Release/hma/y0ebud3x.nhx/PortableApp/bin /p:TestTargetRid=osx-x64 /p:MNAVersion=7.0.0
Standard Output:
MSBuild version 17.4.0-preview-22416-02+5d102ae37 for .NET
/Users/runner/work/1/s/.dotnet/sdk/7.0.100-rc.1.22431.11/MSBuild.dll -maxcpucount -property:_IsPublishing=true --property:NetCoreAppCurrent=net7.0 --property:TestTargetRid=osx-x64 --property:MNAVersion=7.0.0 -property:PublishDir=/Users/runner/work/1/s/artifacts/tests/Release/hma/y0ebud3x.nhx/PortableApp/bin -property:TargetFramework=net7.0 -target:Publish -verbosity:m /bl:PublishProject.binlog ./PortableApp.csproj
/Users/runner/work/1/s/.dotnet/sdk/7.0.100-rc.1.22431.11/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(219,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/Users/runner/work/1/s/artifacts/tests/Release/hma/y0ebud3x.nhx/PortableApp/PortableApp.csproj]
  PortableApp -> /Users/runner/work/1/s/artifacts/tests/Release/hma/y0ebud3x.nhx/PortableApp/bin/Debug/net7.0/PortableApp.dll
  PortableApp -> /Users/runner/work/1/s/artifacts/tests/Release/hma/y0ebud3x.nhx/PortableApp/bin/

) (The following constructor parameters did not have matching fixture data: SharedTestState fixture)
---- Microsoft.DotNet.Cli.Build.Framework.BuildFailureException : Command failed with exit code 1: /Users/runner/work/1/s/.dotnet/dotnet publish /bl:PublishProject.binlog --no-restore --framework net7.0 /p:NetCoreAppCurrent=net7.0 -o /Users/runner/work/1/s/artifacts/tests/Release/hma/y0ebud3x.nhx/PortableApp/bin /p:TestTargetRid=osx-x64 /p:MNAVersion=7.0.0
Standard Output:
MSBuild version 17.4.0-preview-22416-02+5d102ae37 for .NET
/Users/runner/work/1/s/.dotnet/sdk/7.0.100-rc.1.22431.11/MSBuild.dll -maxcpucount -property:_IsPublishing=true --property:NetCoreAppCurrent=net7.0 --property:TestTargetRid=osx-x64 --property:MNAVersion=7.0.0 -property:PublishDir=/Users/runner/work/1/s/artifacts/tests/Release/hma/y0ebud3x.nhx/PortableApp/bin -property:TargetFramework=net7.0 -target:Publish -verbosity:m /bl:PublishProject.binlog ./PortableApp.csproj
/Users/runner/work/1/s/.dotnet/sdk/7.0.100-rc.1.22431.11/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(219,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/Users/runner/work/1/s/artifacts/tests/Release/hma/y0ebud3x.nhx/PortableApp/PortableApp.csproj]
  PortableApp -> /Users/runner/work/1/s/artifacts/tests/Release/hma/y0ebud3x.nhx/PortableApp/bin/Debug/net7.0/PortableApp.dll
  PortableApp -> /Users/runner/work/1/s/artifacts/tests/Release/hma/y0ebud3x.nhx/PortableApp/bin/


---- The following constructor parameters did not have matching fixture data: SharedTestState fixture
```

**Comment by elinor-fung** [comment] 2022-11-03 18:26
https://github.com/dotnet/runtime/pull/77524 added a workaround to main (same as what we did for the wasm failures). I just triggered a backport.

**Comment by elinor-fung** [comment] 2023-01-20 22:16
This was addressed when the repo switched to .NET 7 GA. The workarounds were removed in https://github.com/dotnet/runtime/pull/79035

**Closed by elinor-fung** 2023-01-20 22:16 UTC
Labels: blocking-clean-ci, area-Host, Known Build Error
