### ISSUE TITLE
Support serialization/deserialization of 'ImmutableArray<byte>' as base64 strings

### ISSUE THREAD

**Issue by julealgon** [dotnet/runtime#47550] opened 2021-01-27 22:31 UTC
System.Text.Json will successfully deserialize a base64-encoded string into a `byte[]` property, and serialize a `byte[]` property back into a base64-encoded string. However, this only works for the raw `byte[]` type.

I propose this logic be extended to `ImmutableArray<byte>` as well, using a new converter that performs similar logic than the default one used for `byte[]`.

The reasoning is simple: `ImmutableArray<byte>` is a higher level abstraction than `byte[]` and is a more restrictive and robust type, so its use is preferred. Additionally, using `ImmutableArray<T>` also prevents [CA1819: Properties should not return arrays](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1819). Even though the rule states that a suppression for DTO-like objects is fine, it is still preferred to use a better, more robust type if available, and `ImmutableArray` fits the bill.

Sample implementation (based on the original converter for `byte[]`):

```csharp
    internal sealed class ImmutableByteArrayConverter : JsonConverter<ImmutableArray<byte>>
    {
        public override ImmutableArray<byte> Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return reader.GetBytesFromBase64().ToImmutableArray();
        }

        public override void Write(Utf8JsonWriter writer, ImmutableArray<byte> value, JsonSerializerOptions options)
        {
            writer.WriteBase64StringValue(value.AsSpan());
        }
    }
```

Optionally, the converter could be made to also handle normal number arrays.

**Comment by eiriktsarpalis** [comment] 2021-01-28 15:14
I think it's reasonable to use the same encodings as arrays when serializing immutable arrays. @layomia thoughts?

**Comment by layomia** [comment] 2021-01-28 15:40
@eiriktsarpalis - I closed a dupe of this issue for this reason, thoughts? https://github.com/dotnet/runtime/issues/45147#issuecomment-736188219

>We likely won't make any changes here by default since that would be breaking. A custom converter can be written to get the desired semantics here. Closing since a change like this isn't on the roadmap for JSON for now (especially if it involves new API to opt-in). Can be revisited if proven to be blocking (i.e. a custom converter isn't a viable solution).

I do agree that we should treat the two types the same, but don't have much appetite for adding public API just for the new behavior not to be breaking.

Do you think that a breaking change to serialize `ImmutableArray<byte>` as base64 by default would be low impact?

**Comment by eiriktsarpalis** [comment] 2021-01-28 16:25
I tend to agree with @scalablecory's comment on https://github.com/dotnet/runtime/issues/45147#issuecomment-733464238 that `ImmutableArray<byte>` might warrant this. However we are currently serializing it different this would be a breaking change, so it might not be such a good idea. The workaround is pretty straightforward, just use regular byte arrays for your DTOs.

**Comment by layomia** [comment] 2021-01-28 16:38
> The workaround is pretty straightforward, just use regular byte arrays for your DTOs.

The other workaround if you can't change to byte arrays is to use a custom converter for `ImmutableArray<T>` - https://dotnetfiddle.net/Dxf7Sp.

Will close this issue since there are a couple workarounds and we don't want the breaking changing change.

**Closed by layomia** 2021-01-28 16:38 UTC
Labels: area-System.Text.Json

**Comment by julealgon** [comment] 2021-01-28 17:26
> The workaround is pretty straightforward, just use regular byte arrays for your DTOs.

@eiriktsarpalis I think that's not a good workaround for the reasons I mentioned in OP. I think encouraging people to rely on low-level writable array properties is ill-advised.

> and we don't want the breaking changing change.

@layomia what about actually providing the converter out of the box, but not using it by default?

This is how `JsonStringEnumConverter` works: it is not used by default, but consumers of the library can opt-in to it by just adding an instance of it to the `Converters` collection.

Also, I'd suggest avoiding the `.ToArray()` call on the `Write` side of the converter like you did since `AsSpan` works and does not create a duplicate of the data (see my example code in OP).

**Comment by layomia** [comment] 2021-01-29 23:29
@julealgon - `JsonStringEnumConverter` was provided to address a common scenario. I'd say this is not quite as common. It would be great to see more folks signal that the converter workaround is not sufficient for them. That would help us see if we should add it inbox.

> Also, I'd suggest avoiding the .ToArray() call on the Write side of the converter like you did since AsSpan works and does not create a duplicate of the data (see my example code in OP).

Thanks. I missed your converter entirely; I'd have pointed to that when mentioning the converter workaround.

**Comment by julealgon** [comment] 2021-01-30 13:55
>  I'd say this is not quite as common. It would be great to see more folks signal that the custom converter workaround is not sufficient for them. That would help us see if we should add it inbox.

@layomia While waiting for more upvotes and similar issues to pop up to do this is fair in most situations, I'd like to argue that it does not apply as cleanly to this one.

Most people who will encounter this problem will probably switch to using `byte[]` once they realize they'd have to create a custom converter (no matter how simple). I think the reason more people are not complaining about this is exactly because they are following that easy route and living with it. IMHO, as Microsoft, the use of more robust types should be pushed as much as possible for the future health of the language and the ecosystem.

As long as MS keeps making it harder to use the immutable types, people will keep not using it. Providing a converter for these scenarios would allow people to more easily use them. More people using these types will promote them to be more standard, and will in turn reduce errors and positively impact the image of .Net.

Just wanted to throw this out there. I just think the most common workaround for this is "too easy to fall for" and leads into a poor path for everybody involved.
