### ISSUE TITLE
Installer build (corehost) for Linux/OSX failing in official build

### ISSUE THREAD

**Issue by elinor-fung** [dotnet/runtime#38590] opened 2020-06-30 00:15 UTC
Failing on `singlefilehost` build.

```
gmake[2]: *** No rule to make target `/root/runtime/artifacts/transport/AllArtifacts/CoreCLRProduct__release/lib/libcoreclr_static.a', needed by `cli/apphost/static/singlefilehost'.  Stop.
gmake[2]: *** Waiting for unfinished jobs....
  [ 88%] Building CXX object cli/apphost/static/CMakeFiles/singlefilehost.dir/__/__/__/corehost.cpp.o
gmake[1]: *** [cli/apphost/static/CMakeFiles/singlefilehost.dir/all] Error 2
```

cc @swaroop-sridhar @VSadov

**Comment by swaroop-sridhar** [comment] 2020-06-30 00:18
Caused by https://github.com/dotnet/runtime/pull/36847

**Comment by swaroop-sridhar** [comment] 2020-06-30 00:59
The problem here, as identified by @jkoritzinsky, is that `CoreCLRArtifactsPath` is `/root/runtime/artifacts/transport/AllArtifacts/CoreCLRProduct__release/...`  , rather than `/root/runtime/artifacts/transport/AllArtifacts/CoreCLRProduct_Linux-x64_release/...`

**Comment by swaroop-sridhar** [comment] 2020-06-30 01:02
`CoreCLRArtifactsPath` is computed [here](https://github.com/dotnet/runtime/blame/d65dd306eea83d2435432d787cb435211d540f6c/eng/liveBuilds.targets#L38).

However, in /root/runtime/src/installer/corehost/build.proj, `ArtifactPlatform` is not set [here](https://github.com/dotnet/runtime/blame/d65dd306eea83d2435432d787cb435211d540f6c/eng/liveBuilds.targets#L28-L34) because `RuntimeIdentifier` is not set.

**Comment by VSadov** [comment] 2020-06-30 03:31
It looks like `RuntimeArtifactsPath` is passed correctly to the build and should become `CoreCLRArtifactsPath`, however later it is overriden because of the condition in:
```xml
 <PropertyGroup Condition="
    '$(RuntimeIdentifier)' != '$(OutputRid)' and
    '$(AllArtifactsDownloadPath)' != ''">
```

which is true if `RuntimeIdentifier` is not specified.

Perhaps the fix should be 

```xml
 <PropertyGroup Condition="
    '$(RuntimeIdentifier)' != '' and
    '$(RuntimeIdentifier)' != '$(OutputRid)' and
    '$(AllArtifactsDownloadPath)' != ''">
```

i.e. - if `RuntimeIdentifier` is not specified, just let the default value (`CoreCLRArtifactsPath`) be used?

**Comment by VSadov** [comment] 2020-06-30 03:54
For reference - we get 
`/p:RuntimeArtifactsPath=/root/runtime/artifacts/transport/coreclr`

And that is where the coreclr binaries are unzipped.

However we also get 
`/p:AllArtifactsDownloadPath=artifacts/transport/AllArtifacts`

which triggers the override, but there is nothing to override to - since  `RuntimeIdentifier` in this case is empty.

**Comment by VSadov** [comment] 2020-06-30 23:55
Fixed in https://github.com/dotnet/runtime/pull/38602

**Closed by VSadov** 2020-06-30 23:55 UTC
Labels: area-Single-File, untriaged
