### ISSUE TITLE
DirectoryServices.Protocol tests failed with SIGABRT on checked CoreCLR

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#37046] opened 2020-05-27 09:05 UTC
`runtime (Libraries Test Run checked coreclr Linux x64 Debug)` leg failed due to dotnet crashed with SIGABRT.

From [console log](https://helix.dot.net/api/2019-06-17/jobs/8b5f4fa7-e518-4de6-9db6-6ecb994f96c1/workitems/System.DirectoryServices.Protocols.Tests/console):

```sh
~/work/B90F09F6/w/B73F09D1/e ~/work/B90F09F6/w/B73F09D1/e
  Discovering: System.DirectoryServices.Protocols.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.DirectoryServices.Protocols.Tests (found 343 of 369 test cases)
  Starting:    System.DirectoryServices.Protocols.Tests (parallel test collections = on, max threads = 2)
    System.DirectoryServices.Protocols.Tests.DirectoryServicesProtocolsTests.TestMoveAndRenameUser [SKIP]
      Condition(s) not met: "IsLdapConfigurationExist"
    System.DirectoryServices.Protocols.Tests.DirectoryServicesProtocolsTests.TestNestedOUs [SKIP]
      Condition(s) not met: "IsLdapConfigurationExist"
    System.DirectoryServices.Protocols.Tests.DirectoryServicesProtocolsTests.TestAsyncSearch [SKIP]
      Condition(s) not met: "IsLdapConfigurationExist"
    System.DirectoryServices.Protocols.Tests.DirectoryServicesProtocolsTests.TestAddAndModifyAttribute [SKIP]
      Condition(s) not met: "IsLdapConfigurationExist"
    System.DirectoryServices.Protocols.Tests.DirectoryServicesProtocolsTests.TestAddingMultipleAttributes [SKIP]
      Condition(s) not met: "IsLdapConfigurationExist"
    System.DirectoryServices.Protocols.Tests.DirectoryServicesProtocolsTests.TestPageRequests [SKIP]
      Condition(s) not met: "IsActiveDirectoryServer"
    System.DirectoryServices.Protocols.Tests.DirectoryServicesProtocolsTests.TestAddingOU [SKIP]
      Condition(s) not met: "IsLdapConfigurationExist"
    System.DirectoryServices.Protocols.Tests.DirectoryServicesProtocolsTests.TestDeleteOU [SKIP]
      Condition(s) not met: "IsLdapConfigurationExist"
    System.DirectoryServices.Protocols.Tests.DirectorySe
dotnet: ../nptl/pthread_mutex_lock.c:79: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
./RunTests.sh: line 161: 53067 Aborted                 "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.DirectoryServices.Protocols.Tests.runtimeconfig.json --depsfile System.DirectoryServices.Protocols.Tests.deps.json xunit.console.dll System.DirectoryServices.Protocols.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
~/work/B90F09F6/w/B73F09D1/e
----- end Tue May 26 21:33:23 UTC 2020 ----- exit code 134 ----------------------------------------------------------
exit code 134 means SIGABRT Abort. Managed or native assert, or runtime check such as heap corruption, caused call to abort(). Core dumped.
```

**Comment by ericstj** [comment] 2020-07-09 17:09
cc @joperezr

**Comment by danmosemsft** [comment] 2020-08-07 21:08
Duplicate of https://github.com/dotnet/runtime/issues/39009

**Closed by danmosemsft** 2020-08-07 21:08 UTC
Labels: area-System.DirectoryServices, bug, tenet-reliability
