### ISSUE TITLE
Double.TryParse fails on string that has thousands separator. Regression? 

### ISSUE THREAD

**Issue by katjoek** [dotnet/runtime#100397] opened 2024-03-28 09:50 UTC
### Description

I format a double value to string and parsing that string back to a double fails, using the same culture info.

### Reproduction Steps

This test fails for me
```       
var value = 2000.0;
var valueAsText = value.ToString("N5", CultureInfo.CurrentCulture); // 2,000.00000
var success = double.TryParse(valueAsText, NumberStyles.Any, CultureInfo.CurrentCulture, out value);
Assert.True(success);
```

You can find it here in this repo: https://github.com/katjoek/DoubleTryParseFails

### Expected behavior

I expect it to be possible to convert a double value to a string and back again when using the same culture info and allowing any kind of formatting style when parsing.

### Actual behavior

double.TryParse("2,000.00000", NumberStyles.Any, CultureInfo.CurrentCulture, out var value) returns false eventhough that string was created just before using 2000.0.ToString("N5", CultureInfo.CurrentCulture)

![image](https://github.com/dotnet/runtime/assets/3399018/5f76560d-561f-495c-838a-fbac0593411c)

### Regression?

I think not. I also reproduces on dotnet 6.0.

### Known Workarounds

Format the string in a different way: do not have the thousands separator. In my project, using format "N5" fails, using "F5" works.

### Configuration

This is with .NET core 8.0 on Windows 10 

Processor	11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz   2.30 GHz
Installed RAM	32.0 GB (31.7 GB usable)
Product ID	00330-80000-00000-AA459
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 10 Enterprise
Version	22H2
Installed on	‎17/‎08/‎2022
OS build	19045.4170
Experience	Windows Feature Experience Pack 1000.19054.1000.0

My regional settings:
![image](https://github.com/dotnet/runtime/assets/3399018/2833e9e1-b0e6-463f-9014-a7d53696f9b3)

**Comment by huoyaoyuan** [comment] 2024-03-28 10:20
I can parse this successfully:
```csharp
double.Parse("2,000.000", System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.CurrentCulture)
```

You can print `CultureInfo.CurrentCulture.NumberFormat.NumberDecimalSeparator` to see what culture information is taken by .NET.

**Comment by katjoek** [comment] 2024-04-02 07:25
I also expected "2,000.000" successfully :-)

The NumberDecimalSparator is a period:
![image](https://github.com/dotnet/runtime/assets/3399018/0c10e3d2-2c83-477b-9c91-34c43acf5698)

While I'm at it, NumberGroupSeparator is a comma:
![image](https://github.com/dotnet/runtime/assets/3399018/f9ee9814-3f20-444c-bcd4-f5c4107fdd0b)

Note that leaving out the comma from the input string makes it work for me.

**Comment by katjoek** [comment] 2024-04-02 07:32
Actually, for me ""2,000.000" does parse correctly, but "2,000.00000" does not!

**Comment by huoyaoyuan** [comment] 2024-04-02 09:37
Well, no matter what culture you are using, `ToString` and `TryParse` should successfully round trip since they are using the same culture.

Can you provide a more concrete reproduction? It can be a console application printing failing results. Information about current culture and the resultant parsed string should be printed as well.

**Comment by katjoek** [comment] 2024-04-03 11:22
I added a small console application called Repro-100397 to my repo.

The main code:
```
var options = new JsonSerializerOptions
{
    WriteIndented = true,
    ReferenceHandler = ReferenceHandler.IgnoreCycles,
};
var jsonString = JsonSerializer.Serialize(CultureInfo.CurrentCulture, options);
Console.WriteLine(jsonString);

var str = "2,000.000";
var success = double.TryParse(str, NumberStyles.Any, CultureInfo.CurrentCulture, out var value);
Console.WriteLine($"success: {success}");
Console.WriteLine($"value: {value}");
```

I've attached the resulting output: [Repro-100397-result.txt](https://github.com/dotnet/runtime/files/14851318/Repro-100397-result.txt)

**Comment by huoyaoyuan** [comment] 2024-04-03 17:18
@tannergooding any thoughts on this? I guess this should belong to numerics area.

**Comment by tannergooding** [comment] 2024-04-03 17:55
This would normally be a globalization issue, not numerics.

The issue is that you're outputting as `N5` put parsing using `Any` (which is `AllowLeadingWhite | AllowTrailingWhite | AllowLeadingSign | AllowTrailingSign | AllowParentheses | AllowDecimalPoint | AllowThousands | AllowCurrencySymbol | AllowExponent`). -- The default is notably `NumberStyles.Float | NumberStyles.AllowThousands`

`N5` is going to use `info.NumberDecimalSeparator`, and `info.NumberGroupSeparator`.

While `Parse`, because you've used `Any` which includes `AllowCurrencySymbol`, is going to use `info.CurrencyDecimalSeparator` and `info.CurrencyGroupSeparator`. You would have needed to format using `C5` which would use the currency separators for this to work.

**Comment by katjoek** [comment] 2024-04-03 19:32
@tannergooding, nice to see an explanation. Does this mean that this is as designed? One would expect a round trip of converting to string and parsing it back to a double should work, right?

As a workaround, I know that using F5 also works. But I think I would rather change the “Any” into something else. I’m not sure what, though. Any suggestions?

**Comment by tannergooding** [comment] 2024-04-03 19:40
>  One would expect a round trip of converting to string and parsing it back to a double should work, right?

It does work, the issue is you're not using equivalent parsing/formatting options, and so you can't roundtrip.

That is to say, you're formatting as `x` (`numeric format` in this case) and parsing as `y` (`currency format` in this case). Roundtripping only works if you format as `x` and parse as `x` (or format as `y` and parse as `y`, etc).

The fix would be to not include the `AllowCurrency` specifier in the number styles you picked, since that modifies how `AllowDecimalPoint` is interepreted, as documented by https://learn.microsoft.com/en-us/dotnet/api/system.globalization.numberstyles?view=net-8.0

**Comment by katjoek** [comment] 2024-04-04 07:27
I understand and I also understand that this does not need to be fixed. I also think it is very reasonable that one assumes that it should work. "Any" suggests this. 🙂

This problem by the way does not happen at my colleague's computers . This is probably because I have non-standard localization settings. I have en-NL but with the group and decimal separators swapped. This allows me to read CSV files in Excel that are formatted with InvariantCulture.

Thanks!

**Comment by tannergooding** [comment] 2024-04-04 14:53
> This allows me to read CSV files in Excel that are formatted with InvariantCulture.

If you know it is invariant, then why not just use `double.Parse(..., CultureInfo.InvariantCulture)`?

**Comment by Clockwork-Muse** [comment] 2024-04-04 15:51
As an addition to @tannergooding 's question, because CSV is meant to be an interchange format it _should_ be read/written with the invariant culture (and relying on a machine's culture is doomed to failure).  And also without the thousands separator, especially if the separator would be the field delimiter.

**Comment by katjoek** [comment] 2024-04-05 09:28
The data in this case comes from the UI, not a CSV file with InvariantCulture. :-)

The CSV file is just the reason why I tinkered with the regional settings.

**Comment by tarekgh** [comment] 2024-06-21 00:46
Looks like no more actions are needed here so I am closing the issue. Please reply if you still have any questions.

**Closed by tarekgh** 2024-06-21 00:46 UTC
Labels: area-System.Globalization, untriaged
