### ISSUE TITLE
CS0122: 'ProblemDetailsJsonConverter' is inaccessible due to its protection level in code generated by System.Tex.Json.SourceGenerator

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/runtime#94862] opened 2023-11-16 18:42 UTC
### Description

When creating a `JsonSerializerContext` using `JsonSerializableAttribute` for `Microsoft.AspNetCore.Mvc.ProblemDetails`, the generated code tries to instantiate `global::Microsoft.AspNetCore.Http.ProblemDetailsJsonConverter`.

### Reproduction Steps

**Project**:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
```

**ProblemDetailsJsonSerializerContext.cs**:
```csharp
using Microsoft.AspNetCore.Mvc;
using System.Text.Json.Serialization;

[JsonSerializable(typeof(ProblemDetails))]
public partial class ProblemDetailsJsonSerializerContext: JsonSerializerContext
{
}
```

### Expected behavior

The generated code is compilable.

### Actual behavior

The generated code contains `new global::Microsoft.AspNetCore.Http.ProblemDetailsJsonConverter()`, which yields **CS0122: 'ProblemDetailsJsonConverter' is inaccessible due to its protection level**.

### Configuration

Tried with .NET 6.0 using SDK 6.0.416 and .NET 6.0 and 7.0 using SDK 8.0.100.

The issue seems to be solved for .NET 8.0 using SDK 8.0.100.

**Comment by paulomorgado** [comment] 2023-11-16 20:00
Found a workaround: deriving from `ProblemDetails`:

```csharp
using System.Text.Json.Serialization;

public class ProblemDetails : global::Microsoft.AspNetCore.Mvc.ProblemDetails { }

[JsonSerializable(typeof(ProblemDetails))]
public partial class ProblemDetailsJsonSerializerContext: JsonSerializerContext
{
}
```

**Comment by eiriktsarpalis** [comment] 2023-11-16 23:34
Duplicate of https://github.com/dotnet/runtime/issues/79161. As you're pointing out this was fixed in .NET 8.

**Closed by eiriktsarpalis** 2023-11-16 23:34 UTC
Labels: area-System.Text.Json, untriaged

**Comment by paulomorgado** [comment] 2023-11-17 08:39
@eiriktsarpalis,

> Duplicate of #79161. As you're pointing out this was fixed in .NET 8.

May I remind you that it was fixed for only 1/3 of the supported SDKs?

**Comment by eiriktsarpalis** [comment] 2023-11-17 10:40
As a general rule we don't backport bug fixes that don't meet a certain bar for servicing: security vulns or substantially broken user scenaria without a workaround. 

Have you considered using the latest NuGet package in your application?

**Comment by paulomorgado** [comment] 2023-11-17 10:55
@eiriktsarpalis, what NuGet package would that be?

I'm using the source generator from the SDK (6.0.416 in this project). Is there a way to use a more recent generator without using the .NET 8.0 SDK?

**Comment by eiriktsarpalis** [comment] 2023-11-17 14:41
The System.Text.Json package https://www.nuget.org/packages/System.Text.Json

**Comment by paulomorgado** [comment] 2023-11-17 16:27
@eiriktsarpalis, it does work. But the problem here is that this project is a dependency for other projects where the dependency on 8.0 libraries is not possible.
