### ISSUE TITLE
Poor Debug.Assert experience in VS

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#40793] opened 2020-08-13 19:38 UTC
From https://github.com/dotnet/coreclr/pull/20764#issuecomment-673386853

Repro: Create a simple command line app that just does `Debug.Assert(false)` and F5 it in VS.

Result:
![image](https://user-images.githubusercontent.com/4403806/90122882-57c19900-dda1-11ea-9434-2eb47a7ab03c.png)

**Comment by jkotas** [comment] 2020-08-13 19:39
@noahfalk @gregg-miskelly What needs to get fixed to make this experience to be like on .NET Framework where the debugger highlights the line where the assert failed?

**Comment by gregg-miskelly** [comment] 2020-08-13 20:49
Wow, it is kind of amazing that we are still discovering things like this.

The problem is that the VS debugger has code to automatically step out of asserts before stopping. But the assert detection logic was never updated for .NET Core. I opened VS bug 1173112 for this.

Question: I am assuming that it is enough to just pay attention to:
* System.Diagnostics.Debug.Assert
* System.Diagnostics.Debug.Fail
* System.Diagnostics.Debugger.Break (this one was already handled)
* System.Diagnostics.Debugger.Launch (this one was already handled)

Is that correct? Or is there some reason to care about `DebugProvider`?

**Comment by jkotas** [comment] 2020-08-13 20:58
`DebugProvider` is internal implementation detail of `Debug.Assert`.

**Comment by gregg-miskelly** [comment] 2020-08-13 21:00
Thanks. I think you can close this issue then.

**Comment by jkotas** [comment] 2020-08-13 21:01
Would it make sense to mark some of these methods with `NoInlining` to make sure that the debugger can see them and trigger the step out, even in optimized code?

**Comment by gregg-miskelly** [comment] 2020-08-13 22:01
It would be kind of a weird scenario for it to matter, but maybe it makes sense --
1. In the case of System.Diagnostics.Debug.*: These all have conditional compilation attributes, so normally one wouldn't have optimized code where this is important. But of course you could turn on optimizations for your 'debug' builds (a.k.a. `chk` in old Razzle)
2. In the case of System.Diagnostics.Debugger.Break: My guess is that if this would be inlined, that is probably just fine since the whole goal of the feature is to step back to the calling frame, so if that was inlined into it it wouldn't be a problem.

**Comment by noahfalk** [comment] 2021-01-25 23:48
From discussion above it sounds like this issue was ready to be closed. VS side is tracked separately and .NET tweaks were submitted by @jkotas already. Thanks!

**Closed by noahfalk** 2021-01-25 23:48 UTC
Labels: area-System.Diagnostics
