### ISSUE TITLE
[API Proposal]: Add left join

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#97492] opened 2024-01-25 05:27 UTC
### Background and motivation

I suggest adding the LeftJoin method to Linq JObject, it is useful if you need to find elements that were not joined

### API Proposal

```csharp

```

### API Usage

```csharp


var en = Enumerable.Range(1, 10).Select(a=>a.ToString());
var en2 = Enumerable.Range(1, 5).Select(a => a.ToString());



var result = en2.LeftJoin(en, a => a, x => x, (en2, en) =>
{
    return new { joinResultEn = en,joinResultEn2=en2};
})
    .Where(a=>a.joinResultEn is null)
    .ToList();//
```

**Comment by Abdragiz** [comment] 2024-01-25 07:20
https://learn.microsoft.com/en-us/dotnet/csharp/linq/perform-left-outer-joins

As far as I understand, it's possible to perform a left join with the existing API.

**Comment by roji** [comment] 2024-12-01 15:23
Closing in favor of #110292, which is a full API proposal.

**Comment by roji** [comment] 2024-12-01 15:23
Duplicate of #110292

**Closed by roji** 2024-12-01 15:23 UTC
Labels: api-suggestion, area-System.Linq, wishlist
