### ISSUE TITLE
tcp-throughput regression (localhost) with NetworkStream.ReadAsync()/WriteAsync() from .net 6.0.26 to .net 8.0.1

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#97554] opened 2024-01-26 14:06 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/tcp-throughput-regression-localhost-wi/10561731)._

---
when switching from .net 6 to .net 8, the throughput of the tcp communication between two console applications running on the same computer (127.0.0.1) drops significantly (~ -40%). The attached example uses TcpListener/TcpClient and NetworkStream.ReadAsync()/WriteAsync(). 
The throughput for NetworkStream.Read()/Write() is comparably fast for both .net versions

OS: Windows10/Windows 11
IDE: Visual Studio 2022 17.8.4
.net 6.0.26
.net 8.0.1

---
#### Feedback Bot on 16/01/2024, 02:58 AM: 

(private comment, text removed)
#### Tomas Weinfurt [MSFT] on 16/01/2024, 03:37 AM: 

(private comment, text removed)
#### Thilo Elzer on 16/01/2024, 10:19 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by stephentoub** [comment] 2024-01-26 14:20
Duplicate of https://github.com/dotnet/runtime/issues/97056

**Closed** 2024-01-26 15:16 UTC
Labels: area-System.Net, untriaged
