### ISSUE TITLE
Segmentation fault on .NET 6 - Linux Ubuntu 18.04

### ISSUE THREAD

**Issue by jantache-microsoft** [dotnet/runtime#97467] opened 2024-01-24 20:02 UTC
### Description

With `DOTNET_GCHeapCount=1`, a segmentation fault on a 32 core machine (Standard_E32s_v5) in heap initialization occurs.

### Reproduction Steps

With the mentioned setting and VM size, start up a .NET application.

### Expected behavior

No crashing

### Actual behavior

Crash happens

### Known Workarounds

- Undo GC setting: `DOTNET_GCHeapCount=`
- Smaller core counts also don't seem to reproduce the issue

### Configuration

- Intel x86_64
- Linux, Ubuntu 18.04
- DOTNET_GCHeapCount=1
- eeversion from sos: 6.0.2623.60508 @Commit: dc45e96840243b203b13e61952230e225d2aac52

### Other information

Stack traces from gdb/lldb - both in case there is a preference:

<details>
<summary>LLDB backtrace</summary>

```
(lldb) thread backtrace
* thread #1, name = 'program', stop reason = signal SIGSEGV
  * frame #0: 0x00007fb35dab032a libpthread.so.0`__waitpid + 74
    frame #1: 0x00007fb35c9463a1 libcoreclr.so`::PROCCreateCrashDumpIfEnabled(int, siginfo_t *) at process.cpp:3276
    frame #2: 0x00007fb35c946349 libcoreclr.so`::PROCCreateCrashDumpIfEnabled(signal=<unavailable>, siginfo=0x00007fb35dee34b0) at process.cpp:3463
    frame #3: 0x00007fb35c90f1db libcoreclr.so`invoke_previous_action(action=<unavailable>, code=11, siginfo=0x00007fb35dee34b0, context=0x00007fb35dee3380, signalRestarts=<unavailable>) at signal.cpp:404
    frame #4: 0x00007fb35c90e987 libcoreclr.so`sigsegv_handler(code=11, siginfo=0x00007fb35dee34b0, context=0x00007fb35dee3380) at signal.cpp:611
    frame #5: 0x00007fb35dab0980 libpthread.so.0`___lldb_unnamed_symbol1$$libpthread.so.0 + 1
    frame #6: 0x00007fb35c76ad64 libcoreclr.so`SVR::GCHeap::AssignHeap(alloc_context*) [inlined] SVR::GCHeap::GetHeap(n=23) at gc.cpp:44898
    frame #7: 0x00007fb35c76ad56 libcoreclr.so`SVR::GCHeap::AssignHeap(acontext=0x0000560354caad88) at gc.cpp:44891
    frame #8: 0x00007fb35c76abb7 libcoreclr.so`SVR::GCHeap::Alloc(this=<unavailable>, context=0x0000560354caad88, size=8184, flags=66) at gc.cpp:43628
    frame #9: 0x00007fb35c638877 libcoreclr.so`AllocateSzArray(MethodTable*, int, GC_ALLOC_FLAGS) at gchelpers.cpp:228
    frame #10: 0x00007fb35c63880f libcoreclr.so`AllocateSzArray(pArrayMT=<unavailable>, cElements=1020, flags=66) at gchelpers.cpp:0
    frame #11: 0x00007fb35c4a9ae8 libcoreclr.so`PinnedHeapHandleTable::AllocateHandles(unsigned int) at appdomain.cpp:150
    frame #12: 0x00007fb35c4a9ac4 libcoreclr.so`PinnedHeapHandleTable::AllocateHandles(this=0x0000560354cee3b0, nRequested=<unavailable>) at appdomain.cpp:454
    frame #13: 0x00007fb35c4aad29 libcoreclr.so`BaseDomain::AllocateObjRefPtrsInLargeTable(this=0x0000560354c91e70, nRequested=<unavailable>, ppLazyAllocate=0x00007fb2e33a4620) at appdomain.cpp:896
    frame #14: 0x00007fb35c4abbc5 libcoreclr.so`SystemDomain::LoadBaseSystemClasses(this=<unavailable>) at appdomain.cpp:1454
    frame #15: 0x00007fb35c4ab80d libcoreclr.so`SystemDomain::Init(this=0x00007fb35cb29940) at appdomain.cpp:1266
    frame #16: 0x00007fb35c8f7d3c libcoreclr.so`EEStartupHelper() at ceemain.cpp:990
    frame #17: 0x00007fb35c8f7149 libcoreclr.so`EEStartup() [inlined] EEStartup(this=<unavailable>, p=<unavailable>)::$_0::operator()(void*) const at ceemain.cpp:1153
    frame #18: 0x00007fb35c8f704c libcoreclr.so`EEStartup() at ceemain.cpp:1155
    frame #19: 0x00007fb35c8f6fad libcoreclr.so`EnsureEEStarted() at ceemain.cpp:321
    frame #20: 0x00007fb35c4f47ae libcoreclr.so`CorHost2::Start(this=0x0000560354bf8530) at corhost.cpp:101
    frame #21: 0x00007fb35c4a7ce0 libcoreclr.so`::coreclr_initialize(exePath=<unavailable>, appDomainFriendlyName=<unavailable>, propertyCount=11, propertyKeys=<unavailable>, propertyValues=<unavailable>, hostHandle=0x00007ffd586d78a8, domainId=0x00007ffd586d78a4) at unixinterface.cpp:275
    frame #22: 0x00007fb35de1866f libhostpolicy.so`___lldb_unnamed_symbol77$$libhostpolicy.so + 783
    frame #23: 0x00007fb35de28ba1 libhostpolicy.so`___lldb_unnamed_symbol167$$libhostpolicy.so + 385
    frame #24: 0x00007fb35de2845a libhostpolicy.so`corehost_main + 154
    frame #25: 0x00007fb35de81c14 libhostfxr.so`___lldb_unnamed_symbol94$$libhostfxr.so + 1812
    frame #26: 0x00007fb35de80349 libhostfxr.so`___lldb_unnamed_symbol92$$libhostfxr.so + 665
    frame #27: 0x00007fb35de7b93b libhostfxr.so`hostfxr_main_startupinfo + 171
    frame #28: 0x00005603533c6a25 program`___lldb_unnamed_symbol157$$program + 1045
    frame #29: 0x00005603533c6ef0 program`___lldb_unnamed_symbol158$$program + 144
    frame #30: 0x00007fb35cb8bc87 libc.so.6`__libc_start_main(main=(program`___lldb_unnamed_symbol158$$program), argc=1, argv=0x00007ffd586d7e48, init=<unavailable>, fini=<unavailable>, rtld_fini=<unavailable>, stack_end=0x00007ffd586d7e38) at libc-start.c:310
    frame #31: 0x00005603533bad7a program`___lldb_unnamed_symbol33$$program + 41
```

</details>

<details>
<summary>GDB backtrace</summary>

```
(gdb) bt
#0  0x00007fb35dab032a in __waitpid (pid=13187, stat_loc=0x7fb35dee2dbc, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  0x00007fb35c9463a1 in PROCCreateCrashDump (argv=...) at /__w/1/s/src/coreclr/pal/src/thread/process.cpp:3276
#2  PROCCreateCrashDumpIfEnabled (signal=<optimized out>, siginfo=0x7fb35dee34b0) at /__w/1/s/src/coreclr/pal/src/thread/process.cpp:3463
#3  0x00007fb35c90f1db in invoke_previous_action (action=<optimized out>, code=11, siginfo=0x7fb35dee34b0, context=0x7fb35dee3380, signalRestarts=<optimized out>)
    at /__w/1/s/src/coreclr/pal/src/exception/signal.cpp:404
#4  0x00007fb35c90e987 in sigsegv_handler (code=11, siginfo=0x7fb35dee34b0, context=0x7fb35dee3380) at /__w/1/s/src/coreclr/pal/src/exception/signal.cpp:611
#5  <signal handler called>
#6  0x00007fb35c76ad64 in SVR::GCHeap::GetHeap (n=23) at /__w/1/s/src/coreclr/gc/gc.cpp:44898
#7  SVR::GCHeap::AssignHeap (acontext=0x560354caad88) at /__w/1/s/src/coreclr/gc/gc.cpp:44891
#8  0x00007fb35c76abb7 in SVR::GCHeap::Alloc (this=<optimized out>, context=0x560354caad88, size=8184, flags=66) at /__w/1/s/src/coreclr/gc/gc.cpp:43628
#9  0x00007fb35c638877 in Alloc (size=8184, flags=66) at /__w/1/s/src/coreclr/vm/gchelpers.cpp:228
#10 0x00007fb35c638877 in AllocateSzArray (pArrayMT=<optimized out>, cElements=1020, flags=66) from /program/libcoreclr.so
#11 0x00007fb35c4a9ae8 in PinnedHeapHandleBucket::PinnedHeapHandleBucket (this=0x560354cf2940, Size=1020, pDomain=0x560354c91e70, pNext=<optimized out>)
    at /__w/1/s/src/coreclr/vm/appdomain.cpp:150
#12 PinnedHeapHandleTable::AllocateHandles (this=0x560354cee3b0, nRequested=<optimized out>) at /__w/1/s/src/coreclr/vm/appdomain.cpp:454
#13 0x00007fb35c4aad29 in BaseDomain::AllocateObjRefPtrsInLargeTable (this=0x560354c91e70, nRequested=<optimized out>, ppLazyAllocate=0x7fb2e33a4620)
    at /__w/1/s/src/coreclr/vm/appdomain.cpp:896
#14 0x00007fb35c4abbc5 in SystemDomain::LoadBaseSystemClasses (this=<optimized out>) at /__w/1/s/src/coreclr/vm/appdomain.cpp:1454
#15 0x00007fb35c4ab80d in SystemDomain::Init (this=0x7fb35cb29940 <g_pSystemDomainMemory>) at /__w/1/s/src/coreclr/vm/appdomain.cpp:1266
#16 0x00007fb35c8f7d3c in EEStartupHelper () at /__w/1/s/src/coreclr/vm/ceemain.cpp:990
#17 0x00007fb35c8f7149 in EEStartup()::$_0::operator()(void*) const (this=<optimized out>, p=<optimized out>) at /__w/1/s/src/coreclr/vm/ceemain.cpp:1153
#18 EEStartup () at /__w/1/s/src/coreclr/vm/ceemain.cpp:1155
#19 0x00007fb35c8f6fad in EnsureEEStarted () at /__w/1/s/src/coreclr/vm/ceemain.cpp:321
#20 0x00007fb35c4f47ae in CorHost2::Start (this=0x560354bf8530) at /__w/1/s/src/coreclr/vm/corhost.cpp:101
#21 0x00007fb35c4a7ce0 in coreclr_initialize (exePath=<optimized out>, appDomainFriendlyName=<optimized out>, propertyCount=11, propertyKeys=<optimized out>,
    propertyValues=<optimized out>, hostHandle=0x7ffd586d78a8, domainId=0x7ffd586d78a4) at /__w/1/s/src/coreclr/dlls/mscoree/unixinterface.cpp:275
#22 0x00007fb35de1866f in ?? () from /program/libhostpolicy.so
#23 0x00007fb35de28ba1 in ?? () from /program/libhostpolicy.so
#24 0x00007fb35de2845a in corehost_main () from /program/libhostpolicy.so
#25 0x00007fb35de81c14 in ?? () from /program/libhostfxr.so
#26 0x00007fb35de80349 in ?? () from /program/libhostfxr.so
#27 0x00007fb35de7b93b in hostfxr_main_startupinfo () from /program/libhostfxr.so
#28 0x00005603533c6a25 in ?? ()
#29 0x00005603533c6ef0 in ?? ()
#30 0x00007fb35cb8bc87 in __libc_start_main (main=0x5603533c6e60, argc=1, argv=0x7ffd586d7e48, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>,
    stack_end=0x7ffd586d7e38) at ../csu/libc-start.c:310
#31 0x00005603533bad7a in ?? ()
(gdb)
```

</details>

**Comment by mangod9** [comment] 2024-05-02 21:05
This is most likely a dupe of https://github.com/dotnet/runtime/issues/67008. Assume this doesn't repro on 7 or 8? If it does please reopen

**Closed by mangod9** 2024-05-02 21:05 UTC
Labels: area-GC-coreclr, untriaged
