### ISSUE TITLE
System.Text.Json source generator fails with two nested classes of the same name

### ISSUE THREAD

**Issue by CollinAlpert** [dotnet/runtime#75926] opened 2022-09-20 20:16 UTC
### Description

The SG for the `JsonSerializerContext` fails to generate if multiple classes specified by the `JsonSerializableAttribute` have nested classes with the same name.

### Reproduction Steps

```csharp
using System.Text.Json.Serialization;

namespace Test;

public class CreateTicketRequest
{
    public IReadOnlyList<Model> Models { get; set; }

    public class Model
    {
    }
}

public class UpdateTicketRequest
{
    public IReadOnlyList<Model> Models { get; set; }
	
    public class Model
    {
    }
}



[JsonSerializable(typeof(CreateTicketRequest))]
[JsonSerializable(typeof(UpdateTicketRequest))]
partial class JsonContext : JsonSerializerContext
{
}
```

### Expected behavior

The project compiles and `JsonTypeInfo` is generated for all classes.

### Actual behavior

The build fails with `Argument 2: cannot convert from 'System.Collections.Generic.IReadOnlyList<Test.UpdateTicketRequest.Model>' to 'System.Collections.Generic.IReadOnlyList<Test.CreateTicketRequest.Model>?'`

### Regression?

I reproduced this in .NET 6 as well as .NET 7 RC1.

### Known Workarounds

Rename one of the nested classes.

### Configuration

.NET 7.0.100-rc.1.22431.12
macOS 12.5.1 with Apple Silicon

### Other information

I found https://github.com/dotnet/runtime/issues/72671 which might have something to do with this, however my usage and error message is different.

**Comment by eiriktsarpalis** [comment] 2022-09-21 11:30
Duplicate of #58198. Per feedback in https://github.com/dotnet/runtime/issues/58198#issuecomment-907350706 you can use the  `JsonSerializableAttribute.TypeInfoPropertyName` property to resolve any naming conflicts.

**Closed by eiriktsarpalis** 2022-09-21 11:30 UTC
Labels: area-System.Text.Json, untriaged
