### ISSUE TITLE
IL3050 IL2026 analyzers ignores EnableConfigurationBindingGenerator property

### ISSUE THREAD

**Issue by bdovaz** [dotnet/runtime#97204] opened 2024-01-18 12:58 UTC
Context:

https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8#configuration-binding-source-generator

Having these properties:

```
<PropertyGroup>
  <IsAotCompatible>true</IsAotCompatible>
  <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
  <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
</PropertyGroup>
```

And this code:

```
internal static void AddConfiguration(this IServiceCollection services, IConfiguration configuration)
{
    services.Configure<MyOptions>(configuration.GetSection("Configuration"));
}
```

It tells me the following errors:

```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	IL2026	Using member 'Microsoft.Extensions.DependencyInjection.OptionsConfigurationServiceCollectionExtensions.Configure<TOptions>(IServiceCollection, IConfiguration)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. TOptions's dependent types may have their members trimmed. Ensure all required members are preserved.
```

![image](https://github.com/dotnet/linker/assets/950602/4afb9236-02c8-4d42-a456-2929fd12ff42)

Running:

```
dotnet format --no-restore --severity info --verbosity diagnostic
```

It adds:

```csharp
[RequiresUnreferencedCode("Calls Microsoft.Extensions.DependencyInjection.OptionsConfigurationServiceCollectionExtensions.Configure<TOptions>(IConfiguration)")]
[RequiresDynamicCode("Calls Microsoft.Extensions.DependencyInjection.OptionsConfigurationServiceCollectionExtensions.Configure<TOptions>(IConfiguration)")]
```

**EXPECTED:**

By having `EnableConfigurationBindingGenerator` set to `true` I should not get those errors, in fact, in compilation I do not get anay analyzer warnings/errors, only when executing the `dotnet format` command.

**Comment by tarekgh** [comment] 2024-01-19 17:10
This is a duplicate of https://github.com/dotnet/runtime/issues/94544.

CC @eerhardt @ericstj

**Closed by tarekgh** 2024-01-19 17:10 UTC
Labels: area-Extensions-Configuration
