### ISSUE TITLE
NTLM authentication not working in Linux based environment

### ISSUE THREAD

**Issue by jondoe69420** [dotnet/runtime#101058] opened 2024-04-15 15:17 UTC
### Description

I need to send an http request to a server which uses Windows authentication. I wrote the following code to try and send just any request to my server.

```c#
var handler = new HttpClientHandler 
{
    PreAuthenticate = true,
    UseProxy = false,
    UseDefaultCredentials = false,
    Credentials = new CredentialCache
    {
        {
            new Uri("http://otherapi"), "Negotiate", new NetworkCredential("username", "password")
        }
    }
}

using var client = new HttpClient(handler);
var stringContent = new StringContent("{}", Encoding.UTF8, "application/json");
using var request = new HttpRequestMessage(HttpMethod.Post, "http://otherapi/api/endpoint");
request.Content = stringContent;
using var res = await client.SendAsync(request);
Console.WriteLine($"{res.StatusCode}");
```

When running the above code on a Windows machine, everything works as expected, and `BadRequest` gets printed to the console ( which is what I expect to happen when sending an invalid json request ).

The problem is, I need to run this code on a Linux based machine, and when running it on an Ubuntu 22 machine (as well as the official aspnet docker image),  it fails and prints out to the console `Unauthorized`, which means the windows authentication didn't work.

I also tried it with 
```c#
Credentials = new CredentialCache
    {
        {
            new Uri("http://otherapi"), "NTLM", new NetworkCredential("username", "password")
        }
    }
```

with no success.

I opened up Wireshark on my windows machine to try and figure out whats going on. I saw that the client initially sends a POST request to the server, and then the server responds with a `401`, and the following headers

```
WWW-Authenticate: Negotiate
WWW-Authenticate: NTLM
```

After that I saw that the client sent the same request again, this time with an `Authorization` header, which from what I understand, is the correct behaviour. After that the request continues as expected.

The problem is, when I open Wireshark on my Ubuntu machine, I see that after the server responded with the first 401, the client just stops sending requests for some reason.

### Reproduction Steps

Run the following code in a Linux machine 

```c#
var handler = new HttpClientHandler 
{
    PreAuthenticate = true,
    UseProxy = false,
    UseDefaultCredentials = false,
    Credentials = new CredentialsCache
    {
        {
            new Uri("http://otherapi"), "Negotiate", new NetworkCredential("username", "password")
        }
    }
}

using var client = new HttpClient(handler);
var stringContent = new StringContent("{}", Encoding.UTF8, "application/json");
using var request = new HttpRequestMessage(HttpMethod.Post, "http://otherapi/api/endpoint");
request.Content = stringContent;
using var res = await client.SendAsync(request);
Console.WriteLine($"{res.StatusCode}");
```

### Expected behavior

`BadRequest` printed out on both Linux and Windows

### Actual behavior

`Unauthorized` printed out on Linux,
`BadRequest` printed out on Windows.

### Configuration

I tried both .NET 7 and .NET 8

Ran on Windows 10
Linux was ran on Ubuntu 22 and the official aspnet docker image

**Comment by jondoe69420** [comment] 2024-04-15 16:11
After digging a little deeper, I read online that on Linux, dotnet uses libcurl under the hood. I tried the running the following on my Ubuntu machine

```
curl  --negotiate -u username:password http://otherapi --data '' -i --verbose
```

I got a 401, and looking at the output I saw the line 

```
gss_ini_sec_context(): failed: No credentials were supplied, or the credentials were unavailable or inaccessible. SPNEGO cannot find mechanisms to negotiate.
```

So I changed the command to

```
curl  --ntlm -u username:password http://otherapi --data '' -i
```

And that seemed to work, I got back a 403 Forbidden.

**Comment by huoyaoyuan** [comment] 2024-04-15 18:47
> I read online that on Linux, dotnet uses libcurl under the hood.

It was used for early versions. Higher versions manipulate raw sockets directly.

I believe NTLM is just unimplemented as a Windows-only scheme.

**Comment by jondoe69420** [comment] 2024-04-16 07:23
@huoyaoyuan So there is no support for NTLM authentication in .NET on Linux?

**Comment by huoyaoyuan** [comment] 2024-04-16 07:49
> So there is no support for NTLM authentication in .NET on Linux?

I guess. Please confirm with official response from network team.

**Comment by MihaZupan** [comment] 2024-04-23 09:49
Do you see the same behavior if you enable `AppContext.SetSwitch("System.Net.Security.UseManagedNtlm", true);`?

If so, can you run your repro project with debug-level tracing enabled, like shown in https://github.com/dotnet/runtime/issues/100231#issuecomment-2049541268?

**Comment by rzikm** [comment] 2024-04-23 10:07
> I believe NTLM is just unimplemented as a Windows-only scheme.

NTLM is supported on linux/OSX via libgssapi

Testing with `UseManagedNtlm` sounds like a good step for debugging. Additionally, it would be great if you collected and shared with us packet captures.

cc @filipnavara

**Comment by filipnavara** [comment] 2024-04-23 10:33
The official documentation states that the gss-ntlmssp package must be installed on the system. The error above (`SPNEGO cannot find mechanisms to negotiate.`) is consistent with the package not being installed. Furthermore, on Ubuntu 22.04 there's a conflict between the gss-ntlmssp package and OpenSSL 3 configuration that was already discussed multiple times in other issues (eg. https://github.com/dotnet/runtime/issues/67353#issuecomment-2062210418). I am not familiar with the official docker images and whether they include the OpenSSL 3 workarounds/fixes.

Trying `System.Net.Security.UseManagedNtlm` is a reasonable workaround too...

**Comment by wfurt** [comment] 2024-04-23 16:01
Note that the `gss-ntlmssp` is fixed/updated in Ubuntu 23+. One option is to upgrade or use different distribution as base OS.

**Comment by amitpatel158** [comment] 2024-04-24 01:42
Encountered similar issue while using NTLM Authentication for http proxy.
Used named `HttpClient` with
`HttpClientHandler` &
`WebProxy` (Populated Address & Credentials properties only)

Error: HttpRequestException:
The proxy tunnel request to proxy 'http://xxxxxxxxx:xxxx/'
failed with status code '407'"

Base os: RHEL-8 Minimal (linux)
Application: NET8 based
MicroService
After applying workaround
`System.Net.Security.UseManagedNtim` It worked as expected

**Comment by filipnavara** [comment] 2024-05-11 11:20
> is perhaps the desired state going forward

The managed NTLM only implements the client-side part. That's not necessarily desirable on Linux. I am hesitant to make it the default everywhere non-Windows but not completely ruling it out either.

**Comment by wfurt** [comment] 2024-05-21 01:32
I'm wondering if the switch may be smarter and for example detect cases when the NTLM gssapi module is missing or not functional (because of  OpneSSL 3) Since NTLM is really not that secure and considered legacy, I'm not sure either if we should flip the switch as it can possibly impact Kerberos as well. (I could be wrong but the test coverage is somewhat weak IMHO). 


 And is there good place where we can put some remarks about this @rzikm and @filipnavara. I certainly feel we can document the option better and outline some of the caveats more - but I just don't know where to put it.

**Comment by antonfirsov** [comment] 2024-05-21 17:07
Triage: marking as documentation issue for 9.0 based on https://github.com/dotnet/runtime/issues/101058#issuecomment-2121535782, otherwise it looks like a duplicate of #100231.

**Comment by GuyOrShay** [comment] 2024-07-04 06:55
Hi , there is any updates ?

**Comment by wfurt** [comment] 2024-07-12 00:13
what is your specific issue @GuyOrShay ? There are several workarounds here and this documentation only issue at this point.

**Closed** 2024-09-12 07:35 UTC
Labels: documentation, area-System.Net.Http
