### ISSUE TITLE
AssemblyLoadContext failed to unload assembly

### ISSUE THREAD

**Issue by JasonGLYao** [dotnet/runtime#76809] opened 2022-10-10 08:37 UTC
### Description

we want to utilize the feature of uload in AssemblyLoadContext ,we tried the  [sample](https://github.com/dotnet/samples/tree/main/core/tutorials/Unloading) and it works fine（the plugin assembly can be unloaded）,but if we use System.Text.Json to serialize an object in plugin, then the plugin assembly can not be unloaded any more.  

### Reproduction Steps

- using the source code attachment which downloaded and changed  from the sample code [site](https://github.com/dotnet/samples/tree/main/core/tutorials/Unloading) 

- Compile and run the host.exe 

-  using dotnet-counters to monitor the program ,pay attention to the Number of  Assemblies Loaded in the dotnet-counters terminal.

### Expected behavior

Number of  Assemblies Loaded in dotnet-counters does not increase 

### Actual behavior

Number of  Assemblies Loaded in dotnet-counters  increase until the Host.exe being terminated.

### Regression?

Netcore3.1,Net6 Both with this issue

[Unloading.zip](https://github.com/dotnet/runtime/files/9744439/Unloading.zip)

**Comment by JasonGLYao** [comment] 2022-10-10 08:52
@jeffschwMSFT

**Comment by teo-tsirpanis** [comment] 2022-10-10 09:01
Duplicate of #65323.

**Closed by teo-tsirpanis** 2022-10-10 09:01 UTC
Labels: area-System.Text.Json, untriaged
