### ISSUE TITLE
Test failure: JIT/Regression/JitBlue/Runtime_55253/Runtime_55253/Runtime_55253.cmd

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#107891] opened 2024-09-16 21:30 UTC
pipeline: runtime-coreclr pgostress
job: coreclr windows x64 Checked fullpgo @ Windows.10.Amd64.Open

https://dev.azure.com/dnceng-public/public/_build/results?buildId=808493&view=ms.vss-test-web.build-test-results-tab&runId=20908614&paneView=debug&resultId=120202

```
set DOTNET_TieredCompilation=1
set DOTNET_ReadyToRun=0
set DOTNET_TC_QuickJitForLoops=1
set DOTNET_TieredPGO=1
set DOTNET_JitProfileCasts=1
```

```
07:57:25.840 Running test: JIT/Regression/JitBlue/Runtime_55253/Runtime_55253/Runtime_55253.cmd
Fatal error. Internal CLR error. (0x80131506 (COR_E_EXECUTIONENGINE))
   at System.Runtime.CompilerServices.RuntimeHelpers.DispatchTailCalls(IntPtr, Void (IntPtr, Byte ByRef, System.Runtime.CompilerServices.PortableTailCallFrame*), Byte ByRef)
   at System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.GetPinnableReference(System.String)
   at System.Diagnostics.Tracing.EventPipeInternal.CreateProvider(System.String, Void (Byte*, Int32, Byte, Int64, Int64, EVENT_FILTER_DESCRIPTOR*, Void*), Void*)
   at System.Diagnostics.Tracing.EventPipeEventProvider.Register(System.Guid, System.String)
   at System.Runtime.CompilerServices.RuntimeHelpers.DispatchTailCalls(IntPtr, Void (IntPtr, Byte ByRef, System.Runtime.CompilerServices.PortableTailCallFrame*), Byte ByRef)
   at System.Diagnostics.Tracing.EventProvider.Register(System.Guid, System.String)
   at System.Diagnostics.Tracing.EventSource.Initialize(System.Guid, System.String, System.String[])
   at System.Runtime.CompilerServices.RuntimeHelpers.DispatchTailCalls(IntPtr, Void (IntPtr, Byte ByRef, System.Runtime.CompilerServices.PortableTailCallFrame*), Byte ByRef)
   at System.Diagnostics.Tracing.EventSource..ctor(System.Guid, System.String)
   at System.Diagnostics.Tracing.NativeRuntimeEventSource..ctor()
   at System.Diagnostics.Tracing.NativeRuntimeEventSource..cctor()
   at System.Diagnostics.Tracing.EventSource.InitializeDefaultEventSources()

Return code:      1
Raw output file:      C:\h\w\A3850890\w\96C50812\uploads\JitBlue\Runtime_55253\Runtime_55253\output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\A3850890\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  Runtime_55253.dll 
Expected: 100
Actual: -1073741819
```

**Comment by v-wenyuxu** [comment] 2024-09-18 08:01
**Failed in:** [runtime-coreclr pgostress 20240913.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=808493&view=ms.vss-test-web.build-test-results-tab&runId=20908614&resultId=120202&paneView=debug)

**Failed tests:**
```
coreclr windows x64 Checked fullpgo @ Windows.10.Amd64.Open
    - JIT/Regression/JitBlue/Runtime_55253/Runtime_55253/Runtime_55253.cmd
```

**Error message:**
```
 Fatal error. Internal CLR error. (0x80131506 (COR_E_EXECUTIONENGINE))
   at System.Runtime.CompilerServices.RuntimeHelpers.DispatchTailCalls(IntPtr, Void (IntPtr, Byte ByRef, System.Runtime.CompilerServices.PortableTailCallFrame*), Byte ByRef)
   at System.Runtime.InteropServices.Marshalling.Utf16StringMarshaller.GetPinnableReference(System.String)
   at System.Diagnostics.Tracing.EventPipeInternal.CreateProvider(System.String, Void (Byte*, Int32, Byte, Int64, Int64, EVENT_FILTER_DESCRIPTOR*, Void*), Void*)
   at System.Diagnostics.Tracing.EventPipeEventProvider.Register(System.Guid, System.String)
   at System.Runtime.CompilerServices.RuntimeHelpers.DispatchTailCalls(IntPtr, Void (IntPtr, Byte ByRef, System.Runtime.CompilerServices.PortableTailCallFrame*), Byte ByRef)
   at System.Diagnostics.Tracing.EventProvider.Register(System.Guid, System.String)
   at System.Diagnostics.Tracing.EventSource.Initialize(System.Guid, System.String, System.String[])
   at System.Runtime.CompilerServices.RuntimeHelpers.DispatchTailCalls(IntPtr, Void (IntPtr, Byte ByRef, System.Runtime.CompilerServices.PortableTailCallFrame*), Byte ByRef)
   at System.Diagnostics.Tracing.EventSource..ctor(System.Guid, System.String)
   at System.Diagnostics.Tracing.NativeRuntimeEventSource..ctor()
   at System.Diagnostics.Tracing.NativeRuntimeEventSource..cctor()
   at System.Diagnostics.Tracing.EventSource.InitializeDefaultEventSources()

Return code:      1
Raw output file:      C:hwA3850890w96C50812uploadsJitBlueRuntime_55253Runtime_55253output.txt
Raw output:
BEGIN EXECUTION
 "C:hwA3850890pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  Runtime_55253.dll 
Expected: 100
Actual: -1073741819
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:cores since 9/14/2024 7:57:25 AM
Processing C:corescorerun.exe.21420.dmp
Invoking: C:Program Files (x86)Windows Kits10Debuggersdcdb.exe -c "$<C:hwA3850890		mptx0cwe.tmp" -z "C:corescorerun.exe.21420.dmp"
stdout: 
Microsoft (R) Windows Debugger Version 10.0.18362.1 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:corescorerun.exe.21420.dmp]
User Mini Dump File with Full Memory: Only application data is available


************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:hwA3850890pPDB
Symbol search path is: C:hwA3850890pPDB
Executable search path is: 
Windows 10 Version 14393 MP (4 procs) Free x64
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.6343 (rs1_release.230913-1727)
Machine Name:
Debug session time: Sat Sep 14 07:57:28.000 2024 (UTC + 0:00)
System Uptime: 0 days 0:40:56.725
Process Uptime: 0 days 0:00:02.000
..........................

************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  The system cannot find the file specified

You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.sympath) is correct.
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(53ac.53b8): Access violation - code c0000005 (first/second chance not available)
For analysis of this file, run !analyze -v
*** WARNING: Unable to verify checksum for coreclr.dll
coreclr!TypeDesc::GetInternalCorElementType [inlined in coreclr!SigPointer::HasCustomModifier+0x218]:
00007ffe`869f13d8 0fb608          movzx   ecx,byte ptr [rax] ds:fd000000`7ffe2771=??
0:000> cdb: Reading initial command '$<C:hwA3850890		mptx0cwe.tmp'
0:000> .load C:Users
unner.dotnetsossos.dll
0:000> ~*k

.  0  Id: 53ac.53b8 Suspend: 0 Teb: 0000002e`fda2b000 Unfrozen
Child-SP          RetAddr       
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 128
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor552|0_553(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by EgorBo** [comment] 2024-09-18 22:38
Seems like the same issue as https://github.com/dotnet/runtime/issues/107892 (that one also fails in tail calls)

**Comment by BruceForstall** [comment] 2024-09-24 18:25
Also,

https://dev.azure.com/dnceng-public/public/_build/results?buildId=817147&view=ms.vss-test-web.build-test-results-tab&runId=21196090&paneView=debug&resultId=211181

**Comment by jkotas** [comment] 2024-10-07 12:28
Duplicate of #108586

**Closed by jkotas** 2024-10-07 12:28 UTC
Labels: os-windows, JitStress, arch-x64, area-CodeGen-coreclr
