### ISSUE TITLE
In .net 5, When timeout happens, HttpClient throws TaskCaneledException. But the innerException is IOException instead of TimeoutException

### ISSUE THREAD

**Issue by arisewanggithub** [dotnet/runtime#49115] opened 2021-03-04 05:24 UTC
Based on .net 5 document, when timeout happens, HttpClient should throw TaskCanceledException. And the InnerException should be a TimeoutException. But I'm receiving IOException as the InnerException instead. Any reason why this can happen?

**Comment by karelz** [comment] 2021-03-04 07:46
@arisewanggithub can you post the full exception here? Do you have a repro, how often does it happen?

**Comment by arisewanggithub** [comment] 2021-03-04 07:52
Here is the stack trace:
at System.Net.Http.HttpConnection.d__56.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Net.Http.HttpConnectionPool.d__72.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Net.Http.RedirectHandler.d__4.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Net.Http.DiagnosticsHandler.d__5.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at Client.HttpMessageHandlers.RequestTimeoutHandler.d__5.MoveNext()

The RequestTimeoutHandler is an delegating handler we wrote to detect request timeout.
The exception message is: The operation was canceled.

Here is the stack trace info for the InnerException:
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
at System.Net.Http.HttpConnection.d__97.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Net.Http.HttpConnection.RawConnectionStream.d__6.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Net.Security.SslStream.d__181`1.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Net.Http.HttpConnection.d__94.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Net.Http.HttpConnection.d__91.MoveNext()
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Net.Http.HttpConnection.d__56.MoveNext()

Here is the error message for the InnerException:
Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..

This exception is thrown every time timeout happens. I can use fiddler to set send mock response and set response delay. Every time it throws this exception.

**Comment by ManickaP** [comment] 2021-03-04 09:59
@arisewanggithub  could you also post a code causing this? I don't see `HttpClient` on the call stack.

**Comment by arisewanggithub** [comment] 2021-03-04 16:07
@ManickaP, the exception is captured in the delegating handler. So the stack trace in the exception is only including the stack up until the delegating handler.
The httpClient call is just one statement. I can paste it here:
response = await _httpClient.SendAsync(httpRequestMessage, cancellationToken);

I can also paste the code how httpClient is registered:
var httpClientBuilder = services.AddHttpClient<TInterface, TImplementation>()
	.ConfigureHttpClient((httpClient) =>
	{
		httpClient.Timeout = TimeSpan.FromSeconds(timeoutInSeconds);
	})
	.ConfigurePrimaryHttpMessageHandler(() =>
	{
		var httpClientHandler = new HttpClientHandler();
		httpClientHandler.MaxConnectionsPerServer = maxConnectionsPerServer;
		return new RequestTimeoutHandler(timeoutInSeconds) { InnerHandler = httpClientHandler };
	});

var retryPolicy = HttpPolicyExtensions.HandleTransientHttpError()
		.Or<SocketException>()
		.WaitAndRetryAsync(
			networkPolicy.RetryAttempts, retryAttempt => TimeSpan.FromSeconds(retryAttempt));
	var circuitBreakerPolicy = HttpPolicyExtensions.HandleTransientHttpError()
		.AdvancedCircuitBreakerAsync(
			breakerFailureThreshold,
			TimeSpan.FromSeconds(breakerSamplingDurationInSeconds),
			breakerMinimumThroughput,
			TimeSpan.FromSeconds(breakerOpenDurationInSeconds),
			onBreak: (response, timespan, context) =>
			{
			},
			onReset: (context) =>
			{
			},
			onHalfOpen: () =>
			{
			});
	var noOpPolicy = Policy.NoOpAsync().AsAsyncPolicy<HttpResponseMessage>();

	httpClientBuilder.AddPolicyHandler((policyRegistry, httpRequestMessage) =>
	{
		if (httpRequestMessage.Method == HttpMethod.Get || httpRequestMessage.Method == HttpMethod.Delete || httpRequestMessage.Method == HttpMethod.Put || httpRequestMessage.Method == HttpMethod.Post)
		{
			return retryPolicy;
		}
		else
		{
			return noOpPolicy;
		}
	});

	httpClientBuilder.AddPolicyHandler(circuitBreakerPolicy);

**Comment by ManickaP** [comment] 2021-03-04 16:24
> the exception is captured in the delegating handler.

That's probably the root cause of this if I get it right. The mapping of the inner exception to `TimeoutException` is done on `HttpClient` level:
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs#L586-L591

So if you're catching it in the handler somewhere down the handler chain, you will not get the timeout.

**Comment by arisewanggithub** [comment] 2021-03-04 16:39
@ManickaP , I think you are right. If I capture the exception outside of httpClient.SendAsync, then the InnerException is TimeoutException. Seems this is a restriction that is not documented in the .net doc. Thanks for the clarification!

**Comment by ManickaP** [comment] 2021-03-04 17:22
The timeout is a property of `HttpClient` and the docs mention the exception on `HttpClient` methods; neither on `HttpMessageHandler` nor `SocketsHttpHandler`. But I do admit this distinction is low-level and might cause misunderstanding.

I hope the explanation helped you. I'll close the issue for now. Feel free to reopen if needed.

**Closed by ManickaP** 2021-03-04 17:22 UTC
Labels: area-System.Net.Http, untriaged
