### ISSUE TITLE
[tests][wasm] System.Text.RegularExpressions PrecompiledRegex_MatchesTest Assert Equal failure

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#66033] opened 2022-03-01 21:55 UTC
```
[FAIL] System.Text.RegularExpressions.Tests.PrecompiledRegexScenarioTest.PrecompiledRegex_MatchesTest
Assert.Equal() Failure
                                 ↓ (pos 27)
Expected: ···success1245something\r
Actual:   ···success1245something
                                 ↑ (pos 27)
   at System.Text.RegularExpressions.Tests.PrecompiledRegexScenarioTest.PrecompiledRegex_MatchesTest() in /_/src/libraries/System.Text.RegularExpressions/tests/PrecompiledRegexScenarioTest.cs:line 36
   at System.Reflection.RuntimeMethodInfo.InvokeWorker(Object obj, BindingFlags invokeAttr, Span`1 parameters) in /_/src/mono/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.Mono.cs:line 386
```
Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1636124&view=logs&j=92eb2883-f4d8-5bc5-c259-7b4501afdc79&t=36b9b4a8-3bbd-51f8-0fa3-810b34136031
Log: https://helix.dot.net/api/jobs/e340e6ec-054f-4c02-96ed-b4d5437df64d/workitems/normal-System.Text.RegularExpressions.Tests?api-version=2019-06-17

**Comment by stephentoub** [comment] 2022-03-01 22:05
Duplicate of https://github.com/dotnet/runtime/issues/65978

**Closed by stephentoub** 2022-03-01 22:05 UTC
Labels: arch-wasm, untriaged
