### ISSUE TITLE
EventSource.Write throws System.NotSupportedException when using anonymous object that includes string array

### ISSUE THREAD

**Issue by christian-clausen** [dotnet/runtime#29009] opened 2019-03-19 15:15 UTC
UPDATE: I forgot to mention that I see this as a quite critical issue, because tracing may lead to application crash when someone begins observing.

With NuGet package Microsoft.NETCore.UniversalWindowsPlatform version 6.2.8, we get the following exception:

```
    System.NotSupportedException: Arrays of null-terminated string are not supported
```

when we run this code:

```csharp
    var log = new EventSource("Observito-Test-Tack");
    log.Write("Msg", new EventSourceOptions() { Level = EventLevel.Informational, Opcode = EventOpcode.Info },
        new
        {
            Strings = new[]
                {
                    "Foo",
                    "Bar"
                }
        });
```

With NuGet package Microsoft.NETCore.UniversalWindowsPlatform version 6.1.9 we did not get this exception.

The problem also only appears when someone is listening for events of this EventSource. 

## Steps to reproduce

A minimal repro is available here: https://github.com/observito/StringArrayTraceRepro.

1. Set breakpoint in exception block of ```ArrayRepro.Reproduce```
1. Run App1 (Local Machine)
1. Observe that no exception is thrown
1. Run the following from a command-line as administrator (The Guid corresponding to 
     ```Observito-Test-Tack``` is ```{53487b38-863e-5b17-bdce-7b706a2e81a6}```):
```logman start test_trace -p {53487b38-863e-5b17-bdce-7b706a2e81a6} -ets```  
1. Run App1 again
1. Notice that an exception is thrown
1. Downgrade NuGet package Microsoft.NETCore.UniversalWindowsPlatform to version 6.1.9
1. UPDATE: Restart computer
1. Repeat the test above
1. Notice that now no exception is thrown

**Comment by josalem** [comment] 2020-11-07 01:15
@davmason would your 5.0 work fix this as well?

**Comment by davmason** [comment] 2020-11-07 01:58
No, this is a dupe of #10428

**Closed by davmason** 2020-11-07 01:58 UTC
Labels: area-System.Diagnostics.Tracing, bug
