### ISSUE TITLE
Test failure readytorun/determinism/crossgen2determinism/crossgen2determinism.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#66275] opened 2022-03-07 01:56 UTC
Run: [runtime-coreclr jitstress-isas-x86 20220305.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1647092&view=ms.vss-test-web.build-test-results-tab&runId=45496552&resultId=110944&paneView=debug)

Failed test:
```
CoreCLR Linux x64 Checked jitstress_isas_2_x86_nosse2 @ Ubuntu.1804.Amd64.Open

- readytorun/determinism/crossgen2determinism/crossgen2determinism.sh
- JIT/Performance/CodeQuality/Roslyn/CscBench/CscBench.sh
- profiler/eventpipe/eventpipe/eventpipe.sh
- baseservices/TieredCompilation/BasicTestWithMcj/BasicTestWithMcj.sh
- JIT/Directed/debugging/debuginfo/tester/tester.sh
- tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.sh
- tracing/eventpipe/gcdump/gcdump/gcdump.sh
- JIT/HardwareIntrinsics/General/Vector128_1/Vector128_1_ro/Vector128_1_ro.sh
- readytorun/tests/mainv2/mainv2.sh
- JIT/HardwareIntrinsics/General/Vector256_1/Vector256_1_ro/Vector256_1_ro.sh
- JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.sh
- readytorun/tests/mainv1/mainv1.sh
- readytorun/crossgen2/crossgen2smoke/crossgen2smoke.sh
- Interop/NativeLibrary/AssemblyLoadContext/ResolveUnmanagedDllTests/ResolveUnmanagedDllTests.sh
- Interop/NativeLibrary/Callback/CallbackStressTest_TargetUnix/CallbackStressTest_TargetUnix.sh
- GC/LargeMemory/API/gc/keepalive/keepalive.sh
- GC/LargeMemory/API/gc/gettotalmemory/gettotalmemory.sh
- readytorun/crossgen2/crossgen2smoke_donotalwaysusecrossgen2/crossgen2smoke_donotalwaysusecrossgen2.sh

CoreCLR windows x64 Checked jitstress_isas_x86_nosse2 @ Windows.10.Amd64.Open

- JIT\\Performance\\CodeQuality\\Roslyn\\CscBench\\CscBench.cmd
- readytorun\\determinism\\crossgen2determinism\\crossgen2determinism.cmd
- Interop\\COM\\Dynamic\\Dynamic\\Dynamic.cmd
- baseservices\\TieredCompilation\\BasicTestWithMcj\\BasicTestWithMcj.cmd
- tracing\\eventpipe\\providervalidation\\providervalidation\\providervalidation.cmd
- managed\\Compilation\\Compilation\\Compilation.cmd
- tracing\\eventpipe\\buffersize\\buffersize\\buffersize.cmd

```
**Error message:**
```
Assert failure(PID 7338 [0x00001caa], Thread: 7338 [0x1caa]): Assertion failed 'IsBaselineSimdIsaSupportedDebugOnly()' in '<>c__DisplayClass5_0:<Initialize>b__0(System.String,System.Reflection.Assembly,System.Nullable`1[DllImportSearchPath]):long:this' during 'Morph - Inlining' (IL size 132; hash 0xe63efdb0; FullOpts)

File: /__w/1/s/src/coreclr/jit/gentree.cpp Line: 18174
Image: /datadisks/disk1/work/BEB709DF/p/corerun
/datadisks/disk1/work/BEB709DF/w/B1CC096E/e/readytorun/determinism/crossgen2determinism/crossgen2determinism.sh: line 164:  7338 Aborted                 (core dumped) $CORE_ROOT/corerun $CORE_ROOT/crossgen2/crossgen2.dll --map -r:$CORE_ROOT/*.dll -r:../../crossgen2/crossgen2smoke/helperdll.dll -r:../../crossgen2/crossgen2smoke/helperildll.dll -o:crossgen2smoke1.ildll ../../crossgen2/crossgen2smoke/crossgen2smoke.dll

Assert failure(PID 7350 [0x00001cb6], Thread: 7350 [0x1cb6]): Assertion failed 'IsBaselineSimdIsaSupportedDebugOnly()' in '<>c__DisplayClass5_0:<Initialize>b__0(System.String,System.Reflection.Assembly,System.Nullable`1[DllImportSearchPath]):long:this' during 'Morph - Inlining' (IL size 132; hash 0xe63efdb0; FullOpts)

File: /__w/1/s/src/coreclr/jit/gentree.cpp Line: 18174
Image: /datadisks/disk1/work/BEB709DF/p/corerun
/datadisks/disk1/work/BEB709DF/w/B1CC096E/e/readytorun/determinism/crossgen2determinism/crossgen2determinism.sh: line 166:  7350 Aborted                 (core dumped) $CORE_ROOT/corerun $CORE_ROOT/crossgen2/crossgen2.dll --map -r:$CORE_ROOT/*.dll -r:../../crossgen2/crossgen2smoke/helperdll.dll -r:../../crossgen2/crossgen2smoke/helperildll.dll -o:crossgen2smoke2.ildll ../../crossgen2/crossgen2smoke/crossgen2smoke.dll
Unhandled exception. System.IO.FileNotFoundException: Could not find file '/datadisks/disk1/work/BEB709DF/w/B1CC096E/e/readytorun/determinism/crossgen2determinism/crossgen2smoke1.ildll'.
File name: '/datadisks/disk1/work/BEB709DF/w/B1CC096E/e/readytorun/determinism/crossgen2determinism/crossgen2smoke1.ildll'
at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func2 errorRewriter) at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func2 errorRewriter)
at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Func4 createOpenException) at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Permissions openPermissions, Int64& fileLength, Permissions& filePermissions, Func4 createOpenException)
at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Permissions openPermissions, Func`4 createOpenException)
at System.IO.File.ReadAllBytes(String path)
at Program.Main()
/datadisks/disk1/work/BEB709DF/w/B1CC096E/e/readytorun/determinism/crossgen2determinism/crossgen2determinism.sh: line 284:  7362 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /datadisks/disk1/work/BEB709DF/w/B1CC096E/uploads/Reports/readytorun.determinism/crossgen2determinism/crossgen2determinism.output.txt
Raw output:
BEGIN EXECUTION
Gathering state for process 7338 corerun
Crashing thread 00001caa signal 00000006
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.7338.dmp
Written 76808192 bytes (18752 pages) to core file
Dump successfully written
Gathering state for process 7350 corerun
Crashing thread 00001cb6 signal 00000006
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.7350.dmp
Written 76697600 bytes (18725 pages) to core file
Dump successfully written
/datadisks/disk1/work/BEB709DF/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false crossgen2determinism.dll ''
Gathering state for process 7362 corer


Stack trace
   at readytorun_determinism._crossgen2determinism_crossgen2determinism_._crossgen2determinism_crossgen2determinism_sh()
```

**Comment by kunalspathak** [comment] 2022-03-07 02:32
Duplicate of https://github.com/dotnet/runtime/issues/66205

**Closed by kunalspathak** 2022-03-07 02:32 UTC
Labels: os-linux, os-windows, JitStress, arch-x64, area-crossgen2-coreclr, untriaged
