### ISSUE TITLE
System.Linq.Enumerable has special treatment of IList<T>, which should also apply to IReadOnlyList<T>

### ISSUE THREAD

**Issue by AlexVallat** [dotnet/runtime#57822] opened 2021-08-20 13:50 UTC
In several places in System.Linq.Enumerable, it checks for a more performant path by testing if the source is `IList<T>` (for example https://github.com/dotnet/runtime/blob/0f5b75344d5858d76da403735ee34c71d9d69d54/src/libraries/System.Linq/src/System/Linq/Last.cs#L76)

This should ideally also test for `IReadOnlyList<T>`, as `IList<T>` does not inherit from `IReadOnlyList<T>`, and an implementer of `IReadOnlyList<T>` is equally valid for the fast paths here.

**Comment by huoyaoyuan** [comment] 2021-08-20 14:55
https://github.com/dotnet/runtime/issues/42254

**Comment by Wraith2** [comment] 2021-08-20 15:30
from @EgorBo in https://github.com/dotnet/runtime/issues/42254#issuecomment-692964530

> I found quite a few complains or rejected attempts to optimize LINQ for IReadOnlyCollection<T>:
> 
> #28651 - LINQ results implicit support for IReadOnlyCollection
> #27517 - Performance: Make constructor List(IEnumerable collection) know about IReadOnlyCollection
> #26679 - Linq ToDictionary() should presize for IReadOnlyCollection
> #14366 - System.Linq performance improvement suggestions (mentions IROC<>)
> #24793 - Respect IReadOnlyList in the BCL
> #23910 - Add optimized path for IReadOnlyCollection/IReadOnlyList in System.Linq
> #18714 - Consider checking for IReadOnlyCollection in Enumerable.ToArray
> #27516 - Performance of LINQ .Any() - type check to leverage .Count property? (mentions IROC)
> #27517 - Performance: Make constructor List(IEnumerable collection) know about IReadOnlyCollection
dotnet/corefx#28472 - Check for IReadOnlyCollection
> #43001 - LINQ IEnumerable extension methods should add special case IReadOnlyCollection<T>

**Comment by eiriktsarpalis** [comment] 2021-08-24 09:44
Duplicate of #24793. Closing in favor of #42254.

**Closed by eiriktsarpalis** 2021-08-24 09:44 UTC
Labels: area-System.Linq, untriaged
