### ISSUE TITLE
Microsoft.Extensions.Configuration: IReadOnlyList Options with default value are not filled

### ISSUE THREAD

**Issue by drauch** [dotnet/runtime#38852] opened 2020-07-07 06:42 UTC
LABEL=area-Extensions-Configuration

# Description

When I configure the following Options class:

```
class MyOptions
{
    // Null if not in appsettings.json, otherwise values from appsettings.json
    public string[] Works1 { get; set; }
    // Null if not in appsettings.json, otherwise values from appsettings.json
    public List<string> Works2 { get; set; }
    // Null if not in appsettings.json, otherwise values from appsettings.json
    public IReadOnlyList<string> Works3 { get; set; }
    // Empty if not in appsettings.json, otherwise values from appsettings.json
    public List<string> Works4 { get; set; } = new List<string>();
    // Empty in any case
    public IReadOnlyList<string> DOES_NOT_WORK { get; set; } = new List<string>();
}
```
The DOES_NOT_WORK is not properly filled, it is always empty, even if there are values in the appsettings.json

### Configuration

.NET Framework 4.8 / Windows 10 / x64 / ASP.NET Core 2.1
(aspnetcore repo says that the Configuration package is now maintained here, which is why I'm filing the issue here, hope it's correct)

Best regards,
D.R.

**Comment by drauch** [comment] 2020-07-07 18:18
@jeffschwMSFT I think System.Collections is not the correct label, it should be area-Extensions-Configuration don't you think?

**Comment by ericstj** [comment] 2020-07-07 19:47
Interesting. So if no instance is provided it can bind but if it finds an instance then it cannot.

The problem is here:
https://github.com/dotnet/runtime/blob/4cb924de165aa8e5373a109a68611d422aa72a09/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs#L309-L346

If the instance is null then it checks the target type for [known generic interfaces](https://github.com/dotnet/runtime/blob/4cb924de165aa8e5373a109a68611d422aa72a09/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs#L227-L282), then it will instantiate it as a `List<T>`.  
https://github.com/dotnet/runtime/blob/4cb924de165aa8e5373a109a68611d422aa72a09/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs#L218-L223

However if it is already initialized, it checks the *target type* (in this case `IReadOnlyList<T>`) for only a couple known mutable interfaces:
https://github.com/dotnet/runtime/blob/4cb924de165aa8e5373a109a68611d422aa72a09/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs#L322-L345

I think the fix here would be to use `instance.GetType()` for checking against these instead of targetType.  @layomia this looks a lot like a bug I recall you fixing in the JSON serializer around a similar case.

**Comment by drauch** [comment] 2020-07-08 05:54
Thanks for analyzing this. You added the 5.x label, is there any chance such a bug is backported to 2.x if someone fixes it?

Best regards,
D.R.

**Comment by ericstj** [comment] 2020-07-08 05:59
@Pilchie + team can consider for backport.  Also, since this is a nuget package you can always independently reference the newer version and carry it with your application.

**Comment by pinkfloydx33** [comment] 2020-07-08 10:57
I ran into a similar issue the other day. If the type of the property is an `IList<T>` with a _default value_ of `T[]`, the original array is preserved and binding is "skipped". I had expected it to create a new list of the appropriate size. Consider the following class:

```csharp
public class MyClass
{
    public IList<string> MyProp { get; set; } = new[] { "ABC" };
}
```
With configuration sourced from the following json:

```json
{ 
    "MyProp": ["DEF", "GHI"]
}
```
The property is settable so I would expect the binder to overwrite it. However it preserves the original value

```csharp
var obj = new MyClass();
config.Bind(obj);
Console.WriteLine(obj.MyProp.Count); // 1
Console.WriteLine(obj.MyProp[0]); // ABC
```
This occurs because `BindCollection` is invoked for the property, which ends up throwing and *swallowing* an exception:
https://github.com/dotnet/runtime/blob/4cb924de165aa8e5373a109a68611d422aa72a09/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs#L445-L452

It throws due to calling `ICollection.Add` on the array which is obviously not implemented. This ends up needlessly binding the element as well.

I was able to get around the issue by setting the property to `null` before binding:

```csharp
var obj = new MyClass { MyProp = null };
config.Bind(obj);
Console.WriteLine(obj.MyProp.Count); // 2
Console.WriteLine(obj.MyProp[0]); // DEF
Console.WriteLine(obj.MyProp[1]); // GHI
```

This works alright if I'm manually calling `Bind` but it doesn't work otherwise. For example when calling `Configure<TOpt>(IConfiguration)` I have no control over the object. It also doesn't work if I wanted additive behavior as I'd have to *know* what the default values were so that I could *repeat* them in my configuration. (In this case I also don't control the class in question). 

If the property is instead _declared_ as `T[]` we get additive behavior

```csharp
public class MyClass
{
    public string[] MyProp { get; set; } = { "ABC" };
}

var obj = new MyClass();
config.Bind(obj);
Console.WriteLine(obj.MyProp.Length); // 3
Console.WriteLine(obj.MyProp[0]); // ABC
Console.WriteLine(obj.MyProp[1]); // DEF
Console.WriteLine(obj.MyProp[2]); // GHI
```

It behaves the same if its declared/defaulted as:
```charp
public IList<string> MyProp { get; set; } = new List<string> { "ABC" };
```

If the property is settable I would expect the binder to overwrite it. The different behavior for `IList<T>`/`T[]`, whether or not there's a default value (and _it's_ type) is a bit confusing. It seems like you should check both the static and runtime types. So instead of:

https://github.com/dotnet/runtime/blob/4cb924de165aa8e5373a109a68611d422aa72a09/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs#L328-L331

You'd have the following which indeed works, generating a new array with three values

```csharp
else if (type.IsArray || instance.GetType().IsArray)
{
  instance = BindArray((Array)instance, config, options);
}
```

In my case I don't even want the additive behavior--I'd like the list to be replaced entirely (losing the default values). I can achieve this by setting `null` if I'm calling `Bind` manually but not otherwise. Perhaps a property on `BinderOptions` to "replace collections" or something like that for a bit more control could help. I may open an issue for it.

**Comment by Pilchie** [comment] 2020-07-08 18:11
To answer the servicing question - our normal policy is that we considering fixing things in servicing if:
1. There is no satisfactory workaround.
2. It is blocking deployment.
3. A request comes through customer support for it.

In this particular case, it seems like there are usable workarounds, so we wouldn't introduce risk to existing LTS customers by servicing for it unless there is something I'm not understanding.

**Comment by ericstj** [comment] 2020-07-08 19:19
> As an aside, in my case I don't even want the additive behavior--I'd like the list to be replaced entirely (losing the default values). I can achieve this by setting null if I'm calling Bind manually but not otherwise. Perhaps a property on BinderOptions to "replace collections" or something like that for a bit more control could help. I may open an issue for it.

I agree.  Given the current behavior of appending has existed from this component's inception (https://github.com/aspnet/Configuration/commit/7d0ccdeaaf1cf6fd5623ae3dda54a222c82c63fd) I believe @pinkfloydx33's suggestion is actually a feature request and requires more thought.  Currently the binder assigning significant meaning to an instance of a collection being available (it appends).  For this reason I don't think we should replace an immutable instance with a mutable one without an explicit declaration of intent.  

One could go further to state that the binder is also assigning significant meaning to the type of the property and its intentional that it doesn't try to mutate the instance.  Do you imagine it's a violation of the object contract to examine the runtime-type to append to it?  I know I'd feel bad if I was doing something like this `((IList<t>)api.SomeReadOnlyCollection).Add(stuff)`, but then again in the BCL we gaurd against this type of thing when it matters by wrapping a mutable collection in an immutable one.

@davidfowl @HaoK do you have any guidance here on how intentional these behaviors are?

**Comment by Serg046** [comment] 2020-08-09 16:50
Based on these tests' names, I'd say the behaviour is intentional

https://github.com/dotnet/runtime/blob/4cb924de165aa8e5373a109a68611d422aa72a09/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/ConfigurationCollectionBindingTests.cs#L903-L1015

**Comment by Serg046** [comment] 2020-08-12 17:32
But if we still wanted to change the behaviour, I would take it

**Comment by maryamariyan** [comment] 2020-08-12 23:52
> Based on these tests' names, I'd say the behaviour is intentional

@HaoK I think you added these tests earlier in PR https://github.com/aspnet/Configuration/pull/504. Do we close the issue as the behavior is intentional?

**Comment by HaoK** [comment] 2020-08-13 00:03
Right the current behavior is intentional

**Closed** 2020-08-13 00:08 UTC
Labels: area-Extensions-Configuration, bug, up-for-grabs

**Comment by fschmied** [comment] 2020-08-13 15:50
@maryamariyan Are you sure that closing this is a good thing - even if it was intentional, it's very surprising and a likely cause of errors?
