### ISSUE TITLE
[API Proposal]: BinaryPrimitives.ReverseEndianness

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#75901] opened 2022-09-20 15:21 UTC
### Background and motivation

BinaryPrimitives today exposes a ReverseEndianness method for byte, ushort, uint, ulong, sbyte, short, int, and long, and https://github.com/dotnet/runtime/issues/72107 proposes adding overloads for nuint, UInt128, nint, and Int128 as well.  However, we lack versions of this API for processing multiple elements at a time.  A developer can write this in their own loop, e.g.

- https://github.com/dotnet/runtime/blob/20c8ae6457caa652a34fc42ff5f92b6728231039/src/libraries/System.Text.Encoding.CodePages/src/System/Text/BaseCodePageEncoding.cs#L115-L123
- https://github.com/dotnet/runtime/blob/20c8ae6457caa652a34fc42ff5f92b6728231039/src/libraries/System.Text.Encoding.CodePages/src/System/Text/BaseCodePageEncoding.netcoreapp.cs#L26-L29
- https://github.com/dorssel/usbipd-win/blob/2f7cbb732889ed00617e85f2f0b22239e8533960/Usbipd/Interop/UsbIp.cs#L165-L171
- https://github.com/HaveIBeenPwned/PwnedPasswordsAzureFunction/blob/0f81f2258f8f1f8f8486adf0820b141a43be396e/Shared/HaveIBeenPwned.PwnedPasswords.Shared/MD4.cs#L51-L55
- https://github.com/ratbuddy/ratbuddyssey/blob/65166ec837abc2ad78e2b2f239e8b1eb26aaaeef/Ratbuddyssey/AudysseyMultEQAvrTcpClientWithTimeout.cs#L51-L55
- https://github.com/saucecontrol/PhotoSauce/blob/d2555900c980c38a521e6381fc9b7a52dea66e3c/src/MagicScaler/Metadata/ExifReader.cs#L72-L73
- https://github.com/mono/mono/blob/b40e9939a7d07b30a75625692874f02bcc9be18f/mcs/class/referencesource/mscorlib/system/io/binaryreader.cs#L249-L250
- https://github.com/couchbase/couchbase-net-client/blob/4a755f449d2c4b37a4a44ba7107f2ba7a8594d80/src/Couchbase/Core/IO/Operations/Hello.cs#L59-L63
- https://github.com/Nenkai/PDTools/blob/2a9a5963f3754a029dfe0287aaddf8cbd804c763/PDTools.Files/Textures/TextureSet3.cs#L67-L68
- https://github.com/Nenkai/GTToolsSharp/blob/c33dbdb53e905be5b4b31a6575595749d5533a73/GTToolsSharp/Encryption/GT5POldCrypto.cs#L51-L52
- https://github.com/dotnet/runtime/issues/72107#issuecomment-1241858368
- https://github.com/dotnet/runtime/blob/8ceb8f8a25590cd9a1a35df5c7384b81b173ae1f/src/libraries/System.Net.Primitives/src/System/Net/IPAddress.cs#L294-L306

but it'd be nice if a) they didn't have to, and b) it could be vectorized (for at least some data types).

### API Proposal

```diff
namespace System.Buffers.Binary;

public static class BinaryPrimitives
{
+    public static void ReverseEndianness(ReadOnlySpan<ushort> source, Span<ushort> destination);
+    public static void ReverseEndianness(ReadOnlySpan<short> source, Span<short> destination);
+    public static void ReverseEndianness(ReadOnlySpan<uint> source, Span<uint> destination);
+    public static void ReverseEndianness(ReadOnlySpan<int> source, Span<int> destination);
+    public static void ReverseEndianness(ReadOnlySpan<ulong> source, Span<ulong> destination);
+    public static void ReverseEndianness(ReadOnlySpan<long> source, Span<long> destination);
+    public static void ReverseEndianness(ReadOnlySpan<nuint> source, Span<nuint> destination);
+    public static void ReverseEndianness(ReadOnlySpan<nint> source, Span<nint> destination);
+    public static void ReverseEndianness(ReadOnlySpan<UInt128> source, Span<UInt128> destination);
+    public static void ReverseEndianness(ReadOnlySpan<Int128> source, Span<Int128> destination);
}
```

`source` and `destination` may be the same.

I did not include overloads for byte/sbyte as they're useless (the current byte/sbyte overloads are useless, too).

### API Usage

```csharp
Span<uint> values = ...;
BinaryPrimitives.ReverseEndianness(values);
```

### Alternative Designs

- Instead of taking a source and a destination span, each overload could instead just take a `Span<T>` that's reversed in-place, and if you need the results in a different location, you first copy and then reverse in-place in the destination.

**Comment by Clockwork-Muse** [comment] 2022-09-20 15:23
Duplicate of #75900

**Comment by stephentoub** [comment] 2022-09-20 15:25
> Duplicate of https://github.com/dotnet/runtime/issues/75900

I closed the other one... somehow it got opened twice.

**Comment by Clockwork-Muse** [comment] 2022-09-20 15:26
... What's the anticipated behavior around in-place reversals?

**Comment by stephentoub** [comment] 2022-09-20 15:26
> What's the anticipated behavior around in-place reversals?

That it works.

**Comment by terrajobst** [comment] 2022-09-27 18:12
* Looks good as proposed
    - We discussed offering a single argument one. One argument against it that it might make code harder to read because ignoring the return value for scalars would be wrong. Another argument against it is that the two argument version is more versatile (it can handle passing the same span).

```C#
namespace System.Buffers.Binary;

public static class BinaryPrimitives
{
    public static void ReverseEndianness(ReadOnlySpan<ushort> source, Span<ushort> destination);
    public static void ReverseEndianness(ReadOnlySpan<short> source, Span<short> destination);
    public static void ReverseEndianness(ReadOnlySpan<uint> source, Span<uint> destination);
    public static void ReverseEndianness(ReadOnlySpan<int> source, Span<int> destination);
    public static void ReverseEndianness(ReadOnlySpan<ulong> source, Span<ulong> destination);
    public static void ReverseEndianness(ReadOnlySpan<long> source, Span<long> destination);
    public static void ReverseEndianness(ReadOnlySpan<nuint> source, Span<nuint> destination);
    public static void ReverseEndianness(ReadOnlySpan<nint> source, Span<nint> destination);
    public static void ReverseEndianness(ReadOnlySpan<UInt128> source, Span<UInt128> destination);
    public static void ReverseEndianness(ReadOnlySpan<Int128> source, Span<Int128> destination);
}
```

**Closed** 2022-11-04 08:57 UTC
Labels: api-approved, area-System.Memory, in-pr
