### ISSUE TITLE
Test failure DataContractSerializerTests.DCS_MyPersonSurrogate_Stress

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#84392] opened 2023-04-06 01:44 UTC
Run: [runtime-coreclr libraries-jitstress 20230405.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=228282&view=ms.vss-test-web.build-test-results-tab&runId=4307816&resultId=157250&paneView=debug)

Failed test:
```
net8.0-linux-Release-x64-CoreCLR_checked-no_tiered_compilation-Ubuntu.1804.Amd64.Open

- DataContractSerializerTests.DCS_MyPersonSurrogate_Stress
```
**Error message:**
```
Assert.Equal() Failure
Expected: Person[Name=name,Age=30]
Actual:   Person[Name=name,Age=30]


Stack trace
   at DataContractSerializerTests.DCS_MyPersonSurrogate_Stress() in /_/src/libraries/System.Runtime.Serialization.Xml/tests/DataContractSerializerStressTests.cs:line 62
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
```

**Comment by hoyosjs** [comment] 2023-06-29 22:30
Closing as dupe of https://github.com/dotnet/runtime/issues/35066

**Closed by hoyosjs** 2023-06-29 22:30 UTC
Labels: area-Serialization, os-linux, JitStress, arch-x64, untriaged
