### ISSUE TITLE
System.IO.Compression.SubReadStream Read Makes Unnecessary Calls

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#95450] opened 2023-11-30 09:50 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/SystemIOCompressionSubReadStream-Read/10491601)._

---
\[severity:I’m unable to use this version\]

### Description

The most recent patches for the dot net framework (v4.8 on Windows 11) are now seeing excessive calls to Stream.Read where the requested byte count during the read operation is 0. Is this expected? Shouldn’t the read operation be blocked if the count is known to be 0?

### Reproduction Steps

```  
using (var zipArchive = new ZipArchive(someStreamHere))
{
    var zipArchiveEntry = zipArchive.GetEntry("testFile.txt");
    using (var zipEntry = zipArchiveEntry.Open())
    {
        using (var streamReader = new StreamReader(zipEntry))
        {
            var fileContents = streamReader.ReadToEnd();
           // Do something with the file
        }
    }
}
  
```

### Expected behavior

The stream provided to the `ZipArchive` should be read, but the calls to the underlying Stream.Read should not request reads with count = 0

### Actual behavior

Calls are made to read the stream (`someStreamHere` in the example) with byte counts = 0

### Regression?

Yes, but I am not sure as to when this started occurring. It is possible this sample code has been calling Read with byte counts = 0 for quite some time.

### Known Workarounds

None

### Configuration

Windows 11, x64.  
Dot net framework 4.8.09032

### Other information

From decompiling SubReadStream.cs from System.IO.Compression, we can see that the decompiled code appears to not account for the zero byte count case.

```  
public override int Read(byte\[\] buffer, int offset, int count)
{
  this.ThrowIfDisposed();
  this.ThrowIfCantRead();
  
  if (this.\_superStream.Position != this.\_positionInSuperStream)
      this.\_superStream.Seek(this.\_positionInSuperStream, SeekOrigin.Begin);
  
  if (this.\_positionInSuperStream + (long) count > this.\_endInSuperStream)
      count = (int) (this.\_endInSuperStream - this.\_positionInSuperStream);
  
  // BUG: Count could be 0 here. Is calling this.superStream.Read with count = 0 expected?  
  int num = this.\_superStream.Read(buffer, offset, count);
  this.\_positionInSuperStream += (long) num;
  
  return num;
}
  
```

---
#### Dan Bracey on 10/13/2023, 06:23 PM: 

(private comment, text removed)
#### Feedback Bot on 10/16/2023, 04:15 AM: 

(private comment, text removed)
#### Dan Bracey on 10/31/2023, 11:03 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by wfurt** [comment] 2024-01-03 18:38
This is documented for .NET 6 and 4.8 probably does it for very same reason
https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams

I'm wondering if this should be closed as expected @carlossanlop @jeffhandley?

**Comment by stephentoub** [comment] 2024-01-03 18:50
> and 4.8 probably does it for very same reason

The changes cited in https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams were not ported back to .NET Framework 4.8.

**Comment by jeffhandley** [comment] 2024-01-05 20:06
Oops; it seems we had a loop of GitHub-->VS Feedback-->GitHub and this does seem to be specific to .NET Framework since the cited change started in .NET 6. I don't see where we would have had a regression on .NET Framework though--I might be misunderstanding something though.

@wfurt -- Unless you see where this is unexpected on .NET Framework, I recommend we close this GitHub issue, keep the VS Feedback issue open, inform the customer we think they are experiencing the expected behavior on .NET Framework (which differs from .NET 6+), and request their response and other findings.

**Comment by eiriktsarpalis** [comment] 2024-01-26 12:44
Closing in favor of https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1901091

**Closed by eiriktsarpalis** 2024-01-26 12:44 UTC
Labels: area-System.IO.Compression, untriaged
