### ISSUE TITLE
System.ArgumentException: Type must derive from Delegate. after call the p/invoke RegisterClass() method

### ISSUE THREAD

**Issue by temamarvel** [dotnet/runtime#34584] opened 2020-04-06 12:25 UTC
I tried new .NET Core 5.0.100-preview.2.20176.6 on my code and got an exception 
System.ArgumentException: Type must derive from Delegate. (Parameter 't') at at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t).

On .NET Core 3.1 or .NET Framework 4.6 my code works correctly.

I have prepared the sample to demonstrate this issue
https://github.com/temamarvel/netcore5nativecrashtest

Is there a bug?

**Comment by AaronRobinsonMSFT** [comment] 2020-04-06 18:19
@temamarvel This is a minor behavioral change and is fixing a long standing bug. We have updated our guidance about `struct` marshaling with `Delegate` fields [here](https://docs.microsoft.com/dotnet/standard/native-interop/best-practices#structs).

Additional details can be found at https://github.com/dotnet/runtime/issues/33919.

**Comment by AaronRobinsonMSFT** [comment] 2020-04-06 18:19
Duplicate of #33919.

**Comment by temamarvel** [comment] 2020-04-06 18:22
Thank you so much for information. I will check it.

**Comment by jkotas** [comment] 2020-04-06 18:43
Was this breaking change really required - what is the benefit? Given that we are getting feedback about the breaking nature of this change already, I would strongly recommend reverting it. This is the kind of thing we can make better for the new interop story based on source generators.

If we really want to do this breaking change, we need to have an issue marked with breaking-change label for this and good justification for it.

**Closed** 2020-04-07 04:20 UTC
Labels: area-Interop-coreclr, tenet-compatibility
