### ISSUE TITLE
Implement SqlDateTime2

### ISSUE THREAD

**Issue by bjornbouetsmith** [dotnet/runtime#46127] opened 2020-12-16 10:19 UTC
### Description
My own and other people's performance tests show that that SqlTypes can give better performance than using the built in .NET types. https://github.com/dotnet/SqlClient/issues/846

In sql client specifically, calling GetDateTime vs GetSqlDateTime and similar "pairs" of methods.

The performance gain from using SqlTypes and their GetSqlWhatever method comes from not having to call IsDbNull on SqlDataReader.

I found this issue when profiling and IsDbNull stuck its head out, then I tried using GetSqlDateTime, since it handles null internally - but that struct does not support DATETIME2 - so I am stuck with using IsDbNull+GetDateTime.

So I propose that you add a SqlDateTime2 struct to make the "API" complete. It seems like this was forgotten when DATETIME2 was introduced into SQL Server - unless the SqlTypes are legacy and not meant for new development?

Having a SqlDateTime2 struct makes it possible to implement a GetSqlDateTime2 method in "sql client".

An alternative would also be to "fix" SqlDateTime - so it also handles the extended range of DATETIME2 - but that would potentially be a breaking change for some applications.

**Comment by David-Engel** [comment] 2020-12-16 18:20
This would be in System.Data.

@roji - Do you know any of the history about why some data types like datetime2, introduced in SQL Server 2008, did not get their own [SqlType](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqltypes?view=dotnet-plat-ext-5.0) while they did get their own [DbType](https://docs.microsoft.com/en-us/dotnet/api/system.data.dbtype?view=net-5.0) and [SqlDbType](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqldbtype?view=dotnet-plat-ext-5.0)? My guess is it may have to do with other ADO.NET data providers and backwards compatibility...

**Comment by Wraith2** [comment] 2020-12-16 21:13
> This would be in System.Data.

Or, it could be put into Micsoft.Data.SqlClient if that's the only place that would use it. As far as i know the reason that the other SqlTypes are still in runtime is that DataTable uses them so if it were put into runtime would that also include adding these types to DataTable DataAdapter etc? @roji and I discussed this somewhat at https://github.com/dotnet/SqlClient/issues/846 and I thought that those types were supported but not actively being considered for new development, EF and other ORM's have largely replaced them.

**Comment by roji** [comment] 2021-07-13 09:16
Closing in favor of https://github.com/dotnet/SqlClient/issues/846, and the move to implement there instead of in the runtime. To summarize the current situation:

* SQL Server `datetime2` is already fully usable via SqlDataReader.GetDateTime (but not via SqlDataReader.GetSqlDateTime - by design)
* The motivation behind introducing a GetSqlDateTime2 (this issue) is that GetDateTime requires a null check with IsDBNull before invocation. The argument is that the perf impact of the extra IsDBNull check is worth introducing this new API.

**Closed by roji** 2021-07-13 09:16 UTC
Labels: area-System.Data, untriaged
