### ISSUE TITLE
[API Proposal]: Provide generic version of JsonSerializable attribute

### ISSUE THREAD

**Issue by HakamFostok** [dotnet/runtime#91869] opened 2023-09-11 09:46 UTC
### Background and motivation

Even if the benefit is small, this will save one `Type` object from being created.
If you have a lot of objects to serialize, and if you apply the `JsonSerializable` a lot of times, then there may be a little difference

### API Proposal

```csharp

namespace System.Text.Json.Serialization;

[System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple=true)]
public sealed class JsonSerializableAttribute<T>  : System.Text.Json.Serialization.JsonAttribute
{
}
```

### API Usage

```csharp
[JsonSerializable<string>]
public partial class MyJsonContext : JsonSerializerContext {}
```

### Alternative Designs

None

### Risks

None

**Comment by eiriktsarpalis** [comment] 2023-09-11 12:43
Duplicate of https://github.com/dotnet/runtime/issues/71712.

> If this was a new API we might be having a different conversation, but as it stands the proposal seems to be introducing too much risk or ambiguity to warrant inclusion. Generic attributes might be more useful in cases where we want to constraints on specified types, but that doesn't really apply here. I think we should just close this.

**Closed by eiriktsarpalis** 2023-09-11 12:43 UTC
Labels: api-suggestion, area-System.Text.Json, untriaged
