### ISSUE TITLE
Animated Gif - division by zero

### ISSUE THREAD

**Issue by AngeloCresta** [dotnet/runtime#55972] opened 2021-07-19 21:13 UTC
### Description
Binding an animated gif to a picture box will cause a division by zero error

### configuration
VS 2022 P2,. Net Core 6 preview 6 on Windows 10 21H1 (x64) 

### Regression?
Worked on. Net 5

### Other information - Stack Trace

CoreCLR Version: 6.0.21.35212
.NET Version: 6.0.0-preview.6.21352.12
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DivideByZeroException: Attempted to divide by zero.
   at System.Math.DivRem(Int64 a, Int64 b, Int64& result) in System.Private.CoreLib.dll:token 0x600046a+0x0
   at System.Drawing.ImageAnimator.ImageInfo.AdvanceAnimationBy(Int64 milliseconds) in System.Drawing.Common.dll:token 0x6000bed+0x31
   at System.Drawing.ImageAnimator.AnimateImages() in System.Drawing.Common.dll:token 0x60002e0+0x3d
   at System.Threading.Thread.StartHelper.Callback(Object state) in System.Private.CoreLib.dll:token 0x600288d+0x0
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in System.Private.CoreLib.dll:token 0x6002a2d+0x40
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in System.Private.CoreLib.dll:token 0x6002a2d+0x80
   at System.Threading.Thread.StartCallback() in System.Private.CoreLib.dll:token 0x600280f+0xe

**Comment by safern** [comment] 2021-07-19 22:15
@jeffhandley this seems like a regression from: https://github.com/dotnet/runtime/commit/3ffc4fc0b2a1b28a9b44f12a19bf2299c1901f87#diff-b932d2f5042c51d85e4441810d14e37dd2f7dbecf05237075aed420a4b6e7663

It looks like the timeElapsed is 0 in here? https://github.com/dotnet/runtime/commit/3ffc4fc0b2a1b28a9b44f12a19bf2299c1901f87#diff-b932d2f5042c51d85e4441810d14e37dd2f7dbecf05237075aed420a4b6e7663R408

Hitting the exception in: https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Drawing.Common/src/System/Drawing/ImageInfo.cs#L164

@AngeloCresta could you share a zip with a GIF and a Program.cs that causes the exception?

**Comment by AngeloCresta** [comment] 2021-07-20 07:15
This is a sample project with the control that uses the animated gif causing the error.
[WinFormsApp1.zip](https://github.com/dotnet/runtime/files/6846228/WinFormsApp1.zip)

**Comment by jeffhandley** [comment] 2021-07-20 22:46
Thank you, @AngeloCresta! I'll get this fixed in 6.0 RC1.

**Closed** 2021-07-24 14:56 UTC
Labels: area-System.Drawing, in pr
