### ISSUE TITLE
DateTime AddUnits & TimeSpan IntervalFromDoubleTicks rounding issues at the factionalPart level

### ISSUE THREAD

**Issue by oe06** [dotnet/runtime#107129] opened 2024-08-29 09:53 UTC
### Description

All methods AddHours/AddMiniutes/... using AddUnits have floating round issue at the factionalPart

### Reproduction Steps

DateTime.MinValue.AddHours(1.2).Ticks;
DateTime.MinValue.AddTicks((long) Math.Round(1.2*36E7)).Ticks;
should returns the same value

### Expected behavior

43_200_000_000
43_200_000_000

### Actual behavior

43_199_999_999
43_200_000_000

### Regression?

Yes since new implementation done in .NET7

### Known Workarounds

use AddTicks or FromTicks with (long) Math.Round(value*TicksPer....)

or fixing DateTime.cs at line 898 with ticks += (long) Math.Round(fractionalPart * ticksPerUnit);
and TimeSpan.cs at line 323 return new TimeSpan((long) Math.Round(ticks);

### Other information

"So, you're not adding 1.2 hours (which would be 4320 seconds or 43_200_000_000 ticks), instead you're adding approximately 43_199_999_999 ticks instead."

Following the current code at line (898 of dateTime.cs) ticks += (long)(fractionalPart * ticksPerUnit);
(fractionalPart * ticksPerUnit)=719_999_999.999999 according to the IEEE 754 standard representation
but you casting it directly as a long (without a correct rounding) so in this cast (long) 719_999_999.999999 gives 719_999_999
if you apply Math.Round(fractionalPart * ticksPerUnit) it gives (a "more" correct mathematic representation value) 720_000_000

What I'm trying to tell you is that the problems detected are problems of conversion from real to integer which are done without mathematically correct rounding.

**Comment by tannergooding** [comment] 2024-08-29 11:34
> What I'm trying to tell you is that the problems detected are problems of conversion from real to integer which are done without mathematically correct rounding.

There is no such thing as "mathematically correct rounding". Math has many different types of rounding, especially as you get into higher levels. The one that most are taught as the basic form in elementary or primary school is known as `Round to nearest, Ties Away from Zero`.

Computer types, by design, do not follow this rounding mode for many different reasons. For integer types, they use `truncation` to round and is done primarily for performance, this is why `5 / 2 == 2`. For floating-point types, they use `Round to nearest, Ties to Even` (sometimes known as `Banker's Rounding`) for individual operations to remove rounding bias. However, for conversion to integer types they also use `truncation` by default for performance and to improve accuracy of operations.

As per the initial response given on https://github.com/dotnet/runtime/issues/107092:
> Now, there is some things that could be improved here, such as explicitly handling some values to ensure they round up instead of down. That would fix this particular case, but would inversely break other cases.

This was specifically referring to the use of a more explicit round function and handling instead of using the standard convert to integer, which truncates, functionality. There are cases, like the one you've raised, that this would seemingly fix. However, there are inversely other cases that would now break in their place (this becomes particularly relevant for very large additions, especially as the tick count nears `2^52`). There is no singular solution which fixes all cases, in part due to the actual values represented by the literals users type (such as `1.2`) not being exactly representable and improving cases, even minimally, comes with a substantial cost which can have large negative impact to existing code (and may change the result from the IEEE 754 compliant result).

Instead, we opted to expose new APIs which are faster and clearer, because they operate strictly on integer values which cannot be misconstrued and do not need decomposition to handling lack of representation. These APIs should be preferred where possible instead.

**Comment by oe06** [comment] 2024-08-29 12:16
So you advise using AddTicks or FromTicks instead, to avoid any approximations made in methods using real numbers?

**Comment by tannergooding** [comment] 2024-08-29 12:26
Yes, in general if you need to ensure exact results you should not be using `float` or `double` which can not exactly represent the values you are likely intending to add (such as `1.2`)

Instead, use APIs where you know the `float`/`double` is exactly representable and does not introduce rounding error due to the representation format.

-or-

use the APIs that explicitly operate in terms of integers instead, such as `AddTicks(long ticks)`. Additionally, In the case of .NET 9 or later you can use new APIs such as `TimeSpan.FromHours(int hours, long minutes = 0, long seconds = 0, long milliseconds = 0, long microseconds = 0)` (https://learn.microsoft.com/en-us/dotnet/api/system.timespan.fromhours?view=net-9.0#system-timespan-fromhours(system-int32-system-int64-system-int64-system-int64-system-int64)) which exist for convenience and which often have better overall performance. Thus you can do something like `Console.WriteLine((new DateTime(2004,2,1,11,6,7) + TimeSpan.FromHours(1, minutes: 12)).Ticks)`;

**Comment by oe06** [comment] 2024-08-29 12:52
I would have hoped that the result would be rounded to the nearest tick by default. :-(

**Comment by tarekgh** [comment] 2024-08-29 15:50
@oe06 I am closing this issue too as it looks like all your questions are addressed. Feel free to send more questions if you still have any.

**Closed by tarekgh** 2024-08-29 15:50 UTC
Labels: area-System.DateTime

**Comment by tannergooding** [comment] 2024-08-29 16:29
> I would have hoped that the result would be rounded to the nearest tick by default. :-(

As mentioned, there are reasons this isn't done both for perf and correctness in other edge cases. There's a balance everywhere.

The perf side might be less important now that the other APIs taking `long` exist, but its likely not worth the additional churn and work.
