### ISSUE TITLE
Long running test: System.Diagnostics.Tests.InstanceDataTests.InstanceDataCollectionCollection_CopyTo

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#33372] opened 2020-03-09 14:15 UTC
https://dev.azure.com/dnceng/public/_build/results?buildId=551597&view=ms.vss-test-web.build-test-results-tab&runId=17416796&resultId=180795&paneView=attachments

Configurations:
- netcoreapp5.0-Windows_NT-Release-x86-CoreCLR_release-Windows.10.Amd64.Server19H1.ES.Open
- netcoreapp5.0-Windows_NT-Debug-x64-CoreCLR_release-Windows.10.Amd64.Server19H1.ES.Open

```
  Discovering: System.Diagnostics.PerformanceCounter.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Diagnostics.PerformanceCounter.Tests (found 89 of 91 test cases)
  Starting:    System.Diagnostics.PerformanceCounter.Tests (parallel test collections = on, max threads = 2)
   System.Diagnostics.PerformanceCounter.Tests: [Long Running Test] 'System.Diagnostics.Tests.InstanceDataTests.InstanceDataCollectionCollection_CopyTo', Elapsed: 00:02:00
```

4808.1n2wfgek.bux.dmp: https://helix.dot.net/api/2019-06-17/jobs/ddf1dfcc-a4c5-4f13-9f9a-c49d9ca60a55/workitems/System.Diagnostics.PerformanceCounter.Tests/files/4808.1n2wfgek.bux.dmp

console.8477c80a.log: https://helix.dot.net/api/2019-06-17/jobs/ddf1dfcc-a4c5-4f13-9f9a-c49d9ca60a55/workitems/System.Diagnostics.PerformanceCounter.Tests/files/console.8477c80a.log

@tarekgh @Anipik can you please take a look?

**Comment by tarekgh** [comment] 2020-03-09 23:08
@ViktorHofer does this test consistently timeout? or it just fails sporadically? 

I am seeing the test is written in a way with trying many times (10 times for each PerformanceCounter creation) which looks in some circumstances can timeout I guess because of that.

**Comment by danmosemsft** [comment] 2020-03-09 23:23
Dupe of https://github.com/dotnet/runtime/issues/33291 I think?

**Comment by danmosemsft** [comment] 2020-03-09 23:25
If we've done all we can with retries, maybe we should disable the perf counter tests with `[NotForCi]`. We would have to manually run them for various OS periodically. Not ideal, but it's very unlikely we'll regress the code since we don't change it.

**Comment by tarekgh** [comment] 2020-03-09 23:41
@danmosemsft I believe adding [NotForCi] is reasonable.

one note here, the time out is not mainly from InstanceDataCollectionCollection_CopyTo but looks from PerformanceCounter_PerformanceData(). I guess we can try adding NotForCi to PerformanceCounter_PerformanceData() and watch if this would be enough.

**Comment by danmosemsft** [comment] 2020-03-09 23:49
My theory is that there is nothing special about hte tests and somehow the OS gets too busy to return from the calls we make into it. This was apparently hte case in the linked issue.

**Closed** 2020-03-10 07:12 UTC
Labels: area-System.Diagnostics.Tracing, untriaged
