### ISSUE TITLE
SSL Stress Connection Refused Linux

### ISSUE THREAD

**Issue by ManickaP** [dotnet/runtime#93204] opened 2023-10-09 09:51 UTC
Getting 2 different stacks with the same reason:
```
2023-10-09T09:28:26.3900195Z client_1  | There were a total of 38 failures classified into 2 different types:
2023-10-09T09:28:26.3900444Z client_1  | 
2023-10-09T09:28:26.3936702Z client_1  | Failure Type 1/2:
2023-10-09T09:28:26.3937778Z client_1  | System.Net.Sockets.SocketException (111): Connection refused
2023-10-09T09:28:26.3938315Z client_1  |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1378
2023-10-09T09:28:26.3938776Z client_1  |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1294
2023-10-09T09:28:26.3939085Z client_1  |    at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/ValueTask.cs:line 258
2023-10-09T09:28:26.3939545Z client_1  | --- End of stack trace from previous location ---
2023-10-09T09:28:26.3939747Z client_1  |    at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/TCPClient.cs:line 193
2023-10-09T09:28:26.3939988Z client_1  |    at SslStress.SslClientBase.<StartCore>g__RunSingleWorker|15_1(Int32 workerId, Random random) in /app/System.Net.Security/tests/StressTests/SslStress/SslClientBase.cs:line 116
2023-10-09T09:28:26.3940172Z client_1  | 
2023-10-09T09:28:26.3997089Z client_1  | 	                              Fail: 36	Timestamps: 08:58:25, 08:58:25, 08:58:25, 08:58:25, 08:58:26, 08:58:26, 08:58:26, 08:58:26, 08:58:26, 08:58:26, 08:58:26, 08:58:26, 08:58:26, 08:58:26, 08:58:26, 08:58:26, 08:58:26, 08:58:26, 08:58:26, 08:58:26, 08:58:26, 08:58:26, 08:58:26, 08:58:26, 08:58:26, 08:58:26, 08:58:26, 08:58:26, 08:58:26, 08:58:26, 08:58:26, 08:58:26, 08:58:26, 08:58:26, 08:58:26, 08:58:26
2023-10-09T09:28:26.4006172Z client_1  | 	    TOTAL                     Fail: 2
2023-10-09T09:28:26.4008079Z client_1  | 
2023-10-09T09:28:26.4008521Z client_1  | Failure Type 2/2:
2023-10-09T09:28:26.4009820Z client_1  | System.Net.Sockets.SocketException (111): Connection refused
2023-10-09T09:28:26.4010635Z client_1  |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1387
2023-10-09T09:28:26.4011252Z client_1  |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(Socket socket) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1224
2023-10-09T09:28:26.4011775Z client_1  |    at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 100
2023-10-09T09:28:26.4012207Z client_1  |    at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 78
2023-10-09T09:28:26.4012763Z client_1  |    at System.Net.Sockets.Socket.ConnectAsync(IPAddress address, Int32 port) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 135
2023-10-09T09:28:26.4016295Z client_1  |    at System.Net.Sockets.TcpClient.ConnectAsync(IPAddress address, Int32 port) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/TCPClient.cs:line 175
2023-10-09T09:28:26.4016743Z client_1  |    at SslStress.SslClientBase.<StartCore>g__RunSingleWorker|15_1(Int32 workerId, Random random) in /app/System.Net.Security/tests/StressTests/SslStress/SslClientBase.cs:line 116
2023-10-09T09:28:26.4017196Z client_1  |    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs:line 288
2023-10-09T09:28:26.4017705Z client_1  |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 179
2023-10-09T09:28:26.4018049Z client_1  |    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs:line 368
2023-10-09T09:28:26.4018353Z client_1  |    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs:line 346
2023-10-09T09:28:26.4018669Z client_1  |    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs:line 795
2023-10-09T09:28:26.4018937Z client_1  |    at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 3456
2023-10-09T09:28:26.4019207Z client_1  |    at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 1999
2023-10-09T09:28:26.4019464Z client_1  |    at System.Threading.Tasks.Task.TrySetException(Object exceptionObject) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 3371
2023-10-09T09:28:26.4019735Z client_1  |    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs:line 516
2023-10-09T09:28:26.4020023Z client_1  |    at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/TCPClient.cs:line 193
2023-10-09T09:28:26.4020292Z client_1  |    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs:line 288
2023-10-09T09:28:26.4020760Z client_1  |    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ExecutionContext.cs:line 179
2023-10-09T09:28:26.4021059Z client_1  |    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs:line 368
2023-10-09T09:28:26.4021383Z client_1  |    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/CompilerServices/AsyncTaskMethodBuilderT.cs:line 346
2023-10-09T09:28:26.4021753Z client_1  |    at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs:line 795
2023-10-09T09:28:26.4022023Z client_1  |    at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 3456
2023-10-09T09:28:26.4022281Z client_1  |    at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 1999
2023-10-09T09:28:26.4022510Z client_1  |    at System.Threading.Tasks.Task.TrySetException(Object exceptionObject) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 3371
2023-10-09T09:28:26.4022803Z client_1  |    at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/ValueTask.cs:line 258
2023-10-09T09:28:26.4023065Z client_1  |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs _) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1031
2023-10-09T09:28:26.4023339Z client_1  |    at System.Net.Sockets.SocketAsyncEventArgs.OnCompletedInternal() in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs:line 210
2023-10-09T09:28:26.4023634Z client_1  |    at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncFailure(SocketError socketError, Int32 bytesTransferred, SocketFlags flags) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.cs:line 636
2023-10-09T09:28:26.4023945Z client_1  |    at System.Net.Sockets.SocketAsyncEventArgs.CompletionCallback(Int32 bytesTransferred, SocketFlags flags, SocketError socketError) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Unix.cs:line 391
2023-10-09T09:28:26.4024267Z client_1  |    at System.Net.Sockets.SocketAsyncEventArgs.ConnectCompletionCallback(SocketError socketError) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEventArgs.Unix.cs:line 72
2023-10-09T09:28:26.4024546Z client_1  |    at System.Net.Sockets.SocketAsyncContext.ConnectOperation.InvokeCallback(Boolean allowPooling) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 665
2023-10-09T09:28:26.4024843Z client_1  |    at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.ProcessAsyncOperation(TOperation op) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 1004
2023-10-09T09:28:26.4025111Z client_1  |    at System.Net.Sockets.SocketAsyncContext.ProcessAsyncWriteOperation(WriteOperation op) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 1415
2023-10-09T09:28:26.4025411Z client_1  |    at System.Net.Sockets.SocketAsyncContext.WriteOperation.System.Threading.IThreadPoolWorkItem.Execute() in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 347
2023-10-09T09:28:26.4025809Z client_1  |    at System.Net.Sockets.SocketAsyncContext.AsyncOperation.Process() in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 291
2023-10-09T09:28:26.4026060Z client_1  |    at System.Net.Sockets.SocketAsyncContext.HandleEvents(SocketEvents events) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs:line 2202
2023-10-09T09:28:26.4026344Z client_1  |    at System.Net.Sockets.SocketAsyncEngine.System.Threading.IThreadPoolWorkItem.Execute() in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncEngine.Unix.cs:line 242
2023-10-09T09:28:26.4026588Z client_1  |    at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 913
2023-10-09T09:28:26.4026868Z client_1  |    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.WorkerThread.NonBrowser.cs:line 58
2023-10-09T09:28:26.4027184Z client_1  | --- End of stack trace from previous location ---
2023-10-09T09:28:26.4027388Z client_1  |    at System.Net.Sockets.TcpClient.CompleteConnectAsync(Task task) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/TCPClient.cs:line 193
2023-10-09T09:28:26.4027623Z client_1  |    at SslStress.SslClientBase.<StartCore>g__RunSingleWorker|15_1(Int32 workerId, Random random) in /app/System.Net.Security/tests/StressTests/SslStress/SslClientBase.cs:line 116
2023-10-09T09:28:26.4027818Z client_1  | 
2023-10-09T09:28:26.4027918Z client_1  | 	                              Fail: 2	Timestamps: 08:58:26, 08:58:26
2023-10-09T09:28:26.4028058Z client_1  | 	    TOTAL                     Fail: 2
2023-10-09T09:28:26.4028140Z client_1  | 

```

https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/431500/logs/13

**Comment by liveans** [comment] 2024-07-12 15:23
Duplicate of #94222
Fixed in #100296

/cc @rzikm

**Closed by liveans** 2024-07-12 15:23 UTC
Labels: area-System.Net.Sockets
