### ISSUE TITLE
AssemblyLoadConext dident be collected after unloaded in mono runtime

### ISSUE THREAD

**Issue by newNcy** [dotnet/runtime#100124] opened 2024-03-22 06:57 UTC
### Description

embedding mono in c and use alc to load assembly, the gc  seems not work

### Reproduction Steps

things i did in C
```C
    MonoImage * img = mono_assembly_get_image(assembly);
    MonoClass * klass = mono_class_from_name(img, "Lib", "Lib");
    MonoMethod * run_game = mono_class_get_method_from_name(klass, "run_game", -1);
    char buff[1024] = {0};
    strlcpy(buff, get_bundle_path(), 1024);
    strlcat(buff, "/", 1024);
    strlcat(buff, "Program.dll", 1024);
    
    
    void * args[1]  = {mono_string_new(domain, buff)};
    for (int i = 0; i <  1000000000; i++)
    {
        mono_runtime_invoke(run_game, NULL, args, NULL);
    }
```

In Lib.cs 
 ```c#
127 public static void run_game(string path)
128     {
129         var alc = new AssemblyLoadContext("_", true);
130         Console.WriteLine($"dll to load {path}");
131         var asm = alc.LoadFromAssemblyPath(path);
132         Console.WriteLine($"dll to load {asm}");
133 
134         var programType = asm.GetType("Program");
135         if (programType == null)
136         {
137             Console.WriteLine("Program type not found in the assembly");
138             return;
139         }
140 
141         var nqueenMethod = programType.GetMethod("Nqueen", BindingFlags.Public | BindingFlags.Static);
142         if (nqueenMethod == null)
143         {
144             Console.WriteLine("Nqueen method not found in the Program type");
145             return;
146         }
147         
148         nqueenMethod.Invoke(null, null);
149         alc.Unload();
150         alc = null;
151     }
```
in Program.cs
``` C#
132     public static void Nqueen()
133     {
134         new List<object>();
135         GC.Collect();
136     }   
```

### Expected behavior

memory allocated by ios app not increase

### Actual behavior

memory allocated by ios app keep increase

**Comment by huoyaoyuan** [comment] 2024-03-22 07:35
Duplicate of #79711. The feature hasn't been done for mono yet.

**Closed** 2024-03-22 07:46 UTC
Labels: untriaged, needs-area-label
