### ISSUE TITLE
CI build failure: mono llvmfullaot linux x64 - No output

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#77403] opened 2022-10-24 20:50 UTC
Not sure if duplicate, couldn't find one.
I was unable to find any useful artifacts in the Tests section.

- Build failure seen in this PR: https://github.com/dotnet/runtime/pull/74157
- Queue: `mono llvmfullaot Pri0 Runtime Tests Run Linux x64 release`
- Failed step: `LLVM AOT compile CoreCLR tests`
- Log file: https://dev.azure.com/dnceng-public/public/_build/results?buildId=61384&view=logs&j=7105ddeb-5f39-5d9f-83e7-ac87577a95a3&t=1f99299e-c631-5cfe-bd5e-d99bee5f9e36&l=49
- Output: 

```
build.sh -log:MonoAot mono_fullaot release x64 /p:RuntimeVariant=llvmfullaot
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /__w/_temp/c8093669-c7e6-4b6d-9c36-bcb0c70d67cb.sh
__DistroRid: linux-x64
Building Tests...
__TargetOS: Linux
__TargetArch: x64
__BuildType: Release
__TestIntermediatesDir: /__w/1/s/artifacts/tests/coreclr/obj/Linux.x64.Release
__NativeTestIntermediatesDir: /__w/1/s/artifacts/tests/coreclr/obj/Linux.x64.Release/Native
__ManagedTestIntermediatesDir: /__w/1/s/artifacts/tests/coreclr/obj/Linux.x64.Release/Managed
Creating TestBinDir: /__w/1/s/artifacts/tests/coreclr/Linux.x64.Release
Creating LogsDir: /__w/1/s/artifacts/log
Creating MsbuildDebugLogsDir: /__w/1/s/artifacts/log/MsbuildDebugLogs
Building tests via "/__w/1/s/eng/common/msbuild.sh"  --warnAsError false /__w/1/s/src/tests/build.proj /t:TestBuild /p:TargetArchitecture=x64 /p:Configuration=Release /p:TargetOS=Linux /nodeReuse:false    /maxcpucount "/flp:Verbosity=normal;LogFile=/__w/1/s/artifacts/log/MonoAot.Linux.x64.Release.log" "/flp1:WarningsOnly;LogFile=/__w/1/s/artifacts/log/MonoAot.Linux.x64.Release.wrn" "/flp2:ErrorsOnly;LogFile=/__w/1/s/artifacts/log/MonoAot.Linux.x64.Release.err" "/bl:/__w/1/s/artifacts/log/MonoAot.Linux.x64.Release.binlog" /p:NUMBER_OF_PROCESSORS=4 /p:RuntimeVariant=llvmfullaot
/__w/1/s/.dotnet/sdk/7.0.100-rc.1.22431.12/MSBuild.dll /nologo -maxcpucount /m /maxcpucount -verbosity:m /v:minimal /bl:/__w/1/s/artifacts/log/MonoAot.Linux.x64.Release.binlog /clp:Summary /flp1:WarningsOnly;LogFile=/__w/1/s/artifacts/log/MonoAot.Linux.x64.Release.wrn /flp2:ErrorsOnly;LogFile=/__w/1/s/artifacts/log/MonoAot.Linux.x64.Release.err /flp:Verbosity=normal;LogFile=/__w/1/s/artifacts/log/MonoAot.Linux.x64.Release.log /nr:true /nodeReuse:false /p:TreatWarningsAsErrors=false /p:ContinuousIntegrationBuild=false /p:TargetArchitecture=x64 /p:Configuration=Release /p:TargetOS=Linux /p:NUMBER_OF_PROCESSORS=4 /p:RuntimeVariant=llvmfullaot /t:TestBuild /__w/1/s/src/tests/build.proj
  [20:21:08.55] Restoring all packages...
    Determining projects to restore...
    All projects are up-to-date for restore.
    Determining projects to restore...
    All projects are up-to-date for restore.
    Determining projects to restore...
    All projects are up-to-date for restore.
/__w/1/s/src/tests/build.proj(437,5): error MSB3073: The command ""/__w/1/s/.dotnet/dotnet" restore -r linux-x64 Common/CoreCLRTestLibrary/CoreCLRTestLibrary.csproj  /p:SetTFMForRestore=true /p:TargetOS=Linux /p:TargetArchitecture=x64 /p:Configuration=Release /p:CrossBuild=" exited with code 1.

Build FAILED.

/__w/1/s/src/tests/build.proj(437,5): error MSB3073: The command ""/__w/1/s/.dotnet/dotnet" restore -r linux-x64 Common/CoreCLRTestLibrary/CoreCLRTestLibrary.csproj  /p:SetTFMForRestore=true /p:TargetOS=Linux /p:TargetArchitecture=x64 /p:Configuration=Release /p:CrossBuild=" exited with code 1.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:07.74
Build failed with exit code 1. Check errors above.
Failed to build tests. See the build logs:
    /__w/1/s/artifacts/log/MonoAot.Linux.x64.Release.log
    /__w/1/s/artifacts/log/MonoAot.Linux.x64.Release.wrn

```

**Comment by jkotas** [comment] 2022-11-05 22:17
Duplicate of https://github.com/dotnet/runtime/issues/76906

**Closed by jkotas** 2022-11-05 22:17 UTC
Labels: untriaged, area-Infrastructure-mono
