### ISSUE TITLE
Null or empty array configuration does not update corresponding bound model property

### ISSUE THREAD

**Issue by Myster-Tee** [dotnet/runtime#97857] opened 2024-02-02 08:57 UTC
### Description

When binding a class model declaring an array of string property to a configuration section, model property is not updated when corresponding configuration property is set to null or empty array.

This bug prevents the implementation of distinct semantic logic between an empty array and a null array

### Reproduction Steps

1. Create a .NET console app with Microsoft.Extensions.Hosting nuget

```csharp
internal class Program
{
    static void Main(string[] args)
    {
        var hostBuilder = Host.CreateApplicationBuilder(args);

        hostBuilder.Configuration.AddJsonFile("config.json", false, true);

        hostBuilder.Services.Configure<SomeSettingsModel>(hostBuilder.Configuration);
        hostBuilder.Services.AddSingleton<Service>();

        var app = hostBuilder.Build();

        app.Services.GetRequiredService<Service>();

        app.Run();
    }
}

class Service
{
    public Service(IOptionsMonitor<SomeSettingsModel> optionsMonitor)
    {
        LogUsers(optionsMonitor.CurrentValue);
        optionsMonitor.OnChange(LogUsers);
    }

    void LogUsers(SomeSettingsModel model)
    {
        if (model.Users == null)
            Console.WriteLine("Users: null");
        else
            Console.WriteLine($"Users: {model.Users.Length}");
    }
}

class SomeSettingsModel
{
    private string?[]? _users;

    public string?[]? Users
    {
        get => _users;
        set
        {
            Console.WriteLine("Users setter invoked");
            _users = value;
        }
    }
}
```

2. Create a config.json with the content below
```json
{
  "Users": ["Jean", "Albert"]
}
```

3. Launch application

4. Update JSON to
```json
{
  "Users": []
}
```

5. Update JSON to
```json
{
  "Users": ["Jean", "Albert"]
}
```

6. Update JSON to
```json
{
  "Users": null
}
```

### Expected behavior

Output expected at step 4:

```
Users setter invoked
Users: 0
```

Output expected at step 6:
```
Users setter invoked
Users: null
```

### Actual behavior

Actual output at step 4:

```
Users: null
```

Actual output at step 6:
```
Users: null
```

### Configuration

.NET 7
Windows 10
X64

**Comment by tarekgh** [comment] 2024-02-02 17:41
This is a duplicate of https://github.com/dotnet/runtime/issues/58930

**Closed by tarekgh** 2024-02-02 17:41 UTC
Labels: untriaged, area-Extensions-Configuration
