### ISSUE TITLE
Questions about 'JsonStringEnumConverter' not using namingPolicy when deserializing the object.

### ISSUE THREAD

**Issue by liuI** [dotnet/runtime#41138] opened 2020-08-21 02:06 UTC
https://github.com/dotnet/runtime/blob/a5b491cb64475563597d837a6ec3a6b8b353175b/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Value/EnumConverter.cs#L317

Use the obtained string value directly here. But why not use _namingPolicy'?

like:

``` C#
        internal override T ReadWithQuotes(ref Utf8JsonReader reader)
        {
            string? enumString = reader.GetString();
            
            var v =  _namingPolicy == null ? enumString : FormatEnumValueToString(enumString, encoder);
             
            // Try parsing case sensitive first
            if (!Enum.TryParse(v, out T value)
                && !Enum.TryParse(v, ignoreCase: true, out value))
            {
                ThrowHelper.ThrowJsonException();
            }

            return value;
        }
```

**Comment by layomia** [comment] 2020-08-26 00:42
Duplicate of https://github.com/dotnet/runtime/issues/31619.

**Closed by layomia** 2020-08-26 00:42 UTC
Labels: area-System.Text.Json
