### ISSUE TITLE
[API Proposal]: System.Text.JsonSerializerContext should support deserialization to private members.

### ISSUE THREAD

**Issue by voroninp** [dotnet/runtime#95385] opened 2023-11-29 08:19 UTC
### Background and motivation

Reflection-based deserialization has no problems with accessing properties with private setters when `[JsonInclude]` is applied.
Yet `JsonSerializerContext` throws an exception in this case.

Why cannot  source generator [`[UnsafeAccessor]`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.unsafeaccessorattribute?view=net-8.0) to write to the property?

```
public sealed record Foo
{
    public int Bar { get; private set; }
}

public static class BreakIntoFoo
{
    [UnsafeAccessor(UnsafeAccessorKind.Method, Name = $"set_{nameof(Foo.Bar)}")]
    public static extern void SetProp(Foo foo, int value);
}

var foo = new Foo();
BreakIntoFoo.SetProp(foo, 5);
Console.WriteLine(foo.Bar); // You see 5 here.
```

### API Proposal

Api won't not change at all, the internals should.

### API Usage

As usual.

### Risks

I assume that `UnsafeAccessorAttribute` is taken into account by the linker when trimming the app. If it's not the case, then this feature won't be trimming firendly.

**Comment by eiriktsarpalis** [comment] 2023-11-29 08:27
Duplicate of https://github.com/dotnet/runtime/issues/88519. 

Note that we wouldn't be supporting private members by default, only those annotated with the `JsonInclude` attribute. Also, `UnsafeAccessorAttribute` is only available in .NET 8 and newer versions, so this would be challenging to support in multi-targeted projects.

**Closed by eiriktsarpalis** 2023-11-29 08:27 UTC
Labels: api-suggestion, area-System.Text.Json, untriaged
