### ISSUE TITLE
In .NET 7 large number of concurrent requests will memory leak

### ISSUE THREAD

**Issue by Cricle** [dotnet/runtime#81056] opened 2023-01-12 08:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When TFM=.NET7 
`wrk -t8 -c1000 -d30s --latency http://192.168.2.86:8889`  many times, memory will grow to 1G.

When TFM=.NET6
`wrk -t8 -c1000 -d30s --latency http://192.168.2.86:8889`  many times, memory only 145M.

The Code in program

```csharp
            Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
            var builder = WebApplication.CreateBuilder(args);
            
            builder.Services.AddSingleton(new HitokotoManager(Init()));
            builder.Services.AddResponseCompression();

            var app = builder.Build();

            app.UseResponseCompression();
            app.Use(async (HttpContext builder, RequestDelegate next) =>
            {
                    //Write 1kb data in response
            });
```

### Expected Behavior

Memory will not be much larger due to long concurrent requests

### .NET Version

7.0.100

### Anything else?

.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.403 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.112 [C:\Program Files\dotnet\sdk]
  6.0.307 [C:\Program Files\dotnet\sdk]
  7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-preview.4.22251.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-preview.4.22229.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-preview.4.22229.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  arm64 [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\arm64\InstallLocation]
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by VSadov** [comment] 2023-07-15 14:38
I think I am able to reproduce this. At least I do see abnormal memory consumption on 7.0 with NativeAOT.
The numbers are not the same as reported on my machine, but there is clearly an anomaly that I cannot explain (yet) on NativeAOT.

**Comment by VSadov** [comment] 2023-07-15 15:37
I am not able to reproduce the problem with 8.0.
Both CoreCLR and NativeAOT stabilize around commit size of 100-150Mb. Considering that this is with Server GC, this is pretty good.

Possibly the bug was fixed or maybe it is still there, but scenario no longer meets conditions for it to appear.
**"use 8.0" could be a possible workaround.**

Still need to figure what is going on on 7.0. (and to be sure it is indeed fixed in 8.0)

**Comment by VSadov** [comment] 2023-07-15 15:39
With 7.0 I see CoreCLR stabilizing aroung 950 Mb commit size.
That is more than in 8.0 and there could be reasons for that. There were many improvements on the dotnet runtime and on ASP.net sides.

With NativeAOT commit size grows to multiple gigabytes. Sometimes it stabilizes around 2Gb, sometimes it goes to 8Gb and still keeps going. There is something clearly wrong in 7.0

**Comment by VSadov** [comment] 2023-07-15 15:54
The app is using 455 threads total. This is on Windows10 machine with 32 logical cores. I assume 64 threads belong to GC and the rest 391 is the app threads.
The number looks a bit high, but not completely unusual.

Same app on CoreCLR uses fewer threads (under 120 total). NativeAOT has a different threadpool on Windows, compared to CoreCLR, so we can't compare directly. 

The thread count is stable though, and should not cause memory retention. It is likely that the culprit is somewhere else.

**Comment by VSadov** [comment] 2023-07-15 19:19
@jkotas - some input on how many threads an app can have. (re: https://github.com/dotnet/runtime/pull/88772#issuecomment-1635610903 ). 
Here is an ASP.net app that runs fine (on 8.0). When seeing a large number of connections, it may use up to 400 threads on a 32-core machine.

**Comment by MichalStrehovsky** [comment] 2023-07-16 12:34
One big difference on .net 7 is that native aot doesn't use regions. We enabled regions early in 8 but on 7 jit and aot differ in this. Not sure if that could matter but calling it out

**Comment by VSadov** [comment] 2023-07-17 18:29
> One big difference on .net 7 is that native aot doesn't use regions.

This seems unlikely. Regions may help with fragmentation in huge heaps, but unlikely to help with leaks. 
I have tried turning off regions, just to be sure. That did not cause the issue to appear in 7.0 CoreCLR or in 8.0 NativeAOT.

**Comment by VSadov** [comment] 2023-07-17 18:44
When comparing stacks that cause allocations the following stands out:
It is not seen in 8.0, but 7.0 spends noticeable time there. Seeing SyncTable in profiles is pretty rare in general.

```
Name
|+ brief.api!RhpNewObject
||+ brief.api!S_P_CoreLib_System_Threading_SyncTable__AssignEntry
|||+ brief.api!S_P_CoreLib_System_Threading_Monitor__GetLock
||| + brief.api!S_P_CoreLib_System_Threading_Monitor__Enter_0
|||  + brief.api!Microsoft_Extensions_DependencyInjection_Microsoft_Extensions_DependencyInjection_ServiceLookup_ServiceProviderEngineScope__BeginDispose
|||  |+ brief.api!Microsoft_Extensions_DependencyInjection_Microsoft_Extensions_DependencyInjection_ServiceLookup_ServiceProviderEngineScope__DisposeAsync
|||  | + brief.api!Microsoft_AspNetCore_Http_Microsoft_AspNetCore_Http_Features_RequestServicesFeature__DisposeAsync
|||  |  + brief.api!Microsoft_AspNetCore_Http_Abstractions_Microsoft_AspNetCore_Http_HttpResponse___c____cctor_b__35_1
|||  |   + brief.api!Microsoft_AspNetCore_Server_Kestrel_Core_Microsoft_AspNetCore_Server_Kestrel_Core_Internal_Http_HttpProtocol___FireOnCompleted_g__ProcessEvents_242_0_d__MoveNext
|||  |    + brief.api!S_P_CoreLib_System_Runtime_CompilerServices_AsyncMethodBuilderCore__Start
|||  |     + brief.api!Microsoft_AspNetCore_Server_Kestrel_Core_Microsoft_AspNetCore_Server_Kestrel_Core_Internal_Http_HttpProtocol___FireOnCompleted_g__ProcessEvents_242_0
|||  |      + brief.api!Microsoft_AspNetCore_Server_Kestrel_Core_Microsoft_AspNetCore_Server_Kestrel_Core_Internal_Http_HttpProtocol__ProcessRequests_d__238_1__MoveNext
|||  |       + brief.api!S_P_CoreLib_System_Threading_ExecutionContext__RunFromThreadPoolDispatchLoop
|||  |        + brief.api!S_P_CoreLib_System_Runtime_CompilerServices_AsyncTaskMethodBuilder_1_AsyncStateMachineBox_1>__MoveNext_0
|||  |         + brief.api!S_P_CoreLib_System_Threading_ThreadPoolWorkQueue__Dispatch
|||  |          + brief.api!S_P_CoreLib_System_Threading_ThreadPool__DispatchCallback
|||  |           + ntdll!TppWorkpExecuteCallback
|||  |            + ntdll!TppWorkerThread
|||  |             + kernel32!BaseThreadInitThunk
|||  |              + ntdll!RtlUserThreadStart
|||  |               + AllThreads
|||  |                + Process64 Brief.Api (29992) Args:  --urls http://*:8889
```

The reson for this allocation is that `ServiceProviderEngineScope.BeginDispose` takes a lock on its private dictionary.
NativeAOT in 7.0 did not have thin locks yet, so this means allocating a fat lock for each `ServiceProviderEngineScope` (does this happen for each HTTP request?)

The fat locks can in theory add up, but should not leak. 

Perhaps finalizer thread cannot keep up with reclaiming so many locks. 
(although reclaiming is a fairly cheap operation, at least relative to creating a fat lock, so it should keep up).

**Comment by davidfowl** [comment] 2023-07-17 20:03
There are 2 main dictionaries in the DI container implementation, the one that stores registrations (global) and one allocated per request to store scoped instances. The latter is likely what you’re seeing. It stores object graphs for scopes instances instantiated by the container. 

Interesting to see how expensive that lock is on native AOT

**Comment by VSadov** [comment] 2023-07-17 20:19
Interestingly, disabling thin locks (so that every lock would allocate a lock object vs. alloc-free use of sync bits), and disabling regions (to be sure) still does not make the bug to surface on 8.0 NativeAOT.

Runtime churns through a lot of lock objects, but everything seems to be reclaimed orderly and promptly (as expected). 
The high watermark for the fat lock count that I see is about 66K, which is basically in a "not a big deal" range and a lot less than 5.3M on 7.0.

**Comment by VSadov** [comment] 2023-07-17 20:48
> Interesting to see how expensive that lock is on native AOT

On 8.0 the cost of lock is the Lock object (3 nints) + `DeadEntryCollector` (1 int) + dependent handle. 
It is not a lot - I'd round it up to 60 bytes or so. CoreCLR would have comparable expenses. 

You'd typically need to go out of your way to make locks themselves a problem (before what they are protecting is already a problem). 

Also note that neither CoreCLR nor NativeAOT will create lock objects, if they can get away with just using sync bits in the object header. Trivial noncontending uses of `lock` statements would not allocate anything. 
This part (thin locks) was NYI in 7.0 for NativeAOT

However not having thin locks does not seem the root cause here. Taking out the feature does not cause the bug to appear.

**Comment by VSadov** [comment] 2023-07-17 21:37
> Also note that neither CoreCLR nor NativeAOT will create lock objects if they can get away with just using sync bits

For the perspective on this - with thin locks enabled this app has **fat lock watermark at 8** on NativeAOT 8.0 
And these locks seem to be long-lived as I do not see any recycling of entries in the steady state of the app. 

Compared to up to 66K of simultaneous lock instances needed otherwise, thin locks is a quite impressive optimization.

**Comment by VSadov** [comment] 2023-07-18 00:11
Ok, all the stuff about locks can be ignored. it is interesting, but not the root cause here.

The actual reason for the "leak" is simply because server GC gets really lazy for this scenario and does not collect very often. I see just one GC happening every few seconds and that sems to be Gen0.

- There is no "leak" observed if workstation GC is used.
(as in `set DOTNET_gcServer=0`)

- It is also possible to limit the "leak" by forcing GC once in a while.
Commit size stays within 20-30% of CoreCLR, with something like:

```cs
        public static Thread gcForcer = new Thread(
                () =>
                {
                    for (; ; )
                    {
                        // force a GC once a while. It does not need to be blocking.
                        GC.Collect(2, GCCollectionMode.Forced, blocking: false);
                        Thread.Sleep(10000);
                    }
                }
             );

        public static async Task Main(string[] args)
        {
            gcForcer.Start();
```

In a way GC is not completely wrong here - there is plenty of RAM on the machine and it can afford 8Gb heap, but the expectations are clearly that it collects more often.  
I do not think the NativeAOT runtime can change anything to fix this behavior. 

I am not sure what changed in 8.0 that this scenario no longer reproduces (regardless of regions turned on or off). 
Perhaps GC tunnings have changed or something got fixed? 

@mangod9 - I think GC team needs to take a look.

It is also possible that something changed in ASP.net/`DependencyInjection` and the app no longer meets the pattern that causes GC to be lazy.  

Either way - something changed that caused GC to be less lazy for this scenario in 8.0. Porting that change to 7.0, if possible, would be the likely fix.

**Comment by sgf** [comment] 2024-08-09 03:28
On a 1GB RAM cloud Windows OS, the page file is not set. The available memory is about 400MB,
.net AOT Hello World command line cannot start. Because of its OOM.
But the application, does not enter the Main method at all, which causes, in cmd, it does not show any text.

**Comment by Cricle** [comment] 2024-08-12 01:29
I think this has already been resolved in net8.0. I try to compile AOT with net8.0, and use ab.exe to benchmark. The memory is normal.

**Comment by MichalStrehovsky** [comment] 2024-08-12 12:55
> I think this has already been resolved in net8.0. I try to compile AOT with net8.0, and use ab.exe to benchmark. The memory is normal.

Thank you for checking!

**Closed by MichalStrehovsky** 2024-08-12 12:55 UTC
Labels: area-GC-coreclr
