### ISSUE TITLE
Test failure tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.sh

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#80679] opened 2023-01-16 05:48 UTC
Run: [runtime-coreclr r2r-extra 20230114.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=138050&view=ms.vss-test-web.build-test-results-tab&runId=3001764&resultId=121733&paneView=debug)

Failed test:
```
R2R-CG2 linux arm Checked forcerelocs @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7

- tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.sh
```
**Error message:**
```
/root/helix/work/workitem/e/tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.sh: line 302: -r:/root/helix/work/workitem/e/tracing/eventpipe/eventsourceerror/eventsourceerror/IL-CG2/*.dll: No such file or directory
[createdump] waitpid() returned successfully (wstatus 00000000)
/root/helix/work/workitem/e/tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.sh: line 441: 10679 Segmentation fault      (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/tracing.eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/root/helix/work/workitem/e/tracing/eventpipe/eventsourceerror/eventsourceerror/IL-CG2/common.dll
04:07:13
Response file: /root/helix/work/workitem/e/tracing/eventpipe/eventsourceerror/eventsourceerror/common.dll.rsp
/root/helix/work/workitem/e/tracing/eventpipe/eventsourceerror/eventsourceerror/IL-CG2/common.dll
-o:/root/helix/work/workitem/e/tracing/eventpipe/eventsourceerror/eventsourceerror/common.dll
-r:/root/helix/work/correlation/System..dll
-r:/root/helix/work/correlation/Microsoft..dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--method-layout:random
--targetarch:arm
--targetos:linux
-O
Running CrossGen2:  dotnet /root/helix/work/correlation/crossgen2/crossgen2.dll @/root/helix/work/workitem/e/tracing/eventpipe/eventsourceerror/eventsourceerror/common.dll.rsp

Emitting R2R PE file: /root/helix/work/workitem/e/tracing/eventpipe/eventsourceerror/eventsourceerror/common.dll
Running R2RDump:  dotnet /root/helix/work/correlation/R2RDump/R2RDump.dll --header --sc --in /root/helix/work/workitem/e/tracing/eventpipe/eventsourceerror/eventsourceerror/common.dll --out /root/helix/work/workitem/e/tracing/eventpipe/eventsourceerror/eventsourceerror/common.dll.r2rdump --val
04:07:19
/root/helix/work/workitem/e/tracing/eventpipe/eventsourceerror/eventsourceerror/IL-CG2/eventsourceerror.dll
04:07:19
Response file: /root/helix/work/workitem/e/tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.dll.rsp
/root/helix/work/workitem/e/tracing/eventpipe/eventsourceerror/eventsourceerror/IL-CG2/eventsourceerror.dll
-o:/root/helix/work/workitem/e/tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.dll
-r:/root/helix/work/correlation/System..dll
-r:/root/helix/work/correlation/Microsoft..dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--method-layout:random
--targetarch:arm
--targetos:linux
-O
Running CrossGen2:  dotnet /root/helix/work/correlation/crossgen2/crossgen2.dll @/root/helix/work/workitem/e/tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.dll.rsp

Emitting R2R PE file: /root/helix/work/workitem/e/tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.dll
Running R2RDump:  dotnet /root/helix/work/correlation/R2RDump/R2RDump.dll --header --sc --in /root/helix/work/workitem/e/tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.dll --out /root/helix/work/workitem/e/tracing/eventpipe/eventsourceerror/eventsourceerror/eventsourceerror.dll.r2rdump --val
04:07:25
/root/helix/work/workitem/e/tracing/eventpipe/eventsourceerror/eventsourceerror/IL-CG2/Microsoft.Diagnostics.NETCore.Client.dll
04:07:25
Response file: /root/helix/work/workitem/e/tracing/eventpipe/eventsourceerror/eventsourceerror/Microsoft.Diagnostics.NETCore.Client.dll.rsp
/root/helix/work/workitem/e/tracing/eventpipe/eventsourceerror/eventsourceerror/IL-CG2/Microsoft.Diagnostics.NETCore.Client.dll
-o:/root/helix/work/workitem/e/tracing/eventpipe/eventsourceerror/eventsourceerror/Microsoft.Diagnostics.NETCore.Client.dll
-r:/root/helix/work/correlation/System..dll
-r:/root/helix/work/correlation/Microsoft..dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--method-layout:random
--targetarch:arm
--tar


Stack trace
   at tracing_eventpipe._eventsourceerror_eventsourceerror_eventsourceerror_._eventsourceerror_eventsourceerror_eventsourceerror_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by kunalspathak** [comment] 2023-01-18 17:32
Duplicate of https://github.com/dotnet/runtime/issues/80666

**Closed by kunalspathak** 2023-01-18 17:32 UTC
Labels: os-linux, area-crossgen2-coreclr, untriaged, blocking-clean-ci-optional
