### ISSUE TITLE
[release/7.0] Could not load file or assembly System.Text.Json Version=7.0.0.0,or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#77988] opened 2022-11-07 20:08 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=72698
Build error leg or test failing: Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled
Pull request: https://github.com/dotnet/runtime/pull/77187

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section).

```json
{
  "ErrorMessage": "The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)",
  "BuildRetry": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[83072](https://dev.azure.com/dnceng-public/public/_build/results?buildId=83072)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=83072&view=ms.vss-test-web.build-test-results-tab&runId=1736448&resultId=102767)||
|[82919](https://dev.azure.com/dnceng-public/public/_build/results?buildId=82919)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=82919&view=ms.vss-test-web.build-test-results-tab&runId=1733300&resultId=102386)|dotnet/runtime#78333|
|[82880](https://dev.azure.com/dnceng-public/public/_build/results?buildId=82880)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=82880&view=ms.vss-test-web.build-test-results-tab&runId=1731480&resultId=102409)|dotnet/runtime#78331|
|[81499](https://dev.azure.com/dnceng-public/public/_build/results?buildId=81499)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=81499&view=ms.vss-test-web.build-test-results-tab&runId=1702208&resultId=102237)|dotnet/runtime#78273|
|[80982](https://dev.azure.com/dnceng-public/public/_build/results?buildId=80982)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=80982&view=ms.vss-test-web.build-test-results-tab&runId=1701776&resultId=102359)|dotnet/runtime#78256|
|[81193](https://dev.azure.com/dnceng-public/public/_build/results?buildId=81193)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=81193&view=ms.vss-test-web.build-test-results-tab&runId=1698292&resultId=102135)||
|[81098](https://dev.azure.com/dnceng-public/public/_build/results?buildId=81098)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=81098&view=ms.vss-test-web.build-test-results-tab&runId=1694942&resultId=102606)|dotnet/runtime#78258|
|[80937](https://dev.azure.com/dnceng-public/public/_build/results?buildId=80937)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=80937&view=ms.vss-test-web.build-test-results-tab&runId=1691090&resultId=102233)||
|[80500](https://dev.azure.com/dnceng-public/public/_build/results?buildId=80500)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=80500&view=ms.vss-test-web.build-test-results-tab&runId=1689826&resultId=102224)|dotnet/runtime#78235|
|[80837](https://dev.azure.com/dnceng-public/public/_build/results?buildId=80837)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=80837&view=ms.vss-test-web.build-test-results-tab&runId=1689094&resultId=102357)||
|[80506](https://dev.azure.com/dnceng-public/public/_build/results?buildId=80506)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=80506&view=ms.vss-test-web.build-test-results-tab&runId=1683402&resultId=102194)|dotnet/runtime#77831|
|[79957](https://dev.azure.com/dnceng-public/public/_build/results?buildId=79957)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=79957&view=ms.vss-test-web.build-test-results-tab&runId=1682894&resultId=102272)|dotnet/runtime#77831|
|[80467](https://dev.azure.com/dnceng-public/public/_build/results?buildId=80467)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=80467&view=ms.vss-test-web.build-test-results-tab&runId=1682118&resultId=102263)||
|[80462](https://dev.azure.com/dnceng-public/public/_build/results?buildId=80462)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=80462&view=ms.vss-test-web.build-test-results-tab&runId=1681958&resultId=102215)||
|[78936](https://dev.azure.com/dnceng-public/public/_build/results?buildId=78936)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=78936&view=ms.vss-test-web.build-test-results-tab&runId=1676418&resultId=102327)|dotnet/runtime#78147|
|[79254](https://dev.azure.com/dnceng-public/public/_build/results?buildId=79254)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=79254&view=ms.vss-test-web.build-test-results-tab&runId=1672028&resultId=102108)|dotnet/runtime#78178|
|[80014](https://dev.azure.com/dnceng-public/public/_build/results?buildId=80014)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=80014&view=ms.vss-test-web.build-test-results-tab&runId=1671748&resultId=102196)||
|[79977](https://dev.azure.com/dnceng-public/public/_build/results?buildId=79977)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=79977&view=ms.vss-test-web.build-test-results-tab&runId=1671156&resultId=102639)||
|[79966](https://dev.azure.com/dnceng-public/public/_build/results?buildId=79966)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=79966&view=ms.vss-test-web.build-test-results-tab&runId=1670688&resultId=102215)|dotnet/runtime#78107|
|[79962](https://dev.azure.com/dnceng-public/public/_build/results?buildId=79962)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=79962&view=ms.vss-test-web.build-test-results-tab&runId=1670686&resultId=102408)|dotnet/runtime#78122|
|[79320](https://dev.azure.com/dnceng-public/public/_build/results?buildId=79320)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=79320&view=ms.vss-test-web.build-test-results-tab&runId=1666168&resultId=102642)||
|[79788](https://dev.azure.com/dnceng-public/public/_build/results?buildId=79788)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=79788&view=ms.vss-test-web.build-test-results-tab&runId=1666054&resultId=102230)||
|[79711](https://dev.azure.com/dnceng-public/public/_build/results?buildId=79711)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=79711&view=ms.vss-test-web.build-test-results-tab&runId=1664910&resultId=104059)||
|[79209](https://dev.azure.com/dnceng-public/public/_build/results?buildId=79209)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=79209&view=ms.vss-test-web.build-test-results-tab&runId=1665170&resultId=102247)|dotnet/runtime#78174|
|[78162](https://dev.azure.com/dnceng-public/public/_build/results?buildId=78162)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=78162&view=ms.vss-test-web.build-test-results-tab&runId=1665008&resultId=102272)|dotnet/runtime#78118|
|[77991](https://dev.azure.com/dnceng-public/public/_build/results?buildId=77991)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=77991&view=ms.vss-test-web.build-test-results-tab&runId=1661216&resultId=104083)|dotnet/runtime#78122|
|[78956](https://dev.azure.com/dnceng-public/public/_build/results?buildId=78956)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=78956&view=ms.vss-test-web.build-test-results-tab&runId=1661060&resultId=103830)|dotnet/runtime#78149|
|[78488](https://dev.azure.com/dnceng-public/public/_build/results?buildId=78488)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=78488&view=ms.vss-test-web.build-test-results-tab&runId=1661024&resultId=105829)|dotnet/runtime#77612|
|[73673](https://dev.azure.com/dnceng-public/public/_build/results?buildId=73673)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=73673&view=ms.vss-test-web.build-test-results-tab&runId=1660994&resultId=103752)|dotnet/runtime#77924|
|[79507](https://dev.azure.com/dnceng-public/public/_build/results?buildId=79507)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=79507&view=ms.vss-test-web.build-test-results-tab&runId=1660956&resultId=103103)|dotnet/runtime#78107|
|[77848](https://dev.azure.com/dnceng-public/public/_build/results?buildId=77848)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=77848&view=ms.vss-test-web.build-test-results-tab&runId=1660930&resultId=102133)|dotnet/runtime#77831|
|[78569](https://dev.azure.com/dnceng-public/public/_build/results?buildId=78569)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=78569&view=ms.vss-test-web.build-test-results-tab&runId=1660696&resultId=102228)|dotnet/runtime#77818|
|[75353](https://dev.azure.com/dnceng-public/public/_build/results?buildId=75353)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=75353&view=ms.vss-test-web.build-test-results-tab&runId=1556424&resultId=102271)||
|[72698](https://dev.azure.com/dnceng-public/public/_build/results?buildId=72698)|dotnet/runtime|[Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled](https://dev.azure.com/dnceng-public/public/_build/results?buildId=72698&view=ms.vss-test-web.build-test-results-tab&runId=1555598&resultId=102227)|dotnet/runtime#77187|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|34|

**Comment by carlossanlop** [comment] 2022-11-07 20:09
@dotnet/area-system-text-json this is an error coming from System.Text.Json btw.

**Comment by carlossanlop** [comment] 2022-11-09 20:39
Another 7.0 PR affected (unrelated change: it is just bumping the emscripten dependencies): https://github.com/dotnet/runtime/pull/77818
Job: https://dev.azure.com/dnceng-public/public/_build/results?buildId=76759&view=logs&j=bcd0b573-6223-5b97-9574-b5bb8414cd58&t=77990c5a-bddc-5d6f-6f2e-eea0cb8098e6&l=51
Log file: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-77818-merge-4dc7fa30176d46c786/Microsoft.Extensions.Logging.Console.Tests/1/console.fc56e2dd.log?helixlogtype=result

**Comment by carlossanlop** [comment] 2022-11-10 20:30
Also showed up in the PR to update the arcade dependencies: https://github.com/dotnet/runtime/pull/78107

Queue: `Libraries Build windows net48 x86 Release`
Job: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-78107-merge-ec3bc7608be8448d9f/Microsoft.Extensions.Logging.Console.Tests/1/console.5693599f.log?helixlogtype=result 
Log file: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-78107-merge-ec3bc7608be8448d9f/Microsoft.Extensions.Logging.Console.Tests/1/console.5693599f.log?helixlogtype=result
```
===========================================================================================================

C:\h\w\B85E09BA\w\B5100980\e>xunit.console.exe Microsoft.Extensions.Logging.Console.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: Microsoft.Extensions.Logging.Console.Tests (app domain = on [no shadow copy], method display = ClassAndMethod, method display options = None)
  Discovered:  Microsoft.Extensions.Logging.Console.Tests (found 110 of 112 test cases)
  Starting:    Microsoft.Extensions.Logging.Console.Tests (parallel test collections = on, max threads = 2)

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Text.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.Extensions.Logging.ConsoleLoggerExtensions.AddConsole(ILoggingBuilder builder)
   at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection services, Action`1 configure)
   at Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.<>c.<AddConsole_IsOutputRedirected_ColorDisabled>b__21_0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args)
    Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.AddConsole_IsOutputRedirected_ColorDisabled [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:
        
        Child exception:
          System.IO.FileLoadException: Could not load file or assembly 'System.Text.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
        File name: 'System.Text.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
           at Microsoft.Extensions.Logging.ConsoleLoggerExtensions.AddConsole(ILoggingBuilder builder)
           at Microsoft.Extensions.DependencyInjection.LoggingServiceCollectionExtensions.AddLogging(IServiceCollection services, Action`1 configure)
           at Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest.<>c.<AddConsole_IsOutputRedirected_ColorDisabled>b__21_0()
        
        WRN: Assembly binding logging is turned OFF.
        To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
        Note: There is some performance penalty associated with assembly bind failure logging.
        To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
        
        
        Child process:
          Microsoft.Extensions.Logging.Console.Tests, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 Microsoft.Extensions.Logging.Console.Test.ConsoleLoggerTest+<>c Void <AddConsole_IsOutputRedirected_ColorDisabled>b__21_0()
        
        
  Finished:    Microsoft.Extensions.Logging.Console.Tests
=== TEST EXECUTION SUMMARY ===
   Microsoft.Extensions.Logging.Console.Tests  Total: 621, Errors: 0, Failed: 1, Skipped: 0, Time: 3.921s
----- end Thu 11/10/2022 18:29:41.14 ----- exit code 1 ----------------------------------------------------------
```

**Comment by carlossanlop** [comment] 2022-11-10 20:36
It seems this problem started after this PR got merged: https://github.com/dotnet/runtime/pull/73737 which introduced some System.Text.Json code in the affected tests.

Pinging @dotnet/area-extensions-logging for help fixing this.

**Comment by tarekgh** [comment] 2022-11-10 20:49
CC @eerhardt

**Comment by eerhardt** [comment] 2022-11-10 22:13
> It seems this problem started after this 7.0 PR got merged: https://github.com/dotnet/runtime/pull/73737

That PR was merged 3 months ago. How would that have caused this to start happening in the past week?

**Comment by carlossanlop** [comment] 2022-11-10 22:22
Hmm I can be wrong too. But it's the last change that this test project received in 7.0, and the addition of S.T.Json code was a big coincidence. I am also not seeing the same problem in any other test projects (so far).

**Comment by eerhardt** [comment] 2022-11-10 22:24
All the failures appear to be on .NET Framework. My suspicion is that something changed in the build infra or on .NET Framework that caused this to start failing. I don't think a PR from 3 months ago would have caused this, unless it has been failing for the last 3 months.

**Comment by eerhardt** [comment] 2022-11-10 22:50
Looking at the binlog, it looks like it is picking up `7.0.1` of STJ for some reason:

![image](https://user-images.githubusercontent.com/8291187/201222488-3cf2dac6-5bfe-4234-8d55-f55b92a74f2f.png)

I believe this is the issue.

**Comment by eerhardt** [comment] 2022-11-10 22:52
Looks like the `7.0.1` change came in 8 days ago - which aligns with when this started failing:  https://github.com/dotnet/runtime/pull/77388.

**Comment by tarekgh** [comment] 2022-11-10 23:05
Could it be desktop binding redirect issue? 

@carlossanlop do you know if there any other tests failing for the same reason? 

CC @ericstj

**Comment by eerhardt** [comment] 2022-11-10 23:06
> Could it be desktop binding redirect issue?

Yes - that is what I am saying above.

To investigate this, I would download the test .zip file, and inspect which assembly is compiled against `Version=7.0.0.0` of System.Text.Json. Now that the above servicing change is in, it should be compiled against `Version=7.0.0.1`.

**Comment by tarekgh** [comment] 2022-11-11 03:13
This is interesting, locally I built the runtime as `x86` and runs the test and it passes. on my machine both the test and the library referencing `7.0.0.0`. but on the CI run the test was using `7.0.0.1` while the library was using `7.0.0.0`.

**Comment by ericstj** [comment] 2022-11-11 16:24
Normally binding redirects would be automatically generated if the references in the test required them - but that would require the mismatch to be seen at compile time.

It looks to me like that's not happening (.0 references in the assemblies and no binding redirects).  If I had to guess this is a problem with the selection of reference assemblies passed as project references assemblies during build.

I would expect that the net4x build of M.E.Console would get the net4x build of System.Text.Json with a 7.0.0.1 version, and the test would get the same.  A binlog of the build of would show if this were the case or not.

**Comment by ericstj** [comment] 2022-11-11 17:40
I’m away from the computer right now, but I think I thought of the problem. It looks like packaging.targets is what defines the incremented assembly version and that’s only included. When IsPackable is set which wouldn’t be the case for the reference assembly projects. @ViktorHofer

**Comment by joperezr** [comment] 2022-11-11 17:53
I took a quick peek at the issue. Seems like the tests are correctly building against 7.0.0.1 version of System.Text.Json, the issue here is that the implementation assembly `Microsoft.Extensions.Logging.Console` is building against 7.0.0.0, and seems like we don't have a binding redirect to unify those versions so when the implementation assembly tries to load S.T.J that is when things crash.

**Comment by joperezr** [comment] 2022-11-11 18:24
After looking at the binlog, seems like the issue is that the implementation of `Microsoft.Extensions.Logging.Console` is building against the net462 ref of `System.Text.Json` which is 7.0.0.0, but the tests `Microsoft.Extensions.Logging.Console.Tests` are building against the net462 implementation of `System.Text.Json` which is 7.0.0.1. It would be good to fix that discrepancy, but even then things should theoretically work as long as the tests are producing a dllconfig with binding redirects, which is not happening for some reason. I have to step out for a bit, but I will continue the investigation later today.

**Comment by ViktorHofer** [comment] 2022-11-11 20:14
> I’m away from the computer right now, but I think I thought of the problem. It looks like packaging.targets is what defines the incremented assembly version and that’s only included. When IsPackable is set which wouldn’t be the case for the reference assembly projects. @ViktorHofer


@ericstj sounds like https://github.com/dotnet/runtime/issues/63467?

**Comment by ericstj** [comment] 2022-11-11 20:47
I knew this looked familiar. I remember looking at it with @eerhardt. Do you recall doing anything about it in 6.0?

Perhaps the smallest change here would be to not use the reference assembly projects for p2ps when IsPackable is true, or perhaps as a smaller change just do that for net4x configurations.

**Comment by joperezr** [comment] 2022-11-11 20:56
I actually think that the smallest change to fix this would be just to set two properties in order to make sure that auto binding redorects are created correctly. I haven't been able to validate this as I'm away from my desk but I'll try it out in a bit.

**Comment by joperezr** [comment] 2022-11-11 21:32
Yup, I have now validated that if you just add `<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>` property into the `Microsoft.Extensions.Logging.Console.Tests` project the binding redirects are now produced into the dll.config file and the tests pass successfully:

![image](https://user-images.githubusercontent.com/13854455/201433780-75081813-eede-4615-8b39-9f767a141d51.png)

**Comment by ericstj** [comment] 2022-11-12 00:37
If we can build against correctly versioned reference we should.  Reduce the cases where we require redirects.

**Comment by joperezr** [comment] 2022-11-12 00:46
That's fine by me. That said, that's a change that probably should be made in main first and later cherry picked to release branch. I would suggest to, in the mean time, merge the pr I have opened in release that would fix the build and tests by generating redirects, and we can later remove that once we have the reference version fixes ready.

**Comment by eerhardt** [comment] 2022-11-14 16:18
> I knew this looked familiar. I remember looking at it with @eerhardt. Do you recall doing anything about it in 6.0?

I thought I remembered this issue as well, but couldn't find it last week. For release/6.0 to work around the issue, I did this:

https://github.com/dotnet/runtime/blob/ce7aaecf99f9faf7cfe878fd1f3851e8f6e72567/src/libraries/Microsoft.Extensions.Hosting/tests/UnitTests/Microsoft.Extensions.Hosting.Unit.Tests.csproj#L21-L25

**Comment by ViktorHofer** [comment] 2022-11-25 10:33
Fixed by https://github.com/dotnet/runtime/pull/78730

**Closed by ViktorHofer** 2022-11-25 10:33 UTC
Labels: area-Infrastructure-libraries, blocking-clean-ci, Known Build Error
