### ISSUE TITLE
[System.Text.Json] CamelCase DictionaryKeyPolicy for array value or list value

### ISSUE THREAD

**Issue by leopripos** [dotnet/runtime#33508] opened 2020-03-12 05:59 UTC
For List value:
```cshap
var dictionary = new Dictionary<string, List<string>>
{
    { "Test", new List<string>{ "Value1", "Value2" } }
};

var json = JsonSerializer.Serialize(dictionary, new JsonSerializerOptions { 
    DictionaryKeyPolicy = JsonNamingPolicy.CamelCase 
});
Console.WriteLine(json); // Outputs: {"Test": ["Value1", "Value2"]}
```
For Array Value:
```cssharp
var dictionary = new Dictionary<string, string[]>
{
    { "Test", new string[]{ "Value1", "Value2" } }
};

var json = JsonSerializer.Serialize(dictionary, new JsonSerializerOptions { 
    DictionaryKeyPolicy = JsonNamingPolicy.CamelCase 
});
Console.WriteLine(json); // Outputs: {"Test": ["Value1", "Value2"]}
```

Expected Result: `{"test": ["Value1", "Value2"]}`

**Comment by layomia** [comment] 2020-03-13 21:55
This is a duplicate of https://github.com/dotnet/runtime/issues/30889 and was fixed for 5.0 in https://github.com/dotnet/corefx/pull/41691. Can you try the fix in 5.0?

**Closed by layomia** 2020-03-13 21:55 UTC
Labels: area-System.Text.Json

**Comment by leopripos** [comment] 2020-03-15 17:59
@layomia Yes, fixed. What about core 3.1 LTS? any update plan?

**Comment by layomia** [comment] 2020-03-26 15:12
This doesn't meet the bar for servicing at this point. It is also too late to make such a breaking change to 3.1 LTS.
