### ISSUE TITLE
Error when running WPF app published with Trim option.

### ISSUE THREAD

**Issue by lucent-sea** [dotnet/runtime#46252] opened 2020-12-19 17:01 UTC
### Description

I get the below error when trying to run a WPF app published with the Trim option.  It's reproducible with the default WPF template project too.

Repro Steps:

- Create .NET WPF app from default project template.
- Change the target framework to .NET 5 (the template still has Core 3.1 selected)
- Create a folder publish profile that's self-contained and has trim selected.
- After publishing, try to run the EXE.
- Observe the below error in Event Viewer.

Example Project:
[WpfApp1.zip](https://github.com/dotnet/runtime/files/5719841/WpfApp1.zip)

```
Log Name:      Application
Source:        Application Error
Date:          12/19/2020 8:46:17 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Maker
Description:
Faulting application name: WpfApp1.exe, version: 1.0.0.0, time stamp: 0x5fbf100e
Faulting module name: KERNELBASE.dll, version: 10.0.19041.662, time stamp: 0xec58f015
Exception code: 0xe0434352
Fault offset: 0x000000000002d759
Faulting process id: 0x4dc0
Faulting application start time: 0x01d6d62677df205c
Faulting application path: D:\repos\WpfApp1\WpfApp1\bin\Release\net5.0-windows\publish\WpfApp1.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: dfc16fb5-0078-418a-97a8-c1cef8749b80
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-12-19T16:46:17.5941365Z" />
    <EventRecordID>59343</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>Maker</Computer>
    <Security />
  </System>
  <EventData>
    <Data>WpfApp1.exe</Data>
    <Data>1.0.0.0</Data>
    <Data>5fbf100e</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.662</Data>
    <Data>ec58f015</Data>
    <Data>e0434352</Data>
    <Data>000000000002d759</Data>
    <Data>4dc0</Data>
    <Data>01d6d62677df205c</Data>
    <Data>D:\repos\WpfApp1\WpfApp1\bin\Release\net5.0-windows\publish\WpfApp1.exe</Data>
    <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data>dfc16fb5-0078-418a-97a8-c1cef8749b80</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```
If you create a new .NET WPF project, change the target framework from Core 3.1 to .NET 5 (the template still has the wrong target), create a folder

### Configuration

- Windows 10, version 20H2
- Visual Studio 2019 Community Edition, version 16.8.3
- Dotnet SDK 5.0.101

### Regression?

Self-contained, trimmed publishing used to work for my WPF app before migrating to .NET 5: https://github.com/lucent-sea/Remotely/tree/master/Desktop.Win

**Comment by lucent-sea** [comment] 2020-12-19 22:38
I forgot to include the event that had the stack trace:

```
Application: WpfApp1.exe
CoreCLR Version: 5.0.120.57516
.NET Version: 5.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Windows.Markup.XamlParseException: The type initializer for 'System.Windows.Window' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.Windows.FrameworkElement' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.Windows.Documents.TextElement' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.Windows.Documents.Typography' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Windows.Media.TextFormatting.TextRunTypographyProperties.OnPropertiesChanged()
   at MS.Internal.Text.TypographyProperties.ResetProperties()
   at MS.Internal.Text.TypographyProperties..ctor()
   at System.Windows.Documents.Typography..cctor()
   --- End of inner exception stack trace ---
   at System.Windows.Documents.TextElement..cctor()
   --- End of inner exception stack trace ---
   at System.Windows.FrameworkElement..cctor()
   --- End of inner exception stack trace ---
   at System.Windows.Window..cctor()
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.WrappedInvoke(Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.WrappedInvoke(Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at System.Windows.Threading.Dispatcher.Invoke(DispatcherPriority priority, Delegate method, Object arg)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at WpfApp1.App.Main()
```

**Comment by vitek-karas** [comment] 2020-12-19 23:04
This is a duplicate of https://github.com/dotnet/sdk/issues/14261.

**Closed** 2020-12-19 23:06 UTC
Labels: area-Host, linkable-framework, untriaged
