### ISSUE TITLE
[Blazor WASM] InvariantGlobalization causes error after upgrading to .Net 6 Preview 6

### ISSUE THREAD

**Issue by srpeirce** [dotnet/runtime#55750] opened 2021-07-14 23:25 UTC
### Describe the bug
In .Net6-preview-6, Blazor WASM apps stop working when enabling `InvariantGlobalization`.
It worked in .Net 6 preview 5.

### To Reproduce
Example:
https://github.com/srpeirce/Blazor6-6/blob/main/Blazor6-6.Web/Blazor6-6.Web.csproj

Install dotnet 6 preview 6.

Create a new blazor project.
Run the project - it works!

Goto csproj and add:
`<InvariantGlobalization>true</InvariantGlobalization>`

The Blazor app now fails to load, with error in console.

### Exceptions (if any)
![image](https://user-images.githubusercontent.com/12847647/125705109-a6250fd3-f096-469f-9b0e-8a70f34df7da.png)

```
dotnet.6.0.0-preview.6.21352.12.js:1 /__w/1/s/src/mono/mono/metadata/icall.c:6619 <disabled>
550895 @ dotnet.6.0.0-preview.6.21352.12.js:1
blazor.webassembly.js:1 undefined
window.Module.s.printErr @ blazor.webassembly.js:1
blazor.webassembly.js:1 RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
    at abort (dotnet.6.0.0-preview.6.21352.12.js:1)
    at _abort (dotnet.6.0.0-preview.6.21352.12.js:1)
    at <anonymous>:wasm-function[5994]:0x13d6ec
    at <anonymous>:wasm-function[2461]:0x78f19
    at <anonymous>:wasm-function[2187]:0x6130b
    at <anonymous>:wasm-function[6671]:0x15d556
    at <anonymous>:wasm-function[6495]:0x154eb0
    at <anonymous>:wasm-function[3347]:0xa8bfc
    at <anonymous>:wasm-function[676]:0x1646f
    at <anonymous>:wasm-function[304]:0xa0b5
```

### Further technical details
Dotnet version: `6.0.100-preview.6.21355.2`

**Comment by mkArtakMSFT** [comment] 2021-07-15 16:42
@lewing FYI

**Comment by lewing** [comment] 2021-07-15 19:01
cc @eerhardt

**Comment by lewing** [comment] 2021-07-15 22:12
This reproduces easily with a template app I don't think my team has touched InvariantGlobalization so I suspect this is from https://github.com/dotnet/runtime/pull/53453 and is due to the different startup sequence Blazor uses.

**Comment by eerhardt** [comment] 2021-07-15 22:32
An interesting observation I had here is that if I `dotnet publish -c Release` the app with `InvariantGlobalization=true`, the app now loads and works correctly. It appears to only be an issue in the untrimmed/unpublished app.

**Comment by pavelsavara** [comment] 2021-07-16 14:02
I noticed that we also set `this.mono_wasm_setenv ("DOTNET_SYSTEM_GLOBALIZATION_PREDEFINED_CULTURES_ONLY", "1")` which I didn't see in blazor code. But I don't understand the whole picture yet.

**Comment by eerhardt** [comment] 2021-07-16 14:35
looking at the error - this isn't an exception from .NET code, right? We would actually get a decent error message if .NET code was throwing an exception. This is a runtime error in the native code is my assumption.

**Comment by pavelsavara** [comment] 2021-07-16 16:11
Maybe related, but I'm not confident. https://github.com/dotnet/runtime/issues/55838

**Comment by pavelsavara** [comment] 2021-07-27 16:17
Replicated with local debug build of runtime.
```
Process terminated due to "Unable to load required ICU Globalization data. Please see https://aka.ms/dotnet-missing-libicu for more information"
632114	@	dotnet.6.0.0-preview.7.21360.10.js:1424
_emscripten_asm_const_int	@	dotnet.6.0.0-preview.7.21360.10.js:5760
$func121	@	dotnet.wasm:0x8318
$func4432	@	dotnet.wasm:0x129ce4
$func7118	@	dotnet.wasm:0x1b8404
$func7116	@	dotnet.wasm:0x1b8355
$func7115	@	dotnet.wasm:0x1b82ca
$func7119	@	dotnet.wasm:0x1b844c
$func1569	@	dotnet.wasm:0x967b5
$func1647	@	dotnet.wasm:0x99c87
$func284	@	dotnet.wasm:0x2ca38
$func248	@	dotnet.wasm:0x2b374
$func192	@	dotnet.wasm:0xbb9e
$func191	@	dotnet.wasm:0xa149
$func5965	@	dotnet.wasm:0x17284a
$func2798	@	dotnet.wasm:0xd69e3
$func2811	@	dotnet.wasm:0xd759b
$func2804	@	dotnet.wasm:0xd6e4e
$func442	@	dotnet.wasm:0x46fca
$func241	@	dotnet.wasm:0x2ad18
$func192	@	dotnet.wasm:0x2818b
$func191	@	dotnet.wasm:0xa149
$func5965	@	dotnet.wasm:0x17284a
$func2798	@	dotnet.wasm:0xd69e3
$func2811	@	dotnet.wasm:0xd759b
$func2804	@	dotnet.wasm:0xd6e4e
$func442	@	dotnet.wasm:0x46fca
$func241	@	dotnet.wasm:0x2ad18
$func192	@	dotnet.wasm:0x2818b
$func191	@	dotnet.wasm:0xa149
$func5965	@	dotnet.wasm:0x17284a
$func2798	@	dotnet.wasm:0xd69e3
$func2811	@	dotnet.wasm:0xd759b
$func2874	@	dotnet.wasm:0xdb57d
$mono_wasm_invoke_method	@	dotnet.wasm:0x8410
Module._mono_wasm_invoke_method	@	dotnet.6.0.0-preview.7.21360.10.js:10068
_call_method_with_converted_args	@	dotnet.6.0.0-preview.7.21360.10.js:8663
call_method	@	dotnet.6.0.0-preview.7.21360.10.js:8623
(anonymous)	@	dotnet.6.0.0-preview.7.21360.10.js:8888
call_assembly_entry_point	@	dotnet.6.0.0-preview.7.21360.10.js:8895
callEntryPoint	@	blazor.webassembly.js:1
ut	@	blazor.webassembly.js:1
async function (async)		
ut	@	blazor.webassembly.js:1
(anonymous)	@	blazor.webassembly.js:1
(anonymous)	@	blazor.webassembly.js:1
```

**Comment by eerhardt** [comment] 2021-07-27 16:23
> "Unable to load required ICU Globalization data. Please see https://aka.ms/dotnet-missing-libicu for more information"

That message appears to be coming from

https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.Private.CoreLib/src/System/Globalization/GlobalizationMode.Unix.cs#L16-L40

However, the `Environment.FailFast` call is protected by `if (!Invariant)`. So we should not be getting into this code when `<InvariantGlobalization>true</InvariantGlobalization>`. 

`Invariant` comes from:

https://github.com/dotnet/runtime/blob/578f81a6f80c04874bd1c89d9d95d0a45a665249/src/libraries/System.Private.CoreLib/src/System/Globalization/GlobalizationMode.cs#L14

Is the AppContext/environment variable not getting set at the right time?

**Comment by pavelsavara** [comment] 2021-07-27 16:38
I hit a breakpoint setting that env variable before call to `callEntryPoint`

![image](https://user-images.githubusercontent.com/271576/127193198-d0df7fdf-f66d-47e2-a4d1-6d36ddedfcb3.png)

**Comment by eerhardt** [comment] 2021-07-27 16:39
Can you see why `Invariant` is not returning `true` in the C# code above?

**Comment by pavelsavara** [comment] 2021-07-27 16:52
Because we are using `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT` as default value, by calling wrong overload.
```
        internal static bool GetBooleanConfig(string configName, bool defaultValue)
        internal static bool GetBooleanConfig(string switchName, string envVariable, bool defaultValue = false)
```

I will open PR shortly.

**Comment by pavelsavara** [comment] 2021-07-27 17:17
If I print the `Environment.GetEnvironmentVariable("DOTNET_SYSTEM_GLOBALIZATION_INVARIANT")` from C# side I get empty string

**Comment by pavelsavara** [comment] 2021-07-27 17:55
Calling `globalThis.ENV.DOTNET_SYSTEM_GLOBALIZATION_INVARIANT="1"` on instead of  `MONO.mono_wasm_setenv("DOTNET_SYSTEM_GLOBALIZATION_INVARIANT", "1")` fixes the issue. 
Also `mono_wasm_setenv` doesn't change the `ENV`. I don't know why yet.

See also https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#interacting-with-code-environment-variables

**Comment by pavelsavara** [comment] 2021-07-27 18:43
Moving `mono_wasm_setenv` to `preInit` instead of `preRun` fails with `Cannot read property 'Wb' of undefined` so I think that's too early for `cwrap` and `ccall`.

Moving `mono_wasm_setenv` to `callEntryPoint` **works!** 
It doesn't change `ENV` either.

**Comment by pavelsavara** [comment] 2021-07-27 19:05
Also moving it to `onRuntimeInitialized` works instead of [preRun](https://github.com/dotnet/aspnetcore/blob/0610031dc58512bd71f55bcbdd1f06656b753929/src/Components/Web.JS/src/Platform/Mono/MonoPlatform.ts#L282).

**Closed** 2021-08-04 12:19 UTC
Labels: arch-wasm, area-VM-meta-mono

**Comment by srpeirce** [comment] 2021-08-12 18:18
@pavelsavara 
To confirm, this still doesn't work in Preview 7. Has it been fixed for RC?
![image](https://user-images.githubusercontent.com/12847647/129248122-07bc367c-8a7f-4cca-b230-843b667bfef4.png)

**Comment by srpeirce** [comment] 2021-08-12 18:53
BTW for anybody who stumbles on this issue, this was my workaround - it's only a problem in debug.
```xml
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
    <BlazorEnableTimeZoneSupport>false</BlazorEnableTimeZoneSupport>
    <BlazorWebAssemblyPreserveCollationData>false</BlazorWebAssemblyPreserveCollationData>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'!='DEBUG'">
    <!-- Bug in .Net 6 Preview 7 - this should not be non-debug only. https://github.com/dotnet/runtime/issues/55750 -->
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  ```

**Comment by eerhardt** [comment] 2021-08-12 23:24
> this still doesn't work in Preview 7. Has it been fixed for RC?

Correct - the fix didn't make it into Preview7. It will be fixed in RC1.
