### ISSUE TITLE
Serialization and MD5 hashes failing after upgrading from .Net Core 3.1 to .Net 5

### ISSUE THREAD

**Issue by thelgevold** [dotnet/runtime#52539] opened 2021-05-10 11:53 UTC
### Describe the bug
After upgrading one of my applications from .Net Core 3.1 to .Net 5 I am noticing weird failures in the parts of my code dealing with byte array serialization and MD5 hashes. 

The code worked just fine in .Net Core 3.1, but after the upgrade to .Net 5 I am seeing issues at runtime when running on Linux.

Specifically the code hashes an object to a GUID as seen below:

```
        public Guid GenerateKey(string id, DateTime date1, DateTime? date2, string environment, string currencyCode, string ns, Dictionary<string, string> buildVersions)
        {
            var buildVersionString = string.Join(',', buildVersions.OrderBy(bv => bv.Key).Select(bv => $"{bv.Key}:{bv.Value}"));

            var key = new Key(id, date1, date2, environment, currencyCode, ns, buildVersionString); 

            var str = JsonConvert.SerializeObject(key);
            var bytes = Encoding.UTF8.GetBytes(str);

            var hashBytes = ComputeHash(bytes);

            return new Guid(hashBytes);
        }

        private byte[] ComputeHash(byte[] bytes)
        {
           using(var md5Hasher = MD5.Create())
           {
               return md5Hasher.ComputeHash(bytes);
           }     
        }
```
In .Net 3.1 I was able to generate multiple Guids using a simple ToDictionary call:

```
            var storedContents = new Content();

            storedContents.Keys = request.Ids.ToDictionary(
                                  k => k,
                                  v => keyProvider.GenerateKey(
                                  v,
                                  request.Date1,
                                  request.Date2,
                                  request.Environment,
                                  request.CurrencyCode,
                                  request.Namespace,
                                  request.BuildVersions)
            );
```
But in .Net 5 this started failing with the error below. The weird part is that it doesn't fail all the time, but fails pretty reliably after making a few requests.
```
Entry point was not found.
         at System.Collections.Generic.IEnumerable`1.GetEnumerator()
         at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
         at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
         at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
         at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()
         at System.String.JoinCore[T](Char* separator, Int32 separatorLength, IEnumerable`1 values)
         at POC.KeyProvider.GenerateKey(String id, DateTime date1, Nullable`1 date2, String environment, String currencyCode, String ns, Dictionary`2 buildVersions) in /home/tor/development/bug-repro/Api/POC/KeyProvider.cs:line 27
         at POC.StorageProvider.<>c__DisplayClass2_0.<GetContent>b__1(String v) in /home/tor/development/bug-repro/Api/POC/StorageProvider.cs:line 44
         at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](TSource[] source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
         at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
         at POC.StorageProvider.GetContent(MyRequest request) in /home/tor/development/bug-repro/Api/POC/StorageProvider.cs:line 42
         at Api.Controllers.TestController.Get() in /home/tor/development/bug-repro/Api/Controllers/TestController.cs:line 44
         at lambda_method7(Closure , Object , Object[] )
```

For some reason I am able to get it to work by converting the ToDictionary to a traditional foreach loop.

```
            storedContents.Keys = new Dictionary<string, System.Guid>();

            foreach(var id in request.Ids)
            {
                var key = keyProvider.GenerateKey(
                       id,
                       request.Date1,
                       request.Date2,
                       request.Environment,
                       request.CurrencyCode,
                       request.Namespace,
                       request.BuildVersions
                    );

                storedContents.Keys.Add(id, key);
            }
``` 

It seems like both versions should work, and did in .Net Core 3.1, but in .Net 5 the dictionary approach stopped working. Any thoughts on why this would break in .Net 5 on Linux? Windows seems fine, at least locally on my developer machine.

I have a reproduction of the issue here: https://github.com/thelgevold/Net5-Error

Note: In this example I am using NewtonSoft's JsonConvert.SerializeObject. I am seeing the same exact issue when using MessagePack for the serialization.

### To Reproduce

Here is a small project where the error can be reproduced: https://github.com/thelgevold/Net5-Error

### Exceptions (if any)

```
Entry point was not found.
         at System.Collections.Generic.IEnumerable`1.GetEnumerator()
         at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
         at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
         at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
         at System.Linq.Enumerable.SelectIPartitionIterator`2.MoveNext()
         at System.String.JoinCore[T](Char* separator, Int32 separatorLength, IEnumerable`1 values)
         at POC.KeyProvider.GenerateKey(String id, DateTime date1, Nullable`1 date2, String environment, String currencyCode, String ns, Dictionary`2 buildVersions) in /home/tor/development/bug-repro/Api/POC/KeyProvider.cs:line 27
         at POC.StorageProvider.<>c__DisplayClass2_0.<GetContent>b__1(String v) in /home/tor/development/bug-repro/Api/POC/StorageProvider.cs:line 44
         at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](TSource[] source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
         at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
         at POC.StorageProvider.GetContent(MyRequest request) in /home/tor/development/bug-repro/Api/POC/StorageProvider.cs:line 42
         at Api.Controllers.TestController.Get() in /home/tor/development/bug-repro/Api/Controllers/TestController.cs:line 44
         at lambda_method7(Closure , Object , Object[] )
```

### Further technical details
- ASP.NET Core version 5
- Include the output of `dotnet --info`
.NET SDK (reflecting any global.json):
 Version:   5.0.202
 Commit:    db7cc87d51

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.202/

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

.NET SDKs installed:
  5.0.202 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
- Linux

**Comment by jkotas** [comment] 2021-05-10 15:00
> The weird part is that it doesn't fail all the time, but fails pretty reliably after making a few requests.

Likely related to tiered compilation.

**Comment by AndyAyersMS** [comment] 2021-05-10 16:35
> Include the output of dotnet --info

What version of .NET 5 are you using? We have made several fixes for Linux codegen, in particular for calls in tail position that return structs...

**Comment by thelgevold** [comment] 2021-05-10 16:46
The code is compiled/published on the Ubuntu host and copied to Docker

**Comment by AndyAyersMS** [comment] 2021-05-10 16:52
Ok, thanks. 

Looks like the fix that likely matches your case (https://github.com/dotnet/runtime/commit/7eb058bf6fb686b91446d393dbf15e4f6eaf931b) is going to appear in 5.0.6 which should be available in the next few days. In the meantime you may be able to work around this by marking `GenerateKey` with `[MethodImpl(MethodImplOption.NoInlining)]`.

cc @BruceForstall

**Comment by thelgevold** [comment] 2021-05-10 19:43
Hi @AndyAyersMS 

I tried adding the attribute like this:

```
[MethodImpl(MethodImplOptions.NoInlining)]
        public Guid GenerateKey(string id, DateTime date1, DateTime? date2, string environment, string currencyCode, string ns, Dictionary<string, string> buildVersions)
        {
            var buildVersionString = string.Join(',', buildVersions.OrderBy(bv => bv.Key).Select(bv => $"{bv.Key}:{bv.Value}"));

            var key = new Key(id, date1, date2, environment, currencyCode, ns, buildVersionString); 

            var str = JsonConvert.SerializeObject(key);
            var bytes = Encoding.UTF8.GetBytes(str);

            var hashBytes = ComputeHash(bytes);

            return new Guid(hashBytes);
        }
```
But it looks like the behavior is the same.

**Comment by AndyAyersMS** [comment] 2021-05-10 20:33
Ok, thanks. Let me look at your repro and see if it's really the issue I think it is...

**Comment by AndyAyersMS** [comment] 2021-05-11 20:47
That's great news. 

Thank you for reporting this providing a repro.

**Comment by BruceForstall** [comment] 2021-05-11 20:58
Great! I'll go ahead and close this issue. Feel free to re-open (or open a new issue) if you can reproduce the problem.

**Closed by BruceForstall** 2021-05-11 20:58 UTC
Labels: area-CodeGen-coreclr
