### ISSUE TITLE
.NET 5.0.8 arm64 for Windows Desktop not installing properly

### ISSUE THREAD

**Issue by hamarb123** [dotnet/runtime#56958] opened 2021-08-06 03:03 UTC
### Description

On arm64, .NET 5.0.8 for Windows Desktop doesn't install properly.  It is missing the `dotnet.exe` executable, and it can't run anything. I downloaded it from  [here](https://dotnet.microsoft.com/download/dotnet/5.0):
![image](https://user-images.githubusercontent.com/25316035/128448930-f2b8eb87-4ac6-45a6-b073-b49d398cbdb9.png)
Folder:
![image (1)](https://user-images.githubusercontent.com/25316035/128449328-07e21673-9aa8-435b-97e8-bd89ff630c05.png)
Control panel (note, size is almost half of what the x64 version makes ~200MB):
![image (2)](https://user-images.githubusercontent.com/25316035/128449333-1a16e9ea-821c-469a-a0a9-1b17a3ac0ab0.png)
Files that were in the C:\Program Files\dotnet folder: https://drive.google.com/file/d/1IbIxm_2Cu_DN_5aZ7_Nx20124YaxU3Ex/view?usp=sharing

### Configuration

.NET 5.0.8 (and 5.0.7 I think)
Windows 10.0.21354.1 arm64 running through Parallels on an M1 macbook pro.
It doesn't happen with .NET 6 preview 6
It doesn't happen with the x64 and x86 installers, but they have other issues with this specific application.
There are no other .NET (non-framework) versions at all on this VM.
This is not my machine, but I did help set it up, the OS build is an insider build because that's what you need to use it on Parallels on an M1.

### Other information

Workaround is to install .NET 6 preview 6 and edit the runtimeconfig.json file.

**Comment by vcsjones** [comment] 2021-08-06 14:58
I think this is related to or a duplicate of https://github.com/dotnet/windowsdesktop/issues/1823

**Comment by danmoseley** [comment] 2021-08-06 15:18
@ryalanms can we close as dupe? Seems it.

**Comment by ryalanms** [comment] 2021-08-06 17:37
Yes, this is a duplicate and can be closed.  Until 5.0.10 is released, users will need to install both the ARM64 .NET WindowsDesktop Runtime and the ARM64 .NET Runtime to run ARM64 WindowsDesktop applications on .NET 5.0.

**Comment by vcsjones** [comment] 2021-08-06 17:53
Duplicate of dotnet/windowsdesktop#1823.

**Closed by vcsjones** 2021-08-06 17:53 UTC
Labels: area-Setup, untriaged
