### ISSUE TITLE
HttpClient difference 3.1 vs 5.0. Getting: connection was aborted 

### ISSUE THREAD

**Issue by mikhail-tin** [dotnet/runtime#52287] opened 2021-05-05 06:50 UTC
Hi there,

I have found strange behavior when moved from 3.1 to 5.0.
The same request in the same environment produces a different result.

Runtime: 3.1 - OK 
Runtime 5.0.4 - Exception:
An error occurred while sending the request. -> Unable to read data from the transport connection -> An established connection was aborted by the software in your host machine.

Code: 
program.cs
``` csharp
namespace WebApplication
{
    public class Program
    {
        public static void Main(string[] args) =>
            Host.CreateDefaultBuilder(args).ConfigureWebHostDefaults(wb => { wb.UseStartup<Startup>(); }).Build().Run();
    }

    public class Startup
    {
        public void ConfigureServices(IServiceCollection services){}

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseRouting();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapGet("/", async context =>
                {
                    try
                    {
                        var client = new HttpClient();
                        var resp = await client.GetAsync("https://demo.identityserver.io/.well-known/openid-configuration");
                        await context.Response.WriteAsync(Environment.Version.ToString() + ": " + resp.StatusCode);
                    }
                    catch (Exception ex)
                    {
                        await context.Response.WriteAsync(Environment.Version.ToString() + ": " + ex.Message);
                    }
                });
            });
        }
    }
}
```

WebApplication.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
	<!--<TargetFramework>netcoreapp3.1</TargetFramework>-->
  </PropertyGroup>
</Project>
```

What could be a reason of this behavior  on the same machine(just flip TargetFramework)? 
Also I have tried on another machine and both runtime works fine and no exception.

OS: Win 10

Thx!

**Comment by wfurt** [comment] 2021-05-05 07:16
can you get packet captures with Wireshark? What is your OS?

**Comment by mikhail-tin** [comment] 2021-05-05 07:49
> can you get packet captures with Wireshark? What is your OS?

No, I have no chance to download and install something.
OS Name: Windows, OS Version:  10.0.19041, RID: win10-x64

**Comment by antonfirsov** [comment] 2021-05-05 09:58
@mikhail-tin is this a consistent or an intermittent error? AFAIK the only socket-level between 3.1 and 5.0 is the switch to dual-mode sockets. Can you check if [this `ConnectCallback` override](https://github.com/dotnet/runtime/issues/44686) changes anything?

**Comment by karelz** [comment] 2021-05-05 11:46
@mikhail-tin the code above creates `HttpClient` per request -- that is not a healthy practice, that may easily lead to other problems. Are you able to reproduce the same problem from a console app? (demonstrating 3.1 works and 5.0 does not)
Same question as above -- is it 100% repro on first request, or is it intermittent?

**Comment by mikhail-tin** [comment] 2021-05-05 11:54
It is 100% repro on first request . With CreateWorkaroundClient()  no exception, it helps.  
``` csharp
public static HttpClient CreateWorkaroundClient()
        {
            SocketsHttpHandler handler = new SocketsHttpHandler { ConnectCallback = IPv4ConnectAsync };
            return new HttpClient(handler);

            static async ValueTask<Stream> IPv4ConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
            {
                // By default, we create dual-mode sockets:
                // var socket = new Socket(SocketType.Stream, ProtocolType.Tcp);

                var socket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
                socket.NoDelay = true;

                try
                {
                    await socket.ConnectAsync(context.DnsEndPoint, cancellationToken).ConfigureAwait(false);
                    return new NetworkStream(socket, ownsSocket: true);
                }
                catch
                {
                    socket.Dispose();
                    throw;
                }
            }
        }
```
Thx

**Comment by karelz** [comment] 2021-05-05 12:00
OK, looks like another +1 on DualSockets causing problems ... what is your environment? Is it enterprise setup with some specific firewall? (just out of curiosity)

**Comment by mikhail-tin** [comment] 2021-05-05 12:13
> OK, looks like another +1 on DualSockets causing problems ... what is your environment? Is it enterprise setup with some specific firewall? (just out of curiosity)

No, I have faced it on my machine for development( with firewall, antivirus and proxy). 
I assume we could close the issue as resolved. looks like the reason is firewall or something.

Thx a lot.

**Comment by antonfirsov** [comment] 2021-05-05 12:34
> with firewall, antivirus and proxy

@mikhail-tin can you try disabling these one-by-one without the workaround code? That would be valuable info for us, I'd appreciate.

**Comment by mikhail-tin** [comment] 2021-05-05 12:40
> > with firewall, antivirus and proxy
> 
> @mikhail-tin can you try disabling these one-by-one without the workaround code? That would be valuable info for us, I'd appreciate.

I can't do that due corp policies. No ways..

**Comment by karelz** [comment] 2021-05-05 13:03
@mikhail-tin can you please at least tell us which firewall is used? ... we can then close the issue.

**Comment by mikhail-tin** [comment] 2021-05-05 13:09
@karelz,  Kaspersky Endpoint Security for Windows

**Comment by karelz** [comment] 2021-05-05 13:54
Thanks!

Closing as resolved.

**Closed by karelz** 2021-05-05 13:54 UTC
Labels: area-System.Net, untriaged
