### ISSUE TITLE
Unable to TarFile.ExtractToDirectoryAsync when it contains symbolic link file points to an absolute path 

### ISSUE THREAD

**Issue by yanche** [dotnet/runtime#86724] opened 2023-05-24 20:32 UTC
### Description

I'm using TarFile.ExtractToDirectoryAsync to untar a nginx container image layer, got this exception
Unhandled exception. System.IO.IOException: Extracting the Tar entry '/usr/share/fontconfig/conf.avail/10-hinting-slight.conf' would have resulted in a link target outside the specified destination directory: '{{target directory name}}'
   at System.Formats.Tar.TarEntry.GetDestinationAndLinkPaths(String destinationDirectoryPath)
   at System.Formats.Tar.TarEntry.ExtractRelativeToDirectoryAsync(String destinationDirectoryPath, Boolean overwrite, SortedDictionary`2 pendingModes, CancellationToken cancellationToken)
   at System.Formats.Tar.TarFile.ExtractToDirectoryInternalAsync(Stream source, String destinationDirectoryPath, Boolean overwriteFiles, Boolean leaveOpen, CancellationToken cancellationToken)
   at System.Formats.Tar.TarFile.ExtractToDirectoryInternalAsync(Stream source, String destinationDirectoryPath, Boolean overwriteFiles, Boolean leaveOpen, CancellationToken cancellationToken)

I checked the source code, if TarEntry is symlink, and points to an absolute path, it throws the exception above. Is this behavior expected? When I use `tar` program in Linux, it's able to extract files including the symlink above.

### Reproduction Steps

Create a symlink using absolute path to target file
Create a tar for the symlink file created
Write a C# program using Tar.ExtractToDirectoryAsync to extract the created tar file
You should see exception like
System.IO.IOException: Extracting the Tar entry {{}} would have resulted in a link target outside the specified destination directory: {{}}

### Expected behavior

Untar symlink of absolute target path should succeed

### Actual behavior

Untar symlink of absolute target path failed

**Comment by am11** [comment] 2023-06-22 16:24
Are you getting this error with latest .NET 7? If so, can you share the repro? I cannot reproduce it with runtime v7.0.304:

```sh
$ dotnet --info | grep -A1 Host:
Host:
  Version:      7.0.7

$ dotnet new console -n gh-86724; cd $_
$ cat > Program.cs <<EOF
using System.Formats.Tar;
await TarFile.ExtractToDirectoryAsync("/tmp/nginx.tar", "/tmp/extracted-nginx", false);
Console.WriteLine("Extraction completed!");
EOF

$ docker pull nginx
$ docker save nginx -o /tmp/nginx.tar
$ mkdir /tmp/extracted-nginx

$ dotnet run
Extraction completed!

$ ls /tmp/nginx.tar
232d6a3f388e160ecd1893e740a2d9875b4e483716a1f62297ff4f4e2cf71597	465b0b87f5b2bdeebd1c8974cbce1af053cd8264feb0863cf9746cd185802460	manifest.json
26a81107ef18d3b70e23a73041a0c93f4ad11b246d03e5aa05e628417948f643	9551a223dddac65cc0e11b6047ca18e614d5c435f3175bd70b9b9c7125a6b7e8	repositories
2d21d843073b4df6a03022861da4cb59f7116c864fe90b3b5db3b90e1ce932d3.json	ab89fcab3248504c9da6425826aab938419d13fb6ff7d1465b764750a157fd83
3142c217f92adf3e51630a425e35d66803b8f54a61b3c6b7bff12811aa3d8b29	dd9f1fb038a6d3d0cdb3166c928de9fbbd5279c3b25c65da0103621356d54b8e
```

https://github.com/dotnet/runtime/commit/e242819bde8ec3a7bb97b689792c1ece4b74e1e7 fixed this case.

**Comment by himan-msft** [comment] 2023-06-27 23:33
I am able to repro this issue with .NET 7.0.8.

This is what my `Program.cs` looks like:
```
using System.Formats.Tar;
using System.IO.Compression;

Console.WriteLine($"Dotnet version: {Environment.Version}");

var tarGzFileName = "/tmp/alpine.tar.gz";
using var fileStream = File.OpenRead(tarGzFileName);
using var gzStream = new GZipStream(fileStream, CompressionMode.Decompress);
var extractDirectory = "/tmp/extracted-alpine";
Directory.CreateDirectory(extractDirectory);
await TarFile.ExtractToDirectoryAsync(gzStream, extractDirectory, true);
Console.WriteLine("Extraction successful.");
```

This is the .tar.gz file I am using: [alpine.tar.gz](https://github.com/dotnet/runtime/files/11888071/alpine.tar.gz)

**Comment by carlossanlop** [comment] 2023-07-17 22:54
@yanche what version of .NET were you using? We have fixed a few link and path related bugs in System.Formats.Tar. Particularly, this one might have addressed your problem in 7.0.2: https://github.com/dotnet/runtime/pull/78470 . Also, can you share the link to the nginx container you were trying to extract, to see if I can repro?

@himan-msft I am unable to repro with the provided alpine.tar.gz. I also used 7.0.8, it extracts without problems. Can you share your callstack?

**Comment by himan-msft** [comment] 2023-07-17 23:18
@carlossanlop Here is an updated repro which directly downloads the alpine.tar.gz from the file I provided earlier:
```
using System.Formats.Tar;
using System.IO.Compression;

Console.WriteLine($"Dotnet version: {Environment.Version}");

var alpineImageLayer = "https://github.com/dotnet/runtime/files/11888071/alpine.tar.gz";
var extractDirectory = "/tmp/extracted-alpine";

using var httpClient = new HttpClient();
var downloadStream = await httpClient.GetStreamAsync(alpineImageLayer);
using var gzStream = new GZipStream(downloadStream, CompressionMode.Decompress);
Directory.CreateDirectory(extractDirectory);
await TarFile.ExtractToDirectoryAsync(gzStream, extractDirectory, true);
```

This is the output + callstack I get when running it in Ubuntu 22.04 on WSL2 (5.15.90.1-microsoft-standard-WSL2):
```
Dotnet version: 7.0.8
Unhandled exception. System.IO.IOException: Extracting the Tar entry '/bin/busybox' would have resulted in a link target outside the specified destination directory: '/tmp/extracted-alpine'
   at System.Formats.Tar.TarEntry.GetDestinationAndLinkPaths(String destinationDirectoryPath)
   at System.Formats.Tar.TarEntry.ExtractRelativeToDirectoryAsync(String destinationDirectoryPath, Boolean overwrite, SortedDictionary`2 pendingModes, CancellationToken cancellationToken)
   at System.Formats.Tar.TarFile.ExtractToDirectoryInternalAsync(Stream source, String destinationDirectoryPath, Boolean overwriteFiles, Boolean leaveOpen, CancellationToken cancellationToken)
   at System.Formats.Tar.TarFile.ExtractToDirectoryInternalAsync(Stream source, String destinationDirectoryPath, Boolean overwriteFiles, Boolean leaveOpen, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\Users\hyerrakalva\Repos\TestDotnetTar\TestDotnetTar\Program.cs:line 11
   at Program.<Main>(String[] args)
```

**Comment by tmds** [comment] 2023-07-18 04:28
This is reporting the same limitation as https://github.com/dotnet/runtime/issues/74140.
As explained in https://github.com/dotnet/runtime/issues/74140#issuecomment-1309242434 the behavior is intentional.

You an propose an API that would enable extracting such tar files. It could be an additional option added to https://github.com/dotnet/runtime/issues/69780.

**Comment by am11** [comment] 2023-07-18 04:48
> It could be an additional option added to https://github.com/dotnet/runtime/issues/69780.

Something like:

```diff
public sealed class TarCreateOptions
{
+    public bool ContainAbsoluteSymlinkTargetsInDestination { get; set; } = false;
}
```

and change this logic https://github.com/dotnet/runtime/blob/b6266a6e4ceac8708304eed764e25777d08cf184/src/libraries/System.Formats.Tar/src/System/Formats/Tar/TarEntry.cs#L352 to

```c#
 Path.IsPathFullyQualified(linkName) && !_creationOptions.ContainAbsoluteSymlinkTargetsInDestination ?
     linkName :
     Path.Join(Path.GetDirectoryName(fileDestinationPath),
         _creationOptions.ContainAbsoluteSymlinkTargetsInDestination ? linkName.TrimStart('/') : linkName)); 
```

**Comment by carlossanlop** [comment] 2023-07-20 18:12
@am11 thanks for the suggested API. Let's go ahead and close this issue and please create a new one with your proposal.

**Closed by carlossanlop** 2023-07-20 18:12 UTC
Labels: area-System.Formats.Tar
