### ISSUE TITLE
ProvisionEmscripten task fails with [SSL: CERTIFICATE_VERIFY_FAILED] when acquiring Node.

### ISSUE THREAD

**Issue by joeloff** [dotnet/runtime#101081] opened 2024-04-15 21:00 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=630659
Build error leg or test failing: Build Browser wasm release Browser_wasm_Windows / Build product
Pull request: https://github.com/dotnet/runtime/pull/100648

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "'emcmake' is not recognized as an internal or external command",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": true
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=630659
**Error message validated:** `['emcmake' is not recognized as an internal or external command`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 4/15/2024 9:03:24 PM UTC

**Comment by lewing** [comment] 2024-04-15 21:08
duplicate of https://github.com/dotnet/runtime/issues/100973

**Closed by lewing** 2024-04-15 21:08 UTC
Labels: area-Infrastructure-libraries, blocking-clean-ci, untriaged, Known Build Error
