### ISSUE TITLE
[API Proposal]: Add IsEnumerated property to IEnumerable<T> interface

### ISSUE THREAD

**Issue by RichardMelito** [dotnet/runtime#80144] opened 2023-01-03 20:36 UTC
### Background and motivation

The `IEnumerable<T>` interface is a fundamental part of the .NET runtime because it represents any sequence of `T` that can be enumerated. Its flexibility has made it very common for methods to use `IEnumerable<T>` in their signatures rather than a concrete type or more specific interface. The interface is so flexible that many `IEnumerable<T>` implementers (especially those critical to LINQ) use deferred execution for performance benefits. However, there is currently no good way for consumers of the interface to determine whether an instance has already been enumerated or is waiting to be enumerated via deferred execution. The closest way is to check `TryGetNonEnumeratedCount()` but that method only returns `true` if the type implements `ICollection`, `ICollection<T>`, or the hidden interface `IIListProvider<T>`.

This creates a problem: if a method iterates through a given `IEnumerable<T>` more than once, it is common to freeze the sequence by calling a method such as `ToArray()` to avoid multiple expensive enumerations. However, if the sequence is already enumerated or is passed to another method that does the same thing, then multiple expensive enumerations are still happening.
Example:
```csharp
void MethodA(IEnumerable<int> sequence)
{
    // If sequence is already enumerated then this call will be needlessly expensive
    sequence = sequence.ToArray();
    foreach (var elem in sequence)
    {
        // do stuff
    }

    foreach (var elem in sequence)
    {
        // do stuff
    }

    MethodB(sequence);
}

void MethodB(IEnumerable<int> sequence)
{
    // If sequence is already enumerated (such as when called from MethodA) then this
    // call will be needlessly expensive
    sequence = sequence.ToArray();
    foreach (var elem in sequence)
    {
        // do other stuff
    }

    foreach (var elem in sequence)
    {
        // do other stuff
    }
}
```

I propose adding a property `IsEnumerated` to the interface that signals to consumers whether or not the sequence has been enumerated. It would be complemented by a new extension method `ToEnumerated()` that checks `IsEnumerated` and either returns the original instance or calls `ToImmutableArray()` on it.

The property would have a default implementation of `false` to prevent breaking current code. Applicable derived interfaces like `ICollection<T>` would override the default implementation so that it returns `true`. It may be desirable to emit a compiler warning for implementers that do not implement the new property so that custom enumerated types do not miss out on the performance benefits.

### API Proposal

```csharp
namespace System.Collections.Generic
{
    public interface IEnumerable<out T> : IEnumerable
    {
        bool IsEnumerated { get; }
    }
}

namespace System.Linq
{
    public static partial class Enumerable
    {
        public static IEnumerable<T> ToEnumerated<T>(this IEnumerable<T> source);
    }
}
```

### API Usage

Implementation of `ToEnumerated` using `IsEnumerated`, and rewrite of `TryGetNonEnumeratedCount` to be faster and work with more types:
```csharp
namespace System.Linq;

public static partial class Enumerable
{
    public static IEnumerable<TSource> ToEnumerated<TSource>(this IEnumerable<TSource> source)
    {
        if (source.IsEnumerated)
            return source;

        return source.ToImmutableArray();
    }

    public static bool TryGetNonEnumeratedCount<TSource>(this IEnumerable<TSource> source, out int count)
    {
        if (source.IsEnumerated)
        {
            count = source.Count();
            return true;
        }

        count = 0;
        return false;
    }
}
```
Replacing expensive `ToArray` calls with cheap `ToEnumerated` calls:
```csharp
void MethodA(IEnumerable<int> sequence)
{
    // If sequence is already enumerated then this call will just reassign sequence to itself
    sequence = sequence.ToEnumerated();
    foreach (var elem in sequence)
    {
        // do stuff
    }

    foreach (var elem in sequence)
    {
        // do stuff
    }

    MethodB(sequence);
}

void MethodB(IEnumerable<int> sequence)
{
    // If sequence is already enumerated then this call will just reassign sequence to itself
    sequence = sequence.ToEnumerated();
    foreach (var elem in sequence)
    {
        // do other stuff
    }

    foreach (var elem in sequence)
    {
        // do other stuff
    }
}
```

### Alternative Designs

1. The property could be added to the `IEnumerable` interface instead of `IEnumerable<T>`.
2. An `IEnumerated<T>` interface could be added that indicates at compile time that the type is already enumerated.

### Risks

None. The default interface implementations should mitigate any risks.

**Comment by Clockwork-Muse** [comment] 2023-01-03 21:18
> if a method iterates through a given `IEnumerable<T>` more than once

Then the method is probably broken.  An `IEnumerable` isn't (guaranteed to be) stable in results.  Some `IEnumerable`s can't be re-enumerated at all.

> It would be complemented by a new extension method `ToEnumerated()` that checks `IsEnumerated` and either returns the original instance or calls `ToImmutableArray()` on it.

The "proper" implementation of such a method should probably just check if the type implements any of the various "save off" interfaces (say, `ICollection`), and return it if so.
Also, it's not clear why `ToImmutableArray()` as opposed to the perhaps more normal `ToArray()`.

> and rewrite of `TryGetNonEnumeratedCount` to be faster and work with more types

The shown naive implementation actually applies in fewer cases - `TryGetNonEnumeratedCount` can return a count _before_ enumeration in multiple cases (ie, for `someSourceList.Select()` the count will be known).

Also:
Duplicate of #76675 in intent (although not implementation).

**Comment by RichardMelito** [comment] 2023-01-03 22:00
> > and rewrite of `TryGetNonEnumeratedCount` to be faster and work with more types
> 
> The shown naive implementation actually applies in fewer cases - `TryGetNonEnumeratedCount` can return a count _before_ enumeration in multiple cases (ie, for `someSourceList.Select()` the count will be known).

That is very interesting. It also means that `TryGetNonEnuemratedCount` cannot be relied upon to indicate if the sequence has already been enumerated.

**Comment by RichardMelito** [comment] 2023-01-03 22:07
> I don't quite understand what is the benefit of this over checking for `ICollection<T>`/`IReadOnlyCollection<T>`. What kinds of enumerables would return `true` from `IsEnumerated`, but wouldn't implement these interfaces?

I don't have a specific example in mind, but someone has probably made one somewhere. I agree though, checking for `IReadOnlyCollection<T>` would probably suffice (I forgot that its only members are `Count` and `GetEnumerator`).

That brings up an interesting tangent, though: `TryGetNonEnumeratedCount` does not work for `IReadOnlyCollection<T>` instances! That seems like an oversight.

> Also:
> 
> > Risks: None. The default interface implementations should mitigate any risks.
> 
> I don't believe this is true. Default interface members make it much less likely that adding a new member will be a breaking change, but they don't eliminate the risk altogether. Which is why the .Net team was so far reluctant to use DIMs on frequently used interfaces (and `IEnumerable<T>` certainly is one of those).

Can you elaborate on those risks, or link somewhere that discusses them? I thought that the main motivation for DIMs was to make it safe to extend interfaces.

**Comment by eiriktsarpalis** [comment] 2023-01-10 14:28
> > Also:
> > > Risks: None. The default interface implementations should mitigate any risks.
> > 
> > 
> > I don't believe this is true. Default interface members make it much less likely that adding a new member will be a breaking change, but they don't eliminate the risk altogether. Which is why the .Net team was so far reluctant to use DIMs on frequently used interfaces (and `IEnumerable<T>` certainly is one of those).
> 
> Can you elaborate on those risks, or link somewhere that discusses them? I thought that the main motivation for DIMs was to make it safe to extend interfaces.

See https://github.com/dotnet/runtime/issues/55106 for an example.

**Comment by eiriktsarpalis** [comment] 2023-01-10 14:30
> That brings up an interesting tangent, though: TryGetNonEnumeratedCount does not work for IReadOnlyCollection<T> instances! That seems like an oversight.

It's intentional. Adding more type tests comes at a cost, and most BCL collection types that implement IReadOnlyCollection<T> also implement ICollection<T>.

**Comment by eiriktsarpalis** [comment] 2023-01-10 14:30
Per feedback above, closing as not planned. We consider adding new members to existing interfaces to be potential breaking changes, even if they are DIMs.

**Closed by eiriktsarpalis** 2023-01-10 14:30 UTC
Labels: api-suggestion, area-System.Collections, untriaged
