### ISSUE TITLE
[API Proposal]: Enum should implement IBitwiseOperators, IEqualityOperators

### ISSUE THREAD

**Issue by EtiTheSpirit** [dotnet/runtime#81664] opened 2023-02-05 20:59 UTC
### Background and motivation

Enums can natively have bitwise operations and equality operations performed on them. This all falls apart when attempting to create a generic method that can encompass all classes that can use these operations via generic math. Attempting to pass an enum into such a method will result in a compile error, despite the fact that it makes complete sense for enum to qualify for these operations.

### API Proposal

```csharp
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace System {
    public abstract partial class Enum : IBitwiseOperators<Enum, Enum, Enum>, IEqualityOperators<Enum, Enum, bool> {
        // ...
    }
}
```

### API Usage

```csharp
[Flags]
public enum SomeEnum {
    A = 0,
    B = 1 << 0,
    C = 1 << 1
}

public static bool HasFlags<T>(this T value, T flags, bool matchAll) where T : IBitwiseOperators<T, T, T>, IEqualityOperators<T, T, bool> {
	if (matchAll) return (value & flags) == flags;
	return (value & flags) != default;
}

public static void Main() {
    SomeEnum value0 = SomeEnum.A | SomeEnum.B;
    SomeEnum value1 = SomeEnum.C;
    Console.WriteLine(value0.HasFlags(value1, false)); // output: False
}
```

**Comment by stephentoub** [comment] 2023-02-06 00:34
Exposing this via `IBitwiseOperators<Enum, Enum, Enum>` would make all of the operations prohibitively expensive, e.g. because of boxing.

**Comment by MichalPetryka** [comment] 2023-02-06 11:49
> Exposing this via `IBitwiseOperators<Enum, Enum, Enum>` would make all of the operations prohibitively expensive, e.g. because of boxing.

This could be optimized out via intrinsic like HasFlag is.

**Comment by stephentoub** [comment] 2023-02-06 12:06
> This could be optimized out via intrinsics like HasFlag is.

Even if that considerable effort and complexity was done for all of the input parameters, this doesn't work out type system-wise for the return, as there's no implicit conversion from Enum back to enum types.

**Comment by tannergooding** [comment] 2023-02-06 16:38
If anything was done here so that existing arrays implicitly got the support, I think it would need to like `Array` where various "magic" allows it to "implement" interfaces such as `IEquatable<T>`. That being said, such work is non-trivial and would need buy off from the VM, Runtime, and Language.

Alternatively, it would be possible to do work to allow `enum` declarations to expose their own members and implement interfaces. Such an approach would allow users to opt in their own enums and might be more generally useful. However, this is also likely non-trivial work and comes with its own complications/downsides.

Given that the language couldn't do anything until the runtime/language got support, it's likely worth tagging @jkotas for additional perspective.

**Comment by jkotas** [comment] 2023-02-06 19:02
This is duplicate of #2349.

> various "magic" allows it to "implement" interfaces such as IEquatable<T>

I have commented on this here: https://github.com/dotnet/csharplang/issues/2349#issuecomment-473484877 .

Would roles (https://github.com/dotnet/csharplang/issues/5497, https://github.com/jcouv/csharplang/blob/roles-spec/proposals/roles.md) be usable for this scenario?

**Comment by tannergooding** [comment] 2023-02-06 19:06
> Would roles (https://github.com/dotnet/csharplang/issues/5497, https://github.com/jcouv/csharplang/blob/roles-spec/proposals/roles.md) be usable for this scenario?

@333fred, @jaredpar ?

**Comment by tannergooding** [comment] 2023-03-23 17:23
Closing this as its not something we'll be doing on the library side.

We can investigate using roles/extensions when that feature comes out; otherwise further discussion should happen on the csharplang issue.

**Closed by tannergooding** 2023-03-23 17:23 UTC
Labels: api-suggestion, area-System.Runtime
