### ISSUE TITLE
Test failure readytorun/tests/fileversionpreservation/fileversionpreservation/fileversionpreservation.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#72823] opened 2022-07-26 01:37 UTC
Run: [runtime-coreclr gcstress-extra 20220724.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1900569&view=ms.vss-test-web.build-test-results-tab&runId=49456928&paneView=debug&resultId=108578)
 
Failed test:
```
coreclr OSX arm64 Checked gcstress0xc_zapdisable_jitstress2 @ OSX.1200.ARM64.Open

- readytorun/tests/fileversionpreservation/fileversionpreservation/fileversionpreservation.sh
```

**Error message:**
```
Unhandled exception. System.IO.FileNotFoundException: Could not find file '/private/tmp/helix/working/9B7B093A/w/A52508A2/e/readytorun/tests/fileversionpreservation/fileversionpreservation/fileversionpreservation.dll'.
File name: '/private/tmp/helix/working/9B7B093A/w/A52508A2/e/readytorun/tests/fileversionpreservation/fileversionpreservation/fileversionpreservation.dll'
at Program.RunTest()
at Program.Main()
[createdump] Invalid process id: task_for_pid(83690) FAILED (os/kern) failure (5)
[createdump] This failure may be because createdump or the application is not properly signed and entitled.
[createdump] Failure took 0ms
/private/tmp/helix/working/9B7B093A/w/A52508A2/e/readytorun/tests/fileversionpreservation/fileversionpreservation/fileversionpreservation.sh: line 380: 83690 Abort trap: 6           (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /tmp/helix/working/9B7B093A/w/A52508A2/uploads/Reports/readytorun.tests/fileversionpreservation/fileversionpreservation/fileversionpreservation.output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/9B7B093A/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false fileversionpreservation.dll ''
[createdump] Target process is alive
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/tmp/helix/working/9B7B093A/p
/private/tmp/helix/working/9B7B093A/w/A52508A2/e/readytorun/tests/fileversionpreservation/fileversionpreservation/fileversionpreservation.sh
Expected: True
Actual:   False


Stack trace
   at readytorun_tests._fileversionpreservation_fileversionpreservation_fileversionpreservation_._fileversionpreservation_fileversionpreservation_fileversionpreservation_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```
Queued | OS | Arch | Column1
-- | -- | -- | --
2022-07-24T23:18:16.224Z | osx.1200.arm64.open | arm64 | [runtime-coreclr gcstress-extra   Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1900569&view=ms.vss-test-web.build-test-results-tab&runId=49456928&resultId=108578&paneView=debug)
2022-05-30T00:11:42.56Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr gcstress-extra   Checked-gcstress0xc_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=1795814&view=ms.vss-test-web.build-test-results-tab&runId=47946014&resultId=105216&paneView=debug)
2022-05-29T00:59:21.42Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86   Checked-jitstress_isas_1_x86_nohwintrinsic](https://dev.azure.com/dnceng/public/_build/results?buildId=1794952&view=ms.vss-test-web.build-test-results-tab&runId=47937042&resultId=104228&paneView=debug)
2022-05-29T00:52:28.381Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr gcstress-extra   Checked-gcstress0xc_jitminopts_heapverify1](https://dev.azure.com/dnceng/public/_build/results?buildId=1795007&view=ms.vss-test-web.build-test-results-tab&runId=47936924&resultId=105219&paneView=debug)
2022-05-29T00:10:21.895Z | osx.1200.arm64.open | arm64 | [runtime-coreclr gcstress-extra   Checked-gcstress0xc_jitminopts_heapverify1](https://dev.azure.com/dnceng/public/_build/results?buildId=1795007&view=ms.vss-test-web.build-test-results-tab&runId=47936290&resultId=106042&paneView=debug)

**Comment by ivdiazsa** [comment] 2022-08-04 22:46
This looks like one of those unlucky random crashes in Helix. It hasn't reproduced for a while and I can't get it to happen locally either. So, closing for now. If it repros again, we can reopen.

**Closed by ivdiazsa** 2022-08-04 22:46 UTC
Labels: arch-arm64, os-mac-os-x, GCStress, JitStress, area-ReadyToRun-coreclr, blocking-clean-ci-optional
