### ISSUE TITLE
Requested optimization when two registered services refer to the same target type

### ISSUE THREAD

**Issue by SoftCircuits** [dotnet/runtime#64351] opened 2022-01-26 18:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe the problem.

If I create a class that implements two interfaces.

```cs
public interface IBar {}
public interface IFoo {}

public class Foo : IFoo, IBar
{
}
```

And I want my class to be dependency injected for both interfaces.

```vs
services.AddScoped<IFoo, Foo>();
services.AddScoped<IBar, Foo>();
```

The dependency injector will create two different instances of `Foo`.

```cs
var provider = services.BuildServiceProvider();

var foo1 = provider.GetService<IFoo>();
var foo2 = provider.GetService<IBar>();

Assert.Same(foo1, foo2);     // FAILS
````

### Describe the solution you'd like

It would be far more efficient if the dependency injector could detect that both services reference the same type, and only create a single instance of that type at a time.

### Additional context

I know this issue has been discussed before in years past, including here on GitHub. This still seems relevant to me. And I'd like to know what the current thinking is about making such an optimization. As it stands, it becomes an awkward workaround for cases where unneeded copies of my target type are considered a problem.

**Comment by davidfowl** [comment] 2022-01-26 19:13
This isn't an optimization, it's a feature request. There would need to be a way to explicitly register the same instance of as multiple service types. This can be done today by doing the following:

```C#
var services = new ServiceCollection();
services.AddScoped<IFoo, Foo>();
services.AddScoped<IBar, Foo>(sp => (Foo)sp.GetRequiredService<IFoo>());
```

**Comment by SoftCircuits** [comment] 2022-01-27 01:23
I don't mind whether you call it an optimization or a feature. My point was that my original code works. It just isn't very efficient.

Looks like your code is passing a `Func<>` that tells the dependency injector how to create the instance of `IBar` each time it is needed. Seems like that works.

Do you not think it would be a cool feature if the dependency injector could handle this automatically?

**Comment by davidfowl** [comment] 2022-01-27 16:14
> I don't mind whether you call it an optimization or a feature. My point was that my original code works. It just isn't very efficient.

The comment was to say that the above code has a meaning and works as designed. You need another feature to make 

> Do you not think it would be a cool feature if the dependency injector could handle this automatically?

I actually filed this bug a while back but it's a new feature that would need to be added to all of the DI container adapters and as such the bar is extremely high for any new feature added to the core DI spec or service collection. It requires sign off from all of the DI container maintainers and a new APIs. This is why we don't add features to DI very often (it's intentional to avoid the churn for low value features).

**Comment by davidfowl** [comment] 2022-01-27 16:31
My reply still stands, both parts because you pointed to my reply 😄

**Comment by maryamariyan** [comment] 2022-02-01 22:22
closing issue as won't fix as per conversation above

**Closed by maryamariyan** 2022-02-01 22:22 UTC
Labels: untriaged, area-Extensions-DependencyInjection
