### ISSUE TITLE
P/Invoke function returning SafeSocketHandle throws "System.MissingMethodException: .ctor"

### ISSUE THREAD

**Issue by asmichi** [dotnet/runtime#45633] opened 2020-12-05 07:16 UTC
### Description

On .NET 5, P/Invoke function returning `SafeSocketHandle` throws "System.MissingMethodException: .ctor". See [MissingSafeSocketHandleCtor.zip](https://github.com/dotnet/runtime/files/5646646/MissingSafeSocketHandleCtor.zip) for a full repro project.

```c#
    public static class Program
    {
        private const int AF_INET = 2;
        private const int SOCK_STREAM = 1;

        public static void Main()
        {
            // System.MissingMethodException: '.ctor'
            // (This returns -1 because we have not initialized WinSock2; that does not matter, though.)
            var sock = socket(AF_INET, SOCK_STREAM, 0);
            sock.Dispose();
        }

        [DllImport("Ws2_32.dll")]
        public static extern SafeSocketHandle socket(int af, int type, int protocol);
    }
```

### Configuration

- .NET SDK 5.0.100
- Windows 10 Pro x64 (20H2, 19042.630)

### Regression?

Yes. Worked on 3.1.404.

### Other information

[The SafeHandle doc](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.safehandle?view=net-5.0#notes-to-implementers) says "You should also provide a parameterless constructor".

A parameterless ctor is defined in the `SafeSocketHandle` [source file](https://github.com/dotnet/runtime/blob/v5.0.0-rtm.20519.4/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SafeSocketHandle.cs#L41) but missing from the released assembly at "C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.0\System.Net.Sockets.dll".

I do not think this is an intended behavior. I do now know the root cause, though.

Stack traces:

```
Unhandled exception. System.MissingMethodException: .ctor
   at ConsoleAppSafeSocketHandle.WinSock2.socket(Int32 af, Int32 type, Int32 protocol)
   at ConsoleAppSafeSocketHandle.Program.Main()
```

**Comment by asmichi** [comment] 2020-12-05 07:22
I just wanted to bring this to your attention. Something seems wrong with the released assemblies.

This issue itself is not a blocking issue to me because this issue is easy to work around. It is even acceptable to me if this is marked as an unsupported use case (by design).

**Comment by GrabYourPitchforks** [comment] 2020-12-05 07:25
Possible linker issue? I'd think the linker would special-case `SafeHandle`-derived types and not remove the ctors, but possible something went wrong in this instance.

/cc @marek-safar @MichalStrehovsky

**Comment by marek-safar** [comment] 2020-12-05 07:29
Yep, see https://github.com/mono/linker/issues/1660

**Comment by stephentoub** [comment] 2020-12-05 11:39
@marek-safar, so even though the ctor exists:
https://github.com/dotnet/runtime/blob/dc0e11d2e681659fc20feebf4c092082e75706af/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SafeSocketHandle.cs#L41
the linker is trimming it out in the assembly build because no P/Invokes are using it in the assembly build?

This should be fixed in servicing; I'm not sure how that works.  Can we service the linker and then service release/5.0 to use the updated linker?

**Comment by GrabYourPitchforks** [comment] 2020-12-05 19:20
As a follow-up, we should diff all (incl. non-public) members of the runtime + BCL's pre-trimmed DLLs and post-trimmed DLLs. Could help identify other places where we've inadvertently made a break.

**Comment by MichalStrehovsky** [comment] 2020-12-07 09:36
> the linker is trimming it out in the assembly build because no P/Invokes are using it in the assembly build?

Yeah, I assume this code would cover it if the SafeHandle was actually used in a p/invoke:

https://github.com/mono/linker/blob/b24d0e663d5bf4772b0896e2bc3dab3391fae744/src/linker/Linker.Steps/MarkStep.cs#L2647-L2648

It happens to cover safe handles and things like blittable classes. If the SafeHandle is actually used in a p/invoke, linker will keep it. But it's not used in a p/invoke during the library build.

Linker should probably treat constructors of SafeHandles the same as if they were public.

**Comment by marek-safar** [comment] 2020-12-07 12:25
Yep, this is an actually different issue. We are trimming the constructor as part of libraries build because it's not referenced anywhere and it's private.

I don't think there is much to be fixed in the linker. The linker on final apps would work fine if the constructor was actually present in the runtime/SDK assemblies. We should fix libraries build not to trim such constructors. There are multiple ways how to do it, one of them is to change the constructor to be public.

**Comment by stephentoub** [comment] 2020-12-07 12:45
> one of them is to change the constructor to be public

We should not need to contort the public API surface; whether we want to expose that ctor to be used by code directly is a separate conversation.

> Linker should probably treat constructors of SafeHandles the same as if they were public

I agree with @MichalStrehovsky on this. This isn't specific to this particular SafeHandle.

**Comment by marek-safar** [comment] 2020-12-07 13:15
> We should not need to contort the public API surface

I meant to make it public in the implementation library, there are many other options but private does not feel like the right fit for a method which is called externally.

> Linker should probably treat constructors of SafeHandles the same as if they were public

We could add another quirk option for the libraries build only into linker but that sounds like a riskier option for servicing to me.

> This isn't specific to this particular SafeHandle.

Correct but wouldn't be better to handle the analysis of correct pinvoke support of SafeHandles via Roslyn Analyzers or even source code generator?

**Comment by stephentoub** [comment] 2020-12-07 13:45
> Correct but wouldn't be better to handle the analysis of correct pinvoke support of SafeHandles via Roslyn Analyzers or even source code generator?

I'm not following.  It's perfectly correct to have a public SafeHandle with a private parameter less ctor and that isn't used by any P/Invokes in that library. And such a SafeHandle, like the one in question here,  would validate correctly with an analyzer.

**Comment by jkotas** [comment] 2020-12-07 14:27
The current convention for safe handle constructors works poorly for source generated interop as well. The constructor cannot be invoked directly from source, and thus it requires workarounds using private reflection or similar solution. cc @AaronRobinsonMSFT 

I agree with @marek-safar that the best forward looking option is to mark the safe handle constructors as public.

A separate question is whether this is the best option for servicing. It may be - marking a few methods public in the implementation is fairly low-risk.

**Comment by MichalStrehovsky** [comment] 2020-12-07 14:35
Note that this problem is not limited to SafeHandle - interop will also call private parameterless constructors of blittable classes if they're in an `out` position, so linker would also need to assume those are used too, for parity. It kind of feels like a reflection-like problem, thinking about it more.

We've been using ILLinkTrim/making members public as a solution to private reflection problems.

**Comment by stephentoub** [comment] 2020-12-07 14:37
> I agree with @marek-safar that the best forward looking option is to mark the safe handle constructors as public.

If we want to define new guidelines moving forward for new stuff,  and retroactively make sure all our SafeHandles conform, that's fine.  But it doesn't change the fact that a) the linker is  a public tool for use in the ecosystem and should work with standard .NET patterns,  and b) private ctors are supported as a standard pattern with SafeHandle.

**Comment by jkotas** [comment] 2020-12-07 14:45
Many .NET patterns are fundamentally incompatible with linking. We can always add more special cases to the linker to make some of these patterns work. It makes the complexity to go through the roof. We went this route with .NET Native implementation of the linker. It was not a successful sustainable path.

I am just saying that there is a balance to strike. Just because of somethign is standard .NET pattern does not imply that linker has to support it.

**Comment by jkotas** [comment] 2020-12-07 15:01
> The linker on final apps would work fine if the constructor was actually present in the runtime/SDK assemblies.

Is it going to work fine when the SafeHandle is used as argument of a marshaled delegate; or when the interop signature is emitted via Reflection.Emit?

**Comment by MichalStrehovsky** [comment] 2020-12-07 15:04
> Is it going to work fine when the SafeHandle is used as argument of a marshaled delegate

Nope: https://github.com/mono/linker/issues/1660

> interop signature is emitted via Reflection.Emit

I was going back and forth whether Ref.Emit should be considered linking safe or not. Maybe this is the case where it isn't.

**Comment by marek-safar** [comment] 2020-12-07 15:04
> private ctors are supported as a standard pattern with SafeHandle.

That's the pattern linker supports today and works fine but we run linker in a special mode nobody else runs for our own build. We run linker on single library in kind of pre-trim mode to remove any unused methods. We have handled previous cases where unused methods were removed via XML descriptors, new linker options but and we could handle it with yet another special option but I think we have a broader problem here.

1, Are we sure we have the right default constructors on all SafeHandle types?
2, If never referenced methods are problematic with tooling (source generators, correctness tools, etc) is adding a special flag to linker the right solution?

**Comment by stephentoub** [comment] 2020-12-07 16:31
> Many .NET patterns are fundamentally incompatible with linking.

This seems equally unsustainable,  if "many" common patterns simply fail to work properly.  Do  most of them produce warnings? This one obviously doesn't.

**Comment by jkotas** [comment] 2020-12-07 17:00
They do not produce warnings today and it is something we need to work on. We have a long way to go on linker compatibility.

The problematic relationship of interop and linker friendliness is called out as one of the motivations for https://github.com/dotnet/runtime/blob/master/docs/design/features/source-generator-pinvokes.md. I expect that we will eventually recommend interop source generators for linker friendliness of all interop, except the most trivial one.

**Comment by AaronRobinsonMSFT** [comment] 2020-12-07 18:36
>I expect that we will eventually recommend interop source generators for linker friendliness of all interop, except the most trivial one.

For what its worth the Interop team is going to be writing a proposal to handle this for source generators - see https://github.com/dotnet/runtime/issues/43060 under "New .NET APIs".

**Comment by MichalStrehovsky** [comment] 2020-12-07 20:53
> Do most of them produce warnings? This one obviously doesn't.

I just want to reiterate Marek's comment: "That's the pattern linker supports today and works fine but we run linker in a special mode nobody else runs for our own build" - if we were trimming an entire app and the SafeHandle is actually used in a p/invoke, linker would keep the ctor - not because linker knows about SafeHandle, but because it just keeps ctors of all parameter types used in `out`/return position of p/invokes. The issue here is hit because we run linker in a weird mode as part of library build that is not a user scenario with nice warnings. It's the "I know what I'm doing" mode.

**Comment by stephentoub** [comment] 2020-12-08 01:42
> I just want to reiterate Marek's comment

I understand this isn't the "trim my app" mode.  But at the same time, we trim the libraries we ship for a reason, to reduce the size of the shared framework distribution, and that reason could be meaningful for any library builder.  If memory serves, this reduced the size of our libraries on average by 5-10%.  Who wouldn't want their nuget package to be 5-10% smaller?  (Rhetorical question.)  I get this isn't the primary use case for the linker, and that's fine.  But I don't think we should be discounting the use case nor the bugs that end up silently introduced when it's used in this supported fashion.

Regardless, this makes me wonder what other issues are lurking, with things being trimmed away we weren't expecting.  I definitely agree with @GrabYourPitchforks earlier suggestion:

> As a follow-up, we should diff all (incl. non-public) members of the runtime + BCL's pre-trimmed DLLs and post-trimmed DLLs. Could help identify other places where we've inadvertently made a break.

**Comment by AaronRobinsonMSFT** [comment] 2020-12-08 01:54
> Regardless, this makes me wonder what other issues are lurking, with things being trimmed away we weren't expecting.

Not to pile on, but merely to provide another example. I have had to debug scenarios where the linker broke a COM interface 3 times this year alone - this isn't always obvious when it happens. @elinor-fung also had rather painful debugging sessions where the root cause ends up being a broken VTable because the linker helpfully removed unused methods.

**Comment by MichalStrehovsky** [comment] 2020-12-08 10:10
> Not to pile on, but merely to provide another example. I have had to debug scenarios where the linker broke a COM interface 3 times this year alone

As of .NET 5, linker will emit [IL2050 warning](https://github.com/mono/linker/blob/a31189957106008322166f87f892bfe1b86409ff/docs/error-codes.md#il2050-trim-analysis-correctness-of-com-interop-cannot-be-guaranteed) if it sees COM. Unfortunately it's one of the warning codes one needs to opt into with `<SuppressTrimAnalysisWarnings>false</SuppressTrimAnalysisWarnings>` because there's just too many of those within the base class libraries. Once the user convinces themselves their use of COM is safe, they can suppress the warning with `UnconditionalSuppressMessageAttribute`.

"Linker broke my app without a warning message" cases are considered bugs for the externally supported configurations (i.e. trim with a whole program view).

**Comment by samsp-msft** [comment] 2020-12-08 21:35
Stepping back a bit:
1. Do we know which constructors are being overly aggressively trimmed?
2. What are the possible mitigations?
   1. Modify the linker so it knows this pattern and doesn't trim them - seems like this is a rabbit hole of magic that we don't want to go down
   1. Make the constructors public - but changes the API surface
   1. Use some form of annotation - either XML or attribute to tell linker not to remove them
3. When does this need to be fixed? It sounds like this could be a problem in 5.0 so should be serviced?
4. It sounds like we should do a metadata diff to confirm what the linker is removing from 5.x - Who will own this initiative?

**Comment by marek-safar** [comment] 2020-12-09 12:11
> Do we know which constructors are being overly aggressively trimmed?

We do and it should not be hard to generate a list for the whole runtime libraries.

> When does this need to be fixed?

It's 5.0 regression which should be addressed in servicing

> It sounds like we should do a metadata diff to confirm what the linker is removing from 5.x - Who will own this initiative?

We could but that's a separate effort from this issue, presumably, someone on @danmosemsft team should do that.

**Comment by GrabYourPitchforks** [comment] 2020-12-09 17:17
> Modify the linker so it knows this pattern and doesn't trim them - seems like this is a rabbit hole of magic that we don't want to go down

Why wouldn't we want to enlighten the linker about this pattern? Using a private constructor to initialize SafeHandle-derived types is a well-established pattern that has been around since .NET 2.0. This pattern also occurs frequently within third-party libraries. When developers trim their apps, wouldn't we expect the linker to inspect these dependencies as well?

**Comment by marek-safar** [comment] 2020-12-09 17:22
> When developers trim their apps, wouldn't we expect the linker to inspect these dependencies as well?

As it was explained above few times, that's not the problem here. This pattern works as expected.

**Comment by GrabYourPitchforks** [comment] 2020-12-09 17:49
> As it was explained above few times, that's not the problem here. This pattern works as expected.

I must've misunderstood the conversation between you and Michal and Steve. We run the linker over our individual assemblies in a special mode that says "please trim uncalled private code but preserve all public APIs." Judging from Steve's comment, this mode of operation is supported as a post-compile step for library authors to reduce the size of their NuGet packages. But based on Michal's comment, this trimming step doesn't actually understand the SafeHandle pattern. Rather, only during cross-assembly analysis (where unused _public_ APIs are trimmed) is p/invoke special-cased.

If the "trim uncalled private code from my library but preserve all public APIs" switch really is supported, then the argument I'm trying to make is that the linker when running in this mode of operation would ideally have knowledge about SafeHandle and other common .NET patterns. It would save developers the busy work of having to slap `[DynamicDependency]` everywhere.

**Comment by marek-safar** [comment] 2020-12-09 18:02
> this mode of operation is supported as a post-compile step for library authors to reduce the size of their NuGet packages.

I don't think that's the case, the setup for this is complicated and requires several advanced options to be set correctly. It'd also question if it has any noticeable impact as you are not really trimming but more like tweaking compiler output.

**Comment by samsp-msft** [comment] 2020-12-09 18:18
@marek-safar - who should this bug be assigned to?

**Comment by stephentoub** [comment] 2020-12-09 20:46
> It'd also question if it has any noticeable impact 

I'm not following: We do it because it does. You're saying it no longer does for us, or our libraries are different, or we care about reductions too small for others to care about,  or something else?

**Comment by GrabYourPitchforks** [comment] 2020-12-09 21:42
TBH, if the linker is trimming significant dead code from our libraries, then that might be an indication that we should just delete that code. Code that's ifdefed away might be an exception, but I would expect that to be a minority of hits.

**Comment by stephentoub** [comment] 2020-12-09 21:53
It's able to delete things like private const fields, private ctors used to prevent the automatic introduction of a public one, methods in shared files where only some are used in a given library,  etc.

**Comment by jkotas** [comment] 2020-12-09 21:53
> the linker is trimming significant dead code from our libraries, then that might be an indication that we should just delete that code.

The two main categories of code that the linker is trimming:
- Internal and private constants that we frequently use for clarity. Roslyn emits them into metadata even though they cannot be ever used for anything meaningful. This is in the "we care about reductions too small for others to care about" category.
- Unused methods from helpers under "Common" that are not practical to ifdef with fine granularity. This is in "our libraries are different" category.
- Unreachable platform specific code like implementations optimized using x86 hardware intrinsics on ARM, and vice versa. More details in https://github.com/dotnet/runtime/pull/37615/. This optimization is enabled in CoreLib only currently. It would be nice to enable it for everything shipping in the shared framework.

**Comment by jkotas** [comment] 2020-12-09 22:04
> @marek-safar - who should this bug be assigned to?

I think this bug should go to the linkable framework working group under @danmosemsft .

There are two aspects:
- What to do for .NET servicing: I think we should do something low-risk like add linker .xml to pin the constructor or flip the constructors in the implementation to public.
- What to do going forward: I think we should change the guideline for SafeHandle constructors to make them public, and fix all SafeHandles in the framework to conform.

**Comment by stephentoub** [comment] 2020-12-09 22:08
> What to do going forward: I think we should change the guideline for SafeHandle constructors to make them public

This alone makes it easy to create a handle instance you can't actually use, as the private ctor was used by the runtime with access to the protected handle field as well.  We'd probably also want to add a public SetHandle-like API, while thinking through implications on source compatibility with such a new method on the base type.

**Comment by danmosemsft** [comment] 2020-12-09 22:09
cc @eerhardt 

Folks that hit this in 5.0 have the workaround of adding a linker.xml file, right? It's just tough for them to realize what the fix/workaround is.

**Comment by AaronRobinsonMSFT** [comment] 2020-12-09 22:10
>What to do going forward: I think we should change the guideline for SafeHandle constructors to make them public, and fix all SafeHandles in the framework to conform.

Yes. This is part of what the interop team will be proposing to help support the [`DllImport` source generator](https://github.com/dotnet/runtime/issues/43060).

/cc @jkoritzinsky @elinor-fung

**Comment by marek-safar** [comment] 2020-12-09 22:11
> You're saying it no longer does for us, or our libraries are different, or we care about reductions too small for others to care about, or something else?

It was in the quote ".. step for library authors to reduce the size of their NuGet packages."

> who should this bug be assigned to?

I think this should be handled on @danmosemsft side for servicing. Maybe @eerhardt can quickly step in but the cut for 5.0.2 is soon.

>  I think we should do something low-risk like add linker .XML 

I agree that XML descriptor for libraries build is the easiest fix with no risks.

**Comment by stephentoub** [comment] 2020-12-09 22:12
> Folks that hit this in 5.0 have the workaround of adding a linker.xml file, right? It's just tough for them to realize what the fix/workaround is.

For SafeSocketHandle, no; it's removed as part of our build of the .dll.

**Comment by AaronRobinsonMSFT** [comment] 2020-12-09 22:20
>For SafeSocketHandle, no; it's removed as part of our build of the .dll.

This was one of the COM related issues that also occurred: https://github.com/dotnet/coreclr/pull/28061

**Comment by eerhardt** [comment] 2020-12-10 00:35
For the 5.0 fix, I looked through all SafeHandle types in the shared framework with the following code:

```C#
using System;
using System.IO;
using System.Reflection;
using System.Runtime.InteropServices;

foreach (var file in Directory.EnumerateFiles(@"C:\Program Files\dotnet\shared\Microsoft.NETCore.App\5.0.1\", "*.dll"))
{
    Assembly assembly;
    try
    {
        assembly = Assembly.Load(Path.GetFileNameWithoutExtension(file));
    }
    catch
    {
        continue;
    }

    foreach (Type t in assembly.GetTypes())
    {
        if (t.IsAssignableTo(typeof(SafeHandle)) && t.IsPublic && !t.IsAbstract)
        {
            if (t.GetConstructor(BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Instance, null, Type.EmptyTypes, null) == null)
            {
                Console.WriteLine(t.FullName);
            }
        }
    }
}
```

That spit out 2 types that would have this issue:

```
System.Net.Sockets.SafeSocketHandle
System.Security.Cryptography.SafeEvpPKeyHandle
```

So to fix this in 5.0 servicing, my plan is to introduce 2 "Library_Build" XML descriptors for the 2 SafeHandles above. That will ensure their private constructors are preserved.

Going forward, I agree that we need a better long term strategy here - manually inspecting/verifying that every SafeHandle we create has the right constructors after building isn't a sustainable solution.

_____

Looking through the rest of the SafeHandle types that aren't public, one jumps out that may be in trouble: `System.Reflection.Emit.PunkSafeHandle`.

https://github.com/dotnet/runtime/blob/53c16198a8417e87e62c9df7c5e2e2602f9aa01d/src/coreclr/System.Private.CoreLib/src/System/Reflection/Emit/ISymWrapperCore.cs#L368-L374

This SafeHandle is used as an `Out` of a delegate to a native function. Looking through the code, it appears this is only ever used if someone calls `AssemblyBuilder::DefineDynamicModule(name, emitSymbolInfo: true)`. However, that API is not public in .NET Standard or .NET Core - only .NET Framework and Mono. So there is no way for a test, or user code to call into `PunkSafeHandle`, from what I can tell.

**Comment by eerhardt** [comment] 2020-12-10 17:44
Some more information on the above research:

1. `System.Security.Cryptography.SafeEvpPKeyHandle` is only used with OpenSsl which doesn't work on Windows and throws PNSE.The default ctor exists for this Type on Linux. There isn't a reason someone would use this type on Windows, so I don't think we should make a change for it.

2. I ran the above program on Linux and macOS, and it identified 4 other potentially problematic SafeHandles on non-Windows builds:
    - `Microsoft.Win32.SafeHandles.SafeRegistryHandle`
    - `Microsoft.Win32.SafeHandles.SafeAccessTokenHandle`
    - `Microsoft.Win32.SafeHandles.SafeMemoryMappedFileHandle`
    - `Microsoft.Win32.SafeHandles.SafeMemoryMappedViewHandle`

The first 2 are Windows-specific, so there is no need to change them, for the same reason as `SafeEvpPKeyHandle` on Windows.

The 2 MemoryMapped SafeHandles can be used cross-platform. We have never shipped a non-Windows version of `SafeMemoryMappedFileHandle` that has had a default ctor. This SafeHandle is sort of "fake" on non-Windows anyway - it uses a fake IntPtr and doesn't release anything in ReleaseHandle(). So I don't think we should change `SafeMemoryMappedFileHandle`.

The only remaining SafeHandle is `SafeMemoryMappedViewHandle`. We DID ship a default ctor on this type for non-Windows for `v1.0` and `v1.1`. However, it was removed in `v2.0` (which is the release we started trimming the shared fx assemblies during the build). Someone could theoretically use this type as the return value of a p/invoke into `mmap`. So I'm leaning towards changing this one to be on the safe side.

**Comment by eerhardt** [comment] 2020-12-11 02:34
Reopening for backport to 5.0.

**Comment by eerhardt** [comment] 2020-12-12 01:14
This is now fixed in master and release/5.0

**Closed by eerhardt** 2020-12-12 01:14 UTC
Labels: area-System.Net.Sockets, linkable-framework, regression-from-last-release

**Comment by NN---** [comment] 2021-01-03 20:58
@eerhardt When can we expect releasing .NET 5 update with the fix ?

**Comment by eerhardt** [comment] 2021-01-03 21:37
> When can we expect releasing .NET 5 update with the fix ?

This fix is in the release branch, so the next servicing release of .NET 5 will have the fix. According to https://docs.microsoft.com/en-us/dotnet/core/releases-and-support, `Servicing updates` ship almost every month, and 5.0.1 shipped in December. So I'd guess that 5.0.2 would ship in January or February.

**Comment by marek-safar** [comment] 2021-01-04 11:35
5.0.2 should go out next week, you can test the fix by installing https://github.com/dotnet/installer#installers-and-binaries 5.0.2 preview version
