### ISSUE TITLE
Test failure: System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values. (Parameter 'index')

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#46111] opened 2020-12-16 02:43 UTC
failed in job: [runtime-libraries-coreclr outerloop 20201215.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=921603&view=ms.vss-test-web.build-test-results-tab&runId=29274760&resultId=101017&paneView=debug)

failed tests:
System.Collections.Tests.SortedDictionary_Generic_Tests_EquatableBackwardsOrder_int.ICollection_Generic_Add_AfterRemovingAllItems(count: 75)
System.Collections.Tests.SortedList_Generic_Tests_EquatableBackwardsOrder_int.ICollection_Generic_Add_AfterRemovingAllItems(count: 75)

net6.0-Linux-Release-x64-CoreCLR_release-Centos.7.Amd64.Open

Error message
~~~
System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values. (Parameter 'index')


Stack trace
   at System.Linq.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument) in /_/src/libraries/System.Linq/src/System/Linq/ThrowHelper.cs:line 15
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index) in /_/src/libraries/System.Linq/src/System/Linq/ElementAt.cs:line 50
   at System.Collections.Tests.ICollection_Generic_Tests`1.ICollection_Generic_Add_AfterRemovingAllItems(Int32 count) in /_/src/libraries/Common/tests/System/Collections/ICollection.Generic.Tests.cs:line 260
~~~

**Comment by danmosemsft** [comment] 2020-12-16 03:47
@v-haren  please add only one "area-" label to an issue, thanks

**Comment by eiriktsarpalis** [comment] 2020-12-16 13:19
Test started failing yesterday and seems to impact Linux x64 hosts. I couldn't reproduce the failure on my local Ubuntu device so will try to repro using a draft PR.

**Comment by eiriktsarpalis** [comment] 2021-01-04 12:27
The test failure has stopped occurring in CI for a while now, so I'm going to close this.

**Closed by eiriktsarpalis** 2021-01-04 12:27 UTC
Labels: area-System.Collections, untriaged
