### ISSUE TITLE
[.NET 5 regression] Socket.AsyncOperation gets processed too many times

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#45673] opened 2020-12-07 09:56 UTC
@geoffkizer commented in https://github.com/dotnet/runtime/pull/37974#issuecomment-739418447:

> @tmds I happened to be looking at this code and I'm confused by something.
You added the bool processAsyncEvents = true argument to ProcessSyncEventOrGetAsyncEvent, but it doesn't seem like this is actually getting set to false anywhere. All callers are either explicitly passing true or using the default arg value, which is true.

This should have been be set to `false` when it gets called in `HandleEvents` to avoid processing an `AsyncOperation` multiple times.

https://github.com/dotnet/runtime/blob/1d9e50cb4735df46d3de0cee5791e97295eaf588/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs#L2091-L2114

Calling Process multiple times can lead to weird issues. When the first call leads to completing the operation, the instance may be reused for another operation by the time Process gets called the second time.

cc @karelz @antonfirsov @stephentoub @dotnet/ncl

**Comment by karelz** [comment] 2021-01-05 20:46
Triage: We will run it by shiproom for backporting. While not super bad, in certain rare situations it can cause quite a lot of headaches and servicing issues.

**Comment by geoffkizer** [comment] 2021-01-05 21:09
@karelz Can you point me to the servicing template? I can't remember where to find it.

Details for shiproom:

When we get epoll notifications for a particular socket, we can get either a read notification, a write notification, or both. Each notification will cause us to perform the IO and then invoke the user callback.

Prior to PR https://github.com/dotnet/runtime/pull/37974, when we got both notifications, we would dispatch one notification to the thread pool so that both user callbacks can be processed concurrently. 

Unfortunately, https://github.com/dotnet/runtime/pull/37974 inadvertently broke this behavior, and instead resulted in the notifications being processed in sequence. This means that the second IO operation and callback won't be invoked until the first callback completes, which could in theory take arbitrarily long.

This can lead to unexpected behavior and, at worst, deadlocks. It's probably not that common in practice, but it would be extremely hard to diagnose if it was hit.

The fix is straightforward -- we simply revert to the previous correct behavior here, and isolate the changes from https://github.com/dotnet/runtime/pull/37974 so they do not affect the common path.

I believe we should take this fix for 5.0.

**Comment by antonfirsov** [comment] 2021-01-06 11:21
> Can you point me to the servicing template? I can't remember where to find it.

A recent example: #46598.

**Comment by geoffkizer** [comment] 2021-01-06 18:57
## Customer Impact

When we get epoll notifications for a particular socket, we can get either a read notification, a write notification, or both. Each notification will cause us to perform the IO and then invoke the user callback.

Prior to PR #37974, when we got both notifications, we would dispatch one notification to the thread pool so that both user callbacks can be processed concurrently.

Unfortunately, #37974 inadvertently broke this behavior, and instead resulted in the notifications being processed in sequence. This means that the second IO operation and callback won't be invoked until the first callback completes, which could in theory take arbitrarily long.

This can lead to unexpected behavior and, at worst, deadlocks. It's probably not that common in practice, but it would be extremely hard to diagnose if it was hit.

## Regression?

Yes, caused by #37974 in 5.0.

## Testing

It's not really possible to write a test for this because it requires epoll signalling both the read and write notification in the same notification, which is timing dependent and very difficult to make happen consistently.

## Risk

Low. The fix is to basically just revert to the previous correct behavior here, and isolate the changes from #37974 so they do not affect the common path.

**Comment by antonfirsov** [comment] 2021-01-08 14:07
I opened #46745 to push this forward. Need a few approvals before the shiproom meeting + we need to run TechEmpower.

**Comment by karelz** [comment] 2021-02-12 07:58
Fixed in 6.0 (master) in PR #45683 and in 5.0.4 in PR #46745.

**Closed by karelz** 2021-02-12 07:58 UTC
Labels: area-System.Net.Sockets, bug
