### ISSUE TITLE
The version in HttpRequestMessage had no validate

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/runtime#56662] opened 2021-07-31 04:45 UTC
When I try to specify the HTTP version for the HTTP request, I found that there's no validation on the version, you can set whatever version you want, the request message `ToString()` would output the version directly

For example:

``` c#
var request = new HttpRequestMessage(HttpMethod.Get, "https://google.com")
{
    Version = new Version(4, 0)
};
Console.WriteLine(request.ToString());
```

output:

```
Method: GET, RequestUri: 'https://google.com/', Version: 4.0, Content: <null>, Headers:
{
}
```

while the HTTP version used is `HTTP/1.1`, not the `4.0` 
![image](https://user-images.githubusercontent.com/7604648/127728823-c6e7180e-d318-441f-a9e1-35f72a782d4d.png)

Maybe the request version would be misleading if the HTTP version in `HttpRequestMessage` is not the same with the actual 
HTTP version

**Comment by MihaZupan** [comment] 2021-07-31 08:32
The default `HttpVersionPolicy` is `RequestVersionOrLower`, so establishing 1.1 here is fine.

If you instead set it to `Exact` or `RequestVersionOrHigher`, you should see an exception being thrown before anything is sent.

**Comment by karelz** [comment] 2021-07-31 09:12
If you want to avoid typos, you can use pre-defined versions: https://docs.microsoft.com/en-us/dotnet/api/system.net.httpversion

Closing as By Design.

**Closed by karelz** 2021-07-31 09:12 UTC
Labels: area-System.Net.Http

**Comment by WeihanLi** [comment] 2021-07-31 09:21
The request message version is the same as the request message version in the response message, while the HTTP version in the response message is 1.1, and it seemed it would not throw an exception even when I set the `DefaultVersionPolicy = HttpVersionPolicy.RequestVersionExact` for httpClient

![image](https://user-images.githubusercontent.com/7604648/127735234-1a253485-73bd-4308-8448-2684b7e5b26f.png)

When I set `DefaultVersionPolicy = HttpVersionPolicy.RequestVersionExact` for the request message, I would get an exception

![image](https://user-images.githubusercontent.com/7604648/127735328-1b5b886a-00e6-4009-9b93-2b4a781159a3.png)

Thanks for your quick answer @MihaZupan @Kahbazi

**Comment by MihaZupan** [comment] 2021-07-31 09:26
That's correct, the version policy set on `HttpClient` applies to helper methods that take Uri/string.
If you provide an `HttpRequestMessage` yourself, its policy applies.

**Comment by WeihanLi** [comment] 2021-07-31 09:29
Got it, great thanks @MihaZupan
