### ISSUE TITLE
WASM JS->C# byte[] call parameter doesn't transfer

### ISSUE THREAD

**Issue by TanayParikh** [dotnet/runtime#53540] opened 2021-06-01 17:19 UTC
On JS, I'm using `js_typed_array_to_array(Uint8Array)` to get the pointer to send to C# as a method parameter. 

Expected: C# receives a byte[]
Actual: C# receives a int ptr / `m_value`

This may be a **lower priority** issue as there's a potential work around:
- JS->C# notify byte array available
- C#->JS InvokeUnmarshalled<byte[]>("someFunction")
- The byte array is returned.

Context: https://github.com/dotnet/aspnetcore/pull/33015/files#diff-95f352edb40d191b749ec1f34bf7404f704111b750bbf4ad78cef791a47e8866R77-R91

**Comment by TanayParikh** [comment] 2021-06-01 17:21
cc/ @SteveSandersonMS @javiercn

**Comment by javiercn** [comment] 2021-06-01 17:52
@TanayParikh I already filed an issue for this. I'm going to close this one.

**Comment by javiercn** [comment] 2021-06-01 17:53
This is a dupe of https://github.com/dotnet/runtime/issues/53378

**Closed by javiercn** 2021-06-01 17:52 UTC
Labels: untriaged
