### ISSUE TITLE
Test failure: GC\LargeMemory\API\gc\suppressfinalize\suppressfinalize.cmd

### ISSUE THREAD

**Issue by AriNuer** [dotnet/runtime#13644] opened 2019-10-25 08:24 UTC
Test `GC\LargeMemory\API\gc\suppressfinalize\suppressfinalize.cmd` has failed.

**Build:**[20191024.2](https://dnceng.visualstudio.com/internal/_build/results?buildId=400740)(Master)

**Details:**
https://dnceng.visualstudio.com/internal/_build/results?buildId=400740&view=ms.vss-test-web.build-test-results-tab&runId=12514574&resultId=109800&paneView=debug

**OS & Arch:**
Windows x64

**Queue name:**
R2R Windows_NT x64 Release @ Windows.10.Amd64

**Log:**
```
Error message
Return code: 1
Raw output file: C:\\dotnetbuild\\work\\52df63c8-3358-4f16-ae49-fd75ff9049de\\Work\\9352bd48-d7af-4f0d-b374-458446ab8a21\\Exec\\GC\\LargeMemory\\Reports\\GC.LargeMemory\\API\\gc\\suppressfinalize\\suppressfinalize.output.txt
Raw output:
BEGIN EXECUTION
1 file(s) copied.
" C:\\dotnetbuild\\work\\52df63c8-3358-4f16-ae49-fd75ff9049de\\Payload\\crossgen.exe\" /Platform_Assemblies_Paths C:\\dotnetbuild\\work\\52df63c8-3358-4f16-ae49-fd75ff9049de\\Payload;C:\\dotnetbuild\\work\\52df63c8-3358-4f16-ae49-fd75ff9049de\\Work\\9352bd48-d7af-4f0d-b374-458446ab8a21\\Exec\\GC\\LargeMemory\\API\\gc\\suppressfinalize\\IL;C:\\dotnetbuild\\work\\52df63c8-3358-4f16-ae49-fd75ff9049de\\Work\\9352bd48-d7af-4f0d-b374-458446ab8a21\\Exec\\GC\\LargeMemory\\API\\gc\\suppressfinalize /in suppressfinalize.org /out suppressfinalize.dll
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
Copyright (c) Microsoft Corporation. All rights reserved.
Native image suppressfinalize.dll generated successfully.
\"C:\\dotnetbuild\\work\\52df63c8-3358-4f16-ae49-fd75ff9049de\\Payload\\corerun.exe\" suppressfinalize.dll 2048 
Large Memory Machine required
Test failed
Expected: 100
Actual: 0
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\\dotnetbuild\\work\\52df63c8-3358-4f16-ae49-fd75ff9049de\\Payload\r\n> C:\\dotnetbuild\\work\\52df63c8-3358-4f16-ae49-fd75ff9049de\\Work\\9352bd48-d7af-4f0d-b374-458446ab8a21\\Exec\\GC\\LargeMemory\\API\\gc\\suppressfinalize\\suppressfinalize.cmd
Expected: True
Actual: False

Stack trace
at GC_LargeMemory._API_gc_suppressfinalize_suppressfinalize_._API_gc_suppressfinalize_suppressfinalize_cmd() in F:\workspace\_work\1\s\bin\tests\Windows_NT.x64.Release\TestWrappers\GC.LargeMemory\GC.LargeMemory.XUnitWrapper.cs:line 433
```

**Comment by mangod9** [comment] 2020-07-02 16:12
closing since its a likely dupe of #13551 which @cshung fixed with #32545

**Closed by mangod9** 2020-07-02 16:12 UTC
Labels: arch-x64, area-GC-coreclr, os-windows
