### ISSUE TITLE
Backspace does not work properly when using Console.ReadLine() in Alpine

### ISSUE THREAD

**Issue by RdJNL** [dotnet/runtime#64355] opened 2022-01-26 22:37 UTC
### Description

When doing a `Console.ReadLine()` in Alpine on Docker, the backspace key isn't working correctly. When pressing backspace, the last character is not removed from the input that's displayed. However, when pressing enter, the characters that were removed by the backspace are actually removed, so they're not in the actual input even though they're still showing in the console.

### Reproduction Steps

Using this one line C# program:

```csharp
while (true) { Console.WriteLine(Console.ReadLine()); }
```

And running this in a Docker container on Alpine (you may have to edit the project path, etc.):
<details>
  <summary>Dockerfile</summary>
  
  ```dockerfile
  FROM mcr.microsoft.com/dotnet/runtime:6.0-alpine AS base
  
  FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
  WORKDIR /src
  COPY ["DockerNETConsoleTest/DockerNETConsoleTest.csproj", "DockerNETConsoleTest/"]
  RUN dotnet restore "DockerNETConsoleTest/DockerNETConsoleTest.csproj" -r alpine-x64 --no-cache
  
  COPY . .
  RUN dotnet build "DockerNETConsoleTest/DockerNETConsoleTest.csproj" -c Release --no-restore -r alpine-x64 --no-self-contained
  
  FROM build AS publish
  RUN dotnet publish "DockerNETConsoleTest/DockerNETConsoleTest.csproj" -c Release --no-build -r alpine-x64 --no-self-contained -o /app
  
  FROM base AS final
  COPY --from=publish /app /app
  ENTRYPOINT ["dotnet", "/app/DockerNETConsoleTest.dll"]
  ```
  
</details>

1) Build and run with Docker with `-it` flags
1) Type some text (no enter)
1) Hit backspace
1) No text is erased
1) Press enter
1) The typed text is echoed with the text erased from the backspace

### Expected behavior

When pressing backspace, the input displayed in the console reflects this by removing the last character.

### Actual behavior

No character is removed when pressing backspace, but it is removed from the actual input.

### Known Workarounds

Use a heavier Debian distro (see configuration below).

### Configuration

* .NET 6
* Windows 10 x64
* Running Docker cli in Windows Terminal/Powershell
* Docker 20.10.12
* mcr.microsoft.com/dotnet/runtime:6.0-alpine base image

Seems to work ok on mcr.microsoft.com/dotnet/runtime:6.0 (test by changing the base image in the provided dockerfile, and change the -r flag for restore, build and publish to linux-x64)

**Comment by adamsitnik** [comment] 2022-03-14 12:22
@tmds do you think that it can be related to https://github.com/dotnet/runtime/pull/49649 ?

**Comment by adamsitnik** [comment] 2023-11-13 18:52
> @tmds do you think that it can be related to https://github.com/dotnet/runtime/pull/49649 ?

@tmds ping

**Comment by tmds** [comment] 2023-11-16 09:31
> do you think that it can be related to https://github.com/dotnet/runtime/pull/49649 ?

I don't think so, since it is working on other distros, I don't expect it to cause issues on Alpine only.

I tried to reproduce this on Fedora with the `mcr.microsoft.com/dotnet/sdk:8.0-alpine` image.

I built the `while (true) { Console.WriteLine(Console.ReadLine()); }` app in the image.

When I run the app, characters get echoed as I type, and using backspace removes them.

I tried to reproduce it with the `mcr.microsoft.com/dotnet/sdk:6.0-alpine` image, and that also works for me.

@RdJNL can you still reproduce this?

**Comment by RdJNL** [comment] 2023-11-17 20:06
@tmds I've just tested this with .NET 6 and 8 and unfortunately I'm still able to reproduce the issue with both when I'm using the dockerfile I posted.

However when I start an sdk:8.0-alpine image and build and run the app there, it works as intended. So potentially there's a difference between the sdk:8.0-alpine and runtime:8.0-alpine images. Could you try using the dockerfile I posted and see if you can reproduce the issue?

I'm on Windows 11 x64, tested using both CMD and PowerShell through their own terminal and through Windows Terminal.

**Comment by tmds** [comment] 2023-11-20 08:31
> However when I start an sdk:8.0-alpine image and build and run the app there, it works as intended. So potentially there's a difference between the sdk:8.0-alpine and runtime:8.0-alpine images.

Aha!

From [sdk/8.0/alpine3.18/amd64/Dockerfile](https://github.com/dotnet/dotnet-docker/blob/dbad8de557e0f943fe5103f9c165ac3300832d97/src/sdk/8.0/alpine3.18/amd64/Dockerfile#L50-L51):

```
    # Add ncurses-terminfo-base to resolve psreadline dependency
    && apk add --no-cache ncurses-terminfo-base
```

This adds the terminfo database that is required to make backspace work.

To fix this, `ncurses-terminfo-base` should be added to the `runtime-deps` base image.

@adamsitnik can we move this issue there, or should we create a new one?

**Comment by adamsitnik** [comment] 2023-11-20 08:55
@tmds @RdJNL thank you both for your help! I've created https://github.com/dotnet/dotnet-docker/issues/5016, I am going to close this issue as it's not actionable in dotnet/runtime. Thanks!

**Closed by adamsitnik** 2023-11-20 08:55 UTC
Labels: area-System.Console, needs-further-triage
