### ISSUE TITLE
Expression.Bind parameter validation is incorrect.

### ISSUE THREAD

**Issue by Pentadome** [dotnet/runtime#82850] opened 2023-03-01 19:37 UTC
### Description

[This is the Expression.Bind method](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq.Expressions/src/System/Linq/Expressions/MemberAssignment.cs#L59)

The problem lies here:
```csharp
if (!memberType.IsAssignableFrom(expression.Type))
{
    throw Error.ArgumentTypesMustMatch();
}
```
This validation is incomplete. It fails if the types are not equal at all. [This is also true according to the documentation.](https://learn.microsoft.com/en-us/dotnet/api/system.linq.expressions.expression.memberinit?view=net-7.0#system-linq-expressions-expression-memberinit(system-linq-expressions-newexpression-system-collections-generic-ienumerable((system-linq-expressions-memberbinding))))

### Reproduction Steps

```csharp
public class Foo
{
  public object Value { get; set; }
}

var newExpr = Expression.New(typeof(Foo));
var valueBindExpr = Expression.Bind(typeof(Foo).GetProperty("Value"), Expression.Contant(1));
var objectInitExpr = Expression.MemberInit(newExpr, valueBindExpr);
Expression.Lambda<Func<Foo>>(objectInitExpr, null).Compile() // throws System.InvalidProgramException: Common Language Runtime detected an invalid program.
```

### Expected behavior

`Expression.Bind` to throw when `memberType` is not equal to `expression.Type`.

### Actual behavior

`Expression.Bind` does not validate its arguments correctly. Instead `LambaExpression.Compile` throws `System.InvalidProgramException: Common Language Runtime detected an invalid program.`

Making it very hard to debug the problem.

### Known Workarounds

Convert the value to the property's type first.

```csharp
var property = typeof(Foo).GetProperty("Value");
var valueBindExpr = Expression.Bind(property, Expression.Convert( Expression.Contant(1), property.PropertyType));
```

Maybe this should be default behavior?

**Comment by Pentadome** [comment] 2023-03-27 07:09
@jaredpar I noticed `System.Linq.Expression` is "archived"? So this will not be changed then?

**Comment by cston** [comment] 2024-07-30 18:20
@Pentadome, thanks for reporting this issue.

The current behavior appears to be consistent with .NET Framework 4.7.2 which also fails in this case, although with .NET Framework, the failure is when calling the resulting delegate, rather than in `Compile()`.

Closing since System.Linq.Expressions is effectively archived, see [README.md](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq.Expressions/README.md), and since this does not appear to be a regression.

**Closed by cston** 2024-07-30 18:20 UTC
Labels: area-System.Linq.Expressions, untriaged
