### ISSUE TITLE
System.Text.Json.JsonSerializerOptions.GetJsonTypeInfoFromContextOrCreate(Type) assert causing test failures

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#66672] opened 2022-03-15 18:04 UTC
The assert at https://github.com/dotnet/runtime/blob/ba5a5820fd1803f96713530dc1701888f846a93a/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs#L613
is causing multiple test failures in the System.Text.Json and System.Net.Json test suites.

Helix query:
https://runfo.azurewebsites.net/search/helix-logs/?bq=started%3A~3%20definition%3Aruntime%20result%3A!succeeded&lq=started%3A~7%20logkind%3Aconsole%20text%3A%22system.text.json.jsonserializeroptions.getjsontypeinfofromcontextorcreate%22&pagenumber=1

**Comment by eiriktsarpalis** [comment] 2022-03-16 13:01
Duplicate of #66469.

**Closed by eiriktsarpalis** 2022-03-16 13:01 UTC
Labels: area-System.Text.Json, blocking-clean-ci, untriaged
