### ISSUE TITLE
Exception at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing)

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#106486] opened 2024-08-15 17:31 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=776854
Build error leg or test failing: System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest
Pull request: https://github.com/dotnet/runtime/pull/106455

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing)",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=776854
**Error message validated:** `[at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing)`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 8/15/2024 5:31:44 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[779476](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779476)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779476&view=ms.vss-test-web.build-test-results-tab&runId=19977230&resultId=214257)|dotnet/runtime#106573|
|[779460](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779460)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779460&view=ms.vss-test-web.build-test-results-tab&runId=19977112&resultId=200269)|dotnet/runtime#106572|
|[779394](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779394)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779394&view=ms.vss-test-web.build-test-results-tab&runId=19974400&resultId=192734)|dotnet/runtime#106583|
|[779393](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779393)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779393&view=ms.vss-test-web.build-test-results-tab&runId=19974050&resultId=221478)||
|[779387](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779387)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779387&view=ms.vss-test-web.build-test-results-tab&runId=19973834&resultId=214286)|dotnet/runtime#106575|
|[779313](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779313)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779313&view=ms.vss-test-web.build-test-results-tab&runId=19971202&resultId=214261)|dotnet/runtime#106578|
|[779281](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779281)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779281&view=ms.vss-test-web.build-test-results-tab&runId=19969832&resultId=195243)||
|[779216](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779216)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779216&view=ms.vss-test-web.build-test-results-tab&runId=19967852&resultId=202708)|dotnet/runtime#106574|
|[779198](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779198)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779198&view=ms.vss-test-web.build-test-results-tab&runId=19966718&resultId=213504)|dotnet/runtime#106503|
|[779138](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779138)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779138&view=ms.vss-test-web.build-test-results-tab&runId=19965944&resultId=214261)|dotnet/runtime#106572|
|[779167](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779167)|dotnet/runtime|[System.Security.Cryptography.X509Certificates.Tests.PfxIterationCountTests_X509Certificate2.Import_IterationCountLimitExceeded_ThrowsInAllottedTime](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779167&view=ms.vss-test-web.build-test-results-tab&runId=19965952&resultId=201911)|dotnet/runtime#80154|
|[779102](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779102)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779102&view=ms.vss-test-web.build-test-results-tab&runId=19965836&resultId=195598)|dotnet/runtime#106571|
|[779006](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779006)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779006&view=ms.vss-test-web.build-test-results-tab&runId=19960582&resultId=202158)|dotnet/runtime#106329|
|[778946](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778946)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778946&view=ms.vss-test-web.build-test-results-tab&runId=19958810&resultId=213968)|dotnet/runtime#106569|
|[778929](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778929)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778929&view=ms.vss-test-web.build-test-results-tab&runId=19958234&resultId=202710)|dotnet/runtime#106568|
|[778894](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778894)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778894&view=ms.vss-test-web.build-test-results-tab&runId=19957414&resultId=214259)|dotnet/runtime#106567|
|[778861](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778861)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778861&view=ms.vss-test-web.build-test-results-tab&runId=19956824&resultId=213995)|dotnet/runtime#106509|
|[778785](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778785)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778785&view=ms.vss-test-web.build-test-results-tab&runId=19955992&resultId=195598)|dotnet/runtime#106548|
|[778751](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778751)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778751&view=ms.vss-test-web.build-test-results-tab&runId=19953920&resultId=197555)|dotnet/runtime#106555|
|[778694](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778694)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778694&view=ms.vss-test-web.build-test-results-tab&runId=19952132&resultId=189266)|dotnet/runtime#106562|
|[778635](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778635)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778635&view=ms.vss-test-web.build-test-results-tab&runId=19950696&resultId=214261)|dotnet/runtime#106424|
|[778648](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778648)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.FileStreamFlushAsyncThreadPoolDeadlockTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778648&view=ms.vss-test-web.build-test-results-tab&runId=19948678&resultId=179387)||
|[778590](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778590)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778590&view=ms.vss-test-web.build-test-results-tab&runId=19947894&resultId=208321)|dotnet/runtime#106413|
|[778518](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778518)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778518&view=ms.vss-test-web.build-test-results-tab&runId=19947756&resultId=214261)|dotnet/runtime#106554|
|[778488](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778488)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778488&view=ms.vss-test-web.build-test-results-tab&runId=19945346&resultId=219822)||
|[778456](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778456)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778456&view=ms.vss-test-web.build-test-results-tab&runId=19944504&resultId=189404)||
|[778321](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778321)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778321&view=ms.vss-test-web.build-test-results-tab&runId=19940444&resultId=200269)|dotnet/runtime#106498|
|[778160](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778160)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778160&view=ms.vss-test-web.build-test-results-tab&runId=19936374&resultId=194432)|dotnet/runtime#106532|
|[2517152](https://dev.azure.com/dnceng/internal/_build/results?buildId=2517152)|dotnet-runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng//internal/_build/results?buildId=2517152&view=ms.vss-test-web.build-test-results-tab&runId=54037911&resultId=178438)||
|[778154](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778154)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778154&view=ms.vss-test-web.build-test-results-tab&runId=19935752&resultId=194079)|dotnet/runtime#106533|
|[778128](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778128)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778128&view=ms.vss-test-web.build-test-results-tab&runId=19935390&resultId=200157)|dotnet/runtime#106454|
|[778002](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778002)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778002&view=ms.vss-test-web.build-test-results-tab&runId=19928632&resultId=214024)|dotnet/runtime#106403|
|[777947](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777947)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777947&view=ms.vss-test-web.build-test-results-tab&runId=19927392&resultId=214261)|dotnet/runtime#106451|
|[777913](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777913)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777913&view=ms.vss-test-web.build-test-results-tab&runId=19926202&resultId=221997)||
|[777809](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777809)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777809&view=ms.vss-test-web.build-test-results-tab&runId=19921874&resultId=208321)|dotnet/runtime#106525|
|[777757](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777757)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777757&view=ms.vss-test-web.build-test-results-tab&runId=19918634&resultId=195594)|dotnet/runtime#106520|
|[777739](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777739)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777739&view=ms.vss-test-web.build-test-results-tab&runId=19918386&resultId=200389)||
|[777732](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777732)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777732&view=ms.vss-test-web.build-test-results-tab&runId=19918046&resultId=213914)|dotnet/runtime#103317|
|[777687](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777687)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777687&view=ms.vss-test-web.build-test-results-tab&runId=19916906&resultId=200267)|dotnet/runtime#80154|
|[777681](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777681)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777681&view=ms.vss-test-web.build-test-results-tab&runId=19916908&resultId=195594)||
|[777661](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777661)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777661&view=ms.vss-test-web.build-test-results-tab&runId=19915616&resultId=206419)|dotnet/runtime#106483|
|[777538](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777538)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777538&view=ms.vss-test-web.build-test-results-tab&runId=19911760&resultId=195594)|dotnet/runtime#106500|
|[777317](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777317)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777317&view=ms.vss-test-web.build-test-results-tab&runId=19905902&resultId=194917)||
|[777063](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777063)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777063&view=ms.vss-test-web.build-test-results-tab&runId=19897004&resultId=213889)|dotnet/runtime#106329|
|[776854](https://dev.azure.com/dnceng-public/public/_build/results?buildId=776854)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=776854&view=ms.vss-test-web.build-test-results-tab&runId=19891752&resultId=213889)|dotnet/runtime#106455|
|[776821](https://dev.azure.com/dnceng-public/public/_build/results?buildId=776821)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=776821&view=ms.vss-test-web.build-test-results-tab&runId=19890172&resultId=191921)|dotnet/runtime#106453|
|[776509](https://dev.azure.com/dnceng-public/public/_build/results?buildId=776509)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=776509&view=ms.vss-test-web.build-test-results-tab&runId=19874076&resultId=213887)|dotnet/runtime#106432|
|[776432](https://dev.azure.com/dnceng-public/public/_build/results?buildId=776432)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=776432&view=ms.vss-test-web.build-test-results-tab&runId=19872832&resultId=195594)|dotnet/runtime#106429|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|9|48|48|

**Comment by jkotas** [comment] 2024-08-18 16:29
Duplicate of #106494

**Closed by jkotas** 2024-08-18 16:29 UTC
Labels: area-Infrastructure-libraries, blocking-clean-ci, untriaged, Known Build Error

**Comment by lewing** [comment] 2024-08-18 19:05
> Duplicate of #106494

I think you mean that is a duplicate of this ;)

**Comment by jkotas** [comment] 2024-08-18 19:37
We had 3 issues opened on the same failure. I have picked the one with the most specific title and the best matching pattern as the winner, and resolved the other two as dups.

**Comment by lewing** [comment] 2024-08-19 00:33
> We had 3 issues opened on the same failure. I have picked the one with the most specific title and the best matching pattern as the winner, and resolved the other two as dups.

I meant it as a light hearted "hey but I was first" but after a little more consideration it would actually be nice if build analysis also tracked issues that were matching on the same failure and marked them for further review
