### ISSUE TITLE
[ZlibStream] ArgumentOutOfRangeException when passing in compression levels past level 3 (cast from manual enum defining all of the native compression levels).

### ISSUE THREAD

**Issue by AraHaan** [dotnet/runtime#58742] opened 2021-09-07 08:28 UTC
### Description

I wanted to pass in the native zlib compression levels (raw 0~9) onto the Native zlib that used by DeflateStream in my code. However doing such results in an ArgumentOutOfRangeException when I explicitly cast my enum down to the one that DeflateStream expects (which are the proper values that are supported in the native zlib implementation).

[This branch on my zlib repository](https://github.com/Elskom/zlib.managed/tree/add-tests-and-fix-adler32) should be a minimal reproducible code sample, also the steps to run it are ``dotnet test`` (implies build). The problem lies on [this constructor](https://github.com/Elskom/zlib.managed/blob/add-tests-and-fix-adler32/src/zlib.managed/zlib.managed/ZlibStream.cs#L53-L60).

### Configuration

.NET: 6.0.100-rc.1.21417.19
OS: MacOS v12 Beta
Arch: x64
I do not think it's specific to this configuration.

### Regression?

I have no clue, I just expected that the cast from my enum to the CompressionLevel enum would be ok since the native zlib implementation has those levels implemented already (for zlib it should check to see if compression level is less than -1 or greater than 9).

But then again perhaps there should be a version of DeflateStream that accepts int for compression levels instead for those who directly want to pass specific compression levels directly to the native implementation through that stream (if they want to avoid the CompressionLevel enum).

**Comment by filipnavara** [comment] 2021-09-07 08:49
That won't work (by design). The enumeration is converted into the native values and it's not a simple cast:
https://github.com/dotnet/runtime/blob/6cb0e80fe6f4c13a8e7d3a1b43d8fe6ea9ffc344/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/Deflater.cs#L37-L63

**Comment by AraHaan** [comment] 2021-09-07 09:28
Actually I think that default case should be changed to:

```cs
     default: 
         zlibCompressionLevel = (ZLibNative.CompressionLevel)compressionLevel; 
         memLevel = ZLibNative.Deflate_DefaultMemLevel; 
         break;
```
As most people like me want to use compression levels between the ones that are provided and so they expect to be able to cast it to ``CompressionLevel``. I feel like that should not break anything at all really.

**Comment by filipnavara** [comment] 2021-09-07 09:31
> Actually I think that default case should be changed to

That would not work. The values of the enum overlap with the values of the native compression levels.

**Comment by AraHaan** [comment] 2021-09-07 09:32
Well there should be some way to allow one to use all of the compression levels that the native one supports.

**Comment by filipnavara** [comment] 2021-09-07 09:36
There's not even a guarantee that all native values are supported or that the native zlib is used. In fact, it was not used in early .NET Framework versions and it's probably still not used for Browser implementation (https://github.com/dotnet/runtime/tree/main/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateManaged). For most platforms .NET actually uses a modified Intel Zlib fork and not the original library.

I don't necessarily see a use case for supporting more compression levels but if that was to be done it would have to be a new API that explicitly accepts the 0-9 `int` value.

**Comment by AraHaan** [comment] 2021-09-07 09:51
Also note that their ZlibStream inflater is broken: <img width="908" alt="image" src="https://user-images.githubusercontent.com/15173749/132324394-8c96c878-d715-404e-a358-00188503e824.png">

**Comment by FiniteReality** [comment] 2021-09-07 14:38
> > Actually I think that default case should be changed to
> 
> That would not work. The [values of the enum](https://github.com/dotnet/runtime/blob/6cb0e80fe6f4c13a8e7d3a1b43d8fe6ea9ffc344/src/libraries/System.IO.Compression/src/System/IO/Compression/CompressionLevel.cs#L12-L33) overlap with the values of the native compression levels.

A trick used by some other APIs is to map the *known* values to negative numbers, and then allow somebody to pass a positive value which gets mapped as-is. Since CompressionLevel already uses positive numbers, the opposite could instead be done: negative numbers would get mapped to their absolute value.

Personally, though, I think the best solution would be to expose a ZLibEncoder/Decoder (see [this API request comment](https://github.com/dotnet/runtime/issues/39327#issuecomment-658871313) for inspiration) which takes the encoder/decoder-specific options, and leave the Stream types to take CompressionLevel. After all, new applications should (IMO) be using [pipelines](https://docs.microsoft.com/en-us/dotnet/standard/io/pipelines) which can be wrapped as streams when interfacing with older software.

**Comment by AraHaan** [comment] 2021-09-07 18:54
But what if one wants to construct those streams using an int value for compression levels?

**Comment by FiniteReality** [comment] 2021-09-07 20:14
> But what if one wants to construct those streams using an int value for compression levels?

You don't.

**Comment by stephentoub** [comment] 2021-09-08 14:08
Closing as a dup of https://github.com/dotnet/runtime/issues/42820

**Closed by stephentoub** 2021-09-08 14:08 UTC
Labels: area-System.IO.Compression, untriaged
