### ISSUE TITLE
Test failure GC\\Scenarios\\MinLeakGen\\minleakgen\\minleakgen.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#65354] opened 2022-02-15 01:46 UTC
Run: [runtime-coreclr r2r-extra 20220213.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1610717&view=ms.vss-test-web.build-test-results-tab&runId=44869536&paneView=debug&resultId=108490)

Failed test:
```
R2R windows x64 Checked forcerelocs @ Windows.10.Amd64.Open

- GC\\Scenarios\\MinLeakGen\\minleakgen\\minleakgen.cmd
- GC\\API\\WeakReference\\Finalize\\Finalize.cmd
- GC\\Scenarios\\FinalizeTimeout\\FinalizeTimeout\\FinalizeTimeout.cmd
- GC\\API\\GCHandle\\Free\\Free.cmd
- GC\\API\\GCHandle\\Target\\Target.cmd
- GC\\Scenarios\\LeakWheel\\leakwheel\\leakwheel.cmd
- GC\\Scenarios\\StringCreator\\stringcreator\\stringcreator.cmd
- GC\\Scenarios\\BinTree\\thdtreegrowingobj\\thdtreegrowingobj.cmd
- GC\\Regressions\\Github\\runtime_32848\\runtime_32848\\runtime_32848.cmd
- GC\\Scenarios\\LeakGen\\leakgenthrd\\leakgenthrd.cmd
- GC\\Features\\Finalizer\\finalizeother\\finalizearray\\finalizearray.cmd
- GC\\Features\\KeepAlive\\keepaliveother\\keepalivedirectedgraph\\keepalivedirectedgraph.cmd
- GC\\Scenarios\\FinalNStruct\\finalnstruct\\finalnstruct.cmd
- GC\\API\\GC\\GetGeneration\\GetGeneration.cmd
- GC\\Regressions\\v2.0-beta2\\471729\\471729\\471729.cmd
- CoreMangLib\\system\\enum\\EnumIConvertibleToUint64\\EnumIConvertibleToUint64.cmd
- GC\\API\\GC\\TotalMemory2\\TotalMemory2.cmd
- GC\\Scenarios\\Boxing\\gcvariant\\gcvariant.cmd
- GC\\Regressions\\**
- GC\\API\\GC\\**
- GC\\Scenarios\\**
```
**Error message:**
```
Could Not Find C:\h\w\A1CD0888\w\B7EA0A2F\e\GC\Scenarios\MinLeakGen\minleakgen\IL-CG2\composite-r2r.dll
Could Not Find C:\h\w\A1CD0888\w\B7EA0A2F\e\GC\Scenarios\MinLeakGen\minleakgen\minleakgen.dll.rsp
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'ILCompiler.DependencyAnalysisFramework, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'. The module was expected to contain an assembly manifest.
File name: 'ILCompiler.DependencyAnalysisFramework, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'
at ILCompiler.ReadyToRunCodegenCompilationBuilder.ToCompilation()
at ILCompiler.Program.RunSingleCompilation(Dictionary2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary2 unrootedInputFilePaths, HashSet`1 versionBubbleModulesHash, CompilerTypeSystemContext typeSystemContext)
at ILCompiler.Program.Run(String[] args)
at ILCompiler.Program.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\A1CD0888\w\B7EA0A2F\uploads\Reports\GC.Scenarios\MinLeakGen\minleakgen\minleakgen.output.txt
Raw output:
BEGIN EXECUTION
minleakgen.dll
1 file(s) copied.
Response file: C:\h\w\A1CD0888\w\B7EA0A2F\e\GC\Scenarios\MinLeakGen\minleakgen\minleakgen.dll.rsp
C:\h\w\A1CD0888\w\B7EA0A2F\e\GC\Scenarios\MinLeakGen\minleakgen\IL-CG2\minleakgen.dll
-o:C:\h\w\A1CD0888\w\B7EA0A2F\e\GC\Scenarios\MinLeakGen\minleakgen\minleakgen.dll
--targetarch:x64
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\A1CD0888\p\System..dll
-r:C:\h\w\A1CD0888\p\Microsoft..dll
-r:C:\h\w\A1CD0888\p\mscorlib.dll
-r:C:\h\w\A1CD0888\p\netstandard.dll
-O
" "dotnet" "C:\h\w\A1CD0888\p\crossgen2\crossgen2.dll" @"C:\h\w\A1CD0888\w\B7EA0A2F\e\GC\Scenarios\MinLeakGen\minleakgen\minleakgen.dll.rsp"   -r:C:\h\w\A1CD0888\w\B7EA0A2F\e\GC\Scenarios\MinLeakGen\minleakgen\IL-CG2*.dll"
Crossgen2 failed with exitcode - -532462766
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\A1CD0888\p
C:\h\w\A1CD0888\w\B7EA0A2F\e\GC\Scenarios\MinLeakGen\minleakgen\minleakgen.cmd
Expected: True
Actual:   False


Stack trace
   at GC_Scenarios._MinLeakGen_minleakgen_minleakgen_._MinLeakGen_minleakgen_minleakgen_cmd()
```

**Comment by trylek** [comment] 2022-04-04 20:32
Closing as duplicate of: https://github.com/dotnet/runtime/issues/65646

**Closed by trylek** 2022-04-04 20:32 UTC
Labels: area-crossgen2-coreclr, untriaged
