### ISSUE TITLE
Mono does not align Int128 types on correct boundaries when p/invoking or passing pointers to them to unmanaged code

### ISSUE THREAD

**Issue by davidwrighton** [dotnet/runtime#74223] opened 2022-08-19 07:45 UTC
### Description

Mono does not align Int128 types on correct boundaries when p/invoking or passing pointers to them to unmanaged code. 

As of PR #74123 the layout of Int128 in CoreCLR and NativeAOT will match the native platform Int128 types.

### Reproduction Steps

Enable the `$(XunitTestBinBase)/Interop/PInvoke/Int128/Int128TestFieldLayout` test and run it.

### Expected behavior

Test should pass

### Actual behavior

Test fails

### Regression?

No, Int128 is a new type for .NET 7

### Known Workarounds

Architecture specific tricks to align them correctly.

**Comment by lambdageek** [comment] 2022-08-24 16:14
Dupe of https://github.com/dotnet/runtime/issues/69399

**Closed** 2023-07-24 15:26 UTC
Labels: area-Interop-mono
