### ISSUE TITLE
BufferBlock<T>.Completion never completes in specific scenario

### ISSUE THREAD

**Issue by theodorzoulias** [dotnet/runtime#60768] opened 2021-10-22 15:12 UTC
Hi! While I was writing some library code, I created a small TPL Dataflow pipeline consisting of two blocks, with the completion of the first block not propagated properly to the second block. Here is a minimal example that reproduces this strange behavior:

```C#
using System;
using System.Threading;
using System.Threading.Tasks;
using System.Threading.Tasks.Dataflow;

static class Program
{
    static async Task Main()
    {
        var block1 = new BufferBlock<int>();
        var block2 = new BufferBlock<int>();
        block1.LinkTo(block2, new() { PropagateCompletion = true });
        block1.Post(1);
        block1.Complete();
        await block1.Completion;
        block2.TryReceiveAll(out var items);
        bool completed = block2.Completion.Wait(500);
        Console.WriteLine($"block2 completed in time: {completed}");
    }
}
```

Output:

```none
block2 completed in time: False
```

[Try it on Fiddle](https://dotnetfiddle.net/AFuE5s).

The expected behavior would be for the `block2` to complete immediately, since the `block1` has already completed, the two blocks are linked together with the `PropagateCompletion = true` option, and the `block2` has emitted all the messages it contains. However the `block2` never completes in this scenario. Calling `block2.Completion.Wait()` blocks indefinitely.

Switching from `BufferBlock` to `TransformBlock` for any of the two blocks makes no difference, the issue remains.

There are several subtle changes that prevent this behavior from happening.

1. Adding a `Thread.Sleep(100)` after the `block1.Complete()` solves the problem.
2. Waiting the `block1` synchronously (`block1.Completion.Wait()`) also solves the problem.
3. Waiting the `block2` asynchronously (`await block2.Completion`) solves the problem as well.
4. Completing the `block2` manually (`block2.Complete()`) before waiting its completion, also fixes the problem.

My guess is that some sort of race condition is taking place in this specific scenario.

**Comment by theodorzoulias** [comment] 2021-10-24 00:46
For context, I encountered this behavior while evaluating alternative implementations for an extension method `ToListAsync` for source dataflow blocks:

```C#
/// <summary> Creates a list containing the messages consumed asynchronously
/// from a source dataflow block. </summary>
public static Task<IList<T>> ToListAsync<T>(this IReceivableSourceBlock<T> block)
{
    var buffer = new BufferBlock<T>();
    block.LinkTo(buffer, new() { PropagateCompletion = true });
    return block.Completion.ContinueWith(t =>
    {
        if (t.IsFaulted)
        {
            var tcs = new TaskCompletionSource<IList<T>>();
            tcs.SetException(t.Exception.InnerExceptions);
            return tcs.Task;
        }
        if (t.IsCanceled) t.GetAwaiter().GetResult();
        if (!buffer.TryReceiveAll(out var results)) results = new T[0];
        Debug.Assert(buffer.Completion.Wait(1000)); // Assert that the buffer is empty
        return Task.FromResult(results);
    }, default, TaskContinuationOptions.DenyChildAttach, TaskScheduler.Default).Unwrap();
}
```

I added a `buffer.Completion.Wait(1000)` in a debugging assertion, in order to ensure that all messages have been consumed. This `Debug.Assert` causes the method to deadlock in debug mode. Adding a `block.Complete()` before the `Wait` solved the problem, alas in a not satisfying way. It seems like I am balancing in the edge of race conditions here.

**Comment by theodorzoulias** [comment] 2021-10-24 00:59
@pedoc thanks for the feedback, but I am aware of this workaround. I mentioned it in the bullet #3 of my initial post.

**Comment by pedoc** [comment] 2021-10-24 01:13
yep,Mixing asynchronous and synchronous is not recommended, and some unexpected situations may occur.

It is recommended to take a look at this repo: ```https://github.com/microsoft/vs-threading```, use ```JoinableTaskFactory``` among them to synchronize your asynchronous methods and try to avoid deadlocks.

**Comment by theodorzoulias** [comment] 2021-10-24 01:26
@pedoc could you share an example showing how a `JoinableTaskFactory` could be used in order to solve this specific issue? I added the Microsoft.VisualStudio.Threading package in this fiddle [here](https://dotnetfiddle.net/PTChhp).

**Comment by pedoc** [comment] 2021-10-24 02:05
If you want to use JoinableTaskFactory, all asynchronous calls should be replaced (including await and .Wait()), short code:
```
using System;
using System.Threading;
using System.Threading.Tasks;
using System.Threading.Tasks.Dataflow;
using Microsoft.VisualStudio.Threading;

static class Program
{
    static async Task Main()
    {   
		var joinableTaskContext = new JoinableTaskContext();//only sample,maybe it should be wrapperd 
        var block1 = new BufferBlock<int>();
        var block2 = new BufferBlock<int>();
        block1.LinkTo(block2, new() { PropagateCompletion = true });
        block1.Post(1);
        block1.Complete();
        //Thread.Sleep(100);
        //await block1.Completion;
		joinableTaskContext.Run(() => block1.Completion);

        block2.TryReceiveAll(out var items);
        //await block2.Completion;
		joinableTaskContext.Run(() => block2.Completion);

		bool completed = block2.Completion.IsCompleted;
        Console.WriteLine($"block2 completed in time: {completed}");
    }
}
```
Output
```
block2 completed in time: True
```

BTW,In order to solve this problem, the cost of introducing a library is not worth it.

But there are a few problems for this:
1. Since the first block can use await, why not continue to use the second block? 
2. If you want to use .Wait() in the second block, why not use .Wait() in the first block? 


That is, as long as you maintain the same usage pattern, instead of mixing synchronous and asynchronous, it will work as expected.

**Comment by svick** [comment] 2021-11-03 08:33
@mayorovp and @pedoc are right: this is a deadlock caused by combining `await` with synchronous `Wait()`.

Specifically, it happens because of this part in the TPL Dataflow code:

https://github.com/dotnet/runtime/blob/6527f540e4b50bc84eb72705f80d3f2bdd57473b/src/libraries/System.Threading.Tasks.Dataflow/src/Internal/SourceCore.cs#L962-L968

The problem is that `_completionTask.TrySetResult` executes its continuations synchronously, which means it directly invokes the part of `Main` after `await block1.Completion;`. But that blocks waiting for `block2.Completion`, which means `_targetRegistry.PropagateCompletion()` is never called, which means `block2.Completion` is not completed, leading to a deadlock.

One resolution would be to say that it's the user's fault for combining async and sync code in this way and close this issue.
Another possible resolution would be to use `RunContinuationsAsynchronously` on the `_completionTask`, which sacrifices some performance to prevent this deadlock. I think this is the way to go, so I have opened https://github.com/dotnet/runtime/pull/61140.

**Comment by theodorzoulias** [comment] 2021-11-03 12:38
Thanks @svick. Your reply encourages me to report another deadlocking behavior in TPL Dataflow that I've encountered recently. I may do it later. A good library should be able to survive even when it's stressed to its limits IMHO. 😃

**Comment by theodorzoulias** [comment] 2021-11-08 16:43
@svick [that's](https://github.com/dotnet/runtime/issues/61318) what I was talking about. It's a deadlocking behavior that it's probably unrelated to the async/sync scenario of this issue.

**Closed** 2023-01-26 21:55 UTC
Labels: area-System.Threading.Tasks, in-pr
