### ISSUE TITLE
IndexOf result

### ISSUE THREAD

**Issue by zhoujit** [dotnet/runtime#47077] opened 2021-01-16 08:34 UTC
int idx3 = "a\r\nb".IndexOf("\n");

Above statement returns -1.

OS: Ubuntu/WSL2
Version: .NET 5

**Comment by huoyaoyuan** [comment] 2021-01-16 09:16
Duplicate of #43736

**Comment by jeffschwMSFT** [comment] 2021-01-16 16:56
Closing per #43736

**Closed by jeffschwMSFT** 2021-01-16 16:56 UTC
Labels: untriaged
