### ISSUE TITLE
How to resolve IL2026?

### ISSUE THREAD

**Issue by ygoe** [dotnet/runtime#80374] opened 2023-01-09 17:25 UTC
When I try to build my console application that uses JSON serialisation into a single trimmed executable with .NET 7.0, I get this warning at compile time:

> ...\JsonRpc.cs(254,20): warning IL2026: Using member 'System.Text.Json.JsonSerializer.Serialize<TValue>(TValue, JsonSerializerOptions)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. JSON serialization and deserialization might require types that cannot be statically analyzed. Use the overload that takes a JsonTypeInfo or JsonSerializerContext, or make sure all of the required types are preserved.

That part "make sure all of the required types are preserved" sounds plausible and I could surely identify the affected types. But I couldn't find any information about how to do that on the web. Is it possible to do that? How can this warning be resolved?

**Comment by krwq** [comment] 2023-01-09 17:54
Warning tells you that something might get incorrectly trimmed away because specific API can't guarantee trim safety.

Depending on the types you're serializing - I'd start with suppressing the warning (`[UnconditionalSuppressMessage("some justification")]` if you can update the code or disable the warning on the project level if you can't - you should open the issue against grpc repo if that's the case) and running the app with some payloads. 

If you see missing method/member exceptions that means something which should have stayed got trimmed away - you can make sure it's preserved by adding rd.xml file (search for that and you will find some examples).

If your classes are not super advanced it might just work without any issues. It really depends on the specific type you're serializing/deserializing.

**Comment by krwq** [comment] 2023-01-09 17:56
cc: @eerhardt

**Comment by eerhardt** [comment] 2023-01-09 17:58
The message tells you what to do:

> Use the overload that takes a JsonTypeInfo or JsonSerializerContext

If you want to do Json (de)serialization in a trimmed or NativeAOT app, you should use the JSON source generator: https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation

**Comment by ygoe** [comment] 2023-01-09 19:14
@eerhardt Following the example removes the warnings but then the code breaks which it didn't before. This is the exception in the middle of my program:

> Metadata for type 'System.Text.Json.JsonElement' was not provided by TypeInfoResolver of type 'Util.SourceGenerationContext'. If using source generation, ensure that all root types passed to the serializer have been indicated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically. The unsupported member type is located on type 'System.Object'. Path: $.Result.

My JSON message class looks like this:

```cs
public class JsonRpcMessage
{
	[JsonPropertyName("jsonrpc")]
	public string? JsonRpc { get; set; } = "2.0";

	[JsonPropertyName("id"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
	public long? Id { get; set; }

	[JsonPropertyName("method"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
	public string? Method { get; set; }

	[JsonPropertyName("params"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
	public Dictionary<string, object>? Params { get; set; }

	[JsonPropertyName("result"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
	public object? Result { get; set; }

	[JsonPropertyName("error"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
	public JsonRpcError? Error { get; set; }
}

public class JsonRpcError
{
	[JsonPropertyName("code")]
	public int? Code { get; set; }

	[JsonPropertyName("message")]
	public string? Message { get; set; }
}

/// <summary>
/// Utility class for JSON (de)serialization source generation.
/// </summary>
[JsonSourceGenerationOptions(WriteIndented = true)]
[JsonSerializable(typeof(JsonRpcMessage))]
internal partial class SourceGenerationContext : JsonSerializerContext
{
}
```

I cannot do anything about the `object`-type result property, it can really be anything. Does source generation fail in this situation? Why does the program work without it, despite the warnings?

**Comment by eerhardt** [comment] 2023-01-09 19:29
What happens when you add:

```C#
[JsonSerializable(typeof(JsonRpcMessage))]
[JsonSerializable(typeof(JsonElement))]  // add this
internal partial class SourceGenerationContext : JsonSerializerContext
```

**Comment by ygoe** [comment] 2023-01-09 20:00
Adding that line helps for now. And I wasn't even using `JsonElement`, how should I know that? Was it forgotten in the .NET library code?

**Comment by eerhardt** [comment] 2023-01-09 20:04
> And I wasn't even using JsonElement

I'd have to see all the code for your app, but my assumption is that when you are deserializing to `object`, and the JsonSerializer doesn't know which Type to use, it defaults to `JsonElement`. It says it in the message you pasted above:

> If using source generation, ensure that all root types passed to the serializer have been indicated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically. The unsupported member type is located on type 'System.Object'. Path: $.Result.

**Comment by ygoe** [comment] 2023-01-09 20:43
Yes, that's the result type, and the type of the params dictionary. This is JSON-RPC, it can transport anything. And I'm not sure what it will all be in the future. I'm only just laying the ground for the actual application to come.

Wouldn't `JsonElement` then be a good type to never remove from trimmed code so that the error wouldn't occur without me having to guess that it might be used by the method, even when I'm not using it? It's a bit intransparent if I'm expected to declare all my types and then have to do the job for the framework, too, because it doesn't.

**Comment by eiriktsarpalis** [comment] 2023-01-17 18:37
> Adding that line helps for now. And I wasn't even using `JsonElement`, how should I know that? Was it forgotten in the .NET library code?

That should not be necessary as long as your type graph does contain `object`, for example the following works as expected in trimmed .NET 7 apps:

```C#
JsonRpcMessage? result = JsonSerializer.Deserialize("""{ "result" : {} }""", SourceGenerationContext.Default.JsonRpcMessage);
Console.WriteLine(result?.Result is JsonElement); // True

public class JsonRpcMessage
{
    [JsonPropertyName("result"), JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public object? Result { get; set; }
}

[JsonSourceGenerationOptions(WriteIndented = true)]
[JsonSerializable(typeof(JsonRpcMessage))]
internal partial class SourceGenerationContext : JsonSerializerContext
{
}
```

So it might be that your code is doing something different?

**Comment by eiriktsarpalis** [comment] 2023-01-17 18:38
> > And I wasn't even using JsonElement
> 
> I'd have to see all the code for your app, but my assumption is that when you are deserializing to `object`, and the JsonSerializer doesn't know which Type to use, it defaults to `JsonElement`. It says it in the message you pasted above:

Specifying `JsonElement` explicitly should not be necessary, as the built-in converter for `object` types does reference `JsonElement` directly itself.

**Comment by ygoe** [comment] 2023-02-01 15:56
In the end, I dropped that source generator approach again. It just wasn't practical in any way. It requires me to explicitly declare each and every type that might possibly occur in the process. int, bool, Class1, Class2, SubClass3 etc. For a generic communication interface, this cannot be done. So I went back to the regular (reflection-based?) mechanism and disabled trimming. If trimming isn't supported in this scenario, then I'll have to scratch that from .NET's feature list and live with a 100 MB big executable file. (Even trimmed and with AOT it's still 35 MB for ASP.NET Core Web API.)

BTW, all types that occur in JSON serialisation are also used somewhere in the code. And if they weren't, I wouldn't mind them missing when reading or writing JSON. After all, I can only serialise what I use. So I really don't understand the warning reason here. Maybe .NET trimming needs a totally different approach here to be usable.

**Comment by eiriktsarpalis** [comment] 2023-02-02 14:42
> In the end, I dropped that source generator approach again. It just wasn't practical in any way. It requires me to explicitly declare each and every type that might possibly occur in the process. int, bool, Class1, Class2, SubClass3 etc. 

You should only need to explicitly declare the root type of the value you end up serializing. This is an essential trade-off when using the source generator over reflection and there's not much that can be done about it. 

That being said, this conversation seems to be suggesting that you ended up needing to annotate types contained in the root types. There might be an issue with your code or there might be a bug with the source generator that we're not aware of. However, we'd need some kind of reproduction in order to provide better guidance. Assuming you've decided to move on, I'm going to close this issue as resolved. Feel free to reopen or create a new issue should you decide to return to the issue.

**Closed by eiriktsarpalis** 2023-02-02 14:42 UTC
Labels: area-System.Text.Json, needs-further-triage
