### ISSUE TITLE
Microsoft.Win32.Registry is not working with .NET Standard library as a PowerShell Module

### ISSUE THREAD

**Issue by ranjit6168** [dotnet/runtime#33415] opened 2020-03-10 09:36 UTC
Hi,

I am creating PowerShell Module using .NET Standard 2.0, to support core as well as desktop edition.

I have a dependency on Microsoft.Win32.Registry which supports .NET standard.

However, I am getting the following error on PowerShell ISE but works in PowerShell core: 

Could not load file or assembly 'Microsoft.Win32.Registry, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file.

Following are the steps:

1.) Create a Powershell module using .NET Standard 2.0 in Visual Studio 2017.

2.) Get a NuGet package for Microsoft.Win32.Registry latest version 4.7.0.

3.) In the code, try to read the Registry, compile the code.

4.) Import the .dll as a Module in PowerShell ISE.

5.) Running the Cmdlet implemented in the Module gives the error mentioned above.

Following is the project with sample source which I used to reproduce the issue.

https://github.com/ranjit6168/RegistryIssue

**Comment by fMichaleczek** [comment] 2020-04-23 22:28
@ranjit6168 

Windows PowerShell doesn't support to load 2 versions of the same assembly and Microsoft.Win32.Registry is already loaded from the GAC

Open a Windows PowerShell console and test : 
```
PS> [Microsoft.Win32.Registry]::LocalMachine

Name                           Property
----                           --------

```

You should read this blog from the PS Team :
[Depending on the right PowerShell NuGet package in your .NET project](https://devblogs.microsoft.com/powershell/depending-on-the-right-powershell-nuget-package-in-your-net-project/)

You should use [powershell.standard package](https://docs.microsoft.com/en-us/powershell/scripting/developer/module/how-to-write-a-powershell-module-manifest) and read current issues [here](https://github.com/PowerShell/PowerShellStandard/issues)

My advice is to add a powershell module script (psm1) and manage the loading like that :
```
if ($PSVersionTable.PSVersion.Major -ge 6) {
	Add-Type -Path <YourDllForPowerShellCore>
}
```

@Anipik it's not a dotnet runtime issue and a duplicate of [#35623](https://github.com/dotnet/runtime/issues/35263) with another scenario

**Closed** 2020-04-24 01:13 UTC
Labels: area-Microsoft.Win32, untriaged
