### ISSUE TITLE
 System.IO.FileSystem.Watcher.Tests 

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/runtime#48933] opened 2021-03-02 01:51 UTC
I've been seeing cases where the FileWatcher tests use a closed handle and crash the WorkItem on macOS systems.

```
Unhandled exception. System.ObjectDisposedException: Safe handle has been closed.
Object name: 'SafeHandle'.
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success) in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/InteropServices/SafeHandle.cs:line 148
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success) in /_/src/coreclr/System.Private.CoreLib/src/System/StubHelpers.cs:line 1244
   at Interop.EventStream.FSEventStreamUnscheduleFromRunLoop(SafeEventStreamHandle streamRef, IntPtr runLoop, SafeCreateHandle runLoopMode)
   at System.IO.FileSystemWatcher.RunningInstance.StaticWatcherRunLoopManager.UnscheduleFromRunLoop(SafeEventStreamHandle eventStream) in /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs:line 224
   at System.IO.FileSystemWatcher.RunningInstance.CleanupEventStream() in /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs:line 280
   at System.IO.FileSystemWatcher.RunningInstance.FileSystemEventCallback(IntPtr streamRef, IntPtr clientCallBackInfo, IntPtr numEvents, Byte** eventPaths, FSEventStreamEventFlags* eventFlags, UInt64* eventIds) in /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs:line 356
```

Seen in: https://dev.azure.com/dnceng/public/_build/results?buildId=1016617&view=ms.vss-test-web.build-test-results-tab&runId=31645086&resultId=183971&paneView=debug

**Comment by danmoseley** [comment] 2021-03-02 02:03
Dupe of https://github.com/dotnet/runtime/issues/30056. @wfurt, do you plan to take a look at one of the dumps? I know it was not highest priority as it's failing only ~8 times a month.

**Closed by danmoseley** 2021-03-02 02:03 UTC
Labels: area-System.IO, untriaged

**Comment by wfurt** [comment] 2021-03-02 02:30
yes it is on TODO list but currently pretty deep down.
