### ISSUE TITLE
System.Text.Json: [JsonSourceGenerationOptions(DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)] fails with string type prop

### ISSUE THREAD

**Issue by Dorus** [dotnet/runtime#99202] opened 2024-03-03 07:30 UTC
### Description

Using the annotation `DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull` fails when type contains property `string type`. (Even on nested properties).

### Reproduction Steps

```C#
using System;
using System.Text.Json.Serialization;

namespace Test;

[JsonSourceGenerationOptions(DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(Testable))]
internal partial class MyContext : JsonSerializerContext
{
}

[Serializable]
public class Testable
{
  public string type { get; set; }
}
```

### Expected behavior

No errors

### Actual behavior

![afbeelding](https://github.com/dotnet/runtime/assets/4461459/dcd0d9a7-f323-49a2-ae20-6da2b9a27df1)

### Configuration

```Csproj
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.2" />
  </ItemGroup>
</Project>
```

**Comment by elgonzo** [comment] 2024-03-03 09:38
Duplicate of https://github.com/dotnet/runtime/issues/98050

**Closed** 2024-03-04 16:14 UTC
Labels: area-System.Text.Json, untriaged
