### ISSUE TITLE
Chrome Debugger Tests timeout

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#78599] opened 2022-11-19 18:03 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=88358
Build error leg or test failing: DebuggerTests.MiscTests.DebuggerTests.MiscTests.CheckCallStackOfAsyncGenericMethods
Pull request: https://github.com/dotnet/runtime/pull/78196

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section).

```json
{
  "ErrorMessage": "Timed out after 20s waiting for the browser to be ready: C:\helix\work\correlation\chrome-win\chrome.exe",
  "BuildRetry": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by radical** [comment] 2022-11-21 08:49
Closing as duplicate of https://github.com/dotnet/runtime/issues/76528 .

**Closed by radical** 2022-11-21 08:49 UTC
Labels: arch-wasm, blocking-clean-ci, untriaged, area-Debugger-mono, Known Build Error
