### ISSUE TITLE
ConfigurationBindingGenerator generates code that does not compile

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/runtime#98713] opened 2024-02-20 18:57 UTC
### Description

When using `ConfigurationBindingGenerator` with `JwtBearerOptions`, the generator generates this code:

```csharp
 if (configuration["Events"] is string value292)
 {
     instance.Events = value292;
 }
```

But the type of `JwtBearerOptions.Events` is `JwtBearerEvents`.

### Reproduction Steps

Create a simple console application.
Change the csproj to have:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
  </ItemGroup>

</Project>
```

Change `Program.cs` to:

```csharp
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.Extensions.DependencyInjection;

var serviceCollection = new ServiceCollection();

serviceCollection
    .AddOptions<AuthenticationOptions>()
    .BindConfiguration("Security:Authentication:AuthenticationOptions")
    ;

serviceCollection
    .AddOptions<JwtBearerOptions>("Bearer")
    .BindConfiguration("Security:Authentication:JwtBearerOptions")
    ;

var serviceProvider = serviceCollection.BuildServiceProvider();

Console.WriteLine("Hello, World!");
```

### Expected behavior

Correct binding code is generated.

### Actual behavior

Generated code does not compile.

### Configuration

.NET SDK 8.0.200

**Comment by tarekgh** [comment] 2024-02-20 19:14
This is a duplicate of https://github.com/dotnet/runtime/issues/95561.

**Closed by tarekgh** 2024-02-20 19:14 UTC
Labels: untriaged, area-Extensions-Configuration
