### ISSUE TITLE
System.Linq.Enumerable.TryGetNonEnumeratedCount<TSource> doesn't use IReadOnlyCollection<T>.Count 

### ISSUE THREAD

**Issue by ruoshili** [dotnet/runtime#98976] opened 2024-02-27 07:08 UTC
### Description

`System.Linq.Enumerable.TryGetNonEnumeratedCount<TSource>` extension method doesn't use `IReadOnlyCollection<T>.Count`. 

### Reproduction Steps

Using the following NUnit test.

```cs
public class EnumerableTest
{
        private class MockReadOnlyCollection<T> : IReadOnlyCollection<T>
        {
            public IEnumerator<T> GetEnumerator()
            {
                throw new InvalidOperationException();
            }

            IEnumerator IEnumerable.GetEnumerator()
            {
                return GetEnumerator();
            }

            public int Count => 1;
        }

        [Test]
        public void Test()
        {
            var readOnlyCollection = new MockReadOnlyCollection<int>();
            Assert.True(readOnlyCollection.TryGetNonEnumeratedCount(out var count));
            Assert.AreEqual(1, count);
        }
}
```

### Expected behavior

`System.Linq.Enumerable.TryGetNonEnumeratedCount<TSource>` extension method should use `IReadOnlyCollection<T>.Count`. 

### Actual behavior

`System.Linq.Enumerable.TryGetNonEnumeratedCount<TSource>` extension method doesn't use `IReadOnlyCollection<T>.Count`. 

### Known Workarounds

N/A

### Configuration

* Which version of .NET is the code running on? 
  * .NET | 6, 7, 8, 9
* What OS and version, and what distro if applicable?
  * All OS
* What is the architecture (x64, x86, ARM, ARM64)?
  * All architectures
* Do you know whether it is specific to that configuration?
  * No
* If you're using Blazor, which web browser(s) do you see this issue in?
  * N/A

### Other information

I posted a PR to fix it. https://github.com/dotnet/runtime/pull/98974

**Comment by huoyaoyuan** [comment] 2024-02-27 08:08
This is covered by #42254 and should not be changed alone.

**Comment by eiriktsarpalis** [comment] 2024-02-27 10:26
Duplicate of #61396.

**Closed by eiriktsarpalis** 2024-02-27 10:26 UTC
Labels: area-System.Linq, untriaged
