### ISSUE TITLE
Is it safe to ignore the sessionId on a process to detect it as service?

### ISSUE THREAD

**Issue by gillg** [dotnet/runtime#77350] opened 2022-10-23 08:53 UTC
Hi,

On the legacy method WindowsServiceHelpers.IsWindowsService() the logic is based on SessionID == 0 and parent process services.exe.
Using services.exe seems enough, or in the worst case a OR condition on SessionID 0 or 1, but I guess the session is a safety guard in case of a third party software with an exe named services.exe.

The problem is on a windows container, services.exe has a sessionId = 1 and Golang framework steal the logic from this legacy method. So we experience issues with some Golang softwares hosted in docker and compatibles as cli + service. (Otelcollector, Windows exporter, and any other not launched as host process).

Any advice from the Microsoft team ?

Original code here : https://github.com/dotnet/extensions/blob/f4066026ca06984b07e90e61a6390ac38152ba93/src/Hosting/WindowsServices/src/WindowsServiceHelpers.cs#L31
Some details here : https://github.com/golang/go/issues/56335#issuecomment-1287964605

**Comment by gillg** [comment] 2022-10-23 09:28
According to that command inside a container :
By the way, other interesting output from a host and container :
Host
```
> query session
 SESSIONNAME       USERNAME                 ID  STATE   TYPE        DEVICE
 services                                    0  Disc
>console           my.username            1  Active
```
Container
```
> query session
 SESSIONNAME       USERNAME                 ID  STATE   TYPE        DEVICE
>services                                    1  Disc
```
Maybe instead of a basic "OR" condition, we should identify the session name "services" instead of testing a session ID.
What de you think ?
What is the good way to retrieve a session name from a session ID ?

**Comment by jkotas** [comment] 2022-10-23 17:18
This is duplicate of https://github.com/dotnet/runtime/issues/52416 . 

SessionId is no longer checked in the current Microsoft.Extensions.Hosting.WindowsServices sources:
https://github.com/dotnet/runtime/blob/36bf84fc4a89209f4fdbc1fc201e81afd8be49b0/src/libraries/Microsoft.Extensions.Hosting.WindowsServices/src/WindowsServiceHelpers.cs#L32

**Closed by jkotas** 2022-10-23 17:18 UTC
Labels: untriaged, area-Extensions-Hosting

**Comment by gillg** [comment] 2022-10-23 18:00
Awesome! Thanks a lot for your fast answer. I will circle back with the Golang team.
