### ISSUE TITLE
System.IO.Compression.ZipFile.Tests Fails on iOS/tvOS

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#51378] opened 2021-04-16 15:00 UTC
System.IO.Compression.ZipFile.Tests
System.IO.Compression.Tests.ZipFile_ZipArchive_Create.CreateEntryFromFileExtension
System.IO.Compression.Tests.ZipFile_ZipArchive_Extract.ExtractToDirectoryExtension_Unicode
System.IO.Compression.Tests.ZipFile_ZipArchive_Extract.ExtractToDirectoryExtension
System.IO.Compression.Tests.ZipFile_ZipArchiveEntry_Extract.ExtractToFileExtension
System.IO.Compression.Tests.ZipFile_Extract.ExtractToDirectoryUnicode
System.IO.Compression.Tests.ZipFile_Extract.Unix_ZipWithInvalidFileNames_ThrowsArgumentException
System.IO.Compression.Tests.ZipFile_Extract.ExtractToDirectoryZipArchiveOverwrite
System.IO.Compression.Tests.ZipFile_Extract.ExtractToDirectoryNormal
System.IO.Compression.Tests.ZipFile_Extract.Unix_ZipWithOSSpecificFileNames
System.IO.Compression.Tests.ZipFile_Extract.ExtractToDirectoryOverwriteEncoding
System.IO.Compression.Tests.ZipFile_Extract.ExtractToDirectoryOverwrite
System.IO.Compression.Tests.ZipFile_Create.UpdateReadTwice
System.IO.Compression.Tests.ZipFile_Create.CreateFromDirectory_IncludeBaseDirectory
System.IO.Compression.Tests.ZipFile_Create.Unix_ZipWithInvalidFileNames_ThrowsArgumentException
System.IO.Compression.Tests.ZipFile_Create.CreateFromDirectoryUnicode
System.IO.Compression.Tests.ZipFile_Create.UnsupportedCompressionRoutine
System.IO.Compression.Tests.ZipFile_Create.InvalidDates
System.IO.Compression.Tests.ZipFile_Create.InvalidInstanceMethods
System.IO.Compression.Tests.ZipFile_Create.CreateFromDirectoryNormal
System.IO.Compression.Tests.ZipFile_Create.UpdateAddFile
System.IO.Compression.Tests.ZipFile_Create.InvalidFiles
System.IO.Compression.Tests.ZipFile_Create.ReadStreamOps

```
System.IO.Compression.ZipFile.Tests.dll   Failed: 35

Test collection for System.IO.Compression.Tests.ZipFile_ZipArchive_Create
System.IO.Compression.Tests.ZipFile_ZipArchive_Create.CreateEntryFromFileExtension(withCompressionLevel: True)
    System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/refzipfiles/normal.zip'.
System.IO.Compression.Tests.ZipFile_ZipArchive_Create.CreateEntryFromFileExtension(withCompressionLevel: False)
    System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/refzipfiles/normal.zip'.

Test collection for System.IO.Compression.Tests.ZipFile_ZipArchive_Extract
System.IO.Compression.Tests.ZipFile_ZipArchive_Extract.ExtractToDirectoryExtension_Unicode
    System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/refzipfiles/unicode.zip'.
System.IO.Compression.Tests.ZipFile_ZipArchive_Extract.ExtractToDirectoryExtension
    System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/refzipfiles/normal.zip'.

Test collection for System.IO.Compression.Tests.ZipFile_ZipArchiveEntry_Extract
System.IO.Compression.Tests.ZipFile_ZipArchiveEntry_Extract.ExtractToFileExtension
    System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/refzipfiles/normal.zip'.

Test collection for System.IO.Compression.Tests.ZipFile_Extract
System.IO.Compression.Tests.ZipFile_Extract.ExtractToDirectoryUnicode
    System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/refzipfiles/unicode.zip'.
System.IO.Compression.Tests.ZipFile_Extract.Unix_ZipWithInvalidFileNames_ThrowsArgumentException(zipName: \"NullCharFileName_FromUnix\")
    Assert.Throws() Failure\nExpected: typeof(System.ArgumentException)\nActual:   typeof(System.IO.DirectoryNotFoundException): Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/compat/NullCharFileName_FromUnix.zip'.\n---- System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/compat/NullCharFileName_FromUnix.zip'.
System.IO.Compression.Tests.ZipFile_Extract.Unix_ZipWithInvalidFileNames_ThrowsArgumentException(zipName: \"NullCharFileName_FromWindows\")
    Assert.Throws() Failure\nExpected: typeof(System.ArgumentException)\nActual:   typeof(System.IO.DirectoryNotFoundException): Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/compat/NullCharFileName_FromWindows.zip'.\n---- System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/compat/NullCharFileName_FromWindows.zip'.
System.IO.Compression.Tests.ZipFile_Extract.ExtractToDirectoryZipArchiveOverwrite
    System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/refzipfiles/normal.zip'.
System.IO.Compression.Tests.ZipFile_Extract.ExtractToDirectoryNormal(file: \"empty.zip\", folder: \"empty\")
    System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/refzipfiles/empty.zip'.
System.IO.Compression.Tests.ZipFile_Extract.ExtractToDirectoryNormal(file: \"explicitdir2.zip\", folder: \"explicitdir\")
    System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/refzipfiles/explicitdir2.zip'.
System.IO.Compression.Tests.ZipFile_Extract.ExtractToDirectoryNormal(file: \"prepended.zip\", folder: \"small\")
    System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/refzipfiles/prepended.zip'.
System.IO.Compression.Tests.ZipFile_Extract.ExtractToDirectoryNormal(file: \"appended.zip\", folder: \"small\")
    System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/refzipfiles/appended.zip'.
System.IO.Compression.Tests.ZipFile_Extract.ExtractToDirectoryNormal(file: \"explicitdir1.zip\", folder: \"explicitdir\")
    System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/refzipfiles/explicitdir1.zip'.
System.IO.Compression.Tests.ZipFile_Extract.ExtractToDirectoryNormal(file: \"noexplicitdir.zip\", folder: \"explicitdir\")
    System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/refzipfiles/noexplicitdir.zip'.
System.IO.Compression.Tests.ZipFile_Extract.ExtractToDirectoryNormal(file: \"normal.zip\", folder: \"normal\")
    System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/refzipfiles/normal.zip'.
System.IO.Compression.Tests.ZipFile_Extract.Unix_ZipWithOSSpecificFileNames(zipName: \"backslashes_FromWindows\", fileName: \"aa\\\\bb\\\\cc\\\\dd\")
    System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/compat/backslashes_FromWindows.zip'.
System.IO.Compression.Tests.ZipFile_Extract.Unix_ZipWithOSSpecificFileNames(zipName: \"backslashes_FromUnix\", fileName: \"aa\\\\bb\\\\cc\\\\dd\")
    System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/compat/backslashes_FromUnix.zip'.
System.IO.Compression.Tests.ZipFile_Extract.Unix_ZipWithOSSpecificFileNames(zipName: \"WindowsInvalid_FromUnix\", fileName: \"aa<b>d\")
    System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/compat/WindowsInvalid_FromUnix.zip'.
System.IO.Compression.Tests.ZipFile_Extract.Unix_ZipWithOSSpecificFileNames(zipName: \"WindowsInvalid_FromWindows\", fileName: \"aa<b>d\")
    System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/compat/WindowsInvalid_FromWindows.zip'.
System.IO.Compression.Tests.ZipFile_Extract.ExtractToDirectoryOverwriteEncoding
    System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/refzipfiles/normal.zip'.
System.IO.Compression.Tests.ZipFile_Extract.ExtractToDirectoryOverwrite
    System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/refzipfiles/normal.zip'.

Test collection for System.IO.Compression.Tests.ZipFile_Create
System.IO.Compression.Tests.ZipFile_Create.UpdateReadTwice
    System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/refzipfiles/small.zip'.
System.IO.Compression.Tests.ZipFile_Create.CreateFromDirectory_IncludeBaseDirectory
    System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/refzipfolders/normal'.
System.IO.Compression.Tests.ZipFile_Create.Unix_ZipWithInvalidFileNames_ThrowsArgumentException(zipName: \"NullCharFileName_FromWindows\")
    Assert.Throws() Failure\nExpected: typeof(System.ArgumentException)\nActual:   typeof(System.IO.DirectoryNotFoundException): Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/compat/NullCharFileName_FromWindows.zip'.\n---- System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/compat/NullCharFileName_FromWindows.zip'.
System.IO.Compression.Tests.ZipFile_Create.Unix_ZipWithInvalidFileNames_ThrowsArgumentException(zipName: \"NullCharFileName_FromUnix\")
    Assert.Throws() Failure\nExpected: typeof(System.ArgumentException)\nActual:   typeof(System.IO.DirectoryNotFoundException): Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/compat/NullCharFileName_FromUnix.zip'.\n---- System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/compat/NullCharFileName_FromUnix.zip'.
System.IO.Compression.Tests.ZipFile_Create.CreateFromDirectoryUnicode
    System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/refzipfolders/unicode'.
System.IO.Compression.Tests.ZipFile_Create.UnsupportedCompressionRoutine(zipName: \"invalidDeflate.zip\", throwsOnOpen: False)
    System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/badzipfiles/invalidDeflate.zip'.
System.IO.Compression.Tests.ZipFile_Create.UnsupportedCompressionRoutine(zipName: \"LZMA.zip\", throwsOnOpen: True)
    System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/badzipfiles/LZMA.zip'.
System.IO.Compression.Tests.ZipFile_Create.InvalidDates
    System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/badzipfiles/invaliddate.zip'.
System.IO.Compression.Tests.ZipFile_Create.InvalidInstanceMethods
    System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/refzipfiles/normal.zip'.
System.IO.Compression.Tests.ZipFile_Create.CreateFromDirectoryNormal
    System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/refzipfolders/normal'.
System.IO.Compression.Tests.ZipFile_Create.UpdateAddFile
    System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/refzipfiles/normal.zip'.
System.IO.Compression.Tests.ZipFile_Create.InvalidFiles
    Assert.Throws() Failure\nExpected: typeof(System.IO.InvalidDataException)\nActual:   typeof(System.IO.DirectoryNotFoundException): Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/badzipfiles/EOCDmissing.zip'.\n---- System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/badzipfiles/EOCDmissing.zip'.
System.IO.Compression.Tests.ZipFile_Create.ReadStreamOps
    System.IO.DirectoryNotFoundException : Could not find a part of the path '/private/var/root/Library/Developer/CoreSimulator/Devices/ADAC362F-F37F-4A45-9337-9FB1A65CC32B/data/Containers/Bundle/Application/5D4259EF-2314-4E96-8124-C8656DFC57E2/System.IO.Compression.ZipFile.Tests.app/ZipTestData/refzipfiles/normal.zip'.

**Comment by filipnavara** [comment] 2021-05-06 11:23
This is caused by #52104. However, I was not able to run the test locally to verify if it's fixed by #52372 or not.

**Closed** 2021-05-06 19:26 UTC
Labels: area-System.IO.Compression, in pr, os-ios, os-tvos, untriaged
