### ISSUE TITLE
Unable to run dotnet runtime on linux-musl-x86

### ISSUE THREAD

**Issue by Exmirai** [dotnet/runtime#100223] opened 2024-03-25 07:09 UTC
### Description

I'm trying to build dotnet for i686 architecture. Unfortunately getting "coreclr_initialize failed - Error: 0x8007000e" - Out of Memory error. From docker stats plots realizing that dotnet trying to eat all memory available to container ( due to i686 architecture - only 4 gigs ) and right after hitting a limit it's throwing an error. Also during that process CPU consumption raises to 100%. 
Below is a plot from docker stats representing container state during coreclr initialization ( 2 peaks represents 2 attempts to run an application ). Looks like there's a kinda loop which causes coreclr to take all CPU time
![image](https://github.com/dotnet/runtime/assets/6436703/366efecd-453d-4eef-a5d7-a1df92408e5f)
I'm also tried to build dotnet using official cross image ("mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-2.0-cross-x86") and targeting ubuntu which is also was unsuccessful

### Reproduction Steps

Dockerfile i wrote to build dotnet: https://pastebin.com/J5dTbsGt

### Expected behavior

Dotnet is running 

### Actual behavior

Getting: "coreclr_initialize failed - Error: 0x8007000e"

Details: https://pastebin.com/GXcEjMM8

### Regression?

Unknown

### Known Workarounds

Unknown

### Configuration

Attempting to build: **v8.0.3**
Host OS: ubuntu: **jammy**
Target OS: **alpine-x86**

**Comment by huoyaoyuan** [comment] 2024-03-25 07:33
Duplicate of #83509

**Comment by Exmirai** [comment] 2024-03-25 08:54
So there's no way to at least overcome these behaviour?

**Comment by huoyaoyuan** [comment] 2024-03-25 09:40
linux-x86 is not fully supported. It's not on the supported configuration list.

**Comment by Exmirai** [comment] 2024-03-25 09:45
I know, there could be bugs. But as far as i know it should build and run normally

**Comment by jkotas** [comment] 2024-03-25 15:52
Closing as duplicate of https://github.com/dotnet/runtime/issues/83509

**Closed by jkotas** 2024-03-25 15:52 UTC
Labels: arch-x86, os-linux, area-VM-coreclr, untriaged
