### ISSUE TITLE
Support non-allocating view on string properties values of JSON in System.Text.Json.JsonElement

### ISSUE THREAD

**Issue by tomas-pajurek** [dotnet/runtime#78885] opened 2022-11-27 09:46 UTC
In .NET 7, there is a new set of methods [`CopyString(...)`](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonreader.copystring?view=net-7.0) on the `Utf8JsonReader` that allows for non-allocating view of string properties. Related issue: https://github.com/dotnet/runtime/issues/54410.

With the same background and motivation as in the related issue, would it make sense to introduce similar change also to `JsonElement` type?

**Comment by eiriktsarpalis** [comment] 2022-11-27 12:31
Duplicate of https://github.com/dotnet/runtime/issues/77666#issuecomment-1310232348

**Closed by eiriktsarpalis** 2022-11-27 12:31 UTC
Labels: area-System.Text.Json, untriaged
