### ISSUE TITLE
Net core app silently crash if exception occurs  during inherited type creation from dynamic loaded library.

### ISSUE THREAD

**Issue by gleb-grigoriev** [dotnet/runtime#40758] opened 2020-08-13 08:30 UTC
### Configuration

.Net core 3.1.5, windows 10

### Other information

I have asp net core app which loads dll dynamically using    AssemblyLoadContext.
Assembly loads fine but later when I try to create type located in this assembly app silently crashes (closes) without any information. 

`            var type = asm.GetType("A");
            var factory = type.GetConstructor(new[] { inputData.GetType() });
            TemplateExecution.ExecutionContext execContext;
            try
            {
                execContext = (A)factory.Invoke(new object[] { inputData });
            }
            catch(Exception ex)
            {
                throw;
            }`
catch does not help and debugger does not stop there.
Type A is something like that: `public class A: B {  A() :base() { //some code where exception occurs  } }`
Catch works if exception rises in base constructor (type B), but if it happens in  A type constructor - catch does not help and app silently closes. I can not find any exception information anywhere after that.

**Comment by gleb-grigoriev** [comment] 2020-08-13 08:46
Ohh.. seems that I choose the wrong bugtracker...or?

**Comment by jkotas** [comment] 2020-08-13 15:24
Is it possible to share the project that reproduces the problem?

**Comment by gleb-grigoriev** [comment] 2020-08-13 16:48
Well. I could try to prepare test project if needed. But now I have more details. class B has incorrect (temporary) code in constructor
`this != "";` and  bug in overloaded operators !=/==.  which cause StackOverflow exception. For some reason i could catch this exception in .net core 3.1 console app but not in asp .net....should I still prepare a test project?

**Comment by gleb-grigoriev** [comment] 2020-08-13 16:50
So probably the issue is : if Stackoverflow exception occurs in dynamically load type in asp .net - application silently crash. I`ve tried to throw Stackoverflow exception manually but on this case everything works fine.

**Comment by jkotas** [comment] 2020-08-13 17:12
StackOverflowException cannot not be caught using try/catch in C#. You should still see an error message when stackoverflow happens.

I doubt that the behavior depends on whether the module is dynamically loaded. The behavior difference is more likely caused by ASP.NET hosting layer. It may be still useful if you can create a project that demonstrates the problem if it is not hard.

**Comment by gleb-grigoriev** [comment] 2020-08-13 17:24
are are right. I`m able to catch stackoverflow not in catch but in debugger (it stops on the line) and I see message in normal console app.But asp .net core app is silently closes. If I will have time - I`ll try to create a sample.

**Comment by danmosemsft** [comment] 2020-08-13 18:22
You might try it in 5.0 preview 7 as well. It may give you a better stack.

**Comment by mangod9** [comment] 2020-08-14 17:08
Possible dupe of https://github.com/dotnet/runtime/issues/32629. Moving to Diagnostics and 6.0 (as the other issue)

**Comment by tommcdon** [comment] 2020-12-09 23:43
Looks like a dupe to #32629.  The root issue is related with catching stackoverflow in the debugger before the process exits

**Closed by tommcdon** 2020-12-09 23:43 UTC
Labels: area-Diagnostics-coreclr, needs more info
