### ISSUE TITLE
Hardware Intrinsics test failure

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#35939] opened 2020-05-07 05:09 UTC
```
C:\h\w\A28A0921\w\BC360A0D\e>type C:\h\w\A28A0921\w\BC360A0D\u\SetStressModes_normal.cmd 

C:\h\w\A28A0921\w\BC360A0D\e>C:\h\w\A28A0921\p\CoreRun.exe C:\h\w\A28A0921\p\xunit.console.dll JIT\HardwareIntrinsics\JIT.HardwareIntrinsics.XUnitWrapper.dll -parallel collections -nocolor -noshadow -xml testResults.xml -trait TestGroup=JIT.HardwareIntrinsics 
Microsoft.DotNet.XUnitConsoleRunner v2.5.0 (32-bit .NET 5.0.0-ci)
  Discovering: JIT.HardwareIntrinsics.XUnitWrapper
  Discovered:  JIT.HardwareIntrinsics.XUnitWrapper
  Starting:    JIT.HardwareIntrinsics.XUnitWrapper
    JIT\HardwareIntrinsics\General\NotSupported\NotSupported_ro\NotSupported_ro.cmd [FAIL]
      
      Assert failure(PID 5260 [0x0000148c], Thread: 1196 [0x04ac]): Assertion failed '(jitIntrinsic->gtSIMDSize == 12) || (jitIntrinsic->gtSIMDSize == 16)' in 'System.Runtime.Intrinsics.Vector256:GetUpper(System.Runtime.Intrinsics.Vector256`1[Boolean]):System.Runtime.Intrinsics.Vector128`1[Boolean]' during 'Lowering nodeinfo' (IL size 116)
      
          File: F:\workspace\_work\1\s\src\coreclr\src\jit\lower.cpp Line: 1337
          Image: C:\h\w\A28A0921\p\CoreRun.exe

      
      
      Return code:      1
      Raw output file:      C:\h\w\A28A0921\w\BC360A0D\e\JIT\HardwareIntrinsics\Reports\JIT.HardwareIntrinsics\General\NotSupported\NotSupported_ro\NotSupported_ro.output.txt
      Raw output:
      BEGIN EXECUTION
       "C:\h\w\A28A0921\p\corerun.exe" NotSupported_ro.dll 
 
```
https://github.com/dotnet/runtime/pull/35799
https://helix.dot.net/api/2019-06-17/jobs/b5453ee1-9858-4492-a806-f19e3a75b1bd/workitems/JIT.HardwareIntrinsics/console
cc @tannergooding

**Comment by tannergooding** [comment] 2020-05-07 05:15
This is a dupe of https://github.com/dotnet/runtime/issues/35877

It should be resolved now with https://github.com/dotnet/runtime/pull/35904

**Closed** 2020-05-07 17:55 UTC
Labels: area-CodeGen-coreclr, untriaged
