### ISSUE TITLE
options.GetConverter used inside other JsonConverter causes "Deserialization of types without[...]" error

### ISSUE THREAD

**Issue by raphaelschmitz00** [dotnet/runtime#94538] opened 2023-11-08 20:07 UTC
### Description

Getting a converter via `GetConverter()` and using it inside another JsonConverter throws a NotSupportedException.

### Reproduction Steps

```csharp
using System.Text.Json;
using System.Text.Json.Serialization;


public class TestDocument
{
	public TestType TestType { get; init; }
}


public class TestType { }


public class TestConverter : JsonConverter<TestType>
{
	private readonly JsonConverter<TestType> _innerConverter;
	
	public TestConverter(JsonConverter<TestType> innerConverter)
	{
		_innerConverter = innerConverter;
	}
	
	public override TestType? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) => 
		_innerConverter.Read(ref reader, typeToConvert, options);
	
	public override void Write(Utf8JsonWriter writer, TestType value, JsonSerializerOptions options) => 
		throw new NotImplementedException();
}


public class InnerConverterTests
{
	[Fact]
	public void InnerConverter_Works()
	{
		var json = """{ "TestType": {} }""";
		
		var options = new JsonSerializerOptions();
		var innerConverter = (JsonConverter<TestType>)options.GetConverter(typeof(TestType));
		var testConverter = new TestConverter(innerConverter);
		options.Converters.Add(testConverter);

		// This next line produces the error
		var testDocument = JsonSerializer.Deserialize<TestDocument>(json, options);
	}
}

```

### Expected behavior

With the given example, "standard" deserialization, as if I didn't provide any `JsonSerializerOptions`.

### Actual behavior

Throws a `System.NotSupportedException` with message _"Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported."_

Maybe this is a weird thing to do, but the error message is at least still misleading then.

### Regression?

I don't know.

### Configuration

.NET 7.0.401
win11
x64

**Comment by eiriktsarpalis** [comment] 2023-11-08 20:33
This is a known problem, unfortunately certain built-in converters cannot function independently of contract metadata. As a workaround you could try wrapping the `JsonTypeInfo<T>` instance for the particular type which encapsulates both the converter and the required contract metadata:
```C#
var innerTypeInfo = (JsonTypeInfo<TestType>)JsonSerializerOptions.Default.GetTypeInfo(typeof(TestType));
var options = new JsonSerializerOptions
{
    Converters = { new TestConverter(innerTypeInfo) }
};

JsonSerializer.Deserialize<TestDocument>(json, options);

public class TestConverter : JsonConverter<TestType>
{
    private readonly JsonTypeInfo<TestType> _innerTypeInfo;

    public TestConverter(JsonTypeInfo<TestType> innerTypeInfo)
    {
        _innerTypeInfo = innerTypeInfo;
    }

    public override TestType? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options) =>
        JsonSerializer.Deserialize(ref reader, _innerTypeInfo);

    public override void Write(Utf8JsonWriter writer, TestType value, JsonSerializerOptions options) =>
        throw new NotImplementedException();
}
```

Duplicate of https://github.com/dotnet/runtime/issues/50205.

**Closed by eiriktsarpalis** 2023-11-08 20:33 UTC
Labels: area-System.Text.Json, untriaged
