### ISSUE TITLE
App icon is not embedded when compiled on Ubuntu targeting Windows

### ISSUE THREAD

**Issue by o-mdr** [dotnet/runtime#48111] opened 2021-02-10 16:33 UTC
### Description

I have a cross-platform console dotnet core 5.0 application, here's a relevant extract from the .csproj file
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <ApplicationIcon>main48.ico</ApplicationIcon>
  </PropertyGroup>
  ...
</Project>
```
When I publish it with `dotnet publish` on my laptop running Windows 10 x64, I get a `foo.exe` with the icon (yellow square).

![image](https://user-images.githubusercontent.com/3082246/107537620-fd23c100-6bba-11eb-8cf9-8676f29dfa85.png)

When I  publish it on the build machine running Ubuntu 18.04 LTS, the icon doesn't seem to be embedded correctly. When I download the published app from the build machine and open it in the Windows explorer, the icon is not there.

![image](https://user-images.githubusercontent.com/3082246/107537933-5ab80d80-6bbb-11eb-98a1-a01d6f00ae85.png)

I am using the same source code, same project, but different platforms for the build. 

I've also tried building the project on my laptop using VS Code with WSL Ubuntu 18.04 LTS. I observed the same outcome: binaries compiled on Ubuntu do not have an icon.

Affected commands:
```
dotnet build
dotnet publish
# Published as a single app or an app with separate dependencies
```

I expect that the icon gets embedded correctly during the build on Ubuntu, targeting Windows OS executables.

### Configuration

* Which version of .NET is the code running on? 

dotnet core 5.0

* What OS and version, and what distro if applicable?

Windows 10 x64, Ubuntu 18.04 LTS x64

* What is the architecture (x64, x86, ARM, ARM64)?

Application is compiled as Windows x86

* Do you know whether it is specific to that configuration?

Not sure

### Regression?

Did not test in previous releases

**Comment by o-mdr** [comment] 2021-02-10 16:38
Will this issue be better suited here https://github.com/dotnet/sdk? Apologies if this is the wrong repo

**Comment by jkotas** [comment] 2021-02-10 16:58
Duplicate of https://github.com/dotnet/sdk/issues/3943

**Closed by jkotas** 2021-02-10 16:58 UTC
Labels: untriaged
