### ISSUE TITLE
System.IO.IOException: The configured user limit (1024) on the number of inotify instances has been reached, or the per-process limit on the number of open file descriptors has been reached.

### ISSUE THREAD

**Issue by caroe2014** [dotnet/runtime#37664] opened 2020-06-09 19:14 UTC

**Comment by stephentoub** [comment] 2020-06-09 19:43
From @ackginger in https://github.com/dotnet/runtime/issues/27272:

> Isn't the issue actually here in PhysicalFilesWatcher:
https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PhysicalFilesWatcher.cs#L134
> This class attempts to respect `DOTNET_USE_POLLING_FILE_WATCHER` as it is constructed with `pollForChanges=true` in that case (by [PhysicalFileProvider](https://github.com/dotnet/runtime/blob/master/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PhysicalFileProvider.cs)), and proceeds to register `PollingFileChangeToken`s for use instead of watching the filesystem ... however `TryEnableFileSystemWatcher` is called regardless of the value of `PollForChanges`.

**Comment by adriend-advz** [comment] 2020-06-18 23:51
FWIW, I managed to solve this issue by hosting my App Service in a distinct App Service Plan (was mixing Function Apps and "regular" Web Apps in the same).

**Comment by caroe2014** [comment] 2020-06-19 15:14
You do have a workaround for DotNet Core 3.1 ?

**Comment by adriend-advz** [comment] 2020-06-19 15:21
Actually I have several Function Apps deployed on Azure and one "regular" Web App, all built on .NET Core 3.1 and hosted on Linux containers.
I had the same issue as you with the above mentionned error message on my "regular" web app. I ended up hosting it on an App Service Plan distinct from the one for Function Apps.

**Comment by caroe2014** [comment] 2020-06-19 16:01
Thank you for your answer but what I am looking for is: The ReloadOnChange workaround requires that one now modify  the Program.cs Host.CreateDefaultBuilder that is part of the .NET templates for CORE 3.1.    By default you can see how many **Iconfiguration items** this loads and **there is no guidance** I have found as to **what needs to change** for this issue for **what the Host builder should look like**.  It seems like more work for every new project we create, I think when DotNet Core team created the workaround under 2.2 this Hostbuilder was more code and all the Iconfiguration code was exposed making it easy to update, and this is not the case for 3.1. 

![image](https://user-images.githubusercontent.com/8444418/85153438-d4118300-b21b-11ea-9f4a-4a6e24b8eb70.png)

**Comment by adriend-advz** [comment] 2020-06-19 22:18
My bad, thought I could be able to unblock you :(
Good luck!

**Comment by caroe2014** [comment] 2020-07-15 15:00
Any Update in this Issue?

**Comment by mike-jewell** [comment] 2020-08-09 22:16
Will this be retroactively fixed for dotnet core 3?  What kind of timeframe would there be for a fix?  

Seeing this problem once a week now on Azure app service with the config described in #40350.  The only solution for now is to use log monitor alerts and azure automation powershell scripts to scale down and up again, which isn't ideal.

**Comment by fsalmeida** [comment] 2020-08-10 13:09
I've been facing the same problem as you do.
Recently this problem has ocurred to one of my applications, then I've scaled up the ServicePlan and the application has back to life. Then I scaled it down and it still works.
Today I've faced the same problem with other application and I'm still trying to find a way to solve the problem.

**Comment by stephentoub** [comment] 2020-08-13 10:02
This got moved to Future.  Shouldn't this be fixed for 5.0?  If the problem is what's described above (https://github.com/dotnet/runtime/issues/37664#issuecomment-641530658), this is also an issue with Microsoft.Extensions.
cc: @maryamariyan

**Comment by ericstj** [comment] 2020-08-20 19:20
Looks like this issue is causing significant customer pain and there is a known bug / fix here.  Moving this in to 5.0 for bar check.

**Comment by ericstj** [comment] 2020-08-20 19:35
@pranavkm do you agree with @ackginger's assessment here?  It looks like this behavior has been present since https://github.com/aspnet/FileSystem/commit/c22515597524dfad7f65717cb7e759b9dd7236b6

**Comment by pranavkm** [comment] 2020-08-20 21:05
Yes that is correct. Changing it so that `DOTNET_USE_POLLING_FILE_WATCHER` exclusively uses polling should not only fix this issue, but is also something we'd wanted as an implementation. We'd tried to address this at some point but that PR got nixed because it happened right around the time repos got consolidated.

**Comment by ericstj** [comment] 2020-08-20 22:01
Good point: today this uses a conjunction of both the FSW *and* polling to trigger the events.  The suggested change will make it exclusively use polling when set.

I couldn't find that PR.  Did you recall why it got nixed?  Was there any push back on the behavior change?

**Comment by pranavkm** [comment] 2020-08-20 22:16
Hmm, I thought I had the PR sitting in dotnet/extensions but I can't seem to find it either. I don't recall there being a push-back, it was just in the middle of a bunch of repo changes and it never went anywhere.

**Comment by ericstj** [comment] 2020-09-01 03:53
I have a PR ready for this but I’m not 100% confident it is low enough risk to take this late in 5.0.  Will move to 6.0.  Folks can still pick up the package and try it out on 5.0 / 3.x.

**Closed** 2020-11-12 15:16 UTC
Labels: area-Extensions-FileSystem, bug
