### ISSUE TITLE
Running a dll with dotnet6.0.11 fails with error code HRESULT: 0x80004005

### ISSUE THREAD

**Issue by Jay-Madden** [dotnet/runtime#79668] opened 2022-12-14 19:32 UTC
### Description

Running a dll causes the CLR to fail to start with an obscure HRESULT with this COREHOST_TRACE
```
Files\dotnet\shared\Microsoft.NETCore.App\6.0.11\System.Text.RegularExpressions.dll;C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.11\System.Threading.dll;C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.11\System.Threading.Tasks.Dataflow.dll;C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.11\System.Private.CoreLib.dll
Property NATIVE_DLL_SEARCH_DIRECTORIES = C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\6.0.11\;C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.11\;
Property PLATFORM_RESOURCE_ROOTS = 
Property APP_CONTEXT_BASE_DIRECTORY = D:\WebServices\SSEHub.Notification\
Property APP_CONTEXT_DEPS_FILES = D:\WebServices\SSEHub.Notification\SSEHub.Notifications.Api.deps.json;C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\6.0.11\Microsoft.AspNetCore.App.deps.json;C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.11\Microsoft.NETCore.App.deps.json
Property PROBING_DIRECTORIES = 
Property RUNTIME_IDENTIFIER = win81-x64
Property System.GC.Server = true
Property System.Reflection.Metadata.MetadataUpdater.IsSupported = false
Property System.Reflection.NullabilityInfoContext.IsSupported = true
Property System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization = false
CoreCLR path = 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.11\coreclr.dll', CoreCLR dir = 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.11\'
Loaded library from C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.11\coreclr.dll
Failed to create CoreCLR, HRESULT: 0x80004005
```

Inspected the process run with procmon and found an ACCESS DENIED on the registry key `WinSock2/Paramaters` enabling full access on that key removed the ACCESS DENIED error from procmon but did not fix the HRESULT4005 error.

No further ACCESS DENIED entries found

### Reproduction Steps

N/A

### Expected behavior

Dll executes succesfully

### Actual behavior

Runtime fails to start

### Regression?

N/a

### Known Workarounds

None

### Configuration

```
Property RUNTIME_IDENTIFIER = win81-x64
Dotnet6.0.11
Windows Server 2012 R2
```

**Comment by Jay-Madden** [comment] 2022-12-14 19:35
I can provide full procmon or COREHOST_TRACE output if needed

**Comment by Jay-Madden** [comment] 2022-12-16 19:42
Update, pulled latest main nightly, same result
<img width="658" alt="image" src="https://user-images.githubusercontent.com/25359755/208176445-88ff1ab1-b957-489b-8d95-6f219183cd51.png">

**Comment by agocke** [comment] 2022-12-16 20:17
@elinor-fung

**Comment by elinor-fung** [comment] 2023-01-04 19:45
This is our favourite E_FAIL when initializing coreclr (after going through the host fine). @janvorli made a change a while ago for 8.0 to help with diagnosing issues there. Unfortunately, it doesn't look like that has made it into the latest builds out of dotnet/installer yet.

@Jay-Madden could you also provide the output of `dotnet --info`?

@janvorli any suggestions for other information/logs on builds that don't have your changes for better coreclr initialization failure diagnostics?

**Comment by janvorli** [comment] 2023-01-04 21:23
@Jay-Madden the procmon trace would definitely be helpful for identifying the root cause.

@elinor-fung the last dotnet/installer nightly package is about a month old, that's why it doesn't contain the logging yet.

**Comment by Jay-Madden** [comment] 2023-01-04 22:22
Hello, @janvorli @elinor-fung 

Apologies for not updating this as it slipped my mind. I managed to track down the obscure root of this failure a few days after posting this.

The cause was a misconfiguration one the legacy VMs. Apparently a POC for Dynatrace AppMon (https://www.dynatrace.com/solutions/application-monitoring/) was done many, many years ago on these VMs. AppMon works via a CLR profiler and for some reason, the vms had been configured with `CORECLR_PROFILER*` values to point to the .net framework dynatrace profiler dlls which caused the runtime to fail on startup attempting to load the dll.

So while this is certainly not a runtime problem merely a configuration error. I do hope that the dotnet8 startup logging improvements do cover the use case of a loaded profiler dll causing a crash.

**Comment by janvorli** [comment] 2023-01-05 18:36
@Jay-Madden thank you for the details, I am closing this issue then.

**Closed by janvorli** 2023-01-05 18:36 UTC
Labels: area-Host, untriaged
