### ISSUE TITLE
Intermittent "System.Net.Http.HttpRequestException: No such host is known" when making high volume in-parallel calls from a single host.

### ISSUE THREAD

**Issue by SGeorge007** [dotnet/runtime#54547] opened 2021-06-22 12:27 UTC
I am getting error intermittently within an Azure function (.net core 3.1) when making multiple  post calls per minute to a custom application hosted within azure. Like everyone else facing the issue i am using httpClient to make post calls.

It seems to be related to .net. Please find the issue i am referencing. I searched the net but it seems there is no solution till now. Any help is greatly appreciated.

https://github.com/dotnet/runtime/issues/31247

**Comment by karelz** [comment] 2021-06-22 12:57
The referenced issue didn't have enough info to be able to track it down.
Would it be possible to try it out on .NET 5? Does it have the same problems?
If you can reproduce it on .NET 5, we could try to collect our new in-proc Telemetry from there. That could help us pinpoint the problem. cc @MihaZupan 
It is quite possible that it is external problem -- the OS truly not being able to resolve DNS.

**Comment by SGeorge007** [comment] 2021-06-22 15:20
unfortunately we cannot upgrade the solution to .net 5.0 now.. This app is in azure. Please find the stack trace for the errors.

System.Net.Sockets.SocketException at Common.Helpers.RequestResponseHelper+<PostRequest>d__8`2.MoveNext

 `{"severityLevel":"Error","parsedStack":[{"method":"Common.Helpers.RequestResponseHelper+<PostRequest>d__8`2.MoveNext","assembly":"Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","level":0,"line":117,"fileName":"D:\\a\\1\\s\\src\\Common\\Helpers\\RequestResponseHelper.cs"},{"method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","level":1,"line":0},{"method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","level":2,"line":0},{"method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","level":3,"line":0},{"method":"System.Runtime.CompilerServices.TaskAwaiter`1.GetResult","assembly":"System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","level":4,"line":0},{"method":"AccountManagementServices.Services.AccountService+<AccountSearch>d__10.MoveNext","assembly":"AccountManagementServices, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","level":5,"line":277,"fileName":"D:\\a\\1\\s\\src\\AccountManagementServices\\Services\\AccountService.cs"}],"outerId":"0","message":"One or more errors occurred. (No such host is known.)","type":"System.AggregateException","id":"58677634"}`

**Comment by wfurt** [comment] 2021-06-22 15:34
There is _some_ tracing even in 3.1. Check out notes from  https://github.com/dotnet/runtime/issues/31209  @SGeorge007 

Is your app making new lookup for each request? (e.g. whit is your reuse strategy for HttpClient)

**Comment by SGeorge007** [comment] 2021-06-22 16:55
Is your app making new lookup for each request? (e.g. whit is your reuse strategy for HttpClient)

HttpClient is exposed as a singleton instance:

`
**Startup.cs**
        private void AddSingletonServices(IFunctionsHostBuilder builder)
        {
            builder.Services.AddSingleton(sp => new HttpClient());
        }

        public override void Configure(IFunctionsHostBuilder builder)
        {      
            AddSingletonServices(builder);
       }
       
**RequestResponseHelper *********
           public class RequestResponseHelper : IDisposable, IRequestResponseHelper
    {
        private bool _isDisposed = false;
        private readonly HttpClient _client;
        public RequestResponseHelper(HttpClient client, TelemetryClient telemetryClient, ILogger<RequestResponseHelper> logger = null)
        {
            _client = client;
            _logger = logger;
            _telemetryClient = telemetryClient;
        }
        
                public async Task<TOut> GetRequest<TIn, TOut>(string uri, TIn content)
                   where TIn : class
                   where TOut : class, new()
        {
            try
            {
                _logger?.LogInformation($"{this.GetType().Name} > {MethodBase.GetCurrentMethod().Name} Starts Execution.");
                using HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, uri);
                request.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                var sContent = JsonConvert.SerializeObject(content, Formatting.Indented, new JsonSerializerSettings { ContractResolver = new CamelCasePropertyNamesContractResolver(), NullValueHandling = NullValueHandling.Ignore });
                request.Content = new StringContent(sContent, Encoding.UTF8);
                request.Content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                //using HttpClient _client = new HttpClient();
                var response = _client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead).Result;
       }
        
}


`

**Comment by karelz** [comment] 2021-06-23 09:36
@SGeorge007 are you able to try to isolate a smaller repro out of your app?
Once you have the repro, perhaps try that on .NET 5?

Given the information above, I don't think we can make any progress forward.

Also, when it happens, is it only one failure, or does it start to happen for a period of time and then works fine again?
How often does it happen? (typical intervals between failures)

**Comment by karelz** [comment] 2021-06-29 10:28
Triage: Closing as not actionable at this moment. Feel free to reopen once there is more information and the issue is actionable again.

**Closed by karelz** 2021-06-29 10:28 UTC
Labels: area-System.Net.Http, needs more info, untriaged
