### ISSUE TITLE
Issue with ICU Library Update on Ubuntu 24.2 LTS Affecting String Formatting in .NET 8.0

### ISSUE THREAD

**Issue by cout00** [dotnet/runtime#104031] opened 2024-06-26 13:20 UTC
### Description

After updating to Ubuntu 24.2 LTS, the ICU libraries were also updated, which caused issues with some methods that return string formats in our .NET 8.0.5 application

### Reproduction Steps

```
var culture = new CultureInfo("en-US", false);
string result = culture.DateTimeFormat.LongTimePattern;
var strAsArray = string.Join(" ", result.ToCharArray().Select(a => $"{a}=[{(int)a}]"));
```

### Expected behavior

We expect results like in Windows 10 
`h=[104] :=[58] m=[109] m=[109] :=[58] s=[115] s=[115]  =[32] t=[116] t=[116]`

### Actual behavior

The actual behavior on Linux platform is:
`h=[104] :=[58] m=[109] m=[109] :=[58] s=[115] s=[115]  =[8239] t=[116] t=[116]`

### Regression?

As shown, the character with the code 8239 (NARROW NO-BREAK SPACE) is returned on Linux, while the character with the code 32 (SPACE) is returned on Windows.

These changes affect the customers of our commercoal product DevExpress Reporting as we process and parse such strings internally. Current regular expressions, such as the one below, no longer work:
 
`result = result.Replace("\"tt\"", "AM/PM");`

Could you please provide your comments on this discrepancy and any potential solutions or workarounds?

### Configuration

WSL ubuntu 24.04 LTS
Icu 72.2
net 8.0.5

**Comment by DL444** [comment] 2024-06-26 15:24
Duplicate of #103750 and many others. See linked issue for recommendations.

**Comment by tarekgh** [comment] 2024-06-26 15:42
Yes, this is a duplicate of https://github.com/dotnet/runtime/issues/103750. It is intentional change done by Unicode CLDR standard.

**Closed by tarekgh** 2024-06-26 15:42 UTC
Labels: area-System.Globalization, untriaged
