### ISSUE TITLE
Test failure: Microsoft.Extensions.Hosting.UseWindowsServiceTests.CanCreateService

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#107240] opened 2024-09-02 02:01 UTC
**Failed in:** [runtime-coreclr libraries-pgo 20240901.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=795147&view=ms.vss-test-web.build-test-results-tab&runId=20468466&resultId=106158&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-arm64-defaultpgo-Windows.11.Arm64.Open
    - Microsoft.Extensions.Hosting.UseWindowsServiceTests.CanCreateService
```

**Error message:**
```
 System.ServiceProcess.TimeoutException : The operation requested for service 'CanCreateService' has not been completed within the specified time interval.
```

**Stack trace:**
```
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout) in /_/src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceController.cs:line 994
   at Microsoft.Extensions.Hosting.WindowsServiceTester.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout) in /_/src/libraries/Microsoft.Extensions.Hosting.WindowsServices/tests/WindowsServiceTester.cs:line 58
   at Microsoft.Extensions.Hosting.WindowsServiceTester.WaitForStatus(ServiceControllerStatus desiredStatus) in /_/src/libraries/Microsoft.Extensions.Hosting.WindowsServices/tests/WindowsServiceTester.cs:line 54
   at Microsoft.Extensions.Hosting.UseWindowsServiceTests.CanCreateService() in /_/src/libraries/Microsoft.Extensions.Hosting.WindowsServices/tests/UseWindowsServiceTests.cs:line 47
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by v-wenyuxu** [comment] 2024-09-03 01:22
**Failed in:** [runtime-coreclr libraries-jitstress 20240902.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=795313&view=ms.vss-test-web.build-test-results-tab&runId=20473620&resultId=171199&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-arm64-jitminopts-Windows.11.Arm64.Open
    - Microsoft.Extensions.Hosting.UseWindowsServiceTests.CanCreateService
```

**Error message:**
```
 System.ServiceProcess.TimeoutException : The operation requested for service 'CanCreateService' has not been completed within the specified time interval.
```

**Stack trace:**
```
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout) in /_/src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceController.cs:line 994
   at Microsoft.Extensions.Hosting.WindowsServiceTester.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout) in /_/src/libraries/Microsoft.Extensions.Hosting.WindowsServices/tests/WindowsServiceTester.cs:line 58
   at Microsoft.Extensions.Hosting.WindowsServiceTester.WaitForStatus(ServiceControllerStatus desiredStatus) in /_/src/libraries/Microsoft.Extensions.Hosting.WindowsServices/tests/WindowsServiceTester.cs:line 54
   at Microsoft.Extensions.Hosting.UseWindowsServiceTests.CanCreateService() in /_/src/libraries/Microsoft.Extensions.Hosting.WindowsServices/tests/UseWindowsServiceTests.cs:line 47
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by steveharter** [comment] 2024-09-03 20:11
Appears to be duplicate of https://github.com/dotnet/runtime/issues/103548

**Comment by steveharter** [comment] 2024-09-03 20:13
cc @ericstj

**Comment by ericstj** [comment] 2024-09-03 20:20
Failing in `main` too - service is not starting after waiting 3 minutes.  I'm inclined to believe that something about the environment here is causing the test to fail.  I'll see if I can repro locally by pulling down the test payload from these jitminopts runs.

**Comment by ericstj** [comment] 2024-09-04 03:45
No repro on x64 - need to have a look on arm64.  Could be something with how the service configuration/installation is working there.

**Comment by ericstj** [comment] 2024-09-04 20:06
I tested on an arm64 machine and it works here:
```
D:\scratch\serviceRepro\workitems\Microsoft.Extensions.Hosting.WindowsServices.Tests>"D:\scratch\serviceRepro\.\correlation-payload\dotnet.exe" exec --runtimeconfig Microsoft.Extensions.Hosting.WindowsServices.Tests.runtimeconfig.json --depsfile Microsoft.Extensions.Hosting.WindowsServices.Tests.deps.json xunit.console.dll Microsoft.Extensions.Hosting.WindowsServices.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
  Discovering: Microsoft.Extensions.Hosting.WindowsServices.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  Microsoft.Extensions.Hosting.WindowsServices.Tests (found 12 test cases)
  Starting:    Microsoft.Extensions.Hosting.WindowsServices.Tests (parallel test collections = on [8 threads], stop on fail = off)
  Finished:    Microsoft.Extensions.Hosting.WindowsServices.Tests
=== TEST EXECUTION SUMMARY ===
   Microsoft.Extensions.Hosting.WindowsServices.Tests  Total: 12, Errors: 0, Failed: 0, Skipped: 0, Time: 10.625s
```
I used the exact same test payload from the failing machine.  I'm now running in a loop to determine if there's a timing issue at play.  I don't really see how that could happen here though - it's waiting for the service to start so even if the service started early or late - it should still sync up.  My best guess is that the service is failing to start in a way that's missed by the SCM API.  If I cannot reproduce it we can add some more diagnostics here in hopes we can gather more info in case of a failure.

**Comment by v-wenyuxu** [comment] 2024-09-06 04:20
**Failed in:** [runtime-coreclr libraries-jitstress-random 20240904.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=798256&view=ms.vss-test-web.build-test-results-tab&runId=20571836&resultId=174700&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-arm64-jitstress_random_2-Windows.11.Arm64.Open
    - Microsoft.Extensions.Hosting.UseWindowsServiceTests.CanCreateService
```

**Error message:**
```
 System.ServiceProcess.TimeoutException : The operation requested for service 'CanCreateService' has not been completed within the specified time interval.
```

**Stack trace:**
```
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout) in /_/src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceController.cs:line 994
   at Microsoft.Extensions.Hosting.UseWindowsServiceTests.CanCreateService() in /_/src/libraries/Microsoft.Extensions.Hosting.WindowsServices/tests/UseWindowsServiceTests.cs:line 47
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by v-wenyuxu** [comment] 2024-09-09 05:25
**Failed in:** [runtime-coreclr libraries-jitstressregs 20240908.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=801141&view=ms.vss-test-web.build-test-results-tab&runId=20668134&resultId=177789&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-arm64-jitstressregs2-Windows.11.Arm64.Open
    - Microsoft.Extensions.Hosting.UseWindowsServiceTests.CanCreateService
```

**Error message:**
```
 System.ServiceProcess.TimeoutException : The operation requested for service 'CanCreateService' has not been completed within the specified time interval.
```

**Stack trace:**
```
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout) in /_/src/libraries/System.ServiceProcess.ServiceController/src/System/ServiceProcess/ServiceController.cs:line 994
   at Microsoft.Extensions.Hosting.UseWindowsServiceTests.CanCreateService() in /_/src/libraries/Microsoft.Extensions.Hosting.WindowsServices/tests/UseWindowsServiceTests.cs:line 47
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by mikelle-rogers** [comment] 2024-09-09 17:44
@ericstj, thanks for continuing to look into the test failure!

**Comment by ericstj** [comment] 2024-09-12 23:32
Probably the root cause here is the same as https://github.com/dotnet/runtime/issues/107671.  The process is hanging.  Neither the test nor Service nor Extensions libraries are on the stack.  I could use help from someone taking a look at the dump who has more SOS-fu than this tired manager.  Any takers?

**Closed** 2024-09-16 15:27 UTC
Labels: arch-arm64, os-windows, blocking-clean-ci-optional, area-Extensions-Hosting
