### ISSUE TITLE
How about use IReadonly with Options pattern

### ISSUE THREAD

**Issue by jerviscui** [dotnet/runtime#69851] opened 2022-05-26 12:29 UTC
I know Options can use the readonly property like this:

```csharp
public class ReadOnlyOptions
{
    public IReadOnlyCollection<string> Codes { get; set; } = null!;
}
```

appsettings.json

```json
{
  "ReadOnlyOptions": {
    "Codes": [ "123" ] 
  }
}
```

Two questions:
1. The property must init by null value. If `Codes` init by a empty collection, it will never get the value from the config above.
2. If Codes setting is a empty array, `ReadOnlyOptions.Codes` is always null instead of empty array.

Why can't `IReadOnlyCollection` have the same implementation as `ICollection`?

**Comment by eerhardt** [comment] 2022-07-14 22:02
Duplicate of https://github.com/dotnet/runtime/issues/38852. Closing as dupe.

**Closed by eerhardt** 2022-07-14 22:02 UTC
Labels: untriaged, area-Extensions-Configuration
