### ISSUE TITLE
string.IndexOf() on Thai Culture , Windows11, 64 bits, .net5,6,7,8, return incorrect index

### ISSUE THREAD

**Issue by enginekit** [dotnet/runtime#100381] opened 2024-03-28 01:11 UTC
```c#
using System.Globalization;
CultureInfo.CurrentCulture = new CultureInfo("th-TH");
string line = "/a#name:";
int a = line.IndexOf("a");
int b = line.IndexOf("#");
Console.WriteLine($"a: {a}, b: {b}"); 
//a =1, but b =0, !
```
---

```c#
using System.Globalization;

CultureInfo.CurrentCulture = new CultureInfo("en-us");
string line = "/a#name:";
int a = line.IndexOf("a");
int b = line.IndexOf("#");
Console.WriteLine($"a: {a}, b: {b}"); // Expected output: a: 1, b: 2
//a =1, b =2, correct
```

---

**Comment by huoyaoyuan** [comment] 2024-03-29 02:19
Related to #87939

**Comment by tarekgh** [comment] 2024-06-21 01:10
Yes, this is a duplicate of https://github.com/dotnet/runtime/issues/87939. @enginekit have a look at the linked issue to get the idea why you are seeing this behavior. I am closing the issue but feel free to reply with any question if you have any.

**Closed by tarekgh** 2024-06-21 01:10 UTC
Labels: area-System.Globalization, untriaged
