### ISSUE TITLE
Microsoft.Extensions.FileSystemGlobbing doesn't appear to work in a container.

### ISSUE THREAD

**Issue by jeremyheaton** [dotnet/runtime#51560] opened 2021-04-20 13:18 UTC
### Description
Microsoft.Extensions.FileSystemGlobbing does not appear to work inside a docker container. Sample code is below. It will return positive results on a Windows machine, but fail on a container.

### Configuration

5.0.5 and 5.0

I tried multiple images but these are the two relevant to me (it didn't work on any of them)
mcr.microsoft.com/dotnet/runtime:5.0.5-windowsservercore-ltsc2019
mcr.microsoft.com/windows/servercore:ltsc2019

I believe it is any docker container

### Other information
```c#
namespace TestFileGlobbing
{
    class Program
    {
        static void Main(string[] args)
        {
            Matcher matcher;

            void SetQuery(string query)
            {
                Console.WriteLine($"Adding search pattern '{query}'...");
                matcher = new Matcher(StringComparison.Ordinal);
                matcher.AddInclude(query);
            }

            void Match(string item)
            {
                Console.Write($"Testing patterns against '{item}'...");
                var result = matcher.Match(item);
                if (result.HasMatches)
                {
                    Console.WriteLine(" - YES!!!");
                }
                else
                {
                    Console.WriteLine(" - no matches");
                }
            }

            void Test(string query)
            {
                SetQuery(query);
                Match("./test");
                Match("./test/camera1");
                Match("./test/camera2");
            }

            Test("/test");
            Test("./test");
            Test("./test/camera1");
            Test("**");
        }
    }
}
```

```
mcr.microsoft.com/dotnet/runtime:5.0.5-windowsservercore-ltsc2019
COPY sampleCode /

ENTRYPOINT sampleCode.exe
```

**Comment by jeremyheaton** [comment] 2021-04-20 15:29
Did a quick check and I do see this same issues logged back in March. [issue #49645](https://github.com/dotnet/runtime/issues/49645)

**Comment by jeffhandley** [comment] 2021-07-13 06:28
Closing as a duplicate of #49645

**Closed by jeffhandley** 2021-07-13 06:28 UTC
Labels: area-Extensions-FileSystem, untriaged
