### ISSUE TITLE
[release/8.0-rc1] Assertion failed in 'System.Numerics.BigIntegerCalculator:PowCore during 'Generate code'

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#90693] opened 2023-08-16 20:05 UTC
### Error Blob

```json
{
  "ErrorMessage": "Assertion failed 'false' in 'System.Numerics.BigIntegerCalculator:PowCore(System.Span`1[uint],int,System.ReadOnlySpan`1[uint],System.ReadOnlySpan`1[uint],System.Span`1[uint],System.Span`1[uint])' during 'Generate code'",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": true
}
```

### Reproduction Steps

- Test: System.Security.Cryptography
- PR: https://github.com/dotnet/runtime/pull/90658
- Queue: `Libraries Test Run checked coreclr windows x64 Release`
- Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=375536&view=logs&j=51e4640a-c078-5be6-cc1b-f971e75d762f&t=a795459e-9f5a-52e6-9047-d38ac6fe5fb4&l=57
- Log file: https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-pull-90658-merge-e4963b6bd32c4c7fad/System.Security.Cryptography.Tests/1/console.7a170ede.log?helixlogtype=result
- Output:
```
Mismatch in align instruction.
Containing IG: IG97
loopHeadPredIG: IG111
loopHeadIG: IG112
igInLoop: IG113
igInLoop->backEdge: IG95
igInLoop has align instruction for : IG114
Loop:
	IG112
	IG113
	IG114
	IG115
	IG116
	IG117
	IG118
	IG119
	IG120
	IG121
	IG122
	IG123
	IG124
	IG125
	IG126
	IG127
	IG128
	IG129
	IG130
	IG131
	IG132
	IG133
	IG134
	IG135
	IG136
	IG137
	IG138
	IG139
	IG140
	IG141
	IG142
	IG143
	IG144
	IG145
	IG146
	IG147
	IG148
	IG149
	IG150
	IG151
	IG152
	IG153
	IG154
	IG155
	IG156
	IG157
	IG158
	IG159
	IG160
	IG161
	IG162
	IG163
	IG164
	IG165
	IG166
	IG167
	IG168
	IG169
	IG170
	IG171
	IG172
	IG173
	IG174
	IG175
	IG176
	IG177
	IG178
	IG179
	IG180
	IG181
	IG182
	IG183
	IG184
	IG185
	IG186
	IG187
	IG188
	IG189
	IG190
	IG191
	IG192
	IG193
	IG194
	IG195
	IG196
	IG197

Assert failure(PID 1228 [0x000004cc], Thread: 2788 [0x0ae4]): Assertion failed 'false' in 'System.Numerics.BigIntegerCalculator:PowCore(System.Span`1[uint],int,System.ReadOnlySpan`1[uint],System.ReadOnlySpan`1[uint],System.Span`1[uint],System.Span`1[uint])' during 'Generate code' (IL size 511; hash 0xd0657e4f; Tier1)

    File: D:\a\_work\1\s\src\coreclr\jit\emit.cpp Line: 5883
    Image: C:\h\w\B2F709D7\p\dotnet.exe
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=375536
**Error message validated:** `Assertion failed 'false' in 'System.Numerics.BigIntegerCalculator:PowCore(System.Span`1[uint],int,System.ReadOnlySpan`1[uint],System.ReadOnlySpan`1[uint],System.Span`1[uint],System.Span`1[uint])' during 'Generate code'`
**Result validation: :x:** Known issue did not match with the provided build.
**Validation performed at:** 8/16/2023 8:10:07 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by JulieLeeMSFT** [comment] 2023-08-17 21:19
@EgorBo PTAL.

**Comment by JulieLeeMSFT** [comment] 2023-08-31 16:33
Reassigning to @kunalspathak. PTAL.

**Comment by kunalspathak** [comment] 2023-09-02 13:44
@carlossanlop  - can you please confirm the name of pipeline where this failure was happening so I can grab the fresh logs?

**Comment by kunalspathak** [comment] 2023-09-09 14:52
Duplicate of https://github.com/dotnet/runtime/issues/91838

**Closed by kunalspathak** 2023-09-09 14:52 UTC
Labels: os-windows, arch-x64, area-CodeGen-coreclr, blocking-clean-ci, runtime-coreclr, Known Build Error
