### ISSUE TITLE
CI build failure: Libraries Build windows allConfigurations x64 Debug failed

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#45850] opened 2020-12-09 18:27 UTC
Seeing following build failures in the [PR](https://github.com/dotnet/runtime/pull/45767), unrelated to the PR changes
```
src\libraries\pkg\test\testPackages.proj(214,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Validation Failed: System.IO.Pipelines is harvesting assets from package version 5.0.0 which is not the latest for that package release. Latest package version from that release is 5.0.1. In order to fix this, run `dotnet msbuild System.IO.Pipelines.pkgproj /t:UpdateHarvestVersionOnPackageIndex /p:UpdateStablePackageInfo=true`

src\libraries\pkg\test\testPackages.proj(214,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Validation Failed: System.Security.Cryptography.Pkcs is harvesting assets from package version 5.0.0 which is not the latest for that package release. Latest package version from that release is 5.0.1. In order to fix this, run `dotnet msbuild System.Security.Cryptography.Pkcs.pkgproj /t:UpdateHarvestVersionOnPackageIndex /p:UpdateStablePackageInfo=true`
```

**Comment by safern** [comment] 2020-12-09 18:30
Thanks @buyaa-n, this is a dupe of: https://github.com/dotnet/runtime/issues/45782. This was already fixed, it is possible that your PR ran against a commit where the fix wasn't there yet. You would need to do a full re-run to get it out of the way because we cache the checkout bundle and share it across all legs, so if you do "re-run failed jobs" you will get the same commit.

**Closed by safern** 2020-12-09 18:30 UTC
Labels: area-Infrastructure-libraries, untriaged
