### ISSUE TITLE
`Matrix4x4.CreateLookAt()` does not create a matrix with proper translation

### ISSUE THREAD

**Issue by sunkin351** [dotnet/runtime#34859] opened 2020-04-11 22:14 UTC
I attempted to use this method to create a proper lookat matrix for Vulkan, went to render, and found that the rendered geometry wasn't properly translated away from the camera.

I ported GLM's LookAt function to C# which translated the geometry properly away from the camera to make sure there was not a bug in my code.

Reference glm implementation:
```cs
public static Matrix4x4 glmCreateLookAt(Vector3 cameraPosition, Vector3 cameraTarget, Vector3 cameraUpVector)
{
    var f = Vector3.Normalize(cameraTarget - cameraPosition);
    var s = Vector3.Normalize(Vector3.Cross(f, cameraUpVector));
    var u = Vector3.Cross(s, f);

    Matrix4x4 result = Matrix4x4.Identity;

    result.M11 = s.X;
    result.M12 = s.Y;
    result.M13 = s.Z;

    result.M21 = u.X;
    result.M22 = u.Y;
    result.M23 = u.Z;

    result.M31 = -f.X;
    result.M32 = -f.Y;
    result.M33 = -f.Z;

    result.M41 = -Vector3.Dot(s, cameraPosition);
    result.M42 = -Vector3.Dot(u, cameraPosition);
    result.M43 = Vector3.Dot(f, cameraPosition);

    return result;
}
```

**Comment by tannergooding** [comment] 2020-04-12 00:51
There are both `left-handed` (https://github.com/microsoft/DirectXMath/blob/master/Inc/DirectXMathMatrix.inl#L2044-L2066) and `right-handed` (https://github.com/microsoft/DirectXMath/blob/master/Inc/DirectXMathMatrix.inl#L2057-L2066) implementations.

They are functionally similar but with `f` being inversed. That is:
* in `left-handed` you do `target - position`
* in `right-handed` you do `position - target`

`glmCreateLookAt` is doing `left-handed` while `Matrix4x4.CreatelookAt` is doing `right-handed`. I wasn't around for the original implementation but I imagine that `System.Numerics` uses a `right-handed` coordinate system by default in order to match the behavior of XNA.
It might be worth a proposal to have overloads that make the handedness explicit, such as is provided in the DirectX Math Library.

**Comment by sunkin351** [comment] 2020-04-12 02:42
How do we reverse "handedness" in the meantime? And being that XNA is discontinued at this time, do you think we can, you know, reverse the handedness of this method?

**Comment by tannergooding** [comment] 2020-04-12 15:41
> And being that XNA is discontinued at this time, do you think we can, you know, reverse the handedness of this method?

I don't think that breaking change is worth it. Various engines use one of the handedness or the other and there isn't really a "correct" default. Even between DirectX, Vulkan, and OpenGL, they all use a different handedness and/or origin which impacts how your vertices are rendered, the default winding order, etc.

Instead, we should likely just update the documentation to explicitly call out the handedness and potentially expose helper functions that support the other handedness.

> How do we reverse "handedness" in the meantime

A new function is needed since the position is used more than once in the algorithm

**Comment by tannergooding** [comment] 2021-01-15 18:07
Closing as this is "by design". If someone want's to create a proposal for the other handedness, please open a new proposal following the API proposal template: https://github.com/dotnet/runtime/issues/new?assignees=&labels=api-suggestion&template=02_api_proposal.md

**Closed by tannergooding** 2021-01-15 18:07 UTC
Labels: area-System.Numerics
