### ISSUE TITLE
[NativeAOT] PlatformNotSupportedException when creating an array

### ISSUE THREAD

**Issue by SomeAnonDev** [dotnet/runtime#74299] opened 2022-08-20 21:26 UTC
The following code produces a ``PlatformNotSupportedException`` when compiled using the NativeAOT toolchain with all the default settings:
```csharp
var a = new[] { 42, 42, 42 };
Console.WriteLine(a.Length);
```
```
Unhandled Exception: System.PlatformNotSupportedException: Operation is not supported on this platform.
   at Internal.Runtime.CompilerHelpers.ThrowHelpers.ThrowPlatformNotSupportedException() + 0x24
   at Program.<Main>$(String[]) + 0x9
   at dotnet7aot!<BaseAddress>+0x1b3f13
```

Whether it crashes or not somehow depends on the contents of the array. For instance, this code will run just fine:
```csharp
var a = new[] { 0, 42, 42 };
Console.WriteLine(a.Length);
```

csproj:
```csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

</Project>
```

Platform: win-x64
SDK: 7.0.100-preview.7.22377.5
ILCompiler: 7.0.0-preview.7.22375.6

**Comment by teo-tsirpanis** [comment] 2022-08-20 21:36
Duplicate of dotnet/roslyn#62864.

**Closed by teo-tsirpanis** 2022-08-20 21:36 UTC
Labels: untriaged, area-NativeAOT-coreclr
