### ISSUE TITLE
Test failure JIT\\Methodical\\eh\\leaves\\oponerror_ro\\oponerror_ro.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#62695] opened 2021-12-13 01:05 UTC
Run: [runtime-coreclr outerloop 20211212.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1509234&view=ms.vss-test-web.build-test-results-tab&runId=42982078&resultId=106075&paneView=debug)

Failed test:
```
R2R-CG2 windows arm Checked @ Windows.10.Arm64v8.Open

- JIT\\Methodical\\eh\\leaves\\oponerror_ro\\oponerror_ro.cmd

```
**Error message:**
```
Could Not Find D:\h\w\B8920997\w\B3B50939\e\JIT\Methodical\eh\leaves\oponerror_ro\IL-CG2\composite-r2r.dll
Could Not Find D:\h\w\B8920997\w\B3B50939\e\JIT\Methodical\eh\leaves\oponerror_ro\common.dll.rsp
Fatal error. Internal CLR error. (0x80131506)
at System.SZArrayHelper.GetEnumerator[Internal.JitInterface.CorJitFlag, ILCompiler.ReadyToRun, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null]
at Internal.JitInterface.CorInfoImpl.getJitFlags(Internal.JitInterface.CORJIT_FLAGS ByRef, UInt32)
at Internal.JitInterface.CorInfoImpl._getJitFlags(IntPtr, IntPtr*, Internal.JitInterface.CORJIT_FLAGS*, UInt32)
at Internal.JitInterface.CorInfoImpl.JitCompileMethod(IntPtr ByRef, IntPtr, IntPtr, IntPtr, Internal.JitInterface.CORINFO_METHOD_INFO ByRef, UInt32, IntPtr ByRef, UInt32 ByRef)
at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(ILCompiler.DependencyAnalysis.IMethodNode, Internal.IL.MethodIL)
at Internal.JitInterface.CorInfoImpl.CompileMethod(ILCompiler.DependencyAnalysis.ReadyToRun.MethodWithGCInfo, ILCompiler.Logger)
at ILCompiler.ReadyToRunCodegenCompilation.<ComputeDependencyNodeDependencies>b__35_0(ILCompiler.DependencyAnalysisFramework.DependencyNodeCore1<ILCompiler.DependencyAnalysis.NodeFactory>) at System.Threading.Tasks.Parallel+<>c__DisplayClass33_02[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForEachWorker>b__0(Int32)
at System.Threading.Tasks.Parallel+<>c__DisplayClass19_0`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef, Int32, Boolean ByRef)
at System.Threading.Tasks.TaskReplicator+Replica.Execute()
at System.Threading.Tasks.TaskReplicator+Replica+<>c.<.ctor>b__4_0(System.Object)
at System.Threading.Tasks.Task.InnerInvoke()
at System.Threading.Tasks.Task+<>c.<.cctor>b__271_0(System.Object)
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
at System.Threading.Thread.StartCallback()

Return code:      1
Raw output file:      D:\h\w\B8920997\w\B3B50939\uploads\Reports\JIT.Methodical\eh\leaves\oponerror_ro\oponerror_ro.output.txt
Raw output:
BEGIN EXECUTION
common.dll
oponerror_ro.dll
2 file(s) copied.
Response file: D:\h\w\B8920997\w\B3B50939\e\JIT\Methodical\eh\leaves\oponerror_ro\common.dll.rsp
D:\h\w\B8920997\w\B3B50939\e\JIT\Methodical\eh\leaves\oponerror_ro\IL-CG2\common.dll
-o:D:\h\w\B8920997\w\B3B50939\e\JIT\Methodical\eh\leaves\oponerror_ro\common.dll
--targetarch:arm
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\B8920997\p\System..dll
-r:D:\h\w\B8920997\p\Microsoft..dll
-r:D:\h\w\B8920997\p\mscorlib.dll
-r:D:\h\w\B8920997\p\netstandard.dll
-O
" "dotnet" "D:\h\w\B8920997\p\crossgen2\crossgen2.dll" @"D:\h\w\B8920997\w\B3B50939\e\JIT\Methodical\eh\leaves\oponerror_ro\common.dll.rsp"   -r:D:\h\w\B8920997\w\B3B50939\e\JIT\Methodical\eh\leaves\oponerror_ro\IL-CG2*.dll"
Crossgen2 failed with exitcode - -1073741819
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\B8920997\p
D:\h\w\B8920997\w\B3B50939\e\JIT\Methodical\eh\leaves\oponerror_ro\oponerror_ro.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_Methodical._eh_leaves_oponerror_ro_oponerror_ro_._eh_leaves_oponerror_ro_oponerror_ro_cmd()
```

**Comment by am11** [comment] 2021-12-13 17:02
Looks like this CG2 failure occurred for the commit which replaced old style intrinsics (https://github.com/dotnet/runtime/commit/daa2965c8d8205168cb7e60ce3e0c723ec817ab5), but then this test (and the other from https://github.com/dotnet/runtime/issues/62696) passed in subsequent runs. Either it was an intermittent failure or the build used some old component (clue: JIT interface identifier was changed).

cc @jkotas, @EgorBo

aside, the tag should be <kbd>arch-arm64</kbd> (instead of 32)

**Comment by EgorBo** [comment] 2021-12-13 17:12
> aside, the tag should be arch-arm64 (instead of 32)

Should it? it happens on `R2R-CG2 windows arm Checked @ Windows.10.Arm64v8.Open` which test arm32, doesn't it?

**Comment by am11** [comment] 2021-12-13 17:14
Ah, right (I was focusing on the part after `@` :grin:)

**Comment by trylek** [comment] 2022-04-04 20:38
Closing as duplicate of: https://github.com/dotnet/runtime/issues/65170

**Closed by trylek** 2022-04-04 20:38 UTC
Labels: arch-arm32, os-windows, area-crossgen2-coreclr, untriaged
