### ISSUE TITLE
[Mono][AOT][LLVM][Linux] JIT.Performance.XUnitWrapper Test Failure SIGSEGV

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#58556] opened 2021-09-02 13:46 UTC
Mono llvmaot Pri0 Runtime Tests Run Linux x64 Release
```
Expected: 100
Actual: 134
```

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1336212&view=logs&j=e8cc9eb8-98f1-55f3-b6df-6c384ccb39b6&t=7ec1aa02-369c-51d1-7a60-8e709c4509a9
Log: https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-57208-merge-b7ea4aa9157c441895/JIT/1/console.df1d5d3b.log?sv=2019-07-07&se=2021-09-22T01%3A43%3A29Z&sr=c&sp=rl&sig=eliHVcGixgIxDKYloFFj%2FCaBznbxvxeANx6NmJhAhXA%3D

Error:
```
      Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
      0x00007f229f61b32a in __waitpid (pid=10819, stat_loc=0x7ffdbc78ba00, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
      30../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
```

**Comment by fanyang-mono** [comment] 2021-09-02 14:11
The error message is `../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory`.

**Comment by lambdageek** [comment] 2021-09-02 16:54
This is a duplicate of #58062 most likely.

The stack trace looks similar:

```
       Thread 1 (Thread 0x7f229fc42740 (LWP 10691)):
        #0  0x00007f229f61b32a in __waitpid (pid=10819, stat_loc=0x7ffdbc78ba00, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
        #1  0x00007f229ccf8e87 in dump_native_stacktrace (signal=<optimized out>, mctx=<optimized out>) at /__w/1/s/src/mono/mono/mini/mini-posix.c:842
        #2  mono_dump_native_crash_info (signal=<optimized out>, mctx=0x7ffdbc78c570, info=<optimized out>) at /__w/1/s/src/mono/mono/mini/mini-posix.c:869
        #3  0x00007f229cc9bb9e in mono_handle_native_crash (signal=0x7f229e194cd3 "SIGSEGV", mctx=0x7ffdbc78c570, info=0x7ffdbc78c830) at /__w/1/s/src/mono/mono/mini/mini-exceptions.c:2940
        #4  0x00007f229cbfcc71 in mono_sigsegv_signal_handler_debug (_dummy=11, _info=0x7ffdbc78c830, context=0x7ffdbc78c700, debug_fault_addr=0x8) at /__w/1/s/src/mono/mono/mini/mini-runtime.c:3717
        #5  <signal handler called>
        #6  copy_object_no_checks (obj=0x7f229bcf1680, queue=0x7ffdbc78cf40) at /__w/1/s/src/mono/mono/mini/../sgen/sgen-copy-object.h:69
        #7  0x00007f229cbdbe10 in simple_nursery_serial_copy_object_from_obj (obj_slot=0x7f229a023598, queue=0x7ffdbc78cf40) at /__w/1/s/src/mono/mono/mini/../sgen/sgen-minor-copy-object.h:238
        #8  simple_nursery_serial_scan_object (full_object=<optimized out>, desc=<optimized out>, queue=0x7ffdbc78cf40) at /__w/1/s/src/mono/mono/mini/../sgen/sgen-scan-object.h:64
        #9  0x00007f229cbdceb7 in simple_nursery_serial_drain_gray_stack (queue=0x7ffdbc78cf40) at /__w/1/s/src/mono/mono/mini/../sgen/sgen-minor-scan-object.h:142
        #10 0x00007f229cbb28ab in sgen_drain_gray_stack (ctx=...) at /__w/1/s/src/mono/mono/sgen/sgen-gc.c:578
        #11 finish_gray_stack (generation=0, ctx=...) at /__w/1/s/src/mono/mono/sgen/sgen-gc.c:1140
        #12 0x00007f229cbb1a19 in collect_nursery (reason=0x7f229e1962ef "Nursery full", is_overflow=<optimized out>) at /__w/1/s/src/mono/mono/sgen/sgen-gc.c:1932
        #13 0x00007f229cbadd63 in sgen_perform_collection_inner (requested_size=<optimized out>, generation_to_collect=<optimized out>, reason=<optimized out>, forced_serial=<optimized out>, stw=<optimized out>) at /__w/1/s/src/mono/mono/sgen/sgen-gc.c:2656
        #14 sgen_perform_collection (requested_size=3176, generation_to_collect=0, reason=0x7f229e1962ef "Nursery full", forced_serial=0, stw=1) at /__w/1/s/src/mono/mono/sgen/sgen-gc.c:2768
        #15 0x00007f229cbadb63 in sgen_ensure_free_space (size=3176, generation=<optimized out>) at /__w/1/s/src/mono/mono/sgen/sgen-gc.c:2622
        #16 0x00007f229cba1ce6 in sgen_alloc_obj_nolock (vtable=0x555e04e771d0, size=3176) at /__w/1/s/src/mono/mono/sgen/sgen-alloc.c:258
        #17 0x00007f229cb719f7 in mono_gc_alloc_vector (vtable=0x555e04e771d0, size=3176, max_length=131) at /__w/1/s/src/mono/mono/metadata/sgen-mono.c:1340
        #18 0x000000004114dd6b in ?? ()
        #19 0x00007f229c000438 in ?? ()
        #20 0x0000000000000083 in ?? ()
        #21 0x0000555e07c10540 in ?? ()
        #22 0x0000000000000083 in ?? ()
        #23 0x0000555e04e771d0 in ?? ()
        #24 0x0000555e01dd7d90 in ?? ()
        #25 0x0000555e04e771d0 in ?? ()
        #26 0x00007ffdbc78d150 in ?? ()
        #27 0x0000000000000000 in ?? ()
        /datadisks/disk1/work/B0D00948/w/AF4C09CB/e/JIT/Performance/CodeQuality/Roslyn/CscBench/CscBench.sh: line 355: 10691 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
```

**Comment by lambdageek** [comment] 2021-09-02 16:56
in fact it's identical.  definitely a dupe.

**Closed by lambdageek** 2021-09-02 16:56 UTC
Labels: area-GC-mono
