### ISSUE TITLE
Enabled AOT blazor Wasm Precompilation fails.

### ISSUE THREAD

**Issue by Bala-tec** [dotnet/runtime#61565] opened 2021-11-14 05:35 UTC
### Description

Upgraded the project to .net6, everything works fine. But Enabling the AOT makes publish command fails

Attached the msbuild log file for reference.
[msbuild.zip](https://github.com/dotnet/runtime/files/7533232/msbuild.zip)
.

### Reproduction Steps

Publish the Application using `dotnet publish -c Release`. AOT precompiling fails.

### Expected behavior

Publish the wasm project with AOT.

### Actual behavior

precompilation fails while aoting the `Syncfusion.Blazor.Diagram.dll`

### Configuration

- dotnet: 6.0.100
- OS: Windows 10 x64

**Comment by radical** [comment] 2021-11-15 01:55
Closing as a dupe of https://github.com/dotnet/runtime/issues/61053 .

It fails because `mono-aot-cross` runs out of stack space, and was fixed on `main` but didn't make it into `6.0`. You can either try the 7.0*alpha build from https://github.com/dotnet/installer/#installers-and-binaries or wait for 6.0.1 release.

Also, see https://github.com/dotnet/runtime/issues/61053#issuecomment-959612011 for a possible workaround.

**Closed by radical** 2021-11-15 01:55 UTC
Labels: arch-wasm, untriaged, area-Codegen-AOT-mono
