### ISSUE TITLE
.net core missing many methods

### ISSUE THREAD

**Issue by TKT2016** [dotnet/runtime#36863] opened 2020-05-20 07:49 UTC
# .net core missing many methods

.net core missing many methods.These are very important.

# General
**AppDomain**
missing method
DefineDynamicAssembly(AssemblyName name, AssemblyBuilderAccess access);

 
**AssemblyBuilder**
missing 
DefineDynamicModule(string name, string fileName, bool emitSymbolInfo);
SetEntryPoint(MethodInfo entryMethod, PEFileKinds fileKind);
Save(string assemblyFileName);

 
**ModuleBuilder**
missing method
DefineDocument(string url, Guid language, Guid languageVendor, Guid documentType);

 
**ILGenerator**
missing method
MarkSequencePoint(ISymbolDocumentWriter document, int startLine, int startColumn, int endLine, int endColumn);

 
**LocalBuilder**
missing method
SetLocalSymInfo(string name);

 
missing enum type: 
**PEFileKinds**
 
**AssemblyBuilderAccess**
missing values:
Save,
RunAndSave,
ReflectionOnly

**Comment by GrabYourPitchforks** [comment] 2020-05-22 06:16
Dupe of https://github.com/dotnet/runtime/issues/28206, https://github.com/dotnet/runtime/issues/15704, and other related issues;

**Closed by GrabYourPitchforks** 2020-05-22 06:16 UTC
Labels: area-Meta, untriaged
