### ISSUE TITLE
[API Proposal]: Support the `decimal` type in Attribute values

### ISSUE THREAD

**Issue by robertmclaws** [dotnet/runtime#63060] opened 2021-12-22 05:30 UTC
### Description

Because the CLI does not support the decimal type in attribute values, it makes unit testing of math functions overly complicated. See: https://github.com/microsoft/testfx-docs/issues/79

### Reproduction Steps

```cs
[DataTestMethod]
[DataRow(1m, 2m, 3m)]
[DataRow(1, 2, 3)]
[DataRow(1.0, 2.0, 3.0)]
public void CheckIt(decimal num1, decimal num2, decimal expected)
{
}
```

### Expected behavior

I would expect this code to compile properly.

### Actual behavior

"error CS0182: An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type."

### Known Workarounds

```cs

        //RWM: Whew, this is ugly.
        public static IEnumerable<object[]> TestMethod1Data =>
            // one item per data row
            new[] {
                // one item per parameter, you need to specify the object type
                new object[] { 1m, 2m, 3m },
                new object[] { 13.5m, 178.8m, 192.3m }
            };

        [TestMethod]
        // you can also use a method, but it defaults to property
        [DynamicData(nameof(TestMethod1Data))]
        public void TestMethod1(decimal l, decimal r, decimal expected)
        {
            Assert.AreEqual(expected, l  +  r);
        }
    }
```

### Configuration

Happens in .NET 6.0 and earlier.

**Comment by jkotas** [comment] 2021-12-22 16:44
Duplicate of https://github.com/dotnet/runtime/issues/7426 and https://github.com/dotnet/runtime/issues/4525

**Closed by jkotas** 2021-12-22 16:44 UTC
Labels: area-System.Runtime, untriaged
