### ISSUE TITLE
MemoryCache PostEvictionCallback unexpectedly using the wrong ILogger scope

### ISSUE THREAD

**Issue by WolfspiritM** [dotnet/runtime#69428] opened 2022-05-17 10:58 UTC
### Description

We currently had a big issue where the logging was messing up data and exceptions from one message ended up using the wrong logger scope. After tracing the issue back to the source we figured out that the reason is the implementation of the MemoryCache and the PostEvictionCallbacks.

Lets say we get a bulk of messages and iterate over them. At first we define a new scope with BeginScope("{MessageId}", messageId) and we then use TryGetValue on the cache to find an item in the cache and if it's not there we add it with a callback that logs when the item gets removed.

However the evictioncallback is called when another message is doing TryGetValue. This causes the evictioncallback getting triggered with the wrong ILogger scope and messing up logs.

In our case we disposed an FTP Client once it got evicted from cache after some time and if an exception happens we logged it. This issue caused the log to appear for a completly different tenant and messageid resulting in username and address (which got logged via message) being leaked to another tenant.

There also is no way to "copy" the scope over to the callback as far as I can see.

### Reproduction Steps

```cs
var builder = WebApplication.CreateBuilder();
builder.Logging.AddSimpleConsole((c) => { c.IncludeScopes = true; c.SingleLine = true; });
builder.Services.AddMemoryCache(c => c.ExpirationScanFrequency = TimeSpan.FromMilliseconds(1));

var app = builder.Build();

var logger = app.Services.GetService<ILogger<WebApplication>>();
var memoryCache = app.Services.GetService<IMemoryCache>();

for (var i = 0; i < 10; i++)
{
	var id = i;
	var mid = "message" + id;
	using (logger.BeginScope("{MessageId}", mid))
	{
		logger.LogWarning("Executing... " + mid);
		Thread.Sleep(500);
		var resu = memoryCache.TryGetValue(mid, out var res);
		var t = new MemoryCacheEntryOptions { AbsoluteExpirationRelativeToNow = TimeSpan.FromMilliseconds(1) };
		t.RegisterPostEvictionCallback((a,c,r,s) => {
			logger.LogWarning("Evicted. (Expected: " + mid + ")");
		});
		logger.LogWarning("Creating... " + mid);
		memoryCache.Set(mid, "test", t);
	}
}
```

### Expected behavior

```warn: Microsoft.AspNetCore.Builder.WebApplication[0] => message0 Evicted. (Expected: message0)```

### Actual behavior

```warn: Microsoft.AspNetCore.Builder.WebApplication[0] => message1 Evicted. (Expected: message0)```

**Comment by ericstj** [comment] 2022-07-27 05:51
If I understand correctly you were expecting the logging scope to be stored in the cache along side the cached entry and you expect that scope to be restored when the entry is evicted.  I don't believe that this is how the cache works.  It's not capturing the logging scope as far as I can tell.  @maryamariyan @Tratcher -- is that correct?

**Comment by eerhardt** [comment] 2022-07-27 23:13
@ericstj's analysis above is correct. The way to think about it is that the scope that was used when you added the cache entry has been disposed and is long gone by the time the entry has been evicted.

In your repro code:
```C#
        for (var i = 0; i < 10; i++)
        {
            var id = i;
            var mid = "message" + id;
            using (logger.BeginScope("{MessageId}", mid))
            {
                logger.LogWarning("Executing... " + mid);
                Thread.Sleep(500);
                var resu = memoryCache.TryGetValue(mid, out var res);
                var t = new MemoryCacheEntryOptions { AbsoluteExpirationRelativeToNow = TimeSpan.FromMilliseconds(1) };
                t.RegisterPostEvictionCallback((a, c, r, s) => {
                    logger.LogWarning("Evicted. (Expected: " + mid + ")");
                });
                logger.LogWarning("Creating... " + mid);
                memoryCache.Set(mid, "test", t);
            }
        }
```

Each iteration through the loop creates and disposes the scope. So on the `n`th iteration, the scope from `n - 1` iteration has already been disposed. And the scope on the current `logger` (which is a constant through the loop) has already changed to the new scope.

This is by design. If you need to store certain information from the request that added the entry to the cache to use when it is evicted, you should store that information on the entry. That way you access that information reliably no matter when the entry is evicted.

**Comment by Tratcher** [comment] 2022-08-09 23:10
One thing to consider here would be to make sure eviction callbacks were invoked in a way that that didn't flow any scopes, the original nor the current one.

**Comment by eerhardt** [comment] 2022-08-09 23:27
>  make sure eviction callbacks were invoked in a way that that didn't flow any scopes

Is that even possible without a new feature to `ILogger`?

**Comment by Tratcher** [comment] 2022-08-10 00:27
Scopes flow as asynclocals so dispatching the eviction callback should allow you suppress them.

**Comment by eerhardt** [comment] 2022-08-12 16:39
Re-opening to see if we can dispatch "UnsafeQueueUserWorkItem" to clear out the AsyncLocals during cache eviction:

https://github.com/dotnet/runtime/blob/e71a9583b4d6c9bd97edd87cda7f98f232f63530/src/libraries/Microsoft.Extensions.Caching.Memory/src/CacheEntry.CacheEntryTokens.cs#L105-L112

**Comment by tarekgh** [comment] 2022-08-24 21:34
> Scopes flow as asynclocals so dispatching the eviction callback should allow you suppress them.

I don't think clearing up all asynclocals during the eviction callback is correct. Currently there are some runtime properties stored in asynclocals and it will not be good to clear those during any calls. Example of that `Culture.CurrentCulture` and `Activity.Current`. clearing those can affect the tracing and globalization behavior inside the eviction callback.

**Comment by adamsitnik** [comment] 2023-11-15 11:34
I don't see a possibility to implement this feature request without sacrificing performance. Since it has not received any upvotes or comments from other users for more than a year I am going to close it. Thanks!

**Closed by adamsitnik** 2023-11-15 11:34 UTC
Labels: area-Extensions-Caching
