### ISSUE TITLE
Use wasm and js integration for unsupported systems

### ISSUE THREAD

**Issue by sajjadarashhh** [dotnet/runtime#89500] opened 2023-07-26 12:04 UTC
### Description

In our country people cant used latest technology utilities
For example we have customer with windows 7 and cpu dual core!
We cant force them to bought new system for our applications
We must be consider continued support them
In blazor must be used new features that check if browser is not compatible with blazor requirements like simd that our customers doesnt have problem with .net 7 but in .net 8 with this requirement many of them cant be used our system
We must be avoid to happen that problems when migrating from old version to new version

### Reproduction Steps

Migrate from .net 7 to .net 8 and use windows 7

### Expected behavior

Application is nit running

### Actual behavior

Application must be check browser version and run specific version of that

**Comment by lewing** [comment] 2023-07-26 17:59
this appears to be a duplicate of https://github.com/dotnet/runtime/issues/89028 and the discussion is happening there

**Closed by lewing** 2023-07-26 17:59 UTC
Labels: arch-wasm, area-VM-meta-mono

**Comment by pavelsavara** [comment] 2023-07-26 18:04
[Windows 7 support ended on January 14, 2020](https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962)

You can use wasm-tools workload and recompille the application without SIMD and EH instructions.
- I'm describing basic how to here https://github.com/dotnet/runtime/pull/89469
- detection is here https://github.com/dotnet/runtime/pull/89387
- And compilation s being fixed here https://github.com/dotnet/runtime/pull/89433 and https://github.com/dotnet/runtime/pull/89502
