### ISSUE TITLE
JsonDocument not thread safe at high load

### ISSUE THREAD

**Issue by JustinCanton** [dotnet/runtime#87483] opened 2023-06-13 15:03 UTC
### Description

I have found that the JsonDocument type is not thread safe at very high load. When testing, trying to get a property of a specific name fails if the json document being used is shared across multiple threads.

I wasn't able to find anything saying that the JsonDocument isn't thread safe, so I am not sure if this is a bug, or if this is expected functionality that just isn't mentioned.

### Reproduction Steps

I have 3 xUnit test cases to showcase the different functionalities. The first test case uses the built in NameEquals method, and it works on a shared JsonDocument
```
[Fact]
public async Task NameComparison_WithNameEquals_ReturnsCorrectJsonElement()
{
	var document = JsonDocument.Parse("{\"testField1\":\"1\", \"testField2\": \"2\" }", new JsonDocumentOptions { AllowTrailingCommas = true, CommentHandling = JsonCommentHandling.Skip });

	var taskList = new List<Task>();
	for (var i = 0; i < 1000000; i++)
	{
		var task = new Task(() =>
		{
			var property = document.RootElement.EnumerateObject().FirstOrDefault(p => p.NameEquals("testField2"));

			property.Value.ValueKind.Should().NotBe(JsonValueKind.Undefined);
			property.Name.Should().Be("testField2");
		});

		task.Start();
		taskList.Add(task);
	}

	await Task.WhenAll(taskList).ConfigureAwait(false);
}
```

The next test cases uses individual JsonDocuments for each thread, and does a case insensitive check on the Name property instead of using NameEquals, and it also works as expected
```
[Fact]
public async Task NameComparison_WithCaseInsensitivityAndNewJsonDoc_ReturnsCorrectJsonElement()
{
	var taskList = new List<Task>();
	for (var i = 0; i < 1000000; i++)
	{
		var task = new Task(() =>
		{
			var document = JsonDocument.Parse("{\"testField1\":\"1\", \"testField2\": \"2\" }", new JsonDocumentOptions { AllowTrailingCommas = true, CommentHandling = JsonCommentHandling.Skip });
			var property = document.RootElement.EnumerateObject().FirstOrDefault(p => string.Equals(p.Name, "TestField2", StringComparison.OrdinalIgnoreCase));

			property.Value.ValueKind.Should().NotBe(JsonValueKind.Undefined);
			property.Name.Should().Be("testField2");

		});

		task.Start();
		taskList.Add(task);
	}

	await Task.WhenAll(taskList).ConfigureAwait(false);
}
```

The last test case uses a shared JsonDocument for all threads, and does a case insensitive check on the Name property instead of using NameEquals, and it **fails**
```
[Fact]
public async Task NameComparison_WithCaseInsensitivity_ReturnsIncorrectJsonElement()
{
	var document = JsonDocument.Parse("{\"testField1\":\"1\", \"testField2\": \"2\" }", new JsonDocumentOptions { AllowTrailingCommas = true, CommentHandling = JsonCommentHandling.Skip });

	var taskList = new List<Task>();
	for (var i = 0; i < 1000000; i++)
	{
		var task = new Task(() =>
		{
			var property = document.RootElement.EnumerateObject().FirstOrDefault(p => string.Equals(p.Name, "TestField2", StringComparison.OrdinalIgnoreCase));

			property.Value.ValueKind.Should().NotBe(JsonValueKind.Undefined);
			property.Name.Should().Be("testField2");
		});

		task.Start();
		taskList.Add(task);
	}

	await Task.WhenAll(taskList).ConfigureAwait(false);
}
```

### Expected behavior

The JsonDocument should be thread safe and able to return the correct property when searching.

### Actual behavior

The JsonDocument is not thread safe will return incorrect data at higher loads.

### Configuration

**Which version of .NET is the code running on?**
.net6.0

**What OS and version, and what distro if applicable?**
Windows 10

**What is the architecture (x64, x86, ARM, ARM64)?**
x64 and x86

**Do you know whether it is specific to that configuration?**
I am not aware

**Comment by krwq** [comment] 2023-06-13 16:33
Can you try 8.0 preview? We've fixed several threading issues between 6.0 and now

**Comment by eiriktsarpalis** [comment] 2023-06-13 16:49
Based on the usage pattern I would say it's a duplicate of https://github.com/dotnet/runtime/issues/77421. I tried running your repro using the most recent .NET 8 preview and couldn't repro the failure. Would it be possible to try on your side with the most recent preview?

**Comment by JustinCanton** [comment] 2023-06-13 17:38
It seems like you all are correct. I can't reproduce on the net8.0 preview. I even tried to increase the number of tasks created and it still wasn't reproducible. So it doesn't seems to be a problem in net8.0.

Would this be something that should be fixed in net6.0 as an LTS release? Or is the recommendation to update to using net8.0?

**Comment by eiriktsarpalis** [comment] 2023-06-13 17:58
I wouldn't think this meets the bar for .NET 6/7 servicing, but there's no simple workaround I know of that doesn't involve synchronized access. cc @ericstj for a second opinion.

**Comment by ericstj** [comment] 2023-06-14 15:45
Locking around access seems like a feasible workaround.  It looks to me like we are adding a thread-safety guarantee in 8.0 - which I am interpreting as a feature.

FWIW: most .NET types are not thread-safe by default because thread safety typically comes at a cost.  Adding thread safety to a type that's not documented as thread safe is seen as a feature and we should test, document, and maintain that support once we commit to it.

**Comment by eiriktsarpalis** [comment] 2023-06-14 15:48
> Adding thread safety to a type that's not documented as thread safe is seen as a feature and we should test, document, and maintain that support once we commit to it.

The .NET 6 docs claim that it is thread safe https://learn.microsoft.com/en-us/dotnet/api/system.text.json.nodes.jsonobject?view=net-6.0#remarks when no explicit modifications are being made to the type.

**Comment by eiriktsarpalis** [comment] 2023-06-22 13:05
Closing as duplicate of https://github.com/dotnet/runtime/issues/76440.

**Closed by eiriktsarpalis** 2023-06-22 13:05 UTC
Labels: area-System.Text.Json, needs-further-triage
