### ISSUE TITLE
Test failure JIT\\Methodical\\Arrays\\lcs\\_speed_rellcsbox\\_speed_rellcsbox.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#61646] opened 2021-11-16 01:29 UTC
Run: [runtime-coreclr outerloop 20211115.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1469873&view=ms.vss-test-web.build-test-results-tab&runId=42165126&resultId=106962&paneView=debug)

Failed test:
```
R2R-CG2 windows arm Checked @ Windows.10.Arm64v8.Open

- JIT\\Methodical\\Arrays\\lcs\\_speed_rellcsbox\\_speed_rellcsbox.cmd

```
**Error message:**
```
Could Not Find D:\h\w\AA47097D\w\A9F20918\e\JIT\Methodical\Arrays\lcs_speed_rellcsbox\IL-CG2\composite-r2r.dll
Could Not Find D:\h\w\AA47097D\w\A9F20918\e\JIT\Methodical\Arrays\lcs_speed_rellcsbox_speed_rellcsbox.dll.rsp
Fatal error. Internal CLR error. (0x80131506)
at System.SZArrayHelper.GetEnumerator[Internal.JitInterface.CorJitFlag, ILCompiler.ReadyToRun, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null]
at Internal.JitInterface.CorInfoImpl.getJitFlags(Internal.JitInterface.CORJIT_FLAGS ByRef, UInt32)
at Internal.JitInterface.CorInfoImpl._getJitFlags(IntPtr, IntPtr*, Internal.JitInterface.CORJIT_FLAGS*, UInt32)
at Internal.JitInterface.CorInfoImpl.JitCompileMethod(IntPtr ByRef, IntPtr, IntPtr, IntPtr, Internal.JitInterface.CORINFO_METHOD_INFO ByRef, UInt32, IntPtr ByRef, UInt32 ByRef)
at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(ILCompiler.DependencyAnalysis.IMethodNode, Internal.IL.MethodIL)
at Internal.JitInterface.CorInfoImpl.CompileMethod(ILCompiler.DependencyAnalysis.ReadyToRun.MethodWithGCInfo, ILCompiler.Logger)
at ILCompiler.ReadyToRunCodegenCompilation.<ComputeDependencyNodeDependencies>b__35_0(ILCompiler.DependencyAnalysisFramework.DependencyNodeCore1<ILCompiler.DependencyAnalysis.NodeFactory>) at System.Threading.Tasks.Parallel+<>c__DisplayClass33_02[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForEachWorker>b__0(Int32)
at System.Threading.Tasks.Parallel+<>c__DisplayClass19_0`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef, Int32, Boolean ByRef)
at System.Threading.Tasks.TaskReplicator+Replica.Execute()
at System.Threading.Tasks.TaskReplicator+Replica+<>c.<.ctor>b__4_0(System.Object)
at System.Threading.Tasks.Task.InnerInvoke()
at System.Threading.Tasks.Task+<>c.<.cctor>b__271_0(System.Object)
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
at System.Threading.Thread.StartCallback()

Return code:      1
Raw output file:      D:\h\w\AA47097D\w\A9F20918\uploads\Reports\JIT.Methodical\Arrays\lcs_speed_rellcsbox_speed_rellcsbox.output.txt
Raw output:
BEGIN EXECUTION
_speed_rellcsbox.dll
1 file(s) copied.
Response file: D:\h\w\AA47097D\w\A9F20918\e\JIT\Methodical\Arrays\lcs_speed_rellcsbox\_speed_rellcsbox.dll.rsp
D:\h\w\AA47097D\w\A9F20918\e\JIT\Methodical\Arrays\lcs_speed_rellcsbox\IL-CG2_speed_rellcsbox.dll
-o:D:\h\w\AA47097D\w\A9F20918\e\JIT\Methodical\Arrays\lcs_speed_rellcsbox\_speed_rellcsbox.dll
--targetarch:arm
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\AA47097D\p\System..dll
-r:D:\h\w\AA47097D\p\Microsoft..dll
-r:D:\h\w\AA47097D\p\mscorlib.dll
-r:D:\h\w\AA47097D\p\netstandard.dll
-O
" "dotnet" "D:\h\w\AA47097D\p\crossgen2\crossgen2.dll" @"D:\h\w\AA47097D\w\A9F20918\e\JIT\Methodical\Arrays\lcs_speed_rellcsbox\_speed_rellcsbox.dll.rsp"   -r:D:\h\w\AA47097D\w\A9F20918\e\JIT\Methodical\Arrays\lcs_speed_rellcsbox\IL-CG2*.dll"
Crossgen2 failed with exitcode - -1073741819
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\AA47097D\p
D:\h\w\AA47097D\w\A9F20918\e\JIT\Methodical\Arrays\lcs_speed_rellcsbox_speed_rellcsbox.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_Methodical._Arrays_lcs__speed_rellcsbox__speed_rellcsbox_._Arrays_lcs__speed_rellcsbox__speed_rellcsbox_cmd()
```

**Comment by VincentBu** [comment] 2021-11-24 01:08
Failed again in:[ runtime-coreclr outerloop 20211123.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1483101&view=ms.vss-test-web.build-test-results-tab&runId=42450866&resultId=108099&paneView=debug)

Failed test:
```
R2R-CG2 windows arm Checked @ Windows.10.Arm64v8.Open

- JIT\\Methodical\\VT\\callconv\\_speed_relvtret\\_speed_relvtret.cmd

```
**Error message:**
```
`Could Not Find D:\h\w\B60309E2\w\9D8E08B1\e\JIT\Methodical\VT\callconv_speed_relvtret\IL-CG2\composite-r2r.dll
Could Not Find D:\h\w\B60309E2\w\9D8E08B1\e\JIT\Methodical\VT\callconv_speed_relvtret_speed_relvtret.dll.rsp
Fatal error. Internal CLR error. (0x80131506)
at System.SZArrayHelper.GetEnumerator[Internal.JitInterface.CorJitFlag, ILCompiler.ReadyToRun, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null]
at Internal.JitInterface.CorInfoImpl.getJitFlags(Internal.JitInterface.CORJIT_FLAGS ByRef, UInt32)
at Internal.JitInterface.CorInfoImpl._getJitFlags(IntPtr, IntPtr*, Internal.JitInterface.CORJIT_FLAGS*, UInt32)
at Internal.JitInterface.CorInfoImpl.JitCompileMethod(IntPtr ByRef, IntPtr, IntPtr, IntPtr, Internal.JitInterface.CORINFO_METHOD_INFO ByRef, UInt32, IntPtr ByRef, UInt32 ByRef)
at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(ILCompiler.DependencyAnalysis.IMethodNode, Internal.IL.MethodIL)
at Internal.JitInterface.CorInfoImpl.CompileMethod(ILCompiler.DependencyAnalysis.ReadyToRun.MethodWithGCInfo, ILCompiler.Logger)
at ILCompiler.ReadyToRunCodegenCompilation.<ComputeDependencyNodeDependencies>b__35_0(ILCompiler.DependencyAnalysisFramework.DependencyNodeCore1<ILCompiler.DependencyAnalysis.NodeFactory>) at System.Threading.Tasks.Parallel+<>c__DisplayClass33_02[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForEachWorker>b__0(Int32)
at System.Threading.Tasks.Parallel+<>c__DisplayClass19_01[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef, Int32, Boolean ByRef) at System.Threading.Tasks.TaskReplicator+Replica.Execute() at System.Threading.Tasks.TaskReplicator+Replica+<>c.<.ctor>b__4_0(System.Object) at System.Threading.Tasks.Task.InnerInvoke() at System.Threading.Tasks.Task+<>c.<.cctor>b__271_0(System.Object) at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread) at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread) at System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(System.Threading.Tasks.Task, Boolean) at System.Threading.Tasks.TaskScheduler.TryRunInline(System.Threading.Tasks.Task, Boolean) at System.Threading.Tasks.Task.InternalRunSynchronously(System.Threading.Tasks.TaskScheduler, Boolean) at System.Threading.Tasks.Task.RunSynchronously(System.Threading.Tasks.TaskScheduler) at System.Threading.Tasks.TaskReplicator.Run[[System.Threading.Tasks.RangeWorker, System.Threading.Tasks.Parallel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](ReplicatableUserAction1<System.Threading.Tasks.RangeWorker>, System.Threading.Tasks.ParallelOptions, Boolean)
at System.Threading.Tasks.Parallel.ForWorker[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](Int32, Int32, System.Threading.Tasks.ParallelOptions, System.Action1<Int32>, System.Action2<Int32,System.Threading.Tasks.ParallelLoopState>, System.Func4<Int32,System.Threading.Tasks.ParallelLoopState,System.__Canon,System.__Canon>, System.Func1<System.__Canon>, System.Action1<System.__Canon>) at System.Threading.Tasks.Parallel.ForEachWorker[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Generic.IList1<System.__Canon>, System.Threading.Tasks.ParallelOptions, System.Action`1<System.__Canon>


Stack trace
   at JIT_Methodical._VT_callconv__speed_relvtret__speed_relvtret_._VT_callconv__speed_relvtret__speed_relvtret_cmd()
```

**Comment by trylek** [comment] 2022-04-04 20:38
Closing as duplicate of: https://github.com/dotnet/runtime/issues/65170

**Closed by trylek** 2022-04-04 20:38 UTC
Labels: os-windows, area-crossgen2-coreclr, untriaged
