### ISSUE TITLE
System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3 timeouts

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#101505] opened 2024-04-24 17:25 UTC
```log
System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success(fromVersion: 1.1, overrideHost: True) [FAIL]
      System.TimeoutException : The operation has timed out.
      Stack Trace:
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(55,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.AltSvc.cs(137,0): at System.Net.Http.Functional.Tests.HttpClientHandler_AltSvc_Test.AltSvc_Upgrade_Success(GenericLoopbackServer firstServer, Http3LoopbackServer secondServer, HttpClient client)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.AltSvc.cs(64,0): at System.Net.Http.Functional.Tests.HttpClientHandler_AltSvc_Test.AltSvc_Header_Upgrade_Success(Version fromVersion, Boolean overrideHost)
        --- End of stack trace from previous location ---
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Headers_Http3.SendAsync_UserAgent_CorrectlyWritten [FAIL]
      System.Net.Http.HttpRequestException : Connection handshake was canceled due to the configured timeout of 00:00:10 seconds elapsing. (127.0.0.1:52560)
      ---- System.Net.Quic.QuicException : Connection handshake was canceled due to the configured timeout of 00:00:10 seconds elapsing.
      Stack Trace:
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs(134,0): at System.Net.Http.ConnectHelper.ConnectQuicAsync(HttpRequestMessage request, DnsEndPoint endPoint, TimeSpan idleTimeout, SslClientAuthenticationOptions clientAuthenticationOptions, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectionPool/HttpConnectionPool.Http3.cs(162,0): at System.Net.Http.HttpConnectionPool.GetHttp3ConnectionAsync(HttpRequestMessage request, HttpAuthority authority, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectionPool/HttpConnectionPool.Http3.cs(174,0): at System.Net.Http.HttpConnectionPool.GetHttp3ConnectionAsync(HttpRequestMessage request, HttpAuthority authority, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectionPool/HttpConnectionPool.Http3.cs(85,0): at System.Net.Http.HttpConnectionPool.TrySendUsingHttp3Async(HttpRequestMessage request, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectionPool/HttpConnectionPool.cs(430,0): at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs(30,0): at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs(530,0): at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs(550,0): at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Headers.cs(63,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Headers.<>c__DisplayClass3_0.<<SendAsync_UserAgent_CorrectlyWritten>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(120,0): at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(90,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Net/Http/GenericLoopbackServer.cs(44,0): at System.Net.Test.Common.LoopbackServerFactory.<>c__DisplayClass6_0.<<CreateClientAndServerAsync>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Net/Http/Http3LoopbackServer.cs(116,0): at System.Net.Test.Common.Http3LoopbackServerFactory.CreateServerAsync(Func`3 funcAsync, Int32 millisecondsTimeout, GenericLoopbackOptions options)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Headers.cs(57,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Headers.SendAsync_UserAgent_CorrectlyWritten()
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace -----
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs(89,0): at System.Net.Quic.QuicConnection.<ConnectAsync>g__StartConnectAsync|2_0(QuicClientConnectionOptions options, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectHelper.cs(121,0): at System.Net.Http.ConnectHelper.ConnectQuicAsync(HttpRequestMessage request, DnsEndPoint endPoint, TimeSpan idleTimeout, SslClientAuthenticationOptions clientAuthenticationOptions, CancellationToken cancellationToken)
```
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=654860
Build error leg or test failing: System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success
Pull request: https://github.com/dotnet/runtime/pull/100094

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": [ "System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success", "System.TimeoutException" ],
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=654860
**Error message validated:** `[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success System.TimeoutException`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 4/24/2024 5:25:33 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[655562](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655562)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Cookies_Http3.GetAsync_DefaultCoookieContainer_NoCookieSent](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655562&view=ms.vss-test-web.build-test-results-tab&runId=16228160&resultId=217620)|dotnet/runtime#101527|
|[655408](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655408)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655408&view=ms.vss-test-web.build-test-results-tab&runId=16225078&resultId=217831)|dotnet/runtime#101469|
|[655420](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655420)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655420&view=ms.vss-test-web.build-test-results-tab&runId=16224860&resultId=214526)|dotnet/runtime#101480|
|[655401](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655401)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655401&view=ms.vss-test-web.build-test-results-tab&runId=16224288&resultId=217883)|dotnet/runtime#101378|
|[655365](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655365)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655365&view=ms.vss-test-web.build-test-results-tab&runId=16223678&resultId=209217)|dotnet/runtime#101450|
|[655360](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655360)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655360&view=ms.vss-test-web.build-test-results-tab&runId=16223536&resultId=217851)|dotnet/runtime#101451|
|[655225](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655225)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655225&view=ms.vss-test-web.build-test-results-tab&runId=16219104&resultId=214645)|dotnet/runtime#101450|
|[655183](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655183)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655183&view=ms.vss-test-web.build-test-results-tab&runId=16217204&resultId=214400)|dotnet/runtime#101291|
|[655140](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655140)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655140&view=ms.vss-test-web.build-test-results-tab&runId=16215254&resultId=217835)||
|[655083](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655083)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655083&view=ms.vss-test-web.build-test-results-tab&runId=16213064&resultId=214627)|dotnet/runtime#101513|
|[655080](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655080)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655080&view=ms.vss-test-web.build-test-results-tab&runId=16213180&resultId=217597)|dotnet/runtime#101512|
|[655031](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655031)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655031&view=ms.vss-test-web.build-test-results-tab&runId=16211640&resultId=217748)|dotnet/runtime#101501|
|[654927](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654927)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654927&view=ms.vss-test-web.build-test-results-tab&runId=16207534&resultId=218128)|dotnet/runtime#101392|
|[654914](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654914)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Cookies_Http3.GetAsync_DefaultCoookieContainer_NoCookieSent](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654914&view=ms.vss-test-web.build-test-results-tab&runId=16207318&resultId=209810)|dotnet/runtime#101499|
|[654860](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654860)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654860&view=ms.vss-test-web.build-test-results-tab&runId=16205732&resultId=214545)|dotnet/runtime#100094|
|[654744](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654744)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654744&view=ms.vss-test-web.build-test-results-tab&runId=16203338&resultId=214776)|dotnet/runtime#101330|
|[654715](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654715)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654715&view=ms.vss-test-web.build-test-results-tab&runId=16203008&resultId=214610)|dotnet/runtime#101492|
|[654688](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654688)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654688&view=ms.vss-test-web.build-test-results-tab&runId=16203080&resultId=201921)|dotnet/runtime#100918|
|[654653](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654653)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=654653&view=ms.vss-test-web.build-test-results-tab&runId=16200756&resultId=214696)|dotnet/runtime#100697|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|19|19|19|

**Comment by CarnaViire** [comment] 2024-04-25 09:36
Closing as duplicate of https://github.com/dotnet/runtime/issues/101463

**Closed by CarnaViire** 2024-04-25 09:36 UTC
Labels: blocking-clean-ci, area-System.Net.Quic, Known Build Error
