### ISSUE TITLE
.Net 6.0  Environment.CommandLine and Environment.GetCommandLineArgs() unable to get the correct command line parameters

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#102968] opened 2024-06-02 19:51 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Net-60-中-EnvironmentCommandLine-和-Env/10659406)._

---
[severity:It bothers me. A fix would be nice]
In .Net 6.0, using Environment.CommandLine returns the filename of the dll instead of the filename of the exe; Even if you start the program with command-line arguments, the arguments that follow the returned string are always empty.
The problem with Environment.GetCommandLineArgs() is similar, the first element of the returned array is also the dll file name, and even if you start the program with a command line argument, the array length is always 1, and the command line argument cannot be obtained. It is recommended to fix this issue.

---
#### Feedback Bot on 5/16/2024, 03:45 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by jkotas** [comment] 2024-06-02 19:54
Related / duplicate of https://github.com/dotnet/runtime/issues/101837

**Comment by agocke** [comment] 2024-06-03 17:02
Closing as dup of https://github.com/dotnet/runtime/issues/101837

**Closed by agocke** 2024-06-03 17:02 UTC
Labels: area-Host, untriaged
