### ISSUE TITLE
.net core 3.1 DeflateStream is incompatible with .net framework 4.8 DeflateStream

### ISSUE THREAD

**Issue by tahirkilic** [dotnet/runtime#58038] opened 2021-08-24 09:57 UTC
The following code snippet outputs different byte array in .net core 3.1 and .net framework 4.8. This can not be an optimization issue in the Deflate algorithm because an empty array is being compressed.

By the way, DeflateStream guarantees that the output is smaller or equal to input. When the input is an empty array, the output has to be an empty array.

.net core 3.1 :
Compress(new byte[0])

output : [ 3, 0 ]

.net framework 4.8:
Compress(new byte[0])

output : [  ]

```csharp
private byte[] Compress(byte[] buffer)
{
	using (MemoryStream memoryStream = new MemoryStream())
	{
		using (DeflateStream deflateStream = new DeflateStream(memoryStream, CompressionMode.Compress))
		{
			deflateStream.Write(buffer, 0, buffer.Length);
		}
		
		return memoryStream.ToArray();
	}
}
```

**Comment by Jozkee** [comment] 2021-08-31 05:05
Found this in the source:
https://github.com/dotnet/runtime/blob/5fc05889a8f7afe2af98bc13edf053786b34aa3e/src/libraries/System.IO.Compression/src/System/IO/Compression/DeflateZLib/DeflateStream.cs#L549-L553
And indeed this round-trips i.e: if you inflate the two bytes in memoryStream, you will get a zero-byte array back.

> By the way, DeflateStream guarantees that the output is smaller or equal to input. When the input is an empty array, the output has to be an empty array.

Just curious, where did you find this statement? Is it in the spec? Can you please link to where this is being stated.

**Comment by GSPP** [comment] 2022-12-28 21:26
> By the way, DeflateStream guarantees that the output is smaller or equal to input. When the input is an empty array, the output has to be an empty array.

This is impossible to guarantee for any compression algorithm. This is a theoretical result. That doesn't take away from the case that the OP is making for empty inputs, though.

**Comment by danmoseley** [comment] 2022-12-28 22:17
> This is impossible to guarantee for any compression algorithm. 

It is effectively possible (to within a small constant) if one has a "following data is uncompressed" bit in the header, of course.

**Comment by ViktorHofer** [comment] 2023-01-23 18:31
Closing as duplicate of https://github.com/dotnet/runtime/issues/30539#issuecomment-519728722

**Closed by ViktorHofer** 2023-01-23 18:31 UTC
Labels: area-System.IO.Compression
