### ISSUE TITLE
`Segmentation fault (core dumped)` at runtime in ARM64 self-contained application

### ISSUE THREAD

**Issue by eduherminio** [dotnet/runtime#57534] opened 2021-08-17 00:09 UTC
### Description

* `Segmentation fault (core dumped)` when running a .NET Core self-contained, single file application within ARM64 container `mcr.microsoft.com/dotnet/runtime-deps:6.0.0-preview.7` that was compiled using AMD64 `mcr.microsoft.com/dotnet/sdk:6.0.100-preview.7`
* `Segmentation fault (core dumped)` when running a .NET Core self-contained, single file application within ARM64 container `mcr.microsoft.com/dotnet/sdk:6.0.100-preview.7` or that was compiled using ARM64 `mcr.microsoft.com/dotnet/sdk:6.0.100-preview.7` (in that same container).

#### Repro steps for sdk images (ARM64):

Works as expected (preview.5):

```bash
sudo docker run -it mcr.microsoft.com/dotnet/sdk:6.0.100-preview.5 bash
git clone https://github.com/lynx-chess/lichess-challenger && cd lichess-challenger
dotnet publish src/LichessChallenger/LichessChallenger.csproj -c Release --runtime linux-arm64 --self-contained -o artifacts/
cd artifacts
export LICHESS_API_TOKEN="*"
export LICHESS_USERNAME="eduherminio"
./LichessChallenger
```

Segmentation fault (core dumped) at compile time (preview.6):

```bash
docker run -it mcr.microsoft.com/dotnet/sdk:6.0.100-preview.6 bash
git clone https://github.com/lynx-chess/lichess-challenger && cd lichess-challenger
dotnet publish src/LichessChallenger/LichessChallenger.csproj -c Release --runtime linux-arm64 --self-contained -o artifacts/ # Segmentation fault (core dumped)
```

**Segmentation fault (core dumped) at runtime** (preview.7):

```bash
docker run -it mcr.microsoft.com/dotnet/sdk:6.0.100-preview.7 bash
git clone https://github.com/lynx-chess/lichess-challenger && cd lichess-challenger
dotnet publish src/LichessChallenger/LichessChallenger.csproj -c Release --runtime linux-arm64 --self-contained -o artifacts/
cd artifacts
export LICHESS_API_TOKEN="*"
export LICHESS_USERNAME="eduherminio"
./LichessChallenger # Segmentation fault (core dumped)
```

#### Repro steps for runtime-props images (ARM64):

Works (preview 6, artifact compiled using AMD preview 6):

```bash
sudo docker run -it mcr.microsoft.com/dotnet/runtime-deps:6.0.0-preview.6 bash
apt-get update && apt-get install -y wget unzip
mkdir app && cd app
wget https://github.com/lynx-chess/lichess-challenger/releases/download/v0.1.2/lichess-challenger-0.1.2-linux-arm64.zip
unzip lichess-challenger-0.1.2-linux-arm64.zip
chmod +x LichessChallenger
export LICHESS_API_TOKEN="*"
export LICHESS_USERNAME="eduherminio"
./LichessChallenger
```

Works (preview 7, artifact compiled using AMD preview 6):

```bash
sudo docker run -it mcr.microsoft.com/dotnet/runtime-deps:6.0.0-preview.7 bash
apt-get update && apt-get install -y wget unzip
mkdir app && cd app
wget https://github.com/lynx-chess/lichess-challenger/releases/download/v0.1.2/lichess-challenger-0.1.2-linux-arm64.zip
unzip lichess-challenger-0.1.2-linux-arm64.zip
chmod +x LichessChallenger
export LICHESS_API_TOKEN="*"
export LICHESS_USERNAME="eduherminio"
./LichessChallenger
```

**Segmentation fault (core dumped) at runtime** (preview  6 and 7, artifact compiled using preview 7):

```bash
sudo docker run -it mcr.microsoft.com/dotnet/runtime-deps:6.0.0-preview.7 bash
apt-get update
apt-get install -y wget unzip
mkdir app && cd app
wget https://github.com/lynx-chess/lichess-challenger/releases/download/v0.1.6/lichess-challenger-0.1.3-linux-arm64.zip
unzip lichess-challenger-0.1.3-linux-arm64.zip
chmod +x LichessChallenger
export LICHESS_API_TOKEN="*"
export LICHESS_USERNAME="eduherminio"
./LichessChallenger
```

### Configuration

* .NET Version:
  * mcr.microsoft.com/dotnet/sdk:6.0.100-preview.7
  * mcr.microsoft.com/dotnet/runtime-deps:6.0.0-preview.7  
* Architecture: ARM64
* [Repository used in the repro steps](https://github.com/lynx-chess/lichess-challenger), including [Dockerfile](https://github.com/lynx-chess/lichess-challenger/blob/main/Dockerfile) and [GitHub action](https://github.com/lynx-chess/lichess-challenger/blob/main/.github/workflows/release.yml#L64) used to build the images.

### Regression?

Yes, working as expected in preview.5 and preview.6.

### Other information

Works flawlessly for AMD64.
Example of an image based on `mcr.microsoft.com/dotnet/runtime-deps:6.0.0-preview.7` with this error: `ghcr.io/lynx-chess/lichess-challenger:0.1.3`

Example of an image based on `mcr.microsoft.com/dotnet/runtime-deps:6.0.0-preview.6` without this error: `ghcr.io/lynx-chess/lichess-challenger:0.1.2` (it was built using an AMD64 container, therefore the compile-time error didn't affect it).

**Comment by mangod9** [comment] 2021-08-18 16:01
@eduherminio, does this repro only with single-file enabled?

**Comment by eduherminio** [comment] 2021-08-18 17:30
@mangod9 Yes, it repros only with single-file enabled.

Works: preview.7, no self-contained and no-trimming (to avoid `error NETSDK1102: Optimizing assemblies for size is not supported for the selected publish configuration. Please ensure that you are publishing a self-contained app.`):

```bash
sudo docker run -it mcr.microsoft.com/dotnet/sdk:6.0.100-preview.7 bash
git clone https://github.com/lynx-chess/lichess-challenger && cd lichess-challenger
dotnet publish src/LichessChallenger/LichessChallenger.csproj -c Release --runtime linux-arm64 --no-self-contained /p:PublishTrimmed=false -o artifacts/
cd artifacts
export LICHESS_API_TOKEN="*"
export LICHESS_USERNAME="eduherminio"
./LichessChallenger
```

So I guess it could be the self-contained or the trimming part.

**Comment by eduherminio** [comment] 2021-08-18 17:33
I just realized I'm so dumb I have some `6.0.0-preview.6...` dependencies in `main`, but **bumping them doesn't solve the issue**: same result (failing with `--self-contained` and working with `--no-self-contained /p:PublishTrimmed=false`) with:
```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.0-preview.7.21352.12" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="6.0.0-preview.7.21355.2" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="4.13.0" />
    <PackageReference Include="System.Net.Http.Json" Version="6.0.0-preview.7.21352.12" />
  </ItemGroup>
```
and
```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.0-preview.6.21352.12" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="6.0.0-preview.6.21355.2" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="4.13.0" />
    <PackageReference Include="System.Net.Http.Json" Version="6.0.0-preview.6.21352.12" />
  </ItemGroup>
```

**Comment by vitek-karas** [comment] 2021-08-18 17:49
Just to rule out some things: if you publish as self-contained only (no single-file, no trimming) - does it work?

**Comment by eduherminio** [comment] 2021-08-18 18:18
It does work, @vitek-karas.

```bash
docker run -it mcr.microsoft.com/dotnet/sdk:6.0.100-preview.7 bash
git clone https://github.com/lynx-chess/lichess-challenger && cd lichess-challenger
dotnet publish src/LichessChallenger/LichessChallenger.csproj -c Release --runtime linux-arm64 --self-contained /p:PublishSingleFile=false /p:PublishTrimmed=false -o artifacts/
cd artifacts
export LICHESS_API_TOKEN="*"
export LICHESS_USERNAME="eduherminio"
./LichessChallenger
```

**Comment by vitek-karas** [comment] 2021-08-18 18:49
Thank you - last question - what about just self-contained and single-file (no trimming)? Assuming this fails (sounds like it should from the above)... what happens if you disable Ready2Run (/p:PublishReadyToRun=false) as that is another angle which may cause problems.

**Comment by eduherminio** [comment] 2021-08-18 19:52
Self-contained and single-file without trimming fails
```bash
docker run -it mcr.microsoft.com/dotnet/sdk:6.0.100-preview.7 bash
git clone https://github.com/lynx-chess/lichess-challenger && cd lichess-challenger
dotnet publish src/LichessChallenger/LichessChallenger.csproj -c Release --runtime linux-arm64 --self-contained /p:PublishSingleFile=true /p:PublishTrimmed=false -o artifacts/
cd artifacts
export LICHESS_API_TOKEN="*"
export LICHESS_USERNAME="eduherminio"
./LichessChallenger # Segmentation fault (core dumped)
```

Self-contained and single file, without trimming or ready to run fails as well
````bash
sudo docker run -it mcr.microsoft.com/dotnet/sdk:6.0.100-preview.7 bash
git clone https://github.com/lynx-chess/lichess-challenger && cd lichess-challenger
dotnet publish src/LichessChallenger/LichessChallenger.csproj -c Release --runtime linux-arm64 --self-contained /p:PublishSingleFile=true /p:PublishTrimmed=false /p:PublishReadyToRun=false -o artifacts/
cd artifacts
export LICHESS_API_TOKEN="*"
export LICHESS_USERNAME="eduherminio"
./LichessChallenger # Segmentation fault (core dumped)
```

**Comment by vitek-karas** [comment] 2021-08-18 20:15
That sounds a lot like this is a problem with "Single-file" - @VSadov, could you please take a look.

**Comment by VSadov** [comment] 2021-09-03 17:08
@eduherminio - just curious - is there a failure if the app is launched outside of Docker? (just  trying to narrow down reasons for the failure).

**Comment by VSadov** [comment] 2021-09-03 19:40
So far I am unable to reproduce the crash. The app runs fine for me in a single-file or a regular self-contained configuration.

```
~/repro/publish$ ./LichessChallenger
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
12:36:57 | [INFO] Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
12:36:57 | [INFO] Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
```

This is Debug and without docker. 
Next I will try running inside a container.

**Comment by VSadov** [comment] 2021-09-03 19:51
I see same results in a container. Both self-contained and single-file builds of the app run without crashing.

For building I am using a windows machine with 
```
dotnet --version
6.0.100-rc.1.21420.24
```

**Comment by VSadov** [comment] 2021-09-03 20:20
I have also tried the actual preview-7 SDK instructions - 
```
docker run -it mcr.microsoft.com/dotnet/sdk:6.0.100-preview.7 bash
git clone https://github.com/lynx-chess/lichess-challenger && cd lichess-challenger
dotnet publish src/LichessChallenger/LichessChallenger.csproj -c Release --runtime linux-arm64 --self-contained -o artifacts/
cd artifacts
export LICHESS_API_TOKEN="*"
export LICHESS_USERNAME="eduherminio"
./LichessChallenger 
```

The build produces a lot of trim warnings, but the a app still works. At least as I can tell - there is some diagnostic output and no crashes.

I have tried building with ` -p:PublishAsSingleFile=true`  and without.

**Comment by eduherminio** [comment] 2021-09-06 09:13
> I have also tried the actual preview-7 SDK instructions -
> 
> ```
> docker run -it mcr.microsoft.com/dotnet/sdk:6.0.100-preview.7 bash
> git clone https://github.com/lynx-chess/lichess-challenger && cd lichess-challenger
> dotnet publish src/LichessChallenger/LichessChallenger.csproj -c Release --runtime linux-arm64 --self-contained -o artifacts/
> cd artifacts
> export LICHESS_API_TOKEN="*"
> export LICHESS_USERNAME="eduherminio"
> ./LichessChallenger 
> ```
> 
> The build produces a lot of trim warnings, but the a app still works. At least as I can tell - there is some diagnostic output and no crashes.
> 
> I have tried building with ` -p:PublishAsSingleFile=true` and without.

🤔 that's... odd, I still have the issues following those instructions.

I'm seeing this issue both with and without Docker.
I'm using an `aarch64` OCI VM to test (and deploy) it:

```bash
NAME="Oracle Linux Server"
VERSION="8.4"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.4"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:8:4:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 8"
ORACLE_BUGZILLA_PRODUCT_VERSION=8.4
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=8.4
```

This is one of the preview-7 built binaries that fail while ran directly inside the mentioned VM:
* [https://github.com/lynx-chess/Lynx/releases/download/v0.2.2/Lynx-0.2.2-linux-arm64.zip](https://github.com/lynx-chess/Lynx/releases/download/v0.2.2/Lynx-0.2.2-linux-arm64.zip)

```bash
wget https://github.com/lynx-chess/Lynx/releases/download/v0.2.2/Lynx-0.2.2-linux-arm64.zip
unzip Lynx-0.2.2-linux-arm64.zip -d repro && cd repro
chmod +x Lynx.Cli
./Lynx.Cli  # Segmentation fault (core dumped)
```

Using v0.2.3, which was build [using preview-6](https://github.com/lynx-chess/Lynx/pull/18/files), just works.

**Comment by VSadov** [comment] 2021-09-10 21:25
The app in `Lynx-0.2.2-linux-arm64.zip` does not crash on my VM. 
It is a ` Ubuntu 18.04.3 LTS` VM.

I suspect something is different in your VM.

Could you try building without forcing single file?
 like:

`dotnet publish src/LichessChallenger/LichessChallenger.csproj -c Release --runtime linux-arm64 --self-contained  /p:PublishTrimmed=false -o artifacts/`

That will produce a regular self contained app not packed into a single executable. I wonder if that will run in your VM.

**Comment by eduherminio** [comment] 2021-09-13 00:49
When using `--self-contained /p:PublishTrimmed=false /p:PublishSingleFile=true` it **fails**, both inside of the container and directly in the VM.
When using the same but `/p:PublishSingleFile=false` it **works** both in the container and the VM, with both `/p:PublishTrimmed=false` and `/p:PublishTrimmed=true`.

```bash
mkdir tmp
docker run -it --mount type=bind,src=$PWD/tmp,dst=/home/app -w /home/app mcr.microsoft.com/dotnet/sdk:6.0.100-preview.7 bash
git clone https://github.com/lynx-chess/lichess-challenger && cd lichess-challenger
dotnet publish src/LichessChallenger/LichessChallenger.csproj -c Release --runtime linux-arm64 --self-contained /p:PublishTrimmed=false /p:PublishSingleFile=true -o artifacts/
cd artifacts
export LICHESS_API_TOKEN="*"
export LICHESS_USERNAME="eduherminio"
./LichessChallenger # Segmentation fault inside of container
exit
./tmp/lichess-challenger/artifacts/LichessChallenger # Segmentation fault directly in the VM
```

**Comment by VSadov** [comment] 2021-09-13 15:06
> When using --self-contained /p:PublishTrimmed=false /p:PublishSingleFile=true it fails, both inside of the container and directly in the VM.
When using the same but /p:PublishSingleFile=false it works both in the container and the VM, with both /p:PublishTrimmed=false and /p:PublishTrimmed=true.

So we can rule out the part of running inside a container, since the behavior is the same.
It looks like the main differentiator is the kind of VM. -   Ubuntu vs. OLC

I wonder if there could be some requirement/prerequisite that is missing in OLC that single-file app uses.

**Comment by eduherminio** [comment] 2021-09-13 15:26
If that's the case, it's something that also affects single-file apps that run inside of containers on top of OLC 🤔

**Comment by eduherminio** [comment] 2021-09-14 21:14
@VSadov The issue is _mysteriously_ fixed in rc 1, so feel free to close this unless you want to continue/finish any research you may doing.

I double checked that preview 7 builds kept failing after seeing rc 1 ones working, so maybe there was something odd in preview-7 after all.

**Comment by VSadov** [comment] 2021-09-14 21:41
Hmm. There were very little changes between P7 and RC in the area of single-file, but there were a lot of changes in other part of the runtime. There is a possibility that some unrelated bug was causing this. In particular, if it is due to something like uninitialized data, then a bug could show up only in some environments/builds. These are notoriously hard to find and fix, but also very rare.

I think I will close this issue as right now I do not see a lot of actionable directions to take. We should watch this scenario carefully to be sure the bug does not come back later.

**Closed** 2021-09-14 21:42 UTC
Labels: area-Single-File
