### ISSUE TITLE
Test Failure - `Assertion failed 'varTypeMap[type] != TYP_UNDEF' in 'System.Numerics.Tests.QuaternionTests:QuaternionCreateFromYawPitchRollTest2():this' during 'Morph - Inlining'`

### ISSUE THREAD

**Issue by TIHan** [dotnet/runtime#85589] opened 2023-05-01 14:17 UTC
runtime-coreclr libraries-pgo

```
Console log: 'System.Numerics.Vectors.Tests' from job 5f613735-a57c-4f5f-abe8-325895394dcb workitem e0025d13-6cc0-4c56-abd5-3abd1de47ae2 (windows.10.amd64.open.rt) executed on machine a008PNX running Windows-10-10.0.14393-SP0

C:\h\w\A8130957\w\AEE809EA\e>taskkill.exe /f /im corerun.exe 
ERROR: The process "corerun.exe" not found.

C:\h\w\A8130957\w\AEE809EA\e>set __TestEnv=C:\h\w\A8130957\p\SetStressModes_fullpgo_methodprofiling.cmd 

C:\h\w\A8130957\w\AEE809EA\e>type C:\h\w\A8130957\p\SetStressModes_fullpgo_methodprofiling.cmd 
set DOTNET_TieredCompilation=1
set DOTNET_ReadyToRun=0
set DOTNET_TC_QuickJitForLoops=1
set DOTNET_TieredPGO=1
set DOTNET_JitDelegateProfiling=1
set DOTNET_JitVTableProfiling=1

C:\h\w\A8130957\w\AEE809EA\e>call C:\h\w\A8130957\p\SetStressModes_fullpgo_methodprofiling.cmd 

C:\h\w\A8130957\w\AEE809EA\e>set DOTNET_TieredCompilation=1 

C:\h\w\A8130957\w\AEE809EA\e>set DOTNET_ReadyToRun=0 

C:\h\w\A8130957\w\AEE809EA\e>set DOTNET_TC_QuickJitForLoops=1 

C:\h\w\A8130957\w\AEE809EA\e>set DOTNET_TieredPGO=1 

C:\h\w\A8130957\w\AEE809EA\e>set DOTNET_JitDelegateProfiling=1 

C:\h\w\A8130957\w\AEE809EA\e>set DOTNET_JitVTableProfiling=1 

C:\h\w\A8130957\w\AEE809EA\e>set DOTNET 
DOTNET_JitDelegateProfiling=1
DOTNET_JitVTableProfiling=1
DOTNET_ReadyToRun=0
DOTNET_TC_QuickJitForLoops=1
DOTNET_TieredCompilation=1
DOTNET_TieredPGO=1

C:\h\w\A8130957\w\AEE809EA\e>call RunTests.cmd --runtime-path C:\h\w\A8130957\p 
----- start Sun 04/30/2023 17:17:38.42 ===============  To repro directly: ===================================================== 
pushd C:\h\w\A8130957\w\AEE809EA\e\
"C:\h\w\A8130957\p\dotnet.exe" exec --runtimeconfig System.Numerics.Vectors.Tests.runtimeconfig.json --depsfile System.Numerics.Vectors.Tests.deps.json xunit.console.dll System.Numerics.Vectors.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================

C:\h\w\A8130957\w\AEE809EA\e>"C:\h\w\A8130957\p\dotnet.exe" exec --runtimeconfig System.Numerics.Vectors.Tests.runtimeconfig.json --depsfile System.Numerics.Vectors.Tests.deps.json xunit.console.dll System.Numerics.Vectors.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Numerics.Vectors.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Numerics.Vectors.Tests (found 1479 test cases)
  Starting:    System.Numerics.Vectors.Tests (parallel test collections = on, max threads = 4)

Assert failure(PID 2524 [0x000009dc], Thread: 3496 [0x0da8]): Assertion failed 'varTypeMap[type] != TYP_UNDEF' in 'System.Numerics.Tests.QuaternionTests:QuaternionCreateFromYawPitchRollTest2():this' during 'Morph - Inlining' (IL size 318; hash 0xeccd69b3; Tier1-OSR)

    File: D:\a\_work\1\s\src\coreclr\jit\ee_il_dll.hpp Line: 233
    Image: C:\h\w\A8130957\p\dotnet.exe

----- end Sun 04/30/2023 17:18:00.83 ----- exit code -1073740286 ----------------------------------------------------------
2023-04-30T17:18:01.522Z	INFO   	run.py	run(48)	main	Beginning reading of test results.
2023-04-30T17:18:01.538Z	INFO   	run.py	__init__(42)	read_results	Searching 'C:\h\w\A8130957\w\AEE809EA\e' for test results files
2023-04-30T17:18:01.538Z	INFO   	run.py	__init__(42)	read_results	Searching 'C:\h\w\A8130957\w\AEE809EA\uploads' for test results files
2023-04-30T17:18:01.538Z	WARNING	run.py	__init__(55)	read_results	No results file found in any of the following formats: xunit, junit, trx
2023-04-30T17:18:01.538Z	INFO   	run.py	packing_test_reporter(30)	report_results	Packing 0 test reports to 'C:\h\w\A8130957\w\AEE809EA\e\__test_report.json'
2023-04-30T17:18:01.538Z	INFO   	run.py	packing_test_reporter(33)	report_results	Packed 1559 bytes
ERROR: The process "corerun.exe" not found.
read file: C:\h\w\A8130957\p\debug-dump-template.md
writing output file: C:\h\w\A8130957\w\AEE809EA\uploads\how-to-debug-dump.md
done writing debug dump information
['System.Numerics.Vectors.Tests' END OF WORK ITEM LOG: Command exited with -1073740286]
```

Seems to only appear for this PR: https://github.com/dotnet/runtime/pull/84656

**Comment by SingleAccretion** [comment] 2023-05-01 19:19
I'll close this as duplicate of #85589 (that one has a non-PGO reproduction).

**Closed by SingleAccretion** 2023-05-01 19:19 UTC
Labels: area-CodeGen-coreclr, test-failure
