### ISSUE TITLE
Device deployments using android-arm and android-arm64 are crashing

### ISSUE THREAD

**Issue by pjcollins** [dotnet/runtime#52604] opened 2021-05-11 15:40 UTC
We're seeing crashes on Android arm RIDs using the latest .NET 6 SDK `6.0.100-preview.5.21260.2` (`BundledNETCoreAppPackageVersion=6.0.0-preview.5.21256.1`). This  should be easily reproducible by deploying a simple .NET 6 Android project to an arm64 device using the following RIDs:
```xml
<RuntimeIdentifier>android-arm</RuntimeIdentifier>
```
and 
```xml
<RuntimeIdentifier>android-arm64</RuntimeIdentifier>
```

Logcat:
https://gist.github.com/grendello/f16aef0be1ce9a43172b19af8228c29f

Could this be related to (or potentially a duplicate of) #52454?

**Comment by EgorBo** [comment] 2021-05-11 16:59
Interesting, some unknown (for Mono) CIL opcode (judging by the `mono_inst_name` assert)?

**Comment by steveisok** [comment] 2021-05-11 23:35
I believe this is a duplicate of https://github.com/dotnet/runtime/issues/52454

**Closed by steveisok** 2021-05-11 23:35 UTC
Labels: untriaged
