### ISSUE TITLE
Test failure: System.Tests.ArrayTests.Sort_Array_Array_Generic<String>(keys: [\"bcd\", \"bc\", \"c\", \"ab\"], items: [\"a\", \"b\", \"c\", \"d\"], index: 0, length: 4, comparer: StringComparer { }, expectedKeys: [\"ab\", \"bc\", \"bcd\", \"c\"], expectedItems: [\"d\", \"b\", \"a\", \"c\"])

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#45345] opened 2020-11-30 08:52 UTC
failed in job: https://dev.azure.com/dnceng/public/_build/results?buildId=902287&view=ms.vss-test-web.build-test-results-tab&runId=28813224&resultId=170943&paneView=debug

net6.0-windows-Release-x86-CoreCLR_checked-tailcallstress-Windows.10.Amd64.Open

Error message
~~~
Assert.Equal() Failure
Expected: String[] ["ab", "bc", "bcd", "c"]
Actual:   String[] ["bcd", "bc", "c", "ab"]

Stack trace
   at System.Tests.ArrayTests.Sort_Array_Array_Generic[T](T[] keys, T[] items, Int32 index, Int32 length, IComparer`1 comparer, T[] expectedKeys, T[] expectedItems) in /_/src/libraries/System.Runtime/tests/System/ArrayTests.cs:line 3904
~~~

**Comment by GrabYourPitchforks** [comment] 2020-11-30 09:18
Likely dupe of https://github.com/dotnet/runtime/issues/45317, fixed by https://github.com/dotnet/runtime/pull/45320

**Closed by GrabYourPitchforks** 2020-11-30 09:18 UTC
Labels: untriaged
