### ISSUE TITLE
Why doesn't PriorityQueue have the Remove(TElement element) method

### ISSUE THREAD

**Issue by sw47** [dotnet/runtime#65928] opened 2022-02-27 16:49 UTC
The current PriorityQueue Implementation for .NET [PriorityQueue Implementation for .NET](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.priorityqueue-2?view=net-6.0#methods) does not have the Remove(TElement element) method as written on the original contract defined in this #14032

I perused the history of #14032 spanning half a decade+ worth of discussions (!) and unfortunately didn't find the post which proposed to remove the the Remove method from the final implementation.

Can someone shed some light on this? I would have expected the .NET Priority Queue implementation to have a certain degree of parity to [Java's implementation] (https://docs.oracle.com/javase/7/docs/api/java/util/PriorityQueue.html)

Also, +💯  this https://github.com/dotnet/runtime/issues/14032#issuecomment-729780692 - would be great if the history of this API was written up as a blog entry on DevDiv :)

**Comment by Joe4evr** [comment] 2022-02-27 18:14
The Priority Queue was implemented according to the API proposed at #43957, which states:
> * Should we include a `void Remove(TElement element);` method?
>   * _No. Can be ambiguous operation in the presence of duplicate elements._

**Comment by sw47** [comment] 2022-02-27 18:48
Thanks @Joe4evr - what was the design rationale for not allowing duplicates? PriorityQueues in Java allow duplicates....

**Comment by jnyrup** [comment] 2022-02-27 20:01
`PriorityQueue` supports _enqueuing_ duplicates, the ambiguity comes when removing.

```cs
var pq = new PriorityQueue<int, int>();
pq.Enqueue(1, 1);
pq.Enqueue(1, 2);
// pq.Remove(1); <-- which of the above should be removed?
```

**Comment by Genbox** [comment] 2022-02-27 23:09
> which of the above should be removed?

Presumably the one where the equality comparer determines equality. Sure, the default comparer for integer means that 1 equals 1, but in collections, 1 is not an integer - it is a key - and keys do not necessarily have value equality.

Since .NET has a very simplistic equality comparer interface where it is only possible to compare keys and not position/key hash/priority/value, it gives the developer some difficult decisions with potential side effects when it comes to duplicates. Therefore I agree that it is not exactly straightforward, but also not an issue that the data structure necessarily should concern itself with.

However, it makes me think that a RemoveAt() method would be suitable and is a paradigm in .NET collections already. Was RemoveAt() discussed before?

**Comment by theodorzoulias** [comment] 2022-02-28 00:22
This issue might be a duplicate of this: [Add a priority queue that supports priority updates](https://github.com/dotnet/runtime/issues/44871)

**Comment by eiriktsarpalis** [comment] 2022-02-28 10:52
It might be worth pointing out that the `Remove` method in Java's PriorityQueue is an _O(n)_ operation, so using it to express priority updates (as is sometimes recommended in public forums) can be prohibitively expensive. If we do offer such a solution we might consider offering _O(log n)_ operations, but that requires a different implementation: #44871

Closing in favor of #44871.

**Closed by eiriktsarpalis** 2022-02-28 10:52 UTC
Labels: area-System.Collections, untriaged
