### ISSUE TITLE
MulticastInterface_Set_IPv6_Loopback_Succeeds doesn't

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#92622] opened 2023-09-26 04:22 UTC
On my machine using 867f5d483e340af033f2ba83d29b21bab0e3bcb3 I ran inner loop tests and these failed

MulticastInterface_Set_IPv6_Loopback_Succeeds
MulticastInterface_Set_IPv6_AnyInterface_Succeeds

like this
```
        <failure exception-type="System.Net.Sockets.SocketException">
          <message><![CDATA[System.Net.Sockets.SocketException : A socket operation was attempted to an unreachable network.]]></message>
          <stack-trace><![CDATA[   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName) in C:\git\runtime\src\libraries\System.Net.Sockets\src\System\Net\Sockets\Socket.cs:line 3730
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP) in C:\git\runtime\src\libraries\System.Net.Sockets\src\System\Net\Sockets\Socket.cs:line 1294
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, EndPoint remoteEP) in C:\git\runtime\src\libraries\System.Net.Sockets\src\System\Net\Sockets\Socket.cs:line 1322
   at System.Net.Sockets.Tests.SocketOptionNameTest.CreateBoundUdpIPv6Socket(Int32& localPort) in C:\git\runtime\src\libraries\System.Net.Sockets\tests\FunctionalTests\SocketOptionNameTest.cs:line 304
   at System.Net.Sockets.Tests.SocketOptionNameTest.MulticastInterface_Set_IPv6_Helper(Int32 interfaceIndex) in C:\git\runtime\src\libraries\System.Net.Sockets\tests\FunctionalTests\SocketOptionNameTest.cs:line 199
   at System.Net.Sockets.Tests.SocketOptionNameTest.MulticastInterface_Set_IPv6_AnyInterface_Succeeds() in C:\git\runtime\src\libraries\System.Net.Sockets\tests\FunctionalTests\SocketOptionNameTest.cs:line 135
--- End of stack trace from previous location ---]]></stack-trace>
```
it is trying to do this
```c#
            Socket receiveSocket = new Socket(AddressFamily.InterNetworkV6, SocketType.Dgram, ProtocolType.Udp);

            // sending a message will bind the socket to an available port
            string sendMessage = "dummy message";
            int port = 54320;
            IPAddress multicastAddress = IPAddress.Parse("ff11::1:1");
            receiveSocket.SendTo(Encoding.UTF8.GetBytes(sendMessage), new IPEndPoint(multicastAddress, port));
```
Windows 11 22H2.

code above says 
> On Windows, we can apparently assume interface 1 is "loopback."

Should I expect `ping ff11::1:1` to succeed? It gives 'general failure'

**Comment by liveans** [comment] 2023-10-04 17:30
Duplicate of #90491

**Closed by liveans** 2023-10-04 17:30 UTC
Labels: area-System.Net.Sockets, untriaged
