### ISSUE TITLE
[API Proposal]: ReadOnlySpan<char>.Enumerate(ReadOnlySpan<char> delimiter, StringComparer comparer)

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#68487] opened 2022-04-25 12:00 UTC
### Background and motivation

We already have `MemoryExtensions.EnumerateLines()` to enumerate lines fast and allocate free. That is good but has two downsides:

1. It already says that it shouldn't be used for protocol parsing, see [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.memoryextensions.enumeratelines?view=net-6.0#system-memoryextensions-enumeratelines(system-readonlyspan((system-char))))
2. It is limited to line endings only but we may want to enumerate based on a custom delimiter

Therefore similar to the overloads of String.Split() I suggest an API that enumerates a `ReadOnlyChar<char>` by a custom delimiter with the same benefits of `EnumerateLines()`

### API Proposal

```C#
namespace System
{
    public class MemoryExtensions
    {
        public static SpanLineEnumerator Enumerate(this ReadOnlySpan<char> span, ReadOnlySpan<char> delimiter, StringComparer comparer = StringComparer.OrdinalIgnoreCase);
    }
}
```

### API Usage

```C#
public void ParseUri(string str)
{
	string username = string.Empty;
	foreach (ReadOnlySpan<char> item in str.AsSpan().Enumerate("&".AsSpan()))
	{
		if (!item.StartsWith("username".AsSpan())
			continue;
		username = item.Slice(item.IndexOf('=') + 1).ToString();
	}
}

public void ParseHexString()
{
	string hex = "78 69 ?? 54 65 ** 90 ? 88";
	List<byte?> list = new();
	foreach (ReadOnlySpan<char> item in str.AsSpan().Enumerate(" ".AsSpan()))
	{
		if (item == "??" ||| item == "**" || item == "?")
			list.Add(null);
		else
			list.Add(byte.Parse(item, NumberStyles.HexNumber, CultureInfo.InvariantCulture)); //There are better ways but to keep it short...
	}
}

```

### Risks

None

**Comment by stephentoub** [comment] 2022-04-25 14:06
This looks like a duplicate of https://github.com/dotnet/runtime/issues/934.

**Comment by Symbai** [comment] 2022-04-25 14:10
Pretty much 👀 Although I prefer the name `Enumerate` more than `Split`. Because of the similarity of `String.Split` and `Span.EnumerateLines()`. On Split people would assume to retrieve an array. Enumerate is more clear when its just an enumerator.

**Closed** 2022-04-25 14:12 UTC
Labels: api-suggestion, area-System.Memory, untriaged
