### ISSUE TITLE
Intermittent crash in DynamicGenerics test on OSX x64

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#73299] opened 2022-08-03 14:02 UTC
```
Running Test: ThreadLocalStatics.TLSTesting.ThreadLocalStatics_Test
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/Users/runner/work/1/s/artifacts/tests/coreclr/OSX.x64.Release/Tests/Core_Root
> /Users/runner/work/1/s/artifacts/tests/coreclr/OSX.x64.Release/nativeaot/SmokeTests/DynamicGenerics/DynamicGenerics/DynamicGenerics.sh
Expected: True
Actual:   False
Stack Trace:
  /Users/runner/work/1/s/artifacts/tests/coreclr/OSX.x64.Release/TestWrappers/nativeaot.SmokeTests/nativeaot.SmokeTests.XUnitWrapper.cs(347,0): at nativeaot_SmokeTests._DynamicGenerics_DynamicGenerics_DynamicGenerics_._DynamicGenerics_DynamicGenerics_DynamicGenerics_sh()
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
     at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by jkotas** [comment] 2022-08-03 14:03
Hit in #73271. Full log https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_apis/build/builds/1920116/logs/1036

**Comment by MichalStrehovsky** [comment] 2022-08-03 23:37
Also failed in #73131: https://dev.azure.com/dnceng/public/_build/results?buildId=1917271&view=logs&jobId=d0e6dc78-17a8-5646-915d-5d9284339059&j=2de479a8-eae7-5324-c49d-bebaef329288&t=bb577e75-8247-55f1-4164-04f3b0f2d1eb&s=96ac2280-8cb4-5df5-99de-dd2da759617d

**Comment by MichalStrehovsky** [comment] 2022-08-10 06:30
Looks like intermitted crash in DynamicGenerics is only a tip of the iceberg. I did a libraries test pass on mac in #73546 and it's a crashfest.

Moving this to 8.0. Mac is not supported.

**Comment by carlossanlop** [comment] 2022-08-25 18:42
Hit it in a 7.0 backport: https://github.com/dotnet/runtime/pull/74589
- Queue: Build OSX x64 release NativeAOT.
- Job results: https://dev.azure.com/dnceng/public/_build/results?buildId=1966755&view=logs&j=2de479a8-eae7-5324-c49d-bebaef329288&t=bb577e75-8247-55f1-4164-04f3b0f2d1eb&l=974

```
      nativeaot/SmokeTests/DynamicGenerics/DynamicGenerics/DynamicGenerics.sh [FAIL]
        /Users/runner/work/1/s/src/tests/Common/scripts/nativeaottest.sh: line 14: 22270 Abort trap: 6           $_DebuggerFullPath $1/native/$exename "${@:3}"
        
        Return code:      1
        Raw output file:      /Users/runner/work/1/s/artifacts/tests/coreclr/OSX.x64.Release/nativeaot/SmokeTests/Reports/nativeaot.SmokeTests/DynamicGenerics/DynamicGenerics/DynamicGenerics.output.txt
        Raw output:
        BEGIN EXECUTION
        /Users/runner/work/1/s/src/tests/Common/scripts/nativeaottest.sh /Users/runner/work/1/s/artifacts/tests/coreclr/OSX.x64.Release/nativeaot/SmokeTests/DynamicGenerics/DynamicGenerics/ DynamicGenerics.dll ''
        --------------------------------
        Running Test: My.TestActivatorCreateInstance
        Calling List<My>.ctor
        System.Collections.Generic.List`1[My]
        Adding item to List<My>
        Calling List<My>.get_Count
        Calling GC.Collect
        Calling List<Foo>.ctor
        System.Collections.Generic.List`1[Foo]
        Adding item to List<Foo>
        Calling List<My>.get_Count
        Calling Dictionary<My,My>.ctor
        System.Collections.Generic.Dictionary`2[My,My]
        Adding item to Dictionary<My,My>
```

```
Running Test: ThreadLocalStatics.TLSTesting.ThreadLocalStatics_Test
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/Users/runner/work/1/s/artifacts/tests/coreclr/OSX.x64.Release/Tests/Core_Root
> /Users/runner/work/1/s/artifacts/tests/coreclr/OSX.x64.Release/nativeaot/SmokeTests/DynamicGenerics/DynamicGenerics/DynamicGenerics.sh


Time [secs] | Total | Passed | Failed | Skipped | Assembly Execution Summary
============================================================================
     14.255 |    17 |     16 |      1 |       0 | nativeaot.SmokeTests.XUnitWrapper.dll
----------------------------------------------------------------------------
     14.255 |    17 |     16 |      1 |       0 | (total)
```

**Comment by MichalStrehovsky** [comment] 2022-08-26 01:55
Blocking the test in #74618. Dropping blocking-clean-ci label.

**Comment by filipnavara** [comment] 2022-09-09 12:14
I wonder if the root cause could be similar as https://github.com/dotnet/runtime/pull/75264#discussion_r966997766.

**Comment by carlossanlop** [comment] 2022-09-26 18:36
Found another hit in the `release/7.0-rc2`->`release/7.0` automated merge branch PR: https://github.com/dotnet/runtime/pull/75913

- Queue: Build OSX x64 release NativeAOT
- Job results: https://dev.azure.com/dnceng-public/public/_build/results?buildId=28122&view=logs&j=2de479a8-eae7-5324-c49d-bebaef329288&t=bb577e75-8247-55f1-4164-04f3b0f2d1eb&l=974
- Callstack: 
```
 --------------------------------
        Running Test: ThreadLocalStatics.TLSTesting.ThreadLocalStatics_Test
        Expected: 100
        Actual: 134
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/Users/runner/work/1/s/artifacts/tests/coreclr/OSX.x64.Release/Tests/Core_Root
        > /Users/runner/work/1/s/artifacts/tests/coreclr/OSX.x64.Release/nativeaot/SmokeTests/DynamicGenerics/DynamicGenerics/DynamicGenerics.sh
        Expected: True
        Actual:   False
        Stack Trace:
          /Users/runner/work/1/s/artifacts/tests/coreclr/OSX.x64.Release/TestWrappers/nativeaot.SmokeTests/nativeaot.SmokeTests.XUnitWrapper.cs(347,0): at nativeaot_SmokeTests._DynamicGenerics_DynamicGenerics_DynamicGenerics_._DynamicGenerics_DynamicGenerics_DynamicGenerics_sh()
             at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
             at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
        Output:
          /Users/runner/work/1/s/src/tests/Common/scripts/nativeaottest.sh: line 14: 62770 Abort trap: 6           $_DebuggerFullPath $1/native/$exename "${@:3}"
          
          Return code:      1
          Raw output file:      /Users/runner/work/1/s/artifacts/tests/coreclr/OSX.x64.Release/nativeaot/SmokeTests/Reports/nativeaot.SmokeTests/DynamicGenerics/DynamicGenerics/DynamicGenerics.output.txt
          Raw output:
          BEGIN EXECUTION
          /Users/runner/work/1/s/src/tests/Common/scripts/nativeaottest.sh /Users/runner/work/1/s/artifacts/tests/coreclr/OSX.x64.Release/nativeaot/SmokeTests/DynamicGenerics/DynamicGenerics/ DynamicGenerics.dll ''
          --------------------------------
```

**Comment by MichalStrehovsky** [comment] 2022-09-27 00:54
@carlossanlop how much does this bother things in the release branch? We could backport #74618 to make this go away.

**Comment by carlossanlop** [comment] 2022-09-27 00:57
I have seen it intermittently. It would certainly help clean the CI in the long term. How concerning is this issue in general? We could consider it if it meets the bar, besides cleaning the CI.

@jeffschwMSFT thoughts?

**Comment by jkotas** [comment] 2022-09-27 01:13
Let's backport it.

**Comment by jkotas** [comment] 2022-09-27 04:13
https://github.com/dotnet/runtime/pull/76223

**Comment by carlossanlop** [comment] 2022-09-27 20:29
Do you want to keep this issue open? Or can we consider it fixed after disabling DynamicGenerics from mac in main and 7.0?

**Comment by filipnavara** [comment] 2022-09-27 20:37
Keep open with disabled-test label? (It may be fixed in main, or once my WIP PR gets all the tests enabled w/ related fixes)

**Closed** 2022-10-02 04:08 UTC
Labels: disabled-test, in-pr, area-NativeAOT-coreclr
