### ISSUE TITLE
System.Text.Json.JsonSerializer.DeserializeAsync throws JsonException when Stream contains trailing null terminators '0x00'

### ISSUE THREAD

**Issue by vaslnk** [dotnet/runtime#79559] opened 2022-12-12 20:49 UTC
### Description

`System.Text.Json.JsonSerializer.DeserializeAsync` throws a JsonException when the input Stream (UTF8 byte-array) contains trailing null terminators: 
`'0x00' is invalid after a single JSON value`

### How the Stream is created
This issue was observed when working with a `MemoryStream` that was created using `System.Text.Json.JsonSerializer.Serialize`

The byte array resulting from that operation (see reproduction steps) contains trailing null characters:
`239, 187, 191, 123, 34, 70, 105, 114, 115, 116, 78, 97, 109, 101, 34, 58, 34, 97, 34, 44, 34, 76, 97, 115, 116, 78, 97, 109, 101, 34, 58, 34, 98, 34, 125, 0, 0, 0, 0, 0, 0, 0, ... 0]`

### Deserializing Stream (using System.Text.Json) -> Fails
`Person? personResult = await System.Text.Json.JsonSerializer.DeserializeAsync<Person>(msm);`

Deserializing the stream using `System.Text.Json.JsonSerializer.DeserializeAsync` fails with the following JsonException:
`'0x00' is invalid after a single JSON value. Expected end of data. Path: $ | LineNumber: 0 | BytePositionInLine: 0.`

### Deserializing same Stream (using Newtonsoft.Json) -> Succeeds
On the contrary, Newtonsoft Json Deserializer has no problem to deserialize the UTF8 byte-array stream with trailing null terminators:
```
var serializer = JsonSerializer.CreateDefault();
var streamReader = new StreamReader(msm);
Person? personResult =  serializer.Deserialize<Person>(new JsonTextReader(streamReader));
```

### Reproduction Steps

```
internal class Program
{
    class Person
    {
        public string FirstName { get; set; } = null!;
        public string LastName { get; set; } = null!;
    }


    private static async Task Main(string[] args)
    {
        Person p = new Person()
        {
            FirstName = "a",
            LastName = "b",
        };

        using var ms = new MemoryStream();
        using (var writer = new StreamWriter(ms, System.Text.Encoding.UTF8))
        {
            System.Text.Json.JsonSerializer.Serialize(p, typeof(Person));
            writer.Flush();
        }

        // bytes is equal to [
        //239, 187, 191, 123, 34, 70, 105, 114, 115, 116,
        //78, 97, 109, 101, 34, 58, 34, 97, 34, 44, 34,
        //76, 97, 115, 116, 78, 97, 109, 101, 34, 58, 34,
        //98, 34, 125, 0, 0, 0, 0, 0, 0, 0]
        // Notice the trailing 0 bytes
        byte[] bytes = ms.GetBuffer();
        
        using var msm = new MemoryStream(bytes);

        // Next  code line throws following exception:
        //      System.Text.Json.JsonException:
        //          ''0x00' is invalid after a single JSON value.
        //          Expected end of data. Path: $ | LineNumber: 0 | BytePositionInLine: 0.'
        Person? personResult = await System.Text.Json.JsonSerializer.DeserializeAsync<Person>(msm);
    }
}
```

### Expected behavior

Stream is deserialized into an object:
`personResult == p`

### Actual behavior

```
System.Text.Json.JsonException
  HResult=0x80131500
  Message='0x00' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.<ReadAllAsync>d__65`1.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Program.<Main>d__1.MoveNext() in C:\Users\jvasylenko\Projects\ReproError\ReproError\Program.cs:line 42

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
JsonReaderException: '0x00' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.

```

### Known Workarounds

Trimming null terminators from the end of the byte-array `MemoryStream` that's used as input for deserialization

### Configuration

* .NET 6.0
*  System.Text.Json 6.0.7

**Comment by eiriktsarpalis** [comment] 2022-12-13 12:54
> Now, the data you're deserializing is invalid JSON, so I think it's correct that it throws. 

It's by design, but in the future we might consider adding flags that relax restrictions wrt invalid JSON: See https://github.com/dotnet/runtime/issues/32291

Duplicate of https://github.com/dotnet/runtime/issues/32291.

**Closed by eiriktsarpalis** 2022-12-13 12:54 UTC
Labels: area-System.Text.Json, untriaged
