### ISSUE TITLE
[NET9] [REGRESSION] Gmail API fail with TieredCompilation disabled

### ISSUE THREAD

**Issue by kirsan31** [dotnet/runtime#108969] opened 2024-10-17 11:55 UTC
### Description

Google.Apis.Gmail.v1 call to `GmailService.Users.GetProfile("someId")` fail with _strange_ exception:

> Google.GoogleApiException: Parameter validation failed for "userId" : The parameter value must be a non-empty string

**Only** on .NET9 + `<TieredCompilation>false</TieredCompilation>` (.NET8 in any combinations and .NET9 + `<TieredCompilation>true</TieredCompilation>`  works normally).

### Reproduction Steps

- Build repro app.
- Run .Net9 binary to get an exception and .Net8 to get normal result.

[GmailGetProfile.zip](https://github.com/user-attachments/files/17415050/GmailGetProfile.zip)

### Expected behavior

Must work without _Parameter validation failed_ exception. Repro app must output "Unauthorized" in console.

### Actual behavior

```
Unhandled exception. The service gmail has thrown an exception.
No HttpStatusCode was specified.
No error details were specified.
Google.GoogleApiException: Parameter validation failed for "userId" : The parameter value must be a non-empty string
   at Google.Apis.Requests.ClientServiceRequest`1.AddParameters(RequestBuilder requestBuilder, ParameterCollection inputParameters)
   at Google.Apis.Requests.ClientServiceRequest`1.CreateBuilder()
   at Google.Apis.Requests.ClientServiceRequest`1.CreateRequest(Nullable`1 overrideGZipEnabled)
   at Google.Apis.Requests.ClientServiceRequest`1.ExecuteUnparsedAsync(CancellationToken cancellationToken)
   at Google.Apis.Requests.ClientServiceRequest`1.ExecuteAsync(CancellationToken cancellationToken)
   at GmailGetProfile.Program.Main(String[] args) in ...GmailGetProfile\Program.cs:line 16
   at GmailGetProfile.Program.<Main>(String[] args)
```

### Regression?

Yes it's works in .NET8.

### Known Workarounds

No.

### Configuration

SDK: `9.0.100-rc.2.24474.11`
Runtime: `9.0.0-rc.2.24474.4`
OS: Win11 23H2

**Comment by EgorBo** [comment] 2024-10-17 16:35
Are there any extra steps to run the repro? it prints "Unauthorized" for me

**Comment by EgorBo** [comment] 2024-10-17 16:46
cc @dotnet/jit-contrib (I wasn't able to repro it on macos-arm64/x64, don't have any Windows to test it there).

**Comment by AndyAyersMS** [comment] 2024-10-17 17:36
I can look later today. If anyone else wants to dig in before then, just let me know.

**Comment by hez2010** [comment] 2024-10-17 19:21
Can reproduce on win-x64. 

Didn't investigate too far, to summarize the findings so far:

The issue seems to happen in `ParameterCollection.FromDictionary`.

https://github.com/googleapis/google-api-dotnet-client/blob/6246c9d65cc5a4c4bbaf5fa9524daa96ef1af650/Src/Support/Google.Apis.Core/Requests/Parameters/ParameterCollection.cs#L143

On .NET 8:

the dictionary is

![Image](https://github.com/user-attachments/assets/68596e7b-9f8a-47ba-bca9-0acd39adb48f)

and `ParameterCollection.FromDictionary` yields

![Image](https://github.com/user-attachments/assets/922d4084-4e20-4b18-8edb-3afce6e6bc1d)

While on .NET 9 the dictionary is the same but `ParameterCollection.FromDictionary` yields the following result:

![Image](https://github.com/user-attachments/assets/4a079a8b-c81c-4282-bc8c-cfa6d71e4dc6)

codegen diff (net8.0 - net9.0): https://www.diffchecker.com/JbWCBrJw/

**Comment by AndyAyersMS** [comment] 2024-10-17 21:38
Works with `DOTNET_JitEnablePhysicalPromotion=0`, so possibly related to promotion. FYI @jakobbotsch

**Comment by AndyAyersMS** [comment] 2024-10-17 21:48
@hez2010 looks like you implicated the right method

```
 255: JIT compiled Google.Apis.Requests.Parameters.ParameterCollection:FromDictionary(System.Collections.Generic.IDictionary`2[System.String,System.Object]):Google.Apis.Requests.Parameters.ParameterCollection [FullOpts, IL size=188, code size=715, hash=0xb412e2dc]

set DOTNET_JitEnablePhysicalPromotionRange=b412e2dc
set DOTNET_TieredCompilation=0
(run)
userId : test
userId :
userId :
userId :

set DOTNET_JitEnablePhysicalPromotionRange=0-b412e2db,b412e2dd-ffffffff
set DOTNET_TieredCompilation=0
(run)
userId : test
$.xgafv :
alt :
prettyPrint :
```

**Comment by AndyAyersMS** [comment] 2024-10-17 22:23
We promote a KVP:
```
Picking promotions
Accesses for V03
  [000..016) as System.Collections.Generic.KeyValuePair`2[System.String,System.Object]
lvaGrabTemp returning 36 (V36 tmp28) (a long lifetime temp) called for V03.[000..008).
lvaGrabTemp returning 37 (V37 tmp29) (a long lifetime temp) called for V03.[008..016).

```
Looks like the read back (initialization) of V36 happens in a nested QMARK but the uses are unconditional, so we end up with uninitialized reads later on?
```
Reading back pending replacements before tree with possible exception side effect inside block in try region
  V03.[000..008) -> V36
New statement:
STMT00010 ( ??? ... ??? )
               [000046] DA-X-------                         *  STORE_LCL_VAR int    V11 tmp3         
               [000045] -A-X-------                         \--*  QMARK     int   
               [000036] -----------    if                      +--*  EQ        int   
               [000035] -----------                            |  +--*  LCL_VAR   ref    V10 tmp2         
               [000034] -----------                            |  \--*  CNS_INT   ref    null
               [000044] -A-X-------    if                      \--*  COLON     int   
               [000042] -A-X------- else                          +--*  QMARK     int   
               [000038] -A-X-------    if                         |  +--*  NE        int   
               [000318] -A-X-------                               |  |  +--*  COMMA     long  
               [000317] DA---------                               |  |  |  +--*  STORE_LCL_VAR ref    V36 tmp28        
               [000316] -----------                               |  |  |  |  \--*  LCL_FLD   ref   (RB) V03 loc2         [+0]
               [000037] #--X-------                               |  |  |  \--*  IND       long  
               [000032] -----------                               |  |  |     \--*  LCL_VAR   ref    V10 tmp2          (last use)
```
Seems like a tricky interaction of promotion, QMARK, and EH. Would guess we need to move the readback even earlier, likely in a preceding statement, or else duplicate it on the other conditional paths.

@jakobbotsch I will defer to you on this one.

**Comment by kirsan31** [comment] 2024-10-18 12:22
@JulieLeeMSFT 
.Net **10** really? So the fundamental regression that potentially can break lots of apps -  not meet a service bar for yet not released product?
If this related to `DOTNET_JitEnablePhysicalPromotion` may be it's too early to enable it by default?

**Comment by hez2010** [comment] 2024-10-18 13:11
> .Net 10 really? So the fundamental regression that potentially can break lots of apps - not meet a service bar for yet not released product?

The dotnet mainstream development has been moved to .NET 10. Adding it to 10.0.0 milestone only means that the issue is considered to be fixed at 10.0.0 milestone, i.e., **the current phase**, then it can be **backported** to .NET 9. It doesn't mean you will have to wait for the release of .NET 10 to get the fix.

**Comment by AndyAyersMS** [comment] 2024-10-18 15:20
@kirsan31 we will almost certainly backport a fix for this to .NET 9.

**Comment by jakobbotsch** [comment] 2024-10-21 12:37
The problem is that `InsertPreStatementReadBacks` inserts read backs only for locals that the upcoming statement has uses of. In this case the `QMARK` statement does not have any uses of `V36`, so it does not get handled by it. However, we then end up seeing that there is an indirection in the QMARK that can throw an exception that may result in implicit control flow within the function, which induces its own read back that ends up inside the QMARK.

**Comment by jakobbotsch** [comment] 2024-10-22 10:58
#109107 has the fix for the issue, but this fix won't make it into .NET 9 until the first servicing release.

In the meantime you can work around the problem by setting `DOTNET_JitEnablePhysicalPromotion=0` in the environment before starting the application.

**Closed** 2024-10-22 16:55 UTC
Labels: area-CodeGen-coreclr, in-pr

**Comment by AndyAyersMS** [comment] 2025-02-12 00:13
FYI 9.0.2 is now out, with the fix.
