### ISSUE TITLE
System.Formats.Tar.Tests.TarWriter_WriteEntry_LongFile_Tests.WriteEntry_LongFileSize fails on Mono

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/runtime#88731] opened 2023-07-12 12:11 UTC
It affects both the sync version and the WriteEntry_LongFileSizeAsync one.
It seems to only happen for the Pax entryformat:

```
      System.Formats.Tar.Tests.TarWriter_WriteEntry_LongFile_Tests.WriteEntry_LongFileSize(entryFormat: Pax, size: 8589934592, unseekableStream: False) [FAIL]
        Assert.Equal() Failure
        Expected: 8589934592
        Actual:   0
        Stack Trace:
          /Users/alexander/dev/runtime/src/libraries/System.Formats.Tar/tests/TarWriter/TarWriter.WriteEntry.LongFile.Tests.cs(49,0): at System.Formats.Tar.Tests.TarWriter_WriteEntry_LongFile_Tests.WriteEntry_LongFileSize(TarEntryFormat entryFormat, Int64 size, Boolean unseekableStream)
             at System.Object.InvokeStub_TarWriter_WriteEntry_LongFile_Tests.WriteEntry_LongFileSize(Object , Object , IntPtr* )
          /Users/alexander/dev/runtime/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs(55,0): at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

I'll disable the test for now.

**Comment by carlossanlop** [comment] 2023-07-12 23:02
Thanks, @akoeplinger for disabling it. Do you have a PR? If not, I can send it.

**Comment by carlossanlop** [comment] 2023-07-12 23:03
Duplicate of https://github.com/dotnet/runtime/issues/88271

**Closed by carlossanlop** 2023-07-12 23:03 UTC
Labels: disabled-test, runtime-mono, area-System.Formats.Tar
