### ISSUE TITLE
InvalidCastException from NativeAOT compiler during benchmarkdotnet run

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#106501] opened 2024-08-15 20:28 UTC
I'm using 9.0.0-rc.1.24403.1.

.csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net9.0;net8.0</TargetFrameworks>
    <LangVersion>Preview</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ServerGarbageCollection>true</ServerGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.14.0" />
  </ItemGroup>

</Project>
```

Program.cs
```csharp
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

BenchmarkSwitcher.FromAssembly(typeof(Tests).Assembly).Run(args);

[HideColumns("Job", "Error", "StdDev", "Median", "RatioSD")]
public partial class Tests
{
    private Base _obj = new();

    [Benchmark]
    public int GetValue() => _obj.GetValue();
}

public class Base
{
    public virtual int GetValue() => 42;
}

public class Derived : Base
{
    public override int GetValue() => 48;
}
```

Command:
```
dotnet run -c Release -f net8.0 --filter "*" --runtimes nativeaot8.0 nativeaot9.0
```

.NET 8 run succeeds. .NET 9 run crashes:
```
System.InvalidCastException: Specified cast is not valid.
     at ILCompiler.CompilerTypeSystemContext.EnsureLoadableTypeUncached(TypeDesc) + 0x3eb
     at ILCompiler.CompilerTypeSystemContext.EnsureLoadableType(TypeDesc) + 0x5a
     at ILCompiler.LibraryRootProvider.CheckCanGenerateMethod(MethodDesc) + 0x4c
     at ILCompiler.DependencyAnalysis.TypeMetadataNode.GetStaticDependencies(NodeFactory) + 0x48a
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependenciesImpl(DependencyNodeCore`1) + 0x56
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.GetStaticDependencies(DependencyNodeCore`1) + 0xce
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ProcessMarkStack() + 0xed
     at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer`2.ComputeMarkedNodes() + 0x49
     at ILCompiler.ILScanner.ILCompiler.IILScanner.Scan() + 0x1b
     at ILCompiler.Program.<Run>g__RunScanner|4_0(Program.<>c__DisplayClass4_0&) + 0x1fa
     at ILCompiler.Program.Run() + 0x28ff
     at ILCompiler.ILCompilerRootCommand.<>c__DisplayClass240_0.<.ctor>b__0(ParseResult) + 0x321
```

**Comment by MichalStrehovsky** [comment] 2024-08-15 20:33
What a coincidence - duplicate of #106439 opened 14 hours ago. Will need a BDN fix for .NET 9 due to bar, but also fixed in main (without requiring the BDN fix).

**Closed by MichalStrehovsky** 2024-08-15 20:33 UTC
Labels: area-NativeAOT-coreclr

**Comment by stephentoub** [comment] 2024-08-16 14:01
cc: @adamsitnik
