### ISSUE TITLE
[QUIC] Consider implementing send buffering on .NET side

### ISSUE THREAD

**Issue by CarnaViire** [dotnet/runtime#73691] opened 2022-08-10 13:00 UTC
We currently utilize send buffering on msquic side. Msquic will copy app buffer and return as soon as copy is done.

We had to (temporarily) introduce an additional copy in #72746 to overcome a too-early-user-buffer-release problem on abort. If we will not be able to solve this problem in a different way, it doesn't make sense to have 2x copying, so we should consider switching to app-level buffering.

Using our own send buffering would also allow to optimize the buffering for our usecases better than a general-case msquic buffering. We can also benefit from copying happening in parallel on managed threads in comparison to copying happening sequentially on msquic thread.

*Note*: in case of app level buffering, msquic will hold onto the app buffer and return only after ACK is received.

*Note 2 from msquic docs*: To fill the pipe in this mode, the app is responsible for keeping enough sends pending at all times to ensure the connection doesn't go idle. MsQuic indicates the amount of data the app should keep pending in the QUIC_STREAM_EVENT_IDEAL_SEND_BUFFER_SIZE event. The app should always have at least two sends pending at a time. If only a single send is used, the connection can go idle for the time between that send is completed and the new send is queued.

Some related discussions:
https://github.com/microsoft/msquic/pull/1602#discussion_r633888493
https://github.com/dotnet/runtime/issues/44782#issuecomment-823449304

**Comment by ManickaP** [comment] 2022-09-02 17:39
While discussing this improvement and the issues discovered in https://github.com/dotnet/runtime/issues/72696, one thought was to tie send buffer memory release to `StreamClose`, e.g. Dispose SendBuffer within `MsQuicContextSafeHandle.ReleaseHandle` for the stream. This would also address an issue of not releasing the memory in case QuicStream is not disposed of, but only GCed since there's no finalizer for it.

**Comment by ManickaP** [comment] 2023-07-07 09:58
Closing based on the almost 50% perf regression on the basic send buffering implementation from this PR: https://github.com/dotnet/runtime/pull/88320

IMHO, it'll be really hard to beat already optimized msquic buffering, especially with all `WriteAsync` calls needing to be always serialized.

We can always re-open if we decide to give this another spin.

**Closed by ManickaP** 2023-07-07 09:58 UTC
Labels: tenet-performance, area-System.Net.Quic
