### ISSUE TITLE
System.ExecutionEngineException: Fatal error. Internal CLR error. (0x80131506)

### ISSUE THREAD

**Issue by pccai** [dotnet/runtime#79969] opened 2022-12-25 09:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Fatal error. Internal CLR error. (0x80131506)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1ContentLengthMessageBody.TryReadInternal(System.IO.Pipelines.ReadResult ByRef)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.OnConsumeAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol+<ProcessRequests>d__238`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol+<ProcessRequests>d__238`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Microsoft.AspNetCore.Server.Kestrel.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol+<ProcessRequests>d__238`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Microsoft.AspNetCore.Server.Kestrel.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol+<ProcessRequests>d__238`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Microsoft.AspNetCore.Server.Kestrel.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]].ExecuteFromThreadPool(System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()

### .NET Version

7.0.101

**Comment by davidfowl** [comment] 2022-12-26 04:20
Can you fill in some more environment details? Is this on windows or linux? x64? x86?

**Comment by danmoseley** [comment] 2022-12-26 04:48
Is it consistent? Did it work before - if so what changed? Did it work on 6.0?
Can you make your app simpler until it stops happening?

**Comment by jkotas** [comment] 2022-12-26 22:21
This is most likely duplicate of #78206 or some other GC regions related crash.

- Any change you can share crash dump for the crash?
- Does the crash still repros if you set `set DOTNET_GCName=clrgc` (this will disable the new .NET 7 GC regions feature)?

**Comment by mangod9** [comment] 2022-12-26 23:10
yeah a dump (or repro) would be helpful. Just to clarify the GCName setting suggested by Jan above -- it should be:

`DOTNET_GCName=clrgc.dll` on windows and `DOTNET_GCName=libclrgc.so` on linux

There is also a private shared here in case you want to try it out: https://github.com/dotnet/runtime/issues/78206#issuecomment-1323962997

**Comment by pccai** [comment] 2022-12-27 10:01
windows 10
net 6.0.12  is fine，but when net7 in vs2022 this  CLR error occurs frequently.

**Comment by mangod9** [comment] 2023-01-18 17:34
Hi @pccai, were you able to try clrgc or can share a dump to investigate this further?

**Comment by mangod9** [comment] 2023-02-01 19:19
Closing for now, Please try your scenario with 7.0.2 and reopen if it still repros.

**Closed by mangod9** 2023-02-01 19:19 UTC
Labels: area-GC-coreclr, untriaged, needs-further-triage
