### ISSUE TITLE
.NET Core options binding with JSON files: inconsistent behavior with invalid collection items

### ISSUE THREAD

**Issue by peter-perot** [dotnet/runtime#36129] opened 2019-09-16 13:23 UTC
### Describe the bug

I have detected an inconsistent and annoying behavior with .NET Core options binding when JSON files, arrays and lists come into play. In a nutshell: options that contain invalid data and are items of an array or list, are simply dropped or nulled out.

### To Reproduce

Let's use the following JSON file:

```JSON
{
  "Category": "Bravo",
  "SubOptionsAsArray": [
    {
      "Category": "Bravo"
    },
    {
      "Category": "Zulu"
    }
  ],
  "SubOptionsAsList": [
    {
      "Category": "Bravo"
    },
    {
      "Category": "Zulu"
    }
  ]
}
```

I'm using a property named `Category` on different levels: on top-level, as and array item, and as a list item. This property is an enum can take the values `Alpha` and `Bravo`. Value `Zulu` is considered invalid.

Here is the C# code. Add the JSON file to the project and name it `example.json`.

Used packages:

- `Microsoft.Extensions.Configuration.Json` version 2.2.0
- `Microsoft.Extensions.DependencyInjection` version 2.2.0
- `Microsoft.Extensions.Options.ConfigurationExtensions` version 2.2.0

```csharp
using System.Collections.Generic;
using System.IO;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

namespace Example
{
  class Program
  {
    static void Main(string[] args)
    {
      var configuration = new ConfigurationBuilder()
        .SetBasePath(Directory.GetCurrentDirectory())
        .AddJsonFile("example.json")
        .Build();

      var serviceProvider = new ServiceCollection()
        .Configure<MyOptions>(configuration)
        .BuildServiceProvider();

      var options = serviceProvider.GetRequiredService<IOptions<MyOptions>>().Value;
    }
  }

  public class MyOptions
  {
    public MySubOptions[] SubOptionsAsArray { get; set; }

    public List<MySubOptions> SubOptionsAsList { get; set; }

    public MyCategory Category { get; set; }
  }

  public class MySubOptions
  {
    public MyCategory Category { get; set; }
  }

  public enum MyCategory
  {
    Alpha,
    Bravo
  }
}
```

Set a breakpoint after the line where the `options` variable is set und run the program. Now let's examine the `options` variable:

`options.SubOptionsAsArray.Length` is 2. The first element is the correctly bound element with category _Bravo_, but the second element is _null_.

`options.SubOptionsAsList.Count` is 1. The first element is the correctly bound element with category _Bravo_. The second element with invalid category _Zulu_ has simply been dropped.

IAW: Throwing the options back into a JSON file would look like this:

```JSON
{
  "Category": "Bravo",
  "SubOptionsAsArray": [
    {
      "Category": "Bravo"
    },
    null
  ],
  "SubOptionsAsList": [
    {
      "Category": "Bravo"
    }
  ]
}
```

This is really annoying since I don't get any information on the invalid data.

### Expected behavior

When I write JSON like this...

``` JSON
{
  "Category": "Zulu"
}
```

... and run the program, the framework throws an exception indicating that _Category_ value _Zulu_ cannot be bound. **This is the correct behavior I would expect to be the same with nested data like array or list items, but not silently dropping invalid data or replacing it with `null`.**

The problem is that a user who has mistyped something that is part of the deeper levels of the JSON file, will never get a hint that something went wrong. Instead the invalid part of the JSON file is dropped or nulled out.

**Comment by maryamariyan** [comment] 2020-10-06 22:48
closing as dupe of https://github.com/dotnet/runtime/issues/36015

**Closed by maryamariyan** 2020-10-06 22:48 UTC
Labels: area-Extensions-Configuration
