### ISSUE TITLE
Windows Update can seemingly corrupt .NET Desktop Runtime installations sometimes

### ISSUE THREAD

**Issue by hamarb123** [dotnet/runtime#65217] opened 2022-02-11 21:30 UTC
### Description

I have a WinForms app that written in VB.NET with many dlls written in C#, but I don't think it's the language (in and of itself) is what's causing the issue, it's probably something with that dll's set-up. If you try to run the app, no visible error is provided to the user telling them they need to upgrade, which is not very useful (not that an upgrade should be needed in the first place). My Wpf application doesn't have this issue, but it is written in C#. Since there is a valid installation of .NET Desktop Runtime, it should be able to use that.

I can share my app if you want (I think it would work with any VB.NET WinForms app, but I'm yet to test it and make a minimal repro), here is my runtimeconfig.json though:
<details>
<summary>runtimeconfig.json</summary>
<pre>
{
  "runtimeOptions": {
    "tfm": "net6.0",
    "frameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "6.0.0"
      },
      {
        "name": "Microsoft.WindowsDesktop.App",
        "version": "6.0.0"
      }
    ],
    "configProperties": {
      "System.Reflection.Metadata.MetadataUpdater.IsSupported": false
    }
  }
}
</pre>
</details>
which shows that it needs the .NET Windows Desktop Runtime, which means it should just run with 6.0.1.

### Reproduction Steps

1. Install .NET 6.0.1 Runtime
2. Install .NET 6.0.1 Desktop Runtime
3. Run Windows Update (notice: .NET Runtime will be updated, but Desktop Runtime will not be)
4. Try to run my application

### Expected behavior

The app works exactly as it did before using 6.0.1 if needed, or the desktop runtime is updated as well, or (less preferably than the other 2, but still better than nothing) the app shows an error telling the user to update .NET Desktop Runtime.

### Actual behavior

No error is provided when running the exe to the user, but when running the dll on the command-line, it shows the following:
```
Microsoft Windows [Version 10.0.22000.493]
(c) Microsoft Corporation. All rights reserved.

C:\Users\<username>>dotnet "<dll path>"
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'Microsoft.VisualBasic.Forms, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'Microsoft.VisualBasic.Forms, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

This suggests that somehow it is selecting the wrong runtime.

### Known Workarounds

Force user to install .NET Desktop Runtime 6.0.2 if .NET Runtime 6.0.2 somehow gets installed.

### Configuration

Windows 11 (10.0.22000.493).
Running on arm64, though I doubt the issue is specific to that.

### Other information

It is probably either caused by trying to use 6.0.1, or by not being able to locate "Microsoft.VisualBasic.Forms.dll" of the correct version.

**Comment by Wraith2** [comment] 2022-02-11 22:38
Do you think this might be related to https://github.com/dotnet/winforms/issues/6663 ?

**Comment by hamarb123** [comment] 2022-02-12 10:26
> Do you think this might be related to [dotnet/winforms#6663](https://github.com/dotnet/winforms/issues/6663) ?

That seems likely, I will test re-compiling my app later.

**Comment by RussKie** [comment] 2022-02-15 05:54
Duplicate of https://github.com/dotnet/core/issues/7176

**Closed by RussKie** 2022-02-15 05:54 UTC
Labels: area-Setup, untriaged
