### ISSUE TITLE
Incorrect CA2021 Warning

### ISSUE THREAD

**Issue by sra-michaelgold** [dotnet/runtime#109344] opened 2024-10-29 15:48 UTC
### Description

Using 9.0.100-rc.2.24474.11 SDK

I'm getting incorrect CA2021 warning on valid code.  See repro steps below.
 

### Reproduction Steps

```csharp
IEnumerable<BaseClass<int>> list = [new Implementation()];

var first = list.OfType<Implementation>().First();
Console.WriteLine(first.GetHashCode());


public abstract class BaseClass<T>
{
}

public sealed class Implementation : BaseClass<int>
{
}
```

### Expected behavior

No warning

### Actual behavior

  Program.cs(3, 13): [CA2021] This call will always result in an empty sequence because type 'BaseClass<int>' is incompatible with type 'Implementation' (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2021)

### Known Workarounds

Add NoWarn for CA2021 to csproj, but this is not optimal in case the issue actually exists.

### Other information

9.0.100-rc.2.24474.11 SDK
Running in Rider 2024.2.7
Windows 10 x64

**Comment by vcsjones** [comment] 2024-10-29 21:43
This looks like a duplicate of https://github.com/dotnet/roslyn-analyzers/issues/7357.

I am going to close this as an existing issue has been identified in the appropriate repo, but feel free to re-open if you believe this was closed mistakenly.

**Closed by vcsjones** 2024-10-29 21:43 UTC
Labels: untriaged, needs-area-label

**Comment by sra-michaelgold** [comment] 2024-10-30 12:37
Thanks @vcsjones ! I agree it's a dupe.  Apologies for not seeing the existing issue.
