### ISSUE TITLE
.net core is slow, net.9 even slower, especially BigInteger

### ISSUE THREAD

**Issue by johnnygiter** [dotnet/runtime#108933] opened 2024-10-16 15:48 UTC
1. Net (all versions, 6, 7 8  and comming 9 are all very slow compared to other languages)
I do not expect to be as fast as e.g. rust, but being 10x slower than slow python is a bit of a shame:

https://programming-language-benchmarks.vercel.app/problem/edigits
BigInteger improvements for me are almost not noticable in net 9.0 (max 7%) I expected 200-500%

2. **Regression** - Benchmark below works for me slower than on v8 (despite it's very slow overall comparing to other langs using similar algo )

```
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using BenchmarkDotNet.Configs;
using System;
using System.Numerics;
using BenchmarkDotNet.Jobs;

[DisassemblyDiagnoser]
[SimpleJob(RuntimeMoniker.Net80, baseline: true)]
[SimpleJob(RuntimeMoniker.Net90)]
[GroupBenchmarksBy(BenchmarkLogicalGroupRule.ByMethod)]
public class PerformanceTest
{
    [Benchmark]
    [Arguments(80000)]

    public string Run(int n)
    {
        var result = new System.Text.StringBuilder();
        var k = BinarySearch(n);
        var (p, q) = SumTerms(0, k - 1);
        p += q;
        var a = BigInteger.Pow(new BigInteger(10), n - 1);
        var answer = p * a / q;
        var answerStr = answer.ToString();
        Span<char> sb = stackalloc char[10];
        for (var i = 0; i < n; i += 10)
        {
            var count = i + 10;
            if (count > n)
            {
                count = n;
            }
            for (var j = i; j < i + 10; j++)
            {
                if (j < n)
                {
                    sb[j - i] = answerStr[j];
                }
                else
                {
                    sb[j - i] = ' ';
                }
            }

            result.AppendLine($"{new string(sb)}\t:{count}");
        }
        return result.ToString();
    }

    static (BigInteger, BigInteger) SumTerms(int a, int b)
    {
        if (b == a + 1)
        {
            return (new BigInteger(1), new BigInteger(b));
        }
        var mid = (a + b) / 2;
        var (pLeft, qLeft) = SumTerms(a, mid);
        var (pRight, qRight) = SumTerms(mid, b);
        return (pLeft * qRight + pRight, qLeft * qRight);
    }

    static int BinarySearch(int n)
    {
        var a = 0;
        var b = 1;
        while (!TestK(n, b))
        {
            a = b;
            b *= 2;
        }
        while (b - a > 1)
        {
            var m = (a + b) / 2;
            if (TestK(n, m))
            {
                b = m;
            }
            else
            {
                a = m;
            }
        }
        return b;
    }

    static bool TestK(int n, int k)
    {
        if (k < 0)
        {
            return false;
        }
        var lnKFactorial = k * (Math.Log((double)k) - 1) + 0.5 * Math.Log(Math.PI * 2);
        var log10KFactorial = lnKFactorial / Math.Log(10);
        return log10KFactorial >= (double)(n + 50);
    }

    public static void Main(string[] args)
    {
        var summary = BenchmarkRunner.Run<PerformanceTest>();
        Console.WriteLine(summary);
    }
}

```

```
.NET SDK 9.0.100-rc.2.24474.11
  [Host]   : .NET 8.0.10 (8.0.1024.46610), X64 RyuJIT AVX2
  .NET 8.0 : .NET 8.0.10 (8.0.1024.46610), X64 RyuJIT AVX2
  .NET 9.0 : .NET 9.0.0 (9.0.24.47305), X64 RyuJIT AVX2


| Method | Job      | Runtime  | n     | Mean     | Error   | StdDev  | P95      | Ratio | RatioSD | Code Size |
|------- |--------- |--------- |------ |---------:|--------:|--------:|---------:|------:|--------:|----------:|
| Run    | .NET 8.0 | .NET 8.0 | 80000 | 314.1 ms | 2.51 ms | 5.62 ms | 333.0 ms |  1.00 |    0.02 |  11,613 B |
| Run    | .NET 9.0 | .NET 9.0 | 80000 | 371.6 ms | 0.57 ms | 0.53 ms | 372.5 ms |  1.18 |    0.02 |   9,354 B |
```

**Comment by tannergooding** [comment] 2024-10-16 16:40
Closing this as a duplicate of https://github.com/dotnet/runtime/issues/92184

There was not a significant effort put into improving `BigInteger` in .NET 9 and the above discussion thread already has commentary covering how such benchmarks are not necessarily representative of real world performance, considerations around "why" you can see differences between Python vs .NET and why those differences are expected and semi-reasonable, etc.

`BigInteger` will eventually get improvements and as with any changes the performance differences will vary based on your hardware, inputs, and many other considerations. .NET will likewise continue prioritizing real world performance considerations over simply scoring the highest microbenchmark numbers.

**Closed by tannergooding** 2024-10-16 16:40 UTC
Labels: area-System.Numerics, tenet-performance, untriaged
