### ISSUE TITLE
[NativeAOT] No way to dll export variables?

### ISSUE THREAD

**Issue by Slxdy** [dotnet/runtime#93936] opened 2023-10-24 18:28 UTC
Hi, I'm trying to do the following, but in C# with NativeAOT:
```cpp
extern "C" 
{
  __declspec(dllexport) unsigned long NvOptimusEnablement = 0x00000001;
  __declspec(dllexport) int AmdPowerXpressRequestHighPerformance = 1;
}
```

I have been looking for a way to export variables through NativeAOT, but couldn't find any existing solution.

Can we please get an attribute for exporting constants?
For example:
```cs
[ExportVariable]
public const ulong NvOptimusEnablement = 1;
```

**Comment by teo-tsirpanis** [comment] 2023-10-24 19:46
Maybe you can compile your code C and then [link the resulting object file to your app](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/interop#linking).

**Comment by jkotas** [comment] 2023-10-24 20:35
Duplicate of https://github.com/dotnet/runtime/issues/88598 and https://github.com/dotnet/runtime/issues/60422

> Maybe you can compile your code C and then [link the resulting object file to your app](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/interop#linking).

Yes, this is the suggested workaround.

**Comment by Slxdy** [comment] 2023-10-25 14:57
> Maybe you can compile your code C and then [link the resulting object file to your app](https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/interop#linking).

Hey, thanks for your response. I'm trying to get it to work, but nativeaot doesn't seem to export the lib exports. Do I need to add something to my exports.def file?

**Comment by jkotas** [comment] 2023-10-25 15:04
Yes, you either need to add the symbol to the exports file or you need to mark the export with `__declspec(dllexport)` in the C code (https://learn.microsoft.com/cpp/cpp/dllexport-dllimport)

**Comment by Slxdy** [comment] 2023-10-25 15:21
This is the exact code I'm compiling
```c
extern "C" 
{
  __declspec(dllexport) unsigned long NvOptimusEnablement = 0x00000001;
  __declspec(dllexport) int AmdPowerXpressRequestHighPerformance = 1;
}
```

I compiled it with MSVC, got the .lib file, added the following to an ItemGroup in my csproj:
```xml
<NativeLibrary Include="resources/GraphicsExports.lib" />
```
But when I decompile the final exe, the exports arent there.

**Comment by teo-tsirpanis** [comment] 2023-10-25 15:23
You should include the `.obj` file.

**Comment by Slxdy** [comment] 2023-10-25 15:34
> You should include the `.obj` file.

Yep, that works. Thanks

**Closed** 2023-10-25 15:35 UTC
Labels: question, untriaged, area-NativeAOT-coreclr
