### ISSUE TITLE
Test failure System.Diagnostics.Tests.InstanceDataTests.InstanceDataCollectionCollection_CopyTo

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#67634] opened 2022-04-06 02:32 UTC
Run: [runtime-coreclr libraries-jitstress2-jitstressregs 20220402.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1696536&view=ms.vss-test-web.build-test-results-tab&runId=46286920&resultId=175706&paneView=debug)

Failed test:
```
net7.0-windows-Release-x64-CoreCLR_checked-jitstress2_jitstressregs2-Windows.10.Amd64.Open

- System.Diagnostics.Tests.InstanceDataTests.InstanceDataCollectionCollection_CopyTo
- System.Diagnostics.Tests.InstanceDataTests.InstanceDataCollection_GetItem_ExistingCounter
- System.Diagnostics.Tests.InstanceDataTests.InstanceDataCollection_GetKeys
- System.Diagnostics.Tests.InstanceDataTests.InstanceDataCollection_GetValues
- System.Diagnostics.Tests.InstanceDataTests.InstanceDataCollection_NullTest
- System.Diagnostics.Tests.InstanceDataTests.InstanceDataCollectionCollection_Contains_Valid
- System.Diagnostics.Tests.InstanceDataTests.InstanceDataCollectionCollection_GetKeys
- System.Diagnostics.Tests.InstanceDataTests.InstanceDataCollectionCollection_Contains_inValid
- System.Diagnostics.Tests.InstanceDataTests.InstanceDataCollectionCollection_GetItem_Invalid
- System.Diagnostics.Tests.InstanceDataTests.InstanceDataCollectionCollection_GetValues
```
**Error message:**
```
System.AggregateException : One or more errors occurred. (Category 'Processor' does not exist.) (Category 'Processor' does not exist.) (Category 'Processor' does not exist.) (Category 'Processor' does not exist.) (Category 'Processor' does not exist.) (Category 'Processor' does not exist.) (Category 'Processor' does not exist.) (Category 'Processor' does not exist.) (Category 'Processor' does not exist.) (Category 'Processor' does not exist.)
---- System.InvalidOperationException : Category 'Processor' does not exist.
---- System.InvalidOperationException : Category 'Processor' does not exist.
---- System.InvalidOperationException : Category 'Processor' does not exist.
---- System.InvalidOperationException : Category 'Processor' does not exist.
---- System.InvalidOperationException : Category 'Processor' does not exist.
---- System.InvalidOperationException : Category 'Processor' does not exist.
---- System.InvalidOperationException : Category 'Processor' does not exist.
---- System.InvalidOperationException : Category 'Processor' does not exist.
---- System.InvalidOperationException : Category 'Processor' does not exist.
---- System.InvalidOperationException : Category 'Processor' does not exist.


Stack trace
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen) in /_/src/libraries/Common/tests/TestUtilities/System/RetryHelper.cs:line 48
   at System.Diagnostics.Tests.Helpers.RetryOnAllPlatforms[T](Func`1 func) in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/Helpers.cs:line 0
   at System.Diagnostics.Tests.InstanceDataTests.InstanceDataCollectionCollection_CopyTo() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/InstanceDataTests.cs:line 118
----- Inner Stack Trace #1 (System.InvalidOperationException) -----
   at System.Diagnostics.PerformanceCounterLib.GetCategorySample(String machine, String category) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs:line 847
   at System.Diagnostics.PerformanceCounterCategory.ReadCategory() in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs:line 549
   at System.Diagnostics.Tests.InstanceDataTests.<>c__DisplayClass11_0.<GetInstanceDataCollectionCollection>b__1() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/InstanceDataTests.cs:line 128
   at System.Diagnostics.Tests.Helpers.<>c__DisplayClass12_0`1.<RetryOnAllPlatforms>b__0() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/Helpers.cs:line 75
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen) in /_/src/libraries/Common/tests/TestUtilities/System/RetryHelper.cs:line 40
----- Inner Stack Trace #2 (System.InvalidOperationException) -----
   at System.Diagnostics.PerformanceCounterLib.GetCategorySample(String machine, String category) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs:line 847
   at System.Diagnostics.PerformanceCounterCategory.ReadCategory() in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs:line 549
   at System.Diagnostics.Tests.InstanceDataTests.<>c__DisplayClass11_0.<GetInstanceDataCollectionCollection>b__1() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/InstanceDataTests.cs:line 128
   at System.Diagnostics.Tests.Helpers.<>c__DisplayClass12_0`1.<RetryOnAllPlatforms>b__0() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/Helpers.cs:line 75
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen) in /_/src/libraries/Common/tests/TestUtilities/System/RetryHelper.cs:line 40
----- Inner Stack Trace #3 (System.InvalidOperationException) -----
   at System.Diagnostics.PerformanceCounterLib.GetCategorySample(String machine, String category) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs:line 847
   at System.Diagnostics.PerformanceCounterCategory.ReadCategory() in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs:line 549
   at System.Diagnostics.Tests.InstanceDataTests.<>c__DisplayClass11_0.<GetInstanceDataCollectionCollection>b__1() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/InstanceDataTests.cs:line 128
   at System.Diagnostics.Tests.Helpers.<>c__DisplayClass12_0`1.<RetryOnAllPlatforms>b__0() in /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/Helpers.cs:line 75
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc, Predicate`1 retryWhen) in /_/src/libraries/Common/tests/TestUtilities/System/RetryHelper.cs:line 40
----- Inner Stack Trace #4 (System.InvalidOperationException) -----
   at System.Diagnostics.PerformanceCounterLib.GetCategorySample(String machine, String category) in /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs:line 847
   at System.Diagnostics.PerformanceCounterCategory.ReadCategory() in /_/src/librari
```

**Comment by danmoseley** [comment] 2022-04-07 19:00
dupe of https://github.com/dotnet/runtime/issues/60933

issue believe understood: https://github.com/dotnet/runtime/issues/60933#issuecomment-958146471

**Closed by danmoseley** 2022-04-07 19:00 UTC
Labels: os-windows, JitStress, arch-x64, untriaged, area-System.Diagnostics.PerformanceCounter
