### ISSUE TITLE
Marshal.PtrToStructure CLR Error on .NET 6.0

### ISSUE THREAD

**Issue by darius-iko** [dotnet/runtime#76861] opened 2022-10-11 05:53 UTC
### Description

Here is my test code:

`                
                var vtablePtr = Native.DerivedClassPtrToTestClassPtr(derivedVTablePtr);

                {
                    // IBase1 + IBase2
                    var ibase2Ptr = Native.TestClassPtrToIBase2Ptr(vtablePtr);
                    IntPtr vt = Marshal.ReadIntPtr(ibase2Ptr.Ptr);

                    // This will error on .NET 6 !!!
                    **var ibase2 = Marshal.PtrToStructure<Native.IBase2>(vt);**

                    Console.WriteLine($"C#, Result: {ibase2.IBase1Method1(new Native.IBase1Ptr { Ptr = ibase2Ptr.Ptr }, 10000)}");
                    Console.WriteLine($"C#, Result: {ibase2.IBase1Method2(new Native.IBase1Ptr { Ptr = ibase2Ptr.Ptr }, 10000)}");
                    Console.WriteLine($"C#, Result: {ibase2.IBase1Method3(new Native.IBase1Ptr { Ptr = ibase2Ptr.Ptr }, 10000)}");
                    Console.WriteLine($"C#, Result: {ibase2.IBase2Method1(ibase2Ptr, 10000)}");
                    Console.WriteLine($"C#, Result: {ibase2.IBase2Method2(ibase2Ptr, 10000)}");
                    Console.WriteLine();
                }
`

Marshal.PtrToStructure does not error when the project target framework is set to .NET 5.0, but that code will become CLR error when the target framework is set to .NET 6.
![image](https://user-images.githubusercontent.com/8023913/195007160-384cf260-776c-4d08-a0dd-649f297d7e17.png)

Here is the project solution:
[ConsoleAppError.zip](https://github.com/dotnet/runtime/files/9751509/ConsoleAppError.zip)

### Reproduction Steps

Marshal.PtrToStructure does not error when the project target framework is set to .NET 5.0, but that code will become CLR error when the target framework is set to .NET 6.

### Expected behavior

Marshal.PtrToStructure does not error on .NET 5 and .NET 6.

### Actual behavior

Marshal.PtrToStructure does not error when the project target framework is set to .NET 5.0, but that code will become CLR error when the target framework is set to .NET 6.

### Regression?

yes, it works on .NET 5.

### Configuration

.NET 6
Windows 10
x64

**Comment by elinor-fung** [comment] 2022-10-19 01:05
Thank you for the repro project the actual error is from `Marshal.GetDelegateForFunctionPointer`
```
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointerInternal(IntPtr ptr, Type t)
   at System.Runtime.InteropServices.Marshal.PtrToStructureHelper(IntPtr ptr, Object structure, Boolean allowValueClasses)
   at System.Runtime.InteropServices.Marshal.PtrToStructure[T](IntPtr ptr)
   at ConsoleAppError.TestClass.TestAll() in C:\Users\elfung\Downloads\ConsoleAppError\ConsoleAppError\ConsoleAppError\TestClass.cs:line 27
   at ConsoleAppError.Program.Main(String[] args) in C:\Users\elfung\Downloads\ConsoleAppError\ConsoleAppError\ConsoleAppError\Program.cs:line 47
```
when trying to handle the `IBase2MethodInt` delegate field on `IBase2`.

We hit the below
https://github.com/dotnet/runtime/blob/51e3afb2ba42609c3711cb50fb5eaa6800bc1fde/src/coreclr/jit/importercalls.cpp#L4152-L4155
because the first argument for a `ThisCall` function is expected to be a pointer, but it is defined as a struct.
```c#
[UnmanagedFunctionPointer(CallingConvention.ThisCall)]
public delegate int IBase2MethodInt(IBase2Ptr ptr, int par);
```

@darius-iko could you try switching your `thiscall` delegates to take a pointer instead?

@AaronRobinsonMSFT @jkoritzinsky I think .NET 5 is allowing blittable structs as the first argument for a `thiscall` delegate and we ended up being more strict about the argument type when we pushed some of the handling from interop to the JIT. While it does manifest as a regression from .NET 5, I think the current behaviour is technically correct and would rather avoid adding back any handling for the previous behaviour. Thoughts?

**Comment by AaronRobinsonMSFT** [comment] 2022-10-19 14:54
> While it does manifest as a regression from .NET 5, I think the current behaviour is technically correct and would rather avoid adding back any handling for the previous behaviour. Thoughts?

Agree.

Open to changes if there is a large enough impact to the community though, however I'm doubtful this impacts many since it has been this way for a few releases.

**Comment by darius-iko** [comment] 2022-10-22 10:37
@elinor-fung could you fix the project solution I provided in the first post and repost the fixed solution? I got that solution from other place and I am new to CLR topics.

**Comment by elinor-fung** [comment] 2022-10-25 17:40
@darius-iko The key part is changing the delegate to take an `IntPtr` as the first argument instead of the structs. This is what was causing the marshalling to fail.
```diff
[UnmanagedFunctionPointer(CallingConvention.ThisCall)]
-public delegate int IBase1MethodInt(IBase1Ptr ptr, int par);
+public delegate int IBase1MethodInt(IntPtr ptr, int par);

[UnmanagedFunctionPointer(CallingConvention.ThisCall)]
-public delegate int IBase2MethodInt(IBase2Ptr ptr, int par);
+public delegate int IBase2MethodInt(IntPtr ptr, int par);
```

And then when calling it, pass in the pointer directly rather than wrapping it in a struct. For example:
```diff
-Console.WriteLine($"C#, Result: {ibase2.IBase1Method1(new Native.IBase1Ptr { Ptr = ibase2Ptr.Ptr }, 10000)}");
+Console.WriteLine($"C#, Result: {ibase2.IBase1Method1(ibase2Ptr.Ptr, 10000)}");
```

This is an updated version of the `TestClass.cs` file from your project (renamed to .txt for upload). It is the only thing that needs to change.
[TestClass.txt](https://github.com/dotnet/runtime/files/9862602/TestClass.txt)

**Comment by darius-iko** [comment] 2022-10-26 01:16
@elinor-fung Thank you

**Comment by elinor-fung** [comment] 2022-10-27 00:04
@darius-iko Does that work for you? Do you have any other concerns here?

**Comment by darius-iko** [comment] 2022-10-27 12:35
@elinor-fung yes, it works. Thank you.

**Comment by elinor-fung** [comment] 2022-10-27 16:55
Glad to hear it. I'm going to close this then.

**Closed by elinor-fung** 2022-10-27 16:55 UTC
Labels: area-Interop-coreclr, needs-further-triage
