### ISSUE TITLE
[wasm] Blazor project failing to publish on windows due to a unicode character in the path

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#87877] opened 2023-06-21 19:11 UTC
`Wasm.Build.Tests.Blazor.BuildPublishTests.WithDllImportInMainAssembly`:

```
          Expected 0 exit code but got 1: C:\\helix\\work\\workitem\\e\\dotnet-latest\\dotnet.exe publish ...
          
          at Wasm.Build.Tests.CommandResult.EnsureExitCode(Int32 expectedExitCode, String messagePrefix, Boolean suppressOutput) in /_/src/mono/wasm/Wasm.Build.Tests/Common/CommandResult.cs:line 44
          at Wasm.Build.Tests.CommandResult.EnsureSuccessful(String messagePrefix, Boolean suppressOutput) in /_/src/mono/wasm/Wasm.Build.Tests/Common/CommandResult.cs:line 28
          at Wasm.Build.Tests.BuildTestBase.BlazorBuildInternal(String id, String config, Boolean publish, Boolean setWasmDevel, String[] extraArgs) in /_/src/mono/wasm/Wasm.Build.Tests/BuildTestBase.cs:line 610
          at Wasm.Build.Tests.BuildTestBase.BlazorPublish(BlazorBuildOptions options, String[] extraArgs) in /_/src/mono/wasm/Wasm.Build.Tests/BuildTestBase.cs:line 564
          at Wasm.Build.Tests.Blazor.BuildPublishTests.WithDllImportInMainAssembly(String config, Boolean build, Boolean publish) in /_/src/mono/wasm/Wasm.Build.Tests/Blazor/BuildPublishTests.cs:line 163
        --- End of stack trace from previous location ---
```

```
Fatal: Failed opening 'C:\helix\work\workitem\e\wbt\blz_dllimp_Debug_?publish\obj\Debug\net8.0\wasm\for-publish\dotnet.native.wasm' (TaskId:269)

emcc : error : 'C:\helix\work\workitem\e\dotnet-latest\packs\Microsoft.NET.Runtime.Emscripten.3.1.34.Sdk.win-x64\8.0.0-preview.6.23312.1\tools\bin\wasm-opt --post-emscripten -Oz --low-memory-unused --zero-filled-
memory --pass-arg=directize-initial-contents-immutable --strip-producers C:\helix\work\workitem\e\wbt\blz_dllimp_Debug_\u7149publish\obj\Debug\net8.0\wasm\for-publish\dotnet.native.wasm -o C:\helix\work\workitem\e\wbt\blz_dllimp_De
bug_\u7149publish\obj\Debug\net8.0\wasm\for-publish\dotnet.native.wasm -g --mvp-features --enable-exception-handling --enable-mutable-globals --enable-sign-ext --enable-simd' failed (returned 1) [C:\helix\work\workitem\e\wbt\blz_dl
limp_Debug_煉publish\blz_dllimp_Debug_煉publish.csproj]
```

**Comment by ilonatommy** [comment] 2023-07-11 11:03
It's a duplicate of https://github.com/dotnet/runtime/issues/83497. They got disabled then and I honestly have no idea how to fix the problem. I will devote some more time to this today and in case I have results, will post them on the original issue. Closing this one.

**Closed by ilonatommy** 2023-07-11 11:03 UTC
Labels: arch-wasm, area-Build-mono, test-failure
