### ISSUE TITLE
Reflection does not respect unmanaged constraint

### ISSUE THREAD

**Issue by quixoticaxis** [dotnet/runtime#102017] opened 2024-05-08 13:37 UTC
### Description

Reflection facilities ignore `unmanaged` constraint thus enabling the creation of invalid types

### Reproduction Steps

Run the code.

```csharp
using System;

var openGeneric = typeof(UnmanagedConstrainedImplementation<>);
var closedGeneric = openGeneric.MakeGenericType(typeof(Managed));

var invalid  = (IGeneralInterface<Managed>)Activator.CreateInstance(closedGeneric)!;
invalid.Call(new());

public interface IGeneralInterface<T>
{
    void Call(T value);
}

public class UnmanagedConstrainedImplementation<T>
    : IGeneralInterface<T>
where T : unmanaged
{
    public void Call(T value)
    {
    }
}

public record struct Managed(object One, object Other);
```

### Expected behavior

The program throws.

### Actual behavior

The program runs to completion successfully.

### Regression?

No.

### Known Workarounds

It is possible to check constraints manually.

### Configuration

Not specific to configuration.

### Other information

Related to #102016.
IMHO, `MakeGenericType` should check the constraint. Otherwise, it is not clear what the extent of this API responsibilities is: it does check `struct` constraint, but treats `unmanaged` exactly the same, so it does check some constraints while not checking the others.

**Comment by jkotas** [comment] 2024-05-08 15:56
This is by design. `unmanaged` constraint is C# only concept. The runtime knows nothing about it.

**Comment by jkotas** [comment] 2024-05-08 15:58
Duplicate of https://github.com/dotnet/runtime/issues/12420

**Closed** 2024-05-08 19:01 UTC
Labels: area-System.Reflection, untriaged
