### ISSUE TITLE
HttpClientFactory support for keyed DI

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#89755] opened 2023-08-01 02:27 UTC
_Updated by @CarnaViire_

_**UPD:** Added Alternative Designs section, added opt-out API to the proposal_

_**UPD2:** Punted Scope Mismatch fix_

------

HttpClientFactory allows for named clients. The new keyed DI feature can be used to resolve the clients by their name.

## API

```c#
namespace Microsoft.Extensions.DependencyInjection;

public static partial class HttpClientBuilderExtensions // existing
{
    public static IHttpClientBuilder AddAsKeyedScoped(this IHttpClientBuilder builder) {} // new
    // alternatives:
    //   AsKeyed(this IHttpClientBuilder builder, ServiceLifetime lifetime)
    //   SetKeyedLifetime(this IHttpClientBuilder builder, ServiceLifetime lifetime)

    // UPD: optional -- opt-out API
    public static IHttpClientBuilder RemoveAsKeyed(this IHttpClientBuilder builder) {} // new
    // alternatives:
    //   DropKeyed(this IHttpClientBuilder builder)
    //   DisableKeyedLifetime(this IHttpClientBuilder builder)
}
```

## Usage

```c#
services.AddHttpClient("foo", c => c.BaseAddress = new Uri("https://foo.example.com"))
    .UseSocketsHttpHandler(h => h.UseCookies = false)
    .AddHttpMessageHandler<MyAuthHandler>()
    .AddAsKeyedScoped();

services.AddHttpClient("bar")
    .AddAsKeyedScoped()
    .ConfigureHttpClient(c => c.BaseAddress = new Uri("https://bar.example.com"));

services.AddHttpClient<BazClient>(c => c.BaseAddress = new Uri("https://baz.example.com"))
    .RemoveAsKeyed(); // explicitly opt-out

// ...

public class MyController
{
    public MyController(
        [FromKeyedServices("foo")] HttpClient fooClient,
        [FromKeyedServices("bar")] HttpClient barClient)
    {
        _fooClient = fooClient;
        _barClient = barClient;
    }
}

```

Also, should be able to do the following

```c#
services.ConfigureHttpClientDefaults(
    b => b.AddAsKeyedScoped()); // "AnyKey"-like registration -- all clients opted in
```

### 1. Why opt-in and not on by default

Opting _in_ rather than out, because it changes the lifetime from "essentially Transient" to Scoped.
([**UPD2:** _punted_] ~~Plus we expect to fix the scope mismatch problem described by https://github.com/dotnet/runtime/issues/47091, in case Keyed Services infra (`[FromKeyedServices...]`) is used to inject a client -- but this fix _must_ be _opt-in_ in one way or the other, at least in this release~~)

Also I believe there's no straightforward API to un-register a service from service collection once added -- I believe it's done by manually removing the added descriptor from the service collection.

(We can consider making keyed registration a default in the _next_ release, but we'd need to think about good way to opt-out then)

**UPD:** Added opt-out API to the proposal

### 2. Why only Keyed Scoped (and not Keyed Transient)

`HttpClient` is `IDisposable`, and we want to avoid multiple instances being captured by the service provider. Asking for a "new" client each time is a part of `HttpClientFactory` guidelines, but DI will capture all `IDisposable`s and hold them until the end of the application (for a root provider; or the end of the scope for a scope provider). Captured Transients will break and/or delay rotation clean up, resulting in a memory leak. There's no way to avoid the capturing that I'm aware of.

### 3. How it should be used in Singletons

By using the "old way" = using `IHttpClientFactory.CreateClient()` -- this will continue working _as before_ = creating a _scope per handler lifetime_.

### 4. What about Typed Clients

If opting into KeyedScoped, Typed clients ~~will~~ [**UPD2:** can] be re-registered as scoped services, rather than transients. (This was actually a long-existing ask that we couldn't implement without some kind of opt-in https://github.com/dotnet/runtime/issues/36067)

This will mean that the Typed clients will stop working in Singletons -- but them "working" there is actually a pitfall, since they're captured for the whole app lifetime and thus not able to participate in handler rotation.

Given that a Typed client is tied with a single named client, it doesn't make much sense to register it as _keyed_. I see a Typed client as functionally analogous to a service with a `[FromKeyedServices...]` dependance on a named client with name = service type name. See the example below.

<details>

```c#
services.AddHttpClient<BazClient>(c => c.BaseAddress = new Uri("https://baz.example.com"))
    .AddAsKeyedScoped();

public class BazClient
{
    public BazClient(
        HttpClient httpClient,
        ISomeOtherService someOtherDependency)
    {
        _httpClient = httpClient;
        _someOtherDependency = someOtherDependency;
    }
}

// -- EQUAL TO --

services.AddScoped<BazClient>();
services.AddHttpClient(nameof(BazClient), c => c.BaseAddress = new Uri("https://baz.example.com"))
    .AddAsKeyedScoped();

public class BazClient
{
    public BazClient(
        [FromKeyedServices(nameof(BazClient))] HttpClient httpClient,
        ISomeOtherService someOtherDependency)
    {
        _httpClient = httpClient;
        _someOtherDependency = someOtherDependency;
    }
}
```

FWIW I'd even suggest moving away from the Typed Client approach and substitute it with the keyed approach instead. It will also give more freedom if e.g. multiple instances of a "typed client" with different named clients are needed:

```c#
services.AddKeyedScoped<IClient, MyClient>(KeyedService.AnyKey);

services.AddHttpClient("foo", c => c.BaseAddress = new Uri("https://foo.example.com")).AddAsKeyedScoped();
services.AddHttpClient("bar", c => c.BaseAddress = new Uri("https://bar.example.com")).AddAsKeyedScoped();

public class MyClient : IClient
{
    public MyClient([ServiceKey] string name, IServiceProvider sp)
    {
        _httpClient = sp.GetRequiredKeyedService<HttpClient>(name);
    }
}

// ...

provider.GetRequiredKeyedService<IClient>("foo"); // depends on "foo" client
provider.GetRequiredKeyedService<IClient>("bar"); // depends on "bar" client

provider.GetRequiredKeyedService<IClient>("bad-name"); // throws, as no keyed HttpClient with such name exists
```

</details>

## Alternative Designs

These are based around passing the lifetime as a parameter to avoid multiple methods. This is different from ordinary DI registrations, but then again, HttpClientFactory is _already_ a different API set.

#### `AsKeyed(ServiceLifetime)` +  `DropKeyed()`

   - ➕ minimalistic
   - ➕ allows for other lifetimes
   - ❔ no "paired" opt-out verb (like Add-Remove) to use
       - used `DropKeyed` instead. Inspiration:
           - `SocketOptionName.DropMembership` (paired with `AddMembership`)
           - `UdpClient.DropMulticastGroup` (paired with `JoinMulticastGroup`) 
   - other similar `AsKeyed` alternatives:
       - `Keyed(ServiceLifetime)` -- ➕ even more minimalistic
       - `AddAsKeyed(ServiceLifetime)` -- ❔ pairs with the alternative `RemoveAsKeyed`
   - other similar `DropKeyed` alternatives:
       - `RemoveAsKeyed` -- ❔ from main proposal, with "As" inside

```c#
// namespace Microsoft.Extensions.DependencyInjection
// classHttpClientBuilderExtensions

public static IHttpClientBuilder AsKeyed(this IHttpClientBuilder builder, ServiceLifetime lifetime) {}

// --- usage ---

services.AddHttpClient("foo")
    .AddHttpMessageHandler<MyAuthHandler>()
    .AsKeyed(ServiceLifetime.Scoped);

services.AddHttpClient("bar")
    .AsKeyed(ServiceLifetime.Scoped);

services.AddHttpClient("baz")
    .DropKeyed();
```

#### `SetKeyedLifetime(ServiceLifetime)` + `DisableKeyedLifetime()`

   - ➕ allows for other lifetimes
   - ➕ makes sense even if/when the keyed registration is done by default (when used to change an already set lifetime)
   - ❔ aligns with with `SetHandlerLifetime(TimeSpan)` -- though also might be a bit confusing
   - ❔ "Disable" is not an actual pair for "Set" either, but `SetKeyedLifetime(null)` or `ClearKeyedLifetime()` are not clear enough
   - other similar alternatives:
       - `EnableKeyedLifetime(ServiceLifetime)` -- ➕ aligns with `DisableKeyedLifetime`
       - `AddKeyedLifetime(ServiceLifetime)` -- ❔ hints that a service descriptor will be _added_ to the service collection (e.g. if called multiple times, it will be added multiple times)
       - `SetKeyedServiceLifetime(ServiceLifetime)` -- ❔ this one doesn't clash with `SetHandlerLifetime` that much, but is more bulky

```c#
// namespace Microsoft.Extensions.DependencyInjection
// classHttpClientBuilderExtensions

public static IHttpClientBuilder SetKeyedLifetime(this IHttpClientBuilder builder, ServiceLifetime lifetime) {}
public static IHttpClientBuilder DisableKeyedLifetime(this IHttpClientBuilder builder) {}


// --- usage ---

services.AddHttpClient("foo")
    .AddHttpMessageHandler<MyAuthHandler>()
    .SetKeyedLifetime(ServiceLifetime.Scoped);

services.AddHttpClient("bar")
    .SetKeyedLifetime(ServiceLifetime.Scoped);

services.AddHttpClient("baz")
    .DisableKeyedLifetime();
```

### Some dismissed alternative namings/designs

<details>

- `AddHttpClient(...., ServiceLifetime)` overload with a new parameter -- there are already _20 (!!) overloads_ of `AddHttpClient`, and we'd like to be able to opt-in in all configuration approaches (including `ConfigureHttpClientDefaults`)
- `AddKeyedScoped()` (without "As") -- conflicts with existing APIs like `AddHttpMessageHandler` which adds to the _client_, not to the service collection
- Anything other than `Add`, e.g. `Register...` -- doesn't align with ServiceCollection APIs, only `Add..`/`TryAdd..` is used there
    - **UPD:** AsKeyed and SetKeyedLifetime made way into Alternative Design section
- `AddKeyedClient()`, `AddKeyedScopedHttpClient()`, `AddScopedClient()`, `AddHttpClientAsKeyedScoped()`,... -- not clear that _not only_ HttpClient will be registered, but also the related HttpMessageHandler chain and, if present, a related Typed client.
- `AddKeyedServices()`, `AddToKeyedServices()` -- not clear that it will be _scoped_

</details>

---

_Old proposal by @CarnaViire_

<details>

```c#
namespace Microsoft.Extensions.DependencyInjection;

public static partial class HttpClientBuilderExtensions
{
    public static IHttpClientBuilder AddAsKeyedTransient(this IHttpClientBuilder builder) {}
    public static IHttpClientBuilder AddAsKeyedScoped(this IHttpClientBuilder builder) {}
}
```

Usage:

```c#
services.AddHttpClient("foo", c => c.BaseAddress = new Uri("https://foo.example.com"))
    .UseSocketsHttpHandler(h => h.UseCookies = false)
    .AddHttpMessageHandler<MyAuthHandler>()
    .AddAsKeyedTransient();

services.AddHttpClient("bar")
    .AddAsKeyedScoped()
    .ConfigureHttpClient(c => c.BaseAddress = new Uri("https://bar.example.com"));

services.AddHttpClient<BazClient>(c => c.BaseAddress = new Uri("https://baz.example.com"))
    .AddAsKeyedScoped();
```

Alternatives:

```c#
services.AddHttpClient("foo")
    .AddKeyedServices(); // forces transient-only

// -OR-

services.AddHttpClient("foo")
    .AddClientAsKeyedTransient();
    .AddMessageHandlerAsKeyedScoped();

// -OR-

enum ClientServiceType
{
    NamedClient,
    TypedClient,
    MessageHandler
}

services.AddHttpClient("foo")
    .AddKeyedService(ClientServiceType.NamedClient, ServiceLifetime.Transient)
    .AddKeyedService(ClientServiceType.MessageHandler, ServiceLifetime.Scoped);
```

</details>

--------

_Original issue by @JamesNK_

<details>

HttpClientFactory allows for named clients. The new keyed DI feature should be used to resolve clients by their name.

Required today:

```cs
services.AddHttpClient("adventureworks", c => c.BaseAddress = new Uri("https://www.adventureworks.com"));
services.AddHttpClient("contoso", c => c.BaseAddress = new Uri("https://www.contoso.com"));

public class MyController
{
    public MyController(IHttpClientFactory httpClientFactory)
    {
        _adventureWorksClient = httpClientFactory.CreateClient("adventureworks");
        _contosoClient = httpClientFactory.CreateClient("contoso");
    }
}
```

With keyed DI:

```cs
services.AddHttpClient("adventureworks", c => c.BaseAddress = new Uri("https://www.adventureworks.com"));
services.AddHttpClient("contoso", c => c.BaseAddress = new Uri("https://www.contoso.com"));

public class MyController
{
    public MyController(
        [FromKeyedServices("adventureworks")] HttpClient adventureWorksClient,
        [FromKeyedServices("contoso")] HttpClient contosoClient)
    {
        _adventureWorksClient = adventureWorksClient;
        _contosoClient = contosoClient;
    }
}
```

Also would support multiple typed clients with different names. I think there is validation against doing that today, so need to consider how to change validation to allow it.

</details>

**Comment by karelz** [comment] 2023-08-01 16:29
Triage: We should try to integrate with KeyedServices new feature if it is low cost. It will avoid introducing potential breaking changes in next release.

**Comment by karelz** [comment] 2023-08-14 19:01
Moving it to 9.0 per discussion in https://github.com/dotnet/runtime/pull/90272#issuecomment-1677820701

**Comment by julealgon** [comment] 2024-07-10 14:19
I'm sad to see @JamesNK original proposal not be the one used in the end here and instead you keep piling on special casing and custom stuff into this nasty `AddHttpClient` hack to a missing "dependent service" registration feature in the container.

With each extra custom API that gets added like this, you make the whole DI system more and more complicated to use.

At least James' original idea intended to remove some of the "custom" nature of the method and rely on the new keyed service support. Now it will be _even more custom_ with extra API additions.

I've made this point in a few other issues with a few different folks before, but I think you should _really_ reconsider this for the long term here. What the DI framework needs is a way to indicate a dependent service registration/configuration that works not only for `HttpClient` but generically.

`HttpClient` could leverage it, named `IOptions` could leverage it, `ILogger` could leverage it.

You keep creating special cases around each and that will just not scale in the long term IMHO.

**Comment by CarnaViire** [comment] 2024-07-11 01:45
@halter73 

> I think we might want to consider AsKeyedScoped.

It was actually the first name I considered, and then I forgot to include it in the list 🙈 The problem with `AsKeyedScoped` is that while it looks really nice if used right after `AddHttpClient`:

```c#
services.AddHttpClient("foo").AsKeyedScoped(); // nice!
```

but as soon as it's placed after any other configuration methods, it becomes super confusing, like it is no longer about the client, but about the previous item:

```c#
services.AddHttpClient("foo")
    .AddHttpMessageHandler(...).AsKeyedScoped(); // is it about the additional handler?

services.AddHttpClient("foo")
    .UseSocketsHttpHandler(...).AsKeyedScoped(); // is it about SocketsHttpHandler?

services.AddHttpClient("foo")
    .SetHandlerLifetime(...).AsKeyedScoped(); // ???
```

> it'd be nice if service registrations could opt-out of automatic disposal. ... for something like this feature to make use of it, it would need to be configurable per ServiceDesriptor.

That would be PERFECT actually. I wonder if that's something that could be squeezed into 9.0 (sweet dreams 😅)

This would make transient clients "safe" from the memory leak, so that would mean that we can (at least) bring back `AddAsKeyedTransient` from the first version of my proposal 😄

And then we even technically _can_ consider `AddAsKeyedTransient` being called by default (but for that I need to dig up the investigations from last year as to why _exactly_ we then decided that default wouldn't work so we must have an API -- I vaguely remember that there was a problem caused by DI containers that don't support Keyed services)

> What if we made the keyed HttpClient registration a singleton?

Some time ago, we actually did briefly entertain the idea of pushing the rotation logic down -- into some kind of a _"magic handler"_. This sounds very close to what you were proposing, but with a "wrapper" handler instead of a "wrapper" client. I still would like to investigate this approach in the future. But this would most possibly require an untrivial amount of time 😢

So while the idea is tempting, it definitely will not fit in 9.0 😢

**Comment by CarnaViire** [comment] 2024-07-11 02:09
@julealgon

Oh I would _love_ to have a keyed registration a default. (I even tried to do so last year)

But with the current state of DI -- we cannot.

As I mentioned in the Considerations section -- we can't make a Scoped registration a default, _and_ we can't have a Transient registration _at all_ at the moment.

Also, even if we _were_ able to implement a default Transient registration -- I still see a value in having an option to _change the lifetime_, and use Scoped instead. But then you need an API for that 😄

> At least James' original idea intended to remove some of the "custom" nature of the method and rely on the new keyed service support. Now it will be even more custom with extra API additions.

I'm not sure I understand the "contrast" between "ideas" you're trying to make. These are different things/"points in time". The initial ask was to be able to _inject_ the clients via the keyed services infra. So the "custom nature" that is being "removed" in this case is the necessity to inject an IHttpClientFactory instance. The ask is _still_ satisfied, and the "custom nature" is _still_ being "removed", even with the presence of the opt-in API at the registration time.

**Comment by julealgon** [comment] 2024-07-11 15:36
@CarnaViire 
> I still see a value in having an option to _change the lifetime_, and use Scoped instead. But then you need an API for that 😄

Of course there is value in being able to change the lifetime, I think everyone would agree with that. The problem is in the second part: the API to do so.

The container's original API was badly designed from the beginning IMHO, with the hardcoded nature of the lifetime in the same call as the types to register. These APIs will _never_ scale properly:
- `Add{Lifetime}`

Because other APIs were introduced later to register specific things but because the lifetime was built into the original methods (instead of being chained, or just be a parameter, or whatever) you end up with things like:
- `AddHttpClient` // ...where is the lifetime now?
- `AddHostedService` // same problem, even though hosted services will only be resolved once so it doesn't matter much here
- `AddKeyed...` // now you have to replicate the overload 3 times one for each lifetime.... because again, the original API is not scalable/composable

If suddenly we want a `AddLazy...` extension, now it also needs to replicate the method 3 times, one for each lifetime, because the lifetime is coupled to the registration call...

Then if you ever need/want to introduce some sort of fourth lifetime, or a custom lifetime, you are screwed because you now have to go over a bunch of existing methods creating overloads for each of them to support the added lifetime.

Many container libraries have solved this issue by decoupling the types to register from the lifetime, either by having the lifetime be a parameter to the registration, or be a fluent call with a separate method, but yet Microsoft still made this obvious mistake. Even the original Unity container didn't have this issue.

I honestly believe a new more usable/composable API surface should be designed for MEDI while the old methods should be deprecated. It is the only way to move past these silly limitations.

Creating a `.As{Lifetime}` method while using all the old `Add{Lifetime}` ones in the same scope is _extremely_ confusing. It only makes the whole API not orthogonal and more complicated to use. Now suddenly you need to understand that there are multiple ways to specify a lifetime depending on how you make the call.

At that point, why not just have `Add().As{Lifetime}` be the standard API then? (or something to that effect)?

> > At least James' original idea intended to remove some of the "custom" nature of the method and rely on the new keyed service support. Now it will be even more custom with extra API additions.
> 
> I'm not sure I understand the "contrast" between "ideas" you're trying to make. **These are different things/"points in time".** The initial ask was to be able to _inject_ the clients via the keyed services infra. So the "custom nature" that is being "removed" in this case is the necessity to inject an IHttpClientFactory instance. The ask is _still_ satisfied, and the "custom nature" is _still_ being "removed", even with the presence of the opt-in API at the registration time.

Fair enough (based on the bolded). My concern was specifically with the addition of the completely custom (and outlandish based on the current API) `AddAsKeyedScoped`. The fact that that fluent call is now needed is an abomination and shows the obvious design flaw with the original API that I mentioned above.

My take has been that the team should stop and think about this more deeply. Stop introducing special cases for things and making the DI API more convoluted to use, and think about something that works more seamlessly, in a more orthogonal manner.

The API as it is is doomed to fail. It will get worse and worse over time as more of these "special" requirements come in. It has already been tarnished with the original introduction of `AddHttpClient`, named options and named httpclients. All of that should be migrated either to keyed registrations (now that the concept exists in MEDI) and proper "dependent registrations" (which do not exist yet).

If the container supported dependent registrations, even most cases of named/keyed services would completely go away:
```csharp
services.Add<IHttpClientFactory, HttpClientFactory>(options => 
{
    options
        .WithSingletonLifetime()
        
        // General purpose "factory" mechanism in the container. 
        // No need for special casing factories all over the place
        // Allows fetching `HttpClient` from the container and use the factory to create them
        .FactoryFor<HttpClient>()
        .Configure(/* general purpose delegating handlers can be configured here */);
});

services.Add<IMyRepository, GenericRepository>(options => options.WithScopedLifetime());

services.Add<IMyService, MyService>(options => 
{
    options
        .WithTransientLifetime()
        .DependsOn(services =>
        {
            // Allow for specific dependent registrations that only apply to this service.
            // Other services requesting `IMyRepository` will still return `GenericRepository` from above
            services.Add<IMyRepository, SomeSpecialRepositoryImplementation>();

            // General-purpose `Configure` API that can be used for any object, not only `IOptions`
            // this configuration only applies to this particular service since it is inside `DependsOn`.
            // Keep in mind the `HttpClient` will still be constructed by the factory as thats defined outside
            services.Configure<HttpClient, MyApiOptions>((httpClient, apiOptions) => 
            {
                httpClient.BaseAddress = apiOptions.BaseAddress;
                httpClient.Timeout = apiOptions.GlobalTimeout;
            ));
            
            services.Configure<IHttpClientFactory>(/* specific delegating handlers can be set here */);
        },
});

services.Add<ILoggerFactory, LoggerFactory>(options => 
{
    options
        .WithTransientLifetime()
        .FactoryFor<ILogger>()
        .DependOn((services, injectionContext) => 
        {
            // Overload allows access to `injectionContext` object, which provides the target type
            // Factory receives the type and uses it to populate the `Category` for the `ILogger`,
            // eliminating the need for the `ILogger<T>` hack.
            services.Add<Type>(injectionContext.TargetType);
        });
}

public sealed class MyService(
    HttpClient httpClient, 
    IMyRepository myRepository, 
    ILogger logger)
    : IMyService
{
    // specific `HttpClient` injected without named/keyed registrations, still created by factory
    // custom `IMyRepository` injected without keyed registrations for single use case
    // `ILogger` has proper `Category` set based on `MyService` type. No need for `ILogger<T>` to exist
    ...
}
```

- No need for coupling lifetimes with types to register
- No need for special "named" httpclients since the dependency is 1 to 1 (can use general purpose keyed registrations for 1:N cases)
- No need for special "typed" httpclients same as above
- No need for special "configuration" mechanism for `IOptions`: becomes generic and applies to things like `HttpClient` without the need for special `ConfigureClient` etc
- No need for `IOptions` mechanism/abstraction whatsoever (another hack, IMHO)
- No need for special `AddHttpClient` with configurations by just making that a standard method that can work on any instance
- No need for special `ILogger<T>` to workaround container limitation of not knowing the injection target type

**Comment by CarnaViire** [comment] 2024-07-12 19:02
Thanks for the detailed write up @julealgon!

I can definitely see your points. I can relate to the frustration.
I cannot speak from behalf of M.E.DI owners though -- I'm a part of the Networking Libraries team (System.Net.*). I can only suggest you to create a separate issue with the points and suggestions you have (I think you can just take the comment and create an issue from it), so it will get categorized into `area-Extensions-DependencyInjection`. This can both reach the code owners, and give an opportunity for other people to express the interest in the same thing. 

But I must set the expectations -- what you say here

> I honestly believe a new more usable/composable API surface should be designed for MEDI while the old methods should be deprecated. It is the only way to move past these silly limitations.

is not an option. We can't break the users like this.

---

I've added a couple of alternative designs that take in a `ServiceLifetime` though.

And it _is_ a different API shape already (`IHttpClientBuilder`, not `IServiceCollection`). So even if there were some nice `IServiceCollection` APIs, they won't be applicable to `IHttpClientBuilder` as is anyway. But the users of `IHttpClientBuilder` APIs should still be able to use the feature (meaning Keyed DI support), so that's what we're trying to do here.

**Comment by CarnaViire** [comment] 2024-07-12 19:08
Updated the top post:

- added opt-out API (optional)
    - `RemoveAsKeyed()`
- added alternative designs section
    - `AsKeyed(ServiceLifetime)` + `RemoveAsKeyed()`
    - `SetKeyedLifetime(ServiceLifetime)` + `DisableKeyedLifetime()`

cc @halter73 @JamesNK @MihaZupan @ManickaP

**Comment by CarnaViire** [comment] 2024-07-13 18:37
Just wanted to record some thoughts, because we've discussed this somewhere; regarding the _automatic_ opt-in to the _context Scope propagation_ (https://github.com/dotnet/runtime/issues/47091), in case the client is registered with the Keyed DI:

**_On one hand..._**
### ✅ Align with expectations from resolving

Scope propagation will align with expectations from resolving a client, if it has any scoped dependencies.

If I resolve a service from a _specific (scoped) service provider_, I definitely would expect the service's scoped dependencies to be satisfied from _this exact_ service provider.

The existing scope mismatch problem is big enough already. While we technically could try arguing that "bla bla when you get a client from a singleton HttpClientFactory, the factory doesn't have any access to a scope, and _that's why_ a client is created in a different one", this is moot when the factory is hidden "under the hood" of the keyed DI infra. The scope mismatch would become even more prominent and even more confusing.

**_On the other hand..._**
### ⚠️ Potentially unnecessary allocations, ⚠️ PrimaryHandler premature disposal danger

The first point is, if I _don't_ have any scoped dependencies, then I don't care, and I don't really want to recreate a handler chain in each and every little scope (esp., if I imagine turning the rotation _off_ by setting the handler lifetime to Infinity)

The second point is, we cannot cache a primary handler, in case it was registered in DI in any way (e.g. if using [`ConfigurePrimaryHttpMessageHandler<THandler>(IHttpClientBuilder)`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.httpclientbuilderextensions.configureprimaryhttpmessagehandler?view=net-8.0#microsoft-extensions-dependencyinjection-httpclientbuilderextensions-configureprimaryhttpmessagehandler-1(microsoft-extensions-dependencyinjection-ihttpclientbuilder)) overload) -- if resolving it within an existing scope, it will get disposed by DI after that scope is finished (as opposed to the detached scope HttpClientFactory creates and controls now)

**Comment by terrajobst** [comment] 2024-07-16 17:44
* We would like to align the names and take in the lifetime
* The default behavior won't change for .NET 9, the expectation is that .NET 10 will change the default add it keyed lifetime by default.

```C#
namespace Microsoft.Extensions.DependencyInjection;

public static partial class HttpClientBuilderExtensions
{
    public static IHttpClientBuilder AddAsKeyed(this IHttpClientBuilder builder, ServiceLifetime lifetime = ServiceLifetime.Scoped);
    public static IHttpClientBuilder RemoveAsKeyed(this IHttpClientBuilder builder);
}
```

**Closed** 2024-07-18 22:59 UTC
Labels: enhancement, api-approved, blocking, area-Extensions-HttpClientFactory, in-pr
