### ISSUE TITLE
[API Proposal]: Fix to ActivityListener.ShouldListenTo edge case

### ISSUE THREAD

**Issue by RassK** [dotnet/runtime#70727] opened 2022-06-14 13:39 UTC
### Background and motivation

I'm not sure if it's a bug or just missing piece in public api. The public api of `ActivitySource.ShouldListenTo` allows to change the filter method on the fly. Actually this is half true, so there is a edge case that is unhandled.

The edge case occurs when `ActivitySource.AddActivityListener()` is called before `ActivitySource.ShouldListenTo` is changed.

Small repro here >
```csharp
using System.Diagnostics;
using System.Reflection;
using System.Text.RegularExpressions;

public static class Program
{
    public static void Main(params string[] args)
    {
        ActivityListener listener = new ActivityListener
        {
            Sample = (ref ActivityCreationOptions<ActivityContext> options) => ActivitySamplingResult.AllDataAndRecorded,
            ShouldListenTo = (source) => Regex.IsMatch(source.Name, "Source1"),
            ActivityStarted = (activity) => Console.WriteLine("Activity started: {0}", activity.DisplayName)
        };

        ActivitySource.AddActivityListener(listener);

        ActivitySource source1 = new ActivitySource("Source1");
        ActivitySource source2 = new ActivitySource("Source2");

        listener.ShouldListenTo = (source) => Regex.IsMatch(source.Name, "Source1|Source2");

        // Uncomment to fix Source2
        // FixListener(listener);

        using var activity1 = source1.StartActivity("From.Source1");
        using var activity2 = source2.StartActivity("From.Source2");

        Console.WriteLine("Press Enter to exit.");
        Console.ReadLine();
    }

    public static void FixListener(ActivityListener listener)
    {
        typeof(ActivitySource)
            .GetMethod("DetachListener", BindingFlags.NonPublic | BindingFlags.Static)?
            .Invoke(null, new[] { listener });

        ActivitySource.AddActivityListener(listener);
    }
}

```

### Background
We are looking ways to dynamically subscribe to ActivitySources based on assembly loading. 
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/388
https://github.com/open-telemetry/opentelemetry-dotnet/issues/3253

### API Proposal

Based on API usages, there are 3 different options:

1. The cleanest fix would be to fix the reactivity of `ActivitySource.ShouldListenTo`. When property is changed all ActivitySources must be revaluated. Resulting to **no public api changes**.
2. Make `AcitivitySource.DetachListener` public https://github.com/dotnet/runtime/blob/a361f7f84ac627b34a611be89b52d9dc75293bbf/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/ActivitySource.cs#L337
3. Introduce new api `AcitivitySource.UpdateListener`

(Step 2 and 3 would still need documentation fix for `ActivitySource.ShouldListenTo`)

### API Usage

I have 3 different ways currently on my mind:

1. Revaluate ActivitySources

```csharp
ActivityListener listener = new ActivityListener
{
    ShouldListenTo = (source) => Regex.IsMatch(source.Name, "Source1"),
};

ActivitySource.AddActivityListener(listener);

// Triggers revaluation of all existing sources
listener.ShouldListenTo = (source) => Regex.IsMatch(source.Name, "Source1|Source2");
```

2. Change DetachListener to public

```csharp
ActivityListener listener = new ActivityListener
{
    ShouldListenTo = (source) => Regex.IsMatch(source.Name, "Source1"),
};

ActivitySource.AddActivityListener(listener);

listener.ShouldListenTo = (source) => Regex.IsMatch(source.Name, "Source1|Source2");

ActivitySource.DetachListener(listener);
ActivitySource.AddActivityListener(listener);
```

3. Introduce UpdateListener

```csharp
ActivityListener listener = new ActivityListener
{
    ShouldListenTo = (source) => Regex.IsMatch(source.Name, "Source1"),
};

ActivitySource.AddActivityListener(listener);

listener.ShouldListenTo = (source) => Regex.IsMatch(source.Name, "Source1|Source2");

ActivitySource.UpdateListener(listener);
```

**Comment by tarekgh** [comment] 2022-06-14 16:21
This is not a bug. It is intentional you need to call `AddActivityListener` after setting all the listener properties. The reason is when calling `AddActivityListener` we enumerate all ActivitySource objects and run it through the listeners for filtering. If we change that to run this filtering every time set `ShouldListenTo`, there will be a performance concern with that. You always have the choice to create a new listener at any time to force the behavior you want. 

CC @noahfalk

**Comment by pellared** [comment] 2022-06-15 18:37
> You can dispose of the old listener at any time and create a new listener at any time to force the behavior you want. 

@tarekgh 

The problem is that caller would need to deal with possible race conditions.

1. If the new listener is created after the previous listener is disposed, then one can lose activities.
2. If the new listener is created after the previous listener is disposed, then one can receive duplicate activities.

**Comment by tarekgh** [comment] 2022-06-15 19:13
Reopening till we discuss it.

**Comment by RassK** [comment] 2022-06-15 21:26
That being discovered today means "Make `AcitivitySource.DetachListener` public" causes  the same issue theoretically as there is a blackout or overlapping when detaching and reattaching logic runs.

**Comment by tarekgh** [comment] 2022-06-15 21:27
To learn more about the scenario. It is mentioned above `We are looking ways to dynamically subscribe to ActivitySources based on assembly loading.`. Can this be handled inside the `ShouldListenTo` delegate? When a new assembly is loaded and a new ActivitySource is created, `ShouldListenTo` should get called at that time and you can just enable listening to the new ActivitySource.  The logic inside `ShouldListenTo` should be able to handle such case I guess. in other word, if you know when you need to reset `ShouldListenTo`, the delegate implementation can handle this case without resetting `ShouldListenTo` . Do you have the case want to cancel listening to an ActivitySource object?

**Comment by RassK** [comment] 2022-06-15 23:16
> To learn more about the scenario. It is mentioned above `We are looking ways to dynamically subscribe to ActivitySources based on assembly loading.`. Can this be handled inside the `ShouldListenTo` delegate? When a new assembly is loaded and a new ActivitySource is created, `ShouldListenTo` should get called at that time and you can just enable listening to the new ActivitySource. The logic inside `ShouldListenTo` should be able to handle such case I guess. in other word, if you know when you need to reset `ShouldListenTo`, the delegate implementation can handle this case without resetting `ShouldListenTo` . Do you have the case want to cancel listening to an ActivitySource object?

I'm afraid we are somehow losing the race between modifying `ShouldListenTo` and creating a new ActivitySource. At first I wasn't focusing to the ActivitySource issue at all, that was the last thing I had to figure out. Which means the race condition was  always lost. 

Currently we don't have cases that require dll unloading / cancelling a source. It's a possibility but we don't have any idea, how much that feature is used + what is the actual business logic.

**Comment by tarekgh** [comment] 2022-06-16 00:59
> I'm afraid we are somehow losing the race between modifying ShouldListenTo and creating a new ActivitySource. At first I wasn't focusing to the ActivitySource issue at all, that was the last thing I had to figure out. Which means the race condition was always lost.

I believe you can just write the `ShouldListenTo` delegate code in a way that doesn't need to be updated later at all, instead the logic inside should handle the cases you want to support automatically, If I correctly understand your scenario, there is a new assembly/component get loaded. and then this component later will create a new ActivitySource object which you want to decide listening to.  At that time, the listener `ShouldListenTo` will get invoked. At that time, you can have the logic to decide if want to listen to this object or not (either using the ActivitySource name or the assembly created this object, or any other logic fits your scenario). There are not any race conditions here at all and everything should work as expected.

> Currently we don't have cases that require dll unloading / cancelling a source. It's a possibility but we don't have any idea, how much that feature is used + what is the actual business logic.

Thanks for the info. Even in the future if any assembly gets unloaded, the ActivitySource created by this assembly is going to go away and get collected and naturally the listener will work without any problem or need to unregister anything.

**Comment by RassK** [comment] 2022-06-16 10:09
@tarekgh that sounds as very good idea. It should fix our issue, based on the fact that on the startup time we know either we want all supported sources or user selected sources and it doesn't change afterwards.

**Comment by tarekgh** [comment] 2022-06-16 17:33
Thanks @RassK. Based on that I am closing the issue. Feel free to send any more questions and requests and I'll be happy to help with them.

**Closed by tarekgh** 2022-06-16 17:33 UTC
Labels: api-suggestion, area-System.Diagnostics.Activity
