### ISSUE TITLE
Uri.CheckHostName does not check/limit total dns name length

### ISSUE THREAD

**Issue by nitinag** [dotnet/runtime#30474] opened 2019-08-03 16:39 UTC
**Uri.CheckHostName** (and "**new Uri(string uriString)**", other possible areas) does not check/limit the total length of the dns name to **253** as required by the RFC. It does limit each label to 63 characters as expected/required.

The total dns name size limit is 255 octets per the RFC, but since in dns, the first label length byte does not represent a dot and the ending 0 length null byte is required, which also does not represent a dot, that makes for a max **total ASCII string length of 253** (with each part between dots limited to 63 characters).

Test:
Uri.CheckHostName("abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijk.abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijk.abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijk.abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghij");
with a 254 character dns name (greater than the allowed 253) should return UriHostNameType.Unknown due to max total length.

"To simplify implementations, the total length of a domain name (i.e.,
label octets and label length octets) is restricted to 255 octets or
less."
https://tools.ietf.org/html/rfc1035#section-3.1

"names           255 octets or less"
https://tools.ietf.org/html/rfc1035#section-2.3.4

"Domain names in messages are expressed in terms of a sequence of labels.
Each label is represented as a one octet length field followed by that
number of octets."
https://tools.ietf.org/html/rfc1035#section-3.1

"Since every domain name ends with the null label of
the root, a domain name is terminated by a length byte of zero."
https://tools.ietf.org/html/rfc1035#section-3.1

**Comment by MihaZupan** [comment] 2020-03-19 05:23
Duplicate of #33746

**Closed by MihaZupan** 2020-03-19 05:23 UTC
Labels: area-System.Net, bug
