### ISSUE TITLE
[browser][debugger] chrome failing to start

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#86166] opened 2023-05-12 18:41 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=272043
Build error leg or test failing: DebuggerTests.BreakpointTests.DebuggerTests.BreakpointTests.StepperBoundary
Pull request: https://github.com/dotnet/runtime/pull/86158

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Zygote could not fork: process_type gpu-process numfds",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[305194](https://dev.azure.com/dnceng-public/public/_build/results?buildId=305194)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrame2Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=305194&view=ms.vss-test-web.build-test-results-tab&runId=6200832&resultId=100298)|dotnet/runtime#86255|
|[304822](https://dev.azure.com/dnceng-public/public/_build/results?buildId=304822)|dotnet/runtime|[chrome-DebuggerTests.EvaluateOnCallFrameTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=304822&view=ms.vss-test-web.build-test-results-tab&runId=6190154&resultId=100298)|dotnet/runtime#87405|
|[299126](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299126)|dotnet/runtime|[DebuggerTests.SetVariableValueTests.DebuggerTests.SetVariableValueTests.SetVariableValuesAtBreakpointSiteFail](https://dev.azure.com/dnceng-public/public/_build/results?buildId=299126&view=ms.vss-test-web.build-test-results-tab&runId=6056548&resultId=100084)|dotnet/runtime#86813|
|[290256](https://dev.azure.com/dnceng-public/public/_build/results?buildId=290256)|dotnet/runtime|[DebuggerTests.EvaluateOnCallFrameTests.DebuggerTests.EvaluateOnCallFrameTests.EvaluateTypeInstanceMembers](https://dev.azure.com/dnceng-public/public/_build/results?buildId=290256&view=ms.vss-test-web.build-test-results-tab&runId=5809834&resultId=100245)|dotnet/runtime#86908|
|[280871](https://dev.azure.com/dnceng-public/public/_build/results?buildId=280871)|dotnet/runtime|[chrome-DebuggerTests.GetPropertiesTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=280871&view=ms.vss-test-web.build-test-results-tab&runId=5570238&resultId=100298)|dotnet/runtime#86384|
|[280524](https://dev.azure.com/dnceng-public/public/_build/results?buildId=280524)|dotnet/runtime|[chrome-DebuggerTests.CallFunctionOnTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=280524&view=ms.vss-test-web.build-test-results-tab&runId=5562588&resultId=100298)|dotnet/runtime#86415|
|[278651](https://dev.azure.com/dnceng-public/public/_build/results?buildId=278651)|dotnet/runtime|[chrome-DebuggerTests.CallFunctionOnTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=278651&view=ms.vss-test-web.build-test-results-tab&runId=5527832&resultId=100298)|dotnet/runtime#85920|
|[274652](https://dev.azure.com/dnceng-public/public/_build/results?buildId=274652)|dotnet/runtime|[chrome-DebuggerTests.SteppingTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=274652&view=ms.vss-test-web.build-test-results-tab&runId=5434032&resultId=100298)|dotnet/runtime#85920|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|3|8|

**Comment by radical** [comment] 2023-06-14 22:02
Dupe of https://github.com/dotnet/runtime/issues/87053 .

**Closed by radical** 2023-06-14 22:02 UTC
Labels: arch-wasm, area-VM-meta-mono, Known Build Error
