### ISSUE TITLE
CS 0184 when attempting to check `typeInfo is TypeBuilder` and similar errors on casts from TypeInfo to TypeBuilder.

### ISSUE THREAD

**Issue by dammejed** [dotnet/runtime#42922] opened 2020-09-30 21:37 UTC
### Description
Hello,

I'm attempting to migrate some code that was generating dynamic types from the .Net framework to .net 5.0 RC. I encountered a situation which is extremely puzzling to me. The code snippet below demonstrates the issue I'm encountering:

```csharp
var builder = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName("Foo"), AssemblyBuilderAccess.RunAndCollect);
var module = builder.DefineDynamicModule("Biz");

var typeBuilder = module.DefineType("Bar"); //  According to the debugger
var typeinfo = typeBuilder.GetTypeInfo();   //  These two are the exact same object.

var isTypeBuilder = typeinfo is TypeBuilder; // CS 0184: The given expression is never of the provided ('TypeBuilder') type. (compiles to false)
var isTypeBuilder2 = typeinfo.GetType()
        .IsAssignableTo(typeof(TypeBuilder));  // no warning, returns true.
```

The problem is when I attempt to use `typeInfo is TypeBuilder`. In the .net framework, this works. In .net 5.0, I'm presented with the CS 0184 warning. I haven't attempted this in previous .net core releases, but I could do that if it would help triage.

What's puzzling to me is that, according to the debugger (and the [Source for TypeBuilder](https://github.com/dotnet/runtime/blob/v5.0.0-rc.1.20451.14/src/coreclr/src/System.Private.CoreLib/src/System/Reflection/Emit/TypeBuilder.cs#L13), if I understand well), `TypeBuilder` does indeed inherit from `TypeInfo`. Yet when F12 decompiling `TypeBuilder`, the [source](https://github.com/dotnet/runtime/blob/v5.0.0-rc.1.20451.14/src/libraries/System.Reflection.Emit/ref/System.Reflection.Emit.cs#L425) claims that `TypeBuilder` simply inherits directly from `Type`.

Can someone help me understand the discrepancy? Is that a bug or intentional?

For context, the project I was using was relying on a `System.Reflection.Context.CustomReflectionContext` to override `MapType(TypeInfo ti)` to return a custom proxy wrapper when it's used on `TypeBuilder` instances. The fact that I can't use a compile-time `is` check makes the code a bit more cumbersome.

### Configuration

Which version of .NET is the code running on?
**.Net 5.0 RC**
What OS and version, and what distro if applicable?
**Windows 10 Enterprise 1909**
What is the architecture (x64, x86, ARM, ARM64)?
**x64**

I don't think it's specific to this configuration.
### Regression?

**Yes**, this worked well in the 'full' .net framework.

### Other information

**Workaround**: Use 
```csharp
(object)typeInfo is TypeBuilder
```
to check for the type, or 
```csharp
(TypeBuilder)(object)typeInfo
```
to cast.

**Comment by stephentoub** [comment] 2020-09-30 22:28
This is happening because, although `TypeBuilder` derives from `TypeInfo` in the implementation, in the reference assembly it actually derives from `TypeInfo`'s base type `Type`.
https://github.com/dotnet/runtime/blob/118eee973af81119fd00fe75bc9c14ce3192ff1e/src/libraries/System.Reflection.Emit/ref/System.Reflection.Emit.cs#L425

This is visible in the docs as well... for .NET Framework 4.8, it's shown as deriving from TypeInfo, whereas in .NET Core it's shown as deriving from Type:
https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.typebuilder?view=netframework-4.8
https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.typebuilder?view=netcore-3.1

@jkotas, @terrajobst, is this an accident of history (with all our shuffling around Type vs TypeInfo) that should be fixed in core, or is it by design?

**Comment by jkotas** [comment] 2020-10-01 05:17
I think this is just an accident of history. I do not see a problem with fixing this in the ref assembly.

**Comment by dammejed** [comment] 2020-10-01 20:24
Thanks for the quick turnaround folks, appreciate you having a look.
@stephentoub FYI, the same seems to be true of `EnumBuilder`, though I haven't used that type in my own projects.

**Comment by stephentoub** [comment] 2020-10-02 13:59
> FYI, the same seems to be true of EnumBuilder

Thanks.  Yup, and also GenericTypeParameterBuilder.

**Closed** 2020-10-09 10:14 UTC
Labels: area-System.Reflection, bug
