### ISSUE TITLE
asmdiff failed for checked and release for smoke_tests.nativeaot.windows.arm64

### ISSUE THREAD

**Issue by JulieLeeMSFT** [dotnet/runtime#104584] opened 2024-07-09 02:02 UTC
Pipeline: [runtime-coreclr superpmi-asmdiffs-checked-release](https://dev.azure.com/dnceng-public/public/_build?definitionId=153&_a=summary): [20240708.2](https://dev.azure.com/dnceng-public/public/_build/results?buildId=733731)
Failed job: [Link](https://dev.azure.com/dnceng-public/public/_build/results?buildId=733726&view=logs&j=83516c17-6666-5250-abde-63983ce72a49&t=2694d93b-a574-5310-1876-2e252085b877)
[Log](https://[helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-8695c9bf0a31465ea2/windows-arm64/1/console.606a30e5.log?helixlogtype=result](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-8695c9bf0a31465ea2/windows-arm64/1/console.606a30e5.log?helixlogtype=result))

Error Message:
```
[23:18:54] Asm diffs summary:

[23:18:54]   Replay failures in 1 MCH files:

[23:18:54]     C:\h\w\AE3409D3\p\artifacts\spmi\mch\e6c7a441-8d3c-4135-abc2-bc4dd7c6a4d7.windows.arm64\smoke_tests.nativeaot.windows.arm64.checked.mch

[23:18:54]   Asm diffs in 1 MCH files:

[23:18:54]     C:\h\w\AE3409D3\p\artifacts\spmi\mch\e6c7a441-8d3c-4135-abc2-bc4dd7c6a4d7.windows.arm64\smoke_tests.nativeaot.windows.arm64.checked.mch
```

**Comment by JulieLeeMSFT** [comment] 2024-07-09 02:05
Seems caused by https://github.com/dotnet/runtime/pull/104282 
@kunalspathak 

The commit before #104282 passed the test: [20240708.2](https://dev.azure.com/dnceng-public/public/_build/results?buildId=733731)

**Comment by jakobbotsch** [comment] 2024-07-09 07:49
Duplicate of #104441 ?

**Closed** 2024-07-26 16:50 UTC
Labels: area-CodeGen-coreclr, blocking-clean-ci-optional, Priority:2
