### ISSUE TITLE
System.Text.Json 5.0.1, net461 has AssemblyVersion 5.0.0.1 ?

### ISSUE THREAD

**Issue by PainElemental** [dotnet/runtime#49642] opened 2021-03-15 12:54 UTC
The nuget package of System.Text.Json 5.0.1 has 3 assembies:
.net core: Assembly Version 5.0.0.0
.net standard: Assembly Version 5.0.0.0
.net 4.6.1: Assembly Version 5.0.0.1

Why does the .NET Framework version have a different assembly version? Isn't that in conflict with semantic versioning?

Because of this different assembly version I have to use binding redirect for my application...

**Comment by eiriktsarpalis** [comment] 2021-03-15 16:19
@ViktorHofer or @safern might know why this is.

**Comment by ViktorHofer** [comment] 2021-03-15 16:26
That is actually by design and explained in detail here: https://github.com/dotnet/runtime/blob/release/5.0/docs/project/library-servicing.md#determine-assemblyversion.

cc @Anipik @ericstj

**Comment by eiriktsarpalis** [comment] 2021-03-15 16:30
Thanks for the clarification @ViktorHofer. In that case I'm going to close the issue.

**Closed by eiriktsarpalis** 2021-03-15 16:30 UTC
Labels: area-System.Text.Json, untriaged
