### ISSUE TITLE
C# record with expression crashes at runtime under AOT

### ISSUE THREAD

**Issue by jharjung** [dotnet/runtime#106468] opened 2024-08-15 14:54 UTC
### Description

Given the following record hierarchy:

```csharp
public abstract record A(bool Prop);
public abstract record B(bool Prop) : A(Prop);
public record C(bool Prop) : B(Prop);
```

This code crashes at runtime when AOT compiled:

```csharp
A x = new C(false);
var _ = x with { Prop = true };
```

Both of these variations work under AOT:
- Make `B` non-abstract: `public record B(bool Prop) : A(Prop);`
- Cast the `C` to `B` instead of `A`: `B x = new C(false);`

These variations, and combinations of them, have no impact:
- Make `A` non-abstract: `public record A(bool Prop);`
- Use a declared property rather than a positional property: `public bool Prop { get; init; }`
- Use a declared property with `set` instead of `init`: `public bool Prop { get; set; }`
- Implement explicit copy constructors:
   - `public A(A Other) { this.Prop = Other.Prop; }`
   - `public B(B Other) : base(Other) { }`
   - `public C(C Other) : base(Other) { }`

### Reproduction Steps

ConsoleApp.csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

</Project>
```

Program.cs:

```csharp
using System;

namespace ConsoleApp
{
    public abstract record A(bool Prop);
    public abstract record B(bool Prop) : A(Prop);
    public record C(bool Prop) : B(Prop);

    public static class Program
    {
        public static void Main(string[] Args)
        {
            ThisWillRun();
            ThisWillCrash();
        }

        public static void ThisWillRun()
        {
            Console.WriteLine("ThisWillRun: Enter");
            B b = new C(false); // cast to *B*
            Console.WriteLine("ThisWillRun: Before With");
            var _ = b with { Prop = true };
            Console.WriteLine("ThisWillRun: After With");
            Console.WriteLine("ThisWillRun: Exit");
        }

        public static void ThisWillCrash()
        {
            Console.WriteLine("ThisWillCrash: Enter");
            A a = new C(false); // cast to *A*
            Console.WriteLine("ThisWillCrash: Before With");
            var _ = a with { Prop = true }; // crash happens here
            Console.WriteLine("ThisWillCrash: After With");
            Console.WriteLine("ThisWillCrash: Exit");
        }
    }
}
```

### Expected behavior

No crash

### Actual behavior

Crashes under all of the following scenarios:

1. Build for `osx-arm64` using .net 8 and .net 9 preview 7
2. Build for `osx-x64` using .net 8 and .net 9 preview 7
3. In a Windows ARM64 virtual machine, build for `win-arm64` using .net 7, .net 8, and .net 9 preview 7
4. In a Windows ARM64 virtual machine, build for `win-x64` using .net 7, .net 8, and .net 9 preview 7

Unfortunately I don't have an x64 machine to test on.

Output on OSX:

```
ThisWillRun: Enter
ThisWillRun: Before With
ThisWillRun: After With
ThisWillRun: Exit
ThisWillCrash: Enter
ThisWillCrash: Before With
zsh: segmentation fault  ./bin/Release/net8.0/osx-arm64/publish/ConsoleApp
```

Output on Windows:
```
ThisWillRun: Enter
ThisWillRun: Before With
ThisWillRun: After With
ThisWillRun: Exit
ThisWillSegFault: Enter
ThisWillSegFault: Before With
```

(On Windows, there's no error printed for the crash, the program just stops)

### Regression?

No

### Known Workarounds

None

### Configuration

.net 7.0.410, .net 8.0.302, and .net 9.0.100-preview.7.24407.12

M3 Max Macbook Pro, Sonoma 14.1.2
Parallels 19.2.1
Windows 11 Pro for ARM64 23H2 22631.3880
Visual Studio 2022 17.10 LTSC for ARM64

**Comment by MichalStrehovsky** [comment] 2024-08-15 15:52
This is same as #96175.

`var _ = a with { Prop = true }; // crash happens here` -> here we need to call the compiler-generated `<Clone>$` method on C virtually. `<Clone>$` is a covariant return override.

The difference between `ThisWillRun` and `ThisWillCrash` is that in one the covariant return method is being called in the doubly-overriden situation and that's the bug.

Cc @agocke - I see we just moved #96175 out of .NET 9. I assume we cannot get David on this. There's not much we can do than close as duplicate of #96175.

**Closed by MichalStrehovsky** 2024-08-15 15:52 UTC
Labels: untriaged, area-NativeAOT-coreclr, needs-area-label

**Comment by jharjung** [comment] 2024-08-15 16:50
@MichalStrehovsky Sorry for the duplicate and thank you for the clarification.

Any idea why this works when building for the `browser-wasm` rid? Does "AOT" mean different things for these targets?

**Comment by agocke** [comment] 2024-08-15 17:24
I hadn't seen this -- this definitely raises the priority on https://github.com/dotnet/runtime/issues/96175.

I will try to resource this.

**Comment by MichalStrehovsky** [comment] 2024-08-16 10:10
> @MichalStrehovsky Sorry for the duplicate and thank you for the clarification.

No worries, the failure mode is not very obvious.

> Any idea why this works when building for the `browser-wasm` rid? Does "AOT" mean different things for these targets?

WASM uses Mono AOT, not native AOT. It's a different runtime & type system.
