### ISSUE TITLE
Null-Conditional operator not functioning correctlly in Razor/Blazor and debugging in Edge is dying sometimes.

### ISSUE THREAD

**Issue by AceSyntax** [dotnet/runtime#77542] opened 2022-10-27 10:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I've added a little code to the standard blazor template app in the counter page to demonstrate this.
This code should work without an execption being caught.  
```csharp
private void IncrementCount()
    {
        currentCount++;

        TestClass t = null;

        try
        {
            Console.WriteLine(t?.Name);
            Console.WriteLine(t?.ToString());
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
            throw;
        }
    }

    public class TestClass
    {
        public string Name { get; set; }
    }
```
### Expected Behavior

The above code should work, with out any exception being thrown.

### Steps To Reproduce

Add this code to a standard blazor app's counter page.
```csharp
private void IncrementCount()
    {
        currentCount++;

        TestClass t = null;

        try
        {
            Console.WriteLine(t?.Name);
            Console.WriteLine(t?.ToString());
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
            throw;
        }
    }

    public class TestClass
    {
        public string Name { get; set; }
    }
```
### Exceptions (if any)

No exception is being thrown.   The debugger just dies and although the page renders correctly and both Console.WriteLines show up in the browsers console I'm unable to see that happening when debugging.

However in another more complex app, I am getting an exception when using the null-conditional operator on a null object and I'm seeing a null reference execption and I'm able to catch it.

Also Edge is showing an unhandled exception to the user.

This behaviour is clearly wrong and is causing seriously paninful problems.

### .NET Version

core 6 and version 5 of  core 7

### Anything else?

I love Blazor, it's amazing!

Thanks to the Blazor team for all the work they have put into making it so awesome!

**Comment by radical** [comment] 2022-10-27 18:56
cc @ilonatommy

**Comment by AceSyntax** [comment] 2022-10-28 13:01
One change that might be significant; I was using a record, not a class.   I've tried changing the demo code above but I still can't reproduce the exception being thrown unfortunatly.

**Comment by ilonatommy** [comment] 2022-11-01 10:21
@AceSyntax, thank you for helping us improving Blazor experience. I cannot reproduce neither with net 6.0, net 7 preview 5 or any newer version. I tried both `class` and `record` in two IDE's: Visual Studio and Chrome/Edge browser. What I did was to set breakpoints on all 3 `Console.WriteLines` and check if we can resume from them. We are never getting into `catch` and debugger have never died. 
- Are there any additional actions you were performing that could help me reproduce? Any particular values checked in watch window or any step-in/over actions?
- Do I understand right it happened **every time** you were debugging this small repro using Edge browser? If so, did it happen after some specific action that you've done? E.g. always after resume or always after setting a new breakpoint?
- Could you, please screenshot the Edge exception you see in the small repro? Is it thrown on line `t.?Name` or `t.?ToString()`?

**Closed** 2023-02-17 06:01 UTC
Labels: arch-wasm, area-Debugger-mono, no-recent-activity, needs-author-action
