### ISSUE TITLE
DeflateStream.ReadAsync disregards Memory<byte> buffer size

### ISSUE THREAD

**Issue by MarcelKonnegen** [dotnet/runtime#67092] opened 2022-03-24 10:53 UTC
### Description

I have a zip archive with a ZipArchiveEntry to which I open a readable stream for decompression. The type of stream that is returned is a DeflateStream. The file in the zip-archive is 300GB of size, so the buffer size is smaller than the total file size.

I create a byte[] buffer of size 400_000_00:
`var buffer = new byte[400000000];`

To asynchronously read from the stream, I create a `var memoryBuffer = Memory<byte>(buffer)`.

When I now read from the stream using the synchronous `var bytesRead = DeflateStream.Read(buffer, 0, buffer.Length);` the buffer is filled and bytesRead is equal to `buffer.Length`.

When I read from the stream using the asynchronous `var bytesRead = DeflateStream.ReadAsync(memoryBuffer);` the buffer is only partially filled and the bytesRead will equal around 200_000.

### Reproduction Steps

1. Zip a large file
2. Retrieve the `ZipArchiveEntry` using System.IO.Compression.ZipFile
3. Invoke `ZipArchiveEntry.Open()` to create a DeflateStream pointing to the archive entry.
4. Create a large sized Memory<byte>
5. Use the `DeflateStream.ReadAsync(Memory<byte>)` method to read from the stream.

### Expected behavior

`Read(byte[], 0, length)` and `ReadAsync(Memory<byte>)` should return the same number of bytesRead and fill the passed buffer.

### Actual behavior

The synchronous method behaves as expected, the asynchronous method only fills a small portion of the buffer.

### Known Workarounds

Use the synchronous variant when the asynchronous variant would be more appropriate.

**Comment by stephentoub** [comment] 2022-03-24 11:14
> Read(byte[], 0, length) and ReadAsync(Memory<byte>) should return the same number of bytesRead and fill the passed buffer.

This is not the defined behavior of Stream.Read. From the docs, e.g. "[Read](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.read?view=net-6.0) returns 0 only when there is no more data in the stream and no more is expected (such as a closed socket or end of file). An implementation is free to return fewer bytes than requested even if the end of the stream has not been reached."

**Comment by stephentoub** [comment] 2022-03-24 13:22
Thanks for the question.  I'm going to close this, as the behavior is by design.  Any Stream.Read{Async} usage needs to expect that the call will not return as many bytes as are requested, and if it requires as many as were requested, the caller needs to loop.  https://github.com/dotnet/runtime/issues/16598 tracks adding a method that will do that looping for you; I'm hopeful it'll be added in .NET 7.

**Closed by stephentoub** 2022-03-24 13:22 UTC
Labels: area-System.IO.Compression, untriaged

**Comment by MarcelKonnegen** [comment] 2022-03-25 08:02
Hi Stephen,
thanks for getting back so quickly. I am aware of the documentation and everything you have said is correct. Yet, my issue is that for the same stream the two method `Read` and `ReadAsync` behave differently which they shouldn't. The difference is essential and basically renders the async version unusable for our purposes as it will only yield a fraction of the bytes requested in comparison to the non-async version. 

I understand that this behavior is covered by the documentation, still I believe this is a bug as the user expectation is, given the identical circumstances, that both variants should behave as expected (which the non-async version does).

**Comment by stephentoub** [comment] 2022-03-25 13:13
> Yet, my issue is that for the same stream the two method Read and ReadAsync behave differently which they shouldn't. The difference is essential and basically renders the async version unusable for our purposes as it will only yield a fraction of the bytes requested in comparison to the non-async version.

There is no guarantee that Stream.Read and Stream.ReadAsync will return the same number of bytes as each other on each call, as the underlying implementations could be wildly different, all the way down through the OS.

That said, if consistency is your goal, I expect you'll then be pleased if you try your repro on .NET 6 (presumably you were using .NET 5 or earlier), as DeflateStream.Read/ReadAsync are much more likely there to return the same number of bytes as each other. The behavior will be closer to that of ReadAsync than to that of Read you see today.

**Comment by MarcelKonnegen** [comment] 2022-03-25 15:25
Hi Stephen,
great feedback, thanks! Indeed, I am working on .NET5 right now. There is no chance that the company I am working for will jump to .NET6 in the foreseeable future. However, I will give it a test at home using .NET6. 

Just for the context: I am chunking a very large stream of a CSV file (> 300GB) into chunks of approximately 200,000 rows which are then imported into the database using SqlBulkCopy. Therefore, I am passing in a very large buffer (~400MB) into the `Read{Async}` method. Using the synchronous Read method, the method will fill the buffer completely for each step in the while loop (until Read() returns 0). I have appr. 1400 SQL bulk inserts therefore. Using the same buffer (wrapped in `Memory<byte>`) with the `ReadAsync()` method it will only fill appr. 200KB of the buffer (the number of bytes read returned by `ReadAsync ()` is correct with respect to the number of bytes in the buffer). However, this now results in 1440 * 2000 (200KB * 2000 = 400MB), almost 3M SQL bulk insert operations which is not an option in our specific context.

Again, thanks for the great and timely feedback!

**Comment by stephentoub** [comment] 2022-03-25 16:03
> Using the synchronous Read method, the method will fill the buffer completely for each step in the while loop (until Read() returns 0). I have appr. 1400 SQL bulk inserts therefore. Using the same buffer (wrapped in Memory<byte>) with the ReadAsync() method it will only fill appr. 200KB of the buffer (the number of bytes read returned by ReadAsync () is correct with respect to the number of bytes in the buffer). However, this now results in 1440 * 2000 (200KB * 2000 = 400MB), almost 3M SQL bulk insert operations which is not an option in our specific context.

It doesn't need to be an option. Just add a loop to your code. If it's important for your performance that you always operate on a filled buffer, you should be doing so for both the sync and async cases, as neither guarantees it'll be filled.

```C#
static int ReadAll(this Stream s, byte[] buffer)
{
    int totalRead = 0;
    while (totalRead < buffer.Length)
    {
        int bytesRead = stream.Read(buffer.AsSpan(totalRead));
        if (bytesRead == 0) break;
        totalRead += bytesRead;
    }
    return totalRead;
}

static async ValueTask<int> ReadAllAsync(this Stream s, byte[] buffer)
{
    int totalRead = 0;
    while (totalRead < buffer.Length)
    {
        int bytesRead = await stream.ReadAsync(buffer.AsMemory(totalRead));
        if (bytesRead == 0) break;
        totalRead += bytesRead;
    }
    return totalRead;
}
```
