### ISSUE TITLE
System.PlatformNotSupportedException raised on System.IO.Ports.SerialPort.GetPortNames()

### ISSUE THREAD

**Issue by jsmcneal** [dotnet/runtime#31045] opened 2019-10-02 16:20 UTC
I am trying to enumerate serial ports in an UWP application using  SerialPort.GetPortNames() because Windows.Devices.SerialCommunication SerialDevice does not enumerate correctly for my target device (returns null).  

UWP Target: Windows 10 1809
Min Version: Windows 10 1809

Windows Enterprise 10.01.18362
MS VS Version 15.9.15
MS .NET Framework Version 4.8.0.03752
Microsoft.Windows.Compatibility Version 3.0.0

**Comment by YZahringer** [comment] 2020-02-12 16:18
Related: https://github.com/dotnet/runtime/issues/22085 & https://github.com/dotnet/corefx/pull/31539

@vbaderks [comment](https://github.com/dotnet/corefx/pull/31539#issuecomment-484293908), this is not yet available in UWP. I suppose it will come in a future Windows 10 Build, with `.NET Standard 2.1` support.

**Comment by Jozkee** [comment] 2022-04-01 22:09
Duplicate of https://github.com/dotnet/runtime/issues/67461

**Closed by Jozkee** 2022-04-01 22:09 UTC
Labels: area-System.IO
