### ISSUE TITLE
One about foreach and type access

### ISSUE THREAD

**Issue by SimpleZDM** [dotnet/runtime#80647] opened 2023-01-14 03:31 UTC
### Description

![This is an image](https://img-blog.csdnimg.cn/a7cab0ea857c407daf667aba7a43049c.png)
![This is an image](https://img-blog.csdnimg.cn/783052eddb664545bd518e062dc1a49e.png)
I am a junior programmer.
I want you to debug the above problems, may not be as simple as you think.
This makes me very confused and I would like to have a.NET expert help explain.

### Reproduction Steps

100%

### Expected behavior

Cannot apply indexing with [] to an expression of type 'object'

### Actual behavior

An exception will be thrown if the type is not public (Cannot apply indexing with [] to an expression of type 'object')
It's easy to understand that the runtime environment finds out that it's a protected type so it throws an exception but you can access it directly with foreach whether test is a protected type or not private

### Regression?

An exception will be thrown if the type is not public (Cannot apply indexing with [] to an expression of type 'object')
It's easy to understand that the runtime environment finds out that it's a protected type so it throws an exception but you can access it directly with foreach whether test is a protected type or not private

### Known Workarounds

An exception will be thrown if the type is not public (Cannot apply indexing with [] to an expression of type 'object')
It's easy to understand that the runtime environment finds out that it's a protected type so it throws an exception but you can access it directly with foreach whether test is a protected type or not private

### Configuration

.net 6

**Comment by huoyaoyuan** [comment] 2023-01-15 10:04
I cannot reproduce with following code on .NET 7:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;

namespace CSPlayground
{
    class Program
    {
        private class Test
        {

        }

        static void Main(string[] args)
        {
            var dic = new Dictionary<string, Test>();
            dic.Add("1", new());
            TestDynamic(dic, typeof(Test));
            Console.WriteLine("Hello, world!");
        }

        public static void TestDynamic(dynamic dy, Type e)
        {
            try
            {
                var o = dy["1"];
                var x = Enumerable.First(dy);

                foreach (var kvp in dy)
                {

                }
            }
            catch
            {

            }
        }
    }
}
```

No exception thrown with `Test` being `private` or `public`.

**Comment by stephentoub** [comment] 2024-07-19 16:40
Closing as no repro and no subsequent response. Thanks.

**Closed by stephentoub** 2024-07-19 16:40 UTC
Labels: area-System.Dynamic.Runtime, untriaged
