### ISSUE TITLE
NuGet ILAsm V5.0.0 /res: support is missing

### ISSUE THREAD

**Issue by gerhard17** [dotnet/runtime#48046] opened 2021-02-09 11:13 UTC
### Description
I'm migrating a C# project using IL postprocessing from .NET framework to .NET 5.

The .NET framework ILAsm has a switch /res: to include windows embedded resources like FileVersion, ProductName or Copyright. 

With the new NuGet ILAsm V5.0.0 everything is working like before, but using the /res: option results in an error:
```
Could not create output file, error code=0x80070714
```

### Configuration

The MsBuild script includes following NuGet package references
```
<ItemGroup>
  <PackageReference Include="Microsoft.NETCore.ILAsm" Version="5.0.0" GeneratePathProperty="true" PrivateAssets="all" />
  <PackageReference Include="Microsoft.NETCore.ILDAsm" Version="5.0.0" GeneratePathProperty="true" PrivateAssets="all" />
</ItemGroup>
```

The MsBuild script executes the command:
```
"C:\Users\s2477\.nuget\packages\microsoft.netcore.ilasm\5.0.0\runtimes\native\ILAsm.exe" 
/nologo /quiet 
/output="C:\GParse\NetFx.Parsing.UnsafeInterop\obj\Debug\net5.0\NetFx.Parsing.UnsafeInterop.dll" 
/alignment=512 /dll /debug:IMPL /PDBFMT=PORTABLE 
/res:"C:\GParse\NetFx.Parsing.UnsafeInterop\obj\Debug\net5.0\NetFx.Parsing.UnsafeInterop.transformed.res" 
"C:\GParse\NetFx.Parsing.UnsafeInterop\obj\Debug\net5.0\NetFx.Parsing.UnsafeInterop.transformed.il" 
"C:\GParse\NetFx.Parsing.UnsafeInterop\obj\Debug\net5.0\NetFx.Parsing.UnsafeInterop.projectdefs.il" 
"C:\GParse\NetFx.Parsing.UnsafeInterop\Global.il" 
"C:\GParse\NetFx.Parsing.UnsafeInterop\UnsafeUtilities\UnsafeMemory.il"
```

### Regression?

Yes, it worked with .NET Framework ILAsm, but fails with NuGet ILAsm Version 5.0.0

**Comment by mletterle** [comment] 2021-04-12 19:12
Related: #11412

**Comment by maximmasiutin** [comment] 2022-05-26 21:19
/res: support is also missing in ILASM 6.
If  you run the same command as in your example, but without /res:, it will compile the file without an error.

**Comment by TIHan** [comment] 2023-04-24 21:55
Duplicate of https://github.com/dotnet/runtime/issues/11412

**Closed by TIHan** 2023-04-24 21:55 UTC
Labels: area-ILTools-coreclr
