### ISSUE TITLE
[Perf -53%] System.Numerics.Tests.Perf_Vector4.GetHashCodeBenchmark

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#39029] opened 2020-07-09 22:05 UTC
### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Changes | [diff](https://github.com/dotnet/runtime/compare/a4a49f07fbf986d496ef57521e76b22caaf9bfb3...3c6656f83b01ece6af7e11eb75ec0145554b139d)

### Regressions in System.Numerics.Tests.Perf_Vector4

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier
-- | -- | -- | -- | -- | --
GetHashCodeBenchmark | 3.13 ns | 4.80 ns | 1.53 | Bimodal | True

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_09_2020/release/3.1.1xx%20-%3E%20master_x64_Windows%2010.0.18362/System.Numerics.Tests.Perf_Vector4_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_09_2020/release/3.1.1xx%20-%3E%20master_x64_Windows%2010.0.18362/System.Numerics.Tests.Perf_Vector4.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Numerics.Tests.Perf_Vector4*';
```
<details>

#### System.Numerics.Tests.Perf_Vector4.GetHashCodeBenchmark

```log
[2.799 ; 3.009) | @
[3.009 ; 3.320) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[3.320 ; 3.630) | 
[3.630 ; 3.941) | 
[3.941 ; 4.252) | 
[4.252 ; 4.483) | 
[4.483 ; 4.675) | @
[4.675 ; 4.986) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[4.986 ; 5.373) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[5.373 ; 5.771) | @
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by DrewScoggins** [comment] 2020-07-09 22:09
The earliest build we have in that graph is here, https://github.com/dotnet/core-setup/tree/b903a6e815dbcec7acfeef39db1e9189fef7ed69. That is the link to the core-setup that went into the version of core-sdk that we were running. I am not sure if that is before or after had branched for 3.1, but that should at least give a place to start looking for what caused this.

**Comment by tannergooding** [comment] 2020-07-10 00:02
There haven't been any notable changes to GetHashCode outside @stephentoub switching it off `HashHelpers.Combine` back in September: https://github.com/dotnet/runtime/commits/master/src/libraries/System.Numerics.Vectors/src (which is still the current implementation)
* Noting after October the filles moved into S.P.Corelib: https://github.com/dotnet/runtime/commits/master/src/libraries/System.Private.CoreLib/src/System/Numerics

**Comment by tannergooding** [comment] 2020-07-10 00:02
We are also talking just shy of 2ns on something that is likely never used (and shouldn't be used) in a HashTable in the first place

**Comment by DrewScoggins** [comment] 2020-07-10 18:44
Yeah, it also looks like in https://github.com/dotnet/runtime/issues/39035 @stephentoub mentioned that this was by design.

**Comment by adamsitnik** [comment] 2020-08-19 13:49
Confirmed, 5.0 milestone added:

## System.Numerics.Tests.Perf_Vector4.GetHashCodeBenchmark

| Conclusion | Base | Diff | Base/Diff | Modality | Operating System        | Bit | Processor Name                              | Base Runtime    | Diff Runtime         |
| ---------- | ----:| ----:| ---------:| --------:| ----------------------- | --- | ------------------------------------------- | --------------- | --------------------- |
| Slower     | 2.84 | 9.76 |      0.29 |          | Windows 10.0.18363.1016 | Arm | Microsoft SQ1 3.0 GHz                       | .NET Core 3.1.6 | 5.0.100-rc.1.20413.9 |
| Slower     | 2.94 | 4.58 |      0.64 |          | Windows 10.0.18363.959  | X64 | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 3.1.6 | 5.0.100-rc.1.20404.3 |
| Slower     | 3.25 | 4.37 |      0.74 |          | Windows 10.0.18363.959  | X64 | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 3.1.6 | 5.0.100-rc.1.20418.3 |
| Slower     | 3.80 | 5.39 |      0.70 |          | Windows 10.0.19041.450  | X64 | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 3.1.6 | 5.0.100-rc.1.20413.9 |
| Slower     | 3.04 | 4.84 |      0.63 |          | ubuntu 18.04            | X64 | Intel Xeon CPU E5-1650 v4 3.60GHz           | .NET Core 3.1.6 | 5.0.100-rc.1.20403.23|
| Slower     | 3.50 | 5.49 |      0.64 |          | macOS Mojave 10.14.5    | X64 | Intel Core i7-5557U CPU 3.10GHz (Broadwell) | .NET Core 3.1.6 | 5.0.100-rc.1.20404.2 |

**Comment by adamsitnik** [comment] 2020-08-20 12:55
> We are also talking just shy of 2ns on something that is likely never used

I am sorry, I've missed this comment. Removing the 5.0 milestone

**Comment by jeffhandley** [comment] 2020-08-27 23:10
Closing this as an expected (and acceptable) regression due to https://github.com/dotnet/corefx/pull/40935.

**Closed by jeffhandley** 2020-08-27 23:10 UTC
Labels: arch-x64, area-System.Numerics, os-windows, tenet-performance, tenet-performance-benchmarks, untriaged
