### ISSUE TITLE
Unexplained CPU usage on Linux when using HTTPClient and Regex

### ISSUE THREAD

**Issue by RaidMax** [dotnet/runtime#33013] opened 2020-02-29 16:29 UTC
I'm encountering a CPU usage issue when retrieving a string with `HTTPClient` and processing the resulting string with `Regex`. This issue _does not occur on Windows_.
I'm not certain if the issues lies in the `HTTPClient` or the `Regex` class.
At apparent random intervals it'll spike CPU usage. I've encountered this on multiple Linux systems (even different distros)

**Code Snippet**
```csharp
while (true)
{
    string response = await _client.GetStringAsync($"http://127.0.0.1:8080/");
    string[] lines = response.Split("\r\n");

    foreach (var line in lines)
    {
        if (Regex.Match(line, matchPattern).Success)
        {
            Console.WriteLine($"{(DateTime.Now - start).TotalMilliseconds} found match");
        }
    }

    await Task.Delay(250);
}
```

**OS**
```
centos-release-7-7.1908.0.el7.centos.x86_64
3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
**Runtime**
```
Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Symptoms**
![image](https://user-images.githubusercontent.com/6732771/75611236-53990c00-5ade-11ea-8eb8-f706f7e8cbf4.png)

**Sample Solution Reproducing Behavior**
Compile and run `dotnet HttpTestRepo.dll`
Additionally run `dotnet TestRepo.dll`
Within 60 seconds or so, the CPU should spike.
[Repro.zip](https://github.com/dotnet/runtime/files/4270562/Repro.zip)

**Comment by danmosemsft** [comment] 2020-02-29 17:54
The regex implementation is identical on Windows and Linux so most likely it is not the culprit.

Have you tried profiling? If the spike is more than a second or two or may be sufficient to just grab a dump file (https://github.com/dotnet/diagnostics/blob/master/documentation/dotnet-dump-instructions.md) and see what is going on.

**Comment by danmosemsft** [comment] 2020-02-29 17:55
How to get a profile : https://github.com/dotnet/diagnostics/blob/master/documentation/dotnet-trace-instructions.md

Please post back what you find out.

**Comment by RaidMax** [comment] 2020-02-29 17:57
Thanks for you comment. I originally captured trace logs when I encountered the issue in live code, but couldn't really ascertain the source and it's much more complex than the repro code. I will try profiling this simpler code and see what I can determine

**Comment by RaidMax** [comment] 2020-02-29 18:17
@danmosemsft,
Here are some results from speedscope analysis. 
This was about a 15 second capture.
I've attached two captures (the second one is very short during the CPU spike).
Let me know if I can provide more information.

**Thread 1**
![image](https://user-images.githubusercontent.com/6732771/75612814-d6c15e80-5aec-11ea-993b-0702c1884c64.png)

**Thread 2**
![image](https://user-images.githubusercontent.com/6732771/75612820-e17bf380-5aec-11ea-9454-96bc81e197f8.png)

**Thread 3**
![image](https://user-images.githubusercontent.com/6732771/75612832-f5275a00-5aec-11ea-9e63-7a5345d54f8f.png)

**Thread 4**
![image](https://user-images.githubusercontent.com/6732771/75612838-ff495880-5aec-11ea-8dc4-f7860bb4ed30.png)

**Reference Files**
[trace.speedscope.zip](https://github.com/dotnet/runtime/files/4270705/trace.speedscope.zip)

**Comment by danmosemsft** [comment] 2020-02-29 19:14
You could try  RegexOptions.Compiled, but I'm still guessing it's irrelevant. Is the regex getting invoked just as often in both platforms?

Cc @adamsitnik

**Comment by RaidMax** [comment] 2020-02-29 19:21
On average yes. My first attempt to counter the issue was to increase the regex cache size (as original project had a lot more patterns) followed by using the compilation and case insensitive flag when that failed to make a difference. The compiled flag slightly reduces average CPU usage but not the spikes.

**Comment by danmosemsft** [comment] 2020-02-29 19:33
If you change the regex to something else (string.contains perhaps) do you still see the difference between  platforms ?

**Comment by RaidMax** [comment] 2020-02-29 19:43
Yes, a stop gap design I started working on was implementing a different parsing method for each platform. 

Replacing the regex call with a string.Split and accessing the elements by index appears to prevent the CPU usage spikes. 

However using regex alone with a static set of strings that resemble the test data I can’t reproduce the issue.

The only way I’ve been able to reproduce the issue is using the HTTPClient and Regex in tandem.

**Comment by stephentoub** [comment] 2020-03-01 00:51
I haven't tried it, but your repro is splitting the response based on "\r\n".  Is it possible in your Linux environment the input being split contains "\n" rather than "\r\n", and that's causing different inputs than you expect to the regex?

**Comment by RaidMax** [comment] 2020-03-01 01:05
The sample text filed used as the source were created on a Windows machine. (This goes for the repro code as well as the project I originally observed this behavior in).

If it were the case that the new line characters were being altered perhaps in the WriteLine response, would high CPU utilization be a symptom?

**Comment by stephentoub** [comment] 2020-03-01 01:08
> If it were the case that the new line characters were being altered perhaps in the WriteLine response

The listener in your repro is using StreamWriter to write each line to the response.  StreamWriter by default will use "\n" as the line ending on Linux.

> would high CPU utilization be a symptom?

Potentially.  If backtracking is involved, some regular expressions can become exponentially more expensive on longer inputs.

Again, I don't know if this is the cause, but the "\r\n" jumped out at me, given the description of your issue.

**Comment by RaidMax** [comment] 2020-03-01 01:21
I think you're on the right track here. The actual source of the string/lines to be parsed are coming from a python script (not the Listener), which I assumed was sending the chunks of the file with the original line endings. 
Also in the project original noticed in the split looks like this:
![image](https://user-images.githubusercontent.com/6732771/75617705-8ff15a00-5b28-11ea-96a8-e6919a7dd906.png)


However I was able to reproduce CPU utilization on Windows by slapping two of the lines that were supposed to separated into one. Will report back if I discover anything new.

**Comment by stephentoub** [comment] 2020-03-01 19:37
> However I was able to reproduce CPU utilization on Windows by slapping two of the lines that were supposed to separated into one.

Thanks. Since the difference is now explained, can we close this issue?

**Comment by RaidMax** [comment] 2020-03-01 20:22
Yeah I think that's fine, I haven't had a chance to dig further yet, but for now it looks like it's explained by having runaway regex matching due to line ending differences.

**Comment by stephentoub** [comment] 2020-03-01 21:18
Thanks. For reference, can you share the regex, the input that takes a long time, and the expected result?

**Closed by stephentoub** 2020-03-01 21:18 UTC
Labels: area-System.Net.Http, tenet-performance, untriaged
