### ISSUE TITLE
System.Text.Json.Serialization JsonConverter not taken in account

### ISSUE THREAD

**Issue by Seamus3131** [dotnet/runtime#34581] opened 2020-04-06 09:52 UTC
Hi,

I created a simple .net core console application and trying to test serialize/deserialize an object with inheritance.
My goal is to add a property 'type' in the json serialization indicating the children class and use it also for deserialization.
Using JsonConverterAttribute on class does not work.
Adding explicitely JsonCustomConverter to list of known JsonConverter will work (but I want to avoid)

Many thanks for your help

```csharp
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace ConverterTest
{
public class CustomJsonConverter<T> : JsonConverter<T>
{
        public override bool CanConvert(Type typeToConvert) { return typeof(T).IsAssignableFrom(typeToConvert); }
        public override T Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            using (var jsonDocument = JsonDocument.ParseValue(ref reader))
            {
                var assemblies = AppDomain.CurrentDomain.GetAssemblies();
                var types = new List<Type>();
                foreach (var assembly in assemblies)
                {
                    try { types.AddRange(assembly.GetTypes()); }
                    catch { /*silent*/ }
                }
                var realTypeToConvert = types.FirstOrDefault(
                    t => t.Name == jsonDocument.RootElement.GetProperty(@"type").GetString()
                    );
                return (T)JsonSerializer.Deserialize(jsonDocument.RootElement.GetRawText(), realTypeToConvert, options);
            }
        }

        public override void Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
        {
            Type typeFromConvert = value.GetType();
            var json = JsonSerializer.Serialize(value, typeFromConvert);
            using (var jsonDoc = JsonDocument.Parse(json))
            {
                writer.WriteStartObject();
                writer.WriteString("type", typeFromConvert.Name);
                foreach (JsonProperty element in jsonDoc.RootElement.EnumerateObject())
                {
                    element.WriteTo(writer);
                }
                writer.WriteEndObject();
            }
        }
}

 [JsonConverter(typeof(CustomJsonConverter<DataTypeDTO>))]
 public class DataTypeDTO
 {
        public string Id { get; set; }
 }
 public class LongDataTypeDTO : DataTypeDTO    {
        public string Name { get; set; }
 }

class Program{
   public static void Main(string[] args)
   {
      JsonSerializerOptions _options = new JsonSerializerOptions { WriteIndented = true,   PropertyNamingPolicy = JsonNamingPolicy.CamelCase };
      LongDataTypeDTO longDataTypeDTO = new LongDataTypeDTO() { Id = "1", Name = "2" };
      var stringContent = JsonSerializer.Serialize(longDataTypeDTO, _options);
      Console.WriteLine(stringContent);
      var obj = JsonSerializer.Deserialize<DataTypeDTO>(stringContent, _options);
      Console.ReadKey();
   }
}
}
```

**Comment by layomia** [comment] 2020-04-06 17:47
As you mention, adding an instance of the converter to the `Converters` collection works. **Why do you want to avoid doing this**?

When the serializer fetches `JsonConverterAttribute` on types, it doesn't include those inherited from parents. So the attribute placed on `DataTypeDTO` will be used only instances declared as that type, e.g. `JsonSerializer.Serialize<DataTypeDTO>(longDataTypeDTO, _options);` should work as expected.

The other thing to note is you shouldn't pass the same `JsonSerializerOptions` instance (that contains the current converter) when recursively calling back into the serializer. See more documentation [here](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to#callbacks).

See https://dotnetfiddle.net/CgGeL2 for some modifications to your repro showing how I assume you expect things to work.

**Comment by Seamus3131** [comment] 2020-04-06 19:32
Thanks for the response.

I wanted to avoid explicit add to Converters, to be able to deliver the object and CustomConverter in lib usable by others without they need to know specific option init to perform json serialization.

I will use this thread for one additional question, using your updates, I see that CamelCase is not used even with the option configure. Do you have an idea on what could be the problem?
Is it related to the CustomConverter wich needs to make usage of the JsonSerializerOptions?

Many thanks

**Comment by Seamus3131** [comment] 2020-04-06 19:35
Thanks

> As you mention, adding an instance of the converter to the Converters collection works. Why do you want to avoid doing this?
> When the serializer fetches JsonConverterAttribute on types, it doesn't include those inherited from parents. So the attribute placed on DataTypeDTO will be used only instances declared as that type, e.g. JsonSerializer.Serialize<DataTypeDTO>(longDataTypeDTO, _options); should work as expected.
> The other thing to note is you shouldn't pass the same JsonSerializerOptions instance (that contains the current converter) when recursively calling back into the serializer. See more documentation here.
> See https://dotnetfiddle.net/CgGeL2 for some modifications to your repro showing how I assume you expect things to work.

Thank you

**Comment by layomia** [comment] 2020-04-06 23:04
Wrt the `JsonConverterAttribute` being applied to derived types, closing as a duplicate of https://github.com/dotnet/runtime/issues/30427.

**Closed by layomia** 2020-04-06 23:04 UTC
Labels: area-System.Text.Json
