### ISSUE TITLE
Test failure : Loader/classloader/MethodImpl/self_override5/self_override5.sh

### ISSUE THREAD

**Issue by AriNuer** [dotnet/runtime#33275] opened 2020-03-06 05:55 UTC
**Job:**
[runtime-coreclr crossgen2 outerloop:20200304.1](https://dev.azure.com/dnceng/public/_build/results?buildId=547414&view=results)

**Error message:**
```
Return code: 1
Raw output file: /home/helixbot/work/B6220979/w/B9100A00/e/Loader/classloader/Reports/Loader.classloader/MethodImpl/self_override5/self_override5.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
Warning: No files matching /home/helixbot/work/B6220979/w/B9100A00/e/Loader/classloader/MethodImpl/self_override5/*.dll
Emitting R2R PE file: /home/helixbot/work/B6220979/w/B9100A00/e/Loader/classloader/MethodImpl/self_override5/self_override5.dll

in ReleaseLock
/home/helixbot/work/B6220979/p/corerun self_override5.dll ''
In MyFoo::DoBarOverride
In MyBar::DoBar
FAIL: expected MyBar::DoBarOverride to execute, but another method was executed instead.
FAIL
Expected: 100
Actual: 101
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/home/helixbot/work/B6220979/p
> /home/helixbot/work/B6220979/w/B9100A00/e/Loader/classloader/MethodImpl/self_override5/self_override5.sh
Expected: True
Actual: False
```
**Stack tarce:**
`
at Loader_classloader._MethodImpl_self_override5_self_override5_._MethodImpl_self_override5_self_override5_sh() in /Users/runner/runners/2.165.0/work/1/s/artifacts/tests/coreclr/OSX.x64.Checked/TestWrappers/Loader.classloader/Loader.classloader.XUnitWrapper.cs:line 173188
`

**Details:**
https://dev.azure.com/dnceng/public/_build/results?buildId=547414&view=ms.vss-test-web.build-test-results-tab&runId=17309172&resultId=100691&paneView=debug

**Comment by mangod9** [comment] 2020-03-16 17:36
dupe of https://github.com/dotnet/runtime/issues/32731

**Comment by mangod9** [comment] 2020-03-20 16:32
closing since the original issue should be fixed.

**Closed by mangod9** 2020-03-20 16:32 UTC
Labels: arch-x64, area-crossgen2-coreclr, os-linux
