### ISSUE TITLE
Test failure JIT\\HardwareIntrinsics\\General\\Regression\\GitHub_47236\\GitHub_47236\\GitHub_47236.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#66570] opened 2022-03-14 02:00 UTC
Run: [runtime-coreclr r2r 20220310.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1658055&view=ms.vss-test-web.build-test-results-tab&runId=45675952&resultId=100132&paneView=debug)

Failed test:
```
R2R windows x86 Checked @ Windows.10.Amd64.Open

- JIT\\HardwareIntrinsics\\General\\Regression\\GitHub_47236\\GitHub_47236\\GitHub_47236.cmd

```
**Error message:**
```
Could Not Find C:\h\w\B0B809CA\w\A3010934\e\JIT\HardwareIntrinsics\General\Regression\GitHub_47236\GitHub_47236\IL-CG2\composite-r2r.dll
Could Not Find C:\h\w\B0B809CA\w\A3010934\e\JIT\HardwareIntrinsics\General\Regression\GitHub_47236\GitHub_47236\GitHub_47236.dll.rsp
Unhandled exception. System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)
at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable1 searchPath, Boolean throwOnError) at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable1 searchPath)
at Internal.JitInterface.JitConfigProvider.<>c__DisplayClass5_0.<Initialize>b__0(String libName, Assembly assembly, Nullable1 searchPath) at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags) at Internal.JitInterface.CorInfoImpl.GetJitHost(IntPtr configProvider) at Internal.JitInterface.CorInfoImpl.Startup(CORINFO_OS os) at Internal.JitInterface.JitConfigProvider.Initialize(TargetDetails target, IEnumerable1 jitFlags, IEnumerable1 parameters, String jitPath) at ILCompiler.ReadyToRunCodegenCompilationBuilder.ToCompilation() at ILCompiler.Program.RunSingleCompilation(Dictionary2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary2 unrootedInputFilePaths, HashSet1 versionBubbleModulesHash, CompilerTypeSystemContext typeSystemContext)
at ILCompiler.Program.Run(String[] args)
at ILCompiler.Program.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\B0B809CA\w\A3010934\uploads\Reports\JIT.HardwareIntrinsics\General\Regression\GitHub_47236\GitHub_47236\GitHub_47236.output.txt
Raw output:
BEGIN EXECUTION
GitHub_47236.dll
TestLibrary.dll
2 file(s) copied.
Response file: C:\h\w\B0B809CA\w\A3010934\e\JIT\HardwareIntrinsics\General\Regression\GitHub_47236\GitHub_47236\GitHub_47236.dll.rsp
C:\h\w\B0B809CA\w\A3010934\e\JIT\HardwareIntrinsics\General\Regression\GitHub_47236\GitHub_47236\IL-CG2\GitHub_47236.dll
-o:C:\h\w\B0B809CA\w\A3010934\e\JIT\HardwareIntrinsics\General\Regression\GitHub_47236\GitHub_47236\GitHub_47236.dll
--targetarch:x86
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\B0B809CA\p\System..dll
-r:C:\h\w\B0B809CA\p\Microsoft..dll
-r:C:\h\w\B0B809CA\p\mscorlib.dll
-r:C:\h\w\B0B809CA\p\netstandard.dll
-O
" "dotnet" "C:\h\w\B0B809CA\p\crossgen2\crossgen2.dll" @"C:\h\w\B0B809CA\w\A3010934\e\JIT\HardwareIntrinsics\General\Regression\GitHub_47236\GitHub_47236\GitHub_47236.dll.rsp"   -r:C:\h\w\B0B809CA\w\A3010934\e\JIT\HardwareIntrinsics\General\Regression\GitHub_47236\GitHub_47236\IL-CG2*.dll"
Crossgen2 failed with exitcode - -532462766
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\B0B809CA\p
C:\h\w\B0B809CA\w\A3010934\e\JIT\HardwareIntrinsics\General\Regression\GitHub_47236\GitHub_47236\GitHub_47236.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_HardwareIntrinsics._General_Regression_GitHub_47236_GitHub_47236_GitHub_47236_._General_Regression_GitHub_47236_GitHub_47236_GitHub_47236_cmd()
```

**Comment by trylek** [comment] 2022-04-04 20:23
This is possibly a dupe of https://github.com/dotnet/runtime/issues/65646 but I'm not closing this one yet as it's slightly different - this one fails loading the clrjit shared library, not managed assemblies.

**Comment by trylek** [comment] 2022-04-04 20:58
So far this has only been seen on Windows x86 and arm.

**Comment by mangod9** [comment] 2022-07-06 17:40
Closing since this hasnt reproed in a few months.

**Closed by mangod9** 2022-07-06 17:40 UTC
Labels: arch-x86, os-windows, area-crossgen2-coreclr, untriaged
