### ISSUE TITLE
JIT: Spurious 0-sized diffs in smoke_tests.nativeaot.windows.arm64

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#104441] opened 2024-07-04 14:49 UTC
We're seeing some spurious 0-sized diffs in smoke_tests.nativeaot.windows.arm64. Seems likely to be related to #104282, can you take a look @kunalspathak?

**Comment by jakobbotsch** [comment] 2024-07-21 16:34
@kunalspathak #104516 does not seem to have fixed this issue -- I still see 0 sized diffs on superpmi-diffs in smoke_tests.nativeaot.windows.arm64.checked.

**Comment by kunalspathak** [comment] 2024-07-22 00:37
> @kunalspathak #104516 does not seem to have fixed this issue -- I still see 0 sized diffs on superpmi-diffs in smoke_tests.nativeaot.windows.arm64.checked.

Yes, the fix in #104516 was mainly for handling the "unhandled reloc type" errors and not this specific one. I was not able to setup libcoredistools to debug what the problem is. Will send separate fix for this one.

**Closed** 2024-07-26 16:50 UTC
Labels: area-CodeGen-coreclr
