### ISSUE TITLE
.Net 6  installation failed on Mac

### ISSUE THREAD

**Issue by NicoleWang001** [dotnet/runtime#46962] opened 2021-01-12 02:48 UTC
**Affected Mac:**
Mac OS: Catalina(10.15.6)&Big Sur(11.1) - intel chip

**Steps to reproduce:**
1.  Download SDK "dotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg" from https://github.com/dotnet/installer,
2.  Open and install ​

**Expected result:**
1. .net 6 is installed successfully

**Actual result:**
1. Error occurs when try to install .net 6.
![image](https://user-images.githubusercontent.com/1578239/104262697-10ac1100-54c3-11eb-9b7c-a1238d594fe5.png)
install log:
2021-01-12 09:50:01+08 e2euser2s-Mac-mini Installer[3878]: Microsoft .NET SDK 6.0.100-alpha.1.21060.3 (x64) 6.0.100-alpha.1.21060.3 Installation Log
2021-01-12 09:50:01+08 e2euser2s-Mac-mini Installer[3878]: Opened from: /Users/e2euser2/Downloads/dotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg
2021-01-12 09:50:01+08 e2euser2s-Mac-mini Installer[3878]: Package Authoring Error: <background> has an unsupported MIME type: image/data
2021-01-12 09:50:01+08 e2euser2s-Mac-mini Installer[3878]: Package Authoring Error: <background_scaling> has an unsupported MIME type: X-NSObject/NSNumber
2021-01-12 09:50:01+08 e2euser2s-Mac-mini Installer[3878]: Package Authoring Error: <background_alignment> has an unsupported MIME type: X-NSObject/NSNumber
2021-01-12 09:50:01+08 e2euser2s-Mac-mini Installer[3878]: Package Authoring Error: <layout-direction> has an unsupported MIME type: X-NSObject/NSNumber
2021-01-12 09:50:01+08 e2euser2s-Mac-mini Installer[3878]: Failed to load specified background image
2021-01-12 09:50:01+08 e2euser2s-Mac-mini Installer[3878]: Product archive /Users/e2euser2/Downloads/dotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg trustLevel=100
2021-01-12 09:50:01+08 e2euser2s-Mac-mini Installer[3878]: Could not load resource readme: (null)
2021-01-12 09:50:01+08 e2euser2s-Mac-mini Installer[3878]: Could not load resource license: (null)
2021-01-12 09:50:05+08 e2euser2s-Mac-mini Installer[3878]: ================================================================================
2021-01-12 09:50:05+08 e2euser2s-Mac-mini Installer[3878]: User picked Standard Install
2021-01-12 09:50:05+08 e2euser2s-Mac-mini Installer[3878]: Choices selected for installation:
2021-01-12 09:50:05+08 e2euser2s-Mac-mini Installer[3878]: 	Upgrade: "Microsoft .NET SDK 6.0.100-alpha.1.21060.3 (x64)"
2021-01-12 09:50:05+08 e2euser2s-Mac-mini Installer[3878]: 	Install: "Microsoft .NET Targeting Pack 6.0.0-alpha.1.21059.3 (x64)"
2021-01-12 09:50:05+08 e2euser2s-Mac-mini Installer[3878]: 		dotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg#com.microsoft.dotnet.pack.targeting.6.0.0-alpha.1.21059.3.component.osx.x64.pkg : com.microsoft.dotnet.pack.targeting.6.0.0-alpha.1.21059.3.component.osx.x64.pkg : 6.0.0
2021-01-12 09:50:05+08 e2euser2s-Mac-mini Installer[3878]: 	Upgrade: "Microsoft .NET Standard 2.1 Targeting Pack 2.1.0 (x64)"
2021-01-12 09:50:05+08 e2euser2s-Mac-mini Installer[3878]: 		dotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg#com.microsoft.standard.pack.targeting.2.1.0.component.osx.x64.pkg : com.microsoft.standard.pack.targeting.2.1.0.component.osx.x64.pkg : 2.1.0
2021-01-12 09:50:05+08 e2euser2s-Mac-mini Installer[3878]: 	Install: "Microsoft .NET AppHost Pack  (x64)"
2021-01-12 09:50:05+08 e2euser2s-Mac-mini Installer[3878]: 		dotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg#com.microsoft.dotnet.pack.apphost.6.0.0-alpha.1.21059.3.component.osx.x64.pkg : com.microsoft.dotnet.pack.apphost.6.0.0-alpha.1.21059.3.component.osx.x64.pkg : 6.0.0
2021-01-12 09:50:05+08 e2euser2s-Mac-mini Installer[3878]: 	Upgrade: "Microsoft .NET Runtime 6.0.0-alpha.1.21059.3 (x64)"
2021-01-12 09:50:05+08 e2euser2s-Mac-mini Installer[3878]: 		dotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg#com.microsoft.dotnet.sharedframework.Microsoft.NETCore.App..component.osx.x64.pkg : com.microsoft.dotnet.sharedframework.Microsoft.NETCore.App..component.osx.x64.pkg : 6.0.0
2021-01-12 09:50:05+08 e2euser2s-Mac-mini Installer[3878]: 	Install: "Microsoft .NET Host FX Resolver 6.0.0-alpha.1.21059.3 (x64)"
2021-01-12 09:50:05+08 e2euser2s-Mac-mini Installer[3878]: 		dotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg#com.microsoft.dotnet.hostfxr.6.0.0-alpha.1.21059.3.component.osx.x64.pkg : com.microsoft.dotnet.hostfxr.6.0.0-alpha.1.21059.3.component.osx.x64.pkg : 6.0.0
2021-01-12 09:50:05+08 e2euser2s-Mac-mini Installer[3878]: 	Install: "Microsoft .NET Host 6.0.0-alpha.1.21059.3 (x64)"
2021-01-12 09:50:05+08 e2euser2s-Mac-mini Installer[3878]: 		dotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg#com.microsoft.dotnet.sharedhost.6.0.0-alpha.1.21059.3.component.osx.x64.pkg : com.microsoft.dotnet.sharedhost.6.0.0-alpha.1.21059.3.component.osx.x64.pkg : 6.0.0
2021-01-12 09:50:05+08 e2euser2s-Mac-mini Installer[3878]: 	Install: "Microsoft .NET SDK 6.0.100-alpha.1.21060.3 (x64)"
2021-01-12 09:50:05+08 e2euser2s-Mac-mini Installer[3878]: 		dotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg#com.microsoft.dotnet.dev.6.0.100-alpha.1.21060.3.component.osx.x64.pkg : com.microsoft.dotnet.dev.6.0.100-alpha.1.21060.3.component.osx.x64.pkg : 6.0.100-alpha.1.21060.3
2021-01-12 09:50:05+08 e2euser2s-Mac-mini Installer[3878]: ================================================================================
2021-01-12 09:50:05+08 e2euser2s-Mac-mini Installer[3878]: It took 0.00 seconds to summarize the package selections.
2021-01-12 09:50:06+08 e2euser2s-Mac-mini Installer[3878]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: location = file://localhost
2021-01-12 09:50:06+08 e2euser2s-Mac-mini Installer[3878]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Users/e2euser2/Downloads/dotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg#com.microsoft.dotnet.pack.targeting.6.0.0-alpha.1.21059.3.component.osx.x64.pkg
2021-01-12 09:50:06+08 e2euser2s-Mac-mini Installer[3878]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Users/e2euser2/Downloads/dotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg#com.microsoft.standard.pack.targeting.2.1.0.component.osx.x64.pkg
2021-01-12 09:50:06+08 e2euser2s-Mac-mini Installer[3878]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Users/e2euser2/Downloads/dotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg#com.microsoft.dotnet.pack.apphost.6.0.0-alpha.1.21059.3.component.osx.x64.pkg
2021-01-12 09:50:06+08 e2euser2s-Mac-mini Installer[3878]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Users/e2euser2/Downloads/dotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg#com.microsoft.dotnet.sharedframework.Microsoft.NETCore.App..component.osx.x64.pkg
2021-01-12 09:50:06+08 e2euser2s-Mac-mini Installer[3878]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Users/e2euser2/Downloads/dotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg#com.microsoft.dotnet.hostfxr.6.0.0-alpha.1.21059.3.component.osx.x64.pkg
2021-01-12 09:50:06+08 e2euser2s-Mac-mini Installer[3878]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Users/e2euser2/Downloads/dotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg#com.microsoft.dotnet.sharedhost.6.0.0-alpha.1.21059.3.component.osx.x64.pkg
2021-01-12 09:50:06+08 e2euser2s-Mac-mini Installer[3878]: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Users/e2euser2/Downloads/dotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg#com.microsoft.dotnet.dev.6.0.100-alpha.1.21060.3.component.osx.x64.pkg
2021-01-12 09:50:06+08 e2euser2s-Mac-mini Installer[3878]: Set authorization level to root for session
2021-01-12 09:50:11+08 e2euser2s-Mac-mini Installer[3878]: Administrator authorization granted.
2021-01-12 09:50:11+08 e2euser2s-Mac-mini Installer[3878]: Will use PK session
2021-01-12 09:50:11+08 e2euser2s-Mac-mini Installer[3878]: Using authorization level of root for IFPKInstallElement
2021-01-12 09:50:11+08 e2euser2s-Mac-mini Installer[3878]: Starting installation:
2021-01-12 09:50:11+08 e2euser2s-Mac-mini Installer[3878]: Configuring volume "Untitled"
2021-01-12 09:50:11+08 e2euser2s-Mac-mini Installer[3878]: Preparing disk for local booted install.
2021-01-12 09:50:11+08 e2euser2s-Mac-mini Installer[3878]: Free space on "Untitled": 62.01 GB (62007308288 bytes).
2021-01-12 09:50:11+08 e2euser2s-Mac-mini Installer[3878]: Create temporary directory "/var/folders/5s/v3qcm3kd0c92h5_4772b1csw0000gn/T//Install.3878owfbZg"
2021-01-12 09:50:11+08 e2euser2s-Mac-mini Installer[3878]: IFPKInstallElement (7 packages)
2021-01-12 09:50:12+08 e2euser2s-Mac-mini Installer[3878]: Current Path: /System/Library/CoreServices/Installer.app/Contents/MacOS/Installer
2021-01-12 09:50:12+08 e2euser2s-Mac-mini installd[654]: PackageKit: Adding client PKInstallDaemonClient pid=3878, uid=501 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
2021-01-12 09:50:12+08 e2euser2s-Mac-mini Installer[3878]: PackageKit: Enqueuing install with framework-specified quality of service (utility)
2021-01-12 09:50:12+08 e2euser2s-Mac-mini installd[654]: PackageKit: ----- Begin install -----
2021-01-12 09:50:12+08 e2euser2s-Mac-mini installd[654]: PackageKit: request=PKInstallRequest <7 packages, destination=/>
2021-01-12 09:50:12+08 e2euser2s-Mac-mini installd[654]: PackageKit: packages=(
	    "<null>",
	    "<null>",
	    "<null>",
	    "<null>",
	    "<null>",
	    "<null>",
	    "<null>"
	)
2021-01-12 09:50:12+08 e2euser2s-Mac-mini installd[654]: PackageKit: Set reponsibility for install to 3878
2021-01-12 09:50:12+08 e2euser2s-Mac-mini installd[654]: PackageKit: Will do receipt-based obsoleting for package identifier com.microsoft.netstandard.pack.targeting.2.1.0.component.osx.x64 (prefix path=usr/local/share/dotnet)
2021-01-12 09:50:12+08 e2euser2s-Mac-mini installd[654]: PackageKit: Will do receipt-based obsoleting for package identifier com.microsoft.dotnet.sharedhost.component.osx.x64 (prefix path=usr/local/share/dotnet)
2021-01-12 09:50:12+08 e2euser2s-Mac-mini installd[654]: PackageKit: Extracting file://localhost/Users/e2euser2/Downloads/dotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg#com.microsoft.dotnet.pack.targeting.6.0.0-alpha.1.21059.3.component.osx.x64.pkg (destination=/Library/InstallerSandboxes/.PKInstallSandboxManager/97953CD9-2E05-40B0-8A95-A9B5F0F18508.activeSandbox/Root/usr/local/share/dotnet, uid=0)
2021-01-12 09:50:12+08 e2euser2s-Mac-mini installd[654]: PackageKit: Extracting file://localhost/Users/e2euser2/Downloads/dotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg#com.microsoft.standard.pack.targeting.2.1.0.component.osx.x64.pkg (destination=/Library/InstallerSandboxes/.PKInstallSandboxManager/97953CD9-2E05-40B0-8A95-A9B5F0F18508.activeSandbox/Root/usr/local/share/dotnet, uid=0)
2021-01-12 09:50:12+08 e2euser2s-Mac-mini installd[654]: PackageKit: Extracting file://localhost/Users/e2euser2/Downloads/dotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg#com.microsoft.dotnet.pack.apphost.6.0.0-alpha.1.21059.3.component.osx.x64.pkg (destination=/Library/InstallerSandboxes/.PKInstallSandboxManager/97953CD9-2E05-40B0-8A95-A9B5F0F18508.activeSandbox/Root/usr/local/share/dotnet, uid=0)
2021-01-12 09:50:12+08 e2euser2s-Mac-mini installd[654]: PackageKit: Extracting file://localhost/Users/e2euser2/Downloads/dotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg#com.microsoft.dotnet.sharedframework.Microsoft.NETCore.App..component.osx.x64.pkg (destination=/Library/InstallerSandboxes/.PKInstallSandboxManager/97953CD9-2E05-40B0-8A95-A9B5F0F18508.activeSandbox/Root/usr/local/share/dotnet, uid=0)
2021-01-12 09:50:13+08 e2euser2s-Mac-mini installd[654]: PackageKit: Extracting file://localhost/Users/e2euser2/Downloads/dotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg#com.microsoft.dotnet.hostfxr.6.0.0-alpha.1.21059.3.component.osx.x64.pkg (destination=/Library/InstallerSandboxes/.PKInstallSandboxManager/97953CD9-2E05-40B0-8A95-A9B5F0F18508.activeSandbox/Root/usr/local/share/dotnet, uid=0)
2021-01-12 09:50:13+08 e2euser2s-Mac-mini installd[654]: PackageKit: Extracting file://localhost/Users/e2euser2/Downloads/dotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg#com.microsoft.dotnet.sharedhost.6.0.0-alpha.1.21059.3.component.osx.x64.pkg (destination=/Library/InstallerSandboxes/.PKInstallSandboxManager/97953CD9-2E05-40B0-8A95-A9B5F0F18508.activeSandbox/Root/usr/local/share/dotnet, uid=0)
2021-01-12 09:50:13+08 e2euser2s-Mac-mini installd[654]: PackageKit: Extracting file://localhost/Users/e2euser2/Downloads/dotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg#com.microsoft.dotnet.dev.6.0.100-alpha.1.21060.3.component.osx.x64.pkg (destination=/Library/InstallerSandboxes/.PKInstallSandboxManager/97953CD9-2E05-40B0-8A95-A9B5F0F18508.activeSandbox/Root/usr/local/share/dotnet, uid=0)
2021-01-12 09:50:14+08 e2euser2s-Mac-mini installd[654]: PackageKit: prevent user idle system sleep
2021-01-12 09:50:14+08 e2euser2s-Mac-mini installd[654]: PackageKit: suspending backupd
2021-01-12 09:50:14+08 e2euser2s-Mac-mini installd[654]: PackageKit: Using trashcan path /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/PKInstallSandboxTrash/97953CD9-2E05-40B0-8A95-A9B5F0F18508.sandboxTrash for sandbox /Library/InstallerSandboxes/.PKInstallSandboxManager/97953CD9-2E05-40B0-8A95-A9B5F0F18508.activeSandbox
2021-01-12 09:50:14+08 e2euser2s-Mac-mini install_monitor[3886]: Temporarily excluding: /AppleInternal, /Applications, /Library, /System, /bin, /private, /sbin, /usr
2021-01-12 09:50:14+08 e2euser2s-Mac-mini installd[654]: PackageKit: Shoving /Library/InstallerSandboxes/.PKInstallSandboxManager/97953CD9-2E05-40B0-8A95-A9B5F0F18508.activeSandbox/Root (1 items) to /
2021-01-12 09:50:15+08 e2euser2s-Mac-mini installd[654]: PackageKit (package_script_service): Preparing to execute script "./postinstall" in /private/tmp/PKInstallSandbox.iAJksC/Scripts/com.microsoft.dotnet.hostfxr.6.0.0.component.osx.x64.BpdGui
2021-01-12 09:50:15+08 e2euser2s-Mac-mini package_script_service[1140]: PackageKit: Executing script "postinstall" in /tmp/PKInstallSandbox.iAJksC/Scripts/com.microsoft.dotnet.hostfxr.6.0.0.component.osx.x64.BpdGui
2021-01-12 09:50:15+08 e2euser2s-Mac-mini package_script_service[1140]: Set responsibility to pid: 3878, responsible_path: /System/Library/CoreServices/Installer.app/Contents/MacOS/Installer
2021-01-12 09:50:15+08 e2euser2s-Mac-mini package_script_service[1140]: PackageKit: *** launch path not accessible
2021-01-12 09:50:15+08 e2euser2s-Mac-mini package_script_service[1140]: PackageKit: Failed task attributes: {
	    NSFileCreationDate = "2021-01-09 22:13:56 +0000";
	    NSFileExtensionHidden = 0;
	    NSFileGroupOwnerAccountID = 0;
	    NSFileGroupOwnerAccountName = wheel;
	    NSFileHFSCreatorCode = 0;
	    NSFileHFSTypeCode = 0;
	    NSFileModificationDate = "2021-01-09 22:13:56 +0000";
	    NSFileOwnerAccountID = 0;
	    NSFileOwnerAccountName = root;
	    NSFilePosixPermissions = 420;
	    NSFileReferenceCount = 1;
	    NSFileSize = 454;
	    NSFileSystemFileNumber = 65312;
	    NSFileSystemNumber = 16777229;
	    NSFileType = NSFileTypeRegular;
	}
2021-01-12 09:50:15+08 e2euser2s-Mac-mini package_script_service[1140]: Responsibility set back to self.
2021-01-12 09:50:15+08 e2euser2s-Mac-mini install_monitor[3886]: Re-included: /AppleInternal, /Applications, /Library, /System, /bin, /private, /sbin, /usr
2021-01-12 09:50:16+08 e2euser2s-Mac-mini installd[654]: PackageKit: releasing backupd
2021-01-12 09:50:16+08 e2euser2s-Mac-mini installd[654]: PackageKit: allow user idle system sleep
2021-01-12 09:50:16+08 e2euser2s-Mac-mini installd[654]: PackageKit: Cleared responsibility for install from 3878.
2021-01-12 09:50:16+08 e2euser2s-Mac-mini installd[654]: PackageKit: Cleared permissions on Installer.app
2021-01-12 09:50:16+08 e2euser2s-Mac-mini installd[654]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “dotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Users/e2euser2/Downloads/dotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg#com.microsoft.dotnet.hostfxr.6.0.0-alpha.1.21059.3.component.osx.x64.pkg, PKInstallPackageIdentifier=com.microsoft.dotnet.hostfxr.6.0.0.component.osx.x64, NSLocalizedDescription=An error occurred while running scripts from the package “dotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg”.} {
	    NSFilePath = "./postinstall";
	    NSLocalizedDescription = "An error occurred while running scripts from the package \U201cdotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg\U201d.";
	    NSURL = "file://localhost/Users/e2euser2/Downloads/dotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg#com.microsoft.dotnet.hostfxr.6.0.0-alpha.1.21059.3.component.osx.x64.pkg";
	    PKInstallPackageIdentifier = "com.microsoft.dotnet.hostfxr.6.0.0.component.osx.x64";
	}
2021-01-12 09:50:16+08 e2euser2s-Mac-mini installd[654]: PackageKit: Running idle tasks
2021-01-12 09:50:16+08 e2euser2s-Mac-mini Installer[3878]: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “dotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file://localhost/Users/e2euser2/Downloads/dotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg#com.microsoft.dotnet.hostfxr.6.0.0-alpha.1.21059.3.component.osx.x64.pkg, PKInstallPackageIdentifier=com.microsoft.dotnet.hostfxr.6.0.0.component.osx.x64, NSLocalizedDescription=An error occurred while running scripts from the package “dotnet-sdk-6.0.100-alpha.1.21060.3-osx-x64.pkg”.}
2021-01-12 09:50:16+08 e2euser2s-Mac-mini installd[654]: PackageKit: Removing client PKInstallDaemonClient pid=3878, uid=501 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
2021-01-12 09:50:16+08 e2euser2s-Mac-mini installd[654]: PackageKit: Done with sandbox removals
2021-01-12 09:50:17+08 e2euser2s-Mac-mini Installer[3878]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
2021-01-12 09:50:17+08 e2euser2s-Mac-mini Installer[3878]: IFDInstallController 340CBA0 state = 8
2021-01-12 09:50:17+08 e2euser2s-Mac-mini Installer[3878]: Displaying 'Install Failed' UI.
2021-01-12 09:50:17+08 e2euser2s-Mac-mini Installer[3878]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.
2021-01-12 09:50:23+08 e2euser2s-Mac-mini Installer[3878]: Package Removal: User opted to keep package.

**Comment by wli3** [comment] 2021-01-14 00:30
I find installing `com.microsoft.dotnet.hostfxr.6.0.0-alpha.1.21063.3.component.osx.x64.pkg` alone could cause this issue.

**Comment by wli3** [comment] 2021-01-14 00:31
And install `dotnet-sdk-internal-6.0.100-dev-osx-x64.pkg` separately is also fine.

**Comment by wli3** [comment] 2021-01-14 00:32
Note this is a blocking issue.

**Comment by akoeplinger** [comment] 2021-01-19 15:34
I think I know what the issue is: the `postinstall` script is not marked as `executable` anymore:

```
$ ls -lah dotnet6/com.microsoft.dotnet.hostfxr.6.0.0-alpha.1.21068.2.component.osx.x64.pkg/Scripts/
-rw-r--r--  1 alexander  staff   454B Jan 18 12:43 postinstall

$ ls -lah dotnet5/com.microsoft.dotnet.hostfxr.5.0.1.component.osx.x64.pkg/Scripts/
-rwxr-xr-x  1 alexander  staff   389B Nov 26 03:05 postinstall
```

**Comment by akoeplinger** [comment] 2021-01-20 12:54
I tested with dotnet-sdk-6.0.100-alpha.1.21070.3-osx-x64.pkg and it installs without issue now :)

**Closed by akoeplinger** 2021-01-20 12:54 UTC
Labels: area-Setup, untriaged
