### ISSUE TITLE
Consider adding a way to customize console log output format

### ISSUE THREAD

**Issue by robbieknuth** [dotnet/runtime#35430] opened 2019-09-05 07:29 UTC
### Is your feature request related to a problem? Please describe.
The default logging format is good for readability. And it is already demonstrated that customization is needed, given the existence of ConsoleLoggerFormat, eg Default and Systemd. I sometimes have a need for logging raw text without any kind of formatting at all, and sometimes to output a json formatted log for more structured logging. I want a way to take the components of the log messages and format them in whatever way i see fit, but benefit from the work done to have a log queue that prevents log tearing, and be able to plug this logger into everything that expects an ILogger already.

### Describe the solution you'd like
I would like a way to specify the format used by the console logger, to potentially eliminate timestamps, event id, etc, and simply write text. Or, take a log message with its various fields and return a string

### Describe alternatives you've considered
- Console.Writeline => this works, but doesn't play nice with DI, nor does it play nice with things like LogLevel. Also the console logger has a queue to prevent log tearing.
- Heavily copying the consolelogger implementation => this isn't that hard, and will be what I do in the short term, however something built in would eliminate the need for a custom implementation. And special casing Systemd acknowledges that custom formatting is already needed.

### Additional context
Effectively I want a way to give a delegate that would act like CreateSystemdLogMessage or CreateDefaultLogMessage.

**Comment by maryamariyan** [comment] 2020-06-22 21:49
close as dupe of #34742, if you see anything missing from this feature just let us know.

**Closed by maryamariyan** 2020-06-22 21:49 UTC
Labels: area-Extensions-Logging, untriaged
