### ISSUE TITLE
System.Text.Json.JsonSerializer does not deserialize System.Version properly

### ISSUE THREAD

**Issue by michaeloyer** [dotnet/runtime#50465] opened 2021-03-31 03:24 UTC
### Description

The call to `JsonSerializer.Deserialize<Version>` does not appear to be applying the values in my json payload. Example code below.

```
open System
open System.Text.Json

let version = Version(1,2,3)
let serializedVersion = JsonSerializer.Serialize(version)
let deserializedVersion = JsonSerializer.Deserialize<Version>(serializedVersion)

// Output
printfn $"{nameof(version)}: {version}"
printfn $"{nameof(serializedVersion)}: {serializedVersion}"
printfn $"{nameof(deserializedVersion)}: {deserializedVersion}"
```

#### Output:
```
version: 1.2.3
serializedVersion: {"Major":1,"Minor":2,"Build":3,"Revision":-1,"MajorRevision":-1,"MinorRevision":-1}
deserializedVersion: 0.0  <-- (Unexpected)
```

#### Expected Output:
```
deserializedVersion: 1.2.3
```

### Configuration
**net5.0**, **netcoreapp3.1**

### Other Information
Same effect if `Version` is a property on a class or in an array

**Comment by eiriktsarpalis** [comment] 2021-03-31 13:44
This is by design. The default serialization for classes is to write public properties to JSON (and in this case deserialize via the default constructor). The recommended workaround is to register a [custom converter for `System.Version`](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to?pivots=dotnet-5-0#sample-basic-converter):

```csharp
public class VersionConverter : JsonConverter<Version>
{
    public override Version Read(ref Utf8JsonReader reader, Type _, JsonSerializerOptions _)
        => new Version(reader.GetString());

    public override void Write(Utf8JsonWriter writer, Version version, JsonSerializerOptions _)
        => writer.WriteStringValue(version.ToString());
}
```
There is a cost associated with including dedicated converters for each BCL type, so we generally don't do it unless there is strong demand. By this logic I don't believe that `System.Version` meets the bar for inclusion.

I'm therefore going to close this issue, but we can always revisit this request at a later stage. Thank you for your contribution.

**Closed by eiriktsarpalis** 2021-03-31 13:44 UTC
Labels: area-System.Text.Json, untriaged

**Comment by eiriktsarpalis** [comment] 2021-03-31 16:36
Actually, it looks like we have already added a Version converter, it should be released in .NET 6:

https://github.com/dotnet/runtime/pull/41384.
