### ISSUE TITLE
System.Configuration.ConfigurationManager nuget  8.0.1 contains diffferent assembly versions.

### ISSUE THREAD

**Issue by mujdatdinc** [dotnet/runtime#109581] opened 2024-11-06 14:26 UTC
System.Configuration.ConfigurationManager nuget  8.0.1 package all Assembly versions are 8.0.0.0 (same as nuget 8.0.0 )except net462 assembly which is 8.0.0.1.
This  is causing  assembly resolution problems on some scenarios where netstandart2.0 libraries using System.Configuration.ConfigurationManager running on  net462  like unit tests can not locate the 8.0.0.0 version which  it is compiled. 

Assembly redirection is required as a workaround.

**Comment by steveharter** [comment] 2024-11-06 15:59
I see we enabled servicing in 8.0.0.1: https://github.com/dotnet/runtime/commit/8072b235c7742ac2178dee11cfb44ee8585304bd#diff-4c624ed07275e559b56977da61f85c1ca4197ffd40d23265b129119651dc90beR10-R11
```diff
+    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
+    <ServicingVersion>1</ServicingVersion>
```

PTAL @ViktorHofer @ericstj

**Comment by vcsjones** [comment] 2024-11-06 16:16
This looks like a duplicate of https://github.com/dotnet/runtime/issues/92486 except with a different package:

> This is expected and by design. We version the NETFramework assemblies so that they are guaranteed a unique version should someone install to the GAC. This is especially important in servicing so that applications can guarantee they receive a serviced version.

> We must not version the netstandard2.0 nor NET6/NET7 versions because this assembly also ships in the shared framework which is updated in place.

> Consuming a newer assembly version than what a binary was built with is completely normal. The same thing happens when updating packages. So long as the version increases across compatible relationships (newer assembly version, newer framework version, netstandard -> netstandard-compatible-framework) then the version increase is acceptable and compatible.

> When using NuGet package on .NETFramework you must configure your project to use bindingRedirects in order to allow for these newer versions. In most cases the build [will do this for you](https://learn.microsoft.com/en-us/dotnet/framework/configure-apps/how-to-enable-and-disable-automatic-binding-redirection).

**Comment by steveharter** [comment] 2024-11-06 16:49
Closing as duplicate (and by design)

**Closed by steveharter** 2024-11-06 16:49 UTC
Labels: area-System.Configuration, untriaged
