### ISSUE TITLE
crossgen2 fails to compile dlls on armel with versionbubble after compilation of ILCompiler.ReadyToRun.dll

### ISSUE THREAD

**Issue by gbalykov** [dotnet/runtime#55663] opened 2021-07-14 18:20 UTC
### Description

This bug is related to compilation of crossgen2 itself with `--inputbubble` option. It reproduces on tizen armel only, I was not able to reproduce it on ubuntu x64/arm64.

After compilation of `System.Private.CoreLib.dll` and `crossgen2/ILCompiler.ReadyToRun.dll` any dll fails to compile, for example error for `crossgen2/crossgen2.dll`:
```
Error: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at ILCompiler.CompilerTypeSystemContext.OpenPEFile(String filePath, MemoryMappedViewAccessor& mappedViewAccessor) in ILCompiler.ReadyToRun.dll:token 0x6000029+0x33
   at ILCompiler.CompilerTypeSystemContext.AddModule(String filePath, String expectedSimpleName, Boolean useForBinding, ModuleData oldModuleData) in ILCompiler.ReadyToRun.dll:token 0x600002a+0xa
   at ILCompiler.CompilerTypeSystemContext.GetOrAddModuleFromPath(String filePath, Boolean useForBinding) in ILCompiler.ReadyToRun.dll:token 0x6000028+0x4e
   at ILCompiler.Program.Run(String[] args) in crossgen2.dll:token 0x600015a+0x18c
   at ILCompiler.Program.Main(String[] args) in crossgen2.dll:token 0x6000162+0x5
```

crossgen2 compilation command:
```sh
./corerun ./crossgen2/crossgen2.dll -r:`pwd`/*.dll -r:`pwd`/crossgen2/*.dll -O --compilebubblegenerics --inputbubble -o:`pwd`/crossgen2/crossgen2.ni.dll `pwd`/crossgen2/crossgen2.dll
```

Without `--inputbubble` everything works fine. 

Can this happen because armel is not handled correctly somewhere in crossgen2?

cc @alpencolt @jkotas

**Comment by t-mustafin** [comment] 2021-07-19 18:17
Similar problem #48466.

**Comment by davidwrighton** [comment] 2021-07-19 23:00
This appears to be caused by some miscompilation of ILCompiler.ReadyToRun.dll. Unless you get lucky with the issue I noticed in note 1 below, you will need to debug this and understand what the failure is as I am not able to run or debug logic on a Tizen scenario. I've given a few pointers in note 2 below.

1. When compiling with crossgen2 and intending to target armel, explicitly specifying the armel architecture is ALWAYS required as there is no programmatic way to identify in .NET to detect that the architecture of the OS is armel. It is possible that this failure is caused by crossgen2 targetting the wrong OS/Arch and that `--targetarch armel` was not specified for compilation of System.Private.CoreLib.dll or ILCompiler.ReadyToRun.dll. 

Alternatively, you could contribute a change which updates the ILCompiler.Program.InitializeDefaultOptions function to detect armel.

2. `--inputbubble` is not supposed to have this sort of effect. However, its primary effect is to dramatically increase the amount of inlining across modules. This can cause the reporting stack traces to be very difficult to understand and exact failures to be hard to predict. A first step in diagnosing an apparent miscompilation would be to disable optimization on the OpenPEFile function using MethodImplOptions.NoOptimization, or to compile ILCompiler.ReadyToRun.dll without the `-O` switch. Another approach would be to use the r2rdump tool with the `--disasm` option, examine the generated output for OpenPEFile and determine what is happening at offset 0x32 in the OpenPEFile function and determine what the NullReferenceException is caused by.

**Comment by gbalykov** [comment] 2021-07-20 10:55
@davidwrighton thanks a lot for suggestions! Indeed, we forgot `--targetarch armel` option, but I was unlucky and it didn't help. We'll investigate according to your note 2.

**Comment by mangod9** [comment] 2021-07-28 15:18
Is this a requirement for .net 6?

**Comment by davidwrighton** [comment] 2021-07-28 18:25
@mangod9 Not really. I'll move this issue to 7.0.0, as its not a ship blocker for any work done for use in any supported scenarios. However, if @gbalykov is able to find a fix or find a repro which applies to a non-armel scenario we will likely be able to take it into the .NET 6 product, but we will not consider this bug as part of the .NET 6 release.

**Comment by gbalykov** [comment] 2021-08-01 10:22
Ok, thanks. We'll try to fix this before .net 6 is released

**Comment by gbalykov** [comment] 2021-08-12 11:43
@davidwrighton I can confirm that this reproduces on armhf ubuntu 18.04, commit 4d82932722b56924598708f991961a75e5a90b36. I've checked in armhf rootfs on arm64 ubuntu on rpi4.

Build rootfs:
```
z@dagon:~/Dev/runtime$ cat .tools/rootfs/arm/etc/os-release 
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

To build runtime:
```sh
ROOTFS_DIR=`pwd`/.tools/rootfs/arm ./build.sh --portablebuild false --cross --clang9 --arch arm --runtimeConfiguration Release --librariesConfiguration Release --subset clr+libs.native /p:EnableSourceLink=false
ROOTFS_DIR=`pwd`/.tools/rootfs/arm ./build.sh --cross --clang9 --arch arm --runtimeConfiguration Release --librariesConfiguration Release --subset libs.ref+libs.src+libs.pretest+libs.packages /p:EnableSourceLink=false
```

To pack artifacts:
```sh
mkdir overlay_arm
cp artifacts/bin/coreclr/Linux.arm.Release/IL/System.Private.CoreLib.dll overlay_arm/ -r
cp artifacts/bin/coreclr/Linux.arm.Release/{corerun,crossgen2,*.so,*.so.dbg} overlay_arm/ -r
cp artifacts/bin/native/net6.0-Linux-Release-arm/libSystem.*.so overlay_arm/
cp artifacts/bin/microsoft.netcore.app.runtime.linux-arm/Release/runtimes/linux-arm/lib/net6.0/*.dll overlay_arm
tar -zcvf overlay_arm.tar.gz overlay_arm
```

armhf rootfs setup on rpi4 with arm64 ubuntu:
```sh
z@z:~/Dev/armhf$ ls
mnt  ubuntu-18.04.5-preinstalled-server-armhf+raspi4.img
z@z:~/Dev/armhf$ fdisk -l ubuntu-18.04.5-preinstalled-server-armhf+raspi4.img | grep "Linux" | awk '{print $2 * 512}'
269484032
z@z:~/Dev/armhf$ sudo mount -o rw,loop,offset=269484032 -t auto `pwd`/ubuntu-18.04.5-preinstalled-server-armhf+raspi4.img `pwd`/mnt
z@z:~/Dev/armhf$ cat mnt/etc/os-release 
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
z@z:~/Dev/armhf$ export ROOTFS=`pwd`/mnt
z@z:~/Dev/armhf$ sudo mount -t proc /proc $ROOTFS/proc
z@z:~/Dev/armhf$ sudo mount -t sysfs /sys $ROOTFS/sys
z@z:~/Dev/armhf$ sudo mount -o bind /dev $ROOTFS/dev
z@z:~/Dev/armhf$ sudo mount -o bind /dev/pts $ROOTFS/dev/pts
z@z:~/Dev/armhf$ sudo chroot ./mnt/
```

Compilation with crossgen2 with bubble:
```sh
root@z:/home/overlay_arm# ./corerun ./crossgen2/crossgen2.dll --targetarch arm -r:`pwd`/*.dll -r:`pwd`/crossgen2/*.dll -O --compilebubblegenerics --inputbubble -o:`pwd`/System.Private.CoreLib.ni.dll `pwd`/System.Private.CoreLib.dll
Emitting R2R PE file: /home/overlay_arm/System.Private.CoreLib.ni.dll
root@z:/home/overlay_arm# mv System.Private.CoreLib.dll System.Private.CoreLib.dll.bak
root@z:/home/overlay_arm# mv System.Private.CoreLib.ni.dll System.Private.CoreLib.dll
root@z:/home/overlay_arm# ./corerun ./crossgen2/crossgen2.dll --targetarch arm -r:`pwd`/*.dll -r:`pwd`/crossgen2/*.dll -O --compilebubblegenerics --inputbubble -o:`pwd`/crossgen2/ILCompiler.ReadyToRun.ni.dll `pwd`/crossgen2/ILCompiler.ReadyToRun.dll
Emitting R2R PE file: /home/overlay_arm/crossgen2/ILCompiler.ReadyToRun.ni.dll
root@z:/home/overlay_arm# ./corerun ./crossgen2/crossgen2.dll --targetarch arm -r:`pwd`/*.dll -r:`pwd`/crossgen2/*.dll -O --compilebubblegenerics --inputbubble -o:`pwd`/crossgen2/crossgen2.dll `pwd`/crossgen2/crossgen2.dll
Error: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at ILCompiler.CompilerTypeSystemContext.OpenPEFile(String filePath, MemoryMappedViewAccessor& mappedViewAccessor)
   at ILCompiler.CompilerTypeSystemContext.AddModule(String filePath, String expectedSimpleName, Boolean useForBinding, ModuleData oldModuleData)
   at ILCompiler.CompilerTypeSystemContext.GetOrAddModuleFromPath(String filePath, Boolean useForBinding)
   at ILCompiler.Program.Run(String[] args)
   at ILCompiler.Program.Main(String[] args)
```

Same compilation of ILCompiler.ReadyToRun.dll without input bubble doesn't lead to errors.

**Comment by gbalykov** [comment] 2021-08-12 11:46
Follow-up question on this, why is `arm` architecture missing from `src/coreclr/tools/Common/JitInterface/ThunkGenerator/InstructionSetDesc.txt`?

**Comment by gbalykov** [comment] 2021-08-12 11:51
Some additional info:
- removal of -O option doesn't help, besides r2rdump shows same asm with/without it for OpenPEFile
addition of 
- `[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.NoOptimization)]` to OpenPEFile seems to help
- doesn't reproduce in debug mode of coreclr & crossgen2

**Comment by davidwrighton** [comment] 2021-08-12 18:38
@gbalykov arm is omitted from InstructionSetDesc as none of the CPU specific instruction sets have been implemented for ARM in the JIT (and as ARM is rapidly being replaced by ARM64, we are unlikely to invest in changing that).

**Comment by davidwrighton** [comment] 2021-08-12 18:53
Dunno, I'll take a look today, but I'm fairly busy right now, so it will take at least a few hours.

**Comment by davidwrighton** [comment] 2021-08-13 03:23
Sigh, this is a quirk of `--inputbubble` that I had forgotten. The layout of fields in a type is affected by whether or not a type is compiled with R2R or not. This effect is quite subtle and doesn't effect many types, but unfortunately, is not non-existent. `--inputbubble` makes the assumption that all files that the newly compiled binary might reference are also compiled with R2R so that it can perform complete field layout. The fix here is to compile every assembly via R2R and then place the crossgen'd images where they need to be, not depend on these various components being built in place. This is a design quirk of `--inputbubble` not a bug. (Although I'm tempted to suggest changing the type layout rules for .NET 7 so that this doesn't happen, but that's not going to happen now.)

Additionally, a very useful feature of crossgen2 that I used to help diagnose the issue, was compiling the binaries using the `--verify-type-and-field-layout` switch to crossgen2. That will generate checks for field layout structure that will pinpoint problematic layout issues instead of waiting for the inevitable random runtime crashes. In this case, it identified the `System.IO.MemoryMappedFiles.MemoryMappedViewAccessor._view` field as problematic, so if I happened to compile the `System.IO.MemoryMappedFiles.dll` file before compiling `ILCompiler.ReadyToRun.ni.dll` everything seems to have worked well.

I'll leave this issue open for a day in case this doesn't address your problem, but I think this should cover it.

**Comment by gbalykov** [comment] 2021-08-13 06:25
Thanks for your answer! Compilation of `System.IO.MemoryMappedFiles.dll` did indeed work. 

Is there a more detailed description of types, that are affected by this? Maybe there's a way to check that dll references such types prior to compilation? We need this in scenario when only part of system dlls are compiled in r2r. Without such check we are only left with compilation of all dlls with inputbubble or compilation of part of dlls without bubble (which leads to more compilations during app startup).

**Comment by davidwrighton** [comment] 2021-08-13 18:08
The issue is basically that if a type layout leaves some empty padding space at the end of the type, then under some circumstances, a derived type can and will fill that space in with more data. Which types this applies to is architecture dependent, and for generics the affect can happen for some instantiations and not for others.

One option is to use the `--inputbubbleref`, but as I said in #51555, I will not be investigating any bugs that you encounter while using that option.

However, all is not lost, as I said, one option is to make everything be a ready to run image, which is still safe, no actual methods need to be compiled. There isn't a switch for this behavior in crossgen2, but most of the effect can be achieved by adding `--singlemethodtypename System.Object --singlemethodname ToString` to the command line while compiling input bubble enabled and wanting an image without any R2R code. The effect of that will be to run generate an R2R binary without any actual code in it. The size growth as a result will be larger than ideal, but not the size growth of full R2R.

In addition, if the assembly doesn't actually expose any types, but instead is just a set of type forwarders, then you can skip running it through R2R, as it won't have any types where layout can be a problem. There are many of these facade assemblies in the product. As an example System.Runtime.dll is one.

Or of course, one could restrict the use of `--inputbubble` to a small set of core assemblies where all references are within the version bubble. And finally, I would encourage your team to verify that the performance improvement of `--inputbubble` is actually worth it for your scenarios.

**Comment by gbalykov** [comment] 2021-08-13 18:51
Thanks, we'll consider all these options and see what works best in our scenario.

**Comment by gbalykov** [comment] 2022-07-02 05:42
@davidwrighton does your recent change https://github.com/dotnet/runtime/pull/71271 fix this issue?

**Comment by davidwrighton** [comment] 2022-07-06 18:00
Not at all. The behavior described here is inherent to how `--inputbubble` works. My work in #71271 is designed to allow cross module inlining and such without any of the functionality risks of `--inputbubble`, but does come with other runtime and file size costs. Considering that there is no functionality issue here, I'm going to close this bug.

**Closed by davidwrighton** 2022-07-06 18:00 UTC
Labels: area-crossgen2-coreclr
