### ISSUE TITLE
Failing test - `HttpMetricsTest_Http11_Async_HttpMessageInvoker.RequestDuration_ConnectionClosedWhileReceivingHeaders_Recorded`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#93627] opened 2023-10-17 20:27 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=441439
Build error leg or test failing: System.Net.Http.Functional.Tests.HttpMetricsTest_Http11_Async_HttpMessageInvoker.RequestDuration_ConnectionClosedWhileReceivingHeaders_Recorded
Pull request: https://github.com/dotnet/runtime/pull/93618

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "In value:  String[] [\"System.Threading.Tasks.TaskCanceledException\", \"response_ended\"]",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=441439
**Error message validated:** `In value:  String[] ["System.Threading.Tasks.TaskCanceledException", "response_ended"]`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 10/17/2023 8:36:19 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by MihaZupan** [comment] 2023-10-19 11:11
Triage: The same issue was reported in #91721 (including sample message and stack trace).
Closing that as a duplicate of this issue given that the `build-analysis` template has been filled here.

**Comment by antonfirsov** [comment] 2024-01-04 15:30
Duplicate of #96407.

**Closed by antonfirsov** 2024-01-04 15:30 UTC
Labels: area-System.Net.Http, blocking-clean-ci, Known Build Error
