### ISSUE TITLE
With net6.0 preview 3, publish console app with RID(osx-x64) failed with error MSB4018.

### ISSUE THREAD

**Issue by dandanmu** [dotnet/runtime#49493] opened 2021-03-11 09:06 UTC
Repro steps:
1. Install SDK 6.0 preview 3 from master branch of https://github.com/dotnet/installer
2. mkdir hello
3. dotnet new console
4. dotnet publish -c Release -r osx-x64

Expected Result:
Publish with RID(osx-x64) should work fine.

Actual Result:
Publish with RID(osx-x64) failed with error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\Users\v-damu\hello1\hello1.csproj]
![image](https://user-images.githubusercontent.com/65638819/110762384-b4c7f380-828b-11eb-939a-a5533a44d0e3.png)

Note:
Publish with RID(win-x64, linux-x64) is working fine.

dotnet --info:
.NET SDK (reflecting any global.json):
Version: 6.0.100-preview.3.21160.18
Commit: 5a0f4f6800

Runtime Environment:
OS Name: Windows
OS Version: 10.0.19041
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\6.0.100-preview.3.21160.18\

Host (useful for support):
Version: 6.0.0-preview.3.21159.16
Commit: 3eddf4a06b

.NET SDKs installed:
6.0.100-preview.3.21160.18 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
Microsoft.AspNetCore.App 6.0.0-preview.3.21160.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.0-preview.3.21159.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.0-preview.3.21127.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
https://aka.ms/dotnet-download

**Comment by vitek-karas** [comment] 2021-03-12 11:42
@sdmaclea did we something weird with the apphost for macos? I can also repro this locally easily.

**Comment by sdmaclea** [comment] 2021-03-12 17:18
I don't know of anything that was actually committed.  Just my prototype change in review.

**Comment by sdmaclea** [comment] 2021-03-12 18:06
My last change in the `src\installer` tree was #47247 in January.  Looking through the change history there were several infra related changes which might have broken this. 

/cc @ViktorHofer @am11

**Comment by am11** [comment] 2021-03-12 20:21
If we comment out these two lines: https://github.com/dotnet/runtime/blob/997dc08f691ee0246990a21c73850a041b80b800/src/installer/managed/Microsoft.NET.HostModel/AppHost/MachOUtils.cs#L272-L273 the error goes away. Here the filestream is for apphost and validation is linkEditEnd: 132880 vs. fileEnd: 135168. Other properties of linkEdit are:

```json
{
   "cmd":25,
   "cmdsize":72,
   "fileoff":81920,
   "filesize":50960,
   "flags":0,
   "initprot":1,
   "nsects":0,
   "vmaddr":4295049216,
   "vmsize":65536
}
```

**Comment by am11** [comment] 2021-03-12 20:36
I've built hello app the same way as OP; on Windows targeting osx-x64 with dotnet6-p3. This restored image (file: `apphost`) is a valid macOS binary. I am not sure where the 2288 bytes difference is coming from which is violating our verification.

**Comment by sdmaclea** [comment] 2021-03-12 20:59
Maybe the signing of the apphost changed.  Perhaps it is now adhoc signed instead of unsigned?

Maybe an XCode update or an signing infra change.

/cc @mmitche

**Comment by vitek-karas** [comment] 2021-03-12 21:52
@VSadov

**Comment by am11** [comment] 2021-03-12 22:06
Ah, I was testing the wrong binary when copied to macOS, here is what happens when I run that app (built after commenting out aforementioned two lines):

```sh
$ ./hello
dyld: malformed mach-o image: symbol strings overrun __LINKEDIT
bort trap: 6           ./hello
Error: Process completed with exit code 134.
```

So at least our verification is legit.

**Comment by VSadov** [comment] 2021-03-12 23:19
Is this a regular apphost? (not the singlefile)
I am guessing this is related to signing. Otherwise tests would not pass in CI.

**Comment by am11** [comment] 2021-03-12 23:24
Yup, not the singlefile; it's self-contained executable based off regular apphost: `dotnet publish -c Release -r osx-x64`

**Comment by VSadov** [comment] 2021-03-13 00:26
Hmm. Works for me. Tried on an M1 and on old x64 machine. osx-x64 worked in both cases.

I have used very recent build - whatever was published for main in the last hour or so `dotnet-sdk-6.0.100-preview.3.21162.43-osx-x64` on x64. 
Perhaps there was a corrupted build?

**Comment by VSadov** [comment] 2021-03-13 00:27
Ah, I see the repro was built on Windows. I will try again.

**Comment by VSadov** [comment] 2021-03-13 01:36
Yes. It reproduces on Windows. 

Also I verified that apphost in `microsoft.netcore.app.host.osx-x64\6.0.0-preview.3.21162.1\runtimes\osx-x64\native` is ok. `codesign -dv` does not report any problems with it. 
In fact if a I copy it over the one included in the OSX SDK, it works fine.

My current working theory is that the code that strips the signature from the template has issues, but why only on Windows?

**Comment by am11** [comment] 2021-03-13 02:12
If we revert the changes made in this commit 872d9e47d1c3fe7e4ad262340a548977c0d46ce1, the error goes away. I think it has something to do with different memory map behavior between unix and windows.

**Comment by VSadov** [comment] 2021-03-13 02:17
@brianrob

**Comment by am11** [comment] 2021-03-13 04:38
Reported a possible bug https://github.com/dotnet/runtime/issues/49571.

@brianrob, e.g. following patch hot fixes this issue with netstandard2.0 which Microsoft.NET.HostModel targets:

<details>
  <summary>Diff</summary>

```diff
diff --git a/src/installer/managed/Microsoft.NET.HostModel/AppHost/BinaryUtils.cs b/src/installer/managed/Microsoft.NET.HostModel/AppHost/BinaryUtils.cs
index 0d733815e62..91ec3a0e9f3 100644
--- a/src/installer/managed/Microsoft.NET.HostModel/AppHost/BinaryUtils.cs
+++ b/src/installer/managed/Microsoft.NET.HostModel/AppHost/BinaryUtils.cs
@@ -174,7 +174,7 @@ public static void CopyFile(string sourcePath, string destinationPath)
             File.Copy(sourcePath, destinationPath, overwrite: true);
         }

-        internal static void WriteToStream(MemoryMappedViewAccessor sourceViewAccessor, FileStream fileStream)
+        internal static void WriteToStream(MemoryMappedViewAccessor sourceViewAccessor, FileStream fileStream, int sourceLength)
         {
             int pos = 0;
             int bufSize = 16384; //16K
@@ -182,7 +182,7 @@ internal static void WriteToStream(MemoryMappedViewAccessor sourceViewAccessor,
             byte[] buf = new byte[bufSize];
             do
             {
-                int bytesRequested = Math.Min((int)sourceViewAccessor.Capacity - pos, bufSize);
+                int bytesRequested = Math.Min((int)sourceLength - pos, bufSize);
                 if (bytesRequested <= 0)
                 {
                     break;
diff --git a/src/installer/managed/Microsoft.NET.HostModel/AppHost/HostWriter.cs b/src/installer/managed/Microsoft.NET.HostModel/AppHost/HostWriter.cs
index 8bc479d31ee..bc4bef97dc6 100644
--- a/src/installer/managed/Microsoft.NET.HostModel/AppHost/HostWriter.cs
+++ b/src/installer/managed/Microsoft.NET.HostModel/AppHost/HostWriter.cs
@@ -99,7 +99,7 @@ void UpdateResources()
                         // Save the transformed host.
                         using (FileStream fileStream = new FileStream(appHostDestinationFilePath, FileMode.Create))
                         {
-                            BinaryUtils.WriteToStream(memoryMappedViewAccessor, fileStream);
+                            BinaryUtils.WriteToStream(memoryMappedViewAccessor, fileStream, (int)new FileInfo(appHostSourceFilePath).Length);

                             // Remove the signature from MachO hosts.
                             if (!appHostIsPEImage)
```
</details>

**Comment by brianrob** [comment] 2021-03-16 22:12
@dandanmu, thanks for reporting this, and for the candidate fix.  I've posted #49493 to address this.

**Closed** 2021-03-17 00:24 UTC
Labels: area-HostModel, in pr, untriaged
