### ISSUE TITLE
TimeZoneInfo AdjustmentRules broken under Linux

### ISSUE THREAD

**Issue by jrydow** [dotnet/runtime#44475] opened 2020-11-10 18:56 UTC
### Description

* TimeZoneInfo.AdjustmentRules Don't work when run on Linux.
* It seems that Floating Date Rules don't work at all as expected.
* Conversion from the local tz database is mixed up, Start and End rules seem to be swapped.
* The actual rule seem to be wrong in the time of day when to switch to/from daylight saving time.

### Configuration
* .Net 3.1 core
* Ubuntu 18.04 LTS
* x64
* Do you know whether it is specific to that configuration? Yes works when run on Windows

### Regression?
Don't know

### Other information

Below are two test cases that work on when run on Windows, but fail when run on Linux
```
using System;
using System.Collections.ObjectModel;
using System.Linq;
using Xunit;
using static System.TimeZoneInfo;

namespace Example.TimeZoneUtil.Tests
{
    public class TimezoneFailsOnLinuxTests
    {
        // This is what is the tz database in Ubuntu 18.04 (zdump -v /usr/share/zoneinfo/America/Nassau)
        // /usr/share/zoneinfo/America/Nassau  Sun Mar  8 06:59:59 2020 UT = Sun Mar  8 01:59:59 2020 EST isdst=0 gmtoff=-18000
        // /usr/share/zoneinfo/America/Nassau  Sun Mar  8 07:00:00 2020 UT = Sun Mar  8 03:00:00 2020 EDT isdst=1 gmtoff=-14400
        // /usr/share/zoneinfo/America/Nassau  Sun Nov  1 05:59:59 2020 UT = Sun Nov  1 01:59:59 2020 EDT isdst=1 gmtoff=-14400
        // /usr/share/zoneinfo/America/Nassau  Sun Nov  1 06:00:00 2020 UT = Sun Nov  1 01:00:00 2020 EST isdst=0 gmtoff=-18000
        [Fact]
        public void TestRealWorldZone()
        {
            // From https://www.nist.gov/pml/time-and-frequency-division/popular-links/daylight-saving-time-dst
            // During 2020, daylight saving time is in effect from March 8 at 2 a.m. (local time) to November 1 at 2 a.m. (local time).
            // begins at 2:00 a.m.on the second Sunday of March(at 2 a.m.the local time time skips ahead to 3 a.m.so there is one less hour in the day)
            // ends at 2:00 a.m.on the first Sunday of November(at 2 a.m.the local time becomes 1 a.m.and that hour is repeated, so there is an extra hour in the day)

            ReadOnlyCollection<TimeZoneInfo> timeZones = TimeZoneInfo.GetSystemTimeZones();
            var est = timeZones.FirstOrDefault(a => a.DisplayName.Contains("(UTC-05:00) Eastern Time"));
            if (est == null)
            {
                // This is the linux name
                est = timeZones.FirstOrDefault(a => a.DisplayName.Contains("(UTC-05:00) Eastern Standard Time"));
            }
            TimeZoneInfo.AdjustmentRule[] adjustments = est.GetAdjustmentRules();

            // Look for the adjustment of 2020
            TimeZoneInfo.AdjustmentRule adjustment = null;
            foreach (TimeZoneInfo.AdjustmentRule a in adjustments)
            {
                // These dates have already passed
                if (a.DateEnd < DateTime.Parse("2020-01-01"))
                    continue;

                adjustment = a;
                break;
            }

            Assert.True(adjustment.DateStart.Year <= 2020);
            Assert.True(adjustment.DateEnd.Year >= 2020);
            Assert.Equal(3, adjustment.DaylightTransitionStart.Month); // This fails on linux, seems like start and end are mixed up.
            Assert.Equal(2, adjustment.DaylightTransitionStart.TimeOfDay.Hour); // This also fails on linux, TimeOfDay says 01:00:00
            if (adjustment.DaylightTransitionStart.IsFixedDateRule)
            {
                // This is where we end up running Linux
                Assert.Equal(8, adjustment.DaylightTransitionStart.Day);   // This fails on linux, seems like start and end are mixed up.
            }
            else
            {
                Assert.Equal(2, adjustment.DaylightTransitionStart.Week);
                Assert.Equal(0, (int)adjustment.DaylightTransitionStart.DayOfWeek);
            }


            Assert.Equal(11, adjustment.DaylightTransitionEnd.Month); // This fails on linux, seems like start and end are mixed up.
            Assert.Equal(2, adjustment.DaylightTransitionEnd.TimeOfDay.Hour); // Fails, TimeOfDay actually says 01:59:59, which is the last second in dst, not when the actual shift happens.
            if (adjustment.DaylightTransitionEnd.IsFixedDateRule)
            {
                // This is where we end up running Linux
                Assert.Equal(1, adjustment.DaylightTransitionEnd.Day);   // This fails on linux, seems like start and end are mixed up.
            }
            else
            {
                Assert.Equal(1, adjustment.DaylightTransitionEnd.Week);
                Assert.Equal(0, (int)adjustment.DaylightTransitionStart.DayOfWeek);
            }
        }

        [Fact]
        public void TestCustomTimeZone()
        {
            TransitionTime startTransition = TransitionTime
                .CreateFloatingDateRule(new DateTime(1, 1, 1, 4, 0, 0), 4, 1, DayOfWeek.Monday);
            TransitionTime endTransition = TransitionTime
                .CreateFloatingDateRule(new DateTime(1, 1, 1, 3, 0, 0), 11, 2, DayOfWeek.Saturday);

            AdjustmentRule adjustment;
            adjustment = AdjustmentRule.CreateAdjustmentRule(new DateTime(0001, 1, 1), DateTime.MaxValue.Date, new TimeSpan(1, 0, 0), startTransition, endTransition);
            AdjustmentRule[] adjustments = { adjustment };

            TimeSpan offset = new TimeSpan(-8, 0, 0);
            TimeZoneInfo tz = CreateCustomTimeZone("Northwest town", offset, "DisplayName", "StdName", "DstName", adjustments);

            TimeZoneInfo.AdjustmentRule[] adjustmentsRead = tz.GetAdjustmentRules();

            // Look for the adjustment of 2020
            TimeZoneInfo.AdjustmentRule adjustmentRead = adjustmentsRead[0];

            Assert.True(adjustmentRead.DateStart.Year <= 2020);
            Assert.True(adjustmentRead.DateEnd.Year >= 2020);

            // None of the tests below works on Linux, and even if they would be converted to
            // fixed rules, those are not correct. The below tests pass when run under windows.
            Assert.False(adjustmentRead.DaylightTransitionStart.IsFixedDateRule);
            Assert.Equal(4, adjustmentRead.DaylightTransitionStart.Month); // This should at least be correct!
            Assert.Equal(4, adjustmentRead.DaylightTransitionStart.TimeOfDay.Hour); // This should at least be correct!
            //Assert.Equal(1, adjustmentRead.DaylightTransitionStart.Day); // This is unclear what it means since it should not be a Fixed rule in the first place
            Assert.Equal(1, adjustmentRead.DaylightTransitionStart.Week);
            Assert.Equal(DayOfWeek.Monday, adjustmentRead.DaylightTransitionStart.DayOfWeek);

            Assert.False(adjustmentRead.DaylightTransitionEnd.IsFixedDateRule);
            Assert.Equal(11, adjustmentRead.DaylightTransitionEnd.Month); // This should at least be correct!
            Assert.Equal(3, adjustmentRead.DaylightTransitionEnd.TimeOfDay.Hour); // This should at least be correct!
            Assert.Equal(2, adjustmentRead.DaylightTransitionEnd.Week);
            Assert.Equal(DayOfWeek.Saturday, adjustmentRead.DaylightTransitionEnd.DayOfWeek);
        }
    }
}
```

**Comment by tarekgh** [comment] 2020-11-10 20:32
Thanks @jrydow for reporting it. This is a duplicate of https://github.com/dotnet/runtime/issues/20626 we'll close this one and we can follow up on the other issue.

**Closed by tarekgh** 2020-11-10 20:32 UTC
Labels: area-System.Globalization

**Comment by tarekgh** [comment] 2020-11-11 01:09
@jrydow by the way, what is your scenario that you want to use the adjustment rules for?

**Comment by jrydow** [comment] 2020-11-11 07:44
I need to supply daytime rules to iot devices.

**Comment by tarekgh** [comment] 2020-11-11 17:15
@jrydow 

> I need to supply daytime rules to iot devices.

Could elaborate more on that? what you are doing on iot devices with such rules? more info will help here.

**Comment by jrydow** [comment] 2020-11-12 11:38
@tarekgh 
We have IoT devices that are spread over the world. They are running tasks on schedule, locally on the device, and need to be able to use daylight savings and local time correctly. Since it is an embedded system is uses its own way of to store what timezone and how the dst rules for that. It is basically a maximum 64 byte string, somewhat resembling the Unix string that is used by tz. We planned to update the string over the air regularly, every year or so. The reason for having the schedule on board is that the device will then do its tasks even when there is no connection to the backend. The format is used by IAR, and I think others, for resource limited embedded systems.

The format is described here: https://velcdn.azureedge.net/-/media/com/api/klf200/technical%20specification%20for%20klf%20200%20api-ver3-18.pdf
 On page 20-21

**Comment by tarekgh** [comment] 2020-11-12 18:14
@jrydow thanks for the info. how many rules usually you send to the device? is it just current year rule? or you send multiple years rules?

**Comment by jrydow** [comment] 2020-11-13 15:27
@tarekgh 
Currently just one, since we plan to update regularly, so yes the current year rule.
