### ISSUE TITLE
SocketException (10054)  while  trying to post byte array to a HTTPS server in dotnet 6 with HTTPClient

### ISSUE THREAD

**Issue by desaiaditya93** [dotnet/runtime#99724] opened 2024-03-13 21:56 UTC
### Describe the bug
Trying to post a byte array to a server having digest authentication, im adding the calculated cnonce in headers and this code works fine for HTTP , but for HTTPS, I am getting SocketException . Here is the code for the same

```c#
var handler = new HttpClientHandler()
{
    Credentials = new NetworkCredential("admin", "private"),
    ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator,
    PreAuthenticate = false,
    SslProtocols = System.Security.Authentication.SslProtocols.Tls12,
    UseProxy = false,
    UseCookies = false,
 
};

ServicePointManager.SetTcpKeepAlive(true, 100, 200);

var httpClient = new HttpClient(handler);
   HttpContent contentss = new ByteArrayContent(array1);
   contentss.Headers.ContentType = new MediaTypeHeaderValue("application/octet-stream");
   clientss.DefaultRequestHeaders.Authorization = headers;


   var response1 = await httpClient .PostAsync("https://192.168.1.1/fwup_install", contentss);
```

### Exceptions (if any)
 System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
-->

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by wfurt** [comment] 2024-03-19 03:58
the exception is what it seems to be e.g. it is the server closing connection. And it is unlikely the root cause in HttpClient. Can you do packet capture, inspect server logs or provide repro e.g. at least URL you are trying to connect to? It is also possible server does not like something about the request e.g. we have seen cases when missing headers may lead to issues like this.

Note that for .NET Core `ServicePointManager.SetTcpKeepAlive` makes no difference as `HttpClient` does not use `ServicePointManager` any more.

**Comment by desaiaditya93** [comment] 2024-03-20 07:31
issue was from the server side, HTTPClient is working fine

**Closed** 2024-03-20 07:30 UTC
Labels: area-System.Net.Http, untriaged, needs-author-action

**Comment by wfurt** [comment] 2024-03-20 16:35
good to know. thanks for confirming @desaiaditya93
