### ISSUE TITLE
[release/6.0] CI failure in JIT.Methodical.eh tests run in Browser wasm Release AllSubsets_Mono_RuntimeTests

### ISSUE THREAD

**Issue by buyaa-n** [dotnet/runtime#81388] opened 2023-01-30 22:34 UTC
JIT.Methodical.eh tests fails on `Browser wasm Release AllSubsets_Mono_RuntimeTests` build with error: `System.IO.IOException: The system cannot open the device or file specified. : 'NuGet-Migrations'`
Build: https://github.com/dotnet/runtime/pull/81291/checks?check_run_id=10940259682
Log: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-81291-merge-d3fecd5e4ead400f9f/JIT.Methodical.eh/1/console.e6ca2831.log?helixlogtype=result
```log
+ dotnet /datadisks/disk1/work/C59B0A98/p/xunit/xunit.console.dll JIT/Methodical/JIT.Methodical.XUnitWrapper.dll -parallel collections -nocolor -noshadow -xml testResults.xml -trait TestGroup=JIT.Methodical.eh
Microsoft.DotNet.XUnitConsoleRunner v2.5.0 (64-bit .NET 6.0.13)
  Discovering: JIT.Methodical.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  JIT.Methodical.XUnitWrapper (found 142 of 695 test cases)
  Starting:    JIT.Methodical.XUnitWrapper (parallel test collections = on, max threads = 2)
    JIT/Methodical/eh/nested/cascadedcatchret/cascadedcatch_d/cascadedcatch_d.sh [FAIL]
      System.IO.IOException: The system cannot open the device or file specified. : 'NuGet-Migrations'
         at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
         at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
         at NuGet.Common.Migrations.MigrationRunner.Run()
         at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
         at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean isDotnetBeingInvokedFromNativeInstaller, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider, Dictionary`2 performanceMeasurements)
         at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
         at Microsoft.DotNet.Cli.Program.Main(String[] args)
      
      Return code:      1
      Raw output file:      /datadisks/disk1/work/C59B0A98/w/ACF10954/uploads/Reports/JIT.Methodical/eh/nested/cascadedcatchret/cascadedcatch_d/cascadedcatch_d.output.txt
      Raw output:
      BEGIN EXECUTION
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/datadisks/disk1/work/C59B0A98/p
      > /datadisks/disk1/work/C59B0A98/w/ACF10954/e/JIT/Methodical/eh/nested/cascadedcatchret/cascadedcatch_d/cascadedcatch_d.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at JIT_Methodical._eh_nested_cascadedcatchret_cascadedcatch_d_cascadedcatch_d_._eh_nested_cascadedcatchret_cascadedcatch_d_cascadedcatch_d_sh()
      Output:
        System.IO.IOException: The system cannot open the device or file specified. : 'NuGet-Migrations'
           at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
           at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
           at NuGet.Common.Migrations.MigrationRunner.Run()
           at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
           at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean isDotnetBeingInvokedFromNativeInstaller, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider, Dictionary`2 performanceMeasurements)
           at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
           at Microsoft.DotNet.Cli.Program.Main(String[] args)
        
        Return code:      1
        Raw output file:      /datadisks/disk1/work/C59B0A98/w/ACF10954/uploads/Reports/JIT.Methodical/eh/nested/cascadedcatchret/cascadedcatch_d/cascadedcatch_d.output.txt
        Raw output:
        BEGIN EXECUTION
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/datadisks/disk1/work/C59B0A98/p
        > /datadisks/disk1/work/C59B0A98/w/ACF10954/e/JIT/Methodical/eh/nested/cascadedcatchret/cascadedcatch_d/cascadedcatch_d.sh
  Finished:    JIT.Methodical.XUnitWrapper
=== TEST EXECUTION SUMMARY ===
   JIT.Methodical.XUnitWrapper  Total: 142, Errors: 0, Failed: 1, Skipped: 0, Time: 130.987s
```

```json
{
  "ErrorMessage": "JIT_Methodical._eh_nested_cascadedcatchret_cascadedcatch_d_cascadedcatch_d_._eh_nested_cascadedcatchret_cascadedcatch_d_cascadedcatch_d_sh()",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by buyaa-n** [comment] 2023-01-31 17:34
Same failure in https://helix.dot.net/api/2019-06-17/jobs/c27e71d0-7250-4526-9fb9-6be6796e7497/workitems/baseservices.threading/console
```log
baseservices/threading/interlocked/and_or/and_or_int64/and_or_int64.sh [FAIL]
      System.IO.IOException: The system cannot open the device or file specified. : 'NuGet-Migrations'
         at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
         at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
         at NuGet.Common.Migrations.MigrationRunner.Run()
         at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
         at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean isDotnetBeingInvokedFromNativeInstaller, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider, Dictionary`2 performanceMeasurements)
         at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
         at Microsoft.DotNet.Cli.Program.Main(String[] args)
      
      Return code:      1
      Raw output file:      /datadisks/disk1/work/A32308D4/w/B0D90978/uploads/Reports/baseservices.threading/interlocked/and_or/and_or_int64/and_or_int64.output.txt
      Raw output:
      BEGIN EXECUTION
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/datadisks/disk1/work/A32308D4/p
      > /datadisks/disk1/work/A32308D4/w/B0D90978/e/baseservices/threading/interlocked/and_or/and_or_int64/and_or_int64.sh
      Expected: True
      Actual:   False
      Stack Trace:
           at baseservices_threading._interlocked_and_or_and_or_int64_and_or_int64_._interlocked_and_or_and_or_int64_and_or_int64_sh()
      Output:
        System.IO.IOException: The system cannot open the device or file specified. : 'NuGet-Migrations'
           at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
           at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
           at NuGet.Common.Migrations.MigrationRunner.Run()
           at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
           at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean isDotnetBeingInvokedFromNativeInstaller, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider, Dictionary`2 performanceMeasurements)
           at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
           at Microsoft.DotNet.Cli.Program.Main(String[] args)
        
        Return code:      1
        Raw output file:      /datadisks/disk1/work/A32308D4/w/B0D90978/uploads/Reports/baseservices.threading/interlocked/and_or/and_or_int64/and_or_int64.output.txt
        Raw output:
        BEGIN EXECUTION
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/datadisks/disk1/work/A32308D4/p
        > /datadisks/disk1/work/A32308D4/w/B0D90978/e/baseservices/threading/interlocked/and_or/and_or_int64/and_or_int64.sh
  Finished:    baseservices.threading.XUnitWrapper
=== TEST EXECUTION SUMMARY ===
   baseservices.threading.XUnitWrapper  Total: 3, Errors: 0, Failed: 1, Skipped: 0, Time: 1.957s
```

**Comment by radical** [comment] 2023-02-28 17:20
This is a dupe of https://github.com/dotnet/runtime/issues/80619 .

**Closed by radical** 2023-02-28 17:20 UTC
Labels: arch-wasm, untriaged, area-Codegen-JIT-mono, test-failure, Known Build Error
