### ISSUE TITLE
AOT Crash on iOS Release build, net8p7

### ISSUE THREAD

**Issue by Redth** [dotnet/runtime#90751] opened 2023-08-17 16:03 UTC
### Description

Catching a crash at runtime with a .NET MAUI iOS app on .NET 8 Preview 7.

Native output / trace:
https://gist.github.com/Redth/60b7ec5051d447c3e9321e6a5497e371

Using full interpreter mode does seem to avoid the crash.

### Reproduction Steps

Not sure about extracting a simple repro yet, but happy to run more builds/diagnostics on request.

### Expected behavior

No crashing

### Actual behavior

Crashes

### Regression?

This worked at least with .NET 7 and I believe earlier .NET 8 previews as well.

### Configuration

- .NET 8 Preview 7
- iOS 17
- ARM64

**Comment by Redth** [comment] 2023-08-17 16:21
@steveisok FYI

**Comment by SamMonoRT** [comment] 2023-08-18 12:58
cc @ivanpovazan @kotlarmilos

**Comment by ivanpovazan** [comment] 2023-08-30 13:21
After an offline discussion, the reported issue seems to happen only in the `AOT+interpreter` configuration.
However, it has been confirmed that the issue is not reproducible in this configuration anymore with `.NET8 rc1 release`.


Additionally, it was reported that for the iOS app in question, the interpreter had to be enabled (via: `UseInterpreter=true`) in the first place, because the app was crashing in the default - AOT only configuration with:
```
System.TypeInitializationException: TypeInitialization_Type, LiteDB.BsonExpression
2023-08-23 10:01:38.995 PoolMath[47619:3598848]  ---> System.ExecutionEngineException: Attempting to JIT compile method '(wrapper dynamic-method) LiteDB.BsonValue object:Thunk1ret_BsonValue_IEnumerable`1_BsonDocument_BsonValue_Collation_BsonDocument (System.Func`2<object[], object>,System.Collections.Generic.IEnumerable`1<LiteDB.BsonDocument>,LiteDB.BsonDocument,LiteDB.BsonValue,LiteDB.Collation,LiteDB.BsonDocument)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.
```
As this failure seems to be present in .NET7 as well, I have a created separate tracking issue: https://github.com/dotnet/runtime/issues/91332 for it, where we will try to address it in .NET9 timeframe.


I would suggest that we close this issue if what was originally reported is not reproducible anymore. 
Do you agree @Redth ?

**Comment by ivanpovazan** [comment] 2023-10-10 12:52
@Redth is this issue still reproducible?

**Comment by ivanpovazan** [comment] 2023-11-23 15:05
Based on my last comments I will close this issue as it does not seem to be reproducible anymore.

@Redth please feel free to reopen it if needed.

**Closed by ivanpovazan** 2023-11-23 15:05 UTC
Labels: area-Codegen-AOT-mono, os-ios
