### ISSUE TITLE
Regex.Match is different between .NET 8.0.4 and .NET Framework 4.8

### ISSUE THREAD

**Issue by VB-Man** [dotnet/runtime#101223] opened 2024-04-18 03:01 UTC
### Description

Regex.Match is different between .NET 8.0.4 and .NET Framework 4.8

### Reproduction Steps

        Dim regex As New Regex("AAB|AAC", RegexOptions.RightToLeft)
        Dim m As Match
        m = regex.Match("AABAACD", 6)

        If m.Success = True Then
            '.NET Framework 4.8
            '.NET Framework 4.7.2
        Else
            '.NET 7.0.0
            '.NET 8.0.0
            '.NET 8.0.4
        End If

        MsgBox(m.Success)

### Expected behavior

I think the operation of .NET Framework is correct.
I want the processing results of .NET Core to be the same as .NET Framework.

### Actual behavior

There is no particular description.

**Comment by huoyaoyuan** [comment] 2024-04-18 03:28
The match successes for 6.0.29, and fails for 8.0.4. Looks like a regression in 7.0.

**Comment by stephentoub** [comment] 2024-04-23 03:06
Thanks for the good repro. Fix is in https://github.com/dotnet/runtime/pull/101408.

**Closed** 2024-04-23 16:06 UTC
Labels: bug, area-System.Text.RegularExpressions
