### ISSUE TITLE
System.Text.Json Source Generator with TreatWarningsAsErrors Fails

### ISSUE THREAD

**Issue by romfir** [dotnet/runtime#64499] opened 2022-01-29 22:07 UTC
### Description

When project is set to treat warnings as errors and XML documentation generation is enabled the build using System.Text.Json source generator fails.

### Reproduction Steps

csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

</Project>
```

and when I add  a public class derived from JsonSerializerContext the build fails

```csharp
using System.Text.Json;
using System.Text.Json.Serialization;
namespace ConsoleApp7;

/// <summary>
/// </summary>
public class Program
{
    static void Main(string[] args)
    {
        // Display the number of command line arguments.
        Console.WriteLine(args.Length);

        Person? person = new() { FirstName = "Jane", LastName = "Doe" };
        byte[] utf8Json = JsonSerializer.SerializeToUtf8Bytes(person, MyJsonContext2.Default.Person);
        person = JsonSerializer.Deserialize(utf8Json, MyJsonContext2.Default.Person);
    }
}

/// <summary>
/// </summary>
public class Person
{
    /// <summary>
    /// </summary>
    public string? FirstName { get; set; }
    /// <summary>
    /// </summary>
    public string? LastName { get; set; }
}

/// <summary>
/// 
/// </summary>
[JsonSerializable(typeof(Person))]
public partial class MyJsonContext2 : JsonSerializerContext
{
}
```

![image](https://user-images.githubusercontent.com/33402460/151679017-b4055816-cd86-4daf-94b4-16db7a19ce3f.png)

### Expected behavior

The build should pass, one idea is to add ```#pragma warning disable 1591``` and possibly ```// <auto-generated />``` to generated files

### Actual behavior

The build failes

**Comment by eiriktsarpalis** [comment] 2022-02-01 16:53
Related to #61734 and #62076.

**Comment by layomia** [comment] 2022-02-03 17:40
Dupe of https://github.com/dotnet/runtime/issues/61379.

**Closed by layomia** 2022-02-03 17:40 UTC
Labels: area-System.Text.Json, untriaged
