### ISSUE TITLE
Many test timeouts -- external server outage

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#57134] opened 2021-08-10 15:03 UTC
Looks like correlated problem for multiple tests at the same time on the same machines -- likely external problem.

Methods monitored:
```kusto
  or Method == 'ConnectAsync_DnsEndPoint_Success'
  or Method == 'SendAsync_CorrectVersionSelected_ExternalServer'
  or Method == 'GetStreamAsync_ReadToEnd_Success'
  or Method == 'GetAsync_CredentialIsCredentialCacheUriRedirect_StatusCodeOK'
  or Method == 'DefaultHeaders_SetCredentials_ClearedOnRedirect'
  or Method == 'UseCallback_ValidCertificate_ExpectedValuesDuringCallback'
  or Method == 'AuthenticatedProxiedRequest_GetAsyncWithCreds_Success'
  or Method == 'GetAsync_UseResponseHeadersReadAndCallLoadIntoBuffer_Success'
  or Method == 'SendReceive_PartialMessageBeforeCompleteMessageArrives_Success'
  or Method == 'GetAsync_MaxLimited_ConcurrentCallsStillSucceed'
  or Method == 'PostLargeContentUsingContentLengthSemantics_Success'
  or Method == 'PostUsingChunkedEncoding_Success'
  or Method == 'CloseOutputAsync_ExpectedStates'
  or Method == 'CloseAsync_CloseOutputAsync_Throws'
  or Method == 'CloseAsync_CloseDescriptionHasUnicode_Success'
  or Method == 'ReceiveAsync_MultipleOutstandingReceiveOperations_Throws'
  or Method == 'PostUsingNoSpecifiedSemantics_UsesChunkedSemantics'
  or Method == 'PostSyncBlockingContentUsingChunkedEncoding_Success'
  or Method == 'PostRepeatedFlushContentUsingChunkedEncoding_Success'
  or Method == 'PostRewindableStreamContentMultipleTimes_StreamContentFullySent'
  or Method == 'SendReceive_PartialMessageDueToSmallReceiveBuffer_Success'
  or Method == 'SendReceive_Concurrent_Success'
  or Method == 'SendAsync_SendCloseMessageType_ThrowsArgumentExceptionWithMessage'
  or Method == 'EchoTextMessage_Success'
  or Method == 'EchoBinaryMessage_Success'
  or Method == 'ConnectAsync_PassNoSubProtocol_ServerRequires_ThrowsWebSocketException'
  or Method == 'ConnectAsync_AddCustomHeaders_Success'
  or Method == 'ConnectAndCloseAsync_UseProxyServer_ExpectedClosedState'
  or Method == 'ReceiveAsync_AfterCancellationDoReceiveAsync_ThrowsWebSocketException'
  or Method == 'PostUsingContentLengthSemantics_Success'
  or Method == 'PostAsync_EmptyContent_ContentTypeHeaderNotSent'
  or Method == 'GetAsync_UseResponseHeadersReadAndCopyToMemoryStream_Success'
  or Method == 'PostEmptyContentUsingChunkedEncoding_Success'
  or Method == 'GetAsync_ServerNeedsBasicAuthAndSetDefaultCredentials_StatusCodeUnauthorized'
  or Method == 'GetAsync_RequestHeadersAddCustomHeaders_HeaderAndValueSent'
  or Method == 'ConnectAsync_PassMultipleSubProtocols_ServerRequires_ConnectionUsesAgreedSubProtocol'
  or Method == 'AuthenticatedProxyTunnelRequest_PostAsyncWithCreds_Success'
  or Method == 'SendAsync_SendRequestUsingMethodToEchoServerWithNoContent_MethodCorrectlySent'
  or Method == 'UseCallback_BadCertificate_ExpectedPolicyErrors'
  or Method == 'CloseAsync_CloseDescriptionIsNull_Success'
  or Method == 'CloseAsync_CloseDescriptionIsMaxLength_Success'
  or Method == 'SendAsync_SendCloseMessageType_ThrowsArgumentExceptionWithMessage'
  or Method == 'CloseAsync_DuringConcurrentReceiveAsync_ExpectedStates'
  or Method == 'GetAsync_ResponseHeadersRead_ReadFromEachIterativelyDoesntDeadlock'
  or Method == 'GetAsync_AllowAutoRedirectFalse_RedirectFromHttpToHttp_StatusCodeRedirect'
  or Method == 'SendAsync_SendRequestUsingMethodToEchoServerWithContent_Success'
  or Method == 'GetAsync_AllowAutoRedirectTrue_RedirectFromHttpToHttp_StatusCodeOK'
  or Method == 'GetAsync_AllowAutoRedirectTrue_RedirectFromHttpToHttps_StatusCodeOK'
  or Method == 'SendReceive_VaryingLengthBuffers_Success'
  or Method == 'ClientWebSocket_Abort_CloseOutputAsync'
  or Method == 'Connect_DnsEndPoint_Success'
  or Method == 'SendAsync_SendZeroLengthPayloadAsEndOfMessage_Success'
  or Method == 'ReadAsStreamAsync_Cancel_TaskIsCanceled'
  or Method == 'PostNoContentUsingContentLengthSemantics_Success'
  or Method == 'PostAsync_ExpectContinue_Success'
  or Method == 'Abort_CloseAndAbort_Success'
  or Method == 'Abort_SendAndAbort_Success'
  or Method == 'CloseOutputAsync_Cancel_Success'
  or Method == 'CloseOutputAsync_ClientInitiated_CanReceive_CanClose'
  or Method == 'CloseOutputAsync_CloseDescriptionIsNull_Success'
  or Method == 'GetAsync_AllowAutoRedirectTrue_RedirectFromHttpsToHttp_StatusCodeRedirect'
  or Method == 'GetAsync_AllowAutoRedirectTrue_RedirectToUriWithParams_RequestMsgUriSet'
  or Method == 'GetAsync_AllowAutoRedirectTrue_RedirectWithRelativeLocation'
  or Method == 'GetAsync_SetAutomaticDecompression_HeadersRemoved'
  or Method == 'PostAsync_CallMethod_StreamContent'
  or Method == 'PostEmptyContentUsingConflictingSemantics_Success'
  or Method == 'PostEmptyContentUsingContentLengthSemantics_Success'
  or Method == 'PostNonRewindableContentUsingAuth_NoPreAuthenticate_ThrowsHttpRequestException'
  or Method == 'PostNonRewindableContentUsingAuth_PreAuthenticate_Success'
  or Method == 'PostRewindableContentUsingAuth_NoPreAuthenticate_Success'
  or Method == 'PostUsingUsingConflictingSemantics_UsesChunkedSemantics'
  or Method == 'ReceiveAsync_ReceiveThenCancel_ThrowsOperationCanceledException'
  or Method == 'SendAsync_MultipleOutstandingSendOperations_Throws'
  or Method == 'SendAsync_RequestVersion20_ResponseVersion20IfHttp2Supported'
  or Method == 'SendAsync_SendRequestUsingNoBodyMethodToEchoServerWithContent_NoBodySent'
  or Method == 'SslStream_AllowRenegotiation_True_Succeeds'
  or Method == 'UploadData_Success'
  or Method == 'UploadString_Success'
  or Method == 'UploadValues_Success'
  or Method == 'UseCallback_NotSecureConnection_CallbackNotCalled'
  or Method == 'UseDefaultCredentials_SetGetResponse_ExpectSuccess'
  or Method == 'UseDefaultCredentials_SetToFalseAndServerNeedsAuth_StatusCodeUnauthorized'
  or Method == 'ZeroByteReceive_CompletesWhenDataAvailable'
  or Method == 'UploadFile_Success'
  or Method == 'SendAsync_Cancel_Success'
  or Method == 'CloseAsync_Cancel_Success'
  or Method == 'EventSource_SocketAcceptFailure_LogsAcceptFailed'
  or Method == 'BeginReceiveMessageFromV4BoundToAnyV6_Success'
  or Method == 'Socket_StaticConnectAsync_ConnectionRefused'
  or Method == 'GetAsync_EmptyResponseHeader_Success'
```

Failures 7/1-9/6 (incl. PRs):

Day and Time range | Notes
-- | --
7/1-7/31 | Nothing over 5 failures
8/1 (0:22) ... 11:51:08-12:12:49 | 5x failures (5x main=6.0)
8/2 (5 mins) ... 14:36:19-14:41:47 | 18x failures - PR #56723<br/>**2 test runs hang** (1x Debian.10.Amd64.Open, 1x Centos.8.Amd64.Open)
8/7 (0:52) ... 11:51:06-12:42:59 | 68x failures (68x main=6.0)<br/>**6 test runs hang** (2x Debian.10.Amd64.Open, 1x Ubuntu.1910.Amd64.Open, 1x Centos.8.Amd64.Open, 1x Fedora.34.Amd64.Open, 1x Windows.Server.Core.1909.Amd64.Open - WinHttpHandler)
8/8 (0:44) ... 11:49:55-12:34:16 | 81x failures (79x main=6.0, 2x 6.0-preview7)<br/>**4 test runs hang** (2x Centos.8.Amd64.Open, 1x Ubuntu.1910.Amd64.Open, 1x Fedora.34.Amd64.Open)
8/12 (0:31) ... 11:51:35-12:22:48 | 6x failures (6x 6.0-preview7)
8/15 (5 min) ... 12:36:25-12:41:50 | **4 test runs hang** (2x Alpine.312.Amd64.Open, Fedora.34.Amd64.Open, Debian.10.Amd64.Open)
8/16 (TBD) ... 10:37:46 | **1 test run hang** (Debian.10.Amd64.Open)
8/18 (7 min) ... 13:04:23-13:11:14 | **5 test runs hang** (4x 6.0-rc1, 1x 6.0) (Fedora.34.Amd64.Open, Debian.10.Amd64.Open, Alpine.312.Amd64.Open, Mariner.1.0.Amd64.Open, Centos.8.Amd64.Open)
8/22 (6 min) ... 12:37:28-12:43:56 | **5 test runs hang** (5x 6.0) (Centos.8.Amd64.Open, Fedora.34.Amd64.Open, Ubuntu.1910.Amd64.Open, Debian.10.Amd64.Open, Mariner.1.0.Amd64.Open)
8/24 (4 min) ... 10:31:46-10:35:31 | PR #58003: **3 test runs hang** (3x main=7.0) (1x Alpine.312.Amd64.Open, 1x Fedora.34.Amd64.Open, 1x Centos.8.Amd64.Open)
8/24 (0:32) ... 11:50:40-12:22:28 | 19x failures (7x main=7.0, 6x 6.0, 6x 6.0-rc1)
8/24 (12 min) ... 12:35:08-12:47:10 | **15 test runs hang** (8x 6.0, 7x 6.0-rc1)
8/26 (0:47) ... 12:03:42-12:50:28 | 33x failures (20x 6.0-rc1, 13x 6.0)
8/27 (0:33) ... 13:34:056-14:07:51 | **1 test run hang** (1x main=7.0) (1x WinHttpHandler)
8/29 (1:02) ... 11:58:58-13:01:18 | 57x failures (35x 6.0, 22x 6.0-rc1)<br/>**17 test runs hang** (11x 6.0, 6x 6.0-rc1) (2x WinHttpHandler)
8/31 (0:54) ... 11:46:51-12:51:16 | 162x failures (130x 6.0, 31x 6.0-rc1, 1x main=7.0)
9/4 (0:38) ... 11:56:27-12:34:07 | 48x failures (37x 6.0, 11x 6.0-rc1)<br/>**6 test runs hang** (4x 6.0, 2x 6.0-rc1)
9/5 (0:45) ... 11:47:05-12:31:54 | 29x failures (17x 6.0, 12x 6.0-rc1)<br/>**4 test runs hang** (2x 6.0, 2x 6.0-rc1)
9/6 (0:52) ... 11:52:55-12:45:37 | 49x failures (33x main=7.0, 10x 6.0, 6x 6.0-rc1)<br/>**6 test runs hang** (6x main=7.0)

## Original report - only 1 test ConnectAsync_DnsEndPoint_Success

Test: System.Net.Sockets.Tests.TcpClientTest.ConnectAsync_DnsEndPoint_Success.ConnectAsync_DnsEndPoint_Success

Failure:
```
System.Net.Sockets.SocketException : Connection timed out

   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1370
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1286
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(ValueTask task) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/TCPClient.cs:line 312
   at System.Net.Sockets.Tests.TcpClientTest.ConnectAsync_DnsEndPoint_Success(Int32 mode) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TcpClientTest.cs:line 178
--- End of stack trace from previous location ---
```

**Comment by karelz** [comment] 2021-08-10 15:04
Looks like recent regression - @antonfirsov any thoughts what might have happened?

**Comment by antonfirsov** [comment] 2021-08-10 16:38
What *might* be worrying is that the synchronous variant `Connect_DnsEndPoint_Success` doesn't show any failures.

The MacOS failures are around since 2021-06-11. Two PR-s around that time: #53479 #53479

**Comment by karelz** [comment] 2021-08-10 16:46
@antonfirsov there are 5-ish more tests that started timing out at the same time. I couldn't file the issues yet due to GH acting up ...
Overall this seems like very worrying Linux regression around 8/2 ... perhaps even a bit earlier

**Comment by ManickaP** [comment] 2021-08-10 19:42
Triage: we should investigate what happened, whether this really is a recent regression, which we should fix.

**Comment by ManickaP** [comment] 2021-08-10 21:02
BTW, I already punt the other issues to future, if there hasn't been any change in sockets code in that time frame, this was probably external server fluke.
Other issues: #57135 #57053

**Comment by karelz** [comment] 2021-08-13 10:52
Looks like correlated problem for multiple tests at the same time on the same machines -- likely external problem.

Methods monitored:
```
  or Method == 'ConnectAsync_DnsEndPoint_Success'
  or Method == 'SendAsync_CorrectVersionSelected_ExternalServer'
  or Method == 'GetStreamAsync_ReadToEnd_Success'
  or Method == 'GetAsync_CredentialIsCredentialCacheUriRedirect_StatusCodeOK'
  or Method == 'DefaultHeaders_SetCredentials_ClearedOnRedirect'
  or Method == 'UseCallback_ValidCertificate_ExpectedValuesDuringCallback'
  or Method == 'AuthenticatedProxiedRequest_GetAsyncWithCreds_Success'
  or Method == 'GetAsync_UseResponseHeadersReadAndCallLoadIntoBuffer_Success'
  or Method == 'SendReceive_PartialMessageBeforeCompleteMessageArrives_Success'
```

Failures 8/2-8/13 (incl. PRs):

Day and Time range | Notes
-- | --
8/2 (5 mins) ... 14:36:19-14:41:47 | 8x failure - PR #56723<br/>(7x Alpine.312.Amd64.Open, 1x Centos.8.Amd64.Open)
8/7 (15 mins) ... 12:27:59-12:42:59 | 21x failure - official run<br/>(14x Alpine.312.Amd64.Open, 2x Debian.10.Amd64.Open, 3x Ubuntu.1910.Amd64.Open, 1x Centos.8.Amd64.Open, 1x Fedora.34.Amd64.Open)
8/8 (10 mins) ... 12:24:24-12:34:16 | 34x failure - official run<br/>(17x Alpine.312.Amd64.Open, 9x Debian.10.Amd64.Open, 7x Ubuntu.1910.Amd64.Open, 1x Centos.8.Amd64.Open)

**Comment by karelz** [comment] 2021-08-13 10:56
@antonfirsov can you please check that all the tests listed above are Outerloop / external server? (are they same external server?)
If they are all external server, I would close this issue. We will keep monitoring CI as usual ...

**Comment by karelz** [comment] 2021-08-13 13:28
Once of the many timeouts happened on PlatformHandler on 8/7 -- this is really external problem, so closing for now.
If it happens too often in future we may try to figure out some detection of the external outage.

**Comment by antonfirsov** [comment] 2021-08-13 14:01
Sorry for not paying much attention previously, it took some time to get to this.

It looks like all tests (including socket and websocket tests) were reaching out to `corefx-net-http2.azurewebsites.net`, so it was probably outage of that site, or some other infra issue resolving/reaching it's endpoints.

**Comment by pavelsavara** [comment] 2021-09-02 15:45
Or we could self host the echo service on the same machine which is running the test, as we do for WASM.

**Comment by karelz** [comment] 2021-09-02 17:48
@pavelsavara that is a solution we are considering, assuming we know the root cause -- which is what we should check on first IMO (see https://github.com/dotnet/runtime/issues/57134#issuecomment-906878156)

**Comment by wfurt** [comment] 2021-09-02 20:15
Timing on loopback is not quite the same so there is _some_ value in getting to external servers. This also partially serves as interop test. But obviously we pay some price as well.

**Comment by pavelsavara** [comment] 2021-09-03 08:41
Agreed. Another benefit of Azure hosted service is that it is running on long term unchanging runtime.

**Comment by VincentBu** [comment] 2021-09-14 01:43
Failed again in:[ runtime-libraries-coreclr outerloop 20210913.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1358546&view=ms.vss-test-web.build-test-results-tab&runId=39705438&resultId=103602&paneView=debug)

Failed test:
```
net7.0-Linux-Release-x64-CoreCLR_release-(Ubuntu.1910.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-19.10-helix-amd64-cfcfd50-20191030180623

- System.Net.WebSockets.Client.Tests.ArraySegmentSendReceiveTest.ReceiveAsync_MultipleOutstandingReceiveOperations_Throws(server: ws://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)
- System.Net.WebSockets.Client.Tests.ArraySegmentSendReceiveTest.SendReceive_PartialMessageBeforeCompleteMessageArrives_Success(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)
- System.Net.WebSockets.Client.Tests.ConnectTest.ConnectAsync_AddCustomHeaders_Success(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocketHeaders.ashx)
- System.Net.WebSockets.Client.Tests.MemorySendReceiveTest.SendAsync_SendCloseMessageType_ThrowsArgumentExceptionWithMessage(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)

net7.0-Linux-Release-x64-CoreCLR_release-(Fedora.34.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-34-helix-20210728124700-4f64125

- System.Net.WebSockets.Client.Tests.CancelTest.CloseAsync_Cancel_Success(server: ws://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)
- System.Net.WebSockets.Client.Tests.MemorySendReceiveTest.SendReceive_Concurrent_Success(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)
- System.Net.WebSockets.Client.Tests.CloseTest.CloseAsync_CloseOutputAsync_Throws(server: ws://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)
- System.Net.WebSockets.Client.Tests.ArraySegmentSendReceiveTest.ZeroByteReceive_CompletesWhenDataAvailable(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)

net7.0-Linux-Release-x64-CoreCLR_release-(Centos.8.Amd64.Open)Ubuntu.1604.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:centos-8-helix-20201229003624-c1bf759

- System.Net.WebSockets.Client.Tests.ArraySegmentSendReceiveTest.ReceiveAsync_MultipleOutstandingReceiveOperations_Throws(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)
- System.Net.WebSockets.Client.Tests.CancelTest.ReceiveAsync_ReceiveThenCancel_ThrowsOperationCanceledException(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)
- System.Net.WebSockets.Client.Tests.ArraySegmentSendReceiveTest.SendReceive_PartialMessageBeforeCompleteMessageArrives_Success(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)
- System.Net.WebSockets.Client.Tests.ConnectTest.EchoBinaryMessage_Success(server: ws://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)
- System.Net.WebSockets.Client.Tests.AbortTest.Abort_ReceiveAndAbort_Success(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)
- System.Net.WebSockets.Client.Tests.ArraySegmentSendReceiveTest.ZeroByteReceive_CompletesWhenDataAvailable(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)
- System.Net.WebSockets.Client.Tests.CloseTest.CloseAsync_CloseOutputAsync_Throws(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)
```
**Error message:**
```
System.Threading.Tasks.TaskCanceledException : A task was canceled.


Stack trace
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) in /_/src/libraries/Common/src/System/Threading/Tasks/TaskCompletionSourceWithCancellation.cs:line 23
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 548
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs:line 988
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs:line 30
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options) in /_/src/libraries/System.Net.WebSockets.Client/src/System/Net/WebSockets/WebSocketHandle.Managed.cs:line 143
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken) in /_/src/libraries/System.Net.WebSockets.Client/src/System/Net/WebSockets/ClientWebSocket.cs:line 104
   at System.Net.WebSockets.Client.Tests.WebSocketHelper.<>c__DisplayClass4_0.<<GetConnectedWebSocket>b__0>d.MoveNext() in /_/src/libraries/System.Net.WebSockets.Client/tests/WebSocketHelper.cs:line 98
--- End of stack trace from previous location ---
   at System.Net.WebSockets.Client.Tests.WebSocketHelper.Retry[T](ITestOutputHelper output, Func`1 func)
   at System.Net.WebSockets.Client.Tests.SendReceiveTest.ReceiveAsync_MultipleOutstandingReceiveOperations_Throws(Uri server) in /_/src/libraries/System.Net.WebSockets.Client/tests/SendReceiveTest.cs:line 222
--- End of stack trace from previous location ---
```

**Comment by deeprobin** [comment] 2022-03-27 16:47
Can we close this or is this still relevant?

**Comment by wfurt** [comment] 2022-05-19 00:13
Let's close it. It is super old. We should open new issue if we see something similar. It feels it would be beneficial to have more specific issues as the reasons may be different.

**Closed by wfurt** 2022-05-19 00:13 UTC
Labels: area-System.Net.Sockets, test-run-core
