### ISSUE TITLE
WinformsControlsTest cannot be run under debugger in Visual Studio

### ISSUE THREAD

**Issue by WPMGPRoSToTeMa** [dotnet/runtime#64568] opened 2022-01-31 18:09 UTC
* .NET Core Version: 
7.0.0-beta.22078.2

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**
WinformsControlsTest cannot be run under debugger using F5 in Visual Studio, the following error is shown:
`A fatal error has occurred and debugging needs to be terminated. For more details, please see the Microsoft Help and Support web site. HRESULT=0x80070057. ErrorCode=0x0.`
![Fatal error when WinformsControlsTest runs under debugger in VS](https://user-images.githubusercontent.com/5282741/151824760-df1cf5f4-8966-44b2-a1a1-b70e99102d6b.png)

It was found that this problem is caused by ~dotnet/winforms#6569~ dotnet/winforms#6573.

WinformsControlsTest still can be run without debugger attached using Ctrl+F5. Debugging also doesn't work if attach the debugger later - breakpoints cannot be hit and there are no assemblies in Modules window.

**Expected behavior:**
It should be possible to run WinformsControlsTest with debugger attached in Visual Studio.

**Minimal repro:**
1. Open the solution using `start-vs`.
2. Choose WinformsControlsTest as the current project on the toolbar.
3. Click Run or press F5.

**Comment by WPMGPRoSToTeMa** [comment] 2022-01-31 22:35
@RussKie thanks. Sorry, I was doing that without a VS restart and stopped at a good commit.

**Comment by dreddy-work** [comment] 2022-02-01 18:37
Debugging tests are blocked here.

**Comment by tommcdon** [comment] 2022-02-01 23:00
Thanks for the bug report - we have found the root cause and are working on a fix: https://github.com/dotnet/runtime/pull/64523

**Comment by tommcdon** [comment] 2022-02-02 00:37
#64523 is merged, so this should be fixed on the next build

**Comment by RussKie** [comment] 2022-02-02 00:39
Awesome!

**Comment by tommcdon** [comment] 2022-02-04 16:28
Closing via https://github.com/dotnet/runtime/pull/64523
It looks like the fix has been merged into winforms on https://github.com/dotnet/winforms/commit/ff8a062d552d86dec868e5e884435823499eef4d
Please let us know if there are any issues

**Closed by tommcdon** 2022-02-04 16:28 UTC
Labels: blocking, area-Diagnostics-coreclr
