### ISSUE TITLE
Test failure: Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.Bind_T

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#107442] opened 2024-09-06 04:19 UTC
**Failed in:** [runtime-coreclr libraries-jitstress-random 20240904.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=798256&view=ms.vss-test-web.build-test-results-tab&runId=20571720&resultId=102725&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-x86-jitstress_random_2-Windows.10.Amd64.Open
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.Bind_T
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.UnsupportedTypes
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.ValueTypesAreInvalidAsBindInputs
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.GetValue_TypeOf_Key
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.BindConfigurationWithConfigureActions
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.Configure_T_name_BinderOptions
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.GetValue_T_Key
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.InvalidRootMethodInputTypes
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.SucceedWhenGivenConflictingTypeNames
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.MinimalGenerationIfNoBindableMembers
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.Bind_Key_Instance
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.Configure_T
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.DefaultConstructorParameters
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.GetValue_TypeOf_Key_DefaultValue
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.Get_TypeOf_BinderOptions
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.Primitives
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.SucceedWhenGivenMinimumRequiredReferences
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.Configure_T_name
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.Configure_T_BinderOptions
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.Get_PrimitivesOnly
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.GetValue
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.Get
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.Bind
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.CannotDetermineTypeInfo
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.WithBadMisconfiguredInput_GeneratorWontFail
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.MissingILogger
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.NeedlessLogLevelInMessage
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.NoILoggerField
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.InvalidMethodBody
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.NeedlessQualifierInMessage
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.NestedTypeOK
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.MultipleILoggerFields
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.NotPartial
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorEmitterTests.TestEmitter
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.SyntaxListWithManyItems
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.MissingLogLevel
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.InvalidRefKindsOut
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.SourceErrors
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.PrimaryConstructorOnOtherPartialDeclarationOK
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.WithNullMessage_GeneratorWontFail
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.NeedlessLoggerInMessage
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.MalformedFormatString
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.FileScopedNamespaceOK
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.FieldOnOtherPartialDeclarationOK
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.MissingArgument
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.PrimaryConstructorLoggerShadowedByBaseClass
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.InvalidMethodBody
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.MultipleTypeDefinitions
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.MissingILogger
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorEmitterTests.TestBaseline_TestWithNestedClassWithGenericTypesWithAttributes_Success
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorEmitterTests.TestBaseline_TestWithNestedClass_Success
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.MultipleTypeDefinitions
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.MultipleILoggerFields
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.NeedlessQualifierInMessage
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.MissingLogLevel
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.SourceErrors
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.InvalidMethodExpressionBody
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.MissingLoggerMessageAttributeType
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.MissingILogger
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.Valid_AdditionalAttributes
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.NotPartial
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.NeedlessExceptionInMessage
    - Microsoft.Gen.OptionsValidation.Unit.Test.EmitterTests.ShouldNotProduceErrorWhenDataTypeAttributesAreUsed
    - Microsoft.Gen.OptionsValidation.Unit.Test.EmitterTests.ShouldSkipAtrributeWhenAttributeSymbolIsNotBasedOnValidationAttribute
    - Microsoft.Gen.OptionsValidation.Unit.Test.EmitterTests.IgnoredStaticMembers
    - Microsoft.Gen.OptionsValidation.Unit.Test.EmitterTests.ShouldNotProduceErrorWhenPropertiesAreUsedAsAttributeArgument
net9.0-windows-Release-x86-jitstress_random_1-Windows.10.Amd64.Open
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorEmitterTests.TestBaseline_TestWithDefaultValues_Success
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorEmitterTests.TestBaseline_TestWithNestedClassWithGenericTypesWithAttributes_Success
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorEmitterTests.TestBaseline_TestWithNestedClass_Success
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.MultipleTypeDefinitions
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.MultipleILoggerFields
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.NeedlessQualifierInMessage
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.MissingLogLevel
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.SourceErrors
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.InvalidMethodExpressionBody
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.MissingLoggerMessageAttributeType
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.MissingILogger
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.Valid_AdditionalAttributes
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.NotPartial
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.NeedlessExceptionInMessage
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.UnsupportedTypes
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.ValueTypesAreInvalidAsBindInputs
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.GetValue_TypeOf_Key
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.BindConfigurationWithConfigureActions
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.Configure_T_name_BinderOptions
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.GetValue_T_Key
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.InvalidRootMethodInputTypes
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.SucceedWhenGivenConflictingTypeNames
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.MinimalGenerationIfNoBindableMembers
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.Bind_Key_Instance
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.Configure_T
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.DefaultConstructorParameters
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.GetValue_TypeOf_Key_DefaultValue
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.Get_TypeOf_BinderOptions
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.Primitives
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.SucceedWhenGivenMinimumRequiredReferences
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.Configure_T_name
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.Configure_T_BinderOptions
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.Get_PrimitivesOnly
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.GetValue
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.Get
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.Bind
    - Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.CannotDetermineTypeInfo
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.LogLevelDoublySet_AndInMessageTemplate_ProducesDiagnostic
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.WithBadMisconfiguredInput_GeneratorWontFail
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.MissingILogger
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.NeedlessLogLevelInMessage
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.NoILoggerField
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.InvalidMethodBody
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.NeedlessQualifierInMessage
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.NestedTypeOK
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.MultipleILoggerFields
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.NotPartial
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorEmitterTests.TestEmitter
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.SyntaxListWithManyItems
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.MissingLogLevel
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.InvalidRefKindsOut
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.SourceErrors
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.PrimaryConstructorOnOtherPartialDeclarationOK
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.WithNullMessage_GeneratorWontFail
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.NeedlessLoggerInMessage
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.MalformedFormatString
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.FileScopedNamespaceOK
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.FieldOnOtherPartialDeclarationOK
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.MissingArgument
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.PrimaryConstructorLoggerShadowedByBaseClass
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.InvalidMethodBody
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.MultipleTypeDefinitions
    - Microsoft.Extensions.Logging.Generators.Tests.LoggerMessageGeneratorParserTests.MissingILogger
    - Microsoft.Gen.OptionsValidation.Unit.Test.EmitterTests.ShouldNotProduceErrorWhenDataTypeAttributesAreUsed
    - Microsoft.Gen.OptionsValidation.Unit.Test.EmitterTests.ShouldSkipAtrributeWhenAttributeSymbolIsNotBasedOnValidationAttribute
    - Microsoft.Gen.OptionsValidation.Unit.Test.EmitterTests.IgnoredStaticMembers
    - Microsoft.Gen.OptionsValidation.Unit.Test.EmitterTests.ShouldNotProduceErrorWhenPropertiesAreUsedAsAttributeArgument
```

**Error message:**
```
 System.OutOfMemoryException : Insufficient memory to continue the execution of the program.
```

**Stack trace:**
```
   at System.Reflection.Internal.StreamMemoryBlockProvider.ReadMemoryBlockNoLock(Stream stream, Int64 start, Int32 size) in /_/src/libraries/System.Reflection.Metadata/src/System/Reflection/Internal/MemoryBlocks/StreamMemoryBlockProvider.cs:line 71
   at System.Reflection.PortableExecutable.PEReader..ctor(Stream peStream, PEStreamOptions options, Int32 size) in /_/src/libraries/System.Reflection.Metadata/src/System/Reflection/PortableExecutable/PEReader.cs:line 190
   at Microsoft.CodeAnalysis.ModuleMetadata.CreateFromStream(Stream peStream, PEStreamOptions options)
   at Microsoft.CodeAnalysis.MetadataReference.CreateFromFile(Stream peStream, String path, MetadataReferenceProperties properties, DocumentationProvider documentation)
   at Microsoft.CodeAnalysis.MetadataReference.CreateFromFile(String path, MetadataReferenceProperties properties, DocumentationProvider documentation)
   at SourceGenerators.Tests.RoslynTestUtils.CreateTestProject(AdhocWorkspace workspace, IEnumerable`1 references, Boolean includeBaseReferences, LanguageVersion langVersion) in /_/src/libraries/Common/tests/SourceGenerators/RoslynTestUtils.cs:line 51
   at Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.ConfigBindingGenTestDriver.UpdateCompilationWithSource(String source) in /_/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/SourceGenerationTests/ConfigBindingGenTestDriver.cs:line 85
   at Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.ConfigBindingGenTestDriver.RunGeneratorAndUpdateCompilation(String source) in /_/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/SourceGenerationTests/ConfigBindingGenTestDriver.cs:line 57
   at Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.RunGeneratorAndUpdateCompilation(String source, LanguageVersion langVersion, IEnumerable`1 assemblyReferences) in /_/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/SourceGenerationTests/GeneratorTests.Helpers.cs:line 186
   at Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.VerifyAgainstBaselineUsingFile(String filename, String testSourceCode, ExtensionClassType extType, ExpectedDiagnostics expectedDiags) in /_/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/SourceGenerationTests/GeneratorTests.Helpers.cs:line 147
   at Microsoft.Extensions.SourceGeneration.Configuration.Binder.Tests.ConfigurationBindingGeneratorTests.Bind_T() in /_/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/SourceGenerationTests/GeneratorTests.Baselines.Options.cs:line 168
--- End of stack trace from previous location ---
```

**Comment by tarekgh** [comment] 2024-09-06 16:47
Duplicate of https://github.com/dotnet/runtime/issues/107381

**Closed by tarekgh** 2024-09-06 16:47 UTC
Labels: arch-x86, os-windows, JitStress, untriaged, blocking-clean-ci-optional, area-Extensions-Logging
