### ISSUE TITLE
The HostBuilder holds on to Autofac's root IServiceProvider which cannot be disposed

### ISSUE THREAD

**Issue by Tragetaschen** [dotnet/runtime#36060] opened 2020-02-05 14:44 UTC
### Describe the bug
This is a follow up on https://github.com/autofac/Autofac.Extensions.DependencyInjection/issues/68

The `HostBuilder` creates the initial `IServiceProvider _appServices` for the host:
https://github.com/dotnet/extensions/blob/v3.1.1/src/Hosting/Hosting/src/HostBuilder.cs#L233
For the Autofac integration, this service provider holds a reference to the built Container and certain features of Autofac expect proper disposal of this Container, for example
- instances handed over to Autofac with `builder.RegisterInstance([IDisposable])` live in the container until used by other components
- All active child lifetime scopes are disposed, which is relevant for the `IConfiguration` infrastructure

### To Reproduce
https://github.com/Tragetaschen/autofac-does-not-dispose

There is a `MyDisposable` instance registered with Autofac that is not disposed when the program exists gracefully.

### Expected behavior

My expectation is that I can properly dispose the resources held by `HostBuilder`, but currently there isn't an interface for that. I have been able to restore Autofac's documented behavior by pulling out the private `_appServices` field using reflection and calling Dispose on that.

### Additional context
.NET Core 3.1.1

**Comment by eerhardt** [comment] 2020-08-31 16:30
@davidfowl and I investigated this issue a bit and here is what we learned:

1. When `HostBuilder` creates a `Host`, it must first an `IServiceProvider` that contains the configured services (one of which is the `Host` itself).
2. Once it has an `IServiceProvider`, it then calls `serviceProvider.GetRequiredService<IHost>()` in order to materialize the `Host`.
3. Nothing about `HostBuilder` is `IDisposable`. It just builds up the Configuration, ServiceProvider, and Host (which are all `IDisposable` themselves). It expects the resulting `Host` to get `Run`, which will `Dispose()` the `Host`. Disposing the `Host` will dispose the `IServiceProvider`, which will dispose all the services in the `IServiceProvider`.
4. The way the `Host` gets its `IServiceProvider` is through DI, i.e. the `Host`'s ctor takes an `IServiceProvider`, which the `HostBuilder`'s `IServiceProvider` is expected to fill in. This is the `IServiceProvider` which will get disposed when the `Host` is done running.

The issue is that the `IServiceProvider` which first gets created by the `HostBuilder` is not the same instance as the `IServiceProvider` that gets passed into the `Host`'s ctor. Instead, the instance created by `HostBuilder` is considered a "root" `IServiceProvider` to the one that gets passed into the `Host`'s ctor. And disposing this "child" `IServiceProvider` doesn't dispose the "root" `IServiceProvider`.

My assumption is that `HostBuilder` and `Host` had an unwritten assumption that the same `ISerivceProvider` instance that was created during `HostBuilder` would be used to fill out the `Host`'s `IServiceProvider` ctor arg. This doesn't appear to be the case for `Autofac`.

To fix this in `Microsoft.Extensions.Hosting`, one approach could be to no longer use DependencyInjection to create the `Host`, but instead call it's `ctor` directly passing in the `IServiceProvider` that was created during the `HostBuilder.Build()` method.

Since this behavior exists in 3.1, and is not a regression in 5.0, moving to 6.0 as this doesn't meet the 5.0 bar at this time.

**Comment by Tragetaschen** [comment] 2020-08-31 17:58
I second that analysis—it matches the conclusion I came to.

For those requiring disposal of the "root" `IServiceProvider` within `IHostBuilder` (which in turn disposes all the others as well), here is a "fix" as posted in the Autofac sibling issue https://github.com/autofac/Autofac.Extensions.DependencyInjection/issues/68

```C#
#nullable enable

// after IHost.Run[Async]() has returned:
await hostBuilder.Fixup_AsIAsyncDisposable().DisposeAsync();

// somewhere accessible
public static IAsyncDisposable Fixup_AsIAsyncDisposable(this IHostBuilder hostBuilder)
{
    var type = hostBuilder.GetType();
    var field = type.GetField("_appServices", BindingFlags.Instance | BindingFlags.NonPublic)!;
    var appServices = field.GetValue(hostBuilder)!;
    return (IAsyncDisposable)appServices;
}
```

which accesses [the private field](https://github.com/dotnet/runtime/blob/v5.0.0-preview.8.20407.11/src/libraries/Microsoft.Extensions.Hosting/src/HostBuilder.cs#L30) holding the `IServiceProvider`. This code "works" from 3.0 to 5.0 Preview8, but is obviously brittle.

**Closed** 2020-12-04 13:04 UTC
Labels: area-Extensions-Hosting, bug
