### ISSUE TITLE
Need to run non-English text through UTF8Encoding for PGO scenarios

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#57698] opened 2021-08-18 22:36 UTC
Per https://github.com/dotnet/runtime/issues/52313, there are regressions in `UTF8Encoding` in .NET 6 when processing non-English text. The root cause may be that we don't include a non-English text corpus in our runs which feed the PGO data generator, which could cause the JIT to reorder blocks in a manner suboptimal for non-English scenarios.

We should include non-English text during these runs to help seed the PGO data generator.

**Comment by jeffschwMSFT** [comment] 2021-08-19 14:33
cc @agocke

**Comment by Lxiamail** [comment] 2021-08-19 16:28
I can look into this. @jeffschwMSFT @GrabYourPitchforks, is this needed for .NET6 coming up RC release?

**Comment by jeffschwMSFT** [comment] 2021-08-19 16:30
@Lxiamail I would like to understand and then we can decide if this is an blocking issue for .NET 6.

**Comment by AndyAyersMS** [comment] 2021-08-19 22:49
Suggest we update the PGO collection process for main and keep an eye on the perf impact there (takes a few days to know for sure). If we're happy with the results, we can make the case to back port this to .NET 6 and/or try and surgically update the MIBC we use there somehow.

**Comment by GrabYourPitchforks** [comment] 2021-08-19 23:06
@Lxiamail We're still within ~10% of the net5 perf. I personally don't have a strong opinion here. Unless shiproom decides that it's blocking, my \[weakly held\] preference is not to hold up RC1 for this, but instead to address it in RC2. If the PGO update for RC1 is low-risk then, sure, take it. :)

**Comment by AndyAyersMS** [comment] 2022-06-16 22:20
@mangod9 any plans for your folks to work on this, or should we transfer this to another team?

**Comment by mangod9** [comment] 2022-06-16 23:06
this hasnt been on our radar. Looks like the issue is about enable non EN scenario within the apps?

**Comment by AndyAyersMS** [comment] 2022-06-17 01:03
Yes, we need to get some coverage over these currently "cold" paths.

**Comment by mangod9** [comment] 2022-07-27 16:09
Hi @sblom, should we move this to the perf-infra area path?

**Comment by mangod9** [comment] 2022-08-03 18:39
should this be moved to 8, or is the expectation to add the new scenario in the next week?

**Comment by AndyAyersMS** [comment] 2022-08-03 18:57
I really think we should try this for 7. It has been almost a year. 

@EgorBo is willing to do the work.

**Comment by EgorBo** [comment] 2022-08-03 22:25
Filed a PR there

**Comment by mangod9** [comment] 2022-08-15 18:48
@EgorBo if the PR is in a separate repo we should probably track the issue in that repo, since this is still marked as 7.

**Comment by EgorBo** [comment] 2022-08-15 18:59
@mangod9 that PR was already merged and we're just waiting for PGO data to propagate to dotnet/runtime via maestro bot

**Comment by mangod9** [comment] 2022-08-23 17:12
I see an update recently for this: https://github.com/dotnet/runtime/commit/8027c80a36ae73f2c729c6950c695a418304ecf3. Assume that would include the latest data?

**Closed** 2022-08-23 19:50 UTC
Labels: tenet-performance, area-VM-coreclr, runtime-coreclr
