### ISSUE TITLE
SourceGen build errors for [JsonIgnore]'d RegularExpressions.GroupCollection 

### ISSUE THREAD

**Issue by andrewdbond** [dotnet/runtime#82996] opened 2023-03-05 13:36 UTC
### Description

Using System.Text.Json source generation on a class that contains a System.Text.RegularExpressions.MatchCollection or System.Text.RegularExpressions.GroupCollection field or property produces build errors, even when the [JsonIgnore] attribute and private access modifiers are applied.

### Reproduction Steps

1. Run `dotnet new console`
2. Use the following code in Program.cs:

```C#
using System.Text.Json.Serialization;

Console.WriteLine("Hello, World!");

public class SerializedClass
{
	[JsonIgnore]
	private System.Text.RegularExpressions.MatchCollection foo;
}

[JsonSourceGenerationOptions]
[JsonSerializable(typeof(SerializedClass))]
internal partial class SourceGenerationContext : JsonSerializerContext
{
}
```

3. Run `dotnet build`

### Expected behavior

Build is successful.

### Actual behavior

> projectFolder\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\SourceGenerationContext.ReadOnlySpanChar.g.cs(10,129): error CS0306: The type 'ReadOnlySpan<char>' may not be used as a type argument [projectFolder\project.csproj]
> projectFolder\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\SourceGenerationContext.ReadOnlySpanChar.g.cs(19,128): error CS0306: The type 'ReadOnlySpan<char>' may not be used as a type argument [projectFolder\project.csproj]
> projectFolder\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\SourceGenerationContext.ReadOnlySpanChar.g.cs(14,127): error CS0306: The type 'ReadOnlySpan<char>' may not be used as a type argument [projectFolder\project.csproj]
> 
> Build FAILED.

### Configuration

* .NET 7
* Windows 11, version 22H2
* Architecture: x64

**Comment by eiriktsarpalis** [comment] 2023-03-06 15:29
Duplicate of #76919.

**Closed by eiriktsarpalis** 2023-03-06 15:29 UTC
Labels: area-System.Text.Json, untriaged
