### ISSUE TITLE
MissingMethodException after changing method signature on hot reload

### ISSUE THREAD

**Issue by isadorasophia** [dotnet/runtime#87032] opened 2023-06-01 23:04 UTC
### Description

When trying to rename methods with hot reload on .NET 7, I consistently get a `MissingMethodException` when changing the methods signatures.

### Reproduction Steps

1. Debug the following app with .NET 7:
```csharp
static void Main(string[] args)
{
    Debugger.Break();
    Foo(23);
}

static int Foo(int something)
{
    Console.WriteLine(something);
    return 0;
}
```
2. F5 and break.
3. Modify Foo with:
```csharp
static int Foo(int something, bool aValue = false)
{
    Console.WriteLine(something);
    return 0;
}
```
4. Successfully apply changes and F5

### Expected behavior

Successfully execute the modified `Foo` method.

### Actual behavior

**MissingMethodException** gets thrown:

![image](https://github.com/dotnet/runtime/assets/7958854/766ece36-1202-498c-afce-bc77cd731659)

**Comment by isadorasophia** [comment] 2023-06-01 23:06
Similar to [#65442](https://github.com/dotnet/roslyn/issues/65442) (on Roslyn)

**Comment by mikelle-rogers** [comment] 2023-06-02 00:57
I then tried reproducing this with .NET 7 in Visual Studio and checked the box next to "Do not use top-level statements" and the issue reproduced.

**Comment by AaronRobinsonMSFT** [comment] 2023-06-02 01:08
@isadorasophia I've not debugged this, but this might be an issue with the default value in the signature. What if you update both the callsite and the method?

@tmat Are default values supported in EnC in general?

**Comment by tmat** [comment] 2023-06-02 04:45
@davidwengier The reason for MethodMissingException is that Main is not recompiled because it does not have any changes, so it calls the old version of Foo, which now throws because it has been "deleted". 

This behavior is currently expected. Issue https://github.com/dotnet/roslyn/issues/59264 tracks improving this by emitting a call to the newer version of Foo into the body of its old version instead of MethodMissingException throw.

**Comment by tmat** [comment] 2023-06-02 04:46
Closing this issue as dup of https://github.com/dotnet/roslyn/issues/65442.

**Closed by tmat** 2023-06-02 04:46 UTC
Labels: area-Diagnostics-coreclr
