### ISSUE TITLE
System.Text.Json doesn't serialize tuples correctly

### ISSUE THREAD

**Issue by TDroogers** [dotnet/runtime#68264] opened 2022-04-20 09:44 UTC
### Describe the bug

System.Text.Json serializes tuples as `{}`

### Expected Behavior

Tuples being serialized and deserialized correctly

### Steps To Reproduce

```
Console.WriteLine(JsonSerializer.Serialize(("el0", "el1"))); // output: {}
```

EDIT (@krwq): simplified repro to just essentials

**Comment by javiercn** [comment] 2022-04-20 13:11
@TDroogers I've transferred this issue to the runtime repo so that they can give you a definite answer here.

**Comment by krwq** [comment] 2022-06-07 11:45
@TDroogers any chance you could share a repro which is self contained (define/share classes being serialized in the sample rather than using some external classes)

**Comment by krwq** [comment] 2022-06-07 11:53
@TDroogers I went ahead and modified issue description to simplify it to the core of the issue

**Comment by krwq** [comment] 2022-06-07 11:55
Setting milestone as 7.0.0 to consider fixing in this release or providing workable workaround although we cannot guarantee this will get fixed in this release.

**Comment by krwq** [comment] 2022-06-07 13:02
Just found out this is by design since tuples don't have any public properties. The way you can do this is:

```csharp
var o = new JsonSerializerOptions { IncludeFields = true };
Console.WriteLine(JsonSerializer.Serialize(("el0", "el1", "fff"), o));
```

**Closed by krwq** 2022-06-07 13:02 UTC
Labels: bug, area-System.Text.Json

**Comment by krwq** [comment] 2022-06-07 13:10
I've created https://github.com/dotnet/runtime/issues/70352 to track improvements in this area for vNext

**Comment by TDroogers** [comment] 2022-06-07 14:19
Thanks
