### ISSUE TITLE
Feature Request : Eliminate unpredictable stacktraces when the same Exception object is being concurrently re-thrown

### ISSUE THREAD

**Issue by dmitriyse** [dotnet/runtime#32009] opened 2020-02-10 03:00 UTC
## Problem
There is a common enough case where the same task is awaited by multiple threads.
In a case where task completed with fault, the awaiters reuse the same ```Exception``` object.

This orders of things produces hidden problem - Stacktrace race condition.
(tested on **.Net Core 3.1**)
### Repro code:
```CSharp
namespace System.Threading
{
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using Xunit;
    using Xunit.Abstractions;

    public class ConcurrentExceptionReThrowTests
    {
        private readonly ITestOutputHelper _outputHelper;

        public ConcurrentExceptionReThrowTests(ITestOutputHelper outputHelper)
        {
            _outputHelper = outputHelper;
        }

        [Fact]
        public async Task SomeTest()
        {
            var faultedTask = Task.Run(
                () => { throw new InvalidOperationException("Test exception"); });

            //var completionSource = new TaskCompletionSource<bool>();
            //try
            //{
            //    throw new InvalidOperationException("Test exception");
            //}
            //catch (InvalidOperationException ex)
            //{
            //    completionSource.SetException(ex);
            //}

            var tasksToWait = new List<Task>();

            for (var i = 0; i < 10; i++)
            {
                var task = (i & 1) == 0
                    ? Task.Run(() => OneUsage(faultedTask))
                    : Task.Run(() => SecondUsage(faultedTask));
                tasksToWait.Add(task);
            }

            // Waiting all tasks to complete.
            foreach (var t in tasksToWait)
            {
                await t;
            }
        }

        public async Task OneUsage(Task taskToWait)
        {
            try
            {
                await taskToWait;
            }
            catch (InvalidOperationException ex)
            {
                var str = ex.ToString();
                if (str.Contains("SecondUsage"))
                {
                    _outputHelper.WriteLine("----\nOneUsage saw stacktrace from SecondUsage:\n" + str);
                }
            }
        }

        public async void SecondUsage(Task taskToWait)
        {
            try
            {
                await taskToWait;
            }
            catch (InvalidOperationException ex)
            {
                var str = ex.ToString();
                if (str.Contains("OneUsage"))
                {
                    _outputHelper.WriteLine("----\nSecondUsage saw stacktrace from OneUsage:\n" + str);
                }
            }
        }
    }
}
```
### The output is the absolute mess:
```
----
SecondUsage saw stacktrace from OneUsage:
System.InvalidOperationException: Test exception
   at System.Threading.ConcurrentExceptionReThrowTests.<>c.<SomeTest>b__2_0() in C:\src\System\Threading\ConcurrentExceptionReThrowTests.cs:line 24
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ConcurrentExceptionReThrowTests.OneUsage(Task taskToWait) in C:\src\System\Threading\ConcurrentExceptionReThrowTests.cs:line 57
   at System.Threading.ConcurrentExceptionReThrowTests.OneUsage(Task taskToWait) in C:\src\System\Threading\ConcurrentExceptionReThrowTests.cs:line 57
   at System.Threading.ConcurrentExceptionReThrowTests.SecondUsage(Task taskToWait) in C:\src\System\Threading\ConcurrentExceptionReThrowTests.cs:line 73
   at System.Threading.ConcurrentExceptionReThrowTests.SecondUsage(Task taskToWait) in C:\src\System\Threading\ConcurrentExceptionReThrowTests.cs:line 73
   at System.Threading.ConcurrentExceptionReThrowTests.OneUsage(Task taskToWait) in C:\src\System\Threading\ConcurrentExceptionReThrowTests.cs:line 57
   at System.Threading.ConcurrentExceptionReThrowTests.OneUsage(Task taskToWait) in C:\src\System\Threading\ConcurrentExceptionReThrowTests.cs:line 57
----
OneUsage saw stacktrace from SecondUsage:
System.InvalidOperationException: Test exception
   at System.Threading.ConcurrentExceptionReThrowTests.<>c.<SomeTest>b__2_0() in C:\src\System\Threading\ConcurrentExceptionReThrowTests.cs:line 24
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ConcurrentExceptionReThrowTests.OneUsage(Task taskToWait) in C:\src\System\Threading\ConcurrentExceptionReThrowTests.cs:line 57
   at System.Threading.ConcurrentExceptionReThrowTests.OneUsage(Task taskToWait) in C:\src\System\Threading\ConcurrentExceptionReThrowTests.cs:line 57
   at System.Threading.ConcurrentExceptionReThrowTests.SecondUsage(Task taskToWait) in C:\src\System\Threading\ConcurrentExceptionReThrowTests.cs:line 73
   at System.Threading.ConcurrentExceptionReThrowTests.SecondUsage(Task taskToWait) in C:\src\System\Threading\ConcurrentExceptionReThrowTests.cs:line 73
   at System.Threading.ConcurrentExceptionReThrowTests.OneUsage(Task taskToWait) in C:\src\System\Threading\ConcurrentExceptionReThrowTests.cs:line 57
   at System.Threading.ConcurrentExceptionReThrowTests.OneUsage(Task taskToWait) in C:\src\System\Threading\ConcurrentExceptionReThrowTests.cs:line 57
   at System.Threading.ConcurrentExceptionReThrowTests.SecondUsage(Task taskToWait) in C:\src\System\Threading\ConcurrentExceptionReThrowTests.cs:line 73
----
SecondUsage saw stacktrace from OneUsage:
System.InvalidOperationException: Test exception
   at System.Threading.ConcurrentExceptionReThrowTests.<>c.<SomeTest>b__2_0() in C:\src\System\Threading\ConcurrentExceptionReThrowTests.cs:line 24
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ConcurrentExceptionReThrowTests.OneUsage(Task taskToWait) in C:\src\System\Threading\ConcurrentExceptionReThrowTests.cs:line 57
   at System.Threading.ConcurrentExceptionReThrowTests.OneUsage(Task taskToWait) in C:\src\System\Threading\ConcurrentExceptionReThrowTests.cs:line 57
   at System.Threading.ConcurrentExceptionReThrowTests.SecondUsage(Task taskToWait) in C:\src\System\Threading\ConcurrentExceptionReThrowTests.cs:line 73
   at System.Threading.ConcurrentExceptionReThrowTests.SecondUsage(Task taskToWait) in C:\src\System\Threading\ConcurrentExceptionReThrowTests.cs:line 73
   at System.Threading.ConcurrentExceptionReThrowTests.OneUsage(Task taskToWait) in C:\src\System\Threading\ConcurrentExceptionReThrowTests.cs:line 57
   at System.Threading.ConcurrentExceptionReThrowTests.OneUsage(Task taskToWait) in C:\src\System\Threading\ConcurrentExceptionReThrowTests.cs:line 57
   at System.Threading.ConcurrentExceptionReThrowTests.SecondUsage(Task taskToWait) in C:\src\System\Threading\ConcurrentExceptionReThrowTests.cs:line 73
----
OneUsage saw stacktrace from SecondUsage:
System.InvalidOperationException: Test exception
   at System.Threading.ConcurrentExceptionReThrowTests.<>c.<SomeTest>b__2_0() in C:\src\System\Threading\ConcurrentExceptionReThrowTests.cs:line 24
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ConcurrentExceptionReThrowTests.OneUsage(Task taskToWait) in C:\src\System\Threading\ConcurrentExceptionReThrowTests.cs:line 57
   at System.Threading.ConcurrentExceptionReThrowTests.OneUsage(Task taskToWait) in C:\src\System\Threading\ConcurrentExceptionReThrowTests.cs:line 57
   at System.Threading.ConcurrentExceptionReThrowTests.SecondUsage(Task taskToWait) in C:\src\System\Threading\ConcurrentExceptionReThrowTests.cs:line 73
   at System.Threading.ConcurrentExceptionReThrowTests.SecondUsage(Task taskToWait) in C:\src\System\Threading\ConcurrentExceptionReThrowTests.cs:line 73
   at System.Threading.ConcurrentExceptionReThrowTests.OneUsage(Task taskToWait) in C:\src\System\Threading\ConcurrentExceptionReThrowTests.cs:line 57
   at System.Threading.ConcurrentExceptionReThrowTests.OneUsage(Task taskToWait) in C:\src\System\Threading\ConcurrentExceptionReThrowTests.cs:line 57

... the same mess further
```

## Possible Workaround 1
It would be beneficial to store an Exception Stacktrace in the ```ThreadLocal<>``` variable.
And use ```ExceptionDispatchInfo``` as the only option to pass StrackTrace data across threads.
## Possible Workaround 2
*TaskAwaiter re-throws a clone of the original exception.
## Possible Workaround 3
*TaskAwaiter can be configured to forcefully wrap original exception (for example into AggregationException or by wrapper delegate)

**Comment by danmosemsft** [comment] 2020-02-10 04:11
@stephentoub

**Comment by stephentoub** [comment] 2020-02-10 05:36
This is how it's always been and is effectively by design. We chose to propagate the original exception and to concatenate on each re-throw (via ExceptionDispatchInfo). If that happens with the same object concurrently, the segments can be interleaved.

**Comment by dmitriyse** [comment] 2020-02-10 06:07
Most of developers don't know about the "accumulation of stacktrace segments" side-effect. And if them face with such behavior they will be very upset.
I see two disadvantages:
1) Potential risk to receive meaningless stacktraces or even super confusing in logs (and spend extra hours how it possible that your code when could have such weird call stack).
2) When you know that your code have the "accumulation of stacktrace segmentes" side-effect to eliminate this you need to always spent extra efforts to detect places in code where this side-effect exists and adds extra exception wrapping and then conditional handling.

"By design" means some decision was made and it does not saying that the decision were absolutely optimal.
I suggest to add additional behavior to the runtime where stacktraces are "thread local" and give the developers "runtime settings" to choose what behavior is optimal for them.

```Json
{
  "runtimeOptions": {
    "rollForwardOnNoCandidateFx": 2,
    "configProperties": {
      "System.Runtime.TieredCompilation": true,
      "System.Runtime.ThreadLocalStackTraces": true     //       <------- Setting
    }
  }
}
```

**Comment by stephentoub** [comment] 2020-02-10 06:17
> "By design" means some decision was made and it does not saying that the decision were absolutely optimal.

Not saying it was optimal.  But it was done thoughtfully, a decade ago.

> where stacktraces are "thread local" 

I don't know what that means in this context.  The whole purpose of the existing concatenation is to help understand the flow even when it hops threads, which is very common with async.  Are you suggesting that if thread 1 throws an exception, and the continuation runs on thread 2 that thread 2 wouldn't see the portion of the stack trace that occurred on thread 1?  That's a deal breaker.

**Comment by dmitriyse** [comment] 2020-02-10 06:47
The idea is to use ThreadLocal<T> variable for the stack trace.
So the different thread will have its own view of exception stack traces.
```CSharp
public class Exception
{
    //private object? _stackTrace; replace to
    private ThreadLocal<object?> _stackTrace;
}
```
When the TaskAwaiter rises exception from ExceptionDispatchInfo the _stackTrace should be overwritten to a saved in the ExceptionDispatchInfo value.

There no problems in the basic scenarios,
But in general the proposed change is very very complex.
For example we needs to deal with inner exceptions, currently ExceptionDispatchInfo do nothing with the inner exception on Throw method,

**Comment by dmitriyse** [comment] 2020-02-10 06:56
There are other approaches, for example to Configure awaiters to forcefully clone the exception object.
In a worst case, if nothing can be done, the problem should be well documented somewhere.

**Comment by dmitriyse** [comment] 2020-02-10 07:24
>Are you suggesting that if thread 1 throws an exception, and the continuation runs on thread 2 that thread 2 wouldn't see the portion of the stack trace that occurred on thread 1? That's a deal breaker.

There is one thread in which a Task completes with error "Raiser-Thread".

And probably multiple threads that awaits the faulted Task:
Thread 1 -> Independent Stacktrace storage but with the initial copy from the ExceptionDispatchInfo
Thread 2 -> Independent Stacktrace storage but with the initial copy from the ExceptionDispatchInfo
Thread 3 -> Independent Stacktrace storage but with the initial copy from the ExceptionDispatchInfo

Finally we have: 
stacktrace in the Thread 1 should be  ```Raised-Thread``` + ```Thread 1```
the same story for Thread 2, the stacktrace should be ```Raiser-Thread``` + ```Thread 2```

That was the idea with the "ThreadLocal stacktraces".

**Comment by stephentoub** [comment] 2023-01-21 21:24
Thanks for the discussion. I'm closing this as by design.  If there are opportunities to improve the documentation, we'd be happy to see the docs improved.  That can be done in the https://github.com/dotnet/dotnet-api-docs repo.

**Closed by stephentoub** 2023-01-21 21:24 UTC
Labels: documentation, area-System.Threading.Tasks
