### ISSUE TITLE
Test failure Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#94900] opened 2023-11-17 07:46 UTC
**Failed in:** [runtime-coreclr outerloop 20231116.11](https://dev.azure.com/dnceng-public/public/_build/results?buildId=473351&view=ms.vss-test-web.build-test-results-tab&runId=10801976&resultId=119432&paneView=debug)

**Failed tests:**
```
coreclr windows x64 Checked @ Windows.10.Amd64.Open
    - Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd
coreclr windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open
    - Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd
R2R-CG2 windows x64 Checked @ Windows.10.Amd64.Open
    - Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd
R2R-CG2 windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open
    - Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd
```

**Error message:**
```
 
Return code:      1
Raw output file:      C:hwB91D0A04wA04F093EuploadsDisabledRuntimeMarshallingDisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabledoutput.txt
Raw output:
BEGIN EXECUTION
 "C:hwB91D0A04pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.dll 
Xunit.Sdk.FalseException: Assert.False() Failure
Expected: False
Actual:   True
   at Xunit.Assert.False(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 83
   at Xunit.Assert.False(Boolean condition) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 34
   at DisabledRuntimeMarshalling.PInvokeAssemblyMarshallingEnabled.DelegatesFromExternalAssembly.StructWithDefaultNonBlittableFields()
   at __GeneratedMainWrapper.Main()
Expected: 100
Actual: 101
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:cores since 11/17/2023 2:50:47 AM
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> C:hwB91D0A04wA04F093EeInteropInterop../DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.cmd
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 128
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath)
   at Program.<<Main>$>g__TestExecutor37|0_38(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2023-09-09T07:15:28.489Z | runtime-coreclr crossgen2 | Checked | osx.1200.amd64.open | x64 | Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.sh | Failed | {"System.JobName":"__default","System.PhaseAttempt":"1","System.PhaseName":"run_test_p0_coreclr_R2R_CG2_HotColdSplitting_osx_x64_checked","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionId":"124","System.StageAttempt":"1","Project":"public","BuildId":"400574","System.JobAttempt":"1","architecture":"x64","Reason":"Schedule","System.StageName":"Build","AzurePipelinesTestRunId":"8652182","System.JobId":"29eafa29-58bb-5a4a-b8d7-ac7ba8f4fdef","operatingSystem":"OSX.1200.Amd64.Open","configuration":"Checked","DefinitionName":"runtime-coreclr crossgen2","BuildNumber":"20230908.1"} | Schedule
2023-09-09T07:15:28.489Z | runtime-coreclr crossgen2 | Checked | osx.1200.amd64.open | x64 | Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.sh | Failed | {"System.JobName":"__default","System.PhaseAttempt":"1","System.PhaseName":"run_test_p0_coreclr_R2R_CG2_HotColdSplitting_osx_x64_checked","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionId":"124","System.StageAttempt":"1","Project":"public","BuildId":"400574","System.JobAttempt":"1","architecture":"x64","Reason":"Schedule","System.StageName":"Build","AzurePipelinesTestRunId":"8652182","System.JobId":"29eafa29-58bb-5a4a-b8d7-ac7ba8f4fdef","operatingSystem":"OSX.1200.Amd64.Open","configuration":"Checked","DefinitionName":"runtime-coreclr crossgen2","BuildNumber":"20230908.1"} | Schedule
2023-09-09T07:15:28.489Z | runtime-coreclr crossgen2 | Checked | osx.1200.amd64.open | x64 | Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.sh | Failed | {"System.JobName":"__default","System.PhaseAttempt":"1","System.PhaseName":"run_test_p0_coreclr_R2R_CG2_HotColdSplitting_osx_x64_checked","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionId":"124","System.StageAttempt":"1","Project":"public","BuildId":"400574","System.JobAttempt":"1","architecture":"x64","Reason":"Schedule","System.StageName":"Build","AzurePipelinesTestRunId":"8652182","System.JobId":"29eafa29-58bb-5a4a-b8d7-ac7ba8f4fdef","operatingSystem":"OSX.1200.Amd64.Open","configuration":"Checked","DefinitionName":"runtime-coreclr crossgen2","BuildNumber":"20230908.1"} | Schedule
2023-09-09T07:15:28.489Z | runtime-coreclr crossgen2 | Checked | osx.1200.amd64.open | x64 | Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.sh | Failed | {"System.JobName":"__default","System.PhaseAttempt":"1","System.PhaseName":"run_test_p0_coreclr_R2R_CG2_HotColdSplitting_osx_x64_checked","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionId":"124","System.StageAttempt":"1","Project":"public","BuildId":"400574","System.JobAttempt":"1","architecture":"x64","Reason":"Schedule","System.StageName":"Build","AzurePipelinesTestRunId":"8652182","System.JobId":"29eafa29-58bb-5a4a-b8d7-ac7ba8f4fdef","operatingSystem":"OSX.1200.Amd64.Open","configuration":"Checked","DefinitionName":"runtime-coreclr crossgen2","BuildNumber":"20230908.1"} | Schedule
2023-09-09T07:15:28.489Z | runtime-coreclr crossgen2 | Checked | osx.1200.amd64.open | x64 | Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.sh | Failed | {"System.JobName":"__default","System.PhaseAttempt":"1","System.PhaseName":"run_test_p0_coreclr_R2R_CG2_HotColdSplitting_osx_x64_checked","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionId":"124","System.StageAttempt":"1","Project":"public","BuildId":"400574","System.JobAttempt":"1","architecture":"x64","Reason":"Schedule","System.StageName":"Build","AzurePipelinesTestRunId":"8652182","System.JobId":"29eafa29-58bb-5a4a-b8d7-ac7ba8f4fdef","operatingSystem":"OSX.1200.Amd64.Open","configuration":"Checked","DefinitionName":"runtime-coreclr crossgen2","BuildNumber":"20230908.1"} | Schedule
<details>
<summary>More failures</summary>

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2023-09-09T07:15:28.489Z | runtime-coreclr crossgen2 | Checked | osx.1200.amd64.open | x64 | Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.sh | Failed | {"System.JobName":"__default","System.PhaseAttempt":"1","System.PhaseName":"run_test_p0_coreclr_R2R_CG2_HotColdSplitting_osx_x64_checked","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionId":"124","System.StageAttempt":"1","Project":"public","BuildId":"400574","System.JobAttempt":"1","architecture":"x64","Reason":"Schedule","System.StageName":"Build","AzurePipelinesTestRunId":"8652182","System.JobId":"29eafa29-58bb-5a4a-b8d7-ac7ba8f4fdef","operatingSystem":"OSX.1200.Amd64.Open","configuration":"Checked","DefinitionName":"runtime-coreclr crossgen2","BuildNumber":"20230908.1"} | Schedule
2023-09-09T07:15:28.489Z | runtime-coreclr crossgen2 | Checked | osx.1200.amd64.open | x64 | Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.sh | Failed | {"System.JobName":"__default","System.PhaseAttempt":"1","System.PhaseName":"run_test_p0_coreclr_R2R_CG2_HotColdSplitting_osx_x64_checked","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionId":"124","System.StageAttempt":"1","Project":"public","BuildId":"400574","System.JobAttempt":"1","architecture":"x64","Reason":"Schedule","System.StageName":"Build","AzurePipelinesTestRunId":"8652182","System.JobId":"29eafa29-58bb-5a4a-b8d7-ac7ba8f4fdef","operatingSystem":"OSX.1200.Amd64.Open","configuration":"Checked","DefinitionName":"runtime-coreclr crossgen2","BuildNumber":"20230908.1"} | Schedule
2023-09-09T07:15:28.489Z | runtime-coreclr crossgen2 | Checked | osx.1200.amd64.open | x64 | Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.sh | Failed | {"System.JobName":"__default","System.PhaseAttempt":"1","System.PhaseName":"run_test_p0_coreclr_R2R_CG2_HotColdSplitting_osx_x64_checked","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionId":"124","System.StageAttempt":"1","Project":"public","BuildId":"400574","System.JobAttempt":"1","architecture":"x64","Reason":"Schedule","System.StageName":"Build","AzurePipelinesTestRunId":"8652182","System.JobId":"29eafa29-58bb-5a4a-b8d7-ac7ba8f4fdef","operatingSystem":"OSX.1200.Amd64.Open","configuration":"Checked","DefinitionName":"runtime-coreclr crossgen2","BuildNumber":"20230908.1"} | Schedule
2023-09-09T07:15:28.489Z | runtime-coreclr crossgen2 | Checked | osx.1200.amd64.open | x64 | Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.sh | Failed | {"System.JobName":"__default","System.PhaseAttempt":"1","System.PhaseName":"run_test_p0_coreclr_R2R_CG2_HotColdSplitting_osx_x64_checked","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionId":"124","System.StageAttempt":"1","Project":"public","BuildId":"400574","System.JobAttempt":"1","architecture":"x64","Reason":"Schedule","System.StageName":"Build","AzurePipelinesTestRunId":"8652182","System.JobId":"29eafa29-58bb-5a4a-b8d7-ac7ba8f4fdef","operatingSystem":"OSX.1200.Amd64.Open","configuration":"Checked","DefinitionName":"runtime-coreclr crossgen2","BuildNumber":"20230908.1"} | Schedule
2023-08-25T06:32:17.121Z | runtime-coreclr r2r | Checked | ubuntu.2204.amd64.open.rt | x64 | Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.sh | Failed | {"System.PhaseName":"run_test_p1_R2R_linux_x64_checked","Project":"public","AzurePipelinesTestRunId":"8241710","BuildNumber":"20230824.1","System.StageName":"Build","System.JobId":"45a39349-90d5-51c8-4429-a48b2907fbdd","configuration":"Checked","System.JobName":"__default","operatingSystem":"Ubuntu.2204.Amd64.Open","DefinitionName":"runtime-coreclr r2r","System.StageAttempt":"1","Reason":"Schedule","DefinitionId":"120","BuildId":"385732","System.JobAttempt":"1","System.PhaseAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","architecture":"x64"} | Schedule
2023-08-25T06:32:17.121Z | runtime-coreclr r2r | Checked | ubuntu.2204.amd64.open.rt | x64 | Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.sh | Failed | {"System.PhaseName":"run_test_p1_R2R_linux_x64_checked","Project":"public","AzurePipelinesTestRunId":"8241710","BuildNumber":"20230824.1","System.StageName":"Build","System.JobId":"45a39349-90d5-51c8-4429-a48b2907fbdd","configuration":"Checked","System.JobName":"__default","operatingSystem":"Ubuntu.2204.Amd64.Open","DefinitionName":"runtime-coreclr r2r","System.StageAttempt":"1","Reason":"Schedule","DefinitionId":"120","BuildId":"385732","System.JobAttempt":"1","System.PhaseAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","architecture":"x64"} | Schedule
2023-08-25T06:32:17.121Z | runtime-coreclr r2r | Checked | ubuntu.2204.amd64.open.rt | x64 | Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.sh | Failed | {"System.PhaseName":"run_test_p1_R2R_linux_x64_checked","Project":"public","AzurePipelinesTestRunId":"8241710","BuildNumber":"20230824.1","System.StageName":"Build","System.JobId":"45a39349-90d5-51c8-4429-a48b2907fbdd","configuration":"Checked","System.JobName":"__default","operatingSystem":"Ubuntu.2204.Amd64.Open","DefinitionName":"runtime-coreclr r2r","System.StageAttempt":"1","Reason":"Schedule","DefinitionId":"120","BuildId":"385732","System.JobAttempt":"1","System.PhaseAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","architecture":"x64"} | Schedule
2023-08-25T06:32:17.121Z | runtime-coreclr r2r | Checked | ubuntu.2204.amd64.open.rt | x64 | Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.sh | Failed | {"System.PhaseName":"run_test_p1_R2R_linux_x64_checked","Project":"public","AzurePipelinesTestRunId":"8241710","BuildNumber":"20230824.1","System.StageName":"Build","System.JobId":"45a39349-90d5-51c8-4429-a48b2907fbdd","configuration":"Checked","System.JobName":"__default","operatingSystem":"Ubuntu.2204.Amd64.Open","DefinitionName":"runtime-coreclr r2r","System.StageAttempt":"1","Reason":"Schedule","DefinitionId":"120","BuildId":"385732","System.JobAttempt":"1","System.PhaseAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","architecture":"x64"} | Schedule
2023-08-25T06:32:17.121Z | runtime-coreclr r2r | Checked | ubuntu.2204.amd64.open.rt | x64 | Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.sh | Failed | {"System.PhaseName":"run_test_p1_R2R_linux_x64_checked","Project":"public","AzurePipelinesTestRunId":"8241710","BuildNumber":"20230824.1","System.StageName":"Build","System.JobId":"45a39349-90d5-51c8-4429-a48b2907fbdd","configuration":"Checked","System.JobName":"__default","operatingSystem":"Ubuntu.2204.Amd64.Open","DefinitionName":"runtime-coreclr r2r","System.StageAttempt":"1","Reason":"Schedule","DefinitionId":"120","BuildId":"385732","System.JobAttempt":"1","System.PhaseAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","architecture":"x64"} | Schedule
2023-08-25T06:32:17.121Z | runtime-coreclr r2r | Checked | ubuntu.2204.amd64.open.rt | x64 | Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.sh | Failed | {"System.PhaseName":"run_test_p1_R2R_linux_x64_checked","Project":"public","AzurePipelinesTestRunId":"8241710","BuildNumber":"20230824.1","System.StageName":"Build","System.JobId":"45a39349-90d5-51c8-4429-a48b2907fbdd","configuration":"Checked","System.JobName":"__default","operatingSystem":"Ubuntu.2204.Amd64.Open","DefinitionName":"runtime-coreclr r2r","System.StageAttempt":"1","Reason":"Schedule","DefinitionId":"120","BuildId":"385732","System.JobAttempt":"1","System.PhaseAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","architecture":"x64"} | Schedule
2023-08-25T06:32:17.121Z | runtime-coreclr r2r | Checked | ubuntu.2204.amd64.open.rt | x64 | Interop/DisabledRuntimeMarshalling/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled/DisabledRuntimeMarshalling_Disabled_NativeAssemblyEnabled.sh | Failed | {"System.PhaseName":"run_test_p1_R2R_linux_x64_checked","Project":"public","AzurePipelinesTestRunId":"8241710","BuildNumber":"20230824.1","System.StageName":"Build","System.JobId":"45a39349-90d5-51c8-4429-a48b2907fbdd","configuration":"Checked","System.JobName":"__default","operatingSystem":"Ubuntu.2204.Amd64.Open","DefinitionName":"runtime-coreclr r2r","System.StageAttempt":"1","Reason":"Schedule","DefinitionId":"120","BuildId":"385732","System.JobAttempt":"1","System.PhaseAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","architecture":"x64"} | Schedule
</details>

**Comment by AaronRobinsonMSFT** [comment] 2023-11-17 16:31
This actually might be something to do with the project being invalid for merged testing. Moving back to InteropServices until we can confirm.

/cc @trylek

**Comment by AndyAyersMS** [comment] 2023-11-17 21:26
This is getting a ton of hits in CI, see https://github.com/dotnet/runtime/issues/94931

**Comment by AaronRobinsonMSFT** [comment] 2023-11-17 21:45
I'll take a look.

**Comment by AaronRobinsonMSFT** [comment] 2023-11-17 21:53
closing as duplicate of https://github.com/dotnet/runtime/issues/94931

**Closed by AaronRobinsonMSFT** 2023-11-17 21:53 UTC
Labels: area-System.Runtime.InteropServices, os-windows, arch-x64, untriaged, blocking-outerloop
