### ISSUE TITLE
Feature Request: Property Injection

### ISSUE THREAD

**Issue by knight1219** [dotnet/runtime#92916] opened 2023-10-02 15:02 UTC
I know there have been several requests for this over the years

- https://github.com/dotnet/extensions/issues/3019
- https://github.com/dotnet/extensions/issues/3898
- https://github.com/dotnet/extensions/issues/3136

The answer seems to always be "We don't plan to add this, use something else." But that's not true. Microsoft *has* planned AND done this. It works great and I use it ever single day.

One word: **_Blazor_**.

Blazor's built in DI has property injection. Pop a [Inject] attribute on and you good as gold. Maybe the DI container for Blazor is special? Maybe this is the "use something else" for the Blazor team? Can anyone give a good reason why we have this very requested feature on a front-end system and not built in to the very core of the default DI container?

Because if there *is* a difference in the Blazor Di container, how much deviation can we expect? The whole idea of Blazor is being able to use C# and "the same code" on both front and back end and it would be nice if a core part of both systems worked the same.

**Comment by steveharter** [comment] 2023-11-01 19:21
> Because if there is a difference in the Blazor Di container, how much deviation can we expect? The whole idea of Blazor is being able to use C# and "the same code" on both front and back end and it would be nice if a core part of both systems worked the same.

Blazor support for property injection is to support the `@inject` directive in view pages; see https://learn.microsoft.com/en-us/aspnet/core/mvc/views/dependency-injection. It wasn't really intended to be used outside of that such as using `[Inject]` directly.

For another perspective, see https://stackoverflow.com/questions/65629065/c-sharp-asp-net-core-inject-attribute-usage-for-dependency-injection. This has some references to why property injection isn't exactly a best practice.

Closing as a duplicate of the other issues linked in the description for this issue.

cc @davidfowl

**Closed by steveharter** 2023-11-01 19:21 UTC
Labels: area-Extensions-DependencyInjection
