### ISSUE TITLE
Microsoft.Extensions.FileProviders.Physical.Tests Failed with access denied

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#57266] opened 2021-08-12 06:14 UTC
Release coreclr debug libraries windows.81.amd64

https://github.com/dotnet/runtime/pull/57143

```
Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.UsePollingFileWatcher_UseActivePolling_HasChanged_SymbolicLink_TargetChanged(useWildcard: False, linkWasBroken: False) [FAIL]
      System.UnauthorizedAccessException : Access to the path 'C:\h\w\CA000AB6\t\prclsd4p.iat\ybz3jmzk.eor' is denied.
      Stack Trace:
        /_/src/libraries/Common/src/Interop/Windows/Kernel32/Interop.CreateSymbolicLink.cs(60,0): at Interop.Kernel32.CreateSymbolicLink(String symlinkFileName, String targetFileName, Boolean isDirectory)
        /_/src/libraries/System.Private.CoreLib/src/System/IO/FileSystem.Windows.cs(428,0): at System.IO.FileSystem.CreateSymbolicLink(String path, String pathToTarget, Boolean isDirectory)
        /_/src/libraries/System.Private.CoreLib/src/System/IO/File.cs(1026,0): at System.IO.File.CreateSymbolicLink(String path, String pathToTarget)
        /_/src/libraries/Microsoft.Extensions.FileProviders.Physical/tests/PhysicalFileProviderTests.netcoreapp.cs(109,0): at Microsoft.Extensions.FileProviders.PhysicalFileProviderTests.UsePollingFileWatcher_UseActivePolling_HasChanged_SymbolicLink_TargetChanged(Boolean useWildcard, Boolean linkWasBroken)
        --- End of stack trace from previous location ---
  Finished:    Microsoft.Extensions.FileProviders.Physical.Tests
  ```

**Comment by danmoseley** [comment] 2021-08-12 06:25
BTW I had to read the code to see whether this path is source or destination.
Its assumed to be destination when the OS API fails - is that a safe assumption?
https://github.com/dotnet/runtime/blob/dcce0f56e10f5ac9539354b049341a2d7c0cdebf/src/libraries/Common/src/Interop/Windows/Kernel32/Interop.CreateSymbolicLink.cs#L60

**Comment by adamsitnik** [comment] 2021-08-12 07:08
cc @carlossanlop @Jozkee

**Comment by hoyosjs** [comment] 2021-08-12 10:22
Seems like a dupe of #56810

**Closed by hoyosjs** 2021-08-12 10:22 UTC
Labels: untriaged, area-Extensions-FileSystem
