### ISSUE TITLE
[API Proposal]: new<TArgument>() generic constraints for constructor with parameters

### ISSUE THREAD

**Issue by MithrilMan** [dotnet/runtime#68858] opened 2022-05-04 15:25 UTC
### Background and motivation

Actually we can instantiate generic types, without using Activator.CreateInstance, if we put a `new()` generic constraint but this is limited to parameterless constructor.

If we want to instantiate a generic type using a constructor overload, we have to find alternative solutions.

Suppose a scenario where I want to create a Guard static class like this

```
public static class Guard
{
   public static void Against<TException>(bool assertion, string message) where TException : Exception
   {
      if (assertion)
         throw (TException)Activator.CreateInstance(typeof(TException), message);
   }
}
```

where I can pass an exception as a generic type, I have to use Activator.CreateInstance if I want to instantiate it with a message.

### API Proposal

having a way to set a generic constructor with parameter constraint would solve the issue.

a constraint in the form of

`new<TArgument1>()`
`new<TArgument1, TArgument2>()`
`new<TArgument1, TArgument2, TArgument3>()`
...

### API Usage

```csharp
public static class Guard
{
   public static void Against<TException>(bool assertion, string message) where TException : Exception, new<string>()
   {
      if (assertion)
         throw new TException(message);
   }
}
```

**Comment by 333fred** [comment] 2022-05-04 15:34
Duplicate of https://github.com/dotnet/csharplang/discussions/769.

**Closed by 333fred** 2022-05-04 15:35 UTC
Labels: api-suggestion, untriaged
