### ISSUE TITLE
PEReader throws exception when using PEStreamOptions.PrefetchMetadata for some assemblies

### ISSUE THREAD

**Issue by joelverhagen** [dotnet/runtime#46344] opened 2020-12-22 23:13 UTC
### Description

I am using `System.Reflection.PortableExecutable.PEReader` on all assemblies on NuGet.org and I am seeing a strange behavior. My expectation would be that that using `PEStreamOptions.PrefetchMetadata` would not cause an exception to be thrown if calling `PEReader.HasMetadata` returns a boolean successfully when not using that option. Perhaps this is a bad assumption, but to me it is not clear from the documentation so I figured I'd open an issue just in case.

In the [documentation for the constructor](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.portableexecutable.pereader.-ctor?view=net-5.0#System_Reflection_PortableExecutable_PEReader__ctor_System_IO_Stream_System_Reflection_PortableExecutable_PEStreamOptions_), it does mention an `IOException` can be thrown when prefetching, but I'm not sure if this particular case is what is being talked about.

In short, I was expecting `PEStreamOptions.PrefetchMetadata` to perform the same sort of flow as `PEReader.HasMetadata`, but eagerly instead of lazily, meaning the same results -- exceptions or return values whatever the case may be. Is this a wrong thought? This assumption seems to be true for most DLLs, but not all.

Here's a small bit of code to demonstrate:

```csharp
var path = "korwblex.dll"; // found in qnamakerruntime 4.0.9 (NuGet package)
// path = "dotnet-ef.exe"; // this one is not a managed assembly I think and behaves how I would expect

Console.WriteLine(path);
Console.WriteLine("== PEReader with no options ==");
using (var fileStream = File.OpenRead(path))
using (var peReader = new PEReader(fileStream))
{
    Console.WriteLine(peReader.HasMetadata); // returns false
}

Console.WriteLine("== PEReader with PrefetchMetadata ==");
using (var fileStream = File.OpenRead(path))
using (var peReader = new PEReader(fileStream, PEStreamOptions.PrefetchMetadata))
{
    Console.WriteLine(peReader.HasMetadata); // throws IOException
}
```

The output is:

```
korwblex.dll
== PEReader with no options ==
False
== PEReader with PrefetchMetadata ==
Unhandled exception. System.IO.IOException: An attempt was made to move the file pointer before the beginning of the file. : 'C:\z\trash\2020-12-15\ConsoleApp2\ConsoleApp2\bin\Debug\net5.0\korwblex.dll'
   at System.IO.FileStream.SeekCore(SafeFileHandle fileHandle, Int64 offset, SeekOrigin origin, Boolean closeInvalidHandle)
   at System.IO.FileStream.Seek(Int64 offset, SeekOrigin origin)
   at System.Reflection.Internal.StreamMemoryBlockProvider.ReadMemoryBlockNoLock(Stream stream, Boolean isFileStream, Int64 start, Int32 size)
   at System.Reflection.PortableExecutable.PEReader..ctor(Stream peStream, PEStreamOptions options, Int32 size)
   at System.Reflection.PortableExecutable.PEReader..ctor(Stream peStream, PEStreamOptions options)
   at ConsoleApp2.Program.Main(String[] args) in C:\z\trash\2020-12-15\ConsoleApp2\ConsoleApp2\Program.cs:line 23
```

### Configuration

```
NET SDK (reflecting any global.json):
 Version:   5.0.200-preview.20614.14
 Commit:    863605c8c3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.200-preview.20614.14\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab
```

### Regression?

I don't know.

### Other information

Here is a ZIP of the project. The "korwblex.dll" has a strange, even suspicious, name but my expectation is the PEReader is safe even for untrusted input. [ConsoleApp2.zip](https://github.com/dotnet/runtime/files/5732325/ConsoleApp2.zip)

**Comment by krwq** [comment] 2021-02-26 14:44
Looking at the documentation of PrefetchMetadata from https://docs.microsoft.com/en-us/dotnet/api/system.reflection.portableexecutable.pestreamoptions?view=net-5.0

> PEReader closes the stream automatically by the time the constructor returns unless LeaveOpen is specified. The underlying file may be closed and even deleted after PEReader is constructed.

So I think an error is expected, I think you'd need to pass `PEStreamOptions.PrefetchMetadata | PEStreamOptions.LeaveOpen)` for this to behave as you expect.

**Comment by krwq** [comment] 2021-03-03 13:53
@joelverhagen let me know if that helps whenever you have a chance to test.

**Comment by joelverhagen** [comment] 2021-03-03 17:16
Apologies on the delay @krwq. I tried `PEStreamOptions.PrefetchMetadata | PEStreamOptions.LeaveOpen` and it seemed to have the same result as `PEStreamOptions.PrefetchMetadata` -- an `IOException` is thrown instead of a `false` boolean.

```csharp
Console.WriteLine("== PEReader with PrefetchMetadata ==");
using (var fileStream = File.OpenRead(path))
using (var peReader = new PEReader(fileStream, PEStreamOptions.PrefetchMetadata | PEStreamOptions.LeaveOpen))
{
    Console.WriteLine(peReader.HasMetadata); // throws IOException
}
````

This is easy enough to work around (I just avoided using `PrefetchMetadata):
https://github.com/joelverhagen/ExplorePackages/blob/734404bf00aec69408f527e0a736cfb57dd19888/src/ExplorePackages.Worker.Logic/CatalogScan/Drivers/PackageAssemblyToCsv/PackageAssemblyToCsvDriver.cs#L196

If this is by design, feel free to close. Perhaps the docs could be improved to clarify this difference.

**Comment by krwq** [comment] 2021-03-04 10:37
At first glance it doesn't seem by design to me. Thanks for testing!

**Comment by buyaa-n** [comment] 2022-10-24 18:35
[Triage] The issue is valid, keeping it open in future milestone. 

PE file does not contain any managed metadata, therefore throws when trying to load metadata
https://github.com/dotnet/runtime/blob/58a1180ad6421c6f69cf307b57b2496c888585f2/src/libraries/System.Reflection.Metadata/src/System/Reflection/PortableExecutable/PEReader.cs#L201-L202

The `_lazyPEHeaders.MetadataStartOffse` = -1, I am not sure if we should just skip loading metadata or should throw in this case.
cc @tmat @steveharter

**Comment by ericstj** [comment] 2023-08-11 06:46
I think skipping read is the right thing to do, so long as all our APIs would still behave as they would when data is not prefetched.  I took a brief look and it seems like that would be the case.

**Comment by steveharter** [comment] 2023-08-11 14:30
Moving to v9; valid issue that should be addressed.

**Closed** 2024-04-03 20:32 UTC
Labels: area-System.Reflection.Metadata, help wanted, in-pr
