### ISSUE TITLE
Include the information you need in ReflectionTypeLoadException

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#45790] opened 2020-12-08 21:57 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/759588/include-the-information-you-need-in-reflectiontype.html)._

---
<p>In Azure (but I could get it elsewhere also) I get something like this:</p><p>Failed to load role entrypoint. System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Retrieve the LoaderExceptions property for more information. 
at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module) 
at System.Reflection.Assembly.GetTypes() 
at Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironment.GetRoleEntryPoint(Assembly entryPointAssembly) </p><p>To watch fusion logs in Azure, I have to get to a compliant device (which has a tiny screen), use some compliant methods (which even more), and in the end it takes hours to get a RDP view on a constantly restarting VM to get the information I need in a lot of noice from the fusion log viewer.</p><p>Instead, the exception should include the class name of the class it failed to resolve. Bonus for including the dependency path or last .class/.dll that needed whatever wasn't found.</p>

---
#### Jane Wu [MSFT] on 10/8/2019, 05:29 AM: 

<p>Thank you for taking the time to provide your suggestion. We will do some preliminary checks to make sure we can proceed further.  We’ll provide an update once the issue has been triaged by the product team.</p>

**Comment by jkotas** [comment] 2020-12-09 00:19
Duplicate of https://github.com/dotnet/runtime/issues/24452. Fixed in .NET Core.

**Closed by jkotas** 2020-12-09 00:19 UTC
Labels: area-System.Reflection, untriaged
