### ISSUE TITLE
Utf8JsonReader.TryGetDateTime throws IndexOutOfRangeException

### ISSUE THREAD

**Issue by mlankamp** [dotnet/runtime#70584] opened 2022-06-10 19:23 UTC
### Description

The `Utf8JsonReader.TryGetDateTime` throws an `IndexOutOfRangeException`, and since this is a Try method I would expect all exceptions to be caught.

### Reproduction Steps

```C#
using System.Text;
using System.Text.Json;

var json = "{ \"value\": \"\\u00BD\\u0022\" }";
ReadOnlySpan<byte> jsonUtf8 = Encoding.UTF8.GetBytes(json);

var reader = new Utf8JsonReader(jsonUtf8);

while (reader.TokenType != JsonTokenType.EndObject)
{
    if (reader.TokenType == JsonTokenType.String)
    {
        if (reader.TryGetDateTime(out DateTime d))
        {
            Console.WriteLine(d);
        }
    }

    reader.Read();
}
```

### Expected behavior

Because it's a try method I would expect a return value of false.

### Actual behavior

```
   at System.Text.Json.JsonHelpers.TryParseDateTimeOffset(ReadOnlySpan`1 source, DateTimeParseData& parseData)
   at System.Text.Json.JsonHelpers.TryParseAsISO(ReadOnlySpan`1 source, DateTime& value)
   at System.Text.Json.JsonReaderHelper.TryGetEscapedDateTime(ReadOnlySpan`1 source, DateTime& value)
   at System.Text.Json.Utf8JsonReader.TryGetDateTimeCore(DateTime& value)
   at System.Text.Json.Utf8JsonReader.TryGetDateTime(DateTime& value)
```

### Regression?

No

### Known Workarounds

Wrap in a try-catch block

### Configuration

net6 on Windows and Linux

**Comment by eiriktsarpalis** [comment] 2022-06-13 14:28
Duplicate of #62720, .NET 7 will incorporate the fix.

**Closed by eiriktsarpalis** 2022-06-13 14:28 UTC
Labels: area-System.Text.Json, untriaged
