### ISSUE TITLE
[API Proposal]: An extension method similar to "enumerate" or "withIndex" in other languages

### ISSUE THREAD

**Issue by PaddiM8** [dotnet/runtime#78156] opened 2022-11-10 13:14 UTC
### Background and motivation

Many modern languages have functions that give you the current index of the _iteration_. In Rust and Python, this is called `enumerate`, and in Kotlin `withIndex`. In C#,`Select` already provides this, but it would also be neat to have a pretty way of doing it with foreach loops, as is often done in the languages mentioned. 

In Rust, it's described like this: https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.enumerate

Calling it `Enumerate` would probably be confusing in C#, considering we have Enumerables. `WithIndex` is probably more appropriate, but it could also be confusing, since the point of a method like this is generally not to deal with indices of elements, but of iterations, but I'm not sure what else would be appropriate.

### API Proposal

```csharp
public IEnumerable<(T item, int index)> WithIndex<T>(this IEnumerable<T> self);
```

### API Usage

```csharp
foreach (var (item, i) in items.WithIndex())
{
    ...
}
```

**Comment by stephentoub** [comment] 2022-11-10 13:37
> In C#,Selectalready provides this, but it would also be neat to have a pretty way of doing it with foreach loops

Just pointing out that the proposed usage:
```C#
foreach (var (item, i) in items.WithIndex())
```
is possible with Select and a foreach loop:
```C#
foreach (var (item, i) in items.Select((t,i) => (t,i)))
```

**Comment by PaddiM8** [comment] 2022-11-10 13:42
@stephentoub Yep! It's just a small convenience method for some less visual noise.

**Comment by dakersnar** [comment] 2022-11-10 17:41
The `Select` pattern does seem a bit unintuitive to me compared to what other languages are offering, especially considering it looks like `Select` is designed for more complex transformations. I think `WithIndex` is a reasonable name for this functionality and feels cleaner than using `Select` here.

**Comment by NN---** [comment] 2022-11-12 08:14
C# Language discussion: https://github.com/dotnet/csharplang/discussions/627

**Comment by davidfowl** [comment] 2022-11-13 07:13
This would be better (and more efficient) if implemented as a language feature.

**Comment by PaddiM8** [comment] 2022-11-19 15:24
> This would be better (and more efficient) if implemented as a language feature.

Perhaps. Seems to be commonly implemented with a function in mainstream languages but one could argue that it doesn't show intent as clearly and doesn't work with while loops.

I guess the alternative to an extension method would be something like this?
```cs
foreach (var x in items : i)
    ...

while (condition : i)
    ...
```

Is adding complexity to the language worth it though?

**Comment by davidfowl** [comment] 2022-11-19 19:39
I don't see how you make it as efficient as it can be without that.

**Comment by GSPP** [comment] 2022-11-26 21:25
I found this to be a surprisingly common need and I have used such an extension method quite a bit. My usages actually rarely were foreach-based. Rather, the index was fed into further LINQ processing. `items.Select((t, i) => (t, i))` works but it's verbose and not semantic.

**Comment by terrajobst** [comment] 2023-12-12 22:32
Sorry, didn't see this earlier. I just filed something similar and we approved it today.

Duplicate of #95563.

**Closed by terrajobst** 2023-12-12 22:32 UTC
Labels: api-suggestion, area-System.Runtime, untriaged
