### ISSUE TITLE
Test failure Regressions/coreclr/GitHub_45929/test45929/test45929.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#58702] opened 2021-09-06 01:47 UTC
Run: [runtime-coreclr gcstress-extra 20210904.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1343634&view=ms.vss-test-web.build-test-results-tab&runId=39348758&paneView=debug&resultId=109549)

Failed test:
```
CoreCLR Linux arm64 Checked gcstress0xc_jitstress1 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- Regressions/coreclr/GitHub_45929/test45929/test45929.sh

```
**Error message:**
```
/root/helix/work/workitem/Regressions/coreclr/GitHub_45929/test45929/test45929.sh: line 370:  3000 Segmentation fault      (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/Regressions.coreclr/GitHub_45929/test45929/test45929.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false test45929.dll ''
The test started.
Progress:
9/4/2021 11:19:04 PM : 000.0% : 1003
9/4/2021 11:19:10 PM : 000.0% : 6480
9/4/2021 11:19:10 PM : 000.0% : 6508
9/4/2021 11:19:11 PM : 000.0% : 6812
9/4/2021 11:19:11 PM : 000.0% : 7268
9/4/2021 11:19:12 PM : 000.1% : 7987
9/4/2021 11:19:13 PM : 000.1% : 9252
9/4/2021 11:19:15 PM : 000.1% : 11075
9/4/2021 11:19:18 PM : 000.2% : 14083
9/4/2021 11:19:20 PM : 000.3% : 16157
9/4/2021 11:19:23 PM : 000.4% : 18967
9/4/2021 11:19:27 PM : 000.6% : 23273
9/4/2021 11:19:33 PM : 000.9% : 29419
9/4/2021 11:19:36 PM : 001.0% : 32356
9/4/2021 11:19:57 PM : 002.0% : 53277
Gathering state for process 3000 corerun
Crashing thread 00000cb6 signal 0000000b
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.3000.dmp
Written 162549760 bytes (39685 pages) to core file
Dump successfully written
Expected: 100
Actual: 139
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/Regressions/coreclr/GitHub_45929/test45929/test45929.sh
Expected: True
Actual:   False


Stack trace
   at Regressions_coreclr._GitHub_45929_test45929_test45929_._GitHub_45929_test45929_test45929_sh()
```

**Comment by mangod9** [comment] 2022-07-27 17:31
closing as dupe of https://github.com/dotnet/runtime/issues/60152

**Closed by mangod9** 2022-07-27 17:31 UTC
Labels: arch-arm64, os-linux, GCStress, area-VM-coreclr
