### ISSUE TITLE
Base64 String decoding

### ISSUE THREAD

**Issue by NUnitTester** [dotnet/runtime#50233] opened 2021-03-25 12:34 UTC
### Description

the following Code was used:
string base64String = ...;
Convert.FromBase64String(base64String);

"asdfghw=" ok, Result:  < 106, 199, 95, 130, 28 >
"asdfghw=asdfghw="  ok, Exception
"asdfghw==" wrong! Should be Exception, but gives a total wrong result with less Bytes than the first one. Result: < 106, 199, 95, 135 >

 .NET 4.8
Windows 10
x64, x86 

. NET 3.1 Core
"asdfghw==" 
System.FormatException: "The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters."

**Comment by EgorBo** [comment] 2021-03-25 15:23
`asdfghw==` is not a correct base64, it should be `asdfghw=`, .NET doesn't accept malformed base64 strings since .NET Core 2.1

**Comment by GrabYourPitchforks** [comment] 2021-03-25 18:29
> .NET doesn't accept malformed base64 strings since .NET Core 2.1

To be fair, we do accept some malformed strings. For instance, `Convert.FromBase64String("asdfghW=")` doesn't throw an exception, even though it probably should.

**Comment by buyaa-n** [comment] 2024-07-26 17:54
> asdfghw== is not a correct base64, it should be asdfghw=, .NET doesn't accept malformed base64 strings since .NET Core 2.1

As mentioned its not reproducible in Core

> To be fair, we do accept some malformed strings. For instance, Convert.FromBase64String("asdfghW=") doesn't throw an exception, even though it probably should.

Resolved with https://github.com/dotnet/runtime/pull/105262, closing

**Closed by buyaa-n** 2024-07-26 17:54 UTC
Labels: area-System.Runtime
