### ISSUE TITLE
System.Text.Json Serializer does not appear to work on Xamarin iOS

### ISSUE THREAD

**Issue by jefffhaynes** [dotnet/runtime#31326] opened 2019-10-28 17:54 UTC
Perhaps not surprisingly, System.Text.Json.Serializer does not appear to function on iOS likely owing to the lack of Emit support.

```c#
public class ChatMessage
{
    [JsonPropertyName("id")]
    public string Id { get; set; }

    [JsonPropertyName("sent")]
    public DateTime? SentOn { get; set; }
}

JsonSerializer.Deserialize<ChatMessage>(json);
```

This yields:

System.ExecutionEngineException: Attempting to JIT compile method '(wrapper delegate-invoke) void <Module>:invoke_callvirt_void_ChatMessage_Nullable`1<DateTime> (Chat.Messaging.ChatMessage,System.Nullable`1<System.DateTime>)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.

**Comment by eman1986** [comment] 2020-02-18 20:28
is there plans to get this working for iOS? My team just upgraded our api website to NETCore 3.1 and we switched out to the System.Text.Json

**Comment by steveharter** [comment] 2020-04-28 21:47
> Are there plans to get this working for iOS?

We are [working on enabling "reach" scenarios](https://github.com/dotnet/designs/pull/113) for 5.0, but nothing is committed yet.

We've made some serializer changes in 5.0 that appear to help with its usage of `Type.MakeGenericType` -- I verified that a simple iOS device test that used to fail on 3.1 is now working on 5.0 master. When we are get our test infrastructure to run all serializer tests on an iOS device then we will know the actual status and what work is remaining.

**Comment by mc0re** [comment] 2020-06-01 18:55
> Interesting that I can make System.Text.Json working on UWP .Net Native after adding some linker instructions.

@huoyaoyuan What instructions?

**Comment by huoyaoyuan** [comment] 2020-06-02 06:29
@mc0re 
```xml
<Assembly Name="System.Collections.Immutable" Dynamic="Required Public" />
```

It only solves part of the problem. Not fully working.

**Comment by steveharter** [comment] 2020-06-02 20:26
Let's try to keep this issue just for Xamarin and not .NET Native since there are separate issues.

The .NET Native issues are caused by its linker removing "unreferenced" assemblies.
  - The serializer issue for that: https://github.com/dotnet/runtime/issues/29912
  - The UWP issue for that: https://github.com/dotnet/runtime/issues/978

**Comment by Jacko1394** [comment] 2020-06-24 03:59
Adding the `--interpreter` flag to the additional Mtouch args seems to fix the problem for me.
`<MtouchExtraArgs>--interpreter</MtouchExtraArgs>`
Tho I agree annoying it just doesn't work...

**Comment by steveharter** [comment] 2020-08-04 17:38
@Jacko1394 is this still on 3.1? Have you been able to try this on any 5.0 previews?

**Comment by steveharter** [comment] 2020-08-11 15:33
Closing this as fixed for 5.0.

If this repros still on 5.0, please re-open.

**Closed by steveharter** 2020-08-11 15:33 UTC
Labels: area-System.Text.Json

**Comment by klogeaage** [comment] 2020-08-15 12:08
@steveharter I tried the latest preview package, 5.0.0-preview.7.20364.11, but it completely failed to deserialize the JSON received from my .Net Core 3.1 backend. This is surprising, as the backend uses System.Text.Json. It gave no errors, just returned objects with no sensible data in them.

This is the code with the working Newtonsoft statements commented out:
```
  HttpResponseMessage response = await _client.GetAsync($"{ControllerName}{additionalParameters}");
  response.EnsureSuccessStatusCode();
  using var stream = await response.Content.ReadAsStreamAsync();
  //using (var reader = new StreamReader(stream))
  //using (var json = new JsonTextReader(reader))
  //    rv = _serializer.Deserialize<T1>(json);
  rv = await System.Text.Json.JsonSerializer.DeserializeAsync<T1>(stream);
  return rv;
```

Would you be interested in digging into what the problem is? Then I would be happy to continue testing.

**Comment by mc0re** [comment] 2020-08-15 19:12
@klogeaage I might be off-track here, but check the serialization options you use in the 3.1 serializer.
For what I recall, *Newtonsoft* (de)serializes into `camelCase` by default, while *System.Text.Json* - into `PascalCase`. There is also different treatment of numbers - *Newtonsoft* happily accepts `"10"` as a numeric field, while *System.Text.Json* does not.

In short, check the incoming text and if you're using any options for serialization.

**Comment by steveharter** [comment] 2020-08-16 00:50
Due to Ios policy, Reflection.Emit is not supported. The netstandard version of System.Text.Json needs to be used which uses standard reflection instead of Emit.

**Comment by klogeaage** [comment] 2020-08-16 14:00
@mc0re thanks for your comments, which led me to the solution: setting `PropertyNamingPolicy = System.Text.Json.JsonNamingPolicy.CamelCase` on the front-end. I don't set this on the back-end, but apparently Asp.NET Core does, which I guess makes sense as it results in more idiomatic JSON.

@steveharter so with the above change, I was able to get it working also on a physical iOS device, which is what didn't work previously. So this issue can remain closed as far as I'm concerned.

However, I found that there is no performance improvement to be gained in moving from Newtonsoft (using the `JsonTextReader `pattern and avoiding strings as shown above) - on the contrary, I found a degradation in deserialization performance of between 32% (Android) and 20% (iOS), measured on physical devices as an average of 10 operations deserializing a 523 KB JSON payload. 

While this is not a disastrous performance hit, it is contrary to the claim that System.Text.Json will have better performance than Newtonsoft.Json and it once again shows that Newtonsoft.Json is a tough act to follow.

**Comment by ericstj** [comment] 2020-08-19 00:49
That seems a significant per difference and disagrees with most of our benchmarks. Share a full benchmark in a new issue and we’ll investigate.  We stand by our perf claims.  It’s possible there is an opportunity for improvement here in STJ or mono runtime.

**Comment by klogeaage** [comment] 2020-08-20 11:52
@ericstj I'm glad you take this seriously and have created a new issue as requested: #41089.

**Comment by steveharter** [comment] 2020-08-24 21:52
> However, I found that there is no performance improvement to be gained in moving from Newtonsoft (using the JsonTextReader pattern and avoiding strings as shown above) - on the contrary, I found a degradation in deserialization performance of between 32% (Android) and 20% (iOS), measured on physical devices as an average of 10 operations deserializing a 523 KB JSON payload.

The likely reason perf is slower in STJ is in these cases is because STJ uses standard reflection Invoke, not Emit, for the netstandard (non-inbox) configurations. Newtonsoft instead uses compiled expressions trees which are netstandard-compatible but also brings in the very large System.Linq.Expressions.dll so there a disk_size+memory_usage+startup_time vs throughput tradeoff here. It is possible to add support for S.Linq.Expressions if we decide it's worth the tradeoff in these non-inbox scenarios, however for 6.0 we are also looking at alternate ways to get\set properties and call constructors that do not use Emit but are just as fast.

**Comment by klogeaage** [comment] 2020-08-24 22:07
@steveharter may I suggest you post your comments in #41089 which I created for the performance issue?

**Comment by steveharter** [comment] 2020-08-24 22:11
@klogeaage yes thanks.

**Comment by jefffhaynes** [comment] 2020-08-24 22:20
You could try "magic methods" (maybe that is what you're trying), originally from Skeet:

https://github.com/jefffhaynes/BinarySerializer/blob/master/BinarySerializer/MagicMethods.cs

**Comment by steveharter** [comment] 2020-08-24 22:45
> You could try "magic methods" (maybe that is what you're trying), originally from Skeet:

That exact example will box, however in 3.0\3.1 we did use that approach for performance (instead of reflection invoke). However, it required tricky usage of generics to avoid boxing, which is exactly the issue that cause Xamarin to not work.

**Comment by jefffhaynes** [comment] 2020-08-24 22:46
Ah, fair point!
