### ISSUE TITLE
Inconsistent/Incorrect float formatting

### ISSUE THREAD

**Issue by Suchiman** [dotnet/runtime#12897] opened 2019-06-16 21:03 UTC
Using following code
```csharp
var SingleValue = 65747.125f;
Console.WriteLine(SingleValue.ToString("#,###.00"));
Console.WriteLine(SingleValue.ToString());
```

On [.NET Framework](https://sharplab.io/#v2:EYLgHgbALANALiATgVwHYB8ACAmAjAWACgicBmIgbyIAJbqdsa6rC63qA3AQ0WoGUAlqgDmAGwCmANS6jk46gF5qEAKwB2KGoB0ubCoBmAbibt6uAJwAKQSInTZ4rQBUA9nziIhwywCIAxDB+QVoADCE+AJQRxqymZlY2YlIycs5uHl6WUTFsAL5xRES5QA=), this results in
```
65,747.13
65747.13
```
which doesn't roundtrip but rounds correctly.

On [.NET Core](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoa0gZmoG9qACNl0k195q9/lgDcAhlBYBlAJZ4A5gBsYANWFycMFgF4WSAKwB2FHoB0ZEjoBmAbm4COZAJwAKKbIXLVMIwBUI4jFGkZRwAiAGI0UMijAAZo4IBKeOs+WzsnF3klFTVvX39Ax0Tk/gBfVOpqEqA) this gives
```
65,747.10
65747.125
```
which actually roundtrips the floating point number (:+1:), except when you specify a format string, then the result is completely off for some reason.

cc @tannergooding

**Comment by tannergooding** [comment] 2020-06-23 21:38
Closing as the custom-numeric format string issue was fixed and the change to regular formatting is by design.

**Closed by tannergooding** 2020-06-23 21:38 UTC
Labels: area-System.Numerics
