### ISSUE TITLE
System.Data.Common asnyc method abstractions

### ISSUE THREAD

**Issue by ladeak** [dotnet/runtime#39079] opened 2020-07-10 15:49 UTC
## Background

System.Data defines ```IDbCommand```, ```IDbConnection```
System.Data.Odbc has implementations of these interfaces that also support Async operations (OpenAsync, ReadAsync, ExecuteScalarAsync, etc). Those async methods are actually inherited from the base, for example ```DbCommand```.

Provide async method counterparts on interfaces, so DB logic of an app using these abstractions can still rely on interfaces and use the async methods.
Having the async methods on interfaces improves testability (OdbcCommand, OdbcConnection, OdbcReader, etc. types could be  mocked by their interfaces). Today a partial workaround is to wrap these sealed classes / type match them during runtime).

## Proposed API

In System.Data create interface IAsyncDbCommand:

```
public interface IAsyncDbCommand : IDbCommand 
{
        Task<int> ExecuteNonQueryAsync();
        Task<IDataReader> ExecuteReaderAsync();
        Task<IDataReader> ExecuteReaderAsync(CommandBehavior behavior);
        Task<object?> ExecuteScalarAsync();
        // overrides with Cancellation etc.
}
```
so this can be implemented by ```DbCommand``` (or actually is already implemented).

## Alternative Designs

Evolve ```IDbCommand``` interface by using Default implementations in interfaces.
```
Task<int> ExecuteNonQueryAsync() => Task.FromResult(ExecuteNonQuery());
```

**Comment by SingleAccretion** [comment] 2020-07-10 17:00
> Default implementations in interfaces.

The optimistic timeline for the usage of this feature in the BCL is ~2027 (or so I heard anyway). Just FYI.

**Comment by scalablecory** [comment] 2020-07-10 17:34
What benefit do you see to using the interfaces as an abstraction vs the base classes?

**Comment by roji** [comment] 2020-07-10 17:41
Duplicate of #26505

**Comment by roji** [comment] 2020-07-10 17:42
As @ajcvickers wrote in https://github.com/dotnet/runtime/issues/26505#issuecomment-648313455:

> System.Data and many applications built on System.Data assume that the interfaces can be cast to the base types. This greatly reduces the usefulness of the interfaces since in many cases different implementations than expected with result in exceptions. This means that, even with default interface implementations now available, we still don't plan to evolve these interfaces.

**Closed by roji** 2020-07-10 17:42 UTC
Labels: api-suggestion, area-System.Data, untriaged

**Comment by ladeak** [comment] 2020-07-10 20:51
Thank you for the suggestion and the explanation on the history of this interface. I generally prefer to code against interfaces compared to abstract base classes, but in this case it makes sense to use that.
