### ISSUE TITLE
System.Text.Json serialization fails in .Net Framework for objects with a specify constructor

### ISSUE THREAD

**Issue by christian-h-jensen** [dotnet/runtime#78844] opened 2022-11-25 08:54 UTC
### Description

When you serialize an object, which has a constructer with a DateTime and a default value (default), then it fails if you run in .Net Framework.

I seems strange that the serializer should even care about the constructor? For the deserialization I can understand that.

### Reproduction Steps

Try to serialize an object with System.Text.Json in e.g net48. The objects has to have a constructer which takes a DateTime and has default value (default).

Have made a public github repo with unittests. This is done for a few runtimes. net472, net48, netcoreapp3.1, net6.0. It looks like it only fails in the .Net Framework runtimes.

https://github.com/christian-h-jensen/SerializeJson

### Expected behavior

That the serializer just serializes the object.

### Actual behavior

Serialization fails with:
  Message: 
Test method SerializeJson.Test.SerializeTest.JsonSerialize_can_serialize_a_person threw exception: 
System.FormatException: Encountered an invalid type for a default value.

  Stack Trace: 
MdConstant.GetValue(MetadataImport scope, Int32 token, RuntimeTypeHandle fieldTypeHandle, Boolean raw)
RuntimeParameterInfo.GetDefaultValueInternal(Boolean raw)
RuntimeParameterInfo.get_HasDefaultValue()
ReflectionJsonTypeInfo`1.GetParameterInfoValues()
JsonTypeInfo.Configure()
JsonTypeInfo.<EnsureConfigured>g__ConfigureLocked|143_0()
JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Boolean resolveIfMutable)
JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType)
JsonSerializer.GetTypeInfo[T](JsonSerializerOptions options)
JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
SerializeTest.JsonSerialize_can_serialize_a_person() line 17

**Comment by eiriktsarpalis** [comment] 2022-11-25 09:40
Duplicate of https://github.com/dotnet/runtime/issues/18844. We generally don't backport bugfixes like that to .NET framework, so you might consider using a workaround, either
```C#
public Person(DateTime? birthDay = null)
```
or
```C#
public Person(DateTime? birthDay = DateTime.Now)
```

**Closed by eiriktsarpalis** 2022-11-25 09:40 UTC
Labels: area-System.Text.Json, untriaged
