### ISSUE TITLE
Mono is not unloading collectible assemblies

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#91641] opened 2023-09-05 21:36 UTC
Placeholder for now until verified through CI.

The tests being added for https://github.com/dotnet/runtime/pull/91290 that check if a collectible assembly is unloaded are not passing under Mono. I assume this should work.

Also, even if the Type-based caches that were added in the `ActivatorUtilities.cs` in the referenced PR are #ifdef'd out (like they are for NetFramework), the tests under Mono still fail suggesting the unload issue is general and that the usage of `ConditionalWeakTable<Type, ConstructorInfoEx[]>` in `ActivatorUtilities.cs` is not the reason the tests fail.

**Comment by jkotas** [comment] 2023-09-06 03:48
Duplicate of https://github.com/dotnet/runtime/issues/34072

**Closed by jkotas** 2023-09-06 03:48 UTC
Labels: untriaged, runtime-mono, needs-area-label
