### ISSUE TITLE
[API Proposal]: Consider DI overloads to use implementation factory with open generic types

### ISSUE THREAD

**Issue by Chakrygin** [dotnet/runtime#72163] opened 2022-07-14 08:04 UTC
### Background and motivation

Hi!

Now we can register an implementation factory for an open generic type, but we can't use it because it doesn't have any information about the type of the object to be created.

For example:

```cs
public sealed class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddSingleton(typeof(ILogger<>), serviceProvider =>
        {
            // We can't create an logger because we don't know its type.
            var logger = ...;

            return logger;
        });
    }
}
```

### API Proposal

This proposal about to add implementation factory overloads that also have the type parameter of the object being created.

```cs
public static IServiceCollection AddSingleton(
    this IServiceCollection services,
    Type serviceType,
    Func<IServiceProvider, Type, object> implementationFactory) // <= Add Type parameter.
```

### API Usage

```cs
public sealed class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddSingleton(typeof(ILogger<>), (serviceProvider, serviceType) =>
        {
            var loggerType = GetLoggerTypeByServiceType(serviceType); // Using reflection
            var logger = ActivatioUtilities.CreateInstance(loggerType, serviceProvider);

            return logger;
        });
    }
}
```

```cs
// serviceType in implementation factory is ILogger<SomeClass>
var logger = serviceProvider.GetRequiredService<ILogger<SomeClass>>();
```

**Comment by eerhardt** [comment] 2022-07-14 14:46
Duplicate of https://github.com/dotnet/runtime/issues/41050.

**Closed by eerhardt** 2022-07-14 14:46 UTC
Labels: api-suggestion, untriaged, area-Extensions-DependencyInjection
