### ISSUE TITLE
Blazor Hot Reload: MatBlazor Button breaks Hot reload in Dotnet 6 preview 3.

### ISSUE THREAD

**Issue by vallgrenerik** [dotnet/runtime#51126] opened 2021-04-10 12:45 UTC
### Describe the bug
Hello! 
First: Thanks for fantastic work with Hot reload. It looks promising! 
But unfortunately a MatBlazor (https://www.matblazor.com/) button "MatButton" makes the hot reload crash.

### To Reproduce
I've created a repo https://github.com/vallgrenerik/HotReloadTest 
(A simple Blazor WASM ASP.Core Hosted)
Look inside the Index.razor in the .Client project. 

Uncomment the button to make it crash.
Comment out the MatButton, press CTRL + R in terminal to force reload and the Hot reload works again.

### Exceptions (if any)
The crash appears in the browser console like this: 
```
* Assertion at /__w/1/s/src/mono/mono/metadata/metadata-update.c:809, 
condition `<disabled>' not met
```
Full crash: 
```
dotnet.6.0.0-preview.3.21201.4.js:1 * Assertion at /__w/1/s/src/mono/mono/metadata/metadata-update.c:809, condition `<disabled>' not met

542288 @ dotnet.6.0.0-preview.3.21201.4.js:1
_emscripten_asm_const_int @ dotnet.6.0.0-preview.3.21201.4.js:1
(anonymous) @ 008ace4e:0xdec8e
(anonymous) @ 008ace4e:0x19281b
(anonymous) @ 008ace4e:0x107942
(anonymous) @ 008ace4e:0x8b218
(anonymous) @ 008ace4e:0xf002
(anonymous) @ 008ace4e:0x7c6f
(anonymous) @ 008ace4e:0x56f3
(anonymous) @ 008ace4e:0x1a180a
(anonymous) @ 008ace4e:0x11988d
(anonymous) @ 008ace4e:0xee6f7
(anonymous) @ 008ace4e:0xdf021
(anonymous) @ 008ace4e:0xe1e41
(anonymous) @ 008ace4e:0x46356
(anonymous) @ 008ace4e:0x12dfac
(anonymous) @ 008ace4e:0x117c6e
(anonymous) @ 008ace4e:0x7a160
(anonymous) @ 008ace4e:0xfcc5
(anonymous) @ 008ace4e:0x10dc13
(anonymous) @ 008ace4e:0xee3e6
(anonymous) @ 008ace4e:0xedf47
(anonymous) @ 008ace4e:0x194d3b
(anonymous) @ 008ace4e:0x59c7c
(anonymous) @ 008ace4e:0x46258
(anonymous) @ 008ace4e:0x12dfac
(anonymous) @ 008ace4e:0x117c6e
(anonymous) @ 008ace4e:0x7a160
(anonymous) @ 008ace4e:0x152f4
(anonymous) @ 008ace4e:0x10e00d
fb @ 008ace4e:0x108652
Module._mono_wasm_invoke_method @ dotnet.6.0.0-preview.3.21201.4.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_InvokeDotNet @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_InvokeDotNet:19
invokeDotNetFromJS @ blazor.webassembly.js:1
m @ blazor.webassembly.js:1
e.invokeMethod @ blazor.webassembly.js:1
he._internal.applyHotReload @ blazor.webassembly.js:1
(anonymous) @ aspnetcore-browser-refresh.js:101
applyBlazorDeltas @ aspnetcore-browser-refresh.js:101
BlazorHotReloadDeltav1 @ aspnetcore-browser-refresh.js:31
connection.onmessage @ aspnetcore-browser-refresh.js:37
Show 11 more frames
```

### Further technical details
- ASP.NET Core version 6.0.0-preview.3.21201.13
- Include the output of dotnet --info
```
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.3.21202.5
 Commit:    aee38a6dd4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.3.21202.5\

Host (useful for support):
  Version: 6.0.0-preview.3.21201.4
  Commit:  236cb21e3c

.NET SDKs installed:
  3.1.407 [C:\Program Files\dotnet\sdk]
  5.0.200-preview.20614.14 [C:\Program Files\dotnet\sdk]
  5.0.200-preview.21077.7 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.3.21202.5 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.3.21201.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.3.21201.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.3.21201.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
- Microsoft Visual Studio Professional 2019 Preview
Version 16.10.0 Preview 1.0

**Comment by dicarne** [comment] 2021-04-29 04:14
AntDesign also crash. In fact, I guess any third-party UI framework will cause this problem. Hotreload worked well when I create a new project, but it carshed when I import AntDesign.

**Comment by anddrzejb** [comment] 2021-04-29 07:32
I am a member of AntDesign. I just run my own tests and in my case I did not experience crashes. In my case best Hot Reload experience is with server-side. My changes were immediately applied. In case of wasm - if I had any component of AntDesign in my razor file, the changes I was making were not applied. I had to press Ctrl+R, then they were applied. If I commented out AntDesign component - changes were applied. I also created a basic razor library to have comparison - and basic library changes are reflected. 

One curious scenario - when AntDesign component was already added, on first run when I commented it out, hot reload was kicking in and the component was removed from DOM. Uncommenting had no effect - it was not added again. If on the first run I made any other change (either to the AntDesign component or for example just added a text), hot reload was not working. Then removing AntDesign component had no effect either. 

Eventually I replaced AntDesign nuget with direct reference to AntDesing project. I upgraded it to net6 but it had no effect.
After upgrading to net6 I tried to do some development in the AntDesign. My setup is that I have a main project which references AntDesign. Hot reload was not working there (this is on server-side). When I was making a change to AntDesign, hot reload was not seeing it. I was at least expecting a message in the console in form of `watch: File changed (...)` but not even that. Eventually I narrowed it down to the fact that `AntDesign` is targeting multiple frameworks. So I had to replace this
```xml
    <TargetFrameworks>netstandard2.1;net5;net6</TargetFrameworks>
```
with this
```xml
    <TargetFramework>net6</TargetFramework>
```
and hot reload started working. Of course I had to also comment out couple of `<ItemGroup Condition="$(TargetFramework) == ''(...)">` condition groups. Hot reload wasn't fast, but I guess this is because AntDesign is a fairly large project? Again, this is only for server side. 
@dicarne I can publish my repro - maybe you'll be able to track down the differences and why my project is not crashing.

**Comment by dicarne** [comment] 2021-04-29 08:01
My TargetFramework is `<TargetFramework>net6</TargetFramework>`. I use wasm and removed all condition groups. I even clone AntDesign and compiled a net6 version, but it didn't help.
I use `dotnet watch` to start. Page looks great until I change something in source code.
And errors occur in console:
```
* Assertion at /__w/1/s/src/mono/mono/metadata/metadata-update.c:809, condition `<disabled>' not met

542288 @ dotnet.6.0.0-preview.3.21201.4.js:1
_emscripten_asm_const_int @ dotnet.6.0.0-preview.3.21201.4.js:1
(anonymous) @ 008ace4e:0xdec8e
(anonymous) @ 008ace4e:0x19281b
(anonymous) @ 008ace4e:0x107942
(anonymous) @ 008ace4e:0x8b218
(anonymous) @ 008ace4e:0xf002
(anonymous) @ 008ace4e:0x7c6f
(anonymous) @ 008ace4e:0x56f3
(anonymous) @ 008ace4e:0x1a180a
(anonymous) @ 008ace4e:0x11988d
(anonymous) @ 008ace4e:0xee6f7
(anonymous) @ 008ace4e:0xdf021
(anonymous) @ 008ace4e:0xe1e41
(anonymous) @ 008ace4e:0x46356
(anonymous) @ 008ace4e:0x12dfac
(anonymous) @ 008ace4e:0x117c6e
(anonymous) @ 008ace4e:0x7a160
(anonymous) @ 008ace4e:0xfcc5
(anonymous) @ 008ace4e:0x10dc13
(anonymous) @ 008ace4e:0xee3e6
(anonymous) @ 008ace4e:0xedf47
(anonymous) @ 008ace4e:0x194d3b
(anonymous) @ 008ace4e:0x59c7c
(anonymous) @ 008ace4e:0x46258
(anonymous) @ 008ace4e:0x12dfac
(anonymous) @ 008ace4e:0x117c6e
(anonymous) @ 008ace4e:0x7a160
(anonymous) @ 008ace4e:0x152f4
(anonymous) @ 008ace4e:0x10e00d
fb @ 008ace4e:0x108652
Module._mono_wasm_invoke_method @ dotnet.6.0.0-preview.3.21201.4.js:1
managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_InvokeDotNet @ managed__Microsoft_AspNetCore_Components_WebAssembly__Microsoft_AspNetCore_Components_WebAssembly_Services_DefaultWebAssemblyJSRuntime_InvokeDotNet:19
invokeDotNetFromJS @ blazor.webassembly.js:1
m @ blazor.webassembly.js:1
e.invokeMethod @ blazor.webassembly.js:1
he._internal.applyHotReload @ blazor.webassembly.js:1
(anonymous) @ aspnetcore-browser-refresh.js:101
applyBlazorDeltas @ aspnetcore-browser-refresh.js:101
BlazorHotReloadDeltav1 @ aspnetcore-browser-refresh.js:31
connection.onmessage @ aspnetcore-browser-refresh.js:37
Show 11 more frames
```
```
ExitStatus {name: "ExitStatus", message: "Program terminated with exit(0)", status: 0}
message: "Program terminated with exit(0)"
name: "ExitStatus"
status: 0
```
If I remove AntDesign, hotreload works again. @anddrzejb I guess wasm hotreload is not support well.

**Comment by anddrzejb** [comment] 2021-04-29 08:28
@dicarne You are right. Somehow I missed the exceptions in the browser...

**Comment by lambdageek** [comment] 2021-04-29 13:45
@anddrzejb @dicarne Blazor server-side and browser have different hot reload capabilities - currently there are more limitations on the browser side.  For the .NET 6 release, we're working to bring the WebAssembly hot reload closer to the capabilities of Blazor on the server, and to improve diagnostics so that the app falls back to restarting if we cannot hot reload the code on the browser.

**Comment by anddrzejb** [comment] 2021-04-29 16:23
I do remember from the blog post that wasm experience is behind in comparison to server-side. 

I wanted also to emphasize that in server-side it seems that hot reload is not working for libraries that target multiple frameworks.

**Comment by lambdageek** [comment] 2021-04-29 16:28
> I wanted also to emphasize that in server-side it seems that hot reload is not working for libraries that target multiple frameworks.

@pranavkm is there an issue already for this ^^^ ?

**Comment by pranavkm** [comment] 2021-04-29 16:55
@anddrzejb could you file a separate issue for this in https://github.com/dotnet/aspnetcore possibly with a minimal app that reproduces the problem? We haven't tested this particular scenario but it's surprising to know that multi-targeting affects this.

**Comment by anddrzejb** [comment] 2021-04-29 17:19
Sure, I will try to prep something. I think that is the problem - once I removed multitargeting from AntDesign, hot reload started to work. When I reversed it - it stopped working.

**Comment by lewing** [comment] 2021-07-31 21:35
@lambdageek what is the status of this?

**Comment by lambdageek** [comment] 2021-08-13 18:10
This issue is essentially a duplicate of https://github.com/dotnet/runtime/issues/50249 at this point.

> Updating of existing lambda bodies that are generated from .razor pages will become supported once dotnet/roslyn#55407 makes it into the dotnet SDK.

That means editing a page that has existing MatBlazor buttons should work

> Adding new lambdas will be .net 7

Adding new MatBlazor buttons will be a rude edit in .net 6 and will cause the blazor webassembly app to ask to restart.

**Comment by lambdageek** [comment] 2022-01-18 23:46
> > Adding new lambdas will be .net 7
> 
> Adding new MatBlazor buttons will be a rude edit in .net 6 and will cause the blazor webassembly app to ask to restart.

The initial support for hot reload edits that add new lambdas has been added (https://github.com/dotnet/runtime/pull/63513).  It should be available in the first .NET 7 preview.

**Comment by vallgrenerik** [comment] 2022-01-20 06:49
Thanks for the update @lambdageek 
Should I close this issue?

**Comment by lambdageek** [comment] 2022-01-20 13:55
@vallgrenerik I'd prefer to keep it open until a preview is out and I can verify that it's working.

**Comment by ilonatommy** [comment] 2022-06-15 09:23
@lambdageek, I tested in 7 preview 4 - it does not crash, hot reload with the button works. I am closing.

**Closed by ilonatommy** 2022-06-15 09:23 UTC
Labels: arch-wasm, area-EnC-mono
