### ISSUE TITLE
QUIC LargeDataSentAndReceived test hung CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#55968] opened 2021-07-19 21:27 UTC
net6.0-Linux-Debug-x64-Mono_release-(Fedora.32.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-32-helix-20210710031120-870c408

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55925-merge-f386de62d8e44beab3/System.Net.Quic.Functional.Tests/console.ee68f32a.log?sv=2019-07-07&se=2021-08-08T18%3A52%3A02Z&sr=c&sp=rl&sig=X6ArQ3b5FP5o27fhzaUgTiFgU0zYguuhE3ZKfo2vDLA%3D

```
  Discovering: System.Net.Quic.Functional.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Quic.Functional.Tests (found 106 of 121 test cases)
  Starting:    System.Net.Quic.Functional.Tests (parallel test collections = on, max threads = 2)
   System.Net.Quic.Functional.Tests: [Long Running Test] 'System.Net.Quic.Tests.QuicStreamTests_MsQuicProvider.LargeDataSentAndReceived', Elapsed: 00:02:02
[Long Running Test] 'System.Net.Quic.Tests.MsQuicQuicStreamConformanceTests.ReadWrite_Success', Elapsed: 00:02:04
   System.Net.Quic.Functional.Tests: [Long Running Test] 'System.Net.Quic.Tests.QuicStreamTests_MsQuicProvider.LargeDataSentAndReceived', Elapsed: 00:04:02
[Long Running Test] 'System.Net.Quic.Tests.MsQuicQuicStreamConformanceTests.ReadWrite_Success', Elapsed: 00:04:04
   System.Net.Quic.Functional.Tests: [Long Running Test] 'System.Net.Quic.Tests.QuicStreamTests_MsQuicProvider.LargeDataSentAndReceived', Elapsed: 00:06:02
[Long Running Test] 'System.Net.Quic.Tests.MsQuicQuicStreamConformanceTests.ReadWrite_Success', Elapsed: 00:06:04
   System.Net.Quic.Functional.Tests: [Long Running Test] 'System.Net.Quic.Tests.QuicStreamTests_MsQuicProvider.LargeDataSentAndReceived', Elapsed: 00:08:02
[Long Running Test] 'System.Net.Quic.Tests.MsQuicQuicStreamConformanceTests.ReadWrite_Success', Elapsed: 00:08:04
   System.Net.Quic.Functional.Tests: [Long Running Test] 'System.Net.Quic.Tests.QuicStreamTests_MsQuicProvider.LargeDataSentAndReceived', Elapsed: 00:10:02
[Long Running Test] 'System.Net.Quic.Tests.MsQuicQuicStreamConformanceTests.ReadWrite_Success', Elapsed: 00:10:04
   System.Net.Quic.Functional.Tests: [Long Running Test] 'System.Net.Quic.Tests.QuicStreamTests_MsQuicProvider.LargeDataSentAndReceived', Elapsed: 00:12:02
[Long Running Test] 'System.Net.Quic.Tests.MsQuicQuicStreamConformanceTests.ReadWrite_Success', Elapsed: 00:12:04
   System.Net.Quic.Functional.Tests: [Long Running Test] 'System.Net.Quic.Tests.QuicStreamTests_MsQuicProvider.LargeDataSentAndReceived', Elapsed: 00:14:02
[Long Running Test] 'System.Net.Quic.Tests.MsQuicQuicStreamConformanceTests.ReadWrite_Success', Elapsed: 00:14:04

...
[EXECUTION TIMED OUT]
Exit Code:-3Executor timed out after 900 seconds and was killed
['System.Net.Quic.Functional.Tests' END OF WORK ITEM LOG: Command timed out, and was killed]
```

**Comment by ManickaP** [comment] 2021-07-20 07:58
Duplicate of #55642

**Closed by ManickaP** 2021-07-20 07:58 UTC
Labels: area-System.Net.Quic, untriaged
