### ISSUE TITLE
System.Globalization tests fail on Android

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#37074] opened 2020-05-27 17:40 UTC
### System.Globalization.CalendarsWithConfigSwitch.Tests:
- [ ] System.Globalization.Tests.CalendarTests.TestJapaneseCalendarDateParsing
```
<test name="System.Globalization.Tests.CalendarTests.TestJapaneseCalendarDateParsing" type="System.Globalization.Tests.CalendarTests" method="TestJapaneseCalendarDateParsing" time="0.237673" result="Fail">
  <failure exception-type="Xunit.Sdk.ThrowsException">
    <message><![CDATA[Assert.Throws() Failure\nExpected: typeof(System.FormatException)\nActual:   (No exception was thrown)]]></message>
    <stack-trace><![CDATA[   at System.Globalization.Tests.CalendarTests.TestJapaneseCalendarDateParsing() in /Users/mdhwang/runtime/src/libraries/System.Globalization.Calendars/tests/CalendarTestWithConfigSwitch/CalendarTests.cs:line 22
		at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/mdhwang/runtime/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 359]]></stack-trace>
  </failure>
</test>
```
___
### System.Globalization.Tests:
[List of test failures](https://github.com/dotnet/runtime/files/4690726/fails.txt)
[XML of test failures](https://github.com/dotnet/runtime/files/4690727/test_failures.txt)

**Comment by tarekgh** [comment] 2020-05-27 17:49
@safern could you please link this to the global issue tracking all failures and possibly close it?

**Comment by safern** [comment] 2020-05-27 17:50
Thanks, @mmitche -- dupe of: https://github.com/dotnet/runtime/issues/36672

I believe @steveisok opened some issues for Android so I recommend looking for issues with the label: `os-android` and see what's opened, which ones we can collapse into a single meta issue and which ones don't need a new issue to avoid having to mark them as dupe and closing them.

**Closed by safern** 2020-05-27 17:50 UTC
Labels: area-System.Globalization, os-android, test-run-core, untriaged
