### ISSUE TITLE
Segregate Count() to interface ICountable or support Enumerable.Count(this IEnumerable enumerable)

### ISSUE THREAD

**Issue by ivanivanyuk1993** [dotnet/runtime#41589] opened 2020-08-31 11:33 UTC
## Background and Motivation

I have a use case
```cs
private PropertyGetterOrConstant<TEntity> GetCountPropertyGetterOrConstant(PropertyGetInfoProto propertyGetInfoProto)
{
    var countPropertyGetterOrConstant = GetPropertyGetterOrConstant(propertyGetInfoProto.Count);

    PropertyGetterOrConstant<TEntity> resultPropertyGetterOrConstant;
    if (countPropertyGetterOrConstant.IsConstant)
        resultPropertyGetterOrConstant = new PropertyGetterOrConstant<TEntity>(
            ((IEnumerable) countPropertyGetterOrConstant.Constant).OfType<object>().Count()
        );
    else
        resultPropertyGetterOrConstant = new PropertyGetterOrConstant<TEntity>(
            entity => ((IEnumerable) countPropertyGetterOrConstant.Getter!(entity)).OfType<object>().Count()
        );

    return resultPropertyGetterOrConstant;
}
```
I want it to be
```cs
private PropertyGetterOrConstant<TEntity> GetCountPropertyGetterOrConstant(PropertyGetInfoProto propertyGetInfoProto)
{
    var countPropertyGetterOrConstant = GetPropertyGetterOrConstant(propertyGetInfoProto.Count);

    PropertyGetterOrConstant<TEntity> resultPropertyGetterOrConstant;
    if (countPropertyGetterOrConstant.IsConstant)
        resultPropertyGetterOrConstant = new PropertyGetterOrConstant<TEntity>(
            ((ICountable) countPropertyGetterOrConstant.Constant).Count()
        );
    else
        resultPropertyGetterOrConstant = new PropertyGetterOrConstant<TEntity>(
            entity => ((ICountable) countPropertyGetterOrConstant.Getter!(entity)).Count()
        );

    return resultPropertyGetterOrConstant;
}
```
or
```cs
private PropertyGetterOrConstant<TEntity> GetCountPropertyGetterOrConstant(PropertyGetInfoProto propertyGetInfoProto)
{
    var countPropertyGetterOrConstant = GetPropertyGetterOrConstant(propertyGetInfoProto.Count);

    PropertyGetterOrConstant<TEntity> resultPropertyGetterOrConstant;
    if (countPropertyGetterOrConstant.IsConstant)
        resultPropertyGetterOrConstant = new PropertyGetterOrConstant<TEntity>(
            ((IEnumerable) countPropertyGetterOrConstant.Constant).Count()
        );
    else
        resultPropertyGetterOrConstant = new PropertyGetterOrConstant<TEntity>(
            entity => ((IEnumerable) countPropertyGetterOrConstant.Getter!(entity)).Count()
        );

    return resultPropertyGetterOrConstant;
}
```

## Proposed API

Now public static int Count<TSource>(this IEnumerable<TSource> source) in System.Linq.Enumerable has to check for multiple Type cases
```cs
public static int Count<TSource>(this IEnumerable<TSource> source)
{
    if (source == null)
    {
        ThrowHelper.ThrowArgumentNullException(ExceptionArgument.source);
    }

    if (source is ICollection<TSource> collectionoft)
    {
        return collectionoft.Count;
    }

    if (source is IIListProvider<TSource> listProv)
    {
        return listProv.GetCount(onlyIfCheap: false);
    }

    if (source is ICollection collection)
    {
        return collection.Count;
    }

    int count = 0;
    using (IEnumerator<TSource> e = source.GetEnumerator())
    {
        checked
        {
            while (e.MoveNext())
            {
                count++;
            }
        }
    }

    return count;
}
```

It could be

```cs
public static int Count(ICountable countable)
{
    if (countable == null)
    {
        ThrowHelper.ThrowArgumentNullException(ExceptionArgument.source);
    }

    return countable.Count();
}
```

## Usage Examples

```cs
private PropertyGetterOrConstant<TEntity> GetCountPropertyGetterOrConstant(PropertyGetInfoProto propertyGetInfoProto)
{
    var countPropertyGetterOrConstant = GetPropertyGetterOrConstant(propertyGetInfoProto.Count);

    PropertyGetterOrConstant<TEntity> resultPropertyGetterOrConstant;
    if (countPropertyGetterOrConstant.IsConstant)
        resultPropertyGetterOrConstant = new PropertyGetterOrConstant<TEntity>(
            ((ICountable) countPropertyGetterOrConstant.Constant).Count()
        );
    else
        resultPropertyGetterOrConstant = new PropertyGetterOrConstant<TEntity>(
            entity => ((ICountable) countPropertyGetterOrConstant.Getter!(entity)).Count()
        );

    return resultPropertyGetterOrConstant;
}
```

## Risks

It requires implementing ICountable in ICollection and IIListProvider and using countable.Count() instead of collection.Count and list.GetCount() in code

**Comment by adamsitnik** [comment] 2020-10-29 14:47
Closing as duplicate of #41598

**Closed by adamsitnik** 2020-10-29 14:47 UTC
Labels: api-suggestion, area-System.Linq
