### ISSUE TITLE
System.Resources.Extensions.DeserializingResourceReader cannot load an assembly if .NET WinForms controls are used inside a C++ app

### ISSUE THREAD

**Issue by EgorRudakov2** [dotnet/runtime#66799] opened 2022-03-17 10:47 UTC
* .NET Core Version: 6.0.201

* Have you experienced this same bug with .NET Framework?: No

**Problem description:**

I have a native C++ app that shows WinForms form via proxy managed c++ dll (built with .NET Core Runtime Support (/clr:netcore) switch). Deserialization of the form fails if the form resx file contains a value of a type defined in a 3rd party assembly, since assembly loading fails. If the same form is loaded from С# WinForms Application, everything works fine.

Exception thrown by DeserializingResourceReader:
```
System.NotSupportedException: Cannot read resources that depend on serialization.
   at System.Resources.Extensions.DeserializingResourceReader.UseReflectionToGetType(Int32 typeIndex)
   at System.Resources.Extensions.DeserializingResourceReader.FindType(Int32 typeIndex)
   at System.Resources.Extensions.DeserializingResourceReader.DeserializeObject(Int32 typeIndex)
   at System.Resources.Extensions.DeserializingResourceReader._LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.Extensions.DeserializingResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.Extensions.DeserializingResourceReader.ResourceEnumerator.get_Entry()
   at System.Resources.Extensions.DeserializingResourceReader.ResourceEnumerator.get_Current()
   at System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   at System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   at System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   at System.ComponentModel.ComponentResourceManager.ApplyResources(Object value, String objectName, CultureInfo culture)
   at System.ComponentModel.ComponentResourceManager.ApplyResources(Object value, String objectName)
   at Net6ClassLibarary.Form2.InitializeComponent()
   at Net6ClassLibarary.Form2..ctor()
   at CLRFunctions.ShowWinFormsForm() in C:\work\!!\Sample\Project1CLR\TestClass.cpp:line 9
```

FileNotFoundException that cached by DeserializingResourceReader.UseReflectionToGetType(int typeIndex) method:
```
System.IO.FileNotFoundException: Could not load file or assembly 'PropertyTypeLibrary, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'PropertyTypeLibrary, Culture=neutral, PublicKeyToken=null'
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMarkHandle stackMark, ObjectHandleOnStack assemblyLoadContext, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
```
According to the logs from dotnet--trace:

First, assembly successfully loaded to the IsolatedComponentLoadContext
` AssemblyLoadContext=""IsolatedComponentLoadContext(C:\work\!!\Sample\x64\Debug\Project1CLR.dll)"`
then
DeserializingResourceReader trying to load to the Default context:
`AssemblyLoadContext="Default"`
and fails.
You can see full logs there (problem assembly name "PropertyTypeLibrary"):

[dottraceLogs.zip](https://github.com/dotnet/winforms/files/8282455/dottraceLogs.zip)

**Expected behavior:**

A form is deserialized without any exception (same as in a C# Winforms App)

**Minimal repro:**

1. Open and build the attached solution using VS 2022 (required C++ and MFC build tools).
2. Run with debugger the MFCApplication2 project.
3. Click the Button1 button. The application crashes on resource deserialization.
If you run WinFormsApp1, you will see that the same approach works correctly in a WinForms C# application.

Sample project structure:

- MFCApplication2 - Native C++ and entry point
- Project1CLR - Proxy dll that used to show managed WinForms form from native C++ app.
- Net6ClassLibrary - contains form to show
- WinFormsControlLibrary1 - contains winforms user control that have serializable property with user defined type (used by the form in Net6ClassLibrary)
- PropertyTypeLibrary - contains user defined type for control property (that dll is fails to load by DeserializingResourceReader)
- WinFormsApp1 - simple app to demonstrate that deserialization works fine in the pure managed app.

[С++Net6.zip](https://github.com/dotnet/winforms/files/8282488/%2B%2BNet6.zip)

**Comment by dreddy-work** [comment] 2022-03-17 22:44
This does not look like WinForms issue. It seems something changed in System.Resources.Extensions.DeserializingResourceReader in .NET core throwing this.

**Comment by AaronRobinsonMSFT** [comment] 2022-03-23 15:44
This is similar to the C++/CLI issue described at https://github.com/dotnet/runtime/issues/61105. A similar, likely identical root cause but in .NET Framework, was described in https://github.com/dotnet/docs/issues/26649.

/cc @vitek-karas @elinor-fung

**Comment by StephenMolloy** [comment] 2022-05-05 21:47
There seems to be various runtime, winforms, and resources components in play here. Nothing that looks like XmlSerializer or DataContractSerializer though. Removing area-serialization which is specific to those two serializers.

**Comment by ericstj** [comment] 2022-05-05 23:42
As @EgorRudakov2 pointed out the problem is the `FileNotFoundException`.  For that resource to be read it needs to be able to load the assembly `PropertyTypeLibrary`.  The resource reader knows nothing about `AssemblyLoadContexts`, it needs the host / runtime / Reflection to make the right choice for loading.  Since a native host is involved here, that component takes some of the responsibility itself.

For a normal WinForms application it has a deps.json file that tells the host which libraries make up the application and where to load libraries.  The host reads that deps file and sets up the runtime.  

@AaronRobinsonMSFT @EgorRudakov2 can either of you comment on why the runtime cannot load this assembly?  Is it because the host isn't setup correctly to find it in the default ALC or does it have something to do with the different ALCs involved?

**Comment by vitek-karas** [comment] 2022-05-06 09:45
The problem is that C++/CLI hosting loads the assembly into a secondary ALC (in .NET 6 this is the only behavior). But the resource reader code is not ALC aware, so it calls `Type.GetType(<typename>)` inside `System.Resources.Extensions.DeserilizingResourceReader.UseReflectionToGetType`. The `Type.GetType(string)` will use the ALC of the calling method, which in this case is from winforms, so framework and thus in Default ALC. So it can't find the type which is only loaded into the secondary ACL by the C++/CLI hosting.

In .NET 7 we changed the default and C++/CLI hosting will load the assembly into Default ALC - see https://github.com/dotnet/runtime/pull/66486 for details.

In .NET 6 you might be able to workaround this by adding
```C#
using (AssemblyLoadContext.EnterContextualReflection(typeof(Form2).Assembly))
{
    InitializeComponent();
}
```

Around the call to InitializeComponent - or if that's not possible inside the InitializeComponent.
What this does is that it tells `Type.GetType` (and other reflection APIs) to not use the callers ALC, but instead the one specified in the call (so in the case the ALC of the assembly which has `Form2` in it).
But I wasn't able to try this - I couldn't get your repro building (maybe I'm using too new VS, or some other problem...).

**Comment by agocke** [comment] 2022-07-01 20:05
Fixed in .NET 6.

**Closed by agocke** 2022-07-01 20:05 UTC
Labels: area-AssemblyLoader-coreclr, untriaged
