### ISSUE TITLE
Test failure System.Numerics.Tensors.Tests.IntPtrGenericTensorPrimitives.MinMagnitude_TwoTensors_SpecialValues

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#96471] opened 2024-01-04 06:41 UTC
Run: [runtime-coreclr libraries-jitstress 20240103.3](https://dev.azure.com/dnceng-public/public/_build/results?buildId=513811&view=ms.vss-test-web.build-test-results-tab&runId=12042888&resultId=168387&paneView=debug)

Failed test:
```
net9.0-linux-Release-x64-CoreCLR_checked-jitstress2_tiered-Ubuntu.2204.Amd64.Open

- System.Numerics.Tensors.Tests.IntPtrGenericTensorPrimitives.MinMagnitude_TwoTensors_SpecialValues
- System.Numerics.Tensors.Tests.IntPtrGenericTensorPrimitives.Add_TwoTensors_InPlace
- System.Numerics.Tensors.Tests.IntPtrGenericTensorPrimitives.Min_TwoTensors_SpecialValues
- System.Numerics.Tensors.Tests.Int64GenericTensorPrimitives.Max_TwoTensors_SpecialValues
- System.Numerics.Tensors.Tests.IntPtrGenericTensorPrimitives.MultiplyAdd_TensorTensorScalar_InPlace
... ...
net9.0-linux-Release-x64-CoreCLR_checked-jitminopts-Ubuntu.2204.Amd64.Open

- System.Numerics.Tensors.Tests.UIntPtrGenericTensorPrimitives.MaxMagnitude_TwoTensors_SpecialValues
- System.Numerics.Tensors.Tests.UIntPtrGenericTensorPrimitives.MinMagnitude_TwoTensors_SpecialValues
- System.Numerics.Tensors.Tests.UIntPtrGenericTensorPrimitives.MinMagnitude_TwoTensors_InPlace
- System.Numerics.Tensors.Tests.UIntPtrGenericTensorPrimitives.MaxMagnitude_TwoTensors_InPlace
- System.Numerics.Tensors.Tests.UIntPtrGenericTensorPrimitives.Min_TwoTensors_SpecialValues
... ...
net9.0-linux-Release-x64-CoreCLR_checked-jitstress1-Ubuntu.2204.Amd64.Open

- System.Numerics.Tensors.Tests.Int64GenericTensorPrimitives.Divide_TwoTensors_ByZero_Throws
- System.Numerics.Tensors.Tests.UInt64GenericTensorPrimitives.Divide_TwoTensors_InPlace
- System.Numerics.Tensors.Tests.UInt64GenericTensorPrimitives.Divide_TensorScalar
- System.Numerics.Tensors.Tests.UIntPtrGenericTensorPrimitives.Min_TwoTensors_SpecialValues
- System.Numerics.Tensors.Tests.UIntPtrGenericTensorPrimitives.Divide_TensorScalar_InPlace
... ...
net9.0-linux-Release-x64-CoreCLR_checked-jitstress1_tiered-Ubuntu.2204.Amd64.Open

- System.Numerics.Tensors.Tests.DoubleGenericTensorPrimitives.Min_TwoTensors_SpecialValues
- System.Numerics.Tensors.Tests.IntPtrGenericTensorPrimitives.MinMagnitude_TwoTensors_SpecialValues
- System.Numerics.Tensors.Tests.UInt64GenericTensorPrimitives.MinMagnitude_TwoTensors_InPlace
- System.Numerics.Tensors.Tests.IntPtrGenericTensorPrimitives.Min_TwoTensors_SpecialValues
- System.Numerics.Tensors.Tests.UInt64GenericTensorPrimitives.Negate_AllLengths
... ...
```
**Error message:**
```
Assert.All() Failure: 4 out of 256 items in the collection did not pass.
[3]: Item:  4
Error: Assert.Equal() Failure: Values differ
Expected: 1579215652652062848
Actual:   -3690635635009759767
[4]: Item:  5
Error: Assert.Equal() Failure: Values differ
Expected: 1262741478833362244
Actual:   -950887324362334071
[5]: Item:  6
Error: Assert.Equal() Failure: Values differ
Expected: 2390979035222143809
Actual:   3708664934748602959
[6]: Item:  7
Error: Assert.Equal() Failure: Values differ
Expected: -3780711830439635657
Actual:   -1304740399604855863



Stack trace
   at System.Numerics.Tensors.Tests.TensorPrimitivesTests`1.MinMagnitude_TwoTensors_SpecialValues() in /_/src/libraries/System.Numerics.Tensors/tests/TensorPrimitivesTests.cs:line 1914
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by jakobbotsch** [comment] 2024-01-04 09:13
Duplicate of #96464

**Closed by jakobbotsch** 2024-01-04 09:13 UTC
Labels: area-System.Numerics.Tensors, os-linux, JitStress, arch-x64, untriaged
