### ISSUE TITLE
Backlog Clearing Strategy for System.Buffers, System.Numerics, System.Numerics.Tensors, System.Runtime, System.Runtime.Intrinsics

### ISSUE THREAD

**Issue by dakersnar** [dotnet/runtime#77119] opened 2022-10-17 16:58 UTC
This issue outlines the strategy we are currently employing to clean up the issue backlog in preparation for .NET 8. In general, we don't plan on using the backlog-cleanup-candidate tag, especially on older/stale issues. Instead, if appropriate, we will close issues with a note encouraging the author to reopen the issue as needed. 

# General strategy

We separate our issue backlog clearing strategy by label.

## api-suggestion
https://github.com/dotnet/runtime/issues?q=is%3Aopen+is%3Aissue+label%3Aarea-System.Buffers%2Carea-System.Numerics%2Carea-System.Numerics.Tensors%2Carea-System.Runtime%2Carea-System.Runtime.Intrinsics+label%3Aapi-suggestion

Number of issues: ~144

Status: Sorted into categories

We will sort these suggestions into specific categories, and handle categories differently. 
- Some suggestions we plan to shepherd to api-ready-for-review. 
- Some suggestions we plan to redo ourselves if the idea is good but the proposal needs an overhaul to match the api-suggestion guidelines.
- Some suggestions require follow-up from a specific team member outside the pod.
- Some suggestions are closed as "duplicate" with a note. 
- Some suggestions are closed as "not planned" with a note.

## api-needs-work
https://github.com/dotnet/runtime/issues?q=is%3Aopen+is%3Aissue+label%3Aarea-System.Buffers%2Carea-System.Numerics%2Carea-System.Numerics.Tensors%2Carea-System.Runtime%2Carea-System.Runtime.Intrinsics+label%3Aapi-needs-work

Number of issues: ~78

Status: TODO

We will follow a similar strategy as above, but more often leaning towards closing the issue while inviting people to pick it up again in a new issue if they would like to.

## api-ready-for-review
https://github.com/dotnet/runtime/issues?q=is%3Aopen+is%3Aissue+label%3Aarea-System.Buffers%2Carea-System.Numerics%2Carea-System.Numerics.Tensors%2Carea-System.Runtime%2Carea-System.Runtime.Intrinsics+label%3Aapi-ready-for-review

Number of issues: ~10

Status: Done

Issues with this label do not need to be cleaned up, as they have already been deemed worthy of API review.

## api-approved
https://github.com/dotnet/runtime/issues?q=is%3Aopen+is%3Aissue+label%3Aarea-System.Buffers%2Carea-System.Numerics%2Carea-System.Numerics.Tensors%2Carea-System.Runtime%2Carea-System.Runtime.Intrinsics+label%3Aapi-approved

Number of issues: ~30

Status: Done

Most issues with this label do not need to be cleaned up, as we have already approved them. Some are candidates for inclusion in our .NET 8 plans while some remain in our Future backlog. As our .NET 8 plans are refined, we will apply the '8.0.0' and 'Future' milestones accordingly.

## everything else (non-api issues)
 https://github.com/dotnet/runtime/issues?q=is%3Aopen+is%3Aissue+label%3Aarea-System.Buffers%2Carea-System.Numerics%2Carea-System.Numerics.Tensors%2Carea-System.Runtime%2Carea-System.Runtime.Intrinsics+-label%3Aapi-approved+-label%3Aapi-needs-work+-label%3Aapi-ready-for-review+-label%3Aapi-suggestion
 
Number of issues: ~332

Status: TODO

Most of these issues fall into two categories. Here is how we will handle each:
- Bugs
    - All bugs should be kept open, unless they are duplicates of other issues
- Unpolished "API suggestions"
    - A lot of these have potential to be sculpted into a proper api-suggestion but require more work from the author or us.
    - For issues that we don't have resources for, aren't fleshed out enough, not properly designed, we will close with a note like: "Thanks for your suggestion, there aren’t enough details here, but if you would like to push this further feel free to open an API suggestion following our guidelines."
    - Some of these suggestions will be interesting enough to create a formal api-suggestion ourselves. These issues will be left open with a note: "We plan on putting up a proper API proposal ourselves."
		
# Timeline
This process has been in the works for about a month, and we plan on finishing by the end of October/early November.
	
# Area-specific notes

## System.Runtime
This area is very broad, and has a variety of contributors. Clearing this backlog often involves reaching out to the appropriate contributor to get opinions on individual issues.

**Comment by dakersnar** [comment] 2022-10-17 17:01
@tannergooding @michaelgsharp feel free to make direct edits to this as needed. cc @jeffhandley as well.

**Comment by dakersnar** [comment] 2022-10-17 23:28
Thanks for the feedback. Your first point I definitely agree with. Your second point makes sense to me, but I'll let Tanner weigh in before I change it.

**Comment by GSPP** [comment] 2022-10-18 18:34
> Instead, if appropriate, we will close issues with a note encouraging the author to reopen the issue as needed.

Will reopening be possible? It seems that issues become permanently closed after some time. Reopening would require creating a new issue with the same content. Most contributors would not do that since they would interpret the original closure as the "final word" by the team. Nobody wants to cause noise or annoy people. Even if reopening is possible, doing that just to signal interest would seem inappropriate.

Maybe there needs to be a differentiation between "we will never do this" and "not now or not in this form".

We just had such a case with the directory copy feature (https://github.com/dotnet/runtime/issues/60903). The team will not pursue this right now because it is undecided what form the feature would take. But closing this issue would signal that the very concept of copying a directory has been permanently rejected.

**Comment by tannergooding** [comment] 2022-10-24 17:12
> It's OK (and encouraged) to close bugs that aren't commonly encountered, cannot be reproduced, have low impact (especially relative to the cost/risk involved)

The intent/implication is that no bug should be closed without due diligence. That is, we should be asking for more details if not enough are provided, we should be trying to reproduce the issue and closing it specifically as "no repro" if we cannot reproduce, or we should be closing it as effectively "by design" if its an issue where the risk or other complications make it such that we will never take a fix.

**Comment by dakersnar** [comment] 2022-10-31 22:27
@GSPP Thanks for the notes. I think our goal will be to clearly and explicitly point users towards follow-up actions via the closing comment. 

> Will reopening be possible? It seems that issues become permanently closed after some time. Reopening would require creating a new issue with the same content. Most contributors would not do that since they would interpret the original closure as the "final word" by the team. Nobody wants to cause noise or annoy people. Even if reopening is possible, doing that just to signal interest would seem inappropriate.

This is a great point, and if we go with the above outlined approach, we will have to make sure the closing comment explicitly encourages users to request the issue be reopened if appropriate. Hopefully this will help reduce the negative feelings you outlined that can come with challenging the closing of an issue.

> Maybe there needs to be a differentiation between "we will never do this" and "not now or not in this form".

I think we definitely plan on being specific when we close issues to make that differentiation. Depending on our diagnosis, we will point users towards appropriate follow-up actions which could include one or more of:
- Requesting the issue be reopened
- Creating a discussion thread
- Creating a new (usually more formal) issue that addresses our feedback

**Comment by GSPP** [comment] 2022-11-03 17:26
> make sure the closing comment explicitly encourages users to request the issue be reopened if appropriate

The issue of demand is a question of "how much". If users have to request a reopening (by comment), then it would take quite a few comments to lead to a critical mass that would justify a reopening. This would cause a lot of noise. Then, users would likely reason in the same way in that they don't want to cause noise and will, therefore, abstain from commenting in the first place.

This looks like a voting problem to me. In the past, this issue tracker has supported voting through the built-in GitHub 👍 reaction. After following this issue tracker for many years now as an interested enthusiast I find this to work well to express interest. There usually are two kinds of issues: a) close to zero votes for niche features or infeasible proposals, b) dozens of votes, hearts, rockets and so on.

Unfortunately, issue closure seems to lead to issue locking which then disables voting. And this leads to that unfortunate state where any expression of user interest has become practically infeasible.

Under the new rules, how would the directory copy feature (https://github.com/dotnet/runtime/issues/60903) be handled?

**Comment by dakersnar** [comment] 2022-11-03 19:49
These are all good points. We will evaluate API suggestions on a case-by-case basis and leave open the ones that are both well-formed and popular. But at the end of the day, the backlog is too large to ever reasonably be handled, so we have to proceed with some degree of pickiness. Your example would definitely fall into the "leave this open" category. The kind of proposals we are likely to close are issues that do not conform to our API suggestion guidelines, are duplicates, need a complete overhaul, are not planned, etc.

FWIW I think the original wording above for `api-suggestion` and `api-needs-work` reflects this flexibility.

**Comment by jeffhandley** [comment] 2023-10-24 20:19
This can be closed. The issue serves the purpose of declaring our backlog cleaning strategy, and backlog refinement is an ongoing activity hereafter.

**Closed by jeffhandley** 2023-10-24 20:19 UTC
Labels: area-Meta
