### ISSUE TITLE
System.Net.Http.dll test failures: unable to compile method / assembly:<unknown assembly> type:<unknown type> member:(null)'

### ISSUE THREAD

**Issue by layomia** [dotnet/runtime#57180] opened 2021-08-10 23:43 UTC
Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1284333&view=results

**Comment by ManickaP** [comment] 2021-08-11 07:09
This is dupe of https://github.com/dotnet/runtime/issues/57010 that's been addressed in https://github.com/dotnet/runtime/pull/57011
This should already be somewhat fixed in main and the proper fix is worked on.

**Closed by ManickaP** 2021-08-11 07:09 UTC
Labels: area-System.Net.Http, untriaged
