### ISSUE TITLE
The performance of java is almost twice that of C#

### ISSUE THREAD

**Issue by sukney** [dotnet/runtime#78691] opened 2022-11-22 09:24 UTC
JAVA CODE：
```java
long start = System.currentTimeMillis(); 
int[][] array = new int[10000][10000]; 
for (int row = 0; row < array.length; row++) {
 for (int col = 0; col < array[row].length; col++) { 
array[row][col] = col + 1;
 }
 }
 long end = System.currentTimeMillis();
 System.out.println(String.format("阵列创建耗时:%d", end - start));
 start = System.currentTimeMillis();
 long total = 0; for (int row = 0; row < array.length; row++) {
 for (int col = 0; col < array[row].length; col++) { 
total += array[row][col]; 
} } 
end = System.currentTimeMillis(); 
System.out.println(String.format("运算结果:%d", total)); 
System.out.println(String.format("运算耗时:%d", end-start));
```
.net CODE：
```csharp
 const int arrLength = 10000;
    Stopwatch sw = new Stopwatch();
    long start = Environment.TickCount;
    int[,] arr = new int[arrLength, arrLength];
    for (int row = 0; row < arrLength; row++)
    {
        for (int col = 0; col < arrLength; col++)
        {
            arr[row, col] = col + 1;
        }
    }
    long end = Environment.TickCount;
    TimeSpan ts = sw.Elapsed;
    Console.WriteLine(String.Format("阵列创建耗时:{0}", end - start));
    start = Environment.TickCount;
    long total = 0;
    for (int row = 0; row < arrLength; row++)
    {
        for (int col = 0; col < arrLength; col++)
        {
            total += arr[row, col];
        }
    }
    end = Environment.TickCount;
    Console.WriteLine(String.Format("运算结果:{0}", total));
    Console.WriteLine(String.Format("运算耗时:{0}", end - start));
```

**Comment by jakobbotsch** [comment] 2022-11-22 11:03
Note that the C# and Java examples are not equivalent since the Java example uses jagged arrays and the C# example uses multi-dimensional arrays. How do they compare if you use jagged arrays in C# too?

The poor performance for MD arrays can probably be considered a duplicate of #71674 (it should be solved by that).

**Comment by hrrrrustic** [comment] 2022-11-22 11:24
Btw `Stopwatch` and `ts` are unused

**Comment by MichalPetryka** [comment] 2022-11-22 13:49
@george-polevoy You should use .Length instead of ArrLength so that the JIT can fully optimize things.

**Comment by hez2010** [comment] 2022-11-22 15:38
Also note that you cannot just use Stopwatch to evaluate the performance. 
.NET has tiered compilation so a method will be first quick-jitted to unoptimized tier-0 code, and then be re-jited to optimized tier-1 code after several times of execution. Tier-0 and tier-1 code have huge performance difference. 
To evaluate the accurate performance, you will need to use BenchmarkDotNet.

**Closed** 2022-12-31 06:01 UTC
Labels: tenet-performance, area-CodeGen-coreclr, untriaged, no-recent-activity, needs-author-action
