### ISSUE TITLE
MetadataLoadContext: Custom attribute enum argument parsing fails for non-core System.Enum-derived type because IsEnum is false

### ISSUE THREAD

**Issue by IS4Code** [dotnet/runtime#98658] opened 2024-02-19 14:16 UTC
### Description

When a `MetadataLoadContext` is used to load a core .NET assembly (such as mscorlib.dll) that is *not* used as its `CoreAssembly`, it will report `IsEnum` incorrectly for enums because they derive from the local assembly's definition of `System.Enum` and not from the original core one's (same goes for `IsValueType`).

As a result, parsing enum arguments of a custom attribute defined in such an assembly results in an exception due to the type not being recognized as an enum.

### Reproduction Steps

```cs
var context = new MetadataLoadContext(new Resolver(), "System.Runtime");
var path = Environment.ExpandEnvironmentVariables(@"%ProgramFiles(x86)%\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\mscorlib.dll");
var mscorlib = context.LoadFromAssemblyPath(path);
foreach(var attr in mscorlib.GetCustomAttributesData())
{
    Console.WriteLine(attr.Constructor);
    Console.WriteLine(attr.ConstructorArguments.Count);
}

class Resolver : MetadataAssemblyResolver
{
    public override Assembly? Resolve(MetadataLoadContext context, AssemblyName assemblyName)
    {
        if(assemblyName.Name == "System.Runtime")
        {
            return context.LoadFromAssemblyPath(typeof(object).Assembly.Location);
        }
        return null;
    }
}
```

### Expected behavior

Code runs without an exception.

### Actual behavior

Fails at `System.Void .ctor(System.Diagnostics.DebuggableAttribute+DebuggingModes)`:
```
ArgumentException: Type provided must be an enum.
   at System.Reflection.TypeLoading.Ecma.EcmaDefinitionType.ComputeEnumUnderlyingType()
   at System.Reflection.TypeLoading.RoType.GetEnumUnderlyingType()
   at System.Reflection.TypeLoading.Ecma.EcmaHelpers.GetEnumUnderlyingPrimitiveTypeCode(Type enumType, MetadataLoadContext loader)
   at System.Reflection.Metadata.Ecma335.CustomAttributeDecoder`1.DecodeFixedArgumentType(BlobReader& signatureReader, BlobReader genericContextReader, Boolean isElementType)
   at System.Reflection.Metadata.Ecma335.CustomAttributeDecoder`1.DecodeFixedArguments(BlobReader& signatureReader, BlobReader& valueReader, Int32 count, BlobReader genericContextReader)
   at System.Reflection.Metadata.Ecma335.CustomAttributeDecoder`1.DecodeValue(EntityHandle constructor, BlobHandle value)
   at System.Reflection.TypeLoading.Ecma.EcmaCustomAttributeData.LoadArguments()
   at System.Reflection.TypeLoading.Ecma.EcmaCustomAttributeData.get_ConstructorArguments()
```

### Known Workarounds

`IsEnum` and `IsValueType` being false can be circumvented in user code by not using those properties and instead just checking the base type, but when its value is to be parsed (in custom attributes or field/parameter values), it is not possible to fix it externally.

### Configuration

[MetadataLoadContext v8.0.0](https://www.nuget.org/packages/System.Reflection.MetadataLoadContext/8.0.0)

### Other information

One way to fix this issue is to make `IsEnum` and `IsValueType` not depend on the core definitions of `System.ValueType` and `System.Enum` and instead check only its name, similarly to how tools like ildasm do it. In that case, it would be fixed here:

https://github.com/dotnet/runtime/blob/eeadd653e1982d7037a93a9ab38129c07336e7db/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/Types/RoType.TypeClassification.cs#L45-L67

Another option is to make `ComputeEnumUnderlyingType` (or any code that requires `IsEnum` or `IsValueType`) not fail for not-quite-enum types, in which case the change would be here:

https://github.com/dotnet/runtime/blob/eeadd653e1982d7037a93a9ab38129c07336e7db/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/Types/Ecma/EcmaDefinitionType.cs#L100-L125

**Comment by steveharter** [comment] 2024-02-28 21:16
> it will report IsEnum incorrectly for enums because they derive from the local assembly's definition of System.Enum and not from the original core one's (same goes for IsValueType).

If that is the case, then yes that is a bug. Moving to 9.0.

**Comment by MichalStrehovsky** [comment] 2024-03-21 20:51
> > it will report IsEnum incorrectly for enums because they derive from the local assembly's definition of System.Enum and not from the original core one's (same goes for IsValueType).
> 
> If that is the case, then yes that is a bug. Moving to 9.0.

I don't think this is a bug. It's not possible to reason about types with a mismatched core assembly.

If you replace the foreach loop in the reproduction steps with `Console.WriteLine(mscorlib.GetType("System.Int32").IsValueType);` it will print false. A type cannot derive from a random type named `System.Enum` or `System.ValueType` to be an enum/value type. It needs to derive from the one in the core assembly.

**Comment by IS4Code** [comment] 2024-03-22 00:18
It is not a random type named `System.Enum` or `System.ValueType` ‒ it is *the* `System.Enum` or `System.ValueType`... just not in the core assembly. Arguably I am not sure what the proper condition should be, but I feel there ought to be *some* distinction to take use of. And even if `IsEnum` stayed being `false` (I am somewhat okay with that), using such a type in an enum should not lead to an exception, since, it is, fundamentally, still an enum and all information that is needed to use it like an enum is there.

**Comment by MichalStrehovsky** [comment] 2024-03-22 05:11
> It is not a random type named `System.Enum` or `System.ValueType` ‒ it is *the* `System.Enum` or `System.ValueType`... just not in the core assembly.

How about this one?

```csharp
using System.Reflection;
using System;
using System.IO;

var context = new MetadataLoadContext(
    new PathAssemblyResolver(
        Directory.EnumerateFiles(Path.Combine(Path.GetDirectoryName(typeof(object).Assembly.Location)), "*.dll")),
        "mscorlib");
var thisProgram = context.LoadFromAssemblyPath(Assembly.GetExecutingAssembly().Location);

Console.WriteLine(thisProgram.GetType("IsThisEnum").IsEnum);

class IsThisEnum : Enum { }

namespace System
{
    class ValueType { }
    class Enum : ValueType { }
}
```

This is not an enum because it doesn't derive from the correct `System.Enum` that doesn't derive from the correct `System.ValueType`. This example at least has a correct `System.Object` (because here is just one core assembly), but the repro steps in the top post differ even in `System.Object` (one is a class in the assembly of the runtime that executes the program, the other is from the reference assembly).

It's not valid to mix core assemblies from two different places. The only way to win is to only load a single core library.

**Comment by MichalStrehovsky** [comment] 2024-03-25 12:44
> That is a good point, yet there are tools that have precisely this behaviour, such as ildasm:

ILDASM shows a different icon, but this has no effect on its operations. An icon can be a best effort thing. ILDASM can't do any better because it needs to operate without a core assembly and at that point one only has a name. `MetadataLoadContext` provides services that require core assembly, it's not possible to construct it without providing it.

> the type is valid, is used legitimately as an enum with a valid encoding

It's an enum in an alternate universe. This type would not be `Type.IsAssignableFrom` `System.Enum` (or even `System.Object`). The problem is that `MetadataLoadContext` allowed a different core library to load. Maybe if it detects there's a possibility of having two `System.Object` with no base type, it should abort the assembly load because things start to make no sense at that point.

**Comment by IS4Code** [comment] 2024-03-25 13:11
> ILDASM shows a different icon, but this has no effect on its operations. An icon can be a best effort thing. ILDASM can't do any better because it needs to operate without a core assembly and at that point one only has a name.

Well it's not just the icon, but also `.class value` and `.class enum`, but that is just a detail.

> It's an enum in an alternate universe. This type would not be Type.IsAssignableFrom System.Enum (or even System.Object).

There is no need to change that. The only change would be for `MetadataLoadContext` to objectively decide that in such an alternate universe, the type might be usable as an enum, don't throw an artificial exception in such a case, and at least *try* to accept it in a position where a "real" enum would be accepted. There is no need for `MetadataLoadContext` to reject the type outright, and it would only take a change in `ComputeBaseTypeClassification()` (specifically, to be backwards-compatible, there would probably be a `ComputeBaseTypeClassificationRestrictive()` with the original behaviour, and `ComputeBaseTypeClassificationPermissive()` that just checks the name of the base type.

There is no need to report *anything* differently, aside from not throwing an exception and just going with the "enum-like" type a little bit longer.

> Maybe if it detects there's a possibility of having two System.Object with no base type, it should abort the assembly load because things start to make no sense at that point.

Please no. Loading these assemblies is otherwise fine, with only this unreasonable exception causing troubles.

**Comment by MichalStrehovsky** [comment] 2024-03-25 14:50
> Well it's not just the icon, but also `.class value` and `.class enum`, but that is just a detail.

Yes, it shows correctly as `.class private auto ansi beforefieldinit IsThisEnum` if you double click it or disassemble to file. `.class enum` is just "trying to be helpful", like the icon. It would be a bug if it didn't do it.

> Please no. Loading these assemblies is otherwise fine, with only this unreasonable exception causing troubles.

It only works fine because this use case is not actually doing much with the mismatched assembly. Why is it not possible to just set the correct core assembly?

**Comment by IS4Code** [comment] 2024-03-25 15:46
> It only works fine because this use case is not actually doing much with the mismatched assembly. Why is it not possible to just set the correct core assembly?

In my situation I am using `MetadataLoadContext` to parse an arbitrary assembly and do analysis on it (including serializing information found in custom attributes). The analysis goes deep, to every nested type, method, property, field etc. I need to provide a default core assembly (although I would welcome not having to, since preferably the assembly should be analyzed in isolation), and I need to be able to accept any arbitrary assembly.

I do not know prior to loading an assembly whether it might be core or non-core. I can see a possible workaround by using heuristics to treat it as a core assembly directly (no references, presence of some relevant core types etc.), but I would much more appreciate not having to parse the assembly twice just to get rid of an exception when reading custom attributes.

**Comment by steveharter** [comment] 2024-03-28 14:43
> I do not know prior to loading an assembly whether it might be core or non-core. 

A fairly safe bet is to check for the well-known assembly names:
- "System.Runtime" (.NET Core)
- "mscorlib" (.NET Framework)
-  "netstandard" (when targeting both .NET Core and .NET Framework).

Another approach is to check whether the assembly declares `System.Object`.

**Comment by steveharter** [comment] 2024-03-28 15:01
Based on the feedback above, changing semantics to accommodate this scenario (having a core assembly specified + supporting one or more unspecified cores) is not desired since it will give the false impression that this scenario is fully supported when there will be other unknown and untested edge cases. So even if we change to support `Type.IsEnum` and `Type.IsValueType`, there will be other issues, as there are issues today when no core assembly is specified. For example: https://github.com/dotnet/runtime/blob/78c2c98950534457424a65c6182e816a703ed2b1/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/MetadataLoadContext.Apis.cs#L236-L247
- https://github.com/dotnet/runtime/blob/e612bf4d0b6f08623092902c34a504e932388664/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/General/Ecma/EcmaHelpers.cs#L59-L78
- https://github.com/dotnet/runtime/blob/e612bf4d0b6f08623092902c34a504e932388664/src/libraries/System.Reflection.MetadataLoadContext/src/System/Reflection/TypeLoading/CustomAttributes/CustomAttributeHelpers.cs#L86-L100

**Closed by steveharter** 2024-03-28 15:01 UTC
Labels: bug, area-System.Reflection, help wanted, in-pr
