### ISSUE TITLE
Using File.ReadLines with Enumerable.Concat results in undisposed Stream

### ISSUE THREAD

**Issue by Levi--G** [dotnet/runtime#51219] opened 2021-04-14 08:49 UTC
### Description

Using System.IO.File.ReadLines as the second IEnumerable in a System.Linq.Enumerable.Concat where a selection only results in iterating the first collection, the Stream used to read the file is never disposed.

Minimum to reproduce:
```cs
var path = "test.txt";
//Create test file
File.WriteAllText(path, "test");
//test access = ok
using (var s = File.Open(path, FileMode.OpenOrCreate, FileAccess.ReadWrite, FileShare.None)) { }
//The problem case:
var a = Enumerable.Repeat("", 1).Concat(File.ReadLines(path)).FirstOrDefault();
//This will throw with a file in use exception:
using (var s = File.Open(path, FileMode.OpenOrCreate, FileAccess.ReadWrite, FileShare.None)) { }
```
The problem lies with the ReadLines creating the stream in the constructor rather than when starting to iterate and the Concat only disposes IEnumerables it has begun iterating, thus leaving the ReadLines undisposed if the second collection never started to iterate. This is not clear from the documentation and in my opinion should not happen.

### Configuration

Tested on .NET core 3.1 and .NET 5
Tested on Windows 10, x64
Unless i am mistaken it is not specific to this configuration dealing only with managed classes

### Regression?

I can't say for certain if this is a regression or not, might need more investigation.

### Other information

Possible (but not pretty) workaround would be manually disposing the Iterator:
```cs
var e = File.ReadLines(path);
var a = Enumerable.Repeat("", 1).Concat(e).FirstOrDefault();
(e as IDisposable).Dispose();
```

Thank you for your time.

**Comment by stephentoub** [comment] 2021-04-14 10:45
It's not a regression. This has always been an issue with File.ReadLines since it was introduced in .NET Framework 4.0.  The API purposefully violates guidelines around enumer**ators** rather than enumer**ables** wrapping disposable resources, opening the specified file as part of the ReadLines call rather than as part of calling GetEnumerator on the returned enumerable.  Enumerators are disposable, enumerables are not, which means if you don't enumerate the returned enumerable, you end up not closing the file until it's eventually GC'd and a finalizer is run to close the file.  If memory serves, this design was employed to throw any file-related exceptions as part of the ReadLines call, and it was decided the overall experience with that was better than these downsides.

**Comment by Levi--G** [comment] 2021-04-14 11:13
Interesting, so how would one correctly use use ReadLines with Linq then not knowing if it would be disposed or not then? Because the IEnumerable it returns needs to be disposed but needs to be casted to IDisposable before it can be disposed, not making it very clear its required? Maybe a note in the docs could clear this up?

**Comment by Levi--G** [comment] 2021-04-14 11:25
Doesn't this then also mean that the whole idea behind IEnumerables is ignored? I thought IEnumerables were a type of query that only executed when an item was actually requested. So if i'd make a query with ReadLines (or multiple) and decide later in the process i only need one or none at all it would already be too late and the files are already opened even though i never actually needed to open any? This actually blows my mind cause i always thought queries when not enumerated would never actually do anything and could just be ignored. guess i need to be more careful in the future of what happens underneath the apis. Maybe a bit offtopic but this makes me curious if you know other apis that do the same?

**Comment by stephentoub** [comment] 2021-04-19 01:16
> This actually blows my mind cause i always thought queries when not enumerated would never actually do anything

This isn't about the "query" that processes the result of ReadLines.  It's about the File.ReadLines method itself, which is opening the file before it gives you the enumerable.  As I noted, it's doing so in order to make sure that the enumerable that's handed back is targeting a file that's known to exist, known to be readable, etc.  I don't agree with the design, but it was very much an explicit choice to do it this way, with the decision being that it was the lesser evil, and it's been this way since it was initially introduced.  I don't see it changing.

**Comment by Jozkee** [comment] 2021-06-16 17:53
Closing as expected behavior.

**Closed by Jozkee** 2021-06-16 17:53 UTC
Labels: area-System.IO
