### ISSUE TITLE
Visibility checking seems insconsistent if Profiler is attached.

### ISSUE THREAD

**Issue by weidingerhp** [dotnet/runtime#43025] opened 2020-10-05 11:57 UTC
### Description
Had a problem with a .netcore2.2 app that behaved differently as soon as any profiler was attached.

Namely an Error indicating that "NullScope" from Microsoft.Extensions.Logging.Abstractions was missing.
The problem appears that in that particular app the Logging.Abstractions version 3.1 (where NullScope is internal) 
and a 2.2 Version of Logging was used.

when started normally (dotnet app.dll) the application runs without any problem. But:
- if a profiler is attached
- if the app is built self-contained
i get a TypeLoadException.

Besides that this is obviously a faulty configuration i assume that this should consistently fail.

Many thanks in advance

### Configuration
see attached reproducer
[test.dependencyverification.zip](https://github.com/dotnet/runtime/files/5327154/test.dependencyverification.zip)

### Other information
Reproducer is attached. Just try to run it normally and run it with e.g. the JetBrains dotTrace or any other profiler.
see [test.dependencyverification.zip](https://github.com/dotnet/runtime/files/5327154/test.dependencyverification.zip)

**Comment by josalem** [comment] 2020-10-05 22:05
CC @davmason @dotnet/dotnet-diag

**Comment by davmason** [comment] 2020-10-14 21:35
Hi @weidingerhp,

have you engaged with the JetBrains team about the failure? Profilers generally modify the process pretty thoroughly, so the issue is likely not a runtime issue. If you have further evidence that it is runtime related I can dig in deeper

**Comment by davmason** [comment] 2020-11-13 20:47
Closing this, if you have any further information feel free to reopen

**Closed by davmason** 2020-11-13 20:47 UTC
Labels: area-Diagnostics-coreclr

**Comment by weidingerhp** [comment] 2020-11-25 18:29
Sorry about the late answer @davmason - did not see your comment at first.

No - did not engage the JetBrains Team. This problem also happens with the dynatrace-agent active. Unfortunately i did not have more profilers to test this.

The thing that worries me a little is that the app should also not work if the profiler is not involved - but it does work. (NullScope is also not visible if no profiler is attached - but in that case the CLR does not care)

I assume that JIT behaves differently or is not involved at all (Native Images) if no profiler is attached.

**Comment by weidingerhp** [comment] 2020-11-25 18:36
btw - it seems like i took to long - can't re-open this issue :)

**Comment by sdmaclea** [comment] 2020-11-25 19:08
I guess it is not clear to me why the app should fail if no profiler was attached.  

What you describe sounds like a JetBrains profiler bug when profiling a .NET Core 2.2 app.  I can reopen the issue, but unless there is something to suggest this is a runtime issue, you should engage the JetBrains developers

**Comment by weidingerhp** [comment] 2020-11-26 09:57
Hi @sdmaclea ,

The app should fail because it accesses an internal class in another assembly.

I think its more a problem that JIT is forced by an attached profiler. I don't think its a bug from the profiler.
I will try if i can reconstruct this by generating native-images. I think that this could explain the behavior.

In the meantime thanks for your responses

**Comment by davmason** [comment] 2020-12-01 00:45
@weidingerhp if you set the environment variable COMPlus_ReadyToRun=0 then you can force the runtime to only JIT code and ignore all pre-generated code

**Comment by weidingerhp** [comment] 2020-12-02 08:31
@davmason thanks for the info - will try.

**Comment by weidingerhp** [comment] 2020-12-02 09:00
@davmason Yes - setting the "COMPlus_ReadyToRun=0" Environment does also reproduce the issue.

As soon as i set "COMPlus_ReadyToRun" to 1 or remove it it works again.
