### ISSUE TITLE
Test failure GC/Scenarios/ServerModel/servermodel/servermodel.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#59611] opened 2021-09-26 01:11 UTC
Run: [runtime-coreclr outerloop 20210924.10](https://dev.azure.com/dnceng/public/_build/results?buildId=1385743&view=ms.vss-test-web.build-test-results-tab&runId=40359490&resultId=110845&paneView=debug)

Failed test:
```

CoreCLR Linux arm64 Checked no_tiered_compilation @ (Alpine.312.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.12-helix-arm64v8-20200602002604-25f8a3e

- GC/Scenarios/ServerModel/servermodel/servermodel.sh

```
**Error message:**
```
Assert failure(PID 3277 [0x00000ccd], Thread: 3277 [0x0ccd]): m_alignpad == 0
File: /__w/1/s/src/coreclr/vm/syncblk.cpp Line: 2952
Image: /root/helix/work/correlation/corerun

/root/helix/work/workitem/e/GC/Scenarios/ServerModel/servermodel/servermodel.sh: line 384:  3277 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/GC.Scenarios/ServerModel/servermodel/servermodel.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false servermodel.dll '/numrequests:100'
Using -680952688 as random seed
Gathering state for process 3277 corerun
Crashing thread 00000ccd signal 00000006
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.3277.dmp
Written 1117114368 bytes (272733 pages) to core file
Dump successfully written
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/e/GC/Scenarios/ServerModel/servermodel/servermodel.sh
Expected: True
Actual:   False


Stack trace
   at GC_Scenarios._ServerModel_servermodel_servermodel_._ServerModel_servermodel_servermodel_sh()
```

**Comment by VincentBu** [comment] 2021-11-17 01:10
Failed again in: [runtime-coreclr outerloop 20211116.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1471657&view=ms.vss-test-web.build-test-results-tab&runId=42204718&resultId=110546&paneView=debug)

Failed test:
```
R2R-CG2 Linux arm64 Checked no_tiered_compilation @ (Alpine.314.Arm64.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm64v8-20210910135810-8a6f4f3

- GC/Scenarios/ServerModel/servermodel/servermodel.sh

```
**Error message:**
```
rm: cannot remove 'IL-CG2/composite-r2r.dll': No such file or directory
/root/helix/work/workitem/e/GC/Scenarios/ServerModel/servermodel/servermodel.sh: line 260: -r:/root/helix/work/workitem/e/GC/Scenarios/ServerModel/servermodel/IL-CG2/*.dll: No such file or directory
rm: cannot remove '/root/helix/work/workitem/e/GC/Scenarios/ServerModel/servermodel/servermodel.dll.rsp': No such file or directory

Assert failure(PID 17825 [0x000045a1], Thread: 17825 [0x45a1]): m_alignpad == 0
File: /__w/1/s/src/coreclr/vm/syncblk.cpp Line: 2952
Image: /root/helix/work/correlation/corerun

/root/helix/work/workitem/e/GC/Scenarios/ServerModel/servermodel/servermodel.sh: line 384: 17825 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/GC.Scenarios/ServerModel/servermodel/servermodel.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/root/helix/work/workitem/e/GC/Scenarios/ServerModel/servermodel/IL-CG2/servermodel.dll
Response file: /root/helix/work/workitem/e/GC/Scenarios/ServerModel/servermodel/servermodel.dll.rsp
/root/helix/work/workitem/e/GC/Scenarios/ServerModel/servermodel/IL-CG2/servermodel.dll
-o:/root/helix/work/workitem/e/GC/Scenarios/ServerModel/servermodel/servermodel.dll
-r:/root/helix/work/correlation/System..dll
-r:/root/helix/work/correlation/Microsoft..dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--targetarch:arm64
-O
Running CrossGen2:  dotnet /root/helix/work/correlation/crossgen2/crossgen2.dll @/root/helix/work/workitem/e/GC/Scenarios/ServerModel/servermodel/servermodel.dll.rsp

Emitting R2R PE file: /root/helix/work/workitem/e/GC/Scenarios/ServerModel/servermodel/servermodel.dll
in ReleaseLock
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false servermodel.dll '/numrequests:100'
Using -1403702577 as random seed
Gathering state for process 17825 corerun
Crashing thread 000045a1 signal 00000006
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.17825.dmp
Written 1131290624 bytes (276194 pages) to core file
Dump successfully written
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/e/GC/Scenarios/ServerModel/servermodel/servermodel.sh
Expected: True
Actual:   False


Stack trace
   at GC_Scenarios._ServerModel_servermodel_servermodel_._ServerModel_servermodel_servermodel_sh()
```

**Comment by VincentBu** [comment] 2022-01-17 02:15
Failed again in: [ runtime 20220116.15](https://dev.azure.com/dnceng/public/_build/results?buildId=1555955&view=ms.vss-test-web.build-test-results-tab&runId=43869284&paneView=debug&resultId=102878)

Failed test:
```
CoreCLR Linux x64 Checked @ Ubuntu.1804.Amd64.Open

- GC/Scenarios/ServerModel/servermodel/servermodel.sh

```
**Error message:**
```
/datadisks/disk1/work/B4A5099C/w/B36D0978/e/GC/Scenarios/ServerModel/servermodel/servermodel.sh: line 424: 21085 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /datadisks/disk1/work/B4A5099C/w/B36D0978/uploads/Reports/GC.Scenarios/ServerModel/servermodel/servermodel.output.txt
Raw output:
BEGIN EXECUTION
/datadisks/disk1/work/B4A5099C/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false servermodel.dll '/numrequests:100'
Using -1111126069 as random seed
took 512 iteration to reach steady state
937 reqs/sec
360 reqs/sec
Gathering state for process 21085 corerun
Crashing thread 0000526a signal 00000005
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.21085.dmp
Written 1563123712 bytes (381622 pages) to core file
Dump successfully written
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/datadisks/disk1/work/B4A5099C/p
/datadisks/disk1/work/B4A5099C/w/B36D0978/e/GC/Scenarios/ServerModel/servermodel/servermodel.sh
Expected: True
Actual:   False


Stack trace
   at GC_Scenarios._ServerModel_servermodel_servermodel_._ServerModel_servermodel_servermodel_sh()
```

**Comment by VincentBu** [comment] 2022-03-15 00:54
Failed again in: [runtime-coreclr outerloop 20220314.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1662502&view=ms.vss-test-web.build-test-results-tab&runId=45745890&resultId=110255&paneView=debug)

Failed test:
```
R2R-CG2 Linux arm64 Checked no_tiered_compilation @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- GC/Scenarios/ServerModel/servermodel/servermodel.sh

```
**Error message:**
```
rm: cannot remove 'IL-CG2/composite-r2r.dll': No such file or directory
/root/helix/work/workitem/e/GC/Scenarios/ServerModel/servermodel/servermodel.sh: line 260: -r:/root/helix/work/workitem/e/GC/Scenarios/ServerModel/servermodel/IL-CG2/*.dll: No such file or directory
rm: cannot remove '/root/helix/work/workitem/e/GC/Scenarios/ServerModel/servermodel/servermodel.dll.rsp': No such file or directory

Assert failure(PID 9415 [0x000024c7], Thread: 9415 [0x24c7]): global_regions_to_decommit[kind].get_num_free_regions() == num_regions_to_decommit_before + (size_t)num_regions_to_decommit[kind]
File: /__w/1/s/src/coreclr/gc/gc.cpp Line: 12432
Image: /root/helix/work/correlation/corerun

apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f9a30cff8)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f9a30cff8)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0x7f9a302070)
/root/helix/work/workitem/e/GC/Scenarios/ServerModel/servermodel/servermodel.sh: line 384:  9415 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/GC.Scenarios/ServerModel/servermodel/servermodel.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/root/helix/work/workitem/e/GC/Scenarios/ServerModel/servermodel/IL-CG2/servermodel.dll
Response file: /root/helix/work/workitem/e/GC/Scenarios/ServerModel/servermodel/servermodel.dll.rsp
/root/helix/work/workitem/e/GC/Scenarios/ServerModel/servermodel/IL-CG2/servermodel.dll
-o:/root/helix/work/workitem/e/GC/Scenarios/ServerModel/servermodel/servermodel.dll
-r:/root/helix/work/correlation/System..dll
-r:/root/helix/work/correlation/Microsoft..dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--targetarch:arm64
-O
Running CrossGen2:  dotnet /root/helix/work/correlation/crossgen2/crossgen2.dll @/root/helix/work/workitem/e/GC/Scenarios/ServerModel/servermodel/servermodel.dll.rsp

Emitting R2R PE file: /root/helix/work/workitem/e/GC/Scenarios/ServerModel/servermodel/servermodel.dll
in ReleaseLock
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false servermodel.dll '/numrequests:100'
Using 663511072 as random seed
took 964 iteration to reach steady state
315 reqs/sec
Gathering state for process 9415 corerun
Crashing thread 000024c7 signal 00000006
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.9415.dmp
Written 1100959744 bytes (268789 pages) to core file
Dump successfully written
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/e/GC/Scenarios/ServerModel/servermodel/servermodel.sh
Expected: True
Actual:   False


Stack trace
   at GC_Scenarios._ServerModel_servermodel_servermodel_._ServerModel_servermodel_servermodel_sh()
```

**Comment by mangod9** [comment] 2022-03-15 04:39
Dupe of https://github.com/dotnet/runtime/issues/66601

**Closed by mangod9** 2022-03-15 04:39 UTC
Labels: arch-arm64, os-linux, area-GC-coreclr, blocking-outerloop
