### ISSUE TITLE
DateTimeOffset.TryParse issue when machine local time zone has positive UTC offset

### ISSUE THREAD

**Issue by DavidKiff** [dotnet/runtime#41823] opened 2020-09-03 12:10 UTC
DateTimeOffset.TryParse("01-Jan-0001", DateTimeFormatInfo.InvariantInfo, DateTimeStyles.None, out var parsed1).Dump(); // False
DateTimeOffset.TryParse("01-Jan-0002", DateTimeFormatInfo.InvariantInfo, DateTimeStyles.None, out var parsed2).Dump(); // True
	
DateTimeOffset.TryParse("01-Jan-0001", out var parsed3).Dump(); // False
DateTimeOffset.TryParse("01-Jan-0002", out var parsed4).Dump(); // True
	
DateTime.TryParse("01-Jan-0001", out var parsed5).Dump(); // True
DateTime.TryParse("01-Jan-0002", out var parsed6).Dump(); // True

I expect all these to return true.  I have tried to reproduce in London, using en-SG and en-US as the UI culture but I can't.  

If I change the dates to Feb, it works too. 

Dump of the DateTimeFormatInfo.CurrentCulture:
`
<body>
  <div class="spacer">
    <table id="t1">
      <tr>
        <td class="typeheader" colspan="2">
          DateTimeFormatInfo<span class="fixedextenser">4</span>
        </td>
      </tr>
      <tr id="sum2">
        <td colspan="2" class="summary" style="">System.Globalization.DateTimeFormatInfo</td>
      </tr>
      <tr>
        <th class="member" title="System.String">AMDesignator</th>
        <td>AM</td>
      </tr>
      <tr>
        <th class="member" title="System.Globalization.Calendar">Calendar</th>
        <td>
          <table id="t3">
            <tr>
              <td class="typeheader" colspan="2">
                GregorianCalendar<span class="fixedextenser">4</span>
              </td>
            </tr>
            <tr id="sum4">
              <td colspan="2" class="summary" style="">System.Globalization.GregorianCalendar</td>
            </tr>
            <tr>
              <th class="member" title="System.Boolean">IsReadOnly</th>
              <td>
                <b>True</b>
              </td>
            </tr>
            <tr>
              <th class="member" title="System.DateTime">MinSupportedDateTime</th>
              <td>1/1/0001 12:00:00 AM</td>
            </tr>
            <tr>
              <th class="member" title="System.DateTime">MaxSupportedDateTime</th>
              <td>31/12/9999 11:59:59 PM</td>
            </tr>
            <tr>
              <th class="member" title="System.Globalization.CalendarAlgorithmType">AlgorithmType</th>
              <td>SolarCalendar</td>
            </tr>
            <tr>
              <th class="member" title="System.Globalization.GregorianCalendarTypes">CalendarType</th>
              <td>Localized</td>
            </tr>
            <tr>
              <th class="member" title="System.Int32[]">Eras</th>
              <td>
                <table id="t5">
                  <tr>
                    <td class="typeheader" colspan="1">
                      Int32[1] <span class="fixedextenser">4</span>
                    </td>
                  </tr>
                  <tr>
                    <td>1</td>
                  </tr>
                </table>
              </td>
            </tr>
            <tr>
              <th class="member" title="System.Int32">TwoDigitYearMax</th>
              <td>2029</td>
            </tr>
          </table>
        </td>
      </tr>
      <tr>
        <th class="member" title="System.String">DateSeparator</th>
        <td>/</td>
      </tr>
      <tr>
        <th class="member" title="System.DayOfWeek">FirstDayOfWeek</th>
        <td>Sunday</td>
      </tr>
      <tr>
        <th class="member" title="System.Globalization.CalendarWeekRule">CalendarWeekRule</th>
        <td>FirstDay</td>
      </tr>
      <tr>
        <th class="member" title="System.String">FullDateTimePattern</th>
        <td>dddd, d MMMM yyyy h:mm:ss tt</td>
      </tr>
      <tr>
        <th class="member" title="System.String">LongDatePattern</th>
        <td>dddd, d MMMM yyyy</td>
      </tr>
      <tr>
        <th class="member" title="System.String">LongTimePattern</th>
        <td>h:mm:ss tt</td>
      </tr>
      <tr>
        <th class="member" title="System.String">MonthDayPattern</th>
        <td>d MMMM</td>
      </tr>
      <tr>
        <th class="member" title="System.String">PMDesignator</th>
        <td>PM</td>
      </tr>
      <tr>
        <th class="member" title="System.String">RFC1123Pattern</th>
        <td>ddd, dd MMM yyyy HH':'mm':'ss 'GMT'</td>
      </tr>
      <tr>
        <th class="member" title="System.String">ShortDatePattern</th>
        <td>d/M/yyyy</td>
      </tr>
      <tr>
        <th class="member" title="System.String">ShortTimePattern</th>
        <td>h:mm tt</td>
      </tr>
      <tr>
        <th class="member" title="System.String">SortableDateTimePattern</th>
        <td>yyyy'-'MM'-'dd'T'HH':'mm':'ss</td>
      </tr>
      <tr>
        <th class="member" title="System.String">TimeSeparator</th>
        <td>:</td>
      </tr>
      <tr>
        <th class="member" title="System.String">UniversalSortableDateTimePattern</th>
        <td>yyyy'-'MM'-'dd HH':'mm':'ss'Z'</td>
      </tr>
      <tr>
        <th class="member" title="System.String">YearMonthPattern</th>
        <td>MMMM yyyy</td>
      </tr>
      <tr>
        <th class="member" title="System.String[]">AbbreviatedDayNames</th>
        <td>
          <table id="t6">
            <tr>
              <td class="typeheader" colspan="1">
                String[7] <span class="fixedextenser">4</span>
              </td>
            </tr>
            <tr>
              <td>Sun</td>
            </tr>
            <tr>
              <td>Mon</td>
            </tr>
            <tr>
              <td>Tue</td>
            </tr>
            <tr>
              <td>Wed</td>
            </tr>
            <tr>
              <td>Thu</td>
            </tr>
            <tr>
              <td>Fri</td>
            </tr>
            <tr>
              <td>Sat</td>
            </tr>
          </table>
        </td>
      </tr>
      <tr>
        <th class="member" title="System.String[]">ShortestDayNames</th>
        <td>
          <table id="t7">
            <tr>
              <td class="typeheader" colspan="1">
                String[7] <span class="fixedextenser">4</span>
              </td>
            </tr>
            <tr>
              <td>Su</td>
            </tr>
            <tr>
              <td>Mo</td>
            </tr>
            <tr>
              <td>Tu</td>
            </tr>
            <tr>
              <td>We</td>
            </tr>
            <tr>
              <td>Th</td>
            </tr>
            <tr>
              <td>Fr</td>
            </tr>
            <tr>
              <td>Sa</td>
            </tr>
          </table>
        </td>
      </tr>
      <tr>
        <th class="member" title="System.String[]">DayNames</th>
        <td>
          <table id="t8">
            <tr>
              <td class="typeheader" colspan="1">
                String[7] <span class="fixedextenser">4</span>
              </td>
            </tr>
            <tr>
              <td>Sunday</td>
            </tr>
            <tr>
              <td>Monday</td>
            </tr>
            <tr>
              <td>Tuesday</td>
            </tr>
            <tr>
              <td>Wednesday</td>
            </tr>
            <tr>
              <td>Thursday</td>
            </tr>
            <tr>
              <td>Friday</td>
            </tr>
            <tr>
              <td>Saturday</td>
            </tr>
          </table>
        </td>
      </tr>
      <tr>
        <th class="member" title="System.String[]">AbbreviatedMonthNames</th>
        <td>
          <table id="t9">
            <tr>
              <td class="typeheader" colspan="1">
                String[13] <span class="fixedextenser">4</span>
              </td>
            </tr>
            <tr>
              <td>Jan</td>
            </tr>
            <tr>
              <td>Feb</td>
            </tr>
            <tr>
              <td>Mar</td>
            </tr>
            <tr>
              <td>Apr</td>
            </tr>
            <tr>
              <td>May</td>
            </tr>
            <tr>
              <td>Jun</td>
            </tr>
            <tr>
              <td>Jul</td>
            </tr>
            <tr>
              <td>Aug</td>
            </tr>
            <tr>
              <td>Sep</td>
            </tr>
            <tr>
              <td>Oct</td>
            </tr>
            <tr>
              <td>Nov</td>
            </tr>
            <tr>
              <td>Dec</td>
            </tr>
            <tr>
              <td> </td>
            </tr>
          </table>
        </td>
      </tr>
      <tr>
        <th class="member" title="System.String[]">MonthNames</th>
        <td>
          <table id="t10">
            <tr>
              <td class="typeheader" colspan="1">
                String[13] <span class="fixedextenser">4</span>
              </td>
            </tr>
            <tr>
              <td>January</td>
            </tr>
            <tr>
              <td>February</td>
            </tr>
            <tr>
              <td>March</td>
            </tr>
            <tr>
              <td>April</td>
            </tr>
            <tr>
              <td>May</td>
            </tr>
            <tr>
              <td>June</td>
            </tr>
            <tr>
              <td>July</td>
            </tr>
            <tr>
              <td>August</td>
            </tr>
            <tr>
              <td>September</td>
            </tr>
            <tr>
              <td>October</td>
            </tr>
            <tr>
              <td>November</td>
            </tr>
            <tr>
              <td>December</td>
            </tr>
            <tr>
              <td> </td>
            </tr>
          </table>
        </td>
      </tr>
      <tr>
        <th class="member" title="System.Boolean">IsReadOnly</th>
        <td>
          <b>True</b>
        </td>
      </tr>
      <tr>
        <th class="member" title="System.String">NativeCalendarName</th>
        <td>Gregorian Calendar</td>
      </tr>
      <tr>
        <th class="member" title="System.String[]">AbbreviatedMonthGenitiveNames</th>
        <td>
          <table id="t11">
            <tr>
              <td class="typeheader" colspan="1">
                String[13] <span class="fixedextenser">4</span>
              </td>
            </tr>
            <tr>
              <td>Jan</td>
            </tr>
            <tr>
              <td>Feb</td>
            </tr>
            <tr>
              <td>Mar</td>
            </tr>
            <tr>
              <td>Apr</td>
            </tr>
            <tr>
              <td>May</td>
            </tr>
            <tr>
              <td>Jun</td>
            </tr>
            <tr>
              <td>Jul</td>
            </tr>
            <tr>
              <td>Aug</td>
            </tr>
            <tr>
              <td>Sep</td>
            </tr>
            <tr>
              <td>Oct</td>
            </tr>
            <tr>
              <td>Nov</td>
            </tr>
            <tr>
              <td>Dec</td>
            </tr>
            <tr>
              <td> </td>
            </tr>
          </table>
        </td>
      </tr>
      <tr>
        <th class="member" title="System.String[]">MonthGenitiveNames</th>
        <td>
          <table id="t12">
            <tr>
              <td class="typeheader" colspan="1">
                String[13] <span class="fixedextenser">4</span>
              </td>
            </tr>
            <tr>
              <td>January</td>
            </tr>
            <tr>
              <td>February</td>
            </tr>
            <tr>
              <td>March</td>
            </tr>
            <tr>
              <td>April</td>
            </tr>
            <tr>
              <td>May</td>
            </tr>
            <tr>
              <td>June</td>
            </tr>
            <tr>
              <td>July</td>
            </tr>
            <tr>
              <td>August</td>
            </tr>
            <tr>
              <td>September</td>
            </tr>
            <tr>
              <td>October</td>
            </tr>
            <tr>
              <td>November</td>
            </tr>
            <tr>
              <td>December</td>
            </tr>
            <tr>
              <td> </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </div>
</body>

`

**Comment by danmosemsft** [comment] 2020-09-14 17:58
What build is in use here? Is this a regression in 5.0 or not new?

@tarekgh

**Comment by tarekgh** [comment] 2020-09-14 18:09
I don't think this is a regression. and I think this is by design too. 

You are trying to parse `01-Jan-0001` which is the minimum DateTime value we can support. If your local time zone has positive offset of UTC, then we need to convert the parsed date to your local time. That will make the date go before min Date/time we can support.
We don't support time before the Min DateTime values.in other word having negative ticks.

**Comment by tarekgh** [comment] 2020-09-14 18:18
Forgot to mention, you can workaround the issue by passing `DateTimeStyles.AssumeUniversal`. 

I am closing the issue, but feel free to respond back with any question or concern. Thanks for reporting it.

**Closed by tarekgh** 2020-09-14 18:18 UTC
Labels: area-System.Runtime, question
