### ISSUE TITLE
Roslyn generates corrupt assembly with 65535 (0xFFFF) fields - BadImageFormatException (0x8013110E)

### ISSUE THREAD

**Issue by FSDKO** [dotnet/runtime#94890] opened 2023-11-16 16:10 UTC
If there are **exact** 65535 fields in an assembly, the roslyn compiler may generate an "corrupt" assembly file.
With one field more or less everything works fine.

Rosyln compiles this assemly without any error or warning. Also dependent projects, that references this, compiles without any error or warning.
But at runtime accessing any type of this "corrupt" assembly results in an [`System.BadImageFormatException`](https://learn.microsoft.com/dotnet/api/system.badimageformatexception):
"File is corrupt. (0x8013110E)"

This problem may be similar to the existing issue dotnet/runtime#94892.

**Version Used**: 

* 3.0.19.17001 (net48)
* 4.700.23.40302 (Visual Studio 2022 Version 17.7.1)
* 4.900.23.56033 (Visual Studio 2022 Version 17.9.0 Preview 1.0)

Target Framework for the Library / Console App:

 * net48 / net48 (❌ fails)
 * netstandard2.0 / net6.0 (❌ fails)
 * net6.0 / net6.0 (❌ fails)
 * net7.0 / net7.0 (✅  works)
 * net8.0 / net8.0 (❌ fails)

**Steps to Reproduce**:

1. Create a class library project "FFFF_Field" with following code:
<details>
  <summary>Generate the complete code...</summary>

  ```c#
    int maxFieldCount = 65535;

    var sb = new StringBuilder();
    sb.AppendLine("namespace FFFF_Field");
    sb.AppendLine("{");

    sb.AppendLine($"    public class MyClass1");
    sb.AppendLine("    {");
    for (int field = 1; field <= 10; field++)
        sb.AppendLine($"        public static readonly string Field_{field:X4} = null;");
    sb.AppendLine("    }");

    sb.AppendLine($"    public class MyClass2");
    sb.AppendLine("    {");
    for (int field = 11; field <= maxFieldCount; field++)
        sb.AppendLine($"        public static readonly string Field_{field:X4} = null;");
    sb.AppendLine("    }");

    sb.AppendLine("    public interface ITest1");
    sb.AppendLine("    {");
    sb.AppendLine($"       string Property {{ get; set; }}");
    sb.AppendLine("    }");

    sb.AppendLine("}");
  ```
</details>

```c#
namespace FFFF_Field
{
    public class MyClass1
    {
        public static readonly string Field_0001 = null;
        public static readonly string Field_0002 = null;
        public static readonly string Field_0003 = null;
        public static readonly string Field_0004 = null;
        public static readonly string Field_0005 = null;
        public static readonly string Field_0006 = null;
        public static readonly string Field_0007 = null;
        public static readonly string Field_0008 = null;
        public static readonly string Field_0009 = null;
        public static readonly string Field_000A = null;
    }
    public class MyClass2
    {
        public static readonly string Field_000B = null;
        public static readonly string Field_000C = null;
        public static readonly string Field_000D = null;
        [...]
        public static readonly string Field_FFFD = null;
        public static readonly string Field_FFFE = null;
        public static readonly string Field_FFFF = null;
    }
    public interface ITest1
    {
       string Property { get; set; }
    }
}
```

2. Create a Console App "ConsoleTest" and reference the class libraray project "FFF_Field":
```c#
using System;

namespace ConsoleTest
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            try
            {
                Test();
            }
            catch (Exception ex)
            {
                Console.Write(ex.ToString());
            }
            Console.ReadLine();
        }

        private static void Test()
        {
            Console.WriteLine(typeof(FFFF_Field.MyClass1).FullName);
            Console.WriteLine(typeof(FFFF_Field.MyClass2).FullName);
            Console.WriteLine(typeof(FFFF_Field.ITest1).FullName);
        }
    }
}
```

3. Execute the console App

**Diagnostic Id**:

-/-

**Expected Behavior**:

Console-Output:
```console
FFFF_Field.MyClass1
FFFF_Field.MyClass2
FFFF_Field.ITest1
```

**Actual Behavior**:

Console-Output:
```console
System.BadImageFormatException: Could not load file or assembly 'FFFF_Field, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. File is corrupt. (0x8013110E)
File name: 'FFFF_Field, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' ---> System.BadImageFormatException: File is corrupt. (0x8013110E)
   at ConsoleTest.Program.Test()
   at ConsoleTest.Program.Main(String[] args) in C:\FS\repos\FFFF_Method\TestAssembly\Program.cs:line 9
```

**Comment by steveharter** [comment] 2024-01-08 22:27
I believe this is a very old issue that has not been fixed. See the following:
- https://github.com/dotnet/coreclr/pull/20865
- https://github.com/dotnet/runtime/issues/26096
- https://github.com/dotnet/runtime/issues/94892

cc @MichalStrehovsky, @jkotas 

We do have an older repro that I verified still occurs in v8.

**Comment by steveharter** [comment] 2024-01-09 15:29
Closing as duplicate of https://github.com/dotnet/runtime/issues/94892

**Closed by steveharter** 2024-01-09 15:29 UTC
Labels: bug, area-System.Reflection.Metadata
