### ISSUE TITLE
Test failure JIT\\HardwareIntrinsics\\X86\\Fma_Vector256\\Fma_ro\\Fma_ro.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#65474] opened 2022-02-17 00:58 UTC
Run: [runtime-coreclr r2r 20220215.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1615542&view=ms.vss-test-web.build-test-results-tab&runId=44957226&paneView=debug&resultId=100120)

Failed test:
```
R2R windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open

- JIT\\HardwareIntrinsics\\X86\\Fma_Vector256\\Fma_ro\\Fma_ro.cmd

R2R windows x64 Checked @ Windows.10.Amd64.Open

- JIT\\HardwareIntrinsics\\X86\\Sse2.X64\\Sse2.X64_ro\\Sse2.X64_ro.cmd

```
**Error message:**
```
Could Not Find C:\h\w\973608E9\w\AFEE09DD\e\JIT\HardwareIntrinsics\X86\Fma_Vector256\Fma_ro\IL-CG2\composite-r2r.dll
Could Not Find C:\h\w\973608E9\w\AFEE09DD\e\JIT\HardwareIntrinsics\X86\Fma_Vector256\Fma_ro\Fma_ro.dll.rsp
Unhandled exception. System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)
at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable1 searchPath, Boolean throwOnError) at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable1 searchPath)
at Internal.JitInterface.JitConfigProvider.<>c__DisplayClass5_0.<Initialize>b__0(String libName, Assembly assembly, Nullable1 searchPath) at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags) at Internal.JitInterface.CorInfoImpl.GetJitHost(IntPtr configProvider) at Internal.JitInterface.CorInfoImpl.Startup(CORINFO_OS os) at Internal.JitInterface.JitConfigProvider.Initialize(TargetDetails target, IEnumerable1 jitFlags, IEnumerable1 parameters, String jitPath) at ILCompiler.ReadyToRunCodegenCompilationBuilder.ToCompilation() at ILCompiler.Program.RunSingleCompilation(Dictionary2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary2 unrootedInputFilePaths, HashSet1 versionBubbleModulesHash, CompilerTypeSystemContext typeSystemContext)
at ILCompiler.Program.Run(String[] args)
at ILCompiler.Program.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\973608E9\w\AFEE09DD\uploads\Reports\JIT.HardwareIntrinsics\X86\Fma_Vector256\Fma_ro\Fma_ro.output.txt
Raw output:
BEGIN EXECUTION
Fma_ro.dll
TestLibrary.dll
2 file(s) copied.
Response file: C:\h\w\973608E9\w\AFEE09DD\e\JIT\HardwareIntrinsics\X86\Fma_Vector256\Fma_ro\Fma_ro.dll.rsp
C:\h\w\973608E9\w\AFEE09DD\e\JIT\HardwareIntrinsics\X86\Fma_Vector256\Fma_ro\IL-CG2\Fma_ro.dll
-o:C:\h\w\973608E9\w\AFEE09DD\e\JIT\HardwareIntrinsics\X86\Fma_Vector256\Fma_ro\Fma_ro.dll
--targetarch:x86
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\973608E9\p\System..dll
-r:C:\h\w\973608E9\p\Microsoft..dll
-r:C:\h\w\973608E9\p\mscorlib.dll
-r:C:\h\w\973608E9\p\netstandard.dll
-O
" "dotnet" "C:\h\w\973608E9\p\crossgen2\crossgen2.dll" @"C:\h\w\973608E9\w\AFEE09DD\e\JIT\HardwareIntrinsics\X86\Fma_Vector256\Fma_ro\Fma_ro.dll.rsp"   -r:C:\h\w\973608E9\w\AFEE09DD\e\JIT\HardwareIntrinsics\X86\Fma_Vector256\Fma_ro\IL-CG2*.dll"
Crossgen2 failed with exitcode - -532462766
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\973608E9\p
C:\h\w\973608E9\w\AFEE09DD\e\JIT\HardwareIntrinsics\X86\Fma_Vector256\Fma_ro\Fma_ro.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_HardwareIntrinsics._X86_Fma_Vector256_Fma_ro_Fma_ro_._X86_Fma_Vector256_Fma_ro_Fma_ro_cmd()
```

**Comment by tannergooding** [comment] 2022-03-11 17:24
Dupe of https://github.com/dotnet/runtime/issues/65646

**Closed by tannergooding** 2022-03-11 17:24 UTC
Labels: arch-x86, os-windows, arch-x64, area-crossgen2-coreclr, untriaged
