### ISSUE TITLE
Expression.Equal does not consistently use operator ==

### ISSUE THREAD

**Issue by Coda17** [dotnet/runtime#52357] opened 2021-04-29 19:52 UTC
### Description

When creating a binary expression with `Expression.Equal` where one side is a class (`SomeClass`) that inherits from a class that implements `operator ==(SomeType, SomeType)`, I would expect the expression to compare using `operator ==`. This differs from the behavior if `SomeClass` were to implement `operator ==` itself, where it does use `operator ==`.

Example:
```csharp
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
					
public class Program
{
    public static void Main()
    {
    	var someClasses = new []
    	{
    		SomeClass.One, SomeClass.Two, SomeClass.One, SomeClass.Two
    	}.AsQueryable();
		
    	var parameter = Expression.Parameter(typeof(SomeClass), "e");
    	var value = Expression.Constant(new SomeClass(2, "Two"), typeof(SomeClass));

        // This expression does not use .Equals or operator ==
        // (or the implementation of IEquality<SomeClass>, if provided)
        var expression = Expression.Equal(parameter, value);

	var lambda = Expression.Lambda<Func<SomeClass, bool>>(expression, parameter);
		
	var result = someClasses.Where(lambda);
	foreach (var someClass in result)
	{
		Console.WriteLine($"{someClass.Id} {someClass.Name}");
	}
    }
	
    public abstract class Enumeration<TEnum> where TEnum : Enumeration<TEnum>
    {
    	public int Id {get; set;}
    	public string Name {get;set;}

    	protected Enumeration(int id, string name) => (Id, Name) = (id, name);
		
    	public override bool Equals(object obj)
        {
            if (!(obj is TEnum otherValue)) {return false;};
            var typeMatches = GetType() == obj.GetType();
            var valueMatches = Id.Equals(otherValue.Id);
            return typeMatches && valueMatches;
        }
		
    	public override int GetHashCode() => Id.GetHashCode();

    	public static bool operator ==(Enumeration<TEnum> left, Enumeration<TEnum> right)
    	{
    		if (ReferenceEquals(left, right)) return true;
    		if (left is null || right is null) return false;
    		return left.Id == right.Id;
    	}

    	public static bool operator !=(Enumeration<TEnum> left, Enumeration<TEnum> right)
    	{
    		return !(left == right);
    	}
    }

    public class SomeClass : Enumeration<SomeClass>
    {
    	public static SomeClass One = new SomeClass(1, "One");
    	public static SomeClass Two = new SomeClass(2, "Two");
    	public SomeClass(int id, string name) : base(id, name) {}

        // If I uncomment all of this, I get the behavior I would expect.
    	//public override bool Equals(object obj)
        //{
        //    if (!(obj is SomeClass otherValue)) {return false;};
        //    var typeMatches = GetType() == obj.GetType();
        //    var valueMatches = Id.Equals(otherValue.Id);
        //    return typeMatches && valueMatches;
        //}
		
    	//public override int GetHashCode() => Id.GetHashCode();

    	//public static bool operator ==(SomeClass left, SomeClass right)
    	//{
    	//	if (ReferenceEquals(left, right)) return true;
    	//	if (left is null || right is null) return false;
    	//	return left.Id == right.Id;
    	//}

    	//public static bool operator !=(SomeClass left, SomeClass right)
    	//{
    	//	return !(left == right);
    	//}
    }
}
```

### Configuration

* Which version of .NET is the code running on?
3.1
* What OS and version, and for Linux, what distro?
Microsoft Windows 10 Enterprise 10.0.18363 Build 18363
* What is the architecture (x64, x86, ARM, ARM64)?
x64
* Do you know whether it is specific to that configuration?
No but seems unlikely

### Regression?

Not sure

### Other information

Workaround: It seems to be possible to workaround this by passing the `operator ==` method to the `Expression.Equal` call, like `Expression.Equal(parameter, value, false, typeof(SomeClass).BaseType.GetTypeInfo().GetMethod("op_Equality", BindingFlags.Public | BindingFlags.Static));`.

Workaround 2: Pass the base type to the `Expression.Constant` call: `Expression.Constant(new SomeClass(2, "Two"), typeof(SomeClass).BaseType);`

Both workarounds are hard to implement in situations where working with generic types where you don't really care where in the inheritance tree equals is implemented, you just care that it's implemented somewhere.

**Comment by cston** [comment] 2021-07-13 23:13
@Coda17, thanks for reporting this issue.

It appears to be duplicate of https://github.com/dotnet/runtime/issues/51692. Closing as duplicate.

**Closed by cston** 2021-07-13 23:13 UTC
Labels: area-System.Linq.Expressions, untriaged
