### ISSUE TITLE
Test failure JIT/Regression/JitBlue/Runtime_34587/Runtime_34587/Runtime_34587.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#63716] opened 2022-01-13 01:37 UTC
Run: [runtime-coreclr outerloop 20220112.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1549158&view=ms.vss-test-web.build-test-results-tab&runId=43747090&paneView=debug&resultId=109964)

Failed test:
```
R2R-CG2 OSX x64 Checked @ OSX.1014.Amd64.Open
- JIT/Regression/JitBlue/Runtime_34587/Runtime_34587/Runtime_34587.sh

R2R-CG2 OSX x64 Checked no_tiered_compilation @ OSX.1014.Amd64.Open
- JIT/Regression/JitBlue/Runtime_34587/Runtime_34587/Runtime_34587.sh

R2R-CG2 windows x64 Checked @ Windows.10.Amd64.Open
- JIT\\Regression\\JitBlue\\Runtime_34587\\Runtime_34587\\Runtime_34587.cmd

R2R-CG2 windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open
- JIT\\Regression\\JitBlue\\Runtime_34587\\Runtime_34587\\Runtime_34587.cmd

R2R-CG2 windows x86 Checked @ Windows.10.Amd64.Open
- JIT\\Regression\\JitBlue\\Runtime_34587\\Runtime_34587\\Runtime_34587.cmd

R2R-CG2 windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open
- JIT\\Regression\\JitBlue\\Runtime_34587\\Runtime_34587\\Runtime_34587.cmd

R2R-CG2 Linux x64 Checked no_tiered_compilation @ (Alpine.314.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64-20210910135833-1848e19
- JIT/Regression/JitBlue/Runtime_34587/Runtime_34587/Runtime_34587.sh

R2R-CG2 Linux x64 Checked no_tiered_compilation @ Ubuntu.1804.Amd64.Open
- JIT/Regression/JitBlue/Runtime_34587/Runtime_34587/Runtime_34587.sh

R2R-CG2 Linux x64 Checked @ (Alpine.314.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64-20210910135833-1848e19
- JIT/Regression/JitBlue/Runtime_34587/Runtime_34587/Runtime_34587.sh

R2R-CG2 Linux x64 Checked @ Ubuntu.1804.Amd64.Open
- JIT/Regression/JitBlue/Runtime_34587/Runtime_34587/Runtime_34587.sh

```
**Error message:**
```
rm: IL-CG2/composite-r2r.dll: No such file or directory
/private/tmp/helix/working/ACE1090F/w/ADDD099C/e/JIT/Regression/JitBlue/Runtime_34587/Runtime_34587/Runtime_34587.sh: line 250: -r:/private/tmp/helix/working/ACE1090F/w/ADDD099C/e/JIT/Regression/JitBlue/Runtime_34587/Runtime_34587/IL-CG2/*.dll: No such file or directory
rm: /private/tmp/helix/working/ACE1090F/w/ADDD099C/e/JIT/Regression/JitBlue/Runtime_34587/Runtime_34587/Runtime_34587.dll.rsp: No such file or directory
Process terminated. Assertion failed.
at ILCompiler.DependencyAnalysis.SortableDependencyNode.ObjectNodeComparer.Compare(DependencyNodeCore1 x1, DependencyNodeCore1 y1)
at ILCompiler.Sorting.Implementation.MergeSortCore5.Merge(T[] localCopyOfHalfOfArray, TDataStructure arrayToSort, Int32 index, Int32 halfLen, Int32 length, TComparer comparer) at ILCompiler.Sorting.Implementation.MergeSortCore5.MergeSortHelper(TDataStructure arrayToSort, Int32 index, Int32 length, TComparer comparer, T[] scratchSpace)
at ILCompiler.Sorting.Implementation.MergeSortCore5.SequentialSort(TDataStructure arrayToSort, Int32 index, Int32 length, TComparer comparer) at ILCompiler.Sorting.Implementation.MergeSortCore5.ParallelSortApi(TDataStructure arrayToSort, TComparer comparer)
at ILCompiler.MergeSortApi.MergeSortAllowDuplicates[T](List1 listToSort, IComparer1 comparer)
at ILCompiler.DependencyAnalysisFramework.DependencyAnalyzer2.ComputeMarkedNodes() at ILCompiler.ReadyToRunCodegenCompilation.Compile(String outputFile) at ILCompiler.Program.RunSingleCompilation(Dictionary2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary2 unrootedInputFilePaths, HashSet1 versionBubbleModulesHash, CompilerTypeSystemContext typeSystemContext)
at ILCompiler.Program.Run(String[] args)
at ILCompiler.Program.Main(String[] args)
/private/tmp/helix/working/ACE1090F/w/ADDD099C/e/JIT/Regression/JitBlue/Runtime_34587/Runtime_34587/Runtime_34587.sh: line 206: 60570 Abort trap: 6           (core dumped) $__Command

Return code:      1
Raw output file:      /tmp/helix/working/ACE1090F/w/ADDD099C/uploads/Reports/JIT.Regression/JitBlue/Runtime_34587/Runtime_34587/Runtime_34587.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/private/tmp/helix/working/ACE1090F/w/ADDD099C/e/JIT/Regression/JitBlue/Runtime_34587/Runtime_34587/IL-CG2/Runtime_34587.dll
Response file: /private/tmp/helix/working/ACE1090F/w/ADDD099C/e/JIT/Regression/JitBlue/Runtime_34587/Runtime_34587/Runtime_34587.dll.rsp
/private/tmp/helix/working/ACE1090F/w/ADDD099C/e/JIT/Regression/JitBlue/Runtime_34587/Runtime_34587/IL-CG2/Runtime_34587.dll
-o:/private/tmp/helix/working/ACE1090F/w/ADDD099C/e/JIT/Regression/JitBlue/Runtime_34587/Runtime_34587/Runtime_34587.dll
-r:/tmp/helix/working/ACE1090F/p/System..dll
-r:/tmp/helix/working/ACE1090F/p/Microsoft..dll
-r:/tmp/helix/working/ACE1090F/p/mscorlib.dll
--verify-type-and-field-layout
--targetarch:x64
-O
Running CrossGen2:  dotnet /tmp/helix/working/ACE1090F/p/crossgen2/crossgen2.dll @/private/tmp/helix/working/ACE1090F/w/ADDD099C/e/JIT/Regression/JitBlue/Runtime_34587/Runtime_34587/Runtime_34587.dll.rsp

Gathering state for process 60570
Crashing thread 00047a7f signal 00000006
Writing minidump with heap to file /cores/coredump.60570.dmp
Written 400437672 bytes (97763 pages) to core file
Dump successfully written
Crossgen2 failed with exitcode: 134
in ReleaseLock
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/tmp/helix/working/ACE1090F/p
/private/tmp/helix/working/ACE1090F/w/ADDD099C/e/JIT/Regression/JitBlue/Runtime_34587/Runtime_34587/Runtime_34587.sh
Expected: True
Actual:   False


Stack trace
   at JIT_Regression._JitBlue_Runtime_34587_Runtime_34587_Runtime_34587_._JitBlue_Runtime_34587_Runtime_34587_Runtime_34587_sh()
```

**Comment by trylek** [comment] 2022-01-14 23:30
Closing as duplicate of #63818 containing more triage details.

**Closed by trylek** 2022-01-14 23:30 UTC
Labels: os-linux, os-mac-os-x, os-windows, arch-x64, area-crossgen2-coreclr, untriaged
