### ISSUE TITLE
IL2008: System.Diagnostics.FileVersionInfo: Could not resolve type 'System.SR'.

### ISSUE THREAD

**Issue by henning-krause** [dotnet/runtime#102303] opened 2024-05-16 06:26 UTC
I'm trying to trim my application and get this warning:

```
resource ILLink.Substitutions.xml in System.Diagnostics.FileVersionInfo, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a(5,6): warning IL2008: System.Diagnostics.FileVersionInfo: Could not resolve type 'System.SR'. 
```

It's unclear to me what the linker is complaining about and how I can fix this. There isn't even a hint to where I use FileVersionInfo. I can't find any reference to it in my solution, so it must be further down the call-stream.

It would be great if the ILLinker could pinpoint me to the source.

**Comment by henning-krause** [comment] 2024-05-16 06:36
By chance I found the issue:

I had a call to Assembly.GetExecutingAssembly().Location in my code. I replaced it with AppContext.BaseDirectory and the issue went away.

Still, is there a way the Linker could generate a better warning here?

**Comment by MichalStrehovsky** [comment] 2024-05-16 07:29
The problem is that `System.Diagnostics.FileVersionInfo` has the resource and a manifest asking to remove the resource if `UseResourceKeys` feature switch is enabled, but no SR class because the resource is already dead on Windows at the time we build the assembly.

It's safe to ignore or suppress this warning. It's a harmless bug in the authoring.

**Comment by MichalStrehovsky** [comment] 2024-05-16 09:13
This should be fixed.

**Closed** 2024-06-17 21:55 UTC
Labels: untriaged, area-Tools-ILLink
