### ISSUE TITLE
Request timed out  

### ISSUE THREAD

**Issue by dongzhaosheng73** [dotnet/runtime#100062] opened 2024-03-21 07:34 UTC
### Description

The client occasionally sends System.TimeoutException: Request timed out
---> System.Threading.Tasks.TaskCanceledException: A task was canceled. The error client occasionally sends System.TimeoutException: Request timed out
---> System.Threading.Tasks.TaskCanceledException: A task was canceled. mistake.

### Reproduction Steps

In random recurrence, either the client must be restarted or HttpClient must use a new socket.
I found that there were already similar problems but there was no practical solution.

https://github.com/restsharp/RestSharp/issues/1092

### Expected behavior

Request timed out should not affect subsequent request behavior

### Actual behavior

Request timed out Subsequent requests will cause the Request timed out until the client restarts

### Configuration

.net 6
windows11
x86
RestSharp 108.0.2

**Comment by antonfirsov** [comment] 2024-03-25 21:00
@dongzhaosheng73 this is not actionable for us with the information provided. Given the issue is RestSharp-specific and you also opened https://github.com/restsharp/RestSharp/issues/2176, I think you will have better chances getting help there, but they would also need more information.

The best would be if you could provide a a repro. If it's not possible, detailed description of the client & server scenario with at least some code is still desired.

**Comment by antonfirsov** [comment] 2024-03-25 21:01
Triage: moving to Future for now, in the unlikely case it turns out to be a problem with HttpClient, we can bump the priority. Otherwise we should close.

**Comment by alexeyzimarev** [comment] 2024-04-02 14:32
I am not sure that the issue is related to RestSharp as RestSharp just forms a request message and sends it over via `HttpClient`.

**Comment by ManickaP** [comment] 2024-04-02 16:44
Whether this is related to RestSharp or not doesn't change that fact that the issue as-is now is not actionable. We need a repro case, preferably just with `HttpClient`. Or traces, captures, logs from reporter's environment.

**Comment by alexeyzimarev** [comment] 2024-04-06 10:53
What I meant is that the issue opened in RestSharp repository is not actionable as well as RestSharp's role is to create a request message and pass it over to `HttpClient`. My challenge is with "you will have better chances getting help there", as I don't think I can provide any help with the issue. Surely, I agree with your point that the issue that occurs in a specific environment, at random, is almost impossible to fix in lack of reliable repro.

**Closed** 2024-05-04 19:39 UTC
Labels: area-System.Net.Http, no-recent-activity, needs-author-action
