### ISSUE TITLE
JsonSerializerOptions.IgnoreNullValues is not respected if Custom Coverter is used for a class object

### ISSUE THREAD

**Issue by mzilberman** [dotnet/runtime#33433] opened 2020-03-10 16:41 UTC
We have been working on a set of converters to support a flexible model. In our example we have a `PropertyValue<T>` and derived types` NullPropertyValue`, `LiteralValue`, `RangeValue` etc...   This is done to explicitly detect in the model if a property was specified as "null" or or was unset entirely within the input document.

Serializer options are set as `JsonSerializerOptions.IgnoreNullValues = true`

In the Custom Converter if the property is `null` in the document we set attempted to `writer.WriteNull()` or `writer.WriteNullValue()` and in both cases the writer did not respect `JsonSerializerOptions.IgnoreNullValues` setting.

At this moment the workaround for us to post process the document by re-read the entire document using `Utf8Reader` and re-write the document using `Utf8Writer`.

@steveharter

**Comment by layomia** [comment] 2020-03-11 16:40
Can you share a code snippet highlighting your scenario?

Following from what I can understand - it would be the converter's responsibility to check for and honor the `IgnoreNullValues` option, accessible through the `options` argument in the [`Write` method](https://docs.microsoft.com/dotnet/api/system.text.json.serialization.jsonconverter-1.write?view=netcore-3.1#System_Text_Json_Serialization_JsonConverter_1_Write_System_Text_Json_Utf8JsonWriter__0_System_Text_Json_JsonSerializerOptions_), not the writer's. Is there any reason to not check for the option in the converter?

**Comment by mzilberman** [comment] 2020-04-05 13:43
The simplest example here:
    public class IgnoreBooleanConverter: JsonConverter<bool>
    {
        public override bool Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Writes a specified value as JSON.
        /// </summary>
        /// <param name="writer">The writer to write to.</param>
        /// <param name="value">The value to convert to JSON.</param>
        /// <param name="options">An object that specifies serialization options to use.</param>
        public override void Write(Utf8JsonWriter writer, bool value, JsonSerializerOptions options)
        {
            writer.WriteNullValue();
        }
    }

------------
            var options = new JsonSerializerOptions();
            options.Converters.Add(new IgnoreBooleanConverter());
            options.IgnoreNullValues = true; 

            var content = JsonSerializer.Serialize(document, options);

This code will still produce Null value for the property of type bool.  It is expected that setting IgnoreNullValues to true will cause the serializer not to write properties with Null.

**Comment by NinoFloris** [comment] 2020-04-06 12:13
I believe this is because null values do trigger custom converters when the custom converter converts a value type, meaning that you would need to check `options.IgnoreNullValues` yourself when building a value type converter. @layomia is that what's happening here?

**Comment by mzilberman** [comment] 2020-04-06 15:26
@NinoFloris .  Agree, but there is no mechanics available to suppress emission of the property. No matter what is implemented within converter some artifact of the property is emitted into the writer.

**Comment by layomia** [comment] 2020-04-06 18:32
> I believe this is because null values do trigger custom converters when the custom converter converts a value type

Whether or not the serializer passes `null` to converters is separate from this issue and is discussed in https://github.com/dotnet/runtime/issues/34439. In this example, we are serializing a non-nullable `struct` which cannot be `null`.

> It is expected that setting IgnoreNullValues to true will cause the serializer not to write properties with Null.

In your example, it is the converter that is writing `null`, not the serializer. When a converter is used, the serializer delegates all (de)serialization responsibility for the current scope to the converter. It is the converter's responsibility to honor and check for options including whether to write null. 

`IgnoreNullValues` is a serializer option, not a writer option, and the writer should not be taking the extra perf hit to check whether to write `null` which should have been done by the caller (serializer or converter).

> but there is no mechanics available to suppress emission of the property

Why write `null` in the first place without checking `options.IgnoreNullValues`? Are you in a situation where the property name is already written somehow, then you realize the value is `null` and don't want to write the property anymore? Can you provide a simple complete repro that highlights what the limitation here is?

**Comment by layomia** [comment] 2020-04-06 22:44
per offline discussion with @mzilberman, I think it makes sense to provide a way to honor the `options.IgnoreNullValues` even when the converter writes `null` tokens with the writer. This is helpful when the property name is already written which can occur in some scenarios involving converter composition.

**Comment by NinoFloris** [comment] 2020-04-07 17:38
Ah! Yes agreed, this is for instance critical to `Option/ValueOption` in F#. These conceptually map their `None` value to null yet they are usually called too late to stop the property name from getting written. I tested this by turning on `IgnoreNullValues`, and making my Option converter not write anything for the `None` case, this even causes invalid json to be written (netcore 3.1).

**Comment by NinoFloris** [comment] 2020-04-07 20:38
@layomia to eloborate on my last point, shouldn't there be a check after invoking a converter to see whether the writer advanced a position?

**Comment by NinoFloris** [comment] 2020-04-18 17:22
I see it's been added to the backlog, F# support is in P1, I would conceptually see this issues being highly related to good F# support (as I wrote here https://github.com/dotnet/runtime/issues/33433#issuecomment-610524670)

**Comment by NinoFloris** [comment] 2020-08-06 14:36
@layomia do you have a suggestion which way we should take this?

I've been thinking there are a few possibilities:

- A property on the converter class which can then be optionally configured through the constructor if exposed.
- Some property on the Options like `IgnoreConverterNullValues`, downside is that for F# this does not have enough granularity, sometimes you want discriminated unions to write null and other times you want it ignored. 
- A new method on the writer to explicitly opt-in, something like `IgnoreProperty()`.

I'd really like to get something in for say 5.1, it's blocking us from creating like for like responses when compared with Newtonsoft.

**Comment by NinoFloris** [comment] 2021-03-18 19:37
@layomia ping, any updates? Some workaround should exist, a custom converter must be able to emit nothing and not break the output json.

**Comment by eiriktsarpalis** [comment] 2021-07-15 17:05
Does the issue still persist in .NET 5? I tried recreating a repro in https://github.com/dotnet/runtime/issues/50294#issuecomment-880865310 but it seems to work as expected.

**Comment by eiriktsarpalis** [comment] 2021-07-16 08:48
Given that I haven't been able to reproduce the issue in .NET 5, I'm going to close this issue. Feel free to reopen if the issue persists.

**Closed by eiriktsarpalis** 2021-07-16 08:48 UTC
Labels: area-System.Text.Json, needs more info
