### ISSUE TITLE
Publish and run a C# Net5.0 Console-app on Debian 10.5 (arm32bit)

### ISSUE THREAD

**Issue by GW-Lab** [dotnet/runtime#44729] opened 2020-11-16 15:00 UTC
Version Used:
16.9.1

Steps to Reproduce:

Create a Net5.0 c# console app (Release any-cpu)
Publish de console app to a folder (pameters: realease | Any CPU, Net5.0, self-contained, linux-arm, path...)
On the host (debian 10.5) the console app is recognised as a Shared-library
The console app will not run/execute
Expected Behavior:
The console app will run/execte on debian 10.5 (32bit)

Actual Behavior:
The console app will not run/execte on debian 10.5 (32bit)

note:
If you try the same and target Net-core 3.1.9 instead of Net5.0 the console app is recognised as a Executable and wil run/execute without any problems

**Comment by jkotas** [comment] 2020-11-19 01:59
Duplicate of #44900

**Closed by jkotas** 2020-11-19 01:59 UTC
Labels: arch-arm32, area-Host, untriaged
