### ISSUE TITLE
ConfigurationBinder source generator generates code without a using for a Type

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#94065] opened 2023-10-26 20:22 UTC
### Description

Trying to use the ConfigurationBinder Source Generator with a StackExchange.Redis ConfigurationOptions type (which wasn't necessarily designed to work with IConfiguration), produces code that doesn't compile.

### Reproduction Steps

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
    <NoWarn>$(NoWarn);SYSLIB1100;SYSLIB1101</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.0-rtm.23511.16" />
    <PackageReference Include="StackExchange.Redis" Version="2.6.122" />
  </ItemGroup>

</Project>
```

```csharp
using Microsoft.Extensions.Configuration;
using StackExchange.Redis;

Console.WriteLine("Hello, World!");

static void BindToConfiguration(ConfigurationOptions options, IConfiguration configuration)
{
    var configurationOptionsSection = configuration.GetSection("ConfigurationOptions");
    configurationOptionsSection.Bind(options);
}
```

### Expected behavior

The project should build cleanly.

### Actual behavior

```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	CS0246	The type or namespace name 'SslClientAuthenticationOptions' could not be found (are you missing a using directive or an assembly reference?)	ConsoleApp101	C:\Users\eerhardt\source\repos\ConsoleApp101\ConsoleApp101\Microsoft.Extensions.Configuration.Binder.SourceGeneration\Microsoft.Extensions.Configuration.Binder.SourceGeneration.ConfigurationBindingGenerator\BindingExtensions.g.cs	1400		
```

The code that doesn't compile looks like:

```csharp
        public static void BindCore(IConfiguration configuration, ref Func<string, SslClientAuthenticationOptions> instance, bool defaultValueIfNotFound, BinderOptions? binderOptions)
        {
            ValidateConfigurationKeys(typeof(Func<string, SslClientAuthenticationOptions>), s_configKeys_FuncStringSslClientAuthenticationOptions, configuration, binderOptions);

            if (AsConfigWithChildren(configuration.GetSection("Method")) is IConfigurationSection section263)
            {
                MethodInfo? temp265 = instance.Method;
                if (temp265 is not null)
                {
                    BindCore(section263, ref temp265, defaultValueIfNotFound: false, binderOptions);
                }
                else
                {
                    throw new InvalidOperationException("Cannot create instance of type 'System.Reflection.MethodInfo' because it is missing a public instance constructor.");
                }
            }
        }
```

### Known Workarounds

Add `global using System.Net.Security;` to the code.

**Comment by ericstj** [comment] 2023-10-26 21:04
Here's the type in question: https://github.com/StackExchange/StackExchange.Redis/blob/5504ed9a93f729f204e6cb53280cb4efa1ccd390/src/StackExchange.Redis/ConfigurationOptions.cs

That exposes a public `Func<string,SslClientAuthenticationOptions>` property:
https://github.com/StackExchange/StackExchange.Redis/blob/5504ed9a93f729f204e6cb53280cb4efa1ccd390/src/StackExchange.Redis/ConfigurationOptions.cs#L573

> which wasn't necessarily designed to work with IConfiguration

Right - I don't think it's normal to expose a Func on a type being bound with config. 

I wonder what the generated code that's trying to bind a `MethodInfo` does 😆 -- I can't imagine that working.  I'm surprised you didn't see a diagnostic telling you this type wasn't supported.

Probably we need to avoid generating code that doesn't compile and better detect these unsupported types and skip them or let the user specify they wish to skip them.

**Comment by ericstj** [comment] 2023-10-26 22:37
Here's a simplified repro:
[configFunc.zip](https://github.com/dotnet/runtime/files/13183343/configFunc.zip)


This does emit a mess of diagnostics to let you know you're not doing something that will be supported.
```
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1100: Cannot create instance of type 'System.Reflection.MethodInfo' because it is missing a public instance constructor. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1100) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1100: Cannot create instance of type 'System.Reflection.ParameterInfo' because it is missing a public instance constructor. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1100) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1100: Cannot create instance of type 'System.Reflection.CustomAttributeData' because it is missing a public instance constructor. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1100) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1100: Cannot create instance of type 'System.Type' because it is missing a public instance constructor. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1100) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1100: Cannot create instance of type 'System.Reflection.Assembly' because it is missing a public instance constructor. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1100) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1100: The collection element type is not supported: 'System.Collections.Generic.IEnumerable<System.Reflection.CustomAttributeData>'. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1100) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'CustomAttributes' on type 'System.Reflection.Assembly' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1100: Cannot create instance of type 'System.Reflection.TypeInfo' because it is missing a public instance constructor. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1100) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1100: Cannot create instance of type 'System.Reflection.ConstructorInfo' because it is missing a public instance constructor. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1100) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'CustomAttributes' on type 'System.Reflection.ConstructorInfo' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'DeclaringType' on type 'System.Reflection.ConstructorInfo' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1100: Cannot create instance of type 'System.Reflection.Module' because it is missing a public instance constructor. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1100) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'CustomAttributes' on type 'System.Reflection.Module' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'ReflectedType' on type 'System.Reflection.ConstructorInfo' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1100: Cannot create instance of type 'System.Reflection.EventInfo' because it is missing a public instance constructor. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1100) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'EventHandlerType' on type 'System.Reflection.EventInfo' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'CustomAttributes' on type 'System.Reflection.EventInfo' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'DeclaringType' on type 'System.Reflection.EventInfo' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'ReflectedType' on type 'System.Reflection.EventInfo' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1100: Cannot create instance of type 'System.Reflection.FieldInfo' because it is missing a public instance constructor. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1100) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'FieldType' on type 'System.Reflection.FieldInfo' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'CustomAttributes' on type 'System.Reflection.FieldInfo' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'DeclaringType' on type 'System.Reflection.FieldInfo' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'ReflectedType' on type 'System.Reflection.FieldInfo' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1100: Cannot create instance of type 'System.Reflection.MemberInfo' because it is missing a public instance constructor. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1100) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'CustomAttributes' on type 'System.Reflection.MemberInfo' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'DeclaringType' on type 'System.Reflection.MemberInfo' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'ReflectedType' on type 'System.Reflection.MemberInfo' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1100: Cannot create instance of type 'System.Reflection.PropertyInfo' because it is missing a public instance constructor. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1100) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'PropertyType' on type 'System.Reflection.PropertyInfo' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'CustomAttributes' on type 'System.Reflection.PropertyInfo' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'DeclaringType' on type 'System.Reflection.PropertyInfo' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'ReflectedType' on type 'System.Reflection.PropertyInfo' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1100: The collection element type is not supported: 'System.Type[]'. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1100) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'GenericTypeParameters' on type 'System.Reflection.TypeInfo' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1100: The collection element type is not supported: 'System.Collections.Generic.IEnumerable<System.Type>'. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1100) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'ImplementedInterfaces' on type 'System.Reflection.TypeInfo' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'BaseType' on type 'System.Reflection.TypeInfo' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1100: Cannot create instance of type 'System.Reflection.MethodBase?' because it is missing a public instance constructor. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1100) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'CustomAttributes' on type 'System.Reflection.MethodBase?' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'DeclaringType' on type 'System.Reflection.MethodBase?' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'ReflectedType' on type 'System.Reflection.MethodBase?' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'DeclaringType' on type 'System.Reflection.TypeInfo' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1100: Cannot create instance of type 'System.Reflection.Binder' because it is missing a public instance constructor. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1100) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'DefaultBinder' on type 'System.Reflection.TypeInfo' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'GenericTypeArguments' on type 'System.Reflection.TypeInfo' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'ReflectedType' on type 'System.Reflection.TypeInfo' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1100: Cannot create instance of type 'System.Runtime.InteropServices.StructLayoutAttribute?' because it has multiple public parameterized constructors. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1100) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'UnderlyingSystemType' on type 'System.Reflection.TypeInfo' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'CustomAttributes' on type 'System.Reflection.TypeInfo' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'DeclaringType' on type 'System.Reflection.TypeInfo' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'ReflectedType' on type 'System.Reflection.TypeInfo' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'ExportedTypes' on type 'System.Reflection.Assembly' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'DefaultBinder' on type 'System.Type' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'GenericTypeArguments' on type 'System.Type' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'CustomAttributes' on type 'System.Type' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1100: Cannot create instance of type 'System.Reflection.ICustomAttributeProvider' because it is missing a public instance constructor. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1100) [C:\scratch\configFunc\configFunc.csproj]
C:\scratch\configFunc\Program.cs(5,1): warning SYSLIB1101: Property 'ReturnTypeCustomAttributes' on type 'System.Reflection.MethodInfo' is not supported. (https://learn.microsoft.com/dotnet/fundamentals/syslib-diagnostics/syslib1101) [C:\scratch\configFunc\configFunc.csproj]
```

We can reduce all that noise by just using a generic type we define ourselves, and not Func (which shouldn't be used in a config type).
```c#
using Some.Name;

using Microsoft.Extensions.Configuration;
var c = new ConfigurationBuilder().Build();
c.Get<MyConfig>();

public class MyConfig
{
    public MyGeneric<E1>? G { get; set; }
}

public class MyGeneric<T>
{
}

namespace Some.Name
{
    public enum E1 
    {
        A,
        B,
        C
    }
}
```
This will reproduce the missing namespace.  The bug seems to be that the source generator won't add usings if they are only needed for type parameters.

Now this isn't really a common case - because the type parameter is completely unused in the types the binder knows about.

If I add a member that uses the type parameter, the error goes away and the generator produces good code.
```c#
public class MyGeneric<T>
{
    public T Value { get; set; }
}
````

Similarly, I can workaround the original issue if I add code that binds to the missing type.

**Comment by eerhardt** [comment] 2023-10-27 19:15
@ericstj - I see this bug is in `9.0.0` right now. Per our discussion today, this bug should be fixed in 8.0.x servicing right? We will fully qualify all the types we generate code for?

**Comment by ericstj** [comment] 2023-10-27 21:25
Yes - we will need to fix this in servicing.  First fix in main then backport.  I think that this bug will actually be fixed with https://github.com/dotnet/runtime/issues/93498 - by eliminating any dependence on `using` statements.

**Comment by ericstj** [comment] 2023-11-03 19:09
I confirmed that my minimal repro with MyGeneric is fixed now with https://github.com/dotnet/runtime/issues/93498.

We now generate this as:
```c#
instance.G ??= new global::MyGeneric<global::Some.Name.E1>();
```

We still generate binding logic for the Func and all of the reflection types, but those are generated and compile correctly.  They will go away once we trim out delegates.

**Closed by ericstj** 2023-11-03 19:09 UTC
Labels: bug, area-Extensions-Configuration
