### ISSUE TITLE
Problem with name clashes in nested types, when using JSON source generator

### ISSUE THREAD

**Issue by lskyum** [dotnet/runtime#87645] opened 2023-06-15 20:20 UTC
### Description

When using the source generator for System.Text.Json, it produces compilation errors when nested classes have naming clashes like this example:

```
public class Foo
{
	public class A { }  // Naming clash with Bar.A

	public A Value { get; set; }

	public Bar Bar { get; set; }
}

public class Bar
{
	public class A { }  // Naming clash with Foo.A

	public A Value { get; set; }
}

[JsonSourceGenerationOptions(WriteIndented = true)]
[JsonSerializable(typeof(Foo))]
internal partial class SourceGenerationContext : JsonSerializerContext
{
}
```

When compiling it generates the following error:
```Cannot convert from 'Bar.A' to 'Foo.A?'```

It will however serialize just fine with the regular JsonSerializer like so:
```
var foo = new Foo()
{
	Value = new Foo.A(),
	Bar = new Bar() { Value = new Bar.A() }
};
string json = JsonSerializer.Serialize(foo, new JsonSerializerOptions { WriteIndented = true });
```

### Reproduction Steps

Compile the following program and see that it fails to compile:
```
public class Foo
{
	public class A { }
	public A Value { get; set; }
	public Bar Bar { get; set; }
}

public class Bar
{
	public class A { }
	public A Value { get; set; }
}

[JsonSourceGenerationOptions(WriteIndented = true)]
[JsonSerializable(typeof(Foo))]
internal partial class SourceGenerationContext : JsonSerializerContext
{
}

internal class Program
{
	static void Main(string[] args)
	{
		var foo = new Foo()
		{
			Value = new Foo.A(),
			Bar = new Bar() { Value = new Bar.A() }
		};
		string json = JsonSerializer.Serialize(foo, SourceGenerationContext.Default.Foo);
	}
}
```

### Expected behavior

I would expect it to compile and serialize 'foo' to JSON.

### Actual behavior

It can't compile and gives the error: Argument 2: cannot convert from 'Bar.A' to 'Foo.A?'

### Configuration

.NET 7 "Any CPU" on Windows
Visual Studio 17.6.2

**Comment by eiriktsarpalis** [comment] 2023-06-15 23:20
Duplicate of https://github.com/dotnet/runtime/issues/58198.

Compiling the above will result in the following warning being generated:
```
Warning	SYSLIB1031	There are multiple types named A. Source was generated for the first one detected. Use 'JsonSerializableAttribute.TypeInfoPropertyName' to resolve this collision.
```
Disambiguating the type names results in the repro working as expected:
```C#
[JsonSourceGenerationOptions(WriteIndented = true)]
[JsonSerializable(typeof(Foo))]
[JsonSerializable(typeof(Bar.A), TypeInfoPropertyName = "BarA")]
internal partial class SourceGenerationContext : JsonSerializerContext
{
}
```

**Closed by eiriktsarpalis** 2023-06-15 23:20 UTC
Labels: area-System.Text.Json, untriaged

**Comment by lskyum** [comment] 2023-06-16 05:45
@eiriktsarpalis Thanks for the workaround!

Just a suggestion: Add an option for JsonSourceGenerationOptions called something like OnlyExposeRootTypeInfo=true and just use name mangling for all other types.

**Comment by eiriktsarpalis** [comment] 2023-06-16 07:59
> Add an option for JsonSourceGenerationOptions called something like OnlyExposeRootTypeInfo=true and just use name mangling for all other types.

It's something that we could consider, but unfortunately that would be a potential source breaking change for users that are explicitly referencing the generated properties for these types.
