### ISSUE TITLE
[Proposal] Obtain delegate invocation list without allocation

### ISSUE THREAD

**Issue by sakno** [dotnet/runtime#52937] opened 2021-05-18 20:36 UTC
## Background and Motivation
Reflection of delegate's invocation list requires defensive copy of the returned array because the array can be potentially mutated by the caller. This allocation could be avoided. Use cases:
* Execution of methods chain depends on their attributes (ordering, priority etc.)
* Changing type of the delegate instance (requires enumeration of the entire chain to convert each method individually)
* Parallel execution of the chain

## Proposed API

```csharp
using System.Runtime.InteropServices;

public static class DelegatesMarshal
{
  public static ReadOnlySpan<TDelegate> GetInvocationList<TDelegate>(TDelegate d) where TDelegate : MulticastDelegate;
  public static ReadOnlySpan<MulticastDelegate> GetInvocationList(MulticastDelegate d);
}
```

Returned span must be empty if the delegate is not a combination of other delegates.

## Usage Examples
```csharp
Action action;

foreach (Action d in DelegatesMarshal.GetInvocationList(action))
{
  d();
}
```

## Alternative Designs
Place proposed methods as static methods to `MulticastDelegate` class.

## Risks
The delegate in invocation list can be modified using `MemoryMarshal.GetReference` method.

**Comment by jkotas** [comment] 2021-05-18 21:06
Duplicate of #41849

**Closed** 2021-05-18 23:19 UTC
Labels: api-suggestion, untriaged
