### ISSUE TITLE
Test failure: The command error output did not contain expected result

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#35949] opened 2020-05-07 08:24 UTC
failed in job: [runtime 20200506.84 ](https://dev.azure.com/dnceng/public/_build/results?buildId=633940&view=ms.vss-test-web.build-test-results-tab&runId=19746274&resultId=100672&paneView=debug)

failed test: 
CompatibilityCheck_Frameworks
MultiThreadedComponentDependencyResolutionWhithFailures
RunApp_UnhandledException

Error message
~~~
The command error output did not contain expected result: "Initialized context for app: /root/runtime/artifacts/tests/Release/ha/nativeHosting/0/app/App.dll""
File Name: /root/runtime/artifacts/tests/Release/ha/nativeHosting/0/nativehost
Arguments: host_context mixed none /root/runtime/artifacts/tests/Release/ha/nativeHosting/0/mockRuntime/host/fxr/5.0.0-ci/libhostfxr.so /root/runtime/artifacts/tests/Release/ha/nativeHosting/0/app/App.dll /root/runtime/artifacts/tests/Release/ha/nativeHosting/0/frameworkCompat.runtimeconfig.json
Exit Code: 139
StdOut:

StdErr:
Tracing enabled @ Wed May 6 23:27:18 2020 UTC
--- Invoked hostfxr_initialize_for_dotnet_command_line [commit hash: f4a67dfe8528126ef4330eb433a433f7b8713759]

"


Stack trace
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at Microsoft.DotNet.CoreSetup.Test.CommandResultAssertions.HaveStdErrContaining(String pattern) in /_/src/installer/test/TestUtils/Assertions/CommandResultAssertions.cs:line 89
   at Microsoft.DotNet.CoreSetup.Test.HostActivation.NativeHosting.HostContextResultExtensions.InitializeContextForApp(CommandResultAssertions assertion, String path) in /_/src/installer/test/HostActivation.Tests/NativeHosting/HostContextResultExtensions.cs:line 61
   at Microsoft.DotNet.CoreSetup.Test.HostActivation.NativeHosting.HostContext.CompatibilityCheck_Frameworks(String scenario, Boolean selfContained, Boolean useIncludedFrameworks, String frameworkName, String version, String rollForward, Nullable`1 isCompatibleVersion) in /_/src/installer/test/HostActivation.Tests/NativeHosting/HostContext.cs:line 464
~~~

**Comment by vitek-karas** [comment] 2020-05-20 19:56
@VSadov Another one.
This looks like a dupe of https://github.com/dotnet/runtime/issues/35950

**Comment by swaroop-sridhar** [comment] 2020-05-20 20:02
I agree it is dup of  #35950

**Closed by swaroop-sridhar** 2020-05-20 20:02 UTC
Labels: arch-x64, area-Host, untriaged
