### ISSUE TITLE
Utf8JsonWriter#flush takes exceptionally long

### ISSUE THREAD

**Issue by Fyko** [dotnet/runtime#48999] opened 2021-03-02 05:27 UTC
### Description
`Utf8JsonWriter#flush` takes an excruciating amount of time. Upwards of 100ms for a single object. I apologize in advance for the brevity of this issue, I'm not very fluent when it comes to C# ecosystems.

Relevent Issue: https://github.com/Tyrrrz/DiscordChatExporter/issues/502

### Configuration
.NET Version: `5.0.103`
Ubuntu 20.04.2 LTS on Windows 10 [WSL2] ~ x86_64

### Data
Here's an example (not sure how reproducable it is, though):
https://paste.nomsy.net/futiwuqefi.cs
`_writer` is declared as:
```csharp
_writer = new Utf8JsonWriter(stream, new JsonWriterOptions
{
    Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
    Indented = true,
    SkipValidation = true
});
```

Output:
```
Starting 642601055862915112
Wrote 642601055862915112 meta after 0ms
Wrote 642601055862915112 content after 0ms
Wrote 642601055862915112 author data after 0ms
Wrote 642601055862915112 attachments after 0ms
Wrote 642601055862915112 embeds after 0ms
Wrote 642601055862915112 reactions after 0ms
Wrote 642601055862915112 mentions after 0ms
Flushed after 91ms
Wrote message 642601055862915112 after 91ms
```

**Comment by danmoseley** [comment] 2021-03-02 22:17
Thanks @Fyko is it possible to share a standalone repro? the code you linked is helpful but does not run alone.

**Comment by Fyko** [comment] 2021-03-03 00:08
Sure, I've pushed the reproducable example to https://github.com/Fyko/export-api/tree/bug/48999
once cloned, cd into ExportAPI and run `dotnet run`.

Then, with a tool like Postman, `POST` to `http://localhost:5000/v2/export` with the JSON body:
```json
{
    "token": "",
    "channel_id": "",
    "export_format": 4,
    "date_format": "MM//dd/yyyy"
}

```
where `token` is a valid discord bot token and `channel_id` is the ID of a discord channel the bot has access to.

**Comment by Fyko** [comment] 2021-03-23 18:20
Good afternoon! Any updates? @danmoseley

**Comment by danmoseley** [comment] 2021-03-23 18:41
Hi @fyko the next step is for the JSON crew @eiriktsarpalis, @layomia to triage or respond.

BTW, it might be interesting to check on 3.1 and current (6.0 preview 2) to confirm the same problem.

**Comment by eiriktsarpalis** [comment] 2021-03-24 12:12
Hi @Fyko we're tracking your issue but at this point we're slightly backlogged. We will try to respond ASAP. In the meantime it would really help if you could trim down your reproducing app into as small a reproduction as possible (e.g. trimming any unrelated logic or unused controllers/endpoints or even reducing to a small console app).

**Comment by eiriktsarpalis** [comment] 2021-04-01 12:06
Hey @Fyko, I tried building your repro locally but it failed with the following error:
```
/usr/share/dotnet/sdk/5.0.201/Microsoft.Common.CurrentVersion.targets(1947,5): warning : The referenced project '../DiscordChatExporter/DiscordChatExporter.Domain/DiscordChatExporter.Domain.csproj' does not exist. [/home/eirik/devel/private/export-api/ExportAPI/ExportAPI.csproj]
/home/eirik/devel/private/export-api/ExportAPI/Controllers/v1/ExportController.cs(8,7): error CS0246: The type or namespace name 'DiscordChatExporter' could not be found (are you missing a using directive or an assembly reference?) [/home/eirik/devel/private/export-api/ExportAPI/ExportAPI.csproj]
```

I would strongly recommend that you strip down the repro to the smallest program possible (since in most cases it could be something wrong with the code itself).

**Comment by Fyko** [comment] 2021-04-01 17:37
Hey Erik, I'll loop back to this tonight or tomorrow afternoon. Cheers!

**Comment by eiriktsarpalis** [comment] 2021-04-19 16:00
Hi @Fyko, have you had perhaps the chance to revisit this? Thanks!

**Comment by eiriktsarpalis** [comment] 2021-06-29 17:44
I'm going to close the issue for now. @Fyko feel free to reopen once you have the time to revisit. Thanks!

**Closed by eiriktsarpalis** 2021-06-29 17:44 UTC
Labels: area-System.Text.Json, needs more info, tenet-performance, untriaged
