### ISSUE TITLE
Module.FullyQualifiedName throws in single-file app

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#40103] opened 2020-07-29 21:07 UTC
On non-single file apps `Module.FullyQualifiedName` returns absolute path to the file of the module (which is basically always the assembly file). If the module is an in-memory module (so loaded from stream), it returns `<Unknown>` string.

In single-file if the module is one of the assemblies which are bundled it will throw from this property.

I think we should make it behave the same as it does for in-memory modules - so return `<Unknown>` for bundled assemblies.

The same applies to `Module.Name` (which is implemented by calling `Module.FullyQualifiedName` internally) - we need to test it.

**Comment by vitek-karas** [comment] 2020-07-29 21:08
/cc @MichalStrehovsky @jkotas 
Another API behavior question for single-file.

**Comment by jkotas** [comment] 2020-07-29 21:12
> behave the same as it does for in-memory modules - so return `<Unkown>` for bundled assemblies.

Agree.

**Comment by vitek-karas** [comment] 2020-07-30 10:34
This issue sort of propagates to `Assembly.GetFile`/`Assembly.GetFiles` as well. On non-single-file app `Assembly.GetFile` returns the assembly file opened as a file stream. For in-memory assemblies the method throws `IOException` because it simply tries to open `Module.FullyQualifiedName`.

In single-file it now throws `FileNotFoundException` (that's this issue) so the exception type is different. This should get fixed once the original issue is fixed.

**Comment by vitek-karas** [comment] 2020-07-30 14:05
Repro is part of the test app here: https://github.com/vitek-karas/single-file-feature-test

**Comment by jkotas** [comment] 2020-07-30 19:03
> In single-file it now throws FileNotFoundException (that's this issue) so the exception type is different. This should get fixed once the original issue is fixed.

It would be nice to explicitly throw in this case, and not depend what FileStream is going to throw by accident (it can even succeed if you have a file called `<Unknown>` in the current directory).

**Comment by vitek-karas** [comment] 2020-07-30 20:22
I create https://github.com/dotnet/runtime/issues/40154 to track that as it's not single-file specific behavior.

**Comment by vitek-karas** [comment] 2020-08-14 11:37
It seems that on Linux the API already behaves correctly (returns `<Unknown>`).

**Comment by agocke** [comment] 2020-08-18 17:56
@tlakollo Could you take a look at this?

**Comment by agocke** [comment] 2020-09-02 17:32
Moving to 6.0, as this is by design for 5.0

**Comment by vitek-karas** [comment] 2021-01-05 14:27
Note that there are existing tests around `FullyQualifiedName` which are wrong. https://github.com/dotnet/runtime/blob/master/src/installer/tests/Microsoft.NET.HostModel.Tests/AppHost.Bundle.Tests/SingleFileApiTests.cs

These tests don't use SDK to produce the single-file, they use SDK to produce a self-contained build of an application and then run the bundler manually to "convert" it to a single-file. This manual step is mostly in https://github.com/dotnet/runtime/blob/6e111ea8695635624147227cf685fd6769b88ea4/src/installer/tests/Microsoft.NET.HostModel.Tests/Helpers/BundleHelper.cs#L126

This manual step does not fully duplicate functionality in SDK, namely it will copy `mscorrc.dll` into the output (since it's a native library and thus left next to the single-file). This makes the `Module.FullyQualifiedName` API to actually work. But in real SDK produced single-file the `mscorrc.dll` is omitted in the output. This is sort of mentioned in the [design doc](https://github.com/dotnet/designs/blob/main/accepted/2020/single-file/design.md#host-builds):
> Certain additional binaries may be optionally included with the app to enable debugging scenarios. The work to not require these binaries as separate files on disk alongside the app is ongoing.
> * For exception stack trace source information, error string resources on Windows: Microsoft.DiaSymReader.Native.amd64.dll, mscorrc.debug.dll, mscorrc.dll

But in the case of `FullyQualifiedName` this causes a runtime failure because the value for in-memory modules should be `<Unknown>` which is actually localized and thus loaded from resources. If the resources are missing (`mscorrc.dll`) runtime will fail with `FileNotFoundException` (which itself will have no message, since again we can't load resources).

**Comment by jkotas** [comment] 2021-01-05 16:16
> `<Unknown>` which is actually localized

We should stop localizing this and just return hardcoded `<Unknown>`

**Comment by vitek-karas** [comment] 2021-01-26 12:16
There's an important gotcha with this. The code simply looks for `mscorrc.dll` using `LoadLibrary`. If that file happens to be on path - the whole thing will work and not throw. Where this happens is for example VS developer console window - it has .NET Framework on path, which also contains `mscorrc.dll` which also has the same resource - so the .NET Core ends up loading resources from .NET Framework in this case.

Testing this should make sure that it doesn't run in cases where `mscorrc.dll` can be found elsewhere on the machine.

**Comment by RussKie** [comment] 2021-03-01 01:36
We get more users trying to run Windows Forms apps as single file and hitting this bug. It would be great to have a fix.

**Comment by agocke** [comment] 2021-03-02 22:24
This should be fixed as of 5.0.4 https://github.com/dotnet/runtime/pull/47565

**Closed by agocke** 2021-03-02 22:24 UTC
Labels: area-Single-File
