### ISSUE TITLE
[Bug] GenerateReferenceAssemblySource drops constraint

### ISSUE THREAD

**Issue by terrajobst** [dotnet/runtime#100843] opened 2024-04-09 22:46 UTC
A community member [pointed out to me](https://twitter.com/0x_F0/status/1777819523741052981) that `System.Enum.GetNames<TEnum>()` [dropped the `Enum` constraint](https://github.com/dotnet/runtime/blob/404b286b23093cd93a985791934756f64a33483e/src/libraries/System.Runtime/ref/System.Runtime.cs#L2439) while the [implementation still has it](https://github.com/dotnet/runtime/blob/404b286b23093cd93a985791934756f64a33483e/src/libraries/System.Private.CoreLib/src/System/Enum.cs#L220).

Running Git Blame revealed that this changed in e5d59bd65f6cc9c0f00cc863542cfda91d6f8355 by @jkotas.

It looks like the tool has dropped this constraint but not in all cases.

It would be good to understand why that is so we don't inadvertently change the reference assemblies.

**Comment by ericstj** [comment] 2024-04-10 00:43
We need to add APICompat support to check these: https://github.com/dotnet/sdk/issues/39659

The latest GenAPI handles this scenario.  I tested with a standalone lib that exposes a similar API and it emits:
```
        public static string[] GetNames<TEnum>()
            where TEnum : struct, System.Enum { throw null; }
```
So this gets fixed when we fix https://github.com/dotnet/sdk/issues/31088

**Comment by jkotas** [comment] 2024-04-10 04:59
> It looks like the tool has dropped this constraint but not in all cases.

The genapi tooling has number of issues.

The reformatting was motivated by work on new unrelated APIs. I wanted the ref sources to be auto-generated, but then noticed a lot of formatting inconsistencies in System.Runtime ref sources. I tried to keep just the style changes only and revert everything else, but missed this one. 

Thank you FlashOver for catching it!

**Comment by jkotas** [comment] 2024-04-10 05:43
Fixed by https://github.com/dotnet/runtime/pull/100844

The underlying problem is duplicate of issues listed in https://github.com/dotnet/runtime/issues/100843#issuecomment-2046256270 .

**Closed by jkotas** 2024-04-10 05:43 UTC
Labels: area-Infrastructure-libraries, untriaged
