### ISSUE TITLE
Test failure Interop/NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.sh

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#85212] opened 2023-04-23 01:33 UTC
**Failed in:** runtime-coreclr ilasm 20230422.1

**Failed tests:**
```
coreclr linux x64 Checked ilasmroundtrip @ Ubuntu.1804.Amd64.Open
    - Interop/NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.sh
coreclr windows x86 Checked ilasmroundtrip @ Windows.10.Amd64.Open
    - Interop\\NativeLibrary\\API\\NativeLibraryTests\\NativeLibraryTests.cmd
coreclr osx arm64 Checked ilasmroundtrip @ OSX.1200.ARM64.Open
    - Interop/NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.sh
coreclr windows x64 Checked ilasmroundtrip @ Windows.10.Amd64.Open
    - Interop\\NativeLibrary\\API\\NativeLibraryTests\\NativeLibraryTests.cmd
coreclr linux arm64 Checked ilasmroundtrip @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8
    - Interop/NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.sh
coreclr linux arm Checked ilasmroundtrip @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7
    - Interop/NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.sh
coreclr windows arm64 Checked ilasmroundtrip @ Windows.11.Arm64.Open
    - Interop\\NativeLibrary\\API\\NativeLibraryTests\\NativeLibraryTests.cmd
coreclr osx x64 Checked ilasmroundtrip @ OSX.1200.Amd64.Open
    - Interop/NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.sh
coreclr windows arm64 Checked ilasmroundtrip @ Windows.11.Arm64.Open
    - Interop\\DllImportAttribute\\DllImportPath\\DllImportPathTest\\DllImportPathTest.cmd
```

**Error message:**
```
 
Return code:      1
Raw output file:      /datadisks/disk1/work/95D10907/w/9BDE089D/uploads/Reports/Interop.NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.output.txt
Raw output:
BEGIN EXECUTION
/datadisks/disk1/work/95D10907/p/ildasm -raweh -unicode -out=NativeLibraryTests.dasm.il NativeLibraryTests.dll
/datadisks/disk1/work/95D10907/p/ilasm -output=NativeLibraryTests.asm.dll NativeLibraryTests.dasm.il

.NET IL Assembler.  Version 8.0.0-ci
Copyright (c) Microsoft Corporation.  All rights reserved.
Assembling &#39;NativeLibraryTests.dasm.il&#39;  to EXE --&gt; &#39;NativeLibraryTests.asm.dll&#39;
Source file is UNICODE

Assembled method Microsoft.CodeAnalysis.EmbeddedAttribute::.ctor
Assembled method System.Runtime.CompilerServices.NullableAttribute::.ctor
Assembled method System.Runtime.CompilerServices.NullableAttribute::.ctor
Assembled method System.Runtime.CompilerServices.NullableContextAttribute::.ctor
Assembled method System.Runtime.CompilerServices.NullablePublicOnlyAttribute::.ctor
Assembled method GetLibraryExportTests�&lt;&gt;c__DisplayClass8_0::.ctor
Assembled method GetLibraryExportTests�&lt;&gt;c__DisplayClass8_0::&lt;GetLibraryExport&gt;b__0
Assembled method GetLibraryExportTests�&lt;&gt;c__DisplayClass9_0::.ctor
Assembled method GetLibraryExportTests�&lt;&gt;c__DisplayClass9_0::&lt;TryGetLibraryExport&gt;b__0
Assembled method GetLibraryExportTests::.ctor
Assembled method GetLibraryExportTests::GetValidExport_ManualMangling
Assembled method GetLibraryExportTests::GetValidExport
Assembled method GetLibraryExportTests::NullHandle
Assembled method GetLibraryExportTests::NullExport
Assembled method GetLibraryExportTests::ExportDoesNotExist
Assembled method GetLibraryExportTests::Dispose
Assembled method GetLibraryExportTests::GetLibraryExport
Assembled method GetLibraryExportTests::TryGetLibraryExport
Assembled method GetLibraryExportTests::RunExportedFunction
Assembled method GetMainProgramHandleTests�&lt;&gt;c__DisplayClass9_0::.ctor
Assembled method GetMainProgramHandleTests�&lt;&gt;c__DisplayClass9_0::&lt;GetSymbolFromMainProgramHandle&gt;b__0
Assembled method GetMainProgramHandleTests::CanAccessCoreRunExportFromMainProgramHandle
Assembled method GetMainProgramHandleTests::NativeLibraryLoadDoesNotLoadSymbolsGlobally
Assembled method GetMainProgramHandleTests::GloballyLoadedLibrarySymbolsVisibleFromMainProgramHandle
Assembled method GetMainProgramHandleTests::InvalidSymbolName_Fails
Assembled method GetMainProgramHandleTests::GloballyLoadedLibrarySymbolsVisibleFromMainProgramHandle_Mangling
Assembled method GetMainProgramHandleTests::FreeMainProgramHandle
Assembled method GetMainProgramHandleTests::get_IsHostedByCoreRun
Assembled method GetMainProgramHandleTests::GetSymbolFromMainProgramHandle
Assembled method GetMainProgramHandleTests::LoadLibraryGlobally
Assembled method GetMainProgramHandleTests::.ctor
Assembled method GetMainProgramHandleTests::.cctor
Assembled method NativeLibraryTests�&lt;&gt;c__DisplayClass24_0::.ctor
Assembled method NativeLibraryTests�&lt;&gt;c__DisplayClass24_0::&lt;LoadLibrary_NameOnly&gt;b__0
Assembled method NativeLibraryTests�&lt;&gt;c__DisplayClass25_0::.ctor
Assembled method NativeLibraryTests�&lt;&gt;c__DisplayClass25_0::&lt;TryLoadLibrary_NameOnly&gt;b__0
Assembled method NativeLibraryTests�&lt;&gt;c__DisplayClass26_0::.ctor
Assembled method NativeLibraryTests�&lt;&gt;c__DisplayClass26_0::&lt;LoadLibrary_WithAssembly&gt;b__0
Assembled method NativeLibraryTests�&lt;&gt;c__DisplayClass27_0::.ctor
Assembled method NativeLibraryTests�&lt;&gt;c__DisplayClass27_0::&lt;TryLoadLibrary_WithAssembly&gt;b__0
Assembled method NativeLibraryTests�&lt;&gt;c__DisplayClass28_0::.ctor
Assembled method NativeLibraryTests�&lt;&gt;c__DisplayClass28_0::&lt;FreeLibrary&gt;b__0
Assembled method NativeLibraryTests::.ctor
Assembled method NativeLibraryTests::LoadLibraryFullPath_NameOnly
Assembled method NativeLibraryTests::LoadLibraryOnNonExistentFile_NameOnly
Assembled method NativeLibraryTests::LoadLibraryOnInvalidFile_NameOnly
Assembled method NativeLibraryTests::LoadLibraryRelativePaths_NameOnly
Assembled method NativeLibraryTests::LoadLibraryFullPath
```

**Stack trace:**
```
   at Interop_NativeLibrary._API_NativeLibraryTests_NativeLibraryTests_._API_NativeLibraryTests_NativeLibraryTests_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2023-04-22T20:58:11.517Z | runtime-coreclr ilasm | Checked-ilasmroundtrip | osx.1200.arm64.open | arm64 | Interop/NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.sh | Failed | {"System.PhaseName":"run_test_p1__osx_arm64_checked","DefinitionName":"runtime-coreclr ilasm","operatingSystem":"OSX.1200.ARM64.Open","BuildId":"248912","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionId":"140","System.JobName":"__default","System.StageAttempt":"1","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","Project":"public","System.StageName":"Build","BuildNumber":"20230422.1","AzurePipelinesTestRunId":"4808456","System.JobAttempt":"1","Reason":"Schedule","architecture":"arm64","System.PhaseAttempt":"1","configuration":"Checked-ilasmroundtrip"} | Schedule
2023-04-22T20:51:47.248Z | runtime-coreclr ilasm | Checked-ilasmroundtrip | osx.1200.amd64.open | x64 | Interop/NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.sh | Failed | {"AzurePipelinesTestRunId":"4808286","Reason":"Schedule","System.StageAttempt":"1","configuration":"Checked-ilasmroundtrip","architecture":"x64","System.JobAttempt":"1","System.PhaseName":"run_test_p1__osx_x64_checked","System.JobName":"__default","operatingSystem":"OSX.1200.Amd64.Open","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","Project":"public","DefinitionId":"140","BuildId":"248912","System.PhaseAttempt":"1","System.StageName":"Build","BuildNumber":"20230422.1","DefinitionName":"runtime-coreclr ilasm"} | Schedule
2023-04-22T20:19:59.066Z | runtime-coreclr ilasm | Checked-ilasmroundtrip | ubuntu.1804.amd64.open.rt | x64 | Interop/NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.sh | Failed | {"AzurePipelinesTestRunId":"4808064","BuildId":"248912","System.PhaseAttempt":"1","System.StageAttempt":"1","Project":"public","System.JobName":"__default","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobId":"6dfec640-5b96-5d95-2a5b-7c236ea2d5c5","DefinitionId":"140","BuildNumber":"20230422.1","Reason":"Schedule","System.StageName":"Build","System.JobAttempt":"1","architecture":"x64","operatingSystem":"Ubuntu.1804.Amd64.Open","configuration":"Checked-ilasmroundtrip","System.PhaseName":"run_test_p1__linux_x64_checked","DefinitionName":"runtime-coreclr ilasm"} | Schedule
2023-04-22T20:19:12.453Z | runtime-coreclr ilasm | Checked-ilasmroundtrip | ubuntu.1804.armarch.open | arm | Interop/NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.sh | Failed | {"BuildNumber":"20230422.1","BuildId":"248912","DefinitionId":"140","Reason":"Schedule","operatingSystem":"(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7","CollectionUri":"https://dev.azure.com/dnceng-public/","DefinitionName":"runtime-coreclr ilasm","System.StageAttempt":"1","System.JobName":"__default","System.PhaseAttempt":"1","System.JobId":"860c965f-b28e-50d5-65d2-e40bd59f3a69","System.JobAttempt":"1","AzurePipelinesTestRunId":"4808060","architecture":"arm","configuration":"Checked-ilasmroundtrip","System.StageName":"Build","Project":"public","System.PhaseName":"run_test_p1__linux_arm_checked"} | Schedule
2023-04-22T20:18:13.714Z | runtime-coreclr ilasm | Checked-ilasmroundtrip | ubuntu.1804.armarch.open | arm64 | Interop/NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.sh | Failed | {"System.StageAttempt":"1","System.PhaseAttempt":"1","architecture":"arm64","BuildNumber":"20230422.1","AzurePipelinesTestRunId":"4808058","CollectionUri":"https://dev.azure.com/dnceng-public/","operatingSystem":"(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8","BuildId":"248912","DefinitionId":"140","System.StageName":"Build","Project":"public","Reason":"Schedule","System.JobAttempt":"1","configuration":"Checked-ilasmroundtrip","DefinitionName":"runtime-coreclr ilasm","System.JobId":"34b2f53b-add1-5e74-7a39-5a11483297fc","System.PhaseName":"run_test_p1__linux_arm64_checked","System.JobName":"__default"} | Schedule
2023-04-15T20:59:21.517Z | runtime-coreclr ilasm | Checked-ilasmroundtrip | osx.1200.arm64.open | arm64 | Interop/NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.sh | Failed | {"Reason":"Schedule","System.StageAttempt":"1","DefinitionId":"140","operatingSystem":"OSX.1200.ARM64.Open","System.PhaseName":"run_test_p1__osx_arm64_checked","System.JobAttempt":"1","System.StageName":"Build","System.JobName":"__default","DefinitionName":"runtime-coreclr ilasm","Project":"public","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230415.1","AzurePipelinesTestRunId":"4623672","configuration":"Checked-ilasmroundtrip","System.PhaseAttempt":"1","architecture":"arm64","BuildId":"240791"} | Schedule
2023-04-15T20:54:31.335Z | runtime-coreclr ilasm | Checked-ilasmroundtrip | osx.1200.amd64.open | x64 | Interop/NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.sh | Failed | {"System.JobName":"__default","operatingSystem":"OSX.1200.Amd64.Open","System.JobId":"bf644a0b-2dbe-5a03-d8c6-a86fdd97c823","architecture":"x64","BuildId":"240791","DefinitionId":"140","Reason":"Schedule","DefinitionName":"runtime-coreclr ilasm","System.StageAttempt":"1","Project":"public","System.PhaseName":"run_test_p1__osx_x64_checked","BuildNumber":"20230415.1","configuration":"Checked-ilasmroundtrip","System.PhaseAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobAttempt":"1","AzurePipelinesTestRunId":"4623660","System.StageName":"Build"} | Schedule
2023-04-15T20:22:33.309Z | runtime-coreclr ilasm | Checked-ilasmroundtrip | ubuntu.1804.armarch.open | arm64 | Interop/NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.sh | Failed | {"System.JobAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","BuildNumber":"20230415.1","Project":"public","AzurePipelinesTestRunId":"4623248","System.StageAttempt":"1","architecture":"arm64","BuildId":"240791","DefinitionName":"runtime-coreclr ilasm","configuration":"Checked-ilasmroundtrip","System.StageName":"Build","Reason":"Schedule","DefinitionId":"140","System.JobId":"34b2f53b-add1-5e74-7a39-5a11483297fc","System.PhaseName":"run_test_p1__linux_arm64_checked","System.PhaseAttempt":"1","System.JobName":"__default","operatingSystem":"(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8"} | Schedule
2023-04-15T20:19:35.641Z | runtime-coreclr ilasm | Checked-ilasmroundtrip | ubuntu.1804.amd64.open.rt | x64 | Interop/NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.sh | Failed | {"CollectionUri":"https://dev.azure.com/dnceng-public/","architecture":"x64","BuildId":"240791","Project":"public","configuration":"Checked-ilasmroundtrip","AzurePipelinesTestRunId":"4623240","BuildNumber":"20230415.1","DefinitionId":"140","System.PhaseName":"run_test_p1__linux_x64_checked","DefinitionName":"runtime-coreclr ilasm","operatingSystem":"Ubuntu.1804.Amd64.Open","System.JobAttempt":"1","System.StageName":"Build","System.PhaseAttempt":"1","System.JobId":"6dfec640-5b96-5d95-2a5b-7c236ea2d5c5","System.JobName":"__default","System.StageAttempt":"1","Reason":"Schedule"} | Schedule
2023-04-15T20:19:09.603Z | runtime-coreclr ilasm | Checked-ilasmroundtrip | ubuntu.1804.armarch.open | arm | Interop/NativeLibrary/API/NativeLibraryTests/NativeLibraryTests.sh | Failed | {"System.StageAttempt":"1","System.JobName":"__default","System.PhaseAttempt":"1","Project":"public","AzurePipelinesTestRunId":"4623234","System.JobAttempt":"1","Reason":"Schedule","DefinitionName":"runtime-coreclr ilasm","architecture":"arm","System.StageName":"Build","System.JobId":"860c965f-b28e-50d5-65d2-e40bd59f3a69","BuildNumber":"20230415.1","operatingSystem":"(Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7","System.PhaseName":"run_test_p1__linux_arm_checked","configuration":"Checked-ilasmroundtrip","BuildId":"240791","DefinitionId":"140","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule

**Comment by AaronRobinsonMSFT** [comment] 2023-05-01 08:05
Duplicate of https://github.com/dotnet/runtime/issues/84914

**Closed by AaronRobinsonMSFT** 2023-05-01 08:05 UTC
Labels: arch-arm64, arch-x86, os-linux, os-mac-os-x, os-windows, arch-x64, area-Interop-coreclr, untriaged, blocking-clean-ci-optional
