### ISSUE TITLE
WASM GC Proposal and .NET

### ISSUE THREAD

**Issue by syedqutub** [dotnet/runtime#82992] opened 2023-03-05 06:52 UTC
I have heard that Google dart is moving to wasm with the help of the gc proposal. Does this mean .net may also move to wasm gc in future?

**Comment by En3Tho** [comment] 2023-03-05 08:56
Duplicate of https://github.com/dotnet/runtime/issues/82974

**Closed** 2023-03-05 10:47 UTC
Labels: area-GC-coreclr, untriaged

**Comment by En3Tho** [comment] 2023-03-06 21:27
@Maoni0 Thanks. I reposted your message in that other issue
