### ISSUE TITLE
Cannot inject a singleton object into Startup's ctor

### ISSUE THREAD

**Issue by justinushermawan** [dotnet/runtime#1749] opened 2020-01-15 04:18 UTC
I need to inject a singleton `AppSettings` instance into my `Startup`'s constructor, in there I'll set its initial value and will be injected then into my MVC controllers to be used by those. The snippet codes as below.

```
public Startup(IConfiguration configuration, AppSettings appSettings)
{
     Configuration = configuration;
            
     appSettings.cacheDirPath = Path.Combine(Directory.GetCurrentDirectory(),
     Configuration.GetValue<string>("GitLab:cache_dir_name"));
     DirectoryInfo di = new DirectoryInfo(appSettings.cacheDirPath);
     if (!di.Exists)
     {
          di.Create();
     }
}

public AppSettings AppSettings { get; set; }

public void ConfigureServices(IServiceCollection services)
{
     ...
     services.AddSingleton<AppSettings>();
}
```

Unexpectedly, it throws an exception like this:
```
2020-01-13 16:35:15.0945||ERROR|App.Program|Stopped program because of exception System.InvalidOperationException: Unable to resolve service for type 'App.AppSettings' while attempting to activate 'App.Startup'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
```

How to resolve this issue?

**Comment by vitek-karas** [comment] 2020-01-20 08:55
I think this would get more answers if filed in ASP.NET Core repo: https://github.com/dotnet/aspnetcore/issues

Maybe somebody with access can move it over there?

**Comment by jeffschwMSFT** [comment] 2020-01-21 17:18
@Pilchie

**Comment by Pilchie** [comment] 2020-01-21 17:48
This is a duplicate of https://github.com/aspnet/Announcements/issues/353.

**Closed by Pilchie** 2020-01-21 17:48 UTC
Labels: untriaged
