### ISSUE TITLE
SocketException (10060) in HTTP 1.1 stress tests

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#59086] opened 2021-09-14 13:47 UTC
In #50854 I concluded that the root cause of the 10060 connection errors is the Windows firewall, which has been disabled for Windows runs in #52381, reducing the number of failures. However, looking at today's CI runs it seems like the issue is still present, failing about 5-10% of the Windows runs. 

It's very hard to decide if some sort of regression happened, or 10060 just kept living with a lower frequency. In either case, I believe it's very unlikely that this is an issue with .NET Http / Socket code.

**Comment by karelz** [comment] 2021-09-14 13:55
@antonfirsov is the frequency now higher? (perhaps some regression might have sneaked in)
Is it similar frequency in main and release/6.0 branches? (6.0 branches are a bit more flaky due to used HW differences)

**Comment by antonfirsov** [comment] 2021-09-14 14:02
> Is it similar frequency in main and release/6.0 branches? 

We don't have enough data to decide, the first nightly 6.0 run is about 10 days old.

> is the frequency now higher?

I can't answer that without a full analysis of the logs of the last 2-3 months. (The focus was on high frequency failures before.)

**Comment by karelz** [comment] 2021-09-14 14:27
Oh, I thought this is high frequency failure. If it is not near the top, I am fine waiting until it is near top of the failures to investigate ...

**Comment by karelz** [comment] 2022-07-21 12:15
Triage: We didn't see it pop up lately. If we discover it in stress runs again, we will reopen. Closing.

**Closed by karelz** 2022-07-21 12:15 UTC
Labels: area-System.Net.Http
