### ISSUE TITLE
JIT Intristics for typeof(T).IsX

### ISSUE THREAD

**Issue by exyi** [dotnet/runtime#67113] opened 2022-03-24 19:42 UTC
### Description

typeof(T).IsValueType is optimized into a constant in a generic method. Is there a reason why other System.Type.IsX properties (for example IsEnum) are not folded into a constant when the method is specialized for a type? I'd specifically find the `IsEnum` useful, but it seems to me that providing support for constant folding of all Type properties would be quite useful.

```csharp
public bool OptimizedNicely<T>() {
    return typeof(T).IsValueType;
//     mov eax, 1
//     ret

}
public bool WhyNotThisOne<T>() {
    return typeof(T).IsEnum;
//    sub rsp, 0x28
//    mov rcx, 0x7ffd095c9480
//    call 0x00007ffd68fbd020
//    mov rcx, rax
//    mov rax, [0x7ffd09527fd0]
//    add rsp, 0x28
//    jmp rax
}
```

### Configuration

.NET 6 x64, can be replicated using [sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACAZQAtsoAHAGW2ADoASgFcAdhgCW+GAG4aNYgGYGZBgGEGAbxoMdDANoApcRgDiMETCjiwACgwBPDjAgAzG+LEBKTwF1tuxQZgCAgAGwYAeQ4JfHEALxgAEwA5axhQ+wAeABUAPhtPTX9dAIB2BgcnVxtszz4ASVwANWxQoRhsxxlihgBfHsNjMwsrW0rnNw8Mbz9qEsDgsIYAdRZ7ZIgMbJZxXAiLHPzCrTmSsoqu6tqG3ABRESF8WVOdfupeoA==)

### Workaround

Surprisingly, using `typeof(Enum).IsAssignableFrom(typeof(T))` [works](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACAZQAtsoAHAGW2ADoASgFcAdhgCW+GAG4aNYgGYGZBgGEGAbxoMdDANoApcRgDiMETCjiwACgwBPDjAgAzG+LEBKT2gZHT5pbWdo7ObgAi2BgwACqSMADSHgAm3gC62rqKDMAQEAA2fjAAVgA8MQB8Np6ambpZAOwMDk6uNgCiIkL4nnwAkrgAgri44gDmIrz5MABiUBD4Ia1uMd6y1PUAvjSbQA==):

```csharp
public bool Jej<T>() {
    return typeof(Enum).IsAssignableFrom(typeof(T));
}
```

However, this workaround may not help for the other cases (like `IsGeneric` or `IsPrimitive`)

**Comment by teo-tsirpanis** [comment] 2022-03-24 19:58
Duplicate of #4920.

**Closed by teo-tsirpanis** 2022-03-24 19:58 UTC
Labels: tenet-performance, area-CodeGen-coreclr, untriaged
