### ISSUE TITLE
Cannot read appsettings.json if you used Microsoft.EntityFrameworkCore.Tools 8.0-preview

### ISSUE THREAD

**Issue by mis2000lab** [dotnet/runtime#89284] opened 2023-07-21 01:49 UTC
### Description

My VS2022 Preview version (on Windows 10 and for .NET **8.0 preview**) is 17.7.0 Preview **4**.0 and 17.7.0 Preview **3**.0

**1. Cannot read appsettimgs.json** 

Error Message : 
_An error occurred while starting the application.
TypeLoadException: Could not load type 'System.Buffers.SearchValues' from assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
System.Text.Json.JsonReaderHelper..cctor()_

_TypeInitializationException: The type initializer for 'System.Text.Json.JsonReaderHelper' threw an exception.
System.Text.Json.JsonReaderHelper.GetUtf8ByteCount(ReadOnlySpan<char> text)_

_InvalidDataException: Failed to load configuration from file 'C:\Users\WebApplication2022_NetCore8_MVC\appsettings.json'.
Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(bool reload)_

_TypeLoadException: Could not load type 'System.Buffers.SearchValues' from assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
System.Text.Json.JsonReaderHelper..cctor()_

**2. Always point a error  "var builder = WebApplication.CreateBuilder(args);" in Program.cs**

### Reproduction Steps

Maybe I find the error root cause is **NuGet package - "Microsoft.EntityFrameworkCore.Tools"**
It cause this error , when i uninstall it then error disappear.

if version 7.0.9 (stable version), it's ok.
if version is 8.0-preview-xxxxx, it will cause error.

### Expected behavior

.NET 6.0 , 7.0 it's normal.
I have tested many times and find root cause is NuGet package - "Microsoft.EntityFrameworkCore.Tools"

### Actual behavior

NuGet package - "Microsoft.EntityFrameworkCore.Tools"
if version is 8.0-preview-xxxxx, it will cause error.

**Comment by layomia** [comment] 2023-07-21 17:54
cc @ViktorHofer / @ericstj for a sanity check wrt. packaging.

**Comment by ericstj** [comment] 2023-07-21 20:09
https://github.com/dotnet/runtime/commit/80739c2adb869911cc0fd56a335fc1e68e38f63b renamed this type from `IndexOfAnyValues` to `SearchValues`.  That fix first shipped in 8.0 preview 5.  Can you please ensure that you're using the 8.0 Preview5 runtime or later?

This behavior would happen if you're using newer 8.0 preview packages and an older runtime.  The packages expect the runtime changes to match the version they were built against.  This sort of problem is pretty common during previews as we add new API and consume it in packages shipping at the same time.

**Comment by eiriktsarpalis** [comment] 2023-07-27 12:33
I think we can close this on the assumption that this is caused by https://github.com/dotnet/runtime/issues/89284#issuecomment-1646187529. @mis2000lab feel free to reopen if you're still experiencing the issue.

**Closed by eiriktsarpalis** 2023-07-27 12:33 UTC
Labels: question, area-System.Text.Json, needs-author-action
