### ISSUE TITLE
System.Text.Json deserialize fails on List<Tuple<,>> with trimming

### ISSUE THREAD

**Issue by michaldobrodenka** [dotnet/runtime#73169] opened 2022-08-01 18:16 UTC
### Description

Class:

```
public class Example
{
public List<Tuple<double, string>> Values { get; set; }
}
```

fails to deserialize when published as self contained and trim mode link. (linux-arm, I haven't tried other platforms). When using trim mode CopyUsed - everything works, but my app is almost 50% bigger.

json example:
```
{"Values":[{"Item1":10,"Item2":"10"}]}
```

### Reproduction Steps

small example compiled as self contained and 

```JsonSerializer.Deserialize<Example>(str);```

### Expected behavior

To deserialize json.

### Actual behavior

Exception:
```
JSON Deserialize exception: System.ArgumentNullException: Value cannot be null. (Parameter 'obj')
   at System.OrdinalIgnoreCaseComparer.GetHashCode(String )
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.ParameterLookupKey.GetHashCode()
   at System.Collections.Generic.Dictionary`2.FindValue(TKey )
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.InitializeConstructorParameters(JsonParameterInfoValues[] , Boolean )
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo..ctor(Type , JsonConverter , Type , JsonSerializerOptions )
   at System.Text.Json.JsonSerializerOptions.<InitializeForReflectionSerializer>g__CreateJsonTypeInfo|112_0(Type , JsonSerializerOptions )
   at System.Text.Json.JsonSerializerOptions.GetClassFromContextOrCreate(Type )
   at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type )
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.get_ElementTypeInfo()
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , TCollection& )
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , T& )
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object , ReadStack& , Utf8JsonReader& )
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , T& )
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , T& )
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , TCollection& )
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , T& )
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object , ReadStack& , Utf8JsonReader& )
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , T& )
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , T& )
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object , ReadStack& , Utf8JsonReader& )
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , T& )
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , T& )
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , TCollection& )
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& , Type , JsonSerializerOptions , ReadStack& , T& )
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& , JsonSerializerOptions , ReadStack& )
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 , JsonTypeInfo , Nullable`1 )
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 , JsonTypeInfo )
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String , JsonSerializerOptions )
```

### Regression?

Yes. It was working in NET5. After installing NET6 it doesn't work in NET5. Net6 linker is used to compile NET5 project?

### Known Workarounds

Use TrimMode=CopyUsed

### Configuration

-r linux-arm -p:PublishTrimmed=True -p:TrimMode=CopyUsed --self-contained true -c Release -f net6.0

**Comment by eiriktsarpalis** [comment] 2022-08-01 20:07
Stacktrace appears related to #58690.

**Comment by agocke** [comment] 2022-08-01 20:24
@michaldobrodenka did your app produce trim warnings when you were linking?

**Comment by MichalStrehovsky** [comment] 2022-08-02 02:17
> Yes. It was working in NET5. After installing NET6 it doesn't work in NET5. Net6 linker is used to compile NET5 project?

Yes, the trimming is done by the SDK. It uses compatible settings, but the underlying trimming optimizations can be different. If this is indeed the same issue as analyzed in #58690, the underlying problem is that one of the new trimming optimizations is to remove parameter names of methods that were not visible targets of reflection and this is breaking System.Text.Json.

Reflection-based System.Text.Json has a lot of other trimming related problems. The only configuration of System.Text.Json that is well-supported with trimming is the [source generated one](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-source-generation) (@eiriktsarpalis do we document this somewhere?). Anything else might require extra work in terms of trimming annotations (the publishing process will generate warnings and such apps need to be thoroughly re-tested after trimming). The annotation required here is likely to make it visible that the constructors of `Tuple<,>` are reflection-accessed.

> @michaldobrodenka did your app produce trim warnings when you were linking?

If the target framework is .NET 5, we wouldn't produce warnings because at that time trimming was in preview and the warnings were suppressed.

Cc @vitek-karas @sbomer

**Comment by michaldobrodenka** [comment] 2022-08-02 06:49
ok, I found a nice workaround. 

instead of `List<Tuple<double, string>>` I use `List<ExampleValueItem>` and ValueItem is 

```
    public class ExampleValueItem
    {
        public double Item1 { get; set; }

        public string Item2 { get; set; }
    }
```

Since I don't need generics here it's ok for me.  For backward compatibility members are named Item1/2, but that's ok. In future I'll try not to be lazy and create class for use case like this.

My app is back on linking.

What was interesting that excluding System.Text.Json from trimming was not enough.

**Comment by MichalStrehovsky** [comment] 2022-08-02 06:54
> What was interesting that excluding System.Text.Json from trimming was not enough.

The problem is in removing parameter names on the constructor of the Tuple class and that one is in CoreLib. So you would need to disable trimming on CoreLib.

> My app is back on linking.

The workaround works because ExampleValueItem is now defined in your assembly and I assume your assembly is not manifested as trimmable and it's not trimmed as a result. (By default, pretty much only the framework is trimmed.)

It would be the best to use the source generated Json. It will avoid problems like this (exception that is not possible to reason about or root cause easily).

**Comment by eiriktsarpalis** [comment] 2022-08-02 08:43
> The only configuration of System.Text.Json that is well-supported with trimming is the [source generated one](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-source-generation) (eiriktsarpalis do we document this somewhere?).

Yes, I would say it is fairly well-documented both in the API and conceptual doc level. See also https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-source-generation-modes

> ok, I found a nice workaround.

I would still recommend using the source generator in .NET 6 since the reflection-based serialization modes are not supported with trimming and could fail in unexpected ways.

I think we can close this as by-design. We should still update the reflection-based serializer to better anticipate trimmed parameter names and fail with a helpful error message, which is tracked by #58690.

**Closed by eiriktsarpalis** 2022-08-02 08:43 UTC
Labels: area-System.Text.Json, untriaged

**Comment by michaldobrodenka** [comment] 2022-08-02 11:19
@MichalStrehovsky  thank you for your comprehensive answer! really appreciate it.

I'll stay with my custom non generic class and will avoid serializing Tuples.

**Comment by agocke** [comment] 2022-08-02 18:47
One more note that [reflection-based serializers](https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/incompatibilities#reflection-based-serializers) are known to be incompatible with trimming and the recommendation is to use a source generated replacement, like the source-generated version of System.Text.Json that Eirik linked to.
