### ISSUE TITLE
[Mono WASM] CoreCLR tests on WASM: Interop tests failed due to lack of support on WASM

### ISSUE THREAD

**Issue by fanyang-mono** [dotnet/runtime#41519] opened 2020-08-28 15:03 UTC
### Description

The following tests are failing due to lack of Interop support on WASM:
- Interop/ICustomMarshaler/*
- Interop/NativeLibrary/*
- Interop/PInvoke/*
- Interop/UnmanagedCallersOnly/*

### Configuration

1. Get dotnet/runtime repo
2. Remove the test(s) that you would like to reproduce from `<repo_root>/src/coreclr/tests/issues.targets`
2. Build WASM: `./build.sh --os Browser --arch wasm --subset mono+libs -c Release`
3. Build runtime tests: `cd src/coreclr/ && ./build-test.sh -skipstressdependencies -excludemonofailures os Browser wasm Release`
4. To run all runtime tests, at the end of the runtime tests build log, there is "Example runtest.sh command". Use that command plus `wasm`. For example, for me it was
`./tests/runtest.sh --coreOverlayDir=/Users/fanyang/Documents/work/dotnet_naricc/runtime/artifacts/tests/coreclr/Browser.wasm.Release/Tests/Core_Root --testNativeBinDir=/Users/fanyang/Documents/work/dotnet_naricc/runtime/artifacts/obj/coreclr/Browser.wasm.Release/tests --testRootDir=/Users/fanyang/Documents/work/dotnet_naricc/runtime/artifacts/tests/coreclr/Browser.wasm.Release --copyNativeTestBin Release wasm`
5. To run a single test, you could do
```
set CORE_ROOT=<repo_root>/artifacts/tests/coreclr/Browser.wasm.Release/Tests/Core_Root     
<repo_root>/artifacts/tests/coreclr/Browser.wasm.Release/JIT/Methodical/switch/switch5/switch5.sh
```
### Regression?

No. WASM is a new product.

**Comment by fanyang-mono** [comment] 2020-08-28 15:04
One potential related issue https://github.com/mono/mono/issues/8007

**Comment by SamMonoRT** [comment] 2021-06-21 15:37
Not going to be fixed in 6.0

**Comment by ilonatommy** [comment] 2022-06-10 07:12
@fanyang-mono, what's the status on this?

**Comment by radical** [comment] 2022-06-10 18:58
Closing as duplicate of https://github.com/dotnet/runtime/issues/64127 .

**Closed by radical** 2022-06-10 18:58 UTC
Labels: arch-wasm, area-Interop-mono
