### ISSUE TITLE
Implement Thread Abort second pass redirection on Unix

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/runtime#72703] opened 2022-07-22 23:54 UTC
We never implemented the logic that handles rethrowing ThreadAbort exceptions after handlers on Unix. Right now we don't honor the redirect and continue execution after the funclet.

> I think implementing mechanism functionally equivalent to the `RedirectForThrowControl` on Unix is feasible. It needs to be implemented very differently though. The windows version relies on windows specific EH details that I think cannot be replicated reasonably on Unix. I think we would directly use the `DispatchManagedException` modified to optionally start at a passed in context. But I am not sure about the details, I just gave it a brief look.

_Originally posted by @janvorli in https://github.com/dotnet/runtime/issues/12739#issuecomment-1191565869_

**Comment by mangod9** [comment] 2022-08-03 18:57
@janvorli are you working on this?

**Comment by janvorli** [comment] 2022-08-03 19:15
No, I was considering this for 8.0.

**Comment by mangod9** [comment] 2022-08-03 19:56
@hoyosjs ok to move to 8 or is this blocking for 7?

**Comment by hoyosjs** [comment] 2022-08-03 21:56
Yup, i think 8 is fine.

**Comment by evolutionise** [comment] 2022-11-28 23:31
This is still causing a few problems for me on 6.0, using Rider on an M1 Mac on Monterey - are there any known workarounds? 
It would be great to get the fixes in sooner rather than later if possible - it's quite disruptive to debugging our application as it consistently happens with some EF objects. Any chance it could be included in one of the minor versions of 7?

**Comment by Will-Bill** [comment] 2022-12-21 20:12
This issue was first raised in May 22, 2019. It is now nearly 2023, I am stuck debugging a database issue but .NET debugger quits when viewing the object, meaning I can't see what the issue is.

This is such a terrible experience. I can't believe more noise is not made about this. Maybe because people dont know what to search.

".NET debugger crashes when viewing database entity" 

Please release this as a patch to .NET 7 and stop kicking the can down the road, i'd be very thankful.

**Comment by janvorli** [comment] 2022-12-21 20:59
@Will-Bill the crash was expected to be fixed in #72705. Are you still experiencing it?

**Comment by aspeckt-112** [comment] 2023-07-31 12:20
I'm still seeing this issue on macOS 13.3.1.

.NET SDK version 7.0.306

Microsoft.EntityFrameworkCore.SqlServer 7.0.9

**Closed** 2023-08-03 07:53 UTC
Labels: area-ExceptionHandling-coreclr, in-pr
