### ISSUE TITLE
AssemblyLoadContext Name creates invalid AssemblyName when Source Assembly was loaded from byte Array

### ISSUE THREAD

**Issue by jogibear9988** [dotnet/runtime#84295] opened 2023-04-04 12:29 UTC
### Description

DispatcheProxyGenerator fails cause the Name of the load Context wich is "Assembly.Load(byte[],...)", because it tries to Parse the Assembly Name via AssemblyNameParser, see screenshots for the stacktrace...

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/364896/229791695-2922be2b-e6e5-441d-9d12-10dbab6c5a73.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/364896/229791706-b6ff1c6a-1b8e-4e66-9602-5b8c1ff2110c.png)

### Reproduction Steps

I'll try to create one

### Expected behavior

It should work with an assembly load context created by a assembly loaded from byte arrays

### Actual behavior

does not work

### Regression?

Yes, it worked in Net6

### Known Workarounds

We patched "_name" of assemblyLoadcontext to null

**Comment by vitek-karas** [comment] 2023-04-04 12:37
This is duplicate of https://github.com/dotnet/runtime/issues/80387. And has been fixed (in 7.0) by https://github.com/dotnet/runtime/pull/82807.

@buyaa-n would know in exactly which release the fix should appear in.

**Comment by jogibear9988** [comment] 2023-04-04 13:20
@vitek-karas in wich 7.x version is this fixed?

**Comment by jogibear9988** [comment] 2023-04-04 13:23
befor i forget: @vitek-karas thanks for the info

**Comment by jogibear9988** [comment] 2023-04-04 13:26
the pull request sais 7.0.5, so I think it should be in next release

**Closed** 2023-04-04 13:26 UTC
Labels: area-AssemblyLoader-coreclr, untriaged

**Comment by buyaa-n** [comment] 2023-04-04 15:27
Yes it is included in next (April) release
