### ISSUE TITLE
[wasm][debugger] Windows drive letter is both uppercase and lowercase in chrome debugger

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#53036] opened 2021-05-20 18:11 UTC
![image](https://user-images.githubusercontent.com/271576/119028143-6af43b80-b9a7-11eb-9fc6-e977ea54e2f1.png)

- .NET 6 preview 5, Windows
- `dotnet workload install wasm-tools`
- `dotnet new blazorwasm`
- `dotnet run`
- in browser 'clrl+alt+D'

**Comment by lewing** [comment] 2021-05-21 19:51
I think we're getting these paths directly from the pdb data, I wonder why they are different there.  We can probably normalize this particular case in the proxy though.

**Comment by ilonatommy** [comment] 2022-02-22 09:56
On .NET 6, preview 7 - bug is still there. 
On main with HEAD at [5393bce](https://github.com/ilonatommy/runtime/commit/5393bce01195fc06bc47080ead01ea05896a3fbd) - could not reproduce. It seems to be fixed.

**Comment by ilonatommy** [comment] 2022-02-22 10:07
Could not reproduce on main:
![image](https://user-images.githubusercontent.com/32700855/155109884-f7c8cf07-e5d9-4d1a-a952-698d717f95a9.png)

In .NET 6, preview 7 the bug persists but it seems to have been fixed by now.

**Closed by ilonatommy** 2022-02-22 10:07 UTC
Labels: arch-wasm, area-Debugger-mono
