### ISSUE TITLE
System.Text.Json inconsistent behavior using JsonExtensionData on JsonObject

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/runtime#61080] opened 2021-11-02 00:47 UTC
### Description

When I use the `JsonExtensionData`, I found that the `JsonObject` is a little different from `Dictionary<string, object>`/`Dictionary<string, JsonElement>`, not sure if it‘s by design or a bug.

![image](https://user-images.githubusercontent.com/7604648/139767472-a8c39d27-2797-48c8-8f0d-ff7df081c8e5.png)

The last one is using the `JsonObject`, test code is below

### Reproduction Steps

``` c#
using static System.Console;

var p = JsonSerializer.Deserialize<Person>(jsonString);
ArgumentNullException.ThrowIfNull(p, nameof(p));
WriteLine(JsonSerializer.Serialize(p));

var p1 = JsonSerializer.Deserialize<Person1>(jsonString);
ArgumentNullException.ThrowIfNull(p1, nameof(p1));
WriteLine(JsonSerializer.Serialize(p1));

var p2 = JsonSerializer.Deserialize<Person2>(jsonString);
ArgumentNullException.ThrowIfNull(p2, nameof(p2));
WriteLine(JsonSerializer.Serialize(p2));

var p3 = JsonSerializer.Deserialize<Person3>(jsonString);
ArgumentNullException.ThrowIfNull(p3, nameof(p3));
WriteLine(JsonSerializer.Serialize(p3));


    public record Person(string Name, int Age);

    public record Person1(string Name, int Age) : Person(Name, Age)
    {
        [JsonExtensionData]
        public Dictionary<string, object?> Extensions { get; set; } = new();
    }

    public record Person2(string Name, int Age) : Person(Name, Age)
    {
        [JsonExtensionData]
        public Dictionary<string, JsonElement> Extensions { get; set; } = new(StringComparer.OrdinalIgnoreCase);
    }

    public record Person3(string Name, int Age) : Person(Name, Age)
    {
        [JsonExtensionData]
        public JsonObject? Extensions { get; set; }
    }
```

### Expected behavior

Maybe the `JsonObject` should behave as `Dictionary<string, object>`/`Dictionary<string, JsonElement>`

### Actual behavior

![image](https://user-images.githubusercontent.com/7604648/139767472-a8c39d27-2797-48c8-8f0d-ff7df081c8e5.png)

### Configuration

.NET 6 RC2
Windows
x64

**Comment by eiriktsarpalis** [comment] 2021-11-02 10:43
Thanks for reporting, this is a duplicate of #60560. Please consider upvoting that issue so we can prioritize accordingly.

**Closed by eiriktsarpalis** 2021-11-02 10:43 UTC
Labels: area-System.Text.Json, untriaged

**Comment by WeihanLi** [comment] 2021-11-02 14:42
Actually, I had seen that issue, but I'm not using the custom converter, I'm not sure if it's the same issue, so I opened this issue

**Comment by eiriktsarpalis** [comment] 2021-11-02 14:46
I think it's the same, see also #60806. In any case I made a note in the open issue so that both cases are accounted for.
