### ISSUE TITLE
ConfigurationBinder.GetValue<T> can raise InvalidOperationException with non-nullable value types

### ISSUE THREAD

**Issue by MattA48** [dotnet/runtime#42868] opened 2020-09-29 10:14 UTC
# ConfigurationBinder.GetValue<T> can raise InvalidOperationException with non-nullable value types

ConfigurationBinder.GetValue fails when there is no value in the config data and the type is a non-nullable value (i.e. bool). This also fails when given a default value with an InvalidOperationException

# General

.Net Core v 3.1.301

Call made to 
            bool test = config.GetValue<bool>("test");
or
            bool test = config.GetValue<bool>("test", false);

where config is of type IConfiguration, and the configuration file pointed to does not have a value for 'test'. I would expect the call to return default(bool) for the first case and the default value for the 2nd.

workaround for now is to use bool test = config.GetValue<bool?>("test") ?? false;

**Comment by ericstj** [comment] 2020-09-30 18:37
Looks like a reasonable request.  Moving to 6.0.0 as it is not a regression and has a workaround.

**Comment by davidfowl** [comment] 2020-10-28 12:42
OR we add a TryGetValue 😄

**Comment by grochoge** [comment] 2022-05-02 19:49
I'd prefer to have a method that would throw an exception if a configuration value doesn't exist. Right now the behavior is ConfigurationBinder.GetValue<T> is undocumented. Should I open another issue to request this function be documented?

**Comment by maryamariyan** [comment] 2022-05-03 21:12
>  Should I open another issue to request this function be documented?

yes, for docs, file the issue over on https://github.com/dotnet/dotnet-api-docs

**Comment by danielmpetrov** [comment] 2022-11-03 18:37
Cannot reproduce this, I'm getting the default value correctly. Has this been fixed or can you provide a reproduction snippet @MattA48?

**Comment by maryamariyan** [comment] 2022-11-08 22:16
closing since it seems to be not reproducible anymore as per @danielmpetrov 's comment.

**Closed by maryamariyan** 2022-11-08 22:16 UTC
Labels: bug, area-Extensions-Configuration
