### ISSUE TITLE
API Request: Method to temporarily disable Task synchronization

### ISSUE THREAD

**Issue by HaloFour** [dotnet/runtime#1448] opened 2020-01-08 15:01 UTC
It's a common problem when writing a C# library that does asynchronous tasks that the code ends up having to be littered with calls to `ConfigureAwait(false)` in order to avoid resuming on the synchronization context.  You need one of these calls for every single `Task` awaited and it's easy to miss one which can have adverse effects.

```cs
public async Task<Something> DoSomeStuff()
{
    var x = await DoSomething().ConfigureAwait(false);
    var y = await DoSomethingElse().ConfigureAwait(false);
    var z = await DoOtherStuff().ConfigureAwait(false);
    return await MixItAllTogether(x, y, z).ConfigureAwait(false);
}
```

There are numerous suggestions for changing C# to make it easier to disable the synchronization context, however that would also require either finding a generic way to expose synchronization through the awaiter pattern or making the language aware of how `Task` works and its supporting APIs, which would limit the amount of policy that could be expressed by other task-like libraries.

My understanding of `ConfigureAwait(false)` is that it ignores the `SynchronizationContext.Current` and `TaskScheduler.Current`.  Temporarily disabling `SynchronizationContext` is trivial.  However, my understanding is that resetting `TaskScheduler.Current` is not so trivial and involves running within a new `Task` configured with `TaskCreationOptions.HideScheduler`.  This is why I'm suggesting a new API, one that can reset both safely (as well as handle any other concerns).

My suggested API is something akin to the following:

```cs
public class Task
{
    public static DisabledSynchronizationDisposable DisableSynchronizationContext() { ... }
    public struct DisabledSynchronizationDisposable : IDisposable { ... }
}
```

The names are up for discussion, I don't particularly care what it's called as long as it's clear what it does.

What the API would do internally is capture the `SynchronizationContext.Current` and `TaskScheduler.Current`, then reset both to `null` and `Default` respectively.  The API would then return a struct implementing `IDisposable` that would restore the captured contexts.

The API would be used as follows:

```cs
public async Task<Something> DoSomeStuff()
{
    using (Task.DisableSynchronizationContext())
    {
        // no more sync context to worry about
        var x = await DoSomething();
        var y = await DoSomethingElse();
        var z = await DoOtherStuff();
        return await MixItAllTogether(x, y, z);
    }
}
```

If preferable, this API could return an awaitable instead of a disposable:

```cs
public async Task<Something> DoSomeStuff()
{
    await Task.DisableSynchronizationContext();

    // no more sync context to worry about
    var x = await DoSomething();
    var y = await DoSomethingElse();
    var z = await DoOtherStuff();
    return await MixItAllTogether(x, y, z);
}
```

**Disadvantages**: There is a danger that consuming code would not restore the synchronization context on completion of the method by not disposing the returned disposable.

**Comment by MithrilMan** [comment] 2020-01-08 15:15
It's unlikely that you'll have lot of await within the same method and this would decrease readability moving the behavior of async to another place (in this case on `DisableSynchronizationContext` call).

There is even the risk of abusing of this method, calling DisableSynchronizationContext on application start, causing code to be even more unreadable.

What then if you call a method that internally reset the SynchronizationContext and TaskScheduler to something else, within your using? It would cause your next await to not honor your DisableSynchronizationContext closure.

**Comment by HaloFour** [comment] 2020-01-08 15:25
@MithrilMan 

> It's unlikely that you'll have lot of await within the same method

This would also apply to any methods called by this method.

> There is even the risk of abusing of this method, calling DisableSynchronizationContext on application start, causing code to be even more unreadable.

Application code can already disable/override the synchronization context.  Most of it is as simple as `SynchronizationContext.SetSynchronizationContext(somethingElse)`.

> What then if you call a method that internally reset the SynchronizationContext and TaskScheduler to something else, within your using? It would cause your next await to not honor your DisableSynchronizationContext closure.

I don't see any problem with this.

**Comment by MithrilMan** [comment] 2020-01-08 15:35
> This would also apply to any methods called by this method.

causing code to be unreadable/unpredictable

> I don't see any problem with this.

```
using (Task.DisableSynchronizationContext())
    {
        // no more sync context to worry about
        var x = await DoSomething();

       CallToAMethodThatChangeBackContexts();
       // from this point, these awaits may act as ConfigureAwait(true)
       // race condition will not be fun to find now

        var y = await DoSomethingElse(); 
        var z = await DoOtherStuff();
        return await MixItAllTogether(x, y, z);
    }
```

**Comment by HaloFour** [comment] 2020-01-08 16:02
@MithrilMan 

All of those problems already exist.  I don't see why an API to make it easier in the common scenario makes that any worse, or any the potential for abuse by outside actors invalidates having such an API.

IMO, this is infinitely better and less error prone than trying to invent a new `await` keyword or syntax.

**Comment by airbreather** [comment] 2020-01-08 16:16
> If preferable, this API could return an awaitable instead of a disposable:

This only seems viable if the language also gets an enhancement similar to the proposal I put here: https://github.com/dotnet/csharplang/issues/645#issuecomment-565030255 to ensure that the suppressed context is restored before the async method completes.

**Comment by jnm2** [comment] 2020-03-29 13:53
> Disadvantages: There is a danger that consuming code would not restore the synchronization context on completion of the method by not disposing the returned disposable.

This would be another great reason for the BCL to ship with analyzers out of the box.

**Comment by stephentoub** [comment] 2023-01-21 20:22
Thanks for the suggestion.  While not exactly the same thing, I'm going to close this as a duplicate of https://github.com/dotnet/runtime/issues/29593. As you said, it's trivial to use SynchronizationContext via SetCurrent, and what's missing is a TaskScheduler.SetCurrent.  This proposal would also have the same issue that the other one has, which is that today there isn't a good way in the implementation to forcibly change TaskScheduler.Current, which is really just looking up what Task is currently running and getting its associated scheduler.  This proposal could instead set some other [ThreadStatic] flag or field, but that would in turn make most awaits more expensive as they'd now have another thread-static access (and while there are variations, they all similarly involve adding at least some overhead to the common path).

**Closed by stephentoub** 2023-01-21 20:22 UTC
Labels: api-suggestion, area-System.Threading.Tasks
