### ISSUE TITLE
System.Text.Json JsonSerializer.Deserialize() fails on lists in v5.0.x

### ISSUE THREAD

**Issue by Geoff-Holder** [dotnet/runtime#47881] opened 2021-02-04 23:01 UTC
JsonSerializer.Deserialize<IEnumerable\<someClass\>>(result);
Fails with the error:  **Constructor on type 'System.Text.Json.Serialization.Converters.IEnumerableOfTConverter not found**
in versions 5.0.1, 5.0.0
Rolling back to v4.7.2; works as described!

Example taken form https://platform.uno/docs/articles/howto-consume-webservices.html

**Comment by rperazzolli** [comment] 2021-02-10 13:20
Just like Geoff. In my case the UWP project works fine, but WASM fails. Switching to version 4.7.2 everything works fine.

**Comment by eiriktsarpalis** [comment] 2021-04-12 16:47
Hi @Geoff-Holder. Would it be possible to share a minimal reproduction demonstrating the issue? Please also include project configuration since we suspect this might be linker related.

Thanks.

**Comment by Geoff-Holder** [comment] 2021-04-23 08:18
Hi @eiriktsarpalis 
I have tried to reproduce the issue but cannot.
Since that time my dev machine (Win server 2016) was destroyed, Now currently developing on a Win10, VS has upgraded. the code has moved on somewhat,  - So I am anything but, like for like reproduction.
I also note that .net5 has this module built in, so am uncertain which module would be used when explicitly including a package. - or whether this is even implicated in the behavioural change (from then to now) or not.
If I discover anything further I will let you know!
Or if @rperazzolli could add anything!

**Comment by eiriktsarpalis** [comment] 2021-04-23 10:06
Thanks @Geoff-Holder. In that case I'm going to close the issue but feel free to reopen if new evidence comes up.

**Closed by eiriktsarpalis** 2021-04-23 10:06 UTC
Labels: area-System.Text.Json, needs more info, untriaged
