### ISSUE TITLE
FileSystemWatcher Renamed event has empty FullPath

### ISSUE THREAD

**Issue by Eveldee** [dotnet/runtime#50101] opened 2021-03-23 15:25 UTC
### Description

When using **FileSystemWatcher** on **Windows** (this bug doesn't occur for me on WSL1, Alpine musl) 
and a folder (or file without extension) is renamed to a **1 character long name**, the content of **FullPath** is **empty** in the event args.
Note that when this 1 character folder/file is renamed, the content of OldFullPath is correct and isn't empty.

Can be reproduced easily using this code and renaming a folder or a file to a 1 character long name in the user directory:

```cs
static void Main(string[] args)
{
	var watcher = new FileSystemWatcher(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile))
	{
		IncludeSubdirectories = true
	};

	watcher.Renamed += Watcher_Renamed;

	watcher.EnableRaisingEvents = true;

	Console.ReadKey(true);
}

private static void Watcher_Renamed(object sender, RenamedEventArgs e)
{
	Console.WriteLine($"Renamed {e.OldFullPath} to {e.FullPath} | {e.OldName}/{e.Name}");
}
```

### Configuration

Dotnet info:
```
OS Name:     Windows
OS Version:  10.0.19042
OS Platform: Windows
RID:         win10-x64
Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96
  ```

### Regression?

This bug doesn't seem to be a regression, it's reproducible on .Net Core 3.1

### Other information

Example output when renaming 'Test' to 'A' in C:\Users\Eveldee:
`Renamed C:\Users\Eveldee\Test to C:\Users\Eveldee\ | Test/`

**Comment by carlossanlop** [comment] 2021-03-25 17:28
Duplicate of https://github.com/dotnet/runtime/issues/45203

**Closed by carlossanlop** 2021-03-25 17:28 UTC
Labels: area-System.IO, untriaged
