### ISSUE TITLE
FileVersionInfo.FileVersion abnormal for C:\system32\notepad.exe

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#79077] opened 2022-12-01 10:02 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/FileVersionInfoFileVersion-abnormal-for/10198166)._

---
![filever.jpg](https://aka.ms/dc/image?name=B27799a80192a4419937574367550cb38638037337624347707_filever.jpg&tid=27799a80192a4419937574367550cb38638037337624347707)

I need to get the file version information for files.  
I use the following code to get file version  
But I got differenct FileVersion event if it show the same version in the file property.

```  
FileVersionInfo info = FileVersionInfo.GetVersionInfo(args[1]);
Console.WriteLine(info.FileVersion);
  
  
```

I copy the C:\\windows\\system32\\notepad.exe then rename it as “notepad2.exe”  
So the binary hash is the same. It also show the same verison in the file property.  
But if I get FileVersion through FileVersionInfo .FileVersion

the orginal notepad.exe show “**10.0.19041.2130 (WinBuild.160101.0800)**”  
the copy one show “**10.0.19041.1865 (WinBuild.160101.0800)**”

Do I call the wroing api to get file version?  
What is the correct api I need to call to get the correct file version?

## Remark
C:\system32\notepad.exe has the same issue

---
#### Tracy Wang [MSFT] on 11/11/2022, 08:28 AM: 

(private comment, text removed)
#### Kinki Wu on 11/11/2022, 08:51 AM: 

(private comment, text removed)
#### Kinki Wu on 12/1/2022, 04:56 AM: 

(private comment, text removed)
#### Feedback Bot on 11/17/2022, 09:08 AM: 

(private comment, text removed)
#### mapichov [MSFT] on 11/30/2022, 04:50 PM: 

(private comment, text removed)
#### mapichov [MSFT] on 11/30/2022, 05:09 PM: 

(private comment, text removed)
#### Marie Píchová on 12/1/2022, 11:03 AM: 

<p>Thank you for your reply. I was able to reproduce this on my machine with <code>cmd.exe</code>. Both <code>FileVersion</code> and <code>ProductVersion</code> have 1 as the private part, but the file properties as well as <code>FileVersionInfo.ProductPrivatePart</code> have 608. Once the file gets moved, the version strings correspond to the file properties.</p>
<p>I’ll move this issue to runtime repository, as I’m not expert on versioning.</p>

---
### Original Solutions
(no solutions)

**Comment by MSDN-WhiteKnight** [comment] 2022-12-03 09:21
Could this be related to resolving paths for [side-by-side assemblies](https://learn.microsoft.com/en-us/windows/win32/sbscs/about-side-by-side-assemblies-)? I.e. trying to resolve notepad.exe (system component) resolve s into some path under winsxs directory rather then system32, while for notepad2.exe (regular user program) it resolves directly from system32.

**Comment by adamsitnik** [comment] 2022-12-19 11:16
@tommcdon `FileVersionInfo` is part of `System.Diagnostics` namespace, so I've moved it to `area-System.Diagnostics`

**Comment by tommcdon** [comment] 2022-12-19 15:36
This seems to be part of System.Diagnostics.FileVersionInfo 
cc @ericstj

**Comment by ericstj** [comment] 2023-01-04 18:21
This is the correct API to get the fileversion.

Agreed that this could be a case of either SxS redirection, or [filesystem redirection](https://learn.microsoft.com/en-us/windows/win32/winprog64/file-system-redirector), or even an app-compat shim.

You could get tripped up by either of these if the copy step was happening outside your application and thus it might not be redirected in the same way.  That would explain the observed behavior.

I could not reproduce this on my machine using the following sample:
[filever.zip](https://github.com/dotnet/runtime/files/10346526/filever.zip)

Ultimately we just PInvoke to [GetFileversionEx](https://learn.microsoft.com/en-us/windows/win32/api/winver/nf-winver-getfileversioninfoexw) with the path passed in, so there is little opportunity for an issue unique to .NET here.  More likely we're getting "suprised" by the OS behavior.
 https://github.com/dotnet/runtime/blob/2f273648367ddf3c044ff0b5f37211126469ce8e/src/libraries/System.Diagnostics.FileVersionInfo/src/System/Diagnostics/FileVersionInfo.Windows.cs#L21

I hope this helps, let us know if you have further questions.

**Closed** 2023-02-02 00:02 UTC
Labels: question, area-System.Diagnostics, no-recent-activity, needs-author-action
