### ISSUE TITLE
[API Proposal]: IFloatingPointIeee754<T>.Lerp

### ISSUE THREAD

**Issue by PavielKraskouski** [dotnet/runtime#80044] opened 2022-12-29 15:05 UTC
### Background and motivation

_Lerp_ stands for [linear interpolation](https://en.wikipedia.org/wiki/Linear_interpolation). It can be widely used to mix two values with a given proportion.

### API Proposal

```csharp
namespace System.Numerics;

public interface IFloatingPointIeee754<T> where T : IFloatingPointIeee754<T>?
{
    static virtual T Lerp(T value1, T value2, T amount) => (value1 * (T.One - amount)) + (value2 * amount);
}
```

```csharp
namespace System;

public readonly struct Half : IFloatingPointIeee754<Half>
{
    public static Half Lerp(Half value1, Half value2, Half amount)
    {
        return value1 * (One - amount) + value2 * amount;
    }
}

public readonly struct Single : IFloatingPointIeee754<float>
{
    public static float Lerp(float value1, float value2, float amount)
    {
        return value1 * (One - amount) + value2 * amount;
    }
}

public readonly struct Double : IFloatingPointIeee754<double>
{
    public static double Lerp(double value1, double value2, double amount)
    {
        return value1 * (One - amount) + value2 * amount;
    }
}
```

```csharp
namespace System.Runtime.InteropServices;

public readonly struct NFloat : IFloatingPointIeee754<NFloat>
{
    public static NFloat Lerp(NFloat value1, NFloat value2, NFloat amount)
    {
        return value1 * (One - amount) + value2 * amount;
    }
}
```

### API Usage

```csharp
float value1 = 3f;
float value2 = 12f;
float amount = 0.5f;
Console.WriteLine(float.Lerp(value1, value2, amount));
Console.WriteLine(double.Lerp(value1, value2, amount));
Console.WriteLine(Half.Lerp((Half)value1, (Half)value2, (Half)amount));
Console.WriteLine(NFloat.Lerp(value1, value2, amount));
```

**Comment by svick** [comment] 2022-12-29 16:59
> `MathF.Clamp`

This already exists, as [`float.Clamp`](https://learn.microsoft.com/en-us/dotnet/api/system.single.clamp?view=net-7.0).

In general, you can expect new APIs directly on the numeric types themselves, instead of on `Math`/`MathF`. This approach is in line with generic math and is more consistent and has fewer overload resolution headaches.

> `Math.Mod` and `MathF.Mod`

This part is a duplicate of https://github.com/dotnet/runtime/issues/65408.

**Comment by tannergooding** [comment] 2023-01-03 18:36
@PavielKraskouski, as mentioned above we're not really adding APIs to Math/MathF anymore. Instead, new APIs are being exposed directly on the primitive types.

`Lerp` is a common enough (and optimizable enough) operation that it is likely worth exposing.

If you could update the proposal to cover adding it to `IFloatingPointIeee754<T>` and the corresponding types (`Half`, `Single`, `Double`, and `NFloat`), then we can move forward with the proposal.

**Comment by PavielKraskouski** [comment] 2023-01-05 00:32
@tannergooding Updated. Should I remove the `Math` and `MathF` suggestions?

**Comment by tannergooding** [comment] 2023-01-05 00:36
Yes please. I'd also recommend breaking `Mod` out into its own proposal (with it likewise being on `INumber<T>` and the corresponding primitives).

`Mod` is going to be more controversial, for many reasons, and so splitting Lerp/Mod into separate proposals will help with getting them reviewed and in.

**Comment by PavielKraskouski** [comment] 2023-01-05 17:31
@tannergooding Done.

**Comment by tannergooding** [comment] 2023-01-05 17:34
Thanks! I've marked ready-for-review and made a slight tweak to the proposal so that the `IFloatingPoint<T>` method is `static virtual` and has a `default implementation` (which is needed for back-compat).

**Comment by PavielKraskouski** [comment] 2023-01-08 20:48
@tannergooding What are your thoughts on adding more interpolation methods such as [`Bilerp`](https://en.wikipedia.org/wiki/Bilinear_interpolation) and [`Trilerp`](https://en.wikipedia.org/wiki/Trilinear_interpolation) based on `Lerp`?

**Comment by tannergooding** [comment] 2023-01-08 21:23
Those one's are much less common. I could see `slerp`, but for bi and trilinear, even libraries like DirectX Math and GLM don't provide them "out of the box".

I'd say it really comes down to them being more "complex" functions and not a "primitive" function like `lerp` is.

**Comment by bartonjs** [comment] 2023-01-17 20:06
Looks good as proposed

* Our existing Lerp implementations seem to use value1/value2 everywhere, and there's not an industry standard naming pair.
* This will be our first time ever that we've modified a shipped interface with a DIM.
  * Time to learn!

```C#
namespace System.Numerics
{
    public interface IFloatingPointIeee754<T> where T : IFloatingPointIeee754<T>?
    {
        static virtual T Lerp(T value1, T value2, T amount) => (value1 * (T.One - amount)) + (value2 * amount);
    }
}

namespace System
{
    public readonly struct Half : IFloatingPointIeee754<Half>
    {
        public static Half Lerp(Half value1, Half value2, Half amount)
        {
            return value1 * (One - amount) + value2 * amount;
        }
    }

    public readonly struct Single : IFloatingPointIeee754<float>
    {
        public static float Lerp(float value1, float value2, float amount)
        {
            return value1 * (One - amount) + value2 * amount;
        }
    }

    public readonly struct Double : IFloatingPointIeee754<double>
    {
        public static double Lerp(double value1, double value2, double amount)
        {
            return value1 * (One - amount) + value2 * amount;
        }
    }
}

namespace System.Runtime.InteropServices
{
    public readonly struct NFloat : IFloatingPointIeee754<NFloat>
    {
        public static NFloat Lerp(NFloat value1, NFloat value2, NFloat amount)
        {
            return value1 * (One - amount) + value2 * amount;
        }
    }
}
```

**Closed** 2023-01-26 10:17 UTC
Labels: api-approved, area-System.Numerics, in-pr
