### ISSUE TITLE
TypeLoadException on struct with generic

### ISSUE THREAD

**Issue by AxelHu** [dotnet/runtime#46188] opened 2020-12-17 08:56 UTC
I'm using net5.0 and vs community 2019 16.8.3. I found this issue in a part-time project.

Run the following code in a new project and a TypeLoadException will be thrown.
``` C#
using System;

var a = new T1();

public struct T1
{
    public T2<T1> a;
}

public struct T2<T>
{
}
```

Here is the exception message
```
System.TypeLoadException:“Could not load type 'T1' from assembly 'Main, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.”
```

It's not the top-level statements that lead to exception, the original code in my own project is well organized.

Is it a bug or something I shouldn't do in C#? I have no idea since the compiler does not stop me from doing so.

**Comment by Joe4evr** [comment] 2020-12-17 10:29
Duplicate of #6924.

**Closed** 2020-12-17 14:03 UTC
Labels: area-TypeSystem-coreclr, untriaged
