### ISSUE TITLE
Possible DictionaryKeyPolicy bug when serializing Dictionary<string, object>

### ISSUE THREAD

**Issue by hairlesshobo** [dotnet/runtime#43143] opened 2020-10-07 17:15 UTC
### Description

I have noticed a difference in how Dictionaries are serialized, depending on the value type of the dictionary. The behavior is inconsistent with what I would have expected to happen. In short, if you are serializing a `Dictionary<string, string>`, then all keys, even those who's value is `null`, is passed through the `DictionaryKeyPolicy` (either the built in `CamelCase` policy or a custom naming policy). When you serialize a `Dictionary<string, object>`, however, only non-null entries are passed to the naming policy. The others are skipped for some reason. Example code...

```csharp
using System;
using System.Collections.Generic;
using System.Text.Json;

namespace Test
{
    class Program
    {
        static void Main()
        {
            JsonSerializerOptions options = new JsonSerializerOptions()
            {
                DictionaryKeyPolicy = JsonNamingPolicy.CamelCase,
                PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
                IgnoreNullValues = true,
                WriteIndented = true
            };

            TestClass tc = new TestClass()
            {
                FirstName = "Stephen",
                ResidentCountry = "USA",
                NicknamesObj = new Dictionary<string, object>()
                {
                    { "MySpouse", "Steven" },
                    { "MyFriends", "Steve" },
                    { "TheInternet", "hairlesshobo" },
                    { "EveryoneElse", null }
                },
                NicknamesStr = new Dictionary<string, string>()
                {
                    { "MySpouse", "Steven" },
                    { "MyFriends", "Steve" },
                    { "TheInternet", "hairlesshobo" },
                    { "EveryoneElse", null }
                }
            };

            Console.WriteLine(JsonSerializer.Serialize(tc, options));
        }
    }

    public class TestClass
    {
        public string FirstName { get; set; }
        public string ResidentCountry { get; set; }
        public Dictionary<string, object> NicknamesObj { get; set; }
        public Dictionary<string, string> NicknamesStr { get; set; }
    }

}
```

Now, I would have expected that the output would use camelCase for all properties and Dictionary keys, but in the case of the `NicknamesObj` property, that is not the case. See below for output:

```json
{
  "firstName": "Stephen",
  "residentCountry": "USA",
  "nicknamesObj": {
    "mySpouse": "Steven",
    "myFriends": "Steve",
    "theInternet": "hairlesshobo",
    "EveryoneElse": null
  },
  "nicknamesStr": {
    "mySpouse": "Steven",
    "myFriends": "Steve",
    "theInternet": "hairlesshobo",
    "everyoneElse": null
  }
}
```

Notice how `everyoneElse` in `nicknamesStr` was passed through the naming policy, but `EveryoneElse` in `nicknamesObj` was not passed through. Since both dictionaries have a key of type `string`, I can't imagine why the behavior would be different in one case vs the other. Additionally, I have found that it doesn't make a difference whether you use the built in camelCase naming policy or if you create a custom one and use it. Either way, the key name is never passed through the naming policy class for dictionaries with value type of `object`. If this is the expected behavior, perhaps someone could explain why this is the case?

### Configuration

This is with version 4.7.2 of System.Text.Json on .NET Core 3.1.6.  See below for output of `dotnet --info`:

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.302     
 Commit:    41faccf259  

Runtime Environment:    
 OS Name:     Windows   
 OS Version:  10.0.18363
 OS Platform: Windows   
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.302\

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

.NET Core SDKs installed:
  2.1.809 [C:\Program Files\dotnet\sdk]
  3.1.103 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]
  3.1.302 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Please let me know if you need any additional details regarding how to reproduce this issue.

**Comment by Jozkee** [comment] 2020-10-09 03:22
Duplicate of https://github.com/dotnet/runtime/issues/33508 and https://github.com/dotnet/runtime/issues/30889.

**Closed by Jozkee** 2020-10-09 03:22 UTC
Labels: area-System.Text.Json, untriaged

**Comment by hairlesshobo** [comment] 2020-10-09 11:05
I spent a while searching for a duplicate and couldn't find one. Sorry about that! Thanks for the info.
