### ISSUE TITLE
Extra ILC warnings when PublishAOT=true on method already marked RequiresUnreferencedCode

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#75898] opened 2022-09-20 15:04 UTC
### Description

When Publishing AOT, I'm seeing extra warnings being emitted that clutter the warnings and confuse developers.

From what I can tell, the warnings are coming from:

https://github.com/dotnet/runtime/blob/2f3fcca06499725469b6ae021be960e08d808c75/src/libraries/Microsoft.Extensions.Logging.Configuration/src/LoggerProviderConfigurationExtensions.cs#L25-L29

ServiceDescriptor.Singleton has a [DAM] attribute for the constructor of the 2nd generic arg:

https://github.com/dotnet/runtime/blob/2f3fcca06499725469b6ae021be960e08d808c75/src/libraries/Microsoft.Extensions.DependencyInjection.Abstractions/src/ServiceDescriptor.cs#L302

and LoggerProviderConfigureOptions has RDC and RUC on its ctor:

https://github.com/dotnet/runtime/blob/2f3fcca06499725469b6ae021be960e08d808c75/src/libraries/Microsoft.Extensions.Logging.Configuration/src/LoggerProviderConfigureOptions.cs#L14-L16

However, these warnings shouldn't be emitted because `RegisterProviderOptions` has RDC and RUC attributes. So I should only be getting the warnings from my call to `RegisterProviderOptions`.

cc @MichalStrehovsky @vitek-karas 

### Reproduction Steps

Using 7.0-rc1, `dotnet publish -c Release -r win-x64` the following app:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishAOT>true</PublishAOT>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="7.0.0-rc.1.22426.10" />
  </ItemGroup>
</Project>
```

```C#
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging.Configuration;
using Microsoft.Extensions.Logging.Console;

LoggerProviderOptions.RegisterProviderOptions<ConsoleLoggerOptions, ConsoleLoggerProvider>(new ServiceCollection());
```

### Expected behavior

I should only get warnings for my program's call to `RegisterProviderOptions`.

### Actual behavior

Along with the expected warnings from my code, I'm getting these extra warnings in the publish output:

```
ILC : Trim analysis warning IL2026: Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Singleton<IConfigureOptions`1<ConsoleLoggerOptions>,LoggerProviderConfigureOptions`2<ConsoleLoggerOptions,ConsoleLoggerProvider>>(): Using member 'Microsoft.Extensions.Logging.Configuration.LoggerProviderConfigureOptions`2<ConsoleLoggerOptions,ConsoleLoggerProvider>.LoggerProviderConfigureOptions`2<ConsoleLoggerOptions,ConsoleLoggerProvider>(ILoggerProviderConfiguration`1<ConsoleLoggerProvider>)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. TOptions's dependent types may have their members trimmed. Ensure all required members are preserved. [C:\Users\eerhardt\source\repos\WorkerService12\WorkerService12\WorkerService12.csproj]
ILC : Trim analysis warning IL2026: Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Describe<IConfigureOptions`1<ConsoleLoggerOptions>,LoggerProviderConfigureOptions`2<ConsoleLoggerOptions,ConsoleLoggerProvider>>(ServiceLifetime): Using member 'Microsoft.Extensions.Logging.Configuration.LoggerProviderConfigureOptions`2<ConsoleLoggerOptions,ConsoleLoggerProvider>.LoggerProviderConfigureOptions`2<ConsoleLoggerOptions,ConsoleLoggerProvider>(ILoggerProviderConfiguration`1<ConsoleLoggerProvider>)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. TOptions's dependent types may have their members trimmed. Ensure all required members are preserved. [C:\Users\eerhardt\source\repos\WorkerService12\WorkerService12\WorkerService12.csproj]
```

### Regression?

I'm not sure. Probably not.

**Comment by agocke** [comment] 2022-11-17 22:50
@tlakollo Let's work on this as soon as packaging is done and ready for linker in runtime.

**Comment by eerhardt** [comment] 2023-01-10 00:51
@tlakollo - any update on this? We'd like to get to 0 warnings in a very basic ASP.NET app soon.

**Comment by vitek-karas** [comment] 2023-01-10 08:51
I'll look into this.

**Comment by vitek-karas** [comment] 2023-01-10 12:22
This is a known problem (don't think we have an issue yet) which we've been discussing for a while. In general the NativeAOT compiler's handling of warnings from DAM annotation of generic arguments is problematic. It performs the DAM validation in places where it should not (which is most likely the reason for the extra warnings you see here) and it also reports these warnings as originating from wrong places (doesn't seem to be hit by this code).

I've discussed this with @MichalStrehovsky and we need to modify how the compiler handles DAM on generics. The broad idea is:
* Avoid analyzing generic instantiations which are caused by instantiating method bodies or types - basically if the original IL is something like `MyGeneric<!0>` then we should only analyzer that, and not any specific `MyGeneric<Foo>` which is produced by the compiler during instantiation of generics.
* Instead of relying on dependency nodes, try to analyze generic instantiations from data flow as much as possible (since there we can provide the correct message origin)

Unfortunately what this means is that it's not a simple fix and thus will take some time. I guess we (read @vitek-karas :wink:) need to prioritize this work.

**Comment by DamianEdwards** [comment] 2023-01-10 17:51
I'm hitting this warning now with the code produced by the new project template so it seems this is going to be on the critical path to getting past our stage 1 goals (create a new project from this template with native AOT enabled and get now warnings).

**Comment by eerhardt** [comment] 2023-01-12 15:46
> and thus will take some time

Any idea how long? Is it something that could make it into 8.0-preview2? That's when we are targeting getting a basic ASP.NET app published for AOT without any warnings.

**Comment by vitek-karas** [comment] 2023-01-12 18:55
I'm hoping to have it done it about a week. I'll know better couple of days in (still lot to learn in the compiler to do this right).

**Comment by MichalStrehovsky** [comment] 2023-01-13 03:13
> (still lot to learn in the compiler to do this right)

Just a note that we don't have to fix all of the generic issues in one go. We have known holes around generics (e.g. #80037), so "just" replacing the existing scheme with one that generates warnings from dataflow (that are suppressible) would be a good first step.

**Comment by vitek-karas** [comment] 2023-01-30 14:41
The fix has been reverted due to https://github.com/dotnet/runtime/issues/81358.

**Comment by eerhardt** [comment] 2023-02-08 16:25
Reopening as this fix had to be reverted. See https://github.com/dotnet/runtime/pull/81783

**Closed** 2023-02-21 10:04 UTC
Labels: in-pr, area-NativeAOT-coreclr
