### ISSUE TITLE
System.Text.Json lost the property of derived class after serialize.

### ISSUE THREAD

**Issue by Mutuduxf** [dotnet/runtime#51906] opened 2021-04-27 00:56 UTC
Target framework 5.0,here is the demo.

```csharp
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text.Json;

namespace SystemTextJsonTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var apple = new Apple
            {
                Id = Guid.NewGuid(),
                Bananas = new List<Banana>
                {
                    new Banana0{Id = Guid.NewGuid(),Value = 1},
                    new Banana1{Id = Guid.NewGuid(),Value = DateTime.UtcNow.ToString(CultureInfo.InvariantCulture)}
                }
            };
            //The property "Value" of the derived class is lost
            //{"Id":"fead1a5a-87a2-41c2-a1ba-c48fda1da67a","Bananas":[{"Id":"8fe8ff02-4bc8-42db-8c44-e014ae522d00"},{"Id":"236edd74-8cdd-40f9-87e0-70fe0a2adba4"}]}
            var json = JsonSerializer.Serialize(apple);
            Console.WriteLine(json);
            Console.ReadLine();
        }
    }

    public class Apple
    {
        public Guid Id { get; set; }
        public List<Banana> Bananas { get; set; }
    }

    public class Banana
    {
        public Guid Id { get; set; }
    }

    public class Banana0 : Banana
    {
        public int Value { get; set; }
    }

    public class Banana1 : Banana
    {
        public string Value { get; set; }
    }
}
```

**Comment by huoyaoyuan** [comment] 2021-04-27 02:48
This is the expected behaviour. Unless the variable type is `object`, the json serializer will use variable type, not object type for serialization.

**Comment by eiriktsarpalis** [comment] 2021-04-27 12:39
As @huoyaoyuan mentioned, this behaviour is by design. We are working on adding opt-in behaviour that should permit polymorphic serialization in future releases.

Duplicate of #45189.

**Closed by eiriktsarpalis** 2021-04-27 12:39 UTC
Labels: area-System.Text.Json, untriaged
