### ISSUE TITLE
Utf8JsonReader.TryGetGuid() only parses Guids of format 'D' (nnnnnnnn-nnnn-nnnn-nnnn-nnnnnnnnnnnn)

### ISSUE THREAD

**Issue by stylesm** [dotnet/runtime#767] opened 2019-12-11 14:22 UTC
`System.Text.Reader.Utf8JsonReader.TryGetGuid(out Guid value)` 

calls 

`System.Buffers.Text.Utf8Parser.TryParse(ReadOnlySpan<byte> source, out Guid value, out int bytesConsumed, char standardFormat = default)`

However, when it does, it passes 'D' in as the `standardFormat` parameter, meaning only Guids in the format `nnnnnnnn-nnnn-nnnn-nnnn-nnnnnnnnnnnn` are parsed successfully.

There are 4 Guid formats supported by Utf8Parser:
```        
        ///     D (default)     nnnnnnnn-nnnn-nnnn-nnnn-nnnnnnnnnnnn
        ///     B               {nnnnnnnn-nnnn-nnnn-nnnn-nnnnnnnnnnnn}
        ///     P               (nnnnnnnn-nnnn-nnnn-nnnn-nnnnnnnnnnnn)
        ///     N               nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn
```

It would be great if `Utf8JsonReader.TryGetGuid(out Guid value)` supported the other three formats, defaulting to 'D' for backwards compatibility.

This bubbles up into other APIs, e,g, `System.Text.Json`

Am happy to take on dev work if this is agreed.

Am in a rush and haven't checked contrib guidelines so likely update this later.

**Comment by layomia** [comment] 2019-12-12 00:21
Duplicate of https://github.com/dotnet/corefx/issues/40609.

**Closed by layomia** 2019-12-12 00:21 UTC
Labels: area-System.Text.Json
