### ISSUE TITLE
NetworkInterfaceType for System.Net.NetworkInformation.NetworkInterface is always 0 on Android 11

### ISSUE THREAD

**Issue by quenkk** [dotnet/runtime#51984] opened 2021-04-28 12:40 UTC
When I get all interfaces with `NetworkInterface.GetAllNetworkInterfaces()` and then I want to check if they are Wifi or Ethernet I use this kind of code:
```c#
foreach (var networkInterface in NetworkInterface.GetAllNetworkInterfaces())
{
    if (networkInterface.NetworkInterfaceType != NetworkInterfaceType.Wireless80211 &&
         networkInterface.NetworkInterfaceType != NetworkInterfaceType.Ethernet)
         continue;

    //Getting Ip address here
}
```

On the Android 11 the NetworkInterfaceType always returns 0, so whole loop never goes into getting Ip address. For Android 10 and lower it works fine.

If I lower Target Android Version to Android 10.0 (API level 29) then it work on Android 11, but starting August 2021 it would be required to target API 30 in order to publish new or updated version of app to Google Play.

**Comment by dustinkerstein** [comment] 2021-10-06 13:14
@quenkk, were you able to find a workaround for this? Maybe something with the requested permissions in the manifest? Thanks!

**Comment by quenkk** [comment] 2021-10-13 08:03
@dustinkerstein For now I used hacky workaround for it:

`foreach (var networkInterface in NetworkInterface.GetAllNetworkInterfaces())
{
    if (netInterface.NetworkInterfaceType == NetworkInterfaceType.Wireless80211 ||
         netInterface.NetworkInterfaceType == NetworkInterfaceType.Ethernet ||
         netInterface.Name.StartsWith("wlan") ||
         netInterface.Name.StartsWith("eth"))
    {
        //Getting Ip address here
    }
}`

**Comment by steveisok** [comment] 2021-12-14 02:36
Closing as this is a duplicate of https://github.com/dotnet/runtime/issues/51303.

**Closed by steveisok** 2021-12-14 02:36 UTC
Labels: area-System.Net, os-android
