### ISSUE TITLE
Socket.BeginConnect in .NET 6 throws an unobserved SocketException

### ISSUE THREAD

**Issue by xPaw** [dotnet/runtime#61411] opened 2021-11-10 11:28 UTC
### Description

After updating to .NET 6 we started seeing (separate users and software) unobserved `SocketException`.

After analyzing the logs, I believe it is being triggered here:

https://github.com/SteamRE/SteamKit/blob/2.4.0-Alpha.3/SteamKit2/SteamKit2/Networking/Steam3/TcpConnection.cs#L158

However it is hard to tell because the stacktrace doesn't really have useful information which could pin point the exact code.

The code that uses AwaitableSocketAsyncEventArgs is in `Socket.ConnectAsync`

@yaakov-h pointed out this:
> ValueTask<TResult>.AsTask is the only code path to there, and I don’t think SK2 knows about ValueTask, so that’s gotta be a runtime bug.

https://source.dot.net/#System.Private.CoreLib/ValueTask.cs,638

### Reproduction Steps

-

### Expected behavior

Exception should be catchable, or not happen in this manner?

### Actual behavior

```
Unhandled exception. System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Operation canceled) (Operation canceled)
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
   --- End of inner exception stack trace ---
   at System.AggregateException.Handle(Func`2 predicate)
   at SteamDatabaseBackend.Bootstrapper.OnUnobservedTaskException(Object sender, UnobservedTaskExceptionEventArgs args) in /home/steamdb/deploy/Bootstrapper.cs:line 149
   at System.Threading.Tasks.TaskScheduler.PublishUnobservedTaskException(Object sender, UnobservedTaskExceptionEventArgs ueea)
   at System.Threading.Tasks.TaskExceptionHolder.Finalize()
```

### Regression?

I did not get this on .NET 5.

### Configuration

Debian 11 x64.

**Comment by JustArchi** [comment] 2021-11-10 11:32
I've observed similar error in entirely different library, `Discord.Net`, that also didn't happen in .NET 5.0.

However, I don't have much besides the stacktrace:

```
ArchiBot|OnUnobservedTaskException() System.Net.Sockets.SocketException (125): Operation canceled
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
```

Could be a coincidence, but I very much doubt that the first day after updating to .NET 6.0 I got networking issues that triggered a bug that I didn't see for the last year if not more, especially considering other people stumble upon the same. Some regression probably happened.

**Comment by JustArchi** [comment] 2021-11-10 11:56
Just for the sake of completeness, I have this (another) unobserved task exception logged next to the bunch of operation canceled errors above:

```
ArchiBot|OnUnobservedTaskException() System.Net.Http.HttpRequestException: Resource temporarily unavailable (discord.com:443)
---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
at Discord.Net.Rest.DefaultRestClient.SendInternalAsync(HttpRequestMessage request, CancellationToken cancelToken, Boolean headerOnly)
at Discord.Net.Rest.DefaultRestClient.SendAsync(String method, String endpoint, CancellationToken cancelToken, Boolean headerOnly, String reason)
at Discord.Net.Queue.RestRequest.SendAsync()
at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
at Discord.API.DiscordRestApiClient.SendAsync[TResponse](String method, String endpoint, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
at Discord.API.DiscordRestApiClient.GetBotGatewayAsync(RequestOptions options)
at Discord.Rest.ClientHelper.GetBotGatewayAsync(BaseDiscordClient client, RequestOptions options)
at Discord.WebSocket.DiscordShardedClient.OnLoginAsync(TokenType tokenType, String token)
at Discord.Rest.BaseDiscordClient.LoginInternalAsync(TokenType tokenType, String token, Boolean validateToken)
at Discord.Rest.BaseDiscordClient.LoginInternalAsync(TokenType tokenType, String token, Boolean validateToken)
at Discord.Rest.BaseDiscordClient.LoginAsync(TokenType tokenType, String token, Boolean validateToken)
at ArchiBot.Platform.Discord.DiscordBot.Start(String token)
```

However, it might or might not be related to the above, so it shouldn't be blindly assumed that this is the culprit. It could help pinpoint the real culprit perhaps, and that's why I'm attaching it, maybe it gives a clue where the error is coming from.

**Comment by stephentoub** [comment] 2021-11-10 14:31
By "unobserved SocketException" you mean the UnobservedTaskException event is being raised?

That would make sense and be legit based on the code you shared.  The code you linked to is ignoring the returned IAsyncResult in the case of a timeout,  so if the operation times out, it's just dropping that IAsymcResult on the floor without ever joining with it and seeing whatever exception it might contain. In .NET 6, BeginConnect is just a thin wrapper for ConnectAsync, so by not joining with it,  you're allowing potentially faulted task to go unobserved.  So the event is raised.

**Comment by xPaw** [comment] 2021-11-10 14:57
Why is the stacktrace so unhelpful, shouldn't it point to the code where BeginConnect was called?

Documentation was updated to say that `SocketException` won't be thrown on NET 6, how come?
> SocketException
.NET Framework and .NET 5 and earlier only: An error occurred when attempting to access the socket.

https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.beginconnect?view=net-5.0

**Comment by antonfirsov** [comment] 2021-11-10 15:02
> Documentation was updated to say that `SocketException` won't be thrown on NET 6, how come?

@xPaw it means that the exceptions we used to throw synchronously on `Begin***` methods will be thrown asynchronously, thus only observed on `EndConnect`.

**Comment by xPaw** [comment] 2021-11-10 15:22
> thus only observed on EndConnect, I believe you are facing this change now.

In the code I linked EndConnect is wrapped in a try/catch.

What is the correct fix for this then? I wrapped the BeginConnect in a try/catch (to catch the the other exceptions), but I'm not sure that will help with this particular issue.

> There are potential things that can be done to improve the exception stack to include the stack of BeginConnect

As it stands, I just have to guess where the exception came from.

**Comment by stephentoub** [comment] 2021-11-10 15:24
> In the code I linked EndConnect is wrapped in a try/catch.

The problem is that you're not always calling EndConnect.  The code shared is:
```C#
            var asyncResult = socket!.BeginConnect(CurrentEndPoint, null, null );
            if ( WaitHandle.WaitAny( new WaitHandle[] { asyncResult.AsyncWaitHandle, cancellationToken.Token.WaitHandle }, timeout ) == 0 )
            {
                try
                {
                    socket.EndConnect( asyncResult );
                    ConnectCompleted( true );
                }
                catch ( Exception ex )
                {
                    log.LogDebug( "TcpConnection", "Socket exception while completing connection request to {0}: {1}", CurrentEndPoint, ex );
                    ConnectCompleted( false );
                }
            }
            else
            {
                ConnectCompleted( false );
            }
```
If that else block is taken, the asyncResult and thus any exceptions it might eventually fault with are ignored.  This problem was always there, the code was always ignoring the exception in that case, it's just that now the UnobservedTaskException event is being raised to tell you about it.

**Comment by xPaw** [comment] 2021-11-10 15:27
Right, that's a good catch (I didn't write this code).

So is this not a regression then? My problem with this is how unhelpful the exception is.

**Comment by willdean** [comment] 2021-11-10 21:05
>My problem with this is how unhelpful the exception is.

+100 from me here on this.  We're going through exactly the same misery trying to track this down here in an app which we've just moved from 5-6.

I'm delighted if something new has drawn attention to a lurking latent defect.  But highly undelighted that there is no connection, either temporal or "geographical" between the error message and the problem.

**Comment by yaakov-h** [comment] 2021-11-11 05:29
Same. I'm quite surprised that the stack trace of the unobserved exception ends at the implementation of `ValueTask.ToTask()`, missing the lower frames of `BeginConnect()`, the user code that called into the sockets stack, _and even the program entry point or `ThreadStart` method._

I'm not sure I've ever seen that before from an exception that has been thrown.

**Comment by stephentoub** [comment] 2021-11-11 14:12
The exception here is going unhandled on stacks completely separate from the code that called BeginConnect.  The exception isn't propagating out through code that would update its stack, as would happen if you were using await.  Rather, the exception is being triggered in a callback, ignored, and then the UnobservedTaskException event is being raised.

**Comment by zpqrtbnk** [comment] 2021-11-13 15:29
Been bitten by the same issue. In one case, we had an issue similar to the one above (ignoring the `IAsyncResult` in some cases). Fixed, works. However... the following code fails and I cannot manage to understand why. If we remove the `Repeat` attribute and run it *once*, it works, but as soon as it runs more than once, we get an unobserved exception, on the second run.

```
[Test]
[Repeat(2)]
public async Task Net6Repro()
{
    var endpoint = new IPEndPoint(IPAddress.Parse("127.0.0.1"), 11000);
    var socket = new Socket(endpoint.Address.AddressFamily, SocketType.Stream, System.Net.Sockets.ProtocolType.Tcp);
    socket.Bind(endpoint);
    socket.Listen(10);
    socket.BeginAccept(asyncResult =>
    {
        try
        {
            var accepted = socket.EndAccept(asyncResult);
        }
        catch (Exception e)
        {
            Console.WriteLine("caught " + e);
        }
    }, socket);
    await Task.Delay(1000);
    socket.Close();
    socket.Dispose();
}
```

Nothing connects to the socket -- this is the whole test.

**Comment by zpqrtbnk** [comment] 2021-11-13 15:50
OK. In the example above, `socket.Close()` and `socket.Dispose()` are redundant because `Close` invokes `Dispose`. We cannot `Shutdown` the socket since it is not connected. I am not aware of any other way to "stop accepting"... so I end up disposing. The callback is invoked, but `socket.EndAccept(asyncResult)` throws because `socket` is disposed, and so it does not really run. And the async result is left with an unobserved exception.

The thing about repeating the test once or twice isn't important - probably a glitch of our tests.

If I grab the `_task` property of the async result via reflection, and observe the result of that task, then all is fine. So, the question is: how can I observe that task? Is there a way to terminate the "accept" without disposing the socket, that I am not aware of?

**Comment by antonfirsov** [comment] 2021-11-13 17:41
@stephentoub I wonder if we should alter the Task's exception observed status in `End*` calls in case the socket is disposed:

https://github.com/dotnet/runtime/blob/0818df12f8c6ffd19f38b10ee5ab43ccd486e537/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L2535-L2539

**Comment by stephentoub** [comment] 2021-11-13 20:15
> I wonder if we should alter the Task's exception observed status in End* calls in case the socket is disposed:

I'd actually be more inclined to remove that ThrowIfDisposed call.

**Comment by zpqrtbnk** [comment] 2021-11-15 06:46
Have tried to simplify to come to a bare minimum repro. Code below works fine up to .NET 5 but leaves an unobserved exception with .NET 6  for reasons discussed above: cannot `EndAccept` the `asyncResult` because the `listenSocket` has been disposed already, so cannot observe the exception its task contains. Simply closing the socket instead of disposing does not help as `Close` invokes `Dispose`.
```
using var listenSocket = new Socket(SocketType.Stream, ProtocolType.Tcp);
listenSocket.Bind(new IPEndPoint(IPAddress.Loopback, 8080));
listenSocket.Listen();
listenSocket.BeginAccept(asyncResult =>
{
    try
    {
        var socket = listenSocket.EndAccept(asyncResult);
    }
    catch {  }
});
Thread.Sleep(100);
listenSocket.Dispose();
```

**Comment by antonfirsov** [comment] 2021-11-15 15:06
> I'd actually be more inclined to remove that ThrowIfDisposed call.

The code in https://github.com/dotnet/runtime/issues/61411#issuecomment-968585218 throws `ObjectDisposedException` in previous versions. Breaking exception compatibility may lead to user complaints similar to #41585. Unless it causes us too much pain, I would attempt to remove unobserved exceptions being propagated in cases when user code is correct. Not anything high priority though.

**Comment by stephentoub** [comment] 2021-11-15 15:16
>> I'd actually be more inclined to remove that ThrowIfDisposed call.

> The code in #61411 (comment) throws ObjectDisposedException in previous versions.

Understood. But there are plenty of differences that come from switching to use Tasks under the covers instead of the legacy APM implementation, including but not limited to exceptions that emerged from the Begin call now coming from the End call, unobserved exceptions now triggering UnobservedTaskException, how frequently the callback is invoked synchronously vs asynchronously, etc.  Calling ThrowIfDisposed prior to EndXx breaks the model that EndXx is used to join with outstanding operation, which means the use of ThrowIfDisposed can result in not-yet-completed async operations continuing to run even after EndXx is called; to me, that takes priority.

My $.02.  Up to you and @geoffkizer what you'd like to do here.

**Comment by antonfirsov** [comment] 2021-11-15 15:55
Can't we do something like this?

```C#
public Socket EndAccept(IAsyncResult asyncResult) {
	try { return TaskToApm.End<Socket>(asyncResult); }
	catch {
		if (IsDisposed) throw new ObjectDisposedException();
		throw;
	}
} 
```

**Comment by stephentoub** [comment] 2021-11-15 15:59
> Can't we do something like this?

Why is the ObjectDisposedException there better than the actual exception the operation failed with?

**Comment by antonfirsov** [comment] 2021-11-15 16:51
> It could have failed long before the Socket was disposed.

Even if that's the case, we still used to check the disposed state and throw ODE at the very beginning. My code is not compatible with old logic though if called with a successful operation on a disposed socket, so I see that this can be more complicated than I thought.

> the use of ThrowIfDisposed can result in not-yet-completed async operations continuing to run even after EndXx is called

Wasn't this the same before the async refactor?

https://github.com/dotnet/runtime/blob/release/5.0/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L3599-L3606

I'm fine prioritizing simplicity and correctness over compatibility, but in that case I'd prefer to see us explicitly documenting a breaking change and rejecting asks like #41585.

**Comment by geoffkizer** [comment] 2021-11-15 20:08
It seems like the old EndAccept code had a race that could lead to a leak of a Socket object (which would get finalized eventually, but that's not ideal). If a socket was successfully accepted and then the listen socket was disposed before EndAccept was called, then we'd leak the accepted socket.

In general, checking if the Socket itself is disposed in the End* method seems questionable to me. If the operation completed successfully, the End* call should succeed regardless of whether the socket has been disposed in the meantime (and thus, not leak the accepted socket etc). If it failed before the socket was disposed, the End call should fail with an exception indicating the failure, not ODE.

The tricky case is when the operation failed *because* the socket was disposed. Arguably, we should throw ODE in this case. But we explicitly don't throw ODE for Task and SAEA operations -- in fact there's code deep in the SAEA implementation to convert ODE into OperationAborted in certain circumstances.

So I think we should:
(1) Remove the blanket ThrowIfDisposed call from various End methods
(2) Wrap a try/catch around the calls to TaskToApm.End that checks specifically for OperationAborted and converts it to ObjectDisposedException

This seems like the best mix of correctness and compatibility here. That said, if we don't care about maintaining the ODE in this case, we could simply not do (2) and allow the OperationAborted SocketException to propagate.

> I'm fine prioritizing simplicity and correctness over compatibility, but in that case I'd prefer to see us explicitly documenting a breaking change and rejecting asks like #41585.

I think that if we were looking at it now, we would certainly consider rejecting #41585. At the time we thought it was a simple fix, so we did it. In retrospect, I don't think we fully understood the implications.

**Comment by zpqrtbnk** [comment] 2021-11-16 05:28
Probably ignoring lots of details and constraints here but is this not what we are trying to achieve? Still throws the (correct and expected) `ObjectDisposedException`, just makes sure that in *every cases* the `IAsyncResult` is taken care of?

```
public void EndSomething(IAsyncResult asyncResult)
{
    try
    {
        ThrowIfDisposed();
    }
    finally
    {
        TaskToApm.End(asyncResult);
    }
}
```

**Comment by karelz** [comment] 2021-12-09 16:57
Triage:
- We should not throw ObjectDisposedException in End operations.
- If user does not call End operation, that is user error and it is fine for the exceptions to go unobserved.

**Comment by xPaw** [comment] 2021-12-10 10:42
Worth mentioning that it is common to do a connect timeout, which would involve _not_ calling EndConnect, like this: https://stackoverflow.com/a/4708790

**Comment by antonfirsov** [comment] 2021-12-10 11:22
In case we remove the disposed check, it will be possible to can call `EndConnect` after `socket.Close()` to observe the exception. I understand this is not ideal, but the APM (Begin*/End*) methods are really legacy compatibility API-s today.

It's preferred to migrate to task-based overloads when going `async` is an option. When not, `SocketAsyncEventArgs` methods provide much better performance (especially when the `SocketAsyncEventArgs` is cached by the user) and no weird side effects. To handle timeouts, one can use `CancelConnectAsync` with them.

**Closed** 2022-08-05 16:33 UTC
Labels: enhancement, area-System.Net.Sockets, in-pr

**Comment by mikhail-barg** [comment] 2022-08-08 07:29
Great to see this is finally fixed! Could you please clarify which runtime version would get the fix? Will it be available in net6 considering it's LTS status?

**Comment by stianeklund** [comment] 2022-08-16 12:30
Any news as to when these changes will be available in net7? I don't see any new changes in `System.Net.Sockets`, might just be in daily builds (I haven't gone that far to test that yet). Also curious whether or not this will be back ported to net6?

**Comment by stephentoub** [comment] 2022-08-16 12:34
It's already in daily builds and will be in RC1 of .NET 7. There are no plans to backport it.
