### ISSUE TITLE
Incorrect matching with RegexOptions.IgnoreCase

### ISSUE THREAD

**Issue by cnblogs-dudu** [dotnet/runtime#78609] opened 2022-11-20 12:55 UTC
### Description

A regular expression with RegexOptions.IgnoreCase got incorrect matching after upgrading from .NET 6 to .NET 7.

### Reproduction Steps

```cs
var regex = new Regex(
    @"(?<url>https?://(?<host>[^./]+([.][^. /]+)*[.][a-zA-Z]{2,3})(:\d+)?/?[^\u0391-\uFFE5\s,]*)",
    RegexOptions.IgnoreCase | RegexOptions.Compiled);

var text = "https://www.nuget.org/packages/Cnblogs.IdentityServer4/";
var linkingText = regex.Replace(text, "<a href=\"${url}\">${host}</a>");

Console.WriteLine(linkingText);
// .NET 7 output: <a href="https://www.nuget.org/pac">www.nuget.org</a>kages/Cnblogs.IdentityServer4/
// .NET 6 output: <a href="https://www.nuget.org/packages/Cnblogs.IdentityServer4/">www.nuget.org</a>
```

### Expected behavior

Output: 
```text
<a href="https://www.nuget.org/packages/Cnblogs.IdentityServer4/">www.nuget.org</a>
```

### Actual behavior

Output: 
```text
<a href="https://www.nuget.org/pac">www.nuget.org</a>kages/Cnblogs.IdentityServer4/
```

### Known Workarounds

Remove `RegexOptions.IgnoreCase`

**Comment by svick** [comment] 2022-11-20 18:58
When I use `[GeneratedRegex]` for your regex (which uses a similar engine as `RegexOptions.Compiled` in .Net 7), the description generated for the last section of the regex is:

> Match a character in the set [^,Kk\u00C5\u00DF\u00E5\u023A\u023E-\u0240\u0250-\u0252\u025C\u0261\u0265\u0266\u026A-\u026C\u0271\u027D\u0282\u0287\u029D\u029E\u037B-\u037D\u037F\u0386\u0388-\u038A\u038C\u038E\u038F\u0391-\uFFE5\s] atomically any number of times.

Notice that it contains `k`, which is exactly where the matching stopped. Why? Because of U+212A Kelvin Sign. That character is part of your specified range, looks like the letter K and compares equal to the letter k if your ignore case (i.e. `string.Equals("k", "\u212A", StringComparison.CurrentCultureIgnoreCase)` returns `true` for me).

So it seems to me that the .Net 7 behavior is correct.

**Comment by danmoseley** [comment] 2022-11-20 20:32
I agree. How did you choose `\u0391-\uFFE5`? In general hand parsing URLs is probably difficult.

**Comment by stephentoub** [comment] 2022-11-20 22:33
> So it seems to me that the .Net 7 behavior is correct.

Yes, as outlined, this is by design. This was a long-standing bug we fixed in .NET 7, so prior to .NET 7 (both .NET Framework and .NET Core) you can witness the wrong behavior.  It's most easily visible with a repro like this, where ranges are obviously being handled inconsistently:
```C#
using System;
using System.Text.RegularExpressions;

class Program
{
    static void Main()
    {
        Console.WriteLine(Regex.IsMatch("k", @"[\u212A]", RegexOptions.IgnoreCase));
        Console.WriteLine(Regex.IsMatch("k", @"[\u212A\u212B]", RegexOptions.IgnoreCase));
        Console.WriteLine(Regex.IsMatch("k", @"[\u212A-\u212B]", RegexOptions.IgnoreCase));
    }
}
```
On .NET Framework and .NET 6, that'll erroneously output True, True, False, which makes no sense, since the 2nd and 3rd variations should be identical (the second has a set containing two characters and the third has a range of those same two characters).  On .NET 7, it'll correctly output True, True, True.  This had to do with how ranges were handled when IgnoreCase was specified, and we completely overhauled the implementation in .NET 7 to address many such issues; an example is https://github.com/dotnet/runtime/issues/36149.

**Comment by am11** [comment] 2022-11-20 23:44
Is it well-defined which homoglyphs are supported? e.g.

```c#
Console.WriteLine(Regex.IsMatch("a", @"[\u1D468]", RegexOptions.IgnoreCase));
```

[Mathematical Bold Italic Capital A - 𝑨](https://www.htmlsymbol.com/unicode-code/1d468.html) fails to compare with `a` (and some [other variations](https://github.com/codebox/homoglyph#background) as well)

**Comment by stephentoub** [comment] 2022-11-21 00:55
> [Mathematical Bold Italic Capital A - 𝑨](https://www.htmlsymbol.com/unicode-code/1d468.html)

A few things...

First, `@"[\u1D468]"` isn't what you intended it to be.  That's a set of two distinct characters: `'\u1D46'` (ᵆ) and `'8'`.  If you actually wanted "Mathematical Bold Italic Capital A", you'd write `"\uD835\uDC68"` or `"\U0001D468"`.

Second, "Mathematical Bold Italic Capital A" is actually two Chars, as it's a surrogate pair, which Regex doesn't support. Regex operates over individual System.Chars.

Third, for "Is it well-defined which homoglyphs are supported", it's based entirely on the Unicode data used by the runtime. The case equivalence rule currently used by Regex, in order to compute the folding table ahead of time and to be as compatible with previous releases as possible, is two chars c1 and c2 are considered equivalent under IgnoreCase if c1.ToLower() == c2 or if c1.ToLower() == c2.ToLower().

Fourth, this is veering a bit off topic for the actual question raised here.  While the repro involves the Kelvin sign lowercasing to 'k' (as defined in Unicode), the issue here was a bug in previous releases having to do with how character class ranges were processed when being parsed.  That bug was fixed in .NET 7.

**Comment by cnblogs-dudu** [comment] 2022-11-21 01:58
> I agree. How did you choose `\u0391-\uFFE5`? In general hand parsing URLs is probably difficult.

For the following case:
```cs
text = "https://www.nuget.org/packages/Cnblogs.IdentityServer4/发布了";
// output:  <a href="https://www.nuget.org/packages/Cnblogs.IdentityServer4/">www.nuget.org</a>发布了
```

**Comment by ericstj** [comment] 2023-05-23 20:29
We don't have a breaking change doc on this for 7.0.  Can we distill the behavior change that happened in .NET 7.0 and add that to the docs here: https://github.com/dotnet/docs/issues/new?assignees=gewarren&labels=breaking-change%2CPri1%2Cdoc-idea&projects=&template=breaking-change.yml&title=%5BBreaking+change%5D%3A+

**Comment by buyaa-n** [comment] 2023-05-26 22:16
I can create an issue for breaking change doc, but I am not familiar with this area therefore might not cover all information that needed for filing breaking changes issue. For example, don't know if any other character affected than the `k` etc

**Comment by buyaa-n** [comment] 2023-08-17 03:12
A breaking change [doc created](https://github.com/dotnet/docs/issues/36733), closing

**Closed by buyaa-n** 2023-08-17 03:12 UTC
Labels: documentation, area-System.Text.RegularExpressions, needs-breaking-change-doc-created
