### ISSUE TITLE
RuntimeError: abort(undefined) when running Blazor WebAssembly app with InvariantGlobalization enabled

### ISSUE THREAD

**Issue by danroth27** [dotnet/runtime#55741] opened 2021-07-15 14:03 UTC
I'm trying to update this min Blazor WebAssembly app to .NET 6 Preview 6: https://github.com/anthonychu/MinBlazorApp/tree/net6p6 (use the net6p6 branch).  When I try to run the app with InvariantGlobalization enabled I get:

```
blazor.webassembly.js:1 RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
    at abort (dotnet.6.0.0-preview.6.21352.12.js:1)
    at _abort (dotnet.6.0.0-preview.6.21352.12.js:1)
    at <anonymous>:wasm-function[5994]:0x13d6ec
    at <anonymous>:wasm-function[2461]:0x78f19
    at <anonymous>:wasm-function[2187]:0x6130b
    at <anonymous>:wasm-function[6671]:0x15d556
    at <anonymous>:wasm-function[6495]:0x154eb0
    at <anonymous>:wasm-function[3347]:0xa8bfc
    at <anonymous>:wasm-function[676]:0x1646f
    at <anonymous>:wasm-function[304]:0xa0b5
```

Disabling InvariantGlobalization works around the issue.

@lewing

**Comment by danroth27** [comment] 2021-07-15 14:05
@anthonychu

**Comment by lewing** [comment] 2021-07-15 19:06
duplicate of https://github.com/dotnet/runtime/issues/55750

**Closed by lewing** 2021-07-15 19:06 UTC
Labels: arch-wasm, area-Debugger-mono
