### ISSUE TITLE
Failure in GC\API\NoGCRegion\Callback_Svr\Callback_Svr.cmd

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#100149] opened 2024-03-22 16:16 UTC
This was found in the preview3 branch shortly after the snap.

## Build Information

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=612542
Build error leg or test failing: `GC\API\NoGCRegion\Callback_Svr\Callback_Svr.cmd [FAIL]`

## Error Message

```json
{
  "ErrorMessage" : "Callback_Svr.cmd [FAIL]",
  "BuildRetry" : false,
  "ExcludeConsoleLog" : false
}
```

- PR: https://github.com/dotnet/runtime/pull/100087
- Queue: `coreclr Pri0 Runtime Tests Run windows x64 checked`
- Job result: https://dev.azure.com/dnceng-public/public/_build/results?buildId=612542&view=logs&j=3318da16-4f37-5bd4-5590-5fa501caad81&t=d79aec97-8057-56aa-c96f-ef49ab91e155&l=32
- Log file: https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-pull-100087-merge-b8b6572972314f8480/PayloadGroup0/1/console.f621f742.log?helixlogtype=result
- Output:
```
  Starting:    GC.API.XUnitWrapper (parallel test collections = on [4 threads], stop on fail = off)
    GC\API\NoGCRegion\Callback_Svr\Callback_Svr.cmd [FAIL]
      
      Assert failure(PID 13556 [0x000034f4], Thread: 13596 [0x351c]): promoted_bytes (heap_number) == promoted
      
      CORECLR! SVR::gc_heap::mark_phase + 0x167C (0x00007ff9`a01f151c)
      CORECLR! SVR::gc_heap::gc1 + 0x240 (0x00007ff9`a01e3290)
      CORECLR! SVR::gc_heap::garbage_collect + 0x99B (0x00007ff9`a01e2ffb)
      CORECLR! SVR::gc_heap::gc_thread_function + 0x504 (0x00007ff9`a01e49a4)
      CORECLR! SVR::gc_heap::gc_thread_stub + 0x7E (0x00007ff9`a01e4e4e)
      CORECLR! <lambda_00df4fcd53073f077538c77dbea54afc>::<lambda_invoker_cdecl> + 0x74 (0x00007ff9`9feae204)
      KERNEL32! BaseThreadInitThunk + 0x14 (0x00007ff9`d06d84d4)
      NTDLL! RtlUserThreadStart + 0x21 (0x00007ff9`d2921791)
          File: D:\a\_work\1\s\src\coreclr\gc\gc.cpp:24284
          Image: C:\h\w\9DE808CA\p\corerun.exe
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=612542
**Error message validated:** `[Callback_Svr.cmd [FAIL]`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 3/22/2024 4:17:19 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[713550](https://dev.azure.com/dnceng-public/public/_build/results?buildId=713550)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=713550&view=ms.vss-test-web.build-test-results-tab&runId=17847974&resultId=115587)|dotnet/runtime#103735|
|[705708](https://dev.azure.com/dnceng-public/public/_build/results?buildId=705708)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=705708&view=ms.vss-test-web.build-test-results-tab&runId=17603798&resultId=100172)|dotnet/runtime#103055|
|[702343](https://dev.azure.com/dnceng-public/public/_build/results?buildId=702343)|dotnet/runtime|[GC\\API\\GC\\GetGenerationWR\\GetGenerationWR.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=702343&view=ms.vss-test-web.build-test-results-tab&runId=17496442&resultId=100023)|dotnet/runtime#101796|
|[699355](https://dev.azure.com/dnceng-public/public/_build/results?buildId=699355)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=699355&view=ms.vss-test-web.build-test-results-tab&runId=17404236&resultId=100165)|dotnet/runtime#101796|
|[698356](https://dev.azure.com/dnceng-public/public/_build/results?buildId=698356)|dotnet/runtime|[PayloadGroup0.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=698356&view=ms.vss-test-web.build-test-results-tab&runId=17377092&resultId=103117)|dotnet/runtime#103076|
|[697940](https://dev.azure.com/dnceng-public/public/_build/results?buildId=697940)|dotnet/runtime|[GC\\API\\GCHandleCollector\\Count\\Count.cmd](https://dev.azure.com/dnceng-public/public/_build/results?buildId=697940&view=ms.vss-test-web.build-test-results-tab&runId=17362628&resultId=100023)|dotnet/runtime#101796|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|6|

**Comment by mangod9** [comment] 2024-03-22 16:34
Yeah this seems related to a CI failure we are investigating: https://github.com/dotnet/runtime/issues/100035. Is this a consistent failure in preview3?

**Comment by mangod9** [comment] 2024-07-03 21:40
Closing since this was dupe of #100035

**Closed by mangod9** 2024-07-03 21:40 UTC
Labels: os-windows, arch-x64, area-GC-coreclr, blocking-clean-ci, runtime-coreclr, Known Build Error
