### ISSUE TITLE
Test failure: baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#106602] opened 2024-08-19 01:28 UTC
**Failed in:** [runtime-coreclr jitstress 20240817.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779360&view=ms.vss-test-web.build-test-results-tab&runId=19972668&resultId=107942&paneView=debug)

**Failed tests:**
```
coreclr linux arm64 Checked jitstress2_tiered @ (Ubuntu.2004.Arm64.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-20.04-helix-arm64v8
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.cmd
```

**Error message:**
```
 
Assert failure(PID 193 [0x000000c1], Thread: 198 [0x00c6]): (n_heaps <= heap_number) || !gc_t_join.joined()
    File: /__w/1/s/src/coreclr/gc/gc.cpp:7003
    Image: /root/helix/work/correlation/corerun

apply_reg_state: ip and cfa unchanged; stopping here (ip=0xffff8373ba58)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0xffff834709f0)
waitpid() returned successfully (wstatus 00000000) WEXITSTATUS 0 WTERMSIG 0

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/RuntimeConfiguration/TestConfigTester/output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true TestConfigTester.dll ''
Running: "/root/helix/work/workitem/e/baseservices/RuntimeConfiguration/TestConfigTester/TestConfig.dll" Verify_ServerGC_Env_Enable
    set DOTNET_gcServer=1
[createdump] Gathering state for process 193 corerun
[createdump] Crashing thread 00c6 signal 6 (0006)
[createdump] Writing crash report to file /home/helixbot/dotnetbuild/dumps/coredump.193.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.193.dmp
[createdump] Written 51478528 bytes (12568 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 250ms
System.Exception: Failed: Verify_ServerGC_Env_Enable: exit code = 134
   at TestConfigTester.RunTests()
   at __GeneratedMainWrapper.Main()
Expected: 100
Actual: 101
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 8/18/2024 5:34:04 AM
Processing /home/helixbot/dotnetbuild/dumps/coredump.193.dmp.crashreport.json
Printing stacktrace from '/home/helixbot/dotnetbuild/dumps/coredump.193.dmp.crashreport.json'
Invoking llvm-symbolizer --pretty-print
Stack trace:
----------------------------------
Thread Id: 0xc1
      Child SP               IP Call Site
 0xffffcafa3a60 0xffff838feb08 libc.so.6!memcmp
 0xffffcafa3a60 0xffff83594c3c libcoreclr.so!UnlockedLoaderHeap::UnlockedAllocMem_NoThrow(unsigned long, char const*, int) at /__w/1/s/src/coreclr/utilcode/loaderheap.cpp:1475:17
 0xffffcafa3ae0 0xffff83594ae8 libcoreclr.so!UnlockedLoaderHeap::UnlockedAllocMem(unsigned long, char const*, int) at /__w/1/s/src/coreclr/utilcode/loaderheap.cpp:1380:9
 0xffffcafa3af0 0xffff83159728 libcoreclr.so!BaseHolder<void*, FunctionBase<void*, &(ClrEnterCriticalSection(void*)), &(ClrLeaveCriticalSection(void*))>, 0ul, &(int CompareDefault<void*>(void*, void*))>::Release() at ??:0:0
 (inlined by) BaseHolder<void*, FunctionBase<void*, &(ClrEnterCriticalSection(void*)), &(ClrLeaveCriticalSection(void*))>, 0ul, &(int CompareDefault<void*>(void*, void*))>::~BaseHolder() at ??:256:9
 (inlined by) LoaderHeap::RealAllocMemUnsafe(unsigned long, char const*, int) at ??:618:5
 0xffffcafa3b50 0xffff8317e1d4 libcoreclr.so!EEClass::operator new(unsigned long, LoaderHeap*, AllocMemTracker*) at ??:0:0
 0xffffcafa3bb0 0xffff83384710 libcoreclr.so!MethodTableBuilder::CreateClass(Module*, unsigned int, int, int, int, MethodTableBuilder::bmtGenericsInfo const*, LoaderAllocator*, AllocMemTracker*) at ??:0:0
 0xffffcafa3c70 0xffff833a30c4 libcoreclr.so!ClassLoader::CreateTypeHandleForTypeDefThrowing(Module*, unsigned int, Instantiation, AllocMemTracker*) at ??:0:0
 0xffffcafa5fc0 0xffff83194144 libcoreclr.so!Nullable::IsNullableType(TypeHandle) at ??:0:0
 (inlined by) ClassLoader::CreateTypeHandleForTypeKey(TypeKey const*, AllocMemTracker*) at ??:2685:13
 0xffffcafa60e0 0xffff83193b38 libcoreclr.so!CHECK::EnterAssert() at ??:0:0
 (inlined by) ClassLoader::DoIncrementalLoad(TypeKey const*, TypeHandle, ClassLoadLevel) at ??:2614:17
 0xffffcafa61e0 0xffff831953f8 libcoreclr.so!CHECK::EnterAssert() at ??:0:0
 (inlined by) ClassLoader::LoadTypeHandleForTypeKey_Body(TypeKey const*, TypeHandle, C
```

**Stack trace:**
```
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor22|0_23(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by jkotas** [comment] 2024-08-19 14:05
Duplicate of #103839?

**Comment by v-wenyuxu** [comment] 2024-08-20 01:51
**Failed in:** [runtime-coreclr outerloop 20240819.3](https://dev.azure.com/dnceng-public/public/_build/results?buildId=780714&view=ms.vss-test-web.build-test-results-tab&runId=20019514&resultId=114602&paneView=debug)

**Failed tests:**
```
R2R-CG2 linux arm64 Checked @ (Ubuntu.2004.Arm64.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-20.04-helix-arm64v8
    - baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.cmd
```

**Error message:**
```
 /root/helix/work/workitem/e/baseservices/baseservices/../RuntimeConfiguration/TestConfigTester/TestConfigTester.sh: line 329: -r:/root/helix/work/workitem/e/baseservices/RuntimeConfiguration/TestConfigTester/IL-CG2/*.dll: No such file or directory

Assert failure(PID 1449 [0x000005a9], Thread: 1454 [0x05ae]): (n_heaps <= heap_number) || !gc_t_join.joined()
    File: /__w/1/s/src/coreclr/gc/gc.cpp:7003
    Image: /root/helix/work/correlation/corerun

apply_reg_state: ip and cfa unchanged; stopping here (ip=0xffff8390b34c)
apply_reg_state: ip and cfa unchanged; stopping here (ip=0xffff836402f0)
waitpid() returned successfully (wstatus 00000000) WEXITSTATUS 0 WTERMSIG 0

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/RuntimeConfiguration/TestConfigTester/output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/root/helix/work/workitem/e/baseservices/RuntimeConfiguration/TestConfigTester/IL-CG2/TestConfig.dll
19:58:46
Response file: /root/helix/work/workitem/e/baseservices/RuntimeConfiguration/TestConfigTester/TestConfig.dll.rsp
/root/helix/work/workitem/e/baseservices/RuntimeConfiguration/TestConfigTester/IL-CG2/TestConfig.dll
-o:/root/helix/work/workitem/e/baseservices/RuntimeConfiguration/TestConfigTester/TestConfig.dll
-r:/root/helix/work/correlation/System.*.dll
-r:/root/helix/work/correlation/Microsoft.*.dll
-r:/root/helix/work/correlation/xunit.*.dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--method-layout:random
--targetarch:arm64
--targetos:linux
Running CrossGen2:  dotnet /root/helix/work/correlation/crossgen2/crossgen2.dll @/root/helix/work/workitem/e/baseservices/RuntimeConfiguration/TestConfigTester/TestConfig.dll.rsp  
Emitting R2R PE file: /root/helix/work/workitem/e/baseservices/RuntimeConfiguration/TestConfigTester/TestConfig.dll
Running R2RDump:  dotnet /root/helix/work/correlation/R2RDump/R2RDump.dll --header --sc --in /root/helix/work/workitem/e/baseservices/RuntimeConfiguration/TestConfigTester/TestConfig.dll --out /root/helix/work/workitem/e/baseservices/RuntimeConfiguration/TestConfigTester/TestConfig.dll.r2rdump --val
19:58:47
/root/helix/work/workitem/e/baseservices/RuntimeConfiguration/TestConfigTester/IL-CG2/TestConfigTester.dll
19:58:47
Response file: /root/helix/work/workitem/e/baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll.rsp
/root/helix/work/workitem/e/baseservices/RuntimeConfiguration/TestConfigTester/IL-CG2/TestConfigTester.dll
-o:/root/helix/work/workitem/e/baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
-r:/root/helix/work/correlation/System.*.dll
-r:/root/helix/work/correlation/Microsoft.*.dll
-r:/root/helix/work/correlation/xunit.*.dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--method-layout:random
--targetarch:arm64
--targetos:linux
Running CrossGen2:  dotnet /root/helix/work/correlation/crossgen2/crossgen2.dll @/root/helix/work/workitem/e/baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll.rsp  
Emitting R2R PE file: /root/helix/work/workitem/e/baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll
Running R2RDump:  dotnet /root/helix/work/correlation/R2RDump/R2RDump.dll --header --sc --in /root/helix/work/workitem/e/baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll --out /root/helix/work/workitem/e/baseservices/RuntimeConfiguration/TestConfigTester/TestConfigTester.dll.r2rdump --val
19:58:49
/root/helix/work/workitem/e/baseservices/RuntimeConfiguration/TestConfigTester/IL-CG2/TestLibrary.dll
19:58:49
Response file: /root/helix/work/workitem/e/baseservices/RuntimeConfiguration/TestConfigTester/TestLibrary.dll.rsp
/root/helix/work/workitem/e/baseservices/RuntimeConfiguration/TestConfigTester/IL-CG2/TestLibrary.dll
-o:/root/helix/work/workitem/e/baseservices/RuntimeConfiguration/TestConfigTester/TestLibrary.dll
-r:/root/helix/work/correlation/System.*.dll
-r:/root/helix/work/correlation/Microsof
```

**Stack trace:**
```
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor22|0_23(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Closed** 2024-08-22 17:59 UTC
Labels: arch-arm64, os-linux, JitStress, area-GC-coreclr, untriaged, blocking-clean-ci-optional
