### ISSUE TITLE
[System.Net.Http.Json] HttpClient not always calling HttpContent.LoadIntoBufferAsync (reopening)

### ISSUE THREAD

**Issue by asinitson** [dotnet/runtime#53803] opened 2021-06-07 08:03 UTC
### Description

When doing a Post with HttpClient and using JsonContent, sometimes an empty body is posted if message size is small, if message size is big (couple of hundred kilobytes), then empty body is post 100% of the time. Explicitly calling LoadIntoBufferAsync() on the HttpContent resolves the issue, but as far as I understand it should be called automatically, thus I am opening an issue (bug) report. Using other clients (for example `curl`) does not expose any problems.

### Configuration

The issue was first found and can be reproduced every time with the following setup:
.NET 5.0 both inside of Docker container and locally

On the receiving side Python 3.8 Azure Functions are used. Interestingly enough the issue could not be reproduced with non-Premium version.

### Other information

The are multiple issue reports describing the same issue, but all of them are closed without any resolution. The most relevant of them is this (I would continue posting in the same issue, but it is locked, this is why I am opening a new issue):
[[System.Net.Http.Json] HttpClient not always calling HttpContent.LoadIntoBufferAsync](https://github.com/dotnet/runtime/issues/46683)

**Comment by davidfowl** [comment] 2021-06-07 08:11
Can you share your sample? I'm guessing it has to do with chunked request handling in python rather than being related to explicitly calling `LoadIntoBufferAsync`.

**Comment by asinitson** [comment] 2021-06-07 08:12
Full reproduction code:

## .NET 5.0 side

```csharp
using System;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading;
using System.Threading.Tasks;
using System.Text.Json;
using System.IO;
using System.Collections.Generic;

namespace EmptyPayloadReproduction
{
    class Program
    {
        private static readonly HttpClient _httpClient = new()
        {
            Timeout = TimeSpan.FromSeconds(40)
        };
        private static string ConnectionString => "<redacted_out>";

        static async Task Main(string[] args)
        {
            Console.WriteLine("Starting application");
            var cancellationSource = new CancellationTokenSource();
            var cancellation = cancellationSource.Token;
            Console.CancelKeyPress += (sender, arguments) =>
            {
                Console.WriteLine("User requested exit");
                arguments.Cancel = true;
                cancellationSource.Cancel();
            };

            Console.WriteLine($"Setting URI from connection string '{ConnectionString}'");
            var success = Uri.TryCreate(ConnectionString, UriKind.Absolute, out Uri connection);
            if (!success)
            {
                Console.Error.WriteLine($"Invalid connection string '{ConnectionString}'");
            }
            _httpClient.BaseAddress = connection;

            while (!cancellation.IsCancellationRequested)
            {
                Console.WriteLine($"Sending HTTP request to '{_httpClient.BaseAddress}'");

                // This produces errors frequently
                var shortQuery = new
                {
                    something = "some_string"
                };
                // This produces errors virtually 100% of the time, you can take any big-ish JSON file
                string json = File.ReadAllText("big.json");
                var longQuery = JsonSerializer.Deserialize<Dictionary<string, dynamic>>(json);

                var requestContent = JsonContent.Create(longQuery);
                // This is a fix, but it should not be needed!
                //await requestContent.LoadIntoBufferAsync();
                var response = await _httpClient.PostAsync(default(Uri), requestContent, cancellation);
                var responseContent = await response.Content.ReadAsStringAsync(cancellation);

                if (response.IsSuccessStatusCode)
                {
                    Console.WriteLine("Response received:");
                    Console.WriteLine(responseContent);
                } 
                else
                {
                    var message = $"Error {response.StatusCode}: '{responseContent}'";
                    Console.Error.WriteLine(message);
                    break;
                }
                
                // Delay between iterations does not change anything
                int iterationDelayMilliseconds = 3 * 1000;
                await Task.Delay(iterationDelayMilliseconds);
            }
            Console.WriteLine("Exiting application");
        }
    }
}
```

## Python 3.8 Azure Function

```python
# A relevant snippet, can provide full file on request
def main(req: func.HttpRequest) -> func.HttpResponse:
    json = req.get_json()
    logging.info('Received JSON message')
    try:
        content_length = len(json)
        logging.info(f'JSON length: {content_length}')
        return func.HttpResponse(
            f'JSON length: {content_length}, JSON received successfully',
            status_code=200)
    except Exception as exception:
        logging.error("Got exception!")
        logging.error(exception)
        func.HttpResponse('Something went wrong', status_code=400)
```

**Comment by asinitson** [comment] 2021-06-07 08:16
> Can you share your sample? I'm guessing it has to do with chunked request handling in python (or maybe azure functions handling or python) rather than being related to explicitly calling LoadIntoBufferAsync.

Do you have any hints on how can I test that theory? Can I switch it on/off somewhere? I created an experimental setup especially to get to the bottom of this issue, so I can test things freely.

**Comment by davidfowl** [comment] 2021-06-07 08:35
> Do you have any hints on how can I test that theory?

Do a run with the shortQuery and capture the content length:

```C#
var shortQuery = new
{
    something = "some_string"
};
var content = JsonContent.Create(shortQuery);
await content.LoadIntoBufferAsync();
Console.WriteLine(content.Headers.ContentLength);
```

Then replace the `LoadIntoBufferAsync` with the assignment of the ContentLength:

```C#
var shortQuery = new
{
    something = "some_string"
};
var content = JsonContent.Create(shortQuery);
content.Headers.ContentLength = ???; // Whatever number you got
```

**Comment by asinitson** [comment] 2021-06-07 10:02
> Then replace the LoadIntoBufferAsync with the assignment of the ContentLength:

Confirming that this resolves issue in both cases: short message and long message.

Where do I go from this? Does it mean Azure Functions themselves have some issue (chunking?)? Do you think it's in the platform itself? There is not much that can be done code-wise. As you have seen, Python reproduction is already quite small, there is not much I can change there (or is there?).

**Comment by davidfowl** [comment] 2021-06-07 15:33
Yes I think this is an azure functions issue. I'd suggest filing an issue here https://github.com/Azure/azure-functions-host. You can use `LoadIntoBufferAsync` as a workaround until the issue is resolved. Just beware of memory issues buffering everything into memory before sending it (it may or may not be a problem depending on the size).

**Comment by karelz** [comment] 2021-06-08 08:35
Triage: Seems to be external, closing. Feel free to reopen if there is more to it ...

**Closed by karelz** 2021-06-08 08:35 UTC
Labels: area-System.Net.Http, untriaged

**Comment by asinitson** [comment] 2021-06-08 15:12
**@davidfowl: Thank you for the quick response and support!**

I will considering opening bug report towards Azure Functions, but it is unlikely. Whoever is interested in reporting it, feel free to use reproduction snippets from above.

The workaround is good enough for now. Instead of dealing with Azure Functions, we decided to completely switch to a dedicated container service (probably in Kubernetes cluster). Hopefully reproduction above will be good enough warning for others considering Azure Functions with Python (not sure if other languages are affected and I don't plan to test it).

-------------------------------
_Offtopic below the line_

-------------------------------

Slightly ranty explanation why I think Azure Functions is not a good product:

* This exact issue #53803. It seems not a big deal if you know workaround, but before you get to know it, it will fail you in a bad way. This affected my team a lot and we have spent significant amount of time looking for a workaround.

* **Deployment is tricky**. There are certain combination of allowed parameters (tier/size/kind) and you have just to know compatible combinations - documentation was not very helpful in that respect, you have to wade through blog posts and bug reports. Non-compatible parameters sometimes make function silently fail to deploy or the parameter you set gets silently substituted by Azure and you get something else, not exactly what you asked for. This is why it took so much time to create those Terraform files. There are plenty of bug reports opened about deployments occasionally failing without any answers or resolution.

* **Non-premium Azure Functions regularly failed for us**, usually on Fridays (when Santa little helpers go to weekend, I guess) with warnings in Azure portal about service availability and all that stuff and sometimes without any warnings (which is worse). Problems were **not** experienced just during peak loads in the beginning of COVID19 pandemic, which hints at some systematic problems in the product.
