### ISSUE TITLE
TypeLoadException when struct contains nullable static field of itself

### ISSUE THREAD

**Issue by gurksaft** [dotnet/runtime#79636] opened 2022-12-14 09:17 UTC
### Description

If a struct contains a static field that is of the same type as itself and also nullable then referencing the type during runtime will result in a TypeLoadException with no explanation to why it fails to load the type.

### Reproduction Steps

Program.cs
```
System.Console.WriteLine(typeof(TestStruct1));
```

TestStruct1.cs
```
public struct TestStruct1
{
	public static TestStruct1? Instance;
}
```

ConsoleApp1.csproj
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>
</Project>
```

### Expected behavior

Remarking the field TestStruct1.Instance results in the expected behavior which is that the name of the struct "TestStruct1" is rendered to console. Removing the Nullable-part or changing to another struct (as Nullable) of the field type works as intended.

### Actual behavior

TypeLoadException when the type is referenced in runtime. Changing from `typeof(TestStruct1)` to `new TestStruct1()` in Program.cs makes no difference.

### Known Workarounds

Write code that does not use this pattern at all; struct with static nullable field of itself.

### Configuration

Tested with:
* .NET 6 and 7
* Windows 10 and 11
* Visual Studio 2022 17.4.3 and 14.7.0
* Intel x64 CPU
* Published Release build and debug

**Comment by DaZombieKiller** [comment] 2022-12-14 10:08
This is a duplicate of https://github.com/dotnet/runtime/issues/6924.

**Closed** 2023-02-27 14:16 UTC
Labels: area-TypeSystem-coreclr, untriaged
