### ISSUE TITLE
Test failure JIT\\jit64\\localloc\\call\\call07_small\\call07_small.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#65943] opened 2022-02-28 02:25 UTC
Run: [runtime-coreclr r2r-extra 20220226.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1634506&view=ms.vss-test-web.build-test-results-tab&runId=45277474&resultId=101646&paneView=debug)

Failed test:
```
R2R windows x86 Checked jitstress1 @ Windows.10.Amd64.Open
- JIT\\jit64\\localloc\\call\\call07_small\\call07_small.cmd
- JIT\\jit64\\mcc\\interop\\mcc_i37\\mcc_i37.cmd
- JIT\\jit64\\mcc\\interop\\mcc_i77\\mcc_i77.cmd
- JIT\\Methodical\\VT\\callconv\\jumper4_il_r\\jumper4_il_r.cmd
- JIT\\jit64\\localloc\\call\\call07_dynamic\\call07_dynamic.cmd

R2R windows arm64 Checked jitstress1 @ Windows.10.Arm64v8.Open
- JIT\\jit64\\mcc\\interop\\mcc_i77\\mcc_i77.cmd
- JIT\\jit64\\mcc\\interop\\mcc_i37\\mcc_i37.cmd

R2R windows x86 Checked jitstress2_tiered @ Windows.10.Amd64.Open
- JIT\\Performance\\CodeQuality\\Bytemark\\Bytemark\\Bytemark.cmd
- JIT\\superpmi\\superpmicollect\\Bytemark\\Bytemark.cmd

R2R windows x64 Checked jitstressregs0x10 @ Windows.10.Amd64.Open
- JIT\\HardwareIntrinsics\\X86\\Sse41\\Sse41_ro\\Sse41_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse41\\DotProduct_r\\DotProduct_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse41\\MultipleSumAbsoluteDifferences_ro\\MultipleSumAbsoluteDifferences_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse41\\Multiply_ro\\Multiply_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\**

R2R windows arm64 Checked jitstress1_tiered @ Windows.10.Arm64v8.Open
- JIT\\Performance\\CodeQuality\\Bytemark\\Bytemark\\Bytemark.cmd
- JIT\\superpmi\\superpmicollect\\Bytemark\\Bytemark.cmd
- GC\\API\\GC\\GetTotalAllocatedBytes\\GetTotalAllocatedBytes.cmd

R2R windows x64 Checked jitstress2_tiered @ Windows.10.Amd64.Open
- JIT\\Performance\\CodeQuality\\Bytemark\\Bytemark\\Bytemark.cmd
- JIT\\superpmi\\superpmicollect\\Bytemark\\Bytemark.cmd
- JIT\\Methodical\\VT\\callconv\\jumper5_il_r\\jumper5_il_r.cmd

R2R windows arm64 Checked jitstress2 @ Windows.10.Arm64v8.Open
- JIT\\jit64\\mcc\\interop\\mcc_i37\\mcc_i37.cmd
- JIT\\jit64\\mcc\\interop\\mcc_i77\\mcc_i77.cmd

R2R windows x64 Checked jitstress1_tiered @ Windows.10.Amd64.Open
- JIT\\Performance\\CodeQuality\\Bytemark\\Bytemark\\Bytemark.cmd
- JIT\\superpmi\\superpmicollect\\Bytemark\\Bytemark.cmd
- Loader\\classloader\\InterfaceFolding\\TestCase2_Nested_J_Nested_I\\TestCase2_Nested_J_Nested_I.cmd
- Loader\\classloader\\rmv\\il\\RMV-2-8-33-two\\RMV-2-8-33-two.cmd
- JIT\\Methodical\\VT\\callconv\\jumper5_il_r\\jumper5_il_r.cmd
- Loader\\classloader\\explicitlayout\\Regressions\\ASURT\\ASURT150271\\test13\\test13.cmd
- JIT\\HardwareIntrinsics\\General\\Vector256\\Vector256_r\\Vector256_r.cmd
- JIT\\HardwareIntrinsics\\General\\Vector256_1\\Vector256_1_r\\Vector256_1_r.cmd
- JIT\\HardwareIntrinsics\\General\\Vector256_1\\Vector256_1_ro\\Vector256_1_ro.cmd
- JIT\\HardwareIntrinsics\\**

```
**Error message:**
```
Could Not Find C:\h\w\B64E09D1\w\B2790994\e\JIT\jit64\localloc\call\call07_small\IL-CG2\composite-r2r.dll
Could Not Find C:\h\w\B64E09D1\w\B2790994\e\JIT\jit64\localloc\call\call07_small\call07_small.dll.rsp
Could Not Find C:\h\w\B64E09D1\w\B2790994\e\JIT\jit64\localloc\call\call07_small\localloc_common.dll.rsp
Could Not Find C:\h\w\B64E09D1\w\B2790994\e\JIT\jit64\localloc\call\call07_small\TestLibrary.dll.rsp
Fatal error. 0xC0000005
at LocallocTest.func0(Int32, Int32, Int32, Int32, Int32, Int32, Int32, Int32, Int32*)
at LocallocTest.Main()

Return code:      1
Raw output file:      C:\h\w\B64E09D1\w\B2790994\uploads\Reports\JIT.jit64\localloc\call\call07_small\call07_small.output.txt
Raw output:
BEGIN EXECUTION
call07_small.dll
localloc_common.dll
TestLibrary.dll
3 file(s) copied.
Response file: C:\h\w\B64E09D1\w\B2790994\e\JIT\jit64\localloc\call\call07_small\call07_small.dll.rsp
C:\h\w\B64E09D1\w\B2790994\e\JIT\jit64\localloc\call\call07_small\IL-CG2\call07_small.dll
-o:C:\h\w\B64E09D1\w\B2790994\e\JIT\jit64\localloc\call\call07_small\call07_small.dll
--targetarch:x86
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\B64E09D1\p\System..dll
-r:C:\h\w\B64E09D1\p\Microsoft..dll
-r:C:\h\w\B64E09D1\p\mscorlib.dll
-r:C:\h\w\B64E09D1\p\netstandard.dll
-O
" "dotnet" "C:\h\w\B64E09D1\p\crossgen2\crossgen2.dll" @"C:\h\w\B64E09D1\w\B2790994\e\JIT\jit64\localloc\call\call07_small\call07_small.dll.rsp"   -r:C:\h\w\B64E09D1\w\B2790994\e\JIT\jit64\localloc\call\call07_small\IL-CG2*.dll"
Emitting R2R PE file: C:\h\w\B64E09D1\w\B2790994\e\JIT\jit64\localloc\call\call07_small\call07_small.dll
Response file: C:\h\w\B64E09D1\w\B2790994\e\JIT\jit64\localloc\call\call07_small\localloc_common.dll.rsp
C:\h\w\B64E09D1\w\B2790994\e\JIT\jit64\localloc\call\call07_small\IL-CG2\localloc_common.dll
-o:C:\h\w\B64E09D1\w\B2790994\e\JIT\jit64\localloc\call\call07_small\localloc_common.dll
--targetarch:x86
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\B64E09D1\p\System..dll
-r:C:\h\w\B64E09D1\p\Microsoft..dll
-r:C:\h\w\B64E09D1\p\mscorlib.dll
-r:C:\h\w\B64E09D1\p\netstandard.dll
-O
" "dotnet" "C:\h\w\B64E09D1\p\crossgen2\crossgen2.dll" @"C:\h\w\B64E09D1\w\B2790994\e\JIT\jit64\localloc\call\call07_small\localloc_common.dll.rsp"   -r:C:\h\w\B64E09D1\w\B2790994\e\JIT\jit64\localloc\call\call07_small\IL-CG2*.dll"
Emitting R2R PE file: C:\h\w\B64E09D1\w\B2790994\e\JIT\jit64\localloc\call\call07_small\localloc_common.dll
Response file: C:\h\w\B64E09D1\w\B2790994\e\JIT\jit64\localloc\call\call07_small\TestLibrary.dll.rsp
C:\h\w\B64E09D1\w\B2790994\e\JIT\jit64\localloc\call\call07_small\IL-CG2\TestLibrary.dll
-o:C:\h\w\B64E09D1\w\B2790994\e\JIT\jit64\localloc\call\call07_small\TestLibrary.dll
--targetarch:x86
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\B64E09D1\p\System..dll
-r:C:\h\w\B64E09D1\p\Microsoft..dll
-r:C:\h\w\B64E09D1\p\mscorlib.dll
-r:C:\h\w\B64E09D1\p\netstandard.dll
-O
" "dotnet" "C:\h\w\B64E09D1\p\crossgen2\crossgen2.dll" @"C:\h\w\B64E09D1\w\B2790994\e\JIT\jit64\localloc\call\call07_small\TestLibrary.dll.rsp"   -r:C:\h\w\B64E09D1\w\B2790994\e\JIT\jit64\localloc\call\call07_small\IL-CG2*.dll"
Emitting R2R PE file: C:\h\w\B64E09D1\w\B2790994\e\JIT\jit64\localloc\call\call07_small\TestLibrary.dll
"C:\h\w\B64E09D1\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  call07_small.dll
Expected: 100
Actual: -1073741819
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\B64E09D1\p
C:\h\w\B64E09D1\w\B2790994\e\JIT\jit64\localloc\call\call07_small\call07_small.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_jit64._localloc_call_call07_small_call07_small_._localloc_call_call07_small_call07_small_cmd()
```

**Comment by jakobbotsch** [comment] 2022-06-07 10:54
I was not able to reproduce the xarch ones and it seems none of these are being hit in recent jitstress runs, so I will probably just close this.

@BruceForstall you marked this blocking-clean-ci-optional recently; did you see some of these failures then, or were you just doing this for all the test failures in the optional pipelines?

**Comment by BruceForstall** [comment] 2022-06-07 17:25
I was looking at "area-CodeGen-coreclr" issues that came from CI test failures, and marking them as such.

I see that with https://dev.azure.com/dnceng/public/_build/results?buildId=1808217&view=ms.vss-test-web.build-test-results-tab, the set of failures is different, so it's fine to close this.

**Closed by BruceForstall** 2022-06-07 17:25 UTC
Labels: arch-arm64, arch-x86, os-windows, JitStress, arch-x64, area-CodeGen-coreclr, blocking-clean-ci-optional
