### ISSUE TITLE
ImageSharp broken on .NET 5

### ISSUE THREAD

**Issue by tannergooding** [dotnet/runtime#42912] opened 2020-09-30 18:31 UTC
https://github.com/SixLabors/ImageSharp/issues/1356 was raised as ImageSharp being broken on .NET 5 RC 1.

Although it is still not clear if this is an issue with dotnet/runtime or maybe something wrong with the project (such as incorrect build targets/dependencies), this quantifies as something we would classify as `blocking-release` if it is indeed an issue coming from the runtime or libraries themselves.

This is being opened as a tracking issue until we can finish root causing the issue and determine what here is broken.

**Comment by tannergooding** [comment] 2020-09-30 18:32
CC. @danmosemsft, @jeffschwMSFT, @richlander 

Going to assign this to myself and will try to work with James to ensure we can resolve the issue.

**Comment by AaronRobinsonMSFT** [comment] 2020-09-30 19:09
@tannergooding Please reach out to me if you need any help investigating this or there is even a small chance it is interop related.

**Comment by safern** [comment] 2020-09-30 21:03
@tannergooding I would be surprised if this was System.Drawing issue as ImageSharp doesn't use it, right?

**Comment by tannergooding** [comment] 2020-09-30 21:12
Yeah, I don't think this is `area-System.Drawing` (CC. @jeffhandley).

I don't think there is a good area we can categorize this as other than just "tracking-external-issue", at least until we can determine if it is actually a runtime issue or not.

The latest comments indicate (https://github.com/SixLabors/ImageSharp/issues/1356#issuecomment-701605488): 
> Just to re-iterate, I only see the issue when deploying a release configuration to an Azure App Service from Visual Studio 2019 with a self-contained .Net 5 RC-1 runtime being installed. And only when the App Service is rather limited in memory. Is there anyway we can use that exact setup to recreate the issue?

**Comment by danmosemsft** [comment] 2020-09-30 21:22
Do they know whether it repros on Linux?

**Comment by jeffhandley** [comment] 2020-09-30 22:43
Ah, sorry for the wrong label.

**Comment by jeffschwMSFT** [comment] 2020-09-30 22:54
@jeffhandley since this is still in flight I am not sure which label makes the most sense.  I added meta just as a placeholder.

**Comment by tannergooding** [comment] 2020-10-01 15:15
There is a relatively simple repro now: [repro.zip](https://github.com/dotnet/runtime/files/5313046/repro.zip)

You can extract the above zip and run it on a machine with a single core (such as can be configured in Hyper-V) and it will result in the outputs being corrupted.

CC. @danmosemsft, @jeffschwMSFT, @jkotas

**Comment by janvorli** [comment] 2020-10-01 16:33
I'll take a look.

**Comment by mangod9** [comment] 2020-10-01 17:19
I am able to repro this. I have reduced the repro further to remove aync: 

``` csharp
    class Program
    {
        static async Task Main(string[] args)
        {
            var imageProcessor = new ImageProcessor();

            string outputFileName = "small.jpg";
            string inputFile = @"93362884-d5684100-f846-11ea-852a-b3735e5503a7_small.png";
            ResizeTestAsync(imageProcessor, outputFileName, inputFile);

            Console.WriteLine("done");
            Console.ReadLine();
        }

        private static void ResizeTestAsync(ImageProcessor imageProcessor, string outputFileName, string inputFile)
        {
            using Stream inputStream = new FileStream(inputFile, FileMode.Open, FileAccess.Read);
            using (MemoryStream lowResStream = imageProcessor.ResizeTo(inputStream, ImageProcessor.LowResWidth))
            {
                using (Stream outputStream = new FileStream(outputFileName, FileMode.Create, FileAccess.Write))
                {
                    lowResStream.CopyTo(outputStream);
                }
            }
        }
    }

    public class ImageProcessor
    {
        public const int LowResWidth = 700;

        public MemoryStream ResizeTo(Stream input, int width)
        {
            var output = new MemoryStream();
            input.Seek(0, SeekOrigin.Begin);
            using Image image = Image.Load(input);
            image.Mutate(x => x.Resize(width: width, 0));
            image.SaveAsJpeg(output);
            output.Seek(0, SeekOrigin.Begin);
            input.Seek(0, SeekOrigin.Begin);
            return output;
        }
    }
}
```

If I replace `image.Mutate(x => x.Resize(width: width, 0));` with something like `image.Mutate(x => x.Flip(FlipMode.None));` for example the issue doesnt repro. So something related to resizing is most likely the issue.

**Comment by JimBobSquarePants** [comment] 2020-10-01 20:43
Hey @mangod9 

`image.Mutate(x => x.Flip(FlipMode.None));` used like that doesn't actually do anything. It's normally used in conjunction with `RotateMode` in the  `RotateFlip` method.. 

https://github.com/SixLabors/ImageSharp/blob/4dadf2494018564c5b7b1199faeb5ab3840a1ee3/src/ImageSharp/Processing/Processors/Transforms/Linear/FlipProcessor%7BTPixel%7D.cs#L37-L46

According to the ImageSharp thread this is affecting other methods also like `Crop` which is a very different operation to `Resize` internally (there's no pixel format transforms to from/Vector4, different parallelism rules, It's basically buffer copying into a new buffer span). 

https://github.com/SixLabors/ImageSharp/issues/1356#issuecomment-701194676

**Comment by mangod9** [comment] 2020-10-01 21:05
Ok thanks for the clarification @JimBobSquarePants. It felt like `Flip` would be just another transform similar to `Resize`.  Do you happen to know if there is any specific async behavior as part of Resize/Crop operations?

**Comment by tocsoft** [comment] 2020-10-01 22:12
The only async stuff ImageSharp does is before decoding, when being passed some nonseekable streams (I.e. the aspnetcore ones that block sync reads/writes), we call CopyToAsync into a MemoryStream before decoding synchronously. All the rest of our general processing code is sync.

**Comment by tocsoft** [comment] 2020-10-02 07:29
The corruption is being introduced during the JPEG decoding step no async is involved in that process. If it makes a differnece our decoder is making use of some of intrinsics APIs (thats the only CPU level stuff in our code).

My repoduction of the isssue can be found here https://github.com/tocsoft/Net5CorruptingImageSharp/tree/d62a120bb13165611598c91fc48eac35a83e5e3f

This also verifies that its effecting linux too and not just windows.

**Comment by JimBobSquarePants** [comment] 2020-10-02 07:35
@tocsoft I thought @brianpopow said it was all decoders?

https://github.com/SixLabors/ImageSharp/issues/1356#issuecomment-701000973

That's great news if you have narrowed it down to there though!

**Comment by tocsoft** [comment] 2020-10-02 07:51
To be fair I haven't checked the other decoders only JPEG at this stage.. but in the test case that currently being investigated its the decoder that's at fault.

**Comment by janvorli** [comment] 2020-10-02 08:20
I have tried to repro it yesterday and it didn't happed during jpeg decoding. The decoded image was correct (I've modified the repro to save it to a file right before performing Mutate in the ResizeTo method) and the scaled image was broken.

**Comment by mangod9** [comment] 2020-10-02 08:37
I seem to be able to repro with the simpler repro from @tocsoft, which I simplified further by using a very small `9x7` jpg. Does appear like its decoding incorrectly possibly in this function (when compared to a working machine): https://github.com/SixLabors/ImageSharp/blob/78a584e8482b052d7a9885682299e2f37518d83d/src/ImageSharp/Formats/Jpeg/Components/FastFloatingPointDCT.cs#L76 which happens to have `Vector4` + AggressiveInlining so wondering if its a codegen issue.

**Comment by mangod9** [comment] 2020-10-02 09:28
Actually after debugging a little further it appears to be something here: https://github.com/SixLabors/ImageSharp/blob/64e7d6a22aced9fdbd8d53e5f5d8a4b52f9081e0/src/ImageSharp/Formats/Jpeg/Components/Block8x8F.cs#L508

**Comment by brianpopow** [comment] 2020-10-02 10:32
> @tocsoft I thought @brianpopow said it was all decoders?
> 
> [SixLabors/ImageSharp#1356 (comment)](https://github.com/SixLabors/ImageSharp/issues/1356#issuecomment-701000973)
> 
> That's great news if you have narrowed it down to there though!

I think there are two different maybe related issues:

1. Just decode an jpg image and save it: This will result in this green stripes pattern. Decoding and saving the image works for PNG, BMP and TGA. Decoding and saving GIF seems to have another issue. The image seems to be yellowish.

2. Decoding an image (no matter which one) and mutating it will result in half the image is missing, like reported from the thread starter of [Issue1356](github.com/SixLabors/ImageSharp/issues/1356). So far i can verify that resizing will have this effect and EdgeDetection.

**Comment by jeffschwMSFT** [comment] 2020-10-02 13:37
@AndyAyersMS @JulieLeeMSFT @tannergooding

**Comment by JulieLeeMSFT** [comment] 2020-10-02 16:36
@echesakovMSFT

**Comment by echesakovMSFT** [comment] 2020-10-02 17:25
@JulieLeeMSFT Taking a look.

**Comment by mangod9** [comment] 2020-10-02 18:31
I have provided repro details to Egor. It appears that turning off intrinsics make things work.

**Comment by tannergooding** [comment] 2020-10-02 18:37
I'm looking as well and I don't see any issues in the actual codegen. The managed code likewise does not appear to do anything problematic with the `ref` that might cause GC corruption or the like.

**Comment by AaronRobinsonMSFT** [comment] 2020-10-02 18:41
>I'm looking as well and I don't see any issues in the actual codegen. 

Was tiering also ruled out?

**Comment by tannergooding** [comment] 2020-10-02 18:44
> Was tiering also ruled out?

It repro's under `Debug` for me. The only requirement I found was that you have a 1 core machine for it to consistently repro.

**Comment by mangod9** [comment] 2020-10-02 18:52
One of the things I notice was that a simple `Vector<short>.Zero` shows some corrupted values, only when watching within a debugger. `ToString()` does output the right values however. So not sure if that's just a debugging weirdness or an actual issue, but it doesnt repro with 3.1 or on a multi-proc machine.

**Comment by echesakovMSFT** [comment] 2020-10-02 18:56
> Was tiering also ruled out?

@AaronRobinsonMSFT I ran a repro that Manish gave me with `COMPlus_TieredCompilation=0` and still see the issue.
On other,  I don't see the issue with `COMPlus_EnableAvx2=0`, so I am trying to localize all the places in ImageSharp using the intrinsics.

**Comment by AaronRobinsonMSFT** [comment] 2020-10-02 18:58
>On other, I don't see the issue with COMPlus_EnableAvx2=0, so I am trying to localize all the places in ImageSharp using the intrinsics.

Great. I am glad we have some options that influence behavior - helps pinpoint these issues.

**Comment by tannergooding** [comment] 2020-10-02 19:11
> One of the things I notice was that a simple Vector<short>.Zero shows some corrupted values, only when watching within a debugger. ToString() does output the right values however. So not sure if that's just a debugging weirdness or an actual issue, but it doesnt repro with 3.1 or on a multi-proc machine.

`Vector<T>` not working quite right in the debugger is a known issue: <https://github.com/dotnet/runtime/issues/9688>. Basically the debugger will only show the first 16-bytes  not the upper 16-bytes as they don't have a backing field (the VM resizes the type if AVX2 is supported).

If the first 16-bytes are corrupted, that sounds like a different issue, however.

**Comment by mangod9** [comment] 2020-10-02 19:55
> Basically the debugger will only show the first 16-bytes not the upper 16-bytes as they don't have a backing field (the VM resizes the type if AVX2 is supported).
Ok interesting. wonder why it doesnt occur on multiproc machine.

**Comment by echesakovMSFT** [comment] 2020-10-02 20:17
The issue seems to be related to `ExtendedIntrinsics.ByteToNormalizedFloatReduce`.

With the following change to SimdUtils.cs the issue does not reproduce:

```diff
index 7f917648d..8b6938e0b 100644
--- a/src/ImageSharp/Common/Helpers/SimdUtils.cs
+++ b/src/ImageSharp/Common/Helpers/SimdUtils.cs
@@ -81,7 +81,7 @@ internal static void ByteToNormalizedFloat(ReadOnlySpan<byte> source, Span<float
             DebugGuard.IsTrue(source.Length == dest.Length, nameof(source), "Input spans must be of same length!");

 #if SUPPORTS_EXTENDED_INTRINSICS
-            ExtendedIntrinsics.ByteToNormalizedFloatReduce(ref source, ref dest);
+            //ExtendedIntrinsics.ByteToNormalizedFloatReduce(ref source, ref dest);
 #else
             BasicIntrinsics256.ByteToNormalizedFloatReduce(ref source, ref dest);
 #endif
```

**Comment by tannergooding** [comment] 2020-10-02 20:23
> Ok interesting. wonder why it doesnt occur on multiproc machine.

@mangod9, we have another rarely reproducing bug here where @jkotas speculated it might be due to a thread suspension issue corrupting registers: https://github.com/dotnet/runtime/issues/41108#issuecomment-701652105

Given that both issues involve vector types, and the ImageSharp issue only reproduces on a 1-core machine, it makes me think that they could be related.
Possibly some thread-suspension issue or possibly some GC metadata that isn't getting updated correctly (only the ImageSharp issue involves `refs`).

**Comment by mangod9** [comment] 2020-10-02 20:31
hmm.. wonder if we should run those failing tests on the single proc machine to check if they fail consistently there.

**Comment by tannergooding** [comment] 2020-10-02 20:47
The issues do look to be unrelated, I can't repro #41108 on the 1-core VM.

However, I got an even simpler repro for this issue and it does look to be the upper 16-bytes getting corrupted somewhere:
```
var f = new Vector<float>(1.0f);
Console.WriteLine(f);
```

will print something like:
```
<1, 1, 1, 1, 0, 0, 1.7832655E+23, 4.5908E-41>
```

when it should print:
```
<1, 1, 1, 1, 1, 1, 1, 1>
```

**Comment by tannergooding** [comment] 2020-10-02 20:51
I'm going to get a checked build of the latest JIT built and see if I can get a JIT dump produced to try and spot any additional differences that may exist, if any

**Comment by mangod9** [comment] 2020-10-02 21:00
Interestingly for some reason I wasnt able to get `Console.WriteLine` to print the corrupted values, but was seeing them in the Debugger

**Comment by antonfirsov** [comment] 2020-10-02 21:04
We were able to narrow it further by running ImageSharp unit tests. I can confirm Vector<T> is root cause somewhere in ImageSharp uint32 -> float conversion pipeline. Can provide more info on Monday.

**Comment by jkotas** [comment] 2020-10-02 21:25
Potentially related: https://github.com/dotnet/runtime/issues/38974

**Comment by jkotas** [comment] 2020-10-02 21:27
Now that the GC may be sometime using AVX registers due to https://github.com/dotnet/runtime/tree/master/src/coreclr/src/gc/vxsort, this latent bug may be causing actual corruptions.

**Comment by tannergooding** [comment] 2020-10-02 21:28
> I'm going to get a checked build of the latest JIT built and see if I can get a JIT dump produced to try and spot any additional differences that may exist, if any

Using the latest head, I can't get a repro for any of the cases, so this may be something we've fixed.

Running either with a checked RC1 build gives:
```
Assert failure(PID 21164 [0x000052ac], Thread: 21900 [0x558c]): Assertion failed 'sizeBytes == originalSize' in 'System.SpanHelpers:IndexOf(byref,ushort,int):int' during 'Pre-import' (IL size 1068)

    File: C:\Repos\runtime_base\src\coreclr\src\jit\importer.cpp Line: 1589
    Image: C:\repos\Core_Root_RC1\CoreRun.exe
```

I do not see the same if I up the core count to 2+. I have not tried to repro on RC2 yet.

**Comment by echesakovMSFT** [comment] 2020-10-02 21:29
> 
> 
> > I'm going to get a checked build of the latest JIT built and see if I can get a JIT dump produced to try and spot any additional differences that may exist, if any
> 
> Using the latest head, I can't get a repro for any of the cases, so this may be something we've fixed.
> 
> Running either with a checked RC1 build gives:
> 
> ```
> Assert failure(PID 21164 [0x000052ac], Thread: 21900 [0x558c]): Assertion failed 'sizeBytes == originalSize' in 'System.SpanHelpers:IndexOf(byref,ushort,int):int' during 'Pre-import' (IL size 1068)
> 
>     File: C:\Repos\runtime_base\src\coreclr\src\jit\importer.cpp Line: 1589
>     Image: C:\repos\Core_Root_RC1\CoreRun.exe
> ```
> 
> I do not see the same if I up the core count to 2+. I have not tried to repro on RC2 yet.

I built the runtime on top of 3c6e6cc14728ce9a1955e076d2a758407dc70f5a to collect the jit dump and the issue (and assert) doesn't repro with the newer version of runtime.

**Comment by echesakovMSFT** [comment] 2020-10-02 21:34
Some change between 38017c3935de95d0335bac04f4901ddfc2718656 and 3c6e6cc14728ce9a1955e076d2a758407dc70f5a either fixed or hid the issue.

**Comment by tannergooding** [comment] 2020-10-02 21:47
I'll run these through git bisect and report back when done.

**Comment by JulieLeeMSFT** [comment] 2020-10-02 21:48
CC @CarolEidt

**Comment by echesakovMSFT** [comment] 2020-10-02 21:53
I think it could be b1f107e6f13252644bbff443670eb4ec540aad86 that made the difference - I reverted this commit on top of release/5.0 (3c6e6cc) and re-building/trying to repro the issue.

**Comment by echesakovMSFT** [comment] 2020-10-02 22:04
> 
> 
> I think it could be [b1f107e](https://github.com/dotnet/runtime/commit/b1f107e6f13252644bbff443670eb4ec540aad86) that made the difference - I reverted this commit on top of release/5.0 ([3c6e6cc](https://github.com/dotnet/runtime/commit/3c6e6cc14728ce9a1955e076d2a758407dc70f5a)) and re-building/trying to repro the issue.

Confirm that this is the case - build of runtime on top of 3c6e6cc minus b1f107e fails with the same assert.

**Comment by echesakovMSFT** [comment] 2020-10-02 22:05
To double check this I will run ImageSharp repro with 5.0.100 RC2

**Comment by mangod9** [comment] 2020-10-02 22:10
good to know that its already fixed :). From the PR it isnt very clear why it would be consistent failure only on single proc. Is there an explanation?

**Comment by echesakovMSFT** [comment] 2020-10-02 22:20
> 
> 
> To double check this I will run ImageSharp repro with 5.0.100 RC2

5.0.0-rc.2.20475.5 works as expected - no image corruption

**Comment by JulieLeeMSFT** [comment] 2020-10-02 22:22
> 5.0.0-rc.2.20475.5 works as expected - no image corruption

Great! Did we test on Windows/Linux as well as single proc machine as others observed issues there?

**Comment by echesakovMSFT** [comment] 2020-10-02 22:24
> 
> 
> > 5.0.0-rc.2.20475.5 works as expected - no image corruption
> 
> Great! Did we test on Windows/Linux as well as single proc machine as others observed issues there?

I did the test only on the single proc Windows machine that Manish provided me.

**Comment by tannergooding** [comment] 2020-10-02 22:25
`git bisect` reports the same. b1f107e6f13252644bbff443670eb4ec540aad86 is `good` and f6b31c21e1369a387cd49e82d4d6e8998b5172ed is `bad`.

The assert goes away as does the image corruption.

> From the PR it isnt very clear why it would be consistent failure only on single proc. Is there an explanation?

The AVX register is meant to be ECX, bit 28. One of the queries was checking EDX, bit 28 by accident.

EDX, bit 28 is the bit that indicates Multi-Threading support:
![image](https://user-images.githubusercontent.com/10487869/94974451-7a2f8300-04c3-11eb-80d0-a44eff120765.png)

> A value of 0 for HTT indicates there is only a single logical processor in
the package and software should assume only a single APIC ID is reserved. A value of 1 for HTT indicates the
value in CPUID.1.EBX[23:16] (the Maximum number of addressable IDs for logical processors in this package) is
valid for the package.

**Comment by echesakovMSFT** [comment] 2020-10-02 22:28
@JulieLeeMSFT I am checking Linux x64 runtime now - rc1 vs rc2

**Comment by mangod9** [comment] 2020-10-02 22:32
> EDX, bit 28 is the bit that indicates Multi-Threading support:

Ah makes sense now.

**Comment by echesakovMSFT** [comment] 2020-10-02 23:20
Have troubles reproducing this locally on Linux - no matter what I do the cpuid still shows HTT to be set and there is no issue on both rc1 and rc2.

@brianpopow as far as I understood from https://github.com/SixLabors/ImageSharp/issues/1356 you managed to repro this on  Linux - could you do this only an Azure VM or you also had a local repro?

**Comment by echesakovMSFT** [comment] 2020-10-03 00:44
I managed to get the repro on Linux. In order to do that I created a Hyper-V VM with one CPU and loaded an Ubuntu Live image.

I can confirm that the issue there was fixed with RC2. Attached are the result of Manish's repro with .NET 5.0 RC1 and RC2:

**5.0.100-rc.1.20454.5**
![garden-rc1](https://user-images.githubusercontent.com/5292656/94979212-59bcf400-04d6-11eb-9279-83dd4bfd70d7.jpg)
**5.0.100-rc.2.20480.7**
![garden-rc2](https://user-images.githubusercontent.com/5292656/94979208-57f33080-04d6-11eb-8435-3c6e2aa21e72.jpg)

**Comment by mangod9** [comment] 2020-10-03 01:01
Thanks @echesakovMSFT and @tannergooding for investigating! @JimBobSquarePants @tocsoft @brianpopow, if you could also please validate we can close this out. .net 5 RC2 should be releasing in two weeks. Thx!

**Comment by brianpopow** [comment] 2020-10-03 07:32
@mangod9 is there a docker image of .net 5 RC2 available? That would be the easiest way for me to reproduce this.

**Comment by mangod9** [comment] 2020-10-03 19:20
@brianpopow unfortunately docker images are not built for daily builds. You could manually install the sdk from here: https://github.com/dotnet/installer/blob/master/README.md#installers-and-binaries. Another option could be to build the repro app as a self-contained app using RC2 for xcopy deployment to the single proc image or VM.

**Comment by brianpopow** [comment] 2020-10-05 04:15
@mangod9: me and @antonfirsov have tested with the current dotnet master branch and can confirm that the issue is fixed.

Thanks to all for investigating this issue!

**Comment by mangod9** [comment] 2020-10-05 04:17
great, thanks for confirming. Will close this now :)

**Closed by mangod9** 2020-10-05 04:17 UTC
Labels: area-VM-coreclr, blocking-release, tracking-external-issue
