### ISSUE TITLE
[wasm][aot] Test failure in System.Drawing.Primitives test suite

### ISSUE THREAD

**Issue by vargaz** [dotnet/runtime#83394] opened 2023-03-14 16:21 UTC
### Description

Expected result: pass
Actual result:
```
  fail: [FAIL] System.Drawing.PrimitivesTest.RectangleTests.RectangleFConversionTest(x: 3.40282347E+38, y: -3.40282347E+38, width: 3.40282347E+38, height: -3.40282347E+38)
  info: Assert.Equal() Failure
  info: Expected: {X=-2147483648,Y=-2147483648,Width=-2147483648,Height=-2147483648}
  info: Actual:   {X=2147483647,Y=-2147483648,Width=2147483647,Height=-2147483648}
  info:    at System.Reflection.MethodInvoker.Invoke(Object , IntPtr* , BindingFlags )
  fail: [FAIL] System.Drawing.PrimitivesTest.RectangleTests.RectangleFConversionTest(x: -3.40282347E+38, y: 3.40282347E+38, width: -3.40282347E+38, height: 3.40282347E+38)
  info: Assert.Equal() Failure
  info: Expected: {X=-2147483648,Y=-2147483648,Width=-2147483648,Height=-2147483648}
  info: Actual:   {X=-2147483648,Y=2147483647,Width=-2147483648,Height=2147483647}
  info:    at System.Reflection.MethodInvoker.Invoke(Object , IntPtr* , BindingFlags )
```

To reproduce:
```./dotnet.sh build /t:Test /p:TargetOS=browser /p:TargetArchitecture=wasm /p:Configuration=Release /p:EnableAggressiveTrimming=true /p:RunAOTCompilation=true /p:WasmNativeStrip=false src/libraries/System.Drawing.Primitives/tests/```

Testcase:
```
using System;
using System.Drawing;
using System.Runtime.CompilerServices;

public class Test
{
	public static void Main () {
		float x = float.MaxValue;

		var rect = new RectangleF(x, x, x, x);

		var r2 = Rectangle.Truncate(rect);
		Console.WriteLine (r2);
	}
}
```

The testcase should print:
```{X=-2147483648,Y=-2147483648,Width=-2147483648,Height=-2147483648}```
With AOT it prints:
```{X=2147483647,Y=2147483647,Width=2147483647,Height=2147483647}```

### Reproduction Steps

.

### Expected behavior

.

### Actual behavior

.

### Regression?

Yes

### Known Workarounds

.

**Comment by vargaz** [comment] 2023-03-14 16:33
Disabled in:
https://github.com/dotnet/runtime/pull/83397

**Comment by lewing** [comment] 2023-08-18 16:35
@radekdoulik @vargaz any thoughts on this?

**Comment by ilonatommy** [comment] 2024-07-04 13:19
It is still an issue. @radekdoulik, what might be the problem here?

**Comment by lewing** [comment] 2024-07-29 20:28
duplicate of https://github.com/dotnet/runtime/issues/60585

**Closed by lewing** 2024-07-29 20:28 UTC
Labels: arch-wasm, area-System.Drawing, disabled-test, wasm-aot-test
