### ISSUE TITLE
System.Text.Json Json doesn't serialize dictionary type class property 

### ISSUE THREAD

**Issue by leung85** [dotnet/runtime#34001] opened 2020-03-24 04:54 UTC
core version 3.1.102
```
 public class TestDict
    {
        public Dictionary<string, string> Test = new Dictionary<string, string>(){
            { "09:00", "In"},
            { "18:00", "Out"}
        };
    }

 var option = new JsonSerializerOptions();
            option.WriteIndented = true;
            string configJson = System.Text.Json.JsonSerializer.Serialize(new TestDict(), option);
```

the configJson  return `{}`, 
But it can be serialized if just use Dictionary<string, string> directly.

**Comment by vcsjones** [comment] 2020-03-24 13:19
This is because `Test` is a field and fields are not currently supported by `JsonSerializer`. If you change `Test` to a property, then it should work as expected:

```csharp
using System;
using System.Collections.Generic;
using System.Text.Json;

public class Program {
    public class TestDict {
        public Dictionary<string, string> Test { get; set; } = new Dictionary<string, string>(){
            { "09:00", "In"},
            { "18:00", "Out"}
        };
    }

    static void Main() {
        var option = new JsonSerializerOptions();
        option.WriteIndented = true;
        string configJson = JsonSerializer.Serialize(new TestDict(), option);
        Console.WriteLine(configJson);
    }
}
```

The request to support fields is being tracked in #876.

**Comment by layomia** [comment] 2020-03-25 00:42
Closing as duplicate of https://github.com/dotnet/runtime/issues/876.

**Closed by layomia** 2020-03-25 00:42 UTC
Labels: area-System.Text.Json
