### ISSUE TITLE
DataTable of. Net 5 cannot be visualized

### ISSUE THREAD

**Issue by geekworm** [dotnet/runtime#46340] opened 2020-12-17 06:43 UTC
I built a new one ASP.NET Core Web API  project, a DataTable is code in the default interface, but there is no data in the visual interface, as shown in the following figure:
`
DataTable dttest = new DataTable();
dttest.Columns.Add("name");
dttest.Columns.Add("anum"); 
dttest.Columns.Add("bnum"); 
dttest.Columns.Add("hgpre");
dttest.Columns.Add("avg"); 

dttest.Rows.Add(new object[] { "Able", 152, 152, 100.00, 95.25 });
dttest.Rows.Add(new object[] { "Ber", 1, 1, 100.00, 95.00 });
dttest.Rows.Add(new object[] { "Cder", 427, 424, 99.30, 95.50 });
dttest.Rows.Add(new object[] { "Dio", 313, 307, 98.08, 95.48 });
dttest.Rows.Add(new object[] { "Eili", 435, 417, 95.86, 95.37 });
dttest.Rows.Add(new object[] { "Fri", 147, 140, 95.24, 95.34 });
dttest.Rows.Add(new object[] { "Goe", 267, 254, 95.13, 95.03 });
dttest.Rows.Add(new object[] { "Hele", 161, 153, 95.03, 94.97 });
dttest.Rows.Add(new object[] { "J", 313, 297, 94.89, 95.44 });
dttest.Rows.Add(new object[] { "K", 480, 455, 94.79, 95.37 });
dttest.Rows.Add(new object[] { "L", 144, 134, 93.06, 95.37 });
`

![1](https://user-images.githubusercontent.com/12904579/102452860-10605780-4076-11eb-91f0-5ad17912a20e.jpg)
![2](https://user-images.githubusercontent.com/12904579/102452864-135b4800-4076-11eb-92ce-9b2abf8e0ef6.jpg)

I hope this function works！
Thinks.

**Comment by jieny** [comment] 2021-07-05 01:50
any update?

**Comment by ajcvickers** [comment] 2021-07-13 15:27
I am not able to reproduce this. Please attach a project that reproduces what you are seeing so that we can investigate further.

![image](https://user-images.githubusercontent.com/1430078/125480028-eff31e9a-a4d9-4b90-a776-5ac256689a9c.png)

**Comment by jieny** [comment] 2021-08-01 04:58
vs 16.10.4 is ok now.

**Comment by roji** [comment] 2021-08-01 08:57
Am closing as there's an indication that the issue no longer occurs. If someone runs into this again, please post back here and we can revisit.

**Closed by roji** 2021-08-01 08:57 UTC
Labels: area-System.Data
