### ISSUE TITLE
.NET Core 3.1 - FileInfo not giving any value corresponding to Change timestamp in Linux

### ISSUE THREAD

**Issue by rajeevcoding** [dotnet/runtime#43994] opened 2020-09-03 07:37 UTC
.NET Core 3.1 - FileInfo not giving any value corresponding to Change timestamp in Linux

I am getting files copied to Linux system by an external job. My .NET Core Worker service then picks those files and process it. What I want is to have an offset of 2 minutes before accessing any files after it is copied. This is to ensure, the file is copied completely before I start reading it. On Windows, I can access the Copy time by accessing Last Access time. See below - 

CreationTime - 9/3/2020 12:45:35 PM
CreationTimeUtc - 9/3/2020 7:15:35 AM
**LastAccessTime - 9/3/2020 12:45:35 PM
LastAccessTimeUtc - 9/3/2020 7:15:35 AM**
LastWriteTime - 7/20/2020 8:47:21 AM
LastWriteTimeUtc - 7/20/2020 3:17:21 AM

The Problem is, the same logic does not work in Linux system (CentOS 7). The .NET Core program output this -

CreationTime - 7/20/2020 3:17:21 AM
CreationTimeUtc - 7/20/2020 3:17:21 AM
LastAccessTime - 7/20/2020 3:17:21 AM
LastAccessTimeUtc - 7/20/2020 3:17:21 AM
LastWriteTime - 7/20/2020 3:17:21 AM
LastWriteTimeUtc - 7/20/2020 3:17:21 AM

Please note, all of the times are same. In fact, it is always giving time in UTC.

The stats of file there shows (stat <filename>)-

Access: 2020-07-20 03:17:21.000000000 +0000
Modify: 2020-07-20 03:17:21.000000000 +0000
**Change: 2020-09-03 07:22:23.565590525 +0000**

LastAccessTime in this is not working for me. My question is - how can I access this Change timestamp in .NET Core.

Please let me know if you need any additional detail. 

PS - This is my first post raising an issue. If I am not following the correct process, please guide me to get things corrected.

**Comment by Jozkee** [comment] 2020-10-30 22:09
Duplicate of https://github.com/dotnet/runtime/issues/42372

**Closed by Jozkee** 2020-10-30 22:09 UTC
Labels: area-System.IO, untriaged
