### ISSUE TITLE
Test failure JIT\\Methodical\\Invoke\\fptr\\ftn_t_il_r\\ftn_t_il_r.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#66183] opened 2022-03-04 08:06 UTC
Run:  [runtime-coreclr outerloop 20220303.5](https://dev.azure.com/dnceng/public/_build/results?buildId=1644284&view=ms.vss-test-web.build-test-results-tab&runId=45451178&resultId=104155&paneView=debug)

Failed test:
```
R2R-CG2 windows arm Checked @ Windows.10.Arm64v8.Open

- JIT\\Methodical\\Invoke\\fptr\\ftn_t_il_r\\ftn_t_il_r.cmd

```
**Error message:**
```
Could Not Find D:\h\w\AAC6092A\w\B69C09CB\e\JIT\Methodical\Invoke\fptr\ftn_t_il_r\IL-CG2\composite-r2r.dll
Could Not Find D:\h\w\AAC6092A\w\B69C09CB\e\JIT\Methodical\Invoke\fptr\ftn_t_il_r\ftn_t_il_r.dll.rsp
Fatal error. Internal CLR error. (0x80131506)
at System.SZArrayHelper.GetEnumerator[[Internal.JitInterface.CorJitFlag, ILCompiler.ReadyToRun, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null]](https://dev.azure.com/dnceng/public/_build/results?buildId=1644284&view=ms.vss-test-web.build-test-results-tab&runId=45451178&resultId=104155&paneView=debug)
at Internal.JitInterface.CorInfoImpl.getJitFlags(Internal.JitInterface.CORJIT_FLAGS ByRef, UInt32)
at Internal.JitInterface.CorInfoImpl._getJitFlags(IntPtr, IntPtr*, Internal.JitInterface.CORJIT_FLAGS*, UInt32)
at Internal.JitInterface.CorInfoImpl.JitCompileMethod(IntPtr ByRef, IntPtr, IntPtr, IntPtr, Internal.JitInterface.CORINFO_METHOD_INFO ByRef, UInt32, IntPtr ByRef, UInt32 ByRef)
at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(ILCompiler.DependencyAnalysis.IMethodNode, Internal.IL.MethodIL)
at Internal.JitInterface.CorInfoImpl.CompileMethod(ILCompiler.DependencyAnalysis.ReadyToRun.MethodWithGCInfo, ILCompiler.Logger)
at ILCompiler.ReadyToRunCodegenCompilation.<ComputeDependencyNodeDependencies>b__35_0(ILCompiler.DependencyAnalysisFramework.DependencyNodeCore1<ILCompiler.DependencyAnalysis.NodeFactory>) at System.Threading.Tasks.Parallel+<>c__DisplayClass33_02[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForEachWorker>b__0(Int32)
at System.Threading.Tasks.Parallel+<>c__DisplayClass19_0`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef, Int32, Boolean ByRef)
at System.Threading.Tasks.TaskReplicator+Replica.Execute()
at System.Threading.Tasks.TaskReplicator+Replica+<>c.<.ctor>b__4_0(System.Object)
at System.Threading.Tasks.Task.InnerInvoke()
at System.Threading.Tasks.Task+<>c.<.cctor>b__271_0(System.Object)
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
at System.Threading.Thread.StartCallback()

Return code:      1
Raw output file:      D:\h\w\AAC6092A\w\B69C09CB\uploads\Reports\JIT.Methodical\Invoke\fptr\ftn_t_il_r\ftn_t_il_r.output.txt
Raw output:
BEGIN EXECUTION
ftn_t_il_r.dll
TestLibrary.dll
2 file(s) copied.
Response file: D:\h\w\AAC6092A\w\B69C09CB\e\JIT\Methodical\Invoke\fptr\ftn_t_il_r\ftn_t_il_r.dll.rsp
D:\h\w\AAC6092A\w\B69C09CB\e\JIT\Methodical\Invoke\fptr\ftn_t_il_r\IL-CG2\ftn_t_il_r.dll
-o:D:\h\w\AAC6092A\w\B69C09CB\e\JIT\Methodical\Invoke\fptr\ftn_t_il_r\ftn_t_il_r.dll
--targetarch:arm
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\AAC6092A\p\System..dll
-r:D:\h\w\AAC6092A\p\Microsoft..dll
-r:D:\h\w\AAC6092A\p\mscorlib.dll
-r:D:\h\w\AAC6092A\p\netstandard.dll
-O
" "dotnet" "D:\h\w\AAC6092A\p\crossgen2\crossgen2.dll" @"D:\h\w\AAC6092A\w\B69C09CB\e\JIT\Methodical\Invoke\fptr\ftn_t_il_r\ftn_t_il_r.dll.rsp"   -r:D:\h\w\AAC6092A\w\B69C09CB\e\JIT\Methodical\Invoke\fptr\ftn_t_il_r\IL-CG2*.dll"
Crossgen2 failed with exitcode - -1073741819
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\AAC6092A\p
D:\h\w\AAC6092A\w\B69C09CB\e\JIT\Methodical\Invoke\fptr\ftn_t_il_r\ftn_t_il_r.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_Methodical._Invoke_fptr_ftn_t_il_r_ftn_t_il_r_._Invoke_fptr_ftn_t_il_r_ftn_t_il_r_cmd()
```

**Comment by trylek** [comment] 2022-04-04 20:26
This is possibly a dupe of https://github.com/dotnet/runtime/issues/65646 but I'm not closing this one just yet as it has a different manifestation - internal CLR crash instead of assembly load failure.

**Comment by trylek** [comment] 2022-07-06 17:54
@mangod9 - I believe so; in <code>issues.targets</code> the test is only disabled on mono and we haven't seen any recent reproes of the failure in the outerloop pipeline that is quite closely monitored these days, closing as no repro.

**Closed by trylek** 2022-07-06 17:54 UTC
Labels: arch-arm32, os-windows, area-crossgen2-coreclr, untriaged, blocking-outerloop
