### ISSUE TITLE
[.NetCore 3.x] dnspy app Single app exception "The decompiler extension wasn't built. Make sure you build every project before you press F5."

### ISSUE THREAD

**Issue by jiangzeng01** [dotnet/runtime#42792] opened 2020-09-27 09:39 UTC
**Application Name:** dnspy
**OS:** Windows 10 RS5
**CPU:** X64
**.NET Build Number:** 5.0.100-rc.2.20471.7
**App Source:** \\\appcompatsrv\Appcompat\DotNetCore\AppSource\SingleFileP0AppsTarget5\AppSources\dnSpy
**App location:** \\\appcompatsrv\Appcompat\DotNetCore\AppSource\SingleFileP0AppsTarget5\Apps\dnSpy-SingleFile
**DevDiv bug:** [https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1220456](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1220456)

**Repro steps:**
Build & publish default target 3.1 app
Run the "build-SingleFile.ps1" file to build and publish this app
Copy '\\appcompatsrv\Appcompat\DotNetCore\AppSource\SingleFileP0AppsTarget5\Apps\dnSpy-SingleFile' to local machine.
Double-click "dnSpy.exe"

**Expected Result:**
dnSpy app should load assembly information successful.

**Actual Result:**
Get exception when dnSpy loading assembly information.

**Findings :**
The FDD app and Self-Contained app works fine.
We tried .NET Core SDK 3.1, the same error.
After launch the single file app, we check the %userprofile%\AppData\Local\Temp\.net\dnSpy folder, and compare with Self-contained app folder, we found found below assemblies are missing for Singlefile 3.1 app temp folder:
```
dnSpy.Analyzer.x.dll
dnSpy.AsmEditor.x.dll
dnSpy.BamlDecompiler.x.dll
dnSpy.Contracts.Debugger.DotNet.CorDebug.dll
dnSpy.Contracts.Debugger.DotNet.Mono.dll
dnSpy.Debugger.DotNet.CorDebug.x.dll
dnSpy.Debugger.DotNet.Interpreter.dll
dnSpy.Debugger.DotNet.Mono.x.dll
dnSpy.Debugger.DotNet.x.dll
dnSpy.Debugger.x.dll
dnSpy.Decompiler.ILSpy.Core.dll
dnSpy.Decompiler.ILSpy.x.dll
dnSpy.Scripting.Roslyn.x.dll
```

In addition, we checked the source code of dnSpy, we found some of above assemblies are loaded with Assembly.Load() function. 
For example:
![Assembly Load](https://user-images.githubusercontent.com/49379637/94361569-d1aaa900-00e7-11eb-8d7f-ecdb22e5336a.png)

@dotnet-actwx-bot

**Comment by jiangzeng01** [comment] 2020-09-27 09:39
We are not sure about if "assembly.load" will work in .NET Core 3.1 or not.
Please help to check.

**Comment by vitek-karas** [comment] 2020-09-28 14:08
`Assembly.Load` will work fine in Single-File - the problem is those missing files - we need to figure out what made SDK to NOT include them.

**Comment by agocke** [comment] 2020-09-28 18:17
As it is, I don't see an actual product bug here, but we could assist with MSBuild debugging. I agree that it looks like the SDK is not including those files, but I don't see evidence that the default tasks/targets are to blame.

**Comment by vitek-karas** [comment] 2021-07-14 20:53
Closing as there's not enough information here to make progress. Please feel free to reopen the issue if there still an issue around this with additional info available.

**Closed by vitek-karas** 2021-07-14 20:53 UTC
Labels: area-Single-File, customer assistance
