### ISSUE TITLE
Add WebSocketOptions.Timeout to ClientWebSocket

### ISSUE THREAD

**Issue by bjornen77** [dotnet/runtime#48729] opened 2021-02-24 23:06 UTC
*Edited by* @CarnaViire

### Justification

This API allows the users to identify and close idle WebSocket connections without having to rely on the TCP KeepAlive timeout, which can be way too big (e.g. ~15 min on Linux), and can be impossible or very hard to configure.

// *see the original issue in the end of the post*

### API Proposal

```c#
namespace System.Net.WebSockets;

// used to create a base WebSocket (ManagedWebSocket) instance
public class WebSocketCreationOptions
{
    // existing
    //public TimeSpan KeepAliveInterval { get; set; } // default: infinite (off)

    // new
    public TimeSpan KeepAliveTimeout { get; set; } = Timeout.InfiniteTimeSpan;

    // ...
}

// used to configure a ClientWebSocket instance
public class ClientWebSocketOptions
{
    // existing
    //[UnsupportedOSPlatform("browser")]
    //public TimeSpan KeepAliveInterval { get; set; } // default: 30s

    // new
    [UnsupportedOSPlatform("browser")]
    public TimeSpan KeepAliveTimeout { get; set; } = Timeout.InfiniteTimeSpan;

    // ...
}
```

### Usage

For ClientWebSocket:
```c#
var ws = new ClientWebSocket();
ws.Options.KeepAliveTimeout = TimeSpan.FromSeconds(10);
await ws.ConnectAsync(uri, cts.Token);
```

For ManagedWebSocket:
```c#
var options = new WebSocketCreationOptions()
{
    KeepAliveInterval = WebSocket.DefaultKeepAliveInterval,
    KeepAliveTimeout = TimeSpan.FromSeconds(10)
};
var ws = WebSocket.CreateFromStream(stream, options);
```

### Notes on behavior

`Timeout.InfiniteTimeSpan` or `TimeSpan.Zero` would disable the timeout logic and fall back to the existing "unsolicited" `Pong` keep-alive (per understanding in https://github.com/dotnet/runtime/issues/35473#issuecomment-620726903 we cannot send `Ping`s without waiting for the reply)

Any other positive timeout value would turn on `Ping-Pong` logic; we will be sending `Ping`s instead of `Pong`s and track whether we've received `Pong`s in time; if not, the connection is treated as stale and aborted. The behavior and implementation should be similar to HTTP/2 `KeepAlivePingTimeout`.

### Alternative Naming

We could name the new property KeepAlive*Ping*Timeout. This will "break" it's similarity to KeepAliveInterval, but it might help highlight that `Ping`s, not `Pong`s, are being sent (if we care enough about this distinction).

```c#
namespace System.Net.WebSockets;

public class WebSocketCreationOptions
{
    //public TimeSpan KeepAliveInterval { get; set; } // existing
    public TimeSpan KeepAlivePingTimeout { get; set; } // new

    // ...
}

public class ClientWebSocketOptions
{
    //public TimeSpan KeepAliveInterval { get; set; } // existing
    public TimeSpan KeepAlivePingTimeout { get; set; } // new

    // ...
}
```

### Existing API shape for other keep-alives

For comparison:

```c#
// HTTP/2 in runtime:
namespace System.Net.Http;
public class SocketsHttpHandler
{
    public TimeSpan KeepAlivePingDelay { get; set; } // default: infinite (off)
    public TimeSpan KeepAlivePingTimeout { get; set; } // default: 20s (N/A when delay=inf)
    public HttpKeepAlivePingPolicy KeepAlivePingPolicy { get; set; } // default: Always
    // ...
}

// HTTP/2 in Kestrel:
namespace Microsoft.AspNetCore.Server.Kestrel.Core;
public class Http2Limits
{
    public TimeSpan KeepAlivePingDelay { get; set; } // default: infinite (off)
    public TimeSpan KeepAlivePingTimeout { get; set; } // default: 20s (N/A when delay=inf)
    // ...
}

// Sockets in runtime:
namespace System.Net.Sockets;
public enum SocketOptionName
{
    TcpKeepAliveInterval, // between probe retries, if no answer received
    TcpKeepAliveRetryCount, // probe retries before deemed idle, if no answer received
    TcpKeepAliveTime, // before the first probe, after the last received byte
    // ...
}
```

-----

*Original issue by* @bjornen77

I think that adding a WebSocketOptions.Timeout property would be a good thing. 

Today, the ClientWebSocket is closed when the TCP Retransmission times out(if the connection to the server drops for some reason). This timeout seems to be different on Windows and Linux. By default, on Windows it takes about 21 seconds and on Linux it takes about 15 minutes before the WebSocket is closed. It would be good if we could have a separate Timeout setting, so that we get the same behavior regardless of the platform.  And also that this could be configured by the application without having to modify the TCP Timeout settings in the OS... The websocket should still be disconnected if the OS TCP Timeout is reached.

The ClientWebSocket today only sends "Pong" to the server, and therefore it does not wait for a "Pong" response to arrive. I think that the ClientWebSocket shall send a "Ping" instead, and then verify that a "Pong" is received within the Timeout set.  If not received, the connection shall be closed. Or at least it should expose the "received "Pong" message in the WebSocketReceiveResult.MessageType. It would be good if an received "Ping" message from a server is also exposed. Then the application could use these Ping/Pong message types to implement its own timeout logic.

**Comment by bjornen77** [comment] 2021-02-24 23:08
Related: https://github.com/dotnet/aspnetcore/issues/24614

**Comment by ManickaP** [comment] 2021-02-25 12:32
This is a duplicate of: https://github.com/dotnet/runtime/issues/35473
We expose [`KeepAliveInterval`](https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.clientwebsocketoptions.keepaliveinterval?view=net-5.0) but we use it only for sending Pongs to keep the connection open:
https://github.com/dotnet/runtime/blob/b121bcacec60f10b316b25eb9d0b7113599bc508/src/libraries/System.Net.WebSockets/src/System/Net/WebSockets/ManagedWebSocket.cs#L576-L579

We might revisit the original decision to not to send Pings.

**Comment by bjornen77** [comment] 2021-02-25 13:15
I think it should be revisited. With today's implementation you rely on the OS TCP/IP timeout setting to be able to determine when the WebSocket has been disconnected. It is not always wanted to change this setting in the OS as it effect all applications running there.

Also. this OS setting differs by default between Windows and Linux. By default on Linux it takes about 15 minutes before the client realizes that the server is not there anymore. I think that it would be good to be able to set a timeout value on the ClientWebSocket itself(and use the PING/PONG frames internally for this purpose).

**Comment by ManickaP** [comment] 2021-02-25 17:23
Triage: we are open to adding proper ping/pong sending. At the moment, there's only this one issue asking for it so we'll leave it to future.

**Comment by bjornen77** [comment] 2021-02-25 19:06
If adding a new Timeout setting/property maybe the following would be something to consider when implementing:

- Timeout value is set to <=0, the old behavior is used, where only PONGs are sent. 
- Timeout value is set to > 0, the new PING/PONG sequence, with timeout detection is used.

**Comment by gdalsnes** [comment] 2021-02-26 12:28
> Triage: we are open to adding proper ping/pong sending. At the moment, there's only this one issue asking for it so we'll leave it to future.

Not so. Issue #24614 is already asking for the same (and duplicate #26117)

**Comment by aroman** [comment] 2021-06-24 16:20
Strong +1 for this issue. This is an important feature for applications like games where detecting a broken connection quickly is important for user experience. The WebSocket API does not expose the ability to send ping or pong messages, so there isn't even really a way to add this functionality in our applications without creating our own works-like ping/pong messages (which aren't really ping/pong messages but regular websocket messages). 

Just one point of clarification in the original issue — OP mentions that the current implementation only sends pong, rather than ping. I don't think that's true, from what I can see in [ManagedWebSocket:518](https://github.com/dotnet/runtime/blob/7cbf0a7011813cb84c6c858ef19acb770daa777e/src/libraries/Common/src/System/Net/WebSockets/ManagedWebSocket.cs#L518). I think the issue is simply that the implementation doesn't wait for a pong in response to the ping. 

The WebSocket RFC [does not explicitly specify](https://datatracker.ietf.org/doc/html/rfc6455#section-5.5.2) that clients should disconnect in the case a pong is not received in response to a ping within a certain timeframe. I think this would be a good thing to do though, as a user-configurable option. It should probably be default-off, so the change doesn't impact any applications which are somehow depending on very long retry times. Just adding an extra `WebSocketOptions` for this as OP suggests is the right approach IMHO.

**Comment by karelz** [comment] 2021-11-01 14:31
@gdalsnes @aroman can you please upvote top post? That will help us track number of people who need this behavior. Thanks!

**Comment by gdalsnes** [comment] 2021-11-01 15:59
I guess SignalR uses its own pingpong, and is covering over for this flaw for most use cases? But I use it with vs-streamjsonrpc and ended up implementing my own pingpong, and used 99.9% time on that and the rest on actual work... My testing involved killing processes, pulling network cables, supending/resuming/killing VM's, "pulling" network "cables" within VM's etc. I easily got into situations with infinite hang (waited over night).

**Comment by CarnaViire** [comment] 2021-11-01 20:07
I've updated the top comment with the API proposal

**Comment by gdalsnes** [comment] 2021-11-01 20:38
> I've updated the root description with the API proposal

But will this cover aspnetcore websocket as well? It should also have the same timeout option, else it can hang forever and stall request pipelines (potentional DOS problem?)

**Comment by karelz** [comment] 2021-11-01 20:45
@gdalsnes what do you mean by "aspnetcore WebSocket"?
ASP.NET WebSocket is based on our implementation to our best knowledge. Unless there is some wrapper around our APIs, all should be good. We do not restrict what frameworks/apps above us do.

**Comment by CarnaViire** [comment] 2021-11-01 20:47
@gdalsnes good point. This will need an additional API from ASP.NET Core side as well. I suspect it should be added to `ExtendedWebSocketAcceptContext` the way WebSocket compression was added... @BrennanConroy will you be able to help with ASP.NET Core side please?

**Comment by BrennanConroy** [comment] 2021-11-01 20:52
`WebSocketAcceptContext` would likely need a new property, something like `KeepAliveTimeout`. I can help out if this feature gets added.

**Comment by michaldobrodenka** [comment] 2023-05-16 18:54
We need to ping from client and server every few seconds to make sure connection is still alive and restart asap if needed. Since this is not possible with official ClientWebSocket, I use modified websocket-sharp for now

**Comment by Madguy93** [comment] 2024-01-11 20:05
I would also like to see this implemented. Our setup is running a websoket server with lots of embedded devices as clients. We run a standardized protocol based on websocket and therefore cannot implement our own ping mechanism or use signalR. It's important since if you run linux for your servers it will take about 15 min for it to detect a disconnect as the default TCP RTO setting in linux.

**Comment by CarnaViire** [comment] 2024-01-15 16:29
Triage: given that the customer ask is high, and it should be relatively easy to implement, optimistically putting it to 9.0.

**Comment by CarnaViire** [comment] 2024-01-18 17:37
@pavelsavara do you know whether _browser_ websocket supports sending keep-alives (ping/pong frames)?

**Comment by pavelsavara** [comment] 2024-01-18 17:58
There is no flag on the [browser API](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/WebSocket) for controlling it AFAIK. 

There are notes on how to implement ping/pong in the server in the [FF docs](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers#pings_and_pongs_the_heartbeat_of_websockets), which suggests that the browser itself may implement it.

But I don't know, I never tested it and never looked at it with wireshark. We should test that, so that our server doesn't break the browser as a client.

**Comment by CarnaViire** [comment] 2024-01-18 18:08
Thanks @pavelsavara! So, I guess, from the API perspective, we keep `UnsupportedOSPlatform("browser")` attribute on both the existing `ClientWebSocketOptions.KeepAliveInterval` and the new `ClientWebSocketOptions.KeepAliveTimeout` properties, correct?

And when implementing the respective API on Kestrel side, we would need to either add a test (if that's possible in the infra) of Kestrel talking to a browser WS client, or at least verify it manually? cc @BrennanConroy

**Comment by BrennanConroy** [comment] 2024-01-18 21:02
We'll likely have to manually test with the browser. These kinds of tests aren't great to add to automation since they by design would need to last 20+ seconds due to no APIs in the browser that let us influence the keep alive timeout.

Assuming we add good enough unit tests the one-off manual test should be fine.

**Comment by mar1u50** [comment] 2024-02-28 12:43
It's unfortunate that we can't implement this effectively because ManagedWebSocket.SendFrameAsync is private, preventing us from sending the PING frames ourselves in the application. Additionally, ClientWebSocket.ReceiveAsync doesn't allow the reception of PONG frames in the application.

**Comment by CarnaViire** [comment] 2024-02-28 16:13
@mar1u50 is there a reason you would still need this access on the application level, after the proposed API gets implemented?

**Comment by mar1u50** [comment] 2024-02-28 16:34
I think the only missing part (or maybe I missed this from the API change description) is a sequence number sent in the PING to be able to pair it with the PONG.
We may want to disconnect also if the PING-PONG took too long time.

**Comment by CarnaViire** [comment] 2024-02-28 16:56
The proposed `WebSocketCreationOptions.KeepAliveTimeout` is exactly the "too long time" you mention -- that will be tracked and applied from within the WebSocket, so it will get disconnected automatically in case of the response timing out. The pairing process will also become just a part of the internal implementation. You still won't be able to send any _arbitrary_ data in the PING frame, but given that its main purpose is for pairing with PONGs, I am not sure that the exact values should matter on the application level.

**Comment by mar1u50** [comment] 2024-03-01 13:49
In systems where there may be other machines between the client and server, such as a CloudFlare node, it is possible that if the client-CloudFlare connection dies, the CloudFlare-server connection will not also die. Likewise, it is possible for the CloudFlare-server connection to die while the client-CloudFlare connection remains active. To prevent either end from remaining in a zombie state, I was thinking that the server could also check if pings are still coming and force a close if they are not. For this, the server should be able to detect if the ping is the one requested by the client (through its payload). It is true that this could be implemented in another way too: the client initiates pings and waits for pongs, and at the same time, the server also initiates pings and waits for pongs.

**Comment by CarnaViire** [comment] 2024-03-01 14:26
> It is true that this could be implemented in another way too: the client initiates pings and waits for pongs, and at the same time, the server also initiates pings and waits for pongs.

Yes, I believe this would be the expected approach by RFC. If the server is on Kestrel, the timeout APIs will be introduced as a follow-up to this one (see https://github.com/dotnet/runtime/issues/48729#issuecomment-956579982), within the same release.

**Comment by BrennanConroy** [comment] 2024-03-01 17:32
I've been using this as the tracking issue, until there is something to do on the Kestrel side.

**Comment by bartonjs** [comment] 2024-03-05 20:07
Looks good as proposed.

```c#
namespace System.Net.WebSockets;

public partial class WebSocketCreationOptions
{
    public TimeSpan KeepAliveTimeout { get; set; } = Timeout.InfiniteTimeSpan;
}

public partial class ClientWebSocketOptions
{
    [UnsupportedOSPlatform("browser")]
    public TimeSpan KeepAliveTimeout { get; set; } = Timeout.InfiniteTimeSpan;
}
```

**Comment by ken-goldstein-igt** [comment] 2024-05-02 00:15
The proposal is exactly what's needed for my company's servers. With .NET 5-8, the replacement of the unidirectional Ping with a unidirectional Pong broke tens of thousands of clients that didn't have a 3rd party implementation that could understand Pong frames as a heartbeat. The result was chaos, with disconnections about every minute or so.

**Comment by Madguy93** [comment] 2024-05-06 18:03
Will this be ready for dotnet 9?

**Comment by CarnaViire** [comment] 2024-05-07 08:59
@Madguy93 it is currently planned for .NET 9, yes.

**Comment by osexpert** [comment] 2024-05-24 09:33
I wonder... Maybe you could also add two new DateTimes, so we can better get a view of what is happening internally in the WS?
```

DateTime? DataLastTransmittedUtc
DateTime? DataLastRecievedUtc
```

These would be updated whenever data (including ping\pong) is transmitted\recieved.

**Comment by chrsin** [comment] 2024-06-26 10:43
@CarnaViire any estimate on which preview it would make? (I won't hold you to it)

Right now our options seem to be as follows and would like to make an informed decision.
1. start Development with a preview version of dotnet 9 (unless its far out in the future)
2. Use something else than AspNet for handling the Websocket part of our application.
3. Use custom messages to track when the connection is lost

**Comment by CarnaViire** [comment] 2024-07-09 10:12
> any estimate on which preview it would make?

Most possibly Preview 7, scheduled for the middle of August @chrsin

**Comment by CarnaViire** [comment] 2024-07-09 10:39
> I wonder... Maybe you could also add two new DateTimes, so we can better get a view of what is happening internally in the WS?
> 
> ```
> 
> DateTime? DataLastTransmittedUtc
> DateTime? DataLastRecievedUtc
> ```
> 
> These would be updated whenever data (including ping\pong) is transmitted\recieved.

@osexpert these timestamps, or rather, the difference between `UtcNow` and these timestamps, will always be less or equal to `KeepAliveInterval + KeepAliveTimeout`. And you will need to go and regularly check these values manually, let's say in a loop with some interval, e.g. `KeepAliveTimeout/2`.

BUT if you already need go and check the `WebSocket` instance in a regular fashion, and your goal is to notify when the connection is torn down -- instead of the timestamps, you can just check the [`WebSocket.State`](https://learn.microsoft.com/en-us/dotnet/api/system.net.websockets.websocket.state?view=net-8.0) property, and raise the notification when it becomes [Aborted](https://learn.microsoft.com/en-us/dotnet/api/system.net.websockets.websocketstate?view=net-8.0) (or Closed, or CloseReceived, etc) 

It seems redundant to check the timestamps, "do the math" (and manual comparison with a timeout) to deduce the state, when the state would be _already_ computed and available in `Websocket.State`.

**Comment by CarnaViire** [comment] 2024-07-23 19:45
> > any estimate on which preview it would make?
> 
> Most possibly Preview 7, scheduled for the middle of August @chrsin

Update: this didn't make it in time for Preview 7; it is now targeting RC1 instead (September)

**Closed** 2024-08-09 07:02 UTC
Labels: api-approved, area-System.Net, in-pr
