### ISSUE TITLE
[API Proposal]: Utf8.IsValid(...)

### ISSUE THREAD

**Issue by neon-sunset** [dotnet/runtime#86937] opened 2023-05-31 07:59 UTC
### Background and motivation

`Ascii.IsValid` methods are very useful.
Expecting to find similar methods on the `Utf8` class, there appear to be none. It would be great if .NET 8 sees an addition of a method to simplify the validation of user-supplied `ReadOnlySpan<byte>` to ensure the input is not malformed and invalid utf8 data is not propagated throughout the application state.

### API Proposal

```csharp
namespace System.Text.Unicode;

public static class Utf8
{
    public static bool IsValid(ReadOnlySpan<byte> value);
}
```

### API Usage

```csharp
var input = // get user input
var validated = new U8String(input);

readonly struct U8String
{
   ...
   public U8String(ReadOnlySpan<bytes> source)
   {
      if (!Utf8.IsValid(source))
      {
         ThrowHelpers.ArgumentException(nameof(source));
      }
   }
   ...
}
```

### Alternative Designs

N/A

### Risks

N/A

**Comment by jeffhandley** [comment] 2023-06-06 22:24
This is a duplicate of #502, which remains open. I'll add another comment there to bump it up.

**Closed by jeffhandley** 2023-06-06 22:24 UTC
Labels: api-suggestion, area-System.Runtime, untriaged
