### ISSUE TITLE
WASM leg failed in CI - RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#59911] opened 2021-10-03 19:37 UTC
From `Browser wasm Release AllSubsets_Mono_AOT` logs: https://helix.dot.net/api/2019-06-17/jobs/0ec4f1e0-ddf3-45e9-af78-ff1783b9f2a6/workitems/System.Runtime.Serialization.Xml.Tests/console

```
[15:36:33] info: Starting:    System.Runtime.Serialization.Xml.Tests.dll
[15:36:36] fail: console.error: RangeError: Maximum call stack size exceeded
                 
[15:36:36] fail: console.error: RangeError: Maximum call stack size exceeded
                 
[15:36:36] fail:     at RangeError.valueOf (<anonymous>)
                 
[15:36:36] fail:     at invoke_vi (dotnet.js:10302:16)
                 
[15:36:36] fail:     at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[116059]:0x1600ceb)
                 
[15:36:36] fail:     at do_jit_call (<anonymous>:wasm-function[98812]:0x140c666)
                 
[15:36:36] fail:     at interp_exec_method (<anonymous>:wasm-function[98748]:0x13ff70e)
                 
[15:36:36] fail:     at interp_entry (<anonymous>:wasm-function[98794]:0x140bc17)
                 
[15:36:36] fail:     at interp_entry_instance_0 (<anonymous>:wasm-function[98869]:0x140da18)
                 
[15:36:36] fail:     at corlib_aot_wrapper_gsharedvt_in_sig_void_this_ (<anonymous>:wasm-function[46262]:0x9ddb9f)
                 
[15:36:36] fail:     at System_Private_DataContractSerialization_System_Xml_XmlBaseWriter_WriteEndAttribute (<anonymous>:wasm-function[50726]:0xa60df5)
                 
[15:36:36] fail:     at System_Private_DataContractSerialization_System_Xml_XmlDictionaryAsyncCheckWriter_WriteEndAttribute (<anonymous>:wasm-function[50202]:0xa4557f)
                 
[15:36:36] fail:     at System_Private_DataContractSerialization_System_Runtime_Serialization_XmlWriterDelegator_WriteAttributeString_string_System_Xml_XmlDictionaryString_System_Xml_XmlDictionaryString_string (<anonymous>:wasm-function[53276]:0xaf5461)
                 
[15:36:36] fail:     at System_Private_DataContractSerialization_System_Runtime_Serialization_XmlObjectSerializerWriteContext_OnHandleIsReference_System_Runtime_Serialization_XmlWriterDelegator_System_Runtime_Serialization_DataContract_object (<anonymous>:wasm-function[52541]:0xac7d79)
                 
[15:36:36] fail:     at System_Private_DataContractSerialization_System_Runtime_Serialization_XmlObjectSerializerWriteContext_SerializeWithoutXsiType_System_Runtime_Serialization_DataContract_System_Runtime_Serialization_XmlWriterDelegator_object_System_RuntimeTypeHandle (<anonymous>:wasm-function[52539]:0xac76f0)
                 
[15:36:36] fail:     at System_Private_DataContractSerialization_System_Runtime_Serialization_XmlObjectSerializerWriteContext_InternalSerialize_System_Runtime_Serialization_XmlWriterDelegator_object_bool_bool_int_System_RuntimeTypeHandle (<anonymous>:wasm-function[53271]:0xaf442c)
                 
[15:36:36] fail:     at System_Private_DataContractSerialization_System_Runtime_Serialization_XmlObjectSerializerWriteContext_InternalSerializeReference_System_Runtime_Serialization_XmlWriterDelegator_object_bool_bool_int_System_RuntimeTypeHandle (<anonymous>:wasm-function[53270]:0xaf42c4)
                 
[15:36:36] fail:     at System_Private_DataContractSerialization_aot_wrapper_gsharedvt_out_sig_void_this_objobju1u1i4cl1d_Mono_dValueTuple_601_3cint_3e_ (<anonymous>:wasm-function[55810]:0xb7c2d7)
                 
[15:36:36] fail:     at jit_call_cb (<anonymous>:wasm-function[98855]:0x140d615)
                 
[15:36:36] fail:     at invoke_vi (dotnet.js:10299:25)
                 
[15:36:36] fail:     at mono_llvm_cpp_catch_exception (<anonymous>:wasm-function[116059]:0x1600ceb)
                 
[15:36:36] fail:     at do_jit_call (<anonymous>:wasm-function[98812]:0x140c666)
                 
[15:36:36] fail:     at interp_exec_method (<anonymous>:wasm-function[98748]:0x13ff857)
                 
[15:36:36] fail:     at interp_entry (<anonymous>:wasm-function[98794]:0x140bc17)
                 
[15:36:36] fail:     at interp_entry_static_4 (<anonymous>:wasm-function[98891]:0x140e119)
                 
[15:36:36] fail:     at corlib_aot_wrapper_gsharedvt_in_sig_void_objobjobjobj (<anonymous>:wasm-function[48062]:0xa035cf)
                 
[15:36:36] fail:     at System_Private_DataContractSerialization_wrapper_delegate_invoke__Module_invoke_void_XmlWriterDelegator_object_XmlObjectSerializerWriteContext_ClassDataContract_System_Runtime_Serialization_XmlWriterDelegator_object_System_Runtime_Serialization_XmlObjectSerializerWriteContext_System_Runtime_Serialization_ClassDataContract (<anonymous>:wasm-function[55265]:0xb70453)
                 
[15:36:36] fail:     at System_Private_DataContractSerialization_System_Runtime_Serialization_ClassDataContract_WriteXmlValue_System_Runtime_Serialization_XmlWriterDelegator_object_System_Runtime_Serialization_XmlObjectSerializerWriteContext (<anonymous>:wasm-function[51982]:0xaa5816)

... then it repeats the same thing 60+ times ...
```

**Comment by radical** [comment] 2021-10-12 14:22
Dupe of https://github.com/dotnet/runtime/issues/59926 .

**Closed by radical** 2021-10-12 14:22 UTC
Labels: untriaged, area-Infrastructure-mono
