### ISSUE TITLE
[Uri] TryCreate doubles file:/// Uris with certain escaped unreserved characters

### ISSUE THREAD

**Issue by ScottLouvau** [dotnet/runtime#36288] opened 2020-05-12 16:50 UTC
It looks like Uri.TryCreate() handles certain escaped characters incorrectly, doubling the Uri.

For example:
```c#
            string original = "file:///new%2Dhost/share/folder/file.cs";
            bool succeeded = Uri.TryCreate(original, UriKind.Absolute, out Uri result);
            string output = result.AbsoluteUri;
            // Succeeded: true
```
Output: file:///new%2Dhost/share/folder/file.cs/**new-host/share/folder/file.cs**

This reproduces for `file:///` Uris with dash (`%2D`) and underscore (`%5F`), either in the first part of the Uri or later in the path. It does not reproduce for space (`%20`) or parens (`%28`, `%29`). I didn't try every escaping.

**Comment by davidsh** [comment] 2020-05-12 16:51
@MihaZupan

**Comment by MihaZupan** [comment] 2020-05-12 18:46
Duplicate of #1061

**Closed by MihaZupan** 2020-05-12 18:46 UTC
Labels: area-System.Net, bug, untriaged
