### ISSUE TITLE
Websocket callback missing for the Ping/Pong Frames RFC6455 [bug]

### ISSUE THREAD

**Issue by filzek** [dotnet/runtime#100771] opened 2024-04-08 13:36 UTC
I would like to address an issue with the current implementation of WebSockets in .NET, particularly concerning the handling of ping and pong frames as defined by RFC 6455. In the WebSocket protocol, ping and pong frames play a crucial role in maintaining the connection and ensuring its liveliness. Both the client and server can initiate these frames, and they are expected to respond with corresponding pong and ping frames, respectively.

However, in the Microsoft implementation of WebSockets, the handling of these frames is abstracted away from the application layer. Specifically, the WebSocketMessageType enum in the System.Net.WebSockets namespace does not include Ping or Pong types, which are essential for correctly processing these frames. The current implementation automatically responds to ping frames with pong frames but does not expose these interactions to the application. This lack of visibility can lead to issues in correctly managing the WebSocket connection, especially in scenarios where application-level keepalive mechanisms are necessary.

To align more closely with RFC 6455 and provide better control over the WebSocket connection, I propose the following enhancements to the WebSocketMessageType enum:

```c#
namespace System.Net.WebSockets
{
    public enum WebSocketMessageType
    {
        Text = 0,
        Binary = 1,
        Close = 2,
        Ping = 9,
        Pong = 10
    }
}
```

By adding Ping and Pong types to the enum, applications can explicitly handle these frames in the ReceiveAsync method, allowing for more accurate monitoring and control of the connection state:

```c#
result = await socket.ReceiveAsync(new ArraySegment<byte>(buffer), CancellationToken.None);

if (result.MessageType == WebSocketMessageType.Ping)
{
    // Handle ping frame
}

if (result.MessageType == WebSocketMessageType.Pong)
{
    // Handle pong frame
}
```

These changes would enable developers to implement more robust WebSocket servers and clients that adhere to the WebSocket protocol as defined by RFC 6455.

Please advise ASAP when this resource will be update and fixes in the .net websocket class.

**Comment by MihaZupan** [comment] 2024-04-08 14:09
> ... which are essential for correctly processing these frames. ... This lack of visibility can lead to issues in correctly managing the WebSocket connection, especially in scenarios where application-level keepalive mechanisms are necessary.

What do you mean by "correctly" here?

Application-level keepalive mechanisms are generally written on top of WebSockets, treating WS as an arbitrary bi-directional transport.

> By adding Ping and Pong types to the enum, applications can explicitly handle these frames in the ReceiveAsync method, allowing for more accurate monitoring and control of the connection state:
> These changes would enable developers to implement more robust WebSocket servers and clients that adhere to the WebSocket protocol as defined by RFC 6455.

Are you simply looking for information about how long a WebSocket connection has been idle?
What would you like to do with such information?

**Comment by osexpert** [comment] 2024-04-08 21:04
Possible duplicate of https://github.com/dotnet/runtime/issues/48729#issuecomment-1887881397

**Comment by filzek** [comment] 2024-04-09 01:00
> Possible duplicate of #48729

It is not duplicate, its complete different.

**Comment by filzek** [comment] 2024-04-09 01:26
> > ... which are essential for correctly processing these frames. ... This lack of visibility can lead to issues in correctly managing the WebSocket connection, especially in scenarios where application-level keepalive mechanisms are necessary.
> 
> What do you mean by "correctly" here?
> 
> Application-level keepalive mechanisms are generally written on top of WebSockets, treating WS as an arbitrary bi-directional transport.
> 
> > By adding Ping and Pong types to the enum, applications can explicitly handle these frames in the ReceiveAsync method, allowing for more accurate monitoring and control of the connection state:
> > These changes would enable developers to implement more robust WebSocket servers and clients that adhere to the WebSocket protocol as defined by RFC 6455.
> 
> Are you simply looking for information about how long a WebSocket connection has been idle? What would you like to do with such information?

Its quite simple in a multiserver environment with inumerous concurrent connections every resource count, so, all the multiple server consumes a unique redis server and this memory operation need to be update frenquently, so, if the Ping/Pong frame is forward to the ReceiveAsync it can handle and update the socket connection seamless, so, this is why the type shall include the pingpong frame.

**Comment by osexpert** [comment] 2024-04-09 07:04
> > Possible duplicate of #48729
> 
> It is not duplicate, its complete different.

There are comments in there that discuss wanting\needing to expose- or keep the ping\pong logic private, so I would say its not _completely_ different.

**Comment by MihaZupan** [comment] 2024-04-09 11:18
> if the Ping/Pong frame is forward to the ReceiveAsync it can handle and update the socket connection seamless

What do you mean by "handle and update socket connection"?
What are you looking to achieve that you can't with the various knobs on the class?

**Comment by filzek** [comment] 2024-04-09 14:26
> > if the Ping/Pong frame is forward to the ReceiveAsync it can handle and update the socket connection seamless
> 
> What do you mean by "handle and update socket connection"? What are you looking to achieve that you can't with the various knobs on the class?

@MihaZupan quite simple way:

"If the Ping/Pong frame is forwarded to the ReceiveAsync method, it can seamlessly handle and update the socket connection."

In response to the question about handling and updating the socket connection:

"The current method does not provide a straightforward solution to handle Ping/Pong frames. As a result, there is no way to perform any operations upon receiving a Ping or Pong frame. In scenarios where actions are taken based on the data received in a WebSocket connection, it is essential to handle these operations directly within the method. This approach aligns with the principles of Clean Code and the SOLID methodology, promoting simplicity, efficiency, and wise design."

![image](https://github.com/dotnet/runtime/assets/29267027/3eac1d3e-9d64-4a89-a818-d6f73338de66)

A WebSocket server establishes a bidirectional connection with a Redis server. Upon receiving a Ping/Pong frame in the WebSocket, it updates the Redis server to indicate that the client is alive. Multiple servers connect to Redis and check for actions before connecting to the WebSocket server to send messages to the client.

![image](https://github.com/dotnet/runtime/assets/29267027/eee88f80-ee6e-4583-a860-612351b40744)


By updating the client status upon receiving a Ping/Pong frame, you ensure that the status is extremely accurate and reflects the most recent state within a specific timeframe. This approach is both simple and efficient, allowing for real-time monitoring of the client's connection status in a complex or simple scenario.

**Comment by antonfirsov** [comment] 2024-04-09 15:13
Triage: we are hesitant to take this. @CarnaViire any thoughts?

**Comment by filzek** [comment] 2024-04-09 16:23
> Triage: we are hesitant to take this. @CarnaViire any thoughts?

**I'd like to suggest two potential approaches to address this:**

**1. Basic Forwarding Option in Setup:**
Provide an option in the setup to forward the client operation in read-only mode (notify only) for the ReceiveAsync method. This can be achieved by adding parameters to the WebSocketAcceptContext:

```
using var webSocket = await HttpContext.WebSockets.AcceptWebSocketAsync(new WebSocketAcceptContext()
{
    KeepAliveInterval = TimeSpan.FromSeconds(5),
    Forward.Ping = true,
    Forward.Pong = true,
    // Add other WebSocket message types as needed
});

```


**2. Client-Controlled Handling:**
Allow clients to decide whether they want to handle the response to the socket. This approach is more complex but offers greater flexibility. We can introduce a tri-mode action for each content type in the **ContentType** message, with options like **autohandle**, **readonly**, and **clienthandle**. If nothing is set, the system should handle all content types except those already being forwarded.

- **autohandle** (default): The system automatically handles the content.
- **readonly**: The system notifies and sends the content to the client in ReceiveAsync, but no action is required from the user.
- **clienthandle**: The system does not take any action upon receiving this content type; the user must handle it as needed.

```
using var webSocket = await HttpContext.WebSockets.AcceptWebSocketAsync(new WebSocketAcceptContext()
{
    KeepAliveInterval = TimeSpan.FromSeconds(5),
    ContentType = new ContentTypeSettings
    {
        Ping = ContentTypeAction.Readonly,
        // Configure other content types as needed
    }
});

// Process received messages
WebSocketReceiveResult result = await socket.ReceiveAsync(new ArraySegment<byte>(buffer), CancellationToken.None);

if (result.MessageType == WebSocketMessageType.Ping)
{
    // Handle the Ping message as needed
}

```

I believe these approaches provide a balance between simplicity and flexibility, catering to different use cases. Let me know your thoughts!

**Comment by karelz** [comment] 2024-04-15 13:47
@filzek we are confused by your request. Especially with your replies in https://github.com/dotnet/runtime/issues/100771#issuecomment-2045315362 (incl. the second picture and how it is related to this topic at all).
Can you please restate the GOAL (real-world scenarios) and WHY / HOW is it going to help? (if it is about perf, let's talk also numbers)
Please, try to be crisp on the real-world scenario to help us focus the discussion.

**Comment by filzek** [comment] 2024-04-16 02:47
So, for a websocket usage the Ping/Pong frames either recieved or send could help to keep the status for the clients over a multi APIs platforms.

The design thing of solve problems in a simple way could be extremely reduce the work to create callbacks, rewrite websocket layter and controls to a simples option to forward the frames (like proposed) to the basic handle.

GOAL:
Have all the websocket messages forward to the basic handler

WHY:
Handling messages at least in READING mode could help solve a lot of work for multi apis handling.

HOW IT WILL HELP
Simple, when the websocket forward the frames we in a very easy way update and take action based on its own socket protocol.

**Comment by CarnaViire** [comment] 2024-04-22 11:31
Thanks for the reply @filzek. But unfortunately, it didn't bring any clarity over your scenario. Can you please clarify the following:

> could help to keep the status for the clients over a multi APIs platforms.

What status? What clients? What platforms? What APIs? Who is the consumer of the "statuses" and what do they do with it? Please, try to be crisp on the REAL-WORLD scenario to help us focus the discussion.

> GOAL:
> Have all the websocket messages forward to the basic handler

What is a "basic handler"?

I understand that you would like to get your hands on the PING frames. But surely it is not THE goal in itself, is it? It sounds more like a POTENTIAL APPROACH to reach some kind of goal. What is the actual goal? What are you going to do once you get the frames?

> extremely reduce the work to create callbacks, rewrite websocket layter and controls

Why would you need to rewrite a websocket layer?

> could help solve a lot of work for multi apis handling.

What kind of work? What is "a lot"? What exactly do you mean by "multi apis handling" and how is it related?

> very easy way update and take action

Very easy way as compared to what? What and how are you updating? What is the action?

> based on its own socket protocol

What is "it" in this sentence? What is the "socket protocol" and how is it related to the ask?

**Closed** 2024-05-23 18:48 UTC
Labels: api-suggestion, area-System.Net, untriaged, no-recent-activity, needs-author-action

**Comment by filzek** [comment] 2024-05-23 23:17
@CarnaViire

When deploying a service with multiple connections among different APIs and customers, it's important to consider the implementation of a keep-alive layer in addition to the existing WebSocket keep-alive mechanism. However, duplicating this effort is unnecessary and inefficient.

The keep-alive mechanism provided by WebSockets should be sufficient for ensuring that customer X is alive and able to receive data. This mechanism communicates directly with the WebSocket connection handler, removing the need for additional layers.

**Why would you need to rewrite a WebSocket layer?**
Rewriting the WebSocket layer allows us to utilize the keep-alive feature to update the status in Redis or any other memory/SQL table, indicating that the customer or API is active. This integration ensures that the connection status is monitored effectively, enabling real-time updates on whether the customer is able to receive data.

**What kind of work does this involve? What exactly do you mean by "multi-APIs handling," and how is it related?**
Implementing additional services to check if clients are alive involves significant effort and resources. This work is redundant because the WebSocket protocol's keep-alive mechanism already performs this task. Deploying a new service to cycle through WebSocket clients to verify their status requires maintaining additional functions, which is inefficient.

External APIs need to communicate with WebSocket APIs or gateways. For instance, if an API needs to notify an app about changes in processing rules, it must verify if the client is alive. This requires sending a packet to the client, necessitating a service to confirm the client's status. This multi-handling approach is redundant and leads to unnecessary consumption of resources (manpower, data, disk space, CPU usage) without providing any real benefit. Instead, updating the basic response from the ping or pong frames in the WebSocket handler is a simpler solution.

**How does the keep-alive mechanism simplify this process?**
The WebSocket protocol's ping/pong frames are managed by the WebSocket layer. The basic WebSocket handler can forward these frames to the application handler, which can then use the keep-alive signals to update the client's socket status. This method allows for efficient communication without the need for extensive service rewrites. Currently, we've rewritten the entire WebSocket based on the C# WebSocket to control the keep-alive mechanism, but this approach is not optimal. Leveraging the WebSocket protocol's existing keep-alive features and forwarding them to the basic handler enables programmers to utilize this information effectively.

**What is the "keep-alive mechanism" in this context?**
The keep-alive mechanism refers to the ping/pong frames defined in the WebSocket RFC. These frames ensure that the connection remains active and can be used to update the connection status within the application, streamlining the process and reducing unnecessary redundancy.

Is that clear?

**Comment by osexpert** [comment] 2024-05-24 05:49
Maybe this could be solved by exposing two DateTimes?
DateTime DataLastTransmittedUtc
DateTime DataLastRecievedUtc
These would be updated whenever data (including ping\pong) is transmitted\recieved.
