### ISSUE TITLE
CI OSX x64 Could not find a part of the path '.../NuGetScratch/

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#33010] opened 2020-02-29 12:48 UTC
```
azure-pipelines
/ runtime-live-build (Build OSX x64 release Runtime_Debug)

src/libraries/Directory.Build.props#L38
src/libraries/Directory.Build.props(38,3): error : System.AggregateException: One or more errors occurred. (Could not find a part of the path '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/NuGetScratch/ccd9d22adb6549f086362689e42245d6/9c159c0681d8495c9d48c5e0d296844d.proj.nuget.dgspec.json'.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/NuGetScratch/ccd9d22adb6549f086362689e42245d6/9c159c0681d8495c9d48c5e0d296844d.proj.nuget.dgspec.json'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at NuGet.ProjectModel.DependencyGraphSpec.Save(String path)
   at NuGet.Commands.NoOpRestoreUtilities.PersistDGSpecFile(DependencyGraphSpec spec, String dgPath, ILogger log)
   at NuGet.Commands.RestoreCommand.EvaluateCacheFile()
   at NuGet.Commands.RestoreCommand.ExecuteAsync(CancellationToken token)
   at NuGet.Commands.RestoreRunner.ExecuteAsync(RestoreSummaryRequest summaryRequest, CancellationToken token)
   at NuGet.Commands.RestoreRunner.CompleteTaskAsync(List`1 restoreTasks)
   at NuGet.Commands.RestoreRunner.RunWithoutCommit(IEnumerable`1 restoreRequests, RestoreArgs restoreContext)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Build.NuGetSdkResolver.NuGetSdkResolver.NuGetAbstraction.GetSdkResult(SdkReference sdk, Object nuGetVersion, SdkResolverContext context, SdkResultFactory factory)
```
Seen in https://github.com/dotnet/runtime/pull/2004

**Comment by vcsjones** [comment] 2020-02-29 16:17
Dupe of #32764.

**Comment by jkotas** [comment] 2020-03-01 15:41
I have noted the stacktrace in https://github.com/dotnet/runtime/issues/32764 so that it is easy to find.

**Closed by jkotas** 2020-03-01 15:41 UTC
Labels: area-Infrastructure-coreclr, untriaged
