### ISSUE TITLE
Test failure  System.Net.Mail.Tests.LoggingTest.EventSource_EventsRaisedAsExpected

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#85754] opened 2023-05-04 08:41 UTC
**Failed in:** [runtime-coreclr libraries-jitstress 20230503.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=260461&view=ms.vss-test-web.build-test-results-tab&runId=5100514&resultId=169116&paneView=debug)

**Failed tests:**
```
net8.0-windows-Release-x86-CoreCLR_checked-jitstress1-Windows.10.Amd64.Open
    - System.Net.Mail.Tests.LoggingTest.EventSource_EventsRaisedAsExpected
net8.0-windows-Release-x86-CoreCLR_checked-tailcallstress-Windows.10.Amd64.Open
    - System.Net.Mail.Tests.LoggingTest.EventSource_EventsRaisedAsExpected
net8.0-windows-Release-x86-CoreCLR_checked-no_tiered_compilation-Windows.10.Amd64.Open
    - System.Net.Mail.Tests.LoggingTest.EventSource_EventsRaisedAsExpected
net8.0-windows-Release-x64-CoreCLR_checked-tailcallstress-Windows.10.Amd64.Open
    - BasicEventSourceTests.TestsManifestGeneration.Test_EventSource_EtwManifestGenerationRollover
    - System.Net.Mail.Tests.LoggingTest.EventSource_EventsRaisedAsExpected
net8.0-windows-Release-x86-CoreCLR_checked-zapdisable-Windows.10.Amd64.Open
    - System.Net.Mail.Tests.LoggingTest.EventSource_EventsRaisedAsExpected
net8.0-windows-Release-x64-CoreCLR_checked-zapdisable-Windows.10.Amd64.Open
    - System.Net.Mail.Tests.LoggingTest.EventSource_EventsRaisedAsExpected
net8.0-windows-Release-x64-CoreCLR_checked-no_tiered_compilation-Windows.10.Amd64.Open
    - System.Net.Mail.Tests.LoggingTest.EventSource_EventsRaisedAsExpected
net8.0-windows-Release-x64-CoreCLR_checked-jitstress1-Windows.10.Amd64.Open
    - System.Net.Mail.Tests.LoggingTest.EventSource_EventsRaisedAsExpected
net8.0-linux-Release-x64-CoreCLR_checked-jitstress1-Ubuntu.1804.Amd64.Open
    - System.Net.Mail.Tests.LoggingTest.EventSource_EventsRaisedAsExpected
```

**Error message:**
```
 Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
```

**Stack trace:**
```
 
Child exception:
  System.InvalidOperationException: Data stream is still open.
   at System.Net.Mail.SmtpConnection.ShutdownConnection(Boolean isAbort) in /_/src/libraries/System.Net.Mail/src/System/Net/Mail/SmtpConnection.cs:line 147
   at System.Net.Mail.SmtpConnection.ReleaseConnection() in /_/src/libraries/System.Net.Mail/src/System/Net/Mail/SmtpConnection.cs:line 177
   at System.Net.Mail.SmtpTransport.ReleaseConnection() in /_/src/libraries/System.Net.Mail/src/System/Net/Mail/SmtpTransport.cs:line 165
   at System.Net.Mail.SmtpClient.Dispose(Boolean disposing) in /_/src/libraries/System.Net.Mail/src/System/Net/Mail/SmtpClient.cs:line 1015
   at System.Net.Mail.SmtpClient.Dispose() in /_/src/libraries/System.Net.Mail/src/System/Net/Mail/SmtpClient.cs:line 1000
   at System.Net.Mail.Tests.SmtpClientTest.TestMailDelivery() in /_/src/libraries/System.Net.Mail/tests/Functional/SmtpClientTest.cs:line 313
   at System.Net.Mail.Tests.LoggingTest.&lt;&gt;c.&lt;EventSource_EventsRaisedAsExpected&gt;b__1_1() in /_/src/libraries/System.Net.Mail/tests/Functional/LoggingTest.cs:line 38
   at System.Diagnostics.Tracing.TestEventListener.RunWithCallback(Action`1 handler, Action body) in /_/src/libraries/Common/tests/System/Diagnostics/Tracing/TestEventListener.cs:line 111
   at System.Net.Mail.Tests.LoggingTest.&lt;&gt;c.&lt;EventSource_EventsRaisedAsExpected&gt;b__1_0() in /_/src/libraries/System.Net.Mail/tests/Functional/LoggingTest.cs:line 35
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59

Child process:
  System.Net.Mail.Functional.Tests, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Mail.Tests.LoggingTest+&lt;&gt;c Void &lt;EventSource_EventsRaisedAsExpected&gt;b__1_0()


```

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2023-05-03T07:34:51.35Z | runtime-coreclr libraries-jitstress | Release | ubuntu.1804.amd64.open.rt | x64 | System.Net.Mail.Tests.LoggingTest.EventSource_EventsRaisedAsExpected | Failed | {"AzurePipelinesTestRunId":"5100440","DefinitionId":"138","System.JobName":"__default","BuildNumber":"20230503.1","System.JobAttempt":"1","DefinitionName":"runtime-coreclr libraries-jitstress","System.PhaseAttempt":"1","System.StageAttempt":"1","configuration":"Release","scenario":"jitstress1","operatingSystem":"Ubuntu.1804.Amd64.Open","BuildId":"260461","System.PhaseName":"libraries_test_run_checked_coreclr_linux_x64_Release","architecture":"x64","Reason":"Schedule","Project":"public","runtimeFlavor":"coreclr","System.StageName":"Build","System.JobId":"fe27627b-bd13-56b8-97c3-9bb28451d0b9","CollectionUri":"https://dev.azure.com/dnceng-public/"} | Schedule

**Comment by MihaZupan** [comment] 2023-05-22 14:21
I don't see any failures in Kusto since May 3rd. Given the timeline this is likely a duplicate of https://github.com/dotnet/runtime/issues/85752, https://github.com/dotnet/runtime/issues/85753, https://github.com/dotnet/runtime/issues/85637

**Closed by MihaZupan** 2023-05-22 14:21 UTC
Labels: arch-x86, area-System.Net, os-linux, os-windows, JitStress, arch-x64, untriaged
