### ISSUE TITLE
Consider annotating TaskCreationOptions.LongRunning as unsupported on browser

### ISSUE THREAD

**Issue by marek-safar** [dotnet/runtime#44865] opened 2020-11-18 12:10 UTC
I don't have a strong opinion on this but we could consider annotating `TaskCreationOptions.LongRunning` and `TaskContinuationOptions.LongRunning` with `UnsupportedOSPlatform("browser")` attribute as we cannot handle them well.

**Comment by stephentoub** [comment] 2020-11-18 13:45
I think it'd be better to just make them nop. They already have a scheduler-specific meaning, as its the particular TaskScheduler being used that decides what to do if this is specified. I think it's reasonable on a platform that doesn't support new threads to say its just ignored. We've previously talked about supporting Thread.Start by just queuing a work item: if that was done,  this would just naturally fall out.

**Comment by ilonatommy** [comment] 2022-06-13 11:01
Looks like a duplicate of https://github.com/dotnet/runtime/issues/44544. @marek-safar are you fine with closing this one?

**Closed** 2022-08-11 11:49 UTC
Labels: arch-wasm, area-System.Threading.Tasks
