### ISSUE TITLE
System.IO.Ports.SerialPort not working on linux-musl-arm64

### ISSUE THREAD

**Issue by kskog** [dotnet/runtime#63187] opened 2021-12-29 09:13 UTC
We've tried to use SerialPort on linux-musl-arm64, but it doesn't work and I think the reason is that it is currently not supported. Is that right?

Do you have plans to add support in the near future?

**Comment by wfurt** [comment] 2021-12-29 22:38
what error do you get @kskog? AFAIK there should be no reason to be different.
cc: @krwq

**Comment by kskog** [comment] 2021-12-30 14:50
When we try to open the port, it fails with an exception. There is a dll that is missing. We’re using Alpine Linux.

I will post details later.

**Comment by kskog** [comment] 2022-01-03 09:08
Here's the exception I get:

Unable to load shared library 'libSystem.IO.Ports.Native' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library liblibSystem.IO.Ports.Native: No such file or directory

**Comment by wfurt** [comment] 2022-01-04 01:38
Does it work without trimming & single file? As @adamsitnik suggested there may be simply something missing in that case.

**Comment by kskog** [comment] 2022-01-04 08:19
The problem for us is that we have to pack it to make it fit.

I tried to compile without trimming & single file, but there is no file called _liblibSystem.IO.Ports.Native.so_ there.

I can see a file _libSystem.IO.Ports.Native.so_ is there though, but that file is also there when I trimmed/single-filed.

Just out of curiosity, why is there two _lib_ in front of the name? Could that be the issue, that it appends two _liblib_ instead of just _lib_ ?

**Comment by krwq** [comment] 2022-01-04 12:30
@kskog that does look like potential issue, can you share which version of System.IO.Ports package are you using? Looking at:
https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/Common/src/Interop/Unix/Interop.Libraries.cs#L14

the lib prefix seems consistent with other libraries so I'd expect that to work the same as elsewhere...

**Comment by krwq** [comment] 2022-01-04 12:31
Although recently there has been this change: https://github.com/dotnet/runtime/commit/3d6f8a26cb8ee6e9f156c1ab65b3aa0059841552#diff-c1db2d15cd6bf99da7a388eca0ae209ff70f2708d8c4ee6f10d11ad320bdb917
possibly we somehow work differently when library is part of the framework vs a package

**Comment by krwq** [comment] 2022-01-04 12:34
also might be worth checking with `strace` if we probe for both `libSystem.IO.Ports.Native.so` and `liblibSystem.IO.Ports.Native` or just one of them - possibly just the error message is bad and the issue is not about missing file but something else which makes it not able to be loaded

**Comment by kskog** [comment] 2022-01-04 13:29
I am using version 6.0.0

**Comment by krwq** [comment] 2022-01-04 15:46
can you try using `strace -f command_line_you_normally_run_your_process_with` and see if the output probes for both of those files or just one? (i.e. redirect stderr and stdout to a file and search for `System.IO.Ports.Native`)

**Comment by kskog** [comment] 2022-01-07 08:51
I will try, but need to get to the office to test.

**Comment by kskog** [comment] 2022-01-10 08:19
Output from strace:

`sched_yield()                           = 0
sched_yield()                           = 0
futex(0x7ff6e9ddd4, FUTEX_WAIT_PRIVATE, 2, {tv_sec=9, tv_nsec=989997880}) = 0
openat(AT_FDCWD, "/bin/mtgw/libSystem.IO.Ports.Native.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 128
fcntl(128, F_SETFD, FD_CLOEXEC)         = 0
fstat(128, {st_mode=S_IFREG|0744, st_size=198944, ...}) = 0
read(128, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0\267\0\1\0\0\0\0\0\1\0\0\0\0\0"..., 960) = 960
mmap(NULL, 200704, PROT_READ, MAP_PRIVATE, 128, 0) = 0x7f8e420000
mmap(0x7f8e430000, 8192, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 128, 0x10000) = 0x7f8e430000
mmap(0x7f8e440000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 128, 0x20000) = 0x7f8e440000
mmap(0x7f8e450000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 128, 0x30000) = 0x7f8e450000
close(128)                              = 0
mmap(NULL, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8e474000
openat(AT_FDCWD, "/bin/mtgw/netcoredeps/ld-linux-aarch64.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/ld-linux-aarch64.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/local/lib/ld-linux-aarch64.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/ld-linux-aarch64.so.1", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
munmap(0x7f8e420000, 200704)            = 0
munmap(0x7f8e474000, 16384)             = 0
openat(AT_FDCWD, "/bin/mtgw/netcoredeps/libSystem.IO.Ports.Native.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/libSystem.IO.Ports.Native.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/local/lib/libSystem.IO.Ports.Native.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/libSystem.IO.Ports.Native.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/bin/mtgw/liblibSystem.IO.Ports.Native.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/bin/mtgw/netcoredeps/liblibSystem.IO.Ports.Native.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/liblibSystem.IO.Ports.Native.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/local/lib/liblibSystem.IO.Ports.Native.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/liblibSystem.IO.Ports.Native.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/bin/mtgw/libSystem.IO.Ports.Native", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/bin/mtgw/netcoredeps/libSystem.IO.Ports.Native", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/libSystem.IO.Ports.Native", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/local/lib/libSystem.IO.Ports.Native", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/libSystem.IO.Ports.Native", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/bin/mtgw/liblibSystem.IO.Ports.Native", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/bin/mtgw/netcoredeps/liblibSystem.IO.Ports.Native", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/liblibSystem.IO.Ports.Native", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/local/lib/liblibSystem.IO.Ports.Native", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/liblibSystem.IO.Ports.Native", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
mmap(NULL, 32768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8e470000
munmap(0x7f8e470000, 32768)             = 0
sched_yield()                           = 0
sched_yield()                           = 0
`

**Comment by kskog** [comment] 2022-01-10 08:32
Exception output:

[01-10 08:31:27.224] [WRN] [Open]                        Failed to open serial port                         | Port: /dev/ttyACM0, Speed: 1000000, DataPath: ble
Exception info:
Message: Unable to load shared library 'libSystem.IO.Ports.Native' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library liblibSystem.IO.Ports.Native: No such file or directory
<Stack trace>
   at Interop.Serial.SerialPortOpen(String )
   at System.IO.Ports.SafeSerialDeviceHandle.Open(String )
   at System.IO.Ports.SerialStream..ctor(String , Int32 , Parity , Int32 , StopBits , Int32 , Int32 , Handshake , Boolean , Boolean , Boolean , Byte )
   at System.IO.Ports.SerialPort.Open()
   at Meshtech.Gateway.Modules.SerialPort.DotNetSerialPort..ctor(String portName, Int32 portSpeed, Int32 readBufferSize, Int32 writeBufferSize) in /home/ksk/src/cisco-91xx/docker/gateway/Meshtech.Gateway/Modules/SerialPort/DotNetSerialPort.cs:line 25
   at Meshtech.Gateway.Modules.SerialPort.SerialPortModule.Open(SerialPortConfig portConfig) in /home/ksk/src/cisco-91xx/docker/gateway/Meshtech.Gateway/Modules/SerialPort/SerialPort.cs:line 69
</Stack trace>

**Comment by krwq** [comment] 2022-01-10 14:28
@kskog this seems weird - looking at the strace I'd expect either `libSystem.IO.Ports.Native.so` is not in the same directory as your executable. What's you working directory and executable directory when running? What's the location of the `.so` file? It should be in the current working directory

**Comment by kskog** [comment] 2022-01-11 09:00
libSystem.IO.Ports.Native.so is in the same directory as the executable (/bin/mtgw), however, current working directory is /

**Comment by kskog** [comment] 2022-01-12 07:49
Do I have to have working directory set to the directory created by `dotnet publish` ?

To me, it looks like it is able to load `/bin/mtgw/libSystem.IO.Ports.Native.so`, but fails to load it's dependency `liblibSystem.IO.Ports.Native.so`.

**Comment by kskog** [comment] 2022-01-12 08:55
I have now also tried to run without trimming and single-file. I still get the same error.

We're also running the exact same program on linux-x64, but on that platform (Yocto) we're not running self-contained. On that platfrom it works fine.

Working:
`dotnet publish -c Release -r linux-x64 --no-self-contained Meshtech.Gateway/Meshtech.Gateway.csproj`

Not working:
`dotnet publish -c Release -p:PublishTrimmed=true -p:TrimMode=Link -p:PublishSingleFile=true -r linux-musl-arm64 --self-contained --output mtgw gateway/Meshtech.Gateway/Meshtech.Gateway.csproj`

Since I have also tried without trimming and single-file, I think the issue must be due to self-contained or platform.

**Comment by kskog** [comment] 2022-01-12 09:25
Also tried to run self-contained on linux-x64. That also works fine, so then I believe it boils down to `linux-musl-arm64` causing the  issue. Could you try to reproduce?

**Comment by krwq** [comment] 2022-01-13 10:46
@kskog if you run .NET app which doesn't use serial ports on arm64 does it work?

what if you try using same method as you do on yocto for arm64?

Second look at the strace I think it does find `/bin/mtgw/libSystem.IO.Ports.Native.so` but for some reason it is depending on `ld-linux-aarch64.so.1` which suggests it's a x64 rather than arm64

**Comment by kskog** [comment] 2022-01-13 11:45
We currently use https://github.com/jcurl/RJCP.DLL.SerialPortStream on arm64 and it works, but that lib has some issues and we would like to use the .NET version if possible.

As I explained above, all is fine on Yocto (linux-x64).

I think `aarch64` means ARM64 (https://en.wikipedia.org/wiki/AArch64), so it makes sense that it looks for `ld-linux-aarch64.so.1`. It is compiled for arm64, I am 100% sure about that. Otherwise it wouldn't work at all.

**Comment by kskog** [comment] 2022-01-18 10:07
We're using a USB serial port device, not a physical serial port. The device name is `/dev/ttyACM0`.

**Comment by JimiC** [comment] 2022-03-03 17:16
I have the same issue on my app. Works on `Debian` but fails on `Alpine` container .

**Comment by kskog** [comment] 2022-03-09 08:48
Would be great if you could prioritize this. It seems to be a minor issue.. We're having issues with the serialport lib we use now and would love to switch to `System.IO.Ports.SerialPort`.

**Comment by JimiC** [comment] 2022-03-09 09:53
@krwq To iterate further, here is my `strace`. My app lives in `/home` and is compiled without `trim` and without `single file` and without `self-contained`.

```
[pid    60] open("/home/libSystem.IO.Ports.Native.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 35
[pid    60] fcntl64(35, F_SETFD, FD_CLOEXEC) = 0
[pid    60] statx(35, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_BASIC_STATS, 0xbed45e08) = -1 ENOSYS (Function not implemented)
[pid    60] fstat64(35, {st_mode=S_IFREG|0644, st_size=9824, ...}) = 0
[pid    60] read(35, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0L\r\0\0004\0\0\0"..., 936) = 936
[pid    60] mmap2(NULL, 77824, PROT_READ|PROT_EXEC, MAP_PRIVATE, 35, 0) = 0xb1c12000
[pid    60] mmap2(0xb1c23000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 35, 0x1000) = 0xb1c23000
[pid    60] close(35)                   = 0
[pid    60] open("/home/netcoredeps/ld-linux-armhf.so.3", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] open("/lib/ld-linux-armhf.so.3", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] open("/usr/local/lib/ld-linux-armhf.so.3", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] open("/usr/lib/ld-linux-armhf.so.3", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] munmap(0xb1c12000, 77824)   = 0
[pid    60] open("/home/netcoredeps/libSystem.IO.Ports.Native.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] open("/lib/libSystem.IO.Ports.Native.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] open("/usr/local/lib/libSystem.IO.Ports.Native.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] open("/usr/lib/libSystem.IO.Ports.Native.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] open("/home/liblibSystem.IO.Ports.Native.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] open("/usr/share/dotnet/shared/Microsoft.NETCore.App/5.0.14/liblibSystem.IO.Ports.Native.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] open("/home/liblibSystem.IO.Ports.Native.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] open("/home/netcoredeps/liblibSystem.IO.Ports.Native.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] open("/lib/liblibSystem.IO.Ports.Native.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] open("/usr/local/lib/liblibSystem.IO.Ports.Native.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] open("/usr/lib/liblibSystem.IO.Ports.Native.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] open("/home/libSystem.IO.Ports.Native", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] open("/usr/share/dotnet/shared/Microsoft.NETCore.App/5.0.14/libSystem.IO.Ports.Native", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] open("/home/libSystem.IO.Ports.Native", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] open("/home/netcoredeps/libSystem.IO.Ports.Native", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] open("/lib/libSystem.IO.Ports.Native", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] open("/usr/local/lib/libSystem.IO.Ports.Native", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] open("/usr/lib/libSystem.IO.Ports.Native", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] open("/home/liblibSystem.IO.Ports.Native", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] open("/usr/share/dotnet/shared/Microsoft.NETCore.App/5.0.14/liblibSystem.IO.Ports.Native", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] open("/home/liblibSystem.IO.Ports.Native", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] open("/home/netcoredeps/liblibSystem.IO.Ports.Native", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] open("/lib/liblibSystem.IO.Ports.Native", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] open("/usr/local/lib/liblibSystem.IO.Ports.Native", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] open("/usr/lib/liblibSystem.IO.Ports.Native", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] cacheflush(0xb1ce3e2c, 0xb1ce3e5c, 0) = 0
```

If you look closely it's obvious that the library loader is looking for:
- "/home/libSystem.IO.Ports.Native.so"
- "/home/liblibSystem.IO.Ports.Native.so"
- "/home/libSystem.IO.Ports.Native" (note it doesn't include '.so')

but still fails to load it
`Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libSystem.IO.Ports.Native' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library liblibSystem.IO.Ports.Native: No such file or directory`

and this is the folder structure
![image](https://user-images.githubusercontent.com/1716442/157417216-205719cc-8d39-4997-a755-7616a35a3595.png)

**Comment by JimiC** [comment] 2022-03-09 10:01
And looking at the `trace` it seems to me that it does find the library
```
[pid    60] open("/home/libSystem.IO.Ports.Native.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 35
[pid    60] fcntl64(35, F_SETFD, FD_CLOEXEC) = 0
[pid    60] statx(35, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_BASIC_STATS, 0xbed45e08) = -1 ENOSYS (Function not implemented)
[pid    60] fstat64(35, {st_mode=S_IFREG|0644, st_size=9824, ...}) = 0
[pid    60] read(35, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0L\r\0\0004\0\0\0"..., 936) = 936
[pid    60] mmap2(NULL, 77824, PROT_READ|PROT_EXEC, MAP_PRIVATE, 35, 0) = 0xb1c12000
[pid    60] mmap2(0xb1c23000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 35, 0x1000) = 0xb1c23000
[pid    60] close(35)                   = 0
```

but fails to read it?
- Could it be that the compiler includes the wrong library?
- Could it be that the library is not supporting `alpine-arm`?

I'm no expert so I'm wild guessing here.

**Comment by krwq** [comment] 2022-03-09 12:13
@JimiC I think the interesting part is after the file is opened:

```
[pid    60] open("/home/libSystem.IO.Ports.Native.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 35
[pid    60] fcntl64(35, F_SETFD, FD_CLOEXEC) = 0
[pid    60] statx(35, "", AT_STATX_SYNC_AS_STAT|AT_EMPTY_PATH, STATX_BASIC_STATS, 0xbed45e08) = -1 ENOSYS (Function not implemented)
[pid    60] fstat64(35, {st_mode=S_IFREG|0644, st_size=9824, ...}) = 0
[pid    60] read(35, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0L\r\0\0004\0\0\0"..., 936) = 936
[pid    60] mmap2(NULL, 77824, PROT_READ|PROT_EXEC, MAP_PRIVATE, 35, 0) = 0xb1c12000
[pid    60] mmap2(0xb1c23000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 35, 0x1000) = 0xb1c23000
[pid    60] close(35)                   = 0
[pid    60] open("/home/netcoredeps/ld-linux-armhf.so.3", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] open("/lib/ld-linux-armhf.so.3", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] open("/usr/local/lib/ld-linux-armhf.so.3", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] open("/usr/lib/ld-linux-armhf.so.3", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid    60] munmap(0xb1c12000, 77824)   = 0
```

note how it tries to find `ld-linux-armhf.so.3` - likely next step is to identify correct file name and steps to what should be done for that file to be loaded instead (i.e. add another configuration in the package for that platform).

If you have time you can go ahead and play around with your local build (i.e. if you use `dotnet pack` you can later add the directory where package was created to nuget.config - also make sure to clear nuget cache for the dev package, I think it will be somewhere under `~/.nuget` or similar)

**Comment by JimiC** [comment] 2022-03-09 12:26
So, from what you are saying I'm missing `ld-linux-armhf.so.3` but I do have `ld-linux-armhf.so.1`
![image](https://user-images.githubusercontent.com/1716442/157441544-81ebd205-98f5-41f9-9840-4ea5aaefff3b.png)

I'm gonna try to install the pkg and report back any findings

**Comment by wfurt** [comment] 2022-03-09 18:41
I'm wondering if we build on newer OS version that this is running on.. cc: @janvorli

**Comment by JimiC** [comment] 2022-03-09 19:09
@wfurt My app was tested on your `5.0.15-alpine3.14-arm32v7` docker image. I don't think using `alpine3.15` will make any difference, but I'll give it a shot.

**Comment by wfurt** [comment] 2022-03-09 19:15
The interesting part is that the binary expected `ld-linux-armhf.so.3` and you have `ld-linux-armhf.so.1`....

**Comment by JimiC** [comment] 2022-03-09 19:16
I have `ld-musl-armhf.so.1`

**Comment by janvorli** [comment] 2022-03-14 14:55
`ld-linux-armhf.so.3` indicates that it is a binary that is not built for Linux MUSL, but rather for glibc. The name needs to start with `ld-musl`. While it is possible to install a compatibility layer on MUSL that provides ability to run applications compiled for GLIBC, we don't test that and I would not recommend doing that for dotnet apps. And it seems it is probably set to support only apps using `ld-linux-armhf.so.1` loader, not the `ld-linux-armhf.so.3`
I wonder how did the glibc version of `libSystem.IO.Ports.Native.so` end up being published when linux-musl-arm RID was being used. Seems like a dotnet publish issue.

**Comment by JimiC** [comment] 2022-03-14 16:04
Strange at it may seem I tested it again with a fresh Docker image on a BeagleBone board.
Here's a screenshot of the results
![image](https://user-images.githubusercontent.com/1716442/158212106-d1ee2acc-ff4b-47d9-8a58-cc9c65cccf5b.png)

Now everything runs as expected
![image](https://user-images.githubusercontent.com/1716442/158212471-ae13f1d8-0515-47a1-8737-002da473f0e6.png)
P.S. First 2 lines in the logs is from the previous run that failed

**Comment by Jozkee** [comment] 2022-04-01 20:51
> Seems like a dotnet publish issue

What's the right area label for that? cc @danmoseley @ericstj

**Comment by ericstj** [comment] 2022-04-04 20:25
> What's the right area label 

This is still a `area-System.IO` issue with how it's building and shipping the `libSystem.IO.Ports.Native.so`.  Typically we need to get to an understanding of "this should work like this, but it is not" before we triage elsewhere.

> I wonder how did the glibc version of libSystem.IO.Ports.Native.so end up being published when linux-musl-arm RID was being used. 

This is happening because Ports is not **shipping** a `linux-musl` build.  It's only shipping a regular linux build: https://www.nuget.org/packages/runtime.native.System.IO.Ports
<img width="370" alt="image" src="https://user-images.githubusercontent.com/8918108/161625820-ace4f7e3-5672-431c-94fe-fbac2bbc8a49.png">

**Comment by daglundberg** [comment] 2022-05-13 16:26
SerialPort.Open() throws "System.DllNotFoundException: 'libSystem.IO.Ports.Native on Android". I'm using dotnet 6. Is it possible to use a workaround like the one mentioned above also on android?

**Comment by destroyar** [comment] 2022-07-23 17:58
FWIW I ran into a very similar issue this morning on ARMv7 (pi zero2w). Deployed a standalone/trimmed package, and got the same exception `Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libSystem.IO.Ports.Native'`. I was able to turn off trimming/single file and work around it, but wanted to call it out in case it helps here at all.

**Comment by GeorgeStephens** [comment] 2022-08-21 20:33
@destroyar, can you share how you worked around it? Running into the same issue on a a CM4.

**Comment by StephanieZ** [comment] 2022-08-24 16:15
Another thing you might want to try, if you change your .pubxml or dotnet publish command to include: <IncludeNativeLibrariesForSelfExtract>false</IncludeNativeLibrariesForSelfExtract>

Then you can see what native libraries are actually included in your image. Otherwise, they get added to your single file binary and .net tries to extract them to the filesystem. If the permissions on the ~/.net folder and its subfolders are wrong for some reason (like you ran as root and your service/application is running as a different user) then your service cannot access your native library files, which could result in the issue you are seeing. I just ran into this one a MAC OS service application that's running in .net.

Hope this helps.

**Comment by kskog** [comment] 2023-03-27 07:45
It's now been over a year since I first posted this issue. Please fix this so we don't need to include https://pkgs.alpinelinux.org/package/edge/main/aarch64/libc6-compat to get it to work. It shouldn't be that hard..?

Here: https://www.nuget.org/packages/runtime.native.System.IO.Ports/, you can see that `runtime.linux-musl-arm64.runtime.native.System.IO.Ports` is _not_ on the list.

The problem seems to be that the native lib requires ld-linux-aarch64.so.1 even when the app is compiled for linux-musl-arm64.

At least, there should be a warning that this is not supported.

**Comment by krwq** [comment] 2023-03-27 09:54
@kskog can you try with the latest .NET 8 preview package? I think the root cause could be same one as https://github.com/dotnet/runtime/issues/79196 - I think we should be picking up linux-arm64 package and likely for same reason as in other issue that's not happening

**Comment by kskog** [comment] 2023-03-28 07:18
Are these the required steps?

- Update System.IO.SerialPort nuget package to [8.0.0-preview.2.23128.3](https://www.nuget.org/packages/System.IO.Ports/8.0.0-preview.2.23128.3)
- Change <TargetFramework> in csproj to net8.0
- Build this with latest .NET 8 preview SDK

**Comment by cskowronnek** [comment] 2023-03-28 15:55
It's the same error on linux-musl-arm by the way

**Comment by wfurt** [comment] 2023-03-28 16:26
We should figure out how to reproduce it @krwq. I don't have access to good machine so we may be experiment with Docker  unless somebody can share machine for investigation.

**Comment by krwq** [comment] 2023-03-28 18:08
@kskog only first one should be required AFAIK

**Comment by kskog** [comment] 2023-03-30 08:24
@krwq I did all the 3 steps above but it still fails without `libc6_compat`. Same exception:
```
Message: Unable to load shared library 'libSystem.IO.Ports.Native' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /app/libSystem.IO.Ports.Native.so)
Error loading shared library libSystem.IO.Ports.Native.so: No such file or directory
Error loading shared library /app/liblibSystem.IO.Ports.Native.so: No such file or directory
Error loading shared library liblibSystem.IO.Ports.Native.so: No such file or directory
Error loading shared library /app/libSystem.IO.Ports.Native: No such file or directory
Error loading shared library libSystem.IO.Ports.Native: No such file or directory
Error loading shared library /app/liblibSystem.IO.Ports.Native: No such file or directory
Error loading shared library liblibSystem.IO.Ports.Native: No such file or directory
```

It looks like there are still no linux-musl-arm64 file here, maybe that is the reason?

![image](https://user-images.githubusercontent.com/1573920/228775388-6a823fbd-af74-45e8-a630-1274aefac26b.png)

**Comment by krwq** [comment] 2023-05-30 15:57
cc: @carlossanlop

**Comment by sensiki** [comment] 2023-09-14 05:44
Any updates? It still doesn't work

**Comment by wfurt** [comment] 2023-11-09 17:28
I put comment on  #92145. it would be great if anybody can give it try. Once the PR is merged the packages should show up in donet-9 package feed. 

https://dev.azure.com/dnceng-public/public/_build/results?buildId=459685&view=artifacts&pathAsName=false&type=publishedArtifacts

find `library_bin_linux_musl_arm*` and there should be `runtime.linux-musl-arm64.runtime.native.System.IO.Ports.9.0.0-ci.nupkg`

**Closed** 2023-11-14 14:28 UTC
Labels: packaging, os-alpine, in-pr, area-System.IO.Ports
