### ISSUE TITLE
Test failure: Loader\\AssemblyDependencyResolver\\AssemblyDependencyResolverTests\\AssemblyDependencyResolverTests\\AssemblyDependencyResolverTests.cmd

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#34882] opened 2020-04-13 04:26 UTC
failed in job: [runtime-coreclr outerloop 20200412.3](https://dev.azure.com/dnceng/public/_build/results?buildId=598005&view=ms.vss-test-web.build-test-results-tab&runId=18835598&resultId=109084&paneView=debug)

Error message
~~~
Return code: 1
Raw output file: C:\h\w\9F9408D6\w\A94C0972\e\Loader\AssemblyDependencyResolver\Reports\Loader.AssemblyDependencyResolver\AssemblyDependencyResolverTests\AssemblyDependencyResolverTests\AssemblyDependencyResolverTests.output.txt
Raw output:
BEGIN EXECUTION
1 file(s) copied.
" "C:\h\w\9F9408D6\p\crossgen.exe" /Platform_Assemblies_Paths C:\h\w\9F9408D6\p;C:\h\w\9F9408D6\w\A94C0972\e\Loader\AssemblyDependencyResolver\AssemblyDependencyResolverTests\AssemblyDependencyResolverTests /in C:\h\w\9F9408D6\w\A94C0972\e\Loader\AssemblyDependencyResolver\AssemblyDependencyResolverTests\AssemblyDependencyResolverTests\AssemblyDependencyResolverTests.org /out C:\h\w\9F9408D6\w\A94C0972\e\Loader\AssemblyDependencyResolver\AssemblyDependencyResolverTests\AssemblyDependencyResolverTests\\AssemblyDependencyResolverTests.dll"
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
Copyright (c) Microsoft Corporation. All rights reserved.
Native image C:\h\w\9F9408D6\w\A94C0972\e\Loader\AssemblyDependencyResolver\AssemblyDependencyResolverTests\AssemblyDependencyResolverTests\\AssemblyDependencyResolverTests.dll generated successfully.
"C:\h\w\9F9408D6\p\corerun.exe" AssemblyDependencyResolverTests.dll 
TestComponentLoadFailure Start
TestComponentLoadFailure FAILED:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> Xunit.Sdk.ThrowsException: Assert.Throws() Failure
Expected: typeof(System.InvalidOperationException)
Actual: typeof(System.ArgumentNullException): Value cannot be null. (Parameter 't')
at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
at TestLibrary.HostPolicyMock.MockValues_corehost_set_error_writer.get_LastSetErrorWriter() in F:\workspace\_work\1\s\src\coreclr\tests\src\Common\CoreCLRTestLibrary\HostPolicyMock.cs:line 132
at AssemblyDependencyResolverTests.AssemblyDependencyResolverTests.<>c__DisplayClass4_0.<TestComponentLoadFailure>b__0(String componentAssemblyPath) in F:\workspace\_work\1\s\src\coreclr\tests\src\Loader\AssemblyDependencyResolver\AssemblyDependencyResolverTests\AssemblyDependencyResolverTests.cs:line 55
at Interop.HostPolicy.corehost_resolve_component_dependencies(String componentMainAssemblyPath, corehost_resolve_component_dependencies_result_fn result)
at System.Runtime.Loader.AssemblyDependencyResolver..ctor(String componentAssemblyPath)
at AssemblyDependencyResolverTests.AssemblyDependencyResolverTests.<TestComponentLoadFailure>b__4_1() in F:\workspace\_work\1\s\src\coreclr\tests\src\Loader\AssemblyDependencyResolver\AssemblyDependencyResolverTests\AssemblyDependencyResolverTests.cs:line 62
at Xunit.Assert.RecordException(Action testCode) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\Record.cs:line 27
--- End of inner exception stack trace ---
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
at AssemblyDependencyResolverTests.TestBase.<>c__DisplayClass18_1.<RunTestsForInstance>b__1() in F:\workspace\_work\1\s\src\coreclr\tests\src\Loader\AssemblyDependencyResolver\AssemblyDependencyResolverTests\TestBase.cs:line 87
at AssemblyDependencyResolverTests.TestBase.RunSingleTest(Action test, String testName) in F:\workspace\_work\1\s\src\coreclr\tests\src\Loader\AssemblyDependencyResolver\AssemblyDependencyResolverTests\TestBase.cs:line 70
TestComponentLoadFailureWithPreviousErrorWriter Start
TestC


Stack trace
   at Loader_AssemblyDependencyResolver._AssemblyDependencyResolverTests_AssemblyDependencyResolverTests_AssemblyDependencyResolverTests_._AssemblyDependencyResolverTests_AssemblyDependencyResolverTests_AssemblyDependencyResolverTests_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.arm64.Checked\TestWrappers\Loader.AssemblyDependencyResolver\Loader.AssemblyDependencyResolver.XUnitWrapper.cs:line 140
~~~

**Comment by jkotas** [comment] 2020-04-13 06:59
Duplicate of #34881

**Closed by jkotas** 2020-04-13 06:59 UTC
Labels: area-Interop-coreclr, untriaged
