### ISSUE TITLE
DataAnnotations Validation messages are incorrect in a trimmed app.

### ISSUE THREAD

**Issue by doyce** [dotnet/runtime#42257] opened 2020-09-15 12:03 UTC
I'm using DataAnnotationsValidator in my Blazor Webassembly application together with ValidationMessage component. The validated property has a Required attribute applied with no custom validation message. In version 3.2, there was a default validation message appearing, saying that this field is required. After upgrading to .net 5 RC1, the default message was replaced by some kind of placeholder (see image).

![obrazek](https://user-images.githubusercontent.com/64796813/93207677-98735000-f75b-11ea-853e-371287e23bc0.png)

Note that this behavior occurs only when the application is published as production. When running in development mode in Visual Studio, the default validation message appears correctly.

The default validation message is also broken for other attributes (tested with Range).

**Comment by pranavkm** [comment] 2020-09-15 16:22
@eerhardt \ @layomia I tried this and it reproduces with a rc1+ or newer build. Publishing the app without trimming produces the right results. Additionally, I did not see issues reading resx files from the app (which isn't linked).

**Comment by eerhardt** [comment] 2020-09-15 16:46
You can disable this behavior by setting:

```xml
<UseSystemResourceKeys>false</UseSystemResourceKeys>
```

As a workaround for now.

@vitek-karas @MichalStrehovsky @marek-safar @joperezr @jeffhandley @ericstj  - thoughts on this? Should we exclude `System.ComponentModel.DataAnnotations` from `UseSystemResourceKeys` by default since a lot of its messages are not exception messages?

**Comment by jeffhandley** [comment] 2020-09-15 17:42
Retaining the messages from `DataAnnotations` by default seems like a good idea to me.

**Comment by eerhardt** [comment] 2020-09-15 20:29
I've opened a PR to fix this. https://github.com/dotnet/runtime/pull/42274

Anyone have thoughts on whether this meets the 5.0 bar or not?

**Comment by pranavkm** [comment] 2020-09-15 20:32
Forms and validation is pretty essential to Blazor and our built-in Component uses DataAnnotations. It would be frustrating for developers to have to remember to modify their project file any time they use validation. I'd certainly ask.

**Comment by jeffhandley** [comment] 2020-09-15 21:27
It feels like a "broken or incomplete .NET 5.0 scenario" to me; I'd support it.

**Comment by eerhardt** [comment] 2020-09-22 22:28
Reopening for backport to 5.0.

**Comment by eerhardt** [comment] 2020-09-23 16:24
Fix merged into 5.0. Closing.

**Closed by eerhardt** 2020-09-23 16:24 UTC
Labels: area-System.ComponentModel.DataAnnotations, blocking-release, linkable-framework
