### ISSUE TITLE
.NET 6 strong name signing behavior breaks existing code.

### ISSUE THREAD

**Issue by masonwheeler** [dotnet/runtime#69311] opened 2022-05-13 14:01 UTC
### Description

I've got a program that uses the Boo interpreter under the hood.  It breaks on updating to .NET 6, because of a breaking change that causes strong name signing to throw an exception.  The following code will always throw, even if the public key value is `null`:
```
			var assemblyName = new AssemblyName();
			assemblyName.Name = GetAssemblySimpleName(outputFile);
			assemblyName.Version = GetAssemblyVersion();
			if (Parameters.DelaySign)
				assemblyName.SetPublicKey(GetAssemblyKeyPair(outputFile).PublicKey);
			else
				assemblyName.KeyPair = GetAssemblyKeyPair(outputFile);
			return assemblyName;
```
Is there any way to fix this behavior without 1) modifying the compiler's code or 2) reverting back to .NET 5 and losing some important .NET 6 benefits I'd prefer to keep?

### Reproduction Steps

    var assemblyName = new AssemblyName();
    assemblyName.Name = "test";
    assemblyName.SetPublicKey(null);

### Expected behavior

Behavior should remain consistent with previous versions of .NET.

### Actual behavior

An exception is thrown.

### Regression?

Yes, this is a massive breaking change from .NET 5 and earlier .NET versions.  And even if strong-name signing is no longer supported, supplying a `null` here indicates that *strong-name signing is not actually being used,* and therefore no problem exists that needs to be interrupted by throwing an exception.

### Configuration

.NET 6, Windows 10, x64

**Comment by AaronRobinsonMSFT** [comment] 2022-05-13 14:42
@masonwheeler Someone will take a look today, what is the exception that is being thrown?

**Comment by jkotas** [comment] 2022-05-13 14:43
```
var assemblyName = new AssemblyName();
assemblyName.Name = "test";
assemblyName.SetPublicKey(null);
```

This does not throw for me on .NET 6.

What is the stacktrace of the exception you seeing?

**Comment by masonwheeler** [comment] 2022-05-13 14:49
@jkotas Sorry, my mistake, when simplifying this code I took the wrong branch.

The problem is coming from setting `KeyPair`, which [unconditionally throws `PlatformNotSupportedException`.](https://github.com/dotnet/runtime/blob/9d0644972eca8caa05f8faaf9ca4b063c7fa75cc/src/libraries/System.Private.CoreLib/src/System/Reflection/AssemblyName.cs#L251)

**Comment by masonwheeler** [comment] 2022-05-13 14:52
It appears that this breaking change was introduced in [this commit](https://github.com/dotnet/runtime/commit/207b03a073107e63df0b67056dd596226065651e) by @buyaa-n.

**Comment by masonwheeler** [comment] 2022-05-13 22:25
It gets worse.  When I try to modify the compiler to omit this code branch, it starts failing on all sorts of other reflection APIs that are not in .NET 6, even though the compiler is compiled against .NET Framework.  On .NET 5 this would Just Work, seamlessly using the Framework versions of those APIs; what in the world happened in this version?

**Comment by AaronRobinsonMSFT** [comment] 2022-05-13 22:56
@jeffhandley @GrabYourPitchforks @joperezr Tagging all of you as reviewers of https://github.com/dotnet/runtime/pull/50941. It would seem we introduced changes that are causing issues for @masonwheeler. Did we create a breaking change issue for tracking? Did we miss something determining the potential impact here?

**Comment by GrabYourPitchforks** [comment] 2022-05-14 00:02
@AaronRobinsonMSFT Looks like we missed the doc for this. I can do retroactively update the doc if needed. The scenario previously compiled and ran but never *worked*. As soon as you ever tried doing anything with the instance, you'd get a runtime exception. The only thing you could ever do was to create the instance and then never look at it again. So to make more explicit that this scenario was unsupported, the exception-throwing logic was moved into the instance ctor, and since no instances could ever be created, propagated to public entry points returning this type (like the _KeyPair_ accessor).

@masonwheeler Can you clarify what you mean by the below comment?

> it starts failing on all sorts of other reflection APIs that are not in .NET 6

Pretty much all reflection APIs which were in .NET Framework should also be in .NET 6 and should work correctly. If you have a simplified repro showing something that does not work - even after the call to the _KeyPair_ property has been removed - let us know and we can take a look! Thanks.

**Comment by masonwheeler** [comment] 2022-05-14 00:07
@GrabYourPitchforks There's still a lot of System.Reflection.Emit — the compiler's codegen backend — that remains unimplemented.  To give just one example, a method containing a call to `AssemblyBuilder.SetEntryPoint` fails on .NET 6 with a `MissingMethodException`.  In .NET 5 it worked correctly, detecting that the assembly was built under Framework and calling the relevant Framework APIs.  That strategy appears to be completely broken in 6.

**Comment by jkotas** [comment] 2022-05-14 00:12
`AssemblyBuilder.SetEntryPoint` did not exist in .NET 5. There is no for a call to `AssemblyBuilder.SetEntryPoint` could have worked in .NET 5.

**Comment by masonwheeler** [comment] 2022-05-14 00:14
@jkotas Like I said, it worked because the assembly in question was compiled under Framework 4.x and it was using some sort of compatibility mode to invoke the Framework APIs.  I don't know the exact details; I just know that it was working in .NET 5 and it's broken in 6.

**Comment by jkotas** [comment] 2022-05-14 00:31
.NET 5 does not have any compatibility mode that would have allowed a call to `AssemblyBuilder.SetEntryPoint` to work.

**Comment by masonwheeler** [comment] 2022-05-14 00:32
Then why was it working?  Because it was, right up until I upgraded the host app to 6.

**Comment by jkotas** [comment] 2022-05-14 00:37
Can you share a repro that shows `AssemblyBuilder.SetEntryPoint` working on .NET 5?

**Comment by buyaa-n** [comment] 2022-05-31 20:51
Created a [breaking change doc issue](https://github.com/dotnet/docs/issues/29681), closing as by design

**Closed by buyaa-n** 2022-05-31 20:51 UTC
Labels: area-System.Reflection, needs-further-triage

**Comment by KalleOlaviNiemitalo** [comment] 2022-06-01 04:40
.NET API Catalog shows 14.9 % usage of [AssemblyName.KeyPair](https://apisof.net/catalog/0944dc64-56ac-51c4-bdb5-2d1d40b6fa53) in NetFx Compat Lab. That seems quite high to me.
