### ISSUE TITLE
JIT: CMOV aka CMOVcc not generated when method is inlined.

### ISSUE THREAD

**Issue by hexawyz** [dotnet/runtime#96593] opened 2024-01-07 16:40 UTC
### Description

When playing with the now infamous "One Billion Row Challenge", I noticed that while the JIT properly emits `CMOVG` and `CMOVL` for Min/Max operations, those sometimes get replaced by more classical branches when in the context of a more complex method.
I've put the relevant code here to look at the disassembly: [Code on SharpLab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8lAbhvqfIDoARAS2wBzAHYRcGfmFztajZn0Gjxk6dwDCEACYwAgiOwAbAJ65+MjvJ4AlAK4jJ+GBoj4ADv0MwoAZW8A3KRgLOS5uOwd+J24ASQdvCDc/KECwYNlOBQAVGAQMWQ5SBgAFbChcbxoAbxoGOoYAegaGLIALcwYOjFaYBkhYBiMhaH5u/G4GGIwGAHdoAGtcBggRQYYzESEvBm7YbC1Z0daIW2m3KAhgL3xcblr6gG0AWRhu7Rj3QwAKF7etD7chgA8m5JCtbrohEJYLgzP4YCDHPwAF7YMEiACUAF17nViABmLhIBj2XDYABmvWIKBKZQqXwEYHRZWMAB4AKoYckADh8GCg/E21hg5LQkwwMHwvDR2AAfIMobAhGjgmLYOSGMBjBL1hgyhg1SLNdrejARFoMbiGDVqABIW3q406sC2KCwBwMAC8DEdEn1sntTQY7IqOzmDBEwQlB0MEESS1wEB2rTRs16YGwq3mMBgblmC0FQmWq2wDEMZSEvRmgq0EBmyw11bepwYKcCmx2Sdsbi0Ks60xg8Kgxh2UWcNHtM3a2y+7JEZMpsVwui0WhhuAAMsFcG1M19HS63WaDT6jWaLZa7babfbbZB59MRILpgB1Gt1nwo3reugIFB0ACAO5OgA3te8JE6D02hhY5DAOH8EGAgor1tIMX16HQJSgfBBV6boq3feszGRXoelgCd7SfD1YHwbBBULLdNm6L1g3nClnAAIRNIFyXJCoMH3I1D3dE9HXPDFQIdI0tR1atzTrABRc0WMdOcF2cFctC4iUeL415BI1YTjzFKiMG4J5BS+N95JmT8SIYABqFpWhgiA4MNWj6M2RihG6DEJIoqSNRkgibOFSMZiMaDglg+DTw1Gi6KooQfOY+VrNrWyvwYAB+eLWPU7gfFsYB+WwJltIRXj+IMw4bKUrQxWi3BYoxBgQHyuTMoa5DbyDUpyl6WA3BgFUtBMElIkMZM8JcmK3IODowAuWEYC0O4UNrQKb1vZ91klKQ3JWOIdAQFiXnwaBjCeOkU0MDQ9glHw3D3A9XREsUvmfDE1PY7hKt0mq3qPBxDUbQiGv82JzVyHivi+EKMQAclYJGApQoKGH8Mp+0laU9RUo1NEMLwmX4cEbvKO7uAAcVeAA1IxbBgYVySBKBNN4EVsFsQwBOEaEYGVCVcBMmB605Hk+QFIURXhkKACofrYxddFwYoIGfbxaqMhwMTFCocMgWMRBO3J9eWFtgDjabcnMDBcHR29MZCiNbHwYBvD5fVCY1X7VdXHX3uM/ajaO02YbOpzyCd3bqMU80zbO70LquymWqMB7Rqel6RFqkR3c93w9SgE8vr1/3OO46r9MdAuPa9kvRKNLqE4vaHTrhhGTWRgAdEQ0ck209uxwxmZYgaKgAMX4BA1o15988Lxv9TBgq/s0peG+L1efTbpP/KH3Xpm9VSVY0wO6+XnfS7VffI8chgY963aNS+O2JEdwLr2/4eJSlGU3BISC2FjAL4o9max3tAAX2/jAQwFRv47V2v/fGpZvQRXAUzGAUDbSwOoIFfBt4pyeF6LOc+S5NLri3LCXcedgYfU6oRcK4sopzRagtQ+FF8H1AYDw+oE5zj8GxjqZgxI9qTxgDPOeWgF4OFqq7P0t98qu3EhOHa1s3KdFwAAOSFmiYR35dQ+09N6buEpkZwBRhRR0rtj6+20Xo4Whjcr5UrkAy+RolEnhju1fK3jQLngce/ZSpiGBI17lAJGriz6FWKqVKA5UBJiXNGKXxHUUkWlAiPbBLF7FwHCXQaxV57GnyNO4zeDCQ7PxoBREhM4ACE7iYjLlXOuGmj1vB0KDiDZuGpxKXntMgvaYA8nBw9AUpGRTJIQKMaM2UP5XHkEYArLGuSnKjI6rMySpS3EUMqUJcZPjY74IosQAA7I4/Rkh4SuLgLMvx2yJz4NOdQUk7FTz7BWBNCQUBbBMmDFyXk/JCys3MTAVZbhNbxCgGKPaXgmKtDah1GICkACOtgZRXBgByIF0tQUillNUQRAoRFDVGrWEQE1FYMAAPpQq1lAFiDKYUBiEWSz5lKJp7VpQi3yrQWJ8u6L1AkDBhT7CBFS4wz1MyshCvKRmY9vzykwfS6FWExS8rNPy9GE5RUQCHAKHQXBGBZAgPizYXw2qenlEpSAWhCzcHZFkKe3JaavAtUIL4irIEisJAa7wRreiaOmuizFCCvgPB0RADAOjeaGBfD0PO/JIFYmWMAAAVjAJkeVLgZsGbaG16aM3aMBVLEFssNS/IYAAMhrQwMNRhcBfF+bqu0oqQ0NoxU22ceKK1CFZssfCUBrUKuwUVGAGKzRpEbd8GNZFuA+pwX65Yhr+DGr2nTDAAAJPArRNA6Cteoiiu6WoHtIixTBsdWgeK0iaZtS7Y4XNbNwM1p793aDAU7F5tTqAPC5sAWwUJvACFwICbAxgvgACILIiE9FUWD0CxQ3QQPBlDSGGDFXwPBrD0CGCaHsBgeDBGHDQKg9iGgvz/nTCmHjGUxK7Tsr7DynCIg2WkuYx6WltEEDseEZx6YtLcDuz4xynlkBCMBj1YSPYXKRx7Vg16eU3HBQBlFbJ758mPQoaU3SnjamZMUs05BaYWHdNCZE9Jzlxm9okZPspiTDgV20YAXqcu0xZnIuTOYLBSqxSzP89gtJbUqh8N/baJjOoXNoPcwwVjcKPQ8YS9MYT+Bkt9BOHrY9V4VOrG9Kx0C3HsDJzi8VwrqWWKpcK45k+GXJPPPC6K6kDBgFKhVLFzz2X7S5fOmiG9sGvi5cC0q2ORWSs3W6OZYrg2ktrJG+V92jlvRPJyzVhyDkAyvNtE1mkrXrlgOizKIdZFBk7R6ynPr5lLJDeO94bguXRs8d65NlDM3itinnXdsbo2KsOW9J9qARVLOrcy9MP7t3Ad2c2zQaBQA==)

To confirm that what I observed in SharpLab corresponded to what would be a Tier1 codegen, I manually observed a Release build in Visual Studio. I could see the assembly for the method changing between two occurences of a manual breakpoint (using `Debugger.Break()`)

As far as I can tell, the code generation difference is not directly related to JIT inlining, as I would see the conditional jump opcodes before splitting this specific code in a separate method.

Relevant C# Code for the method:
````
struct ItemData
{
	private int _min;
	private int _max;
	private int _sum;
	private int _count;

	public void Aggregate(int value)
	{
		_min = Math.Min(_min, value);
		_max = Math.Max(_max, value);
		_sum += value;
		_count++;
	}
}
````

Code of the method before inlining:
````
ItemData.Aggregate(Int32)
    L0000: mov eax, [rcx]
    L0002: cmp eax, edx
    L0004: cmovg eax, edx
    L0007: mov [rcx], eax
    L0009: mov eax, [rcx+4]
    L000c: cmp eax, edx
    L000e: cmovl eax, edx
    L0011: mov [rcx+4], eax
    L0014: add [rcx+8], edx
    L0017: inc dword ptr [rcx+0xc]
    L001a: ret
````

Relevant code of the method when inlined:
````
Parser.Parse(System.Collections.Generic.Dictionary`2<Utf8StringRef,ItemData>, Byte ByRef, Byte ByRef)
…
    L00cc: mov ecx, [r13]
    L00d0: cmp ecx, eax
    L00d2: jle short L00e6 ; Corresponding to cmovg above
    L00d4: mov edx, eax
    L00d6: mov [r13], edx
    L00da: mov ecx, [r13+4]
    L00de: cmp ecx, eax
    L00e0: jge short L010b  ; Corresponding to cmovl above
    L00e2: mov edx, eax
    L00e4: jmp short L010d
    L00e6: mov edx, ecx
    L00e8: jmp short L00d6
…
    L010b: mov edx, ecx
    L010d: mov [r13+4], edx
    L0111: add [r13+8], eax
    L0115: inc dword ptr [r13+0xc]
    L0119: jmp short L0100
    L011b: cmp rdi, rsi
…
````

I initially thought that the problem with `CMOVcc` was that it can not have a memory destination, but as can be seen in the non inlined method, the JIT chooses to use it despite that fact, which matches with my intuition that it is the correct thing to do here.
The jumps that I see re-introduced in the inlined version (possibly because the JIT failed to detect the pattern there ?) are at least increasing the size of the assembly, but I'd assume they would possibly degrade the performance of the code, depending on the exact data processed.

I tried to trick the JIT in generating `CMOV`-based code in multiple different ways there (introducing intermediate variables, etc), but I could not get it to not do it.
IIRC, the worst of the cases I managed to produce was one where the conditional jumps would directly point to `JMP` opcodes without doing anything else uselful.

Code can also be found here: https://github.com/hexawyz/OneBillionRows/blob/adf45647de4d4d9d49c6002e29bd483cee608af3/OneBillionRows/Program.cs#L328

I apologize for not providing a more minimal repro, but hopefully, this one is still small enough so that you can understand what is happening here.

### Configuration

Local: .NET 8.0.100, x64
SharpLab: Core CLR 8.0.23.53103 on x64

**Comment by neon-sunset** [comment] 2024-01-07 16:54
It's probably this https://github.com/dotnet/runtime/issues/96380

**Comment by jakobbotsch** [comment] 2024-01-07 18:15
Thanks for the report. Indeed, this is a duplicate of #96380. We do not emit conditional instructions inside loops today because it can cause significant performance regressions, and the right analysis to predict the profitability has not yet been implemented.
I'm going to close this, but we will keep the example you have shared in mind for when we get around to working on this.

**Closed by jakobbotsch** 2024-01-07 18:15 UTC
Labels: tenet-performance, area-CodeGen-coreclr, untriaged
