### ISSUE TITLE
[Uri] macOS localpath ucschars are still escaped 

### ISSUE THREAD

**Issue by NinoFloris** [dotnet/runtime#58504] opened 2021-09-01 14:59 UTC
Underlying issue: https://github.com/dotnet/runtime/issues/33053

I recently re-enabled a skipped test for this and at least on macOS this still fails for me.

Did this actually get fixed?

**Comment by MihaZupan** [comment] 2021-09-02 21:53
We did make a change here. Can you share an example of the input/output/desired output?

**Comment by karelz** [comment] 2021-09-09 16:09
@NinoFloris any update? It is currently not actionable for us. Thanks!

**Comment by NinoFloris** [comment] 2021-09-09 21:05
Apologies, this got lost in my holiday inbox backlog.

 The failing test is as follows (F#), making these paths unc does not change things (though it might do so on windows):
```fs
[<InlineData("/f\uFFF0ile.txt")>]
[<InlineData("/pa\uFFF0th/to/file.txt")>]
let [<Theory>] ``localpath containing ucschar should be returned as is`` (path: string) =
    Assert.Equal(path, Uri(path).LocalPath)
```

```
Assert.Equal() Failure
            ↓ (pos 2)
Expected: /f￰ile.txt
Actual:   /f%EF%BF%B0ile.txt
            ↑ (pos 2)

Assert.Equal() Failure
             ↓ (pos 3)
Expected: /pa￰th/to/file.txt
Actual:   /pa%EF%BF%B0th/to/file.txt
             ↑ (pos 3)
```

Given both macOS and unix forbid almost nothing more than the forward slash from appearing in a f path reverting (or foregoing) any percent encoding seems appropriate for LocalPath, including the 'Specials' range (as emojis do indeed get properly decoded) https://www.unicode.org/charts/PDF/UFFF0.pdf.

**Comment by MihaZupan** [comment] 2021-09-14 19:30
Same as https://github.com/dotnet/runtime/issues/33053#issuecomment-598282251

Triage: `LocalPath` should do escaping which is appropriate for the platform.

**Comment by karelz** [comment] 2021-09-14 21:35
@MihaZupan is it a dupe, or did we fix it only partially in 5.0?
Do we still need more info?

**Comment by MihaZupan** [comment] 2021-09-14 21:44
We fixed the UNC path case (#33053), but the issue remains for Unix file paths.

**Comment by MihaZupan** [comment] 2021-12-20 15:37
Note that in your example, `\uFFF0` is not in the `ucschar` definition. Regardless, `LocalPath` shouldn't be escaping it.

**Comment by NinoFloris** [comment] 2021-12-20 17:09
>What is the reason you are using Uri when dealing with file paths instead of Path APIs?

Let me answer that one from my perspective at least. We don't have any other fully featured apis that deal with unix-like paths (including parsing relative segments to absolute etc) consistently, while Uri still mostly works as expected* on windows when it comes to these paths.

*Caveats abound... but they are navigable.

**Comment by MihaZupan** [comment] 2023-08-03 13:00
Duplicate of #89538

**Closed by MihaZupan** 2023-08-03 13:00 UTC
Labels: bug, area-System.Net
