### ISSUE TITLE
System.Diagnostics (Observability) work planned for .NET 7

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#62027] opened 2021-11-24 21:02 UTC
**This issue captures the planned work for .NET 7. This list is expected to change throughout the release cycle according to ongoing planning and discussions, with possible additions and subtractions to the scope.**

## Planned for .NET 7
- [x] #63649
- [x] #63648
    - open-telemetry/opentelemetry-dotnet#2362
- [x] https://github.com/dotnet/runtime/issues/67207
- [x] #67276
- [x] #63652
- [x] #42575
- [x] #63353
- [x] #65660
- [x] #63868
- [x] https://github.com/dotnet/runtime/issues/68056

## Planned for .NET 8+
- #63650
- #50777
- #12750
- #12730
- #61857
    - Currently there is an applied workaround for that
- #63651
    - Spec exists already
- #61947
    - @Reyang is following up with creating a prototype using Source Generators
- #53641
    - OTel specs dependency
- [Attribute Extractor Support](https://github.com/open-telemetry/oteps/blob/8335c9a53cdf3398075dd9523d3752522c0ece28/text/0165-instrumentation-api.md#attributesextractor)
    - OTel Specs dependency
    - @noahfalk following up with this item
- Add Timer instrument
    - OTel specs dependency
- Support Bound instruments
    - OTel specs dependency
- OTel Baggage signal is independent of tracing, where .NET Baggage is associated with Activity
    - Cijo going to send the link for this item
    - Need to figure out who is asking for that and need to clarify the ask
    - P3 till we get specific ask
- OTel propagators support OTel Baggage, .NET propagators does not
    - Cijo going to send the link for this item
    - Need to figure out who is asking for that and need to clarify the ask
    - P3 till we get specific ask

**Comment by tarekgh** [comment] 2021-11-24 21:05
CC @noahfalk @shirhatti @cijothomas @reyang @maryamariyan

**Comment by ejsmith** [comment] 2022-04-29 21:36
@tarekgh this OpenTelemetry spec feature is really important for a lot of scenarios:

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#multiple-instrument-callbacks

I am attempting to populate queue stats like queue count, working item count and deadletter counts as 3 different observable gauges. Getting the counts requires an expensive call and, when I make that, it returns all 3 counts at the same time. The problem is since gauges are required to be observable, I have to give different callbacks for each gauge. I think there are a lot of similar use cases that would greatly benefit from this feature being implemented.

**Comment by tarekgh** [comment] 2022-05-02 00:08
@ejsmith thanks for the suggestion. For now, you may solve this by using the following simple workaround:

```C#
    public class InstrumentsValues<T1, T2, T3>
                    where T1 : struct
                    where T2 : struct
                    where T3 : struct
    {
        private T1? _value1;
        private T2? _value2;
        private T3? _value3;
        private Func<(T1, T2, T3)> UpdateValues { get; set; }

        public InstrumentsValues(Func<(T1, T2, T3)> readValues)
        {
            _value1 = null;
            _value2 = null;
            _value3 = null;

            UpdateValues = readValues;
        }

        public T1 GetValue1()
        {
            if (!_value1.HasValue)
            {
                (_value1, _value2, _value3) = UpdateValues();
            }

            T1 value = _value1.Value;
            _value1 = null;
            return value;
        }

        public T2 GetValue2()
        {
            if (!_value2.HasValue)
            {
                (_value1, _value2, _value3) = UpdateValues();
            }

            T2 value = _value2.Value;
            _value2 = null;
            return value;
        }

        public T3 GetValue3()
        {
            if (!_value3.HasValue)
            {
                (_value1, _value2, _value3) = UpdateValues();
            }

            T3 value = _value3.Value;
            _value3 = null;
            return value;
        }
    }

````  

and here is an example how to use it:

```C#
            Random random = new Random();
            using Meter meter = new Meter("My Meter");
            InstrumentsValues<int, long, double> values = new InstrumentsValues<int, long, double>(() => (random.Next(), random.NextInt64(), random.NextDouble()));

            ObservableCounter<int> observableCounter1 = meter.CreateObservableCounter<int>("Counter 1", () => new Measurement<int>(values.GetValue1(), new KeyValuePair<string, object?>("Counter 1", null)));
            ObservableGauge<long> observableGauge = meter.CreateObservableGauge<long>("Gauge 1", () => new Measurement<long>(values.GetValue2(), new KeyValuePair<string, object?>("Gauge 1", null)));
            ObservableCounter<double> observableCounter2 = meter.CreateObservableCounter<double>("Counter 2", () => new Measurement<double>(values.GetValue3(), new KeyValuePair<string, object?>("Counter 2", null)));
````

I assume your gauges are going to be observed at the same time. But if not, it is easy to tweak this implementation to invalidate the values periodically. 

CC @noahfalk @reyang @CodeBlanch

**Comment by ejsmith** [comment] 2022-05-02 00:36
@tarekgh I'll give this method a try. I tried something similar, but it didn't work.

**Comment by noahfalk** [comment] 2022-07-26 04:49
@tarekgh - how do you feel about closing this issue and we can re-open a new one once we've made plans with the OpenTelemetry folks for .NET 8? We can always refer back to this issue if we want to see the list of items we were considering - the list won't be lost.

**Closed** 2022-07-26 16:20 UTC
Labels: Epic, area-System.Diagnostics, Priority:2, Team:Libraries
