### ISSUE TITLE
[Uri] LocalPath shouldn't encode unicode chars

### ISSUE THREAD

**Issue by lyf6lyf** [dotnet/runtime#62946] opened 2021-12-17 06:14 UTC
### Description

We have a file that have some unicode chars "D:\Library\Music\VITAA & SLIMANE - C‡a va Ca vient.mp3".
`Uri.LocalPath` will encode them and it make the other system API can't read it.

### Reproduction Steps

```csharp
var x = new Uri(@"D:\Library\Music\VITAA & SLIMANE - C‡a va Ca vient.mp3");
Console.WriteLine(x.OriginalString);
Console.WriteLine(x.LocalPath);
```

![image](https://user-images.githubusercontent.com/6219635/146497253-6da3f0e3-f29c-4dbe-a3ee-352a6153fd49.png)

### Expected behavior

The `LocalPath` should be D:\Library\Music\VITAA & SLIMANE - C‡\u0087\u0087a va Ca vient.mp3

### Actual behavior

The `LocalPath` is D:\Library\MusicVITAA & SLIMANE - C?%C2%87%C2%87a va Ca vient.mp3

### Configuration

version: UWP and Net 6

OS: Windows 22504.1010

Architecture: x64,

**Comment by MihaZupan** [comment] 2021-12-20 15:39
This looks like the same issue as #58504 - Uri will escape characters that are not a part of `ucschar` per RFC3987.
But it should not do so for `LocalPath`.

What is the reason you are using `Uri` when dealing with file paths instead of `Path` APIs?

**Comment by MihaZupan** [comment] 2021-12-20 15:39
Duplicate of #58504

**Closed by MihaZupan** 2021-12-20 15:39 UTC
Labels: area-System.Net, untriaged

**Comment by lyf6lyf** [comment] 2021-12-22 04:46
@MihaZupan 

> What is the reason you are using Uri when dealing with file paths instead of Path APIs?

We will run different code depending on the input string. 
```
var uri = new Uri(inputStr);
if (uri.IsFile){
    Handle(uri.LocalString);
}
else {
...
}
```
Besides, if the original string is "file://c/path/to/file", `Uri.LocalPath` will be "\\c\path\to\file". We want to leverage it because we use some library that can't be used with "file://" protocol.
