### ISSUE TITLE
Circular Shift for bitarray

### ISSUE THREAD

**Issue by TourajOstovari** [dotnet/runtime#46668] opened 2021-01-07 12:27 UTC
## Background and Motivation
For Cryptography usage.

## Proposed API

```diff
namespace System.Collections.BitArray
{
+    public class BitArray {
public void CircularShiftLeft(int times);
public void CircularShiftRight(int times);
public void LogicalShiftLeft(int times);
public void LogicalShiftRight(int times);
}
```

## Usage Examples

``` C#
BitArray A = new BitArray(1024, true);
A.CircularShiftLeft(15);
```

## Risks

No Risks

**Comment by tannergooding** [comment] 2021-01-07 16:18
Closing as a duplicate of https://github.com/dotnet/runtime/issues/46669

**Closed by tannergooding** 2021-01-07 16:18 UTC
Labels: api-suggestion, untriaged
