### ISSUE TITLE
[API Proposal]: ring buffer

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#77718] opened 2022-11-01 13:16 UTC
### Background and motivation

I suggest adding a circular buffer, the implementation of the suggest is below, you can write your own implementation.
https://en.wikipedia.org/wiki/Circular_buffer

### API Proposal

```csharp

   public class QueueRing<T>
    {
        public void Enqueue(T obj)
        {
            lock (_objLock)
            {
                if (_queue.Count > _maxCountBuffer)
                {
                    _queue.TryDequeue(out _);
                }
                _queue.Enqueue(obj);
            }
        }
        public IEnumerable<T> WhereBuffer(Func<T, bool> func)
        {
            lock (_objLock)
            {
                foreach (var item in _queue)
                {
                    if (func(item))
                        yield return item;
                }
            }
        }
        ConcurrentQueue<T> _queue;
        object _objLock;
        int _maxCountBuffer;
        public QueueRing(int maxCountBuffer)
        {
            _maxCountBuffer = maxCountBuffer;
            _objLock = new object();
            _queue = new ConcurrentQueue<T>();
        }
    }
```

### API Usage

-

### Alternative Designs

-

### Risks

-

**Comment by epeshk** [comment] 2022-11-01 13:39
Looks like [BoundedChannel](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Threading.Channels/src/System/Threading/Channels/BoundedChannel.cs#L46) exists for exactly this purpose. Is it suitable for your use case?

https://learn.microsoft.com/en-us/dotnet/core/extensions/channels#bounded-creation-patterns

**Comment by Mr0N** [comment] 2022-11-01 14:36
> `Queue<T>` _is_ a circular buffer. Are you missing any functionality from it?

Automatic removal of objects if the buffer is full

**Comment by eiriktsarpalis** [comment] 2022-11-01 14:38
Duplicate of #30650.

**Closed by eiriktsarpalis** 2022-11-01 14:38 UTC
Labels: api-suggestion, area-System.Collections, needs-further-triage

**Comment by Mr0N** [comment] 2022-11-01 14:40
> Duplicate of #30650.

Why this question has been open for 3 years, can't you write a ring buffer? :)

**Comment by Mr0N** [comment] 2022-11-01 14:48
Or even better, make the method of adding objects virtual in Queue
