### ISSUE TITLE
HttpClient setting up https connection takes 3x times longer in net8 than net7 when using container

### ISSUE THREAD

**Issue by karataliu** [dotnet/runtime#98829] opened 2024-02-21 11:47 UTC
### Describe the Bug
We have a test project that uses HttpClient to test services. The HttpClient has a timeout of 1s.

This has been working well on net7 for months, but when we recently update to net8, it will 70% hit timeout of 1s. And changing timeout to 1.5s can fix the issue.

I tried control some variables, and the outcome is HttpClient is the factor here.

Please check the repro project below for details.

After analyzing the captured dump. there is a obvious difference sometime after 'Change Ciper Spec'

![image](https://github.com/dotnet/dotnet-docker/assets/10071498/a5cd8e5b-b987-4256-8f39-f1b84253caf4)

Left is net7, right is net8.
Checking the gap between No.19 and No.21:
For net7, it is ~0.15s.
For net8, it is ~0.5s
That is a 3x gap. 

I have tested many times, this can constantly repro.
Also this pattern is not that obvious when not running client in a container, so I suppose it's something related to container setup.

Could someone help share where the gap lies in? Thanks.

### Steps to Reproduce
See repro project https://github.com/karataliu/HttpClientTest2

### Output of `docker version`
24.0.2

**Comment by ManickaP** [comment] 2024-02-23 08:22
> Tested `mcr.microsoft.com/dotnet/runtime:7.0-bookworm-slim` can repro the issue, and the performance is just like `mcr.microsoft.com/dotnet/sdk:8.0` and `mcr.microsoft.com/dotnet/runtime:8.0`.

Debian 11 has OpenSSL 1.1 https://packages.debian.org/bullseye/openssl, whereas Debian 12 has newer OpenSSL 3 https://packages.debian.org/bookworm/openssl. There's a known perf regression between those two: https://github.com/openssl/openssl/issues/20286. 

Could you try your test on .NET 8 on Debian 11 (with OpenSSL 1.1)?

**Comment by karataliu** [comment] 2024-02-23 10:08
Tried following:

container image|additional package|net8 app can repro|average duration
-|-|-|-
debian:11| apt install libicu67|N|0.17
debian:12|apt install libicu72 libssl3|N| 0.17


Combine them toghether:
can repro:
- mcr.microsoft.com/dotnet/sdk:8.0
- mcr.microsoft.com/dotnet/runtime:8.0
- mcr.microsoft.com/dotnet/runtime:7.0-bookworm-slim

all debian 12 based

cannot repro:
- mcr.microsoft.com/dotnet/sdk:7.0
- mcr.microsoft.com/dotnet/runtime:7.0
- debian:11
- debian:12

top 3 are debian:11 based, but a raw debian:12 indeed cannot repro

**Comment by ManickaP** [comment] 2024-02-23 15:47
I just tried all of these 3: mcr.microsoft.com/dotnet/sdk:8.0, mcr.microsoft.com/dotnet/runtime:8.0, mcr.microsoft.com/dotnet/runtime:7.0-bookworm-slim and I cannot repro it. It always runs in ~0.17.

I'd suggest deleting the images and containers and re-pull them, to see if that helps. Also you can try this on a different machine to see if it's something in your environment. Lastly, you can turn on our internal logging to see if and eventually where it gets stuck for that 0.5 second. You can do that programmatically and take inspiration from this: https://github.com/dotnet/runtime/blob/main/src/libraries/Common/tests/TestUtilities/TestEventListener.cs

**Comment by wfurt** [comment] 2024-02-25 20:20
most of the TLS perf in OpenSSL 3.x is about locking and concurrent access. I don't the it should be visible in simple test like posted. I'll try to reproduce it next week. 

One thing you can try @karataliu is to copy `openssl.cnf` from old image to new one.

**Comment by wfurt** [comment] 2024-02-26 17:26
I cannot get repro either. The actual times fluctuates e.g. if we really want to proceed we would probably need to craft real benchmark using Benchmark.net. 

Note that https://github.com/dotnet/runtime/issues/98797#issuecomment-1964553152 also outlines differences between 7.0 and 8.0 e.g.  Debian 11 and Debian 12. Since the .NET image piggyback on underlying Debian it may be worth to report it to Debian. 

Alternatively use different distribution as base for .NET 8.0.

**Comment by wfurt** [comment] 2024-02-26 17:30
Any more thoughts on this @rzikm ? I think after the cipher change the client would see handshake completed. What jumps at me would certificate validation that can take some time. In my case the server is using  self-signed RSA 2048 key without any AIA.

**Comment by karataliu** [comment] 2024-02-27 09:29
> mcr.microsoft.com/dotnet/sdk:8.0


> I just tried all of these 3: mcr.microsoft.com/dotnet/sdk:8.0, mcr.microsoft.com/dotnet/runtime:8.0, mcr.microsoft.com/dotnet/runtime:7.0-bookworm-slim and I cannot repro it. It always runs in ~0.17.
> 
> I'd suggest deleting the images and containers and re-pull them, to see if that helps. Also you can try this on a different machine to see if it's something in your environment. Lastly, you can turn on our internal logging to see if and eventually where it gets stuck for that 0.5 second. You can do that programmatically and take inspiration from this: https://github.com/dotnet/runtime/blob/main/src/libraries/Common/tests/TestUtilities/TestEventListener.cs

Thanks.

Can repro on latest image:
```
$ docker pull mcr.microsoft.com/dotnet/sdk:8.0
$ docker run -ti mcr.microsoft.com/dotnet/sdk:8.0 bash
root@edbc4e9c244f:/# export URI=https://<>:5001
root@adc58b342787:/# /net8
00:00:00.6196374
root@adc58b342787:/# /net8
00:00:00.4571024
root@adc58b342787:/# /net8
00:00:00.5078147
root@adc58b342787:/# /net8
00:00:00.5387380
root@adc58b342787:/# /net8
00:00:00.4506109
root@adc58b342787:/# /net8
00:00:00.9244355
```

Didn't quite get how that TestEventListener works. Is there a easy way to turn on metric on httpclient? Could you help suggest some code snip?

**Comment by karataliu** [comment] 2024-02-27 14:25
> I cannot get repro either. The actual times fluctuates e.g. if we really want to proceed we would probably need to craft real benchmark using Benchmark.net.
> 
> Note that [#98797 (comment)](https://github.com/dotnet/runtime/issues/98797#issuecomment-1964553152) also outlines differences between 7.0 and 8.0 e.g. Debian 11 and Debian 12. Since the .NET image piggyback on underlying Debian it may be worth to report it to Debian.


Thanks, but that couldn't explain why debian-12 raw image cannot repro?


With 1.0s timeout, on net7 image the pass rate is ~100%, one net8 image our test pass rate has dropped to ~70%, but with 1.5s it becomes ~100% again.
Those test runs on random build agents, so it is supposed to be already verified by many different machines.

**Comment by wfurt** [comment] 2024-02-27 16:53
AFAIK there is nothing magic about the images. Just base line + .NET. You can probably look at the differences for yourself.

**Comment by MichaelSimons** [comment] 2024-02-27 17:01
> AFAIK there is nothing magic about the images. Just base line + .NET. You can probably look at the differences for yourself.

That is correct.

[8.0 bookworm-slim runtime-deps](https://github.com/dotnet/dotnet-docker/blob/main/src/runtime-deps/8.0/bookworm-slim/amd64/Dockerfile)
[8.0 bookworm-slim runtime](https://github.com/dotnet/dotnet-docker/blob/main/src/runtime/8.0/bookworm-slim/amd64/Dockerfile)

[7.0 bullseye-slim runtime-deps](https://github.com/dotnet/dotnet-docker/blob/main/src/runtime-deps/6.0/bullseye-slim/amd64/Dockerfile)
[7.0 bullseye-slim runtime](https://github.com/dotnet/dotnet-docker/tree/main/src/runtime/7.0/bullseye-slim/amd64)

[7.0 bookworm-slim runtime-deps](https://github.com/dotnet/dotnet-docker/blob/main/src/runtime-deps/6.0/bookworm-slim/amd64/Dockerfile)
[7.0 bookworm-slim runtime](https://github.com/dotnet/dotnet-docker/tree/main/src/runtime/7.0/bookworm-slim/amd64)

Comparing 7.0 bookworm-slim to 7.0 bullseye-slim shows the only difference besides the base image is libssl1.1 vs 3 and libicu67 vs 72

**Comment by karataliu** [comment] 2024-02-28 01:08
> AFAIK there is nothing magic about the images. Just base line + .NET. You can probably look at the differences for yourself.
yeah, i have no question on that. Just want to explore why the test result happens.

Any suggestion on follow up on investigation? I suppose instrument should be helpful.

Also for people who didn't repro, could you share your setup?

For my repro:
1. the server runs on host
2. the net8 binary is built by `dotnet publish -c Release -r linux-x64 -p:PublishSingleFile=true --self-contained net8.csproj` and copied to each runtime

**Comment by rzikm** [comment] 2024-02-28 15:32
> Any more thoughts on this @rzikm ? I think after the cipher change the client would see handshake completed. What jumps at me would certificate validation that can take some time. In my case the server is using self-signed RSA 2048 key without any AIA.

The message which seems to get delayed is the client-side Finish, which is just after building server certificate chain and validation,  the AIA seems reasonable suspect, although I don't know that particular part would repro on one distro and not on another.

I also cannot reproduce the issue on any of the "reproducing" images (using the contoso.com certificate we use for unit tests, as well as the default dev certificate used by aspnet.core), I had both client and server run inside the image.

@karataliu Are you using some custom certificate perhaps? If so, would it be possible to generate a cert which reproduces the issue and share it with us to see if the issue reproduces? Also, if it's AIA, you can check if any of these changes eliminate the gap

```cs
hch.CheckCertificateRevocationList = false;
```

```cs
var hc = new HttpClient(new SocketsHttpHandler()
{
    SslOptions = {
        CertificateChainPolicy = new X509ChainPolicy {
            DisableCertificateDownloads = true,
            RevocationMode = X509RevocationMode.NoCheck,
        },
        RemoteCertificateValidationCallback = delegate { return true; }
    }
});
```

> For my repro: the server runs on host

on host is... windows (with docker runing in WSL2 mode)? how are you running the image such that you can reach the server from inside the image?

**Comment by karataliu** [comment] 2024-02-28 23:55
> I also cannot reproduce the issue on any of the "reproducing" images (using the contoso.com certificate we use for unit tests, as well as the default dev certificate used by aspnet.core), I had both client and server run inside the image.
> 
> @karataliu Are you using some custom certificate perhaps? If so, would it be possible to generate a cert which reproduces the issue and share it with us to see if the issue reproduces? Also, if it's AIA, you can check if any of these changes eliminate the gap

All in the repro repository: https://github.com/karataliu/HttpClientTest2/tree/dev/Server
The only related https config is: https://github.com/karataliu/HttpClientTest2/blob/dev/Server/Properties/launchSettings.json
```
"applicationUrl": "https://0.0.0.0:5001
```
I didn't generate the cert, but believe the aspnet generated it:
server log:
```
warn: Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer[8]
      The ASP.NET Core developer certificate is not trusted. For information about trusting the ASP.NET Core developer certificate, see https://aka.ms/aspnet/https-trust-dev-cert.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://0.0.0.0:5001
```

via curl:
```
* Server certificate:
*  subject: CN=localhost
*  start date: Oct 14 06:40:07 2023 GMT
*  expire date: Oct 14 06:40:07 2024 GMT
*  issuer: CN=localhost
* ```




If someone is not using the repro repository, might I know what steps did you try in repro? Basically I have verified simply accessing any internet https WON'T repro. But with above repro it can.

**Comment by karataliu** [comment] 2024-02-29 00:00
> on host is... windows (with docker runing in WSL2 mode)? how are you running the image such that you can reach the server from inside the image?

Host is a ubuntu VM. The server listens at 0.0.0.0, and client access server bridge endpoint (interface br-*). All the repro steps are using same config.

**Comment by CarnaViire** [comment] 2024-03-13 23:42
I was able to repro it with a plain Deb 12 base image. I've used the GH repro app as a base, with some modifications (e.g. server is Ubuntu 22 in container as well). I've also tried @rzikm's suggestions to see whether it will influence anything or not (it didn't). All the dockerfiles and scripts etc are in https://github.com/CarnaViire/repro-karataliu-HttpClientTest2/tree/test

As far as I understand, it is most possibly openssl's fault; but I'll let @rzikm comment. I've verified that most of the time is spent in cert validation (that we're going to ignore in the callback anyway...). Disabling the name check for the self-signed cert (`CertificateChainPolicy.VerificationFlags = X509VerificationFlags.IgnoreInvalidName`) cuts half of the cost (I assume because it essentially removes one of the PInvokes to OpenSSL). Deb 11 is still faster.

<details>
<summary>Some numbers</summary>

Debian 12, SocketsHttpHandler:
```
net7.0 avg: 1608 ms; max: 2362 ms
net8.0 avg: 1396 ms; max: 2205 ms
```

Debian 12, SocketsHttpHandler + IgnoreCertName:
```
net7.0 avg: 639 ms; max: 754 ms
net8.0 avg: 627 ms; max: 756 ms
```

Debian 11, SocketsHttpHandler:
```
net7.0 avg: 220 ms; max: 280 ms
net8.0 avg: 205 ms; max: 364 ms
```

Debian 11, SocketsHttpHandler + IgnoreCertName:
```
net7.0 avg: 140 ms; max: 159 ms
net8.0 avg: 117 ms; max: 127 ms
```
</details>

**Comment by rzikm** [comment] 2024-03-14 13:45
I might be doing something wrong, but I still can't reproduce this

```
> .\run-docker-compose.ps1 -Distro debian-12 -Handler "SocketsHttpHandler"
...
client-1  |
client-1  | net7.0 avg: 184 ms; max: 193 ms
client-1  | net8.0 avg: 171 ms; max: 175 ms
```

Can you check openssl version that gets installed? in my case it is `OpenSSL 3.0.11 19 Sep 2023 (Library: OpenSSL 3.0.11 19 Sep 2023)`

If we suspect its OpenSSL, we can try forcing older version by setting `CLR_OPENSSL_VERSION_OVERRIDE=1.1`. To install libssl1.1 we need to pull the package manually:

```
curl -LO http://ftp.us.debian.org/debian/pool/main/o/openssl/libssl1.1_1.1.1w-0+deb11u1_amd64.deb
apt-get install ./libssl1.1_1.1.1w-0+deb11u1_amd64.deb
```

**Comment by wfurt** [comment] 2024-03-14 16:45
maybe you can check the set @CarnaViire  has @rzikm. It seems like this may be sensitive to environment. It is interesting that name validation would have impact. I'm not sure if any of this would do name resolution...?

**Comment by CarnaViire** [comment] 2024-03-15 01:22
Hmmm the one thing that heavily influenced the numbers for me (though, for both 11 and 12) was... Windows Defender 😅 After adding a bunch of exclusions, my numbers became better. The difference was still there (~x1.5-x2 or smth), but it indeed seem to be mitigated by forcing OpenSSL 1.1 on Deb 12. @karataliu can you verify it as well pls? (the repro [fork](https://github.com/CarnaViire/repro-karataliu-HttpClientTest2/tree/test) now has updated scripts etc)

```
> .\run-docker-compose.ps1 -Distro debian-11 -Handler "SocketsHttpHandler"
...
client-1  | net7.0 avg: 125 ms; max: 144 ms
client-1  | net8.0 avg: 115 ms; max: 125 ms
```

```
> .\run-docker-compose.ps1 -Distro debian-12 -Handler "SocketsHttpHandler"
...
client-1  | net7.0 avg: 243 ms; max: 272 ms
client-1  | net8.0 avg: 233 ms; max: 256 ms
```

```
> .\run-docker-compose.ps1 -Distro debian-12 -Handler "SocketsHttpHandler" -ForceOpenSSL11
...
client-1  | net7.0 avg: 139 ms; max: 180 ms
client-1  | net8.0 avg: 124 ms; max: 140 ms
```

<details>
<summary>OpenSSL versions</summary>

Deb 11

```
--OpenSSL--
Version: 1.1.1w-0+deb11u1
libssl.so.1.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libssl.so.1.1
```

Deb 12

```
--OpenSSL--
Version: 1.1.1w-0+deb11u1
libssl.so.1.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libssl.so.1.1
Version: 3.0.11-1~deb12u2
libssl.so.3 (libc6,x86-64) => /lib/x86_64-linux-gnu/libssl.so.3
```

</details>

BTW @wfurt I initially was suspicious as well, but no, name resolution is negligible in comparison with the cert validation stuff. E.g.,
- **3ms** (ResolutionStart to ResolutionStop)
- **280ms** (RemoteCertificate to RemoteCertificateError)
- vs total **418ms** (RequestStart to RequestStop)

<details>
<summary>logs</summary>
```
00:57:49.6862899[RequestStart] scheme: https, host: server, port: 5001, pathAndQuery:....
...
00:57:49.7306788[ResolutionStart] hostNameOrAddress: server
00:57:49.7342958[ResolutionStop]
...
00:57:49.7588694[HandshakeStart] isServer: False, targetHost: server
...
00:57:49.7992966[RemoteCertificate] remoteCertificate: [Version]   V3  [Subject]   CN=localhost   Simple Name: localhost   DNS Name: localhost  [Issuer]....
00:57:50.0798391[RemoteCertificateError] sslStreamHash: 11429296, message: Remote certificate has errors:
...
00:57:50.0812457[HandshakeStop] protocol: 12288
...
00:57:50.1044661[RequestStop] statusCode: 404
```

</details>

**Comment by wfurt** [comment] 2024-03-15 16:46
If we think the validation is culprit, perhaps you can reproduce it with just `X509Chain.Build` @CarnaViire. And is your server  using self-signed cert or if not, does it send the chain?

**Comment by CarnaViire** [comment] 2024-03-15 17:31
The server is the same plain `dotnet new web` Kestrel with no configs as it was in the initial repro @karataliu had. Thus, the cert is a default ([`KestrelServerOptions.ApplyDefaultCertificate()`](https://github.com/dotnet/aspnetcore/blob/6b7a6a94fb3ff2c004f354dbfe662644dac0ce26/src/Servers/Kestrel/Core/src/KestrelServerOptions.cs#L315)) self-signed cert auto-generated ([`CertificateManager.CreateAspNetCoreHttpsDevelopmentCertificate()`](https://github.com/dotnet/aspnetcore/blob/6b7a6a94fb3ff2c004f354dbfe662644dac0ce26/src/Shared/CertificateGeneration/CertificateManager.cs#L602)) by Kestrel.

> If we think the validation is culprit, perhaps you can reproduce it with just X509Chain.Build

@karataliu will you be able to try it in your environment? Would you need help with writing a sample app?

**Comment by karataliu** [comment] 2024-03-18 06:56
I can confirm using libssl 1.1 in debian 12 has very obvious effect in reducing the time.
```
root@7e427d45b979:/# /net8
00:00:00.5293588
root@7e427d45b979:/# /net8
00:00:00.4826952
root@7e427d45b979:/# /net8
00:00:00.4759067
root@7e427d45b979:/# /net8
00:00:00.4927925
root@7e427d45b979:/# export CLR_OPENSSL_VERSION_OVERRIDE=1.1
root@7e427d45b979:/# /net8
00:00:00.2923880
root@7e427d45b979:/# /net8
00:00:00.2669526
root@7e427d45b979:/# /net8
00:00:00.3079818
root@7e427d45b979:/# /net8
00:00:00.2995710
```

In client side we already skipped validation: `ServerCertificateCustomValidationCallback = (_, _, _, _) => true`
https://github.com/karataliu/HttpClientTest2/blob/dev/HttpClientTest/Program.cs#L9

Is there any reason that openssl is still involved?

**Comment by CarnaViire** [comment] 2024-03-19 11:14
Triage: the issue is external and is caused by OpenSSL 3 perf regression.

Closing as answered.

**Closed by CarnaViire** 2024-03-19 11:14 UTC
Labels: area-System.Net.Http, untriaged

**Comment by karataliu** [comment] 2024-03-20 10:04
Thanks all for the investigation.

per current image list:
https://github.com/dotnet/dotnet-docker/blob/main/README.runtime.md#linux-amd64-tags

bookworm/jammy all uses openssl3
cbl-mariner2.0 uses openssl1.1

If someone hit the issue, please consider using openssl1.1 based images.
