### ISSUE TITLE
string.StartsWith returns `True` when comparing with some control characters

### ISSUE THREAD

**Issue by danipen** [dotnet/runtime#103116] opened 2024-06-06 09:42 UTC
### Description

When performing a `string.StartsWith(string value)` and the value is the Escape control character (ASCII 27), this function returns `True`.

### Reproduction Steps

```csharp
string escapeSequence = "\u001B"; // ESC - ASCII char 27
Console.WriteLine("something".ToUpper().StartsWith(escapeSequence));

True
```

### Expected behavior

The code snippet returns `False`

### Actual behavior

The code snippet returns `True`

### Regression?

Yes, .NET Framework 4.8 and Roslyn 4.8 compilers seem to do it ok.

**Comment by huoyaoyuan** [comment] 2024-06-06 09:46
Duplicate of #99279 and so on.

**Closed** 2024-06-06 09:49 UTC
Labels: area-System.Globalization, untriaged

**Comment by tarekgh** [comment] 2024-06-06 15:10
@danipen please look at the comment https://github.com/dotnet/runtime/issues/72992#issuecomment-1198334822 for more explanation.
