### ISSUE TITLE
.Net 7 Distributed Transaction - scope.Dispose() block process

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#81469] opened 2023-02-01 10:21 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Net-7-Distributed-Transaction---scopeD/10256044)._

---
[severity:I'm unable to use this version]
Hello,

like described in Q&A, we face the problem with the new feature in .Net 7, distributed transactions.
The transaction works, datas are commited on the database (SQL Server) after "scope.Completed()", however when the transactionscope is disposed we lost the process and everything is locked.

https://learn.microsoft.com/en-us/answers/questions/1118409/net-7-distributed-transaction-scope-dispose()-bloc?page=1

We need a fix for that bug, or  distributed transactions in .Net 7 are not useable, thx.

---
#### Feedback Bot on 1/19/2023, 03:03 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by roji** [comment] 2023-02-01 10:49
Which SqlClient are you using, Microsoft.Data.SqlClient or System.Data.SqlClient, and which precise version? If it's Microsoft.Data.SqlClient with anything below the recently-released 5.1.0, please update to 5.1.0 and try again (https://github.com/dotnet/SqlClient/issues/1800).

**Comment by JanLanger84** [comment] 2023-02-08 12:31
We use Microsoft.Data.SqlClient. A manual installation of version 5.1.0 via nuget solved the problem.

Thanks!

**Comment by roji** [comment] 2023-02-08 17:22
Great to hear, thanks!

**Comment by roji** [comment] 2023-02-08 17:23
Duplicate of dotnet/SqlClient#1800

**Closed by roji** 2023-02-08 17:22 UTC
Labels: area-System.Transactions, untriaged
