### ISSUE TITLE
Let System.ConsoleKeyInfo able to represent keypress in the Unicode world

### ISSUE THREAD

**Issue by WenceyWang** [dotnet/runtime#51085] opened 2021-04-11 18:17 UTC
## Background and Motivation

The design of keyboard key code and key char is dated back to IBM PC and we have code pages to make things work.

Currently, we have much more complicated keyboards, some of them can type in script languages, some of them can directly input emoji.

But `System.ConsoleKeyInfo` uses a `char` to store key char. Which caused a lot of long hanging serious issue:

https://github.com/dotnet/runtime/issues/27828 is only one of the examples.

These problems can be easily fixed by adding a new property.

## Proposed API

```diff
namespace System
{
  public struct ConsoleKeyInfo {
+    public ReadOnlySpan<System.Text.Rune> KeyCharacters { get; }
}
```

## Usage Examples

``` C#
StringBuilder inputText = new StringBuilder ( );

while ( true )
{
	ConsoleKeyInfo key = Console . ReadKey ( true );

	switch ( key.Key )
	{
		case ConsoleKey.Escape:
		case ConsoleKey.Enter:
			// Some Logic
			break;
		default:
			foreach ( Rune rune in key.KeyCharacters )
			{
				inputText.Append ( rune );
			}
			break;
	}
	
}

```

## Alternative Designs

The property type can also be `ReadOnlySpan<char>` or even `string`. The name can also be different.

## Risks
`ConsoleKeyInfo` is `[Serializable]`.

**Comment by GrabYourPitchforks** [comment] 2021-04-13 02:20
For reference, there's a discussion going on at https://github.com/dotnet/runtime/issues/27828 on whether a `string`-returning API needs to be added, or whether callers can keep querying the _KeyChar_ property over and over in a loop, stitching together the key presses and building up the input string.

**Comment by adamsitnik** [comment] 2023-11-13 18:41
Closing as a duplicate of #27828

**Closed** 2023-11-13 18:43 UTC
Labels: api-suggestion, area-System.Console
