### ISSUE TITLE
DiagnosticsHandler: System.FormatException: The format of value 'MyApp%2F2022.1.0a5+(Windows%3B+U%3B+Windows+NT+10.0%3B+en)' is invalid.    at System.Net.Http.Headers.NameValueHeaderValue.CheckValueFormat(String value)

### ISSUE THREAD

**Issue by GitMyCode** [dotnet/runtime#57230] opened 2021-08-11 18:38 UTC
### Description

I currently use ActivitySource and set some data in a baggage that i then use in a custom httpHandler. Everything is fine and all.
but when i add some baggage i get sometime this format error:

```
System.FormatException: The format of value 'MyApp%2F2022.1.0a5+(Windows%3B+U%3B+Windows+NT+10.0%3B+en)' is invalid.
   at System.Net.Http.Headers.NameValueHeaderValue.CheckValueFormat(String value) in /_/src/libraries/System.Net.Http/src/System/Net/Http/Headers/NameValueHeaderValue.cs:line 359
   at System.Net.Http.DiagnosticsHandler.InjectHeaders(Activity currentActivity, HttpRequestMessage request) in /_/src/libraries/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs:line 315
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs:line 74
```
it turn out that by default on httpClient there is an Handler `DiagnosticHandler` that is added then this one fail while trying to create an `Request-Context`
```
 public HttpClientHandler()
    {
      this._underlyingHandler = new SocketsHttpHandler();
      if (DiagnosticsHandler.IsGloballyEnabled())
        this._diagnosticsHandler = new DiagnosticsHandler((HttpMessageHandler) this._underlyingHandler);
      this.ClientCertificateOptions = ClientCertificateOption.Manual;
    }
```  
And in that handler it does what was merge here i think: https://github.com/dotnet/corefx/pull/36203/files
```
  baggage.Append(WebUtility.UrlEncode(item.Key)).Append('=').Append(WebUtility.UrlEncode(item.Value)).Append(',');
```

How can i turn this thing off or what should i do to my baggage data to prevent it to explose at the next http request ?

**Comment by MihaZupan** [comment] 2021-08-11 18:50
This is a duplicate of https://github.com/dotnet/runtime/issues/57230.

To turn off the `DiagnosticsHandler`, see https://github.com/dotnet/runtime/issues/35337#issuecomment-879381782

**Closed by MihaZupan** 2021-08-11 18:50 UTC
Labels: area-System.Net.Http, untriaged

**Comment by MihaZupan** [comment] 2021-08-11 18:55
Note that disabling the handler will also mean no Activity is being created per request.

If you want to avoid just the specific encoding issue, you can either implement a custom DistributedContextPropagator for 6.0, or avoid using problematic characters in the baggage until #57230 is fixed.

**Comment by GitMyCode** [comment] 2021-08-11 20:26
thanks a lot! 
And what would be the problematic characters?
