### ISSUE TITLE
 .net core runtime does not load two version of same assembly

### ISSUE THREAD

**Issue by indrajitjadeja** [dotnet/runtime#81593] opened 2023-02-03 13:29 UTC
### Description

I was trying to load two version of same assembly using deps.json file. but as per traces, runtime can only perform probing for one version, and it does nothing for another version.

### Reproduction Steps

I have used System.Text.Json assembly for deserialization of json string.
I have created two .Net 6.0 libraries CoreLibraryA and CoreLibraryB.
in which CoreLibraryA depends on System.Text.Json 7.0.0
and CoreLibraryB depends on System.Text.Json 6.0.0
I have created one .Net 6 Console test app which uses both CoreLibraryA and CoreLibraryB libraries.

Upon build of "CoreTest" console app, I have modified runtimeconfig.json and deps.json file in output directory as below:

CoreTest.runtimeconfig.json
`{
  "runtimeOptions": {
    "tfm": "net6.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "6.0.0"
    },
    "additionalProbingPaths": "libs"
  }
}`

CoreTest.deps.json

`"targets": {
   ".NETCoreApp,Version=v6.0": {
      "System.Text.Json/7.0.0": {
        "dependencies": {
          "System.Runtime.CompilerServices.Unsafe": "6.0.0",
          "System.Text.Encodings.Web": "7.0.0"
        },
        "runtime": {
          "7.0.0/System.Text.Json.dll": {
            "assemblyVersion": "7.0.0.0",
            "fileVersion": "7.0.22.51805"
          }
        }
      },
      "System.Text.Json/6.0.0": {
        "dependencies": {
          "System.Runtime.CompilerServices.Unsafe": "6.0.0",
          "System.Text.Encodings.Web": "6.0.0"
        },
        "runtime": {
          "6.0.0/System.Text.Json.dll": {
            "assemblyVersion": "6.0.0.0",
            "fileVersion": "6.0.1322.58009"
          }
        }
       }
   }
},
"libraries": {
 "System.Text.Json/7.0.0": {
      "type": "package",
      "serviceable": true,
      "sha512": "sha512-DaGSsVqKsn/ia6RG8frjwmJonfos0srquhw09TlT8KRw5I43E+4gs+/bZj4K0vShJ5H9imCuXupb4RmS+dBy3w==",
      "path": "/",
      "hashPath": "system.text.json.7.0.0.nupkg.sha512"
    },
    "System.Text.Json/6.0.0": {
      "type": "package",
      "serviceable": true,
      "sha512": "sha512-DaGSsVqKsn/ia6RG8frjwmJonfos0srquhw09TlT8KRw5I43E+4gs+/bZj4K0vShJ5H9imCuXupb4RmS+dBy3w==",
      "path": "/",
      "hashPath": "system.text.json.6.0.0.nupkg.sha512"
    }
}`

Then I ran the CoreTest.exe, druing runtime .net core only try to load System.Text.Json 7.0.0 version and skips the loading of System.Text.Json 6.0.0

**Traces**
Adding runtime asset 7.0.0/System.Text.Json.dll assemblyVersion=7.0.0.0 fileVersion=7.0.22.51805 from System.Text.Json/7.0.0
Adding runtime asset 6.0.0/System.Text.Json.dll assemblyVersion=6.0.0.0 fileVersion=6.0.1322.58009 from System.Text.Json/6.0.0
Reconciling library System.Text.Json/7.0.0
Parsed runtime deps entry 4 for asset name: System.Text.Json from package: System.Text.Json, library version: 7.0.0, relpath: 7.0.0/System.Text.Json.dll, assemblyVersion 7.0.0.0, fileVersion 7.0.22.51805
Reconciling library System.Text.Json/6.0.0
Parsed runtime deps entry 5 for asset name: System.Text.Json from package: System.Text.Json, library version: 6.0.0, relpath: 6.0.0/System.Text.Json.dll, assemblyVersion 6.0.0.0, fileVersion 6.0.1322.58009
Processing TPA for deps entry [System.Text.Json, 7.0.0, 7.0.0/System.Text.Json.dll]
  Considering entry [System.Text.Json/7.0.0/7.0.0/System.Text.Json.dll], probe dir [], probe fx level:0, entry fx level:0
    Local path query did not exist C:\Users\Indrajit\Downloads\AnalysisProjects\CoreTest\CoreTest\bin\Debug\net6.0\System.Text.Json.dll
    Skipping... not found in deps dir 'C:\Users\Indrajit\Downloads\AnalysisProjects\CoreTest\CoreTest\bin\Debug\net6.0\'
    Skipping... not found in probe dir ''
  Considering entry [System.Text.Json/7.0.0/7.0.0/System.Text.Json.dll], probe dir [C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.13], probe fx level:1, entry fx level:0
    Skipping... not found in deps json.
    Skipping... not found in probe dir 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.13'
  Considering entry [System.Text.Json/7.0.0/7.0.0/System.Text.Json.dll], probe dir [C:\Users\Indrajit\Downloads\AnalysisProjects\CoreTest\CoreTest\bin\Debug\net6.0\libs], probe fx level:-1, entry fx level:0
    Relative path query exists C:\Users\Indrajit\Downloads\AnalysisProjects\CoreTest\CoreTest\bin\Debug\net6.0\libs\\7.0.0\System.Text.Json.dll
    Probed package dir and matched 'C:\Users\Indrajit\Downloads\AnalysisProjects\CoreTest\CoreTest\bin\Debug\net6.0\libs\\7.0.0\System.Text.Json.dll'
Adding tpa entry: C:\Users\Indrajit\Downloads\AnalysisProjects\CoreTest\CoreTest\bin\Debug\net6.0\libs\\7.0.0\System.Text.Json.dll, AssemblyVersion: 7.0.0.0, FileVersion: 7.0.22.51805
**Processing TPA for deps entry [System.Text.Json, 6.0.0, 6.0.0/System.Text.Json.dll]**
Processing TPA for deps entry [Microsoft.NETCore.App.Runtime.win-x64, 6.0.13, System.Private.CoreLib.dll]
  Considering entry [Microsoft.NETCore.App.Runtime.win-x64/6.0.13/System.Private.CoreLib.dll], probe dir [], probe fx level:0, entry fx level:1

As per above traces probing should be done after highlighted line and runtime should have loaded the System.Text.Json 6.0.0 but instead it has done nothing and started processing for another assembly.

### Expected behavior

Two version of same assembly should be loaded by runtime.
.Net framework does load two version of same assemblies when it is added to GAC.

### Actual behavior

.Net runtime only loads one version of assembly even if the dependencies are mentioned in manifest file (deps.json)

### Regression?

.Net framework does load two version of same assemblies when it is added to GAC.

### Configuration

.Net 6
Windows 11
x64
not specific to above configurations it replicates on windows 10

**Comment by vitek-karas** [comment] 2023-02-06 11:41
The assembly loading behavior is different in .NET 6+ from .NET Framework and it is by design. Instead of various hidden loading behaviors .NET 6 is much more explicit. It supports `AssemblyLoadContext` (ALC) explicitly, each such ALC can only load one version of any given assembly. If your application needs more than one version, it can do so by loading them into different ALCs.

See https://learn.microsoft.com/en-us/dotnet/core/dependency-loading/overview for the description of the system.
https://learn.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support is a guide to building an application with plugins, where each plugin can load a different version of its dependencies. It might not apply directly to your case, but the general principles should be similar.

I would add that the `.deps.json` file is considered mostly an implementation detail between the .NET SDK and the .NET runtime. Modifying it manually is a very advanced scenario which is generally unsupported (although we obviously try to not break existing behaviors). It does not support specifying two versions of the same dependency (since SDK would never do that) and thus the behavior is basically undefined when it happens.

**Comment by agocke** [comment] 2023-08-09 16:02
Closing as by design -- the fix is loading into separate AssemblyLoadContexts

**Closed by agocke** 2023-08-09 16:02 UTC
Labels: area-AssemblyLoader-coreclr, untriaged
