### ISSUE TITLE
Console apps do not read trace listeners from app.config

### ISSUE THREAD

**Issue by bgavrilMS** [dotnet/runtime#48105] opened 2021-02-10 13:39 UTC
### Description

.NET Core 3.1 / .NET 5 console apps do not read trace listeners defined in app.config

### Repro steps

1. Create a new console app and add the following code: 

```csharp
        static void Main(string[] args)
        {
            Console.WriteLine(Trace.Listeners[0].GetType());
            Console.ReadLine();
        }
```
2. Also add a simple app config using Visual Studio and configre a TextWriter listener.

```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <system.diagnostics>
    <trace autoflush="true" indentsize="4">
      <listeners>
        <add name="myListener" type="System.Diagnostics.TextWriterTraceListener" initializeData="TextWriterOutput.txt" />
        <remove name="Default" />
      </listeners>
    </trace>
  </system.diagnostics>
</configuration>
```
3. Run this app using .NET classic, e.g. net471. Output `System.Diagnostics.TextWriterTraceListener`
4. Run this app using netcoreapp3.1 or net5.

Expected Output: `System.Diagnostics.TextWriterTraceListener`
Actual Output: `System.Diagnostics.DefaultTraceListener` 

Note: I tried running the netcore console app from Visual Studio, via `dotnet exec console_app.dll` and by executing the .exe, and they all result in the same thing. Have not tried in other apps.

Bin/debug files shows the config is there...

![image](https://user-images.githubusercontent.com/12273384/107517129-3e10db00-6ba5-11eb-8d04-45e8310a5280.png)

### Configuration

* Which version of .NET is the code running on? net471, netcoreapp3.1, net5
* What OS and version, and what distro if applicable? Win 10 20H2
* What is the architecture (x64, x86, ARM, ARM64)? x64

### Regression?

Works in .NET Framework!

**Comment by jkotas** [comment] 2021-02-10 15:47
Duplicate of #23937

**Closed by jkotas** 2021-02-10 15:47 UTC
Labels: area-System.Diagnostics.Tracing, untriaged
