### ISSUE TITLE
TypeLoadException when using value types with empty generic T where T causes a Type cycle

### ISSUE THREAD

**Issue by jarnmo** [dotnet/runtime#72039] opened 2022-06-06 11:42 UTC
_UPDATE (Steve Harter): I added a simple repro below. I believe this should result in CS0523_

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Blazor (server) app throws `System.Reflection.ReflectionTypeLoadException: 'Unable to load one or more of the requested types.
Could not load type 'TypeLoadError.MyStruct` on start up when MyStruct has a generic struct field of a struct that has a field of type MyStruct.

### Expected Behavior

App should start without errors.

### Steps To Reproduce

1. Clone https://github.com/jarnmo/BlazorTypeLoadError
2. Run

Or 

1. Copy https://github.com/jarnmo/BlazorTypeLoadError/blob/master/Structs.cs
2. Set One as a Parameter of a component
3. Run

ReflectionTypeLoadException should be thrown at Program.cs:25 `app.MapFallbackToPage("/_Host");`

### Exceptions (if any)

System.Reflection.ReflectionTypeLoadException: 'Unable to load one or more of the requested types.
Could not load type 'TypeLoadError.One' from assembly 'TypeLoadError, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

### .NET Version

6.0.300

### Anything else?

Tested using VS 2022

**Comment by tfenise** [comment] 2022-07-12 18:04
#6924

**Comment by lambdageek** [comment] 2022-07-13 13:31
> Verified as issue. Simple repro:

(Checked that .NET Preview 6 MonoVM doesn't have this issue - no TLE from the above repro)

**Comment by teo-tsirpanis** [comment] 2022-07-27 11:26
Duplicate of #6924.

**Closed by teo-tsirpanis** 2022-07-27 11:26 UTC
Labels: area-TypeSystem-coreclr, runtime-coreclr
