### ISSUE TITLE
[9.0] System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#106493] opened 2024-08-15 19:22 UTC
## Build Information

Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=776432
Build error leg or test failing: ` System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest` in `Libraries Test Run release coreclr windows x64 Debug`

## Error Message

```json
{
  "ErrorMessage" : "at System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest(Int32 ioCompletionPortCount)",
  "BuildRetry" : false,
  "ExcludeConsoleLog" : false
}
```

- PR: https://github.com/dotnet/runtime/pull/106429
- Queue: `Libraries Test Run release coreclr windows x64 Debug`
- Job result: https://dev.azure.com/dnceng-public/public/_build/results?buildId=776432&view=logs&j=cb131f87-d5af-5ecc-6e5f-6dc86994859c&t=6a61743b-4295-56b4-b08a-082e36892f8d&l=117
- Log file: https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-pull-106429-merge-8a077d37470941fb90/System.Threading.ThreadPool.Tests/1/console.bb045b5b.log?helixlogtype=result
- Output:
```
----- start Thu 08/15/2024  2:15:18.45 ===============  To repro directly: =====================================================
pushd C:\h\w\A1E808D0\w\B00D09BE\e\
"C:\h\w\A1E808D0\p\dotnet.exe" exec --runtimeconfig System.Threading.ThreadPool.Tests.runtimeconfig.json --depsfile System.Threading.ThreadPool.Tests.deps.json xunit.console.dll System.Threading.ThreadPool.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================

C:\h\w\A1E808D0\w\B00D09BE\e>"C:\h\w\A1E808D0\p\dotnet.exe" exec --runtimeconfig System.Threading.ThreadPool.Tests.runtimeconfig.json --depsfile System.Threading.ThreadPool.Tests.deps.json xunit.console.dll System.Threading.ThreadPool.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Threading.ThreadPool.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Threading.ThreadPool.Tests (found 48 test cases)
  Starting:    System.Threading.ThreadPool.Tests (parallel test collections = on [2 threads], stop on fail = off)
    System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest(ioCompletionPortCount: 7) [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Half-way through waiting for remote process.
      Memory load: 17
      
      Image Name                     PID Services                                    
      ========================= ======== ============================================
      svchost.exe                    596 BrokerInfrastructure, DcomLaunch, LSM,      
                                         PlugPlay, Power, SystemEventsBroker         
      svchost.exe                    628 RpcEptMapper, RpcSs                         
      svchost.exe                    740 AppIDSvc, Dhcp, EventLog, lmhosts,          
                                         vmictimesync, Wcmsvc                        
      svchost.exe                    776 AeLookupSvc, Appinfo, BITS, CertPropSvc,    
                                         gpsvc, iphlpsvc, LanmanServer, ProfSvc,     
                                         sacsvr, Schedule, SENS, SessionEnv,         
                                         ShellHWDetection, Themes, Winmgmt           
      svchost.exe                    840 EventSystem, FontCache, netprofm, nsi,      
                                         W32Time, WinHttpAutoProxySvc                
      svchost.exe                    936 CryptSvc, Dnscache, LanmanWorkstation,      
                                         NlaSvc, WinRM                               
      svchost.exe                    376 BFE, DPS, MpsSvc, pla                       
      svchost.exe                   1104 AppHostSvc                                  
      svchost.exe                   1124 DiagTrack                                   
      svchost.exe                   1324 TrkWks, UALSVC, UmRdpService,               
                                         vmickvpexchange, vmicshutdown               
      svchost.exe                   1348 W3SVC, WAS                                  
      svchost.exe                   1652 TermService                                 
      svchost.exe                   1704 vmicheartbeat                               
      svchost.exe                   5928 AppXSvc                                     
      Timed out at 8/15/2024 2:16:26 AM after 60000ms waiting for remote process.
      Wrote mini dump to: C:\h\w\A1E808D0\w\B00D09BE\uploads\4972.wy2cwqn1.5f1.dmp
      	Process ID: 4972
      	Handle: 980
      	Name: dotnet
      	MainModule: C:\h\w\A1E808D0\p\dotnet.exe
      	StartTime: 8/15/2024 2:15:26 AM
      	TotalProcessorTime: 00:00:00.3281250
      	Threads:
      		Thread #1 (OS 0x154C)   [MTA]
      			[PrestubMethodFrame] (System.DateTimeFormat.CoreLib]])
      			System.DateTimeFormat.TryFormat[[System.Char, System.Private.CoreLib]](System.DateTime, System.Span`1<Char>, Int32 ByRef, System.ReadOnlySpan`1<Char>, System.IFormatProvider, System.TimeSpan)
      			System.DateTimeFormat.TryFormat[[System.Char, System.Private.CoreLib]](System.DateTime, System.Span`1<Char>, Int32 ByRef, System.ReadOnlySpan`1<Char>, System.IFormatProvider)
      			System.DateTime.TryFormat(System.Span`1<Char>, Int32 ByRef, System.ReadOnlySpan`1<Char>, System.IFormatProvider)
      			System.Text.StringBuilder+AppendInterpolatedStringHandler.AppendFormatted[[System.DateTime, System.Private.CoreLib]](System.DateTime)
      			Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean)
      			Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose()
      			System.Threading.ThreadPools.Tests.ThreadPoolTests+<>c.<IOCompletionPortCountConfigVarTest>b__47_0(System.String)
      			[HelperMethodFrame_PROTECTOBJ] (System.RuntimeMethodHandle.InvokeMethod)
      			System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(System.Object, IntPtr*)
      			System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(System.Object, System.Span`1<System.Object>, System.Reflection.BindingFlags)
      			System.Reflection.MethodBaseInvoker.InvokeWithOneArg(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
      			System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
      			System.Reflection.MethodBase.Invoke(System.Object, System.Object[])
      			Microsoft.DotNet.RemoteExecutor.Program.Main(System.String[])
      		Thread #2 (OS 0x1298) [Finalizer] [Background] 
      			[DebuggerU2MCatchHandlerFrame]
      		Thread #3 (OS 0x104C)  [Background] [MTA]
      			[DebuggerU2MCatchHandlerFrame]
      
      Stack Trace:
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(225,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing)
        /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs(55,0): at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose()
        /_/src/libraries/System.Threading.ThreadPool/tests/ThreadPoolTests.cs(1348,0): at System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest(Int32 ioCompletionPortCount)
           at InvokeStub_ThreadPoolTests.IOCompletionPortCountConfigVarTest(Object, Span`1)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(95,0): at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
Unhandled exception. System.AggregateException: One or more errors occurred. (Assert.True() Failure
Expected: True
Actual:   False)
 ---> Xunit.Sdk.TrueException: Assert.True() Failure
Expected: True
Actual:   False
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at Xunit.Assert.True(Boolean condition) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 97
   at System.Threading.Tests.ThreadTestHelpers.CheckedWait(WaitHandle wh) in /_/src/libraries/Common/tests/System/Threading/ThreadTestHelpers.cs:line 153
   at System.Threading.ThreadPools.Tests.ThreadPoolTests.<IOCompletionPortCountConfigVarTest>g__RunAsyncIOTest|47_3() in /_/src/libraries/System.Threading.ThreadPool/tests/ThreadPoolTests.cs:line 1428
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 1892
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2782
   at System.Threading.Tasks.Task.Wait() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 2626
   at System.Threading.ThreadPools.Tests.ThreadPoolTests.<>c.<IOCompletionPortCountConfigVarTest>b__47_1() in /_/src/libraries/System.Threading.ThreadPool/tests/ThreadPoolTests.cs:line 1367
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args) in /_/src/coreclr/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.CoreCLR.cs:line 36
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 97
Unhandled exception. System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1386
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Net.Sockets.Socket>.GetResult(Int16 token) in /_/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.Tasks.cs:line 1323
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/ValueTask.cs:line 665
--- End of stack trace from previous location ---
   at System.Threading.ThreadPools.Tests.ThreadPoolTests.<>c__DisplayClass47_1.<<IOCompletionPortCountConfigVarTest>b__5>d.MoveNext() in /_/src/libraries/System.Threading.ThreadPool/tests/ThreadPoolTests.cs:line 1408
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 1926
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 1503
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 1099
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.WorkerThread.cs:line 128
   at System.Threading.Thread.StartCallback() in /_/src/coreclr/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs:line 100
    System.Threading.ThreadPools.Tests.ThreadPoolTests.ReadWriteAsyncTest [SKIP]
      Condition(s) not met: "UseWindowsThreadPool"
    System.Threading.ThreadPools.Tests.ThreadPoolTests.MetricsTest [SKIP]
      Condition(s) not met: "IsMetricsTestSupported"
  Finished:    System.Threading.ThreadPool.Tests
=== TEST EXECUTION SUMMARY ===
   System.Threading.ThreadPool.Tests  Total: 78, Errors: 0, Failed: 1, Skipped: 2, Time: 81.136s
----- end Thu 08/15/2024  2:16:40.52 ----- exit code 1 ----------------------------------------------------------
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=776432
**Error message validated:** `[at System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest(Int32 ioCompletionPortCount)`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 8/15/2024 7:22:56 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[779476](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779476)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779476&view=ms.vss-test-web.build-test-results-tab&runId=19977230&resultId=214257)|dotnet/runtime#106573|
|[779460](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779460)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779460&view=ms.vss-test-web.build-test-results-tab&runId=19977112&resultId=200269)|dotnet/runtime#106572|
|[779394](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779394)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779394&view=ms.vss-test-web.build-test-results-tab&runId=19974400&resultId=192734)|dotnet/runtime#106583|
|[779393](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779393)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779393&view=ms.vss-test-web.build-test-results-tab&runId=19974050&resultId=221478)||
|[779387](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779387)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779387&view=ms.vss-test-web.build-test-results-tab&runId=19973834&resultId=214286)|dotnet/runtime#106575|
|[779313](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779313)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779313&view=ms.vss-test-web.build-test-results-tab&runId=19971202&resultId=214261)|dotnet/runtime#106578|
|[779281](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779281)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779281&view=ms.vss-test-web.build-test-results-tab&runId=19969832&resultId=195243)||
|[779216](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779216)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779216&view=ms.vss-test-web.build-test-results-tab&runId=19967852&resultId=202708)|dotnet/runtime#106574|
|[779198](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779198)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779198&view=ms.vss-test-web.build-test-results-tab&runId=19966718&resultId=213504)|dotnet/runtime#106503|
|[779138](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779138)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779138&view=ms.vss-test-web.build-test-results-tab&runId=19965944&resultId=214261)|dotnet/runtime#106572|
|[779102](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779102)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779102&view=ms.vss-test-web.build-test-results-tab&runId=19965836&resultId=195598)|dotnet/runtime#106571|
|[779006](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779006)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=779006&view=ms.vss-test-web.build-test-results-tab&runId=19960582&resultId=202158)|dotnet/runtime#106329|
|[778946](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778946)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778946&view=ms.vss-test-web.build-test-results-tab&runId=19958810&resultId=213968)|dotnet/runtime#106569|
|[778929](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778929)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778929&view=ms.vss-test-web.build-test-results-tab&runId=19958234&resultId=202710)|dotnet/runtime#106568|
|[778894](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778894)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778894&view=ms.vss-test-web.build-test-results-tab&runId=19957414&resultId=214259)|dotnet/runtime#106567|
|[778861](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778861)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778861&view=ms.vss-test-web.build-test-results-tab&runId=19956824&resultId=213995)|dotnet/runtime#106509|
|[778785](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778785)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778785&view=ms.vss-test-web.build-test-results-tab&runId=19955992&resultId=195598)|dotnet/runtime#106548|
|[778751](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778751)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778751&view=ms.vss-test-web.build-test-results-tab&runId=19953920&resultId=197555)|dotnet/runtime#106555|
|[778694](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778694)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778694&view=ms.vss-test-web.build-test-results-tab&runId=19952132&resultId=189266)|dotnet/runtime#106562|
|[778635](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778635)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778635&view=ms.vss-test-web.build-test-results-tab&runId=19950696&resultId=214261)|dotnet/runtime#106424|
|[778590](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778590)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778590&view=ms.vss-test-web.build-test-results-tab&runId=19947894&resultId=208321)|dotnet/runtime#106413|
|[778518](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778518)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778518&view=ms.vss-test-web.build-test-results-tab&runId=19947756&resultId=214261)|dotnet/runtime#106554|
|[778488](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778488)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778488&view=ms.vss-test-web.build-test-results-tab&runId=19945346&resultId=219822)||
|[778456](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778456)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778456&view=ms.vss-test-web.build-test-results-tab&runId=19944504&resultId=189404)||
|[778321](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778321)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778321&view=ms.vss-test-web.build-test-results-tab&runId=19940444&resultId=200269)|dotnet/runtime#106498|
|[778160](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778160)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778160&view=ms.vss-test-web.build-test-results-tab&runId=19936374&resultId=194432)|dotnet/runtime#106532|
|[2517152](https://dev.azure.com/dnceng/internal/_build/results?buildId=2517152)|dotnet-runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng//internal/_build/results?buildId=2517152&view=ms.vss-test-web.build-test-results-tab&runId=54037911&resultId=178438)||
|[778154](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778154)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778154&view=ms.vss-test-web.build-test-results-tab&runId=19935752&resultId=194079)|dotnet/runtime#106533|
|[778128](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778128)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778128&view=ms.vss-test-web.build-test-results-tab&runId=19935390&resultId=200157)|dotnet/runtime#106454|
|[778002](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778002)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=778002&view=ms.vss-test-web.build-test-results-tab&runId=19928632&resultId=214024)|dotnet/runtime#106403|
|[777947](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777947)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777947&view=ms.vss-test-web.build-test-results-tab&runId=19927392&resultId=214261)|dotnet/runtime#106451|
|[777913](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777913)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777913&view=ms.vss-test-web.build-test-results-tab&runId=19926202&resultId=221997)||
|[777809](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777809)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777809&view=ms.vss-test-web.build-test-results-tab&runId=19921874&resultId=208321)|dotnet/runtime#106525|
|[777757](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777757)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777757&view=ms.vss-test-web.build-test-results-tab&runId=19918634&resultId=195594)|dotnet/runtime#106520|
|[777739](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777739)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777739&view=ms.vss-test-web.build-test-results-tab&runId=19918386&resultId=200389)||
|[777732](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777732)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777732&view=ms.vss-test-web.build-test-results-tab&runId=19918046&resultId=213914)|dotnet/runtime#103317|
|[777687](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777687)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777687&view=ms.vss-test-web.build-test-results-tab&runId=19916906&resultId=200267)|dotnet/runtime#80154|
|[777681](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777681)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777681&view=ms.vss-test-web.build-test-results-tab&runId=19916908&resultId=195594)||
|[777661](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777661)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777661&view=ms.vss-test-web.build-test-results-tab&runId=19915616&resultId=206419)|dotnet/runtime#106483|
|[777538](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777538)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777538&view=ms.vss-test-web.build-test-results-tab&runId=19911760&resultId=195594)|dotnet/runtime#106500|
|[777317](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777317)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=777317&view=ms.vss-test-web.build-test-results-tab&runId=19905902&resultId=194917)||
|[776509](https://dev.azure.com/dnceng-public/public/_build/results?buildId=776509)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=776509&view=ms.vss-test-web.build-test-results-tab&runId=19874076&resultId=213887)|dotnet/runtime#106432|
|[776432](https://dev.azure.com/dnceng-public/public/_build/results?buildId=776432)|dotnet/runtime|[System.Threading.ThreadPools.Tests.ThreadPoolTests.IOCompletionPortCountConfigVarTest](https://dev.azure.com/dnceng-public/public/_build/results?buildId=776432&view=ms.vss-test-web.build-test-results-tab&runId=19872832&resultId=195594)|dotnet/runtime#106429|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|9|43|43|

**Comment by jkotas** [comment] 2024-08-18 16:28
Duplicate of #106494

**Closed by jkotas** 2024-08-18 16:28 UTC
Labels: area-System.Threading, untriaged, Known Build Error
