### ISSUE TITLE
TypeLoadException when using self type as generic parameter for struct

### ISSUE THREAD

**Issue by zvirja** [dotnet/runtime#47129] opened 2021-01-18 19:08 UTC
### Steps to reproduce

Compile and run following C# code (this is [MVCE](https://stackoverflow.com/help/minimal-reproducible-example) so code might look a bit weird).

```c#
// Changing to `class` solves the issue
public struct Ref<T>
{
}

public struct Cell
{
    public Ref<Cell> Next;
}

class Program
{
    static void Main(string[] args)
    {
        Cell c;
    }
}
```

### Exception

The following exception is begin thrown:

```
Unhandled exception. System.TypeLoadException: Could not load type 'BugRepro.Cell' from assembly 'BugRepro, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at BugRepro.Program.Main(String[] args)
```

### Configuration
.NET Core: 5.0.2 (reproducible with older versions too, including .NET 4.8)
OS: Windows
Arch: x86

### Other information

Exception does not contain any other information to narrow down the issue cause. Looks like the issue is related to Type Loader which gets confused with the usage of the `Cell<T>` type.

**Comment by zvirja** [comment] 2021-01-18 19:15
UPD: The `Cell` type is not necessarily should be nested. This fails as well:
```c#
    public struct ListCell
    {
        public Pool<ListCell>.Ref Next;
    }
    public class PooledList
    {
        // When next line is commented out - issue is gone.
        private Pool<ListCell>.Ref _firstChild;
    }
```

**Comment by EgorBo** [comment] 2021-01-18 21:24
Explanation: https://github.com/dotnet/runtime/issues/6924#issuecomment-547078135

**Comment by mangod9** [comment] 2021-07-04 16:31
Assume this is ok to close as dupe of 6924? Please reopen if that isnt the case. Thx!

**Closed by mangod9** 2021-07-04 16:31 UTC
Labels: area-TypeSystem-coreclr, untriaged
