### ISSUE TITLE
Handle concurrent writes in System.Net.Quic

### ISSUE THREAD

**Issue by jkotalik** [dotnet/runtime#32190] opened 2020-02-12 21:01 UTC
There are a few places where calling WriteAsync/ReadAsync on a QuicStream would cause the stream to go into an invalid state. Let's make sure we don't throw and or support concurrent reads/writes.

**Comment by scalablecory** [comment] 2020-02-13 04:49
Duplicate of #32078

**Closed by scalablecory** 2020-02-13 04:49 UTC
Labels: area-System.Net, untriaged
