### ISSUE TITLE
Test failure: JIT\opt\Tailcall\TailcallVerifyWithPrefix\TailcallVerifyWithPrefix.cmd

### ISSUE THREAD

**Issue by JulieLeeMSFT** [dotnet/runtime#69587] opened 2022-05-20 01:16 UTC
Log file: [Link](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-7c25bf59a6d940b592/JIT.1/1/console.8e34e161.log?helixlogtype=result)
Failed pipeline: [Link](https://dev.azure.com/dnceng/public/_build/results?buildId=1779275&view=results) cc @AntonLapounov 
```
  Starting:    JIT.opt.XUnitWrapper (parallel test collections = on, max threads = 8)
    JIT\opt\Tailcall\TailcallVerifyWithPrefix\TailcallVerifyWithPrefix.cmd [FAIL]
      
      Return code:      1
      Raw output file:      D:\h\w\B05809AE\w\C51F0A3A\uploads\Reports\JIT.opt\Tailcall\TailcallVerifyWithPrefix\TailcallVerifyWithPrefix.output.txt
      Raw output:
      BEGIN EXECUTION
       "D:\h\w\B05809AE\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  TailcallVerifyWithPrefix.dll 
      Executing Condition3.Test1 - Caller: Arguments: None - ReturnType: Int32; Callee: Arguments: None - ReturnType: Int32
      Execution finished - Test PASSED
      Executing Condition3.Test2 - Caller: Arguments: None - ReturnType: void; Callee: Arguments: None - ReturnType: string
      Execution finished - Test PASSED
      Executing Condition4.Test1 - Caller: Arguments: None - ReturnType: 3 byte struct; Callee: Arguments: None - ReturnType: 3 byte struct
      Execution finished - Test PASSED
      Executing Condition4.Test2 - Caller: Arguments: None - ReturnType: 3 byte struct; Callee: Arguments: None - ReturnType: 3 byte struct [Verifying the field values in the return type struct]
      Execution finished - Test PASSED
      Executing Condition5.Test1 - There is a 'conv.i2' IL instruction between the tail. call to the Callee and the ret IL instruction which is not allowed. Expecting to catch an InvalidProgramException internally if tail. prefix is present.
      Execution finished - Test PASSED
      Executing Condition5.Test2 - Caller: Arguments: None - ReturnType: byte; Callee: Arguments: None - ReturnType: byte
      Execution finished - Test PASSED
      Executing Condition5.Test3 - Caller: Arguments: None - ReturnType: Int32; Callee: Arguments: None - ReturnType: Int32
      Execution finished - Test PASSED
      Executing Condition5.Test4 - Caller: Arguments: None - ReturnType: UInt32; Callee: Arguments: None - ReturnType: Int32
      Execution finished - Test PASSED
      Executing Condition5.Test5 - Caller: Arguments: None - ReturnType: Int32; Callee: Arguments: None - ReturnType: UInt32
      Execution finished - Test PASSED
      Executing Condition5.Test6 - Caller: Arguments: None - ReturnType: Int64; Callee: Arguments: None - ReturnType: UInt64
      Execution finished - Test PASSED
      Executing Condition5.Test7 - Caller: Arguments: None - ReturnType: UInt64; Callee: Arguments: None - ReturnType: Int64
      Execution finished - Test PASSED
      Executing Condition5.Test8 - Caller: Arguments: None - ReturnType: UInt64; Callee: Arguments: None - ReturnType: UInt32 - Expecting a InvalidProgramException
      Execution finished - Test PASSED
      Executing Condition5.Test9 - Caller: Arguments: None - ReturnType: UInt32; Callee: Arguments: None - ReturnType: UInt64 - Expecting a InvalidProgramException
      Execution finished - Test PASSED
      Executing Condition9.Test1 - Caller: Arguments: None - ReturnType: void; Callee(Interface Member): Arguments: None - ReturnType: void
      Execution finished - Test PASSED
      Executing Condition10.Test1 - Caller<string>: Arguments: None - ReturnType: void; Callee: Arguments: None - ReturnType: void
      Execution finished - Test PASSED
      Executing Condition10.Test2 - Caller: Arguments: None - ReturnType: void; Callee<string>: Arguments: None - ReturnType: void
      Execution finished - Test PASSED
      Executing Condition10.Test3 - class Foo1<string, int>: Caller: Arguments: None - ReturnType: void; Callee: Arguments: None - ReturnType: void
                                    class Foo1<string, int>: Caller: Arguments: None - ReturnType: void; Callee: Arguments: None - ReturnType: void
                                    class Foo1<string, short>: Caller: Arguments: None - ReturnType: void; Callee: Arguments: None - ReturnType: void
                                    class Foo1<string, ValueType3Bytes>: Caller: Arguments: None - ReturnType: void; Callee: Arguments: None - ReturnType: void
      Execution finished - Test PASSED
      Executing Condition10.Test4 - class Foo2<string, int>: Caller: Arguments: string, int - ReturnType: void; Callee: Arguments: string - ReturnType: void
                                    class Foo2<string, int>: Caller: Arguments: string, int - ReturnType: void; Callee: Arguments: string - ReturnType: void
                                    class Foo2<string, short>: Caller: Arguments: string, short - ReturnType: void; Callee: Arguments: string - ReturnType: void
                                    class Foo2<string, ValueType3Bytes>: Caller: Arguments: string, ValueType3Bytes - ReturnType: void; Callee: Arguments: string - ReturnType: void
      Execution finished - Test PASSED
      Executing Condition10.Test5 - Caller: Arguments: None - ReturnType: void; Callee<string>: Arguments: None - ReturnType: void
      Execution finished - Test PASSED
      Executing Condition11.Test1 - Caller: Arguments: None - ReturnType: void; Callee(virtual): Arguments: None - ReturnType: void
      Execution finished - Test PASSED
      Executing Condition12.Test1 - Caller: Arguments: int,int,int - ReturnType: void; Callee: Arguments: string,string,string - ReturnType: void
      Execution finished - Test PASSED
      Executing Condition13.Test1 - Caller: Arguments: None - ReturnType: 3 byte struct; Callee: Arguments: None - ReturnType: 3 byte struct
      Execution finished - Test PASSED
      Executing Condition16.Test1 - Caller: Arguments: None - ReturnType: void; Callee: Arguments: None - ReturnType: void
      GOOD: Failed to get the lock
      GOOD: got the lock again...
      Execution finished - Test PASSED
      Executing Condition17.Test1 - Caller: Arguments: None - ReturnType: 3 byte struct; Callee: Arguments: None - ReturnType: void
      Execution finished - Test PASSED
      Executing Condition18.Test1 - Caller(declarative security): Arguments: None - ReturnType: 3 byte struct; Callee: Arguments: None - ReturnType: 3 byte struct
      Execution finished - Test PASSED
      Executing Condition19.Test1 - Caller: Arguments: None - ReturnType: void; Callee (doing a pinvoke call): Arguments: None - ReturnType: void
      result: 0
      Execution finished - Test PASSED
      Executing Condition19.Test2 - Caller: Arguments: None - ReturnType: void; Callee (IS A pinvoke call): Arguments: None - ReturnType: void
      result: 0
      Execution finished - Test PASSED
      Executing Condition20.Test1 - Caller: Arguments: int - ReturnType: void; Callee: the same as Caller (called again)
      Execution finished - Test PASSED
      Expected: 100
      Actual: -1073741819
      END EXECUTION - FAILED
```

**Comment by jakobbotsch** [comment] 2022-05-20 08:14
This does not look persistent so will remove the blocking label.

**Comment by jakobbotsch** [comment] 2022-05-20 08:37
Unfortunately doesn't look like there is any dump here. I'm trying to repro by running the test in a loop on win-arm32, but no luck so far.

**Comment by jakobbotsch** [comment] 2022-05-20 08:55
In the same run the UnsafeBlockCopy test failed. This is an extremely simple test that should involve next to no GC:
https://github.com/dotnet/runtime/blob/3914bcc230134ec3e1c9be903c6bd8ff60d92501/src/tests/JIT/opt/Inline/tests/UnsafeBlockCopy.cs#L7-L33

It seems unlikely to me that the problem is codegen related.

**Comment by jakobbotsch** [comment] 2022-06-07 11:13
I cannot reproduce this and without the dump/more failures there is nothing actionable here, so will close this. Let's reopen it if we get more failures.

**Closed by jakobbotsch** 2022-06-07 11:13 UTC
Labels: area-CodeGen-coreclr
