### ISSUE TITLE
Directory.GetFiles fails when the directory has a file with 255 characters in the name

### ISSUE THREAD

**Issue by Const-me** [dotnet/runtime#57578] opened 2021-08-17 16:10 UTC
### Description

Critical error in Directory.GetFiles function

### Configuration

Using .NET Core 2.1 LTS.

The OS is Debian Linux, OS kernel 4.4.132+.

The architecture is ARMv7, 32-bit. The CPU is Rockchip RK3288.

I don’t know whether it is specific to that configuration, but based on the source code in your repository, the bug probably affects all Linux regardless on the rest of the factors.

[According to Linux documentation](https://serverfault.com/a/9548), files names of 255 characters are valid on all supported file systems except FAT32.<br />
Linux command-line shell is also fine with such files. The scp integrated into sshd server also handles them fine. It’s very unexpected for .NET Core to not be able to handle such files, especially since the file was previously created by other pieces of the same C# standard library.

### Other information

I've attached the repro project. Here’s the output:

```
File name length: 255 characters
Created OK
Read OK: Hello, world
Fail: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at System.ReadOnlySpan`1..ctor(Void* pointer, Int32 length)
   at Interop.Sys.DirectoryEntry.GetName(Span`1 buffer)
   at System.IO.Enumeration.FileSystemEntry.get_FileName()
   at System.IO.Enumeration.FileSystemEnumerableFactory.<>c__DisplayClass3_0.<UserFiles>b__1(FileSystemEntry& entry)
   at System.IO.Enumeration.FileSystemEnumerable`1.DelegateEnumerator.ShouldIncludeEntry(FileSystemEntry& entry)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.IO.Directory.GetFiles(String path)
   at Program.mainImpl()
   at Program.Main(String[] args)
```

P.S. Unfortunately, that was not a synthetic test. Our customer has actually uploaded the file with such a long name. This bug has broken an expensive device with embedded Linux. I incorrectly assumed that if a file was successfully created, written and read using .NET’s `FileStream`-based classes, the name should be good enough for the rest of the file system APIs.

**Comment by Const-me** [comment] 2021-08-17 16:12
[FileSystemFail.zip](https://github.com/dotnet/runtime/files/7001480/FileSystemFail.zip)

**Comment by adamsitnik** [comment] 2021-08-17 16:43
Triage: it's not a regression, the name buffer size is hardcoded to 256.

https://github.com/dotnet/runtime/blob/addbbcb411bda2a9744e893d492b6b87b8d933fa/src/libraries/System.Private.CoreLib/src/System/IO/Enumeration/FileSystemEntry.Unix.cs#L18

https://github.com/dotnet/runtime/blob/00e19e3af923b657302a073ebcf2c955ff74d9d7/src/libraries/Common/src/Interop/Unix/System.Native/Interop.ReadDir.cs#L32

I am going to take a look

**Comment by adamsitnik** [comment] 2021-08-17 16:55
Hi @Const-me 

Thank you for a detailed bug report and nice repro case. I was able to confirm that it's a .NET Core 2.1 bug that got fixed in .NET Core 3.1

```log
adam@adsitnik-ubuntu:~/projects/repros/maxPath$ dotnet run -c Release -f netcoreapp2.1
File name length: 255 characters
Created OK
Read OK: Hello, world
Fail: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at System.ReadOnlySpan`1..ctor(Void* pointer, Int32 length)
   at Interop.Sys.DirectoryEntry.GetName(Span`1 buffer)
   at System.IO.Enumeration.FileSystemEntry.get_FileName()
   at System.IO.Enumeration.FileSystemEnumerableFactory.<>c__DisplayClass3_0.<UserFiles>b__1(FileSystemEntry& entry)
   at System.IO.Enumeration.FileSystemEnumerable`1.DelegateEnumerator.ShouldIncludeEntry(FileSystemEntry& entry)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.IO.Directory.GetFiles(String path)
   at FileSystemFail.mainImpl() in /home/adam/projects/repros/maxPath/Program.cs:line 36
   at FileSystemFail.Main(String[] args) in /home/adam/projects/repros/maxPath/Program.cs:line 49
adam@adsitnik-ubuntu:~/projects/repros/maxPath$ dotnet run -c Release -f netcoreapp3.1
File name length: 255 characters
Created OK
Read OK: Hello, world
./maxPath.csproj
./012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678.abcde
./Program.cs
Completed OK
adam@adsitnik-ubuntu:~/projects/repros/maxPath$ dotnet run -c Release -f net5.0
File name length: 255 characters
Created OK
Read OK: Hello, world
./maxPath.csproj
./012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678.abcde
./Program.cs
Completed OK
```

.NET Core 2.1 is no longer supported: https://dotnet.microsoft.com/platform/support/policy/dotnet-core
Please update to .NET Core 3.1 or .NET 5 where the bug has been fixed.

**Closed** 2021-08-17 16:57 UTC
Labels: area-System.IO

**Comment by Const-me** [comment] 2021-08-17 20:47
Hi @adamsitnik

Thanks for the quick response.

The migration to 3.1 LTS wasn’t too bad, worked on first try. Gonna test for couple more days before publishing. We have a private Debian repository for OTA updates of these pieces of equipment, the updates easy and reliable, the button on the touch screen simply runs `/usr/bin/apt-get`

One question remains.

The critical bug was fixed in 2019.
How comes the .NET runtime 2.1 (still supported to this day, the page you have linked says support will end on August 21, 2021) never received the patch?

Most importantly, what we should do in the future?

Does Microsoft fix critical bugs in older but still supported versions of .NET runtime?
If yes, why not this one?
If no, that’s fine too (a free product, we get what we paid for), but do you think we should use the latest versions of the runtime on the devices we sell, instead of the LTS one?

**Comment by adamsitnik** [comment] 2021-08-17 20:51
@danmoseley since you have fixed the bug in https://github.com/dotnet/corefx/pull/34389 would you like to answer @Const-me question?

**Comment by Jozkee** [comment] 2021-08-18 00:31
@adamsitnik, Dan is away this week, perhaps @jeffhandley or @ericstj may be able to respond that question.

**Comment by jeffhandley** [comment] 2021-08-18 06:52
I'll review this on Wednesday and will reply.

**Comment by jeffhandley** [comment] 2021-08-19 04:25
I appreciate the questions, @Const-me.

We do not port every bug fix to every supported version of .NET, as that would be impractical for several reasons. First is that from version to version, other aspects of the product and code base change; new features are added; code is refactored; and support for operating systems and configurations might change--that means not every bug fix is a simple port to each prior version. Second is that every change ported to a prior version introduces risk to that prior version that must be minimized such that servicing updates can be trusted to be fully compatible without introducing new issues or breaking changes.

For these and other reasons, we do not proactively port bug fixes to prior (supported) versions. Instead, we await customer reports that an issue is a significant blocker and that migrating to another version where the fix might already exist is not an immediate option. Typically a report such as yours would prompt us to consider porting the fix to the version affected.  As you've noted though, .NET Core 2.1 is just about to reach its end-of-support date. As such, we have already completed the last servicing update .NET Core 2.1.

> Do you think we should use the latest versions of the runtime on the devices we sell, instead of the LTS one?

I recommend reviewing our [support policy](https://dotnet.microsoft.com/platform/support/policy) documentation to guide this decision. Determining how .NET servicing updates can be utilized in your own device servicing updates is likely a key factor for you, and the support length for non-LTS vs. LTS releases could inform your strategy.

I hope this helps,
Jeff Handley
