### ISSUE TITLE
The .NET 6 breaking change of `FileStream.Position` in async I/O is not exhibited.

### ISSUE THREAD

**Issue by teo-tsirpanis** [dotnet/runtime#80926] opened 2023-01-20 15:58 UTC
### Description

According to https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/filestream-position-updates-after-readasync-writeasync-completion, starting in .NET 6 updating the position of a `FileStream` should update its `Position` after async I/O has completed, but upon looking at its source code it seemed it was updated before, and when I tried it my suspicions are confirmed.

### Reproduction Steps

Run the following snippet in .NET 6 and 7:

```csharp
byte[] bytes = new byte[10_000];
string path = Path.Combine(Path.GetTempPath(), Path.GetTempFileName());

using (FileStream fs = new FileStream(path, FileMode.Create, FileAccess.ReadWrite, FileShare.None, bufferSize: 4096, useAsync: true))
{
    Task[] writes = new Task[3];

    writes[0] = fs.WriteAsync(bytes, 0, bytes.Length);
    Console.WriteLine(fs.Position);  // 10000 in .NET 5, 0 in .NET 6

    writes[1] = fs.WriteAsync(bytes, 0, bytes.Length);
    Console.WriteLine(fs.Position);  // 20000 in .NET 5, 0 in .NET 6

    writes[2] = fs.WriteAsync(bytes, 0, bytes.Length);
    Console.WriteLine(fs.Position);  // 30000 in .NET 5, 0 in .NET 6

    await Task.WhenAll(writes);
    Console.WriteLine(fs.Position);  // 30000 in all versions
}
```

### Expected behavior

It should print `0 0 0 30000`.

### Actual behavior

It prints `10000 20000 30000 30000`.

### Regression?

No, this is an advertised breaking change that does not occur.

### Configuration

.NET 6 and 7, Windows 10

### Other information

https://github.com/dotnet/runtime/blob/031177b8878371f081f8840ff814503970a7e5b0/src/libraries/System.Private.CoreLib/src/System/IO/Strategies/OSFileStreamStrategy.cs#L257-L261

This seems to me that the position is changed before.

**Comment by adamsitnik** [comment] 2023-01-20 16:18
Hi @teo-tsirpanis 

To tell the long story short `FileStream` was never thread safe and people should not be using it to perform multiple async reads/writes at the same time. But of course they do ;) One of our goals for the rewrite was to break as few users as possible, that is why `FileStream` updates the position before it starts the async operation. So the next operation starts at the position where previous should finish (and those who misue `FileStream`get invalid `Postion`). We don't advertise this publicly as we officially don't support this scenario and don't want to encourage our users to misuse the `FileStream` (IMO we should just throw in such scenarios). That is also why we have introduced the thread-safe `RandomAccess`, which should be used in such cases. 

I am going to close the issue as it's by design.

**Closed by adamsitnik** 2023-01-20 16:18 UTC
Labels: area-System.IO, untriaged

**Comment by stephentoub** [comment] 2023-01-20 16:24
> that is why FileStream updates the position before it starts the async operation

I believe @teo-tsirpanis is objecting to this line in the breaking change notification (not that we should change FileStream, but that what's documented in the breaking change notification doesn't match):
"Starting in .NET 6, [FileStream.Position](https://learn.microsoft.com/en-us/dotnet/api/system.io.filestream.position#system-io-filestream-position) is updated after those operations complete."
