### ISSUE TITLE
Additional metrics for .NET Core and ASP.NET Core

### ISSUE THREAD

**Issue by rob2244** [dotnet/runtime#79459] opened 2022-12-09 16:44 UTC
I have talked internally with the IC3 platform team, and we've come up with a list of additional metrics we'd love to see in .NET 8 which would help us (and others) better understand, monitor and fine tune our services. 

### Http Connection Pool Metrics
Ideally these metrics would be available per FQDN:Port combination, broken down by type (i.e. HTTP1.1/HTTP2) and there would be some way to track which http client each pool belongs to.

- total number of connections
- number of idle connections
- average idle connection time
- number of connections evicted from pool due to idle timeout
- number of connection timeouts
- average time to connect
- queue length
- average time spent in queue
- number of http 2 keep alive pings which didn't receive a response
- average response time of http 2 keep alive pings

### Rate Limiting Middleware Metrics
It would be great if we could have some way of telling these apart by specific rate limiter, as I know that in .NET 7 you can have multiple rate limiters configured. Maybe if we could name each rate limiter then get the metrics output by the name? Or maybe it could be by the endpoint which the rate limiter protects?

- Number of requests kicked out by limiter
- For limiters with queues, length of queue and average time spent in queue
- For Token based limiters the number of unclaimed tokens in the pool and the average rate at which tokens are removed from the pool
- For Fixed window limiters the number of requests seen per window
- For sliding window limiters, the number of requests seen in a window, the number of requests seen in a segment and the number of requests that appeared in multiple segments

### Kestrel Metrics
- Number of client requests cancelled/client disconnects (not sure if this one is possible or not)

### Memory Metrics 
- Private Bytes (MB) as tracked by [this](https://github.com/dotnet/runtime/issues/43140) issue

Thanks!

**Comment by MihaZupan** [comment] 2022-12-09 19:34
Oops, changed the labels on the wrong issue

**Comment by MihaZupan** [comment] 2022-12-09 19:50
Thank you for the suggestions!

> average idle connection time

How would this be defined? The average idle-time across all currently idle connections? The average idle-time of connections that were woken up to serve a request within the current interval?

> number of connection timeouts

Are you referring to the number of connection attempts that hit the ConnectTimeuot, or the number of requests that hit the request timeout before obtaining a connection?

> number of http 2 keep alive pings which didn't receive a response

This seems rather niche, what were you looking to do with this information?

> average time spent in queue

Akin to counters like `http11-requests-queue-duration`, just with dimensions?
Note that this counter currently tracks the average time spent on queue for requests that ended up on the queue (not all requests).
Was that the sort of information you were looking for, or just an average across all requests to track how much latency the request queue is adding to an average request?

> average response time of http 2 keep alive pings

Is the purpose of this to track the average RTT or something else?

> Rate Limiting Middleware Metrics

cc: @BrennanConroy

> Kestrel Metrics

cc: @davidfowl

**Comment by davidfowl** [comment] 2022-12-10 04:47
cc @samsp-msft @adityamandaleeka

**Comment by rob2244** [comment] 2022-12-14 17:03
@MihaZupan 

- For the average idle time: I was thinking the latter, i.e.  
> The average idle-time of connections that were woken up to serve a request within the current interval

Although I see how both of these could be useful in different ways.

- For the number of connection timeouts: the number of connection attempts that hit the ConnectTimeout

- Regarding the Http 2 metrics, for some of these metrics I was trying to think what might help devs outside of IC3 (with these specifically I was thinking it might help troubleshoot or serve as an early warning to http 2 issues). I don't think we have any use for this metric currently. If any of these don't make sense or there's already easier ways to troubleshoot/track them, feel free to disregard.

- Yes exactly, the current `requests-queue-duration` metric is great, it would just be adding the relevant dimensions.

**Comment by MihaZupan** [comment] 2023-01-23 18:15
Triage: Re: networking, most of these metrics make sense. We'll need to figure out how we want to approach adding dimensions as part of #79371. Optimistically moving to 8.0.

**Comment by davidfowl** [comment] 2023-04-16 08:07
cc @JamesNK

**Comment by JamesNK** [comment] 2023-04-17 13:25
Proposed rate limiting middleware metrics - https://github.com/dotnet/aspnetcore/issues/47745

**Comment by arman-microsoft** [comment] 2023-05-25 15:51
Hey folks, we had another ask from the same team for an additional memory metric.

**Ask**: his ask for visibility into the free space in each generation of the heap.

**Context**: We are seeing sometimes large heap footprints and are unable to determine if they are mostly free for whatever reason uncompacted (transient allocation activity leaving large uncompated holes) or if they are actually rooted and we need to intervene and reboot the node and investigate as a likely cause for suspecting leak.

**Comment by samsp-msft** [comment] 2023-05-25 18:10
> > average idle connection time
> How would this be defined? The average idle-time across all currently idle connections? The average idle-time of connections that were woken up to serve a request within the current interval?

Forget the average part - that can be calculated later. Report the time each connection was idle when it was re-used or disconnected due to timeout.

> > number of connection timeouts
> Are you referring to the number of connection attempts that hit the ConnectTimeuot, or the number of requests that hit the request timeout before obtaining a connection?

or the number of pooled connections that timeout?
 
> > number of http 2 keep alive pings which didn't receive a response

> This seems rather niche, what were you looking to do with this information?

+1 on the niche part

> > average time spent in queue
> 
> Akin to counters like `http11-requests-queue-duration`, just with dimensions? Note that this counter currently tracks the average time spent on queue for requests that ended up on the queue (not all requests). Was that the sort of information you were looking for, or just an average across all requests to track how much latency the request queue is adding to an average request?

this should just be request queue time, measured for each request, that will give you the average and p9x values.

**Comment by karelz** [comment] 2023-07-04 06:57
Looks like the remaining work is mostly duplicate of #79371

**Comment by antonfirsov** [comment] 2023-07-04 14:36
As per https://github.com/dotnet/runtime/issues/79459#issuecomment-1619624996, I'm closing this as a duplicate of #88384.

@rob2244 please take a look at that issue, and let us know, if we missed something!

**Closed by antonfirsov** 2023-07-04 14:36 UTC
Labels: enhancement, area-System.Net.Http
