### ISSUE TITLE
Suppurt C++\CLI in Linux with installed Net.Core Runtime?

### ISSUE THREAD

**Issue by ankofl** [dotnet/runtime#105230] opened 2024-07-22 10:25 UTC
I guess today, even if we install net core.runtime on Linux, we still won't be able to use libraries using C++\CLI inside it?

I will be very annoyed if this is still the case...

**Comment by huoyaoyuan** [comment] 2024-07-22 11:11
> we still won't be able to use libraries using C++\CLI inside it?

For already-compiled C++/CLI assemblies, **they are never usable on a different platform**. They are even not sharable between .NET Framework and .NET Core. It's a mixture of IL and native Windows code, using Windows calling convention and so on. It's only supported by MSVC, which can only compiles Windows code.

We are not interested in porting C++/CLI to other platforms. It's highly legacy and consists of a lot of magic codes, and doesn't work well with many modern technologies. See also #4116 #66117 .

**Comment by ankofl** [comment] 2024-07-22 11:27
In that case, are there alternatives to C++\CLI for Linux as part of Net?Core RunTIme, or is PInvoke the only option for interaction?

**Comment by huoyaoyuan** [comment] 2024-07-22 11:39
P/Invoke is the only option. C++/CLI actually consists with specialized in-file P/Invoke.

There are tools like the `LibraryImport` source generator and `ClangSharp` to help you generate efficient and correct modern P/Invoke.

**Comment by jkoritzinsky** [comment] 2024-07-22 14:45
Closing as the question has been answered and this is a duplicate of #4121.

**Closed** 2024-07-22 14:45 UTC
Labels: untriaged, needs-area-label
