### ISSUE TITLE
ChannelReader.ReadAsync/ChannelWriter.WriteAsync don't return or throw when cancellation token is signaled

### ISSUE THREAD

**Issue by jeffbromberger** [dotnet/runtime#64051] opened 2022-01-20 16:25 UTC
### Description

If one of these calls is currently blocking - ReadAsync because the channel is empty, or WriteAsync because the channel is full - then signaling the cancellation token does not result in a return of execution to the caller. I.e. it does not return a value nor does it throw. It just blocks forever. Calling Complete on the channel from another thread will cause the blocked call to throw ChannelClosedException, but I'm not clear on why the cancellation token being signaled is not sufficient.  Further, there seems to be inconsistency across runtime environments.  The supplied code actually does work on .NET Fiddle, but does not work in a Windows 10 x64 environment in either VS2019 or from a cmd.exe execution.

@stephentoub 

### Reproduction Steps

```
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Channels;
using System.Threading.Tasks;


public class Program
{
    public static async Task Task1(Channel<String> q1, CancellationToken cancellationToken)
    {
        int idx = 0;

        Console.WriteLine($"Task1 starting");

        while (!cancellationToken.IsCancellationRequested)
        {
            try
            {
                await Task.Delay(100);

                string s = $"element{idx++}";

                Console.WriteLine($"Calling write on {s}");
                await q1.Writer.WriteAsync(s, cancellationToken);
                Console.WriteLine($"Write returned for {s}");
            }
            catch (OperationCanceledException)
            {
                Console.WriteLine($"Operation was cancelled");
            }
            catch (ChannelClosedException)
            {
                Console.WriteLine($"Channel was closed");
            }
        }

        //q1.Writer.Complete();
        Console.WriteLine($"Task1 stopping");

    }

    public static async Task Main()
    {
        Console.WriteLine($"Main started");

        var tasklist = new List<Task>();

        var q1 = Channel.CreateBounded<String>(
            new BoundedChannelOptions(10)
            {
                AllowSynchronousContinuations = false,
                SingleReader = true,
                SingleWriter = true,
                FullMode = BoundedChannelFullMode.Wait
            });

        var cts = new CancellationTokenSource(5000);

        tasklist.Add(Task.Run(() => Task1(q1, cts.Token), cts.Token));

        while (!cts.Token.IsCancellationRequested)
        {
            try
            {
                await Task.Delay(10000, cts.Token);
            }
            catch (OperationCanceledException) { }
        }

        //q1.Writer.Complete();

        Console.WriteLine($"Waiting for all tasks to terminate");
        Task.WaitAll(tasklist.ToArray(), CancellationToken.None);
        Console.WriteLine($"All tasks terminated");
    }
}
```

### Expected behavior

WriteAsync should throw (or return) when cancellation token is signaled allowing task to complete.  Oddly, this *does* seem to work as expected when the supplied code is pasted into a .NET Fiddle.  But on a Win 10 x64 machine, in VS2019 or from the command prompt, it hangs indefinitely.

If the main thread calls Complete on the channel, then the blocked WriteAsync call will throw ChannelClosedException.  But it seems that the passed in cancelation token has no effect on its own.

### Actual behavior

```
Main started
Task1 starting
Calling write on element0
Write returned for element0
Calling write on element1
Write returned for element1
Calling write on element2
Write returned for element2
Calling write on element3
Write returned for element3
Calling write on element4
Write returned for element4
Calling write on element5
Write returned for element5
Calling write on element6
Write returned for element6
Calling write on element7
Write returned for element7
Calling write on element8
Write returned for element8
Calling write on element9
Write returned for element9
Calling write on element10
Waiting for all tasks to terminate
```

### Configuration

.NET 5.0.404, Windows 10 x64 Enterprise 1809

**Comment by stephentoub** [comment] 2022-01-20 16:42
Do you still see this with .NET 6?

**Comment by jeffbromberger** [comment] 2022-01-20 16:50
@stephentoub  I have not tried because I'm using VS2019 and my understanding per the docs is that .NET 6 requires VS2022... if it would help you analyze I can try to set up a .NET 6 environment independent of VS, but I would hope to be able to use .NET 5/VS2019 for this project in the long run...

**Comment by stephentoub** [comment] 2022-01-20 16:56
> I would hope to be able to use .NET 5/VS2019 for this project in the long run...

FYI, end of support for .NET 5 is May 8th.
https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

> if it would help you analyze I can try to set up a .NET 6 environment independent of VS

I tried your repro, and while I see the reported results with .NET 5, it runs to completion successfully on .NET 6.

**Comment by jeffbromberger** [comment] 2022-01-20 17:11
> FYI, end of support for .NET 5 is May 8th. https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core
> 
> I tried your repro, and while I see the reported results with .NET 5, it runs to completion successfully on .NET 6.

@stephentoub  Thanks for that heads up.  It had not clicked with me that .NET 5 was only a 1.5 year lifecycle.  It sounds like this won't be fixed in 5.0, but do you have any idea what is causing this behavior?  I'm hoping for some reassurance that calling Complete is a reliable workaround in the absence of the token actually canceling the operation.

**Comment by stephentoub** [comment] 2022-01-20 18:10
I'm trying to figure out if it's reliably addressed in .NET 6 or if it's just happening to typically not repro due to timing; I believe it's the latter, in which case there's probably still a fix to consider in .NET 6+.  I don't think this is related to channels at all, actually.  What's happening is the CTS's underlying timer fires and Cancel's the CTS, which synchronously completes the Task.Delay's task, which synchronously invokes the await continuation from that task, which then synchronously blocks in the Task.WaitAll.  The problem is there's another registration in the CTS waiting to be invoked, and it won't be invoked until after the first callback completes, and it won't complete until that Task.WaitAll completes, which won't complete until the other registration is invoked to cancel the task being waited on... deadlock.  You can see this with a simple repro:
```C#
var cts = new CancellationTokenSource(2000);
cts.Token.Register(() => Console.WriteLine("B"));
try { await Task.Delay(-1, cts.Token); }
catch { }
Console.WriteLine("A");
Console.ReadLine();
```
That will output "A" but then won't output "B" until you press enter.  The workaround is to break the synchronous continuation chain leading to blocking, and the easiest way to do that is to add an await that will be guaranteed to yield.  For example, in your repro, change the `catch (OperationCanceledException) { }` line to instead be `catch (OperationCanceledException) { await Task.Yield(); }` and you should see the issue go away.

**Comment by jeffbromberger** [comment] 2022-01-20 20:30
Thank you for the further explanation.  I'm a long time kernel programmer but a .NET novice, so I'm happy to accept the user error label here.  The part that surprises me is that I would have expected the signaling of the token being canceled to impact all tasks simultaneously - like multiple threads waiting on a common event in win32.  But it sounds like the cancelation needs to propagate through synchronously from task to task performing each of their continuations serially?  Or did I misunderstand your analysis?

**Comment by stephentoub** [comment] 2022-01-20 20:34
> I'm happy to accept the user error label here

I didn't mean to imply you did anything wrong, apologies.  I was trying to say that the components are behaving the way they were designed to, but the confluence of those designs is leading to an issue that violates what a user can reasonably expect, and so is an issue we should consider fixing.

> But it sounds like the cancelation needs to propagate through synchronously from task to task performing each of their continuations serially?

Effectively, yes.  CancellationToken.Register hooks up a callback that's invoked when the associated CancellationTokenSource.Cancel method is called.  All such registrations with the same token source are invoked synchronously one after the other (that's generally how events work in .NET, and this is basically an event, just with a different syntax).

**Comment by jeffbromberger** [comment] 2022-01-20 20:42
No worries, no offense taken.  Again, really appreciate the responsiveness on all of this.

**Closed** 2022-01-26 03:32 UTC
Labels: area-System.Threading, in-pr
