### ISSUE TITLE
System.Runtime.Serialization.Formatters.pdb not found

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#107285] opened 2024-09-03 10:13 UTC
[Log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-107258-merge-2b87f1f71ea949479e/System.Runtime.Tests/1/console.a9923f60.log?helixlogtype=result)

```
MSBuild version 17.12.0-preview-24374-02+48e81c6f1 for .NET
/private/tmp/helix/working/AD00095A/w/ADF5094C/e/publish/ProxyProjectForAOTOnHelix.proj(116,5): error MSB3030: Could not copy the file "/tmp/helix/working/AD00095A/p/build/microsoft.netcore.app.runtime.ios-arm64/runtimes/ios-arm64/native/System.Runtime.Serialization.Formatters.pdb" because it was not found.
Signing bundle /tmp/helix/working/AD00095A/w/ADF5094C/e/System.Runtime.Tests.app
No embedded provisioning profile found at /tmp/helix/working/AD00095A/w/ADF5094C/e/System.Runtime.Tests.app/embedded.mobileprovision! Failed to sign the app!
```

## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=796046
Build error leg or test failing: System.Runtime.Tests

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": ["System.Runtime.Serialization.Formatters", "because it was not found"],
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=796110
**Error message validated:** `[System.Runtime.Serialization.Formatters because it was not found`]
**Result validation:** :x: Known issue did not match with the provided build.
**Validation performed at:** 9/3/2024 10:41:17 AM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by adamsitnik** [comment] 2024-09-03 13:00
Is it related to https://github.com/dotnet/runtime/pull/107079? cc @matouskozak @ivanpovazan

**Comment by matouskozak** [comment] 2024-09-03 13:17
> Yes, this was the error we were fixing (as reported in: #107029)
> 
> @pavelsavara the build you linked does not have any info ?

Here is a recent failure from `runtime` pipeline rolling-builds https://dev.azure.com/dnceng-public/public/_build/results?buildId=796046&view=logs&j=7f49df26-8126-5de3-bf2f-6ac6bde01830&t=c62b6a8c-bf71-5057-7f45-9c355fe0b802

**Comment by ivanpovazan** [comment] 2024-09-03 16:32
Previous fix was not enough, on rolling builds we seem to run tests with `DebuggerSupport=true` which requires pdbs to be passed as well.

**Comment by ivanpovazan** [comment] 2024-09-04 06:04
I am closing this as duplicate of https://github.com/dotnet/runtime/issues/107309 since Build Analysis seemed to match the pattern there.

**Closed by ivanpovazan** 2024-09-04 06:04 UTC
Labels: blocking-clean-ci, area-Infrastructure-mono, Known Build Error, binaryformatter-migration
