### ISSUE TITLE
Error in load assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1'

### ISSUE THREAD

**Issue by paulocarinhena** [dotnet/runtime#68023] opened 2022-04-14 13:56 UTC
### Description

This error happens when I distribute my application. Even when I send the correct dll:

System.IO.FileLoadException: "Could not load file or assembly "System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" or one of it's dependences. The found Assembly's manifest definition does not match the Assembly reference. (Exception from HRESULT: 0x80131040)"

Even sending the correct dll it just doesn't work.

### Reproduction Steps

Code error:

Usuario user = new Usuario();
user.Username = "teste";
user.Password = "teste";
user.Role = ".";

 string strJson = JsonSerializer.Serialize<Usuario>(user); <= Error

### Expected behavior

Not error in serialize object

### Actual behavior

Error in line serialize.

### Configuration

Net framework 4.8 in Windows 10 (c# Windows Forms)

**Comment by jeffschwMSFT** [comment] 2022-04-14 15:53
@paulocarinhena this seems to be impacting .NET Framework, correct?  Can you share a repro and file this issue via VS Feedback mechanism?  Thanks

**Comment by bfren** [comment] 2022-04-14 16:12
I'm getting this but where Version=7.0.0.0 since updating packages to .NET 7 Preview 3 - the issue appears to be with the System.Text.Json package.  Downgrading to Preview 2 makes it go away.

**Comment by eiriktsarpalis** [comment] 2022-04-14 17:04
Hi @paulocarinhena could you possibly share a reproducing project (in a zip or a repo) that showcases the issue? Thanks!

**Comment by jkotas** [comment] 2022-04-14 18:22
This should be fixed by https://github.com/dotnet/runtime/pull/67385

**Comment by bfren** [comment] 2022-04-14 20:17
Was that merge in the net7 preview 3 packages released yesterday?

**Comment by jkotas** [comment] 2022-04-14 20:25
#67385 is not in preview3. It will be in preview4.

**Comment by bfren** [comment] 2022-04-14 21:33
That does make preview 3 kind of unusable though 😂

**Comment by eiriktsarpalis** [comment] 2022-04-15 09:09
Duplicate of #67385.

**Comment by bfren** [comment] 2022-05-11 06:29
@eiriktsarpalis I know this marked as a duplicate but a) I can't respond in #67385, and b) this is still a problem in .NET 7 Preview 4.  I've just updated and run my unit tests and all the JSON-based tests are failing with the same exception:

```
Could not load type 'System.Runtime.CompilerServices.Unsafe' from assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

Is this because the Unsafe package is not being published to NuGet, which has no preview versions after .NET 7 Preview 2?

![Screenshot 2022-05-11 072554](https://user-images.githubusercontent.com/17511478/167782660-ecb1ffbc-7581-46b2-b672-1ec710546799.jpg)

**Comment by jkotas** [comment] 2022-05-11 15:34
> Is this because the Unsafe package is not being published to NuGet, which has no preview versions after .NET 7 Preview 2?

The Unsafe package is not going to be published to NuGet anymore. It is by design. The last stable version of the package is 6.0.0.

> Could not load type 'System.Runtime.CompilerServices.Unsafe' from assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

This error means that you are building against 7.0 Preview 3 or newer reference assemblies, but you are running against 7.0 Preview 2 or older runtime. Please make sure to update both the runtime and the reference assemblies to latest Preview.

**Comment by bfren** [comment] 2022-05-11 19:03
OK thanks I'll give that ago. Apologies.

**Closed** 2022-06-10 00:02 UTC
Labels: area-System.Text.Json, untriaged, no-recent-activity, needs-author-action
