### ISSUE TITLE
System.Text.Json Serialize ignores Properties from base interfaces

### ISSUE THREAD

**Issue by jogibear9988** [dotnet/runtime#73021] opened 2022-07-28 20:44 UTC
### Description

If you have a Interface wich inherits from a Basic one, System.Text.Json only serializes the Properties from the Interface specified.
This has nothing to do with polymorphism, cause I've got a instance of the derived interface.
(Look, my Object Variable is of Type B, and Type B should include the Properties of Type A)

### Reproduction Steps

Try this Code:

        interface A
        {
            string NameA { get; }
        }

        interface B : A
        {
            string NameB { get; }
        }

        public class C : B
        {
            public string NameA => "A";
            public string NameB => "B";
        }

        [Test]
        public void TestSystemTextJson()
        {
            B obj = new C();
            var text = System.Text.Json.JsonSerializer.Serialize(obj);
        }

### Expected behavior

The result should be:

        {"NameA":"A","NameB":"B"}

### Actual behavior

The result is:

    {"NameB":"B"}

### Configuration

.Net6 latest Service Pack
Windows 10
x64

**Comment by eiriktsarpalis** [comment] 2022-07-28 21:19
Thanks for reporting. I believe this is a duplicate of #41749.

**Closed** 2022-07-28 21:19 UTC
Labels: area-System.Text.Json, untriaged
