### ISSUE TITLE
ODBC connection is not working with .NetCore 3.0 and 3.1 

### ISSUE THREAD

**Issue by deepan-1984** [dotnet/runtime#32152] opened 2020-02-11 10:16 UTC
# Issue Title

ODBC connection is not working with .NetCore 3.0 and 3.1 

# General
Getting below error with >net core 3.0 and 3.1 version working with Net Core 2.0 
ERROR [IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified

**Comment by deepan-1984** [comment] 2020-02-12 11:32
> Can you please provide some code demonstrating the issue?
with NetCore 3.0
![image](https://user-images.githubusercontent.com/50020399/74331300-678ffe80-4db9-11ea-83cb-507f86554d88.png)

**Comment by saurabh500** [comment] 2020-03-08 22:48
This is a duplicate of https://github.com/dotnet/runtime/issues/32105 from the same issue author. Closing.

**Closed by saurabh500** 2020-03-08 22:48 UTC
Labels: area-System.Data, untriaged
