### ISSUE TITLE
Wrong ContentRoot when built with /p:PublishSingleFile

### ISSUE THREAD

**Issue by ststeiger** [dotnet/runtime#40828] opened 2020-08-14 08:04 UTC
I'm building a .NET Core 3.1 Service with this option: 
`dotnet publish -r win-x86 -c Release /p:PublishSingleFile=true -o D:\inetpub\RamMonitor`

I'm setting the ContentRoot
```
string programDirectory = System.IO.Path.GetDirectoryName(typeof(Program).Assembly.Location);
string executablePath = System.Diagnostics.Process.GetCurrentProcess().MainModule.FileName;
string executableDirectory = System.IO.Path.GetDirectoryName(executablePath);

if ("dotnet".Equals(executable, System.StringComparison.InvariantCultureIgnoreCase))
{
    s_logger.Log(Logging.LogLevel_t.Information, "Executable is dotnet");
    s_logger.Log(Logging.LogLevel_t.Information, "Program Directory: {0}", programDirectory);
    builder.UseContentRoot(programDirectory);
}
else
{
    s_logger.Log(Logging.LogLevel_t.Information, "Executable is NOT dotnet");
    s_logger.Log(Logging.LogLevel_t.Information, "Executable Directory: {0}", executableDirectory);
    builder.UseContentRoot(executableDirectory);
}
```
The logger shows:
```
Executable is NOT dotnet
Executable Directory: D:\inetpub\LdapService
```
I also set `config.SetBasePath(executableDirectory);` in ConfigureHostConfiguration. 

But then, in ConfigureAppConfiguration
```
IHostEnvironment env = hostingContext.HostingEnvironment;
s_logger.Log(Logging.LogLevel_t.Information, "ContentRootPath: {0}", env.ContentRootPath);
```
it shows `ContentRootPath: C:\WINDOWS\TEMP\.net\LdapService\nmv05eyy.ngz\`...

That's the wrong ContentRoot Path ! 
Also, it is not the contentRoot path that has been set EXPLICITLY, and SetBasePath seems to be IGNORED as well. 

Consequently, `config.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)`
fails silently, because optional: false is set, and then the program does some rubbish, for yet unknonw reason (I set default-values which seem to be ignored). 
As a consequence of this malfunction, the system's RAM usage is not monitored and corrected properly, and due to a bug in the .NET Framework (WebSockets), another malfunction is triggered in the ASP.NET worker process in IIS, which kills the worker process, and as a consequence of that, all customers whose Web-Application is on the same machine get 

> 503 Service Unavailable

...

Great work ! Keep it up - and soon you will be out of a job ... 

Project file for reference: 
```
<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>netcoreapp3.1</TargetFramework>
        <UserSecretsId>dotnet-RamMonitor-D01A4C22-E4F2-4466-BACD-59E42880C888</UserSecretsId>
        <PublishTrimmed>true</PublishTrimmed>
        <AssemblyName>LdapService</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="install.bat" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="install.bat" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="3.1.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="3.1.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="3.1.0" />
        <PackageReference Include="Microsoft.Extensions.Primitives" Version="3.1.2" />
        <PackageReference Include="Quartz" Version="3.0.7" />
        <PackageReference Include="System.Management" Version="4.7.0" />
    </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>


  <ItemGroup>
    <Content Update="install.bat">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  
</Project>

```

PS: 
Why is there a 
```
    <ItemGroup>
      <None Remove="install.bat" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="install.bat" />
    </ItemGroup>
```
for install.bat, but not for appsettings.json, when the IDE shows BuildAction="Content" for both install.bat and appsettings.json ?

**Comment by ststeiger** [comment] 2020-08-14 08:28
Source, for reproduction:

> dotnet publish -r win-x86 -c Release /p:PublishSingleFile=true -o D:\inetpub\RamMonitor


```
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.EventLog;


// Add package Microsoft.Extensions.Hosting.WindowsServices
// version 3.1.0
namespace RamMonitor
{
    
    
    public static class Program
    {
        private static Logging.TrivialLogger s_logger;

        private static string s_ProgramDirectory;
        private static string s_Current_Directory;
        private static string s_BaseDirectory;
        private static string s_ExecutablePath;
        private static string s_ExecutableDirectory;
        private static string s_Executable;


        private static void DisplayError(System.Exception ex)
        {
            System.Console.WriteLine(System.Environment.NewLine);
            System.Console.WriteLine(System.Environment.NewLine);
                
            System.Exception thisError = ex;
            while (thisError != null)
            {
                System.Console.WriteLine(ex.Message);
                System.Console.WriteLine(ex.StackTrace);
                    
                thisError = thisError.InnerException;

                if (thisError != null)
                {
                    System.Console.WriteLine(System.Environment.NewLine);
                    System.Console.WriteLine("Inner Exception:");
                } // End if (thisError != null) 

            } // Whend 
                
            System.Console.WriteLine(System.Environment.NewLine);
            System.Console.WriteLine(System.Environment.NewLine);
        } // End Sub DisplayError 


        static Program()
        {
            try
            {
                s_ProgramDirectory = System.IO.Path.GetDirectoryName(typeof(Program).Assembly.Location);
                s_Current_Directory = System.IO.Directory.GetCurrentDirectory();
                s_BaseDirectory = System.AppDomain.CurrentDomain.BaseDirectory;
                s_ExecutablePath = System.Diagnostics.Process.GetCurrentProcess().MainModule.FileName;
                s_ExecutableDirectory = System.IO.Path.GetDirectoryName(s_ExecutablePath);
                s_Executable = System.IO.Path.GetFileNameWithoutExtension(s_ExecutablePath);
                
                string logFilePath = null;
                string fileName = @"ServiceStartupLog.htm";
                
                if ("dotnet".Equals(s_Executable, System.StringComparison.InvariantCultureIgnoreCase))
                {
                    logFilePath = System.IO.Path.Combine(s_ProgramDirectory, fileName);
                }
                else
                {
                    logFilePath = System.IO.Path.Combine(s_ExecutableDirectory, fileName);
                }
                
                // s_logger = new Logging.HtmlLogger(@"D:\IDGLog.htm");
                s_logger = new Logging.HtmlLogger(logFilePath);
                
                s_logger.Log(Logging.LogLevel_t.Information, "Program Directory: {0}", s_ProgramDirectory);
                s_logger.Log(Logging.LogLevel_t.Information, "Current Directory: {0}", s_Current_Directory);
                s_logger.Log(Logging.LogLevel_t.Information, "Base Directory: {0}", s_BaseDirectory);
                s_logger.Log(Logging.LogLevel_t.Information, "Executable Path: {0}", s_ExecutablePath);
                s_logger.Log(Logging.LogLevel_t.Information, "Executable Directory: {0}", s_ExecutableDirectory);
                s_logger.Log(Logging.LogLevel_t.Information, "Executable: {0}", s_Executable);
            } // End Try 
            catch (System.Exception ex)
            {
                DisplayError(ex);
                System.Environment.Exit(ex.HResult);
            } // End Catch 
            
        } // End Static Constructor 
        
        
        public static void Main(string[] args)
        {
            try
            {
                CreateHostBuilder(args).Build().Run();
            }
            catch (System.Exception ex)
            {
                DisplayError(ex);
                s_logger.Log(Logging.LogLevel_t.Configuration, "EXXX: {0}", ex);
                System.Environment.Exit(ex.HResult);
            }

        } // End Sub Main 


        private static IHostBuilder CreateHostBuilder(string[] args)
        {
            IHostBuilder builder = new HostBuilder();
            
            try
            {
                // builder.UseContentRoot(System.IO.Directory.GetCurrentDirectory());
                // builder.UseContentRoot(System.IO.Path.GetDirectoryName(typeof(Program).Assembly.Location));
                // builder.UseContentRoot(System.AppContext.BaseDirectory);
                
                if ("dotnet".Equals(s_Executable, System.StringComparison.InvariantCultureIgnoreCase))
                {
                    s_logger.Log(Logging.LogLevel_t.Information, "Executable is dotnet");
                    builder.UseContentRoot(s_ProgramDirectory);
                }
                else
                {
                    s_logger.Log(Logging.LogLevel_t.Information, "Executable is NOT dotnet");
                    builder.UseContentRoot(s_ExecutableDirectory);
                }
                
                if (System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(System.Runtime.InteropServices.OSPlatform.Windows))
                {
                    // https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-3.1&tabs=visual-studio#app-configuration
                    // Requires Microsoft.Extensions.Hosting.WindowsServices
                    builder.UseWindowsService();
                }
                else if (System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(System.Runtime.InteropServices.OSPlatform.Linux))
                {
                    // https://devblogs.microsoft.com/dotnet/net-core-and-systemd/
                    // Requires Microsoft.Extensions.Hosting.WindowsServices
                    builder.UseSystemd(); // Add: Microsoft.Extensions.Hosting.Systemd
                }
                else if (System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(System.Runtime.InteropServices.OSPlatform.OSX))
                {
                    throw new System.NotImplementedException("Service for OSX Platform is NOT implemented.");
                }
                else
                {
                    throw new System.NotSupportedException("This Platform is NOT supported.");
                }
                
                builder.ConfigureHostConfiguration(
                    delegate (IConfigurationBuilder config)
                    {
                        // Has no effect ... 
                        // s_logger.Log(Logging.LogLevel_t.Information, "SetBasePath: {0}", s_ExecutableDirectory);
                        // config.SetBasePath(s_ExecutableDirectory);
                        
                        config.AddEnvironmentVariables(prefix: "DOTNET_");
                        if (args != null)
                        {
                            config.AddCommandLine(args);
                        } // End if (args != null) 

                    } // End Delegate 
                );
                
                builder.ConfigureAppConfiguration(
                        delegate (HostBuilderContext hostingContext, IConfigurationBuilder config)
                        {
                            IHostEnvironment env = hostingContext.HostingEnvironment;
                            // Completely wrong ... 
                            // s_logger.Log(Logging.LogLevel_t.Information, "ContentRootPath: {0}", env.ContentRootPath);

                            string appSettingsFile = System.IO.Path.Combine(s_ExecutableDirectory, "appsettings.json");
                            
                            // config.AddJsonFile("appsettings.json"
                            config.AddJsonFile(appSettingsFile, optional: false, reloadOnChange: true)
                                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true, reloadOnChange: true);
                            
                            if (env.IsDevelopment() && !string.IsNullOrEmpty(env.ApplicationName))
                            {
                                System.Reflection.Assembly appAssembly =
                                    System.Reflection.Assembly.Load(new System.Reflection.AssemblyName(env.ApplicationName));

                                if (appAssembly != null)
                                {
                                    config.AddUserSecrets(appAssembly, optional: true);
                                } // End if (appAssembly != null) 

                            } // End if (env.IsDevelopment() && !string.IsNullOrEmpty(env.ApplicationName))

                            config.AddEnvironmentVariables();

                            if (args != null)
                            {
                                config.AddCommandLine(args);
                            } // End if (args != null) 

                        } // End Delegate 
                    )
                    .ConfigureLogging(
                        delegate (HostBuilderContext hostingContext, ILoggingBuilder logging)
                        {
                            bool isWindows = System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(
                                    System.Runtime.InteropServices.OSPlatform.Windows
                            );

                            // IMPORTANT: This needs to be added *before* configuration is loaded, this lets
                            // the defaults be overridden by the configuration.
                            if (isWindows)
                            {
                                // Default the EventLogLoggerProvider to warning or above
                                logging.AddFilter<EventLogLoggerProvider>(level => level >= LogLevel.Warning);
                            } // End if (isWindows) 

                            // logging.ClearProviders();
                            logging.AddConfiguration(hostingContext.Configuration.GetSection("Logging"));

                            // https://www.codeproject.com/Articles/5255953/Use-Trace-and-TraceSource-in-NET-Core-Logging
                            // https://github.com/nreco/logging/tree/master/src/NReco.Logging.File
                            // https://github.com/adams85/filelogger
                            // https://docs.microsoft.com/en-us/dotnet/framework/debug-trace-profile/tracing-and-instrumenting-applications
                            logging.AddFileLogger(
                                delegate (FileLoggerOptions options)
                                {
                                    string postFix = System.DateTime.Now.ToString("yyyy'-'MM'-'dd'_'HH'-'mm'-'ss");

                                    options.LogFilePath = @"D:\LogFile_RamMonitor_"+ postFix + ".txt";
                                    options.LogLevel = LogLevel.Information;
                                }
                            );

                            logging.AddConsole();
                            logging.AddDebug();
                            logging.AddEventSourceLogger(); // is for Event Tracing.
                            // this uses Event Tracing for Windows (ETW)
                            // https://docs.microsoft.com/en-us/windows/win32/etw/event-tracing-portal

                            if (isWindows)
                            {
                                // Add the EventLogLoggerProvider on windows machines
                                logging.AddEventLog(); // this is for Windows Event Log 
                            } // End if (isWindows) 

                        } // End Delegate 
                    )
                    .ConfigureServices(
                        delegate (HostBuilderContext hostingContext, IServiceCollection services)
                        {
                            // AWSSDK.Extensions.NETCore.Setup
                            // AWSSDK.SQS
                            // Microsoft.VisualStudio.Azure.Containers.Tools.Targets

                            // AWS Configuration
                            // AWSOptions options = hostingContext.Configuration.GetAWSOptions();
                            // services.AddDefaultAWSOptions(options);
                            // services.AddAWSService<IAmazonSQS>();

                            // Worker Service
                            services.AddHostedService<Worker>();
                        } // End Delegate 
                    )
                    .UseDefaultServiceProvider(
                        delegate (HostBuilderContext hostingContext, ServiceProviderOptions options)
                        {
                            bool isDevelopment = hostingContext.HostingEnvironment.IsDevelopment();
                            options.ValidateScopes = isDevelopment;
                            options.ValidateOnBuild = isDevelopment;
                        } // End Delegate 
                    );

                // throw new System.Exception("wade", new System.Exception("hade"));
            }
            catch (System.Exception ex)
            {
                s_logger.Log(Logging.LogLevel_t.Configuration, "EXXX: {0}", ex);

                System.Console.WriteLine(ex.Message);
                System.Console.WriteLine(ex.StackTrace);
                System.Console.WriteLine();
                System.Console.WriteLine(System.Environment.NewLine);
                System.Environment.Exit(1);
            }

            return builder;
        } // End Function CreateHostBuilder 


        private static IHostBuilder OldCreateHostBuilder(string[] args)
        {
            // return Host.CreateDefaultBuilder(args).ConfigureServices((hostContext, services) => { services.AddHostedService<Worker>(); });

            return Host.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration(
                    delegate (HostBuilderContext hostingContext, IConfigurationBuilder config)
                    {
                        IConfigurationRoot builder = new ConfigurationBuilder()
                            .SetBasePath(System.IO.Directory.GetCurrentDirectory())
                            .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                            .AddJsonFile($"appsettings.{hostingContext.HostingEnvironment.EnvironmentName}.json",
                                optional: true, reloadOnChange: true)
                            .AddEnvironmentVariables()
                            .Build();
                    } // End Delegate 
                )
                .ConfigureServices(
                    delegate (HostBuilderContext hostingContext, IServiceCollection services)
                    {
                        // AWSSDK.Extensions.NETCore.Setup
                        // AWSSDK.SQS
                        // Microsoft.VisualStudio.Azure.Containers.Tools.Targets

                        // AWS Configuration
                        // AWSOptions options = hostingContext.Configuration.GetAWSOptions();
                        // services.AddDefaultAWSOptions(options);
                        // services.AddAWSService<IAmazonSQS>();

                        // Worker Service 
                        services.AddHostedService<Worker>();
                    } // End Delegate 
                );
        } // End Function OldCreateHostBuilder 


    } // End Class Program 


} // End Namespace RamMonitor 

```

**Comment by eerhardt** [comment] 2020-08-17 23:54
Thanks for the bug report, @ststeiger.

I'm having a hard time repro'ing your reported behavior. Can you help me out? I can't get the above code to compile. Using the `.csproj` listed, and the above Program.cs, I get the following compile errors:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'Logging' could not be found (are you missing a using directive or an assembly reference?)	TestWrongContentRoot	F:\DotNetTest\TestWrongContentRoot\Program.cs	16	Active
Error	CS0246	The type or namespace name 'Logging' could not be found (are you missing a using directive or an assembly reference?)	TestWrongContentRoot	F:\DotNetTest\TestWrongContentRoot\Program.cs	76	Active
Error	CS0103	The name 'Logging' does not exist in the current context	TestWrongContentRoot	F:\DotNetTest\TestWrongContentRoot\Program.cs	78	Active
Error	CS0103	The name 'Logging' does not exist in the current context	TestWrongContentRoot	F:\DotNetTest\TestWrongContentRoot\Program.cs	79	Active
Error	CS0103	The name 'Logging' does not exist in the current context	TestWrongContentRoot	F:\DotNetTest\TestWrongContentRoot\Program.cs	80	Active
Error	CS0103	The name 'Logging' does not exist in the current context	TestWrongContentRoot	F:\DotNetTest\TestWrongContentRoot\Program.cs	81	Active
```

It looks like I can't find:

```C#
        private static Logging.TrivialLogger s_logger;
```

or

```C#
                s_logger = new Logging.HtmlLogger(logFilePath);
```

I went ahead and commented out the usages of `s_logger` so I could move past it. I got the program running, and I wasn't able to repro the reported:

```
                builder.ConfigureAppConfiguration(
                        delegate (HostBuilderContext hostingContext, IConfigurationBuilder config)
                        {
                            IHostEnvironment env = hostingContext.HostingEnvironment;
                            // Completely wrong ... 
                            // s_logger.Log(Logging.LogLevel_t.Information, "ContentRootPath: {0}", env.ContentRootPath);
```

If I `Console.WriteLine` the value of `env.ContentRootPath` at that time, I see the folder I published to: `F:\inetpub\RamMonitor`.

The command line I used was:

```
dotnet publish -r win-x86 -c Release /p:PublishSingleFile=true -o F:\inetpub\RamMonitor
F:\inetpub\RamMonitor\LdapService.exe
```

Do you think you could create a .zip file of a complete project that reproduces the issue? Or maybe create a new git repository with the program in it that I could publish locally?

Another question: How are you executing the `LdapService.exe`? Are you invoking it from the commandline? Or through some other mechanism?

**Comment by ststeiger** [comment] 2020-08-19 15:15
@eerhardt:
Here you go: https://gofile.io/d/6XrTdc

With AddJsonFile as mentioned above:
```
config.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
   .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true, reloadOnChange: true);
```

**Comment by eerhardt** [comment] 2020-08-19 16:10
> With AddJsonFile as mentioned above:

Is there also another workaround that needs to be removed to see the bug? In `CreateHostBuilder` I see:

```C#
builder.UseContentRoot(s_ContentRootDirectory);
```

I believe this is working around the bug as well. If I remove that line,a nd change the AddJsonFile as above, then I see:

```
The configuration file 'appsettings.json' was not found and is not optional. The physical path is 'C:\Users\eerhardt\AppData\Local\Temp\.net\RamMonitor\t5xcud2o.0cc\appsettings.json'.
```

That is the problem you are reporting, right? Assuming it is, I think I know understand the issue(s).

### Issue 1 - AppContext.BaseDirectory is "wrong" in PublishSingleFile for 3.0

This is a duplicate of https://github.com/dotnet/runtime/issues/3704. It is being documented according to https://github.com/dotnet/runtime/issues/38405#issuecomment-652643506. The good new is that this was fixed in net5.0 PublishSingleFile. When targeting .NET 5, and publishing a single file, AppContext.BaseDirectory will point to the directory of the .exe.

The reason this affects you is because by default the `hostingContext.HostingEnvironment.ContentRootPath` gets its value from `AppContext.BaseDirectory`. Calling `builder.UseContentRoot(path)` with the correct path, as what you were doing, is the correct workaround. It will override the incorrect default of `AppContext.BaseDirectory`, and use the path you specify.

### Issue 2 - config.SetBasePath has no effect

The problem you are hitting here is that there are 2 separate "configurations":

1. The "Host" configuration - this configures the Hosting system. This is done in `builder.ConfigureHostConfiguration`.
2. The "App" configuration - this configures the application itself. This is done in `builder.ConfigureAppConfiguration`.

In your code, you were calling `config.SetBasePath` inside of the `ConfigureHostConfiguration` delegate. So that was affecting the Hosting system's configuration - which basically is going unused.

If instead, you moved the `config.SetBasePath` to the `ConfigureAppConfiguration` delegate, this would tell the file system to use the path you specified, instead of the incorrect default - which is based off `AppContext.BaseDirectory`. The `HostingEnvironment.ContentRootPath` will still be incorrectly set to the `%TEMP%` directory that `AppContext.BaseDirectory` returns, but the call to `config.AddJsonFile("appsettings.json", optional: false` will now pass and your service runs.

_____

So in the end, to work around this underlying bug, you should continue to use `builder.UseContentRoot` to override the default behavior.

I'm going to close this issue as answered, and as a duplicate of #3704. If I didn't answer your questions, or misunderstood something, please re-open. If you need to re-open, please upload a repro project that reproduces the problem without modification.

**Closed** 2020-08-19 16:10 UTC
Labels: area-Extensions-Hosting, needs more info

**Comment by eerhardt** [comment] 2020-08-19 19:29
One more piece of information that I discovered while investigating another issue:

When a normal ASP.NET application loads, it sets its `ContentRootPath` to `Directory.GetCurrentDirectory()` in `CreateDefaultBuilder`:

https://github.com/dotnet/runtime/blob/aa5fdab9654d74bc6274c0b5d820272c8e859621/src/libraries/Microsoft.Extensions.Hosting/src/Host.cs#L56-L60

That's why a basic ASP.NET app isn't broken by PublishSingleFile - it is getting its content root set to the current working directory, and doesn't fallback to the `AppContext.BaseDirectory` value. This solidifies my advice above - calling `UseContentRoot` yourself is the correct workaround for this issue. That will no longer be needed in `net5.0`.

**Comment by ststeiger** [comment] 2020-08-20 13:55
> If instead, you moved the config.SetBasePath to the ConfigureAppConfiguration delegate

Ah, damn, I see. 
Small but mean difference. 
Well, theoretically, IHostEnvironment is correct, the host is actually there. 
But then, what it would needed is an IAppEnvironment as well, because the two are not equal under ShadowCopy/PublishSingleFile. 

Looking forward to .NET 5.0 which no longer shadow-copies. 
Bonus points if it could also statically link native libs ;)

One more question:
BackgroundService does not have a "Pause"-function. 
Windows-Services used to. 
Not that I would mind, IMHO it never made any sense, but is Pause going away indefinitely, or coming later ? 
Or is it just executing stop and start behind the scene ?

**Comment by ststeiger** [comment] 2020-08-20 14:04
Oh, also, something for the SQL-Server team:
I had SQL-Server 2016 instance: hostname\SQLExpress 
That was upgraded to SQL-Server 2019. 
New instance-name: HOSTNAME

That changed the service name of of SQL-Server, and any service that depends on sql-server (MSSQLExpress-service)  fails to start. 
The old service name doesn't show up under "dependencies" in services.msc 
Also it can't be removed or changed by GUI. 
Needed to do that in the registry. 
Not a problem, but had no rights to do so. 

IMHO, the SQL-Server installer should fix that. 
Also, services.msc should show orphaned dependencies (maybe in red), and not no-dependencies instead, which is plain wrong. 
Since there is no public bugtracker...

**Comment by eerhardt** [comment] 2020-08-20 15:09
> BackgroundService does not have a "Pause"-function.
Windows-Services used to.
Not that I would mind, IMHO it never made any sense, but is Pause going away indefinitely, or coming later ?
Or is it just executing stop and start behind the scene ?

I don't know of any plans to support a "Pause"-function.  #35991 speaks of it a little, but it doesn't sound like there was much support for that feature.

If you have a scenario for needing it, can you open a new issue with a description of why it would be useful?
