### ISSUE TITLE
Dynamic structure alignment by IntPtr.Size

### ISSUE THREAD

**Issue by NN---** [dotnet/runtime#61107] opened 2021-11-02 17:35 UTC
There are use cases where structure has different alignment in 32 and 64 bits.
It would be very useful to be able to align structure by size of pointer or its derivative.

```C#
[StructLayout(LayoutKind.Sequential, Pack = IntPtr.Size)]
struct MyStruct
{
   public int I;
}
```     

A possible solution mentioned in #33899 is to use two structures and introduce an interface.
However it means boxing and requires defining properties instead of simple fields.
Much more convenient solution is to allow packing depending on IntPtr.Size.

P.S.
It would be also nice to allow IntPtr.Size usage in arrays marshaling:

```C#
[StructLayout(LayoutKind.Sequential, Pack = IntPtr.Size)]
public value struct typeData
{
   [MarshalAs(UnmanagedType.ByValArray, SizeConst = IntPtr.Size)] byte[] a1;
}
```

**Comment by NN---** [comment] 2021-11-02 17:39
area-Infrastructure

**Comment by jkotas** [comment] 2021-11-02 19:28
Duplicate of #60573

**Closed by jkotas** 2021-11-02 19:28 UTC
Labels: untriaged
