### ISSUE TITLE
.net 8 AOT Published files Windows run with environment variable do not work

### ISSUE THREAD

**Issue by Seabizkit** [dotnet/runtime#107227] opened 2024-08-31 14:14 UTC
### Description

im trying to run the app with 
```
ASPNETCORE_ENVIRONMENT=Development
```

seem to work run when running from vs and setting it, but when published no matter what you do 

```
var environment = app.Environment.IsDevelopment();
```
is always false.
but 
```
var env = builder.Environment.EnvironmentName;
Console.WriteLine($"Environment: {env}");
```
reports correctly

### Reproduction Steps

```csharp
using Microsoft.AspNetCore.Server.Kestrel.Core;
using Microsoft.OpenApi.Any;
using Microsoft.OpenApi.Models;
using Paradox.TextReaderAPI.Code;
using Paradox.TextReaderAPI.Extensions;
using Paradox.TextReaderAPI.Interfaces;
using Paradox.TextReaderAPI.Services;
using Paradox.TextReaderCommon;
using System.Diagnostics;

var builder = WebApplication.CreateSlimBuilder(args);
builder.WebHost.UseKestrelHttpsConfiguration();

var env = builder.Environment.EnvironmentName;
Console.WriteLine($"Environment: {env}");
// Add services to the container.
builder.Logging.AddConsole();
builder.Services.Configure<KestrelServerOptions>(options =>
{
    options.Limits.MaxRequestBodySize = int.MaxValue; // if don't set default value is: 30 MB
});


builder.Services.ConfigureHttpJsonOptions(options =>
{
    options.SerializerOptions.TypeInfoResolverChain.Insert(0, MyJsonContext.Default);
});

builder.Services.AddControllers().AddJsonOptions(options =>
{
    options.JsonSerializerOptions.TypeInfoResolver = MyJsonContext.Default;
    //options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter());
});
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "My API", Version = "v1" });

    // Explicitly map EnumTextReader
    c.MapType<EnumTextReader>(() => new OpenApiSchema
    {
        Type = "string",
        Enum = Enum.GetNames(typeof(EnumTextReader))
                   .Select(name => new OpenApiString(name))
                   .ToList<IOpenApiAny>()
    });
});

builder.Services.AddResponseCompression();

builder.Services.AddHealthChecks();

var app = builder.Build();

var stopwatch = Stopwatch.StartNew();
app.Lifetime.ApplicationStarted.Register(() =>
{
    stopwatch.Stop();
    Console.WriteLine($"Application started in {stopwatch.ElapsedMilliseconds} ms");
});
// Configure the HTTP request pipeline.
var environment = app.Environment.IsDevelopment();
app.Logger.LogInformation($"IsDevelopment:{environment}");
if (environment)
{
    app.UseSwagger();
    app.UseSwaggerUI();

    // Redirect root URL to Swagger UI
    app.Use(async (context, next) =>
    {
        if (context.Request.Path == "/")
        {
            context.Response.Redirect("/swagger");
        }
        else
        {
            await next();
        }
    });
}

app.MapHealthChecks("_health");

//app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();

```

### Expected behavior

if i set ASPNETCORE_ENVIRONMENT=Development 

app.Environment.IsDevelopment();

should be true

### Actual behavior

its false

### Configuration

.net 8 
AOT
Win64
Self-contained

**Comment by agocke** [comment] 2024-08-31 14:45
@eerhardt  didn’t asp somehow disable development mode for aot?

**Comment by Seabizkit** [comment] 2024-09-02 07:24
> > @eerhardt didn’t asp somehow disable development mode for aot?
> 
> No, this should work just fine.
> 
> PS: This application is using methods that aren't AOT friendly (MapControllers)

thanks for taking the time to look, so i took the time to rule out MapControllers

here is what i have now and am testing with ....

'''csharp
using Microsoft.AspNetCore.Server.Kestrel.Core;
using Paradox.TextReaderAPI.Code;
using Paradox.TextReaderAPI.Extensions;
using Paradox.TextReaderAPI.Interfaces;
using Paradox.TextReaderAPI.Services;
using Paradox.TextReaderCommon;
using System.Diagnostics;

var builder = WebApplication.CreateSlimBuilder(args);
builder.WebHost.UseKestrelHttpsConfiguration();

var env = builder.Environment.EnvironmentName;
Console.WriteLine($"Environment: {env}");
// Add services to the container.
builder.Logging.AddConsole();
builder.Services.Configure<KestrelServerOptions>(options =>
{
    options.Limits.MaxRequestBodySize = int.MaxValue; // if don't set default value is: 30 MB
});

builder.Services.ConfigureHttpJsonOptions(options =>
{
    options.SerializerOptions.TypeInfoResolverChain.Insert(0, MyJsonContext.Default);
});
// Add services to the container.
builder.Services.AddScoped<ITextReaderService, TextReaderService>();
builder.Services.AddTextReaderFactory<ITextReaderFactory, TextReaderFactory>();

builder.Services.AddResponseCompression();
builder.Services.AddHealthChecks();
var app = builder.Build();

var stopwatch = Stopwatch.StartNew();
app.Lifetime.ApplicationStarted.Register(() =>
{
    stopwatch.Stop();
    Console.WriteLine($"Application started in {stopwatch.ElapsedMilliseconds} ms");
});
// Configure the HTTP request pipeline.
var environment = app.Environment.IsDevelopment();
app.Logger.LogInformation($"IsDevelopment:{environment}");
if (environment)
{
    app.MapGet("/car", () => "testing!");
}

app.MapHealthChecks("_health");
app.MapGet("/", () => "Hello World!");

var todosApi = app.MapGroup("/todos");
todosApi.MapGet("/", () => { return "car"; });

app.Run();

'''

this is what im using to run var cmd on windows
```
set ASPNETCORE_ENVIRONMENT=Development && Paradox.TextReaderAPI.exe
```

here is the out put

![image](https://github.com/user-attachments/assets/172e47de-2dcf-4b9b-a3e4-fb4a7e60067e)

i can hit all the other endpoint but cant hit the /car one which kind of makes sense
Except it should be in environment Development so IsDevelopment should be **true**

**Comment by eerhardt** [comment] 2024-09-03 17:10
> this is what I'm using to run via CMD on windows

> set ASPNETCORE_ENVIRONMENT=Development && Paradox.TextReaderAPI.exe

This is adding an extra space ` ` to the end of the environment variable value.

![image](https://github.com/user-attachments/assets/438449a5-72b0-44fe-bcd0-46d059e58da5)

You need to set the environment variable to only `Development` without the space at the end.

Closing as this is by design.

**Closed by eerhardt** 2024-09-03 17:10 UTC
Labels: untriaged, area-NativeAOT-coreclr
