### ISSUE TITLE
EncodingExtensions.Convert throws ArgumentOutOfRangeException decoding sliced single-segment ReadOnlySequence

### ISSUE THREAD

**Issue by gix** [dotnet/runtime#45346] opened 2020-11-30 08:56 UTC
### Description

Calling [`EncodingExtensions.Convert`](https://docs.microsoft.com/en-us/dotnet/api/system.text.encodingextensions.convert?view=net-5.0#System_Text_EncodingExtensions_Convert_System_Text_Decoder_System_Buffers_ReadOnlySequence_System_Byte___System_Buffers_IBufferWriter_System_Char__System_Boolean_System_Int64__System_Boolean__) to decode a sliced ReadOnlySequence with only one segment or a backing array throws `ArgumentOutOfRangeException`:
```
Specified argument was out of the range of valid values. (Parameter 'position')
   at System.ThrowHelper.ThrowArgumentOutOfRangeException_PositionOutOfRange()
   at System.Buffers.ReadOnlySequence`1.BoundsCheck(SequencePosition& position, Boolean positionIsNotNull)
   at System.Text.EncodingExtensions.Convert(Decoder decoder, ReadOnlySequence`1& bytes, IBufferWriter`1 writer, Boolean flush, Int64& charsUsed, Boolean& completed)
```

As far as I can tell, `ReadOnlySequence<T>.GetFirstSpan` returns a defaulted `SequencePosition next` in these cases, but `0` is not a valid position in the sliced sequence.

Small repro (just create a new .NET 5.0 console app):
```C#
using System;
using System.Buffers;
using System.Text;

class Program
{
    static void Main()
    {
        var writer = new ArrayBufferWriter<char>();
        var bytes = new byte[] { (byte)'1', (byte)'2', (byte)'3' };

        var segment = new BufferSegment(bytes);
        segment.Append(bytes);
        var seq1 = new ReadOnlySequence<byte>(bytes);
        var seq2 = new ReadOnlySequence<byte>(segment, 0, segment, 3);
        var seq3 = new ReadOnlySequence<byte>(segment, 0, segment.Next, 3);

        // Backed by array
        Encoding.UTF8.GetDecoder().Convert(seq1, writer, false, out var _, out var _); // OK
        Encoding.UTF8.GetDecoder().Convert(seq1.Slice(1), writer, false, out var _, out var _); // Fails

        // Single-segment
        Encoding.UTF8.GetDecoder().Convert(seq2, writer, false, out var _, out var _); // OK
        Encoding.UTF8.GetDecoder().Convert(seq2.Slice(1), writer, false, out var _, out var _); // Fails

        // Multi-segment
        Encoding.UTF8.GetDecoder().Convert(seq3, writer, false, out var _, out var _); // OK
        Encoding.UTF8.GetDecoder().Convert(seq3.Slice(1), writer, false, out var _, out var _); // OK
    }

    class BufferSegment : ReadOnlySequenceSegment<byte>
    {
        public BufferSegment(Memory<byte> memory)
        {
            Memory = memory;
        }

        public BufferSegment Append(Memory<byte> memory)
        {
            var segment = new BufferSegment(memory) {
                RunningIndex = RunningIndex + Memory.Length
            };
            Next = segment;
            return segment;
        }
    }
}
```

### Configuration

* Which version of .NET is the code running on? **.NET 5.0.100**
* What OS and version, and what distro if applicable? **Windows 10**
* What is the architecture (x64, x86, ARM, ARM64)? **x64**
* Do you know whether it is specific to that configuration? **No, but I don't think it is specific to this configuration.**

**Comment by tarekgh** [comment] 2020-11-30 17:23
CC @GrabYourPitchforks

**Comment by GrabYourPitchforks** [comment] 2020-11-30 20:13
Error seems to be in how the encoding extensions call the internal helper method `GetFirstSpan`, as shown in __line 139__ below:

https://github.com/dotnet/runtime/blob/c8a97ff77957202323b64b8513f363366010343f/src/libraries/System.Memory/src/System/Text/EncodingExtensions.cs#L137-L145

The internal `GetFirstSpan` method outs a default _SequencePosition_ for a single-segment sequence. We probably need to create our own helper method rather than rely on that one.

**Comment by eiriktsarpalis** [comment] 2021-08-05 12:04
@GrabYourPitchforks is this something we should try to get fixed for .NET 6?

**Comment by GrabYourPitchforks** [comment] 2021-08-05 16:10
@eiriktsarpalis I don't have bandwidth to work on this for .NET 6. Since it's not a regression, it's falling below other work items in terms of priority. I'll move to .NET 7 for now and unassign from self, but feel free to move back if somebody wants to pick it up.

**Comment by eiriktsarpalis** [comment] 2021-08-05 16:50
Assigning to self, will try to tackle if I happen to have cycles towards the deadline.

**Closed** 2023-02-07 21:39 UTC
Labels: bug, area-System.Text.Encoding, in-pr
