### ISSUE TITLE
Incorrect method return on Android in Release mode

### ISSUE THREAD

**Issue by AndriySvyryd** [dotnet/runtime#96264] opened 2023-12-22 01:16 UTC
### Description

```C#
public class Property : IProperty
{
    public virtual List<Property>? RelatedProperties { get; set; }

    public virtual IEnumerable<Property> GetRelatedProperties()
        => RelatedProperties ?? Enumerable.Empty<Property>();

    IEnumerable<IReadOnlyProperty> IReadOnlyProperty.GetRelatedProperties()
        => GetRelatedProperties();

    IEnumerable<IProperty> IProperty.GetRelatedProperties()
        => GetRelatedProperties();
}
```

### Reproduction Steps

1. Clone https://github.com/AndriySvyryd/MauiApp9-NOAOT.git
2. Run Release on an Android emulator

### Expected behavior

All calls should return a non-null object

### Actual behavior

`((IReadOnlyProperty)property).GetRelatedProperties()` returns `null`

### Configuration

Android 13.0 - API 33, x86_64

**Comment by simonrozsival** [comment] 2024-01-04 12:22
I have only been able to reproduce the bug with a MAUI app and not with the runtime's sample Android app. I'm seeing the same bug also when running the same code on Mac Catalyst so it is not Android-specific but Mono specific.

I simplified the repro project to the following steps:

1. create a new maui app: `dotnet new maui`
2. update the `MauiProgram` class by adding the following snippet:
```c#
public static void Test()
{
	Console.WriteLine("All these should be True:");

	IProperty property = new Property();
	for (int i = 0; i < 3; i++)
	{
		Console.WriteLine($"Test {i}: {property.GetRelatedProperties() is not null}");
	}
}

public interface IProperty 
{
	static void AddPrincipals<T>() {}
	IEnumerable<IProperty> GetRelatedProperties();
}

public class Property : IProperty
{
	public virtual bool IsIndex() => false;
	public IEnumerable<IProperty> GetRelatedProperties() => Enumerable.Empty<Property>();
}
```
3. call `Test();` from `CreateMauiApp`
4. build and run the app on Android emulator using `dotnet build -t:Run -f net8.0-android -r android-arm64 -c Release`

Expected output:
```
All these should be True:
Test 0: True
Test 1: True
Test 2: True
```
Actual output:
```
All these should be True:
Test 0: True
Test 1: False
Test 2: False
```

Some observations:
- When `AddPrincipals<T>()` is changed into a non-generic `AddPrincipals()`, the bug doesn't manifest
- When I remove the `AddPrincipals<T>()` method or make it `static virtual`, the bug doesn't manifest
- When I remove the `IsIndex()` method or make it non-virtual, the app crashes with `SIGSEGV` on the second call to `GetRelatedProperties()` instead of producing invalid output
- When I change `AddPrincipals<T>()` to be `static virtual`, the bug doesn't manifest
- When I change the order of definitions of `AddPrincipals<T>()` and `GetRelatedProperties()` in `IProperty`, the bug doesn't manifest
- When I change `IProperty property = new Property();` to `Property property = new Property();`, the bug doesn't manfiest

/cc @lambdageek @vargaz

**Comment by fanyang-mono** [comment] 2024-01-10 22:44
Runtime's sample Android app uses Mono JIT.
Maui Android uses Mono AOT
Maui iOS & Mac Catalyst probably use Mono full AOT.

Thus, this could be a Mono AOT bug.

**Comment by fanyang-mono** [comment] 2024-01-11 05:01
I wasn't able to reproduce this issue with Mono AOT with or without LLVM or Mono LLVM full AOT. Will try the MAUI app tomorrow.

**Comment by fanyang-mono** [comment] 2024-01-11 20:55
I tried to reproduce this with Maui app like @simonrozsival showed earlier. This is what I found:

- I was able to reproduce it when using .NET8 SDK and maui workload
- I was not able to reproduce it any more when using .NET9 nightly built. It seems that this issue has been fixed in .NET9.

@vargaz @lambdageek Does this issue look like something you fixed recently for .NET9?

**Comment by vargaz** [comment] 2024-01-11 21:02
Nothing similar i can remember. If this is a generics issue, then maybe:
https://github.com/dotnet/runtime/pull/94437

**Comment by lambdageek** [comment] 2024-01-11 21:15
Repros in a console app with .NET 8.0.0

global.json:
```json
{
  "sdk": {
    "version": "8.0.100"
  }
}
```

foo.csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>full</TrimMode>
    <UseMonoRuntime>true</UseMonoRuntime>
    <SelfContained>true</SelfContained>
  </PropertyGroup>
</Project>
```

Program.cs:
```csharp
using System;
using System.Text;
namespace MauiApp9;

public interface IProperty : IReadOnlyProperty
{
    new IEnumerable<IProperty> GetRelatedProperties();
}

public interface IReadOnlyProperty 
{
    private static void AddPrincipals<T>()
    {
    }

    bool IsForeignKey();

    IEnumerable<IReadOnlyProperty> GetRelatedProperties();

    bool IsIndex();
}

public class Property : IProperty
{
    public virtual List<Property>? RelatedProperties { get; set; }

    public virtual bool IsForeignKey()
        => false;

    public virtual IEnumerable<Property> GetRelatedProperties()
        => RelatedProperties ?? Enumerable.Empty<Property>();

    public virtual bool IsIndex()
        => false;

    IEnumerable<IReadOnlyProperty> IReadOnlyProperty.GetRelatedProperties()
        => GetRelatedProperties();

    IEnumerable<IProperty> IProperty.GetRelatedProperties()
        => GetRelatedProperties();
}

public class P {
    public static void Main() {
        Console.WriteLine (Test());
    }
    public static string Test()
    {
        var property = new Property();

        var output = new StringBuilder();
        output.AppendLine("All these should be 0:");
        output.AppendLine("IReadOnly:\t" + (((IReadOnlyProperty)property).GetRelatedProperties()?.Count() ?? -1));

        Test(property, output);
        
        return output.ToString();
    }

    private static void Test(IReadOnlyProperty property, StringBuilder output)
    {
        output.AppendLine("IReadOnly:\t" + (((IReadOnlyProperty)property).GetRelatedProperties()?.Count() ?? -1));
        output.AppendLine("IProperty:\t" + (((IProperty)property).GetRelatedProperties()?.Count() ?? -1));
    }
}
```

```console
$ dotnet run
All these should be 0:
IReadOnly:	0
IReadOnly:	-1
IProperty:	0
```

**Comment by lambdageek** [comment] 2024-01-11 21:17
Does not repro with 8.0.101:

global.json:
```json
{
  "sdk": {
    "version": "8.0.101"
  }
}
```

```console
$ dotnet run
All these should be 0:
IReadOnly:	0
IReadOnly:	0
IProperty:	0
```

This is almost certainly https://github.com/dotnet/runtime/pull/94437 like @vargaz said.
it only reproduces for me if all the classes are in the `MauiApp9` namespace - which sounds like it's an IMT hash collision issue like in 94437

**Comment by fanyang-mono** [comment] 2024-01-11 21:22
Yeah, I just tried `SDK 8.0.101`. It is not reproducible there anymore. @AndriySvyryd Please try that SDK that we just released yesterday to see if it works for your project.

**Comment by lambdageek** [comment] 2024-01-11 21:25
@AndriySvyryd is your real use-case EFCore in a MAUI app?  These method names are the same as what IBM/RedHat reported when they were trying EFCore with Mono: https://github.com/dotnet/runtime/issues/93770#issuecomment-1784521219

**Comment by AndriySvyryd** [comment] 2024-01-11 21:51
> Yeah, I just tried SDK 8.0.101. It is not reproducible there anymore. @AndriySvyryd Please try that SDK (downloading from [dotnet.microsoft.com/en-us/download/dotnet/8.0](https://dotnet.microsoft.com/en-us/download/dotnet/8.0)) that we just released yesterday to see if it works for your project.

I can no longer repro with 8.0.101

> @AndriySvyryd is your real use-case EFCore in a MAUI app? These method names are the same as what IBM/RedHat reported when they were trying EFCore with Mono: https://github.com/dotnet/runtime/issues/93770#issuecomment-1784521219

Yes, these issues were reported when using EFCore in a MAUI app https://github.com/dotnet/efcore/issues/32553, https://github.com/dotnet/efcore/issues/32040. I created a non-EF repro to make them easier to debug.

**Comment by fanyang-mono** [comment] 2024-01-11 22:04
I am going to close this issue, as it has been fixed in the .NET8 SDK 8.0.101.

**Closed by fanyang-mono** 2024-01-11 22:04 UTC
Labels: area-Codegen-JIT-mono
