### ISSUE TITLE
DotNet MAUI with .Net 7 fails to open Websocket in Android Foreground Service

### ISSUE THREAD

**Issue by genifycom** [dotnet/runtime#93226] opened 2023-10-07 16:19 UTC
### Description

If you take Carl Franklins android foreground service  https://github.com/carlfranklin/MAUIAndroidFS and replace SignalR with WebSockets, the websocket fails to connect in the Android Foreground service.

I took the service code and changed it to use WebSockets instead of a HubConnection.

The service starts up fine, and on the startup creates the Websocket

ClientWebSocket client = new();

In the OnStartCommand I try connecting the Socket to a wss endpoint

await client.ConnectAsync(new Uri("wss://mywssendpoint/"), cts.Token);

Interestingly, this line sits indefinitely. It does not appear to timeout or fail (e.g. in try-catch block).

This is with MAUI Blazor using .Net 7

Does anyone have any idea what might be wrong here?

### Steps to Reproduce

Take the sample at https://github.com/carlfranklin/MAUIAndroidFS and replace SignalR with WebSockets in MAUI .Net 7

### Version with bug

7.0.92

### Is this a regression from previous behavior?

Not sure, did not test other versions

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

None

### Relevant log output

```shell
No error. The client.ConnectAsync simply sits there without error and never completes.
```

**Comment by steveisok** [comment] 2023-10-09 15:40
@mdh1418 please triage and see if you can reproduce. I'm curious what happens when you set `<UseNativeHttpHandler>false</UseNativeHttpHandler>` in your csproj.

**Comment by vitek-karas** [comment] 2024-06-26 17:30
@simonrozsival could you try to repo on 8 and see if this is something we should look into more?

**Comment by simonrozsival** [comment] 2024-07-12 13:19
@genifycom I am having trouble reproducing the issue for several reasons:
- I am not sure how to modify the linked project to replace SignalR with WebSocketClient. The `OnStartCommand` is not async so I am not sure how you modified the code to use `await`.
- I don't know what your web socket server looks like and how you deploy it for testing.

I am closing this issue for now, but feel free to reopen it or open a new issue if you can provide a fully functional repro project that can be easily deployed locally.

**Closed by simonrozsival** 2024-07-12 13:19 UTC
Labels: area-System.Net, os-android, untriaged
