### ISSUE TITLE
[wasm] broken .locals init

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#71425] opened 2022-06-29 09:57 UTC
New unit test `System.Runtime.InteropServices.JavaScript.Tests.JavaScriptTests`
 showing that it takes 1000 calls to JS to expose un-initialised `out int something` argument on icall.
Only when in Release and with `[MethodImpl(MethodImplOptions.AggressiveInlining)]`

Repro https://github.com/dotnet/runtime/pull/71387

[log trace](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-71387-merge-96c9ca01899846faba/normal-System.Private.Runtime.InteropServices.JavaScript.Tests/1/console.de98dbbc.log?helixlogtype=result)
```
  info: mono_wasm_do_nothing ptr: 46277408 value: 0
  info: I 997
  info: mono_wasm_do_nothing ptr: 46277408 value: 0
  info: I 998
  info: mono_wasm_do_nothing ptr: 46277408 value: 0
  info: I 999
  info: mono_wasm_do_nothing ptr: 46277360 value: 999
```

Note the change of the pointer on the last line.

**Comment by pavelsavara** [comment] 2022-06-29 15:53
@BrzVlad

**Comment by lewing** [comment] 2022-07-08 02:16
cc @SamMonoRT

**Comment by BrzVlad** [comment] 2022-07-09 11:09
Closing this as duplicate of https://github.com/dotnet/runtime/issues/37955

**Closed by BrzVlad** 2022-07-09 11:09 UTC
Labels: arch-wasm, area-System.Runtime.InteropServices.JavaScript
