### ISSUE TITLE
Slow file access times when accessing NFS server

### ISSUE THREAD

**Issue by DomiStyle** [dotnet/runtime#48757] opened 2021-02-25 12:09 UTC
### Description

NFS performance is awful in .NET while Python and Bash have no problem accessing files at expected speeds.

As the tests below show, .NET needs around 6 seconds to access a file on an NFS share, doesn't matter if reading or writing. File size doesn't matter, access times are slow. Creating folders, deleting folders and deleting files works normally.

### Configuration

.NET 5.0.103
Ubuntu 20.04.2 LTS x64 (with 5.11 kernel)
Issue happens on all my .NET applications across various Linux distros

### Regression?

Didn't work since at least the introduction of .NET Core 3.0

### Other information

Test files are available [in this repository](https://github.com/DomiStyle/dotnet-nfs-test).

All times in milliseconds

Network speed according to iperf3: 9.13 Gbits/sec
Files on NFS server are on HDD

**1GB file size**

Shell:

    From local to NFS: 10847
    From NFS to local: 636

.NET:

    From local to NFS: 16814
    From NFS to local: 6776
    Time to create folder: 3
    Time to delete folder: 0
    Time to create 10MB file: 6252
    Time to read 10MB file: 6235
    Time to delete 10MB file: 1

Python:

    From local to NFS:  10812.782049179077
    From NFS to local:  571.5739727020264

**10MB file size**

Shell:

    From local to NFS: 167
    From NFS to local: 8

.NET:

    From local to NFS: 6352
    From NFS to local: 6208
    Time to create folder: 4
    Time to delete folder: 0
    Time to create 10MB file: 6319
    Time to read 10MB file: 6216
    Time to delete 10MB file: 1

Python:

    From local to NFS:  183.42185020446777
    From NFS to local:  6.532192230224609

**10MB file size**
Local control test (SSD)

Shell:

    From local to local: 1
    From local to local: 1

.NET:

    From local to local: 4
    From local to local: 0
    Time to create folder: 6
    Time to delete folder: 0
    Time to create 10MB file: 5
    Time to read 10MB file: 3
    Time to delete 10MB file: 0

Python:

    From local to local:  0.05602836608886719
    From local to local:  0.010967254638671875

**Comment by DomiStyle** [comment] 2021-02-25 12:17
Area label is probably area-System.IO.

@jeffhandley @adamsitnik @carlossanlop @jozkee

**Comment by DomiStyle** [comment] 2022-02-07 12:48
I can still reproduce this on .NET 6. I tested a few different server distros to see if there are differences:

* Ubuntu 20.04.3: Same behavior as in original issue
* Debian 11: Same behavior as in original issue
* Alpine Linux 3.15: Only the very first read after a NFS server restart is (very) delayed, all successive requests work as expected
* Fedora Server 35: Same behavior as Alpine Linux

The control applications in Python and Bash still experience none of these issues. The client is always Ubuntu 21.10.

If the Python or Bash control application accesses the NFS mount on Alpine or Fedora first the .NET application will have no further issues afterwards.

**Comment by DomiStyle** [comment] 2022-02-07 17:25
Hey @adamsitnik

> Is there any chance you could modify the code to use the overload that allows for overwriting?

Sure, I tried with the overloaded method in both directions but unfortunately it is still slow.

I added some `File.Exists` calls in between to test this and checking if a file exists is blazing fast:

```
Run 1
Check if file exists (does not exist): 3
Move from local to NFS: 6317
Check if file exists (exists): 0
Move from NFS to local: 6303
Check if file exists (does not exist): 0
Time to create folder: 8
Time to delete folder: 6
Time to create 10MB file: 6212
Time to read 10MB file: 6303
Time to delete 10MB file: 14

Run 2
Check if file exists (does not exist): 14
Move from local to NFS: 6249
Check if file exists (exists): 0
Move from NFS to local: 6296
Check if file exists (does not exist): 0
Time to create folder: 4
Time to delete folder: 4
Time to create 10MB file: 6208
Time to read 10MB file: 6310
Time to delete 10MB file: 6

Run 3
Check if file exists (does not exist): 6
Move from local to NFS: 6256
Check if file exists (exists): 0
Move from NFS to local: 6290
Check if file exists (does not exist): 0
Time to create folder: 4
Time to delete folder: 4
Time to create 10MB file: 6230
Time to read 10MB file: 6295
Time to delete 10MB file: 7
```

Works normally: `File.Exists`, `File.Delete`, `Directory.CreateDirectory`, `Directory.Delete`

Stuck for ~6 seconds: `File.WriteAllBytes`, `File.ReadAllBytes`, `File.Move`

**Comment by DomiStyle** [comment] 2022-02-07 18:59
@adamsitnik Sure, here's the trace:
[slowNfs.trace.zip](https://github.com/dotnet/runtime/files/8017931/slowNfs.trace.zip)

I simplified the program and just let it move a file to NFS and back 3 times.

I got `Crossgen not found. Framework symbols will be unavailable.` at the end, just tell me if I need to fix that warning in order for the trace to be useful.

**Comment by adamsitnik** [comment] 2022-02-09 18:34
@DomiStyle big thanks for sharing the trace file! I was able to open it and identify the problem.

So the code performs 3 `lstats` (https://github.com/dotnet/runtime/issues/65092) to find out that the source and destination files are not on the same drive (and file system):

https://github.com/dotnet/runtime/blob/71393d07bc2f8a388dd2e06726757eaf11e3307c/src/libraries/System.Private.CoreLib/src/System/IO/FileSystem.Unix.cs#L227

and falls back to the slow path:

https://github.com/dotnet/runtime/blob/71393d07bc2f8a388dd2e06726757eaf11e3307c/src/libraries/System.Private.CoreLib/src/System/IO/FileSystem.Unix.cs#L235-L236

Which performs multiple sys-calls instead of single `rename`:

![image](https://user-images.githubusercontent.com/6011991/153265682-a3fc5d92-9aa4-4b48-a1e1-1abea70e1a18.png)

And spends most of the time in `sendfile64`

@tmds I can see that rename fails with `EXDEV` when the files are not on the same file system. Is my understanding correct that your recent work on #64264 should help us here as the `copy_file_range` is capable of copying files across different file systems?

You can see the trace file [here](https://www.speedscope.app/#profileURL=https://gist.githubusercontent.com/adamsitnik/90fbef23bf90034aadea60ff2019605c/raw/026b73cdb45f41c0942b37fe07341d937940f718/slownfs.json), please go directly to "Left Heavy" tab as there is only 20ms of data in the trace file and "Time Order" is empty.

**Comment by tmds** [comment] 2022-02-10 17:58
I don't expect `copy_file_range` to be much better than `sendfile` when copying between file systems.

Does the timing change if you avoid the file locking by setting `DOTNET_SYSTEM_IO_DISABLEFILELOCKING=1`?

Can you share the output of `strace -c cp src dst` for copying from and to the NFS share? And also without the `-c` flag.

**Comment by tmds** [comment] 2022-02-11 04:45
> Yes, that drastically reduces the access time from 6s to <100ms, which seems to be inline with what bash can do.

The locking is what is causing the long delay. To improve it you should look at your NFS client/server configuration.

NFS locking implementation changed significantly between NFSv3 and NFS4.

With NFSv3, you can disable locking for a mount using the `nolock` option. It should have an effect similar as setting `DOTNET_SYSTEM_IO_DISABLEFILELOCKING`.

**Comment by DomiStyle** [comment] 2022-02-11 12:11
> The locking is what is causing the long delay. To improve it you should look at your NFS client/server configuration.

I think you're right.

I wrote a test application for locking and unlocking in bash and I get the same ~6 second delay with a `no locks available` message.

> NFS locking implementation changed significantly between NFSv3 and NFS4.

Turns out that Ubuntu and Debian don't enable the service required for locks to work over NFSv3 anymore by default while Fedora does. Still doesn't explain why the first lock is delayed by 40s on Fedora but it's unlikely that a .NET application accesses my NFS server first so not an issue for me.

> With NFSv3, you can disable locking for a mount using the nolock option. It should have an effect similar as setting DOTNET_SYSTEM_IO_DISABLEFILELOCKING.

Enabling the service on Ubuntu resolves the issue, as does adding the `nolock` mount option or just switching to NFSv4.

That just leaves the question why .NET requires locks to move a file while bash and Python do not?

**Comment by tmds** [comment] 2022-02-11 12:27
> That just leaves the question why .NET requires locks to move a file while bash and Python do not?

The locks are used to emulate Windows [FileShare](https://docs.microsoft.com/en-us/dotnet/api/system.io.fileshare?view=net-6.0) behavior.

In this case, they prevent other .NET processes to write to the source file, and read from the destination file.

**Comment by DomiStyle** [comment] 2022-02-11 12:48
> In this case, they prevent other .NET processes to write to the source file, and read from the destination file.

Interesting, does DOTNET_SYSTEM_IO_DISABLEFILELOCKING work in every release .NET application or only in debug mode?

**Comment by tmds** [comment] 2022-02-11 12:52
> Interesting, does DOTNET_SYSTEM_IO_DISABLEFILELOCKING work in every release .NET application or only in debug mode?

It was introduced in .NET 6.

**Comment by tmds** [comment] 2022-02-16 09:18
I'm going to close the issue.

The root cause for the delay is .NET locking over NFSv3 without the lock service being available.

The options are:

- Disable .NET locking using `DOTNET_SYSTEM_IO_DISABLEFILELOCKING` (introduced in .NET 6).
- Disable locking for the mount using the `nolock` option.
- Enable the lock service.
- Use NFS4 which has built-in lock support.

**Closed by tmds** 2022-02-16 09:18 UTC
Labels: area-System.IO, tenet-performance, up-for-grabs
