### ISSUE TITLE
Test failure  JIT/HardwareIntrinsics/X86/X86Base/Pause_r/Pause_r.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#61709] opened 2021-11-17 01:06 UTC
Run: [runtime 20211116.61](https://dev.azure.com/dnceng/public/_build/results?buildId=1472496&view=ms.vss-test-web.build-test-results-tab&runId=42223874&paneView=debug&resultId=102265)

Failed test
```
Mono Linux x64 Release @ Ubuntu.1804.Amd64.Open
- JIT/HardwareIntrinsics/X86/X86Base/Pause_r/Pause_r.sh
- JIT/HardwareIntrinsics/X86/X86Base/Pause_ro/Pause_ro.sh

Mono Linux x64 Release no_tiered_compilation @ Ubuntu.1804.Amd64.Open
- JIT/HardwareIntrinsics/X86/X86Base/Pause_ro/Pause_ro.sh
- JIT/HardwareIntrinsics/X86/X86Base/Pause_r/Pause_r.sh

```
**Error message:**
```
Return code:      1
Raw output file:      /datadisks/disk1/work/A96D0970/w/AB720969/uploads/Reports/JIT.HardwareIntrinsics/X86/X86Base/Pause_r/Pause_r.output.txt
Raw output:
BEGIN EXECUTION
/datadisks/disk1/work/A96D0970/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false Pause_r.dll ''
Expected: 100
Actual: 0
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/datadisks/disk1/work/A96D0970/p
/datadisks/disk1/work/A96D0970/w/AB720969/e/JIT/HardwareIntrinsics/X86/X86Base/Pause_r/Pause_r.sh
Expected: True
Actual:   False


Stack trace
   at JIT_HardwareIntrinsics._X86_X86Base_Pause_r_Pause_r_._X86_X86Base_Pause_r_Pause_r_sh()
```

**Comment by JulieLeeMSFT** [comment] 2021-11-18 01:57
@echesakovMSFT PTAL.

**Comment by echesakovMSFT** [comment] 2021-11-18 16:19
This is a duplicate of #61693.

Tanner is working on the issue in #61707.

**Closed by echesakovMSFT** 2021-11-18 16:19 UTC
Labels: os-linux, arch-x64, area-CodeGen-coreclr
