### ISSUE TITLE
The lifetime of a property used in a method on struct is longer when tiered compilation is enabled

### ISSUE THREAD

**Issue by SergeyTeplyakov** [dotnet/runtime#43334] opened 2020-10-12 22:58 UTC
### Description

Normally, if a local or a field/property is used only at the beginning of the method and then it sets to null, the object that was referenced from a local (or from a field/property) is eligible to GC if that was the last reference to it due to GCInfo table created by the jit.

But here is an example that doesn't work as I expected in some cases:

```csharp
internal struct TestIsAlive
{
    private object Reference { get; set; }
 
    public TestIsAlive(object reference) { Reference = reference; }
    
    [MethodImpl(MethodImplOptions.NoInlining)] // this doesn't really matter!
    private void TouchReference(object reference) { }
 
    public void CheckEligibilityWithPropertyNonAsync()
    {
        TouchReference(Reference); // Actually, GC.KeepAlive will do the same
 
        // Just for fun let’s call the method twice
        bool isAlive = CollectAndCheckIfAlive();
        bool isAlive2 = CollectAndCheckIfAlive();
 
        Console.WriteLine($"CheckEligibilityWithPropertyNonAsync IsAlive={isAlive}, IsAlive2={isAlive2}");
    }
 
    private bool CollectAndCheckIfAlive()
    {
        var wr = new WeakReference(Reference);
        Reference = null;
        GC.Collect();
        return wr.IsAlive;
    }
}
 
class Program
{
    static void Main(string[] args)
    {
        var test = new TestIsAlive(new object());
        test.CheckEligibilityWithPropertyNonAsync();
    }
}

```

If you run it for .NET Framwork, or .netcoreapp2.1 the output is:

```
CheckEligibilityWithPropertyNonAsync IsAlive=false, IsAlive2=False
```

I.e. the object that was stored in the `Reference` property is collected because it is not used in the method except in the first line.

But running this code targeting .netcoreapp3.1 the behavior changes and the output is:

```
CheckEligibilityWithPropertyNonAsync IsAlive=True, IsAlive2=False
```

But the behavior changes if tiered compilation is off. I.e. running the following command first: `$env:COMPlus_TieredCompilation=0`, changes the behavior and the reference now collected as expected.

### Configuration

.netcoreapp 3.1

### Regression?

Yes, because the behavior is different based on whether tiered compilation is on or off.

### Other information

We hit this problem in [BuildXl](https://github.com/microsoft/BuildXL) when a property was only used at the beginning of an async method and then was set to `null`, but the object was alive for the duration of the entire method causing higher than expected peak memory consumption.

I don't think there is anything wrong with GC, and maybe just GCInfo is not set correctly when the tiered compilation is on.

**Comment by SergeyTeplyakov** [comment] 2020-10-12 22:59
I was trying to set the label to "area-CodeGen-coreclr", but I don't think I have permission to do so.

**Comment by janvorli** [comment] 2020-10-14 10:02
There is no guarantee on lifetime of objects used in a method, even if you assign null to a local. The JIT can create internal locals that still hold that value or decide to not to track a lifetime of a variable and consider it alive for the whole method.
The fact that it was behaving differently in previous version is an implementation detail. 

If you need to make sure there is no reference after certain point, you can put the code using that reference into a non-inlineable method (mark the method by `[MethodImpl(MethodImplOptions.NoInlining)]` attribute). That way, it cannot escape that method.

**Comment by SergeyTeplyakov** [comment] 2020-10-14 17:15
@janvorli I totally agree with you that there are no such guarantees and that the behavior is an implementation detail, but the knowledge about GCInfo is out there and people can rely on that regardless of the guarantees:). For instance, one may use !gcinfo in windbg, and the behavior is easily observable via weak references as well.

And to be clear, if the jit people think this is fine, then I'm not in the position to argue with it. But if we can provide a more consistent behavior in terms of object lifetimes and collect some stuff faster and to be consistent with the old behavior, I think it's a good thing to have. And the behavior sounds just counter-intuitive to me: if tiered compilation is on one would expect more optimizations, not less.

And, @janvorli, can you please clarify one thing to me: do you think that the current behavior makes sense or not from your personal perspective, regardless of whether anyone should rely on it or not?

**Comment by janvorli** [comment] 2020-10-14 17:20
@SergeyTeplyakov the GCInfo should match the lifetime. Are you saying that you've checked the gcinfo and the lifetimes it described didn't match the behavior?

**Comment by SergeyTeplyakov** [comment] 2020-10-14 17:43
I'm almost sure that GCInfo matches the lifetime, I haven't look because for me it will take a reasonable amount of time and I want to have some feedback about the issue first.

What I'm trying to say is that GCInfo should be the same for both cases, regardless of whether tiered compilation is on or not.

**Comment by janvorli** [comment] 2020-10-14 17:48
It would be strange to me if it was the same. Basically, tiered compilation means that you have a different result from compiling the method after the tiered compilation kicks in, (possibly much) better optimized than the initial one. Things can be reordered, helper locals eliminated, functions inlined etc. The GC info represents the generated machine code, so it cannot really be the same.

**Comment by SergeyTeplyakov** [comment] 2020-10-14 17:52
Ok, so it means that the tiered compilation provides better results at the end, but the first runs can be less optimal? Right?

This can explain the behavior, but the question that I have is this one: is it that costly to collect the GCInfo the same way we do for non-tiered compilation and that's why the first runs track the lifetime differently?

I also tried calling this method multiple times, but was unable to hit the case when the lifetime was back to non-tiered version.

**Comment by janvorli** [comment] 2020-10-14 17:57
Yes, that's the purpose of the tiered compilation. 


> is it that costly to collect the GCInfo the same way we do for non-tiered compilation and that's why the first runs track the lifetime differently?

I am not sure I understand the question. The GCInfo isn't something independent of the generated code. It is what gets generated during the compilation and is a function of the generated code. When you compile the code with different optimizations, local variables, helper internal temporary variables etc will in most cases end up in different CPU registers and stack slots.

**Comment by AndyAyersMS** [comment] 2020-10-14 18:00
With tiered compilation enabled, the method is first jitted at Tier0, without optimization. At this level the jit introduces a temporary to hold onto the result of the nested call in:
```C#
        var wr = new WeakReference(Reference);
```
Also at Tier0 all gc references are "untracked" and so reported for the life of the method. So this temporary ends up keeping the object alive until the method returns.

So this behavior is "by design" and not a bug.

```asm
; Assembly listing for method TestIsAlive:CollectAndCheckIfAlive():bool:this
; Emitting BLENDED_CODE for X64 CPU with AVX - Windows
; Tier-0 compilation
; MinOpts code
; rbp based frame
; partially interruptible
; Final local variable assignments
;
;  V00 this         [V00    ] (  1,  1   )   byref  ->  [rbp+0x10]   this
;  V01 OutArgs      [V01    ] (  1,  1   )  lclBlk (32) [rsp+0x00]   "OutgoingArgSpace"
;  V02 tmp1         [V02    ] (  1,  1   )     ref  ->  [rbp-0x08]   must-init class-hnd exact "NewObj constructor temp"
;  V03 tmp2         [V03    ] (  1,  1   )     ref  ->  [rbp-0x10]   must-init "argument with side effect"
;
; Lcl frame size = 48

G_M13049_IG01:
       55                   push     rbp
       4883EC30             sub      rsp, 48
       488D6C2430           lea      rbp, [rsp+30H]
       33C0                 xor      rax, rax
       488945F8             mov      qword ptr [rbp-08H], rax
       488945F0             mov      qword ptr [rbp-10H], rax
       48894D10             mov      bword ptr [rbp+10H], rcx
                                                ;; bbWeight=1    PerfScore 5.00
G_M13049_IG02:
       48B9987A10E7F87F0000 mov      rcx, 0x7FF8E7107A98
       E83997785F           call     CORINFO_HELP_NEWFAST
       488945F8             mov      gword ptr [rbp-08H], rax
       488B4D10             mov      rcx, bword ptr [rbp+10H]
       E844F9FFFF           call     TestIsAlive:get_Reference():System.Object:this
       488945F0             mov      gword ptr [rbp-10H], rax                                 // temporary = gc ref
       488B55F0             mov      rdx, gword ptr [rbp-10H]
       488B4DF8             mov      rcx, gword ptr [rbp-08H]
       E83BFBFEFF           call     System.WeakReference:.ctor(System.Object):this
       488B4D10             mov      rcx, bword ptr [rbp+10H]
       33D2                 xor      rdx, rdx
       E830F9FFFF           call     TestIsAlive:set_Reference(System.Object):this            // class ref gets nulled
       E88BE6FFFF           call     System.GC:Collect()                                      // temporary does not
       488B4DF8             mov      rcx, gword ptr [rbp-08H]
       488B45F8             mov      rax, gword ptr [rbp-08H]
       488B00               mov      rax, qword ptr [rax]
       488B4048             mov      rax, qword ptr [rax+72]
       FF5020               call     qword ptr [rax+32]System.WeakReference:get_IsAlive():bool:this
       90                   nop
                                                ;; bbWeight=1    PerfScore 20.75
G_M13049_IG03:
       488D6500             lea      rsp, [rbp]
       5D                   pop      rbp
       C3                   ret
                                                ;; bbWeight=1    PerfScore 2.00

Stack slot id for offset 16 (0x10) (frame) (byref, untracked) = 0.
Stack slot id for offset -8 (0xfffffff8) (frame) (untracked) = 1.
Stack slot id for offset -16 (0xfffffff0) (frame) (untracked) = 2.
```

**Comment by SergeyTeplyakov** [comment] 2020-10-14 18:18
Thanks a lot, @AndyAyersMS and @janvorli!

**Comment by JulieLeeMSFT** [comment] 2020-10-14 18:45
@SergeyTeplyakov if it answered your question, can we close this ticket?

**Closed** 2020-10-14 18:50 UTC
Labels: area-CodeGen-coreclr, untriaged
