### ISSUE TITLE
Test failure: JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#109905] opened 2024-11-18 02:02 UTC
**Failed in:** [runtime-coreclr jitstress-random 20241117.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=871741&view=ms.vss-test-web.build-test-results-tab&runId=22727084&resultId=110573&paneView=debug)

**Failed tests:**
```
coreclr osx arm64 Checked jitstress_random_2 @ OSX.1200.ARM64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
coreclr osx arm64 Checked jitstress_random_1 @ OSX.1200.ARM64.Open
    - JIT/Regression/JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.cmd
```

**Error message:**
```
 
Assert failure(PID 16832 [0x000041c0], Thread: 266530 [0x41122]): Assertion failed 'newLayoutCost < currLayoutCost' in 'System.Xml.XmlTextReaderImpl:ParseQName(ubyte,int,byref):int:this' during 'Optimize layout' (IL size 315; hash 0x8ab5d5eb; FullOpts)

    File: /Users/runner/work/1/s/src/coreclr/jit/fgopt.cpp:5380
    Image: /private/tmp/helix/working/A71C091F/p/corerun

ASSERT FAILED
	Expression: (end & ~(~(vm_page_size-1))) == 0
	Location:   line 48 in /Users/runner/work/1/s/src/coreclr/debug/createdump/memoryregion.h
	Function:   MemoryRegion
	Process:    16833
waitpid() returned successfully (wstatus 00000086) WEXITSTATUS 0 WTERMSIG 6
/private/tmp/helix/working/A71C091F/w/A65E0933/e/JIT/Regression/Regression_3/../JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.sh: line 454: 16832 Abort trap: 6           (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /tmp/helix/working/A71C091F/w/A65E0933/uploads/JitBlue/DevDiv_461649/DevDiv_461649/output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/A71C091F/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true DevDiv_461649.dll ''
[createdump] Gathering state for process 16832 
[createdump] Crashing thread 41122 signal 6 (0006)
[createdump] Writing crash report to file /cores/coredump.16832.dmp.crashreport.json
[createdump] Crash report successfully written
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /cores since 11/17/2024 11:19:18 AM
Processing /cores/coredump.16832.dmp.crashreport.json
Printing stacktrace from '/cores/coredump.16832.dmp.crashreport.json'
Invoking llvm-symbolizer --pretty-print
Errors while running llvm-symbolizer --pretty-print
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'llvm-symbolizer' with working directory '/private/tmp/helix/working/A71C091F/w/A65E0933/e/JIT/Regression/Regression_3'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs:line 499
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs:line 456
   at CoreclrTestLib.CoreclrTestWrapperLib.TryPrintStackTraceFromCrashReport(String crashReportJsonFile, TextWriter outputWriter)
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> /private/tmp/helix/working/A71C091F/w/A65E0933/e/JIT/Regression/Regression_3/../JitBlue/DevDiv_461649/DevDiv_461649/DevDiv_461649.sh
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 141
   at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 123
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor331|0_332(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by amanasifkhalid** [comment] 2024-11-18 15:29
Duplicate of #109831

**Closed** 2024-11-18 21:01 UTC
Labels: JitStress, area-CodeGen-coreclr, blocking-clean-ci-optional, in-pr
