### ISSUE TITLE
[API Proposal]: `Process.Architecture` or `Process.Is64Bit`

### ISSUE THREAD

**Issue by just-ero** [dotnet/runtime#70374] opened 2022-06-07 17:31 UTC
### Background and motivation

Working a lot with external process memory, I find it a little tedious having to use [`IsWow64Process`](https://docs.microsoft.com/en-us/windows/win32/api/wow64apiset/nf-wow64apiset-iswow64process) each time I want to infer the architecture of a target process. Not to mention, that function's `out Wow64Process` parameter is heaps confusing.

It would be a lot nicer if I could simply check a `Process.Is64Bit` property.

### API Proposal

```cs
namespace System.Diagnostics;

public class Process
{
    public bool Is64Bit { get; }
}
```

### API Usage

```csharp
var proc = Process.GetCurrentProcess();
Console.WriteLine(proc.Is64Bit);
```

### Alternative Designs

```cs
namespace System.Diagnostics;

public class Process
{
    public enum ProcessArchitecture
    {
        x64,
        x86,
        TheFutureIsNow
    }

    public ProcessArchitecture Architecture { get; }
}
```

**Comment by adamsitnik** [comment] 2022-06-23 14:54
Hello @just-ero 

It's a duplicate of https://github.com/dotnet/runtime/issues/1124

**Closed by adamsitnik** 2022-06-23 14:54 UTC
Labels: api-suggestion, area-System.Diagnostics.Process
