### ISSUE TITLE
Does .NET support NUMA core processing?

### ISSUE THREAD

**Issue by msedi** [dotnet/runtime#58184] opened 2021-08-26 14:59 UTC
### Discussed in https://github.com/dotnet/runtime/discussions/58116

<div type='discussions-op-text'>

<sup>Originally posted by **msedi** August 25, 2021</sup>
We have an AMD Threadripper with 2 NUMA cores (in total: 128 cores) and try to run a simple program (see below), but we can only see that one NUMA core is used.  Environment.ProcessorCount only shows 64 which is somehow OK and has already been discussed, but the question is does `COMPlus_Thread_UseAllCpuGroups `have an effect at all or is there currently no way to use all NUMA cores?

For Parallel.For, even if I set `MaxDegreeOfParallelism = 2*Environment.ProcessorCount `there is no effect. 

Our runtimeconfig.josn looks like this:

```json
{
  "runtimeOptions": {
    "tfm": "net5.0",
    "includedFrameworks": [
      {
        "name": "Microsoft.NETCore.App",
        "version": "5.0.9"
      }
    ],
    "configProperties": {
      "System.GC.Server": true,
      "System.GC.CpuGroup": true,
      "System.GC.RetainVM": true,
      "System.Runtime.TieredCompilation.QuickJit": false,
      "System.Runtime.TieredCompilation.QuickJitForLoops": false
    }
  }
}
```
The test code look this.

 ```cs
            ParallelOptions options = new ParallelOptions()
            {
                MaxDegreeOfParallelism = Environment.ProcessorCount
            };


            Parallel.For(0, 100, options, idx =>
            {
                Random r = new Random();
                double result = 0;

                for (long i = 0; i < long.MaxValue; i++)
                {
                    unchecked { result += Math.Log(r.NextDouble()); };
                }

                Console.WriteLine($"Result {result}");
            });
```

**Comment by mangod9** [comment] 2021-09-01 15:54
Yeah `COMPlus_Thread_UseAllCpuGroups` along with `GCCpuGroup` would be required to support 64+ cores on windows. Does it not work for you?

**Comment by msedi** [comment] 2021-09-01 16:53
@mangod9: Thanks for your feedback. That's what I tried but I couldn't get all threads to work, I can only see 64 threads running instead of the full 128. Thats currently my configuration, including setting the COMPlus_Thread_UseAllCpuGroups as the environment (Btw: Is there a reason why I cannot set this in the runtimeconfig?). I was under the assumption that it was already available in the .NET Framework, but I#m not sure anymore)

runtimeconfig.json:
```
  "configProperties": {
    "System.GC.Server": true,
    "System.GC.CpuGroup": true,
    "System.GC.RetainVM": true,
    "System.Runtime.TieredCompilation.QuickJit": false,
    "System.Runtime.TieredCompilation.QuickJitForLoops": false
  }

Is there a way to dump the settings the runtime is starting up with and what parameters are used?
```

**Comment by msedi** [comment] 2021-09-21 10:54
@mangod9: Is there an example that shows how.NET is using NUMA processing?

**Comment by mangod9** [comment] 2021-11-12 17:45
Sorry just getting back to this. Could you please share the hardware configuration you are running this on with your test repro?

**Comment by msedi** [comment] 2021-11-15 13:19
@mangod9 : No problem. I have created a repository to show you the problem. 

https://github.com/msedi/NUMAPressure

Since I have to enable NUMA cores per environment variable you have to start the app with NUMAPressureExec.bat. I hope the environment variable will not be necessary in future versions and the setting will be available in appsettings again, as it was the case in the .NET Framework?

Attached ist the config of my system, unforunaly its german, but I assume you get the necessary information, otherwise please just ask.

```
Gerätename	RECONBOX
Prozessor	AMD Ryzen Threadripper 3990X 64-Core Processor    2.90 GHz
Installierter RAM	256 GB (256 GB verwendbar)
Geräte-ID	3C873D7D-8297-4BBE-8C13-88A6965FC4DC
Produkt-ID	00330-53722-87533-AAOEM
Systemtyp	64-Bit-Betriebssystem, x64-basierter Prozessor
Stift- und Toucheingabe	Für diese Anzeige ist keine Stift- oder Toucheingabe verfügbar.

Edition	Windows 10 Pro
Version	21H1
Installiert am	‎18.‎08.‎2021
Betriebssystembuild	19043.1110
Leistung	Windows Feature Experience Pack 120.2212.3530.0

```

In the repo I have added an image TaskManager.png that shows that only one NUMA core ist used.

**Comment by mxplusb** [comment] 2021-11-15 16:49
I am also interested in this issue.

**Comment by mangod9** [comment] 2021-11-15 22:03
I tried running your repro with setting `DOTNET_Thread_UseAllCpuGroups=1` and I am able to get all cores utilized on the machine (note that the issue is not specifically related to NUMA, but any machine with 64+ cores on windows). As you can see all NUMA nodes show activity on the machine I tried it on:

![image](https://user-images.githubusercontent.com/61718172/141860079-a4e9c6a4-0b20-45da-aebd-64d9f76fbb9e.png)

**Comment by msedi** [comment] 2021-11-16 07:35
@mangod9: Thanks for looking into this. I have tried ona different machine, also with 2 NUMA cores with the same settings and I get the same result:

![TaskManager2](https://user-images.githubusercontent.com/8020659/141940936-ea046c0b-bbed-4c6b-88d1-6e8671a0b5f6.png)

**Comment by msedi** [comment] 2021-11-16 09:46
What about Environment.ProcessorCount in my call

```
ParallelOptions options = new ParallelOptions()
{
   MaxDegreeOfParallelism = Environment.ProcessorCount
};
```

Is this correct to do it like this, also in .NET 6?
Did you change something on your side? On NUMA cores its only the amount of cores, not of logical cores.

**Comment by msedi** [comment] 2022-12-12 09:50
Coming back to this topic, would it be much effort to enable the setting `Thread_UseAllCpuGroups`  in `runtimeConfig.json` again?
I took a look at the source code and it seems it is simply only not used in the config a just needs to be added.

**Comment by jkotas** [comment] 2023-08-11 05:13
Duplicate of https://github.com/dotnet/runtime/issues/81713 and https://github.com/dotnet/sdk/issues/3664

Note that this setting is not necessary on Windows 11+ and Windows Server 2022+. The CPU groups are enabled by default on these OSes.

https://learn.microsoft.com/en-us/windows/win32/procthread/processor-groups#behavior-starting-with-windows-11-and-windows-server-2022
https://github.com/dotnet/runtime/pull/68639

**Closed by jkotas** 2023-08-11 05:13 UTC
Labels: area-VM-coreclr
