### ISSUE TITLE
Test failed file_io.GetFileSize.test1

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#58481] opened 2021-09-01 01:49 UTC
Run: [runtime-coreclr outerloop 20210831.9](https://dev.azure.com/dnceng/public/_build/results?buildId=1332149&view=ms.vss-test-web.build-test-results-tab&runId=39077262&paneView=debug&resultId=103948)

Failed test:
```
CoreCLR Linux arm Checked no_tiered_compilation @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- file_io.GetFileSize.test1
- file_io.GetFileSizeEx.test1
- file_io.SetFilePointer.test5
```
**Error message:**
```
GetFileSize: ERROR -> File sizes do not match up.


Stack trace
```

Failed test:
```
CoreCLR Linux arm Checked no_tiered_compilation @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- file_io.SetFilePointer.test6
- file_io.SetFilePointer.test7

```
**Error message:**
```
SetFilePointer: ERROR -> Asked to move far past the current file pointer. low order sent: 10  low order returned: 10 high order sent: 1  high order returned: 0


Stack trace
```

**Comment by adamsitnik** [comment] 2021-09-01 08:02
It's similar to #51831, since it's testing PAL I've moved it from `System.IO` to `PAL-coreclr`

**Comment by AndyAyersMS** [comment] 2021-09-09 01:03
@mangod9 this is causing a lot of outerloop failures, any way we can prioritize a fix?

**Comment by mangod9** [comment] 2021-09-09 01:05
adding @janvorli

**Comment by VincentBu** [comment] 2021-09-09 01:23
Failed again in: [runtime-coreclr outerloop 20210908.5](https://dev.azure.com/dnceng/public/_build/results?buildId=1349184&view=ms.vss-test-web.build-test-results-tab&runId=39492276&paneView=debug&resultId=103501)

Failed test:
```
CoreCLR Linux arm Checked no_tiered_compilation @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- file_io.GetFileSize.test1
- file_io.GetFileSizeEx.test1

CoreCLR Linux arm Checked @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- file_io.GetFileSize.test1
- file_io.GetFileSizeEx.test1
```
**Error message:**
```
GetFileSize: ERROR -> File sizes do not match up.


Stack trace
```

Failed test:
```
CoreCLR Linux arm Checked no_tiered_compilation @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- file_io.SetFilePointer.test5

CoreCLR Linux arm Checked @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- file_io.SetFilePointer.test5
```
**Error message:**
```
SetFilePointer: ERROR -> Failed to move pointer past EOF.


Stack trace
```

Failed test:
```
CoreCLR Linux arm Checked no_tiered_compilation @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- file_io.SetFilePointer.test6
- file_io.SetFilePointer.test7

CoreCLR Linux arm Checked @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- file_io.SetFilePointer.test6
- file_io.SetFilePointer.test7
```
**Error message:**
```
SetFilePointer: ERROR -> Asked to move far past the current file pointer. low order sent: 10  low order returned: 10 high order sent: 1  high order returned: 0


Stack trace
```

**Comment by mangod9** [comment] 2021-09-10 18:53
assume the failures on arm32 only?

**Comment by AndyAyersMS** [comment] 2021-09-10 19:43
Yes.

**Comment by VincentBu** [comment] 2021-09-16 01:37
Failed again in: [runtime-coreclr outerloop 20210915.9](https://dev.azure.com/dnceng/public/_build/results?buildId=1364691&view=ms.vss-test-web.build-test-results-tab&runId=39855992&resultId=102517&paneView=debug)

Failed test:
```
CoreCLR Linux arm Checked no_tiered_compilation @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- file_io.GetFileSize.test1
- file_io.GetFileSizeEx.test1

CoreCLR Linux arm Checked @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- file_io.GetFileSize.test1
- file_io.GetFileSizeEx.test1
```
**Error message:**
```
GetFileSize: ERROR -> File sizes do not match up.


Stack trace
```
Failed test:
```
CoreCLR Linux arm Checked no_tiered_compilation @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- file_io.SetFilePointer.test5

CoreCLR Linux arm Checked @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- file_io.SetFilePointer.test5
```
**Error message:**
```
SetFilePointer: ERROR -> Failed to move pointer past EOF.


Stack trace
```
Failed test:
```
CoreCLR Linux arm Checked no_tiered_compilation @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- file_io.SetFilePointer.test6
- file_io.SetFilePointer.test7
CoreCLR Linux arm Checked @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- file_io.SetFilePointer.test6
- file_io.SetFilePointer.test7
```
**Error message:**
```
SetFilePointer: ERROR -> Asked to move far past the current file pointer. low order sent: 10  low order returned: 10 high order sent: 1  high order returned: 0


Stack trace
```

**Comment by BruceForstall** [comment] 2021-09-22 02:18
@mangod9 @janvorli @mateoatr @agocke This is still failing regularly and causing a lot of noise in outerloop runs.

**Comment by BruceForstall** [comment] 2021-09-22 02:18
e.g., https://dev.azure.com/dnceng/public/_build/results?buildId=1376847&view=ms.vss-test-web.build-test-results-tab&runId=40153424&resultId=101903&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

**Comment by janvorli** [comment] 2021-09-22 19:05
I'll take a look

**Comment by janvorli** [comment] 2021-09-22 21:24
This is caused by a removal of a define that enables 64 bit file offsets on all targets (including 32 bit ones) in #58096.

**Comment by janvorli** [comment] 2021-09-22 21:44
On arm Unix, it breaks getting file size using various windows style API implemented in PAL and also coredump. For files > 2GB.

**Comment by BruceForstall** [comment] 2021-09-22 22:41
@janvorli It looks like this needs to get fixed in .NET 6?

**Comment by am11** [comment] 2021-09-22 22:41
@janvorli, I think 7.0 is the correct milestone as #58096 is 7.0 only.

**Comment by janvorli** [comment] 2021-09-22 22:51
Ah, great, I haven't realized that it didn't go in while we were still moving all changes to 6.0. Changing this back to 7.0 then.

**Comment by VincentBu** [comment] 2021-09-24 01:20
Failed again in: [runtime-coreclr outerloop 20210923.7](https://dev.azure.com/dnceng/public/_build/results?buildId=1381994&view=ms.vss-test-web.build-test-results-tab&runId=40281206&resultId=102246&paneView=debug)

Failed test:
```
CoreCLR Linux arm Checked no_tiered_compilation @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- file_io.GetFileSize.test1
- file_io.GetFileSizeEx.test1

CoreCLR Linux arm Checked @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- file_io.GetFileSize.test1
- file_io.GetFileSizeEx.test1
```
**Error message:**
```
GetFileSize: ERROR -> File sizes do not match up.


Stack trace
```

Failed test:
```
CoreCLR Linux arm Checked no_tiered_compilation @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
file_io.SetFilePointer.test5
CoreCLR Linux arm Checked @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
file_io.SetFilePointer.test5
```
**Error message:**
```
SetFilePointer: ERROR -> Failed to move pointer past EOF.


Stack trace
```

Failed test;
```
CoreCLR Linux arm Checked no_tiered_compilation @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- file_io.SetFilePointer.test6
- file_io.SetFilePointer.test7

CoreCLR Linux arm Checked @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- file_io.SetFilePointer.test6
- file_io.SetFilePointer.test7
```
**Error message:**
```
SetFilePointer: ERROR -> Asked to move far past the current file pointer. low order sent: 10  low order returned: 10 high order sent: 1  high order returned: 0


Stack trace
```

**Comment by BruceForstall** [comment] 2021-09-29 00:57
@janvorli Have you had a chance to look at this?

**Closed** 2021-09-29 08:42 UTC
Labels: arch-arm32, os-linux, area-PAL-coreclr, in pr

**Comment by janvorli** [comment] 2021-09-29 08:44
The PR with a fix was merged just a minute ago.

**Comment by am11** [comment] 2021-09-29 13:32
https://dev.azure.com/dnceng/public/_build/results?buildId=1392530&view=results is green. ✅
