### ISSUE TITLE
Breaking changes on ConfigurationBinder behaviour

### ISSUE THREAD

**Issue by mapogolions** [dotnet/runtime#58330] opened 2021-08-29 16:27 UTC
### Description
Before [this](https://github.com/dotnet/runtime/commit/e4a455f26a91932f5de398f0082be83cb9678c36) changes I could convert any non-terminal section (section that doesn't have a value, but has child keys) to an array  as shown the example below. This is not possible in the current implementation.

```c#
var configRoot = new ConfigurationBuilder()
    .AddInMemoryCollection(new KeyValuePair<string, string>[]
    {
        new("section:key1", "1"),
        new("section:key2", "2"),
        new("section:key3", "3")
        /**
         {
             "section": {
                 "key1": "1",
                 "key2": "2",
                 "key3": "3"
             }
         }
        */
    })
    .Build();
var values = configRoot.GetSection("section").Get<int[]>();


Assert.Equal(3, values.Length);
Assert.Equal(1, values[0]);
Assert.Equal(2, values[1]);
Assert.Equal(3, values[2]);
```

### Other information

[This line of code](https://github.com/dotnet/runtime/blob/cffaa78235ea93d5e3eeb56956579df503e11250/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs#L719) requires the child key (as "key1", "key2", "key3" in example above) to be an integer.

**Comment by mapogolions** [comment] 2021-09-03 18:57
In my opinion, the most unexpected side effect of the introduced changes is demonstrated by the example below. 
```c#
       [Fact]
        public void ShouldGetArrayOfConfigurationSectionsFromTopLevel()
        {
            var configRoot = new ConfigurationBuilder()
                .AddInMemoryCollection(new KeyValuePair<string, string>[]
                {
                    new("Foo", "1"),
                    new("Bar", "2")
                })
                .Build();

            var sections = configRoot.Get<IConfigurationSection[]>();
            var fooConfigSection = sections.SingleOrDefault(x => x.Key == "Foo");
            var barConfigSection = sections.SingleOrDefault(x => x.Key == "Bar");

            Assert.Equal(2, sections.Count());
            Assert.Equal("1", fooConfigSection.Value);
            Assert.Equal("2", barConfigSection.Value);
        }
```

**Comment by joperezr** [comment] 2021-09-08 21:50
cc: @maryamariyan can you please take a look?

**Comment by maryamariyan** [comment] 2021-09-09 20:57
Thanks for the feedback @mapogolions. You could use an AppContext switch (`Microsoft.Extensions.Configuration.BindSingleElementsToArray`) to provide "temporary" access to the previous behavior.

**Comment by vidommet** [comment] 2021-09-09 23:55
As @maryamariyan commented, the old behavior can be opted in. But in my opinion, the casting above doesn't make complete sense as the objects are not part of an array. The children can still be retrieved using `IConfigurationSection[] section = root.GetChildren().ToArray()`. It could be an unintended behavior of the old implementation.

**Comment by maryamariyan** [comment] 2021-09-29 00:37
@mapogolions FYI the recent configuration binder changes are being reverted via https://github.com/dotnet/runtime/pull/59716

**Comment by safern** [comment] 2021-09-29 19:34
Closing as we reverted the breaking change.

**Closed by safern** 2021-09-29 19:34 UTC
Labels: area-Extensions-Configuration, needs-breaking-change-doc-created
