### ISSUE TITLE
Proxy authentication not recognized in macOS

### ISSUE THREAD

**Issue by olivepedro** [dotnet/runtime#86322] opened 2023-05-16 12:35 UTC
### Description

I'm using HttpClient to open an URI, like this:
    HttpResponseMessage response = httpClient.GetAsync("https://www.microsoft.com/").Result;

I setup a proxy using environment variables http_proxy/https_proxy=http://user:pass@server:port
In Windows and Ubuntu, I can successful connect to the proxy. In macOS, I get the error:
![image](https://github.com/dotnet/runtime/assets/98524705/1ca5154c-5200-4d89-a708-0897b8139f0f)

### Reproduction Steps

Sample app:

```
Console.WriteLine("Starting");

HttpClientHandler handler = new();

HttpClient httpClient = new(handler);

try
{
    HttpResponseMessage response = httpClient.GetAsync("https://www.microsoft.com/").Result;

    response.EnsureSuccessStatusCode();
}
catch (Exception e)
{
    Console.WriteLine("\nException Caught!");
    Console.WriteLine($"Message :{e.Message}");
    Console.WriteLine($"Inner :{e.InnerException}");
}
finally
{
    handler.Dispose();
    httpClient.Dispose();
}

Console.WriteLine("Ending");
```

Set environment variables:
```
export http_proxy=http://user:pass@server:port
export https_proxy=http://user:pass@server:port
```

### Expected behavior

Connection is successful and we get the console output:
![image](https://github.com/dotnet/runtime/assets/98524705/b4da2c75-18e5-4f71-a3b0-e8e165f39d04)

### Actual behavior

an exception is thrown:
![image](https://github.com/dotnet/runtime/assets/98524705/1ca5154c-5200-4d89-a708-0897b8139f0f)

**Comment by wfurt** [comment] 2023-05-22 08:28
Can you post packet captures @olivepedro? And would it work if you set the proxy explicitly using https://learn.microsoft.com/en-us/dotnet/api/system.net.webproxy?view=net-7.0? 

That code is same as on Linux so I don't see reason why this should behave any different.

**Comment by grazius** [comment] 2023-06-06 11:03
Hello
We finally found the root cause of our problem. 
It's not related to the Mac implementation but to the authentication through our http proxy when we call https urls.

To find the root cause we switch in java to make the same test and we also get a 407 return code.
To resolve this in java we referrer to this url https://www.oracle.com/java/technologies/javase/8u111-relnotes.html

> Disable Basic authentication for HTTPS tunneling
> 
> In some environments, certain authentication schemes may be undesirable when proxying HTTPS. Accordingly, the Basic authentication scheme has been deactivated, by default, in the Oracle Java Runtime, by adding Basic to the jdk.http.auth.tunneling.disabledSchemes networking property. Now, proxies requiring Basic authentication when setting up a tunnel for HTTPS will no longer succeed by default. If required, this authentication scheme can be reactivated by removing Basic from the jdk.http.auth.tunneling.disabledSchemes networking property, or by setting a system property of the same name to "" ( empty ) on the command line.
> 
> Additionally, the jdk.http.auth.tunneling.disabledSchemes and jdk.http.auth.proxying.disabledSchemes networking properties, and system properties of the same name, can be used to disable other authentication schemes that may be active when setting up a tunnel for HTTPS, or proxying plain HTTP, respectively.

Have we got the same restriction in dotnet ?
An environment variable exists to allow this use case ?

Best regards

**Comment by wfurt** [comment] 2023-06-06 12:22
Do you know what scheme is used in successful case? You can create [CredentialCache](https://learn.microsoft.com/en-us/dotnet/api/system.net.credentialcache?view=net-7.0) and using it instead of credentials. But that does not work with the environment - you would need to set WebProxy explicitly and pass the cache to is as credentials.

**Comment by wfurt** [comment] 2023-06-06 13:02
right. so instead of `NetworkCredential` use `CredentialCache`. That allows you to do credentials only for given authentication scheme. That assumes you would know what that is. But that should be easy since you have working setup.

**Comment by grazius** [comment] 2023-06-06 15:20
what i see in source code
https://github.com/dotnet/runtime/blob/8a5ae8bbd0e111a13446187fe64ca7b2f68285a9/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpEnvironmentProxy.cs#LL91C13-L91C13

It's a NetworkCredential that is used !

**Comment by wfurt** [comment] 2023-06-06 15:33
I don't understand the last comment @grazius. The environment syntax does not allow to specify authentication scheme. So either the proxy needs to clearly indicate what it supports or it is going to fail. It is difficult to make guesses without actually seeing the exchange.

**Comment by grazius** [comment] 2023-06-07 08:15
Hello

> I don't understand the last comment @grazius.

It's just to say that the HttpEnvironmentProxy code use a NetworkCredential where in my "Non System proxy" implementation i need to use a CredentialCache... So i'm not surprised that the return code is 407 when we try to use environment variable to specify the proxy. 

>  So either the proxy needs to clearly indicate what it supports or it is going to fail.

```
# define proxy without creds
export HTTPS_PROXY='http://my-corporate-proxy:3128'
# make a simple curl (over the proxy)
curl -vvv https://www.google.com                                       

* Uses proxy env variable HTTPS_PROXY == 'http://my-corporate-proxy:3128'
*   Trying 1.1.1.1:3128...
* Connected to my-corporate-proxy (1.1.1.1) port 3128 (#0)
* allocate connect buffer
* Establish HTTP proxy tunnel to www.google.com:443
> CONNECT www.google.com:443 HTTP/1.1
> Host: www.google.com:443
> User-Agent: curl/7.87.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 407 authenticationrequired
< Via: x.x.x.x (McAfee Web Gateway version)
< Date: Wed, 07 Jun 2023 07:47:27 GMT
< Content-Type: text/html
< Cache-Control: no-cache
< Content-Length: 3785
< X-Frame-Options: deny
< Proxy-Connection: Keep-Alive
< Proxy-Authenticate: Negotiate
< Proxy-Authenticate: Basic realm="Directory identifier (LDAP)"
< 
* Ignore 3785 bytes of response-body
* CONNECT tunnel failed, response 407
* Closing connection 0
curl: (56) CONNECT tunnel failed, response 407
```
What our corporate proxy does not indicate clearly that make the authentication fail with proxy define as environment variable ?

Best regards

**Comment by wfurt** [comment] 2023-06-07 08:23
The `Proxy-Authenticate: Negotiate` should be sufficient and it should take precedence over `Basic`. It is not clear to me why `Basic` would be advertised when not functional but that is irrelevant. When you connect do you see `Negotiate` scheme in follow-up request or do you `Basic` or would it just stop there? 

And what .NET version do you use? https://github.com/dotnet/runtime/issues/887 was fixed in 6.0 so it _should_ work if you use recent versions.

**Comment by grazius** [comment] 2023-06-07 13:03
Yes regarding the code previously provided
```
var client = new HttpClient(handler: httpClientHandler, disposeHandler: true);
```

**Comment by grazius** [comment] 2023-06-08 11:33
Hello
i make tcpdump to understand what is done.
```
-------------
REQ 1
-------------

Hypertext Transfer Protocol
    CONNECT dev.azure.com:443 HTTP/1.1\r\n
    Host: dev.azure.com:443\r\n
    \r\n
    [Full request URI: dev.azure.com:443]
    [HTTP request 1/2]
    [Response in frame: 183]
    [Next request in frame: 206]

Hypertext Transfer Protocol
    HTTP/1.1 407 authenticationrequired\r\n
    Via: 1.1 1.1.1.1 (McAfee Web Gateway xxxx)\r\n
    Date: Thu, 08 Jun 2023 11:06:55 GMT\r\n
    Content-Type: text/html\r\n
    Cache-Control: no-cache\r\n
    Content-Length: 3783\r\n
    X-Frame-Options: deny\r\n
    Proxy-Connection: Keep-Alive\r\n
    Proxy-Authenticate: Negotiate\r\n
    Proxy-Authenticate: Basic realm="Directory identifier (LDAP)"\r\n
    \r\n
    [HTTP response 1/2]
    [Time since request: 0.005718000 seconds]
    [Request in frame: 179]
    [Next request in frame: 206]
    [Next response in frame: 209]
    [Request URI: dev.azure.com:443]
    File Data: 3783 bytes

-------------
REQ 2
-------------

Hypertext Transfer Protocol
    CONNECT dev.azure.com:443 HTTP/1.1\r\n
    Host: dev.azure.com:443\r\n
    Proxy-Authorization: Negotiate XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=\r\n
    \r\n
    [Full request URI: dev.azure.com:443]
    [HTTP request 2/2]
    [Prev request in frame: 179]
    [Response in frame: 209]

Hypertext Transfer Protocol
    HTTP/1.1 407 authenticationrequired\r\n
    Via: 1.1 1.1.1.1 (McAfee Web Gateway xxxx)\r\n
    Date: Thu, 08 Jun 2023 11:06:55 GMT\r\n
    Content-Type: text/html\r\n
    Cache-Control: no-cache\r\n
    Content-Length: 3783\r\n
    X-Frame-Options: deny\r\n
    Proxy-Connection: Keep-Alive\r\n
    Proxy-Authenticate: Negotiate\r\n
    Proxy-Authenticate: Basic realm="Directory identifier (LDAP)"\r\n
    \r\n
    [HTTP response 2/2]
    [Time since request: 0.005641000 seconds]
    [Prev request in frame: 179]
    [Prev response in frame: 183]
    [Request in frame: 206]
    [Request URI: dev.azure.com:443]
    File Data: 3783 bytes
```
So dotnet try to use the Negociate only

**Comment by grazius** [comment] 2023-06-08 12:05
To complete, on our Mac Workstation we've got Kerberos to interact with our Active Directory.
Maybe the case is not well supported on our proxy.

They're is a way to force the authentication scheme to Basic ?
Or to disable the NTLM support ?

Best regards

**Comment by wfurt** [comment] 2023-06-08 14:24
The `HttpClient` will try to find strongest authentication scheme and use it. If that fails, it would not try different scheme with same credentials.  Aside from the `CredentialCache` where the schemes are explicit there is no good way how to change it. If server does not offer `Negotiate`, HttpClient will use `Basic`. 

Note that `Negotiate` does not necessarily mean Kerberos. It can still be simple NTLM and there may be some variations on domain name and form.   

There was some discussion and insight in https://github.com/dotnet/runtime/issues/82547

**Comment by grazius** [comment] 2023-06-08 14:53
Our corporate proxy is used for internet access so i think it's normal that it present the Negociate Auth scheme before the Basic.

But here i use a dotnet application (this application is ArtifactTool developed internally by Microsoft).
This application is provided through the azure-cli (developped in Python) on we have no problem to use Basic auth.

The only way today i found to make this tool working is to had a mitmproxy without authentication that call our corporate proxy with the Basic auth ... But it's really a workaround.

What i don't understand here is our proxy work with java, python, a simple curl ... but not with dotnet core :(

So they're is a no way to force the authentication scheme to Basic ?
Or disable the NTLM support (in order to ignore Negociate) ?

Best regards

**Comment by wfurt** [comment] 2023-06-08 15:49
There is way but you need to do it explicitly and not via environment.

**Comment by wfurt** [comment] 2023-06-12 13:17
I feel this is corner case - this did not come up so far e.g. this is first instance. If anything you should figure out what the `Negotiate` does not work. Did you look at the issue I linked?

**Closed** 2023-07-10 18:02 UTC
Labels: area-System.Net.Http, os-mac-os-x, no-recent-activity, needs-author-action
