### ISSUE TITLE
[API Proposal]: System.Text.Json deserialize escaped Json string (from Python server) with properties of type ObservableCollection<CustomClass>

### ISSUE THREAD

**Issue by SunshineSpring666** [dotnet/runtime#76229] opened 2022-09-27 05:56 UTC
### Background and motivation

In a Client-Server or Browser-Server scenario, we may have some custom data models which may contain some properties of List<T>, where T might be any custom classes, or unicode strings, etc. e.g.:
```csharp
public class MyPoco
{
    public ObservableCollection<string> Names { get; set; } = new ObservableCollection<string>;
}
```

Below is a demo Json string returned from a Python server (the object is serialized using the popular json.dumps() method). This is actually what we got directly from server end:
```csharp
"{"code":0,"data":"[{\"Names\":\"[\\\"\\u5f91\\u9a78\\\", \\\"\\u5f25\\u6622\\u6656\\\"]\", \"registry\": null}]"}"
```
(the data is generated by setting the json.dumps(MyPoco) to the dict["data"], then returns the dict to client)
We may need to first deserialize the outer structure into a Dictionary<string, object>, then we expect the dict["data"] string be to directly consumed by Serializer.Deserialize<MyPoco>(dict["data"]), without the need of any custom converter. 

Note that if we serialize then deserialize this custom class back and forth just using the System.Text.Json Serializer, no custom converter is needed. But, the server-returned Json string is escaped, making the Serializer throws exception when parsing properties of type ObservableCollection<T>. Since:
\" should be "
"[ should be [
]" should be ]

We expect System.Text.Json could directly consumed the escaped Json string, and parse the contained object's properties to their corresponding types, including parsing a list of T-type objects' json into corresponding ObservableCollection<T> properties.

Currently, such escaped Json cannot be directly consumed by Serializer. If we use Regex.Unescape() before deserialization, the unicode chars cannot be properly handled. If we define and use custom converter and apply it to each and every property of ObservableCollection<T> type, there would be so many such calls. 

I hope System.Text.Json can handle such escaped strings properly. Since the types are explicitly defined as ObservableCollection<SomeCustomType>, if the Serializer detects such escaped characters or parse failure, it tries to unescape it first then deserialize it.

Discussions are made [here](https://github.com/dotnet/runtime/issues/76130)

### API Proposal

```csharp
namespace System.Text.Json;

JsonSerializerOptions options = new JsonSerializerOptions()
{
    AllowUnescapedString = true,
};
System.Text.Json.JsonSerializer.Deserialize<ObservableCollection<SomeCustomType>>(JsonReturnedFromServer, options);
    
```

### API Usage

```csharp
namespace System.Text.Json;

public string JsonReturnedFromServer { get; set; } = "{\"code\":0,\"data\":\"[{\\\"Names\\\":\\\"[\\\\\\\"\\\\u5f91\\\\u9a78\\\\\\\", \\\\\\\"\\\\u5f25\\\\u6622\\\\u6656\\\\\\\"]\\\", \\\"registry\\\": null}]\"}";

private void UseSystemTextJson()
{
        JsonSerializerOptions options = new JsonSerializerOptions()
        {
            AllowUnescapedString = true,
        };
        var dict = System.Text.Json.JsonSerializer.Deserialize<Dictionary<string, object>>(JsonReturnedFromServer, options);
        var dat = System.Text.Json.JsonSerializer.Deserialize<ObservableCollection<MyPoco>>(dict["data"].ToString(), options);
}
```

**Comment by svick** [comment] 2022-09-27 10:03
I think having to do exactly what you want is extremely rare, so it is not worth having a special option just for that. On the other hand, System.Text.Json should be customizable enough so that you can do it yourself. And luckily for you, it is. What you need:

1. The `ObservableConverter<T>` from [your previous issue](https://github.com/dotnet/runtime/issues/76130). Though you need to make sure to pass `options` when you're calling `JsonSerializer.Deserialize` there, so that the converter is still used in the nested deserialization.
2. Converter factory for the generic converter. [This example](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/converters-how-to?pivots=dotnet-7-0#support-round-trip-for-stackt) has one you can use, after replacing `Stack` with the types you need.

**Comment by eiriktsarpalis** [comment] 2022-09-27 11:22
I would recommend keeping the conversation in the [original issue](https://github.com/dotnet/runtime/issues/76130), so as to not bifurcate the conversation. We can make a decision there if and what API proposal is needed.

Dupe of #76229.

**Closed by eiriktsarpalis** 2022-09-27 11:22 UTC
Labels: api-suggestion, area-System.Text.Json, untriaged
