### ISSUE TITLE
Test failure System.Net.Http.Functional.Tests.TelemetryTest_Http11.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#49350] opened 2021-03-09 02:13 UTC
Run: [runtime-libraries-coreclr outerloop 20210308.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1026996&view=ms.vss-test-web.build-test-results-tab&runId=31900290&resultId=104424&paneView=debug)

Failed test:
```
net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c
 -System.Net.Http.Functional.Tests.TelemetryTest_Http11.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue
```

**Error message:**
```
Half-way through waiting for remote process.
Memory load: 30

Image Name PID Services 
========================= ======== ============================================
svchost.exe 472 DcomLaunch, LSM, SystemEventsBroker 
svchost.exe 952 RpcEptMapper, RpcSs 
svchost.exe 4160 gpsvc, iphlpsvc, ProfSvc, Schedule, SENS, 
 UserManager, Winmgmt 
svchost.exe 3600 EventSystem, nsi, RemoteRegistry 
svchost.exe 3948 Dhcp, EventLog, TimeBrokerSvc, 
 WinHttpAutoProxySvc 
svchost.exe 708 CryptSvc, Dnscache, LanmanWorkstation, WinR 
svchost.exe 3332 DiagTrack 
svchost.exe 3872 CoreMessagingRegistrar 
svchost.exe 396 SysMain 
svchost.exe 2948 WerSvc 
Timed out at 3/8/2021 12:42:27 PM after 60000ms waiting for remote process.
Wrote mini dump to: C:\helix\work\workitem\uploads\1924.tkx0yt2x.x3r.dmp
\tProcess ID: 1924
\tHandle: 2768
\tName: dotnet
\tMainModule: C:\helix\work\correlation\dotnet.exe
\tStartTime: 3/8/2021 12:41:26 PM
\tTotalProcessorTime: 00:00:00.6718750
\tThreads:
\t\tThread #1 (OS 0xDA4) [MTA]
\t\t\t[HelperMethodFrame]
\t\t\tSystem.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
\t\t\tMicrosoft.DotNet.RemoteExecutor.Program.Main(System.String[])
\t\t\t[HelperMethodFrame]
\t\t\tSystem.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
\t\t\tSystem.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
\t\t\tSystem.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
\t\t\tSystem.Runtime.CompilerServices.TaskAwaiter.GetResult()
\t\t\tMicrosoft.DotNet.RemoteExecutor.Program.Main(System.String[])
\t\tThread #2 (OS 0x804) [Finalizer] [Background] [MTA]
\t\t\t[DebuggerU2MCatchHandlerFrame]
\t\tThread #4 (OS 0xDAC) [Background] [MTA]
\t\t\t[HelperMethodFrame] (System.Threading.WaitHandle.WaitOneCore)
\t\t\tSystem.Threading.WaitHandle.WaitOneNoCheck(Int32)
\t\t\tSystem.Diagnostics.Tracing.CounterGroup.PollForValues()
\t\t\tSystem.Threading.Thread.StartCallback()
\t\t\t[DebuggerU2MCatchHandlerFrame]
\t\tThread #5 (OS 0x3B4) [Thread pool worker] [Background] [MTA]
\t\tThread #6 (OS 0x324) [Thread pool completion port] [Background] [MTA]
\t\tThread #8 (OS 0x120C) [Thread pool worker] [Background] [MTA]
\t\t\t[HelperMethodFrame] (System.Threading.WaitHandle.WaitOneCore)
\t\t\tSystem.Threading.WaitHandle.WaitOneNoCheck(Int32)
\t\t\tSystem.Threading.WaitHandle.WaitOne()
\t\t\tSystem.Threading.PortableThreadPool+GateThread.GateThreadStart()
\t\t\tSystem.Threading.Thread.StartCallback()
\t\t\t[DebuggerU2MCatchHandlerFrame]

Stack trace
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/RemoteInvokeHandle.cs:line 224
   at System.Net.Http.Functional.Tests.TelemetryTest.EventSource_ConnectionPoolAtMaxConnections_LogsRequestLeftQueue() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/TelemetryTest.cs:line 553


```

**Comment by ManickaP** [comment] 2021-03-11 17:18
Triage: we should investigate for 6.0

**Comment by MihaZupan** [comment] 2021-03-25 02:22
Duplicate of #46073

**Closed by MihaZupan** 2021-03-25 02:22 UTC
Labels: arch-x64, area-System.Net.Http, os-windows
