### ISSUE TITLE
Ldap GetMembers working over 389 port

### ISSUE THREAD

**Issue by AALOON** [dotnet/runtime#65894] opened 2022-02-25 14:25 UTC
### Description

Hi!

When GroupPrincipal.GetMembers used and 389 port blocked on machine (and 636 specified on connection string)
Method not working

problem is here:
https://github.com/dotnet/runtime/blob/main/src/libraries/System.DirectoryServices.AccountManagement/src/System/DirectoryServices/AccountManagement/AD/ADStoreCtx.cs
protected virtual void LoadDomainInfo()

![image](https://user-images.githubusercontent.com/14330773/155730260-08c31778-4562-4f00-8ec6-e9c29ae0310e.png)

### Reproduction Steps

var  options = Negotiate | SecureSocketLayer;
using var context = new PrincipalContext( ContextType.Domain, "domain:636", "DC=domain", options);
using (var indentity = GroupPrincipal.FindByIdentity(context, "Group"))
{
    var tmp = indentity.GetMembers(true).First(); // we will wall
}

### Expected behavior

When domain specified, used same port (LDAPS) communication

### Actual behavior

Method failed when 389 blocked

### Configuration

- Net462, NetCore31, NetCore5 and other
- Windows
- Debug, Release

**Comment by danmoseley** [comment] 2022-02-28 03:32
Hi @AALOON thanks for the report. Do you want to debug a little to find where the cause might be?

**Comment by AALOON** [comment] 2022-02-28 09:30
@danmoseley 
Actually, I debugged it. And link to source code and image show the place where it goes wrong.
When we loading group from sub domain or just different group type (e.g. security) we will LoadDomainInfo information (protected virtual void LoadDomainInfo()).
Where method loads DnsHostName and builds up ldap link on  default port (389)
Load triggered by accessing to properties such this
![image](https://user-images.githubusercontent.com/14330773/155956594-fd634d79-c49b-4dd9-9a17-9fc38d8c755e.png)
also same problem exists in DirectoryEntry domainNC = SDSUtils.BuildDirectoryEntry(
I don't know but there could be two potential fixes if I am not mistaken:
1) switch dnsHostName to UserSuppliedServerName (but there could be problems on sub domain groups)
2) switch AuthenticationTypes.Anonymous -> this.authTypes (but I also don't know how it can impact other domains)

Also I can create pull request if some one who understands ldap and this policy, will say I am right or I am wrong and that designed to work this way.

If there need any other debug information I will help.

**Comment by joperezr** [comment] 2022-03-23 16:52
cc: @jay98014 and @kumarravi do you mind taking a look?

**Comment by patrickulrich007** [comment] 2023-01-17 23:15
Is this issues fixed? I have the same problem, it will be more and more important, as customers start switching from LDAP to LDAPS and closing the 389 port.

**Comment by buyaa-n** [comment] 2023-01-18 18:15
ping @jay98014 and @kumarravi again

**Comment by patrickulrich007** [comment] 2023-02-03 12:25
Is there an other way with C#, to get the groups from a user, with .net libraries? I know, that I could do it directly with LDAP queries, but I would like to avoid that.

**Comment by kumarravik78c** [comment] 2023-09-12 17:27
I have approved the PR after validating the fix on my local set up.

**Closed** 2023-09-13 20:10 UTC
Labels: area-System.DirectoryServices, in-pr
