### ISSUE TITLE
Customer reports occasional errors in event log when stopping Windows service

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#66294] opened 2022-03-07 14:49 UTC
### Description

Customer reports that when starting/stopping their .NET based Windows service many times, there occasionally will be an error in the event log that erroneously reports that the service stopped unexpectedly, even though the stop is actually expected and was requested via the SCM.

(I have not been able to repro locally yet.)

Reached out to understand whether the concern is simply that the error is wrong/confusing to anyone that looks into the event log, or a more significant functional bug.

### Reproduction Steps

1. Install the test service: sc.exe create TestService binpath= <path-to-extract-dir>\TestWinService.exe
2. Open the services manager, right click on TestService, go to properties, switch to the Log On tab, change the user to "Local Service" (NT AUTHORITY\LOCAL SERVICE). Delete the password fields and click OK.
3. From a Powershell window, run the restart_loop.ps1 script. After awhile (usually within an hour or so, often much less), the event log will have at least one error as listed in the description.
4. To clean the system, run: sc.exe delete TestService

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="5.0.1" />
  </ItemGroup>

</Project>
```
```c#
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace TestWinService
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args)
        {

            var builder = Host.CreateDefaultBuilder(args)
                .ConfigureLogging((hostContext, logger) =>
                {
                    logger.SetMinimumLevel(LogLevel.Trace);
                    logger.AddConsole();
                })
                .ConfigureServices((hostContext, services) =>
                {
                    services.AddSingleton<TestService>();
                    services.AddHostedService<TestService>(x => x.GetRequiredService<TestService>());
                });

            builder.UseWindowsService();
            return builder;
        }
    }

    class TestService : BackgroundService
    {
        private readonly ILogger<TestService> logger;
        public TestService(ILogger<TestService> logger)
        {
            this.logger = logger;
        }
        protected async override Task ExecuteAsync(CancellationToken stoppingToken)
        {
            while (!stoppingToken.IsCancellationRequested)
            {
                this.logger.LogError("Ping!");
                await Task.Delay(2000);
            }
        }
    }
}
```
```ps1
while($true)
{
	sc.exe start TestService
	echo "Service started"
	Start-Sleep -m 5000
	sc.exe stop TestService
	echo "Service stopped"
	Start-Sleep -m 5000
}
```

Note that the service when running as "Local Service" does not have permission to write to the event log. That's presumably not relevant: the messages here are coming from the SCM.

### Expected behavior

No erroneous SCM errors in the event log.

### Actual behavior

snippet from event log created by repro code above
```
Relevant log excerpt:
[0]0338.18A8::06/17/2021-17:40:40.952 [SCM]------ Starting services in group Null -----
[0]0338.18A8::06/17/2021-17:40:40.952 [SCM]BIG LOOP COUNT 1 - Service: TestService
[0]0338.18A8::06/17/2021-17:40:40.952 [SCM]TestService is marked START NOW - Loop: 1
[0]0338.18A8::06/17/2021-17:40:40.952 [SCM]ScStartMarkedServicesInServiceSet: Starting TestService, share proc ID 0
[0]0338.18A8::06/17/2021-17:40:40.952 [Microsoft.Windows.ServiceControlManager]{"ServiceName":"TestService","OldState":1,"NewState":2,"DurationInMs":4000,"meta":{"provider":"Microsoft.Windows.ServiceControlManager","event":"ServiceStateChange","time":"2021-06-17T17:40:40.952","cpu":0,"pid":824,"tid":6312,"channel":11,"level":5,"keywords":"0x200000000000"}}
Unknown( 71): GUID=f563f025-6e86-3268-146c-3bf0aaf62bb4 (No Format Information found).
Unknown( 75): GUID=f563f025-6e86-3268-146c-3bf0aaf62bb4 (No Format Information found).
[0]0338.18A8::06/17/2021-17:40:40.956 [SCM]ScInitControlMessageContext: Channel 0x00000254A71DC130, event 0x0000000000000C20
[0]0338.0ED0::06/17/2021-17:40:41.124 [SCM]RI_ScOpenServiceChannelHandle: Caller PID 0x0000028c, context handle 0x00000254A71DC130, refs 0x2
[0]0338.18A8::06/17/2021-17:40:41.124 [SCM]ScWaitForFirstResponse: Received first response for TestService from pid 0X28C
[0]0338.18A8::06/17/2021-17:40:41.124 [Microsoft.Windows.ServiceControlManager]{"ServiceHostName":"C:\\publish\\TestWinService.exe","PID":652,"meta":{"provider":"Microsoft.Windows.ServiceControlManager","event":"ServiceHostStarted","time":"2021-06-17T17:40:41.124","cpu":0,"pid":824,"tid":6312,"channel":11,"level":5,"keywords":"0x200000000000"}}
[0]0338.18A8::06/17/2021-17:40:41.124 [SCM]ScSendControl: Sending control 0x00000051 to service/module TestService, caller PID 0x00001620, channel 0x00000254A71DC130, refs 0x3
[0]0338.0ED0::06/17/2021-17:40:41.124 [SCM]RI_ScOpenServiceStatusHandle: Service TestService, seq 0x629, status 0, PID 0x0000028c
[0]0338.18A8::06/17/2021-17:40:41.125 [Microsoft.Windows.ServiceControlManager]{"ServiceName":"TestService","StartReason":1,"LoadOrderGroup":"None","SvchostGroup":"None","PID":652,"IsCritical":false,"IsUserService":false,"IsOwnProcess":true,"TriggerType":0,"meta":{"provider":"Microsoft.Windows.ServiceControlManager","event":"ServiceStarted","time":"2021-06-17T17:40:41.125","cpu":0,"pid":824,"tid":6312,"channel":11,"level":5,"keywords":"0x200000000000"}}
[0]0338.18A8::06/17/2021-17:40:41.125 [SCM]Database Lock is OFF (from API)
Unknown( 13): GUID=f563f025-6e86-3268-146c-3bf0aaf62bb4 (No Format Information found).
Unknown( 14): GUID=f563f025-6e86-3268-146c-3bf0aaf62bb4 (No Format Information found).
[0]0338.18A8::06/17/2021-17:40:41.127 [SCM]RSetServiceStatus:  Status field accepted, service TestService, state 0x00000002(SERVICE_START_PENDING), exit 0, sexit 0, controls 0x00000005
[0]0338.18A8::06/17/2021-17:40:41.127 [SCM]Service Record updated with new status for service TestService
[0]0338.18A8::06/17/2021-17:40:41.130 [SCM]RSetServiceStatus:  Status field accepted, service TestService, state 0x00000004(SERVICE_RUNNING), exit 0, sexit 0, controls 0x00000005
[0]0338.18A8::06/17/2021-17:40:41.130 [Microsoft.Windows.ServiceControlManager]{"ServiceName":"TestService","OldState":2,"NewState":4,"DurationInMs":188,"meta":{"provider":"Microsoft.Windows.ServiceControlManager","event":"ServiceStateChange","time":"2021-06-17T17:40:41.130","cpu":0,"pid":824,"tid":6312,"channel":11,"level":5,"keywords":"0x200000000000"}}
[0]0338.18A8::06/17/2021-17:40:41.130 [SCM]Service Record updated with new status for service TestService
[0]0338.18A8::06/17/2021-17:40:41.130 [SCM]TestService START_PENDING -> RUNNING
[0]0338.18A8::06/17/2021-17:40:46.142 [SCM]ScControlService: Service TestService, control 1, reason 0x00000000, comment NULL
[0]0338.18A8::06/17/2021-17:40:46.142 [SCM]ScSendControl: Sending control 0x00000001 to service/module TestService, caller PID 0x00001634, channel 0x00000254A71DC130, refs 0x3
[0]0338.18A8::06/17/2021-17:40:46.142 [Microsoft.Windows.ServiceControlManager]{"ServiceName":"TestService","ControlCode":1,"meta":{"provider":"Microsoft.Windows.ServiceControlManager","event":"ServiceSendControl","time":"2021-06-17T17:40:46.142","cpu":0,"pid":824,"tid":6312,"channel":11,"level":5,"keywords":"0x200000000000"}}
[0]0338.0ED0::06/17/2021-17:40:46.144 [SCM]RSetServiceStatus:  Status field accepted, service TestService, state 0x00000003(SERVICE_STOP_PENDING), exit 0, sexit 0, controls 0x00000005
[0]0338.0ED0::06/17/2021-17:40:46.144 [Microsoft.Windows.ServiceControlManager]{"ServiceName":"TestService","OldState":4,"NewState":3,"DurationInMs":5000,"meta":{"provider":"Microsoft.Windows.ServiceControlManager","event":"ServiceStateChange","time":"2021-06-17T17:40:46.144","cpu":0,"pid":824,"tid":3792,"channel":11,"level":5,"keywords":"0x200000000000"}}
[0]0338.0ED0::06/17/2021-17:40:46.144 [SCM]Service Record updated with new status for service TestService
[0]0338.18A8::06/17/2021-17:40:46.144 [SCM]ScSendControl: Service TestService, control 1, user S-1-5-21-2088405651-850969028-1873988176-1000, caller PID 0x00001634
[0]0338.18A8::06/17/2021-17:40:46.144 [SCM]RSetServiceStatus:  Status field accepted, service TestService, state 0x00000003(SERVICE_STOP_PENDING), exit 0, sexit 0, controls 0x00000005
[0]0338.18A8::06/17/2021-17:40:46.144 [SCM]Service Record updated with new status for service TestService
[0]0338.18A8::06/17/2021-17:40:47.150 [SCM]RSetServiceStatus:  Status field accepted, service TestService, state 0x00000003(SERVICE_STOP_PENDING), exit 0, sexit 0, controls 0x00000005
[0]0338.18A8::06/17/2021-17:40:47.150 [SCM]Service Record updated with new status for service TestService
[0]0338.22C4::06/17/2021-17:40:47.150 [SCM]RSetServiceStatus:  Status field accepted, service TestService, state 0x00000003(SERVICE_STOP_PENDING), exit 0, sexit 0, controls 0x00000005
[0]0338.22C4::06/17/2021-17:40:47.150 [SCM]Service Record updated with new status for service TestService
Unknown( 93): GUID=f563f025-6e86-3268-146c-3bf0aaf62bb4 (No Format Information found).
Unknown( 38): GUID=2690e78e-f395-3cf2-0a73-3f394cab6882 (No Format Information found).
[0]0338.18A8::06/17/2021-17:40:47.181 [Microsoft.Windows.ServiceControlManager]{"ServiceHostName":"C:\\publish\\TestWinService.exe","meta":{"provider":"Microsoft.Windows.ServiceControlManager","event":"ServiceHostFailed","time":"2021-06-17T17:40:47.181","cpu":0,"pid":824,"tid":6312,"channel":11,"level":5,"keywords":"0x400000000000"}}
Unknown( 39): GUID=2690e78e-f395-3cf2-0a73-3f394cab6882 (No Format Information found).
[0]0338.18A8::06/17/2021-17:40:47.181 [Microsoft.Windows.ServiceControlManager]{"ServiceName":"TestService","ImageName":"C:\\publish\\TestWinService.exe","IsOwnProcess":true,"ShutdownInProgress":false,"Reason":1,"Status":1287,"meta":{"provider":"Microsoft.Windows.ServiceControlManager","event":"ServiceFailed","time":"2021-06-17T17:40:47.181","cpu":0,"pid":824,"tid":6312,"channel":11,"level":5,"keywords":"0x400000000000"}}
[0]0338.18A8::06/17/2021-17:40:47.181 [SCM]CWin32ServiceRecord::QueueRecoveryAction: Failure count for TestService incremented to 1.
[0]0338.18A8::06/17/2021-17:40:47.181 [Microsoft.Windows.ServiceControlManager]{"ServiceName":"TestService","FailCount":1,"ActionDelay":0,"ActionType":0,"ResetPeriod":4294967295,"FailureReason":1,"IsOwnProcess":true,"Action":"None","meta":{"provider":"Microsoft.Windows.ServiceControlManager","event":"ServiceRecoveryAction","time":"2021-06-17T17:40:47.181","cpu":0,"pid":824,"tid":6312,"channel":11,"level":5,"keywords":"0x400000000000"}}
[0]0338.18A8::06/17/2021-17:40:47.181 [Microsoft.Windows.ServiceControlManager]{"ServiceName":"TestService","OldState":3,"NewState":1,"DurationInMs":1046,"meta":{"provider":"Microsoft.Windows.ServiceControlManager","event":"ServiceStateChange","time":"2021-06-17T17:40:47.181","cpu":0,"pid":824,"tid":6312,"channel":11,"level":5,"keywords":"0x200000000000"}}
[0]0338.18A8::06/17/2021-17:40:47.181 [SCM]SC_SERVICE_CHANNEL_CONTEXT_HANDLE_rundown: Context handle 0x00000254A71DC130
[0]0338.18A8::06/17/2021-17:40:47.181 [SCM]RI_ScCloseServiceChannelHandle: Context handle 0x00000254A71DC130
```

### Regression?

unknown.

### Configuration

.NET 5

### Other information

partner report, tracked internally by https://microsoft.visualstudio.com/OS/_workitems/edit/33989430?src=WorkItemMention&src-action=artifact_link

**Comment by danmoseley** [comment] 2022-03-07 15:27
@ericstj is anyone on @dotnet/area-system-serviceprocess available to spend say an hour looking at this this week? I attempted to repro but did not. I've reached out to the partner to understand the priority (details in link above)

**Comment by ericstj** [comment] 2022-03-07 20:31
This looks like a duplicate of https://github.com/dotnet/runtime/issues/62579.  Let me know if you agree.

**Comment by danmoseley** [comment] 2022-03-07 20:44
Oh! Yes it is. I'll post to ask how important a fox is to them as it's not at all clear this would meet a servicing bar.

**Closed** 2022-03-07 20:44 UTC
Labels: area-System.ServiceProcess, untriaged
