### ISSUE TITLE
.NET Global Tools fail to launch of Apple Silicon

### ISSUE THREAD

**Issue by richlander** [dotnet/runtime#52335] opened 2021-04-23 14:16 UTC
This is my experience on Big Sur 11.3 (Apple Silicon).

```bash
rich@MacBook-Air ~ % rm -r .dotnet/tools 
rich@MacBook-Air ~ % dotnet tool list -g
Package Id      Version      Commands
-------------------------------------
rich@MacBook-Air ~ % dotnet tool install -g dotnet-runtimeinfo
You can invoke the tool using the following command: dotnet-runtimeinfo
Tool 'dotnet-runtimeinfo' (version '1.0.4') was successfully installed.
rich@MacBook-Air ~ % dotnet-runtimeinfo
zsh: killed     dotnet-runtimeinfo
rich@MacBook-Air ~ % codesign -s - ~/.dotnet/tools/dotnet-runtimeinfo 
rich@MacBook-Air ~ % dotnet-runtimeinfo 
**.NET information
Version: 6.0.0
FrameworkDescription: .NET 6.0.0-preview.3.21201.4
Libraries version: 6.0.0-preview.3.21201.4
Libraries hash: 236cb21e3c1992c8cee6935ce67e2125ac4687e8

**Environment information
OSDescription: Darwin 20.4.0 Darwin Kernel Version 20.4.0: Fri Mar  5 01:14:02 PST 2021; root:xnu-7195.101.1~3/RELEASE_ARM64_T8101
OSVersion: Unix 11.3.0
OSArchitecture: Arm64
ProcessorCount: 8

rich@MacBook-Air ~ % dotnet runtimeinfo
**.NET information
Version: 6.0.0
FrameworkDescription: .NET 6.0.0-preview.3.21201.4
Libraries version: 6.0.0-preview.3.21201.4
Libraries hash: 236cb21e3c1992c8cee6935ce67e2125ac4687e8

**Environment information
OSDescription: Darwin 20.4.0 Darwin Kernel Version 20.4.0: Fri Mar  5 01:14:02 PST 2021; root:xnu-7195.101.1~3/RELEASE_ARM64_T8101
OSVersion: Unix 11.3.0
OSArchitecture: Arm64
ProcessorCount: 8
```

`codesign` is the missing link. I think we need to run it upon installation of .NET global tools.

I do not see the behavior for x64 emulation. It is apparently subject to different rules.

**Comment by NikolaMilosavljevic** [comment] 2021-05-12 20:52
[Triage] @marcpopMSFT this looks like a new requirement for global tool installation script/process. Does your team own this?

**Comment by marcpopMSFT** [comment] 2021-05-13 20:14
@NikolaMilosavljevic my understanding from @wli3 is that this would be signing needed during the apphost creation on install and that that apphost creation process was on the runtime (hence moving it over)

**Comment by NikolaMilosavljevic** [comment] 2021-05-13 20:28
> @NikolaMilosavljevic my understanding from @wli3 is that this would be signing needed during the apphost creation on install and that that apphost creation process was on the runtime (hence moving it over)

We do produce unsigned apphost in dotnet/runtime, but, Global tool installation process generates machine specific version of apphost during installation.

It seems to me that whichever process does the install of the global tool and generates apphost during installation, needs to sign it, also during installation.

**Comment by KevinCathcart** [comment] 2021-05-14 02:01
The SDK global tool install code eventually calls into the SDK's [ShellShim code](https://github.com/dotnet/sdk/blob/a30e465a2e2ea4e2550f319a2dc088daaafe5649/src/Cli/dotnet/ShellShim/AppHostShimMaker.cs) to create the apphost, but actual apphost creation is handled by the runtime's HostModel code. (Specifically [HostWriter.CreateAppHost](https://github.com/dotnet/runtime/blob/7185031f3456539f1b2e8eb38db578db85b8f6ff/src/installer/managed/Microsoft.NET.HostModel/AppHost/HostWriter.cs)). That code would be area-HostModel. 

There are two approaches.

One option is to run Apple's `codesign` tool, which is only going to be available on Apple platforms. (It is open source, so in theory creating a cut down version that can run on other platforms might be possible, but the C# approach would probably be simpler). This has the limitation that other scenarios like cross-platform publish won't work on Apple Silicon. For this scenario, it is not completely clear to me if the code to do that definitely belongs in the HostModel code or if it might belong elsewhere, but the team in charge of the HostModel can help determine that.

The other option is to have C# code directly generate the ad-hoc signature. If we did that, it unquestionably belongs in the HostModel code (the existing code to remove signatures lives there). Other languages (including [golang](https://github.com/golang/go/blob/12d383c7c7406dda2cb969a89ce3801c220614c5/src/cmd/internal/codesign/codesign.go)) are taking this approach. So porting what they do might be possible.  

Hope this helps.

**Comment by vitek-karas** [comment] 2021-05-14 19:20
Just curious what problem there is with relying on `codesign` - one can only install macOS ARM64 binaries on macOS, so the tool should always be there.

Do golang and others provide "global tool" experience similar to ours?

That said - having the ability to "auto-sign" macOS binaries on any platform would be beneficial since we do support cross-targeting.

**Comment by KevinCathcart** [comment] 2021-05-14 20:54
Using `codesign` for global tools installation is not a problem. It would work just fine. I only propose the other approach because it potentially solves two problems at once. The codesign approach is probably faster and easier to code, so doing that as an initial fix for this particular issue is sensible. If later on, the other approach is used to make cross-targeting work better, global tools could be updated to use the new approach.

Golang wanted to sign the apps itself for because of a unique feature of their linking process called the buildid, which is something added to the executable based in part on a hash of the executable. They determined that having their own linker call out to `codesign` would not work, because of the buildid. If they apply it before before `codesign`, then `codesign`'s reformating of the executable invalidates their buildid. If they do it after `codesign` then they have just invalidated the signature. In order to make them play nicely, they needed to modify the buildid algorithm to ignore the signature block's contents, be able to reformat the executable as if it was signed, stamp the executable with the buildid, and then calculate the signature, and put it where it belongs. 

I'm pretty sure golang also supports cross-compilation, which would give a second reason to want to support calculating the signatures themselves.

**Comment by agocke** [comment] 2021-05-14 22:32
https://github.com/dotnet/runtime/issues/50375 tracks signing on Mac. I think we should start by signing whenever publishing for Mac, on Mac, then support cross-compilation later if necessary.

**Comment by KevinCathcart** [comment] 2021-05-15 00:53
That is certainly reasonable. Obviously code wise the global tools signing is likely to be basically the same as signing on publish for Mac, so solving that one by shelling out to `codesign -s - ExecutableName` would likely fix this global tool case as a side effect.

**Comment by richlander** [comment] 2021-05-15 15:22
npm has the closest global tools experience. It relies on shell scripts with the node runtime as the shebang provider. As a result, I don't think they'll have this issue. node itself appears to be a universal binary on Apple Silicon, although that's not all that relevant to the conversation.

More context:

```bash
rich@thundera ~ % sudo npm install -g yarn    
rich@thundera ~ % which yarn
/usr/local/bin/yarn
rich@thundera ~ % ls -l /usr/local/bin/yarn                       
lrwxr-xr-x  1 rich  admin  36 May 15 07:57 /usr/local/bin/yarn -> ../lib/node_modules/yarn/bin/yarn.js
rich@thundera ~ % cat /usr/local/bin/yarn
#!/usr/bin/env node
// snip
```

We could switch to scripts on macOS to work around this problem. That would be unfortunate, and also appears unnecessary. I believe at least the PowerShell tool signs its apphost as policy requirement. We'd have to revisit that if we moved to scripts.

The golang issue doesn't seem exactly the same. I don't think we have an analog to that.

**Comment by KevinCathcart** [comment] 2021-05-15 16:34
Agreed that golang reasoning for needing to implement signing itself does not apply. The only way there could be a similar need would be if apphost was designed to try to verify its own integrity with an injected checksum of itself or something along those lines, and it does not do that [0]. I pointed golang out more to show that there is precedent for languages implementing the signing logic themselves.

While .NET is not unique in having an apphost style system, I think it might be unique in generating them on install for a global tools system. I do think most other languages with installable global tools systems use scripts. 

But having the ability to ad hoc sign in some way (either by calling out to codesign, or doing it manually) is needed for the Mac publishing scenario, unless that process can be redesigned to not require modifying the apphost from its original template, possibly utilizing either a script or a config file to provide it similar information. (This is unlike script-launched global tools that could theoretically utilize the muxer, to not need their own host). Furthermore not modifying the executable is totally not a good option for single file publishing.

So using the same solution as publishing needs seems like the obvious choice for global tools.

Footnote(s):
0. Authenticode’s interaction with strong name signatures is the closest thing .NET has, but: 1) MacOS does not care about PE format files being signed, 2) I think the validation code for strong names has been removed from coreclr, and 3) the strong name algorithm was designed to not only ignore the Authenticode signature, but also to ignore the changes to the executable’s structure that adding the signature entails, so the process does not need to be interleaved.

**Comment by richlander** [comment] 2021-05-15 17:06
> So using the same solution as publishing needs seems like the obvious choice for global tools.

Agreed.

**Comment by vitek-karas** [comment] 2021-07-09 13:34
@mateoatr Could you please see if the changes to always sign apphost on MacOS can be used by global tool installation as well?

**Comment by mateoatr** [comment] 2021-07-09 20:18
> @mateoatr Could you please see if the changes to always sign apphost on MacOS can be used by global tool installation as well?

Just tried it with the changes that I have on the open SDK PR and it appears to work.

```
dotnet-dev@DNCENGDEV-02 matorre % uname -a
Darwin DNCENGDEV-02.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 x86_64
dotnet-dev@DNCENGDEV-02 matorre % rm -rf ~/.dotnet/tools
dotnet-dev@DNCENGDEV-02 matorre % dotnet tool list -g
Package Id      Version      Commands
-------------------------------------
dotnet-dev@DNCENGDEV-02 matorre % dotnet tool install -g dotnet-runtimeinfo 
You can invoke the tool using the following command: dotnet-runtimeinfo
Tool 'dotnet-runtimeinfo' (version '1.0.4') was successfully installed.
dotnet-dev@DNCENGDEV-02 matorre % dotnet-runtimeinfo
**.NET information
Version: 6.0.0
FrameworkDescription: .NET 6.0.0-preview.5.21301.5
Libraries version: 6.0.0-preview.5.21301.5
Libraries hash: ec3e0b276b159ab24946f17f2b89d00862488a6a

**Environment information
OSDescription: Darwin 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101
OSVersion: Unix 11.4.0
OSArchitecture: Arm64
ProcessorCount: 8
```

**Comment by richlander** [comment] 2021-07-09 21:31
That looks great. Huge improvement.

Is that enabled for both the x64 and Arm64 SDK on macOS?

**Comment by mateoatr** [comment] 2021-07-10 01:43
> Is that enabled for both the x64 and Arm64 SDK on macOS?

Yep, works on both. We made the [relevant changes](https://github.com/dotnet/runtime/pull/53913) in Microsoft.NET.HostModel a few weeks ago (unfortunately these didn't make it to preview 6).

**Comment by vitek-karas** [comment] 2021-07-15 09:50
Any idea if we can add a test for this somewhere? (I want to close this issue since it's fixed, but without any test coverage... it's risky).

**Comment by agocke** [comment] 2021-08-02 17:43
I think we can close this as fixed for `HostModel`. .NET Global tools need to have their own testing -- and that should be a separate issue.

Created https://github.com/dotnet/sdk/issues/19463 to track

**Comment by wli3** [comment] 2021-09-20 20:51
@agocke @vitek-karas see https://github.com/dotnet/efcore/issues/25927#issuecomment-923175239 it still happens in RC1

**Comment by vitek-karas** [comment] 2021-09-20 21:00
The killed message is typically because you try to run arm64 executable which is not signed (x64 should not require signing yet). But we will have to try this obviously.

**Comment by mateoatr** [comment] 2021-09-20 22:16
> The killed message is typically because you try to run arm64 executable which is not signed (x64 should not require signing yet). But we will have to try this obviously.

I just tried it, and this is indeed the case. I followed the repro steps in https://github.com/dotnet/efcore/issues/25927 with the rc1 bits and the executable is not signed. I'm investigating.

**Comment by mateoatr** [comment] 2021-09-21 00:22
Looks like installing through `dotnet tool` will not set `AppHostSourcePath`, thus not entering the `CreateAppHost` target nor creating an apphost that can be signed (using the `CreateAppHost` task).

**Comment by agocke** [comment] 2021-10-04 21:03
Dup of https://github.com/dotnet/sdk/issues/21349

**Closed by agocke** 2021-10-04 21:03 UTC
Labels: area-HostModel
