### ISSUE TITLE
Zombie thread created by System.DirectoryServices.Protocols.LdapConnection

### ISSUE THREAD

**Issue by robsonj** [dotnet/runtime#75614] opened 2022-09-14 16:22 UTC
If I construct a new `LdapConnection()`, it spawns a new background thread called '.NET LDAP Results Retriever', which remains after the `LdapConnection` has been disposed. There doesn't seem to be any way to end this background thread, it seems to sit there until the process exits.

To create the issue...

```
            var connection = new LdapConnection(LDAP_SERVER, LDAP_SEARCHER);
            connection.Dispose();
```

Note the background thread (named '.NET LDAP Results Retriever') which remains, with no facility to end it

**Comment by joperezr** [comment] 2022-09-28 17:14
Thanks for the report @robsonj. Can you please share a bit more about your environment? In particular, are you running on Windows or Unix? We use different underlying native implementations which handle the LDAP communication depending on that, so knowing the answer to that question would aid with the investigation and narrowing down of the problem. Can you also share which Target framework are you using? is this NET 7.0, Net 6.0? Finally, can you share the NuGet package version that you are using as well?

**Comment by robsonj** [comment] 2022-09-28 17:16
We are running on Linux, .net 6. Lemme get back to you on the package version

**Comment by robsonj** [comment] 2022-09-28 17:31
System.DirectoryServices.Protocols version 6.0.1

**Comment by RoadTrain** [comment] 2022-10-07 05:08
I think here it is: https://github.com/dotnet/runtime/blob/b38fb072af49cb4336428c57ff28a22cc5d72cc2/src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapPartialResultsProcessor.cs#L336
Indeed the `Thread` object is created and apparently is not handled later in any way.

**Comment by RoadTrain** [comment] 2022-10-15 03:52
I wonder what's the best approach to take here. Maybe rewrite this piece using some kind of abstraction like `BackgroundWorker` instead of a bare `Thread`? Or just implement `Dispose` to manage the thread termination?

**Comment by danmoseley** [comment] 2022-10-15 12:57
All this code predates modern practices. If we were to write it today I imagine it would use "Task". Would that require a lot of changes?

**Comment by hangy** [comment] 2022-10-26 17:24
What's interesting about the current implementation, is that it the partial result processor is used as a static instance for all `LdapConnection` instances: https://github.com/dotnet/runtime/blob/691cf0f448781df1379278943825a44c7120db75/src/libraries/System.DirectoryServices.Protocols/src/System/DirectoryServices/Protocols/ldap/LdapConnection.cs#L43 Therefore, `SearchRequest`s from different connections will likely not be done (or at least not returned) concurrently, and could have side-effects on unrelated requests. Is this something that a new (ie. `Task` based) implementation should keep?

**Comment by danmoseley** [comment] 2023-05-25 02:38
@hangy given this library has existed for a long time and is essentially considered stable, and we do not have data that that perf improvement is important, I would suggest to prefer compatibility with what it does today. Do you want to offer a PR?

**Comment by steveharter** [comment] 2023-07-24 21:20
Moving to future; if someone wants to modify the code to use `Task` instead of a background thread (or other suitable approach) we can move this to the current release.

**Comment by buyaa-n** [comment] 2024-07-24 17:05
> If I construct a new LdapConnection(), it spawns a new background thread called '.NET LDAP Results Retriever', which remains after the LdapConnection has been disposed. 

> I wonder what's the best approach to take here. Maybe rewrite this piece using some kind of abstraction like BackgroundWorker instead of a bare Thread? Or just implement Dispose to manage the thread termination?
> Is there any commonly used approach to this problem within the runtime?

For me it looks the current behavior is by design, it is background thread, isn't it expected to finish after the application stops? Isn't it not expected to finish after the LdapConnection disposed? I don't feel we should handle this manually, why do you think we need to handle this manually @robsonj @RoadTrain?

**Comment by RoadTrain** [comment] 2024-07-29 10:43
> For me it looks the current behavior is by design, it is background thread, isn't it expected to finish after the application stops? Isn't it not expected to finish after the LdapConnection disposed? I don't feel we should handle this manually, why do you think we need to handle this manually @robsonj @RoadTrain?

This behavior makes sense in cases when `LdapConnection` instances are used heavily, I suspect.
It doesn't make much sense if we only use `LdapConnection` to retrieve something during app initialization, to then have a thread doing nothing for the rest of the application lifetime.

I'd say rewriting it in an async pattern would be a good idea, but it seems to me the urgency is low.
At least there seems to be no leak.
Maybe this behavior just needs to be documented.

**Closed** 2024-08-29 06:05 UTC
Labels: bug, area-System.DirectoryServices, os-linux, no-recent-activity, in-pr, needs-author-action
