### ISSUE TITLE
Creating System.Uri with a relative Uri works on Linux and not Windows, without the `UriKind` enum provided

### ISSUE THREAD

**Issue by glitch100** [dotnet/runtime#69308] opened 2022-05-13 10:32 UTC
### Description

We came up against an issue where dev machines weren't able to get past a line that wasn't providing the `UriKind.Relative` into a new `Uri` being created, but it wasn't an issue until the Windows devs got there as both our CICD environment and other devs are using various distros of Linux. 

I was sure that maybe we had done something wrong as it seems like such a simple issue, but wrote a few lines to check it.

---
`Program.cs`
```c#
using System;
using System.Net.Http;
using static System.Console;

WriteLine("Creating Relative Uri");
_ = new Uri("/test/1234");
WriteLine("Done");
```

#### For Windows
`dotnet run` 
#### For Docker
`docker run --rm -it -v ${pwd}:/app/ -w /app mcr.microsoft.com/dotnet/sdk:6.0 dotnet run`

### Expected behavior

I would expect the following exception:
` System.UriFormatException: Invalid URI: The format of the URI could not be determined.`

### Actual behavior

Linux does not throw, Windows does

### Configuration

```
OS Name	Microsoft Windows 10 Pro
Version	10.0.19044 Build 19044
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Type	x64-based PC
Processor	Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz, 2592 Mhz, 6 Core(s), 12 Logical Processor(s)

```
For my own machine:
- SDKs
```
3.1.419 [C:\Program Files\dotnet\sdk]
5.0.408 [C:\Program Files\dotnet\sdk]
6.0.100 [C:\Program Files\dotnet\sdk]
6.0.105 [C:\Program Files\dotnet\sdk]
6.0.203 [C:\Program Files\dotnet\sdk]
```
- Runtimes
```
Microsoft.AspNetCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
``` 

For Linux  testing I used the following images in Docker
- `mcr.microsoft.com/dotnet/sdk:6.0`
- `mcr.microsoft.com/dotnet/runtime:6.0`

### Other information

After confirming it, I checked some of the code for initializing a new Uri and saw this block. I didn't dig any deeper but if it this it looks intentional? 
https://github.com/dotnet/runtime/blob/215b39abf947da7a40b0cb137eab4bceb24ad3e3/src/libraries/System.Private.Uri/src/System/UriExt.cs#L52-L65

**Comment by stephentoub** [comment] 2022-05-13 11:33
This is by design. `/test/1234` is a valid full path on Linux.

**Comment by glitch100** [comment] 2022-05-13 11:37
Yea I realize that, but I guess it just feels odd from the context of our use case where it's for a web request and we are constructing a `HttpRequestMessage` where the Client that will be used has a Base Url provided. I just thought there wouldn't be different behavior per platform on something like this

**Comment by stephentoub** [comment] 2022-05-13 11:59
Thanks. If we had it to do over, I expect Uri wouldn't allow file paths. But once it does, it needs to work with file paths for whatever OS you're on, at which point the difference is just surfacing the existing platform difference that's already there.

**Comment by MihaZupan** [comment] 2022-05-13 15:56
Closing as this is (unfortunately) by design.

We're introducing a new API in .NET 7 (if we get around to implementing it 😄) that will let you very explicitly opt-out of file paths: #59099
```c#
new Uri("/foo", new UriCreationOptions { AllowImplicitFilePaths = false });
```

**Closed by MihaZupan** 2022-05-13 15:56 UTC
Labels: area-System.Net, untriaged
