### ISSUE TITLE
Avoid copy of buffer in implementation of JsonSerializer.ReadValue

### ISSUE THREAD

**Issue by steveharter** [dotnet/runtime#29952] opened 2019-06-19 13:34 UTC
The implementation of `JsonSerializer.ReadValue` makes an [unnecessary copy of the buffer and has unnecessary processing](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fcorefx%2Fpull%2F38088%23discussion_r289494963&data=02%7C01%7CSteve.Harter%40microsoft.com%7Cc7214f0ab8a74c70223008d6f469483e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636965130348037357&sdata=aHXnbclS4ChAhARJDLgOH%2Fuy6CYVmXJDedkvtiTNoDk%3D&reserved=0) and should be fixed to call into the normal serialization loop.

**Comment by eiriktsarpalis** [comment] 2022-07-29 17:06
Duplicate of #70902. Closing since the other issue links to a more up-to-date version of the code.

**Closed by eiriktsarpalis** 2022-07-29 17:06 UTC
Labels: area-System.Text.Json, tenet-performance, backlog-cleanup-candidate
