### ISSUE TITLE
Configuration binder don't bind properties in some cases

### ISSUE THREAD

**Issue by piotrkantorowicz** [dotnet/runtime#101278] opened 2024-04-19 05:01 UTC
### Description

Hello!

I have a problem with binding properties from appsetting.json to object.

### Reproduction Steps

Use this pieces of code to retrieve values from .appsettins.json:

```
public class ApplicationSettings
{
    public string? Name { get; set; }
    
    public ApplicationType? Type { get; set; }
    
    public string? Description { get; set; }
}

public enum ApplicationType
{
    None = 0,
    Crud
}
```

``` 
  "App": {
    "Name": "ExampleApp",
    "Type:": "Crud",
    "Description": "Example description."
  }
```

```
ApplicationSettings applicationSettings = new();
builder.Configuration.Bind("App", applicationSettings);
```

### Expected behavior

Configuration binder should bind correct value from appsettings.json

### Actual behavior

I got always **Type** property set to **None** but It should be **Crud**. 

Another thing is when I change the type of this property eg. to string:

```
public class ApplicationSettings
{
    public string? Name { get; set; }
    
    public string? Type { get; set; }
    
    public string? Description { get; set; }
}
```

then I have got an exception:

> System.InvalidOperationException: Cannot create instance of type 'System.String' because it has multiple public parameterized constructors.
   at Microsoft.Extensions.Configuration.ConfigurationBinder.CreateInstance(Type type, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, BindingPoint bindingPoint, IConfiguration config, BinderOptions options, Boolean isParentCollection)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperties(Object instance, IConfiguration configuration, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, BindingPoint bindingPoint, IConfiguration config, BinderOptions options, Boolean isParentCollection)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Bind(IConfiguration configuration, Object instance, Action`1 configureOptions)

### Known Workarounds

I tried use GetSection and GetValue with no success.
For example - ` var applicationType = builder.Configuration.GetSection("App").GetValue<ApplicationType>("Type");`

### Configuration

.NET version - 8.0.204
OS - Windows 11, x64
Microsoft.Extensions.Configuration.Binder - implicty installed in v8.0.0

.csproj configuration:

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.2">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.2"/>
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="6.5.0"/>
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="6.5.0"/>
        <PackageReference Include="WolverineFx" Version="2.2.0"/>
        <PackageReference Include="WolverineFx.FluentValidation" Version="2.2.0"/>

    </ItemGroup>

**Comment by tarekgh** [comment] 2024-04-19 18:47
The problem is you have in the json file ` "Type:": "Crud",`. remove the colon ` "Type": "Crud",` and that should work. I am closing the issue but feel free to send any question if you have any.

**Closed by tarekgh** 2024-04-19 18:47 UTC
Labels: untriaged, area-Extensions-Configuration

**Comment by piotrkantorowicz** [comment] 2024-04-20 03:32
@tarekgh For sure it is, sorry for that...
