### ISSUE TITLE
ILC compiler failure with SynchronizationLockException in CI

### ISSUE THREAD

**Issue by vitek-karas** [dotnet/runtime#108590] opened 2024-10-07 10:31 UTC
Occurred in https://dev.azure.com/dnceng-public/public/_build/results?buildId=827048&view=results.

```
    Unhandled exception: System.AggregateException: One or more errors occurred. (Object synchronization method was called from an unsynchronized block of code.)
     ---> System.Threading.SynchronizationLockException: Object synchronization method was called from an unsynchronized block of code.
       at System.Threading.ObjectHeader.Release(Object) + 0x14a
       at System.Threading.Monitor.Exit(Object) + 0x17
       at System.Resources.ResourceReader.AllocateStringForNameIndex(Int32, Int32&) + 0x6a1
       at System.Resources.ResourceReader.ResourceEnumerator.get_Key() + 0xeb
       at ILCompiler.SubstitutionProvider.AssemblyFeatureInfo..ctor(EcmaModule, Logger, IReadOnlyDictionary`2, BodyAndFieldSubstitutions) + 0x5af
       at ILCompiler.SubstitutionProvider.FeatureSwitchHashtable.CreateValueFromKey(EcmaModule) + 0x5a
       at Internal.TypeSystem.LockFreeReaderHashtable`2.CreateValueAndEnsureValueIsInTable(TKey) + 0x3b
       at Internal.TypeSystem.LockFreeReaderHashtable`2.GetOrCreateValue(TKey) + 0x62
```

**Comment by jkotas** [comment] 2024-10-07 11:40
Duplicate of https://github.com/dotnet/runtime/issues/104340

We need to update SDK to .NET 9 RC2 to pick up the fix.

**Closed** 2024-10-07 13:16 UTC
Labels: untriaged, area-NativeAOT-coreclr
