### ISSUE TITLE
AV x64 dotnet.exe on windows arm64

### ISSUE THREAD

**Issue by MarcoRossignoli** [dotnet/runtime#72284] opened 2022-07-15 19:23 UTC
### Description

Full description inside the [item](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1576188)

**Comment by MarcoRossignoli** [comment] 2022-07-15 19:25
cc : @jkotas

**Comment by jkotas** [comment] 2022-07-15 20:21
Potentially related to https://github.com/dotnet/runtime/issues/64884

**Comment by mangod9** [comment] 2022-07-15 20:41
assume this is a dupe of https://github.com/dotnet/runtime/issues/71856. @janvorli is looking into it.

**Comment by mangod9** [comment] 2022-08-05 22:45
the related https://github.com/dotnet/runtime/issues/71856 is closed. Please validate on latest rc1 builds.

**Closed by mangod9** 2022-08-05 22:45 UTC
Labels: arch-arm64, area-GC-coreclr
