### ISSUE TITLE
[5.0.100-rc.2.20464.10] Single File launch failed for MultiRPC app after retarget .NET5

### ISSUE THREAD

**Issue by jiangzeng01** [dotnet/runtime#42363] opened 2020-09-17 02:57 UTC
**Application Name:** MultiRPC
**OS:** Windows 10 RS5
**CPU:** X64
**.NET Build Number:** 5.0.100-rc.2.20464.10
**App Location:** \\appcompatsrv\Appcompat\DotNetCore\AppSource\SingleFileP0AppsTarget5\Apps\MultiRPC
**App Source:**  \\appcompatsrv\Appcompat\DotNetCore\AppSource\SingleFileP0AppsTarget5\AppSources\MultiRPC
**DevDiv bug:** [https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1215391](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1215391)

**Repro steps:**
Target .NET5
Single File exe was created by
dotnet publish MultiRPCCore.csproj -r win-x64 -p:PublishSingleFile=true --self-contained true
using 5.0.100-rc.2.20464.10 SDK

Copy '\\appcompatsrv\Appcompat\DotNetCore\AppSource\SingleFileP0AppsTarget5\Apps\MultiRPC' to local machine.
Double-click on MultiRPC.exe

**Expected Result:**
Open MultiRPC successful.

**Actual Result:**
The MultiRPC cannot be launched successful.

**Findings :**
The Self-contained and Framework-Dependency app can be launched. Only the Single file unable to launch.

**Exception from Event View :**
```
Application: MultiRPC.exe
CoreCLR Version: 5.0.20.46205
.NET Version: 5.0.0-rc.2.20462.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Windows.Markup.XamlParseException: 'Set property 'System.Windows.ResourceDictionary.Source' threw an exception.' Line number '9' and line position '18'.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'baseUri')
   at System.Uri..ctor(Uri baseUri, String relativeUri)
   at MS.Internal.AppModel.ContentFilePart.GetStreamCore(FileMode mode, FileAccess access)
   at System.IO.Packaging.PackagePart.GetStream(FileMode mode, FileAccess access)
   at MS.Internal.IO.Packaging.PackagePartExtensions.GetSeekableStream(PackagePart packPart, FileMode mode, FileAccess access)
   at System.IO.Packaging.PackWebResponse.CachedResponse.GetResponseStream()
   at System.IO.Packaging.PackWebResponse.GetResponseStream()
   at System.IO.Packaging.PackWebResponse.get_ContentType()
   at MS.Internal.WpfWebRequestHelper.GetContentType(WebResponse response)
   at MS.Internal.WpfWebRequestHelper.GetResponseStream(WebRequest request, ContentType& contentType)
   at System.Windows.ResourceDictionary.set_Source(Uri value)
   at System.Windows.Baml2006.WpfSharedBamlSchemaContext.<>c.<Create_BamlProperty_ResourceDictionary_Source>b__342_0(Object target, Object value)
   at System.Windows.Baml2006.WpfKnownMemberInvoker.SetValue(Object instance, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(XamlMember member, Object obj, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at MultiRPC.App.InitializeComponent()
   at MultiRPC.App.Main()
```

cc @dotnet-actwx-bot

**Comment by jiangzeng01** [comment] 2020-09-17 02:58
There is another issue for this app when target default 3.x.
Which is different with this issue:
[https://github.com/dotnet/runtime/issues/41091](https://github.com/dotnet/runtime/issues/41091)

**Comment by LakshanF** [comment] 2020-09-17 23:20
This issue is also by design for SingleFile.

As shown in the exception stack above, (at System.Uri..ctor(Uri baseUri, String relativeUri)), 

the baseUri parameter is null due to Assembly.Codebase being called to create a Uri which we throw in SingleFile [here](https://github.com/dotnet/runtime/blob/527f9ae88a0ee216b44d556f9bdc84037fe0ebda/src/coreclr/src/System.Private.CoreLib/src/System/Reflection/RuntimeAssembly.cs#L93-L94).  The Uri file is created at ContentFilePart [here](https://github.com/dotnet/wpf/blob/922458cd0094773d463a42afe94b869aa47bf82e/src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/ContentFilePart.cs#L76).

**Comment by Sewer56** [comment] 2020-09-21 23:03
Seems to be a duplicate of https://github.com/dotnet/wpf/issues/3516

**Comment by VSadov** [comment] 2021-07-22 20:21
Yes, this is a duplicate of https://github.com/dotnet/wpf/issues/3516

**Closed by VSadov** 2021-07-22 20:21 UTC
Labels: area-Single-File
