### ISSUE TITLE
DictionaryKeyPolicy ignored when serializing dictionaries with non-string keys

### ISSUE THREAD

**Issue by ramondeklein** [dotnet/runtime#48069] opened 2021-02-09 18:53 UTC
Issue #31849 describes that the `DictionaryKeyPolicy` wasn't working for the first level properties in a dictionary. This now works in .NET Core 5.0 for dictionaries with string-based keys. .NET Core 5 also added serialization of dictionaries with non-string keys. But when using such dictionaries, the `DictionaryKeyPolicy` is ignored.

I have created two unit tests that illustrate this issue:
```
using System.Collections.Generic;
using System.Text.Json;
using Microsoft.VisualStudio.TestTools.UnitTesting;

[TestClass]
public class DictionaryKeyPolicyTests
{
    public enum ObjectType
    {
        Value,
        Class
    }

    private static readonly JsonSerializerOptions JsonSerializerOptions = new JsonSerializerOptions
    {
        DictionaryKeyPolicy = JsonNamingPolicy.CamelCase
    };

    [TestMethod]
    public void TestStringDictionarySerialization()
    {
        var obj = new Dictionary<string, string>
        {
            {"Value", "Value"},
            {"Class", "Class"}
        };
        var json = JsonSerializer.Serialize(obj, JsonSerializerOptions);
        Assert.AreEqual("{\"value\":\"Value\",\"class\":\"Class\"}", json);
    }

    [TestMethod]
    public void TestEnumDictionarySerialization()
    {
        var obj = new Dictionary<ObjectType, string>
        {
            {ObjectType.Value, "Device"},
            {ObjectType.Class, "Class"}
        };
        var json = JsonSerializer.Serialize(obj, JsonSerializerOptions);
        // fails, because DictionaryKeyPolicy isn't used
        Assert.AreEqual("{\"value\":\"Device\",\"class\":\"Class\"}", json);
    }
}
```
I would expect that this would be serialized as `{"value": "Value","class": "Class"}`, but it serializes as `{"Value": "Value","Class": "Class"}` instead.

**Comment by eiriktsarpalis** [comment] 2021-02-10 16:37
@layomia might have an opinion on this. Looks related to https://github.com/dotnet/runtime/issues/47765?

**Comment by eiriktsarpalis** [comment] 2021-02-10 16:38
Actually it is a duplicate of #47765. Closing.

**Closed by eiriktsarpalis** 2021-02-10 16:38 UTC
Labels: area-System.Text.Json, untriaged
