### ISSUE TITLE
[wasm] `System.Net.Http.Functional.Tests` *AOT* timing out, even though the tests ran to completion

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#85676] opened 2023-05-02 19:21 UTC
Running with *chrome*, helix log suggests that it timed out:
```
Console log: 'WasmTestOnBrowser-System.Net.Http.Functional.Tests' from job a205073e-a02c-4539-ab3a-883da3077f57 (windows.amd64.server2022.open.rt) using docker image mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-ltsc2022-helix-webassembly-net8-20230327150108-4404b5c on a00BG9N
running %HELIX_CORRELATION_PAYLOAD%\scripts\96680fc6a2344048be059f82f0e29c6c\execute.cmd in C:\h\w\A5530909\w\99110838\e max 4800 seconds
```

But looking at the log files uploaded from the run, `wasm-console.log` shows:

```
...
Finished:    System.Net.Http.Functional.Tests.dll

=== TEST EXECUTION SUMMARY ===
Total: 757, Errors: 0, Failed: 2, Skipped: 76, Time: 17.7430999s

Finished writing 385909 bytes of RESULTXML
Xml file was written to the provided writer.
Tests run: 757 Passed: 679 Inconclusive: 0 Failed: 2 Ignored: 0 Skipped: 76
test-main.js exiting WasmTestRunner.dll System.Net.Http.Functional.Tests.dll with result 1
{"name":"ExitStatus","message":"Program terminated with exit(1)","status":1}
WASM EXIT 1
```

Did xharness not register the exit? The chrome log has the following at the end:
```
[1683022723.209][INFO]: [7838563e7d9073c425871f308d4dae9e] COMMAND Quit {
}
[1683022723.220][INFO]: [7838563e7d9073c425871f308d4dae9e] RESPONSE Quit
[1683022723.220][DEBUG]: Log type 'driver' lost 0 entries on destruction
[1683022723.220][DEBUG]: Log type 'browser' lost 0 entries on destruction
```

.. which suggests that the session was closed.

This is hit regularly. Last [rolling build failure](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-a205073ea02c4539ab/WasmTestOnBrowser-System.Net.Http.Functional.Tests/1/console.383ccb8e.log?helixlogtype=result	https://dev.azure.com/dnceng-public/public/_build/results?buildId=258971).

It is also hiding two actual test failures:

```
[FAIL] System.Net.Http.Functional.Tests.TelemetryTest_Http20.EventSource_ExistsWithCorrectId
Assert.Equal() Failure
          ↓ (pos 0)
Expected: System.Net.Http
Actual:   HttpTelemetry
          ↑ (pos 0)
   at System.Net.Http.Functional.Tests.TelemetryTest.EventSource_ExistsWithCorrectId()
   at System.Reflection.MethodInvoker.Invoke(Object , IntPtr* , BindingFlags )
```

```
 [FAIL] System.Net.Http.Functional.Tests.TelemetryTest_Http11.EventSource_ExistsWithCorrectId
Assert.Equal() Failure
          ↓ (pos 0)
Expected: System.Net.Http
Actual:   HttpTelemetry
          ↑ (pos 0)
   at System.Net.Http.Functional.Tests.TelemetryTest.EventSource_ExistsWithCorrectId()
   at System.Reflection.MethodInvoker.Invoke(Object , IntPtr* , BindingFlags )
```

cc @pavelsavara @maraf

**Comment by radical** [comment] 2023-05-02 19:59
Looking at the `run.py` log as suggested in https://github.com/dotnet/arcade/issues/13345#issuecomment-1527647482:

`2023-05-02T10:19:06.012Z	ERROR  	executor(733)	_execute_command_in_container	Exception: 'charmap' codec can't encode character '\u2193' in position 63837: character maps to <undefined>`

And `\u2193` maps to the downward arrow character, which shows up in the failing tests. So maybe if the tests are passing, or are disabled then the whole thing will complete.

It needs to be fixed separately though anyway - https://github.com/dotnet/arcade/issues/13345.

**Comment by radical** [comment] 2023-05-02 20:11
The failing tests are disabled on browser - https://github.com/dotnet/runtime/issues/71877 .

**Comment by pavelsavara** [comment] 2023-07-26 12:49
Closing as duplicate of https://github.com/dotnet/runtime/issues/71877 which also has `[ActiveIssue]` in code.

**Closed by pavelsavara** 2023-07-26 12:49 UTC
Labels: arch-wasm, area-Infrastructure-mono
