### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by rmszc81** [dotnet/runtime#44702] opened 2020-11-15 15:45 UTC
Hello guys,
Is there any plans to release .net 5 on freebsd?

There's some useful links on internet on how to build from sources and I succeeded following the tutorials that I found but still, it's not officially supported from Microsoft.

And, is there any way that we can contribute to make it happen?

Thanks.

**Comment by jkotas** [comment] 2020-11-15 17:27
We do not have plans to have official Microsoft support for FreeBSD in .NET 5.

You can follow the discussion in https://github.com/dotnet/runtime/issues/14537. The current plan is to produce FreeBSD packages as experimental in dotnet/runtimelab repo.

cc @wfurt 

Closing as duplicate of #14537

**Closed by jkotas** 2020-11-15 17:27 UTC
Labels: untriaged
