### ISSUE TITLE
System.Text.Json DictionaryKeyPolicy not respected during serialization when the dictionary value is a List

### ISSUE THREAD

**Issue by eldon111** [dotnet/runtime#52110] opened 2021-04-30 15:20 UTC
### Description
When using JsonSerializerOptions to specify CamelCase for dictionary keys, that option is ignored when the dictionary value is a List.

Example code to reproduce:
```
JsonSerializerOptions jsonSerializerOptions = new JsonSerializerOptions
{
    DictionaryKeyPolicy = JsonNamingPolicy.CamelCase,
};
var dict1 = new Dictionary<string, List<string>>
{
    {"KeyOne", new List<string> {"Value1", "Value2"}},
};
var dict2 = new Dictionary<string, string>
{
    {"KeyTwo", "Value"},
};

// {"KeyOne":["Value1","Value2"]}
var result1 = JsonSerializer.Serialize(dict1, jsonSerializerOptions);

// {"keyTwo":"Value"}
var result2 = JsonSerializer.Serialize(dict2, jsonSerializerOptions);
```

### Configuration
.NET 5.0.100
macOS Catalina 10.15.7
x64

**Comment by eiriktsarpalis** [comment] 2021-05-04 10:24
I can't reproduce the issue using sdk version 5.0.202. Have you tried running it with a more recent version? cc @layomia who might know if this is a bug we fixed in servicing.

**Comment by eiriktsarpalis** [comment] 2021-07-21 16:04
Issue has stagnated for a while, closing. Feel free to reopen whenever you find the time to revisit.

**Closed by eiriktsarpalis** 2021-07-21 16:04 UTC
Labels: area-System.Text.Json, needs more info, untriaged
