### ISSUE TITLE
Microsoft.Extensions.FileSystemGlobbing.Matcher matches no file in Docker

### ISSUE THREAD

**Issue by Davee02** [dotnet/runtime#49645] opened 2021-03-15 13:32 UTC
### Description

I'm investigating an issue that only appears when running the application in Docker with .Net 5. The code works as intended when running it on a windows or in WSL2 (with debug & release configuration).

When I'm running the following snippet, I expect the assertion succeeds (which it does when running it in a non-dockeriued environment). When running the docker image, the assertion fails.

```csharp
using System;
using System.Diagnostics;
using Microsoft.Extensions.FileSystemGlobbing;

namespace DaHo.FileSystemGlobbing.Repro
{
    class Program
    {
        static void Main(string[] args)
        {
            var matcher = new Matcher();

            matcher.AddInclude("file.txt");

            var matchResult = matcher.Match("file.txt");

            Trace.Assert(matchResult.HasMatches);

            Console.WriteLine("Assertion successful");
        }
    }
}
```

I created [a short reproduction with instructions](https://github.com/Davee02/DaHo.FileSystemGlobbing.Repr). I was able to reproduce the issue on my work computer and my private notebook.

### Configuration

Running `dotnet --info` on the windows host machine returns the following:

```
.NET SDK (reflecting any global.json):
 Version:   5.0.200
 Commit:    70b3e65d53

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.200\

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  2.1.804 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]
  3.1.302 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  3.1.403 [C:\Program Files\dotnet\sdk]
  3.1.406 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Running `docker info`:

```
Client:
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 25
  Running: 2
  Paused: 0
  Stopped: 23
 Images: 76
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: error
  NodeID:
  Error: error while loading TLS certificate in /var/lib/docker/swarm/certificates/swarm-node.crt: certificate (1 - xxufo3bdpqy9208ngvhzuli26) not valid after Sun, 17 Jan 2021 05:03:00 UTC, and it is currently Mon, 01 Mar 2021 08:13:34 UTC: x509: certificate has expired or is not yet valid
  Is Manager: false
  Node Address: 192.168.65.3
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.128-microsoft-standard
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 5
 Total Memory: 7.773GiB
 Name: docker-desktop
 ID: 7LXF:JIBR:V4JD:V4FA:6JKI:WR4W:HW7G:VBC3:6UME:QPTY:4DQ2:324L
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio weight support
WARNING: No blkio weight_device support
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Comment by thierryrama** [comment] 2023-03-12 20:00
This is still an issue in dotnet 7.

**Comment by danmoseley** [comment] 2023-03-13 02:57
@richlander  any idea here, from a container oriented perspective?

**Comment by Jozkee** [comment] 2023-03-14 05:38
This is related to the CWD, you can repro without Docker if you run the exe from the root directory. I still don't know the root cause, though.

**Comment by Jozkee** [comment] 2023-03-15 16:45
> This is still an issue in dotnet 7.

@thierryrama can you please verify in your csproj that your FileSystemGlobbing package version is >= 6.0
Look for something like this:
```csproj
<PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" Version="6.0.0" />
```

As I said earlier, I was able to repro the issue without docker, and then realized that by bumping to net7.0, this was still repro'ing but then I realized FileSystemGlobbing was an OOB package. Bumping it from 5.0 to 6.0 solved the issue on my repro.

I'm very certain that this was fixed by https://github.com/dotnet/runtime/pull/45139 in the 6.0 timeframe.

**Closed** 2023-04-13 00:01 UTC
Labels: area-Extensions-FileSystem, no-recent-activity, needs-author-action
