### ISSUE TITLE
IsAssignableFrom isn't working with generic interfaces and classes

### ISSUE THREAD

**Issue by virzak** [dotnet/runtime#83858] opened 2023-03-23 22:36 UTC
### Description

IsAssignableFrom isn't working with interfaces and classes. This is not a problem with non-generic interfaces

### Reproduction Steps

```cs
Console.WriteLine(typeof(IParsable<>).IsAssignableFrom(typeof(double)));  // true
Console.WriteLine(typeof(IParsable<>).IsAssignableFrom(typeof(MyStruct))); // true
Console.WriteLine(typeof(IParsable<>).IsAssignableFrom(typeof(MyClass))); // false???

Console.WriteLine(typeof(IComparable).IsAssignableFrom(typeof(MyStruct))); // true
Console.WriteLine(typeof(IComparable).IsAssignableFrom(typeof(MyClass))); // true

class MyClass : IParsable<MyClass>, IComparable {
    public static MyClass Parse(string s, IFormatProvider? provider) => throw new NotImplementedException();
    public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, [MaybeNullWhen(false)] out MyClass result) => throw new NotImplementedException();
    public int CompareTo(object? obj) => throw new NotImplementedException();
}

struct MyStruct : IParsable<MyStruct>, IComparable {
    public static MyStruct Parse(string s, IFormatProvider? provider) => throw new NotImplementedException();
    public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, [MaybeNullWhen(false)] out MyStruct result) => throw new NotImplementedException();
    public int CompareTo(object? obj) => throw new NotImplementedException();
}
```

### Expected behavior

Expecting everything to return true

### Actual behavior

Class implementation returns false

**Comment by Wraith2** [comment] 2023-03-24 00:19
`typeof(IParsable<>)` is the open generic type and `MyClass` does not implement it, nothing would pass this test. `MyClass` implements the closed `typeof(IParsable<MyClass>)`

**Comment by virzak** [comment] 2023-03-24 00:22
Why MyStruct works then?

**Comment by jkotas** [comment] 2023-03-24 02:12
The behavior that you are seeing is a bug #78619 that was fixed for .NET 8.

The correct answer is:
```
False
False
False
True
True
```
Uninstantiated generics are not AssignableTo.

Duplicate of #78619

**Closed by jkotas** 2023-03-24 02:12 UTC
Labels: area-TypeSystem-coreclr, untriaged
