### ISSUE TITLE
System.Text.Json Serialization issue when constructor has ReadOnlySpan<char> parameter

### ISSUE THREAD

**Issue by kepar** [dotnet/runtime#48827] opened 2021-02-26 17:11 UTC
When trying to serialize an object with a ReadOnlySpan<char> parameter in the constructor, I get an Unhandled exception. of type **System.TypeLoadException** with the message: The generic type 'System.Text.Json.Serialization.Converters.SmallObjectWithParameterizedConstructorConverter`5' was used with an invalid instantiation in assembly 'System.Text.Json, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

I'm using .Net 5 with "System.Text.Json" Version="5.0.1"

This problem can be reproduced with this code: https://dotnetfiddle.net/edSoUp
copied here for reference:

```C#
using System;

var typeWithString = new TypeWithString("foo");
var typewithSpan = new TypeWithSpan("bar");

var working =  System.Text.Json.JsonSerializer.Serialize(typeWithString);

Console.WriteLine(working);

var json = System.Text.Json.JsonSerializer.Serialize(typewithSpan);

Console.WriteLine(json);


class TypeWithSpan
{ 
    public TypeWithSpan(ReadOnlySpan<char> value)
    {
		FirstLetter = value.Slice(0,1).ToString();
    }
	
	public string FirstLetter {get; }
}

class TypeWithString
{
    public TypeWithString(string value)
    {
        FirstLetter = value.Substring(0, 1);
    }

    public string FirstLetter { get; }
}
```

The serialization of the type TypeWithString works as expected, the serialization of the type TypeWithSpan fails with :
Unhandled exception. System.TypeLoadException: The generic type 'System.Text.Json.Serialization.Converters.SmallObjectWithParameterizedConstructorConverter`5' was used with an invalid instantiation in assembly 'System.Text.Json, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at System.RuntimeTypeHandle.Instantiate(Type[] inst)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at System.Text.Json.Serialization.Converters.ObjectConverterFactory.CreateConverter(Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverterFactory.GetConverterInternal(Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetConverter(Type typeToConvert)
   at System.Text.Json.JsonSerializerOptions.DetermineConverter(Type parentClassType, Type runtimePropertyType, MemberInfo memberInfo)
   at System.Text.Json.JsonClassInfo.GetConverter(Type type, Type parentClassType, MemberInfo memberInfo, Type& runtimeType, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type type)
   at System.Text.Json.JsonSerializerOptions.GetOrAddClassForRootType(Type type)
   at System.Text.Json.WriteStack.Initialize(Type type, JsonSerializerOptions options, Boolean supportContinuation)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, Type inputType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue& value, Type inputType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at <Program>$.<Main>$(String[] args)

**Comment by eiriktsarpalis** [comment] 2021-03-29 16:37
Duplicate of https://github.com/dotnet/runtime/issues/44327. Thanks for reporting the issue.

**Closed by eiriktsarpalis** 2021-03-29 16:37 UTC
Labels: area-System.Text.Json, untriaged
