### ISSUE TITLE
Proposal: AppContext.SetData

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#47922] opened 2021-02-05 18:14 UTC
## Background and Motivation

Right now `AppContext` only exposes the following APIs:

- GetData
- SetSwitch
- TryGetSwitch

And the fact that a corresponding `SetData` method is missing is a bit confusing. You currently need to set data through `AppDomain.SetData`, even though you can then retrieve it through `AppContext`, as that data flows to `AppContext` anyway.

This proposal is to add the "missing" `SetData` API to `AppContext` to bring it on par with `AppDomain`.
This would also be more intuitive to use for consumers (eg. personally I was quite puzzled at first when I saw code in https://github.com/terrafx using `AppContext.GetData` in a few places, but with no `AppContext.SetData` in sight).

**EDIT:** looks like the API is actually... Already there?

https://github.com/dotnet/runtime/blob/8a52f1e948b6f22f418817ec1068f07b8dae2aa5/src/libraries/System.Private.CoreLib/src/System/AppContext.cs#L48

But it's not listed in the API docs, and I can't access it from IntelliSense.
It seems it's not present in the ref assemblies - was this just missed or was it intentional?

## Proposed API

```diff
namespace System
{
    public static partial class AppContext
    {
+        public static void SetData(string name, object? data);
    }
}
```

**Comment by tannergooding** [comment] 2021-06-26 14:26
CC. @jkotas, just wanting to confirm that there isn't an intentional reason behind this not being exposed.

**Comment by jkotas** [comment] 2021-06-26 14:39
AppContext.GetData and friends were introduced in .NET Core 1.0 as a replacement for AppDomain.GetData. When AppDomain type came back as part of .NET Standard 2.0, we lost the motivation to make this complete: https://github.com/dotnet/runtime/issues/18887#issuecomment-323844481

AppContext.SetData would be duplicate of AppDomain.SetData. If you would like to expose it for completeness, feel free to.

**Comment by tannergooding** [comment] 2021-06-26 14:50
> AppContext.SetData would be duplicate of AppDomain.SetData. If you would like to expose it for completeness, feel free to.

Yes, I think it will be good to expose for completeness however. Many things on AppDomain aren't exposed or don't work and its largely a "legacy" type on .NET Core. Having the method exposed where users can find it and the related `GetData` makes sense to me and avoids users needing to understand the relationship between AppContext and AppDomain.

**Comment by bartonjs** [comment] 2021-08-17 18:45
Looks good as proposed, for symmetry.

```C#
namespace System
{
    public static partial class AppContext
    {
        public static void SetData(string name, object? data);
    }
}
```

**Comment by GrabYourPitchforks** [comment] 2021-08-17 18:46
We should doc both for this and for `SetSwitch` that they're intended to be set very early in the app's startup routine. Other components of the base libraries or the application might read and cache these values, and if you call `SetData` / `SetSwitch` after this caching has taken place your changes won't be honored.

**Comment by deeprobin** [comment] 2021-12-19 18:33
Feel free to assign me :smile:

**Closed** 2021-12-21 14:55 UTC
Labels: api-approved, area-System.Runtime
