### ISSUE TITLE
Linux: Could not load file or assembly 'Microsoft.Extension.Hosting.Abstractions' Aborted(core dumped)

### ISSUE THREAD

**Issue by arvindrajachourasiya** [dotnet/runtime#36880] opened 2020-05-22 15:25 UTC
Error:
Unhandeled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extension.Hosting.Abstractions, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

File name: 'Microsoft.Extension.Hosting.Abstructions, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

Aborted(core dumped)

### Description

I am creating `Worker Service` using .Net Core. I have installed it using `Terminal `in Linux virtual machine(Ubuntu 64 bit) but service didn't get installed properly.
When I run command  `dotnet /home/linux/Downloads/CreateHwService.dll` getting above error.
My project's package have '`Microsoft.Extension.Hosting.Abstructions(3.1.3)` library.

How can I solve this?

This is my .csproj file(not complete)

```
<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UserSecretsId>dotnet-L3WorkerService-2E903376-1574-483D-80CC-4BDD7</UserSecretsId>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="3.1.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="3.1.3" />
  </ItemGroup>
</Project>

```
Expected Behavior
Given command should be execute successfully and service should start working.

Actual Behavior
`dotnet /` command throwing exception.

Dotnet version-  dotnetcore 3.1
Ubuntu version- Ubuntu 18.04.4

### Regression?
This is the first time I am developing.

**Comment by vcsjones** [comment] 2020-05-22 16:11
Somewhere in one of your project files there is a typo it seems, "Microsoft.Extension.Hosting.Abstructions" should be "Microsoft.Extension.Hosting.Abstr***a***ctions".

**Comment by arvindrajachourasiya** [comment] 2020-05-22 16:16
@vcsjones - oh sorry. This is because I got error in Virtual machine, from there I have manually typed that message here. That why typo. Thank you.

**Comment by maryamariyan** [comment] 2020-07-16 20:24
closing as dupe of https://github.com/dotnet/runtime/issues/37356

**Closed by maryamariyan** 2020-07-16 20:24 UTC
Labels: area-Extensions-Hosting
