### ISSUE TITLE
String.ToUpper with Turkish CultureInfo doesn't work on Android

### ISSUE THREAD

**Issue by kpetryla** [dotnet/runtime#102622] opened 2024-05-23 05:23 UTC
### Description

In Turkish, there are two I (dotless: ı, I and dotted: i, İ) Every time on Android  after  uppercase with CultureInfo an i, I get an I. On iOS everything works correctly.
<img width="411" alt="and" src="https://github.com/dotnet/maui/assets/15184713/d49adefc-1719-4b1c-9e99-d05d421b0038">
![ios](https://github.com/dotnet/maui/assets/15184713/4ef185c3-2682-4893-9b30-eb5015e5e40a)

### Steps to Reproduce

1. Create string with "I" in it like in example "indigo"
2. Use method to upper case with Turkish CultureInfo (str1.ToUpper(new CultureInfo("tr-TR", false))
3. result is INDIGO instead İNDİGO

### Link to public reproduction project repository

https://github.com/kpetryla/String.ToUpper/tree/main/TurkishUpperCase

### Version with bug

8.0.21 SR4.1

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Affected platform versions

Android 14, Android 13

**Comment by tarekgh** [comment] 2024-05-23 19:12
@vitek-karas @mkhamoyan

**Comment by vitek-karas** [comment] 2024-05-24 07:31
@matouskozak could you please take a quick look - at least to tell if this is coming from the OS or from our code.

**Comment by mkhamoyan** [comment] 2024-05-24 13:20
We are relying on Android ICU. It was previously discussed here https://github.com/dotnet/runtime/issues/77689

**Comment by matouskozak** [comment] 2024-05-27 11:19
Closing as duplicate of https://github.com/dotnet/runtime/issues/77689

**Closed by matouskozak** 2024-05-27 11:19 UTC
Labels: area-System.Globalization, os-android, untriaged
