### ISSUE TITLE
[QUIC][8.0] System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ServerSendsTrailingHeaders_Success Stream aborted by peer (268)

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#98786] opened 2024-02-22 01:24 UTC
### Error Blob

```json
{
  "ErrorMessage": "Stream aborted by peer (268)",
  "BuildRetry": true,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Reproduction Steps

- Affected 8.0 PR: https://github.com/dotnet/runtime/pull/98444
- Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=566646
- Queue: `Libraries Test Run release coreclr linux x64 Debug`
- Job result: https://dev.azure.com/dnceng-public/public/_build/results?buildId=566646&view=logs&j=bc8f69e2-91b3-518c-84f8-466a04c1af40&t=0864dbdb-cb3f-5f82-b0b6-057b78db53e2&l=88
- Log file: https://helixre107v0xd1eu3ibi6ka.blob.core.windows.net/dotnet-runtime-refs-pull-98444-merge-9f5385aab5bf47cfb6/System.Net.Http.Functional.Tests/3/console.1fbf03c8.log?helixlogtype=result
- Output:
```
    System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ServerSendsTrailingHeaders_Success [FAIL]
      System.Net.Quic.QuicException : Stream aborted by peer (268).
      Stack Trace:
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ResettableValueTaskSource.cs(169,0): at System.Net.Quic.ResettableValueTaskSource.TryComplete(Exception exception, Boolean final)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ResettableValueTaskSource.cs(233,0): at System.Net.Quic.ResettableValueTaskSource.TrySetException(Exception exception, Boolean final)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs(559,0): at System.Net.Quic.QuicStream.HandleEventPeerReceiveAborted(_PEER_RECEIVE_ABORTED_e__Struct& data)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs(609,0): at System.Net.Quic.QuicStream.HandleStreamEvent(QUIC_STREAM_EVENT& streamEvent)
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs(640,0): at System.Net.Quic.QuicStream.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_STREAM_EVENT* streamEvent)
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ResettableValueTaskSource.cs(279,0): at System.Net.Quic.ResettableValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
        /_/src/libraries/Common/tests/System/Net/Http/Http3LoopbackStream.cs(165,0): at System.Net.Test.Common.Http3LoopbackStream.SendFrameAsync(Int64 frameType, ReadOnlyMemory`1 framePayload)
        /_/src/libraries/Common/tests/System/Net/Http/Http3LoopbackStream.cs(120,0): at System.Net.Test.Common.Http3LoopbackStream.SendHeadersFrameAsync(Nullable`1 statusCode, IEnumerable`1 headers, Boolean qpackEncodeStatus)
        /_/src/libraries/Common/tests/System/Net/Http/Http3LoopbackStream.cs(261,0): at System.Net.Test.Common.Http3LoopbackStream.SendResponseHeadersAsync(Nullable`1 statusCode, IEnumerable`1 headers)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs(1639,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.<>c__DisplayClass39_0.<<ServerSendsTrailingHeaders_Success>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs(1640,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.<>c__DisplayClass39_0.<<ServerSendsTrailingHeaders_Success>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs(1640,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.<>c__DisplayClass39_0.<<ServerSendsTrailingHeaders_Success>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(120,0): at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(90,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(55,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs(1663,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http3.ServerSendsTrailingHeaders_Success()
        --- End of stack trace from previous location ---
```

 ### Known issue validation
**Build: :mag_right:** 
**Result validation:** :warning: Validation could not be done without an Azure DevOps build URL on the issue. Please add it to the "**Build:** :mag_right:" line.
**Validation performed at:** 5/23/2024 2:56:02 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[681987](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681987)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2_IncorrectServerPreface_RequestFailsWithAppropriateHttpProtocolException](https://dev.azure.com/dnceng-public/public/_build/results?buildId=681987&view=ms.vss-test-web.build-test-results-tab&runId=16926710&resultId=209261)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|1|1|

**Comment by carlossanlop** [comment] 2024-02-22 01:25
I suspect the ErrorMessage string might be too generic, please feel free to modify it if a better suited message is found in the output.

**Comment by ManickaP** [comment] 2024-02-22 11:08
#91017 related

**Comment by AlitzelMendez** [comment] 2024-02-22 19:49
Known issues update: This issue has been affected by the issue described in: https://github.com/dotnet/dnceng/issues/2065. Since all the issues opened after 02/20 can cause the build analysis to fail, I will exclude this issue from the build analysis and add a tracking label to restore it as a known issue once this problem is resolved.

**Comment by rzikm** [comment] 2024-04-08 08:38
There are no recent hits of this issue in Kusto, last one is 3/13 on Alpine (where we run against main, so it may be caused by https://github.com/dotnet/runtime/issues/100064). I think we can close this as not actionable.

**Comment by ManickaP** [comment] 2024-05-23 14:55
Failures < 1 per month, but this has quite a bit of re-runs. Also doesn't happen on main.

**Comment by ManickaP** [comment] 2024-05-23 15:00
Dupe of #87552

**Closed by ManickaP** 2024-05-23 15:00 UTC
Labels: area-System.Net.Http, os-linux, arch-x64, blocking-clean-ci, runtime-coreclr, Known Build Error
