### ISSUE TITLE
Test failure: JIT/Regression/JitBlue/GitHub_18884/GitHub_18884/GitHub_18884.cmd

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#107892] opened 2024-09-16 21:33 UTC
pipeline: runtime-coreclr pgostress
job: coreclr windows x64 Checked syntheticpgo @ Windows.10.Amd64.Open

https://dev.azure.com/dnceng-public/public/_build/results?buildId=808493&view=ms.vss-test-web.build-test-results-tab&runId=20908620&paneView=debug&resultId=119320

```
set DOTNET_TieredCompilation=1
set DOTNET_ReadyToRun=0
set DOTNET_TC_QuickJitForLoops=1
set DOTNET_JitSynthesizeCounts=1
set DOTNET_JitCheckSynthesizedCounts=1
```

```
07:54:05.738 Running test: JIT/Regression/JitBlue/GitHub_18884/GitHub_18884/GitHub_18884.cmd

Assert failure(PID 1980 [0x000007bc], Thread: 2840 [0x0b18]): Consistency check failed: AV in clr at this callstack:
------
CORECLR! TypeHandle::Verify + 0x16 (0x00007ffc`e8353a36)
CORECLR! SigPointer::HasCustomModifier + 0x1A6 (0x00007ffc`e8301366)
CORECLR! CEEInfo::getArgType + 0xA0C (0x00007ffc`e8203dcc)
CLRJIT! Compiler::lvaInitTypeRef + 0x349 (0x00007ffc`e96706c9)
CLRJIT! Compiler::compCompileHelper + 0x319 (0x00007ffc`e953b4a9)
CLRJIT! Compiler::compCompile + 0x8F8 (0x00007ffc`e953a988)
CLRJIT! `jitNativeCode'::`8'::__Body::Run + 0xE2 (0x00007ffc`e9536942)
CLRJIT! jitNativeCode + 0x155 (0x00007ffc`e9540e25)
CLRJIT! CILJit::compileMethod + 0x169 (0x00007ffc`e9548669)
CORECLR! invokeCompileMethod + 0x203 (0x00007ffc`e8227fb3)
CORECLR! UnsafeJitFunction + 0x83B (0x00007ffc`e81fccab)
CORECLR! MethodDesc::JitCompileCodeLocked + 0x1D2 (0x00007ffc`e82d2b22)
CORECLR! MethodDesc::JitCompileCodeLockedEventWrapper + 0x50D (0x00007ffc`e82d33ad)
CORECLR! MethodDesc::JitCompileCode + 0x5A9 (0x00007ffc`e82d2849)
CORECLR! MethodDesc::PrepareILBasedCode + 0x4F2 (0x00007ffc`e82d51d2)
CORECLR! MethodDesc::PrepareCode + 0xF3 (0x00007ffc`e82d4c83)
CORECLR! MethodDesc::PrepareInitialCode + 0x132 (0x00007ffc`e82d5372)
CORECLR! MethodDesc::DoPrestub + 0xD16 (0x00007ffc`e82cda66)
CORECLR! PreStubWorker + 0x476 (0x00007ffc`e82d9f76)
-----
.AV on tid=0xb18 (2840), cxr=000000E6BED79E40, exr=000000E6BED7A330
FAILED: false

CORECLR! CHECK::Trigger + 0x1F0 (0x00007ffc`e880d170)
CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x4BB (0x00007ffc`e8181d8b)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x91 (0x00007ffc`e8181661)
CORECLR! CLRVectoredExceptionHandler + 0x76C (0x00007ffc`e81815bc)
CORECLR! CLRVectoredExceptionHandlerShim + 0x181 (0x00007ffc`e8181fe1)
NTDLL! RtlInitializeCriticalSection + 0x190 (0x00007ffd`16fc6dc0)
NTDLL! RtlImageNtHeaderEx + 0x17B (0x00007ffd`16f946cb)
NTDLL! KiUserExceptionDispatcher + 0x3A (0x00007ffd`17009caa)
CORECLR! TypeHandle::Verify + 0x16 (0x00007ffc`e8353a36)
CORECLR! SigPointer::HasCustomModifier + 0x1A6 (0x00007ffc`e8301366)
    File: D:\a\_work\1\s\src\coreclr\vm\excep.cpp:6881
    Image: C:\h\w\B2A009B8\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\B2A009B8\w\B2730973\uploads\JitBlue\GitHub_18884\GitHub_18884\output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\B2A009B8\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  GitHub_18884.dll 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
```

**Comment by v-wenyuxu** [comment] 2024-09-18 08:02
**Failed in:** [runtime-coreclr pgostress 20240913.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=808493&view=ms.vss-test-web.build-test-results-tab&runId=20908620&resultId=119320&paneView=debug)

**Failed tests:**
```
coreclr windows x64 Checked syntheticpgo @ Windows.10.Amd64.Open
    - JIT/Regression/JitBlue/GitHub_18884/GitHub_18884/GitHub_18884.cmd
```

**Error message:**
```
 
Assert failure(PID 1980 [0x000007bc], Thread: 2840 [0x0b18]): Consistency check failed: AV in clr at this callstack:
------
CORECLR! TypeHandle::Verify + 0x16 (0x00007ffc`e8353a36)
CORECLR! SigPointer::HasCustomModifier + 0x1A6 (0x00007ffc`e8301366)
CORECLR! CEEInfo::getArgType + 0xA0C (0x00007ffc`e8203dcc)
CLRJIT! Compiler::lvaInitTypeRef + 0x349 (0x00007ffc`e96706c9)
CLRJIT! Compiler::compCompileHelper + 0x319 (0x00007ffc`e953b4a9)
CLRJIT! Compiler::compCompile + 0x8F8 (0x00007ffc`e953a988)
CLRJIT! `jitNativeCode'::`8'::__Body::Run + 0xE2 (0x00007ffc`e9536942)
CLRJIT! jitNativeCode + 0x155 (0x00007ffc`e9540e25)
CLRJIT! CILJit::compileMethod + 0x169 (0x00007ffc`e9548669)
CORECLR! invokeCompileMethod + 0x203 (0x00007ffc`e8227fb3)
CORECLR! UnsafeJitFunction + 0x83B (0x00007ffc`e81fccab)
CORECLR! MethodDesc::JitCompileCodeLocked + 0x1D2 (0x00007ffc`e82d2b22)
CORECLR! MethodDesc::JitCompileCodeLockedEventWrapper + 0x50D (0x00007ffc`e82d33ad)
CORECLR! MethodDesc::JitCompileCode + 0x5A9 (0x00007ffc`e82d2849)
CORECLR! MethodDesc::PrepareILBasedCode + 0x4F2 (0x00007ffc`e82d51d2)
CORECLR! MethodDesc::PrepareCode + 0xF3 (0x00007ffc`e82d4c83)
CORECLR! MethodDesc::PrepareInitialCode + 0x132 (0x00007ffc`e82d5372)
CORECLR! MethodDesc::DoPrestub + 0xD16 (0x00007ffc`e82cda66)
CORECLR! PreStubWorker + 0x476 (0x00007ffc`e82d9f76)
-----
.AV on tid=0xb18 (2840), cxr=000000E6BED79E40, exr=000000E6BED7A330
FAILED: false

CORECLR! CHECK::Trigger + 0x1F0 (0x00007ffc`e880d170)
CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x4BB (0x00007ffc`e8181d8b)
CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x91 (0x00007ffc`e8181661)
CORECLR! CLRVectoredExceptionHandler + 0x76C (0x00007ffc`e81815bc)
CORECLR! CLRVectoredExceptionHandlerShim + 0x181 (0x00007ffc`e8181fe1)
NTDLL! RtlInitializeCriticalSection + 0x190 (0x00007ffd`16fc6dc0)
NTDLL! RtlImageNtHeaderEx + 0x17B (0x00007ffd`16f946cb)
NTDLL! KiUserExceptionDispatcher + 0x3A (0x00007ffd`17009caa)
CORECLR! TypeHandle::Verify + 0x16 (0x00007ffc`e8353a36)
CORECLR! SigPointer::HasCustomModifier + 0x1A6 (0x00007ffc`e8301366)
    File: D:_work1ssrccoreclrmexcep.cpp:6881
    Image: C:hwB2A009B8pcorerun.exe


Return code:      1
Raw output file:      C:hwB2A009B8wB2730973uploadsJitBlueGitHub_18884GitHub_18884output.txt
Raw output:
BEGIN EXECUTION
 "C:hwB2A009B8pcorerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  GitHub_18884.dll 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:cores since 9/14/2024 7:54:05 AM
Processing C:corescorerun.exe.1980.dmp
Invoking: C:Program Files (x86)Windows Kits10Debuggersdcdb.exe -c "$<C:hwB2A009B8		mpwok4sb.tmp" -z "C:corescorerun.exe.1980.dmp"
stdout: 
Microsoft (R) Windows Debugger Version 10.0.18362.1 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.


Loading Dump File [C:corescorerun.exe.1980.dmp]
User Mini Dump File with Full Memory: Only application data is available


************* Path validation summary **************
Response                         Time (ms)     Location
OK                                             C:hwB2A009B8pPDB
Symbol search path is: C:hwB2A009B8pPDB
Executable search path is: 
Windows 10 Version 14393 MP (4 procs) Free x64
Product: Server, suite: TerminalServer DataCenter SingleUserTS
10.0.14393.6343 (rs1_release.230913-1727)
Machine Name:
Debug session time: Sat Sep 14 07:54:09.000 2024 (UTC + 0:00)
System Uptime: 0 days 0:06:14.847
Process Uptime: 0 days 0:00:04.000
..........................

************* Symbol Loading Error Summary **************
Module name            Error
ntdll                  The system cannot find the file specified

You can troubleshoot most symbol related issues by turning on symbol loading diagnostics (!sym noisy) and repeating the command that caused symbols to be loaded.
You should also verify that your symbol search path (.sy
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor339|0_340(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by jkotas** [comment] 2024-10-07 12:27
Duplicate of #108586

**Closed by jkotas** 2024-10-07 12:27 UTC
Labels: os-windows, JitStress, arch-x64, area-CodeGen-coreclr
