### ISSUE TITLE
[API Proposal]: ReadOnlySequence<byte> handling by System.Text.Json source generator

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/runtime#95187] opened 2023-11-23 19:51 UTC
### Background and motivation

In .NET 8.0, System.Text.Json source generator generates code to JSON serialize `ReadOnlyMemory<byte>` values the same way as `byte[]`.

To avoid extra allocations, it would be nice to be able to JSON serialize `ReadOnlySequence<byte>` the same way.

Currently, the generator tries to write code to serialize `ReadOnlySequence<byte>`, which is not possible.

### API Proposal

```csharp
// System.Text.Json source generator code
// ...
```

### API Usage

```csharp
public class Dto
{
    public ReadOnlySequence<byte> Data { get; set; }
}

[JsonSerializable(typeof(Dto))]
public partial class Class1JsonSerializationContext : JsonSerializerContext
{
}
```

**Comment by eiriktsarpalis** [comment] 2023-11-24 10:10
It's essentially a duplicate of #67337. Once we add support for writing partial string values it should be trivial to include streaming converters for `string`, `ReadOnlyMemory<byte>` or `ReadOnlySequence<byte>`.

**Closed by eiriktsarpalis** 2023-11-24 10:10 UTC
Labels: api-suggestion, area-System.Text.Json, untriaged
