### ISSUE TITLE
Confused about unobserved exception

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#91100] opened 2023-08-25 01:55 UTC
I have a unit test that checks for unobserved exceptions. I'm confused about a situation where an exception is being reported as unobserved:

The test successfully awaits an exception thrown from `ResponseHeadersAsync`, yet that exception is still being raised by the `TaskScheduler.UnobservedTaskException` event.

The PR with the new test is here: https://github.com/grpc/grpc-dotnet/pull/2255. It also includes some fixes to suppress unobserved exceptions in some other situations. I can't figure out the one below, however.

Here is the log output:

```
 AsyncUnaryCall_CallFailed_NoUnobservedExceptions(0,False,ResponseHeadersAsync)
   Source: RetryTests.cs line 1081
   Duration: 340 ms

  Message: 
  Expected: 0
  But was:  1


  Stack Trace: 
<AsyncUnaryCall_CallFailed_NoUnobservedExceptions>d__28.MoveNext() line 1131
1)    at Grpc.Net.Client.Tests.Retry.RetryTests.<AsyncUnaryCall_CallFailed_NoUnobservedExceptions>d__28.MoveNext() in C:\Development\Source\grpc-dotnet\test\Grpc.Net.Client.Tests\Retry\RetryTests.cs:line 1131

  Standard Output: 
0.103s Grpc.Net.Client.Tests.CancellationTests - Debug: Starting call
0.132s Grpc.Net.Client.Internal.RetryCall - Trace: Starting retry worker.
0.134s Grpc.Net.Client.Internal.RetryCall - Debug: Starting attempt 1.
0.161s Grpc.Net.Client.Internal.GrpcCall - Debug: Starting gRPC call. Method type: 'Unary', URI: 'https://localhost/ServiceName/MethodName'.
0.173s Grpc.Net.Client.Internal.GrpcCall - Debug: Error starting gRPC call.
0.177s Grpc.Net.Client.Internal.GrpcCall - Information: Call failed with gRPC error status. Status code: 'Internal', Message: 'Error starting gRPC call. Exception: Test error'.
System.Exception: Test error
   at Grpc.Net.Client.Tests.Retry.RetryTests.<>c.<AsyncUnaryCall_CallFailed_NoUnobservedExceptions>b__28_1(HttpRequestMessage request) in C:\Development\Source\grpc-dotnet\test\Grpc.Net.Client.Tests\Retry\RetryTests.cs:line 1104
   at Grpc.Tests.Shared.TestHttpMessageHandler.<>c__DisplayClass2_0.<<Create>b__0>d.MoveNext() in C:\Development\Source\grpc-dotnet\test\Shared\TestHttpMessageHandler.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Grpc.Net.Client.Internal.GrpcCall`2.<RunCall>d__89.MoveNext() in C:\Development\Source\grpc-dotnet\src\Grpc.Net.Client\Internal\GrpcCall.cs:line 502
0.222s Grpc.Net.Client.Internal.GrpcCall - Debug: Finished gRPC call.
0.225s Grpc.Net.Client.Internal.GrpcCall - Debug: gRPC call canceled.
0.229s Grpc.Net.Client.Internal.RetryCall - Debug: Evaluated retry for failed gRPC call. Status code: 'Internal', Attempt: 1, Retry: False
0.231s Grpc.Net.Client.Internal.RetryCall - Debug: Call commited. Reason: FatalStatusCode
0.232s Grpc.Net.Client.Internal.RetryCall - Trace: Stopping retry worker.
0.237s Grpc.Net.Client.Tests.CancellationTests - Debug: Waiting for finalizers
0.241s Grpc.Net.Client.Tests.CancellationTests - Critical: Unobserved task exception
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. Exception: Test error", DebugException="System.Exception: Test error") ---> System.Exception: Test error
   at Grpc.Net.Client.Tests.Retry.RetryTests.<>c.<AsyncUnaryCall_CallFailed_NoUnobservedExceptions>b__28_1(HttpRequestMessage request) in C:\Development\Source\grpc-dotnet\test\Grpc.Net.Client.Tests\Retry\RetryTests.cs:line 1104
   at Grpc.Tests.Shared.TestHttpMessageHandler.<>c__DisplayClass2_0.<<Create>b__0>d.MoveNext() in C:\Development\Source\grpc-dotnet\test\Shared\TestHttpMessageHandler.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Grpc.Net.Client.Internal.GrpcCall`2.<RunCall>d__89.MoveNext() in C:\Development\Source\grpc-dotnet\src\Grpc.Net.Client\Internal\GrpcCall.cs:line 502
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Grpc.Net.Client.Internal.GrpcCall`2.<GetResponseHeadersCoreAsync>d__79.MoveNext() in C:\Development\Source\grpc-dotnet\src\Grpc.Net.Client\Internal\GrpcCall.cs:line 333
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Grpc.Net.Client.Internal.Retry.RetryCallBase`2.<GetResponseHeadersCoreAsync>d__88.MoveNext() in C:\Development\Source\grpc-dotnet\src\Grpc.Net.Client\Internal\Retry\RetryCallBase.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Grpc.Tests.Shared.ExceptionAssert.<ThrowsAsync>d__0`1.MoveNext() in C:\Development\Source\grpc-dotnet\test\Shared\ExceptionAssert.cs:line 36
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Error starting gRPC call. Exception: Test error", DebugException="System.Exception: Test error") ---> System.Exception: Test error
   at Grpc.Net.Client.Tests.Retry.RetryTests.<>c.<AsyncUnaryCall_CallFailed_NoUnobservedExceptions>b__28_1(HttpRequestMessage request) in C:\Development\Source\grpc-dotnet\test\Grpc.Net.Client.Tests\Retry\RetryTests.cs:line 1104
   at Grpc.Tests.Shared.TestHttpMessageHandler.<>c__DisplayClass2_0.<<Create>b__0>d.MoveNext() in C:\Development\Source\grpc-dotnet\test\Shared\TestHttpMessageHandler.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Grpc.Net.Client.Internal.GrpcCall`2.<RunCall>d__89.MoveNext() in C:\Development\Source\grpc-dotnet\src\Grpc.Net.Client\Internal\GrpcCall.cs:line 502
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Grpc.Net.Client.Internal.GrpcCall`2.<GetResponseHeadersCoreAsync>d__79.MoveNext() in C:\Development\Source\grpc-dotnet\src\Grpc.Net.Client\Internal\GrpcCall.cs:line 333
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Grpc.Net.Client.Internal.Retry.RetryCallBase`2.<GetResponseHeadersCoreAsync>d__88.MoveNext() in C:\Development\Source\grpc-dotnet\src\Grpc.Net.Client\Internal\Retry\RetryCallBase.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Grpc.Tests.Shared.ExceptionAssert.<ThrowsAsync>d__0`1.MoveNext() in C:\Development\Source\grpc-dotnet\test\Shared\ExceptionAssert.cs:line 36<---

0.320s Grpc.Net.Client.Tests.CancellationTests - Debug: Observed exception was awaited by the test
```

The test:
* Starts a fake gRPC call that immediately fails with an error.
* Calls `ResponseHeadersAsync` on the gRPC client and catches the error thrown.
* Runs GC/finalizes to trigger any unobserved exceptions.
* Gets one unobserved exception and then verifies with `Assert.AreSame` that it is the same error that was thrown from `ResponseHeadersAsync`.

I don't know why the error is raised as unobserved when it was previously awaited and caught.

The behavior is consistent on .NET 4.x, .net6, .net7, .net8.

**Comment by BrennanConroy** [comment] 2023-08-25 21:36
I was curious, and nerd-sniped myself a little.

I wasn't able to figure out why since there is so much exception handling going on, but if you add `await Task.Yield();` before `throw new Exception("Test error");` it fixes the problem, or if you add `_ = call.ResponseAsync.Exception;` to `MakeGrpcCallAsync` it also fixes it.

Maybe that'll help point you to the issue since you're more familiar with the code-base.

**Comment by JamesNK** [comment] 2023-08-26 13:05
> `_ = call.ResponseAsync.Exception;`

I looked into this, and there are errors thrown from `ResponseAsync` **_and_** `ResponseHeadersAsync`. The unobserved error from `ResponseAsync` is the problem. Observing both methods fixes this.

What I think is creating the confusing stack trace is the same exception is being thrown from both locations. The stack trace is modified between throws. The stack trace for the exception ends up with `ResponseHeadersAsync` in it by the time the finalizer thread runs, and the ex is reported as unobserved. This is then confusing because the async method that's causing the unobserved exception is `ResponseAsync`.

**Comment by ericstj** [comment] 2023-09-09 00:22
@JamesNK it sounds like you found the root cause here.  Did you have any suggestion to make this easier to understand?  Should the code that's rethrowing the exception instead wrap it to avoid overwriting the stack-trace?

**Comment by JamesNK** [comment] 2023-09-09 04:02
I don't know. I think someone who knows more about how tasks and exceptions interact would need to look into it. But this is probably a pretty fringe scenario.

**Comment by stephentoub** [comment] 2024-06-28 14:34
There doesn't appear to be anything actionable here at this point so I'm going to close the issue. Thanks.

**Closed by stephentoub** 2024-06-28 14:34 UTC
Labels: question, area-System.Threading.Tasks
