### ISSUE TITLE
NRE in `iOS.Device.Aot.Test` when starting up xharness

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#96403] opened 2024-01-02 16:31 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=512194
Build error leg or test failing: iOS.Device.Aot.Test.WorkItemExecution
Pull request: https://github.com/dotnet/runtime.git/pull/96399

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "at Microsoft.DotNet.XHarness.iOS.Shared.Hardware.Device.get_Architecture",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

```
[09:53:22] info: Preparing run for ios-device
[09:53:22] info: Looking for available ios-device devices..
[09:53:22] dbug: Looking for available ios-device devices. Storing logs into list-ios-device-20240102_095322.log
[09:53:25] crit: System.NullReferenceException: Object reference not set to an instance of an object.
                    at Microsoft.DotNet.XHarness.iOS.Shared.Hardware.Device.get_Architecture() in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/Device.cs:line 100
                    at Microsoft.DotNet.XHarness.iOS.Shared.Hardware.Device.get_Supports64Bit() in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/Device.cs:line 82
                    at Microsoft.DotNet.XHarness.iOS.Shared.Hardware.HardwareDeviceLoader.<>c.<get_Connected64BitIOS>b__7_0(IHardwareDevice x) in /_/src/Microsoft.DotNet.XHarness.iOS.Shared/Hardware/HardwareDeviceLoader.cs:line 48
                    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
                    at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
                    at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
                    at Microsoft.DotNet.XHarness.Apple.DeviceFinder.FindDevice(TestTargetOs target, String deviceName, ILog log, Boolean includeWirelessDevices, Boolean pairedDevicesOnly, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.XHarness.Apple/DeviceFinder.cs:line 87
                    at Microsoft.DotNet.XHarness.Apple.BaseOrchestrator.OrchestrateOperationInternal(TestTargetOs target, String deviceName, Boolean includeWirelessDevices, Boolean resetSimulator, Boolean enableLldb, GetAppBundleInfoFunc getAppBundle, ExecuteMacCatalystAppFunc executeMacCatalystApp, ExecuteAppFunc executeApp, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.XHarness.Apple/Orchestration/BaseOrchestrator.cs:line 215
                    at Microsoft.DotNet.XHarness.Apple.BaseOrchestrator.OrchestrateOperation(TestTargetOs target, String deviceName, Boolean includeWirelessDevices, Boolean resetSimulator, Boolean enableLldb, GetAppBundleInfoFunc getAppBundle, ExecuteMacCatalystAppFunc executeMacCatalystApp, ExecuteAppFunc executeApp, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.XHarness.Apple/Orchestration/BaseOrchestrator.cs:line 96
                    at Microsoft.DotNet.XHarness.Apple.RunOrchestrator.OrchestrateRun(GetAppBundleInfoFunc getAppBundleInfo, TestTargetOs target, String deviceName, TimeSpan timeout, TimeSpan launchTimeout, Int32 expectedExitCode, Boolean includeWirelessDevices, Boolean resetSimulator, Boolean enableLldb, Boolean signalAppEnd, Boolean waitForExit, IReadOnlyCollection`1 environmentalVariables, IEnumerable`1 passthroughArguments, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.XHarness.Apple/Orchestration/RunOrchestrator.cs:line 221
                    at Microsoft.DotNet.XHarness.CLI.Commands.Apple.AppleAppCommand`1.Invoke(ILogger logger) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/AppleAppCommand.cs:line 68
                    at Microsoft.DotNet.XHarness.CLI.Commands.XHarnessCommand`1.Invoke(IEnumerable`1 arguments) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/XHarnessCommand.cs:line 145
XHarness exit code: 71 (GENERAL_FAILURE)
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=512194
**Error message validated:** `at Microsoft.DotNet.XHarness.iOS.Shared.Hardware.Device.get_Architecture`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 1/2/2024 4:32:55 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by akoeplinger** [comment] 2024-01-07 09:44
The root cause of this one is https://github.com/dotnet/dnceng/issues/1749

**Comment by jeffschwMSFT** [comment] 2024-02-15 23:13
was not seen recently... dropping blocking-clean-ci

24-Hour Hit Count | 7-Day Hit Count | 1-Month Count
-- | -- | --
0 | 0 | 0

**Comment by akoeplinger** [comment] 2024-02-16 09:46
The root cause of this was https://github.com/dotnet/dnceng/issues/1749 which was fixed, let's close this.

**Closed by akoeplinger** 2024-02-16 09:46 UTC
Labels: untriaged, area-Infrastructure-mono, Known Build Error
