### ISSUE TITLE
Get different result when using ToString("F2", new CultureInfo("de-DE") in .NET6 and .Framework4.7.2

### ISSUE THREAD

**Issue by guangzhengli** [dotnet/runtime#75588] opened 2022-09-14 07:08 UTC
### Description

code:
```
  double value = 50.555d;
  Console.WriteLine(value.ToString("F2", new CultureInfo("de-DE")));
```

.dotnet6: output = 50.55
.Framework4.7.2 output = 50.56

![MnVCDR](https://cdn.jsdelivr.net/gh/guangzhengli/PicURL@master/uPic/MnVCDR.jpg)

### Reproduction Steps

```
    internal class Program
    {
        static void Main(string[] args)
        {
            double value = 50.555d;
            Console.WriteLine(value.ToString("F2", new CultureInfo("de-DE")));
        }
    }
``` 

### Expected behavior

output = 50.56

### Actual behavior

output = 50.55

### Known Workarounds

Console.WriteLine(string.Format(new CultureInfo("de-DE"), "{0:0.00}", value));

### Other information

Is there any reason for this difference? Thanks!

**Comment by aloraman** [comment] 2022-09-14 11:32
@KalleOlaviNiemitalo Well, yes. It happens because actual float-pointing value is less than 50.555, but it doesn't explain the difference with .NetFramework. It is indeed caused by that breaking change in .Net Core 2.1, but this quote is the only piece of documentation, that explains what happened.
To get to the details of what's actually changed you need to dig deeper into Github issues (e.g., https://github.com/dotnet/runtime/issues/27174 and related changes https://github.com/dotnet/coreclr/pull/12894) which is not simple - a lot of repos were moved and/or archived. Basically, the implementation has moved from native `ecvt` function, to  different managed implementation, which uses Dragon4 algorithm. We can guess .NetFramework uses similar `_ecvt` function (at least open sourced SSCLI does)
The thing is, the breaking change has happened intentionally, so the chance this behavior will be fixed in the future is very slim.

**Comment by Joe4evr** [comment] 2022-09-14 11:57
> That's a known breaking change, that happened in .NET Core 2.1 See https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings:

There was another change to floating-point number parsing and formatting in .NET Core 3.0: https://devblogs.microsoft.com/dotnet/floating-point-parsing-and-formatting-improvements-in-net-core-3-0/#making-the-formatter-ieee-754-2008-compliant

**Comment by eerhardt** [comment] 2022-09-14 13:25
cc @tannergooding @dakersnar

**Comment by tannergooding** [comment] 2022-09-14 14:54
IEEE 754 floating-point values can only exactly represent values that are a multiple of some power of 2. Since `50.555` doesn't fit this requirement, it rounds to the nearest representable result instead: `50.55499999999999971578290569595992565155029296875`.

The floating-point parsing/formatting behavior prior to .NET Core 3.1 was not IEEE 754 compliant and had numerous edge case bugs where it would effectively "double round" due to not considering the exact represented value.

The value rounded to 2 fractional digits is indeed `50.55` because the third fractional digit of the infinitely precise value represented is `4` and therefore below the midpoint. This likewise matches what other languages do for their IEEE 754 floating-point parsing/formatting under similar circumstances.

**Closed by tannergooding** 2022-09-14 14:54 UTC
Labels: area-System.Globalization, untriaged

**Comment by danmoseley** [comment] 2022-09-14 14:58
@guangzhengli I don't know what you are using double for, but please note that you should not use double for financial calculations. Use Decimal .

**Comment by guangzhengli** [comment] 2022-09-15 02:27
Thanks for letting me know about these.
