### ISSUE TITLE
Support for implicit project

### ISSUE THREAD

**Issue by johankson** [dotnet/runtime#64939] opened 2022-02-07 20:49 UTC
Given the new fantastic implicit usings and top level programs in .net 6, it would be great to finish it off with implicit project file that assumes .net 6, implicit usings so that you can go:

`dotnet myfile.cs`

without having a project file. It should then assume the following

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>somethingsmarthere</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
```

If there is a project file in the directory, it should of course be used.

**Comment by jkotas** [comment] 2022-02-07 22:13
Duplicate of https://github.com/dotnet/sdk/issues/12328. See https://github.com/dotnet/designs/pull/213 and https://github.com/dotnet/csharplang/blob/main/meetings/2021/LDM-2021-05-12.md#simple-c-programs for recent updates.

**Closed by jkotas** 2022-02-07 22:13 UTC
Labels: untriaged
