### ISSUE TITLE
[monovm] Assertion at object.c:657, condition `lock->done' not met

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/runtime#96872] opened 2024-01-11 22:29 UTC
### Description

When running some threaded code in a MAUI app (android in this case), the app may fail with the following error:

```
[nyname.UnoApp16] * Assertion at /__w/1/s/src/mono/mono/metadata/object.c:657, condition `lock->done' not met
```

https://github.com/dotnet/runtime/blob/cf34ef04b89a3e73405ae0cef5ecdb55ba17736d/src/mono/mono/metadata/object.c#L657

This happens when connecting in parallel to multiple websockets, see the `StartConnection()` in `MainPage.xaml.cs`.

### Reproduction Steps

- Build the following app:  [96872-threading-crash.zip](https://github.com/dotnet/runtime/files/13909047/96872-threading-crash.zip)
- Start the app with a debugger

### Expected behavior

The app does not crash

### Actual behavior

the app crashes immediately most of the time

### Regression?

Yes, was working fine in 8.0.100.

### Known Workarounds

Yes, don't execute any threaded code.

### Configuration

```
dotnet --version
8.0.101
```

```
dotnet workload update --print-rollback
==workloadRollbackDefinitionJsonOutputStart==
{
  "microsoft.net.sdk.android": "34.0.52/8.0.100",
  "microsoft.net.sdk.ios": "17.0.8490/8.0.100",
  "microsoft.net.sdk.maccatalyst": "17.0.8490/8.0.100",
  "microsoft.net.sdk.macos": "14.0.8490/8.0.100",
  "microsoft.net.sdk.maui": "8.0.3/8.0.100",
  "microsoft.net.sdk.tvos": "17.0.8490/8.0.100",
  "microsoft.net.workload.mono.toolchain.current": "8.0.1/8.0.100",
  "microsoft.net.workload.emscripten.current": "8.0.1/8.0.100",
  "microsoft.net.workload.emscripten.net6": "8.0.1/8.0.100",
  "microsoft.net.workload.emscripten.net7": "8.0.1/8.0.100",
  "microsoft.net.workload.mono.toolchain.net6": "8.0.1/8.0.100",
  "microsoft.net.workload.mono.toolchain.net7": "8.0.1/8.0.100",
  "microsoft.net.sdk.aspire": "8.0.0-preview.2.23619.3/8.0.100"
}
==workloadRollbackDefinitionJsonOutputEnd==
```

**Comment by lambdageek** [comment] 2024-01-11 23:45
Probably I messed something up in https://github.com/dotnet/runtime/pull/93875

**Comment by lambdageek** [comment] 2024-01-11 23:55
Oh... yea...

https://github.com/dotnet/runtime/blob/cf34ef04b89a3e73405ae0cef5ecdb55ba17736d/src/mono/mono/metadata/object.c#L615-L657

on line 615 we know `!lock->done`
then on 650-651 we find out that `wait_result == 0` - ie we were signaled on `lock->cond`.  And then we fall through to 656.  But we probably need a barrier so that we actually see `lock->done` (although I thought mutex locking/unlocking is a barrier.)

alternately a thread that is doing the initialization is dying and we're calling `mono_release_type_locks` which doesn't set `lock->done`

**Comment by lambdageek** [comment] 2024-01-12 00:14
Just noticed another thing that is wrong. when we `goto retry_top`, we repeat `HANDLE_FUNCTION_ENTER()` without doing a corresponding `HANDLE_FUNCTION_RETURN`, so we're incidentally messing up the coop handle stack.

**Comment by lambdageek** [comment] 2024-01-12 00:17
Oh. It's probably a spurious wakeup.  We need to actually re-evaluate `lock->done` if `wait_result == 0`

**Comment by lambdageek** [comment] 2024-01-12 15:52
Can repro the crash on a real Pixel 6a, but not in an emulator

**Comment by lambdageek** [comment] 2024-01-12 22:37
Reopening until the 8.0.x backport is merged

**Comment by lambdageek** [comment] 2024-01-13 04:57
Backport has been merged, too.

**Closed by lambdageek** 2024-01-13 04:57 UTC
Labels: area-VM-threading-mono

**Comment by liejuntao001** [comment] 2024-01-17 17:21
When will the fix be released? We are all stuck by this issue.
Both 8.0.101 and 8.0.100 not working.

**Comment by lambdageek** [comment] 2024-01-17 18:53
> When will the fix be released? We are all stuck by this issue. 

@liejuntao001 see https://github.com/dotnet/runtime/issues/96804#issuecomment-1890313303 
there is a suggestion in there for how to enable additional logging that may help you to work around the issue.

servicing releases for .NET come out approximately monthly.  The fix for this issue is queued up for the February servicing release.

>Both 8.0.101 and 8.0.100 not working.

This assertion is new in 8.0.101.  What is the issue in 8.0.100?  Could you open a new GitHub issue for it.

**Comment by jeromelaban** [comment] 2024-01-17 18:55
> This assertion is new in 8.0.101. What is the issue in 8.0.100? Could you open a new GitHub issue for it.

@lambdageek as rolling back workloads is not easy (it requires rollback files), changing the active version of the SDK in global.json does not have any effect, which can cause confusion. I hope that https://github.com/dotnet/designs/pull/294 will clear a lot of this confusion...

**Comment by lambdageek** [comment] 2024-01-17 19:38
> > This assertion is new in 8.0.101. What is the issue in 8.0.100? Could you open a new GitHub issue for it.
> 
> @lambdageek as rolling back workloads is not easy (it requires rollback files), changing the active version of the SDK in global.json does not have any effect on the active workload, which can cause confusion. I hope that [dotnet/designs#294](https://github.com/dotnet/designs/pull/294) will clear a lot of this confusion...

You're right. that would explain it.

> 
> > The fix for this issue is queued up for the February servicing release
> 
> As for the monthly servicing, February is quite far away for an issue that arises when updating visual studio, and for which rolling back is difficult.

As a temporary workaround you might be able to force the 8.0.101 SDK to use the 8.0.0 runtime pack with something like this:

```xml
<Target Name="UpdateRuntimePackVersion" BeforeTargets="ProcessFrameworkReferences">
  <ItemGroup>
    <KnownRuntimePack Condition="%(RuntimePackLabels) == 'Mono'" LatestRuntimeFrameworkVersion="8.0.0" />
  </ItemGroup>
</Target>
```

**Comment by liejuntao001** [comment] 2024-01-17 22:28
This workaround works for me.

**Comment by orimslala** [comment] 2024-01-27 03:39
Hi, has this been released. i am getting crashes as well..

**Comment by BeepBeepBopBop** [comment] 2024-01-30 20:30
Hello, I am still experiencing this issue despite being up to date with MAUI latest version and also including the workaround in the  csproj.

**Comment by mlyrstad** [comment] 2024-01-31 07:34
> Hello, I am still experiencing this issue despite being up to date with MAUI latest version and also including the workaround in the csproj.

I don't think the fix is _released_ yet. These guys don't believe in hotfixes, it seems, even for critical issues like this. May have something to do with the fact that the error is so far down in the system, I dunno. We have to wait for the Februrary push.

**Comment by bitzeal-johan** [comment] 2024-02-03 11:09
When is the February push out? It is February now. We're waiting. Our customers projects are crashing.

**Comment by gdamino** [comment] 2024-02-06 20:13
This bug broken our production App.
Our app starts a few threads to do some stuff with tcp sockets, it crash on every user devices and emulators.
`Assertion at /__w/1/s/src/mono/mono/metadata/object.c:657, condition lock->done not met`
It's a critical issue, no workarounds works here, when it will be fixed?

**Comment by bcaceiro** [comment] 2024-02-09 06:01
So when will this be available in MAUI? I am getting this crashes all the time

**Comment by filipnavara** [comment] 2024-02-10 12:00
> When is the February push out?

As always, on patch Tuesday - the second Tuesday of a month - so February 13th.

**Comment by paulwroe** [comment] 2024-02-13 14:22
Any joy with the new update, has anyone had a chance to try it (if it's available)

**Comment by paulwroe** [comment] 2024-02-13 19:48
I'm on Visual Studio for Mac 2022 they've got a new update out today so I'll try that tomorrow, I also use Rider and there's a Mono update for VS, which I think is where the issue is, fingers crossed!

**Comment by gdamino** [comment] 2024-02-14 13:34
Sdk 8.0.200 fixed the issue on Debug configuration for me, but still persist in Release for android. No way
