### ISSUE TITLE
Test failure: Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#34987] opened 2020-04-15 06:51 UTC
failed in job: [runtime-libraries outerloop 20200414.5 ](https://dev.azure.com/dnceng/public/_build/results?buildId=600073&view=ms.vss-test-web.build-test-results-tab&runId=18899108&resultId=103144&paneView=debug)

failed tests:
System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Proxy_Test.Proxy_UseEnvironmentVariableToSetSystemProxy_RequestGoesThruProxy
System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Proxy_Http2_Test.Proxy_UseEnvironmentVariableToSetSystemProxy_RequestGoesThruProxy

Error message
~~~
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  Xunit.Sdk.ContainsException: Assert.Contains() Failure
Not found: HTTP/1.1 LoopbackProxyServer
In value:  {"Method":"GET","Url":"/Echo.ashx","Headers": {
    "Connection": "Keep-Alive",
    "Host": "corefx-net-http11.azurewebsites.net",
    "Max-Forwards": "10",
    "X-WAWS-Unencoded-URL": "/Echo.ashx",
    "CLIENT-IP": "40.85.153.96:1233",
    "X-ARR-LOG-ID": "ceca0602-e2cb-42f0-8329-c06052639742",
    "DISGUISED-HOST": "corefx-net-http11.azurewebsites.net",
    "X-SITE-DEPLOYMENT-ID": "corefx-net-http11",
    "WAS-DEFAULT-HOSTNAME": "corefx-net-http11.azurewebsites.net",
    "X-Original-URL": "/Echo.ashx",
    "X-Forwarded-For": "40.85.153.96:1233"
  },
  "Cookies": {},
  "BodyContent": "",
  "BodyLength": 0,
  "SecureConnection": false,
  "ClientCertificatePresent": false,
  "ClientCertificate": null
}
   at System.Net.Http.Functional.Tests.HttpClientHandler_Proxy_Test.<>c.<<Proxy_UseEnvironmentVariableToSetSystemProxy_RequestGoesThruProxy>b__4_0>d.MoveNext() in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.Proxy.cs:line 167
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 66

Child process:
  System.Net.Http.WinHttpHandler.Functional.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Http.Functional.Tests.HttpClientHandler_Proxy_Test+<>c System.Threading.Tasks.Task <Proxy_UseEnvironmentVariableToSetSystemProxy_RequestGoesThruProxy>b__4_0(System.String, System.String)

Child arguments:
  2.0, C:\Users\runner\AppData\Local\Temp\ddwkpkvn.xzn
~~~

**Comment by davidsh** [comment] 2020-04-15 15:06
@aik-jahoda This looks similar to the test failures you are already working on.

**Comment by aik-jahoda** [comment] 2020-04-15 15:24
@davidsh yes, this is what I'm working just now as part of #33558. This test is currently disabled and this issue reports test failure in my PR: #34444. I close it as it doesn't affect our tests and the fix is already in progress.
Feel free to reopen.

**Closed by aik-jahoda** 2020-04-15 15:24 UTC
Labels: area-System.Net.Http, untriaged

**Comment by davidsh** [comment] 2020-04-15 15:25
Duplicate of #33558
