### ISSUE TITLE
Consider Uri .ctor to allow for paths starting with \\?\

### ISSUE THREAD

**Issue by krwq** [dotnet/runtime#58712] opened 2021-09-06 08:00 UTC
See https://github.com/dotnet/runtime/pull/58627#issuecomment-912630223 for context.

Would be nice if URI allowed for UNC paths such as i.e. those starting with `\\?\` - that would make it easier to make long paths scenarios to work.

**Comment by karelz** [comment] 2021-09-07 19:34
Triage: Is there any reason, why `Uri` was used in these situation vs. `Path`?
We already regret we support path in Uri, extending it even more is not something we are thrilled about ...

**Comment by karelz** [comment] 2021-09-14 19:43
@krwq ping?

**Comment by karelz** [comment] 2021-09-21 19:51
Triage: Unclear what's customer demand, no info. Closing for now, we can reopen if there are customers asking for it.

**Closed by karelz** 2021-09-21 19:51 UTC
Labels: area-System.Net, needs more info, untriaged

**Comment by krwq** [comment] 2021-09-23 09:50
@karelz legacy reasons, that's what full framework did in at least configuration manager and xml and there is still lots of legacy code relying on that

**Comment by karelz** [comment] 2021-09-23 10:21
@krwq thanks for info. Given the arguments above and the fact we didn't hear from end customers about it yet since .NET Core 1.0, I am inclined to leave it closed for now and wait for feedback. If there is indeed strong demand from customers, we can change our mind in future.

**Comment by buyaa-n** [comment] 2022-06-15 20:22
Another case reported [Reading application settings in NET WinForms OOP designer fails with exception 'Invalid URI: The hostname could not be parsed"](https://github.com/dotnet/runtime/issues/70318#) with similar root cause, but in this case we need to create Uri as it is used for subsequent calls:
https://github.com/dotnet/runtime/blob/c8654e7378a085c8221028cf0ebd759d800ceba7/src/libraries/System.Configuration.ConfigurationManager/src/System/Configuration/ClientConfigPaths.cs#L251-L269

@karelz  could we reopen the issue and investigate?

**Comment by karelz** [comment] 2022-06-20 14:19
We could consider it post-7.0 (as it is risky change), if there are scenarios where it is highly inconvenient to not use `Uri` -- is there more info on how it is being used and why `Path` might not work?

**Comment by RussKie** [comment] 2022-06-21 00:05
@karelz this bug affects Windows Forms out-of-process designer experience.

/cc: @merriemcgaw

**Comment by karelz** [comment] 2022-06-21 10:10
@buyaa-n thanks for the info above. Can you please provide more details about how/where does the `\\?\` path originates? Is there option to change that part to `Path`?

@RussKie understood from the context. Key questions I have: How does it work on .NET Framework? Is it a breaking change between .NET Core and .NET Framework?
Are there workaround options?

The key reason I am asking is that `Uri` is highly sensitive area. It is tricky code base with long history of MSRCs, and bad bugs. There were couple of design decisions in the past which lead to current state where paths are being treated as `Uri`, while behaving differently on Windows and Linux (often as a nasty surprise to users).
From that perspective, support for `\\?\` is a feature, not a bug fix. And it would work only on Windows. It has non-trivial impact on the rest of the `Uri` and needs to be thought through very carefully.

Due to dev availability reasons, we won't be able to implement it before Platform complete, which also increases risk significantly. That's why I am looking strongly into alternatives in 7.0 time frame. And if we decide to do it, we need all the information we can get about the scenario.
Hope it helps to explain the context.

**Comment by buyaa-n** [comment] 2022-06-21 17:28
>  Can you please provide more details about how/where does the \\?\ path originates?

According to https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd `\\?\` is added for long paths (260+plust characters)

> The key reason I am asking is that Uri is highly sensitive area. It is tricky code base with long history of MSRCs, and bad bugs. There were couple of design decisions in the past which lead to current state where paths are being treated as Uri, while behaving differently on Windows and Linux (often as a nasty surprise to users).
> From that perspective, support for \\?\ is a feature, not a bug fix. And it would work only on Windows. It has non-trivial impact on the rest of the Uri and needs to be thought through very carefully.

Thanks for  explanation, it seems Uri doesn't support `\\?\` in .Net framework  too, so seems its better to fix it in `AppDomain.CurrentDomain.BaseDirectory` there is open issue [Consider stripping \\?\ from AppDomain.CurrentDomain.BaseDirectory](https://github.com/dotnet/runtime/issues/58714)
