### ISSUE TITLE
NET 9: Redirecting the output of 'dotnet run' command adds escape characters at the beginning of file: ]9;4;3;\]9;4;0;\

### ISSUE THREAD

**Issue by indrajitjadeja** [dotnet/runtime#109815] opened 2024-11-14 10:16 UTC
### Description

When redirecting the output of `dotnet run` command on windows command prompt  or Windows power shell, it prints the below escape characters at the beginning of the file 

> ]9;4;3;\]9;4;0;\

### Reproduction Steps

Open a windows command prompt or Windows power shell and follow below commands
```
C:\nt9\testit>dotnet --version
9.0.100

C:\nt9>dotnet new console -o testit

C:\nt9>cd testit

C:\nt9\testit>dotnet run
Hello, World!

C:\nt9\testit>dotnet run > nt9.log

C:\nt9\testit>notepad nt9.log
```
[nt9.log](https://github.com/user-attachments/files/17746934/nt9.log)

### Expected behavior

It should print the redirected output without escape characters at the beginning of the file.

### Actual behavior

'nt9.log' file content :

> ]9;4;3;\]9;4;0;\Hello, World!

### Regression?

Using .NET 8 SDK, such issue does not replicate.

```
C:\nt8>dotnet new globaljson --sdk-version 8.0.202
The template "global.json file" was created successfully.

C:\nt8>dotnet new console -o testit

C:\nt8>cd testit

C:\nt8\testit>dotnet --version
8.0.202

C:\nt8\testit>dotnet run
Hello, World!

C:\nt8\testit>dotnet run>nt8.log

C:\nt8\testit>notepad nt8.log
```
'nt8.log' file content:

> Hello, World!

[nt8.log](https://github.com/user-attachments/files/17746945/nt8.log)

### Configuration

.NET version: 9.0.100
OS and version : Windows 11 Enterprise 21H2
Arch: x64

**Comment by huoyaoyuan** [comment] 2024-11-14 10:24
Duplicate of https://github.com/dotnet/sdk/issues/44610

**Comment by vcsjones** [comment] 2024-11-14 14:56
Thanks for taking the time to report an issue. Based on @huoyaoyuan's comment, I am going to close this issue as a duplicate, as the other issue was pre-existing and is likely a better place for the issue to reside.

**Closed** 2024-11-14 14:56 UTC
Labels: untriaged, needs-area-label
