### ISSUE TITLE
Binary DataContract Serialization raises exception with certain contents.

### ISSUE THREAD

**Issue by davidmullin** [dotnet/runtime#81290] opened 2023-01-27 19:54 UTC
### Description

Deserializing an object with certain content using DataContract serialization, but from binary rather than text, sometimes generates an XmlException (see below).  This appears to be impacted by the actual value of the properties on the object.  The exact same data & code functions correctly in .Net Framework 4.8, but errors in .Net 7.

I actually encountered this after converting my service & application to CoreWCF using NetHttpBinding and I started getting client-side errors deserializing results.  I observed that it did not happen with BasicHttpBinding, which led me to look at the binary DataContract serialization process.

Full exception is:

System.Runtime.Serialization.SerializationException: There was an error deserializing the object of type CaseTrakker.ThemeSummaryModel2. The input source is not correctly formatted.
---> System.Xml.XmlException: The input source is not correctly formatted.
   at System.Xml.XmlExceptionHelper.ThrowXmlException(XmlDictionaryReader reader, String res, String arg1, String arg2, String arg3)
   at System.Xml.XmlBufferReader.ReadValue(XmlBinaryNodeType nodeType, ValueHandle value)
   at System.Xml.XmlBinaryReader.ReadNode()
   at System.Xml.XmlBinaryReader.ReadElementContentAsFloat()
   at ReadColorDtoFromXml(XmlReaderDelegator, XmlObjectSerializerReadContext, XmlDictionaryString[], XmlDictionaryString[])
   at System.Runtime.Serialization.DataContracts.ClassDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 id, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
   at ReadThemeSummaryModel2FromXml(XmlReaderDelegator, XmlObjectSerializerReadContext, XmlDictionaryString[], XmlDictionaryString[])
   at System.Runtime.Serialization.DataContracts.ClassDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   at System.Runtime.Serialization.DataContractSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   --- End of inner exception stack trace ---
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Xml.XmlExtensions.DeserializeBinaryContract[T](Byte[] valueToDeserialize) in C:\Work\ADO\CaseTrakker_Main\CaseTrakkerCore\Xml\XmlExtensions.cs:line 446
   at Net6TestApplicationTemplate.MainWindow.DoTestButton_Click(Object sender, RoutedEventArgs e) in C:\Work\ADO\CaseTrakker_Main\Prototypes\Net6TestApplicationTemplate\MainWindow.xaml.cs:line 176

### Reproduction Steps

Given this XML

```
<ThemeSummaryModel2 xmlns:i=http://www.w3.org/2001/XMLSchema-instance xmlns=http://schemas.datacontract.org/2004/07/System.Windows.Media>
  <MediumLightColor>
    <A>255</A>
    <B>191</B>
    <G>191</G>
    <R>191</R>
    <ScA>1</ScA>
    <ScB>0.5209956</ScB>
    <ScG>0.5209956</ScG>
    <ScR>0.5209956</ScR>
  </MediumLightColor>
</ThemeSummaryModel2>
```

The following code raises the above exception in .Net 7, but does not in .Net Framework 4.8.  If I zero out all of the properties, or just create a new instance of ThemeSummaryModel2, it has no problem.

```
public void DoTest(string xml)
{
	var theme = xml.DeserializeContract<ThemeSummaryModel2>();
	var bin = theme.SerializeBinaryContract<ThemeSummaryModel2>();
	var theme2 = bin.DeserializeBinaryContract<ThemeSummaryModel2>();
}

[DataContract(Namespace = "http://schemas.datacontract.org/2004/07/System.Windows.Media")]
public struct ColorDto
{
	[DataMember]
	public byte A { get; set; }
	[DataMember]
	public byte R { get; set; }
	[DataMember]
	public byte G { get; set; }
	[DataMember]
	public byte B { get; set; }

	[DataMember]
	public float ScA { get; set; }
	[DataMember]
	public float ScR { get; set; }
	[DataMember]
	public float ScG { get; set; }
	[DataMember]
	public float ScB { get; set; }
}

[DataContract(Namespace = "http://schemas.datacontract.org/2004/07/System.Windows.Media")]
public class ThemeSummaryModel2
{
	[DataMember]
	public ColorDto MediumLightColor { get; set; }
}

public static T DeserializeContract<T>(this string valueToDeserialize) where T : class
{
	using (StringReader reader = new StringReader(valueToDeserialize))
	{
		using (XmlTextReader xmlReader = new XmlTextReader(reader))
		{
			DataContractSerializer serializer = new DataContractSerializer(typeof(T));
			return serializer.ReadObject(xmlReader) as T;
		}
	}
}

public static byte[] SerializeBinaryContract<T>(this T objectToSerialize) where T : class
{
	MemoryStream writer = new MemoryStream();
	using (XmlDictionaryWriter xmlWriter = XmlDictionaryWriter.CreateBinaryWriter(writer))
	{
		DataContractSerializer serializer = new DataContractSerializer(typeof(T));
		serializer.WriteObject(xmlWriter, objectToSerialize);
		xmlWriter.Flush();
		writer.Position = 0;
		return writer.ToArray();
	}
}

public static T DeserializeBinaryContract<T>(this byte[] valueToDeserialize) where T : class
{
	using (XmlDictionaryReader xmlReader = XmlDictionaryReader.CreateBinaryReader(valueToDeserialize, XmlDictionaryReaderQuotas.Max))
	{
		DataContractSerializer serializer = new DataContractSerializer(typeof(T));
		return serializer.ReadObject(xmlReader) as T;
	}
}
```

### Expected behavior

I except to be able to serialize and deserialize a DataContract object into a binary stream, regardless of the values of the properties in that object.

### Actual behavior

Sometimes, depending upon the exact values of the properties of the object being serialized, I get an exception when deserializing the binary stream.  

I know it is entirely an issue with deserialization, because I've taken the stream created in .Net 7, and deserialized it in .Net Framework 4.8 without issue.  Similarly, if I take the stream created in .Net Framework 4.8, it generates the same exception when deserializing with .Net 7.

### Regression?

It worked in .Net Framework 4.8 (and before, so far as I am aware).

I do not know if it worked in previous versions of .Net.

### Known Workarounds

None.

### Configuration

I am using .Net 7 Desktop
x64
Windows 10
I do not believe that it has anything to do with the configuration.

**Comment by StephenMolloy** [comment] 2023-02-16 23:02
Duplicate of #78913. Fixed in 7.0.3 with PR #80321 and in 8.0 with PR #80274.

**Closed by StephenMolloy** 2023-02-16 23:02 UTC
Labels: area-Serialization, untriaged
