### ISSUE TITLE
Assembly conflicts in dotnet app with plugin support

### ISSUE THREAD

**Issue by azeebazy** [dotnet/runtime#68762] opened 2022-04-28 12:21 UTC
I have a .net core application which make use of plugin architecture as described in [creating-app-with-plugin-support](https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support). 

### Description
My App structure is as below 
bin/
└── MyApp/
    ├── plugins/
    │   └── PluginA/
    │       ├── ...
    │       ├── PluginA.dll
    │       └── Newtonsoft.Json.dll (v 13.x)
    ├── MyApp.dll
    └── Newtonsoft.Json.dll (v13.x)

My plugin A assembly will have controllers in them which are added to services using a custom ControllerProvider

```
public class ControllerProvider : IApplicationFeatureProvider<ControllerFeature>
    {
        private readonly List<AssemblyData> _assemblyData;

        public ControllerProvider(List<AssemblyData> assemblyData)
        {
            _assemblyData = assemblyData;
        }
        public void PopulateFeature(IEnumerable<ApplicationPart> parts, ControllerFeature feature)
        {
            foreach (AssemblyData data in _assemblyData)
            {
                try
                {
                    // Check if the requested assembly is part of the loaded assemblies
                    var assembly = AppDomain.CurrentDomain.GetAssemblies().FirstOrDefault(a => a.GetName().Name == new AssemblyName(Path.GetFileNameWithoutExtension(data.Path)).Name);

                    foreach (var candidate in data.Controllers)
                    {
                        var controller = assembly.GetType(candidate).GetTypeInfo();
                        feature.Controllers.Add(controller);
                    }
                }
                catch (BadImageFormatException ex)
                {
                    //Handle this here
                    Console.WriteLine(ex);
                }
            }
        }
    }

```
and in ConfigureServices method of Startup class

`services.AddMvcCore().ConfigureApplicationPartManager(m => m.FeatureProviders.Add(new ControllerProvider(settings.AssemblyData))).SetCompatibilityVersion(Microsoft.AspNetCore.Mvc.CompatibilityVersion.Latest);`

For example, my ControllerA inside PluginA is loaded in a LoadContext#2 (or other context except DefaultLoadContext). 
ControllerA has the following Api

```
                [HttpPost]
		public IActionResult SampleApi([FromBody] object rawData)
		{
                       var jsonObj = (JObject)rawData;

			if (!(rawData is JObject)) {
				return BadRequest("Parameter can not be empty");
			}

			if (!(rawData is JObject jsonObject)) {
				return BadRequest("Parameter can not be empty");
			}

			//Logic

			return Ok();
		}
```

If I try to access the SampleApi inside ControllerA, I will receive  an InvalidCastException in line
`var jsonObj = (JObject)rawData;`

**System.InvalidCastException: [A]Newtonsoft.Json.Linq.JObject cannot be cast to [B]Newtonsoft.Json.Linq.JObject. Type A originates from 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' in the context 'Default' at location 'C:\bin\MyApp\Newtonsoft.Json.dll'. Type B originates from 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' in the context 'Default' at location 'C:\bin\MyApp\plugins\PluginA\Newtonsoft.Json.dll'.**

The whole idea behind plugin architecture is to remove these kind of conflicts. Am I missing something or Is it by design.

### Configuration

> C:\WINDOWS\system32>dotnet --info
> .NET SDK (reflecting any global.json):
>  Version:   5.0.400
>  Commit:    d61950f9bf
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.19042
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\5.0.400\
> 
> Host (useful for support):
>   Version: 5.0.9
>   Commit:  208e377a53
> 
> .NET SDKs installed:
>   5.0.301 [C:\Program Files\dotnet\sdk]
>   5.0.400 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.All 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by vitek-karas** [comment] 2022-05-02 12:01
Assuming you're using `AssemblyDependencyResolver` this is very likely a problem when building the plugin. As described in the guide you reference plugins should only include dependencies which they want isolated. If they have dependencies which should be shared and thus provided by the host, plugins should not carry those assemblies.
In the build this is achieved by adding `<Private>false</Private>` to `ProjectReference` or `<ExcludeAssets>runtime</ExcludeAssets>` to `PackageReference`.

See https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support#reference-a-plugin-interface-from-a-nuget-package and also the part of that doc which shows a reference to the `PluginBase` (where it uses both `Private` and `ExcludeAssets` on a `ProjectReference`, to make sure that if the `PluginBase` has its own NuGet dependencies, those will not be carried into the plugin's output).

You can also implement the runtime mechanism as proposed by @X1C3, but I recommend starting with the build of plugins if you have control over that. Only if you can't rely on plugins doing the right thing I would do the runtime mechanism.

**Comment by azeebazy** [comment] 2022-05-04 17:43
@X1C3 I tried the following too see the loadcontexts 

`System.Runtime.Loader.AssemblyLoadContext.GetLoadContext(typeof(JObject).Assembly)` clearly shows the Newtonsoft.Json.dll loaded in custom loadcontext and
`System.Runtime.Loader.AssemblyLoadContext.GetLoadContext(rawData.GetType().Assembly)` shows the Newtonsoft.Json.dll loaded in "Default" loadcontext.

Thus the same assembly is not loaded twice in the Default load context.

@vitek-karas For the product related assemblies, yes we are skipping their loading again in the custom load context of the plugins. Does this mean we need to prevent commonly used assemblies like Newtonsoft.Json as well from loading in plugin load context?
Also, does the plugin developer actually need to know the versions of the assemblies used by core product.

**Comment by vitek-karas** [comment] 2022-05-04 17:50
> Does this mean we need to prevent commonly used assemblies like Newtonsoft.Json as well from loading in plugin load context?

It's not about "commonly used", it's about "used to communicate". If you need to exchange instances of type T from plugin to the host or vice versa, the T has to be from an assembly which is loaded into the host and NOT loaded for the second time in the plugin - so should be loaded into Default only.

You seem to pass JSON objects between the host and the plugin, so the JSON types (Newtonsoft) needs to be shared (loaded only to Default).

> Also, does the plugin developer actually need to know the versions of the assemblies used by core product.

Somewhat - it the plugin depends on assembly A version 1 and the host provides A version 2, it will work just fine (assuming version 2 is backward compatible enough). Not the other way round. So the host must always be equal or newer to the plugin. This only applies to the assemblies which are shared (loaded into Default and used by the plugin). Assemblies which are used only by the plugin can be whatever version since they're isolated from the host.

**Comment by agocke** [comment] 2022-07-01 20:01
Closing, as I think the current behavior is working as designed.

**Closed by agocke** 2022-07-01 20:01 UTC
Labels: area-AssemblyLoader-coreclr, untriaged
