### ISSUE TITLE
Vector<byte>.Count doesn't match the code behavior

### ISSUE THREAD

**Issue by jods4** [dotnet/runtime#64052] opened 2022-01-20 16:34 UTC
### Description

Vector<byte> doesn't seem to work correctly on my machine.
On my machine, `Vector.IsHardwareAccelerated` is true, `Vector<byte>.Count` is 32, which is what I'd expect given my CPU supports AVX2.
But then, all computations seem to happen on 16 bytes only, not 32.

### Reproduction Steps

Check `Vector<byte>.Count`, on my machine it's 32.
Then simply look at `Vector<byte>.One` in the debugger.

### Expected behavior

It should contain 32 bytes, each equal to 1.

### Actual behavior

As can be seen in this screenshot, only the first 16 bytes have value 1, the rest is 0.
![image](https://user-images.githubusercontent.com/3832820/150380816-69377677-bf70-4a42-92aa-d47817a4599a.png)

### Regression?

I've seen the same behavior on .net framework (x64 only, as Vector is not HW accelerated in x32); and .net core 6.

### Known Workarounds

Not use Vector<byte>?
Assume a `Vector.Count` of 16 although it's not (very fragile and dangerous).

### Configuration

.net 6 (also reproduces in .net 4.7.2 x64)
Windows 11
x64

### Other information

That seems to obvious to be a bug but I can't find anything about it in the MSDN docs.
I thought maybe just the debugger view might be incorrect, but the result of my computation is wrong.
For example: 
`Vector.Dot(Vector<byte>.One, Vector<byte>.One)`
should be equal to `Vector.Count` (32), but it's 16.

**Comment by Wraith2** [comment] 2022-01-20 17:07
I believe this is a problem with the debugger in visual studio not being able to show the vector correctly rather than the vector not working. If you check the result by checking values produced it might show this. I'm pretty sure there's an open issue for this.

**Comment by tannergooding** [comment] 2022-01-20 17:21
Right, this is a dupe of https://github.com/dotnet/runtime/issues/9688.

The issue is that the debugger only handles fields and not the backing bytes. This means that it may miss data if the user is taking advantage of padding or if the VM explicitly resizes the type.

CC. @tommcdon this is yet another hit on the issue. Is this not something where we can just say "if (typeof(T).IsBlittable) { memcpy(dst, src, sizeof(T)); }`? I'd be happy to take a look if you can point me to where the debugger is marshalling the data between the host process and the debugger.

**Closed by tannergooding** 2022-01-20 17:22 UTC
Labels: area-System.Numerics, duplicate

**Comment by jods4** [comment] 2022-01-20 17:50
@tannergooding 
I suspected as much but I was led astray by the fact that in the immediate window, 
`Vector.Dot(Vector<byte>.One, Vector<byte>.One) == 16`.

I just tried the same inside my program and it returns 32, so the immediate window seems impacted by the same bug as the debugger.

My program did not work because of a stupid bug of my own. I went from using array (for .net 4.7.2) to span (.net 6) back to arrays and forgot to put back the index argument required for arrays. Runtime actually works perfectly, of course. 😆 

Out of curiosity: will `Vector<T>` use 64 bytes stride on machines with AVX512?

**Comment by tannergooding** [comment] 2022-01-20 17:54
> Out of curiosity: will Vector<T> use 64 bytes stride on machines with AVX512?

We don't support AVX-512 today and we've not determined how `Vector<T>` will be impacted if/when the support is added. It's likely going to be hard/problematic because increasing it to 64-bytes implicitly will likely regress a number of user-scenarios. At the same time, it would likely cause perf increases for other scenarios and so it needs a lot of additional thought before a decision is made.
