### ISSUE TITLE
[Perf] Regressions in IndexOf

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#54165] opened 2021-06-14 18:54 UTC
### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Baseline | [4a73cb9af55814e26b78f22d30bd35faa60c31a3](https://github.com/dotnet/runtime/commit/4a73cb9af55814e26b78f22d30bd35faa60c31a3)
Compare | [6ab1cee00ba41b308009c88864aba46b0f61f061](https://github.com/dotnet/runtime/commit/6ab1cee00ba41b308009c88864aba46b0f61f061)
Diff | [Diff](https://github.com/dotnet/runtime/compare/4a73cb9af55814e26b78f22d30bd35faa60c31a3...6ab1cee00ba41b308009c88864aba46b0f61f061)

### Regressions in System.Globalization.Tests.StringSearch

Benchmark | Baseline | Test | Test/Base | Test Quality | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[LastIndexOf_Word_NotFound - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Globalization.Tests.StringSearch.LastIndexOf_Word_NotFound(Options%3a%20(en-US%2c%20IgnoreNonSpace%2c%20False)).html>) | 556.53 ns | 592.84 ns | 1.07 | 0.01 | | |
[LastIndexOf_Word_NotFound - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Globalization.Tests.StringSearch.LastIndexOf_Word_NotFound(Options%3a%20(en-US%2c%20None%2c%20False)).html>) | 556.77 ns | 592.91 ns | 1.06 | 0.00 | | |
[IndexOf_Word_NotFound - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Globalization.Tests.StringSearch.IndexOf_Word_NotFound(Options%3a%20(%2c%20None%2c%20False)).html>) | 560.81 ns | 594.70 ns | 1.06 | 0.00 | | |
[LastIndexOf_Word_NotFound - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Globalization.Tests.StringSearch.LastIndexOf_Word_NotFound(Options%3a%20(%2c%20None%2c%20False)).html>) | 556.54 ns | 590.50 ns | 1.06 | 0.00 | | |
[IndexOf_Word_NotFound - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Globalization.Tests.StringSearch.IndexOf_Word_NotFound(Options%3a%20(en-US%2c%20IgnoreNonSpace%2c%20False)).html>) | 560.67 ns | 596.84 ns | 1.06 | 0.00 | | |
[IndexOf_Word_NotFound - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Globalization.Tests.StringSearch.IndexOf_Word_NotFound(Options%3a%20(en-US%2c%20None%2c%20False)).html>) | 560.08 ns | 596.92 ns | 1.07 | 0.00 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_24_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Globalization.Tests.StringSearch_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_24_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Globalization.Tests.StringSearch_2.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_24_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Globalization.Tests.StringSearch_3.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_24_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Globalization.Tests.StringSearch_4.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_24_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Globalization.Tests.StringSearch_5.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_24_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Globalization.Tests.StringSearch_6.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_24_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Globalization.Tests.StringSearch.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Globalization.Tests.StringSearch*'
```
<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-9c632bad-2437-4447-a3ec-17ea7a97adde206274cbd7943ce83/ede1bb44-a225-4002-a01f-3b20c32a38e3.zip?sv=2019-07-07&se=2021-06-18T00%3A31%3A06Z&sr=c&sp=rl&sig=6PcmdolT%2Bdxm3e4o%2FXaGWIp6wgQjTOfK%2FZ9QRfh2NHc%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-9db6f87f-a034-4c28-ae89-8391868837414341467fbc14fe1b8/abe3de14-3bf8-4158-8cd2-e51423171eb0.zip?sv=2019-07-07&se=2021-06-18T09%3A53%3A33Z&sr=c&sp=rl&sig=UAqSSpAxPccDz3Xc%2F6KZqCL%2BkSu3RkPoidCDzt38HOw%3D>)

#### System.Globalization.Tests.StringSearch.LastIndexOf_Word_NotFound(Options: (en-US, IgnoreNonSpace, False))

```log

```
#### System.Globalization.Tests.StringSearch.LastIndexOf_Word_NotFound(Options: (en-US, None, False))

```log

```
#### System.Globalization.Tests.StringSearch.IndexOf_Word_NotFound(Options: (, None, False))

```log

```
#### System.Globalization.Tests.StringSearch.LastIndexOf_Word_NotFound(Options: (, None, False))

```log

```
#### System.Globalization.Tests.StringSearch.IndexOf_Word_NotFound(Options: (en-US, IgnoreNonSpace, False))

```log

```
#### System.Globalization.Tests.StringSearch.IndexOf_Word_NotFound(Options: (en-US, None, False))

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>
### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Baseline | [4a73cb9af55814e26b78f22d30bd35faa60c31a3](https://github.com/dotnet/runtime/commit/4a73cb9af55814e26b78f22d30bd35faa60c31a3)
Compare | [6ab1cee00ba41b308009c88864aba46b0f61f061](https://github.com/dotnet/runtime/commit/6ab1cee00ba41b308009c88864aba46b0f61f061)
Diff | [Diff](https://github.com/dotnet/runtime/compare/4a73cb9af55814e26b78f22d30bd35faa60c31a3...6ab1cee00ba41b308009c88864aba46b0f61f061)

### Regressions in System.Memory.ReadOnlySpan

Benchmark | Baseline | Test | Test/Base | Test Quality | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[IndexOfString - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows 10.0.18362/System.Memory.ReadOnlySpan.IndexOfString(input%3a%20%22AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXAAAAAAAAAAAAAAAAAAAAAAAAAAAAA%22%2c%20value%3a%20%22x%22%2c%20comparisonType%3a%20InvariantCultureIgno.html>) | 231.36 ns | 245.69 ns | 1.06 | 0.00 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_24_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Memory.ReadOnlySpan_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/05_24_2021/refs/heads/main_x64_Windows%2010.0.18362_Regression/System.Memory.ReadOnlySpan.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Memory.ReadOnlySpan*'
```
<details>

### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-9c632bad-2437-4447-a3ec-17ea7a97adde206274cbd7943ce83/ede1bb44-a225-4002-a01f-3b20c32a38e3.zip?sv=2019-07-07&se=2021-06-18T00%3A31%3A06Z&sr=c&sp=rl&sig=6PcmdolT%2Bdxm3e4o%2FXaGWIp6wgQjTOfK%2FZ9QRfh2NHc%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-9db6f87f-a034-4c28-ae89-8391868837414341467fbc14fe1b8/abe3de14-3bf8-4158-8cd2-e51423171eb0.zip?sv=2019-07-07&se=2021-06-18T09%3A53%3A33Z&sr=c&sp=rl&sig=UAqSSpAxPccDz3Xc%2F6KZqCL%2BkSu3RkPoidCDzt38HOw%3D>)

#### System.Memory.ReadOnlySpan.IndexOfString(input: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", value: "x", comparisonType: InvariantCultureIgnoreCase)

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by tarekgh** [comment] 2021-06-15 17:57
@EgorBo @kunalspathak, I have looked at the merged commits around the regression time, I am not seeing anything can be related to cause this issue except the following two commits:

```
commit 8868e97a3e69f43e7e97f1b7da463185de9300bf
Author: Kunal Pathak <Kunal.Pathak@microsoft.com>
Date:   Wed May 19 10:01:26 2021 +0530

    Refactor LSRA's heuristics selection (#52832)


commit 0e1adc01d16393c0212c389580e1b788caae5b03
Author: Egor Bogatov <egorbo@gmail.com>
Date:   Wed May 19 09:15:32 2021 +0300

    JIT: Convert some of the old-style intrinsics to NamedIntrinsics (#52156)
```

Could you please have a look?

CC @jkotas

**Comment by kunalspathak** [comment] 2021-06-15 18:05
It seems to be coming from https://github.com/dotnet/runtime/pull/52827 - @AndyAyersMS

**Comment by AndyAyersMS** [comment] 2021-08-09 20:39
The regression clearly seems to be caused by switch peeling introduced in #52827, but when I run the tests I don't see any switch peeling in the key methods. Odd.

Am going to see if I can repro the perf regression locally by disabling peeling.

**Comment by AndyAyersMS** [comment] 2021-08-09 21:54
Local run with switch peeling disabled at recent main; don't see the kind of regressions noted above.

|                Method |  Opt    |                           Options |        Mean | Ratio |
|---------------------- | ------- |---------------------------------- |------------:|------:|
| IndexOf_Word_NotFound | PEEL    |             (, IgnoreCase, False) |   554.11 ns |  1.00 |
| IndexOf_Word_NotFound | NO PEEL |             (, IgnoreCase, False) |   539.38 ns |  0.97 |
| IndexOf_Word_NotFound | PEEL    |              (, IgnoreCase, True) | 7,137.34 ns |  1.00 |
| IndexOf_Word_NotFound | NO PEEL |              (, IgnoreCase, True) | 7,020.49 ns |  0.98 |
| IndexOf_Word_NotFound | PEEL    |                   (, None, False) |   425.29 ns |  1.00 |
| IndexOf_Word_NotFound | NO PEEL |                   (, None, False) |   429.10 ns |  1.01 |
| IndexOf_Word_NotFound | PEEL    |                    (, None, True) | 7,106.73 ns |  1.00 |
| IndexOf_Word_NotFound | NO PEEL |                    (, None, True) | 7,062.79 ns |  0.99 |
| IndexOf_Word_NotFound | PEEL    |        (en-US, IgnoreCase, False) |   536.70 ns |  1.00 |
| IndexOf_Word_NotFound | NO PEEL |        (en-US, IgnoreCase, False) |   534.88 ns |  1.00 |
| IndexOf_Word_NotFound | PEEL    |         (en-US, IgnoreCase, True) | 7,046.30 ns |  1.00 |
| IndexOf_Word_NotFound | NO PEEL |         (en-US, IgnoreCase, True) | 7,038.38 ns |  1.00 |
| IndexOf_Word_NotFound | PEEL    |    (en-US, IgnoreNonSpace, False) |   420.33 ns |  1.00 |
| IndexOf_Word_NotFound | NO PEEL |    (en-US, IgnoreNonSpace, False) |   434.31 ns |  1.04 |
| IndexOf_Word_NotFound | PEEL    |     (en-US, IgnoreSymbols, False) | 7,036.55 ns |  1.00 |
| IndexOf_Word_NotFound | NO PEEL |     (en-US, IgnoreSymbols, False) | 7,034.09 ns |  1.00 |
| IndexOf_Word_NotFound | PEEL    |              (en-US, None, False) |   430.08 ns |  1.00 |
| IndexOf_Word_NotFound | NO PEEL |              (en-US, None, False) |   428.71 ns |  1.00 |
| IndexOf_Word_NotFound | PEEL    |               (en-US, None, True) | 7,286.24 ns |  1.00 |
| IndexOf_Word_NotFound | NO PEEL |               (en-US, None, True) | 7,192.27 ns |  0.98 |
| IndexOf_Word_NotFound | PEEL    |           (en-US, Ordinal, False) |    27.51 ns |  1.00 |
| IndexOf_Word_NotFound | NO PEEL |           (en-US, Ordinal, False) |    27.66 ns |  1.01 |
| IndexOf_Word_NotFound | PEEL    | (en-US, OrdinalIgnoreCase, False) |   586.28 ns |  1.00 |
| IndexOf_Word_NotFound | NO PEEL | (en-US, OrdinalIgnoreCase, False) |   585.29 ns |  1.00 |
| IndexOf_Word_NotFound | PEEL    |              (pl-PL, None, False) | 9,485.88 ns |  1.00 |
| IndexOf_Word_NotFound | NO PEEL |              (pl-PL, None, False) | 9,443.02 ns |  1.00 |

Am going to building at the commit for #52827 and the one just before.

**Comment by DrewScoggins** [comment] 2021-08-09 21:55
https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu%2018.04/System.Globalization.Tests.StringSearch.IndexOf_Word_NotFound(Options:%20(,%20IgnoreCase,%20False)).html is also effected.

**Comment by AndyAyersMS** [comment] 2021-08-10 01:52
Need to use a net5.0 host for BDN to avoid some SDK skew trying to run older bits. Hopefully this is ok. Looks like per that my change indeed introduced a regression, but not from the switch peeling. Instead it may be here:

https://github.com/dotnet/runtime/blob/705bbfd7a4c5424fc524c22a71f04f87519fca18/src/coreclr/jit/fgopt.cpp#L1778-L1783

The old logic effectively had `&&` for that second condition, not `||`. Am seeing what fixing this does....

**Comment by AndyAyersMS** [comment] 2021-08-10 02:12
Hmm, not that. Maybe I'll try reverting more in the area of this change. The old logic seemed wonky but perhaps it had merit at times.

**Comment by AndyAyersMS** [comment] 2021-08-10 02:22
Yep, that seems to do the trick:

|                Method | Jit Version         |         Options |     Mean |
|---------------------- |-------------------- |---------------- |---------:|
| IndexOf_Word_NotFound | main + wonky part restored | (, None, False) | 376.9 ns |
| IndexOf_Word_NotFound | main                | (, None, False) | 425.6 ns |
| IndexOf_Word_NotFound | 6ec2fba             | (, None, False) | 430.7 ns |
| IndexOf_Word_NotFound | 6ec2fba~1           | (, None, False) | 393.6 ns |

Time to look at what this older logic actually did. Perhaps it is more sensible than I realized.

**Comment by AndyAyersMS** [comment] 2021-08-10 16:55
The significant diff is in ```CompareInfo:IndexOfOrdinalHelper(ReadOnlySpan`1,ReadOnlySpan`1,int,long,bool):int:this```

```asm
;;; main

       44897528             mov      dword ptr [rbp+28H], r14d
       4C63E7               movsxd   r12, edi
       4C8965A8             mov      qword ptr [rbp-58H], r12
       49BC78CA6E70FB7F0000 mov      r12, 0x7FFB706ECA78
       4C8B75A8             mov      r14, qword ptr [rbp-58H]
       43803C2600           cmp      byte  ptr [r14+r12], 0
       751D                 jne      SHORT G_M22056_IG25

;;; main + wonky part restored

       44897528             mov      dword ptr [rbp+28H], r14d
       4C63E7               movsxd   r12, edi
       49BE78CA6E70FB7F0000 mov      r14, 0x7FFB706ECA78
       43803C3400           cmp      byte  ptr [r12+r14], 0
       751D                 jne      SHORT G_M22056_IG19
```

**Comment by AndyAyersMS** [comment] 2021-08-10 18:30
In this method there's are a mixuture of blocks with and without PGO data. The diff is that the new logic marks some merged blocks as having IBC, where the old logic did not.

Flow graph is identical before these merges. Here's a sample merge: the `bNext` block `BB05`has PGO data, but since the count exactly matches the count in `BB04`, the old logic does not mark `BB04` has as having PGO, while the new logic does...
```
and that is enough to perturb LSRA and introduce a spill.

BB04 [0002]  1       BB03                  1           [036..04C)                                     i bwd 
BB05 [0039]  1       BB04                  1    100    [036..037)-> BB07 (always)                     i bwd IBC 

Compacting blocks BB04 and BB05:

;; main

BB04 [0002]  1       BB03                  1    100    [036..04C)-> BB50 ( cond )                     i bwd IBC 

;; main + old

BB04 [0002]  1       BB03                  1           [036..04C)-> BB50 ( cond )                     i bwd 
```

The general problem of having a method with mixtures of PGO and non PGO method blocks (from inlining, typically) is something we need to work on in .NET 7.

We could revert this bit of the change but I suspect it would cause regressions elsewhere. So I recommend we leave NET 6 alone and work on this down the road.

**Comment by AndyAyersMS** [comment] 2021-08-10 18:37
One last note -- the reason marking a block has having PGO (`IBC`) is so impactful is that it prevents the simple non-PGO based weight updates when we recognize loops. So later on we end up with this odd weight assignment:
```
;; main

BB17 [0017]  2       BB16,BB20            32         3 [0FA..11C)-> BB33 ( cond )                     i Loop Loop0 bwd bwd-target LIR align 
BB18 [0018]  1       BB17                  0.50  50  3 [11C..12F)-> BB33 ( cond )                     i bwd IBC LIR 
BB19 [0019]  1       BB18                 32         3 [12F..135)-> BB22 ( cond )                     i bwd LIR 
BB20 [0023]  1       BB19                 16         3 [156..16D)-> BB17 ( cond )                     i bwd LIR 

;; main + old

BB17 [0017]  2       BB16,BB20            32     3 [0FA..11C)-> BB33 ( cond )                     i Loop Loop0 bwd bwd-target LIR align 
BB18 [0018]  1       BB17                 32     3 [11C..12F)-> BB33 ( cond )                     i bwd LIR 
BB19 [0019]  1       BB18                 32     3 [12F..135)-> BB22 ( cond )                     i bwd LIR 
BB20 [0023]  1       BB19                 16     3 [156..16D)-> BB17 ( cond )                     i bwd LIR 
```
and so we end up spilling in a hot block. Logic for this weight update is here:

https://github.com/dotnet/runtime/blob/d01dae43e1a30d340d994ffb4ed34ae28d3c5664/src/coreclr/jit/optimizer.cpp#L225-L237

The general fix for this is to treat PGO and non-PGO weights on an even footing, but that requires earlier and more sensible assignments of non-PGO weights.

**Comment by kunalspathak** [comment] 2021-08-10 19:45
> So I recommend we leave NET 6 alone and work on this down the road.

Makes sense to me.

**Comment by AndyAyersMS** [comment] 2022-11-01 22:28
Looking at this afresh. For the first test, we were at around 560 when the regression happened:

![newplot - 2022-11-01T152340 693](https://user-images.githubusercontent.com/10121823/199353307-05d2967d-6f20-47fc-82c4-7362474da759.png)

Now we're at 520 and have been there a while:
![newplot - 2022-11-01T152545 315](https://user-images.githubusercontent.com/10121823/199353609-43c942b6-24d7-4335-a766-ae49544a217e.png)

Other tests here look to be similarly improved or at least back to par. So am going to close this.

**Closed by AndyAyersMS** 2022-11-01 22:28 UTC
Labels: os-windows, tenet-performance, tenet-performance-benchmarks, arch-x64, area-CodeGen-coreclr
