### ISSUE TITLE
CurrentConnections property in ServicePoint object returns zero all the time

### ISSUE THREAD

**Issue by bramakrishna16** [dotnet/runtime#2170] opened 2020-01-24 22:45 UTC
I want to report the number of HTTP outgoing connections for telemetric purpose. [Doc](https://docs.microsoft.com/en-us/dotnet/api/system.net.servicepoint.currentconnections?view=netcore-2.1) says I should be able to get number of open connections, but I am getting `CurrentConnections `as zero for any URI I test for. [CurrentConnections](https://github.com/dotnet/runtime/blob/e7866101d856043808eec5005dfa07ca044a6401/src/libraries/System.Net.ServicePoint/src/System/Net/ServicePoint.cs#L93) in ServicePoint.cs is returned zero for any `ServicePoint` object created.

Here is the snippet of my test case:

```c#
        IHttpClientFactory clientFactory = serviceProvider.GetService<IHttpClientFactory>();
        HttpClient client = clientFactory.CreateClient();
        var taskList = new List<Task<HttpResponseMessage>>();
        
        foreach (var item in Enumerable.Range(0, 1000))
        {
            taskList.Add(Task.Run(async () =>
            {
                HttpRequestMessage httpRequestMessage = new HttpRequestMessage(HttpMethod.Get, "https://www.bing.com/");
                ServicePoint servicePoint = ServicePointManager.FindServicePoint(httpRequestMessage.RequestUri); 
                if (servicePoint.CurrentConnections > 0)
                {
                    Assert.Fail($"Found non zero connection = {servicePoint.CurrentConnections}");
                }
                return await client.SendAsync(httpRequestMessage);
            }
            ));
        }
```

**Comment by wfurt** [comment] 2020-01-29 19:02
HttpClient does not use ServicePoint in .Net Core.

**Comment by karelz** [comment] 2020-02-14 00:46
`ServicePoint` and `HttpWebRequest` are legacy APIs. Some of them are stubbed out for easier migration to do nothing.
Closing as By Design.

I don't believe we have this kind of telemetry in .NET Core yet -- it is something we are looking into for 5.0. cc @davidsh

**Closed by karelz** 2020-02-14 00:46 UTC
Labels: area-System.Net.Http, question, untriaged
