### ISSUE TITLE
TestNonCollectibleType times out under GCStress

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#100576] opened 2024-04-03 07:01 UTC
The test added in #100444 times out under GCStress on linux-x64 and osx-arm64. Example pipeline run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=627621&view=results

**Comment by jakobbotsch** [comment] 2024-04-03 07:04
The test looks innocent enough. I'm not sure why it would time out.

**Comment by VSadov** [comment] 2024-04-03 15:43
Right. The test looks compatible with GCStress. Also the hang is in the regular simplest (not collectible) case. Possibly there is a real bug. 
Luckily it reproes on x64, that may make it easier to diagnose than cases that prefer to show up on arm32.

@jkotas - anything in that test that could hang in GCStress?  (like if everything gets collected at earliest opportunity)

**Comment by markples** [comment] 2024-04-03 16:53
It's WaitForPendingFinalizers

**Comment by VSadov** [comment] 2024-04-03 17:10
`WaitForPendingFinalizers` is often problematic in stress cases as it is hard to use without races that can cause it to skip the wait. (thus various schemes with calling it in a loop).   

I do not think there are scenarios when `WaitForPendingFinalizers` wait is unbounded.

**Comment by VSadov** [comment] 2024-04-03 17:26
GCStress makes finalizer thread to spin-wait for "no gc" quiet time. That could cause a delay, but it should not take hours. Eventually there would be no code running and no GCs happening.

Just calling `WaitForPendingFinalizers` should not be an issue in GCStress. We can't avoid it as not only test code calls it.

**Comment by markples** [comment] 2024-04-03 17:39
See https://github.com/dotnet/runtime/issues/97334#issuecomment-1945079354

(Short version: it doesn't take much to cause WaitForPendingFinalizers to spin forever.  GCStress cause GCs to happen very frequently supplies one of the conditions.  A merged test group typically provides the other.)

**Comment by VSadov** [comment] 2024-04-03 18:04
There is no `ReRegisterForFinalize` or even destructors in this testcase.  It simply calls `WaitForPendingFinalizers` 10 times.

Is there an assumption that we 
- already have a self-replicating neverending finalizer in the system, which is not causing any trouble by itself.
- this is the first testcase in the test group to call `WaitForPendingFinalizers` directly or indirectly.

I guess that is possible. 
The right fix then would be making the test nonmergeable, right?

**Comment by markples** [comment] 2024-04-03 18:19
I think 'yes' to all of those.

It seems to be a somewhat common pattern for a finalizer to have `if (condition) ReRegisterForFinalize(this);` which will flood the finalizer thread under GCStress but (I think?) not cause other problems.

Then this is likely the first one to call `WaitForPendingFinalizers` because it wasn't timing out before.

"Right fix" feels generous :) but that seems to be the best option right now.

It would be nice if the runtime operated like the final example in that other comment, but that would add complexity and more importantly be a breaking change.  (I think it's a rather obscure one, but we'd probably need to think about it.)  Maybe GCStress-only?  (but again complexity)

**Comment by VSadov** [comment] 2024-04-03 18:38
> It would be nice if the runtime operated like the final example in that other comment, but that would add complexity and more importantly be a breaking change. (I think it's a rather obscure one, but we'd probably need to think about it.) Maybe GCStress-only? (but again complexity)

I think if semantics of `WaitForPendingFinalizers` is changed to "wait for all finalizers pended at this moment", it would not be observable change, modulo old races vs. new races. 
That is typically the mental model of unassuming user anyways. Perhaps it could be done by pending another finalizer item and waiting for its completion.

**Comment by VSadov** [comment] 2024-04-03 18:39
I will make the test `RequiresProcessIsolation` and we can see what happens.

Unless @jakobbotsch is already looking into this.

**Comment by markples** [comment] 2024-04-03 18:53
I agree with the reasoning but am always wary of such changes.

The order of finalizers isn't guaranteed, and the implementation definitely does not do so.  That idea does have the nice property of nesting nicely, whereas something like a single "pending pending" queue would not.  A single queue where each WaitFor was started after others had completed would do it, as would a priority queue, but I don't think that the complexity tradeoff makes sense for GCStress.

**Comment by VSadov** [comment] 2024-04-03 19:23
Because of critical finalization we are kind of forced into a single-threaded finalization model. We can assume the execution will stay FIFO. Otherwise the placement of finalizers in the queue is indeed random, and racey, except relative to items pended by `GC.Collect` called on the same thread. That seems unavoidable. 

At least you'd have more reliable guarantees for `GC.Collect(); GC.WFPF()` sequence - will not skip waiting for things you've pended, will not wait forever.

I am not arguing for changing `WaitForPendingFinalizers` just for GCStress. I think we would need stronger reasons.

**Comment by markples** [comment] 2024-04-04 00:08
I don't understand the FIFO and same thread guarantees that you mention here, though I'll admit I often get confused when looking at the code.  The overall movement of objects into the live lists and then the pending execution list ends up being LIFO if uninterrupted.  The insertion and move functions for the queues swap elements on the edges so strange things can happen.

For example
``` c#
using System.Runtime.CompilerServices;

class Fin
{
    static int Count = 0;
    int Id;
    public Fin() => Id = Count++;
    ~Fin() => System.Console.Write($"{Id} ");

    [MethodImpl(MethodImplOptions.NoInlining)]
    public static void Alloc() => new Fin();
    public static void Main()
    {
        for (int j = 0; j < 5; j++)
        {
            Count = 0;
            for (int i = 0; i < 20; i++)
            {
                Alloc();
            }
            GC.Collect();
            GC.WaitForPendingFinalizers();
            Console.WriteLine();
        }
    }
}
```

can output

```
17 0 1 2 3 4 5 19 18 16 15 14 13 12 11 10 9 8 7 6
19 18 17 16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1 0
18 17 16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1 0 19
18 17 16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1 0 19
18 17 16 15 14 13 12 11 10 9 8 7 6 5 4 3 2 1 0 19
```

**Comment by VSadov** [comment] 2024-04-04 01:52
The order in which items end up finalized within the same GC is an implementation detail that noone should depend on. I do not think there can be a well-defined order within the same GC. 

We have an ordering guarantee for the critical finalization though. If two objects are collected in the same GC, the critical one will be finalized after noncritical one.  
It is hard to see how this requirement would not be serializing at GC granularity. Although I do not know exactly how our GC arranges the invariant. Maybe it is LIFO or whatever else and just ordinary finalizers take precedence. (feels like it could lead to replicating ordinary finalizer possibly starving critical ones).

**Closed** 2024-04-04 01:53 UTC
Labels: area-CodeGen-coreclr, blocking-clean-ci-optional

**Comment by jkotas** [comment] 2024-04-04 02:15
@VSadov Thank you for fixing this! The fix matches the established pattern. We have 30+ tests marked as RequiresProcessIsolation with `WaitForPendingFinalizers` comment.

I think a better solution would be to suppress stress GCs temporarily while `WaitForPendingFinalizers` is executing. It would make things just work, without requiring manual annotation of every test that uses `WaitForPendingFinalizers`.

**Comment by VSadov** [comment] 2024-04-04 04:48
> I think a better solution would be to suppress stress GCs temporarily while WaitForPendingFinalizers is executing. It would make things just work, without requiring manual annotation of every test that uses WaitForPendingFinalizers.

It may also make it possible for the test to make a lot of progress (or even complete) at the random time span when WaitForPendingFinalizers disables the stress. Things run a lot faster when stress is disabled and coordinating with finalizer thread/queue may take time. 
Right now these tests are relatively deterministic. Not completely, but enough to see when failures start, even if we run them once a week. I would be worried, that suppressing stress automatically will make things easier, but less useful.

**Comment by jkotas** [comment] 2024-04-04 06:21
GCStress incompatibilities like this one limit GCStress 0x3/0xC usefulness to src/tests in this repo. 

GCStress 0x3/0xC hangs with high probability if you enable it for a random real-world app out there. We are not able to run GCStress 0x3/0xC on libraries tests for this reason. I think it would be better to have GCStress that works for libraries tests even if it means having less perfect coverage around WaitForPendingFinalizers and similar APIs.

**Comment by jakobbotsch** [comment] 2024-04-04 08:39
It seems to me that the tests that should be marked with `RequiresProcessIsolation` are the ones that are creating these resources that stick around after the test execution finishes. Those are the tests that have non-local impact, so those are the ones that should be isolated.
Aren't these classes sticking around even outside GCStress and causing potential test non-determinism related to GC triggers?

**Comment by markples** [comment] 2024-04-04 08:39
re: critical finalizers - Yes, it is simply that ordinary finalizers take precedence.  Starvation is possible, just like it is if a finalizer loops infinitely.

re: stress mode - I think I understand the hesitation at weakening these tests a bit, though the gains from not having to deal with these timeouts, being able to run libraries tests, etc., seem much bigger.  GCStress already isn't perfect coverage (I believe that if an object isn't moved, a temporarily missed reporting could slip by), so we're already making tradeoffs between precision and cost/etc.  I think we're always open to refinements, and if we see GC reporting issues then we're going to ask if GCStress could have caught it earlier.  For example, maybe stress GCs on non finalizer threads could wait a bit (not advocating for or against that here, just that it's a possibility).

One thing I've been curious about is how much different tests under GCStress add to the actual quality of testing.  I suspect that they are very redundant, yet I don't think we have a way to determine that so it's been worthwhile to just pay the cost to run a ton of them.  So for coverage here we're weighing the loss in WaitForPendingFinalizers tests to the gain of libraries tests.  Is there reason to believe that WaitForPendingFinalizers tests are "better" than the libraries tests?  I'd guess that the answer is no, but if it yes, then could we refine the testing?  Perhaps only suppress stress GCs if we see a finalizer added from the finalizer thread?  Or after a fixed period of time?  It seems like this opens up more possibilities than where we are right now.

**Comment by jkotas** [comment] 2024-04-04 14:19
> It seems to me that the tests that should be marked with RequiresProcessIsolation are the ones that are creating these resources that stick around after the test execution finishes

I agree in principle. The problem is that it is hard to identify these tests and it is likely that we have a lot of them. 

For example, DynamicMethods use the ReRegisterForFinalize pattern mentioned above that is likely problematic. 

DynamicMethods are used by MethodInfo.Invoke as an optimization. It means that any test that uses MethodInfo.Invoke is potentially problematic. 

MethodInfo.Invoke is used to format stacktraces in some cases. It means that any test that throws exception and then calls `ToString` on it is potentially problematic... .

**Comment by jakobbotsch** [comment] 2024-04-04 14:29
Are those objects permanently and repeatedly putting themselves back in the finalizer queue? What I understood from reading https://github.com/dotnet/runtime/issues/97334#issuecomment-1945079354 is that those were the problematic cases. I.e. cases where we have finalizers whose execution causes some kind of repeated and cyclic enqueuing back into the finalizer queue.

Did we understand what other object exists when this test is executing that causes the behavior?

**Comment by markples** [comment] 2024-04-04 18:28
Some of those can.  Specifically, they will repeatedly do so until some external condition is met.  I do not know all of the details as to what is going on (e.g., is it a DynamicMethod? is it because of the long weak reference in the comment there, or does gcstress interfere in what should be good operation?)  It's suspicious that this tests also uses WeakReferences, but I can't say that I can specifically point to the failure (and why RequireProcessIsolation is enough).

Also, one of the old issues refers to the arrres test.  On looking at it more closely, I do not understand the previous failure there.  While the finalizer reregisters the object for finalization, it also resurrects the object, so it shouldn't be queued to run again.  (Indeed, the workaround was to mark it RequiresProcessIsolation, not disabling it, so the test's own ReRegister/WaitFor isn't causing problems alone.)

We still have worse-than-linear increasing test execution time as we merge tests together which led to splitting some groups more aggressively than expected.  We've vaguely guessed at causes (maybe more statics get initialized causing the frequent GCs to be more expensive?), but maybe slow and infinite are getting conflated.

I think you are correct in pointing out that we don't fully understand the implications of gcstress.

**Comment by jkotas** [comment] 2024-04-05 02:20
> Did we understand what other object exists when this test is executing that causes the behavior?

It is Gen2GcCallback: https://github.com/dotnet/runtime/blob/d86b84f2c8df7928388bcd6e23e2539a16623f36/src/libraries/System.Private.CoreLib/src/System/Gen2GcCallback.cs#L109-L110

What's happening is:
- Finalizer of Gen2GcCallback pointing to SharedArrayPool<TypeA>.Trim is called 
- The Trim method allocates a bit of memory here and there. For example, the `Utilities.GetMemoryPressure` call at https://github.com/dotnet/runtime/blob/d86b84f2c8df7928388bcd6e23e2539a16623f36/src/libraries/System.Private.CoreLib/src/System/Buffers/SharedArrayPool.cs#L189 allocates a bit of memory, but it is not the only allocation on this path.
- Memory allocation triggers stress GC
- Gen2GcCallback is ReRegistered for finalization

- Finalizer of Gen2GcCallback pointing to SharedArrayPool<TypeB>.Trim is called 
- The Trim method allocates a bit of memory here and there. 
- Memory allocation triggers stress GC. This causes Gen2GcCallback pointing to SharedArrayPool<TypeA>.Trim to become ready for finalization.
- Gen2GcCallback is ReRegistered for finalization

- Finalizer of Gen2GcCallback pointing to SharedArrayPool<TypeA>.Trim is called and cycle repeats.

I wish SharedArrayPool was more tightly integrated with the GC to avoid suboptimal behaviors like this.

**Comment by VSadov** [comment] 2024-04-05 08:18
My concern was mostly about determinism and reproducibility. There is a value in extra coverage, but it better yield failures that are reproducible in reasonable number of retries, otherwise the value is not high. 
Perhaps disabling stress while WaitForPendingFinalizers  is in progress is the best that we can do, but there is a concern.

The root cause is that WaitForPendingFinalizers is defined too loosely and implementation takes advantage of that (or maybe it was documented retroactively to fit the implementation). I do not see that changing.

I.E. if there are no more items to finalize, the event will be signaled, but signaling thread could be delayed (imagine - for a second), then once it eventually signals, all the accumulated waiters will be released. That may end up in some waiters not waiting while something is deterministically in the queue. On the other hand, if items keep coming, the wait may never end. 
WFPF is just hard to use reliably. The corner cases may be very rare in reality, but under stress they will show up.  
As we discussed up in the thread there could be solutions that solve both extremes, but we would not be changing the behavior just for GCStress.

The tests that are affected by "sometimes not waiting" part cannot be helped. They are racey tests, not compatible with stress. 

Scenarios affected by WaitForPendingFinalizers never ending, but passing in isolation, may have some mitigations. We already alter behavior of finalization when stress is enabled, we can tweak that further. 

> GCStress 0x3/0xC hangs with high probability if you enable it for a random real-world app out there.

This seems a good motivation to me. I know that 3-rd parties do use GCStress to test their apps. 

> I wish SharedArrayPool was more tightly integrated with the GC to avoid suboptimal behaviors like this

The "GC-happened" sensing pattern that relies on self-rearming finalizer is not all that rare.  
Here is another variety. (the 3-rd party is me here, but anyone could use similar code):
https://github.com/VSadov/NonBlocking/blob/0c9366d852f54d5e96e7c31fec804268d47be5cb/src/NonBlocking/ConcurrentDictionary/DictionaryImpl%603.cs#L1399-L1402

It is not even the lack of API, I think. 
Any kind of "GC happened" notification that runs 3rd party code will likely have the same issues. In that sense the pattern is not an abuse. 

Anyways. I understand what we want to fix here. I just do not like the randomizing part of the "turn off stress temporarily" solution. I do not have anything much better to suggest though. 

I will log an issue to follow up with whatever solution we can come by.

**Comment by jkotas** [comment] 2024-04-05 15:28
> The "GC-happened" sensing pattern that relies on self-rearming finalizer is not all that rare.

It does not mean that it is a good pattern. There is nothing better, so it is what people end up using.

For ArrayPool in particular, Gen2GcCallback callback fires right after the Gen2 happened. So we run Gen2 GC that collects all garbage, only to trigger ArrayPool cleanup that produces more garbage that sits there unreachable until the next Gen2 GC happens.
