### ISSUE TITLE
Json Deserialize IDictionary<Guid, string>

### ISSUE THREAD

**Issue by frankie-p** [dotnet/runtime#45751] opened 2020-12-08 09:35 UTC
In .net5.0, I have a problem while I switched from Newtonsoft.Json to System.Text.Json:

JsonSerializer.Deserialize<IDictionary<Guid, string>>(JsonSerializer.Serialize(new Dictionary<Guid, string>()));

raises the exception:
System.InvalidCastException: 'Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.String,System.String]' to type 'System.Collections.Generic.IDictionary`2[System.Guid,System.String]'.'

Since 
JsonSerializer.Deserialize<IDictionary<string, string>>(JsonSerializer.Serialize(new Dictionary<string, string>()));
is working fine.

I used to deserialized in interfaces (IEnumerable<T>, IDictionary<K,T>) if possible.

Deserializing in a Dictionary<Guid, string> was working for me (as a workaround).

**Comment by layomia** [comment] 2020-12-08 18:19
Duplicate of https://github.com/dotnet/runtime/issues/44726..

**Closed by layomia** 2020-12-08 18:19 UTC
Labels: area-System.Text.Json
