### ISSUE TITLE
[wasi] Assertion sgen-gc.c:1251, condition `sgen_gray_object_queue_is_empty (queue)' not met

### ISSUE THREAD

**Issue by pavelsavara** [dotnet/runtime#88757] opened 2023-07-12 18:02 UTC
```
[11:52:34] info: Discovered:  managed/System.Collections.Tests.dll (found 5666 of 7580 test cases)
[11:52:34] info: Using random seed for test cases: 59584765
[11:52:34] info: Using random seed for collections: 59584765
[11:52:34] info: Starting:    managed/System.Collections.Tests.dll
[11:54:02] info: [MONO] error: * Assertion at /__w/1/s/src/mono/mono/sgen/sgen-gc.c:1251, condition `sgen_gray_object_queue_is_empty (queue)' not met
[11:54:02] info: 
[11:54:02] info: Process wasmtime exited with 1
```

[Log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-88728-merge-785e2fb60ea84f0185/System.Collections.Tests/1/console.bceb98ff.log?helixlogtype=result)

**Comment by lewing** [comment] 2023-07-26 18:03
closing as a duplicate of https://github.com/dotnet/runtime/issues/81911

**Closed by lewing** 2023-07-26 18:03 UTC
Labels: arch-wasm, area-GC-mono, os-wasi
