### ISSUE TITLE
When an interface inherits an interface, System.Text.Json.JsonSerializer.Serialize only encodes the properties of the current interface into the json

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#48768] opened 2021-02-25 17:21 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/接口继承接口时，SystemTextJsonJsonSerializer/1346438)._

---
The interface inherits the interface, and there should be content in the interface at the next level. Now System.Text.Json.JsonSerializer.Serialize encodes a string that contains only data for this level of interface, not the data for the interface's parent interface.
So I'm inglying back and hoping to get help.

---
#### Feedback Bot on 2/23/2021, 00:07 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by huoyaoyuan** [comment] 2021-02-25 17:52
Should be by design - System.Text.Json uses variable/member type instead of object type, unless the variable type is `object`.

**Comment by centreboard** [comment] 2021-02-25 19:09
In this example I would expect serialising as `IFooBar` to serialise both `A` and `B`?

``` csharp
using System;
using System.Text.Json;

var fooBar = new FooBar{A="Foo", B="Bar"};

Console.WriteLine(JsonSerializer.Serialize(fooBar, typeof(FooBar)));
Console.WriteLine(JsonSerializer.Serialize(fooBar, typeof(IFooBar)));
Console.WriteLine(JsonSerializer.Serialize(fooBar, typeof(Foo)));
Console.WriteLine(JsonSerializer.Serialize(fooBar, typeof(IFoo)));


interface IFoo
{
    string A {get;set;}
}

interface IFooBar: IFoo
{
    string B {get;set;}
}

class Foo: IFoo {
    public string A {get;set;}
}

class FooBar: Foo, IFooBar
{
    public string B {get;set;}
}
```

> {"B":"Bar","A":"Foo"}
{"B":"Bar"}
{"A":"Foo"}
{"A":"Foo"}

**Comment by ShuiFan0** [comment] 2021-02-25 19:21
> In this example I would expect serialising as `IFooBar` to serialise both `A` and `B`?
> 
> ```cs
> using System;
> using System.Text.Json;
> 
> var fooBar = new FooBar{A="Foo", B="Bar"};
> 
> Console.WriteLine(JsonSerializer.Serialize(fooBar, typeof(FooBar)));
> Console.WriteLine(JsonSerializer.Serialize(fooBar, typeof(IFooBar)));
> Console.WriteLine(JsonSerializer.Serialize(fooBar, typeof(Foo)));
> Console.WriteLine(JsonSerializer.Serialize(fooBar, typeof(IFoo)));
> 
> 
> interface IFoo
> {
>     string A {get;set;}
> }
> 
> interface IFooBar: IFoo
> {
>     string B {get;set;}
> }
> 
> class Foo: IFoo {
>     public string A {get;set;}
> }
> 
> class FooBar: Foo, IFooBar
> {
>     public string B {get;set;}
> }
> ```
> 
> > {"B":"Bar","A":"Foo"}
> > {"B":"Bar"}
> > {"A":"Foo"}
> > {"A":"Foo"}

Yes,this I would expect

**Comment by huoyaoyuan** [comment] 2021-02-26 04:34
Well, in this case your expectation is reasonable. I don't know about the design here.

**Comment by eiriktsarpalis** [comment] 2021-07-23 17:55
Duplicate of #41749.

**Closed by eiriktsarpalis** 2021-07-23 17:55 UTC
Labels: area-System.Text.Json, untriaged
