### ISSUE TITLE
Blazor WASM app with Timers / Async code and ClientWebSocket results in increasing CPU utilisation. 

### ISSUE THREAD

**Issue by m-chandler** [dotnet/runtime#62227] opened 2021-12-01 04:37 UTC
### Describe the bug

We had to abort our upgrade to NET6.0 due to performance concerns. The upgraded apps were using significantly higher CPU. I've finally gotten around to identifying the cause and replicating it in a sample project.

The symptom is increasing CPU utilisation throughout the day. We have multiple blazor apps which are run all day, so this is a noticable issue to us.

This appears to be caused by asyncronous code (e.g. System.Threading.Timer, async / await) being used whilst an active ClientWebSocket connection is open. When these two elements are in play a large number of calls are made to "Install Timer" in the browser, and this number increases logarithmically throughout the day. Note: I'm using the Chrome Performance tab to verify this; profiling for a short period of time and then searching for the number of calls to "Install Timer".

Say you had a component set up a timer to do something every 500ms:

```
    public partial class Index
    {
        private Timer _timer;

        public Index()
        {
            _timer = new System.Threading.Timer(_ =>
            {
                Console.WriteLine("In timer, doing stuff.");
            }, null, 0, 500);
        }
    }
```

Ignoring the fact that the timer is never diposed, the above code causes no issues. You can head into the Chrome Performance profiler (or whatever browser you prefer), and notice that there are a reasonable number of calls to "Install Timer". There's more than expected in my example beacuse I tried to turn off BrowserLink and failed, but I digress. 55 is a reasonable number.

![good-timers](https://user-images.githubusercontent.com/2039337/144173486-62413a35-fe2c-41ef-8195-c17ca0290dc8.png)

Now add on a ClientWebSocket Connection wrapped in a service:

```
    public class ApiService
    {
        public ApiService()
        {
            var websocket = new ClientWebSocket();
            Task.Run(async () =>
            {
                await websocket.ConnectAsync(
                    new Uri("wss://websocket-echo.glitch.me"),
                    CancellationToken.None);
                Console.WriteLine("Connected.");
            });
        }
    }
```

Again - ordinarily this code would be fine (and without the Timer in our component, it is fine). Unfortunately when both of the above snippets are used our System.Threading.Timer is now exhibiting serious performance issues.

Profiling the app for 10 seconds every minute results in the below number of calls to "Install Timer".
00:30:00->00:40:00: 422 calls.
01:30:00->01:40:00: 1548 calls.
02:30:00->02:40:00: 2823 calls.
03:30:00->03:40:00: 4023 calls.

4023 "Install Timer" calls over 10 seconds, for a Timer that does something every 500ms?

You can start to visually see the performance issue develop when comparing the below pic, execution times are quite a bit thicker than the previous example.

![bad-timers](https://user-images.githubusercontent.com/2039337/144173284-1d9df959-8e96-4e9e-8166-14ac5d35543b.png)

### To Reproduce
https://github.com/m-chandler/blazor-timers-net6.0

### Exceptions (if any)
N/A

### Further technical details
- ASP.NET Core version: NET 6.0
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version: VS 2022 Pro
- Include the output of `dotnet --info`:

<details>
  <summary>dotnet --info Output</summary>

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  5.0.302 [C:\Program Files\dotnet\sdk]
  5.0.403 [C:\Program Files\dotnet\sdk]
  6.0.100-rc.1.21463.6 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.1.21452.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.1.21451.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-rc.1.21451.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

</details>

**Comment by radical** [comment] 2021-12-01 07:02
cc @kg @vargaz @radekdoulik

**Comment by kg** [comment] 2021-12-01 16:23
@pavelsavara

**Comment by pavelsavara** [comment] 2021-12-01 17:51
It is probably related to my https://github.com/dotnet/runtime/pull/57745
I will try to reproduce and understand this issue.

**Comment by pavelsavara** [comment] 2021-12-01 18:02
I think that I will need to review this code in `PumpTimerQueue`

https://github.com/dotnet/runtime/blob/7ffc96e8591a3e115dbe828ef1c77c01751d32e2/src/mono/System.Private.CoreLib/src/System/Threading/TimerQueue.Browser.Mono.cs#L61

That should only execute those timers which are due already. Does it ?

**Comment by pavelsavara** [comment] 2021-12-05 16:20
I can reproduce it, thanks for the demo @m-chandler.

The `TimeoutCallback` in `TimerQueue.Browser.Mono.cs` is self-scheduling.
The problem is that it doesn't know/remember that it already scheduled "next tick" for particular timers and so, when I call it additionally from `prevent_timer_throttling` it will create another self-scheduling loop.

Luckily, it doesn't fire the Timers which are not due.

I'm working on it.

**Comment by pavelsavara** [comment] 2022-01-10 12:00
Should fixed by https://github.com/dotnet/runtime/pull/62705

**Closed by pavelsavara** 2022-01-10 12:00 UTC
Labels: arch-wasm, area-VM-meta-mono
