### ISSUE TITLE
WPF .exe published using PublishTrimmed fails to launch

### ISSUE THREAD

**Issue by lutzroeder** [dotnet/runtime#50689] opened 2021-04-03 20:39 UTC
### Description

When building a WPF .NET app using `<PublishTrimmed>` the resulting `.exe` fails to launch.

1. Run `dotnet new wpf -n TestApp`
2. Add to `TestApp.csproj`:
```xml
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishTrimmed>true</PublishTrimmed>
    <PublishReadyToRun>true</PublishReadyToRun>
```
3. Run `dotnet publish`
4. Run `bin\Debug\net5.0-windows\win-x64\publish\TestApp.exe`

```
Faulting application name: WpfApp5.exe, version: 1.0.0.0
Faulting module name: KERNELBASE.dll, version: 10.0.19041.804
Exception code: 0xe0434352
Faulting application path: [...]bin\Debug\net5.0-windows\win-x64\publish\TestApp.exe.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Faulting package full name: 
Faulting package-relative application ID: 
 
Application: TestApp.exe
CoreCLR Version: 5.0.421.11614
.NET Version: 5.0.4
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Windows.Markup.XamlParseException: The type initializer for 'System.Windows.Window' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.Windows.FrameworkElement' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.Windows.Documents.TextElement' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'System.Windows.Documents.Typography' threw an exception.
 ---> System.IO.FileNotFoundException: 
File name: 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

### Configuration

```
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  3.1.113 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.200 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]
```

@danmoseley

**Comment by ThomasGoulet73** [comment] 2021-04-04 02:39
You can use this in your csproj:
```
    <ItemGroup>
        <TrimmerRootAssembly Include="System.Diagnostics.Debug" /> 
        <TrimmerRootAssembly Include="System.Runtime" /> 
        <TrimmerRootAssembly Include="System.Runtime.Extensions" />          
    </ItemGroup>
```

**Comment by vitek-karas** [comment] 2021-04-04 19:20
This is basically a duplicate of https://github.com/dotnet/sdk/issues/14261 which was "moved" to the dotnet/wpf repo https://github.com/dotnet/wpf/issues/3811. Currently, by default, WPF apps are basically broken when trimmed. And even if that is fixed (https://github.com/dotnet/sdk/issues/14261 has some discussion how to do that), the size wins are not that good.

**Comment by eerhardt** [comment] 2021-04-06 23:39
@vitek-karas - can we close this as a duplicate of dotnet/wpf#3811?

**Comment by agocke** [comment] 2021-04-07 06:29
Yup, I think closing as a dup is correct. There's also a bug about adding a warning about trimming at https://github.com/dotnet/sdk/issues/16716

**Closed by agocke** 2021-04-07 06:29 UTC
Labels: area-AssemblyLoader-coreclr, linkable-framework, untriaged
