### ISSUE TITLE
TypeLoadException Using Covariant Return Types

### ISSUE THREAD

**Issue by JasonBock** [dotnet/runtime#42300] opened 2020-09-15 20:11 UTC
**Version Used**: 
5.0.100-rc.1.20452.10

**Steps to Reproduce**:
The repo is here: https://github.com/JasonBock/WhatsNewInCSharp9. Specifically, run the `DemonstrateCovariantReturnTypes()` method. Note that everything compiles successfully.

**Expected Behavior**:
The project runs and prints the `Id` and `Name` values.

**Actual Behavior**:
When I run it, I get this:
```
Unhandled exception. System.TypeLoadException: Could not load type 'WhatsNewInCSharp9.CustomPipeline' from assembly 'WhatsNewInCSharp9, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at <Program>$.<<Main>$>g__DemonstrateCovariantReturnTypes|0_5()
   at <Program>$.<Main>$(String[] args) in C:\Users\jason\source\repos\WhatsNewInCSharp9\WhatsNewInCSharp9\Program.cs:line 15
```

**Comment by am11** [comment] 2020-09-16 06:43
There were some fixes for covariant return in RC2. e.g. on macOS, your program returns `d7d4160b-5aab-4517-95be-8b6e9819bfe7, Jason` with `SDK: 5.0.100-rc.2.20459.18, HOST: 5.0.0-rc.2.20458.14`.

**Comment by mangod9** [comment] 2020-09-16 16:06
This is a possible dupe of https://github.com/dotnet/runtime/issues/41571. @janvorli ?

**Comment by janvorli** [comment] 2020-09-16 19:04
I have tested it with 5.0.100-rc.2.20466.4 SDK and it runs without issues, so I believe is it really dupe of #41571.

**Comment by mangod9** [comment] 2020-09-17 18:29
Closing as dupe of #41571 which is fixed in RC2. @JasonBock please reopen if this still repros for you on latest builds

**Closed by mangod9** 2020-09-17 18:29 UTC
Labels: area-TypeSystem-coreclr
