### ISSUE TITLE
NET46 System.DiagnosticSource 4.6.0 adds NETStandard System.Memory to the project

### ISSUE THREAD

**Issue by Dmitry-Matveev** [dotnet/runtime#745] opened 2019-12-10 22:45 UTC
@joperezr recently conducted an investigation of [Application Insights nuget package](https://www.nuget.org/packages/Microsoft.ApplicationInsights) installation into .NET 4.6.1 project on a set of the internal services where System.Net.Http FW dependency got replaced with NETStandard one from MSBuild Extensions folder upon AI nuget installation. Other services in the same solution/deployment didn't expect the change and failed to start properly at deployment time.

Jose was able to trace it through the dependency chain of NET46 nuget targets to [System.Memory](https://www.nuget.org/packages/System.Memory/) package that turned out to be NETStandard instead of NET46 upon installation.

The possible root cause is the fact that [System.DiagnosticSource 4.6.0](https://www.nuget.org/packages/System.Diagnostics.DiagnosticSource/4.6.0) package references NETStandard version of [System.Memory](https://www.nuget.org/packages/System.Memory/) even for NET46 installation target. That forces Visual Studio to apply possible fixes for Net Standard dependencies such as bringing in new System.Net.Http dependency for the given project.

Downgrading AI nuget packages to 2.10 that references System.DiagnosticSource 4.5.0 allowed to work around the issue and other services in the solution were able to start successfully upon deployment.

Can you please triage/fix the issue, so that onboarding internal services running .NET 4.6.1 onto AI packages does not break such services if they cannot move to 4.7 or package references?

**Comment by joperezr** [comment] 2019-12-10 23:02
cc: @ericstj 

The problem here is not really System.DiagnosticSource as that one does dual-target for net46, the problem is that it depends on System.Memory which doesn't dual target. This means that every application that targets .NET Framework (version <= 4.7.1) and wants to install only the ApplicationInsights package, will require all of the netstandard facades given that System.Memory targets .NET Standard 2.0. This could be mitigated if we service the System.Memory package in order to also have it dual-target, so that it won't require all of the facades at runtime. System.Memory package isn't built in master any longer, so the fix would need to happen on corefx repo in the release/2.1 branch. We have definitely gotten asks about this same scenario in the past, so I think it would be reasonable for us to fix it.

**Comment by Dmitry-Matveev** [comment] 2020-01-23 21:43
@joperezr , is there any action/justification we may provide on our side to affect the decision to propagate the fix into servicing milestones? It's currently under `Servicing-consider` and we are looking for ways to positively affect that consideration :)

**Comment by joperezr** [comment] 2020-01-23 21:47
We are actually currently working on this, not just for System.Memory, but for all packages that might use a dual-targetting. This effort is tracked by https://github.com/dotnet/runtime/issues/1625 so in fact we could close this specific one as a dupe of that one (except that one covers much more than just System.Memory). We have already done the costing of the work, and the justification seem to satisfy our team so the only thing left is to take it up to Shiproom and tactics who will evaluate this and make the final decision. We currently plan on doing that next week, so if approved, we will go ahead and do the work to release the new set of packages.

**Comment by danmosemsft** [comment] 2020-09-03 15:23
@ericst is this done now and we can close?

**Comment by joperezr** [comment] 2020-09-03 15:31
Yup, we serviced this in 3.1 plus we have it in 5.0 as well so we can close this. In fact I believe App Insights is already using the serviced package, right @Dmitry-Matveev @TimothyMothra ? We also added some regression tests for this so this shouldn’t happen again for any package that is supported in .net framework.

**Closed** 2020-09-03 15:32 UTC
Labels: Servicing-consider, area-System.Memory, enhancement, packaging
