### ISSUE TITLE
[API Proposal]: Add `WithIndex()` to Collections

### ISSUE THREAD

**Issue by robjakedorsett** [dotnet/runtime#102309] opened 2024-05-16 08:42 UTC
### Background and motivation

I would like to add a feature to Linq.

The feature is very simple, the rationale behind wanting this feature is that I tend to create an extension method for it on every project I work on as it's very helpful in scenarios where an index is required when iterating while still keeping the minimal syntax foreach provides.

### API Proposal

```csharp
namespace System.Linq;

public static partial class Enumerable
{
    public static IEnumerable<(TSource items, int index)> WithIndex<TSource>(this IEnumerable<TSource> source)
    {
          if (source == null)
                throw new ArgumentNullException(nameof(source));
          
          return source.Select((item, index) => (item, index));
    }
}
```

### API Usage

```csharp
// Fancy the value
var c = new List<int>();
c.Add(1);
c.Add(2);


// Getting the values out
foreach (var (v, index) in c.WithIndex())
    Console.WriteLine(index);
    Console.WriteLine(v);
```

### Risks

I don't think this would contain any risks to regression as this is an addition

**Comment by huoyaoyuan** [comment] 2024-05-16 09:14
Duplicate of #95563. The method has been approved and implemented for 9.0.

**Closed by huoyaoyuan** 2024-05-16 09:14 UTC
Labels: api-suggestion, area-System.Linq, untriaged
