### ISSUE TITLE
AOT 32-bits 

### ISSUE THREAD

**Issue by jssmotta** [dotnet/runtime#86558] opened 2023-05-21 18:35 UTC
We need AOT 32-bits to run side-by-side IIS pool 32-bit applications.
32bits compilation is 4 times faster than 64-bits and consumes much extra memory to do the same job.

**Comment by Wraith2** [comment] 2023-05-21 21:54
What is the source for your numbers?

**Comment by jssmotta** [comment] 2023-05-21 22:01
I have already made several tests in my ERP and CRM systems, using .NET 4.8 and .NET 6 and 7. In all environments, the 32 bits were faster. I installed it in production too to ensure that x64 consumes more memory and is slower than x86.

**Comment by Wraith2** [comment] 2023-05-21 22:08
Can you provide your benchmarks and results?

**Comment by NCLnclNCL** [comment] 2023-05-22 07:50
> Can you provide your benchmarks and results?

he's right, it's obvious because 64 bit uses more addresses than 32 bit and takes more ram, and 64 bit uses more cpu

**Comment by Wraith2** [comment] 2023-05-22 08:00
If it's that obvious then providing an example use case, benchmarks and numbers should be easy. 
If it is made clear that there is significant benefit to doing the work to allow and maintain 32 bit AOT then it may happen. Simply stating that it's better is not enough evidence.

**Comment by NCLnclNCL** [comment] 2023-05-22 08:27
> If it's that obvious then providing an example use case, benchmarks and numbers should be easy. If it is made clear that there is significant benefit to doing the work to allow and maintain 32 bit AOT then it may happen. Simply stating that it's better is not enough evidence.

but obviously only compile from iL to c++ code, while c++ has 32 bit linker why don't they do it

**Comment by Wraith2** [comment] 2023-05-22 09:11
Likely because there is no evidence that the effort required is a good investment. If you can provide evidence that it is both useful and worthwhile to expend resources in providing this functionality then it may get implemented. So, as i've asked repeatedly, can you provide a use-case, benchmarks, numbers?

**Comment by hez2010** [comment] 2023-05-22 09:12
> but obviously only compile from iL to c++ code, while c++ has 32 bit linker why don't they do it

Because NativeAOT is not working in this way which compiles IL to C++ code. The old il2cpp backend has been deprecated and dropped for years.

**Comment by NCLnclNCL** [comment] 2023-05-22 09:21
> > but obviously only compile from iL to c++ code, while c++ has 32 bit linker why don't they do it
> 
> Because NativeAOT is not working in this way which compiles IL to C++ code. The old il2cpp backend has been deprecated and dropped for years.

You need install c++ compile in vs 2022 to compile aot

**Comment by vitek-karas** [comment] 2023-05-22 09:52
> You need install c++ compile in vs 2022 to compile aot

It uses the platform linker from that package, but not the C++ compiler.

**Comment by katanakatana123** [comment] 2023-05-22 13:08
32 bit in c++ compile very fast

**Comment by jkotas** [comment] 2023-05-22 15:43
I assume you meant native AOT support for x86.

We (the core .NET runtime team) do not have plans to enable Windows x86 in near future. We are open to community contributions towards enabling it. See https://github.com/dotnet/runtime/issues/86573 for discussion about this.

Duplicate of https://github.com/dotnet/runtime/issues/86573

**Closed by jkotas** 2023-05-22 15:43 UTC
Labels: tenet-performance, untriaged, area-Codegen-AOT-mono
