### ISSUE TITLE
Test failure System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateShadowTest02

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#83316] opened 2023-03-13 01:06 UTC
Failed in Run: [runtime-coreclr libraries-jitstress2-jitstressregs 20230311.1](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=201383)
 
 **Failed tests:**
 ```
 net8.0-windows-Release-x64-CoreCLR_checked-jitstress2_jitstressregs3-Windows.10.Amd64.Open
     - System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateShadowTest02
 ```
 
 **Error message:**
 ```
 Matrix4x4.CreateShadow did not provide expected value.
Expected: True
Actual:   False
 ```
 
 **Stack trace:**
 ```
   at System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateShadowTest02() in /_/src/libraries/System.Numerics.Vectors/tests/Matrix4x4Tests.cs:line 762
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
 ```

**Comment by JulieLeeMSFT** [comment] 2023-03-14 11:28
@tannergooding PTAL.

**Comment by v-wenyuxu** [comment] 2023-05-15 01:21
**Failed again in:** [runtime-coreclr libraries-jitstress2-jitstressregs 20230513.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=272702&view=ms.vss-test-web.build-test-results-tab&runId=5384550&resultId=133565&paneView=debug)

**Failed tests:**
```
net8.0-windows-Release-x64-CoreCLR_checked-jitstress2_jitstressregs3-Windows.10.Amd64.Open
    - System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateShadowTest02
```

**Error message:**
```
 Matrix4x4.CreateShadow did not provide expected value.
Expected: True
Actual:   False
```

**Stack trace:**
```
    at System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateShadowTest02() in /_/src/libraries/System.Numerics.Vectors/tests/Matrix4x4Tests.cs:line 762
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
```



**Comment by BruceForstall** [comment] 2023-05-17 19:12
Still failing

https://dev.azure.com/dnceng-public/public/_build/results?buildId=277068&view=ms.vss-test-web.build-test-results-tab&runId=5495120&resultId=133658&paneView=debug

@kunalspathak This apparently only fails in JitStressRegs=3; maybe you should take a look?

**Comment by v-wenyuxu** [comment] 2023-05-29 01:29
**Failed again in:** [runtime-coreclr libraries-jitstress2-jitstressregs 20230527.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=288183&view=ms.vss-test-web.build-test-results-tab&runId=5753026&resultId=138288&paneView=debug)

**Failed tests:**
```
net8.0-windows-Release-x64-CoreCLR_checked-jitstress2_jitstressregs3-Windows.10.Amd64.Open
    - System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateShadowTest02
```

**Error message:**
```
 Matrix4x4.CreateShadow did not provide expected value.
Expected: True
Actual:   False
```

**Stack trace:**
```
   at System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateShadowTest02() in /_/src/libraries/System.Numerics.Vectors/tests/Matrix4x4Tests.cs:line 762
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
```

**Comment by v-wenyuxu** [comment] 2023-06-05 01:56
Failed again in: [runtime-coreclr libraries-jitstress2-jitstressregs 20230603.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=294529&view=ms.vss-test-web.build-test-results-tab&runId=5926668&resultId=126785&paneView=debug)

Failed test:
```
net8.0-windows-Release-x64-CoreCLR_checked-jitstress2_jitstressregs3-Windows.10.Amd64.Open

- System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateShadowTest02
```
**Error message:**
```
Matrix4x4.CreateShadow did not provide expected value.
Expected: True
Actual:   False



Stack trace
   at System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateShadowTest02() in /_/src/libraries/System.Numerics.Vectors/tests/Matrix4x4Tests.cs:line 762
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
```

**Comment by v-wenyuxu** [comment] 2023-06-12 01:20
**Failed again in:** [runtime-coreclr libraries-jitstress2-jitstressregs 20230610.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=302409&view=ms.vss-test-web.build-test-results-tab&runId=6131124&resultId=137536&paneView=debug)

**Failed tests:**
```
net8.0-windows-Release-x64-CoreCLR_checked-jitstress2_jitstressregs3-Windows.10.Amd64.Open
    - System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateShadowTest02
```

**Error message:**
```
 Matrix4x4.CreateShadow did not provide expected value.
Expected: True
Actual:   False
```

**Stack trace:**
```
    at System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateShadowTest02() in /_/src/libraries/System.Numerics.Vectors/tests/Matrix4x4Tests.cs:line 762
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
```



**Comment by BruceForstall** [comment] 2023-06-12 20:43
@tannergooding @kunalspathak Since this is only failing under JitStressRegs=3 I assigned it to Kunal.

**Comment by kunalspathak** [comment] 2023-06-21 17:39
Taking a look now.

**Comment by kunalspathak** [comment] 2023-06-22 02:14
The problematic code is the following:

```csharp
public void Matrix4x4CreateShadowTest02()
{
  if (lightDirInfo.Length() < 0.1f)
       continue;
  Vector3 lightDir = Vector3.Normalize(lightDirInfo);
 ...
 ...
}

[Intrinsic]
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public readonly float Length()
{
    float lengthSquared = LengthSquared();
    return MathF.Sqrt(lengthSquared);
}


[Intrinsic]
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static Vector3 Normalize(Vector3 value)
{
    return value / value.Length();
}
```

Here, we CSE `lightDirInfo.Length()` and store its value as `float`. In `Normalize()` when we reload the value, we reload the 64 bits float instead of 128 bits in xmm. That leads to incomplete vector getting loaded with few fields 0. This makes the division returning Nan.

```asm
G_M15576_IG58:  ;; offset=0187H
       vmovss   dword ptr [rsp+58H], xmm6
						;; size=6 bbWeight=16 PerfScore 16.00
G_M15576_IG59:  ;; offset=018DH
       vsqrtss  xmm7, xmm7, xmm6
						;; size=4 bbWeight=16 PerfScore 176.00
G_M15576_IG60:  ;; offset=0191H
       vmovss   xmm6, dword ptr [rsp+5CH]
						;; size=6 bbWeight=16 PerfScore 48.00
G_M15576_IG61:  ;; offset=0197H
       vucomiss xmm6, xmm7
						;; size=4 bbWeight=16 PerfScore 32.00
G_M15576_IG62:  ;; offset=019BH
       ja       G_M15576_IG166
						;; size=6 bbWeight=16 PerfScore 16.00
G_M15576_IG63:  ;; offset=01A1H
       vmovss   xmm7, dword ptr [rsp+58H]
						;; size=6 bbWeight=8 PerfScore 24.00
G_M15576_IG64:  ;; offset=01A7H
       vsqrtps  xmm7, xmm7
						;; size=4 bbWeight=8 PerfScore 88.00
G_M15576_IG65:  ;; offset=01ABH
       vdivps   xmm7, xmm2, xmm7
```


````
                                                                        ┌──▌  t719   simd16 
Generating: N269 (  3,  3) [000094] -----------                   t94 = ▌  HWINTRINSIC float  float ToScalar REG mm6 <l:$688, c:$689>
                                                                        ┌──▌  t94    float  
Generating: N271 (  3,  3) [000635] DA--------z                         ▌  STORE_LCL_VAR float  V62 cse4         d:1 mm6 REG mm6 $VN.Void
Saved:
      G_M15576_IG57:        ; offs=00012CH, size=0006H, bbWeight=16, BB09 [0002], extend
Created:
      G_M15576_IG58:        ; offs=000132H, size=0000H, bbWeight=16, gcrefRegs=0000 {}
Mapped BB09 to G_M15576_IG58
IN0039:        vmovss   dword ptr [V62 rsp+58H], xmm6

...
...
Generating: N287 (  1,  2) [000638] ----------z                  t638 =    LCL_VAR   float  V62 cse4         u:1 mm7 (last use) REG mm7 <l:$688, c:$689>
                                                                        ┌──▌  t638   float  
Generating: N289 (  2,  3) [000107] -----------                  t107 = ▌  HWINTRINSIC simd16 float Sqrt REG mm7 <l:$207, c:$208>
Mapped BB10 to G_M15576_IG63
IN003e:        vmovss   xmm7, dword ptr [V62 rsp+58H]
```

The `/` operator that takes `float` is:

```c#
       public static Vector3 operator /(Vector3 value1, float value2)
       {
            return value1 / new Vector3(value2);
       }

        [Intrinsic]
        public Vector3(float value) : this(value, value, value)
        {
        }

```

which seems that there are one or both the problems: 
1) the nodes that does the conversion of `value2` -> `Vector3(value2)`
2) we should not be CSEing the value directly.

Still investigating.

**Comment by kunalspathak** [comment] 2023-06-22 02:28
mostly caused by #81335

**Comment by tannergooding** [comment] 2023-06-22 04:38
Noting this comes down to a CSE of `HWINTRINSIC float float Dot` and `HWINTRINSIC TYP_SIMD12 float Dot`.

Need to determine why VN decides these can be CSE'd even though they have differing return types.

**Comment by sherlock-xu** [comment] 2023-06-25 01:26
**Failed again in:** [runtime-coreclr libraries-jitstress2-jitstressregs 20230624.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=319319&view=ms.vss-test-web.build-test-results-tab&runId=6546610&resultId=131027&paneView=debug)

**Failed tests:**
```
net8.0-windows-Release-x64-CoreCLR_checked-jitstress2_jitstressregs3-Windows.10.Amd64.Open
    - System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateShadowTest02
```

**Error message:**
```
 Matrix4x4.CreateShadow did not provide expected value.
Expected: True
Actual:   False
```

**Stack trace:**
```
    at System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateShadowTest02() in /_/src/libraries/System.Numerics.Vectors/tests/Matrix4x4Tests.cs:line 762
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
```



**Comment by v-wenyuxu** [comment] 2023-06-25 03:09
**Failed again in:** [runtime-coreclr libraries-jitstress2-jitstressregs 20230624.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=319319&view=ms.vss-test-web.build-test-results-tab&runId=6546610&resultId=131027&paneView=debug)

**Failed tests:**
```
net8.0-windows-Release-x64-CoreCLR_checked-jitstress2_jitstressregs3-Windows.10.Amd64.Open
    - System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateShadowTest02
```

**Error message:**
```
 Matrix4x4.CreateShadow did not provide expected value.
Expected: True
Actual:   False
```

**Stack trace:**
```
    at System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateShadowTest02() in /_/src/libraries/System.Numerics.Vectors/tests/Matrix4x4Tests.cs:line 762
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
```



**Comment by v-wenyuxu** [comment] 2023-07-03 01:24
**Failed again in:** [runtime-coreclr libraries-jitstress2-jitstressregs 20230701.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=327271&view=ms.vss-test-web.build-test-results-tab&runId=6739604&resultId=134156&paneView=debug)

**Failed tests:**
```
net8.0-windows-Release-x64-CoreCLR_checked-jitstress2_jitstressregs3-Windows.10.Amd64.Open
    - System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateShadowTest02
```

**Error message:**
```
Matrix4x4.CreateShadow did not provide expected value.
Expected: True
Actual:   False
```

**Stack trace:**
```
   at System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateShadowTest02() in /_/src/libraries/System.Numerics.Vectors/tests/Matrix4x4Tests.cs:line 762
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodInvoker.cs:line 59
```

**Closed** 2023-07-10 04:16 UTC
Labels: os-windows, JitStress, arch-x64, area-CodeGen-coreclr, blocking-clean-ci-optional
