### ISSUE TITLE
internal sealed class EnumConverter<T>.Read()

### ISSUE THREAD

**Issue by bobbyangers** [dotnet/runtime#63893] opened 2022-01-17 16:49 UTC
### Description

The Read method should consider the `_namingPolicy` when reading a value the source string;  as per the Write

```
internal sealed class EnumConverter<T>.Read()
{
   /* ...*/
 public override T Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            JsonTokenType token = reader.TokenType;

            if (token == JsonTokenType.String)
            {
                if (!_converterOptions.HasFlag(EnumConverterOptions.AllowStrings))
                {
                    ThrowHelper.ThrowJsonException();
                    return default;
                }

                return ReadAsPropertyNameCore(ref reader, typeToConvert, options);
            }
```

### Reproduction Steps

```
        [Test]
        public void When_reading_from_a_special_enum()
        {
             var query = from field in typeToConvert.GetFields(BindingFlags.Public | BindingFlags.Static)
                    let attr = field.GetCustomAttribute<EnumMemberAttribute>()
                    where attr != null
                    select (field.Name, attr.Value);
            var dictionary = query.ToDictionary(p => p.Item1, p => p.Item2);
 
            var json_settings = new JsonSerializerOptions
            {
                PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
                Converters = { new JsonStringEnumConverter(new DictionaryLookupNamingPolicy(dictionary, JsonNamingPolicy.CamelCase), allowIntegerValues) },
            };

            var data = @"{""value"": ""F""}";

            var result = JsonSerializer.Deserialize<DemoSpecial>(data, json_settings);

            ShowResult(result);
            result!.Value.Should().Be(SpecialEnum.First);

        }

        public class DemoSpecial
        {
            public SpecialEnum Value { get; set; }
        }

        public enum SpecialEnum
        {
            Unknown,
            [EnumMember(Value = "F")]
            First,
            [EnumMember(Value = "S")]
            Second,
            [EnumMember(Value = "T")]
            Third
        }

    public class JsonNamingPolicyDecorator : JsonNamingPolicy
    {
        readonly JsonNamingPolicy underlyingNamingPolicy;

        public JsonNamingPolicyDecorator(JsonNamingPolicy underlyingNamingPolicy) => this.underlyingNamingPolicy = underlyingNamingPolicy;

        public override string ConvertName(string name) => underlyingNamingPolicy == null ? name : underlyingNamingPolicy.ConvertName(name);
    }

    internal class DictionaryLookupNamingPolicy : JsonNamingPolicyDecorator
    {
        readonly Dictionary<string, string> dictionary;

        public DictionaryLookupNamingPolicy(Dictionary<string, string> dictionary, JsonNamingPolicy underlyingNamingPolicy) : base(underlyingNamingPolicy) => this.dictionary = dictionary ?? throw new ArgumentNullException(nameof(dictionary));

        public override string ConvertName(string name) => dictionary.TryGetValue(name, out var value) ? value : base.ConvertName(name);

    }

```

### Expected behavior

I have a `DictionaryLookupNamingPolicy`  that extract the `[EnumMember(Value="xx"]` from the Enum.

When writing values out, all good.

```
        public class DemoSpecial
        {
            public SpecialEnum Value { get; set; }
        }

        public enum SpecialEnum
        {
            Unknown,
            [EnumMember(Value = "F")]
            First,
            [EnumMember(Value = "S")]
            Second,
            [EnumMember(Value = "T")]
            Third
        }
```

When reading value from `{  "value": "F" }` it would expect to return a `DemoSpecial`.

### Actual behavior

Currently, it fails:

`The JSON value could not be converted to <namespace>.SpecialEnum. Path: $.value `

### Known Workarounds

Writing my own EnumConverter<T> and override the the `Read` method

**Comment by bobbyangers** [comment] 2022-01-17 16:58
In this function, should try and lookup the get the value from any `_namingPolicy` if not `null`
```
        internal override T ReadAsPropertyNameCore(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? enumString = reader.GetString();

            // Try parsing case sensitive first
            if (!Enum.TryParse(enumString, out T value)
                && !Enum.TryParse(enumString, ignoreCase: true, out value))
            {
                ThrowHelper.ThrowJsonException();
            }

            return value;
        }
```

**Comment by bobbyangers** [comment] 2022-01-17 18:38
```
internal T ReadAsPropertyNameCore(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        string enumString = reader.GetString();
        enumString = _namingPolicy?.ConvertName(enumString!);

        // Try parsing case sensitive first
        if (!Enum.TryParse(enumString, out T value)
            && !Enum.TryParse(enumString, ignoreCase: true, out value))
        {
            ThrowJsonException();
        }

        return value;
    }
```

**Comment by huoyaoyuan** [comment] 2022-01-18 13:26
Duplicate of #31619

**Comment by layomia** [comment] 2022-01-20 03:48
> Duplicate of #31619

Closing as dup.

**Closed by layomia** 2022-01-20 03:48 UTC
Labels: area-System.Text.Json, untriaged
