### ISSUE TITLE
System.Text.Json.SourceGeneration.Tests have issues with BigInteger and records on netfx

### ISSUE THREAD

**Issue by krwq** [dotnet/runtime#63802] opened 2022-01-14 18:08 UTC
Following issues were found when enabling netfx tests:

Whenever:
```
[JsonSerializable(typeof(ClassWithUnsupportedBigInteger))]
// and couple of other BigInteger related classes 
```

is used the code no longer compiles - code generator seem to be generating code which tries to access private fields. Search for `#if !NETFRAMEWORK` in that code - this have been removed for netfx for now to unblock remainder of the tests

also `JsonIgnoreAttribute_UnsupportedBigInteger` is not passing - expected exception seem to differ. See test with ActiveIssue.

Another issues I'm seeing are InvalidOperationException (emit fails in CreateAssemblyImage in the test code), following tests are affected:
- System.Text.Json.SourceGeneration.UnitTests.GeneratorTests.RecordInExternalAssembly
- System.Text.Json.SourceGeneration.UnitTests.GeneratorTests.Record
- System.Text.Json.SourceGeneration.Tests.JsonSerializerContextTests.Converters_AndTypeInfoCreator_NotRooted_WhenMetadataNotPresent (I'm not able to reproduce this one locally)

(those tests were recently added)

Related to: https://github.com/dotnet/runtime/issues/63463

cc: @layomia 

Note: this issue is related to the PR which is not merged yet so some details reated to ActiveIssue or DefineConstants are relevant after merging it. (I need ActiveIssue number in order to finish PR)

**Comment by eiriktsarpalis** [comment] 2023-06-15 19:47
The BigInteger failures were fixed by #87383 and the record unit tests are caused by the fact that netfx doesn't have the `IsExternalInit` class defined. I'll follow up with a PR enabling the tests and closing the issue.

**Closed** 2023-06-15 22:45 UTC
Labels: area-System.Text.Json, in-pr, source-generator
