### ISSUE TITLE
Test failure: System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_GetCounters 

### ISSUE THREAD

**Issue by JulieLeeMSFT** [dotnet/runtime#99135] opened 2024-03-01 00:45 UTC
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=583987&view=results
Build error leg or test failing: **System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_GetCounters**

Error Message:
```
C:\h\w\9F2F08E9\w\A2CA08BA\e>"C:\h\w\9F2F08E9\p\dotnet.exe" exec --runtimeconfig System.Diagnostics.PerformanceCounter.Tests.runtimeconfig.json --depsfile System.Diagnostics.PerformanceCounter.Tests.deps.json xunit.console.dll System.Diagnostics.PerformanceCounter.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Diagnostics.PerformanceCounter.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Diagnostics.PerformanceCounter.Tests (found 88 of 92 test cases)
  Starting:    System.Diagnostics.PerformanceCounter.Tests (parallel test collections = on [2 threads], stop on fail = off)
    System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_GetCounters [FAIL]
      System.InvalidOperationException : Category 'PerformanceCounterCategory_GetCounters_Category' does not exist.
      Stack Trace:
        /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterLib.cs(828,0): at System.Diagnostics.PerformanceCounterLib.GetCategorySample(String machine, String category)
        /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs(438,0): at System.Diagnostics.PerformanceCounterCategory.GetCounterInstances(String categoryName, String machineName)
        /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs(516,0): at System.Diagnostics.PerformanceCounterCategory.GetInstanceNames()
        /_/src/libraries/System.Diagnostics.PerformanceCounter/src/System/Diagnostics/PerformanceCounterCategory.cs(457,0): at System.Diagnostics.PerformanceCounterCategory.GetCounters()
        /_/src/libraries/System.Diagnostics.PerformanceCounter/tests/PerformanceCounterCategoryTests.cs(232,0): at System.Diagnostics.Tests.PerformanceCounterCategoryTests.PerformanceCounterCategory_GetCounters()
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
        /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs(57,0): at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by JulieLeeMSFT** [comment] 2024-03-01 00:45
@BruceForstall PTAL.

**Comment by jkotas** [comment] 2024-03-01 01:36
Duplicate of #90803

**Closed** 2024-03-07 00:13 UTC
Labels: area-CodeGen-coreclr, blocking-clean-ci-optional
