### ISSUE TITLE
.NET Core 3 Tasks do not work on Ubuntu 18.04 OpenVZ

### ISSUE THREAD

**Issue by Xenoage** [dotnet/runtime#2070] opened 2020-01-23 11:27 UTC
I noticed that Tasks in .NET Core 3 are not working on my Ubuntu 18.04 based virtual servers, running on OpenVZ virtualization.

Here is a very basic test program:

```
static async Task Main(string[] args) {
    Console.WriteLine("1");
    await Task.Delay(2000);
    Console.WriteLine("2");
    await Task.Delay(2000);
}
```

"2" is never printed.

Also `Threading.Timer` and `Timers.Timer` have similar problems, they almost never fire (sometimes, but very rarely, they do).

**Comment by jkotas** [comment] 2020-01-23 14:04
Duplicate of https://github.com/dotnet/coreclr/issues/26873 . This issue will be fixed in .NET Core 3.1.2 update.

**Closed by jkotas** 2020-01-23 14:04 UTC
Labels: area-System.Threading.Tasks, untriaged
