### ISSUE TITLE
Long running test: ResolutionsWaitingOnQueue_ResolutionStartCalledBeforeEnqueued

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#56449] opened 2021-07-28 08:11 UTC
Looks like recent regression on 7/26

Failures 7/8-7/28 (incl. PRs) -- all of them Mono Interpreter (from console log) on Debian.9.Amd64.Open:

Day | Run
-- | --
7/26 | PR #56271
7/27 | PR #56417
7/27 | PR #56424
7/27 | PR #56321
7/27 | PR #56224
7/27 | PR #53338
7/27 | PR #56379
7/27 | PR #56374
7/27 | Official run
7/27 | PR #56346
7/27 | PR #56346
7/27 | PR #56347
7/27 | PR #55849
7/27 | PR #55362
7/27 | PR #56334
7/27 | PR #56332
7/28 | PR #56430
7/28 | PR #56434
7/28 | Official run
7/28 | PR #56453

```
  Discovering: System.Net.NameResolution.Functional.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.NameResolution.Functional.Tests (found 56 of 63 test cases)
  Starting:    System.Net.NameResolution.Functional.Tests (parallel test collections = on, max threads = 2)
    System.Net.NameResolution.Tests.GetHostByNameTest.DnsObsoleteBeginEndGetHostByName_EmptyString_ReturnsHostName [SKIP]
      Test environment is not configured for this test to work.
    System.Net.NameResolution.Tests.GetHostByNameTest.DnsObsoleteGetHostByName_EmptyString_ReturnsHostName [SKIP]
      Test environment is not configured for this test to work.
    System.Net.NameResolution.Tests.GetHostEntryTest.Dns_GetHostEntry_DisableIPv6_ExcludesIPv6Addresses [SKIP]
      Condition(s) not met: "GetHostEntry_DisableIPv6_Condition"
    System.Net.NameResolution.Tests.GetHostEntryTest.Dns_GetHostEntryAsync_DisableIPv6_ExcludesIPv6Addresses [SKIP]
      Condition(s) not met: "GetHostEntry_DisableIPv6_Condition"
    System.Net.NameResolution.Tests.GetHostEntryTest.Dns_GetHostEntry_HostString_Ok [SKIP]
      Condition(s) not met: "GetHostEntryWorks"
    System.Net.NameResolution.Tests.GetHostEntryTest.Dns_GetHostEntryAsync_HostString_Ok [SKIP]
      Condition(s) not met: "GetHostEntryWorks"
   System.Net.NameResolution.Functional.Tests: [Long Running Test] 'System.Net.NameResolution.Tests.TelemetryTest.ResolutionsWaitingOnQueue_ResolutionStartCalledBeforeEnqueued', Elapsed: 00:02:11
   System.Net.NameResolution.Functional.Tests: [Long Running Test] 'System.Net.NameResolution.Tests.TelemetryTest.ResolutionsWaitingOnQueue_ResolutionStartCalledBeforeEnqueued', Elapsed: 00:04:11
   System.Net.NameResolution.Functional.Tests: [Long Running Test] 'System.Net.NameResolution.Tests.TelemetryTest.ResolutionsWaitingOnQueue_ResolutionStartCalledBeforeEnqueued', Elapsed: 00:06:11
   System.Net.NameResolution.Functional.Tests: [Long Running Test] 'System.Net.NameResolution.Tests.TelemetryTest.ResolutionsWaitingOnQueue_ResolutionStartCalledBeforeEnqueued', Elapsed: 00:08:11
   System.Net.NameResolution.Functional.Tests: [Long Running Test] 'System.Net.NameResolution.Tests.TelemetryTest.ResolutionsWaitingOnQueue_ResolutionStartCalledBeforeEnqueued', Elapsed: 00:10:11
   System.Net.NameResolution.Functional.Tests: [Long Running Test] 'System.Net.NameResolution.Tests.TelemetryTest.ResolutionsWaitingOnQueue_ResolutionStartCalledBeforeEnqueued', Elapsed: 00:12:11
   System.Net.NameResolution.Functional.Tests: [Long Running Test] 'System.Net.NameResolution.Tests.TelemetryTest.ResolutionsWaitingOnQueue_ResolutionStartCalledBeforeEnqueued', Elapsed: 00:14:11
```

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-56417-merge-1a35455b79e140a4a2/System.Net.NameResolution.Functional.Tests/console.f5167dbc.log?sv=2019-07-07&se=2021-08-16T22%3A09%3A27Z&sr=c&sp=rl&sig=tkQ0Zs4oqqd4jYfLCqOHaRDncjfQmS42yt9MGnIejCo%3D

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=1261893&view=ms.vss-test-web.build-test-results-tab&runId=37399536&resultId=187174&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

cc @dotnet/ncl

**Comment by karelz** [comment] 2021-07-28 08:47
@MihaZupan looks like Telemetry related. Any thoughts here?

**Comment by MihaZupan** [comment] 2021-07-28 09:42
This is a quite new test, but [every possible wait is behind a timeout](https://github.com/dotnet/runtime/blob/cf52b7e38d28b7e28358cee052effe0ed47efb2e/src/libraries/System.Net.NameResolution/tests/FunctionalTests/TelemetryTest.cs#L154). It should never hang.

Given that this is only hanging on the mono interpreter, I suspect it's an issue with the interpreter rather than the test/product.

**Comment by karelz** [comment] 2021-07-28 09:55
@MihaZupan do you have data how often it fails? Or was it just this one occurrence we are aware of?

@marek-safar to triage it for Mono interpreter ...

**Comment by MihaZupan** [comment] 2021-07-28 10:43
Looks like 18 times so far, consistently failing on `debian.9.amd64.open.rt` with interpreter.

**Comment by karelz** [comment] 2021-08-13 14:03
@marek-safar @steveisok @lewing can you please help to get this issue triaged for 6.0?

**Comment by lewing** [comment] 2021-08-20 18:28
@BrzVlad  can you triage the severity here?

cc @SamMonoRT

**Comment by BrzVlad** [comment] 2021-09-06 09:13
I can't reproduce this issue.

**Comment by BrzVlad** [comment] 2022-04-08 08:04
I expect this to be fixed by https://github.com/dotnet/runtime/pull/67663. Re-enabled the test

**Closed by BrzVlad** 2022-04-08 08:04 UTC
Labels: area-System.Net, disabled-test, runtime-mono
