### ISSUE TITLE
Logger Generator not able to Resolve Generic Type Constraints

### ISSUE THREAD

**Issue by matthawley** [dotnet/runtime#62026] opened 2021-11-24 20:20 UTC
### Description

When using the logger generator on an abstract class that defines a type constraint that is outside of the current scope, it will not compile correctly.

### Reproduction Steps

```
internal abstract partial class AzureHandlerBase<TRequirement> : AuthorizationHandler<TRequirement> 
        where TRequirement : IAuthorizationRequirement
{
    private readonly ILogger _logger;

    protected AzureHandlerBase(ILogger logger) {
        _logger = logger;
    }

    [LoggerMessage(1, LogLevel.Information, "Test")]
    private partial void LogIt();
}
```

### Expected behavior

The generated source code would allow the project to compile cleanly.

### Actual behavior

The errors produced are the following:

```
error CS0246: The type or namespace name 'IAuthorizationRequirement' could not be found (are you missing a using directive or an assembly reference?)
error CS0265: Partial declarations of 'AzureHandlerBase<TRequirement>' have inconsistent constraints for type parameter 'TRequirement'
```

### Regression?

Not that I'm aware of.

### Known Workarounds

Fully referencing the type constraint with namespaces allows it to compile:

```
internal abstract partial class AzureHandlerBase<TRequirement> : AuthorizationHandler<TRequirement> 
        where TRequirement : Microsoft.AspNetCore.Authorization.IAuthorizationRequirement
{
    private readonly ILogger _logger;

    protected AzureHandlerBase(ILogger logger) {
        _logger = logger;
    }

    [LoggerMessage(1, LogLevel.Information, "Test")]
    private partial void LogIt();
}
```

### Configuration

.NET 6
Windows 11

**Comment by martincostello** [comment] 2021-11-24 23:01
Possible dupe of #58550.

**Closed** 2021-11-25 01:37 UTC
Labels: untriaged, area-Extensions-Logging
