### ISSUE TITLE
Reusing the same SocketAsyncEventArgs for different udp remote endpoints does not work anymore

### ISSUE THREAD

**Issue by rmja** [dotnet/runtime#97965] opened 2024-02-05 11:10 UTC
### Description

It has been introduced in .NET 8 that the `_socketAddress` inside the `SocketAsyncEventArgs` is only serialized if it is null. This means that it is only serialized the first time the `SocketAsyncEventArgs` is used for a socket operation. However, e.g. in https://github.com/chronoxor/NetCoreServer/blob/master/source/NetCoreServer/UdpServer.cs#L692-L694 the `SocketAsyncEventArgs` is used multiple times for _different_ remote endpoints.

This is what is going on in .NET 8:
https://github.com/dotnet/runtime/blob/v8.0.1/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L3098-L3107

This is the previous same file in .NET 7:
https://github.com/dotnet/runtime/blob/v7.0.15/src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L3027

When comparing the two files, it seems that, if one changes the remote endpoint and calls e.g. `Socket.SendToAsync()` then it will not re-serialize the `_socketAddress` and the payload will not be transmitted to the socket address of the newly configured remote endpoint - instead they whill be transmitted to the first configured remote endpoint.

### Reproduction Steps

* Create a single instance of `var ea = SocketAsyncEventArgs`.
* Call `ea.RemoteEndPoint = firstEndpoint`.
* Call `socket.SendToAsync(ea)`.
* The data is correctly sent to `firstEndpoint`, now set a different remote endpoint `ea.RemoteEndpoint = secondEndpoint`
* Call `socket.SendToAsync(ea)`.
* The data is not sent `secondEndpoint` , it is sent to the old `firstEndpoint` which is clearly not correct.

### Expected behavior

It is expected that consequitive calls to e.g. `Socket.SendToAsync()` with the same instance of `SocketAsyncEventArgs` but with reconfigured `RemoteEndpoint`, actually transmits to different endpoints.

### Actual behavior

All consequitive calls to e.g. `Socket.SendToAsync()` are transmitted to the remote endpoint configured when `Socket.SendToAsync()` is first called. This is verified in wireshark.

### Regression?

This worked fine in .NET 7.

### Known Workarounds

I made the following PR in NetCoreServer in case the re-use of SocketAsyncEventArgs for different remote endpoints is in fact not legal, see: https://github.com/chronoxor/NetCoreServer/pull/284

**Comment by stephentoub** [comment] 2024-02-05 11:57
cc: @wfurt

**Comment by wfurt** [comment] 2024-02-05 17:31
I'll take a look.

**Comment by rmja** [comment] 2024-02-06 08:55
May I ask whether this was triaged to be a regression in .NET 8 or if the use of `SocketAsyncEventArgs` for different remote endpoints is a "too aggressive" optimization inside the `NetCoreServer` library? This would give some insight to whether https://github.com/chronoxor/NetCoreServer/pull/284 should be merged or not, and maybe with a specific .NET 8 "fix" as I can see that this is not added to a .NET 8 patch milestone.

**Comment by wfurt** [comment] 2024-02-07 21:02
it is certainly unintended regression @rmja and the linked code looks fine to me.  I should have PR up today to fix it. Once fixed and merged to main, we can reopen it for servicing request. I'm not sure what exact timing it would be.

**Comment by wfurt** [comment] 2024-03-13 16:25
reporting for backport

**Comment by gmeena** [comment] 2024-05-14 12:04
> it is certainly unintended regression @rmja and the linked code looks fine to me. I should have PR up today to fix it. Once fixed and merged to main, we can reopen it for servicing request. I'm not sure what exact timing it would be.

do we know when it will be available in 8.0.x? any approximation

**Comment by wfurt** [comment] 2024-05-14 16:06
the fix missed 8.0.5 by day or so ;(
It should be in next update around mid June.

**Comment by gmeena** [comment] 2024-05-14 19:21
> the fix missed 8.0.5 by day or so ;( It should be in next update around mid June.

:( we just updated our services to .NET 8 and found this issue, now in spot. Any workaround?

**Comment by wfurt** [comment] 2024-05-14 22:01
use fresh `SocketAsyncEventArgs` for each round or have one used based on the `RemoteEndPoint `

**Comment by gmeena** [comment] 2024-06-10 07:02
@wfurt Is this included in .NET 8.0.6 - May 28, 2024

**Comment by wfurt** [comment] 2024-06-10 16:32
no, my post had wrong version e.g. it missed 8.0.6 and it should be out mid June.

**Comment by wfurt** [comment] 2024-06-10 16:33
8.0 fixed by #99695. it should be out in 8.0.7

**Comment by karelz** [comment] 2024-06-24 17:46
Fixed in main (9.0) in PR #98134 and in 8.0.7 (July release) in PR #99695.

**Closed** 2024-06-24 17:46 UTC
Labels: bug, area-System.Net.Sockets, regression-from-last-release, in-pr
