### ISSUE TITLE
Test failure System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.AfterReadResponseServerError_ClientWrite

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#85233] opened 2023-04-24 01:14 UTC
**Failed in:** [runtime-coreclr libraries-jitstress 20230423.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=249046&view=ms.vss-test-web.build-test-results-tab&runId=4812602&resultId=196298&paneView=debug)

**Failed tests:**
```
net8.0-windows-Release-arm64-CoreCLR_checked-jitstress2_tiered-Windows.11.Arm64.Open
    - System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.AfterReadResponseServerError_ClientWrite
```

**Error message:**
```
 Assert.Throws() Failure
Expected: typeof(System.IO.IOException)
Actual:   (No exception was thrown)
```

**Stack trace:**
```
    at System.Net.Http.WinHttpHandlerFunctional.Tests.BidirectionStreamingTest.AfterReadResponseServerError_ClientWrite() in /_/src/libraries/System.Net.Http.WinHttpHandler/tests/FunctionalTests/BidirectionStreamingTest.cs:line 146
--- End of stack trace from previous location ---
```



**Comment by ManickaP** [comment] 2023-04-24 13:41
Based on Kusto data, we've getting this error sporadically for a while (oldest occurrence is from 12/22). It happens only on Windows Arm 64. It might be timing issue between receiving the RST frame and sending some data here, i.e. test bug:
https://github.com/dotnet/runtime/blob/018a9bd43851c998f9239aedf2fcc09c5eff7488/src/libraries/System.Net.Http.WinHttpHandler/tests/FunctionalTests/BidirectionStreamingTest.cs#L143-L146

Triage: moving to future, we can bump the priority if starts occurring more often.

**Comment by MihaZupan** [comment] 2023-05-22 12:33
Closing as duplicate of #86262 as that one already gets build-analysis updates on impacted PRs.

**Closed by MihaZupan** 2023-05-22 12:33 UTC
Labels: arch-arm64, area-System.Net.Http, os-windows, test-bug, JitStress
