### ISSUE TITLE
iOS (and other Apple platforms): System.Private.CoreLib.dll has P/Invokes to a libhostpolicy library that isn't shipped

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#38543] opened 2020-06-29 13:15 UTC
## Description

The System.Private.CoreLib.dll has P/Invokes to libhostpolicy:

```shell
$ monodis microsoft.netcore.app.runtime.ios-x64/5.0.0-preview.7.20317.2/runtimes/ios-x64/native/System.Private.CoreLib.dll | grep libhostpolicy
.module extern 'libhostpolicy'
    .method assembly static hidebysig pinvokeimpl ("libhostpolicy" as "corehost_resolve_component_dependencies" autochar cdecl )
    .method assembly static hidebysig pinvokeimpl ("libhostpolicy" as "corehost_set_error_writer" autochar cdecl )
```

But there's no libhostpolicy library in the Microsoft.NETCore.Runtime.ios-x64 nuget (nor are these native functions provided by any other library that I can find).

### Other information

It's highly preferable to not have any P/Invokes to native functions that don't exist, because it allows the AOT compiler to generate more efficient code. It also makes other performance improvements possible.

**Comment by marek-safar** [comment] 2020-06-30 06:35
@rolfbjarne this should not matter a lot as they will be removed by illinker

@CoffeeFlux would be nice to clean this up

**Comment by rolfbjarne** [comment] 2020-06-30 08:09
> @rolfbjarne this should not matter a lot as they will be removed by illinker

The linker won't always be enabled, in particular for simulator builds.

There's another complication here, because sometimes we have to ask the native linker to keep the native symbols P/Invokes point to (because otherwise the native linker may remove them, if those symbols come from static libraries). The problem is that if there are P/Invokes to native functions that don't exist, we can't ask the native linker to keep them, because then the native linker will fail. This means we'll have to add code to inspect all the static libraries we link with, compute a list of all the native symbols, and match with the symbols P/Invokes point to, to avoid asking the native linker to keep native symbols that don't exist.

**Comment by spouliot** [comment] 2021-04-07 12:53
Still present with P3

```
$ monodis tests//dotnet/packages/microsoft.netcore.app.runtime.iossimulator-x64/6.0.0-preview.3.21201.4/runtimes/iossimulator-x64/native/System.Private.CoreLib.dll | grep libhostpolicy
.module extern 'libhostpolicy'
    .method assembly static hidebysig pinvokeimpl ("libhostpolicy" as "corehost_resolve_component_dependencies" autochar cdecl )
    .method assembly static hidebysig pinvokeimpl ("libhostpolicy" as "corehost_set_error_writer" autochar cdecl )
```

**Comment by vitek-karas** [comment] 2021-04-07 19:20
The existing implementation of `AssemblyDependencyResolver` is intended only for cases where the runtime is loaded via `hostpolicy` (so even things like `corerun` will not work here - and that is currently by design).

On platforms where we don't use `hostpolicy` the implementation of this class should be different - depending on the platform/deployment behavior. The functional definition of the class is pretty simple: "Here's a path to plugin.dll - figure out where its dependencies are located" - it's meant as a good way to implement `AssemblyLoadContext.Load` method logic basically.

I would imagine that on mobile, we might just throw - as dynamically loaded plugins with dependency resolution may not be a thing (or are not common enough to invest into implementing some standard behavior).

On CoreCLR proper - the class parses the `.deps.json` next to the `plugin.dll` and resolves dependencies based on that. The simplest way to implement that was to call into `hostpolicy` which already has all the logic to do so. It was a deliberate decision to not support anything else at that time. (For example this class doesn't work from `corerun` which doesn't use `hostpolicy`)

**Comment by MaximLipnin** [comment] 2021-06-25 06:18
Addressed in https://github.com/dotnet/runtime/pull/54601

**Closed by MaximLipnin** 2021-06-25 06:18 UTC
Labels: area-CoreLib-mono, os-ios
