### ISSUE TITLE
API Proposal: Add BigEndian APIs to BinaryWriter and BinaryReader

### ISSUE THREAD

**Issue by Bunnui** [dotnet/runtime#77736] opened 2022-11-01 17:59 UTC
It is recommended that BinaryWriter and BinaryReader add support for large terminal read/write methods

**Comment by stephentoub** [comment] 2022-11-01 18:06
@Bunnui, is this an API request?  Can you provide more details?  I don't understand what this issue is.

**Comment by Bunnui** [comment] 2022-11-01 18:22
> @Bunnui, is this an API request? Can you provide more details? I don't understand what this issue is.

由于平台的原因，当与Java后端通信时，C#没有提供一种在流和二进制封装中对大端进行读写的方法。虽然我可以通过反转数组来转换Byte endian，但我看到BinaryPrimitives有用于大端的方法。在BinaryWriter和BinaryReader中，仅提供LittleEndian读写方法，但没有BigEndian处理方法。这样，我就不能放弃这个类并实现流读写的大小写转换。

proposal
System.IO.BinaryReader
System.IO.BinaryWriter
Add support for big end read/write methods

**Comment by Bunnui** [comment] 2022-11-01 18:27
Because my English is not good, it is translated by machine, so maybe the words look strange, please forgive me!

**Comment by Bunnui** [comment] 2022-11-01 19:08
> @Bunnui，这是 API 请求吗？你能提供更多细节吗？我不明白这个问题是什么。

![image](https://user-images.githubusercontent.com/37466008/199314641-a0cd4f93-4f01-40d9-ade9-8331cf4c75dd.png)

![image](https://user-images.githubusercontent.com/37466008/199316126-162aca05-e16a-4fc7-968b-3e5d66f9eef3.png)

![image](https://user-images.githubusercontent.com/37466008/199316464-9756393b-6131-40a3-bd74-a37289096e8d.png)

Something like this, if the server is using Little Endian, BinaryReader, BinaryWriter is convenient, if the server is using big endian they become a nuisance.

The ReadString method also passes in the ReadByteLength,Encoding argument instead of the initial Encoding in the constructor, because it is possible to receive a different encoding

**Comment by Jozkee** [comment] 2023-01-23 16:25
@Bunnui I think this can be closed as duplicate of https://github.com/dotnet/runtime/issues/26904.

**Closed by Jozkee** 2023-01-23 16:25 UTC
Labels: api-suggestion, area-System.IO
