### ISSUE TITLE
Building libs.src causes build errors

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#52622] opened 2021-05-11 21:34 UTC
After building the full repo, for example `.\build.cmd clr+libs -rc Release`, making some code changes, and calling `.\build.cmd -s Libs.src` can fail with errors like the following:

```
C:\Users\eerhardt\.nuget\packages\microsoft.dotnet.build.tasks.targetframework.sdk\6.0.0-beta.21222.1\build\BinPlace.targets(37,5): error MSB3026: Could not copy "C:\git\runtime\artifacts\bin\System.Collections\ref\net6.0-Debug\System.Collections.dll" to "C:\git\runtime\artifacts\bin\ref\net6.0\System.Collections.dll". Beginning retry 1 in 1000ms. The requested operation cannot be performed on a file with a user-mapped section open. : 'C:\git\runtime\artifacts\bin\ref\net6.0\System.Collections.dll'  [C:\git\runtime\src\libraries\System.Collections\ref\System.Collections.csproj]
C:\Users\eerhardt\.nuget\packages\microsoft.dotnet.build.tasks.targetframework.sdk\6.0.0-beta.21222.1\build\BinPlace.targets(37,5): error MSB3026: Could not copy "C:\git\runtime\artifacts\bin\System.Collections\ref\net6.0-Debug\System.Collections.dll" to "C:\git\runtime\artifacts\bin\ref\net6.0\System.Collections.dll". Beginning retry 2 in 1000ms. The requested operation cannot be performed on a file with a user-mapped section open. : 'C:\git\runtime\artifacts\bin\ref\net6.0\System.Collections.dll'  [C:\git\runtime\src\libraries\System.Collections\ref\System.Collections.csproj]
C:\Users\eerhardt\.nuget\packages\microsoft.dotnet.build.tasks.targetframework.sdk\6.0.0-beta.21222.1\build\BinPlace.targets(37,5): error MSB3026: Could not copy "C:\git\runtime\artifacts\bin\System.Resources.Writer\ref\net6.0-Debug\System.Resources.Writer.dll" to "C:\git\runtime\artifacts\bin\ref\net6.0\System.Resources.Writer.dll". Beginning retry 1 in 1000ms. The requested operation cannot be performed on a file with a user-mapped section open. : 'C:\git\runtime\artifacts\bin\ref\net6.0\System.Resources.Writer.dll'  [C:\git\runtime\src\libraries\System.Resources.Writer\ref\System.Resources.Writer.csproj]
C:\Users\eerhardt\.nuget\packages\microsoft.dotnet.build.tasks.targetframework.sdk\6.0.0-beta.21222.1\build\BinPlace.targets(37,5): error MSB3026: Could not copy "C:\git\runtime\artifacts\bin\System.Collections.Concurrent\ref\net6.0-Debug\System.Collections.Concurrent.dll" to "C:\git\runtime\artifacts\bin\ref\net6.0\System.Collections.Concurrent.dll". Beginning retry 1 in 1000ms. The requested operation cannot be performed on a file with a user-mapped section open. : 'C:\git\runtime\artifacts\bin\ref\net6.0\System.Collections.Concurrent.dll'  [C:\git\runtime\src\libraries\System.Collections.Concurrent\ref\System.Collections.Concurrent.csproj]
C:\Users\eerhardt\.nuget\packages\microsoft.dotnet.build.tasks.targetframework.sdk\6.0.0-beta.21222.1\build\BinPlace.targets(37,5): error MSB3026: Could not copy "C:\git\runtime\artifacts\bin\System.Security.Cryptography.X509Certificates\ref\net6.0-Debug\System.Security.Cryptography.X509Certificates.dll" to "C:\git\runtime\artifacts\bin\ref\net6.0\System.Security.Cryptography.X509Certificates.dll". Beginning retry 1 in 1000ms. The requested operation cannot be performed on a file with a user-mapped section open. : 'C:\git\runtime\artifacts\bin\ref\net6.0\System.Security.Cryptography.X509Certificates.dll'  [C:\git\runtime\src\libraries\System.Security.Cryptography.X509Certificates\ref\System.Security.Cryptography.X509Certificates.csproj]
```

1. `.\build.cmd clr+libs -rc Release`
2. touch `src\libraries\System.Runtime\ref\System.Runtime.cs` by adding whitespace to the file
3. `.\build.cmd -s Libs.src`

Note: a workaround seems to be running `.\build.cmd -s libs.ref+libs.src` instead.

We should figure out what the race condition is here and fix it so `.\build.cmd -s Libs.src` works correctly.

cc @vitek-karas @joperezr @ViktorHofer

**Comment by joperezr** [comment] 2021-05-12 17:22
@ViktorHofer this sounds like an issue perhaps introduced when we moved to restore src projects? It's wierd that the issue seems to be that something is locking the ref project's output when you are building the src which in theory should be building against a pre-built targeting pack.

**Comment by ViktorHofer** [comment] 2021-05-12 18:49
The src project builds the ref project as well: https://github.com/dotnet/runtime/blob/87e65109cd85c033c90a30d4d4ca488400b8f2b3/eng/resolveContract.targets#L15-L19.

I believe the split between ref.proj and src.proj doesn't make sense these days anymore, especially as we are driving towards generating the reference assembly automatically and incrementally as part of the src project's build. It sounds like merging this will fix the sporadic race conditions. It would be great if I could get a binlog to look at this further though.

Another request that was made which is related is that people don't want to build oob projects when building libs. I was thinking of removing the notion of ref and src by changing the existing subsets (and underlying projects) to libs.sfx and libs.oob.

Thoughts?

**Comment by joperezr** [comment] 2021-05-12 19:15
That is a good idea, do we have an issue for that?

Regarding this issue though, I don’t think this are actually “sporadic” failures as I believe @vitek-karas was hitting this more often than not, and having to build more than one subset is less than ideal. So unless we plan on removing ref projects in the short term, I would suggest fixing this sooner rather than later. Especially since this is a regression from when we built against a targetting pack.

**Comment by ViktorHofer** [comment] 2021-05-12 19:28
> Especially since this is a regression from when we built against a targetting pack.

What do you mean by that? Did you mean refpath? We never built against a targeting pack. We built against a refpath which is very different from a targeting pack.

> having to build more than one subset is less than ideal. So unless we plan on removing ref projects in the short term

As said, reference projects are already built incrementally as part of the src project's build. I believe we should remove these old subsets short term, probably bundled together with the next infra rollout. I'm already assigned to the issue and will work on that.

> as I believe @vitek-karas was hitting this more often than not

@vitek-karas do you have a binlog handy so that I can look more closely into the race conditions?

**Comment by vitek-karas** [comment] 2021-05-12 21:09
@ViktorHofer I sent you email with the binlog.

The repro is what Eric mentioned above. Clean build everything. Touch one of the ref source files (for example System.Runtime.cs), and run `build -s Lib.Src`. It is basically guaranteed to fail (at least on my machine).

**Comment by joperezr** [comment] 2021-05-13 04:09
> What do you mean by that? Did you mean refpath? We never built against a targeting pack. We built against a refpath which is very different from a targeting pack.

Yes, I meant refpath. Internally we also referred to them as targeting packs, even though they were not the same targeting packs that we mean when talking about .NET Framework.

Even if we remove the subset, it would be interesting to find out the race condition source, as that probably means that we have a problem with the way that we reference the ref projects from the src projects or perhaps have different global properties causing bin clashes, so it might be worth taking a look.

**Comment by ViktorHofer** [comment] 2021-05-14 19:52
> Even if we remove the subset, it would be interesting to find out the race condition source, as that probably means that we have a problem with the way that we reference the ref projects from the src projects or perhaps have different global properties causing bin clashes, so it might be worth taking a look.

Agreed, which is why I asked for the binlog :) Already took a look but not yet sure what's going on.

**Comment by ViktorHofer** [comment] 2021-09-03 09:20
Closing as I haven't seen this again. This was probably mitigated with the removal of the default netstandard.dll reference in source assemblies which caused them to rebuild every time.

**Closed by ViktorHofer** 2021-09-03 09:20 UTC
Labels: area-Infrastructure-libraries
