### ISSUE TITLE
RegEx support for ranges outside of Basic Multilingual Plane

### ISSUE THREAD

**Issue by rampaa** [dotnet/runtime#79865] opened 2022-12-20 19:01 UTC
Currently we can easily create regexes that can check ranges within [BMP](https://en.wikipedia.org/wiki/Plane_(Unicode)#Basic_Multilingual_Plane) like:

```
Regex bmpRegex = new(@"[\u0000-\uffff]");
```

But the same cannot be done for non-BMP ranges, the following won't work:
```
Regex cjkUnifiedIdeographsExtensionBRegex= new(@"[\u20000-\u2a6df]");
```

Admittedly, there is a [workaround](https://stackoverflow.com/a/47627127) but it's just way too inconvenient.

Suggestion:
Allow non-BMP ranges in regex, maybe with a new escape sequence like `\U`:
```
Regex cjkUnifiedIdeographsExtensionBRegex= new(@"[\U20000-\U2A6DF]");
```

**Comment by svick** [comment] 2022-12-20 23:02
This looks like a duplicate of https://github.com/dotnet/runtime/issues/64519, which was closed with:

> This is a known design / limitation of Regex that's existed since it was added, and there are currently no plans to improve that.

**Comment by buyaa-n** [comment] 2022-12-21 17:39
Closing by design as @svick mentioned

**Closed by buyaa-n** 2022-12-21 17:39 UTC
Labels: area-System.Text.RegularExpressions, untriaged

**Comment by rampaa** [comment] 2022-12-21 17:58
To be pedantic, `Regex cjkUnifiedIdeographsExtensionBRegex= new(@"[\u20000-\u2a6df]");` does not give the `[x-y] range in reverse order` error, it just does not work as one may expect, as explained in https://github.com/dotnet/runtime/issues/78609#issuecomment-1321303151. If I am not misunderstanding the comment (I totally might be), it suggests that "\U0001D468" is a valid syntax but VS complains \U is an unrecognized escape sequence.

Anyway, I think it's such a shame that .NET won't let us conveniently use regexes for a huge part of the Unicode standard. I'd have really hoped that there would be at least _some_ interest in fixing this in the future, but welp, I guess.

**Comment by svick** [comment] 2022-12-21 19:36
@rampaa 

Those are not regex escape sequences, they're C# escape sequences, i.e. it should be just `"[\u20000-\u2a6df]"`.

And the "correct" version, `"[\U00020000-\U0002a6df]"` does produce the range in reverse order error.

**Comment by rampaa** [comment] 2022-12-21 21:01
@svick Thanks! I knew that I was missing something obvious about the syntax.

It's still a shame that "fixing" the current behavior is not considered at all though.
