### ISSUE TITLE
Add the IAction***, IFunc*** abstractions and make C# automatically inherit them by delegates

### ISSUE THREAD

**Issue by dmitriyse** [dotnet/runtime#34552] opened 2020-04-05 00:19 UTC
Instantiated delegates are not interchangeable even if they have compatible signatures.
In performance-critical methods this causes small performance leaks:
```CSharp
using System;
using System.Threading;

namespace TheProblem
{
    public class Foo
    {
        public void RunOnMyThread(Action<object> action, object obj)
        {
            // error CS1503: Argument 1: cannot convert from 'System.Action<object>' to 'System.Threading.WaitCallback'
            // ThreadPool.QueueUserWorkItem(action, obj);

            // To avoid the error we needs to make a delegate conversion:
            // PERFORMANCE CRITICAL METHOD.
            ThreadPool.QueueUserWorkItem(
                state => ((Action)state)(), // Optimized to a singleton 
                (Action)(() => action(obj))); // Creates new delegate instance on each call 
            //(PERFORMANCE LEAK !)
        }
    }
}
```
To avoid this, C# languages and the Base Class Library could be improved:

``` CSharp
namespace Improvement
{
    // Introducing new family of contracts IAction***, IFunc***
    public interface IAction<in T1>
    {
        void Invoke(T1 arg1);
    }

    // Improving C# to automatically inherit appropriate contract from the IAction***, IFunc*** family,
    // Generated by the compiler from the "delegate void Action<in T1>(T1 arg1)"
    public class Action<T1> : /*Delegate,*/ IAction<T1> 
    {
        public void Invoke(T1 arg1)
        {
            // Compiled as IL instruction to call the target
        }
    }

    // Improving C# to automatically inherit appropriate contract from the IAction***, IFunc*** family,
    // Generated by the compiler from the "delegate void WaitCallback(object state);"
    public class WaitCallback : /*Delegate,*/ IAction<object>
    {
        public void Invoke(object arg1)
        {
            // Compiled as IL instruction to call the target
        }
    }

    public static class ThreadPool
    {
        // Adding new signatures to the BCL
        public static void QueueUserWorkItem<TWaitCallback>(TWaitCallback callback, object state)
            where TWaitCallback: IAction<object>
        {
            // Implementation
            
            callback.Invoke(state); // Transformed to IL instruction

            // Implementation
        }
    }

    public class Foo
    {
        public void RunOnMyThread(Action<object> action, object obj)
        {
            // After this improvement, we can directly pass any delegate with the Action<object> signature.
            // No Performance leak!
            ThreadPool.QueueUserWorkItem(action, obj);
        }
    }
}
```

Additional benefits of the proposed feature:
```CSharp
    // Not only delegates can benefits from IAction*** , IFunc*** contracts family.
    public class MyWorkItem : IAction<object>
    {
        public void Invoke(object arg1)
        {
            // Do my work
        }
    }

    public class Bar
    {
        public void RunOnMyThread(MyWorkItem workItem)
        {
            // No conversion required!
            ThreadPool.QueueUserWorkItem(workItem, null);

            // Previously it wasn't possible:
            // Argument 1: cannot convert from 'Improvement.MyWorkItem' to 'System.Threading.WaitCallback'
            //ThreadPool.QueueUserWorkItem(workItem, null);
        }
    }

```
Moved from https://github.com/dotnet/csharplang/issues/3336

**Comment by jkotas** [comment] 2020-04-05 03:01
This proposal would introduce an abstraction redundant with delegates. To make this actually work, we would need to duplicate many APIs that take delegate and introduce a second version of them that take this interface.

If we were to do something about this, https://github.com/dotnet/runtime/issues/4331 seems to be more promising approach.

Closing as duplicate of https://github.com/dotnet/runtime/issues/4331

**Closed by jkotas** 2020-04-05 03:01 UTC
Labels: untriaged

**Comment by jkotas** [comment] 2020-04-05 03:07
BTW: Do you have any numbers that show how much overhead would this proposal save for your `ThreadPool.QueueUserWorkItem` example? I believe that it would be in the noise range (assuming that you take advantage of the generic `QueueUserWorkItem<TState>` overload).

**Comment by davidfowl** [comment] 2020-04-05 03:08
There’s also a new overload of UnsafeQueueUserWorkItem that takes an IThreadPoolWorkItem

**Comment by dmitriyse** [comment] 2020-04-08 22:13
> BTW: Do you have any numbers that show how much overhead would this proposal save for your ThreadPool.QueueUserWorkItem example? I believe that it would be in the noise range (assuming that you take advantage of the generic QueueUserWorkItem<TState> overload for the baseline implementation).

@jkotas , unfortunately I am too far right now from a full solution benchmarks.
```QueueUserWorkItem``` and ```UnsafeQueueUserWorkItem``` was just an example where BCL authors decided that "delegates conversion and capturing" should be optimized.
I am writing a general-purpose library, I don't know will my methods would performance-critical or not for certain consumers. But I want to identify and use a "standard best practice" approach.
