### ISSUE TITLE
Test timeout: BeginReceiveFromV6BoundToSpecificV6_Success

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#58452] opened 2021-08-31 17:46 UTC
Test type: `System.Net.Sockets.Tests.DualModeConnectionlessBeginReceiveFrom`

Failures **2021/3/12-8/31** (incl. PRs):

Day | Run | OS
-- | -- | --
7/13 | Official run | Alpine.312.Amd64.Open
7/22 | Official run - release/6.0-preview6 | SLES.12.Amd64.Open
7/30 | Official run | Debian.9.Arm32.Open - arm
8/11 | Official run | Windows.10.Amd64.ServerRS5.Open - x86
8/16 | Official run | Windows.10.Amd64.ServerRS5.Open - x86
8/28 | Official run - release/6.0 | Debian.10.Amd64.Open
8/31 | Official run | Windows.10.Amd64.Server19H1.Open

Failure:
```
System.TimeoutException : The operation has timed out.

   at System.Net.Sockets.Tests.DualModeConnectionlessBeginReceiveFrom.BeginReceiveFrom_Helper(IPAddress listenOn, IPAddress connectTo, Boolean expectedToTimeout) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 1612
   at System.Net.Sockets.Tests.DualModeConnectionlessBeginReceiveFrom.BeginReceiveFromV6BoundToSpecificV6_Success() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 1539
```

**Comment by wfurt** [comment] 2022-05-10 22:07
this looks pretty old. Do we have any recent failures @rzikm?

**Comment by karelz** [comment] 2022-07-19 14:33
Triage: @antonfirsov please look at failure history. If it is not frequent, we should punt it into Future or 8.0 (based on frequency).

**Comment by rzikm** [comment] 2022-07-21 09:59
I don't see any recent failures, so we can probably close this.

**Comment by karelz** [comment] 2022-07-21 10:06
I see only 2 failures (incl. PRs) which passed on rerun:

Failures 2022/3/27-7/21 (incl. PRs):
Day | Failure | Run | OS
-- | -- | -- | --
4/16 | PassedOnRerun | Official | Debian.11.Arm32.Open
5/18 | PassedOnRerun | Official | Windows.11.Amd64.ClientPre.Open

```kusto
let failedTests = (methodName : string, includePR : bool, messageSubstr: string, includePassedOnRerun : bool) {
cluster('engsrvprod.kusto.windows.net').database('engineeringdata').AzureDevOpsTests
    | where TestName startswith "System.Net" 
        and includePassedOnRerun or (Outcome == 'Failed')
    | extend startOfTestName = indexof_regex(TestName, @"[^.]+$")
    | extend Method = substring(TestName, startOfTestName)
    | extend Type = substring(TestName, 0, startOfTestName - 1)
    | project-away startOfTestName
    | where Method == methodName
    | where Message contains messageSubstr
    | distinct JobId, WorkItemId, Message, StackTrace, Method, Type, Arguments, Outcome
    | join kind=inner (cluster('engsrvprod.kusto.windows.net').database('engineeringdata').Jobs
        | where ((Branch == 'refs/heads/main') or (Branch == 'refs/heads/master') or (includePR and (Source startswith "pr/")))
        | where Type startswith "test/functional/cli/"
            and not(Properties contains "runtime-staging")
        | summarize arg_max(Finished, Properties, Type, Branch, Source, Started, QueueName) by JobId
        | project-rename JobType = Type) on JobId
    | extend PropertiesJson = parse_json(Properties)
    | extend OS = replace_regex(tostring(PropertiesJson.operatingSystem), @'\((.*)\).*|([^\(].*)', @'\1\2')
    | extend Runtime = iif(PropertiesJson.runtimeFlavor == "mono", "Mono", iif(PropertiesJson.DefinitionName contains "coreclr", "CoreCLR", ""))
    | extend TargetBranch = extractjson("$.['System.PullRequest.TargetBranch']", Properties)
    | extend Architecture = PropertiesJson.architecture
    | extend Scenario = iif(isempty(PropertiesJson.scenario), "--", PropertiesJson.scenario)
    //| extend DefinitionName = PropertiesJson.DefinitionName
    | project-away PropertiesJson
};
failedTests('BeginReceiveFromV6BoundToSpecificV6_Success', true, '', true);
```

**Comment by karelz** [comment] 2022-07-21 10:06
Given the low frequency, moving to Future.

**Comment by antonfirsov** [comment] 2022-07-21 11:13
I see only one failure this year. We may close this, or address it together with #58452. The root cause might be related.

**Comment by wfurt** [comment] 2023-01-25 17:48
triage: we should look for recent failures and close if it looks stable.

**Comment by antonfirsov** [comment] 2023-02-01 16:14
No failures in last 15 days (can't query timeouts for longer period). #80715 should improve these tests. Closing for now, if it comes back, we can reopen.

**Closed by antonfirsov** 2023-02-01 16:14 UTC
Labels: area-System.Net.Sockets, test-run-core
