### ISSUE TITLE
PooledByteBufferWriter or similar as .net first class citizen?

### ISSUE THREAD

**Issue by MithrilMan** [dotnet/runtime#40007] opened 2020-07-28 13:26 UTC
Any plan to expose PooledByteBufferWriter or a similar implementation as a first class citizen in the framework?
actually AFAIK there is just ArrayBufferWriter that implements IBufferWriter and it doesn't uses memory pools.

It can be really useful when dealing with network protocol implementation and you have to serialize/deserialize data using a temporary memory while preserving lot of allocation of short living objects

Another use case I'm facing is when I need the size of the serialized data (without actually needing the serialized data itself) so I need just a temporary memory to do the serialization and return back the size discarding the memory used to serialize it.

Thanks

**Comment by jkotas** [comment] 2020-07-28 15:26
Duplicate of #33598

**Closed by jkotas** 2020-07-28 15:26 UTC
Labels: api-suggestion, area-System.Buffers, untriaged
