### ISSUE TITLE
CacheExtensions.GetOrCreate{Async} thread-safety

### ISSUE THREAD

**Issue by alrz** [dotnet/runtime#71581] opened 2022-07-02 12:58 UTC
### Description

Atomic operations for IMemoryCache are defined in `CacheExtensions` but without any thread-safety considerations.
I think at least Async flavors should not try to run the factory twice or more.

**Comment by eerhardt** [comment] 2022-07-02 15:58
Looks like a duplicate of https://github.com/dotnet/runtime/issues/36500#issuecomment-1090517755

**Comment by alrz** [comment] 2022-07-02 16:08
>Doesn't seem like a bigger value add than just letting whomever needs this functionality to just add it directly into their code.

By that reasoning, what is the value add for `GetOrCreate`? Whomever needs this functionally could glue together those public APIs as an extension method right? At least they would've known that the impl is or is not thread safe, unlike what we have today.

**Comment by alrz** [comment] 2022-07-12 21:39
> That's actually what the existing `GetOrCreate` is - a glued together extension method:

Exactly my point. I'm saying that the `GetOrCreate` extension *could* justify its existence by considering thread-safety. At the very least, that is what I'd expect from an API named "GetOrCreate"..

**Comment by eerhardt** [comment] 2022-07-20 16:41
This is the same behavior that ConcurrentDictionary.GetOrAdd has. See https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2.getoradd?view=net-6.0#system-collections-concurrent-concurrentdictionary-2-getoradd(-0-system-func((-0-1)))

> If you call GetOrAdd simultaneously on different threads, valueFactory may be called multiple times, but only one key/value pair will be added to the dictionary.

Closing as duplicate of #36500

**Closed by eerhardt** 2022-07-20 16:41 UTC
Labels: tenet-performance, untriaged, area-Extensions-Caching
