### ISSUE TITLE
[API Proposal]: JsonDerivedTypeAttribute<T> for simplified polymorphic JSON configuration

### ISSUE THREAD

**Issue by kzu** [dotnet/runtime#99421] opened 2024-03-07 18:59 UTC
### Background and motivation

You currently have to decide on a "discriminator name" for derived types, such as:

```csharp
[JsonDerivedType(typeof(MessageContent), nameof(MessageContent)]
[JsonDerivedType(typeof(FileContent), nameof(FileContent)]
public abstract record Content ...
```

In many cases, choosing the type name as the discrimantor makes perfect sense. 
Since attributes can now be generic, it would make sense to leverage that to simplify the annotation.

### API Proposal

```csharp
public class JsonDerivedTypeAttribute<T> : JsonDerivedTypeAttribute
{
    public JsonDerivedTypeAttribute(string? typeDiscriminator = default) : base(typeof(T), typeDiscriminator ?? typeof(T).Name)
    {
    }
}```


### API Usage

```csharp
[JsonDerivedType<MessageContent>]
[JsonDerivedType<FileContent>("file")]
public abstract record Content ...
```

### Alternative Designs

Perhaps the overload to override the discriminator string is unnecessary?

**Comment by eiriktsarpalis** [comment] 2024-03-11 10:12
Duplicate of https://github.com/dotnet/runtime/issues/72936.

**Closed by eiriktsarpalis** 2024-03-11 10:12 UTC
Labels: api-suggestion, area-System.Text.Json, untriaged
