### ISSUE TITLE
Test failure JIT\\SIMD\\DivSignedUnsignedTest_r\\DivSignedUnsignedTest_r.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#67019] opened 2022-03-23 01:14 UTC
Run: [runtime-coreclr crossgen2 20220321.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1675364&view=ms.vss-test-web.build-test-results-tab&runId=45952654&resultId=101656&paneView=debug)

Failed test:
```
R2R-CG2 windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open
- JIT\\SIMD\\DivSignedUnsignedTest_r\\DivSignedUnsignedTest_r.cmd
- JIT\\SIMD\\DivSignedUnsignedTest_r\\DivSignedUnsignedTest_r.cmd
- JIT\\Intrinsics\\MathRoundDouble_ro\\MathRoundDouble_ro.cmd
- JIT\\Intrinsics\\BMI1Intrinsicss_r\\BMI1Intrinsicss_r.cmd
- JIT\\SIMD\\VectorMatrix_ro\\VectorMatrix_ro.cmd
- JIT\\Intrinsics\\MathCeilingSingle_ro\\MathCeilingSingle_ro.cmd
- JIT\\Intrinsics\\MathFloorSingle_ro\\MathFloorSingle_ro.cmd
- JIT\\Intrinsics\\BMI1Intrinsics_ro\\BMI1Intrinsics_ro.cmd
- JIT\\Intrinsics\\MathFusedMultiplyAdd_r\\MathFusedMultiplyAdd_r.cmd
- JIT\\Intrinsics\\MathRoundDouble_r\\MathRoundDouble_r.cmd
- JIT\\Intrinsics\\TypeIntrinsics_r\\TypeIntrinsics_r.cmd
- JIT\\Intrinsics\\MathFusedMultiplyAdd_ro\\MathFusedMultiplyAdd_ro.cmd
- JIT\\Intrinsics\\MathCeilingSingle_r\\MathCeilingSingle_r.cmd
- JIT\\Intrinsics\\BinaryPrimitivesReverseEndianness_r\\BinaryPrimitivesReverseEndianness_r.cmd
- JIT\\Intrinsics\\**
- JIT\\SIMD\\SqrtGeneric_ro\\SqrtGeneric_ro.cmd
- JIT\\SIMD\\VectorArrayInit_r\\VectorArrayInit_r.cmd
- JIT\\SIMD\\VectorInit_r\\VectorInit_r.cmd
- JIT\\SIMD\\Vector3_r\\Vector3_r.cmd
- JIT\\SIMD\\Vector4_ro\\Vector4_ro.cmd
- JIT\\SIMD\\VectorHWAccel2_r\\VectorHWAccel2_r.cmd
- JIT\\SIMD\\VectorSum_r\\VectorSum_r.cmd
- JIT\\SIMD\\Vector4_r\\Vector4_r.cmd
- JIT\\SIMD\\VectorConvert_r_Target_64Bit\\VectorConvert_r_Target_64Bit.cmd
- JIT\\SIMD\\**
```
**Error message:**
```
Could Not Find C:\h\w\B6C70A16\w\A88B097B\e\JIT\SIMD\DivSignedUnsignedTest_r\IL-CG2\composite-r2r.dll
Could Not Find C:\h\w\B6C70A16\w\A88B097B\e\JIT\SIMD\DivSignedUnsignedTest_r\DivSignedUnsignedTest_r.dll.rsp
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'ILCompiler.DependencyAnalysisFramework, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'. The module was expected to contain an assembly manifest.
File name: 'ILCompiler.DependencyAnalysisFramework, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'
at ILCompiler.ReadyToRunCodegenCompilationBuilder.ToCompilation()
at ILCompiler.Program.RunSingleCompilation(Dictionary2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary2 unrootedInputFilePaths, HashSet`1 versionBubbleModulesHash, CompilerTypeSystemContext typeSystemContext)
at ILCompiler.Program.Run(String[] args)
at ILCompiler.Program.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\B6C70A16\w\A88B097B\uploads\Reports\JIT.SIMD\DivSignedUnsignedTest_r\DivSignedUnsignedTest_r.output.txt
Raw output:
BEGIN EXECUTION
DivSignedUnsignedTest_r.dll
1 file(s) copied.
Response file: C:\h\w\B6C70A16\w\A88B097B\e\JIT\SIMD\DivSignedUnsignedTest_r\DivSignedUnsignedTest_r.dll.rsp
C:\h\w\B6C70A16\w\A88B097B\e\JIT\SIMD\DivSignedUnsignedTest_r\IL-CG2\DivSignedUnsignedTest_r.dll
-o:C:\h\w\B6C70A16\w\A88B097B\e\JIT\SIMD\DivSignedUnsignedTest_r\DivSignedUnsignedTest_r.dll
--targetarch:x64
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\B6C70A16\p\System..dll
-r:C:\h\w\B6C70A16\p\Microsoft..dll
-r:C:\h\w\B6C70A16\p\mscorlib.dll
-r:C:\h\w\B6C70A16\p\netstandard.dll
-O
" "dotnet" "C:\h\w\B6C70A16\p\crossgen2\crossgen2.dll" @"C:\h\w\B6C70A16\w\A88B097B\e\JIT\SIMD\DivSignedUnsignedTest_r\DivSignedUnsignedTest_r.dll.rsp"   -r:C:\h\w\B6C70A16\w\A88B097B\e\JIT\SIMD\DivSignedUnsignedTest_r\IL-CG2*.dll"
Crossgen2 failed with exitcode - -532462766
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\B6C70A16\p
C:\h\w\B6C70A16\w\A88B097B\e\JIT\SIMD\DivSignedUnsignedTest_r\DivSignedUnsignedTest_r.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_SIMD._DivSignedUnsignedTest_r_DivSignedUnsignedTest_r_._DivSignedUnsignedTest_r_DivSignedUnsignedTest_r_cmd()
```

**Comment by trylek** [comment] 2022-04-04 20:19
Closing as duplicate of: https://github.com/dotnet/runtime/issues/65646

**Closed by trylek** 2022-04-04 20:19 UTC
Labels: os-windows, arch-x64, area-crossgen2-coreclr, untriaged
