### ISSUE TITLE
[API Proposal]: `System.Boolean` and `System.String` should implement `ISpanFormattable`

### ISSUE THREAD

**Issue by Neme12** [dotnet/runtime#88408] opened 2023-07-05 07:54 UTC
### Background and motivation

I just watched an API review (https://www.youtube.com/watch?v=YYFxFpiurN8&t=6325) where it was approved that `System.Boolean` and `System.String` would implement `ISpanParsable` (#78523 and #78842). I think any type that implements `IParsable`/`ISpanParsable` should also implement `IFormattable`/`ISpanFormattable`, as these two interfaces go hand in hand and it's common to use both of them (e.g. when I'm writing some generic code to deserialize a type, I usually write the serialization logic as well). I can't think of any other type that currently implements `ISpanParsable` but not `ISpanFormattable`. I think both of these types should implement `ISpanFormattable` as well for completeness and parity.

### API Proposal

```csharp
namespace System;

public readonly partial struct Boolean : ISpanFormattable
{
    string IFormattable.ToString(string? format, IFormatProvider? formatProvider);
    bool ISpanFormattable.TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider? provider);
}

public sealed partial class String : ISpanFormattable
{
    string IFormattable.ToString(string? format, IFormatProvider? formatProvider);
    bool ISpanFormattable.TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider? provider);
}
```

### API Usage

```cs
T Deserialze<T>(string value) where T : IParsable<T>
{
    return T.Parse(value, CultureInfo.InvariantCulture);
}

string Serialze<T>(T value) where T : IFormattable
{
    // Of course, the Span overload will be more useful than the string one as people can already use
    // regular ToString if they don't care about the culture. But if they do, this one is useful as well
    // so that people don't have to special case bool and string.
    return value.ToString(null, CultureInfo.InvariantCulture);
}
```

**Comment by KeterSCP** [comment] 2023-07-05 09:09
isn't this a duplicate of https://github.com/dotnet/runtime/issues/88275?

**Comment by stephentoub** [comment] 2023-07-05 12:59
> isn't this a duplicate of #88275?

Yes

**Closed by stephentoub** 2023-07-05 12:59 UTC
Labels: api-suggestion, untriaged, needs-area-label

**Comment by Neme12** [comment] 2023-07-05 13:24
> isn't this a duplicate of #88275?

Yes, with a different reasoning.
