### ISSUE TITLE
Could not load type 'System.Runtime.CompilerServices.Unsafe' from assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

### ISSUE THREAD

**Issue by RussKie** [dotnet/runtime#66056] opened 2022-03-02 03:17 UTC
### Description

It appears the latest nightly SDK bundles an outdated version of Microsoft.NETCore.App - 7.0.0-preview.2.22116.9, whilst Microsoft.AspNetCore.App and Microsoft.WindowsDesktop.App are bundled with 7.0.0-preview.3.22117.6 and 7.0.0-preview.3.22116.6 respectively.
This results in failures to launch a Windows Desktop app targeting .NET 7.0, e.g.:
```
Application: GitUI.exe
CoreCLR Version: 7.0.22.11609
.NET Version: 7.0.0-preview.2.22116.9
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeLoadException: Could not load type 'System.Runtime.CompilerServices.Unsafe' from assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at System.Windows.Forms.Application.ThreadContext.Interop.Mso.IMsoComponent.FPreTranslateMessage(MSG* msg)
   at System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData) in D:\Development\dotnet-winforms\src\System.Windows.Forms\src\System\Windows\Forms\Application.ComponentManager.cs:line 336
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context) in D:\Development\dotnet-winforms\src\System.Windows.Forms\src\System\Windows\Forms\Application.ThreadContext.cs:line 1117
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context) in D:\Development\dotnet-winforms\src\System.Windows.Forms\src\System\Windows\Forms\Application.ThreadContext.cs:line 981
   at System.Windows.Forms.Application.Run(Form mainForm) in D:\Development\dotnet-winforms\src\System.Windows.Forms\src\System\Windows\Forms\Application.cs:line 1181
   at GitUI.Program.Main() in D:\Development\!Repro\5774-Test-InvisiblePanel\Program.cs:line 33
```

This issue impacts our ability to test, and will likely affect the CTI folks.

/cc: @dreddy-work @Olina-Zhang 

### Reproduction Steps

Install the latest nightly SDK https://aka.ms/dotnet/7.0.1xx/daily/dotnet-sdk-win-x64.exe (at the time of writing, 7.0.100-preview.3.22128.6, ab332adae54d8e089fa0a9e81f30afddf63c9eb2),

### Expected behavior

The version of Microsoft.NETCore.App workload is at 7.0.0-preview.3.xyz.

### Actual behavior

As described above.

### Known Workarounds

To get around the issue I had to copy the latest version of Microsoft.NETCore.App workload from `.\dotnet-winforms\.dotnet\shared\Microsoft.NETCore.App` to `C:\Program Files\dotnet\shared\Microsoft.NETCore.App`. This workaround is not obvious, and likely out of reach of an average user, especially if the user doesn't actively contribute to one of .NET repo, where the latest version can be copied from.

**Comment by dreddy-work** [comment] 2022-03-02 06:48
related https://github.com/dotnet/sdk/pull/24009.

**Comment by jkotas** [comment] 2022-03-02 16:28
Yes, this is caused by incoherent dependencies in sdk repo and it will be fixed by https://github.com/dotnet/sdk/pull/24009 .

**Comment by akoeplinger** [comment] 2022-03-03 14:43
https://github.com/dotnet/sdk/pull/24009 was merged

**Closed** 2022-03-03 16:08 UTC
Labels: area-Infrastructure-libraries, untriaged
