### ISSUE TITLE
[wasi/wasm] dotnet workload search output has placeholder text in en-US.utf-8 locale

### ISSUE THREAD

**Issue by lambdageek** [dotnet/runtime#90207] opened 2023-08-09 01:16 UTC
This is with .NET 8 Preview 7 on linux-x64 with `LANG=en_US.utf-8`

```console
$ dotnet workload search

Workload ID                 Description                                         
--------------------------------------------------------------------------------
android                     .NET SDK Workload for building Android applications.
macos                       .NET SDK Workload for building macOS applications.  
maui-android                .NET MAUI SDK for Android                           
maui-tizen                  .NET MAUI SDK for Tizen                             
maui-windows                .NET MAUI SDK for Windows                           
wasi-experimental           workloads/wasi-experimental/description             
wasm-experimental           workloads/wasm-experimental/description             
wasm-experimental-net7      .NET WebAssembly experimental tooling for net7.0    
wasm-tools                  .NET WebAssembly build tools                        
wasm-tools-net6             .NET WebAssembly build tools for net6.0             
wasm-tools-net7             .NET WebAssembly build tools for net7.0      
```

note that `wasi-experimental` and `wasm-experimental` both have placeholder text instead of a proper description

**Comment by lambdageek** [comment] 2023-08-09 01:30
Looks like there's a typo here: 

https://github.com/dotnet/runtime/blob/18b668ac2cbd4cd0c8ea40915854ed05069409eb/src/mono/nuget/Microsoft.NET.Workload.Mono.Toolchain.Current.Manifest/localize/WorkloadManifest.en.json#L3

should probably be `workload/wasm-tools/description` not `wasm-tools-experimental`.

---

if I set locale to `C` I see the expected output:

```console
$ LANG=C dotnet workload search

Workload ID                 Description                                         
--------------------------------------------------------------------------------
android                     .NET SDK Workload for building Android applications.
macos                       .NET SDK Workload for building macOS applications.  
maui-android                .NET MAUI SDK for Android                           
maui-tizen                  .NET MAUI SDK for Tizen                             
maui-windows                .NET MAUI SDK for Windows                           
wasi-experimental           .NET WASI experimental                              
wasm-experimental           .NET WebAssembly experimental tooling               
wasm-experimental-net7      .NET WebAssembly experimental tooling for net7.0    
wasm-tools                  .NET WebAssembly build tools                        
wasm-tools-net6             .NET WebAssembly build tools for net6.0             
wasm-tools-net7             .NET WebAssembly build tools for net7.0             
```

**Comment by lambdageek** [comment] 2023-08-09 01:38
How does it decide which strings to localize and which ones to replace by placeholders??

```console
$ LANG=cs dotnet workload search

ID úlohy                    Popis                                               
--------------------------------------------------------------------------------
android                     .NET SDK Workload for building Android applications.
macos                       .NET SDK Workload for building macOS applications.  
maui-android                .NET MAUI SDK for Android                           
maui-tizen                  .NET MAUI SDK for Tizen                             
maui-windows                .NET MAUI SDK for Windows                           
wasi-experimental           workloads/wasi-experimental/description             
wasm-experimental           workloads/wasm-experimental/description             
wasm-experimental-net7      workloads/wasm-experimental-net7/description        
wasm-tools                  Nástroje pro sestavení .NET WebAssembly             
wasm-tools-net6             Nástroje pro sestavení .NET WebAssembly             
wasm-tools-net7             Nástroje pro sestavení .NET WebAssembly             
```

Apparently `wasm-experimental` gets a placeholder but `android` just uses the `LANG=C` string?

**Comment by lewing** [comment] 2023-08-13 03:56
duplicate of https://github.com/dotnet/runtime/issues/76968

**Closed by lewing** 2023-08-13 03:56 UTC
Labels: arch-wasm, area-Build-mono, os-wasi, os-browser
