### ISSUE TITLE
Test failure: Assertion failed 'topBB->bbNum <= botBB->bbNum'

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#42787] opened 2020-09-27 02:33 UTC
failed in job: [runtime-coreclr jitstress2-jitstressregs 20200926.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=832659&view=ms.vss-test-web.build-test-results-tab&runId=26545102&resultId=106376&paneView=debug)

failed tests:
JIT\\Methodical\\tailcall\\_il_reldeep_array_nz\\_il_reldeep_array_nz.cmd
JIT\\Methodical\\tailcall\\_il_reldeep_inst\\_il_reldeep_inst.cmd
JIT\\Methodical\\tailcall\\_il_reldeep_gc\\_il_reldeep_gc.cmd
JIT\\Methodical\\tailcall\\_il_reldeep_virt\\_il_reldeep_virt.cmd
JIT\\Methodical\\VT\\callconv\\_il_reljumps3\\_il_reljumps3.cmd
JIT\\Methodical\\VT\\callconv\\_il_reljumps2\\_il_reljumps2.cmd
JIT/Methodical/VT/callconv/_il_reljumps3/_il_reljumps3.sh
JIT/Methodical/VT/callconv/_il_reljumps2/_il_reljumps2.sh
JIT\\jit64\\mcc\\interop\\mcc_i37\\mcc_i37.cmd
JIT\\Regression\\JitBlue\\GitHub_23147\\GitHub_23147\\GitHub_23147.cmd
JIT\\jit64\\mcc\\interop\\mcc_i77\\mcc_i77.cmd
JIT\\Methodical\\tailcall\\_il_reldeep_value\\_il_reldeep_value.cmd
JIT\\Methodical\\tailcall\\_il_reldeep_array\\_il_reldeep_array.cmd
JIT\\Methodical\\VT\\callconv\\_il_reljumper4\\_il_reljumper4.cmd
JIT\\jit64\\mcc\\interop\\mcc_i87\\mcc_i87.cmd
JIT/Regression/VS-ia64-JIT/V1.2-M02/b14364/b14364/b14364.sh
JIT\\Regression\\VS-ia64-JIT\\V1.2-M02\\b14364\\b14364\\b14364.cmd

Error message
~~~
Assert failure(PID 4460 [0x0000116c], Thread: 4948 [0x1354]): Assertion failed 'topBB->bbNum <= botBB->bbNum' in 'JitTest.TestClass:Method11():System.String:this' during 'Set block order' (IL size 34)

    File: F:\workspace\_work\1\s\src\coreclr\src\jit\optimizer.cpp Line: 3935
    Image: C:\h\w\C33C0A68\p\CoreRun.exe


Return code:      1
Raw output file:      C:\h\w\C33C0A68\w\AB16094C\e\JIT\Methodical\Reports\JIT.Methodical\tailcall\_il_reldeep_inst\_il_reldeep_inst.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\C33C0A68\p\corerun.exe" _il_reldeep_inst.dll 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\C33C0A68\p
> C:\h\w\C33C0A68\w\AB16094C\e\JIT\Methodical\tailcall\_il_reldeep_inst\_il_reldeep_inst.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_Methodical._tailcall__il_reldeep_inst__il_reldeep_inst_._tailcall__il_reldeep_inst__il_reldeep_inst_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x64.Checked\TestWrappers\JIT.Methodical\JIT.Methodical.XUnitWrapper.cs:line 180851
~~~

**Comment by BruceForstall** [comment] 2020-09-28 01:14
@dotnet/jit-contrib JIT assertion regression in jitstress2 run, especially 4 tailcall tests.

**Comment by BruceForstall** [comment] 2020-10-05 19:25
@dotnet/jit-contrib This is still causing many jobs to fail

**Comment by erozenfeld** [comment] 2020-10-05 19:48
I haven't investigated this but my guess is that this is likely caused by removal of this line https://github.com/dotnet/runtime/blob/5c8e3f820deb54941ebcec53d02f466d7c27f7ed/src/coreclr/src/jit/compiler.cpp#L4660 in my #42664.

**Comment by briansull** [comment] 2020-10-05 21:12
I will take a look

**Comment by briansull** [comment] 2020-10-05 21:38
The GS Cookie phase was inserting a new basic block and (indirectly) depending upon the call to fgRenumberBlocks that Eugene removed.   I will add a renuimber bloicks call to the GS Cookie phase if it can insert a new basic block.

I am testing a fix.

**Comment by BruceForstall** [comment] 2020-10-08 22:44
This should be fixed by https://github.com/dotnet/runtime/pull/43077

**Closed by BruceForstall** 2020-10-08 22:44 UTC
Labels: JitStress, area-CodeGen-coreclr
