### ISSUE TITLE
[API Proposal]: ImmutableArray[Slice]

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#59965] opened 2021-10-04 20:06 UTC
### Background and motivation

To be able to create child Immutable Arrays easily.

### API Proposal

Not sure.

### API Usage

```C#

var Slice = MyImmutableArray[2..7];

```

**Comment by eiriktsarpalis** [comment] 2021-10-05 10:38
Exposing range functionality like array does sounds like a reasonable request. The API proposal as it stands needs a bit more work however.

**Comment by eiriktsarpalis** [comment] 2021-10-05 10:39
Actually, it appears this is a duplicate of https://github.com/dotnet/runtime/issues/22928. I'm going to close this one.

**Closed by eiriktsarpalis** 2021-10-05 10:39 UTC
Labels: api-needs-work, api-suggestion, area-System.Collections
