### ISSUE TITLE
Potential performance regression in ConcurrentDictionary

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#59101] opened 2021-09-14 17:39 UTC
Originally detected by the bot in https://github.com/DrewScoggins/performance-2/issues/7188 but not reported in dotnet/runtime (cc @DrewScoggins)

<details>

## System.Collections.ContainsKeyFalse<Int32, Int32>.ConcurrentDictionary(Size: 512)

| Result |     Base |     Diff | Ratio | Alloc Delta | Modality | Operating System        | Bit   | Processor Name                                  | Base V        | Diff V      |
| ------ | --------:| --------:| -----:| -----------:| -------- | ----------------------- | ----- | ----------------------------------------------- | ------------- | ------------ |
| Slower |  2337.71 |  3388.27 |  0.69 |          +0 |          | Windows 10.0.19043.1165 | X64   | AMD Ryzen Threadripper PRO 3945WX 12-Cores      | 5.0.921.35908 | 6.0.21.41701|
| Slower |  2800.31 |  4248.82 |  0.66 |          +0 |          | Windows 10.0.20348      | X64   | AMD EPYC 7452                                   | 5.0.921.35908 | 6.0.21.41701|
| Slower |  2835.78 |  4290.08 |  0.66 |          +0 |          | Windows 10.0.20348      | X64   | AMD EPYC 7452                                   | 5.0.921.35908 | 6.0.21.41701|
| Slower |  3301.32 |  4170.55 |  0.79 |          +0 |          | Windows 10.0.18363.1621 | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz               | 5.0.921.35908 | 6.0.21.41701|
| Slower |  3646.48 |  4747.06 |  0.77 |          +0 |          | Windows 8.1             | X64   | Intel Core i7-3610QM CPU 2.30GHz (Ivy Bridge)   | 5.0.921.35908 | 6.0.21.45401|
| Slower |  3171.31 |  4216.53 |  0.75 |          +0 |          | Windows 10.0.19042.685  | X64   | Intel Core i7-5557U CPU 3.10GHz (Broadwell)     | 5.0.921.35908 | 6.0.21.41701|
| Slower |  2812.69 |  3443.40 |  0.82 |          +0 | several? | Windows 10.0.19043.1165 | X64   | Intel Core i7-6700 CPU 3.40GHz (Skylake)        | 5.0.921.35908 | 6.0.21.41701|
| Slower |  3428.46 |  4345.94 |  0.79 |          +0 |          | Windows 10.0.22454      | X64   | Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R)   | 5.0.921.35908 | 6.0.21.41701|
| Slower |  2231.82 |  2870.58 |  0.78 |          +0 |          | Windows 10.0.22451      | X64   | Intel Core i7-8700 CPU 3.20GHz (Coffee Lake)    | 5.0.921.35908 | 6.0.21.41701|
| Slower |  2418.54 |  3126.49 |  0.77 |          +0 |          | Windows 10.0.19042.1165 | X64   | Intel Core i9-9900T CPU 2.10GHz                 | 5.0.921.35908 | 6.0.21.41701|
| Slower |  8967.53 | 12350.98 |  0.73 |          +0 |          | Windows 7 SP1           | X64   | Intel Core2 Duo CPU T9600 2.80GHz               | 5.0.721.25508 | 6.0.21.41701|
| Slower |  2979.47 |  4139.37 |  0.72 |          +0 |          | centos 8                | X64   | AMD EPYC 7452                                   | 5.0.921.35908 | 6.0.21.41701|
| Slower |  2999.37 |  4220.56 |  0.71 |          +0 |          | debian 10               | X64   | AMD EPYC 7452                                   | 5.0.921.35908 | 6.0.21.41701|
| Slower |  3286.92 |  4461.40 |  0.74 |          +0 |          | rhel 7                  | X64   | AMD EPYC 7452                                   | 5.0.921.35908 | 6.0.21.41701|
| Slower |  3055.47 |  4329.07 |  0.71 |          +0 |          | sles 15                 | X64   | AMD EPYC 7452                                   | 5.0.921.35908 | 6.0.21.41701|
| Slower |  3011.99 |  4248.63 |  0.71 |          +0 |          | opensuse-leap 15.3      | X64   | AMD EPYC 7452                                   | 5.0.921.35908 | 6.0.21.41701|
| Slower |  3069.50 |  3891.08 |  0.79 |          +0 |          | ubuntu 18.04            | X64   | Intel Xeon CPU E5-1650 v4 3.60GHz               | 5.0.921.35908 | 6.0.21.41701|
| Slower |  4322.81 |  4963.95 |  0.87 |          +0 |          | ubuntu 18.04            | X64   | Intel Core i7-2720QM CPU 2.20GHz (Sandy Bridge) | 5.0.921.35908 | 6.0.21.41701|
| Slower |  3245.88 |  3643.83 |  0.89 |          +0 |          | alpine 3.13             | X64   | Intel Core i7-7700 CPU 3.60GHz (Kaby Lake)      | 5.0.921.35908 | 6.0.21.41701|
| Same   | 13122.35 | 13184.61 |  1.00 |          +0 |          | ubuntu 16.04            | Arm64 | Unknown processor                               | 5.0.421.11614 | 6.0.21.41701|
| Same   |  5359.32 |  5528.86 |  0.97 |          +0 |          | Windows 10.0.19043.1165 | Arm64 | Microsoft SQ1 3.0 GHz                           | 5.0.921.35908 | 6.0.21.41701|
| Same   |  5727.84 |  5525.96 |  1.04 |          +0 |          | Windows 10.0.22000      | Arm64 | Microsoft SQ1 3.0 GHz                           | 5.0.921.35908 | 6.0.21.41701|
| Same   |  3405.21 |  3604.28 |  0.94 |          +0 |          | Windows 10.0.19043.1165 | X86   | AMD Ryzen Threadripper PRO 3945WX 12-Cores      | 5.0.921.35908 | 6.0.21.41701|
| Same   |  4636.79 |  5053.24 |  0.92 |          +0 |          | Windows 10.0.18363.1621 | X86   | Intel Xeon CPU E5-1650 v4 3.60GHz               | 5.0.921.35908 | 6.0.21.41701|
| Same   | 15316.42 | 15962.39 |  0.96 |          +0 |          | Windows 10.0.19043.1165 | Arm   | Microsoft SQ1 3.0 GHz                           | 5.0.921.35908 | 6.0.21.41701|
| Slower |  4226.65 |  5122.23 |  0.83 |          +0 | bimodal  | macOS Big Sur 11.5.2    | X64   | Intel Core i5-4278U CPU 2.60GHz (Haswell)       | 5.0.921.35908 | 6.0.21.41701|
| Same   |  3518.00 |  3832.79 |  0.92 |          +0 |          | macOS Big Sur 11.5.2    | X64   | Intel Core i7-4870HQ CPU 2.50GHz (Haswell)      | 5.0.921.35908 | 6.0.21.41701|
| Slower |  3601.26 |  4275.64 |  0.84 |          +0 |          | macOS Big Sur 11.4      | X64   | Intel Core i7-5557U CPU 3.10GHz (Broadwell)     | 5.0.921.35908 | 6.0.21.41701|
</details>

Repro:

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f net5.0 net6.0 --filter "System.Collections.ContainsKeyFalse*Int*ConcurrentDictionary"
```

https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_x64_ubuntu%2018.04%2fSystem.Collections.ContainsKeyFalse(Int32%2c%20Int32).ConcurrentDictionary(Size%3a%20512).html

![image](https://user-images.githubusercontent.com/6011991/133306265-a104dace-bf8e-4441-a89b-357bd7c0f624.png)

It seems to be mostly related to x64 and might have been caused by a PGO update (cc @AndyAyersMS @kunalspathak @EgorBo)

[ARM results](https://pvscmdupload.blob.core.windows.net/reports/allTestHistory%2frefs%2fheads%2fmain_arm64_ubuntu%2018.04%2fSystem.Collections.ContainsKeyFalse(Int32%2c%20Int32).ConcurrentDictionary(Size%3a%20512).html):

![image](https://user-images.githubusercontent.com/6011991/133306663-af60ce24-00c8-46aa-b91f-5df131494ce2.png)

**Comment by EgorBo** [comment] 2021-09-14 17:49
So there were two regressions: changes from the inliner and https://github.com/dotnet/runtime/pull/54998 (this one got fixed by https://github.com/dotnet/runtime/pull/55300).

**Comment by EgorBo** [comment] 2021-09-14 18:45
assigned to myself since it's most likely inliner changes.

**Comment by EgorBo** [comment] 2021-10-11 10:17
Oops, missed this one.
Looking at it now

**Comment by AndyAyersMS** [comment] 2022-06-28 15:28
Odd that this is still in 6.0 .. @EgorBo should we move this to 7.0 or elsewhere?

**Comment by AndyAyersMS** [comment] 2022-07-25 15:53
@EgorBo ping...

**Comment by EgorBo** [comment] 2022-07-26 18:18
Sorry, forgot to leave my notes here, so the issues seems only noticeable on Alpine-x64:

![image](https://user-images.githubusercontent.com/523221/181081632-40ad1752-ec89-4a6a-9766-f7e6943db3fb.png)

the big jump and the fix are https://github.com/dotnet/runtime/pull/54998 and https://github.com/dotnet/runtime/pull/55300

the initial jump is PGO update

**Closed by EgorBo** 2022-07-26 18:18 UTC
Labels: tenet-performance, arch-x64, area-CodeGen-coreclr, needs-further-triage
