### ISSUE TITLE
[API Proposal]: Since we can run source code in visual studio, why don't we make running from source code a thing

### ISSUE THREAD

**Issue by Xyncgas** [dotnet/runtime#62424] opened 2021-12-06 04:11 UTC
### Background and motivation

So c# can be like javascript / python, I just give people source codes, and they will download whatever package I used from nuget, and it just runs and people can change the source code so it's flexible.

And there isn't a way to run from source file like python but it's certainly possible I feel like.

It saves a lot trouble with configuring the program, for simple stuffs like changing the port my program is listening of course you can use a json config, but it's way more flexible if people can change stuffs in the source code

### API Proposal

N/A

### API Usage

dotnet run myapp.cs

**Comment by stephentoub** [comment] 2021-12-06 04:26
Duplicate of https://github.com/dotnet/sdk/issues/12328. Also https://github.com/dotnet/designs/pull/213, https://github.com/dotnet/csharplang/issues/3507, https://github.com/dotnet/csharplang/blob/main/meetings/2021/LDM-2021-05-12.md#simple-c-programs. Thanks.

**Closed by stephentoub** 2021-12-06 04:26 UTC
Labels: api-suggestion, area-Meta, untriaged
