### ISSUE TITLE
Test failure: System.Net.Quic.Tests.QuicStreamTests_MsQuicProvider.BasicTest

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#56269] opened 2021-07-24 15:26 UTC
Test failures **5/24-8/10 (incl. PRs)**:

Day | Run
-- | --
7/15 | PR #55716
7/15 | PR #55726
7/19 | PR #55883
7/20 | PR #56031
7/24 | PR #56223
7/26 | 1x Official run + 3x PR (PR #55353, PR #54640, PR #56282)
7/27 | PR #56215
7/28 | PR #56411
7/29 | 1x Official run + 2x PR (PR #56566, PR #56473)
7/30 | 1x Official run + 3x PR (PR #55871, PR #56639, PR #55353)
8/1 | PR #55353
8/3 | PR #56753
8/4 | 2x PR (PR #56486, PR #56818)
8/5 | 2x PR (PR #56874, PR #56905)
8/6 | PR #56869
8/10 | 2x PR (PR #57076, PR #57079 - ConfigurationOpen failed)

```
System.Net.Quic.QuicException : Connection has been shutdown by transport. Error Code: CONNECTION_REFUSED

   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.HandleEventShutdownInitiatedByTransport(State state, ConnectionEvent& connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicConnection.cs:line 252
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection.NativeCallbackHandler(IntPtr connection, IntPtr context, ConnectionEvent& connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicConnection.cs:line 645
--- End of stack trace from previous location ---
   at System.Net.Quic.Tests.QuicTestBase`1.<>c__DisplayClass21_0.<<RunClientServer>b__1>d[[System.Net.Quic.Tests.MsQuicProviderFactory, System.Net.Quic.Functional.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].MoveNext() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 136
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 55
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 82
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 49
   at System.Net.Quic.Tests.QuicTestBase`1.<RunClientServer>d__21[[System.Net.Quic.Tests.MsQuicProviderFactory, System.Net.Quic.Functional.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].MoveNext() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 123
   at System.Net.Quic.Tests.QuicStreamTests`1.<BasicTest>d__1[[System.Net.Quic.Tests.MsQuicProviderFactory, System.Net.Quic.Functional.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].MoveNext() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs:line 23
--- End of stack trace from previous location ---
```

Alternative failure:
```
System.Net.Quic.QuicException : ConfigurationOpen failed. Error Code: INVALID_PARAMETER

   at System.Net.Quic.Implementations.MsQuic.Internal.QuicExceptionHelpers.ThrowIfFailed(UInt32 status, String message, Exception innerException) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/Internal/QuicExceptionHelpers.cs:line 12
   at System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicConfigurationHandle.Create(QuicOptions options, QUIC_CREDENTIAL_FLAGS flags, X509Certificate certificate, SslStreamCertificateContext certificateContext, List`1 alpnProtocols) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/Interop/SafeMsQuicConfigurationHandle.cs:line 165
   at System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicConfigurationHandle.Create(QuicClientConnectionOptions options) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/Interop/SafeMsQuicConfigurationHandle.cs:line 56
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection..ctor(QuicClientConnectionOptions options) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicConnection.cs:line 175
   at System.Net.Quic.Implementations.MsQuic.MsQuicImplementationProvider.CreateConnection(QuicClientConnectionOptions options) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicImplementationProvider.cs:line 19
   at System.Net.Quic.QuicConnection..ctor(QuicImplementationProvider implementationProvider, QuicClientConnectionOptions options) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 45
   at System.Net.Quic.QuicConnection..ctor(QuicImplementationProvider implementationProvider, EndPoint remoteEndPoint, SslClientAuthenticationOptions sslClientAuthenticationOptions, IPEndPoint localEndPoint) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 38
   at System.Net.Quic.Tests.QuicTestBase`1.CreateQuicConnection(IPEndPoint endpoint) in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 71
   at System.Net.Quic.Tests.QuicTestBase`1.<>c__DisplayClass32_0.<<RunClientServer>b__1>d.MoveNext() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 170
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 64
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 91
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 55
   at System.Net.Quic.Tests.QuicTestBase`1.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions) in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 157
   at System.Net.Quic.Tests.QuicStreamTests`1.BasicTest() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs:line 25
--- End of stack trace from previous location ---
```

**Comment by wfurt** [comment] 2021-07-24 23:27
I think this is symptom of  #55979. This test is trivial as name suggests.

**Comment by karelz** [comment] 2021-07-29 16:40
Triage: @wfurt will add some instrumentations, so that we can make it actionable. We are unable to repro it locally (unlike other failures).

**Comment by wfurt** [comment] 2021-07-29 18:10
I got local failure with different trace
```
     <test name="System.Net.Quic.Tests.QuicStreamTests_MsQuicProvider.BasicTest" type="System.Net.Quic.Tests.QuicStreamTests_MsQuicProvider" method="BasicTest" time="4.3213071" result="Fail">
        <failure exception-type="System.Net.Quic.QuicException">
          <message><![CDATA[System.Net.Quic.QuicException : ConfigurationOpen failed. Error Code: INVALID_PARAMETER]]></message>
          <stack-trace><![CDATA[   at System.Net.Quic.Implementations.MsQuic.Internal.QuicExceptionHelpers.ThrowIfFailed(UInt32 status, String message, Exception innerException) in /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/Internal/QuicExceptionHelpers.cs:line 12
   at System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicConfigurationHandle.Create(QuicOptions options, QUIC_CREDENTIAL_FLAGS flags, X509Certificate certificate, SslStreamCertificateContext certificateContext, List`1 alpnProtocols) in /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/Interop/SafeMsQuicConfigurationHandle.cs:line 165
   at System.Net.Quic.Implementations.MsQuic.Internal.SafeMsQuicConfigurationHandle.Create(QuicClientConnectionOptions options) in /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/Interop/SafeMsQuicConfigurationHandle.cs:line 56
   at System.Net.Quic.Implementations.MsQuic.MsQuicConnection..ctor(QuicClientConnectionOptions options) in /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicConnection.cs:line 174
   at System.Net.Quic.Implementations.MsQuic.MsQuicImplementationProvider.CreateConnection(QuicClientConnectionOptions options) in /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/MsQuicImplementationProvider.cs:line 19
   at System.Net.Quic.QuicConnection..ctor(QuicImplementationProvider implementationProvider, QuicClientConnectionOptions options) in /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 44
   at System.Net.Quic.QuicConnection..ctor(QuicImplementationProvider implementationProvider, EndPoint remoteEndPoint, SslClientAuthenticationOptions sslClientAuthenticationOptions, IPEndPoint localEndPoint) in /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 37
   at System.Net.Quic.Tests.QuicTestBase`1.CreateQuicConnection(IPEndPoint endpoint) in /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 71
   at System.Net.Quic.Tests.QuicTestBase`1.<>c__DisplayClass32_0.<<RunClientServer>b__1>d.MoveNext() in /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 170
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /home/furt/github/wfurt-runtime/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 64
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /home/furt/github/wfurt-runtime/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 91
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /home/furt/github/wfurt-runtime/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 55
   at System.Net.Quic.Tests.QuicTestBase`1.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions) in /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 157
   at System.Net.Quic.Tests.QuicStreamTests`1.BasicTest() in /home/furt/github/wfurt-runtime/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicStreamTests.cs:line 25
--- End of stack trace from previous location ---]]></stack-trace>
        </failure>
```

I will investigate as well as I'll put in some instrumentation to find out more on CI failures.

**Comment by wfurt** [comment] 2021-08-04 16:08
The `Error Code: CONNECTION_REFUSED` looks like symptoms of  #55979. The difference between this and other tests is `iterations: 100,` so we run 100 runs in tight loop.

**Comment by ManickaP** [comment] 2021-08-10 17:11
Triage: closing as a dupe, we can reopen if it turns out it isn't.
Duplicate of  #55979

**Closed by ManickaP** 2021-08-10 17:11 UTC
Labels: test-run-core, area-System.Net.Quic

**Comment by karelz** [comment] 2021-08-13 09:23
Duplicate of #55979
