### ISSUE TITLE
Exception occurs while deserializing a System.RunTimeType Property

### ISSUE THREAD

**Issue by sethuramkumar** [dotnet/runtime#80590] opened 2023-01-12 16:37 UTC
### .NET version

Net 6.0

### Did it work in .NET Framework?

No

### Issue description

I am trying to deserialize a Type property.
I have added System.RuntimeType in KnownTypes of Serializer and deserializer by declaring typeof(Type.GetType()).
Serialization works properly, but in Deserialization facing the below exception:

![image](https://user-images.githubusercontent.com/92511047/212124954-37700933-6737-4c5b-8435-712f33508949.png)

### Steps to reproduce
1.Add System.RuntTimeType in Known types of Serializer and Deserializer.
2.Serialize the property using DataContractSerializer.
3.And then Deserialize.

Exception will occur:
![image](https://user-images.githubusercontent.com/92511047/212124954-37700933-6737-4c5b-8435-712f33508949.png)

**Comment by mairaw** [comment] 2023-01-13 00:58
Actually transferred to runtime repo now.

**Comment by sethuramkumar** [comment] 2023-01-18 10:11
Any update on this?

**Comment by elachlan** [comment] 2023-01-31 22:46
@sethuramkumar could you please provide a minimum viable reproduction of the error?

**Comment by sethuramkumar** [comment] 2023-02-07 11:22
Hi @elachlan
please find the stack trace below:System.Runtime.Serialization.SerializationException
  HResult=0x8013150C
  Message=The constructor with parameters (SerializationInfo, StreamingContext) is not found in ISerializable type 'System.RuntimeType'.
  Source=System.Runtime.Serialization
  StackTrace:
   at System.Runtime.Serialization.ClassDataContract.ClassDataContractCriticalHelper.GetISerializableConstructor()
   at System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.ReadISerializable(ClassDataContract classContract)
   at System.Runtime.Serialization.XmlFormatReaderGenerator.CriticalHelper.GenerateClassReader(ClassDataContract classContract)
   at System.Runtime.Serialization.XmlFormatReaderGenerator.GenerateClassReader(ClassDataContract classContract)
   at System.Runtime.Serialization.ClassDataContract.get_XmlFormatReaderDelegate()
   at System.Runtime.Serialization.ClassDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 id, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
   at System.Runtime.Serialization.ClassDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 id, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
   at System.Runtime.Serialization.CollectionDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 id, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
   at System.Runtime.Serialization.ClassDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   at System.Runtime.Serialization.DataContractSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObject(XmlDictionaryReader reader)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObject(Stream stream)

**Comment by StephenMolloy** [comment] 2023-02-16 22:37
Based on the stack trace, it looks like RunTimeType is advertising that it is `ISerializable` but does not provide the serializable constructor. Moving to System.Runtime.

**Comment by sethuramkumar** [comment] 2023-04-26 03:17
Any updates on this?

**Comment by tannergooding** [comment] 2023-08-14 18:23
Similar here @GrabYourPitchforks. What's the current policy on implementing `ISerializable` and the corresponding constructors/etc moving forward?

**Comment by jkotas** [comment] 2023-11-01 13:17
RuntimeType is not binary serializable in .NET Core/5+. (It was binary serializable in .NET Framework - https://github.com/microsoft/referencesource/blob/51cf7850defa8a17d815b4700b67116e3fa283c2/mscorlib/system/rttype.cs#L85.)

We are not introducing any new binary serializable types per https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md#net-6-nov-2021.

**Comment by StephenMolloy** [comment] 2023-11-07 22:34
This was reported as a problem with DataContractSerializer, not binary formatter.

**Comment by jkotas** [comment] 2023-11-07 22:52
RuntimeType implementation and behavior is by design.

Do you see anything to fix in DataContractSerializer?

**Comment by StephenMolloy** [comment] 2023-11-07 23:11
Nevermind. I skipped right over the part about this not working in .Net 4.x either.

**Closed by StephenMolloy** 2023-11-07 23:11 UTC
Labels: area-Serialization, needs-further-triage
