### ISSUE TITLE
Test failure readytorun/tests/mainv1/mainv1.sh

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#85442] opened 2023-04-27 02:43 UTC
Run: [runtime-coreclr jitstress 20230425.5](https://dev.azure.com/dnceng-public/public/_build/results?buildId=252731&view=ms.vss-test-web.build-test-results-tab&runId=4906396&resultId=118796&paneView=debug)

Failed test:
```
coreclr linux x64 Checked jitstress2 @ Ubuntu.1804.Amd64.Open

- readytorun/tests/mainv1/mainv1.sh

coreclr linux arm64 Checked jitstress2 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8

- readytorun/tests/mainv1/mainv1.sh
- readytorun/tests/mainv2/mainv2.sh

coreclr osx arm64 Checked jitstress2 @ OSX.1200.ARM64.Open

- readytorun/tests/mainv1/mainv1.sh
- readytorun/tests/mainv2/mainv2.sh
```
**Error message:**
```
Assert failure(PID 8409 [0x000020d9], Thread: 8495 [0x212f]): Assertion failed '(unsigned)TypeGet(value) < ArrLen(genTypeSizes)' in 'Internal.TypeSystem.Ecma.MetadataExtensions:GetDecodedCustomAttribute(Internal.TypeSystem.Ecma.EcmaMethod,System.String,System.String):System.Nullable1[System.Reflection.Metadata.CustomAttributeValue1[Internal.TypeSystem.TypeDesc]]' during 'Physical promotion' (IL size 93; hash 0xe1e354cb; FullOpts)

File: /__w/1/s/src/coreclr/jit/compiler.hpp Line: 458
Image: /datadisks/disk1/work/A4170970/p/corerun
[createdump] waitpid() returned successfully (wstatus 00000000)
/datadisks/disk1/work/A4170970/w/AA2709AD/e/readytorun/tests/mainv1/mainv1.sh: line 231:  8409 Aborted                 (core dumped) $CORE_ROOT/corerun $CORE_ROOT/crossgen2/crossgen2.dll --map -r:$CORE_ROOT/*.dll -r:IL_DLLS/fieldgetter.dll -r:IL_DLLS/mainv1.dll -o:test.dll ../testv1/test/test.dll

Return code:      1
Raw output file:      /datadisks/disk1/work/A4170970/w/AA2709AD/uploads/Reports/readytorun.tests/mainv1/mainv1.output.txt
Raw output:
BEGIN EXECUTION
[createdump] Gathering state for process 8409 corerun
[createdump] Crashing thread 212f signal 6 (0006)
[createdump] Writing crash report to file /home/helixbot/dotnetbuild/dumps/coredump.8409.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.8409.dmp
[createdump] Written 113864704 bytes (27799 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 529ms
Crossgen failed with exitcode: 134
Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 4/26/2023 5:48:43 AM
Processing /home/helixbot/dotnetbuild/dumps/coredump.8409.dmp.crashreport.json
Printing stacktrace from '/home/helixbot/dotnetbuild/dumps/coredump.8409.dmp.crashreport.json'
Invoking llvm-symbolizer --pretty-print
Stack trace:
Thread Id: 0x20d9
Child SP               IP Call Site
0x7ffd6a3ba380 0x7f4ba279e66e libcoreclr.so!MethodDesc::GetMethodDescChunk() const at /__w/1/s/src/coreclr/vm/method.hpp:2326:51
(inlined by) MethodDesc::GetMethodTable_NoLogging() const at /__w/1/s/src/coreclr/vm/method.hpp:3415:31
(inlined by) MethodDesc::GetMethodTable() const at /_w/1/s/src/coreclr/vm/method.hpp:3424:12
(inlined by) CEEInfo::getMethodClass(CORINFO_METHOD_STRUCT) at /_w/1/s/src/coreclr/vm/jitinterface.cpp:8585:44
0x7ffd6a3ba410 0x7f4b9e639075 libclrjit.so!Compiler::eeGetMethodFullName(CORINFO_METHOD_STRUCT, bool, bool, char*, unsigned long)::$_3::operator()() const at /_w/1/s/src/coreclr/jit/eeinterface.cpp:402:9
(inlined by) Compiler::eeRunFunctorWithSPMIErrorTrap<Compiler::eeGetMethodFullName(CORINFO_METHOD_STRUCT, bool, bool, char, unsigned long)::$3>(Compiler::eeGetMethodFullName(CORINFO_METHOD_STRUCT, bool, bool, char, unsigned long)::$3)::{lambda(Compiler::eeGetMethodFullName(CORINFO_METHOD_STRUCT, bool, bool, char, unsigned long)::$3*)#1}::operator()(Compiler::eeGetMethodFullName(CORINFO_METHOD_STRUCT, bool, bool, char, unsigned long)::$_3*) const at /_w/1/s/src/coreclr/jit/compiler.h:8087:66
(inlined by) Compiler::eeRunFunctorWithSPMIErrorTrap<Compiler::eeGetMethodFullName(CORINFO_METHOD_STRUCT, bool, bool, char, unsigned long)::$3>(Compiler::eeGetMethodFullName(CORINFO_METHOD_STRUCT, bool, bool, char, unsigned long)::$3)::{lambda(Compiler::eeGetMethodFullName(CORINFO_METHOD_STRUCT, bool, bool, char, unsigned long)::$_3*)#1}::_invoke(Compiler::eeGetMethodFullName(CORINFO_METHOD_STRUCT, bool, bool, char, unsigned long)::$_3*) at /__w/1/s/src/coreclr/jit/compiler.h:8087:48
0x7ffd6a3ba4b0 0x7f4ba27a5339 libcoreclr.so!CEEInfo::runWithSPMIErrorTrap(void ()(void), void*) at /_w/1/s/src/coreclr/vm/jitinterface.cpp:10691:5
0x7ffd6a3ba4c0 0x7f4b9e638575 libclrjit.so!Compiler::eeGetMethodFullName(CORINFO_METHOD_STRUCT*, bool, bool, char


Stack trace
   at readytorun_tests._mainv1_mainv1_._mainv1_mainv1_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Queued | Pipeline | Pipeline_Configuration | OS | Arch | Test | Outcome | Properties | BuildReason
-- | -- | -- | -- | -- | -- | -- | -- | --
2023-04-26T06:10:04.217Z | runtime-coreclr jitstress | Checked-jitstress2 | osx.1200.arm64.open | arm64 | readytorun/tests/mainv1/mainv1.sh | Failed | {"System.PhaseAttempt":"1","System.PhaseName":"run_test_p1__osx_arm64_checked","DefinitionId":"109","architecture":"arm64","System.JobName":"__default","System.StageName":"Build","Project":"public","System.StageAttempt":"1","operatingSystem":"OSX.1200.ARM64.Open","configuration":"Checked-jitstress2","System.JobAttempt":"1","BuildNumber":"20230425.5","DefinitionName":"runtime-coreclr jitstress","CollectionUri":"https://dev.azure.com/dnceng-public/","AzurePipelinesTestRunId":"4906774","System.JobId":"765fd5e9-e47f-5cb0-4cbf-499eaaaee93e","Reason":"Schedule","BuildId":"252731"} | Schedule
2023-04-26T05:27:22.852Z | runtime-coreclr jitstress | Checked-jitstress2 | ubuntu.1804.armarch.open | arm64 | readytorun/tests/mainv1/mainv1.sh | Failed | {"System.StageName":"Build","System.JobName":"__default","operatingSystem":"(Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8","configuration":"Checked-jitstress2","System.StageAttempt":"1","System.JobId":"34b2f53b-add1-5e74-7a39-5a11483297fc","Project":"public","BuildId":"252731","DefinitionName":"runtime-coreclr jitstress","architecture":"arm64","DefinitionId":"109","Reason":"Schedule","AzurePipelinesTestRunId":"4906414","System.PhaseName":"run_test_p1__linux_arm64_checked","CollectionUri":"https://dev.azure.com/dnceng-public/","System.JobAttempt":"1","BuildNumber":"20230425.5","System.PhaseAttempt":"1"} | Schedule
2023-04-26T05:25:12.735Z | runtime-coreclr jitstress | Checked-jitstress2 | ubuntu.1804.amd64.open.rt | x64 | readytorun/tests/mainv1/mainv1.sh | Failed | {"System.StageAttempt":"1","CollectionUri":"https://dev.azure.com/dnceng-public/","operatingSystem":"Ubuntu.1804.Amd64.Open","BuildId":"252731","System.JobAttempt":"1","Project":"public","DefinitionId":"109","System.JobId":"6dfec640-5b96-5d95-2a5b-7c236ea2d5c5","configuration":"Checked-jitstress2","System.JobName":"__default","Reason":"Schedule","DefinitionName":"runtime-coreclr jitstress","System.StageName":"Build","BuildNumber":"20230425.5","architecture":"x64","AzurePipelinesTestRunId":"4906396","System.PhaseAttempt":"1","System.PhaseName":"run_test_p1__linux_x64_checked"} | Schedule

**Comment by jakobbotsch** [comment] 2023-04-27 08:10
Duplicate of #85403

**Closed by jakobbotsch** 2023-04-27 08:10 UTC
Labels: arch-arm64, os-linux, os-mac-os-x, JitStress, arch-x64, area-CodeGen-coreclr, untriaged
