### ISSUE TITLE
Microsoft.Extensions.Configuration App binding adding to the initialized Collections, not replacing 

### ISSUE THREAD

**Issue by Cazzar** [dotnet/runtime#46988] opened 2021-01-14 15:31 UTC
## Background and Motivation

When defining a configuration that has some defaulted options that are a `List<T>` or an `array` type we might want to have the ability to provide a default list, but completely replaces the enumerable's contents with what is in the configuration file.

## Proposed API

```diff
namespace Microsoft.Extensions.Configuration
{
    public class BinderOptions
    {
        public bool BindNonPublicProperties { get; set; }
+        public bool OverrideLists { get; set; }
    }
}
```

## Usage Examples
Expanding upon [my original repo](https://github.com/Cazzar/ConfigurationArrayTest/blob/f36fa8ce04251cd7ca00f2989a5219c178bf0705/ConfigurationTest/Program.cs) as a base

``` C#
var config = new ConfigurationBuilder().AddNewtonsoftJsonStream(new MemoryStream(Encoding.ASCII.GetBytes("{ \"Example\": [ \"Item 2\" ] }"))).Build();
var obj = config.Get<ConfigType>(options => options.OverrideLists = true);
```

## Alternative Designs

This gives a similar action to `Newtonsoft.JSON`'s [ObjectCreationHandling](https://www.newtonsoft.com/json/help/html/DeserializeObjectCreationHandling.htm) option with the value of `Replace` which when handling an Object when deserializing to a class, it uses a new class with _no_ contents at all.

<hr>

### Description

Example Repo: https://github.com/Cazzar/ConfigurationArrayTest
To show the issue itself, simply running `dotnet run` should work

The issue itself seems to occur that if you have an initialization for an IEnumerable instead of having the option to Replace the contents on deserialization, it will append to the contents, making it impossible to use a strongly typed configuration instance with defaults in the case that they are not provided.

Testing this, it seems to show both a pattern within both System.Text.Json and the Newtonsoft.Json versions of configuration loading.

### Configuration
- Windows 10 Build 19042.685 NET 5.0.1 x64
- Doesn't seem to be configuration specific.

### Other information
Example output from my repo above:
```
Newtonsoft.JSON
Item Count: 2
Items in array: Item 1, Item 2

System.Net.Json
Item Count: 2
Items in array: Item 1, Item 2
```

In this case, I would expect only `Item 2` to exist in the arrays, effectively overwriting the bound object with the contents of the configuration.

From further speculation, this might not be specifically bound to the input type but by the Binding options not having the option to replace
An initial thought would be for this using Add without clearing the collection first: https://github.com/dotnet/runtime/blob/796cbeeec0a97428e97b92250cb9ff65aadf41de/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs#L423-L447

**Comment by CodeBlanch** [comment] 2021-01-15 00:36
@Cazzar Funny I just ran into this too. It seems to be working as designed given there are unit tests for the behavior, for example:

https://github.com/dotnet/runtime/blob/e3247adc4a81a55add33541e6bfc2ff74e261e41/src/libraries/Microsoft.Extensions.Configuration.Binder/tests/ConfigurationCollectionBindingTests.cs#L305-L332

What I ran into is in the case of `IReadOnlyCollection`...
```csharp
        public class Test
        {
            public IReadOnlyCollection<string> ReadOnlyValues { get; set; } = new[] { "default" };
        }
```
...configuration is completely ignored because you can't add to an existing `IReadOnlyCollection`.

My expectation was that "ReadOnlyValues" would be completely replaced if something was specified in the configuration.

**Comment by Cazzar** [comment] 2021-01-15 00:51
@CodeBlanch Interesting, even if it was a binding option that might be a reasonable solution, since if you were to use raw JSON parsing, it is possible, at least with Newtonsoft.JSON that you can replace instead of update.

I've got a potential workaround idea that I will try later today and update here for the solution.

Given that it is an expected pattern, breaking the current API would not be a good idea, I wouldn't be against some sort of binding options.

**Comment by safern** [comment] 2021-01-29 21:31
@Cazzar this definitely looks like by design and it would be a breaking change to "fix" this. What I might suggest if we wanted to support this scenario would be adding an option to BindingOptions that is something like: `OverrideLists` or something like that, that would trigger the behavior you're suggesting. 

Anyway,  were you able to find a workaround for this? If not I can help finding one. I think we might be able to close this issue?

**Comment by Cazzar** [comment] 2021-01-30 06:22
@safern I, unfortunately, couldn't find something that worked well enough for my use-case (though it may also relate to the need of the configuration being serialised back in place which was a dirty bit of code, to begin with). Since I was using it with `IOptions`, I had a fair bit to try including late-initializing the properties and ended up moving to the previous setup we had internally.

Given it does look like intended functionality as I mentioned in https://github.com/dotnet/runtime/issues/46988#issuecomment-760571860 an option within BindingOptions would probably be a good idea in the long run.

**Comment by safern** [comment] 2021-02-01 18:08
> Given it does look like intended functionality as I mentioned in #46988 (comment) an option within BindingOptions would probably be a good idea in the long run.

Would you mind submitting a formal API proposal to add that BindingOption as part of this or a new issue? 

Here are the instructions on how to do that: https://github.com/dotnet/runtime/blob/master/docs/project/api-review-process.md

**Comment by Cazzar** [comment] 2021-02-02 13:16
Because I would have just referenced this issue, I have updated the above description based off the process @safern

**Comment by safern** [comment] 2021-02-02 19:07
Thank you, @Cazzar. Based on the proposed API, would it be reasonable that the flag is named something like: `UseDefaultLists` or something that has to be set to true explicitly to trigger this behavior? Currently overriding the list is the default behavior, so I would like a flag that is explicit about turning on a new feature vs turning off an old behavior, does that make sense?

**Comment by CodeBlanch** [comment] 2021-02-02 19:16
@safern The behavior right now is to add to the list, if possible, otherwise it does nothing (the readonly case). The behavior we want to enable is to override whatever is there.

**Comment by safern** [comment] 2021-02-02 19:26
> @safern The behavior right now is to add to the list, if possible, otherwise it does nothing (the readonly case). The behavior we want to enable is to override whatever is there.

Sorry I mixed up things. You're right. The proposal looks good.

**Comment by terrajobst** [comment] 2021-02-09 19:25
* How important is this?
    - This is getting into the realm of the complicated serialization behavior.
    - It seems default values in collections are a bit of fringe behavior.
    - Let's close it for now until there is more evidence that we need this.
* General feedback:
    - It seems a bit weird to ask developers to make their collections settable; it would be more natural if the binder would call a `Clear()` method.
    - If the collection implements both `IList` and is settable, preferring the setter seems reasonable.

```C#
namespace Microsoft.Extensions.Configuration
{
    public partial class BinderOptions
    {
        // Already exists:
        // public bool BindNonPublicProperties { get; set; }
        public bool OverrideLists { get; set; }
    }
}
```

**Closed by terrajobst** 2021-02-09 19:25 UTC
Labels: api-ready-for-review, area-Extensions-Configuration
