### ISSUE TITLE
Disable producing NETStandard targeting pack in 5.0 branch

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [dotnet/runtime#33208] opened 2020-03-05 03:20 UTC
Net Standard 2.1 packages (with preview branding) are still being produced in 5.0 branches.

This issue was fixed in 3.1 - issue https://github.com/dotnet/runtime/issues/3800

Are we missing the fix in runtime repo?

**Comment by dagood** [comment] 2020-03-09 00:09
Duplicate of https://github.com/dotnet/runtime/issues/2294

**Closed by dagood** 2020-03-09 00:09 UTC
Labels: area-Infrastructure-installer, untriaged

**Comment by dagood** [comment] 2020-03-09 00:13
https://github.com/dotnet/runtime/issues/3800 covers disabling targeting packs from building during servicing builds only. We don't disable targeting pack builds in general in `master`/`preview` branches because we expect constant API breaks. NETStandard is a special case because it doesn't quite fit in with the repo.
