### ISSUE TITLE
System.Text.Json serialize exception with AllowNamedFloatingPointLiterals

### ISSUE THREAD

**Issue by Samotorcan** [dotnet/runtime#63740] opened 2022-01-13 13:36 UTC
### Description

Serializing an `new object()` with System.Text.Json throws an InvalidOperationException when using `NumberHandling = JsonNumberHandling.AllowNamedFloatingPointLiterals` in .NET 6.0.

### Reproduction Steps

.NET 6.0 project.

```C#
JsonSerializer.Serialize(new object(), new JsonSerializerOptions { NumberHandling = JsonNumberHandling.AllowNamedFloatingPointLiterals });
```

Throws an exception:
```
System.InvalidOperationException: 'Operation is not valid due to the current state of the object.'
```

Changing the `NumberHandling` to `Strict` produces the expected JSON `{}`.

### Expected behavior

`new object()` should be serialized to JSON `{}`.

### Actual behavior

Exception thrown:
```
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at System.Text.Json.Serialization.JsonConverter`1.WriteNumberWithCustomHandling(Utf8JsonWriter writer, T value, JsonNumberHandling handling)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteUsingSerializer[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.WriteStringUsingSerializer[TValue](TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
```

### Regression?

Work correctly in .NET 5.0.

### Known Workarounds

Use Strict option in NumberHandling if possible.

### Configuration

.NET 6.0

**Comment by eiriktsarpalis** [comment] 2022-01-14 10:55
Duplicate of https://github.com/dotnet/runtime/issues/61995. Will be fixed in .NET 6 in servicing.

**Closed by eiriktsarpalis** 2022-01-14 10:55 UTC
Labels: area-System.Text.Json, untriaged
