### ISSUE TITLE
Inconsistent internal field handling between `JsonSourceGenerationMode`s

### ISSUE THREAD

**Issue by nxtn** [dotnet/runtime#70928] opened 2022-06-18 10:09 UTC
### Description

`JsonSourceGenerationMode.Metadata` and `JsonSourceGenerationMode.Serialization` handle internal fields differently in serialization.

### Reproduction Steps

```cs
using System.Text.Json;
using System.Text.Json.Serialization;

internal sealed class Root
{
    internal string key = "value";
}

[JsonSourceGenerationOptions(IncludeFields = true, GenerationMode = JsonSourceGenerationMode.Metadata)]
[JsonSerializable(typeof(Root))]
internal sealed partial class MetadataContext : JsonSerializerContext
{
}

[JsonSourceGenerationOptions(IncludeFields = true, GenerationMode = JsonSourceGenerationMode.Serialization)]
[JsonSerializable(typeof(Root))]
internal sealed partial class SerializationContext : JsonSerializerContext
{
}

internal static class Program
{
    private static JsonSerializerOptions Options => new()
    {
        IncludeFields = true,
    };

    private static void Main()
    {
        var root = new Root();

        // {}
        System.Console.WriteLine(JsonSerializer.Serialize(root, Options));

        // {}
        System.Console.WriteLine(JsonSerializer.Serialize(root, new MetadataContext(Options).Root));

        // {"key":"value"}
        System.Console.WriteLine(JsonSerializer.Serialize(root, new SerializationContext(Options).Root));
    }
}
```

### Expected behavior

The behaviors should be consistent between modes.

### Actual behavior

`JsonSourceGenerationMode.Metadata` doesn't include internal fields.
`JsonSourceGenerationMode.Serialization` includes internal fields.

### Configuration

.NET 6 and .NET 7 Preview 5

**Comment by eiriktsarpalis** [comment] 2022-07-19 12:45
It looks like the metadata source generator does not include fields when `IncludeFields` is set to true.

**Comment by eiriktsarpalis** [comment] 2023-06-15 20:33
This was addressed by https://github.com/dotnet/runtime/pull/87136. The reproducing code will now consistently produce `{}` for all configurations.

**Closed by eiriktsarpalis** 2023-06-15 20:33 UTC
Labels: bug, area-System.Text.Json, source-generator
