### ISSUE TITLE
DateTime.ToString() on alpine-3.17 are broken

### ISSUE THREAD

**Issue by saintogod** [dotnet/runtime#80551] opened 2023-01-12 06:21 UTC
### Describe the Bug

Latest alpine image has incorrect output of DateTime.ToString("G").

### Steps to Reproduce

1. Create a console project 
    `dotnet new console -n TestLocale`
2. Make sure that TestLocale.csproj is using .net 6
3. Modify Program.cs with the following content
```csharp
Console.WriteLine(DateTime.Now.ToString("G", System.Globalization.CultureInfo.GetCultureInfo("en-US")));
```
4. run `docker run -it --rm  -w /app -v ${PWD}:/app mcr.microsoft.com/dotnet/sdk:6.0.405-alpine3.17 dotnet run .`

Expect the output to be "1/12/2023 5:27:10 AM", but got "1/12/2023 5:27:10AM", missing the whitespace before "AM".

### Other Information

The same code works as expected on alpine3.16 `docker run -it --rm  -w /app -v ${PWD}:/app mcr.microsoft.com/dotnet/sdk:6.0.405-alpine3.16 dotnet run .`

### Output of `docker version`

Client: Docker Engine - Community
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:28:08 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:25:58 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.15
  GitCommit:        5b842e528e99d4d4c1686467debf2bd4b88ecd86
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### Output of `docker info`

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.14.1)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 14
  Running: 8
  Paused: 0
  Stopped: 6
 Images: 99
 Server Version: 20.10.22
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b842e528e99d4d4c1686467debf2bd4b88ecd86
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.102.1-microsoft-standard-WSL2
 Operating System: Ubuntu 20.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 24.95GiB
 Name: QINGYUAN
 ID: SW6C:R6HF:C25T:LZHI:CZXV:EU63:E45Q:XZOM:TNF6:MCTG:OCZ6:7VEC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support

**Comment by Clockwork-Muse** [comment] 2023-01-12 16:01
> So either this is a bug in the ICU library itself or with how the .NET runtime is interacting with this newer version of ICU. 

There's a third, more likely, option: that ICU has decided that there shouldn't be a space there, and this is the correct output.  

There's no guarantees at all about what the output of formatting looks for anything that is not the invariant culture.  Formats change regularly.  If you have a test explicitly looking for this output, that test has most likely been written in error (and would not succeed on Windows legacy platforms or anywhere the user has customized their formats).  When you test formatting operations, either test with a custom locale that doesn't change, or only check that the output is nonempty.  If you are doing data interchange, you should be using ISO format in the invariant locale, period.

**Comment by tarekgh** [comment] 2023-01-12 16:23
Here is the CLDR change which is showing in `ICU 72` https://unicode-org.atlassian.net/browse/CLDR-14032. I am closing this as it is not a bug in .NET. It is a change in the Unicode data which get used in .NET. We need to use whatever ICU/CLDR decide to have as it is the correct thing decided by the Unicode standard.

**Closed by tarekgh** 2023-01-12 16:23 UTC
Labels: area-System.Globalization, needs-author-action
