### ISSUE TITLE
Executing a SOAP rating service request in a .NET 7 COM-enabled assembly fails with 'The given assembly name was invalid' 

### ISSUE THREAD

**Issue by 1KByington** [dotnet/runtime#82640] opened 2023-02-22 19:25 UTC
### Description

We have a .NET class library assembly COM server that executes a client call to a SOAP service. It works fine in .NET framework 6.x but when we change the target framework to .NET 7.x it throws the exception 'The given assembly name was invalid' at the point where the proxy function for the SOAP service is called. Changing the target framework was the only change made. The application works as expected when the target is .NET 6.x.

Microsoft support case #2212020010001039

### Reproduction Steps

See the included example project which duplicates the error.

### Expected behavior

We would expect the application to work the same (no error when executing the SOAP service proxy method) when the only change to the project is to change the target framework from .NET 6 to .NET 7.

### Actual behavior

The exception error message 'The given assembly name was invalid' is generated when the .NET assembly COM server attempts to invoke a SOAP web service method.

### Regression?

Works as expected in .NET 6

### Known Workarounds

Workaround is to target framework 6.0, not 7.0.

### Impact

Prevents upgrading from .NET 6 to .NET 7.

### Configuration

.NET version:  7.x
OS:  Windows 10 and 11 and Windows Server 2019
Architecture:  X86, Any CPU, x64

**Comment by jkotas** [comment] 2023-02-24 20:02
This is regression introduced by https://github.com/dotnet/runtime/pull/62095/files#diff-e09e7f6880244829d1c3b16e19b451ab04d059a7df0d8a367cd3fd08230c9096R126 . It is not safe to assume that alc.Name is going to be a valid assembly name.

**Comment by jkotas** [comment] 2023-02-24 20:03
cc @buyaa-n @vitek-karas @teo-tsirpanis

**Comment by buyaa-n** [comment] 2023-02-27 17:19
> This is regression introduced by https://github.com/dotnet/runtime/pull/62095/files#diff-e09e7f6880244829d1c3b16e19b451ab04d059a7df0d8a367cd3fd08230c9096R126 

Right, this is duplicate of https://github.com/dotnet/runtime/issues/80387. The fix is easy, just not decided yet if we should keep the ALC name (by replacing the special characters or just using same name for each ALC).  Anyway, we will fix this soon and port into 7.0 , closing this issue as duplicate.

**Closed by buyaa-n** 2023-02-27 17:19 UTC
Labels: area-System.Reflection, untriaged, regression-from-last-release
