### ISSUE TITLE
System.IO.FileSystem.AccessControl project has problems loading in Visual Studio

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#47809] opened 2021-02-03 18:26 UTC
1. I synced my local main branch to the latest bits.
2. I successfully built everything successfully using:
    ```
    build.cmd clr+libs+libs.pretest -rc release
    ```
3. Also successfully built and executed the unit tests in IO.FileSystem.AccessControl:
    ```
    cd src/libraries/System.IO.FileSystem.AccessControl/tests
    dotnet build /t:Test
    ````
4. But when I open the FileSystem.AccessControl.sln file,  all the types that exist both in `net461-windows` and `net6.0-windows`, show the following error message and red squiggle:
    ```
    The type 'FileSystemRights' exists in both 'System.IO.FileSystem.AccessControl, Version=6.0.0.0, Culture=neutral,
    PublicKeyToken=b03f5f7f11d50a3a' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
    System.IO.FileSystem.AccessControl.Tests (net461-windows)
    ```
    ```
    The call is ambiguous between the following methods or properties: 'FileSystemAclExtensions.CreateDirectory(DirectorySecurity, string)'
    and 'FileSystemAclExtensions.CreateDirectory(DirectorySecurity, string)'
    System.IO.FileSystem.AccessControl.Tests (net6.0-windows)
    ```
    ```
    Ambiguity between 'FileSystemAccessRule.FileSystemRights' and 'FileSystemAccessRule.FileSystemRights'
    System.IO.FileSystem.AccessControl.Tests (net6.0-windows)
    ```
    ```
    MSB4018
    The "ResolvePackageDependencies" task failed unexpectedly.
    System.ArgumentException: An item with the same key has already been added.
       at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
       at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
       at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
       at Microsoft.NET.Build.Tasks.ResolvePackageDependencies.ExecuteCore()
       at Microsoft.NET.Build.Tasks.TaskBase.Execute()
       at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
       at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	System.Security.Principal.Windows (src\System.Security.Principal.Windows)	C:\Program 
    Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	186
    ```

These errors make it very difficult to work with this assembly:
- I can't go to a type definition using F12.
- I can't get intellisense to pop up.
- I cannot build directly from VS (I have to do it from the command line).
- I can't run unit tests from VS (I have to attach VS to a command line execution).

Any help would be greatly appreciated. Let me know if you'd like me to show you a live repro.

cc @Anipik

**Comment by eugene-shcherbo** [comment] 2021-02-08 21:14
Hey @carlossanlop , have similar errors actually when working on the `src/libraries/System.Threading.AccessControl/tests`. In my case there is one additional error:

> Missing partial modifier on declaration of type 'MutexAccessRule'; another partial declaration of this type exists System.Threading.AccessControl (netstandard2.0-windows)

It seems that the reason of this happening in my case is because while compiling the code for some targets which shouldn't support mutex api the compiler creates in the obj directory `.cs` files with `.notsupported` suffix in the name (e.g. `System.Security.AccessControl.notsupported.cs`). Those files contain definitions of my classes marked with the `partial` keyword and some methods of the classes throw this `PlatformNotSupportedException`. So Visual Studio somehow sees two definitions of classes and shows the errors.

By the way, if I remove targets which folders in the obj directory contain those 'notsupported' files (or just remove files from the directory), then everything works fine. And I sometimes can build the solution from V, but sometimes can not.

Sorry, I don't know a lot about the building process, so some my conclusions might be wrong or nonsense, but probably your issue is similar to the one I have, so it might help to find the source of the problem.

**Comment by safern** [comment] 2021-02-08 22:10
@Anipik could you take a look at this when possible?

**Comment by ericstj** [comment] 2021-07-29 01:21
So the building errors no longer seem to reproduce in the latest, but the intellisense errors still repro. 

I debugged the design time build and found the following in the `$(NetCoreAppCurrent)-windows` binlog:
```
GeneratePlatformNotSupportedAssemblyMessage = SR.PlatformNotSupported_AccessControl
TargetFramework = net6.0-windows
TargetsWindows = true
```
This implies a problem with evaluation.  GeneratePlatformNotSupportedAssemblyMessage should not be set for Windows.  It looks like this is due to ordering, we cannot use `TargetFramework`-derived properties at all in the project file, we can only use `TargetFramework` itself.

The reason this doesn't reproduce on commandline build is due to TargetFramework being passed as a global property in this case.

Essentially the cause is the same as here: https://github.com/dotnet/runtime/issues/33427#issuecomment-597634844

I was able to workaround this by changing the conditions in the project file to use TargetFramework instead of TargetsWindows.  I wonder if we should do this across the repo.

**Comment by safern** [comment] 2021-07-29 02:55
> TargetsWindows. I wonder if we should do this across the repo.

If we do that, should we remove those properties entirely?

**Comment by ViktorHofer** [comment] 2021-07-29 07:25
> If we do that, should we remove those properties entirely?

Unfortunately the SDK/msbuild doesn't yet offer a good alternative to what we express with i.e. `TargetsUnix`. You would want `TargetsUnix` to be true for any rid that derives from `unix` where-as if you check for `TargetPlatformIdentifier` you will get back `Unix` when targeting `net6.0-Unix` without a way to check if the `TargetPlatformIdentifier` is compatible with another one (at least with the existing msbuild property functions: https://docs.microsoft.com/en-us/visualstudio/msbuild/property-functions?view=vs-2019#msbuild-targetframework-and-targetplatform-functions

We essentially would need the following function: `IsTargetFrameworkWithPlatformCompatible(string targetFrameworkTarget, string targetPlatformCandidate)` and/or `IsTargetPlatformCompatible(string targetPlatformTarget, string targetPlatformCandidate)`.

cc @rainersigwald

**Comment by ViktorHofer** [comment] 2021-07-29 07:31
> I was able to workaround this by changing the conditions in the project file to use TargetFramework instead of TargetsWindows. I wonder if we should do this across the repo.

For cases where we don't check on a parent rid, like i.e. TargetsUnix but on a rid which doesn't have any childs like TargetsWindows I'm all in for replacing those with TargetPlatformIdentifier checks, i.e.: `'$(TargetPlatformIdentifier)' == 'windows'`. As mentioned in the post above, I don't think we yet have a good way to check for TargetPlatformIdentifier inheritance.

**Comment by ericstj** [comment] 2021-07-29 16:20
> I'm all in for replacing those with TargetPlatformIdentifier checks

I don't believe that works either since `TargetPlatformIdentifier` is derived from `TargetFramework` and there simply is no code that can do that work between where the designer sets `TargetFramework` and where the project consumes it.  Using any TargetFramework-derived properties in other project propertygroups does not work in design time build.

Here's a sample:
```
  <PropertyGroup>
    <TargetFrameworks>$(NetCoreAppCurrent)-windows;$(NetCoreAppCurrent)</TargetFrameworks>
    <!-- Design time build effectively sets TargetFramework here through it's use of SetProperty -->
  </PropertyGroup>

  <PropertyGroup>
    <TestTargetsWindows>$(TargetsWindows)</TestTargetsWindows>
    <TestTargetFrameworkIdentifier>$(TargetFrameworkIdentifier)</TestTargetFrameworkIdentifier>
    <TestTargetFramework>$(TargetFramework)</TestTargetFramework>
    <TestTargetPlatformIdentifier>$(TargetPlatformIdentifier)</TestTargetPlatformIdentifier>
  </PropertyGroup>
```

The design time binlog for this can show the values:
![image](https://user-images.githubusercontent.com/8918108/127528128-d1713f9d-4d44-4642-8364-5557634acfb3.png)

**Comment by ViktorHofer** [comment] 2021-07-29 16:37
The idea is not to pass in a derived property but make use the msbuild property functions which always accept `$(TargetFramework)` as an input. The second function is just for completeness to be used inside a target or anywhere where design time builds don't matter.

This should already work today both in design time builds and normal builds:

```
  <PropertyGroup>
    <TargetFrameworks>$(NetCoreAppCurrent)-windows;$(NetCoreAppCurrent)</TargetFrameworks>
    <!-- Design time build effectively sets TargetFramework here through it's use of SetProperty -->
  </PropertyGroup>

  <PropertyGroup>
    <TestTargetsWindows>$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'</TestTargetsWindows>
    <TestTargetFrameworkIdentifier>$([MSBuild]::GetTargetFrameworkIdentifier($(TargetFramework)'))</TestTargetFrameworkIdentifier>
    <TestTargetFramework>$(TargetFramework)</TestTargetFramework>
    <TestTargetPlatformIdentifier>$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)'))</TestTargetPlatformIdentifier>
  </PropertyGroup>
```

An example with my proposal from above:

```
  <PropertyGroup>
    <TargetFrameworks>$(NetCoreAppCurrent)-linux;$(NetCoreAppCurrent)-osx;$(NetCoreAppCurrent)</TargetFrameworks>
    <!-- Design time build effectively sets TargetFramework here through it's use of SetProperty -->
  </PropertyGroup>

  <PropertyGroup>
    <TestTargetsUnix>$([MSBuild]::IsTargetFrameworkWithPlatformCompatible('$(TargetFramework)', 'unix'))</TestTargetsUnix>
  </PropertyGroup>
```

**Comment by ericstj** [comment] 2021-07-29 17:01
I see, sorry for misunderstanding.  Property functions are helpful as a way to do the calculation inline, but given we can't satisfy all cases it might be a bit of an unexpected cliff when you needed a runtime compatibility decision as you mentioned.  The concept of TargetPlatform compatibility/hierarchy is actually not one present in the product so even if we had more property functions added it won't help us calculate that.  Another blocker is that those property functions reject pre-net5.0 TFMs today so this would hinder our ability to adopt this for some time.  Now if we could define custom property functions, I think that would solve this and give the best user experience, but not supported AFAIK.

Maybe we can gather some data about which properties are used and at what frequency to help us understand what to do.  For instance: if we can recommend a subset of patterns that are acceptable, and for cases where nothing is acceptable we convert to using Items instead of properties?

**Comment by FWest98** [comment] 2021-07-29 17:21
I'm running into these exact same issues for `System.DirectoryServices.AccountManagement`. After updating the solution file and DotGenFacades (https://github.com/dotnet/runtime/issues/51601#issuecomment-888488959), I got these "ambiguous" IntelliSense errors; building and testing worked without problems. Replacing the NotSupportedAssemblyMessage condition with `'$(TargetPlatformIdentifier)' != 'windows'` solved the IntelliSense issues, but caused the build to fail. I have tried a number of combinations of conditions, but all of them cause either IntelliSense or the build to fail. Is there anything concrete I can do now to at least get my local development setup working?

**Comment by ViktorHofer** [comment] 2021-07-29 17:28
For properties, instead of doing `'$(TargetPlatformIdentifier)' != 'windows'` you want to do the following: 

`$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'`

For items you can use the former one. That has do with the evaluation order in msbuild (properties first, then items).

**Comment by FWest98** [comment] 2021-07-29 17:58
Great! And then, since these functions don't accept pre-net5.0 TFMs, you also need to remove `netcoreapp3.1-windows` from the `TargetFrameworks`. Now it works!

**Comment by ericstj** [comment] 2021-07-29 20:15
Honestly in most cases here I'm not seeing much usage that would get more complicated by just having some comparisons with TargetFramework values, or even TargetFramework.EndsWith comparisons.  Most of these conditions are referring to literal values that are a couple lines up in the same file.

**Comment by ViktorHofer** [comment] 2022-05-10 10:42
This was fixed with https://github.com/dotnet/runtime/commit/20e8f905d05f2d8f390d0e2ef10f1a4a1289967c. Closing.

**Closed by ViktorHofer** 2022-05-10 10:42 UTC
Labels: area-Infrastructure-libraries
