### ISSUE TITLE
Finally statement is not always been executed in Linux container

### ISSUE THREAD

**Issue by cdlliuy** [dotnet/runtime#67214] opened 2022-03-28 01:07 UTC
### Description

The .net doc https://docs.microsoft.com/en-us/dotnet/standard/exceptions/how-to-use-finally-blocks#:~:text=A%20finally%20block%20always%20executes,block%20to%20catch%20an%20ArgumentOutOfRangeException.  provides an example that  `A finally block always executes, regardless of whether an exception is thrown.`

When executing the mentioned code example in above docs on Windows  with compiled dll,  the statement inside finally was executed as expected. 

```
>> Debug/net5.0/win-x64» dotnet yingtestproject.dll                                                                  
Error: System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'length')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   at yingtestproject.Program.Main(String[] args) in C:\Users\lying\source\repos\yingtestproject\yingtestproject\Program.cs:line 54
Unhandled exception. System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'length')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   at yingtestproject.Program.Main(String[] args) in C:\Users\lying\source\repos\yingtestproject\yingtestproject\Program.cs:line 54
>> Debug/net5.0/win-x64» dotnet yingtestproject.dll                                                                  
Error: System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'length')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   at yingtestproject.Program.Main(String[] args) in C:\Users\lying\source\repos\yingtestproject\yingtestproject\Program.cs:line 54
Unhandled exception. System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'length')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   at yingtestproject.Program.Main(String[] args) in C:\Users\lying\source\repos\yingtestproject\yingtestproject\Program.cs:line 54
This statement is always executed.
```

But when running the application inside a linux container (by deploying the container on k8s as a pod),  the pod keeps crashing with exit code 134 (SIGABRT)

Then,   I tried to add sleep in Dockerfile to see why it crashes.  Inside the linux container,  when executing the dll as the same way as windows,  I got below: 

```
>> root@yingtestapp-raw-deployment-6f9c9cd7-2dkzf:/app# dotnet yingtestproject.dll
Error: System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'length')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   at yingtestproject.Program.Main(String[] args) in C:\Users\lying\source\repos\yingtestproject\yingtestproject\Program.cs:line 54
Unhandled exception. System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'length')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Array destinationArray, Int32 length)
   at yingtestproject.Program.Main(String[] args) in C:\Users\lying\source\repos\yingtestproject\yingtestproject\Program.cs:line 54
Aborted
```

Here is my docker file: 
```
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS dotnet-tools
WORKDIR /app

RUN dotnet tool install -g dotnet-certificate-tool --version 2.0.0 \
    && dotnet tool install -g dotnet-dump \
    && dotnet tool install -g dotnet-trace \
    && dotnet tool install -g dotnet-counters \
    && dotnet tool install -g dotnet-symbol

FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY ./*.png ./
COPY ./*.jpg ./
COPY ./*.sh ./
COPY ./build/* ./
EXPOSE 80

RUN apt-get update \
    && apt-get install -y curl \
    && apt-get install -y procps \
    libc6-dev \
    libgdiplus \
    libx11-dev

COPY --from=dotnet-tools /root/.dotnet/tools /root/.dotnet/tools/
ENV PATH="${PATH}:/root/.dotnet/tools"

ENV LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8

ENTRYPOINT ["./run.sh"]
```

Here is the content of run.sh
```
echo "Running program with app.sh"
exec dotnet ./yingtestproject.dll
```

### Reproduction Steps

see above description 

### Expected behavior

I wonder whether the difference handling of Finally is expected on different OS.  If the root cause is the OS level handling for uncaughted exception, then the statement for "finally" in the docs side is "incorrect", and need to be midified. 

### Actual behavior

see above description

**Comment by danmoseley** [comment] 2022-03-28 01:33
Can you please share the code that is executing?

**Comment by AaronRobinsonMSFT** [comment] 2022-03-28 04:01
I believe the OP is using the code in the linked sample.

```csharp
class ArgumentOutOfRangeExample
{
    public static void Main()
    {
        int[] array1 = {0, 0};
        int[] array2 = {0, 0};

        try
        {
            Array.Copy(array1, array2, -1);
        }
        catch (ArgumentOutOfRangeException e)
        {
            Console.WriteLine("Error: {0}", e);
            throw;
        }
        finally
        {
            Console.WriteLine("This statement is always executed.");
        }
    }
}
```

**Comment by AaronRobinsonMSFT** [comment] 2022-03-28 04:08
@cdlliuy Are you relying on the output in the `finally` as the only indication it was executed? Note that the code snippet I placed above and in the linked documentation is expected to crash, but it will execute the `Console.WriteLine()`. Whether that is always observable is something I am not sure of. I could see an issue with the runtime not flushing the output buffer during an unhandled exception.

Confirmation on how you are determining the `finally` is not run would be helpful.

**Comment by AaronRobinsonMSFT** [comment] 2022-03-28 04:26
This could also be a duplicate of https://github.com/dotnet/runtime/issues/8145.

**Comment by Joe4evr** [comment] 2022-03-28 14:58
Was also recently reported at #65657.

**Comment by 333fred** [comment] 2022-03-29 00:56
> This could also be a duplicate of #8145.

I believe so. Note that our [docs](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/try-finally) on try-finally indicate that this is expected behavior:

> Within a handled exception, the associated finally block is guaranteed to be run. However, if the exception is unhandled, execution of the finally block is dependent on how the exception unwind operation is triggered. That, in turn, is dependent on how your computer is set up. The only cases where finally clauses don't run involve a program being immediately stopped. An example of this would be when [InvalidProgramException](https://docs.microsoft.com/en-us/dotnet/api/system.invalidprogramexception) gets thrown because of the IL statements being corrupt. On most operating systems, reasonable resource cleanup will take place as part of stopping and unloading the process.



> Was also recently reported at #65657.

I would agree with Jan that that one is also a duplicate of 8145.

**Comment by Joe4evr** [comment] 2022-03-29 01:27
> I believe so. Note that our [docs](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/try-finally) on try-finally indicate that this is expected behavior:

So does that mean the language spec needs updating to no longer state [it guarantees execution of `finally` blocks](https://github.com/dotnet/csharpstandard/blob/draft-v6/standard/statements.md#1211-the-try-statement)?
> The statements of a `finally` block are always executed when control leaves a `try` statement. This is true whether the control transfer occurs as a result of normal execution, as a result of executing a `break`, `continue`, `goto`, or `return` statement, or as a result of propagating an exception out of the `try` statement.

**Comment by 333fred** [comment] 2022-03-29 01:46
I'll leave that decision to @MadsTorgersen or @BillWagner, but I suspect the answer is no: the runtime does not have all the behaviors the C# specification expects, in this and several other aspects (consider that `int[]` and `uint[]` are the same type at runtime, for example).

**Comment by cdlliuy** [comment] 2022-03-29 09:31
Yes, I am just running with the sample code provided by the docs. 

This is very helpful!  After adding a Thread.Sleep(20*1000) in original code example,   I got the console.writeline() output !

So, it is a timing issue on Linux (I previous thought console.writeline() is sync method(), and can be always trusted) , and finally block are still called as the doc said.  

> @cdlliuy Are you relying on the output in the `finally` as the only indication it was executed? Note that the code snippet I placed above and in the linked documentation is expected to crash, but it will execute the `Console.WriteLine()`. Whether that is always observable is something I am not sure of. I could see **an issue with the runtime not flushing the output buffer during an unhandled exception.**

If  anyone else fell into the same situation with that simple example,  maybe it is better to improve the doc's code example with a Thread.sleep() as well.

**Closed** 2022-06-21 22:56 UTC
Labels: area-ExceptionHandling-coreclr, untriaged, needs-further-triage
