### ISSUE TITLE
when native AOT support to compile to 32 bit application

### ISSUE THREAD

**Issue by NCLnclNCL** [dotnet/runtime#86570] opened 2023-05-22 07:37 UTC
32bit compiled apps run using less ram and cpu, it seems to be fast too, and I think should have LARGEADDRESSAWARE enabled by default to be able to use 4gb ram on 64 bit devices

**Comment by MichalStrehovsky** [comment] 2023-05-22 08:35
Duplicate of #86573.

**Closed by MichalStrehovsky** 2023-05-22 08:35 UTC
Labels: untriaged, needs-area-label
