### ISSUE TITLE
MathF.CopySign is buggy when an input is NaN

### ISSUE THREAD

**Issue by FrantzUml** [dotnet/runtime#1239] opened 2020-01-01 18:33 UTC
The CopySign(float x, float y) in System.MathF has a bug when x or y is NaN.
With IEEE, NaN may have sign 1 or 0, mantissa anything, but biased exponent is 2^32 -1
So, in CopySign when you convert in 'int' the float.NaN you get a negative number.

CopySign(float.NaN, 3.2F) gives with sign = 1 (negative in IEEE) but the sign should be 0
CopySign(float.NaN, -3.2F) gives with sign = 0 (positive in IEEE) but the sign should be 1 (as -3.2F is negative). 

I did not verify in Math class (if you used same algorithm, it's same error).

**Comment by tannergooding** [comment] 2020-01-01 21:22
I'm not able to reproduce the issue. Take the following simple program:
```cs
            var nan1 = float.NaN;
            var nan2 = MathF.CopySign(float.NaN,  3.2f);
            var nan3 = MathF.CopySign(float.NaN, -3.2f);

            var bits1 = BitConverter.SingleToInt32Bits(nan1);
            var bits2 = BitConverter.SingleToInt32Bits(nan2);
            var bits3 = BitConverter.SingleToInt32Bits(nan3);

            Console.WriteLine($"{nan1:G17}    {bits1:x8}");
            Console.WriteLine($"{nan2:G17}    {bits2:x8}");
            Console.WriteLine($"{nan3:G17}    {bits3:x8}");
```

The output is:
```
NaN    ffc00000
NaN    7fc00000
NaN    ffc00000
```

**Comment by tannergooding** [comment] 2020-01-01 21:27
The `CopySign` implementation is also rather trivial:
```cs
        public static unsafe float CopySign(float x, float y)
        {
            // This method is required to work for all inputs,
            // including NaN, so we operate on the raw bits.
 
            int xbits = BitConverter.SingleToInt32Bits(x);
            int ybits = BitConverter.SingleToInt32Bits(y);
 
            // If the sign bits of x and y are not the same,
            // flip the sign bit of x and return the new value;
            // otherwise, just return x
 
            if ((xbits ^ ybits) < 0)
            {
                return BitConverter.Int32BitsToSingle(xbits ^ int.MinValue);
            }
 
            return x;
        }
```

We get the raw signed bits of each float. We then xor the bits together and check if its negative. This is functionally correct because all negative signed integers have the most significant bit set and all positive signed integers have the most significant bit cleared. Since the truth table for `xor` is:

| 0 | 0 | 0 |
| 0 | 1 | 1 |
| 1 | 0 | 1 |
| 1 | 1 | 0 |

We know that it will only be negative if the signs differed. If the signs don't differ, we can return the result as given. Otherwise, we need to flip the sign which is done by xor'ing with `int.MinValue` (`0x8000_0000`) which (given the above truth table) will preserve all bits but the most significant and flip the bit otherwise (now making it match the sign of `y`).

**Comment by FrantzUml** [comment] 2020-01-01 22:27
> Hello,
but in your example, nan2 should be positive but is negative, and nan3 should be negative but is positive.
If you use the true function to get the IEEE bit sign of a 'float' as:
private const int FLT_SGN_MASK = -1 - 0x7F_FF_FF_FF;
internal static int IEEESignBit(float number)
{
	if (float.IsNaN(number))
	{
		return ((System.BitConverter.SingleToInt32Bits(number) & FLT_SGN_MASK) != 0) ? 0 : 1;
	}
	else
	{
		return ((System.BitConverter.SingleToInt32Bits(number) & FLT_SGN_MASK) != 0) ? 1 : 0;
	}
}
then you can verify that the sign bit of float.NaN is 0

So, if you calculate CopySign(-3F, float.NaN) you should have +3F but you get -3F


> I'm not able to reproduce the issue. Take the following simple program:
> 
> ```cs
>             var nan1 = float.NaN;
>             var nan2 = MathF.CopySign(float.NaN,  3.2f);
>             var nan3 = MathF.CopySign(float.NaN, -3.2f);
> 
>             var bits1 = BitConverter.SingleToInt32Bits(nan1);
>             var bits2 = BitConverter.SingleToInt32Bits(nan2);
>             var bits3 = BitConverter.SingleToInt32Bits(nan3);
> 
>             Console.WriteLine($"{nan1:G17}    {bits1:x8}");
>             Console.WriteLine($"{nan2:G17}    {bits2:x8}");
>             Console.WriteLine($"{nan3:G17}    {bits3:x8}");
> ```
> 
> The output is:
> 
> ```
> NaN    ffc00000
> NaN    7fc00000
> NaN    ffc00000
> ```

**Comment by tannergooding** [comment] 2020-01-01 23:31
> but in your example, nan2 should be positive but is negative, and nan3 should be negative but is positive.

`nan2=0x7FC0_0000` and `nan3=0xFFC0_0000`, this means `nan2` is positive and `nan3` is negative; as expected all values above `0x8000_0000` are negative, all values below it are positive.

> internal static int IEEESignBit(float number)

This function is not correct. All floating-point values (including Infinity, NaN, and Zero) represent the sign in the same way, by the most significant bit. If the most significant bit is set, it is negative; otherwise it is positive.

Getting the sign of an IEEE floating-point value is as simple as `(BitConverter.SingleToInt32Bits(value) >> 31) & 1` and `(BitConverter.DoubleToInt64Bits(value) >> 63) & 1`.

> So, if you calculate CopySign(-3F, float.NaN) you should have +3F but you get -3F

This is because `float.NaN` is negative by default. This is for back-compat reasons as x86 CPUs have traditionally returned a negative `NaN` and so we do the same.

**Comment by tannergooding** [comment] 2020-03-05 19:39
Closing as I believe this has been resolved. Please reopen if you feel that was not the case.

**Closed by tannergooding** 2020-03-05 19:39 UTC
Labels: area-System.Numerics
