### ISSUE TITLE
Fatal error HRESULT=0x80070057 when loading/unloading multiple times assemblies.

### ISSUE THREAD

**Issue by cedricmelancon** [dotnet/runtime#535] opened 2019-11-27 12:10 UTC
# General

I ran in a crash with HRESULT=0x80050057 when creating a plugin manager. The plugin manager is scanning a folder for plugins, loads all of them, get the metadata and unload. After some plugins, the application crashes.

I managed to reproduce the problem with the sample provided on github at the following location:
https://github.com/dotnet/samples/tree/master/core/tutorials/Unloading

To reproduce the behavior, I modified the Main.cs in Host Project as follow:

```c#
static void Main(string[] args)
{
   WeakReference hostAlcWeakRef;
   string currentAssemblyDirectory = 
   Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
#if DEBUG
   string configName = "Debug";
#else
   string configName = "Release";
#endif
   
   string pluginFullPath = Path.Combine(currentAssemblyDirectory, $"..\\..\\..\\..\\Plugin\\bin\\{configName}\\netcoreapp3.0\\Plugin.dll");

   for (var iteration = 0; iteration < 10; ++iteration)
   {
      ExecuteAndUnload(pluginFullPath, out hostAlcWeakRef);

      // Poll and run GC until the AssemblyLoadContext is unloaded. 
      // You don't need to do that unless you want to know when the context
      // got unloaded. You can just leave it to the regular GC.
      for (int i = 0; hostAlcWeakRef.IsAlive && (i < 10); i++)
      {
         GC.Collect();
         GC.WaitForPendingFinalizers();
      }

      Console.WriteLine($"Unload success: {!hostAlcWeakRef.IsAlive}");

      Thread.Sleep(1500);
   }
}
```

**Comment by jkotas** [comment] 2019-12-05 04:42
cc @janvorli

**Comment by janvorli** [comment] 2019-12-09 11:28
@cedricmelancon can you please share more details on what configuration / OS / .NET Core version and steps to execute you have reproed the problem with? I've tried to repro it with .NET Core 3.0.0 (SDK 3.0.100) in both Release and Debug version on Windows and I was unable to repro the problem.

**Comment by cedricmelancon** [comment] 2019-12-09 13:55
@janvorli  I ran the program with .Net Core 3.0.0 (SDK 3.0.100) on a Windows 10 Pro as well as in a Linux container in Debug and Release as well. Can I get you more information?

**Comment by janvorli** [comment] 2019-12-09 15:13
I have ran it from the command line using `dotnet run` command before and the issue didn't repro. However, I have just tried to run it under VS2019 and the issue has reproduced. 
When you have ran it in the Linux container, have you ran it from the command line or also under Visual Studio?

**Comment by cedricmelancon** [comment] 2019-12-09 21:25
In fact, I just realized that I never deployed my code in a container because it was failing while running in Visual Studio. Do you have an idea of what could be the problem with VS or how to bypass the issue besides running with the command line?

**Comment by janvorli** [comment] 2019-12-09 21:34
It sounds to me like a bug in VS in handling unloadable AssemblyLoadContexts. @tommcdon are we aware of any VS2019 issues w.r.t. unloadable AssemblyLoadContext that would cause the debugging session to be terminated with the following message?
![image](https://user-images.githubusercontent.com/10758568/70474959-d740ef00-1ad3-11ea-97d0-7a81aba0a1e8.png)
It happens when we create an unloadable assembly load context, load something into it, unload it and repeat that multiple times (loading the same assembly into the context in each attempt).

**Comment by cedricmelancon** [comment] 2019-12-13 15:07
The issue happens also if we try to load another assembly. It's not only related to loading the same assembly over and over.

**Comment by janvorli** [comment] 2019-12-18 10:29
@cedricmelancon can you please report this to the Visual Studio team using the "Send feedback" button / "Report a problem" submenu in the Visual Studio itself (in the upper right corner of the visual studio window)?

**Comment by cedricmelancon** [comment] 2019-12-18 15:50
@janvorli Sure I will do that. Thank you.

**Comment by baehny** [comment] 2019-12-19 09:18
Here are two visual studio issues describing the same problem:

https://developercommunity.visualstudio.com/content/problem/785136/c-debugger-crashes-after-unloading-assemblyloadcon.html

https://developercommunity.visualstudio.com/content/problem/698374/vs2019-and-fatal-error-has-occurred-and-debugging.html

**Comment by jeffschwMSFT** [comment] 2020-01-08 22:01
Closing in favor of the developercommunity issues

**Closed by jeffschwMSFT** 2020-01-08 22:01 UTC
Labels: area-TypeSystem, untriaged

**Comment by waldnercharles** [comment] 2020-01-27 15:06
I believe this issue should be re-opened. The issue doesn't appear to be editor specific. The debugger crashes in Visual Studio, VS Code, and JetBrains Rider.

**Comment by jeffschwMSFT** [comment] 2020-01-27 16:27
Thanks @waldnercharles for the feedback.  The developercommunity issue can be used to help with all these products.  Can you jump on that issue and provide additional details?

**Comment by waldnercharles** [comment] 2020-01-29 16:38
The issue on developercommunity was closed and re-reported here:

https://github.com/dotnet/runtime/issues/2317

**Comment by jeffschwMSFT** [comment] 2020-01-29 17:09
@hoyosjs can you help sort out if this issue should be tracked on developer community or github?  Thanks

**Comment by hoyosjs** [comment] 2020-01-29 17:15
I looked at it a tiny bit yesterday. So far I'd keep it here until I can investigate a little more.

**Comment by isc30** [comment] 2020-04-05 15:23
Same issue here, using VS2019 16.4.2 enterprise and .net core 3.1.200 AssemblyLoadContext.

Loading something works, unloading, then repeating the process.

At some point it crashes with the following error (also reproduced by @janvorli):
![imagen](https://user-images.githubusercontent.com/10807051/78502554-fc7ffa00-7761-11ea-9d3a-03faf192289f.png)

**Comment by baehny** [comment] 2020-04-05 15:32
The issue is fixed for .net 5 preview:
https://github.com/dotnet/runtime/issues/2317

and was back ported to 3.1.4:
https://github.com/dotnet/coreclr/pull/28023

So as far as I know the issue will be fixed for .net core with an upcoming release.
