### ISSUE TITLE
ConcurrentDictionary Count is slow

### ISSUE THREAD

**Issue by fredwangwang** [dotnet/runtime#100853] opened 2024-04-10 05:45 UTC
### Description

During one of the performance testing, found out that calling to `ConcurrentDictionary.Count` is contributing significant time to a hot path.

### Configuration

win x64 .net8.0

### Regression?

Dont think this is a regression.

### Analysis

Looking into the implementation for Count, found out that each time Count is called, it is locking the entire dictionary and iterate through all buckets to get a sum.

It seems that the performance would be much better to keep an atomic counter so that get Count is instant.

https://source.dot.net/#System.Collections.Concurrent/System/Collections/Concurrent/ConcurrentDictionary.cs,1116

![image](https://github.com/dotnet/runtime/assets/21690857/1e074c61-f535-4d21-b12f-de9d6f2e6c0c)

![image](https://github.com/dotnet/runtime/assets/21690857/d9a4fe72-64ea-4807-9508-1bcfc219ea87)

**Comment by EgorBo** [comment] 2024-04-10 10:26
See https://github.com/dotnet/runtime/issues/15249#issuecomment-142131725

**Comment by eiriktsarpalis** [comment] 2024-04-10 11:33
Duplicate of #15249

**Closed by eiriktsarpalis** 2024-04-10 11:33 UTC
Labels: area-System.Collections, tenet-performance, untriaged
