### ISSUE TITLE
AssemblyBuilder.GetDynamicModule does not return previously created dynamic modules

### ISSUE THREAD

**Issue by ibisystemsdev** [dotnet/runtime#57130] opened 2021-08-10 13:48 UTC
### Description

The last variable in the following snippet will always be null instead of returning the ModuleBuilder:

```
var assembly = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName("Workbench.Dynamic"), AssemblyBuilderAccess.Run);
var moduleName = "Workbench.Dynamic.Module";
var module = assembly.DefineDynamicModule(moduleName);
var missing = assembly.GetDynamicModule(moduleName);
```

### Configuration

.NET 5.0 Console Application 

### Regression?

Module is returned as expected when targeting .NET 4.8

### Other information

FullyQualifiedName and ScopeName of the module also differ between the versions:

Under .NET 4.8
![NET48](https://user-images.githubusercontent.com/88723371/128878161-5d606e0b-2124-4778-88e1-e7325dbb340f.png)

Under .NET 5.0
![NET50](https://user-images.githubusercontent.com/88723371/128878175-25ae6700-5952-461d-b883-4e32953188e3.png)

**Comment by adamsitnik** [comment] 2021-08-10 14:23
@buyaa-n @joperezr @krwq @steveharter

**Comment by krwq** [comment] 2021-08-10 17:07
@ibisystemsdev seems like those are two separate issues and it's been like that since at least .NET Core 3.1. Do you have any particular scenarios which are blocked by this?

**Comment by Marusyk** [comment] 2021-08-10 19:31
In CoreCLR there is only one module in each dynamic assembly, the manifest module. What behavior is expected here?

**Comment by ibisystemsdev** [comment] 2021-08-11 07:29
@krwq The current behavior requires me to pass around the ModuleBuilder from .DefineDynamicModule. It would be more convenient if I could get the module from the AssemblyBuilder like in .NET 4.8. Also its quite misleading if the dynamic module can never be retrieved using GetDynamicModule.

@Marusyk I expect to define a dynamic module and be able to get it from the AssemblyBuilder after creation. I think the manifest module is not supposed to be used for defining new types or is it?

**Comment by svick** [comment] 2021-08-11 09:34
@ibisystemsdev 

> Also its quite misleading if the dynamic module can never be retrieved using GetDynamicModule.

This is almost certainly a bad idea, but AFAICT you *can* do it using `assembly.GetDynamicModule("RefEmit_InMemoryManifestModule")`.

**Comment by madelson** [comment] 2022-04-27 00:36
Currently, `DefineDynamicModule` ignores the passed-in name, but `GetDynamicModule` respects it, leading to this issue. Is the intent that `GetDynamicModule` should also ignore the name?

Based on how the builder works today, would it make more sense to obsolete the existing define and get methods and replace them with a read only property `ManifestModule`?

**Comment by buyaa-n** [comment] 2022-05-03 01:03
>  I expect to define a dynamic module and be able to get it from the AssemblyBuilder after creation. I think the manifest module is not supposed to be used for defining new types or is it?

As @Marusyk mentioned above .Net core only support one module in each dynamic assembly, the manifest module. And it is the module supposed to be used for defining new types. This is by design not a bug.

Probably we should obsolete the old methods as @madelson mentioned, I see an [issue](https://github.com/dotnet/runtime/issues/67053) created for that, so closing this issue

**Closed by buyaa-n** 2022-05-03 01:03 UTC
Labels: bug, area-System.Reflection.Emit, up-for-grabs
