### ISSUE TITLE
C# HttpListener will show ObjectDisposedException if you stop listen after start listen immediately

### ISSUE THREAD

**Issue by 1234567Yang** [dotnet/runtime#96705] opened 2024-01-09 19:28 UTC
### Description

The question [here on Stackoverflow](https://stackoverflow.com/questions/77762827/c-sharp-httplistener-will-show-objectdisposedexception-if-you-stop-listen-after).

### Reproduction Steps

Use the code:

```
HttpListener httpListener = new HttpListener();
httpListener.Start();
httpListener.Stop();
```

### Expected behavior

The `HttpListener` should be started and stopped immediately without showing error.

### Actual behavior

It will throw an `ObjectDisposedException`.

### Configuration

.NET Framework 4.8
Windows 11

**Comment by wfurt** [comment] 2024-01-09 19:45
This is not repo for .NET Framework @1234567Yang. and `HttpListener` is discouraged for new development. It is unlikely IMHO this will ever be fixed.

**Comment by antonfirsov** [comment] 2024-01-09 19:51
Also, I can't reproduce the issue. I don't see how is this possible given that `Start()` is setting `m_State = State.Started` (unless it throws):

https://referencesource.microsoft.com/#System/net/System/Net/HttpListener.cs,871

Something odd must be happening in your app. Have you tried to repro this in a minimal console application?

**Comment by 1234567Yang** [comment] 2024-01-17 01:12
Sorry, I forgot to post the comment.
I tested the case and I found that this bug will occur when you create a .net library and use it in console app, but it works fine if you use it in Windows app.
![image](https://github.com/dotnet/runtime/assets/113082249/ca9f1481-0f60-490d-9f75-86d141dd53f3)


I also uploaded [the file](https://github.com/dotnet/runtime/files/13957247/Test.zip) to reappear the problem.

**Comment by MihaZupan** [comment] 2024-02-16 15:52
![image](https://github.com/dotnet/runtime/assets/25307628/7a24db32-82c7-430e-a657-cc6d571ee57c)

The exception you're seeing is thrown and caught internally here
https://github.com/dotnet/runtime/blob/de12fe75a599220f7390ba5af8f9a2d4e6de5ec0/src/libraries/System.Net.HttpListener/src/System/Net/Windows/HttpListenerSession.Windows.cs#L74-L81

It does not appear to be affecting the call to `Stop` itself (`Stop` isn't throwing), you're just seeing that an exception happened somewhere in debug logs.

**Comment by antonfirsov** [comment] 2024-02-21 13:03
Triage: given the exception is caught internally, this is not this as a bug, closing.

@1234567Yang if you experience practical issue from this other than seeing an exception being logged in the VS Debugger, let us know!

**Closed by antonfirsov** 2024-02-21 13:03 UTC
Labels: area-System.Net, untriaged, needs-author-action
