### ISSUE TITLE
Open Generics mixed with Closed Generics in dependency injection

### ISSUE THREAD

**Issue by francescodente** [dotnet/runtime#64995] opened 2022-02-08 17:28 UTC
### Description

This bug occurs when registering both an open generic implementation for an open generic interface and a closed generic implementation for a closed version of the same interface.

Depending on the order of registration to the `IServiceCollection`, using `GetServices<T>()` on the corresponding `IServiceProvider` results in different collections being returned.

### Reproduction Steps

```csharp
public interface ITestService<T> { }

public class Open<T> : ITestService<T> { }

public class ClosedForInt : ITestService<int> { }

var serviceProviderA = new ServiceCollection()
    .AddTransient(typeof(ITestService<>), typeof(Open<>))
    .AddTransient(typeof(ITestService<int>), typeof(ClosedForInt))
    .Build();

var serviceProviderB = new ServiceCollection()
    .AddTransient(typeof(ITestService<int>), typeof(ClosedForInt))
    .AddTransient(typeof(ITestService<>), typeof(Open<>))
    .Build();

var works = serviceProviderA.GetServices<ITestService<int>>(); // Contains an Open<int> and a ClosedForInt
var doesNotWork = serviceProviderB.GetServices<ITestService<int>>(); // Contains two ClosedForInt instances.

```

### Expected behavior

`GetServices<ITestService<int>>()` should return the same instances regardless of the order of registration in the DI container.

### Actual behavior

Registering the open generic implementation after closed implementations yields the incorrect services when calling `GetService<ITestService<int>>()`.

### Known Workarounds

Registering open generic implementations first seems to make everything work, but I haven't tried other combinations and orders of registration.

**Comment by eerhardt** [comment] 2022-02-08 22:57
@francescodente - what version of `Microsoft.Extensions.DependencyInjection` are you using?

**Comment by francescodente** [comment] 2022-02-09 12:49
> @francescodente - what version of `Microsoft.Extensions.DependencyInjection` are you using?

I tested version 6.0.0

**Comment by bcallaghan-et** [comment] 2022-07-18 19:14
I can replicate the OP's results if I add `ValidateOnBuild = true` (the default in Development builds) to the `BuildServiceProvider` call. If I instead set `ValidateOnBuild = false` (the default in Production builds), I get the OP's expected non-bugged results.

```c#
var openFirstNoValidate = new ServiceCollection()
    .AddTransient(typeof(ITestService<>), typeof(Open<>))
    .AddTransient(typeof(ITestService<int>), typeof(ClosedForInt))
    .BuildServiceProvider(new ServiceProviderOptions { ValidateOnBuild = false });

var closedFirstNoValidate = new ServiceCollection()
    .AddTransient(typeof(ITestService<int>), typeof(ClosedForInt))
    .AddTransient(typeof(ITestService<>), typeof(Open<>))
    .BuildServiceProvider(new ServiceProviderOptions { ValidateOnBuild = false });

var openFirstWithValidate = new ServiceCollection()
    .AddTransient(typeof(ITestService<>), typeof(Open<>))
    .AddTransient(typeof(ITestService<int>), typeof(ClosedForInt))
    .BuildServiceProvider(new ServiceProviderOptions { ValidateOnBuild = true });

var closedFirstWithValidate = new ServiceCollection()
    .AddTransient(typeof(ITestService<int>), typeof(ClosedForInt))
    .AddTransient(typeof(ITestService<>), typeof(Open<>))
    .BuildServiceProvider(new ServiceProviderOptions { ValidateOnBuild = true });

var works = openFirstNoValidate.GetServices<ITestService<int>>();
var alsoWorks = closedFirstNoValidate.GetServices<ITestService<int>>();
var stillWorks = openFirstWithValidate.GetServices<ITestService<int>>();
var doesntWork = closedFirstWithValidate.GetServices<ITestService<int>>();
```

**Comment by eerhardt** [comment] 2022-07-18 19:26
That sounds like a duplicate of https://github.com/dotnet/runtime/issues/65145. @francescodente - can you confirm?

**Comment by francescodente** [comment] 2022-07-19 10:50
> That sounds like a duplicate of #65145. @francescodente - can you confirm?

Yes, it definitely is.

**Closed** 2022-07-19 13:20 UTC
Labels: area-Extensions-DependencyInjection
