### ISSUE TITLE
Test failure: Microsoft.Extensions.Hosting.Tests.HostTests.CreateDefaultBuilder_ConfigJsonDoesReload

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#43576] opened 2020-10-19 08:08 UTC
failed in job: [runtime-coreclr libraries-jitstress 20201018.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=857718&view=ms.vss-test-web.build-test-results-tab&runId=27451628&resultId=104094&paneView=debug)

net6.0-Windows_NT-Release-x86-CoreCLR_checked-no_tiered_compilation-Windows.10.Amd64.Open

Error message
~~~
Assert.Equal() Failure
Expected: Hello ASP.NET Core: 6ba9540fc4c844f8a37895fef503bc7e
Actual:   (null)


Stack trace
   at Microsoft.Extensions.Hosting.Tests.HostTests.CreateDefaultBuilder_ConfigJsonDoesReload() in /_/src/libraries/Microsoft.Extensions.Hosting/tests/UnitTests/HostTests.cs:line 203
~~~

**Comment by eerhardt** [comment] 2020-10-19 21:52
See comment here: https://github.com/dotnet/runtime/issues/43389#issuecomment-712462829

**Comment by maryamariyan** [comment] 2020-10-21 12:43
Closing as dupe of https://github.com/dotnet/runtime/issues/43389

**Closed by maryamariyan** 2020-10-21 12:43 UTC
Labels: area-Extensions-Hosting, untriaged
