### ISSUE TITLE
Test failure Attempt #1 - System.Net.Quic.Tests.QuicConnectionTests.TestConnect(address: ::1)

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#95776] opened 2023-12-08 01:33 UTC
Run: [runtime-coreclr libraries-pgo 20231207.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=491980&view=ms.vss-test-web.build-test-results-tab&runId=11397638&resultId=192129&paneView=debug)

Failed test:
```
net9.0-linux-Release-arm-CoreCLR_checked-fullpgo_random_gdv-(Ubuntu.1804.Arm32.Open)Ubuntu.2004.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7

- Attempt #1 - System.Net.Quic.Tests.QuicConnectionTests.TestConnect(address: ::1)
- Attempt #1 - System.Net.Quic.Tests.QuicConnectionTests.TestConnect(address: 127.0.0.1)
- System.Net.Quic.Tests.QuicConnectionTests.TestConnect(address: fe80::42:acff:fe11:2%151)
```
**Error message:**
```
System.AggregateException : One or more errors occurred. (The connection timed out from inactivity.) (The connection timed out from inactivity.)
---- System.Net.Quic.QuicException : The connection timed out from inactivity.
---- System.Net.Quic.QuicException : The connection timed out from inactivity.



Stack trace
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 88
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 55
   at System.Net.Quic.Tests.QuicConnectionTests.TestConnect(IPAddress address) in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicConnectionTests.cs:line 36
   at System.Net.Quic.Tests.QuicConnectionTests.TestConnect(IPAddress address) in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicConnectionTests.cs:line 50
--- End of stack trace from previous location ---
----- Inner Stack Trace #1 (System.Net.Quic.QuicException) -----
   at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 507
   at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 570
   at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 604
--- End of stack trace from previous location ---
   at System.Net.Quic.QuicConnection.FinishConnectAsync(QuicClientConnectionOptions options, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 346
   at System.Net.Quic.QuicConnection.<ConnectAsync>g__StartConnectAsync|2_0(QuicClientConnectionOptions options, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 79
   at System.Net.Quic.QuicConnection.<ConnectAsync>g__StartConnectAsync|2_0(QuicClientConnectionOptions options, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 94
   at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 120
----- Inner Stack Trace #2 (System.Net.Quic.QuicException) -----
   at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 507
   at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 570
   at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs:line 604
--- End of stack trace from previous location ---
   at System.Net.Quic.ValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ValueTaskSource.cs:line 176
   at System.Net.Quic.QuicListener.StartConnectionHandshake(QuicConnection connection, SslClientHelloInfo clientHello) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicListener.cs:line 236
   at System.Net.Quic.QuicListener.AcceptConnectionAsync(CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicListener.cs:line 186
   at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 120
```

**Comment by ManickaP** [comment] 2024-01-02 04:11
Same problem as https://github.com/dotnet/runtime/issues/86565, closing as dupe. I'll disable the tests.

**Comment by ManickaP** [comment] 2024-01-02 04:12
Duplicate of #86565

**Closed by ManickaP** 2024-01-02 04:12 UTC
Labels: os-linux, untriaged, blocking-clean-ci-optional, area-System.Net.Quic
