### ISSUE TITLE
Test failure: Sockets.Tests.TelemetryTest.EventSource_SocketConnectsRemote_LogsConnectStartStop

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#44221] opened 2020-11-03 20:56 UTC
Different variants of `System.Net.Sockets.Tests.TelemetryTest.EventSource_SocketConnectsRemote_LogsConnectStartStop`  started to fail since 2020-10-28, on Unixes.

https://dev.azure.com/dnceng/public/_build/results?buildId=874418&view=ms.vss-test-web.build-test-results-tab
(net6.0-Linux-Debug-x64-CoreCLR_release-(Alpine.312.Amd64.Open)ubuntu.1604.amd64.open)

#### Error Message
```
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
```

#### Stack Trace

<details>

```

Child exception:
  System.TimeoutException: Timed out waiting for ConnectStop
   at System.Net.Sockets.Tests.TelemetryTest.WaitForEventAsync(ConcurrentQueue`1 events, String name) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 412
   at System.Net.Sockets.Tests.TelemetryTest.<>c__DisplayClass9_0.<<EventSource_SocketConnectsRemote_LogsConnectStartStop>b__2>d.MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 151
--- End of stack trace from previous location ---
   at System.Diagnostics.Tracing.TestEventListener.RunWithCallbackAsync(Action`1 handler, Func`1 body) in /_/src/libraries/Common/tests/System/Diagnostics/Tracing/TestEventListener.cs:line 109
   at System.Net.Sockets.Tests.TelemetryTest.<>c.<<EventSource_SocketConnectsRemote_LogsConnectStartStop>b__9_0>d.MoveNext() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/TelemetryTest.cs:line 142
--- End of stack trace from previous location ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Program.cs:line 65

Child process:
  System.Net.Sockets.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.Sockets.Tests.TelemetryTest+<>c System.Threading.Tasks.Task <EventSource_SocketConnectsRemote_LogsConnectStartStop>b__9_0(System.String, System.String)

Child arguments:
  Eap, True

```

</details>

**Comment by MihaZupan** [comment] 2020-12-14 08:28
Duplicate of #44015

**Closed by MihaZupan** 2020-12-14 08:28 UTC
Labels: area-System.Net.Sockets, bug
