### ISSUE TITLE
Test failure JIT/IL_Conformance/Old/Conformance_Base/ldc_mul_ovf_i4/ldc_mul_ovf_i4.dll

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#93448] opened 2023-10-13 07:57 UTC
**Failed in:** [runtime-coreclr outerloop 20231012.12](https://dev.azure.com/dnceng-public/public/_build/results?buildId=437267&view=ms.vss-test-web.build-test-results-tab&runId=9720950&resultId=114470&paneView=debug)

**Failed tests:**
```
coreclr windows arm64 Checked no_tiered_compilation @ Windows.11.Arm64.Open
    - JIT/Directed/ConstantFolding/value_numbering_checked_arithmetic_with_constants_ro/value_numbering_checked_arithmetic_with_constants_ro.dll
    - JIT/IL_Conformance/Old/Conformance_Base/ldc_mul_ovf_i4/ldc_mul_ovf_i4.dll
    - JIT/jit64/rtchecks/overflow/overflow02_mul/overflow02_mul.dll
    - JIT/Regression/CLR-x86-JIT/V1-M09.5-PDC/b25815/b25815/b25815.dll
    - JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b71869/b71869/b71869.dll
R2R-CG2 windows arm64 Checked @ Windows.11.Arm64.Open
    - JIT/Directed/ConstantFolding/value_numbering_checked_arithmetic_with_constants_ro/value_numbering_checked_arithmetic_with_constants_ro.dll
    - JIT/IL_Conformance/Old/Conformance_Base/ldc_mul_ovf_i4/ldc_mul_ovf_i4.dll
    - JIT/jit64/rtchecks/overflow/overflow02_mul/overflow02_mul.dll
    - JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b71869/b71869/b71869.dll
    - JIT/Regression/CLR-x86-JIT/V1-M09.5-PDC/b25815/b25815/b25815.dll
R2R-CG2 windows arm64 Checked no_tiered_compilation @ Windows.11.Arm64.Open
    - JIT/Directed/ConstantFolding/value_numbering_checked_arithmetic_with_constants_ro/value_numbering_checked_arithmetic_with_constants_ro.dll
    - JIT/jit64/rtchecks/overflow/overflow02_mul/overflow02_mul.dll
    - JIT/IL_Conformance/Old/Conformance_Base/ldc_mul_ovf_i4/ldc_mul_ovf_i4.dll
    - JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b71869/b71869/b71869.dll
    - JIT/Regression/CLR-x86-JIT/V1-M09.5-PDC/b25815/b25815/b25815.dll
```

**Error message:**
```
Assert.Equal() Failure
Expected: 100
Actual:   101
```

**Stack trace:**
```
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/xunit.assert/Asserts/EqualityAsserts.cs:line 96
   at Program.<<Main>$>g__TestExecutor235|0_236(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by jakobbotsch** [comment] 2023-10-13 08:23
Duplicate of #93441

**Closed by jakobbotsch** 2023-10-13 08:23 UTC
Labels: arch-arm64, os-windows, area-CodeGen-coreclr, untriaged, blocking-outerloop
