### ISSUE TITLE
Can't execute dotnet-arm64 on asuswrt

### ISSUE THREAD

**Issue by pengweiqhca** [dotnet/runtime#42497] opened 2020-09-19 23:45 UTC
``` bash
# ./dotnet
./dotnet: error while loading shared libraries: libpthread.so.0: cannot open shared object file: No such file or directory

# uname -a
Linux RT-AX86U 4.1.52 #2 SMP PREEMPT Sat Jul 25 23:55:08 CST 2020 aarch64 Merlin_Koolshare_RT-AX86U
```
But `/lib` and `/opt/lib` have the file `libpthread.so.0`

**Comment by am11** [comment] 2020-09-21 07:49
Try with `LD_DEBUG=libs dotnet --info` and it will show where it is trying to locate libpthread.

**Comment by pengweiqhca** [comment] 2020-09-21 11:55
> Try with `LD_DEBUG=libs dotnet --info` and it will show where it is trying to locate libpthread.

I fixed some error, now I got these error `/lib64/libc.so.6: version `GLIBC_2.27' not found (required by /opt/lib/libgssapi_krb5.so.2)` and `relocation error: /opt/lib/libc.so.6: symbol _dl_exception_create, version GLIBC_PRIVATE not defined in file ld-linux-aarch64.so.1 with link time reference`

**Comment by janvorli** [comment] 2020-09-21 12:01
Can you please run `ld --version` and copy here the output? It seems that your libc is too old. The minimum supported version is glibc 2.14.

**Comment by ericstj** [comment] 2020-09-21 16:30
Move to host as it appears to be a portable-build issue with native code and host is failing to start.  @janvorli let me know if there is a better area path.

**Comment by janvorli** [comment] 2020-09-21 16:44
@ericstj the area sounds correct.

**Comment by pengweiqhca** [comment] 2020-09-22 01:31
> ld --version

-sh: ld: not found

> Can you please run `ld --version` and copy here the output? It seems that your libc is too old. The minimum supported version is glibc 2.14.

-sh: ld: not found

**Comment by am11** [comment] 2020-09-22 10:43
> symbol _dl_exception_create, version GLIBC_PRIVATE not defined in file ld-linux-aarch64.so.1

It could be that there is a wrong symlink for ld-linux-aarch64.so.1 (or manually created in past), which `dotnet(1)` is picking. You can check if the symlink reported by `ls -l /lib64/ld* | grep lrw` exists and it is pointing to the file that has the correct version which your libc is expecting. Also, you can try after deleting (or temporarily renaming) that symlink.

**Comment by pengweiqhca** [comment] 2020-09-23 02:02
> > symbol _dl_exception_create, version GLIBC_PRIVATE not defined in file ld-linux-aarch64.so.1
> 
> It could be that there is a wrong symlink for ld-linux-aarch64.so.1 (or manually created in past), which `dotnet(1)` is picking. You can check if the symlink reported by `ls -l /lib64/ld* | grep lrw` exists and it is pointing to the file that has the correct version which your libc is expecting. Also, you can try after deleting (or temporarily renaming) that symlink.

find the only one
``` bash
# ls -l /opt/lib/ld* | grep lrw
lrwxrwxrwx    1 admin    root            10 Sep 22 09:29 /opt/lib/ld-linux-aarch64.so.1 -> ld-2.27.so
```

**Comment by janvorli** [comment] 2020-09-23 09:02
> `/lib64/libc.so.6: version `GLIBC_2.27' not found (required by /opt/lib/libgssapi_krb5.so.2)`and`relocation error: /opt/lib/libc.so.6: symbol _dl_exception_create, version GLIBC_PRIVATE not defined in file ld-linux-aarch64.so.1

I have just noticed that you mentioned two different libc.so.6 - `/lib64/libc.so.6` and `/opt/lib/libc.so.6`. t seems that `/opt/lib/libgssapi_krb5.so.2` most likely expects to load the `/opt/lib/libc.so.6`, but finds the `/lib64/libc.so.6` on the library load paths first. I think that the `/lib64/libc.so.6` is some version older than the 2.27 that the `/opt/lib/libgssapi_krb5.so.2` requires.

You can try to see which version it is e.g. this way:
```sh
objdump -T /lib64/libc.so.6 | grep -o -e 'GLIBC_[^ )]* ' | sort | uniq
```

This will list all unique versions of symbols (GLIBC_*) exposed by the libc.

**Comment by pengweiqhca** [comment] 2020-09-23 09:09
> This will list all unique versions of symbols (GLIBC_*) exposed by the libc.

``` bash
# objdump -T /lib64/libc.so.6 | grep -o -e 'GLIBC_[^ )]* ' | sort | uniq
GLIBC_2.17
GLIBC_2.18
GLIBC_2.22
GLIBC_2.23
GLIBC_2.24
GLIBC_2.25
GLIBC_2.26
GLIBC_PRIVATE

# objdump -T /opt/lib/libc.so.6 | grep -o -e 'GLIBC_[^ )]* ' | sort | uniq
GLIBC_2.17
GLIBC_2.18
GLIBC_2.22
GLIBC_2.23
GLIBC_2.24
GLIBC_2.25
GLIBC_2.26
GLIBC_2.27
GLIBC_PRIVATE
```

**Comment by janvorli** [comment] 2020-09-23 09:22
Thank you. So the /lib64/libc.so.6 seems to be of version 2.26 and that's why the `/opt/lib/libgssapi_krb5.so.2` cannot link to it. Can you please try the following?

```sh
LD_LIBRARY_PATH=/opt/lib:$LD_LIBRARY_PATH dotnet --info
```

This puts the /opt/lib to the front of the library search path, so dotnet should be forced to use the libc.so.6 from there instead of the one from /lib64.

**Comment by pengweiqhca** [comment] 2020-09-23 09:34
``` bash
# LD_LIBRARY_PATH=/opt/lib:$LD_LIBRARY_PATH ./dotnet --info
./dotnet: relocation error: /opt/lib/libc.so.6: symbol _dl_exception_create, version GLIBC_PRIVATE not defined in file ld-linux-aarch64.so.1 with link time reference
```

**Comment by am11** [comment] 2020-09-23 09:46
> find the only one

I meant if you try moving/deleting that symlink, does it make a difference? something line `mv /opt/lib/ld-linux-aarch64.so.1 /tmp ; dotnet --info`.

**Comment by pengweiqhca** [comment] 2020-09-24 01:11
> > find the only one
> 
> I meant if you try moving/deleting that symlink, does it make a difference? something line `mv /opt/lib/ld-linux-aarch64.so.1 /tmp ; dotnet --info`.

No difference

**Comment by am11** [comment] 2020-09-24 07:14
> symbol _dl_exception_create, version GLIBC_PRIVATE not defined in file ld-linux-aarch64.so.1
> ....
> find the only one
> ```
> # ls -l /opt/lib/ld* | grep lrw
> lrwxrwxrwx    1 admin    root            10 Sep 22 09:29 /opt/lib/ld-linux-aarch64.so.1 -> ld-2.27.so
> ```

interesting. after deleting `ld-linux-aarch64.so.1` symlink, i was expecting that at least your error message would be different than `symbol _dl_exception_create, version GLIBC_PRIVATE not defined in file ld-linux-aarch64.so.1`.

**Comment by janvorli** [comment] 2020-09-24 09:26
I have found that the symbol _dl_exception_create was added in glibc 2.27 and it was not present in 2.26. So it seems that the problem is actually that there is ld-linux-aarch64.so.1 from glibc 2.26 that is being loaded. My guess is that it resides in /lib64.

That would explain why @am11's suggestion didn't help.

Having two different glibc versions in the system is a recipe for problems in general, as things like this can happen. It seems that a fix would be to upgrade the glibc in /lib64 to 2.27 if that's possible.

**Comment by pengweiqhca** [comment] 2020-09-24 10:56
> I have found that the symbol _dl_exception_create was added in glibc 2.27 and it was not present in 2.26. So it seems that the problem is actually that there is ld-linux-aarch64.so.1 from glibc 2.26 that is being loaded. My guess is that it resides in /lib64.
> 
> That would explain why @am11's suggestion didn't help.
> 
> Having two different glibc versions in the system is a recipe for problems in general, as things like this can happen. It seems that a fix would be to upgrade the glibc in /lib64 to 2.27 if that's possible.

I have upgraded the /lib64/libc.so.6, but still not working.

``` bash
# objdump -T /lib64/libc.so.6 | grep -o -e 'GLIBC_[^ )]* ' | sort | uniq
GLIBC_2.17
GLIBC_2.18
GLIBC_2.22
GLIBC_2.23
GLIBC_2.24
GLIBC_2.25
GLIBC_2.26
GLIBC_2.27
GLIBC_PRIVATE

# LD_DEBUG=libs LD_LIBRARY_PATH=/opt/lib:$LD_LIBRARY_PATH ./dotnet --info
     26438:     find library=libpthread.so.0 [0]; searching
     26438:      search path=/opt/lib/tls/aarch64:/opt/lib/tls:/opt/lib/aarch64:/opt/lib:tls/aarch64:tls:aarch64:      (LD_LIBRARY_PATH)
     26438:       trying file=/opt/lib/tls/aarch64/libpthread.so.0
     26438:       trying file=/opt/lib/tls/libpthread.so.0
     26438:       trying file=/opt/lib/aarch64/libpthread.so.0
     26438:       trying file=/opt/lib/libpthread.so.0
     26438:
     26438:     find library=libdl.so.2 [0]; searching
     26438:      search path=/opt/lib:tls/aarch64:tls:aarch64:          (LD_LIBRARY_PATH)
     26438:       trying file=/opt/lib/libdl.so.2
     26438:
     26438:     find library=libstdc++.so.6 [0]; searching
     26438:      search path=/opt/lib:tls/aarch64:tls:aarch64:          (LD_LIBRARY_PATH)
     26438:       trying file=/opt/lib/libstdc++.so.6
     26438:
     26438:     find library=libm.so.6 [0]; searching
     26438:      search path=/opt/lib:tls/aarch64:tls:aarch64:          (LD_LIBRARY_PATH)
     26438:       trying file=/opt/lib/libm.so.6
     26438:
     26438:     find library=libgcc_s.so.1 [0]; searching
     26438:      search path=/opt/lib:tls/aarch64:tls:aarch64:          (LD_LIBRARY_PATH)
     26438:       trying file=/opt/lib/libgcc_s.so.1
     26438:
     26438:     find library=libc.so.6 [0]; searching
     26438:      search path=/opt/lib:tls/aarch64:tls:aarch64:          (LD_LIBRARY_PATH)
     26438:       trying file=/opt/lib/libc.so.6
     26438:
     26438:     /opt/lib/libc.so.6: error: relocation error: symbol _dl_exception_create, version GLIBC_PRIVATE not defined in file ld-linux-aarch64.so.1 with link time reference (fatal)
./dotnet: relocation error: /opt/lib/libc.so.6: symbol _dl_exception_create, version GLIBC_PRIVATE not defined in file ld-linux-aarch64.so.1 with link time reference
```

**Comment by agocke** [comment] 2022-07-13 06:50
Overall, it looks like the problem here has been identified -- the glibc configuration provided by asuswrt is not sufficient. Either the versions are incorrect, or there are problems with multiple versions being installed.

At the moment it doesn't look like there's anything wrong with the .NET binaries. Closing for now, but we can re-open if the glibc configuration matches any of our supported distro configurations and it still doesn't work.

**Closed by agocke** 2022-07-13 06:50 UTC
Labels: question, area-Host
