### ISSUE TITLE
Can't build on latest main

### ISSUE THREAD

**Issue by kg** [dotnet/runtime#55833] opened 2021-07-16 15:20 UTC
### Description

Builds broke after pulling latest main. I've tried deleting .dotnet, artifacts, etc.

```./build.sh --os Browser -c debug --subset mono+libs```

```
/home/kate/.nuget/packages/microsoft.dotnet.sharedframework.sdk/6.0.0-beta.21364.3/targets/sharedfx.targets(467,5): error : Assembly 'System.Private.Xml' is missing dependency 'System.Net.Http' [/home/kate/Projects/dotnet-runtime-wasm/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.sfxproj]
/home/kate/.nuget/packages/microsoft.dotnet.sharedframework.sdk/6.0.0-beta.21364.3/targets/sharedfx.targets(467,5): error : Assembly 'netstandard' is missing dependency 'System.Console' [/home/kate/Projects/dotnet-runtime-wasm/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.sfxproj]
/home/kate/.nuget/packages/microsoft.dotnet.sharedframework.sdk/6.0.0-beta.21364.3/targets/sharedfx.targets(467,5): error : Assembly 'System.Diagnostics.TextWriterTraceListener' is missing dependency 'System.Console' [/home/kate/Projects/dotnet-runtime-wasm/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.sfxproj]
/home/kate/.nuget/packages/microsoft.dotnet.sharedframework.sdk/6.0.0-beta.21364.3/targets/sharedfx.targets(467,5): error : Assembly 'netstandard' is missing dependency 'System.Net.Http' [/home/kate/Projects/dotnet-runtime-wasm/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.sfxproj]
/home/kate/.nuget/packages/microsoft.dotnet.sharedframework.sdk/6.0.0-beta.21364.3/targets/sharedfx.targets(467,5): error : Assembly 'netstandard' is missing dependency 'System.Net.WebSockets.Client' [/home/kate/Projects/dotnet-runtime-wasm/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.sfxproj]
/home/kate/.nuget/packages/microsoft.dotnet.sharedframework.sdk/6.0.0-beta.21364.3/targets/sharedfx.targets(467,5): error : Assembly 'System.Net.Http.Json' is missing dependency 'System.Net.Http' [/home/kate/Projects/dotnet-runtime-wasm/src/installer/pkg/sfx/Microsoft.NETCore.App/Microsoft.NETCore.App.Runtime.sfxproj]
```

### Configuration

Latest main
Debian 10 x64

### Regression?

Yes

**Comment by safern** [comment] 2021-07-16 17:30
It looks like the shared fx validation is failing for wasm runtime pack. Maybe @jkoritzinsky knows what to look for.

**Comment by kg** [comment] 2021-07-16 17:43
Rolling back main by about a week or so fixed it for me, FYI

**Comment by ericstj** [comment] 2021-07-16 19:54
Those errors imply that `System.Console` `System.Net.Http` and `System.Net.WebSockets.Client` were all missing from the shared fx directory being packaged.

What doesn't make sense to me is why the shared framework / installer subset is even being built when the specified subsets are `--subset mono+libs`.  Is is possible that https://github.com/dotnet/runtime/commit/d953229d5429d2ffde833740dd481aab864d3e0c somehow caused this?

**Comment by safern** [comment] 2021-07-16 20:22
While that change seems suspicious it seems like it didn't caused it or at least the dotnet-linker-tests browser build on that PR was green and it only build mono+libs:

```
 /__w/1/s/build.sh -ci -arch wasm -os Browser -s mono+libs -c Release -p:WasmBuildNative=false  /p:CrossBuild=false
```

https://dev.azure.com/dnceng/public/_build/results?buildId=1236923&view=logs&jobId=9bd06b96-2bdb-52e1-9716-7806e46fa22b&j=9bd06b96-2bdb-52e1-9716-7806e46fa22b&t=d83ae7ee-16ce-5d79-bbbc-579a57b6f65e

cc: @lewing @radical

**Comment by lewing** [comment] 2021-07-16 22:26
@kg I can't reproduce this, I just built main in a codespace without any problem.

**Comment by radical** [comment] 2021-07-16 22:47
I couldn't reproduce it either.

**Comment by kg** [comment] 2021-07-17 05:20
What should I clean other than artifacts, .dotnet and emsdk? I nuked my nuget cache too.

**Comment by kg** [comment] 2021-07-17 08:27
I can't reproduce this anymore on any revision of main, so it must have been some sort of transient issue with dependencies.

**Comment by kg** [comment] 2021-07-20 23:51
It came back, and rebasing onto latest main didn't fix it. I nuked artifacts, nuked ~/.nuget, nuked .dotnet, and did git clean -xffd. Any ideas?

**Comment by hoyosjs** [comment] 2021-07-21 03:36
hmm this comes from the dependency closure validation in https://github.com/dotnet/arcade/blame/89806f0b9e93ad2bbe32c654412835c0801a2032/src/Microsoft.DotNet.Build.Tasks.Packaging/src/VerifyClosure.cs#L209
@ericstj, maybe you might have some clues on where to look?

**Comment by kg** [comment] 2021-07-21 03:47
It started working again mysteriously an hour or two ago, but I didn't change anything that I think should've caused it to start working again.

**Comment by ericstj** [comment] 2021-07-21 04:17
The error indicates that those assemblies are  missing from the shared framework directory which is a real problem (assuming it’s correct). Did you see the exact same errors?  Is it possible there were earlier build failures that you missed? Share a binlog if you repro and we can have a look.

**Comment by kg** [comment] 2021-07-21 04:22
Good point, I regret not saving a binlog any of these previous times.

I'm using the ```runtime/.dotnet/``` automatically provisioned by the infrastructure and I purged it by hand. Likewise that .nuget in my home dir was purged too.

The errors were exactly the same (including the set of assemblies) every time it happened, and it would happen repeatedly if I re-ran the build. I'm still not sure why it started working again once previously, or why it re-broke and then started working again afterward...

**Comment by ericstj** [comment] 2021-07-21 16:59
Could be that some build action is removing/rebuilding the files and there is some sort of race.  I have seen things like this before when folks have an IDE open as it might trigger builds as a result of the commandline build and those race with the actual build process.  If it repros again grab a binlog and also inspect <artifacts>\bin\microsoft.netcore.app.runtime.<RID>\<Configuration>\... that should have the files in question.  If it doesn't then look at the binlog find out why.

**Comment by kg** [comment] 2021-07-21 17:07
Interesting point - I have VS code open, but I don't use its build functionality so I never considered whether it could be invoking msbuild here.

**Comment by akoeplinger** [comment] 2021-07-21 17:43
If you have the C# extension activated it might, I'd try disabling it for the workspace if you're not using it.

**Comment by agocke** [comment] 2022-07-29 21:14
Closing until this repros again.

**Closed by agocke** 2022-07-29 21:14 UTC
Labels: os-linux, area-Infrastructure
