### ISSUE TITLE
Multiple PRs failing with WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests failure

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#78892] opened 2022-11-27 21:05 UTC
```
[20:18:39] fail: [FAIL] System.Runtime.InteropServices.JavaScript.Tests.JSImportExportTest.JsImportTaskTypes
[20:18:39] info: System.ObjectDisposedException : Cannot access a disposed object.
[20:18:39] info: Object name: 'value'.
[20:18:39] info:    at System.Runtime.InteropServices.JavaScript.Tests.JavaScriptTestHelper.echopromise_JSObject(JSObject value)
[20:18:39] info:    at System.Runtime.InteropServices.JavaScript.Tests.JSImportExportTest.JsImportTaskTypes()
```
e.g.

- https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-78580-merge-b5300e4f62ba4ceda2/WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests/1/console.763a06ed.log?helixlogtype=result
- https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-78888-merge-4816d5330d8744be90/WasmTestOnBrowser-System.Runtime.InteropServices.JavaScript.Tests/1/console.1b6cace7.log?helixlogtype=result

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by jkotas** [comment] 2022-11-28 23:53
Duplicate of https://github.com/dotnet/runtime/issues/77334

**Closed by jkotas** 2022-11-28 23:53 UTC
Labels: untriaged, area-System.Runtime.InteropServices.JavaScript, Known Build Error
