### ISSUE TITLE
ConfigurationBinder.Bind fails to bind null to a nullable property of a record type

### ISSUE THREAD

**Issue by Dersei** [dotnet/runtime#109816] opened 2024-11-14 11:07 UTC
### Description

Using `Bind` with `IConfiguration` on a specific configuration of classes and records results in an exception.

### Reproduction Steps

I have a structure like this in my application:

```csharp
public record Child;
public record Parent(Child? Child);

public class Wrapper
{
    public Parent Parent { get; init; } = null!;
}
```
It's part of my app's configuration, so I have the corresponding section in appsettings.json:
```csharp
{
  "Wrapper": {
    "Parent": {
      "Child": null
    }
  }
}
```
And then I bind that section to the instance of the class using ConfigurationBinder.Bind extension method:

```csharp
var wrapper = new Wrapper();
hostContext.Configuration.GetSection("Wrapper").Bind(wrapper);
```

### Expected behavior

The configuration should deserialize correctly - `Child` property in `Parent` should be set to `null` - or at least the exception should be more clear about the source of the problem.

### Actual behavior

An exception is thrown:
```csharp
System.ArgumentException: Object of type 'System.String' cannot be converted to type 'Child'.
   at System.RuntimeType.CheckValue(Object& value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.ConstructorInfo.Invoke(Object[] parameters)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.CreateInstance(Type type, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, BindingPoint bindingPoint, IConfiguration config, BinderOptions options, Boolean isParentCollection)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperties(Object instance, IConfiguration configuration, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, BindingPoint bindingPoint, IConfiguration config, BinderOptions options, Boolean isParentCollection)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Bind(IConfiguration configuration, Object instance, Action`1 configureOptions)
```

### Known Workarounds

`Parent` record can be replaced with a class:

```csharp
public class Parent
{
    public required Child? Child { get; init; }
}
```

### Configuration

The situation happens on both .NET 8 and .NET 9 with packages versions:
```xml
<PackageVersion Include="Microsoft.Extensions.Configuration" Version="9.0.0" />
<PackageVersion Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.0" />
<PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="9.0.0" />
<PackageVersion Include="System.Text.Json" Version="9.0.0" />
```
and 
```xml
<PackageVersion Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
<PackageVersion Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.2" />
<PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
<PackageVersion Include="System.Text.Json" Version="8.0.4" />
```

**Comment by tarekgh** [comment] 2024-11-14 18:40
This is duplicate of https://github.com/dotnet/runtime/issues/36510

**Closed by tarekgh** 2024-11-14 18:40 UTC
Labels: untriaged, area-Extensions-Configuration
