### ISSUE TITLE
Xcode local build failure: xcode-select : error : tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#102471] opened 2024-05-20 23:37 UTC
When building runtime in my local Macbook Pro with `build.sh -rc Release` today, I got this failure:

```
xcode-select : error : tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance [/Users/carlos/repos/runtime/src/coreclr/tools/aot/ILCompiler/ILCompiler.csproj]
/Users/carlos/repos/runtime/src/coreclr/tools/aot/ILCompiler/ILCompiler.csproj(79,24): error MSB4086: A numeric comparison was attempted on "$(_XcodeVersion)" that evaluates to "" instead of a number, in condition "'$(_XcodeVersion)' >= '15'".
```

It came from here:
https://github.com/dotnet/runtime/blob/main/src/coreclr/tools/aot/ILCompiler/ILCompiler.csproj#L79

Root cause was that the `Xcode -> Preferences -> Location -> Command Line Tools` dropdown was set to `No Xcode selected`. So I had to manually select the single only option in the dropdown and now the local build succeeded. It's explained here:
https://stackoverflow.com/a/72115137

The top error comes from Xcode itself, but that message wasn't helpful. But we could kind of address this from our side:

- We could add a new MSBuild message on our side when we detect such Xcode error message.
- We could document this as a manual configuration prerequisite step for building in https://github.com/dotnet/runtime/blob/main/docs/workflow/requirements/macos-requirements.md
- Or if this can be configured automatically for the user when building, even better.

**Comment by jkotas** [comment] 2024-05-20 23:41
Duplicate of https://github.com/dotnet/runtime/issues/100189 ?

**Comment by carlossanlop** [comment] 2024-05-20 23:46
Yes, it seems like the same failure, it just happened at different times. I'll close this and update that one with my findings and my suggestions.

**Comment by carlossanlop** [comment] 2024-05-20 23:48
Oh I typed too soon - That one is already closed as fixed. Maybe it was a different root cause, as that one was merged 2 months ago.

**Comment by jkotas** [comment] 2024-05-20 23:51
You can try the change in #102473 to check that it fixes the build break for you.

**Closed** 2024-05-21 10:41 UTC
Labels: os-mac-os-x, untriaged, area-NativeAOT-coreclr
