### ISSUE TITLE
CI infrastructure failure: Unable to pull image mcr.microsoft.com/...

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#2209] opened 2020-01-26 18:17 UTC
I have seen this intermittent error on number of different CI jobs in last few days.

cc @dotnet/runtime-infrastructure

**Comment by jkotas** [comment] 2020-01-26 18:18
Failed in https://github.com/dotnet/runtime/pull/2203 :

```
Output:
Unable to pull image mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-61052b7-20190723211353
Exit Code:-4
```

**Comment by jkotas** [comment] 2020-01-27 03:41
Failed in #2212
```
Output:
Unable to pull image mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-61052b7-20190723211353
Exit Code:-4
```

**Comment by safern** [comment] 2020-01-27 18:52
cc: @MattGal could you take a look at this please? It seems like helix is sometimes failing to pull down the image to run the tests.

**Comment by MattGal** [comment] 2020-01-27 21:00
> cc: @MattGal could you take a look at this please? It seems like helix is sometimes failing to pull down the image to run the tests.

Taking a look...

**Comment by MattGal** [comment] 2020-01-27 21:15
Relevant Kusto query:

```
WorkItems
| where QueueName == "windows.10.amd64.serverrs5.open" and ExitCode == -4
| summarize count() by MachineName
```
In short, this has only happened once, on three machines in history for Windows, and it seems like something really horked Docker starting from the first work item on these machines.

The machines in question are all recycled; if this reproduces again, we need to get on a machine and investigate the state of the Docker windows service, as we've never seen this in 1.5 years of Windows docker support.  I'd recommend closing this and pinging dnceng asap if you ever see it again.

**Comment by jkotas** [comment] 2020-01-27 22:18
Ok, thanks for taking a look.

**Comment by jkotas** [comment] 2020-02-01 00:53
Hit by https://dev.azure.com/dnceng/public/_build/results?buildId=503475&view=ms.vss-test-web.build-test-results-tab&runId=15997016&resultId=177483&paneView=attachments :
```
Output:
Unable to pull image mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-29-helix-a12566d-20191210224553
Exit Code:-4
```

**Comment by MattGal** [comment] 2020-02-01 01:02
This is totally different from the last time, other than I use -4 to indicate docker problems... linux vs. windows, this time it's an http 500 from mcr.microsoft.com versus a problem talking to the daemon:
```
2020-01-31T23:19:59.127Z	INFO   	servicebusrepository(109)	renew_workitem_lock	Renewed work item lock. Status Code: 200
2020-01-31T23:20:28.397Z	WARNING	dockerhelper(63)	pull	Hit exception trying to pull: 500 Server Error: Internal Server Error ("Get https://mcr.microsoft.com/v2/dotnet-buildtools/prereqs/manifests/fedora-29-helix-a12566d-20191210224553: dial tcp 40.112.242.159:443: i/o timeout") Retrying up to 5 times
2020-01-31T23:20:44.128Z	INFO   	servicebusrepository(99)	renew_workitem_lock	Entering renew_workitem_lock for https://nethelix.servicebus.windows.net/ubuntu.1604.amd64.open/messages/97039465/3f424dd8-9ed5-4c2a-b2ec-c53e175ce09e
```
@MichaelSimons  / @mthalman do you guys have a recommended support path for asking mcr for "did stuff happen in this time frame?"

**Comment by MichaelSimons** [comment] 2020-02-03 14:21
@MattGal - you could log an issue on the [internal MCR repo](https://github.com/microsoft/mcr) or ask on the [internal MCR-Talk teams channel](https://teams.microsoft.com/l/team/19%3a7ec341fcc0594ebf92e1dd6ed0ae43be%40thread.skype/conversations?groupId=18d401f3-650b-4a4e-8d7e-72f8f7162949&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)

**Comment by ViktorHofer** [comment] 2020-02-13 21:26
Just happened again in CI: https://dev.azure.com/dnceng/public/_build/results?buildId=519517&view=ms.vss-test-web.build-test-results-tab&runId=16423544&resultId=169297&paneView=attachments

```
Executed on a0018G7 using docker image mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-08e8e40-20200107182504
running %HELIX_CORRELATION_PAYLOAD%\scripts\5d0d34f0b7e34c27828fb41b52c8f01f\execute.cmd in C:\h\w\949308AE\w\9FD308FB\e max 900 seconds

Output:
Unable to pull image mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-08e8e40-20200107182504
Exit Code:-4
```

**Comment by MichaelSimons** [comment] 2020-02-13 21:30
@MattGal - Naive question, does this Helix logic have retry logic around pulling images?

**Comment by MattGal** [comment] 2020-02-18 21:02
> @MattGal - Naive question, does this Helix logic have retry logic around pulling images?

Correct, there are 5 retries;  however this one was not the HTTP 500 we've seen recently from MCR rather I think that machine's docker service itself failed.  (it's long since been recycled)

**Comment by MattGal** [comment] 2020-02-19 17:53
@MichaelSimons I thought on this issue further and made this PR https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines/pullrequest/6269?_a=files which will cause work items to auto retry and the machine to reboot as well if failures happen in container pruning or pull operations (previously we only saw this symptom in run scenarios)

**Comment by safern** [comment] 2020-02-20 19:06
Failed again on: https://dev.azure.com/dnceng/public/_build/results?buildId=529417&view=logs for multiple workitems.

https://helix.dot.net/api/2019-06-17/jobs/2e23327f-6e1e-4ee0-b137-1f8caa13ffb7/workitems/System.Numerics.Vectors.Tests/console

@MattGal I guess rollout will be next week?

**Comment by MattGal** [comment] 2020-02-20 19:14
> Failed again on: https://dev.azure.com/dnceng/public/_build/results?buildId=529417&view=logs for multiple workitems.
> 
> https://helix.dot.net/api/2019-06-17/jobs/2e23327f-6e1e-4ee0-b137-1f8caa13ffb7/workitems/System.Numerics.Vectors.Tests/console
> 
> @MattGal I guess rollout will be next week?

Sorry about that yes, we're hoping to roll out the new infra retry behavior Tuesday, no blocking issues stopping that.

**Comment by MattGal** [comment] 2020-02-20 19:16
Looks like it happened on 5 machines in the past day and they're all cleaned up now.  This time the error seemed relevant to the container's mounts (the workaround should solve this regardless) so I'll investigate to see if a previous work item on the machines caused shenanigans too.

**Comment by jaredpar** [comment] 2020-03-02 18:53
Closing as we haven't seen recent occurrences of this. Please re-open if they pop up again.

**Closed by jaredpar** 2020-03-02 18:53 UTC
Labels: area-Infrastructure, blocking-clean-ci, untriaged

**Comment by MattGal** [comment] 2020-03-02 23:14
> Closing as we haven't seen recent occurrences of this. Please re-open if they pop up again.

I actually rolled out a fix for this last week :) that's awesome to hear, and fingers crossed it stays this way.
