### ISSUE TITLE
FileStream sets default encoding to UTF8-BOM in .net6

### ISSUE THREAD

**Issue by jsienkie223** [dotnet/runtime#67229] opened 2022-03-28 11:46 UTC
### Description

FileStream sets different files encodings depending on the .net version:
using .net5 its UTF-8
using .net6 its UTF-8 with BOM

### Reproduction Steps

var fileStream = new FileStream(filename, FileMode.Create);
var obj = new object();
var xmlSerialiser = new XmlSerializer(obj.GetType());
xmlSerialiser.Serialize(fileStream, obj);

### Expected behavior

both .net5 and .net 6 use the same file encoding

### Actual behavior

.net5: file is encoded using UTF-8
.net6: file is encoded using UTF-8 with BOM

### Known Workarounds

Wrap FilesStream with StreamWriter which forces utf-6 without BOM enocding in .net6

### Configuration

-  .net6/.net5
- windows 10
- x64
-

**Comment by KeterSCP** [comment] 2022-03-28 13:58
Seems like a duplicate of https://github.com/dotnet/runtime/issues/63585

**Comment by adamsitnik** [comment] 2022-03-28 15:44
@KeterSCP is right, this is a duplicate of #63585

**Closed by adamsitnik** 2022-03-28 15:44 UTC
Labels: area-Serialization, untriaged
