### ISSUE TITLE
Crash when running dotnet command with .NET 7 7.0.100-preview.5.22267.11-win-arm64

### ISSUE THREAD

**Issue by WenJunJi01** [dotnet/runtime#69513] opened 2022-05-18 09:30 UTC
**Environment:** .NET SDK 7.0.100-preview.5.22267.11(runtime-7.0.0-preview.5.22266.11)

**Repro steps:**

1. Install .NET SDK .NET SDK 7.0.100-preview.5.22267.11 on a clean Windows ARM64 OS.
2. Run dotnet command in CLI, for example, `dotnet --info`

**Expected Result:**
The command can be executed.

**Actual Result:**
Crash when running dotnet command.
![image](https://user-images.githubusercontent.com/87680983/169006663-4730d567-b9eb-4054-98fc-6e4754ce1fe1.png)

**Comment by danmoseley** [comment] 2022-05-18 19:46
@WenJunJi01 can you confirm it works for you with preview 4? perhaps you could try older preview 5 builds? to help narrow it down.

**Comment by NicoleWang001** [comment] 2022-05-19 04:43
@danmoseley  
This issue is not repro with 7.0.100-preview.4.22252.9.
This issue is not repro with 7.0.100-preview.5.22263.22 either.

**Comment by tarekgh** [comment] 2022-05-19 17:45
CC @jkotas 

This looks the coreclr is calling AppContext.Setup passing invalid pointers?

**Comment by jkotas** [comment] 2022-05-19 17:51
Duplicate of https://github.com/dotnet/runtime/issues/69222

**Closed by jkotas** 2022-05-19 17:51 UTC
Labels: arch-arm64, area-VM-coreclr, untriaged, arm64
