### ISSUE TITLE
Accessing struct with static generic struct field of self/`this` type throws TypeLoadExcaption

### ISSUE THREAD

**Issue by Sewer56** [dotnet/runtime#1105] opened 2019-12-21 01:57 UTC
**Human Explanation**
If a struct contains a **static field** that is a struct accepting generic type `T`. and type `T` is the struct itself, attempting to access the struct will throw a `TypeLoadException`.

**Minimal Reproduction**:

```csharp
class Program
{
    static unsafe void Main(string[] args) => TypeLoadException();
    static object TypeLoadException() => SelfReferencingType.Entry;

    public struct SelfReferencingType
    {
        public static Generic<SelfReferencingType> Entry = new Generic<SelfReferencingType>();
    }

    public struct Generic<T>
    {
        public T Value;
    }
}
```

Tested with .NET Core 2.1 and .NET Core 3.0.

**Expected Result**:
Program Terminates

**Actual Result**:
```
System.TypeLoadException: 'Could not load type 'Reproduction.Program+SelfReferencingType' from assembly 'Reproduction, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.'
```

![devenv_nVovUsWSIH](https://user-images.githubusercontent.com/6697380/71301371-36391a80-2396-11ea-9411-cb8336c86536.png)

**Comment by jkotas** [comment] 2019-12-21 14:40
This is duplicate of https://github.com/dotnet/coreclr/issues/4049. Unfortunately, it is very hard to fix in the current CoreCLR implementation (https://github.com/dotnet/coreclr/issues/7957 has some discussion about it).

**Closed by jkotas** 2019-12-21 14:40 UTC
Labels: area-TypeSystem, untriaged
