### ISSUE TITLE
BadImageFormatException when calling static virtual method in interface

### ISSUE THREAD

**Issue by serialexperiment** [dotnet/runtime#82217] opened 2023-02-16 01:51 UTC
### Description

Calling static methods from an interface on another interface type implementing the first interface causes a BadImageFormatException (Method has no body) on Android.  I have tried this on both an emulator and my actual Android phone, and I get the same result both ways.  The exact same code works on Windows, but fails on Android.  I wasn't sure if this was a runtime issue or a rosalyn issue so I just raised it here - sorry if this isn't the right place.

### Reproduction Steps

Here is a simple MAUI app that reproduces the issue:
[Repo link](https://github.com/serialexperiment/StaticVirtualInterfaceMemberIssue)

**edit by @akoeplinger** See https://github.com/dotnet/runtime/issues/82217#issuecomment-2058734115 for a simpler repro

**On Android:**

1. Have an interface with a static virtual member, like this:
`public interface IHaveStaticMethod
{
	static abstract void Method();
}`

2. Have another interface that implements the first interface, like this:
`public interface IInterface : IHaveStaticMethod
{
	static void IHaveStaticMethod.Method()
	{
		Console.WriteLine("Hello, world!");
	}
}`

3. Call the static method, using a method like this:
`private void CallMethod<T>() where T : IHaveStaticMethod => T.Method();`

### Expected behavior

The method should be called, like it is on Windows

### Actual behavior

Exception: System.BadImageFormatException: Method has no body

### Regression?

I don't think this is a regression, seeing as how the language feature is pretty new.

### Configuration

- .NET 7
- Only occurs on Android as far as I know (I don't have a means of testing IOS or anything else)

**Comment by SamMonoRT** [comment] 2023-07-25 17:51
cc @BrzVlad as he worked on the static virtual interface support a bit.

**Comment by thaystg** [comment] 2023-08-09 19:07
I have a fix for it here: https://github.com/dotnet/runtime/compare/main...thaystg:runtime:thays_fix_82217?expand=1
Not sure if it's good enough.

**Comment by thaystg** [comment] 2023-10-04 13:58
I'm not working on it. We can move it to net9.

**Comment by BrzVlad** [comment] 2023-10-04 14:18
This issue seems to consist of a constrained call where the generic type is also an interface. This looks like a duplicate of https://github.com/dotnet/runtime/issues/90139. I think this is fixed on main.

**Comment by akoeplinger** [comment] 2024-04-16 10:13
This is still an issue in 9.0, I extracted the repro into a simpler console-based mono app: 
[repro.zip](https://github.com/dotnet/runtime/files/14995269/repro.zip)

1.`dotnet publish --self-contained`
2. Run `bin/Release/net9.0/osx-arm64/publish/repro`

Crash:
```
.NET 9.0.0-preview.3.24172.9
IsMono: True
Hello, world!
* Assertion at /Users/runner/work/1/s/src/mono/mono/mini/mini-generic-sharing.c:2758, condition `is_ok (error)' not met, function:mini_instantiate_gshared_info, (null) assembly:/Users/alexander/dev/test/repro/bin/Release/net9.0/osx-arm64/publish/System.Private.CoreLib.dll type:BadImageFormatException member:(null)


=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x104fac858 - /Users/alexander/dev/test/repro/bin/Release/net9.0/osx-arm64/publish/libcoreclr.dylib : mono_dump_native_crash_info
	0x104f5ae74 - /Users/alexander/dev/test/repro/bin/Release/net9.0/osx-arm64/publish/libcoreclr.dylib : mono_handle_native_crash
	0x10517c138 - /Users/alexander/dev/test/repro/bin/Release/net9.0/osx-arm64/publish/libcoreclr.dylib : sigabrt_signal_handler.cold.1
	0x104fac1bc - /Users/alexander/dev/test/repro/bin/Release/net9.0/osx-arm64/publish/libcoreclr.dylib : mono_runtime_setup_stat_profiler
	0x184917584 - /usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x1848e6c20 - /usr/lib/system/libsystem_pthread.dylib : pthread_kill
	0x1847f3a20 - /usr/lib/system/libsystem_c.dylib : abort
	0x10504c780 - /Users/alexander/dev/test/repro/bin/Release/net9.0/osx-arm64/publish/libcoreclr.dylib : monoeg_g_printv
	0x105059e54 - /Users/alexander/dev/test/repro/bin/Release/net9.0/osx-arm64/publish/libcoreclr.dylib : mono_log_write_logfile
	0x10504cb30 - /Users/alexander/dev/test/repro/bin/Release/net9.0/osx-arm64/publish/libcoreclr.dylib : monoeg_g_logv_nofree
	0x10504cbd4 - /Users/alexander/dev/test/repro/bin/Release/net9.0/osx-arm64/publish/libcoreclr.dylib : monoeg_assertion_message
	0x104f63524 - /Users/alexander/dev/test/repro/bin/Release/net9.0/osx-arm64/publish/libcoreclr.dylib : instantiate_info
	0x104f0a9d0 - /Users/alexander/dev/test/repro/bin/Release/net9.0/osx-arm64/publish/libcoreclr.dylib : mini_init_method_rgctx
	0x1049be120 - Unknown
	0x10486a8bc - Unknown
	0x10486abe8 - Unknown
	0x104ec4338 - /Users/alexander/dev/test/repro/bin/Release/net9.0/osx-arm64/publish/libcoreclr.dylib : mono_jit_runtime_invoke
	0x1050dd094 - /Users/alexander/dev/test/repro/bin/Release/net9.0/osx-arm64/publish/libcoreclr.dylib : mono_runtime_invoke_checked
	0x1050e4850 - /Users/alexander/dev/test/repro/bin/Release/net9.0/osx-arm64/publish/libcoreclr.dylib : mono_runtime_exec_main_checked
	0x104f19510 - /Users/alexander/dev/test/repro/bin/Release/net9.0/osx-arm64/publish/libcoreclr.dylib : mono_jit_exec
	0x104f1bfec - /Users/alexander/dev/test/repro/bin/Release/net9.0/osx-arm64/publish/libcoreclr.dylib : mono_main
	0x104f91564 - /Users/alexander/dev/test/repro/bin/Release/net9.0/osx-arm64/publish/libcoreclr.dylib : monovm_execute_assembly
	0x1047a1b90 - /Users/alexander/dev/test/repro/bin/Release/net9.0/osx-arm64/publish/libhostpolicy.dylib : _Z19run_app_for_contextRK20hostpolicy_context_tiPPKc
	0x1047a298c - /Users/alexander/dev/test/repro/bin/Release/net9.0/osx-arm64/publish/libhostpolicy.dylib : corehost_main
	0x1046d2744 - /Users/alexander/dev/test/repro/bin/Release/net9.0/osx-arm64/publish/libhostfxr.dylib : _ZN10fx_muxer_t24handle_exec_host_commandERKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEERK19host_startup_info_tS8_RKNS0_13unordered_mapI13known_optionsNS0_6vectorIS6_NS4_IS6_EEEE18known_options_hashNS0_8equal_toISD_EENS4_INS0_4pairIKSD
	0x1046d19c4 - /Users/alexander/dev/test/repro/bin/Release/net9.0/osx-arm64/publish/libhostfxr.dylib : _ZN10fx_muxer_t7executeENSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEiPPKcRK19host_startup_info_tPciPi
	0x1046ce568 - /Users/alexander/dev/test/repro/bin/Release/net9.0/osx-arm64/publish/libhostfxr.dylib : hostfxr_main_startupinfo
	0x10464d510 - /Users/alexander/dev/test/repro/bin/Release/net9.0/osx-arm64/publish/repro : _Z9exe_startiPPKc
	0x10464d724 - /Users/alexander/dev/test/repro/bin/Release/net9.0/osx-arm64/publish/repro : main
	0x18455e0e0 - /usr/lib/dyld : start

=================================================================
	External Debugger Dump:
=================================================================

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x1848aea60):0x1848aea50  ff 0f 5f d6 c0 03 5f d6 10 29 80 d2 01 10 00 d4  .._..._..)......
0x1848aea60  03 01 00 54 7f 23 03 d5 fd 7b bf a9 fd 03 00 91  ...T.#...{......
0x1848aea70  50 e0 ff 97 bf 03 00 91 fd 7b c1 a8 ff 0f 5f d6  P........{...._.
0x1848aea80  c0 03 5f d6 70 0a 80 d2 01 10 00 d4 03 01 00 54  .._.p..........T

=================================================================
	Managed Stacktrace:
=================================================================
=================================================================
zsh: abort      bin/Release/net9.0/osx-arm64/publish/repro
```

**Comment by thaystg** [comment] 2024-06-28 13:16
@steveisok is someone from your team that should work on it?

**Comment by steveisok** [comment] 2024-08-09 19:44
I think this is a duplicate of https://github.com/dotnet/runtime/issues/79331. Closing.

**Closed by steveisok** 2024-08-09 19:44 UTC
Labels: area-VM-meta-mono
