### ISSUE TITLE
No nullability annotation for StringValues

### ISSUE THREAD

**Issue by onyxmaster** [dotnet/runtime#45819] opened 2020-12-09 07:34 UTC
Currently, the [StringValues string conversion operator](https://github.com/dotnet/runtime/blob/9d3d945b5add4035ab547af16f76a17e39768285/src/libraries/Microsoft.Extensions.Primitives/src/StringValues.cs#L72) (and [StringValues.GetStringValue](https://github.com/dotnet/runtime/blob/9d3d945b5add4035ab547af16f76a17e39768285/src/libraries/Microsoft.Extensions.Primitives/src/StringValues.cs#L173)) are not nullable-annotated.

Since this implicit conversion can return null but is not annotated as such, it easily breaks code if you rely on nullability annotations. This is especially bad because the conversion is implicit and because of this, you can pass an empty StringValues to a method that expects a string, but null is passed instead, while the nullability analyzer stays silent.

I understand that not everything is null-annotated (especially former parts of ASP.NET Core), but we were bitten by this and the required change is probably minimal (although it might require other code to be annotated too).

**Comment by eerhardt** [comment] 2020-12-11 15:48
Duplicate of https://github.com/dotnet/runtime/issues/43605.

**Closed by eerhardt** 2020-12-11 15:48 UTC
Labels: area-Extensions-Primitives, untriaged
