### ISSUE TITLE
Test failure:Loader/classloader/generics/Instantiation/Positive/NestedBaseClass05/NestedBaseClass05.sh 

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#55551] opened 2021-07-13 02:50 UTC
Run: [runtime-coreclr r2r-extra 20210711.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1232094&view=ms.vss-test-web.build-test-results-tab&runId=36687280&resultId=107046&paneView=debug)

Failed test:
```
R2R OSX arm64 Checked jitstressregs3 @ OSX.1100.ARM64.Open

- Loader/classloader/generics/Instantiation/Positive/NestedBaseClass05/NestedBaseClass05.sh

R2R OSX arm64 Checked jitstressregs2 @ OSX.1100.ARM64.Open

- JIT/HardwareIntrinsics/X86/Avx2_Vector128/Avx2_ro/Avx2_ro.sh

```
**Error message:**
```
/private/tmp/helix/working/B80309D1/w/B5EF0990/e/JIT/HardwareIntrinsics/X86/Avx2_Vector128/Avx2_ro/Avx2_ro.sh: line 254: -r:/private/tmp/helix/working/B80309D1/w/B5EF0990/e/JIT/HardwareIntrinsics/X86/Avx2_Vector128/Avx2_ro/IL-CG2/.dll: No such file or directory
rm: /private/tmp/helix/working/B80309D1/w/B5EF0990/e/JIT/HardwareIntrinsics/X86/Avx2_Vector128/Avx2_ro/Avx2_ro.dll.rsp: No such file or directory
rm: /private/tmp/helix/working/B80309D1/w/B5EF0990/e/JIT/HardwareIntrinsics/X86/Avx2_Vector128/Avx2_ro/TestLibrary.dll.rsp: No such file or directory
Unhandled exception. System.AggregateException: One or more errors occurred. (Code generation failed for method '[TestLibrary]TestLibrary.Assert.ThrowsArgumentException<__Canon>(string,Action,string)') (Code generation failed for method '[TestLibrary]TestLibrary.Utilities.GetWindowsBuildNumber()') (Code generation failed for method '[TestLibrary]TestLibrary.Assert.AreAllEqual<__Canon>(__Canon[],__Canon[],string)') (Code generation failed for method '[TestLibrary]TestLibrary.Assert.AreAllEqualUnordered<__Canon>(__Canon[],__Canon[])')
---> ILCompiler.CodeGenerationFailedException: Code generation failed for method '[TestLibrary]TestLibrary.Assert.ThrowsArgumentException<__Canon>(string,Action,string)'
---> System.NullReferenceException: Object reference not set to an instance of an object.
at System.SZArrayHelper.GetEnumeratorT in System.Private.CoreLib.dll:token 0x6000158+0x0
at ILCompiler.ReadyToRunCompilationModuleGroupBase.ComputeInstantiationVersionsWithCode(Instantiation inst, TypeSystemEntity entityWithInstantiation) in ILCompiler.ReadyToRun.dll:token 0x60000db+0x0
at System.Collections.Concurrent.ConcurrentDictionary2.GetOrAdd(TKey key, Func2 valueFactory) in System.Collections.Concurrent.dll:token 0x60000d3+0x4f
at Internal.JitInterface.CorInfoImpl.HandleToModuleToken(CORINFO_RESOLVED_TOKEN& pResolvedToken, MethodDesc methodDesc, Object& context, TypeDesc& constrainedType) in ILCompiler.ReadyToRun.dll:token 0x6000724+0x3
at Internal.JitInterface.CorInfoImpl.ComputeMethodWithToken(MethodDesc method, CORINFO_RESOLVED_TOKEN& pResolvedToken, TypeDesc constrainedType, Boolean unboxing) in ILCompiler.ReadyToRun.dll:token 0x6000723+0x0
at Internal.JitInterface.CorInfoImpl.getCallInfo(CORINFO_RESOLVED_TOKEN& pResolvedToken, CORINFO_RESOLVED_TOKEN pConstrainedResolvedToken, CORINFO_METHOD_STRUCT_* callerHandle, CORINFO_CALLINFO_FLAGS flags, CORINFO_CALL_INFO* pResult) in ILCompiler.ReadyToRun.dll:token 0x600073c+0x266
at Internal.JitInterface.CorInfoImpl.getCallInfo(IntPtr thisHandle, IntPtr* ppException, CORINFO_RESOLVED_TOKEN* pResolvedToken, CORINFO_RESOLVED_TOKEN* pConstrainedResolvedToken, CORINFO_METHOD_STRUCT* callerHandle, CORINFO_CALLINFO_FLAGS flags, CORINFO_CALL_INFO* pResult) in ILCompiler.ReadyToRun.dll:token 0x60007e0+0x7
--- End of inner exception stack trace ---
at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(IMethodNode methodCodeNodeNeedingCode, MethodIL methodIL) in ILCompiler.ReadyToRun.dll:token 0x6000813+0xc8
at Internal.JitInterface.CorInfoImpl.CompileMethod(MethodWithGCInfo methodCodeNodeNeedingCode, Logger logger) in ILCompiler.ReadyToRun.dll:token 0x600071d+0x48
at ILCompiler.ReadyToRunCodegenCompilation.<ComputeDependencyNodeDependencies>b__36_0(DependencyNodeCore1 dependency) in ILCompiler.ReadyToRun.dll:token 0x600013c+0x0 at System.Threading.Tasks.Parallel.<>c__DisplayClass19_01.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000067+0xcf
--- End of stack trace from previous location ---
at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) in System.Threading.Tasks.Parallel.dll:token 0x6000067+0x1e7
at System.Threading.Tasks.TaskReplicator.Replica.Execute() in S


Stack trace
   at JIT_HardwareIntrinsics._X86_Avx2_Vector128_Avx2_ro_Avx2_ro_._X86_Avx2_Vector128_Avx2_ro_Avx2_ro_sh() in JIT.HardwareIntrinsics.XUnitWrapper.dll:token 0x600013a+0x295
```

**Comment by mangod9** [comment] 2021-07-20 01:56
Dupe of #51250

**Closed by mangod9** 2021-07-20 01:56 UTC
Labels: JitStress, arch-arm64, area-crossgen2-coreclr, untriaged
