### ISSUE TITLE
Could not load file or assembly 'Microsoft.CodeAnalysis.NetAnalyzers

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#84995] opened 2023-04-18 17:45 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=242955
Build error leg or test failing: Build / coreclr Common Pri0 Test Build AnyOS AnyCPU checked / Build managed test components
Pull request: https://github.com/dotnet/runtime/pull/79169

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Could not load file or assembly 'Microsoft.CodeAnalysis.NetAnalyzers",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[381868](https://dev.azure.com/dnceng-public/public/_build/results?buildId=381868)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/381868/logs/1009)|dotnet/runtime#90912|
|[381040](https://dev.azure.com/dnceng-public/public/_build/results?buildId=381040)|dotnet/runtime|Build managed test components|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/381040/logs/846)|dotnet/runtime#90814|
|[380937](https://dev.azure.com/dnceng-public/public/_build/results?buildId=380937)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/380937/logs/1019)||
|[379994](https://dev.azure.com/dnceng-public/public/_build/results?buildId=379994)|dotnet/runtime|Build managed test components|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/379994/logs/96)||
|[377230](https://dev.azure.com/dnceng-public/public/_build/results?buildId=377230)|dotnet/runtime|Build managed test components|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/377230/logs/77)||
|[375016](https://dev.azure.com/dnceng-public/public/_build/results?buildId=375016)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/375016/logs/313)||
|[374758](https://dev.azure.com/dnceng-public/public/_build/results?buildId=374758)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/374758/logs/1092)|dotnet/runtime#90620|
|[374599](https://dev.azure.com/dnceng-public/public/_build/results?buildId=374599)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/374599/logs/889)||
|[372068](https://dev.azure.com/dnceng-public/public/_build/results?buildId=372068)|dotnet/runtime|Build managed test components|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/372068/logs/996)||
|[370598](https://dev.azure.com/dnceng-public/public/_build/results?buildId=370598)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/370598/logs/539)|dotnet/runtime#90360|
|[369321](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369321)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/369321/logs/967)|dotnet/runtime#90273|
|[369189](https://dev.azure.com/dnceng-public/public/_build/results?buildId=369189)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/369189/logs/418)|dotnet/runtime#90290|
|[367837](https://dev.azure.com/dnceng-public/public/_build/results?buildId=367837)|dotnet/runtime|Build managed test components|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/367837/logs/99)||
|[367215](https://dev.azure.com/dnceng-public/public/_build/results?buildId=367215)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/367215/logs/340)|dotnet/runtime#90132|
|[367201](https://dev.azure.com/dnceng-public/public/_build/results?buildId=367201)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/367201/logs/1001)|dotnet/runtime#88926|
|[366557](https://dev.azure.com/dnceng-public/public/_build/results?buildId=366557)|dotnet/runtime|Build managed test components|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/366557/logs/765)|dotnet/runtime#90146|
|[366123](https://dev.azure.com/dnceng-public/public/_build/results?buildId=366123)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/366123/logs/648)|dotnet/runtime#90116|
|[362955](https://dev.azure.com/dnceng-public/public/_build/results?buildId=362955)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/362955/logs/1211)|dotnet/runtime#89988|
|[362769](https://dev.azure.com/dnceng-public/public/_build/results?buildId=362769)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/362769/logs/1143)|dotnet/runtime#89977|
|[362227](https://dev.azure.com/dnceng-public/public/_build/results?buildId=362227)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/362227/logs/1102)|dotnet/runtime#89930|
|[361772](https://dev.azure.com/dnceng-public/public/_build/results?buildId=361772)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/361772/logs/1054)|dotnet/runtime#88894|
|[355196](https://dev.azure.com/dnceng-public/public/_build/results?buildId=355196)|dotnet/runtime|Build managed test components|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/355196/logs/1033)|dotnet/runtime#89632|
|[354832](https://dev.azure.com/dnceng-public/public/_build/results?buildId=354832)|dotnet/runtime|Build Tests|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/354832/logs/1294)|dotnet/runtime#88394|
|[354675](https://dev.azure.com/dnceng-public/public/_build/results?buildId=354675)|dotnet/runtime|Build managed test components|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/354675/logs/1023)|dotnet/runtime#89609|
|[354544](https://dev.azure.com/dnceng-public/public/_build/results?buildId=354544)|dotnet/runtime|Build managed test components|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/354544/logs/1172)|dotnet/runtime#89405|
|[352336](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352336)|dotnet/runtime|Build managed test components|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/352336/logs/721)|dotnet/runtime#89493|
|[352201](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352201)|dotnet/runtime|Build managed test components|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/352201/logs/105)||
|[352084](https://dev.azure.com/dnceng-public/public/_build/results?buildId=352084)|dotnet/runtime|Build managed test components|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/352084/logs/567)|dotnet/runtime#89422|
|[351406](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351406)|dotnet/runtime|Build managed test components|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/351406/logs/1136)|dotnet/runtime#89430|
|[351171](https://dev.azure.com/dnceng-public/public/_build/results?buildId=351171)|dotnet/runtime|Build managed test components|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/351171/logs/65)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|5|30|

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=322450
**Error message validated:** `Could not load file or assembly 'Microsoft.CodeAnalysis.NetAnalyzers`
**Result validation: :white_check_mark:** Known issue matched with the provided build.
**Validation performed at:** 6/28/2023 10:10:52 PM UTC

**Comment by ViktorHofer** [comment] 2023-04-18 17:53
cc @jkoritzinsky

**Comment by markples** [comment] 2023-06-05 17:29
@ViktorHofer @jkoritzinsky Do you have any ideas on what is causing this (or why it intermittently hits - it's rare enough that it almost seems like a new issue each time it comes up)?

**Comment by jkoritzinsky** [comment] 2023-06-05 18:06
My guess is some weirdness around how we do restore in the src/tests projects is causing issues. Once we reduce the number of project files in the src/tests tree (the next phase of the test consolidation), we can remove our custom "restore" infrastructure and do something more normal.

**Comment by carlossanlop** [comment] 2023-08-23 19:52
This is affecting the release/8.0 branch too. The milestone has been set to 9.0.0.

**Comment by carlossanlop** [comment] 2023-08-23 21:35
Duplicate of #85082

**Closed by carlossanlop** 2023-08-23 21:35 UTC
Labels: blocking-clean-ci, area-Infrastructure, Known Build Error
