### ISSUE TITLE
Windows service stops with `KERNELBASE.dll` fault after user-handled exception when using outdated packages in .NET 7

### ISSUE THREAD

**Issue by JeremyMahieu** [dotnet/runtime#91447] opened 2023-08-30 09:47 UTC
### Description
I have a console application running as a windows service on a Windows Server 2019 machine. After updating from .NET 6 to .NET 7 I have infrequent crashes of this service with two entries in the Windows Event Log.

It doesn't make sense that this would throw as user unhandled beucase it's called in a try..catch block furthermore, I did not change code of these areas, only updated .NET and related packages.
I understand the exception that's being thrown and I can safely ignore it.

### Event log
![image](https://github.com/dotnet/core/assets/23409814/24064d99-8021-4ebf-96aa-d916dc180507)

```
Application: [Redacted].Processing.exe
CoreCLR Version: 7.0.1023.36312
.NET Version: 7.0.10
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: The requested operation requires an element of type 'Number', but the target element has type 'False'.
   at System.Text.Json.ThrowHelper.ThrowJsonElementWrongTypeException(JsonTokenType expectedType, JsonTokenType actualType)
   at System.Text.Json.JsonDocument.TryGetValue(Int32 index, Double& value)
   at System.Text.Json.JsonElement.GetDouble()
   at [Redacted].Common.SharedLogic.OPC.TagManager.ReadTag[T](String key) in [Redacted].Common\SharedLogic\OPC\TagManager.cs:line 36
   at [Redacted].Processing.Logic.[Redacted].Start(Int32 pos, TagManager tagManager, TagMessagingClient tagService, [Redacted], LogMessageService logMessagingClient, [Redacted]) in [Redacted].cs:line 203
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```
```
Faulting application name: [Redacted].Processing.exe, version: 1.0.0.0, time stamp: 0x6492041a
Faulting module name: KERNELBASE.dll, version: 10.0.17763.4131, time stamp: 0xa6224d08
Exception code: 0xe0434352
Fault offset: 0x00000000000349b9
Faulting process id: 0x1544
Faulting application start time: 0x01d9da45080ee20b
Faulting application path: [Redacted].Processing.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 7dee3000-2393-492d-ac58-7ab00ceac8ed
Faulting package full name: 
Faulting package-relative application ID: 
```
### Code
```csharp
                        try
                        {
                            if (!Instances.ContainsKey(66))
                            {
                                Instances.Add(66, new POS211_65());
                            }
                            ((POS211_65)Instances[66]).Start(66, tagManager, tagService, dbContext, logMessagingClient, unitManipuationMessagingClient);
                        }
                        catch { } // This catch should catch all the Exceptions but but it's not.
```
```csharp
        public T ReadTag<T>(string key)
        {
            if (Tags.ContainsKey(key))
            {
                Tag tag = Tags[key];
                if (tag.Value == null)
                {
                    return default(T);
                }
(...)
                if (typeof(T) == typeof(Int64) && ( tag.Value.GetType() == typeof(JsonElement) ))
                {
                    return (T)(object)(Int64)((JsonElement)tag.Value).GetDouble(); <EXCEPTION HERE>
                }
(...)
                return (T)tag.Value;
            }
            else
            {
                Console.WriteLine($"Tag '{key}' not found, cannot read.");
                throw new ApplicationException("Tag not found, cannot read.");
            }
        }
 ```
 ### Versions
These are the installed runtimes. I basically installed the hosting bundle for these versions.
 ```
 C:\Users\redacted>dotnet --list-runtimes
Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
```
C:\Users\redacted>systeminfo | findstr /B /C:"OS Name" /B /C:"OS Version"
OS Name:                   Microsoft Windows Server 2019 Standard
OS Version:                10.0.17763 N/A Build 17763
```

**Comment by danmoseley** [comment] 2023-09-01 04:53
What happens if you step using a debugger as the exception is thrown?
What happens if you put logging in the catch, is it hit?

**Comment by tarekgh** [comment] 2023-09-01 16:13
@JeremyMahieu although it is not clear what exactly caused that but there were breaking changes in .NET 7.0. One interesting [breaking change](https://learn.microsoft.com/en-us/dotnet/core/compatibility/globalization/7.0/icu-globalization-api) is .NET 7.0 started to use ICU library for globalization support on Windows Server 2019. Could you try enable [NLS](https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu#use-nls-instead-of-icu) legacy globalization mode and tell if this make any change?

**Comment by JeremyMahieu** [comment] 2023-09-01 16:27
@danmoseley I'll try your suggestion, might take while.
@tarekgh If I understand correctly this is working on why the `InvalidOperationException` is thrown? It might be that this error has always been present, but just now it causes the process to crash. I'm more concerned about kernelbase.dll thing, or do you think this ICU library could be related to that? Either way I will try it but as it happens not very often it will take a while. Thanks.

**Comment by tarekgh** [comment] 2023-09-01 16:35
> I'm more concerned about kernelbase.dll

From your description, the only change is your upgrade from .NET 6.0 to .NET 7.0. I doubt anything specific to `kernelbase.dll` more than something else like .NET interop with Windows modules. This is unknown yet. My suggestion was mostly something you can quickly try to see if it has any effect on the behavior you are seeing. 

Do you have a small repro we can look at?

**Comment by JeremyMahieu** [comment] 2023-09-01 17:55
I've managed to replicate it, please find the minimal repo here.
Although in doing so, the solution seems painfully obvious. I forgot to update the packages in this repo.
```
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="5.0.6" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="5.0.1" />
```
Was able to generate the same `KERNELBASE.dll` on a normal Windows 11 install.

https://github.com/JeremyMahieu/KernelbaseExceptionEscape

**Comment by tarekgh** [comment] 2023-09-01 22:20
I tried to run your sample without any changes on Windows 11 and I couldn't reproduce the issue. Looks there is something missing here,

![image](https://github.com/dotnet/runtime/assets/10833894/8c1b55de-1468-403b-89a3-d2b054e373a0)

**Comment by JeremyMahieu** [comment] 2023-09-02 06:20
@tarekgh, you have to run it as a service, see instructions in the `README.md`

**Comment by ericstj** [comment] 2023-09-08 15:28
>     <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="5.0.6" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="5.0.1" />

Both of these versions don't exist.  Building this project results in warnings and you end up using 6.0.0.

I tried out the repro here and couldn't reproduce the exception in the event log after merely starting the service.  The service runs fine for me.

My best guess at what you're hitting from the problem you describe (exception handler not working) is https://github.com/dotnet/runtime/issues/83093 which can make it so that on system (or container) shutdown the CLR tears down the process while the service is still running code.  This is due to a bug in the CoreCLR shutdown handler that doesn't permit the service's stop handler to run.  Could you take a look at your repro and see if this is the case - are the uncaught exceptions happening when the service is stopping?

You may find that this is less common after taking updates to the package because we also [fixed a race condition](https://github.com/dotnet/runtime/issues/62579) in service stop which would not synchronize stopping user code on a background thread when exiting the process which might also produce the problem.

Both of these might manifest more often after moving to .NET 7 since 

Let me know if these sound likely or if the unhandled exceptions are not correlated to a service stop.  If that's the case then we'd need to see a repro using supported package versions / framework version (since if we made any fix it would need to be to a supported version) and hopefully you can tease out what steps might be missing to get a more reliable repro.

Thanks!

**Comment by JeremyMahieu** [comment] 2023-09-09 21:01
> Both of these versions don't exist. Building this project results in warnings and you end up using 6.0.0.

You're right the first doesn't doesn't exist. the second one [exists](https://www.nuget.org/packages/Microsoft.Extensions.Hosting.WindowsServices/5.0.1) but is deprecated.
I managed to get the same problem with still supported packages in the updated repo.

```
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="3.1.32" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="3.1.32" />
```

> Could you take a look at your repro and see if this is the case - are the uncaught exceptions happening when the service is stopping?

You're right the exception actually happens when stopping the service.

Thanks for all the info, you were spot on. For me personally it was already solved by updating the packages to 7.

**Closed** 2023-09-09 21:36 UTC
Labels: area-Extensions-Hosting, needs-further-triage
