### ISSUE TITLE
Unexpected Linq (Except Method) Behaviour

### ISSUE THREAD

**Issue by AdemCatamak** [dotnet/runtime#66760] opened 2022-03-15 20:35 UTC
### Description

When operating with a list of value objects (int, string, record, etc.), after using the Except method, resulting list contains distinct values.

Test Case:

- Create list of int which are not unique : 1, 2, 2, 3, 4
- Give an empty list to Except method
- Expected result is the initial list. However resulting list only contains distinct values : 1, 2, 3, 4

```
[Fact]
public void IntegerToListTest()
{
    IReadOnlyCollection<int> expectedCollection = new List<int> { 1, 2, 2, 3, 4 };

    var emptyList = new List<int>();

    List<int> actualList = expectedCollection.Except(emptyList)
                                              .ToList();

    var collectionStr = string.Join(" | ", actualList);
    _output.WriteLine($"int list -> {collectionStr}");
    // int list -> 1 | 2 | 3 | 4

    Assert.Equal(expectedCollection.Count, actualList.Count);
}
```

### Configuration

* Which version of .NET is the code running on? => .Net 6
* What OS and version, and for Linux, what distro? => Mac OS 12.2.1
* What is the architecture (x64, x86, ARM, ARM64)? => x64

### Other information

When I use the OrderBy and ToList methods one after the other, the result is created without removing the duplicate elements from the list. Therefore, I suspect the issue is in the `Except` method. 

Kindly, refer to my unit-tests below:

https://github.com/AdemCatamak/LinqTest
https://github.com/AdemCatamak/LinqTest/blob/main/LinqTest/ExceptAndToListTest.cs

**Comment by Clockwork-Muse** [comment] 2022-03-17 15:30
Duplicate of #44516

**Closed** 2022-03-18 07:50 UTC
Labels: area-System.Linq, untriaged
