### ISSUE TITLE
Test failure GC\\Scenarios\\ServerModel\\servermodel\\servermodel.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#63908] opened 2022-01-18 01:01 UTC
Run: [runtime 20220117.81](https://dev.azure.com/dnceng/public/_build/results?buildId=1557304&view=ms.vss-test-web.build-test-results-tab&runId=43892830&paneView=debug&resultId=102907)

Failed test:
```
CoreCLR windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open

- GC\\Scenarios\\ServerModel\\servermodel\\servermodel.cmd

```
**Error message:**
```
Return code:      1
Raw output file:      D:\h\w\AD0A094D\w\A6B50957\uploads\Reports\GC.Scenarios\ServerModel\servermodel\servermodel.output.txt
Raw output:
BEGIN EXECUTION
"D:\h\w\AD0A094D\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  servermodel.dll /numrequests:100
Using 1663481965 as random seed
took 512 iteration to reach steady state
499 reqs/sec
538 reqs/sec
551 reqs/sec
Expected: 100
Actual: -2147483645
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\AD0A094D\p
D:\h\w\AD0A094D\w\A6B50957\e\GC\Scenarios\ServerModel\servermodel\servermodel.cmd
Expected: True
Actual:   False


Stack trace
   at GC_Scenarios._ServerModel_servermodel_servermodel_._ServerModel_servermodel_servermodel_cmd()
```

**Comment by VincentBu** [comment] 2022-03-16 01:14
Failed again in: [runtime-coreclr jitstress 20220314.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1663666&view=ms.vss-test-web.build-test-results-tab&runId=45764366&resultId=108658&paneView=debug)

Failed test:
```
CoreCLR windows arm64 Checked jitstress2 @ Windows.10.Arm64v8.Open

- GC\\Scenarios\\ServerModel\\servermodel\\servermodel.cmd

```
**Error message:**
```
Assert failure(PID 1740 [0x000006cc], Thread: 6672 [0x1a10]): global_regions_to_decommit[kind].get_num_free_regions() == num_regions_to_decommit_before + (size_t)num_regions_to_decommit[kind]

CORECLR! WKS::gc_heap::distribute_free_regions + 0x5E0 (0x00007ff83cfbf048) CORECLR! WKS::gc_heap::gc1 + 0xBB0 (0x00007ff83cfc3820)
CORECLR! WKS::gc_heap::garbage_collect + 0x6C0 (0x00007ff83cfc2c30) CORECLR! WKS::GCHeap::GarbageCollectGeneration + 0x584 (0x00007ff83cfab4dc)
CORECLR! WKS::gc_heap::trigger_gc_for_alloc + 0x94 (0x00007ff83cfdc7c4) CORECLR! WKS::gc_heap::try_allocate_more_space + 0x3E8 (0x00007ff83cfdcd98)
CORECLR! WKS::GCHeap::Alloc + 0x144 (0x00007ff83cfa9ac4) CORECLR! Alloc + 0x164 (0x00007ff83ce062d4)
CORECLR! AllocateSzArray + 0x1B0 (0x00007ff83ce074e8) CORECLR! JIT_NewArr1 + 0x16C (0x00007ff83ce2dcac)
File: D:\a_work\1\s\src\coreclr\gc\gc.cpp Line: 12432
Image: D:\h\w\B09E09BE\p\corerun.exe

Return code:      1
Raw output file:      D:\h\w\B09E09BE\w\ABC20997\uploads\Reports\GC.Scenarios\ServerModel\servermodel\servermodel.output.txt
Raw output:
BEGIN EXECUTION
"D:\h\w\B09E09BE\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  servermodel.dll /numrequests:100
Using 94132460 as random seed
took 804 iteration to reach steady state
320 reqs/sec
327 reqs/sec
316 reqs/sec
352 reqs/sec
381 reqs/sec
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\B09E09BE\p
D:\h\w\B09E09BE\w\ABC20997\e\GC\Scenarios\ServerModel\servermodel\servermodel.cmd
Expected: True
Actual:   False


Stack trace
   at GC_Scenarios._ServerModel_servermodel_servermodel_._ServerModel_servermodel_servermodel_cmd()
```

**Comment by mangod9** [comment] 2022-03-16 01:45
Dupe of https://github.com/dotnet/runtime/issues/66601, should be fixed in today's build

**Closed by mangod9** 2022-03-16 01:45 UTC
Labels: arch-arm64, os-windows, area-GC-coreclr, untriaged
