### ISSUE TITLE
Calling interface method of value type cause boxing

### ISSUE THREAD

**Issue by kefyru** [dotnet/runtime#95202] opened 2023-11-24 11:24 UTC
### Description

```
Console.WriteLine(GC.CollectionCount(0)); // --> 0
for (var i = 0; i < 100000000; i++) Do(i); 
Console.WriteLine(GC.CollectionCount(0)); // --> 40..50

void Do<T>(T value) 
{
  Span<char> span = stackalloc char[16];
  ((ISpanFormattable)value).TryFormat(span, out _, default, default);
}
```
This code should not box value, but it does.
net7.0 Apple silicon

### Reproduction Steps

1. create empty  console app
2. paste this code
3. run

### Expected behavior

value should not be boxed

### Actual behavior

value boxes

### Configuration

<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

</Project>

### Other information

Macbook pro M1, Rider 2023.2.3

**Comment by KeterSCP** [comment] 2023-11-24 12:05
Allocations that you observe come from tier-0 (unoptimized) code.
If you run a warmup first (so the method would be jitted to tier-1) before doing actual measurements, you will see that allocations number does not change:

```csharp
for (var i = 0; i < 100000000; i++) Do(i); // Warmup
Console.WriteLine(GC.CollectionCount(0)); // --> 0
for (var i = 0; i < 100000000; i++) Do(i);
Console.WriteLine(GC.CollectionCount(0)); // --> 40..50

void Do<T>(T value)
{
    Span<char> span = stackalloc char[16];
    ((ISpanFormattable)value).TryFormat(span, out _, default, default);
}
```

I would suggest using [BenchmarkDotNet](https://benchmarkdotnet.org/) which does all the necessary job (warmup, overhead calculation, etc) behind the scenes for you.

**Comment by ovska** [comment] 2023-11-24 12:07
Are you running in RELEASE or DEBUG mode? The minimal allocations that are still present in RELEASE mode are also present when you use `TryFormat` on an `int` directly, without it being through a generic method and cast, so the interface method isn't your culprit.

**Comment by EgorBo** [comment] 2023-11-24 12:45
It seems to be a duplicate of https://github.com/dotnet/runtime/issues/90965

**Comment by JulieLeeMSFT** [comment] 2023-12-08 22:52
Hi @kefyru, closing this as a duplicate. Please feel free to reopen if you belive it is not.
 
> It seems to be a duplicate of #90965

**Closed by JulieLeeMSFT** 2023-12-08 22:52 UTC
Labels: area-CodeGen-coreclr, untriaged
