### ISSUE TITLE
InMemoryDirectoryInfo constructor not recognizing root

### ISSUE THREAD

**Issue by AnakinRaW** [dotnet/runtime#93107] opened 2023-10-06 10:21 UTC
### Description

Hi, 

so unless i'm totally overseeing something here, the behavior of the `InMemoryDirectoryInfo` constructor irritates me a lot. 
It seems that the parameter `rootDir` is not acutally used to resolve relative path. 

The documentation however states this: 

> param files: Collection of file names. If relative paths `rootDir` will be prepended to the paths.</param>

### Reproduction Steps

See the following code: 

```csharp
var files = new List<string>{"Test.txt", "New/../Test.txt", "new/test.txt"};
var fs = new InMemoryDirectoryInfo("x:/", files);
var i = fs.EnumerateFileSystemInfos().ToList();
```

### Expected behavior

expected result of `i` is a list containing 3 items of the following file names:

```
{"x:/test.txt", "x:/test.txt", "x:/new/test.txt"}
```

### Actual behavior

The actual result is empty. 
In the debugger you can also see that the relative paths have been resolved to the applications current directory (so something like c:/dev/app/bin/debug/test.txt)

**Comment by krwq** [comment] 2023-10-06 12:19
I think the problem is that we use GetFullPath here:
https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.FileSystemGlobbing/src/InMemoryDirectoryInfo.cs#L53

I think this also looks like a duplicate of https://github.com/dotnet/runtime/issues/50648

Looking at the tests, this somewhat looks like scenario similar to yours: https://github.com/dotnet/runtime/blob/52806bc157decf345005249c9ea7969c8b9e7e1b/src/libraries/Microsoft.Extensions.FileSystemGlobbing/tests/FunctionalTests.cs#L848

Would you be interested in creating a PR with couple of tests with a fix?

**Comment by krwq** [comment] 2023-10-06 12:24
I'm closing this as dup of https://github.com/dotnet/runtime/issues/50648

**Closed by krwq** 2023-10-06 12:24 UTC
Labels: untriaged, area-Extensions-FileSystem
