### ISSUE TITLE
CancellationTokenSource.CancelAfter(TimeSpan delay) throws ArgumentOutOfRangeException for valid TimeSpan values

### ISSUE THREAD

**Issue by arunjvs** [dotnet/runtime#68841] opened 2022-05-03 22:53 UTC
### Description

**On .NET Framework:**

`System.Threading.CancellationTokenSource.CancelAfter(TimeSpan delay)` throws `System.ArgumentOutOfRangeException` for any `TimeSpan delay` parameter with `delay.TotalMilliseconds > Int32.MaxValue` but `delay.TotalMilliseconds <= TimeSpan.MaxValue.TotalMilliseconds` (which evalutes to `Int64.MaxValue/10000`).

https://github.com/microsoft/referencesource/blob/5697c29004a34d80acdaf5742d7e699022c64ecd/mscorlib/system/threading/CancellationTokenSource.cs#L425-L434

**On .NET Core:**

There is a slightly larger upper bound of `Timer.MaxSupportedTimeout` which evaluates to `uint MaxSupportedTimeout = 0xfffffffe` but still way below `TimeSpan.MaxValue.TotalMilliseconds` (which evalutes to `Int64.MaxValue/10000`).

https://github.com/dotnet/runtime/blob/4cd4cff89cce3d48b70fdb3bfd604d3982d5e808/src/libraries/System.Private.CoreLib/src/System/Threading/CancellationTokenSource.cs#L273-L282

Not only is rejecting a valid TimeSpan argument confusing, the documentation has language errors too:

https://docs.microsoft.com/en-us/dotnet/api/system.threading.cancellationtokensource.cancelafter?view=net-6.0#system-threading-cancellationtokensource-cancelafter(system-timespan)

The TimeSpan version in the documentation doesn't make sense in the `ArgumentOutOfRangeException` clause.

### Reproduction Steps

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise>csi
Microsoft (R) Visual C# Interactive Compiler version 3.11.0-4.22108.8 ()
Copyright (C) Microsoft Corporation. All rights reserved.

Type "#help" for more information.
> TimeSpan.MaxValue.TotalMilliseconds
922337203685477
> Int32.MaxValue
2147483647
> (new System.Threading.CancellationTokenSource()).CancelAfter(TimeSpan.FromMilliseconds(Int32.MaxValue))
```
**Below Fails for valid TimeSpan**
```
> (new System.Threading.CancellationTokenSource()).CancelAfter(TimeSpan.FromMilliseconds(Int32.MaxValue + 1L))
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: delay
  + System.Threading.CancellationTokenSource.CancelAfter(System.TimeSpan)
```
**Below Fails for valid TimeSpan**
```
> (new System.Threading.CancellationTokenSource()).CancelAfter(TimeSpan.MaxValue)
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: delay
  + System.Threading.CancellationTokenSource.CancelAfter(System.TimeSpan)
```

### Expected behavior

`(new System.Threading.CancellationTokenSource()).CancelAfter(TimeSpan.MaxValue)` should succeed.

### Actual behavior

`(new System.Threading.CancellationTokenSource()).CancelAfter(TimeSpan.MaxValue)` throws `System.ArgumentOutOfRangeException`.

### Regression?

No

### Known Workarounds

None

**Comment by stephentoub** [comment] 2022-05-04 00:17
This is by design.  It uses System.Threading.Timer and supports the range allowed by Timer.  The range was a bit more constrained than necessary in .NET Framework and it was fixed in .NET 6 to be the full range supported by Timer.
https://github.com/dotnet/runtime/pull/43708

**Closed by stephentoub** 2022-05-04 00:17 UTC
Labels: area-System.Threading, untriaged

**Comment by arunjvs** [comment] 2022-05-04 00:23
Sure, can we keep this open then until the doc is fixed in the PR above, or should this be moved to docs issues?

**Comment by stephentoub** [comment] 2022-05-04 00:28
We don't usually track dotnet/dotnet-api-docs improvements with issues in dotnet/runtime, and I don't think an issue is even needed to track such an improvement; PRs are welcome for minor doc improvements without corresponding issues.  But if you really want an issue, feel free to create one in dotnet/dotnet-api-docs.  Thanks.
