### ISSUE TITLE
Provide a runtime package through the store

### ISSUE THREAD

**Issue by TravisEz13** [dotnet/runtime#86808] opened 2023-05-26 17:57 UTC
### Summary

Provide a runtime package through the store so that other store packages can be FDD

### Background

PowerShell should move to Framework Dependent Deployments, so that .NET runtime issues are automatically serviced and to reduce the package size of PowerShell.  Deploying via the store and MSIX seems like where we are encouraged to move this to for Windows.  So, we need the .NET Runtime to support this scenario.

**Comment by reflectronic** [comment] 2023-05-27 01:24
See also: https://github.com/dotnet/runtime/issues/51574, https://github.com/dotnet/installer/issues/7725

**Comment by jkotas** [comment] 2023-05-27 01:27
Duplicate of https://github.com/dotnet/runtime/issues/51574

**Closed by jkotas** 2023-05-27 01:27 UTC
Labels: area-Setup, untriaged
