### ISSUE TITLE
string.Create should accept a Span as state

### ISSUE THREAD

**Issue by MithrilMan** [dotnet/runtime#1641] opened 2020-01-12 01:52 UTC
I've a method like this:
`public static string ToHexString(ReadOnlySpan<byte> rawData, bool reverse = false)`

that internally need to create a string.

The problem is that `string.Create` doesn't allow me to pass rawData as the `state` argument (source of my string creation `SpanAction`) because `ReadOnlySpan `(ref struct) must not be a generic type argument.

This forces me to pass rawData as a byte array, thus creating a copy of it while in my scenario I would save an allocation by using directly the rawData.

Could you add a way to create a string like in the scenario above, without requiring that additional allocation?

Would be nice to have a way to create a string and manipulate it (like string.Create(length) and then having a span on that string to alter the chars).
The reason such method doesn't exists is because of design decision, to not abuse of string manipulation being them, by definition, immutable?

Any alternative way to do what I need?
I tried to create a buffer (char array) and alter it but the problem is that doesn't exist a way that return a string out of a char array using the same memory and trying to use `MemoryMarshal.TryGetString` return false in this scenario. I think there is room for improvement in string management (memory wise), but if there is already a way to save some allocation, please let me know (without using unsafe code that requires me to compile in unsafe mode)

thanks

**Comment by jkotas** [comment] 2020-01-12 02:14
Duplicate of https://github.com/dotnet/corefx/issues/39268

**Closed by jkotas** 2020-01-12 02:14 UTC
Labels: area-System.Runtime, untriaged
