### ISSUE TITLE
Test failure Loader\\classloader\\TypeGeneratorTests\\TypeGeneratorTest942\\Generated942\\Generated942.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#61391] opened 2021-11-10 01:25 UTC
Run: [runtime-coreclr outerloop 20211109.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1461153&view=ms.vss-test-web.build-test-results-tab&runId=41988354&resultId=106861&paneView=debug)

Failed test:
```
R2R-CG2 windows arm Checked @ Windows.10.Arm64v8.Open

- Loader\\classloader\\TypeGeneratorTests\\TypeGeneratorTest942\\Generated942\\Generated942.cmd

```
**Error message:**
```
Could Not Find D:\h\w\B0F30967\w\B28F0983\e\Loader\classloader\TypeGeneratorTests\TypeGeneratorTest942\Generated942\IL-CG2\composite-r2r.dll
Could Not Find D:\h\w\B0F30967\w\B28F0983\e\Loader\classloader\TypeGeneratorTests\TypeGeneratorTest942\Generated942\Generated942.dll.rsp
Could Not Find D:\h\w\B0F30967\w\B28F0983\e\Loader\classloader\TypeGeneratorTests\TypeGeneratorTest942\Generated942\TestFramework.dll.rsp
Fatal error. Internal CLR error. (0x80131506)
at System.SZArrayHelper.GetEnumerator[Internal.JitInterface.CorJitFlag, ILCompiler.ReadyToRun, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null]
at Internal.JitInterface.CorInfoImpl.getJitFlags(Internal.JitInterface.CORJIT_FLAGS ByRef, UInt32)
at Internal.JitInterface.CorInfoImpl._getJitFlags(IntPtr, IntPtr*, Internal.JitInterface.CORJIT_FLAGS*, UInt32)
at Internal.JitInterface.CorInfoImpl.JitCompileMethod(IntPtr ByRef, IntPtr, IntPtr, IntPtr, Internal.JitInterface.CORINFO_METHOD_INFO ByRef, UInt32, IntPtr ByRef, UInt32 ByRef)
at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(ILCompiler.DependencyAnalysis.IMethodNode, Internal.IL.MethodIL)
at Internal.JitInterface.CorInfoImpl.CompileMethod(ILCompiler.DependencyAnalysis.ReadyToRun.MethodWithGCInfo, ILCompiler.Logger)
at ILCompiler.ReadyToRunCodegenCompilation.<ComputeDependencyNodeDependencies>b__35_0(ILCompiler.DependencyAnalysisFramework.DependencyNodeCore1<ILCompiler.DependencyAnalysis.NodeFactory>) at System.Threading.Tasks.Parallel+<>c__DisplayClass33_02[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForEachWorker>b__0(Int32)
at System.Threading.Tasks.Parallel+<>c__DisplayClass19_0`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef, Int32, Boolean ByRef)
at System.Threading.Tasks.TaskReplicator+Replica.Execute()
at System.Threading.Tasks.TaskReplicator+Replica+<>c.<.ctor>b__4_0(System.Object)
at System.Threading.Tasks.Task.InnerInvoke()
at System.Threading.Tasks.Task+<>c.<.cctor>b__271_0(System.Object)
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
at System.Threading.Thread.StartCallback()

Return code:      1
Raw output file:      D:\h\w\B0F30967\w\B28F0983\uploads\Reports\Loader.classloader\TypeGeneratorTests\TypeGeneratorTest942\Generated942\Generated942.output.txt
Raw output:
BEGIN EXECUTION
Generated942.dll
TestFramework.dll
2 file(s) copied.
Response file: D:\h\w\B0F30967\w\B28F0983\e\Loader\classloader\TypeGeneratorTests\TypeGeneratorTest942\Generated942\Generated942.dll.rsp
D:\h\w\B0F30967\w\B28F0983\e\Loader\classloader\TypeGeneratorTests\TypeGeneratorTest942\Generated942\IL-CG2\Generated942.dll
-o:D:\h\w\B0F30967\w\B28F0983\e\Loader\classloader\TypeGeneratorTests\TypeGeneratorTest942\Generated942\Generated942.dll
--targetarch:arm
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\B0F30967\p\System..dll
-r:D:\h\w\B0F30967\p\Microsoft..dll
-r:D:\h\w\B0F30967\p\mscorlib.dll
-r:D:\h\w\B0F30967\p\netstandard.dll
-O
" "dotnet" "D:\h\w\B0F30967\p\crossgen2\crossgen2.dll" @"D:\h\w\B0F30967\w\B28F0983\e\Loader\classloader\TypeGeneratorTests\TypeGeneratorTest942\Generated942\Generated942.dll.rsp"   -r:D:\h\w\B0F30967\w\B28F0983\e\Loader\classloader\TypeGenerator


Stack trace
   at Loader_classloader._TypeGeneratorTests_TypeGeneratorTest942_Generated942_Generated942_._TypeGeneratorTests_TypeGeneratorTest942_Generated942_Generated942_cmd()
```

**Comment by trylek** [comment] 2022-04-04 20:39
Closing as duplicate of: https://github.com/dotnet/runtime/issues/65170

**Closed** 2022-07-06 17:50 UTC
Labels: os-windows, area-crossgen2-coreclr, untriaged
