### ISSUE TITLE
[Win11] [Bug] [ConcurrentBag regression in .Net 9] System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

### ISSUE THREAD

**Issue by drweb86** [dotnet/runtime#110355] opened 2024-11-29 00:50 UTC
**Steps:**

1. Create new .Net 9 project and put code in Visual Studio 2022

```
using System.Collections.Concurrent;

var breakingBadHoleInTheBag = new ConcurrentBag<ConcurrentBagItem>();

int tries = 500000;
while (tries-- > 0)
{
    breakingBadHoleInTheBag.SingleOrDefault(x => x == (object)breakingBadHoleInTheBag);
    breakingBadHoleInTheBag.Add(new ConcurrentBagItem());
}

class ConcurrentBagItem { }
```
2. Execute with or without debugger

**Actual result:**

```
An unhandled exception of type 'System.AccessViolationException' occurred in System.Collections.Concurrent.dll
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
```

**Expected result:**

Works without error, as in .Net 9.

Please introduce ConcurrentBag - from .Net 8 because uinstable work in .Net 9 breaks my app

**Comment by stephentoub** [comment] 2024-12-04 10:49
It's very unlikely this is actually related to ConcurrentBag. It's more likely some code in your app is resulting in corruption that then appears as an AV in other code, in this case in CB. Without a repro or crash dump, though, we can't investigate.

**Comment by drweb86** [comment] 2024-12-04 14:55
Ill try to create repro then

ср, 4 дек. 2024 г., 13:49 Stephen Toub ***@***.***>:

**Comment by drweb86** [comment] 2024-12-05 22:36
Here's the reproduction sample

```
// See https://aka.ms/new-console-template for more information
using System.Collections.Concurrent;
using System.IO;
using System.Threading.Tasks;

Console.WriteLine("Hello, World!");

var concurrentBag = new ConcurrentBag<ConcurrentBagItem>();

var workerThread = new Thread(() =>
{
    int tries = 500000;
    while (tries-- > 0)
    {
        var testGuid = Guid.NewGuid();
        var item = concurrentBag.SingleOrDefault(x => x.Test == testGuid);
        if (item == null)
            concurrentBag.Add(new ConcurrentBagItem());
    }
});
workerThread.Start();
workerThread.Join();

class ConcurrentBagItem
{
    public Guid Test = Guid.NewGuid();
}
```

Build for .Net 9 and run => Access Violation,
Build for .Net 8 and run => No error.

Please return .Net 8 implementation.

**Comment by stephentoub** [comment] 2024-12-06 04:42
Thanks for the repro.

This is not about the ConcurrentBag implementation.

I suspect this may be the same as the issue fixed by https://github.com/dotnet/runtime/pull/109074. If you add `<CETCompat>false</CETCompat>` into a PropertyGroup in your csproj, does the problem go away?

**Comment by drweb86** [comment] 2024-12-06 11:55
@stephentoub ,

Adding
```
<CETCompat>false</CETCompat>
```
worked.

But guys, seriously, we're in the dark times, when its needed to modify csproj config to make ConcurrentBag work.

**Comment by stephentoub** [comment] 2024-12-06 13:17
> But guys, seriously, we're in the dark times, when its needed to modify csproj config to make ConcurrentBag work.

Again, this has nothing to do with ConcurrentBag. It is a runtime bug to do with Intel's CET security mechanism, it's already been fixed in main with https://github.com/dotnet/runtime/pull/109074 and it's being fixed in 9.0 with https://github.com/dotnet/runtime/pull/109548 (cc: @janvorli, @jeffschwMSFT). I mentioned the csproj property to both confirm this is the same problem and to give you a temporary workaround.

**Comment by stephentoub** [comment] 2024-12-06 13:21
Closing as a duplicate of #109074. Thanks for reporting.

**Closed by stephentoub** 2024-12-06 13:21 UTC
Labels: area-System.Collections, needs-further-triage

**Comment by drweb86** [comment] 2024-12-06 15:52
@stephentoub Thanks!
