### ISSUE TITLE
API runtime support for efficient type switch

### ISSUE THREAD

**Issue by gafter** [dotnet/runtime#29002] opened 2019-03-18 22:56 UTC
I'd like the C# compiler to be able to compile a series of type tests, which typically occur in a pattern-matching switch statement, to something more efficient than a sequence of IL type tests, especially when the number of types being tested for is large (https://github.com/dotnet/roslyn/issues/31515).  I originally asked for an IL instruction to do this (https://github.com/dotnet/coreclr/issues/23241), but it was suggested that the library approach could do just as well.  Some kind of custom hashtable is probably ideal.

I developed this prototype as a starting point: https://github.com/gafter/TypeSwitch/blob/master/TypeSwitch/TypeSwitchDispatch.cs

It appears to be faster than a series of type tests when there are more than about 10 types being tested in the switch.  I think an API something like this should go in `System.Runtime.CompilerServices` and hopefully live in System.Runtime/corlib.

[2019-04-29: To be clear, I am willing to contribute the code that appears at https://github.com/gafter/TypeSwitch/blob/master/TypeSwitch/TypeSwitchDispatch.cs to the dotnet foundation, who can release it under whatever license they/we see fit.  The code was originally developed by me. -@gafter]

**Comment by ericstj** [comment] 2020-07-29 16:33
Per @gafter's comment https://github.com/dotnet/runtime/issues/29002#issuecomment-502904329 closing this.  Please reopen if I misunderstood.

**Comment by gafter** [comment] 2020-07-29 17:14
I think you misunderstood. All my comment is saying is that it cannot be implemented outside the runtime because of a couple of special cases that only the runtime knows about.

**Comment by gafter** [comment] 2020-07-29 17:18
This issue track the same request as https://github.com/dotnet/runtime/issues/12260. I believe the current consensus is that it can be done as an API in which the set of types to match are passed as generic type arguments (e.g. the elements of a tuple type).  See https://github.com/gafter/TypeSwitch/blob/master/TypeSwitch/TypeSwitchDispatch.cs for a prototype that does not address the issue mentioned in https://github.com/dotnet/runtime/issues/29002#issuecomment-502904329

**Comment by jkotas** [comment] 2020-07-29 17:20
Duplicate of #12260. Let's have just one issue tracking this feature request.

**Closed by jkotas** 2020-07-29 17:20 UTC
Labels: api-suggestion, area-System.Runtime.CompilerServices
