### ISSUE TITLE
System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests failing on Bitmaps

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#34302] opened 2020-03-30 22:04 UTC
|Build|Kind|Console Log|
|---|---|---|
|[579823](https://dev.azure.com/dnceng/public/_build/results?buildId=579823)|PR https://github.com/dotnet/runtime/pull/34283|[console.log](https://helix.dot.net/api/2019-06-17/jobs/61cee794-d456-49ac-8706-5029b27b4b91/workitems/System.Runtime.Serialization.Formatters.Tests/files/console.0dbfd29c.log)|
|[579750](https://dev.azure.com/dnceng/public/_build/results?buildId=579750)|PR https://github.com/dotnet/runtime/pull/34249|[console.log](https://helix.dot.net/api/2019-06-17/jobs/5de4ecea-f859-4e26-9bd6-3c3aad663855/workitems/System.Runtime.Serialization.Formatters.Tests/files/console.c4b4b786.log)|
|[579797](https://dev.azure.com/dnceng/public/_build/results?buildId=579797)|PR https://github.com/dotnet/runtime/pull/33890|[console.log](https://helix.dot.net/api/2019-06-17/jobs/6e9d3d5c-8d50-485b-94b1-40d1f2b1e96d/workitems/System.Runtime.Serialization.Formatters.Tests/files/console.29f13a09.log)|
|[579787](https://dev.azure.com/dnceng/public/_build/results?buildId=579787)|PR https://github.com/dotnet/runtime/pull/34025|[console.log](https://helix.dot.net/api/2019-06-17/jobs/4864b559-deda-4af0-80ff-b3ed02159b0c/workitems/System.Runtime.Serialization.Formatters.Tests/files/console.f2e3025f.log)|
|[579684](https://dev.azure.com/dnceng/public/_build/results?buildId=579684)|PR https://github.com/dotnet/runtime/pull/32592|[console.log](https://helix.dot.net/api/2019-06-17/jobs/5862ba4c-1e8d-447c-895f-331056b40872/workitems/System.Runtime.Serialization.Formatters.Tests/files/console.c28227d2.log)|
|[579587](https://dev.azure.com/dnceng/public/_build/results?buildId=579587)|PR https://github.com/dotnet/runtime/pull/34225|[console.log](https://helix.dot.net/api/2019-06-17/jobs/bf4f6bd9-bd98-4c80-b7e5-16a925dcaa50/workitems/System.Runtime.Serialization.Formatters.Tests/files/console.8c9dc767.log)|
|[579596](https://dev.azure.com/dnceng/public/_build/results?buildId=579596)|PR https://github.com/dotnet/runtime/pull/34046|[console.log](https://helix.dot.net/api/2019-06-17/jobs/88fc68f3-5501-4697-929b-b7da071ccf8b/workitems/System.Runtime.Serialization.Formatters.Tests/files/console.8f95b447.log)|
|[579675](https://dev.azure.com/dnceng/public/_build/results?buildId=579675)|PR https://github.com/dotnet/runtime/pull/34086|[console.log](https://helix.dot.net/api/2019-06-17/jobs/fe87691b-aef9-4f62-92b8-e24964acdf2d/workitems/System.Runtime.Serialization.Formatters.Tests/files/console.8c519f7a.log)|
|[579375](https://dev.azure.com/dnceng/public/_build/results?buildId=579375)|PR https://github.com/dotnet/runtime/pull/34154|[console.log](https://helix.dot.net/api/2019-06-17/jobs/bcba89ee-95e9-4148-b46f-21d5347872f5/workitems/System.Runtime.Serialization.Formatters.Tests/files/console.3c812404.log)|
|[579629](https://dev.azure.com/dnceng/public/_build/results?buildId=579629)|PR https://github.com/dotnet/runtime/pull/34022|[console.log](https://helix.dot.net/api/2019-06-17/jobs/1c174834-4501-440d-8cea-6380451e5ba0/workitems/System.Runtime.Serialization.Formatters.Tests/files/console.a8d5509a.log)|
|[579589](https://dev.azure.com/dnceng/public/_build/results?buildId=579589)|PR https://github.com/dotnet/runtime/pull/34166|[console.log](https://helix.dot.net/api/2019-06-17/jobs/e9b77e21-c126-43d8-aa9f-2668f56022eb/workitems/System.Runtime.Serialization.Formatters.Tests/files/console.e1c24dbd.log)|
|[579412](https://dev.azure.com/dnceng/public/_build/results?buildId=579412)|PR https://github.com/dotnet/runtime/pull/34263|[console.log](https://helix.dot.net/api/2019-06-17/jobs/c49dfd44-1608-4c10-ac3a-5a48a656e32d/workitems/System.Runtime.Serialization.Formatters.Tests/files/console.9c9a431a.log)|
|[579508](https://dev.azure.com/dnceng/public/_build/results?buildId=579508)|PR https://github.com/dotnet/runtime/pull/34064|[console.log](https://helix.dot.net/api/2019-06-17/jobs/4e5f0bb4-e1d8-4260-872d-0a0ec0c8b1c6/workitems/System.Runtime.Serialization.Formatters.Tests/files/console.95f50a45.log)|
|[579319](https://dev.azure.com/dnceng/public/_build/results?buildId=579319)|PR https://github.com/dotnet/runtime/pull/34261|[console.log](https://helix.dot.net/api/2019-06-17/jobs/0b1a99e3-fd79-46d6-b8ee-5268cc7bb334/workitems/System.Runtime.Serialization.Formatters.Tests/files/console.7290c735.log)|
|[579539](https://dev.azure.com/dnceng/public/_build/results?buildId=579539)|PR https://github.com/dotnet/runtime/pull/34275|[console.log](https://helix.dot.net/api/2019-06-17/jobs/2aecb6c2-4df6-4967-be58-c4818f748ef3/workitems/System.Runtime.Serialization.Formatters.Tests/files/console.98aa007f.log)|
|[579428](https://dev.azure.com/dnceng/public/_build/results?buildId=579428)|PR https://github.com/dotnet/runtime/pull/32592|[console.log](https://helix.dot.net/api/2019-06-17/jobs/4dd5f2eb-f705-4413-8dea-4114cb79857c/workitems/System.Runtime.Serialization.Formatters.Tests/files/console.2231d719.log)|
|[579536](https://dev.azure.com/dnceng/public/_build/results?buildId=579536)|PR https://github.com/dotnet/runtime/pull/34275|[console.log](https://helix.dot.net/api/2019-06-17/jobs/396f3f84-beb3-43b2-aa03-368ad94e3dec/workitems/System.Runtime.Serialization.Formatters.Tests/files/console.ad81c6b7.log)|
|[579294](https://dev.azure.com/dnceng/public/_build/results?buildId=579294)|PR https://github.com/dotnet/runtime/pull/32592|[console.log](https://helix.dot.net/api/2019-06-17/jobs/dcd90afe-5b67-4dba-ac4d-852ff918829c/workitems/System.Runtime.Serialization.Formatters.Tests/files/console.49523f95.log)|

Sample failures:
```
    System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateAgainstBlobs(obj: Bitmap { Flags = 73744, FrameDimensionsList = [7462dc86-6180-4c7e-8e3f-ee7333a7a483], Height = 100, HorizontalResolution = 96, Palette = ColorPalette { Entries = [...], Flags = 0 }, ... }, blobs: [System.Runtime.Serialization.Formatters.Tests.TypeSerializableValue, System.Runtime.Serialization.Formatters.Tests.TypeSerializableValue]) [FAIL]
      Assert.Equal() Failure
      Expected: 73744
      Actual:   77840
      Stack Trace:
        /_/src/libraries/System.Runtime.Serialization.Formatters/tests/EqualityExtensions.cs(1236,0): at System.Runtime.Serialization.Formatters.Tests.EqualityExtensions.IsEqual(Bitmap this, Bitmap other, Boolean isSamePlatform)
    System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.RoundtripManyObjectsInOneStream [FAIL]
      Assert.Equal() Failure
      Expected: 86265190
      Actual:   86266510
      Stack Trace:
        /_/src/libraries/System.Runtime.Serialization.Formatters/tests/EqualityExtensions.cs(1237,0): at System.Runtime.Serialization.Formatters.Tests.EqualityExtensions.IsEqual(Bitmap this, Bitmap other, Boolean isSamePlatform)
    System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateBasicObjectsRoundtrip(obj: Bitmap { Flags = 77840, FrameDimensionsList = [7462dc86-6180-4c7e-8e3f-ee7333a7a483], Height = 100, HorizontalResolution = 86265340, Palette = ColorPalette { Entries = [...], Flags = 0 }, ... }, assemblyFormat: Full, filterLevel: Full, typeFormat: TypesAlways) [FAIL]
      Assert.Equal() Failure
      Expected: 86265340
      Actual:   86266570
      Stack Trace:
        /_/src/libraries/System.Runtime.Serialization.Formatters/tests/EqualityExtensions.cs(1237,0): at System.Runtime.Serialization.Formatters.Tests.EqualityExtensions.IsEqual(Bitmap this, Bitmap other, Boolean isSamePlatform)
    System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateBasicObjectsRoundtrip(obj: Bitmap { Flags = 77840, FrameDimensionsList = [7462dc86-6180-4c7e-8e3f-ee7333a7a483], Height = 100, HorizontalResolution = 86265340, Palette = ColorPalette { Entries = [...], Flags = 0 }, ... }, assemblyFormat: Full, filterLevel: Full, typeFormat: TypesWhenNeeded) [FAIL]
      Assert.Equal() Failure
      Expected: 86265340
      Actual:   86266570
      Stack Trace:
        /_/src/libraries/System.Runtime.Serialization.Formatters/tests/EqualityExtensions.cs(1237,0): at System.Runtime.Serialization.Formatters.Tests.EqualityExtensions.IsEqual(Bitmap this, Bitmap other, Boolean isSamePlatform)
    System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateBasicObjectsRoundtrip(obj: Bitmap { Flags = 77840, FrameDimensionsList = [7462dc86-6180-4c7e-8e3f-ee7333a7a483], Height = 100, HorizontalResolution = 86265340, Palette = ColorPalette { Entries = [...], Flags = 0 }, ... }, assemblyFormat: Full, filterLevel: Full, typeFormat: XsdString) [FAIL]
      Assert.Equal() Failure
      Expected: 86265340
      Actual:   86266570
      Stack Trace:
        /_/src/libraries/System.Runtime.Serialization.Formatters/tests/EqualityExtensions.cs(1237,0): at System.Runtime.Serialization.Formatters.Tests.EqualityExtensions.IsEqual(Bitmap this, Bitmap other, Boolean isSamePlatform)
    System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateBasicObjectsRoundtrip(obj: Bitmap { Flags = 77840, FrameDimensionsList = [7462dc86-6180-4c7e-8e3f-ee7333a7a483], Height = 100, HorizontalResolution = 86265340, Palette = ColorPalette { Entries = [...], Flags = 0 }, ... }, assemblyFormat: Full, filterLevel: Low, typeFormat: TypesAlways) [FAIL]
      Assert.Equal() Failure
      Expected: 86265340
      Actual:   86266570
      Stack Trace:
        /_/src/libraries/System.Runtime.Serialization.Formatters/tests/EqualityExtensions.cs(1237,0): at System.Runtime.Serialization.Formatters.Tests.EqualityExtensions.IsEqual(Bitmap this, Bitmap other, Boolean isSamePlatform)
    System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateBasicObjectsRoundtrip(obj: Bitmap { Flags = 77840, FrameDimensionsList = [7462dc86-6180-4c7e-8e3f-ee7333a7a483], Height = 100, HorizontalResolution = 86265340, Palette = ColorPalette { Entries = [...], Flags = 0 }, ... }, assemblyFormat: Full, filterLevel: Low, typeFormat: TypesWhenNeeded) [FAIL]
      Assert.Equal() Failure
      Expected: 86265340
      Actual:   86266570
      Stack Trace:
        /_/src/libraries/System.Runtime.Serialization.Formatters/tests/EqualityExtensions.cs(1237,0): at System.Runtime.Serialization.Formatters.Tests.EqualityExtensions.IsEqual(Bitmap this, Bitmap other, Boolean isSamePlatform)
    System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateBasicObjectsRoundtrip(obj: Bitmap { Flags = 77840, FrameDimensionsList = [7462dc86-6180-4c7e-8e3f-ee7333a7a483], Height = 100, HorizontalResolution = 86265340, Palette = ColorPalette { Entries = [...], Flags = 0 }, ... }, assemblyFormat: Full, filterLevel: Low, typeFormat: XsdString) [FAIL]
      Assert.Equal() Failure
      Expected: 86265340
      Actual:   86266570
      Stack Trace:
        /_/src/libraries/System.Runtime.Serialization.Formatters/tests/EqualityExtensions.cs(1237,0): at System.Runtime.Serialization.Formatters.Tests.EqualityExtensions.IsEqual(Bitmap this, Bitmap other, Boolean isSamePlatform)
    System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateBasicObjectsRoundtrip(obj: Bitmap { Flags = 77840, FrameDimensionsList = [7462dc86-6180-4c7e-8e3f-ee7333a7a483], Height = 100, HorizontalResolution = 86265340, Palette = ColorPalette { Entries = [...], Flags = 0 }, ... }, assemblyFormat: Simple, filterLevel: Full, typeFormat: TypesAlways) [FAIL]
      Assert.Equal() Failure
      Expected: 86265340
      Actual:   86266570
      Stack Trace:
        /_/src/libraries/System.Runtime.Serialization.Formatters/tests/EqualityExtensions.cs(1237,0): at System.Runtime.Serialization.Formatters.Tests.EqualityExtensions.IsEqual(Bitmap this, Bitmap other, Boolean isSamePlatform)
    System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateBasicObjectsRoundtrip(obj: Bitmap { Flags = 77840, FrameDimensionsList = [7462dc86-6180-4c7e-8e3f-ee7333a7a483], Height = 100, HorizontalResolution = 86265340, Palette = ColorPalette { Entries = [...], Flags = 0 }, ... }, assemblyFormat: Simple, filterLevel: Full, typeFormat: TypesWhenNeeded) [FAIL]
      Assert.Equal() Failure
      Expected: 86265340
      Actual:   86266570
      Stack Trace:
        /_/src/libraries/System.Runtime.Serialization.Formatters/tests/EqualityExtensions.cs(1237,0): at System.Runtime.Serialization.Formatters.Tests.EqualityExtensions.IsEqual(Bitmap this, Bitmap other, Boolean isSamePlatform)
    System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateBasicObjectsRoundtrip(obj: Bitmap { Flags = 77840, FrameDimensionsList = [7462dc86-6180-4c7e-8e3f-ee7333a7a483], Height = 100, HorizontalResolution = 86265340, Palette = ColorPalette { Entries = [...], Flags = 0 }, ... }, assemblyFormat: Simple, filterLevel: Full, typeFormat: XsdString) [FAIL]
      Assert.Equal() Failure
      Expected: 86265340
      Actual:   86266570
      Stack Trace:
        /_/src/libraries/System.Runtime.Serialization.Formatters/tests/EqualityExtensions.cs(1237,0): at System.Runtime.Serialization.Formatters.Tests.EqualityExtensions.IsEqual(Bitmap this, Bitmap other, Boolean isSamePlatform)
    System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateBasicObjectsRoundtrip(obj: Bitmap { Flags = 77840, FrameDimensionsList = [7462dc86-6180-4c7e-8e3f-ee7333a7a483], Height = 100, HorizontalResolution = 86265340, Palette = ColorPalette { Entries = [...], Flags = 0 }, ... }, assemblyFormat: Simple, filterLevel: Low, typeFormat: TypesAlways) [FAIL]
      Assert.Equal() Failure
      Expected: 86265340
      Actual:   86266570
      Stack Trace:
        /_/src/libraries/System.Runtime.Serialization.Formatters/tests/EqualityExtensions.cs(1237,0): at System.Runtime.Serialization.Formatters.Tests.EqualityExtensions.IsEqual(Bitmap this, Bitmap other, Boolean isSamePlatform)
    System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateBasicObjectsRoundtrip(obj: Bitmap { Flags = 77840, FrameDimensionsList = [7462dc86-6180-4c7e-8e3f-ee7333a7a483], Height = 100, HorizontalResolution = 86265340, Palette = ColorPalette { Entries = [...], Flags = 0 }, ... }, assemblyFormat: Simple, filterLevel: Low, typeFormat: TypesWhenNeeded) [FAIL]
      Assert.Equal() Failure
      Expected: 86265340
      Actual:   86266570
      Stack Trace:
        /_/src/libraries/System.Runtime.Serialization.Formatters/tests/EqualityExtensions.cs(1237,0): at System.Runtime.Serialization.Formatters.Tests.EqualityExtensions.IsEqual(Bitmap this, Bitmap other, Boolean isSamePlatform)
    System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateBasicObjectsRoundtrip(obj: Bitmap { Flags = 77840, FrameDimensionsList = [7462dc86-6180-4c7e-8e3f-ee7333a7a483], Height = 100, HorizontalResolution = 86265340, Palette = ColorPalette { Entries = [...], Flags = 0 }, ... }, assemblyFormat: Simple, filterLevel: Low, typeFormat: XsdString) [FAIL]
      Assert.Equal() Failure
      Expected: 86265340
      Actual:   86266570
      Stack Trace:
        /_/src/libraries/System.Runtime.Serialization.Formatters/tests/EqualityExtensions.cs(1237,0): at System.Runtime.Serialization.Formatters.Tests.EqualityExtensions.IsEqual(Bitmap this, Bitmap other, Boolean isSamePlatform)
  Finished:    System.Runtime.Serialization.Formatters.Tests
```

@jkotas do you think this might be related to https://github.com/dotnet/runtime/pull/33967

**Comment by safern** [comment] 2020-03-30 22:18
Dupe of: https://github.com/dotnet/runtime/issues/28553

**Closed by safern** 2020-03-30 22:18 UTC
Labels: area-System.Drawing, blocking-clean-ci, untriaged
