### ISSUE TITLE
Test failure profiler\\unittest\\metadatagetdispenser\\metadatagetdispenser.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#65645] opened 2022-02-21 01:34 UTC
Run: [runtime-coreclr r2r 20220217.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1620230&view=ms.vss-test-web.build-test-results-tab&runId=45054456&paneView=debug&resultId=100632)

Failed test:
```
R2R windows x86 Checked @ Windows.10.Amd64.Open

- profiler\\unittest\\metadatagetdispenser\\metadatagetdispenser.cmd
- profiler\\unittest\\releaseondetach\\releaseondetach.cmd
- profiler\\unittest\\getappdomainstaticaddress\\getappdomainstaticaddress.cmd
- profiler\\unittest\\inlining\\inlining.cmd

R2R windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open

- profiler\\elt\\slowpatheltleave\\slowpatheltleave.cmd
- profiler\\elt\\slowpatheltenter\\slowpatheltenter.cmd

```
**Error message:**
```
Could Not Find C:\h\w\B59C096A\w\9E0508DF\e\profiler\unittest\metadatagetdispenser\IL-CG2\composite-r2r.dll
Could Not Find C:\h\w\B59C096A\w\9E0508DF\e\profiler\unittest\metadatagetdispenser\common.dll.rsp
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'System.Diagnostics.Tracing, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. An attempt was made to load a program with an incorrect format.
File name: 'System.Diagnostics.Tracing, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
at ILCompiler.Program.Run(String[] args)
at ILCompiler.Program.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\B59C096A\w\9E0508DF\uploads\Reports\profiler.unittest\metadatagetdispenser\metadatagetdispenser.output.txt
Raw output:
BEGIN EXECUTION
common.dll
metadatagetdispenser.dll
Profiler.dll
profiler_common.dll
TestLibrary.dll
5 file(s) copied.
Response file: C:\h\w\B59C096A\w\9E0508DF\e\profiler\unittest\metadatagetdispenser\common.dll.rsp
C:\h\w\B59C096A\w\9E0508DF\e\profiler\unittest\metadatagetdispenser\IL-CG2\common.dll
-o:C:\h\w\B59C096A\w\9E0508DF\e\profiler\unittest\metadatagetdispenser\common.dll
--targetarch:x86
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\B59C096A\p\System..dll
-r:C:\h\w\B59C096A\p\Microsoft..dll
-r:C:\h\w\B59C096A\p\mscorlib.dll
-r:C:\h\w\B59C096A\p\netstandard.dll
-O
" "dotnet" "C:\h\w\B59C096A\p\crossgen2\crossgen2.dll" @"C:\h\w\B59C096A\w\9E0508DF\e\profiler\unittest\metadatagetdispenser\common.dll.rsp"   -r:C:\h\w\B59C096A\w\9E0508DF\e\profiler\unittest\metadatagetdispenser\IL-CG2*.dll"
Crossgen2 failed with exitcode - -532462766
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\B59C096A\p
C:\h\w\B59C096A\w\9E0508DF\e\profiler\unittest\metadatagetdispenser\metadatagetdispenser.cmd
Expected: True
Actual:   False


Stack trace
   at profiler_unittest._metadatagetdispenser_metadatagetdispenser_._metadatagetdispenser_metadatagetdispenser_cmd()
```

**Comment by trylek** [comment] 2022-04-04 20:31
Closing as duplicate of: https://github.com/dotnet/runtime/issues/65646

**Closed by trylek** 2022-04-04 20:31 UTC
Labels: arch-x86, os-windows, arch-x64, area-crossgen2-coreclr, untriaged
