### ISSUE TITLE
Test Failure: System.Net.Http.FunctionalTests

### ISSUE THREAD

**Issue by maryamariyan** [dotnet/runtime#40627] opened 2020-08-10 20:17 UTC
Error Message:
```
Assert.Equal() Failure\r\nExpected: HostNotFound\r\nActual:   Unknown
```

Stacktrace
```
   at System.Net.Http.Functional.Tests.SocketsHttpHandler_ConnectionFactoryTest.CustomConnectionFactory_SyncRequest_Fails() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.cs:line 165
   at System.Net.Http.Functional.Tests.SocketsHttpHandler_ConnectionFactoryTest.CustomConnectionFactory_SyncRequest_Fails() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.cs:line 165
--- End of stack trace from previous location ---
```

Seen on PR: https://github.com/dotnet/runtime/pull/40568 `(Libraries Test Run release coreclr Windows_NT x86 Debug)`

**Comment by antonfirsov** [comment] 2020-08-10 20:26
Seems like a duplicate of #40564, which should be already fixed by #40565.

That CI run is 2 days old, @maryamariyan can you re-run after a merge?

**Comment by maryamariyan** [comment] 2020-08-10 20:32
> That CI run is 2 days old, @maryamariyan can you re-run?

Sure. Also rerunning on #40067

**Comment by maryamariyan** [comment] 2020-08-10 21:38
Failed again

**Comment by wfurt** [comment] 2020-08-10 21:53
Arte you sure you have the fix @maryamariyan? @geoffkizer removed the assert so it would be surprising that you would still hit it. If the test fails for other reason, please post full details.

**Comment by maryamariyan** [comment] 2020-08-10 22:01
> Arte you sure you have the fix @maryamariyan? @geoffkizer removed the assert so it would be surprising that you would still hit it. If the test fails for other reason, please post full details.

The PRs I think are not rebased since two days ago, but I reran the failures an hour ago. More info:

https://dev.azure.com/dnceng/public/_build/results?buildId=762500&view=ms.vss-test-web.build-test-results-tab
https://dev.azure.com/dnceng/public/_build/results?buildId=762551&view=ms.vss-test-web.build-test-results-tab

**Comment by wfurt** [comment] 2020-08-10 22:22
It looks like the branch still has the assert. So ether the rebase missed the fix or there is some other problem.

https://github.com/alefranz/runtime/blob/b476d61ad59fe736b8124c5d8c2a4cb96353daae/src/libraries/System.Net.Http/tests/FunctionalTests/SocketsHttpHandlerTest.cs#L165

**Comment by antonfirsov** [comment] 2020-08-13 10:58
@karelz unless anyone confirms that it happened again, I think this was just a weird git artifact, and we can close.

**Comment by karelz** [comment] 2020-08-13 13:37
Closing as it seems to be point in time problem.

**Closed by karelz** 2020-08-13 13:37 UTC
Labels: area-System.Net.Http, needs more info
