### ISSUE TITLE
Question: Is there any API to create a UOH?

### ISSUE THREAD

**Issue by ygc369** [dotnet/runtime#37209] opened 2020-05-31 01:03 UTC
@VSadov @Maoni0 
I know the concept of UOH from [here](https://github.com/dotnet/runtime/issues/33445), but I don't know any API to allocate/destroy a UOH. Is there any API to do this? If not, why to talk about it? 
I think if we can do this, maybe we can create a user-defined arena.

**Comment by Suchiman** [comment] 2020-05-31 02:18
@ygc369 AFAIK this is not about being able to be able to create your own heaps but is a collective term to describe the heaps other than the SOH (Small Object Heap). Previously there was only the SOH and the LOH (Large Object Heap) but with the addition of the POH (Pinned Object Heap) there are now 2 heaps that don't participate in generational behavior. UOH is meant to refer to LOH and POH heaps.

**Comment by GrabYourPitchforks** [comment] 2020-05-31 04:37
Isn't this a dupe of https://github.com/dotnet/runtime/issues/33916?

**Closed** 2020-08-26 13:01 UTC
Labels: area-GC-coreclr, needs more info, question
