### ISSUE TITLE
JsonSerializer doesn't correctly deserialize readonly structs

### ISSUE THREAD

**Issue by palenshus** [dotnet/runtime#94443] opened 2023-11-06 23:38 UTC
### Description

JSON deserialization for readonly structs seems to have some issues. For example, in this case, I would expect `Foo.bar` to be "hello" when deserialized (as is the case for Newtonsoft.Json). If I uncomment the `[JsonConstructor]` attribute, it works, but that seems overly restrictive. For example, if I want to give my property a different name than the constructor parameter, I get an exception.

```cs
var test = new Foo("hello");
string json = JsonSerializer.Serialize(test);
Console.WriteLine(json);	// {"bar":"hello"}
var obj = JsonSerializer.Deserialize<Foo>(json);
Console.WriteLine(obj.bar);	// null

public readonly record struct Foo
{
	//[JsonConstructor]
	public Foo(string bar)
	{
		this.bar = bar;
	}
	
	public readonly string bar { get; }
}
```

### Reproduction Steps

See description

### Expected behavior

`obj.bar` should be "hello"

### Actual behavior

`obj.bar` is null

### Known Workarounds

Add [JsonConstructor] attribute, or use Newtonsoft.Json

### Configuration

.NET 7

**Comment by eiriktsarpalis** [comment] 2023-11-07 15:17
Duplicate of https://github.com/dotnet/runtime/issues/59309. Struct types always implicitly include a default constructor so this example creates an ambiguity that can only be resolved using an explicit `JsonConstructorAttribute`. The reflection-based serializer can't tell if the default constructor was explicitly or implicitly defined so it will by-default assume that the type includes two constructors.

**Closed** 2023-11-15 20:17 UTC
Labels: area-System.Text.Json, untriaged
