### ISSUE TITLE
Test failure: baseservices\\threading\\paramthreadstart\\ThreadStartGenerics\\ThreadStartGenerics.cmd

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#41931] opened 2020-09-07 07:37 UTC
failed in job: [ runtime-coreclr ilasm 20200905.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=803706&view=ms.vss-test-web.build-test-results-tab&runId=25452210&paneView=debug&resultId=102990)

CoreCLR Windows_NT arm64 Checked ilasmroundtrip @ Windows.10.Arm64v8.Open

failed tests:
baseservices\\threading\\paramthreadstart\\ThreadStartGenerics\\ThreadStartGenerics.cmd
JIT\\Regression\\CLR-x86-JIT\\V2.0-Beta2\\b399444\\b399444a\\b399444a.cmd

Error message
~~~
Return code:      1
Raw output file:      D:\h\w\B17D0988\w\B00E09B4\e\baseservices\threading\Reports\baseservices.threading\paramthreadstart\ThreadStartGenerics\ThreadStartGenerics.output.txt
Raw output:
BEGIN EXECUTION
D:\h\w\B17D0988\p\ildasm.exe /raweh /out=ThreadStartGenerics.dasm.il ThreadStartGenerics.dll
D:\h\w\B17D0988\p\ilasm.exe /output=ThreadStartGenerics.asm.dll  ThreadStartGenerics.dasm.il

Microsoft (R) .NET IL Assembler.  Version 6.0.0-ci
Copyright (c) Microsoft Corporation.  All rights reserved.
Assembling 'ThreadStartGenerics.dasm.il'  to EXE --> 'ThreadStartGenerics.asm.dll'
Could not open ThreadStartGenerics.dasm.il

***** FAILURE ***** 
EXECUTION OF ILASM - FAILED 1
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=D:\h\w\B17D0988\p
> D:\h\w\B17D0988\w\B00E09B4\e\baseservices\threading\paramthreadstart\ThreadStartGenerics\ThreadStartGenerics.cmd
Expected: True
Actual:   False


Stack trace
   at baseservices_threading._paramthreadstart_ThreadStartGenerics_ThreadStartGenerics_._paramthreadstart_ThreadStartGenerics_ThreadStartGenerics_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.arm64.Checked\TestWrappers\baseservices.threading\baseservices.threading.XUnitWrapper.cs:line 27397
~~~

**Comment by briansull** [comment] 2021-01-04 18:37
Possibly a duplicate of  #44139

**Comment by mangod9** [comment] 2021-07-10 01:13
Closing since this hasnt reproed in a while

**Closed by mangod9** 2021-07-10 01:13 UTC
Labels: arch-arm64, area-System.Threading
