### ISSUE TITLE
[dotnet-sdk-8.0.100-rc.1.23415.7] videoduplicatefinder fail to import Scan Result with System.InvalidOperationException

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/runtime#91048] opened 2023-08-24 08:56 UTC
### Description

When run the 3rd party application with the latest .NET 8 build, it failed to import the scan results. During our investigation, it is trying to deserialize json to .NET object, this error occurs when .NET object has System.Text.Encoding type property.  

### Reproduction Steps

**Minimal Repro steps (Demo attached):** 
[JsonDemo.zip](https://github.com/dotnet/runtime/files/12427532/JsonDemo.zip)

1. Create a default7.0 console project.
2. Copy the following code to Program.cs.
```
using System.Text;
using System.Text.Json;

string content = "{\"EncodField\":null,\"MyProperty1\":1}";
using MemoryStream stream = new();
using StreamWriter writer = new(stream);
writer.Write(content);
writer.Flush();
stream.Position = 0;
MyClass? test = await JsonSerializer.DeserializeAsync<MyClass>(stream);
await Console.Out.WriteLineAsync(test.MyProperty1.ToString());

class MyClass
{
    public System.Text.Encoding? EncodField { get; set; }
    public int MyProperty1 { get; set; }
}
```
4. Build the project.
5. Change the runtime.config file to let the app run against with dotnet-sdk-8.0.100-rc.1.23415.7.
```
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "8.0.0-rc.1.23414.4"
    }
```
7. Launch the project.

### Expected behavior

Launch successfully.

### Actual behavior

The error displayed is as follows:

```
System.InvalidOperationException
  HResult=0x80131509
  Message=The type 'System.ReadOnlySpan`1[System.Byte]' of property 'Preamble' on type 'System.Text.Encoding' is invalid for serialization or deserialization because it is a pointer type, is a ref struct, or contains generic parameters that have not been replaced by specific types.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_CannotSerializeInvalidType(Type typeToConvert, Type declaringType, MemberInfo memberInfo) in /_/src/libraries/System.Text.Json/src/System/Text/Json/ThrowHelper.Serialization.cs:line 149
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.CreatePropertyInfo(JsonTypeInfo typeInfo, Type typeToConvert, MemberInfo memberInfo, JsonSerializerOptions options, Boolean shouldCheckForRequiredKeyword, Boolean hasJsonIncludeAttribute) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/DefaultJsonTypeInfoResolver.Helpers.cs:line 209
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.AddMembersDeclaredBySuperType(JsonTypeInfo typeInfo, Type currentType, Boolean constructorHasSetsRequiredMembersAttribute, PropertyHierarchyResolutionState& state) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/DefaultJsonTypeInfoResolver.Helpers.cs:line 145
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.PopulateProperties(JsonTypeInfo typeInfo) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/DefaultJsonTypeInfoResolver.Helpers.cs:line 95
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.CreateTypeInfoCore(Type type, JsonConverter converter, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/DefaultJsonTypeInfoResolver.Helpers.cs:line 58
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.GetTypeInfo(Type type, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/DefaultJsonTypeInfoResolver.cs:line 69
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoNoCaching(Type type) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs:line 815
   at System.Text.Json.JsonSerializerOptions.CachingContext.CreateCacheEntry(Type type, CachingContext context) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Caching.cs:line 261
--- End of stack trace from previous location ---
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Nullable`1 ensureNotNull, Boolean resolveIfMutable, Boolean fallBackToNearestAncestorType) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Caching.cs:line 112
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo.Configure() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonPropertyInfo.cs:line 317
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.ConfigureProperties() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 1086
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 685
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureSynchronized|170_0() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 655
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Nullable`1 ensureNotNull, Boolean resolveIfMutable, Boolean fallBackToNearestAncestorType) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Caching.cs:line 115
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 695
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureSynchronized|170_0() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 655
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Nullable`1 ensureNotNull, Boolean resolveIfMutable, Boolean fallBackToNearestAncestorType) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Caching.cs:line 115
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo.Configure() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonPropertyInfo.cs:line 317
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.ConfigureProperties() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 1086
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 685
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureSynchronized|170_0() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 655
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Nullable`1 ensureNotNull, Boolean resolveIfMutable, Boolean fallBackToNearestAncestorType) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Caching.cs:line 115
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo.Configure() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonPropertyInfo.cs:line 317
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.ConfigureProperties() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 1086
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 685
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureSynchronized|170_0() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 655
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Nullable`1 ensureNotNull, Boolean resolveIfMutable, Boolean fallBackToNearestAncestorType) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Caching.cs:line 115
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo.Configure() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonPropertyInfo.cs:line 317
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.ConfigureProperties() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 1086
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 685
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureSynchronized|170_0() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 655
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Nullable`1 ensureNotNull, Boolean resolveIfMutable, Boolean fallBackToNearestAncestorType) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Caching.cs:line 115
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 695
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureSynchronized|170_0() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 655
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Nullable`1 ensureNotNull, Boolean resolveIfMutable, Boolean fallBackToNearestAncestorType) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Caching.cs:line 115
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo.Configure() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonPropertyInfo.cs:line 317
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.ConfigureProperties() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 1086
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 685
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureSynchronized|170_0() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 655
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Nullable`1 ensureNotNull, Boolean resolveIfMutable, Boolean fallBackToNearestAncestorType) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Caching.cs:line 115
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 695
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureSynchronized|170_0() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonTypeInfo.cs:line 655
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Nullable`1 ensureNotNull, Boolean resolveIfMutable, Boolean fallBackToNearestAncestorType) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Caching.cs:line 115
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoForRootType(Type type, Boolean fallBackToNearestAncestorType) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.Caching.cs:line 152
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Helpers.cs:line 50
   at System.Text.Json.JsonSerializer.DeserializeAsync[TValue](Stream utf8Json, JsonSerializerOptions options, CancellationToken cancellationToken) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Stream.cs:line 55
```

### Regression?

Yes

**Verify Scenarios:**
1). Windows 10 21H2 AMD64 + dotnet-sdk-7.0.110: Pass
2). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.100-rc.1.23415.7: Fail
3). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.100-rc.1.23417.18: Fail
4). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.100-rc.1.23421.5: Fail
5). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.100-preview.2.23117.18: Fail
6). Windows 10 21H2 AMD64 + dotnet-sdk-8.0.100-preview.1.23115.2-win-x64: Pass

### Configuration

**Application Name**: videoduplicatefinder
**OS**： Windows 10 21H2
**CPU:** X64
**.NET Build Number:** dotnet-sdk-8.0.100-rc.1.23415.7
**App & Source Location:** Checking at https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1874021

**Github Link:** https://github.com/0x90d/videoduplicatefinder

### Other information

@dotnet-actwx-bot @dotnet/compat

**Comment by eiriktsarpalis** [comment] 2023-08-24 09:48
Possible duplicate of https://github.com/dotnet/runtime/issues/86419

**Comment by Junjun-zhao** [comment] 2023-08-28 02:56
@eiriktsarpalis Yes. Thanks for checking this issue.
According to comments of https://github.com/dotnet/runtime/issues/86419, team will be creating a breaking change doc for this issue. Once the breaking change doc is created, could you help update the bug?  This document will subsequently be shared with the customers whose apps are affected by this change. Thank you.

**Comment by krwq** [comment] 2023-08-31 10:15
@Junjun-zhao can you clarify what update do you mean? Can we close this issue as duplicate or do we expect to do anything else here? The other issue will be auto updated when there is any change made referencing it

**Comment by Junjun-zhao** [comment] 2023-09-01 01:46
Yes, we can close this issue as duplicate, but can you please update https://github.com/dotnet/runtime/issues/86419 when breaking change document is created.

We are the .NET AppCompat team and we have a representative set of apps in our lab. Generally, an issue that we find in-house could potentially impact a bigger customer base in the real world. After breaking change document is created, we will communicate with customers about the breaking change.

**Closed** 2023-09-04 10:00 UTC
Labels: area-System.Text.Json, untriaged

**Comment by Junjun-zhao** [comment] 2023-09-12 01:12
Breaking change issue filed:  https://github.com/dotnet/docs/issues/37041
