### ISSUE TITLE
Test failure JIT\\HardwareIntrinsics\\General\\Vector128\\Vector128_r\\Vector128_r.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#66320] opened 2022-03-08 01:24 UTC
Run: [runtime-coreclr crossgen2 20220306.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=1648348&view=ms.vss-test-web.build-test-results-tab&runId=45508384&resultId=100274&paneView=debug)

Failed test:
```
R2R-CG2 windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open

- JIT\\HardwareIntrinsics\\General\\Vector128\\Vector128_r\\Vector128_r.cmd
- JIT\\HardwareIntrinsics\\General\\Vector128\\Vector128_ro\\Vector128_ro.cmd
- JIT\\HardwareIntrinsics\\General\\Vector128_1\\Vector128_1_r\\Vector128_1_r.cmd
- JIT\\HardwareIntrinsics\\General\\Vector128_1\\Vector128_1_ro\\Vector128_1_ro.cmd
```
**Error message:**
```
Could Not Find C:\h\w\98BE084E\w\AC4D0954\e\JIT\HardwareIntrinsics\General\Vector128\Vector128_r\IL-CG2\composite-r2r.dll
Could Not Find C:\h\w\98BE084E\w\AC4D0954\e\JIT\HardwareIntrinsics\General\Vector128\Vector128_r\TestLibrary.dll.rsp
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'ILCompiler.DependencyAnalysisFramework, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.
File name: 'ILCompiler.DependencyAnalysisFramework, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'
at ILCompiler.ReadyToRunCodegenCompilationBuilder.ToCompilation()
at ILCompiler.Program.RunSingleCompilation(Dictionary2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary2 unrootedInputFilePaths, HashSet`1 versionBubbleModulesHash, CompilerTypeSystemContext typeSystemContext)
at ILCompiler.Program.Run(String[] args)
at ILCompiler.Program.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\98BE084E\w\AC4D0954\uploads\Reports\JIT.HardwareIntrinsics\General\Vector128\Vector128_r\Vector128_r.output.txt
Raw output:
BEGIN EXECUTION
TestLibrary.dll
Vector128_r.dll
2 file(s) copied.
Response file: C:\h\w\98BE084E\w\AC4D0954\e\JIT\HardwareIntrinsics\General\Vector128\Vector128_r\TestLibrary.dll.rsp
C:\h\w\98BE084E\w\AC4D0954\e\JIT\HardwareIntrinsics\General\Vector128\Vector128_r\IL-CG2\TestLibrary.dll
-o:C:\h\w\98BE084E\w\AC4D0954\e\JIT\HardwareIntrinsics\General\Vector128\Vector128_r\TestLibrary.dll
--targetarch:x64
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\98BE084E\p\System..dll
-r:C:\h\w\98BE084E\p\Microsoft..dll
-r:C:\h\w\98BE084E\p\mscorlib.dll
-r:C:\h\w\98BE084E\p\netstandard.dll
-O
" "dotnet" "C:\h\w\98BE084E\p\crossgen2\crossgen2.dll" @"C:\h\w\98BE084E\w\AC4D0954\e\JIT\HardwareIntrinsics\General\Vector128\Vector128_r\TestLibrary.dll.rsp"   -r:C:\h\w\98BE084E\w\AC4D0954\e\JIT\HardwareIntrinsics\General\Vector128\Vector128_r\IL-CG2*.dll"
Crossgen2 failed with exitcode - -532462766
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\98BE084E\p
C:\h\w\98BE084E\w\AC4D0954\e\JIT\HardwareIntrinsics\General\Vector128\Vector128_r\Vector128_r.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_HardwareIntrinsics._General_Vector128_Vector128_r_Vector128_r_._General_Vector128_Vector128_r_Vector128_r_cmd()
```

**Comment by tannergooding** [comment] 2022-03-11 17:23
Dupe of https://github.com/dotnet/runtime/issues/65646

**Closed by tannergooding** 2022-03-11 17:23 UTC
Labels: os-windows, arch-x64, area-crossgen2-coreclr, untriaged
