### ISSUE TITLE
BigInteger incorrectly parses large integer hex string

### ISSUE THREAD

**Issue by alexhelms** [dotnet/runtime#50385] opened 2021-03-29 18:46 UTC
### Description
The following expression results in the wrong parsed value:

```c#
string s = BigInteger.Parse("FFFFFFFFFFFFFFFF01", NumberStyles.HexNumber, null).ToString("X")
Debug.Assert(s == "F01");
```

I would expect the string to be the same as the input -- `FFFFFFFFFFFFFFFF01`. Further, any number of Fs results in the same `F01` result.

Trying another huge number results in the correct parsing:

```c#
string s = BigInteger.Parse("abcdefabcdefabcdefabcdefabcdef", NumberStyles.HexNumber, null).ToString("X")
Debug.Assert(s == "ABCDEFABCDEFABCDEFABCDEFABCDEF");
```

### Configuration

```
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295
```

**Comment by tannergooding** [comment] 2021-03-29 18:55
This is different from how other integral types, like `int32` parse hex values like this.
`Int32` and others treat `FF01` as a positive value, while `BigInteger` is treating it as a `signed` value and therefore produces `-255`.

However, this is a long time difference and changing it will be breaking.
It would require a bar check on how breaking it would be and if the change is ultimately worthwhile.

**Comment by alexhelms** [comment] 2021-03-29 19:07
Got it. I understand this is because of how two's complement works and the assumptions BigInteger makes. I supposed the documentation for Parse could indicate that it assumes signed integers? I don't see anything in the docs for Parse that says it assumes signed integers. Longer term, perhaps an additional flag to indicate signed or unsigned?

**Comment by tannergooding** [comment] 2021-06-17 23:53
Closing this as "by design".

We are happy to take a PR updating the documentation or a new issue proposing (https://github.com/dotnet/runtime/issues/new?assignees=&labels=api-suggestion&template=02_api_proposal.md&title=) an API that allows you to explicitly parse as signed vs unsigned.

**Closed by tannergooding** 2021-06-17 23:53 UTC
Labels: area-System.Numerics
