### ISSUE TITLE
dotnet watch does not work on macOS Catalina

### ISSUE THREAD

**Issue by optimizasean** [dotnet/runtime#54586] opened 2021-06-22 23:50 UTC
**Edited**: See https://github.com/dotnet/runtime/issues/54586#issuecomment-882884380. There is some issue with `dotnet watch` and projects in a home directory that is not in the usual location (possibly related to directory symlinks).

---
*Original report*:

I have seen a few messages in the aspnet gitter but I think it might be an isolated problem, not an issue. I hope if someone else has the same problem, they will google and find it here and then we will be able to tell if it is an issue or a problem with my system. As for 5.X it worked with Mojave through 3.X-5.X. At 6p2, it worked on Mojave but once I moved to Catalina, it stopped working.

Moved to fresh new mac on Catalina and it also doesn't work here, since .NET6p2 all the way to .NET6p5 (current).

I have tried all variants of the watch command using absolute and relative path, project v.s. solution, as well as the different delimiters like -- run and more on .NET6p5. Have exhausted every combination. It does not detect additions, deletions, or changes in files: .css .razor .cs, even the Program or Startup files. It does not detect even when a file is moved, renamed, added, or deleted.

Probably separate issue: The watch command causes these two errors in browser console:
```
* Assertion at /__w/1/s/src/mono/mono/metadata/assembly.c:1374, condition `<disabled>' not met

542256 @ dotnet.6.0.0-preview.5.21301.5.js:1
```

```
ExitStatus
message: "Program terminated with exit(0)"
name: "ExitStatus"
status: 0
__proto__: Object
```

Moved these notes from the end of: https://github.com/dotnet/corefx/pull/41963 at the tip from @danmoseley

Linked comments:
https://github.com/dotnet/corefx/pull/41963#issuecomment-812221620
https://github.com/dotnet/corefx/pull/41963#issuecomment-812774601
https://github.com/dotnet/corefx/pull/41963#issuecomment-866336263

**Comment by hoyosjs** [comment] 2021-06-23 00:33
@pranavkm fyi, in case you are familiar with this in `dotnet-watch` 

cc: @tommcdon

**Comment by danmoseley** [comment] 2021-06-23 01:17
@lewing  is the assert above, WASM specific? I see .ha

**Comment by tommcdon** [comment] 2021-06-23 01:19
@lambdageek

**Comment by pranavkm** [comment] 2021-06-23 02:52
This might be a dupe of https://github.com/dotnet/aspnetcore/issues/33319. Are you able to try using preview6  nightlies (of the sdk and packages) https://github.com/dotnet/installer#installers-and-binaries to see if that helps?

**Comment by lambdageek** [comment] 2021-07-02 05:48
@pranavkm there are two separate issues here:
1. `dotnet watch` apparently not detecting source file changes.
2. the assembly.c assertion in the JS console (that is definitely a duplicate of dotnet/aspnetcore#33319).

@optimizasean can you provide a short self-contained, buildable example that demonstrates the problem you're running into with `dotnet watch`.  Ideally, a git repo that has the exact project that has the problem, and also what is the exact command you're running to run `dotnet watch` as well as an example of an edit that you're making.

**Comment by optimizasean** [comment] 2021-07-19 21:41
Oops sorry didn't get the notification for this...

Basically dotnet new blazorwasm (or any project really) and I have that problem.  I have recently discovered it fails in console, webapi, blazorserver, blazorwasm, and mvc...

Sample dotnet commands: dotnet watch, dotnet watch -- run, dotnet watch --project (project details), dotnet watch run... basically all of them.

It fails consistently on all accounts with all combinations of commands.  I am now on preview 6 and the issue has persisted.  Happens on *.cs, *.razor, and all other files located within both my webapi and my blazor project I have been working on.  I can add, delete, modify, basically any file located inside any .NET project using any version of the watch command and it fails to recompile/reload since it appears not to notice any changes or file system events.  Nothing appears in the console after doing things with the files:

```
watch : Started
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://[::]:80
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: {path}
```
do anything at this point and the console does not change or write anything.  ctrl-shift-r and ctrl-c both work, it is not like the window is frozen, just not detecting any file system events from my understanding.

**Comment by optimizasean** [comment] 2021-07-19 21:49
Wait...think I just isolated the issue possibly...the watch command only works if your user account folder is in the standard location.   I just tested on another account and it works now (.NET6p6) however still fails on my main account.  What do I need to give permission to so that it can work in a different directory or through symlinks?

Short: works in user account folder ~/ only if user account folder is in expected location /Users/accountname/anysubdirectoryhere.  If you move your user account folder elsewhere /Sandbox/accountname/anysubdirectoryhere it will not watch anything?

**Comment by lambdageek** [comment] 2021-07-28 14:22
> Wait...think I just isolated the issue possibly...the watch command only works if your user account folder is in the standard location. I just tested on another account and it works now (.NET6p6) however still fails on my main account. What do I need to give permission to so that it can work in a different directory or through symlinks?
> 
> Short: works in user account folder ~/ and all sub folders only if user account folder is in expected location /Users/accountname/anysubdirectoryhere. If you move your user account folder elsewhere /Sandbox/accountname/anysubdirectoryhere it will not watch anything?
> 
> Tested with user folder setup of: /System/Volumes/Data/Sandbox/optimizasean/..... and /Sandbox/optimizasean/....... since usually the user would be located at /System/Volumes/Data/Users/optimizasean it appears it is path/permissions related possibly?

@pranavkm ^ Possibly `dotnet watch` doesn't follow directory symlinks?

@optimizasean I'm a a little bit unclear on the directory setup.  Can you tell me a couple of directory names and all the symlinks from one folder to another, and in which directory you run `dotnet watch`.

**Comment by pranavkm** [comment] 2021-07-28 15:37
@Jozkee am I correct in understanding that https://github.com/dotnet/runtime/pull/52679 does not allow the FSW to follow symlinks in subdir? 

@optimizasean you could consider using the polling file watcher https://docs.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch?view=aspnetcore-5.0#dotnet-watch-configuration for your app's setup.

**Comment by Jozkee** [comment] 2021-08-02 17:06
@Jozkee am I correct in understanding that #52679 does not allow the FSW to follow symlinks in subdir?

Yes, FSW doesn't detect changes on directories that are referenced by a symlink inside of the watched directory.
If `dotnet watch` uses PhysicalFileProvider to watch for changes, it is possible that this could be fixed by https://github.com/dotnet/runtime/pull/55664 while using polling.

**Comment by optimizasean** [comment] 2021-08-02 22:17
@pranavkm you are correct.  The file polling works through `DOTNET_USE_POLLING_FILE_WATCHER=1 dotnet watch` and properly detects changes immediately.

@lambdageek there may be symlinks but I am pretty sure I am not in a symlinked directory when running, although it is just not the standard location of the user folder from my understanding.

At the root I do have one symlink: `/Developers -> /System/Volumes/Data/Developers`, other than that nothing is symlinked

**Comment by lambdageek** [comment] 2021-08-10 14:57
I think this is resolved - per https://github.com/dotnet/runtime/issues/54586#issuecomment-872734512 - 
> 1. `dotnet watch` apparently not detecting source file changes.

This is due to symlinks (and ultimately https://github.com/dotnet/runtime/pull/52679), and the workaround is to use `DOTNET_USE_POLLING_FILE_WATCHER=1 dotnet watch`

> 2. the assembly.c assertion in the JS console (that is definitely a duplicate of https://github.com/dotnet/aspnetcore/issues/33319)

which is fixed in .net 6 preview 6

**Closed by lambdageek** 2021-08-10 14:57 UTC
Labels: area-EnC-mono
