### ISSUE TITLE
[HTTP/3] [HttpStress] QuicException: Stream aborted by peer (258) in `(POST Duplex | PUT) Slow`

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#100534] opened 2024-04-02 16:49 UTC
There are 30-50 hits per Linux CI run since #100023, and some rare sporadic Windows hits, but with error code 269.

```
System.Net.Http.HttpRequestException: Error while copying content to a stream.
 ---> System.Net.Http.HttpProtocolException: The HTTP/3 server reset the stream. HTTP/3 error code 'H3_INTERNAL_ERROR' (0x102). (HttpProtocolError)
 ---> System.Net.Quic.QuicException: Stream aborted by peer (258).
   at System.Net.Quic.ResettableValueTaskSource.TryComplete(Exception exception, Boolean final) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ResettableValueTaskSource.cs:line 177
   at System.Net.Quic.ResettableValueTaskSource.TrySetException(Exception exception, Boolean final) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ResettableValueTaskSource.cs:line 237
   at System.Net.Quic.QuicStream.HandleEventPeerSendAborted(_PEER_SEND_ABORTED_e__Struct& data) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs:line 580
   at System.Net.Quic.QuicStream.HandleStreamEvent(QUIC_STREAM_EVENT& streamEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs:line 635
   at System.Net.Quic.QuicStream.NativeCallback(QUIC_HANDLE* stream, Void* context, QUIC_STREAM_EVENT* streamEvent) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs:line 667
--- End of stack trace from previous location ---
   at System.Net.Quic.ResettableValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/ResettableValueTaskSource.cs:line 251
   at System.Net.Quic.QuicStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicStream.cs:line 308

```

**Comment by ManickaP** [comment] 2024-04-03 08:06
This might be the very same root cause as https://github.com/dotnet/runtime/issues/76183#issuecomment-2032544294

**Comment by antonfirsov** [comment] 2024-08-20 14:01
There were recent occurrences, reopening. Even though the root cause might be the same as for #76183, it's worth to track the issue separately.

**Comment by ManickaP** [comment] 2024-10-22 16:11
I see only error code 267 request_rejected, I'll close this one, because what we're seeing is covered by #109121.

**Closed by ManickaP** 2024-10-22 16:11 UTC
Labels: area-System.Net.Http, tracking-external-issue
