### ISSUE TITLE
`Process.Modules` does not list all modules/shared objects of a target process when executed on Linux

### ISSUE THREAD

**Issue by just-ero** [dotnet/runtime#70904] opened 2022-06-17 17:53 UTC
### Description

Not all modules/shared objects are listed when calling `Process.Modules` on a process on Linux machines. MacOS machines may also be affected.

Of note for this issue is that `/proc/{proc.Id}/maps` (the file which holds all maps loaded by a process) lists most maps more than once, presumably because they take up multiple memory regions. Those maps look similar to the following output:
```
7f673eb42000-7f673eb6a000 r--p 00000000 08:20 9815                       /usr/lib/x86_64-linux-gnu/libc.so.6
7f673eb6a000-7f673ecff000 r-xp 00028000 08:20 9815                       /usr/lib/x86_64-linux-gnu/libc.so.6
7f673ecff000-7f673ed57000 r--p 001bd000 08:20 9815                       /usr/lib/x86_64-linux-gnu/libc.so.6
7f673ed57000-7f673ed5b000 r--p 00214000 08:20 9815                       /usr/lib/x86_64-linux-gnu/libc.so.6
7f673ed5b000-7f673ed5d000 rw-p 00218000 08:20 9815                       /usr/lib/x86_64-linux-gnu/libc.so.6
```
The flags (`r`, `w`, `x`, `p`, `s`) in the second column are the root of this issue.  
The maps that do not get listed only have a single entry which contains the flags `r`, and `s`:
```
7f673a9a3000-7f673a9ab000 r--s 00000000 08:20 2470                       /usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.6/System.Runtime.dll
```

### Reproduction Steps

Create a new console application with the following content in `Program.cs`:
```cs
using System.Diagnostics;

// use the executing process as a simple example
var proc = Process.GetCurrentProcess();

// /proc/{pId}/maps holds information about loaded memory maps
// it is also used by Process.Modules as per
// System.Diagnostics.Process/Interop.ProcFsStat.ParseMapModules.cs#L18
var maps = $"/proc/{proc.Id}/maps";

// since the issue is about maps which only have the `r--s` (read and shared),
// we only care about entries with those flags here
var readSharedMaps = File.ReadLines(maps)
                     .Where(line => line.Contains("r--s"));

// list missing maps
foreach (var map in readSharedMaps)
{
    Console.WriteLine(map);
}

Console.WriteLine();

// list and compare to Process.Modules
foreach (ProcessModule module in proc.Modules)
{
    Console.WriteLine(module.ModuleName);
}
```

Build using `dotnet build --os linux -c release` and run on a Linux machine or the Windows Subsystem for Linux using `dotnet TestConsole.dll` or `./TestConsole`.

The output will be similar to the following:
```
7fb7a43de000-7fb7a43e6000 r--s 00000000 08:20 2470                       /usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.6/System.Runtime.dll
7fb7a43e6000-7fb7a43e8000 r--s 00000000 08:20 2299                       /home/just-ero/code/TestConsole.dll

TestConsole
System.Private.CoreLib.dll
System.Diagnostics.Process.dll
System.ComponentModel.Primitives.dll
System.Linq.dll
System.Console.dll
System.Collections.NonGeneric.dll
System.Collections.dll
System.Threading.dll
Microsoft.Win32.Primitives.dll
System.Memory.dll
libicui18n.so.70.1
libicudata.so.70.1
libicuuc.so.70.1
libSystem.Native.so
libclrjit.so
librt.so.1
libcoreclr.so
libhostpolicy.so
libhostfxr.so
libc.so.6
libgcc_s.so.1
libm.so.6
libstdc++.so.6.0.30
libdl.so.2
libpthread.so.0
ld-linux-x86-64.so.2
[vdso]
```

Evidently, `Process.Modules` did not list `System.Runtime.dll`.

### Expected behavior

`Process.Modules` should list all loaded modules.

### Actual behavior

`Process.Modules` does not list all modules.

### Configuration

Tested on a .NET 6 console application, built using `dotnet build --os linux -c release` (results in a 64-bit build), executed on WSL2, Ubuntu 22.04 trying both `dotnet TestConsole.dll` and `./TestConsole`, both not listing `TestConsole.dll` and `System.Runtime.dll` (the latter will list `TestConsole` because it is the "executable" and therefore the main module, but not the library).

### Other information

Due to [the requirement of *both* the `read` and `exec` flags](https://github.com/dotnet/runtime/blob/a103efd28d46af39fc22a77458a11d204226e8d4/src/libraries/Common/src/Interop/Linux/procfs/Interop.ProcFsStat.ParseMapModules.cs#L88) for a module to be considered valid, modules which only contain the `read` and `shared` flags will get ignored. I'm unsure how or if this can be fixed without breaking things.

**Comment by tmds** [comment] 2022-06-18 06:39
Dup of https://github.com/dotnet/runtime/issues/64042?

**Comment by just-ero** [comment] 2022-06-18 06:50
> Dup of #64042?

A bit unfortunate that this issue has been known for over 4 years, apparently, forcing people to keep creating their own implementation of `Process.Modules` that fixes it.

**Comment by jkotas** [comment] 2022-06-18 12:16
Yes, this is duplicate of https://github.com/dotnet/runtime/issues/64042.

> A bit unfortunate that this issue has been known for over 4 years, apparently, forcing people to keep creating their own implementation of Process.Modules that fixes it.

If you need to inspect details of other processes, your best bet are 3rd party libraries that specialize in it. I do not expect we will ever make `Process.Modules` property 100% reliable.

If we were designing the `Process` class from scratch again, `Process.Modules` property would not exist on it. `Process.Modules` property does not fit well into cross-platform .NET runtime core libraries.

**Closed by jkotas** 2022-06-18 12:16 UTC
Labels: area-System.Diagnostics.Process
