### ISSUE TITLE
EE skips static field initialization when scope references collection literals

### ISSUE THREAD

**Issue by isadorasophia** [dotnet/runtime#92615] opened 2023-09-25 23:23 UTC
### Description

While investigating bug #92022, I noticed that debugging a console app with .NET 8 RC1 using collection literals may imply in the debugger not initializing static fields upon evaluation.

### Reproduction Steps

I included an example app below. You can notice that the only change is how I reference `Constants.Coordinates[0]` in the line below the breakpoint.

### Expected behavior

**Working scenario**
```csharp
Debugger.Break(); // Breaking here, evaluating Constants.Something returns 3 ✅

Console.WriteLine($"Hello, World from {Constants.Something}");

public static class Constants
{
    public static readonly int Something = 3;

    public static readonly ImmutableArray<string> Coordinates =
    [
        "a8", "b8", "c8", "d8", "e8", "f8", "g8", "h8",
        "a7", "b7", "c7", "d7", "e7", "f7", "g7", "h7",
        "a6", "b6", "c6", "d6", "e6", "f6", "g6", "h6",
        "a5", "b5", "c5", "d5", "e5", "f5", "g5", "h5",
        "a4", "b4", "c4", "d4", "e4", "f4", "g4", "h4",
        "a3", "b3", "c3", "d3", "e3", "f3", "g3", "h3",
        "a2", "b2", "c2", "d2", "e2", "f2", "g2", "h2",
        "a1", "b1", "c1", "d1", "e1", "f1", "g1", "h1"
    ];
}
```
![image](https://github.com/dotnet/runtime/assets/7958854/7b7b46b2-45a6-41a1-939e-bf9c089ce212)

### Actual behavior

**Breaking scenario**
```csharp
Debugger.Break(); // Breaking here, evaluating Constants.Something returns 0 ❌

Console.WriteLine($"Hello, World from {Constants.Coordinates[0]}");

public static class Constants
{
    public static readonly int Something = 3;

    public static readonly ImmutableArray<string> Coordinates =
    [
        "a8", "b8", "c8", "d8", "e8", "f8", "g8", "h8",
        "a7", "b7", "c7", "d7", "e7", "f7", "g7", "h7",
        "a6", "b6", "c6", "d6", "e6", "f6", "g6", "h6",
        "a5", "b5", "c5", "d5", "e5", "f5", "g5", "h5",
        "a4", "b4", "c4", "d4", "e4", "f4", "g4", "h4",
        "a3", "b3", "c3", "d3", "e3", "f3", "g3", "h3",
        "a2", "b2", "c2", "d2", "e2", "f2", "g2", "h2",
        "a1", "b1", "c1", "d1", "e1", "f1", "g1", "h1"
    ];
}
```
![image](https://github.com/dotnet/runtime/assets/7958854/50174a57-8335-4752-bde0-058a4dfa0930)

### Regression?

This is a new .NET 8/C# 12 feature.

### Configuration

.NET 8 RC1 and Visual Studio 17.8 Preview 2

**Comment by tommcdon** [comment] 2023-09-25 23:36
@mikelle-rogers

**Comment by tommcdon** [comment] 2024-07-23 21:11
We investigated this issue and determined it was by design, and so we are closing it. Please let us know if this assessment is not correct and we will re-evaluate.

**Closed by tommcdon** 2024-07-23 21:11 UTC
Labels: enhancement, area-Diagnostics-coreclr

**Comment by jkotas** [comment] 2024-07-23 23:27
@tommcdon Did you mean to say that this issue was fixed? The behavior described in the repro steps looks like a clear bug to me, but it does not reproduce for me on current VS.

**Comment by mikelle-rogers** [comment] 2024-07-24 00:07
(It is great if it no longer repros!)
During issue triage today, I mentioned this was by design based off a conversation with my teammate. I had not checked to see if I could reproduce it since November 2023.
Here is the comment from my coworker when I asked about this issue in November 2023: 

"I'm pretty sure both examples are testing undefined behavior. There is a bit on the metadata for all .NET type definitions called 'BeforeFieldInit'. You don't directly set it when writing in C#, but its there if you look with ILDasm. As I recall C# types that do not have static constructors are marked 'BeforeFieldInit'. Static fields in a type marked 'BeforeFieldInit are promised to be initialized no later than when they are first accessed, but there is no promise about how early it could happen. This means the runtime is free to initialize the static field before or after those calls to Debugger.Break(). On the debugger side, calling ICorDebugClass::GetStaticFieldValue() does not automatically cause a static field to become initialized. If the runtime for other reasons had already initialized the field then it will be initialized, and if the runtime hasn't needed to intialize it then it won't be. Many years ago there was some discussion around adding new ICorDebug APIs that would either report whether the static was initialized or let the debugger ask that it become initialized. Those are reasonable requests if VS debugger wants to make them."


We reached out to the VS debugger team asking about priority in November 2023. They replied they did not know what the priority was. We had not heard from then since.

**Comment by jkotas** [comment] 2024-07-24 00:17
Sounds good.

FuncEval in Visual Studio is expected to execute the static constructors as necessary, just like regular code would execute them. It is how it worked since forever. 

This looks like a bug in collection literals features that was fixed in Roslyn or VS FuncEval engine.

**Comment by jkotas** [comment] 2024-07-24 00:49
Still, this looks like a Visual Studio to me.

Also, BeforeFieldInit is not relevant for the repro - it repros with explicit static constructor too:

```
Debugger.Break(); // Breaking here, evaluating Constants.Something returns 0 ❌

Console.WriteLine($"Hello, World from {Constants.Coordinates[0]}");

public static class Constants
{
    static Constants()
    {
        Something = 3;

        Coordinates =
        [
            "a8", "b8", "c8", "d8", "e8", "f8", "g8", "h8",
            "a7", "b7", "c7", "d7", "e7", "f7", "g7", "h7",
            "a6", "b6", "c6", "d6", "e6", "f6", "g6", "h6",
            "a5", "b5", "c5", "d5", "e5", "f5", "g5", "h5",
            "a4", "b4", "c4", "d4", "e4", "f4", "g4", "h4",
            "a3", "b3", "c3", "d3", "e3", "f3", "g3", "h3",
            "a2", "b2", "c2", "d2", "e2", "f2", "g2", "h2",
            "a1", "b1", "c1", "d1", "e1", "f1", "g1", "h1"
        ];
    }

    public static readonly int Something;

    public static readonly ImmutableArray<string> Coordinates;
}
```

**Comment by tommcdon** [comment] 2024-07-24 13:12
I've opened [Bug 2172208](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2172208): Visual Studio Expression Evaluation returns incorrect data for static variables not yet initialized.
