### ISSUE TITLE
System.ServiceProcess.Tests.ServiceControllerTests fails in outerloop

### ISSUE THREAD

**Issue by noahfalk** [dotnet/runtime#56679] opened 2021-08-01 00:39 UTC
Multiple test cases failed in this job https://github.com/dotnet/runtime/pull/56654/checks?check_run_id=3207664110

[Example failure](https://helix.dot.net/api/2019-06-17/jobs/d56d8f87-25b6-4771-9e5b-c824b95f44d9/workitems/System.ServiceProcess.ServiceController.Tests/console):
```
Console log: 'System.ServiceProcess.ServiceController.Tests' from job d56d8f87-25b6-4771-9e5b-c824b95f44d9 workitem 1f3c5d50-0a2e-4a8c-b0e0-4dd9478c65d5 (windows.10.amd64.server19h1.es.open.rt) executed on machine a001RLF

C:\h\w\A9F20938\w\B23F099E\e>taskkill.exe /f /im corerun.exe 
ERROR: no se encontr¢ el proceso "corerun.exe".

C:\h\w\A9F20938\w\B23F099E\e>call RunTests.cmd --runtime-path C:\h\w\A9F20938\p 
----- start 31/07/2021  5:22:10,13 ===============  To repro directly: ===================================================== 
pushd C:\h\w\A9F20938\w\B23F099E\e\
"C:\h\w\A9F20938\p\dotnet.exe" exec --runtimeconfig System.ServiceProcess.ServiceController.Tests.runtimeconfig.json --depsfile System.ServiceProcess.ServiceController.Tests.deps.json xunit.console.dll System.ServiceProcess.ServiceController.Tests.dll -xml testResults.xml -nologo -nocolor -trait category=OuterLoop -notrait category=IgnoreForCI -notrait category=failing 
popd
===========================================================================================================

C:\h\w\A9F20938\w\B23F099E\e>"C:\h\w\A9F20938\p\dotnet.exe" exec --runtimeconfig System.ServiceProcess.ServiceController.Tests.runtimeconfig.json --depsfile System.ServiceProcess.ServiceController.Tests.deps.json xunit.console.dll System.ServiceProcess.ServiceController.Tests.dll -xml testResults.xml -nologo -nocolor -trait category=OuterLoop -notrait category=IgnoreForCI -notrait category=failing  
  Discovering: System.ServiceProcess.ServiceController.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.ServiceProcess.ServiceController.Tests (found 25 of 40 test cases)
  Starting:    System.ServiceProcess.ServiceController.Tests (parallel test collections = on, max threads = 2)
    System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.InvalidOperationException)
      Actual:   (No exception was thrown)
      Stack Trace:
        /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceControllerTests.netcoreapp.cs(16,0): at System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException()
  Finished:    System.ServiceProcess.ServiceController.Tests
=== TEST EXECUTION SUMMARY ===
   System.ServiceProcess.ServiceController.Tests  Total: 25, Errors: 0, Failed: 1, Skipped: 0, Time: 49,009s
----- end 31/07/2021  5:22:59,82 ----- exit code 1 ----------------------------------------------------------
 31/07/2021- 5:22:59,82
 31/07/2021- 5:23:00,02
2021-07-31 05:23:00,310: INFO: 3496: run(141): main: Main thread starting 10 workers
Searching 'C:\h\w\A9F20938\w\B23F099E\e\..' for log files
Found log 'C:\h\w\A9F20938\w\B23F099E\e\..\console.6465c620.log'
Uri 'https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-56654-merge-d56d8f8725b647719e/System.ServiceProcess.ServiceController.Tests/console.6465c620.log?sv=2019-07-07&se=2021-08-20T04%3A54%3A22Z&sr=c&sp=rl&sig=xTvsNZna7J0%2B6Ef59WdgAQptLdsSnpANFS4EFd64dCE%3D'
Generated log list: console.6465c620.log:
  https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-56654-merge-d56d8f8725b647719e/System.ServiceProcess.ServiceController.Tests/console.6465c620.log?sv=2019-07-07&se=2021-08-20T04%3A54%3A22Z&sr=c&sp=rl&sig=xTvsNZna7J0%2B6Ef59WdgAQptLdsSnpANFS4EFd64dCE%3D

Searching 'C:\h\w\A9F20938\w\B23F099E\e' for test results files
Found results file C:\h\w\A9F20938\w\B23F099E\e\testResults.xml with format xunit
Searching 'C:\h\w\A9F20938\w\B23F099E\uploads' for test results files
 31/07/2021- 5:23:05,81
```

**Comment by mateoatr** [comment] 2021-08-04 15:23
A few more failures in [runtime-libraries-coreclr outerloop](https://dev.azure.com/dnceng/public/_build/results?buildId=1272892&view=results).

**Comment by eerhardt** [comment] 2021-08-11 18:32
Dupe of #57115

**Closed by eerhardt** 2021-08-11 18:32 UTC
Labels: area-System.ServiceProcess, blocking-clean-ci-optional

**Comment by danmoseley** [comment] 2021-08-11 19:25
There were 3 distinct failures, the two linked above, and also one that should be fixed by this https://github.com/dotnet/runtime/pull/57108 

thanks for letting us know, it's easy to miss outerloop failures.
