### ISSUE TITLE
Test failure System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#59451] opened 2021-09-22 02:21 UTC
Run:  [runtime-libraries-coreclr outerloop 20210921.5](https://dev.azure.com/dnceng/public/_build/results?buildId=1374984&view=ms.vss-test-web.build-test-results-tab&runId=40107272&resultId=103258&paneView=debug)

Failed test:
```
net7.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.ServerRS5.Open

- System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)
- System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(server: ws://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)

net7.0-windows-Release-x64-CoreCLR_release-(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-08e8e40-20200107182504

- System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(server: ws://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)

net7.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.Server19H1.Open

- System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)
- System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(server: ws://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)

net7.0-windows-Release-x64-CoreCLR_release-Windows.81.Amd64.Open

- System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(server: ws://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)

net7.0-OSX-Release-arm64-CoreCLR_release-OSX.1100.ARM64.Open

- System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)
- System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(server: ws://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)

net7.0-Linux-Release-x64-CoreCLR_release-(Mariner.1.0.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-1.0-helix-20210528192219-92bf620

- System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(server: ws://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)

net7.0-Linux-Release-x64-CoreCLR_release-(Ubuntu.1910.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-19.10-helix-amd64-cfcfd50-20191030180623

- System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(server: ws://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)

net7.0-Linux-Release-arm64-CoreCLR_release-(Ubuntu.1804.ArmArch.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-helix-arm64v8-20210106155927-56c6673

- System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(server: ws://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)

net7.0-windows-Release-x86-CoreCLR_release-Windows.7.Amd64.Open

- System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(server: ws://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)

net7.0-Linux-Release-arm-CoreCLR_release-(Debian.10.Arm32.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-arm32v7-20210304164340-6616c63

- System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(server: ws://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)

```
**Error message:**
```
Assert.Throws() Failure
Expected: typeof(System.OperationCanceledException)
Actual:   (No exception was thrown)


Stack trace
   at System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(Uri server) in /_/src/libraries/System.Net.WebSockets.Client/tests/CancelTest.cs:line 27
--- End of stack trace from previous location ---
```

**Comment by VincentBu** [comment] 2021-09-30 01:47
Failed again in: [runtime-libraries-coreclr outerloop 20210929.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1392616&view=ms.vss-test-web.build-test-results-tab&runId=40496884&paneView=debug&resultId=104474)

Failed test:
```
net7.0-windows-Release-x64-CoreCLR_release-Windows.81.Amd64.Open
- Attempt #3 - System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)
- Attempt #1 - System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)

net7.0-Linux-Release-x64-CoreCLR_release-Ubuntu.1804.Amd64.Open
- Attempt #3 - System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)

net7.0-Linux-Release-x64-CoreCLR_release-(Centos.8.Amd64.Open)Ubuntu.1604.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:centos-8-helix-20201229003624-c1bf759
- Attempt #1 - System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)

net7.0-Linux-Release-x64-CoreCLR_release-RedHat.7.Amd64.Open
- Attempt #3 - System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)

net7.0-Linux-Release-x64-CoreCLR_release-(Fedora.34.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:fedora-34-helix-20210913123654-4f64125
- Attempt #3 - System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)
- Attempt #1 - System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)

net7.0-Linux-Release-x64-CoreCLR_release-(Debian.11.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-11-helix-amd64-20210304164428-5a7c380
- Attempt #3 - System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)
- Attempt #2 - System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)

net7.0-Linux-Release-x64-CoreCLR_release-(Mariner.1.0.Amd64.Open)ubuntu.1604.amd64.open@mcr.microsoft.com/dotnet-buildtools/prereqs:cbl-mariner-1.0-helix-20210528192219-92bf620
- Attempt #3 - System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)
- Attempt #2 - System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)

net7.0-OSX-Release-arm64-CoreCLR_release-OSX.1100.ARM64.Open
- Attempt #3 - System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)
- Attempt #1 - System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(server: wss://corefx-net-http11.azurewebsites.net/WebSocket/EchoWebSocket.ashx)
```
**Error message:**
```
Assert.Throws() Failure
Expected: typeof(System.OperationCanceledException)
Actual:   (No exception was thrown)


Stack trace
   at System.Net.WebSockets.Client.Tests.CancelTest.ConnectAsync_Cancel_ThrowsCancellationException(Uri server) in /_/src/libraries/System.Net.WebSockets.Client/tests/CancelTest.cs:line 27
--- End of stack trace from previous location ---
```

**Comment by CarnaViire** [comment] 2021-09-30 10:49
Seems like a dupe of https://github.com/dotnet/runtime/issues/58355

**Comment by karelz** [comment] 2021-09-30 11:16
Duplicate of #58355

**Closed by karelz** 2021-09-30 11:16 UTC
Labels: arch-arm64, arch-x86, area-System.Net.Sockets, os-linux, os-mac-os-x, os-windows, arch-x64, untriaged
