### ISSUE TITLE
[iOS] An SSL error when sending request to server with self-signed certificate

### ISSUE THREAD

**Issue by sikandaramla** [dotnet/runtime#85415] opened 2023-04-26 13:09 UTC
As suggested by @simonrozsival, I've set  ServerCertificateCustomValidationCallback =
        HttpClientHandler.DangerousAcceptAnyServerCertificateValidator and also set NSAllowsArbitraryLoads to true but I'm not able to get rid of the SSL error with the Self-signed certificate. I'm using .Net 7

              @IgorKravchenko10 I think there are two issues in the code you linked:
- I can't see that you would set a `ServerCertificateCustomValidationCallback` to bypass certificate validation anywhere in the code. I think you need to modify your `OnHttpClientCreating()` method to include:
```csharp
var handler = new HttpClientHandler
{
    ServerCertificateCustomValidationCallback =
        HttpClientHandler.DangerousAcceptAnyServerCertificateValidator,
};
var httpClient = new HttpClient(handler);
```
- on iOS you need to modify your Info.plist to make connections to servers with invalid certificates, for example by adding this snippet:
```xml
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
```
See https://developer.apple.com/documentation/security/preventing_insecure_network_connections for more information.

Does this solve your problem?

_Originally posted by @simonrozsival in https://github.com/dotnet/maui/issues/11225#issuecomment-1317175099_

**Comment by wfurt** [comment] 2023-04-26 18:21
-9816 is `errSSLClosedNoNotify` so it seems like peer may be closing the stream. This may be result of issues with trust. 
If you register real callback it would give you X509Chain. You can iterate the status for more info. I would recommend to do packet capture and look at the TLS handshake. 

You can also look at https://support.apple.com/en-us/HT210176

**Comment by sikandaramla** [comment] 2023-04-29 07:10
Hey, what info is required of me? I've added error details as suggested by @simonrozsival

**Comment by sikandaramla** [comment] 2023-05-02 17:52
> @sikandaramla Can you try making requests against https://self-signed.badssl.com? I can't reproduce the error against that server. If even that doesn't work, there's something wrong with your setup (maybe the Info.plist isn't correct or its previous version is cached in the `obj` directory?).
> 
> ```cs
> var handler = new HttpClientHandler
> {
>     ServerCertificateCustomValidationCallback =
>         HttpClientHandler.DangerousAcceptAnyServerCertificateValidator,
> };
> var httpClient = new HttpClient(handler);
> var response = await httpClient.GetAsync("https://self-signed.badssl.com");
> Console.WriteLine(response);
> ```
> 
> One more thing I can think of at the moment: doesn't the server also require some client certificate?

Hey @simonrozsival 

Let me try this site and get back to you. I've deleted obj folders many times so that's not an issue here. I don't think the issue is with the Info.plist either. I agree with the client-side certificate which I've placed and pointed out in the Android version but I couldn't find anything for iOS, do you have a link or something I can look at for MAUI iOS?

**Comment by simonrozsival** [comment] 2024-07-18 07:30
I tested this issue again with .NET 9 Preview 6 and I cannot reproduce the issue. I'm closing the issue now, @sikandaramla, but feel free to reopen it or open a new issue if you have more information that would allow me to reproduce the issue.

**Closed by simonrozsival** 2024-07-18 07:30 UTC
Labels: area-System.Net.Http, os-ios, needs-further-triage, needs-author-action
