### ISSUE TITLE
Configuration Binding Generator Initializes Suffixed Default Values Incorrectly

### ISSUE THREAD

**Issue by chrisoverzero** [dotnet/runtime#92773] opened 2023-09-28 15:34 UTC
### Description

When configuration binding generation is enabled by means of:

```xml
<EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
<Features>$(Features);InterceptorsPreview</Features>
```

…a project can fail to compile with this error message:

```
/app/repro/Microsoft.Extensions.Configuration.Binder.SourceGeneration/Microsoft.Extensions.Configuration.Binder.SourceGeneration.ConfigurationBindingGenerator/BindingExtensions.g.cs(87,25): e
rror CS0664: Literal of type double cannot be implicitly converted to type 'decimal'; use an 'M' suffix to create a literal of this type [/app/repro/repro.csproj]
```

### Reproduction Steps

Given the following project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
    <Features>$(Features);InterceptorsPreview</Features>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0-rtm.23477.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.0-rtm.23477.9" />
  </ItemGroup>

</Project>
```

…and the following Program.cs:

```csharp
using Microsoft.Extensions.Configuration;

var c = new ConfigurationBuilder().Build();
var x = c.GetSection("Anything").Get<Values>();
Console.WriteLine(x);

readonly record struct Values(int A, string B, decimal C = 2.30m);
```

…run `dotnet build` via SDK version "8.0.100-rtm.23477.37".

### Expected behavior

The compilation succeeds, and the value is bound from configuration.

### Actual behavior

Compilation fails with the following error:

```
/app/repro/Microsoft.Extensions.Configuration.Binder.SourceGeneration/Microsoft.Extensions.Configuration.Binder.SourceGeneration.ConfigurationBindingGenerator/BindingExtensions.g.cs(87,25): e
rror CS0664: Literal of type double cannot be implicitly converted to type 'decimal'; use an 'M' suffix to create a literal of this type [/app/repro/repro.csproj]
```

The line in question in the generated code appears here in a method named `InitializeValues` (but really `Initialize{typename}`):

```csharp
decimal C = 2.30;
if (configuration["C"] is string value2)
{
    C = ParseDecimal(value2, () => configuration.GetSection("C").Path);
}
```

### Regression?

I'm afraid I don't know.

### Configuration

.NET Version: 8.0.100-rtm.23477.37
OS and version: macOS 13.5.1 (22G90)
Architecture: x64
Specific?: No, I don't think so.
Blazor: ❌

### Other information

You know what, I just checked initializing `float C = 2.30f` as well, and it behaves the same.

```csharp
float C = 2.3;
if (configuration["C"] is string value2)
{
    C = ParseFloat(value2, () => configuration.GetSection("C").Path);
}
```

**Comment by ericstj** [comment] 2023-10-03 16:06
I confirmed this repro in the latest codebase.  We'll need to see what's missing from how we emit the default value.  Thanks for the report @chrisoverzero

**Comment by ericstj** [comment] 2023-10-06 22:20
So it would seem that JSON has a similar bug to this.  It doesn't produce code that doesn't compile, but it does produce code that loses precision.  Then using that code at runtime produces an exception.

Here's the JSON repro:
```C#
using System.Text.Json;
using System.Text.Json.Serialization;

var deserialized = JsonSerializer.Deserialize<MyPi>("{}", SourceGenerationContext.Default.MyPi);

Console.WriteLine(deserialized);

public struct MyPi
{
    [JsonConstructor]
    public MyPi(decimal value = 3.1415926535897932384626433M) { Value = value; }
    public decimal Value { get; }
}

[JsonSerializable(typeof(MyPi), GenerationMode = JsonSourceGenerationMode.Metadata)]
internal partial class SourceGenerationContext : JsonSerializerContext { }
```

This happens because JSON produces this:
```C#
    private static global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[] MyPiCtorParamInit()
    {
        var parameters = new global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[1];

        parameters[0] = new()
        {
            Name = "value",
            ParameterType = typeof(decimal),
            Position = 0,
            HasDefaultValue = true,
            DefaultValue = 3.1415926535897932384626433
        };
        
        return parameters;
    }
```
`DefaultValue` here is https://github.com/dotnet/runtime/blob/7b08680a92cbd8743b59db38e5120966a0b475aa/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonParameterInfoValues.cs#L43

That syntax results in initializing the `object` value to a boxed `double` which will throw at runtime:
```
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'System.Double' to type 'System.Decimal'.
   at System.Text.Json.Serialization.Metadata.JsonParameterInfo`1..ctor(JsonParameterInfoValues parameterInfoValues, JsonPropertyInfo`1 matchingPropertyInfo)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.CreateJsonParameterInfo(JsonParameterInfoValues parameterInfoValues)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.ConfigureConstructorParameters()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureSynchronized|170_0()
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Nullable`1 ensureNotNull, Boolean resolveIfMutable, Boolean fallBackToNearestAncestorType)
   at System.Text.Json.JsonSerializerOptions.GetTypeInfo(Type type)
   at SourceGenerationContext.get_MyPi() in C:\scratch\jsonDecimal\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\SourceGenerationContext.MyPi.g.cs:line 18
   at Program.<Main>$(String[] args) in C:\scratch\jsonDecimal\Program.cs:line 4
```

This is related to this issue, which was missing this case: https://github.com/dotnet/roslyn/issues/58705

I believe the fix here, needed for both Configuration and Json is refine and share our literal formatting helper:
https://github.com/dotnet/runtime/blob/7204fbe5f56d52dd3fc4238e33de45f532f05d50/src/libraries/System.Text.Json/gen/JsonSourceGenerator.Emitter.cs#L1354-L1403

CC @dotnet/area-system-text-json

**Comment by ericstj** [comment] 2023-10-07 01:42
I have a fix for this, but in testing it I hit https://github.com/dotnet/runtime/issues/93159.  I'll try to get the fix done for just this case and move on to that next.

**Comment by ericstj** [comment] 2023-10-10 13:41
@chrisoverzero is this issue blocking your adoption of the source generator in 8.0?

**Comment by chrisoverzero** [comment] 2023-10-10 13:46
It is not blocking me at this time, no. It’s something I discovered when doing reproduction for another issue.

**Comment by ericstj** [comment] 2023-10-10 13:55
Ok, closing this out for now, the fix will remain in the 9.0 codebase.

**Comment by ericstj** [comment] 2023-10-26 23:03
While the `decimal` case isn't common, this also fixed the formatting of Enums with default values with is much more common.  We should consider this for servicing.

**Comment by ericstj** [comment] 2024-07-22 21:00
This was serviced in https://github.com/dotnet/runtime/commit/213f1a24a078985c1e7ef14e425cdff291cde6f6

**Closed by ericstj** 2024-07-22 21:00 UTC
Labels: bug, area-Extensions-Configuration
