### ISSUE TITLE
NetworkStream.ReadAsync runs slower on ubuntu than on windows

### ISSUE THREAD

**Issue by sancheolz** [dotnet/runtime#90664] opened 2023-08-16 13:01 UTC
### Description

The following code runs in 2044 milliseconds on Windows 10 x64. On Ubuntu 22.04 x64 on the same hardware, it runs in 88732 milliseconds. The CoreRemoting nuget package is used here.
```cs
using System.Diagnostics;
using CoreRemoting;
//using CoreRemoting.Channels.Websocket;
using CoreRemoting.DependencyInjection;

namespace RemotingPerf
{
    public class Program
    {
        private static void Main(string[] args)
        {
            try
            {
                #region CoreRemoting

                new RemotingServer(new ServerConfig()
                {
                    RegisterServicesAction = container =>
                    {
                        container.RegisterService<ITestService, TestService>(ServiceLifetime.Singleton);
                    },
                    //Channel = new WebsocketServerChannel(),
                    MessageEncryption = false
                }).Start();
                
                var client = new RemotingClient(new ClientConfig
                {
                    //Channel = new WebsocketClientChannel(),
                    MessageEncryption = false
                });
                
                client.Connect();
                
                // Create a proxy of the remote service, which behaves almost like a regular local object
                var proxy = client.CreateProxy<ITestService>();

                #endregion

                int i = 0;
                var sw = Stopwatch.StartNew();
                while (i < 1000)
                {
                    proxy.TestMethod();
                    i++;
                }
                Console.WriteLine("Elapsed ms {0}", sw.ElapsedMilliseconds);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
        }
    }

    public class TestService : ITestService//, MarshalByRefObject
    {
        public void TestMethod()
        {
        }
    }

    public interface ITestService
    {
        void TestMethod();
    }
}
```

### Configuration

**Windows Configuration**

Runtime Environment:
OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.310\

global.json file:
  Not found

Host:
  Version:      6.0.15
  Architecture: x64
  Commit:       5edef4b20b

**Ubuntu Configuration**

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/lib/dotnet/sdk/6.0.120/

global.json file:
  Not found

Host:
  Version:      6.0.20
  Architecture: x64
  Commit:       a08d9ce2ca

### Analysis

After some searching, I found out that a significant part of the time on ubuntu is spent on this code in the WatsonTCP package.
[`read = await stream.ReadAsync(buffer, 0, buffer.Length);`](https://github.com/jchristn/WatsonTcp/blob/ec984fabd89516175398a51a1d9c66ba4df6dae4/src/WatsonTcp/WatsonCommon.cs#L114)
Here stream is a NetworkStream.
On windows, much less time is spent on it.

**Comment by wfurt** [comment] 2023-08-16 16:39
What is `WatsonTCP`? That is not part of runtime, right? So if suspect the problem is there please open issue appropriately. If you feel this is runtime problem please post complete runable repro with runtime only components. 

Did you try to get packet captures? There were issues like this in the past when there is mismatch between IPv4/V4.

**Comment by karelz** [comment] 2023-08-17 08:33
Also, it uses [CoreRemoting](https://www.nuget.org/packages/CoreRemoting) package, which is not part of .NET.

Closing. Feel free to reopen if there is .NET Libraries-only repro - ideally using [BenchmarkDotNet](https://benchmarkdotnet.org/) as perf measurement infra.

**Closed by karelz** 2023-08-17 08:33 UTC
Labels: area-System.Net.Sockets, tenet-performance, needs-author-action, needs-area-label

**Comment by sancheolz** [comment] 2023-08-22 08:49
Here the small repro with runtime only components.

```cs
using System.Diagnostics;
using System.Net;
using System.Net.Sockets;

namespace TcpClientPerf; 
internal class Program
{
    private static TcpClientTest _tcpClientTest;
    private static bool _all;
    private static int _countReceivedMessages;

    static void Main(string[] args)
    {
        var _tcpServer = new TcpServerTest();
        _tcpServer.Start();

        _tcpClientTest = new TcpClientTest();
        _tcpClientTest.MessageReceived += OnMessage;
        _tcpClientTest.Connect();
        var sw = Stopwatch.StartNew();
        _tcpClientTest.SendAsync();

        while (!_all)
        {
            Thread.Sleep(100);
        }

        Console.WriteLine($"_countReceivedMessages {_countReceivedMessages} elapsed {sw.ElapsedMilliseconds} ms");
    }

    private static void OnMessage(object sender, EventArgs e)
    {
        _tcpClientTest.SendAsync();
        if (Interlocked.Increment(ref _countReceivedMessages) > 10) _all = true;
        Console.WriteLine($"_countReceivedMessages {_countReceivedMessages}");
    }
}

public class TcpClientTest
{
    public event EventHandler<EventArgs> MessageReceived;

    private NetworkStream _DataStream;

    public void Connect()
    {
        var client = new TcpClient(AddressFamily.InterNetwork);

        var asyncResult = client.BeginConnect("127.0.0.1", 9090, null, null);
        var waitHandle = asyncResult.AsyncWaitHandle;
        waitHandle.WaitOne(TimeSpan.FromSeconds(5), false);

        client.EndConnect(asyncResult);
                    
        _DataStream = client.GetStream();

        Task.Run(() => DataReceiver());
    }

    public async Task SendAsync()
    {
        await TcpCommon.SendData(_DataStream);
    }
         
    private async Task DataReceiver()
    {
        while (true)
        {
            await TcpCommon.ReadMessageDataAsync(_DataStream, 16);
            await TcpCommon.ReadMessageDataAsync(_DataStream, 16).ConfigureAwait(false); 
            await Task.Run(() => MessageReceived?.Invoke(this, null));
        }
    }
}

public class TcpServerTest
{
    private TcpListener _Listener;
    private NetworkStream _NetworkStream;

    public void Start()
    {
        _Listener = new TcpListener(IPAddress.Loopback, 9090);
        _Listener.Start();
        Task.Run(() => AcceptConnections());
    }

    private async Task AcceptConnections()
    { 
        while (true)
        {
            TcpClient tcpClient = await _Listener.AcceptTcpClientAsync().ConfigureAwait(false);
            _NetworkStream = tcpClient.GetStream();
            Task.Run(() => DataReceiver());
        }
    }

    private async Task DataReceiver()
    {
        while (true)
        {
            await TcpCommon.ReadMessageDataAsync(_NetworkStream, 16);
            await TcpCommon.ReadMessageDataAsync(_NetworkStream, 16)
                .ConfigureAwait(false);
            await Task.Run(() => TcpCommon.SendData(_NetworkStream));
        }
    }
}

internal static class TcpCommon
{
    internal static async Task SendData(Stream networkStream)
    {
        await networkStream.WriteAsync(new byte[]{ 0x7b, 0x22, 0x6c, 0x65, 0x6e, 0x22, 0x3a, 0x33, 0x33, 0x30, 0x34, 0x7d, 0xd, 0xa, 0xd, 0xa}, 0, 16).ConfigureAwait(false);
        await networkStream.WriteAsync(new byte[]{ 0x7b, 0x22, 0x6c, 0x65, 0x6e, 0x22, 0x3a, 0x33, 0x33, 0x30, 0x34, 0x7d, 0xd, 0xa, 0xd, 0xa}, 0, 16).ConfigureAwait(false);
        await networkStream.FlushAsync().ConfigureAwait(false);
    }
    internal static async Task ReadMessageDataAsync(Stream stream, int count)
    {
        byte[] buffer = new byte[count];
        var ts = DateTime.UtcNow;
        await stream.ReadAsync(buffer, 0, buffer.Length);
        var time = DateTime.UtcNow - ts;
        Console.WriteLine("MessageReadTime " + time);
    }
}
```

<details><summary>Output from Windows 10 x64</summary>
<p>
MessageReadTime 00:00:00.0000874
MessageReadTime 00:00:00.0000262
MessageReadTime 00:00:00.0182856
MessageReadTime 00:00:00.0000198
MessageReadTime 00:00:00.0008676
MessageReadTime 00:00:00.0000093
_countReceivedMessages 1
MessageReadTime 00:00:00.0001461
MessageReadTime 00:00:00.0000041
MessageReadTime 00:00:00.0001389
MessageReadTime 00:00:00.0000036
_countReceivedMessages 2
MessageReadTime 00:00:00.0000806
MessageReadTime 00:00:00.0000035
MessageReadTime 00:00:00.0001191
MessageReadTime 00:00:00.0000034
_countReceivedMessages 3
MessageReadTime 00:00:00.0000792
MessageReadTime 00:00:00.0000035
MessageReadTime 00:00:00.0003133
MessageReadTime 00:00:00.0000062
_countReceivedMessages 4
MessageReadTime 00:00:00.0027197
MessageReadTime 00:00:00.0000210
MessageReadTime 00:00:00.0018642
MessageReadTime 00:00:00.0000049
_countReceivedMessages 5
MessageReadTime 00:00:00.0000061
MessageReadTime 00:00:00.0000059
MessageReadTime 00:00:00.0001854
MessageReadTime 00:00:00.0001168
_countReceivedMessages 6
MessageReadTime 00:00:00.0006040
MessageReadTime 00:00:00.0000068
MessageReadTime 00:00:00.0002680
MessageReadTime 00:00:00.0000050
_countReceivedMessages 7
MessageReadTime 00:00:00.0000053
MessageReadTime 00:00:00.0000053
_countReceivedMessages 8
MessageReadTime 00:00:00.0002133
MessageReadTime 00:00:00.0000983
MessageReadTime 00:00:00.0003896
MessageReadTime 00:00:00.0000064
MessageReadTime 00:00:00.0002033
MessageReadTime 00:00:00.0001613
_countReceivedMessages 9
MessageReadTime 00:00:00.0000824
MessageReadTime 00:00:00.0000057
MessageReadTime 00:00:00.0002317
MessageReadTime 00:00:00.0000057
_countReceivedMessages 10
MessageReadTime 00:00:00.0000054
MessageReadTime 00:00:00.0000047
MessageReadTime 00:00:00.0002127
_countReceivedMessages 11
MessageReadTime 00:00:00.0000041
MessageReadTime 00:00:00.0002046
MessageReadTime 00:00:00.0000030
MessageReadTime 00:00:00.0001998
_countReceivedMessages 12
MessageReadTime 00:00:00.0000055
MessageReadTime 00:00:00.0001944
MessageReadTime 00:00:00.0000026
MessageReadTime 00:00:00.0002431
_countReceivedMessages 13
MessageReadTime 00:00:00.0000063
MessageReadTime 00:00:00.0030642
MessageReadTime 00:00:00.0000114
MessageReadTime 00:00:00.0003385
MessageReadTime 00:00:00.0076009
_countReceivedMessages 14
MessageReadTime 00:00:00.0000151
MessageReadTime 00:00:00.0000066
MessageReadTime 00:00:00.0021366
MessageReadTime 00:00:00.0001469
_countReceivedMessages 15
MessageReadTime 00:00:00.0000060
MessageReadTime 00:00:00.0000053
MessageReadTime 00:00:00.0002169
MessageReadTime 00:00:00.0000054
_countReceivedMessages 16
MessageReadTime 00:00:00.0000054
MessageReadTime 00:00:00.0000053
MessageReadTime 00:00:00.0002254
MessageReadTime 00:00:00.0000035
_countReceivedMessages 17
MessageReadTime 00:00:00.0000055
MessageReadTime 00:00:00.0000052
_countReceivedMessages 18
MessageReadTime 00:00:00.0003237
MessageReadTime 00:00:00.0000054
MessageReadTime 00:00:00.0002781
MessageReadTime 00:00:00.0000056
MessageReadTime 00:00:00.0002265
MessageReadTime 00:00:00.0000049
_countReceivedMessages 19
MessageReadTime 00:00:00.0000053
MessageReadTime 00:00:00.0000051
MessageReadTime 00:00:00.0002070
MessageReadTime 00:00:00.0000057
_countReceivedMessages 20
MessageReadTime 00:00:00.0000053
MessageReadTime 00:00:00.0000046
_countReceivedMessages 21
MessageReadTime 00:00:00.0002497
MessageReadTime 00:00:00.0000141
MessageReadTime 00:00:00.0003253
MessageReadTime 00:00:00.0000057
MessageReadTime 00:00:00.0002241
MessageReadTime 00:00:00.0000047
_countReceivedMessages 22
MessageReadTime 00:00:00.0000053
MessageReadTime 00:00:00.0000052
MessageReadTime 00:00:00.0002149
MessageReadTime 00:00:00.0000055
_countReceivedMessages 23
MessageReadTime 00:00:00.0000052
MessageReadTime 00:00:00.0000049
MessageReadTime 00:00:00.0001460
_countReceivedMessages 24
MessageReadTime 00:00:00.0000038
MessageReadTime 00:00:00.0001148
MessageReadTime 00:00:00.0000026
MessageReadTime 00:00:00.0001273
_countReceivedMessages 25
MessageReadTime 00:00:00.0000045
MessageReadTime 00:00:00.0001204
MessageReadTime 00:00:00.0000053
MessageReadTime 00:00:00.0002122
_countReceivedMessages 26
MessageReadTime 00:00:00.0000044
MessageReadTime 00:00:00.0001348
MessageReadTime 00:00:00.0000053
MessageReadTime 00:00:00.0001677
_countReceivedMessages 27
MessageReadTime 00:00:00.0000037
MessageReadTime 00:00:00.0001110
MessageReadTime 00:00:00.0000043
MessageReadTime 00:00:00.0001684
MessageReadTime 00:00:00.0000047
_countReceivedMessages 28
MessageReadTime 00:00:00.0000057
MessageReadTime 00:00:00.0000183
MessageReadTime 00:00:00.0003292
_countReceivedMessages 29
MessageReadTime 00:00:00.0000039
MessageReadTime 00:00:00.0001366
MessageReadTime 00:00:00.0000026
MessageReadTime 00:00:00.0001444
_countReceivedMessages 30
MessageReadTime 00:00:00.0000047
MessageReadTime 00:00:00.0001444
MessageReadTime 00:00:00.0000053
MessageReadTime 00:00:00.0001610
_countReceivedMessages 31
MessageReadTime 00:00:00.0000044
MessageReadTime 00:00:00.0001452
MessageReadTime 00:00:00.0000052
MessageReadTime 00:00:00.0001284
MessageReadTime 00:00:00.0000041
_countReceivedMessages 32
MessageReadTime 00:00:00.0000058
MessageReadTime 00:00:00.0000166
MessageReadTime 00:00:00.0003407
_countReceivedMessages 33
MessageReadTime 00:00:00.0000034
MessageReadTime 00:00:00.0001372
MessageReadTime 00:00:00.0000054
MessageReadTime 00:00:00.0001391
_countReceivedMessages 34
MessageReadTime 00:00:00.0000040
MessageReadTime 00:00:00.0001767
MessageReadTime 00:00:00.0000040
MessageReadTime 00:00:00.0000802
_countReceivedMessages 35
MessageReadTime 00:00:00.0000037
MessageReadTime 00:00:00.0001707
MessageReadTime 00:00:00.0000052
MessageReadTime 00:00:00.0001741
_countReceivedMessages 36
MessageReadTime 00:00:00.0000042
MessageReadTime 00:00:00.0001217
MessageReadTime 00:00:00.0000046
MessageReadTime 00:00:00.0001766
_countReceivedMessages 37
MessageReadTime 00:00:00.0000043
MessageReadTime 00:00:00.0001206
MessageReadTime 00:00:00.0000026
MessageReadTime 00:00:00.0011989
MessageReadTime 00:00:00.0000075
_countReceivedMessages 38
MessageReadTime 00:00:00.0000174
MessageReadTime 00:00:00.0000213
MessageReadTime 00:00:00.0040349
MessageReadTime 00:00:00.0000070
_countReceivedMessages 39
MessageReadTime 00:00:00.0000071
MessageReadTime 00:00:00.0000053
MessageReadTime 00:00:00.0004153
MessageReadTime 00:00:00.0000047
_countReceivedMessages 40
MessageReadTime 00:00:00.0000061
MessageReadTime 00:00:00.0000126
MessageReadTime 00:00:00.0003782
MessageReadTime 00:00:00.0000046
_countReceivedMessages 41
MessageReadTime 00:00:00.0000047
MessageReadTime 00:00:00.0000050
MessageReadTime 00:00:00.0003671
MessageReadTime 00:00:00.0000044
_countReceivedMessages 42
MessageReadTime 00:00:00.0000066
MessageReadTime 00:00:00.0000063
MessageReadTime 00:00:00.0003332
MessageReadTime 00:00:00.0000058
_countReceivedMessages 43
MessageReadTime 00:00:00.0000066
MessageReadTime 00:00:00.0000055
MessageReadTime 00:00:00.0004154
MessageReadTime 00:00:00.0000047
_countReceivedMessages 44
MessageReadTime 00:00:00.0000065
MessageReadTime 00:00:00.0000065
MessageReadTime 00:00:00.0003973
_countReceivedMessages 45
MessageReadTime 00:00:00.0150583
MessageReadTime 00:00:00.0002759
MessageReadTime 00:00:00.0000060
MessageReadTime 00:00:00.0002345
MessageReadTime 00:00:00.0000047
_countReceivedMessages 46
MessageReadTime 00:00:00.0000050
MessageReadTime 00:00:00.0000773
MessageReadTime 00:00:00.0001473
MessageReadTime 00:00:00.0000047
_countReceivedMessages 47
MessageReadTime 00:00:00.0000057
MessageReadTime 00:00:00.0000053
MessageReadTime 00:00:00.0001302
_countReceivedMessages 48
MessageReadTime 00:00:00.0000042
MessageReadTime 00:00:00.0001318
MessageReadTime 00:00:00.0000053
MessageReadTime 00:00:00.0001618
MessageReadTime 00:00:00.0000050
_countReceivedMessages 49
MessageReadTime 00:00:00.0001158
MessageReadTime 00:00:00.0000045
MessageReadTime 00:00:00.0001526
MessageReadTime 00:00:00.0000048
_countReceivedMessages 50
MessageReadTime 00:00:00.0000044
MessageReadTime 00:00:00.0000031
_countReceivedMessages 51
MessageReadTime 00:00:00.0001449
MessageReadTime 00:00:00.0000057
MessageReadTime 00:00:00.0002364
MessageReadTime 00:00:00.0000044
MessageReadTime 00:00:00.0001925
_countReceivedMessages 52
MessageReadTime 00:00:00.0000036
MessageReadTime 00:00:00.0001413
MessageReadTime 00:00:00.0000057
MessageReadTime 00:00:00.0001495
_countReceivedMessages 53
MessageReadTime 00:00:00.0000046
MessageReadTime 00:00:00.0001344
MessageReadTime 00:00:00.0000056
MessageReadTime 00:00:00.0001488
MessageReadTime 00:00:00.0000039
_countReceivedMessages 54
MessageReadTime 00:00:00.0000054
MessageReadTime 00:00:00.0000058
MessageReadTime 00:00:00.0002468
MessageReadTime 00:00:00.0000052
_countReceivedMessages 55
MessageReadTime 00:00:00.0000053
MessageReadTime 00:00:00.0000043
MessageReadTime 00:00:00.0001523
_countReceivedMessages 56
MessageReadTime 00:00:00.0000055
MessageReadTime 00:00:00.0001601
MessageReadTime 00:00:00.0000026
MessageReadTime 00:00:00.0001623
_countReceivedMessages 57
MessageReadTime 00:00:00.0000036
MessageReadTime 00:00:00.0001256
MessageReadTime 00:00:00.0000038
MessageReadTime 00:00:00.0001046
_countReceivedMessages 58
MessageReadTime 00:00:00.0000045
MessageReadTime 00:00:00.0002315
MessageReadTime 00:00:00.0000047
MessageReadTime 00:00:00.0002958
_countReceivedMessages 59
MessageReadTime 00:00:00.0000045
MessageReadTime 00:00:00.0002421
MessageReadTime 00:00:00.0000084
MessageReadTime 00:00:00.0002302
_countReceivedMessages 60
MessageReadTime 00:00:00.0000030
MessageReadTime 00:00:00.0001662
MessageReadTime 00:00:00.0000069
MessageReadTime 00:00:00.0002541
_countReceivedMessages 61
MessageReadTime 00:00:00.0000036
MessageReadTime 00:00:00.0001986
MessageReadTime 00:00:00.0000070
MessageReadTime 00:00:00.0002535
_countReceivedMessages 62
MessageReadTime 00:00:00.0000066
MessageReadTime 00:00:00.0002405
MessageReadTime 00:00:00.0060525
MessageReadTime 00:00:00.0065279
MessageReadTime 00:00:00.0175038
_countReceivedMessages 63
MessageReadTime 00:00:00.0001899
MessageReadTime 00:00:00.0000060
MessageReadTime 00:00:00.0002184
MessageReadTime 00:00:00.0000049
_countReceivedMessages 64
MessageReadTime 00:00:00.0000084
MessageReadTime 00:00:00.0001422
MessageReadTime 00:00:00.0001717
MessageReadTime 00:00:00.0000048
_countReceivedMessages 65
MessageReadTime 00:00:00.0000052
MessageReadTime 00:00:00.0001591
MessageReadTime 00:00:00.0001495
MessageReadTime 00:00:00.0000046
_countReceivedMessages 66
MessageReadTime 00:00:00.0001170
MessageReadTime 00:00:00.0000047
MessageReadTime 00:00:00.0001449
MessageReadTime 00:00:00.0000044
_countReceivedMessages 67
MessageReadTime 00:00:00.0000054
MessageReadTime 00:00:00.0000057
MessageReadTime 00:00:00.0002431
MessageReadTime 00:00:00.0000045
_countReceivedMessages 68
MessageReadTime 00:00:00.0000052
MessageReadTime 00:00:00.0000053
_countReceivedMessages 69
MessageReadTime 00:00:00.0002453
MessageReadTime 00:00:00.0000062
MessageReadTime 00:00:00.0003191
MessageReadTime 00:00:00.0001688
MessageReadTime 00:00:00.0000915
MessageReadTime 00:00:00.0001645
_countReceivedMessages 70
MessageReadTime 00:00:00.0000054
MessageReadTime 00:00:00.0000053
MessageReadTime 00:00:00.0003869
MessageReadTime 00:00:00.0001939
_countReceivedMessages 71
MessageReadTime 00:00:00.0000054
MessageReadTime 00:00:00.0000045
MessageReadTime 00:00:00.0012022
MessageReadTime 00:00:00.0077868
_countReceivedMessages 72
MessageReadTime 00:00:00.0126719
MessageReadTime 00:00:00.0000145
MessageReadTime 00:00:00.0007546
MessageReadTime 00:00:00.0000063
_countReceivedMessages 73
MessageReadTime 00:00:00.0001890
MessageReadTime 00:00:00.0000080
MessageReadTime 00:00:00.0003202
MessageReadTime 00:00:00.0000052
_countReceivedMessages 74
MessageReadTime 00:00:00.0002111
MessageReadTime 00:00:00.0000055
MessageReadTime 00:00:00.0002867
MessageReadTime 00:00:00.0000055
_countReceivedMessages 75
MessageReadTime 00:00:00.0001359
MessageReadTime 00:00:00.0000052
MessageReadTime 00:00:00.0002344
MessageReadTime 00:00:00.0000055
_countReceivedMessages 76
MessageReadTime 00:00:00.0001338
MessageReadTime 00:00:00.0000052
MessageReadTime 00:00:00.0012052
MessageReadTime 00:00:00.0000071
_countReceivedMessages 77
MessageReadTime 00:00:00.0001567
MessageReadTime 00:00:00.0000059
MessageReadTime 00:00:00.0002599
MessageReadTime 00:00:00.0000053
_countReceivedMessages 78
MessageReadTime 00:00:00.0002256
MessageReadTime 00:00:00.0000037
MessageReadTime 00:00:00.0002648
MessageReadTime 00:00:00.0000051
_countReceivedMessages 79
MessageReadTime 00:00:00.0001328
MessageReadTime 00:00:00.0000050
MessageReadTime 00:00:00.0002240
MessageReadTime 00:00:00.0000097
_countReceivedMessages 80
MessageReadTime 00:00:00.0081279
MessageReadTime 00:00:00.0000094
MessageReadTime 00:00:00.0006774
MessageReadTime 00:00:00.0000067
_countReceivedMessages 81
MessageReadTime 00:00:00.0000328
MessageReadTime 00:00:00.0000074
MessageReadTime 00:00:00.0007225
MessageReadTime 00:00:00.0000064
_countReceivedMessages 82
MessageReadTime 00:00:00.0000076
MessageReadTime 00:00:00.0000067
MessageReadTime 00:00:00.0004773
MessageReadTime 00:00:00.0000070
_countReceivedMessages 83
MessageReadTime 00:00:00.0000077
MessageReadTime 00:00:00.0000066
MessageReadTime 00:00:00.0004994
MessageReadTime 00:00:00.0000050
_countReceivedMessages 84
MessageReadTime 00:00:00.0000053
MessageReadTime 00:00:00.0000060
MessageReadTime 00:00:00.0004582
MessageReadTime 00:00:00.0000050
_countReceivedMessages 85
MessageReadTime 00:00:00.0000102
MessageReadTime 00:00:00.0000061
MessageReadTime 00:00:00.0004486
MessageReadTime 00:00:00.0000058
_countReceivedMessages 86
MessageReadTime 00:00:00.0000158
MessageReadTime 00:00:00.0000058
MessageReadTime 00:00:00.0005165
MessageReadTime 00:00:00.0000046
_countReceivedMessages 87
MessageReadTime 00:00:00.0000069
MessageReadTime 00:00:00.0000063
MessageReadTime 00:00:00.0004684
MessageReadTime 00:00:00.0000052
_countReceivedMessages 88
MessageReadTime 00:00:00.0000052
MessageReadTime 00:00:00.0000050
MessageReadTime 00:00:00.0003917
MessageReadTime 00:00:00.0000045
_countReceivedMessages 89
MessageReadTime 00:00:00.0000124
MessageReadTime 00:00:00.0000097
MessageReadTime 00:00:00.0011640
MessageReadTime 00:00:00.0003132
_countReceivedMessages 90
MessageReadTime 00:00:00.0001805
MessageReadTime 00:00:00.0000041
MessageReadTime 00:00:00.0002490
MessageReadTime 00:00:00.0000046
_countReceivedMessages 91
MessageReadTime 00:00:00.0001559
MessageReadTime 00:00:00.0000035
MessageReadTime 00:00:00.0124380
MessageReadTime 00:00:00.0000099
_countReceivedMessages 92
MessageReadTime 00:00:00.0001740
MessageReadTime 00:00:00.0000987
MessageReadTime 00:00:00.0013623
MessageReadTime 00:00:00.0000086
_countReceivedMessages 93
MessageReadTime 00:00:00.0000059
MessageReadTime 00:00:00.0000047
_countReceivedMessages 94
MessageReadTime 00:00:00.0029750
MessageReadTime 00:00:00.0000195
MessageReadTime 00:00:00.0228637
MessageReadTime 00:00:00.0000096
_countReceivedMessages 95
_countReceivedMessages 94 elapsed 247 ms
MessageReadTime 00:00:00.0818805
MessageReadTime 00:00:00.0000422
MessageReadTime 00:00:00.0032021
MessageReadTime 00:00:00.0000071
_countReceivedMessages 96
MessageReadTime 00:00:00.0043444
MessageReadTime 00:00:00.0000140
</p>
</details> 

<details><summary>Output from Ubuntu 22.04</summary>
<p>
MessageReadTime 00:00:00.0006965
MessageReadTime 00:00:00.0000343
MessageReadTime 00:00:00.0322437
MessageReadTime 00:00:00.0000071
MessageReadTime 00:00:00.0009366
_countReceivedMessages 1
MessageReadTime 00:00:00.0437536
MessageReadTime 00:00:00.0439251
MessageReadTime 00:00:00.0471753
_countReceivedMessages 2
MessageReadTime 00:00:00.0479710
MessageReadTime 00:00:00.0436464
MessageReadTime 00:00:00.0441246
MessageReadTime 00:00:00.0438000
MessageReadTime 00:00:00.0441034
_countReceivedMessages 3
MessageReadTime 00:00:00.0562547
MessageReadTime 00:00:00.0562089
MessageReadTime 00:00:00.0425442
_countReceivedMessages 4
MessageReadTime 00:00:00.0440013
MessageReadTime 00:00:00.0432311
MessageReadTime 00:00:00.0439555
MessageReadTime 00:00:00.0435444
_countReceivedMessages 5
MessageReadTime 00:00:00.0438237
MessageReadTime 00:00:00.0437165
MessageReadTime 00:00:00.0443037
MessageReadTime 00:00:00.0435517
_countReceivedMessages 6
MessageReadTime 00:00:00.0444335
MessageReadTime 00:00:00.0435110
MessageReadTime 00:00:00.0444429
MessageReadTime 00:00:00.0435253
MessageReadTime 00:00:00.0440612
_countReceivedMessages 7
MessageReadTime 00:00:00.0485045
MessageReadTime 00:00:00.0487849
MessageReadTime 00:00:00.0429391
_countReceivedMessages 8
MessageReadTime 00:00:00.0433903
MessageReadTime 00:00:00.0436227
MessageReadTime 00:00:00.0444621
MessageReadTime 00:00:00.0434473
_countReceivedMessages 9
MessageReadTime 00:00:00.0440257
MessageReadTime 00:00:00.0440333
MessageReadTime 00:00:00.0441363
MessageReadTime 00:00:00.0480099
_countReceivedMessages 10
MessageReadTime 00:00:00.0483017
MessageReadTime 00:00:00.0477322
MessageReadTime 00:00:00.0481266
MessageReadTime 00:00:00.0435546
_countReceivedMessages 11
MessageReadTime 00:00:00.0444523
MessageReadTime 00:00:00.0431531
MessageReadTime 00:00:00.0439868
_countReceivedMessages 11 elapsed 1024 ms
MessageReadTime 00:00:00.0438073
_countReceivedMessages 12
MessageReadTime 00:00:00.0441487
MessageReadTime 00:00:00.0436357
MessageReadTime 00:00:00.0439488
MessageReadTime 00:00:00.0499445
_countReceivedMessages 13
MessageReadTime 00:00:00.0686116
</p>
</details> 
 
On Ubuntu test takes 1024 ms and on Windows it takes 247 ms. On both OSes IPv6 turned off. I can do packet capture using wireshark if necessary

**Comment by sancheolz** [comment] 2023-08-22 18:29
@karelz I can not reopen this issue. Should I open another?

**Comment by wfurt** [comment] 2023-08-22 19:07
add this to your code:
```diff
    private async Task AcceptConnections()
    {
        while (true)
        {
            TcpClient tcpClient = await _Listener.AcceptTcpClientAsync().ConfigureAwait(false);
+           tcpClient.Client.NoDelay = true;

    public void Connect()
    {
        var client = new TcpClient(AddressFamily.InterNetwork);
+       client.Client.NoDelay = true;
```

I think you may be victim of Nagle's algorithm for small messages. 
It drops from  908ms to 101 ms on my Linux VM
