### ISSUE TITLE
Unable to build System.Runtime.WindowsRuntime

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#33721] opened 2020-03-18 15:11 UTC
I just did a clean, sync, and full rebuild.  When I now try to build System.Runtime.WindowsRuntime, I get this error:
```
d:\repos\runtime\src\libraries\System.Runtime.WindowsRuntime\src>d:\repos\runtime\dotnet msbuild /t:rebuild
D:\repos\runtime\.dotnet
Microsoft (R) Build Engine version 16.6.0-preview-20126-02+13cfe7fc5 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Users\stoub\.nuget\packages\microsoft.dotnet.build.tasks.targetframework.sdk\5.0.0-beta.20167.1\build\Microsoft.DotNet.Build.Tasks.TargetFramework.Sdk.targets(84,5): error : Not able to find a compatible supported target framework for netstandard1.0 in Project System.Runtime.WindowsRuntime.csproj. The Supported Configurations are netcoreapp5.0, netstandard2.0 [d:\repos\runtime\src\libraries\System.Runtime.WindowsRuntime\src\System.Runtime.WindowsRuntime.csproj]
C:\Users\stoub\.nuget\packages\microsoft.dotnet.build.tasks.targetframework.sdk\5.0.0-beta.20167.1\build\Microsoft.DotNet.Build.Tasks.TargetFramework.Sdk.targets(84,5): error : Not able to find a compatible supported target framework for netstandard1.2 in Project System.Runtime.WindowsRuntime.csproj. The Supported Configurations are netcoreapp5.0, netstandard2.0 [d:\repos\runtime\src\libraries\System.Runtime.WindowsRuntime\src\System.Runtime.WindowsRuntime.csproj]
  Restore completed in 42.75 ms for d:\repos\runtime\src\libraries\restore\winrt\winrt.depproj.
  Restore completed in 8.25 ms for d:\repos\runtime\src\libraries\restore\winrt\winrt.depproj.
```
cc: @Anipik, @ViktorHofer

**Comment by ViktorHofer** [comment] 2020-03-18 15:17
@ericstj @Anipik the TargetFramework filtering is broken, it shouldn't build for netstandard1.0. Possibly the result of https://github.com/dotnet/arcade/commit/7da8e04ee543aaf13777cea14f8de831af5f4c40?

**Comment by ericstj** [comment] 2020-03-18 15:58
Why is it restoring a src project?  This is restore failing I believe.

**Comment by Anipik** [comment] 2020-03-18 18:31
Taking a look here

**Comment by Anipik** [comment] 2020-03-18 23:14
The failure is not linked with https://github.com/dotnet/arcade/commit/7da8e04ee543aaf13777cea14f8de831af5f4c40
as it hadnt made it through.

The Problem is more general. Clean target is not running properly, clean outerbuild target triggers clean for all project tfms which end up calling P2preferences for each tfm. this p2p reference calls fails for netstandard tfms. This is the reason why this failure is not seen on ci as we dont run the clean target

We should not be resolving project references during clean. I have a fix for it and will be putting up the pr in a short while.

**Closed** 2020-03-24 14:18 UTC
Labels: area-Infrastructure
