### ISSUE TITLE
[API Proposal]: Expose response status code in WebSocketException for WebSocketError.NotAWebSocket case

### ISSUE THREAD

**Issue by IlyaBiryukov** [dotnet/runtime#72976] opened 2022-07-28 00:59 UTC
### Background and motivation

When client web socket connection fails to switch protocols, e.g. due to 401, 403, 429, or 500 errors, the client may want to know the details of the server response status code. 

### API Proposal

```csharp
namespace System.Net.WebSockets;

public class WebSocketException : Win32Exception
{
    public int? ResponseStatusCode { get; internal set; }
}
```

### API Usage

```csharp
try
{
    var socket = new ClientWebSocket();
    await socket.ConnectAsync(uri, cancellation);
}
catch (WebSocketException wse) when (wse.WebSocketErrorCode == WebSocketError.NotAWebSocket)
{
    Console.WriteLine($"Couldn't connect to web socket service. Status code: {wse.ResponseStatusCode}");
}
```

### Alternative Designs

Use `WebSocketException` constructors with `nativeError` and pass in the response status code as native error. The downside is that the native error is expected to be an HResult, not an HTTP response status code.

### Risks

Low risks.

**Comment by MihaZupan** [comment] 2022-07-28 01:02
This has been added for 7.0 as part of https://github.com/dotnet/runtime/issues/25918#issuecomment-1132039238.

You have to set `ClientWebSocketOptions.CollectHttpResponseDetails = true` and then look at `ClientWebSocket.HttpStatusCode`.

**Comment by CarnaViire** [comment] 2022-07-28 10:51
Duplicate of #25918

**Closed by CarnaViire** 2022-07-28 10:52 UTC
Labels: api-suggestion, area-System.Net, untriaged
