### ISSUE TITLE
NetworkInterface.GetAllNetworkInterfaces() not returning all interfaces

### ISSUE THREAD

**Issue by Remorc** [dotnet/runtime#1028] opened 2019-12-18 15:58 UTC
# NetworkInterface.GetAllNetworkInterfaces() not returning all interfaces

# General

I am working on migrating a code base from mono to dotnet core. I am attempting to get all of the network interfaces on my machine, including can0 and vcan0. I am calling NetworkInterface.GetAllNetworkInterfaces() to get all of the interfaces.

Here is an article that might be relevant? https://stackoverflow.com/questions/48246451/networkinterface-getallnetworkinterfaces-method-doesnt-match-all-the-results

Also worth noting that using mono works as expected.

 Here is what `ip link` returns:

```shell
debian@my-debian-machine:~$ ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: can0: <NOARP,UP,LOWER_UP,ECHO> mtu 16 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 10
    link/can
3: eth0: <BROADCAST,MULTICAST,DYNAMIC,UP,LOWER_UP> mtu 1430 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether b0:d5:cc:fd:92:b0 brd ff:ff:ff:ff:ff:ff
4: usb0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT group default qlen 1000
    link/ether b0:d5:cc:fd:92:b2 brd ff:ff:ff:ff:ff:ff
5: usb1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN mode DEFAULT group default qlen 1000
    link/ether b0:d5:cc:fd:92:b5 brd ff:ff:ff:ff:ff:ff
6: vcan0: <NOARP,UP,LOWER_UP> mtu 72 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/can
```

# Expected Behavior

All interfaces should be returned (lo, can0, eth0, usb0, usb1, vcan0)

# Actual Behavior

Only interfaces with, as I believe, MAC addresses are returned (lo, eth0, usb0, usb1)

edit: I forgot to add that I am running on Linux and seeing this issue

**Comment by danmosemsft** [comment] 2019-12-18 23:58
@Remorc what version of .NET Core are you using? If not 3.0 or 3.1, can you please confirm it reproduces with one of those?

**Comment by Remorc** [comment] 2019-12-19 12:58
@danmosemsft I am targeting .NET Core 3.0, but I also tried 3.1 and got the same results.

**Comment by wfurt** [comment] 2020-01-14 21:33
I think this is dup of https://github.com/dotnet/corefx/issues/41515 and fixed by https://github.com/dotnet/corefx/pull/41490. Old code would skip any interface without IP address.
You can check 5.0 daily builds.

**Comment by wfurt** [comment] 2020-01-24 08:41
Did you have a chance to try daily build @Remorc?  I'm inclined to close this as dup.

**Comment by wfurt** [comment] 2020-01-31 05:24
duplicate of  dotnet/corefx#41515

**Closed by wfurt** 2020-01-31 05:24 UTC
Labels: area-System.Net, os-linux, tenet-compatibility
