### ISSUE TITLE
XML Serialization issue (Null reference exeption) when transferring data from server to client

### ISSUE THREAD

**Issue by cap-gsvetov** [dotnet/runtime#47654] opened 2021-01-27 17:55 UTC
We are getting an error while transferring a serialized Xml object when running the application in the ASP.NET Core Blazor Server hosting mode. We have tried very simple XML objects, and get the same error. Looks like the issue is on the deserialization side. The error only happens when we deploy the server side with Docker. When running in Visual Studio, everything is fine. We have examined the DLLs, comparing VS Builds verses published folder and really can't see any differences

[Errors with Docker.pdf](https://github.com/dotnet/aspnetcore/files/5882126/Errors.with.Docker.pdf)

@danmosemsft, @eerhardt

**Comment by cap-gsvetov** [comment] 2021-02-01 19:55
The error shows in the stack trace to be in blazor.webassembly.js, no line number is provided, see below

![image](https://user-images.githubusercontent.com/53909870/106510849-18911c80-6495-11eb-9dec-cbe505a325ed.png)

**Comment by danmoseley** [comment] 2021-02-19 22:20
@marek-safar should this indeed go to serialization folks first or may be a more general problem?

**Comment by marek-safar** [comment] 2021-02-23 08:46
This is quite possibly linker serialization issue

**Comment by cap-gsvetov** [comment] 2021-02-23 15:54
I am the original poster - Is that something we can remedy or work around or look at on our side?

**Comment by eerhardt** [comment] 2021-02-23 16:19
@cap-gsvetov - it would be great if you had a .zip or a GH repository of a program illustrating the problem. That way we could reproduce it on our end and see exactly what the issue is.

**Comment by LaughingJohn** [comment] 2021-07-14 14:50
Apologies for jumping on, but I just thought I'd mention I have a problem that sounds suspiciously similar to this one which appears to be related to code trimming.

I added this to my .csproj to solve the issue:

See: [](https://github.com/dotnet/aspnetcore/issues/34337)

**Comment by eerhardt** [comment] 2021-07-14 16:52
I believe this was fixed with https://github.com/dotnet/runtime/pull/44772. I've tried using XmlSerializer in a trimmed app, and it works for me. We even have some simple trimming tests to ensure it continues to work:

https://github.com/dotnet/runtime/blob/fa779e8cb2b5868a0ac2fd4215f39ffb91f0dab0/src/libraries/System.Private.Xml/tests/TrimmingTests/XmlSerializer.Deserialize.cs#L19-L35

Closing. Please re-open if this still repros with the latest 6.0 builds.

**Closed by eerhardt** 2021-07-14 16:52 UTC
Labels: area-Serialization, untriaged
