### ISSUE TITLE
[Proposal] Add new overload to Uri.EscapeDataString

### ISSUE THREAD

**Issue by stevejgordon** [dotnet/runtime#40603] opened 2020-08-10 07:30 UTC
Updated by @MihaZupan on 2024-01-15.

## Background and Motivation

In low allocation scenarios, it may be useful to support escaping URI data into an existing `Span<char>` buffer, rather than allocating a new `string`. 

As an example, see this [performance improvement](https://github.com/elastic/elasticsearch-net/issues/4951) suggestion for Elasticsearch.NET. The proposed change removes allocations on a hot path for query string building. It uses the existing `Uri.EscapeDataString` method which allocates a new string, only when the input contains characters that need encoding. This could be avoided if I were able to encode directly into the buffer rented from the `ArrayPool`.

## Proposed API

```c#
namespace System
{
    partial class Uri
    {
        // Existing
        public static string EscapeDataString(string stringToEscape);
        public static string UnescapeDataString(string stringToUnescape);

        // New
        public static string EscapeDataString(ReadOnlySpan<char> charsToEscape);
        public static bool TryEscapeDataString(ReadOnlySpan<char> charsToEscape, Span<char> destination, out int charsWritten);

        public static string UnescapeDataString(ReadOnlySpan<char> charsToUnescape);
        public static bool TryUnescapeDataString(ReadOnlySpan<char> charsToUnescape, Span<char> destination, out int charsWritten);
    }
}
```

## Usage Examples

The `foreach` loop from the linked issue could then be re-written along the lines of:

```c#
foreach (var key in nv.AllKeys)
{
    if (position != 1)
        bufferSpan[position++] = '&';

    // assume we are sure we have space in the destination
    if (Uri.TryEscapeDataString(key, bufferSpan.Slice(position), out var charsWritten))
        position += charsWritten;

    var value = nv[key];
    if (!value.IsNullOrEmpty())
    {
        bufferSpan[position++] = '=';
        if (Uri.TryEscapeDataString(value, bufferSpan.Slice(position), out charsWritten))
            position += charsWritten;
    }
}
```

In cases where the keys/values contain reserved characters, this avoids the temporary string allocations.

## Alternative Designs

1. 
    The existing method names contain `string`.
    Is it okay for the new span-based overloads to share the same name for better discoverability, or should we consider alternative names, e.g. `EscapeData` / `EscapeDataChars`?
1.
    The above design follows other `Span<T>` based overloads I have seen in common use and assumes that the operation could fail if the destination is too small. An alternative would be to throw in that case and instead apply the following signature (where the return value indicates the chars written):
    ```c#
    public static int EscapeDataString(ReadOnlySpan<char> stringToEscape, Span<char> destination);
    ```

**Comment by MihaZupan** [comment] 2021-05-10 13:10
I would expect this API to only be used in cases like the one you described above - manually optimizing the concatenation of query string parts.

Given that that would be the only use case, would having `QueryHelper` (#32606) APIs be preferable?
Regardless of the public API, that can be more efficient in the final ToString/Serialize operation than what is reasonably achievable today.

**Comment by karelz** [comment] 2021-06-16 10:18
@stevejgordon any thoughts on the above?

**Comment by stevejgordon** [comment] 2021-06-16 12:36
@MihaZupan and @karelz sorry I missed the notification on the original reply.

The `QueryHelper` proposal looks useful and sounds like it could work for us in general terms. We essentially have two `NameValueCollection`s which we combine and then format a final query string value from them. My only concern would be the [comment](https://github.com/dotnet/runtime/issues/32606#issuecomment-589897073) which suggests that API would focus more on general usability rather than low allocations. 

Our approach can certainly be further optimised and I feel the above API would still be useful in more advanced cases. It would be interesting to compare its performance against `QueryBuilder` if that is also approved.

**Comment by MihaZupan** [comment] 2022-09-13 11:52
Marked #54828 as a duplicate of this since we'd likely want to match span support for `EscapeDataString` and `UnescapeDataString`.

It looks like there's a bit more community interest here, optimistically moving to 8.0

**Comment by karelz** [comment] 2023-06-09 14:08
Sadly, we won't make it in 8.0 due to circumstances. Moving to Future for now.

**Comment by MihaZupan** [comment] 2024-01-15 21:47
I've updated the proposal to include both the `string Foo(ROS<char>)` and `bool TryFoo(ROS<char>, Span<char>, out int)` overloads, for both `EscapeDataString` and `UnescapeDataString`.
Also updated the parameter names from `string-` to `chars-`, but we can discuss more in API review.

@dotnet/ncl Marking this one as ready for review, scream if you disagree :)

A few more uses in YARP and ASP.NET Core:
- https://github.com/microsoft/reverse-proxy/blob/379671ef2afd01e55168929c33c6b5cbcd0b06b0/src/ReverseProxy/Forwarder/RequestUtilities.cs#L177
- https://github.com/dotnet/aspnetcore/blob/60ebe2da0246c271133ab0a98a991e5099393e39/src/Shared/QueryStringEnumerable.cs#L102
- https://github.com/dotnet/aspnetcore/blob/60ebe2da0246c271133ab0a98a991e5099393e39/src/Http/Http.Abstractions/src/PathString.cs#L106

**Comment by bartonjs** [comment] 2024-02-06 18:37
Looks good as proposed

```C#
namespace System
{
    partial class Uri
    {
        // Existing
        public static string EscapeDataString(string stringToEscape);
        public static string UnescapeDataString(string stringToUnescape);

        // New
        public static string EscapeDataString(ReadOnlySpan<char> charsToEscape);
        public static bool TryEscapeDataString(ReadOnlySpan<char> charsToEscape, Span<char> destination, out int charsWritten);

        public static string UnescapeDataString(ReadOnlySpan<char> charsToUnescape);
        public static bool TryUnescapeDataString(ReadOnlySpan<char> charsToUnescape, Span<char> destination, out int charsWritten);
    }
}
```

**Closed** 2024-02-13 13:39 UTC
Labels: api-approved, area-System.Net, tenet-performance, in-pr
