### ISSUE TITLE
Configuration Binder turns IList<T> into Array<T>

### ISSUE THREAD

**Issue by phatcher** [dotnet/runtime#93601] opened 2023-10-17 11:32 UTC
### Description

Was updating some code from .NET 6 to 7 and encountered a change/regressions.

### Reproduction Steps

Given some classes as follows...

```
public class Child 
{
    public string Name { get; set; }  
}

public class Parent
{
    public string Name { get; set; }

    public IList<Child> Children { get; set; } = new List<Child>();
}
```

and some config - appsettings.json
```
{
  "MySection": {
    "Name": "A",
    "Children": [
      {
        "Name": "B"
      }
    ]
  },
```
and appsettings.Test.json
```
{
  "MySection": {
    "Children": [
      {
        "Name": "C"
      }
    ]
  }
}

```
and a program as follows
```
    internal class Program
    {
        static void Main(string[] args)
        {
            var host = Host.CreateDefaultBuilder(args)
                .ConfigureServices((b, c) =>
                {
                    var ws = b.Configuration.GetSection("MySection");

                    var w = new Parent();
                    ws.Bind(w);

                   Console.WriteLine($"MySection.Children.IsReadOnly: {w.Children.IsReadOnly}");
                })
                .Build();
        }
    }
```

### Expected behavior

The Configuration Binder emits an `List<T>`

### Actual behavior

The Configuration Binder emits an `Array<T>` (assumed from error below)

```
System.NotSupportedException : Collection was of a fixed size.
   at System.SZArrayHelper.Add[T](T _)
```

### Regression?

Worked correctly in NET 6, also works if you define the list as `List<T>` rather than `IList<T>` so principal of least surprise applies here

### Known Workarounds

1. Check to see if the child `IList<T>` is readonly and if so make a new list before adding
2. Change the definition of Parent.Children to `List<Child>`

### Configuration

.NET 7

**Comment by tarekgh** [comment] 2023-10-17 21:43
@phatcher I couldn't reproduce the same issue locally. The output of your code is showing `MySection.Children.IsReadOnly: False`. Could you please share the exact version of `Microsoft.Extensions.Configuration.Binder` which is used in your project? The one I used is:
```Xml
	<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="7.0.4" />
```

**Comment by phatcher** [comment] 2023-10-17 23:34
I wasn't referencing it directly - it was coming in via `Microsoft.Extensions.Hosting`, or `Microsoft.Extensions.Options.ConfigurationExtensions` both of which only exist at `7.0.0` and with a bit of testing, it looks like this was fixed by `Microsoft.Extensions.Configuration.Binder` `7.0.1`, and so it needs an explicit reference.

I can do this, but can I suggest that you do a bump on Hosting or Optons.ConfigurationExtensions referring to a later/current version, to make it easier for users?

**Comment by tarekgh** [comment] 2023-10-18 16:37
@ViktorHofer @ericstj when we service `Microsoft.Extensions.Configuration.Binder` library, don't we update the other libraries which reference it too? I am seeing `Microsoft.Extensions.Options.ConfigurationExtensions` still reference `7.0.0` even we have recent version `7.0.4`. Also, do we service such requests especially if we have an easy workaround for it?

**Comment by tarekgh** [comment] 2023-10-18 21:22
Thanks @ericstj for your reply. Closing per that reply.

**Closed by tarekgh** 2023-10-18 21:22 UTC
Labels: area-Extensions-Configuration
