### ISSUE TITLE
Assertion failure in `System.Net.Mail.Functional.Tests` on `mono OSX x64`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#72916] opened 2022-07-27 06:32 UTC
Hit on unrelated https://github.com/dotnet/runtime/pull/72892 .
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1905656&view=logs&jobId=c6f8dc49-92a1-5760-c098-ba97b8142bfb&j=c6f8dc49-92a1-5760-c098-ba97b8142bfb&t=5d5289b6-723b-5155-5d15-b590d280a14a) and [log](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-72892-merge-bf1f01475e7a49b3b0/System.Net.Mail.Functional.Tests/1/console.c48ed7ed.log?helixlogtype=result):

```
  Starting:    System.Net.Mail.Functional.Tests (parallel test collections = on, max threads = 6)
Assertion failed: (0 <= fd && fd < sysconf(_SC_OPEN_MAX)), function ToFileDescriptor, file pal_utilities.h, line 86.

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x101410e24 - /private/tmp/helix/working/B25309D1/p/shared/Microsoft.NETCore.App/7.0.0/libcoreclr.dylib : mono_dump_native_crash_info
	0x1013b4f1e - /private/tmp/helix/working/B25309D1/p/shared/Microsoft.NETCore.App/7.0.0/libcoreclr.dylib : mono_handle_native_crash
	0x1014b4c48 - /private/tmp/helix/working/B25309D1/p/shared/Microsoft.NETCore.App/7.0.0/libcoreclr.dylib : sigabrt_signal_handler.cold.1
	0x101410758 - /private/tmp/helix/working/B25309D1/p/shared/Microsoft.NETCore.App/7.0.0/libcoreclr.dylib : sigabrt_signal_handler
	0x7ff8178a3dfd - /usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x7 - Unknown
	0x7ff8177d9d24 - /usr/lib/system/libsystem_c.dylib : abort
	0x7ff8177d90cb - /usr/lib/system/libsystem_c.dylib : err
	0x102ee6644 - /private/tmp/helix/working/B25309D1/p/shared/Microsoft.NETCore.App/7.0.0/libSystem.Native.dylib : ToFileDescriptor
	0x102ee6b33 - /private/tmp/helix/working/B25309D1/p/shared/Microsoft.NETCore.App/7.0.0/libSystem.Native.dylib : SystemNative_SetLingerOption
	0x10601b046 - Unknown
	0x10601addb - Unknown
	0x1 - Unknown

=================================================================
	External Debugger Dump:
=================================================================

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x7ff81785800e):0x7ff817857ffe  ff ff c3 90 90 90 b8 48 01 00 02 49 89 ca 0f 05  .......H...I....
0x7ff81785800e  73 08 48 89 c7 e9 ad a1 ff ff c3 90 90 90 b8 53  s.H............S
0x7ff81785801e  00 00 02 49 89 ca 0f 05 73 08 48 89 c7 e9 95 a1  ...I....s.H.....
0x7ff81785802e  ff ff c3 90 90 90 b8 83 01 00 02 49 89 ca 0f 05  ...........I....

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at Sys:<SetLingerOption>g____PInvoke|34_0 <0x000a5>
	  at Sys:SetLingerOption <0x00092>
	  at System.Net.Sockets.SocketPal:SetLingerOption <0x000fa>
	  at System.Net.Sockets.Socket:SetLingerOption <0x0004a>
	  at System.Net.Sockets.Socket:SetSocketOption <0x002da>
	  at System.Net.Sockets.Socket:set_LingerState <0x00052>
	  at System.Net.Sockets.TcpClient:set_LingerState <0x00062>
	  at System.Net.Mail.SmtpConnection:ShutdownConnection <0x0019a>
	  at System.Net.Mail.SmtpConnection:Abort <0x00042>
	  at System.Net.Mail.SmtpTransport:Abort <0x000c2>
	  at System.Net.Mail.SmtpClient:Abort <0x00042>
	  at System.Net.Mail.SmtpClient:SendAsyncCancel <0x0009a>
	  at <>c:<SendMailAsync>b__84_1 <0x0006a>
	  at System.Threading.CancellationTokenSource:Invoke <0x0007d>
	  at <>c:<ExecuteCallback>b__9_0 <0x0007a>
	  at System.Threading.ExecutionContext:RunInternal <0x000fd>
	  at CallbackNode:ExecuteCallback <0x0015a>
	  at System.Threading.CancellationTokenSource:ExecuteCallbackHandlers <0x004ba>
	  at System.Threading.CancellationTokenSource:NotifyCancellation <0x000da>
	  at System.Threading.CancellationTokenSource:Cancel <0x00052>
	  at System.Threading.CancellationTokenSource:Cancel <0x00042>
	  at <SendMailAsync_CanBeCanceled_CancellationToken>d__34:MoveNext <0x0063a>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000ae>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start <0x00072>
	  at System.Net.Mail.Tests.SmtpClientTest:SendMailAsync_CanBeCanceled_CancellationToken <0x0012a>
	  at <Module>:runtime_invoke_object__this__ <0x000b0>
	  at <unknown> <0xffffffff>
	  at System.Reflection.RuntimeMethodInfo:InternalInvoke <0x000b8>
	  at System.Reflection.MethodInvoker:InterpretedInvoke <0x000ca>
	  at System.Reflection.RuntimeMethodInfo:Invoke <0x0029a>
	  at System.Reflection.MethodBase:Invoke <0x00058>
	  at Xunit.Sdk.TestInvoker`1:CallTestMethod <0x0005a>
	  at <<InvokeTestMethodAsync>b__1>d:MoveNext <0x00412>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000da>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder:Start <0x00042>
	  at <>c__DisplayClass48_0:<InvokeTestMethodAsync>b__1 <0x000d6>
	  at <AggregateAsync>d__4:MoveNext <0x000f5>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000da>
	  at Xunit.Sdk.ExecutionTimer:AggregateAsync <0x000d2>
	  at <>c__DisplayClass48_0:<InvokeTestMethodAsync>b__0 <0x0018a>
	  at <RunAsync>d__9:MoveNext <0x000a0>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000d2>
	  at Xunit.Sdk.ExceptionAggregator:RunAsync <0x000ca>
	  at <InvokeTestMethodAsync>d__48:MoveNext <0x002ea>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000e2>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x00042>
	  at Xunit.Sdk.TestInvoker`1:InvokeTestMethodAsync <0x00106>
	  at Xunit.Sdk.XunitTestInvoker:InvokeTestMethodAsync <0x0013a>
	  at <<RunAsync>b__47_0>d:MoveNext <0x006d9>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000ea>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x00042>
	  at Xunit.Sdk.TestInvoker`1:<RunAsync>b__47_0 <0x000de>
	  at <RunAsync>d__10`1:MoveNext <0x000a7>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000d2>
	  at Xunit.Sdk.ExceptionAggregator:RunAsync <0x000ca>
	  at Xunit.Sdk.TestInvoker`1:RunAsync <0x0012a>
	  at Xunit.Sdk.XunitTestRunner:InvokeTestMethodAsync <0x0010a>
	  at <InvokeTestAsync>d__4:MoveNext <0x00210>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000e2>
	  at Xunit.Sdk.XunitTestRunner:InvokeTestAsync <0x000da>
	  at <>c__DisplayClass43_0:<RunAsync>b__0 <0x00043>
	  at <RunAsync>d__10`1:MoveNext <0x000cb>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000da>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x00042>
	  at Xunit.Sdk.ExceptionAggregator:RunAsync <0x000fb>
	  at <RunAsync>d__43:MoveNext <0x00592>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000ea>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x00042>
	  at Xunit.Sdk.TestRunner`1:RunAsync <0x000de>
	  at Xunit.Sdk.XunitTestCaseRunner:RunTestAsync <0x000f2>
	  at <RunAsync>d__19:MoveNext <0x003ca>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000e2>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x00042>
	  at Xunit.Sdk.TestCaseRunner`1:RunAsync <0x000de>
	  at Xunit.Sdk.XunitTestCase:RunAsync <0x000f2>
	  at Xunit.Sdk.XunitTestMethodRunner:RunTestCaseAsync <0x000c0>
	  at <RunTestCasesAsync>d__32:MoveNext <0x001ce>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000ea>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x00042>
	  at Xunit.Sdk.TestMethodRunner`1:RunTestCasesAsync <0x000de>
	  at <RunAsync>d__31:MoveNext <0x00218>
	  at System.Runtime.CompilerServices.AsyncMethodBuilderCore:Start <0x000da>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start <0x00042>
	  at Xunit.Sdk.TestMethodRunner`1:RunAsync <0x000d6>
	  at Xunit.Sdk.XunitTestClassRunner:RunTestMethodAsync <0x0012a>
	  at <RunTestMethodsAsync>d__38:MoveNext <0x009a0>
	  at AsyncStateMachineBox`1:ExecutionContextCallback <0x00052>
	  at System.Threading.ExecutionContext:RunInternal <0x000fd>
	  at AsyncStateMachineBox`1:MoveNext <0x0011a>
	  at AsyncStateMachineBox`1:MoveNext <0x00042>
	  at <>c:<.cctor>b__17_0 <0x00056>
	  at System.Threading.Tasks.AwaitTaskContinuation:RunCallback <0x0008f>
	  at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation:Run <0x000ba>
	  at System.Threading.Tasks.Task:RunContinuations <0x00328>
	  at System.Threading.Tasks.Task:FinishContinuations <0x00092>
	  at System.Threading.Tasks.Task`1:TrySetResult <0x00112>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetExistingTaskResult <0x00102>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult <0x000d2>
	  at <RunAsync>d__31:MoveNext <0x00912>
	  at AsyncStateMachineBox`1:ExecutionContextCallback <0x00052>
	  at System.Threading.ExecutionContext:RunInternal <0x000fd>
	  at AsyncStateMachineBox`1:MoveNext <0x00112>
	  at AsyncStateMachineBox`1:MoveNext <0x00042>
	  at <>c:<.cctor>b__17_0 <0x00056>
	  at System.Threading.Tasks.AwaitTaskContinuation:RunCallback <0x0008f>
	  at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation:Run <0x000ba>
	  at System.Threading.Tasks.Task:RunContinuations <0x00328>
	  at System.Threading.Tasks.Task:FinishContinuations <0x00092>
	  at System.Threading.Tasks.Task`1:TrySetResult <0x00112>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetExistingTaskResult <0x00102>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult <0x000d2>
	  at <RunTestCasesAsync>d__32:MoveNext <0x005aa>
	  at AsyncStateMachineBox`1:ExecutionContextCallback <0x00052>
	  at System.Threading.ExecutionContext:RunInternal <0x000fd>
	  at AsyncStateMachineBox`1:MoveNext <0x0011a>
	  at AsyncStateMachineBox`1:MoveNext <0x00042>
	  at <>c:<.cctor>b__17_0 <0x00056>
	  at System.Threading.Tasks.AwaitTaskContinuation:RunCallback <0x0008f>
	  at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation:Run <0x000ba>
	  at System.Threading.Tasks.Task:RunContinuations <0x00328>
	  at System.Threading.Tasks.Task:FinishContinuations <0x00092>
	  at System.Threading.Tasks.Task`1:TrySetResult <0x00112>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetExistingTaskResult <0x00102>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult <0x000d2>
	  at <RunAsync>d__19:MoveNext <0x00c1a>
	  at AsyncStateMachineBox`1:ExecutionContextCallback <0x00052>
	  at System.Threading.ExecutionContext:RunInternal <0x000fd>
	  at AsyncStateMachineBox`1:MoveNext <0x0011a>
	  at AsyncStateMachineBox`1:MoveNext <0x00042>
	  at <>c:<.cctor>b__17_0 <0x00056>
	  at System.Threading.Tasks.AwaitTaskContinuation:RunCallback <0x0008f>
	  at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation:Run <0x000ba>
	  at System.Threading.Tasks.Task:RunContinuations <0x00328>
	  at System.Threading.Tasks.Task:FinishContinuations <0x00092>
	  at System.Threading.Tasks.Task`1:TrySetResult <0x00112>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetExistingTaskResult <0x00102>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult <0x000d2>
	  at <RunTestAsync>d__11:MoveNext <0x0092a>
	  at AsyncStateMachineBox`1:ExecutionContextCallback <0x0004a>
	  at System.Threading.ExecutionContext:RunInternal <0x000fd>
	  at AsyncStateMachineBox`1:MoveNext <0x00112>
	  at AsyncStateMachineBox`1:MoveNext <0x00042>
	  at <>c:<.cctor>b__17_0 <0x00056>
	  at System.Threading.Tasks.AwaitTaskContinuation:RunCallback <0x0008f>
	  at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation:Run <0x000ba>
	  at System.Threading.Tasks.Task:RunContinuations <0x00328>
	  at System.Threading.Tasks.Task:FinishContinuations <0x00092>
	  at System.Threading.Tasks.Task`1:TrySetResult <0x00112>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetExistingTaskResult <0x00102>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult <0x000d2>
	  at <RunAsync>d__43:MoveNext <0x00d62>
	  at AsyncStateMachineBox`1:ExecutionContextCallback <0x00052>
	  at System.Threading.ExecutionContext:RunInternal <0x000fd>
	  at AsyncStateMachineBox`1:MoveNext <0x0011a>
	  at AsyncStateMachineBox`1:MoveNext <0x00042>
	  at <>c:<.cctor>b__17_0 <0x00056>
	  at System.Threading.Tasks.AwaitTaskContinuation:RunCallback <0x0008f>
	  at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation:Run <0x000ba>
	  at System.Threading.Tasks.Task:RunContinuations <0x00328>
	  at System.Threading.Tasks.Task:FinishContinuations <0x00092>
	  at System.Threading.Tasks.Task`1:TrySetResult <0x00112>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetExistingTaskResult <0x00102>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult <0x000d2>
	  at <RunAsync>d__10`1:MoveNext <0x0046a>
	  at AsyncStateMachineBox`1:ExecutionContextCallback <0x00052>
	  at System.Threading.ExecutionContext:RunInternal <0x000fd>
	  at AsyncStateMachineBox`1:MoveNext <0x00112>
	  at AsyncStateMachineBox`1:MoveNext <0x00042>
	  at <>c:<.cctor>b__17_0 <0x00056>
	  at System.Threading.Tasks.AwaitTaskContinuation:RunCallback <0x0008f>
	  at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation:Run <0x000ba>
	  at System.Threading.Tasks.Task:RunContinuations <0x00328>
	  at System.Threading.Tasks.Task:FinishContinuations <0x00092>
	  at System.Threading.Tasks.Task`1:TrySetResult <0x00112>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetExistingTaskResult <0x00102>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult <0x000d2>
	  at <InvokeTestAsync>d__4:MoveNext <0x00532>
	  at AsyncStateMachineBox`1:ExecutionContextCallback <0x0004a>
	  at System.Threading.ExecutionContext:RunInternal <0x000fd>
	  at AsyncStateMachineBox`1:MoveNext <0x00112>
	  at AsyncStateMachineBox`1:MoveNext <0x00042>
	  at <>c:<.cctor>b__17_0 <0x00056>
	  at System.Threading.Tasks.AwaitTaskContinuation:RunCallback <0x0008f>
	  at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation:Run <0x000ba>
	  at System.Threading.Tasks.Task:RunContinuations <0x00328>
	  at System.Threading.Tasks.Task:FinishContinuations <0x00092>
	  at System.Threading.Tasks.Task`1:TrySetResult <0x000ea>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetExistingTaskResult <0x000c2>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult <0x000b2>
	  at <RunAsync>d__10`1:MoveNext <0x0040a>
	  at AsyncStateMachineBox`1:ExecutionContextCallback <0x0004a>
	  at System.Threading.ExecutionContext:RunInternal <0x000fd>
	  at AsyncStateMachineBox`1:MoveNext <0x00112>
	  at AsyncStateMachineBox`1:MoveNext <0x00042>
	  at <>c:<.cctor>b__17_0 <0x00056>
	  at System.Threading.Tasks.AwaitTaskContinuation:RunCallback <0x0008f>
	  at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation:Run <0x000ba>
	  at System.Threading.Tasks.Task:RunContinuations <0x00328>
	  at System.Threading.Tasks.Task:FinishContinuations <0x00092>
	  at System.Threading.Tasks.Task`1:TrySetResult <0x000ea>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetExistingTaskResult <0x000c2>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult <0x000b2>
	  at <<RunAsync>b__47_0>d:MoveNext <0x00ed2>
	  at AsyncStateMachineBox`1:ExecutionContextCallback <0x00052>
	  at System.Threading.ExecutionContext:RunInternal <0x000fd>
	  at AsyncStateMachineBox`1:MoveNext <0x0011a>
	  at AsyncStateMachineBox`1:MoveNext <0x00042>
	  at <>c:<.cctor>b__17_0 <0x00056>
	  at System.Threading.Tasks.AwaitTaskContinuation:RunCallback <0x0008f>
	  at System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation:Run <0x000ba>
	  at System.Threading.Tasks.Task:RunContinuations <0x00328>
	  at System.Threading.Tasks.Task:FinishContinuations <0x00092>
	  at System.Threading.Tasks.Task`1:TrySetResult <0x000ea>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetExistingTaskResult <0x000c2>
	  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:SetResult <0x000b2>
	  at <InvokeTestMethodAsync>d__48:MoveNext <0x005f2>
	  at AsyncStateMachineBox`1:ExecutionContextCallback <0x00052>
	  at System.Threading.ExecutionContext:RunInternal <0x000fd>
	  at AsyncStateMachineBox`1:MoveNext <0x0011a>
	  at AsyncStateMachineBox`1:MoveNext <0x00042>
	  at <>c:<.cctor>b__8_0 <0x00056>
	  at <>c__DisplayClass7_0:<Post>b__1 <0x0004c>
	  at Xunit.Sdk.MaxConcurrencySyncContext:RunOnSyncContext <0x0006e>
	  at <>c__DisplayClass11_0:<WorkerThreadProc>b__0 <0x0005a>
	  at System.Threading.ExecutionContext:RunInternal <0x000fd>
	  at System.Threading.ExecutionContext:Run <0x00072>
	  at System.Object:lambda_method2 <0x0008a>
	  at Xunit.Sdk.ExecutionContextHelper:Run <0x00081>
	  at Xunit.Sdk.MaxConcurrencySyncContext:WorkerThreadProc <0x00262>
	  at <>c:<QueueUserWorkItem>b__5_0 <0x00076>
	  at System.Threading.Tasks.Task:InnerInvoke <0x000b5>
	  at <>c:<.cctor>b__273_0 <0x00036>
	  at System.Threading.ExecutionContext:RunInternal <0x000fd>
	  at System.Threading.Tasks.Task:ExecuteWithThreadLocal <0x00352>
	  at System.Threading.Tasks.Task:ExecuteEntryUnsafe <0x000ba>
	  at <>c:<.cctor>b__10_0 <0x0006a>
	  at System.Threading.Thread:StartCallback <0x00141>
	  at System.Object:runtime_invoke_void__this__ <0x000b0>
=================================================================
./RunTests.sh: line 168: 72837 Abort trap: 6           "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.Net.Mail.Functional.Tests.runtimeconfig.json --depsfile System.Net.Mail.Functional.Tests.deps.json xunit.console.dll System.Net.Mail.Functional.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
```

**Comment by danmoseley** [comment] 2022-07-27 09:15
https://github.com/dotnet/runtime/issues/72830

**Comment by wfurt** [comment] 2022-07-27 18:22
duplicate of https://github.com/dotnet/runtime/issues/72830

**Closed by wfurt** 2022-07-27 18:22 UTC
Labels: area-System.Net, blocking-clean-ci, untriaged, test-failure
