### ISSUE TITLE
[Perf -7%] System.Text.Perf_Utf8Encoding.GetBytes

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#45554] opened 2020-12-03 17:27 UTC
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [d73c65ed402fad658c39d78773d181c4459b62c8](https://github.com/dotnet/runtime/commit/d73c65ed402fad658c39d78773d181c4459b62c8)
Compare | [fe80a77dac16de2451be60563123b8fbf8ea8355](https://github.com/dotnet/runtime/commit/fe80a77dac16de2451be60563123b8fbf8ea8355)

### Regressions in System.Text.Perf_Utf8Encoding

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[GetBytes](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04/System.Text.Perf_Utf8Encoding.GetBytes(Input%3a%20Cyrillic).html>) | 91.13 μs | 97.86 μs | 1.07 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/11_30_2020/refs/heads/master_x64_ubuntu%2018.04_Regression/System.Text.Perf_Utf8Encoding_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/11_30_2020/refs/heads/master_x64_ubuntu%2018.04/System.Text.Perf_Utf8Encoding.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Text.Perf_Utf8Encoding*'
```
<details>

.
### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-5d7e161d-bbae-4a84-a7af-78c52cafe80c6293086d0a6422381/9a4daa21-fa03-403a-ae10-231b75fd79a0.zip?sv=2019-07-07&se=2020-12-24T19%3A49%3A21Z&sr=c&sp=rl&sig=Dir55fAFxM%2BZnLY3jCUCPgyrORpZCNcXNp8%2F%2BZRGn1I%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-05ecc104-82ba-4de7-b7ce-8be8d1af4476a6ebe26717e459ea4/617bb3f6-9fe1-465a-af05-521fafe576e2.zip?sv=2019-07-07&se=2020-12-25T06%3A19%3A26Z&sr=c&sp=rl&sig=Am1V38b4IXaqZs73WjYtp9c2SwmA0To6txWrb5AU%2FsE%3D>)

#### System.Text.Perf_Utf8Encoding.GetBytes(Input: Cyrillic)

```log
[88821.971 ; 91127.201) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[91127.201 ; 94296.831) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[94296.831 ; 97253.700) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[97253.700 ; 99712.542) | @@@@@@@@@@@@@@@@@@@@@@@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by tarekgh** [comment] 2020-12-03 23:01
@GrabYourPitchforks did we have any recent change in this area? or you think this is related to codegen?

**Comment by GrabYourPitchforks** [comment] 2020-12-07 18:27
There weren't any recent changes to _System.Text_ here. There were two JIT changes (https://github.com/dotnet/runtime/commit/703145649baf152e3678825be1849f6fd1bd2b24 and https://github.com/dotnet/runtime/commit/3e65d689d5ed03589c4f42fc81fab995b0be7f3c) between baseline + compare, but I don't know how to reason about whether those JIT changes may have impacted these scenarios. If other perf tests started showing regressions at around the same time then it might finger those.

**Comment by danmosemsft** [comment] 2020-12-11 21:33
@DrewScoggins were there any other regressions at the same point?

**Comment by danmosemsft** [comment] 2020-12-11 21:33
cc @AndyAyersMS and @sandreenko who made those changes in case something pops for them.

**Comment by DrewScoggins** [comment] 2020-12-11 21:36
Not that we saw, no.

**Comment by sandreenko** [comment] 2020-12-11 22:17
It could have been caused by https://github.com/dotnet/runtime/commit/3e65d689d5ed03589c4f42fc81fab995b0be7f3c, the description is here https://github.com/dotnet/runtime/pull/43130#discussion_r527330557.
Could you please mark it as codegen and assign it to me? I will try to find a solution after we setup arm64 apple testing in ci.

**Comment by GrabYourPitchforks** [comment] 2020-12-11 22:21
Check also the comments for https://github.com/DrewScoggins/performance-2/issues/3543. There's some discussion there that the JIT may have experienced regressions around this time frame.

**Comment by danmosemsft** [comment] 2020-12-11 22:56
@sandreenko thanks - I've assigned to you.

**Comment by EgorBo** [comment] 2022-10-05 17:21
Closing this as we fixed it via PGO static data from training sessions where we added non en-us inputs including cyrilic e.g. 
![image](https://user-images.githubusercontent.com/523221/194122493-417fc640-cd33-41e4-9173-1791ba8ae4d1.png)

**Closed by EgorBo** 2022-10-05 17:21 UTC
Labels: os-linux, tenet-performance, tenet-performance-benchmarks, arch-x64, area-CodeGen-coreclr

**Comment by danmoseley** [comment] 2022-10-05 20:38
@EgorBo for my reference, where do we store training scenarios?
