### ISSUE TITLE
System.Diagnostic.Process.Start(...) does not Support mailto: protocoll

### ISSUE THREAD

**Issue by LokiMidgard** [dotnet/runtime#30303] opened 2019-07-19 06:05 UTC
Porting a .Net Framework App to .Net Core 3.0, I was not able to invoke the default mail client with the `mailto:` protocoll using `System.Diagnostics.Process.Start(...)`.

.Net Core `3.0.100-preview5-011568`  
Windows 10 1809  
Outlook 2016  

Sampe code to reproduce

```c#
var body = "This is a body of a message";
var recipients = String.Join(",", "to@user.com", "alsoTo@user.com");
string mailto = $"mailto:{recipients}?Subject={"Subject of message"}&Body={body}";
mailto = Uri.EscapeUriString(mailto);
System.Diagnostics.Process.Start(mailto);

```

The Exception that occures: `System.ComponentModel.Win32Exception: 'Das System kann die angegebene Datei nicht finden.'` (Translated `System can not find the file` not sure if that is the actuall english error message)

**Comment by eiriktsarpalis** [comment] 2020-06-22 15:58
Closing, since this seems to be by design.

**Closed by eiriktsarpalis** 2020-06-22 15:58 UTC
Labels: area-System.Diagnostics.Process, untriaged
