### ISSUE TITLE
[API Proposal]: `KeyValuePair<TKey, TValue>` override `GetHashCode`, `Equals` and operators

### ISSUE THREAD

**Issue by Cricle** [dotnet/runtime#80058] opened 2022-12-30 02:05 UTC
### Background and motivation

In [KeyValuePair](https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/KeyValuePair.cs,27) no override `GetHashCode`, `Equals` and operators, it will use [ValueType](https://source.dot.net/#System.Private.CoreLib/src/System/ValueType.cs,21) reflection operation.

![image](https://user-images.githubusercontent.com/26201412/210027333-7443726e-e3e5-4c53-93ed-2088aa812df0.png)

### API Proposal

```csharp
namespace System.Collections.Generic;

    public readonly struct KeyValuePair<TKey, TValue>:IEquatable<KeyValuePair<TKey, TValue>>
    {
        public override int GetHashCode()
        {
            return HashCode.Combine(key, value);
        }
        public override bool Equals([NotNullWhen(true)] object? obj)
        {
            if (obj is KeyValuePair<TKey, TValue> pair)
            {
                return Equals(pair);
            }
            return false;
        }

        public bool Equals(KeyValuePair<TKey, TValue> other)
        {
            return Equals(key, other.key)&&
                Equals(value,other.value);
        }

        public static bool operator ==(KeyValuePair<TKey, TValue> left, KeyValuePair<TKey, TValue> right)
        {
            return left.Equals(right);
        }

        public static bool operator !=(KeyValuePair<TKey, TValue> left, KeyValuePair<TKey, TValue> right)
        {
            return !(left == right);
        }
    }

```

### API Usage

```csharp
var kv1 = new KeyValuePair<int, int>(1, 2);
var kv2 = new KeyValuePair<int, int>(1, 2);
Console.WriteLine(kv1==kv2);//true
```

### Alternative Designs

No.

### Risks

No.

**Comment by jkotas** [comment] 2022-12-30 03:26
Duplicate of #35602

**Closed** 2023-01-10 11:29 UTC
Labels: api-suggestion, area-System.Collections, untriaged
