### ISSUE TITLE
[Perf -13%] System.Collections.IndexerSet<Int32>.SortedList

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#39033] opened 2020-07-09 22:12 UTC
### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Changes | [diff](https://github.com/dotnet/runtime/compare/a4a49f07fbf986d496ef57521e76b22caaf9bfb3...3c6656f83b01ece6af7e11eb75ec0145554b139d)

### Regressions in System.Collections.IndexerSet<Int32>

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier
-- | -- | -- | -- | -- | --
SortedList | 29.21 μs | 33.68 μs | 1.15 | Bimodal | False

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_09_2020/release/3.1.1xx%20-%3E%20master_x64_Windows%2010.0.18362/System.Collections.IndexerSet(Int32)_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_09_2020/release/3.1.1xx%20-%3E%20master_x64_Windows%2010.0.18362/System.Collections.IndexerSet(Int32).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Collections.IndexerSet<Int32>*';
```
<details>

#### System.Collections.IndexerSet<Int32>.SortedList(Size: 512)

```log
[28076.484 ; 29188.569) | @@@@@@@@@@@@@@@@@@@@@@@@@@
[29188.569 ; 29858.113) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[29858.113 ; 30754.387) | @@@@@@@@@@@@@@@@@@@@@@@
[30754.387 ; 31983.035) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[31983.035 ; 32675.472) | @@@@
[32675.472 ; 34134.320) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by danmosemsft** [comment] 2020-08-01 00:52
Also stresses Array.Copy by doing inserts.

Duplicate of https://github.com/dotnet/runtime/issues/39112

**Comment by danmosemsft** [comment] 2020-08-01 00:52
Duplicate of #39112

**Comment by danmosemsft** [comment] 2020-08-01 00:52
It seems your comment must literally and entirely be "Duplicate of #nnn" for Github to recognize it...

**Closed by danmosemsft** 2020-08-01 00:52 UTC
Labels: arch-x64, area-System.Collections, os-windows, tenet-performance, tenet-performance-benchmarks, untriaged
