### ISSUE TITLE
Test failure Loader\\classloader\\RefFields\\Validate\\Validate.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#64484] opened 2022-01-29 01:31 UTC
Run: [runtime-coreclr outerloop 20220128.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1578514&view=ms.vss-test-web.build-test-results-tab&runId=44287326&resultId=103876&paneView=debug)

Failed test:
```
R2R-CG2 windows arm64 Checked no_tiered_compilation @ Windows.10.Arm64v8.Open

- Loader\\classloader\\RefFields\\Validate\\Validate.cmd

R2R-CG2 windows arm64 Checked @ Windows.10.Arm64v8.Open

- Loader\\classloader\\RefFields\\Validate\\Validate.cmd

R2R-CG2 windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open

- Loader\\classloader\\RefFields\\Validate\\Validate.cmd

R2R-CG2 windows x86 Checked @ Windows.10.Amd64.Open

- Loader\\classloader\\RefFields\\Validate\\Validate.cmd

R2R-CG2 windows x64 Checked @ Windows.10.Amd64.Open

- Loader\\classloader\\RefFields\\Validate\\Validate.cmd

R2R-CG2 windows x64 Checked no_tiered_compilation @ Windows.10.Amd64.Open

- Loader\\classloader\\RefFields\\Validate\\Validate.cmd

R2R-CG2 OSX x64 Checked no_tiered_compilation @ OSX.1014.Amd64.Open

- Loader/classloader/RefFields/Validate/Validate.sh

R2R-CG2 windows arm Checked @ Windows.10.Arm64v8.Open

- Loader\\classloader\\RefFields\\Validate\\Validate.cmd

R2R-CG2 Linux x64 Checked @ (Alpine.314.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64-20210910135833-1848e19

- Loader/classloader/RefFields/Validate/Validate.sh

R2R-CG2 Linux x64 Checked no_tiered_compilation @ (Alpine.314.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64-20210910135833-1848e19

- Loader/classloader/RefFields/Validate/Validate.sh

R2R-CG2 OSX x64 Checked @ OSX.1014.Amd64.Open

- Loader/classloader/RefFields/Validate/Validate.sh
```
**Error message:**
```
Could Not Find D:\h\w\B73B0984\w\A5830909\e\Loader\classloader\RefFields\Validate\IL-CG2\composite-r2r.dll
Could Not Find D:\h\w\B73B0984\w\A5830909\e\Loader\classloader\RefFields\Validate\InvalidCSharp.dll.rsp
Could Not Find D:\h\w\B73B0984\w\A5830909\e\Loader\classloader\RefFields\Validate\Validate.dll.rsp

Assert failure(PID 8896 [0x000022c0], Thread: 10676 [0x29b4]): Verify_FieldOffset 'InvalidCSharp.WithTypedReferenceField`1.Field' Field offset 0!=8(actual) || baseOffset 0!=0(actual)

CORECLR! LoadDynamicInfoEntry + 0x1450 (0x00007ffe377540e8) CORECLR! Module::FixupNativeEntry + 0x6C (0x00007ffe376d0d2c)
CORECLR! Module::FixupDelayListAux<Module ,int (__cdecl Module::)(CORCOMPILE_IMPORT_SECTION *,unsigned __int64,unsigned __int64 *,int)> + 0x18C (0x00007ffe37814c54) CORECLR! ReadyToRunInfo::GetEntryPoint + 0x2F4 (0x00007ffe37815de4)
CORECLR! MethodDesc::GetPrecompiledR2RCode + 0x38 (0x00007ffe377afff0) CORECLR! MethodDesc::GetPrecompiledCode + 0x28 (0x00007ffe377afdc8)
CORECLR! MethodDesc::PrepareILBasedCode + 0x2AC (0x00007ffe377b1e14) CORECLR! MethodDesc::PrepareCode + 0x54 (0x00007ffe377b1b5c)
CORECLR! CodeVersionManager::PublishVersionableCodeIfNecessary + 0x2A8 (0x00007ffe376f7ec8) CORECLR! MethodDesc::DoPrestub + 0x344 (0x00007ffe377ada64)
File: D:\a_work\1\s\src\coreclr\vm\jitinterface.cpp Line: 13639
Image: D:\h\w\B73B0984\p\corerun.exe

Return code:      1
Raw output file:      D:\h\w\B73B0984\w\A5830909\uploads\Reports\Loader.classloader\RefFields\Validate\Validate.output.txt
Raw output:
BEGIN EXECUTION
InvalidCSharp.dll
Validate.dll
2 file(s) copied.
Response file: D:\h\w\B73B0984\w\A5830909\e\Loader\classloader\RefFields\Validate\InvalidCSharp.dll.rsp
D:\h\w\B73B0984\w\A5830909\e\Loader\classloader\RefFields\Validate\IL-CG2\InvalidCSharp.dll
-o:D:\h\w\B73B0984\w\A5830909\e\Loader\classloader\RefFields\Validate\InvalidCSharp.dll
--targetarch:arm64
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\B73B0984\p\System..dll
-r:D:\h\w\B73B0984\p\Microsoft..dll
-r:D:\h\w\B73B0984\p\mscorlib.dll
-r:D:\h\w\B73B0984\p\netstandard.dll
-O
" "dotnet" "D:\h\w\B73B0984\p\crossgen2\crossgen2.dll" @"D:\h\w\B73B0984\w\A5830909\e\Loader\classloader\RefFields\Validate\InvalidCSharp.dll.rsp"   -r:D:\h\w\B73B0984\w\A5830909\e\Loader\classloader\RefFields\Validate\IL-CG2*.dll"
Emitting R2R PE file: D:\h\w\B73B0984\w\A5830909\e\Loader\classloader\RefFields\Validate\InvalidCSharp.dll
Response file: D:\h\w\B73B0984\w\A5830909\e\Loader\classloader\RefFields\Validate\Validate.dll.rsp
D:\h\w\B73B0984\w\A5830909\e\Loader\classloader\RefFields\Validate\IL-CG2\Validate.dll
-o:D:\h\w\B73B0984\w\A5830909\e\Loader\classloader\RefFields\Validate\Validate.dll
--targetarch:arm64
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\B73B0984\p\System..dll
-r:D:\h\w\B73B0984\p\Microsoft..dll
-r:D:\h\w\B73B0984\p\mscorlib.dll
-r:D:\h\w\B73B0984\p\netstandard.dll
-O
" "dotnet" "D:\h\w\B73B0984\p\crossgen2\crossgen2.dll" @"D:\h\w\B73B0984\w\A5830909\e\Loader\classloader\RefFields\Validate\Validate.dll.rsp"   -r:D:\h\w\B73B0984\w\A5830909\e\Loader\classloader\RefFields\Validate\IL-CG2*.dll"
Emitting R2R PE file: D:\h\w\B73B0984\w\A5830909\e\Loader\classloader\RefFields\Validate\Validate.dll
"D:\h\w\B73B0984\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  Validate.dll
Validate_Invalid_RefField_Fails...
Validate_RefStructWithRefField_Load...
Validate_Create_RefField...
Validate_Create_RefStructField...
Validate_Create_TypedReferenceRefField...
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\B73B0984\p
D:\h\w\B73B0984\w\A5830909\e\Loader\classloader\RefFields\Validate\Validate.cmd
Expected: True
Actual:   False


Stack trace
   at Loader_classloader._RefFields_Validate_Validate_._RefFields_Validate_Validate_cmd()
```

**Comment by am11** [comment] 2022-01-29 08:28
@AaronRobinsonMSFT, this seems to be a duplicate of https://github.com/dotnet/runtime/issues/64465.

**Comment by AaronRobinsonMSFT** [comment] 2022-01-30 00:16
Closing as duplicate of #64465

**Closed by AaronRobinsonMSFT** 2022-01-30 00:16 UTC
Labels: arch-arm64, arch-x86, os-linux, os-mac-os-x, os-windows, arch-x64, area-crossgen2-coreclr, untriaged
