### ISSUE TITLE
[Perf - 10-20x regression] System.Globalization.Tests.Perf_DateTimeCultureInfo.Parse in ja

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#37807] opened 2020-06-12 17:37 UTC
### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Changes | [diff](https://github.com/dotnet/installer/compare/a4a49f07fbf986d496ef57521e76b22caaf9bfb3...ccd701fe23f236755650af3ce3d9ab6bdd8a4af9)

### Regressions in System.Globalization.Tests.Perf_DateTimeCultureInfo

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier
-- | -- | -- | -- | -- | --
Parse | 518.38 ns | 5.52 μs | 10.65 |  | False

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/06_11_2020/Windows%2010.0.18362_x64/System.Globalization.Tests.Perf_DateTimeCultureInfo_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/06_11_2020/Windows%2010.0.18362_x64/System.Globalization.Tests.Perf_DateTimeCultureInfo.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Globalization.Tests.Perf_DateTimeCultureInfo*';
```
<details>

#### System.Globalization.Tests.Perf_DateTimeCultureInfo.Parse(culturestring: ja)

```log
[-265.889 ; 1287.875) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[1287.875 ; 2817.846) | 
[2817.846 ; 4347.817) | 
[4347.817 ; 6269.985) | @@@@@@@@@@@@@@@@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by DrewScoggins** [comment] 2020-06-12 17:37
Also likely ICU related @adamsitnik

**Comment by safern** [comment] 2020-06-12 18:35
Yeah I think this is definitely related to the ICU change on Windows.

**Comment by danmosemsft** [comment] 2020-08-02 20:45
Without env var, the huge regression for `ja` is clear - it's 1887% (20x) regressed:

[2020/08/02 13:36:30][INFO] BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19041.421 (2004/?/20H1)
[2020/08/02 13:36:30][INFO] Intel Core i7-7700 CPU 3.60GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
[2020/08/02 13:36:30][INFO] .NET Core SDK=5.0.100-rc.1.20401.3
[2020/08/02 13:36:30][INFO]   [Host]     : .NET Core 3.1.6 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.31603), X64 RyuJIT
[2020/08/02 13:36:30][INFO]   Job-FVRXJJ : .NET Core 3.1.6 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.31603), X64 RyuJIT
[2020/08/02 13:36:30][INFO]
[2020/08/02 13:36:30][INFO] PowerPlanMode=00000000-0000-0000-0000-000000000000  Runtime=.NET Core 3.1  Arguments=/p:DebugType=portable
[2020/08/02 13:36:30][INFO] Toolchain=netcoreapp3.1  IterationTime=250.0000 ms  MaxIterationCount=20
[2020/08/02 13:36:30][INFO] MinIterationCount=15  WarmupCount=1
[2020/08/02 13:36:30][INFO]
[2020/08/02 13:36:30][INFO] | Method | culturestring |     Mean |    Error |   StdDev |   Median |      Min |      Max | Gen 0 | Gen 1 | Gen 2 | Allocated |
[2020/08/02 13:36:30][INFO] |------- |-------------- |---------:|---------:|---------:|---------:|---------:|---------:|------:|------:|------:|----------:|
[2020/08/02 13:36:30][INFO] |  Parse |               | 440.9 ns |  8.69 ns |  8.93 ns | 442.1 ns | 426.0 ns | 455.3 ns |     - |     - |     - |         - |
[2020/08/02 13:36:30][INFO] |  Parse |            da | 529.6 ns | 10.75 ns | 12.38 ns | 529.8 ns | 507.5 ns | 551.5 ns |     - |     - |     - |         - |
[2020/08/02 13:36:30][INFO] |  Parse |            fr | 442.0 ns |  6.01 ns |  5.33 ns | 441.9 ns | 434.5 ns | 451.2 ns |     - |     - |     - |         - |
[2020/08/02 13:36:30][INFO] |  Parse |            ja | 455.6 ns |  8.24 ns |  7.31 ns | 458.6 ns | 443.9 ns | 465.7 ns |     - |     - |     - |         - |
[2020/08/02 13:36:30][INFO]

[2020/08/02 13:37:23][INFO]
[2020/08/02 13:37:23][INFO] BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19041.421 (2004/?/20H1)
[2020/08/02 13:37:23][INFO] Intel Core i7-7700 CPU 3.60GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
[2020/08/02 13:37:23][INFO] .NET Core SDK=5.0.100-rc.1.20401.3
[2020/08/02 13:37:23][INFO]   [Host]     : .NET Core 5.0.0 (CoreCLR 5.0.20.40101, CoreFX 5.0.20.40101), X64 RyuJIT
[2020/08/02 13:37:23][INFO]   Job-ZUZTSW : .NET Core 5.0.0 (CoreCLR 5.0.20.40101, CoreFX 5.0.20.40101), X64 RyuJIT
[2020/08/02 13:37:23][INFO]
[2020/08/02 13:37:23][INFO] PowerPlanMode=00000000-0000-0000-0000-000000000000  Runtime=.NET Core 5.0  Arguments=/p:DebugType=portable
[2020/08/02 13:37:23][INFO] Toolchain=netcoreapp5.0  IterationTime=250.0000 ms  MaxIterationCount=20
[2020/08/02 13:37:23][INFO] MinIterationCount=15  WarmupCount=1
[2020/08/02 13:37:23][INFO]
[2020/08/02 13:37:23][INFO] | Method | culturestring |       Mean |       Error |      StdDev |     Median |        Min |         Max | Gen 0 | Gen 1 | Gen 2 | Allocated |
[2020/08/02 13:37:23][INFO] |------- |-------------- |-----------:|------------:|------------:|-----------:|-----------:|------------:|------:|------:|------:|----------:|
[2020/08/02 13:37:23][INFO] |  Parse |               |   399.1 ns |     7.67 ns |     6.41 ns |   399.3 ns |   390.7 ns |    414.3 ns |     - |     - |     - |         - |
[2020/08/02 13:37:23][INFO] |  Parse |            da |   425.6 ns |     8.17 ns |     7.64 ns |   424.3 ns |   415.2 ns |    436.6 ns |     - |     - |     - |         - |
[2020/08/02 13:37:23][INFO] |  Parse |            fr |   403.4 ns |    10.60 ns |    12.20 ns |   402.6 ns |   386.0 ns |    433.3 ns |     - |     - |     - |         - |
[2020/08/02 13:37:23][INFO] |  Parse |            ja | 8,588.9 ns | 3,503.94 ns | 3,749.18 ns | 6,850.0 ns | 4,300.0 ns | 16,000.0 ns |     - |     - |     - |         - |
[2020/08/02 13:37:23][INFO]


But with `DOTNET_SYSTEM_GLOBALIZATION_USENLS=1` the regression vanishes.
`C:\git>py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter "System.Globalization.Tests.Perf_DateTimeCultureInfo.Parse"`

[2020/08/02 13:42:42][INFO]
[2020/08/02 13:42:42][INFO] BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19041.421 (2004/?/20H1)
[2020/08/02 13:42:42][INFO] Intel Core i7-7700 CPU 3.60GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
[2020/08/02 13:42:42][INFO] .NET Core SDK=5.0.100-rc.1.20401.3
[2020/08/02 13:42:42][INFO]   [Host]     : .NET Core 5.0.0 (CoreCLR 5.0.20.40101, CoreFX 5.0.20.40101), X64 RyuJIT
[2020/08/02 13:42:42][INFO]   Job-GXOISF : .NET Core 5.0.0 (CoreCLR 5.0.20.40101, CoreFX 5.0.20.40101), X64 RyuJIT
[2020/08/02 13:42:42][INFO]
[2020/08/02 13:42:42][INFO] PowerPlanMode=00000000-0000-0000-0000-000000000000  Runtime=.NET Core 5.0  Arguments=/p:DebugType=portable
[2020/08/02 13:42:42][INFO] Toolchain=netcoreapp5.0  IterationTime=250.0000 ms  MaxIterationCount=20
[2020/08/02 13:42:42][INFO] MinIterationCount=15  WarmupCount=1
[2020/08/02 13:42:42][INFO]
[2020/08/02 13:42:42][INFO] | Method | culturestring |     Mean |   Error |  StdDev |   Median |      Min |      Max | Gen 0 | Gen 1 | Gen 2 | Allocated |
[2020/08/02 13:42:42][INFO] |------- |-------------- |---------:|--------:|--------:|---------:|---------:|---------:|------:|------:|------:|----------:|
[2020/08/02 13:42:42][INFO] |  Parse |               | 402.2 ns | 3.94 ns | 3.69 ns | 400.9 ns | 397.2 ns | 409.2 ns |     - |     - |     - |         - |
[2020/08/02 13:42:42][INFO] |  Parse |            da | 481.0 ns | 2.70 ns | 2.53 ns | 480.8 ns | 477.6 ns | 485.7 ns |     - |     - |     - |         - |
[2020/08/02 13:42:42][INFO] |  Parse |            fr | 406.7 ns | 3.93 ns | 3.49 ns | 406.4 ns | 400.8 ns | 412.5 ns |     - |     - |     - |         - |
[2020/08/02 13:42:42][INFO] |  Parse |            ja | 412.6 ns | 4.55 ns | 4.03 ns | 413.1 ns | 403.4 ns | 419.3 ns |     - |     - |     - |         - |

This regression would be painful to ship with.

**Comment by tarekgh** [comment] 2020-08-02 21:44
@danmosemsft the ja perf test is misleading. I discussed this with @adamsitnik before. The test was including the warming up code which is cached when called first time. It is expected to the initialization code will be slower because ICU has more information we cache. I am not really worried about this scenario.

**Comment by danmosemsft** [comment] 2020-08-02 21:54
Can we tweak the scenario somehow to avoid measuring the warm up?

**Comment by tarekgh** [comment] 2020-08-02 21:58
I am keeping this opened to find out if we tweak the test or I can find a workaround in the code to avoid the re-initialization in some cases. linking here the issue I discussed with Adam https://github.com/dotnet/runtime/issues/31273.

**Comment by adamsitnik** [comment] 2020-08-17 19:25
I've confirmed that this is caused by ICU

|               Method | culturestring | 3.1 Mean |    5.0 ICU |   5.0 NLS| 
|--------------------- |-------------- |---------:|-----------:|---------:|
| ToStringHebrewIsrael |             ? | 540.1 ns |   463.3 ns | 518.3 ns | 
|             ToString |               | 254.0 ns |   248.9 ns | 245.7 ns | 
|                Parse |               | 466.9 ns |   423.7 ns | 424.7 ns | 
|             ToString |            da | 247.5 ns |   234.0 ns | 241.1 ns | 
|                Parse |            da | 551.2 ns |   449.3 ns | 515.6 ns | 
|             ToString |            fr | 251.5 ns |   246.4 ns | 244.3 ns | 
|                Parse |            fr | 466.5 ns |   424.7 ns | 440.2 ns | 
|             ToString |            ja | 258.1 ns |   243.5 ns | 245.4 ns | 
|                Parse |            ja | 482.1 ns | 5,078.9 ns | 456.9 ns | 

> I am keeping this opened to find out if we tweak the test or I can find a workaround in the code to avoid the re-initialization in some cases

@tarekgh Since this is the same problem as https://github.com/dotnet/runtime/issues/31273 I hope that it's OK if I close this issue, add it to #40942 and keep the older issue opened (#31273) while setting the milestone of older issue to 5.0?

**Closed by adamsitnik** 2020-08-17 19:25 UTC
Labels: arch-x64, area-System.Globalization, os-windows, tenet-performance
