### ISSUE TITLE
int.TryParse has become ambigous when used with dynamic

### ISSUE THREAD

**Issue by LunicLynx** [dotnet/runtime#109117] opened 2024-10-22 13:50 UTC
Related to: #94422

This code started to fail with .NET 8

```csharp
dynamic x = new List<string> { null };
int.TryParse(x[0], out int i);
Console.WriteLine(i);
```

The snippet is certainly non sensical, but this was previously working without an exception. TryParse just returning `false`.

I noticed this for partial views in asp.net, if they are not typed they are dynamic.

I do not expect a fix, just wanted to document this edge case here.

**Comment by tannergooding** [comment] 2024-10-28 16:11
Closing as a duplicate of https://github.com/dotnet/runtime/issues/94422

New overloads can sometimes break reflection, dynamic, and other surface area which do not have the most up to date language specific overload resolution rules.

**Closed by tannergooding** 2024-10-28 16:11 UTC
Labels: area-System.Runtime, untriaged
