### ISSUE TITLE
API Proposal: IDataRecord IsDbNullAsync

### ISSUE THREAD

**Issue by rgarrison12345** [dotnet/runtime#36168] opened 2020-05-09 19:23 UTC
I have a use case where I am retrieving values from an instance of IDataRecord in an async function.  I'd like to do asynchronous operations when available.  I noticed that IsDbNullAsync is not a part of IDataRecord but it is a member of DbDataReader as a virtual member.

I think adding this member to IDataRecord will be more inline with today's asynchronous methods and will not cause an issue with existing classes that inherit from DbDataReader.  But may cause an issue with those that don't or just implement IDataRecord.

**Comment by roji** [comment] 2020-06-23 17:41
Duplicate of #26505

**Comment by roji** [comment] 2020-06-23 17:43
@rgarrison12345 ADO interfaces such as IDataRecord and IDbConnection are mostly a legacy detail - all new APIs are introduced on the base classes instead. Also, is there any reason you can't use DbDataReader instead of IDataRecord?

Am closing this as a duplicate for now, but we can continue discussing.

**Closed by roji** 2020-06-23 17:43 UTC
Labels: area-System.Data, untriaged

**Comment by rgarrison12345** [comment] 2020-06-24 00:06
Hello @roji 

I currently have some code that looks like the below.  I am using DbDataReader to iterate through the result set, but I'm mapping a record from the current record in the reader.  I'm Using MapRecord<T> to map an instance of IDataRecord.  If there's a better way to do this I am open to suggestion.

My interest in the approach is there may be some business logic where I need to skip a record from being mapped so I don't pass the entire DbDataReader object.
List<T> returnList = new List<T>();

            //Keep looping through the result set
            while (await reader.ReadAsync(token).ConfigureAwait(false) == true)
            {
                //Return this object
                returnList.Add(MapRecord<T>(reader));
            }

            return returnList;

**Comment by roji** [comment] 2020-06-25 01:07
There's not a lot of code in your sample to give me context, but you could simply have MapRecord accept the reader as a DbDataReader and access all functionality there. It's true that this may expose unwanted methods (e.g. Read, NextResult), but if you really care about that you can wrap the reader in your own facade which would hide those (not unlike what IDataRecord provides).

One additional comment that may be more important than the above: unless you've specified CommandBehavior.SequentialAccess, using IsDbNullAsync (or any other async field access method) is likely to be the wrong thing to do. Without SequentialAccess, the reader is supposed to support random column access (including going back), which typically means that the provider buffers the entire row in memory. That means that accessing any column data is going to be synchronous anyway, and calling the async method can only add overhead. If your rows are expected to be very large, then SequentialAccess does make sense, and in that case IsDbNullAsync is useful.

**Comment by rgarrison12345** [comment] 2020-06-25 19:17
Thanks for the input @roji .  The code I posted is actually the full method minus the name and signature.  I appreciate the recommendation.  Now that I have an understanding about how the reader is designed to work, I think my recommendation is fine closing out.
