### ISSUE TITLE
Test failure _AdvSimd_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Program.VectorLookupExtension_3_SByte()

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#84554] opened 2023-04-10 01:12 UTC
Run: [runtime-coreclr jitstress 20230408.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=232678&view=ms.vss-test-web.build-test-results-tab&runId=4421098&resultId=117413&paneView=debug)

Failed test:
```
coreclr windows arm64 Checked jitstress1 @ Windows.11.Arm64.Open

- _AdvSimd_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Program.VectorLookupExtension_3_SByte()
- _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.VectorLookupExtension_2_Byte()

coreclr linux arm64 Checked jitstress1 @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8

- _AdvSimd_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Program.VectorLookupExtension_3_SByte()
- _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.VectorLookupExtension_2_Byte()

coreclr osx arm64 Checked jitstress1 @ OSX.1200.ARM64.Open

- _AdvSimd_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Program.VectorLookupExtension_3_SByte()
- _AdvSimd_Arm64_ro::JIT.HardwareIntrinsics.Arm._AdvSimd.Arm64.Program.VectorLookupExtension_2_Byte()
```
**Error message:**
```
One or more scenarios did not complete as expected.


Stack trace
   at JIT.HardwareIntrinsics.Arm._AdvSimd.Program.VectorLookupExtension_3_SByte() in /__w/1/s/artifacts/tests/coreclr/obj/AnyOS.x64.Checked/Managed/JIT/HardwareIntrinsics/Arm/AdvSimd/AdvSimd_ro/AdvSimd_ro/gen/VectorTableLookupExtension3.Vector64.SByte.cs:line 60
   at Program.&lt;&lt;Main&gt;$&gt;g__TestExecutor45|0_44(StreamWriter tempLogSw, StreamWriter statsCsvSw, &lt;&gt;c__DisplayClass0_0&amp;)
```

**Comment by kunalspathak** [comment] 2023-04-10 04:01
Duplicate of https://github.com/dotnet/runtime/issues/84536

**Closed by kunalspathak** 2023-04-10 04:01 UTC
Labels: arch-arm64, os-linux, os-mac-os-x, os-windows, JitStress, area-CodeGen-coreclr, untriaged
