### ISSUE TITLE
[Question] Working around Thread Non-PreEmptive Check

### ISSUE THREAD

**Issue by Sewer56** [dotnet/runtime#82684] opened 2023-02-26 16:27 UTC
# Background

As an author of one of the various hooking libraries for .NET [[Reloaded.Hooks]](https://github.com/Reloaded-Project/Reloaded.Hooks), I started working on a high performance User Space Virtual File System using .NET as an experiment [for fun and science] where the user can overlay multiple folders together to act as 1 folder within the current process.  

During this process, an old emergent recurring low-level issue has come up again. Usually in the past I have worked around this but, I figure I'd finally ask the runtime folks if anyone has a potential idea of a high performance workaround [current workaround is slow] that doesn't involve a separate native code project [some ASM is okay!].  

The problem is certain APIs that can be called in the rare path of a Reverse P/Invoke [Native->Managed] transition (e.g. `CloseHandle` for threads), which make it impossible to hook those methods for the following reasons:  

- Infinite Recursion [solvable]  
- Error from thread already being in non-preemptive [currently not solvable]  
  - i.e. `Attempted to call a UnmanagedCallersOnly method from managed code.` after finding out `thread->PreemptiveGCDisabled()`

The second problem is particularly problematic; because even if you solve the recursion problem and allow max 1 call per thread; on a recursive call the transition stub will believe the thread is *not in pre-emptive mode*, and error.

Example Stack Trace: [Pastebin](https://pastebin.com/r4KdrMR9).  

I will be using `CloseHandle` as an example as that's the one function where it doesn't seem possible to work around in a high performance manner.  

# My Current Workaround

Calling WinAPI to determine whether the handle is a non-Thread handle.  

Problem: This solution is ***very, very slow***, ~140ns per iteration on a 5900X.  
This is unacceptable.  

File Filter in x86 ASM [FASM]

```csharp
"use32",
                
// We put called address in EDI
"push edi", // backup EDI (it's non-volatile)
"push dword [esp+8]", // push handle
                
// Call Kernel32.GetFileType (or equivalent) to determine handle is file handle [or at least non-thread]
// There are also other options like NtQueryObject; this one is just the simplest and filters out to what I needed.
$"mov edi, {getFileTypeAddr}", 
$"call edi",
                
// Check result
$"cmp eax, 1",
$"jne exit",
                    
    // It's a file, let's fire our callback.
    "push dword [esp+8]", // push handle
    $"mov edi, {closeHandleCallbackAddr}",
    $"call edi",

$"exit:",
$"pop edi",
```

As a result, I'm not sure how I can resolve this problem [without delegating to native code] in a relatively high performance manner.  
On a recursive call [during RPI], error throws because believes. 

# Non-Solutions

## Thread Lock

ASM Implementation [x86 FASM]

```csharp
"push esi",
                
// EAX, ECX, EDX are volatile and free to use per STDCALL convention, rest is backed up
// EAX: Temporary/Scratch Variable
// ECX: Saved Thread ID
// EDX: Thread ID Address
// ESI: Current Thread ID
                
// we put called address in EDI
"mov esi, [fs:18h]",  // get TEB/TIB
"mov esi, [esi+24h]", // <= thread id in esi, can also use WinAPI for this if needed
                
// Check if allow recurse
$"mov ecx, [{threadIdPtr}]",
"cmp ecx, esi",
"je exit",

// Loop
"checkInterlocked:",
    $"lea edx, [{threadIdPtr}]", 
    $"mov eax, {defaultThreadId}", 
    "lock cmpxchg [edx], esi", 
    $"cmp eax, {defaultThreadId}",
    "jne checkInterlocked",

// Fire our callback.
"push dword [esp+8]", // re-push handle
$"mov ecx, {closeHandleCallbackAddr}",
$"call ecx",
$"mov dword [{threadIdPtr}], {defaultThreadId}", // release lock
                    
$"exit:",
"pop esi",
```

C# Equivalent

```csharp
int threadId = // <= Get Thread from TEB/TIB/WinAPI
if (_fieldInterlocked == threadId)
    return _field;
            
while (Interlocked.CompareExchange(ref _fieldInterlocked, threadId, -1) != -1) { }
// Call Callback here // 
_fieldInterlocked = -1;
```

This does not work due to the reason described in the beginning of the issue in `Background`.

## Call Raw .NET Method

a.k.a. `SuppressGCTransitionAttribute` but in reverse.  

Follow `_clrcall` calling convention, and call .NET method directly from native code; having the .NET Code run in cooperative mode.  

The idea here is you could in theory still execute .NET JIT-ted code, as long as you're not interacting with GC allocated memory.  

This appears to not currently be safely possible. *It does seem to work in practice*, BUT the code can get JIT-ted as partially interruptible and inject a GC safe point, i.e. `CORINFO_HELP_POLL_GC`. This is not good; because if a GC is ongoing, and a cooperative/native thread hits the safe point; well, things will go kaboom.

Fully interruptible seems okay from testing; but I have no idea how to force this.

## Questions

Therefore I have a few questions:  

- Would it ever be possible to suppress non-preemptive mode check?  
  - I understand the check is implemented for a very good reason and usually indicates a real runtime problem.

- Alternatively: Is it possible to force code to not inject GC Poll calls in any way?
  - This would be fine, at least for my limited use case. I'm fine working without anything GC for small code slices. [avoid GC holes >.<]

Note: *I have been doing this sort of stuff for a few years and I am fully aware of the runtime dangers involved.*  

I open this issue mainly as a point of documenting a low-level slice of .NET that's been difficult technically to me in the past; since I don't know of any high performance solution that doesn't involve using native code and sharing memory.

**Comment by jkotas** [comment] 2023-02-26 19:54
There is no reliable way to hook arbitrary OS APIs via managed code. You have to use unmanaged code for situations like this.

> I understand the check is implemented for a very good reason and usually indicates a real runtime problem.

If you suppress the check, you are just going to get intermittent impossible-to-debug crashes later. This check ensures that fundamental invariants that the runtime depends on are intact.

Duplicate of https://github.com/dotnet/runtime/issues/78086#issuecomment-1312630265

**Closed by jkotas** 2023-02-26 19:54 UTC
Labels: question, area-Interop-coreclr, untriaged

**Comment by jkotas** [comment] 2023-02-26 19:57
> Fully interruptible seems okay from testing; but I have no idea how to force this.

Fully interruptible code is not okay either. GC polls are injected into fully interruptible code by hijacking the thread execution.

**Comment by Sewer56** [comment] 2023-02-27 10:47
For the record; I completely agree with Jan's response. 

I mostly opened an issue for documentation reasons; to have something I could direct people to when people have questions. Sometimes I have end users of my library running into this edge case, and while I've known about the why and how to trigger it; I've never dug deep enough into CoreCLR to know the lower level gory details, and sometimes things beyond my understanding are brought up, so I was curious if I could get any insight. 

There is some useful background knowledge to be gained from places like the [BoTR [especially clr-abi.md]](https://github.com/dotnet/runtime/tree/main/docs/design/coreclr/botr), [CLR Code Guide](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/clr-code-guide.md) and Matt Warren's [Performance is a Feature!](https://mattwarren.org/) blogs; but you can only learn so much without spending dozens of hours properly studying the CLR yourself, so I figured I'd finally ask.

[Misc Note: From my experience, suppression crashes usually end up in the form of a deadlock. Direct crashes have been a bit more rare, even when stress testing and using `DOTNET_GCStress=C`.]

-----

I do have an actual question though; which provided the motivation for posting after 3-ish years.

- Do any prospects exist for getting the JIT to produce GC-less/untracked code?

Something I've personally adopted for trivial callbacks before, is writing a GC-free implementation of a callback [no roots/gc pointers in registers]; dump the assembly with `DOTNET_JitDisasm` then apply a series of [mostly] regex based transformations to produce code that can be then piped into an assembler [removed GC Polls, fixup CLR specific terminology e.g. 'bword' -> 'dword/qword'] etc. at runtime. This means there isn't a need for a whole separate project, compiler and you get a guarantee of correctness without duplicating over code. 

In theory this could work with `RuntimeHelpers.PrepareMethod()` and following the ABI; provided you can convince the CLR to not track the code [or at the very least insert GC Polls]. It was just something I am curious about. 

I'm aware this is all just a game of whack-a-mole that is best avoided since there are no guarantees of any sort; but sometimes human curiosity triumphs. As they say in Chess: 'If you see a mate in one, look for better'.

**Comment by jkotas** [comment] 2023-02-27 14:28
> Do any prospects exist for getting the JIT to produce GC-less/untracked code?

It is super niche scenario. I do not expect that we are going to build anything like this.
