### ISSUE TITLE
Wrong code generation for Unsafe.AsRef<T>, Read<T> when T is a structure

### ISSUE THREAD

**Issue by Temp1ar** [dotnet/runtime#64802] opened 2022-02-04 10:27 UTC
### Description

Looks like JIT doesn't properly evaluate the size of a structure when emitting Unsafe.AsRef<T> for structures less than 4 bytes consisting of a single primitive type field. I have structure, storing ushort in it and sometimes get AccessViolationException when trying to read it from the memory. 

I created a[ gist in sharplab.io](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgCUBXAOwwEt8YLAMIR8AB14AbGFADKMgG68wMXAG4a9Jq049+ggJI8ZEMfKhKV6mpsayAFtihiAMtmDtufARuo0GDDQA2rIYUBxgGG4AnhAcGAAUMXEYANK8XAAmLPIAjhwwetiSaAwACthgANYMALwM5ACUALqaAMwMuGERGAwAQtEYMKHhkTQA3v5MHcCDMAz40QBqxQW+AL421CHdkcnxSdix8elZOTD5hXzFpRXVdQ0t7Z27vQ7QGCM9E1PEHbj2D4LZarGAbLY7UZRI4pQ7HNIZbJ5ApFErlSo1epNVq0f6vBhGT6vH7UAJ/BgZXqLFaSNY0TZ+bZfPYwg77BFnZFXXg3dH3LFPXEvKEMFwQLgAc2ZGBJZI6knFEuBNLp1AZzzI2gA7AxJtQAJBBABSvAwAHFCjJlAkMNExDAIAAzBKzIaNRqlE3my1Qa22+1OhIDIbS904w1ei1cK1gG12h3OgEfd2e01RmNxgPO95QIlQsM0CNpn1++OBykphiRkux/0JhKE0OCove6O+2tl50KyWV6tt0tZpKKpvhwvk5hIBjcXDYR3zAAqDAtGAAPPOAHwJYgoABUDGwjV1hf1TB1AFUuDO5ywAIK4NgwR1rzcHtQBd8BQvrD/0mhAA=) to illustrate the case.

### Reproduction Steps

```
[StructLayout(LayoutKind.Sequential, Pack = 1)]
public struct ShortStruct
{
  public short myValue;
}

public class Program {
	public static unsafe T Get<T>(void* a) {
		 return Unsafe.AsRef<T>(a);       
	}

        public unsafe static void Main() {
            int a = 1;
            var x = Get<ShortStruct>(&a);
            Console.WriteLine(x);
        }
}
```

### Expected behavior

I expect 2 bytes will be read and the generated code be equivalent to 
```
Program.Get[[System.Int16, System.Private.CoreLib]](Void*)
    L0000: movsx rax, word ptr [rcx]
    L0004: ret
```

### Actual behavior

It actually tries to read 4 bytes
```
Program.Get[[ShortStruct, _]](Void*)
    L0000: mov eax, [rcx]
    L0002: ret
```

### Regression?

Yes, if I switch the target to .NET Framework (x64) in that sharplab.io gist - everything is generating correctly
```
Program.Get[[System.Int16, mscorlib]](Void*)
    L0000: mov rax, rcx
    L0003: movsx rax, word [rax]
    L0007: ret

Program.Get[[ShortStruct, _]](Void*)
    L0000: mov rax, rcx
    L0003: movsx rax, word [rax]
    L0007: ret
```

### Configuration

At least .NET 6.0 (x64) is affected

**Comment by jakobbotsch** [comment] 2022-02-04 12:18
Duplicate of #58874

**Closed by jakobbotsch** 2022-02-04 12:18 UTC
Labels: area-CodeGen-coreclr, untriaged

**Comment by jakobbotsch** [comment] 2022-02-04 12:21
Are you hitting this in production after migrating to .NET 6? We might consider bumping the priority of a fix.

**Comment by Temp1ar** [comment] 2022-02-04 14:50
Yes, we see this in production, but I'm not sure this is happen after migration to .NET 6 or not. We just found more or less stable repro steps.
