### ISSUE TITLE
Allow custom TState to be passed into Linq Extension methods to prevent closures

### ISSUE THREAD

**Issue by toupswork** [dotnet/runtime#107010] opened 2024-08-27 01:54 UTC
### Background and motivation

When using linq, often lambdas create closures, especially with the `.Select` function.

 Sure we can prevent closures by writing our own functions without using linq, but then we'd lose out on performance benefits in Linq, including, but not limited to SIMD optimizations within linq.

**TO BE CLEAR**: Ideally all Linq extension methods will take a `TContext` overload, but `Select` is the one I wish had it the most.

What I'd like is if the `Select` function worked similar to how things such as `String.Create` work where there is an overload that takes in a generic `TContext` that allows you to pass dependencies into your lambda without creating a closure.

### API Usage
Example
```C#
string[] fruits = ["apple", "banana", "mango", "orange","passionfruit", "grape" ];

// some dependency
var fruitTypeResolver = new FruitTypeResolver();

// pass in dependency without creating a closure
var fruitTypes = fruits.Select(fruitTypeResolver, (state, fruit) => state.ResolveFruitType(fruit));

```
### API Proposal
So I guess the signature for the new Select function that takes in a TContext is: 
```C#
public static IEnumerable<TResult> Select<TSource, TContext, TResult>(
    this IEnumerable<TSource> source,
    TContext context,
    Func<TContext, TSource, TResult> selector);
```
I can get why an overload might be frowned upon, but what about this alternative where you call `.WithContext(context)`?

### Alternative Designs

Maybe add a extension function such as `WithContext()`

```C#
public static ContextualEnumerable<TSource, TContext> WithContext<TSource, TContext>(
    this IEnumerable<TSource> source,
    TContext context)
{
    return new ContextualEnumerable<TSource, TContext>(source, context);
}
```
EXAMPLE:
```C#
string[] fruits = [ "apple", "banana", "mango", "orange", "passionfruit", "grape" ];
var fruitTypeResolver = new FruitTypeResolver();

// Apply WithContext and then use Select with the context automatically passed to the lambda
var fruitTypes = fruits
    .WithContext(fruitTypeResolver)
    .Select((resolver, fruit) => resolver.ResolveFruitType(fruit))
    .Where((resolver, fruitType) => resolver.IsPreferredFruitType(fruitType));

```

**Comment by teo-tsirpanis** [comment] 2024-08-27 02:00
> SIMD optimizations within linq

I believe these are extremely and will most likely not activate after a `Select` either way. If you want to rely on hardware acceleration of an operation, you should use something like `TensorPrimitives`, which accepts spans instead of enumerables.

**Comment by toupswork** [comment] 2024-08-27 02:02
> > SIMD optimizations within linq
> 
> I believe these are extremely and will most likely not activate after a `Select` either way. If you want to rely on hardware acceleration of an operation, you should use something like `TensorPrimitives`, which accepts spans instead of enumerables.

Right. Select is not an example of losing SIMD; ideally I'd like for all of the linq extension methods to have a TContext overload, but I am using Select because this is where the majority of closures are created.

**Comment by huoyaoyuan** [comment] 2024-08-27 02:13
Duplicate of #94654

**Comment by toupswork** [comment] 2024-08-27 02:18
> Duplicate of #94654

What about the alternative I provided though? Maybe that would be more digestible than the original?

**Comment by toupswork** [comment] 2024-08-27 07:30
Thanks to @stephentoub, "The .NET God", and many others have spent so much time trying to squeeze out every last drop of performance in .NET. So many other APIs have been updated to allow for passing a state parameter.

The intransigence against wanting to implement ways to eliminate closures in Linq is just so surprising. 

in the past the argument was, "well, if you're that concerned about performance, just don't use linq" , which had merit then, but now with everything that was done to improve linq, I think it's possible that implementing your own would have more performance degradation than just living with the closure problem.

**Comment by eiriktsarpalis** [comment] 2024-08-27 09:41
> So many other APIs have been updated to allow for passing a state parameter.

> The intransigence against wanting to implement ways to eliminate closures in Linq is just so surprising.

Unlike many low-level callback APIs like `System.Timer` or `String.Create`, LINQ is a high-level _composable_ abstraction that prioritizes user-friendliness over performance. Yes, we could expose overloads for every single method to accept a state parameter, however the amount of state management that this would introduce in a non-trivial LINQ expression defeats the purpose of using LINQ over procedural looping. While we've applied a bunch of optimizations, these typically tend to focus on keeping allocations from happening behind the scenes (avoiding `Enumerator` allocations, operator fusion, etc.) without introducing complexity in the user experience. 

A certain degree of allocations come with the territory when using LINQ, since you need to allocate at least one `IEnumerable` per node inside a LINQ expression. Avoiding these altogether is possible, however this typically requires some form of metaprogramming that is beyond the scope of `System.Linq` itself. Examples of such approaches include [LinqOptimizer](https://nessos.github.io/LinqOptimizer/) or [Strymonas](https://strymonas.github.io/).

**Comment by toupswork** [comment] 2024-08-27 16:34
> > So many other APIs have been updated to allow for passing a state parameter.
> 
> > The intransigence against wanting to implement ways to eliminate closures in Linq is just so surprising.
> 
> Unlike many low-level callback APIs like `System.Timer` or `String.Create`, LINQ is a _composable_ abstraction that prioritizes user-friendliness over performance. Yes, we could expose overloads for every single method to accept a state parameter, however the amount of state management that this would introduce in a non-trivial LINQ expression defeats the purpose of using LINQ over procedural looping. While we've applied a bunch of optimizations, these typically tend to focus on keeping allocations from happening behind the scenes (avoiding `Enumerator` allocations, operator fusion, etc.) without introducing complexity in the user experience.
> 
> A certain degree of allocations come with the territory when using LINQ, since you need to allocate at least one `IEnumerable` per node inside a LINQ expression. Avoiding these altogether is possible, however this typically requires some form of metaprogramming that is beyond the scope of `System.Linq` itself. Examples of such approaches include [LinqOptimizer](https://nessos.github.io/LinqOptimizer/) or [Strymonas](https://strymonas.github.io/).

I appreciate you explaining this to me. Thank you!

**Closed** 2024-08-27 18:42 UTC
Labels: api-suggestion, area-System.Linq, untriaged
