### ISSUE TITLE
There are no dedicated DateOnly and TimeOnly type converters

### ISSUE THREAD

**Issue by darjanbogdan** [dotnet/runtime#74682] opened 2022-08-26 21:29 UTC
Currently `TypeDescriptor.GetConverter` methods return default `System.ComponentModel.TypeConverter` instances for `DateOnly` and `TimeOnly` types. It looks like `Time/DateOnlyTypeConverter` implementation is missing?

This may lead to subtle "bugs" (in the case of using `var` or more generic code) in which `IsValid` method always returns `false`. In the case of mentioned types.

Example:
```csharp
DateOnly date = DateOnly.MaxValue;
var converter = TypeDescriptor.GetConverter(date);
converter.GetType().FullName.Dump(); // Output: System.ComponentModel.TypeConverter

string minDate = $"{DateOnly.MinValue}";
converter.IsValid(minDate).Dump(); // Outputs: false
```

I wonder if it would be beneficial to throw an exception in case of an unsupported type. But it would be a breaking change though.

Not sure if that was an intentional decision, but thought would be good to share.

**Comment by eerhardt** [comment] 2022-08-26 21:33
Duplicate of https://github.com/dotnet/runtime/issues/68743.

**Closed by eerhardt** 2022-08-26 21:33 UTC
Labels: area-System.ComponentModel, untriaged
