### ISSUE TITLE
iOS: System.Net.NetworkInformation.Ping.Send throws System.Net.NetworkInformation.PingException: An exception occurred during a Ping request.

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#41355] opened 2020-08-25 20:49 UTC
### Description

Repro:

```csharp
var p = new Ping ();
p.Send ("localhost");
```

result:

```
<System.Net.NetworkInformation.PingException: An exception occurred during a Ping request.
 ---> System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.EnsureInitialized()
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Net.NetworkInformation.Ping.SendWithPingUtility(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options)
   at System.Net.NetworkInformation.Ping.SendPingCore(IPAddress address, Byte[] buffer, Int32 timeout, PingOptions options)
   at System.Net.NetworkInformation.Ping.GetAddressAndSend(String hostNameOrAddress, Int32 timeout, Byte[] buffer, PingOptions options)
   --- End of inner exception stack trace ---
   at System.Net.NetworkInformation.Ping.GetAddressAndSend(String hostNameOrAddress, Int32 timeout, Byte[] buffer, PingOptions options)
   at System.Net.NetworkInformation.Ping.Send(String hostNameOrAddress, Int32 timeout, Byte[] buffer, PingOptions options)
   at System.Net.NetworkInformation.Ping.Send(String hostNameOrAddress, Int32 timeout, Byte[] buffer)
   at System.Net.NetworkInformation.Ping.Send(String hostNameOrAddress)
   at LinkSdk.DllImportTest.<>c__DisplayClass3_0.<LackOfCapget>b__0() in [...]/xamarin-macios/tests/linker/ios/link sdk/DllImportTest.cs:line 88
```

I'm not sure what the behavior/result should be (the ideal is probably that it should just work, but that would probably need a very different implementation - see also https://xamarin.github.io/bugzilla-archives/96/964/bug.html), but I don't think it should be a PingException. Maybe a PlatformNotSupportedException?

The stack trace also shows that the current code tries to launch another process. That doesn't work on any of Apple's mobile platforms. Most of the System.Diagnostics.Process class should probably just throw PlatformNotSupportedException.

### Configuration

.NET 5.0.100-rc.1.20414.5
iOS BCL (microsoft.netcore.app.runtime.ios-x64/5.0.0-rc.1.20404.16)

**Comment by wfurt** [comment] 2020-08-25 20:53
This dup of #36890 and #36941.
PNSP is reasonable to me. I don't think #36941 will get done for 5.0.

cc: @marek-safar

**Comment by marek-safar** [comment] 2020-08-25 21:08
Closing as duplicate of #36941.

**Closed by marek-safar** 2020-08-25 21:08 UTC
Labels: area-System.Net, os-ios, untriaged
