### ISSUE TITLE
Support Single File Diagnostics

### ISSUE THREAD

**Issue by tommcdon** [dotnet/runtime#45382] opened 2020-11-30 21:06 UTC
This issue is tracking the work necessary to support single-file diagnostics.  Our goal is to deliver parity with debugging and profiling with framework dependent applications where applicable.  

- [x] Reduce long term maintenance by moving to the dotnet/diagnostics repo
- [x]  `dbgshim` needs an ELF parser to identify if a module is CoreCLR + extract the DAC/DBI keys. There's currently a copy in use in the runtime for `createdump` and the DAC on Linux dumps and one used in SOS for `OpenVirtualProcess`.
- [x] `dbgshim` OVP needs updated `ILibraryProvider` callback interface that accepts buildid information for DAC/DBI. This receives the DAC/DBI keys that were retrieved.
- [x] `dbgshim` live debugging case needs to integrate `ILibraryProvider` so that the caller can locate DAC/DBI instead of `dbgshim`.
  - We search for CoreCLR in the module list. On Linux and macOS we have the PAL runtime startup helper: https://github.com/dotnet/runtime/blob/6438d08ae76587bf4c70ab06da4beca245af04da/src/coreclr/src/pal/src/thread/process.cpp#L1654
  - Use the path to coreclr as a lookup location for DBI: F:\github\coreclr\src\dlls\dbgshim\dbgshim.cpp:382
  - provide the coreclr base address to DBI: 
    ```
    mscordbi!Cordb::SetTargetCLR 
    mscordbi!CoreCLRCreateCordbObjectEx 
    mscordbi!CoreCLRCreateCordbObject dbgshim!CreateCoreDbgWithoutSandboxSupport 
    dbgshim!CreateCoreDbg dbgshim!RuntimeStartupHelper::InvokeStartupCallback 
    dbgshim!RuntimeStartupHandler 
    dbgshim!InvokeStartupCallback dbgshim!StartupHelperThread
    ```		
- [ ]  `createdump` and a portion of the DAC need to be linked into the host
- [x] The linked version of `createdump` needs to be modified to use a linked in DAC rather than searching for it.
- F:\github\coreclr\src\debug\createdump\crashinfo.cpp(374) - cache coreclr path unneeded
- F:\github\coreclr\src\debug\createdump\crashinfo.cpp(620) - add alternate path to construct pfnCLRDataCreateInstance
- [x] Mac OS superhost debugging support https://github.com/dotnet/runtime/issues/38901
- [x] Link DotNetRuntimeInfo into the superhost https://github.com/dotnet/diagnostics/issues/1764
- [x] https://github.com/dotnet/diagnostics/issues/2438#issuecomment-931490245

**Comment by clairernovotny** [comment] 2021-06-09 19:57
Is there any updates here on progress? This is also affecting attaching to .NET 5 & 6 apps in an MSIX that aren't single file.

**Comment by hoyosjs** [comment] 2021-06-09 20:12
The work for dbgshim needed for msix is planned but not yet fully designed. Other more time sensitive components of single file diagnostics were getting addressed first. Cc @tommcdon

**Comment by michalk-gc** [comment] 2021-07-29 13:23
This one is required so we can e.g. attach a debugger to installed MSIX app. My team has just migrated the app from .NET framework, where it worked, to .NET 5.0 and it turns out that we won't be able to debug it until .NET 7.0? Feels like a big gap to me.

**Comment by yoziv** [comment] 2021-11-10 13:27
debugging in single file mode worked for in .Net 5 and not working in .net 6 , is it only going to be fixed in .net 7?

**Comment by hoyosjs** [comment] 2021-11-10 14:21
@yoziv By debugging you mean using a debugger like VS? I'm sorry this might be causing some issues in your experience... Right now single file is only debuggable through SOS. Single files are a deployment mechanism and they changed quite a bit in .NET 6. There wasn't enough time in .NET 6 to add support to launching/attach to one them. For the inner dev loop, debugging would need to go through the usual app build, and SOS is available for the cases where that doesn't work - like post mortem diagnostics.

**Comment by ssa3512** [comment] 2021-11-14 11:22
@hoyosjs right now you can't even F5 debug a project with single file publish enabled when it is targeting .NET 6 in VS2022. That may be different from what this issue is tracking. Is this issue specifically the ability to attach a debugger to the published application?

https://developercommunity2.visualstudio.com/t/Unable-to-attach-to-CoreCLR-when-debug/1523427?entry=problem&ref=native&refTime=1636746090780&refUserId=8c25c91a-2d4f-6773-b0fa-d18fdec3f989

This feedback is specifically for "press play" debug in .NET 6/VS2022 which does not work.

**Comment by AraHaan** [comment] 2021-11-14 22:48
Currently I bypass this by making ``<PublishSingleFile>`` only happen on ``Release`` configuration, while debug does not do single file at all.

**Comment by hoyosjs** [comment] 2021-11-15 07:14
Sorry - from a scenario perspective this is indeed a regression. I wasn't aware that VS does a use of the publish output to running inner loop scenarios, I expected only build to happen. To achieve this behavior - as @AraHaan says - the best solution is to have this on the project file:

```xml
<PublishSingleFile Condition="'$(Configuration)' == 'Release'">true</PublishSingleFile>
```

The only scenario that this will still fail to cover is doing attach to a running application build outside of the IDE (basically, a release mode attach).

**Comment by avidenic** [comment] 2021-11-16 14:44
Tnx @hoyosjs The workaround works.

**Closed** 2022-04-28 20:03 UTC
Labels: enhancement, area-Diagnostics-coreclr

**Comment by ALIENQuake** [comment] 2022-04-29 21:40
@mikem8361 Many thanks for this!
