### ISSUE TITLE
Test failure  file_io.GetFileSize.test1

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#51831] opened 2021-04-25 06:13 UTC
Run: [runtime-coreclr jitstress-isas-x86 20210424.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1106300&view=ms.vss-test-web.build-test-results-tab&runId=33782256&resultId=110928&paneView=debug)

Failed tests:
CoreCLR OSX x64 Checked jitstress_isas_x86_nohwintrinsic @ OSX.1013.Amd64.Open
```
file_io.GetFileSize.test1
file_io.GetFileSizeEx.test1

Error message:

GetFileSize: ERROR -> Call to SetEndOfFile failed with 112.
```

Failed tests:
```
file_io.SetFilePointer.test5
file_io.SetFilePointer.test6
file_io.SetFilePointer.test7

Error message:

SetFilePointer: ERROR -> Call to SetEndOfFile failed with error code: 112
```

**Comment by VincentBu** [comment] 2021-05-11 02:05
Failed again in [runtime-coreclr outerloop 20210510.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1130595&view=ms.vss-test-web.build-test-results-tab&runId=34330182&resultId=110932&paneView=debug)
```
- file_io.GetFileSize.test1

GetFileSize: ERROR -> Call to SetEndOfFile failed with 112.
```
```
- file_io.GetFileSizeEx.test1

GetFileSizeEx: ERROR -> SetEndOfFile failed due to lack of disk space
```
```
- file_io.SetFilePointer.test5

SetFilePointer: ERROR -> SetEndOfFile failed due to lack of disk space
```
```
- file_io.SetFilePointer.test6
- file_io.SetFilePointer.test7

SetFilePointer: ERROR -> Call to SetEndOfFile failed with error code: 112
```

**Comment by VincentBu** [comment] 2021-07-09 02:08
Run: [runtime-coreclr jitstress 20210707.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1226071&view=ms.vss-test-web.build-test-results-tab&runId=36539602&resultId=110381&paneView=debug)

Failed test:
```
- file_io.GetFileSizeEx.test1
GetFileSizeEx: ERROR -> SetEndOfFile failed due to lack of disk space

- file_io.GetFileSize.test1
GetFileSize: ERROR -> Call to SetEndOfFile failed with 112.

- file_io.SetFilePointer.test5
SetFilePointer: ERROR -> SetEndOfFile failed due to lack of disk space

- file_io.SetFilePointer.test6
- file_io.SetFilePointer.test7
SetFilePointer: ERROR -> Call to SetEndOfFile failed with error code: 112

```

**Comment by janvorli** [comment] 2021-07-26 23:37
I believe this issue is caused by not enough memory on the test device. The test tries to set the file size to about 4GB and there were cases when machines in the CI were getting out of disk space. Closing the issue for now to see if it will repro.

**Closed by janvorli** 2021-07-26 23:37 UTC
Labels: JitStress, arch-x64, area-PAL-coreclr, os-mac-os-x
