### ISSUE TITLE
System.Text.Json: Structs should serialize all public fields

### ISSUE THREAD

**Issue by jessicah** [dotnet/runtime#44009] opened 2020-10-29 04:45 UTC
### Description

Structs should serialize all public fields by default.

### Configuration

.net core 5.0

### Other information

I haven't tried C# 9 record types, but I would assume the behaviour should be the same there too.

**Comment by Symbai** [comment] 2020-10-29 07:35
And can you tell us WHY it should do that?

**Comment by Joe4evr** [comment] 2020-10-29 08:58
Why have you opened a duplicate issue?

**Comment by GrabYourPitchforks** [comment] 2020-10-29 19:07
Possible dupe of https://github.com/dotnet/runtime/issues/876.

**Comment by layomia** [comment] 2020-10-29 20:03
Closing as dupe of https://github.com/dotnet/runtime/issues/44009 and #876.

**Closed by layomia** 2020-10-29 20:03 UTC
Labels: area-System.Text.Json, untriaged
