### ISSUE TITLE
Crash/Unhandled exception with .net runtime upgrade.

### ISSUE THREAD

**Issue by prat-coder** [dotnet/runtime#90869] opened 2023-08-21 03:47 UTC
### Description

There is Windows Desktop Application built with 6.0.20 runtime version. And we package the runtime along with the application. 

But on a fresh machine, if the .net runtime higher than 6.0.20 is already installed(assuming that runtime was upgraded automatically) and Desktop application is looking for 6.0.20 dlls, application crashes as the dlls are not found. 

Is there a way we can know that higher version of runtime is present than the intended one and we have to re-init , so that application works well.

Or what is the recommendation on the upgrade case, how does the application handle. Is there something which can be provided from runtime.

### Reproduction Steps

Have a sample wpf desktop app(6.0.20 runtime version) containing a button. And on button click event, trying to log on console using any member function/enum/property from System.Diagnostics dll. 

If runtime is upgraded to 6.0.21 and in application output as per Visual Studio we see: 
Warning: Unable to load Dynamic Function Table Callback DLL 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.20\mscordaccore.dll'. Call stacks may be truncated. The system cannot find the path specified.
![image (2)](https://github.com/dotnet/runtime/assets/80393975/4c1fcaef-a49b-42df-895a-988115d15a7d)

 
All framework dlls are deleted and show up like this in procexp:
![image (3)](https://github.com/dotnet/runtime/assets/80393975/9f2ed9c0-c8e0-4c65-8e76-ade2809f648e)

### Expected behavior

There should be no exception seen. Application should work well.

### Actual behavior

Application throws unhandled exception.

### Configuration

Application using .net runtime version 6.0.20 . 

Upgrade the runtime on the machine on which application is run to say 6.0.21.

**Comment by vitek-karas** [comment] 2023-08-24 20:04
I tried to repro this, but no luck. What I'm doing is:
```C#
        private void Button_Click(object sender, RoutedEventArgs e)
        {
            System.Diagnostics.Debug.WriteLine("Hello");
        }
```

Could you please clarify what the repro should look like?

Also - would it be possible to paste the exception call stack for the failure you see?

**Comment by prat-coder** [comment] 2023-08-25 05:33
Some more background. It looks like running upgrade in interactive session vs session 0 has a behavior change.

- If I run the sample app have dotnet 6.0.20 and then upgrade using doubleclick of installer to 6.0.21 then app gets closed.
- If instead the upgrade was done using psexec -s "runtime.exe" /q then app doesn't get closed and is in the state shown in screenshots. (Windows Update or SCCM updates might install the dotnetcore in session 0 probably)
- If upgrade was done using psexec -sid "runtime.exe" /q then app gets closed again. So it looks like there is a difference in behavior on where the installer was run (interactive session vs session 0)

We also had a dotnet Windows service in our code base. The behavior is slightly different:
- If upgrade happens in interactive session, then service gets restarted after upgrade automatically.
- If upgrade happens in session 0, the restart of service doesn't happen and it is also in the state where it is loading previous runtime dlls from C:\Config.Msi\xyz

Sample app attached.

**Comment by prat-coder** [comment] 2023-08-25 05:39
[WpfApp3.zip](https://github.com/dotnet/runtime/files/12435920/WpfApp3.zip)



Snapshot of procexp and callstack 
![CallStack](https://github.com/dotnet/runtime/assets/80393975/5c802934-90b5-49c8-8d99-c50c6ba3c6d8)


CrashDump:
https://drive.google.com/file/d/1AnwjS4sP9PAnO4kc40tGrGSNji4-h7YR/view?usp=sharing

**Comment by vitek-karas** [comment] 2023-08-25 15:29
If I read this correctly, the failure only happens if the app is running and the runtime is upgraded "underneath" it, right?
If that's the case, then it's an installer problem - it should not remove the "old" runtime when it's still in use.

@NikolaMilosavljevic for additional comments from the installer side.

**Comment by NikolaMilosavljevic** [comment] 2023-10-17 20:25
We are aware of this issue. Registering your application with restart manager seems to help, but only in that application would get rebooted and restarted after .NET installation/upgrade.

@joeloff is there a master tracking issue for this?

**Comment by logicaloud** [comment] 2023-11-05 21:52
Hi @NikolaMilosavljevic and @joeloff.  There have been several related issues logged over the years (i.e., #60144), I'm sure you are aware of them. It is not a good situation having services running that could fail unexpectedly because of a Windows update some time earlier. At that time customers may not easily make the connection between the update and the failed service, and hence simply consider the .NET software "unreliable".

Could you shed some light on the issue, i.e.:

Is there an ETA for a fix in Windows Update? 

Is there a now a master tracking issue where this Windows Update bug is already tracked? If yes, could it be linked here? If not, could this be pushed along?

**Comment by nipun11092023** [comment] 2023-11-10 18:38
@NikolaMilosavljevic 
We tried registering the application for restart, but this still does not seem to be working.

Steps to reproduce:
1) Write a simple app which has registered for restart (code attached below)
2) install dotnet desktop runtime 6.0.20 
3) Run the app and make sure it is running.
4) install dotnet desktop runtime 6.0.24

Result:
The app does NOT get restarted.
Would you please advise on this ? Is there a plan to fix the dotnet installer to avoid getting into this problematic state ?
[HelloWPF.zip](https://github.com/dotnet/runtime/files/13322367/HelloWPF.zip)

**Comment by NikolaMilosavljevic** [comment] 2023-11-10 19:18
> @NikolaMilosavljevic We tried registering the application for restart, but this still does not seem to be working.
> 
> Steps to reproduce:
> 
> 1. Write a simple app which has registered for restart (code attached below)
> 2. install dotnet desktop runtime 6.0.20
> 3. Run the app and make sure it is running.
> 4. install dotnet desktop runtime 6.0.24 while the app is running.
> 
> Result: The app does NOT get restarted. Would you please advise on this ? Is there a plan to fix the dotnet installer to avoid getting into this problematic state ? [HelloWPF.zip](https://github.com/dotnet/runtime/files/13322367/HelloWPF.zip)

There seems to be some additional issues with WPF apps. @joeloff you did a thorough investigation on this - is that documented somewhere?

**Comment by logicaloud** [comment] 2023-11-10 20:46
We have a multi-platform application running Windows services with a WPF frontend. Ideally, we'd like to avoid diving into `RegisterApplicationRestart`, but it sounds like that at least, for the services part, `RegisterApplicationRestart` would prevent issues, is that correct?

Apologies for my simplistic view of the problem, but could the .NET installer/Windows Update not "keep things in place" until the next full restart?

**Comment by joeloff** [comment] 2024-01-02 20:05
@NikolaMilosavljevic we don't have an issue and the installer cannot detect files being used. That's all part of the installer service itself. Also note that it only works if the service considers the files to be in use and there are cases where RM won't work at all because sessions are restricted to individual MSI transactions and things like the desktop runtime spans multiple MSIs that will either close and fail to restart an app or close and restart applications multiple times.

**Comment by NikolaMilosavljevic** [comment] 2024-04-04 19:35
Closing in favor of the original issue (https://github.com/dotnet/runtime/issues/60144) which offers some options and workarounds and is the best place to track any new developments.

**Closed by NikolaMilosavljevic** 2024-04-04 19:35 UTC
Labels: area-Setup, untriaged
