### ISSUE TITLE
System.IntPtr casting from long give wrong value

### ISSUE THREAD

**Issue by CorrM** [dotnet/runtime#32416] opened 2020-02-17 00:45 UTC
in example

```
long gg = long.Parse(mapSplit[0].Split("-")[0], NumberStyles.HexNumber); // 0x00000000ff07b000
var startAddress = (IntPtr)gg; // 0xffffffffff07b000
```

what the problem !!, why casting change the value .!

**Comment by jkotas** [comment] 2020-02-17 01:13
Could you please share a few more details to allow us reproduce the problem?
- The type and value of `mapSplit[0].Split("-")[0]` when you see this problem
- The .NET Runtime version and OS version that you see this problem on

**Comment by CorrM** [comment] 2020-02-17 01:28
mapSplit[0].Split("-")[0] is `string` "ff07b000".
`Xamarin Android`, `.NET Standard 2.1` => Win10

**Comment by EgorBo** [comment] 2020-02-17 10:15
I suspect it was fixed in https://github.com/mono/mono/pull/18222

**Comment by CorrM** [comment] 2020-02-17 21:59
@EgorBo 
Tested too in .Net Stander 2.1 Lib, Same problem when casting (same code above).

**Comment by naricc** [comment] 2020-02-18 00:12
@EgorBo

It looks like that problem, although as far as I know, that bug only ever manifest when using LLVM. Although the actual bug was in the Mini IR optimization passes, so maybe it is possible to trigger with out using LLVM in the right circumstance.

**Comment by CorrM** [comment] 2020-02-18 01:49
@naricc @EgorBo 
Ok, Here another problem on casting !,
```
// T          => long
// byteArray  => { 0x00, 0x14, 0x27, 0xc1 }
// index      => 0
(T)(object)BitConverter.ToInt32(byteArray, index); // Return 0xffffffffc1271400 !!
```
that's casting `int` to `long`.
again it's `Xamarin Android`.

**.Net 4.7.2** : Same Problem !!
```
byte[] byteArray = { 0x00, 0x14, 0x27, 0xC1 };
long v = (long)BitConverter.ToInt32(byteArray, 0); Return 0xffffffffc1271400 !!
```

**Comment by svick** [comment] 2020-02-18 07:51
@CorrM I think that's the correct behavior. The call to `BitConverter.ToInt32` returns 0xC1271400 hexadecimal, which is -1054403584 decimal. If you cast it to long, you get -1054403584 decimal, which is 0xFFFFFFFFC1271400 in 64-bit hexadecimal.

In other words, since the highest bit of the 32-bit number is 1, the highest 33 bits of the 64-bit number have to be 1, due to sign extension.

**Comment by CorrM** [comment] 2020-02-18 08:49
@svick then who to keep hex (0xC1271400) as long ! i mean as `0x00000000C1271400`. !

**Comment by svick** [comment] 2020-02-18 09:55
Then you want to use unsigned conversion, for example:

```c#
long v = BitConverter.ToUInt32(byteArray, 0);
```

Also, consider using `ulong` instead of `long`, since it seems your values are not actually signed.

**Comment by CorrM** [comment] 2020-02-18 11:18
@svick ok what about casting long to intptr .?!

**Comment by svick** [comment] 2020-02-18 13:35
As far as I can tell, your original code was correct for that case. The problem is that on Xamarin Android, you encountered the bug mentioned by @EgorBo, I think. If you're looking for a workaround, I don't have an easy way to test this, so I can't help you.

**Comment by CorrM** [comment] 2020-02-20 19:19
Updates .?!

**Comment by CorrM** [comment] 2020-02-25 02:21
any workarround .?, i can't complete my work with this bug !!.
@svick @EgorBo @naricc

**Comment by CorrM** [comment] 2020-02-27 12:17
@EgorBo @svick 

**Here some new information**
`IntPtr.Size = 4`.

**ULONG & UIntPtr**
:white_check_mark:
```
ulong gi = 0xff07b000;
var gg1 = (UIntPtr)gi;
Log.WriteLine(LogPriority.Debug, "CorrM", $"{gg1.ToUInt64():X}");
// 02-27 20:04:19.207 D/CorrM   ( 8043): FF07B000
```
**LONG & IntPtr**
:x: Same Problem

```
long gi = 0xff07b000;
var gg1 = (IntPtr)gi;
Log.WriteLine(LogPriority.Debug, "CorrM", $"{gg1.ToInt64():X}");
02-27 20:10:33.667 D/CorrM   ( 8935): FFFFFFFFFF07B000
```


Why `VS2019` Show As 8byte if its 4bytes !! (i think that is a bug in VS)
![27-2-2020 2-00-27 PM](https://user-images.githubusercontent.com/5868825/75443185-8bcb0e00-5969-11ea-9044-619ed151bbe4.png)

**Comment by EgorBo** [comment] 2020-02-27 13:17
> @EgorBo @svick
> 
> **Here some new information**
> `IntPtr.Size = 4`.
> 
> **LONG & UIntPtr**
> ✅
> 
> ```
> long gi = 0xff07b000;
> var gg1 = (UIntPtr)gi;
> Log.WriteLine(LogPriority.Debug, "CorrM", $"{gg1.ToUInt64():X}");
> // 02-27 20:04:19.207 D/CorrM   ( 8043): FF07B000
> ```
> 
> **LONG & IntPtr**
> ❌ Same Problem
> 
> ```
> long gi = 0xff07b000;
> var gg1 = (IntPtr)gi;
> Log.WriteLine(LogPriority.Debug, "CorrM", $"{gg1.ToInt64():X}");
> // 02-27 20:10:33.667 D/CorrM   ( 8935): FFFFFFFFFF07B000
> ```
> 
> Why `VS2019` Show As 8byte if its 4bytes !! (i think that is a bug in VS)
> ![27-2-2020 2-00-27 PM](https://user-images.githubusercontent.com/5868825/75443185-8bcb0e00-5969-11ea-9044-619ed151bbe4.png)

You can't cast `0xff07b000` to IntPtr on x86, it should throw ArithmeticException (even under `unchecked {}` context).

**Comment by CorrM** [comment] 2020-02-27 13:26
No Execption Thrown, it's just pass as nothing !!, and as i know even it's x86 .Net will store long (64bit) into 8byte as here
https://stackoverflow.com/questions/22363503/will-a-long-integer-work-on-a-32-bit-system

**Comment by EgorBo** [comment] 2020-02-27 13:35
> No Execption Thrown, it's just pass as nothing !!, and as i know even it's x86 .Net will store long (64bit) into 8byte as here
> https://stackoverflow.com/questions/22363503/will-a-long-integer-work-on-a-32-bit-system

Seems like a bug in Mono (non netcore one), it should throw that exception just like CoreCLR does.

**Comment by CorrM** [comment] 2020-02-27 13:41
@EgorBo ok, i think u must edit this issue tag and title

**Comment by danmosemsft** [comment] 2020-08-12 23:27
@lambdageek are you planning on handling this? Can we move this out of the 5.0 milestone or is it required in order to ship ?

**Comment by jeffhandley** [comment] 2020-08-26 20:00
> @lambdageek are you planning on handling this? Can we move this out of the 5.0 milestone or is it required in order to ship ?

Hi @lambdageek - checking in on this.  Thanks!

**Comment by jeffhandley** [comment] 2020-09-02 18:48
@marek-safar Is this still being tracked for 5.0.0 on your team?

**Comment by marek-safar** [comment] 2020-09-03 09:24
@EgorBo can we close this issue for netcore?

/cc @SamMonoRT

**Comment by EgorBo** [comment] 2020-09-15 13:23
Ah, sure it was mono/mono specific, sorry for the delayed response.

**Closed by EgorBo** 2020-09-15 13:23 UTC
Labels: area-System.Runtime, os-android, runtime-mono
