### ISSUE TITLE
Runtime exception ConfigurationManager in any UWP release app (or Debug with .net native toolchain)

### ISSUE THREAD

**Issue by mdbill** [dotnet/runtime#46900] opened 2021-01-13 03:36 UTC
To Reproduce:
Start with a Blank App (Universal Windows)
add the nuget  for ConfigurationManager (5.0), and an app.config file.

Then just add...
using System.Configuration;

and...
string sAttr= ConfigurationManager.AppSettings.Get("Key0");

(A console app works. Debug mode works)
But if you run 
 Release mode or
 Debug with .net native toolchain checked.

System.Configuration.ConfigurationErrorsException: 'Configuration system failed to initialize'
MissingMethodException: No parameterless constructor defined for this object.

Also tried ConfigurationManager (4.5)

 The error changes to...
An error occurred creating the configuration section handler for appSettings: The type 'System.Configuration.AppSettingsSection' cannot be found in assembly 'System.Configuration.ConfigurationManager, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

**Comment by safern** [comment] 2021-01-13 22:03
This seems to be happing due to AOT and reflection not working correctly there. 

cc: @tommcdon

**Comment by mdbill** [comment] 2021-01-21 02:14
Can anyone confirm this? Has anyone tried the simple steps to reproduce it?

**Comment by mdbill** [comment] 2021-01-26 22:03
Am I in the right place with this bug report? This is a critical issue. My app is dead.

**Comment by mdbill** [comment] 2021-01-27 23:00
Digging around I did get a PlatformNotSupported exception at one point (among other errors)  Does ConfigurationManager support UWP?

**Comment by mdbill** [comment] 2021-01-28 15:51
This limitation? or bug? causes widespread problems.   For example, Microsoft's Cosmos DB V3 SDK is dependent on this. They have confirmed that UWP support is not available for CosmosDB.  Furthermore, they don't feel they can fix it and are relying on the .net team to fix ConfigurationManager.

**Comment by krwq** [comment] 2021-03-03 11:06
@mdbill if I understand correctly if UWP without native toolchain works but it doesn't with native toolchain enabled I'd assume this is a bug. I do not currently have information if this is officially supported or not, I'll see if I can find more information. Marking as 6.0 until we have better response. I can't promise this will be fixed in this release.

**Comment by krwq** [comment] 2021-03-03 13:40
@mdbill I was able to repro your issue. Can you also point me to CosmosDB issue you mentioned?

After quick investigation I think I found a workaround for you.

Add

```xml
    <Type Name="System.Configuration.ClientConfigurationHost" Dynamic="Required All"/>
    <Type Name="System.Configuration.AppSettingsSection" Dynamic="Required All"/>
```

into `Properties\Default.rd.xml` inside `<Application>` section. Note that using different APIs might trigger other errors and without specific use case it's hard to provide solution.

Simpler workaround is to just disable trimming for the entire assembly - that should not give you any random "Missing type" errors but will increase resulting size of the app:

```xml
<Assembly Name="System.Configuration.ConfigurationManager" Dynamic="Required All" />
```

@eerhardt @tommcdon do you happen to know how to fix this without having to edit Default.rd.xml file? I'm not super familiar with this space.

I'm decreasing priority given there is a workaround.

**Comment by mdbill** [comment] 2021-03-03 15:26
Thanks for the workaround, I haven't tried it yet, but it's good to have some progress/attention on this.

> @mdbill I was able to repro your issue. Can you also point me to CosmosDB issue you mentioned?

Sure, both the V3 and V2 SDKs have dependencies on configurationManager. And both have open bug reports.  The simpler one to repro is V3. Just one line of code to attempt instantiate the CosmosClient class crashes.
https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2049#issuecomment-754904780

In V2, the dependency is in the cosmos.direct.dll, so the crash happens only using direct mode (vs gateway mode)
https://github.com/Azure/azure-cosmos-dotnet-v2/issues/831

**Comment by eerhardt** [comment] 2021-03-03 16:30
> do you happen to know how to fix this without asking users to edit Default.rd.xml file?

Looking at the ILLink warnings in the above console app, I see the following warnings:

```
ILLink : Trim analysis warning IL2057: System.Configuration.ConfigurationErrorsException.ConfigurationErrorsException(SerializationInfo,StreamingContext): Unrecognized value passed to the parameter 'typeName' of method 'System.Type.GetType(String,Boolean)'. It's not possible to guarantee the availability of the target type. [C:\Users\eerhardt\source\repos\ConsoleApp7\ConsoleApp7\ConsoleApp7.csproj]
ILLink : Trim analysis warning IL2067: System.Configuration.TypeUtil.CreateInstance(Type): '#0' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicParameterlessConstructor' in call to 'System.Object System.Activator::CreateInstance(System.Type,System.Boolean)'. The parameter 'type' of method 'System.Configuration.TypeUtil.CreateInstance(Type)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [C:\Users\eerhardt\source\repos\ConsoleApp7\ConsoleApp7\ConsoleApp7.csproj]
ILLink : Trim analysis warning IL2070: System.Configuration.TypeUtil.GetConstructor(Type,Type,Boolean): 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors', 'DynamicallyAccessedMemberTypes.NonPublicConstructors' in call to 'System.Type.GetConstructor(BindingFlags,Binder,CallingConventions,Type[],ParameterModifier[])'. The parameter 'type' of method 'System.Configuration.TypeUtil.GetConstructor(Type,Type,Boolean)' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it is assigned to. [C:\Users\eerhardt\source\repos\ConsoleApp7\ConsoleApp7\ConsoleApp7.csproj]
ILLink : Trim analysis warning IL2057: System.Configuration.TypeUtil.GetImplicitType(String): Unrecognized value passed to the parameter 'typeName' of method 'System.Type.GetType(String)'. It's not possible to guarantee the availability of the target type. [C:\Users\eerhardt\source\repos\ConsoleApp7\ConsoleApp7\ConsoleApp7.csproj]
ILLink : Trim analysis warning IL2026: System.Configuration.TypeUtil.GetImplicitType(String): Using method 'System.Reflection.Assembly.GetType(String,Boolean)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Types might be removed. [C:\Users\eerhardt\source\repos\ConsoleApp7\ConsoleApp7\ConsoleApp7.csproj]
ILLink : Trim analysis warning IL2057: System.Configuration.TypeUtil.GetType(String,Boolean): Unrecognized value passed to the parameter 'typeName' of method 'System.Type.GetType(String,Boolean)'. It's not possible to guarantee the availability of the target type. [C:\Users\eerhardt\source\repos\ConsoleApp7\ConsoleApp7\ConsoleApp7.csproj]
```

So it looks like ConfigurationManager will need some trim annotations to make it trimming safe.

I'm able to reproduce the same error on the latest `net6.0` bits, outside of UWP.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="6.0.0-preview.3.21153.4" />
  </ItemGroup>

</Project>
```

```C#
using System;
using System.Configuration;

namespace ConsoleApp7
{
    class Program
    {
        static void Main(string[] args)
        {
            string sAttr = ConfigurationManager.AppSettings.Get("Key0");
            Console.WriteLine("helo" + sAttr);
        }
    }
}
```

```
❯ dotnet publish -c Release -r win-x64 -p:PublishTrimmed=true -p:TrimMode=link
❯ C:\Users\eerhardt\source\repos\ConsoleApp7\ConsoleApp7\bin\Release\net6.0\win-x64\publish\ConsoleApp7.exe
Unhandled exception. System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize
 ---> System.MissingMethodException: Cannot dynamically create an instance of type 'System.Configuration.ClientConfigurationHost'. Reason: No parameterless constructor defined.
   at System.RuntimeType.ActivatorCache..ctor(RuntimeType rt)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Configuration.TypeUtil.CreateInstance(Type type)
   at System.Configuration.Internal.ConfigSystem.System.Configuration.Internal.IConfigSystem.Init(Type typeConfigHost, Object[] hostInitParams)
   at System.Configuration.ClientConfigurationSystem..ctor()
   at System.Configuration.ConfigurationManager.EnsureConfigurationSystem()
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationManager.EnsureConfigurationSystem()
   at System.Configuration.ConfigurationManager.PrepareConfigSystem()
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.get_AppSettings()
   at ConsoleApp7.Program.Main(String[] args) in C:\Users\eerhardt\source\repos\ConsoleApp7\ConsoleApp7\Program.cs:line 12
```

I've split this off into its own issue: https://github.com/dotnet/runtime/issues/49062. That way this issue can be specifically about UWP.

Adding the trim annotations will fix this in net6.0, but I don't think the UWP tool chain respects them. @MichalStrehovsky would know.

**Comment by mdbill** [comment] 2021-03-03 16:31
Both of the workarounds do make the test case here pass.  Unfortunately, neither fixed the issue with the Cosmos V3 SDK...which is the whole reason I opened this bug report.  
The V2 SDK also still crashes.
@krwq Since you lowered the priority thinking maybe this workaround helps, I'd appreciate the priority going back up.

**Comment by krwq** [comment] 2021-03-03 18:43
@mdbill I can't repro the Cosmos v3 issue after I add `<Assembly Name="System.Configuration.ConfigurationManager" Dynamic="Required All" />` to the Default.rd.xml file.

**Comment by mdbill** [comment] 2021-03-03 23:12
Strange, I was sure it threw an exception, but it did seem to get past the instantiation now that I re-tested it.
I'll try the full app since I still see an exception which may not be related or fatal (Exception thrown: 'System.TypeLoadException' in TestCosmos.UWP.McgInterop.dll)  Thx for testing it!  I probably would not have tried again without new info.

**Comment by krwq** [comment] 2021-03-04 07:50
you might want to disable trimming for all assemblies which cause any issues if you still see errors (better to disable specific types if you care about the size though)

**Comment by mdbill** [comment] 2021-03-04 15:22
Thanks, my full app seems to be working so far, and because you mentioned increase in size, I'm **not** using 
<Assembly Name="System.Configuration.ConfigurationManager" Dynamic="Required All" />
I'm just using....
<Type Name="System.Configuration.ClientConfigurationHost" Dynamic="Required All"/>
<Type Name="System.Configuration.AppSettingsSection" Dynamic="Required All"/>

I still have to re-submit it to the app Store, but I wouldn't think this change will get rejected like it does if I try to turn off .net native or optimization for example.

**Comment by krwq** [comment] 2021-07-14 07:47
I'm closing this issue since @eerhardt has disabled trimming on that library for now (https://github.com/dotnet/runtime/pull/49085) and we have another issue to enable it back with trimmer annotations helping it to preserve the right members or warn the user if they need to do something (https://github.com/dotnet/runtime/issues/49062)

**Closed by krwq** 2021-07-14 07:47 UTC
Labels: area-System.Configuration, bug

**Comment by MichalStrehovsky** [comment] 2021-07-14 08:23
> I'm closing this issue since @eerhardt has disabled trimming on that library for now (#49085) and we have another issue to enable it back with trimmer annotations helping it to preserve the right members or warn the user if they need to do something (#49062)

FWIW, the attributes added in #49062 are new to .NET 6 and .NET Native will not understand them - this will do nothing for UWP. That said, I don't think anything is going to be done for UWP in this repo. The RD.XML workaround is the solution.
