### ISSUE TITLE
[API Proposal]: Frozen Set and Collection Literals

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#97760] opened 2024-01-31 12:14 UTC
### Background and motivation

Frozen Sets are collections.  They should be able to participate in collection literal syntax.

Currently, to create a frozen set you have to do this:
```
ContactIdStatus = new[] { CompanyIdStatus, PersonIdStatus }.ToFrozenSet();
```

But you should be able to just do this:
```
ContactIdStatus = [ CompanyIdStatus, PersonIdStatus ];
```

### API Proposal

I am not sure.

### API Usage

```csharp

FrozenSet<int> = [1,2,3];

```

### Alternative Designs

Leave things as-is.

### Risks

None that I can think of.

**Comment by eiriktsarpalis** [comment] 2024-01-31 12:22
I'm pretty sure that frozen set literal support was considered and rejected, but couldn't find any evidence as to that in the [relevant issue](https://github.com/dotnet/runtime/issues/87569). It might be that it was skipped because, at the time, the constructor still accepted an additional boolean parameter controlling the degree of optimization but that has since been stripped. In principle I think this could be supported.

cc @stephentoub

**Comment by stephentoub** [comment] 2024-01-31 12:45
Duplicate of https://github.com/dotnet/runtime/issues/92190

**Closed by stephentoub** 2024-01-31 12:45 UTC
Labels: api-suggestion, area-System.Collections, untriaged
