### ISSUE TITLE
[API Proposal]: Default `IEnumerator<T>` implementation for `object IEnumerator.Current { get; }`

### ISSUE THREAD

**Issue by Akarinnnnn** [dotnet/runtime#67751] opened 2022-04-08 11:58 UTC
### Background and motivation

`IEmumerator<T>` has a historical burden: `object IEnumearble.Current { get; }`, which erases type and conflicts with generic version. In most strong typed enumerator, the ancient `Current` just returns the value which got from generic version, consider below snippet:
```csharp
struct MyEnumerator<T>: IEnumerator<T>
{
    // omitted MoveNext, Reset, etc.
    // …
    T Current => /* logic */;

    // the historical burden
    object IEnumerator.Current => Current;
}
```
Almost every strong typed enumerator have to paste `object IEnumerator.Current => Current;`. We can move this to `IEnumerator<T>` to make it easier. Also mention this change on tutorials about _writing an enumerator._

### API Proposal

```diff C#
namespace System.Collections.Generic
{
    public interface IEnumerator<out T> : IDisposable, IEnumerator
    {
        // Returns the current element of the enumeration. The returned value is
        // undefined before the first call to MoveNext and following a
        // call to MoveNext that returned false. Multiple calls to
        // GetCurrent with no intervening calls to MoveNext
        // will return the same object.
        new T Current
        {
            get;
        }

+        object IEnumerable.Current => Current;
    }
}
```

### API Usage

With default implementation inside `IEnumerator<T>`, enumerators don't have to implement old `Current` itself.
```C#
struct MyEnumerator<T>: IEnumerator<T>
{
    // omitted MoveNext, Reset, etc.
    // now we don't have to implement `IEnumerator.Current` ourselves
    T Current => /* logic */;
}
```

**Comment by GrabYourPitchforks** [comment] 2022-04-08 14:39
Dupe of https://github.com/dotnet/runtime/issues/29513.

**Closed** 2022-04-13 12:27 UTC
Labels: api-suggestion, area-System.Collections, untriaged
