### ISSUE TITLE
[wasm][eat] System.Runtime.Loader test failing due to missing `System.MulticastDelegate` in `System.Runtime`

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#51893] opened 2021-04-26 21:30 UTC
[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-51697-merge-9125846b99214378b6/System.Runtime.Loader.Tests/console.f9e056fb.log?sv=2019-07-07&se=2021-05-16T10%3A10%3A08Z&sr=c&sp=rl&sig=sLFwFf7TqJBCYW8SJjWKm0ZfSDTTJbceEi2RV4jD8KI%3D)

Fails with `/p:EnableAggressiveTrimming=true`

```
fail: [FAIL] System.Runtime.Loader.Tests.AssemblyLoadContextTest.LoadAssemblyByPath_ValidUserAssembly
info: System.TypeLoadException : Could not resolve type with token 01000014 from typeref (expected class 'System.MulticastDelegate' in assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
info:    at System.Reflection.RuntimeModule.GetTypes()
info:    at System.Reflection.Assembly.GetTypes()
info:    at System.Reflection.Assembly.get_DefinedTypes()
info:    at System.Runtime.Loader.Tests.AssemblyLoadContextTest.LoadAssemblyByPath_ValidUserAssembly()
info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
fail: [FAIL] System.Runtime.Loader.Tests.AssemblyLoadContextTest.LoadAssemblyByStream_ValidUserAssembly
info: System.TypeLoadException : Could not resolve type with token 01000014 from typeref (expected class 'System.MulticastDelegate' in assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
info:    at System.Reflection.RuntimeModule.GetTypes()
info:    at System.Reflection.Assembly.GetTypes()
info:    at System.Reflection.Assembly.get_DefinedTypes()
info:    at System.Runtime.Loader.Tests.AssemblyLoadContextTest.LoadAssemblyByStream_ValidUserAssembly()
info:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

```

**Comment by fanyang-mono** [comment] 2021-04-29 23:46
This issue seems to be only reproducible within the test infrastructure.

**Comment by ilonatommy** [comment] 2022-06-15 10:29
@radical is this still a problem?

**Comment by radical** [comment] 2022-06-16 04:03
@lambdageek Based on https://github.com/dotnet/runtime/pull/52088#issuecomment-830288424 , should we skip these [two](https://github.com/radical/runtime/blob/main/src/libraries/System.Runtime.Loader/tests/AssemblyLoadContextTest.cs#L73) [tests](https://github.com/radical/runtime/blob/main/src/libraries/System.Runtime.Loader/tests/AssemblyLoadContextTest.cs#L89) on wasm for EAT, and AOT?

You added separate hot reload tests, and these don't seem related.

**Comment by lewing** [comment] 2023-07-24 20:26
[closing this since it is trimming related failure and we will address it differently

**Closed by lewing** 2023-07-24 20:26 UTC
Labels: arch-wasm, disabled-test, area-AssemblyLoader-mono, trimming-for-aot
