### ISSUE TITLE
[API Proposal]: List<T>[Range]

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#74824] opened 2022-08-30 16:42 UTC
### Background and motivation

It would be really nice if List<T> had a [Range] operator so I could simply type:

```
var Values = List[1..4];
```
Instead of:
```
var Values = List.ToArray()[1..4].ToList();
```

### API Proposal

```csharp
namespace System.Collections.Generic;

public class List<T> 
{
    public List<T> this[Range range] {get;}
}
```

### API Usage

```csharp

var Values = List[1..4];

```

### Alternative Designs

```
var Values = List.ToArray()[1..4].ToList();
```

### Risks

None that I can think of.
I would also suggest extending the range operator to other countable collections.
For example, ImmutableList, ImmutableArray, LinkedList, etc.

**Comment by BrennanConroy** [comment] 2022-08-30 16:47
Looks similar to https://github.com/dotnet/runtime/issues/66773

**Comment by eiriktsarpalis** [comment] 2022-08-30 17:56
Yep. Closing as dupe of #66773.

**Closed by eiriktsarpalis** 2022-08-30 17:56 UTC
Labels: api-suggestion, area-System.Collections
