### ISSUE TITLE
LoggerMessage not serializing type

### ISSUE THREAD

**Issue by sgtobin** [dotnet/runtime#62957] opened 2021-12-17 15:57 UTC
### Description

Not seeing the WeatherForecast object being desterilized in the logs. I am only seeing the results of ToString() on the WeatherForecast 
```cmd
{
  "EventId": 0,
  "LogLevel": "Information",
  "Category": "Web.Controllers.WeatherForecastController",
  "Message": "Forecast: Web.WeatherForecast",
  "State": {
    "Message": "Forecast: Web.WeatherForecast",
    "weatherForecast": "Web.WeatherForecast",
    "{OriginalFormat}": "Forecast: {weatherForecast}"
  }
}
```

### Reproduction Steps

```c#
    [ApiController]
    [Route("[controller]")]
    public partial class WeatherForecastController : ControllerBase
    {
        private static readonly string[] Summaries = new[]
        {
            "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
        };

        private readonly ILogger<WeatherForecastController> _logger;

        public WeatherForecastController(ILogger<WeatherForecastController> logger)
        {
            _logger = logger;
        }

        [LoggerMessage(0, LogLevel.Information, @"Forecast: {weatherForecast}")]
        partial void LogForecast(WeatherForecast weatherForecast);

        [HttpGet(Name = "GetWeatherForecast")]
        public IEnumerable<WeatherForecast> Get()
        {
            LogForecast(new WeatherForecast { Summary = "Hello?" });

            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = Random.Shared.Next(-20, 55),
                Summary = Summaries[Random.Shared.Next(Summaries.Length)]
            })
            .ToArray();
        }
    }
```

### Expected behavior

I expected to see the WeatherForecast object desterilized... 

### Actual behavior

Seeing the results of .ToString() on the WeatherForecast object.

**Comment by maryamariyan** [comment] 2021-12-22 04:21
This is currently not supported.

**Comment by maryamariyan** [comment] 2021-12-22 07:47
Closing as dupe of https://github.com/dotnet/runtime/issues/61947

**Closed by maryamariyan** 2021-12-22 07:47 UTC
Labels: area-Extensions-Logging
