### ISSUE TITLE
Ascii and Latin1 APIs can return wrong results for misaligned buffers

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#84877] opened 2023-04-15 04:23 UTC
```c#
char* pBuffer = stackalloc char[17];
Span<char> misalignedSpan = new((char*)((byte*)pBuffer + 1), 16);
misalignedSpan.Fill('a');

if (!Ascii.IsValid(misalignedSpan)) Console.WriteLine("Oh no");
```

`Ascii.IsValid` pins the input and works with pointers internally. `GetIndexOfFirstNonAsciiChar_Intrinsified` will attempt to 16-byte align the input pointer to make use of aligned reads, but in doing so it ends up working with the "corrupted" data if the input wasn't 2-byte aligned initially.
https://github.com/dotnet/runtime/blob/72586a7397aab4ba9a3afe7fdc6f9de1b7b6e77c/src/libraries/System.Private.CoreLib/src/System/Text/Ascii.Utility.cs#L829
As a result it may end up returning the wrong result (both false positives and false negatives).

`Latin1Utility` also likely shares the same issue.

It's safe to assume that related operations on `Encoding` that make use of these helpers are likewise affected.

**Comment by tannergooding** [comment] 2023-04-17 14:33
CC. @GrabYourPitchforks, this has been around for about 4 years since https://github.com/dotnet/coreclr/pull/22516

While the JIT expects that any `T`, `ref T`, or `T*` is "naturally aligned" and it expects you to use the `unaligned.` prefix (such as via `Unsafe.ReadUnaligned`) to access unaligned data; correctly detecting and handling data that is misaligned isn't difficult and won't noticeably hurt the common path. -- We should just need to check that `address % 2 == 0` prior to trying to align the data.

**Comment by thatbakamono** [comment] 2023-04-29 23:09
The issue is actually not reproducible anymore with the provided example, I noticed after rebasing that `Ascii.IsValid` got reimplemented in #84881 without using the affected methods. All other APIs relying on `GetIndexOfFirstNonXYZChar` or `GetIndexOfFirstNonXYZByte` (where `XYZ` is either `Ascii` or `Latin1`) should be still affected.

**Comment by thatbakamono** [comment] 2023-05-11 13:22
Sorry for stalling the issue, I thought I'd be able to resolve it pretty quickly but a few unforeseen complications occurred and I don't think I'll be able to finish working on the fix any time soon. Thanks for the opportunity though, I learned quite a bit about the workflow and it'll allow me to make contributions more easily in the future.

**Comment by GrabYourPitchforks** [comment] 2024-05-20 20:33
Looks like a dupe of https://github.com/dotnet/runtime/issues/44497, which was resolved by-design. From that issue: in general, pointers are assumed to be properly aligned for the target data type, except in very specific circumstances where the API is expressly documented as supporting unaligned accesses.

**Comment by stephentoub** [comment] 2024-07-23 17:06
Closing as duplicate and by-design per above.

**Closed by stephentoub** 2024-07-23 17:06 UTC
Labels: bug, area-System.Buffers
