### ISSUE TITLE
Json.net can't deserialize simple struct, throws System.NullReferenceException

### ISSUE THREAD

**Issue by sake402** [dotnet/runtime#67781] opened 2022-04-08 21:52 UTC
### Description

System.Text.Json is unable to deserialize a very basic struct

### Reproduction Steps

```
using System;
					
public class Program
{
	
    public enum LengthUnitTypes
    {
        None,
        m,
        cm,
        mm,
        um,
        @in,
        ft,
        km,
        mi
    }
	public struct Length{
            public Length()
            {
            }

            public Length(double value, LengthUnitTypes unit)
            {
                Value = value;
                Unit = unit;
            }

            public double Value { get; set; } = 0;
            public LengthUnitTypes Unit { get; set; } = LengthUnitTypes.None;
	}
	public static void Main()
	{
		var l = new Length();
		var json = System.Text.Json.JsonSerializer.Serialize(l);
		Console.WriteLine(json);
		l = System.Text.Json.JsonSerializer.Deserialize<Length>(json);
		Console.WriteLine("Hello World");
	}
}
```

Result
```
{"Value":0,"Unit":0}
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at ValueSetter(Object , Double )
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Program.Main()
Command terminated by signal 6

```

See fiddle here https://dotnetfiddle.net/n21G3a

### Expected behavior

No exception. And if something is wrong with class/struct declaration, throw a more descriptive exception.

### Actual behavior

Throws null reference

**Comment by EgorBo** [comment] 2022-04-08 23:19
Likely dupe of https://github.com/dotnet/runtime/issues/62983 (fixed in 7.0)

**Comment by eiriktsarpalis** [comment] 2022-04-09 12:30
Can confirm that the issue has been resolved with the latest builds in .NET 7

**Closed by eiriktsarpalis** 2022-04-09 12:30 UTC
Labels: area-System.Text.Json, untriaged

**Comment by danmoseley** [comment] 2022-04-09 13:37
Should we consider for backport?

**Comment by EgorBo** [comment] 2022-04-11 09:01
> Should we consider for backport?

I asked that in https://github.com/dotnet/runtime/pull/62989 but since nobody responded I didn't file one

**Comment by eiriktsarpalis** [comment] 2022-04-11 10:47
I'm guessing it got dropped because it happened over the holidays. I think we should backport it.
