### ISSUE TITLE
OpenXml throws a different exception given identical code and similar build configuration for two distinct solutions. Why?

### ISSUE THREAD

**Issue by amine-aboufirass** [dotnet/runtime#76744] opened 2022-10-07 14:16 UTC
Suppose I have two separate solutions in Visual Studio 2019:
- `openxml-exceptions.sln`
- `openxml-exceptions-reference.sln`

# `openxml-exceptions.sln`

This solution contains two projects:
- `basic-example`: A class library
- `call-basic-example`: A console app

## `basic-example` 

The project file is as follows:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>basic_example</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
  	  <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
	
  <ItemGroup>
	<PackageReference Include="DocumentFormat.OpenXml" Version="2.14.0" />
  </ItemGroup>

</Project>
```

The project also contains `SpreadsheetWriterExample.cs`:

```using System;
using System.IO;
using DocumentFormat.OpenXml.Packaging;
using System.Collections.Generic;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Spreadsheet;
using System.Text;

namespace basic_example
{
   public class SpreadSheetWriterExample
   {

      public static void CreateSpreadsheetWorkbook(string filepath)
      {
         // Create a spreadsheet document by supplying the filepath.
         // By default, AutoSave = true, Editable = true, and Type = xlsx.
         Console.WriteLine("creating spreadsheet document");
         try
         {
            using (SpreadsheetDocument spreadsheetDocument = SpreadsheetDocument.Create(filepath, SpreadsheetDocumentType.Workbook))
            {
               spreadsheetDocument.Close();
            }
         }
         catch (DirectoryNotFoundException e)
         {
            Console.WriteLine("DirectoryNotFoundException");
         }
         catch (ArgumentException)
         {
            Console.WriteLine("ArgumentException");
         }
         catch (IOException e)
         {
            Console.WriteLine("IOException");
         }
      }

      public static void Run()
      {
         
         CreateSpreadsheetWorkbook("asd\\da*dw.xlsx");
      }
   }
}
```

## `call-basic-example`

The project file is as follows:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RootNamespace>call_basic_example</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\basic-example\basic-example.csproj" />
  </ItemGroup>

</Project>
```

The project also contains `Program.cs`:

```
using System;
using basic_example;

namespace call_basic_example
{
   class Program
   {
      static void Main(string[] args)
      {

         SpreadSheetWriterExample.Run();
      }
   }
}
```

# `openxml-exceptions-reference.sln`

This solution contains one project:

- `basic-example`: A console app

# `basic-example`

The project file is as follows:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <OutputType>Exe</OutputType>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>basic_example</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
  	  <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
	
  <ItemGroup>
	<PackageReference Include="DocumentFormat.OpenXml" Version="2.14.0" />
  </ItemGroup>

</Project>
```

The project also includes `SpreadSheetWriterExample.cs`:

```
using System;
using System.IO;
using DocumentFormat.OpenXml.Packaging;
using System.Collections.Generic;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Spreadsheet;
using System.Text;

namespace basic_example
{
   public class SpreadSheetWriterExample
   {

      public static void CreateSpreadsheetWorkbook(string filepath)
      {
         // Create a spreadsheet document by supplying the filepath.
         // By default, AutoSave = true, Editable = true, and Type = xlsx.
         Console.WriteLine("creating spreadsheet document");
         try
         {
            using (SpreadsheetDocument spreadsheetDocument = SpreadsheetDocument.Create(filepath, SpreadsheetDocumentType.Workbook))
            {
               spreadsheetDocument.Close();
            }
         }
         catch (DirectoryNotFoundException e)
         {
            Console.WriteLine("DirectoryNotFoundException");
         }
         catch (ArgumentException)
         {
            Console.WriteLine("ArgumentException");
         }
         catch (IOException e)
         {
            Console.WriteLine("IOException");
         }
      }

      public static void Main()
      {
         
         CreateSpreadsheetWorkbook("asd\\da*dw.xlsx");
      }
   }
}
```

# Question:

When I build and run `openxml-exceptions.sln` with `call-basic-example` as the startup project, I get `DirectoryNotFoundException` in the output.

When I build and run `openxml-exceptions-reference.sln` I get `ArgumentException` in the output.

I am using the following version of Visual Studio:

[![enter image description here][1]][1]

Given that I am using the exact same framework version in the class library of `openxml-exceptions.sln` and the console app of `openxml-exceptions-reference.sln` and the exact same version of `OpenXml`, I cannot wrap my head around *why* the thrown and caught error are different for each solution. As far as I can tell they should be exactly the same, but I am apparently overlooking something fundamental.

Why are the errors thrown different for each solution, given the exact same code, framework version and package version?

  [1]: https://i.stack.imgur.com/ifFUl.png

**Comment by amine-aboufirass** [comment] 2022-10-07 14:54
I also just tried this without using `OpenXml`, namely replacing 

```
using (SpreadsheetDocument spreadsheetDocument = SpreadsheetDocument.Create(filepath, SpreadsheetDocumentType.Workbook))
{
    spreadsheetDocument.Close();
}
```

with 

```
using (FileStream fs = File.Create(filepath))
{
    using (StreamWriter writer = new StreamWriter(fs))
        {
            writer.Write("Test");
        }
}
```
And it turns out that I'm getting the same behavior. So it's not strictly related to `OpenXml` I suppose...

**Comment by amine-aboufirass** [comment] 2022-10-11 10:35
@adamsitnik I have two remarks or you:

1,  `netstandard2.0` might cause an exception in the command line using `dotnet` CLI but it runs fine from Visual Studio. Please run it from Visual Studio
1. You are using a different filename from the one I have specified in the OP. Please use `"asd\\da*dw.xlsx"` to replicate the behavior I am seeing.

If you make the above changes and try with `netstandard2.0` *and* Exe in the project file you will see that you get an `ArgumentException` whereas for the other frameworks throw a `DirectoryNotFoundException`.

**Comment by adamsitnik** [comment] 2022-10-11 12:33
> Please use "asd\\da*dw.xlsx" to replicate the behavior I am seeing.

@amine-aboufirass thanks, that was the missing part.

This change was introduced in .NET Core 2.1 in https://github.com/dotnet/corefx/pull/25458 and https://github.com/dotnet/coreclr/pull/15191.

It was explained in https://learn.microsoft.com/en-us/archive/blogs/jeremykuhne/system-io-in-net-core-2-1-sneak-peek and documented as a breaking change in https://github.com/dotnet/dotnet-api-docs/pull/5415

Since it was by design and it's documented I am closing the issue.

**Closed by adamsitnik** 2022-10-11 12:33 UTC
Labels: area-System.IO, needs-further-triage
