### ISSUE TITLE
Test failure JIT\\Methodical\\Boxing\\seh\\try_il_r\\try_il_r.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#65686] opened 2022-02-22 01:25 UTC
Run: [runtime-coreclr r2r-extra 20220220.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1623899&view=ms.vss-test-web.build-test-results-tab&runId=45114340&resultId=102260&paneView=debug)

Failed test:
```
R2R windows x64 Checked jitstressregs0x10 @ Windows.10.Amd64.Open

- JIT\\Methodical\\Boxing\\seh\\try_il_r\\try_il_r.cmd
- JIT\\Methodical\\Arrays\\misc\\address_il_d\\address_il_d.cmd
- JIT\\Methodical\\Boxing\\misc\\tailjump_cs_d\\tailjump_cs_d.cmd
- JIT\\Methodical\\casts\\coverage\\castclass_newobj_d\\castclass_newobj_d.cmd
- JIT\\Methodical\\AsgOp\\i8\\i8flat_cs_r\\i8flat_cs_r.cmd

```
**Error message:**
```
Could Not Find C:\h\w\B86A0A2A\w\9F5D08EF\e\JIT\Methodical\Boxing\seh\try_il_r\IL-CG2\composite-r2r.dll
Could Not Find C:\h\w\B86A0A2A\w\9F5D08EF\e\JIT\Methodical\Boxing\seh\try_il_r\try_il_r.dll.rsp
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'System.Diagnostics.Tracing, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The module was expected to contain an assembly manifest.
File name: 'System.Diagnostics.Tracing, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
at ILCompiler.Program.Run(String[] args)
at ILCompiler.Program.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\B86A0A2A\w\9F5D08EF\uploads\Reports\JIT.Methodical\Boxing\seh\try_il_r\try_il_r.output.txt
Raw output:
BEGIN EXECUTION
try_il_r.dll
1 file(s) copied.
Response file: C:\h\w\B86A0A2A\w\9F5D08EF\e\JIT\Methodical\Boxing\seh\try_il_r\try_il_r.dll.rsp
C:\h\w\B86A0A2A\w\9F5D08EF\e\JIT\Methodical\Boxing\seh\try_il_r\IL-CG2\try_il_r.dll
-o:C:\h\w\B86A0A2A\w\9F5D08EF\e\JIT\Methodical\Boxing\seh\try_il_r\try_il_r.dll
--targetarch:x64
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\B86A0A2A\p\System..dll
-r:C:\h\w\B86A0A2A\p\Microsoft..dll
-r:C:\h\w\B86A0A2A\p\mscorlib.dll
-r:C:\h\w\B86A0A2A\p\netstandard.dll
-O
" "dotnet" "C:\h\w\B86A0A2A\p\crossgen2\crossgen2.dll" @"C:\h\w\B86A0A2A\w\9F5D08EF\e\JIT\Methodical\Boxing\seh\try_il_r\try_il_r.dll.rsp"   -r:C:\h\w\B86A0A2A\w\9F5D08EF\e\JIT\Methodical\Boxing\seh\try_il_r\IL-CG2*.dll"
Crossgen2 failed with exitcode - -532462766
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\B86A0A2A\p
C:\h\w\B86A0A2A\w\9F5D08EF\e\JIT\Methodical\Boxing\seh\try_il_r\try_il_r.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_Methodical._Boxing_seh_try_il_r_try_il_r_._Boxing_seh_try_il_r_try_il_r_cmd()
```

**Comment by trylek** [comment] 2022-04-04 20:28
Closing as duplicate of: https://github.com/dotnet/runtime/issues/65646

**Closed by trylek** 2022-04-04 20:28 UTC
Labels: os-windows, JitStress, arch-x64, area-crossgen2-coreclr, untriaged
