### ISSUE TITLE
Mono's System.Private.CoreLib Threading NullReferenceException

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#51895] opened 2021-04-26 21:54 UTC
```
  Discovering: Microsoft.Extensions.Hosting.Unit.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  Microsoft.Extensions.Hosting.Unit.Tests (found 108 of 109 test cases)
  Starting:    Microsoft.Extensions.Hosting.Unit.Tests (parallel test collections = on, max threads = 12)

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
   at System.IO.FileSystemWatcher.RunningInstance.FileSystemEventCallback(IntPtr streamRef, IntPtr clientCallBackInfo, IntPtr numEvents, Byte** eventPaths, FSEventStreamEventFlags* eventFlags, UInt64* eventIds) in /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs:line 354
   at System.IO.FileSystemWatcher.RunningInstance.StaticWatcherRunLoopManager.WatchForFileSystemEventsThreadStart(ManualResetEventSlim runLoopStarted, SafeEventStreamHandle eventStream) in /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs:line 255
   at System.IO.FileSystemWatcher.RunningInstance.StaticWatcherRunLoopManager.<>c.<ScheduleEventStream>b__3_0(Object args) in /_/src/libraries/System.IO.FileSystem.Watcher/src/System/IO/FileSystemWatcher.OSX.cs:line 205
   at System.Threading.Thread.StartCallback() in /_/src/mono/System.Private.CoreLib/src/System/Threading/Thread.Mono.cs:line 236
```

Configuration: `net6.0-OSX-Debug-x64-Mono_release-OSX.1015.Amd64.Open`

core.28810:
  https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-51891-merge-4df95a776f8845c08e/Microsoft.Extensions.Hosting.Unit.Tests/core.28810?sv=2019-07-07&se=2021-05-16T21%3A33%3A56Z&sr=c&sp=rl&sig=H2ZL3fnJrWeUiUgDH0X%2F%2Fph9du9TWqcIHWXCt0ta%2B2c%3D

console.fe66311c.log:
  https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-51891-merge-4df95a776f8845c08e/Microsoft.Extensions.Hosting.Unit.Tests/console.fe66311c.log?sv=2019-07-07&se=2021-05-16T21%3A33%3A56Z&sr=c&sp=rl&sig=H2ZL3fnJrWeUiUgDH0X%2F%2Fph9du9TWqcIHWXCt0ta%2B2c%3D

**Comment by ViktorHofer** [comment] 2021-04-26 21:55
cc @jkotas

**Comment by jkotas** [comment] 2021-04-26 21:57
Duplicate of #30056

**Closed by jkotas** 2021-04-26 21:57 UTC
Labels: area-System.IO, bug, untriaged
