### ISSUE TITLE
HTTP2: Consider supporting h2c without AppContext switch

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#988] opened 2019-10-07 22:05 UTC
**API proposal: https://github.com/dotnet/corefx/issues/41621#issuecomment-564280539**

Today users must set an AppContext switch to be able to use h2c (HTTP/2 without TLS) with HttpClient. This switch was added in .NET Core 3.0 to make it easier to debug the content of HttpClient traffic by having it sent without TLS.

```cs
AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);
```

This setting has turned out to be very useful, and has a lot of legitimate uses outside of just debugging. I think HttpClient should support h2c without setting this switch.

Although browsers require a web server to always encrypt HTTP/2 content, it is common for back end services to send HTTP/2 API calls without TLS, especially during development. Most development ecosystems don't have the TLS-by-default focus that .NET has.

For example, a gRPC service hosted written in Java/Go/C++ probably won't have a TLS cert setup in development, and .NET devs will need to jump through additional hoops to figure out how to successfully call it.

Another example of where h2c is required is ASP.NET Core gRPC on macOS. .NET Core ASP.NET on Mac doesn't support server TLS, so users have to develop with h2c - https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-3.0#unable-to-start-aspnet-core-grpc-app-on-macos

@shirhatti

**Comment by scalablecory** [comment] 2020-04-03 17:54
Closing as duplicate of #987

**Closed by scalablecory** 2020-04-03 17:54 UTC
Labels: api-suggestion, area-System.Net.Http
