### ISSUE TITLE
JsonSerializer not correctly applying casing rules to nested values

### ISSUE THREAD

**Issue by devony** [dotnet/runtime#42832] opened 2020-09-29 02:00 UTC
### Description

When I try to serialize a dictionary within a dictionary using  `DictionaryKeyPolicy = JsonNamingPolicy.CamelCase`, only the inner-most object is correctly formatted. This seems to apply to classes as well.
```

using System;
using System.Collections.Generic;
using System.Text.Json;

public class Program
{
		
	class Test {
		public string TestKey {get;set;}
	}
	
	public static void Main()
	{
		var dict = new Dictionary<string, Dictionary<string, Test>>();
		var innerDict = new Dictionary<string, Test>();
		var testObj =  new Test { TestKey = "TestValue" };
		innerDict.Add("PascalCase", testObj);
		dict.Add("PascalCase1", innerDict);
		
		var options = new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase, DictionaryKeyPolicy = JsonNamingPolicy.CamelCase };
		Console.WriteLine(JsonSerializer.Serialize(testObj, options));
		Console.WriteLine(JsonSerializer.Serialize(innerDict, options));
		Console.WriteLine(JsonSerializer.Serialize(dict, options));
	}
}
```

presents output:
```
{"testKey":"TestValue"}
{"PascalCase":{"testKey":"TestValue"}}
{"PascalCase1":{"PascalCase":{"testKey":"TestValue"}}}
```

dotnetfiddle here: https://dotnetfiddle.net/jCtGeQ

### Configuration
Repros in fiddle above. Locally:

 .NET Core 3.1
Win10 Enterprise x64 19041

**Comment by layomia** [comment] 2020-09-30 04:03
Duplicate of https://github.com/dotnet/runtime/issues/30889. Fixed in .NET 5. You can try the fix in [.NET 5 RC1](https://devblogs.microsoft.com/dotnet/announcing-net-5-0-rc-1/) (upgrade the app's TFM) or the NuGet package (stay with .NET Core 3.1 but use the latest System.Text.Json features/bug fixes).

**Closed by layomia** 2020-09-30 04:03 UTC
Labels: area-System.Text.Json, untriaged
