### ISSUE TITLE
GC.LargeMemory failed with System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#53004] opened 2021-05-20 02:40 UTC
Run: [runtime-coreclr jitstress 20210519.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1145874&view=ms.vss-test-web.build-test-results-tab&runId=34698082&resultId=108225&paneView=debug)

Failed tests:
```
CoreCLR OSX arm64 Checked jitminopts @ OSX.1100.ARM64.Open

- GC/LargeMemory/Allocation/largeexceptiontest/largeexceptiontest.sh
- GC/LargeMemory/API/gc/gettotalmemory/gettotalmemory.sh
- GC/LargeMemory/API/gc/keepalive/keepalive.sh
- GC/LargeMemory/API/gc/suppressfinalize/suppressfinalize.sh

```
**Error message:**
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
at System.SZArrayHelper.get_Item[T](Int32 index) in System.Private.CoreLib.dll:token 0x6000162+0x0
at MemCheck.ParseSizeMBArgument(IReadOnlyList1 args) in memcheck.dll:token 0x6000007+0x0 at MemCheck.ParseSizeMBAndLimitByAvailableMem(IReadOnlyList1 args) in memcheck.dll:token 0x6000006+0x0
at LargeExceptionTest.Main(String[] args) in largeexceptiontest.dll:token 0x6000004+0x0
task_for_pid(17855) FAILED 5 (os/kern) failure
/private/tmp/helix/working/A2FD0903/w/B1360936/e/GC/LargeMemory/Allocation/largeexceptiontest/largeexceptiontest.sh: line 384: 17855 Abort trap: 6           (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /private/tmp/helix/working/A2FD0903/w/B1360936/e/GC/LargeMemory/Reports/GC.LargeMemory/Allocation/largeexceptiontest/largeexceptiontest.output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/A2FD0903/p/corerun largeexceptiontest.dll '2048'
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/tmp/helix/working/A2FD0903/p
/private/tmp/helix/working/A2FD0903/w/B1360936/e/GC/LargeMemory/Allocation/largeexceptiontest/largeexceptiontest.sh
Expected: True
Actual:   False


Stack trace
   at GC_LargeMemory._Allocation_largeexceptiontest_largeexceptiontest_._Allocation_largeexceptiontest_largeexceptiontest_sh()
```

**Comment by AaronRobinsonMSFT** [comment] 2021-05-20 03:26
Likely related to https://github.com/dotnet/runtime/issues/49365

/cc @sdmaclea

**Comment by mangod9** [comment] 2021-07-20 18:25
Dupe of https://github.com/dotnet/runtime/issues/51250

**Closed by mangod9** 2021-07-20 18:25 UTC
Labels: JitStress, arch-arm64, area-GC-coreclr, os-mac-os-x
