### ISSUE TITLE
S.R.InteropServices.JavaScript is part of the shared framework but doesn't have a ref assembly

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#39042] opened 2020-07-09 22:40 UTC
System.Runtime.InteropServices.JavaScript is currently declared as part of the shared framework but doesn't have a reference assembly. As the project isn't OOB either, there is currently no way for a customer to reference the library besides directly referencing the implementation one from the shared framework directory.

Is the omission of a reference assembly intentional?

cc @kjpou1 @marek-safar @ericstj

**Comment by jkotas** [comment] 2020-07-09 23:01
This is internal library, for internal consumption only for now. 

See https://github.com/dotnet/runtime/pull/35573#discussion_r421408401

**Comment by safern** [comment] 2020-07-09 23:01
So then we should close the issue as by design?

**Comment by ericstj** [comment] 2020-07-09 23:07
Do we want to change the name to `System.Private` to indicate it is internal only?  We've done so elsewhere (CoreLib, URI, XML).

**Comment by marek-safar** [comment] 2020-07-10 06:31
> Do we want to change the name to System.Private to indicate it is internal only?

Is it worth it? We'll probably make the library public in the future (e.g. .NET7).

**Comment by stephentoub** [comment] 2020-07-10 11:35
> Is it worth it? We'll probably make the library public in the future (e.g. .NET7).

I would think so.  That's two releases away, including an LTS.

**Comment by ericstj** [comment] 2020-08-04 18:31
Do we think its worth the risk to change the name at this point in the release?  What could break if we change this name?  cc @steveisok @akoeplinger

**Comment by lewing** [comment] 2020-08-04 19:21
Nothing external should break at this point, the name is already different than the 3.2 counterpart.  The name is referenced in a couple of places by the js in a couple of places internally.

**Comment by steveisok** [comment] 2020-08-04 19:22
I think this is pretty low risk and we should be able to change it.

**Comment by akoeplinger** [comment] 2020-08-04 20:12
I think I already did this as part of https://github.com/dotnet/runtime/commit/c6520585b6f48d80228241320198b2efdb8e0fe5.

**Comment by ViktorHofer** [comment] 2020-08-04 20:15
Thanks Alex. You missed removing the P2P in the test project (as it wasn't part of the targeting pack before): https://github.com/dotnet/runtime/blob/c91269cb959a78309d0fa3040ae6028cce97f86e/src/libraries/System.Runtime.InteropServices.JavaScript/tests/System.Runtime.InteropServices.JavaScript.Tests.csproj#L21-L22

**Comment by ViktorHofer** [comment] 2020-08-04 20:17
Submitted https://github.com/dotnet/runtime/pull/40337 to clean this up. Meanwhile, this issue can be closed. Thanks all.

**Comment by steveisok** [comment] 2020-08-04 20:29
@ViktorHofer I still think we need to change the name since it's internal.

**Comment by akoeplinger** [comment] 2020-08-04 20:31
I wasn't aware of this issue and that this is an internal library for 5.0 so I think we'll need to remove the reference assembly again.

**Comment by safern** [comment] 2020-08-04 20:33
> I wasn't aware of this issue and that this is an internal library for 5.0 so I think we'll need to remove the reference assembly again.

We don't need to remove the ref assembly, we can make the ref to not be shipped if we want to:

https://github.com/dotnet/runtime/blob/master/src/libraries/NetCoreAppLibrary.props#L149

**Comment by ViktorHofer** [comment] 2020-08-04 20:33
@safern Why would we keep the ref if we aren't shipping it?

**Comment by safern** [comment] 2020-08-04 20:40
I don't know, because we plan on making it public further down the road and to simplify the change; I guess "if we want to" wasn't clear enough to express that 😄. 

I guess I was just trying to express that we have libraries where the ref is OOB and the implementation Inbox. In this case the ref is not even OOB, so if we don't need the ref for anything, removing it sounds reasonable.

**Comment by ViktorHofer** [comment] 2020-08-04 21:30
@steveisok @akoeplinger can you make a decision on what we should do here for 5.0? In master right now we expose a ref assembly which means the assembly isn't private atm. Should we remove the ref assembly and rename library or keep the ref and hence expose the lib?

**Comment by steveisok** [comment] 2020-08-04 21:36
I thought I said changing it would be low risk and something we should be able to do.  

To be clear, if it's internal in 5.0, we should treat it as such and rename / remove the ref.

**Closed** 2020-08-07 13:45 UTC
Labels: arch-wasm, area-System.Runtime.InteropServices.JavaScript
