### ISSUE TITLE
System.IO.Tests.SymbolicLink_Changed_Tests.FileSystemWatcher_DirectorySymbolicLink_TargetsFile_Fails failing

### ISSUE THREAD

**Issue by janvorli** [dotnet/runtime#53311] opened 2021-05-26 20:05 UTC
I've seen this test failing on Windows 10 amd64/x86 on a PR with changes that were unrelated (only touching PAL tests). 

The error is 
Assert.Throws() Failure
Expected: typeof(System.IO.FileNotFoundException)
Actual:   (No exception was thrown)

https://dev.azure.com/dnceng/public/_build/results?buildId=1157809&view=ms.vss-test-web.build-test-results-tab&runId=34956638&resultId=113343

The history of the failure shows that it has been failing this way intermittently since May 19 which actually looks like a day when the test was added.

**Comment by BruceForstall** [comment] 2021-05-27 05:35
I see a ton of these failures:

https://dev.azure.com/dnceng/public/_build/results?buildId=1158648&view=ms.vss-test-web.build-test-results-tab&runId=34972676&resultId=113462&paneView=debug

looks like windows x86/x64.

**Comment by BruceForstall** [comment] 2021-05-27 05:36
@danmoseley

**Comment by VincentBu** [comment] 2021-05-28 02:23
Failed again in [runtime-coreclr libraries-jitstress 20210527.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1159094&view=ms.vss-test-web.build-test-results-tab&runId=34981020&resultId=107950&paneView=debug)

Failed test:
```
net6.0-windows-Release-x64-CoreCLR_checked-jitstress1-Windows.10.Amd64.Open

- System.IO.Tests.SymbolicLink_Changed_Tests.FileSystemWatcher_DirectorySymbolicLink_TargetsFile_Fails

```
**Error message:**
```
Assert.Throws() Failure
Expected: typeof(System.IO.FileNotFoundException)
Actual:   (No exception was thrown)


Stack trace
   at System.IO.Tests.SymbolicLink_Changed_Tests.FileSystemWatcher_DirectorySymbolicLink_TargetsFile_Fails() in /_/src/libraries/System.IO.FileSystem.Watcher/tests/FileSystemWatcher.SymbolicLink.cs:line 42
```

**Comment by danmoseley** [comment] 2021-05-28 02:34
@carlossanlop

**Comment by Jozkee** [comment] 2021-06-01 17:03
Duplicate of https://github.com/dotnet/runtime/issues/53366. It was already disabled in https://github.com/dotnet/runtime/pull/53368.
Sorry for the annoyance.

**Closed by Jozkee** 2021-06-01 17:03 UTC
Labels: area-System.IO, blocking-clean-ci, untriaged
