### ISSUE TITLE
Test Infrastructure Failure: System.IO.IOException: Unknown error 42424

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#70079] opened 2022-06-01 13:26 UTC
I am seeing some failures in gc-extra pipelines for linux arm64
```
Test Infrastructure Failure: System.IO.IOException: Unknown error 42424 : '/root/helix/work/workitem/uploads/Arrays/lcs/lcs2_d'
at System.IO.FileSystem.CreateDirectory(String fullPath)
at System.IO.Directory.CreateDirectory(String path)
at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String basePath, String assemblyPath)
Expected: True
Actual:   False
```

E.g. https://dev.azure.com/dnceng/public/_build/results?buildId=1799737&view=ms.vss-test-web.build-test-results-tab&runId=47999058&paneView=debug&resultId=110210

**Comment by kunalspathak** [comment] 2022-06-01 13:27
cc: [trylek](https://github.com/trylek)

**Comment by adamsitnik** [comment] 2022-06-24 14:46
@tmds I have tried to google for the `42424` error code, but I was not able to find any meaningful results. Is it even possible that `mkdir` has failed with such an error?

**Comment by jakobbotsch** [comment] 2022-07-24 13:28
Fixed by #72298

**Comment by jakobbotsch** [comment] 2022-07-24 13:29
Actually duplicate of #70296

**Closed by jakobbotsch** 2022-07-24 13:28 UTC
Labels: arch-arm64, area-System.IO, os-linux, GCStress, blocking-clean-ci-optional, needs-further-triage

**Comment by adamsitnik** [comment] 2022-07-25 10:40
> @tmds I have tried to google for the 42424 error code, but I was not able to find any meaningful results. Is it even possible that mkdir has failed with such an error?

It turned out that GCStress was trashing last error: https://github.com/dotnet/runtime/pull/72298
