### ISSUE TITLE
Is there a way to modify the file properties of the exe generated after .NET compilation?

### ISSUE THREAD

**Issue by Gaoyifei1011** [dotnet/runtime#106127] opened 2024-08-06 03:29 UTC
### Description

Is there a way to modify the file properties of the exe generated after .NET compilation?
是否有方法修改.net编译后生成的exe的文件属性？

In the solution of cpp project, we can add.rc resource file to modify the file properties of the compiled exe program. In c#, most of the properties can be modified, but OriginalFileName and InteralFileName cannot be modified.
在cpp项目的解决方案中，我们可以添加.rc的资源文件来修改编译后exe程序的文件属性，在c#中，大部分属性可以被修改，然而OriginalFileName和InteralFileName这两个属性却无法修改。

When the application is PublishSingleFile and AOT published, the name generated by the application is xxx.exe, but InternalFileName and OriginalFileName in the file properties still show xxx.dll. Is there any way to change it to xxx.exe?
当应用程序采用单文件捆绑发布（PublishSingleFile）和AOT发布时，应用程序生成的名称为xxx.exe，然而文件属性中的InternalFileName和OriginalFileName仍然显示xxx.dll，有没有什么方法将其修改为xxx.exe呢？

![image](https://github.com/dotnet/runtime/assets/49179966/c0f5e318-4301-4577-8113-9f58cb19525b)

### Reproduction Steps

None

### Expected behavior

OrigianlFileName and InternalFileName value should be xxx.exe after publishsinglefile and aot publish

### Actual behavior

OrigianlFileName and InternalFileName value are xxx.dll after publishsinglefile and aot publish

### Regression?

These two properties appear as xxx.exe in the.NET framework and xxx.dll in the.NET core
这两个属性在.net framework中显示为xxx.exe，在.net core中显示为xxx.dll

### Known Workarounds

I can only use the ResourceHacker and xxx.res files to manually modify the file properties after the application compiles
我只能使用ResourceHacker和xxx.res文件在应用程序编译完成后手动修改文件属性

### Configuration

.net 8,9

### Other information

Provide the Settings options for modifying OriginalFileName and InternalFileName
请提供修改OriginalFileName和InternalFileName的设置选项

**Comment by Gaoyifei1011** [comment] 2024-08-08 12:39
> Moving to runtime as this is about how the apphost file is produced. That isn't controlled by the C# compiler.

![{329B649A-8E27-4E44-A2ED-D2D706EC66C3}](https://github.com/user-attachments/assets/0e78b503-2c88-4154-b88e-d1b8e29de471)
However, among the earliest responses, some people thought it was roslyn.
https://github.com/dotnet/runtime/issues/94519#issuecomment-1802027404

**Comment by vitek-karas** [comment] 2024-08-13 08:33
This is effectively the exact same issue as https://github.com/dotnet/runtime/issues/94519. 
@Gaoyifei1011 is there some difference? If not, why did you create a second issue for the same problem?

**Comment by Gaoyifei1011** [comment] 2024-08-13 08:36
> This is effectively the exact same issue as #94519. @Gaoyifei1011 is there some difference? If not, why did you create a second issue for the same problem?

According to the problem, dotnet/rosyln should be responsible for this problem, I submitted this problem to dotnet/rosyln, but it was moved to dotnet/runtime.
根据问题的提示，这个问题应该是由 dotnet/rosyln 负责的，我把这个问题提交到 dotnet/rosyln 后却被移到 dotnet/runtime 了。

**Comment by vitek-karas** [comment] 2024-08-13 08:38
I do agree with Jared that this is something the host/runtime team should tackle first. I'll close this as a duplicate of #94519 .

**Closed by vitek-karas** 2024-08-13 08:38 UTC
Labels: area-Host, untriaged, needs-area-label

**Comment by Gaoyifei1011** [comment] 2024-08-13 08:41
> I do agree with Jared that this is something the host/runtime team should tackle first. I'll close this as a duplicate of #94519 .

好的，非常感谢。随着 CSWINRT 支持 AOT 发布后，使用 AOT 发布的应用程序可能会越来越多。随着 AOT 使用的普及，希望这个问题能够尽快能够得到解决。
Ok, thank you very much. As CSWINRT supports AOT releases, the number of applications that use AOT releases is likely to increase. With the popularity of AOT usage, hopefully this problem will be solved soon.
