### ISSUE TITLE
Test failure:Interop/ICustomMarshaler/ConflictingNames/MultipleALCs/MultipleALCs.sh 

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#56951] opened 2021-08-06 01:33 UTC
Run: [runtime-coreclr gcstress-extra 20210803.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1274221&view=ms.vss-test-web.build-test-results-tab&runId=37692360&paneView=debug&resultId=101270)

Failed test:
```
CoreCLR Linux arm Checked gcstress0xc_zapdisable @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- Interop/ICustomMarshaler/ConflictingNames/MultipleALCs/MultipleALCs.sh

```
**Error message:**
```
Assert failure(PID 542 [0x0000021e], Thread: 559 [0x022f]): refCollectionObject != NULL
File: /__w/1/s/src/coreclr/vm/gcenv.ee.common.cpp Line: 190
Image: /root/helix/work/correlation/corerun

/root/helix/work/workitem/Interop/ICustomMarshaler/ConflictingNames/MultipleALCs/MultipleALCs.sh: line 364:   542 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/Interop.ICustomMarshaler/ConflictingNames/MultipleALCs/MultipleALCs.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun MultipleALCs.dll ''
Gathering state for process 542 corerun
Crashing thread 0000022f signal 00000006
Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.542.dmp
Written 53407744 bytes (13039 pages) to core file
Dump successfully written
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/Interop/ICustomMarshaler/ConflictingNames/MultipleALCs/MultipleALCs.sh
Expected: True
Actual:   False


Stack trace
   at Interop_ICustomMarshaler._ConflictingNames_MultipleALCs_MultipleALCs_._ConflictingNames_MultipleALCs_MultipleALCs_sh() in Interop.ICustomMarshaler.XUnitWrapper.dll:token 0x6000004+0x295
```

**Comment by AaronRobinsonMSFT** [comment] 2021-08-06 02:53
This is a duplicate of https://github.com/dotnet/runtime/issues/47696

**Closed by AaronRobinsonMSFT** 2021-08-06 02:53 UTC
Labels: os-linux, GCStress, area-Interop-coreclr, untriaged
