### ISSUE TITLE
Could not serialize nested ConcurrentDictionary to json

### ISSUE THREAD

**Issue by Executor-Cheng** [dotnet/runtime#670] opened 2019-12-08 04:46 UTC
The following code works in .NET Core 3.0.
In .NET Core 3.1, it will throw `System.NotSupportedException`.
```CSharp
string input = "{\"x\":{\"y\":\"z\"}}";
var test = JsonSerializer.Deserialize<ConcurrentDictionary<string, ConcurrentDictionary<string, string>>>(input); // ok
string output = JsonSerializer.Serialize(test); // throws
```

**Comment by danmosemsft** [comment] 2019-12-08 04:56
@layomia

**Comment by layomia** [comment] 2019-12-09 17:54
I'll take a look.

**Comment by ericstj** [comment] 2019-12-12 17:55
We may want to consider this for 3.1 servicing if we think this will be a common case.  Will this be hit for any case of a nested dictionary?

**Comment by Executor-Cheng** [comment] 2019-12-13 00:14
The following types work well
`System.Collections.Generic.SortedDictionary<TKey,TValue>`
`System.Collections.Generic.SortedList<TKey,TValue>`
`System.Collections.Immutable.ImmutableDictionary<TKey,TValue>`
`System.Collections.Immutable.ImmutableSortedDictionary<TKey,TValue>`

If I warp `ConcurrentDictionary<string, string>` in `ReadOnlyDictionary<string, string>`, it will throw.
Warp `Dictionary<string, string>` in `ReadOnlyDictionary<string, string>` will not throw.
It seems that it is only affect `ConcurrentDictionary<string, string>`.
```CSharp
ReadOnlyDictionary<string, ReadOnlyDictionary<string, string>> test = new ReadOnlyDictionary<string, ReadOnlyDictionary<string, string>>(new ConcurrentDictionary<string, ReadOnlyDictionary<string, string>>
{
    ["x"] = new ReadOnlyDictionary<string, string>(new ConcurrentDictionary<string, string>
    {
        ["y"] = "z"
    })
});
JsonSerializer.Serialize(test); // throws
```

**Comment by layomia** [comment] 2019-12-13 01:26
<details>
<summary>This issue appears limited only to nesting that involves concurrent dictionaries:</summary>
<br>

```
  {"Key":{"Key":1}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Text.Json.Serialization.Tests.DictionaryTests+MyNonGenericDictionary]
  {"Key":{"Key":1}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Generic.IReadOnlyDictionary`2[System.String,System.Text.Json.Serialization.Tests.DictionaryTests+MyClass]]
  {"Key":{"Key":1}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Int32]]
  {"Key":{"Key":1}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Text.Json.Serialization.Tests.GenericIDictionaryWrapper`2[System.String,System.Nullable`1[System.Int32]]]
  {"Key":{"Key":1}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.IDictionary]
  {"Key":{"Key":1}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Specialized.OrderedDictionary]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Generic.IDictionary`2[System.String,System.Text.Json.Serialization.Tests.DictionaryTests+MyNonGenericDictionary]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Generic.IDictionary`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Text.Json.Serialization.Tests.DictionaryTests+MyNonGenericDictionary]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Generic.Dictionary`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Text.Json.Serialization.Tests.DictionaryTests+MyNonGenericDictionary]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Text.Json.Serialization.Tests.DictionaryTests+MyNonGenericDictionary]]
  {"Key":{"Key":{"Key":1}}} -> System.Text.Json.Serialization.Tests.GenericIDictionaryWrapper`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Text.Json.Serialization.Tests.DictionaryTests+MyNonGenericDictionary]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Text.Json.Serialization.Tests.GenericIDictionaryWrapper`2[System.String,System.Text.Json.Serialization.Tests.DictionaryTests+MyNonGenericDictionary]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.IDictionary]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Specialized.OrderedDictionary]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Generic.IDictionary`2[System.String,System.Collections.Generic.IReadOnlyDictionary`2[System.String,System.Text.Json.Serialization.Tests.DictionaryTests+MyClass]]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Generic.IDictionary`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Generic.IReadOnlyDictionary`2[System.String,System.Text.Json.Serialization.Tests.DictionaryTests+MyClass]]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Generic.Dictionary`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Generic.IReadOnlyDictionary`2[System.String,System.Text.Json.Serialization.Tests.DictionaryTests+MyClass]]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Generic.IReadOnlyDictionary`2[System.String,System.Text.Json.Serialization.Tests.DictionaryTests+MyClass]]]
  {"Key":{"Key":{"Key":1}}} -> System.Text.Json.Serialization.Tests.GenericIDictionaryWrapper`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Generic.IReadOnlyDictionary`2[System.String,System.Text.Json.Serialization.Tests.DictionaryTests+MyClass]]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Text.Json.Serialization.Tests.GenericIDictionaryWrapper`2[System.String,System.Collections.Generic.IReadOnlyDictionary`2[System.String,System.Text.Json.Serialization.Tests.DictionaryTests+MyClass]]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Generic.IDictionary`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Int32]]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Generic.IDictionary`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Int32]]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Generic.Dictionary`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Int32]]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Int32]]]
  {"Key":{"Key":{"Key":1}}} -> System.Text.Json.Serialization.Tests.GenericIDictionaryWrapper`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Int32]]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Text.Json.Serialization.Tests.GenericIDictionaryWrapper`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Int32]]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Generic.IDictionary`2[System.String,System.Collections.Generic.Dictionary`2[System.String,System.Text.Json.Serialization.Tests.DictionaryTests+IClass]]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Generic.Dictionary`2[System.String,System.Text.Json.Serialization.Tests.DictionaryTests+IClass]]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Text.Json.Serialization.Tests.GenericIDictionaryWrapper`2[System.String,System.Collections.Generic.Dictionary`2[System.String,System.Text.Json.Serialization.Tests.DictionaryTests+IClass]]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Generic.IDictionary`2[System.String,System.Collections.Immutable.ImmutableDictionary`2[System.String,System.Object]]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Immutable.ImmutableDictionary`2[System.String,System.Object]]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Text.Json.Serialization.Tests.GenericIDictionaryWrapper`2[System.String,System.Collections.Immutable.ImmutableDictionary`2[System.String,System.Object]]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Generic.IDictionary`2[System.String,System.Text.Json.Serialization.Tests.GenericIDictionaryWrapper`2[System.String,System.Nullable`1[System.Int32]]]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Generic.IDictionary`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Text.Json.Serialization.Tests.GenericIDictionaryWrapper`2[System.String,System.Nullable`1[System.Int32]]]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Generic.Dictionary`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Text.Json.Serialization.Tests.GenericIDictionaryWrapper`2[System.String,System.Nullable`1[System.Int32]]]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Text.Json.Serialization.Tests.GenericIDictionaryWrapper`2[System.String,System.Nullable`1[System.Int32]]]]
  {"Key":{"Key":{"Key":1}}} -> System.Text.Json.Serialization.Tests.GenericIDictionaryWrapper`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Text.Json.Serialization.Tests.GenericIDictionaryWrapper`2[System.String,System.Nullable`1[System.Int32]]]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Text.Json.Serialization.Tests.GenericIDictionaryWrapper`2[System.String,System.Text.Json.Serialization.Tests.GenericIDictionaryWrapper`2[System.String,System.Nullable`1[System.Int32]]]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Generic.IDictionary`2[System.String,System.Collections.IDictionary]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Generic.IDictionary`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.IDictionary]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Generic.Dictionary`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.IDictionary]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.IDictionary]]
  {"Key":{"Key":{"Key":1}}} -> System.Text.Json.Serialization.Tests.GenericIDictionaryWrapper`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.IDictionary]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Text.Json.Serialization.Tests.GenericIDictionaryWrapper`2[System.String,System.Collections.IDictionary]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Generic.IDictionary`2[System.String,System.Collections.Hashtable]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Hashtable]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Text.Json.Serialization.Tests.GenericIDictionaryWrapper`2[System.String,System.Collections.Hashtable]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Generic.IDictionary`2[System.String,System.Collections.Specialized.OrderedDictionary]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Generic.IDictionary`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Specialized.OrderedDictionary]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Generic.Dictionary`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Specialized.OrderedDictionary]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Specialized.OrderedDictionary]]
  {"Key":{"Key":{"Key":1}}} -> System.Text.Json.Serialization.Tests.GenericIDictionaryWrapper`2[System.String,System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Collections.Specialized.OrderedDictionary]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Concurrent.ConcurrentDictionary`2[System.String,System.Text.Json.Serialization.Tests.GenericIDictionaryWrapper`2[System.String,System.Collections.Specialized.OrderedDictionary]]
```

</details>

I believe this is because this is the only generic BCL type where we use a different runtime type than was declared (I don't think this needs to change).

<details>
<summary>The PR https://github.com/dotnet/corefx/pull/42772 also has a deserialization fix for an `InvalidCastOperation` thrown when a dictionary element has a converter that returns a type different from the declared type:</summary>
<br>

```
  {"Key":1} -> System.Collections.Generic.IReadOnlyDictionary`2[System.String,System.Text.Json.Serialization.Tests.DictionaryTests+MyClass]
  {"Key":{"Key":1}} -> System.Collections.Generic.IDictionary`2[System.String,System.Collections.Generic.IReadOnlyDictionary`2[System.String,System.Text.Json.Serialization.Tests.DictionaryTests+MyClass]]
  {"Key":{"Key":1}} -> System.Collections.Generic.Dictionary`2[System.String,System.Collections.Generic.IReadOnlyDictionary`2[System.String,System.Text.Json.Serialization.Tests.DictionaryTests+MyClass]]
  {"Key":{"Key":1}} -> System.Text.Json.Serialization.Tests.GenericIDictionaryWrapper`2[System.String,System.Collections.Generic.IReadOnlyDictionary`2[System.String,System.Text.Json.Serialization.Tests.DictionaryTests+MyClass]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Generic.IDictionary`2[System.String,System.Collections.Generic.IDictionary`2[System.String,System.Collections.Generic.IReadOnlyDictionary`2[System.String,System.Text.Json.Serialization.Tests.DictionaryTests+MyClass]]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Generic.Dictionary`2[System.String,System.Collections.Generic.IDictionary`2[System.String,System.Collections.Generic.IReadOnlyDictionary`2[System.String,System.Text.Json.Serialization.Tests.DictionaryTests+MyClass]]]
  {"Key":{"Key":{"Key":1}}} -> System.Text.Json.Serialization.Tests.GenericIDictionaryWrapper`2[System.String,System.Collections.Generic.IDictionary`2[System.String,System.Collections.Generic.IReadOnlyDictionary`2[System.String,System.Text.Json.Serialization.Tests.DictionaryTests+MyClass]]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Generic.IDictionary`2[System.String,System.Collections.Generic.Dictionary`2[System.String,System.Collections.Generic.IReadOnlyDictionary`2[System.String,System.Text.Json.Serialization.Tests.DictionaryTests+MyClass]]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Generic.Dictionary`2[System.String,System.Collections.Generic.Dictionary`2[System.String,System.Collections.Generic.IReadOnlyDictionary`2[System.String,System.Text.Json.Serialization.Tests.DictionaryTests+MyClass]]]
  {"Key":{"Key":{"Key":1}}} -> System.Text.Json.Serialization.Tests.GenericIDictionaryWrapper`2[System.String,System.Collections.Generic.Dictionary`2[System.String,System.Collections.Generic.IReadOnlyDictionary`2[System.String,System.Text.Json.Serialization.Tests.DictionaryTests+MyClass]]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Generic.IDictionary`2[System.String,System.Text.Json.Serialization.Tests.GenericIDictionaryWrapper`2[System.String,System.Collections.Generic.IReadOnlyDictionary`2[System.String,System.Text.Json.Serialization.Tests.DictionaryTests+MyClass]]]
  {"Key":{"Key":{"Key":1}}} -> System.Collections.Generic.Dictionary`2[System.String,System.Text.Json.Serialization.Tests.GenericIDictionaryWrapper`2[System.String,System.Collections.Generic.IReadOnlyDictionary`2[System.String,System.Text.Json.Serialization.Tests.DictionaryTests+MyClass]]]
  {"Key":{"Key":{"Key":1}}} -> System.Text.Json.Serialization.Tests.GenericIDictionaryWrapper`2[System.String,System.Text.Json.Serialization.Tests.GenericIDictionaryWrapper`2[System.String,System.Collections.Generic.IReadOnlyDictionary`2[System.String,System.Text.Json.Serialization.Tests.DictionaryTests+MyClass]]]
```

Here, we have these types and a converter

```c#
private interface IClass { }

private class MyClass : IClass { }

private class MyFactory : JsonConverterFactory
{
    public override bool CanConvert(Type typeToConvert)
    {
        return typeToConvert == typeof(IClass) || typeToConvert == typeof(MyClass);
    }

    public override JsonConverter CreateConverter(Type typeToConvert, JsonSerializerOptions options)
    {
        return new MyStuffConverter();
    }
}

private class MyStuffConverter : JsonConverter<IClass>
{
    public override IClass Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        return new MyClass();
    }

    public override void Write(Utf8JsonWriter writer, IClass value, JsonSerializerOptions options)
    {
        writer.WriteNumberValue(1);
    }
}
```

</details>

This problem is an edge case which is fixed in 5.0.

Overall, while the reported issue is only reproducible for nested concurrent dictionaries, I think the fix is targeted enough to be considered for servicing.

**Comment by Executor-Cheng** [comment] 2019-12-13 05:22
Well done! Thank you for looking into the issue and providing the quick fix.

**Comment by danmosemsft** [comment] 2019-12-13 05:37
We leave issues open until final PR is merged and any servicing also merged

**Comment by ahsonkhan** [comment] 2020-01-16 04:12
Fixed in https://github.com/dotnet/runtime/pull/784 for 5.0 and https://github.com/dotnet/corefx/pull/42772 for 3.1.

**Closed by ahsonkhan** 2020-01-16 04:12 UTC
Labels: area-System.Text.Json
