### ISSUE TITLE
Bad IL Format error on creating a dynamic method using `System.Linq.Expressions.Compiler.LambdaCompiler.Compile`

### ISSUE THREAD

**Issue by adityapatwardhan** [dotnet/runtime#57106] opened 2021-08-10 00:19 UTC
### Description

When using .NET 6 Preview 7 SDK, creating dynamic methods using `System.Linq.Expressions.Compiler.LambdaCompiler.Compile` is erroring out with `System.BadImageFormatException`.

### Configuration

.NET 6 Preview 7 SDK on Windows 10 x64.

### Regression?

Yes, from .NET 7 preview 6.

### Other information

Repro steps:

On PowerShell built against .NET 6 preview 7 SDK run the following steps:

PS C:\> [short]::MinValue
-32768
PS C:\> $baseType = [short]
PS C:\> $a = $($baseType::MinValue)
OperationStopped: Bad IL format.
PS C:\> Get-Error

Exception             :
    Type       : System.BadImageFormatException
    Message    : Bad IL format.
    TargetSite :
        Name          : CreateDelegate
        DeclaringType : System.Reflection.Emit.DynamicMethod
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    Data       : System.Collections.ListDictionaryInternal
    Source     : System.Private.CoreLib
    HResult    : -2147024885
    StackTrace :
   at **System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType, Object target) in System.Private.CoreLib.dll:token 0x600583e+0x0
   at System.Linq.Expressions.Compiler.LambdaCompiler.CreateDelegate() in System.Linq.Expressions.dll:token 0x6000f63+0x22
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda) in System.Linq.Expressions.dll:token 0x6000f5c+0x16
   at System.Linq.Expressions.Expression`1.Compile() in System.Linq.Expressions.dll:token 0x600067d+0x0
   at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args) in System.Linq.Expressions.dll:token 0x6000126+0x36
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0) in System.Linq.Expressions.dll:token 0x6001062+0x14b**
   at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame) in D:\PSGit\PowerShell\src\System.Management.Automation\engine\interpreter\DynamicInstructions.Generated.cs:line 141
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) in D:\PSGit\PowerShell\src\System.Management.Automation\engine\interpreter\ControlFlowInstructions.cs:line 358
CategoryInfo          : OperationStopped: (:) [], BadImageFormatException
FullyQualifiedErrorId : System.BadImageFormatException
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : -1
    Line             : $a = $($baseType::MinValue)
    PositionMessage  : At line:1 char:1
                       + $a = $($baseType::MinValue)
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1

**Comment by mmitche** [comment] 2021-08-10 17:09
@danmoseley Can you help out @adityapatwardhan with a workaround?

**Comment by davidwrighton** [comment] 2021-08-10 20:43
This issue is caused by the new static interfaces features and the generic math feature.

What's happening is that for some reason the powershell code above is attempting to call the IMinMaxValue<short>.MinValue property without using the constrained prefix as is required by the static interfaces feature.

In a dump that @cston provided, I found that the error was triggered by generated IL that looked like...

```
call IMinMaxValue<short>.get_MinValue()
```

which given that IMinMaxValue<T>.get_MinValue is an abstract static method, caused the runtime to produce an exception.

That method is designed to be called by an IL sequence such as...
```
constrained. !0
call IMinMaxValue<!0>.get_MinValue()
```

Or possibly relevant to this situation
```
constrained. short
call IMinMaxValue<short>.get_MinValue()
```

However, I suspect the real fix is to not discover the IMinMaxValue<short>.MinValue property when looking for the implementation of `$($baseType::MinValue)` but instead to find the public const MinValue that has existed for many years. @cston, I hope you can take this issue from here as I'm not familiar with the mechanisms in Linq Expressions that are getting us into this situation.

**Comment by richlander** [comment] 2021-08-11 23:25
I added the blocking label since this issue is blocking PowerShell from (A) adopting a newer build than Preview 6, and (B) sym-shipping with us in November.

**Comment by daxian-dbw** [comment] 2021-08-11 23:34
@adityapatwardhan and I talked with @davidwrighton offline and the recommendation is to just ignore static virtual members on interfaces, especially as the set of APIs may change in .NET 7. We will make the necessary updates in PowerShell code.

**Comment by richlander** [comment] 2021-08-11 23:39
This seems like it is potentially a breaking change for Reflection users that still needs to be addressed. Is that right?

**Comment by daxian-dbw** [comment] 2021-08-11 23:46
Today, to call the abstract static method/property on an interface with reflection, one has to call `GetInterfaceMap(<interfaceType>)` on a concrete type that implements that interface, then get the target method and call `Invoke(null, args)` on the target method. It makes sense from the technical perspective since it's abstract, but from a user's view, it's not obvious and the error message "Bad IL format" could definitely be better.

@davidwrighton mentioned that the set of reflection APIs may change in .NET 7, so I guess work has already been planned for this new feature?

**Comment by davidwrighton** [comment] 2021-08-12 18:15
I don't expect the behavior of the reflection apis to change in .NET 7. What I do expect is that there will be virtual statics in addition to abstract statics, which is why I wanted you to be sure to check for IsVirtual and not IsAbstract on the method when writing your reflection check.

However, it is quite likely that the generic math apis will change between .NET 6 and .NET 7 those are still in flux, and the api surface exposed in the .NET 6 preview version of that feature is unlikely to exactly match the api surface exposed in .NET 7 official release of that feature.

**Comment by daxian-dbw** [comment] 2021-08-12 18:31
@davidwrighton, thanks for the clarification.

**Comment by cston** [comment] 2021-08-12 21:02
Closing since this issue is being addressed in https://github.com/PowerShell/PowerShell/pull/15908.

**Closed by cston** 2021-08-12 21:02 UTC
Labels: area-System.Linq.Expressions, blocking
