### ISSUE TITLE
Unexpected System.BadImageFormatException for an invocation of a static abstract method declared in a non-generic interface

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/runtime#74792] opened 2022-08-30 04:07 UTC
### Description

See https://github.com/dotnet/roslyn/issues/63617 for additional info.

### Expected behavior

Code should run successfully

### Actual behavior

System.BadImageFormatException is thrown

### Regression?

Do not know

### Known Workarounds

No

**Comment by AlekseyTs** [comment] 2022-08-30 04:09
@davidwrighton, @trylek FYI

**Comment by trylek** [comment] 2022-08-30 10:45
Hmm, I have just created a regression test for this issue but it seems to be passing on current runtime main in release mode. I'll try debug mode and I'll further poke on it later today, @AlekseyTs - would there be a way for you to identify the exact version of .NET runtime that hits this in Roslyn testing?

Thanks

Tomas

**Comment by AlekseyTs** [comment] 2022-08-30 15:37
The issue is reported by an external user and is reproducing in SharpLab, the original issue has the link. In Roslyn we still do not attempt to execute the test scenarios because our tests are still running against .NET 6. I am not sure what version of the runtime SharpLab is using.

**Comment by AlekseyTs** [comment] 2022-08-30 17:07
I just tried the scenario in VS (Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview Version 17.4.0 Preview 2.0 
 32817.501.main]) and it runs fine. I guess, it should be fine to add the test and close the issue as fixed.

**Comment by danmoseley** [comment] 2022-08-31 16:20
> our tests are still running against .NET 6

@AlekseyTs  when do you think you will run tests against 7?

**Comment by AlekseyTs** [comment] 2022-08-31 16:48
> when do you think you will run tests against 7?

When our infrastructure switches to run tests against 7. CC @dotnet/roslyn-infrastructure

**Comment by JoeRobich** [comment] 2022-08-31 17:03
@jaredpar shared some thoughts and challenges about adding a net7.0 target to our unit tests in https://github.com/dotnet/roslyn/issues/62510#issuecomment-1189081841. This something we can look at introducing to rolling builds in our September sprint.

**Comment by jaredpar** [comment] 2022-08-31 17:07
> When our infrastructure switches to run tests against 7. 

Our infrastructure currently executes our tests on a `net7.0` runtime but we still compile against `net6.0` reference assemblies. 

Note: moving the TF of the project to `net6.0` won't change this. The reference assemblies our compiler tests compile against are different than what TF we use in the project file. 

> @jaredpar shared some thoughts and challenges about adding a net7.0 target to our unit tests in https://github.com/dotnet/roslyn/issues/62510#issuecomment-1189081841. This something we can look at introducing to rolling builds in our September sprint.

I'm pretty confident our tests already execute against a `net7.0` runtime. Believe our helix setup matches our local global.json which forces a `net7.0` runtime. So while our tests target `net6.0` the execution environment should be `net7.0`. 

High level there are three TF to think about: 
1. The TF we use in the unit test project file
2. The TF runtime used to execute our tests
3. The TF reference assemblies our actual unit tests build against

Right now 2 is `net7.0` (to my understanding) and 1 + 3 are `net6.0`

**Comment by JoeRobich** [comment] 2022-08-31 17:10
> Right now 2 is net7.0 (to my understanding) 

Confirmed from a helix log that .NET 7 is the runtime.

```
C:\h\w\A1950933\w\A57F08F7\e>dotnet --info 
.NET SDK:
 Version:   7.0.100-preview.7.22377.5
 Commit:    ba310d9309

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\h\w\A1950933\p\dotnet-cli\sdk\7.0.100-preview.7.22377.5\

Host:
  Version:      7.0.0-preview.7.22375.6
  Architecture: x64
  Commit:       eecb028078

.NET SDKs installed:
  7.0.100-preview.7.22377.5 [C:\h\w\A1950933\p\dotnet-cli\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.0-preview.7.22376.6 [C:\h\w\A1950933\p\dotnet-cli\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.0-preview.7.22375.6 [C:\h\w\A1950933\p\dotnet-cli\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 7.0.0-preview.7.22377.1 [C:\h\w\A1950933\p\dotnet-cli\shared\Microsoft.WindowsDesktop.App]
```

**Comment by jaredpar** [comment] 2022-08-31 17:15
If it doesn't require any API from a `net7.0` reference assembly then we should be able to add the regression test now.

**Comment by AlekseyTs** [comment] 2022-08-31 17:19
@jaredpar, @JoeRobich Compiler test targeting new .NET 7 features are determining whether to execute a scenario when the test is compiled (```#if !NET7_0_OR_GREATER```). If a test is built against .NET 6, it really doesn't matter what runtimes are available when the test assembly is executed. If you'd like to get more details about that, let's take that offline.

> we should be able to add the regression test now.

Runtime is already adding one.

**Comment by mangod9** [comment] 2022-09-06 20:45
@trylek / @AlekseyTs is this required for 7?

**Comment by trylek** [comment] 2022-09-06 20:52
Well, there isn't a specific fix here, I just made a regression test and used it to double-check that the test now passes, I assume that means that the fix, whatever it was, has made it into .NET 7. I'm not sure if it makes sense to backport the regression test as such; I would assume that if someone in the future breaks it, they will see it from a PR failure and fix it before backporting their change to .NET 7 if need be.

**Comment by mangod9** [comment] 2022-09-06 22:27
So ok to close this or any action is still pending for this issue?

**Comment by trylek** [comment] 2022-09-06 23:10
I concur with @AlekseyTs's comment that

> I just tried the scenario in VS (Microsoft Visual Studio Enterprise 2022 (64-bit) - Int Preview Version 17.4.0 Preview 2.0
32817.501.main]) and it runs fine. I guess, it should be fine to add the test and close the issue as fixed.

**Closed by trylek** 2022-09-06 23:10 UTC
Labels: area-VM-coreclr, untriaged
