### ISSUE TITLE
System.Text.Json Polymorphism Type Discriminator Not Deserialized

### ISSUE THREAD

**Issue by 9ParsonsB** [dotnet/runtime#102455] opened 2024-05-20 14:27 UTC
### Description

When deserializing a polymorphic type with `TypeDiscriminatorPropertyName` set to an existing Property name, that Property is no longer deserialized

### Reproduction Steps

```csharp
[JsonPolymorphic(TypeDiscriminatorPropertyName = "event")]
[JsonDerivedType(typeof(ChildEvent), "child")]
public abstract class EventBase
{
    [JsonPropertyName("timestamp")]
    public DateTimeOffset Timestamp { get; init; }
    
    [JsonPropertyName("event")]
    public string Event { get; set; }
}

public class ChildEvent : EventBase;

var json = """
           { "event": "child", "timestamp":"2024-05-20T12:36:10Z" }
           """;

var obj = JsonSerializer.Derserialize<EventBase>(json);

Console.WriteLine(obj.Event); // ""

// obj.Event = null;

```

### Expected behavior

TypeDiscriminator Property is still deserialized

### Actual behavior

TypeDiscriminator Property is always null/default

### Configuration

.NET 9.0.100-preview.3.24204.13
Arch Linux 6.8.9-arch1-1 x86-64

**Comment by eiriktsarpalis** [comment] 2024-05-20 15:27
Duplicate of https://github.com/dotnet/runtime/issues/72170#issuecomment-1439773918. The runtime type of a property cannot be used to influence the discriminator which is a type-level mapping.

**Closed by eiriktsarpalis** 2024-05-20 15:27 UTC
Labels: area-System.Text.Json, untriaged
