### ISSUE TITLE
Test failure Regressions/coreclr/0099/AboveStackLimit/AboveStackLimit.sh

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#78622] opened 2022-11-21 06:12 UTC
Run: [runtime-coreclr ilasm 20221119.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=88711&view=ms.vss-test-web.build-test-results-tab&runId=1867338&resultId=103783&paneView=debug)

Failed test:
```
coreclr Linux x64 Checked ilasmroundtrip @ Ubuntu.1804.Amd64.Open

- Regressions/coreclr/0099/AboveStackLimit/AboveStackLimit.sh
- JIT/opt/virtualstubdispatch/bigvtbl/bigvtbl_cs_r/bigvtbl_cs_r.sh
- JIT/opt/virtualstubdispatch/bigvtbl/bigvtbl_cs_d/bigvtbl_cs_d.sh
- JIT/opt/virtualstubdispatch/bigvtbl/bigvtbl_cs_ro/bigvtbl_cs_ro.sh
- JIT/opt/virtualstubdispatch/bigvtbl/bigvtbl_cs_do/bigvtbl_cs_do.sh
... ...
```
**Error message:**
```
AboveStackLimit.dasm.il(71) : error : syntax error at token '�' in:           instance void .ctor(int32 �~�_0) cil managed
AboveStackLimit.dasm.il(71) : error : syntax error at token '�' in:           instance void .ctor(int32 �~�_0) cil managed
AboveStackLimit.dasm.il(71) : error : syntax error at token '�' in:           instance void .ctor(int32 �~�_0) cil managed

Return code:      1
Raw output file:      /datadisks/disk1/work/ADB50935/w/ADE908FA/uploads/Reports/Regressions.coreclr/0099/AboveStackLimit/AboveStackLimit.output.txt
Raw output:
BEGIN EXECUTION
/datadisks/disk1/work/ADB50935/p/ildasm -raweh -unicode -out=AboveStackLimit.dasm.il AboveStackLimit.dll
/datadisks/disk1/work/ADB50935/p/ilasm -output=AboveStackLimit.asm.dll AboveStackLimit.dasm.il

.NET IL Assembler.  Version 8.0.0-ci
Copyright (c) Microsoft Corporation.  All rights reserved.
Assembling 'AboveStackLimit.dasm.il'  to EXE --> 'AboveStackLimit.asm.dll'
Source file is UNICODE

Assembled method Microsoft.CodeAnalysis.EmbeddedAttribute::.ctor

***** FAILURE *****
EXECUTION 1 OF ILASM - FAILED with 1
Trying again
/datadisks/disk1/work/ADB50935/p/ilasm -output=AboveStackLimit.asm.dll AboveStackLimit.dasm.il

.NET IL Assembler.  Version 8.0.0-ci
Copyright (c) Microsoft Corporation.  All rights reserved.
Assembling 'AboveStackLimit.dasm.il'  to EXE --> 'AboveStackLimit.asm.dll'
Source file is UNICODE

Assembled method Microsoft.CodeAnalysis.EmbeddedAttribute::.ctor

***** FAILURE *****
EXECUTION 2 OF ILASM - FAILED with 1
Trying again
/datadisks/disk1/work/ADB50935/p/ilasm -output=AboveStackLimit.asm.dll AboveStackLimit.dasm.il

.NET IL Assembler.  Version 8.0.0-ci
Copyright (c) Microsoft Corporation.  All rights reserved.
Assembling 'AboveStackLimit.dasm.il'  to EXE --> 'AboveStackLimit.asm.dll'
Source file is UNICODE

Assembled method Microsoft.CodeAnalysis.EmbeddedAttribute::.ctor

***** FAILURE *****
EXECUTION 3 OF ILASM - FAILED with 1
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/datadisks/disk1/work/ADB50935/p
/datadisks/disk1/work/ADB50935/w/ADE908FA/e/Regressions/coreclr/0099/AboveStackLimit/AboveStackLimit.sh
Expected: True
Actual:   False


Stack trace
   at Regressions_coreclr._0099_AboveStackLimit_AboveStackLimit_._0099_AboveStackLimit_AboveStackLimit_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Queued | OS | Arch | Column1
-- | -- | -- | --
2022-10-23T10:50:07.47Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86 Checked-jitstress_isas_2_x86_nossse3](https://dev.azure.com/dnceng/public/_build/results?buildId=60194&view=ms.vss-test-web.build-test-results-tab&runId=1237810&resultId=107535&paneView=debug)
2022-10-23T10:45:16.715Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86 Checked-jitstress_isas_2_x86_nosse42](https://dev.azure.com/dnceng/public/_build/results?buildId=60194&view=ms.vss-test-web.build-test-results-tab&runId=1237804&resultId=107539&paneView=debug)
2022-10-23T10:44:53.419Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86 Checked-jitstress_isas_2_x86_nosse41](https://dev.azure.com/dnceng/public/_build/results?buildId=60194&view=ms.vss-test-web.build-test-results-tab&runId=1237802&resultId=107478&paneView=debug)
2022-10-23T10:13:30.363Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86 Checked-jitstress_isas_2_x86_nosse3_4](https://dev.azure.com/dnceng/public/_build/results?buildId=60194&view=ms.vss-test-web.build-test-results-tab&runId=1237656&resultId=107533&paneView=debug)
2022-10-23T08:40:09.83Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86 Checked-jitstress_isas_2_x86_nosse3](https://dev.azure.com/dnceng/public/_build/results?buildId=60194&view=ms.vss-test-web.build-test-results-tab&runId=1237156&resultId=107522&paneView=debug)
<details>
<summary>More failures</summary>

Queued | OS | Arch | Column1
-- | -- | -- | --
2022-10-23T08:32:58.173Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86 Checked-jitstress_isas_2_x86_nosse](https://dev.azure.com/dnceng/public/_build/results?buildId=60194&view=ms.vss-test-web.build-test-results-tab&runId=1237106&resultId=107484&paneView=debug)
2022-10-23T08:32:56.985Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86 Checked-jitstress_isas_2_x86_nosse2](https://dev.azure.com/dnceng/public/_build/results?buildId=60194&view=ms.vss-test-web.build-test-results-tab&runId=1237110&resultId=107497&paneView=debug)
2022-10-23T07:49:32.066Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86 Checked-jitstress_isas_2_x86_nohwintrinsic](https://dev.azure.com/dnceng/public/_build/results?buildId=60194&view=ms.vss-test-web.build-test-results-tab&runId=1236882&resultId=107507&paneView=debug)
2022-10-23T04:38:43.493Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86 Checked-jitstress_isas_1_x86_nossse3](https://dev.azure.com/dnceng/public/_build/results?buildId=60194&view=ms.vss-test-web.build-test-results-tab&runId=1235974&resultId=107529&paneView=debug)
2022-10-23T04:37:16.624Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86 Checked-jitstress_isas_1_x86_nosse42](https://dev.azure.com/dnceng/public/_build/results?buildId=60194&view=ms.vss-test-web.build-test-results-tab&runId=1235970&resultId=107493&paneView=debug)
2022-10-23T04:04:41.652Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86 Checked-jitstress_isas_1_x86_nosse41](https://dev.azure.com/dnceng/public/_build/results?buildId=60194&view=ms.vss-test-web.build-test-results-tab&runId=1235868&resultId=107500&paneView=debug)
2022-10-23T03:28:10.757Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86 Checked-jitstress_isas_1_x86_nosse3_4](https://dev.azure.com/dnceng/public/_build/results?buildId=60194&view=ms.vss-test-web.build-test-results-tab&runId=1235766&resultId=107537&paneView=debug)
2022-10-23T02:18:49.163Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86 Checked-jitstress_isas_1_x86_nosse3](https://dev.azure.com/dnceng/public/_build/results?buildId=60194&view=ms.vss-test-web.build-test-results-tab&runId=1235438&resultId=107500&paneView=debug)
2022-10-23T02:17:36.068Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86 Checked-jitstress_isas_1_x86_nosse2](https://dev.azure.com/dnceng/public/_build/results?buildId=60194&view=ms.vss-test-web.build-test-results-tab&runId=1235418&resultId=107506&paneView=debug)
2022-10-23T01:51:59.137Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86 Checked-jitstress_isas_1_x86_nosse](https://dev.azure.com/dnceng/public/_build/results?buildId=60194&view=ms.vss-test-web.build-test-results-tab&runId=1235278&resultId=107539&paneView=debug)
2022-10-23T01:11:53.966Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress-isas-x86 Checked-jitstress_isas_1_x86_nohwintrinsic](https://dev.azure.com/dnceng/public/_build/results?buildId=60194&view=ms.vss-test-web.build-test-results-tab&runId=1235094&resultId=106850&paneView=debug)
2022-10-22T23:43:34.63Z | osx.1200.arm64.open | arm64 | [runtime-coreclr gcstress-extra Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=60210&view=ms.vss-test-web.build-test-results-tab&runId=1234568&resultId=106684&paneView=debug)
2022-10-22T23:24:37.995Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr gcstress-extra Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=60210&view=ms.vss-test-web.build-test-results-tab&runId=1234520&resultId=105986&paneView=debug)
2022-10-22T23:23:04.467Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr gcstress-extra Checked-gcstress0xc_zapdisable_jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=60210&view=ms.vss-test-web.build-test-results-tab&runId=1234498&resultId=106438&paneView=debug)
2022-10-20T06:41:34.456Z | osx.1200.arm64.open | arm64 | [runtime-coreclr jitstress Checked-jitstress2_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=57962&view=ms.vss-test-web.build-test-results-tab&runId=1189108&resultId=110638&paneView=debug)
2022-09-23T06:56:27.552Z | osx.1200.arm64.open | arm64 | [runtime-coreclr jitstress Checked-jitstress2_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=27197&view=ms.vss-test-web.build-test-results-tab&runId=545718&resultId=107693&paneView=debug)
2022-09-23T06:01:52.287Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress Checked-jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=27197&view=ms.vss-test-web.build-test-results-tab&runId=544928&resultId=106659&paneView=debug)
2022-09-23T06:01:51.583Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress Checked-jitstress1](https://dev.azure.com/dnceng/public/_build/results?buildId=27197&view=ms.vss-test-web.build-test-results-tab&runId=544924&resultId=106711&paneView=debug)
2022-09-22T06:52:24.578Z | osx.1200.arm64.open | arm64 | [runtime-coreclr jitstress Checked-jitstress2_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=25851&view=ms.vss-test-web.build-test-results-tab&runId=520634&resultId=107894&paneView=debug)
2022-09-22T06:37:18.032Z | osx.1200.arm64.open | arm64 | [runtime-coreclr jitstress Checked-jitstress1_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=25851&view=ms.vss-test-web.build-test-results-tab&runId=520452&resultId=107689&paneView=debug)
2022-09-22T06:19:28.4Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress Checked-jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=25851&view=ms.vss-test-web.build-test-results-tab&runId=520258&resultId=106694&paneView=debug)
2022-09-22T06:19:26.433Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress Checked-jitstress1](https://dev.azure.com/dnceng/public/_build/results?buildId=25851&view=ms.vss-test-web.build-test-results-tab&runId=520256&resultId=106714&paneView=debug)
2022-10-12T08:58:25.529Z | osx.1015.amd64.open | x64 | [runtime-staging Release](https://dev.azure.com/dnceng/public/_build/results?buildId=49282&view=ms.vss-test-web.build-test-results-tab&runId=992930&resultId=101910&paneView=debug)
2022-09-24T08:51:23.447Z | osx.1015.amd64.open | x64 | [runtime-staging Release](https://dev.azure.com/dnceng/public/_build/results?buildId=28573&view=ms.vss-test-web.build-test-results-tab&runId=576324&resultId=101870&paneView=debug)
2022-09-23T06:10:23.938Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr jitstress Checked-jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=27197&view=ms.vss-test-web.build-test-results-tab&runId=545044&resultId=102673&paneView=debug)
2022-09-22T07:09:06.366Z | ubuntu.1804.amd64.open.rt | x64 | [runtime-coreclr jitstress Checked-jitstress2_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=25851&view=ms.vss-test-web.build-test-results-tab&runId=520844&resultId=103615&paneView=debug)
2022-09-22T06:23:36.542Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr jitstress Checked-jitstress1_tiered](https://dev.azure.com/dnceng/public/_build/results?buildId=25851&view=ms.vss-test-web.build-test-results-tab&runId=520288&resultId=101899&paneView=debug)
2022-09-22T06:23:34.727Z | ubuntu.1804.armarch.open | arm | [runtime-coreclr jitstress Checked-jitstress1](https://dev.azure.com/dnceng/public/_build/results?buildId=25851&view=ms.vss-test-web.build-test-results-tab&runId=520290&resultId=102729&paneView=debug)
2022-09-22T06:11:07.948Z | ubuntu.1804.armarch.open | arm64 | [runtime-coreclr jitstress Checked-jitstress2](https://dev.azure.com/dnceng/public/_build/results?buildId=25851&view=ms.vss-test-web.build-test-results-tab&runId=520160&resultId=102696&paneView=debug)

</details>

**Comment by jakobbotsch** [comment] 2022-11-21 20:51
cc @markples, not sure if this is related to the recent changes

**Comment by markples** [comment] 2022-11-21 22:01
This is likely the same as #78623, but I don't know yet.

**Comment by markples** [comment] 2022-11-21 22:26
This appears to be Linux/OSX-only.

**Comment by markples** [comment] 2022-11-22 18:41
Duplicate of #78623

**Closed** 2022-11-22 21:57 UTC
Labels: os-linux, arch-x64, area-CodeGen-coreclr, untriaged, blocking-clean-ci-optional
