### ISSUE TITLE
Test failure: ilverify\\ILVerificationTests.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#102428] opened 2024-05-20 01:21 UTC
**Failed in:** [runtime-coreclr jitstress 20240516.5](https://dev.azure.com/dnceng-public/public/_build/results?buildId=678708&view=ms.vss-test-web.build-test-results-tab&runId=16826446&resultId=100021&paneView=debug)

**Failed tests:**
```
coreclr windows arm64 Checked jitstress2_tiered @ Windows.11.Arm64.Open
    - ilverify\\ILVerificationTests.cmd
    - profiler\\gc\\gcbasic\\gcbasic.cmd
    - GC\\API\\GC\\GetTotalAllocatedBytes\\GetTotalAllocatedBytes.cmd
    - GC\\API\\GC\\KeepAliveNull\\KeepAliveNull.cmd
    - GC\\API\\GCHandleCollector\\Usage\\Usage.cmd
    - GC\\API\\GCHandleCollector\\Count\\Count.cmd
    - GC\\Features\\KeepAlive\\keepaliveother\\keepalivescope\\keepalivescope.cmd
    - GC\\Regressions\\v2.0-beta1\\149926\\149926\\149926.cmd
    - GC\\Regressions\\v2.0-beta2\\452950\\452950\\452950.cmd
    - GC\\Scenarios\\DoublinkList\\doublinkgen\\doublinkgen.cmd
    - GC\\Scenarios\\DoublinkList\\doublinkstay\\doublinkstay.cmd
    - GC\\Scenarios\\DoublinkList\\dlstack\\dlstack.cmd
    - GC\\Scenarios\\DoublinkList\\dlcollect\\dlcollect.cmd
    - GC\\Scenarios\\DoublinkList\\dlbigleakthd_v2\\dlbigleakthd_v2.cmd
    - GC\\Scenarios\\LeakGen\\leakgenthrd\\leakgenthrd.cmd
    - GC\\Scenarios\\BinTree\\thdtreegrowingobj\\thdtreegrowingobj.cmd
    - GC\\Scenarios\\BinTree\\thdtreelivingobj\\thdtreelivingobj.cmd
    - GC\\Scenarios\\SingLinkList\\singlinkstay\\singlinkstay.cmd
    - GC\\Scenarios\\DoublinkList\\doublinknoleak2\\doublinknoleak2.cmd
    - GC\\Scenarios\\DoublinkList\\dlbigleakthd\\dlbigleakthd.cmd
    - GC\\Scenarios\\BinTree\\thdtree\\thdtree.cmd
    - GC\\Scenarios\\DoublinkList\\dlbigleak\\dlbigleak.cmd
coreclr windows arm64 Checked jitstress2 @ Windows.11.Arm64.Open
    - ilverify\\ILVerificationTests.cmd
    - profiler\\gc\\gcbasic\\gcbasic.cmd
    - GC\\API\\GCHandleCollector\\Usage\\Usage.cmd
    - GC\\API\\GCHandleCollector\\Count\\Count.cmd
    - GC\\Features\\KeepAlive\\keepaliveother\\keepalivescope\\keepalivescope.cmd
    - GC\\Regressions\\v2.0-beta2\\452950\\452950\\452950.cmd
    - GC\\Scenarios\\BinTree\\thdtreegrowingobj\\thdtreegrowingobj.cmd
    - GC\\Scenarios\\SingLinkList\\singlinkstay\\singlinkstay.cmd
    - GC\\Scenarios\\BinTree\\thdtree\\thdtree.cmd
    - GC\\Scenarios\\BinTree\\thdtreelivingobj\\thdtreelivingobj.cmd
coreclr windows arm64 Checked jitstress1_tiered @ Windows.11.Arm64.Open
    - ilverify\\ILVerificationTests.cmd
    - GC\\API\\GC\\GetTotalAllocatedBytes\\GetTotalAllocatedBytes.cmd
    - GC\\Regressions\\v2.0-beta1\\149926\\149926\\149926.cmd
    - GC\\Scenarios\\LeakGen\\leakgenthrd\\leakgenthrd.cmd
    - GC\\Scenarios\\BinTree\\thdtreelivingobj\\thdtreelivingobj.cmd
coreclr windows arm64 Checked jitstress1 @ Windows.11.Arm64.Open
    - GC\\Scenarios\\BinTree\\thdtreelivingobj\\thdtreelivingobj.cmd
```

**Error message:**
```
 
Assert failure(PID 8552 [0x00002168], Thread: 4456 [0x1168]): (uImageBase == uImageBaseFromOS) && (memcmp(pFunctionEntry, pFunctionEntryFromOS, sizeof(RUNTIME_FUNCTION)) == 0)

CORECLR! Thread::VirtualUnwindCallFrame + 0xDC (0x00007ffd`61a79f7c)
CORECLR! EECodeManager::EnsureCallerContextIsValid + 0x70 (0x00007ffd`619b8f38)
CORECLR! StackFrameIterator::CheckForSkippedFrames + 0x34 (0x00007ffd`61a75dac)
CORECLR! StackFrameIterator::ProcessCurrentFrame + 0x12C (0x00007ffd`61a7928c)
CORECLR! StackFrameIterator::NextRaw + 0x5C4 (0x00007ffd`61a78b1c)
CORECLR! Thread::StackWalkFramesEx + 0x28C (0x00007ffd`61a79d7c)
CORECLR! Thread::StackWalkFrames + 0x130 (0x00007ffd`61a79a48)
CORECLR! ScanStackRoots + 0x290 (0x00007ffd`61b197f0)
CORECLR! GCToEEInterface::GcScanRoots + 0x1A4 (0x00007ffd`61b18564)
CORECLR! WKS::gc_heap::mark_phase + 0x4D4 (0x00007ffd`61ce0f14)
    File: D:\a\_work\1\s\src\coreclr\vm\stackwalk.cpp:596
    Image: C:\h\w\9C7308A1\p\corerun.exe


Return code:      1
Raw output file:      C:\h\w\9C7308A1\w\B1DE09B8\uploads\Reports\ilverify\ILVerificationTests.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\9C7308A1\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false" -p "System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true"  ILVerificationTests.dll 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test failed. Trying to see if dump file was created in C:\cores since 5/17/2024 5:39:15 AM
Processing C:\cores\corerun.exe.8552.dmp
Unable to find cdb.exe at C:\Program Files (x86)\Windows Kits\10\Debuggers\arm64\cdb.exe
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\9C7308A1\p
> C:\h\w\9C7308A1\w\B1DE09B8\e\ilverify\ILVerificationTests.cmd
```

**Stack trace:**
```
   at ilverify._ILVerificationTests_._ILVerificationTests_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

**Comment by jkotas** [comment] 2024-05-20 02:53
Duplicate of #102337 ? cc @janvorli

**Comment by janvorli** [comment] 2024-05-20 11:58
I'll take a look.

**Comment by janvorli** [comment] 2024-05-20 12:01
Yes, the tests above were run from a state of main before my fix went in.

**Comment by janvorli** [comment] 2024-05-20 12:02
Dup of #102337

**Closed by janvorli** 2024-05-20 12:02 UTC
Labels: arch-arm64, os-windows, JitStress, area-VM-coreclr, untriaged, blocking-clean-ci-optional
