### ISSUE TITLE
StringComparer.CurrentCulture incorrectly sorts Turkish letters

### ISSUE THREAD

**Issue by AmadeusW** [dotnet/runtime#40847] opened 2020-08-14 18:15 UTC
### Description

Some of the letters from the Turkic alphabet are incorrectly sorted, even when using `StringComparer.CurrentCulture` using ``CultureInfo("tr-TR")`

I set up a simple program which attempts to sort letters using various `StringComparer`s and `CultureInfo`s:
https://gist.github.com/AmadeusW/892c4a3d3d341b50d964d1834f0d91e9

Sorting `new[] { 'h', 'ğ', 'g', 'i', 'k', 'ı', 'j', 'Ğ', 'H', 'G', 'I', 'K', 'İ', 'J' }` 
should result in `"G Ğ H I İ J K g ğ h ı i j k"`
but instead we get `"G H I J K g h i j k Ğ ğ İ ı"`

BTW, is it possible to get these characters sorted correctly in `en-US` culture?

### Configuration

.NETFramework 4.7.2 on Windows 10.0.19041 Build 19041 x64
.NET 3.1 on Windows 10.0.19041 Build 19041 x64
.NET 5.0 on Windows 10.0.19041 Build 19041 x64
Reproes on coworker's machine as well

### Regression?

Don't know, .NET Framework 4.7.2 seems broken

**Comment by BertanAygun** [comment] 2020-08-14 18:18
This example also seems to be broken on my machine: https://docs.microsoft.com/en-us/dotnet/api/system.stringcomparer.ordinalignorecase?view=netcore-3.1

I've also tried with letters like c ç o ö s ş u ü which shows the same behavior. The Turkish specific letters are always sorted to end.

**Comment by svick** [comment] 2020-08-14 21:31
The problem is that you're using **string** comparer to compare **chars**. If I switch to comparing strings, I get output that's much closer to what you're expecting.

My code:

```c#
static void Main()
{
    var chars0 = new[] { 'h', 'ğ', 'g', 'i', 'k', 'ı', 'j', 'Ğ', 'H', 'G', 'I', 'K', 'İ', 'J' };
    var chars = chars0.Select(c => c.ToString()).ToArray();

    var ordinal = Sort(chars, StringComparer.Ordinal);
    var outputOrdinal = string.Join(' ', ordinal);
    Console.WriteLine(outputOrdinal);

    var invariant = Sort(chars, StringComparer.InvariantCulture);
    var outputInvariant = string.Join(' ', invariant);
    Console.WriteLine(outputInvariant);

    CultureInfo turkic = new CultureInfo("tr-TR");
    Thread.CurrentThread.CurrentCulture = turkic;
    var culturedTr = Sort(chars, StringComparer.CurrentCulture);
    var outputTr = string.Join(' ', culturedTr);
    Console.WriteLine(outputTr);
}

static IEnumerable<string> Sort(string[] chars, StringComparer comparer)
{
    string[] copy = new string[chars.Length];
    Array.Copy(chars, copy, chars.Length);
    Array.Sort(copy, comparer);
    return copy;
}
```

The output:

```
G H I J K g h i j k Ğ ğ İ ı
g G ğ Ğ h H i I İ ı j J k K
g G ğ Ğ h H ı I i İ j J k K
```

Note that this error becomes much more obvious if you use a more modern API. For example with my modifications, `chars.OrderBy(c => c, StringComparer.CurrentCulture)` compiles fine, while `chars0.OrderBy(c => c, StringComparer.CurrentCulture)` produces:

> error CS0411: The type arguments for method 'Enumerable.OrderBy\<TSource, TKey>(IEnumerable\<TSource>, Func\<TSource, TKey>, IComparer\<TKey>?)' cannot be inferred from the usage. Try specifying the type arguments explicitly.

The problem is that the overload `Array.Sort(Array, IComparer)` accepts any comparer for any array and a correctly implemented `IComparer` shouldn't throw for types it doesn't know how to handle itself. Maybe it would make sense to obsolete that overload, considering that correct usages should use `Array.Sort<T>(T[], IComparer<T>)` instead?

**Comment by am11** [comment] 2020-08-14 22:10
> This example also seems to be broken on my machine: https://docs.microsoft.com/en-us/dotnet/api/system.stringcomparer.ordinalignorecase?view=netcore-3.1

Interestingly, output from that documented example on .NET 5.0.100-preview.8.20362.3 and .NET 4.7.2 are the same; that is, both are different than what documentation suggests should be.

Difference:

```diff
--- expected	2020-08-14 22:06:54.787516000 +0000
+++ actual	2020-08-14 22:07:30.989684000 +0000
@@ -9,8 +9,8 @@
 0x131
 
 Invariant culture, ignore case...
-0x49
 0x69
+0x49
 0x131
 
 The current culture is "en-US".
@@ -20,8 +20,8 @@
 0x131
 
 Current culture, ignore case...
-0x49
 0x69
+0x49
 0x131
 
 Ordinal...
@@ -30,11 +30,12 @@
 0x131
 
 Ordinal, ignore case...
-0x69
 0x49
+0x69
 0x131
 
 Turkish culture, ignore case...
-0x131
 0x49
+0x131
 0x69
```

**Comment by BertanAygun** [comment] 2020-08-14 22:12
@svick, I can repro the same sorting strings as well using List.Sort suggested by the MSDN link I posted earlier. I get the same output as @am11, which is the wrong output.

**Comment by svick** [comment] 2020-08-14 22:25
@am11 @BertanAygun As far as I can tell, the only difference is how values that only differ in case (according to the given culture) are sorted when ignoring case. And since `List<T>.Sort` is documented as being unstable, it's okay that the order is different in that situation.

If you still think there is an issue, can clarify why the output is incorrect?

**Comment by BertanAygun** [comment] 2020-08-14 22:50
Here is another example, these should have output "cçıi" per Turkish alphabet ordering. On try.dot.net, it outputs 'ciçı'.

`        // Create a list of string.
        List<string> list = new List<string>();
        list.Add("ç");
        list.Add("c");
        list.Add("i");
        list.Add("ı");

        // Get the tr-TR (Turkish-Turkey) culture.
        CultureInfo turkish = new CultureInfo("tr-TR");
        foreach (var s in list.OrderBy(s => s, StringComparer.Create(turkish, false)))
        {
          Console.Write(s);
        }`

**Comment by am11** [comment] 2020-08-14 22:55
I am not sure if the output of unstable sort being different across the frameworks is ok; if not, then maybe that is not the problem here, since both .NET Framework 4.7.2 and .NET 5 are showing a consistent output.

**Comment by BertanAygun** [comment] 2020-08-14 22:59
I tested this locally and get the correct output both for netcoreapp3.1 and net472 but I consistently get the wrong output on try.dot.net. Not sure which host try.dot.net uses but it could be related to that now. 

Although I would expect runtime to throw if sorting by given culture isn't supported on the host since it can cause unexpected behavior in the app.

**Comment by svick** [comment] 2020-08-14 23:15
@BertanAygun I *think* this happens because try.dot.net is using Blazor, [which omits some culture information by default](https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-3.1#blazor-webassembly). You might want to open an issue on [dotnet/try](https://github.com/dotnet/try/) about this.

**Comment by tarekgh** [comment] 2020-08-14 23:23
Thanks @svick for your follow up replies. I believe you are right. easiest way to confirm is rung the line of code 

```
Console.WriteLine(RuntimeInformation.FrameworkDescription);
```

which prints: 
`Mono 6.5.0 (explicit/9f49cc85af1)`

by that I am closing this issue. You may try the latest version of Blazor and you can report the issue if it is still there.

**Closed by tarekgh** 2020-08-14 23:23 UTC
Labels: area-System.Globalization, question
