### ISSUE TITLE
The version string is placed into libcoreclr.so many times

### ISSUE THREAD

**Issue by janvorli** [dotnet/runtime#41612] opened 2020-08-31 17:34 UTC
The version string embedded into libcoreclr.so is present 21 times in the .NET 5.0 RC1 runtime.
In other libraries that are part of coreclr, the version string is also embedded multiple times. 

I've found that this problem was caused by the #36847, most likely triggered by using object libraries 
instead of static ones for the coreclr libraries subcomponents.

**Comment by ViktorHofer** [comment] 2020-09-01 19:01
Duplicate of https://github.com/dotnet/runtime/issues/39456

**Closed by ViktorHofer** 2020-09-01 19:01 UTC
Labels: area-Infrastructure-coreclr
