### ISSUE TITLE
In .NET 7 RuntimeHelpers.PrepareMethod no longer jits a method

### ISSUE THREAD

**Issue by Symbai** [dotnet/runtime#83042] opened 2023-03-06 19:39 UTC
### Description

In .NET Framework up to .NET 6 it was possible to force jitting a method using `RuntimeHelpers.PrepareMethod(methodInfo.MethodHandle)` function. Then obtain the memory address of the jitted method using `methodInfo.MethodHandle.GetFunctionPointer().ToInt64()`.

In .NET 7 however this doesn't lead to the jitted method. It leads to an indirect jump instruction:

`7FFD3B3F81B0 - FF 25 FA0F0000        - jmp qword ptr [7FFD3B3F91B0]`

IF(!) the method is jitted by the runtime. This indirect jump goes to the jitted method. If not, it leads to:

```
7FFD3E0A4360 - 48 8B 05 F90F0000     - mov rax,[7FFD3E0A5360]
7FFD3E0A4367 - 66 FF 08              - dec word ptr [rax]
7FFD3E0A436A - 74 06                 - je 7FFD3E0A4372
7FFD3E0A436C - FF 25 F60F0000        - jmp qword ptr [7FFD3E0A5368]
7FFD3E0A4372 - FF 25 F80F0000        - jmp qword ptr [7FFD3E0A5370] 
```

Where none of these leads to the jitted method. It always looks like that above for any method I've tried. Its always a mov, dec, JE instruction followed by two indirect jump instructions. In other words, it is no longer possible to force the runtime jitting a method and obtaining the correct memory address anymore. At least not by the way it has worked before and I couldn't find any note about a breaking change.

### Reproduction Steps

```
Assembly assembly = AppDomain.CurrentDomain.GetAssemblies()[0];
CType type = assembly.Type[0];
MethodInfo methodInfo = type.Methods.Single(x => x.Name == "Bla");

RuntimeHelpers.PrepareMethod(methodInfo.MethodHandle);
MessageBox.Show(methodInfo.MethodHandle.GetFunctionPointer().ToInt64().ToString("X"));
```

### Expected behavior

I expect to get the memory address of the jitted method

### Actual behavior

I get somewhat different but only if the method is not jitted by the runtime yet

### Regression?

Yes, worked in .NET Framework up to .NET 6

**Comment by EgorBo** [comment] 2023-03-06 19:50
```
7FFD3E0A4360 - 48 8B 05 F90F0000     - mov rax,[7FFD3E0A5360]
7FFD3E0A4367 - 66 FF 08              - dec word ptr [rax]
7FFD3E0A436A - 74 06                 - je 7FFD3E0A4372
7FFD3E0A436C - FF 25 F60F0000        - jmp qword ptr [7FFD3E0A5368]
7FFD3E0A4372 - FF 25 F80F0000        - jmp qword ptr [7FFD3E0A5370] 
```
this is a call-counting stub that is needed to promote method to Tier1 (that `dec` instruction is basically decreasing call-count from 30 to 0)

**Comment by EgorBo** [comment] 2023-03-06 19:51
Although, presumably PrepareMethod is expected to compile straight to tier1 so callcounting stub is not expected

**Comment by EgorBo** [comment] 2023-03-06 19:54
Yes, looks like `RuntimeHelpers.PrepareMethod` compiles code to Tier0 by default. No idea what's the expected behavior here cc @jkotas

**Comment by jkotas** [comment] 2023-03-07 04:33
In .NET Core/5+, `RuntimeHelpers.PrepareMethod` ensures that there is code generated for the method and that invocation of the method is not going to trigger immediate synchronous JITing. It does not make any guarantees about the kind of code that is generated, it can be R2R, Tier 0, Tier 1, ... .

Closing as by design / duplicate of https://github.com/dotnet/runtime/issues/1711

**Closed by jkotas** 2023-03-07 04:33 UTC
Labels: area-CodeGen-coreclr

**Comment by Symbai** [comment] 2023-03-07 15:47
If this is by design then it should get documented as a breaking change. As it breaks existing code. Is there any workaround? The API request #1711 is from 2020 without any activity. It is not even reviewed / approved etc and probably will not for the next years as no one goes back and reviews such old requests.

**Comment by jkotas** [comment] 2023-03-07 16:03
Implementation of this method has not changed for quite some time. There is nothing to fix.

The exact layout of the code that gets returned by `RuntimeMethodHandle.GetFunctionPointer()` internal implementation detail. Changes in internal implementation details of the runtime are not considered to be breaking changes. If the code depends on internal implementation details, it should expect to be broken without notice.
