### ISSUE TITLE
DOTNET_GCHeapHardLimitPercent being ignored without warnings

### ISSUE THREAD

**Issue by theolivenbaum** [dotnet/runtime#100804] opened 2024-04-09 07:27 UTC
### Description

We've a customer report setting DOTNET_GCHeapHardLimitPercent = 64 (i.e. 100%) on a container, and hitting OOM issues when the container was way under the real memory limit value assigned to the container. After some investigation, it seems like the 100% value was being ignored and replaced by the default 75% value, and after setting it to a lower value (for example 61 or 97%), all started to work fine. I couldn't find in the documentation if there was any limit on this value. 

I'm not sure if this is intended or a bug on the code reading DOTNET_GCHeapHardLimitPercent, but in any case, would be nice to have something like the [abort_conf](https://man.freebsd.org/cgi/man.cgi?jemalloc(3)#:~:text=disabled%20by%20default.-,opt.abort_conf,-(bool)%20r) option from jemalloc to avoid these hidden configuration failures.

### Reproduction Steps

Set `DOTNET_GCHeapHardLimitPercent=64` on a container, check reported value in `GC.GetConfigurationVariables()`

### Expected behavior

No OOM issues

### Actual behavior

Constant OOM issues when reaching 75% of available memory limit on container.

### Known Workarounds

Setting a slightly lower value works.

### Configuration

.NET 8.0 latest release, x64, running on an OpenShift container.

**Comment by mangod9** [comment] 2024-05-02 21:03
the docs do mention that setting the limit to 100% is invalid.

**Comment by mangod9** [comment] 2024-06-26 22:35
Closing for now as its by design.

**Closed by mangod9** 2024-06-26 22:35 UTC
Labels: area-GC-coreclr, untriaged

**Comment by theolivenbaum** [comment] 2024-06-27 03:32
@mangod9 are you sure this is mentioned in the docs?

https://learn.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector#heap-limit-percent

I could only find that the sum of the three values for Per-object-heap limits percent must be smaller than 100:


```
Each value must be greater than zero and less than 100. Additionally, the sum of the three percentage values must be less than 100. Otherwise, the runtime will fail to initialize.
```

It also implies it would fail when you set the sum to 100 or more, which was not the case for setting heap-limit percent to 100%.
