### ISSUE TITLE
Test failure profiler\\eventpipe\\reverse_startup\\reverse_startup.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#65352] opened 2022-02-15 01:34 UTC
Run: [runtime-coreclr r2r-extra 20220213.1
](https://dev.azure.com/dnceng/public/_build/results?buildId=1610717&view=ms.vss-test-web.build-test-results-tab&runId=44868956&paneView=debug&resultId=100502)

Failed test:
```
R2R windows x86 Checked jitstressregs1 @ Windows.10.Amd64.Open

- profiler\\eventpipe\\reverse_startup\\reverse_startup.cmd
- profiler\\eventpipe\\eventpipe\\eventpipe.cmd
- profiler\\eventpipe\\eventpipe_readevents\\eventpipe_readevents.cmd

R2R windows x64 Checked forcerelocs @ Windows.10.Amd64.Open

- Regressions\\coreclr\\GitHub_47007\\test47007\\test47007.cmd
- readytorun\\multifolder\\multifolder\\multifolder.cmd
- baseservices\\exceptions\\generics\\GenericExceptions\\GenericExceptions.cmd
- readytorun\\determinism\\crossgen2determinism\\crossgen2determinism.cmd
- baseservices\\exceptions\\unittests\\StrSwitchFinally\\StrSwitchFinally.cmd
- readytorun\\coreroot_determinism\\coreroot_determinism\\coreroot_determinism.cmd
- baseservices\\exceptions\\generics\\nested-try-catch05\\nested-try-catch05.cmd
- baseservices\\exceptions\\regressions\\v1.0\\19896\\19896.cmd
- baseservices\\exceptions\\unittests\\ReturnFromCatch\\ReturnFromCatch.cmd
- baseservices\\TieredCompilation\\BasicTestWithMcj\\BasicTestWithMcj.cmd
- baseservices\\exceptions\\generics\\try-filter-finally01\\try-filter-finally01.cmd
- baseservices\\exceptions\\generics\\TypeParameter017\\TypeParameter017.cmd
- baseservices\\exceptions\\stackoverflow\\stackoverflowtester\\stackoverflowtester.cmd
```
**Error message:**
```
Could Not Find C:\h\w\AE74095D\w\B8A109A4\e\profiler\eventpipe\reverse_startup\IL-CG2\composite-r2r.dll
Could Not Find C:\h\w\AE74095D\w\B8A109A4\e\profiler\eventpipe\reverse_startup\common.dll.rsp
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'ILCompiler.DependencyAnalysisFramework, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'. The module was expected to contain an assembly manifest.
File name: 'ILCompiler.DependencyAnalysisFramework, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'
at ILCompiler.ReadyToRunCodegenCompilationBuilder.ToCompilation()
at ILCompiler.Program.RunSingleCompilation(Dictionary2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary2 unrootedInputFilePaths, HashSet`1 versionBubbleModulesHash, CompilerTypeSystemContext typeSystemContext)
at ILCompiler.Program.Run(String[] args)
at ILCompiler.Program.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\AE74095D\w\B8A109A4\uploads\Reports\profiler.eventpipe\reverse_startup\reverse_startup.output.txt
Raw output:
BEGIN EXECUTION
common.dll
Profiler.dll
profiler_common.dll
reverse_startup.dll
TestLibrary.dll
5 file(s) copied.
Response file: C:\h\w\AE74095D\w\B8A109A4\e\profiler\eventpipe\reverse_startup\common.dll.rsp
C:\h\w\AE74095D\w\B8A109A4\e\profiler\eventpipe\reverse_startup\IL-CG2\common.dll
-o:C:\h\w\AE74095D\w\B8A109A4\e\profiler\eventpipe\reverse_startup\common.dll
--targetarch:x86
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\AE74095D\p\System..dll
-r:C:\h\w\AE74095D\p\Microsoft..dll
-r:C:\h\w\AE74095D\p\mscorlib.dll
-r:C:\h\w\AE74095D\p\netstandard.dll
-O
" "dotnet" "C:\h\w\AE74095D\p\crossgen2\crossgen2.dll" @"C:\h\w\AE74095D\w\B8A109A4\e\profiler\eventpipe\reverse_startup\common.dll.rsp"   -r:C:\h\w\AE74095D\w\B8A109A4\e\profiler\eventpipe\reverse_startup\IL-CG2*.dll"
Crossgen2 failed with exitcode - -532462766
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\AE74095D\p
C:\h\w\AE74095D\w\B8A109A4\e\profiler\eventpipe\reverse_startup\reverse_startup.cmd
Expected: True
Actual:   False


Stack trace
   at profiler_eventpipe._reverse_startup_reverse_startup_._reverse_startup_reverse_startup_cmd()
```

**Comment by trylek** [comment] 2022-04-04 20:32
Closing as duplicate of: https://github.com/dotnet/runtime/issues/65646

**Closed by trylek** 2022-04-04 20:32 UTC
Labels: arch-x86, os-windows, JitStress, area-crossgen2-coreclr, untriaged
