### ISSUE TITLE
System.Text.Json 9.0 error

### ISSUE THREAD

**Issue by BlameTwo** [dotnet/runtime#110283] opened 2024-11-30 14:35 UTC
### Description

In System In Text. Json, when I perform AOT publishing on the application, the error message is: 
Method not found: 'Void System.' Text.Json.Serialization.Metadata.JsonObjectInfoValues`1<WavesLauncher.Core.Models.LauncherIndex>.set_ConstructorAttributeProviderFactory(System.Func`1<System.Reflection.ICustomAttributeProvider>)'.

My development environment is as follows:
`Visual Studio 2022 preview 17.13`
`net8.0-windows10.0.22621.0`
`C# preview`
`WindowsAppSdk 1.6`

In the application, I explicitly applied `System Text. Json 9.0` Nuget package, I encountered an error while running the application after AOT. When I removed  After  `System .Text. Json 9.0`, it was found that everything was normal.

Has this problem already occurred? But I find this very strange, as if the version is incompatible, and there are no warning signs, which confuses me.

### Reproduction Steps

Create one Net 8 program, and simply create a Json object and implement its JsonContext generator. Note that you need to manually reference `System.Text.Json 9.0` package.

Afterwards, write a simple serialization and deserialization logic and publish the program in AOT format to generate errors

### Expected behavior

He should execute any serialization and deserialization program logic normally

### Actual behavior

Method not found: 'Void System.' Text.Json.Serialization.Metadata.JsonObjectInfoValues`1<WavesLauncher.Core.Models.LauncherIndex>.set_ConstructorAttributeProviderFactory(System.Func`1<System.Reflection.ICustomAttributeProvider>)'.

**Comment by vcsjones** [comment] 2024-11-30 14:46
This looks like a duplicate of https://github.com/dotnet/runtime/issues/110214

Please see that issue for more details.

**Closed** 2024-11-30 19:19 UTC
Labels: area-System.Text.Json, untriaged
