### ISSUE TITLE
Null Reference Exception In System.SpanHelpers.PerTypeValues`1.MeasureArrayAdjustment

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#52999] opened 2021-05-19 23:12 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Null-Reference-Exception-In-SystemSpanH/1425914)._

---
[severity:I'm unable to use this version]
**Description**
In production systems (but not our dev environment, we cannot reproduce at will) we are seeing a null reference exception thrown out of System.SpanHelpers.PerTypeValues`1.MeasureArrayAdjustment. This is being called as the result of an MS App Insights (v2.17) SDK call.

The stack trace/exception details look like:
System.TypeInitializationException: The type initializer for 'PerTypeValues1' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object. at System.SpanHelpers.PerTypeValues1.MeasureArrayAdjustment()
at System.SpanHelpers.PerTypeValues1.. cctor() --- End of inner exception stack trace --- at System.SpanHelpers.IsReferenceOrContainsReferences[T]() at System.Diagnostics.ActivityTraceId.CreateRandom() at System.Diagnostics.Activity.GenerateW3CId() at System.Diagnostics.Activity.Start() at Microsoft.ApplicationInsights.TelemetryClientExtensions.<>c__DisplayClass3_01.b__0()
at Microsoft.ApplicationInsights.ActivityExtensions.TryRun(Action action)
at Microsoft.ApplicationInsights.TelemetryClientExtensions.StartOperation[T](TelemetryClient telemetryClient, T operationTelemetry)

This has only started happening on recent builds of our software, going back to earlier builds of our product gets rid of the error. The two significant changes between those builds are our application assemblies changed from targeting .Net 4.5 to .Net 4.8, and the app insights SDK and dependencies were all upgraded (to 2.17 of App Insights, and the dependency that came with that except for System.Diagnostics.DiagnosticsSource which has been updated to 5.0.0.1).

**Configuration**
.Net 4.8
Windows 10
x86 .Net WinForms executable
Do not believe this is specific to this configuration, but uncertain.

https://github.com/dotnet/runtime/issues/52875

---
#### Feedback Bot on 5/18/2021, 07:17 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jkotas** [comment] 2021-05-19 23:14
Duplicate of https://github.com/dotnet/runtime/issues/52875. This is .NET Framework runtime crash. It is non-actionable in dotnet/runtime repo.

**Closed** 2021-05-19 23:17 UTC
Labels: untriaged
