### ISSUE TITLE
NullRef in System.Text.Json.Serialization.Tests.NumberHandlingTests.UnsupportedFormats (Linux_musl x64 Debug)

### ISSUE THREAD

**Issue by trylek** [dotnet/runtime#46106] opened 2020-12-16 00:44 UTC
OS: **Linux_musl**
Architecture: **x64**
Configuration: **checked** CoreCLR, **debug** test build
Example run: https://dev.azure.com/dnceng/public/_build/results?buildId=922427
(my PR run for a completely unrelated change fixing a few bugs in R2RDump)

<pre>
  Discovering: System.Text.Json.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Text.Json.Tests (found 2250 of 2294 test cases)
  Starting:    System.Text.Json.Tests (parallel test collections = on, max threads = 2)
    System.Text.Json.Serialization.Tests.NumberHandlingTests.UnsupportedFormats [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.Text.Json.JsonException)
      Actual:   typeof(System.NullReferenceException): Object reference not set to an instance of an object.
      ---- System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs(447,0): at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs(516,0): at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type type)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs(533,0): at System.Text.Json.JsonSerializerOptions.GetOrAddClassForRootType(Type type)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/ReadStack.cs(84,0): at System.Text.Json.ReadStack.Initialize(Type type, JsonSerializerOptions options, Boolean supportContinuation)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Helpers.cs(19,0): at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs(194,0): at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 json, Type returnType, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs(49,0): at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/tests/Serialization/NumberHandlingTests.cs(978,0): at System.Text.Json.Serialization.Tests.NumberHandlingTests.<>c__DisplayClass48_0`1.<AssertUnsupportedFormatThrows>b__0()
        ----- Inner Stack Trace -----
        /_/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs(447,0): at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs(516,0): at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type type)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs(533,0): at System.Text.Json.JsonSerializerOptions.GetOrAddClassForRootType(Type type)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/ReadStack.cs(84,0): at System.Text.Json.ReadStack.Initialize(Type type, JsonSerializerOptions options, Boolean supportContinuation)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Helpers.cs(19,0): at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs(194,0): at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 json, Type returnType, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs(49,0): at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/tests/Serialization/NumberHandlingTests.cs(978,0): at System.Text.Json.Serialization.Tests.NumberHandlingTests.<>c__DisplayClass48_0`1.<AssertUnsupportedFormatThrows>b__0()
    System.Text.Json.Serialization.Tests.NumberHandlingTests.Number_AsRootType_RoundTrip [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs(447,0): at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs(516,0): at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type type)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializerOptions.cs(533,0): at System.Text.Json.JsonSerializerOptions.GetOrAddClassForRootType(Type type)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/ReadStack.cs(84,0): at System.Text.Json.ReadStack.Initialize(Type type, JsonSerializerOptions options, Boolean supportContinuation)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Helpers.cs(19,0): at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs(194,0): at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 json, Type returnType, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.String.cs(49,0): at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
        /_/src/libraries/System.Text.Json/tests/Serialization/NumberHandlingTests.cs(105,0): at System.Text.Json.Serialization.Tests.NumberHandlingTests.PerformAsRootTypeSerialization[T](T number, String jsonWithNumberAsNumber, String jsonWithNumberAsString)
        /_/src/libraries/System.Text.Json/tests/Serialization/NumberHandlingTests.cs(85,0): at System.Text.Json.Serialization.Tests.NumberHandlingTests.RunAsRootTypeTest[T](List`1 numbers)
        /_/src/libraries/System.Text.Json/tests/Serialization/NumberHandlingTests.cs(67,0): at System.Text.Json.Serialization.Tests.NumberHandlingTests.Number_AsRootType_RoundTrip()

Assert failure(PID 22 [0x00000016], Thread: 41 [0x0029]): m_alignpad == 0
    File: /__w/1/s/src/coreclr/vm/syncblk.cpp Line: 2966
    Image: /root/helix/work/correlation/dotnet
</pre>

Not sure if the final assertion failure is meaningful or if it's just a side effect of the primary nullref.

**Comment by jkotas** [comment] 2020-12-16 01:23
This is very likely duplicate of https://github.com/dotnet/runtime/issues/46100

**Closed by jkotas** 2020-12-16 01:23 UTC
Labels: area-System.Text.Json, untriaged

**Comment by steveharter** [comment] 2021-02-24 20:27
A status recap:

From the info above a `NullReferenceException` is coming from `ConcurrentDictionary<Type, JsonClassInfo>.TryGetValue` and the test is using a shared\static `JsonSerializerOptions` which contains that dictionary and is likely being accessed from other concurrent tests. Although multiple threads are expected to work fine here with the static ConcurrentDictionary, it is possible the issue is related to having multiple threads.

We also have crashes\dumps elsewhere in STJ which may or may not be related to this. 

Currently this PR and these other crashes only occur on non-windows platforms (Linux_musl and OSX release).
