### ISSUE TITLE
wasm AOT library test failure - ArgumentNull_Generic Arg_ParamName_Name, type

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#46709] opened 2021-01-07 21:44 UTC
In effort to run library tests with AOT compilation on CI https://github.com/dotnet/runtime/issues/46633, there are a number of failures arising from https://github.com/dotnet/runtime/pull/46651.

Test suite `Microsoft.Bcl.AsyncInterfaces.Tests.csproj` fails with 
```
System.ArgumentNullException : ArgumentNull_Generic Arg_ParamName_Name, type
```
[AsyncInterfaces.txt](https://github.com/dotnet/runtime/files/5784089/AsyncInterfaces.txt)

Repro:
Check out changes in https://github.com/dotnet/runtime/pull/46651
`./build.sh -os Browser -arch wasm -c Release`
Remove https://github.com/dotnet/runtime/blob/f7f50465ee2c23f8a59753027af4f84b73737f52/eng/testing/ILLink.Descriptor.xunit.xml#L15-L20
Modify https://github.com/dotnet/runtime/blob/9538bee0fc1fb24993217071e954d9597385485f/src/libraries/System.Private.CoreLib/src/System/IO/FileStream.Unix.cs#L256  to be an empty catch
```
catch
{
}
```
`./dotnet.sh build /t:Test /p:TargetOS=Browser /p:TargetArchitecture=wasm /p:Configuration=Release /p:EnableAggressiveTrimming=true /p:RunAOTCompilation=true src/libraries/Microsoft.Bcl.AsyncInterfaces/tests/Microsoft.Bcl.AsyncInterfaces.Tests.csproj`

**Comment by radical** [comment] 2021-01-12 20:02
I'm not able to reproduce this. I get:

```
  info: 14:28:15.4973850 v8 --expose_wasm --stack-trace-limit=1000 runtime.js -- --run WasmTestRunner.dll Microsoft.Bcl.AsyncInterfaces.Tests.dll -notrait category=OuterLoop -notrait category=failing

  info: Arguments: --run,WasmTestRunner.dll,Microsoft.Bcl.AsyncInterfaces.Tests.dll,-notrait,category=OuterLoop,-notrait,category=failing
  info: console.debug: MONO_WASM: Initializing mono runtime
  info: console.debug: MONO_WASM: ICU data archive(s) loaded, disabling invariant mode
  info: console.debug: mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
  info: Initializing.....
  info: Discovering: Microsoft.Bcl.AsyncInterfaces.Tests.dll (method display = ClassAndMethod, method display options = None)
  info: Discovered:  Microsoft.Bcl.AsyncInterfaces.Tests.dll (found 18 of 18 test cases)
  info: Starting:    Microsoft.Bcl.AsyncInterfaces.Tests.dll
  info: Finished:    Microsoft.Bcl.AsyncInterfaces.Tests.dll
  info:
  info: === TEST EXECUTION SUMMARY ===
  info: Total: 18, Errors: 0, Failed: 0, Skipped: 0, Time: 0.250562s
  info:
  info: 14:28:17.0556170 Process v8 exited with 0

  info: Application has finished with exit code: 0
  XHarness exit code: 0
  XHarness artifacts: /Users/radical/dev/r2/artifacts/bin/Microsoft.Bcl.AsyncInterfaces.Tests/net6.0-Release/browser-wasm/AppBundle/xharness-output
```

According to #46651, [System.Private.Xml.Linq/tests/Schema/System.Xml.Schema.Extensions.Tests.csproj](https://github.com/dotnet/runtime/pull/46651/files#diff-5ef2fd16f58de91bff2f05ad601ab6ff000c0febabb2312d232f20cfa132a71bR187) also should have the same error, but I can't reproduce it for that either.

```
  XHarness command issued: wasm test --app=. --engine=V8 --engine-arg=--stack-trace-limit=1000 --js-file=runtime.js --output-directory=/Users/radical/dev/r2/artifacts/bin/System.Xml.Schema.Extensions.Tests/net6.0-Release/browser-wasm/AppBundle/xharness-output -- --run WasmTestRunner.dll System.Xml.Schema.Extensions.Tests.dll -notrait category=OuterLoop -notrait category=failing


  info: 15:00:18.7187700 v8 --expose_wasm --stack-trace-limit=1000 runtime.js -- --run WasmTestRunner.dll System.Xml.Schema.Extensions.Tests.dll -notrait category=OuterLoop -notrait category=failing

  info: Arguments: --run,WasmTestRunner.dll,System.Xml.Schema.Extensions.Tests.dll,-notrait,category=OuterLoop,-notrait,category=failing
  info: console.debug: MONO_WASM: Initializing mono runtime
  info: console.debug: MONO_WASM: ICU data archive(s) loaded, disabling invariant mode
  info: console.debug: mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
  info: Initializing.....
  info: Discovering: System.Xml.Schema.Extensions.Tests.dll (method display = ClassAndMethod, method display options = None)
  info: Discovered:  System.Xml.Schema.Extensions.Tests.dll (found 13 of 13 test cases)
  info: Starting:    System.Xml.Schema.Extensions.Tests.dll
  info: Finished:    System.Xml.Schema.Extensions.Tests.dll
  info:
  info: === TEST EXECUTION SUMMARY ===
  info: Total: 13, Errors: 0, Failed: 0, Skipped: 0, Time: 0.185409s
  info:
  info: 15:00:20.1515530 Process v8 exited with 0

  info: Application has finished with exit code: 0
  XHarness exit code: 0
  XHarness artifacts: /Users/radical/dev/r2/artifacts/bin/System.Xml.Schema.Extensions.Tests/net6.0-Release/browser-wasm/AppBundle/xharness-output
```

**Comment by radical** [comment] 2021-06-24 21:51
Closing this, as this predates the newer set of aot test issues that are tracked with `wasm-aot-test` label.

**Closed by radical** 2021-06-24 21:51 UTC
Labels: arch-wasm, area-Infrastructure-libraries
