### ISSUE TITLE
[wasm][aot][tests] System.Threading.Tasks.Tests failures

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#50968] opened 2021-04-08 20:59 UTC
This can be reproduced on `main`.

[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-76d6323478354200b5/System.Threading.Tasks.Tests/console.e6127e9f.log?sv=2019-07-07&se=2021-04-27T19%3A10%3A01Z&sr=c&sp=rl&sig=sD%2BRBEufPbrlRruQFK0D%2FkcngP%2Bdu6qiZlchrTM%2Fu10%3D)

```
[19:53:49] info: Starting:    System.Threading.Tasks.Tests.dll
[19:53:50] fail: [FAIL] System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests.TaskMethodBuilder_ValidateFaultedTask
[19:53:50] info: Assert.NotNull() Failure
[19:53:50] info: 
[19:53:50] fail: [FAIL] System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests.TrackedSyncContext_ValidateException
[19:53:50] info: Assert.NotNull() Failure
[19:53:50] info: 
[19:53:50] fail: [FAIL] System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests.TaskMethodBuilderT_ValidateFaultedTask
[19:53:50] info: Assert.NotNull() Failure
[19:53:50] info: 
[19:53:50] fail: [FAIL] System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests.Tcs_ValidateFaultedTask
[19:53:50] info: Assert.NotNull() Failure
[19:53:50] info: 
[19:53:50] info: Finished:    System.Threading.Tasks.Tests.dll
```

**Comment by vargaz** [comment] 2021-05-06 13:09
Caused by missing stacktrace support, i.e. this assert fails:
```
       private static void ValidateException(Exception e)
        {
            Assert.NotNull(e);
            Assert.NotNull(e.StackTrace);
            Assert.Matches(@"---.+---", e.StackTrace);
        }
```

**Comment by lewing** [comment] 2021-05-08 21:49
closing in favor of https://github.com/dotnet/runtime/issues/50957

**Closed by lewing** 2021-05-08 21:49 UTC
Labels: arch-wasm, area-Codegen-AOT-mono, wasm-aot-test
