### ISSUE TITLE
System.Text.Json Source Generator throws "CS0306: Type“ReadOnlySpan<byte> cannot be used as type argument" on certain class due to unknown reason

### ISSUE THREAD

**Issue by xiaoyuvax** [dotnet/runtime#96540] opened 2024-01-05 11:12 UTC
### Description

in .csproj:
`	<TargetFrameworks>net7.0;net8.0</TargetFrameworks>  `
output:
> 6>D:\_t\TestJson\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\GlobalJsonSourceGenerationContext.ReadOnlySpanByte.g.cs(13,129,13,146): error CS0306: Type “ReadOnlySpan<byte>”  cannot be used as type argument.
> 6>D:\_t\TestJson\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\GlobalJsonSourceGenerationContext.ReadOnlySpanByte.g.cs(22,128,22,151): error CS0306: Type“ReadOnlySpan<byte>”  cannot be used as type argument
> 6>D:\_t\TestJson\System.Text.Json.SourceGeneration\System.Text.Json.SourceGeneration.JsonSourceGenerator\GlobalJsonSourceGenerationContext.ReadOnlySpanByte.g.cs(17,127,17,143): error CS0306: Type“ReadOnlySpan<byte>”  cannot be used as type argument
> 6>TestJson -> D:\_t\TestJson\bin\Debug\net8.0\TestJson.dll
### Reproduction Steps

in .csproj:
```
<PropertyGroup>
	<TargetFrameworks>net7.0;net8.0</TargetFrameworks>
</PropertyGroup>
```

in code:
```
   [JsonSourceGenerationOptions(WriteIndented = false)]
   [JsonSerializable(typeof(MyType))] 
   public partial class GlobalJsonSourceGenerationContext : JsonSerializerContext
   {
   }
```

when build would throw errors on certain class, but i can't determine the exact cause in such class.
even when the code files isolated, such as copied to a new solution with dependency given, the problem doesn't reproduce. Weird!

### Other information

1) not all class throws this error, i have only one class causes this problem, but not reproduce if the class is copied into a new solution, with dependency served by ways of copying all depdent code files into the solution or reference built .dll.
2) no ReadOnlySpan used in that class at all.

**Comment by eiriktsarpalis** [comment] 2024-01-08 15:46
I suspect that this is a bug in .NET 7 that got fixed in .NET 8 which should explain the behavior you're seeing. To be sure though, would it be possible to share the definition of `MyType`?

**Comment by xiaoyuvax** [comment] 2024-01-15 04:32
By gradually removing codes from the affected class, it turns out to be this protected member leading to this problem, and what's even more weird is no matter it's protected or private or  [JsonIgnore] , compile errors all appear.
IMqttClient is the interface from dotnet/Mqtt.net (https://github.com/dotnet/MQTTnet) , that i can't dig deep into.
and i've also tested this in an independent project, and it reproduces.

```
   public class MockClass
   {
       protected IMqttClient client = null;
   }
```

**Comment by xiaoyuvax** [comment] 2024-01-15 06:44
By the same methodology,  i discovered another code structure which causes throwing some other exceptions including:

CS0534	“GlobalJsonSourceGenerationContext” does not implement inherited abstract member “JsonSerializerContext.GetTypeInfo(Type)” 	
CS7036	There is no argument given that corresponds to the required parameter “options” by “JsonSerializerContext.JsonSerializerContext(JsonSerializerOptions?)”

```
 public class ClassA
 {
 }

  public partial class MockClassBase
  {
      
      [System.Text.Json.Serialization.JsonIgnore]                             // replace [JsonIgnore] here will pass
      public virtual ClassA ServerContext { get; set; }
  }

 public sealed partial class MockClass : MockClassBase
 {
     [System.Text.Json.Serialization.JsonIgnore]                             //  replace [JsonIgnore] here will pass
     public new ClassA ServerContext { get; set; }                         // replace the "new" keyword with "override" will pass
 }

 [JsonSourceGenerationOptions(WriteIndented = false)]
 [JsonSerializable(typeof(MockClass))] 
 public partial class GlobalJsonSourceGenerationContext : JsonSerializerContext
 {
 }
```

**Comment by eiriktsarpalis** [comment] 2024-01-15 08:43
Yes, it's clearly a duplicate of the class of bugs addressed in https://github.com/dotnet/runtime/pull/87136. We won't be able to backport this fix to .NET 7, my recommendation is to reference the `8.0.0` System.Text.Json NuGet package in your `net7.0` target which should result in the newer source generator being used.

**Closed by eiriktsarpalis** 2024-01-15 08:43 UTC
Labels: area-System.Text.Json, untriaged
