### ISSUE TITLE
[NativeAOT] IndexOutOfRangeException when running under perfview

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#75945] opened 2022-09-21 02:52 UTC
Stacktrace:
```
---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
System.Diagnostic.Tracing.EventSource.WriteEventWithRelatedActivityIdCore
System.Diagnostic.Tracing.EventSource.WriteEvent
System.Diagnostic.DiagnosticSourceEventSource.FilterAndTransform
System.Diagnostic.DiagnostisListener.AllListenerObservable.OnNewDiagnosticListener
System.Diagnostic.Listener..ctor
System.Net.DiagnosticHandler..ctor
System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun
```

Repro: https://github.com/kshyju/Net7IsolatedHttpApp

**Comment by jkotas** [comment] 2022-09-21 02:58
cc @noahfalk @brianrob

**Comment by tommcdon** [comment] 2022-09-21 05:30
adding @vitek-karas 
@jkotas  do you know if this issue reproduces with a .net core trimmed app?  I'm curious if this is a trimming safety issue, or if it is NativeAOT specific.

**Comment by jkotas** [comment] 2022-09-22 03:06
There are multiple issues actually, some are native AOT specific and some apply to trimmed apps in general.

**Comment by eerhardt** [comment] 2022-09-23 00:01
FYI - I've been hacking on DiagnosticSource to make it work with NativeAOT. I've got a change working with PerfView locally - https://github.com/eerhardt/runtime/commit/5f276797dc78366fc8c3bf69489921551d86269d.

I just need to figure out a way to test it now, so we can ensure it stays fixed.

**Comment by tommcdon** [comment] 2022-09-23 02:31
@eerhardt is it OK if I assign this issue to you since you are working on a fix?

**Closed** 2022-09-28 21:30 UTC
Labels: area-System.Diagnostics.Tracing, in-pr
