### ISSUE TITLE
System.Text.Json.JsonSerializerOptions.PropertyNameCaseInsensitive does not apply to JsonPolymorphismOptions.TypeDiscriminatorPropertyName

### ISSUE THREAD

**Issue by aremes** [dotnet/runtime#86028] opened 2023-05-10 08:25 UTC
### Description

When serializing from different classes using JsonPolymorphismOptions, I assumed it would make sense to make the casing of my type discriminator match the casing of all properties. Easy enough to do. There's a caveat though: JsonSerializerOptions.PropertyNamingPolicy *must* be the same for serialization and deserialization.

In cases where I don't know what casing was used during serialization, i could usually just set JsonSerializerOptions.PropertyNameCaseInsensitive to true. But this setting seems to be ignored when the deserializer looks for the discriminator, for some reason.

Is there a rationale behind this?

### Reproduction Steps

```c#
using System.Text.Json;
using System.Text.Json.Serialization.Metadata;

namespace DiscriminatorCasing
{
	abstract class Base { }

	class Derived1 : Base { }

	class Derived2 : Base { }

	class BaseTypeResolver : IJsonTypeInfoResolver
	{
		public JsonTypeInfo? GetTypeInfo(Type type, JsonSerializerOptions options)
		{
			if (type == typeof(Base))
			{
				var ti = JsonTypeInfo.CreateJsonTypeInfo(typeof(Base), options);
				ti.PolymorphismOptions = new()
				{
					TypeDiscriminatorPropertyName = 
						/* I thought this would have made sense: */
						options.PropertyNamingPolicy?.ConvertName("Type") ?? "Type"
				};

				ti.PolymorphismOptions.DerivedTypes.Add(new(typeof(Derived1), 1));
				ti.PolymorphismOptions.DerivedTypes.Add(new(typeof(Derived2), 2));
				return ti;
			}
			return null;
		}
	}
	internal class Program
	{
		static void Main(string[] args)
		{
			var serializationOptions = new JsonSerializerOptions();
			serializationOptions.TypeInfoResolver = JsonTypeInfoResolver.Combine(
				new BaseTypeResolver(),
				new DefaultJsonTypeInfoResolver()
			);

			serializationOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;

			var derived1 = new Derived1();

			var serialized = JsonSerializer.Serialize<Base>(derived1, serializationOptions);
			//{"type":1}

			var deserializationOptions = new JsonSerializerOptions();
			deserializationOptions.TypeInfoResolver = JsonTypeInfoResolver.Combine(
				new BaseTypeResolver(),
				new DefaultJsonTypeInfoResolver()
			);

			deserializationOptions.PropertyNameCaseInsensitive = true; //Why doesnt this have an effect?

			// Throws: System.NotSupportedException: 'Deserialization of types without a parameterless constructor,
			// a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute'
			// is not supported.
			// (Because it expects "Type" discriminator. PropertyNameCaseInsensitive is ignored.)
			var deserialized = JsonSerializer.Deserialize<Base>(serialized, deserializationOptions);
		}
	}
}
```

### Expected behavior

It should correctly deserialize to `Derived1` when `deserializationOptions.PropertyNameCaseInsensitive` is set to true.

### Actual behavior

It throws a System.NotSupportedException because it expects a "Type" discriminator, but the serializer contains a "type" discriminator.

### Regression?

Not that i'm aware of

### Known Workarounds

* Make sure JsonSerializerOptions.PropertyNamingPolicy is the same for both serialization or deserialization
* Dont adjust type discriminator casing, hard-code the name to something.

### Configuration

.NET 7, Windows 10, Visual Studio 2022. Should not be specific to OS/Architecture, though

**Comment by eiriktsarpalis** [comment] 2023-05-10 14:02
Duplicate of #75269.

**Closed by eiriktsarpalis** 2023-05-10 14:02 UTC
Labels: area-System.Text.Json, untriaged

**Comment by aremes** [comment] 2023-05-11 06:37
Feeling stupid now :) Thanks, @eiriktsarpalis!

**Comment by eiriktsarpalis** [comment] 2023-05-11 12:58
Nothing stupid about discovering bugs :-)
