### ISSUE TITLE
I'm getting System.MissingMethodException when using netstandard2.0 project from net8.0

### ISSUE THREAD

**Issue by astryia** [dotnet/runtime#96197] opened 2023-12-19 18:03 UTC
### Description

I have netstandard2.0 project which is wrapper around StackExchange.Redis nuget package which also targets netstandard2.0. I have net8.0 console application which is using netstandard2.0.
I'm getting runtime error:
```
"Method not found: 'Void StackExchange.Redis.ConfigurationOptions.set_EndPoints(StackExchange.Redis.EndPointCollection)'."}
    ClassName: null
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146233069
    HasBeenThrown: true
    HelpLink: null
    InnerException: null
    MemberName: null
    Message: "Method not found: 'Void StackExchange.Redis.ConfigurationOptions.set_EndPoints(StackExchange.Redis.EndPointCollection)'."
    SerializationStackTraceString: "   at CacheWrapper.CacheWrapper.BuildConfigurationOptions()\r\n   at CacheWrapper.CacheWrapper..ctor() in CacheWrapper.cs:line 11\r\n   at Program.<Main>$(String[] args) in Program.cs:line 3"
    SerializationWatsonBuckets: null
    Signature: null
    Source: "CacheWrapper"
```

I understand that the problem is in StackExchange.Redis nuget package which uses **init only setters** in netstandard version of the library.
Is it any way I can identify such situations at compile time?

### Reproduction Steps

CacheWrapper.csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" Version="2.7.10" />
  </ItemGroup>

</Project>
```
CacheWrapper.cs
```
using StackExchange.Redis;

namespace CacheWrapper
{
    public class CacheWrapper
    {
        private readonly ConfigurationOptions _options;

        public CacheWrapper()
        {
            _options = BuildConfigurationOptions();
        }

        public IDatabase Connect()
        {
            var connectionMultiplexer = ConnectionMultiplexer.Connect(_options);
            return connectionMultiplexer.GetDatabase();
        }

        internal ConfigurationOptions BuildConfigurationOptions()
        {
            var endPoints = new EndPointCollection { { "127.0.0.1", 11111 } };

            return
                new ConfigurationOptions
                {
                    AbortOnConnectFail = false,
                    EndPoints = endPoints,
                    SyncTimeout = 30000
                };
        }
    }
}
```
CacheUser.csproj
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CacheWrapper\CacheWrapper.csproj" />
  </ItemGroup>

</Project>
```
Program.cs
```
var cache = new CacheWrapper.CacheWrapper();
```

### Expected behavior

Works with no error or signature mismatch compilation error.

### Actual behavior

System.MissingMethodException

### Regression?

Works with no errors under net48.

### Known Workarounds

Add net8.0 target to CacheWrapper.csproj
```
<TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
```

### Other information

IL code difference
net8.0
```
    IL_0025: dup
    IL_0026: ldloc.0      // endPoints
    IL_0027: callvirt     instance void modreq ([System.Runtime]System.Runtime.CompilerServices.IsExternalInit) [StackExchange.Redis]StackExchange.Redis.ConfigurationOptions::set_EndPoints(class [StackExchange.Redis]StackExchange.Redis.EndPointCollection)
    IL_002c: nop
```
netstandard2.0
```
    IL_0025: dup
    IL_0026: ldloc.0      // endPoints
    IL_0027: callvirt     instance void modreq ([StackExchange.Redis]System.Runtime.CompilerServices.IsExternalInit) [StackExchange.Redis]StackExchange.Redis.ConfigurationOptions::set_EndPoints(class [StackExchange.Redis]StackExchange.Redis.EndPointCollection)
    IL_002c: nop
```

**Comment by jkotas** [comment] 2023-12-19 23:38
https://github.com/dotnet/runtime/issues/79082#issuecomment-1333716389 describes the problem and the solution. This needs to be fixed in the StackExchange.Redis nuget package. Please open an issue in StackExchange.Redis nuget package repo.

**Closed by jkotas** 2023-12-19 23:38 UTC
Labels: untriaged, needs-area-label

**Comment by astryia** [comment] 2023-12-19 23:47
@jkotas, is it any way I can get compiler warning or something for this type of situation? For me it pretty obvious method signature mismatch, why it can only be discovered at runtime?

**Comment by MichalPetryka** [comment] 2023-12-19 23:58
> compiler warning

The issue is that when targetting .Net Standard, you build against a .Net Standard version of the library which doesn't match up with the runtime specific one.

> why it can only be discovered at runtime?

The runtime checks for such errors lazily, when importing the target method.

If you want to verify it beforehand, you have to use the `ilverify` commandline tool that can check assemblies for validity.
(and the target library should contain a `TypeForwardedTo` attribute in the runtime specific version to fix this)

**Comment by jkotas** [comment] 2023-12-20 02:59
> @jkotas, is it any way I can get compiler warning or something for this type of situation? 

By default, the compiler will produce error if you try to use new language features when targeting older runtimes or netstandard2.0. The problem is that people suppress this error and invent creative workarounds to use some new C# language features on older runtimes or netstandard2.0. It comes with a lot of gotchas, like the issue you have run into.

**Comment by MichalPetryka** [comment] 2023-12-20 03:04
> > @jkotas, is it any way I can get compiler warning or something for this type of situation? 
> 
> By default, the compiler will produce error if you try to use new language features when targeting older runtimes or netstandard2.0. The problem is that people suppress this error and invent creative workarounds to use some new C# language features on older runtimes or netstandard2.0. It comes with a lot of gotchas, like the issue you have run into.

Worth noting that using newer language versions on older runtimes is also technically not officially supported.

**Comment by huoyaoyuan** [comment] 2023-12-20 03:37
I remember there is an analyzer proposal for analyzing compatibility of versions and TFMs of nuget packages. Is it public?

**Comment by WeihanLi** [comment] 2023-12-20 03:59
> I remember there is an analyzer proposal for analyzing compatibility of versions and TFMs of nuget packages. Is it public?

The NuGet package validation?
https://learn.microsoft.com/en-us/dotnet/fundamentals/apicompat/package-validation/overview

**Comment by astryia** [comment] 2023-12-20 04:46
Thank you all for detailed explanations. 

> The NuGet package validation?
> https://learn.microsoft.com/en-us/dotnet/fundamentals/apicompat/package-validation/overview

From what I understand this validation can be used by package authors. As the package consumer, I have to rely on them or incorporate ilverify into my build process.

**Comment by WeihanLi** [comment] 2023-12-20 05:51
Yeah, think it's mainly for package authors, we could verify the changes via the `apicompat` dotnet tool if we want

https://learn.microsoft.com/en-us/dotnet/fundamentals/apicompat/global-tool

**Comment by mgravell** [comment] 2023-12-20 11:24
crossso the rabbit hole got a bit deeper: https://github.com/dotnet/roslyn-analyzers/issues/7110 /cc @jkotas
