### ISSUE TITLE
Segmentation fault when using globalization and entity framework on alpine 3.16

### ISSUE THREAD

**Issue by yulivee** [dotnet/runtime#77596] opened 2022-10-28 09:56 UTC
1. Use EntityFramework in .NET App
2. Install icu-libs
3. Set environment variables for globalization
```
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
ENV DOTNET_RUNNING_IN_CONTAINER=true
RUN apk add --no-cache icu-libs icu-data-full icu-dev 
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
```
4. Run the application

### Describe the Bug

The application immediately crashes with `Segmentation Fault`. 

### Steps to Reproduce

I have created a simple demonstrator for this issue here: `https://github.com/yulivee/alpineGlobalizationDemonstrator`, dockerfile and docker-compose included. Image can be built with `docker compose build`

Run the image with `docker run` and overwrite the entrypoint with /bin/sh. Executing `dotnet alpinetest.dll` produces the segmentation fault.

The image uses a non-root user to run, but running as root produces the same output.

### Other Information

Affected images: `FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine3.16`
Docker is running in WSL 2 on Windows 10.

Looking at strace output it seems to be related to security libraries. Unfortunately, I am not very skilled in reading strace. Full output is included in the referenced repository (straceOutput)
```
madvise(0x7f89b8cf1000, 4096, MADV_DODUMP) = 0
madvise(0x7f8a2729d000, 4096, MADV_FREE) = 0
mmap(NULL, 20480, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8a27f03000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8a28693000
munmap(0x7f8a28693000, 8192)            = 0
open("/usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.10/System.Net.Security.Native.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/app/System.Net.Security.Native.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/lib/System.Net.Security.Native.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/local/lib/System.Net.Security.Native.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/lib/System.Net.Security.Native.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.10/libSystem.Net.Security.Native.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 175
fcntl(175, F_SETFD, FD_CLOEXEC)         = 0
fstat(175, {st_mode=S_IFREG|0755, st_size=14352, ...}) = 0
read(175, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\360\20\0\0\0\0\0\0"..., 960) = 960
mmap(NULL, 20480, PROT_READ, MAP_PRIVATE, 175, 0) = 0x7f8a2721f000
mmap(0x7f8a27220000, 4096, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 175, 0x1000) = 0x7f8a27220000
mmap(0x7f8a27221000, 4096, PROT_READ, MAP_PRIVATE|MAP_FIXED, 175, 0x2000) = 0x7f8a27221000
mmap(0x7f8a27222000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 175, 0x2000) = 0x7f8a27222000
close(175)                              = 0
mprotect(0x7f8a27222000, 4096, PROT_READ) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
rt_sigprocmask(SIG_UNBLOCK, [RT_3], NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [SEGV], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [RT_3], NULL, 8) = 0
rt_sigaction(SIGSEGV, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f8a2e22dc9f}, NULL, 8) = 0
unlink("/tmp/clr-debug-pipe-38-135814-in") = 0
unlink("/tmp/clr-debug-pipe-38-135814-out") = 0
unlink("/tmp/dotnet-diagnostic-38-135814-socket") = 0
rt_sigreturn({mask=[]})                 = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
+++ killed by SIGSEGV +++
Segmentation fault
```

I have considered running on `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true` and skipping the whole globalization mess, but unfortunately, that just keeps producing the following exception: 
```
/app # DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
/app # dotnet alpinetest.dll
Unhandled exception. System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
en-us is an invalid culture identifier.
   at System.Globalization.CultureInfo.GetCultureInfo(String name)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternal(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass18_0.<Exists>b__0(DateTime giveUp)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation, Func`2 verifySucceeded)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists(Boolean retryOnNotExists)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at Program.<Main>$(String[] args) in /build/Program.cs:line 19
Aborted (core dumped)
```

so for now, I have not found a way to run an ASP.NET Core App using EntityFramework in an alpine container. Can someone please advise on this?

### Output of `docker version`

```
Client: Docker Engine - Community
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:47:57 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:45:46 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Output of `docker info`
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)

Server:
 Containers: 20
  Running: 9
  Paused: 0
  Stopped: 11
 Images: 487
 Server Version: 20.10.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc version: v1.0.3-0-gf46b6ba
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.102.1-microsoft-standard-WSL2
 Operating System: Ubuntu 18.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 24.83GiB
 Name: TPSSCHUHMA-2
 ID: ZYFO:EKVT:T2H2:IATZ:ZDTU:2B55:CEDM:OJHU:N7R6:6XTV:CE3G:UAIP
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by jkotas** [comment] 2022-10-28 15:36
```
Thread 1 "dotnet" received signal SIGSEGV, Segmentation fault.
0x00007f5b4c79744c in NetSecurityNative_ImportPrincipalName () from /usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.10/libSystem.Net.Security.Native.so
(gdb) bt
#0  0x00007f5b4c79744c in NetSecurityNative_ImportPrincipalName ()
   from /usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.10/libSystem.Net.Security.Native.so
```

This is duplicate of https://github.com/dotnet/runtime/issues/60906. 

Update to the latest servicing update of Microsoft.Data.SqlClient by adding `<PackageReference Include="Microsoft.Data.SqlClient" Version="2.1.5" />` to your .csproj; or to latest major version by adding `<PackageReference Include="Microsoft.Data.SqlClient" Version="5.0.1" />`.

**Closed by jkotas** 2022-10-28 15:36 UTC
Labels: bug, area-System.Data.SqlClient, untriaged
