### ISSUE TITLE
Add Range support for List

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/runtime#48735] opened 2021-02-25 01:40 UTC
## Background and Motivation

Since C# 8, we had support for `Index` and `Range`, but the `Range` is only support for `Array`, so I'm wondering that if there's 
any need for `Range` support for `List`

## Proposed API

```diff
namespace System.Collections.Generic
{
     public class List<T> : IList<T>, IList, IReadOnlyList<T> {
+        public T[] this[Range range] { get; }
     }
}
```

## Usage Examples

``` C#
var list = Enumerable.Range(1, 10).ToList();
var subArray = list[2..^2];
```

## Alternative Designs

Since we could add support for `Range` Implicitly, we could also add a `T[] Slice(int start, int count)` method without implement `Range` indexer

## Possible implement

1. `Range` indexer

``` c#
T[] this[Range range] => RuntimeHelpers.GetSubArray(_items, range);
```

2. `Slice` method

``` c#
public T[] Slice(int start, int count)
{
    var array = new T[count];
    Array.Copy(_items, array, start, count);
    return array;
}
```

**Comment by eiriktsarpalis** [comment] 2021-02-25 15:10
Hi @WeihanLi, this is a duplicate of #321, feel free to contribute to the conversation there. I'm going to close this issue.

**Closed by eiriktsarpalis** 2021-02-25 15:10 UTC
Labels: api-suggestion, area-System.Collections, untriaged
