### ISSUE TITLE
Test failure: readytorun\crossgen2\crossgen2smoke\crossgen2smoke.cmd

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/runtime#38482] opened 2020-06-27 03:13 UTC
https://dev.azure.com/dnceng/public/_build/results?buildId=705744&view=ms.vss-test-web.build-test-results-tab&runId=21861154&resultId=109360&paneView=debug

The above link is for a failure in a manually scheduled run of gcstress0x3-gcstress0xc pipeline for a PR but I was able to get a local repro on master @ f1bf0defd31da8f60dc33a63071a8e00b036e300

The failure is non-deterministic, it took me 7 tries to get a repro.

Windows x64

```
set COMPlus_TieredCompilation=0
set COMPlus_GCStress=0xC
```

```
readytorun\crossgen2\crossgen2smoke\crossgen2smoke.cmd [FAIL]
      
      Assert failure(PID 656 [0x00000290], Thread: 3904 [0x0f40]): Consistency check failed: AV in clr at this callstack:
      ------
      CORECLR! memcmp + 0x12 (0x00007ffc`56c51532)
      CORECLR! Thread::VirtualUnwindCallFrame + 0x340 (0x00007ffc`56568608)
      CORECLR! EECodeManager::EnsureCallerContextIsValid + 0x1C3 (0x00007ffc`568a8bdb)
      CORECLR! StackFrameIterator::CheckForSkippedFrames + 0x72 (0x00007ffc`5656323e)
      CORECLR! StackFrameIterator::ProcessCurrentFrame + 0x178 (0x00007ffc`565675c8)
      CORECLR! StackFrameIterator::Init + 0x1E5 (0x00007ffc`56565659)
      CORECLR! Thread::StackWalkFramesEx + 0x12E (0x00007ffc`56567fae)
      CORECLR! Thread::HandledJITCase + 0x234 (0x00007ffc`565b6eec)
      CORECLR! ThreadSuspend::SuspendRuntime + 0x421 (0x00007ffc`565bc349)
      CORECLR! ThreadSuspend::SuspendEE + 0x29B (0x00007ffc`565bbc4f)
      CORECLR! GCToEEInterface::SuspendEE + 0x48 (0x00007ffc`56b96a98)
      CORECLR! WKS::GCHeap::GarbageCollectGeneration + 0x249 (0x00007ffc`56b13c35)
      CORECLR! WKS::GCHeap::StressHeap + 0x4CA (0x00007ffc`56b16c4a)
      CORECLR! Thread::PerformPreemptiveGC + 0x31F (0x00007ffc`565b8a17)
      CORECLR! Thread::RareEnablePreemptiveGC + 0x11E (0x00007ffc`565b91d6)
      CORECLR! Thread::EnablePreemptiveGC + 0xF7 (0x00007ffc`564b3423)
      CORECLR! GCHolderBase::PopInternal<1> + 0x13F (0x00007ffc`564b02c3)
      CORECLR! GCCoop::~GCCoop + 0x9 (0x00007ffc`564b1159)
      CORECLR! MscorlibBinder::TriggerGCUnderStress + 0x1A3 (0x00007ffc`565eecdb)
      -----
      .AV on tid=0xf40 (3904), cxr=000000FCC1974F40, exr=000000FCC1975430
      FAILED: false
      
      CORECLR! CHECK::Trigger + 0x2C9 (0x00007ffc`56467d65)
      CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x2B2 (0x00007ffc`564c0306)
      CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x97 (0x00007ffc`564bfdc7)
      CORECLR! CLRVectoredExceptionHandler + 0x215 (0x00007ffc`564bfd0d)
      CORECLR! CLRVectoredExceptionHandlerShim + 0x1A0 (0x00007ffc`564c0580)
      NTDLL! RtlInitializeCriticalSection + 0x190 (0x00007ffc`85a45ef0)
      NTDLL! RtlImageNtHeaderEx + 0x17B (0x00007ffc`85a1fa7b)
      NTDLL! KiUserExceptionDispatcher + 0x3A (0x00007ffc`85a8964a)
      CORECLR! memcmp + 0x12 (0x00007ffc`56c51532)
      CORECLR! Thread::VirtualUnwindCallFrame + 0x340 (0x00007ffc`56568608)
          File: F:\workspace\_work\1\s\src\coreclr\src\vm\excep.cpp Line: 7494
          Image: C:\h\w\B7160A3B\p\CoreRun.exe
      
      
      Return code:      1
```

**Comment by BruceForstall** [comment] 2020-06-28 17:24
@dotnet/crossgen-contrib

**Comment by nattress** [comment] 2020-06-29 22:48
This looks like a duplicate of https://github.com/dotnet/runtime/issues/34316

**Closed** 2020-07-15 14:45 UTC
Labels: GCStress, area-crossgen2-coreclr
