### ISSUE TITLE
ToImmutableDictionary can add null as key

### ISSUE THREAD

**Issue by Bonuspunkt** [dotnet/runtime#56298] opened 2021-07-26 12:48 UTC
```csharp
new[]{"a", null}.ToImmutableDictionary(t => t, t => t); // works
new ImmutableDictionary<string, string>().Add("a", "a").Add(null,null); // throws ArgumentNullException
```

also there is no "nice way" to access the value when the key is null.

**Comment by eiriktsarpalis** [comment] 2021-07-26 14:36
Hi @Bonuspunkt, thanks for reporting this bug. It's a duplicate of #50865 and has already fixed in #51438.

**Closed by eiriktsarpalis** 2021-07-26 14:36 UTC
Labels: area-System.Collections, untriaged
