### ISSUE TITLE
Uri.TryCreate throwing NullReferenceException for two URL's without a slash

### ISSUE THREAD

**Issue by RPM1984** [dotnet/runtime#44364] opened 2020-10-29 04:18 UTC
Hi there 👋 

Came across a weird one. I saw [this](https://github.com/dotnet/runtime/issues/22871) issue, which points to something intermittent, but this is fully reproducible.

```
Uri.TryCreate("https://video1.com,https://video2.com", UriKind.Absolute, out Uri videoUri); // returns "https://video1.com/,https://video2.com/"
Uri.TryCreate("https://video1.com/,https://video2.com/", UriKind.Absolute, out Uri videoUri); // throws NullReferenceException
```

https://dotnetfiddle.net/dmEJh5

Any reason why the slashes in the second example throw an exception? Is there a more suitable method I should be using instead? I would expect both above lines to both succeed (or both fail).

**Comment by MihaZupan** [comment] 2020-11-07 09:53
Marking as a bug as we should never be throwing NRE.

**Comment by MCCshreyas** [comment] 2020-11-08 05:32
For me the first call is working, and second is throwing exception in dotnetfiddle. Can you please check on your side? @RPM1984

**Comment by RPM1984** [comment] 2020-11-08 05:42
@MCCshreyas correct. The 1st line is ok, I just put it there for an example. The second line is crashing, but shouldn't. The only difference is the trailing slash.

**Comment by MCCshreyas** [comment] 2020-11-08 07:11
@RPM1984 No, no. I mean the first URL without end / is not working for me, see below screenshot. 

![image](https://user-images.githubusercontent.com/17148381/98459305-a4114f00-21bf-11eb-97b5-acddff9f9bfd.png)

**Comment by RPM1984** [comment] 2020-11-09 00:07
@MCCshreyas sorry yes you're right, i had the comment/failing one the wrong way around 😊

**Comment by MihaZupan** [comment] 2020-11-09 08:43
Upon a closer look, I can't reproduce any issue here.

The `NullReferenceException` you're seeing here comes from the fact you're not checking the value returned from `TryCreate`. If it returns false, the `Uri` will be null.

The following example works as expected.
```c#
if (Uri.TryCreate("https://video1.com,https://video2.com", UriKind.Absolute, out Uri uri1))
    Console.WriteLine(uri1.AbsoluteUri);

if (Uri.TryCreate("https://video1.com/,https://video2.com/", UriKind.Absolute, out Uri uri2))
    Console.WriteLine(uri2.AbsoluteUri);
```

**Closed by MihaZupan** 2020-11-09 08:43 UTC
Labels: area-System.Net

**Comment by RPM1984** [comment] 2020-11-09 22:10
@MihaZupan you're right.. i feel dumb 😊 .

i think originally this stemmed from the fact the example without the slash _wasn't_ parsing, but with the slash it was. but then I (wrongly) saw it was throwing an exception.

so yes, issue can be closed -> and I think the confusion here is that the second example above **shouldn't** be successfully parsing -> it's not a valid URI? in other words, both examples should fail parsing.

**Comment by MihaZupan** [comment] 2020-11-10 11:30
> the second example above shouldn't be successfully parsing -> it's not a valid URI?

It's not pretty, but I don't see why it wouldn't be valid. It's an absolute Uri, so it can contain `,` and `:`.
