### ISSUE TITLE
System.Composition nuget packages have mixture of assembly versions and CHANGES public key token

### ISSUE THREAD

**Issue by AArnott** [dotnet/runtime#45638] opened 2020-12-05 15:26 UTC
The `System.Composition.*` nuget packages ship 4 assemblies with incoherent assembly versions:

netstandard1.0 and portable-net45+win8+wp8+wpa81 ship assembly version 1.0.33.0
netstandard2.0 and net461 ship assembly version 5.0.0.0

Why is this? I tend to expect corefx to ship a nuget package with a coherent sent of assembly versions.

**UPDATE: public key token changes too!**

Up through v1.4.1 versions of the packages, the public key token for these assemblies was `b03f5f7f11d50a3a`.
But in 5.0.0, the assemblies that actually experience an assembly version change also experience an public key token change to `cc7b13ffcd2ddd51`. This is **a breaking change for .NET Framework** and I suspect for .NET Core runtimes as well. Changing the public key token means the CLR will not bind references even with binding redirects.

This will break apps that are composed of assemblies that reference System.Composition 5.0 packages.

Surely the public key token change is a mistake. Please issue a servicing fix for this.

**Comment by danmosemsft** [comment] 2020-12-08 11:00
@ericstj @joperezr do we need to push another package promptly and delist this one?

**Comment by ViktorHofer** [comment] 2020-12-08 12:24
> Up through v1.4.1 versions of the packages, the public key token for these assemblies was b03f5f7f11d50a3a.

That is the Microsoft public key: https://github.com/dotnet/arcade/blob/4873d157a8f34f8cc7e28b3f9938b32c642ef542/src/Microsoft.DotNet.Arcade.Sdk/tools/StrongName.targets#L30.

> But in 5.0.0, the assemblies that actually experience an assembly version change also experience an public key token change to cc7b13ffcd2ddd51. 

That is the Open public key: https://github.com/dotnet/arcade/blob/4873d157a8f34f8cc7e28b3f9938b32c642ef542/src/Microsoft.DotNet.Arcade.Sdk/tools/StrongName.targets#L64.

This was intended to be fixed with https://github.com/dotnet/corefx/commit/18e82cabc1d2cddad8ff07ae96edb7296d9fad9d but likely regressed with https://github.com/dotnet/corefx/pull/41723/files#diff-739e1ffbaee417f430131875c0471f5ab63a11561f06de857adcd32f4eddce15L4 which removed the MSFT public key token.

cc @Anipik

**Comment by ViktorHofer** [comment] 2020-12-08 12:27
@danmosemsft we do have another case where we need to service packages which is https://github.com/dotnet/runtime/issues/45560. Depending on the date of the next servicing, we might want to service them together?

**Comment by ericstj** [comment] 2020-12-08 14:27
This same bug occurred in previous release
https://github.com/dotnet/runtime/issues/31221

Perhaps we should change the props files for these to match the pattern of the rest of the repo since this has happened multiple times.

**Comment by ViktorHofer** [comment] 2020-12-14 18:30
Fixed in both release/5.0 and master. The package will be updated with the next servicing release.

**Closed by ViktorHofer** 2020-12-14 18:30 UTC
Labels: area-System.Composition, regression-from-last-release
