### ISSUE TITLE
[Android] System.Text.Json MissingMethodException

### ISSUE THREAD

**Issue by matheussouza97** [dotnet/runtime#67782] opened 2022-04-08 21:55 UTC
### Description

MissingMethodException - Constructor on type 'System.Text.Json.Serialization.Converters.DictionaryOfTKeyTValueConverter`3[[System.Collections.Generic.Dictionary`2[[System.String, mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]' not found.

### Reproduction Steps

- Create a Xamarin-Android project
- Change the linker options to Link all assemblies
- Try Serialize a Dictionary like this:

```code
var payload = new Dictionary<string, object?>
{
    ["contentCheckOk"] = true,
};

JsonSerializer.Serialize(payload);
```
- Run the project.

### Expected behavior

get the serialization.

### Actual behavior

MissingMethodException - Constructor on type 'System.Text.Json.Serialization.Converters.DictionaryOfTKeyTValueConverter

### Known Workarounds

Add the System.Text.Json to ignore assemblies option.

**Comment by eiriktsarpalis** [comment] 2022-04-09 12:18
Could you please share a project that demonstrates the issue? Either a link to repo or a zip file might help. Thanks.

**Comment by matheussouza97** [comment] 2022-04-11 16:42
> Could you please share a project that demonstrates the issue? Either a link to repo or a zip file might help. Thanks.

yes, of course.
[SystemTextJsonError.zip](https://github.com/dotnet/runtime/files/8466143/SystemTextJsonError.zip)

**Comment by eiriktsarpalis** [comment] 2022-04-14 14:57
I see. Yeah, this is expected with trimming enabled when consuming reflection-based serialization APIs. A relevant warning should have been emitted by the linker. The recommended workaround is to use source generation which provides a linker-safe way to serialize:

```C#
var payload = new Dictionary<string, object?>
{
    ["contentCheckOk"] = true,
};

System.Console.WriteLine(JsonSerializer.Serialize(payload, MyContext.Default.DictionaryStringObject));

[JsonSerializable(typeof(Dictionary<string, object?>))]
[JsonSerializable(typeof(bool))] // need to explicitly opt in any types used as keys in the Dictionary
public partial class MyContext : JsonSerializerContext
{ 

}
```
Closing, since this is by design.

**Closed by eiriktsarpalis** 2022-04-14 14:57 UTC
Labels: area-System.Text.Json, needs-further-triage

**Comment by eerhardt** [comment] 2022-04-16 03:04
@matheussouza97 - what version of `System.Text.Json` and the linker are you using? Since you are using Xamarin-Android, I assume it is an old linker.

With the linker version in .NET 6, this no longer repros. 

We used to have `DynamicDependency` attributes that would preserve these internal ctors, but they were removed here: https://github.com/dotnet/runtime/pull/38595#discussion_r447833102 because the latest version of the linker understands the pattern intrinsically.

With .NET Maui this won't be a problem (since it uses the latest version of the linker).
