### ISSUE TITLE
Random.NextBytes is very slightly biased against 0xFF

### ISSUE THREAD

**Issue by Clockwork-Muse** [dotnet/runtime#41457] opened 2020-08-27 17:05 UTC
`NextBytes(byte[])` [is implemented like so](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/Random.cs#L237-L244):

```csharp
public virtual void NextBytes(byte[] buffer)
{
    if (buffer == null) throw new ArgumentNullException(nameof(buffer));
    for (int i = 0; i < buffer.Length; i++)
    {
        buffer[i] = (byte)InternalSample();
    }
}
```
(side note: why no `unchecked` on the cast...?)

The `Span<byte>` version has the same effective implementation if `Next()` has not been overridden.

The problem is that `InternalSample()` returns values in the range [`0`, `int.MaxValue`) - that is, `int.MaxValue` is not included.  This skews the distribution of possible values for bytes:
 - `0x00`-`0xFE` - 8388608 values
 - `0xFF` - 8388607 values

([Sample generation program](https://gist.github.com/Clockwork-Muse/0095f83bd2a76ac54a549c564f88c28c))

The catch is that I'm not sure that this is fixable, given that any fix for this would be a breaking change in the behavior, and we've been reluctant to do so for other parts of `Random`.

**Comment by GrabYourPitchforks** [comment] 2020-08-27 18:09
Possible dupe of https://github.com/dotnet/runtime/issues/23198.

**Comment by Clockwork-Muse** [comment] 2020-08-27 18:50
@GrabYourPitchforks - I mean, that issue is about the fact that there's a deviation in the algorithm used to generate what `InternalSample()` returns.

This one is more about how there's a slight bias due to the fact that `InternalSample()` doesn't return `int.MaxValue`.  That is, even if there was no deviation in the algorithm, there would still be this issue.

Although yes, it may end up being a dupe due to the resolution.  I just wanted this explicitly called out.

**Comment by GrabYourPitchforks** [comment] 2020-08-31 18:24
Ah, yes, you're right in that it's not an exact dupe. But the resolution would be the same. Either they're all resolved as "by design", or they're fixed all at once.

**Closed** 2021-01-21 01:26 UTC
Labels: area-System.Runtime, bug, in pr

**Comment by Clockwork-Muse** [comment] 2021-01-21 07:09
Note to future readers:

The fix implemented at this time only affects randoms created without an explicit seed.  Due to compatibility concerns, randoms initialized with a seed retain the old behavior.
