### ISSUE TITLE
Test failure tracing/eventpipe/bigevent/bigevent/bigevent.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#67216] opened 2022-03-28 02:18 UTC
Run: [runtime-coreclr r2r-extra 20220326.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1684072&view=ms.vss-test-web.build-test-results-tab&runId=46092706&paneView=debug&resultId=109832)

Failed test:
```
R2R Linux arm64 Checked gcstress0xf @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm64v8-20210531091519-97d8652

- tracing/eventpipe/bigevent/bigevent/bigevent.sh

```
**Error message:**
```
rm: cannot remove 'IL-CG2/composite-r2r.dll': No such file or directory
/root/helix/work/workitem/e/tracing/eventpipe/bigevent/bigevent/bigevent.sh: line 265: -r:/root/helix/work/workitem/e/tracing/eventpipe/bigevent/bigevent/IL-CG2/.dll: No such file or directory
rm: cannot remove '/root/helix/work/workitem/e/tracing/eventpipe/bigevent/bigevent/bigevent.dll.rsp': No such file or directory
rm: cannot remove '/root/helix/work/workitem/e/tracing/eventpipe/bigevent/bigevent/common.dll.rsp': No such file or directory
rm: cannot remove '/root/helix/work/workitem/e/tracing/eventpipe/bigevent/bigevent/Microsoft.Diagnostics.NETCore.Client.dll.rsp': No such file or directory
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
at Microsoft.Diagnostics.Tracing.TraceEvent.CopyBlob(IntPtr, IntPtr, Int32)
at Microsoft.Diagnostics.Tracing.TraceEvent.Clone()
at Microsoft.Diagnostics.Tracing.Parsers.ExternalTraceEventParser.<.ctor>b__0_0(Microsoft.Diagnostics.Tracing.TraceEvent)
at Microsoft.Diagnostics.Tracing.TraceEventDispatcher.Lookup(EVENT_RECORD)
at Microsoft.Diagnostics.Tracing.EventPipeEventSource.DispatchEventRecord(EVENT_RECORD*)
at Microsoft.Diagnostics.Tracing.EventPipeEventSource.EventCache_OnEvent(Microsoft.Diagnostics.Tracing.EventPipeEventHeader ByRef)
at Microsoft.Diagnostics.Tracing.EventPipe.EventCache.SortAndDispatch(Int64)
at Microsoft.Diagnostics.Tracing.EventPipe.EventCache.ProcessSequencePointBlock(Byte[])
at Microsoft.Diagnostics.Tracing.EventPipeSequencePointBlock.ReadBlockContents(FastSerialization.PinnedStreamReader)
at Microsoft.Diagnostics.Tracing.EventPipeBlock.FromStream(FastSerialization.Deserializer)
at FastSerialization.Deserializer.ReadObjectDefinition(FastSerialization.Tags, FastSerialization.StreamLabel)
at FastSerialization.Deserializer.ReadObject()
at Microsoft.Diagnostics.Tracing.EventPipeEventSource.Process()
at Tracing.Tests.Common.IpcTraceTest+<>c__DisplayClass9_0.<Validate>b__1()
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
/root/helix/work/workitem/e/tracing/eventpipe/bigevent/bigevent/bigevent.sh: line 389:   515 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/tracing.eventpipe/bigevent/bigevent/bigevent.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/root/helix/work/workitem/e/tracing/eventpipe/bigevent/bigevent/IL-CG2/bigevent.dll
Response file: /root/helix/work/workitem/e/tracing/eventpipe/bigevent/bigevent/bigevent.dll.rsp
/root/helix/work/workitem/e/tracing/eventpipe/bigevent/bigevent/IL-CG2/bigevent.dll
-o:/root/helix/work/workitem/e/tracing/eventpipe/bigevent/bigevent/bigevent.dll
-r:/root/helix/work/correlation/System..dll
-r:/root/helix/work/correlation/Microsoft..dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--targetarch:arm64
-O
Running CrossGen2:  dotnet /root/helix/work/correlation/crossgen2/crossgen2.dll @/root/helix/work/workitem/e/tracing/eventpipe/bigevent/bigevent/bigevent.dll.rsp

Emitting R2R PE file: /root/helix/work/workitem/e/tracing/eventpipe/bigevent/bigevent/bigevent.dll
/root/helix/work/workitem/e/tracing/eventpipe/bigevent/bigevent/IL-CG2/common.dll
Response file: /root/helix/work/workitem/e/tracing/eventpipe/bigevent/bigevent/common.dll.rsp
/root/helix/work/workitem/e/tracing/eventpipe/bigevent/bigevent/IL-CG2/common.dll
-o:/root/helix/work/workitem/e/tracing/eventpipe/bigevent/bigevent/commo


Stack trace
   at tracing_eventpipe._bigevent_bigevent_bigevent_._bigevent_bigevent_bigevent_sh()
```

**Comment by tommcdon** [comment] 2022-03-29 21:44
@josalem

**Comment by josalem** [comment] 2022-03-29 21:51
This is a dup of #54801 which describes the investigation to root cause to https://github.com/microsoft/perfview/issues/1474.

**Comment by hoyosjs** [comment] 2022-03-31 22:22
The fix is in @josalem. Do we need to consume it in the repo?

**Comment by josalem** [comment] 2022-03-31 22:23
Fix is in main over at Microsoft/PerfView. We need to roll up a new release and then upgrade the tests to that release before we can close this issue.

**Closed** 2022-04-21 22:11 UTC
Labels: arch-arm64, os-linux, tracking-external-issue, GCStress, area-Tracing-coreclr, in-pr
