### ISSUE TITLE
Test failure:System.Net.NameResolution.Tests.GetHostEntryTest.Dns_GetHostEntryAsync_DisableIPv6_ExcludesIPv6Addresses

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#55549] opened 2021-07-13 01:53 UTC
Run [runtime 20210712.116](https://dev.azure.com/dnceng/public/_build/results?buildId=1233668&view=ms.vss-test-web.build-test-results-tab&runId=36716834&resultId=150199&paneView=debug)
Failed test:
```
net6.0-Linux-Release-x64-CoreCLR_release-SLES.12.Amd64.Open

- System.Net.NameResolution.Tests.GetHostEntryTest.Dns_GetHostEntry_DisableIPv6_ExcludesIPv6Addresses(hostnameOuter: \"\")
- System.Net.NameResolution.Tests.GetHostEntryTest.Dns_GetHostEntryAsync_DisableIPv6_ExcludesIPv6Addresses(hostnameOuter: \"\")

net6.0-Linux-Release-x64-Mono_release-SLES.12.Amd64.Open

- System.Net.NameResolution.Tests.GetHostEntryTest.Dns_GetHostEntry_DisableIPv6_ExcludesIPv6Addresses(hostnameOuter: \"\")
- System.Net.NameResolution.Tests.GetHostEntryTest.Dns_GetHostEntryAsync_DisableIPv6_ExcludesIPv6Addresses(hostnameOuter: \"\")

```
**One of error messages:**
```
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.


Stack trace

Child exception:
  System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known
   at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 403
   at System.Net.Dns.GetHostEntryCore(String hostName, AddressFamily addressFamily) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 384
   at System.Net.Dns.GetHostEntry(String hostNameOrAddress, AddressFamily family) in /_/src/libraries/System.Net.NameResolution/src/System/Net/Dns.cs:line 91
   at System.Net.NameResolution.Tests.GetHostEntryTest.<Dns_GetHostEntry_DisableIPv6_ExcludesIPv6Addresses>g__RunTest|7_0(String hostnameInner) in /_/src/libraries/System.Net.NameResolution/tests/FunctionalTests/GetHostEntryTest.cs:line 131

Child process:
  System.Net.NameResolution.Functional.Tests, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Net.NameResolution.Tests.GetHostEntryTest Void <Dns_GetHostEntry_DisableIPv6_ExcludesIPv6Addresses>g__RunTest|7_0(System.String)

Child arguments:
```

**Comment by karelz** [comment] 2021-07-13 08:48
Duplicate of #55271

**Closed by karelz** 2021-07-13 08:48 UTC
Labels: arch-x64, area-System.Net, os-linux, untriaged
