### ISSUE TITLE
dotnet test cannot compile projects whereas dotnet build succeeds

### ISSUE THREAD

**Issue by meziantou** [dotnet/runtime#43373] opened 2020-10-13 21:42 UTC
### Description

`dotnet test` fails as it cannot compile a project, but `dotnet build` can compile the project.

### Repro

1. `git clone https://github.com/meziantou/Meziantou.Framework.git` on Windows
2. `git checkout e9c7f1fba14be2e56f3e39e7212e82ae87b334d8` (latest commit when I'm creating this issue)
2. `dotnet build` in the root folder => build succeeds
3. `dotnet test --no-build` => tests passed
4. `dotnet test` => some projects compile, some fail. I think it doesn't resolve `<ProjectReference>` correctly.

For instance I get the following compilation error:

````
tests\Meziantou.Framework.Win32.RestartManager.Tests\RestartManagerTests.cs(18,37): error CS0103: The name 'RestartManager' does not exist in the current context
````

Note that running tests per project (e.g. `dotnet test tests/proj1.csproj`) instead of on the solution works.

### Configuration

````
C:\Users\meziantou\source\repos\meziantou\Meziantou.Framework>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.2.20479.15
 Commit:    da7dfa8840

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.2.20479.15\

Host (useful for support):
  Version: 5.0.0-rc.2.20475.5
  Commit:  c5a3f49c88

.NET SDKs installed:
  3.1.300 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.2.20475.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
````

### Other information

I got a similar error on a private project with .NET 5.0 RC1. However, I cannot share it here.

**Comment by danmosemsft** [comment] 2020-10-13 22:16
@nohwnd any idea where this issue should go?

**Comment by nohwnd** [comment] 2020-10-14 09:37
Dupe of https://github.com/microsoft/vstest/issues/2570 (and https://github.com/dotnet/sdk/issues/13584). Should be fixed in GA.

**Comment by danmosemsft** [comment] 2020-10-14 11:03
Thanks @nohwnd

**Closed by danmosemsft** 2020-10-14 11:03 UTC
