### ISSUE TITLE
Blazor WebAssembly: "An unhandled error has occurred. Reload" since .NET 8.0.5

### ISSUE THREAD

**Issue by ghost** [dotnet/runtime#102307] opened 2024-05-16 07:46 UTC
### Description

Since the update of Visual Studio to version 17.9.7 and .NET 8.0.5, an error is produced when starting Blazor Webassembly applications in release mode in the Edge Browser from Visual Studio ("An unhandled error has occurred. Reload").
This error occurs with all Blazor Webassembly applications.
To reproduce it, I created a completely new and empty Blazor Webassembly app. The error occurs even without any changes.

![blazor_error](https://github.com/dotnet/runtime/assets/165083146/cf79d892-cede-4981-94a2-ebb0fb1a8ee1)

An example project can be found here:
https://github.com/Coding-Victim/BlazorApp1

### Reproduction Steps

Create an empty Blazor WebAssembly project, select "Release", start the project with the MS Edge browser (newest Version)

### Expected behavior

The empty WebAssembly app starts without any problems

### Actual behavior

The empty WebAssembly app starts, but the MS Edge shows the message: "An unhandled error has occurred. Reload"

In the HTML, style="display: block;" is automatically added to the line <div id="blazor-error-ui">. This actually only happens if an exception is thrown. Since .NET 8.0.5, this already happens when the empty project is started through Visual Studio with MS Edge browser. 

### Regression?

In .NET 8.0.4 it worked in all projects without any problems

### Configuration

.NET 8.0.5
Visual Studio 2022 (v17.9.7)
Windows 10 and 11
MS Edge

**Comment by maraf** [comment] 2024-05-17 19:12
It looks like a duplicate of https://github.com/dotnet/runtime/issues/102272. Please see devtools console for error details. Let us know if the issue is different

**Comment by Coding-Victim** [comment] 2024-05-17 20:05
I think the issue is different. I got the following error in the browser console.

```
blazor.webassembly.js:1  DEBUGGING IS NOT ENABLED
Dt @ blazor.webassembly.js:1
put_char @ dotnet.native.8.0.5.p7qv7rl7e4.js:8
write @ dotnet.native.8.0.5.p7qv7rl7e4.js:8
write @ dotnet.native.8.0.5.p7qv7rl7e4.js:8
doWritev @ dotnet.native.8.0.5.p7qv7rl7e4.js:8
_fd_write @ dotnet.native.8.0.5.p7qv7rl7e4.js:8
$func8373 @ 00b2193a:0x1fb5df
$func8387 @ 00b2193a:0x1fbd0d
$func8388 @ 00b2193a:0x1fbdb6
$func8382 @ 00b2193a:0x1fbc0e
$func549 @ 00b2193a:0x3bd8c
$func548 @ 00b2193a:0x3bd6d
$mono_wasm_send_dbg_command @ 00b2193a:0x6dcf8
Module._mono_wasm_send_dbg_command @ dotnet.native.8.0.5.p7qv7rl7e4.js:8
e.<computed> @ cwraps.ts:338
Bt @ debug.ts:89
(anonym) @ VM14:1
mono_wasm_runtime_ready @ debug.ts:32
(anonym) @ startup.ts:290
await in (anonym) (asynchron)
Nl.e.onRuntimeInitialized @ startup.ts:92
doRun @ dotnet.native.8.0.5.p7qv7rl7e4.js:8
run @ dotnet.native.8.0.5.p7qv7rl7e4.js:8
runCaller @ dotnet.native.8.0.5.p7qv7rl7e4.js:8
removeRunDependency @ dotnet.native.8.0.5.p7qv7rl7e4.js:8
(anonym) @ startup.ts:232
await in (anonym) (asynchron)
Nl.e.preRun @ startup.ts:90
callRuntimeCallbacks @ dotnet.native.8.0.5.p7qv7rl7e4.js:8
preRun @ dotnet.native.8.0.5.p7qv7rl7e4.js:8
run @ dotnet.native.8.0.5.p7qv7rl7e4.js:8
runCaller @ dotnet.native.8.0.5.p7qv7rl7e4.js:8
removeRunDependency @ dotnet.native.8.0.5.p7qv7rl7e4.js:8
(anonym) @ startup.ts:505
await in (anonym) (asynchron)
(anonym) @ startup.ts:138
Nl.e.instantiateWasm @ startup.ts:86
createWasm @ dotnet.native.8.0.5.p7qv7rl7e4.js:8
(anonym) @ dotnet.native.8.0.5.p7qv7rl7e4.js:8
Fe @ run.ts:464
await in Fe (asynchron)
(anonym) @ run.ts:505
await in (anonym) (asynchron)
Pe @ run.ts:428
await in Pe (asynchron)
create @ run.ts:362
(anonym) @ blazor.webassembly.js:1
await in (anonym) (asynchron)
load @ blazor.webassembly.js:1
(anonym) @ blazor.webassembly.js:1
await in (anonym) (asynchron)
hn @ blazor.webassembly.js:1
mn @ blazor.webassembly.js:1
fn @ blazor.webassembly.js:1
An @ blazor.webassembly.js:1
(anonym) @ blazor.webassembly.js:1
(anonym) @ blazor.webassembly.js:1
```

**Comment by maraf** [comment] 2024-05-21 12:43
cc @thaystg

**Closed** 2024-07-26 12:37 UTC
Labels: arch-wasm, area-VM-meta-mono, os-browser
