### ISSUE TITLE
IOptionsSnapshot Results in High CPU 100% at 1500 RPS with 15 Node Cluster (8core per vm 32GB Memory)

### ISSUE THREAD

**Issue by justConfused** [dotnet/runtime#42222] opened 2020-08-13 05:50 UTC
### Describe the bug
IOptionsSnapshot Results in High CPU 100% at 1500 RPS with 15 Node Cluster (8core per vm 32GB Memory). HTTP.Sys Asp Net core 2.1

It looks like `Wait` on GC is blocking for some mutex as captured traces from azure profile show. Image below.

### To Reproduce
1.) Start Azure Vm StandardDv2_v8
2.) 100 RPS
3.) HTTP.SYS(AspNetCore): Add IOptionsSnapshot as scoped depend so it created on ever request
4.) CPU should 100

### Expected behavior
High CPU

### Screenshots
![image](https://user-images.githubusercontent.com/42451741/90098654-9138cc80-dced-11ea-935e-9ebfba5b6809.png)

**Comment by BrennanConroy** [comment] 2020-09-14 21:51
> This is something we might want to address in 5.0 or 6.0

6.0 😄

**Comment by davidfowl** [comment] 2020-10-02 18:35
@maryamariyan we should close as dupe of https://github.com/dotnet/runtime/issues/36130

**Closed** 2020-10-02 18:43 UTC
Labels: area-Extensions-Options, bug, tenet-performance
