### ISSUE TITLE
.NET 6 slower than .NET 5 for relatively simple linq

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#65399] opened 2022-02-15 20:53 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/NET-6-slower-than-NET-5-for-relatively/1600495)._

---
[severity:It's more difficult to complete my work]
Having the following two classes to run peformance tests:

program.cs:
```
using System;
using BenchmarkDotNet.Running;

namespace ConsolePerformanceTest
{
    internal static class Program
    {
        private static void Main(string[] args)
        {
            Console.WriteLine("Hello, World!");
            var summary = BenchmarkRunner.Run<TestConvertPerformance>();
            
}
    }
}
```
TestConvertPerformance.cs:

```
using System;
using System.Linq;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Jobs;

namespace ConsolePerformanceTest
{
    [SimpleJob(RuntimeMoniker.Net50)]
    [SimpleJob(RuntimeMoniker.Net60)]
    public class TestConvertPerformance
    {
        private int[] _data= Array.Empty<int>();

[Params(1000, 10_000, 100_000)]
        public int N;
        [GlobalSetup]
        public void Setup()
        {
            _data = new int[N];
            var r = new Random(42);
            for (int i = 0;i<N;i++)
            {
                _data[i] = r.Next();
            }
        }
        [Benchmark]
        public uint[] ConvertToUint() => _data. Select(Convert.ToUInt32). ToArray();
    }
}
```
Yields the following results on my machine:

>BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19044.1348 (21H2)
>Intel Xeon CPU E5-1607 0 3.00GHz, 1 CPU, 4 logical and 4 physical cores
>.NET SDK=6.0.100
>  [Host]   : .NET 6.0.0 (6.0.21.52210), X64 RyuJIT
>  .NET 5.0 : .NET 5.0.12 (5.0.1221.52207), X64 RyuJIT
>  .NET 6.0 : .NET 6.0.0 (6.0.21.52210), X64 RyuJIT

>|        Method |      Job |  Runtime |      N |       Mean |     Error |    StdDev |
>|-------------- |--------- |--------- |------- |-----------:|----------:|----------:|
>| ConvertToUint | .NET 5.0 | .NET 5.0 |   1000 |   4.077 us | 0.0123 us | 0.0115 us |
>| ConvertToUint | .NET 6.0 | .NET 6.0 |   1000 |   4.411 us | 0.0098 us | 0.0092 us |
>| ConvertToUint | .NET 5.0 | .NET 5.0 |  10000 |  39.829 us | 0.1105 us | 0.0979 us |
>| ConvertToUint | .NET 6.0 | .NET 6.0 |  10000 |  43.262 us | 0.1320 us | 0.1235 us |
>| ConvertToUint | .NET 5.0 | .NET 5.0 | 100000 | 402.705 us | 0.4670 us | 0.4140 us |
>| ConvertToUint | .NET 6.0 | .NET 6.0 | 100000 | 453.619 us | 0.7872 us | 0.6979 us |

I have not been able to test in wasm directly using benchmarkdotnet but running my app and testing the testing method (i.e. `_data. Select(Convert.ToUInt32). ToArray();`) in wasm (**not** AOT) results in a downgrade of about 800 % on average for .NET 6 compared to .NET 5. That is .NET 6 wasm is 8 times **slower** than .NET 5.
Is there an explanation for this. Is my code incorrect somehow?

---
#### Feedback Bot on 12/1/2021, 02:27 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by EgorBo** [comment] 2022-02-15 22:25
From a quick glance I don't see anything offending in the output codegen: https://www.diffchecker.com/g9xkPW88

.NET 6.0 has even better handling of `ManagedThreadId` (I guess because of https://github.com/dotnet/runtime/pull/41213)

maybe it affected loop-alignment somehow

**Comment by danmoseley** [comment] 2022-02-16 05:28
In general if you care about perf at this level we would likely not recommend using Linq.

**Comment by EgorBo** [comment] 2022-02-16 12:26
At this scale it can be anything:
1) Data alignment
2) Loop alignment (e.g. we still sometimes incorrectly estimate instructions' size on x86/64 and that leads to invalid alignment)
3) JCC erratum - small unrelated codegen changes might slightly move some jumps so they will cross 32b boundary and hit a noticeably penalty

**Comment by EgorBo** [comment] 2022-02-16 12:31
@eiriktsarpalis I can't repro your results on my win-x64 core i7-8700K:


|  Method |      Job |  Runtime |      N |       Mean |     Error |    StdDev |
|-------- |--------- |--------- |------- |-----------:|----------:|----------:|
| ToArray | .NET 5.0 | .NET 5.0 |   1000 |   2.215 us | 0.0178 us | 0.0149 us |
| ToArray | .NET 6.0 | .NET 6.0 |   1000 |   1.977 us | 0.0109 us | 0.0102 us |
| ToArray | .NET 5.0 | .NET 5.0 |  10000 |  19.193 us | 0.3648 us | 0.3746 us |
| ToArray | .NET 6.0 | .NET 6.0 |  10000 |  19.214 us | 0.1240 us | 0.1160 us |
| ToArray | .NET 5.0 | .NET 5.0 | 100000 | 208.497 us | 1.5968 us | 1.4937 us |
| ToArray | .NET 6.0 | .NET 6.0 | 100000 | 204.279 us | 4.0522 us | 4.5040 us |

**Comment by lewing** [comment] 2022-07-25 23:05
cc @BrzVlad

**Comment by BrzVlad** [comment] 2022-08-01 13:27
On wasm I don't see any benchmark regression. main is about 12% faster than .NET 5.0 for this benchmark.

**Comment by eiriktsarpalis** [comment] 2022-08-04 11:55
I think we can close this. Can revisit if more data arises.

**Closed by eiriktsarpalis** 2022-08-04 11:55 UTC
Labels: arch-wasm, area-System.Linq, tenet-performance
