### ISSUE TITLE
.Skip allows a Collection to be modified during enumeration

### ISSUE THREAD

**Issue by joshbartley** [dotnet/runtime#40415] opened 2020-08-05 20:42 UTC
### Description
I flipped a variable and found out that .Skip allows the IEnumerable to be modified during enumeration which caused an infinite loop. Related to a similar issue that was moved in [dotnet/corefx] (#32278). 

```c# 
            var example = new List<string>() { "test0","test1" };  
            var i = 0;  
            foreach (var item in example.Skip(1))
            {
                example.Add("test");
                i++;
                if (i > 1000)
                {
                    Console.WriteLine("Modified IEnumerable through LINQ");
                    break;
                }
            }
```

Tested without LINQ, and the exception is thrown that you cannot modify a IEnumerable in progress. 

Tried with .OrderBy() and it allowed the code to run but did not add new entries to the end of the IEnumerable and would only run twice, which could be a separate bug. 

I have not tried with a LINQ/Lambda only statement as the first time this happened it locked a 24gb Ryzen machine. 

### Configuration

.Net 3.1 ,Windows 10 x64

### Regression?

Previously any modification of the IEnumerable while enumerating caused an exception. 

### Other information

An optimization caused an issue with a similar bug report for 2.1 dealing with infinite loops and IEnumerable [dotnet/corefx] (#32278). It was decided to roll back that merge request to fix the issue.

**Comment by Clockwork-Muse** [comment] 2020-08-05 21:04
`OrderBy` has to create a copy of the input enumerable (`O(n log n)`) in order to serve up the results in reasonable time (`O(n)`), since otherwise it would scan the list each time (`O(n^2)`), so that's not surprising.  What did you mean by "only run twice", though?

**Comment by joshbartley** [comment] 2020-08-05 21:21
When using `OrderBy(x=> x)` versus `Skip(1)` the loop only runs twice, once for each item. An exception should still throw for `OrderBy()` as in the example it is modifying a `IEnumerator` which is not allowed.

**Comment by benaadams** [comment] 2020-08-05 21:33
It doesn't look to use the IEnumerable but use IList indexing (hence modified enumerator not triggered).

However, it should probably use `sourceList.Count - count` as the upperbound rather than `int.MaxValue` so max enumerations is snapshotted at the creation?

https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.Linq/src/System/Linq/Skip.SpeedOpt.cs#L11-L13

Uses both `_source.Count` and `_maxIndexInclusive` as a guard on enumeration; but that's not helpful if  `_source.Count` is increasing and `_maxIndexInclusive` is set to 2 billion rather than starting `count - skip` https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.Linq/src/System/Linq/Partition.SpeedOpt.cs#L177-L180

**Comment by Clockwork-Muse** [comment] 2020-08-05 22:21
> When using `OrderBy(x=> x)` versus `Skip(1)` the loop only runs twice, once for each item. An exception should still throw for `OrderBy()` as in the example it is modifying a `IEnumerator` which is not allowed.

Not a bug in itself, since it's iterating over the "original" items.  Since it appears to be using indices directly, it's likely snapshotting the range.

@benaadams - possibly, although that's still not going to throw in all the same cases (ie, `add`+`remove`, which will throw for an enumerator, but not due to index checking).  Likely good enough for this case, though.

**Comment by benaadams** [comment] 2020-08-05 22:58
>  possibly, although that's still not going to throw in all the same cases

It wouldn't throw at all; however throwing is a peculiarity of some collections not guaranteed by IEnumerable. Looping effectively forever is more of an issue?

**Comment by Clockwork-Muse** [comment] 2020-08-06 03:55
True, yes.

**Comment by stephentoub** [comment] 2020-09-21 17:01
> However, it should probably use sourceList.Count - count as the upperbound rather than int.MaxValue so max enumerations is snapshotted at the creation?

No, there shouldn't be a difference functionally between:
```C#
List<T> list = ...;
IEnumerable<T> e = list.SomeLinqOps();
list.Add(...)/Remove(...)/etc.;
foreach (T t in e) { ... }
```
and
```C#
List<T> list = ...;
list.Add(...)/Remove(...)/etc.;
IEnumerable<T> e = list.SomeLinqOps();
foreach (T t in e) { ... }
```
Snapshotting of anything to do with the contents of the list shouldn't happen until the enumerable is actually enumerated.

**Comment by eiriktsarpalis** [comment] 2020-12-01 18:50
We could perhaps improve it so that the list count is snapshotted on `GetEnumerator()`. Note however that `ListPartition<T>` [implements IEnumerator itself](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Linq/src/System/Linq/Iterator.cs#L81) so any changes to that effect would have to be made carefully.

**Comment by eiriktsarpalis** [comment] 2020-12-01 20:30
I tried prototyping [snapshotting logic for ListPartition](https://github.com/eiriktsarpalis/runtime/commit/1835cb62b4a0b0f2b829bee4d97b1cc729a74a80) however I'm not particularly satisfied with the result. Due to the current design of the internal `Iterator<TResult>` type, the snapshotting needs to happen in the first `MoveNext()` call, which could have performance ramifications.

The question then is whether we consider the potential infinite loop serious enough to make such an inclusion.

**Comment by jeffhandley** [comment] 2022-02-09 11:03
I'm inclined to close this without resolution, but I'd like to confirm a couple understandings I have on it.

1. Guarding against mutation will incur a performance penalty; the more robustly we guard against it, the steeper the penalty
2. Such an infinite loop bug would likely be encountered during development/testing
3. It's ostensible that this loophole could be used for good; I can imagine a scenario where under certain circumstances, new elements are added to be included in the enumeration, but without causing an infinite loop

**Comment by Clockwork-Muse** [comment] 2022-02-09 16:09
> It's ostensible that this loophole could be used for good; I can imagine a scenario where under certain circumstances, new elements are added to be included in the enumeration, but without causing an infinite loop

There are no scenarios where this is reasonable, even without the infinite loop bug.

Modifying a collection during an enumeration is always user error, and should be fixed by one or more different mechanisms (yielding an additional item, building a list to concatenate on the end...)

**Comment by eiriktsarpalis** [comment] 2022-02-09 16:11
I should clarify that the workaround I had proposed does not guard against mutation in general, it simply attaches an upper bound to specifically prevent the type of blow-up encountered in the original example. I suspect a "correct" fix would involve removing the `ListPartition<T>` optimization altogether, since any LINQ method using it under wraps would be susceptible to the source being modified.

**Comment by eiriktsarpalis** [comment] 2022-02-14 14:05
Closing as by-design, combining mutation with LINQ is arguably a corner case (or rather anti-pattern) that can result in surprising behavior in the presence of performance optimizations. I don't think we should be reverting optimizations on lists for that reason.

**Closed by eiriktsarpalis** 2022-02-14 14:05 UTC
Labels: enhancement, area-System.Linq, needs-further-triage
