### ISSUE TITLE
Test failure System.Net.Quic.Tests.MsQuicTests.ByteMixingOrNativeAVE_MinimalFailingTest

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#72422] opened 2022-07-19 02:24 UTC
Run: [runtime-libraries-coreclr outerloop 20220718.5](https://dev.azure.com/dnceng/public/_build/results?buildId=1887157&view=ms.vss-test-web.build-test-results-tab&runId=49281830&paneView=debug&resultId=104544)

Failed test:
```
net7.0-windows-Release-x64-CoreCLR_release-Windows.Amd64.Server2022.Open

- System.Net.Quic.Tests.MsQuicTests.ByteMixingOrNativeAVE_MinimalFailingTest

```
**Error message:**
```
System.TimeoutException : The operation has timed out.


Stack trace
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 55
   at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions) in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 299
   at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions) in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 299
   at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions) in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 299
   at System.Net.Quic.Tests.QuicTestBase.RunClientServer(Func`2 clientFunction, Func`2 serverFunction, Int32 iterations, Int32 millisecondsTimeout, QuicListenerOptions listenerOptions) in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/QuicTestBase.cs:line 299
   at System.Net.Quic.Tests.MsQuicTests.<ByteMixingOrNativeAVE_MinimalFailingTest>g__RunTest|23_0(Byte[] data) in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs:line 838
   at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 128
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 92
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 55
   at System.Net.Quic.Tests.MsQuicTests.ByteMixingOrNativeAVE_MinimalFailingTest() in /_/src/libraries/System.Net.Quic/tests/FunctionalTests/MsQuicTests.cs:line 873
--- End of stack trace from previous location ---
```

**Comment by CarnaViire** [comment] 2022-07-19 10:47
This has most possibly the same root cause as https://github.com/dotnet/runtime/issues/72196

**Comment by ManickaP** [comment] 2022-07-19 11:40
It is the same thing, at least from my tests. I'll close it with #72439 PR.

**Closed** 2022-07-19 16:00 UTC
Labels: os-windows, arch-x64, blocking-outerloop, area-System.Net.Quic, in-pr
