### ISSUE TITLE
ServiceProviderEngineScope captures the same object twice into a list of disposables

### ISSUE THREAD

**Issue by arthuredgarov** [dotnet/runtime#91179] opened 2023-08-27 18:46 UTC
### Description

When a DI scope and all disposables instantiated with it are being disposed - the same object appears in the list of items to dispose twice.

It is only reproducible if there are two service descriptors registered:
- First one with `AddScoped<TService, TImplementation>();`
- Second one with `AddScoped<TImplementation>(Func<IServiceProvider, TImplementation> implementationFactory);`

See reproduction steps below.

---

Real life scenario:

Registering a `DbContext` with `AddDbContext<TContextService, TContextImplementation>();` registers two descriptors like mentioned above.

So having this:
```
public class MyDbContext : DbContext, IMyDbContext
{
    //Bla bla bla
}
```
```
services.AddDbContext<IMyDbContext, MyDbContext>();
```
```
private void Test(IServiceProvider provider)
{
    var scope = provider.CreateScope();
    var context = scope.ServiceProvider.GetRequiredService<MyDbContext>();
    scope.Dispose();
}
```
causes the `ObjectDisposedException`.

### Reproduction Steps

Test class:
```
internal class Disposable : IDisposable
{
    private bool _disposed;

    public void Dispose()
    {
        if (_disposed)
            throw new ObjectDisposedException(GetType().Name);

        _disposed= true;
    }
}
```

Way to reproduce:
```
var services = new ServiceCollection();

services.AddScoped<IDisposable, Disposable>();

services.AddScoped(p => (Disposable)p.GetRequiredService<IDisposable>());

var provider = services.BuildServiceProvider();

var scope = provider.CreateScope();

var instance = scope.ServiceProvider.GetService<Disposable>();

scope.Dispose();
```

### Expected behavior

Only one entry per disposable instance is stored in service provider's disposable instances cache.

### Actual behavior

Multiple entries referencing the same instance are stored in service provider's disposables instances cache.

### Known Workarounds

Remove service descriptor with implementation factory before building service provider and register a new service descriptor with implementation type.

```
var type = typeof(Disposable);

var descriptorToRemove = services
    .First(descriptor => descriptor.ServiceType == type && descriptor.ImplementationFactory != null);

services.Remove(descriptorToRemove);

services.AddScoped<Disposable>();
```

### Configuration

- Which version of .NET is the code running on? - **.NET 7**
- What OS and version, and what distro if applicable? - **Windows 11 (Build 22621.2215)**
- What is the architecture (x64, x86, ARM, ARM64)? - **x64**
- Do you know whether it is specific to that configuration? - **No**

**Comment by steveharter** [comment] 2023-08-28 14:48
Verified repro; allow occurs on v7 (in addition to v8).

**Comment by steveharter** [comment] 2023-08-28 14:49
Is there a reason
`var instance = scope.ServiceProvider.GetService<Disposable>();` is used instead of
`var instance = scope.ServiceProvider.GetService<IDisposable>();`?

That appears to be causing the issue.

**Comment by arthuredgarov** [comment] 2023-08-28 16:50
> Is there a reason `var instance = scope.ServiceProvider.GetService<Disposable>();` is used instead of `var instance = scope.ServiceProvider.GetService<IDisposable>();`?
> 
> That appears to be causing the issue.

@steveharter, yes, there is a reason for that. You can check the [issue](https://github.com/dotnet/aspnetcore/issues/49329) linked to this one. But in a few words: if you're using EF data protection with `PersistKeysToDbContext<MyDbContext>` - the underlying keys repository will try to get instance of `DbContext` through `var instance = scope.ServiceProvider.GetService<MyDbContext>();` since it have only `<MyDbContext>` generic parameter.

And in case you are subscribing on `ChangeTracker` events in constructor and unsubscribing from it's events in `Dispose` method - `ChangeTracker` will throw an exception since it was disposed after the first call.

**Comment by arthuredgarov** [comment] 2023-08-28 16:55
@davidfowl, agree. But there is a real-life scenario which I described in the comment above. And of course I will use `dsiposed` flag to ensure that my `DbContext` is disposed only once. But is it still a good thing to happen? For me it seems that the behavior of capturing disposable object could be enhanced with checking whether the object with such reference is already present in the list of services to dispose.

**Comment by winseros** [comment] 2023-10-21 09:44
I have the same issue on the project.

Imagine the code:

```csharp
static class Program
{
    static void Main(string[] args)
    {
        var provider = new ServiceCollection()
            .AddScoped<MyClass>()
            .AddScoped<IMyInterface1>(p => p.GetRequiredService<MyClass>())
            .AddScoped<IMyInterface2>(p => p.GetRequiredService<MyClass>())
            .BuildServiceProvider();

        using var scope = provider.CreateScope();
        var s1 = scope.ServiceProvider.GetRequiredService<IMyInterface1>();
        s1.Method1();
        var s2 = scope.ServiceProvider.GetRequiredService<IMyInterface2>();
        s2.Method2();
    }
}

interface IMyInterface1
{
    void Method1();
}

interface IMyInterface2
{
    void Method2();
}

class MyClass : IMyInterface1, IMyInterface2, IDisposable
{
    public void Dispose() => Console.WriteLine("Dispose");

    public void Method1() => Console.WriteLine("Method1");

    public void Method2() => Console.WriteLine("Method2");
}
```

The output of this code is:
```
Method1
Method2
Dispose
Dispose
Dispose
```
Which I consider wrong. I expect the output to be:
```
Method1
Method2
Dispose
```

**Comment by steveharter** [comment] 2023-11-02 19:30
> For me it seems that the behavior of capturing disposable object could be enhanced with checking whether the object with such reference is already present in the list of services to dispose.

Since the dispose pattern is very clear that methods are supposed to be idempotent, I don't understand why we should add such overhead to prevent calling a Dispose more than once on the same instance. Are there any other reference implementations of such a pattern?

Closing as not a bug \ feature we want to address at this time.

**Closed by steveharter** 2023-11-02 19:30 UTC
Labels: area-Extensions-DependencyInjection, needs-further-triage

**Comment by arthuredgarov** [comment] 2023-11-02 19:44
> Since the dispose pattern is very clear that methods are supposed to be idempotent…

Well, I’d be more than happy if that was true, but EF team might not agree with you. If you are disposing a DbContext instance and inside of Dispose method you are referring to ChangeTracker members - it will throw an ObjectDisposedException on a second call, which means it’s not idempotent. Basically, thats the reason why I opened this issue.

I understand that it’s not a top priority issue, but still worth fixing, I believe.

**Comment by steveharter** [comment] 2023-11-03 20:14
Are there issue(s) for the EF team?
