### ISSUE TITLE
Add parameter InheritHandles to System.Diagnostics.ProcessStartInfo class

### ISSUE THREAD

**Issue by FStapenhorst** [dotnet/runtime#39602] opened 2020-07-18 17:27 UTC
## Background and Motivation

When working with C++ DLLs that create file handles, for example log files, using the MFC CFile class or CStdioFile class, the DLL holds a file handle to the file opened. If this DLL is loaded into the address space of a .Net Framework application and this application starts a new process using the ProcessStartInfo.UseShellExecute parameter set to FALSE, all file handles are inherited to all child processes. This results in open (and possible write and read locked) files even if the file is closed in the C++ DLL which originally opened it! This leads to issues especially if the C++ DLL attempts to re-open the log file again - it will receive a sharing violation.
Currently, the only way to work around this issue is to set ProcessStartInfo.UseShellExecute=TRUE but then you loose the Redirect stdout feature of the ProcessStart (which is only supported if ProcessStartInfo.UseShellExecute=FALSE).

## Proposed API
Add a new bool parameter to ProcessStartInfo: InheritHandles (Default: true)
```
 public bool InheritHandles { get; set; } = true;
```
Then, when creating the process using CreateProcess() use the parameter (see `//handle inheritance` flag below)
```
fixed (char* environmentBlockPtr = environmentBlock)
{
  retVal = Interop.Kernel32.CreateProcess(
    null,                // we don't need this since all the info is in commandLine
    commandLine,         // pointer to the command line string
    ref unused_SecAttrs, // address to process security attributes, we don't need to inherit the handle
    ref unused_SecAttrs, // address to thread security attributes.
    _inheritHandles,                // handle inheritance flag
    creationFlags,       // creation flags
    (IntPtr)environmentBlockPtr, // pointer to new environment block
    workingDirectory,    // pointer to current directory name
    ref startupInfo,     // pointer to STARTUPINFO
    ref processInfo      // pointer to PROCESS_INFORMATION
  );
  if (!retVal)
    errorCode = Marshal.GetLastWin32Error();
}
```

## Risks
If the default of the new property is set to true, there are no risks because the current behavior is unchanged.

**Comment by jkotas** [comment] 2020-07-18 18:05
Duplicate of #13943

**Closed** 2020-07-23 06:14 UTC
Labels: api-suggestion, area-System.Diagnostics.Process, untriaged
