### ISSUE TITLE
[API Proposal]: Valuestopwatch

### ISSUE THREAD

**Issue by mburbea** [dotnet/runtime#101319] opened 2024-04-19 23:34 UTC
### Background and motivation

With the advent of the relatively  new static apis of `Stopwatch.GetTimeStamp` and `Stopwatch.GetElapsedTime(long)`, I have found myself trying to reduce the weight of some of my analytic logging and metric collecting and replaced usages of the `Stopwatch` class for tasks with adding a `long startTs = Stopwatch.GetTimestamp();` instead of a stopwatch. I imagine others are probably doing something similar and it could be nice to ship a wrapper struct in the bcl.

### API Proposal

```csharp
namespace System.Diagnostics;

public readonly struct ValueStopwatch
{
    private readonly long _startTimestamp;
    public ValueStopwatch()=>
         _startTimestamp = Stopwatch.GetElapsed();

     public readonly TimeSpan GetElapsedTime() => 
         Stopwatch.GetElapsedTime(_startTimestamp);
}
```

### API Usage

```csharp

ValueStopwatch sw = new();
//... do work here..
_logger.LogInformation("Completed work in {elapsed}", sw.GetElapsedTime());
```

### Alternative Designs

Alternatively, we can not ship the helper and just use the existing apis.

### Risks

Bloat?

**Comment by teo-tsirpanis** [comment] 2024-04-19 23:46
Duplicate of #48570.

**Closed by teo-tsirpanis** 2024-04-19 23:46 UTC
Labels: api-suggestion, area-System.Diagnostics, untriaged

**Comment by mburbea** [comment] 2024-04-19 23:58
Sorry didn't notice, although I think it still might be worth revisting this api as this is used in quite a few repositories including this file here: https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Http/src/ValueStopwatch.cs

**Comment by teo-tsirpanis** [comment] 2024-04-20 00:28
This type exists because `Microsoft.Extensions.Http` targets frameworks that do not have the new `Stopwatch` APIs. I don't think `ValueStopwatch` is actually needed when exclusively targeting modern frameworks; the new APIs are quite as easy to use.
