### ISSUE TITLE
.NET 6: System.Random - seeded implementation of .NextInt64* methods is inconsistent with .Next* methods

### ISSUE THREAD

**Issue by sdrapkin** [dotnet/runtime#58486] opened 2021-09-01 03:21 UTC
### Description

**.NET 6, 5, 3.1, and probably most .NET Frameworks:**
```csharp
var r1 = new Random(123);	
r1.Next().Dump(); // 2114319875
r1.Next().Dump(); // 1949518561
r1.Next().Dump(); // 1596751841
r1.Next().Dump(); // 1742987178
```
```csharp
var r1 = new Random(123);	
r1.Next(0).Dump(); // 0 (technically does not need to consume state, but state got iterated)
r1.Next().Dump();  // 1949518561 (2nd call matches)
r1.Next().Dump();  // 1596751841 (3rd call matches)
r1.Next().Dump();  // 1742987178 (4th call matches)
```
```csharp
var r1 = new Random(123);	
r1.Next(1).Dump(); // 0 (technically does not need to consume state, but state got iterated)
r1.Next().Dump();  // 1949518561 (2nd call matches)
r1.Next().Dump();  // 1596751841 (3rd call matches)
r1.Next().Dump();  // 1742987178 (4th call matches)
```
```csharp
var r1 = new Random(123);
r1.Next((1 << 30) + 1).Dump(); // 1057159938 (iterates state only once)
r1.Next().Dump();              // 1949518561 (2nd call matches)
r1.Next().Dump();              // 1596751841 (3rd call matches)
r1.Next().Dump();              // 1742987178 (4th call matches)
```

**.NET 6:**
```csharp
var r2 = new Random(123);
r2.NextInt64().Dump(); // 5751341171501756545
r2.NextInt64().Dump(); // 1468073721509004893
r2.NextInt64().Dump(); // 4492647383573077195
r2.NextInt64().Dump(); // 7443599010373778036
```
```csharp
var r2 = new Random(123);
r2.NextInt64(0).Dump(); // 0 (state not consumed)
r2.NextInt64().Dump();  // 5751341171501756545 (different - 1st state consumption)
r2.NextInt64().Dump();  // 1468073721509004893 (different - 2nd state consumption)
r2.NextInt64().Dump();  // 4492647383573077195 (different - 3rd state consumption)
```
```csharp
var r2 = new Random(123);
r2.NextInt64(1).Dump(); // 0 (state not consumed)
r2.NextInt64().Dump();  // 5751341171501756545 (different - 1st state consumption)
r2.NextInt64().Dump();  // 1468073721509004893 (different - 2nd state consumption)
r2.NextInt64().Dump();  // 4492647383573077195 (different - 3rd state consumption)
```
```csharp
var r2 = new Random(123);
r2.NextInt64((1 << 62) + 1).Dump(); // 341812549 (state is consumed twice) 
r2.NextInt64().Dump();              // 4492647383573077195 (matches 4th result above)
r2.NextInt64().Dump();              // 7443599010373778036
r2.NextInt64().Dump();              // 1003052373149355376
```

### Conclusions
Legacy seeded `System.Random` consumes state in stable fixed consumptions per API-call, regardless of parameters passed into API (as long as they are valid).

New `.NextInt64*` methods deviate from this expected (but not documented) behavior, and consume state in variable number of consumptions per API-call, depending on the input values.

Legacy seeded `System.Random` has always had the (undocumented) design of state-rotations being a function of the API calls only, but not the specific parameters. New `.NextInt64*` methods should have the same behavior to ensure consistency and reproducibility.

### P.S.
`System.Random` test-suite is missing these scenarios...

@stephentoub @jkotas

**Comment by stephentoub** [comment] 2021-09-01 03:40
> New .NextInt64* methods should have the same behavior to ensure consistency and reproducibility.

I'm not seeing why it's important that new overloads exhibit the same undocumented side effects.  Can you clarify why you believe it matters?

**Comment by sdrapkin** [comment] 2021-09-01 15:20
> I'm not seeing why it's important that new overloads exhibit the same undocumented side effects. Can you clarify why you believe it matters?

Let's recall that just because .NET team wishes developers to use the API in a certain way and even explicitly documents the caveats of misuse, the real usage often differs. We all remember this:
> The implementation of the random number generator in the Random class isn't guaranteed to remain the same across major versions of the .NET Framework. As a result, you shouldn't assume that the same seed will result in the same pseudo-random sequence in different versions of the .NET Framework.

...and yet here we are, with the nonideal implementation of `System.Random(Seed)` cemented forever because of rampant widespread reliance on the stability of reproducible seeded random sequences cross-version and cross-environment. You all know this, no need to rehash.

---
Imagine someone is using `System.Random(Seed)` in a game which generates persistent "game-world" on the fly (very common) as the player moves through it, with locations of the (re)-appearing objects sourced from `Random`. However, each game first initializes the locations and strength/attributes of the enemies using calls to `.Next(min, max)` with variable parameters (ex. using `DateTime.UtcNow` or `Environment.TickCount`) - the enemies should be appearing in different locations throughout the world, and with different attributes to make the game fun to replay. There is a fixed number of enemies, and a fixed number of calls to `Random.*` during enemy-generation.

.NET 6 is released and the developer replaces `.Next(min, max)` calls with `.NextInt64(min, max)` in the next game release (whatever the reasons - ex. a larger range is required to improve enemy-generation logic). The generated game-world is now different (expected), but it is consistent (ie. the same world for each Seed).

And then the heisenbug reports start coming in - players report that on sporadic rare occasions the game-world is totally different. If players restart the game, the game-world is usually back to "normal/expected", until it gets screwed up again on some subsequent replay.

---
1. Is it the .NET team's decision to make the seeded `.NextInt64*` methods behave differently from `.Next*` methods in terms of fixed-vs-variable # of state-consumptions per API call?

	* The behavior discrepancy is material and will likely have real-usage consequences (we can all pedantically say *"..but we made no guarantees.."* - that does not change how developers use it and expect it to function based on observed and relied-upon behavior).
	* If "Yes", then it will be adding another real-world-usage problem to the long list of problems that seeded `System.Random` already has. Either way, the decision is explicit and well-considered.

2. If the answer to (1) is "Yes", does the .NET team believe that existing documentation is fine as is (ie. we will wish our hypothetical game-developer the best of luck figuring out wtf is going on)?

**Comment by stephentoub** [comment] 2021-09-01 15:23
> And then the heisenbug reports start coming in - players report that on sporadic rare occasions the game-world is totally different.

Can you please elaborate on this?  For a given seed, the values produced by a given sequence of NextInt64(min, max) calls will be deterministic and repeatable.  Your comment suggests you don't believe that to be true.

**Comment by sdrapkin** [comment] 2021-09-01 16:00
> Can you please elaborate on this?

Assume the following code-logic of our hypothetical game:
```csharp
// the one-and-only seeded Random
// seed is constant per game-level
var random = new Random(123);
const int ENEMIES = 20;
Enemy[] _enemies = new Enemy[ENEMIES];

// initialize enemies
for (int i = 0; i < ENEMIES; ++i)
{
	var enemy = new Enemy(
		strength: random.Next(Environment.TickCount),
		location: random.Next((int)DateTime.UtcNow.Ticks));
	_enemies[i] = enemy;
}

// generate game-world
{
	// call random.* APIs for all other world-objects (fixed parameters)
}
```

The parameters passed into `random.Next(max)` during enemy-initialization are variable. I am not saying this is great code, but this is realistic real-world code. 

The above will produce consistent world-generation with `random.Next*`, and sporadically inconsistent world-generation with `random.NextInt64*`.

The consistency of seeded `.Next*` (ie. fixed state-consumption behavior for ALL valid parameters) is as much of an expected and relied-upon behavior of legacy seeded `System.Random` as its seed-to-result mapping. If .NET team disagrees with this assertion, then consider at least documenting the behavior discrepancy.

We cannot address this by telling developers that they are bad developers writing bad code, nor can we even point to clear documentation explaining (a) what did the developer do wrong? (b) why did the behavior change from `.Next*` to `.NextInt64*`?

**Comment by tannergooding** [comment] 2021-09-01 16:03
I believe they are indicating that because `NextInt64` may require you to enumerate two pieces of state to ensure it is sufficiently random, replacing a call of `Next()` with a call to `NextInt64()` now changes the downstream results of other `Next()` calls and therefore "breaks" the determinism/reproducability.

In practice, however this was already possible for certain scenarios even on full framework. Simply try to use `Random.Next(int, int)` for any range that is more than `int.MaxValue` and it will pull 2 pieces of state to ensure the sample distribution is good enough: https://referencesource.microsoft.com/#mscorlib/system/random.cs,160

The user explicitly broke the "determinism" by change the sequence of random calls that otherwise had occurred.

**Comment by tannergooding** [comment] 2021-09-01 16:27
I'm not personally convinced that's necessary as that is already the definition of determinism.

Determinism is "for a set of constant inputs you will get a constant output". If you change the inputs or the actions performed, you are now doing something different.

If you insert an additional `Random` call or a different `Random` call, the downstream sequence can change. If you decide to change the maximum or minimum result, then the output can change.
Consider the case where you have some `rng.Next(256)` and it was returning exactly `255` at step `10`. You now change these calls to be `rng.Next(257)` because you realized its exclusive not inclusive. Because you are now including an additional `bit` in the output, the result returned may no longer be `255` (and based on the existing implementation will very likely actually be `256` since its implemented as `Sample() * maxValue`).

**Comment by tannergooding** [comment] 2021-09-01 16:28
Any change in the calls to some `random` instance can change the determinism of the outputs, whether that's the inputs, the methods invoked, or the order in which they are invoked.

**Comment by sdrapkin** [comment] 2021-09-01 16:35
@tannergooding What the current documentation does not allude to is that (N+1)th call to `.Next*` or `.NextInt64*` can return a different result depending on what parameters were passed into N-th call. **This is completely non-obvious.**

You reason by taking me to under-the-hood level of bits, calls to `Sample()`, max values, etc. As a consumer of .NET I don't need to know any of this. I only need to understand how to use the APIs provided, based on constraints that the documentation should clearly explain.

**Comment by jwosty** [comment] 2021-09-01 17:21
> 
> @tannergooding What the current documentation does not allude to is that (N+1)th call to `.Next*` or `.NextInt64*` can return a different result depending on what parameters were passed into N-th call. **This is completely non-obvious.**

Seems like this is really just undefined behavior then, not contradictory behavior. Potential courses of action:

1. Define the undefined behavior
2. Explicitly document that the behavior is undefined (instead of implicitly, by omitting documentation on this facet)
3. Do nothing and keep not mentioning this in the documentation (thus keeping it "undefined" by omission)

**Comment by stephentoub** [comment] 2021-09-01 18:02
The defined behavior is that the same seed with the same sequence of calls and the same inputs to those calls is deterministic and will produce the same results.  If the docs don't already, I'm fine with the docs being augmented to call that out and that changing any of those things can result in different output.  I'm surprised it's considered "completely non-obvious", but if changing the docs addresses the confusion, great.

**Comment by sdrapkin** [comment] 2021-09-01 18:21
It seems that the consensus is that updating the documentation to be explicit about what seeded invocation-conditions guarantee determinism **as well as** what invocation-conditions *do not* guarantee determinism will address this issue.

Can someone make it happen?

**Comment by tannergooding** [comment] 2021-09-01 18:41
The API docs are also open source and contributions are welcome: https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System/Random.xml

**Comment by tannergooding** [comment] 2021-09-07 16:23
Closing this as by-design. As indicated above doc contributions/improvements are welcome if you'd like to see this updated.

**Closed by tannergooding** 2021-09-07 16:23 UTC
Labels: area-System.Runtime
