### ISSUE TITLE
JsonIgnore attribute incompatible with .NET required keyword

### ISSUE THREAD

**Issue by el1b0t** [dotnet/runtime#110810] opened 2024-12-18 15:01 UTC
### Description

When using System.Text.Json.Serialization.JsonIgnoreAttribute on a property, it appears that the runtime ignores the flag if the keyword "required" is also used on the property. There are circumstances where a property should be able to be marked as both, I believe.

### Reproduction Steps

```
using System.Text.Json;
using System.Text.Json.Serialization;

namespace JsonBugMinimalApp;

class Program
{
    static void Main(string[] args)
    {
        try
        {
            Console.WriteLine(JsonSerializer.Serialize(new Contact() { Id = 1 }));
        }
        catch (Exception e)
        {
            Console.WriteLine(e.ToString());
        }
    }

    private class Contact
    {
        [JsonIgnore] public required int Id { get; set; }
    }
}
```

### Expected behavior

Console.WriteLine should produce: "{}"

### Actual behavior

Console.WriteLine produces: "System.InvalidOperationException: JsonPropertyInfo 'Id' defined in type 'JsonBugMinimalApp.Program+Contact' is marked required but does not specify a setter"

### Known Workarounds

Remove required keyword on property or use a constructor for setting properties that are desired to be required.

### Configuration

Version of .NET: 8
OS and version: Windows 11 Business (26100.2314)
Architecture: X64

**Comment by julealgon** [comment] 2024-12-18 15:13
> There are circumstances where a property should be able to be marked as both, I believe.

I don't see how this would apply for _deserialization_ though. If a property is `required`, the serializer would need the value to be able to build the type properly otherwise it would completely violate the intent of the keyword leading to all sorts of bugs.

For _serialization_ I could see this making much more sense, in case one just doesn't want that property to be in the output (although in this case then you wouldn't be able to deserialize back from that payload of course).

**Comment by el1b0t** [comment] 2024-12-18 15:46
To me, it feels like the JsonSerializer should give precedence to the JsonIgnore attribute and ignore the required keyword in the .NET framework, since required properties have many uses beyond potentially JSON. Perhaps it's just a misunderstanding on my part, though.

**Comment by gregsdennis** [comment] 2024-12-18 17:22
Maybe not an exact duplicate, but very related: https://github.com/dotnet/runtime/issues/110733

**Comment by eiriktsarpalis** [comment] 2024-12-18 17:22
It's a duplicate of #110733, what differs is the ignore condition.

**Closed by eiriktsarpalis** 2024-12-18 17:22 UTC
Labels: area-System.Text.Json, untriaged
