### ISSUE TITLE
Test failure System.Net.Sockets.Tests.DualModeConnectionlessReceiveMessageFrom.ReceiveMessageFromAsyncV4BoundToSpecificV4_Success

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#58482] opened 2021-09-01 02:03 UTC
Run: [runtime-libraries-coreclr outerloop 20210831.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1330895&view=ms.vss-test-web.build-test-results-tab&runId=39044190&resultId=102784&paneView=debug)

Failed test:
```
net6.0-Linux-Release-x64-CoreCLR_release-(Debian.11.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-11-helix-amd64-20210304164428-5a7c380

- System.Net.Sockets.Tests.DualModeConnectionlessReceiveMessageFrom.ReceiveMessageFromAsyncV4BoundToSpecificV4_Success

net6.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.Server19H1.Open

- System.Net.Sockets.Tests.DualModeConnectionlessReceiveFromAsync.ReceiveFromAsyncV4BoundToAnyV4_Success
- System.Net.Sockets.Tests.DualModeConnectionlessReceiveFromAsync.ReceiveFromAsyncV6BoundToSpecificV6_Success
- System.Net.Sockets.Tests.DualModeConnectionlessBeginReceiveFrom.BeginReceiveFromV6BoundToSpecificV6_Success
```
**Error message:**
```
System.TimeoutException : The operation has timed out.


Stack trace
   at System.Net.Sockets.Tests.DualModeConnectionlessReceiveMessageFrom.ReceiveMessageFromAsync_Helper(IPAddress listenOn, IPAddress connectTo, Boolean expectedToTimeout) in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 2381
   at System.Net.Sockets.Tests.DualModeConnectionlessReceiveMessageFrom.ReceiveMessageFromAsyncV4BoundToSpecificV4_Success() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 2282
```

Failed test:
```
net6.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.Server19H1.Open

- System.Net.Sockets.Tests.DnsEndPointTest.Socket_StaticConnectAsync_ConnectionRefused
- System.Net.Sockets.Tests.DnsEndPointTest.Socket_StaticConnectAsync_HostNotFound

net6.0-Linux-Release-arm64-CoreCLR_release-(Ubuntu.1804.ArmArch.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-helix-arm64v8-20210106155927-56c6673

- System.Net.Sockets.Tests.DnsEndPointTest.Socket_StaticConnectAsync_Success(type: APM)

```
**Error message:**
```
Timed out while waiting for connection
Expected: True
Actual:   False


Stack trace
   at System.Net.Sockets.Tests.DnsEndPointTest.Socket_StaticConnectAsync_ConnectionRefused() in /_/src/libraries/System.Net.Sockets/tests/FunctionalTests/DnsEndPointTest.cs:line 434
```

**Comment by karelz** [comment] 2021-09-01 09:55
Duplicate of #57937 and #21924

**Closed by karelz** 2021-09-01 09:55 UTC
Labels: area-System.Net.Sockets, os-linux, os-windows, arch-x64, untriaged
