### ISSUE TITLE
[wasm][tests][aot] System.Diagnostics.TraceSource.Tests failures

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#50958] opened 2021-04-08 20:36 UTC
[Logs](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48226-merge-76d6323478354200b5/System.Diagnostics.TraceSource.Tests/console.a03fdee4.log?sv=2019-07-07&se=2021-04-27T19%3A10%3A01Z&sr=c&sp=rl&sig=sD%2BRBEufPbrlRruQFK0D%2FkcngP%2Bdu6qiZlchrTM%2Fu10%3D)

```
[19:40:40] info: console.debug: mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
[19:40:40] info: console.info: Initializing.....
[19:40:40] info: Could not find constructor for 'Xunit.Sdk.CollectionPerAssemblyTestCollectionFactory' with arguments type(s): Xunit.Sdk.TestAssembly
[19:40:40] info: Discovering: System.Diagnostics.TraceSource.Tests.dll (method display = ClassAndMethod, method display options = None)
[19:40:40] info: Discovered:  System.Diagnostics.TraceSource.Tests.dll (found 259 of 259 test cases)
[19:40:40] info: Could not find constructor for 'Xunit.Sdk.CollectionPerAssemblyTestCollectionFactory' with arguments type(s): Xunit.Sdk.TestAssembly
[19:40:40] info: Starting:    System.Diagnostics.TraceSource.Tests.dll
[19:40:41] fail: [FAIL] System.Diagnostics.TraceSourceTests.TraceEventCacheClassTests.CallstackTest_NotEmpty
[19:40:41] info: Assert.NotEmpty() Failure
[19:40:41] info: 
[19:40:41] fail: [FAIL] System.Diagnostics.TraceSourceTests.TraceEventCacheClassTests.CallstackTest_ContainsExpectedFrames
[19:40:41] info: Assert.Contains() Failure
[19:40:41] info: Not found: System.Environment.get_StackTrace()
[19:40:41] info: In value:
[19:40:41] info: 
[19:40:41] fail: [FAIL] System.Diagnostics.TraceSourceTests.TraceListenerClassTests.WriteFooterTest_Callstack
[19:40:41] info: Assert.Contains() Failure
[19:40:41] info: Not found: WriteFooterTest_Callstack
[19:40:41] info: In value:  Source Critical: 42 :
[19:40:41] info:     Callstack=
[19:40:41] info: 
[19:40:41] info: 
[19:40:41] info: Finished:    System.Diagnostics.TraceSource.Tests.dll
```

**Comment by BrzVlad** [comment] 2021-05-07 14:07
Duplicate of https://github.com/dotnet/runtime/issues/50957

**Closed by BrzVlad** 2021-05-07 14:07 UTC
Labels: arch-wasm, area-Codegen-AOT-mono, untriaged, wasm-aot-test
