### ISSUE TITLE
Test failure readytorun/r2rdump/FrameworkTests/R2RDumpTests/R2RDumpTests.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#54200] opened 2021-06-15 01:35 UTC
Run: [runtime-coreclr jitstress 20210613.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1185650&view=ms.vss-test-web.build-test-results-tab&runId=35638988&resultId=109505&paneView=debug)

Failed test:
```
CoreCLR OSX arm64 Checked jitminopts @ OSX.1100.ARM64.Open

- readytorun/r2rdump/FrameworkTests/R2RDumpTests/R2RDumpTests.sh

```
**Error message:**
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.CSharp.RuntimeBinder.Semantics.TypeTable.KeyPair2.Equals(KeyPair2 other) in Microsoft.CSharp.dll:token 0x6000664+0x0
at Microsoft.CSharp.RuntimeBinder.Semantics.TypeTable.KeyPair2.Equals(KeyPair2 other) in Microsoft.CSharp.dll:token 0x6000664+0x18
at System.Collections.Generic.Dictionary2.FindValue(TKey key) in System.Private.CoreLib.dll:token 0x6006279+0x84 at System.Collections.Generic.Dictionary2.TryGetValue(TKey key, TValue& value) in System.Private.CoreLib.dll:token 0x6006281+0x0
at Microsoft.CSharp.RuntimeBinder.Semantics.TypeTable.LookupAggregate(AggregateSymbol aggregate, AggregateType outer, TypeArray args) in Microsoft.CSharp.dll:token 0x6000658+0x0
at Microsoft.CSharp.RuntimeBinder.Semantics.TypeManager.GetAggregate(AggregateSymbol agg, AggregateType atsOuter, TypeArray typeArgs) in Microsoft.CSharp.dll:token 0x600061e+0xa
at Microsoft.CSharp.RuntimeBinder.Semantics.TypeManager.GetAggregate(AggregateSymbol agg, TypeArray typeArgsAll) in Microsoft.CSharp.dll:token 0x600061f+0x19
at Microsoft.CSharp.RuntimeBinder.SymbolTable.GetConstructedType(Type type, AggregateSymbol agg) in Microsoft.CSharp.dll:token 0x6000198+0x49
at Microsoft.CSharp.RuntimeBinder.SymbolTable.LoadSymbolsFromType(Type type) in Microsoft.CSharp.dll:token 0x6000196+0x86
at Microsoft.CSharp.RuntimeBinder.SymbolTable.GetCTypeFromType(Type type) in Microsoft.CSharp.dll:token 0x600019e+0x8
at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.CreateLocal(Type type, Boolean isOut, LocalVariableSymbol local) in Microsoft.CSharp.dll:token 0x600015e+0x17
at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.CreateArgumentEXPR(ArgumentObject argument, LocalVariableSymbol local) in Microsoft.CSharp.dll:token 0x6000160+0x81
at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.CreateArgumentListEXPR(ArgumentObject[] arguments, LocalVariableSymbol[] locals, Int32 startIndex, Int32 endIndex) in Microsoft.CSharp.dll:token 0x600015f+0x13
at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.BindCall(ICSharpInvokeOrInvokeMemberBinder payload, Expr callingObject, ArgumentObject[] arguments, LocalVariableSymbol[] locals) in Microsoft.CSharp.dll:token 0x6000167+0x211
at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.DispatchPayload(ICSharpInvokeOrInvokeMemberBinder payload, ArgumentObject[] arguments, LocalVariableSymbol[] locals) in Microsoft.CSharp.dll:token 0x600015b+0x0
at Microsoft.CSharp.RuntimeBinder.CSharpInvokeMemberBinder.DispatchPayload(RuntimeBinder runtimeBinder, ArgumentObject[] arguments, LocalVariableSymbol[] locals) in Microsoft.CSharp.dll:token 0x60000cf+0x0
at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.BindCore(ICSharpBinder payload, Expression[] parameters, DynamicMetaObject[] args, DynamicMetaObject& deferredBinding) in Microsoft.CSharp.dll:token 0x6000154+0x43
at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.Bind(ICSharpBinder payload, Expression[] parameters, DynamicMetaObject[] args, DynamicMetaObject& deferredBinding) in Microsoft.CSharp.dll:token 0x6000153+0x10
at Microsoft.CSharp.RuntimeBinder.BinderHelper.Bind(ICSharpBinder action, RuntimeBinder binder, DynamicMetaObject[] args, IEnumerable`1 arginfos, DynamicMetaObject onBindingError) in Microsoft.CSharp.dll:token 0x6000065+0x1ea
at Microsoft.CSharp.RuntimeBinder.CSharpInvokeMemberBinder.FallbackInvokeMember(DynamicMetaObject target, DynamicMetaObject[] args, DynamicMetaObject errorSuggestion) in Microsoft.CSharp.dll:token 0x60000dc+0x1c
at System.Dynamic.InvokeMemberBinder.FallbackInvokeMember(DynamicMetaObject target, DynamicMetaObject[] args) in System.Linq.Expressions.dll:token 0x60011d0+0x0
at System.Dynamic.DynamicMetaObject.BindInvokeMember(InvokeMemberBinder binder, DynamicMetaObject[] args) in System.Linq.Expressions.dll:token 0x60010a1+0xb
at System.Dynamic.InvokeMemberBinder.Bind(DynamicMetaObject target, Dynamic


Stack trace
   at readytorun_r2rdump._FrameworkTests_R2RDumpTests_R2RDumpTests_._FrameworkTests_R2RDumpTests_R2RDumpTests_sh() in readytorun.r2rdump.XUnitWrapper.dll:token 0x6000004+0x295
```

**Comment by VincentBu** [comment] 2021-06-15 01:36
Historical failures of this test:

Queued | OS | Arch | Pipeline
-- | -- | -- | --
2021-06-14T06:08:36.668Z | osx.1100.arm64.open | arm64 | [runtime-coreclr r2r-extra   Checked-jitminopts](https://dev.azure.com/dnceng/public/_build/results?buildId=1185607&amp;view=ms.vss-test-web.build-test-results-tab&amp;runId=35639552&amp;resultId=109492&amp;paneView=debug)
2021-06-14T05:18:22.845Z | osx.1100.arm64.open | arm64 | [runtime-coreclr jitstress   Checked-jitminopts](https://dev.azure.com/dnceng/public/_build/results?buildId=1185650&amp;view=ms.vss-test-web.build-test-results-tab&amp;runId=35638988&amp;resultId=109505&amp;paneView=debug)
2021-06-13T06:20:51.202Z | osx.1100.arm64.open | arm64 | [runtime-coreclr r2r-extra   Checked-jitminopts](https://dev.azure.com/dnceng/public/_build/results?buildId=1185015&amp;view=ms.vss-test-web.build-test-results-tab&amp;runId=35627768&amp;resultId=109038&amp;paneView=debug)
2021-06-13T05:18:22.819Z | osx.1100.arm64.open | arm64 | [runtime-coreclr jitstress   Checked-jitminopts](https://dev.azure.com/dnceng/public/_build/results?buildId=1185075&amp;view=ms.vss-test-web.build-test-results-tab&amp;runId=35626830&amp;resultId=109505&amp;paneView=debug)
2021-06-12T05:17:46.126Z | osx.1100.arm64.open | arm64 | [runtime-coreclr jitstress   Checked-jitminopts](https://dev.azure.com/dnceng/public/_build/results?buildId=1184361&amp;view=ms.vss-test-web.build-test-results-tab&amp;runId=35611300&amp;resultId=109505&amp;paneView=debug)

**Comment by BruceForstall** [comment] 2021-06-21 20:44
Another failure: https://dev.azure.com/dnceng/public/_build/results?buildId=1196845&view=ms.vss-test-web.build-test-results-tab&runId=35886886&resultId=109506&paneView=debug

**Comment by BruceForstall** [comment] 2021-06-21 20:44
@dotnet/crossgen-contrib

**Comment by BruceForstall** [comment] 2021-06-22 06:24
Also @sandreenko . Only happens with JITMinOpts on macOS arm64

**Comment by VincentBu** [comment] 2021-06-28 01:35
Failed again in [runtime-coreclr jitstress 20210626.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1208102&view=ms.vss-test-web.build-test-results-tab&runId=36128132&resultId=109511&paneView=debug)

Failed test:
```
CoreCLR OSX arm64 Checked jitminopts @ OSX.1100.ARM64.Open

- readytorun/r2rdump/FrameworkTests/R2RDumpTests/R2RDumpTests.sh

```
**Error message:**
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.CSharp.RuntimeBinder.Semantics.TypeTable.KeyPair2.Equals(KeyPair2 other) in Microsoft.CSharp.dll:token 0x6000664+0x0
at Microsoft.CSharp.RuntimeBinder.Semantics.TypeTable.KeyPair2.Equals(KeyPair2 other) in Microsoft.CSharp.dll:token 0x6000664+0x18
at System.Collections.Generic.Dictionary2.FindValue(TKey key) in System.Private.CoreLib.dll:token 0x6006279+0x84 at System.Collections.Generic.Dictionary2.TryGetValue(TKey key, TValue& value) in System.Private.CoreLib.dll:token 0x6006281+0x0
at Microsoft.CSharp.RuntimeBinder.Semantics.TypeTable.LookupAggregate(AggregateSymbol aggregate, AggregateType outer, TypeArray args) in Microsoft.CSharp.dll:token 0x6000658+0x0
at Microsoft.CSharp.RuntimeBinder.Semantics.TypeManager.GetAggregate(AggregateSymbol agg, AggregateType atsOuter, TypeArray typeArgs) in Microsoft.CSharp.dll:token 0x600061e+0xa
at Microsoft.CSharp.RuntimeBinder.Semantics.TypeManager.GetAggregate(AggregateSymbol agg, TypeArray typeArgsAll) in Microsoft.CSharp.dll:token 0x600061f+0x19
at Microsoft.CSharp.RuntimeBinder.SymbolTable.GetConstructedType(Type type, AggregateSymbol agg) in Microsoft.CSharp.dll:token 0x6000198+0x49
at Microsoft.CSharp.RuntimeBinder.SymbolTable.LoadSymbolsFromType(Type type) in Microsoft.CSharp.dll:token 0x6000196+0x86
at Microsoft.CSharp.RuntimeBinder.SymbolTable.GetCTypeFromType(Type type) in Microsoft.CSharp.dll:token 0x600019e+0x8
at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.CreateLocal(Type type, Boolean isOut, LocalVariableSymbol local) in Microsoft.CSharp.dll:token 0x600015e+0x17
at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.CreateArgumentEXPR(ArgumentObject argument, LocalVariableSymbol local) in Microsoft.CSharp.dll:token 0x6000160+0x81
at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.CreateArgumentListEXPR(ArgumentObject[] arguments, LocalVariableSymbol[] locals, Int32 startIndex, Int32 endIndex) in Microsoft.CSharp.dll:token 0x600015f+0x13
at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.BindCall(ICSharpInvokeOrInvokeMemberBinder payload, Expr callingObject, ArgumentObject[] arguments, LocalVariableSymbol[] locals) in Microsoft.CSharp.dll:token 0x6000167+0x211
at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.DispatchPayload(ICSharpInvokeOrInvokeMemberBinder payload, ArgumentObject[] arguments, LocalVariableSymbol[] locals) in Microsoft.CSharp.dll:token 0x600015b+0x0
at Microsoft.CSharp.RuntimeBinder.CSharpInvokeMemberBinder.DispatchPayload(RuntimeBinder runtimeBinder, ArgumentObject[] arguments, LocalVariableSymbol[] locals) in Microsoft.CSharp.dll:token 0x60000cf+0x0
at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.BindCore(ICSharpBinder payload, Expression[] parameters, DynamicMetaObject[] args, DynamicMetaObject& deferredBinding) in Microsoft.CSharp.dll:token 0x6000154+0x43
at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.Bind(ICSharpBinder payload, Expression[] parameters, DynamicMetaObject[] args, DynamicMetaObject& deferredBinding) in Microsoft.CSharp.dll:token 0x6000153+0x10
at Microsoft.CSharp.RuntimeBinder.BinderHelper.Bind(ICSharpBinder action, RuntimeBinder binder, DynamicMetaObject[] args, IEnumerable`1 arginfos, DynamicMetaObject onBindingError) in Microsoft.CSharp.dll:token 0x6000065+0x1ea
at Microsoft.CSharp.RuntimeBinder.CSharpInvokeMemberBinder.FallbackInvokeMember(DynamicMetaObject target, DynamicMetaObject[] args, DynamicMetaObject errorSuggestion) in Microsoft.CSharp.dll:token 0x60000dc+0x1c
at System.Dynamic.InvokeMemberBinder.FallbackInvokeMember(DynamicMetaObject target, DynamicMetaObject[] args) in System.Linq.Expressions.dll:token 0x60011d0+0x0
at System.Dynamic.DynamicMetaObject.BindInvokeMember(InvokeMemberBinder binder, DynamicMetaObject[] args) in System.Linq.Expressions.dll:token 0x60010a1+0xb
at System.Dynamic.InvokeMemberBinder.Bind(DynamicMetaObject target, Dynamic


Stack trace
   at readytorun_r2rdump._FrameworkTests_R2RDumpTests_R2RDumpTests_._FrameworkTests_R2RDumpTests_R2RDumpTests_sh() in readytorun.r2rdump.XUnitWrapper.dll:token 0x6000004+0x295
```
Historical failures of this test has updated in this [comment](https://github.com/dotnet/runtime/issues/54200#issuecomment-861104590)

**Comment by mangod9** [comment] 2021-07-20 02:11
Dupe of #51250

**Closed by mangod9** 2021-07-20 02:11 UTC
Labels: JitStress, arch-arm64, area-R2RDump-coreclr, blocking-outerloop, os-mac-os-x, untriaged
