### ISSUE TITLE
[API Proposal]: Default Constructor for String

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#72468] opened 2022-07-19 16:33 UTC
### Background and motivation

When interconnecting with different systems, four main data types are used as IDs:
```int``` (struct)
```long``` (struct)
```guid``` (struct)
```string``` (class)

Creating classes like this:
```
public class MyBase<TKey> {
  public TKey Id {get; set;}
}
```
is not nullable friendly because ```TKey``` could be null.

It would be nice if I could simply add a ```where TKey : new()``` constraint to get a nice, non-nullable key.

### API Proposal

```csharp
namespace System;

public class String
{
public String() { }
}
```

### API Usage

```csharp
var c = new String();
```

### Alternative Designs

I could create a static helper method that would return ```default(TKey)``` or string.Empty based on the TKey type.

**Comment by jkotas** [comment] 2022-07-19 16:43
Duplicate of https://github.com/dotnet/runtime/issues/64714

**Comment by GrabYourPitchforks** [comment] 2022-07-19 16:44
Relying on `new` seems like a code smell, even for _int_ / _long_ / _Guid_. Calling the parameterless ctor on these types isn't meaningful. It just returns the equivalent of `default(T)`, which isn't really useful as a key in your database.

What exactly are you trying to do?

**Closed** 2022-07-19 16:44 UTC
Labels: api-suggestion
