### ISSUE TITLE
DI, AddHttpClient: configured HttpClient not resolved when registered in wrong order

### ISSUE THREAD

**Issue by dweggemans** [dotnet/runtime#71197] opened 2022-06-23 10:34 UTC
### Description

It seems the order of registration matters when adding a typed HttpClient and consumer to the DI. 
Calling AddHttpClient before registering the dependent class results in a default HttpClient instance being injected.
Calling AddHttpClient after registering the dependent class result in the configured HttpClient being injected.

### Reproduction Steps

```csharp
[TestFixture]
    class AddHttpClient_registration_order_matters
    {
        [Test]
        public void Resolve_configured_http_client_when_http_client_is_added_last()
        {
            var services = new ServiceCollection();

            services.AddTransient<IDependency, Dependency>();
            services.AddTransient<Consumer>();
            services.AddHttpClient<IDependency, Dependency>(client =>
            {
                client.BaseAddress = new Uri("http://microsoft.com");
            });

            var provider = services.BuildServiceProvider();


            var consumer = provider.GetRequiredService<Consumer>();
        }

        [Test]
        public void Resolve_configured_http_client_when_http_client_is_added_first()
        {
            var services = new ServiceCollection();

            services.AddHttpClient<IDependency, Dependency>(client =>
            {
                client.BaseAddress = new Uri("http://microsoft.com");
            });
            services.AddTransient<IDependency, Dependency>();
            services.AddTransient<Consumer>();

            var provider = services.BuildServiceProvider();


            //This fails because the default HttpClient is injected instead of the configured one
            var consumer = provider.GetRequiredService<Consumer>();
        }

        class Consumer
        {
            public Consumer(IDependency dependency)
            {
            }
        }

        interface IDependency { }

        class Dependency : IDependency
        {
            public Dependency(HttpClient httpClient)
            {
                if (httpClient.BaseAddress == null) throw new ArgumentException(nameof(httpClient));
            }
        }
    }
```

### Expected behavior

DI should inject the configured HttpClient in both cases.

### Actual behavior

Calling AddHttpClient before registering the dependent class results in a **default** HttpClient instance being injected.
Calling AddHttpClient after registering the dependent class result in the configured HttpClient being injected.

### Configuration

6.0.4 on windows

**Comment by CarnaViire** [comment] 2022-06-23 15:08
@dweggemans you don't need to separately register your `IDependency` -- `AddHttpClient` already does that for you. You should *remove* this line:

```c#
services.AddTransient<IDependency, Dependency>();
```

By design of DI, whatever is added last via `AddTransient`/`AddSingleton` etc, will *override* the previous registration on the *same* interface. This is what you see as you essentially register your `IDependency` twice.

Thanks! Closing as everything works as expected.

**Closed by CarnaViire** 2022-06-23 15:08 UTC
Labels: untriaged, area-Extensions-HttpClientFactory
