### ISSUE TITLE
Each parameter in the deserialization constructor on type 'SpeechCreatedEvent' must bind to an object property or field on deserialization. Each parameter name must match with a property or field on the object. The match can be case-insensitive.'

### ISSUE THREAD

**Issue by logcorner** [dotnet/runtime#69547] opened 2022-05-19 09:34 UTC
Hi I'm migrating from newtonsoft.json to System.Text.Json using .NET6 I have an issues when deserializing json string into object.

The error message is  Each parameter in the deserialization constructor on type 'SpeechCreatedEvent' must bind to an object property or field on deserialization. Each parameter name must match with a property or field on the object. The match can be case-insensitive.'

You can find the sample code in the following repository https://github.com/logcorner/DotNetJsonSerilizer

It works fine with newtonsoft.json but raise an exception when using System.Text.Json
` JsonSerializerOptions settings = new JsonSerializerOptions
            {
                IncludeFields = true
            };
            var result = (TEvent)JsonSerializer.Deserialize(serializedEvent, Type.GetType(eventType), settings);`

With Newtonsoft.Json I have implemented a DefaultContractResolver as following 
` private class PrivateSetterContractResolver : DefaultContractResolver
        {
            protected override JsonProperty CreateProperty(
                MemberInfo member,
                MemberSerialization memberSerialization)
            {
                var prop = base.CreateProperty(member, memberSerialization);
                if (!prop.Writable)
                {
                    var property = member as PropertyInfo;
                    if (property != null)
                    {
                        var hasPrivateSetter = property.GetSetMethod(true) != null;
                        prop.Writable = hasPrivateSetter;
                    }
                }
                return prop;
            }
        }`

Do I need to implement a JsonConverter with System.Text.Json ? 
Regards

**Comment by eiriktsarpalis** [comment] 2022-05-19 09:48
Hi, we plan to support custom contract resolution in .NET 7 via https://github.com/dotnet/runtime/issues/63686. Until then, it won't be possible to modify the list of serializable properties I'm afraid.

Duplicate of #63686

**Closed by eiriktsarpalis** 2022-05-19 09:48 UTC
Labels: question, area-System.Text.Json

**Comment by logcorner** [comment] 2022-05-19 09:54
So I'm suspending the migration for now.

I can't use System.Text.Json if I can't deserialize complex types.

I would like this feature to be implemented soon
Regard

**Comment by danmoseley** [comment] 2022-05-19 10:52
https://github.com/dotnet/runtime/issues/43563
