### ISSUE TITLE
Regression in System.Buffers.Tests.RentReturnArrayPoolTests

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#31448] opened 2019-11-08 22:49 UTC
The following ArrayPool tests have all regressed from 3.0 -> 3.1
`System.Buffers.Tests.RentReturnArrayPoolTests<Byte>.SingleSerial(RentalSize: 4096, ManipulateArray:`
![image](https://user-images.githubusercontent.com/9439069/68515568-583b6b00-0236-11ea-8be6-da7ae4d52a0e.png)
`System.Buffers.Tests.RentReturnArrayPoolTests<Object>.MultipleSerial(RentalSize: 4096, ManipulateArr`
![image](https://user-images.githubusercontent.com/9439069/68515604-6e492b80-0236-11ea-9c2a-9657640be0c9.png)
`System.Buffers.Tests.RentReturnArrayPoolTests<Byte>.SingleSerial(RentalSize: 4096, ManipulateArray:`
![image](https://user-images.githubusercontent.com/9439069/68515632-83be5580-0236-11ea-8fbd-dff9cdc4a3f2.png)
`System.Buffers.Tests.RentReturnArrayPoolTests<Byte>.ProducerConsumer(RentalSize: 4096, ManipulateArr`
![image](https://user-images.githubusercontent.com/9439069/68515644-8de05400-0236-11ea-8311-e7c4d53b9e5d.png)
`System.Buffers.Tests.RentReturnArrayPoolTests<Byte>.MultipleSerial(RentalSize: 4096, ManipulateArray`
![image](https://user-images.githubusercontent.com/9439069/68515661-a3ee1480-0236-11ea-8df3-8823e6c9ec28.png)
`System.Buffers.Tests.RentReturnArrayPoolTests<Byte>.SingleSerial(RentalSize: 4096, ManipulateArray:`
![image](https://user-images.githubusercontent.com/9439069/68515706-b6684e00-0236-11ea-9f8e-48df08b7096c.png)
`System.Buffers.Tests.RentReturnArrayPoolTests<Byte>.ProducerConsumer(RentalSize: 4096, ManipulateArr`
![image](https://user-images.githubusercontent.com/9439069/68515721-c08a4c80-0236-11ea-851b-2b2bee79e456.png)
`System.Buffers.Tests.RentReturnArrayPoolTests<Object>.SingleParallel(RentalSize: 4096, ManipulateArr`
![image](https://user-images.githubusercontent.com/9439069/68515747-cc760e80-0236-11ea-8b9f-4519d5f878d0.png)
`System.Buffers.Tests.RentReturnArrayPoolTests<Object>.MultipleSerial(RentalSize: 4096, ManipulateArr`
![image](https://user-images.githubusercontent.com/9439069/68515759-d730a380-0236-11ea-84f9-0e9029afae9d.png)

**Comment by adamsitnik** [comment] 2020-08-12 10:44
I was not able to reproduce this regression, 5.0 is same as 3.1 and slighly faster than 2.1. Closing

**Comment by adamsitnik** [comment] 2020-08-12 10:44
I forgot to share the numbers....


 BenchmarkDotNet=v0.12.1.1405-nightly, OS=Windows 10.0.18363.959 (1909/November2019Update/19H2)
 Intel Xeon CPU E5-1650 v4 3.60GHz, 1 CPU, 12 logical and 6 physical cores
 .NET Core SDK=5.0.100-rc.1.20411.10
   [Host]     : .NET Core 2.1.11 (CoreCLR 4.6.27617.04, CoreFX 4.6.27617.02), X64 RyuJIT
   Job-HVDWYH : .NET Core 2.1.11 (CoreCLR 4.6.27617.04, CoreFX 4.6.27617.02), X64 RyuJIT


 |       Method | RentalSize | ManipulateArray | Async | UseSharedPool |        Mean |     Error |    StdDev |      Median |         Min |         Max |  Gen 0 | Gen 1 | Gen 2 | Allocated |
 |------------- |----------- |---------------- |------ |-------------- |------------:|----------:|----------:|------------:|------------:|------------:|-------:|------:|------:|----------:|
 | SingleSerial |       4096 |           False | False |         False |    42.05 ns |  0.688 ns |  0.574 ns |    41.96 ns |    41.35 ns |    43.51 ns |      - |     - |     - |         - |
 | SingleSerial |       4096 |           False | False |          True |    35.22 ns |  0.274 ns |  0.256 ns |    35.23 ns |    34.86 ns |    35.56 ns |      - |     - |     - |         - |
 | SingleSerial |       4096 |           False |  True |         False |   969.03 ns |  1.461 ns |  1.220 ns |   968.66 ns |   967.61 ns |   971.19 ns | 0.0050 |     - |     - |         - |
 | SingleSerial |       4096 |           False |  True |          True |   977.72 ns |  2.822 ns |  2.501 ns |   978.07 ns |   973.84 ns |   981.48 ns | 0.0050 |     - |     - |         - |
 | SingleSerial |       4096 |            True | False |         False | 1,762.72 ns |  9.768 ns |  7.626 ns | 1,764.96 ns | 1,741.28 ns | 1,770.67 ns |      - |     - |     - |         - |
 | SingleSerial |       4096 |            True | False |          True | 1,743.25 ns | 19.042 ns | 17.812 ns | 1,747.08 ns | 1,706.94 ns | 1,759.43 ns |      - |     - |     - |         - |
 | SingleSerial |       4096 |            True |  True |         False | 2,356.34 ns | 37.708 ns | 35.272 ns | 2,349.42 ns | 2,309.05 ns | 2,430.44 ns |      - |     - |     - |         - |
 | SingleSerial |       4096 |            True |  True |          True | 2,360.51 ns | 27.896 ns | 26.094 ns | 2,357.62 ns | 2,321.35 ns | 2,418.40 ns |      - |     - |     - |         - |


 BenchmarkDotNet=v0.12.1.1405-nightly, OS=Windows 10.0.18363.959 (1909/November2019Update/19H2)
 Intel Xeon CPU E5-1650 v4 3.60GHz, 1 CPU, 12 logical and 6 physical cores
 .NET Core SDK=5.0.100-rc.1.20411.10
   [Host]     : .NET Core 3.1.6 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.31603), X64 RyuJIT
   Job-YBVNEZ : .NET Core 3.1.6 (CoreCLR 4.700.20.26901, CoreFX 4.700.20.31603), X64 RyuJIT


 |       Method | RentalSize | ManipulateArray | Async | UseSharedPool |        Mean |     Error |    StdDev |      Median |         Min |         Max | Gen 0 | Gen 1 | Gen 2 | Allocated |
 |------------- |----------- |---------------- |------ |-------------- |------------:|----------:|----------:|------------:|------------:|------------:|------:|------:|------:|----------:|
 | SingleSerial |       4096 |           False | False |         False |    39.22 ns |  0.591 ns |  0.462 ns |    39.41 ns |    38.38 ns |    39.79 ns |     - |     - |     - |         - |
 | SingleSerial |       4096 |           False | False |          True |    31.27 ns |  0.504 ns |  0.472 ns |    31.32 ns |    30.56 ns |    31.91 ns |     - |     - |     - |         - |
 | SingleSerial |       4096 |           False |  True |         False |   903.13 ns |  3.118 ns |  2.917 ns |   904.08 ns |   893.97 ns |   906.48 ns |     - |     - |     - |         - |
 | SingleSerial |       4096 |           False |  True |          True |   895.64 ns |  2.213 ns |  2.070 ns |   896.27 ns |   890.60 ns |   897.95 ns |     - |     - |     - |         - |
 | SingleSerial |       4096 |            True | False |         False | 1,733.62 ns |  2.444 ns |  2.041 ns | 1,733.48 ns | 1,730.30 ns | 1,736.71 ns |     - |     - |     - |         - |
 | SingleSerial |       4096 |            True | False |          True | 1,716.88 ns | 38.262 ns | 42.528 ns | 1,724.65 ns | 1,544.32 ns | 1,741.00 ns |     - |     - |     - |         - |
 | SingleSerial |       4096 |            True |  True |         False | 2,259.99 ns | 33.670 ns | 29.847 ns | 2,255.80 ns | 2,223.73 ns | 2,319.49 ns |     - |     - |     - |         - |
 | SingleSerial |       4096 |            True |  True |          True | 2,228.76 ns | 31.270 ns | 29.250 ns | 2,240.60 ns | 2,188.43 ns | 2,269.29 ns |     - |     - |     - |         - |



 BenchmarkDotNet=v0.12.1.1405-nightly, OS=Windows 10.0.18363.959 (1909/November2019Update/19H2)
 Intel Xeon CPU E5-1650 v4 3.60GHz, 1 CPU, 12 logical and 6 physical cores
 .NET Core SDK=5.0.100-rc.1.20411.10
   [Host]     : .NET Core 5.0.0 (CoreCLR 5.0.20.40416, CoreFX 5.0.20.40416), X64 RyuJIT
   Job-NJRRAP : .NET Core 5.0.0 (CoreCLR 5.0.20.40416, CoreFX 5.0.20.40416), X64 RyuJIT


 |       Method | RentalSize | ManipulateArray | Async | UseSharedPool |        Mean |     Error |    StdDev |      Median |         Min |         Max | Gen 0 | Gen 1 | Gen 2 | Allocated |
 |------------- |----------- |---------------- |------ |-------------- |------------:|----------:|----------:|------------:|------------:|------------:|------:|------:|------:|----------:|
 | SingleSerial |       4096 |           False | False |         False |    36.59 ns |  0.459 ns |  0.407 ns |    36.68 ns |    35.85 ns |    37.09 ns |     - |     - |     - |         - |
 | SingleSerial |       4096 |           False | False |          True |    26.53 ns |  0.102 ns |  0.095 ns |    26.54 ns |    26.38 ns |    26.69 ns |     - |     - |     - |         - |
 | SingleSerial |       4096 |           False |  True |         False |   901.56 ns |  7.801 ns |  7.297 ns |   904.92 ns |   883.48 ns |   908.26 ns |     - |     - |     - |         - |
 | SingleSerial |       4096 |           False |  True |          True |   900.61 ns |  3.191 ns |  2.985 ns |   901.43 ns |   892.57 ns |   904.13 ns |     - |     - |     - |         - |
 | SingleSerial |       4096 |            True | False |         False | 1,728.09 ns | 26.150 ns | 23.181 ns | 1,731.29 ns | 1,698.50 ns | 1,777.46 ns |     - |     - |     - |         - |
 | SingleSerial |       4096 |            True | False |          True | 1,720.18 ns |  2.415 ns |  2.259 ns | 1,720.88 ns | 1,716.25 ns | 1,722.80 ns |     - |     - |     - |         - |
 | SingleSerial |       4096 |            True |  True |         False | 2,241.87 ns | 15.515 ns | 13.754 ns | 2,244.24 ns | 2,216.50 ns | 2,264.94 ns |     - |     - |     - |         - |
 | SingleSerial |       4096 |            True |  True |          True | 2,215.86 ns | 20.589 ns | 19.259 ns | 2,219.94 ns | 2,188.13 ns | 2,242.81 ns |     - |     - |     - |         - |

**Closed by adamsitnik** 2020-08-12 10:44 UTC
Labels: area-System.Buffers, tenet-performance-benchmarks
