### ISSUE TITLE
Test failure profiler\\gc\\gc\\gc.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#67826] opened 2022-04-11 01:26 UTC
Run: [runtime-coreclr jitstress2-jitstressregs 20220410.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1709799&view=ms.vss-test-web.build-test-results-tab&runId=46509850&paneView=debug&resultId=101149)

Failed test:
```
coreclr windows x64 Checked jitstress2_jitstressregs0x10 @ Windows.10.Amd64.Open

- profiler\\gc\\gc\\gc.cmd

```
**Error message:**
```
Assert failure(PID 3060 [0x00000bf4], Thread: 7736 [0x1e38]): CONTRACT VIOLATION by SimpleRWLock::TryEnterRead at "D:\a_work\1\s\src\coreclr\vm\simplerwlock.cpp" @ 27

CAN_TAKE_LOCK called in a CANNOT_TAKE_LOCK region.

                    CONTRACT in VirtualCallStubManager::FindStubManager at "D:\a\_work\1\s\src\coreclr\vm\virtualcallstub.cpp" @ 969
                    GCX_NOTRIGGER in CLRVectoredExceptionHandlerPhase3 at "D:\a\_work\1\s\src\coreclr\vm\excep.cpp" @ 7489
VIOLATED-->  CONTRACT in ProfToEEInterfaceImpl::GetObjectGeneration at "D:\a_work\1\s\src\coreclr\vm\proftoeeinterfaceimpl.cpp" @ 9000
CONTRACT in EEToProfInterfaceImpl::GarbageCollectionFinished at "D:\a_work\1\s\src\coreclr\vm\eetoprofinterfaceimpl.cpp" @ 5889
CONTRACT in GarbageCollectionFinishedCallback at "D:\a_work\1\s\src\coreclr\vm\proftoeeinterfaceimpl.cpp" @ 693
GCX_COOP in GCInterface_Collect at "D:\a_work\1\s\src\coreclr\vm\comutilnative.cpp" @ 1006
CONTRACT in GCInterface_Collect at "D:\a_work\1\s\src\coreclr\vm\comutilnative.cpp" @ 997
CONTRACT in MethodDescCallSite::CallTargetWorker at "D:\a_work\1\s\src\coreclr\vm\callhelpers.cpp" @ 280
GCX_COOP in Assembly::ExecuteMainMethod at "D:\a_work\1\s\src\coreclr\vm\assembly.cpp" @ 1570
CONTRACT in Assembly::ExecuteMainMethod at "D:\a_work\1\s\src\coreclr\vm\assembly.cpp" @ 1554
GCX_COOP in CorHost2::ExecuteAssembly at "D:\a_work\1\s\src\coreclr\vm\corhost.cpp" @ 357
CONTRACT in CorHost2::ExecuteAssembly at "D:\a_work\1\s\src\coreclr\vm\corhost.cpp" @ 306

CORECLR! CONTRACT_ASSERT + 0x307 (0x00007ffb975d2f17) CORECLR! ClrDebugState::LockTaken + 0x76 (0x00007ffb976c1396)
CORECLR! SimpleRWLock::TryEnterRead + 0xB0 (0x00007ffb97b514f0) CORECLR! SimpleRWLock::EnterRead + 0xA2 (0x00007ffb97b50fc2)
CORECLR! LockedRangeList::IsInRangeWorker + 0x3D (0x00007ffb975e657d) CORECLR! VirtualCallStubManager::getStubKind + 0x103 (0x00007ffb9779bc73)
CORECLR! VirtualCallStubManager::FindStubManager + 0x116 (0x00007ffb978c9f86) CORECLR! AdjustContextForVirtualStub + 0x53 (0x00007ffb97cd6243)
CORECLR! CLRVectoredExceptionHandlerPhase3 + 0x2CF (0x00007ffb976fb1cf) CORECLR! CLRVectoredExceptionHandlerPhase2 + 0x91 (0x00007ffb976fac91)
File: D:\a_work\1\s\src\coreclr\vm\simplerwlock.cpp Line: 27
Image: C:\h\w\B59D09E6\p\CoreRun.exe

Unhandled exception. System.Exception: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler implementation. This text was not found in the output above.
at Profiler.Tests.ProfilerTestRunner.Run(String profileePath, String testName, Guid profilerClsid, String profileeArguments, ProfileeOptions profileeOptions, Dictionary`2 envVars, String reverseServerName, Boolean loadAsNotification, Int32 notificationCopies)
at Profiler.Tests.GCTests.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\B59D09E6\w\B22909F9\uploads\Reports\profiler.gc\gc\gc.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\B59D09E6\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  gc.dll
Profiler path: C:\h\w\B59D09E6\w\B22909F9\e\profiler\gc\gc\Profiler.dll
Profiler.dll!DllGetClassObject
Profiler.dll!Profiler::Initialize
Did 0 iterations Allocated=70008
Did 1000 iterations Allocated=522288
Did 2000 iterations Allocated=970384
Did 3000 iterations Allocated=1418480
Did 4000 iterations Allocated=1866576

Test failed: Profiler tests are expected to contain the text 'PROFILER TEST PASSES' in the console output of the profilee app to indicate a passing test. Usually it is printed from the Shutdown() method of the profiler impleme


Stack trace
   at profiler_gc._gc_gc_._gc_gc_cmd()
```

**Comment by tommcdon** [comment] 2022-04-11 02:30
@davmason would you mind taking a quick look?

**Comment by jkotas** [comment] 2022-04-11 04:46
Duplicate of #67630

**Closed by jkotas** 2022-04-11 04:46 UTC
Labels: os-windows, JitStress, arch-x64, area-Diagnostics-coreclr
