### ISSUE TITLE
WinHttpHandler ResponseHeadersRead_SynchronizationContextNotUsedByHandler test hung CI

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#55969] opened 2021-07-19 21:29 UTC
net6.0-windows-Debug-x86-CoreCLR_release-Windows.7.Amd64.Open

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55954-merge-def8893518f04c0a88/System.Net.Http.WinHttpHandler.Functional.Tests/console.b22ef9b2.log?sv=2019-07-07&se=2021-08-08T20%3A30%3A41Z&sr=c&sp=rl&sig=cvBXlvzI%2B3E6QlYwmBx46M3%2B7FdfhkX0b%2BRdzZ1NPjM%3D

```
  Discovering: System.Net.Http.WinHttpHandler.Functional.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Net.Http.WinHttpHandler.Functional.Tests (found 293 of 519 test cases)
  Starting:    System.Net.Http.WinHttpHandler.Functional.Tests (parallel test collections = on, max threads = 2)
   System.Net.Http.WinHttpHandler.Functional.Tests: [Long Running Test] 'System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Asynchrony_Test.ResponseHeadersRead_SynchronizationContextNotUsedByHandler', Elapsed: 00:02:11
   System.Net.Http.WinHttpHandler.Functional.Tests: [Long Running Test] 'System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Asynchrony_Test.ResponseHeadersRead_SynchronizationContextNotUsedByHandler', Elapsed: 00:04:11
   System.Net.Http.WinHttpHandler.Functional.Tests: [Long Running Test] 'System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Asynchrony_Test.ResponseHeadersRead_SynchronizationContextNotUsedByHandler', Elapsed: 00:06:11
   System.Net.Http.WinHttpHandler.Functional.Tests: [Long Running Test] 'System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Asynchrony_Test.ResponseHeadersRead_SynchronizationContextNotUsedByHandler', Elapsed: 00:08:11
   System.Net.Http.WinHttpHandler.Functional.Tests: [Long Running Test] 'System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Asynchrony_Test.ResponseHeadersRead_SynchronizationContextNotUsedByHandler', Elapsed: 00:10:11
   System.Net.Http.WinHttpHandler.Functional.Tests: [Long Running Test] 'System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Asynchrony_Test.ResponseHeadersRead_SynchronizationContextNotUsedByHandler', Elapsed: 00:12:11
   System.Net.Http.WinHttpHandler.Functional.Tests: [Long Running Test] 'System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Asynchrony_Test.ResponseHeadersRead_SynchronizationContextNotUsedByHandler', Elapsed: 00:14:11
['System.Net.Http.WinHttpHandler.Functional.Tests' END OF WORK ITEM LOG: Command timed out, and was killed]
```

**Comment by karelz** [comment] 2021-07-28 14:29
Duplicate of #54034

**Closed by karelz** 2021-07-28 14:29 UTC
Labels: area-System.Net.Http
