### ISSUE TITLE
[API Proposal]: Extend `JsonIgnoreCondition` with `WhenReadingNull`

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/runtime#90011] opened 2023-08-04 10:35 UTC
### Background and motivation

    It appears that a new issue was created(https://github.com/dotnet/runtime/issues/90007) and the problem is similar to the one we discussed here. Based on my understanding, implementing the WhenReadingNull feature would address the problem described in the issue.
_Originally posted by @ScarletKuro in https://github.com/dotnet/runtime/issues/66490#issuecomment-1665360868_

Sometimes we may want to ignore the JSON value when the input value is `null`

some discussions here:
- https://github.com/dotnet/runtime/issues/66490#issuecomment-1142804662
- https://github.com/dotnet/runtime/issues/66490#issuecomment-1664743983
- https://github.com/dotnet/runtime/issues/66490#issuecomment-1665225750

and this may be also helpful for the issue

https://github.com/dotnet/runtime/issues/90007

### API Proposal

```diff
namespace System.Text.Json.Serialization;

public enum JsonIgnoreCondition
{
  Never = 0,
  Always = 1,
  WhenWritingDefault = 2,
  WhenWritingNull = 3,
  WhenWriting = 4,
  WhenReading = 5,
+ WhenReadingNull = 6
}
```

### API Usage

```csharp
public class TestBody
{
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenReadingNull)]
    public string? A { get; set; } = "initialValue";
}


string json = """{"A": null}""";
TestBody? testBody = JsonSerializer.Deserialize<TestBody>(json);
// testBody.A = "initialValue";


string json1 = """{"A": "1234"}""";
TestBody? testBody1 = JsonSerializer.Deserialize<TestBody>(json1);
// testBody1.A = "1234";
```

**Comment by ScarletKuro** [comment] 2023-08-04 10:49
Another related issues/discussions:
https://github.com/dotnet/runtime/issues/74008#issuecomment-1219990497
https://github.com/dotnet/runtime/issues/83706#issuecomment-1480116062
https://github.com/dotnet/runtime/issues/30795#issuecomment-529574768
https://github.com/dotnet/runtime/issues/62086

**Comment by eiriktsarpalis** [comment] 2023-08-04 11:22
Closing as duplicate of https://github.com/dotnet/runtime/issues/83706, as it better conveys the requirement for the feature.

**Closed by eiriktsarpalis** 2023-08-04 11:22 UTC
Labels: api-suggestion, area-System.Text.Json, untriaged
