### ISSUE TITLE
net9.0-ios regression causing `InvalidProgramException` in certain circumstances 

### ISSUE THREAD

**Issue by rdavisau** [dotnet/runtime#108108] opened 2024-09-22 05:45 UTC
### Description

Regression introduced in .net9 preview 5, and still present in rc1. On iOS, certain code that worked on .net9 preview 4 and all previous versions of .net now crashes with `InvalidProgramException` in release builds.

Triggering code is a path of [DryIoc](https://github.com/dadhi/DryIoc)'s [interpreter](https://github.com/dadhi/DryIoc/blob/master/src/DryIoc/Container.cs#L3342). From what I could isolate, it occurs in these circumstances:

* multiple singleton service types (`A`, `B`), depend on another singleton type (`Z`)
* the `Z` type is injected lazily (`Lazy<Z>` constructor parameter)
* DryIoC is configured to use its own interpreter
* DryIoC attempts to resolve one of the service types (e.g. `B`), after having previously resolved the other service type (e.g. `A`)

Circumstances that don't cause it:
* `Z` type is injected directly, not lazily
* Only one of the service types is resolved, including repeated resolutions of the same type.

Tagging @dadhi the DryIoC library author who may be able to provide information on what specific parts of the interpreter are exercised in this "resolution of second service injecting lazy dependency" case that differ from the cases that don't trigger the crash. 

### Reproduction Steps

* be running .net9 p5 or later, with the `ios` workload installed
* have physical ios device plugged in
* clone https://github.com/rdavisau/ios-net9-invalidprogram-repro
* run `./net9.sh {Your Physical Device UDID}`

### Expected behavior

Application launches and remains running with log output:
```
Resolve a service that depends on Lazy<Thing> once
Ok
Resolve the same service that depends on Lazy<Thing> a second time
Ok
Resolve a different service that depends on Lazy<Thing>
Ok
```

### Actual behavior

Application launches and quickly crashes, with log output:

```
Resolve a service that depends on Lazy<Thing> once
Ok
Resolve the same service that depends on Lazy<Thing> a second time
Ok
Resolve a different service that depends on Lazy<Thing>

Terminating app due to uncaught exception 'System.InvalidProgramException', reason: ' (System.InvalidProgramException) 
at DryIoc.Interpreter.TryInterpretSingletonAndUnwrapContainerException(IResolverContext r, Expression expr, ImMapEntry`1 itemRef, Object& result) 
at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request) at DryIoc.Factory.GetExpressionOrDefault(Request request) 
at DryIoc.Container.ResolveAndCache(Int32 serviceTypeHash, Type serviceType, IfUnresolved ifUnresolved) 
at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) 
at DryIoc.Resolver.Resolve[IServiceB](IResolver resolver, IfUnresolved ifUnresolved) 
at InvalidProgram.AppDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions) 
at InvalidProgram.AppDelegate.Registrar_Callbacks.callback_2_InvalidProgram_AppDelegate_FinishedLaunching(IntPtr pobj, IntPtr sel, IntPtr p0, IntPtr p1, IntPtr* exception_gchandle) '
```
(sometimes, app may crash before exception details are written to console)

### Regression?

Yes. This was working in .net9 preview 4 and earlier stables. 
Introduced in .net9 preview 5 and still present in .net9 rc1.

### Configuration

dotnet --info
```
.NET SDK:
 Version:           9.0.100-rc.1.24452.12
 Commit:            81a714c6d3
 Workload version:  9.0.100-manifests.b772b23d
 MSBuild version:   17.12.0-preview-24422-09+d17ec720d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.6
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/9.0.100-rc.1.24452.12/

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [ios]
   Installation Source: SDK 9.0.100-rc.1
   Manifest Version:    17.5.9270-net9-rc1/9.0.100-rc.1
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/9.0.100-rc.1/microsoft.net.sdk.ios/17.5.9270-net9-rc1/WorkloadManifest.json
   Install Type:        FileBased

 [maui]
   Installation Source: SDK 9.0.100-rc.1
   Manifest Version:    9.0.0-rc.1.24453.9/9.0.100-rc.1
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/9.0.100-rc.1/microsoft.net.sdk.maui/9.0.0-rc.1.24453.9/WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      9.0.0-rc.1.24431.7
  Architecture: arm64
  Commit:       static

.NET SDKs installed:
  6.0.417 [/usr/local/share/dotnet/sdk]
  7.0.404 [/usr/local/share/dotnet/sdk]
  8.0.100 [/usr/local/share/dotnet/sdk]
  8.0.204 [/usr/local/share/dotnet/sdk]
  9.0.100-preview.3.24204.13 [/usr/local/share/dotnet/sdk]
  9.0.100-preview.4.24267.66 [/usr/local/share/dotnet/sdk]
  9.0.100-preview.5.24307.3 [/usr/local/share/dotnet/sdk]
  9.0.100-preview.6.24328.19 [/usr/local/share/dotnet/sdk]
  9.0.100-preview.7.24407.12 [/usr/local/share/dotnet/sdk]
  9.0.100-rc.1.24452.12 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.25 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.3.24172.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.4.24267.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.5.24306.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.6.24328.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.7.24406.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-rc.1.24452.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.25 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.3.24172.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.4.24266.19 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.5.24306.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.6.24327.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.7.24405.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-rc.1.24431.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by ivanpovazan** [comment] 2024-09-24 14:47
Hello @rdavisau 
I have a question about the repro project attached to the issue. 
It seems like you overwriting default configuration for app trimming (like forcing `TrimMode=full`):
https://github.com/rdavisau/ios-net9-invalidprogram-repro/blob/cca4dae68e8f2abdb2b7ab9bad01db60d6d8d78b/InvalidProgram-net9.csproj#L26

I was wondering what is the reason for overwriting the defaults and if the issue is reproducible if you use the default settings (so we can rule out potential trimming problem)?

**Comment by rdavisau** [comment] 2024-09-25 03:53
Thanks @ivanpovazan 

There were various extra properties set in the reproduction that mirror the real project I observed the issue in. I have removed as many customisations as possible while being able to continue to reproduce the issue. I found two things:

* different combinations of mtouchlink/trimmode did not appear to affect the crash (full, partial, sdk only etc.)
* from the current state of the repro, which now only includes a `<PublishTrimmed>true</PublishTrimmed>` element, you can fix the issue by removing the `PublishedTrimmed` element. 

The second point is surprising to me, since we can't specify `<PublishTrimmed>false</PublishTrimmed>`, so I suppose that the inclusion of `PublishTrimmed` at all causes some other properties to be set? In this case it seems it could be trimming-related after all.

**Comment by vitek-karas** [comment] 2024-09-25 17:26
I tried this without trying to run the app, just to see the difference in trimming.
The main difference in the input to the trimmer are these feature switches (this is without PublishTrimmed -> with PublishTrimmed):
```
--feature Microsoft.Extensions.DependencyInjection.VerifyOpenGenericServiceTrimmability false->true
--feature System.ComponentModel.DefaultValueAttribute.IsSupported ->false
--feature System.ComponentModel.Design.IDesignerHost.IsSupported ->false
--feature System.Resources.UseSystemResourceKeys true->false
--feature System.Runtime.CompilerServices.RuntimeFeature.IsDynamicCodeSupported false->true
--feature System.Runtime.InteropServices.Marshalling.EnableGeneratedComInterfaceComImportInterop ->false
```

The rest of the command line is basically identical. Specifically `IsDynamicCodeSupported` and (for DI especially) `VerifyOpenGenericServiceTrimmability` might affect the app.
I don't have a device to test the app on, but it would be really interesting to try to set these feature switches one by one to see which one causes the problem. From there it should be much easier to figure out the trimming difference.

**Comment by rdavisau** [comment] 2024-09-25 19:59
I can go through the different combinations, but I’m not sure how to override the feature switches 💭

**Comment by ivanpovazan** [comment] 2024-09-25 20:43
The problem we are having seems to be a mismatch in the feature switch configuration when `PublishTrimmed` property is set on a project level (or forced) or resolved by the SDK:
- if it *is not set* on the project level, we will use feature switch configuration as set in the Xamarin SDK early in `Xamarin.Shared.Sdk.targets`: 
https://github.com/xamarin/xamarin-macios/blob/ec50934897ef1b98c1cd73ca780cdf5a3750faaa/dotnet/targets/Xamarin.Shared.Sdk.targets#L121-L158
The SDK later sets: `PublishTrimmed` to `true` so that we run the linker in:
https://github.com/xamarin/xamarin-macios/blob/ec50934897ef1b98c1cd73ca780cdf5a3750faaa/dotnet/targets/Xamarin.Shared.Sdk.targets#L298

- if it *is set* on project level, `Microsoft.NET.ILLink.targets` will set its own feature switch configuration in: https://github.com/dotnet/runtime/blob/a16e0d58e92fe5f3bcda9e75e9afd1ee0f766967/src/tools/illink/src/ILLink.Tasks/build/Microsoft.NET.ILLink.targets#L34-L61 as it is imported before `Xamarin.Shared.Sdk.targets`

<img width="976" alt="Screenshot 2024-09-25 at 22 37 44" src="https://github.com/user-attachments/assets/b53b8d78-dcb9-47fd-b1aa-e97ef83b1df0">



This is specifically problematic in case of for example: `DynamicCodeSupport `, which should not be `true` on iOS platforms if interpreter is not enabled.

So I suggest as a workaround to not set manually `PublishTrimmed=true` on a project level and we should look into how to properly align the feature switch configuration.

/cc: @rolfbjarne do you have any other suggestion?

**Comment by rolfbjarne** [comment] 2024-09-25 22:11
My suggestion would be to not set the PublishTrimmed defaults (or any other trimmer/linker default really) until right before they're needed (i.e. in a target), that way we (xamarin-macios) can provide different defaults earlier in the build.

**Comment by rdavisau** [comment] 2024-09-25 22:51
In the repro, removing PublishTrimmed (and now there are no customisations) resolves the issue. 
In my real project, I have removed PublishTrimmed, but kept the other configuration bits that I think I still want to specify: 

```
<PropertyGroup Condition="true">
    <TrimmerSingleWarn>false</TrimmerSingleWarn>    
    <TrimMode>full</TrimMode>
    <MtouchLink>full</MtouchLink>
    <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
</PropertyGroup>
<ItemGroup Condition="true">
    <TrimmerRootDescriptor Include="trim.xml" />
</ItemGroup>
```

and the same crash occurs. Have I misunderstood? Or can one of these settings also end up trigginer the different set trim features?

**Comment by ivanpovazan** [comment] 2024-09-26 06:53
I think there are two problems:

1. Manually setting `PublishTrimmed=true` in the project file which sets different default values for feature switches that can cause runtime issues
2. Enabling full trimming `TrimMode=full` in the project file for an application which is not fully trim-compatible

For `1.` thank you for checking it out, and verifying that removing explicitly setting `PublishTrimmed` works around the problem. (and we will look into how to make better experience around this)

For `2.` when I enable full trimming in the app e.g.,:
> ```
>    <PropertyGroup Condition="true">
>        <TrimmerSingleWarn>false</TrimmerSingleWarn>    
>        <TrimMode>full</TrimMode>
>        <MtouchLink>full</MtouchLink>
>        <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
>    </PropertyGroup>
>    <ItemGroup Condition="true">
>        <TrimmerRootDescriptor Include="trim.xml" />
>    </ItemGroup>
> ```

and build the app, it produces 134 warnings, out of which 124 are Trim analysis warning coming from `DryIoc` nuget package (list of warnings: https://gist.github.com/ivanpovazan/aa88dac789576ba2210c17d3e9c30a35). This means that the referenced library is not trim-compatible and as such cannot be used in a fully trimmed app. As long as there are trim analysis warnings during build-time, there is no guarantee that the app will run successfully, and that will properly work when `TrimMode=full` is set.

**Comment by rdavisau** [comment] 2024-09-26 23:24
Ok, got it. 

So if we set aside `1.`, then we think this really is "just a linking issue". 
The reason for the change then could be linker becoming more aggressive, or maybe more parts of dotnet being marked linksafe - they were always undetected, but now can be removed?
If this type of issue could cause `InvalidProgramException` (I expect `MissingXException`, but since we are dealing with clever code I suppose clever code could trigger different outcome), then I think there is no issue here.

Separately I wonder are there any ways to know from the runtime error what was linked out that was needed? I am analysing the difference between the ~400mb linker-dependencies files, but if there is an easier way I will take it. And I know the real answer is "don't use full trim with warnings", but I also think it can't be too many hints away from working  🙂

**Comment by ivanpovazan** [comment] 2024-09-27 13:16
Regarding:
> Separately I wonder are there any ways to know from the runtime error what was linked out that was needed? I am analysing the difference between the ~400mb linker-dependencies files, but if there is an easier way I will take it. And I know the real answer is "don't use full trim with warnings", but I also think it can't be too many hints away from working 🙂

The recommendation is to start resolving trim warnings rather than finding what trimmer removed and try to root it or simply not use `TrimMode=full` when a dependency is not compatible with it.

---

Regarding:
> InvalidProgramException

I just built/ran your repro project with `dotnet v9.0.100-rc.1.24452.12` and the provided configuration:
```
<PropertyGroup Condition="true">
       <TrimmerSingleWarn>false</TrimmerSingleWarn>    
       <TrimMode>full</TrimMode>
       <MtouchLink>full</MtouchLink>
       <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
   </PropertyGroup>
   <ItemGroup Condition="true">
       <TrimmerRootDescriptor Include="trim.xml" />
   </ItemGroup>
```
and the previously provided `trim.xml`, the program runs without crashing.
Here is the log from the device:

```
default	14:56:07.725970+0200	InvalidProgram-net9	Resolve a service that depends on Lazy<Thing> once
default	14:56:07.743236+0200	InvalidProgram-net9	Ok
default	14:56:07.743387+0200	InvalidProgram-net9	Resolve the same service that depends on Lazy<Thing> a second time
default	14:56:07.743488+0200	InvalidProgram-net9	Ok
default	14:56:07.743587+0200	InvalidProgram-net9	Resolve a different service that depends on Lazy<Thing>
default	14:56:07.743805+0200	InvalidProgram-net9	Ok
```

Since:
1. We identified the problem with explicitly setting `PublishTrimmed` and opened a tracking issue for it
2. The remaining issue with `TrimMode=full` cannot be reproduced with the provided repro project
3. We are in the scope of using unsupported configurations i.e., full trimming with programs that have trim warnings

I will close this issue. If you encounter the same or similar issue again in a scenario/configuration we support, please feel free to reopen this and I will gladly take a look again. Thank you for understanding.

**Closed by ivanpovazan** 2024-09-27 13:16 UTC
Labels: area-Codegen-Interpreter-mono, os-ios, needs-further-triage

**Comment by rdavisau** [comment] 2024-09-28 01:20
Yes, I observed the same. Frustratingly, the same change did not yield the desired outcome in my real project, but I take your recommendations on board. Thanks for helping investigate.
