### ISSUE TITLE
6.0 RC1: ImplicitUsings with .NET Framework 4.x - System.Net.Http is not available

### ISSUE THREAD

**Issue by buvinghausen** [dotnet/runtime#59163] opened 2021-09-15 14:41 UTC
I have two NuGet packages I maintain with legacy .NET Framework support for 4.6.2 when I enabled ImplicitUsings on those projects they both failed to compile due to the inclusion of System.Net.Http which the legacy .NET Framework doesn't have available without adding a package dependency on System.Net.Http

Error Message: error CS0234: The type or namespace name 'Http' does not exist in the namespace 'System.Net' (are you missing an assembly reference?)

Failed workaround:
```xml
<ItemGroup>
  <Using Remove="System.Net.Http" />
</ItemGroup>
```

(Updated)
Workaround:
```xml
<ItemGroup Condition="'$(TargetFramework)'=='net462'">
  <Reference Include="System.Net.Http" />
</ItemGroup>
```

Suggested fix:
```cs
// <auto-generated/>
global using global::System;
global using global::System.Collections.Generic;
global using global::System.IO;
global using global::System.Linq;
#if !NETFRAMEWORK
global using global::System.Net.Http;
#endif
global using global::System.Threading;
global using global::System.Threading.Tasks;
```

[Reproduced here for convenience just remove the package reference](https://github.com/buvinghausen/SequentialGuid/blob/master/src/SequentialGuid/SequentialGuid.csproj#L12)

**Comment by MichalPetryka** [comment] 2021-09-15 15:34
.Net Framework 4.6.2 does include System.Net.Http, especially since it's in .Net Standard 2.0 which .NF 4.6.2 covers.

**Comment by buvinghausen** [comment] 2021-09-15 15:39
@MichalPetryka that would be a no.....

![image](https://user-images.githubusercontent.com/1130210/133464761-f305712e-74a8-4d58-bd16-72a50c85ae09.png)

**Comment by buvinghausen** [comment] 2021-09-15 15:44
![image](https://user-images.githubusercontent.com/1130210/133465563-f9cdc0d1-afcb-40b1-a606-12733f94787f.png)

**Comment by karelz** [comment] 2021-09-15 15:47
@buvinghausen I am not sure I fully understand.
`System.Net.Http` is empty nuget package and we recommend people to drop reference to it if they can. You seem to claim that it is somehow needed, which is suspicious.
Do you have a small repro demonstrating why is it needed? Which APIs do you use?
They should be part of System.dll (or System.Net.dll or System.Net.Http.dll) on .NET Framework -- all those are part of .NET Framework itself, no need to have NuGet packages (though you may need to play games with binding redirects).

**Comment by buvinghausen** [comment] 2021-09-15 15:48
@karelz please see the OP the bottom has everything you need

**Comment by karelz** [comment] 2021-09-15 16:04
@buvinghausen I see your code link now.
I don't understand what is ImplicitUsings in your context, and why is it needed.

Also, I am not sure what this comment means:
https://github.com/buvinghausen/SequentialGuid/blob/master/src/SequentialGuid/SequentialGuid.csproj#L9
```
... System.Net.Http is not included in .net framework legacy
```

Is there a chance to create HelloWorld-style CS file with project which would demonstrate the problem? That will help me identify where to route this. It does not seem to be problem of the NuGet package itself ...

**Comment by teo-tsirpanis** [comment] 2021-09-15 16:16
[Here it is.](https://github.com/dotnet/runtime/files/7171741/netfx-http.zip) Try to `dotnet build` it.

**Comment by buvinghausen** [comment] 2021-09-15 16:36
@karelz sorry I was on a conference call but it looks like @teo-tsirpanis got it covered.

**Comment by AraHaan** [comment] 2021-09-15 17:38
Normally System.Net.Http is not referenced by the .NET SDK by default I think on .NET Framework 4.6.2. I remember before I had to explicitly add ``<Reference Include=System.Net.Http" />`` back when I had projects target .NET Framework at all just to be safe.

**Comment by buvinghausen** [comment] 2021-09-15 19:26
@AraHaan thank you for the input I was able to add the following lines to my Directory.Build.props files and now everything compiles and tests

```xml
<ItemGroup Condition="'$(TargetFramework)'=='net462'">
  <Reference Include="System.Net.Http" />
</ItemGroup>
```

[You can see the commit here](https://github.com/buvinghausen/SequentialGuid/commit/1055e1f91d80090ccfc2b0f5e1b0f6053d90f458)

@karelz I don't know if this is something you still want to triage so I will leave it open for the time being but I don't need it kept open on my behalf as I should be able to publish to nuget without the added dependency.  This was more an exploration of implicit usings than a must have deal in the end.

**Comment by teo-tsirpanis** [comment] 2021-09-15 20:30
If I target `net20`, I get these errors (trimmed for brevity) and no extra reference can save me if I use implicit `using`s:

```
Error CS0234 : The type or namespace name 'Linq' does not exist in the namespace 'System'
Error CS0234 : The type or namespace name 'Http' does not exist in the namespace 'System.Net'
Error CS0234 : The type or namespace name 'Tasks' does not exist in the namespace 'System.Threading'
```

I think this issue belongs `dotnet/sdk`.

**Comment by buvinghausen** [comment] 2021-09-16 00:03
@teo-tsirpanis Yeah I would imagine anything below net45 would be SOL.  Task&lt;T&gt; came with .NET 4 and System.Linq came with .NET 3.5.

**Comment by martincostello** [comment] 2021-09-16 06:32
FYI I bought this up a few weeks ago in the SDK issue for the global using feature and the response I got was that it was by-design as this feature is only supported for .NET 6 https://github.com/dotnet/sdk/issues/19521#issuecomment-903819782

**Comment by karelz** [comment] 2021-09-16 08:26
Duplicate of https://github.com/dotnet/sdk/issues/19521

**Comment by karelz** [comment] 2021-09-16 08:27
Thanks @martincostello for referencing that. It seems like dupe, so I marked it so. Not much we can do about it in System.Net.Http NuGet package ...

**Closed by karelz** 2021-09-16 08:26 UTC
Labels: area-System.Net.Http, untriaged
