### ISSUE TITLE
Cannot parte RFC1123 dates

### ISSUE THREAD

**Issue by jmalbarran** [dotnet/runtime#80156] opened 2022-12-28 19:18 UTC
### Describe the bug
This bug was already reported in Stackoverflow 12 years ago, but it seems is not solved yet
https://stackoverflow.com/questions/2580356/parsing-rfc1123-formatted-dates-in-c-net-4-0

I'm parsing e-mail .eml files, and these one has the date in RFC1123 format, with specific time zone or no time zone:

Examples:

"Tue, 08 Oct 2019 12:41:35 -0700 (PDT)"

"Tue, 8 Oct 2019 21:41:23 +0200"

"Thu, 5 Sep 2019 12:53:23 -0700 (PDT)"

I'm trying
```DateTime.ParseExact(date,CultureInfo.InvariantCulture.DateTimeFormat.RFC1123Pattern,CultureInfo.InvariantCulture)```

and

```Convert.ToDateTime(date,CultureInfo.InvariantCulture)````

### To Reproduce
I'm trying
```DateTime.ParseExact(date,CultureInfo.InvariantCulture.DateTimeFormat.RFC1123Pattern,CultureInfo.InvariantCulture)```

and

```Convert.ToDateTime(date,CultureInfo.InvariantCulture)````

### Exceptions (if any)
InvalidFormatException

### Further technical details
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and its version

**Comment by Clockwork-Muse** [comment] 2023-01-04 02:24
1. [That's not a valid time format for RFC1123](https://stackoverflow.com/a/54929530/812837).  Only GMT is a supported zone, and offsets aren't permitted.  This is therefore not a bug in C#.
 2. The three-character timezone codes are **NOT** unique, and you may not be able to reconcile them with the offsets.  There are multiple conflicting codes with the same or near (DST conflicts) offsets.  I'm not sure whether the `.eml` files you are dealing with are even using a "standard" set of codes - there are _multiple_ sets, many with conflicting entries (famously, IATA, an airline standards body, uses UTC for "Utrecht", an airport in the Netherlands).

You will likely need to strip the timezone first, and use a custom date-time format string for the parsing.
You **MUST** use `DateTimeOffset` for the parse, because `DateTime` will not correctly retain sufficient information to retain the offset.

**Comment by tarekgh** [comment] 2023-01-11 19:22
Thanks @Clockwork-Muse for your reply. Closing it per that reply.

**Closed by tarekgh** 2023-01-11 19:22 UTC
Labels: untriaged, area-System.DateTime
