### ISSUE TITLE
EnumerationOptions not filtering Hidden attributes in macOS

### ISSUE THREAD

**Issue by imerzan** [dotnet/runtime#57348] opened 2021-08-13 14:33 UTC
### Description

When using `DirectoryInfo.EnumerateDirectories()` with `EnumerationOptions` configured to ignore Hidden Attributes, the enumeration is still returning hidden items. Only occurring on macOS (works as intended on Windows).

```
var options = new EnumerationOptions()
{
     AttributesToSkip = FileAttributes.Hidden | FileAttributes.System
};
var source = new DirectoryInfo("Test Directory");
foreach (DirectoryInfo subfolder in source.EnumerateDirectories("*", options);
{
     Console.WriteLine(subfolder.Name); // Still prints hidden folders in OSX but not Windows
}
```

I expect that `EnumerationOptions.AttributesToSkip` should function the same on macOS as Windows.

### Configuration

.NET 5.0.302
macOS Big Sur 11.5.1
osx-x64 self-contained
Only occurs on my osx-x64 build. win-x64 works fine.

### Regression?

* Did this work in a previous build or release of .NET Core, or from .NET Framework? If you can try a previous release or build to find out, that can help us narrow down the problem. If you don't know, that's OK.

I have not tried this code in a previous build or release.

### Other information

If I use the following code modification as a workaround, it seems to function:
```
// omitted some code, same example from above
foreach (DirectoryInfo subfolder in source.EnumerateDirectories("*", options);
{
     if (subfolder.Attributes.HasFlag(FileAttributes.Hidden)) continue; // This will properly skip hidden folders
     Console.WriteLine(subfolder.Name);
}
```

Not sure if related to https://github.com/dotnet/runtime/issues/25989

**Comment by Jozkee** [comment] 2021-08-13 16:24
Duplicate of https://github.com/dotnet/runtime/issues/37301
@imerzan this is fixed in 6.0, you can confirm that your scenario is correctly covered by testing with the latest preview sdk https://dotnet.microsoft.com/download/dotnet/6.0.

**Closed by Jozkee** 2021-08-13 16:24 UTC
Labels: area-System.IO, untriaged
