### ISSUE TITLE
Backport #61798 to .NET 6

### ISSUE THREAD

**Issue by madelson** [dotnet/runtime#73007] opened 2022-07-28 15:15 UTC
#61798 is breaking concurrent use of the .NET Azure SDKs for us starting in .NET 6 (see https://github.com/Azure/azure-sdk-for-net/issues/27018, for example). Can this fix be backported to .NET 6?

**Comment by MihaZupan** [comment] 2022-07-28 15:27
Judging by the stack trace you posted in https://github.com/Azure/azure-sdk-for-net/issues/27018#issuecomment-1198188705, you appear to be hitting #65379.

Can you please try the workaround mentioned in the issue?

**Comment by MihaZupan** [comment] 2022-07-28 15:28
Duplicate of #65379.

**Closed by MihaZupan** 2022-07-28 15:28 UTC
Labels: area-System.Net.Http, untriaged

**Comment by madelson** [comment] 2022-07-28 20:24
@MihaZupan thanks for the info on the other error. 

However, I'm also seeing the index-out-of-bounds error (see https://github.com/Azure/azure-sdk-for-net/issues/27018#issuecomment-1180568093) so I'd still appreciate that fix being backported.

**Comment by MihaZupan** [comment] 2022-07-28 20:32
https://github.com/dotnet/runtime/issues/65379 is the cause for that `IndexOutOfRangeException` (see `EstablishProxyTunnelAsync` in the stack trace).

**Comment by madelson** [comment] 2022-07-28 20:45
Ah ok I misunderstood. So #61799 covers *both* stacktraces:

```
System.IndexOutOfRangeException: Index was outside the bounds of the array. 
at System.Net.Http.Headers.HttpHeaders.ReadStoreValues[T](Span`1 values, Object storeValue, HttpHeaderParser parser, Int32& currentIndex) 
at System.Net.Http.Headers.HttpHeaders.GetStoreValuesAsStringOrStringArray(HeaderDescriptor descriptor, Object sourceValues, String& singleValue, String[]& multiValue) 
at System.Net.Http.Headers.HttpHeaders.GetStoreValuesAsStringArray(HeaderDescriptor descriptor, HeaderStoreItemInfo info) 
at System.Net.Http.Headers.HttpHeaders.TryGetValues(HeaderDescriptor descriptor, IEnumerable`1& values) 
at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, HttpRequestHeaders headers, CancellationToken cancellationToken) 
at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) 
at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) 
at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request) 
at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) 
at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) 
at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) 
at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) 
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) 
at System.Net.Http.HttpClient.<SendAsync>g_Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) 
```

**AND**

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute. 
at System.Collections.Generic.List`1.Enumerator.MoveNextRare() 
at System.Net.Http.Headers.HttpHeaders.ReadStoreValues[T](Span`1 values, Object storeValue, HttpHeaderParser parser, Int32& currentIndex)
at System.Net.Http.Headers.HttpHeaders.GetStoreValuesAsStringOrStringArray(HeaderDescriptor descriptor, Object sourceValues, String& singleValue, String[]& multiValue) 
at System.Net.Http.Headers.HttpHeaders.GetStoreValuesAsStringArray(HeaderDescriptor descriptor, HeaderStoreItemInfo info) 
at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, HttpRequestHeaders headers, CancellationToken cancellationToken) 
at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) 
at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request) 
at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) 
at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) 
at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) 
at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) 
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) 
at System.Net.Http.HttpClient.<SendAsync>g_Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) 
```

Is that correct?

**Comment by MihaZupan** [comment] 2022-07-28 20:55
https://github.com/dotnet/runtime/pull/68115 tracks the issue that before 7.0, reading from a header collection concurrently was not thread-safe, blowing up in many different ways (like the two exceptions you observed).

We treat concurrent use like that as improper usage. But there are cases where `HttpClient` itself accesses the collection when it shouldn't, leading to errors in otherwise well-behaved client code.
https://github.com/dotnet/runtime/issues/65379 tracks one such bug that occurs if the user uses a proxy. In your case, both exceptions are just different manifestations of the same race condition.

**Comment by madelson** [comment] 2022-07-28 21:03
@MihaZupan thanks. It is still my understanding that these problems are unique to (or at least much more prevalent in) .NET 6; we're hitting them through the Azure SDK and we did not see them prior to the .NET 6 upgrade. Do you think any of the relevant changes will be backported to 6?
