### ISSUE TITLE
Regression in Crossgen2 Throughput

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#51006] opened 2021-04-09 16:42 UTC
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Diff | [Diff](https://github.com/dotnet/runtime/compare/a3e0894f38b1ab558653e7c1b7322a8c4db92af1...bdd7ca0d78ce86c2dc0ab24df42a09ef514a771c)

### Regressions in Crossgen2 Throughput - Single - Microsoft.CodeAnalysis

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[CodeAnalysis](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_RunKind=crossgen_scenarios/Crossgen2%20Throughput%20-%20Single%20-%20Microsoft.CodeAnalysis.html>) | 1854.95 ms | 1921.10 ms | 1.04 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_08_2021/refs/heads/main_x64_ubuntu%2018.04_RunKind=crossgen_scenarios_Regression/Crossgen2%20Throughput%20-%20Single%20-%20Microsoft.CodeAnalysis_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_08_2021/refs/heads/main_x64_ubuntu%2018.04_RunKind=crossgen_scenarios_Regression/Crossgen2%20Throughput%20-%20Single%20-%20Microsoft.CodeAnalysis.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'Crossgen2 Throughput - Single - Microsoft.CodeAnalysis*'
```
<details>

#### Crossgen2 Throughput - Single - Microsoft.CodeAnalysis

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Diff | [Diff](https://github.com/dotnet/runtime/compare/a3e0894f38b1ab558653e7c1b7322a8c4db92af1...bdd7ca0d78ce86c2dc0ab24df42a09ef514a771c)

### Regressions in Crossgen2 Throughput - Single - System.Net.Sockets

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[Sockets](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_RunKind=crossgen_scenarios/Crossgen2%20Throughput%20-%20Single%20-%20System.Net.Sockets.html>) | 775.46 ms | 786.31 ms | 1.01 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_08_2021/refs/heads/main_x64_ubuntu%2018.04_RunKind=crossgen_scenarios_Regression/Crossgen2%20Throughput%20-%20Single%20-%20System.Net.Sockets_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_08_2021/refs/heads/main_x64_ubuntu%2018.04_RunKind=crossgen_scenarios_Regression/Crossgen2%20Throughput%20-%20Single%20-%20System.Net.Sockets.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'Crossgen2 Throughput - Single - System.Net.Sockets*'
```
<details>

#### Crossgen2 Throughput - Single - System.Net.Sockets

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Diff | [Diff](https://github.com/dotnet/runtime/compare/a3e0894f38b1ab558653e7c1b7322a8c4db92af1...bdd7ca0d78ce86c2dc0ab24df42a09ef514a771c)

### Regressions in Crossgen2 Throughput - Single - System.Private.CoreLib

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[CoreLib](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_RunKind=crossgen_scenarios/Crossgen2%20Throughput%20-%20Single%20-%20System.Private.CoreLib.html>) | 2741.40 ms | 3018.09 ms | 1.10 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_08_2021/refs/heads/main_x64_ubuntu%2018.04_RunKind=crossgen_scenarios_Regression/Crossgen2%20Throughput%20-%20Single%20-%20System.Private.CoreLib_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_08_2021/refs/heads/main_x64_ubuntu%2018.04_RunKind=crossgen_scenarios_Regression/Crossgen2%20Throughput%20-%20Single%20-%20System.Private.CoreLib.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'Crossgen2 Throughput - Single - System.Private.CoreLib*'
```
<details>

#### Crossgen2 Throughput - Single - System.Private.CoreLib

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Diff | [Diff](https://github.com/dotnet/runtime/compare/a3e0894f38b1ab558653e7c1b7322a8c4db92af1...bdd7ca0d78ce86c2dc0ab24df42a09ef514a771c)

### Regressions in Crossgen2 Throughput - Single Threaded - Single - System.Data.Common

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[Common](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_RunKind=crossgen_scenarios/Crossgen2%20Throughput%20-%20Single%20Threaded%20-%20Single%20-%20System.Data.Common.html>) | 2563.62 ms | 2740.17 ms | 1.07 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_08_2021/refs/heads/main_x64_ubuntu%2018.04_RunKind=crossgen_scenarios_Regression/Crossgen2%20Throughput%20-%20Single%20Threaded%20-%20Single%20-%20System.Data.Common_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_08_2021/refs/heads/main_x64_ubuntu%2018.04_RunKind=crossgen_scenarios_Regression/Crossgen2%20Throughput%20-%20Single%20Threaded%20-%20Single%20-%20System.Data.Common.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'Crossgen2 Throughput - Single Threaded - Single - System.Data.Common*'
```
<details>

#### Crossgen2 Throughput - Single Threaded - Single - System.Data.Common

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Diff | [Diff](https://github.com/dotnet/runtime/compare/a3e0894f38b1ab558653e7c1b7322a8c4db92af1...bdd7ca0d78ce86c2dc0ab24df42a09ef514a771c)

### Regressions in Crossgen2 Throughput - Single - Microsoft.CodeAnalysis.VisualBasic

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[VisualBasic](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_RunKind=crossgen_scenarios/Crossgen2%20Throughput%20-%20Single%20-%20Microsoft.CodeAnalysis.VisualBasic.html>) | 3807.93 ms | 3969.92 ms | 1.04 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_08_2021/refs/heads/main_x64_ubuntu%2018.04_RunKind=crossgen_scenarios_Regression/Crossgen2%20Throughput%20-%20Single%20-%20Microsoft.CodeAnalysis.VisualBasic_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_08_2021/refs/heads/main_x64_ubuntu%2018.04_RunKind=crossgen_scenarios_Regression/Crossgen2%20Throughput%20-%20Single%20-%20Microsoft.CodeAnalysis.VisualBasic.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'Crossgen2 Throughput - Single - Microsoft.CodeAnalysis.VisualBasic*'
```
<details>

#### Crossgen2 Throughput - Single - Microsoft.CodeAnalysis.VisualBasic

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Diff | [Diff](https://github.com/dotnet/runtime/compare/a3e0894f38b1ab558653e7c1b7322a8c4db92af1...bdd7ca0d78ce86c2dc0ab24df42a09ef514a771c)

### Regressions in Crossgen2 Throughput - Single Threaded - Single - Microsoft.CodeAnalysis.CSharp

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[CSharp](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_RunKind=crossgen_scenarios/Crossgen2%20Throughput%20-%20Single%20Threaded%20-%20Single%20-%20Microsoft.CodeAnalysis.CSharp.html>) | 7879.24 ms | 8506.36 ms | 1.08 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_08_2021/refs/heads/main_x64_ubuntu%2018.04_RunKind=crossgen_scenarios_Regression/Crossgen2%20Throughput%20-%20Single%20Threaded%20-%20Single%20-%20Microsoft.CodeAnalysis.CSharp_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_08_2021/refs/heads/main_x64_ubuntu%2018.04_RunKind=crossgen_scenarios_Regression/Crossgen2%20Throughput%20-%20Single%20Threaded%20-%20Single%20-%20Microsoft.CodeAnalysis.CSharp.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'Crossgen2 Throughput - Single Threaded - Single - Microsoft.CodeAnalysis.CSharp*'
```
<details>

#### Crossgen2 Throughput - Single Threaded - Single - Microsoft.CodeAnalysis.CSharp

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Diff | [Diff](https://github.com/dotnet/runtime/compare/a3e0894f38b1ab558653e7c1b7322a8c4db92af1...bdd7ca0d78ce86c2dc0ab24df42a09ef514a771c)

### Regressions in Crossgen2 Throughput - Single Threaded - Single - Microsoft.CodeAnalysis

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[CodeAnalysis](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_RunKind=crossgen_scenarios/Crossgen2%20Throughput%20-%20Single%20Threaded%20-%20Single%20-%20Microsoft.CodeAnalysis.html>) | 3577.61 ms | 3794.41 ms | 1.06 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_08_2021/refs/heads/main_x64_ubuntu%2018.04_RunKind=crossgen_scenarios_Regression/Crossgen2%20Throughput%20-%20Single%20Threaded%20-%20Single%20-%20Microsoft.CodeAnalysis_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_08_2021/refs/heads/main_x64_ubuntu%2018.04_RunKind=crossgen_scenarios_Regression/Crossgen2%20Throughput%20-%20Single%20Threaded%20-%20Single%20-%20Microsoft.CodeAnalysis.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'Crossgen2 Throughput - Single Threaded - Single - Microsoft.CodeAnalysis*'
```
<details>

#### Crossgen2 Throughput - Single Threaded - Single - Microsoft.CodeAnalysis

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Diff | [Diff](https://github.com/dotnet/runtime/compare/a3e0894f38b1ab558653e7c1b7322a8c4db92af1...bdd7ca0d78ce86c2dc0ab24df42a09ef514a771c)

### Regressions in Crossgen2 Throughput - Composite - framework-r2r

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[Crossgen2 Throughput - Composite - framework-r2r](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_RunKind=crossgen_scenarios/Crossgen2%20Throughput%20-%20Composite%20-%20framework-r2r.html>) | 32497.26 ms | 35029.59 ms | 1.08 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_08_2021/refs/heads/main_x64_ubuntu%2018.04_RunKind=crossgen_scenarios_Regression/Crossgen2%20Throughput%20-%20Composite%20-%20framework-r2r_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_08_2021/refs/heads/main_x64_ubuntu%2018.04_RunKind=crossgen_scenarios_Regression/Crossgen2%20Throughput%20-%20Composite%20-%20framework-r2r.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'Crossgen2 Throughput - Composite - framework-r2r*'
```
<details>

#### Crossgen2 Throughput - Composite - framework-r2r

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Diff | [Diff](https://github.com/dotnet/runtime/compare/a3e0894f38b1ab558653e7c1b7322a8c4db92af1...bdd7ca0d78ce86c2dc0ab24df42a09ef514a771c)

### Regressions in Crossgen2 Throughput - Single Threaded - Single - System.Net.WebProxy

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[WebProxy](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_RunKind=crossgen_scenarios/Crossgen2%20Throughput%20-%20Single%20Threaded%20-%20Single%20-%20System.Net.WebProxy.html>) | 661.70 ms | 667.57 ms | 1.01 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_08_2021/refs/heads/main_x64_ubuntu%2018.04_RunKind=crossgen_scenarios_Regression/Crossgen2%20Throughput%20-%20Single%20Threaded%20-%20Single%20-%20System.Net.WebProxy_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_08_2021/refs/heads/main_x64_ubuntu%2018.04_RunKind=crossgen_scenarios_Regression/Crossgen2%20Throughput%20-%20Single%20Threaded%20-%20Single%20-%20System.Net.WebProxy.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'Crossgen2 Throughput - Single Threaded - Single - System.Net.WebProxy*'
```
<details>

#### Crossgen2 Throughput - Single Threaded - Single - System.Net.WebProxy

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Diff | [Diff](https://github.com/dotnet/runtime/compare/a3e0894f38b1ab558653e7c1b7322a8c4db92af1...bdd7ca0d78ce86c2dc0ab24df42a09ef514a771c)

### Regressions in Crossgen2 Throughput - Single - System.Data.Common

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[Common](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_RunKind=crossgen_scenarios/Crossgen2%20Throughput%20-%20Single%20-%20System.Data.Common.html>) | 1268.30 ms | 1327.32 ms | 1.05 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_08_2021/refs/heads/main_x64_ubuntu%2018.04_RunKind=crossgen_scenarios_Regression/Crossgen2%20Throughput%20-%20Single%20-%20System.Data.Common_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_08_2021/refs/heads/main_x64_ubuntu%2018.04_RunKind=crossgen_scenarios_Regression/Crossgen2%20Throughput%20-%20Single%20-%20System.Data.Common.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'Crossgen2 Throughput - Single - System.Data.Common*'
```
<details>

#### Crossgen2 Throughput - Single - System.Data.Common

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Diff | [Diff](https://github.com/dotnet/runtime/compare/a3e0894f38b1ab558653e7c1b7322a8c4db92af1...bdd7ca0d78ce86c2dc0ab24df42a09ef514a771c)

### Regressions in Crossgen2 Throughput - Single - System.ServiceModel.Syndication

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[Syndication](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_RunKind=crossgen_scenarios/Crossgen2%20Throughput%20-%20Single%20-%20System.ServiceModel.Syndication.html>) | 726.85 ms | 732.04 ms | 1.01 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_08_2021/refs/heads/main_x64_ubuntu%2018.04_RunKind=crossgen_scenarios_Regression/Crossgen2%20Throughput%20-%20Single%20-%20System.ServiceModel.Syndication_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_08_2021/refs/heads/main_x64_ubuntu%2018.04_RunKind=crossgen_scenarios_Regression/Crossgen2%20Throughput%20-%20Single%20-%20System.ServiceModel.Syndication.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'Crossgen2 Throughput - Single - System.ServiceModel.Syndication*'
```
<details>

#### Crossgen2 Throughput - Single - System.ServiceModel.Syndication

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Diff | [Diff](https://github.com/dotnet/runtime/compare/a3e0894f38b1ab558653e7c1b7322a8c4db92af1...bdd7ca0d78ce86c2dc0ab24df42a09ef514a771c)

### Regressions in Crossgen2 Throughput - Single Threaded - Single - System.Net.Sockets

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[Sockets](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_ubuntu 18.04_RunKind=crossgen_scenarios/Crossgen2%20Throughput%20-%20Single%20Threaded%20-%20Single%20-%20System.Net.Sockets.html>) | 1106.07 ms | 1149.64 ms | 1.04 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_08_2021/refs/heads/main_x64_ubuntu%2018.04_RunKind=crossgen_scenarios_Regression/Crossgen2%20Throughput%20-%20Single%20Threaded%20-%20Single%20-%20System.Net.Sockets_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/04_08_2021/refs/heads/main_x64_ubuntu%2018.04_RunKind=crossgen_scenarios_Regression/Crossgen2%20Throughput%20-%20Single%20Threaded%20-%20Single%20-%20System.Net.Sockets.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'Crossgen2 Throughput - Single Threaded - Single - System.Net.Sockets*'
```
<details>

#### Crossgen2 Throughput - Single Threaded - Single - System.Net.Sockets

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by DrewScoggins** [comment] 2021-04-09 16:43
This seems like the most likely change in the commit range, https://github.com/dotnet/runtime/pull/50675

**Comment by EgorBo** [comment] 2021-04-09 19:17
I'd be nice to somehow fix the regression but I'd love https://github.com/dotnet/runtime/pull/50675 to stay anyway as I'm going to work on the inliner at some point and an ability to recognize some (foldable) calls is very helpful (e.g. https://github.com/dotnet/runtime/pull/50784)

**Comment by tannergooding** [comment] 2021-04-10 01:36
CC. @AndyAyersMS, @jkotas 

This looks to be the "true" cost (about 8% worst case) of #50675, since crossgen/prejit will be resolving the method tokens for basically every method.
I imagine this is also where caching the tokens would help the most. Since we are prejit, we will end up resolving all these tokens eventually anyways.

**Comment by AndyAyersMS** [comment] 2021-04-10 01:54
> Since we are prejit, we will end up resolving all these tokens eventually anyways.

If that was the case, and re-resolving an already resolved token is cheap, I would not have expected much of a regression. So either:
* re-resolving is not as cheap as we thought
* or the subsequent call to `eeGetCallInfo` is the part that is costly
* or we are doing a lot of speculative resolution we never did before.

My bet would be on `eeGetCallInfo`, I think it is doing a lot more work than we need here (we just need the method handle and a few flags)....

**Comment by tannergooding** [comment] 2021-04-10 15:35
> My bet would be on eeGetCallInfo, I think it is doing a lot more work than we need here (we just need the method handle and a few flags)....

We're only passing in `CORINFO_CALLINFO_KINDONLY` (and `CORINFO_CALLINFO_CALLVIRT` if its a `callvirt`) to try and limit the work done. If there is another API that does even less work, I'm happy to switch:
```cpp
impResolveToken(codeAddr, &resolvedToken, CORINFO_TOKENKIND_Method);
eeGetCallInfo(&resolvedToken,
              (prefixFlags & PREFIX_CONSTRAINED) ? &constrainedResolvedToken : nullptr,
              combine(CORINFO_CALLINFO_KINDONLY,
                      (opcode == CEE_CALLVIRT) ? CORINFO_CALLINFO_CALLVIRT : CORINFO_CALLINFO_NONE),
              &callInfo);
```

**Comment by jkotas** [comment] 2021-04-11 21:01
#51088 will make it a bit cheaper. There is a lot of other useless work that the speculative getCallInfo does:
- Compute class and method flags for the target
- Compute method signature
Do you expect that these will be used? If not, we can add more flags to supress them.

**Comment by trylek** [comment] 2021-04-11 23:39
Thanks for all the valuable clarifications in this thread. Do we believe it's still accurate to label this bug as "area-crossgen2-coreclr"? Can someone please either help me understand what's the expected Crossgen2 ask or consider changing the label?

**Comment by tannergooding** [comment] 2021-04-12 00:46
> Do you expect that these will be used? If not, we can add more flags to supress them.

@jkotas, right now we only care about "is this method an intrinsic?" (`CORINFO_FLG_INTRINSIC` or `CORINFO_FLG_JIT_INTRINSIC`) and the method handle so we can call `getIntrinsicID` and `lookupNamedIntrinsic`, respectively.

I doubt, at least initially, there will be anything interesting we want to do with arbitrary/non-intrinsic method tokens, so I think we can filter down to just those flags and the handle.
* `lookupNamedIntrinsic` will independently call `getMethodSig` using the method handle for a couple paths, but that will be more "pay for play" than doing it for every token

**Comment by jkotas** [comment] 2021-04-12 01:25
"is this method an intrisic?" check can be done on the method handle returned by resolvedToken. It should not be necessary to call `eeGetCallInfo` at all to answer this question.

**Comment by tannergooding** [comment] 2021-04-12 01:45
What's the right way to get the `CORINFO_FLG_INTRINSIC` and `CORINFO_FLG_JIT_INTRINSIC` flags without calling `eeGetCallInfo`? We need to know each flag, specifically, so we know which of `getIntrinsicID` or `lookupNamedIntrinsic` to call.

**Comment by jkotas** [comment] 2021-04-12 01:58
You can introduce a new dedicated method that just returns whether the method handle is intrinsic. An example of similar prior art is `isValueClass` that is redundant with `CORINFO_FLG_VALUECLASS`.

>  so we know which of getIntrinsicID or lookupNamedIntrinsic to call.

I would use this as an opportunity to cleanup the handling of intrinsics, only implemented the `lookupNamedIntrinsic ` path - convert the old-style `getIntrinsicID` intrinsics to the new style as necessary.

**Closed** 2021-04-14 03:03 UTC
Labels: arch-x64, area-crossgen2-coreclr, in pr, os-linux, tenet-performance, tenet-performance-benchmarks
