### ISSUE TITLE
Publishing a .NET Core app as a single file makes file names disappear from stack traces

### ISSUE THREAD

**Issue by 0xced** [dotnet/runtime#34187] opened 2020-03-27 10:07 UTC
Here is an example to reproduce this issue.

MyApp.csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
</Project>
```
Program.cs:
```csharp
using System;

namespace MyApp
{
    internal static class Program
    {
        private static void Main()
        {
            try
            {
                throw new NotImplementedException();
            }
            catch (Exception exception)
            {
                Console.WriteLine(exception.StackTrace);
            }
        }
    }
}
```

✅ Publish as self-contained and run → file information and line number is displayed in the stack trace.
```
dotnet publish --nologo --verbosity quiet --output self-contained --configuration Release --runtime win-x64 --self-contained true && .\self-contained\MyApp.exe
   at MyApp.Program.Main() in C:\Projects\Experiments\MyApp\Program.cs:line 11
```

❌ Publish as singe file and run → file information and line number have disappeared from the stack trace.
```
dotnet publish --nologo --verbosity quiet --output single-file --configuration Release --runtime win-x64 /p:PublishSingleFile=true && .\single-file\MyApp.exe
   at MyApp.Program.Main()
```

Tested on Windows 10 version 1809 (build 17763.1039) and the .NET Core SDK 3.1.201.

Is there some other option to enable in order to make file and line information work with single file publishing?

**Comment by 0xced** [comment] 2020-03-27 11:43
After digging a bit more I found that you need to add `<DebugType>embedded</DebugType>` in your project file (or run `dotnet publish` with ` /p:DebugType=embedded`) to get file information and line numbers in the stack traces.

But if you try to trim the single executable (with `/p:PublishTrimmed=true`) then the file information and line numbers will not be present in stack traces (even when setting the debug type to embedded).

**Comment by swaroop-sridhar** [comment] 2020-03-27 22:08
@0xced  You can also use the `/p:IncludeSymbolsInSingleFile=true` setting to get the PDB file packaged into the single-file bundle. This will also solve your problem about line numbers. Bit Id' recommend the `/p:DebugType=embedded` solution.

In .net 5 single-file will not extract the app to a separate directory, and shouldn't have this conflict. I'll keep the issue open in order to test for the case. Thanks.

**Comment by swaroop-sridhar** [comment] 2020-03-27 22:09
I think the `PublishTrimmed` issue is the same as https://github.com/dotnet/runtime/issues/33386

**Comment by swaroop-sridhar** [comment] 2020-06-25 00:31
@mikem8361  wrote: 

"It looks like the symbol support in the runtime needs the full assembly path to open and extract the PDB info needed to then open the PDB to get the line/source info. There is support for “in-memory” modules but they require an “in-memory” PDB which normally happens with the Assembly.Load(byte[], byte[]) or AssemblyLoadContext.LoadFromStream() reflection APIs (a special case).

For the single-file app case where there is no physical module file to open, we could treat they kind of like in-memory modules and get the PDB info that way.  There is code in the get line/source info path to do it this way but it is commented out because of an issue (#18423) with how modules are laid out in-memory.

Here is a rough path through the runtime code to the System.Private.CoreLib stack trace code to the System.Diagnostics.StackTrace code that actually gets the line/source info from the PDB:

Starts here with the GetStackFramesInternal() FCALL:
https://github.com/dotnet/runtime/blob/02489cdc20f1562daa8b663b2ccc3f1840a8f347/src/coreclr/src/vm/debugdebugger.cpp#L326

Here is where the assembly path is expected and passed to the StackFrameHelper (along with a bunch of other info):
https://github.com/dotnet/runtime/blob/02489cdc20f1562daa8b663b2ccc3f1840a8f347/src/coreclr/src/vm/debugdebugger.cpp#L768

Where the StackFrameHelper gets called:
https://github.com/dotnet/runtime/blob/02489cdc20f1562daa8b663b2ccc3f1840a8f347/src/coreclr/src/System.Private.CoreLib/src/System/Diagnostics/StackFrameHelper.cs#L96

Which loads System.Diagnostics.StackTrace and calls it here:
https://github.com/dotnet/runtime/blob/071bb6ba5d1ca9eaca0b07061edaf05ed3c398ef/src/libraries/System.Diagnostics.StackTrace/src/System/Diagnostics/StackTraceSymbols.cs#L53

To get this to work, the commented out/issue needs to be fixed by passing a “IsFileLayout” flag though all these layers and passing it to the PEReader constructor isLoadedImage parameter:
https://github.com/dotnet/runtime/blob/071bb6ba5d1ca9eaca0b07061edaf05ed3c398ef/src/libraries/System.Diagnostics.StackTrace/src/System/Diagnostics/StackTraceSymbols.cs#L166

I hope this helps."

**Comment by CyberSinh** [comment] 2021-01-25 00:23
I tested the simple sample code provided on the first post under .NET 5 and I can confirm the source filename and line number is not shown, even with `<DebugType>embedded</DebugType>`.

Here are the publishing settings used:
```xml
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration>Release</Configuration>
    <Platform>x64</Platform>
    <PublishDir>bin\Release\net5.0\publish\</PublishDir>
    <PublishProtocol>FileSystem</PublishProtocol>
    <TargetFramework>net5.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>True</PublishSingleFile>
    <PublishReadyToRun>False</PublishReadyToRun>
    <PublishTrimmed>False</PublishTrimmed>
    <DebugType>embedded</DebugType>
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
</Project>
```
Should I wait .NET 6 for better debugging support with `PublishSingleFile`? Any other idea? 

Thanks.

**Comment by 0xced** [comment] 2021-01-25 11:35
@CyberSinh Your sample project file includes the `DebugType` twice, once with `embedded` and once with `full`. You should probably remove the `full` if you want to make sure to test with `embedded`.

```xml
<DebugType>embedded</DebugType>
<DebugType>full</DebugType>
```

**Comment by CyberSinh** [comment] 2021-01-25 11:48
Sorry, it was a copy-paste error. I edited my post. The issue is here with just one `DebugType` tag.

**Comment by jkotas** [comment] 2021-04-19 16:55
Dup of #51461

**Comment by tommcdon** [comment] 2021-04-19 19:44
> Dup of #51461

Closing

**Closed by tommcdon** 2021-04-19 19:44 UTC
Labels: area-Diagnostics-coreclr
