### ISSUE TITLE
DacDbiArrayList<T>::Dealloc() released the memory through the wrong allocator

### ISSUE THREAD

**Issue by cshung** [dotnet/runtime#57577] opened 2021-08-17 16:08 UTC
The memory associated with `m_list` was allocating through `forDbi` here.

https://github.com/dotnet/runtime/blob/bbf4e797a13984acee37b19d0a79217188824301/src/coreclr/debug/inc/dacdbistructures.inl#L96-L106

But then it is released through the CRT.

https://github.com/dotnet/runtime/blob/bbf4e797a13984acee37b19d0a79217188824301/src/coreclr/debug/inc/dacdbistructures.inl#L62-L79

At the very least, this is causing an assertion in debug build, and it is unclear what the consequences are in the release build.

**Comment by tommcdon** [comment] 2021-08-17 18:08
@cshung nice catch!  Moving to .net 7 as this appears to be pre-existing and there are no known issues on release builds.

**Comment by AaronRobinsonMSFT** [comment] 2021-08-25 00:30
This appears to have been introduced in https://github.com/dotnet/runtime/pull/55945

**Comment by AaronRobinsonMSFT** [comment] 2021-08-25 02:41
After locally reverting https://github.com/dotnet/runtime/pull/55945, I am getting far less asserts. However, occasionally I get much more catastrophic crashes. This seems like a very serious issue.

**Comment by AaronRobinsonMSFT** [comment] 2021-09-03 04:52
@tommcdon This is becoming a rather acute issue for local development. I am unable to debug a locally built debug/checked runtime in WinDBG without hundreds of asserts popping up.

**Comment by tommcdon** [comment] 2021-09-07 20:15
Adding @hoyosjs @mikem8361.  Is the issue specific to placement new and delete[] operators in the DAC?  I am wondering if placement delete[] is needed here, or if we need to change the alloc/delloc pattern being used here.

**Comment by hoyosjs** [comment] 2021-09-07 21:26
The problem is there is a mismatch of allocators - we noticed it earlier as a lot of the workstreams changed the allocators. This is just one case. Another was observed in the usage of STL constructs in the DAC. For this case the deallocation should use the deallocation through the custom allocator as well.

**Closed** 2021-09-09 01:35 UTC
Labels: area-Diagnostics-coreclr, in pr
