### ISSUE TITLE
.Net 6.0 XDocument XML Giving Wrong Value of an Element (Bug)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#99899] opened 2024-03-18 12:37 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Net-60-XDocument-XML-Giving-Wrong-Valu/10617394)._

---
Hi

Please see the Screenshot.

How come the Element ‘Student1’ has a Value ‘Four Bungalows’?

‘Four Bungalows’ is actually the Value of the ‘Student1\\StudentAddress’ Element.

The Value for ‘Student1’ should be an Empty String, as it has No Value in it, and it just has a Child Element ‘StudentAddress’.

This is a Bug for sure. Or the logic XDocument uses is faulty.

Regards  
bikramjeeth

![image](https://github.com/dotnet/runtime/assets/3184057/b0a8160d-d716-4b93-86ed-fae0ae98d92d)

---
#### Feedback Bot on 3/18/2024, 04:56 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by colejohnson66** [comment] 2024-03-18 12:49
This is not a bug, and, in fact, is documented.

Per the [documentation](https://learn.microsoft.com/en-us/dotnet/api/system.xml.linq.xelement.value?view=net-8.0), `XElement.Value` contains "[...] the concatenated text contents of this element".

From the example:

```cs
XElement el = XElement.Parse("<Root>This is <b>mixed</b> content</Root>");  
Console.WriteLine("{0}", el.Value);  
```

This outputs:

```
This is mixed content
```

It's conceptually similar to HTML/JS' `innerText` property.

**Comment by garevaul** [comment] 2024-03-19 02:50
Ok, but My situation is like this,

I Need to Add an Element 'StudentAddress' to the Element 'Student1', But ONLY CONDITION TO, that if Element 'Student1' Does Not have its own value. This means that 'Student1' is More like a Container Element.

So in the example below, the value for Element 'Students\Student1' is an Empty String.
So, 'Student1' is like a Container Element. Which means there is No Value of Element 'Student1'.
SO WE CAN ADD 'StudentAddress'.

```
<Root>
  <Students>
    <Student1></Student1>
    <Student2>Bill Gates2</Student2>
  </Students>
</Root>
```

Now When we Add an Element 'StudentAddress' within the Container Element 'Student1', it is Done Correctly. We Get >>

```
<Root>
  <Students>
    <Student1>
        <StudentAddress>Four Bungalows</StudentAddress>
    </Student1>
    <Student2>Bill Gates2</Student2>
  </Students>
</Root>
```


BUT Now that 'StudentAddress' has been added to 'Student1', THE NEXT TIME My Code Checks whether 'Student1' is a Container Type of an Element, IT WILL BE FALSE because Even though 'Student1' Does Not Have a Value, and is Still a Container Type of an Element, BUT THIS TIME when we Query on VALUE of 'Student1', it returns back the 'StudentAddress' Value, and So making it an Element having its own value (even though it DOES NOT HAVE its Own value).

Regards
Bikramjeeth

**Comment by jeffhandley** [comment] 2024-03-21 22:52
Hi @garevaul. When using `XElement`, you can check its other properties to determine if it's empty or contains other elements rather than relying on `Value` alone. Specifically, you can check [`XElement.HasElements`](https://learn.microsoft.com/dotnet/api/system.xml.linq.xelement.haselements?view=net-8.0#system-xml-linq-xelement-haselements) and [`IsEmpty`](https://learn.microsoft.com/dotnet/api/system.xml.linq.xelement.isempty?view=net-8.0).

Here's some code that shows how you can distinguish the different states of a Student element for the scenarios you described.

```c#
using System.Xml.Linq;
using System.Diagnostics;

XDocument srcTree = new XDocument(
    new XElement("Root",
        new XElement("Students",
            new XElement("Student1"),
            new XElement("Student2", "Bill Gates2"),
            new XElement("Student3",
                new XElement("StudentAddress", "Four Bungalows")
            )
        )
    )
);

XElement root = srcTree.Element("Root")!;
XElement students = root.Element("Students")!;

XElement student1 = students.Element("Student1")!;
Debug.Assert(student1.IsEmpty == true);
Debug.Assert(student1.HasElements == false);
Debug.Assert(student1.Value == string.Empty);

XElement student2 = students.Element("Student2")!;
Debug.Assert(student2.IsEmpty == false);
Debug.Assert(student2.HasElements == false);
Debug.Assert(student2.Value == "Bill Gates2");

XElement student3 = students.Element("Student3")!;
Debug.Assert(student3.IsEmpty == false);
Debug.Assert(student3.HasElements == true);
Debug.Assert(student3.Value == "Four Bungalows");

Console.WriteLine(srcTree.ToString());
```

Since this is working as designed and expected, I'm closing the issue. I hope the above code helps.

**Closed by jeffhandley** 2024-03-21 22:52 UTC
Labels: area-System.Xml, untriaged
