### ISSUE TITLE
GC crashes application when using AssemblyBuilder

### ISSUE THREAD

**Issue by evo01** [dotnet/runtime#13456] opened 2019-09-23 05:45 UTC
Howdy,

I am using .NET Core 3.0, current preview release, and the following code crashes the application immediately.  It appears assemblies cannot be collected as if you get rid of the GC.Collect, and wait for the amount of memory being used to reach 160 MB, the application attempts to GC and it crashes then too.

```
        static void Main(string[] args)
        {
            while (true)
            {
                AssemblyBuilder.DefineDynamicAssembly(new AssemblyName("Test.dll"), AssemblyBuilderAccess.RunAndCollect);

                for (int i = 0; i < 3; i++)
                {
                    GC.Collect(i);   
                }
            }
        }
```

**Comment by hoyosjs** [comment] 2020-03-31 06:33
Verified dupe of dotnet/runtime#2317. Fix is available in master and in 3.1 after 3.1.4.

**Closed by hoyosjs** 2020-03-31 06:33 UTC
Labels: area-Diagnostics-coreclr, bug, p1
