### ISSUE TITLE
[x86] SequenceEqual returns false for equal spans

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#65292] opened 2022-02-14 02:22 UTC
Run: [runtime-libraries-coreclr outerloop 20220213.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1610237&view=ms.vss-test-web.build-test-results-tab&runId=44860608&paneView=debug&resultId=102808)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_release-Windows.Amd64.Server2022.Open

- System.IO.Tests.UnseekableDeviceFileStreamConnectedConformanceTests.ReadWrite_Success_Large(mode: AsyncMemory, writeSize: 10485760, startWithFlush: True)
- System.IO.Tests.AnonymousPipeFileStreamConnectedConformanceTests.ReadWrite_Success_Large(mode: SyncArray, writeSize: 10485760, startWithFlush: False)

```
**Error message:**
```
Showing first 10 differences
Total number of differences: 0 out of 10485760


Stack trace
   at System.AssertExtensions.SequenceEqual[T](ReadOnlySpan`1 expected, ReadOnlySpan`1 actual) in /_/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs:line 473
   at System.IO.Tests.ConnectedStreamConformanceTests.ReadWrite_Success(ReadWriteMode mode, Int32 writeSize, Boolean startWithFlush) in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 1765
   at System.IO.Tests.ConnectedStreamConformanceTests.ReadWrite_Success_Large(ReadWriteMode mode, Int32 writeSize, Boolean startWithFlush) in /_/src/libraries/Common/tests/StreamConformanceTests/System/IO/StreamConformanceTests.cs:line 1719
--- End of stack trace from previous location ---
```

|Build|Kind|Start Time|
|---|---|---|
[1612202](https://dev.azure.com/dnceng/public/_build/results?buildId=1612202)|Rolling|2022-14-02|
[1613425](https://dev.azure.com/dnceng/public/_build/results?buildId=1613425)|Rolling|2022-15-02|
[1616198](https://dev.azure.com/dnceng/public/_build/results?buildId=1616198)|Rolling|2022-16-02|
[1616876](https://dev.azure.com/dnceng/public/_build/results?buildId=1616876)|Rolling|2022-16-02|
[1617545](https://dev.azure.com/dnceng/public/_build/results?buildId=1617545)|Rolling|2022-17-02|
[1618267](https://dev.azure.com/dnceng/public/_build/results?buildId=1618267)|Rolling|2022-17-02|

**Comment by adamsitnik** [comment] 2022-02-14 10:49
To my surprise I am able to reproduce it locally:

```cmd
.\build.cmd -c Release -subset clr+libs+libs.tests -arch x86
.\dotnet.cmd build .\src\libraries\System.IO.FileSystem\tests\System.IO.FileSystem.Tests.csproj /t:Test /p:Configuration=Release /p:TargetArchitecture=x86 /p:Outerloop=true
```

**Comment by adamsitnik** [comment] 2022-02-14 11:28
> Total number of differences: 0 out of 10485760

It seems to be a bug in `System.Memory` or codegen, as `SequenceEquals` returns true, but the helper fails to find any differences:

https://github.com/dotnet/runtime/blob/e23382c32bf03d3fea5a2f1157a99148a51ca3f4/src/libraries/Common/tests/TestUtilities/System/AssertExtensions.cs#L445-L471


I was able to reproduce it using the following test:

```cs
public class Repro
{
    [Fact]
    public void TryToMimic()
    {
        while (true)
        {
            byte[] writerBytes = RandomNumberGenerator.GetBytes(10 * 1024 * 1024);
            var readerBytes = new byte[writerBytes.Length];

            writerBytes.CopyTo(readerBytes, 0);

            Assert.True(writerBytes.SequenceEqual(readerBytes));
        }
    }
}
```

@EgorBo is there any chance you could take a look?

**Comment by EgorBo** [comment] 2022-02-14 12:02
Thanks for the minimal repro, looking at it now

**Comment by EgorBo** [comment] 2022-02-15 15:25
I can't reproduce it locally 🙁 the 
```
.\build.cmd -c Release -subset clr+libs+libs.tests -arch x86
.\dotnet.cmd build .\src\libraries\System.IO.FileSystem\tests\System.IO.FileSystem.Tests.csproj /t:Test /p:Configuration=Release /p:TargetArchitecture=x86 /p:Outerloop=true
```
and the repro specifically finish just fine for me (win10-x64, core i7 8700K)

**Comment by EgorBo** [comment] 2022-02-15 15:40
> > I can't reproduce it locally 🙁 the
> 
> I can't always reproduce it when running all `System.IO.FileSystem` tests, but if I run the small repro for a minute or two it fails. Have you tried that?

ah, let me try to run it a bit longer then 👍

**Comment by jkotas** [comment] 2022-02-15 16:30
We have number of other tests failing on Windows x86 intermittently with very similar symptoms:
- https://github.com/dotnet/runtime/issues/65353
- https://github.com/dotnet/runtime/issues/65235
- https://github.com/dotnet/runtime/issues/65026

It looks like a Windows x86 specific GC hole to me.

**Comment by adamsitnik** [comment] 2022-02-15 16:50
> It looks like a Windows x86 specific GC hole to me.

@jkotas could you please explain what makes you think it's a GC hole? I am just curious what symptoms GC holes have in general.

I was expecting it to be a miss-aligned read since it does not reproduce always and there is no hang/AV.

**Comment by jkotas** [comment] 2022-02-15 16:57
https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/clr-code-guide.md#211-how-gc-holes-are-created explains what GC hole is.

The typical manifestations of GC holes are intermittent crashes and data corruptions.

**Comment by EgorBo** [comment] 2022-02-15 17:41
> Is my understanding correct that switching from managed to native memory should "solve" the GC hole issue for my small repro ?

GC holes can be anywhere even in a simple C#-only code where JIT doesn't report gcinfo correctly so when GC interupts it doesn't update all regs correctly.

Are you on the most recent Main btw?

**Comment by adamsitnik** [comment] 2022-02-15 17:42
I am on:

```log
Author:			Jakob Botsch Nielsen <Jakob.botsch.nielsen@gmail.com>
Date:			1 day ago (2/14/2022 11:08:08 AM)
Committer:		GitHub <noreply@github.com>
Commit hash:	e23382c32bf03d3fea5a2f1157a99148a51ca3f4
Child:			Commit index
Parent:			6e05d78d

Keep information about CSE defs on assignment nodes (#64896)

Reuse the gtCSEnum field on assignments to signal "this is a performed
CSE def". gtCanSwapOrder uses the CSE def information to reason about
evaluation order, so without keeping this information we could risk
substitution a CSE def, followed by reordering operands, and then
finally substituting a CSE use.

Fix #64883
Contained in branches:
main
```

**Comment by adamsitnik** [comment] 2022-02-15 17:43
If I run just this unit test, I am not able to repro.

Should I get a memory dump?

**Comment by EgorBo** [comment] 2022-02-15 17:48
> If I run just this unit test, I am not able to repro.
> 
> Should I get a memory dump?

wouldn't hurt I'd guess.

I've been running your repro in the FileSystem.IO test suite for 7 minutes already and still no signs of the bug

**Comment by EgorBo** [comment] 2022-02-15 18:04
> Just checking: Are you running the exact same build flavor (release libraries + release CoreCLR x86)?

I've tried both `release libs + release clr` and `release libs + checked clr`

**Comment by adamsitnik** [comment] 2022-02-15 18:09
I've pushed my exact repro to https://github.com/adamsitnik/runtime/tree/issue65292repro

And uploaded full dump to [OneDrive](https://microsofteur-my.sharepoint.com/:u:/g/personal/adsitnik_microsoft_com/EWuQPxctXV9Ik_Inmhp5HZMBeT72OA0_Wjbtm_SAF7SHTw?e=2Bdue6)

**Comment by jkotas** [comment] 2022-02-15 18:29
Could you please reproduce the crash with these env variables set: https://github.com/dotnet/runtime/issues/45557#issuecomment-738547930

And then upload the dump together with the binaries and .pdb symbols.

**Comment by jakobbotsch** [comment] 2022-02-15 20:23
#63763 changed some behavior of GC reporting around calls. Can you try to apply #65397 and see if you still reproduce it @adamsitnik?

**Comment by EgorBo** [comment] 2022-02-15 20:28
Yeah I was about to ask the same, I was not able to repro the problem even with your bits

**Comment by jkotas** [comment] 2022-02-15 23:23
@adamsitnik The dump has `COMPlus_LogFacility=524289`. Could you please collect one with `COMPlus_LogFacility=0x00080001`? The COMPlus switches are hex by default, so specifying 524289 is not equivalent to `0x00080001`.

**Comment by adamsitnik** [comment] 2022-02-16 10:33
> Can you try to apply https://github.com/dotnet/runtime/pull/65397 and see if you still reproduce it

I am still able to reproduce using provided PR.

**Comment by EgorBo** [comment] 2022-02-16 16:50
I followed the exact steps you listed in that txt and ran the test for like 20 minutes - no crashes so far 😐 that's becoming interesting, try to understand the dump now

**Comment by adamsitnik** [comment] 2022-02-16 18:06
> I followed the exact steps you listed in that txt and ran the test for like 20 minutes - no crashes so far 

I wonder if it would help if you copy-pasted the class that defines the test and basically increase the number of exact the same test running in parallel. (repro1 repro2 etc)

I am also not sure why I can easily repro it and others can't. My machine is AMD x64, tomorrow I'll try to repro it on my Intel hardware to see if it makes a difference. My other guess is different intrinsics available.

**Comment by EgorBo** [comment] 2022-02-16 18:21
> > I followed the exact steps you listed in that txt and ran the test for like 20 minutes - no crashes so far
> 
> I wonder if it would help if you copy-pasted the class that defines the test and basically increase the number of exact the same test running in parallel. (repro1 repro2 etc)
> 
> I am also not sure why I can easily repro it and others can't. My machine is AMD x64, tomorrow I'll try to repro it on my Intel hardware to see if it makes a difference. My other guess is different intrinsics available.

hm.. interesting, can you paste your CPU-Z or whatever, also windows version just in case

**Comment by jkotas** [comment] 2022-02-16 18:27
The stresslog shows that the thread got suspended in the middle of SequenceEqual for last GC:
```
7f0c  11.636214853 : `GCROOTS`            Scanning Frameless method 0A625568 (System.SpanHelpers.SequenceEqual(Byte ByRef, Byte ByRef, UIntPtr)) EIP = 153A8313 &EIP = 0CCFBA98
7f0c  11.636214473 : `GCROOTS`            Scanning ExplicitFrame 0EF8CDB4 AssocMethod = 00000000 frameVTable = 50BE091C (coreclr!RedirectedThreadFrame::`vftable')
7f0c  11.636214292 : `GC`GCROOTS`         } Starting scan of Thread 0CA13D90 ID = c
```

The IP corresponds to this code:

```
...
153a830d c4e17d100401    vmovupd ymm0,ymmword ptr [ecx+eax]
>>> 153a8313 c4e17d740402    vpcmpeqb ymm0,ymm0,ymmword ptr [edx+eax]
153a8319 c4e17dd7f8      vpmovmskb edi,ymm0
...
```

Notice that this is using AVX-256 instructions and registers. I think that the most likely cause of this problem is problem with preserving values of AVX-256 ymm registers during GC suspension on x86.

We had problems with this before - see https://github.com/dotnet/runtime/pull/47212 and linked bugs.

@adamsitnik Could you please run the simple repo from https://github.com/dotnet/runtime/issues/47016#issuecomment-760567054 on your machine to see whether it hits the problem?

@VSadov Could you please take a look?

**Comment by VSadov** [comment] 2022-02-16 18:41
I will take a look. I have AMD machines.

**Comment by VSadov** [comment] 2022-02-16 19:05
So far I tried the original repro from  https://github.com/dotnet/runtime/issues/47016#issuecomment-760567054 on Ryzen 5950 (new) and 2600 (old-ish) and there is no repro with dotnet 6.0

Will try the new repro and will try recent 7.0 bits. Maybe it is something new.

**Comment by tannergooding** [comment] 2022-02-16 19:18
> So far I tried the original repro from https://github.com/dotnet/runtime/issues/47016#issuecomment-760567054 on Ryzen 5950 (new) and 2600 (old-ish) and there is no repro with dotnet 6.0

Some BIOS will let you toggle a switch forcing the ERMSB bit to return true. It's an available option on the past few Asus ROG Crosshair boards I've had (for Zen, Zen2, and Zen3).

**Comment by VSadov** [comment] 2022-02-16 20:12
@tannergooding - the theory is that AMD spuid does not report ERMSB (is there a way to check?) and therefore uses a different codepath in memcopy.

**Comment by VSadov** [comment] 2022-02-16 20:15
so far I was unable to repro this issue. 

I am using the following repro compiled as a self-contained 7.0 win-x86 app and clr bits replaced with locally built bits for e23382c32bf03d3fea5a2f1157a99148a51ca3f4  

```cs
using System.Runtime.InteropServices;

class Program
{
    static void GCLoop()
    {
        for (; ; )
        {
            GC.Collect();
            Thread.Sleep(1);
        }
    }

    static unsafe void Main()
    {
        new Thread(GCLoop).Start();

        const int size = 10 * 1024 * 1024;

        while (true)
        {
            void* writerBytesPointer = NativeMemory.Alloc(size);
            void* readerBytesPointer = NativeMemory.Alloc(size);

            try
            {
                Span<byte> writerBytes = new Span<byte>(writerBytesPointer, size);
                Span<byte> readerBytes = new Span<byte>(readerBytesPointer, size);

                for (int i = 0; i < writerBytes.Length; i++) writerBytes[i] = (byte)i;
                writerBytes.CopyTo(readerBytes);

                if (!writerBytes.SequenceEqual(readerBytes))
                {
                    Console.WriteLine("Hello");
                }

                // Console.Write('.');
            }
            finally
            {
                NativeMemory.Free(readerBytesPointer);
                NativeMemory.Free(writerBytesPointer);
            }
        }
    }
}
```

**Comment by VSadov** [comment] 2022-02-16 20:40
@adamsitnik - can you try my repro above in your environment?

**Comment by VSadov** [comment] 2022-02-16 21:02
Other things that I tried to force a repro:
- running System.IO.FileSystem.Tests in a loop 30 times - no failures.
- tried my repro with the zipped up bits that @adamsitnik uploaded. no difference..

**Comment by tannergooding** [comment] 2022-02-16 21:06
> the theory is that AMD cpuid does not report ERMSB (is there a way to check?) and therefore uses a different codepath in memcopy.

Right. I was indicating that it may be reporting "supported" on your CPU based on a BIOS setting; which might prevent you from being able to reproduce.

**Comment by filipnavara** [comment] 2022-02-16 21:32
> AMD cpuid does not report ERMSB (is there a way to check?)

CPU-Z is not very detailed but the `CoreInfo -f` (from SysInternals) should be detailed enough. For reference, this is the output on AMD Ryzen 7 5700G where ERMSB is listed as supported:

```
Coreinfo v3.52 - Dump information on system CPU and memory topology
Copyright (C) 2008-2021 Mark Russinovich
Sysinternals - www.sysinternals.com


AMD Ryzen 7 5700G with Radeon Graphics
AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD
Microcode signature: 00000000
HTT             *       Multicore
CET             *       Supports Control Flow Enforcement Technology
Kernel CET      -       Kernel-mode CET Enabled
User CET        *       User-mode CET Allowed
HYPERVISOR      *       Hypervisor is present
VMX             -       Supports Intel hardware-assisted virtualization
SVM             -       Supports AMD hardware-assisted virtualization
X64             *       Supports 64-bit mode

SMX             -       Supports Intel trusted execution
SKINIT          -       Supports AMD SKINIT
SGX             -       Supports Intel SGX

NX              *       Supports no-execute page protection
SMEP            *       Supports Supervisor Mode Execution Prevention
SMAP            *       Supports Supervisor Mode Access Prevention
PAGE1GB         *       Supports 1 GB large pages
PAE             *       Supports > 32-bit physical addresses
PAT             *       Supports Page Attribute Table
PSE             *       Supports 4 MB pages
PSE36           *       Supports > 32-bit address 4 MB pages
PGE             *       Supports global bit in page tables
SS              -       Supports bus snooping for cache operations
VME             *       Supports Virtual-8086 mode
RDWRFSGSBASE    *       Supports direct GS/FS base access

FPU             *       Implements i387 floating point instructions
MMX             *       Supports MMX instruction set
MMXEXT          *       Implements AMD MMX extensions
3DNOW           -       Supports 3DNow! instructions
3DNOWEXT        -       Supports 3DNow! extension instructions
SSE             *       Supports Streaming SIMD Extensions
SSE2            *       Supports Streaming SIMD Extensions 2
SSE3            *       Supports Streaming SIMD Extensions 3
SSSE3           *       Supports Supplemental SIMD Extensions 3
SSE4a           *       Supports Streaming SIMDR Extensions 4a
SSE4.1          *       Supports Streaming SIMD Extensions 4.1
SSE4.2          *       Supports Streaming SIMD Extensions 4.2

AES             *       Supports AES extensions
AVX             *       Supports AVX instruction extensions
AVX2            *       Supports AVX2 instruction extensions
AVX-512-F       -       Supports AVX-512 Foundation instructions
AVX-512-DQ      -       Supports AVX-512 double and quadword instructions
AVX-512-IFAMA   -       Supports AVX-512 integer Fused multiply-add instructions
AVX-512-PF      -       Supports AVX-512 prefetch instructions
AVX-512-ER      -       Supports AVX-512 exponential and reciprocal instructions
AVX-512-CD      -       Supports AVX-512 conflict detection instructions
AVX-512-BW      -       Supports AVX-512 byte and word instructions
AVX-512-VL      -       Supports AVX-512 vector length instructions
FMA             *       Supports FMA extensions using YMM state
MSR             *       Implements RDMSR/WRMSR instructions
MTRR            *       Supports Memory Type Range Registers
XSAVE           *       Supports XSAVE/XRSTOR instructions
OSXSAVE         *       Supports XSETBV/XGETBV instructions
RDRAND          *       Supports RDRAND instruction
RDSEED          *       Supports RDSEED instruction

CMOV            *       Supports CMOVcc instruction
CLFSH           *       Supports CLFLUSH instruction
CX8             *       Supports compare and exchange 8-byte instructions
CX16            *       Supports CMPXCHG16B instruction
BMI1            *       Supports bit manipulation extensions 1
BMI2            *       Supports bit manipulation extensions 2
ADX             *       Supports ADCX/ADOX instructions
DCA             -       Supports prefetch from memory-mapped device
F16C            *       Supports half-precision instruction
FXSR            *       Supports FXSAVE/FXSTOR instructions
FFXSR           *       Supports optimized FXSAVE/FSRSTOR instruction
MONITOR         *       Supports MONITOR and MWAIT instructions
MOVBE           *       Supports MOVBE instruction
ERMSB           *       Supports Enhanced REP MOVSB/STOSB
PCLMULDQ        *       Supports PCLMULDQ instruction
POPCNT          *       Supports POPCNT instruction
LZCNT           *       Supports LZCNT instruction
SEP             *       Supports fast system call instructions
LAHF-SAHF       *       Supports LAHF/SAHF instructions in 64-bit mode
HLE             -       Supports Hardware Lock Elision instructions
RTM             -       Supports Restricted Transactional Memory instructions

DE              *       Supports I/O breakpoints including CR4.DE
DTES64          -       Can write history of 64-bit branch addresses
DS              -       Implements memory-resident debug buffer
DS-CPL          -       Supports Debug Store feature with CPL
PCID            -       Supports PCIDs and settable CR4.PCIDE
INVPCID         *       Supports INVPCID instruction
PDCM            -       Supports Performance Capabilities MSR
RDTSCP          *       Supports RDTSCP instruction
TSC             *       Supports RDTSC instruction
TSC-DEADLINE    -       Local APIC supports one-shot deadline timer
TSC-INVARIANT   *       TSC runs at constant rate
xTPR            -       Supports disabling task priority messages

EIST            -       Supports Enhanced Intel Speedstep
ACPI            -       Implements MSR for power management
TM              -       Implements thermal monitor circuitry
TM2             -       Implements Thermal Monitor 2 control
APIC            *       Implements software-accessible local APIC
x2APIC          -       Supports x2APIC

CNXT-ID         -       L1 data cache mode adaptive or BIOS

MCE             *       Supports Machine Check, INT18 and CR4.MCE
MCA             *       Implements Machine Check Architecture
PBE             -       Supports use of FERR#/PBE# pin

PSN             -       Implements 96-bit processor serial number

PREFETCHW       *       Supports PREFETCHW instruction

Maximum implemented CPUID leaves: 0000000D (Basic), 80000021 (Extended).
Maximum implemented address width: 48 bits (virtual), 48 bits (physical).

Processor signature: 00A50F00
```

**Comment by VSadov** [comment] 2022-02-16 21:37
Thanks @filipnavara . It looks like both AMD machines that I tried to repro on report ERMSB as supported. 
I will check if that can be disabled somehow.

**Comment by filipnavara** [comment] 2022-02-16 21:49
I tried the repro from https://github.com/dotnet/runtime/issues/65292#issuecomment-1042134569 and it prints `Hello` all the time. Does that mean it repros on my machine?

**Comment by VSadov** [comment] 2022-02-16 21:50
Yes!  It is not supposed to print anything.

**Comment by filipnavara** [comment] 2022-02-16 21:51
Where should I ship the machine to? 😂 More realistically, happy to give access to it or test anything that comes along.

**Comment by VSadov** [comment] 2022-02-16 21:52
Is that on the 5700 that you run CoreInfo on?

**Comment by filipnavara** [comment] 2022-02-16 21:56
> Is that on the 5700 that you run CoreInfo on?

Yep.

**Comment by VSadov** [comment] 2022-02-16 22:02
Hmm, the next thing I was going to as is what MSVC build you have, but since you have used an official build, the only difference that I can think of is something in the run environment - like OS or C runtime differences.

**Comment by filipnavara** [comment] 2022-02-16 22:07
Unlikely to make any difference, but here it goes:
- Windows 11 version 10.0.22557.1 (today's Insider build)
- ucrtbase.dll in SysWOW64 is the same version 10.0.22557.1

**Comment by filipnavara** [comment] 2022-02-16 22:14
Is there any rough idea when it started happening? Assuming it's a new/reoccurring thing maybe it's something I can try to bisect?

**Comment by filipnavara** [comment] 2022-02-16 22:42
Actually, it reproduces even on 6.0.100 SDK, so the range may be much bigger than I anticipated, or there is some external trigger factor.

**Comment by VSadov** [comment] 2022-02-16 22:56
Seems like Win11 might be one of the conditions. The original issue was for Server2022 as well.

**Comment by filipnavara** [comment] 2022-02-16 22:57
That sounds plausible. I have several identical nearly machines, will try on Windows 10 one.

**Comment by VSadov** [comment] 2022-02-16 22:57
Yep!!. I got a repro on my mail machine that is Intel (CoffeLake), but runs Win11.

**Comment by filipnavara** [comment] 2022-02-16 23:05
The "sister" machine running Windows 10 doesn't reproduce it, so that is in line with the Windows 11 theory.

**Comment by VSadov** [comment] 2022-02-16 23:12
Preserving AVX registers across suspension points calls into a number of OS APIs. I will debug through that to see if anything changed on Win11.

**Comment by VSadov** [comment] 2022-02-17 02:47
So far I do not see anything unusual - we initialize context storage, get contexts from OS, set contexts... 
Whether the OS returns correct data - I do not know yet, but nothing indicates a failure.

The only API that we call dynamically is `InitializeContext2` to enable context compaction and it is present and we call it. Besides, the context compaction is optional and if I comment out related code, the bug still reproduces.

**Comment by VSadov** [comment] 2022-02-17 07:02
The codepath used by X86 when resuming from suspension uses `memcpu` inside an exception filter to inject the stored context into the exception record. That seems to be messing up the YMM registers on Win11.

In general extended contexts initialized via `InitializeContext`/`InitializeContext2`, even if they contain the same register sets, may be "formatted" differently due to alignment or context compaction. There is `CopyContext` which knows about such details.

I have a fix that fixes the issue that we have here, but I need to think more if that is sufficient or we have a bigger problem as we have other scenarios (i.e. in exception handling) that use `memcpy` with extended contexts.

CC:@janvorli

**Comment by adamsitnik** [comment] 2022-02-17 09:00
> @adamsitnik Could you please run the simple repo from https://github.com/dotnet/runtime/issues/47016#issuecomment-760567054 on your machine to see whether it hits the problem?

@jkotas it does:

```log
PS D:\projects\runtime\artifacts\bin\testhost\net7.0-windows-Release-x86\shared\Microsoft.NETCore.App\7.0.0> .\corerun.exe C:\Users\adsitnik\source\repos\SequenceEqualRepro\bin\Release\net6.0\SequenceEqualRepro.dll
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at SequenceEqualRepro.Program.<Main>g__Work|1_0(Object _) in C:\Users\adsitnik\source\repos\SequenceEqualRepro\Program.cs:line 23
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute() in D:\projects\runtime\src\libraries\System.Private.CoreLib\src\System\Threading\ThreadPoolWorkQueue.cs:line 965
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in D:\projects\runtime\src\libraries\System.Private.CoreLib\src\System\Threading\ThreadPoolWorkQueue.cs:line 715
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() in D:\projects\runtime\src\libraries\System.Private.CoreLib\src\System\Threading\PortableThreadPool.WorkerThread.cs:line 77
   at System.Threading.Thread.StartCallback() in D:\projects\runtime\src\coreclr\System.Private.CoreLib\src\System\Threading\Thread.CoreCLR.cs:line 105
```

**Comment by davidwrighton** [comment] 2022-02-17 22:43
@VSadov I'm pretty sure the only path where AVX registers need careful handling is the restore path used in suspension. Fortunately, the AVX registers are not considered saved state for the purposes of function calls, so EH logic has to tolerate them being trashed anyways.

**Comment by VSadov** [comment] 2022-02-17 23:24
@davidwrighton   Right. extended registers are volatile and thus in a case of software exception that goes via `RaiseException` will not be preserved anyways. I am less sure what is expected in hardware exception case.

In the fix (https://github.com/dotnet/runtime/issues/65292) I am no longer using `ReplaceExceptionContextRecord` to restore suspension context - to separate suspension scenario from exception handling in general. Also because `CopyContext` is Windows - only API.

`ReplaceExceptionContextRecord` seems to be specifically trying to handle extended registers. It could be just for suspension/resume case though. I'd defer to you and @janvorli on this. 
Perhaps support for extended could be removed there once suspension does not call it. 

Ideally, we will switch x86 to the same plan as x64, but it is a bit longer story and I think we need a quick fix for now.

**Comment by filipnavara** [comment] 2022-02-18 15:04
Should this be reopened to track the need for servicing backport?

**Comment by ericstj** [comment] 2022-02-24 18:35
Should this also be ported to Preview2 (if there is time?)

**Comment by jeffschwMSFT** [comment] 2022-02-24 18:45
Preview 2 is basically complete.  We will snap for Preview 3 in the coming weeks.  In the meantime we can provide privates if a workaround is needed.

**Comment by danmoseley** [comment] 2022-02-28 16:23
@MaximLipnin @VSadov I assume this is not blocking anything any more as it is fixed in main and this issue is to track backports?

**Comment by VSadov** [comment] 2022-05-04 00:30
the last tracked piece - porting to 3.1 has been completed. Closing.

**Closed by VSadov** 2022-05-04 00:30 UTC
Labels: arch-x86, os-windows, area-VM-coreclr
