### ISSUE TITLE
[mono][wasm] Unable to find RazorClassLibrary.dll to be lazy loaded later.

### ISSUE THREAD

**Issue by jandupej** [dotnet/runtime#85395] opened 2023-04-26 13:03 UTC
New wasm (windows and linux) build errors have emerged with.
```
C:\helix\work\workitem\e\wbt\nuget\blz_razor_lib_top_yja0qqds.yk3\microsoft.net.sdk.webassembly.pack\8.0.0-preview.4.23224.7\build\Microsoft.NET.Sdk.WebAssembly.Browser.targets(314,5): error BLAZORSDK1001: Unable to find 'RazorClassLibrary.dll' to be lazy loaded later. Confirm that project or package references are included and the reference is used in the project. [C:\helix\work\workitem\e\wbt\blz_razor_lib_top_yja0qqds.yk3\wasm\wasm.csproj]
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=251572
Build error leg or test failing: Wasm.Build.Tests.Blazor.BuildPublishTests.BugRegression_60479_WithRazorClassLib
Pull request: https://github.com/dotnet/runtime/pull/85163

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "Unable to find 'RazorClassLibrary.dll' to be lazy loaded later.",
  "BuildRetry": false,
  "ErrorPattern": "",
  "ExcludeConsoleLog": false
}
```

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[252149](https://dev.azure.com/dnceng-public/public/_build/results?buildId=252149)|dotnet/runtime|[Workloads-Webcil-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=252149&view=ms.vss-test-web.build-test-results-tab&runId=4900314&resultId=100101)||
|[251910](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251910)|dotnet/runtime|[Workloads-Webcil-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251910&view=ms.vss-test-web.build-test-results-tab&runId=4887136&resultId=100101)|dotnet/runtime#85282|
|[251772](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251772)|dotnet/runtime|[Workloads-Webcil-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251772&view=ms.vss-test-web.build-test-results-tab&runId=4883984&resultId=100101)|dotnet/runtime#85313|
|[251720](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251720)|dotnet/runtime|[Workloads-Webcil-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251720&view=ms.vss-test-web.build-test-results-tab&runId=4882186&resultId=100100)|dotnet/runtime#83411|
|[251699](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251699)|dotnet/runtime|[Workloads-Webcil-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251699&view=ms.vss-test-web.build-test-results-tab&runId=4880908&resultId=100101)|dotnet/runtime#74623|
|[251525](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251525)|dotnet/runtime|[Workloads-Webcil-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251525&view=ms.vss-test-web.build-test-results-tab&runId=4880898&resultId=100101)|dotnet/runtime#85288|
|[251680](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251680)|dotnet/runtime|[Workloads-Webcil-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251680&view=ms.vss-test-web.build-test-results-tab&runId=4880424&resultId=100101)|dotnet/runtime#82393|
|[251625](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251625)|dotnet/runtime|[Workloads-Webcil-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251625&view=ms.vss-test-web.build-test-results-tab&runId=4879512&resultId=100101)|dotnet/runtime#85254|
|[250766](https://dev.azure.com/dnceng-public/public/_build/results?buildId=250766)|dotnet/runtime|[Workloads-Webcil-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=250766&view=ms.vss-test-web.build-test-results-tab&runId=4879844&resultId=100101)|dotnet/runtime#85275|
|[251572](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251572)|dotnet/runtime|[Workloads-Webcil-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251572&view=ms.vss-test-web.build-test-results-tab&runId=4878476&resultId=100101)|dotnet/runtime#85163|
|[251562](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251562)|dotnet/runtime|[Workloads-Webcil-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251562&view=ms.vss-test-web.build-test-results-tab&runId=4878420&resultId=100101)|dotnet/runtime#83677|
|[251278](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251278)|dotnet/runtime|[Workloads-Webcil-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251278&view=ms.vss-test-web.build-test-results-tab&runId=4877312&resultId=100101)|dotnet/runtime#85303|
|[251487](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251487)|dotnet/runtime|[Workloads-Webcil-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251487&view=ms.vss-test-web.build-test-results-tab&runId=4876778&resultId=100101)|dotnet/runtime#85317|
|[251474](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251474)|dotnet/runtime|[Workloads-Webcil-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251474&view=ms.vss-test-web.build-test-results-tab&runId=4876360&resultId=100101)|dotnet/runtime#85314|
|[251469](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251469)|dotnet/runtime|[Workloads-Webcil-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251469&view=ms.vss-test-web.build-test-results-tab&runId=4876346&resultId=100101)|dotnet/runtime#85313|
|[251428](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251428)|dotnet/runtime|[Workloads-Webcil-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251428&view=ms.vss-test-web.build-test-results-tab&runId=4875618&resultId=100101)|dotnet/runtime#85310|
|[251361](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251361)|dotnet/runtime|[Workloads-Webcil-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251361&view=ms.vss-test-web.build-test-results-tab&runId=4875048&resultId=100101)|dotnet/runtime#85308|
|[251336](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251336)|dotnet/runtime|[Workloads-Webcil-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251336&view=ms.vss-test-web.build-test-results-tab&runId=4873336&resultId=100100)|dotnet/runtime#83411|
|[251420](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251420)|dotnet/runtime|[Wasm.Build.Tests.Blazor.BuildPublishTests.BugRegression_60479_WithRazorClassLib](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251420&view=ms.vss-test-web.build-test-results-tab&runId=4875470&resultId=100025)|dotnet/runtime#85311|
|[251313](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251313)|dotnet/runtime|[Workloads-Webcil-Wasm.Build.Tests.Blazor.BuildPublishTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=251313&view=ms.vss-test-web.build-test-results-tab&runId=4872026&resultId=100101)|dotnet/runtime#85307|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|4|20|20|

**Comment by maraf** [comment] 2023-04-26 18:04
The test is already disabled on main. Duplicate of https://github.com/dotnet/runtime/issues/85354

**Closed by maraf** 2023-04-26 18:04 UTC
Labels: arch-wasm, blocking-clean-ci, area-Build-mono, Known Build Error
