### ISSUE TITLE
[API Proposal]: IEnumerable<T> Default Implementation for IEnumerable

### ISSUE THREAD

**Issue by Stroniax** [dotnet/runtime#75351] opened 2022-09-09 16:07 UTC
### Background and motivation

`System.Collections.Generic.IEnumerable<T>` implements `System.Collections.IEnumerable`, and initially because there were no default interface implementations this meant that the `GetEnumerator` method must be implemented twice on any type that implements the generic `IEnumerable<T>`. `IEnumerator<T>` implements `IEnumerator`, which means that generally the non-generic `IEnumerable.GetEnumerator()` method will call the generic overload. Therefore it would make sense to have a default implementation of the non-generic `IEnumerable.GetEnumerator()` method to simply return the result of the generic `IEnumerable<T>.GetEnumerator()` method call.

### API Proposal

```csharp
namespace System.Collections.Generic;

public interface IEnumerable<T> : IEnumerable
{
    new IEnumerator<T> GetEnumerator();
   
    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
}
```

### API Usage

```csharp
public class MyValues : IEnumerable<T> {
    public IEnumerator<T> GetEnumerator() {
      yield break;
    }
    // no need to define IEnumerable.GetEnumerator() unless special behavior is required
}
```

**Comment by stephentoub** [comment] 2022-09-09 16:10
Duplicate of https://github.com/dotnet/runtime/issues/29513

**Closed** 2022-09-09 16:37 UTC
Labels: api-suggestion, area-System.Linq, untriaged
