### ISSUE TITLE
Microsoft.Extensions.Configuration.ConfigurationBinder.Get<T> silently ignores type conversion issues in child collections / arrays

### ISSUE THREAD

**Issue by stevewgh** [dotnet/runtime#35007] opened 2020-04-15 15:59 UTC
_(Tested with Microsoft.Extensions.Configuration.Binder@3.1.3 and Microsoft.Extensions.Configuration.Json@3.1.3)_

Given this application.settings file:

```json
{
  "Items": [
    {
      "IsEnabled": true
    },
    {
      "IsEnabled": "123"
    },
    {
      "IsEnabled": false
    }
  ]
}
```

with this C# code to consume the settings file:

``` c#   
class ApplicationConfiguration
{
    public List<ApplicationConfigurationItem> Items { get; set; }
}

class ApplicationConfigurationItem
{
    public bool IsEnabled { get; set; }
}

class Program
{
    static void Main(string[] args)
    {
        var configuration = new ConfigurationBuilder()
            .AddJsonFile("appsettings.json")
            .Build();

        var root = configuration.Get<ApplicationConfiguration>();
        Debug.Assert(root.Items.Count == 3);
    }
}
```

The Debug assertion will be hit because there are only two items in the collection. The configuration binding has an [empty catch block](https://github.com/dotnet/runtime/blob/2eef5a3dc0f9afeb07a1aada1c5312fc013b7871/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs#L447-L449) which prevents the caller from knowing if there was an issue binding the configuration to the POCO's.

This is a different behavior when the binding of child objects is done manually.  An InvalidOperationException is thrown when converting the "123" to a boolean - which is expected:

 ``` c#
class Program
{
    static void Main(string[] args)
    {
        var configuration = new ConfigurationBuilder()
            .AddJsonFile("appsettings.json")
            .Build();

        var applicationConfiguration = new ApplicationConfiguration
        {
            Items = configuration
                .GetSection("Items")
                .GetChildren()
                .Select(section => section.Get<ApplicationConfigurationItem>())
                .ToList()
        };
    }
}
```

Catching and swallowing the exception prevents the caller from knowing about any potential issues with the configuration. Could this behavior be changed please, or at least allow an overload of the binding methods that allow the behavior to be switched on?

Thanks

**Comment by davidfowl** [comment] 2020-04-15 16:37
> Catching and swallowing the exception prevents the caller from knowing about any potential issues with the configuration. Could this behavior be changed please, or at least allow an overload of the binding methods that allow the behavior to be switched on?

An overload sounds reasonable.

**Comment by maryamariyan** [comment] 2021-03-03 00:14
Closing as dupe of https://github.com/dotnet/runtime/issues/36015, fixing that would address this issue as well

**Closed by maryamariyan** 2021-03-03 00:14 UTC
Labels: area-Extensions-Configuration, untriaged
