### ISSUE TITLE
System.Reflection.Metadata Dependency question 

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/runtime#95626] opened 2023-12-05 09:03 UTC
Happened to find that `System.Reflection.Metadata` has `System.Collections.Immutable` for each target

![image](https://github.com/dotnet/runtime/assets/7604648/9365e77a-1bfc-40ac-84ff-a86a4cafaedc)

while it seemed the `System.Collections.Immutable` is part of `Microsoft.NETCore.App`, so I' wondering is it required to add the dependency for all targets even for `net6.0`/`net7.0`/`net8.0`

**Comment by huoyaoyuan** [comment] 2023-12-05 09:38
`System.Reflection.Metadata` is also a part of `Microsoft.NETCore.App`. When installing 8.0 package on 6.0 framework, it's expected to bring 8.0 dependency.

I'm not sure about the case when installing or 8.0 framework.

**Comment by ViktorHofer** [comment] 2023-12-07 08:23
> I'm not sure about the case when installing on 8.0 framework.

Same as for net6.0 and net7.0, the net8.0 assembly could be newer than what's provided by the 8.0 shared framework. All these dependencies are intentional. I'm closing this now as it is by design. Feel free to open a new issue if you still have questions.

**Closed by ViktorHofer** 2023-12-07 08:23 UTC
Labels: question, area-System.Reflection.Metadata
