### ISSUE TITLE
CI failure in runtime (mono llvmfullaot Pri0 Runtime Tests Run Linux arm64/x64 release)  legs

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#68971] opened 2022-05-06 16:41 UTC
## Build Information
Build: https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=1755437
Build error leg: LLVM AOT cross-compile CoreCLR tests
Pull request: https://github.com/dotnet/runtime/pull/68847

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section).

```json
{
  "ErrorMessage": "" 
}
```

## Build Information
Build: https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=1755437
Build error leg: LLVM AOT compile CoreCLR tests
Pull request: https://github.com/dotnet/runtime/pull/68847

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section).

```json
{
  "ErrorMessage": "" 
}
```

#### Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|0|0|0|

**Comment by lewing** [comment] 2022-05-06 18:48
duplicate of https://github.com/dotnet/runtime/issues/68932

**Closed by lewing** 2022-05-06 18:48 UTC
Labels: untriaged, runtime-mono, area-Codegen-LLVM-mono, Known Build Error
