### ISSUE TITLE
Linker fails on function pointers in System.Private.CoreLib

### ISSUE THREAD

**Issue by jeromelaban** [dotnet/runtime#43824] opened 2020-10-26 15:10 UTC
## Description

When linking the latest master's `System.Private.CoreLib.dll`, the following error happens:

```
Mono.Linker.MarkException: Error processing method: 'System.Boolean Interop/Globalization::EnumCalendarInfo(method System.Void *(System.Char*,System.IntPtr),System.String,System.Globalization.CalendarId,System.Globalization.CalendarDataType,System.IntPtr)' in assembly: 'System.Private.CoreLib.dll' ---> System.NullReferenceException: Object reference not set to an instance of an object
at Mono.Linker.Steps.MarkStep.ProcessInteropMethod (Mono.Cecil.MethodDefinition method) [0x0007e] in <c337541799f547028f11675864404f19>:0
at Mono.Linker.Steps.MarkStep.ProcessMethod (Mono.Cecil.MethodDefinition method) [0x0019a] in <c337541799f547028f11675864404f19>:0
at Mono.Linker.Steps.MarkStep.ProcessQueue () [0x0001b] in <c337541799f547028f11675864404f19>:0
```

### Other information

Using 0e402bcd28f.

**Comment by jkotas** [comment] 2020-10-26 15:17
Duplicate of #41866. Fixed in latest linker.

**Closed by jkotas** 2020-10-26 15:17 UTC
Labels: untriaged

**Comment by jeromelaban** [comment] 2020-10-26 15:23
Thanks Jan!
