### ISSUE TITLE
test failure in DynamicDependencyMethod

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#88922] opened 2023-07-14 16:56 UTC
build_linux_x64_checked_CLR_Tools_Tests-xunit_3
https://dev.azure.com/dnceng-public/public/_build/results?buildId=339807&view=ms.vss-test-web.build-test-results-tab&runId=7084448&paneView=debug
```
System.AggregateException : One or more errors occurred. (Roslyn compilation errors: (196,36): error CS1061: 'Type' does not contain a definition for 'RequiresPublicMethods' and no accessible extension method 'RequiresPublicMethods' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)
(197,29): error CS1061: 'Type' does not contain a definition for 'RequiresPublicMethods' and no accessible extension method 'RequiresPublicMethods' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)
(25,8): warning CS0169: The field 'DynamicDependencyMethod.B.field' is never used
(134,19): warning CS0649: Field 'C.field' is never assigned to, and will always have its default value null
)
---- System.Exception : Roslyn compilation errors: (196,36): error CS1061: 'Type' does not contain a definition for 'RequiresPublicMethods' and no accessible extension method 'RequiresPublicMethods' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)
(197,29): error CS1061: 'Type' does not contain a definition for 'RequiresPublicMethods' and no accessible extension method 'RequiresPublicMethods' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)
(25,8): warning CS0169: The field 'DynamicDependencyMethod.B.field' is never used
(134,19): warning CS0649: Field 'C.field' is never assigned to, and will always have its default value null
```

```
Stack trace
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Mono.Linker.Tests.TestCasesRunner.TestRunner.GetResultOfTaskThatMakesXUnitAssertions[T](Task`1 task) in /_/src/coreclr/tools/aot/Mono.Linker.Tests/TestCasesRunner/TestRunner.cs:line 152
   at Mono.Linker.Tests.TestCasesRunner.TestRunner.Compile(TestCaseSandbox sandbox, TestCaseCompilationMetadataProvider metadataProvider) in /_/src/coreclr/tools/aot/Mono.Linker.Tests/TestCasesRunner/TestRunner.cs:line 83
   at Mono.Linker.Tests.TestCasesRunner.TestRunner.Run(TestCase testCase) in /_/src/coreclr/tools/aot/Mono.Linker.Tests/TestCasesRunner/TestRunner.cs:line 33
   at Mono.Linker.Tests.TestCases.All.Run(String testName) in /_/src/coreclr/tools/aot/Mono.Linker.Tests/TestCases/TestSuites.cs:line 101
   at Mono.Linker.Tests.TestCases.All.DynamicDependencies(String t) in /_/src/coreclr/tools/aot/Mono.Linker.Tests/TestCases/TestSuites.cs:line 23
   at InvokeStub_All.DynamicDependencies(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
----- Inner Stack Trace -----
   at Mono.Linker.Tests.TestCasesRunner.TestCaseCompiler.CompileCSharpAssemblyWithRoslyn(CompilerOptions options) in /_/src/coreclr/tools/aot/Mono.Linker.Tests/TestCasesRunner/TestCaseCompiler.cs:line 328
   at Mono.Linker.Tests.TestCasesRunner.TestCaseCompiler.CompileCSharpAssemblyWithDefaultCompiler(CompilerOptions options) in /_/src/coreclr/tools/aot/Mono.Linker.Tests/TestCasesRunner/TestCaseCompiler.cs:line 228
   at Mono.Linker.Tests.TestCasesRunner.TestCaseCompiler.CompileCSharpAssembly(CompilerOptions options) in /_/src/coreclr/tools/aot/Mono.Linker.Tests/TestCasesRunner/TestCaseCompiler.cs:line 405
   at Mono.Linker.Tests.TestCasesRunner.TestCaseCompiler.CompileAssembly(CompilerOptions options) in /_/src/coreclr/tools/aot/Mono.Linker.Tests/TestCasesRunner/TestCaseCompiler.cs:line 217
   at Mono.Linker.Tests.TestCasesRunner.TestCaseCompiler.CompileTestIn(NPath outputDirectory, String outputName, IEnumerable`1 sourceFiles, String[] commonReferences, String[] mainAssemblyReferences, IEnumerable`1 defines, NPath[] resources, String[] additionalArguments) in /_/src/coreclr/tools/aot/Mono.Linker.Tests/TestCasesRunner/TestCaseCompiler.cs:line 60
   at Mono.Linker.Tests.TestCasesRunner.TestRunner.<>c__DisplayClass5_0.<Compile>b__1() in /_/src/coreclr/tools/aot/Mono.Linker.Tests/TestCasesRunner/TestRunner.cs:line 77
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

**Comment by danmoseley** [comment] 2023-07-14 16:56
https://github.com/dotnet/runtime/pull/88913

**Comment by lewing** [comment] 2023-07-14 19:00
duplicate of https://github.com/dotnet/runtime/issues/88870

**Comment by lewing** [comment] 2023-07-14 19:06
cc @vitek-karas

**Closed** 2023-07-14 19:47 UTC
Labels: area-CodeGen-coreclr, untriaged
