### ISSUE TITLE
Test failure JIT/HardwareIntrinsics/X86/Sse41/DotProduct_ro/DotProduct_ro.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#53215] opened 2021-05-25 06:56 UTC
Run: [runtime-coreclr crossgen2 20210523.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1152546&view=ms.vss-test-web.build-test-results-tab&runId=34841562&resultId=102093&paneView=debug)

Failed test:
```
R2R-CG2 OSX arm64 Checked @ OSX.1100.ARM64.Open

- JIT/HardwareIntrinsics/X86/Sse41/DotProduct_ro/DotProduct_ro.sh

```
**Error message:**
```
/private/tmp/helix/working/A33108F2/w/98ED0890/e/JIT/HardwareIntrinsics/X86/Sse41/DotProduct_ro/DotProduct_ro.sh: line 254: -r:/private/tmp/helix/working/A33108F2/w/98ED0890/e/JIT/HardwareIntrinsics/X86/Sse41/DotProduct_ro/IL-CG2/.dll: No such file or directory
rm: /private/tmp/helix/working/A33108F2/w/98ED0890/e/JIT/HardwareIntrinsics/X86/Sse41/DotProduct_ro/DotProduct_ro.dll.rsp: No such file or directory
rm: /private/tmp/helix/working/A33108F2/w/98ED0890/e/JIT/HardwareIntrinsics/X86/Sse41/DotProduct_ro/TestLibrary.dll.rsp: No such file or directory
Unhandled exception. System.AggregateException: One or more errors occurred. (Code generation failed for method '[TestLibrary]TestLibrary.Utilities.GetWindowsBuildNumber()') (Code generation failed for method '[TestLibrary]TestLibrary.Assert.AreAllEqual<__Canon>(__Canon[],__Canon[],string)') (Code generation failed for method '[TestLibrary]TestLibrary.Assert.AreAllEqualUnordered<__Canon>(__Canon[],__Canon[])')
---> ILCompiler.CodeGenerationFailedException: Code generation failed for method '[TestLibrary]TestLibrary.Utilities.GetWindowsBuildNumber()'
---> System.NullReferenceException: Object reference not set to an instance of an object.
at System.SZArrayHelper.GetEnumeratorT
at ILCompiler.ReadyToRunCompilationModuleGroupBase.ComputeInstantiationVersionsWithCode(Instantiation inst, TypeSystemEntity entityWithInstantiation)
at ILCompiler.ReadyToRunCompilationModuleGroupBase.VersionsWithMethodUncached(MethodDesc method)
at System.Collections.Concurrent.ConcurrentDictionary2.GetOrAdd(TKey key, Func2 valueFactory)
at ILCompiler.ReadyToRunCompilationModuleGroupBase.VersionsWithMethodBody(MethodDesc method)
at ILCompiler.DependencyAnalysis.ReadyToRun.DevirtualizationManager.IsEffectivelySealed(MethodDesc method)
at ILCompiler.Compilation.IsEffectivelySealed(MethodDesc method)
at Internal.JitInterface.CorInfoImpl.getMethodAttribsInternal(MethodDesc method)
at Internal.JitInterface.CorInfoImpl.ceeInfoGetCallInfo(CORINFO_RESOLVED_TOKEN& pResolvedToken, CORINFO_RESOLVED_TOKEN pConstrainedResolvedToken, CORINFO_METHOD_STRUCT_* callerHandle, CORINFO_CALLINFO_FLAGS flags, CORINFO_CALL_INFO* pResult, MethodDesc& methodToCall, MethodDesc& targetMethod, TypeDesc& constrainedType, MethodDesc& originalMethod, TypeDesc& exactType, MethodDesc& callerMethod, EcmaModule& callerModule, Boolean& useInstantiatingStub)
at Internal.JitInterface.CorInfoImpl.getCallInfo(CORINFO_RESOLVED_TOKEN& pResolvedToken, CORINFO_RESOLVED_TOKEN* pConstrainedResolvedToken, CORINFO_METHOD_STRUCT_* callerHandle, CORINFO_CALLINFO_FLAGS flags, CORINFO_CALL_INFO* pResult)
at Internal.JitInterface.CorInfoImpl.getCallInfo(IntPtr thisHandle, IntPtr* ppException, CORINFO_RESOLVED_TOKEN* pResolvedToken, CORINFO_RESOLVED_TOKEN* pConstrainedResolvedToken, CORINFO_METHOD_STRUCT* callerHandle, CORINFO_CALLINFO_FLAGS flags, CORINFO_CALL_INFO* pResult)
--- End of inner exception stack trace ---
at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(IMethodNode methodCodeNodeNeedingCode, MethodIL methodIL)
at Internal.JitInterface.CorInfoImpl.CompileMethod(MethodWithGCInfo methodCodeNodeNeedingCode, Logger logger)
at ILCompiler.ReadyToRunCodegenCompilation.<ComputeDependencyNodeDependencies>b__36_0(DependencyNodeCore1 dependency) at System.Threading.Tasks.Parallel.<>c__DisplayClass33_02.<ForEachWorker>b__0(Int32 i)
at System.Threading.Tasks.Parallel.<>c__DisplayClass19_01.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion) --- End of stack trace from previous location --- at System.Threading.Tasks.Parallel.<>c__DisplayClass19_01.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
at System.Threading.Tasks.TaskReplicator.Replica.Execute()

Stack trace
   at JIT_HardwareIntrinsics._X86_Sse41_DotProduct_ro_DotProduct_ro_._X86_Sse41_DotProduct_ro_DotProduct_ro_sh()
```

**Comment by mangod9** [comment] 2021-07-20 02:11
dupe of #51250

**Closed by mangod9** 2021-07-20 02:11 UTC
Labels: arch-arm64, area-crossgen2-coreclr, os-mac-os-x, untriaged
