### ISSUE TITLE
.net core 2.2 Internal error in the .NET Runtime at IP 00007FFEA84EB6B5 with exit code 80131506

### ISSUE THREAD

**Issue by paxhujing** [dotnet/runtime#59458] opened 2021-09-22 04:16 UTC
![image](https://user-images.githubusercontent.com/13563757/134282609-c2d20a49-f2f5-47ad-bedc-90e9e88ffa01.png)

![image](https://user-images.githubusercontent.com/13563757/134282584-7ec68974-bc7d-4b00-98df-655b95851806.png)

**Comment by GrabYourPitchforks** [comment] 2021-09-22 04:35
[.NET Core 2.2 is out of support.](https://github.com/dotnet/announcements/issues/147/) Does the problem repro with a supported version, like .NET Core 3.1 or .NET 5? If so, please update the issue with details of the error you're encountering on those runtimes. Thanks!

**Comment by paxhujing** [comment] 2021-09-22 04:49
> [.NET Core 2.2 is out of support.](https://github.com/dotnet/announcements/issues/147/) Does the problem repro with a supported version, like .NET Core 3.1 or .NET 5? If so, please update the issue with details of the error you're encountering on those runtimes. Thanks!

This is my first time encounter it. It doesn't host on  .NET Core 3.1 or .NET 5.Before crash,the program is capturing user-defined exception frequently.

**Comment by mangod9** [comment] 2021-09-22 15:01
Hi @paxhujing, to confirm you are unable to reproduce the failure on 3.1 or 5?

**Comment by paxhujing** [comment] 2021-09-23 03:23
> Hi @paxhujing, to confirm you are unable to reproduce the failure on 3.1 or 5?
I have updated to 3.1.If encounter it again,i will update this issuse.Thanks!

**Comment by mangod9** [comment] 2021-09-23 05:34
Ok thanks, closing for now, Please reopen if you see it again.

**Closed by mangod9** 2021-09-23 05:34 UTC
Labels: needs more info, area-VM-coreclr
