### ISSUE TITLE
JIT: Discarded cast on RHS of assignment leads to missing sign extension

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#60597] opened 2021-10-18 23:28 UTC
### Description

The program below outputs different results in debug and release:

### Reproduction Steps

```csharp
// Generated by Fuzzlyn v1.5 on 2021-10-18 19:57:54
// Run on .NET 6.0.0-rc.1.21430.1 on X64 Windows
// Seed: 4016123192189520851
// Reduced from 337.3 KiB to 0.6 KiB in 00:06:41
// Debug: Outputs 65535
// Release: Outputs 255
public class C0
{
    public ushort F2;
}

public struct S0
{
    public sbyte F0;
    public S0(sbyte f0): this()
    {
        F0 = f0;
    }
}

public class Program
{
    public static long s_8;
    public static S0[, ] s_13;
    public static void Main()
    {
        for (int vr8 = 0; vr8 < 2; vr8++)
        {
            System.Console.WriteLine(s_8);
            s_13 = new S0[, ]{{new S0(-1)}};
            C0 vr10 = new C0();
            vr10.F2 = (ushort)((sbyte)s_8 ^ (long)s_13[0, 0].F0);
            ushort vr41 = vr10.F2;
            s_8 = vr41;
        }
    }
}
```

### Expected behavior

Same result

### Actual behavior

Not same result

### Regression?

This works fine in .NET 6 rc2.

### Other information

We do the following transformation during morph:
```scala
STMT00010 (IL 0x02D...  ???)
               [000070] -A-XG-------              ▌  ASG       ushort
               [000069] ---XG+-N----              ├──▌  IND       ushort
               [000114] -----+------              │  └──▌  ADD       byref 
               [000057] -----+------              │     ├──▌  LCL_VAR   ref    V05 tmp4         
               [000113] -----+------              │     └──▌  CNS_INT   long   8 field offset Fseq[F2]
               [000068] ---XG-------              └──▌  CAST      int <- ushort <- long
               [000067] ---XG-------                 └──▌  XOR       long  
               [000060] ----G+------                    ├──▌  CAST      long <- int
               [000058] ----G+------                    │  └──▌  CLS_VAR   byte   Hnd=0x2185cf18 Fseq[s_8]
               [000066] ---XG-------                    └──▌  CAST      long <- int
               [000065] *--XG-------                       └──▌  IND       byte  
               [000064] ---XG-------                          └──▌  ARR_ELEM[,] byref  Zero Fseq[F0]
               [000061] n---G+------                             ├──▌  IND       ref   
               [000115] H----+------                             │  └──▌  CNS_INT(h) long   0x20498002e88 static Fseq[s_13]
               [000062] -----+------                             ├──▌  CNS_INT   int    0
               [000063] -----+------                             └──▌  CNS_INT   int    0
```
->
```scala
fgMorphTree BB02, STMT00010 (after)
               [000070] -A-XG+------              ▌  ASG       ushort
               [000069] ---XG+-N----              ├──▌  IND       ushort
               [000114] -----+------              │  └──▌  ADD       byref 
               [000057] -----+------              │     ├──▌  LCL_VAR   ref    V05 tmp4         
               [000113] -----+------              │     └──▌  CNS_INT   long   8 field offset Fseq[F2]
               [000067] ---XG-------              └──▌  XOR       byte  
               [000058] ----G+------                 ├──▌  CLS_VAR   byte   Hnd=0x2185cf18 Fseq[s_8]
               [000065] *--XG+------                 └──▌  IND       byte  
               [000064] ---XG+------                    └──▌  ARR_ELEM[,] byref  Zero Fseq[F0]
               [000061] n---G+------                       ├──▌  IND       ref   
               [000115] H----+------                       │  └──▌  CNS_INT(h) long   0x20498002e88 static Fseq[s_13]
               [000062] -----+------                       ├──▌  CNS_INT   int    0
               [000063] -----+------                       └──▌  CNS_INT   int    0
```
Not sure whether codegen or morph is in the wrong here.

cc @dotnet/jit-contrib @SingleAccretion 

P.S. This was found in a CI run of Fuzzlyn: https://dev.azure.com/dnceng/public/_build/results?buildId=1427670&view=ms.vss-build-web.run-extensions-tab

**Comment by jakobbotsch** [comment] 2021-10-19 10:20
Thanks for diagnosing @SingleAccretion! It's unfortunate that we don't have an IR type checker to catch things like this (cc @BruceForstall).

@benjamin-hodgson Do you want to submit the fix and matching regression test?

**Comment by benjamin-hodgson** [comment] 2021-10-31 21:29
Didn’t have time for this last weekend but looking at it today!

@SingleAccretion’s proposed fix makes sense to me, but I’m actually having a hard time reproducing this bug with the current `main` branch. The example above outputs 65536 for me both with and without optimisation, on my machine and on `sharplab.io` (which currently has a build taken from yesterday’s `main` branch).

Do you have any advice for reproducing the bug? Is it possible that it’s been accidentally fixed by some other change in the meantime?

I’d be happy to submit a PR with a fix and a test, I’m just not 100% certain the fix or the test would be correct since I haven’t managed to make the test fail yet.

**Comment by SingleAccretion** [comment] 2021-10-31 21:39
> which currently has a build taken from yesterday’s `main` branch

Note that SP does not track the runtime's `main`, but Roslyn's (i. e. SP codegen is .NET 5 codegen).

> The example above outputs 65535 for me both with and without optimisation

Without optimization, i. e. with `DOTNET_TieredCompilation=0`? What does the dump look like?

**Comment by benjamin-hodgson** [comment] 2021-10-31 21:41
> Note that SP does not track the runtime's main, but Roslyn's (i. e. SP codegen is .NET 5 codegen).

🤦🏻‍♂️ i knew that and wasn’t thinking

**Closed** 2021-11-01 22:24 UTC
Labels: area-CodeGen-coreclr, in pr
