### ISSUE TITLE
HostWriter: ResourceUpdate fails non-deterministically

### ISSUE THREAD

**Issue by DamianEdwards** [dotnet/runtime#3832] opened 2019-06-27 19:48 UTC
## Steps to reproduce
1. Create a new web app: `dotnet new webapp`
1. Repeatedly build the app from the CLI with no changes: `dotnet build`

## Expected  behavior
No errors

## Actual behavior
Randomly see the following error (twice in the last 20 builds just now):
```
C:\src\local\BuildPerf\WebApp3.0> dotnet build                                                                                     Microsoft (R) Build Engine version 16.3.0-preview-19325-02+eca7818b1 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 19.81 ms for C:\src\local\BuildPerf\WebApp3.0\WebApp3.0.csproj.
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
C:\Program Files\dotnet\sdk\3.0.100-preview7-012649\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(358,5): error MSB4018: The "CreateAppHost" task failed unexpectedly. [C:\src\local\BuildPerf\WebApp3.0\WebApp3.0.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview7-012649\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(358,5): error MSB4018: Microsoft.NET.Build.Tasks.ResourceUpdater+HResultException: 8007006E [C:\src\local\BuildPerf\WebApp3.0\WebApp3.0.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview7-012649\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(358,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResourceUpdater.ThrowExceptionForLastWin32Error() in /_/src/Tasks/Microsoft.NET.Build.Tasks/ResourceUpdater.cs:line 436 [C:\src\local\BuildPerf\WebApp3.0\WebApp3.0.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview7-012649\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(358,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResourceUpdater.Update() in /_/src/Tasks/Microsoft.NET.Build.Tasks/ResourceUpdater.cs:line 324 [C:\src\local\BuildPerf\WebApp3.0\WebApp3.0.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview7-012649\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(358,5): error MSB4018:    at Microsoft.NET.Build.Tasks.AppHost.Create(String appHostSourceFilePath, String appHostDestinationFilePath, String appBinaryFilePath, Boolean windowsGraphicalUserInterface, String intermediateAssembly, Logger log) in /_/src/Tasks/Microsoft.NET.Build.Tasks/AppHost.cs:line 82 [C:\src\local\BuildPerf\WebApp3.0\WebApp3.0.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview7-012649\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(358,5): error MSB4018:    at Microsoft.NET.Build.Tasks.CreateAppHost.ExecuteCore() in /_/src/Tasks/Microsoft.NET.Build.Tasks/CreateAppHost.cs:line 38 [C:\src\local\BuildPerf\WebApp3.0\WebApp3.0.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview7-012649\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(358,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() in /_/src/Tasks/Common/TaskBase.cs:line 38 [C:\src\local\BuildPerf\WebApp3.0\WebApp3.0.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview7-012649\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(358,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\src\local\BuildPerf\WebApp3.0\WebApp3.0.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview7-012649\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(358,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\src\local\BuildPerf\WebApp3.0\WebApp3.0.csproj]

Build FAILED.

C:\Program Files\dotnet\sdk\3.0.100-preview7-012649\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(358,5): error MSB4018: The "CreateAppHost" task failed unexpectedly. [C:\src\local\BuildPerf\WebApp3.0\WebApp3.0.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview7-012649\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(358,5): error MSB4018: Microsoft.NET.Build.Tasks.ResourceUpdater+HResultException: 8007006E [C:\src\local\BuildPerf\WebApp3.0\WebApp3.0.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview7-012649\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(358,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResourceUpdater.ThrowExceptionForLastWin32Error() in /_/src/Tasks/Microsoft.NET.Build.Tasks/ResourceUpdater.cs:line 436 [C:\src\local\BuildPerf\WebApp3.0\WebApp3.0.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview7-012649\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(358,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResourceUpdater.Update() in /_/src/Tasks/Microsoft.NET.Build.Tasks/ResourceUpdater.cs:line 324 [C:\src\local\BuildPerf\WebApp3.0\WebApp3.0.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview7-012649\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(358,5): error MSB4018:    at Microsoft.NET.Build.Tasks.AppHost.Create(String appHostSourceFilePath, String appHostDestinationFilePath, String appBinaryFilePath, Boolean windowsGraphicalUserInterface, String intermediateAssembly, Logger log) in /_/src/Tasks/Microsoft.NET.Build.Tasks/AppHost.cs:line 82 [C:\src\local\BuildPerf\WebApp3.0\WebApp3.0.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview7-012649\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(358,5): error MSB4018:    at Microsoft.NET.Build.Tasks.CreateAppHost.ExecuteCore() in /_/src/Tasks/Microsoft.NET.Build.Tasks/CreateAppHost.cs:line 38 [C:\src\local\BuildPerf\WebApp3.0\WebApp3.0.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview7-012649\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(358,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() in /_/src/Tasks/Common/TaskBase.cs:line 38 [C:\src\local\BuildPerf\WebApp3.0\WebApp3.0.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview7-012649\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(358,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\src\local\BuildPerf\WebApp3.0\WebApp3.0.csproj]
C:\Program Files\dotnet\sdk\3.0.100-preview7-012649\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(358,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\src\local\BuildPerf\WebApp3.0\WebApp3.0.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.58
```

## Environment data
`dotnet --info` output:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview7-012649
 Commit:    3f4ab7f5c5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview7-012649\

Host (useful for support):
  Version: 3.0.0-preview7-27826-04
  Commit:  5c4d829254

.NET Core SDKs installed:
  2.1.700-preview-009618 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009677 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  2.2.204 [C:\Program Files\dotnet\sdk]
  3.0.100-preview7-012649 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview7.19326.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview7-27826-04 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview7-27826-04 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by gimlichael** [comment] 2020-02-11 15:14
I hope this will be prioritized *before* .NET 5.0 as the current milestone indicates.
It might not be breaking, but it is quite annoying to to a clean and built.

**Comment by Ncatalogna** [comment] 2020-02-11 15:34
We are experiencing the same problem with .Net 3.0, 3.1 migrated and new solutions. 

The worst part is that I can replicate it:

* Create an ASP .Net Core project 
* Compile Solution
* Clean Solution
* Execute Solution
----------------------------
Result: MSB4018 Unexpected error in the "CreateAppHost" task.
Microsoft.NET.HostModel.HResultException: 8007006E

--------------------

NET Core SDK (mirroring any global .json):
* Version: 3.1.100
* Commit: cd82f021f4

Runtime environment:
* OS Name: Windows
* OS Version: 10.0.17134
* OS Platform: Windows
* RID: win10-x64
* Base Path: C: Program Files Dotnet 3.1.100

----
Last comment: 

* This problem only occurs in projects created in a business environment.  (Work)
* This problem cannot be replicated in a Domestic environment. (Home)

**Comment by aredfox** [comment] 2020-02-12 21:54
I can also attest that this fails on github actions for some reason I get this error... All the rest worked fine (check previous builds); it seems to occur randomly. Didn't happen to me on the ubuntu -image, but since I added winforms I needed the windows platform, then probs started...

Check
https://github.com/KodeFoxx/Clean-Architecture-Template-for-.Net-Core-3.1-with-EfCore-3.1/runs/442195045?check_suite_focus=true#step:8:54

**Comment by robkuz** [comment] 2020-02-14 16:45
Got this error now like a dozen times in a row today
- only after I shut down Rider
- git clean -xdf
- build clean

and then rebuild it went away.

It happens only on my work machine which is a 16 core machine this happens.
It has never happened at home on a modestly fast notebook

**Comment by robkuz** [comment] 2020-02-14 21:25
This is now becoming absurd!
I am literally trying to do a deployment for more than 8 hours now and I get this error all the time

**Comment by swaroop-sridhar** [comment] 2020-02-14 22:49
We believe that the correct fix for this issue is to complete: 

* https://github.com/dotnet/runtime/issues/3828, and  
* https://github.com/dotnet/runtime/issues/3829, and 
* Consider not shipping AppHost with an extension/permissions indicating an executable.

While this work is slated for .net 5, I think it is a fairly large change for servicing .net core 3.1.
So, for servicing we can consider an alternate simpler fix:

* The current implementation retries the resource update if an update because the device or drive is locked (say by an antivurus) HRESULT 0x21 and 0x6C.
* However, looks like the failures reported have errors 0x5 (Access violation) and 0x6# (Open failed).
* I'd checked with Windows/Defender teams about the file locking, and they didn't expect failure with these error codes. However, different AVs work differently about examining files.
* So, I can flip the check over, and retry the resource update, unless the returned HRESULT is one of: 
   * ERROR_FILE_NOT_FOUND(0x2) 
   * ERROR_PATH_NOT_FOUND (0x3), 
   * ERROR_INVALID_DRIVE (0xf) 
   * ERROR_BAD_NETPATH (0x35)
   * ERROR_BAD_PATHNAME (0xA1)
   * ERROR_BAD_EXE_FORMAT (0xC1)
   * ERROR_FILENAME_EXCED_RANGE (0xCE)  
   * ERROR_BAD_FILE_TYPE (0xDE)
   * ERROR_FILE_TOO_LARGE (0xDF)

@nguerrera  @wli3  What do you think ?

**Comment by wli3** [comment] 2020-02-14 23:23
@swaroop-sridhar are we clear on the root cause? it is actually the antivurus? It is better to know the exact error code. I would choose the "flip the check over" as the last resort since it would hide further bugs.

**Comment by nguerrera** [comment] 2020-02-14 23:26
I don't think fruitless retries are much of a bug hiding concern. We were careful to aggregate all the exceptions for the case where it still fails, right? So if we retry something that won't work we won't lose information about the original failure. If that holds, I think the flip is OK. I wonder if it's not simpler to just brute force retry always?

**Comment by swaroop-sridhar** [comment] 2020-02-15 00:38
@nguerrera  I was trying to avoid running 500 times if the app failed for an evidently different reason (ex: file doesn't exist). However, such cases are very rare as the SDK supplies the apphost, and the HostModel itself creates the file it is about to modify. So, it's probably OK to always retry.

@wli3 We know that the failure is not detereminisitc, not reproducible on our machines, and depends on specific computers/software running. The failure codes obtained so far seems to suggest another application blocking access to the apphost. However, the problem with enumerating known failure codes is that a different use-pattern may generate a different error code in future.

**Comment by nguerrera** [comment] 2020-02-15 01:20
I didn’t realize there was 500 retries possible.

**Comment by swaroop-sridhar** [comment] 2020-02-15 01:29
Yes it is 500 retries with 100 ms wait between each.

**Comment by nguerrera** [comment] 2020-02-15 01:33
Ok then it makes sense to filter the known useless-to-retry cases

**Comment by nguerrera** [comment] 2020-02-15 01:43
I think I’m OK with this plan if its lifecycle is limited to past releases and we do the better thing in 5

**Comment by swaroop-sridhar** [comment] 2020-02-15 02:00
That's my thought @nguerrera. 
I don't like the fix -- but I'm not sure what else can be done that's small enough to take for servicing.
I did spend quite some time trying to repro the failure  -- to obtain a dump to see how the other HResults were obtained, but no luck with that.

**Comment by swaroop-sridhar** [comment] 2020-02-15 03:37
The other option is to retry after the known reported cases of 0x6E (Open failed) and 0x05 (Acces Denied).

**Comment by robkuz** [comment] 2020-02-27 09:14
Is there a date when this will be released.
It is becoming a real issue for me

**Comment by robkuz** [comment] 2020-02-27 21:18
looks like I found the prime suspect (at least in my case). It seems like Dropbox is interfering with the filesystem in a big way and therefore with `createAppHost`
I did run my deploy script which cleans, builds, runs tests, rebuilds, runs partial tests, cleans etc. multiple with either Dropbox sync enabled or disabled. (4 times without and 2 times with) and the results seem pretty clear: whenever I run it with dropbox sync enabled my rather extensive build fails always. if I run it without dropbox sync the build succeeds (4 out of 4).
As a side note - my dropbox account is really, really big (couple of 100K files).
Maybe someone can get into contact with someone from Dropbox?

**Comment by swaroop-sridhar** [comment] 2020-02-27 21:19
> Is there a date when this will be released.

@robkuz  I think this fix will make it into the April servicing release.

**Comment by Brend-Smits** [comment] 2020-03-20 11:10
I know this issue has been closed // a fix is planned. 
I just want to chip in and let others know that thanks to @robkuz I realized that in my case it was caused by Synology Drive. I recommend others having this issue to check if anything is syncing the directory to some external file service like Dropbox, Google Drive or a NAS. 

Thanks all, this resolved my issues 😄

**Comment by robinwilson16** [comment] 2020-04-03 23:37
I'm getting the same error or another saying the cloud operation failed when project is hosted in a OneDrive folder.
I've now set it to always keep the files on this device so will see if that helps. I have had projects on OneDrive with no issues before.

**Comment by AMassani** [comment] 2020-05-01 04:15
> I know this issue has been closed // a fix is planned.
> I just want to chip in and let others know that thanks to @robkuz I realized that in my case it was caused by Synology Drive. I recommend others having this issue to check if anything is syncing the directory to some external file service like Dropbox, Google Drive or a NAS.
> 
> Thanks all, this resolved my issues 😄

**Comment by ericstj** [comment] 2021-02-05 17:41
Folks are still reporting this.  We shouldn't be relying on retry as a solution here.  There is a correct way for build tools to make file changes: only ever write using the very first created handle.  Once a file is closed, only ever open for read.  If you need to write again, make a copy maintaining the open handle and write to that handle.  In this way you can never be broken by AV-interference.

**Comment by agocke** [comment] 2021-07-28 23:10
I believe this has been fixed by https://github.com/dotnet/runtime/pull/48774

**Closed by agocke** 2021-07-28 23:10 UTC
Labels: area-HostModel
