### ISSUE TITLE
`TypeLoadException`: Struct used as a generic argument for a value type

### ISSUE THREAD

**Issue by ds5678** [dotnet/runtime#77074] opened 2022-10-15 03:21 UTC
### Description

> I'm sure where the best place to make this issue is. I think it's a runtime problem, but it could also be Roslyn not checking for this scenario.

A `TypeLoadException` is thrown whenever I declare a struct and use it as a type argument for another struct inside the declaration.

### Reproduction Steps

```cs
namespace Test;

static class Program
{
	public static void Main()
	{
		Foo foo = new Foo(new());
	}
}

public readonly struct Foo
{
	public Foo(Bar<Foo> bar)
	{
		BarValue = bar;
	}

	public Bar<Foo> BarValue { get; }
}

public readonly struct Bar<T>
{
	public bool Value { get; }
	public Bar()
	{
		Value = true;
	}
}
```

### Expected behavior

Either the runtime should load `Foo` or Roslyn should error/warn during compilation.

### Actual behavior

```
System.TypeLoadException: 'Could not load type 'Test.Foo' from assembly 'Test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.'
```

### Regression?

I don't know.

### Known Workarounds

Changing `Foo` or `Bar` to be a reference type.

### Configuration

.NET 6 on Windows 10 x64

I don't know if it's limited to this configuration.

**Comment by huoyaoyuan** [comment] 2022-10-15 04:06
This should be a duplicate of #6924, #72039 and #72930.

**Closed by huoyaoyuan** 2022-10-15 04:06 UTC
Labels: area-TypeSystem-coreclr, untriaged
