### ISSUE TITLE
Assertion failed 'unreached' in 'MyClass:Foo(System.Numerics.Vector`1[Single]):this' during 'Do value numbering' (IL size 9) 

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#51500] opened 2021-04-19 16:48 UTC
Gets the assertion failure on windows/x64 when doing superpmi collection of `System.Dynamic.Runtime.Tests.dll`.

Repro steps:

```cmd
python src\coreclr\scripts\superpmi.py collect --pmi -assemblies System.Dynamic.Runtime.Tests.dll
```

**Comment by kunalspathak** [comment] 2021-04-19 16:49
@dotnet/jit-contrib , @briansull

**Comment by SingleAccretion** [comment] 2021-04-19 18:22
Reproduction:
```cs
[MethodImpl(MethodImplOptions.NoInlining)]
private static void Problem()
{
    VectorDefault(new Vector<float>());
}

[MethodImpl(MethodImplOptions.NoInlining)]
static void VectorDefault<T>(T d)
{
    d = default(T);
}
```
Taking a closer look...

**Comment by SingleAccretion** [comment] 2021-04-19 18:38
The issue is here:
https://github.com/dotnet/runtime/blob/2aba0c511ce6949513f2024c76a30585e7544628/src/coreclr/jit/valuenum.cpp#L7483-L7495

The relevant statement:
```scala
N004 (  9,  7) [000003] IA--G-------              *  ASG       simd16 (init)
N002 (  7,  5) [000005] *---G--N----              +--*  OBJ       simd16<System.Numerics.Vector`1[Single]>
N001 (  1,  1) [000000] -------N----              |  \--*  LCL_VAR   byref  V00 arg0         u:1 (last use)
N003 (  1,  1) [000002] ------------              \--*  CNS_INT   int    0
```
So, we have `OBJ` on the lhs, and `CNS_INT` on the rhs, and `VNPairForCast` is not equipped to handle that. The actual assert fires when we try to fold the cast from zero `int` to `simd16`.

As I am not an expert in this area, deferring the judgement on the proper fix to people who are.

**Comment by AndyAyersMS** [comment] 2021-04-19 18:58
This is a common IR idiom for zero-initialization of a struct (one might prefer to see a struct-typed zero, but we use an int).

Suspect you should you skip trees where `OperIsInitBlkOp` is true, and let code below handle it.

**Comment by SingleAccretion** [comment] 2021-04-19 19:25
That sounds reasonable. Looks like the code in that branch was never prepared to handle `GT_OBJ`s:
https://github.com/dotnet/runtime/blob/2aba0c511ce6949513f2024c76a30585e7544628/src/coreclr/jit/valuenum.cpp#L7682

@AndyAyersMS I will see what I can do here, and hopefully learn something along the way, so I suppose you can assign me to this one.

**Comment by AndyAyersMS** [comment] 2021-04-19 20:43
Do we know why we just started seeing this, or was it just always there and the SPMI run was the first time we noticed?

**Comment by kunalspathak** [comment] 2021-04-19 20:55
> Do we know why we just started seeing this, or was it just always there and the SPMI run was the first time we noticed?

Probably. We never ran SPMI on libraries tests. I noticed this while working on that pipeline. I am talking to @BruceForstall  on how to surface these failures.

**Comment by SingleAccretion** [comment] 2021-04-19 21:03
> Probably

[Agreed](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKGIAYACY8gOgDkBXfGKASzFwBuGvSasAShwB2GXtxYBhCPgAOvADY8AyjwBu/GEJGMtAC2xQVAGWzAWkmXJjDqIgMxNSDBQwDeNBkCGAG0AKV4MAHEYKR5+AAoMAE8VGAgAM3iANRgwDGgAHnT1CGwMAD4ASkqAXQCg4IBZGAxTCAATAElVdXjm1o7ulXUAeRVZCClcdghOqXVeKUWAc1r6wOYkJhQGHLzoABEYdOwOdQwCgBVy+MuGdsr1vyeg+4YAXnvj0/PbypdXgBfGiAoA=).

**Comment by briansull** [comment] 2021-07-16 00:04
Triage Area: ValueNumbering

**Comment by jakobbotsch** [comment] 2021-08-03 15:04
Looks like @echesakov ended up fixing the original repro with #53116, gonna see if I can find a different repro before I close this.

**Closed** 2021-08-04 10:26 UTC
Labels: area-CodeGen-coreclr
