### ISSUE TITLE
Unexpected behavior (InvalidOperationException) with [JsonRequired] property set through constructor

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#84702] opened 2023-04-12 16:22 UTC
### Description

I'm not exactly sure whether this is by design or a bug, but the behavior seems at the very least a bit unexpected.

Consider this:

```csharp
var model = JsonSerializer.Deserialize(
    """{"Name":"Bob"}""",
    MyContext.Default.MyModel);

public sealed class MyModel
{
    public MyModel(string name)
    {
        Name = name;
    }

    [JsonRequired]
    public string Name { get; }
}

[JsonSerializable(typeof(MyModel))]
public sealed partial class MyContext : JsonSerializerContext
{
}
```

Here, there's a readonly property that's marked as required via `[JsonRequired]`. Running this coee, you get:

> "System.InvalidOperationException: 'JsonPropertyInfo 'Name' defined in type 'MyModel' is marked required but does not specify a setter.'"

This is thrown by the generated `MyModel` property in the JSON context type. A couple things:
- If this is by design, the exception docs don't seem correct. Specifically, `JsonSerializer.Deserialize` (as well as all other various overloads) don't list `InvalidOperationException` as one of the possible exceptions they can throw.
- I assumed this would work given that the generator matches the properties from custom constructor by name. If this specific scenario isn't supported by design (which would be consistent with the fact that you can also not have a `required` readonly auto-prop, and must instead also declare a setter), shouldn't this at least have a diagnostic being produced by the generator? It seems that the fact this configuration is invalid can easily be detected by the JSON generator (or even better, by a diagnostic analyzer). Essentially, readonly auto-prop with `[JsonRequired]` should produce an error/warning.

cc. @eiriktsarpalis @layomia 

**EDIT:** actually I think the exception message is also slightly misleading. You get the same exception even if you do have a setter, but it's eg. private. So I guess it shouldn't really say that the property must have "a setter", but that it must have an "publicly accessible setter" or something? This is just a side note to the other points above in this issue.

**Comment by eiriktsarpalis** [comment] 2023-04-13 07:50
Duplicate of https://github.com/dotnet/runtime/issues/78098. @krwq has a fix for this ready in https://github.com/dotnet/runtime/pull/78152 but my feeling is that we need to examing the concept of "required constructor" parameters more holistically, addressing related issues such as the ones listed here: https://github.com/dotnet/runtime/pull/78152#issuecomment-1310503333

**Closed** 2023-04-19 11:35 UTC
Labels: area-System.Text.Json, untriaged
