### ISSUE TITLE
[Perf -22%] System.Collections.AddGivenSize<Int32>.SortedList

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#39112] opened 2020-07-10 21:47 UTC
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Changes | [diff](https://github.com/dotnet/installer/compare/a4a49f07fbf986d496ef57521e76b22caaf9bfb3...3c6656f83b01ece6af7e11eb75ec0145554b139d)

### Regressions in System.Collections.AddGivenSize<Int32>

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier
-- | -- | -- | -- | -- | --
SortedList | 36.19 μs | 43.51 μs | 1.20 |  | False

### Related Issue on x86 Windows
[[Perf -12%] System.Collections.AddGivenSize<Int32>.SortedList](https://github.com/DrewScoggins/performance-2/issues/929)

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_10_2020/release/3.1.1xx%20-%3E%20master_x64_ubuntu%2018.04/System.Collections.AddGivenSize(Int32)_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/07_10_2020/release/3.1.1xx%20-%3E%20master_x64_ubuntu%2018.04/System.Collections.AddGivenSize(Int32).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Collections.AddGivenSize<Int32>*';
```
<details>

#### System.Collections.AddGivenSize<Int32>.SortedList(Size: 512)

```log
[33468.100 ; 34241.363) | @
[34241.363 ; 35597.511) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[35597.511 ; 36860.074) | @@@@@@@@@@
[36860.074 ; 38381.947) | 
[38381.947 ; 40025.831) | @@@@@@@@@@@@@
[40025.831 ; 41613.940) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[41613.940 ; 42970.089) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[42970.089 ; 44360.270) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[44360.270 ; 46060.324) | @
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by danmosemsft** [comment] 2020-08-01 00:50
This test primarily stresses Array.Copy.
https://github.com/dotnet/runtime/blob/d40d32bfec9a7f7b4c0bd9a34566ee40219b7d39/src/libraries/System.Collections/src/System/Collections/Generic/SortedList.cs#L670-L671

The regression apparently occurred between Oct 29 and Nov 4th . On Nov 2nd, we rewrote Array.Copy in C# (https://github.com/dotnet/coreclr/pull/27634)

There was actually a followup PR to replace some overloads of Array.Copy with others that touched SortedList on Nov 4th (https://github.com/dotnet/corefx/pull/42343) but it does not affect the tested codepath.

cc @jkotas

**Comment by danmosemsft** [comment] 2020-08-01 00:55
Duped a bunch of tests that all stress Array.Copy and regressed at the same time. 

Per comments from @stephentoub in some of these, it may be bimodal, or configuration dependent.

**Comment by jkotas** [comment] 2020-08-01 04:44
Memory copying has very complex perf characteristics. Any change will make some cases faster in some situations and some other cases slower in other situations.

I do not think there is much we can do here.

**Comment by danmosemsft** [comment] 2020-08-02 18:01
OK, I am going to close this. Realistically if you are doing this in a hot code path, you would want to consider using a different datastructure . Instead of SortedList/SortedList<K,V>, which is array backed, SortedDictionary<K,V>, which  would give you faster insert/remove at the cost of some memory. ([details](https://stackoverflow.com/questions/935621/whats-the-difference-between-sortedlist-and-sorteddictionary)). Similarly for List<T>/Array you might use SortedSet<T> depending on what you want.

cc area owners @layomia @eiriktsarpalis

**Closed by danmosemsft** 2020-08-02 18:01 UTC
Labels: arch-x64, area-System.Collections, os-linux, tenet-performance, tenet-performance-benchmarks, untriaged
