### ISSUE TITLE
Disabled Job - Libraries Test Run release mono windows x64 Release

### ISSUE THREAD

**Issue by riarenas** [dotnet/runtime#45524] opened 2020-12-03 02:46 UTC
Almost all tests involving networking fail in that leg. The test runs have been disabled temporarily in https://github.com/dotnet/runtime/pull/45529

An example in https://dnceng.visualstudio.com/public/_build/results?buildId=906071&view=ms.vss-test-web.build-test-results-tab

>[6:10 PM] Alexander Köplinger  
hmm this might be related to the helix rollout since it overlaps with when the rollout happened. all of the workitems have something to do with networking or hitting some http, and some have exceptions when trying to instantiante MsQuicApi
it's possible that a new Windows version got rolled out that enables http3/quic somehow and that triggers this codepath

Exploratory PR in https://github.com/dotnet/runtime/pull/45520

**Comment by scalablecory** [comment] 2020-12-03 10:00
Looking at logs, failures appear to be related to reflection. Can you point me to where you are seeing `MsQuicApi` as possible suspect?

> some have exceptions when trying to instantiante MsQuicApi

A first-chance exception is expected here as a P/Invoke call is used to test for a DLL's presence. Are you seeing the exception leak out in other ways?

**Comment by akoeplinger** [comment] 2020-12-03 11:38
One example is in this log:

```
System.Xml.Tests.TC_SchemaSet_Add_URL.v4 [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object
      Stack Trace:
        /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(378,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

Unhandled Exception:
System.TypeInitializationException: The type initializer for 'System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi' threw an exception.

 ---> System.NullReferenceException: Object reference not set to an instance of an object

   at System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi..ctor() in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/Internal/MsQuicApi.cs:line 28

   at System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi..cctor() in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/Internal/MsQuicApi.cs:line 156

   --- End of inner exception stack trace ---
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi' threw an exception.

 ---> System.NullReferenceException: Object reference not set to an instance of an object

   at System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi..ctor() in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/Internal/MsQuicApi.cs:line 28

   at System.Net.Quic.Implementations.MsQuic.Internal.MsQuicApi..cctor() in /_/src/libraries/System.Net.Quic/src/System/Net/Quic/Implementations/MsQuic/Internal/MsQuicApi.cs:line 156

   --- End of inner exception stack trace ---
```

It sounds like something goes wrong when loading the MsQuic library but I don't see any related changes between the good/bad commits so my current hunch is that something in the OS changed.

**Comment by akoeplinger** [comment] 2020-12-03 12:37
Hmm after more digging this doesn't look related to MsQuic anymore, I tried disabling loading it with https://github.com/dotnet/runtime/pull/45520 but there are still other workitems that hit the reflection issue.

We seem to be hitting it on the release/5.0 branch as well so it definitely looks related to the recent Helix rollout.

**Comment by riarenas** [comment] 2020-12-03 15:38
@dotnet/dnceng for visibility. This looks like it started failing on all windows queues as of the latest rollout.

**Comment by premun** [comment] 2020-12-03 15:46
I opened https://github.com/dotnet/core-eng/issues/11569 for tracking

**Comment by eerhardt** [comment] 2020-12-03 16:43
I hit the same NullReferenceException in https://dev.azure.com/dnceng/public/_build/results?buildId=906896&view=logs&j=d81dbc02-ec0b-5bd5-14c1-0072bd710d3b&t=780f1b30-8338-5e4d-6b72-c57eeb2413c9&l=76


```
Executed on a000GUM

C:\h\w\A14F08F6\w\AB370972\e>call RunTests.cmd --runtime-path C:\h\w\A14F08F6\p 
----- start Thu 12/03/2020  4:22:57.90 ===============  To repro directly: ===================================================== 
pushd C:\h\w\A14F08F6\w\AB370972\e\
"C:\h\w\A14F08F6\p\dotnet.exe" exec --runtimeconfig System.Data.Common.Tests.runtimeconfig.json --depsfile System.Data.Common.Tests.deps.json xunit.console.dll System.Data.Common.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================

C:\h\w\A14F08F6\w\AB370972\e>"C:\h\w\A14F08F6\p\dotnet.exe" exec --runtimeconfig System.Data.Common.Tests.runtimeconfig.json --depsfile System.Data.Common.Tests.deps.json xunit.console.dll System.Data.Common.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Data.Common.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Data.Common.Tests (found 1810 of 1813 test cases)
  Starting:    System.Data.Common.Tests (parallel test collections = on, max threads = 2)
    System.Data.Tests.SqlTypes.SqlStringTest.ReadWriteXmlTest [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object
      Stack Trace:
        /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(378,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Data.Common.Tests.DbConnectionTests.CanBeFinalized [SKIP]
      Condition(s) not met: "IsPreciseGcSupported"
    System.Data.Common.Tests.DbCommandTests.CanBeFinalized [SKIP]
      Condition(s) not met: "IsPreciseGcSupported"
   System.Data.Common.Tests: [Long Running Test] 'System.Data.Tests.SqlTypes.SqlInt64Test.ReadWriteXmlTest', Elapsed: 00:02:11
   System.Data.Common.Tests: [Long Running Test] 'System.Data.Tests.SqlTypes.SqlInt64Test.ReadWriteXmlTest', Elapsed: 00:04:11
   System.Data.Common.Tests: [Long Running Test] 'System.Data.Tests.SqlTypes.SqlInt64Test.ReadWriteXmlTest', Elapsed: 00:06:11
   System.Data.Common.Tests: [Long Running Test] 'System.Data.Tests.SqlTypes.SqlInt64Test.ReadWriteXmlTest', Elapsed: 00:08:11
   System.Data.Common.Tests: [Long Running Test] 'System.Data.Tests.SqlTypes.SqlInt64Test.ReadWriteXmlTest', Elapsed: 00:10:11
   System.Data.Common.Tests: [Long Running Test] 'System.Data.Tests.SqlTypes.SqlInt64Test.ReadWriteXmlTest', Elapsed: 00:12:11
   System.Data.Common.Tests: [Long Running Test] 'System.Data.Tests.SqlTypes.SqlInt64Test.ReadWriteXmlTest', Elapsed: 00:14:11
```

**Comment by eerhardt** [comment] 2020-12-03 16:51
Also hit in another PR https://github.com/dotnet/runtime/pull/45522. 

Log: https://dev.azure.com/dnceng/public/_build/results?buildId=906830&view=logs&j=d81dbc02-ec0b-5bd5-14c1-0072bd710d3b&t=780f1b30-8338-5e4d-6b72-c57eeb2413c9&l=76

**Comment by MattGal** [comment] 2020-12-03 17:00
Investigating via https://github.com/dotnet/core-eng/issues/11569

**Comment by akoeplinger** [comment] 2020-12-03 17:02
@eerhardt those builds ran before the leg was disabled.

**Comment by akoeplinger** [comment] 2020-12-03 17:07
I think this might be related to the VS update since I can reproduce it locally, i.e. the cause is not the Helix test machine but
the build machine.

**Comment by akoeplinger** [comment] 2020-12-03 18:30
Ok, I confirmed that this is indeed due to the VS update.

Good:
```
  **********************************************************************
  ** Visual Studio 2019 Developer Command Prompt v16.7.3
  ** Copyright (c) 2020 Microsoft Corporation
  **********************************************************************
  [vcvarsall.bat] Environment initialized for: 'x86_x64'
  -- Building for: Visual Studio 16 2019
  -- The C compiler identification is MSVC 19.27.29111.0
  -- The CXX compiler identification is MSVC 19.27.29111.0

```

Bad:
```
  **********************************************************************
  ** Visual Studio 2019 Developer Command Prompt v16.8.0
  ** Copyright (c) 2020 Microsoft Corporation
  **********************************************************************
  [vcvarsall.bat] Environment initialized for: 'x86_x64'
  -- Building for: Visual Studio 16 2019
  -- The C compiler identification is MSVC 19.28.29333.0
  -- The CXX compiler identification is MSVC 19.28.29333.0

```

**Comment by akoeplinger** [comment] 2020-12-03 18:33
To reproduce:

```bash
.\build.cmd mono+libs+libs.pretest -c Release

.\dotnet.cmd build /p:RuntimeFlavor=mono /t:Test /p:Configuration=Release .\src\libraries\System.Private.Xml\tests\XmlSchema\XmlSchemaSet\System.Xml.XmlSchemaSet.Tests.csproj
```

**Comment by radical** [comment] 2020-12-03 23:18
BatchedCI build for https://github.com/dotnet/runtime/commit/2ee13ec8e5ad6af2d7d6e4d812f7c12b807dea42 is also failing with NRE in `RuntimeMethodInfo.Invoke`.

**Comment by lateralusX** [comment] 2021-01-05 10:44
Crash should be fixed by https://github.com/dotnet/runtime/pull/46573. PR also re-enables the Windows x64 Release CI lane.

**Comment by danmosemsft** [comment] 2021-01-10 18:56
Do we need to report to compiler team?

**Comment by lateralusX** [comment] 2021-01-11 07:42
@danmosemsft Yes that would be good, how do we best progress regarding that?

**Comment by akoeplinger** [comment] 2021-01-11 14:58
@lateralusX I'd start with https://docs.microsoft.com/en-us/cpp/overview/how-to-report-a-problem-with-the-visual-cpp-toolset which essentially means opening an issue on developer community via https://aka.ms/feedback/report?space=62.

If we don't get a response we can ping someone internally.

**Comment by akoeplinger** [comment] 2021-01-11 15:00
Closing the issue since the problem on our end was fixed with https://github.com/dotnet/runtime/pull/46573

**Closed by akoeplinger** 2021-01-11 15:00 UTC
Labels: area-Infrastructure-mono, blocking-clean-ci
