### ISSUE TITLE
Bug in System.Numerics.Vector.CopyTo

### ISSUE THREAD

**Issue by toor1245** [dotnet/runtime#46384] opened 2020-12-24 10:55 UTC
### Description

it is code display any behavior on OS's
  
```cs
        public static Vector<T> GetDistancePoint<T>(Vector<T> va, Vector<T> vb)
            where T : unmanaged
        {
            int len = va.Length;

            if (len != vb.Length)
            {
                throw new MatrixDotNetException("vectors are not equal");
            }

            Vector<T> vc = new Vector<T>(len);
            int i = 0;
            
            int size = System.Numerics.Vector<T>.Count;
            int lastIndexBlock = len - len % size;
            for (; i < lastIndexBlock; i += size)
            {
                var vectorA = new System.Numerics.Vector<T>(va.Array, i);
                var vectorB = new System.Numerics.Vector<T>(vb.Array, i);
                var vectorC = Vector.Subtract(vectorB, vectorA);
                vectorC.CopyTo(vc.Array);
            }

            for (; i < vc.Length; i++)
            {
                vc[i] = MathUnsafe<T>.Sub(vb[i], va[i]);
            }

            return vc;
        }
```

### Configuration
version of .NET code running on .NET Core 3.1, .NET 5
OS: Windows 10, Ubuntu 18.04, macOS Catalina 10.15
Architecture: x64
* Do you know whether it is specific to that configuration?
  Bug about difference on configurations 

### Regression?
it executes on .NET Core 3.1 and .NET 5 

### Other information
```cs
        [Fact]
        public void GetDistancePointVectorTest_AssertMustBeEqual()
        {
            // Arrange
            Vector<int> v1 = new[] { 4, 2, 1, 1, 2, 3, 4, 6, 9 };
            Vector<int> v2 = new[] { 4, 2, 4, 1, 3, 4, 5, 7, 11 };
            Vector<int> expected = new[] { 0, 0, 3, 0, 1, 1, 1, 1, 2 };
            
            // Act
            var actual = VectorExtension.GetDistancePoint(v1, v2);
            
            // Assert
            Assert.Equal(expected, actual);
        }
```
on Windows and Ubuntu we have success.

on MacOS we have error message:
```Error Message:
Assert.Equal() Failure
Expected: <0,0,3,0,1,1,1,1,2>

Actual:   <1,1,1,1,0,0,0,0,2>
```

It is related with CopyTo method when we not pass index 
```cs
vectorC.CopyTo(vc.Array);
```
if we pass index all will be work correct
```cs
vectorC.CopyTo(vc.Array, i);
```

**Comment by huoyaoyuan** [comment] 2020-12-24 15:57
`CopyTo(array)` calls `CopyTo(array, 0)`. It's obviously different with `CopyTo(array, i)`.
It looks like your own bug.

**Comment by toor1245** [comment] 2020-12-24 16:38
@huoyaoyuan, it seems when we call `CopyTo(array)`  on Windows or Linux operating system instead of `CopyTo(array, 0)`  is called 
`CopyTo(array, i)`, however on macOS it works as you described.

**Comment by huoyaoyuan** [comment] 2020-12-24 17:34
There's no difference of the managed code on different OSes.
Your description sounds like a critical codegen bug. In this case, you should confirm your hardware, is it x64 Intel or arm64 Apple Silicon.

A full reproduction is also useful.

**Comment by danmosemsft** [comment] 2020-12-24 22:53
Moving to codegen since it is Mac specific and the managed code is the same so it is most likely codegen.

**Comment by toor1245** [comment] 2020-12-25 16:41
@danmosemsft it seems to me it is a problem in code generation not on macOS in my opinion not correct occurs code generation on Windows and Linux because only macOS correctly use `CopyTo(array, 0)` when on other OS it seems to use `CopyTo(array, i) `

**Comment by JulieLeeMSFT** [comment] 2020-12-28 17:28
@sandreenko PTAL.

**Comment by sandreenko** [comment] 2021-03-24 23:35
@BruceForstall could you please take it since you have an x64 OSX setup?

**Comment by BruceForstall** [comment] 2021-04-29 00:00
@toor1245 Does this problem still exist?

If so, can you provide a complete, standalone test case? (Your test case above references a lot of your own code, it appears)

**Closed** 2021-04-29 17:16 UTC
Labels: area-CodeGen-coreclr, needs further triage, os-mac-os-x
