### ISSUE TITLE
AcceptAsyncV6BoundToSpecificV4_CantConnect - failed

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#31233] opened 2019-10-21 07:31 UTC
Test: `System.Net.Sockets.Tests.DualModeAcceptAsync.AcceptAsyncV6BoundToSpecificV4_CantConnect`

https://dnceng.visualstudio.com/public/_build/results?buildId=395162&view=ms.vss-test-web.build-test-results-tab&runId=12321658&resultId=176974&paneView=debug

Configuration: `netcoreapp-Windows_NT-Release-x64-Windows.10.Amd64.Client19H1.Open`

```
Assert.Throws() Failure
Expected: typeof(System.Net.Sockets.SocketException)
Actual: typeof(System.TimeoutException): Timed out while waiting for either of client and server connections...
---- System.TimeoutException : Timed out while waiting for either of client and server connections...
  at System.Net.Sockets.Tests.DualModeAcceptAsync.DualModeConnect_AcceptAsync_Helper(IPAddress listenOn, IPAddress connectTo) in /_/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 976
   at System.Net.Sockets.Tests.DualModeAcceptAsync.<AcceptAsyncV6BoundToSpecificV4_CantConnect>b__4_0() in /_/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 915
----- Inner Stack Trace -----
   at System.Net.Sockets.Tests.DualModeAcceptAsync.DualModeConnect_AcceptAsync_Helper(IPAddress listenOn, IPAddress connectTo) in /_/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 976
   at System.Net.Sockets.Tests.DualModeAcceptAsync.<AcceptAsyncV6BoundToSpecificV4_CantConnect>b__4_0() in /_/src/System.Net.Sockets/tests/FunctionalTests/DualModeSocketTest.cs:line 915
```

@davidsh, @wfurt, @scalablecory, @eiriktsarpalis, @karelz

**Comment by karelz** [comment] 2020-04-03 22:25
Duplicate of #22620

**Closed by karelz** 2020-04-03 22:25 UTC
Labels: area-System.Net.Sockets, os-windows, test bug, test-run-core
