### ISSUE TITLE
Polymorphic Serialization - Doesn't allow typeDiscriminator to be anything but first

### ISSUE THREAD

**Issue by RyanGaudion** [dotnet/runtime#73693] opened 2022-08-10 14:05 UTC
### Description

I have this endpoint:
```
[HttpPost]
public async Task<IActionResult> Add([FromBody] BaseClass test)
{
    //...
}
```
and my BaseClass is annotated as follows:
```
[JsonPolymorphic(TypeDiscriminatorPropertyName = "resourceType")]
[JsonDerivedType(typeof(DerivedClass1), typeDiscriminator: nameof(DerivedClass1))]
[JsonDerivedType(typeof(DerivedClass2), typeDiscriminator: nameof(DerivedClass2))]
```

When sending a json body where `resourceType` is anything but the first property, I get the following error:
```
{
	"type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
	"title": "One or more validation errors occurred.",
	"status": 400,
	"traceId": "...",
	"errors": {
		"$.resourceType": [
			"The metadata property is either not supported by the type or is not the first property in the deserialized JSON object. Path: $.resourceType | LineNumber: 2 | BytePositionInLine: 16."
		]
	}
}
```

### Reproduction Steps

Sending this as a POST request throws the error:
```
{
	"prop1": 1,
	"resourceType": "DerivedClass1",
	"prop2": "test",
}
```

however this doesn't:
```
Sending this as a POST request throws the error:
```
{
        "resourceType": "DerivedClass1",
	"prop1": 1,
	"prop2": "test",
}
```
```

### Expected behavior

I understand the performance advantages to having the discriminator as the first property however is there a toggle/option that can be set to allow the JsonSerializer to look through the whole jsonObject first for the discriminator?

### Actual behavior

....

**Comment by RyanGaudion** [comment] 2022-08-10 14:07
FYI - Using .Net 7 Preview 7

**Comment by Tornhoof** [comment] 2022-08-10 14:11
See https://github.com/dotnet/runtime/issues/72604

**Comment by layomia** [comment] 2022-08-10 19:36
Duplicate of https://github.com/dotnet/runtime/issues/72604.

**Closed by layomia** 2022-08-10 19:36 UTC
Labels: area-System.Text.Json, untriaged
