### ISSUE TITLE
[Perf -13%] Microsoft.Extensions.Primitives.StringSegmentBenchmark.EndsWith

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#40866] opened 2020-08-14 23:30 UTC
### Run Information

Architecture | x64
-- | --
OS | Windows 10.0.18362
Changes | [diff](https://github.com/dotnet/runtime/compare/3218c128072962fc90d92677c704f8653e1777a0...d7506e7d04b5dadf40e48896a8c1585ed10cd354)

### Regressions in Microsoft.Extensions.Primitives.StringSegmentBenchmark

Benchmark | Baseline | Test | Test/Base | Modality | Baseline Outlier
-- | -- | -- | -- | -- | --
[EndsWith](<https://pvscmdupload.blob.core.windows.net/reports/08_12_2020/allTestHistory/Microsoft.Extensions.Primitives.StringSegmentBenchmark.EndsWith.html>) | 9.44 ns | 10.78 ns | 1.14 | Bimodal | True

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/08_14_2020/refs/heads/master_x64_Windows%2010.0.18362/Microsoft.Extensions.Primitives.StringSegmentBenchmark_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/08_14_2020/refs/heads/master_x64_Windows%2010.0.18362/Microsoft.Extensions.Primitives.StringSegmentBenchmark.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'Microsoft.Extensions.Primitives.StringSegmentBenchmark*'
```
<details>

#### Microsoft.Extensions.Primitives.StringSegmentBenchmark.EndsWith

```log
[ 8.933 ;  9.178) | @@@@@@@@@@@@@@@@@@@@@@@@@@
[ 9.178 ;  9.457) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 9.457 ;  9.762) | @
[ 9.762 ; 10.041) | @@@@@@@@@@@@@@@@@@@@@@@
[10.041 ; 10.332) | @
[10.332 ; 10.589) | @@
[10.589 ; 10.868) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by gfoidl** [comment] 2020-08-15 08:42
Just to point out that there is https://github.com/dotnet/runtime/issues/39140 (fix is https://github.com/dotnet/runtime/pull/39853), so maybe it's more interesting to validate the numbers after this change is in.

**Comment by ericstj** [comment] 2020-08-27 21:26
This method hasn't changed since we moved the code.  There was a change around the time of this regression in `string.Compare` which this method calls.  @GrabYourPitchforks it looks like https://github.com/dotnet/runtime/commit/189e1aa8f91632c196fe0e6cb1410a85bb7d2283#diff-a70aebfa78baa09ba9bb366e971a14ca occurred around the same time.  Is it possible that this caused a regression here?

**Comment by eerhardt** [comment] 2020-09-02 20:43
I cannot reproduce this regression locally. I've tried from commit https://github.com/dotnet/runtime/commit/ca9547949d8d9612d3dcff1babb001112b36fd93 to https://github.com/dotnet/runtime/commit/4ec3a25cfa9555d5ec07ec6ab2c8db98ad0489c8 (which is basically July 25 to Aug 9).

Here are the results I am seeing locally:

Before (commit ca95479)
|   Method |     Mean |    Error |   StdDev |   Median |      Min |      Max | Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------- |---------:|---------:|---------:|---------:|---------:|---------:|------:|------:|------:|----------:|
| EndsWith | 10.36 ns | 0.085 ns | 0.075 ns | 10.36 ns | 10.21 ns | 10.50 ns |     - |     - |     - |         - |
| EndsWith | 10.31 ns | 0.196 ns | 0.183 ns | 10.33 ns | 9.989 ns | 10.58 ns |     - |     - |     - |         - |
| EndsWith | 10.39 ns | 0.104 ns | 0.081 ns | 10.42 ns | 10.21 ns | 10.52 ns |     - |     - |     - |         - |

After (commit  4ec3a25)

|   Method |     Mean |    Error |   StdDev |   Median |      Min |      Max | Gen 0 | Gen 1 | Gen 2 | Allocated |
|--------- |---------:|---------:|---------:|---------:|---------:|---------:|------:|------:|------:|----------:|
| EndsWith | 10.27 ns | 0.117 ns | 0.110 ns | 10.23 ns | 10.11 ns | 10.47 ns |     - |     - |     - |         - |
| EndsWith | 10.31 ns | 0.107 ns | 0.090 ns | 10.29 ns | 10.19 ns | 10.52 ns |     - |     - |     - |         - |

Looking at this benchmark, the [version of Microsoft.Extensions.Primitives](https://github.com/dotnet/performance/blob/91888ba414526917bc4883e9cc0b4cf077525836/src/benchmarks/micro/MicroBenchmarks.csproj#L30) did not change in this time frame. The benchmark was always hard-coded to use `5.0.0-preview.4.20251.6`. So if something regressed here, it had to be in the 1 method EndsWith calls - `string.Compare(string, int, string, int, int, StringComparison)`. Note that the benchmark is only using `StringComparison.Ordinal`.

Looking at the history of `string.Compare`, @GrabYourPitchforks did change some OrdinalIgnoreCase code around this time, but that change didn't affect the Ordinal code path, so his change should not have affected this.

Given the above information, I'm going to close this issue as "not repro". If we can get a reproducible regression, please re-open and I can take a look.

**Closed by eerhardt** 2020-09-02 20:43 UTC
Labels: arch-x64, area-Extensions-Primitives, os-windows, tenet-performance, tenet-performance-benchmarks
