### ISSUE TITLE
[API Proposal]: property MessageEN in class System.Exception

### ISSUE THREAD

**Issue by TobiasKnauss** [dotnet/runtime#72277] opened 2022-07-15 16:12 UTC
### Background and motivation

https://www.google.com/search?q=c%23+english+exception+messages
There are dozens of more or less bad and ugly workarounds to get English exception messages instead of localized exception messages:
https://stackoverflow.com/questions/209133/exception-messages-in-english
https://stackoverflow.com/questions/2092298/force-exceptions-language-in-english
https://stackoverflow.com/questions/31681139/c-sharp-getting-exception-messages-in-english-when-the-application-is-in-anoth
https://stackoverflow.com/questions/529951/how-to-change-visual-studio-exception-message-language-to-english-while-debuggin
https://stackoverflow.com/a/17994183/2505186: "The .NET framework contains localized exception messages. For me as a developer, that's very annoying, ..."
https://social.msdn.microsoft.com/Forums/vstudio/en-US/6f5526b3-e114-4308-a74a-010f93f870a4/how-to-change-language-of-exception-messages?forum=netfxsetup
https://itecnote.com/tecnote/c-getting-exception-messages-in-english-when-the-application-is-in-another-language/
https://itecnote.com/tecnote/c-exception-messages-in-english/
https://www.reddit.com/r/dotnet/comments/myumt9/how_can_i_get_visual_studio_exceptions_in_english/
https://bytes.com/topic/c-sharp/answers/489412-how-set-language-exception-message
and more...

This shows that many many users request English exception messages, because almost nobody can read messages when they are neither in the users language, nor in English.
Example: My native language is German, I understand English pretty well. But I do not understand French, Spanish, Chinese, etc. When I get a log file from our software running on a computer with French / Spanish / Chinese language, I am not able to understand the logged exception messages.

Services like https://unlocalize.com/ are just a ugly workaround for something which is missing in the framework.

https://docs.microsoft.com/en-us/dotnet/api/system.exception.message says

> The error message should be localized.

but I don't see any reason for this suggestion or claim.

Please not that all types of exceptions are affected: .NET, Win32 (e.g. socket exceptions), and maybe others.

### API Proposal

Inside class Exception:
```csharp
public virtual string MessageEN => ...
```

### API Usage

```csharp
try
{
  throw new SocketException (10060);
}
catch (Exception exception)
{
  Console.WriteLine (exception.MessageEN);
}
```

### Risks

No risks.
No breaking changes.
Just some work.

**Comment by danmoseley** [comment] 2022-07-15 16:39
@TobiasKnauss in .NET Core, error messages for the core libraries have never been localized. Are your customers running .NET Framework? Or is the problem libraries higher in the stack that do localize (I'm not sure which do)

As far as making this work, one challenge I see here is that much of the time, exceptions are constructed (by some library/user code) with a message already loaded, rather than loading the resource themselves. But I'm guessing that those are exactly the cases you care about, since otherwise you could infer the message from the type of the exception. is that right?

**Comment by svick** [comment] 2022-07-15 16:42
This is mostly a duplicate of https://github.com/dotnet/runtime/issues/46656.

**Comment by danmoseley** [comment] 2022-07-15 16:56
It is a duplicate -- in that issue it was called 'InvariantMessage'

I'll close as dupe, but this keeps coming up and there's no doubt it's important. We should continue the conversation.

**Closed by danmoseley** 2022-07-15 16:56 UTC
Labels: api-suggestion, untriaged

**Comment by TobiasKnauss** [comment] 2022-07-15 18:41
> @TobiasKnauss in .NET Core, error messages for the core libraries have never been localized. 

This contradicts the statement "The error message should be localized." in https://docs.microsoft.com/en-us/dotnet/api/system.exception.message
But I am still happy to read this. English exception messages is what I and many other expect and need.

I tested with a .NET 6 console app, and I already assumed something like that, because I did not get localized exception messages for all managed exception types any more (every type of exception EXCEPT Win32Exceptions). I was unsure whether this might have come from .NET SDK being installed maybe without language pack, or from actual changes in the exception messages.

However, Win32Exceptions are still localized, but I think this may came from texts being provided by the operating system (i.e. Windows 10 in my case). This is still a problem.

> Are your customers running .NET Framework?

We have used .NET Framework 4.8 until end of the last year, and a lot of "old" versions are still in the field. So we still face this problem, but we're not going to update these old versions any more. We will migrate them to new versions based on .NET 6 eventually.

> As far as making this work, one challenge I see here is that much of the time, exceptions are constructed (by some library/user code) with a message already loaded, rather than loading the resource themselves. But I'm guessing that those are exactly the cases you care about, since otherwise you could infer the message from the type of the exception. is that right?

I don't fully understand this part and your assumptions.
Exceptions from all 3rd-party libraries we use are always in English. Our own exceptions are in English as well. I was mainly having issues with the exceptions from .NET (Framework). And I am still having trouble with Win32Exceptions (also in .NET 5+).

How could I infer the message from the type of the exceptions? AFAIK, the exception message may differ based on the parameters given to the exception's constructor. Also, I prefer printing the exception message instead of the exception type, since the message may contain useful information (e.g. parameter name in an ArgumentNullException), which the exception type does not.

With the changes in .NET Core you mention (exception messages not translated), it basically boils down to "how can we get English messages of Win32 exceptions?"

**Comment by danmoseley** [comment] 2022-07-18 03:16
> I don't fully understand this part and your assumptions.
> Exceptions from all 3rd-party libraries we use are always in English. Our own exceptions are in English as well. I was mainly having issues with the exceptions from .NET (Framework). And I am still having trouble with Win32Exceptions (also in .NET 5+).

Leaving aside .NET Framework then, which is the way it is, if you use .NET Core I would expect only messages read from the OS (FormatMessage) to be localized. 

However most or all of those cases, though, I'd expect the exception's HRESULT field to be set to whatever the code was that it looked up, and probably it should appear in the ToString() as well. For example, `new Win32Exception(122)` gives a string from the OS like `The data area passed to a system call is too small.` but the NativeErrorCode on the exception is 123 and that appears in the ToString() as well: `System.ComponentModel.Win32Exception (122): The data area passed to a system call is too small.`.

Do you have an example of a case where this isn't true on .NET Core? We can perhaps fix them.

This doesn't fix .NET Framework of course, but that has been that way for 20 years now and it is not possible to change now.. If translators didn't help me, I would download the .NET Framework specific to the locale of my customer, use ILSPY to save the resources, and grep them.
