### ISSUE TITLE
[Perf] Regressions in System.Text.Json.Serialization.Tests.WriteJson<Int32>

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#54171] opened 2021-06-14 20:11 UTC
### Run Information

Architecture | arm64
-- | --
OS | Windows 10.0.19041
Baseline | [bc0fda4e9bff863551be27e52cb84ea3bc0573cb](https://github.com/dotnet/runtime/commit/bc0fda4e9bff863551be27e52cb84ea3bc0573cb)
Compare | [44f050acc0f7791d6cd7ac772945444912bcf299](https://github.com/dotnet/runtime/commit/44f050acc0f7791d6cd7ac772945444912bcf299)
Diff | [Diff](https://github.com/dotnet/runtime/compare/bc0fda4e9bff863551be27e52cb84ea3bc0573cb...44f050acc0f7791d6cd7ac772945444912bcf299)

### Regressions in System.Text.Json.Serialization.Tests.WriteJson&lt;Int32&gt;

Benchmark | Baseline | Test | Test/Base | Test Quality | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
[SerializeToString - Duration of single invocation](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_arm64_Windows 10.0.19041/System.Text.Json.Serialization.Tests.WriteJson(Int32).SerializeToString.html>) | 257.44 ns | 276.18 ns | 1.07 | 0.16 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/06_02_2021/refs/heads/main_arm64_Windows%2010.0.19041_Regression/System.Text.Json.Serialization.Tests.WriteJson(Int32)_1.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/06_02_2021/refs/heads/main_arm64_Windows%2010.0.19041_Regression/System.Text.Json.Serialization.Tests.WriteJson(Int32).html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
py .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Text.Json.Serialization.Tests.WriteJson&lt;Int32&gt;*'
```
<details>

### Payloads

[Baseline](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-c9279d43-b079-4b58-99c1-003753b103fd602a0fbcc624666a3/9adb1e24-5817-440b-b08a-5f39116cfbda.zip?sv=2019-07-07&se=2021-06-26T02%3A40%3A50Z&sr=c&sp=rl&sig=%2Bt3tCm%2FW3%2FEJ0nAPO7SmQA4OGasQNJU7vRoT0VWbdEc%3D>)
[Compare](<https://helixdi8s23ayyeko0k025g8.blob.core.windows.net/helix-job-6367d3c6-88bf-44ae-a839-4e37193d9efc99827dc5bfd4c1b8e/9e55cbfc-315f-4abf-97be-2bd78751495f.zip?sv=2019-07-07&se=2021-06-26T13%3A11%3A53Z&sr=c&sp=rl&sig=axEf1%2FD8gqICYnPiTuCG7nPiUDRn0AmF20DdSc6xCqo%3D>)

#### System.Text.Json.Serialization.Tests.WriteJson&lt;Int32&gt;.SerializeToString

```log

```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by ericstj** [comment] 2021-07-26 23:18
@layomi another one caused by https://github.com/dotnet/runtime/commit/6e5f722a9dab49f9626ea95326ef6e74129621ca similar to https://github.com/dotnet/runtime/issues/54174#issuecomment-887090135

Again looks like we regained the perf:
![image](https://user-images.githubusercontent.com/8918108/127071171-355a603d-9b14-4818-b77f-d518068b0d2c.png)

**Comment by DrewScoggins** [comment] 2021-07-27 00:23
Yeah, looks like https://github.com/dotnet/runtime/pull/54420, got us this regression back. And the rest of the improvements where from JIT changes to use PGO data.

**Comment by layomia** [comment] 2021-07-27 17:26
@ericstj, @DrewScoggins I believe it was this diff that caused/reversed the regression from the JSON side https://github.com/dotnet/runtime/pull/54420/files#r654564729. Unless there are objections, I'll close this issue and https://github.com/dotnet/runtime/issues/54174.

**Closed by layomia** 2021-07-27 17:26 UTC
Labels: arch-arm64, area-System.Text.Json, needs further triage, os-windows, tenet-performance, tenet-performance-benchmarks
