### ISSUE TITLE
Add GetTempFile(string extension)

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#40414] opened 2020-08-05 20:18 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/idea/989476/add-gettempfilestring-extension.html)._

---
<p>`Path.GetTempFile()` is woefully lacking in features when compared to Linux's `tempfile`. In particular, it lacks one key feature which is far more important in Windows than in Linux: the ability to specify a file extension. In my particular use case I needed the correct extension for `System.Windows.Media.MediaPlayer` to correctly handle the file I was creating, and have been forced to give up the guarantees of `GetTempFile()` in exchange for the guarantee of having my file correctly detected as playable.</p> <p>I'm sure there are other use cases where `Path.GetTempFile(string extension)` would be invaluable.</p>

---
#### Feedback Bot on 4/14/2020, 02:45 AM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by danmosemsft** [comment] 2020-08-05 20:23
Would someone interested in this like to format the request as an API proposal? 
https://github.com/dotnet/runtime/issues/new?assignees=&labels=api-suggestion&template=02_api_proposal.md&title=

**Comment by danmosemsft** [comment] 2020-08-05 20:31
BTW, I assume this refers to `Path.GetTempFileName()`. 

Java, for what its worth: 
```
static File | createTempFile(String prefix, String suffix)Creates an empty file in the default temporary-file directory, using the given prefix and suffix to generate its name.
static File | createTempFile(String prefix, String suffix, File directory)Creates a new empty file in the specified directory, using the given prefix and suffix strings to generate its name.
```

It should be pretty safe to just add an extension on the end yourself, though. `GetTempFileName()` is wierd in that it _creates_ the file, which is a legacy of Windows's GetTempFileNameW. In our own tests, we create a name using `Guid.NewGuid().ToString("N").Substring(0, 8)` which has zero chance of colliding in normal circumstances.

**Comment by iSazonov** [comment] 2020-08-07 18:32
Dup https://github.com/dotnet/runtime/issues/23538 and https://github.com/dotnet/runtime/issues/2048

**Comment by danmosemsft** [comment] 2020-08-07 19:17
I think that's a reasonable dupe, thanks, since it does mention configurable names. Meantime I recommend just suffixing the extension manually

**Comment by danmosemsft** [comment] 2020-08-07 19:17
Duplicate of #2048

**Closed by danmosemsft** 2020-08-07 19:17 UTC
Labels: api-suggestion, area-System.IO, untriaged
