### ISSUE TITLE
[MONO][PERF] 9-15 % Regressions in Microsoft.Extensions.DependencyInjection.TimeToFirstService

### ISSUE THREAD

**Issue by naricc** [dotnet/runtime#48089] opened 2021-02-09 23:30 UTC
Likely culprit is this change: https://github.com/dotnet/runtime/commit/6cf1b8ec012d52880d46fa4773f60ed52ddc9f3d

### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [f1ad1b97e9387dc700bf72917f29fc7d1258ac1a](https://github.com/dotnet/runtime/commit/f1ad1b97e9387dc700bf72917f29fc7d1258ac1a)
Compare | [796848aec642d1f8cc2c0d2ee6329ac6ecbd247e](https://github.com/dotnet/runtime/commit/796848aec642d1f8cc2c0d2ee6329ac6ecbd247e)

### Regressions in Microsoft.Extensions.DependencyInjection.TimeToFirstService

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[BuildProvider](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono/Microsoft.Extensions.DependencyInjection.TimeToFirstService.BuildProvider(Mode%3a%20%22ILEmit%22).html>) | 1.80 μs | 2.01 μs | 1.12 | | |
[BuildProvider](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono/Microsoft.Extensions.DependencyInjection.TimeToFirstService.BuildProvider(Mode%3a%20%22Runtime%22).html>) | 1.76 μs | 2.03 μs | 1.15 | | |
[BuildProvider](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono/Microsoft.Extensions.DependencyInjection.TimeToFirstService.BuildProvider(Mode%3a%20%22Expressions%22).html>) | 1.75 μs | 1.95 μs | 1.11 | | |
[Singleton](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono/Microsoft.Extensions.DependencyInjection.TimeToFirstService.Singleton(Mode%3a%20%22ILEmit%22).html>) | 8.64 μs | 9.46 μs | 1.09 | | |

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/01_26_2021/refs/heads/master_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/Microsoft.Extensions.DependencyInjection.TimeToFirstService_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/01_26_2021/refs/heads/master_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/Microsoft.Extensions.DependencyInjection.TimeToFirstService_2.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/01_26_2021/refs/heads/master_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/Microsoft.Extensions.DependencyInjection.TimeToFirstService_3.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/01_26_2021/refs/heads/master_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/Microsoft.Extensions.DependencyInjection.TimeToFirstService_4.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/01_26_2021/refs/heads/master_x64_ubuntu%2018.04_LLVM=false_MonoAOT=false_MonoInterpreter=false_RunKind=micro_mono_Regression/Microsoft.Extensions.DependencyInjection.TimeToFirstService.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'Microsoft.Extensions.DependencyInjection.TimeToFirstService*'
```
<details>

.
### Payloads

[Baseline](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-8f38a3ae-aed2-465a-827f-f73470769aa171492ba5c70469b9c/69a2f29a-296d-4b59-b76a-a1bb8f897ce8.zip?sv=2019-07-07&se=2021-02-21T23%3A17%3A12Z&sr=c&sp=rl&sig=qVs8a2SEgMBIJjeMsrm%2Bl3xKxom%2B44wvu3lxdArb8kg%3D>)
[Compare](<https://helixdi107v0xdeko0k025g8.blob.core.windows.net/helix-job-d69cd2c0-25ce-4498-884f-34927b3d428e2c5f9714b81407584/cb6ecd55-5d0d-44f3-9c49-663151bc9517.zip?sv=2019-07-07&se=2021-02-23T10%3A49%3A28Z&sr=c&sp=rl&sig=Xa5bxmy6ApFHGYvSlh9QfwkkPEnKgsFw94InoxRgYfs%3D>)

#### Microsoft.Extensions.DependencyInjection.TimeToFirstService.BuildProvider(Mode: "ILEmit")

```log
[1657.670 ; 1707.317) | @@@@
[1707.317 ; 1743.224) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[1743.224 ; 1806.465) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[1806.465 ; 1864.642) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[1864.642 ; 1906.749) | @@@@
[1906.749 ; 1953.478) | @
[1953.478 ; 2048.458) | @@@@@@@@@@@@
```
#### Microsoft.Extensions.DependencyInjection.TimeToFirstService.BuildProvider(Mode: "Runtime")

```log
[1683.507 ; 1744.913) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[1744.913 ; 1810.017) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[1810.017 ; 1874.072) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[1874.072 ; 1931.168) | @@@
[1931.168 ; 1974.478) | @@@
[1974.478 ; 2073.685) | @@@@@@@@@
```
#### Microsoft.Extensions.DependencyInjection.TimeToFirstService.BuildProvider(Mode: "Expressions")

```log
[1620.248 ; 1667.170) | @
[1667.170 ; 1713.092) | @@@@@@@@@@@@@@@@@@@
[1713.092 ; 1778.618) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[1778.618 ; 1839.328) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[1839.328 ; 1893.620) | @@@@@@@@@@@@@@@
[1893.620 ; 1960.673) | @@@@@@
[1960.673 ; 2035.185) | @@@@@@@@@
[2035.185 ; 2096.852) | @
```
#### Microsoft.Extensions.DependencyInjection.TimeToFirstService.Singleton(Mode: "ILEmit")

```log
[8394.223 ; 8606.590) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[8606.590 ; 8913.573) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[8913.573 ; 9163.796) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[9163.796 ; 9568.064) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by danmoseley** [comment] 2021-02-19 19:52
dupe of https://github.com/dotnet/runtime/issues/47867 I think.

**Closed by danmoseley** 2021-02-19 19:52 UTC
Labels: area-Codegen-JIT-mono, tenet-performance-benchmarks, untriaged
