### ISSUE TITLE
readytorun coreroot_determinism tests failing

### ISSUE THREAD

**Issue by Anipik** [dotnet/runtime#48719] opened 2021-02-24 19:39 UTC
```
   readytorun\coreroot_determinism\coreroot_determinism\coreroot_determinism.cmd [FAIL]
      1 / 1 (100%, 1 failed): failed in 23011 msecs, exit code -1073740286 = 0xC0000602, expected 0: corerun.exe C:\h\w\B3510949\p\crossgen2\crossgen2.dll @C:\h\w\B3510949\w\A68F08F4\e\readytorun\coreroot_determinism\coreroot_determinism\seed1\CPAOT-ret.out\System.Private.CoreLib.dll.rsp
      !! Assert failure(PID 5600 [0x000015e0], Thread: 6236 [0x185c]): CONTRACT VIOLATION by Thread::SetFrame at "D:\workspace\_work\1\s\src\coreclr\vm\threads.cpp" @ 212
      !! MODE_COOPERATIVE encountered while thread is in preemptive state.
      !!                         CONTRACT in Thread::SetFrame at "D:\workspace\_work\1\s\src\coreclr\vm\threads.cpp" @ 212
      !!                         CONTRACT in HijackFrame::HijackFrame at "D:\workspace\_work\1\s\src\coreclr\vm\threadsuspend.cpp" @ 4970
      !!                         CONTRACT in OnHijackWorker at "D:\workspace\_work\1\s\src\coreclr\vm\threadsuspend.cpp" @ 4984
      !!                         CONTRACT in MethodDescCallSite::CallTargetWorker at "D:\workspace\_work\1\s\src\coreclr\vm\callhelpers.cpp" @ 287
      !!                         GCX_COOP in Assembly::ExecuteMainMethod at "D:\workspace\_work\1\s\src\coreclr\vm\assembly.cpp" @ 1670
      !!                         CONTRACT in Assembly::ExecuteMainMethod at "D:\workspace\_work\1\s\src\coreclr\vm\assembly.cpp" @ 1654
      !!                         GCX_COOP in CorHost2::ExecuteAssembly at "D:\workspace\_work\1\s\src\coreclr\vm\corhost.cpp" @ 357
      !!                         CONTRACT in CorHost2::ExecuteAssembly at "D:\workspace\_work\1\s\src\coreclr\vm\corhost.cpp" @ 306
      !! We can't find the violated contract. Look for an old-style non-holder-based contract.
      !! CORECLR! CONTRACT_ASSERT + 0x2C8 (0x70664cf9)
      !! CORECLR! EEContract::DoChecks + 0x144 (0x70903d0e)
      !! CORECLR! Thread::SetFrame + 0x208 (0x70878430)
      !! CORECLR! HijackFrame::HijackFrame + 0xD8 (0x70a52d09)
      !! CORECLR! OnHijackWorker + 0xBF (0x70a5b34e)
      !! CORECLR! OnHijackTripThread + 0x11 (0x70b9b9ee)
      !! CLRJIT_WIN_X86_X86! Compiler::impImportBlockCode + 0x3C6A (0x6f74e350)
      !! CLRJIT_WIN_X86_X86! Compiler::impImportBlock + 0xC3 (0x6f74a054)
      !! CLRJIT_WIN_X86_X86! Compiler::impImport + 0x2E1 (0x6f749a1c)
      !! CLRJIT_WIN_X86_X86! Compiler::fgImport + 0xA (0x6f72226a)
      !!     File: D:\workspace\_work\1\s\src\coreclr\vm\threads.cpp Line: 212
      !!     Image: C:\h\w\B3510949\p\corerun.exe
      
      Return code:      1
      Raw output file:      C:\h\w\B3510949\w\A68F08F4\e\readytorun\coreroot_determinism\Reports\readytorun.coreroot_determinism\coreroot_determinism\coreroot_determinism.output.txt
      Raw output:
```

log https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-master-fea0bf770da7486089/PayloadGroup0/console.41525101.log?sv=2019-07-07&se=2021-03-15T03%3A26%3A04Z&sr=c&sp=rl&sig=la366P7ckDxpsUD%2FLf5c8dhPc3t7lE8Nt75BQbvsvvE%3D

build https://dev.azure.com/dnceng/public/_build/results?buildId=1007151&view=logs&j=d41eb98a-9c3b-56b2-807e-d9279670850b&t=eb9b1915-3d14-5e50-1ffd-74091760a393

**Comment by hoyosjs** [comment] 2021-02-24 19:51
This is a dupe of #45326

**Closed** 2021-02-24 19:52 UTC
Labels: area-Infrastructure-coreclr, blocking-clean-ci

**Comment by trylek** [comment] 2021-03-02 00:51
I see a similar failure in a recent run PR verifying the Armel Crossgen2 fixes,

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-45058-merge-3770451e4b38461095/PayloadGroup0/console.d9b9651c.log?sv=2019-07-07&se=2021-03-21T23%3A47%3A03Z&sr=c&sp=rl&sig=mSdU4fmeMfJxQz1WXDmNKcSInkLhEqhT%2FGubPJMh9Po%3D

<pre>
  Starting:    readytorun.coreroot_determinism.XUnitWrapper
    readytorun\coreroot_determinism\coreroot_determinism\coreroot_determinism.cmd [FAIL]
      1 / 1 (100%, 1 failed): failed in 23850 msecs, exit code -1073740286 = 0xC0000602, expected 0: corerun.exe C:\h\w\98900912\p\crossgen2\crossgen2.dll @C:\h\w\98900912\w\B3740973\e\readytorun\coreroot_determinism\coreroot_determinism\seed1\CPAOT-ret.out\System.Private.CoreLib.dll.rsp
      !! Assert failure(PID 8488 [0x00002128], Thread: 8644 [0x21c4]): CONTRACT VIOLATION by Thread::SetFrame at "D:\workspace\_work\1\s\src\coreclr\vm\threads.cpp" @ 212
      !! MODE_COOPERATIVE encountered while thread is in preemptive state.
      !!                         CONTRACT in Thread::SetFrame at "D:\workspace\_work\1\s\src\coreclr\vm\threads.cpp" @ 212
      !!                         CONTRACT in HijackFrame::HijackFrame at "D:\workspace\_work\1\s\src\coreclr\vm\threadsuspend.cpp" @ 4970
      !!                         CONTRACT in OnHijackWorker at "D:\workspace\_work\1\s\src\coreclr\vm\threadsuspend.cpp" @ 4984
      !!                         CONTRACT in DispatchCallSimple at "D:\workspace\_work\1\s\src\coreclr\vm\callhelpers.cpp" @ 185
      !!                         CONTRACT in ThreadNative::KickOffThread_Worker at "D:\workspace\_work\1\s\src\coreclr\vm\comsynchronizable.cpp" @ 148
      !!                         CONTRACT in ManagedThreadBase_DispatchInner at "D:\workspace\_work\1\s\src\coreclr\vm\threads.cpp" @ 7294
      !!                         CONTRACT in ManagedThreadBase_FullTransition at "D:\workspace\_work\1\s\src\coreclr\vm\threads.cpp" @ 7543
      !!                         CONTRACT in ThreadNative::KickOffThread at "D:\workspace\_work\1\s\src\coreclr\vm\comsynchronizable.cpp" @ 196
      !! We can't find the violated contract. Look for an old-style non-holder-based contract.
      !! CORECLR! CONTRACT_ASSERT + 0x2C8 (0x702a4cf9)
      !! CORECLR! EEContract::DoChecks + 0x144 (0x705438b4)
      !! CORECLR! Thread::SetFrame + 0x208 (0x704b8343)
      !! CORECLR! HijackFrame::HijackFrame + 0xD8 (0x70692899)
      !! CORECLR! OnHijackWorker + 0xBF (0x7069aede)
      !! CORECLR! OnHijackTripThread + 0x11 (0x707db69e)
      !! CLRJIT_WIN_X86_X86! Compiler::impDevirtualizeCall + 0x59F (0x6f397ed2)
      !! CLRJIT_WIN_X86_X86! Compiler::fgLateDevirtualization + 0xD4 (0x6f3635d4)
      !! CLRJIT_WIN_X86_X86! GenericTreeWalker<1,1,1,0,1>::PostOrderVisit + 0x21 (0x6f360fd8)
      !! CLRJIT_WIN_X86_X86! GenTreeVisitor<GenericTreeWalker<1,1,1,0,1> >::WalkTree + 0xB2 (0x6f3610db)
      !!     File: D:\workspace\_work\1\s\src\coreclr\vm\threads.cpp Line: 212
      !!     Image: C:\h\w\98900912\p\corerun.exe
</pre>

It looks like problem is related to hijacking JIT. @janvorli is the traditional expert in this field but he's likely to be OOF for some time, @jkotas - could you please advise how to further investigate this issue? I recall that some time ago you advised me on a similar issue that was caused by CG2 missing some fixups but so far I haven't managed to track this issue down to a similar thing.

Thanks

Tomas

**Comment by jkotas** [comment] 2021-03-02 02:10
See https://github.com/dotnet/runtime/issues/45326#issuecomment-788520454
