### ISSUE TITLE
NativeAOT: IsInstanceOfType on interface fails in reflection-free 

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtime#69960] opened 2022-05-29 11:08 UTC
### Description

M.S.DI fails on NativeAOT + Linux when compile using reflection-free mode. Crash happens in the https://github.com/dotnet/runtime/blob/215b39abf947da7a40b0cb137eab4bceb24ad3e3/src/libraries/Microsoft.Extensions.DependencyInjection/src/ServiceLookup/ConstantCallSite.cs#L16 and that's only one location which prevent current DI from being used in reflection-free mode.

Only issue is call to `typeof(InterfaceType).IsInstanceOfType()`. If I do call `typeof(ClassType).IsInstanceOfType()` then reflection-free chew this code just fine. Below repro.

### Reproduction Steps

```csharp
var x = new T();
var xType = typeof(IInterface1);
var result = xType.IsInstanceOfType(x);
interface IInterface1 { }
class T: IInterface1 { }
```
csproj
```xml
<IlcDisableReflection>true</IlcDisableReflection>
```

### Expected behavior

Do not crash

### Actual behavior

segfaulted

**Comment by jkotas** [comment] 2022-05-29 12:58
This is duplicate of https://github.com/dotnet/runtime/issues/67193

**Closed by jkotas** 2022-05-29 12:58 UTC
Labels: untriaged, area-NativeAOT-coreclr
