### ISSUE TITLE
Process.WaitForExit() hangs forever even though the process has exited in some cases

### ISSUE THREAD

**Issue by madelson** [dotnet/runtime#29232] opened 2019-04-11 11:34 UTC
**Setup**

Launch a process with stream redirection where that process itself launches a long-running process:

```
// in the host process (process1.exe)
var process2 = new Process
{
    StartInfo = 
    {
        FileName = "process2.exe"
        UseShellExecute = false,
        RedirectStandardOutput = true
    }
};
process2.OutputDataReceived += (o, e) => Console.WriteLine(e.Data);
process2.Start();
process2.BeginOutputReadLine();
process2.WaitForExit(); // never returns, even though process2 does exit fairly quickly
return; // returns from Main(), exiting

// in process2.exe
Console.WriteLine("Launching process3.exe!");
var process3 = new Process { StartInfo = { FileName = "process3.exe", UseShellExecute = false } };
process3.Start();
process3.Dispose();

// in process3.exe
while (true) // loop basically forever performing background tasks
{
     ...
}
```

**Expected Behavior**
Process1 receives the output of Process2. Once Process2 has exited, Process1 can move on from its `WaitForExit()` call. Meanwhile Process3 continues to run.

**Actual Behavior**
`WaitForExit()` never returns.

**Notes**
I believe the problem is that `WaitForExit()` waits for EOF to be returned from redirected streams that are being consumed asynchronously. However, I think that Process3 is somehow inheriting the stdio handles from Process2 which prevents EOF from being sent even after Process2 exits.

Note that unlike dotnet/runtime#26165 and dotnet/runtime#27115 , I am observing the behavior on Windows. I'm not sure if the same would happen on Linux.

**Comment by riku76** [comment] 2020-02-13 13:12
I have the exact same issue on Linux that repeats when a native daemon is running my .NET Core 3.1.1 application as a child and this child is spawning another native child (eg. df or grep) the WaitForExit never returns even if the StandardOutput/Error are NOT redirected. From htop I can see that the child exits, shows quickly as a Zombie and then goes away, so it looks like .NET Core is closing the handle, but somehow ignoring that it exited. Also, the same code works fine if executed on command-line OR under Mono 6.4.0 (even under daemon). Platform is Raspberry Pi 4 (armv7).

**Comment by tmds** [comment] 2020-02-13 13:31
@riku76 the issue described here is related to how a redirected stream keeps WaitForExit from returning. Since you are not redirecting streams, the root cause is different. Can you create a new issue?

**Comment by riku76** [comment] 2020-02-13 14:00
@tmds created: [https://github.com/dotnet/runtime/issues/32225](url)

**Comment by EHerzog76** [comment] 2023-01-02 07:29
Process.WaitForExit() hangs forever
Process.WaitForExit(60000) hangs until the timeout is reached.

In the case, when you use    RedirectStandardOutput
    -) and you read the result syncron  with   Proess.ReadToEnd()
    -) and you start a child-process e.g.:
               Process.StartInfo.FileName = "powershell.exe";
               Process.StartInfo.Arguments = "-NonInteractive -NoProfile -Command "& {Write-Output \"Create a session with New-PSSession ...\"; Invoke-Command -Session $session -ScriptBlock { Get-Process | ConvertTo-Json }; Write-Output \"Delete your session ...\"}";

Until now the only work-a-round is to read the StandardOutput  asynchron   with   Process.BeginOutputReadLine();
Working code pattern can be found here:
https://stackoverflow.com/questions/139593/processstartinfo-hanging-on-waitforexit-why/53504707#53504707

**Comment by Evengard** [comment] 2023-03-02 06:43
Any news on that one? dotnet test seems to be affected by that, and every dotnet test in my CI is running for 15 minutes because of that.

**Comment by tmds** [comment] 2023-03-02 09:46
The expected behavior is that WaitForExit, when output is redirected, waits until the output had finished.

If the are grandchildren keeping the output open, then they keep the WaitForExit from returning. Though that may seem weird, output is output independent of it being produced by the direct child or a grandchild. If the grandchild isn't actually providing output, then the child should start it with redirected output. That is an issue with the child process, not with the .NET process that started the child.

For WaitForExit not working well in containers, there was a fix in .NET 7.0.3+.

**Comment by Evengard** [comment] 2023-03-02 19:38
I just tried a .NET 7.0 docker container (sdk:7.0), it still hangs. So the problem probably is still here...

**Comment by tmds** [comment] 2023-03-02 20:06
Does `dotnet test` work fine for you when running outside of a container, and do you only have an issue when it runs in a container?

**Comment by Evengard** [comment] 2023-03-02 20:20
Seems like so. I've run the same command on the same host system on which I run the (kubernetes with k3s) containers with the same projects, in containers it rarely doesn't hang but most of the times still hang, on the host system seems to be fine.

**Comment by tmds** [comment] 2023-03-03 18:20
I'm going to close this issue, as it was about standard out being kept open by grand children, and that causing `WaitForExit` not to return.

As I mentioned in https://github.com/dotnet/runtime/issues/29232#issuecomment-1451584094, that is the expected behavior.
And, if the grand child is not supposed to keep standard output open, then the child is responsible for redirecting standard output when it starts the grand child.

@Evengard if you have an issue with `WaitForExit` hanging, that occurs only in containers, and reproduces with .NET 7.0.3+, then create a new issue and include some information on how to reproduce the problem.

**Closed by tmds** 2023-03-03 18:20 UTC
Labels: area-System.Diagnostics.Process
