### ISSUE TITLE
System.MissingMethodException : Constructor on type 'System.Text.Json.Serialization.NullableConverter[...]' not found

### ISSUE THREAD

**Issue by MartinZikmund** [dotnet/runtime#47976] opened 2021-02-07 09:19 UTC
### Description

I have a very similar issue to #37047.

My class has the following property:

```
[JsonInclude]
public StringEnum<SiteType>? Type { get; internal set; }
```

Where `StringEnum<T>` is a `struct`. I have defined a custom generic `JsonConverterFactory` for this type:

```
public class StringEnumConverterFactory : JsonConverterFactory
{
    public override bool CanConvert(Type typeToConvert)
    {
        if (!typeToConvert.IsGenericType)
        {
            return false;
        }

        var type = typeToConvert;

        if (!type.IsGenericTypeDefinition)
        {
            type = type.GetGenericTypeDefinition();
        }

        return type == typeof(StringEnum<>);
    }

    public override JsonConverter CreateConverter(
        Type typeToConvert,
        JsonSerializerOptions options)
    {
        var keyType = typeToConvert.GenericTypeArguments[0];
        var converterType = typeof(StringEnumConverter<>).MakeGenericType(keyType);

        return (JsonConverter)Activator.CreateInstance(converterType);
    }
}
```

This is registered in the options:

```
public static JsonSerializerOptions SerializerOptions = new JsonSerializerOptions()
{
    PropertyNamingPolicy = new JsonSnakeCaseNamingPolicy(),
    Converters =
    {
        new DateTimeOffsetConverter(),
        new StringEnumConverterFactory(),
    } 
};
```

However, deserializing a `null` value fails with the following exception:

```
System.MissingMethodException: 'Constructor on type 'System.Text.Json.Serialization.Converters.NullableConverter`1[[StackExchangeApi.Serialization.StringEnum`1[[MyApi.Enums.SiteState, MyApi, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null]], MyApi, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null]]' not found.'
```

### Configuration

.NET Standard 2.0, with System.Text.Json 5.0.1

### Regression?

No.

### Other information

Stack trace:

```
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Text.Json.Serialization.Converters.NullableConverterFactory.CreateValueConverter(Type valueTypeToConvert, JsonConverter valueConverter)
   at System.Text.Json.Serialization.Converters.NullableConverterFactory.CreateConverter(Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverterFactory.GetConverterInternal(Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetConverter(Type typeToConvert)
   at System.Text.Json.JsonSerializerOptions.DetermineConverter(Type parentClassType, Type runtimePropertyType, MemberInfo memberInfo)
   at System.Text.Json.JsonClassInfo.GetConverter(Type type, Type parentClassType, MemberInfo memberInfo, Type& runtimeType, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo.AddProperty(MemberInfo memberInfo, Type memberType, Type parentClassType, Nullable`1 parentTypeNumberHandling, JsonSerializerOptions options)
   at System.Text.Json.JsonClassInfo.CacheMember(Type declaringType, Type memberType, MemberInfo memberInfo, Nullable`1 typeNumberHandling, Dictionary`2 cache, Dictionary`2& ignoredMembers)
   at System.Text.Json.JsonClassInfo..ctor(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetOrAddClass(Type type)
   at System.Text.Json.JsonClassInfo.get_ElementClassInfo()
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
```

**Comment by eiriktsarpalis** [comment] 2021-07-23 17:50
Hi @MartinZikmund, I think your reproduction is missing a few components. Could you please share a standalone reproduction that also contains the implementations of `StringEnumConverter<T>`, `StringEnum<T>` and `CustomClass<T>`?

**Comment by romfir** [comment] 2021-07-27 11:14
It can also be reproduced with following classes:
```csharp
public class EnumCollectionConverter<TEnum> : JsonConverter<IEnumerable<TEnum>>
where TEnum : struct, Enum
{
    public override IEnumerable<TEnum>? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        => JsonSerializer.Deserialize<IEnumerable<TEnum>>(ref reader, options);

    public override void Write(Utf8JsonWriter writer, IEnumerable<TEnum> value, JsonSerializerOptions options)
        => JsonSerializer.Serialize(writer, value.Select(e => e.ToString()), options);
}
```

```csharp
public class EnumConverter<TEnum> : JsonConverter<TEnum?>
where TEnum : struct, Enum
{
    public override TEnum? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        => (TEnum?)JsonSerializer.Deserialize(ref reader, typeToConvert, options);

    public override void Write(Utf8JsonWriter writer, TEnum? value, JsonSerializerOptions options)
        => JsonSerializer.Serialize(writer, value?.ToString(), options);
}
```

```csharp
public class EnumConverterFactory : JsonConverterFactory
{
    public override bool CanConvert(Type typeToConvert)
    {
        if (typeToConvert.IsEnum)
        {
            return true;
        }

        if (typeToConvert.IsAssignableTo(typeof(IEnumerable)) && typeToConvert.IsConstructedGenericType)
        {
            return typeToConvert.GetGenericArguments()[0].IsAssignableTo(typeof(Enum));
        }

        return false;
    }

    public override JsonConverter CreateConverter(Type typeToConvert, JsonSerializerOptions options)
    {
        if (typeToConvert.IsEnum)
        {
            return (JsonConverter)Activator.CreateInstance(
                typeof(EnumConverter<>).MakeGenericType(typeToConvert),
                BindingFlags.Instance | BindingFlags.Public,
                null,
                null,
                null)!;
        }

        Type type = typeToConvert.GetGenericArguments()[0];

        return (JsonConverter)Activator.CreateInstance(
            typeof(EnumCollectionConverter<>).MakeGenericType(type),
            BindingFlags.Instance | BindingFlags.Public,
            null,
            null,
            null)!;

    }
}
```
while trying to deserialize/serialize this class:
```csharp
private enum MyEnum
{
    Test = 1,
    Test2 = 2
}

private class Test2
{
    [JsonConverter(typeof(EnumConverterFactory))]
    public MyEnum? SingleEnum { get; set; }

    [JsonConverter(typeof(EnumConverterFactory))]
    public IEnumerable<MyEnum>? Enums { get; set; }
}
```

**Comment by steveharter** [comment] 2021-08-09 15:02
@MartinZikmund I assume the reason for the custom converters was because `null` can be used and it was not working by default. However, `null` is supported automatically for value types when wrapped by `Nullable<T>`. I think the problem is your `Test2` class has incorrect nullability on the `Enums` property. It should be:
```diff
class Test2
{
-    [JsonConverter(typeof(EnumConverterFactory))]
    public MyEnum? SingleEnum { get; set; }

-    [JsonConverter(typeof(EnumConverterFactory))]
-    public IEnumerable<MyEnum>? Enums { get; set; }
+    public IEnumerable<MyEnum?>? Enums { get; set; } // Any element can be null, or the whole collection
}
```

and no custom converters are necessary.

**Comment by steveharter** [comment] 2021-08-09 15:02
Closing for now; please re-open if this is not correct.

**Closed by steveharter** 2021-08-09 15:02 UTC
Labels: area-System.Text.Json, needs more info, untriaged
