### ISSUE TITLE
JIT.HardwareIntrinsics tests failed with "almost" empty logs

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/runtime#67233] opened 2022-03-28 14:36 UTC
`JIT.HardwareIntrinsics.Arm.Crc32` and `JIT.HardwareIntrinsics.X86.Sse2 ` have failed for [this](https://dev.azure.com/dnceng/public/_build/results?buildId=1685168&view=logs&j=bb94f37e-a09b-5b51-09b2-ab78e7aa5103&t=506cadc9-3cc4-5d96-6847-011f75a33382&l=184) pipeline, they both provide links to console logs which contain only **a single line**:

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-108c6ed12aef4e8d84/JIT.HardwareIntrinsics.Arm.Crc32/1/console.87d4973c.log?sv=2019-07-07&se=2022-04-17T09%3A20%3A36Z&sr=c&sp=rl&sig=VyiT0%2Fq697ZHObIYcCj%2BU2QGtxfuT6eP79nyPTBMFeA%3D

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-ea1ae4eb158e4f41b2/JIT.HardwareIntrinsics.X86.Sse2/1/console.792b959f.log?sv=2019-07-07&se=2022-04-17T09%3A20%3A36Z&sr=c&sp=rl&sig=3itD6dlpKp1b0Ikj2cJL%2FCCYy1PsSv2YwEw0%2F2szuUw%3D

![image](https://user-images.githubusercontent.com/6011991/160422221-e8b63466-37a1-48e7-860f-b28c79473441.png)

**Comment by tannergooding** [comment] 2022-03-28 18:05
@joperezr, there isn't really anything actionable here from the area owners.

This is an infrastructure issue and likely needs someone who has in depth/knowledge understanding of our CI setup and AzDO to diagnose and resolve.

**Comment by joperezr** [comment] 2022-03-28 18:55
@tannergooding you are correct, apologies. In fact, this seems to be a dupe of an already opened core-eng issue. Sorry for the noise.

**Comment by tannergooding** [comment] 2022-04-06 17:16
Noting the tests in question are supposed to be excluded on Arm64: https://github.com/dotnet/runtime/blob/main/src/tests/issues.targets#L249-L252

**Comment by danmoseley** [comment] 2022-04-22 00:34
I spent some time with the query below but found no evidence of recent failures with no output like this. There are periodic bad exits for these tests, mostly in GC stress but no common pattern. Hard to action messages like "END: coreclr_initialize failed - Error: 0x80004005". If such issues are a problem, we should open an issue with their distinctive output.

Execute: [Web](https://dataexplorer.azure.com/clusters/https%3a%2f%2fengsrvprod.kusto.windows.net/databases/engineeringdata?query=H4sIAAAAAAAEAI2SQUvDQBCF74X%2bhyWnFEqQFsRLBVstpgepRmlBRNbs2E5MdsLMxlrwx5tkq60X7Wlmd9%2f7dvaxC%2bK32EEh3c6n2qyBQU0ZwZp8e6MLUKORCmbxfXSt2Ww0Q2wdoxVMJbrgIppwOhwEivi36y%2fb8uw0SgQGwf5GdVtBBUadK72icHhievuzxGlXSQsca3P1ga41ZoRWzehFFLU1Ns1uyZRB6rqdb2S%2faQ9H66sGMSFTdx7dSiZkhXJ4YGyX87UW8O9XjqSZfRWWmgWeMyEbzplKYIcgvccg2UodYPTjCZ56HoIl5GiPYESX8IoWHZJtAN5%2bV1mHBUxz%2fV7H%2bz%2bDD%2fUeMa4wN7E5wrxTelsbnQ8roYrTui523yQ2X16WeksxAgAA) | [Desktop](https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAEAI2SQUvDQBCF74X%2bhyWnFEqQFsRLBVstpgepRmlBRNbs2E5MdsLMxlrwx5tkq60X7Wlmd9%2f7dvaxC%2bK32EEh3c6n2qyBQU0ZwZp8e6MLUKORCmbxfXSt2Ww0Q2wdoxVMJbrgIppwOhwEivi36y%2fb8uw0SgQGwf5GdVtBBUadK72icHhievuzxGlXSQsca3P1ga41ZoRWzehFFLU1Ns1uyZRB6rqdb2S%2faQ9H66sGMSFTdx7dSiZkhXJ4YGyX87UW8O9XjqSZfRWWmgWeMyEbzplKYIcgvccg2UodYPTjCZ56HoIl5GiPYESX8IoWHZJtAN5%2bV1mHBUxz%2fV7H%2bz%2bDD%2fUeMa4wN7E5wrxTelsbnQ8roYrTui523yQ2X16WeksxAgAA&web=0) | [Web (Lens)](https://lens.msftcloudes.com/v2/#/discover/query//results?datasource=(cluster:engsrvprod.kusto.windows.net,database:engineeringdata,type:Kusto)&query=H4sIAAAAAAAEAI2SQUvDQBCF74X%2bhyWnFEqQFsRLBVstpgepRmlBRNbs2E5MdsLMxlrwx5tkq60X7Wlmd9%2f7dvaxC%2bK32EEh3c6n2qyBQU0ZwZp8e6MLUKORCmbxfXSt2Ww0Q2wdoxVMJbrgIppwOhwEivi36y%2fb8uw0SgQGwf5GdVtBBUadK72icHhievuzxGlXSQsca3P1ga41ZoRWzehFFLU1Ns1uyZRB6rqdb2S%2faQ9H66sGMSFTdx7dSiZkhXJ4YGyX87UW8O9XjqSZfRWWmgWeMyEbzplKYIcgvccg2UodYPTjCZ56HoIl5GiPYESX8IoWHZJtAN5%2bV1mHBUxz%2fV7H%2bz%2bDD%2fUeMa4wN7E5wrxTelsbnQ8roYrTui523yQ2X16WeksxAgAA&runquery=1) | [Desktop (SAW)](https://engsrvprod.kusto.windows.net/engineeringdata?query=H4sIAAAAAAAEAI2SQUvDQBCF74X%2bhyWnFEqQFsRLBVstpgepRmlBRNbs2E5MdsLMxlrwx5tkq60X7Wlmd9%2f7dvaxC%2bK32EEh3c6n2qyBQU0ZwZp8e6MLUKORCmbxfXSt2Ww0Q2wdoxVMJbrgIppwOhwEivi36y%2fb8uw0SgQGwf5GdVtBBUadK72icHhievuzxGlXSQsca3P1ga41ZoRWzehFFLU1Ns1uyZRB6rqdb2S%2faQ9H66sGMSFTdx7dSiZkhXJ4YGyX87UW8O9XjqSZfRWWmgWeMyEbzplKYIcgvccg2UodYPTjCZ56HoIl5GiPYESX8IoWHZJtAN5%2bV1mHBUxz%2fV7H%2bz%2bDD%2fUeMa4wN7E5wrxTelsbnQ8roYrTui523yQ2X16WeksxAgAA&saw=1)

https://engsrvprod.kusto.windows.net/engineeringdata

```kusto
WorkItems
| where FriendlyName == "JIT.HardwareIntrinsics.Arm.Crc32" or FriendlyName  == "JIT.HardwareIntrinsics.X86.Sse2"
| where  Queued > ago(30d)
| where Status == "BadExit"
| join Jobs on JobId
| project
  Queued,
  FriendlyName, ExitCode, Status,
  ConsoleUri,
  PhaseName = tostring(parse_json(Properties)["System.PhaseName"]),
  Pipeline = tostring(parse_json(Properties).DefinitionName),
  RuntimeFlavor = tostring(parse_json(Properties).runtimeFlavor),
  BuildId = tostring(parse_json(Properties).BuildId),
  QueueName, Source, WorkItemId
```

**Closed by danmoseley** 2022-04-22 00:34 UTC
Labels: blocking-clean-ci, area-Infrastructure, untriaged
