### ISSUE TITLE
new GCMemoryInfo().Index throws NullReferenceException

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/runtime#45415] opened 2020-12-01 15:40 UTC
### Description

This program throws NullReferenceException:

```C#
using System;

class Program
{
    static void Main()
    {
        Console.WriteLine(new GCMemoryInfo().Index);
    }
}
```

I would expect it to write 0 instead. No exceptions are documented for the [GCMemoryInfo.Index](https://docs.microsoft.com/en-us/dotnet/api/system.gcmemoryinfo.index?view=net-5.0#System_GCMemoryInfo_Index) property.

### Configuration

.NET 5.0 on Windows 10 20H2 x64. I guess the exception would occur with all CoreCLR configurations; not sure about Mono.

### Regression?

No, System.GCMemoryInfo is a new API in .NET 5.0.

### Other information

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.GCMemoryInfo.get_Index()
   at Program.Main() in C:\redacted\Program.cs:line 7
```

.NET Blog: [The updated GetGCMemoryInfo API in .NET 5.0 and how it can help you](https://devblogs.microsoft.com/dotnet/the-updated-getgcmemoryinfo-api-in-net-5-0-and-how-it-can-help-you/)

<https://github.com/dotnet/runtime/issues/34648#issuecomment-627541970> suggested using `public long PinnedHandlesCount => _info?.PinnedHandlesCount ?? 0;` etc. but the properties were implemented in <https://github.com/dotnet/runtime/pull/37879> without the null coalescing. <https://github.com/dotnet/runtime/blob/cf258a14b70ad9069470a108f13765e0e5988f51/src/libraries/System.Private.CoreLib/src/System/GCMemoryInfo.cs#L150>

Code like `new GCMemoryInfo().Index` seems unlikely to be part of real programs, but a program could have a `GCMemoryInfo` field in some class and try to read its properties before initializing it. The developer of such a program could avoid the problem by changing such fields to `Nullable<GCMemoryInfo>` and then checking for null.

**Comment by KalleOlaviNiemitalo** [comment] 2020-12-01 15:41
I think this should have **area-GC-coreclr** like  <https://github.com/dotnet/runtime/issues/34648>, rather than **area-System.Reflection**.

**Comment by Maoni0** [comment] 2020-12-01 20:31
personally I would never use it that way 'cause you are asking for something that you don't have any info for. but I'll defer that to API folks to see if this is valid usage. @stephentoub, @GrabYourPitchforks, could you please comment?

**Comment by Maoni0** [comment] 2020-12-01 20:33
BTW Index 0 means no GC has happened so we should not return 0 in this case.

**Comment by GrabYourPitchforks** [comment] 2020-12-01 20:38
IMO that's fine. It's an uninitialized value type where we don't guarantee that _default(T)_ is meaningful. Some other value types also throw NRE in this situation.

```cs
var e = new List<string>.Enumerator();
e.MoveNext(); // NullReferenceException
```

**Comment by ivdiazsa** [comment] 2020-12-10 01:46
This `NullReferenceException` seems to be by design, as other API's also throw under certain cases like the `Enumerator` example mentioned above. Closing this issue for now. We can reopen if further investigation is required.

**Closed by ivdiazsa** 2020-12-10 01:46 UTC
Labels: area-GC-coreclr

**Comment by GSPP** [comment] 2020-12-20 11:50
`NullReferenceException` is one of those exception types that should almost never be thrown. I can see that `List<T>.Enumerator` might do it because fixing that is a performance issue. Here, there does not seem to be a strong reason to allow this "forbidden" exception type.

.NET is so nice in part because it is so reliable and errors are meaningful. I hope it would not become standard policy to allow forbidden exception types to occur.

**Comment by GrabYourPitchforks** [comment] 2020-12-20 21:44
If there's concern about the usability of this particular type then we could have an analyzer that says "don't call new()", just like we did with Guid. But ultimately this isn't the type of thing that causes applications grief in practice, since it's immediately apparent the very first time you run the program that something went wrong. If this were instead something that only happened every 10,000th web request and it were difficult to track down, I think that would raise the urgency.
