### ISSUE TITLE
JsonNode property names are not renamed according to JsonNamingPolicy

### ISSUE THREAD

**Issue by Nefcanto** [dotnet/runtime#101068] opened 2024-04-02 12:23 UTC
Edit: Reduced repro is [below](https://github.com/dotnet/runtime/issues/101068#issuecomment-2057366958).

When a JsonNode with PascalCase property names is serialized, those property names are not renamed to reflect JsonNamingPolicy.CamelCase.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have created a custom JSON converter for my ASP.NET Core application. This is the code:

```
    public override void Write(Utf8JsonWriter writer, object value, JsonSerializerOptions options)
    {
        var stopwatch = new Stopwatch();
        stopwatch.Start();
        var jsonString = JsonSerializer.Serialize(value);
        var node = JsonNode.Parse(jsonString);
        FlattenRelatedItems(node);
        node.WriteTo(writer, JsonHelper.Options);
        stopwatch.Stop();
    }

    public static void FlattenRelatedItems(JsonNode node)
    {
        if (node is JsonArray jsonArray)
        {
            foreach (var item in jsonArray)
            {
                FlattenRelatedItems(item);
            }
        }
        else if (node is JsonObject jsonObject)
        {
            if (jsonObject.ContainsKey("RelatedItems"))
            {
                jsonObject.TryGetPropertyValue("RelatedItems", out JsonNode relatedItems);
                foreach (var property in relatedItems.AsObject())
                {
                    var valueJson = property.Value.ToString();
                    if (property.Value.GetValueKind() == JsonValueKind.String)
                    {
                        valueJson = $"\"{valueJson}\"";
                    }
                    var value = JsonSerializer.Deserialize<JsonNode>(valueJson);
                    if (jsonObject.ContainsKey(property.Key))
                    {
                        Logger.LogWarning(property.ToString());
                    }
                    else
                    {
                        jsonObject.Add(property.Key, value);
                    }
                }
                jsonObject.Remove("RelatedItems");

            }
            foreach (var property in jsonObject)
            {
                FlattenRelatedItems(property.Value);
            }
        }
    }
```

And this is my `JsonHelper` class:

```
namespace Infra;

public static class JsonHelper
{
    private static object lockToken = new Object();

    public static void ConfigureJsonSerializerOptions(JsonSerializerOptions options)
    {
        options.PropertyNameCaseInsensitive = true;
        options.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
        options.DictionaryKeyPolicy = JsonNamingPolicy.CamelCase;
        options.Encoder = JavaScriptEncoder.Create(UnicodeRanges.All);
        options.NumberHandling = JsonNumberHandling.AllowReadingFromString;
        options.ReadCommentHandling = JsonCommentHandling.Skip;
        options.UnknownTypeHandling = JsonUnknownTypeHandling.JsonNode;
        options.DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull;
        options.AllowTrailingCommas = true;
        options.WriteIndented = true;
        if (!options.Converters.Any(c => c.GetType() == typeof(RelatedItemsFlattenerJsonConverter)))
        {
            if (InfraConfig.GetBooleanSetting("FlattenRelatedItems"))
            {
                options.Converters.Add(new RelatedItemsFlattenerJsonConverter());
            }
        }
        if (!options.Converters.Any(c => c.GetType() == typeof(JsonStringEnumConverter)))
        {
            options.Converters.Add(new JsonStringEnumConverter());
        }
    }

    private static JsonSerializerOptions options;

    public static JsonSerializerOptions Options
    {
        get
        {
            if (options == null)
            {
                lock (lockToken)
                {
                    options = new JsonSerializerOptions();
                    ConfigureJsonSerializerOptions(options);
                }
            }
            return options;
        }
    }

    public static JsonElement? Get(this JsonElement element, string name) =>
        element.ValueKind != JsonValueKind.Null && element.ValueKind != JsonValueKind.Undefined && element.TryGetProperty(name, out var value)
            ? value : (JsonElement?)null;

    public static JsonElement? Get(this JsonElement element, int index)
    {
        if (element.ValueKind == JsonValueKind.Null || element.ValueKind == JsonValueKind.Undefined)
            return null;
        var value = element.EnumerateArray().ElementAtOrDefault(index);
        return value.ValueKind != JsonValueKind.Undefined ? value : (JsonElement?)null;
    }
}
```

But the output JSON does not respect the options passed to it.

### Expected Behavior

The `Utf8JsonWriter` and `JsonNode` should respect the options passed to them.

### Steps To Reproduce

1. Create a custom converter
2. Create custom options (for example, `DictionaryKeyPolicy`)
3. Register that converter
4. Run through the converter

### .NET Version

8.0.201

### Anything else?

.NET SDK:
 Version:           8.0.201
 Commit:            4c2d78f037
 Workload version:  8.0.200-manifests.3097af8b

Runtime Environment:
 OS Name:     debian
 OS Version:  12
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.201/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.2
  Architecture: x64
  Commit:       1381d5ebd2

.NET SDKs installed:
  8.0.201 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by eiriktsarpalis** [comment] 2024-04-15 16:56
@amcasey is correct to point out that `PropertyNamingPolicy` is a `JsonSerializer` feature that is not in scope for `JsonNode` which simply defines a JSON DOM.  Duplicate of https://github.com/dotnet/runtime/issues/66661

**Closed by eiriktsarpalis** 2024-04-15 16:56 UTC
Labels: area-System.Text.Json, untriaged

**Comment by Nefcanto** [comment] 2024-04-15 17:40
@eiriktsarpalis, thank you for the explanation and linking to another issue. I understood. JsonNode represents JSON precisely as it is by design. But what should I do now? I need a custom mapper to change the JSON my API returns. And I want to keep those policies. Any guidance for this part?

**Comment by amcasey** [comment] 2024-04-15 17:57
@Nefcanto As I mentioned above, you can pass your serialization options when you create the json string that you eventually parse into a JsonNode.  Then the JsonNode will have the camelCase names.  You'll need to update `FlattenRelatedItems` to use the new names.

**Comment by Nefcanto** [comment] 2024-04-16 04:49
@amcasey, I updated my code as you mentioned:

```
    public override void Write(Utf8JsonWriter writer, object value, JsonSerializerOptions options)
    {
        var stopwatch = new Stopwatch();
        stopwatch.Start();
        var jsonString = JsonSerializer.Serialize(value, JsonHelper.Options);
        var node = JsonNode.Parse(jsonString);
        FlattenRelatedItems(node);
        node.WriteTo(writer);
        stopwatch.Stop();
    }
```

But now I get this recursive error:

```
   at System.Text.Json.Serialization.JsonConverter`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].WriteCore(System.Text.Json.Utf8JsonWriter, System.__Canon ByRef, System.Text.Json.JsonSerializerOptions, System.Text.Json.WriteStack ByRef)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Serialize(System.Text.Json.Utf8JsonWriter, System.__Canon ByRef, System.Object)
   at System.Text.Json.JsonSerializer.WriteString[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef, System.Text.Json.Serialization.Metadata.JsonTypeInfo`1<System.__Canon>)
   at System.Text.Json.JsonSerializer.Serialize[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon, System.Text.Json.JsonSerializerOptions)
   at Infra.RelatedItemsFlattenerJsonConverter.Write(System.Text.Json.Utf8JsonWriter, System.Object, System.Text.Json.JsonSerializerOptions)
   at System.Text.Json.Serialization.JsonConverter`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryWrite(System.Text.Json.Utf8JsonWriter, System.__Canon ByRef, System.Text.Json.JsonSerializerOptions, System.Text.Json.WriteStack ByRef)
   at System.Text.Json.Serialization.JsonConverter`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].WriteCore(System.Text.Json.Utf8JsonWriter, System.__Canon ByRef, System.Text.Json.JsonSerializerOptions, System.Text.Json.WriteStack ByRef)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Serialize(System.Text.Json.Utf8JsonWriter, System.__Canon ByRef, System.Object)
   at System.Text.Json.JsonSerializer.WriteString[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef, System.Text.Json.Serialization.Metadata.JsonTypeInfo`1<System.__Canon>)
   at System.Text.Json.JsonSerializer.Serialize[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon, System.Text.Json.JsonSerializerOptions)
   at Infra.RelatedItemsFlattenerJsonConverter.Write(System.Text.Json.Utf8JsonWriter, System.Object, System.Text.Json.JsonSerializerOptions)
   at System.Text.Json.Serialization.JsonConverter`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryWrite(System.Text.Json.Utf8JsonWriter, System.__Canon ByRef, System.Text.Json.JsonSerializerOptions, System.Text.Json.WriteStack ByRef)
```

And It's so much that I can't even see the first lines in the terminal.

Is that code correct?

It seems to me that by calling `JsonSerializer.Serialize(value, JsonHelper.Options);` we enter a recursion in which `JsonSerializer` wants to serialize the given JSON, yet it is configured to use `RelatedItemsFlattenerJsonConverter`, then in the `Write` method we're using `JsonSerializer` and it goes into a loop. So what is the solution here?

**Comment by eiriktsarpalis** [comment] 2024-04-16 10:49
@Nefcanto have you tried using one of the `JsonSerializer.SerializeToNode` methods?

**Comment by amcasey** [comment] 2024-04-17 21:30
@Nefcanto my best guess would be that you need to make a copy of your options without
```csharp
        if (!options.Converters.Any(c => c.GetType() == typeof(RelatedItemsFlattenerJsonConverter)))
        {
            if (InfraConfig.GetBooleanSetting("FlattenRelatedItems"))
            {
                options.Converters.Add(new RelatedItemsFlattenerJsonConverter());
            }
        }
```
But I'd investigate Eirik's suggestion first.
