### ISSUE TITLE
`MSB4018: The "GenerateDepsFile" task failed unexpectedly.` in recently daily builds&lt;- Could not load file or assembly "System.Threading.Tasks.Extensions, Version = 4.2.0.0"

### ISSUE THREAD

**Issue by wli3** [dotnet/runtime#36350] opened 2020-05-13 15:40 UTC
@yyjdelete commented on [Mon Apr 27 2020](https://github.com/dotnet/sdk/issues/11460)

That error happens when try to use recently daily builds of dotnet-sdk 5.0.* with msbuild.exe(net472) from VS2019 16.6 preview4(msbuild 16.6.0-preview-20208-15+2f58c1427)
Not working version of dotnet-sdk: 5.0.100-preview.5.20227.13/ 5.0.100-preview.4.20227.14(both daily builds from https://github.com/dotnet/installer/blob/master/README.md#installers-and-binaries)
Last working version: 5.0.100-preview.3.20216.6(release from https://dotnet.microsoft.com/download/dotnet/5.0)

```cs
error MSB4018: The "GenerateDepsFile" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load file or assembly "System.Threading.Tasks.Extensions, Version = 4.2.0.0, Culture = neutral, PublicKeyToken = cc7b13ffcd2ddd51" or one of its dependencies. The system can not find the file specified.
File name: "System.Threading.Tasks.Extensions, Version = 4.2.0.0, Culture = neutral, PublicKeyToken = cc7b13ffcd2ddd51"
    at Microsoft.Extensions.DependencyModel.DependencyContextWriter.Write (DependencyContext context, Stream stream)
    at Microsoft.NET.Build.Tasks.GenerateDepsFile.WriteDepsFile (String depsFilePath)
    at Microsoft.NET.Build.Tasks.GenerateDepsFile.ExecuteCore ()
    at Microsoft.NET.Build.Tasks.TaskBase.Execute ()
    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute ()
    at Microsoft.Build.BackEnd.TaskBuilder. <ExecuteInstantiatedTask> d__26.MoveNext ()
```

#### Step
1. dotnet new console;
2. dotnet clean;
3. dotnet restore;
4. "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\MSBuild.exe"

If you run step 4 again without clean, the error is not shown, but still lead to an broken `xxx.deps.json`. And you can see the same error when build in VS.

---

@wli3 commented on [Wed May 13 2020](https://github.com/dotnet/sdk/issues/11460#issuecomment-628073871)

`DependencyContextWriter` should have retry

**Comment by yyjdelete** [comment] 2020-05-19 15:35
This no longer happen for me with dotnet-sdk `5.0.100-preview.4.20258.7`/(***latest daily builds***)`5.0.100-preview.6.20269.4` and vs2019 `16.6 preview6.0`.

**Comment by yyjdelete** [comment] 2020-05-20 04:43
Finally, I know what is wrong for my computer.

For any one who hit the same issue, simply uninstall Npgsql from GAC(and use nuget instead) may works, or try too see if there is something in `C:\Windows\Microsoft.NET\assembly\GAC_MSIL\Microsoft.Bcl.AsyncInterfaces\v4.0_1.0.0.0__cc7b13ffcd2ddd51` but `C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Threading.Tasks.Extensions\v4.0_4.2.0.0__cc7b13ffcd2ddd51` is not exists.

(TL;DR)
`Npgsql4.13.msi` will add itself and it's dependencies `Microsoft.Bcl.AsyncInterfaces 1.0.0` and `System.Threading.Tasks.Extensions 4.2.0.1` into GAC.
But AsyncInterfaces 1.0.0 depend on `System.Threading.Tasks.Extensions 4.2.0.0` by default. And according to FusionLog, when msbuild.exe(net472) try to load `Microsoft.Bcl.AsyncInterfaces 1.0.0` which is required by `System.Text.Json 5.0.0`, it found and load the one in GAC first instead of dotnet-sdk, and switch from `LoadFrom` context to `default` context(I don't know what it means), and then it try to load `System.Threading.Tasks.Extensions 4.2.0.0` from GAC instead of dotnet-sdk(C:\Program Files\dotnet\sdk\5.0.100-preview.4.20258.7\Sdks\Microsoft.NET.Sdk\tools\net472), but it failed since there is only  `System.Threading.Tasks.Extensions 4.2.0.1` exists in GAC, and never look `System.Threading.Tasks.Extensions 4.2.0.0` inside dotnet-sdk.

I don't know if this will also happen for other program and other assembly used by Npgsql in GAC.

@roji Since you are both member of npgsql and dotnet team. Any idea for that? Should I open an new issue on https://github.com/npgsql/npgsql instead?

**Comment by roji** [comment] 2020-05-21 19:26
Cross-posted as https://github.com/npgsql/npgsql/issues/2971, and likely a duplicate of https://github.com/npgsql/npgsql/issues/2677.

**Comment by tarekgh** [comment] 2020-07-06 18:23
CC @ericstj @joperezr any suggestion where this issue go to?

**Comment by joperezr** [comment] 2020-07-06 22:35
Honestly I don't think that there is a clear action item from our side in here and looks like the issue is mostly with the npgsql installer from what I read above (please correct me if I'm wrong) therefore if it is already logged there I would probably close this.

**Comment by tarekgh** [comment] 2020-07-06 22:37
closing per @joperezr comment. feel free to send any comment or question.

**Closed by tarekgh** 2020-07-06 22:37 UTC
Labels: area-Meta, untriaged
