### ISSUE TITLE
Investigate perf improvements for the built-in JsonNamingPolicy (SnakeCase) for DictionaryKeyPolicy

### ISSUE THREAD

**Issue by ahsonkhan** [dotnet/runtime#31486] opened 2019-11-13 20:29 UTC
One option to reduce the allocations could be to use `ValueStringBuilder` (see https://github.com/dotnet/corefx/pull/41354#discussion_r339179870), though that doesn't help the throughput too much. It might be possible to re-implement the algorithm in `ConvertName` to be faster. Another idea might be to special case the first character to simplify some of the conditions within the loop (like `currentIndex > 0`).

``` ini

BenchmarkDotNet=v0.11.5.1159-nightly, OS=Windows 10.0.18362
Intel Core i7-6700 CPU 3.40GHz (Skylake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.1.100-preview1-014459
  [Host]     : .NET Core 3.0.0 (CoreCLR 4.700.19.46205, CoreFX 4.700.19.46214), X64 RyuJIT
  Job-HPZZRZ : .NET Core 3.0.0 (CoreCLR 4.700.19.46205, CoreFX 4.700.19.46214), X64 RyuJIT

PowerPlanMode=00000000-0000-0000-0000-000000000000  IterationTime=250.0000 ms  MaxIterationCount=10  
MinIterationCount=5  WarmupCount=1  

```
|  Method |     Mean |     Error |    StdDev |   Median |      Min |      Max | Ratio | RatioSD |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|-------- |---------:|----------:|----------:|---------:|---------:|---------:|------:|--------:|-------:|------:|------:|----------:|
| Default | 2.426 us | 0.0473 us | 0.0281 us | 2.425 us | 2.391 us | 2.473 us |  1.00 |    0.00 | 0.1567 |     - |     - |     656 B |
|   Camel | 3.040 us | 0.0895 us | 0.0592 us | 3.027 us | 2.979 us | 3.150 us |  1.26 |    0.04 | 0.2491 |     - |     - |    1048 B |
|   Snake | 4.293 us | 0.0939 us | 0.0621 us | 4.280 us | 4.195 us | 4.397 us |  1.77 |    0.01 | 0.5624 |     - |     - |    2432 B |

```C#
public class SerializeDictionaryWithNamingPolicy
{
    JsonSerializerOptions _camelOptions;
    JsonSerializerOptions _snakeOptions;

    Dictionary<string, string> _foo;

    [GlobalSetup]
    public void Setup()
    {
        _camelOptions = new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase, DictionaryKeyPolicy = JsonNamingPolicy.CamelCase };
        _snakeOptions = new JsonSerializerOptions { PropertyNamingPolicy = new JsonSnakeCaseNamingPolicy(), DictionaryKeyPolicy = new JsonSnakeCaseNamingPolicy() };

        _foo = new Dictionary<string, string>()
        {
            ["ID"] = "A",
            ["url"] = "A",
            ["URL"] = "A",
            ["THIS IS SPARTA"] = "A",
            ["IsCIA"] = "A",
            ["iPhone"] = "A",
            ["IPhone"] = "A",
            ["xml2json"] = "A",
            ["already_snake_case"] = "A",
            ["IsJSONProperty"] = "A",
            ["ABCDEFGHIJKLMNOP"] = "A",
            ["Hi!! This is text.Time to test."] = "A",
        };
    }

    [BenchmarkCategory(Categories.CoreFX, Categories.JSON)]
    [Benchmark(Baseline = true)]
    public string Default()
    {
        return JsonSerializer.Serialize(_foo);
    }

    [BenchmarkCategory(Categories.CoreFX, Categories.JSON)]
    [Benchmark]
    public string Camel()
    {
        return JsonSerializer.Serialize(_foo, _camelOptions);
    }

    [BenchmarkCategory(Categories.CoreFX, Categories.JSON)]
    [Benchmark]
    public string Snake()
    {
        return JsonSerializer.Serialize(_foo, _snakeOptions);
    }
}
```

**Comment by iSazonov** [comment] 2020-06-26 13:35
I wonder - https://github.com/dotnet/corefx/pull/41354 is not merged (Although a lot of effort has been spent there
!) but the issue is a open :-)

**Closed** 2021-11-05 01:02 UTC
Labels: area-System.Text.Json, tenet-performance, up-for-grabs, no recent activity
