### ISSUE TITLE
[Perf -14%] System.Reflection.Attributes.GetCustomAttributesClassHit (2)

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#44816] opened 2020-11-17 18:34 UTC
### Run Information

Architecture | x64
-- | --
OS | ubuntu 18.04
Baseline | [fcce1608222d542eea0b419bcee3c62775c1c418](https://github.com/dotnet/runtime/commit/fcce1608222d542eea0b419bcee3c62775c1c418)
Compare | [52d405e92db4eaaf7f3c52ac615d9cd4f5341315](https://github.com/dotnet/runtime/commit/52d405e92db4eaaf7f3c52ac615d9cd4f5341315)
Diff | [Diff](https://www.github.com/dotnet/runtime/compare/fcce1608222d542eea0b419bcee3c62775c1c418...52d405e92db4eaaf7f3c52ac615d9cd4f5341315)

### Regressions in System.Reflection.Attributes

Benchmark | Baseline | Test | Test/Base | Baseline IR | Compare IR | IR Ratio | Baseline ETL | Compare ETL
-- | -- | -- | -- | -- | -- | -- | -- | --
[GetCustomAttributesMethodBaseHit](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04/System.Reflection.Attributes.GetCustomAttributesMethodBaseHit.html>) | 945.36 ns | 1.15 μs | 1.21 | | |
[GetCustomAttributesClassHit](<https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/master_x64_ubuntu 18.04/System.Reflection.Attributes.GetCustomAttributesClassHit.html>) | 922.46 ns | 1.12 μs | 1.21 | | |

### Related Issue on x64 Windows
[[Perf -9%] System.Reflection.Attributes.GetCustomAttributesMethodBaseHitInherit](https://github.com/DrewScoggins/performance-2/issues/3247)

### Related Issue on x86 Windows
[[Perf -8%] System.Reflection.Attributes.IsDefinedMethodBaseMiss](https://github.com/DrewScoggins/performance-2/issues/3263)

![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/11_16_2020/refs/heads/master_x64_ubuntu%2018.04_Regression/System.Reflection.Attributes_1.png>)
![graph](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/11_16_2020/refs/heads/master_x64_ubuntu%2018.04_Regression/System.Reflection.Attributes_2.png>)
[Historical Data in Reporting System](<https://pvscmdupload.blob.core.windows.net/autofilereport/autofilereports/11_16_2020/refs/heads/master_x64_ubuntu%2018.04/System.Reflection.Attributes.html>)

### Repro

```cmd
git clone https://github.com/dotnet/performance.git
python3 .\performance\scripts\benchmarks_ci.py -f netcoreapp5.0 --filter 'System.Reflection.Attributes*'
```
<details>

#### System.Reflection.Attributes.GetCustomAttributesMethodBaseHit

```log
[ 922.398 ;  956.872) | @@@@@@@@@@@@@@@@@@@@@@@@@@
[ 956.872 ;  976.632) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 976.632 ; 1000.064) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[1000.064 ; 1040.480) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[1040.480 ; 1081.836) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[1081.836 ; 1120.491) | @@@@@@@@@@@@@@
[1120.491 ; 1161.110) | @@@@@@@@@@@@@@@@@
[1161.110 ; 1188.058) | @@
[1188.058 ; 1225.138) | @@@@@@
[1225.138 ; 1269.293) | @
[1269.293 ; 1327.442) | @
```
#### System.Reflection.Attributes.GetCustomAttributesClassHit

```log
[ 911.653 ;  934.782) | @@@@@@@@@@@
[ 934.782 ;  957.356) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 957.356 ;  978.971) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[ 978.971 ; 1001.011) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[1001.011 ; 1023.298) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[1023.298 ; 1058.032) | @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[1058.032 ; 1084.649) | @@@@@@@@@@@@@@@
[1084.649 ; 1109.994) | @@@@@@@@@@@@
[1109.994 ; 1139.926) | @@@@@@@@
[1139.926 ; 1181.718) | @@@@@@
[1181.718 ; 1211.032) | @@
[1211.032 ; 1251.199) | @
[1251.199 ; 1296.092) | @
[1296.092 ; 1356.578) | @@@
```

### Docs

[Profiling workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/profiling-workflow-dotnet-runtime.md)
[Benchmarking workflow for dotnet/runtime repository](https://github.com/dotnet/performance/blob/master/docs/benchmarking-workflow-dotnet-runtime.md)

</details>

**Comment by steveharter** [comment] 2020-11-24 20:31
Not sure on source of regression although https://github.com/dotnet/runtime/pull/45121 may help.

**Comment by danmosemsft** [comment] 2020-11-25 00:16
cc @benaadams

**Comment by danmosemsft** [comment] 2020-11-25 00:23
It's a wierd regression, on both the scenarios it creeps up noisily during the Nov 13th. Hard to interpret such behavior, it's as if training data was rotting or something.

**Comment by krwq** [comment] 2021-07-22 16:15
[Triage] Is this tracking the same work as https://github.com/dotnet/runtime/issues/44713 ? In the meantime we're moving this to 7.0 as it seems non-essential for 6.0

**Comment by steveharter** [comment] 2022-12-05 17:28
Closing; old issue with no obvious root cause. There were various perf improvements made in V6 https://github.com/dotnet/runtime/pull/53152 based off of https://github.com/dotnet/runtime/pull/45121.

> [Triage] Is this tracking the same work as https://github.com/dotnet/runtime/issues/44713 ? In the meantime we're moving this to 7.0 as it seems non-essential for 6.0

No - that other issue was tracking "all attributes" while `GetCustomAttributesClassHit` was only selecting a [single attribute](https://github.com/dotnet/performance/blob/d7dac8a7ca12a28d099192f8a901cf8e30361384/src/benchmarks/micro/runtime/System.Reflection/Attributes.cs#L53).

**Closed by steveharter** 2022-12-05 17:28 UTC
Labels: area-System.Reflection, os-linux, tenet-performance, tenet-performance-benchmarks, arch-x64
