### ISSUE TITLE
IndexOf("\n") does not match "\r\n"

### ISSUE THREAD

**Issue by gfs** [dotnet/runtime#52936] opened 2021-05-18 20:33 UTC
The string based `IndexOf("\n")` and `LastIndexOf("\n")` do not match Windows linebreaks (`\r\n`) but the character based `IndexOf('\n')` does.  This contrasts with the behavior of `Contains` (and the apparent documented behavior of matching any substring) which matches `\r\n` for both `Contains('\n')` and `Contains("\n")`.

Here's the output of IndexOf and LastIndexOf compared with Contains.

```
"\r\n".IndexOf("\n") = -1
"\r\n".IndexOf('\n') = 1
"\r\n".LastIndexOf("\n") = -1
"\r\n".LastIndexOf('\n') = 1
"\r\n".Contains("\n") = True
"\r\n".Contains('\n') = True
```
Code to demonstrate the issue.
```csharp
using System;

namespace IndexOfDemo
{
    class Program
    {
        static void Main(string[] args)
        {
            var inputstring = "\r\n";
            var printableInput = "\\r\\n";
            Console.WriteLine($"\"{printableInput}\".IndexOf(\"\\n\") = {inputstring.IndexOf("\n")}");
            Console.WriteLine($"\"{printableInput}\".IndexOf('\\n') = {inputstring.IndexOf('\n')}");
            Console.WriteLine($"\"{printableInput}\".LastIndexOf(\"\\n\") = {inputstring.LastIndexOf("\n")}");
            Console.WriteLine($"\"{printableInput}\".LastIndexOf('\\n') = {inputstring.LastIndexOf('\n')}");
            Console.WriteLine($"\"{printableInput}\".Contains(\"\\n\") = { inputstring.Contains("\n")}");
            Console.WriteLine($"\"{printableInput}\".Contains('\\n') = { inputstring.Contains('\n')}");
        }
    }
}
```

**Comment by tarekgh** [comment] 2021-05-18 20:40
@gfs thanks for your report. This is a duplicate of https://github.com/dotnet/runtime/issues/43736. Please have a look at the detailed discussion there and let's know of if you still have any question.

**Closed by tarekgh** 2021-05-18 20:40 UTC
Labels: area-System.Globalization, untriaged
