### ISSUE TITLE
AV in CoreCLR!CreateFileWrapper after loading many assemblies in collectible ALCs

### ISSUE THREAD

**Issue by AArnott** [dotnet/runtime#34293] opened 2020-03-30 20:10 UTC
[AB#1277079](https://devdiv.visualstudio.com/10e66e43-9645-4201-b128-0fdc3769cc17/_workitems/edit/1277079)
I have a netcoreapp3.1 console app that tries to load thousands of dll's, each in its own collectible AssemblyLoadContext, to briefly scan them and produce a report. 
After loading many assemblies the application crashes with `OutOfMemoryException` or an AV.

**Repro**

Just run the repro project after adjusting the hard-coded baseDir constant to your own local VS 2019 installation: [andarno.AssemblyRefScanner.zip](https://github.com/dotnet/runtime/files/4405139/andarno.AssemblyRefScanner.zip)

Although it appears to run properly, when under the debugger, the VS Debug output window prints this out at the end:

> The program '[30696] AssemblyRefScanner.exe: Program Trace' has exited with code 0 (0x0).
The program '[30696] AssemblyRefScanner.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.

Or when executed without the debugger the last line is:

> Unhandled exception.

Setting the managed debugger to break on all first chance exceptions doesn't catch the problem -- the process just terminates.

**Comment by jkotas** [comment] 2020-03-30 20:39
Likely duplicate of https://github.com/dotnet/runtime/issues/2317

**Comment by mangod9** [comment] 2020-06-12 22:25
I can still repro the AV in debug builds with this stack:

```
[0x0]   <Unloaded_FileTracker64.dll> + 0x3b64   
[0x1]   CoreCLR!CreateFileWrapper + 0x289   
[0x2]   CoreCLR!PEImage::GetFileHandle + 0x343   
[0x3]   CoreCLR!MappedImageLayout::MappedImageLayout + 0x322   
[0x4]   CoreCLR!PEImageLayout::Map + 0x4b5   
[0x5]   CoreCLR!PEImage::CreateLayoutMapped + 0x32e   
[0x6]   CoreCLR!PEImage::GetLayoutInternal + 0x3ac   
[0x7]   CoreCLR!PEImage::GetLayout + 0xee   
[0x8]   CoreCLR!PEImage::CheckILFormat + 0x72   
[0x9]   CoreCLR!AssemblyNative::LoadFromPath + 0x2c8   
[0xa]   System_Private_CoreLib!ILStubClass.IL_STUB_PInvoke(IntPtr, System.String, System.String, System.Runtime.CompilerServices.ObjectHandleOnStack) + 0x145   
[0xb]   System_Private_CoreLib!System.Runtime.Loader.AssemblyLoadContext.InternalLoadFromPath(System.String, System.String) + 0x87   
[0xc]   System_Private_CoreLib!System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(System.String) + 0x181   
[0xd]   AssemblyRefScanner!AssemblyRefScanner.Program.ScanAssemblyReferences(System.String) + 0x93   
[0xe]   AssemblyRefScanner!AssemblyRefScanner.Program+<>c.<Main>b__2_1(System.String) + 0x45   
[0xf]   system_threading_tasks_dataflow!System.Threading.Tasks.Dataflow.TransformBlock`2[[System.__Canon, System.Private.CoreLib],[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib]], System.Private.CoreLib]].ProcessMessage(System.Func`2<System.__Canon,System.ValueTuple`2<System.__Canon,System.__Canon>>, System.Collections.Generic.KeyValuePair`2<System.__Canon,Int64>) + 0x10b   
[0x10]   system_threading_tasks_dataflow!System.Threading.Tasks.Dataflow.TransformBlock`2+<>c__DisplayClass9_0[[System.__Canon, System.Private.CoreLib],[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib]], System.Private.CoreLib]].<.ctor>b__3(System.Collections.Generic.KeyValuePair`2<System.__Canon,Int64>) + 0x67   
[0x11]   system_threading_tasks_dataflow!System.Threading.Tasks.Dataflow.Internal.TargetCore`1[[System.__Canon, System.Private.CoreLib]].ProcessMessagesLoopCore() + 0x4e8   
[0x12]   system_threading_tasks_dataflow!System.Threading.Tasks.Dataflow.Internal.TargetCore`1+<>c[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib]], System.Private.CoreLib]].<ProcessAsyncIfNecessary_Slow>b__34_0(System.Object) + 0xffffffffffcba2f4   
[0x13]   System_Private_CoreLib!System.Threading.Tasks.Task.InnerInvoke() + 0xed   
[0x14]   System_Private_CoreLib!System.Threading.Tasks.Task+<>c.<.cctor>b__276_0(System.Object) + 0x72   
[0x15]   System_Private_CoreLib!System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) + 0xe8   
[0x16]   System_Private_CoreLib!System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread) + 0x2c0   
[0x17]   System_Private_CoreLib!System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread) + 0x9b   
[0x18]   System_Private_CoreLib!System.Threading.Tasks.Task.ExecuteFromThreadPool(System.Threading.Thread) + 0x2d   
[0x19]   System_Private_CoreLib!System.Threading.ThreadPoolWorkQueue.Dispatch() + 0x2b8   
[0x1a]   System_Private_CoreLib!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback() + 0x1d   
```

**Comment by mangod9** [comment] 2020-08-04 23:16
Moving this to 6.

**Comment by janvorli** [comment] 2021-07-28 23:57
I've investigated this issue. The problem is triggered by attempting to load non-mananaged dlls into the collectible context. It seems that releasing the PEImage created from those in AssemblyNative::LoadFromPath when throwing the BadImageException results in unloading some native dlls from memory. 
When I experimentally added pILImage.SuppressRelease(); before each of the THROW_BAD_FORMAT invocations there, the crash is gone.
I need to investigate it more to figure out the exact culprit. However, I believe that if only managed assemblies were attempted to being loaded there, the issue would not occur.

**Comment by janvorli** [comment] 2021-07-29 20:56
I have tested it more, it crashes only with some special dlls. For example the FileTracker64.dll that is not supposed to be loaded directly or unloaded. It installs detours hooks and when it is removed, the hooks stay. There was one more similar case. So I am closing this issue as we cannot do anything about these.

**Closed** 2021-07-29 20:57 UTC
Labels: area-VM-coreclr
