### ISSUE TITLE
JIT: Optimize "x == a && y == b"

### ISSUE THREAD

**Issue by rameel** [dotnet/runtime#104767] opened 2024-07-11 23:54 UTC
Conditions like `x == a && y == b` can be optimized by converting them into equivalent bitwise operations:

```csharp
void Foo(int a, int b)
{
    if (a == 1 && b == 2)
        Console.WriteLine();
}
```
can be transformed into (at least for x86-64) to reduce conditional jumps
```csharp
void Foo(int a, int b)
{
    if (((a ^ 1) | (b ^ 2)) == 0)
        Console.WriteLine();
}
```

Current codegen:
```asm
cmp    ecx, 1
jne    SHORT G_M000_IG05
cmp    edx, 2
jne    SHORT G_M000_IG05
```

Expected codegen:
```asm
xor    ecx, 1
xor    edx, 2
or     ecx, edx
jne    SHORT G_M000_IG04
```
[Sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAJgEYBYAKBuIGYACMxgYRoG8bGfnylmKRgDEIEAPrkAFAEsAdhkbY0jeYuABKbry7Ve+1QDNGU7IwC85xuUYAyW42AWrpLXoMfi5AJxSNAbm0eAF8gxjCvAWIhUQlSWQUlFTVHN31dDx4ZYylcswA9aw1GQhMnQtdiy0YABjTM/S9fALDQ9x4I/kERMXF6BMVlVUTgZMSwMcUAE3qeDMzskzNqsDsHJ2qZsIamv0D2xjb9TqiY3viUoZTR4cUJ28Ytg/mPRdzTRkKwYtKpcseNFUrHVtpldi0Dm1gkA=)

Another samples:
`a == 1 && b == 0` ==> `((a ^ 1) | b) == 0`
`a == x && b == y` ==> `((a ^ x) | (b ^ y)) == 0`

**Comment by rameel** [comment] 2024-07-12 00:18
Interestingly, C++ compilers did not apply this optimization. Instead, Clang reverted the bitwise operations to conditional jumps. 

[godbolt.org](https://godbolt.org/z/qxc4zrzYd)

**Comment by tannergooding** [comment] 2024-07-12 00:43
That's likely because `if (((a ^ 1) | (b ^ 2)) == 0)` is not strictly better than `if (a == 1 && b == 2)`

Which is "better" depends on several factors and in many cases the jump can be faster than the additional cycle spent doing the `or`. It's something that's very hard to say which will win out barring no PGO data saying otherwise.

**Comment by jakobbotsch** [comment] 2024-07-12 06:34
This is a duplicate of #101347. I also agree with @tannergooding -- the benefits of a transformation like this one are unclear.

**Closed by jakobbotsch** 2024-07-12 06:34 UTC
Labels: area-CodeGen-coreclr, untriaged
