### ISSUE TITLE
NativeAot produces warning for generic instantiation which can't be suppressed

### ISSUE THREAD

**Issue by sbomer** [dotnet/runtime#77455] opened 2022-10-25 22:52 UTC
### Description

Instantiating a generic which has `DynamicallyAccessedMemberTypes` requirements with a type that has members marked `RequiresUnreferencedCode` correctly produces a warning. However, the warning is not suppressible by `RequiresUnreferencedCodeAttribute` or `UnconditionalSuppressMessageAttribute`.

The problem is that the message origin for the warning is an `InstantiatedMethod`, a type system entity that isn't associated with the calling context. Encountered while porting compiler-generated code tests from the linker as part of https://github.com/dotnet/runtime/issues/68786.

### Reproduction Steps

Publish the following with `PublishAot`:
```csharp
using RUC = System.Diagnostics.CodeAnalysis.RequiresUnreferencedCodeAttribute;
using DAM = System.Diagnostics.CodeAnalysis.DynamicallyAccessedMembersAttribute;
using DAMT = System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes;
using USM = System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessageAttribute;

class Program {
    static void Main() {
        Test();
    }
    [USM("", "IL2026:RequiresUnreferencedCode")]
    [RUC("")]
    static void Test() {
        MethodWithGenericWhichRequiresMethods<TypeWithMethodWithRequires>();
    }
    static void MethodWithGenericWhichRequiresMethods<[DAM(DAMT.All)] T>() {}
}

class TypeWithMethodWithRequires {
    [RUC("")]
 
    static void MethodWithRequires() {}
}
```

### Expected behavior

`RequiresUnreferencedCodeAttribute` or `UnconditionalSuppressMessageAttribute` on `Test` should suppress the warning.

### Actual behavior

```
ILC : Trim analysis warning IL2026: Program.MethodWithGenericWhichRequiresMethods<TypeWithMethodWithRequires>(): Using member 'TypeWithMethodWithRequires.MethodWithRequires()' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code.
```

**Comment by kant2002** [comment] 2023-01-03 06:48
This issue was caused by last line with call to `GetFlowDependenciesForInstantiation` which is called inside `MethodGenericDictionaryNode.ComputeNonRelocationBasedDependencies`
https://github.com/dotnet/runtime/blob/2619d1c8eeef4a881c3910c87c1a8903ed742c24/src/coreclr/tools/aot/ILCompiler.Compiler/Compiler/UsageBasedMetadataManager.cs#L800-L809

instantiated generic `method` variable with value `Program.MethodWithGenericWhichRequiresMethods<TypeWithMethodWithRequires>()` was given as source for depenndency flow analysis which is incorect because actual `source` of the call is `Test` method. From my limited understanding when `MethodGenericDictionaryNode` created information about call site is lost.

**Comment by vitek-karas** [comment] 2023-01-30 14:41
The fix has been reverted due to https://github.com/dotnet/runtime/issues/81358.

**Closed** 2023-02-07 09:07 UTC
Labels: untriaged, in-pr, area-NativeAOT-coreclr
