### ISSUE TITLE
`Stream.ReadByte` should use `stackalloc byte[1]` instead allocate one byte array

### ISSUE THREAD

**Issue by DrkWzrd** [dotnet/runtime#68800] opened 2022-05-03 05:52 UTC
### Description

In advance sorry for my english and sorry if this "is not a bug".

Right now in `System.IO.Stream.ReadByte` the code allocates an 1-length array for return the only byte read done in `Read(byte[], int, int)`

https://github.com/dotnet/runtime/blob/c9d8f8089d9e1e8590344eb2d3e1f994a3ba1d26/src/libraries/System.Private.CoreLib/src/System/IO/Stream.cs#L697-L702

### Reproduction Steps

Just that.

### Expected behavior

```C#
public virtual int ReadByte()
{
    var oneByteArray = (stackalloc byte[1]);
    int r = Read(oneByteArray);
    return r == 0 ? -1 : oneByteArray[0];
}
```

### Actual behavior

Actually a call to `ReadByte` can produce unnecesary GCs (and some child classes and developers that are unaware of this use it a lot).

**Comment by alexrp** [comment] 2022-05-03 06:06
This has been brought up a number of times before. This would be a breaking change because we'd now be calling the `Span<byte>` overload instead of the `byte[]` overload. This matters for derived classes that may not be expecting this.

I don't know if there's any appetite for taking that breaking change considering the fix is relatively easy for derived classes that care about the allocation.

**Comment by DrkWzrd** [comment] 2022-05-03 06:15
I think this should be revised, the performance impact is measurable, And this could be solved with something like.

```C#
 public virtual int ReadByte() 
 { 
     var oneByteArray = (stackalloc byte[1]); 
     int r = ReadByteSpan(oneByteArray); 
     return r == 0 ? -1 : oneByteArray[0]; 
 } 

private int ReadByteSpan(Span<byte> buffer)
{
    byte[] sharedBuffer = ArrayPool<byte>.Shared.Rent(buffer.Length);
    try
    {
        int numRead = Read(sharedBuffer, 0, buffer.Length);
        if ((uint)numRead > (uint)buffer.Length)
        {
            throw new IOException(SR.IO_StreamTooLong);
        }

        new ReadOnlySpan<byte>(sharedBuffer, 0, numRead).CopyTo(buffer);
        return numRead;
    }
    finally
    {
        ArrayPool<byte>.Shared.Return(sharedBuffer);
    }
}
```

I know this is "too much" but the performance in this way should be measured.

**Comment by teo-tsirpanis** [comment] 2022-05-03 08:30
> performance impact is measurable

`Stream.ReadByte` should not be used by high-performance code. Regardless of optimizations in its implementation, using it means calling a virtual method _for every byte_. It is recommended to use a `Read` overload and read many bytes at once (I've done something similar in my code and saw a significant performance improvement). And keep in mind that this is the default implementation of `Stream.ReadByte`. Derived classes can override it to make it allocation-free, and in fact most if not all streams in the BCL do that.

**Comment by stephentoub** [comment] 2022-05-03 13:35
> And this could be solved with something like

The overhead of renting/returning a 1-byte buffer as compared to allocating a byte[1] is sizeable:

|     Method |      Mean |
|----------- |----------:|
| RentReturn | 15.503 ns |
|      Alloc |  2.511 ns |

```
[Benchmark]
public byte[] RentReturn()
{
    byte[] buffer = ArrayPool<byte>.Shared.Rent(1);
    ArrayPool<byte>.Shared.Return(buffer);
    return buffer; // just to mirror the same benchmark signature as for Alloc()
}

[Benchmark]
public byte[] Alloc()
{
    byte[] buffer = new byte[1];
    return buffer;
}
```

As @teo-tsirpanis mentioned, this has been discussed and rejected multiple times in the past.

**Comment by Jozkee** [comment] 2022-05-03 21:08
Duplicate of https://github.com/dotnet/runtime/issues/60587.

**Closed by Jozkee** 2022-05-03 21:08 UTC
Labels: area-System.IO, untriaged
