### ISSUE TITLE
Issue when creating and debugging self-contained single file

### ISSUE THREAD

**Issue by ddobric** [dotnet/runtime#42927] opened 2020-09-28 15:13 UTC
Have created a simple application and published it as a self-contained single file.
Used following configuration in VS 2019 16.8.0 Preview 3.1:
![image](https://user-images.githubusercontent.com/1756871/94448331-0f243a80-01ab-11eb-8539-68e0f876dfdb.png)

`dotnet publish -r win-x86 --self-contained=true /p:PublishSingleFile=true`

When trying to debug (attach to process), getting the following error:

![image](https://user-images.githubusercontent.com/1756871/94448295-059ad280-01ab-11eb-879a-40dfa7756140.png)

Following output was generated:
![image](https://user-images.githubusercontent.com/1756871/94448770-9a053500-01ab-11eb-8959-8fcacce8ad83.png)

When looking at the output, I notice the ClassLibrart.Dll, which was referenced by the application. Does this indicate that no single file was generated at all?

Please note that all works fine when Framework-Dependent _publish_ with the single-file is used. Single file produced,  can attach a debugger.

Last but not least, the structure of the output is a bit wired. The Output contains several folders. What is the purpose of all of them?

**Comment by agocke** [comment] 2020-09-30 23:00
To attach to a single-file application, you'll need to copy mscordbi.dll from the parent directory into the exe directory.

**Comment by MaxXor** [comment] 2021-04-27 19:01
You can add `<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>` to your publish profile .pubxml. This will really produce a single executable file. However I'm having the same problems trying to attach the VS debugger to a self-contained executable as I'm trying to figure a crash which only happens when the executable is self-contained.

**Comment by Tyler-IN** [comment] 2023-02-24 00:50
Seems like even with `<DebuggerSupport>`, with .NET 7, if `<PublishSingleFile>` is true, can't attach a debugger.

**Comment by agocke** [comment] 2023-02-24 01:03
@Tyler-IN This should be fixed in the newest VS releases. What VS version are you using?

**Comment by Tyler-IN** [comment] 2023-02-24 02:13
I'm using the latest Rider, I'll give it a shot in VS2022 and see what happens.

**Comment by ALIENQuake** [comment] 2023-02-26 10:30
@Tyler-IN 
Debugging single-file apps require an extra step:

On Windows and Mac, Visual Studio and VS Code can be used to debug crash dumps. Attaching to a running self-contained single-file executable requires an extra file: mscordbi.{dll,so}.
...
if one were to publish a self-contained single-file executable using the dotnet CLI for Windows using the parameters -r win-x64, the executable would be placed in bin/Debug/net6.0/win-x64/publish. A copy of mscordbi.dll would be present in bin/Debug/net6.0/win-x64.

https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file#attaching-a-debugger

https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file

Future improvements are tracked by https://github.com/https://github.com/dotnet/runtime/issues/45382

**Comment by Tyler-IN** [comment] 2023-04-27 06:35
Any news on this?

**Comment by agocke** [comment] 2023-04-27 16:51
I believe there's a fix prepared and checked in. @VSadov do you have a link to that fix?

**Comment by VSadov** [comment] 2023-04-27 17:24
The fix link for 8.0 https://github.com/dotnet/runtime/pull/84965

We have not back ported this to 7.0 yet. 
It may be worth confirming first if the issue is properly fixed in a coherent 8.0 sdk build.

**Comment by agocke** [comment] 2023-04-27 17:39
That fix is in .NET 8 preview 4, so we should be able to see builds from there in the next day or so and validate the change. Assuming all goes well, we can backport to 7.0.

**Comment by arthur-liberman** [comment] 2023-06-28 15:25
It looks like the fix in .NET 8 works. Is there an ETA for this in .NET 6 and/or 7?

**Comment by phillip-haydon** [comment] 2024-03-04 20:41
Using .NET 8 I cannot debug projects marked as `<PublishSingleFile>true</PublishSingleFile>` :(

**Comment by agocke** [comment] 2024-03-05 04:06
Sorry for leaving this hanging -- we didn't find enough data to merit a backport to 7.0 when 8.0 was so close to release. 6.0 is fairly risky and it's not confirmed that this fix is enough for 6.0 anyway. We could consider it with enough feedback.

@phillip-haydon Can you create a new issue with the details? I think we should close this specific issue as resolved in .NET 8.

**Closed by agocke** 2024-03-05 04:06 UTC
Labels: question, area-Single-File
