### ISSUE TITLE
CI System.Linq.Expressions.Tests test failure 

### ISSUE THREAD

**Issue by tarekgh** [dotnet/runtime#55715] opened 2021-07-15 05:38 UTC
Apologize if this is previously reported but I couldn't find this exact one.

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-55520-merge-d9db673c66f0456196/System.Linq.Expressions.Tests/console.fdedcc42.log?sv=2019-07-07&se=2021-08-04T02%3A43%3A05Z&sr=c&sp=rl&sig=SV6q9Oql6gGpDUmq6rMW5RL%2FS2WNYnWLVQKS61bainU%3D

```
Console log: 'System.Linq.Expressions.Tests' from job d9db673c-66f0-4561-964d-657e6709da8f workitem 08209481-fb87-4463-8c63-0e4c8c8a0658 (windows.10.amd64.server19h1.open.rt) executed on machine a003347

C:\h\w\AA630934\w\990A0894\e>taskkill.exe /f /im corerun.exe 
ERROR: The process "corerun.exe" not found.

C:\h\w\AA630934\w\990A0894\e>call RunTests.cmd --runtime-path C:\h\w\AA630934\p 
----- start Thu 07/15/2021  2:55:44.46 ===============  To repro directly: ===================================================== 
pushd C:\h\w\AA630934\w\990A0894\e\
"C:\h\w\AA630934\p\dotnet.exe" exec --runtimeconfig System.Linq.Expressions.Tests.runtimeconfig.json --depsfile System.Linq.Expressions.Tests.deps.json xunit.console.dll System.Linq.Expressions.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
popd
===========================================================================================================

C:\h\w\AA630934\w\990A0894\e>"C:\h\w\AA630934\p\dotnet.exe" exec --runtimeconfig System.Linq.Expressions.Tests.runtimeconfig.json --depsfile System.Linq.Expressions.Tests.deps.json xunit.console.dll System.Linq.Expressions.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Linq.Expressions.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Linq.Expressions.Tests (found 5647 of 5656 test cases)
  Starting:    System.Linq.Expressions.Tests (parallel test collections = on, max threads = 2)
Fatal error. 0xC0000005
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Span`1<System.Object> ByRef, System.Signature, Boolean, Boolean)
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at Xunit.Sdk.TestInvoker`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].CallTestMethod(System.Object)
   at Xunit.Sdk.TestInvoker`1+<>c__DisplayClass48_1+<<InvokeTestMethodAsync>b__1>d[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Xunit.Sdk.TestInvoker`1+<>c
```

**Comment by tarekgh** [comment] 2021-07-15 05:47
This issue could be interop issue too. 

CC @jkoritzinsky

**Comment by jkoritzinsky** [comment] 2021-07-15 05:53
This is a duplicate of https://github.com/dotnet/runtime/issues/55536

**Closed by jkoritzinsky** 2021-07-15 05:53 UTC
Labels: area-System.Linq.Expressions, untriaged
