### ISSUE TITLE
[wasm] Test failure Dispose_DisposingHandlerCancelsActiveOperationsWithoutResponses - ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#58812] opened 2021-09-08 15:13 UTC
Test failure `ERR_CONTENT_LENGTH_MISMATCH` seen on https://github.com/dotnet/runtime/pull/57556 , windows:

`System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandlerTest.Dispose_DisposingHandlerCancelsActiveOperationsWithoutResponses`

[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1347818&view=logs&jobId=f9ca8601-c4c2-5da2-61cf-0da7d83d7557&j=f9ca8601-c4c2-5da2-61cf-0da7d83d7557&t=6f9dc6e4-5fb8-536e-70b9-642f2da0a848)
[Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-57556-merge-adbfa08a278c4aecba/System.Net.Http.Functional.Tests/1/console.99e2f19a.log?sv=2019-07-07&se=2021-09-28T03%3A03%3A42Z&sr=c&sp=rl&sig=2dPmOosL3Rs2TezI24aGG8WnLCIFbgT4fTbSzWcfV7o%3D)

```
[03:28:07] info: Starting:    System.Net.Http.Functional.Tests.dll
[03:28:12] fail: [out of order message from the browser]: http://127.0.0.1:49229/Echo.ashx?auth=basic&user=testuser&password=password - Failed to load resource: the server responded with a status of 401 (Unauthorized)
[03:28:12] fail: [out of order message from the browser]: https://127.0.0.1:49230/Echo.ashx?auth=basic&user=testuser&password=password - Failed to load resource: the server responded with a status of 401 ()
[03:28:12] fail: [out of order message from the browser]: https://127.0.0.1:49230/Echo.ashx?auth=basic&user=testuser&password=password - Failed to load resource: the server responded with a status of 401 ()
[03:38:04] fail: [out of order message from the browser]: http://127.0.0.1:49310/ - Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH
[03:38:04] fail: [FAIL] System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandlerTest.Dispose_DisposingHandlerCancelsActiveOperationsWithoutResponses
[03:38:04] info: System.Net.Http.HttpRequestException : TypeError: Failed to fetch
[03:38:04] info: ---- System.Runtime.InteropServices.JavaScript.JSException : TypeError: Failed to fetch
[03:38:04] info:    at System.Net.Http.BrowserHttpHandler.BrowserHttpContent.GetResponseData(CancellationToken cancellationToken)
[03:38:04] info:    at System.Net.Http.BrowserHttpHandler.BrowserHttpContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
[03:38:04] info:    at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
[03:38:04] info:    at System.Net.Http.HttpContent.<WaitAndReturnAsync>d__82`2[[System.Net.Http.HttpContent, System.Net.Http, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a],[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
[03:38:04] info:    at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<>c__DisplayClass29_1.<<Dispose_DisposingHandlerCancelsActiveOperationsWithoutResponses>b__2>d.MoveNext()
[03:38:04] info: --- End of stack trace from previous location ---
[03:38:04] info:    at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
[03:38:04] info:    at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<>c__DisplayClass29_0.<<Dispose_DisposingHandlerCancelsActiveOperationsWithoutResponses>b__1>d.MoveNext()
[03:38:04] info: --- End of stack trace from previous location ---
[03:38:04] info:    at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
[03:38:04] info:    at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<Dispose_DisposingHandlerCancelsActiveOperationsWithoutResponses>b__29_0(GenericLoopbackServer server1, Uri url1)
[03:38:04] info:    at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
[03:38:04] info:    at System.Net.Http.Functional.Tests.HttpClientHandlerTest.Dispose_DisposingHandlerCancelsActiveOperationsWithoutResponses()
[03:38:04] info: --- End of stack trace from previous location ---
[03:38:04] info: ----- Inner Stack Trace -----
[03:38:04] info:    at System.Net.Http.BrowserHttpHandler.BrowserHttpContent.GetResponseData(CancellationToken cancellationToken)
[03:38:21] info: Finished:    System.Net.Http.Functional.Tests.dll
```

**Comment by pavelsavara** [comment] 2021-09-08 15:20
This is loppback test, it may be caused by timing/consistency of underlying wasm WS 'send'

**Comment by pavelsavara** [comment] 2021-09-09 05:38
Another https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-58730-merge-dd85069d57404d64a1/System.Net.Http.Functional.Tests/1/console.710b184d.log?sv=2019-07-07&se=2021-09-28T12%3A10%3A00Z&sr=c&sp=rl&sig=Q%2FvKnrUWkCHn%2FiQlTFyN6NTloQVw4eNTR7cNBX4R%2BTQ%3D

**Comment by pavelsavara** [comment] 2021-09-14 18:28
Another https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-54011-merge-58d9db09baae4aa195/System.Net.Http.Functional.Tests/1/console.547422dc.log?sv=2019-07-07&se=2021-10-04T13%3A46%3A15Z&sr=c&sp=rl&sig=XRAvX2%2FZ%2FTzVhElXKR92HtJ0M1uHyGUEfUg1sHMISkw%3D

**Comment by radical** [comment] 2021-12-13 09:59
Hit this again on a rolling build - https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-1331159836d04ab186/System.Net.Http.Functional.Tests/1/console.58b18db4.log?sv=2019-07-07&se=2021-12-31T20%3A04%3A08Z&sr=c&sp=rl&sig=BzpBHIgYuw6ccpBZCOmOcFxT4Ye1k60DQEvI3ZilKAE%3D

**Comment by pavelsavara** [comment] 2021-12-15 16:53
Another [Log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-62292-merge-4cd838d80451454f8d/System.Net.Http.Functional.Tests/1/console.4c1b568b.log?sv=2019-07-07&se=2022-01-04T15%3A20%3A10Z&sr=c&sp=rl&sig=JucD4XByvfb0YfTuIXTCqeaofWWcrOTIEXtpU9iSUGE%3D)

**Comment by ilonatommy** [comment] 2022-06-20 08:51
@pavelsavara, keeping it under the 7.0 target?

**Comment by pavelsavara** [comment] 2022-07-11 10:16
Moved to future, It's not clear to me what causes it but it occasionally happens. So I will keep it open and assigned to me.

**Closed** 2022-09-21 08:42 UTC
Labels: arch-wasm, area-System.Net.Http, in-pr
