### ISSUE TITLE
NoWorkload-NoWebcil-ST-Wasm.Build.Tests.WorkItemExecution

### ISSUE THREAD

**Issue by ilonatommy** [dotnet/runtime#103114] opened 2024-06-06 08:33 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=698584
Build error leg or test failing: NoWorkload-ST-Wasm.Build.Tests.WorkItemExecution
Pull request: https://github.com/dotnet/runtime/pull/103088

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "The \"RestoreTask\" task returned false but did not log an error",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=698584
**Error message validated:** `[The "RestoreTask" task returned false but did not log an error`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 6/6/2024 8:34:08 AM UTC

### Report
|Build|Definition|Step Name|Console log|Pull Request|
|---|---|---|---|---|
|[710799](https://dev.azure.com/dnceng-public/public/_build/results?buildId=710799)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/710799/logs/1311)||
|[710341](https://dev.azure.com/dnceng-public/public/_build/results?buildId=710341)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/710341/logs/314)|dotnet/runtime#101337|
|[710259](https://dev.azure.com/dnceng-public/public/_build/results?buildId=710259)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/710259/logs/224)|dotnet/runtime#103574|
|[709904](https://dev.azure.com/dnceng-public/public/_build/results?buildId=709904)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/709904/logs/512)|dotnet/runtime#103564|
|[709680](https://dev.azure.com/dnceng-public/public/_build/results?buildId=709680)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/709680/logs/215)|dotnet/runtime#103405|
|[709462](https://dev.azure.com/dnceng-public/public/_build/results?buildId=709462)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/709462/logs/174)|dotnet/runtime#103537|
|[2474913](https://dev.azure.com/dnceng/internal/_build/results?buildId=2474913)|dotnet-runtime|Restore internal tools (browser_wasm)|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2474913/logs/1253)||
|[708836](https://dev.azure.com/dnceng-public/public/_build/results?buildId=708836)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/708836/logs/222)|dotnet/runtime#103213|
|[708815](https://dev.azure.com/dnceng-public/public/_build/results?buildId=708815)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/708815/logs/369)|dotnet/runtime#103508|
|[708356](https://dev.azure.com/dnceng-public/public/_build/results?buildId=708356)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/708356/logs/152)|dotnet/runtime#103452|
|[708106](https://dev.azure.com/dnceng-public/public/_build/results?buildId=708106)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/708106/logs/524)|dotnet/runtime#103241|
|[708088](https://dev.azure.com/dnceng-public/public/_build/results?buildId=708088)|dotnet/runtime|Build|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/708088/logs/60)|dotnet/runtime#103387|
|[708020](https://dev.azure.com/dnceng-public/public/_build/results?buildId=708020)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/708020/logs/205)|dotnet/runtime#103337|
|[707826](https://dev.azure.com/dnceng-public/public/_build/results?buildId=707826)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/707826/logs/377)|dotnet/runtime#103412|
|[707785](https://dev.azure.com/dnceng-public/public/_build/results?buildId=707785)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/707785/logs/537)|dotnet/runtime#99818|
|[707728](https://dev.azure.com/dnceng-public/public/_build/results?buildId=707728)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/707728/logs/213)|dotnet/runtime#103232|
|[707574](https://dev.azure.com/dnceng-public/public/_build/results?buildId=707574)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/707574/logs/520)|dotnet/runtime#103226|
|[707521](https://dev.azure.com/dnceng-public/public/_build/results?buildId=707521)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/707521/logs/647)|dotnet/runtime#103232|
|[706950](https://dev.azure.com/dnceng-public/public/_build/results?buildId=706950)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/706950/logs/165)|dotnet/runtime#103391|
|[2472827](https://dev.azure.com/dnceng/internal/_build/results?buildId=2472827)|dotnet-runtime|Build runtime (checked + debug)|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2472827/logs/9)||
|[2472807](https://dev.azure.com/dnceng/internal/_build/results?buildId=2472807)|dotnet-runtime|Restore internal tools|[Log](https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2472807/logs/1569)||
|[706387](https://dev.azure.com/dnceng-public/public/_build/results?buildId=706387)|dotnet/runtime|Build product|[Log](https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/706387/logs/208)|dotnet/runtime#103400|

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[704106](https://dev.azure.com/dnceng-public/public/_build/results?buildId=704106)|dotnet/runtime|[Wasm.Build.Tests.NativeLibraryTests.ProjectUsingSkiaSharp](https://dev.azure.com/dnceng-public/public/_build/results?buildId=704106&view=ms.vss-test-web.build-test-results-tab&runId=17547954&resultId=100067)|dotnet/runtime#103299|
|[703834](https://dev.azure.com/dnceng-public/public/_build/results?buildId=703834)|dotnet/runtime|[Wasm.Build.Tests.Blazor.MiscTests.DefaultTemplate_AOT_InProjectFile](https://dev.azure.com/dnceng-public/public/_build/results?buildId=703834&view=ms.vss-test-web.build-test-results-tab&runId=17537004&resultId=100027)|dotnet/runtime#100334|
|[701896](https://dev.azure.com/dnceng-public/public/_build/results?buildId=701896)|dotnet/runtime|[Workloads-ST-Wasm.Build.Tests.AspNetCore.SignalRClientTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=701896&view=ms.vss-test-web.build-test-results-tab&runId=17474740&resultId=100176)|dotnet/runtime#103212|
|[701555](https://dev.azure.com/dnceng-public/public/_build/results?buildId=701555)|dotnet/runtime|[Workloads-ST-Wasm.Build.Tests.Blazor.MiscTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=701555&view=ms.vss-test-web.build-test-results-tab&runId=17460998&resultId=100176)||
|[2450303](https://dev.azure.com/dnceng/internal/_build/results?buildId=2450303)|dotnet-runtime|[release.Partition27.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2450303&view=ms.vss-test-web.build-test-results-tab&runId=53696913&resultId=100024)||
|[2468855](https://dev.azure.com/dnceng/internal/_build/results?buildId=2468855)|dotnet-runtime|[release.Partition20.WorkItemExecution](https://dev.azure.com/dnceng//internal/_build/results?buildId=2468855&view=ms.vss-test-web.build-test-results-tab&runId=53696849&resultId=100045)||
|[700470](https://dev.azure.com/dnceng-public/public/_build/results?buildId=700470)|dotnet/runtime|[Workloads-NoWebcil-ST-Wasm.Build.Tests.Blazor.SimpleRunTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=700470&view=ms.vss-test-web.build-test-results-tab&runId=17430570&resultId=100178)|dotnet/runtime#102882|
|[700110](https://dev.azure.com/dnceng-public/public/_build/results?buildId=700110)|dotnet/runtime|[Workloads-ST-Wasm.Build.Tests.Blazor.SimpleRunTests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=700110&view=ms.vss-test-web.build-test-results-tab&runId=17422322&resultId=100174)|dotnet/runtime#101938|
|[698584](https://dev.azure.com/dnceng-public/public/_build/results?buildId=698584)|dotnet/runtime|[Wasm.Build.Tests.Blazor.WorkloadRequiredTests.WorkloadNotRequiredForInvariantGlobalization](https://dev.azure.com/dnceng-public/public/_build/results?buildId=698584&view=ms.vss-test-web.build-test-results-tab&runId=17382074&resultId=100005)|dotnet/runtime#103088|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|5|24|31|

**Comment by ericstj** [comment] 2024-06-17 23:52
Looks similar to https://github.com/dotnet/runtime/issues/103526

**Comment by ericstj** [comment] 2024-06-17 23:53
Duplicate of https://github.com/dotnet/dnceng/issues/3100

**Closed by ericstj** 2024-06-17 23:53 UTC
Labels: blocking-clean-ci, area-Infrastructure, untriaged, Known Build Error
