### ISSUE TITLE
Different results .Net 5.0 and .Net 6.0 on AES Crypto

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#59121] opened 2021-09-14 23:56 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Different-results-Net-50-and-Net-60-/1522080)._

---
I have found that the code enclosed works under 5.0 but breaks on 6.0.  Under 6.0 the throw is hit because the original data is 17 bytes but under 6.0 it will return 16.  It runs fine under 5.0.

I have included a 5.0 version that works.  And a 6.0 that does not.

This is a big deal as it is my password logic.  So, stopped on switching to 6.0.

---
#### Feedback Bot on 9/6/2021, 02:32 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Brett McDonald on 9/7/2021, 03:43 AM: 

<p>In addition, 17 is just the first length it starts to fail.  As the length gets longer it outputs less data.  So, not just off by one.  Seems there is a problem with the whole process.</p>

---
### Original Solutions
(no solutions)

**Comment by wzchua** [comment] 2021-09-15 00:14
I assume this is about the crypto stream
See https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/partial-byte-reads-in-streams

**Comment by GrabYourPitchforks** [comment] 2021-09-15 02:16
Duplicate of https://github.com/dotnet/runtime/issues/56834. See also the doc linked to by https://github.com/dotnet/runtime/issues/59121#issuecomment-919599014 for sample code that follows the recommended patterns.

**Closed by GrabYourPitchforks** 2021-09-15 02:16 UTC
Labels: untriaged
