### ISSUE TITLE
System.AccessViolationException: Int128 ToString invalid memory reads and string interpolation crash

### ISSUE THREAD

**Issue by hamarb123** [dotnet/runtime#75656] opened 2022-09-15 01:47 UTC
### Description

When I to `.ToString()` on my `Int128`, it reads out memory and then crashes.
When I do string interpolation on my `Int128`, it throws an exception and crashes.
Clearly, this is not intended functionality.

### Reproduction Steps

1. Run
```csharp
Console.WriteLine(new Int128(18446744073709551613, 18446744073709551604).ToString());
```

2. Run
```csharp
Console.WriteLine($"A={new Int128(18446744073709551613, 18446744073709551604)})");
```

(This is literally my whole program now because I wanted to make sure it wasn't something else)

### Expected behavior

Prints a number and doesn't crash ;)

### Actual behavior

1. Prints random memory and crashes
![image](https://user-images.githubusercontent.com/25316035/190293882-d4ff03dc-1ba9-4f3a-8308-a01da3b86830.png)

2. Crashes
![image](https://user-images.githubusercontent.com/25316035/190293930-8f99866b-9a74-4d21-905b-737603783329.png)

### Configuration

.NET 7 RC 1
Windows 10 x64 v10.0.19044.1949
Running in Debug mode

Also tested on macOS 12.6 x64 with .NET 7 Preview 7, got slightly different output (below):
1. ![image](https://user-images.githubusercontent.com/25316035/190293821-3d918ed6-a996-48e9-9682-7d6de97a37be.png)
2. ![image](https://user-images.githubusercontent.com/25316035/190293603-0f3cd38d-3570-437c-9506-b1ee48321dae.png)

### Other information

It's probably missing a `\0` at the end based on that ridiculous console output. idk. Also unsure if the string interpolation one has a secondary issue as well or not.

Edit: it (above) being one of the helper method that converts to a string. This could be why since it may just keep reading random memory when constructing the string until it hits a `\0` `char` (ie. 2x 0 bytes - low chance hence why I see AVEs instead) or an AVE/NRE.

**Comment by tannergooding** [comment] 2022-09-15 01:58
Pretty sure this has already been fixed for RC2, but I will confirm first thing tomorrow.

**Comment by hamarb123** [comment] 2022-09-15 02:00
Okay, so I would have to download a daily build to be able to test my actual code without this. Would the current daily build be new enough?

**Comment by tannergooding** [comment] 2022-09-15 02:01
Yes, I expect the current daily build should contain the relevant fix.

**Comment by hamarb123** [comment] 2022-09-15 02:08
I've tested it, and it is fixed in the daily version, thanks!

Also, (unrelated to this issue), is there a way to get the sdk installer not to do this (I assume it's removing the previous version)?
<img width="636" alt="image" src="https://user-images.githubusercontent.com/25316035/190296267-b5fc576e-05fd-4638-87b8-e0cff06bc078.png">

**Comment by tannergooding** [comment] 2022-09-15 02:11
I think @KathleenDollard or @baronfel would be the people to answer that.

I'll close this issue since the issue is resolved in the latest daily build for .NET 7 RC2.

**Closed by tannergooding** 2022-09-15 02:11 UTC
Labels: bug, area-System.Runtime

**Comment by baronfel** [comment] 2022-09-16 17:56
We typically only keep one version of the SDK from each 'feature band', meaning the last number's hundreth'-place. So depending on which 'channel' you've installed an SDK from (typically standalone installer MSI or VS are the main channels), if you install a newer version in the same feature band within that channel, the previous installation will be removed. So if you really wanted to make it happen, you could install a version of VS that included the preview you wanted, and install the standalone installer of the other version you wanted.

Having said all of that, you can also use the dotnet-install scripts to install any version to any location at any time, setting the `DOTNET_ROOT` to point to that installed location.
