### ISSUE TITLE
Configuration binder failed when getter of read only property throw exception

### ISSUE THREAD

**Issue by lenraven** [dotnet/runtime#65710] opened 2022-02-22 14:22 UTC
### Description

# The problem

When I try to add a read only property, what based on my configuration, the Binding of configuration will throw the following exception.

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at BindPropertyExceptionSample.Configuration.get_FilteredConfigValues() in C:\Source\Github\BindPropertyExceptionSample\BindPropertyExceptionSample\Configuration.cs:line 5
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.PropertyInfo.GetValue(Object obj)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindNonScalar(IConfiguration configuration, Object instance, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Bind(IConfiguration configuration, Object instance, Action`1 configureOptions)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Bind(IConfiguration configuration, Object instance)
   at Program.<Main>$(String[] args) in C:\Source\Github\BindPropertyExceptionSample\BindPropertyExceptionSample\Program.cs:line 12
```

# Sample
Configuration.cs
```csharp
public class Configuration
{
    public IEnumerable<int> FilteredConfigValues => ConfigValues.Where(p => p > 10);
    public IEnumerable<int> ConfigValues { get; set; } = null!;
}
```
appsettings.json:
```json
{
    "Logging": {
        "LogLevel": {
            "Default": "Debug",
            "System": "Information",
            "Microsoft": "Information"
        }
    },
    "TestConfig": {
        "ConfigValues": [ 1, 10, 100, 1000 ]
    }
}
```
Program.cs
```csharp
using BindPropertyExceptionSample;

using Microsoft.Extensions.Configuration;

var config = new ConfigurationBuilder()
    .AddJsonFile("appsettings.json")
    .Build();

var testConfig = new Configuration();
config.GetSection("TestConfig").Bind(testConfig); // The exeption will be thrown here.

Console.WriteLine($"Filtered config values: {string.Join(", ", testConfig.FilteredConfigValues)}");
```

# Reason

The `ConfigurationBinder.BindProperty` is reading the value of the property before it decide is there setter of property.
At this line: [`object? propertyValue = property.GetValue(instance);`](https://github.com/dotnet/runtime/blob/7da602644b7088233a13d5c7202d0aabcd0e29f6/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs#L236)

### Reproduction Steps

You can find a repository with a sample code of the issue [here](https://github.com/lenraven/BindPropertyExceptionSample).

### Expected behavior

Skip the read only properties during the binding.

### Actual behavior

An exception was thrown when I call the Bind of configuration.

### Configuration

Target framework: NET 6.0
SDK: 6.0.101
Operating system: Windows 10
Architecture x64

**Comment by madelson** [comment] 2022-03-16 12:43
Possible duplicate of https://github.com/dotnet/runtime/issues/52905

**Comment by maryamariyan** [comment] 2022-03-25 19:52
But this NRE stacktrace is pointing to the where clause below in the user code itself:

```c#
public class Configuration
{
    public IEnumerable<int> FilteredConfigValues => ConfigValues.Where(p => p > 10);
    public IEnumerable<int> ConfigValues { get; set; } = null!;
}
```

**Comment by tarekgh** [comment] 2022-03-25 21:48
Just to note, if flipping the order of the properties, this should workaround this issue:

```C#
public class Configuration
{
    public IEnumerable<int> ConfigValues { get; set; } = null!;
    public IEnumerable<int> FilteredConfigValues => ConfigValues.Where(p => p > 10);
}
```

**Closed** 2022-04-02 19:01 UTC
Labels: up-for-grabs, area-Extensions-Configuration, in-pr
