### ISSUE TITLE
NullReferenceException sometimes in System.Text.Json on iOS/MAUI

### ISSUE THREAD

**Issue by damiand2** [dotnet/runtime#93967] opened 2023-10-25 11:30 UTC
### Description

I get sporadic (but not that very rare) error reports from mobile app written in MAUI (.net7) on iOS only devices - on Android there are no problems. I use json code generator for serialization.
Sample error stack:
```
System.Text.Json.Utf8JsonWriter.WriteNumberValueMinimized(Int64 )
System.Text.Json.Utf8JsonWriter.WriteNumberValue(Int64 )
System.Text.Json.Serialization.Converters.Int32Converter.WriteNumberWithCustomHandling(Utf8JsonWriter , Int32 , JsonNumberHandling )
System.Text.Json.Serialization.Converters.NullableConverter``1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].WriteNumberWithCustomHandling(Utf8JsonWriter , Nullable``1 , JsonNumberHandling )
System.Text.Json.Serialization.JsonConverter``1[[System.Nullable``1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryWrite(Utf8JsonWriter , Nullable``1& , JsonSerializerOptions , WriteStack& )
System.Text.Json.Serialization.Metadata.JsonPropertyInfo``1[[System.Nullable``1[[System.Int32, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetMemberAndWriteJson(Object , WriteStack& , Utf8JsonWriter )
System.Text.Json.Serialization.Converters.ObjectDefaultConverter``1[[XXX.Mobile.Storage.CardData, XXX.Mobile, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryWrite(Utf8JsonWriter , CardData , JsonSerializerOptions , WriteStack& )
System.Text.Json.Serialization.Converters.JsonMetadataServicesConverter``1[[XXX.Mobile.Storage.CardData, XXX.Mobile, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryWrite(Utf8JsonWriter , CardData , JsonSerializerOptions , WriteStack& )
System.Text.Json.Serialization.JsonConverter``1[[XXX.Mobile.Storage.CardData, XXX.Mobile, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].TryWrite(Utf8JsonWriter , CardData& , JsonSerializerOptions , WriteStack& )
System.Text.Json.Serialization.JsonConverter``1[[XXXMobile.Storage.CardData, XXX.Mobile, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].WriteCore(Utf8JsonWriter , CardData& , JsonSerializerOptions , WriteStack& )
System.Text.Json.JsonSerializer.WriteCore[CardData](Utf8JsonWriter , CardData& , JsonTypeInfo``1 )
System.Text.Json.JsonSerializer.WriteString[CardData](CardData& , JsonTypeInfo``1 )
System.Text.Json.JsonSerializer.Serialize[CardData](CardData , JsonTypeInfo``1 )
XXX.XXX.StoreCardData(CardData cardData)
```

Class that is being serialized:
```C#
public enum CardStatus
{
    Active = 1,
    Inactive = 2
}
public class CardData
{
    public int? CardServiceId { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public int? CardNumber { get; set; }
    public string OfflineCode { get; set; }
    public CardStatus? CardStatus { get; set; }
    public Guid? CurrentVAPhoneInstallationId { get; set; }        
    public int EuzAccountId { get; set; }
    public string EuzAccountTenantCountryCode { get; set; }
    public string CardProductName { get; set; }
    public string CardImagePath { get; set; }
    public DateTime? ActivationDate { get; set; }
    public DateTime LastCheckDate { get; set; }  
}
```
I cannot reproduce it locally , passing all nulls in nullable fields does not reproduce this result.
Class for json code generator:
```C#
[JsonSerializable(typeof(CardData))]
[JsonSerializable(typeof(String))]
[JsonSerializable(typeof(System.Int64))]
[JsonSerializable(typeof(System.Int32))]
[JsonSerializable(typeof(DateTime))]
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
internal partial class JsonSourceGenerationContext : JsonSerializerContext
{
    public static JsonSourceGenerationContext PascalCase = new JsonSourceGenerationContext(new JsonSerializerOptions
    {
        PropertyNamingPolicy = null
    });

    public static JsonSourceGenerationContext Api => Default;
}
public class CardStatusConverter : System.Text.Json.Serialization.JsonConverter<CardStatus?>
{
    public override CardStatus? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {

        if (reader.TokenType == JsonTokenType.Number)
        {
            return (CardStatus)reader.GetInt32();

        }
        else if (reader.TokenType == JsonTokenType.String)
        {
            var val = reader.GetString();
            switch (val)
            {
                case nameof(CardStatus.Active): return CardStatus.Active;
                case nameof(CardStatus.Inactive): return CardStatus.Inactive;
                default: throw new ApplicationException("Unknown value for CardStatus " + val);
            }
        }
        else if (reader.TokenType == JsonTokenType.Null)
        {
            return null;
        }

        throw new System.Text.Json.JsonException();
    }

    public override void Write(Utf8JsonWriter writer, CardStatus? value, JsonSerializerOptions options)
    {
        if (value.HasValue) writer.WriteStringValue(value.ToString());
        else writer.WriteNullValue();
    }
}
```

What i omitted in this code is a lot of generated json classes for Api calls. And here is strange part - i get no errors when using JsonSourceGenerationContext .Api (which means default) serializations, ALL of them happen only when i use JsonSourceGenerationContext.PascalCase, example:
```C#
serializedData = System.Text.Json.JsonSerializer.Serialize(cardData, JsonSourceGenerationContext.PascalCase.CardData);
```

### Reproduction Steps

i cannot reproduce it

### Expected behavior

should not throw nullreferenceexception

### Actual behavior

throws

**Comment by eiriktsarpalis** [comment] 2023-10-25 12:05
Would it be possible to share a self-contained reproducing app? If I were to guess what might be causing it, I'd say it's a runtime issue -- we've received similar issues in the past.

> What i omitted in this code is a lot of generated json classes for Api calls. And here is strange part - i get no errors when using JsonSourceGenerationContext .Api (which means default) serializations, ALL of them happen only when i use JsonSourceGenerationContext.PascalCase

I would guess that happens because by overriding the compile-time settings the serializer will use metadata mode instead of fast-path mode. You could try forcing that mode everywhere (and increase the probability of the error) by passing `GenerationMode = JsonSourceGenerationMode.Metadata` in your `JsonSourceGenerationOptions` annotation.

**Comment by damiand2** [comment] 2023-10-25 13:26
@eiriktsarpalis - i cannot reproduce it, sorry, this happens only in production (on real iphones) and is undeterministic. As you may guess - i'm not really into trying to increase that error rate in production :) . But i will try to go into opposite direction - making second JsonSourceGenerationContext with pascal case option and moving all data types for pascal case serialization there. I will let you know if problem went away.

**Comment by eiriktsarpalis** [comment] 2023-10-25 14:45
Are you able to reproduce the issue on dev devices or in emulators? Have you tried deploying a version of the app that just runs the impacted stacktrace in a loop to see if you can force it?

**Comment by damiand2** [comment] 2023-10-25 15:03
@eiriktsarpalis - i tried first part about devices and simulators - i will try to make a console app with loop like you suggested to see if i can reproduce it. I will let you know about that later on.

**Comment by karakasa** [comment] 2023-10-26 03:08
I'm just a bit curious which line can throw a NRE in that method? 🤔

```
private void WriteNumberValueMinimized(long value)
{
	int maxRequired = 21;
	if (_memory.Length - BytesPending < maxRequired)
	{
		Grow(maxRequired);
	}
	Span<byte> output = _memory.Span;
	if (_currentDepth < 0)
	{
		output[BytesPending++] = 44;
	}
	int bytesWritten;
	bool result = Utf8Formatter.TryFormat(value, output.Slice(BytesPending), out bytesWritten);
	Debug.Assert(result);
	BytesPending += bytesWritten;
}
```

**Comment by damiand2** [comment] 2023-11-15 14:56
problem is still unsolved, however for now i do not see them anymore in production logs when i created separate JsonSourceGenerationContext - one with PascalCase naming policy and one with default

**Comment by eiriktsarpalis** [comment] 2023-11-15 20:17
I'm going to close this for lack of data if that's ok. Feel free to reopen if new information or a better repro comes by. Thanks!

**Closed by eiriktsarpalis** 2023-11-15 20:17 UTC
Labels: area-System.Text.Json, runtime-mono, needs-further-triage
