### ISSUE TITLE
Test failure JIT/Regression/JitBlue/Runtime_40444/Runtime_40444/Runtime_40444.sh

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#66690] opened 2022-03-16 01:24 UTC
Failed in: [runtime-coreclr outerloop 20220315.2](https://dev.azure.com/dnceng/public/_build/results?buildId=1664696&view=ms.vss-test-web.build-test-results-tab&runId=45787668&resultId=105641&paneView=debug)

Failed test:
```
R2R-CG2 windows x86 Checked @ Windows.10.Amd64.Open

- JIT\\Regression\\JitBlue\\Runtime_40444\\Runtime_40444\\Runtime_40444.cmd

```
**Error message:**
```
Could Not Find C:\h\w\B407098D\w\A45308DC\e\JIT\Regression\JitBlue\Runtime_40444\Runtime_40444\IL-CG2\composite-r2r.dll
Could Not Find C:\h\w\B407098D\w\A45308DC\e\JIT\Regression\JitBlue\Runtime_40444\Runtime_40444\Runtime_40444.dll.rsp
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'System.Security.Cryptography.Primitives, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. File is corrupt. (0x8013110E)
File name: 'System.Security.Cryptography.Primitives, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.BadImageFormatException: File is corrupt. (0x8013110E)
at ILCompiler.CoreRTNameMangler.SanitizeNameWithHash(String literal)
at ILCompiler.CoreRTNameMangler.set_CompilationUnitPrefix(String value)
at ILCompiler.Program.RunSingleCompilation(Dictionary2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary2 unrootedInputFilePaths, HashSet`1 versionBubbleModulesHash, CompilerTypeSystemContext typeSystemContext)
at ILCompiler.Program.Run(String[] args)
at ILCompiler.Program.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\B407098D\w\A45308DC\uploads\Reports\JIT.Regression\JitBlue\Runtime_40444\Runtime_40444\Runtime_40444.output.txt
Raw output:
BEGIN EXECUTION
Runtime_40444.dll
1 file(s) copied.
Response file: C:\h\w\B407098D\w\A45308DC\e\JIT\Regression\JitBlue\Runtime_40444\Runtime_40444\Runtime_40444.dll.rsp
C:\h\w\B407098D\w\A45308DC\e\JIT\Regression\JitBlue\Runtime_40444\Runtime_40444\IL-CG2\Runtime_40444.dll
-o:C:\h\w\B407098D\w\A45308DC\e\JIT\Regression\JitBlue\Runtime_40444\Runtime_40444\Runtime_40444.dll
--targetarch:x86
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\B407098D\p\System..dll
-r:C:\h\w\B407098D\p\Microsoft..dll
-r:C:\h\w\B407098D\p\mscorlib.dll
-r:C:\h\w\B407098D\p\netstandard.dll
-O
" "dotnet" "C:\h\w\B407098D\p\crossgen2\crossgen2.dll" @"C:\h\w\B407098D\w\A45308DC\e\JIT\Regression\JitBlue\Runtime_40444\Runtime_40444\Runtime_40444.dll.rsp"   -r:C:\h\w\B407098D\w\A45308DC\e\JIT\Regression\JitBlue\Runtime_40444\Runtime_40444\IL-CG2*.dll"
Crossgen2 failed with exitcode - -532462766
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\B407098D\p
C:\h\w\B407098D\w\A45308DC\e\JIT\Regression\JitBlue\Runtime_40444\Runtime_40444\Runtime_40444.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_Regression._JitBlue_Runtime_40444_Runtime_40444_Runtime_40444_._JitBlue_Runtime_40444_Runtime_40444_Runtime_40444_cmd()
```

**Comment by BruceForstall** [comment] 2022-03-16 01:26
@dotnet/crossgen-contrib Looks like probably some infra failure.

**Comment by BruceForstall** [comment] 2022-03-16 01:27
Looks like every test failed in this run.

**Comment by mangod9** [comment] 2022-03-16 01:29
This is the issue @trylek has been investigating where there is some loader issue with loading assemblies. Doesnt look related to crossgen2 but some infra issue with virus or malware tooling possibly?

**Comment by trylek** [comment] 2022-03-16 10:35
To be precise I believe that, when this happens, the entire Helix work item is doomed but not all tests actually (there are more than 600 tests in outerloop runs).

**Comment by tannergooding** [comment] 2022-03-22 20:33
This is a dupe of https://github.com/dotnet/runtime/issues/65646

**Comment by trylek** [comment] 2022-04-04 20:21
Closing as duplicate of: https://github.com/dotnet/runtime/issues/65646

**Closed by trylek** 2022-04-04 20:21 UTC
Labels: arch-x86, os-windows, area-crossgen2-coreclr, blocking-outerloop
