### ISSUE TITLE
Console output gets messed up after GetCursorPosition is called, if application has been started with "dotnet run".

### ISSUE THREAD

**Issue by perjahn** [dotnet/runtime#75073] opened 2022-09-04 05:33 UTC
### Description

* In Linux, output of console gets messed up after abrupt exit, if application has called Console.GetCursorPosition.
* Reproduce: Create a console app that is calling Console.GetCursorPosition and then waits in a loop. Start application with "dotnet run", and then break the application using Ctrl+C.
* After the .net/c# application has quit, text output in terminal gets disabled.

### Configuration

* Using dotnet 6.0.400.
* Native Kubuntu 22.04 and Docker (mcr.microsoft.com/dotnet/sdk) on both Macos and Linux.
* Architecture x64 and arm64.
* Appear to be specific to linux, b/c it works well on native terminals in Macos (arm64).

### Regression

Haven't tested with older dotnet versions than 6.0, but 6.0.200 has the same problem.

### Example application (that disables console output after Ctrl+C)

```
class Program
{
    public static void Main()
    {
        var pos = System.Console.GetCursorPosition();
        while (true) { }
    }
}
```

### Another example application (that also disables console output after exit)

```
class Program
{
    public static void Main()
    {
        var pos = System.Console.GetCursorPosition();
        System.Environment.FailFast(string.Empty);
    }
}
```

### Project file

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
</Project>
```

**Comment by adamsitnik** [comment] 2022-09-06 07:22
Hi @perjahn 

It looks like you have hit issue #64166, which was already fixed in .NET 7 and is currently being backported to .NET 6 (#64985). The fix is going to be released very soon as part of .NET 6.0.9.

Is there any chance you could try reproducing it with .NET 7?

**Comment by perjahn** [comment] 2022-09-06 18:31
Yes, it's reproducible with .net7. I've tested with the latest mcr.microsoft.com/dotnet/nightly/sdk docker image, and using TargetFramework net7.0. Running this image on both macos and kubuntu.
Kubuntu/x64 had dotnet 7.0.0-rc.1.22409.3 in the docker image and Macos/arm64 had dotnet 7.0.100-rc.1.22415.4 in the docker image. Same problem when running a console app with "dotnet run" and exiting it abruptly. :(

**Comment by adamsitnik** [comment] 2022-09-07 06:07
@perjahn thank you for verification!

@tmds is there any chance you could take a look?

**Comment by tmds** [comment] 2022-09-07 06:28
I can't reproduce this on Fedora using .NET 7.
When I terminate the `dotnet run` using `Ctrl+C` the console echo is working.

When I do the same thing in a container, it also works.
I start my container using `podman run -ti mcr.microsoft.com/dotnet/nightly/sdk` and then use these commands:
```
dotnet new console -o /tmp/console
cd /tmp/console
cat >Program.cs <<EOF
class Program
{
    public static void Main()
    {
        var pos = System.Console.GetCursorPosition();
        while (true) { }
    }
}
EOF
dotnet build
dotnet run
```

Are these steps similar to what you are doing with `docker`?

For the `System.Environment.FailFast(string.Empty);` the terminal doesn't get reset.
afaik it has been like this for all .NET versions.

**Comment by perjahn** [comment] 2022-09-07 13:50
The first example with while(true) appear to have been fixed in .net7, could you also test the second example with FailFast in fedora/podman?

**Comment by tmds** [comment] 2022-09-07 14:49
As mentioned, I don't expect the `FailFast` to restore echo. It has been like this for all .NET versions.

The terminal reset logic is registered with `atexit`, and these handlers don't run when calling `abort` (which is what `FailFast` does).

Maybe mac does something after the child terminated to restore the terminal settings.

**Comment by tmds** [comment] 2022-09-08 09:47
Now we're failing really fast, and don't take the time to reset the terminal.

We could do it. The request hasn't come up before. Maybe because `FailFast` is uncommon.

Do your apps often terminate by `FailFast`?

**Comment by tmds** [comment] 2022-09-08 10:33
To reset the terminal on `FailFast` we need to add some specific handling.

**Comment by danmoseley** [comment] 2022-09-08 13:58
On any FailFast? I believe we try to run as close to zero code as we can before exiting, as it's a security mitigation.

**Comment by adamsitnik** [comment] 2022-10-20 13:56
> The first example with while(true) appear to have been fixed in .net7, 

Thank you for confirmation! In the meantime it got backported to 6.0 as well: https://github.com/dotnet/runtime/pull/64985

> I believe we try to run as close to zero code as we can before exiting, as it's a security mitigation.

It's by design then and I am afraid we won't be changing it anytime soon.

**Closed by adamsitnik** 2022-10-20 13:56 UTC
Labels: area-System.Console
