### ISSUE TITLE
dotnet quit unexpectedly

### ISSUE THREAD

**Issue by wli3** [dotnet/runtime#44567] opened 2020-11-12 01:07 UTC
@sgronblo commented on [Thu Oct 29 2020](https://github.com/dotnet/core/issues/5476)

# Issue Title

Runtime exception in my own program incorrectly identified as a dotnet crash

# General

If I run a simple program that throws any runtime exception using `dotnet run`. It will be detected as a dotnet crash and a dialog saying "dotnet quit unexpectedly" giving me the offer to send a crash report to Apple.

dotnet --version: 3.1.403
OS: macOS Catalina 10.15.7

Simple reproduction:

```
open System

[<EntryPoint>]
let main argv =
    raise (Exception("testing"))
    0 // return an integer exit code
```

Running it through `dotnet run`

![image](https://user-images.githubusercontent.com/320449/97595590-2cb52000-1a47-11eb-8ed3-c4d7f73e7735.png)

I am now forced to click "ignore" every time I run into an exception when developing a real program.

---

@mairaw commented on [Fri Nov 06 2020](https://github.com/dotnet/core/issues/5476#issuecomment-722958897)

Can you check this @cartermp?

---

@cartermp commented on [Fri Nov 06 2020](https://github.com/dotnet/core/issues/5476#issuecomment-723150450)

This one isn't specific to F#, as you'll see the same behavior in a C# app that just throws an exception. Might be good to start with the cli/sdk cc @marcpopMSFT 

---

@marcpopMSFT commented on [Fri Nov 06 2020](https://github.com/dotnet/core/issues/5476#issuecomment-723324911)

@wli3 is this specific to how dotnet run works on mac?

---

@wli3 commented on [Wed Nov 11 2020](https://github.com/dotnet/core/issues/5476#issuecomment-725755155)

Nothing special on mac or dotnet run. We spin up a process to run the application just built. I'll ask runtime team to see if this is expected.

**Comment by mangod9** [comment] 2020-11-12 18:45
@sgronblo does the same behavior repro on 5.0? 

/cc:@janvorli

**Comment by janvorli** [comment] 2020-11-12 22:31
@sgronblo abort() is called when unhandled exception occurs. Unhandled exception is considered to be an abnormal termination, so the message seems correct.

**Comment by sgronblo** [comment] 2020-12-05 04:56
Is this part of some official spec? I guess the problem is should be trivially resolvable by adding an error catch statement to the program. It just seemed like it works differently from every language I've used so far where an uncaught runtime exception  (which could be the result of incorrect user input for example) would not be considered as an error that needs to be reported.

**Comment by janvorli** [comment] 2020-12-07 10:02
If you throw an exception in C++ and you don't catch it, it behaves the same way:

testunhandled.cpp:
```c++
#include <iostream>

void test()
{
    throw 1;
}

int main(int argc, char** argv)
{
    test();
    return 1;
}
```

```sh
clang++ testunhandled.cpp -o testunhandled

./testunhandled
terminate called after throwing an instance of 'int'
Aborted (core dumped)
```

**Comment by sgronblo** [comment] 2020-12-08 13:37
Ok, I tried that. It does not behave the same way as I described in the original issue. There is no dialog saying "testunhandled quit unexpectedly" which is asking if I want to report this error to Apple.

**Comment by janvorli** [comment] 2020-12-08 15:13
I think that macos error reporting most likely has a special handling for c++ exceptions, as both c++ and C# abort on exception:

C++ on macOS (the previous example I've shared was on Linux):
```sh
./testunhandled
libc++abi.dylib: terminating with uncaught exception of type int
Abort trap: 6
```
C#:
```sh
dotnet testunhandled.dll
Unhandled Exception: System.Exception: e
   at testunhandled.Program.Main(String[] args) in /Users/janvorli/test/testunhandled/Program.cs:line 9
Abort trap: 6
```

**Comment by jkotas** [comment] 2020-12-08 15:34
My guess is that it is more likely caused by differences between signed vs. unsigned binaries. Crashes in signed binaries get special treatment. Can you try to sign your C++ binary to see whether it is going to make a difference?

**Comment by janvorli** [comment] 2020-12-08 15:50
On my mac, neither the c++ (even with signing) nor the .NET version displays any dialog. It might be caused by the fact that I have developer mode turned on.
@sgronblo can you please try to run `codesign -s - testunhandled` to sign the C++ compiled binary and then run it again to see if it produces the same dialog when running signed?

**Comment by sgronblo** [comment] 2020-12-14 08:28
I don't have experience with that so will take a bit of time to try it out. But if I write some dinky mini CLI tool and run it with `dotnet run` should that really deserve the full signed binary treatment?

**Comment by ldy985** [comment] 2021-03-04 20:09
I have a related problem on Windows where an application that just throws an exception never terminates. It remains in the background showing as "Suspended". This often causes msbuild to fail due to locked files.

**Comment by mangod9** [comment] 2021-07-10 00:15
Closing since this doesnt need any fixes on the runtime side.

**Closed by mangod9** 2021-07-10 00:15 UTC
Labels: area-VM-coreclr, question
