### ISSUE TITLE
.NET Core 3.1: Serializing a Stack<int> to JSON with JsonSerializer reverses the order of items in the stack upon deserialization.

### ISSUE THREAD

**Issue by dbc2** [dotnet/runtime#1316] opened 2020-01-06 03:33 UTC
If I have a [`Stack<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.stack-1) for some `T`, and round-trip it to JSON using the new [`System.Text.Json.JsonSerializer`](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer), the order of the items in the stack will be **reversed** after deserialization.

Details as follows.  I have a `Stack<int>` and push 3 values `1, 2, 3` onto it.  I then serialize it to JSON using `JsonSerializer`, which results in

    [3,2,1]

However, when I deserialize the JSON to a new stack, the integers in the stack are reversed, and a later assert that the stacks are sequentially equals fails:

	var stack = new Stack<int>(new [] { 1, 2, 3 });

	var json = JsonSerializer.Serialize(stack);
	
	var stack2 = JsonSerializer.Deserialize<Stack<int>>(json);
	
	var json2 = JsonSerializer.Serialize(stack2);
	
	Console.WriteLine("Serialized {0}:", stack);
	Console.WriteLine(json); // Prints [3,2,1]
	
	Console.WriteLine("Round-tripped {0}:", stack);
	Console.WriteLine(json2); // Prints [1,2,3]
	
	Assert.IsTrue(stack.SequenceEqual(stack2)); // Fails
	Assert.IsTrue(json == json2);               // Also fails

Demo fiddle [here](https://dotnetfiddle.net/6LmXLm).
 
Some investigation shows that there is some code in [`CreateDerivedEnumerableInstance(ref ReadStack state, JsonPropertyInfo collectionPropertyInfo, IList sourceList)`](https://github.com/dotnet/corefx/blob/v3.1.0/src/System.Text.Json/src/System/Text/Json/Serialization/JsonPropertyInfoCommon.cs#L150) to create a stack from a deserialized list:

    else if (instance is Stack<TDeclaredProperty> instanceOfStack)
    {
        foreach (TDeclaredProperty item in sourceList)
        {
            instanceOfStack.Push(item);
        }

        return instanceOfStack;
    }

However, it pushes them on in the wrong order, it needs to push them in reverse:

    else if (instance is Stack<TDeclaredProperty> instanceOfStack)
    {
        for (int i = sourceList.Count - 1; i >= 0; i--)
        {
            instanceOfStack.Push((TDeclaredProperty)sourceList[i]);
        }
        return instanceOfStack;
    }

Since there is some code that attempts to correctly deserialize `Stack<T>` I believe this is an actual bug not an enhancement.

Workaround is to create a  [custom `JsonConverter<Stack<T>>`](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonconverter-1) as shown in [this answer](https://stackoverflow.com/a/59604610/3744182) to [How can I serialize a Stack<T> to JSON using System.Text.Json without reversing the stack?](https://stackoverflow.com/q/59604609/3744182).

Incidentally, the code added to handle `Stack<T>`, while present in https://github.com/dotnet/corefx/blob/v3.1.0/src/System.Text.Json/src/System/Text/Json/Serialization/JsonPropertyInfoCommon.cs, seems not to be present in https://github.com/dotnet/runtime/blob/master/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonPropertyInfoCommon.cs.  So I don't know what would happen in the current development version.

**Comment by Tornhoof** [comment] 2020-01-06 10:39
See https://github.com/dotnet/corefx/issues/41887

**Comment by MihaZupan** [comment] 2020-01-06 12:13
Duplicate of dotnet/corefx#41887

**Closed by MihaZupan** 2020-01-06 12:13 UTC
Labels: area-System.Text.Json, untriaged
