### ISSUE TITLE
outerloop: System.IO.Tests on linux-musl-x64 AOT running into SIGKILL

### ISSUE THREAD

**Issue by am11** [dotnet/runtime#102800] opened 2024-05-29 08:21 UTC
From main branch: https://dev.azure.com/dnceng-public/public/_build/results?buildId=689281&view=logs&j=20e6f673-0b0c-5c85-377c-5d941d4c8ee3&t=5801e1cc-59c5-5e47-8484-142b970afd58

console logs: https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-heads-main-9fc74348a0df49998b/System.IO.Tests/1/console.69ead1c7.log?helixlogtype=result

```sh
[SKIP] System.IO.Tests.TextWriterTests.CreateBroadcasting_AllMethodsOverridden
./RunTests.sh: line 179:    21 Killed                  ./System.IO.Tests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -xml testResults.xml $RSP_FILE
/root/helix/work/workitem/e
----- end Tue May 28 10:50:09 UTC 2024 ----- exit code 137 ----------------------------------------------------------
exit code 137 means SIGKILL Killed either due to out of memory/resources (see /var/log/messages) or by explicit kill.
ulimit -c value: unlimited
```

**Comment by am11** [comment] 2024-05-29 09:33
Maybe we can turn it into a tracking issue with `Known Build Error` label, so Build Analysis doesn't fail in PRs?

**Comment by MichalStrehovsky** [comment] 2024-05-29 09:35
Build analysis doesn't look at runtime-nativeaot-outerloop pipeline.

**Comment by am11** [comment] 2024-05-29 10:43
Ah ok. I saw https://github.com/dotnet/runtime/issues/98964 (outerloop, tracking and with known-build-error label), so I thought that's the way.  Since this is failing in CI, lets keep it opened so others' PR won't get blocked?

**Comment by MichalStrehovsky** [comment] 2024-05-29 11:14
Yep, I agree it should be open. Just don't know what to do with it :).

**Comment by jkotas** [comment] 2024-07-03 01:16
This is not specific to native AOT. Duplicate of #100558

**Closed by jkotas** 2024-07-03 01:16 UTC
Labels: blocking-outerloop, os-linux-musl, area-NativeAOT-coreclr
