### ISSUE TITLE
NativeAOT: Compiler produce warnings

### ISSUE THREAD

**Issue by kant2002** [dotnet/runtime#64824] opened 2022-02-04 19:34 UTC
### Description

During publishing of StructuredLogViewer.Avalonia with latest package from the dotnet7 feed I receive following warnings from compiler
```
  ILC: Method '[System.Reactive]System.Reactive.Concurrency.CatchScheduler`1+CatchSchedulerPeriodic+PeriodicallyScheduledWorkItem`1<System.__Canon,System.__Canon>.Tick(__Canon)' will always throw because: Invalid IL or CLR metadata
  ILC: Method '[System.Reactive]System.Reactive.Concurrency.CatchScheduler`1+CatchSchedulerPeriodic+PeriodicallyScheduledWorkItem`1<System.__Canon,System.ValueTuple`2<System.__Canon,System.__Canon>>.Tick(ValueTuple`2<__Canon,__Canon>)' will always throw because: Invalid IL or CLR metadata
```

~~Package from experimental feed does not have this warnings.~~ Package from experimental feed also has this problem.

This error coming for this method
https://github.com/dotnet/reactive/blob/9f2a8090cea4bf931d4ac3ad071f4df147f4df50/Rx.NET/Source/src/System.Reactive/Concurrency/CatchScheduler.cs#L120

### Reproduction Steps

I'm yet to provide minimal repo.

```
git clone https://github.com/kant2002/MSBuildStructuredLog.git
git switch kant/publish-nativeaot
dotnet publish -c Release -r linux-x64 -p:PublishNativeAot=True src/StructuredLogViewer.Avalonia/StructuredLogViewer.Avalonia.csproj
```

### Expected behavior

I think method should compile just fine.

### Actual behavior

ILC chokes on the specific method.

**Comment by MichalStrehovsky** [comment] 2022-02-04 22:22
On a phone now, but I'm pretty sure that's a `catch (T)` in shared code. We have a bug and blocked tests for this.

**Comment by MichalStrehovsky** [comment] 2022-02-05 04:00
Yeah `catch (TException exception)`. Duplicate of https://github.com/dotnet/runtimelab/issues/204.

**Closed by MichalStrehovsky** 2022-02-05 04:00 UTC
Labels: untriaged, area-NativeAOT-coreclr
