### ISSUE TITLE
Install-Package: Dependency loop detected for package 'System.Text.Encoding.CodePages'.

### ISSUE THREAD

**Issue by ZzZombo** [dotnet/runtime#79688] opened 2022-12-15 02:54 UTC
### Description

Attempting to install this package directly or as a dependency fails with this message. I used the NuGet package provider of PowerShell.

### Reproduction Steps

Run this command in PowerShell Core:

`> Install-Package AngleSharp -Scope CurrentUser`

It's the original package that depends on this one, and this error leads to a failure.

### Expected behavior

The package installs fine.

### Actual behavior

The installation fails due to a dependency loop. Installing just the `System.Text.Encoding.CodePages` directly also fails in the same way.

### Configuration

```
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Other information

The issue also affects other users, see https://github.com/AngleSharp/AngleSharp/issues/925.

**Comment by tarekgh** [comment] 2023-01-04 21:30
I don't think there is any problem with `System.Text.Encoding.CodePages` itself. Using nuget.exe just resolves the dependencies correctly. Could be `Install-package` command issue in PS?

@ericstj any thoughts around that? 

```
nuget.exe install System.Text.Encoding.CodePages
Feeds used:
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
  https://api.nuget.org/v3/index.json
  https://aka.ms/skiasharp-eap/index.json

Installing package 'System.Text.Encoding.CodePages' to 'C:\Users\tito'.
  GET https://api.nuget.org/v3/registration5-gz-semver2/system.text.encoding.codepages/index.json
  OK https://api.nuget.org/v3/registration5-gz-semver2/system.text.encoding.codepages/index.json 73ms
  GET https://pkgs.dev.azure.com/xamarin/6fd3d886-57a5-4e31-8db7-52a1b47c07a8/_packaging/737d9830-bed0-4b55-8699-c93e7b529ed0/nuget/v3/registrations2-semver2/system.text.encoding.codepages/index.json
  NotFound https://pkgs.dev.azure.com/xamarin/6fd3d886-57a5-4e31-8db7-52a1b47c07a8/_packaging/737d9830-bed0-4b55-8699-c93e7b529ed0/nuget/v3/registrations2-semver2/system.text.encoding.codepages/index.json 90ms

Attempting to gather dependency information for package 'System.Text.Encoding.CodePages.7.0.0' with respect to project 'C:\Users\tito', targeting 'Any,Version=v0.0'
Gathering dependency information took 2.77 sec
Attempting to resolve dependencies for package 'System.Text.Encoding.CodePages.7.0.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'System.Text.Encoding.CodePages.7.0.0'
Resolved actions to install package 'System.Text.Encoding.CodePages.7.0.0'
Retrieving package 'System.Buffers 4.5.1' from 'NuGet.org'.
Retrieving package 'System.Memory 4.5.5' from 'NuGet.org'.
Retrieving package 'System.Numerics.Vectors 4.5.0' from 'NuGet.org'.
Retrieving package 'System.Runtime.CompilerServices.Unsafe 6.0.0' from 'NuGet.org'.
Retrieving package 'System.Text.Encoding.CodePages 7.0.0' from 'NuGet.org'.
Adding package 'System.Buffers.4.5.1' to folder 'C:\Users\tito'
Added package 'System.Buffers.4.5.1' to folder 'C:\Users\tito'
Successfully installed 'System.Buffers 4.5.1' to C:\Users\tito
Adding package 'System.Numerics.Vectors.4.5.0' to folder 'C:\Users\tito'
Added package 'System.Numerics.Vectors.4.5.0' to folder 'C:\Users\tito'
Successfully installed 'System.Numerics.Vectors 4.5.0' to C:\Users\tito
Adding package 'System.Runtime.CompilerServices.Unsafe.6.0.0' to folder 'C:\Users\tito'
Added package 'System.Runtime.CompilerServices.Unsafe.6.0.0' to folder 'C:\Users\tito'
Successfully installed 'System.Runtime.CompilerServices.Unsafe 6.0.0' to C:\Users\tito
Adding package 'System.Memory.4.5.5' to folder 'C:\Users\tito'
Added package 'System.Memory.4.5.5' to folder 'C:\Users\tito'
Successfully installed 'System.Memory 4.5.5' to C:\Users\tito
Adding package 'System.Text.Encoding.CodePages.7.0.0' to folder 'C:\Users\tito'
Added package 'System.Text.Encoding.CodePages.7.0.0' to folder 'C:\Users\tito'
Successfully installed 'System.Text.Encoding.CodePages 7.0.0' to C:\Users\tito
Executing nuget actions took 539 ms
```

**Comment by ericstj** [comment] 2023-01-04 22:31
I looked at this a few years ago and shared this: https://github.com/dotnet/runtime/issues/31065#issuecomment-538513691

I can't find any other issue opened as a result of that report, but the problem is in the implementation of that `Install-Package` cmdlet.

**Comment by tarekgh** [comment] 2023-01-04 23:23
@ZzZombo I am closing the issue here. Feel free to log the issue to PS to try get the cmdlet fixed. Maybe the workaround here is to use `nuget cli` instead for now.

**Closed by tarekgh** 2023-01-04 23:23 UTC
Labels: area-System.Text.Encoding
