### ISSUE TITLE
Test failure Regressions/coreclr/GitHub_42732/test42732/test42732.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#71755] opened 2022-07-07 07:30 UTC
Run: [runtime-coreclr outerloop 20220706.5](https://dev.azure.com/dnceng/public/_build/results?buildId=1864871&view=ms.vss-test-web.build-test-results-tab&runId=48947350&resultId=109601&paneView=debug)

Failed test:
```
R2R-CG2 Linux x64 Checked no_tiered_compilation @ (Alpine.314.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64-20210910135833-1848e19

- Regressions/coreclr/GitHub_42732/test42732/test42732.sh
- JIT/Directed/TypedReference/TypedReference/TypedReference.sh

R2R-CG2 Linux x64 Checked @ (Alpine.314.Amd64.Open)Ubuntu.1804.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-amd64-20210910135833-1848e19

- Regressions/coreclr/GitHub_42732/test42732/test42732.sh
- JIT/Directed/TypedReference/TypedReference/TypedReference.sh

R2R-CG2 Linux x64 Checked no_tiered_compilation @ Ubuntu.1804.Amd64.Open

- Regressions/coreclr/GitHub_42732/test42732/test42732.sh
- JIT/Directed/TypedReference/TypedReference/TypedReference.sh

R2R-CG2 Linux x64 Checked @ Ubuntu.1804.Amd64.Open

- Regressions/coreclr/GitHub_42732/test42732/test42732.sh
- JIT/Directed/TypedReference/TypedReference/TypedReference.sh

R2R-CG2 OSX x64 Checked @ OSX.1200.Amd64.Open

- Regressions/coreclr/GitHub_42732/test42732/test42732.sh
- JIT/Directed/TypedReference/TypedReference/TypedReference.sh

```
**Error message:**
```
/root/helix/work/workitem/e/Regressions/coreclr/GitHub_42732/test42732/test42732.sh: line 249: -r:/root/helix/work/workitem/e/Regressions/coreclr/GitHub_42732/test42732/IL-CG2/*.dll: No such file or directory

Assert failure(PID 24103 [0x00005e27], Thread: 24103 [0x5e27]): decoderNew.ReadToken() == decoderExisting.ReadToken()
File: /__w/1/s/src/coreclr/vm/frames.cpp Line: 2089
Image: /root/helix/work/correlation/corerun

/root/helix/work/workitem/e/Regressions/coreclr/GitHub_42732/test42732/test42732.sh: line 382: 24103 Aborted                 (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/Regressions.coreclr/GitHub_42732/test42732/test42732.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/root/helix/work/workitem/e/Regressions/coreclr/GitHub_42732/test42732/IL-CG2/TestLibrary.dll
03:53:01
Response file: /root/helix/work/workitem/e/Regressions/coreclr/GitHub_42732/test42732/TestLibrary.dll.rsp
/root/helix/work/workitem/e/Regressions/coreclr/GitHub_42732/test42732/IL-CG2/TestLibrary.dll
-o:/root/helix/work/workitem/e/Regressions/coreclr/GitHub_42732/test42732/TestLibrary.dll
-r:/root/helix/work/correlation/System..dll
-r:/root/helix/work/correlation/Microsoft..dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--targetarch:x64
-O
Running CrossGen2:  dotnet /root/helix/work/correlation/crossgen2/crossgen2.dll @/root/helix/work/workitem/e/Regressions/coreclr/GitHub_42732/test42732/TestLibrary.dll.rsp

Emitting R2R PE file: /root/helix/work/workitem/e/Regressions/coreclr/GitHub_42732/test42732/TestLibrary.dll
03:53:04
/root/helix/work/workitem/e/Regressions/coreclr/GitHub_42732/test42732/IL-CG2/test42732.dll
03:53:04
Response file: /root/helix/work/workitem/e/Regressions/coreclr/GitHub_42732/test42732/test42732.dll.rsp
/root/helix/work/workitem/e/Regressions/coreclr/GitHub_42732/test42732/IL-CG2/test42732.dll
-o:/root/helix/work/workitem/e/Regressions/coreclr/GitHub_42732/test42732/test42732.dll
-r:/root/helix/work/correlation/System..dll
-r:/root/helix/work/correlation/Microsoft..dll
-r:/root/helix/work/correlation/mscorlib.dll
--verify-type-and-field-layout
--targetarch:x64
-O
Running CrossGen2:  dotnet /root/helix/work/correlation/crossgen2/crossgen2.dll @/root/helix/work/workitem/e/Regressions/coreclr/GitHub_42732/test42732/test42732.dll.rsp

Emitting R2R PE file: /root/helix/work/workitem/e/Regressions/coreclr/GitHub_42732/test42732/test42732.dll
03:53:07
in ReleaseLock
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false test42732.dll ''
About to run test
[createdump] Gathering state for process 24103 corerun
[createdump] Crashing thread 00005e27 signal 00000006
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.24103.dmp
[createdump] Written 97488896 bytes (23801 pages) to core file
[createdump] Dump successfully written
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/e/Regressions/coreclr/GitHub_42732/test42732/test42732.sh
Expected: True
Actual:   False
```

**Comment by shimingsg** [comment] 2022-08-05 07:48
Failed again in: [runtime-coreclr outerloop 20220804.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1924538&view=ms.vss-test-web.build-test-results-tab&runId=49806456&paneView=debug&resultId=110486)

Failed test:
```
coreclr Linux arm Checked no_tiered_compilation @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- GC/API/GC/GetGCMemoryInfo/GetGCMemoryInfo.sh
- JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b65423/b65423/b65423.sh
- JIT/Directed/ExcepFilters/mixed/mixed/mixed.sh

coreclr Linux arm Checked @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440
- GC/API/GC/GetGCMemoryInfo/GetGCMemoryInfo.sh

coreclr Linux arm Checked no_tiered_compilation @ (Alpine.314.Arm32.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm32v7-20210910135806-8a6f4f3
- GC/API/GC/GetGCMemoryInfo/GetGCMemoryInfo.sh
- JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b65423/b65423/b65423.sh
- JIT/Directed/ExcepFilters/mixed/mixed/mixed.sh

coreclr Linux arm Checked @ (Alpine.314.Arm32.Open)Ubuntu.1804.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.14-helix-arm32v7-20210910135806-8a6f4f3
- GC/API/GC/GetGCMemoryInfo/GetGCMemoryInfo.sh
```
**Error message:**
```
/root/helix/work/workitem/e/GC/API/GC/GetGCMemoryInfo/GetGCMemoryInfo.sh: line 391:  3302 Segmentation fault      (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/GC.API/GC/GetGCMemoryInfo/GetGCMemoryInfo.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false GetGCMemoryInfo.dll ''
caught arg exception as expected: System.ArgumentOutOfRangeException: Argument must be between Any and Background. (Parameter 'kind')
at System.GC.GetGCMemoryInfo(GCKind kind)
at Test_GetGCMemoryInfo.Main()
[createdump] Gathering state for process 3302 corerun
[createdump] Crashing thread 00000ce6 signal 0000000b
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.3302.dmp
[createdump] Written 80973824 bytes (19769 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 2762ms
Expected: 100
Actual: 139
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/e/GC/API/GC/GetGCMemoryInfo/GetGCMemoryInfo.sh
Expected: True
Actual:   False


Stack trace
   at GC_API._GC_GetGCMemoryInfo_GetGCMemoryInfo_._GC_GetGCMemoryInfo_GetGCMemoryInfo_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by mangod9** [comment] 2022-08-09 16:41
this is a dupe of #73247 which is being investigated.

**Closed by mangod9** 2022-08-09 16:41 UTC
Labels: os-linux, os-mac-os-x, arch-x64, area-crossgen2-coreclr, blocking-outerloop
