### ISSUE TITLE
MethodCallExpression constructor not decorated with protected

### ISSUE THREAD

**Issue by kccarter76** [dotnet/runtime#38789] opened 2020-07-05 05:30 UTC
### Description

The class System.Linq.Expression.MethodCallExpression cannot be used as a base class outside of the runtime.

the constructor is decorated as internal instead of protected internal.

I believe this to be a bug because the class is not sealed.

I am working my own DAL and I am trying to work past a WhereEnumerable Exception and one of my ideas was to inherit from MethodCallExpression and this is where I learned that I can't use it because of how the constructor is decorated.

### Configuration

.NetStandard 2.x

Architecture is AnyCpu

### Regression?

I believe the previous iterations have always been like this.

**Comment by stephentoub** [comment] 2020-07-05 10:48
> the constructor is decorated as internal instead of protected internal. I believe this to be a bug because the class is not sealed.

It's not a bug.  This approach is often used when a library isn't designed for a type to be externally constructed or derived from but itself needs to have derived types, often as an implementation detail (as is the case here, with all of the derived types being internal).

**Comment by kccarter76** [comment] 2020-07-05 22:05
This approach makes it impossible to use this class beyond the runtime as a base class to expand on method call expression which would be useful for my project. With things the way they are. I essentially have to re-invent a wheel plus the undercarriage as well. protected internal provides everything the runtime needs plus making possible for 3rd party development to experiment through polymorphism.

**Comment by GrabYourPitchforks** [comment] 2020-07-06 00:59
Making a class properly polymorphic isn't a light undertaking. With LINQ in particular, the infrastructure has dependencies on the concrete implementations of many of the derived types. Adding virtual members to any type requires a very deep analysis of the various scenarios the type designer wants to allow, including whether the overall library will continue to work in the face of customized behaviors. It also requires a bit of clairvoyance to predict which future scenarios might be permanently foreclosed once these extensibility points become locked in place.

I don't know enough about the Expressions library to say whether this is or is not viable in the long term. But I hope it conveys that any work along these lines isn't as simple as changing the accessibility of one or two members.

**Comment by kccarter76** [comment] 2020-07-06 05:00
I have put together a expression that for the most part replicates MethodCallExpression with the additions I want. 
I have added overrides for CanReduce and Reduce(). That will reduce my expression to a MethodCallExpression using Expression.Call(method, arguments). time will tell if it meets my needs in the mean time. It would be simpler if I could properly inherit from the class.

**Comment by jaredpar** [comment] 2020-07-09 00:11
Closing. As @stephentoub noted this is not a bug.

**Closed by jaredpar** 2020-07-09 00:11 UTC
Labels: area-System.Linq.Expressions, untriaged

**Comment by kccarter76** [comment] 2020-07-09 00:14
well it could be transformed into an enhancement.

**Comment by jaredpar** [comment] 2020-07-09 00:54
This particular library is effectively archived. Even as an enhancement it would not meet the bar.
