### ISSUE TITLE
StringComparison.InvariantCulture behavior change between .NET Core 3.1 and .NET 5

### ISSUE THREAD

**Issue by Zintom** [dotnet/runtime#44687] opened 2020-11-14 17:35 UTC
### Description

Using `StringComparison.InvariantCulture` on `string.LastIndexOf(string, comparison)` returns different results in .NET 5 compared to .NET Core 3.1 when looking for the index of a unicode character.

Witness the following code:
```
string specialChar = "\u007f";
string testString = "hello" + specialChar + "world";

Debug.Assert(testString.LastIndexOf(specialChar) == 5);
```

On .NET Core 3.1, this assertion is `true`, whereas in .NET 5 this assertion is `false`. In fact, in .NET 5, the `LastIndexOf` method is returning the index of the end of the string whereas in 3.1 it is correctly returning "`5`".

### Supposition
I have tried source stepping into the `LastIndexOf` method but frankly, I do not understand it well enough to make an informed analysis of why this happens :( My supposition is that is something to do with `InvariantCulture` and Unicode, because if I change the comparison mode to Ordinal, the assertion is correct in both .NET versions.

**Comment by EgorBo** [comment] 2020-11-14 17:39
ICU-related, doesn't reproduce with
```
<RuntimeHostConfigurationOption Include="System.Globalization.UseNls" Value="true" />
```

**Comment by Zintom** [comment] 2020-11-14 17:45
@EgorBo thanks for the snappy response 😀

Can I ask why this behavior was changed? The MS [Docs](https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/globalization-icu) state that you now **have** to use Ordinal to correctly check the index of a string within a string, surely that just adds extra boilerplate code? Or is there something I'm missing?

**Comment by EgorBo** [comment] 2020-11-14 17:48
@Zintom ah no, it's just a note 🙂 
Looks like it's the same as https://github.com/dotnet/runtime/issues/44439

**Comment by Zintom** [comment] 2020-11-14 17:57
@EgorBo oh I see, I'm somewhat of a noob to GitHub 😁

**Comment by safern** [comment] 2020-11-14 18:32
Thanks @Zintom for reporting the issue. I'm closing it as a dupe of: https://github.com/dotnet/runtime/issues/44439

Also please look at this issue last comment explaining the reasoning behind the change and we're pointing to the docs that we wrote about the change: https://github.com/dotnet/runtime/issues/43736

But long story short the reason why we recommend using Ordinal is because culture aware comparisons my give different results in different machines. Also please see: https://github.com/dotnet/runtime/issues/43956 which explains why there is a lot of confusion in our APIs since some are Ordinal by default and some culture-aware.

As a workaround for now you can switch back to NLS or use Ordinal comparison.

**Closed by safern** 2020-11-14 18:32 UTC
Labels: area-System.Globalization, untriaged

**Comment by GrabYourPitchforks** [comment] 2020-11-14 20:16
This is __not__ a dupe of https://github.com/dotnet/runtime/issues/44439. It is instead a dupe of https://github.com/dotnet/runtime/issues/43736.

**Comment by safern** [comment] 2020-11-14 21:30
Thanks, @GrabYourPitchforks for elaborating.

**Comment by Zintom** [comment] 2020-11-14 21:51
Yeah my bad @GrabYourPitchforks
