### ISSUE TITLE
Test failure JIT\\jit64\\opt\\inl\\caninline_ro\\caninline_ro.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#65647] opened 2022-02-21 01:52 UTC
Run: [runtime-coreclr r2r-extra 20220219.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1623130&view=ms.vss-test-web.build-test-results-tab&runId=45103130&paneView=debug&resultId=100667)

Failed test:
```
R2R windows x64 Checked jitstress2_tiered @ Windows.10.Amd64.Open

- JIT\\jit64\\opt\\inl\\caninline_ro\\caninline_ro.cmd
- JIT\\jit64\\opt\\cg\\il\\ldftn_impl\\ldftn_impl.cmd
- JIT\\jit64\\opt\\cse\\HugeField1\\HugeField1.cmd
- JIT\\jit64\\opt\\cg\\cgstress\\CgStress1_do\\CgStress1_do.cmd
- JIT\\jit64\\opt\\cg\\cgstress\\CgStress3_r\\CgStress3_r.cmd
- JIT\\jit64\\opt\\cse\\VolatileTest_op_shr\\VolatileTest_op_shr.cmd
- JIT\\jit64\\opt\\cse\\volatilestaticfield\\volatilestaticfield.cmd
- JIT\\jit64\\opt\\regress\\vswhidbey\\223862\\div_dbg\\div_dbg.cmd
- JIT\\jit64\\opt\\cse\\VolatileTest_op_mul\\VolatileTest_op_mul.cmd
- JIT\\jit64\\opt\\**

```
**Error message:**
```
Could Not Find C:\h\w\A7B708FE\w\BF6F09B7\e\JIT\jit64\opt\inl\caninline_ro\IL-CG2\composite-r2r.dll
Could Not Find C:\h\w\A7B708FE\w\BF6F09B7\e\JIT\jit64\opt\inl\caninline_ro\caninline_ro.dll.rsp
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'System.IO.MemoryMappedFiles, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The module was expected to contain an assembly manifest.
File name: 'System.IO.MemoryMappedFiles, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
at ILCompiler.CompilerTypeSystemContext.AddModule(String filePath, String expectedSimpleName, Boolean useForBinding, ModuleData oldModuleData)
at ILCompiler.CompilerTypeSystemContext.GetOrAddModuleFromPath(String filePath, Boolean useForBinding)
at ILCompiler.Program.Run(String[] args)
at ILCompiler.Program.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\A7B708FE\w\BF6F09B7\uploads\Reports\JIT.jit64\opt\inl\caninline_ro\caninline_ro.output.txt
Raw output:
BEGIN EXECUTION
caninline_ro.dll
1 file(s) copied.
Response file: C:\h\w\A7B708FE\w\BF6F09B7\e\JIT\jit64\opt\inl\caninline_ro\caninline_ro.dll.rsp
C:\h\w\A7B708FE\w\BF6F09B7\e\JIT\jit64\opt\inl\caninline_ro\IL-CG2\caninline_ro.dll
-o:C:\h\w\A7B708FE\w\BF6F09B7\e\JIT\jit64\opt\inl\caninline_ro\caninline_ro.dll
--targetarch:x64
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\A7B708FE\p\System..dll
-r:C:\h\w\A7B708FE\p\Microsoft..dll
-r:C:\h\w\A7B708FE\p\mscorlib.dll
-r:C:\h\w\A7B708FE\p\netstandard.dll
-O
" "dotnet" "C:\h\w\A7B708FE\p\crossgen2\crossgen2.dll" @"C:\h\w\A7B708FE\w\BF6F09B7\e\JIT\jit64\opt\inl\caninline_ro\caninline_ro.dll.rsp"   -r:C:\h\w\A7B708FE\w\BF6F09B7\e\JIT\jit64\opt\inl\caninline_ro\IL-CG2*.dll"
Crossgen2 failed with exitcode - -532462766
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\A7B708FE\p
C:\h\w\A7B708FE\w\BF6F09B7\e\JIT\jit64\opt\inl\caninline_ro\caninline_ro.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_jit64._opt_inl_caninline_ro_caninline_ro_._opt_inl_caninline_ro_caninline_ro_cmd()
```

**Comment by EgorBo** [comment] 2022-02-24 23:03
doesn't look like a codegen issue

**Comment by trylek** [comment] 2022-04-04 20:31
Closing as duplicate of: https://github.com/dotnet/runtime/issues/65646

**Closed by trylek** 2022-04-04 20:31 UTC
Labels: os-windows, JitStress, arch-x64, area-crossgen2-coreclr
