### ISSUE TITLE
[API Proposal]: Add more parameters on the CreateClient from the IHttpClientFactory

### ISSUE THREAD

**Issue by wreuel** [dotnet/runtime#107552] opened 2024-09-09 15:30 UTC
### Background and motivation

There are times when you need to call a Web API that requires NetworkCredentials, which can be challenging, especially when adding a new client to an already running application. Moreover, ensuring that this client is available throughout the application via Dependency Injection adds complexity. While it's generally not possible to register new services in a running application, I’ve implemented a workaround, which I’ll explain below.

This version is more concise and structured while conveying the same idea.

```csharp
using System.Collections.Concurrent;
using System.Net;
using System.Net.Http.Headers;

public class HttpClientManager : IHttpClientManager
{
	private readonly IHttpClientFactory _httpClientFactory;
	private readonly ConcurrentDictionary<string, HttpClient> _httpClients;

	public HttpClientManager(IHttpClientFactory httpClientFactory)
	{
		_httpClientFactory = httpClientFactory ?? throw new ArgumentNullException(nameof(httpClientFactory));
		_httpClients = [];
	}

	public HttpClient GetOrCreateClient(WebServiceConfig webServiceConfig)
	{
	   
		if (_httpClients.ContainsKey(webServiceConfig.Id))
		{
			return _httpClients[webServiceConfig.Id];
		}

		CreateUpdateHttpClient(webServiceConfig);

		return _httpClients[webServiceConfig.Id];
	}

	public void UpdateClient(WebServiceConfig webServiceConfig)
	{
		if (_httpClients.ContainsKey(webServiceConfig.Id))
		{
			CreateUpdateHttpClient(webServiceConfig);
		}
	}

	private void CreateUpdateHttpClient(WebServiceConfig webServiceConfig)
	{
		switch (webServiceConfig.ConnectionType)
		{
			case Common.Enum.ConnectionType.SOAP:
				var handler = new HttpClientHandler()
				{
					Credentials = new NetworkCredential(webServiceConfig.User, webServiceConfig.PwdDecrypted(), webServiceConfig.Domain)
				};

				var client = new HttpClient(handler)
				{
					BaseAddress = new Uri(webServiceConfig.Url),
				};

				client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue(Constants.APP_JSON));

				if (_httpClients.ContainsKey(webServiceConfig.Id))
				{
					_httpClients[webServiceConfig.Id].Dispose();
				}

				_httpClients[webServiceConfig.Id] = client;

				break;
		}
	}
}
```

### API Proposal

Today we have the methdo called CreateClient, so we should add a overload for that.

```csharp
namespace System.Collections.Generic;

public interface IHttpClientFactory
{
    HttpClient CreateClient(string name);
    HttpClient CreateClient(string name, NetworkCredential credentials);
}
```

### API Usage

```csharp
// Fancy the value
public class HttpClientManager 
{
	private readonly IHttpClientFactory _httpClientFactory;
	private readonly ConcurrentDictionary<string, HttpClient> _httpClients;

	public HttpClientManager(IHttpClientFactory httpClientFactory)
	{
		_httpClientFactory = httpClientFactory ?? throw new ArgumentNullException(nameof(httpClientFactory));
		_httpClients = [];
	}

	public HttpClient GetOrCreateClient(WebServiceConfig webServiceConfig)
	{
	   
		if (_httpClients.ContainsKey(webServiceConfig.Id))
		{
			return _httpClients[webServiceConfig.Id];
		}

		CreateUpdateHttpClient(webServiceConfig);

		return _httpClients[webServiceConfig.Id];
	}

	private void CreateUpdateHttpClient(WebServiceConfig webServiceConfig)
	{
		var client = _httpClientFactory.CreateClient(webServiceConfig.Id, new NetworkCredential(webServiceConfig.User, webServiceConfig.PwdDecrypted(), webServiceConfig.Domain));
		_httpClients[webServiceConfig.Id] = client;
	}
}

```

**Comment by julealgon** [comment] 2024-09-09 16:20
I think you are misunderstanding how `HttpClient` should be configured when using `IHttpClientFactory`. If you were to include all potential configurations that people use in DI in the factory interface, it would become completely unusable due to how complex the overloads would be.

Just use the DI builders instead and configure the handler there.

**Comment by wreuel** [comment] 2024-09-09 16:36
> I think you are misunderstanding how `HttpClient` should be configured when using `IHttpClientFactory`. If you were to include all potential configurations that people use in DI in the factory interface, it would become completely unusable due to how complex the overloads would be.
> 
> 
> 
> Just use the DI builders instead and configure the handler there.

I would say that, not really, and don't get me wrong! What I want in the end is to have a way of adding HttpClients after the application is running, and have that available.

**Comment by joegoldman2** [comment] 2024-09-09 16:54
The issue lacks details but if your credentials are dynamic and can be added to the configuration once the application is already running, just combine `ConfigurePrimaryHttpMessageHandler` and `IOptionsMonitor` this way:

```cs
var services = new ServiceCollection();

services.AddHttpClient<MyTypedClient>()
    .ConfigurePrimaryHttpMessageHandler(serviceProvider =>
    {
        var options = serviceProvider.GetRequiredService<IOptionsMonitor<WebServiceConfig>>().CurrentValue;
        return new SocketsHttpHandler { Credentials = new NetworkCredential(...) };
    });
```

**Comment by wreuel** [comment] 2024-09-09 17:58
> The issue lacks details but if your credentials are dynamic and can be added to the configuration once the application is already running, just combine `ConfigurePrimaryHttpMessageHandler` and `IOptionsMonitor` this way:
> 
> ```cs
> var services = new ServiceCollection();
> 
> services.AddHttpClient<MyTypedClient>()
>     .ConfigurePrimaryHttpMessageHandler(serviceProvider =>
>     {
>         var options = serviceProvider.GetRequiredService<IOptionsMonitor<WebServiceConfig>>().CurrentValue;
>         return new SocketsHttpHandler { Credentials = new NetworkCredential(...) };
>     });
> ```

That would even work, and I've used it before, but what I want is to add new HttpClients, which should be available throughout the entire application. For example, I will connect to WebSite1 using User1 and Pwd1, and then the user goes to a page and adds another WebSite2 with User2 and Pwd2. This second one would then be available to the application without needing to restart to add it as a DI. I've already solved the part of making it available, but what I wanted was to make CreateClient offer the convenience of passing the credentials. I think I was a bit clearer this time.

**Comment by CarnaViire** [comment] 2024-09-10 22:50
> That would even work, and I've used it before, but what I want is to add new HttpClients, which should be available throughout the entire application. For example, I will connect to WebSite1 using User1 and Pwd1, and then the user goes to a page and adds another WebSite2 with User2 and Pwd2. This second one would then be available to the application without needing to restart to add it as a DI. 

The core problem seems to be similar to https://github.com/dotnet/runtime/issues/36378 and https://github.com/dotnet/runtime/issues/35997

Is that correct @wreuel?

**Comment by wreuel** [comment] 2024-09-11 09:25
> > That would even work, and I've used it before, but what I want is to add new HttpClients, which should be available throughout the entire application. For example, I will connect to WebSite1 using User1 and Pwd1, and then the user goes to a page and adds another WebSite2 with User2 and Pwd2. This second one would then be available to the application without needing to restart to add it as a DI.
> 
> The core problem seems to be similar to #36378 and #35997
> 
> Is that correct @wreuel?

You are 100% @CarnaViire, the issues that you mentioned even have some code really similar to the one that I have created, to solve my problem! I can say that they are really similar.

**Comment by CarnaViire** [comment] 2024-09-11 18:16
I will then close this one as a duplicate @wreuel

**Comment by CarnaViire** [comment] 2024-09-11 18:16
Duplicate of https://github.com/dotnet/runtime/issues/36378

**Closed by CarnaViire** 2024-09-11 18:16 UTC
Labels: api-suggestion, area-Extensions-HttpClientFactory
