### ISSUE TITLE
Runtime crashing on startup on emulated x64-on-ARM64 Windows

### ISSUE THREAD

**Issue by v-ainigao** [dotnet/runtime#100425] opened 2024-03-14 07:56 UTC
Repro steps:
1. Install .net9preview3 X64 SDK from https://aka.ms/dotnet/9.0.1xx/daily/dotnet-sdk-win-x64.exe
2. Modify the environment variable path to x64 "C:\Program Files\dotnet\x64".
3. Create new console app.
`dotnet new console `

Expected Result:
Project can be created successfully.

Actual Result:
Creating project or build fails and will be blocking.
![image](https://github.com/dotnet/sdk/assets/106054229/450652a9-1f69-4573-8320-dfc8656c58af)
![image](https://github.com/dotnet/sdk/assets/106054229/be099a99-0475-4891-a0cb-f817b8fc3c7b)

dotnet --info
.NET SDK:
 Version:           9.0.100-preview.3.24163.23
 Commit:            33549194e2
 Workload version:  9.0.100-manifests.42eb89a3
 MSBuild version:   17.10.0-preview-24162-02+0326fd7c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\x64\sdk\9.0.100-preview.3.24163.23\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      9.0.0-preview.3.24162.24
  Architecture: x64
  Commit:       e4fceb3ae5

.NET SDKs installed:
  9.0.100-preview.3.24163.23 [C:\Program Files\dotnet\x64\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 9.0.0-preview.3.24162.20 [C:\Program Files\dotnet\x64\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 9.0.0-preview.3.24162.24 [C:\Program Files\dotnet\x64\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.3.24162.12 [C:\Program Files\dotnet\x64\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  arm64 [C:\Program Files\dotnet]
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by v-ainigao** [comment] 2024-04-01 06:48
This issue also repro's on .net9.0.100-preview.4.24181.1(runtime-9.0.0-preview.4.24178.9).
 ![image](https://github.com/dotnet/runtime/assets/106054229/e38d17ce-bf27-4153-97eb-291988cee2c7)

**Comment by mikem8361** [comment] 2024-04-01 20:35
We haven't had a chance to make any progress on this PR/arm64ec support.

**Comment by nagilson** [comment] 2024-04-01 20:37
@marcpopMSFT I wouldn't say this is blocking but if it's shipping like this we should probably create a known issue for it.

**Comment by v-ainigao** [comment] 2024-04-10 06:50
Today I did some sanity checks on the latest .net9preview4[9.0.100-preview.4.24209.11(runtime-9.0.0-preview.4.24204.3)] in CLI. This issue is fixed, so close it.
![image](https://github.com/dotnet/runtime/assets/106054229/15101ef2-2ef8-48ac-bb52-8f9fc17a325b)

**Comment by v-ainigao** [comment] 2024-04-16 07:19
Today I reproduced this issue again on the latest .net9.0.100-preview.4.24215.10(runtime-9.0.0-preview.4.24211.4)x64 SDK on ARM64OS, so I reopened it, can you help me take a look? @marcpopMSFT 
This memory dump file has been placed in this path. \\mlangfs1\public\v-aini\dump.zip
![image](https://github.com/dotnet/runtime/assets/106054229/e02e42dc-d396-4fde-b48d-052a89a87bd0)
dotnet --info is well.
![image](https://github.com/dotnet/runtime/assets/106054229/ac774254-36cd-48fb-be88-ca4da549fddc)

**Comment by v-ainigao** [comment] 2024-05-07 03:18
This issue repro on arm64os with .net9preview5 x64sdk.
![image](https://github.com/dotnet/runtime/assets/106054229/e41c5b8a-b1bb-4bc2-b4f4-3d3fb070a35b)

**Comment by tommcdon** [comment] 2024-05-07 16:03
I was able to reproduce the issue with an x64 sdk running on Windows arm64.  The issue does not reproduce `DOTNET_LegacyExceptionHandling=1` so the problem is evidently related to the new EH model.  @janvorli  would you mind taking a look?

**Comment by v-ainigao** [comment] 2024-05-13 05:22
This issue still repro's in the latest net9preview4 x64sdk on arm64OS.
SDK version:9.0.100-preview.4.24260.3
![image](https://github.com/dotnet/runtime/assets/106054229/6683219e-5ac4-4531-9ddb-f09009b3e4d1)

**Comment by janvorli** [comment] 2024-05-15 13:05
Windows developers helped me to investigate the issue. It turns out that it is a windows bug that is fixed in 24H2. So, the recommendation is to update Windows to this version. We will also add a workaround to runtime that will prevent using the Windows API with the bug when running x64 emulated on arm64 Windows on older Windows versions. But please note that this workaround may have some performance consequences in GC runtime suspension time in case of a lot of threads.

**Comment by v-ainigao** [comment] 2024-05-16 01:09
> Windows developers helped me to investigate the issue. It turns out that it is a windows bug that is fixed in 24H2. So, the recommendation is to update Windows to this version. We will also add a workaround to runtime that will prevent using the Windows API with the bug when running x64 emulated on arm64 Windows on older Windows versions. But please note that this workaround may have some performance consequences in GC runtime suspension time in case of a lot of threads.

Thank you for your explanation, but I can't create a 24h2 machine on Azure yet.

**Closed** 2024-05-16 22:24 UTC
Labels: area-ExceptionHandling-coreclr

**Comment by v-ainigao** [comment] 2024-05-23 07:23
This issue does not repro in the net9preview5 x64sdk on arm64OS.
SDK version:9.0.100-preview.5.24271.7(runtime-9.0.0-preview.5.24268.2)
![image](https://github.com/dotnet/runtime/assets/106054229/f767805c-1271-4b9f-b690-ddda84acadf4)
