### ISSUE TITLE
Building .NET 6 Blazor WebAssembly applications with .NET 7 SDK leads to errors and warnings

### ISSUE THREAD

**Issue by SteveSandersonMS** [dotnet/runtime#68896] opened 2022-05-05 10:25 UTC
### Description

As far as I'm aware, the normal SDK product goals include being able to build older applications. So, someone with the .NET 7 SDK should be able to build a .NET 6 application without making code changes.

Attempting to build a standard fresh-from-project-template Blazor WebAssembly .NET 6 application leads to errors if you have the WASM tools installed:

```
  Optimizing assemblies for size. This process might take a while.
  Optimizing assemblies for size may change the behavior of the app. Be sure to test after publishing. See: https://aka
  .ms/dotnet-illink
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.0-preview.3.22151.6\Sdk\WasmApp.Native.targets(
288,5): warning : Failed to generate icall function for method '[System.Private.CoreLib] System.Enum::InternalHasFlag'
because type 'System.Enum' is not supported for parameter named ''. Ignoring. [c:\path\TestApp\TestApp.csproj]
  Compiling native assets with emcc with -Oz. This may take a while ...
  [1/3] pinvoke.c -> pinvoke.o [took 0.87s]
  [2/3] corebindings.c -> corebindings.o [took 0.92s]
  [3/3] driver.c -> driver.o [took 1.03s]
  Linking with emcc with -O2. This may take a while ...
emcc : error : response file not found: C:\Users\username\.nuget\packages\microsoft.netcore.app.runtime.mono.browser-was
m\6.0.2\runtimes\browser-wasm\native\src\emcc-link.rsp [c:\path\TestApp\TestApp.csproj]
C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\7.0.0-preview.3.22151.6\Sdk\WasmApp.Native.targets(
409,5): error MSB3073: The command "emcc "@C:\Users\username\.nuget\packages\microsoft.netcore.app.runtime.mono.browser-
wasm\6.0.2\runtimes\browser-wasm\native\src\emcc-default.rsp" "@C:\Users\username\.nuget\packages\microsoft.netcore.app.
runtime.mono.browser-wasm\6.0.2\runtimes\browser-wasm\native\src\emcc-link.rsp" "@c:\path\TestApp\obj\Release\
net6.0\wasm\for-publish\emcc-link.rsp"" exited with code 1. [c:\path\TestApp\TestApp.csproj]
```

If you change the TFM to `net7.0`, it will build/publish successfully, but then at runtime the usage of `Microsoft.AspNetCore.Components.WebAssembly` version 6.0.0 will lead to warnings in the browser console:

```
global cwrap is obsolete, please use Module.cwrap instead     at http://127.0.0.1:8080/_framework/blazor.webassembly.js:1:37065        
global addRunDependency is obsolete, please use Module.addRunDependency instead     at h (http://127.0.0.1:8080/_framework/blazor.webassembly.js:1:42177)
global removeRunDependency is obsolete, please use Module.removeRunDependency instead 
```

### Reproduction Steps

Have an existing project targeting `net6.0` and using `Microsoft.AspNetCore.Components.WebAssembly` version `6.0.0`, and try to build and publish it using the .NET 7 SDK.

### Expected behavior

Existing 6.0 projects should build, publish, and run successfully without errors/warnings using the 7.0 SDK, even when using AOT or relinking.

### Actual behavior

Errors and warnings as described above.

### Regression?

Yes, there were no such errors/warnings from the 6.0 SDK.

### Known Workarounds

Developers have to update their app completely to 7.0 to use the 7.0 SDK.

**Comment by radical** [comment] 2022-05-05 17:02
https://github.com/dotnet/runtime/issues/65211

**Comment by radical** [comment] 2022-05-05 17:04
Closing this as dupe of https://github.com/dotnet/runtime/issues/65211 .

**Closed by radical** 2022-05-05 17:04 UTC
Labels: arch-wasm, untriaged, area-Build-mono
