### ISSUE TITLE
[API Proposal]: GetValueOrDefaultReference<T> for Nullable<T>

### ISSUE THREAD

**Issue by Sergio0694** [dotnet/runtime#64491] opened 2022-01-29 15:46 UTC
### Background and motivation

Follow from a conversation with @MichalStrehovsky.

The `CommunityToolkit.HighPerformance` package (previously named `Microsoft.Toolkit.HighPerformance`) has a [`NullableExtensions.GetValueOrDefaultReference` API](https://docs.microsoft.com/en-us/dotnet/api/microsoft.toolkit.highperformance.extensions.nullableextensions.dangerousgetvalueordefaultreference?view=win-comm-toolkit-dotnet-7.0#microsoft-toolkit-highperformance-extensions-nullableextensions-dangerousgetvalueordefaultreference-1(system-nullable((-0)))) to allow retrieving a `ref T` out of a `T?` value. This currently works, but the fact it relies on the internal layout of `Nullable<T>` makes it technically brittle. This is the last remaining API in the package that is relying on an internal implementation detail of the runtime/BCL, and it'd be nice to remove that one as well. Given this needs to be versioned with the BCL in order to be safe, the proposal is to move this API there.

For an example of use case scenario, @rickbrew is using this API in several places in his interop stack in Paint.NET.

I'd be happy to implement this if it gets past API review 😄

### API Proposal

```C#
namespace System.Runtime.InteropServices
{
    public static class NullableMarshal
    {
        public static ref T GetValueOrDefaultReference<T>(ref T? value) where T : struct;
    }
}
```

The semantics is: returns a ref to the backing field for the value, regardless of whether the nullable has value or not. It's conceptually like `Nullable<T>.GetValueOrDefault()`, except it returns a ref. This is enough of a basic building block to then allow developers to build their own wrappers on top of it (eg. returning a null ref if the nullable has no value).

I couldn't really find an existing type where it made sense to add this API in, so I went for a new `NullableMarshal` type for now. I'm sure a better idea for that will very likely come up during API review, so perfectly happy to see this moved around 😄

### API Usage

This is being done extensively in Paint.NET, through the APIs in the HighPerformance package. An API like `DangerousGetAddressOfValueOrNull` can then be safely built on top of the proposed `NullableMarshal.GetValueOrDefaultReference`, but with it being in the BCL guaranteeing that the layout will be handled correctly.

```C#
public void CopyFromBitmap(Point2Int32? destPoint, RectInt32? srcRect)
{
    HRESULT hr = this.pD2D1Bitmap->CopyFromBitmap(
        (D2D_POINT_2U*)destPoint.DangerousGetAddressOfValueOrNull(),
        spBitmap,
        d2dSrcRect.DangerousGetAddressOfValueOrNull());
    
    // Rest of the code...
}
```

### Alternative Designs

The alternative here would be to always make copies and do checks locally, like so:

```C#
public void CopyFromBitmap(Point2Int32? destPoint, RectInt32? srcRect)
{
    Point2Int32 dest = destPoint.GetValueOrDefault();
    RectInt32 src = srcRect.GetValueOrDefault();

    HRESULT hr = this.pD2D1Bitmap->CopyFromBitmap(
        (D2D_POINT_2U*)(destPoint.HasValue ? &dest : null),
        spBitmap,
        srcRect.HasValue : &src : null);
    
    // Rest of the code...
}
```

This is both more verbose, and slower, due to the additional copies.
This is particularly an issue if the struct is larger.
Also this cannot work if the input value is passed by `in` to save copies, as you'd be forced to do a copy anyway.

### Risks

Technically a dangerous API (though not to the level of others in the namespace) with a niche audience.

**Comment by rickbrew** [comment] 2022-01-29 15:48
Yes please, have all my upvotes, I'd very much like to not rely on brittle, undefined behavior for this!

**Comment by jkoritzinsky** [comment] 2022-01-29 18:27
This building block would also be useful for source-generated interop, so this proposal has my support.

**Comment by stephentoub** [comment] 2022-01-29 19:11
The proposed signature has a return type of `ref T`. Presumably either a) the method needs to set HasValue to true or b) return a `ref readonly T`?

**Comment by jkotas** [comment] 2022-01-29 19:14
Duplicate of https://github.com/dotnet/runtime/issues/1534 . This does not need to be an unsafe API if the returned reference is read-only.

**Comment by stephentoub** [comment] 2022-01-29 19:17
> This does not need to be an unsafe API if the returned reference is read-only.

I didn't notice this was being proposed as an XxMarshal method. Yeah, if we're going to add something for this, I'd much rather it be on Nullable and return ref readonly as I noted, in which case this should be closed as a dup. Someone who wants to cast away the readonlyness can do so with existing unsafe methods.

**Comment by stephentoub** [comment] 2022-01-29 19:29
Closing as a duplicate of #1534.

**Closed by stephentoub** 2022-01-29 19:29 UTC
Labels: api-suggestion, area-System.Runtime, untriaged
