### ISSUE TITLE
Default Interface Method throws an VerificationException

### ISSUE THREAD

**Issue by akiotakahashi** [dotnet/runtime#34982] opened 2020-04-15 01:54 UTC
The code below throws unexpected VerificationException.

Brief descriptions:
- There are two fundamental classes, IContainer&lt;T&gt; and IVisitor&lt;T&gt;
  - IContainer&lt;T&gt;.DoSomething accepts an instance of IVisitor&lt;T&gt;.
  - T is attributed with a constraint "notnull"
- IClassContainer&lt;T&gt; and IClassVisitor&lt;T&gt; are derived types for T constrained with "class"
  - IClassContainer&lt;T&gt;.DoSomething should accepts IClassVisitor&lt;T&gt;
- MyClasssContainer&lt;string&gt; and MyClassVisitor&lt;string&gt; are implementation types
  - `MyClasssContainer<string> :  IClassContainer<string>`
  - `MyClasssVisitor<string> :  IClassVisitor<string>`

Reproduction steps:
1. Call MyClassContainer&lt;string&gt;.DoSomething with MyClassVisitor&lt;string&gt;
2. .NET Runtime throws VerificationException indicating that "class" constraint doesn't satisfy "notnull"

In contrast, no exceptions occur about classes for ValueType (MyValueContainer and MyValueVisitor).

```csharp
#nullable enable

using System;

public class DefaultInterfaceMethodConstraintTest
{
    public static void Main()
    {
        // Construct containers
        var valueContainer = new MyValueContainer<int>();
        var classContainer = new MyClassContainer<string>();
        // Pass visitors to DoSomething method
        // There two below invocations are OK
        var intVisitor = ((IContainer<int>)valueContainer).DoSomething(new MyVisitor<int>());
        var valueVisitor = ((IContainer<int>)valueContainer).DoSomething(new MyValueVisitor<int>());
        // There two below will throw System.Security.VerificationException:
        // 'Method IContainer`1[System.String].DoSomething:
        // type argument 'TVisitor' violates the constraint of type parameter 'TVisitor'.'
        var strVisitor = ((IContainer<string>)classContainer).DoSomething(new MyVisitor<string>());
        var classVisitor = ((IContainer<string>)classContainer).DoSomething(new MyClassVisitor<string>());
        // Outputs
        Console.WriteLine(intVisitor.count);
        Console.WriteLine(strVisitor.count);
        Console.WriteLine(valueVisitor.count);
        Console.WriteLine(classVisitor.count);
    }
}

public interface IContainer<T> where T : notnull
{
    TVisitor DoSomething<TVisitor>(TVisitor visitor) where TVisitor : notnull, IVisitor<T>
    {
        return visitor;
    }
}

public interface IVisitor<T> where T : notnull
{
    void process(T item);
}

public class MyValueContainer<T> : IContainer<T> where T : struct
{
}

public class MyClassContainer<T> : IContainer<T> where T : class
{
}

public struct MyVisitor<T> : IVisitor<T> where T : notnull
{
    public int count;

    public void process(T item)
    {
        this.count++;
    }
}

public struct MyValueVisitor<T> : IVisitor<T> where T : struct
{
    public int count;

    public void process(T item)
    {
        this.count++;
    }
}

public struct MyClassVisitor<T> : IVisitor<T> where T : class
{
    public int count;

    public void process(T item)
    {
        this.count++;
    }
}
```

If MyClassContainer<T> has own implementation of DoSomething, the exception is never occured.

```csharp
public class MyClassContainer<T> : IContainer<T> where T : class
{
    public TVisitor DoSomething<TVisitor>(TVisitor visitor) where TVisitor : notnull, IVisitor<T>
    {
        return visitor;
    }
}
```

**Comment by jkotas** [comment] 2020-04-15 04:20
cc @mangod9

**Comment by mangod9** [comment] 2020-04-15 06:01
Dupe of https://github.com/dotnet/runtime/issues/1674, which was just resolved today :)

**Closed by mangod9** 2020-04-15 06:01 UTC
Labels: area-TypeSystem-coreclr
