### ISSUE TITLE
[API Proposal]:Attribute to execute the method at compile time

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#96377] opened 2023-12-31 11:53 UTC
### Background and motivation

 I suggest adding an attribute for methods to compile them during assembly compilation.
 The code that the programmer will write:
```csharp
namespace System.Collections.Generic;
int obj = new Example().Get(21);
public class Example
{
    [Const]
    public void Get(int item){
    return item+3289;
    
    }
}

```
How will the code be changed after compilation, the compiler
```csharp
namespace System.Collections.Generic;
int obj = new Example().Get(21);
public class Example
{
    [CompilConst]
    public void Get(int item){
    return 3310;
    }
}

```

That is, the compiler must execute the method during compilation that is marked with the attribute, and record the result of this method

### API Proposal

-

### API Usage

-

**Comment by jkotas** [comment] 2023-12-31 12:52
This is C# language feature proposal. C# language proposals should be opened as discussions in https://github.com/dotnet/csharplang/ repo.

Duplicate of https://github.com/dotnet/csharplang/discussions/2379 and related issues.

**Closed by jkotas** 2023-12-31 12:52 UTC
Labels: api-suggestion, untriaged, needs-area-label

**Comment by Mr0N** [comment] 2023-12-31 13:29
> This is C# language feature proposal. C# language proposals should be opened as discussions in https://github.com/dotnet/csharplang/ repo.
> 
> Duplicate of [dotnet/csharplang#2379](https://github.com/dotnet/csharplang/discussions/2379) and related issues.

adding attribute somehow associated with the programming language?

**Comment by jkotas** [comment] 2023-12-31 13:37
Right, there are number of existing attributes like that.

**Comment by Mr0N** [comment] 2023-12-31 13:44
> Right, there are number of existing attributes like that.

I don't know about any. Can you give an example?

**Comment by jkotas** [comment] 2023-12-31 13:58
For example, `MemberNotNullWhenAttribute` and other nullability-related attributes are recognized and interpreted by the C# compiler.

**Comment by Mr0N** [comment] 2024-01-01 18:37
> For example, `MemberNotNullWhenAttribute` and other nullability-related attributes are recognized and interpreted by the C# compiler.

Well, this is a completely different attribute, radically different from what I propose

**Comment by alexrp** [comment] 2024-01-01 18:40
Bottom line is that you're asking for a major *C# compiler* feature here. Adding the attribute to the BCL is not exactly the main work item here.

**Comment by Mr0N** [comment] 2024-01-02 11:49
https://github.com/dotnet/roslyn/issues/71438
