### ISSUE TITLE
Update MetadataLoadContext for covariant returns feature

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#36278] opened 2020-05-12 11:27 UTC
#35308 is the implementation in the runtime. [MetadataLoadContext](https://github.com/dotnet/runtime/tree/master/src/libraries/System.Reflection.MetadataLoadContext) duplicates virtual method resolution rules for various reasons (e.g. getting inherited method level custom attributes, `MethodInfo.GetBaseDefinition`, etc.)

At minimum, it should be looked at whether there's any implications. It's likely there are.

Cc @mangod9

**Comment by mangod9** [comment] 2020-05-12 23:13
Adding @janvorli

**Comment by steveharter** [comment] 2020-08-11 14:14
Propose moving this to future based on schedule + priority. Any thoughts before I do that?

**Comment by steveharter** [comment] 2020-08-11 20:59
I will look at the existing semantics of MLC ASAP and report back.

**Comment by mangod9** [comment] 2020-08-11 21:04
sounds good. should be ok to move unless there are severe implications.

**Comment by steveharter** [comment] 2020-08-13 18:28
It appears only runtime behavior has changed, not standard reflection, so MetadataLoadContext shouldn't need any changes as it is designed to match standard reflection behavior.

I assume the covariance feature did not change reflection behavior by design, and that it was not an oversight. In particular, the behavior of `Type.GetMethods()` for covariant methods is not consistent with non-covariant methods (see the first bullet below).

Here's some areas tested:
- The MLC `Type.GetMethods()` semantics are consistent with standard reflection for hiding base methods. However, covariant DerivedType.`GetMethods()` doesn't have the same behavior as non-covariant. With covariant methods, no collapsing of base methods is done and both the base and derived methods are returned. This is different from non-covariant cases (same return Type) which collapses the base methods and just returns the derived method.
- The MLC `MethodInfo.CustomAttributes` semantics are consistent with standard reflection.
- The MLC `MethodInfo.GetBaseDefinition()` semantics are not supported by MLC and throws NotSupportedException.

Currently it is not possible to add covariant tests to MLC since the new compiler is not yet available in runtime. When it becomes available, I will add additional XUnit-based tests.

In the meantime, see below for console app results.
<details><summary>Click to view test code and results</summary>

```cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;

[AttributeUsage(AttributeTargets.Method, Inherited = true)]
class MyAttribute : Attribute { }

class Covariant0 {[My] public virtual object M() { return "Covariant0.M"; } }
class Covariant1 : Covariant0 {[My] public override string M() { return "Covariant1.M"; } }

class CNoCovariant0 {[My] public virtual string M() { return "CNoCovariant0.M"; } }
class CNoCovariant1 : CNoCovariant0 {[My] public override string M() { return "CNoCovariant1.M"; } }

class Program
{
    static void Main()
    {
        Covariant0 obj = new Covariant1();
        string val = (string)obj.M();
        Console.WriteLine($"Covariant language feature is enabled: {val == "Covariant1.M"}");
        Console.WriteLine();
        Console.WriteLine($"**Reflection**");

        Type t0 = typeof(Covariant0);
        Debug.Assert(t0.GetType().Namespace == "System");
        Type t1 = typeof(Covariant1);
        Debug.Assert(t0.GetType().Namespace == "System");
        Output(t0, t1);

        t0 = typeof(CNoCovariant0);
        Debug.Assert(t0.GetType().Namespace == "System");
        t1 = typeof(CNoCovariant1);
        Debug.Assert(t1.GetType().Namespace == "System");
        Output(t0, t1);

        // Initialize types from MLC
        string[] runtimeAssemblies = Directory.GetFiles(RuntimeEnvironment.GetRuntimeDirectory(), "*.dll");
        var paths = new List<string>(runtimeAssemblies);
        paths.Add(typeof(Program).Assembly.Location);
        var resolver = new PathAssemblyResolver(paths);
        PathAssemblyResolver par = new PathAssemblyResolver(paths);
        MetadataLoadContext mlc = new MetadataLoadContext(par);
        Assembly thisAsm = mlc.LoadFromAssemblyName(typeof(Program).Assembly.GetName());

        Console.WriteLine();
        Console.WriteLine($"**MetadataLoadContext**");

        t0 = thisAsm.GetType(nameof(Covariant0));
        Debug.Assert(t0.GetType().Namespace == "System.Reflection.TypeLoading.Ecma");
        t1 = thisAsm.GetType(nameof(Covariant1));
        Debug.Assert(t1.GetType().Namespace == "System.Reflection.TypeLoading.Ecma");
        Output(t0, t1);

        t0 = thisAsm.GetType(nameof(CNoCovariant0));
        Debug.Assert(t0.GetType().Namespace == "System.Reflection.TypeLoading.Ecma");
        t1 = thisAsm.GetType(nameof(CNoCovariant1));
        Debug.Assert(t1.GetType().Namespace == "System.Reflection.TypeLoading.Ecma");
        Output(t0, t1);

        /* Output is
            Covariant language feature is enabled: True

            **Reflection**
            Methods in Covariant0:
             M AttrCount=1 IsHideBySig=True Attributes=PrivateScope, Public, Virtual, HideBySig, VtableLayoutMask
            Methods in Covariant1:
             M AttrCount=3 IsHideBySig=True Attributes=PrivateScope, Public, Virtual, HideBySig, VtableLayoutMask
             M AttrCount=1 IsHideBySig=True Attributes=PrivateScope, Public, Virtual, HideBySig, VtableLayoutMask
            Methods in CNoCovariant0:
             M AttrCount=1 IsHideBySig=True Attributes=PrivateScope, Public, Virtual, HideBySig, VtableLayoutMask
            Methods in CNoCovariant1:
             M AttrCount=2 IsHideBySig=True Attributes=PrivateScope, Public, Virtual, HideBySig

            **MetadataLoadContext**
            Methods in Covariant0:
             M AttrCount=1 IsHideBySig=True Attributes=PrivateScope, Public, Virtual, HideBySig, VtableLayoutMask
            Methods in Covariant1:
             M AttrCount=3 IsHideBySig=True Attributes=PrivateScope, Public, Virtual, HideBySig, VtableLayoutMask
             M AttrCount=1 IsHideBySig=True Attributes=PrivateScope, Public, Virtual, HideBySig, VtableLayoutMask
            Methods in CNoCovariant0:
             M AttrCount=1 IsHideBySig=True Attributes=PrivateScope, Public, Virtual, HideBySig, VtableLayoutMask
            Methods in CNoCovariant1:
             M AttrCount=2 IsHideBySig=True Attributes=PrivateScope, Public, Virtual, HideBySig
        */
    }

    static void Output(Type t0, Type t1)
    {
        Console.WriteLine($"Methods in {t0.Name}:");
        foreach (MethodInfo mi in t0.GetMethods())
        {
            if (mi.DeclaringType.Name != "Object")
            {
                Console.WriteLine($" {mi.Name} AttrCount={mi.CustomAttributes.Count()} IsHideBySig={mi.IsHideBySig} Attributes={mi.Attributes}");
            }
        }

        Console.WriteLine($"Methods in {t1.Name}:");
        foreach (MethodInfo mi in t1.GetMethods())
        {
            if (mi.DeclaringType.Name != "Object")
            {
                Console.WriteLine($" {mi.Name} AttrCount={mi.CustomAttributes.Count()} IsHideBySig={mi.IsHideBySig} Attributes={mi.Attributes}");
            }
        }
    }
}
```
</details>

**Comment by steveharter** [comment] 2020-08-13 19:39
@janvorli can you verify that the existing reflection semantics of `Type.GetMethods()` is correct for covariant methods?

**Comment by janvorli** [comment] 2020-08-13 21:22
I have no idea what is the supposed semantics of the `Type.GetMethods` for covariant methods. I hope @davidwrighton would have some idea here.

**Comment by davidwrighton** [comment] 2020-08-13 23:27
It sounds like the behavior is correct here. Covariant returns use a different override mechanism than standard name/sig overrides, and this mechanism represents itself in reflection in a different manner. The other method that I would be particular concerned about is `GetInterfaceMap`, but that throws an exception in MetadataLoadContext, so it isn't a concern either. Its plausible that we may wish to add functionality in the future to make MethodImpl based overrides more visible in Reflection, but they currently aren't really visible in either runtime reflection or MetadataLoadContext reflection.

**Closed** 2020-08-13 23:27 UTC
Labels: area-System.Reflection, enhancement, needs more info
