### ISSUE TITLE
DI behavior change between .NET 7.0 and .NET 8.0

### ISSUE THREAD

**Issue by kevinchalet** [dotnet/runtime#88968] opened 2023-07-16 17:29 UTC
### Description

The snippet attached to this ticket works fine on .NET 7.0 (and earlier) but crashes on .NET 8.0 preview6 (changing `<TargetFramework>net8.0</TargetFramework>` to `<TargetFramework>net7.0</TargetFramework>` is enough to stop the exception).

### Reproduction Steps

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0-preview.6.23329.7" />
    <PackageReference Include="Moq" Version="4.18.4" />
  </ItemGroup>

</Project>
```

```csharp
using Microsoft.Extensions.DependencyInjection;
using Moq;

var mock = Mock.Of<IInterface>();

var services = new ServiceCollection();
services.AddSingleton(typeof(IInterface), mock.GetType());

await using var provider = services.BuildServiceProvider();
var instance = provider.GetRequiredService<IInterface>();

Console.WriteLine($"Instance has the correct type: {instance.GetType() == mock.GetType()}");

public interface IInterface { }
```

### Expected behavior

No exception, `Instance has the correct type: True` visible in the console output.

### Actual behavior

> System.InvalidOperationException : 'Unable to resolve service for type 'Castle.DynamicProxy.IInterceptor[]' while attempting to activate 'Castle.Proxies.IInterfaceProxy'.'

### Regression?

Yes, working fine on .NET 7.0 and earlier.

### Other information

Changing the `Microsoft.Extensions.DependencyInjection` package version doesn't seem to have any influence.

**Comment by teo-tsirpanis** [comment] 2023-07-16 18:36
Did not reproduce with Preview 4, just installed Preview 6 and it does. Also reproduces with version 7.0.0 of MS.E.DI. Here's the full stack trace:

```
Unhandled exception. System.InvalidOperationException: Unable to resolve service for type 'Castle.DynamicProxy.IInterceptor[]' while attempting to activate 'Castle.Proxies.IInterfaceProxy'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Program.<Main>$(String[] args) in C:\Users\teo\code\DiRepro\Program.cs:line 10
   at Program.<Main>$(String[] args) in C:\Users\teo\code\DiRepro\Program.cs:line 12
   at Program.<Main>(String[] args)
```

Seems like a reflection change that broke DI. @dotnet/area-system-reflection thoguhts?

**Comment by kevinchalet** [comment] 2023-07-18 13:10
@steveharter thanks for taking the time to investigate, much appreciated! 😃 

The suggested fix is pretty much what I had in mind but I preferred reporting this issue first, given that this code has always worked fine on .NET Framework 4.6.1/4.7.2/4.8 and every .NET Core version from 1.0 to 7.0. If the outcome is "it worked, but only by accident", I'm fine with that 👍🏻 

Thanks again!

**Comment by steveharter** [comment] 2023-07-19 17:01
I'm going to close this as by design, and due to the breaking change above.

If DI needs to work around this issue, please re-open or comment here.

**Closed by steveharter** 2023-07-19 17:01 UTC
Labels: regression-from-last-release, area-Extensions-DependencyInjection
