### ISSUE TITLE
Test failure JIT\\CodeGenBringUpTests\\DivConst_r\\DivConst_r.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#74044] opened 2022-08-17 01:20 UTC
Run: [runtime-coreclr outerloop 20220816.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1946310&view=ms.vss-test-web.build-test-results-tab&runId=50126352&resultId=107281&paneView=debug)

Failed test:
```
R2R-CG2 windows arm Checked no_tiered_compilation @ Windows.10.Arm64v8.Open

- JIT\\CodeGenBringUpTests\\DivConst_r\\DivConst_r.cmd
```
**Error message:**
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
at System.Runtime.InteropServices.NativeLibrary.LoadByName(System.String, System.Runtime.CompilerServices.QCallAssembly, Boolean, UInt32, Boolean)
at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(System.String, System.Reflection.Assembly, System.Nullable1<System.Runtime.InteropServices.DllImportSearchPath>, Boolean)
at System.Runtime.InteropServices.NativeLibrary.Load(System.String, System.Reflection.Assembly, System.Nullable1<System.Runtime.InteropServices.DllImportSearchPath>)
at Internal.JitInterface.JitConfigProvider+<>c__DisplayClass5_0.<Initialize>b__0(System.String, System.Reflection.Assembly, System.Nullable1<System.Runtime.InteropServices.DllImportSearchPath>)
at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(System.String, System.Reflection.Assembly, Boolean, UInt32)
at Internal.JitInterface.CorInfoImpl.JitCompileMethod(IntPtr ByRef, IntPtr, IntPtr, IntPtr, Internal.JitInterface.CORINFO_METHOD_INFO ByRef, UInt32, IntPtr ByRef, UInt32 ByRef)
at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(ILCompiler.DependencyAnalysis.IMethodNode, Internal.IL.MethodIL)
at Internal.JitInterface.CorInfoImpl.CompileMethod(ILCompiler.DependencyAnalysis.ReadyToRun.MethodWithGCInfo, ILCompiler.Logger)
at ILCompiler.ReadyToRunCodegenCompilation.<ComputeDependencyNodeDependencies>g__CompileOneMethod|38_3(ILCompiler.DependencyAnalysisFramework.DependencyNodeCore1<ILCompiler.DependencyAnalysis.NodeFactory>)
at System.Threading.Tasks.Parallel+<>c__DisplayClass33_02[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForEachWorker>b__0(Int32)
at System.Threading.Tasks.Parallel+<>c__DisplayClass19_01[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef, Int32, Boolean ByRef)
at System.Threading.Tasks.TaskReplicator+Replica.Execute()
at System.Threading.Tasks.TaskReplicator+Replica+<>c.<.ctor>b__4_0(System.Object)
at System.Threading.Tasks.Task.InnerInvoke()
at System.Threading.Tasks.Task+<>c.<.cctor>b__273_0(System.Object)
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
at System.Threading.Thread.StartCallback()

Return code:      1
Raw output file:      D:\h\w\B06609AB\w\AA02094E\uploads\Reports\JIT.CodeGenBringUpTests\DivConst_r\DivConst_r.output.txt
Raw output:
BEGIN EXECUTION
DivConst_r.dll
1 file(s) copied.
7:24:56.13
Response file: D:\h\w\B06609AB\w\AA02094E\e\JIT\CodeGenBringUpTests\DivConst_r\DivConst_r.dll.rsp
D:\h\w\B06609AB\w\AA02094E\e\JIT\CodeGenBringUpTests\DivConst_r\IL-CG2\DivConst_r.dll
-o:D:\h\w\B06609AB\w\AA02094E\e\JIT\CodeGenBringUpTests\DivConst_r\DivConst_r.dll
--targetarch:arm
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\B06609AB\p\System..dll
-r:D:\h\w\B06609AB\p\Microsoft..dll
-r:D:\h\w\B06609AB\p\mscorlib.dll
-r:D:\h\w\B06609AB\p\netstandard.dll
-O
" "dotnet" "D:\h\w\B06609AB\p\crossgen2\crossgen2.dll" @"D:\h\w\B06609AB\w\AA02094E\e\JIT\CodeGenBringUpTests\DivConst_r\DivConst_r.dll.rsp"   -r:D:\h\w\B06609AB\w\AA02094E\e\JIT\CodeGenBringUpTests\DivConst_r\IL-CG2*.dll"
7:25:03.46
C


Stack trace
   at JIT_CodeGenBringUpTests._DivConst_r_DivConst_r_._DivConst_r_DivConst_r_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by jeffschwMSFT** [comment] 2022-08-17 15:57
@elinor-fung can you take a look?

**Comment by elinor-fung** [comment] 2022-08-17 16:42
Seems like something similar has cropped up a couple times with running crossgen2 trying to load a jit library:
https://github.com/dotnet/runtime/issues/60278
https://github.com/dotnet/runtime/issues/72069

cc @trylek in case you have some recollection of those investigations

**Comment by trylek** [comment] 2022-08-20 23:01
We haven't yet managed to root cause these failures. They were always intermittent and none of my attempts at running these pipelines with targeted instrumentation have yielded any insights so far.

**Comment by mangod9** [comment] 2022-08-22 15:49
these could be the same write barrier issues @AntonLapounov was looking into. Perhaps we should wait to check after that fix merges

**Comment by mangod9** [comment] 2022-08-23 22:58
Closing this issue due to an infra bug where dumps were not being captured. The infra issue is fixed as of today so please reopen if this occurs again.

**Closed by mangod9** 2022-08-23 22:58 UTC
Labels: os-windows, area-crossgen2-coreclr, blocking-outerloop
