### ISSUE TITLE
Test failure: System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test.ConnectTimeout_TimesOutSSLAuth_Throws

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#41780] opened 2020-09-03 01:55 UTC
failed in job: [runtime-libraries outerloop 20200902.4 ](https://dev.azure.com/dnceng/public/_build/results?buildId=798363&view=ms.vss-test-web.build-test-results-tab&runId=25273810&resultId=102925&paneView=debug)

net5.0-Linux-Release-x64-CoreCLR_release-SLES.12.Amd64.Open

Error message
~~~
Assert.InRange() Failure
Range:  (500 - 60000)
Actual: 61743


Stack trace
   at System.Net.Http.Functional.Tests.HttpClientHandler_Http11_Cancellation_Test.<>c__DisplayClass1_0.<<ConnectTimeout_TimesOutSSLAuth_Throws>b__0>d.MoveNext() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs:line 40
--- End of stack trace from previous location ---
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 96
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 124
   at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass13_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 87
--- End of stack trace from previous location ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 73
   at System.Net.Http.Functional.Tests.HttpClientHandler_Http11_Cancellation_Test.ConnectTimeout_TimesOutSSLAuth_Throws() in /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cancellation.cs:line 27
--- End of stack trace from previous location ---
~~~

**Comment by ManickaP** [comment] 2020-09-03 08:30
Duplicate of #40798

**Closed by ManickaP** 2020-09-03 08:30 UTC
Labels: area-System.Net.Http, untriaged
