### ISSUE TITLE
System.Text.Json Deserialization not support proto type repeated

### ISSUE THREAD

**Issue by SimenCTan** [dotnet/runtime#53356] opened 2021-05-27 14:47 UTC
### greet.proto is the file defined by protobuf
```
syntax = "proto3";

option csharp_namespace = "test";

package greet;

// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc TextJsonDeserialize (RepeatedTypeTextJsonDeserialize) returns (HelloReply);
}

// The response message containing the greetings.
message HelloReply {
  string message = 1;
}

message RepeatedTypeTextJsonDeserialize
{
  string name = 1;
  int32 number = 2;
  repeated int32 repeatednumbers = 3;
}
 ```
### GreeterService class  implement the  Greeter.GreeterBase
```
public class GreeterService : Greeter.GreeterBase
    {
        private readonly ILogger<GreeterService> _logger;
        public GreeterService(ILogger<GreeterService> logger)
        {
            _logger = logger;
        }

        public override Task<HelloReply> TextJsonDeserialize(RepeatedTypeTextJsonDeserialize request, ServerCallContext context)
        {
            var repeatedTypeModel = new RepeatedTypeTextJsonDeserialize
            {
                Name="test",
                Number=1
            };
            repeatedTypeModel.Repeatednumbers.AddRange(new int[]{1,2,3,4});
            var jsonStr = System.Text.Json.JsonSerializer.Serialize(repeatedTypeModel);
            var repeatedFieldTextJsonModel=System.Text.Json.JsonSerializer.Deserialize<RepeatedTypeTextJsonDeserialize>(jsonStr);
            var repeatedFieldNewtonsoftJsonModel = Newtonsoft.Json.JsonConvert.DeserializeObject<RepeatedTypeTextJsonDeserialize>(jsonStr);
            return Task.FromResult(new HelloReply());
        }
    }
````
- System.Text.Json.JsonSerializer serialization object is normal, when deserializing, the value of Repeatednumbers field is empty
- Newtonsoft.Json.JsonConvert serialization and deserialization work normally

### Other information
Sample project is available here:  https://github.com/SimenCTan/TextJsonDeserializeRepeatedField

Thanks!

**Comment by SimenCTan** [comment] 2021-05-31 04:41
>> Here are some common scenario to share generated C# RepeatedTypeTextJsonDeserialize class 
> E.g 
![image](https://user-images.githubusercontent.com/19427810/120140549-5e74ac00-c20d-11eb-8869-c6c3502afbc8.png)
>
- Although I can define a c# model, however it is very convenient to use a class generated by gRPC.NET.

**Comment by eiriktsarpalis** [comment] 2021-05-31 13:19
My recommendation would be to use a separate DTO class for the Redis calls, however I do understand that it might be convenient to reuse the generated class. That being said, could you please share the generated C# class so we can better understand what is causing the behaviour you are experiencing?

**Comment by wzchua** [comment] 2021-05-31 14:08
The RepeatedField is not generated with a setter.

**Comment by SimenCTan** [comment] 2021-06-01 03:40
> My recommendation would be to use a separate DTO class for the Redis calls, however I do understand that it might be convenient to reuse the generated class. That being said, could you please share the generated C# class so we can better understand what is causing the behaviour you are experiencing?

- Sample project is available here: https://github.com/SimenCTan/TextJsonDeserializeRepeatedField . The class UserInfo generated by the protocol buffer compiler :
``` ruby
// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/greet.proto
// </auto-generated>

 public sealed partial class UserInfo : pb::IMessage<UserInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UserInfo> _parser = new pb::MessageParser<UserInfo>(() => new UserInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UserInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::test.GreetReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserInfo(UserInfo other) : this() {
      name_ = other.name_;
      supportType_ = other.supportType_.Clone();
      otherinfo_ = other.otherinfo_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserInfo Clone() {
      return new UserInfo(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "supportType" field.</summary>
    public const int SupportTypeFieldNumber = 2;
    private static readonly pb::FieldCodec<int> _repeated_supportType_codec
        = pb::FieldCodec.ForInt32(18);
    private readonly pbc::RepeatedField<int> supportType_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> SupportType {
      get { return supportType_; }
    }

    /// <summary>Field number for the "otherinfo" field.</summary>
    public const int OtherinfoFieldNumber = 3;
    private string otherinfo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Otherinfo {
      get { return otherinfo_; }
      set {
        otherinfo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UserInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UserInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if(!supportType_.Equals(other.supportType_)) return false;
      if (Otherinfo != other.Otherinfo) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      hash ^= supportType_.GetHashCode();
      if (Otherinfo.Length != 0) hash ^= Otherinfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      supportType_.WriteTo(output, _repeated_supportType_codec);
      if (Otherinfo.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Otherinfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      supportType_.WriteTo(ref output, _repeated_supportType_codec);
      if (Otherinfo.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Otherinfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      size += supportType_.CalculateSize(_repeated_supportType_codec);
      if (Otherinfo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Otherinfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UserInfo other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      supportType_.Add(other.supportType_);
      if (other.Otherinfo.Length != 0) {
        Otherinfo = other.Otherinfo;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18:
          case 16: {
            supportType_.AddEntriesFrom(input, _repeated_supportType_codec);
            break;
          }
          case 26: {
            Otherinfo = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18:
          case 16: {
            supportType_.AddEntriesFrom(ref input, _repeated_supportType_codec);
            break;
          }
          case 26: {
            Otherinfo = input.ReadString();
            break;
          }
        }
      }
    }
    #endif
  }
```

**Comment by SimenCTan** [comment] 2021-06-01 05:35
> The RepeatedField is not generated with a setter.

- Yeap,  but RepeatedField implements IList<T>, ICollection<T>, IEnumerable<T> interfaces, and has an Add method.  The Dictionary class does not have a setter property, but it can still be deserialized through System.Text.Json . Besides, Newtonsoft.Json.JsonConvert Serialize and Deserialize RepeatedField  work well

**Comment by eiriktsarpalis** [comment] 2021-06-01 05:47
This seems like a duplicate of https://github.com/grpc/grpc-dotnet/issues/1067 and https://github.com/dotnet/runtime/issues/30258.

It seems like protobuf has built-in support for JSON serialization, per https://github.com/grpc/grpc-dotnet/issues/1067#issuecomment-703036541, so that might be the prefered workaround.

Closing this issue in favor of https://github.com/dotnet/runtime/issues/30258.

**Closed by eiriktsarpalis** 2021-06-01 05:47 UTC
Labels: area-System.Text.Json, needs more info, untriaged
