### ISSUE TITLE
Add APICompat validation for nullable annotations

### ISSUE THREAD

**Issue by safern** [dotnet/runtime#41724] opened 2020-09-02 02:36 UTC
Now that almost 100% of the shared framework is annotated we should add a rule to [APICompat](https://github.com/dotnet/arcade/tree/master/src/Microsoft.DotNet.ApiCompat) to diff nullable annotations yo protect future changes in ref and implementation to make sure we don't miss any annotation on refs specially.

Currently APICompat is using CCI which is a big challenge as the way nullable annotations are represented in metadata is pretty hard to get the diffing right because of NullableContextAttribute so we should do this with Roslyn.

cc: @ericstj @danmosemsft @jeffhandley

**Comment by safern** [comment] 2020-09-02 02:39
FYI: I also have made progress on a POC to use Roslyn for APICompat in case I don't have bandwidth to tackle this one I can share it with whoever works in it.

**Comment by ericstj** [comment] 2020-09-02 16:02
As we've discussed before I think the best solution here is to get us to converge on https://github.com/dotnet/roslyn-analyzers/tree/master/src/PublicApiAnalyzers and have that support our scenarios.

**Comment by safern** [comment] 2020-09-02 16:25
Yeah I definitely agree as that would also give customers a better experience for using .cs and .dll files for APICompat using the latest Roslyn features.

**Comment by ViktorHofer** [comment] 2022-07-20 16:55
Closing as duplicate of https://github.com/dotnet/sdk/issues/18681

**Closed by ViktorHofer** 2022-07-20 16:55 UTC
Labels: area-Infrastructure-libraries
