### ISSUE TITLE
CurrencyNegativePattern  is set to 1(instead of 0) when getting "en-US" culture in .NET 8.

### ISSUE THREAD

**Issue by NikolayYakov** [dotnet/runtime#103644] opened 2024-06-18 14:28 UTC
### Description

When trying to generate "en-US' CultureInfo using **CultureInfoConverter.ConvertFrom** or **CultureInfo.GetCultures(CultureTypes.SpecificCultures | CultureTypes.NeutralCultures)**  in .NET 8 I receive a culture with CurrencyNegativePattern set to 1, which results in negative numbers shown as  -$100. The methods above work as expected in .NET Framework 4.6.2. I have also noticed that the **CultureInfo.CreateSpecificCulture("en-US")** works fine and return culture with CurrencyNegativePattern set to 0 in both .NET 8 and .NET Framework 4.6.2

### Reproduction Steps

`var negativePattern = CultureInfo.GetCultures(CultureTypes.SpecificCultures | CultureTypes.NeutralCultures).First(c => c.Name == "en-US").NumberFormat.CurrencyNegativePattern;`

### Expected behavior

CurrencyNegativePattern should be 0 and the value should be displayed as ($100)

### Actual behavior

CurrencyNegativePattern is 1 and the value is displayed as -$100

### Regression?

Works as expected in .NET Framework 4.6.2

### Known Workarounds

CultureInfo.CreateSpecificCulture("en-US") works as expected.

**Comment by Clockwork-Muse** [comment] 2024-06-18 16:43
A couple of things here:
 1) You're never guaranteed that any given culture will have static formatting, and formats are updated multiple times a year (globally).  Localized formats will vary between machines and operating systems, so if you're intending to pass the data as interchange, use either explicit formats or the invariant culture.  Otherwise, ignore the actual return and just display it for the user.
 2) I would generally expect the "actual behavior" you're seeing.
 3) One of the big things that changed between .NetF and .Net Core is that it now usually uses [ICU on Windows](https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu), which can drive some differences, however...
4) [`CreateSpecificCulture()`](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.createspecificculture?view=net-8.0#remarks) returning different results tells me that you (or an admin) have set an override on Windows.  Not all culture-related methods and constructors reflect such overrides.

Working as designed.

**Comment by NikolayYakov** [comment] 2024-06-19 07:56
Thanks for the replay @Clockwork-Muse one more question.

 We are developing a reporting engine and trying to achieve consistent globalization behavior between different .NET versions and on different machines. Is there a way to achieve this, without needing to manually set each culture formatting settings?

**Comment by Clockwork-Muse** [comment] 2024-06-19 16:50
Depends on context.
 - For all data storage/persistence/interchange purposes, you **MUST** explicitly specify the invariant culture at minimum while formatting/parsing (specifying an explicit format string in addition will also make your code more clear).  If you're using an established engine/library (eg, `System.Net.Json`) normally this will be handled for you.
 - For _most_ display(/data entry?) purposes, often simply displaying it in the localized format is "fine".  This doesn't change the actual data stored, and usually any human-to-human communication will gloss over any differences.  Ignore any cross-machine or cross-version differences.

If really you want to enforce a specific format throughout your program for display(/data entry), the easiest thing to do will be to create a customized instance of `CultureInfo` on program start and set that as the UI/default culture.  Or just use the invariant culture.  Don't call `GetCultures`/`CreateSpecificCulture` at all, and completely ignore whatever the host has set.

(Note that it's possible to package a specific ICU build alongside your application, but that's generally overkill since by default it includes all cultures, which likely isn't what you want.  In theory you could package up just one/a custom culture, though...)

**Comment by tarekgh** [comment] 2024-06-20 23:45
Customizing CultureInfo or using Invariant culture to ensure consistency across platforms/versions is way to do it. 

> (Note that it's possible to package a specific ICU build alongside your application

If need to support .NET Framework, this will not work.

@NikolayYakov I am closing the issue but feel free to respond with any questions if you still have any.

**Closed by tarekgh** 2024-06-20 23:45 UTC
Labels: area-System.Globalization, untriaged
