### ISSUE TITLE
[wasm] Ensure that debugger proxy, and the app are compatible

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#68402] opened 2022-04-22 17:34 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/DevToolsProxy::Run:-Exception-SystemArg/10020488)._

---
[severity:It's more difficult to complete my work]
About 8 out of the 10 times I run my Blazor UI project, Visual Studio crashes and gives me this error:
```
Error on mono_wasm_get_loaded_files [Result: IsOk: False, IsErr: True, Value: , Error: {
  "result": {
    "type": "object",
    "subtype": "error",
    "className": "ReferenceError",
    "description": "ReferenceError: MONO is not defined\n    at :1:1",
    "objectId": "1741512465779150439.1.9"
  },
  "exceptionDetails": {
    "exceptionId": 5,
    "text": "Uncaught",
    "lineNumber": 0,
    "columnNumber": 0,
    "scriptId": "10",
    "stackTrace": {
      "callFrames": [
        {
          "functionName": "",
          "scriptId": "10",
          "url": "",
          "lineNumber": 0,
          "columnNumber": 0
        }
      ]
    },
    "exception": {
      "type": "object",
      "subtype": "error",
      "className": "ReferenceError",
      "description": "ReferenceError: MONO is not defined\n    at :1:1",
      "objectId": "1741512465779150439.1.10"
    }
  }
} ]
Failed to get the list of loaded files. Managed code debugging won't work due to this.
fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] DevToolsProxy::Run: Exception System.ArgumentException: The tasks argument included a null value. (Parameter 'tasks')    at System.Threading.Tasks.Task.WhenAny(Task[] tasks)    at Microsoft.WebAssembly.Diagnostics.DevToolsProxy.Run(Uri browserUri, WebSocket ideSocket)

C:\Program Files\dotnet\dotnet.exe (process 18824) exited with code 0.
```
---
#### Feedback Bot on 4/22/2022, 02:17 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by mkArtakMSFT** [comment] 2022-04-22 17:35
@lewing FYI

**Comment by radical** [comment] 2022-04-25 18:05
Which version of dotnet are you using?

@thaystg fyi:
`fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] DevToolsProxy::Run: Exception System.ArgumentException: The tasks argument included a null value. (Parameter 'tasks')    at System.Threading.Tasks.Task.WhenAny(Task[] tasks)    at Microsoft.WebAssembly.Diagnostics.DevToolsProxy.Run(Uri browserUri, WebSocket ideSocket)`

- this particular part is fixed by https://github.com/dotnet/runtime/commit/67d8b96d6d04d8aae231425bbf2a192966c4a3f8

**Comment by thaystg** [comment] 2022-04-25 18:24
Probably is using dotnet version 6.x and the .nuget package where is BrowserDebugProxy 7.0.x. This combination would cause this error.

**Comment by radical** [comment] 2022-04-25 19:04
Can we add something to match the versions, so we can fail with a descriptive error?

**Comment by radical** [comment] 2022-04-25 21:23
> Also we could ship BrowserDebugProxy as part of the runtime, so we wouldn't see this kind of incompatibility?

Yeah, we are looking at that now.

**Comment by lewing** [comment] 2022-06-09 14:52
I have an idea, will take a closer look this week

**Comment by lewing** [comment] 2022-07-20 16:22
This is difficult to fix without tying the proxy to the proxy to the runtime version which will mean shipping it from runtime instead of aspnetcore.

**Comment by lewing** [comment] 2022-07-20 16:25
@thaystg assuming we don't want to stick it in the runtime pack we'll need to change the proxy from a transport package to a shipping one and pull the package version from the runtime version in the workload logic

**Comment by radical** [comment] 2022-07-20 20:51
> @thaystg assuming we don't want to stick it in the runtime pack we'll need to change the proxy from a transport package to a shipping one and pull the package version from the runtime version in the workload logic

This will be useful for WasmAppHost too, which currently does include the proxy.

**Comment by lewing** [comment] 2022-07-22 14:28
I gave it some more thought and the only way they could end up with a 7 dev server and a net-6.0 runtime is if they had mismatched versions in the csproj as in an a TargetFramwork of net6 plus the a net7 dev server package reference which is impossible to entirely prevent.  We could add a version check just to make the problem clearer if they setup an invalid config by hand.

**Comment by enantiomer2000** [comment] 2022-10-04 20:34
I am getting the same error as Op. Seems like this happens periodically with my Blazor WASM app. Running .Net 6. Any solution to this?

**Comment by thaystg** [comment] 2022-10-04 20:47
@enantiomer2000 you should not see this if you are using the .net6 runtime and also the devserver package from .net6. Is this your case?

`<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="6.0.8" PrivateAssets="all" />`

**Comment by enantiomer2000** [comment] 2022-10-05 15:52
@thaystg Yes Microsoft.AspNetCore.Components.WebAssembly.DevServer is installed on the WASM client project. Debugging does work except for when it just stops working and I get the same message as Op. I tried making sure that the relevant projects were at the latest 6.0.9 versions which didn't help. It happens every few days it seems. It happened yesterday and I poked at it for a while futilely until I just rebooted my machine upon which time it started working again. I would be happy to help get more info for you if you want it.

**Comment by thaystg** [comment] 2022-10-05 15:54
@enantiomer2000 when it happens again please share with me this file:
`C:\Users\[USER_NAME]\AppData\Local\Temp\visualstudio-js-debugger.txt`

**Comment by Glitched94** [comment] 2022-10-11 14:56
> @enantiomer2000 when it happens again please share with me this file: `C:\Users\[USER_NAME]\AppData\Local\Temp\visualstudio-js-debugger.txt`

I'm experiencing this same issue with .NET 6 Blazor WASM
I've confirmed we have Microsoft.AspNetCore.Components.WebAssembly.DevServer v6.0.7 installed on the advice above.
[Here is the visualstudio-js-debugger.txt file](https://drive.google.com/file/d/1KZ_ZnRNaoQ8duIx48v8MuPONojI6kULV/view?usp=sharing)

**Comment by thaystg** [comment] 2022-10-11 15:12
@Glitched94 , are you creating a new app? It happens always when you start debugging or after some navigation in the app?

**Comment by Glitched94** [comment] 2022-10-11 15:17
> @Glitched94 , are you creating a new app? It happens always when you start debugging or after some navigation in the app?

It's an existing app that we originally wrote in .NET 5 Blazor WASM and upgraded to .NET 6 about 5 months ago.
The issue happens after some page navigations. Where it happens is seemingly random, but once it starts happening, it can be repeated at the same spot multiple times. Eventually the builds stop crashing and we can navigate past that spot, but eventually it'll pop up again in another, or occasionally the same spot as well.

**Comment by thaystg** [comment] 2022-10-11 15:28
Do you have any redirection to a non-wasm page, like a login page or something like this in your app?

**Comment by Glitched94** [comment] 2022-10-11 15:47
Our app only has client-sided pages, the server is only for serving up the data. The only .cshtml we have is the error page from the app template that we just never removed or modified.

**Comment by Glitched94** [comment] 2022-10-11 17:49
@thaystg The error message is not identical to the one at the very top, but one lower on the page:
`fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] DevToolsProxy::Run: Exception System.ArgumentException: The tasks argument included a null value. (Parameter 'tasks') at System.Threading.Tasks.Task.WhenAny(Task[] tasks) at Microsoft.WebAssembly.Diagnostics.DevToolsProxy.Run(Uri browserUri, WebSocket ideSocket)`
There's no other error message accompanying this message.

**Comment by enantiomer2000** [comment] 2022-10-11 23:57
> 
[Blazor_WASM_LogFileContent.txt](https://github.com/dotnet/runtime/files/9760393/Blazor_WASM_LogFileContent.txt)

The debugging bug happened again just now. Attached is the content from visualstudio-js-debugger.txt file. 

From Console output:
Error on mono_wasm_get_loaded_files [Result: IsOk: False, IsErr: True, Value: , Error: {
  "result": {
    "type": "object",
    "subtype": "error",
    "className": "ReferenceError",
    "description": "ReferenceError: MONO is not defined\n    at <anonymous>:1:1",
    "objectId": "2790414281955586462.7.11"
  },
  "exceptionDetails": {
    "exceptionId": 7,
    "text": "Uncaught",
    "lineNumber": 0,
    "columnNumber": 0,
    "scriptId": "129",
    "stackTrace": {
      "callFrames": [
        {
          "functionName": "",
          "scriptId": "129",
          "url": "",
          "lineNumber": 0,
          "columnNumber": 0
        }
      ]
    },
    "exception": {
      "type": "object",
      "subtype": "error",
      "className": "ReferenceError",
      "description": "ReferenceError: MONO is not defined\n    at <anonymous>:1:1",
      "objectId": "2790414281955586462.7.12"
    }
  }
} ]
Failed to get the list of loaded files. Managed code debugging won't work due to this.

**Comment by enantiomer2000** [comment] 2022-10-13 16:30
> > 
> 
> [Blazor_WASM_LogFileContent.txt](https://github.com/dotnet/runtime/files/9760393/Blazor_WASM_LogFileContent.txt)
> 
> The debugging bug happened again just now. Attached is the content from visualstudio-js-debugger.txt file.
> 
> From Console output: Error on mono_wasm_get_loaded_files [Result: IsOk: False, IsErr: True, Value: , Error: { "result": { "type": "object", "subtype": "error", "className": "ReferenceError", "description": "ReferenceError: MONO is not defined\n at :1:1", "objectId": "2790414281955586462.7.11" }, "exceptionDetails": { "exceptionId": 7, "text": "Uncaught", "lineNumber": 0, "columnNumber": 0, "scriptId": "129", "stackTrace": { "callFrames": [ { "functionName": "", "scriptId": "129", "url": "", "lineNumber": 0, "columnNumber": 0 } ] }, "exception": { "type": "object", "subtype": "error", "className": "ReferenceError", "description": "ReferenceError: MONO is not defined\n at :1:1", "objectId": "2790414281955586462.7.12" } } } ] Failed to get the list of loaded files. Managed code debugging won't work due to this.

@thaystg, any feedback on my log file? It would be nice not to have to reboot my machine periodically because of this.

**Comment by hellfirehd** [comment] 2022-10-15 15:50
I have been experiencing the same thing since upgrading to .NET 6 from .NET 5.

[Error_on_mono_wasm_get_loaded_files.log](https://github.com/dotnet/runtime/files/9792514/Error_on_mono_wasm_get_loaded_files.log)

**Comment by mwasson74** [comment] 2022-10-18 12:21
Same thing here

[visualstudio-js-debugger.txt](https://github.com/dotnet/runtime/files/9810273/visualstudio-js-debugger.txt)

**Comment by thaystg** [comment] 2022-10-18 16:57
If anyone can share with us the source code and steps to reproduce it would be great.
I'm still trying to reproduce.

**Comment by hellfirehd** [comment] 2022-10-18 17:00
I cannot share the source code but I would be willing to have someone remote in to my workstation.

**Comment by gerfen** [comment] 2022-10-25 01:03
I'm seeing the same issue using Identity Server with a CSHTML login page.  The debugger detaches when the app reloads after successfully logging into the app.  I've found deleting the bin and obj folders, restoring my nuget packages and doing a rebuild can resolve the issue for a little while.  Sometimes I have to combine the aforementioned steps with closing down Visual Studio and deleting the .vs folder for the solution to be able to get the debugger to remain attached.

**Comment by gerfen** [comment] 2022-10-25 01:31
@thaystg I spoke with my client and they are willing to give your team access the github repo for the project I'm working on so your team can try to repro the issue.

**Comment by thaystg** [comment] 2022-10-25 20:41
@gerfen , perfect, as soon as I have access I can work on fixing it. Thanks a lot.

**Comment by gerfen** [comment] 2022-10-25 20:55
@thaystg Excellent!  

I'll need an email address so I can have an invite sent to you.  I'll also need to create some documentation for you to get the project setup.  FWIW, I'm using the latest Blazor preview bits so you'll need VS 2002 Version 17.4.0 Preview 4.0 as well.

**Comment by thaystg** [comment] 2022-10-25 20:58
My github email is: thaystg@gmail.com

> @thaystg Excellent!
> 
> I'll need an email address so I can have an invite sent to you. I'll also need to create some documentation for you to get the project setup. FWIW, I'm using the latest Blazor preview bits so you'll need VS 2002 Version 17.4.0 Preview 4.0 as well.

**Comment by gerfen** [comment] 2022-10-25 21:00
I'll pass your email along to my customer so they can send you an invite.  I'll be in touch soon. Thanks!

**Comment by gerfen** [comment] 2022-11-11 20:56
@thaystg Any idea when this fix will get pushed to GA?

**Comment by thaystg** [comment] 2022-11-11 21:05
@gerfen this wil be available in the first servicing release.

**Comment by gerfen** [comment] 2022-11-11 21:08
@thaystg  Great! Thanks for the update.

**Comment by gerfen** [comment] 2023-01-03 20:58
@thaystg It appears that this issue was fixed with the release of VS 17.4.3.  via #77501.  Just wanted to confirm.  Thanks!

**Comment by 54696d20** [comment] 2023-01-04 17:09
@gerfen My team is still having the issue. I'm using 17.4.3

**Comment by thaystg** [comment] 2023-01-04 17:11
@54696d20 which version of this package are you using?
`<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="7.0.1" PrivateAssets="all" />`

**Comment by 54696d20** [comment] 2023-01-04 17:15
@thaystg We didn't upgrade to 7.0 because we are still on 6
`<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="6.0.3" PrivateAssets="all" />`

**Comment by thaystg** [comment] 2023-01-04 17:16
Can you upgrade to 6.0.12?

> @thaystg We didn't upgrade to 7.0 because we are still on 6 `<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="6.0.3" PrivateAssets="all" />`

**Comment by 54696d20** [comment] 2023-01-04 17:18
Yes, but still received the same errors. Looked like the same error. Upgrading to it now and will get back with you

**Comment by 54696d20** [comment] 2023-01-04 17:40
`fail: Microsoft.WebAssembly.Diagnostics.DevToolsProxy[0] DevToolsProxy::Run: Exception System.ArgumentException: The tasks argument included a null value. (Parameter 'tasks')    at System.Threading.Tasks.Task.WhenAny(Task[] tasks)    at Microsoft.WebAssembly.Diagnostics.DevToolsProxy.Run(Uri browserUri, WebSocket ideSocket)`

Is the error I receive when I upgraded it to 6.0.12. I worked for a bit without issue. I received the error when I stopped and started it again.

**Comment by thaystg** [comment] 2023-01-04 17:57
Can you share with us a sample project where I can reproduce it?

**Comment by 54696d20** [comment] 2023-01-04 18:04
I knew you'd say that lol. I'd ask the same thing. Let me see what I can do by recreating it in a new project. Unfortunately, the project I'm working on cannot be shared.

**Comment by thaystg** [comment] 2023-01-04 18:07
I think I don't need it, we have a fix for it in .net7, I'll try to backport it to 6.

**Comment by 54696d20** [comment] 2023-01-04 18:11
Awesome! We are trying to build a 2.0 version of our 1.0. So we didn't see a need to update to 7.0 because it wasn't offering a big change. Since 6.0 is LTS, it would be nice to have a fix. I have Devs that can't seem to work "quickly" without it :)

**Comment by gerfen** [comment] 2023-01-04 18:11
@thaystg I can confirm that the fix is working well for me using Microsoft.AspNetCore.Components.WebAssembly.DevServer version 7.0.1.  Thanks again for getting this fixed!

**Closed** 2023-07-24 20:58 UTC
Labels: arch-wasm, area-Debugger-mono
