### ISSUE TITLE
Ability to customize the runtime location for framework-dependent apps (apphost)

### ISSUE THREAD

**Issue by k15tfu** [dotnet/runtime#70975] opened 2022-06-20 06:54 UTC
Hi!

We have a number of framework-dependent apps in our bin directory with their dependencies, and we do bundle .NET runtime for different platforms in separate runtime-specific subfolders, and pack it all together for end users. In general, the overall product layout looks like:
* App1.exe (managed app)
* App2.exe
* (other managed dependencies, `.deps.json` and `.runtimeconfig.json` files)
* linux
* * AppHost1
* * AppHost2
* * dotnet-runtime
* osx
* * AppHost1
* * AppHost2
* * dotnet-runtime
* (and so on for other apps and platforms/architectures)

The current way we use allows us to share the same runtime folder for all our apps. This perfectly works for `dotnet exec` scenarious, but in case of apphost executables it requires `DOTNET_ROOT` to be specified (unfortunately), whether we run it through code or the end user runs it manually.

One of the possible solutions, namely the idea of embedding the runtime location into the apphost executable (e.g. as an option for `dotnet publish`) was already suggested in https://github.com/dotnet/runtime/issues/53834#issuecomment-862188052 and https://github.com/dotnet/runtime/issues/64430#issuecomment-1024333815, and it fits (solves) our use case as well. Ready to help with a pull request.

Linked issues: https://github.com/dotnet/runtime/issues/2572, https://github.com/dotnet/runtime/issues/3453, https://github.com/dotnet/runtime/issues/52974, https://github.com/dotnet/runtime/issues/53834, https://github.com/dotnet/runtime/issues/64430, https://github.com/dotnet/runtime/issues/64538, https://github.com/dotnet/sdk/issues/3405

cc @vitek-karas

**Comment by Symbai** [comment] 2022-06-20 08:50
This is just a dupe of the linked issues, for example #3453 which is still opened and can be used as tracking. I'm not sure why you did created a new one. This only adds more noise. If you want to increase priority, you should post within / and upvoting existing issues.

**Comment by k15tfu** [comment] 2022-06-20 09:50
@Symbai Thank you for the suggestion, https://github.com/dotnet/sdk/issues/10366 sounds to me like this is more about managed assemblies rather than hostfxr in the first place. Regarding https://github.com/dotnet/runtime/issues/64430, as was noted in https://github.com/dotnet/runtime/issues/64430#issuecomment-1025668929 there are discussed two different customizations, and the first of them is what this issue was created for.

**Comment by agocke** [comment] 2023-07-25 17:22
Dup of https://github.com/dotnet/runtime/issues/53834

**Closed by agocke** 2023-07-25 17:22 UTC
Labels: area-Host
