### ISSUE TITLE
The method does not work

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#72715] opened 2022-07-23 10:01 UTC
### Description

https://github.com/Mr0N/ExampleNotWorkingStream/blob/master/ExampleNotWorkingStream/Program.cs
Why does the CopyTo method not work, why does it not copy the stream completely? If this method does not have such semantics, why not create a method that will copy the entire stream?

### Reproduction Steps

-

### Expected behavior

-

### Actual behavior

-

### Regression?

-

### Known Workarounds

-

### Configuration

-

### Other information

-

**Comment by teo-tsirpanis** [comment] 2022-07-23 10:07
@Mr0N we can't see the linked code. Is it in a private repository?

**Comment by Mr0N** [comment] 2022-07-23 10:11
> @Mr0N we can't see the linked code. Is it in a private repository?

made the repository public

**Comment by teo-tsirpanis** [comment] 2022-07-23 10:21
So the issue is that `Stream.CopyTo` does not copy the stream before its current position. This behavior is by design. Copying the entire stream is not possible on non-seekable streams. If you want to do this, you can set the `Position` property to zero before calling `CopyTo`.

**Comment by Mr0N** [comment] 2022-07-23 10:26
> So the issue is that `Stream.CopyTo` does not copy the stream before its current position. This behavior is by design. Copying the entire stream is not possible on non-seekable streams. If you want to do this, you can set the `Position` property to zero before calling `CopyTo`.

Why doesn't CopyTo set the Position itself?

**Comment by Mr0N** [comment] 2022-07-23 10:27
Why is there no method that will guarantee that the stream was copied from the beginning and completely, and if not, throw an error?

**Comment by teo-tsirpanis** [comment] 2022-07-23 10:28
> Why doesn't CopyTo set the Position itself?

Because it's not always allowed to change the position. That's what "non-seekable" means. The [`Stream.CanSeek`](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.canseek) property shows if the position can be changed.

**Comment by Mr0N** [comment] 2022-07-23 10:34
![image](https://user-images.githubusercontent.com/61237140/180601501-97fe0e87-ab19-4586-ac79-24f9905852c7.png)
Why not do that?

**Comment by Mr0N** [comment] 2022-07-23 10:34
static class MyClass
    {
        public static void CopyTo(this Stream obj,Stream stream,bool enableException)
        {
            if (enableException && stream.Position > 0)
                throw new Exception("Stream is not position zero");
            obj.CopyTo(stream);
        }
    }

**Comment by teo-tsirpanis** [comment] 2022-07-23 10:40
You can do it in your code but it also won't always work; turns out if the stream is non-seekable, you can't even _get_ the position.

**Comment by Mr0N** [comment] 2022-07-23 10:51
> You can do it in your code but it also won't always work; turns out if the stream is non-seekable, you can't even _get_ the position.
```
   static class MyClass
    {
        public static void CopyTo(this Stream obj,Stream stream,bool enableException)
        {
            if (enableException &&!obj.CanSeek)
                throw new Exception("the stream does not support positions");
            if (enableException && stream.Position > 0)
                throw new Exception("Stream is not position zero");
            obj.CopyTo(stream);
        }
    }

```

**Comment by teo-tsirpanis** [comment] 2022-07-23 10:52
Seems fine!

**Comment by Mr0N** [comment] 2022-07-23 10:54
> Seems fine!

yes, now make a separate method in the stream base class, or add this method

**Comment by Mr0N** [comment] 2022-07-23 12:08
Well, that is, I want a method that will be guaranteed to write information from one stream to another, if not throw an exception

**Comment by Mr0N** [comment] 2022-07-23 12:10
Because CopyTo is not a very stable method, with many errors and incorrectly formed files.

**Comment by teo-tsirpanis** [comment] 2022-07-23 12:11
Why do you need this method to be in the BCL instead of implementing it in your code as you showed?

**Comment by Mr0N** [comment] 2022-07-23 12:17
> Why do you need this method to be in the BCL instead of implementing it in your code as you showed?

I can do many projects, implementing the same thing every time is not a good time, and secondly, in my opinion, a stream should have a normal method that will guarantee the transfer of information from one stream to another

**Comment by Mr0N** [comment] 2022-07-23 12:17
-

**Comment by Mr0N** [comment] 2022-07-23 12:18
> > Why do you need this method to be in the BCL instead of implementing it in your code as you showed?
> 
> I can do many projects, implementing the same thing every time is not a good time, and secondly, in my opinion, a stream should have a normal method that will guarantee the transfer of information from one stream to another

now there is no such method, which is a bit sad.

**Comment by huoyaoyuan** [comment] 2022-07-23 12:48
I can see the desire of copying from the start, instead of current position. It may worth a separated method. Maybe `CopyToFromStart`?

**Comment by stephentoub** [comment] 2022-07-23 13:08
CopyTo reliably copies from the current position. As was stated, this is by design. It works not only in situations where seeking doesn't work, but also for situations where you don't want to go back to the beginning, e.g. you read our a few bytes of a header and then copy the rest. For call sites that really want to start at the beginning of the stream, they themselves can set Position = 0, which will throw if it's not supported, and if they want a different behavior, they can check CanSeek and take an alternate path of its false. We're not going to add a helper for two lines.

**Comment by Mr0N** [comment] 2022-07-23 15:51
> CopyTo reliably copies from the current position. As was stated, this is by design. It works not only in situations where seeking doesn't work, but also for situations where you don't want to go back to the beginning, e.g. you read out a few bytes of a header and then copy the rest. For call sites that really want to start at the beginning of the stream, they themselves can set Position = 0, which will throw if it's not supported, and if they want a different behavior, they can check CanSeek and take an alternate path if it's false. I don't see us adding another helper to Stream that saves one line here.

They will add Position, sometimes you don’t even know that Position is shifted, for example after ToArray(); or after other methods, and there is no guarantee that the data will be intact after the CopyTo method

**Comment by Mr0N** [comment] 2022-07-23 16:06
> I can see the desire of copying from the start, instead of current position. It may worth a separated method. Maybe `CopyToFromStart`?

CopyAll

**Comment by stephentoub** [comment] 2022-07-23 16:43
> sometimes you don’t even know that Position

If you require that it be 0, set it to 0. If the stream doesn't support that, you can check CanSeek and if it's false you can decide what to do instead.

**Comment by Mr0N** [comment] 2022-07-23 18:14
> > sometimes you don’t even know that Position
> 
> If you require that it be 0, set it to 0. If the stream doesn't support that, you can check CanSeek and if it's false you can decide what to do instead.

the logic for the method is the same, for sure, why write it all every time, if nothing works and you can’t copy normally, then an error will be thrown

**Comment by stephentoub** [comment] 2022-07-23 18:17
> the logic for the method is the same, for sure, why write it all every time, if nothing works and you can’t copy normally, then an error will be thrown

You mean:
```C#
stream.Position = 0;
stream.CopyTo(destination);
```
instead of:
```C#
stream.CopyAllTo(destination);
```
The difference between those two is negligible and doesn't warrant an additional helper IMO.

**Comment by Mr0N** [comment] 2022-07-23 18:19
> > the logic for the method is the same, for sure, why write it all every time, if nothing works and you can’t copy normally, then an error will be thrown
> 
> You mean:
> 
> ```cs
> stream.Position = 0;
> stream.CopyTo(destination);
> ```
> 
> instead of:
> 
> ```cs
> stream.CopyAllTo(destination);
> ```
> 
> The difference between those two is negligible and doesn't warrant an additional helper IMO.

yes, but no one sets the position to zero for each thread until the problems start

**Comment by Mr0N** [comment] 2022-07-23 18:54
```
 var memory = new MemoryStream(new byte[] {1,2,3});
        var memoryTwo = new MemoryStream();
        var array = memory.ToArray();
        memory.CopyTo(memoryTwo);
```
example of a typical error

**Comment by stephentoub** [comment] 2022-07-23 18:59
> var memory = new MemoryStream(new byte[] {1,2,3});
> var memoryTwo = new MemoryStream();
> var array = memory.ToArray();
> memory.CopyTo(memoryTwo);
> example of a typical error

What's wrong with that?  MemoryStream.ToArray doesn't change the position in the MemoryStream... if the goal of this code was to copy 1,2,3 into memoryTwo, it's successful in doing so.

But even if there was something wrong with it, a developer that wants to copy from the beginning of the stream instead of from the current position needs to change the current position first.  If you know the type of the stream and you know it supports that, e.g. with a MemoryStream, you can just do so.  If you don't know the kind of the stream but you want an exception if you can't set Position, just set the Position.  Many streams have no notion of position or seeking, e.g. NetworkStream, PipeStream, etc.; the concept of copying "from the beginning" rather than "everything that remains" simply doesn't exist.

Please feel free to release a nuget package that has your desired helper as an extension method.  Developers can use your nuget package if they really need it and want to avoid writing out the literally one additional line of code.  This is not something I expect we'd want to add to Stream itself.

Thanks for the discussion.

**Comment by Mr0N** [comment] 2022-07-23 19:13
> > var memory = new MemoryStream(new byte[] {1,2,3});
> > var memoryTwo = new MemoryStream();
> > var array = memory.ToArray();
> > memory.CopyTo(memoryTwo);
> > example of a typical error
> 
> What's wrong with that? MemoryStream.ToArray doesn't change the position in the MemoryStream... if the goal of this code was to copy 1,2,3 into memoryTwo, it's successful in doing so.
> 
> But even if there was something wrong with it, a developer that wants to copy from the beginning of the stream instead of from the current position needs to change the current position first. If you know the type of the stream and you know it supports that, e.g. with a MemoryStream, you can just do so. If you don't know the kind of the stream but you want an exception if you can't set Position, just set the Position. Many streams have no notion of position or seeking, e.g. NetworkStream, PipeStream, etc.; the concept of copying "from the beginning" rather than "everything that remains" simply doesn't exist.
> 
> Please feel free to release a nuget package that has your desired helper as an extension method. Developers can use your nuget package if they really need it and want to avoid writing out the literally one additional line of code. This is not something I expect we'd want to add to Stream itself.
> 
> Thanks for the discussion.

yes, ToArray does not change, but the second one does, you have to guess which method changes what, there is no precision that the method will work, in some cases there are bugs that are difficult to determine, if there was an error, it would be a matter of minutes, in some cases, probably, even parallel streams can change position, well, that's probably the problem of the programmer who wrote it.
There is no desire to create a nuget.
Okay, I just gave an idea how to improve the streams, because I often find errors of this type that are difficult to track, but you can change them as you want, or leave them as they are.

**Comment by teo-tsirpanis** [comment] 2022-07-23 20:26
> you have to guess which method changes what, there is no precision that the method will work, in some cases there are bugs that are difficult to determine

[`Stream.CopyTo`'s documentation](https://docs.microsoft.com/el-gr/dotnet/api/system.io.stream.copyto) clearly states that "Copying _begins at the current position_ in the current stream […]" (emphasis mine). There is no room for doubt for anyone that has read the documentation.

Based on `@stephentoub`'s comments an API that copies a stream from the beginning is unlikely to be added to the BCL and so I'm going to close this issue. Thanks for the discussion @Mr0N.

**Closed by teo-tsirpanis** 2022-07-23 20:26 UTC
Labels: area-System.IO
