### ISSUE TITLE
PublishReadyToRunComposite and PublishSingleFile are making app crash

### ISSUE THREAD

**Issue by hez2010** [dotnet/runtime#55747] opened 2021-07-15 16:07 UTC
### Description
If an app is published with both PublishReadyToRunComposite and PublishSingleFile enabled, the app will crash at startup in silence.

Repro steps:

```
dotnet new console
dotnet publish -c Release -r win-x64 /p:PublishReadyToRun=true /p:PublishReadyToRunComposite=true /p:PublishSingleFile=true
```

And run the published single-file app, you will find the app is crashing at startup.

I guess it may be caused by the .r2r.dll file lookup failure.

### Configuration

.NET 6 Preview 6

**Comment by hoyosjs** [comment] 2021-07-15 18:01
cc: @dotnet/crossgen-contrib

**Comment by VSadov** [comment] 2021-07-15 23:15
Thanks for reporting the issue. It looks like the same bug as described in  https://github.com/dotnet/runtime/issues/45277

It was fixed in https://github.com/dotnet/runtime/pull/53739, but that fix was too late to be included in Preview 6

**Comment by mangod9** [comment] 2021-07-15 23:26
can we ensure this is fixed in preview7. Since #45277 was recently reopened want to ensure things are in fact working correctly.

**Comment by VSadov** [comment] 2021-07-16 01:12
@mangod9  There were no recent changes directly affecting composite r2r support in singlefile. So far I am unable to reproduce the test failure that caused reactivation of #45277. I think it could be caused by some temporary condition present in the integration test pass or by some indirect issue that was fixed since then. (any fixes/changes in crossgen ?)

It would be nice to be certain of what caused the failure, but as far as I can see composite r2r works in sdk/main and should work in Preview7.

**Comment by mangod9** [comment] 2021-07-16 01:17
Ok thanks for checking, can we try enabling the sdk test then? There were some w^x fixes which might have resolved the issue possibly

**Comment by VSadov** [comment] 2021-07-16 01:35
@mangod9 - PR to reenable the test https://github.com/dotnet/sdk/pull/18945  
I have tried a few changes as well, like intentionally forcing a failure - to see if the test behaves deterministically.

**Comment by agocke** [comment] 2021-08-13 19:14
We can't seem to get this to repro any more -- closing for now, will reopen if it pops again.

**Closed by agocke** 2021-08-13 19:14 UTC
Labels: area-Single-File
