### ISSUE TITLE
winmm.dll MidiInStart call fails on .Net Core

### ISSUE THREAD

**Issue by ruiseixasm** [dotnet/runtime#53523] opened 2021-05-30 18:42 UTC
### Description

I develop a code for receiving Midi input messages and always had an error concerning the `MidiInStart` function of the winmm.dll, always returned the value 5. This happen for C# and VB code. The code below works well for the .Net Framework!

### Code in C#

```
using System;
using System.Runtime.InteropServices;

namespace MidiNetFramework_CS1 // Doesn't work on .Net Core!
{
    class Program
    {
        [DllImport("winmm.dll", EntryPoint = "midiInGetNumDevs", CharSet = CharSet.Ansi)]
        public static extern int MidiInGetNumDevs();

        [DllImport("winmm.dll", EntryPoint = "midiInGetDevCaps", CharSet = CharSet.Ansi)]
        public static extern int MidiInGetDevCaps(uint uDeviceID, ref MIDIINCAPS InCaps, int cbMidiInCaps);

        [DllImport("winmm.dll", EntryPoint = "midiInOpen", CharSet = CharSet.Ansi)]
        public static extern int MidiInOpen(ref int lphMidiIn, uint uDeviceID, MidiInCallback dwCallback, int dwInstance, int dwFlags);

        [DllImport("winmm.dll", EntryPoint = "midiInClose", CharSet = CharSet.Ansi)]
        public static extern int MidiInClose(int hMidiIn);

        [DllImport("winmm.dll", EntryPoint = "midiInReset", CharSet = CharSet.Ansi)]
        public static extern int MidiInReset(int hMidiIn);

        [DllImport("winmm.dll", EntryPoint = "midiInStart", CharSet = CharSet.Ansi)]
        public static extern int MidiInStart(int hMidiIn);

        [DllImport("winmm.dll", EntryPoint = "midiInStop", CharSet = CharSet.Ansi)]
        public static extern int MidiInStop(int hMidiIn);

        unsafe public delegate int MidiInCallback(int hMidiIn, int wMsg, int dwInstance, int dwParam1, int dwParam2);
        public static MidiInCallback ptrCallback = new MidiInCallback(InCallback);
        public const int CALLBACK_FUNCTION = 0x30000;
        public const int MIDI_IO_STATUS = 0x20;

        public struct MIDIINCAPS
        {
            public short wMid;
            public short wPid;
            public int vDriverVersion;
            [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 32)]
            public string szPname;
            public int dwSupport;
        }

        public static int hMidiIn;
        public static object in_lock_obj = new Object();

        private static int InCallback(int hMidiIn, int wMsg, int dwInstance, int dwParam1, int dwParam2)
        {
            lock (in_lock_obj)
            {
                Console.WriteLine(wMsg + " | " + dwParam1);
            }
            return 0;
        }

        static void Main()
        {
            int deviceID = -1;
            int DeviceInCount = MidiInGetNumDevs();

            if (DeviceInCount == 0)
            {
                Console.WriteLine("No MIDI devices connected");
            }
            else
            {
                MIDIINCAPS InCaps = new MIDIINCAPS();

                for (int DevCnt = 0; DevCnt < DeviceInCount; DevCnt++)
                {
                    int error = MidiInGetDevCaps((uint)DevCnt, ref InCaps, Marshal.SizeOf(typeof(MIDIINCAPS)));
                    if (error == 0) Console.WriteLine((DevCnt + 1) + ": " + InCaps.szPname);
                }

                while (!deviceID.GetType().Equals(typeof(int)) || deviceID < 0 || deviceID >= DeviceInCount)
                {
                    Console.WriteLine("Enter the number of the chosen device");
                    deviceID = Convert.ToInt32(Console.ReadLine()) - 1;
                }

            }

            if (deviceID >= 0)
            {
                 
                int result = MidiInOpen(ref hMidiIn, (uint)deviceID, ptrCallback, 0, CALLBACK_FUNCTION | MIDI_IO_STATUS);
                if (result != 0)
                {
                    Console.WriteLine("MidiInOpen Error: " + result);
                    hMidiIn = 0;
                }
                else
                {
                    result = MidiInStart(hMidiIn);
                    if (result != 0)
                    {
                        Console.WriteLine("MidiInStart Error: " + result);
                        if (hMidiIn != 0) MidiInClose(hMidiIn);
                        hMidiIn = 0;
                    }
                    else
                        Console.WriteLine("The Device was succesfully connected! (Press Enter to exit)");
                }

                Console.ReadLine();

                if (hMidiIn != 0)
                {
                    MidiInStop(hMidiIn);
                    MidiInReset(hMidiIn);
                    MidiInClose(hMidiIn);
                    hMidiIn = 0;
                }
            }
        }
    }
}
```

### Code in VB

```
Imports System
Imports System.Runtime.InteropServices

Module Module1 'Doesn't work on .Net Core!

    Public Declare Function midiInGetNumDevs Lib "winmm.dll" () As Integer
    Public Declare Function midiInGetDevCaps Lib "winmm.dll" Alias "midiInGetDevCapsA" (ByVal uDeviceID As Integer, ByRef lpCaps As MIDIINCAPS, ByVal uSize As Integer) As Integer
    Public Declare Function midiInOpen Lib "winmm.dll" (ByRef hMidiIn As Integer, ByVal uDeviceID As Integer, ByVal dwCallback As MidiInCallback, ByVal dwInstance As Integer, ByVal dwFlags As Integer) As Integer
    Public Declare Function midiInStart Lib "winmm.dll" (ByVal hMidiIn As Integer) As Integer
    Public Declare Function midiInStop Lib "winmm.dll" (ByVal hMidiIn As Integer) As Integer
    Public Declare Function midiInReset Lib "winmm.dll" (ByVal hMidiIn As Integer) As Integer
    Public Declare Function midiInClose Lib "winmm.dll" (ByVal hMidiIn As Integer) As Integer

    Public Delegate Function MidiInCallback(ByVal hMidiIn As Integer, ByVal wMsg As UInteger, ByVal dwInstance As Integer, ByVal dwParam1 As Integer, ByVal dwParam2 As Integer) As Integer
    Public ptrCallback As New MidiInCallback(AddressOf MidiInProc)
    Public Const CALLBACK_FUNCTION As Integer = &H30000
    Public Const MIDI_IO_STATUS As Integer = &H20

    Public Structure MIDIINCAPS
        Dim wMid As Int16 ' Manufacturer ID
        Dim wPid As Int16 ' Product ID
        Dim vDriverVersion As Integer ' Driver version
        <MarshalAs(UnmanagedType.ByValTStr, SizeConst:=32)> Dim szPname As String ' Product Name
        Dim dwSupport As Integer ' Reserved
    End Structure

    Public hMidiIn As Integer
    Public in_lock_obj = New Object()

    Function MidiInProc(ByVal hMidiIn As Integer, ByVal wMsg As UInteger, ByVal dwInstance As Integer, ByVal dwParam1 As Integer, ByVal dwParam2 As Integer) As Integer
        SyncLock in_lock_obj
            Console.WriteLine(wMsg & " | " & dwParam1)
        End SyncLock
        Return 0
    End Function

    Sub Main()
        Dim deviceID As Integer = -1
        Dim DeviceInCount As Integer = midiInGetNumDevs()

        If DeviceInCount = 0 Then
            Console.WriteLine("No MIDI devices connected")
        Else
            Dim InCaps As New MIDIINCAPS

            For DevCnt As Integer = 0 To DeviceInCount - 1
                midiInGetDevCaps(DevCnt, InCaps, Len(InCaps))
                Console.WriteLine((DevCnt + 1) & ": " & InCaps.szPname)
            Next

            While VarType(deviceID) <> vbInteger Or deviceID < 0 Or deviceID >= DeviceInCount
                Console.WriteLine("Enter the number of the chosen device")
                deviceID = Convert.ToInt32(Console.ReadLine()) - 1
            End While
        End If

        If deviceID >= 0 Then

            Dim result As Integer = midiInOpen(hMidiIn, deviceID, ptrCallback, 0, CALLBACK_FUNCTION Or MIDI_IO_STATUS)

            If result <> 0 Then
                Console.WriteLine("MidiInOpen Error: " + Convert.ToString(result))
                hMidiIn = 0
            Else
                result = midiInStart(hMidiIn)

                If result <> 0 Then
                    Console.WriteLine("MidiInStart Error: " + Convert.ToString(result))
                    If hMidiIn <> 0 Then midiInClose(hMidiIn)
                    hMidiIn = 0
                Else
                    Console.WriteLine("The Device was succesfully connected! (Press Enter to exit)")
                End If

            End If

            Console.ReadLine()

            If hMidiIn <> 0 Then
                midiInStop(hMidiIn)
                midiInReset(hMidiIn)
                midiInClose(hMidiIn)
                hMidiIn = 0
            End If
        End If
    End Sub

End Module
```

### Conclusion

I don't know if this is relevant or not, but it may also happen with other DLL Imports and thus my submission.

**Comment by ManickaP** [comment] 2021-06-01 12:09
This might be a regression in .NET Core. Transferring to runtime repo to properly investigate.

**Comment by KevinCathcart** [comment] 2021-06-01 15:40
I notice that the handle size used in these P/Invoke signatures, fails to match the proper datatype of the handle. The handle is supposed to be a pointer sized integer. So while the given definitions should work in a 32 bit app, it is not guaranteed to work in a 64 bit app.

There is a similar consideration with the `dwCallback` parameter of `miniInOpen`, and last three parameters of the callback. Weirdly this also applies to the `deviceId` parameter for `midiInGetDevCaps`, due to the parameter accepting either a device ID or a handle that has been cast. Hence it needs to be pointer sized to accommodate a cast handle.

If this works on .NET Framework for a 64 bit application, then I'm pretty sure that is only is by coincidence. There is no guarantee that the runtime would leave enough padding after the `public static int hMidiIn` to ensure nothing will get corrupted by a native 64 bit write, nor is there any guarantee that when passing in those arguments, the upper 32 bits of the 64 bit register will be zero. 

I'd not be terribly surprised if both of these not guaranteed things just happened to occur for this code on .NET Framework. However there has been quite a bit of further operation of the Runtime/JIT in .NET Core/5, so I'd also be unsurprised if one of both of those no longer happened to occur.

**Comment by AaronRobinsonMSFT** [comment] 2021-06-08 02:52
@ruiseixasm Hello. Can you share out the C header files for the P/Invokes? If what @KevinCathcart is saying is true then the signatures are incorrect and will cause all sorts of invalid behavior. From Visual Studio the default for a .NET Framework project will be 32-bit but for .NET Core the typical default is 64-bit. You can try this by changing handles to `nint` in .NET 5 or to `IntPtr` which will also be a pointer size.

**Comment by ruiseixasm** [comment] 2021-06-08 08:37
@AaronRobinsonMSFT this script is based on the one shared by [FlexRadio Systems](https://github.com/TAPR/OpenHPSDR-SVN/blob/master/W5WC/PowerSDR_HPSDR_mRX_PS/Source/Console/midi.cs). So, it's strange that the .NET 5 lost backward compatibility rendering the former software useless.

In order to test the changes can you post the edited lines of code with the referred handles?

**Comment by AaronRobinsonMSFT** [comment] 2021-06-08 18:10
>So, it's strange that the .NET 5 lost backward compatibility rendering the former software useless.

This isn't an issue with .NET 5 or even a backwards compatibility issue. The problem is the example &ndash; it is only correct for a 32-bit runtime. If the code from that site was run on a 64-bit .NET Framework the failure would be the same. It would seem no one has ever attempted to run the code on a 64-bit runtime. The code can be run on .NET Core if the 32-bit version is used &ndash; use the x86 version from [here](https://dotnet.microsoft.com/download/dotnet/5.0).

Let's look at the code to understand why this is the case. The official API is declared in the Win32 [`mmeapi.h`](https://docs.microsoft.com/windows/win32/api/mmeapi/nf-mmeapi-midiinopen) header file. As an example let's look at `midiInOpen`. Below is the C declaration.

```c
WINMMAPI
MMRESULT
WINAPI
midiInOpen(
    _Out_ LPHMIDIIN phmi,
    _In_ UINT uDeviceID,
    _In_opt_ DWORD_PTR dwCallback,
    _In_opt_ DWORD_PTR dwInstance,
    _In_ DWORD fdwOpen
    );
```

The first argument is `_Out_ LPHMIDIIN phm`. We can interpret this by looking into the same header file.

```c
DECLARE_HANDLE(HMIDIIN);
typedef HMIDIIN FAR *LPHMIDIIN;
```

Decomposing this is simple in Visual Studio but can be more difficult if we just look at the header.  It seems the `LPHMIDIIN` is a pointer size type and that can be handled by the `ref` or `out` keywords in C#. However, the `HMIDIIN` obscures the fact that it too is a pointer sized data type. This means that if one uses `ref int` in C# it would only return the lower 32-bits from the `HMIDIIN` value. For a 32-bit runtime this is fine because `sizeof(void*) == 4` but on a 64-bit runtime the the following is true `sizeof(void*) == 8`. This is why the declared P/Invokes would always fail on a 64-bit runtime &ndash; the higher bits of the handle will always be lost.

This can be easily fixed using C# 9 by changing the `ref int` to a `ref nint`. If one is using an earlier C# version then `ref IntPtr` should be used.

It might be worth filing an issue or submitting a PR to that repo to properly define the declarations.

**Closed by AaronRobinsonMSFT** 2021-06-08 18:10 UTC
Labels: area-Interop-coreclr, needs more info, untriaged

**Comment by AaronRobinsonMSFT** [comment] 2021-06-08 18:51
@ruiseixasm I just checked and it appears the [CsWin32 source generator](https://github.com/microsoft/cswin32) supports the APIs in question. The generator will automatically generate the correct signature on your behalf.
