### ISSUE TITLE
Strange discrepancies between char[] and string marshaling

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#69809] opened 2022-05-25 18:21 UTC
[LibraryImport] appears to be trying to treat char[] the same as System.String in some ways but not all, and the discrepancy is very strange to me.  I was chatting about it with @AaronRobinsonMSFT earlier today, and he asked that I open an issue.

For example:
(1) [Expected due to `DisableRuntimeMarshalling`] If you don't specify a `StringMarshaling`, then `string` fails to marshal but `char[]` will be marshaled just by pinning it as a `byte*`:
```C#
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: DisableRuntimeMarshalling]

Console.WriteLine("Hello, World!");

partial class Interop
{
    [LibraryImport("SomeLib", EntryPoint = "SomeEntryPoint")]
    internal static partial int MyFunction(
        string s1, // error: SYSLIB1051 Marshalling string or char without explicit marshalling information is not supported
        char[] s2); // ok
}
```
Note that the error for s1 mentions "char" even though the `char[]` compiles fine (if you delete the `string s1` argument, it'll compile successfully).  It's ok to marshal the chars in the char[] just by pinning it, but it's not ok to do the same for string (even though that's what we do if you explicitly specify `StringMarshalling.Utf16`)?

(2) [Addressed: #69837] If you do specify a `StringMarshaling`, e.g. `StringMarshalling.Utf16`, then it all compiles, but whereas the `string` is just pinned, the `char[]` is copied back and forth:
```C#
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: DisableRuntimeMarshalling]

Console.WriteLine("Hello, World!");

partial class Interop
{
    [LibraryImport("SomeLib", EntryPoint = "SomeEntryPoint", StringMarshalling = StringMarshalling.Utf16)]
    internal static partial int MyFunction(
        string s1, // ok, marshaled by pinning
        char[] s2); // ok, marshaled by copy
}
```
It seems like this is due to the null termination guaranteed for string, but it's still a potential perf cliff that's not obvious, e.g. a developer is going to get much better perf in this example by not specifying StringMarshalling.Utf16 and instead putting [MarshalAs(UnmanagedType.LPWStr)] on the string parameter.

(3) [Expected: source generator doesn't support UTF-8 for char] `StringMarshalling.Utf8` works fine for `string` but fails for `char[]`:
```C#
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: DisableRuntimeMarshalling]

Console.WriteLine("Hello, World!");

partial class Interop
{
    [LibraryImport("SomeLib", EntryPoint = "SomeEntryPoint", StringMarshalling = StringMarshalling.Utf8)]
    internal static partial int MyFunction(
        string s1, // ok
        char[] s2); // error:SYSLIB1051 Marshalling char with 'StringMarshalling.Utf8' is not supported
}
```
This one in particular confuses me.  If `StringMarshalling` applies to `char[]`, as (2) highlights, then why doesn't `StringMarshalling.Utf8` work?

(4) Similarly, `StringMarshalling = StringMarshalling.Utf16Marshalling` applies to `char[]`, but `StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Utf16StringMarshaller)` produces an error:
```C#
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;

[assembly: DisableRuntimeMarshalling]

Console.WriteLine("Hello, World!");

partial class Interop
{
    [LibraryImport("SomeLib", EntryPoint = "SomeEntryPoint", StringMarshalling = StringMarshalling.Custom, StringMarshallingCustomType = typeof(Utf16StringMarshaller))]
    internal static partial int MyFunction(
        string s1, // ok
        char[] s2); // error: SYSLIB1051 Marshalling char with 'StringMarshalling.Custom' is not supported. To use a custom type marshaller, specify 'MarshalUsingAttribute'.
}
```

There are of course some fundamental differences between `string` and `char[]`:
- `string` is immutable (in safe code) whereas `char[]` is mutable, which means `string` can't be used for marshaling out in place
- `string` is guaranteed to have a null terminator after the data whereas `char[]` isn't

But other than that, if we're going to treat a `char[]` as a string from a marshaling perspective, I think we should aim to do so as consistently as possible.

**Comment by AaronRobinsonMSFT** [comment] 2022-05-25 18:27
I think this is worth considering. At the C interop boundary these have the same signatures, so I also find it odd that we don't treat them the same. I am assuming we are branching very early on the course `string` vs array marshalling and that is the root cause of the discrepancy. This could also become one of those annoying things to special case, but we should at least record it as a potential future opportunity for alignment.

**Comment by stephentoub** [comment] 2022-05-25 18:47
> Arrays are treated as buffers by default, and char arrays should not be an exception

I'm fine with that and it's what I was expecting the system would do until I started playing with it. It's the half-way nature of the current syatem that bothers me; either they're strings or not, and we shouldn't be in this half-way state.

**Comment by elinor-fung** [comment] 2022-05-25 19:00
I believe (1) is from `DisableRuntimeMarshalling`. With that set, we treat `char` as not needing marshalling, so we just pin the array, but `string` still requires marshalling, so we require specifying how it should be marshalled.

(2) seems like a bug. I think related to having both `DisableRuntimeMarshalling` and `StringMarshalling.Utf16`. We should look at what is going on here.

(3) I think is because we don't support UTF-8 for `char`, which propagates to not supporting it for `char[]`

**Comment by elinor-fung** [comment] 2022-08-05 22:06
We addressed some discrepancies around generation with `DisableRuntimeMarshalling` and `char` in https://github.com/dotnet/runtime/pull/69837 and https://github.com/dotnet/runtime/pull/71028. I pulled out support for treating `char[]` as a string to https://github.com/dotnet/runtime/issues/73501 and will close this in the meantime.

**Closed by elinor-fung** 2022-08-05 22:06 UTC
Labels: area-System.Runtime.InteropServices, source-generator
