### ISSUE TITLE
Internal Error in .NET Runtime

### ISSUE THREAD

**Issue by TonyValenti** [dotnet/runtime#70341] opened 2022-06-07 10:45 UTC
### Description

When I use my app, I consistently get the following error:

Application: UniversalMigrator.preview.exe
CoreCLR Version: 6.0.522.21309
.NET Version: 6.0.5
Description: The process was terminated due to an internal error in the .NET Runtime.at IP 00007FF65F4B70F1 (00007FF65F220000) with exit code 80131506.

### Reproduction Steps

Use my app.

### Expected behavior

It runs without any runtime errors.

### Actual behavior

I get runtime errors.

### Regression?

Not sure.

### Known Workarounds

None.

### Configuration

WPF, Windows 10 x64 on 6.0.5

**Comment by TonyValenti** [comment] 2022-06-07 10:48
I don't know if it helps, but it seems like the IP is slightly different in different runs:
....NET Runtime.at IP 00007FF65F30AA98 (00007FF65F220000) with exit code 80131506.
....NET Runtime.at IP 00007FF65F4B70F1 (00007FF65F220000) with exit code 80131506.

**Comment by janvorli** [comment] 2022-06-07 13:07
@TonyValenti what does your app print to the console when it fails? It should show a call stack that might help to identify the culprit.

**Comment by janvorli** [comment] 2022-06-07 15:52
@TonyValenti One thing that may help to show the stack trace - change your application type from Windows App to Console Application. It will still show the windows, but it will be able to write to the console too. This setting can be found in the project properties under Application - General - Output type.

**Comment by TonyValenti** [comment] 2022-06-09 00:54
Hi @janvorli .  Thank you so much for your help.  I have been able to recreate this issue and am attaching an example project that demonstrates the issue.  While I am experiencing this issue with ImageSharp, I think that it is actually a .NET error.  I am not sure so I'm going to create a similar issue with ImageSharp and link them here.

The Attached project simply loads an included TIFF Image:
[ConsoleApp1.zip](https://github.com/dotnet/runtime/files/8865834/ConsoleApp1.zip)

There are a few things you should notice:
1. Running the app in ```DEBUG``` mode works fine.
2. Running the app in ```RELEASE``` mode works fine.
3. Publishing the app with ```<PublishReadyToRun>True</PublishReadyToRun>``` results in an executable that will crash with the following error:
```
C:\Users\3545admin\source\repos\ConsoleApp1\ConsoleApp1\bin\Release\net6.0\publish\win-x64>ConsoleApp1.exe
STARTING
Fatal error. Internal CLR error. (0x80131506)
   at SixLabors.ImageSharp.Metadata.Profiles.Exif.IExifValue.get_Tag()
   at SixLabors.ImageSharp.Metadata.Profiles.Exif.ExifProfile.GetValueInternal(SixLabors.ImageSharp.Metadata.Profiles.Exif.ExifTag)
   at SixLabors.ImageSharp.Metadata.Profiles.Exif.ExifProfile.GetValue[[SixLabors.ImageSharp.Number, SixLabors.ImageSharp, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d998eea7b14cab13]](SixLabors.ImageSharp.Metadata.Profiles.Exif.ExifTag`1<SixLabors.ImageSharp.Number>)
   at SixLabors.ImageSharp.Formats.Tiff.TiffDecoderCore.GetImageHeight(SixLabors.ImageSharp.Metadata.Profiles.Exif.ExifProfile)
   at SixLabors.ImageSharp.Formats.Tiff.TiffDecoderCore.DecodeFrame[[SixLabors.ImageSharp.PixelFormats.Rgba32, SixLabors.ImageSharp, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d998eea7b14cab13]](SixLabors.ImageSharp.Metadata.Profiles.Exif.ExifProfile, System.Threading.CancellationToken)
   at SixLabors.ImageSharp.Formats.Tiff.TiffDecoderCore.Decode[[SixLabors.ImageSharp.PixelFormats.Rgba32, SixLabors.ImageSharp, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d998eea7b14cab13]](SixLabors.ImageSharp.IO.BufferedReadStream, System.Threading.CancellationToken)
   at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[[SixLabors.ImageSharp.PixelFormats.Rgba32, SixLabors.ImageSharp, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d998eea7b14cab13]](SixLabors.ImageSharp.Formats.IImageDecoderInternals, SixLabors.ImageSharp.Configuration, System.IO.Stream, System.Func`3<SixLabors.ImageSharp.Memory.InvalidMemoryOperationException,SixLabors.ImageSharp.Size,SixLabors.ImageSharp.InvalidImageContentException>, System.Threading.CancellationToken)
   at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[[SixLabors.ImageSharp.PixelFormats.Rgba32, SixLabors.ImageSharp, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d998eea7b14cab13]](SixLabors.ImageSharp.Formats.IImageDecoderInternals, SixLabors.ImageSharp.Configuration, System.IO.Stream, System.Threading.CancellationToken)
   at SixLabors.ImageSharp.Formats.Tiff.TiffDecoder.Decode[[SixLabors.ImageSharp.PixelFormats.Rgba32, SixLabors.ImageSharp, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d998eea7b14cab13]](SixLabors.ImageSharp.Configuration, System.IO.Stream, System.Threading.CancellationToken)
   at SixLabors.ImageSharp.Formats.Tiff.TiffDecoder.Decode(SixLabors.ImageSharp.Configuration, System.IO.Stream, System.Threading.CancellationToken)
   at SixLabors.ImageSharp.Image.Decode(System.IO.Stream, SixLabors.ImageSharp.Configuration, System.Threading.CancellationToken)
   at SixLabors.ImageSharp.Image+<>c__DisplayClass134_0.<Load>b__0(System.IO.Stream)
   at SixLabors.ImageSharp.Image.WithSeekableStream[[System.ValueTuple`2[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](SixLabors.ImageSharp.Configuration, System.IO.Stream, System.Func`2<System.IO.Stream,System.ValueTuple`2<System.__Canon,System.__Canon>>)
   at SixLabors.ImageSharp.Image.Load(SixLabors.ImageSharp.Configuration, System.IO.Stream, SixLabors.ImageSharp.Formats.IImageFormat ByRef)
   at SixLabors.ImageSharp.Image.Load(SixLabors.ImageSharp.Configuration, System.String, SixLabors.ImageSharp.Formats.IImageFormat ByRef)
   at SixLabors.ImageSharp.Image.Load(System.String)
   at Program+<Main>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Program+<Main>d__0, ConsoleApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<Main>d__0 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Program+<Main>d__0, ConsoleApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]](<Main>d__0 ByRef)
   at Program.Main(System.String[])
   at Program.<Main>(System.String[])
```

I speculate that there is something related to ReadyToRun that is not getting property generated.

What do I need to do to advance this issue further?

**Comment by TonyValenti** [comment] 2022-06-09 00:55
Also, notice that the attached project has a publishing profile that will generate the necessary executable with the error.

**Comment by brianpopow** [comment] 2022-06-09 14:29
I believe this issue is similar to a Issue reported in [ImageSharp.Drawing](https://github.com/SixLabors/ImageSharp.Drawing/issues/93).

From the stack trace in this issue and the one from ImageSharp.Drawing, I think it has something todo with `System.ValueTuple`.

**Comment by janvorli** [comment] 2022-06-09 15:13
@TonyValenti thank you a lot for the repro!

**Comment by janvorli** [comment] 2022-06-09 16:52
There seems to be a bug in the code generated by the R2R for the 
`SixLabors.ImageSharp.Formats.Tiff.TiffDecoderCore.GetImageWidth` when it calls the 
`SixLabors.ImageSharp.Metadata.Profiles.Exif.ExifValue<Number>.get_Value`. The `get_Value` is returning a struct (`Number`), and it expects that the pointer to the location of the return struct is passed in RDX. But the `GetImageWidth` doesn't set the RDX to anything. In this case, it ends up being the same as RCX and the get_Value code overwrites the method table (type) of the ExifValue<Number> object. That later results in the fatal error.

```
0:000> !u 00007fff`38dd46a9
Normal JIT generated code
SixLabors.ImageSharp.Metadata.Profiles.Exif.ExifValue`1[[SixLabors.ImageSharp.Number, SixLabors.ImageSharp]].get_Value()
ilAddr is 00007FFF84663E20 pImport is 0000021B528B2870
IL_0000: ldarg.0 
IL_0001: ldfld  class [*]SixLabors.ImageSharp.Metadata.Profiles.Ex`::<Value>k__BackingField
IL_0006: ret 
Begin 00007FFF38DD4690, size 25
00007fff`38dd4690 55              push    rbp
00007fff`38dd4691 488bec          mov     rbp,rsp
00007fff`38dd4694 48894d10        mov     qword ptr [rbp+10h],rcx
00007fff`38dd4698 48895518        mov     qword ptr [rbp+18h],rdx; rcx and rdx are both the same, pointing to a managed object that is going to get corrupted
00007fff`38dd469c 488b4510        mov     rax,qword ptr [rbp+10h]
00007fff`38dd46a0 488b5518        mov     rdx,qword ptr [rbp+18h]
00007fff`38dd46a4 8b4818          mov     ecx,dword ptr [rax+18h]
00007fff`38dd46a7 890a            mov     dword ptr [rdx],ecx  <<< This corrupts method table of a managed object
>>> 00007fff`38dd46a9 8a481c          mov     cl,byte ptr [rax+1Ch]
00007fff`38dd46ac 884a04          mov     byte ptr [rdx+4],cl
00007fff`38dd46af 488b4518        mov     rax,qword ptr [rbp+18h]
00007fff`38dd46b3 5d              pop     rbp
00007fff`38dd46b4 c3              ret
```

```
0:000> !u 00007fff`83239008
preJIT generated code
SixLabors.ImageSharp.Formats.Tiff.TiffDecoderCore.GetImageWidth(SixLabors.ImageSharp.Metadata.Profiles.Exif.ExifProfile)
ilAddr is 00007FFF84690ED0 pImport is 0000021B528B2190
Begin 00007FFF83238FC0, size 5f
00007fff`83238fc0 56              push    rsi
00007fff`83238fc1 4883ec30        sub     rsp,30h
00007fff`83238fc5 488bf1          mov     rsi,rcx
00007fff`83238fc8 ff1562277401    call    qword ptr [SixLabors_ImageSharp!SixLabors.ImageSharp.Metadata.ImageFrameMetadata.GetFormatMetadata[[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib]](SixLabors.ImageSharp.Formats.IImageFormat`2<System.__Canon,System.__Canon>)+0x36ee10 (00007fff`8497b730)]
00007fff`83238fce 488b90780a0000  mov     rdx,qword ptr [rax+0A78h]
00007fff`83238fd5 488bce          mov     rcx,rsi
00007fff`83238fd8 3909            cmp     dword ptr [rcx],ecx
00007fff`83238fda ff15b8c57601    call    qword ptr [SixLabors_ImageSharp!SixLabors.ImageSharp.Metadata.ImageFrameMetadata.GetFormatMetadata[[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib]](SixLabors.ImageSharp.Formats.IImageFormat`2<System.__Canon,System.__Canon>)+0x398c78 (00007fff`849a5598)]
00007fff`83238fe0 488bf0          mov     rsi,rax
00007fff`83238fe3 4885f6          test    rsi,rsi
00007fff`83238fe6 7510            jne     SixLabors_ImageSharp!SixLabors.ImageSharp.Formats.Tiff.TiffDecoderCore.GetImageWidth(SixLabors.ImageSharp.Metadata.Profiles.Exif.ExifProfile)+0x38 (00007fff`83238ff8)
00007fff`83238fe8 488b0df11a7a01  mov     rcx,qword ptr [SixLabors_ImageSharp!SixLabors.ImageSharp.Metadata.ImageFrameMetadata.GetFormatMetadata[[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib]](SixLabors.ImageSharp.Formats.IImageFormat`2<System.__Canon,System.__Canon>)+0x3ce1c0 (00007fff`849daae0)]
00007fff`83238fef 488b09          mov     rcx,qword ptr [rcx]
00007fff`83238ff2 ff1540077601    call    qword ptr [SixLabors_ImageSharp!SixLabors.ImageSharp.Metadata.ImageFrameMetadata.GetFormatMetadata[[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib]](SixLabors.ImageSharp.Formats.IImageFormat`2<System.__Canon,System.__Canon>)+0x38ce18 (00007fff`84999738)]
00007fff`83238ff8 488bce          mov     rcx,rsi
00007fff`83238ffb 4c8d1dee867301  lea     r11,[SixLabors_ImageSharp!SixLabors.ImageSharp.Metadata.ImageFrameMetadata.GetFormatMetadata[[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib]](SixLabors.ImageSharp.Formats.IImageFormat`2<System.__Canon,System.__Canon>)+0x364dd0 (00007fff`849716f0)]
00007fff`83239002 ff15e8867301    call    qword ptr [SixLabors_ImageSharp!SixLabors.ImageSharp.Metadata.ImageFrameMetadata.GetFormatMetadata[[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib]](SixLabors.ImageSharp.Formats.IImageFormat`2<System.__Canon,System.__Canon>)+0x364dd0 (00007fff`849716f0)]
>>> 00007fff`83239008 4889442428      mov     qword ptr [rsp+28h],rax
00007fff`8323900d 488b4c2428      mov     rcx,qword ptr [rsp+28h]
00007fff`83239012 ff15c0e07501    call    qword ptr [SixLabors_ImageSharp!SixLabors.ImageSharp.Metadata.ImageFrameMetadata.GetFormatMetadata[[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib]](SixLabors.ImageSharp.Formats.IImageFormat`2<System.__Canon,System.__Canon>)+0x38a7b8 (00007fff`849970d8)]
00007fff`83239018 90              nop
00007fff`83239019 4883c430        add     rsp,30h
00007fff`8323901d 5e              pop     rsi
00007fff`8323901e c3              ret
```
GetImageWidth source:
https://github.com/SixLabors/ImageSharp/blob/a194b9ead7e6a930f9545f63545ef7bc6bf8c96f/src/ImageSharp/Formats/Tiff/TiffDecoderCore.cs#L503-L519

**Comment by TonyValenti** [comment] 2022-06-09 19:08
@janvorli Thank you so much for digging into this.  What needs to happen to get this in front of the right person for fixing?

**Comment by jakobbotsch** [comment] 2022-06-16 14:06
The `Number` struct has following layout:
https://github.com/SixLabors/ImageSharp/blob/75dc96a27f5120451a5a8c00c75d0eaeff68437c/src/ImageSharp/Primitives/Number.cs#L13-L23

Such a struct has size 8, so it should be returned in register. So it looks like the problem is in `SixLabors.ImageSharp.Metadata.Profiles.Exif.ExifValue<Number>.get_Value` which should not be using ret-buffer. But on 7.0, I see the following codegen for that function:
```asm
; Assembly listing for method SixLabors.ImageSharp.Metadata.Profiles.Exif.ExifValue`1[Number][SixLabors.ImageSharp.Number]:get_Value():SixLabors.ImageSharp.Number:this
; Emitting BLENDED_CODE for X64 CPU with AVX - Windows
; Tier-0 compilation
; MinOpts code
; rbp based frame
; partially interruptible
; Final local variable assignments
;
;  V00 this         [V00    ] (  1,  1   )     ref  ->  [rbp+10H]   do-not-enreg[] this class-hnd
;# V01 OutArgs      [V01    ] (  1,  1   )  lclBlk ( 0) [rsp+00H]   do-not-enreg[] "OutgoingArgSpace"
;
; Lcl frame size = 0

G_M14011_IG01:              ;; offset=0000H
       55                   push     rbp
       488BEC               mov      rbp, rsp
       48894D10             mov      gword ptr [rbp+10H], rcx
                                                ;; size=8 bbWeight=1    PerfScore 2.25
G_M14011_IG02:              ;; offset=0008H
       488B4510             mov      rax, gword ptr [rbp+10H]
       488B4018             mov      rax, qword ptr [rax+24]
                                                ;; size=8 bbWeight=1    PerfScore 3.00
G_M14011_IG03:              ;; offset=0010H
       5D                   pop      rbp
       C3                   ret
                                                ;; size=2 bbWeight=1    PerfScore 1.50
```
So it might have been recently fixed. I will try to see if I can find the exact fix.

**Comment by janvorli** [comment] 2022-06-21 22:51
@jkotas you meant that he has done it in .NET 7, right?

**Comment by jkotas** [comment] 2022-06-21 22:54
Right.

**Comment by michi2525** [comment] 2022-07-21 06:00
I have also the same issue using .Net 6.0.0. My WPF application crashes unexcpectetly and the win10 event viewer shows the following:

Application: Powerunit_Soft.exe
CoreCLR Version: 6.0.21.52210
.NET Version: 6.0.0
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFC8E01CE49 (00007FFC8DFC0000) with exit code 80131506.

Faulting application name: Powerunit_Soft.exe, version: 0.3.5.0, time stamp: 0x61735063
Faulting module name: coreclr.dll, version: 6.0.21.52210, time stamp: 0x61734c6b
Exception code: 0xc0000005
Fault offset: 0x000000000005ce49
Faulting process id: 0x1b34
Faulting application start time: 0x01d89c4537f84fc7
Faulting application path: D:\Enercharge\Application\Program\Powerunit_Soft.exe
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.0\coreclr.dll
Report Id: 66926925-79c0-4659-aab0-bd92605a2e1c
Faulting package full name: 
Faulting package-relative application ID: 


Has somebody an idea how to fix that? 

BR Michael

**Comment by mangod9** [comment] 2022-08-04 05:21
@michi2525 we would need more info on your issue. This appears to be different -- is there a managed stack shown when the failure occurs? Please open a separate issue for it. 

For now will close this original issue.

**Closed by mangod9** 2022-08-04 05:21 UTC
Labels: area-crossgen2-coreclr
