### ISSUE TITLE
Consider making PooledByteBufferWriter public

### ISSUE THREAD

**Issue by pranavkm** [dotnet/runtime#53759] opened 2021-06-05 04:15 UTC
## Proposed API

ASP.NET Core has an internal copy of the [`PooledByteBufferWriter`](https://github.com/dotnet/runtime/blob/9c3a78d835a5f1f7a32824becff9f56236806de5/src/libraries/Common/src/System/Text/Json/PooledByteBufferWriter.cs) that is used in a couple of places. Replacing it with `ArrayBufferWriter<T>` that allocates arrays does not seem like a good choice. It would be great if an alternate `IBufferWriter<T>` implementation is provided that shares the same implementation as `PooledByteBufferWriter`.

```diff
+ namespace System.Buffers
+ {
+     public sealed class PooledArrayBufferWriter : IBufferWriter<T>, IDisposable
+     {
+         PooledByteBufferWriter(int initialCapacity);
+         int Capacity { get; }
+         int FreeCapacity { get; }
+         int WrittenCount { get; }
+         System.ReadOnlyMemory<T> WrittenMemory { get; }
+         System.ReadOnlySpan<T> WrittenSpan { get; }
+         void Advance(int count) { }
+         void Clear() { }
+         System.Memory<T> GetMemory(int sizeHint = 0);
+         System.Span<T> GetSpan(int sizeHint = 0);
+         void Dispose();
+     }
+ }
```

You may find the [Framework Design Guidelines](https://github.com/dotnet/runtime/blob/main/docs/coding-guidelines/framework-design-guidelines-digest.md) helpful.
-->

## Usage Examples

```C#
using var bufferWriter = new PooledByteBufferWriter();
using var writer = new Utf8JsonWriter(bufferWriter);
...
```

## Alternative Designs

Use `System.Buffers.ArrayBufferWriter<T>` and incur the allocation costs.

## Risks

* Failure to dispose the writer may result in buffers not being returned to the pool.

**Comment by GrabYourPitchforks** [comment] 2021-06-05 04:40
Duplicate of https://github.com/dotnet/runtime/issues/33598.

**Closed** 2021-06-05 04:45 UTC
Labels: api-suggestion, area-System.Buffers, untriaged
