### ISSUE TITLE
System.Text.Json.Serialization: Converter from attribute is ignored

### ISSUE THREAD

**Issue by IldarKhayrutdinov** [dotnet/runtime#97803] opened 2024-02-01 08:37 UTC
### Description

Custom converter of property type ignored from property attribute, on serializing and deserializing.

### Reproduction Steps

```
using System.Text.Json;
using System.Text.Json.Serialization;

namespace TestJson;

public class Program
{
    public static void Main(params string[]? args)
    {
        Console.WriteLine($"Runtime: {Environment.Version}");
        Console.WriteLine($"OS: {Environment.OSVersion}");

        JsonSerializerOptions options = new();

        // uncomment for workaround
        //options.Converters.Add(new MyMemoryConverter());

        var obj = new MyObject
        {
            Id = 1000,
            Memory = new MyMemory { Data = new int[] { 0, 1, 2, 3, int.MaxValue } }
        };

        string jsonText = JsonSerializer.Serialize(obj, options);
        Console.WriteLine(jsonText);

        var deserialized = JsonSerializer.Deserialize<MyObject>(jsonText, options);
        Console.WriteLine($"{deserialized.Id}; {{{string.Join(",", deserialized.Memory.Data.ToArray())}}}");
    }
}

internal class MyObject
{
    public int Id { get; set; }

    // property attribute - fails
    [JsonConverter(typeof(MyMemoryConverter))]
    public MyMemory Memory { get; set; }
}

// class attribute - works
//[JsonConverter(typeof(MyMemoryConverter))]
internal class MyMemory
{
    public Memory<int> Data { get; set; }

    public Span<int> Span => this.Data.Span;
}
```
Test project: 
[TestJson.zip](https://github.com/dotnet/runtime/files/14123610/TestJson.zip)

### Expected behavior

Works with property attribute.

### Actual behavior

Exception caused by ref type `Span`:
```
Unhandled exception. System.InvalidOperationException: The type 'System.Span`1[System.Int32]' of property 'Span' on type 'TestJson.MyMemory' is invalid for serialization or deserialization because it is a pointer type, is a ref struct, or contains generic parameters that have not been replaced by specific types.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_CannotSerializeInvalidType(Type typeToConvert, Type declaringType, MemberInfo memberInfo)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.CreatePropertyInfo(JsonTypeInfo typeInfo, Type typeToConvert, MemberInfo memberInfo, JsonSerializerOptions options, Boolean shouldCheckForRequiredKeyword, Boolean hasJsonIncludeAttribute)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.AddMembersDeclaredBySuperType(JsonTypeInfo typeInfo, Type currentType, Boolean constructorHasSetsRequiredMembersAttribute, PropertyHierarchyResolutionState& state)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.PopulateProperties(JsonTypeInfo typeInfo)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.CreateTypeInfoCore(Type type, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.GetTypeInfo(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoNoCaching(Type type)
   at System.Text.Json.JsonSerializerOptions.CachingContext.CreateCacheEntry(Type type, CachingContext context)
--- End of stack trace from previous location ---
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Nullable`1 ensureNotNull, Boolean resolveIfMutable, Boolean fallBackToNearestAncestorType)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo.Configure()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.ConfigureProperties()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.<EnsureConfigured>g__ConfigureSynchronized|172_0()
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Nullable`1 ensureNotNull, Boolean resolveIfMutable, Boolean fallBackToNearestAncestorType)
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoForRootType(Type type, Boolean fallBackToNearestAncestorType)
   at System.Text.Json.JsonSerializer.GetTypeInfo[T](JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at TestJson.Program.Main(String[] args) in C:\home\Work\TestJson\Program.cs:line 24
```

### Regression?

| Runtime \ System.Text.Json | 6.0.9 | 8.0.1 |
| ------------- | ------------- | ------------- |
| .NET 6.0.26 | OK  | ex |
| .NET 8.0.1 | ex | ex |

### Known Workarounds

Adding custom converter to `JsonSerializerOptions.Converters`:
`options.Converters.Add(new MyMemoryConverter());`

and works:
```
Runtime: 8.0.1
OS: Microsoft Windows NT 10.0.22631.0
{"Id":1000,"Memory":[0,1,2,3,2147483647]}
1000; {0,1,2,3,2147483647}
```

### Configuration

* .NET 6.0.26, .NET 8.0.1
* Windows 11 Pro 23H2 (Microsoft Windows NT 10.0.22631.0)
* x64

**Comment by eiriktsarpalis** [comment] 2024-02-01 13:18
Duplicate of https://github.com/dotnet/runtime/issues/95893

**Closed by eiriktsarpalis** 2024-02-01 13:18 UTC
Labels: area-System.Text.Json, untriaged
