### ISSUE TITLE
TarFile.ExtractToDirectory() doesn't work sometimes with compressed archives

### ISSUE THREAD

**Issue by iSazonov** [dotnet/runtime#74242] opened 2022-08-19 13:12 UTC
### Description

TarFile.ExtractToDirectoryInternal() doesn't work with some compressed archives.

The method works in examples from tests of the repo.
But it doesn't work if I try an archive created with 7-Zip or official PowerShell distributive (link is below).

If I try TarReader on the same archives I can read all entries.

Also the method works well if an archive is not compressed.

Small example archives created with 7-Zip
[examples.zip](https://github.com/dotnet/runtime/files/9382391/examples.zip)

### Reproduction Steps

1. Download https://github.com/PowerShell/PowerShell/releases/download/v7.3.0-preview.6/powershell-7.3.0-preview.6-linux-x64.tar.gz
2. Try read with simple code:
```c#
            using (var sourceStream = File.OpenRead(args[0]))
            using (var decompressorStream = new GZipStream(sourceStream, CompressionMode.Decompress))
            {
                TarFile.ExtractToDirectory(decompressorStream, args[1], true);
            }
```

### Expected behavior

The archive is unpacked well.

### Actual behavior

Exception throws:
```
Unhandled exception. System.FormatException: Could not find any recognizable digits.                                                                      at System.ParseNumbers.StringToInt(ReadOnlySpan`1 s, Int32 radix, Int32 flags, Int32& currPos)                                                         at System.Convert.ToInt32(String value, Int32 fromBase)                                                                                                at System.Formats.Tar.TarHelpers.GetTenBaseNumberFromOctalAsciiChars(Span`1 buffer)                                                                    at System.Formats.Tar.TarHeader.TryReadCommonAttributes(Span`1 buffer)                                                                                 at System.Formats.Tar.TarHeader.TryGetNextHeader(Stream archiveStream, Boolean copyData)                                                               at System.Formats.Tar.TarReader.TryGetNextEntryHeader(TarHeader& header, Boolean copyData)                                                             at System.Formats.Tar.TarReader.GetNextEntry(Boolean copyData)                                                                                         at System.Formats.Tar.TarFile.ExtractToDirectoryInternal(Stream source, String destinationDirectoryPath, Boolean overwriteFiles, Boolean leaveOpen)
```

### Configuration

.Net Preview.7

**Comment by Jozkee** [comment] 2022-08-19 16:51
I tried your scenario with 7.0.0-rc1 and didn't get the exception but I did notice that the only file extracted was ThirdPartyNotices.txt. 
cc @carlossanlop

**Comment by iSazonov** [comment] 2022-08-19 17:26
> I tried your scenario with 7.0.0-rc1 and didn't get the exception but I did notice that the only file extracted was ThirdPartyNotices.txt.

I have seen this with several archives - after successfully reading the first entry, the subsequent TarReader.GetNextEntry() returns null (for compressed file).

**Comment by carlossanlop** [comment] 2022-08-22 16:57
The repro of this issue is the same that we are tracking in https://github.com/dotnet/runtime/issues/74316  because `TarFile.ExtractToDirectory` internally uses `TarReader`.

We fixed this with https://github.com/dotnet/runtime/pull/74329 

I'll close this in favor of #74316 .

**Comment by Jozkee** [comment] 2022-08-22 18:49
> We fixed this with https://github.com/dotnet/runtime/pull/74329

@carlossanlop I'm still able to repro using the latest bits.

**Comment by carlossanlop** [comment] 2022-08-22 22:41
Had a call with @Jozkee . We found the root cause of this bug: When reading unseekable streams (like a GZipStream), and encounter a regular file entry (ThirdPartyNotices.txt) with lots of data, TarFile writes it successfully to disk, but attempting to visit the next entry fails because we not advancing the stream correctly: We should always skip the padding after the data, but the current condition is only advancing the padding if the user did not advance the whole data stream.

**Closed** 2022-08-23 06:39 UTC
Labels: area-System.IO, in-pr
