### ISSUE TITLE
DataContractSerializer no longer supports IEnumerable instances backed by LINQ OrderBy

### ISSUE THREAD

**Issue by Treit** [dotnet/runtime#34151] opened 2020-03-26 20:14 UTC
Similar to [this issue](https://github.com/dotnet/runtime/issues/724) with empty enumerables, an IEnumerable<T> that is actually backed by a LINQ OrderBy expression can no longer be serialized by DataContractSerializer in .NET Core.

This change in behavior breaks a lot of existing code at runtime.

The following code sample illustrates the problem. It works fine .NET Framework but fails on .NET Core 3.1.

    namespace Test
    {
        using System.Collections.Generic;
        using System.IO;
        using System.Linq;
        using System.Runtime.Serialization;
        
        [DataContract]
        public class TestClass
        {
            [DataMember]
            public IEnumerable<string> Stuff { get; set; }
        }
        class Program
        {
            static void Main()
            {
                TestClass t = new TestClass
                {
                    Stuff = new List<string> { "a", "b", "c" }.OrderBy(x => x)
                };
                
                DataContractSerializer dcs = new DataContractSerializer(typeof(TestClass));
                using MemoryStream stream = new MemoryStream();
                dcs.WriteObject(stream, t);
            }
        }
    }

**Comment by StephenBonikowsky** [comment] 2020-04-09 02:04
I followed-up with @mconnew from the WCF team and here is some additional context...

The concrete class returned from Linq expressions changed between .NET Framework and .NET Core. Apparently it is up to individual class owners to own the serializability of their classes and the new concrete type being returned now is not serializable.

**Comment by cston** [comment] 2020-04-10 01:00
It looks like implementations of `IEnumerable<T>` and `IEnumerable` are not automatically serializable with `DataContractSerializer` in .NET Core, although such types appear to be serializable in .NET Framework.

I will investigate further. But is this a duplicate of https://github.com/dotnet/runtime/issues/724?

cc @StephenMolloy

**Comment by mconnew** [comment] 2020-04-14 20:33
I've tracked down a code difference between .NET Framework and Core. On Core in [CollectionDataContract.IsCollectionOrTryCreate](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/CollectionDataContract.cs#L1115) we are throwing is there's no default constructor. On Framework we have the additional constraint that we only throw if the type IsSerializable otherwise we generate a potential exception message and store it in the CollectionDataContract. It looks like we then only throw if you try to deserialize (as you can't instantiate an instance) but should be fine for serializing. This delayed logic is missing in Core.

**Comment by Treit** [comment] 2020-04-20 20:35
I'm in the middle of another three-day+ investigation trying to track down yet another instance of this in our codebase that is causing runtime failures.

When I finally do find it, I will have to add yet another call to ToList() to force evaluation of the LINQ expression so it can be serialized. In fact, I will probably need to do that defensively in numerous places based on past experience.

It's painful to think of all of the unnecessary allocations this is forcing into our code base.

How much work would it be to have the same behavior as on .NET Framework? I have lost probably a couple of man-weeks of productivity trying to fix the issues caused by this change in behavior and I am sure I will run into more of them.

**Comment by HongGit** [comment] 2020-07-01 22:13
@mconnew can you please port this to 5.0?

**Closed** 2020-07-07 18:15 UTC
Labels: area-Serialization, bug
