### ISSUE TITLE
Are there currently any plans to integrate HttpClient's ProgressMessageHandler into the System.Net.Http package?

### ISSUE THREAD

**Issue by DanielRouxSA** [dotnet/runtime#89854] opened 2023-08-02 14:29 UTC
Currently, in order to elegantly get download/upload progress information from an HttpClient instance, one has to depend on the Microsoft.AspNet.WebApi.Client package, which in turn adds the arguably unneeded dependency on Newtonsoft.Json (I say arguably unneeded because in all projects in which I use HttpClient, I use System.Text.Json, and I'm sure there are many others who also use HttpClient with System.Text.Json exclusively).

It also just seems a little odd that the HttpClient still cannot, without an additional package dependency, perform progress reporting - something I'd consider essential for any client-side application that uploads or downloads files or large amounts of data.

**Comment by karelz** [comment] 2023-08-02 16:40
Is it the same as #86761 ?

**Comment by DanielRouxSA** [comment] 2023-08-02 18:13
> Is it the same as #86761 ?

Ooh, I didn't see that one when I looked for potential similar issues here. If I understand that one correctly, then yes that should accomplish essentially the same thing.

**Comment by karelz** [comment] 2023-08-02 18:27
Duplicate of #86761

**Closed by karelz** 2023-08-02 18:27 UTC
Labels: area-System.Net.Http, untriaged
