### ISSUE TITLE
Utf8JsonWriter.WriteCommentValue() method overloads behavior differently

### ISSUE THREAD

**Issue by lateapexearlyspeed** [dotnet/runtime#75075] opened 2022-09-05 07:20 UTC
### Description

Utf8JsonWriter.WriteCommentValue(string) and Utf8JsonWriter.WriteCommentValue(ReadOnlySpan of char):

```
{
  "property": 
  /*comment*/"value"
}
```

Utf8JsonWriter.WriteCommentValue(ReadOnlySpan of byte):
```
{
  "property": /*comment*/"value"
}
```

### Reproduction Steps

```cs
            MemoryStream output = new MemoryStream();
            Utf8JsonWriter writer = new Utf8JsonWriter(output, new JsonWriterOptions
            {
                Indented = true
            });
            writer.WriteStartObject();
            writer.WritePropertyName("property");

            // Switch between following 2 statements
            writer.WriteCommentValue("comment");
            // writer.WriteCommentValue(Encoding.UTF8.GetBytes("comment"));

            writer.WriteStringValue("value");
            writer.WriteEndObject();
            
            writer.Flush();

            output.Position = 0;
            using var streamReader = new StreamReader(output);
            string json = streamReader.ReadToEnd();
```

### Expected behavior

These 2 overloads make same indented json result about comment.

### Actual behavior

These 2 overloads have different indented json comment position.

### Known Workarounds

I just guess current difference is not intentional. If we should make them same, which one should we pick ?

I updated code to make them same as this one, please decide if another is better.
```
{
  "property": 
  /*comment*/"value"
}
```

Could you please have a look at this [PR](https://github.com/dotnet/runtime/pull/75074) if proper? thanks ! I will add related test after deciding which format should be picked.

**Comment by krwq** [comment] 2022-09-05 07:59
Closing this as duplicate of https://github.com/dotnet/runtime/issues/52408

**Closed** 2022-09-05 07:59 UTC
Labels: area-System.Text.Json, untriaged
