### ISSUE TITLE
Failed to read environment variable [DOTNET_STARTUP_HOOKS], HRESULT: 0x800700CB

### ISSUE THREAD

**Issue by pedoc** [dotnet/runtime#87687] opened 2023-06-16 12:56 UTC
### Description

in vs17.6.3,the following error message is displayed in eventvwr

```
Description: A .NET application failed.
Application: ServiceHub.IndexingService.exe
Path: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\ServiceHub\Hosts\ServiceHub.Host.Dotnet.x64\ServiceHub.IndexingService.exe
Message: Failed to read environment variable [DOTNET_STARTUP_HOOKS], HRESULT: 0x800700CB
```

```
Description: A .NET application failed.
Application: ServiceHub.DataWarehouseHost.exe
Path: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\ServiceHub\Hosts\ServiceHub.Host.Dotnet.x64\ServiceHub.DataWarehouseHost.exe
Message: Failed to read environment variable [DOTNET_STARTUP_HOOKS], HRESULT: 0x800700CB
```

```
Description: A .NET application failed.
Application: ServiceHub.IndexingService.exe
Path: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\ServiceHub\Hosts\ServiceHub.Host.Dotnet.x64\ServiceHub.IndexingService.exe
Message: Failed to read environment variable [DOTNET_STARTUP_HOOKS], HRESULT: 0x800700CB
```

### Reproduction Steps

Currently every launch of vs triggers this error.

### Expected behavior

no error

### Actual behavior

something went wrong

### Configuration

```
.NET SDK:
 Version:   8.0.100-preview.6.23316.2
 Commit:    5071f1f4ed

 OS Name:     Windows
 OS Version:  10.0.25393
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.6.23316.2\

Host:
  Version:      8.0.0-preview.6.23315.6
  Architecture: x64
  Commit:       35a5afb63f
```

**Comment by pedoc** [comment] 2023-06-16 13:03
If I downgrade to 7.0.7 everything works fine
```
Host:
  Version:      7.0.7
  Architecture: x64
  Commit:       5b20af47d9
```

**Comment by pedoc** [comment] 2023-06-16 13:07
works fine too
```
Host:
  Version:      8.0.0-preview.5.23280.8
  Architecture: x64
  Commit:       bc78804f5d
```

**Comment by danmoseley** [comment] 2023-06-16 16:29
other reports
https://learn.microsoft.com/en-us/answers/questions/1291663/vs2022-debugger-crash-with-error-failed-to-read-en
https://github.com/dotnet/aspnetcore/issues/48274

**Comment by vitek-karas** [comment] 2023-06-16 19:26
This is a duplicate of https://github.com/dotnet/runtime/issues/82260. It has been fixed in .NET 8. We may want to backport the fix to .NET 7 I guess.

@agocke, what do you think?

**Comment by vitek-karas** [comment] 2023-06-16 19:27
Note that this only happens because something sets the env. variable to an empty string value (instead of clearing it entirely), but the host should not do this regardless.

**Comment by agocke** [comment] 2023-06-16 20:57
Yup, worth backporting.

**Comment by pedoc** [comment] 2023-06-17 04:14
> This is a duplicate of #82260.

I don't think this is a duplicate. I didn't find it in my local environment variables, nor have I ever set this environment variable manually.

This exists in 8.0.preview.6, but not in 8.0.preview.5 and .net7, maybe a regression?

**Comment by danmoseley** [comment] 2023-06-17 15:29
That doesn't mean that VS doesn't set it though

**Comment by pedoc** [comment] 2023-06-18 01:33
> That doesn't mean that VS doesn't set it though

Makes sense, maybe there is a way to get the environment variables of the vs process (including those set by itself)?

**Comment by agocke** [comment] 2023-06-18 18:02
Closed as dup of https://github.com/dotnet/runtime/issues/82260

**Closed by agocke** 2023-06-18 18:02 UTC
Labels: area-Host, untriaged

**Comment by pedoc** [comment] 2023-07-07 07:14
This error still exist on dotnet-sdk-8.0.100-preview.7.23356.13-win-x64

**Comment by vitek-karas** [comment] 2023-07-11 11:19
The bug is fixed in 8.0 Preview 7, but the error events from VS don't come from 8.0 Preview 7 processes. VS uses a private copy of .NET runtime (which it installs into its install location), which is 6.0.*. So if we wanted to fix this in VS we would have to backport the fix to .NET 6 and wait till VS picks up the latest .NET.

@elinor-fung @agocke - what do you think about backporting this to 6? Personally, I'm in favor of doing so, the VS behavior is not nice.

**Comment by elinor-fung** [comment] 2023-07-11 15:50
I agree - I think we should propose backporting.

**Comment by DJHale** [comment] 2023-07-14 10:08
I couldn't start my executable from Visual Studio due to this issue. I could see this environment variable having an empty value using process explorer, but like others I did not set it. I had just upgraded from 17.6.4 to 17.6.5 which updated my .net 7 install from 7.0.7 to 7.0.9 when the error started.

Searching on `DOTNET_STARTUP_HOOKS` within Visual Studio's install location, I got a hit in `C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\servicehub.config.json`. This was being set to an empty string there:

```
{
  "$schema": "../../schemas/servicehub.config.schema.json",
  "controller": {
    "args": [ "$PIPE" ],
    "executable": "./ServiceHub/controller/Microsoft.ServiceHub.Controller.exe",
    "contextEnvironmentVariables": [ "VSAPPIDDIR", "VSAPPIDNAME", "VSROOTSUFFIX" ],
    "additionalEnvironmentVariables": { 
      "NODE_OPTIONS": "",
      "COMPLUS_FusionEnableForcedFullClosureWalk": "1",
      "DOTNET_STARTUP_HOOKS": "",
      "COMPlus_ThreadPool_UsePortableThreadPool": "0"
    },
    "dotnetRoot": "../dotnet/runtime"
  },
  "hosts": {
    "rootDir": "./ServiceHub/Hosts",
    "appConfigFallback": "devenv.exe.config"
  },
  "services": {
    "rootDir": "./ServiceHub/Services",
    "discoveryServices": [ "VsixServiceDiscovery", "VsixServiceDiscovery.x86" ]
  }
}
```

Removing it from `additionalEnvironmentVariables` should also resolve the issue for others until this fix filters through as an update. I did restart the machine to ensure this new config was applied correctly.
