### ISSUE TITLE
Better cancellation support for ADO.NET

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#46835] opened 2021-01-11 22:51 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Better-cancellation-support-for-ADONET/1300535)._

---
<p>Hello,<br><br>I'm using asynchronous ADO.NET operations to make some database calls. In our code we need to distinguish between retryable errors (such as deadlocks) and non-retryable ones. <br><br>A CancellationToken is passed along, but whenever this token is triggered, a SqlException is thrown. This SQL exception has SQL error number 0 and it doesn't contain an inner exception. That means I have no means of detecting whether the operation was canceled by investigating the exception. I cannot use the error code, because 0 is too generic. I cannot find an OperationCanceledException nested within. And finally the error message cannot be used either, because it could be different depending on operating system culture. So basically the SqlException doesn't tell me what's going on exactly. <br><br>I would expect an OperationCanceledException to be thrown instead. Or an OperationCanceledException nested within a SqlException, Or perhaps even an AggregateException with an OperationCanceledException and a SqlException nested within. In any way, I would expect an OperationCanceledException (or derived TaskCanceledException) at least somewhere. <br><br>I already found a way to work around this myself. It's possible to check the cancellation token within the SqlException handling block. But this just doesn't feel right. It seems to me that ADO.NET should throw an OperationCanceledException instead of wrapping the cancellation in a SqlException, which essentially hides the actual cancellation. Which is very misleading. It took me a long time to figure out what was really wrong because I was focussed on SQL error number 0 situations. <br><br>The MSDN documentation  clearly statest that ThrowCancellationRequested should be used, in order to throw an OperationCanceledException:<br><a href="https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/task-cancellation" target=_blank>https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/task-cancellation</a><br>And it seems to me that ADO.NET should do the same.<br> <br>I'd really like to hear your thoughts about this. <br>Regards,<br>Stefan Adriaenssen<br><br>Here's some code to simulate the error:<br></p><pre>static void Main(string[] args)
{
    var ct = new CancellationTokenSource();
    var task = Run(ct. Token);
    ct. CancelAfter(1000);
    task. Wait();
    Console.ReadLine();
}

static async Task Run(CancellationToken token)
        {
            using (var connection = new SqlConnection(@&quot;server=localhost;database=tempdb;Integrated Security=true&quot;))
            {
                connection. Open();
 
using (var cmd = new SqlCommand(&quot;waitfor delay '00:05:00'&quot;, connection))
                {
                    try
                    {
                        await cmd.ExecuteNonQueryAsync(token);
                    }
                    catch(AggregateException)
                    {
                        Console.WriteLine(&quot;AggregateException caught&quot;);
                    }
                    catch (OperationCanceledException)
                    {
                        Console.WriteLine(&quot;OperationCanceledException caught&quot;);
                    }
                    catch(SqlException ex)
                    {
                        Console.WriteLine(&quot;SqlException caught&quot;);
                        Console.WriteLine();
                        Console.WriteLine($&quot;Error Number: {ex. Number}&quot;);
                        Console.WriteLine($&quot;Error Code: {ex. ErrorCode}&quot;);
                        Console.WriteLine($&quot;Message: {ex. Message}&quot;);
                        Console.WriteLine($&quot;Inner exception: {(ex. InnerException?. ToString() ?? &quot;&lt;NULL&gt;&quot;)}&quot;);
                        Console.WriteLine();
                        // Only the token's IsCancellationRequested can be used, as a workaround. (An OperationCanceledException could be thrown from here)
                        Console.WriteLine($&quot;Cancellation requested by token: {token. IsCancellationRequested}&quot;);
                    }
                }
            }
        }</pre><br>
</pre>

---
#### Feedback Bot on 1/4/2021, 10:24 PM: 

Thank you for taking the time to provide your suggestion.  We will do some preliminary checks to make sure we can proceed further.  We'll provide an update once the issue has been triaged by the product team.

**Comment by roji** [comment] 2021-01-11 23:04
Duplicate of https://github.com/dotnet/SqlClient/issues/26

**Comment by roji** [comment] 2021-01-11 23:06
This question seems specific to the SqlClient provider, and so belongs in https://github.com/dotnet/SqlClient. dotnet/SqlClient#26 already tracks having SqlClient throw OperationCancelledException instead of SqlException, and also contains some help on how to identify cancellation from the current SqlException. If there are any difficulties identifying cancellation, it's recommended to open a new issue on the SqlClient repo.

**Closed by roji** 2021-01-11 23:06 UTC
Labels: untriaged
