### ISSUE TITLE
Debugging execution code in vs is slow, but the program is compiled and runs fine

### ISSUE THREAD

**Issue by notcaremath** [dotnet/runtime#78940] opened 2022-11-29 00:15 UTC
### Description

vs version 17.4.1, netcore 6.0, runs debug very slowly in vs, as if multithreading doesn’t work, but runs very fast directly after compiling.

### Reproduction Steps
```
        static HttpClient httpClient = new HttpClient();
        private static async Task run(CountdownEvent countdown)
        {
            try
            {
                Console.WriteLine(Thread.CurrentThread.ManagedThreadId);
                for (int i = 0; i < 1000; i++)                {
                    var task = await httpClient.GetAsync("http://10.0.3.222:8087/");
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }
            Console.WriteLine("release");
            countdown.Signal();
        }
        [STAThread]
        public static void Main(string[] args)
        {

            Console.WriteLine("start");
            CountdownEvent countdown = new CountdownEvent(32);
            Stopwatch stopwatch = Stopwatch.StartNew();
            for (int i = 0; i < 32; i++)
            {
                Task.Run(() => run(countdown));
            }
            countdown.Wait();
            Console.WriteLine(stopwatch.ElapsedMilliseconds);
            Console.WriteLine("end");
            Console.ReadLine();
}
```
### Expected behavior

Expect debugging execution in vs to be the same as post-compile execution, but vs is particularly slow, as if multithreading doesn't work, but executing exe files after compile is normal

### Actual behavior

This is a simple console application that submitted a question in vs, but received no feedback, so we can only hope for that

**Comment by tommcdon** [comment] 2022-12-01 14:52
Hi @notcaremath!  Thanks for the bug report!  To help us understand the issue better, are there any exceptions being thrown (these will be included into the output window) or are there any breakpoints being set when running the application?  When I ran the application from Visual Studio, both Control-F5 (launch without debugging) and F5 (debug) both were equally slow because `http://10.0.3.222:8087/` didn't resolve.  Was that an intentional part of the reproducible test case or should we change the address to something that will resolve?

**Comment by notcaremath** [comment] 2022-12-04 09:05
> 嗨@notcaremath！感谢您的错误报告！为了帮助我们更好地理解问题，是否抛出任何异常（这些异常将包含在输出窗口中）或在运行应用程序时是否设置了任何断点？当我从Visual Studio运行应用程序时，Control-F5（启动而不调试）和F5（调试）都同样慢，因为没有解决。这是可重现测试用例的有意部分，还是我们应该将地址更改为可以解决的内容？`http://10.0.3.222:8087/`
Without setting any breakpoints, starting without debugging (Control-F5) is running normally very fast. The debug run is very slow, http://10.0.3.222:8087/ is just a test site and can be replaced with any one.

**Comment by tommcdon** [comment] 2022-12-05 23:27
Thank you @notcaremath!  We will take a look at this issue.  It is possible this is related to https://github.com/dotnet/runtime/issues/38736

**Comment by tommcdon** [comment] 2023-07-17 23:03
Closing as this is a dupe to #38736

**Closed by tommcdon** 2023-07-17 23:03 UTC
Labels: area-Diagnostics-coreclr
