### ISSUE TITLE
Random.NextSingle returns 1.0

### ISSUE THREAD

**Issue by luithefirst** [dotnet/runtime#85016] opened 2023-04-18 22:53 UTC
### Description

According to the documentation Random.NextSingle() should generate a float in [0, 1): "Returns a random floating-point number that is greater than or equal to 0.0, and less than 1.0"

### Reproduction Steps

```
var rnd = new Random(0);
for (int i = 0; i < 10000000; i++)
    if (rnd.NextSingle() == 1.0)
        throw new Exception("Random.NextSingle is 1.0!");
```

### Expected behavior

Random.NextSingle() generates values in [0, 1)

### Actual behavior

Random.NextSingle() generates values in [0, 1]

### Configuration

I could reproduce this with .net 6.0 and 7.0 (have not tested any other)

**Comment by ygra** [comment] 2023-04-24 07:48
AFAIK Random has two different algorithms inside of it: The old .NET Framework one for compatibility which is used whenever a seed is given, and a newer, better, faster, ~stronger~ one for the no-seed case. The latter does not seem to exhibit this behaviour.

**Comment by koszeggy** [comment] 2023-04-25 08:50
The problem is that the implementation of the new `NextSingle` method that was introduced in .NET 6 is just a [cast](https://github.com/dotnet/runtime/blob/5be5b9e73bbab5ed0d94d200cb363564291fbaeb/src/libraries/System.Private.CoreLib/src/System/Random.Net5CompatImpl.cs#L86) from `double` when the compatible algo is used:

```cs
public override float NextSingle() => (float)_prng.Sample();
```

It's obviously not correct as it can round up to 1 even if the original sample was less than 1.
It can be fixed by a simple `while` loop.

**Note:** The issue [affects](https://github.com/dotnet/runtime/blob/5be5b9e73bbab5ed0d94d200cb363564291fbaeb/src/libraries/System.Private.CoreLib/src/System/Random.Net5CompatImpl.cs#L197) also derived `Random` classes that do not override `NextSingle`.

**Comment by luithefirst** [comment] 2023-04-25 10:15
I've also looked at other random generators and for float they use a random int32 value and "scale" to desired output with a bit operation and a constant.

**Closed** 2023-04-25 16:02 UTC
Labels: area-System.Runtime, untriaged, in-pr
