### ISSUE TITLE
[API Proposal]: Make the Task.CancellationToken property public

### ISSUE THREAD

**Issue by theodorzoulias** [dotnet/runtime#62006] opened 2021-11-24 06:21 UTC
### Background and motivation

When a [`Task`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task) is canceled, it stores internally the [`CancellationToken`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.cancellationtoken) that caused its cancellation. When this `Task` is later awaited, an [`OperationCanceledException`](https://docs.microsoft.com/en-us/dotnet/api/system.operationcanceledexception) is thrown, that has the associated `CancellationToken` stored in its [`CancellationToken`](https://docs.microsoft.com/en-us/dotnet/api/system.operationcanceledexception.cancellationtoken) property. This mechanism allows the propagation of the originating `CancellationToken`, but it requires that the exception is thrown and caught. It's not possible to observe it without using the `try`/`catch` language construct. And `throwing`+`catching` exceptions [is quite expensive](https://stackoverflow.com/questions/891217/how-expensive-are-exceptions-in-c "How expensive are exceptions in C#?").

The `Task` type [already has](https://referencesource.microsoft.com/mscorlib/system/threading/tasks/Task.cs.html#60cc1dfe1994edea) a `CancellationToken` property, but unfortunately it's `internal`. My suggestion is to turn this property from `internal` to `public`, so that the originating `CancellationToken` can be observed efficiently.

### API Proposal

```diff
/// <summary>
- /// This internal property provides access to the CancellationToken that was set on the task 
- /// when it was constructed.
+ /// Gets the <see cref="CancellationToken">CancellationToken</see> that caused
+ /// this <see cref="Task">Task</see> instance to complete as canceled.
/// </summary>
- internal CancellationToken CancellationToken
+ public CancellationToken CancellationToken
{
    get
    {
        var props = m_contingentProperties;
        return (props == null) ? default(CancellationToken) : props.m_cancellationToken;
    }
}
```

### API Usage

Library authors will be able to replace inefficient and verbose code like this:

```C#
if (task.IsCanceled)
{ 
    try
    {
        task.WaitAndUnwrapException();
    }
    catch (OperationCanceledException exception)
    {
        var token = exception.CancellationToken;
        return token.IsCancellationRequested ?
            @this.TrySetCanceled(token) : @this.TrySetCanceled();
    }
}
```

...with efficient and streamlined code like this:

```C#
if (task.IsCanceled)
{ 
    var token = task.CancellationToken;
    return token.IsCancellationRequested ?
        @this.TrySetCanceled(token) : @this.TrySetCanceled();
}
```

This example is taken from the [Nito.AsyncEx.Tasks](https://www.nuget.org/packages/Nito.AsyncEx.Tasks/) library ([`TaskCompletionSourceExtensions.TryCompleteFromCompletedTask`](https://github.com/StephenCleary/AsyncEx/blob/0361015459938f2eb8f3c1ad1021d19ee01c93a4/src/Nito.AsyncEx.Tasks/TaskCompletionSourceExtensions.cs#L20) extension method).

### Alternative Designs

The existing internal `Task.CancellationToken` property can be currently invoked through reflection. The disadvantages are obvious (overhead, forward compatibility etc).

It is also possible to get the `Task.CancellationToken` by instantiating a [`TaskCanceledException`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskcanceledexception) object:

```C#
var cancellationToken = new TaskCanceledException(task).CancellationToken;
```

### Risks

None that I can think of.

**Comment by buyaa-n** [comment] 2021-11-24 22:07
> This mechanism allows the propagation of the originating `CancellationToken`, but it requires that the exception is thrown and caught. It's not possible to observe it without using the `try/catch` language construct
> 
> My suggestion is to turn this property from `internal` to `public`, so that the originating `CancellationToken` can be observed efficiently.

I think even if we make the `CancellationToken` property `public` you will still need to catch the exception because the `task` you are observing would still need to throw when the cancellation is requested, which mean it could throw while you are observing the token and checking `token.IsCancellationRequested` and trying to do the action the exception could throw.  It doesn't seem like you could/should handle it without try-catch even with public `CancellationToken` property

Correct me if I'm wrong @stephentoub

**Comment by theodorzoulias** [comment] 2021-11-25 00:50
@buyaa-n true, common application code will typically `await` the task, and incur the cost of handling the `OperationCanceledException`. But currently library code has to do the same also, doubling the final cost. [Here is](https://dotnetfiddle.net/c7irs1) a fiddle demo that measures the impact of intercepting a trivial `HideIdentityOfCanceledTask` extension method for `Task` objects. Two implementations are compared, one that uses try/catch and one that uses reflection. The try/catch version reduces the throughput in half. Sample output:

```none
Canceled task, iterations per second: 70,310
Try/catch wrapper, iterations per second: 37,296
Reflection wrapper, iterations per second: 69,949
```

**Comment by theodorzoulias** [comment] 2022-08-01 16:31
I mentioned in the proposal an additional workaround, beyond using reflection. The `Task.CancellationToken` can be observed by instantiating a [`TaskCanceledException`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskcanceledexception) object, and reading the `CancellationToken` property:

```C#
if (task.IsCanceled)
{
    var cancellationToken = new TaskCanceledException(task).CancellationToken;
}
```

**Comment by stephentoub** [comment] 2022-09-02 01:09
What is the use case for this?  Is it purely about implementing a method that transfers a task's completion information to a TaskCompletionSource?  There's a separate proposal for exposing such an operation directly.

**Comment by theodorzoulias** [comment] 2022-09-03 00:23
@stephentoub yes, my personal use case is, for example, for implementing the [`Then`](https://github.com/dotnet/runtime/issues/58692) operator. I need to cancel a `TaskCompletionSource<T>` with the same token as the antecedent task, and I could use the requested `Task.CancellationToken` API like this:

```C#
public static Task<TNewResult> Then<TResult, TNewResult>(
    this Task<TResult> source,
    Func<TResult, TNewResult> continuationFunction)
{
    return source.ContinueWith(t =>
    {
        if (t.IsCanceled)
        {
            var tcs = new TaskCompletionSource<TNewResult>();
            tcs.SetCanceled(t.CancellationToken); // <--- API Usage
            return tcs.Task;
        }
        if (t.IsFaulted)
        {
            var tcs = new TaskCompletionSource<TNewResult>();
            tcs.SetException(t.Exception.InnerExceptions);
            return tcs.Task;
        }
        var newResult = continuationFunction(t.Result);
        return Task.FromResult(newResult);
    }, default, TaskContinuationOptions.ExecuteSynchronously,
        TaskScheduler.Current).Unwrap();
}
```

Currently I am using as workaround a [`TaskCanceledException`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.taskcanceledexception), which gets the job done but it's a bit artificial:

```C#
if (t.IsCanceled)
{
    var tcs = new TaskCompletionSource<TNewResult>();
    var tce = new TaskCanceledException(t);
    tcs.SetCanceled(tce.CancellationToken);
    return tcs.Task;
}
```

**Comment by stephentoub** [comment] 2023-01-21 21:48
Closing as a duplicate of https://github.com/dotnet/runtime/issues/47998.

**Closed by stephentoub** 2023-01-21 21:48 UTC
Labels: api-suggestion, area-System.Threading.Tasks
