### ISSUE TITLE
Test failure: System.Net.Tests.HttpWebRequestTest_Sync.Timeout_Set30MillisecondsOnLoopback_ThrowsWebException

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#46280] opened 2020-12-21 06:53 UTC
failed in job: [runtime-coreclr libraries-jitstressregs 20201220.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=927836&view=ms.vss-test-web.build-test-results-tab&runId=29414464&resultId=154804&paneView=debug)

failed tests: 
System.Net.Tests.HttpWebRequestTest_Sync.Timeout_Set30MillisecondsOnLoopback_ThrowsWebException
System.Net.Tests.HttpWebRequestTest_Async.Timeout_Set30MillisecondsOnLoopback_ThrowsWebException

net6.0-windows-Release-x86-CoreCLR_checked-jitstressregs3-Windows.10.Amd64.Open

Error message
~~~
Assert.InRange() Failure
Range:  (1 - 15000)
Actual: 20669


Stack trace
   at System.Net.Tests.HttpWebRequestTest.<Timeout_Set30MillisecondsOnLoopback_ThrowsWebException>b__38_0(LoopbackServer server, Uri url)
   at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass12_0.<CreateServerAsync>b__0(LoopbackServer server) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 78
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /_/src/libraries/Common/tests/System/Net/Http/LoopbackServer.cs:line 72
   at System.Net.Tests.HttpWebRequestTest.Timeout_Set30MillisecondsOnLoopback_ThrowsWebException() in /_/src/libraries/System.Net.Requests/tests/HttpWebRequestTest.cs:line 516
--- End of stack trace from previous location ---
~~~

**Comment by wfurt** [comment] 2020-12-21 17:53
This is time sensitive test and it probably does not make sense to run under JitStress.
Is there good way how to exclude it @BruceForstall? The timing is clearly way off.

**Comment by karelz** [comment] 2021-01-06 13:07
Looks like by design one off failure under JitStress, closing.

**Closed by karelz** 2021-01-06 13:07 UTC
Labels: JitStress, area-System.Net, untriaged
