### ISSUE TITLE
Marshal.GetDelegateForFunctionPointer complains about delegate being a generic type definition

### ISSUE THREAD

**Issue by kekekeks** [dotnet/runtime#36110] opened 2020-05-08 12:10 UTC
```cs
class Foo<T>
{
    public delegate void Bar();
}

public static class Program
{
    public static void Main()
    {
        Marshal.GetDelegateForFunctionPointer<Foo<object>.Bar>(new IntPtr(123));
    }
}
```

>System.ArgumentException: The specified Type must not be a generic type definition.

The specified delegate is not a generic type definition. `typeof(Foo<object>.Bar).IsGenericTypeDefinition` returns `false`.

**Comment by svick** [comment] 2020-05-08 12:59
Contrary to what the exception message says, this is the correct behavior and [it is documented as such](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.getdelegateforfunctionpointer?view=netcore-3.1#System_Runtime_InteropServices_Marshal_GetDelegateForFunctionPointer__1_System_IntPtr_).

What is it that you're asking for? If it's to make this code work, then this is a duplicate of https://github.com/dotnet/runtime/issues/13197. Or is it to change the exception message to make it accurate?

**Comment by kekekeks** [comment] 2020-05-08 13:27
>to change the exception message to make it accurate

Would be really nice to avoid confusion, yes

**Comment by AaronRobinsonMSFT** [comment] 2020-05-10 05:52
> > to change the exception message to make it accurate
> 
> Would be really nice to avoid confusion, yes

@kekekeks Here is what I am seeing:

```CSharp
typeof(Foo<object>.Bar).IsGenericTypeDefinition; // false
typeof(Foo<object>.Bar).IsGenericType; // true
```

For the message, would you expect to see the word "definition" dropped?

**Comment by kekekeks** [comment] 2020-05-10 10:34
Ideally I'd like the runtime to not complain about the delegate without any generic parameters in its signature, but yes, the message should at least properly describe what's wrong with the delegate.

**Closed** 2020-05-14 13:54 UTC
Labels: area-Interop-coreclr, untriaged
