### ISSUE TITLE
[6.0] Test failures on OSX: OSVersion_ValidVersion_OSX, CurrencyNegativePattern_Get_ReturnsExpected_ByLocale

### ISSUE THREAD

**Issue by CarnaViire** [dotnet/runtime#80252] opened 2023-01-05 18:41 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=125170
Build error leg or test failing: `System.Tests.EnvironmentTests.OSVersion_ValidVersion_OSX`, `System.Globalization.Tests.NumberFormatInfoCurrencyNegativePattern.CurrencyNegativePattern_Get_ReturnsExpected_ByLocale(locale: \"es-BO\")`
Pull request: https://github.com/dotnet/runtime/pull/79549, https://github.com/dotnet/runtime/pull/80190, https://github.com/dotnet/runtime/pull/80209

Failing Configurations (3)
```
net6.0-OSX-Debug-x64-CoreCLR_checked-OSX.1200.Amd64.Open
net6.0-OSX-Debug-x64-CoreCLR_release-OSX.1200.Amd64.Open
net6.0-OSX-Debug-x64-Mono_release-OSX.1200.Amd64.Open
```

Related/potential cause: https://github.com/dotnet/runtime/pull/80030

## Error Message
1) `System.Tests.EnvironmentTests.OSVersion_ValidVersion_OSX`

Exception Message
```
Assert.Contains() Failure
Not found: 12.4
In value:  osx.11.1-x64
```
CallStack
```
   at System.Tests.EnvironmentTests.OSVersion_ValidVersion_OSX() in /_/src/libraries/System.Runtime.Extensions/tests/System/EnvironmentTests.cs:line 193
```

2)  `System.Globalization.Tests.NumberFormatInfoCurrencyNegativePattern.CurrencyNegativePattern_Get_ReturnsExpected_ByLocale(locale: \"es-BO\")`

Exception Message
```
Assert.Contains() Failure
Not found: 12
In value:  Int32[] [1]
```
Stack Trace
```
   at System.Globalization.Tests.NumberFormatInfoCurrencyNegativePattern.CurrencyNegativePattern_Get_ReturnsExpected_ByLocale(String locale) in /_/src/libraries/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoCurrencyNegativePattern.cs:line 56
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by carlossanlop** [comment] 2023-01-11 01:11
Here's an example of a failing test happening in the internal->public merge PR for 6.0:
- PR: https://github.com/dotnet/runtime/pull/80452/checks?check_run_id=10562386944
- Job result: https://dev.azure.com/dnceng-public/public/_build/results?buildId=132447&view=logs&j=c6f8dc49-92a1-5760-c098-ba97b8142bfb&t=5d5289b6-723b-5155-5d15-b590d280a14a&l=60
- Callstack: https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-80452-merge-0a7bcaf1408544f1a2/System.Globalization.Tests/1/console.d1046adc.log?helixlogtype=result
- The failure is happening here: https://github.com/dotnet/runtime/blob/release/6.0/src/libraries/System.Globalization/tests/NumberFormatInfo/NumberFormatInfoCurrencyNegativePattern.cs#L56

**Comment by tarekgh** [comment] 2023-01-11 01:43
@carlossanlop this looks to me the [OS detection](https://github.com/dotnet/runtime/blob/7ac3cde6be0d10e0bb8d6e5fe0b95eeca549e2b8/src/libraries/Common/tests/TestUtilities/System/PlatformDetection.Unix.cs#L42) is the culprit here and not the test itself. This may explain the other Environment test failure which is same.

**Comment by ViktorHofer** [comment] 2023-01-11 14:02
I agree with Tarek that this needs to be investigated, ideally before next servicing release's code-complete as the failures might indicate a product regression.

**Comment by tarekgh** [comment] 2023-01-11 15:17
https://github.com/dotnet/runtime/issues/44120

**Comment by akoeplinger** [comment] 2023-01-11 15:38
The OSVersion_ValidVersion_OSX test isn't that concerning, it's just a test issue regarding how the version is checked.

The CurrencyNegativePattern_Get_ReturnsExpected_ByLocale was fixed by https://github.com/dotnet/runtime/pull/63971 so we'd need to backport that to 6.0

**Comment by akoeplinger** [comment] 2023-01-12 15:39
@tarekgh I see we're at least missing this change to the test from this commit in 6.0: https://github.com/dotnet/runtime/commit/5da4464f42bd8b790909f2d2b50d80922e3cf934#diff-3b1296c3b8a733ad1c027de7b5c653d0843afcc959cf9b2656160a9dcf8c0aa5R193-R194

But that doesn't explain the full story since we're still getting `12` from Environment.OSVersion vs. `11` from RuntimeInformation.RuntimeIdentifier.

**Comment by akoeplinger** [comment] 2023-01-12 16:39
https://github.com/dotnet/runtime/pull/80560

**Comment by tarekgh** [comment] 2023-01-13 17:19
Fixed by https://github.com/dotnet/runtime/pull/80560

**Closed by tarekgh** 2023-01-13 17:19 UTC
Labels: area-System.Runtime, os-mac-os-x, blocking-clean-ci, untriaged, Known Build Error
