### ISSUE TITLE
Android crash when using AOT+LLVM

### ISSUE THREAD

**Issue by jonathanpeppers** [dotnet/runtime#79910] opened 2022-12-22 16:46 UTC
### Description

A customer's app is crashing only when `$(EnableLLVM)` is enabled.

I got line numbers by doing:
```
adb logcat -d > C:\log.txt
dotnet-symbol 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.android-arm64\7.0.1\runtimes\android-arm64\native\*'
ndk-stack -sym 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Runtime.Mono.android-arm64\7.0.1\runtimes\android-arm64\native' -dump C:\log.txt
```

The crash is:
```
********** Crash dump: **********
Build fingerprint: 'google/redfin/redfin:13/TP1A.221005.002/9012097:user/release-keys'
#00 0x0000000000051894 /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: 058e3ec96fa600fb840a6a6956c6b64e)
#01 0x00000000000474c8 /data/app/~~USuUQdZNFd52WLb7f79NXQ==/com.redacted-iLJ2vTRBBCSbkg8Vh7AMhA==/lib/arm64/libmonodroid.so (xamarin::android::internal::MonodroidRuntime::mono_log_handler(char const*, char const*, char const*, int, void*)+144) (BuildId: 85d3f18c6abc71365f9a1ce3e09a7446559a1364)
#02 0x00000000002da93c /data/app/~~USuUQdZNFd52WLb7f79NXQ==/com.redacted-iLJ2vTRBBCSbkg8Vh7AMhA==/lib/arm64/libmonosgen-2.0.so (BuildId: 35954d8053e3b73f2ec2c546186f7ececef5e3b5)
                                                                                                                                          monoeg_g_logstr
                                                                                                                                          /__w/1/s/src/mono/mono/eglib/goutput.c:151:2
                                                                                                                                          monoeg_g_logv_nofree
                                                                                                                                          /__w/1/s/src/mono/mono/eglib/goutput.c:166:2
#03 0x00000000002daa68 /data/app/~~USuUQdZNFd52WLb7f79NXQ==/com.redacted-iLJ2vTRBBCSbkg8Vh7AMhA==/lib/arm64/libmonosgen-2.0.so (BuildId: 35954d8053e3b73f2ec2c546186f7ececef5e3b5)
                                                                                                                                          monoeg_assertion_message
                                                                                                                                          /__w/1/s/src/mono/mono/eglib/goutput.c:207:22
#04 0x00000000002daaac /data/app/~~USuUQdZNFd52WLb7f79NXQ==/com.redacted-iLJ2vTRBBCSbkg8Vh7AMhA==/lib/arm64/libmonosgen-2.0.so (BuildId: 35954d8053e3b73f2ec2c546186f7ececef5e3b5)
                                                                                                                                          mono_assertion_message
                                                                                                                                          /__w/1/s/src/mono/mono/eglib/goutput.c:226:2
#05 0x0000000000252f50 /data/app/~~USuUQdZNFd52WLb7f79NXQ==/com.redacted-iLJ2vTRBBCSbkg8Vh7AMhA==/lib/arm64/libmonosgen-2.0.so (BuildId: 35954d8053e3b73f2ec2c546186f7ececef5e3b5)
                                                                                                                                          mono_aot_plt_resolve
                                                                                                                                          /__w/1/s/src/mono/mono/mini/aot-runtime.c:5076:2
#06 0x0000000000265b18 /data/app/~~USuUQdZNFd52WLb7f79NXQ==/com.redacted-iLJ2vTRBBCSbkg8Vh7AMhA==/lib/arm64/libmonosgen-2.0.so (BuildId: 35954d8053e3b73f2ec2c546186f7ececef5e3b5)
                                                                                                                                          mono_aot_plt_trampoline
                                                                                                                                          /__w/1/s/src/mono/mono/mini/mini-trampolines.c:914:8
#07 0x0000000000004f00 <anonymous:732cdbc000>
Crash dump is completed
```

Right before the crash, I can see some of the following managed methods being called:
```
12-22 10:34:51.364  3266  3266 D Mono    : AOT: NOT FOUND: Microsoft.Xna.Framework.Input.Touch.TouchLocation:UpdateState (Microsoft.Xna.Framework.Input.Touch.TouchLocation).
12-22 10:34:51.364  3266  3266 D Mono    : AOT: NOT FOUND: Microsoft.Xna.Framework.Vector2:op_Subtraction (Microsoft.Xna.Framework.Vector2,Microsoft.Xna.Framework.Vector2).
12-22 10:34:51.364  3266  3266 D Mono    : AOT: NOT FOUND: Microsoft.Xna.Framework.Vector2:op_Division (Microsoft.Xna.Framework.Vector2,single).
12-22 10:34:51.365  3266  3266 D Mono    : AOT: NOT FOUND: Microsoft.Xna.Framework.Vector2:op_Multiply (Microsoft.Xna.Framework.Vector2,single).
12-22 10:34:51.365  3266  3266 D Mono    : AOT: NOT FOUND: Microsoft.Xna.Framework.Vector2:op_Addition (Microsoft.Xna.Framework.Vector2,Microsoft.Xna.Framework.Vector2).
12-22 10:34:51.365  3266  3266 D Mono    : AOT: NOT FOUND: Microsoft.Xna.Framework.Vector2:LengthSquared ().
```

But I don't see any intrinsics or anything special here:

https://github.com/MonoGame/MonoGame/blob/develop/MonoGame.Framework/Vector2.cs

### Reproduction Steps

I don't have a self-contained repro, but I have access to the customer's source code.

### Expected behavior

`$(EnableLLVM)` doesn't cause a crash.

### Actual behavior

`$(EnableLLVM)` causes a crash.

### Regression?

The app was first ported from Xamarin to .NET 7, so we don't know if this worked in .NET 6.

### Known Workarounds

Use `EnableLLVM=false`.

### Configuration

```
> dotnet --version
7.0.101
```
Also using dotnet/runtime 7.0.1.

### Other information

I can send other logs & information privately, let me know.

**Comment by jonathanpeppers** [comment] 2022-12-22 16:55
/cc @fanyang-mono @vargaz 

(I can't tell if the area path bot is working)

**Comment by SamMonoRT** [comment] 2022-12-22 17:15
We haven't done any intrinsic implementations for Vector2 - that would is tracked by https://github.com/dotnet/runtime/issues/73462 , so it should not be related to intrinsics.

**Comment by SamMonoRT** [comment] 2022-12-22 17:15
Adding 7.0.x milestone and assigning to @vargaz for initial look.

**Comment by jonathanpeppers** [comment] 2022-12-22 17:52
We discovered turning off profiled AOT also solves the problem.

So, this combination works:
```xml
<RunAOTCompilation>true</RunAOTCompilation>
<AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
<EnableLLVM>true</EnableLLVM>
```

It must be the interaction between profiled AOT & LLVM.

This seems similar to some of the other issues we saw in the past like #77319, #73003.

**Comment by vargaz** [comment] 2022-12-23 01:30
Its this line in mono_aot_plt_resolve ():
```
	plt_entry = mono_aot_get_plt_entry (regs, code);
	g_assert (plt_entry);
```

**Comment by vargaz** [comment] 2022-12-23 01:38
Maybe related to:
https://github.com/xamarin/xamarin-android/commit/e1f2198e8a84f3e1fb17c8ee7332ee3ce475274e

**Comment by vargaz** [comment] 2023-01-02 02:03
What does enabling AndroidEnableProfiledAot do ? What profile is it using ?

**Comment by james-allison** [comment] 2023-01-02 09:18
I'm seeing this problem in an app I'm moving from Xamarin Forms to MAUI dotnet 7.  The app crashes with no obvious trigger after 'some time' when built with AOT and LLVM optimisations. It doesn't seem to matter if Startup Tracing is enabled (ProfiledAOT) - though perhaps it lasts a little longer before crashing? 

The app is stable without LLVM optimisations. Disabling startup tracing (Profiled AOT) alone doesn't stop the crashes  - though perhaps it lasts a little longer before crashing?  I'm using Visual Studio 17.4.3 (dotnet MAUI 7.0.52)

`*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 17246 >>> uk.co.hippocamp.murmur <<<

backtrace:
  #00  pc 0x00000000000531f4  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164)
  #01  pc 0x00000000000474c8  /data/app/~~ryOlypuMVi1mciMPBrTz-Q==/uk.co.hippocamp.murmur-gkLwLmRJ8PAnc-_1QUBz7w==/split_config.arm64_v8a.apk!libmono-android.release.so (xamarin::android::internal::MonodroidRuntime::mono_log_handler(char const*, char const*, char const*, int, void*)+144)
  #02  pc 0x00000000002da93c  /data/app/~~ryOlypuMVi1mciMPBrTz-Q==/uk.co.hippocamp.murmur-gkLwLmRJ8PAnc-_1QUBz7w==/split_config.arm64_v8a.apk!libmonosgen-2.0.so
  #03  pc 0x00000000002daa68  /data/app/~~ryOlypuMVi1mciMPBrTz-Q==/uk.co.hippocamp.murmur-gkLwLmRJ8PAnc-_1QUBz7w==/split_config.arm64_v8a.apk!libmonosgen-2.0.so
  #04  pc 0x00000000002daaac  /data/app/~~ryOlypuMVi1mciMPBrTz-Q==/uk.co.hippocamp.murmur-gkLwLmRJ8PAnc-_1QUBz7w==/split_config.arm64_v8a.apk!libmonosgen-2.0.so
  #05  pc 0x0000000000252f50  /data/app/~~ryOlypuMVi1mciMPBrTz-Q==/uk.co.hippocamp.murmur-gkLwLmRJ8PAnc-_1QUBz7w==/split_config.arm64_v8a.apk!libmonosgen-2.0.so
  #06  pc 0x0000000000265b18  /data/app/~~ryOlypuMVi1mciMPBrTz-Q==/uk.co.hippocamp.murmur-gkLwLmRJ8PAnc-_1QUBz7w==/split_config.arm64_v8a.apk!libmonosgen-2.0.so
  #07  pc 0x0000000000004f00 `

**Comment by jonathanpeppers** [comment] 2023-01-03 04:06
> What does enabling AndroidEnableProfiledAot do ? What profile is it using ?

It is on by default, all it does is pass this profile or not:

https://github.com/xamarin/xamarin-android/blob/main/src/profiled-aot/dotnet.aotprofile

Since we don't have good support for customer's recording their own profiles in .NET 6/7 -- most would just be using this setting and profile.

**Comment by hypdeb** [comment] 2023-02-06 20:38
I have a very similar issue in Blazor WebAssembly, but I'm unable to reproduce it in a small enough example. Here is some of the stack trace in case it's relevant:
```
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Could not load list of method overrides due to Method not found: !2 System.Numerics.ISubtractionOperators`3.op_Subtraction(!0,!1)
System.TypeLoadException: Could not load list of method overrides due to Method not found: !2 System.Numerics.ISubtractionOperators`3.op_Subtraction(!0,!1)
   at System.RuntimeType.GetPropertiesByName(String , BindingFlags , MemberListType , RuntimeType )
   at System.RuntimeType.GetPropertyCandidates(String , BindingFlags , Type[] , Boolean )
   at System.RuntimeType.GetProperties(BindingFlags )
   at System.Text.Json.Serialization.Metadata.ReflectionJsonTypeInfo`1[[MyNamespace.Common.Data.TimeSeries, MyNamespace.Common.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].LateAddProperties()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.InitializePropertyCache()
```
For some more information, `TimeSeries` is an abstract record type which implements:
```
IAdditionOperators<TimeSeries, TimeSeries, TimeSeries>,
ISubtractionOperators<TimeSeries, TimeSeries, TimeSeries>,
IMultiplyOperators<TimeSeries, TimeSeries, TimeSeries>,
IDivisionOperators<TimeSeries, TimeSeries, TimeSeries>
```
It seems weird that a JSON serializer would even look at those to be honest.

**Comment by steveisok** [comment] 2023-07-19 21:28
@vargaz @jonathanpeppers is this still an issue?

**Comment by jonathanpeppers** [comment] 2023-07-20 13:59
I believe so, the app was: https://infiniteflight.com/

They just aren't using LLVM for now. It's possible that a "hello world" MonoGame app has the same issue. @dellis1972 do we have one of those around we can try on .NET 8?

**Comment by dellis1972** [comment] 2023-07-21 14:58
I had tried a small 3d MonoGame sample to repo this. Despite some Linker issues to start with its running without issues with LLVM and without.

**Comment by steveisok** [comment] 2023-07-21 16:04
Thanks, will close then.

**Closed by steveisok** 2023-07-21 16:04 UTC
Labels: os-android, area-Codegen-AOT-mono
