### ISSUE TITLE
area-Extensions-DependencyInjection    About creating custom service providers

### ISSUE THREAD

**Issue by Linlccc** [dotnet/runtime#66394] opened 2022-03-09 14:28 UTC
Program.cs
~~~
var builder = WebApplication.CreateBuilder(args);

// Use Custom Service Provider
builder.Host.UseServiceProviderFactory(new CustomServiceProviderFactory());

...

var app = builder.Build();

// The 'service' object here is of type 'CustomServiceProvider'
var service = app.Services;

...

app.Run();
~~~
CustomServiceProviderFactory.cs
~~~
public class CustomServiceProviderFactory: IServiceProviderFactory<IServiceCollection>
{
    public IServiceProvider CreateServiceProvider(IServiceCollection containerBuilder)
    {
        var serviceProvider = containerBuilder.BuildServiceProvider();
        return new CustomServiceProvider(serviceProvider);
    }

    IServiceCollection IServiceProviderFactory<IServiceCollection>.CreateBuilder(IServiceCollection services)
    {
        if (services == null) return new ServiceCollection();
        return services;
    }
}
~~~
CustomServiceProvider.cs
~~~
public class CustomServiceProvider: IServiceProvider, ISupportRequiredService
{
    private readonly IServiceProvider _serviceProvider;
    public CustomServiceProvider(IServiceProvider serviceProvider)
    {
        _serviceProvider = serviceProvider;
    }

    public object GetRequiredService(Type serviceType)
    {
        return GetService(serviceType);
    }

    public object GetService(Type serviceType)
    {
        return _serviceProvider.GetService(serviceType);
    }
}
~~~
CustomControllerActivator.cs
~~~
public class CustomControllerActivator : IControllerActivator
{
    public object Create(ControllerContext context)
    {
        // `serviceProvider` the object is `Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope` type， It's not my custom `CustomServiceProvider` type
        var serviceProvider = context.HttpContext.RequestServices;
        ...
    }

    public void Release(ControllerContext context, object controller)
    {
         ...
    }
}
~~~
WeatherForecastController.cs
~~~
public class WeatherForecastController : ControllerBase
{
    private static readonly string[] Summaries = new[]
    {
        "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
    };

    private readonly ILogger<WeatherForecastController> _logger;
    private readonly IServiceScope serviceProvider;

    public WeatherForecastController(ILogger<WeatherForecastController> logger,IServiceProvider serviceProvider)
    {
        _logger = logger;
        // `serviceProvider` the object is `Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope` type， It's not my custom `CustomServiceProvider` type
        serviceProvider = serviceProvider;
    }

    [HttpGet(Name = "GetWeatherForecast")]
    public IEnumerable<WeatherForecast> Get()
    {
        return Enumerable.Range(1, 5).Select(index => new WeatherForecast
        {
            Date = DateTime.Now.AddDays(index),
            TemperatureC = Random.Shared.Next(-20, 55),
            Summary = Summaries[Random.Shared.Next(Summaries.Length)]
        })
        .ToArray();
    }
}
~~~

As shown in the code posted above, I use a custom service provider, but only `app.Services` is my custom `CustomServiceProvider` type,

In other places, it is Asp.Net Core the default `Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope` type,

What can I do to replace all these with my custom service provider type

**Thank you very much for asking for relief**

**Comment by Linlccc** [comment] 2022-03-09 14:48
@ericstj The labels of this issue don't seem quite right. Please help me to solve the above questions. Thank you very much

**Comment by eerhardt** [comment] 2022-03-09 17:36
The first change to your `CustomServiceProvider` needs to be:

```diff
public class CustomServiceProvider : IServiceProvider, ISupportRequiredService
{
    private readonly IServiceProvider _serviceProvider;
    public CustomServiceProvider(IServiceProvider serviceProvider)
    {
        _serviceProvider = serviceProvider;
    }

    public object GetRequiredService(Type serviceType)
    {
        return GetService(serviceType);
    }

    public object GetService(Type serviceType)
    {
+        if (serviceType == typeof(IServiceProvider)) return this;

        return _serviceProvider.GetService(serviceType);
    }
```

You are trying to inject a service of type `IServiceProvider` into your app. The way DI works, is it takes the `IServiceProvider` and asks it to return the service of type `IServiceProvider`. This calls into your `CustomServiceProvider`, and your `CustomServiceProvider` is returning the inner `_serviceProvider.GetService`, which returns itself for `typeof(IServiceProvider)`.

However, this doesn't fully work with ASP.NET because you are delegating to the underlying `_serviceProvider` to provide services.

What happens is when the app starts up, it tries to get all the `IHostedService` services, which your `CustomServiceProvider` delegates to the underlying `_serviceProvider`. In order to create the [`GenericWebHostService`](https://github.com/dotnet/aspnetcore/blob/4888800d435b86e0d93c25724eefb33a84332537/src/Hosting/Hosting/src/GenericHost/GenericWebHostedService.cs#L19-L25), one of the ctor parameters is a `IHttpContextFactory`. In order to fill that out, the current serviceProvider doesn't call back out to your IServiceProvider. Instead it uses itself to fill out the `IHttpContextFactory`. This means when the [`DefaultHttpContextFactory`](https://github.com/dotnet/aspnetcore/blob/4888800d435b86e0d93c25724eefb33a84332537/src/Hosting/Hosting/src/Http/DefaultHttpContextFactory.cs#L17-L35) is created, it is passed the underlying `_serviceProvider` in its constructor. Thus anything that ASP.NET creates through DI will use the underlying `_serviceProvider`, and not your custom one.

If you really need this to work, I think the options are:

1. Fully implement `IServiceProvider, ISupportRequiredService, IServiceScope, IServiceScopeFactory` interfaces yourself without delegating to an underlying IServiceProvider.
2. You could try injecting your own `IHttpContextFactory` service, and have it return an `HttpContext` with your `CustomServiceProvider`.

cc @davidfowl @halter73 @Tratcher

**Comment by Linlccc** [comment] 2022-03-10 09:01
@eerhardt I will implement the `IServiceScope` , `IServiceScopeFactory` interface, and then use `services.AddScoped<IServiceScopeFactory, CustomServiceScopeFactory>();` to register `IServiceScopeFactory`

However, the `app.Services.CreateScope();` method does not use the `CreateScope` method I defined, and the obtained object is the Asp.Net Core default `ServiceProviderEngineScope` type

Note: `app.Services` is my custom `CustomServiceProvider` type

**Comment by Linlccc** [comment] 2022-03-11 02:01
@eerhardt  I implement `IServiceScope` , `IServiceScopeFactory` interface and then register `IServiceScopeFactory` using `services.AddScoped<IServiceScopeFactory, CustomServiceScopeFactory>();`

Then try to use `app.Services.GetService<IServiceScopeFactory>()` to get the object of `IServiceScopeFactory` type, but the obtained object is the default `ServiceProviderEngineScope` type of Asp.Net Core, not my custom `CustomServiceScopeFactory` type

I don't quite understand here, I hope you can help me clear my doubts

Note:
`app.Services` is the default `ServiceProvider` type of Asp.Net Core

**Comment by davidfowl** [comment] 2022-03-11 02:59
You can't hook into the default IServiceProvider, that's the wrong extensibility point unless you're going to reimplement the entire thing yourself. Decorating the default implementation doesn't work and that's by design.

What are you trying to accomplish?

**Comment by Linlccc** [comment] 2022-03-11 03:13
@davidfowl I want to implement custom DI, but still use the default `IServiceProvider` to get the instance
In fact, all I want is to do my own thing after the default `IServiceProvider` has created the object

**Comment by davidfowl** [comment] 2022-03-11 05:13
> @davidfowl I want to implement custom DI but still create objects with the default IServiceProvider, I don't need to fully customize the container, because it is of no use to me

That's not possible with the build in container. It doesn't have extensibility to do what you're trying to do. You cannot intercept service resolution.

**Comment by maryamariyan** [comment] 2022-03-15 21:29
Closing as the question seems answered.

**Closed by maryamariyan** 2022-03-15 21:29 UTC
Labels: untriaged, area-Extensions-DependencyInjection
