### ISSUE TITLE
ParameterInfo.ToString() is inconsistent with the .NET Framework behavior

### ISSUE THREAD

**Issue by enyim** [dotnet/runtime#110447] opened 2024-12-05 17:41 UTC
### Description

I'm porting large amount of legacy code that relies on string comparison of various objects collected via reflection. (Code should run both on .NET Framework and .NET 8.0+)

Part of this code uses ParameterInfo.ToString() that has different behavior between the frameworks. (Changed in #52804, commit 0377084)

4.8 did not distinguish between null and `""` Name, while 6+ does. This in itself would not be a problem, as we are not comparing data between frameworks. However, .NET 8 sometimes returns null, sometimes `""` for MethodInfo.ReturnParameter.Name, which, with the new behavior breaks tests.

Yes, one could argue that ToString() output is not something to rely on, but 

1) there is already large amount of code out there that do rely on it & I believe backward compatibility is more important
2) ToString() in the Reflection APIs (mostly?) still behave as in .NET Framework

### Reproduction Steps

See the attached repro project. Build and run both versions.

[ParamInfo.zip](https://github.com/user-attachments/files/18027416/ParamInfo.zip)

net48:

```
Name = null => "System.Object "
Name = String.Empty => "System.Object "
Are they equal? True

System.Object EndInvoke(System.IAsyncResult)
  ReturnParameter.ToString() = "System.Object "
  Name = null
System.Object EndInvoke(System.IAsyncResult)
  ReturnParameter.ToString() = "System.Object "
  Name = null
```

net8.0

```
Name = null => "System.Object"
Name = String.Empty => "System.Object "
Are they equal? False

System.Object EndInvoke(System.IAsyncResult)
  ReturnParameter.ToString() = "System.Object "
  Name = ""
System.Object EndInvoke(System.IAsyncResult)
  ReturnParameter.ToString() = "System.Object"
  Name = null
```

### Expected behavior

ParameterInfo should not distinguish between null and empty names, as both values mean that it does not have a name.

### Actual behavior

Difference in behavior.

### Regression?

Changed behavior from .NET Framework 4.8

Does not seem to be documented in https://learn.microsoft.com/en-us/dotnet/core/compatibility/6.0

**Comment by JuergenAuer** [comment] 2024-12-05 19:06
Hi @enyim

> Name = null => "System.Object"
> Name = String.Empty => "System.Object "
> Are they equal? False

first is "System.Object", second is "System.Object " with a space at the end.

Different strings, not the same.

Your NET.4.8 sample - both with a space. Your NET.8: One with, one without a space.

**Comment by enyim** [comment] 2024-12-09 13:44
> Hi [@enyim](https://github.com/enyim)
> 
> > Name = null => "System.Object"
> > Name = String.Empty => "System.Object "
> > Are they equal? False
> 
> first is "System.Object", second is "System.Object " with a space at the end.
> 
> Different strings, not the same.
> 
> Your NET.4.8 sample - both with a space. Your NET.8: One with, one without a space.

yes, this is the issue I am reporting.

**Comment by steveharter** [comment] 2024-12-18 23:30
PTAL @marek-safar based on the change in https://github.com/dotnet/runtime/pull/52804. Was distinguishing between `null` and `""` desired for your scenario?

**Comment by marek-safar** [comment] 2024-12-22 18:53
Yes, one of the goals was to enhance support for trimming outputs diagnostics (null means no metadata, "" means something else). Another goal was to improve stack trace formatting (fixing issues like extra spaces) when metadata trimming is applied.

**Comment by steveharter** [comment] 2024-12-26 16:42
Closing as by design

**Closed by steveharter** 2024-12-26 16:42 UTC
Labels: area-System.Reflection, needs-further-triage
