### ISSUE TITLE
[wasm] `System.Net.WebSockets.Client.Tests.CloseTest.CloseOutputAsync_ClientInitiated_CanReceive_CanClose` failing on browser

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#65796] opened 2022-02-23 19:16 UTC
Hit on https://github.com/dotnet/runtime/pull/65752 (unrelated PR).
[Build](https://dev.azure.com/dnceng/public/_build/results?buildId=1628375&view=logs&j=a07e672c-d717-5036-7657-9f851d8c04dc&t=00a7b5ce-df8e-5072-ea20-a3ed92ab7ac8), and [log](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-65752-merge-0347a9d7fc734426ab/WasmTestOnBrowser-System.Net.WebSockets.Client.Tests/1/console.7b9acac1.log?sv=2019-07-07&se=2022-03-15T18%3A18%3A26Z&sr=c&sp=rl&sig=I%2BmuOFo00o%2FdQUpTiKd0tPdoLF0gz8Y%2BhQ%2Fc4dmDLd4%3D):

```
[18:43:39] info: Discovering: System.Net.WebSockets.Client.Tests.dll (method display = ClassAndMethod, method display options = None)
[18:43:39] info: Discovered:  System.Net.WebSockets.Client.Tests.dll (found 60 of 87 test cases)
[18:43:39] info: Using random seed for test cases: 808720396
[18:43:39] info: Using random seed for collections: 808720396
[18:43:39] info: Starting:    System.Net.WebSockets.Client.Tests.dll
[18:43:39] fail: [out of order message from the browser]: http://127.0.0.1:49168/dotnet.js 2 WebSocket connection to 'ws://127.0.0.1:49168/WebSocket/EchoWebSocket.ashx?subprotocol=CustomProtocol' failed: Error during WebSocket handshake: Response must not include 'Sec-WebSocket-Protocol' header if not present in request: CustomProtocol
[18:43:39] fail: [out of order message from the browser]: http://127.0.0.1:49168/dotnet.js 2 WebSocket connection to 'wss://127.0.0.1:49169/WebSocket/EchoWebSocket.ashx?subprotocol=CustomProtocol' failed: Error during WebSocket handshake: Response must not include 'Sec-WebSocket-Protocol' header if not present in request: CustomProtocol
[18:43:40] fail: [out of order message from the browser]: http://127.0.0.1:49168/dotnet.js 2 WebSocket connection to 'ws://127.0.0.1:49186/' failed: Connection closed before receiving a handshake response
[18:43:42] fail: [out of order message from the browser]: http://127.0.0.1:49168/dotnet.js 2 WebSocket connection to 'ws://bf8a6a8eb73143a0ab2f9fea8dba8dca/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
[18:43:50] warn: WARNING: Web browsers do not support closing the output side of a WebSocket. CloseOutputAsync has closed the socket and discarded any incoming messages.
[18:45:15] fail: [FAIL] System.Net.WebSockets.Client.Tests.CloseTest.CloseOutputAsync_ClientInitiated_CanReceive_CanClose(server: wss://127.0.0.1:49169/WebSocket/EchoWebSocket.ashx)
[18:45:15] info: Assert.Equal() Failure
[18:45:15] info: Expected: 17
[18:45:15] info: Actual:   0
[18:45:15] info:    at System.Net.WebSockets.Client.Tests.CloseTest.CloseOutputAsync_ClientInitiated_CanReceive_CanClose(Uri server)
[18:45:16] info: --- End of stack trace from previous location ---
[18:46:20] info: http://127.0.0.1:49168/dotnet.js 2 WebSocket connection to 'ws://127.0.0.1:49168/WebSocket/EchoWebSocket.ashx?delay10sec' failed: WebSocket is closed before the connection is established.
[18:46:20] info: http://127.0.0.1:49168/dotnet.js 2 WebSocket connection to 'wss://127.0.0.1:49169/WebSocket/EchoWebSocket.ashx?delay10sec' failed: WebSocket is closed before the connection is established.
[18:46:20] info: Finished:    System.Net.WebSockets.Client.Tests.dll
```

cc @pavelsavara

**Comment by ilonatommy** [comment] 2022-06-23 09:29
I can't reproduce it, can you @pavelsavara? Is it probable that it got fixed? Test itself does not have any recent changes.

**Comment by pavelsavara** [comment] 2022-06-23 11:01
Let's close it and re-open if it appears again.

**Comment by antonfirsov** [comment] 2023-09-13 11:52
Hit in #91910. There were several hits in August according to Kusto. Low frequency but reopening for more triage.

<details>

```
cluster('engsrvprod.kusto.windows.net').database('engineeringdata').AzureDevOpsTests
   | where TestName startswith "System.Net"
       and Outcome == 'Failed' or Outcome == 'PassedOnRerun'
   | extend i = indexof_regex(TestName, @"[^.]+$")
   | extend Method = substring(TestName, i)
   | extend Type = substring(TestName, 0, i - 1)
   | project-away i, TestName
   | where Method has 'CloseOutputAsync_ClientInitiated_CanReceive_CanClose'
   | distinct JobId, WorkItemId, Message, StackTrace, Method, Type, Arguments, Outcome
   | join kind=inner (cluster('engsrvprod.kusto.windows.net').database('engineeringdata').Jobs
       | where Finished > now(-40d)
       | extend TargetBranch = extractjson("$.['System.PullRequest.TargetBranch']", Properties)
       | where (Branch == 'refs/heads/main') or (Source startswith "pr/" and TargetBranch == 'main')
       | where Type startswith "test/functional/cli/" and not(Properties contains "runtime-staging")
       | summarize arg_max(Finished, Properties, Type, Branch, Source, Started, QueueName, Attempt, Build, TargetBranch) by JobId
   | project-rename JobType = Type) on JobId
   | extend PropertiesJson = parse_json(Properties)
   | extend OS = replace_regex(tostring(PropertiesJson.operatingSystem), @'\((.*)\).*|([^\(].*)', @'\1\2')
   | extend Runtime = iif(PropertiesJson.runtimeFlavor == "mono", "Mono", iif(PropertiesJson.DefinitionName contains "coreclr", "CoreCLR", ""))
   | extend Architecture = PropertiesJson.architecture
   | extend DefinitionName = PropertiesJson.DefinitionName
   | project-away JobId
   | extend JobId = extractjson("$.['System.JobId']", Properties)
   | join kind=inner (cluster('engsrvprod.kusto.windows.net').database('engineeringdata').WorkItems
       | project-keep ConsoleUri, WorkItemId) on WorkItemId
   | project-away PropertiesJson
   | project-reorder Started, Type, Method, Arguments, StackTrace, ConsoleUri, OS, Architecture, DefinitionName, Branch, TargetBranch, Attempt, Build, *
;
```

</details>

**Closed** 2024-01-16 13:54 UTC
Labels: arch-wasm, area-System.Net, in-pr
