### ISSUE TITLE
DeflateStream using FileStream outputs 2 extra bytes compared to using a MemoryStream

### ISSUE THREAD

**Issue by Washi1337** [dotnet/runtime#53085] opened 2021-05-21 15:34 UTC
### Description

There seems to be an inconsistency when trying to compress some data using `DeflateStream`. If we use a `FileStream` as an output stream, two extra bytes (`03 00`) are written, whereas if we try to use `MemoryStream` instead, those two bytes disappear. Quick Google search seems to indicate `03` indicates the ETX (End-Of-Text) character, but I am not sure if this is related (especially since deflated data is binary data and not textual data).

Both outputs do seem to decompress properly though.

<details>
<summary>
Example code
</summary>

```csharp
using System;
using System.IO;
using System.IO.Compression;
using System.Linq;

namespace DeflateStreamTest
{
    internal static class Program
    {
        private static void Main()
        {
            // Prepare some sample data to compress.
            byte[] originalData = new byte[100000];
            for (int i = 0; i < originalData.Length; i++)
                originalData[i] = (byte) (i & 0xFF);

            // Compress
            byte[] compressedData1 = CompressDeflate(originalData);
            byte[] compressedData2 = CompressDeflateViaFile(originalData);

            // Output lengths
            Console.WriteLine($"Length CompressDeflate: {compressedData1.Length}");
            Console.WriteLine($"Length CompressDeflateViaFile: {compressedData2.Length}");

            // Check if both outputs still decompress to the same output.
            bool valid1 = DecompressDeflate(compressedData1).SequenceEqual(originalData);
            bool valid2 = DecompressDeflate(compressedData2).SequenceEqual(originalData);
            Console.WriteLine($"CompressDeflate Validity Check: {valid1}");
            Console.WriteLine($"CompressDeflateViaFile Validity Check: {valid2}");
        }

        private static byte[] CompressDeflate(byte[] data)
        {
            using var stream = new MemoryStream();
            using var deflate = new DeflateStream(stream, CompressionMode.Compress);
            {
                deflate.Write(data, 0, data.Length);
                deflate.Flush();
            }

            return stream.ToArray();
        }

        private static byte[] CompressDeflateViaFile(byte[] data)
        {
            using var stream = File.Create("temp.bin");
            {
                using var deflate = new DeflateStream(stream, CompressionMode.Compress);
                deflate.Write(data, 0, data.Length);
                deflate.Flush();
            }

            return File.ReadAllBytes("temp.bin");
        }

        private static byte[] DecompressDeflate(byte[] compressedData)
        {
            using var decompressed = new MemoryStream();
            using (var compressed = new MemoryStream(compressedData))
            {
                using var deflate = new DeflateStream(compressed, CompressionMode.Decompress);
                deflate.CopyTo(decompressed);
            }

            return decompressed.ToArray();
        }
    }
}
```
</details>

Outputs:
```
Length CompressDeflate: 717
Length CompressDeflateViaFile: 719
CompressDeflate Validity Check: True
CompressDeflateViaFile Validity Check: True
```

Writing a single byte to `FileStream` using the `Write` method directly does not seem to append the two extra bytes, so it seems like this is an inconsistency introduced by using the `DeflateStream`.

### Configuration
**.NET Version:** .NET 5.0
**OS:** Tested on both Windows 10 and Linux Manjaro (Kernel 5.10.36)
**Architecture:** x86 64-bit

**Comment by danmoseley** [comment] 2021-05-22 02:35
Thanks for the report. Any interest in debugging a little? Symbols and sources are public and debugger should find them.

**Comment by Washi1337** [comment] 2021-05-22 12:50
I realized this is a mistake on my end, albeit a subtle one, and I feel like this could have been prevented if the IDE provides a warning about this, but I am not sure if this is the place to discuss that.

After stepping through the code of `DeflateStream`, I found that the last two bytes are a result of calling the `DeflateStream.Dispose(bool)` method. This made me question why it would not work for `MemoryStream`, since `Dispose` is called because of the `using` statement. At this point I realized my mistake. I forgot to add the parentheses around the creation of the `DeflateStream` in the using statement. This results in the compiler interpreting the using statement as a using declaration, and the braces as a separate (meaningless) scope block. As a result, the `Dispose` method is called _after_ `stream.ToArray()`, instead of before, causing the difference in outputs.

Meaning this:
```csharp
private static byte[] CompressDeflate(byte[] data)
{
    using var stream = new MemoryStream();
    using var deflate = new DeflateStream(stream, CompressionMode.Compress);
    {
        deflate.Write(data, 0, data.Length);
        deflate.Flush();
    }

    return stream.ToArray();
}
```

Should have been this:
```csharp
private static byte[] CompressDeflate(byte[] data)
{
    using var stream = new MemoryStream();
    using (var deflate = new DeflateStream(stream, CompressionMode.Compress))
    {
        deflate.Write(data, 0, data.Length);
        deflate.Flush();
    }

    return stream.ToArray();
}
```

Now both functions output the same value.

Maybe this kind of mistake could have been prevented with a warning in the IDE?

**Comment by danmoseley** [comment] 2021-05-22 14:20
@mavasani  could you move this to https://github.com/dotnet/roslyn-analyzers ? Or perhaps it's a duplicate?

**Comment by stephentoub** [comment] 2021-05-22 14:57
Proposals for analyzers relating to .NET library types are in this repo.  But I'm not clear what specifically is the suggestion... what specific pattern are you suggesting should be flagged?

**Comment by Washi1337** [comment] 2021-05-22 15:01
The pattern where a using declaration is followed by a scope block:

For example:
```csharp
using var x = M();
{
    // ...
}
```

is semantically different from:
```csharp
using (var x = M())
{
    // ...
}
```

Yet they look very similar and (as can be seen in this issue) can result in unintended behaviour. Maybe it is just me making this mistake though :)

**Comment by stephentoub** [comment] 2021-05-22 15:03
> Also as a side note: Is it by design that we need to call DeflateStream.Flush manually before disposing the stream? Without it, we can observe that upon disposing the DeflateStream not all data is written to the output stream.

Can you share repro that demonstrates that?

**Comment by stephentoub** [comment] 2021-05-22 15:04
> The pattern where a using declaration is followed by a scope block:

Ah, so generally about a particular syntax rather than about these specific types.  Thanks.

**Comment by Washi1337** [comment] 2021-05-22 15:08
> Can you share repro that demonstrates that?

For sure. Unless I am missing some parentheses again, here you go:

<details>
<summary>Example code</summary>

```csharp
using System;
using System.IO;
using System.IO.Compression;

namespace DeflateStreamTest
{
    internal static class Program
    {
        private static void Main()
        {
            // Prepare some sample data to compress.
            byte[] originalData = new byte[1];
            for (int i = 0; i < originalData.Length; i++)
                originalData[i] = (byte) (i & 0xFF);

            // Compress
            byte[] compressedData1 = CompressDeflateWithoutFlush(originalData);
            byte[] compressedData2 = CompressDeflateWithFlush(originalData);

            // Output lengths
            Console.WriteLine($"Length CompressDeflateWithoutFlush: {compressedData1.Length}");
            Console.WriteLine($"Length CompressDeflateWithFlush: {compressedData2.Length}");
        }

        private static byte[] CompressDeflateWithoutFlush(byte[] data)
        {
            using var stream = new MemoryStream();
            using (var deflate = new DeflateStream(stream, CompressionMode.Compress))
            {
                deflate.Write(data, 0, data.Length);
            }

            return stream.ToArray();
        }

        private static byte[] CompressDeflateWithFlush(byte[] data)
        {
            using var stream = new MemoryStream();
            using (var deflate = new DeflateStream(stream, CompressionMode.Compress))
            {
                deflate.Write(data, 0, data.Length);
                deflate.Flush();
            }

            return stream.ToArray();
        }
    }
}
```
</details>

Outputs:
```
Length CompressDeflateWithoutFlush: 3
Length CompressDeflateWithFlush: 9
```

**Comment by stephentoub** [comment] 2021-05-22 15:17
Thanks.  That's shows the flush impacts the compressed size,  but it doesn't show that data is lost...?

**Comment by Washi1337** [comment] 2021-05-22 15:28
True, and the original data does not seem to be actually lost. Decompression is possible in both scenarios, as can be seen from the example below. Still you can see that without the flush call, the output memory stream does not include the "tail" sequence (`00 00 FF FF 03 00`). Perhaps some footer of the data that is ignored upon decompressing? Truth be told I am not too familiar with the deflate algorithm.

<details>
<summary>Example code</summary>

```csharp
using System;
using System.IO;
using System.IO.Compression;

namespace DeflateStreamTest
{
    internal static class Program
    {
        private static void Main()
        {
            // Prepare some sample data to compress.
            byte[] originalData = new byte[10];
            for (int i = 0; i < originalData.Length; i++)
                originalData[i] = (byte) (i & 0xFF);

            // Compress
            byte[] compressedData1 = CompressDeflateWithoutFlush(originalData);
            byte[] compressedData2 = CompressDeflateWithFlush(originalData);

            // Output lengths
            Console.WriteLine("Compression test:");
            Console.WriteLine($"- CompressDeflateWithoutFlush: {Convert.ToHexString(compressedData1)}");
            Console.WriteLine($"- CompressDeflateWithFlush:    {Convert.ToHexString(compressedData2)}");

            // Decompress
            byte[] decompressed1 = Decompress(compressedData1);
            byte[] decompressed2 = Decompress(compressedData2);

            Console.WriteLine("Decompression test:");
            Console.WriteLine($"- Original:                    {Convert.ToHexString(originalData)}");
            Console.WriteLine($"- CompressDeflateWithoutFlush: {Convert.ToHexString(decompressed1)}");
            Console.WriteLine($"- CompressDeflateWithFlush:    {Convert.ToHexString(decompressed2)}");
        }

        private static byte[] CompressDeflateWithoutFlush(byte[] data)
        {
            using var stream = new MemoryStream();
            using (var deflate = new DeflateStream(stream, CompressionMode.Compress))
            {
                deflate.Write(data, 0, data.Length);
            }

            return stream.ToArray();
        }

        private static byte[] CompressDeflateWithFlush(byte[] data)
        {
            using var stream = new MemoryStream();
            using (var deflate = new DeflateStream(stream, CompressionMode.Compress))
            {
                deflate.Write(data, 0, data.Length);
                deflate.Flush();
            }

            return stream.ToArray();
        }

        private static byte[] Decompress(byte[] data)
        {
            using var decompressedStream = new MemoryStream();
            using var compressedStream = new MemoryStream(data);
            using (var deflate = new DeflateStream(compressedStream, CompressionMode.Decompress))
            {
                deflate.CopyTo(decompressedStream);
            }

            return decompressedStream.ToArray();
        }
    }
}
```
</details>

Outputs:
```
Compression test:
- CompressDeflateWithoutFlush: 6360646266616563E7E00400
- CompressDeflateWithFlush:    6260646266616563E7E004000000FFFF0300
Decompression test:
- Original:                    00010203040506070809
- CompressDeflateWithoutFlush: 00010203040506070809
- CompressDeflateWithFlush:    00010203040506070809
```

**Comment by stephentoub** [comment] 2021-05-22 15:39
> Still you can see that without the flush call, the output memory stream does not include the "tail" sequence

You're seeing a type 0 block generated as part of a zlib "sync flush", which is what an explicit Flush maps to.  See the deflate/zlib spec.  That's not needed as part of a finishing flush, implicit to Dispose.

**Comment by mavasani** [comment] 2021-05-22 15:54
Seems to be a duplicate of https://github.com/dotnet/roslyn/issues/51668

**Comment by stephentoub** [comment] 2021-05-22 15:59
Thanks.  Closing as there's no bug here and there's already an issue tracking a warning.

**Closed by stephentoub** 2021-05-22 15:59 UTC
Labels: area-System.IO.Compression, untriaged

**Comment by Washi1337** [comment] 2021-05-22 16:08
> Seems to be a duplicate of [dotnet/roslyn#51668](https://github.com/dotnet/roslyn/issues/51668)

Perfect, I will be looking forward to that change.

Also, thank you very much for answering my questions @stephentoub  :)
