### ISSUE TITLE
Guarantee that ConcurrentDictionary enumerations don't emit duplicate keys

### ISSUE THREAD

**Issue by theodorzoulias** [dotnet/runtime#46374] opened 2020-12-23 22:26 UTC
## Background and Motivation

The [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2.getenumerator?view=net-5.0#remarks) of the `ConcurrentDictionary<TKey,TValue>.GetEnumerator` method states that: _the contents exposed through the enumerator may contain modifications made to the dictionary after `GetEnumerator` was called._ This statement makes no guarantee that the keys emitted by the enumerator will be unique, forcing the users of the API to code defensively around this possibility. On the other hand the current implementation of the class (.NET 5) [seems to enforce](https://stackoverflow.com/questions/65417001/is-it-safe-to-copy-a-concurrentdictionary-to-a-normal-dictionary-by-enumerating/65428882#65428882) the uniqueness of the emitted keys, i.e. it's impossible to receive twice the same key during a single iteration of the dictionary.

## Proposed API

My proposal is to elevate this behavior from an implementation detail to a publicly documented guarantee. This will free the users of the API from taking defensive measures, when the correctness of their code depends on the uniqueness of the enumerated keys. This proposal does not require implementation modifications. Only the `remarks` of the `GetEnumerator` method need to be updated. Here is a rough text proposal:

```diff
/// <remarks>
/// The enumerator returned from the dictionary is safe to use concurrently with
/// reads and writes to the dictionary, however it does not represent a moment-in-time snapshot
/// of the dictionary. The contents exposed through the enumerator may contain modifications
/// made to the dictionary after <see cref="GetEnumerator"/> was called.
+ /// It is guaranteed that a single iteration over the dictionary will emit entries having
+ /// distinct keys.
/// </remarks>
public IEnumerator<KeyValuePair<TKey, TValue>> GetEnumerator() => new Enumerator(this);
```
## Usage Examples

Creating copies using the `Dictionary` constructor will be safe:

``` C#
var copy = new Dictionary<string, decimal>(concurrentDictionary);
```

Also converting an existing implementation from using a `Dictionary`+`lock` to using a `ConcurrentDictionary` will be more straightforward (one less thing to worry about).

**Comment by eiriktsarpalis** [comment] 2021-01-04 17:42
The analysis in the linked article seems valid, however it seems likely that the uniqueness invariant is accidental rather than intentional. @stephentoub might be able to provide context here. 

If we do decide to update the docs it becomes part of the informal spec so any future regressions would be considered breaking changes. How could we effectively test for this kind of behaviour?

**Comment by stephentoub** [comment] 2021-01-04 17:58
>however it seems likely that the uniqueness invariant is accidental rather than intentional. @stephentoub might be able to provide context here.

Yes, if that actually holds, it's a side-effect of the chosen implementation rather than a guarantee the dev was trying to make.

**Comment by peterduniho** [comment] 2021-03-10 03:58
> The analysis in the linked article seems valid, however it seems likely that the uniqueness invariant is accidental rather than intentional. @stephentoub might be able to provide context here.
> 
> If we do decide to update the docs it becomes part of the informal spec so any future regressions would be considered breaking changes. How could we effectively test for this kind of behaviour?

Unfortunately, because the current implementation does (apparently) guarantee that duplicate keys won't be returned while enumerating, it wouldn't be possible to reliably author a test using the current implementation. One could attempt to author the test, but there wouldn't be any way to verify its validity.

In _theory_, such a test could be written simply by including synchronization between two threads: one that is enumerating the dictionary, and another that removes and then re-adds a element with a given key, after that key has already been enumerated. I.e. the enumerating thread signals to the modifying thread that it's seen a particular key, at which point it waits until the modifying thread signals that it's removed and re-added that key.

Unfortunately, a _passing_ test does not guarantee anything. It only tests for a specific likely implementation detail in which a duplicate key would be returned. There are alternative implementations which would in turn create alternative scenarios where a duplicate key would be returned. For example, perhaps new elements are inserted into the collection, but a particular reallocation strategy would cause some _other_ element already enumerated but not even modified in the collection to be returned a second time.

All that said, it is worth seriously considering this suggestion. While there is the `ToArray()` method to provide a snapshot of the collection, this is infeasible to use when the collection is very large. It's understandable that enumerating the collection while other threads may be modifying it could result in some inconsistencies. For sure, one might not expect new elements added to be included, or for removed elements to still be included, just as the snapshot would result in. But the API would work _much_ better if there were at least the guarantee that the same key won't be returned more than once, and that any key present when enumeration begins, _will_ be returned.

As it stands now, it's unclear to me when one might use the enumerable implementation of this class. Without any particular guarantees other than it being "safe" (presumably this just means no data corruption and no exceptions), using the implementation without synchronization with other threads is just wishful thinking. In theory, a collection with many elements in it could return an empty sequence and still comply with the spec as given now.

**Comment by GSPP** [comment] 2021-03-10 08:48
What is the use-case for enumerating a `ConcurrentDictionary` while it is being modified? What is the use-case for not receiving duplicate keys? What is the use-case for receiving every key that is present when the enumeration started?

I think these questions should be answered before deciding on what guarantees an enumeration should provide.

I don't mean this as a rhetorical question or to be cheeky. I'm not sure what guarantees a consumer of this API would need. I currently can only think of "debug" use-cases such as dumping a live data structure while some computation is in progress. I don't know what algorithm could make use of enumerating a "hot" CD while it's contents are changing.

**Comment by stephentoub** [comment] 2021-03-10 11:53
> it's unclear to me when one might use the enumerable implementation of this class. Without any particular guarantees other than it being "safe" (presumably this just means no data corruption and no exceptions), using the implementation without synchronization with other threads is just wishful thinking

It's not "wishful thinking".  For example, SocketsHttpHandler stores its connection pools in a ConcurrentDictionary, and it enumerates then even as new entries may be added in order to find and remove stale pools, to trigger keep-alive heartbeats, etc.

**Comment by peterduniho** [comment] 2021-03-10 17:38
> What is the use-case for enumerating a `ConcurrentDictionary` while it is being modified? What is the use-case for not receiving duplicate keys? What is the use-case for receiving every key that is present when the enumeration started?
> 
> I think these questions should be answered before deciding on what guarantees an enumeration should provide.
> 
> I don't mean this as a rhetorical question or to be cheeky. I'm not sure what guarantees a consumer of this API would need. I currently can only think of "debug" use-cases such as dumping a live data structure while some computation is in progress. I don't know what algorithm could make use of enumerating a "hot" CD while it's contents are changing.

That's an excellent point. For what it's worth, I came back to this issue because I am teaching a programming course and decided to put together a multi-user chat server example. There are of course points during execution when the server wants to enumerate all of the clients, whether to report to a new client the current state of the client list or to send all clients a message. Race conditions with respect to old clients begin included in the results, even though they are removed during the progress of the enumeration, or new clients _not_ being included in the results, even though they are added during the progress of the enumeration, seem perfectly reasonable to me.

But, having an old client reported twice because the implementation detail reordered the dictionary contents as a result of a modification, or worse, not reported at all, is very undesirable. It would be much preferable if the implementation were documented as guaranteeing that not to happen.

In the teaching example, this is academic, because we'll never see so many clients in the dictionary that it's prohibitively expensive to take a snapshot of the dictionary with the `ToArray()` method. But I can well imagine real-world scenarios that are essentially the same, where it would be much better to be able to project the dictionary directly into the serialized type used for the inter-process protocol, rather than having to create a complete in-memory duplicate of the dictionary before doing so.

There are obviously a number of alternative ways to address these potential issues. If it's simply impractical for this sort of contract to be provided, that's a completely reasonable answer. I take as given that the professionals involved in the implementation of the API and the underlying data structures know best what's appropriate and what's not.

It's just that at the moment, the implementation _does_ seem to provide stronger guarantees than are documented, and so these guarantees seem feasible to provide. If indeed that's the case, it would be nice if the documentation was updated to reflect that.

**Comment by peterduniho** [comment] 2021-03-10 17:40
> > it's unclear to me when one might use the enumerable implementation of this class. Without any particular guarantees other than it being "safe" (presumably this just means no data corruption and no exceptions), using the implementation without synchronization with other threads is just wishful thinking
> 
> It's not "wishful thinking". For example, SocketsHttpHandler stores its connection pools in a ConcurrentDictionary, and it enumerates them even as new entries may be added in order to find and remove stale pools, to trigger keep-alive heartbeats, etc.

Fair enough. Indeed, now that you mention it, this sort of caching scenario seems like a very common use case for ConcurrentDictionary, and as you point out, is not harmed very much, if at all, by the lack of stronger guarantees (though I'll point out that since the current implementation seems to provide these stronger guarantees, it's hard to know for sure what harm would come by not having them :) ).

**Comment by eiriktsarpalis** [comment] 2021-08-04 11:31
Given that we haven't found a strong use case for this invariant holding, I don't think we should be constraining the implementation by adding it to the informal specification. I'm going to close this for now, but we can reconsider in light of new evidence.

**Closed by eiriktsarpalis** 2021-08-04 11:31 UTC
Labels: area-System.Collections, documentation
