### ISSUE TITLE
`Directory.EnumerateXXX()` returns wrong paths if the directory is a path like `U:`

### ISSUE THREAD

**Issue by KodamaSakuno** [dotnet/runtime#82085] opened 2023-02-14 11:07 UTC
### Description

`Directory.EnumerateXXX()` uses `FileSystemEnumerator<>` to enumerate file system elements from .Net Core 2.1. `FileSystemEnumerator<>` call `Path.GetFullPath` to get the full path of the `directory` parameter and create a directory handle with the previous result. According to [the remarks of `GetFullPathName`](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfullpathnamew#remarks), it returns the current working direcory on the `U:` drive if the input is `U:`. Based on this behavior, `Directory.EnumerateXXX()` returns the enumeration of cwd elements with `U:`-like input if cwd is a directory of `U:` drive on Windows.

However, `FileSystemEnumerator<>` passes such an input to `FileSystemEntry` without any transformation, and `FileSystemEntry` will join `U:` and filename directly. As a result, `Directory.EnumerateXXX()` returns wrong paths.

### Reproduction Steps

1. Create a directory on C drive named `bug`
2. Create three files named `a`, `b` and `c` in that directory
3. Make sure the current working directory is `C:\bug` and run the following code:
```
foreach (var item in Directory.EnumerateFiles("C:"))
{
    Console.WriteLine(item);
}
```

### Expected behavior

```
C:\bug\a
C:\bug\b
C:\bug\c
```

### Actual behavior

```
C:\a
C:\b
C:\c
```

### Configuration

Tested from .Net Core 3.1 to .Net 7.0 on Windows 10

**Comment by kasperk81** [comment] 2023-02-14 15:31
`EnumerateFiles("C:")` and `EnumerateFiles("C:\\")`to produce the same result is a more rational expected behavior

**Comment by Jozkee** [comment] 2023-02-14 16:54
@kasperk81, that can't be made as `C:` and `C:\` have different meanings.

**Comment by Jozkee** [comment] 2023-02-14 17:00
This is a duplicate of https://github.com/dotnet/runtime/issues/68503.

**Closed by Jozkee** 2023-02-14 17:00 UTC
Labels: area-System.IO, untriaged
