### ISSUE TITLE
Regression in System.Collections.TryAddDefaultSize for Windows x86

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/runtime#31468] opened 2019-11-11 22:31 UTC
System.Collections.TryAddDefaultSize<String>.Dictionary(Count: 512) has regressed by 15% from 3.0->3.1

![image](https://user-images.githubusercontent.com/9439069/68626314-fbd38800-048f-11ea-9701-c9c71f1a1fa2.png)

**Comment by danmosemsft** [comment] 2020-07-16 20:09
@DrewScoggins is this still valid - did it revert to before? (I do'nt know how to see the data 😞)

As a general rule if we already shipped this regression, by default I would not consider it must-fix for 5.0 and I'd put the Future milestone (unless there's demonstrated customer impact, etc)

**Comment by DrewScoggins** [comment] 2020-07-16 21:11
You can go ahead and do that. I have not been managing the milestones on these are anything like that.

**Comment by danmosemsft** [comment] 2020-07-16 21:17
My bad - that was addressed to area owners 😄  

@layomia since this is old, not large, only one sub-scenario, we don't have updated data, and it's x86 Windows only, I suggest closing.

**Comment by danmosemsft** [comment] 2020-08-02 18:39
closing as above.

**Closed by danmosemsft** 2020-08-02 18:39 UTC
Labels: area-System.Collections, tenet-performance-benchmarks
