### ISSUE TITLE
JsonIgnoreCondition.WhenWritingNull doesn't play well with required nullable properties

### ISSUE THREAD

**Issue by asleire** [dotnet/runtime#76527] opened 2022-10-03 09:22 UTC
.NET SDK: 7.0.100-rc.1.22431.12

I'm not sure if this is intentional or not, but I'm experiencing an issue when trying to use required nullable properties in my API DTOs. 

1. I want to mark my properties as required in order to force my code to initialize all the properties, even the properties that are nullable. 
2. I want to serialize my objects with the serializer option `DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull`. 

Combining these points lead to an exception upon deserializing a serialized object whose nullable required property was set to null.

I would expect deserialization to ignore required nullable properties when `DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull`

## Minimal reproduction
Code:
```
using System.Text.Json;
using System.Text.Json.Serialization;

var jsonSerializerOptions = new JsonSerializerOptions()
{
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
};

var serializedFoo = JsonSerializer.Serialize(new Foo() { Bar = null }, jsonSerializerOptions);

// This line throws an exception: JSON deserialization for type 'Foo' was missing required properties, including the following: Bar
JsonSerializer.Deserialize<Foo>(serializedFoo, jsonSerializerOptions);

public class Foo
{
    public required string? Bar { get; set; }
}

```

Exception:
```
Unhandled exception. System.Text.Json.JsonException: JSON deserialization for type 'Foo' was missing required properties, including the following: Bar
   at System.Text.Json.ThrowHelper.ThrowJsonException_JsonRequiredPropertyMissing(JsonTypeInfo parent, BitArray requiredPropertiesSet)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
```

**Comment by eiriktsarpalis** [comment] 2022-10-03 10:28
This is by design -- not setting a `required` property for a newly initialized object violates its contract, so the deserializer will rightly fail if it cannot bind to any JSON property. See the docs on [required member support](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/migrate-from-newtonsoft?pivots=dotnet-7-0#required-properties) for more details.

The reason you're seeing this error message is that the two configurations are mutually contradictory: it's not possible to roundtrip a value when it's both ignored on serialization and required on deserialization. Suggested workaround would be to override the ignore condition for the specific properties that are marked `required`:

```C#
public class Foo
{
    [JsonIgnore(JsonIgnoreCondition.Never)]
    public required string? Bar { get; set; }
}
```

**Comment by asleire** [comment] 2022-10-03 10:51
> not setting a required property for a newly initialized object violates its contract, so the deserializer will rightly fail if it cannot bind to any JSON property

Maybe this issue should be changed into a feature request then. The deserializer could be changed so that if a required property is missing, but `DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull`, the deserializer initializes the property to `null`, thus satisfying the contract

I don't think your workaround is valid as I want to ignore the property when serializing if is it null

**Comment by eiriktsarpalis** [comment] 2022-10-03 11:37
> The deserializer could be changed so that if a required property is missing, but DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull, the deserializer initializes the property to null

`JsonIgnoreCondition.WhenWritingNull` strictly influences the _serialization contract_ and has no bearing on how properties are deserialized. Changing the deserializer contradicts both the name and documented semantics of `WhenWritingNull` and is a breaking change.

> I don't think your workaround is valid as I want to ignore the property when serializing if is it null

You should be able to use [contract customization](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/custom-contracts) to switch off [required properties](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.metadata.jsonpropertyinfo.isrequired?view=net-7.0#system-text-json-serialization-metadata-jsonpropertyinfo-isrequired) in the context of JSON deserialization. But I wouldn't recommend this approach: by turning off deserialization validation for `required` properties you end up with instances containing unset properties that the C# compiler assumes have been set. Effectively this violates the contract of your type design.

**Comment by asleire** [comment] 2022-10-03 11:54
> Changing the deserializer contradicts both the name and documented semantics of WhenWritingNull and is a breaking change.

A new value for `JsonIgnoreCondition` or a new `JsonSerializerOptions` property then? 🙂 

I don't think my use case is unreasonable. I want to the `required` modifier to apply to my C# code, not the corresponding JSON contract. At least for nullable properties. 

What about an option in `JsonSerializerOptions` to control the usage of the `required` modifier? 

Option 1: Make `required` properties required in the JSON contract
Option 2: Make `required` properties required in the JSON contract for non-nullable properties
Option 3: Ignore the `required` modifier, making the properties optional (effectively pre-.NET 7 behavior)

**Comment by eiriktsarpalis** [comment] 2022-10-03 12:09
> What about an option in JsonSerializerOptions to control the usage of the required modifier?

As mentioned, this is already possible using the contract model.

**Comment by eiriktsarpalis** [comment] 2022-10-18 13:39
Closing as answered.

**Closed by eiriktsarpalis** 2022-10-18 13:39 UTC
Labels: question, area-System.Text.Json
