### ISSUE TITLE
[API Proposal]: Implement IReadOnlyList<char> by String class

### ISSUE THREAD

**Issue by sakno** [dotnet/runtime#57484] opened 2021-08-16 10:24 UTC
### Background and motivation

`List<T>` and `ImmutableList<T>` already implement `IReadOnlyList<T>` interface. This allows to expose the collection through public API without informing the consumer about implementation details. However, it's not possible to cast string to this interface.

### API Proposal

```csharp
namespace System
{
     public sealed class String : IReadOnlyList<char>
     {
        int IReadOnlyList<char>.Count => Length; // this is the only implementation required by the interface
     }
}
```

### API Usage

```csharp
public T[] Copy<T>(IReadOnlyList<T> list)
{
  var result = new T[list.Count];
  list.CopyTo(result, 0);
  return result;
}
```

In my situation, the copy returns the rented block of memory of special type that allows to return the memory back to the pool.

### Risks

Some third-party code may have the following overloaded extension methods:
```csharp
static void DoSomething<T>(this IEnumerable<T> enumerable);
static void DoSomething<T>(this IReadOnlyCollection<T> collection);
```

In this case, the compiled code will use the second overload instead of first, which is not obvious for the caller.

**Comment by eiriktsarpalis** [comment] 2021-08-16 10:59
Adding new interface implementations to types comes with a runtime cost, which is particularly true if it concerns overwhelmingly common types. It's unlikely we would do this unless there existed a truly compelling use case.

cc @jkotas

**Comment by sakno** [comment] 2021-08-16 11:13
What is the truly compelling use case? How to assume that some situation is that use case?

**Comment by sakno** [comment] 2021-08-16 11:23
On Github, there are 4K issues where `IReadOnlyList` mentioned, 689K lines of code where this interface is used and 55 discussions. Of course, not all of them directly related to the issue, but the interface is commonly used in third-party libraries especially in generic variant so providing such implementation will allow users to pass String objects.

**Comment by jkotas** [comment] 2021-08-16 12:31
This is duplicate of https://github.com/dotnet/runtime/issues/19609 . The idea was discussed at length and rejected.

**Closed** 2021-08-16 12:33 UTC
Labels: api-suggestion, area-System.Runtime, untriaged
