### ISSUE TITLE
`TypeLoadException` when using a struct containing a static `ImmutableArray<T>` field/auto-property

### ISSUE THREAD

**Issue by colejohnson66** [dotnet/runtime#100077] opened 2024-03-21 13:43 UTC
### Description

An interesting one: consuming a DLL that exposes a type containing a static `ImmutableArray<T>` property. When `Program.Main` is async, you get a `TypeLoadException` at `stateMachine.MoveNext()`. When `Program.Main` is *sync*, the program simply never starts.

I've uploaded a [minimum reproducible example](https://github.com/colejohnson66/ImmutableArrayPropertyTypeLoadException). For preservation purposes, I've also attached a ZIP archive of the repository.

If you change the provided `Test()` method to directly print `Struct.One` (as below, and replace `Console.WriteLine(Test())` to `Test()`), then both sync and async versions will run all the way until `Test()` (including printing "Start" to the console, even for the sync version).

```cs
private static void Test()
{
    Console.WriteLine(Struct.One);
}
```

### Reproduction Steps

Create a library that contains a type, `MyType`. That type should have a static property of type `ImmutableArray<MyType>`. Optionally, initialize it with a collection expression in a static constructor. Our original code does contain a collection expression in the static constructor, but, if I recall correctly, commenting out the static constructor does not solve the issue (so it's not an exception in `.cctor`).

Build the library and take the DLL. Manually reference the DLL in the consuming project and attempt to use the type. Notice that the type exists, and that the compiler does not complain. At runtime, observe a `TypeLoadException`.

### Expected behavior

The program runs normally.

### Actual behavior

A `TypeLoadException` at runtime once usage of the type is encountered.

### Known Workarounds

Use a `ReadOnlyCollection<MyType>`. We were previously doing so with `Array.AsReadOnly(new MyType[] {...})`, but changing to use `ImmutableArray<MyType>` broke it.

### Configuration

* .NET 8.0.3
* Windows 11 x86-64 23H2

### Other information

[ImmutableArrayPropertyTypeLoadException-main.zip](https://github.com/dotnet/runtime/files/14695926/ImmutableArrayPropertyTypeLoadException-main.zip)

**Comment by JakeYallop** [comment] 2024-07-07 10:47
Just ran into this one myself. I'd done some refactoring and replaced a `MyStruct[]` with an `ImmutableArray<MyStruct>`. I was able to reproduce it running unit tests. You also don't need to reference a library to reproduce this, just creating a brand new console app with the struct in causes the issue:

This is all that's necessary:
[sharplab](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8ACATAIwCwAUPgAwAE+xAdAMID2ANmwKYDGCULMAM4MAkmDCoEEYFwDcFCvQCcAChicA7jQCyATwDKCNLxUBKU/PKKAzDUFHUvHQYe8KAbwo1vdYgDYaMQkpGU4AQWRkCF0AHj1DYwQAPhoAeXVLAF8gA===)
```csharp
using System;
using System.Collections.Immutable;

Console.WriteLine(new MyStruct());

public struct MyStruct
{
    static ImmutableArray<MyStruct> One;
}
```

**Comment by steveisok** [comment] 2024-07-18 14:59
Closing as it's a duplicate of https://github.com/dotnet/runtime/issues/104511

**Closed by steveisok** 2024-07-18 14:59 UTC
Labels: area-TypeSystem-coreclr
