### ISSUE TITLE
Bmi2.X64_r failed with  Could not load file or assembly 'C:\h\w\BA7A09DC\p\system.runtime.interopservices.dll'. Invalid access to memory location. (0x800703E6)

### ISSUE THREAD

**Issue by danmoseley** [dotnet/runtime#66484] opened 2022-03-10 22:56 UTC
https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-60507-merge-2dea9aa739eb481da4/JIT.HardwareIntrinsics.X86.Bmi2/1/console.2fd9eccb.log?sv=2019-07-07&se=2022-03-30T20%3A31%3A56Z&sr=c&sp=rl&sig=40pgxA%2BdwAJAn8wDMsAc%2Bnc7jjTEwrwQSc4RVoS7brw%3D
```
Console log: 'JIT.HardwareIntrinsics.X86.Bmi2' from job 2dea9aa7-39eb-481d-a4e6-2801af88b6e6 workitem 3e562884-bd8e-4c82-a187-ccddfb882bbf (windows.10.amd64.open.rt) executed on machine a00AQFJ

C:\h\w\BA7A09DC\w\AE9A0A15\e>dotnet C:\h\w\BA7A09DC\p\xunit\xunit.console.dll JIT\HardwareIntrinsics\JIT.HardwareIntrinsics.XUnitWrapper.dll -parallel collections -nocolor -noshadow -xml testResults.xml -trait TestGroup=JIT.HardwareIntrinsics.X86.Bmi2 
Microsoft.DotNet.XUnitConsoleRunner v2.5.0 (32-bit .NET 6.0.0-rtm.21522.10)
  Discovering: JIT.HardwareIntrinsics.XUnitWrapper (method display = ClassAndMethod, method display options = None)
  Discovered:  JIT.HardwareIntrinsics.XUnitWrapper (found 4 of 290 test cases)
  Starting:    JIT.HardwareIntrinsics.XUnitWrapper (parallel test collections = on, max threads = 4)
    JIT\HardwareIntrinsics\X86\Bmi2.X64\Bmi2.X64_r\Bmi2.X64_r.cmd [FAIL]
      Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'C:\h\w\BA7A09DC\p\system.runtime.interopservices.dll'. Invalid access to memory location. (0x800703E6)
      File name: 'C:\h\w\BA7A09DC\p\system.runtime.interopservices.dll'
         at Interop.Kernel32.WriteFile(IntPtr handle, Byte* bytes, Int32 numBytesToWrite, Int32& numBytesWritten, IntPtr mustBeZero)
         at System.ConsolePal.ConsoleHandleIsWritable(IntPtr outErrHandle)
         at System.ConsolePal.GetStandardFile(Int32 handleType, FileAccess access, Boolean useFileAPIs)
         at System.ConsolePal.OpenStandardOutput()
         at System.Console.<get_Out>g__EnsureInitialized|26_0()
         at System.Console.get_Out()
         at System.Console.WriteLine(String value)
         at TestLibrary.Logging.WriteLine(String value)
         at TestLibrary.TestFramework.LogInformation(String str)
         at JIT.HardwareIntrinsics.X86.Program.PrintSupportedIsa()
         at JIT.HardwareIntrinsics.X86.Program.Main(String[] args)
      
      Return code:      1
      Raw output file:      C:\h\w\BA7A09DC\w\AE9A0A15\uploads\Reports\JIT.HardwareIntrinsics\X86\Bmi2.X64\Bmi2.X64_r\Bmi2.X64_r.output.txt
      Raw output:
      BEGIN EXECUTION
       "C:\h\w\BA7A09DC\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  Bmi2.X64_r.dll 
      Expected: 100
      Actual: -532462766
      END EXECUTION - FAILED
      FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=C:\h\w\BA7A09DC\p
      > C:\h\w\BA7A09DC\w\AE9A0A15\e\JIT\HardwareIntrinsics\X86\Bmi2.X64\Bmi2.X64_r\Bmi2.X64_r.cmd
      Expected: True
      Actual:   False
```
broke Pr validation for https://github.com/dotnet/runtime/pull/60507

**Comment by danmoseley** [comment] 2022-03-10 22:57
Most likely this is some infra thing rather than interop.

**Comment by tannergooding** [comment] 2022-03-11 17:22
Dupe of https://github.com/dotnet/runtime/issues/65646

**Closed by tannergooding** 2022-03-11 17:22 UTC
Labels: area-System.Runtime.InteropServices, untriaged
