### ISSUE TITLE
No way to clear several items in IDistributedCache

### ISSUE THREAD

**Issue by dropsonic** [dotnet/runtime#36127] opened 2019-10-08 15:46 UTC
Hi,

In `IDistributedCache`, sometime it is required by the business logic to clear the cache entirely or to delete several items by some rule (e.g. "key starts with ZZZ"). But in the current model, you always have to know the key to remove an item from the cache.

Why is there no method like `IDistributedCache.Clear()` that clears the whole cache?

Thanks!

**Comment by eerhardt** [comment] 2020-10-07 15:36
Duplicate of #36568.

> Why is there no method like IDistributedCache.Clear() that clears the whole cache?

Duplicate of #36547.

**Closed by eerhardt** 2020-10-07 15:36 UTC
Labels: area-Extensions-Caching
