### ISSUE TITLE
JSON deserialization errors with response.Content.ReadFromJsonAsync<List<T>> where JsonSerializer.Deserialize works fine

### ISSUE THREAD

**Issue by mip1983** [dotnet/runtime#107279] opened 2024-09-03 08:02 UTC
### Description

I've started hitting some errors in my blazor web application (in a wasm component) where it's deserializing a response from an API. In debugging the code, I can't see anything wrong with the JSON and it serializes/deserializes fine server side and deserializes fine client side if I get the response as a string and use 'JsonSerializer.Deserialize'.

But, if I use:

```cs
mydata= await response.Content.ReadFromJsonAsync<List<MyType>>(serializerOpts, ct);
```

(Where serializer opts are the same as what was working with 'JsonSerializer.Deserialize'), I hit fairly non-descript exceptions where I can't see anything wrong with the item it's pointing at in the path e.g. 

```
System.Text.Json.JsonException: The JSON value could not be converted to <MyType>. Path: $[81] | LineNumber: 0 | BytePositionInLine: 49154.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[<MyType> ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, <MyType>& value)
   at System.Text.Json.Serialization.JsonConverter`1[[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, MeterListItem& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonCollectionConverter`2[[System.Collections.Generic.List`1[[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, List`1& value)
   at System.Text.Json.Serialization.JsonConverter`1[[System.Collections.Generic.List`1[[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, List`1& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1[[System.Collections.Generic.List`1[[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1[[System.Collections.Generic.List`1[[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.<DeserializeAsync>d__1[[System.Collections.Generic.List`1[[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Net.Http.Json.HttpContentJsonExtensions.<ReadFromJsonAsyncCore>d__12`1[[System.Collections.Generic.List`1[[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at ecoDriverAnalytics.Api.Client.HttpClients.MeterClient.Get<MyType>Async(Int32 userId, Int16 customerId, CancellationToken ct) in <Path>.ApiClient\HttpClients\<MyHttpClient>Client.cs:line 73
```

### .NET Version

8.0.401

### Anything else?

Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.11.2

Host:
  Version:     8.0.401 [C:\Program Files\dotnet\sdk]
  Architecture: x64
  Commit:       static

.NET SDKs installed:
  8.0.304 [C:\Program Files\dotnet\sdk]
  8.0.400 [C:\Program Files\dotnet\sdk]
  8.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.7.24406.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.7.24405.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

### Reproduction Steps

I can't tell what it doesn't like about the JSON in order to give a minimal repro. The Path/byte position of the sample error doesn't reveal anything meaningful as far as I can tell.

I can provide you with sample JSON to test against, you'll need to reach out to me directly so I can share this privately. 

### Expected behavior

If 'JsonSerializer.Deserialize' can deserialize some content, 'HttpResponseMessage.Content.ReadFromJsonAsync<List<T>' should be able to do the same with the same options without error (and if it does error, at the very least give some description as to what was wrong with the content).

### Actual behavior

System.Text.Json.JsonException: The JSON value could not be converted to <MyType>. Path: $[81] | LineNumber: 0 | BytePositionInLine: 49154.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1[[<MyType> ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, <MyType>& value)
   at System.Text.Json.Serialization.JsonConverter`1[[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, MeterListItem& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonCollectionConverter`2[[System.Collections.Generic.List`1[[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, List`1& value)
   at System.Text.Json.Serialization.JsonConverter`1[[System.Collections.Generic.List`1[[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, List`1& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1[[System.Collections.Generic.List`1[[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1[[System.Collections.Generic.List`1[[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ContinueDeserialize(ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.<DeserializeAsync>d__1[[System.Collections.Generic.List`1[[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Net.Http.Json.HttpContentJsonExtensions.<ReadFromJsonAsyncCore>d__12`1[[System.Collections.Generic.List`1[[<MyType>, ecoDriverCore.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at ecoDriverAnalytics.Api.Client.HttpClients.MeterClient.Get<MyType>Async(Int32 userId, Int16 customerId, CancellationToken ct) in <Path>.ApiClient\HttpClients\<MyHttpClient>Client.cs:line 73

### Known Workarounds

Provide increased 'DefaultBufferSize' in JsonSerializerOptions

### Other information

I've raised this here:

https://github.com/dotnet/aspnetcore/issues/57626

But I'm not sure if this belongs in this repo instead?

**Comment by huoyaoyuan** [comment] 2024-09-03 08:35
> if I get the response as a string and use 'JsonSerializer.Deserialize'

To clarify: are you consistently getting different behavior between `ReadFromJsonAsync` and `Deserialize(ReadAsStringAsync())` under the same `JsonSerializationOption`? That sounds really bad.

**Comment by mip1983** [comment] 2024-09-03 11:25
> > if I get the response as a string and use 'JsonSerializer.Deserialize'
> 
> To clarify: are you consistently getting different behavior between `ReadFromJsonAsync` and `Deserialize(ReadAsStringAsync())` under the same `JsonSerializationOption`? That sounds really bad.

Yes, same serializer options object passed to each in my testing. I can read the content as a string and then deserialize but if I try the direct method I consistently get the same error. If I change 'DefaultBufferSize' to 32000, it seems to fix it for now.

**Comment by eiriktsarpalis** [comment] 2024-09-09 10:09
It seems that the aspnetcore issue has prompted more discussion, so I'm going to close this one to keep our discussions concentrated. Once we've more accurately pinned down the problem, we can transfer the issue between repos.

Duplicate of https://github.com/dotnet/aspnetcore/issues/57626

**Closed by eiriktsarpalis** 2024-09-09 10:09 UTC
Labels: area-System.Text.Json, untriaged
