### ISSUE TITLE
Could IServiceProvider support modularlized applications?

### ISSUE THREAD

**Issue by mrpmorris** [dotnet/runtime#85907] opened 2023-05-08 08:46 UTC
To keep initial download time down, Blazor WASM allows us to modularize our applications and then have those modules downloaded when the user needs something within them.

Unfortunately, there is currently no way for IServiceProvider to do the same. So when an app's modules are loaded (Blazor or otherwise), none of the injected dependencies they hold can be registered.

I won't make a suggestion as to how to solve this problem, as I want the problem addressed rather than my idea considered :)

**Comment by steveharter** [comment] 2023-05-23 14:06
This is asking for a lazy-download DI option for assemblies needed by the app. Some sort of registration mechanism that doesn't require the target implementation assembly to be deployed ahead-of-time.

**Comment by gplwhite** [comment] 2023-09-19 05:22
Sounds like a duplicate of https://github.com/dotnet/runtime/issues/91163 ??

**Comment by steveharter** [comment] 2023-10-27 16:31
> Sounds like a duplicate of https://github.com/dotnet/runtime/issues/91163 ??

Yes that could be used to implement this, so closing this issue for now at least until that is implemented.

**Closed by steveharter** 2023-10-27 16:31 UTC
Labels: design-discussion, area-Extensions-DependencyInjection
