### ISSUE TITLE
Http: ActivityHeadersPropagator=null suppresses HttpClient tracing

### ISSUE THREAD

**Issue by markm77** [dotnet/runtime#90407] opened 2023-08-11 16:39 UTC
Hi there,

I raised this OpenTelemetry tracing issue: https://github.com/open-telemetry/opentelemetry-dotnet/issues/4761

But I am actually now wondering if this is a .NET issue. Basically whenever I disable header propagation with `ActivityHeadersPropagator = null` (see below code example), the `traceparent` header disappears (good) but additionally I no longer get tracing capture (shown below via console export) for HttpClient requests (see below tracing example of normal output which disappears). The tracing returns if I remove `ActivityHeadersPropagator = null`.

Is this design behaviour? How can I get tracing for HttpClient but not propagate the `traceparent` header externally?

Code example:
```csharp
var clientHandler = new SocketsHttpHandler
{
    ActivityHeadersPropagator = null // ensures no traceparent HTTP header but also disables tracing (!)
};
httpClient = new HttpClient(clientHandler);
```

Tracing example: 
Activity.TraceId:            49d270cd4150e8987ffcf54ec39f71b8
Activity.SpanId:             5fd61618faba6d3b
Activity.TraceFlags:         Recorded
Activity.ParentSpanId:       d34538734bc1a216
Activity.ActivitySourceName: System.Net.Http
Activity.DisplayName:        HTTP GET
Activity.Kind:               Client
Activity.StartTime:          2023-08-10T13:16:19.1421585Z
Activity.Duration:           00:00:00.0207056
< snip >

NB there are more details in linked Open Telemetry issue but basically I am using latest .NET 7 code.

**Comment by MihaZupan** [comment] 2023-08-11 17:15
Yes, this is by design.

If you want to see the events but not include any headers, you can set it to 
`DistributedContextPropagator.CreateNoOutputPropagator`.

**Comment by markm77** [comment] 2023-08-11 17:43
Thanks @MihaZupan for the quick response.

However when I try:
```csharp
 var clientHandler = new SocketsHttpHandler
        {
            //ActivityHeadersPropagator = null
            ActivityHeadersPropagator = DistributedContextPropagator.CreateNoOutputPropagator() // ensures no traceparent HTTP header
        };
```
I get a `traceparent` header on my outgoing HttpClient request again (in addition to desired tracing).

**Comment by MihaZupan** [comment] 2023-08-21 16:55
Reading the OpenTelemetry description about this: https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Api#context-propagation
Their instrumentation of HttpClient does not make use of the `ActivityHeadersPropagator`. Instead, they have their own (similar) API to do so.

You can set their propagator to some no-op implementation.
```c#
Sdk.SetDefaultTextMapPropagator(new CompositeTextMapPropagator(Array.Empty<TextMapPropagator>()));
```

Alternatively, [judging by their code](https://github.com/open-telemetry/opentelemetry-dotnet/blob/77b3a1ea6067d22fdac90015c361a35124edcbb2/src/OpenTelemetry.Instrumentation.Http/Implementation/HttpHandlerDiagnosticListener.cs#L126), if you set the `Sdk`'s propagator to `TraceContextPropagator`, it will fall back to using the `ActivityHeadersPropagator`.
```c#
Sdk.SetDefaultTextMapPropagator(new TraceContextPropagator());
```

**Comment by markm77** [comment] 2023-08-26 14:37
Hi @MihaZupan ,

Thanks for this, both your suggestions worked and thanks also for explaining that OpenTelemetry tracing uses their own propagator.

My understanding is `Sdk.SetDefaultTextMapPropagator` affects three instrumentation libraries I use (`OpenTelemetry.Instrumentation.AspNetCore`, `OpenTelemetry.Instrumentation.EntityFrameworkCore`, and `OpenTelemetry.Instrumentation.Http`) so using this to suppress `HttpClient` output propagation is less than ideal but I can't see any other solution.

I've decided to use
```csharp
Sdk.SetDefaultTextMapPropagator(new CompositeTextMapPropagator(Array.Empty<TextMapPropagator>()));
```
for now as your second suggestion might suddenly fail if the code you linked changes (feels a bit risky).

Thanks for all your help for what seems to be an OpenTelemetry issue, feel free to close this.

BR,
Mark

**Comment by karelz** [comment] 2023-08-29 08:58
Closing per recommendation above.

**Closed by karelz** 2023-08-29 08:58 UTC
Labels: area-System.Net.Http, untriaged
