### ISSUE TITLE
mono-aot-cross built without any ELF build ID/MacO Id 

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/runtime#47023] opened 2021-01-15 00:56 UTC
### Description

The mono-aot-cross binary in has no Build ID note in it, which causes it to not be indexable in our symbol server and is failing official builds: https://dnceng.visualstudio.com/internal/_build/results?buildId=951671

**Comment by hoyosjs** [comment] 2021-01-15 06:21
Wherever that is build, the compiler needs to get the following flags: --build-id=sha1 flag. See https://github.com/dotnet/runtime/pull/43993/files?diff=split&w=1

**Comment by akoeplinger** [comment] 2021-01-15 11:17
Hm this is almost certainly caused by https://github.com/dotnet/runtime/pull/43535 but we did get a green official build on the PR there: https://dev.azure.com/dnceng/internal/_build/results?buildId=950402&view=results

**Comment by akoeplinger** [comment] 2021-01-15 19:52
Fixed by https://github.com/dotnet/runtime/pull/47051

**Closed by akoeplinger** 2021-01-15 19:52 UTC
Labels: area-Infrastructure-mono, blocking-official-build
