### ISSUE TITLE
[arm64] Test Failed: arm64_cross_checked_windows_nt_corefx_jitstressregs

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#12307] opened 2019-03-21 02:06 UTC
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_jitstressregs0x80_tst/25/

**Log:**
```
Assertion Failed

   at System.Threading.ThreadPoolBoundHandle.BindHandleCore(SafeHandle handle)
   at System.Threading.ThreadPoolBoundHandle.BindHandle(SafeHandle handle)
   at System.Net.Sockets.SafeSocketHandle.GetOrAllocateThreadPoolBoundHandle(Boolean trySkipCompletionPortOnSuccess) in D:\j\workspace\arm64_cross_c---650b4731\_\fx\src\System.Net.Sockets\src\System\Net\Sockets\SafeSocketHandle.Windows.cs:line 51
   at System.Net.Sockets.Socket.GetOrAllocateThreadPoolBoundHandleSlow() in D:\j\workspace\arm64_cross_c---650b4731\_\fx\src\System.Net.Sockets\src\System\Net\Sockets\Socket.Windows.cs:line 304
   at System.Net.Sockets.BaseOverlappedAsyncResult.SetUnmanagedStructures(Object objectsToPin) in D:\j\workspace\arm64_cross_c---650b4731\_\fx\src\System.Net.Sockets\src\System\Net\Sockets\BaseOverlappedAsyncResult.Windows.cs:line 50
   at System.Net.Sockets.OverlappedAsyncResult.SetUnmanagedStructures(Byte[] buffer, Int32 offset, Int32 size, SocketAddress socketAddress) in D:\j\workspace\arm64_cross_c---650b4731\_\fx\src\System.Net.Sockets\src\System\Net\Sockets\OverlappedAsyncResult.Windows.cs:line 61
   at System.Net.Sockets.SocketPal.SendAsync(SafeSocketHandle handle, Byte[] buffer, Int32 offset, Int32 count, SocketFlags socketFlags, OverlappedAsyncResult asyncResult) in D:\j\workspace\arm64_cross_c---650b4731\_\fx\src\System.Net.Sockets\src\System\Net\Sockets\SocketPal.Windows.cs:line 917
   at System.Net.Sockets.Socket.DoBeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, OverlappedAsyncResult asyncResult) in D:\j\workspace\arm64_cross_c---650b4731\_\fx\src\System.Net.Sockets\src\System\Net\Sockets\Socket.cs:line 2562
   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode, AsyncCallback callback, Object state) in D:\j\workspace\arm64_cross_c---650b4731\_\fx\src\System.Net.Sockets\src\System\Net\Sockets\Socket.cs:line 2538
   at System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state) in D:\j\workspace\arm64_cross_c---650b4731\_\fx\src\System.Net.Sockets\src\System\Net\Sockets\Socket.cs:line 2504
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at System.Net.Sockets.Tests.SendReceive`1.<>c__DisplayClass15_1.<SendAsync_ConcurrentDispose_SucceedsOrThrowsAppropriateException>b__1() in D:\j\workspace\arm64_cross_c---650b4731\_\fx\src\System.Net.Sockets\tests\FunctionalTests\SendReceive.cs:line 881
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.<>c.<.cctor>b__10_0(Object s)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
exit code -2146232797 
```

**Comment by karelz** [comment] 2020-02-23 00:38
Unclear which test failure it tracks (to even say if it is a dupe of another existing tracking issue). Closing.

**Closed by karelz** 2020-02-23 00:38 UTC
Labels: arch-arm64, area-System.Net, os-windows, test-corefx
