### ISSUE TITLE
System.Text.Json SourceGenerator crashes if context is an inner class of a generic type

### ISSUE THREAD

**Issue by canton7** [dotnet/runtime#66881] opened 2022-03-19 11:20 UTC
### Description

If the `JsonSerializerContext` subclass given to the System.Text.Json source generator is a child of a generic class, the source generator crashes with the following exception, and does not generate any output:

> Warning CS8785: Generator 'JsonSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentOutOfRangeException' with message 'Length cannot be less than zero.

### Reproduction Steps

Create a .NET 6 project with the following code, and build:

```cs
public class Model
{
}

public partial class Test<T>
{
    [JsonSerializable(typeof(Model))]
    internal partial class MyJsonContext : JsonSerializerContext
    {
    }
}
```

### Expected behavior

The source generator either produces a diagnostic saying that this situation isn't supported, or correctly generates source.

### Actual behavior

The source generator crashes with the exception:

> ArgumentOutOfRangeException with message 'Length cannot be less than zero.'

### Regression?

No

### Known Workarounds

None

### Configuration

.NET 6, Visual Studio 17.2.0 Preview 1.0

**Comment by SteveDunn** [comment] 2022-03-19 13:20
I think the only solution to this is to generate an analysis error if the class is nested. Seems like an odd design, although I can see from the use in this PR that it's test related.

**Comment by canton7** [comment] 2022-03-19 13:27
The JsonSourceGenerator has specific logic to handle the context being a nested type, so I think removing that would be a breaking change. It should be a fairly straightforward fix: you don't need to repeat generic type parameters or anything with declaration another part of a partial generic class. You just need to make sure that you repeat the same type parameter names in the same order.

**Comment by stephentoub** [comment] 2022-03-24 14:52
Duplicate of https://github.com/dotnet/runtime/issues/62762

**Comment by canton7** [comment] 2022-03-24 14:57
I'm not sure if it is a duplicate. #62762 is about the *model* being an inner type of a generic type; this issue is about the *context* being an inner type of a generic type.

Although, the exception message is the same, so maybe it's the same underlying cause.

**Comment by layomia** [comment] 2022-03-30 18:49
Yes I believe this falls under the same general issue of the generator fumbling for open generic types.

**Closed by layomia** 2022-03-30 18:49 UTC
Labels: area-System.Text.Json, untriaged, source-generator
