### ISSUE TITLE
Equivalent for IgnoreIsSpecifiedMembers from Newtonsoft.Json

### ISSUE THREAD

**Issue by MeikelLP** [dotnet/runtime#108195] opened 2024-09-24 14:56 UTC
I'm trying to serialize a property `MyProperty` which have a sibling property name `MyPropertySpecified`. Sadly the property will not be serialized when `MyPropertySpecified` is `false`.

In `Newtonsoft.Json` I can set [`IgnoreIsSpecifiedMembers`](https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_Serialization_DefaultContractResolver_IgnoreIsSpecifiedMembers.htm) to `false` to mitigate this behaviour. Is there any equivalent setting in `System.Text.Json`?

This sadly prevents me from using System.Text.Json though I'd love to have its performance benefits.

**Comment by eiriktsarpalis** [comment] 2024-09-24 19:09
Duplicate of https://github.com/dotnet/runtime/issues/40395. Per the remark in https://github.com/dotnet/runtime/issues/40395#issuecomment-1187193565 you can use [contract customization](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/custom-contracts) to built functionality equivalent to `*IsSpecified` member support offer in System.Text.Json.

**Closed by eiriktsarpalis** 2024-09-24 19:09 UTC
Labels: area-System.Text.Json, untriaged
