### ISSUE TITLE
Timeouts in System.Linq.Expressions.Tests in OSX.10.14 Release

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/runtime#28923] opened 2019-03-11 02:50 UTC
On OS10.14 Release, the S.L.E tests timed out 3 times in a row, each time two tests were logged as long running. I am not sure whether both are just slow tests that need speeding up, or they are interfering and would do better run serially.
```
   System.Linq.Expressions.Tests: [Long Running Test] 'System.Linq.Expressions.Tests.ArrayBoundsTests.NewArrayBounds', Elapsed: 00:08:56
[Long Running Test] 'System.Linq.Expressions.Tests.CompilerTests.CompileDeepTree_NoStackOverflow', Elapsed: 00:09:50
```
https://mc.dot.net/#/product/netcore/30/source/official~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190310.2/workItem/System.Linq.Expressions.Tests/wilogs

**Comment by jaredpar** [comment] 2020-07-08 23:45
Closing as there are no recent reproductions of this test issue and it seems to be running just fine in the outer loop at this time.

**Closed by jaredpar** 2020-07-08 23:45 UTC
Labels: area-System.Linq.Expressions, test-run-core
