### ISSUE TITLE
.NET 7 breaking change in HttpClient timeout handling

### ISSUE THREAD

**Issue by yaakov-h** [dotnet/runtime#82878] opened 2023-03-02 06:18 UTC
### Description

.NET 7 has a breaking change when handling cancellation exceptions.

I could not find this documented at https://learn.microsoft.com/en-us/dotnet/core/compatibility/7.0

If a custom `HttpMessageHandler` throws an `OperationCanceledException` or `TaskCanceledException`, it no longer gets automatically wrapped to include a `TimeoutException`.

### Reproduction Steps

Compile the following code for .NET 6 and for .NET 7.

Run it on both.

```csharp
using System.Runtime.InteropServices;

namespace DotNetHttpRepro
{
    internal class Program
    {
        static async Task Main(string[] args)
        {
            Console.WriteLine(RuntimeInformation.FrameworkDescription);
            Console.WriteLine("------------------");
            Console.WriteLine("await task");
            Console.WriteLine("------------------");

            using var client = new HttpClient(new TimeoutHandler());
            client.Timeout = TimeSpan.FromMilliseconds(1);

            try
            {
                var task = await client.GetAsync("http://localhost");
            }
            catch (Exception ex)
            {
                DumpException(ex);
            }

            Console.WriteLine("------------------");
            Console.WriteLine("Task.Wait");
            Console.WriteLine("------------------");

            try
            {
                client.GetAsync("http://localhost").Wait();
            }
            catch (AggregateException ex)
            {
                DumpException(ex.InnerException!);
            }
        }

        static void DumpException(Exception ex, int indent = 0)
        {
            for (var i = 0; i < indent; i++)
            {
                Console.Write(" ");
            }

            Console.Write("> ");

            Console.WriteLine($"{ex.GetType().FullName}: {ex.Message}");

            if (ex.InnerException != null)
            {
                DumpException(ex.InnerException, indent + 2);
            }
        }


        class TimeoutHandler : HttpMessageHandler
        {
            protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
            {
                var cts = new CancellationTokenSource();
                cts.Cancel();
                cts.Token.ThrowIfCancellationRequested();

                throw null!;
            }
        }
    }
}
```

### Expected behavior

For both .NET 6 and .NET 7:

```
------------------
await task
------------------
> System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 0.001 seconds elapsing.
  > System.TimeoutException: The operation was canceled.
    > System.OperationCanceledException: The operation was canceled.
------------------
Task.Wait
------------------
> System.Threading.Tasks.TaskCanceledException: A task was canceled.
```

### Actual behavior

On .NET 7, the following output is observed instead:

```
------------------
await task
------------------
> System.OperationCanceledException: The operation was canceled.
------------------
Task.Wait
------------------
> System.Threading.Tasks.TaskCanceledException: A task was canceled.
```

### Regression?

Yes.

### Known Workarounds

Manually build and throw the TaskCanceledException + inner TimeoutException structure.

### Configuration

.NET 6.0.14 and .NET 7.0.3, x64, on Windows 11 22H2

**Comment by MihaZupan** [comment] 2023-03-02 06:34
This was an intentional change ([test for this exact scenario](https://github.com/MihaZupan/runtime/blob/fa7d049aad0261f8ed6c0584f1ccf2ad08aec23c/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientTest.cs#L827-L840) from #72274) to avoid reporting an HttpClient timeout when such a timeout did not occur.

In your example, if you change your logic to wait before throwing an `OperationCanceledException` such that the timeout does actually occur, you will see that it does get wrapped in a `TimeoutException`.
```c#
protected async override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
{
    await Task.Delay(100);
    var cts = new CancellationTokenSource();
    cts.Cancel();
    cts.Token.ThrowIfCancellationRequested();
    throw null!;
}

```

**Comment by ManickaP** [comment] 2023-03-17 09:37
Intentional change in 7.0, the behavior is as expected. Closing this as not a bug.

**Closed by ManickaP** 2023-03-17 09:37 UTC
Labels: area-System.Net.Http, untriaged

**Comment by yaakov-h** [comment] 2023-03-18 09:47
@ManickaP should this at least be added to the breaking changes list?
