### ISSUE TITLE
GetCultureInfo for Spanish reports invalid list separator

### ISSUE THREAD

**Issue by ClimberBear** [dotnet/runtime#44391] opened 2020-11-08 12:46 UTC
# Issue Title

GetCultureInfo for Spanish report invalid list separator (report "." instead of ";")

# General

The standard list separator for Spanish in Spain is the semi-colon, as you can see, e.g., exporting Excel files in CSV format.

But, if you execute
CultureInfo.GetCultureInfo("es-ES").TextInfo.ListSeparator
you get "."

My SDK is: 3.1.403 [/usr/local/share/dotnet/sdk] running in MacOS Catalina 10.15.7

**Comment by danmosemsft** [comment] 2020-11-08 20:10
Dupe of https://github.com/dotnet/runtime/issues/43795

**Comment by tarekgh** [comment] 2020-11-08 21:26
@ClimberBear thanks for reporting the issue. I'll close this one and please please follow up on the issue https://github.com/dotnet/runtime/issues/43795. 

Also, I need your feedback regarding the expected list separator value for Spanish culture. I understand you said you expect `;` but would `,` be a wrong value too? I want your feedback on the proposal https://github.com/dotnet/runtime/issues/43795#issuecomment-722049526. Please feel free to reply there so the feedback can be shared among others.

**Closed by tarekgh** 2020-11-08 21:26 UTC
Labels: area-System.Globalization
