### ISSUE TITLE
File.CreateAsSymbolicLink should throw if not able to create the symlink due to do not having permission

### ISSUE THREAD

**Issue by Raffaello** [dotnet/runtime#68525] opened 2022-04-25 22:35 UTC
### Description

when creating a symlink, it returns an object like the file was created, but there is no file, and it is not really clear why.
(it returns a `FileInfo` object, with `Exists==false` and `LinkTarger==null`.)

What is the point of a such successful failure?

It just misleading. 

It would be simpler if it will throw an [UnauthorizedAccessException](https://docs.microsoft.com/en-us/dotnet/api/system.unauthorizedaccessexception?view=net-6.0) or similar

much clearer and no need to understand why it has been created the object but not the file.
(Alternatively should return just null, not an object representing a non created file)

### Reproduction Steps

```csharp
string filePath = "myfullPathFile";
string linkTarget = "myfullPathFile.link";

FileInfo finfo = new(filePath);
FileInfo fi = new(linkTarget);

finfo.Create().Close();
Assert.IsTrue(finfo.Exists);

fi.CreateAsSymbolicLink(filePath);
Assert.IsTrue(fi.Exists); // here thrown, assert is false. And LinkTarger == null.
```

### Expected behavior

If it is because unauthorized operation, like not an admin. It should throw that kind of exception.

I tested only on Windows 10 - NET6.0.

not sure the behavior for eg on linux, but i would aspect if a user is not allowed to create a file in some directory, i would expect the same to receive something from the API to inform the caller that is unauthorized operation. instead of letting guess the caller and just considered it like a  "general File I/O Creation failure" because no more info are provided

### Actual behavior

It returns a FileInfo object representing the symlink file but it doesn't exists, so the `CreateAsSymboliLink` method basically has failed silently and need to check somethig specific in the result to guess that it might be because not authorized.

### Regression?

I think it is just a new API since NET6.0

### Known Workarounds

well check the properties Exists and LinkTarget to be valid values.

but still the point here is dealing with the Failure part, why is failing?
this information, in this case, is missing from `CreateAsSymboliLink` method.

### Configuration

6.0
Windows 10
x64
it is not. It is related to the symbolic link policy in Windows: by default symlink can only be created by an admin.
not using Blazor.

**Comment by Jozkee** [comment] 2022-04-26 00:06
Duplicate of https://github.com/dotnet/runtime/issues/62975, unfortunately the issue is with the Windows API.

**Closed by Jozkee** 2022-04-26 00:06 UTC
Labels: area-System.IO, untriaged

**Comment by Raffaello** [comment] 2022-04-26 08:13
> Duplicate of #62975, unfortunately the issue is with the Windows API.

yes the root cause it might be there and a bug in the kernel afterall, but this API could still perform an internal sanity check before returning a non valid result, as i am able to to understand from is returning result, if it has failed. 

for e.g.

as i am using this API, i need to verify the file is created and not just returning the object, therefore `CreateAsSymbolicLink` could do perform the same sanity checks before returning and correct is returning results.

it is not ideal, it doesn't fix the root cause, but at least for the .NET world perspective layer it can make the use of this function smoother.
