### ISSUE TITLE
Generics return type with explicit layout in PInvoke

### ISSUE THREAD

**Issue by Enigmatrix** [dotnet/runtime#37198] opened 2020-05-30 11:47 UTC
Types with generic parameters and explicit layout should be able to be returned from PInvoke methods (assuming the type is blittable/unmanaged of course).

Currently on .NET Core 3.1, and it just silently fails

**Comment by Enigmatrix** [comment] 2020-05-31 04:00
This is an example of the struct I am returning from a PInvoke function.
``` c#
[StructLayout(LayoutKind.Sequential)]
public struct Error
{
    public uint Code;
    public IntPtr Cause;
}

[StructLayout(LayoutKind.Explicit)]
public struct FfiResult<T> where T: unmanaged
{
    [FieldOffset(0)] public long Tag;
    [FieldOffset(8)] public T Ok;
    [FieldOffset(8)] public Error Error;
}
```
This gives `Could not load type 'FfiResult'1 from assembly '...' because generic types cannot have explicit layout`

**Comment by jkoritzinsky** [comment] 2021-06-21 23:20
I think this falls more under type system/vm than interop since the runtime blocks loading a generic type with explicit layout, so we don't even get to the point of failing to use it in interop scenarios.

**Comment by AaronRobinsonMSFT** [comment] 2022-05-21 17:32
Closing as this is a duplicate of https://github.com/dotnet/runtime/issues/43486.

**Closed by AaronRobinsonMSFT** 2022-05-21 17:32 UTC
Labels: area-TypeSystem-coreclr
