### ISSUE TITLE
ILAsm versions 5.0 or higher fail when given a res file generated by ILDasm

### ISSUE THREAD

**Issue by Newrad0603** [dotnet/runtime#109225] opened 2024-10-25 16:09 UTC
### Description

Attempting to round trip a dll through ILDasm and ILAsm without any changes fails to generate a dll when giving ILAsm the res file created by ILDasm. I've tracked down the failure point to the code in CeeFileGenWriter::emitResourceSection(). The code that scans the res sections never finds any .rsrc sections so the rsrc array check fails and bails. I'm not sure if ILDasm is not generating the proper res format or if ILAsm isn't parsing the res file correctly.

### Reproduction Steps

1) Create a C# Class Library project
2) Target it to .NET 472 (not sure if required for repro, but that's what VS builds target)
3) Build the project
4) Run ILDasm on the dll (just used /out switch)
    >C:\.tools\.nuget\packages\runtime.win-x64.microsoft.netcore.ildasm\8.0.0\runtimes\win-x64\native\ildasm.exe C:\source\repos\ClassLibrary3\ClassLibrary3\bin\Debug\net472\ClassLibrary3.dll /out=C:\source\repos\ClassLibrary3\ClassLibrary3\bin\Debug\net472\ClassLibrary3.il
5) Run ILAsm on the il and res generated by Step 4 (just used /out, /resource, and /dll switches)
    >C:\.tools\.nuget\packages\runtime.win-x64.microsoft.netcore.ilasm\8.0.0\runtimes\win-x64\native\ilasm.exe /dll /resource=C:\source\repos\ClassLibrary3\ClassLibrary3\bin\Debug\net472\ClassLibrary3.res C:\source\repos\ClassLibrary3\ClassLibrary3\bin\Debug\net472\ClassLibrary3.il /out=C:\source\repos\ClassLibrary3\ClassLibrary3\bin\Debug\net472\ClassLibrary3.roundtrip.dll

### Expected behavior

ILAsm successfully creates the dll with the given res entries

### Actual behavior

ILAsm throws the error:
>Could not create output file, error code=0x80070714

### Regression?

This works with the version of ILAsm that ships with Visual Studio and installs to:
>C:\Windows\Microsoft.NET\Framework64\v4.0.30319\ilasm.exe

**Comment by JulieLeeMSFT** [comment] 2024-10-25 16:52
@amanasifkhalid, here is one more high priority issue to include in this quarter's work.

**Comment by jkoritzinsky** [comment] 2024-10-25 17:54
This is a duplicate of https://github.com/dotnet/runtime/issues/11412

**Comment by JulieLeeMSFT** [comment] 2024-10-25 19:09
Closing as duplicate.

**Closed by JulieLeeMSFT** 2024-10-25 19:09 UTC
Labels: area-ILTools-coreclr, Priority:1
