### ISSUE TITLE
Unable to load shared library 'user32'

### ISSUE THREAD

**Issue by TheBarret** [dotnet/runtime#51342] opened 2021-04-15 21:03 UTC
Im not entirely sure what to do with this, this routines used to work but now it seems it requires the user32
on the dotnet unix compilation, where do I go from here?

### Description
This application is compiled in dotnet core 3.1 to be run on Linux,
it makes charts of chat stats, uses a bar graph to show the data visualized.

### Configuration
* Compiled: Dotnet core 3.1 LTS
* OS: Debian(10) Buster
* Arch: Amd64

### Error
```
System.DllNotFoundException: Unable to load shared library 'user32' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libuser32: cannot open shared object file: No such file or directory
   at System.Drawing.UnsafeNativeMethods.GetSystemMetrics(Int32 nIndex)
   at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
   at System.Drawing.Graphics.FillRectangle(Brush brush, Int32 x, Int32 y, Int32 width, Int32 height)
   at System.Drawing.Graphics.FillRectangle(Brush brush, Rectangle rect)
```

**Comment by safern** [comment] 2021-04-15 23:05
@TheBarret thanks for your report. I believe this is a dupe of: https://github.com/dotnet/runtime/issues/49275

However we only fixed this in main branch for .NET 6. You should be able to get this resolved by updating your package reference to version `6.0.0-preview.3.21201.4`. Is that something that works for you? 

I'm going to close the issue but feel free to reopen if that is not enough for you and we can see if this meets the bar to backport it to the 5.0 version of the package.

**Closed by safern** 2021-04-15 23:05 UTC
Labels: area-System.Drawing, untriaged
