### ISSUE TITLE
Could not load Microsoft.Bcl.AsyncInterfaces (1.1.0, 1.1.1) because transitive dependency is not recorded in .deps.json file

### ISSUE THREAD

**Issue by allxiao** [dotnet/runtime#47218] opened 2021-01-20 09:59 UTC
### Description

If the .dll is eventually resolved as `netstandard2.0`, the .NET Core app will fail to start after publish, with error messages:

```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
```

Steps to reproduce:

See [below follow-up](https://github.com/dotnet/runtime/issues/47218#issuecomment-763810511) for the reproduce steps.

---
Original
~~1. Download the package from NuGet [Microsoft.Bcl.AsyncInterfaces/1.1.1](https://www.nuget.org/packages/Microsoft.Bcl.AsyncInterfaces/1.1.1)~~
~~2. Extract the contents of the `.nupkg` file.~~
~~3. Check the file `lib/netstandard2.0/Microsoft.Bcl.AsyncInterfaces.dll`. The target framework is **.Net Framework v4.7.2**~~ (Update: for this piece, it may be a display issue in the tool I used.)

![image](https://user-images.githubusercontent.com/423695/105158127-9a558180-5b48-11eb-9e55-cf8ac30abac0.png)

### Configuration

Not required.

### Regression?

~~Both 1.1.0 and 1.1.1 are affected. Didn't check earlier versions.~~

**Comment by huoyaoyuan** [comment] 2021-01-20 10:52
No, it is .NET Standard dll.
![image](https://user-images.githubusercontent.com/5644458/105164601-477fc800-5b50-11eb-8cce-4d06a2c53b58.png)
The only difference of framework in dll is the BCL reference. It references `netstandard` so it is netstandard dll.

The tool you are using is detecting TFM wrongly.

Trying to load a .NET Framework dll won't result in `FileNotFoundException`, because there's compatibility shim. You are running into another problem.

**Comment by allxiao** [comment] 2021-01-20 17:30
@huoyaoyuan Yes, you're right. The `.NET Framework 4.7.2` displayed should be a problem with the tool dotPeek.

I managed to reproduce the file-not-found issue with minimal files ([Reproduce.zip](https://github.com/dotnet/runtime/files/5844035/Reproduce.zip)). It seems this is caused by uncommon project layout.

```
.
├── Entry                       # Main Entry netcoreapp3.1 project
│   ├── Entry.csproj            # References Autofac.Extensions.DependencyInjection 6.0.0. NO reference to the Lib project
│   ├── Entry.sln               # sln with both Entry and the Lib project
│   └── Program.cs              # Call new Autofac.ContainerBuilder() will cause the file not found exception
├── Lib                         # A dummy netstandard2.0 library project
│   ├── Class1.cs               
│   └── Lib.csproj              # References Autofac 5.0.0, which depends on Microsoft.Bcl.AsyncInterfaces 1.1.0+
└── publish.cmd
```

Run `dotnet publish -c Release -o publish` in the Entry directory, and then invoke `publish\Entry.exe` I will get the error.

* Entry project doesn't need to reference the Lib project to reproduce the issue
* The `Microsoft.Bcl.AsyncInterfaces.dll` (netstandard2.0) can be found in the published output, but there is no reference in the `Entry.deps.json` file.

This looks like to be a problem with `dotnet` command.

To breakout from this issue, I checked the following working options:
* Remove Lib project from Entry.sln
* Remove Entry.sln
* Add an explicit reference to Microsoft.Bcl.AsyncInterfaces 1.1.0 in the Entry project

However, I do not understand why this options will work.

**Comment by huoyaoyuan** [comment] 2021-01-20 17:39
The version numbers of 2 AutoFac components are not aligned, but they are neither latest.

Have you followed the [best practices](https://docs.microsoft.com/en-us/dotnet/core/tutorials/creating-app-with-plugin-support) to use plugin? Not following it will likely cause assembly loading issue.

**Comment by allxiao** [comment] 2021-01-20 17:43
The two Autofac libraries do not follow the same version numbers. They were released at the same date. Autofac.Extensions.DependencyInjection 6.0.0 depends on Autofac 5.0.0

**Comment by joperezr** [comment] 2021-02-09 21:40
Not sure I understand what the problem is here. When targetting .NET Core, Microsoft.Bcl.AsyncInterfaces will only ever be brought in as a transitive dependency (since asyncInterfaces are inbox on System.Runtime for .nET core) and whenever it gets brought in as the package closure, then the right shim for .NET Core should be resolved that remaps the types back to System.Runtime, so I'm not sure I follow the problem. Can you share a repro project where you are seeing this?

**Comment by allxiao** [comment] 2021-02-10 15:58
Hi @joperezr , I uploaded the minimal project setup to reproduce the problem in the earlier reply https://github.com/dotnet/runtime/issues/47218#issuecomment-763810511 : [Reproduce.zip](https://github.com/dotnet/runtime/files/5844035/Reproduce.zip).

**Comment by joperezr** [comment] 2021-02-10 18:25
Oh sorry I missed that. I have checked the project and now know what is going on. The problem here is that by running the publish command you have above, you are effectively publishing the output of two projects into the same directory, causing publish assets from one project to override the assets from the other one. More specifically, your lib project references Autofac package, and will get the netstandard2.0 asset (which depends on M.BCL.AI) because it targets netstandard2.0. On the other hand, Entry project references Autofac project but will get it's netstandard2.1 asset (which does NOT depend on M.BCL.AI) because it targets netcoreapp3.1 and the best applicable asset is netstandard2.1, as opposed to netstandard2.0. This explains why the deps.json for Entry does NOT include AsyncInterfaces, but what happens is that when you pass in the `-o publish` you are effectively making that both projects publish to the same directory, so the netstandard2.1 Autofac.dll is getting overwritten with the netstandard2.0 Autofac.dll which is what is causing the issue here. Publishing two different projects to the same directory is never advised, as things like the one happening here are very possible.

The reason why removing the sln fixes the issue, is because now the publish command will only actually publish the Entry.csproj project, so no overwrite happens as only one project gets published. Another way to fix this would be to add a reference to your lib project from Entry, and then ONLY publish Entry project which will publish all required files correctly.

I'll go ahead and close this issue since it is really just caused by an unadvised use of the publish command, but if you think otherwise or if my explanation above didn't make sense, please don't hesitate to reopen and ask any follow ups that may arise.

**Closed by joperezr** 2021-02-10 18:25 UTC
Labels: area-Meta, needs more info, untriaged

**Comment by joperezr** [comment] 2021-02-10 18:30
I also didn't mention it, but alternatively you could just not pass the `-o publish` argument to the publish command, and it will cause both projects to have different publish directories, which will al so fix the issue.

**Comment by allxiao** [comment] 2021-02-11 03:37
Thanks @joperezr for the detailed explanation.

To add a bit more, if a directory contains both `.csproj` and `.sln` files, when calling `dotnet publish`, it will by default pick up the `.sln` file. In my case this will publish both the `Entry` project and the `Lib` project to the output directory `publish`. The original gap was I thought I was publishing the `Entry` project only, which was not the case.

To publish the `Entry` project, specify the `.csproj` file explicitly to clear the ambiguity:

```
cd Entry
dotnet publish Entry.csproj -c Release -o ../publish
```
