### ISSUE TITLE
Blazor Crashes in AOT mode When Referencing SkiaSharp (Regression in NET8-preview.2)

### ISSUE THREAD

**Issue by elepner** [dotnet/runtime#83970] opened 2023-03-27 10:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When project has references to SkiaSharp and after publishing it in production with AOT flag, the application does not boot.

### Expected Behavior

Application should load like it used to in .NET 7.

### Steps To Reproduce

Minimalistic repository to reproduce the bug https://github.com/elepner/dotnet-8-preview-bug

### Exceptions (if any)

Here's the output of my browser after opening the application:
![image](https://user-images.githubusercontent.com/3992180/227922751-e569a0bf-135b-458c-91af-ceec3b543b7b.png)

### .NET Version

8.0.100-preview.2.23157.25

**Comment by vargaz** [comment] 2023-07-28 02:49
Can't reproduce with preview6.

**Comment by SamMonoRT** [comment] 2023-08-11 23:21
@elepner - Closing this issue as Fixed. Please re-open if you still repro with .NET8 Preview 6 or later builds.

**Closed by SamMonoRT** 2023-08-11 23:21 UTC
Labels: area-Codegen-AOT-mono, needs-author-action
