### ISSUE TITLE
dotnet --info from x64 on ARM64 machine reports both x64 and ARM64 paths

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#59832] opened 2021-09-30 21:50 UTC
### Description

Install both x64 and arm64 dotnet.
Run x64 `dotnet --info`

Expect: just see x64 paths
Actual: see x64 and arm64 paths

### Configuration

* Which version of .NET is the code running on? 6.0 RC2
* What OS and version, and what distro if applicable? Win11
* What is the architecture (x64, x86, ARM, ARM64)? ARM64
* Do you know whether it is specific to that configuration? Yes

Bug is here:

https://github.com/dotnet/runtime/blob/1517985a85ed8af90e762f5b9ebeefd5827096e3/src/native/corehost/hostmisc/pal.windows.cpp#L280-L294

**Comment by richlander** [comment] 2021-09-30 22:19
+1

We want this change.

**Comment by ericstj** [comment] 2021-09-30 22:19
On x64 on ARM64 that ought to return a path with x64 suffix

**Comment by agocke** [comment] 2021-09-30 22:24
@mateoatr Can you look into this?

**Comment by agocke** [comment] 2021-09-30 22:24
Looks related to https://github.com/dotnet/runtime/issues/51101

**Comment by richlander** [comment] 2021-09-30 22:40
Here's what I think the ideal text would look like:

```bash
rich@MacBook-Air-M1-2020 ~ % dotnet --info                            
.NET SDK (reflecting any global.json):
 Version:   6.0.100-rc.2.21478.25
 Commit:    e3936c2261

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.0
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.100-rc.2.21478.25/

Host (useful for support):
  Version: 6.0.0-rc.2.21474.18
  Commit:  d1c6659c2d

.NET SDKs installed:
  6.0.100-rc.2.21473.35 [/usr/local/share/dotnet/sdk]
  6.0.100-rc.2.21478.25 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0-rc.2.21470.37 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-rc.2.21475.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21470.23 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-rc.2.21474.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Architectures installed:
 Arm64 [/usr/local/share/dotnet/sdk]
 x64 [/usr/local/share/dotnet/sdk/x64]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by agocke** [comment] 2021-09-30 23:06
You think the `.NET SDKs installed` section shouldn't have architectures for each SDK?

**Comment by richlander** [comment] 2021-09-30 23:21
It could go either way.

In the general case, a given `dotnet` doesn't see all the other SDKs and runtimes, so it doesn't make sense to me to advertise them in a first-class way. For example, if you get an error that says you are missing .NET 5, it doesn't really help to see it as installed. I think the more "hint" based approach that I'm suggesting is better and then the output is clean and targeted. It is saying "these are the runtimes and sdks you can use is you continue using this `dotnet`."

**Comment by ericstj** [comment] 2021-09-30 23:29
I bet this is also related to https://github.com/dotnet/runtime/issues/59473 since it looks like that's likely influenced by the same default linked above.

**Comment by vitek-karas** [comment] 2021-10-01 15:19
#59473 is basically a dupe of this, just different manifestation. We can consider this for 6, but it should not matter than much (outside of `dotnet --info`).
#51101 is the real fix for the `dotnet --info` but that's a bit harder to implement (I would definitely not do this for 6).

**Comment by ericstj** [comment] 2021-10-01 15:25
Agreed, I'm fine if we dupe this to #59473

**Comment by agocke** [comment] 2021-10-01 18:14
Dup of https://github.com/dotnet/runtime/issues/59473

**Closed by agocke** 2021-10-01 18:14 UTC
Labels: area-Host
