### ISSUE TITLE
`DateTime.Now.ToString("r")` incorrectly attributes GMT

### ISSUE THREAD

**Issue by timheuer** [dotnet/runtime#74182] opened 2022-08-18 21:40 UTC
### Description

`DateTime.Now.ToString("r")` stamps the LOCAL time but appends `GMT` on the string, resulting in an INCORRECT output value.

```
Console.WriteLine(DateTime.Now.ToString("r"));
Console.WriteLine(DateTime.UtcNow.ToString("r"));
Console.WriteLine(DateTimeOffset.Now.ToString("r"));
Console.WriteLine(DateTimeOffset.UtcNow.ToString("r"));
```
produces:
```
Thu, 18 Aug 2022 14:33:58 GMT
Thu, 18 Aug 2022 21:33:59 GMT
Thu, 18 Aug 2022 21:33:59 GMT
Thu, 18 Aug 2022 21:33:59 GMT
```

The first line is factually incorrect, yet what the code produces.

[Documentation ](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#the-rfc1123-r-r-format-specifier) points to the following note:

> Although the RFC 1123 standard expresses a time as Coordinated Universal Time (UTC), the **formatting operation does not modify the value** of the [DateTime](https://docs.microsoft.com/en-us/dotnet/api/system.datetime) object that is being formatted. Therefore, you must convert the [DateTime](https://docs.microsoft.com/en-us/dotnet/api/system.datetime) value to UTC by calling the [DateTime.ToUniversalTime](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.touniversaltime) method before you perform the formatting operation. In contrast, [DateTimeOffset](https://docs.microsoft.com/en-us/dotnet/api/system.datetimeoffset) values perform this conversion automatically; there is no need to call the [DateTimeOffset.ToUniversalTime](https://docs.microsoft.com/en-us/dotnet/api/system.datetimeoffset.touniversaltime) method before the formatting operation. DateTime Struct (System) Represents an instant in time, typically expressed as a date and time of day.

The documentation effectively reads like we documented an unfixed bug.

### Reproduction Steps

`Console.WriteLine(DateTime.Now.ToString("r"));`

### Expected behavior

Would produce either a) the actual GMT correct value or b) the correct timezone noting -- but not a mix of both resulting in an incorrect value.

### Actual behavior

Local time with a `GMT` timezone stamp which is wrong

### Known Workarounds

Don't use `DateTime.Now`, use `DateTime.UtcNow` or `DateTimeOffset`

### Configuration

.NET 7

**Comment by danmoseley** [comment] 2022-08-18 21:43
Curious how much confusion this causes w/others, and whether it's enough to think about whether there's anything we can do to mitigate the wierdness.

**Comment by Clockwork-Muse** [comment] 2022-08-18 23:12
> The documentation effectively reads like we documented an unfixed bug.

Probably backwards compatibility concerns from when `DateTimeKind` was introduced?  Before that all times were "unspecified", and had no way to discern whether times were UTC (which isn't really GMT, but...) or not.
Note that if `DateTime.Kind == DateTimeKind.Unspecified`, the value that `DateTime.ToUniversalTime()` outputs _will be wrong_ if the zone isn't actually in the local timezone/offset, so the remark isn't completely correct anyways.

Which brings me to my next point: regardless of whether or not we fix/change this, no new code should be using the path that hits this (and anything that currently does should be migrated).  
 - The only "legitimate" use of this is for an HTTP header (and `HttpClient` will do the formatting for you, as should any well-behaved web interface library, based off `DateTimeOffset`).
 - `DateTime` generally has issues due to `DateTimeKind`, and should be avoided in preference for `DateTimeOffset` (or NodaTime, if your needs are more than trivial).
 - The format won't be used for internationalization/culture reasons (well, you could end up with the same format, but you won't be using the `"r"` specifier).
 - The format won't be used for data transfer reasons (because you should be using ISO, full stop - and `DateTimeOffset` or NodaTime).

**Comment by danmoseley** [comment] 2022-08-19 00:12
That sounds about right. @timheuer any reason you're not using `DateTimeOffset`? Is it size, or legacy API? (I find @mattjohnsonpint answer very useful: https://stackoverflow.com/questions/4331189/datetime-vs-datetimeoffset)

We have various tools (attributes, analyzers) for deprecating API, but not for deprecating a format specifier. It would need its own analyzer.

**Comment by mattjohnsonpint** [comment] 2022-08-19 17:55
> * `DateTime` generally has issues due to `DateTimeKind`, and should be avoided in preference for `DateTimeOffset`

@Clockwork-Muse - I agree with everything you said except for that.  While that's been reguritated many times (such as in the [Date and Time Guidance](https://docs.microsoft.com/en-us/dotnet/standard/datetime/choosing-between-datetime#the-datetimeoffset-structure) in the docs), it's led to people thinking `DateTime` is deprecated and has no valid use - which is far from the reality.

Instead of recommending `DateTime` be avoided, we should be giving senario-based recommendations such as the following:

> - To represent an absolute point in time such as when recording the time that a transaction occurred, use a `DateTimeOffset`.
> - To represent a date and time in the abstract, such as the time a future event will take place, use a `DateTime`.
> - To represent a date that has no associated time, such as a birthdate business date, or holiday, use a `DateOnly`.
> - To represent a time that has no associated date, such as the time a business opens every day, use a `TimeOnly`.
> - To represent a duration of elapsed time, such as the number of minutes it takes to perform a task, use a `TimeSpan`.
> - To represent a time zone, inclusive of daylight saving time and historical changes to offsets, use a `TimeZoneInfo`.
> - To represent a time zone offset at a particular point in time, use a `TimeSpan`.

**Comment by mattjohnsonpint** [comment] 2022-08-19 18:16
As far as the `"r"` format specifier goes - if we were wanting to make a breaking change, then we could do the following:

```csharp
DateTime.Now.ToString("r")                           == "Thu, 18 Aug 2022 14:33:59 -0700"
DateTime.UtcNow.ToString("r")                        == "Thu, 18 Aug 2022 21:33:59 GMT"
new DateTime(2022, 8, 18, 21, 33, 59).ToString("r")  == "Thu, 18 Aug 2022 21:33:59 GMT"   // Unspecified == Utc
DateTimeOffset.Now.ToString("r")                     == "Thu, 18 Aug 2022 14:33:59 -0700"
DateTimeOffset.UtcNow.ToString("r")                  == "Thu, 18 Aug 2022 21:33:59 GMT"   // Use GMT for +0000
```

These would all still be compliant with RFC 1123/822/2822/5322
We'd then have to document that we were making a breaking change to provide better compliance with the spec, but grandfathering in that `DateTimeKind.Unspecified` is treated as `DateTimeKind.Utc`.

Note on the last one, I think it's important to also stay compliant with the [HTTP Date Header in RFC 7231](https://httpwg.org/specs/rfc7231.html#http.date) for `DateTimeOffset.UtcNow`, so we would emit `GMT` instead of `+0000`.  The trade-off is that there are local times that are also UTC+0 (such as England in the winter, or Iceland year-round) that would see "GMT" instead of their local offset.

**Comment by timheuer** [comment] 2022-08-19 18:48
> That sounds about right. @timheuer any reason you're not using `DateTimeOffset`? Is it size, or legacy API? (I find @mattjohnsonpint answer very useful: [stackoverflow.com/questions/4331189/datetime-vs-datetimeoffset](https://stackoverflow.com/questions/4331189/datetime-vs-datetimeoffset))

Excellent question @danmoseley -- the real answer is indeed legacy/muscle memory and IntelliSense offering...oh and the fact the API seems clear to me -- I want to work with Dates and Times...hmmm, `DateTime` seems to be a great API and it has everything I need a `Now` and all sorts of things.  It isn't intuitive to me that `DateTimeOffset` is a 'better' thing than `DateTime` -- that's my real answer.

**Comment by Clockwork-Muse** [comment] 2022-08-19 21:12
.... It depends on what exactly you're doing with the date/time values, but disregarding some of the minor differences @mattjohnsonpint and I have over `DateTime`/`DateTimeOffset`, there's probably no real reason for you to be using the `"r"` specifier. If you're using `DateTime(Offset).Now`, this implies that the value is being generated/displayed on a client computer, and the formatting should be coming from the client culture.

**Comment by timheuer** [comment] 2022-08-19 21:30
@Clockwork-Muse I used the `"r"` specifier because it was the format I was initially looking for as output. The APIs did not put me on a path of success is all really.  Even the docs show in example that the GMT would be adjusted:
![image](https://user-images.githubusercontent.com/4821/185709775-7e11d82b-0927-4ef4-94c2-7ef911ea5d77.png)

and notes: 
> Unless otherwise noted, a particular standard date and time format specifier produces an identical string representation regardless of whether it is used with a [DateTime](https://docs.microsoft.com/en-us/dotnet/api/system.datetime) or a [DateTimeOffset](https://docs.microsoft.com/en-us/dotnet/api/system.datetimeoffset) value.

So a mix of missed expectations and conflicting docs...but I'm in the "now I know" category, but didn't feel I should be here.

**Comment by danmoseley** [comment] 2022-08-19 22:53
> if we were wanting to make a breaking change for .NET 7

I don't have an opinion on whether we should make a change, but it wouldn't be for .NET 7. .NET 7 is now done, save significant bugs/regressions and nothing is new here. Main is .NET 8.

**Comment by danmoseley** [comment] 2022-08-19 22:53
If @mattjohnsonpint guidance above is canonical (and he's an expert) should we have it in the docs somewhere (if we don't already)?

Should we put a note in the docs discouraging 'r' on DateTime?

**Comment by danmoseley** [comment] 2022-08-19 22:55
> To represent a date and time in the abstract, such as the time a future event will take place, use a DateTime.

With the offset implicit through context? Or do you mean, a value that's independent of offset. For example, my birthday runs 12am to 12pm on 10/25/73 whatever the offset - I actually don't want an offset.

**Comment by Clockwork-Muse** [comment] 2022-08-19 23:03
> With the offset implicit through context? Or do you mean, a value that's independent of offset.

Right, this is my issue with `DateTime` - because `DateTime.Kind` sorta gives you an offset or multiple (I wouldn't have an issue if there wasn't `Kind`).

> For example, my birthday runs 12am to 12am on 10/25/73

Dates don't necessarily start at 12am.  That aside, there's multiple issues here:
 - The actual _event_ of you being born should be `DateTimeOffset` + zone id (Absolute stamp)
 - The yearly reoccurrence is actually a Month+Day pair, not even `Date` - the time is irrelevant if it's the "whole day"
 - Using an inclusive upper bound ("last instant of day") is problematic - a day lasts until the next day starts, which isn't quite the same thing.

**Comment by Clockwork-Muse** [comment] 2022-08-19 23:16
> I used the "r" specifier because it was the format I was initially looking for as output.

Unless you're specifically writing a library that needs to do web protocol things referencing one of the relevant RFCs, ignore that specifier.

The primary problem is that any string you display to the user should be localized, and the various day/month names with that specifier will **only** be in English.  There's also the issue that in most cases localized date/times should be using one of the long/short formats that comes from the OS culture settings, and your program shouldn't know/care what they look like.  In some cases, the long format may include the day-of-week or the month name, but that's not something you should normally need to worry about.

If you're trying to get a common format for interchange, you need to use the `"u"` (universal sortable, essentially ISO) specifier.

**Comment by timheuer** [comment] 2022-08-19 23:39
> The primary problem is that any string you display to the user should be localized

This is not universally true.  This is a timestamp and follows conventions for other standards representing as Zulu time. (this is being used for a container timestamp creation)

**Comment by mattjohnsonpint** [comment] 2022-08-19 23:57
If that's the case,  probably best to stick to ISO 8601 ("o")  format,  with the invariant culture.

**Comment by danmoseley** [comment] 2022-08-20 00:05
@mattjohnsonpint  could you clarify this then, given answers above? Isn't a future event typically subject to an offset as well?
Put another way, what are the disadvantages of using DateTimeOffset over DateTime (other that discoverability, existing API, and perhaps size)?

> To represent a date and time in the abstract, such as the time a future event will take place, use a DateTime.

**Comment by danmoseley** [comment] 2022-08-20 00:29
Looks like https://github.com/dotnet/runtime/issues/68122 is a dupe of this or vice versa.

**Comment by Clockwork-Muse** [comment] 2022-08-20 00:40
> If that's the case, probably best to stick to ISO 8601 ("o") format, with the invariant culture.

Yes, use this one.

**Comment by mattjohnsonpint** [comment] 2022-08-20 00:45
> Isn't a future event typically subject to an offset as well?

Not a deterministic one. 

- The offset *now* might be different than the offset *then*
- You might think you can predict that offset,  but... 
  -  Governments fiddle with DST rules and offsets
  -  Some events are based on "wherever the user happens to be at the time",  such as the alarm clock on a phone. 

> Put another way, what are the disadvantages of using DateTimeOffset over DateTime

It fixes the value to an exact instant in time,  whereas the value may have been intended to be more of an abstract concept. 

Ex: "On Dec 25th,  all stores will close early at 3:00pm" can only be represented with a `DateTime`

**Comment by danmoseley** [comment] 2022-08-20 04:58
Got it. Nevertheless is it the case that much usage of DateTime today does intend a timezone (usually implicitly) and it's being used because it's got the obvious name or it predates DateTimeOffset or some API requires it. Would that be a reasonable assumption?

**Comment by mattjohnsonpint** [comment] 2022-08-21 03:10
Much usage, yes - but whether that's more or less would be impossible to say.  There have always been cases for both "timezoned" and "timezoneless" datetimes.  There always will be.

My personal opinion is that most developers reach for `DateTime` because of its name.  Perhaps the word "offset" in `DateTimeOffset` isn't a concept they've considered.  That doesn't mean that one is better or worse though - they're just for different scenarios.

Part of it might be that in some cases you can bend the rules a bit.  For example, while I would *recommend* a `DateTimeOffset` when dealing with an absolute point in time, you could get away with using a `DateTime` if you just always kept it in terms of UTC.  You don't even need to strictly keep it in `DateTimeKind.Utc` mode.  You could leave it `Unspecified`, and it would be fine - as long as you didn't have any use cases where you needed to convert it to another time zone, format it as a string with a UTC indicator, etc.  Even in those cases, there are workarounds like using `TimeZoneInfo.ConvertTimeFromUtc` (which treats Unspecified as UTC), and just putting a `Z` or `UTC` in the format string (since none of those are valid specifier tokens, they're copied into the output).  

My point is, you can tell people all day long about `DateTimeOffset` and that they should use it for instants - but many of them will say they've never used it and never had a problem - and they're right.

But at the same time, if you took `DateTime` away and *made* them use `DateTimeOffset` (or flagged it with an analyzer, etc.), you'd have a ton of complaints on your hands because too many scenarios that *require* it - like those I outlined.

FYI, this argument has played out before - in OData - with horrible results.  Back when OData came out, it supported `DateTime` - but then somewhere along the way they decided that they would drop it completely.  The results have been horrible.  So many people have `DateTime` data in their schemas, and they were forced to use `DateTimeOffset` instead - even for whole dates.  We actually have guidance [in our docs](https://docs.microsoft.com/en-us/odata/webapi/datetime-support) that walks someone through using a `DateTimeOffset` to query a customer's birthday - which is quite wrong and will likely miss some results depending on the time zones involved...  I would speculate that not having proper support for `DateTime` is one of the contributing factors to why OData isn't used much today.

Also, FWIW just about every language has had its battles with date and time APIs.   .NET is not alone in this regard. :wink:

**Comment by Clockwork-Muse** [comment] 2022-08-21 04:14
> Also, FWIW just about every language has had its battles with date and time APIs. .NET is not alone in this regard.

Yes, but at least Java's was _so_ bad they got a new, sane date/time API out of it.
... not that everybody's moved to it yet (I've reviewed code from a major contractor that used `java.util.Date` in new code...)

**Comment by danmoseley** [comment] 2022-08-21 05:18
Educational @mattjohnsonpint thanks.

**Comment by tannergooding** [comment] 2022-08-22 14:13
CC. @tarekgh. You're normally involved with the Date/Time related work

**Comment by tarekgh** [comment] 2022-08-22 16:22
going back to the original issue, I already discussed this a few days agon with @timheuer. My take here is not to change anything as this is the behavior since day one and we are clearly documenting the behavior as indicated. Is not worth the app-compat breaks especially since we have some easier alternatives.

**Closed** 2022-08-22 16:23 UTC
Labels: area-System.Runtime
