### ISSUE TITLE
On Android, DateTime.ToString("F") or ("f") returns the wrong result in Japanese locale

### ISSUE THREAD

**Issue by cotrasys** [dotnet/runtime#105097] opened 2024-07-18 07:11 UTC
### Description

When DateTime.ToString() is used with the Format specifier "f" or "F", returns the result includes "X曜日".
"X曜日" is meaning the names of the day of the week in Japanese language.

DateTimeFormatInfo.FullDateTimePattern Property (System.Globalization) | Microsoft Learn
https://learn.microsoft.com/en-us/dotnet/api/system.globalization.datetimeformatinfo.fulldatetimepattern?view=net-8.0
This document is showing examples correct format about FullDateTimePattern "F".
```
  en-US     dddd, MMMM dd, yyyy h:mm:ss tt
  ja-JP     yyyy'年'M'月'd'日' H:mm:ss
  fr-FR     dddd d MMMM yyyy HH:mm:ss
```
InteliSense says like this too. 
![image](https://github.com/user-attachments/assets/4b24937c-99e1-460e-bd58-984981abdd0c)

### Steps to Reproduce

1. Write down anywhere this code and execute an app.
```
Debug.WriteLine(new DateTime().ToString("g", new CultureInfo("ja-JP")));
Debug.WriteLine(new DateTime().ToString("G", new CultureInfo("ja-JP")));
Debug.WriteLine(new DateTime().ToString("f", new CultureInfo("ja-JP")));
Debug.WriteLine(new DateTime().ToString("F", new CultureInfo("ja-JP")));
```
2. You'll see this result when app running on other platform or Xamarin.Forms
```
0001/01/01 0:00
0001/01/01 0:00:00
0001年1月1日 0:00
0001年1月1日 0:00:00
```
3. But on MAUI Android, you encount this wrong result
```
0001/01/01 0:00
0001/01/01 0:00:00
0001年1月1日月曜日 0:00
0001年1月1日月曜日 0:00:00
```

### Version with bug

8.0.70 SR7

### Is this a regression from previous behavior?

Yes, this used to work in Xamarin.Forms

### Last version that worked well

Unknown/Other

### Affected platforms

Android

### Did you find any workaround?

Write the format by yourself.

```
Debug.WriteLine(new DateTime().ToString("yyyy年M月d日 H:mm")); // This equals to "f"
Debug.WriteLine(new DateTime().ToString("yyyy年M月d日 H:mm:ss")); // This equals to "F"
```

**Comment by matouskozak** [comment] 2024-07-19 11:22
I've tried the 8.0.7 servicing and I'm getting the
```
0001年1月1日月曜日 0:00
0001年1月1日月曜日 0:00:00
```
on both `dotnet new android` and `dotnet new maui` Android apps.

I even get 
```
0001年1月1日 月曜日 0:00
0001年1月1日 月曜日 0:00:00
``` 
On a desktop console app which suggest this could have been caused by ICU change.

@cotrasys Could you please share what version of .NET and OS version did you use before to get the expected behavior?

**Comment by tarekgh** [comment] 2024-07-19 12:24
>  @tarekgh do you know why it differs from the example https://learn.microsoft.com/en-us/dotnet/api/system.globalization.datetimeformatinfo.fulldatetimepattern?view=net-8.0

The example is written long ago before .NET Core and switching to use ICU.

**Comment by cotrasys** [comment] 2024-07-23 02:24
> @cotrasys Could you please share what version of .NET and OS version did you use before to get the expected behavior?
I'm using Zenfone 9, Android 14.
I created new Xamarin.Forms 5.0.0.2196 project (which using TargetFramework is "netstandard2.0"), it has no problem.
I found this issue on MAUI project .NET 7.0.20 / MauiVersion 7.0.101 and .NET 8.0.7 / MauiVersion 8.0.70

I tested too on such a simple Console app on Windows 10 Home x64 22H2, using "5.0.17" "6.0.32", "7.0.20" and "8.0.7".
I got expected result, no issue.

**Comment by vitek-karas** [comment] 2024-07-23 07:47
Just curious about your testing on non-mobile platforms.

Running the repro on Win 11, .NET 9 Preview 4:
```
0001/01/01 0:00
0001/01/01 0:00:00
0001年1月1日月曜日 0:00
0001年1月1日月曜日 0:00:00
```

The same on .NET 6:
```
0001/01/01 0:00
0001/01/01 0:00:00
0001?1?1???? 0:00
0001?1?1???? 0:00:00
```
(ignoring the fact that the unicode characters got corrupted by console output, it does match the "long" version of the output.

The same on Ubuntu .NET 7:
```
0001/01/01 0:00
0001/01/01 0:00:00
0001年1月1日月曜日 0:00
0001年1月1日月曜日 0:00:00
```

**Comment by matouskozak** [comment] 2024-07-23 14:14
> @matouskozak
> 
> > @cotrasys Could you please share what version of .NET and OS version did you use before to get the expected behavior?
> 
> I'm using Zenfone 9, Android 14. I created new Xamarin.Forms 5.0.0.2196 project (which using TargetFramework is "netstandard2.0"), it has no problem. I found this issue on MAUI project .NET 7.0.20 / MauiVersion 7.0.101 and .NET 8.0.7 / MauiVersion 8.0.70
> 
> I tested too on such a simple Console app on Windows 10 Home x64 22H2, using "5.0.17" "6.0.32", "7.0.20" and "8.0.7". I got expected result, no issue.

We found that the expected behavior is reproducible with enabled NLS https://learn.microsoft.com/en-us/windows/win32/intl/national-language-support. NLS has to be enabled manually or when there is an issue with loading ICU. Either way, we won't be able to get the expected behavior on Android because we depend on the system ICU and that contains the names of the days and NLS is not available on Android.

I've opened a PR for updating the documentation to represent the ICU behavior https://github.com/dotnet/dotnet-api-docs/pull/10141.

**Comment by vitek-karas** [comment] 2024-07-24 11:07
Closing since the behavior is as expected. https://github.com/dotnet/dotnet-api-docs/pull/10141 will update the docs to match the actual behavior.

**Closed by vitek-karas** 2024-07-24 11:07 UTC
Labels: area-System.Globalization, os-android
