### ISSUE TITLE
Test failure JIT\\HardwareIntrinsics\\X86\\Sse2\\StoreAligned_r\\StoreAligned_r.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#65982] opened 2022-03-01 01:31 UTC
Run: [runtime-coreclr crossgen2 20220227.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1635471&view=ms.vss-test-web.build-test-results-tab&runId=45290298&paneView=debug&resultId=100641)

Failed test:
```
R2R-CG2 windows x64 Checked @ Windows.10.Amd64.Open

- JIT\\HardwareIntrinsics\\X86\\Sse2\\StoreAligned_r\\StoreAligned_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse2\\LoadLow_ro\\LoadLow_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse2\\ConvertScalarToVector128Double_ro\\ConvertScalarToVector128Double_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse2\\StoreAlignedNonTemporal_ro\\StoreAlignedNonTemporal_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse2\\MoveScalar.UInt64_ro\\MoveScalar.UInt64_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse2\\MoveScalar.Int64_ro\\MoveScalar.Int64_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse2\\MoveScalar.Int64_r\\MoveScalar.Int64_r.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse2\\StoreScalar_ro\\StoreScalar_ro.cmd
- JIT\\HardwareIntrinsics\\X86\\Sse2\\**
```
**Error message:**
```
Could Not Find C:\h\w\AAFB0913\w\9D3208B9\e\JIT\HardwareIntrinsics\X86\Sse2\StoreAligned_r\IL-CG2\composite-r2r.dll
Could Not Find C:\h\w\AAFB0913\w\9D3208B9\e\JIT\HardwareIntrinsics\X86\Sse2\StoreAligned_r\StoreAligned_r.dll.rsp
Unhandled exception. System.BadImageFormatException: Could not load file or assembly 'ILCompiler.DependencyAnalysisFramework, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'. The module was expected to contain an assembly manifest.
File name: 'ILCompiler.DependencyAnalysisFramework, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null'
at ILCompiler.ReadyToRunCodegenCompilationBuilder.ToCompilation()
at ILCompiler.Program.RunSingleCompilation(Dictionary2 inFilePaths, InstructionSetSupport instructionSetSupport, String compositeRootPath, Dictionary2 unrootedInputFilePaths, HashSet`1 versionBubbleModulesHash, CompilerTypeSystemContext typeSystemContext)
at ILCompiler.Program.Run(String[] args)
at ILCompiler.Program.Main(String[] args)

Return code:      1
Raw output file:      C:\h\w\AAFB0913\w\9D3208B9\uploads\Reports\JIT.HardwareIntrinsics\X86\Sse2\StoreAligned_r\StoreAligned_r.output.txt
Raw output:
BEGIN EXECUTION
StoreAligned_r.dll
TestLibrary.dll
2 file(s) copied.
Response file: C:\h\w\AAFB0913\w\9D3208B9\e\JIT\HardwareIntrinsics\X86\Sse2\StoreAligned_r\StoreAligned_r.dll.rsp
C:\h\w\AAFB0913\w\9D3208B9\e\JIT\HardwareIntrinsics\X86\Sse2\StoreAligned_r\IL-CG2\StoreAligned_r.dll
-o:C:\h\w\AAFB0913\w\9D3208B9\e\JIT\HardwareIntrinsics\X86\Sse2\StoreAligned_r\StoreAligned_r.dll
--targetarch:x64
--verify-type-and-field-layout
--method-layout:random
-r:C:\h\w\AAFB0913\p\System..dll
-r:C:\h\w\AAFB0913\p\Microsoft..dll
-r:C:\h\w\AAFB0913\p\mscorlib.dll
-r:C:\h\w\AAFB0913\p\netstandard.dll
-O
" "dotnet" "C:\h\w\AAFB0913\p\crossgen2\crossgen2.dll" @"C:\h\w\AAFB0913\w\9D3208B9\e\JIT\HardwareIntrinsics\X86\Sse2\StoreAligned_r\StoreAligned_r.dll.rsp"   -r:C:\h\w\AAFB0913\w\9D3208B9\e\JIT\HardwareIntrinsics\X86\Sse2\StoreAligned_r\IL-CG2*.dll"
Crossgen2 failed with exitcode - -532462766
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\AAFB0913\p
C:\h\w\AAFB0913\w\9D3208B9\e\JIT\HardwareIntrinsics\X86\Sse2\StoreAligned_r\StoreAligned_r.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_HardwareIntrinsics._X86_Sse2_StoreAligned_r_StoreAligned_r_._X86_Sse2_StoreAligned_r_StoreAligned_r_cmd()
```

**Comment by tannergooding** [comment] 2022-03-04 18:39
Closing as dupe of https://github.com/dotnet/runtime/issues/65646

**Closed by tannergooding** 2022-03-04 18:39 UTC
Labels: os-windows, arch-x64, area-crossgen2-coreclr, untriaged
