### ISSUE TITLE
JsonObjectCreationHandling.Populate and IDictionary<,>

### ISSUE THREAD

**Issue by CheloXL** [dotnet/runtime#94676] opened 2023-11-13 18:00 UTC
### Description

A property of type IDictionary is not being filled in with data at deserialization, using the new `JsonObjectCreationHandling.Populate` option.

### Reproduction Steps

Have the following class:

```cs
public sealed class Vehicle
{
	private Dictionary<string, string>? _customData;

	public Vehicle(string plate)
	{
		Plate = plate;
	}

	public string Plate { get; }
	public IDictionary<string, string> CustomData
	{
		get { return _customData ??= new(StringComparer.OrdinalIgnoreCase); }
	}
}
```

The following test doesn't pass, and for what I understand, it should:
```cs
[Fact]
public void TestVehicle()
{
	var v = new Vehicle("123")
	{
		CustomData =
		{
			["v"] = "1"
		}
	};

	var def = new JsonSerializerOptions(JsonSerializerDefaults.Web)
	{
		PreferredObjectCreationHandling = JsonObjectCreationHandling.Populate,
		IgnoreReadOnlyProperties = false
	};

	var s = JsonSerializer.Serialize(v, def);
	var d = JsonSerializer.Deserialize<Vehicle>(s, def);
	d.Should().NotBeNull();
	d.CustomData["v"].Should().Be("1");
}
```

### Expected behavior

The test should pass.

### Actual behavior

The test doesn't pass because the dictionary is empty.

### Known Workarounds

Not making the property readonly and making the setter public (even with a private setter this doesn't works, so I'm assuming it is not even trying to populate data, but just creating a new Dictionary and assigning it to the property).

### Configuration

Latest .net 8 rc2, Windows 11x64.

**Comment by eiriktsarpalis** [comment] 2023-11-13 18:46
It's not related to the dictionary property se, this is because of a known issue with the handling of parameterized constructors. Changing your class to:
```C#
public sealed class Vehicle
{
    public required string Plate { get; init; }
    public IDictionary<string, string> CustomData { get; } = new Dictionary<string, string>();
}
```
Should make it work as expected.

Duplicate of https://github.com/dotnet/runtime/issues/92877.

**Closed by eiriktsarpalis** 2023-11-13 18:46 UTC
Labels: area-System.Text.Json, untriaged
