### ISSUE TITLE
Runtime error with system.text.json if a model includes action type for source generator

### ISSUE THREAD

**Issue by musictopia2** [dotnet/runtime#64871] opened 2022-02-06 13:25 UTC
### Description

I discovered that if a model being used for source generation has a type of Action, that causes a runtime error with the source generator even if I mark the attribute ignore.
Action should never even be considered for serializing anyways.

### Reproduction Steps

1.  Create Model
2.  Have a type of Action
3.  Inherit from JsonSerializerContext and mark attribute as JsonSerializable
4.  Build Solution.

### Expected behavior

I expect the project to build successfully and not even see anything having to do with action in the source generator.

### Actual behavior

The runtime error message was "Method name expected"
Also has lots of warnings.
If you want to see a screenshot of the warnings, I can do that as well.

### Known Workarounds

Not use the source generator (which means it uses reflection).

### Configuration

.net 6.

**Comment by martincostello** [comment] 2022-02-06 16:29
Looks like a dupe of #62354.

**Comment by layomia** [comment] 2022-03-02 18:58
> Looks like a dupe of https://github.com/dotnet/runtime/issues/62354.

Yup. Fixed for 6.0.2 in https://github.com/dotnet/runtime/pull/63514.

**Closed by layomia** 2022-03-02 18:58 UTC
Labels: area-System.Text.Json, untriaged
