### ISSUE TITLE
System.Text.Json should support IgnoreDataMemberAttribute or equivalent

### ISSUE THREAD

**Issue by edwinloubser** [dotnet/runtime#47514] opened 2021-01-27 08:57 UTC
Currently the only supported way to ignore individual properties is by decorating properties with the JsonIgnore attribute. But this means that libraries needs to take a dependency on System.Text.Json which is undesirable. I wish for my libraries to indicate which properties need not be serialized in a serialization library agnostic way. IgnoreDataMemberAttribute seems to be supported by most (all?) serialization libraries and it seems odd that System.Text.Json does not.

**Comment by layomia** [comment] 2021-01-27 17:29
Duplicate of https://github.com/dotnet/runtime/issues/29975.

**Closed by layomia** 2021-01-27 17:29 UTC
Labels: area-System.Text.Json, untriaged
