### ISSUE TITLE
QUIC: On idle connection timeout, errors thrown for streams before connection

### ISSUE THREAD

**Issue by JamesNK** [dotnet/runtime#73144] opened 2022-08-01 07:09 UTC
### Description

An HTTP/3 connection has at least two control streams. If those control streams are closed, then the connection should be aborted with `H3_CLOSED_CRITICAL_STREAM` error code.

I noticed that [when a connection is closed because it exceeded the idle timeout](https://github.com/dotnet/runtime/issues/73141), QuicException is thrown on streams before the connection (i.e. `QuicConnection.AcceptInboundStreamAsync`). Because, from Kestrel's perspective, the streams are being closed before the connection, Kestrel aborts the connection with `H3_CLOSED_CRITICAL_STREAM`. This causes additional logs to be written that could confuse someone about why the connection is closing (is it from an idle timeout or critical stream being closed?)

This is similar to [[HTTP/3] Client closing control stream before closing connection #57021](https://github.com/dotnet/runtime/issues/57021), except idle timeout instead of client initialed close.

### Reproduction Steps

See instructions at https://github.com/dotnet/runtime/issues/73141

### Expected behavior

Error from `AcceptInboundStreamAsync` is reported first. This will allow the connection to know it's closing and Kestrel can ignore exceptions from control streams.

### Actual behavior

Control streams error first.

### Other information

I'm not sure whether this change alone fixes the Kestrel issue or if it's the correct fix.

The logs consistently show `AcceptInboundStreamAsync` throwing last, but how are these multiple errors scheduled? Is it simultaneously? Would there be race conditions when handling them?

Perhaps instead Kestrel should assume that an idle timeout on a control stream means the connection has idle timeout as well, and aborting the connection with `H3_CLOSED_CRITICAL_STREAM` is unnecessary.

**Comment by rzikm** [comment] 2022-08-02 12:01
I was not able to reproduce this. Also, from looking at our and MsQuic source code (https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicConnection.cs#L454 and https://github.com/microsoft/msquic/blob/main/src/core/connection.c#L1487), the order of operation seems to be:
- QuicConnIndicateShutdownBegin -> QuicConnection.HandleEventShutdownInitiatedByTransport -> set exception to _acceptQueue (which services AcceptInboundStreamAsync)
- QuicStreamSetShutdown -> immediate shutdown of individual streams -> setting exceptions on QuicStream instances
- some time later, QuicConnection shutdown finishes and we free the resources.

Is it possible that this is just a race between which thread/Task gets to CPU first? all continuations are running asynchronously from MsQuic thread.

**Comment by karelz** [comment] 2022-08-04 16:16
Triage: We believe that all behaves correctly, except that clients have to be resilient to different timing/race conditions -- for example interpret `QuicErrorCode` on exception and check the reason for closing the stream.

@JamesNK what do you think? If you agree, we should close the issue. Thanks!

**Comment by JamesNK** [comment] 2022-08-10 05:48
I'll take another look.

I think Kestrel might need to do a delayed reaction to control streams being closed, i.e. when a control stream is closed, instead of immediately aborting the connection, instead set a flag on the connection, and wait for the next server tick (1 second) to see if the connection is still open and then start the abort.

What does SocketsHttpHandler do in this situation? (the server killing a control stream/connection)

**Comment by rzikm** [comment] 2022-08-10 08:23
> What does SocketsHttpHandler do in this situation? (the server killing a control stream/connection)

So far, we did not really try to detect it 😅, I put up https://github.com/dotnet/runtime/pull/73680 to address that.

I really think that Kestrel should check the `QuicError` property on the exception and tear down the connection with `H3_CLOSED_CRITICAL_STREAM` only if the error is `StreamAborted`

**Comment by karelz** [comment] 2022-08-22 09:27
@JamesNK any update on this? We should make a call if it is something critical for 7.0 at least.

**Closed** 2022-08-22 12:01 UTC
Labels: untriaged, area-System.Net.Quic
