### ISSUE TITLE
Failure test: JIT\\jit64\\opt\\cse\\hugeexpr1\\hugeexpr1.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#56198] opened 2021-07-23 03:08 UTC
Run: [runtime-coreclr r2r 20210721.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1252451&view=ms.vss-test-web.build-test-results-tab&runId=37178270&paneView=debug&resultId=101705)

Failed test:
```
R2R windows x86 Checked no_tiered_compilation @ Windows.10.Amd64.Open

- JIT\\jit64\\opt\\cse\\hugeexpr1\\hugeexpr1.cmd

```
**Error message:**
```
Could Not Find C:\h\w\B2A00A00\w\AB40097C\e\JIT\jit64\opt\cse\hugeexpr1\hugeexpr1.dll.rsp
Out of memory.

Return code:      1
Raw output file:      C:\h\w\B2A00A00\w\AB40097C\uploads\Reports\JIT.jit64\opt\cse\hugeexpr1\hugeexpr1.output.txt
Raw output:
BEGIN EXECUTION
hugeexpr1.dll
1 file(s) copied.
Response file: C:\h\w\B2A00A00\w\AB40097C\e\JIT\jit64\opt\cse\hugeexpr1\hugeexpr1.dll.rsp
C:\h\w\B2A00A00\w\AB40097C\e\JIT\jit64\opt\cse\hugeexpr1\IL-CG2\hugeexpr1.dll
-o:C:\h\w\B2A00A00\w\AB40097C\e\JIT\jit64\opt\cse\hugeexpr1\hugeexpr1.dll
--targetarch:x86
--verify-type-and-field-layout
-r:C:\h\w\B2A00A00\p\System..dll
-r:C:\h\w\B2A00A00\p\Microsoft..dll
-r:C:\h\w\B2A00A00\p\mscorlib.dll
-r:C:\h\w\B2A00A00\p\netstandard.dll
-O
" "dotnet" "C:\h\w\B2A00A00\p\crossgen2\crossgen2.dll" @"C:\h\w\B2A00A00\w\AB40097C\e\JIT\jit64\opt\cse\hugeexpr1\hugeexpr1.dll.rsp"   -r:C:\h\w\B2A00A00\w\AB40097C\e\JIT\jit64\opt\cse\hugeexpr1\IL-CG2*.dll"
Emitting R2R PE file: C:\h\w\B2A00A00\w\AB40097C\e\JIT\jit64\opt\cse\hugeexpr1\hugeexpr1.dll
Crossgen2 failed with exitcode - -532462766
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\B2A00A00\p
C:\h\w\B2A00A00\w\AB40097C\e\JIT\jit64\opt\cse\hugeexpr1\hugeexpr1.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_jit64._opt_cse_hugeexpr1_hugeexpr1_._opt_cse_hugeexpr1_hugeexpr1_cmd() in JIT.jit64.XUnitWrapper.dll:token 0x60001c6+0x284
```

**Comment by davidwrighton** [comment] 2021-07-27 01:38
This was caused by heap fragmentation in both the managed and native heaps. This particular failure could be fixed by converting crossgen2 to use the managed gc heap for the JitHost allocator in crossgen2 on 32bit processes, but that's a bit risky. I'd like to see if this repro's more often before I would fix this. Please re-open if this happens again.

**Closed by davidwrighton** 2021-07-27 01:38 UTC
Labels: arch-x86, area-crossgen2-coreclr, os-windows
