### ISSUE TITLE
Deadlock in SocketAsyncContext.Unix.cs

### ISSUE THREAD

**Issue by shaan1337** [dotnet/runtime#31570] opened 2019-11-26 13:12 UTC
While running XUnit tests on CI (Azure Pipelines) they would almost always hang on macos (we tried both 10.13 and 10.14 on azure pipelines) but never on linux and windows. Moreover the tests would only hang in `RELEASE` builds of macos but never (as far as I remember) on `DEBUG` builds. We've tested on both .net core 3.0 and .net core 3.1-preview 3.

After attaching lldb to the process and getting a thread dump, it appears that there's a deadlock in SocketAsyncContext.Unix.cs (full logs attached for 2 instances):
```
000070000EF32550 0000000111b78efe (MethodDesc 0000000111cf2ee0 + 0x6e System.Net.Sockets.SocketAsyncContext+AsyncOperation.TryCancel()), calling (MethodDesc 000000011191bd68 + 0 System.Threading.SpinWait.SpinOnce())
000070000EF32580 0000000111b7a7bd (MethodDesc 0000000111cf3128 + 0x3d System.Net.Sockets.SocketAsyncContext+OperationQueue`1[[System.__Canon, System.Private.CoreLib]].StopAndAbort(System.Net.Sockets.SocketAsyncContext)), calling (MethodDesc 0000000111cf2ee0 + 0 System.Net.Sockets.SocketAsyncContext+AsyncOperation.TryCancel())
000070000EF325B0 0000000111b76eec (MethodDesc 0000000111cf2410 + 0x3c System.Net.Sockets.SocketAsyncContext.Close()), calling (MethodDesc 0000000111cf3128 + 0 System.Net.Sockets.SocketAsyncContext+OperationQueue`1[[System.__Canon, System.Private.CoreLib]].StopAndAbort(System.Net.Sockets.SocketAsyncContext))
000070000EF325E0 0000000111b4f0ea (MethodDesc 0000000111bc5ec0 + 0xca System.Net.Sockets.SafeSocketHandle.ReleaseHandle()), calling (MethodDesc 0000000111cf2410 + 0 System.Net.Sockets.SocketAsyncContext.Close())
000070000EF32600 000000011b4ea729 (MethodDesc 00000001113d1dd8 + 0xa9 System.Runtime.InteropServices.SafeHandle.InternalRelease(Boolean))
000070000EF32640 000000011b4ed8ca (MethodDesc 000000011140faa0 + 0x1a System.StubHelpers.StubHelpers.SafeHandleRelease(System.Runtime.InteropServices.SafeHandle)), calling (MethodDesc 00000001113d1dd8 + 0 System.Runtime.InteropServices.SafeHandle.InternalRelease(Boolean))
000070000EF32660 000000011137249d (MethodDesc 0000000111d93640 + 0xcd ILStubClass.IL_STUB_PInvoke(System.Runtime.InteropServices.SafeHandle, MessageHeader*, System.Net.Sockets.SocketFlags, Int64*)), calling (MethodDesc 000000011140faa0 + 0 System.StubHelpers.StubHelpers.SafeHandleRelease(System.Runtime.InteropServices.SafeHandle))
000070000EF326A0 000000011137246b (MethodDesc 0000000111d93640 + 0x9b ILStubClass.IL_STUB_PInvoke(System.Runtime.InteropServices.SafeHandle, MessageHeader*, System.Net.Sockets.SocketFlags, Int64*))
000070000EF32700 0000000111b50d7d (MethodDesc 0000000111bc6428 + 0x10d System.Net.Sockets.SocketPal.Receive(System.Net.Sockets.SafeSocketHandle, System.Net.Sockets.SocketFlags, System.Span`1<Byte>, Byte[], Int32 ByRef, System.Net.Sockets.SocketFlags ByRef, Error ByRef)), calling 0000000111367e68 (stub for Interop+Sys.ReceiveMessage(System.Runtime.InteropServices.SafeHandle, MessageHeader*, System.Net.Sockets.SocketFlags, Int64*))
000070000EF327D0 0000000111b50b25 (MethodDesc 0000000111bc6548 + 0x65 System.Net.Sockets.SocketPal.TryCompleteReceiveFrom(System.Net.Sockets.SafeSocketHandle, System.Span`1<Byte>, System.Collections.Generic.IList`1<System.ArraySegment`1<Byte>>, System.Net.Sockets.SocketFlags, Byte[], Int32 ByRef, Int32 ByRef, System.Net.Sockets.SocketFlags ByRef, System.Net.Sockets.SocketError ByRef)), calling (MethodDesc 0000000111bc6428 + 0 System.Net.Sockets.SocketPal.Receive(System.Net.Sockets.SafeSocketHandle, System.Net.Sockets.SocketFlags, System.Span`1<Byte>, Byte[], Int32 ByRef, System.Net.Sockets.SocketFlags ByRef, Error ByRef))
000070000EF327F0 000000010255e36d libcoreclr.dylib!ReleaseSemaphore + 0x3d, calling libcoreclr.dylib!CorUnix::InternalReleaseSemaphore(CorUnix::CPalThread*, void*, int, int*)
000070000EF32850 0000000111b5116f (MethodDesc 0000000111d93870 + 0xaf System.Net.Sockets.SocketAsyncContext+BufferMemoryReceiveOperation.DoTryComplete(System.Net.Sockets.SocketAsyncContext)), calling (MethodDesc 0000000111bc6548 + 0 System.Net.Sockets.SocketPal.TryCompleteReceiveFrom(System.Net.Sockets.SafeSocketHandle, System.Span`1<Byte>, System.Collections.Generic.IList`1<System.ArraySegment`1<Byte>>, System.Net.Sockets.SocketFlags, Byte[], Int32 ByRef, Int32 ByRef, System.Net.Sockets.SocketFlags ByRef, System.Net.Sockets.SocketError ByRef))
000070000EF328A0 0000000111b7a44e (MethodDesc 0000000111cf3108 + 0xae System.Net.Sockets.SocketAsyncContext+OperationQueue`1[[System.__Canon, System.Private.CoreLib]].ProcessQueuedOperation(System.__Canon)), calling 00000001109eb0a0
000070000EF32920 0000000111b7a35f (MethodDesc 0000000111cf30f8 + 0x2f System.Net.Sockets.SocketAsyncContext+OperationQueue`1[[System.__Canon, System.Private.CoreLib]].ProcessAsyncOperation(System.__Canon)), calling 000000011136b0b0 (stub for System.Net.Sockets.SocketAsyncContext+OperationQueue`1[[System.__Canon, System.Private.CoreLib]].ProcessQueuedOperation(System.__Canon))
000070000EF32950 0000000111b510ab (MethodDesc 0000000111cf82d0 + 0x2b System.Net.Sockets.SocketAsyncContext+ReadOperation.System.Threading.IThreadPoolWorkItem.Execute()), calling 000000011136b0a8 (stub for System.Net.Sockets.SocketAsyncContext+OperationQueue`1[[System.__Canon, System.Private.CoreLib]].ProcessAsyncOperation(System.__Canon))
000070000EF32960 000000011b4ef096 (MethodDesc 000000011198f378 + 0x1f6 System.Threading.ThreadPoolWorkQueue.Dispatch())
```

The deadlock seems to happen in this way:
1. an `AsyncOperation` is queued, for instance `BufferMemoryReceiveOperation` as seen in the above stack trace
2. the operation starts being executed on the thread pool
3. after a series of calls, `SocketPal.Receive` makes a call to `Interop.Sys.ReceiveMessage` which calls some unmanaged OS-specific socket code. Eventually the socket handle is released in the unmanaged code which triggers `SocketAsyncContext.Close()`
5. `SocketAsyncContext.Close()` attempts to call `TryCancel()` which waits indefinitely for all async operations to complete: https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs#L212
6. `BufferMemoryReceiveOperation` is itself an async operation, so it's in effect waiting for itself to complete. Deadlock.

It appears that the reason it would not hang in DEBUG builds is because of this line: https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs#L659 which is called here:
https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs#L1096

I've attached two instances of the problem occurring but we can reproduce the problem consistently if any additional information is required:
[macos_deadlock.zip](https://github.com/dotnet/corefx/files/3891980/macos_deadlock.zip)

**Comment by fehmianac** [comment] 2020-02-11 08:06
Hi All,

We also same issue in Production stage.

Situation like that.
We are doing "fail over" our MSSQL database. Some time we had dead lock thread after fail over. When we analyze dump we are seeing some dead lock in "system.net.sockets.socketpal.receive" method.

Is there any work around about this case ?

OS: Ubuntu 18.04 also Docker
Runtime: 3.1.100
ORM: Dapper
Data Client: System.Data.SqlClient 4.80
RPM: About 10K

**Comment by tmds** [comment] 2020-02-11 08:18
@fehmianac so far the issue was only reported against macOS.

From https://github.com/EventStore/EventStore/commit/945e7612c5b7a131150b867a1f1d912e9776e1be it looks like calling `Socket.Close` without a timeout is a workaround. I haven't looked into understanding why that is so.

Can you share the stacktrace from the dump?
Do you know what 'owns' the Socket that is being used in the receive? Then we can see if that `Socket` is also getting closed with a timeout.

**Comment by fehmianac** [comment] 2020-02-11 08:38
Here is our stacktrace.

<img width="972" alt="threads" src="https://user-images.githubusercontent.com/9279620/74221293-d6d6f700-4cc2-11ea-91e6-49fa0d460d29.png">

<img width="1675" alt="stacks" src="https://user-images.githubusercontent.com/9279620/74221295-d9d1e780-4cc2-11ea-8fee-28398684c854.png">

**Comment by tmds** [comment] 2020-02-11 08:58
@fehmianac because there is no `SafeSocketHandle.ReleaseHandle` in the stack, it is a different issue. Can you create a separate issue for it?

**Comment by fehmianac** [comment] 2020-02-11 09:04
Thank you I have created new  [issue](https://github.com/dotnet/runtime/issues/32103) about that case.

**Comment by antonfirsov** [comment] 2020-07-31 16:54
I tried to reproduce this using the code in #381. Did run the tests on several OSX versions (`10.13.4`, `10.14.2` and `10.15.6`) with both 3.1 and current master, and had no success.

I think the [test code in the PR](https://github.com/shaan1337/runtime/blob/0bc0349681fb5c6f5b1dcb480d01660ef2da670a/src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs#L939-L974) is not sufficient to trigger the behavior reported in the opening comment, since it has only one receive call which will be executed synchronously and no `BufferMemoryReceiveOperation` will be queued. The [exception sometimes experienced in that test](https://github.com/dotnet/runtime/pull/381#issuecomment-574018519) seems to come from `CreateConnectedSocketPair()` and is unrelated to the suspected deadlock behavior.

I tried a [more advanced](https://gist.github.com/antonfirsov/b5deb76ebdc342f6f085206632c47c69) approach in order to enforce the async execution, but got no deadlock on `10.14.2`, the only machine available for me for interactive work.

I'm not sure if it's possible to reproduce the issue by disposing the socket manually, but if yes, the problem should not be specific to macOS and should also repro on all Unixes.

I'm afraid we are missing other important circumstances that are also necessary for the deadlock to occur. The issue might be rooted in some unknown native bahivor occuring only on mac. From the opening comment:

> 3. after a series of calls, SocketPal.Receive makes a call to Interop.Sys.ReceiveMessage which calls some unmanaged OS-specific socket code. **Eventually the socket handle is released in the unmanaged code** which triggers SocketAsyncContext.Close()

Do we know how is it possible for a socket close to be triggered from (the same?) unmanaged code while a `recv` is ongoing?

I don't think it would be wise to PR any changes without making sure we have a repro. @geoffkizer @tmds do you have any ideas on what else could I try [in my repro code](https://gist.github.com/antonfirsov/b5deb76ebdc342f6f085206632c47c69)? Or what can **actually** go wrong in the quoted point 3? If no, I suggest to push this to Future.

**Comment by antonfirsov** [comment] 2020-08-03 03:57
Ok, looks like not all findings of my previous comment are true:
- On mac, #381 repro code is sufficient to enqueue `BufferMemoryReceiveOperation`
- It reproduces on AZP with 3.1.302, [regardless of the OS version](https://dev.azure.com/anfirszo/system-net-sockets-deadlock-bug-42718/_build/results?buildId=7). (But didn't repro locally or on Helix for me.)

It *seems to be* gone with newest preview of 5.0:
https://dev.azure.com/anfirszo/system-net-sockets-deadlock-bug-42718/_build/results?buildId=16

**Comment by antonfirsov** [comment] 2020-08-03 15:04
I had [10 successful runs in a row](https://dev.azure.com/anfirszo/system-net-sockets-deadlock-bug-42718/_build?definitionId=1&_a=summary) with 5.0. I also observed that tests are running significantly faster with 5.0, than with 3.1 (12 instead of 30+ seconds).

I think it's safe to assume that the issue is gone -- probably as a side effect of `SocketAsyncEngine` optimizations in 5.0. Nevertheless, it might worth an investigation to get a deeper understanding on: (1) Why does the issue happen on certain macs and (usually) not others? (2) why did it disappear with the changes in 5.0?

This doesn't seem high priority for me however, so I suggest to push post-5.0.

Details:
- The yml that reproduces the issue on 3.1 (thanks to @shaan1337 for updating it): 
https://github.com/shaan1337/system-net-sockets-deadlock-bug-42718/blob/macos-10.14-dotnet-3.1.302/ci.yml
- The 5.0 variant, which succeeds consistently:
https://github.com/antonfirsov/system-net-sockets-deadlock-bug-42718/blob/macos-10.14-net5/ci.yml

**Comment by antonfirsov** [comment] 2020-08-04 22:26
I'm closing this, since the issue is likely gone 5.0.

@shaan1337 feel free to reopen if you can repro it with our latest preview.

**Closed by antonfirsov** 2020-08-04 22:26 UTC
Labels: area-System.Net.Sockets, bug, os-mac-os-x
