### ISSUE TITLE
Bug .net 7 polymorphic deserialization

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#90213] opened 2023-08-09 08:15 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Bug-net-7-polymorphic-deserialization/10397558)._

---
I've create a class and decorated it with JsonDerivedType and JsonPolymophic attributes. The deserialisation at modelbinding time works fine. I serialize this class again in code and store that string in the DB for later use in a special use case.

At 'later use' time I retrieve that saved json, deserialize the object and it fails  with the error 'The metadata property is either not supported by the type or is not the first property in the deserialized JSON object'.

Removing the JsonPolymophic attribute from the class, hence using the default convention $type, and all works fine.

```
    //[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
    [JsonDerivedType(typeof(SfbCondition), typeDiscriminator: 10)]
    [JsonDerivedType(typeof(SfbConsent), typeDiscriminator: 20)]
    public class SurveyFlowBlock 
    {
        [JsonPropertyName("type")] 
        public SurveyFlowBlockTypes Type { get; set; } 
    }
```

---
#### Feedback Bot on 6/25/2023, 04:59 AM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by eiriktsarpalis** [comment] 2023-08-09 08:18
Duplicate of https://github.com/dotnet/runtime/issues/72170

**Closed by eiriktsarpalis** 2023-08-09 08:18 UTC
Labels: area-System.Text.Json, untriaged
