### ISSUE TITLE
System.Net.Quic QuicListener sets QuicAddr.Family incorrectly for the requested IPAddress type

### ISSUE THREAD

**Issue by StephenMLucas** [dotnet/runtime#80248] opened 2023-01-05 17:57 UTC
### Description

In the underlying MSQuic implemention QUIC_ADDRESS_FAMILY_UNSPEC is defined as 0. This means it is both the default and also the only value that QuicListener attempts to set based on the IPAddress type. 

This means that in all cases the connection is created for both IPv4 and IPv6 clients, which leads to misleading error messages from the underlying MSQuic library when an IPv6 client attempts to connect to an IPv4 listener.

### Reproduction Steps

1. Create a QuicListener using an IPv4 IPAddress e.g.
```
`var localIPAddress = Dns.GetHostEntry(Dns.GetHostName()).AddressList.First(x => x.AddressFamily == System.Net.Sockets.AddressFamily.InterNetwork);

 var listenerOptions = new QuicListenerOptions()
 {
                ListenEndPoint = new IPEndPoint(localIPAddress, 4567),` 
```
2. Attempt to connect from a client using an IPv6 address for the same device e.g. when using MSQuic directly and calling MSQuic->ConnectionStart using the DNS name of the device which is resolved to an IPv6 address

### Expected behavior

The client should fail to establish the connection with an appropriate error about the endpoint.

### Actual behavior

The client establishes the connection on the IPv6 endpoint but then fails to find the matching listener. This then results in an error code of Status=0x80410007 : The QUIC connection failed to negotiate a compatible ALPN. ErrorCode=376. 

### Known Workarounds

This issue can be avoided by correctly matching the client and server IPAddresses being used, or by the client knowing what the returned error code actually means in context.

### Configuration

.NET 7.0.1 
Windows 11 X64

**Comment by ManickaP** [comment] 2023-01-09 15:05
@nibanks any thoughts on this?

**Comment by nibanks** [comment] 2023-01-09 15:23
Looks to be a duplicate of https://github.com/microsoft/msquic/issues/2704.

**Comment by StephenMLucas** [comment] 2023-01-09 17:19
Agreed this is related to that thread but, as that bug thread concluded, MsQuic is objectively doing the correct thing (although a better error code would be nice) and the issue here is how System.Net.Quic is using those options- the .NET runtime code is 

`        if (options.ListenEndPoint.Address.Equals(IPAddress.IPv6Any))
        {
            // For IPv6Any, MsQuic would listen only for IPv6 connections. This would make it impossible
            // to connect the listener by using the IPv4 address (which could have been e.g. resolved by DNS).
            // Using the Unspecified family makes MsQuic handle connections from all IP addresses.
            address.Family = QUIC_ADDRESS_FAMILY_UNSPEC;
        }` 

where address.Family is either set to default (0) or QUIC_ADDRESS_FAMILY_UNSPEC (also 0). So either that clause is redundant or the logic of that section isn't quite correct since it's not ensuring that the address.Family being listened to matches the type of IP Address being passed in for the listener. Despite what the comment says it's still impossible to connect with the 'other' type of IP address to the one the listener is bound to, it just fails later in the handshake process with an ALPN negotiation error.

**Comment by StephenMLucas** [comment] 2023-01-09 17:37
It's also possible this represents an API design question for System.Net.Quic since the underlying MSQuic API also allows DNS names to be passed through (in which case QUIC_ADDRESS_FAMILY_UNSPEC works as expected) whilst System.Net.Quic only allows providing an IPEndPoint which has to be either IPv4 or IPv6. 
So it seems like like using QUIC_ADDRESS_FAMILY_UNSPEC is always be the wrong choice for the current .NET API design, but could be used if DnsEndPoint was also supported?

**Comment by rzikm** [comment] 2023-01-10 08:43
> where address.Family is either set to default (0) or QUIC_ADDRESS_FAMILY_UNSPEC (also 0). So either that clause is redundant or the logic of that section isn't quite correct since it's not ensuring that the address.Family being listened to matches the type of IP Address being passed in for the listener.

The address.Family is being set by other means. Since the struct layout is the same as the one used in native socket functions, we decided to reuse the same code already used in System.Net.Sockets. The address family part is set as part of the ToQuicAddr call.

https://github.com/dotnet/runtime/blob/e1deaebb0c02103797fcc822218223df1ea59f18/src/libraries/System.Net.Quic/src/System/Net/Quic/Internal/MsQuicHelpers.cs#L45

If ListenEndPoint is not IPv6Any, then the address family is set as expected.

> Despite what the comment says it's still impossible to connect with the 'other' type of IP address to the one the listener is bound to, it just fails later in the handshake process with an ALPN negotiation error.

It does not fail "later" in the handshake, when MsQuic cannot match an incoming Initial packet to a connection to an existing listener (with the right ALPN + IP Address), it will reply with ALPN negotiation failure. Here I agree that the error is misleading, and would expect something like CONNECTION_REFUSED when no listener is found, and ALPN negotiation error only when *some* listener is found, but has incompatible ALPN settings.

The workaround for IPv6Any you mention was added as a quick (and possibly a bit dirty) fix to https://github.com/dotnet/runtime/issues/67442. Otherwise, ASP.NET users would run into the very same issue when listening for HTTP/3 connections. I think we should just go and mimic what sockets have: an explicit option whether the Listener should be "dual stack" or not (which would require pre-existing support in MsQuic). Thoughts, @nibanks?.

**Comment by nibanks** [comment] 2023-01-10 13:12
> an explicit option whether the Listener should be "dual stack" or not (which would require pre-existing support in MsQuic). Thoughts, @nibanks?.

MsQuic already has the explicit option: listing on an "unspecified" address:

- Using IPv6 wildcard address indicates any IPv6 address
- Using IPv4 wildcard address indicates any IPv4 address
- Using unspecified wildcard address indicates both (dual stack)

I'm unsure of what you're asking for beyond this.

**Comment by ManickaP** [comment] 2023-01-10 16:26
> the underlying MSQuic API also allows DNS host names to be passed through

For a client (outgoing) connection we accept [`DnsEndPoint`](https://learn.microsoft.com/en-us/dotnet/api/system.net.quic.quicclientconnectionoptions.remoteendpoint?view=net-7.0#system-net-quic-quicclientconnectionoptions-remoteendpoint). For listener we accept only [`IPEndPoint`](https://learn.microsoft.com/en-us/dotnet/api/system.net.quic.quiclisteneroptions.listenendpoint?view=net-7.0#system-net-quic-quiclisteneroptions-listenendpoint) as msquic accepts [`QUIC_ADDR`](https://github.com/microsoft/msquic/blob/bebc669abcc9c11a01c40727f92b20bdc23f0c74/src/inc/msquic_posix.h#L157-L161), which is just an alias for `sockaddr`.

And as @rzikm already mentioned, we do pass along `Family` from the given `IPEndPoint`, it's just hidden in the shared code with sockets:
https://github.com/dotnet/runtime/blob/d4907cf8fb4800b4ec96d07cd93be58eb479a2e6/src/libraries/Common/src/System/Net/SocketAddress.cs#L100-L100

So, the only thing here is that the error code/message is confusing and discerning between ALPN mismatch and IP mismatch might be helpful in debugging issues like this? Or anything else is amiss?

**Comment by StephenMLucas** [comment] 2023-01-10 17:40
@ManickaP - I can't say for sure, but it seems like a potential issue beyond just error clarity that System.Net.Quic is asking MsQuic to accept dual stack connections when I've explicitly asked it to listen on an IPv4 endpoint. 

I missed the other code setting AddressFamily, but observationally this isn't working as expected in .NET 7.0.1 since MSQuic is  listening for the "unspecified" address family when I copy the sample code from https://devblogs.microsoft.com/dotnet/dotnet-7-networking-improvements/ . That sample code works in isolation because both .NET listener and client are using IPv4 addresses by default, but if you attempt to connect using an IPv6 address from the client (e.g. using the MSQuic sample.c example code with a DNS name) then the problem becomes apparent.

**Comment by rzikm** [comment] 2023-01-10 17:56
> > an explicit option whether the Listener should be "dual stack" or not (which would require pre-existing support in MsQuic). Thoughts, @nibanks?.
> 
> MsQuic already has the explicit option: listing on an "unspecified" address:
> 
> * Using IPv6 wildcard address indicates any IPv6 address
> * Using IPv4 wildcard address indicates any IPv4 address
> * Using unspecified wildcard address indicates both (dual stack)
> 
> I'm unsure of what you're asking for beyond this.

Is it possible to use the Unspecified family to make MsQuic listen on, lets say 172.22.224.1 (device local address on eth0) + its IPv6 mapping? Similar question for localhost/loopback addresses. Until now I assumed the Unspecified work only as "Listen to everything"

**Comment by nibanks** [comment] 2023-01-10 18:02
When you use the unspecified family, there is no way to represent an address of any value, since those are family specific. So all unspecified family addresses are wildcard addresses.

**Comment by ManickaP** [comment] 2023-01-10 18:07
> then the problem becomes apparent.

What exact behavior do you expect? I'm trying to understand where the problem exactly is.

**Comment by StephenMLucas** [comment] 2023-01-10 18:51
> What exact behavior do you expect? I'm trying to understand where the problem exactly is.

Given a request to listen on an IPv4 Address I'm expecting the library to *not* also be accepting incoming IPv6 connections that don't match the listener. And if I'm listening on IPv6 then it shouldn't be accepting IPv4 connections. If dual stack listening is the desired behavior that should be an explicit user choice in the listener configuration, although that would require a way to specify a wildcard listener address. As @nibanks noted those user choices are already explicit in the MsQuic API but it doesn't seem like that user intent can be reflected through the current System.Net.Quic API.

I could be way off base here, I'm not a networking expert and am happy to be corrected, but having the .NET API opening up more server endpoints then the user expects seems potentially problematic.

**Comment by ManickaP** [comment] 2023-01-11 10:13
> Given a request to listen on an IPv4 Address I'm expecting the library to not also be accepting incoming IPv6 connections that don't match the listener. And if I'm listening on IPv6 then it shouldn't be accepting IPv4 connections. 

@nibanks We're passing in IP address with a family specified. Is there something else we should do? Or this this expected behavior of msquic?

**Comment by nibanks** [comment] 2023-01-11 11:17
No, if you're specifying a specific address with a family you won't get an accept for anything else. I've never seen an issue to the contrary.

**Comment by ManickaP** [comment] 2023-01-11 12:22
@StephenMLucas as far as I understand it, there's nothing System.Net.Quic can do. If you still think there's an issue, we'll need exact code to reproduce it, including description of faulty behavior and what exact behavior you expect. You might even try to reduce it to plain msquic usage (without the .NET layer) and see where particular issue lies.

**Comment by StephenMLucas** [comment] 2023-01-11 19:06
@ManickaP - what I'm seeing is that System.Net.Quic 7.0.1 is *not* setting the specific address family correctly when it calls down to MsQuic - when I provide an IPv4 listener address it sets it to QUIC_ADDRESS_FAMILY_UNSPEC. I'll debug again to be 100% certain and provide the complete repro case.

**Comment by wfurt** [comment] 2023-01-11 20:03
Maybe post small complete repro @StephenMLucas? That is typically fastest way how to get some good insight.

**Comment by StephenMLucas** [comment] 2023-01-11 20:06
@ManickaP - Stepping through it does look like System.Net.Quic is in fact setting the IPv4 family correctly in the QuicAddr (0x2) but it doesn't seem to be reflected at the MSQuic level so maybe this is an interop bug? 

Here's the minimal repro case; [QuicRepro.zip](https://github.com/dotnet/runtime/files/10395539/QuicRepro.zip)

You'll need to swap in the certificate name for your test machine into the QuicServer/Program.cs:21 

Run QuicServer.exe and then QuicClient.exe on the same machine. The output from QuicClient should be;
`Unhandled exception. System.Security.Authentication.AuthenticationException: Application layer protocol negotiation error was encountered.
   at System.Net.Quic.QuicConnection.HandleEventShutdownInitiatedByTransport(_SHUTDOWN_INITIATED_BY_TRANSPORT_e__Struct& data)
   at System.Net.Quic.QuicConnection.HandleConnectionEvent(QUIC_CONNECTION_EVENT& connectionEvent)
   at System.Net.Quic.QuicConnection.NativeCallback(QUIC_HANDLE* connection, Void* context, QUIC_CONNECTION_EVENT* connectionEvent)`

Follow the instructions at [](https://github.com/microsoft/msquic/blob/main/docs/Diagnostics.md) to capture a trace gives the quicrepro.txt included in the zip. The relevant parts are;
`[4]9890.9C58::2023/01/11-11:40:17.859191400 [Microsoft-Quic][ lib][000001B5020E0A30] Worker start
[2]9890.3EA0::2023/01/11-11:40:17.860370000 [Metadata]Metadata: TraceEventInfo, Provider=Microsoft-Quic
[2]9890.3EA0::2023/01/11-11:40:17.860370000 [Microsoft-Quic][bind][0x1B5020E9D60] Created, Udp=0x1B5020EA690 LocalAddr=[::]:4567 RemoteAddr=0x00000000000000000000000000000000000000000000000000000000
[2]9890.3EA0::2023/01/11-11:40:17.860375700 [Microsoft-Quic][ lib] Now in use.
[2]9890.3EA0::2023/01/11-11:40:17.860396400 [Metadata]Metadata: TraceEventInfo, Provider=Microsoft-Quic
[2]9890.3EA0::2023/01/11-11:40:17.860396400 [Microsoft-Quic][list][0x1B5020E0D60] Started, Binding=0x1B5020E9D60, LocalAddr=192.168.0.10:4567, ALPN=0x0673616D706C65`

and later
`[5]38B4.7D68::2023/01/11-11:40:21.974892000 [Metadata]Metadata: TraceEventInfo, Provider=Microsoft-Quic
[5]38B4.7D68::2023/01/11-11:40:21.974892000 [Microsoft-Quic][conn][0x24482224CF0] New Remote IP: [fe80::f928:415:de1c:4d41%218103808]:4567
[5]38B4.7D68::2023/01/11-11:40:21.974923100 [Microsoft-Quic][data][0x24482226990] Created, local=0x, remote=[fe80::f928:415:de1c:4d41%218103808]:4567
[5]38B4.7D68::2023/01/11-11:40:21.975462900 [Microsoft-Quic][bind][0x24482226060] Created, Udp=0x24482226990 LocalAddr=[fe80::f928:415:de1c:4d41%218103808]:57526 RemoteAddr=[fe80::f928:415:de1c:4d41%218103808]:4567
[5]38B4.7D68::2023/01/11-11:40:21.975466200 [Microsoft-Quic][ lib] Now in use.`
followed by
`[4]9890.9E18::2023/01/11-11:40:21.977583100 [Metadata]Metadata: TraceEventInfo, Provider=Microsoft-Quic
[4]9890.9E18::2023/01/11-11:40:21.977583100 [Microsoft-Quic][conn][0x1B5020EAE30] No Listener for IP address: [fe80::f928:415:de1c:4d41%218103808]:4567
[4]9890.9E18::2023/01/11-11:40:21.977584200 [Metadata]Metadata: TraceEventInfo, Provider=Microsoft-Quic
[4]9890.9E18::2023/01/11-11:40:21.977584200 [Microsoft-Quic][conn][0x1B5020EAE30] ERROR, No listener found for connection.`

**Comment by StephenMLucas** [comment] 2023-01-11 22:33
To follow up - I reproduced the same IPv4 / IPv6 connection trace behavior using the MsQuic API directly, so if that is a problem it isn't one at the System.Net.Quic level. I'll follow up with the MSQuic team about that.

So the part that I think is still an API design issue for System.Net.Quic is not the originally reported problem but what @rzikm identified;

> The workaround for IPv6Any you mention was added as a quick (and possibly a bit dirty) fix to https://github.com/dotnet/runtime/issues/67442. Otherwise, ASP.NET users would run into the very same issue when listening for HTTP/3 connections. I think we should just go and mimic what sockets have: an explicit option whether the Listener should be "dual stack" or not (which would require pre-existing support in MsQuic).

When using the MSQuic API I can intentionally specify QUIC_ADDRESS_FAMILY_UNSPEC and have it accept incoming connections on all addresses. There's currently no way to do that via the System.Net.Quic API other than specifying an IPv6 address which will then always be 'promoted' to a wildcard by that workaround to accept any incoming address, whether that was the user intent or not.

**Comment by nibanks** [comment] 2023-01-12 00:53
As I indicated at the top, this is just rehashing what has already been discussed on https://github.com/microsoft/msquic/issues/2704. Because MsQuic multiplexes multiple connections/listeners on the same port, it always creates a wildcard, dual stack socket at the lower edge. Then when it receives a connection, it tries to match it to a listener, based on IP and ALPN. If no match is later found, the connection fails.

**Closed** 2023-01-12 09:40 UTC
Labels: untriaged, area-System.Net.Quic, needs-further-triage
