### ISSUE TITLE
System.Text.Json.Serialization.Tests.StreamTests.TestBOMWithShortAndLongBuffers(stream: MemoryStream { CanRead = True, CanSeek = True, CanTimeout = False, CanWrite = True, Capacity = 32768, ... }, count: 400, expectedStreamLength: 26401, bufferSize: 1) failing in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#32242] opened 2020-02-13 19:17 UTC
Configuration: `netcoreapp5.0-Windows_NT-Release-x64-CoreCLR_release-(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-08e8e40-20200107182504`

https://dnceng.visualstudio.com/public/_build/results?buildId=517998&view=ms.vss-test-web.build-test-results-tab&runId=16388378&paneView=debug

```
System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
   at System.Text.Json.JsonDocument.Dispose() in /_/src/libraries/System.Text.Json/src/System/Text/Json/Document/JsonDocument.cs:line 75
   at System.Text.Json.Serialization.Converters.JsonConverterJsonElement.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/JsonValueConverterJsonElement.cs:line 15
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.cs:line 122
   at System.Text.Json.Serialization.Converters.JsonIEnumerableDefaultConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/JsonIEnumerableDefaultConverter.cs:line 179
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.cs:line 206
   at System.Text.Json.Serialization.JsonConverter`1.TryReadAsObject(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, Object& value) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonConverterOfT.cs:line 82
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& state) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.cs:line 75
   at System.Text.Json.JsonSerializer.ReadCore(JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Stream.cs:line 230
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken) in /_/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Stream.cs:line 156
   at System.Text.Json.Serialization.Tests.StreamTests.TestBOMWithShortAndLongBuffers(Stream stream, Int32 count, Int32 expectedStreamLength, Int32 bufferSize) in /_/src/libraries/System.Text.Json/tests/Serialization/Stream.ReadTests.cs:line 204
--- End of stack trace from previous location ---
```

cc @ahsonkhan @steveharter

**Comment by ahsonkhan** [comment] 2020-02-21 06:01
I don't think we have ever seen this test fail in the past, so we should consider stress testing this and verifying that it always works as expected and it doesn't repro (maybe the recent converter refactoring introduced some subtle regression):
https://github.com/dotnet/runtime/blob/53c67cb43269269fd656e25b7199a065d04aeca1/src/libraries/System.Text.Json/tests/Serialization/Stream.ReadTests.cs#L192-L194

I am surprised we are getting an AOORException when disposing the JsonDocument. Nothing has changed there in a while.

https://github.com/dotnet/runtime/blob/53c67cb43269269fd656e25b7199a065d04aeca1/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/JsonValueConverterJsonElement.cs#L9-L15

https://github.com/dotnet/runtime/blob/59e343b28a8964600e3a65c1b25a16b4c93b409d/src/libraries/System.Text.Json/src/System/Text/Json/Document/JsonDocument.cs#L73-L77

cc @bartonjs in case you have any thoughts or suggestions here.

**Comment by bartonjs** [comment] 2020-02-21 06:15
The only places that _extraRentedBytes gets set to non-null the _utf8Json value is a ReadOnlyMemory over that same array `(0, _utf8Json.Length)`; so I can't see any way that it'd get de-aligned here without some very weird shenanigans or some sort of CLR memory problem (which would presumably be manifesting in other ways).

**Comment by ahsonkhan** [comment] 2020-02-21 06:31
Is it possible that something else was corrupting the shared ArrayPool (maybe due to incorrect rent/return)?

**Comment by bartonjs** [comment] 2020-02-21 07:23
> Is it possible that something else was corrupting the shared ArrayPool 

sure, but it wouldn't manifest that way.

Since `_utf8Json` is already `someArray.AsMemory(0, targetLength)`; `extraRentedBytes.AsSpan(0, _utf8Json.Length)` shouldn't be able to AOOR; that requires the same GC-Ref array changed lengths after the fact.  Or the array that the memory was pointing at got replaced.  Or something rewrote extraRentedBytes to not be the same as _utf8Json (or the other way around, I suppose... but the only (observed) writes to either of these fields is they're set in a ctor and cleared in Dispose... if we race-Disposed then we'd just clear (0,0), which is bad, but isn't AOOR... and there's no possible race here).

**Comment by steveharter** [comment] 2020-02-28 21:44
Linking #32824 in case it is related.

The code in fault should never get into this state when `document.RootElement.Clone()` is used (`extraRentedBytes` will be null). Some other code must be writing to an invalid pointer.

Closing as non-actionable. Please re-open if there are additional hits.

**Closed by steveharter** 2020-02-28 21:44 UTC
Labels: area-System.Text.Json, tenet-reliability
