### ISSUE TITLE
A bug in 'DateTime.ToString(String)' appeared in v5.0.3

### ISSUE THREAD

**Issue by zhenlinyang** [dotnet/runtime#48656] opened 2021-02-22 13:55 UTC
### Description

DateTime dateValue = new DateTime(2021, 02, 22, 08, 00, 00);
Console.WriteLine(dateValue.ToString("yyyy/MM/dd HH:mm:ss"));

--------Output(v5.0.3)--------
2021-02-22 08:00:00
![image](https://user-images.githubusercontent.com/6052587/108721412-ee46f200-755c-11eb-898d-8e5700b3c279.png)

--------Normal version(v5.0.0)--------
2021/02/22 08:00:00
![image](https://user-images.githubusercontent.com/6052587/108721076-8c868800-755c-11eb-9e33-a1e859ce157a.png)

### Configuration

Which version of .NET is the code running on? v5.0.3
What OS and version, and for Linux, what distro? Windows 10 (10.0.18363) / Linux
What is the architecture (x64, x86, ARM, ARM64)? x64
Do you know whether it is specific to that configuration? It is not specific to that configuration.

### Regression?

v5.0.0 can run normally.

**Comment by eiriktsarpalis** [comment] 2021-02-23 17:34
What kind of culture is your machine using? I see that try.dot.net uses the invariant culture so it might have something to do with that?

**Comment by zhenlinyang** [comment] 2021-02-24 09:01
> What kind of culture is your machine using? I see that try.dot.net uses the invariant culture so it might have something to do with that?
E.g. ‘en-US’

Visual Studio (v5.0.3)
![image](https://user-images.githubusercontent.com/6052587/108975397-69c1b400-76c1-11eb-871e-d44920d3db87.png)

try.dot.net (v4.0.50524.0)
![image](https://user-images.githubusercontent.com/6052587/108975776-cf15a500-76c1-11eb-8aa9-9ba135332619.png)

**Comment by eiriktsarpalis** [comment] 2021-02-24 10:52
I can't reproduce with `5.0.3` on my machine:

```csharp
using System;
using System.Globalization;

class Program
{
    static void Main()
    {
        Console.WriteLine(Environment.Version);
        DateTime dateValue = new DateTime(2021, 02, 22, 08, 00, 00);
        Console.WriteLine(dateValue.ToString("yyyy/MM/dd HH:mm:ss", new CultureInfo("en-US")));
    }
}
```

![image](https://user-images.githubusercontent.com/2813363/108989912-0b2f1280-768e-11eb-851f-d6cc41b284bd.png)

Could you share the output of `dotnet --info`? Be sure to use the same SDK as the one used by your VS environment.

**Comment by zhenlinyang** [comment] 2021-02-24 11:08
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.103\

Host (useful for support):
  Version: 6.0.0-preview.1.21102.12
  Commit:  9b2776d481

.NET SDKs installed:
  2.1.812 [C:\Program Files\dotnet\sdk]
  3.1.405 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]
  5.0.200-preview.21079.7 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.1.21103.13 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.1.21103.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.1.21102.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.1.21103.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

![image](https://user-images.githubusercontent.com/6052587/108991968-b2826880-76d3-11eb-915f-55bc6b56998c.png)

**Comment by zhenlinyang** [comment] 2021-02-24 11:17
I installed .Net v6.0.0-preview.1 a few days ago, but I can be sure that the problem occurred before installing .Net v6.0.0-preview.1.

**Comment by eiriktsarpalis** [comment] 2021-02-24 11:34
I can't reproduce the issue in .NET 6 either. Could you check if it reproduces when running the application from the terminal using `dotnet run`? And share the contents of `dotnet --info` in the same session?

**Comment by zhenlinyang** [comment] 2021-02-24 13:06
![image](https://user-images.githubusercontent.com/6052587/109004776-2b89bc00-76e4-11eb-8e48-31b22b30bf6c.png)

I found this bug only occurs in 'en-US'.

**Comment by tarekgh** [comment] 2021-02-24 17:26
@zhenlinyang using `/` and `:` for date and time separator in the format string doesn't mean you'll get literally these characters. These means the date and time separator for the used cultures. i.e. if the culture has `-` as date separator, then the formatted string will get `-` instead of `/`. 

If you want to get literally the `/`, please use single quotation around it. Something like:

```C#
    Console.WriteLine(dateValue.ToString("yyyy'/'MM'/'dd HH':'mm':'ss"));
```

I am closing the issue but feel free to send any question or if you still have any issue.

**Closed by tarekgh** 2021-02-24 17:26 UTC
Labels: area-System.Globalization, untriaged

**Comment by zhenlinyang** [comment] 2021-02-25 04:37
@tarekgh Thank you, I understand that using `'` can force the use of `/`, but I still have two questions.
(1) I have used many versions of dotnet for several years, but this change has only happened recently. Is it reasonable to change `/` to `-` ? Is this an expected modification?
(2) Why the same `v5.0.3`, Windows10 x64, and `en-US`, but some machines display `/` and some machines display `-` ? The same input cannot produce the same output. This makes me doubt the stability of program execution, so that I only dare to use `InvariantCulture`.

**Comment by safern** [comment] 2021-02-25 06:00
@zhenlinyang whats the machine UI Culture? It is possible that it is using the user overrides in the machines that you are seeing this behavior and this machines specify - as the date separator?

 Could you try passing `false` to the culture info constructor so that it doesn't use the user overrides?
```cs
Console.WriteLine(dateValue.ToString("yyyy/MM/dd HH:mm:ss", new CultureInfo("en-US", false)));
```

I was able to repro this issue by changing the short date time settings in my computer to:
![Screen Shot 2021-02-24 at 9 55 24 PM](https://user-images.githubusercontent.com/22899328/109110011-2c721c00-76eb-11eb-881b-05609228c5df.png)

But then when I pass down `false` to the CultureInfo so that it doesn't honor user overrides, I get the expected result.

![image](https://user-images.githubusercontent.com/22899328/109110184-7824c580-76eb-11eb-82ea-6cbcf1ce0784.png)

![image](https://user-images.githubusercontent.com/22899328/109110295-b15d3580-76eb-11eb-8917-6c8d855bd36f.png)

**Comment by zhenlinyang** [comment] 2021-02-25 08:50
@safern Thank you, I reproduced this case and understood the reason. The execution result is different due to the machine configuration.

**Comment by safern** [comment] 2021-02-25 09:25
Yep, please let us know if you have any other questions or hit any hurdles.
