### ISSUE TITLE
GC region related failure on alpine

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#66631] opened 2022-03-15 01:48 UTC
Arm64 libraries test failure on   Starting:    

https://dev.azure.com/dnceng/public/_build/results?buildId=1663158&view=ms.vss-test-web.build-test-results-tab

```
System.Text.Json.Tests (parallel test collections = on, max threads = 4)

Assert failure(PID 24 [0x00000018], Thread: 54 [0x0036]): global_regions_to_decommit[kind].get_num_free_regions() == num_regions_to_decommit_before + (size_t)num_regions_to_decommit[kind]
    File: /__w/1/s/src/coreclr/gc/gc.cpp Line: 12432
    Image: /root/helix/work/correlation/dotnet
```

**Comment by AndyAyersMS** [comment] 2022-03-15 01:50
Also seen in https://dev.azure.com/dnceng/public/_build/results?buildId=1660696&view=ms.vss-test-web.build-test-results-tab on x64.

**Comment by mangod9** [comment] 2022-03-15 04:38
This is a dupe of existing issue: https://github.com/dotnet/runtime/issues/66601

**Closed by mangod9** 2022-03-15 04:38 UTC
Labels: arch-arm64, arch-x64, os-alpine
