### ISSUE TITLE
[CI] Test failure from `System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Cookies_Http3.GetAsync_DefaultCoookieContainer_NoCookieSent`

### ISSUE THREAD

**Issue by kouvel** [dotnet/runtime#101567] opened 2024-04-25 19:23 UTC
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=655031
Build error leg or test failing: Build / Libraries Test Run release coreclr windows x64 Debug / Send to Helix
Pull request: https://github.com/dotnet/runtime/pull/101501

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "System.Net.Quic.QuicException : The connection timed out from inactivity.",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=655031
**Error message validated:** `[System.Net.Quic.QuicException : The connection timed out from inactivity.`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 4/25/2024 8:21:21 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[655218](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655218)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655218&view=ms.vss-test-web.build-test-results-tab&runId=16258546&resultId=214795)|dotnet/runtime#101318|
|[655926](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655926)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Cookies_Http3.GetAsync_DefaultCoookieContainer_NoCookieSent](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655926&view=ms.vss-test-web.build-test-results-tab&runId=16254078&resultId=217803)|dotnet/runtime#101540|
|[656345](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656345)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Cookies_Http3.GetAsync_DefaultCoookieContainer_NoCookieSent](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656345&view=ms.vss-test-web.build-test-results-tab&runId=16249946&resultId=214606)|dotnet/runtime#101568|
|[656316](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656316)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Finalization_Http3.IncompleteResponseStream_ResponseDropped_CancelsRequestToServer](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656316&view=ms.vss-test-web.build-test-results-tab&runId=16249528&resultId=188699)|dotnet/runtime#101513|
|[656320](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656320)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656320&view=ms.vss-test-web.build-test-results-tab&runId=16249504&resultId=214914)|dotnet/runtime#101294|
|[656230](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656230)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656230&view=ms.vss-test-web.build-test-results-tab&runId=16247052&resultId=217928)|dotnet/runtime#101188|
|[655011](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655011)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655011&view=ms.vss-test-web.build-test-results-tab&runId=16246716&resultId=217878)|dotnet/runtime#101221|
|[656221](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656221)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656221&view=ms.vss-test-web.build-test-results-tab&runId=16246766&resultId=217782)|dotnet/runtime#101450|
|[656213](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656213)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656213&view=ms.vss-test-web.build-test-results-tab&runId=16246190&resultId=214564)|dotnet/runtime#101381|
|[656209](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656209)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656209&view=ms.vss-test-web.build-test-results-tab&runId=16246160&resultId=214493)|dotnet/runtime#100266|
|[656202](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656202)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656202&view=ms.vss-test-web.build-test-results-tab&runId=16245960&resultId=214448)|dotnet/runtime#101557|
|[656219](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656219)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656219&view=ms.vss-test-web.build-test-results-tab&runId=16245762&resultId=217685)|dotnet/runtime#100389|
|[656161](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656161)|dotnet/runtime|[System.Net.Http.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656161&view=ms.vss-test-web.build-test-results-tab&runId=16245118&resultId=217973)|dotnet/runtime#101531|
|[656061](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656061)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.ReadAsStreamAsync_HandlerProducesWellBehavedResponseStream](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656061&view=ms.vss-test-web.build-test-results-tab&runId=16242412&resultId=217721)||
|[656049](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656049)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Cookies_Http3.GetAsync_DefaultCoookieContainer_NoCookieSent](https://dev.azure.com/dnceng-public/public/_build/results?buildId=656049&view=ms.vss-test-web.build-test-results-tab&runId=16241592&resultId=214509)|dotnet/runtime#100141|
|[655951](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655951)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655951&view=ms.vss-test-web.build-test-results-tab&runId=16238866&resultId=214384)|dotnet/runtime#101545|
|[655948](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655948)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655948&view=ms.vss-test-web.build-test-results-tab&runId=16239256&resultId=197591)|dotnet/runtime#101545|
|[655753](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655753)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Cookies_Http3.GetAsync_DefaultCoookieContainer_NoCookieSent](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655753&view=ms.vss-test-web.build-test-results-tab&runId=16233836&resultId=206716)|dotnet/runtime#101133|
|[655731](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655731)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655731&view=ms.vss-test-web.build-test-results-tab&runId=16233594&resultId=217625)|dotnet/runtime#101053|
|[655722](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655722)|dotnet/runtime|[System.Net.Quic.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655722&view=ms.vss-test-web.build-test-results-tab&runId=16231922&resultId=104942)||
|[655689](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655689)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655689&view=ms.vss-test-web.build-test-results-tab&runId=16232660&resultId=217816)|dotnet/runtime#101478|
|[655692](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655692)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Cookies_Http3.GetAsync_DefaultCoookieContainer_NoCookieSent](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655692&view=ms.vss-test-web.build-test-results-tab&runId=16232658&resultId=217669)|dotnet/runtime#101531|
|[655700](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655700)|dotnet/runtime|[System.Net.Quic.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655700&view=ms.vss-test-web.build-test-results-tab&runId=16231910&resultId=104942)||
|[655709](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655709)|dotnet/runtime|[System.Net.Quic.Functional.Tests.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655709&view=ms.vss-test-web.build-test-results-tab&runId=16231836&resultId=104942)||
|[655669](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655669)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655669&view=ms.vss-test-web.build-test-results-tab&runId=16231170&resultId=214718)|dotnet/runtime#101392|
|[655619](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655619)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655619&view=ms.vss-test-web.build-test-results-tab&runId=16229756&resultId=217649)|dotnet/runtime#101531|
|[655583](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655583)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Cookies_Http3.GetAsync_DefaultCoookieContainer_NoCookieSent](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655583&view=ms.vss-test-web.build-test-results-tab&runId=16229324&resultId=217761)||
|[655445](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655445)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.ReadAsStreamAsync_HandlerProducesWellBehavedResponseStream](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655445&view=ms.vss-test-web.build-test-results-tab&runId=16225654&resultId=214722)|dotnet/runtime#101525|
|[655365](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655365)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655365&view=ms.vss-test-web.build-test-results-tab&runId=16223678&resultId=209217)|dotnet/runtime#101450|
|[655360](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655360)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655360&view=ms.vss-test-web.build-test-results-tab&runId=16223490&resultId=214371)|dotnet/runtime#101451|
|[655225](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655225)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655225&view=ms.vss-test-web.build-test-results-tab&runId=16219104&resultId=214645)|dotnet/runtime#101450|
|[655080](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655080)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655080&view=ms.vss-test-web.build-test-results-tab&runId=16213180&resultId=217597)|dotnet/runtime#101512|
|[653929](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653929)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.ReadAsStreamAsync_HandlerProducesWellBehavedResponseStream](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653929&view=ms.vss-test-web.build-test-results-tab&runId=16212080&resultId=218047)|dotnet/runtime#101418|
|[655003](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655003)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.ReadAsStreamAsync_HandlerProducesWellBehavedResponseStream](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655003&view=ms.vss-test-web.build-test-results-tab&runId=16210550&resultId=217774)|dotnet/runtime#101507|
|[655031](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655031)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_AltSvc_Test_Http3.AltSvc_Header_Upgrade_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655031&view=ms.vss-test-web.build-test-results-tab&runId=16211640&resultId=217748)|dotnet/runtime#101501|
|[653237](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653237)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Http3.ReadAsStreamAsync_HandlerProducesWellBehavedResponseStream](https://dev.azure.com/dnceng-public/public/_build/results?buildId=653237&view=ms.vss-test-web.build-test-results-tab&runId=16158360&resultId=214438)|dotnet/runtime#101390|
|[652467](https://dev.azure.com/dnceng-public/public/_build/results?buildId=652467)|dotnet/runtime|[System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_HttpClientHandlerTest_Headers_Http3.SendAsync_Expires_Success](https://dev.azure.com/dnceng-public/public/_build/results?buildId=652467&view=ms.vss-test-web.build-test-results-tab&runId=16137076&resultId=218822)|dotnet/runtime#101308|
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|25|37|37|

**Comment by CarnaViire** [comment] 2024-04-25 20:01
Should be a dupe of https://github.com/dotnet/runtime/issues/91757

**Comment by kouvel** [comment] 2024-04-25 20:05
Ah ok. I think the main difference is https://github.com/dotnet/runtime/issues/91757 is using ErrorPattern but the pattern doesn't look like a regex, so it wouldn't have matched the ErrorMessage string in this issue.

**Comment by kouvel** [comment] 2024-04-25 20:07
Actually nevermind, it seems like that should have matched the error message, not sure why it wouldn't have.

**Comment by CarnaViire** [comment] 2024-04-25 20:08
![image](https://github.com/dotnet/runtime/assets/3184057/cfa5af9d-c928-43f0-adfc-393109bbca80)
I believe it was matched

**Comment by CarnaViire** [comment] 2024-04-25 20:09
Oh, it's a different test it seems 🙈

**Comment by CarnaViire** [comment] 2024-04-25 20:14
> Oh is the test taken into account somehow? I thought it was just based on the message/pattern.

Hmmm you're right. The column with the test name confused me.

Then it _should_ have been matched -- as the build in question is present in the table... 🤔

**Comment by kouvel** [comment] 2024-04-25 20:15
The build analysis in my PR https://github.com/dotnet/runtime/pull/101501 did not recognize this as a known issue (at least in attempt 3, though I saw the same failure in the first two). I had rerun it again.

**Comment by JulieLeeMSFT** [comment] 2024-04-26 01:47
@CarnaViire, can we close this issue because you merged #101569?

**Comment by CarnaViire** [comment] 2024-04-26 11:08
@JulieLeeMSFT I'd close this one as it _should_ be all matched to https://github.com/dotnet/runtime/issues/91757 -- in case it wouldn't happen, can you please tag someone from the "Known Issues" team so they can help troubleshoot?

As for https://github.com/dotnet/runtime/pull/101569 -- we need first to verify that the timeouts went away or at least subsided (after the change propagates). And even then, there's going to be quite an untrivial investigation. So at least https://github.com/dotnet/runtime/issues/91757 would be open as a tracking issue for the investigation.

**Comment by CarnaViire** [comment] 2024-04-26 11:08
Duplicate of #91757

**Closed by CarnaViire** 2024-04-26 11:08 UTC
Labels: blocking-clean-ci, untriaged, area-System.Net.Quic, Known Build Error

**Comment by AlitzelMendez** [comment] 2024-04-26 23:20
> @JulieLeeMSFT I'd close this one as it _should_ be all matched to #91757 -- in case it wouldn't happen, can you please tag someone from the "Known Issues" team so they can help troubleshoot?
> 
> As for #101569 -- we need first to verify that the timeouts went away or at least subsided (after the change propagates). And even then, there's going to be quite an untrivial investigation. So at least #91757 would be open as a tracking issue for the investigation.

could you please provide more details on the expectation of this known issue? like sharing a build that you were expecting this issue would match

I compared with the other known issue that you shared but they have a different error message, this one has an ErrorMessage and the other issue has an ErrorPattern which is slightly different so it is naturally that the match different builds, but if you were expecting a particular build please share it with me so I can take a look

**Comment by kouvel** [comment] 2024-04-26 23:43
Here's some info about the failure that wasn't matched to https://github.com/dotnet/runtime/issues/91757:
- PR: https://github.com/dotnet/runtime/pull/101501 (see Attempt 3 of the runtime pipeline)
- Failing job: [link](https://dev.azure.com/dnceng-public/public/_build/results?buildId=655031&view=logs&j=29651480-e2ad-5378-f196-08ddbe18897a&t=9ad806ec-7439-54f6-121a-945264270db4&s=b49e7e65-b64b-557c-018e-3fd79c15ded6)
- Console log: [link](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-101501-merge-f42a4c226523400181/System.Net.Http.Functional.Tests/3/console.ce8bcfa5.log?helixlogtype=result)

Even though https://github.com/dotnet/runtime/issues/91757 is using ErrorPattern, treating it as a regex the expectation was that it would still match the error message in the console log: `System.Net.Quic.QuicException : The connection timed out from inactivity.`

**Comment by kouvel** [comment] 2024-04-26 23:54
I'm not sure how to access the build analysis from previous build attempts. If there's a way, the 3rd attempt would show the failure as some that is not a known failure.

**Comment by CarnaViire** [comment] 2024-04-27 11:11
> the other issue has an ErrorPattern which is slightly different 

As @kouvel also mentioned above, the regex in https://github.com/dotnet/runtime/issues/91757 is 
`"ErrorPattern": "System.Net.Quic.QuicException ?: The connection timed out from inactivity"`
And applying the validation suggested in https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md#how-to-create-a-known-issue-step-by-step you can see that it matches
![image](https://github.com/dotnet/runtime/assets/3184057/569446dc-aac1-4583-838c-d18f3e558316)
unless we're missing something @AlitzelMendez
