### ISSUE TITLE
System.Linq.Expressions tests are broken in CI

### ISSUE THREAD

**Issue by eerhardt** [dotnet/runtime#51346] opened 2021-04-15 21:57 UTC
```
C:\h\w\A918093D\w\A6DD0962\e>"C:\h\w\A918093D\p\dotnet.exe" exec --runtimeconfig System.Linq.Expressions.Tests.runtimeconfig.json --depsfile System.Linq.Expressions.Tests.deps.json xunit.console.dll System.Linq.Expressions.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing  
  Discovering: System.Linq.Expressions.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Linq.Expressions.Tests (found 5645 of 5657 test cases)
  Starting:    System.Linq.Expressions.Tests (parallel test collections = on, max threads = 2)
    System.Linq.Expressions.Tests.ConvertTests.ConvertFloatToNullableULongTest(useInterpreter: False) [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   9223372036854775808
      Stack Trace:
        /_/src/libraries/System.Linq.Expressions/tests/Convert/ConvertTests.cs(11459,0): at System.Linq.Expressions.Tests.ConvertTests.VerifyFloatToNullableULong(Single value, Boolean useInterpreter)
        /_/src/libraries/System.Linq.Expressions/tests/Convert/ConvertTests.cs(3128,0): at System.Linq.Expressions.Tests.ConvertTests.ConvertFloatToNullableULongTest(Boolean useInterpreter)
    System.Linq.Expressions.Tests.ConvertTests.ConvertDoubleToNullableULongTest(useInterpreter: False) [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   9223372036854775808
      Stack Trace:
        /_/src/libraries/System.Linq.Expressions/tests/Convert/ConvertTests.cs(9533,0): at System.Linq.Expressions.Tests.ConvertTests.VerifyDoubleToNullableULong(Double value, Boolean useInterpreter)
        /_/src/libraries/System.Linq.Expressions/tests/Convert/ConvertTests.cs(1686,0): at System.Linq.Expressions.Tests.ConvertTests.ConvertDoubleToNullableULongTest(Boolean useInterpreter)
    System.Linq.Expressions.Tests.ConvertTests.ConvertNullableDoubleToNullableULongTest(useInterpreter: False) [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   9223372036854775808
      Stack Trace:
        /_/src/libraries/System.Linq.Expressions/tests/Convert/ConvertTests.cs(9904,0): at System.Linq.Expressions.Tests.ConvertTests.VerifyNullableDoubleToNullableULong(Nullable`1 value, Boolean useInterpreter)
        /_/src/libraries/System.Linq.Expressions/tests/Convert/ConvertTests.cs(1938,0): at System.Linq.Expressions.Tests.ConvertTests.ConvertNullableDoubleToNullableULongTest(Boolean useInterpreter)
    System.Linq.Expressions.Tests.ConvertTests.ConvertNullableFloatToNullableULongTest(useInterpreter: False) [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   9223372036854775808
      Stack Trace:
        /_/src/libraries/System.Linq.Expressions/tests/Convert/ConvertTests.cs(11830,0): at System.Linq.Expressions.Tests.ConvertTests.VerifyNullableFloatToNullableULong(Nullable`1 value, Boolean useInterpreter)
        /_/src/libraries/System.Linq.Expressions/tests/Convert/ConvertTests.cs(3380,0): at System.Linq.Expressions.Tests.ConvertTests.ConvertNullableFloatToNullableULongTest(Boolean useInterpreter)
  Finished:    System.Linq.Expressions.Tests
=== TEST EXECUTION SUMMARY ===
   System.Linq.Expressions.Tests  Total: 35230, Errors: 0, Failed: 4, Skipped: 0, Time: 29.861s
```

**Comment by eerhardt** [comment] 2021-04-15 21:59
Pinging the authors of the latest changes in src\coreclr:

@kunalspathak @SingleAccretion @davidwrighton @MichalStrehovsky @BruceForstall @trylek @jkoritzinsky

**Comment by SingleAccretion** [comment] 2021-04-15 22:13
Sigh. This is caused by #50450 - we are now folding the cases when `float/double -> ulong` conversions occur (previously they went through the helper path and weren't being folded) and this test is exercising some implementation-defined casts:

https://github.com/dotnet/runtime/blob/79ad10cf22debef83b1038047e1b42db4a5256a2/src/libraries/System.Linq.Expressions/tests/Convert/ConvertTests.cs#L3126

It has the same root cause as #47374, and the fix is blocked by resolving #47478.

I will put up a PR to disable these for now.

@eerhardt I assume the log you have contains all the failures, right?

**Comment by eerhardt** [comment] 2021-04-15 22:17
> I assume the log you have contains all the failures, right?

I think so.

**Comment by AndyAyersMS** [comment] 2021-06-07 20:17
@SingleAccretion going to assign this to you. Let me know if you're not able to get to this sometime in the next week or two.

**Comment by SingleAccretion** [comment] 2021-06-07 20:18
I have a PR up that will re-enable these tests: #53782. I will switch it as ready-for-review.

**Closed** 2021-07-07 15:25 UTC
Labels: area-CodeGen-coreclr, disabled-test, in pr
