### ISSUE TITLE
HTTP/3 request HttpContent cancellation is different from HTTP/2

### ISSUE THREAD

**Issue by MihaZupan** [dotnet/runtime#60253] opened 2021-10-11 14:42 UTC
The behavior of the `CancellationToken` passed to `HttpContent.CopyToAsync` differs between HTTP/2 and HTTP/3.

Both [HTTP/2](https://github.com/dotnet/runtime/blob/9dcde5f8a182a9202a50afa92fec463f6654ecd9/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs#L202) and [HTTP/3](https://github.com/dotnet/runtime/blob/565ff522bf630ff0556f3dc590dcb7337696a5d4/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs#L158-L165) use dedicated `CancellationTokenSource`s that are used to signal the `HttpContent` in case of a server reset / GoAway / connection-level failure / dispose.

The notable difference is that on HTTP/3, the `CancellationTokenRegistration` will be [disposed when `SendAsync` returns](https://github.com/dotnet/runtime/blob/565ff522bf630ff0556f3dc590dcb7337696a5d4/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs#L310). After that point, the CT the content is using is effectively `CT.None`.
This may delay cancellation until a write is attempted (which could take a while in duplex scenarios).

Is this the intended behavior? The choice to dispose the CTR and stop signaling the CT seems odd compared to HTTP/2.

Original YARP discussion: https://github.com/microsoft/reverse-proxy/pull/1271#discussion_r725267658

**Comment by CarnaViire** [comment] 2021-10-11 17:30
Thanks for raising that up.

Do I understand it right that the problem is mostly in aborting stream on the wire and not in showing the exception to the user?

I agree that HTTP/3 seems to be missing GOAWAY cancellation logic after SendAsync completes. This should be fixed.

I also see that AbortWrite on Exception only happens [while inside SendAsync](https://github.com/dotnet/runtime/blob/565ff522bf630ff0556f3dc590dcb7337696a5d4/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs#L299-L301); meaning if any exception occurs after SendAsync finishes, AbortWrite will be postponed until Http3ResponseStream is disposed -- [WriteRequestContentAsync](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L1913-L1918) doesn't have any Exception logic, while [ReadResponseContent](https://github.com/dotnet/runtime/blob/565ff522bf630ff0556f3dc590dcb7337696a5d4/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs#L1042) does. 


**For other scenarios:**

External CancellationToken passed to SendAsync does not affect streaming as soon as SendAsync completes - that is intentional and I believe HTTP/2 also behave in the same manner, so disposing HttpResponseMessage is used for cancellation. See discussion in https://github.com/dotnet/runtime/issues/30791 and
https://github.com/dotnet/runtime/blob/565ff522bf630ff0556f3dc590dcb7337696a5d4/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs#L1913-L1918

Disposing HttpResponseMessage/Http3RequestStream [properly aborts](https://github.com/dotnet/runtime/blob/565ff522bf630ff0556f3dc590dcb7337696a5d4/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http3RequestStream.cs#L88) the stream on the wire.

Also, peer aborting on the wire will be handled inside msquic; correct exception will bubble up upon attempting to write. There is a (now internal) QuicStream API to detect peer aborting right away without writing https://github.com/dotnet/runtime/issues/58229 It was added for Kestrel but I see how it might be useful for HttpClient side too.

**Comment by CarnaViire** [comment] 2021-10-11 19:49
@MihaZupan could you please help me understand the scenario -- where and when the exception is expected? I am only familiar with duplex streaming from gRPC perspective or a very simple custom HttpContent like [this one](https://github.com/dotnet/runtime/blob/d8acd7e7ff4f54efaf170e098eb592309a610219/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http3.cs#L1356-L1387), so maybe I miss something. If SendAsync is finished and no one is writing to the stream -- which method should throw?

**Comment by ManickaP** [comment] 2021-10-13 14:55
@MihaZupan Is this about the cancellation token passed to your custom HttpContent's `SerializeToStreamAsync` override? And it not being ever canceled in H/3 after `SendAsync` portion of logic finishes?

So you're stuck waiting for another data to arrive from the front-end, while the back-end might have cut the connection long time ago. And instead of ending the whole session immediately (cancelling the read via the cancellation token), you need to first consume some data and then you'll learn of the connection abort (or whatever different reason) only from calling `stream.WriteAsync`.

**Comment by MihaZupan** [comment] 2021-10-13 15:07
Yes, that's a good way to describe it.

**Closed** 2022-05-12 17:35 UTC
Labels: bug, area-System.Net.Http, in-pr
