### ISSUE TITLE
Test failure: System.ComponentModel.Composition.ScopeExportFactoryTests.SimpleChainWithMetadata

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#46717] opened 2021-01-08 00:55 UTC
failed in job: [runtime 20210107.59 ](https://dev.azure.com/dnceng/public/_build/results?buildId=942044&view=ms.vss-test-web.build-test-results-tab&runId=29752622&resultId=169899&paneView=debug)

net6.0-Linux-Release-x64-Mono_release-Ubuntu.1604.Amd64.Open

Error message
~~~
System.NotSupportedException : Interface 'System.ComponentModel.Composition.ScopeExportFactoryTests+IFooMetadata' is not a valid MetadataView; MetadataViews do not support non-public interfaces, and interfaces that contain members that are not properties.
---- System.TypeLoadException : Could not load type '_proxy_System.ComponentModel.Composition.ScopeExportFactoryTests+IFooMetadata_a23bfda9-d55b-4277-b21b-84db0c27d4ef' from assembly ''.


Stack trace
   at System.ComponentModel.Composition.MetadataViewProvider.GetMetadataView[IFooMetadata](IDictionary`2 metadata) in /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/MetadataViewProvider.cs:line 44
   at System.ComponentModel.Composition.AttributedModelServices.GetMetadataView[IFooMetadata](IDictionary`2 metadata) in /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/AttributedModelServices.cs:line 23
   at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.CreateStronglyTypedExportFactoryOfTM[IFooContract,IFooMetadata](Export export) in /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/ReflectionModel/ExportfactoryCreator.cs:line 70
   at System.ComponentModel.Composition.ReflectionModel.ExportFactoryCreator.<>c__DisplayClass4_0.<CreateStronglyTypedExportFactoryFactory>b__0(Export e) in /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/ReflectionModel/ExportfactoryCreator.cs:line 44
   at System.ComponentModel.Composition.ReflectionModel.ImportingItem.CastSingleExportToImportType(Type type, Export export) in /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/ReflectionModel/ImportingItem.cs:line 95
   at System.ComponentModel.Composition.ReflectionModel.ImportingItem.CastExportsToSingleImportType(Export[] exports) in /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/ReflectionModel/ImportingItem.cs:line 88
   at System.ComponentModel.Composition.ReflectionModel.ImportingItem.CastExportsToImportType(Export[] exports) in /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/ReflectionModel/ImportingItem.cs:line 44
   at System.ComponentModel.Composition.ReflectionModel.ReflectionComposablePart.SetImport(ImportingItem item, Export[] exports) in /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/ReflectionModel/ReflectionComposablePart.cs:line 242
   at System.ComponentModel.Composition.ReflectionModel.ReflectionComposablePart.SetImport(ImportDefinition definition, IEnumerable`1 exports) in /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/ReflectionModel/ReflectionComposablePart.cs:line 204
   at System.ComponentModel.Composition.Hosting.ImportEngine.PartManager.TrySetImport(ImportDefinition import, Export[] exports) in /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ImportEngine.PartManager.cs:line 79
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportSubset(PartManager partManager, IEnumerable`1 imports, AtomicComposition atomicComposition) in /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ImportEngine.cs:line 477
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportsStateMachine(PartManager partManager, ComposablePart part) in /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ImportEngine.cs:line 357
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImports(PartManager partManager, ComposablePart part, Boolean shouldTrackImports) in /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ImportEngine.cs:line 436
   at System.ComponentModel.Composition.Hosting.ImportEngine.SatisfyImports(ComposablePart part) in /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/ImportEngine.cs:line 171
   at System.ComponentModel.Composition.Hosting.CompositionServices.GetExportedValueFromComposedPart(ImportEngine engine, ComposablePart part, ExportDefinition definition) in /_/src/libraries/System.ComponentModel.Composition/src/System/ComponentModel/Composition/Hosting/CompositionServic
~~~

**Comment by safern** [comment] 2021-01-08 00:57
This issue is: https://github.com/mono/mono/issues/16417 and it was disabled on: https://github.com/dotnet/runtime/pull/46699

cc: @lambdageek @steveisok

**Comment by safern** [comment] 2021-01-08 01:18
Dupe of: https://github.com/dotnet/runtime/issues/46717

**Closed by safern** 2021-01-08 01:18 UTC
Labels: area-System.ComponentModel, disabled-test, runtime-mono
