### ISSUE TITLE
[API Proposal]: make ZipArchive implement IAsyncDisposable

### ISSUE THREAD

**Issue by madelson** [dotnet/runtime#79586] opened 2022-12-13 02:29 UTC
### Background and motivation

Disposing of a `ZipArchive` writes content to the underlying `Stream`. It would be nice to be able to do this as an async operation. 

In particular, https://github.com/dotnet/runtime/issues/1560 (20 upvotes) describes how not being async in this case will throw errors when writing to a `ZipArchive` which is an ASP.NET Core response body stream (since those streams do not allow sync IO by default). Streaming directly into a `ZipArchive` is a nice way to dynamically generate large file exports (e.g. streaming from a database); it's a shame that this doesn't work out of the box without enabling sync IO.

This change would also make partial progress towards supporting https://github.com/dotnet/runtime/issues/1541 (95 upvotes).

### API Proposal

```csharp
namespace System.IO.Compression;

public class ZipArchive : IDisposable, IAsyncDisposable
{
    public ValueTask DisposeAsync();
}
```

### API Usage

```csharp
await using ZipArchive zip = new(Response.Body, ZipArchiveMode.Create, leaveOpen: true);
// generate entries here
```

### Alternative Designs

n/a

**Comment by carlossanlop** [comment] 2023-04-25 23:11
Duplicate of https://github.com/dotnet/runtime/issues/1560

**Closed by carlossanlop** 2023-04-25 23:11 UTC
Labels: api-suggestion, area-System.IO.Compression
