### ISSUE TITLE
Cannot build clr after installing latest VS nightly

### ISSUE THREAD

**Issue by GrabYourPitchforks** [dotnet/runtime#41886] opened 2020-09-04 18:51 UTC
Just updated to VS 2019 Int Preview 16.8.0 Preview 3.0 \[30504.10.main\], and builds are failing on my local box. Repros in both the _master_ and the _release/5.0-rc2_ branches.

Error appears even after running `git clean -xdf`.

```txt
> build.cmd -s clr -c Release
... snip ...
    20>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9461,5): warning C5105: macro expansion producing 'defined' has undefined behavior (compiling source file C:\runtime\artifacts\obj\coreclr\Windows_NT.x64.Release\src\inc\idls_out\cordebug_i.c) [C:\runtime\artifacts\obj\coreclr\Windows_NT.x64.Release\src\inc\corguids_obj.vcxproj]
    20>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9461,5): error C2220: the following warning is treated as an error (compiling source file C:\runtime\artifacts\obj\coreclr\Windows_NT.x64.Release\src\inc\idls_out\cordebug_i.c) [C:\runtime\artifacts\obj\coreclr\Windows_NT.x64.Release\src\inc\corguids_obj.vcxproj]
```

More info on the warning: https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/c5105

**Comment by ViktorHofer** [comment] 2020-09-04 18:52
cc @trylek @jkoritzinsky @josalem

**Comment by josalem** [comment] 2020-09-04 19:12
For reference the file that generates that `.h/.c` pair hasn't been changed since the end of July: https://github.com/dotnet/runtime/blob/master/src/coreclr/src/inc/cordebug.idl

Interesting that this didn't happen before this VS update.  Based on this snippet from the docs:
> Microsoft-specific behavior: The MSVC compiler evaluates the defined operator normally, even under /permissive-.
>
>This warning is new in Visual Studio 2017 version 15.8. It's only generated by the new standards-compliant preprocessor, specified by the /experimental:preprocessor compiler option.

I'm wondering if the default preprocessor warnings changed?

Looking at the [checked in `.cpp` versions](https://github.com/dotnet/runtime/blob/master/src/coreclr/src/pal/prebuilt/idl/cordebug_i.cpp) I didn't see anything that looked like the docs example, but I haven't looked at the generated `.h/.c` files on Windows.

CC @hoyosjs @mikem8361 have you run across this issue before when changing this file?

**Comment by GrabYourPitchforks** [comment] 2020-09-04 19:21
I confirmed that appending `add_compile_options(/wd5105)` to the following locations fixes the build on my machine.

https://github.com/dotnet/runtime/blob/22927dd384ee22bdebc7fa7d06eb1887470a5143/eng/native/configurecompiler.cmake#L445-L447

https://github.com/dotnet/runtime/blob/22927dd384ee22bdebc7fa7d06eb1887470a5143/src/libraries/Native/Windows/CMakeLists.txt#L44

See also internal tracking items https://devdiv.visualstudio.com/DevDiv/_workitems/edit/966470 and https://microsoft.visualstudio.com/OS/_workitems/edit/23240387 for further context.

**Comment by hoyosjs** [comment] 2020-09-04 20:11
The CPP checked in version is just the windows C version renamed. So this is a toolset change indeed, and there's a few places where the new preprocessor will hit this - anything that touches a header like winbase.h or minwindef.h

**Comment by GrabYourPitchforks** [comment] 2020-09-05 00:11
Possible root cause is that the intermediate project file __corguids\_obj.vcxproj__ contains the following line:

```xml
<AdditionalOptions>%(AdditionalOptions) /Zm200 /Zc:strictStrings /w34092 /w34121 /w34125 /w34130 /w34132 /w34212 /w34530 /w35038 /w44177 /ZH:SHA_256 /source-charset:utf-8 -std:c11</AdditionalOptions>
```

Note the "`-std:c11`" at the end. I don't know why this intermediate project file is getting this extra option set. None of the other .vcxproj files seem to contain this setting.

Will need to hand the investigation off to somebody else, as I think I've gone as far as I can go with my current skill set. :)

**Comment by GrabYourPitchforks** [comment] 2020-09-05 05:55
Keeping this open to track reacting to any suggestions from MSVC / Windows SDK team.

**Comment by sebastienros** [comment] 2020-11-13 19:18
This seems to be fixed on master, but I have the same issue on release/5.0

**Comment by kkokosa** [comment] 2021-01-19 13:16
What's the current status of this issue? Or in the other words - **how we can compile 5.0 version on Windows**? On a fresh `release/5.0` branch with 10.0.18362.0 SDK it is still the same:

```
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winbase.h(9305,5): warning C5105: macro expansion producing 'defined' has undefined behavior (compiling source file F:\Github\dotnet\original\runtime\artifacts\obj\coreclr\Windows_NT.x64.Debug\src\inc\idls_out\cordebug_i.c) 
...
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winbase.h(9305,5): error 
C2220: the following warning is treated as an error (compiling source file F:\Github\dotnet\original\runtime\artifacts\obj\coreclr\Windows_NT.x64.Debug\src\inc\idls_out\cordebug_i.c) 
...
```

**Comment by jashook** [comment] 2021-01-28 21:00
I can confirm that this issue also exists in release/3.1 and @GrabYourPitchforks change fixes the errors. /cc @trylek

**Comment by jashook** [comment] 2021-02-10 19:08
3.1 port -> https://github.com/dotnet/coreclr/pull/28142

**Comment by ViktorHofer** [comment] 2021-05-05 16:31
Closing as this should now be fixed in all branches that we care about.

**Closed by ViktorHofer** 2021-05-05 16:31 UTC
Labels: area-Infrastructure-coreclr
