### ISSUE TITLE
NativeAOT doesn't pass the app manifest to the linker

### ISSUE THREAD

**Issue by MichalPetryka** [dotnet/runtime#110798] opened 2024-12-18 03:27 UTC
### Description

.NET provides a default app manifest for the default host, that manifest isn't however embedded in apps built with NativeAOT.

### Reproduction Steps

Launch a NativeAOT app on Windows.
Enable the `Operating System Context` column in `Task Manager` details tab.
Check its value for the app.

### Expected behavior

See it be empty which indicates manifest supporting current version, same as it says for non NativeAOT apps.

### Actual behavior

See it say `Windows Vista` which indicates no manifest.

### Configuration

.NET 9
Windows 10 x64

**Comment by jkotas** [comment] 2024-12-18 04:14
Manifest is just a Win32 resource. NativeAOT copies all Win32 resources from the IL binary to the native binary.

> See it say Windows Vista which indicates no manifest.

If you run a regular .exe build using `dotnet build`, you should see the same behavior.

The behavior that you are seeing is duplicate of https://github.com/dotnet/sdk/issues/12904

**Comment by jkotas** [comment] 2024-12-18 04:41
Duplicate of https://github.com/dotnet/sdk/issues/12904

**Closed by jkotas** 2024-12-18 04:41 UTC
Labels: area-NativeAOT-coreclr
