### ISSUE TITLE
Linux armel fails to build on master.

### ISSUE THREAD

**Issue by ThadHouse** [dotnet/runtime#44082] opened 2020-10-30 19:21 UTC
### Description

Attempting to build armel following the directions at https://github.com/dotnet/runtime/blob/master/docs/workflow/building/coreclr/cross-building.md fails to build with the following errors.

```
make[2]: Entering directory '/home/thad/runtime/artifacts/obj/coreclr/Linux.armel.Debug'
cd /home/thad/runtime/artifacts/obj/coreclr/Linux.armel.Debug && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/thad/runtime/src/coreclr /home/thad/runtime/src/coreclr/src/jit/static /home/thad/runtime/artifacts/obj/coreclr/Linux.armel.Debug /home/thad/runtime/artifacts/obj/coreclr/Linux.armel.Debug/src/jit/static /home/thad/runtime/artifacts/obj/coreclr/Linux.armel.Debug/src/jit/static/CMakeFiles/clrjit_obj.dir/DependInfo.cmake --color=
Dependee "/home/thad/runtime/artifacts/obj/coreclr/Linux.armel.Debug/src/jit/static/CMakeFiles/clrjit_obj.dir/DependInfo.cmake" is newer than depender "/home/thad/runtime/artifacts/obj/coreclr/Linux.armel.Debug/src/jit/static/CMakeFiles/clrjit_obj.dir/depend.internal".
Dependee "/home/thad/runtime/artifacts/obj/coreclr/Linux.armel.Debug/src/jit/static/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/home/thad/runtime/artifacts/obj/coreclr/Linux.armel.Debug/src/jit/static/CMakeFiles/clrjit_obj.dir/depend.internal".
Scanning dependencies of target clrjit_obj
In file included from /home/thad/runtime/artifacts/obj/coreclr/Linux.armel.Debug/src/pal/src/eventprovider/lttngprovider/lttng/traceptprovdotnetruntimestress.cpp:14:
In file included from /home/thad/runtime/artifacts/obj/coreclr/Linux.armel.Debug/src/pal/src/eventprovider/lttngprovider/lttng/./tpdotnetruntimestress.h:128:
In file included from /home/armel/usr/include/lttng/tracepoint-event.h:58:
In file included from /home/armel/usr/include/lttng/ust-tracepoint-event.h:26:
In file included from /home/armel/usr/include/urcu/rculist.h:30:
In file included from /home/armel/usr/include/urcu-pointer.h:31:
In file included from /home/armel/usr/include/urcu/uatomic.h:41:
/home/armel/usr/include/urcu/uatomic/generic.h:75:10: error: address argument to atomic builtin must be a pointer to integer or pointer ('void *' invalid)
                return __sync_val_compare_and_swap_4(addr, old, _new);
                       ^                             ~~~~
/home/armel/usr/include/urcu/uatomic/generic.h:112:3: error: address argument to atomic builtin must be a pointer to integer or pointer ('void *' invalid)
                __sync_and_and_fetch_4(addr, val);
                ^                      ~~~~
/home/armel/usr/include/urcu/uatomic/generic.h:151:3: error: address argument to atomic builtin must be a pointer to integer or pointer ('void *' invalid)
                __sync_or_and_fetch_4(addr, val);
                ^                     ~~~~
/home/armel/usr/include/urcu/uatomic/generic.h:190:10: error: address argument to atomic builtin must be a pointer to integer or pointer ('void *' invalid)
                return __sync_add_and_fetch_4(addr, val);
                       ^                      ~~~~
4 errors generated.
```

This happens in a few for trace provider places as well.

### Configuration

Ubuntu 18.04 host. Running the following commands, just like explained in the workflow guide.

```
sudo apt-get install qemu qemu-user-static binfmt-support debootstrap
sudo apt-get install binutils-arm-linux-gnueabi
sudo ROOTFS_DIR=/home/armel ./eng/common/cross/build-rootfs.sh armel
ROOTFS_DIR=/home/armel ./src/coreclr/build-runtime.sh -armel -debug -verbose -cross

```

**Comment by jkotas** [comment] 2020-10-30 19:35
cc @dotnet/samsung

**Comment by jkotas** [comment] 2020-10-30 19:36
Duplicate of #7152  ?

**Comment by ThadHouse** [comment] 2020-10-30 19:41
That doesn't really show a fix, and the link to the patch file does not exist anymore.]

Note I'm explicitly not building Tizen.

**Comment by ThadHouse** [comment] 2020-10-30 19:43
Is there a flag for disabling tracing, so I can at least get a build?

**Comment by ThadHouse** [comment] 2020-10-30 20:01
I figured out I can pass ` -cmakeargs -DFEATURE_EVENT_TRACE=0` to the build to disable tracing, but then now get the following errors.

```
[ 67%] Building CXX object src/vm/wks/CMakeFiles/cee_wks_core.dir/__/arm/profiler.cpp.o
cd /home/thad/runtime/artifacts/obj/coreclr/Linux.armel.Debug/src/vm/wks && /usr/bin/clang++-6.0 --target=arm-linux-gnueabi --gcc-toolchain=/home/armel/usr --sysroot=/home/armel -DARM_SOFTFP -DBUILDENV_CHECKED=1 -DCLR_ARM_FPU_CAPABILITY=0x7 -DDEBUG -DDEBUGGING_SUPPORTED -DDISABLE_CONTRACTS -DFEATURE_ARRAYSTUB_AS_IL -DFEATURE_BASICFREEZE -DFEATURE_CODE_VERSIONING -DFEATURE_COLLECTIBLE_TYPES -DFEATURE_CORECLR -DFEATURE_CORESYSTEM -DFEATURE_DBGIPC_TRANSPORT_DI -DFEATURE_DBGIPC_TRANSPORT_VM -DFEATURE_DEFAULT_INTERFACES -DFEATURE_EH_FUNCLETS -DFEATURE_EMULATE_SINGLESTEP -DFEATURE_EVENTSOURCE_XPLAT -DFEATURE_HIJACK -DFEATURE_ICASTABLE -DFEATURE_INSTANTIATINGSTUB_AS_IL -DFEATURE_ISYM_READER -DFEATURE_MANAGED_ETW -DFEATURE_MANAGED_ETW_CHANNELS -DFEATURE_MULTICASTSTUB_AS_IL -DFEATURE_MULTICOREJIT -DFEATURE_PAL_ANSI -DFEATURE_PERFMAP -DFEATURE_PGO -DFEATURE_PORTABLE_SHUFFLE_THUNKS -DFEATURE_PROFAPI_ATTACH_DETACH -DFEATURE_READYTORUN -DFEATURE_REJIT -DFEATURE_REMOTE_PROC_MEM -DFEATURE_STANDALONE_GC -DFEATURE_STUBS_AS_IL -DFEATURE_SVR_GC -DFEATURE_SYMDIFF -DFEATURE_TIERED_COMPILATION -DFEATURE_USE_ASM_GC_WRITE_BARRIERS -DFEATURE_UTF8STRING -DHOST_ARM -DHOST_UNIX -DPROFILING_SUPPORTED -DTARGET_ARM -DTARGET_LINUX -DTARGET_UNIX -DUNICODE -DUNIX_ARM_ABI -DURTBLDENV_FRIENDLY=Checked -DWRITE_BARRIER_CHECK -D_BLD_CLR -D_DBG -D_DEBUG -D_SECURE_SCL=0 -D_UNICODE -I/home/thad/runtime/artifacts/obj/coreclr/Linux.armel.Debug/src/vm/wks -I/home/thad/runtime/src/coreclr/src/vm/wks -I/home/thad/runtime/src/coreclr/src/vm -I/home/thad/runtime/src/coreclr/src/pal/prebuilt/inc -I/home/thad/runtime/src/coreclr/../../artifacts/obj/coreclr -I/home/thad/runtime/src/coreclr/src/pal/inc -I/home/thad/runtime/src/coreclr/src/pal/inc/rt -I/home/thad/runtime/src/coreclr/src/pal/src/safecrt -I/home/thad/runtime/src/coreclr/src/inc -I/home/thad/runtime/src/coreclr/src/debug/inc -I/home/thad/runtime/src/coreclr/src/debug/inc/arm -I/home/thad/runtime/src/coreclr/src/debug/inc/dump -I/home/thad/runtime/src/coreclr/src/md/inc -I/home/thad/runtime/src/coreclr/src/classlibnative/bcltype -I/home/thad/runtime/src/coreclr/src/classlibnative/cryptography -I/home/thad/runtime/src/coreclr/src/classlibnative/inc -I/home/thad/runtime/artifacts/obj/coreclr/Linux.armel.Debug/src/inc -I/home/thad/runtime/src/coreclr/src/pal/inc/rt/cpp -I/home/thad/runtime/src/coreclr/src/nativeresources -I/home/thad/runtime/src/coreclr/src/vm/arm -I/home/thad/runtime/src/coreclr/src/vm/../interop/inc -g -fPIC -mthumb -mfpu=vfpv3 -mfloat-abi=softfp -O0 -g -Wall -Wno-null-conversion -fno-omit-frame-pointer -fms-extensions -fwrapv -fstack-protector-strong -Werror -Wno-unused-variable -Wno-unused-value -Wno-unused-function -Wno-tautological-compare -Wimplicit-fallthrough -Wno-invalid-offsetof -ferror-limit=4096 -Wno-unused-private-field -Wno-microsoft -Wno-constant-logical-operand -Wno-pragma-pack -Wno-unknown-warning-option -Wno-incompatible-ms-struct -fsigned-char -fvisibility=hidden -march=armv7-a -nostdinc -std=gnu++11 -o CMakeFiles/cee_wks_core.dir/__/arm/profiler.cpp.o -c /home/thad/runtime/src/coreclr/src/vm/arm/profiler.cpp
In file included from /home/thad/runtime/src/coreclr/src/vm/finalizerthread.cpp:10:
/home/thad/runtime/src/coreclr/src/vm/genanalysis.h:25:8: error: unknown type name 'EventPipeSession'
extern EventPipeSession* gcGenAnalysisEventPipeSession;
       ^
[ 67%] Building CXX object src/vm/wks/CMakeFiles/cee_wks_core.dir/__/exceptionhandling.cpp.o
cd /home/thad/runtime/artifacts/obj/coreclr/Linux.armel.Debug/src/vm/wks && /usr/bin/clang++-6.0 --target=arm-linux-gnueabi --gcc-toolchain=/home/armel/usr --sysroot=/home/armel -DARM_SOFTFP -DBUILDENV_CHECKED=1 -DCLR_ARM_FPU_CAPABILITY=0x7 -DDEBUG -DDEBUGGING_SUPPORTED -DDISABLE_CONTRACTS -DFEATURE_ARRAYSTUB_AS_IL -DFEATURE_BASICFREEZE -DFEATURE_CODE_VERSIONING -DFEATURE_COLLECTIBLE_TYPES -DFEATURE_CORECLR -DFEATURE_CORESYSTEM -DFEATURE_DBGIPC_TRANSPORT_DI -DFEATURE_DBGIPC_TRANSPORT_VM -DFEATURE_DEFAULT_INTERFACES -DFEATURE_EH_FUNCLETS -DFEATURE_EMULATE_SINGLESTEP -DFEATURE_EVENTSOURCE_XPLAT -DFEATURE_HIJACK -DFEATURE_ICASTABLE -DFEATURE_INSTANTIATINGSTUB_AS_IL -DFEATURE_ISYM_READER -DFEATURE_MANAGED_ETW -DFEATURE_MANAGED_ETW_CHANNELS -DFEATURE_MULTICASTSTUB_AS_IL -DFEATURE_MULTICOREJIT -DFEATURE_PAL_ANSI -DFEATURE_PERFMAP -DFEATURE_PGO -DFEATURE_PORTABLE_SHUFFLE_THUNKS -DFEATURE_PROFAPI_ATTACH_DETACH -DFEATURE_READYTORUN -DFEATURE_REJIT -DFEATURE_REMOTE_PROC_MEM -DFEATURE_STANDALONE_GC -DFEATURE_STUBS_AS_IL -DFEATURE_SVR_GC -DFEATURE_SYMDIFF -DFEATURE_TIERED_COMPILATION -DFEATURE_USE_ASM_GC_WRITE_BARRIERS -DFEATURE_UTF8STRING -DHOST_ARM -DHOST_UNIX -DPROFILING_SUPPORTED -DTARGET_ARM -DTARGET_LINUX -DTARGET_UNIX -DUNICODE -DUNIX_ARM_ABI -DURTBLDENV_FRIENDLY=Checked -DWRITE_BARRIER_CHECK -D_BLD_CLR -D_DBG -D_DEBUG -D_SECURE_SCL=0 -D_UNICODE -I/home/thad/runtime/artifacts/obj/coreclr/Linux.armel.Debug/src/vm/wks -I/home/thad/runtime/src/coreclr/src/vm/wks -I/home/thad/runtime/src/coreclr/src/vm -I/home/thad/runtime/src/coreclr/src/pal/prebuilt/inc -I/home/thad/runtime/src/coreclr/../../artifacts/obj/coreclr -I/home/thad/runtime/src/coreclr/src/pal/inc -I/home/thad/runtime/src/coreclr/src/pal/inc/rt -I/home/thad/runtime/src/coreclr/src/pal/src/safecrt -I/home/thad/runtime/src/coreclr/src/inc -I/home/thad/runtime/src/coreclr/src/debug/inc -I/home/thad/runtime/src/coreclr/src/debug/inc/arm -I/home/thad/runtime/src/coreclr/src/debug/inc/dump -I/home/thad/runtime/src/coreclr/src/md/inc -I/home/thad/runtime/src/coreclr/src/classlibnative/bcltype -I/home/thad/runtime/src/coreclr/src/classlibnative/cryptography -I/home/thad/runtime/src/coreclr/src/classlibnative/inc -I/home/thad/runtime/artifacts/obj/coreclr/Linux.armel.Debug/src/inc -I/home/thad/runtime/src/coreclr/src/pal/inc/rt/cpp -I/home/thad/runtime/src/coreclr/src/nativeresources -I/home/thad/runtime/src/coreclr/src/vm/arm -I/home/thad/runtime/src/coreclr/src/vm/../interop/inc -g -fPIC -mthumb -mfpu=vfpv3 -mfloat-abi=softfp -O0 -g -Wall -Wno-null-conversion -fno-omit-frame-pointer -fms-extensions -fwrapv -fstack-protector-strong -Werror -Wno-unused-variable -Wno-unused-value -Wno-unused-function -Wno-tautological-compare -Wimplicit-fallthrough -Wno-invalid-offsetof -ferror-limit=4096 -Wno-unused-private-field -Wno-microsoft -Wno-constant-logical-operand -Wno-pragma-pack -Wno-unknown-warning-option -Wno-incompatible-ms-struct -fsigned-char -fvisibility=hidden -march=armv7-a -nostdinc -std=gnu++11 -o CMakeFiles/cee_wks_core.dir/__/exceptionhandling.cpp.o -c /home/thad/runtime/src/coreclr/src/vm/exceptionhandling.cpp
/home/thad/runtime/src/coreclr/src/vm/finalizerthread.cpp:270:13: error: use of undeclared identifier 'EventPipe'
            EventPipe::Disable(gcGenAnalysisEventPipeSessionId);
            ^
[ 67%] Building CXX object src/vm/wks/CMakeFiles/cee_wks_core.dir/__/gcinfodecoder.cpp.o
cd /home/thad/runtime/artifacts/obj/coreclr/Linux.armel.Debug/src/vm/wks && /usr/bin/clang++-6.0 --target=arm-linux-gnueabi --gcc-toolchain=/home/armel/usr --sysroot=/home/armel -DARM_SOFTFP -DBUILDENV_CHECKED=1 -DCLR_ARM_FPU_CAPABILITY=0x7 -DDEBUG -DDEBUGGING_SUPPORTED -DDISABLE_CONTRACTS -DFEATURE_ARRAYSTUB_AS_IL -DFEATURE_BASICFREEZE -DFEATURE_CODE_VERSIONING -DFEATURE_COLLECTIBLE_TYPES -DFEATURE_CORECLR -DFEATURE_CORESYSTEM -DFEATURE_DBGIPC_TRANSPORT_DI -DFEATURE_DBGIPC_TRANSPORT_VM -DFEATURE_DEFAULT_INTERFACES -DFEATURE_EH_FUNCLETS -DFEATURE_EMULATE_SINGLESTEP -DFEATURE_EVENTSOURCE_XPLAT -DFEATURE_HIJACK -DFEATURE_ICASTABLE -DFEATURE_INSTANTIATINGSTUB_AS_IL -DFEATURE_ISYM_READER -DFEATURE_MANAGED_ETW -DFEATURE_MANAGED_ETW_CHANNELS -DFEATURE_MULTICASTSTUB_AS_IL -DFEATURE_MULTICOREJIT -DFEATURE_PAL_ANSI -DFEATURE_PERFMAP -DFEATURE_PGO -DFEATURE_PORTABLE_SHUFFLE_THUNKS -DFEATURE_PROFAPI_ATTACH_DETACH -DFEATURE_READYTORUN -DFEATURE_REJIT -DFEATURE_REMOTE_PROC_MEM -DFEATURE_STANDALONE_GC -DFEATURE_STUBS_AS_IL -DFEATURE_SVR_GC -DFEATURE_SYMDIFF -DFEATURE_TIERED_COMPILATION -DFEATURE_USE_ASM_GC_WRITE_BARRIERS -DFEATURE_UTF8STRING -DHOST_ARM -DHOST_UNIX -DPROFILING_SUPPORTED -DTARGET_ARM -DTARGET_LINUX -DTARGET_UNIX -DUNICODE -DUNIX_ARM_ABI -DURTBLDENV_FRIENDLY=Checked -DWRITE_BARRIER_CHECK -D_BLD_CLR -D_DBG -D_DEBUG -D_SECURE_SCL=0 -D_UNICODE -I/home/thad/runtime/artifacts/obj/coreclr/Linux.armel.Debug/src/vm/wks -I/home/thad/runtime/src/coreclr/src/vm/wks -I/home/thad/runtime/src/coreclr/src/vm -I/home/thad/runtime/src/coreclr/src/pal/prebuilt/inc -I/home/thad/runtime/src/coreclr/../../artifacts/obj/coreclr -I/home/thad/runtime/src/coreclr/src/pal/inc -I/home/thad/runtime/src/coreclr/src/pal/inc/rt -I/home/thad/runtime/src/coreclr/src/pal/src/safecrt -I/home/thad/runtime/src/coreclr/src/inc -I/home/thad/runtime/src/coreclr/src/debug/inc -I/home/thad/runtime/src/coreclr/src/debug/inc/arm -I/home/thad/runtime/src/coreclr/src/debug/inc/dump -I/home/thad/runtime/src/coreclr/src/md/inc -I/home/thad/runtime/src/coreclr/src/classlibnative/bcltype -I/home/thad/runtime/src/coreclr/src/classlibnative/cryptography -I/home/thad/runtime/src/coreclr/src/classlibnative/inc -I/home/thad/runtime/artifacts/obj/coreclr/Linux.armel.Debug/src/inc -I/home/thad/runtime/src/coreclr/src/pal/inc/rt/cpp -I/home/thad/runtime/src/coreclr/src/nativeresources -I/home/thad/runtime/src/coreclr/src/vm/arm -I/home/thad/runtime/src/coreclr/src/vm/../interop/inc -g -fPIC -mthumb -mfpu=vfpv3 -mfloat-abi=softfp -O0 -g -Wall -Wno-null-conversion -fno-omit-frame-pointer -fms-extensions -fwrapv -fstack-protector-strong -Werror -Wno-unused-variable -Wno-unused-value -Wno-unused-function -Wno-tautological-compare -Wimplicit-fallthrough -Wno-invalid-offsetof -ferror-limit=4096 -Wno-unused-private-field -Wno-microsoft -Wno-constant-logical-operand -Wno-pragma-pack -Wno-unknown-warning-option -Wno-incompatible-ms-struct -fsigned-char -fvisibility=hidden -march=armv7-a -nostdinc -std=gnu++11 -o CMakeFiles/cee_wks_core.dir/__/gcinfodecoder.cpp.o -c /home/thad/runtime/src/coreclr/src/vm/gcinfodecoder.cpp
2 errors generated.
src/vm/wks/CMakeFiles/cee_wks_core.dir/build.make:2083: recipe for target 'src/vm/wks/CMakeFiles/cee_wks_core.dir/__/finalizerthread.cpp.o' failed
make[2]: *** [src/vm/wks/CMakeFiles/cee_wks_core.dir/__/finalizerthread.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/thad/runtime/src/coreclr/src/vm/genanalysis.cpp:5:
/home/thad/runtime/src/coreclr/src/vm/genanalysis.h:25:8: error: unknown type name 'EventPipeSession'
extern EventPipeSession* gcGenAnalysisEventPipeSession;
       ^
/home/thad/runtime/src/coreclr/src/vm/genanalysis.cpp:8:1: error: unknown type name 'EventPipeSession'
EventPipeSession* gcGenAnalysisEventPipeSession = nullptr;
^
In file included from /home/thad/runtime/src/coreclr/src/vm/gcenv.ee.static.cpp:18:
/home/thad/runtime/src/coreclr/src/vm/genanalysis.h:25:8: error: unknown type name 'EventPipeSession'
extern EventPipeSession* gcGenAnalysisEventPipeSession;
       ^
/home/thad/runtime/src/coreclr/src/vm/genanalysis.cpp:61:15: error: use of undeclared identifier 'EventPipeProviderConfiguration'
    NewHolder<EventPipeProviderConfiguration> pProviders = nullptr;
              ^
/home/thad/runtime/src/coreclr/src/vm/genanalysis.cpp:63:5: error: use of undeclared identifier 'pProviders'
    pProviders = new EventPipeProviderConfiguration[providerCnt];
    ^
In file included from /home/thad/runtime/src/coreclr/src/vm/gcenv.ee.static.cpp:29:
/home/thad/runtime/src/coreclr/src/vm/gcenv.ee.cpp:1613:13: error: use of undeclared identifier 'FireEtwGenAwareBegin'
            FireEtwGenAwareBegin((int)gcIndex, GetClrInstanceId());
            ^
/home/thad/runtime/src/coreclr/src/vm/genanalysis.cpp:63:22: error: unknown type name 'EventPipeProviderConfiguration'
    pProviders = new EventPipeProviderConfiguration[providerCnt];
                     ^
/home/thad/runtime/src/coreclr/src/vm/genanalysis.cpp:69:5: error: use of undeclared identifier 'pProviders'
    pProviders[0] = EventPipeProviderConfiguration(W("Microsoft-Windows-DotNETRuntime"), keyword, 5, nullptr);
    ^
/home/thad/runtime/src/coreclr/src/vm/gcenv.ee.cpp:1618:13: error: use of undeclared identifier 'FireEtwGenAwareEnd'
            FireEtwGenAwareEnd((int)gcIndex, GetClrInstanceId());
            ^
/home/thad/runtime/src/coreclr/src/vm/genanalysis.cpp:69:21: error: use of undeclared identifier 'EventPipeProviderConfiguration'
    pProviders[0] = EventPipeProviderConfiguration(W("Microsoft-Windows-DotNETRuntime"), keyword, 5, nullptr);
                    ^
/home/thad/runtime/src/coreclr/src/vm/genanalysis.cpp:70:39: error: use of undeclared identifier 'EventPipe'
    gcGenAnalysisEventPipeSessionId = EventPipe::Enable(
                                      ^
/home/thad/runtime/src/coreclr/src/vm/genanalysis.cpp:75:9: error: use of undeclared identifier 'EventPipeSessionType'
3        EventPipeSessionType::File,
 errors        ^ generated
.
src/vm/wks/CMakeFiles/cee_wks_core.dir/build.make:2109: recipe for target 'src/vm/wks/CMakeFiles/cee_wks_core.dir/__/gcenv.ee.static.cpp.o' failed
make[2]: *** [src/vm/wks/CMakeFiles/cee_wks_core.dir/__/gcenv.ee.static.cpp.o] Error 1
/home/thad/runtime/src/coreclr/src/vm/genanalysis.cpp:76:9: error: use of undeclared identifier 'EventPipeSerializationFormat'
        EventPipeSerializationFormat::NetTraceV4,
        ^
/home/thad/runtime/src/coreclr/src/vm/genanalysis.cpp:73:9: error: use of undeclared identifier 'pProviders'; did you mean 'providerCnt'?
        pProviders,
        ^~~~~~~~~~
        providerCnt
/home/thad/runtime/src/coreclr/src/vm/genanalysis.cpp:62:9: note: 'providerCnt' declared here
    int providerCnt = 1;
        ^
/home/thad/runtime/src/coreclr/src/vm/genanalysis.cpp:82:40: error: use of undeclared identifier 'EventPipe'
        gcGenAnalysisEventPipeSession= EventPipe::GetSession(gcGenAnalysisEventPipeSessionId);
                                       ^
/home/thad/runtime/src/coreclr/src/vm/genanalysis.cpp:84:9: error: use of undeclared identifier 'EventPipe'
        EventPipe::StartStreaming(gcGenAnalysisEventPipeSessionId);
        ^
13 errors generated.
src/vm/wks/CMakeFiles/cee_wks_core.dir/build.make:2161: recipe for target 'src/vm/wks/CMakeFiles/cee_wks_core.dir/__/genanalysis.cpp.o' failed
make[2]: *** [src/vm/wks/CMakeFiles/cee_wks_core.dir/__/genanalysis.cpp.o] Error 1
In file included from /home/thad/runtime/src/coreclr/src/vm/gcenv.ee.standalone.cpp:18:
/home/thad/runtime/src/coreclr/src/vm/genanalysis.h:25:8: error: unknown type name 'EventPipeSession'
extern EventPipeSession* gcGenAnalysisEventPipeSession;
       ^
In file included from /home/thad/runtime/src/coreclr/src/vm/gcenv.ee.standalone.cpp:32:
/home/thad/runtime/src/coreclr/src/vm/gcenv.ee.cpp:1613:13: error: use of undeclared identifier 'FireEtwGenAwareBegin'
            FireEtwGenAwareBegin((int)gcIndex, GetClrInstanceId());
            ^
/home/thad/runtime/src/coreclr/src/vm/gcenv.ee.cpp:1618:13: error: use of undeclared identifier 'FireEtwGenAwareEnd'
            FireEtwGenAwareEnd((int)gcIndex, GetClrInstanceId());
            ^
3 errors generated.
```

**Comment by ThadHouse** [comment] 2020-10-30 20:29
I figured out how to patch generic.h to fix the issue with tracing providers. Still not great it breaks immediately. Now to figure out what to deploy to my device to test.

**Comment by ThadHouse** [comment] 2020-10-31 02:24
Getting further now. I can build all of coreclr and lib, but I cannot build corehost, because the root fs that got generated for armel doesn't have codecvt.

**Closed** 2020-11-12 14:50 UTC
Labels: arch-arm32, area-Tracing-coreclr
