### ISSUE TITLE
crossgen-comparison Linux arm checked fails with timeouts

### ISSUE THREAD

**Issue by sandreenko** [dotnet/runtime#1282] opened 2020-01-03 19:35 UTC
It happens in all runs, the timeout is 60 minutes. We have not seen that in coreclr.

cc @echesakovMSFT @BruceForstall 
<details>

Log example:
```
Starting: Run native crossgen and compare output to baseline (Unix)
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.151.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
$BUILD_SOURCESDIRECTORY/eng/common/msbuild.sh $BUILD_SOURCESDIRECTORY/eng/common/helixpublish.proj /restore /t:Test /bl:$BUILD_SOURCESDIRECTORY/artifacts/log/$BuildConfig/SendToHelix.binlog
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /__w/_temp/7553b9eb-4204-4db6-9f64-3d08371fe862.sh
/__w/3/s/.dotnet/sdk/5.0.100-alpha1-015772/MSBuild.dll /nologo -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,/__w/3/s/.dotnet/sdk/5.0.100-alpha1-015772/dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,/__w/3/s/.dotnet/sdk/5.0.100-alpha1-015772/dotnet.dll -maxcpucount /m -verbosity:m /v:minimal /bl:/__w/3/s/artifacts/log/Checked/SendToHelix.binlog /clp:Summary /nr:true /p:TreatWarningsAsErrors=true /p:ContinuousIntegrationBuild=false /restore /t:Test /warnaserror /__w/3/s/eng/common/helixpublish.proj
  Restore completed in 599.36 ms for /__w/3/s/eng/common/helixpublish.proj.
  Restore completed in 2.35 ms for /__w/3/s/eng/common/helixpublish.proj.
  Starting Azure Pipelines Test Run (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-30f6673-20190814153226
  Uploading payloads for Job on (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-30f6673-20190814153226...
  Finished uploading payloads for Job on (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-30f6673-20190814153226...
  Sending Job to (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-30f6673-20190814153226...
  Sent Helix Job 40b0be17-33d6-41c3-bdce-fd02aba91a98
  Waiting for completion of job 40b0be17-33d6-41c3-bdce-fd02aba91a98
##[error]The operation was canceled.
Finishing: Run native crossgen and compare output to baseline (Unix)
```

https://dev.azure.com/dnceng/public/_build/results?buildId=471248
</details>

**Comment by BruceForstall** [comment] 2020-01-03 19:45
Is this a regression, or has it always failed in `runtime`?

**Comment by sandreenko** [comment] 2020-01-03 19:51
I saw it green a few times, for example here https://dev.azure.com/dnceng/public/_build/results?buildId=456520&view=logs&j=e14ed261-6507-56f9-47b6-1ad25f52112f.

**Comment by jashook** [comment] 2020-01-03 23:36
Generally this is failure happens due to us running at capacity for the helix queue. With the amount of machines that were added last month, there is most likely something that has changed with what jobs are submitted and from where to cause this, or there are a lot of machine that have gone offline.

**Comment by jashook** [comment] 2020-01-03 23:38
> Is this a regression, or has it always failed in `runtime`?

This has not always failed, although the amount of jobs submitted has probably increased this month over last month.

**Comment by sandreenko** [comment] 2020-01-03 23:40
Thanks, @jashook . We can make a quick surgical fix and stop running everything twice (under runtime and under runtime-coreclr pipelines, delete duplicated from https://github.com/dotnet/runtime/blob/master/eng/pipelines/runtime-official.yml and https://github.com/dotnet/runtime/blame/master/eng/pipelines/coreclr/pr.yml) or wait for a few weeks when @safern replaces existing pipelines.

**Comment by jashook** [comment] 2020-01-03 23:51
Seems like the wait times are not too high in the queue, if I remember right these jobs ran close to the timeout. I would suggest upping the timeout by 15 to 30 minutes.

**Comment by safern** [comment] 2020-01-06 19:04
>or wait for a few weeks when @safern replaces existing pipelines.

I should be removing duplication this week. Hope to have a PR before Wednesday.

**Comment by safern** [comment] 2020-01-16 01:15
I just merged: https://github.com/dotnet/runtime/pull/1473 which removes the duplication of pipelines and it will now only be ran once per PR and once on CI. Will leave this open to monitor the outcome after this change and react if needed.

**Comment by jaredpar** [comment] 2020-02-25 21:25
This is presently impacting about 9% of our builds

|Build|Kind|Timeline Record|
|---|---|---|
|[534481](https://dev.azure.com/dnceng/public/_build/results?buildId=534481)|PR https://github.com/dotnet/runtime/pull/2107|Test crossgen-comparison Linux arm checked|
|[534999](https://dev.azure.com/dnceng/public/_build/results?buildId=534999)|PR https://github.com/dotnet/runtime/pull/2107|Test crossgen-comparison Linux arm checked|
|[535931](https://dev.azure.com/dnceng/public/_build/results?buildId=535931)|PR https://github.com/dotnet/runtime/pull/32402|Test crossgen-comparison Linux arm checked|
|[535806](https://dev.azure.com/dnceng/public/_build/results?buildId=535806)|PR https://github.com/dotnet/runtime/pull/32794|Test crossgen-comparison Linux arm checked|
|[534710](https://dev.azure.com/dnceng/public/_build/results?buildId=534710)|PR https://github.com/dotnet/runtime/pull/32762|Test crossgen-comparison Linux arm checked|
|[534703](https://dev.azure.com/dnceng/public/_build/results?buildId=534703)|PR https://github.com/dotnet/runtime/pull/32330|Test crossgen-comparison Linux arm checked|
|[534497](https://dev.azure.com/dnceng/public/_build/results?buildId=534497)|PR https://github.com/dotnet/runtime/pull/32499|Test crossgen-comparison Linux arm checked|
|[534413](https://dev.azure.com/dnceng/public/_build/results?buildId=534413)|PR https://github.com/dotnet/runtime/pull/32626|Test crossgen-comparison Linux arm checked|
|[534345](https://dev.azure.com/dnceng/public/_build/results?buildId=534345)|Rolling|Test crossgen-comparison Linux arm checked|

**Comment by BruceForstall** [comment] 2020-02-25 21:47
@jashook You thought before that this was failing due to overloaded Linux arm hardware, leading to the timeouts. Do you still believe that?

**Comment by jashook** [comment] 2020-02-25 21:48
Yes, I think there is more pressure on the hardware with mono running arm now.

**Comment by echesakovMSFT** [comment] 2020-02-28 01:32
It look that we missed a real regression in crossgen_comparison due to our inability to run this test without timing out https://github.com/dotnet/runtime/issues/32951

@jashook Can we increase timeouts for this job?

**Comment by jaredpar** [comment] 2020-03-02 18:54
Removing blocking label now that mitigations are in place.

**Comment by ViktorHofer** [comment] 2020-03-02 19:13
Is this issue still actionable now that the mitigation is in place? Should we open another issue or link to an existing one which tracks the ARM hardware capacity issue?

**Closed** 2020-03-02 20:42 UTC
Labels: area-Infrastructure-coreclr, untriaged

**Comment by BruceForstall** [comment] 2021-03-02 17:11
@echesakovMSFT I noticed that the crossgen-comparison job is still commented out in ci.yml, so it's not running in the outerloop job. Should we fix that?

**Comment by echesakovMSFT** [comment] 2021-03-03 20:01
@BruceForstall I think it is okay. 

We still have crossgen-comparison job triggered in PRs (if they affect code under src/coreclr). One of the latest runs is green - https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-48830-merge-9b43a99dd41241aaa5/WorkItem/console.42781747.log?sv=2019-07-07&se=2021-03-23T08%3A59%3A24Z&sr=c&sp=rl&sig=Eu7gjhAYzP2ozwKcOMC%2FsAzV9caUqAe2qehEdfwvEjM%3D

In addition to that, @davidwrighton added crossgen2-outerloop pipeline that I believe runs similar comparison jobs but with crossgen2. In theory, the changes that break JIT cross-bitness, cross-architecture or cross-os compatibility should be caught by these jobs. In reality, these jobs have been red for a while (e.g. https://dev.azure.com/dnceng/public/_build?definitionId=701). I opened #49077 to track the issue.

**Comment by davidwrighton** [comment] 2021-03-03 22:01
@echesakovMSFT I intend to get around to fixing some of those crossgen2 comparision issues soon.

**Comment by echesakovMSFT** [comment] 2021-03-03 23:19
@davidwrighton Thank you, David!
