### ISSUE TITLE
Test failure: System.Reflection.PortableExecutable.Tests.PEBuilderTests.NativeResources

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#102979] opened 2024-06-03 02:10 UTC
**Failed in:** [runtime-coreclr libraries-jitstressregs 20240602.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=695102&view=ms.vss-test-web.build-test-results-tab&runId=17271082&resultId=122484&paneView=debug)

**Failed tests:**
```
net9.0-windows-Release-arm64-jitstressregs3-Windows.11.Arm64.Open
    - System.Reflection.PortableExecutable.Tests.PEBuilderTests.NativeResources
```

**Error message:**
```
 Assert.Equal() Failure: Values differ
Expected: 1024
Actual:   -572662307
```

**Stack trace:**
```
   at System.Reflection.PortableExecutable.Tests.PEBuilderTests.NativeResources() in /_/src/libraries/System.Reflection.Metadata/tests/PortableExecutable/PEBuilderTests.cs:line 626
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBaseInvoker.cs:line 57
```

**Comment by TIHan** [comment] 2024-08-06 23:15
Not able to reproduce this issue with the specified JitStressRegs:
```
C:\Users\dotnetperfuser\Desktop\work>set DOTNET
DOTNET_JitStressRegs=3

C:\Users\dotnetperfuser\Desktop\work>C:\Users\dotnetperfuser\Desktop\work\windows.arm64.Checked\Tests\Core_Root\corerun.exe "C:\Users\dotnetperfuser\Desktop\work\net9.0\xunit.console.dll" "C:\Users\dotnetperfuser\Desktop\work\net9.0\System.Reflection.Metadata.Tests.dll" -method "System.Reflection.PortableExecutable.Tests.PEBuilderTests.NativeResources"
Microsoft.DotNet.XUnitConsoleRunner v2.9.0.0 (64-bit .NET 9.0.0-dev)
  Discovering: System.Reflection.Metadata.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Reflection.Metadata.Tests (found 1 of 547 test case)
  Starting:    System.Reflection.Metadata.Tests (parallel test collections = on [16 threads], stop on fail = off)
  Finished:    System.Reflection.Metadata.Tests
=== TEST EXECUTION SUMMARY ===
   System.Reflection.Metadata.Tests  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 0.540s

C:\Users\dotnetperfuser\Desktop\work>C:\Users\dotnetperfuser\Desktop\work\windows.arm64.Checked\Tests\Core_Root\corerun.exe "C:\Users\dotnetperfuser\Desktop\work\net9.0\xunit.console.dll" "C:\Users\dotnetperfuser\Desktop\work\net9.0\System.Reflection.Metadata.Tests.dll" -method "System.Reflection.PortableExecutable.Tests.PEBuilderTests.NativeResources"
Microsoft.DotNet.XUnitConsoleRunner v2.9.0.0 (64-bit .NET 9.0.0-dev)
  Discovering: System.Reflection.Metadata.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Reflection.Metadata.Tests (found 1 of 547 test case)
  Starting:    System.Reflection.Metadata.Tests (parallel test collections = on [16 threads], stop on fail = off)
  Finished:    System.Reflection.Metadata.Tests
=== TEST EXECUTION SUMMARY ===
   System.Reflection.Metadata.Tests  Total: 1, Errors: 0, Failed: 0, Skipped: 0, Time: 0.501s
```

Latest CI runs for `net9.0-windows-Release-arm64-jitstressregs3-Windows.11.Arm64.Open` also show tests in `System.Reflection.Metadata.Tests` are passing.

Closing as it has not reproduceable and not currently occurring in CI.

**Closed by TIHan** 2024-08-06 23:15 UTC
Labels: arch-arm64, os-windows, JitStress, area-CodeGen-coreclr, blocking-clean-ci-optional, Priority:2
