### ISSUE TITLE
String should still implement IReadOnlyList<char>

### ISSUE THREAD

**Issue by DS-AdamMilazzo** [dotnet/runtime#97954] opened 2024-02-05 01:44 UTC
### Background and motivation

There are many APIs that take IReadOnlyList\<T\>. For some of them, passing a string would be perfectly natural. For example, I'm calling a function that computes the diff between two sequences. Passing two strings and having it compute the diff between the two strings would be a natural use of the API, except that string vexingly doesn't implement IReadOnlyList\<char\>. The direct cost of implementing IReadOnlyList\<char\> would seem to be extremely low, since all members are already implemented except Count, which could be implicitly implemented as `int IReadOnlyCollection<char>.Count => Length;`.

This was discussed briefly in #19609. The suggestion was to use ReadOnlySpan\<T\> instead. However, that is not a good workaround in general, for a variety of reasons. Of course, one could also call String.ToCharArray(), but that is inefficient.

### Why to implement IReadOnlyList\<char\>
* A string is logically a read-only list of `char`, so much so that the entire interface is already implemented except for the naming difference between Length and Count.
* Many existing APIs use IReadOnlyList\<T\>, and it would be nice to be able to use string there. This is a tangible benefit.
* The direct cost would seem to be trivial.

### Why ReadOnlySpan\<char\> is not a suitable replacement
* ReadOnlySpan\<char\>, as a ref struct, has restrictions on where it can stored, preventing it from being used in a number of places where an IReadOnlyList\<char\> or a string can be used. This means that many pieces of code currently using IReadOnlyList\<T\> cannot be easily converted to use ReadOnlySpan\<T\>, or cannot be converted at all. So we'll consider ReadOnlyMemory\<char\> as well.
* The fact that an existing API _could_ be rewritten to use ReadOnlyMemory\<T\> or ReadOnlySpan\<T\> does not help unless it will actually be rewritten to do so, and there are significant hurdles, both because the code may not be under one's control, and for technical reasons, some of which are described below.
* ReadOnlyMemory\<T\> is significantly different from IReadOnlyList\<T\>. As its documentation says, it "represents a contiguous region of memory", whereas IReadOnlyList\<T\> is more general than that. Some existing IReadOnlyList\<T\> implementations do not store all the items in a contiguous region of memory and so cannot be efficiently converted to ReadOnlyMemory\<T\>. Generally speaking, code that makes extensive use of IReadOnlyList\<T\> cannot be converted to also work with ReadOnlyMemory\<T\> without duplicating a lot of code or adding wrappers.
* Unlike IReadOnlyList\<T\>, ReadOnlyMemory\<T\> is not directly indexable. It must first be converted to a ReadOnlySpan\<T\>, which appears to introduce a significant amount of extra code into the code path for retrieving a single element compared to IReadOnlyList\<T\>, which is just a virtual method call, and many use cases will require doing the Memory -> Span conversion for every lookup.
* While it's possible to write an IReadOnlyList\<T\> wrapper around ReadOnlyMemory\<T\>, it's non-trivial (though not difficult), less efficient than a native IReadOnlyList\<T\>, and a burden that could easily be avoided if String simply implemented IReadOnlyList\<T\>.

### API Proposal

```csharp
public sealed class String : ..., IReadOnlyList<char>
{
    int IReadOnlyCollection<char>.Count => Length;
}
```

### API Usage

```csharp
string a = GetStringA(), b = GetStringB();
Diff d = Diff.Compute(a, b); // where Diff.Compute<T> takes IReadOnlyList<T>
```

### Alternative Designs

One alternative would be to make ReadOnlyMemory\<T\> implement IReadOnlyList\<T\>. This is more general, but more costly. I would say that the two changes are not mutually exclusive. ReadOnlyMemory\<T\> would benefit from implementing IReadOnlyList\<T\> for the same reason that String would.

### Risks

I am not aware of any significant risks, Of course, as a result of this change, String would be implicitly convertible to IReadOnlyList\<T\> whereas today it is not. If somebody had method overrides like:

```csharp
static void Foo<T>(IReadOnlyList<T> list);
static void Foo<T>(IEnumerable<T> list);
```
then calling `Foo(str)` would become ambiguous where today it is not. I doubt this would affect many people, and I think such people would be glad to have String able to be passed to the presumably more efficient IReadOnlyList\<T\> override, but it would require a cast.

Similarly, if somebody is really depending on String _not_ implementing IReadOnlyList\<T\> it would disturb their logic, but I don't think people should make such assumptions.

**Comment by campersau** [comment] 2024-02-05 11:08
See also #91756

**Comment by Neme12** [comment] 2024-05-04 23:13
This is a duplicate of #91756, so I think this issue should be closed in favor of the other one. But feel free to add any of your additional arguments from this proposal in the comments of the other issue too, and upvote it as well.

**Comment by jkotas** [comment] 2024-05-07 16:06
Closed as duplicate of https://github.com/dotnet/runtime/issues/91756

**Closed** 2024-05-07 16:06 UTC
Labels: api-suggestion, area-System.Runtime, untriaged
