### ISSUE TITLE
System.Private.CoreLib.ni.pdb keeps growing

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#35489] opened 2020-04-26 17:17 UTC
Compiling the runtime multiple times causes `System.Private.CoreLib.ni.pdb` in `runtime\artifacts\bin\coreclr\Windows_NT.x64.Release\PDB` to keep growing and growing.

Its like its doing append rather then overwrite?

**Comment by GrabYourPitchforks** [comment] 2020-04-26 19:42
What specific subset are you building? clr, clr.corelib+clr.nativecorelib, or some different combination? I wonder if a _clean_ step is being missed somewhere.

**Comment by benaadams** [comment] 2020-04-26 20:47
`build -subset Clr -c Release`

if I build 

`build -subset Clr.CoreLib -c Release`

It only builds `D:\GitHub\runtime\artifacts\bin\coreclr\Windows_NT.x64.Release\IL\System.Private.CoreLib.dll`

and doesn't update the R2R
`runtime\artifacts\bin\coreclr\Windows_NT.x64.Release\System.Private.CoreLib.dll` or generate the `.ni.pdb`

**Comment by trylek** [comment] 2021-03-02 18:55
The current POR is to make Crossgen2 the default in .NET 6 and obsoleting Crossgen[1] so this is probably not worth fixing at this point; /cc @dotnet/crossgen-contrib for additional feedback.

**Comment by trylek** [comment] 2021-03-02 18:58
I have changed the label - while the problem is caused by a somewhat silly behavior of DiaSymReader that I had to fix myself for Crossgen2, I believe this is logically a bug in the crossgen native app, not in the surrounding infrastructure.

**Comment by mangod9** [comment] 2021-07-21 02:15
Closing since crossgen is no longer used. Assume this is not an issue in crossgen2, please reactivate if it is.

**Closed by mangod9** 2021-07-21 02:15 UTC
Labels: area-CrossGen/NGEN-coreclr
