### ISSUE TITLE
Proposal: Add Caching to Expression.Property by MethodInfo

### ISSUE THREAD

**Issue by HaloFour** [dotnet/runtime#2011] opened 2020-01-22 14:28 UTC
C# makes heavy use of overload `MemberExpression Property(Expression, MethodInfo)` when generating expression trees using LINQ.  For every invocation this method needs to loop through the properties of the type and compare the method against the property accessor methods, which can be expensive particularly on large types.

I suggest that `System.Linq.Expressions.MemberExpression` maintain a cache of resolved properties by `MethodInfo`.  This would eliminate the cost of having to do the lookup every time the compiler is generating an expression tree over the same type/properties.

**Comment by svick** [comment] 2020-01-22 17:27
According to https://github.com/dotnet/corefx/issues/33170:

> There are several packages in dotnet/corefx where the package and supporting language features are mature and no longer evolving, and where the risk of code change likely exceeds the benefit. Those packages should be effectively archived.
>
> […]
>
> When archived, we would not accept features contributions to the packages. We would consider changes that address significant bugs or regressions, or changes that are necessary to continue shipping the binaries. Other changes will be rejected.

Since System.Linq.Expressions is one of the listed packages and assuming the above is still accurate, then I think you would have a hard time getting such change accepted.

**Comment by HaloFour** [comment] 2020-01-22 17:40
Understood, but it never hurts to ask.  If the ask is to change how the C# generates expression trees vs. improve the current method to be faster, I'd lean strongly towards the latter.

**Comment by jaredpar** [comment] 2020-07-09 00:04
Closing as this is a feature request. This library is effectively archived and new features do not meet the [bar](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Linq.Expressions/README.md) for changes.

**Closed by jaredpar** 2020-07-09 00:04 UTC
Labels: area-System.Linq.Expressions, untriaged

**Comment by jnm2** [comment] 2020-11-26 19:40
This Expression.Lambda performance regression from .NET Framework to .NET Core is being fixed: https://github.com/dotnet/corefx/pull/42874
Even though this Expression.Property isn't a regression, expressions are used possibly as much as regex and regex has recently received perf improvements. For things whose usage is certainly not going to diminish, accepting performance improvements across the board seems like a win.
