### ISSUE TITLE
System.Text.RegularExpressions test fails on Browser wasm

### ISSUE THREAD

**Issue by mdh1418** [dotnet/runtime#39480] opened 2020-07-16 22:54 UTC
`CharactersComparedOneByOne_Invariant` in `RegexCultureTests.cs` fails when running library tests on Browser with
```
Assert.StartsWith() Failure:
Expected: Ö‍
Actual:   Ö
```

**Comment by safern** [comment] 2020-07-17 00:58
I think this is the expected behavior on `GlobalizationMode.Invariant` and that test run was done in invariant mode. If I run these tests on any runtime on Invariant mode I get the same result. See: https://github.com/dotnet/runtime/pull/39470#discussion_r456159087

cc: @tarekgh

**Comment by tarekgh** [comment] 2020-07-17 01:07
I am a little bit confused here. the description of the issue is showing the expected result matching the actual result. no?

**Comment by safern** [comment] 2020-07-17 01:13
because the unicode points are different but the console is showing it correctly cause it understands unicode.

**Comment by tarekgh** [comment] 2020-07-17 01:18
> but the console is showing it correctly cause it understands unicode.

Usually this happen visually and not really changing the underlying Unicode codepoint. so I expect still to be 2 different strings even if they are showing same. but this is not the case here as the underlying string are exactly same. do you have a pointer to the test case?

**Comment by safern** [comment] 2020-07-17 01:20
This is the line that is failing:

https://github.com/dotnet/runtime/blob/6072e4d3a7a2a1493f514cdf4be75a3d56580e84/src/libraries/System.Text.RegularExpressions/tests/RegexCultureTests.cs#L48

The two unicode points are: u004F and u00D6

**Comment by tarekgh** [comment] 2020-07-17 01:37
The part I don't understand is who converted `\u004F\u0308` to `\u00D6`? to clarify more I would expect the text displayed as `Ö` which actually 2 codepoints `\u004F\u0308` and not just `\u00D6`.

**Comment by safern** [comment] 2020-07-17 01:57
I see, I believe the problem is in Xunit itself. The exception is constructed with the string itself:
https://github.com/xunit/assert.xunit/blob/3af483c3e851ef4f463a8ce8b9399b7bc8ab4dc0/StringAsserts.cs#L115

And then Xunit is setting the exception message with those strings which will be the full underlying strings:
https://github.com/xunit/assert.xunit/blob/3af483c3e851ef4f463a8ce8b9399b7bc8ab4dc0/Sdk/Exceptions/StartsWithException.cs#L31

And that's why the console shows them as the same.

**Comment by safern** [comment] 2020-07-17 08:39
Closing per discussion above.

**Closed by safern** 2020-07-17 08:39 UTC
Labels: arch-wasm, area-System.Text.RegularExpressions, untriaged
