### ISSUE TITLE
can not attach to debugger, signature validation issues.

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#107684] opened 2024-09-11 13:39 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/can-not-attach-to-debugger-signature-va/10716386)._

---
![image.png](https://aka.ms/dc/image?name=Ba2c8c6a340ab43eeb1823670bd70a8e7638584778033043365_20240805-140517-image.png&tid=a2c8c6a340ab43eeb1823670bd70a8e7638584778033043365)

---
#### Feedback Bot on 8/5/2024, 09:46 PM: 

(private comment, text removed)
#### Abdul Rahim Charif [MSFT] on 8/8/2024, 04:08 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by tommcdon** [comment] 2024-09-12 04:25
The customer did not provide .NET version information.  I have reached out to them directly and am awaiting a reply.

**Comment by HubDevUser** [comment] 2024-09-13 14:22
4.700.22.55902

**Comment by tommcdon** [comment] 2024-09-13 19:19
@HubDevUser - our suggestion is to move to a supported version of .NET - documented on https://dotnet.microsoft.com/en-us/download/dotnet.  Closing as this is not a bug.

**Closed by tommcdon** 2024-09-13 19:19 UTC
Labels: area-Diagnostics-coreclr
