### ISSUE TITLE
`System.Reflection` - `Type.GetCustomAttributes` Unexpected Attribute Count behavior

### ISSUE THREAD

**Issue by gurustron** [dotnet/runtime#88473] opened 2023-07-06 13:49 UTC
### Discussed in https://github.com/dotnet/runtime/discussions/53016

<div type='discussions-op-text'>

<sup>Originally posted by **AnakinRaW** May 20, 2021</sup>
Hey all, 

I have the following Code:
```cs
[AttributeUsage(AttributeTargets.All, Inherited = true, AllowMultiple = true)]
public class TestAttributeInheritMultiple : Attribute
{
}

public class TestAttributeInheritMultipleDerived : TestAttributeInheritMultiple
{
}

[TestAttributeInheritMultipleDerived]
[TestAttributeInheritMultipleDerived]
public class AttributeTestClass
{
}

[TestAttributeInheritMultipleDerived]
public class AttributeTestClassDerived : AttributeTestClass
{
}
```

when i call `typeof(AttributeTestClassDerived).GetCustomAttributes(true).Length;` i get only **`1`** attribute, though i was expecting the get `3`. 

There are some side observations that lead to my confusion: 
- inspecting the attribute usage of `TestAttributeInheritMultipleDerived ` yields *`Inherited = true and AllowMultiple = true`*. (as expected)
- adding `[AttributeUsage(AttributeTargets.All, Inherited = true, AllowMultiple = true)]` line to `TestAttributeInheritMultipleDerived ` (which should be unnecessary because it already has these usage attributes from its base class) i get **`3`** attributes back for AttributeTestClassDerived. 

Is this expected behavior and I'm overseeing something here, or this is a bug?

Cheers</div>

**Comment by gurustron** [comment] 2023-07-06 14:04
My repro was the following:

```c#
var bb = new B();
var customAttributes = typeof(B).GetCustomAttributes<TestAttribute>(true).ToList();
Console.WriteLine(customAttributes.Count); 

[AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = true)]
public abstract class TestAttributeBase : Attribute {}

// [AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = true)]
public class TestAttribute : TestAttributeBase {}

[Test]
public class A {}

[Test]
[Test]
public class B : A {}
```

**Expected output**:
With commented and uncommented  `AttributeUsage` on child attribute - 3. 

**Actual**
2 when commented

**Comment by nibdev** [comment] 2023-07-06 15:17
this is a duplicate of my issue #88476

**Comment by gurustron** [comment] 2023-07-06 16:01
@nibdev a) this was created earlier then your issue 2) created from discussion started back in 2021 (see the link at the top). So in terms of duplication it is other way around. Added the mention if the SO answer.

**Comment by gurustron** [comment] 2023-07-06 16:08
@nibdev  no problem! You can leave it open, it is more to the guidelines of the issues here.

**Comment by AnakinRaW** [comment] 2023-07-07 07:19
thx, for picking this up again :)

**Comment by buyaa-n** [comment] 2023-08-02 17:27
Putting into future, need to investigate more to see why this is happening

**Comment by steveharter** [comment] 2023-09-27 20:52
The existing behavior appears to be (did not look at the code) that if a derived attribute class doesn't have `[AttributeUsage]` then default values are used for that and the base class's `[AttributeUsage]` is not used.

This does make some sense to me since it is a simple rule and more performance that checking base classes - i.e. just add your own `[AttributeUsage]` instead of assuming the base class's will be used.

**Comment by buyaa-n** [comment] 2023-10-04 21:48
Looks it works just as @steveharter said: the `GetAttributeUsage(RuntimeType decoratedAttribute)` method doesn't check/load the `AttributeUsageAttribute` of the base type. 
https://github.com/dotnet/runtime/blob/a166bb71dea362129a25822852c23dbea1d802ed/src/coreclr/System.Private.CoreLib/src/System/Reflection/RuntimeCustomAttributeData.cs#L1445-L1469

Even it sounds like a bug fixing this now probably quite breaking as it was like this from the beginning. Given that there is a workaround: `add your own [AttributeUsage] instead of assuming the base class's will be used` closing the issue as not planned

**Closed by buyaa-n** 2023-10-04 21:48 UTC
Labels: area-System.Reflection
