### ISSUE TITLE
Test failure JIT\\Directed\\nullabletypes\\Desktop\\boxunboxvaluetype_do\\boxunboxvaluetype_do.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#75503] opened 2022-09-13 01:58 UTC
Run: [runtime-coreclr crossgen2 20220911.2](https://dev.azure.com/dnceng-public/public/_build/results?buildId=12410&view=ms.vss-test-web.build-test-results-tab&runId=245322&resultId=101207&paneView=debug)

Failed test:
```
R2R-CG2 windows arm64 Checked @ Windows.10.Arm64v8.Open

- JIT\\Directed\\nullabletypes\\Desktop\\boxunboxvaluetype_do\\boxunboxvaluetype_do.cmd
```
**Error message:**
```
Fatal error. Internal CLR error. (0x80131506)
at System.Collections.Generic.Stack1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Grow(Int32) at System.Collections.Generic.Stack1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].PushWithResize(System._Canon)
at Internal.JitInterface.CorInfoImpl.beginInlining(IntPtr, IntPtr*, Internal.JitInterface.CORINFO_METHOD_STRUCT*, Internal.JitInterface.CORINFO_METHOD_STRUCT*)
at Internal.JitInterface.CorInfoImpl.JitCompileMethod(IntPtr ByRef, IntPtr, IntPtr, IntPtr, Internal.JitInterface.CORINFO_METHOD_INFO ByRef, UInt32, IntPtr ByRef, UInt32 ByRef)
at Internal.JitInterface.CorInfoImpl.JitCompileMethod(IntPtr ByRef, IntPtr, IntPtr, IntPtr, Internal.JitInterface.CORINFO_METHOD_INFO ByRef, UInt32, IntPtr ByRef, UInt32 ByRef)
at Internal.JitInterface.CorInfoImpl.CompileMethodInternal(ILCompiler.DependencyAnalysis.IMethodNode, Internal.IL.MethodIL)
at Internal.JitInterface.CorInfoImpl.CompileMethod(ILCompiler.DependencyAnalysis.ReadyToRun.MethodWithGCInfo, ILCompiler.Logger)
at ILCompiler.ReadyToRunCodegenCompilation.<ComputeDependencyNodeDependencies>g__CompileOneMethod|38_3(ILCompiler.DependencyAnalysisFramework.DependencyNodeCore1<ILCompiler.DependencyAnalysis.NodeFactory>) at System.Threading.Tasks.Parallel+<>c__DisplayClass19_01[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<ForWorker>b__1(System.Threading.Tasks.RangeWorker ByRef, Int32, Boolean ByRef)
at System.Threading.Tasks.TaskReplicator+Replica.Execute()
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()

Return code:      1
Raw output file:      D:\h\w\ABFD0935\w\AE2609C2\uploads\Reports\JIT.Directed\nullabletypes\Desktop\boxunboxvaluetype_do\boxunboxvaluetype_do.output.txt
Raw output:
BEGIN EXECUTION
boxunboxvaluetype_do.dll
1 file(s) copied.
1:43:13.42
Response file: D:\h\w\ABFD0935\w\AE2609C2\e\JIT\Directed\nullabletypes\Desktop\boxunboxvaluetype_do\boxunboxvaluetype_do.dll.rsp
D:\h\w\ABFD0935\w\AE2609C2\e\JIT\Directed\nullabletypes\Desktop\boxunboxvaluetype_do\IL-CG2\boxunboxvaluetype_do.dll
-o:D:\h\w\ABFD0935\w\AE2609C2\e\JIT\Directed\nullabletypes\Desktop\boxunboxvaluetype_do\boxunboxvaluetype_do.dll
--targetarch:arm64
--verify-type-and-field-layout
--method-layout:random
-r:D:\h\w\ABFD0935\p\System..dll
-r:D:\h\w\ABFD0935\p\Microsoft..dll
-r:D:\h\w\ABFD0935\p\mscorlib.dll
-r:D:\h\w\ABFD0935\p\netstandard.dll
-O
" "dotnet" "D:\h\w\ABFD0935\p\crossgen2\crossgen2.dll" @"D:\h\w\ABFD0935\w\AE2609C2\e\JIT\Directed\nullabletypes\Desktop\boxunboxvaluetype_do\boxunboxvaluetype_do.dll.rsp"   -r:D:\h\w\ABFD0935\w\AE2609C2\e\JIT\Directed\nullabletypes\Desktop\boxunboxvaluetype_do\IL-CG2*.dll"
1:43:21.02
Crossgen2 failed with exitcode - -1073741819
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=D:\h\w\ABFD0935\p
D:\h\w\ABFD0935\w\AE2609C2\e\JIT\Directed\nullabletypes\Desktop\boxunboxvaluetype_do\boxunboxvaluetype_do.cmd
Expected: True
Actual:   False


Stack trace
   at JIT_Directed._nullabletypes_Desktop_boxunboxvaluetype_do_boxunboxvaluetype_do_._nullabletypes_Desktop_boxunboxvaluetype_do_boxunboxvaluetype_do_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by mangod9** [comment] 2022-09-13 16:33
believe this is the dupe of crossgen2 issue @AntonLapounov has recently fixed.

**Comment by AntonLapounov** [comment] 2022-09-13 19:32
Yes, this is a dup of #75041.
```
0:022> kc7
 # Call Site
00 coreclr!DacEnumerableHashTable<InstMethodHashTable,InstMethodHashEntry,4>::BaseFindNextEntryByHash
01 coreclr!InstMethodHashTable::FindMethodDesc
02 coreclr!InstantiatedMethodDesc::FindLoadedInstantiatedMethodDesc
03 coreclr!MethodDesc::FindOrCreateAssociatedMethodDesc
04 coreclr!MethodDesc::FindOrCreateAssociatedMethodDesc
05 coreclr!Dictionary::PopulateEntry
06 coreclr!JIT_GenericHandleWorker
```

**Closed by AntonLapounov** 2022-09-13 19:32 UTC
Labels: arch-arm64, os-windows, area-crossgen2-coreclr, untriaged, blocking-clean-ci-optional
