### ISSUE TITLE
[8.0.100-rc.2.23469.4] The type "IPNetWork" exists in both "System.Net.IPNetwork" and "System.Net.Primitives"

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/runtime#93022] opened 2023-09-25 05:35 UTC
**Application Name:** NETworkManager
**OS：** Windows 10 21H2
**CPU:** X64
**.NET Build Number:** dotnet-sdk-8.0.100-rc.2.23469.4
Also can check at :https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1891043

**Verify Scenarios:**

1. Windows10 21h2 x64 + dotnet-sdk-8.0.100-preview.3.23178.7： Pass
2. Windows10 21h2 x64 + dotnet-sdk-8.0.100-preview.4.23207.7: Fail
3. Windows10 21h2 x64 + dotnet-sdk-8.0.100-rc.2.23469.4: Fail
4. Windows10 21h2 x64 + dotnet-sdk-8.0.100-rc.2.23472.8: Fail

**Issue Description:**

When retargeting NETworkManager app from .NET 6.0 to .NET 8.0, we get "error CS0433: The type 'IPNetwork' exists in both `System.Net.IPNetwork, Version=2.6.611.0, Culture=neutral, PublicKeyToken=717343cc2c25edcf` and `System.Net.Primitives, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a`" exception during building. This exception starts from dotnet-sdk-8.0.100-preview.4.23207.7.

**Minimal Repro steps (Demo attached):**  

[IPNetworkInfoDemo.zip](https://github.com/dotnet/sdk/files/12711470/IPNetworkInfoDemo.zip)

​​1. Create a .NET 6.0 Console application.
2. Install "IPNetwork2" Nuget Package.
3. Add following code to Program.cs file:
```
using System.Net;

IPNetwork.Parse("");
```
4. Build the project, it will build successfully.
5. Retarget the console app to .NET 8.0 from .csproj file:
```
<PropertyGroup>
  <OutputType>Exe</OutputType>
  <TargetFramework>net8.0</TargetFramework>
  <ImplicitUsings>enable</ImplicitUsings>
  <Nullable>enable</Nullable>
</PropertyGroup>
```
6. Build the project.

**Expected Result:**
Build successful after retargeting to .NET 8.0.

**Actual Result**:

Build failed with this exception:
```
error CS0433: The type 'IPNetwork' exists in both 'System
.Net.IPNetwork, Version=2.6.611.0, Culture=neutral, PublicKeyToken=717343cc2c25edcf' and 'System.Net.Primitives, Versio
n=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

**Findings**:
When checking the source code for "IPNetwork2" Nuget Package, the conflict should be occurred with [IPNetwork.cs](https://github.com/lduchosal/ipnetwork/blob/master/src/System.Net.IPNetwork/IPNetwork.cs) from System.Net.IPNetwork project. 
And this conflict start from dotnet-sdk-8.0.100-preview.4.23207.7, but works fine in previous .NET 8.0 version.

@dotnet-actwx-bot @dotnet/compat

**Comment by antonfirsov** [comment] 2023-10-04 20:01
We cannot count with every community library when defining names for new types, and a name conflict with an existing community package doesn't meet our definition of a breaking change.

This should be addressed by changing the NETworkManager application, either by fixing the build applying the hint from: https://github.com/lduchosal/ipnetwork/issues/280#issuecomment-1722494254, or if it's ok for this app to target .NET 8.0 only, it can be updated to use .NET 8.0's new built-in `IPNetwork` type and abandon the IPNetwork2 package.

@Junjun-zhao is there something I'm missing that makes this update difficult?

**Comment by karelz** [comment] 2023-10-05 16:19
Yes, this is problem of the application / IPNetwork2 package.
Any nuget package using System namespace risks future conflicts with .NET types if they are added later, like this one.

Closing as By Design.

**Closed by karelz** 2023-10-05 16:19 UTC
Labels: area-System.Net, untriaged
