### ISSUE TITLE
System.Text.Json.JsonSerializer doesn't serialize properties from derived classes

### ISSUE THREAD

**Issue by mauricio-bv** [dotnet/runtime#31742] opened 2019-12-30 21:41 UTC
I am trying to use the System.Text.Json serialization libray, but I can't get it is serialize it as I used to with Newtonson. Properties in derived classes or Interfaces are not serializing. This issue has also been asked and explained in the link below.

[Link](https://stackoverflow.com/questions/59258655/system-text-json-jsonserializer-doesnt-serialize-properties-from-derived-classe/59536948#59536948)

Is there any serialization option I should set for proper serialization?

**Comment by bstordrup** [comment] 2020-02-15 21:01
I have a similar problem. I have a class that contains some properties that are classes being leafs in a class hierarchy. These properties are not being serialized at all with System.Text.Json.

My code is working perfectly right in .NET 4.7.2 with Newtonsoft.Json being used. When migrating to  .NET core 3.1 using System.Text.Json, I don't get the same result passed back to the client. And it is the Json serialization that is the problem. Tested by manually converting to Json before passing my result object back into the pipeline.

**Comment by layomia** [comment] 2020-02-20 23:30
Closing as duplicate of https://github.com/dotnet/runtime/issues/29937.

We only offer polymorphic support for `System.Object` instances: see https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to#serialize-properties-of-derived-classes.

The exception for other types is the root (with the non-generic `Serialize` overload) where we call `.GetType()`.

**Closed by layomia** 2020-02-20 23:30 UTC
Labels: area-System.Text.Json, untriaged

**Comment by sake402** [comment] 2020-06-23 14:54
```
public class Base{
public string PropertyBase{ get; set; }="Base";
}
public class Foo:Base{
public string PropertyFoo{ get; set; } = "Foo";
}

public class Bar:Base{
public string PropertyBar{ get; set; } = "Bar";
}
```
If we then do
```
var bases = new[]{ new Foo(), new Bar() }
JsonSerializer.Serialize<object>(bases);
```
We get
```
[{"PropertyBase":"Base"}, {"PropertyBase":"Base"}]
```
Despite using object as the serialization type

**Comment by layomia** [comment] 2020-06-23 15:05
@sake402 I couldn't get your repro to compile: https://dotnetfiddle.net/kLEyqt

**Comment by sake402** [comment] 2020-06-23 18:22
@layomia Please check again here.
https://dotnetfiddle.net/cGBgIp

**Comment by qsdfplkj** [comment] 2020-08-12 10:08
@sake402  you should use: `var bases = new object[]{ new Foo(), new Bar() };`

**Comment by sake402** [comment] 2020-08-12 10:33
@qsdfplkj that doesnt work. 
Please see https://dotnetfiddle.net/NpiwnZ
