### ISSUE TITLE
Test failure JIT/Regression/VS-ia64-JIT/V2.0-Beta2/b311420/b311420/b311420.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#54043] opened 2021-06-11 02:07 UTC
Run: [runtime-coreclr r2r-extra 20210610.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1180726&view=ms.vss-test-web.build-test-results-tab&runId=35531738&resultId=109048&paneView=debug)

Failed test:
```
R2R OSX arm64 Checked jitstress1 @ OSX.1100.ARM64.Open

- JIT/Regression/VS-ia64-JIT/V2.0-Beta2/b311420/b311420/b311420.sh

```
**Error message:**
```
/private/tmp/helix/working/ADEA094B/w/A7A6095B/e/JIT/Regression/VS-ia64-JIT/V2.0-Beta2/b311420/b311420/b311420.sh: line 254: -r:/private/tmp/helix/working/ADEA094B/w/A7A6095B/e/JIT/Regression/VS-ia64-JIT/V2.0-Beta2/b311420/b311420/IL-CG2/*.dll: No such file or directory
rm: /private/tmp/helix/working/ADEA094B/w/A7A6095B/e/JIT/Regression/VS-ia64-JIT/V2.0-Beta2/b311420/b311420/b311420.dll.rsp: No such file or directory
Unhandled exception. Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder1.AsyncStateMachineBox1.ExecutionContextCallback(Object s)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder1.AsyncStateMachineBox1.MoveNext(Thread threadPoolThread)
at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
--- End of stack trace from previous location ---
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()System.NullReferenceException: Object reference not set to an instance of an object.
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder1.AsyncStateMachineBox1.ExecutionContextCallback(Object s)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder1.AsyncStateMachineBox1.MoveNext(Thread threadPoolThread)
at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
--- End of stack trace from previous location ---
at System.Threading.ThreadPoolWorkQueue.Dispatch()
at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

dyld: Library not loaded: @rpath/libmscordaccore.dylib
Referenced from: /private/tmp/helix/working/ADEA094B/p/dotnet-cli/shared/Microsoft.NETCore.App/6.0.0-preview.3.21201.4/createdump
Reason: image not found
/private/tmp/helix/working/ADEA094B/w/A7A6095B/e/JIT/Regression/VS-ia64-JIT/V2.0-Beta2/b311420/b311420/b311420.sh: line 204: 72179 Abort trap: 6           (core dumped) $__Command

Return code:      1
Raw output file:      /tmp/helix/working/ADEA094B/w/A7A6095B/uploads/Reports/JIT.Regression/VS-ia64-JIT/V2.0-Beta2/b311420/b311420/b311420.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/private/tmp/helix/working/ADEA094B/w/A7A6095B/e/JIT/Regression/VS-ia64-JIT/V2.0-Beta2/b311420/b311420/IL-CG2/b311420.dll
Response file: /private/tmp/helix/working/ADEA094B/w/A7A6095B/e/JIT/Regression/VS-ia64-JIT/V2.0-Beta2/b311420/b311420/b311420.dll.rsp
/private/tmp/helix/working/ADEA094B/w/A7A6095B/e/JIT/Regression/VS-ia64-JIT/V2.0-Beta2/b311420/b311420/IL-CG2/b311420.dll
-o:/private/tmp/helix/working/ADEA094B/w/A7A6095B/e/JIT/Regression/VS-ia64-JIT/V2.0-Beta2/b311420/b311420/b311420.dll
-r:/tmp/helix/working/ADEA094B/p/System..dll
-r:/tmp/helix/working/ADEA094B/p/Microsoft..dll
-r:/tmp/helix/working/ADEA094B/p/mscorlib.dll
--verify-type-and-field-layout
--targetarch:arm64
-O
Running CrossGen2:  dotnet /tmp/helix/working/ADEA094B/p/crossgen2/crossgen2.dll @/private/tmp/helix/working/ADEA094B/w/A7A6095B/e/JIT/Regression/VS-ia64-JIT/V2.0-Beta2/b311420/b311420/b311420.dll.rsp

Emitting R2R PE file: /private/tmp/helix/working/ADEA094B/w/A7A6095B/e/JIT/Regression/VS-ia64-JIT/V2.0-Beta2/b311420/b311420/b311420.dll
Crossgen2 failed with exitcode: 134
in ReleaseLock
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/tmp/helix/working/ADEA094B/p
/private/tmp/helix/working/ADEA094B/w/A7A6095B/e/JIT/Regression/VS-ia64-JIT/V2.0-Beta2/b311420/b311420/b311420.sh
Expected: True
Actual:   False


Stack trace
   at JIT_Regression._VS_ia64_JIT_V2_0_Beta2_b311420_b311420_b311420_._VS_ia64_JIT_V2_0_Beta2_b311420_b311420_b311420_sh()
```

**Comment by mangod9** [comment] 2021-07-20 01:57
Dupe of #51250

**Closed by mangod9** 2021-07-20 01:57 UTC
Labels: arch-arm64, area-crossgen2-coreclr, os-mac-os-x, untriaged
