### ISSUE TITLE
Test failure: JIT\\Performance\\CodeQuality\\HWIntrinsic\\X86\\PacketTracer\\PacketTracer\\PacketTracer.cmd

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#34111] opened 2020-03-26 04:44 UTC
failed in job: [runtime-coreclr jitstress 20200324.1](https://dev.azure.com/dnceng/public/_build/results?buildId=572214&view=ms.vss-test-web.build-test-results-tab&runId=17945330&resultId=107389&paneView=debug)

Error message
~~~
Assert failure(PID 5820 [0x000016bc], Thread: 5632 [0x1600]): Assertion failed '!"SIMD intrinsic with unsupported base type."' in 'Packet256Tracer:MinIntersections(RayPacket256,Scene):Intersections:this' during 'Generate code' (IL size 206)
File: F:\workspace\_work\1\s\src\coreclr\src\jit\simdcodegenxarch.cpp Line: 3201
Image: C:\h\w\A9FF0959\p\CoreRun.exe
Return code: 1
Raw output file: C:\h\w\A9FF0959\w\AC940A08\e\JIT\Performance\Reports\JIT.Performance\CodeQuality\HWIntrinsic\X86\PacketTracer\PacketTracer\PacketTracer.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\A9FF0959\p\corerun.exe" PacketTracer.dll 
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\A9FF0959\p
> C:\h\w\A9FF0959\w\AC940A08\e\JIT\Performance\CodeQuality\HWIntrinsic\X86\PacketTracer\PacketTracer\PacketTracer.cmd
Expected: True
Actual: False


Stack trace
   at JIT_Performance._CodeQuality_HWIntrinsic_X86_PacketTracer_PacketTracer_PacketTracer_._CodeQuality_HWIntrinsic_X86_PacketTracer_PacketTracer_PacketTracer_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x64.Checked\TestWrappers\JIT.Performance\JIT.Performance.XUnitWrapper.cs:line 6639
~~~

**Comment by BruceForstall** [comment] 2020-03-26 17:13
@tannergooding @echesakovMSFT @CarolEidt Any recent change that might be responsible for this new assert?
`
Assert failure(PID 5820 [0x000016bc], Thread: 5632 [0x1600]): Assertion failed '!"SIMD intrinsic with unsupported base type."' in 'Packet256Tracer:MinIntersections(RayPacket256,Scene):Intersections:this' during 'Generate code' (IL size 206)
File: F:\workspace\_work\1\s\src\coreclr\src\jit\simdcodegenxarch.cpp Line: 3201
`

Windows, x64, JitStress=1

**Comment by tannergooding** [comment] 2020-03-26 17:20
This might be https://github.com/dotnet/runtime/issues/34135

**Comment by CarolEidt** [comment] 2020-03-26 17:24
> This might be #34135

It could be, though it's not entirely clear how that would lead to that assert, nor is it obvious to me how a jitstress run would affect SIMD.

@tannergooding - were you planning to follow up on #34135 or would you like me to take a look at it?

**Comment by tannergooding** [comment] 2020-03-26 17:27
> @tannergooding - were you planning to follow up on #34135 or would you like me to take a look at it?

I've already investigated and believe I root caused the issue and validated that it fixes things. I'll have a PR up momentarily.

> It could be, though it's not entirely clear how that would lead to that assert, nor is it obvious to me how a jitstress run would affect SIMD.

I'm working on seeing if I can repro this issue as well. I know we test all the `COMPlus_EnableISA=0` combinations as part of the outer loop jobs, but I'm unsure if that covers this particular run.

**Comment by tannergooding** [comment] 2020-03-26 18:00
Looks like fixing #34135 fixes this issue as well (I can repro without the fix but not with the fix).

We were getting untyped SIMD16/SIMD32 which was causing the register allocator to create invalid `SIMDIntrinsicUpperSave` nodes: [JitDump.txt](https://github.com/dotnet/runtime/files/4388986/JitDump.txt)

I'm not sure yet what in JitStress=1 interacts badly with #34135

**Comment by tannergooding** [comment] 2020-03-26 19:02
Looks like it was failing because without #34135, `InstructionSet_Vector128` and `InstructionSet_Vector256` are "unsupported" by default. That is, the flags are `11111111001111111111111110`, which means all but the mentioned are marked `supported`:
```
InstructionSet_SSE=1,
    InstructionSet_SSE2=2,
    InstructionSet_SSE3=3,
    InstructionSet_SSSE3=4,
    InstructionSet_SSE41=5,
    InstructionSet_SSE42=6,
    InstructionSet_AVX=7,
    InstructionSet_AVX2=8,
    InstructionSet_AES=9,
    InstructionSet_BMI1=10,
    InstructionSet_BMI2=11,
    InstructionSet_FMA=12,
    InstructionSet_LZCNT=13,
    InstructionSet_PCLMULQDQ=14,
    InstructionSet_POPCNT=15,
    InstructionSet_Vector128=16,
    InstructionSet_Vector256=17,
    InstructionSet_BMI1_X64=18,
    InstructionSet_BMI2_X64=19,
    InstructionSet_LZCNT_X64=20,
    InstructionSet_POPCNT_X64=21,
    InstructionSet_SSE_X64=22,
    InstructionSet_SSE2_X64=23,
    InstructionSet_SSE41_X64=24,
    InstructionSet_SSE42_X64=25,
```

This was causing parts of the JIT to disagree on what can/should be generated.

**Comment by tannergooding** [comment] 2020-03-26 22:15
Resolved by https://github.com/dotnet/runtime/pull/34139

**Closed by tannergooding** 2020-03-26 22:15 UTC
Labels: JitStress, area-CodeGen-coreclr
