### ISSUE TITLE
Test failure JIT/Regression/JitBlue/GitHub_26491/GitHub_26491_MultipleReturns/GitHub_26491_MultipleReturns.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#61081] opened 2021-11-02 01:07 UTC
Run: [runtime 20211101.29](https://dev.azure.com/dnceng/public/_build/results?buildId=1449222&view=ms.vss-test-web.build-test-results-tab&runId=41730676&paneView=debug&resultId=101915)

Failed test:
```
Mono Browser wasm Release @ Ubuntu.1804.Amd64.Open

- JIT/Regression/JitBlue/GitHub_26491/GitHub_26491_MultipleReturns/GitHub_26491_MultipleReturns.sh

```
**Error message:**
```
Return code:      1
Raw output file:      /datadisks/disk1/work/A3D608AC/w/ACF2097A/uploads/Reports/JIT.Regression/JitBlue/GitHub_26491/GitHub_26491_MultipleReturns/GitHub_26491_MultipleReturns.output.txt
Raw output:
BEGIN EXECUTION
Microsoft (R) Build Engine version 17.0.0-preview-21427-02+414393fc1 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

AppDir: /datadisks/disk1/work/A3D608AC/w/ACF2097A/e/JIT/Regression/JitBlue/GitHub_26491/GitHub_26491_MultipleReturns/WasmApp/
TestBinDir: /datadisks/disk1/work/A3D608AC/w/ACF2097A/e/JIT/Regression/JitBlue/GitHub_26491/GitHub_26491_MultipleReturns
ArtifactsBinDir:
/datadisks/disk1/work/A3D608AC/p/build/WasmApp.targets(209,5): warning : Could not find $(AssemblyName)=WasmTestRunner.dll in the assemblies to be bundled. [/datadisks/disk1/work/A3D608AC/p/wasm-test-runner/WasmTestRunner.proj]
/datadisks/disk1/work/A3D608AC/p/build/WasmApp.targets(273,5): error MSB4018: The "WasmAppBuilder" task failed unexpectedly. [/datadisks/disk1/work/A3D608AC/p/wasm-test-runner/WasmTestRunner.proj]
/datadisks/disk1/work/A3D608AC/p/build/WasmApp.targets(273,5): error MSB4018: System.IO.IOException: The process cannot access the file '/datadisks/disk1/work/A3D608AC/w/ACF2097A/e/JIT/Regression/JitBlue/GitHub_26491/GitHub_26491_MultipleReturns/WasmApp/managed/GitHub_26491_MultipleReturns.dll' because it is being used by another process. [/datadisks/disk1/work/A3D608AC/p/wasm-test-runner/WasmTestRunner.proj]
/datadisks/disk1/work/A3D608AC/p/build/WasmApp.targets(273,5): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) [/datadisks/disk1/work/A3D608AC/p/wasm-test-runner/WasmTestRunner.proj]
/datadisks/disk1/work/A3D608AC/p/build/WasmApp.targets(273,5): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) [/datadisks/disk1/work/A3D608AC/p/wasm-test-runner/WasmTestRunner.proj]
/datadisks/disk1/work/A3D608AC/p/build/WasmApp.targets(273,5): error MSB4018:    at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite) [/datadisks/disk1/work/A3D608AC/p/wasm-test-runner/WasmTestRunner.proj]
/datadisks/disk1/work/A3D608AC/p/build/WasmApp.targets(273,5): error MSB4018:    at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite) [/datadisks/disk1/work/A3D608AC/p/wasm-test-runner/WasmTestRunner.proj]
/datadisks/disk1/work/A3D608AC/p/build/WasmApp.targets(273,5): error MSB4018:    at WasmAppBuilder.FileCopyChecked(String src, String dst, String label) in //src/tasks/WasmAppBuilder/WasmAppBuilder.cs:line 351 [/datadisks/disk1/work/A3D608AC/p/wasm-test-runner/WasmTestRunner.proj]
/datadisks/disk1/work/A3D608AC/p/build/WasmApp.targets(273,5): error MSB4018:    at WasmAppBuilder.ExecuteInternal() in //src/tasks/WasmAppBuilder/WasmAppBuilder.cs:line 160 [/datadisks/disk1/work/A3D608AC/p/wasm-test-runner/WasmTestRunner.proj]
/datadisks/disk1/work/A3D608AC/p/build/WasmApp.targets(273,5): error MSB4018:    at WasmAppBuilder.Execute() in /_/src/tasks/WasmAppBuilder/WasmAppBuilder.cs:line 123 [/datadisks/disk1/work/A3D608AC/p/wasm-test-runner/WasmTestRunner.proj]
/datadisks/disk1/work/A3D608AC/p/build/WasmApp.targets(273,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/datadisks/disk1/work/A3D608AC/p/wasm-test-runner/WasmTestRunner.proj]
/datadisks/disk1/work/A3D608AC/p/build/WasmApp.targets(273,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/datadisks/disk1/work/A3D608AC/p/wasm-test-runner/WasmTestRunner.proj]
Test Harness


Stack trace
   at JIT_Regression._JitBlue_GitHub_26491_GitHub_26491_MultipleReturns_GitHub_26491_MultipleReturns_._JitBlue_GitHub_26491_GitHub_26491_MultipleReturns_GitHub_26491_MultipleReturns_sh()
```

**Comment by radical** [comment] 2021-11-02 02:02
Is this seen only with wasm?

**Comment by krwq** [comment] 2021-11-03 13:52
@radical it seems so

**Comment by radical** [comment] 2021-11-05 22:59
IIUC:

- Given: `The process cannot access the file '/datadisks/disk1/work/A3D608AC/w/ACF2097A/e/JIT/Regression/JitBlue/GitHub_26491/GitHub_26491_MultipleReturns/WasmApp/managed/GitHub_26491_MultipleReturns.dll'`
- Given, tests are run in parallel, per collection (IIUC, one per test class)

- This is failing when trying to copy the main assembly to the app bundle in `WasmApp/managed/GitHub_26491_MultipleReturns.dll`.
- there are two projects in `src/tests/JIT/Regression/JitBlue/GitHub_26491`, both of which use the assembly (or app bundle, in case of wasm) from `GitHub_26491_MultipleReturns.ilproj`
- Thus both of these, when built on helix would generate an app bundle in `JIT/Regression/JitBlue/GitHub_26491/GitHub_26491_MultipleReturns/WasmApp/`, and use the same assembly path - `WasmApp/managed/GitHub_26491_MultipleReturns.dll`

- These two projects get two separate test classes in `JIT.Regression.XUnitWrapper.dll`:

```shell
 $ monop -r JIT.Regression.XUnitWrapper.dll | egi 26491
JIT_Regression._JitBlue_GitHub_26491_GitHub_26491_MultipleReturns_GitHub_26491_MultipleReturns_
JIT_Regression._JitBlue_GitHub_26491_GitHub_26491_SingleReturnSynchronized_GitHub_26491_SingleReturnSynchronized_
```

- and xunit will run these in parallel, which means that they can race, and end up overwriting files, or conflict with such exceptions

Possible solutions:
1. build the app bundle on the build machine, and send that to helix. But this won't work for AOT though, since we would want to AOT on helix instead
2. hack: set `TestBinDir` using the top level project name, but this won't help the AOT case at all
3. Explicitly handle the dependencies, by building the dependent project once (`$(CLRTestProjectToRun)`), and only then running all the tests that depend on it. This will need be solved with the work for AOT+runtime-tests. @naricc 

Meanwhile, this seems to be extremely rare, so I don't think a hack(2) would be worth it.

**Comment by lewing** [comment] 2023-07-24 20:29
@radical please triage

**Comment by radical** [comment] 2023-07-24 20:52
AFAICS, this hasn't been hit since Nov 2021. And even then it was a rare one. A lot of stuff has changed with the runtime tests since then. I'll close this, and it can be re-opened if it is ever hit again.

**Closed by radical** 2023-07-24 20:52 UTC
Labels: arch-wasm, area-HostModel
