### ISSUE TITLE
Inconsistent CultureInfo.DateTimeFormat.ShortestDayName between server/wasm

### ISSUE THREAD

**Issue by rabbitism** [dotnet/runtime#37709] opened 2020-06-10 02:34 UTC
### Describe the bug
I used CultureInfo.DateTimeFormat.ShortestDayNames in blazor project. While using en-US culture, It returns different values when using server side project or wasm project. 

In wasm it returns single letter "S M T W T F S"
In server-side it returns double letters "Su Mo Tu We Th Fr Sa"

This is probably a problem of mono runtime.

### To Reproduce

1. Create template project for Blazor server/wasm projects  respectively
2. Output DateTimeFormat.ShortestDayNames for CultureInfo en-US

### Further technical details
- ASP.NET Core version
- Include the output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   5.0.100-preview.1.20155.7
 Commit:    1c44853056

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.1.20155.7\
```
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
```
Visual Studio Community 2019 16.6.1
```

**Comment by danmosemsft** [comment] 2020-06-11 07:33
@lewing is this by design?

**Comment by tarekgh** [comment] 2020-06-11 16:03
This looks to be the difference between the runtimes as stated before. WASM now started to use ICU and looks the previous runtime version was using data similar to WIndows data.

**Comment by safern** [comment] 2020-06-11 16:13
I don’t think WASM is yet using ICU but will soon be using it, right? Also it seems like the preview1 version of the SDK will be using NLS in the Server and in WASM it is using its own managed implementation for globalization if I remember correctly. @steveisok @kg

**Comment by kg** [comment] 2020-06-11 17:07
WASM is not using ICU yet.

**Comment by safern** [comment] 2020-06-11 17:24
Maybe this can be closed as we're tracking the WASM using ICU effort here: https://github.com/dotnet/runtime/issues/33652?

**Comment by tarekgh** [comment] 2020-06-11 17:51
I think when using ICU, we'll get similar results as we are seeing today "S M T W T F S".

**Comment by safern** [comment] 2020-06-11 17:58
Yeah; there will be a difference in preview4 or earlier where we didn't support ICU on Windows, or if the Windows Server SKU is earlier than 19H1.

**Comment by tarekgh** [comment] 2020-06-11 18:01
Mono's team needs to decide if they need to do something or close this by design.

**Comment by marek-safar** [comment] 2020-06-11 21:58
We are looking into fixing this for .NET5 release

**Comment by rabbitism** [comment] 2020-06-12 01:20
Thanks for answering my question. May I know if there is a documentation for ICU you mentioned above? I have another tiny detail, but I want to check if it is a ICU definition issue or .net implementation issue.

**Comment by steveisok** [comment] 2020-07-23 15:38
@EgorBo Please validate now that we have ICU snapped in.

**Comment by EgorBo** [comment] 2020-07-23 18:17
hm.. still reproduces, investigating...

**Comment by EgorBo** [comment] 2020-08-13 10:43
validated:
we print 
```
S M T W T F S
```
so does .NET 5 (coreclr) on Windows and *nix

.NET 3.1 on Windows prints
```
Su Mo Tu We Th Fr Sa
```
because it uses NLS and since .NET 5 it tries to use ICU on all platforms.

**Closed by EgorBo** 2020-08-13 10:43 UTC
Labels: arch-wasm, area-System.Globalization

**Comment by EgorBo** [comment] 2020-08-13 10:48
NOTE: there are other "breaking changes" between NLS and ICU e.g. https://github.com/dotnet/runtime/issues/40258#issuecomment-668123640
