### ISSUE TITLE
could JIT can inline closure Action?

### ISSUE THREAD

**Issue by egmkang** [dotnet/runtime#34634] opened 2020-04-07 09:58 UTC
```
void Foreach(Action<int> fn)
{
    foreach(var item in list)
    {
        fn(item);
    }
}

void test()
{
    var sum = 0;
    Foreach((item) => sum += item);
}
```
in the `test` function, call `Foreach` function will new a small object closure.

can CoreCLR JIT Engine inline this simple closure call?

**Comment by omariom** [comment] 2020-04-07 11:49
Theoretically, if JIT inlines  a call to Foreach at a particular callsite, it could find that the delegate points to a closure,  get rid of the closure allocation, inline the call and "inline" the closure's fields as local variables.

**Comment by EgorBo** [comment] 2020-04-07 12:51
> Theoretically, if JIT inlines call to Foreach

Methods with loop never inline, they simply don't pass this check: https://github.com/dotnet/runtime/blob/a605729eee65344b4c63fb036a35405abcc1de31/src/coreclr/src/jit/inlinepolicy.cpp#L492-L495

**Comment by sakno** [comment] 2020-04-07 17:41
Related to #6498

**Comment by AndyAyersMS** [comment] 2020-04-07 17:57
> Methods with loops never inline

Are you sure? Simple loops can have 5 or fewer BBs.

> can CoreCLR JIT Engine inline this simple closure call?

Following up on what @sakno said, there are some notes on what it would take to inline a delegate invoke starting at [this comment](https://github.com/dotnet/runtime/issues/4584#issuecomment-385135810), and a number of issues to sort through before we're anywhere close to being able to do this.

**Comment by jkotas** [comment] 2020-04-07 21:20
Duplicate of #6498 and #4584

**Closed by jkotas** 2020-04-07 21:20 UTC
Labels: area-CodeGen-coreclr
