### ISSUE TITLE
String.Compare("ß", "ss", StringComparison.InvariantCultureIgnoreCase) doesn't work as expected on MacOS

### ISSUE THREAD

**Issue by kastonework** [dotnet/runtime#33162] opened 2020-03-04 18:38 UTC
# String.Compare("ß", "ss", StringComparison.InvariantCultureIgnoreCase) doesn't work as expected on MacOS

The Eszett ("ß") is considered equivalent to "ss" when doing a culture-based compare. However, this isn't working as expected under .NET Core 3.1 on MacOS.

# General

I used the following test program:
```
using System;

namespace MacNetCoreBugsRepro
{
  class Program
  {
    static void Main(string[] args)
    {
      Console.WriteLine(@"String.Compare(""ß"", ""ss"", false, System.Globalization.CultureInfo.InvariantCulture): {0}", String.Compare("ß", "ss", false, System.Globalization.CultureInfo.InvariantCulture));
      Console.WriteLine(@"String.Compare(""ß"", ""ss"", true, System.Globalization.CultureInfo.InvariantCulture): {0}", String.Compare("ß", "ss", true, System.Globalization.CultureInfo.InvariantCulture));
      Console.WriteLine(@"String.Compare(""xssx"", ""xßx"", true, System.Globalization.CultureInfo.InvariantCulture): {0}", String.Compare("xssx", "xßx", true, System.Globalization.CultureInfo.InvariantCulture));
      Console.WriteLine(@"String.Compare(""\xDF"", ""ss"", false, System.Globalization.CultureInfo.InvariantCulture): {0}", String.Compare("\xDF", "ss", true, System.Globalization.CultureInfo.InvariantCulture));
      Console.WriteLine();

      Console.WriteLine(@"String.Compare(""ß"", ""ss"", StringComparison.OrdinalIgnoreCase): {0}", String.Compare("ß", "ss", StringComparison.OrdinalIgnoreCase));
      Console.WriteLine(@"String.Compare(""xssx"", ""xßx"", StringComparison.OrdinalIgnoreCase): {0}", String.Compare("xssx", "xßx", StringComparison.OrdinalIgnoreCase));
      Console.WriteLine(@"String.Compare(""\xDF"", ""ss"", StringComparison.OrdinalIgnoreCase): {0}", String.Compare("\xDF", "ss", StringComparison.OrdinalIgnoreCase));
      Console.WriteLine();

      Console.WriteLine(@"String.Compare(""ß"", ""ss"", StringComparison.InvariantCultureIgnoreCase): {0}", String.Compare("ß", "ss", StringComparison.InvariantCultureIgnoreCase));
      Console.WriteLine(@"String.Compare(""xssx"", ""xßx"", StringComparison.InvariantCultureIgnoreCase): {0}", String.Compare("xssx", "xßx", StringComparison.InvariantCultureIgnoreCase));
      Console.WriteLine(@"String.Compare(""\xDF"", ""ss"", StringComparison.InvariantCultureIgnoreCase): {0}", String.Compare("\xDF", "ss", StringComparison.InvariantCultureIgnoreCase));
      Console.WriteLine();

      Console.WriteLine(@"String.Compare(""ß"", ""ss"", StringComparison.CurrentCulture): {0}", String.Compare("ß", "ss", StringComparison.CurrentCulture));
      Console.WriteLine(@"String.Compare(""xssx"", ""xßx"", StringComparison.CurrentCulture): {0}", String.Compare("xssx", "xßx", StringComparison.CurrentCulture));
      Console.WriteLine(@"String.Compare(""\xDF"", ""ss"", StringComparison.CurrentCulture): {0}", String.Compare("\xDF", "ss", StringComparison.CurrentCulture));
    }
  }
}

```
Under Windows I get the following output:
```
String.Compare("ß", "ss", false, System.Globalization.CultureInfo.InvariantCulture): 0
String.Compare("ß", "ss", true, System.Globalization.CultureInfo.InvariantCulture): 0
String.Compare("xssx", "xßx", true, System.Globalization.CultureInfo.InvariantCulture): 0
String.Compare("\xDF", "ss", false, System.Globalization.CultureInfo.InvariantCulture): 0

String.Compare("ß", "ss", StringComparison.OrdinalIgnoreCase): 1
String.Compare("xssx", "xßx", StringComparison.OrdinalIgnoreCase): -1
String.Compare("\xDF", "ss", StringComparison.OrdinalIgnoreCase): 1

String.Compare("ß", "ss", StringComparison.InvariantCultureIgnoreCase): 0
String.Compare("xssx", "xßx", StringComparison.InvariantCultureIgnoreCase): 0
String.Compare("\xDF", "ss", StringComparison.InvariantCultureIgnoreCase): 0

String.Compare("ß", "ss", StringComparison.CurrentCulture): 0
String.Compare("xssx", "xßx", StringComparison.CurrentCulture): 0
String.Compare("\xDF", "ss", StringComparison.CurrentCulture): 0

```
Under MacOS I get the following output:
```
String.Compare("ß", "ss", false, System.Globalization.CultureInfo.InvariantCulture): 1
String.Compare("ß", "ss", true, System.Globalization.CultureInfo.InvariantCulture): 1
String.Compare("xssx", "xßx", true, System.Globalization.CultureInfo.InvariantCulture): -1
String.Compare("\xDF", "ss", false, System.Globalization.CultureInfo.InvariantCulture): 1

String.Compare("ß", "ss", StringComparison.OrdinalIgnoreCase): 1
String.Compare("xssx", "xßx", StringComparison.OrdinalIgnoreCase): -1
String.Compare("\xDF", "ss", StringComparison.OrdinalIgnoreCase): 1

String.Compare("ß", "ss", StringComparison.InvariantCultureIgnoreCase): 1
String.Compare("xssx", "xßx", StringComparison.InvariantCultureIgnoreCase): -1
String.Compare("\xDF", "ss", StringComparison.InvariantCultureIgnoreCase): 1

String.Compare("ß", "ss", StringComparison.CurrentCulture): 1
String.Compare("xssx", "xßx", StringComparison.CurrentCulture): -1
String.Compare("\xDF", "ss", StringComparison.CurrentCulture): 1
```

**Comment by GrabYourPitchforks** [comment] 2020-03-04 18:45
@tarekgh Do you know if our calls into libicu are different on MacOSX vs. Linux?

**Comment by tarekgh** [comment] 2020-03-04 18:55
@GrabYourPitchforks  

> Do you know if our calls into libicu are different on MacOSX vs. Linux?

No, we should have the same behavior on Mac OS and Linux. The behavior is different from Windows because of the collation strength differences we are using on Linux. 

This is the duplicate of the issue https://github.com/dotnet/runtime/issues/20599 and the way make it work is to do https://github.com/dotnet/runtime/issues/20599#issuecomment-374791597. basically you need to use CompareOptions.IgnoreNonSpace in the comparison to get the desired behavior on both Windows and Linux/MacOS

**Comment by tarekgh** [comment] 2020-03-04 18:59
@kastonework I am closing this issue but feel free to respond back with any question or request and we'll be happy to assist you with. Thanks for your report.

**Closed by tarekgh** 2020-03-04 18:59 UTC
Labels: area-System.Globalization, question
