### ISSUE TITLE
System.Text.Json: Calling Write method of default dictionary converter from a custom dictionary converter fails with NRE

### ISSUE THREAD

**Issue by elgonzo** [dotnet/runtime#106697] opened 2024-08-20 14:37 UTC
### Description

STJ version: 9.0.0-preview.7.24405.7

Given is an example custom `Dictionary<string, int>` dictionary converter (stripped down to the bits essential to the issue at hand) which invokes the default dictionary converter (obtained from `JsonSerializerOptions.Default`) in its Write method.
```C#
class CustomIntDictionaryConverter : JsonConverter<Dictionary<string, int>>
{
    public override Dictionary<string, int>? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        => throw new NotImplementedException();

    public override void Write(Utf8JsonWriter writer, Dictionary<string, int> value, JsonSerializerOptions options)
    {
        var c = (JsonConverter<Dictionary<string, int>>) JsonSerializerOptions.Default.GetConverter(typeof(Dictionary<string, int>));
        c.Write(writer, value, options);
    }
}
```
Serializing a `Dictionary<string, int>` dictionary using this converter fails with a NRE in the default converter's internal `OnTryWrite` method because it looks like `state.Current.JsonTypeInfo.ElementTypeInfo` is null when trying to get `jsonTypeInfo.ElementTypeInfo!.PropertyInfoForTypeInfo`:
https://github.com/dotnet/runtime/blob/9876ed1b72bb82018cdf18f0e8780c721cf806cd/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Collection/JsonDictionaryConverter.cs#L361

### Reproduction Steps

```C#
var dictInt = new Dictionary<string, int>
{
    ["Foo"] = 0,
    ["Bar"] = 1,
    ["Baz"] = 2
};

var opts = new JsonSerializerOptions();
opts.Converters.Add(new CustomIntDictionaryConverter());

string json = JsonSerializer.Serialize(dictInt, opts);


class CustomIntDictionaryConverter : JsonConverter<Dictionary<string, int>>
{
    public override Dictionary<string, int>? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        => throw new NotImplementedException();

    public override void Write(Utf8JsonWriter writer, Dictionary<string, int> value, JsonSerializerOptions options)
    {
        var c = (JsonConverter<Dictionary<string, int>>) JsonSerializerOptions.Default.GetConverter(typeof(Dictionary<string, int>));
        c.Write(writer, value, options);
    }
}
```

### Expected behavior

The dictionary should be deserialized normally without exceptions.

### Actual behavior

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryWrite(Utf8JsonWriter writer, TDictionary dictionary, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonResumableConverter`1.Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
   at CustomIntDictionaryConverter.Write(Utf8JsonWriter writer, Dictionary`2 value, JsonSerializerOptions options) in X:\ConsoleApp1\ConsoleApp1\Program.cs:line 153
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Serialize(Utf8JsonWriter writer, T& rootValue, Object rootValueBoxed)
   at System.Text.Json.JsonSerializer.WriteString[TValue](TValue& value, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at Program.Main() in X:\ConsoleApp1\ConsoleApp1\Program.cs:line 42
```

### Regression?

Not sure, but i don't think so.
I tested also with 8.0.4, 8.0.0, as well as 7.0.4, and these three also throw an NRE.

### Known Workarounds

So far I got no idea for a workaround except (re)implementing the dictionary serialization logic in the custom converter. Which can become quite burdensome if the custom converter is using a generic type parameter for the dictionary value type (with the help of a converter factory).

### Configuration

.NET version: 8.0
STJ version: 9.0.0-preview.7.24405.7
OS: Windows 11 x64

**Comment by eiriktsarpalis** [comment] 2024-08-27 08:33
Duplicate of #50205. Built-in converters not being usable outside of their configuration context is a known defect of the STJ serialization infrastructure.

**Closed by eiriktsarpalis** 2024-08-27 08:33 UTC
Labels: area-System.Text.Json, needs-further-triage
