### ISSUE TITLE
Marshal.PtrToStructure support in reflection free Native AOT

### ISSUE THREAD

**Issue by Fabi** [dotnet/runtime#70837] opened 2022-06-16 16:15 UTC
Hey,

while working on a project/lib and tried to make it reflection free I noticed that Marshal.PtrToStructure actually throws "Reflection_Disabled" due to it's usage of Activator.CreateInstance. Marshal.StructureToPtr works fine though.

That makes functions like `NetworkInterface.GetAllNetworkInterfaces` that result in `SystemNetworkInterface.GetNetworkInterfaces` calls unusable in reflection free mode.

Are there any plans to fix that or any (safe) alternatives?

**Comment by jkotas** [comment] 2022-06-16 19:01
We have no plans to make Marshal.PtrToStructure work in reflection-free mode. Duplicate of #67193.

However, we are usually happy to take PRs to eliminate `Marshal.PtrToStructure` usage and replace it with manual marshalling that is typically faster and less error prone.

**Closed by jkotas** 2022-06-16 19:01 UTC
Labels: untriaged, area-NativeAOT-coreclr

**Comment by Fabi** [comment] 2022-06-16 19:06
> We have no plans to make Marshal.PtrToStructure work in reflection-free mode. Duplicate of #67193.
> 
> However, we are usually happy to take PRs to eliminate `Marshal.PtrToStructure` usage and replace it with manual marshalling that is typically faster and less error prone.

But isn't this just due to the non generic Activator.CreateInstance usage? The generic one works due to the analyzer catching it and keeping data for it. There is no switch that let us keep data for the non generic function (which calls the non generic one and really not more)

**Comment by jkotas** [comment] 2022-06-17 00:14
`Marshal.PtrToStructure` cannot just use the generic `Activator.CreateInstance`. `Marshal.PtrToStructure` allows private constructors that the generic `Activator.CreateInstance` disallows. Implementing a special version of the generic `Activator.CreateInstance` just to make this legacy API work in reflection-free mode is not worth it.

**Comment by jkotas** [comment] 2022-06-17 01:58
I have fixed up `PtrToStructure` instances you have mentioned and a few more in #70866
