### ISSUE TITLE
[API Proposal]: MaxOrDefault, MinOrDefault

### ISSUE THREAD

**Issue by ph1l1pF** [dotnet/runtime#107370] opened 2024-09-04 19:49 UTC
### Background and motivation

```csharp
var x = new int[] { };
var max = x.Max();
```
This throws an exception: `System.InvalidOperationException: Sequence contains no elements`

I would like something like this.

```csharp
var x = new int[] { };
var max = x.MaxOrDefault();
```

resulting in `max` with the value `0` in this case.

I don't care whether the sequence is empty. I want to have the current maximum/minimum regardless and then get the next higher value. The proposed methods would make that use case easier.

### API Proposal

```csharp
namespace System.Linq;

public static T? MaxOrDefault<T>(this IEnumerable<T?> source) => source.DefaultIfEmpty().Max();

public static T? MinOrDefault<T>(this IEnumerable<T?> source) => source.DefaultIfEmpty().Min();
```

### API Usage

```csharp
var x = new int[] { };
var max = x.MaxOrDefault();
var min = x.MinOrDefault();
```

### Alternative Designs

none

### Risks

none

**Comment by KeterSCP** [comment] 2024-09-04 22:44
Duplicate of https://github.com/dotnet/runtime/issues/55138

**Closed** 2024-09-09 10:45 UTC
Labels: api-suggestion, area-System.Linq, untriaged
