### ISSUE TITLE
Bug with System.Linq.Enumerable.Average<long>(this IEnumerable<long> source) method

### ISSUE THREAD

**Issue by fengzhenqiong** [dotnet/runtime#30697] opened 2019-08-27 14:43 UTC
Seems there's something wrong with the `System.Linq.Enumerable.Average<long>(this IEnumerable<long> source)` method.

Let's say, if I have a collection with only two large numbers (larger than 2^62), if I call this method it will throw System.OverflowException saying that "Arithmetic operation resulted in an overflow".

I used the following code:
`
var numbers = new[] {8000000000000000002L, 7999999999999999998L};
Console.WriteLine(numbers.Average());
`

I also had a look at the source code in .NET Framework 4.8 and seems this problem is there, too. Is this a bug (I think it is), or do you have other considerations?

Anyway, fixing this problem is quite straightforward so I think maybe we should get rid of it.

Thanks.

**Comment by eiriktsarpalis** [comment] 2020-11-27 09:50
> In practice, there's a big difference between having an IEnumerable<int> with 4294967296 elements and an IEnumerable<long> with 2.

Isn't this a by-design restriction though? It reproduces with the `decimal` overload as well:
```csharp
Enumerable.Repeat(long.MaxValue, 2).Average();
``` 
and there are no clear workarounds for that type. I like the fact that it throws since it provides a clear signal that I'm probably doing something wrong: per @tannergooding's argument chances are that a mean represented by `double` would likely be useless.

For the same reason, I'm not convinced we should be implementing a `BigInteger` overload, since `double` would not be a good representation for the kinds of magnitudes the overload is meant to address. We also don't have a `BigDecimal` or `BigRational` implementation readily available.

@fengzhenqiong assuming you're willing to accept a loss of precision, perhaps calculating an iterative mean might be a good fit for your use case. As an example, the Math.NET nuget package has a [RunningStatistics implementation](https://github.com/mathnet/mathnet-numerics/blob/8cdd91d37f36cb4daecc7838898a08ef9c3aa1a4/src/Numerics/Statistics/RunningStatistics.cs#L103) (admittedly it only works with doubles).

**Comment by fengzhenqiong** [comment] 2020-11-28 11:16
@stephentoub  @Clockwork-Muse @tannergooding @eiriktsarpalis 

Just want to share an implementation here that will probably be able to calculate the average of large numbers (in this case it's Int64, but it can also be used in other types, Int128, Decimal, etc.):

`
Int64 ComputeAvarage(IEnumerable<Int64> data)
{
    if (data == null)
        throw new ArgumentNullException("data");

    if (!data.Any()) return 0L;

    Int64 cnt = 1L;
    Int64 avg = data.First(), carry = 0;

    foreach (var item in data.Skip(1))
    {
        ++cnt;
        carry += item - avg;

        if (carry <= -cnt || cnt <= carry)
        {
            var temp = carry / cnt;
            avg += temp;
            carry -= temp * cnt;
        }
        if (carry < 0)
        {
            --avg;
            carry += cnt;
        }
    }

    return avg;// +((Double)carry / cnt);
}
`

It returns Int64 but the commented codes in last line can make it return double.

I just did some simple tests and it seems the performance is almost same as the Decimal version, following is the result which calculate the **last 100000001 largest Int64** numbers, both version took about 2 secs:

Number set: **RangeInt64(Int64.MaxValue - 100000000, 100000001)**

2020-11-28T19:01:51.6389464+08:00
**This Version:**    9223372036804775807
2020-11-28T19:01:53.6810632+08:00
**Decimal Version:** 9223372036804775807
2020-11-28T19:01:55.7211799+08:00

I also test this algorithm with small numbers and the performance is about 2.5x slower than the current average algorithm. But as it provides completeness so maybe you can add this as another overload?

Just for your reference. Thanks for your time.

**Comment by AmrAlSayed0** [comment] 2020-11-28 12:18
I think this is a simpler implementation for the version that returns ```double```:
```csharp
Double ​ComputeAvarage​(​IEnumerable​<​Int64​> ​data​)
{
    ​if​ (​data​ ​==​ ​null​)
        ​throw​ ​new​ ​ArgumentNullException​(​"​data​"​);

    ​if​ (​!​data​.​Any​()) ​return​ ​0;

    ​Int32 ​cnt​ ​=​ ​1​;
    ​Double ​avg​ ​=​ ​0;

    ​foreach​ (​Int64 ​item​ ​in​ ​data​)
    {
        
        ​avg ​+=​ ​(item - avg)/cnt;
        cnt++;
    }

    ​return​ ​avg​;
}```

**Comment by fengzhenqiong** [comment] 2020-11-28 12:46
Surely this is simpler, just wondering about the accuracy for `double` in large iteration, seems there will be precision loss and cannot get the accurate result.

**Comment by Clockwork-Muse** [comment] 2020-11-29 03:48
@AmrAlSayed0 - Your version gives a different result than the current implementation if the first input is sufficiently large, and the second input sufficiently small, due to double precision issues.  

That's outside the issue of whether a "moving average" generates results acceptably.

**Comment by eiriktsarpalis** [comment] 2021-04-22 14:27
I'm going to close this issue as by-design. The workarounds proposed mitigate the issue only partially and incur a performance penalty that is not pay-for-play. LINQ averages are only intended for basic usage, and there exist alternatives in the nuget ecosystem that can be better at calculating averages in more demanding scenaria.

**Closed by eiriktsarpalis** 2021-04-22 14:27 UTC
Labels: area-System.Linq, documentation, untriaged
