### ISSUE TITLE
.NET 7 issue with `IntPtr` when `LangVersion` < 8 

### ISSUE THREAD

**Issue by viniciusjarina** [dotnet/runtime#78878] opened 2022-11-26 21:25 UTC
### Description

If you try to use C# `LangVersion` = 7 it fails to do any operation with `IntPtr`

```
        void Func()
        {
            IntPtr foo = IntPtr.Zero;
            IntPtr foo2 = IntPtr.Zero;

            if (foo2 == foo)
            {

            }
        }
```

```
error CS8107: Feature 'native-sized integers' is not available in C# 7.0. Please use language version 9.0 or greater
```

### Reproduction Steps

File New Project > Library > Change C# version to 7 
Try to use IntPtr `==` operator 

### Expected behavior

It should just build fine. (On all previous versions this was working fine)

### Actual behavior

Build error
```
error CS8107: Feature 'native-sized integers' is not available in C# 7.0. Please use language version 9.0 or greater
```

### Regression?

Yes, since it build fine on .NET 6

### Known Workarounds

Force the LangVersion to 9, but this is not the solution since some projects might require to use old versions of C#.

### Configuration

VSMac 17.4 + .NET 7 7.0.100

**Comment by saucecontrol** [comment] 2022-11-26 21:43
This was an issue with the Roslyn compiler https://github.com/dotnet/roslyn/issues/64059.  It has been fixed, but the fix didn't make the cut for the .NET 7 SDK release.  I believe it should be in the first servicing update.

**Comment by jkotas** [comment] 2022-11-27 00:10
Duplicate of https://github.com/dotnet/roslyn/issues/64059

**Closed by jkotas** 2022-11-27 00:10 UTC
Labels: area-System.Numerics, untriaged
