### ISSUE TITLE
sbyte* is not same as byte*

### ISSUE THREAD

**Issue by DeafMan1983** [dotnet/runtime#110462] opened 2024-12-06 00:05 UTC
[string(sbyte* value)](https://github.com/dotnet/runtime/blob/1d1bf92fcf43aa6981804dc53c5174445069c9e4/src/libraries/System.Private.CoreLib/src/System/String.cs#L183)

I explain you about different byte* and sbyte*

`sbyte*` means `(const) char*` in C and
`byte*` means `unsigned char*` or `uint8*` in C.

Why do you use strlen with byte* ??
Please check ClangSharpPInvokeGenerator because it outputs for `const char*` as `sbyte*`

Please check my SDL2 Wrapper like `void SDL_SetWindowTitle(SDL_Window* window, sbyte* title);`

`byte*` is an embedded data like binary format example bmp, tga or image etc...

Please remember that! strlen has param `char*` and it means `sbyte*` not `byte*`

Thanks! PS: I am shocking because I never see since Net 7.0 with `string(sbyte* value)`

But my package DeafMan1983.Utilities has much conversions.
but it is sensitive for Elten Lee for byte* :(

For `sbyte*` and `char*`(UTF16) in C# for Windows like `TerraFX.Interop.Windows`

I hope you understand my English...

**Comment by colejohnson66** [comment] 2024-12-06 00:33
Whether `char` is signed or unsigned is implementation defined.

**Comment by huoyaoyuan** [comment] 2024-12-06 05:08
ClangSharp question should go to its own repository https://github.com/dotnet/ClangSharp

The runtime repo has specified char as signed with compiler switch:

https://github.com/dotnet/runtime/blob/457114c7a4346bce3ef13d6f48c9bd708083efb7/eng/native/configurecompiler.cmake#L656-L658

For ClangSharp usage, you can also specify char as signed with `--remap` option.

**Comment by richlander** [comment] 2024-12-06 15:35
Issue titles should be kept to just the problem and should avoid any judgement words.

**Comment by tannergooding** [comment] 2024-12-06 17:18
As the author of ClangSharp, the reason it chooses `sbyte*` is because it is by design generating 1-to-1 "blittable" signatures by default. As has been covered above, most ecosystems default to treating `char` as `signed` by default and correspondingly that is what `Clang` will report and what needs to be generated.

In C, barring additional annotations (such as manual attributes or SAL like annotations which are non-standard and fairly uncommon), it is impossible to discern automatically whether a `char*` is a null-terminated string, a pointer to a buffer (effectively an array), a pointer to a single character, etc. So the only "correct" thing to do is to preserve the signature as is by default. This also helps avoid potential ABI issues such as whether the type being signed vs unsigned types is important (a `char` with the value `0xFF` when upcast to `int` becomes `0xFFFFFFFF` if treated as signed and `0x000000FF` if treated as unsigned, after all).

.NET for strings in particular has often (but not always) used `byte`. This is particularly relevant to UTF8 strings which are typically represented as `ReadOnlySpan<byte>` and where the concept of negative (which would be invalid values for something like `ASCII`) may no longer make sense. It is an opinion and one that doesn't strictly relate to what C or C++ uses and what is "most correct" for interop purposes.

**Comment by DeafMan1983** [comment] 2024-12-10 11:23
@huoyaoyuan What is a judgement word? For what are you talking about?

@tannergooding thanks!

Example for `sbyte*` and `string`:
```
[DllImport("libc", EntryPoint = "strlen")]
private static unsafe extern nuint strlen(sbyte* str);

static unsafe string SBytePtrToString(sbyte* value)
{
    if (value == null)
        return string.Empty;

    nuint length = strlen(value);
    int len = (int)length;

    sbyte[] buffer = new sbyte[len];
    for (int i = 0; i < len; i++)
    {
        buffer[i] = value[i];
    }

    char[] chars = new char[len];
    for (int i = 0; i < len; i++)
    {
        chars[i] = (char)buffer[i];
    }

    return new string(chars);
}

static unsafe sbyte* StringToSBytePtr(string value)
{
    if (value == null)
        return null;

    sbyte[] buffer = new sbyte[value.Length + 1];
    for (int i = 0; i < value.Length; i++)
    {
        if (value[i] > sbyte.MaxValue)
            Console.WriteLine("String contains characters that cannot be represented as sbyte.");

        buffer[i] = (sbyte)value[i];
    }

    buffer[value.Length] = 0;

    fixed (sbyte* ptr = buffer)
    {
        return ptr;
    }
}
```

But I will look for some unsupported characters like Chinese alphabets.

Why do I not care about `byte*` because it is data of file or binary. but it is not same to string example:

`fread`/`frwrite` from `stdio.h`:

```
byte* bmp_data = stackalloc byte[width * height * 4];
if (bmp_data == null)
{
    Console.WriteLine("Error: data is null.");
}

fread(bmp_data, bmp_size, (nuint)(width * height * 4), file);
```

`sbyte*` like `char*` from `string.h`

```
sbyte* hello_world = StringToSbytePtr("Hello World!");
nuint length_of_hello_world = strlen(hello_world);
Console.WriteLine("Length of string: {0}", length_of_hello_world);
```

Result:
```
Length of string: 12
```
Proof of screenshot:
![Image](https://github.com/user-attachments/assets/5a3ff709-256a-4752-a2ed-05333cb27b78)

That is all for `sbyte*` and `byte*`

I hope you understand. but 0xffffffff is like uint as uint* for pixel format like this SDL2/3 `void* pixels` from `SDL_Surface*` Since I made SetPixel with `surface->pixels` but it casts to `uint*`.

**Comment by richlander** [comment] 2024-12-10 15:28
> What is a judgement word? For what are you talking about?

The issue title started with "This is wrong!!!!". That is pretty aggressive and casts very definite judgement on our design choices/implementation. We don't talk like that here. When a new person comes to this org, I don't want them to see issues worded like that. It's not welcoming. That's why I edited your issue title.

Design choices are always tradeoffs. It's perhaps best to start these conversations by seeking to better understand those tradeoffs. I was glad to see that Tanner addressed those tradeoffs for you.

**Comment by DeafMan1983** [comment] 2024-12-10 23:30
> This is wrong!

Because I saw why does Microsoft use `byte*` inside `String(sbyte* value)` I saw inside block of construction of string but why do developers like SDL2-CS. That's not judgement word cause problem with different with byte* and sbyte* made me painfully.

Why sbyte* is like in C as char* and byte* is like unit8_t* or unsigned char* if you see in SDL2 example and they use uint8_t* and color manipulation with pixels. Since I have tried to create OOP construction with SDL2 like GtkSharp3 if SDL_GetError() doesn't show up in `Console.WriteLine()` like `invalid window` or `invalid renderer`. SDL2 uses IntPtr but why does developer of SDL2-CS use byte"? Is he also Microsoft Developer? For my sbyte*-string manipulation works as well without helping avoiding marshaling, encoding or string(sbyte* value).

Ok I am very disappointed because Microsoft use `byte*`. How do I can replace it? If I may not access to Dotnet runtime like reference System. But I really want to use respectful with `sbyte*` without helping Marshal or Encoding from reference? Should I create own?

**Comment by colejohnson66** [comment] 2024-12-11 00:45
In C (on desktop computers), the sizes of `char`, `unsigned char`, `signed char`, `int8_t`, and `uint8_t` are all the same: 1. In C#, `byte` and `sbyte` have the same size. Neither one is more correct. As @tannergooding said, `sbyte` was used to match Clang (which treats `char` as signed by default). `byte` could’ve been used with minor changes, but the size of the data would still be the same.

**Comment by tannergooding** [comment] 2024-12-14 17:06
Looks like this has been answered/resolved as best as possible. I'd recommend closing this if nothing further is needed.

As indicated there are distinctions between what C wants/expects for their character types (which was originally centered around `ASCII` or system code pages, later expanding to support Unicode) and what .NET wants/expects (which started centered around `Unicode`). For the cases where you need to interoperate between them, you can simply cast from `byte*` to `sbyte*` or vice-versa.

Such casts are largely only needed in the interop space, where it is expected that you may need to do such things to ensure correct interchange between the two separate languages/runtimes.

**Closed** 2024-12-15 17:29 UTC
Labels: question, area-System.Runtime, needs-author-action
