### ISSUE TITLE
Property duplication on overriding property with [JsonPropertyName]

### ISSUE THREAD

**Issue by PSanetra** [dotnet/runtime#97648] opened 2024-01-29 14:58 UTC
### Description

On serializing a derived class overridden properties may be duplicated if `[JsonPropertyName]` is assigned.

### Reproduction Steps

Create the following classes:

```csharp
public class VirtualProperty_TestClass
{
    public virtual string MyString { get; set; }
}

public class OverridePropertyNameInDerivedClass_TestClass : VirtualProperty_TestClass
{
    [JsonPropertyName("my_string")]
    public override string MyString { get; set; }
}
```

Then serialize an instance of `OverridePropertyNameInDerivedClass_TestClass` like this:

```csharp
string serialized = JsonSerializer.Serialize(new OverridePropertyNameInDerivedClass_TestClass()
{
    MyString = "MyValue"
});
Assert.Equal(@"{""my_string"":""MyValue""}", serialized);
```

### Expected behavior

This serialized string should be equal to `{"my_string":"MyValue"}`.

### Actual behavior

This serialized string is equal to `{"my_string":"MyValue","MyString":"MyValue"}`.

### Configuration

.NET: 8.0.0
OS: Linux
Arch: x64
System.Text.Json: 8.0.0

### Other information

Known affected code:
`OpenIdConnectConfiguration.Issuer` in [Microsoft.IdentityModel.Protocols.OpenIdConnect](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/tree/dev/src/Microsoft.IdentityModel.Protocols.OpenIdConnect) is inherited from `BaseConfguration.Issuer` in [Microsoft.IdentityModel.Tokens](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/2cf55c2c5afb2e2c4fc0c05cd961717299be6e59/src/Microsoft.IdentityModel.Tokens/BaseConfiguration.cs)

Because of this issue serializing a `OpenIdConnectConfiguration` instance will create a json object with both an `issuer` and `Issuer` property. Some other properties like `TokenEndpoint` are affected, too.

**Comment by eiriktsarpalis** [comment] 2024-01-29 15:35
Appears to be a duplicate of https://github.com/dotnet/runtime/issues/51165

**Closed by eiriktsarpalis** 2024-01-29 15:35 UTC
Labels: area-System.Text.Json, untriaged
