### ISSUE TITLE
Test failure System.IO.Tests.FileStream_DisposeAsync.DisposeAsyncFlushes

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#65872] opened 2022-02-25 01:27 UTC
Run: [runtime-coreclr libraries-jitstress 20220223.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1629873&view=ms.vss-test-web.build-test-results-tab&runId=45214198&resultId=173700&paneView=debug)

Failed test:
```
net7.0-windows-Release-x86-CoreCLR_checked-jitstress1_tiered-Windows.10.Amd64.Open

- System.IO.Tests.FileStream_DisposeAsync.DisposeAsyncFlushes

```
**Error message:**
```
Assert.Equal() Failure
Expected: 100
Actual:   200


Stack trace
   at System.IO.Tests.FileStream_DisposeAsync.DisposeAsyncFlushes() in /_/src/libraries/System.IO.FileSystem/tests/FileStream/DisposeAsync.cs:line 39
--- End of stack trace from previous location ---
```

**Comment by MaximLipnin** [comment] 2022-02-25 06:54
It's a dupe of https://github.com/dotnet/runtime/issues/65835

**Closed by MaximLipnin** 2022-02-25 06:54 UTC
Labels: arch-x86, area-System.IO, os-windows, JitStress, untriaged
