### ISSUE TITLE
Random "Internal CLR error. (0x80131506)" when calling dotnet build from dotnet/extensions

### ISSUE THREAD

**Issue by jkotalik** [dotnet/runtime#2150] opened 2020-01-24 18:37 UTC
I'm running into an error fairly consistently when building the dotnet/extensions repo (2 times in a row). I cleaned before the second run as well.

### Repro steps
1. Clone https://github.com/dotnet/extensions. Specific commit hash is bcf0ef7e8f94b178214b34fe78fedc7205810434 if this doesn't repro after a dependency update.
2. Run build.cmd inside of the root of the project.

During that build, I see a fatal error coming from the CLR:
```
Fatal error.   Microsoft.Extensions.Options -> extensions\artifacts\bin\Microsoft.Extensions.Options-ref\Debug\netstandard2.0\Microsoft.Extensions.Options.dll
Internal CLR error. (0x80131506)
   at System.StubHelpers.MngdFixedArrayMarshaler.ConvertContentsToManaged(IntPtr, System.Object ByRef, IntPtr)
   at System.Runtime.InteropServices.Marshal.PtrToStructureHelper(IntPtr, System.Object, Boolean)
   at System.Runtime.InteropServices.Marshal.PtrToStructureHelper(IntPtr, System.Type)
   at System.Runtime.InteropServices.Marshal.PtrToStructure(IntPtr, System.Type)
   at System.Runtime.InteropServices.Marshal.PtrToStructure[[Interop+IpHlpApi+IpAdapterAddresses, System.Net.NetworkInformation, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]](IntPtr)
   at System.Net.NetworkInformation.SystemNetworkInterface.GetNetworkInterfaces()
   at System.Net.NetworkInformation.SystemNetworkInterface.InternalGetIsNetworkAvailable()
   at System.Net.NetworkInformation.NetworkInterface.GetIsNetworkAvailable()
   at Microsoft.DotNet.Cli.Telemetry.PersistenceChannel.Sender.Send(Microsoft.DotNet.Cli.Telemetry.PersistenceChannel.StorageTransmission, System.TimeSpan ByRef)
   at Microsoft.DotNet.Cli.Telemetry.PersistenceChannel.Sender.SendLoop()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task+<>c.<.cctor>b__274_0(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
   at System.Threading.Tasks.ThreadPoolTaskScheduler+<>c.<.cctor>b__10_0(System.Object)
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)
```

**Comment by jkotalik** [comment] 2020-01-24 18:38
Oops, sorry for messing up the labels XD

**Comment by jkoritzinsky** [comment] 2020-01-24 18:39
That's fine haha. I'll take a look into this.

**Comment by jkoritzinsky** [comment] 2020-01-24 21:42
I'm having trouble reproducing this. Any chance you're able to grab a crashdump of the failure?

**Comment by danmosemsft** [comment] 2020-01-24 21:53
@jkotalik what version of .NET is this running on? I remembered https://github.com/dotnet/corefx/issues/42201 which @jkoritzinsky already fixed (?)

**Comment by jkoritzinsky** [comment] 2020-01-24 22:22
@danmosemsft you make a very good point.

I've done some investigating, and it looks like the dotnet/extensions repo's CLI is using a runtime built from dotnet/coreclr@cea2bba3c295c5, which was after the change that introduced the bug but before the fix.

I'm willing to call this a duplicate of dotnet/corefx#42201.

**Comment by jkotalik** [comment] 2020-01-24 22:23
Yeah go ahead and dup it! Thanks for investigating.

**Closed** 2020-01-24 22:22 UTC
Labels: area-Interop
