### ISSUE TITLE
System.Text.Json doesn't integrate with xUnit

### ISSUE THREAD

**Issue by azydevelopment** [dotnet/runtime#34272] opened 2020-03-30 08:52 UTC
Regarding this: https://andrewlock.net/creating-a-custom-xunit-theory-test-dataattribute-to-load-data-from-json-files/

Using this technique with System.Text.Json seems to be impossible because it always wraps things in JsonElements.

Security isn't a valid concern here because it's only used in internal tests.

Am I missing something? Specifically, this line wraps it in JsonElements instead of say..strings.

`return data.ToObject<List<object[]>>();`

**Comment by Clockwork-Muse** [comment] 2020-03-30 15:47
> You may have also noticed that the `GetData()` method is supplied a `MethodInfo` parameter. If you wanted, you could update the `JsonFileDataAttribute` to automatically use the theory test method name as the JSON sub-property, but I'll leave that as an exercise!

... or you could use the `MethodInfo` to get the parameters of the method, and (attempt to) deserialize based on the parameter names and types.  

See also [this feature comparison](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to#deserialization-of-object-properties)

**Comment by layomia** [comment] 2020-03-30 17:44
The serializer returns `JsonElement` instances when deserializing `System.Object` instances. See the [JSON docs](https://docs.microsoft.com/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to#deserialization-of-object-properties) for more information. There's an issue to add an option to return boxed primitives where applicable - https://github.com/dotnet/runtime/issues/29960.

A workaround for you scenario is to add a custom converter, similar to https://github.com/dotnet/runtime/blob/3e4a06c0e90e65c0ad514d8e2a9f93cb584d775a/src/libraries/System.Text.Json/tests/Serialization/CustomConverterTests.Object.cs#L267

In your example, rather than

```C#
return JsonConvert.DeserializeObject<List<object[]>>(fileData);
```

you would have

```C#
JsonSerializerOptions options = new JsonSerializerOptions();
options.Converters.Add(new SystemObjectNewtonsoftCompatibleConverter());

return JsonSerializer.Deserialize<List<object[]>>(fileData, options);
```

Closing as duplicate of https://github.com/dotnet/runtime/issues/29960.

**Closed by layomia** 2020-03-30 17:44 UTC
Labels: area-System.Text.Json, untriaged
