### ISSUE TITLE
[dotnet-sdk-6.0.100-rc.2.21454.3]  Cannot create instance of type 'Sentry.Dsn' when launch just-an-email

### ISSUE THREAD

**Issue by Junjun-zhao** [dotnet/runtime#58852] opened 2021-09-09 06:03 UTC
**Application Name**: just-an-email
**OS**: Windows 10 RS5
**CPU**: X64
**.NET Build Number**: dotnet-sdk-6.0.100-rc.2.21454.3

**Verify Scenarios**:

1). Windows rs5 x64 + dotnet-sdk-6.0.100-rc.1.21451.16: Sentry Package2.1.5:Pass
2). Windows rs5 x64 + dotnet-sdk-6.0.100-rc.2.21454.3+Sentry Package 3.0.0:Pass
3). Windows rs5 x64 + dotnet-sdk-6.0.100-rc.2.21454.3+Sentry Package2.1.5: Fail
4). Windows rs5 x64 + dotnet-sdk-6.0.100-rc.2.21457.4+Sentry Package2.1.5: Fail
5). Windows rs5 x64 + dotnet-sdk-6.0.100-rc.2.21458.9+Sentry Package2.1.5: Fail

**Github Repo link:** https://github.com/mustakimali/just-an-email
**App Source and App checking at** :https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1396752

**Repro steps**:
This is 6.0 app upgraded from .NET Core 3.1.

1.Launch application “JustSending.exe”.  
2.Access http://localhost:5000 using Edge.

**Expected Result**:
The app is launched successfully.

**Actual Result**:
Failed to launch the app with exception that Cannot create instance of type 'Sentry.Dsn'.

**Exception Details**:
```
System.InvalidOperationException: Cannot create instance of type 'Sentry.Dsn' because it is missing a public parameterless constructor.
   at Microsoft.Extensions.Configuration.ConfigurationBinder.CreateInstance(Type type)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.GetPropertyValue(PropertyInfo property, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindNonScalar(IConfiguration configuration, Object instance, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Bind(IConfiguration configuration, Object instance, Action`1 configureOptions)
   at Microsoft.Extensions.Options.NamedConfigureFromConfigurationOptions`1.<>c__DisplayClass1_0.<.ctor>b__0(TOptions options)
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Microsoft.AspNetCore.Builder.ApplicationBuilderExtensions.UseSentry(IApplicationBuilder app)
   at Sentry.AspNetCore.SentryStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder e)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
 ```

**Minimal Repro steps**:

1) Create ASP.NET Core MVC Project(.NET Core 3.1) and then retarget it to .NET 6.0. 
2) Install Sentry.AspNetCore Package2.1.5. 
3) Add settings to aspsettings.
```
 "Sentry": {
    "Dsn": ""
  }
```
4) use Sentry:
```
 public class Program
    {
        public static void Main(string[] args)
        {
            BuildWebHost(args).Build().Run();
        }

        public static IHostBuilder BuildWebHost(string[] args) =>
           Host.CreateDefaultBuilder(args)
               .ConfigureWebHostDefaults(builder =>
               {
                   builder
                       .UseSentry()
                       .UseStartup<Startup>();
               })
    }
```
4) Build and Run

**Expected Result:** 
Page should be loaded successfully

**Actual Result**:
```
System.InvalidOperationException: Cannot create instance of type 'Sentry.Dsn' because it is missing a public parameterless constructor.
   at Microsoft.Extensions.Configuration.ConfigurationBinder.CreateInstance(Type type)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.GetPropertyValue(PropertyInfo property, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty(PropertyInfo property, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindNonScalar(IConfiguration configuration, Object instance, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config, BinderOptions options)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Bind(IConfiguration configuration, Object instance, Action`1 configureOptions)
   at Microsoft.Extensions.Options.NamedConfigureFromConfigurationOptions`1.<>c__DisplayClass1_0.<.ctor>b__0(TOptions options)
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Microsoft.AspNetCore.Builder.ApplicationBuilderExtensions.UseSentry(IApplicationBuilder app)
   at Sentry.AspNetCore.SentryStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder e)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
```
**Additional Information:**
Sentry has a big change in 3.0.0 version. This issue doesn't repro with this version.
You can see https://github.com/getsentry/sentry-dotnet/releases?after=3.2.0 
For Dsn:
Dsn is just a string
SentryOptions now take a string for Dsn:

Before: ```o.Dsn = new Dsn("..")```;
After: ```o.Dsn = ".."```;

In Sentry code , different way to create IwebHostBuilder.
**Before**
```
 public static IWebHostBuilder UseSentry(
            this IWebHostBuilder builder,
            Action<WebHostBuilderContext, SentryAspNetCoreOptions> configureOptions)
        {
            // The earliest we can hook the SDK initialization code with the framework
            // Initialization happens at a later time depending if the default MEL backend is enabled or not.
            // In case the logging backend was replaced, init happens later, at the StartupFilter
            builder.ConfigureLogging((context, logging) =>
            {
                logging.AddConfiguration();
                var section = context.Configuration.GetSection("Sentry");
                logging.Services.Configure<SentryAspNetCoreOptions>(section);

                if (configureOptions != null)
                {
                    logging.Services.Configure<SentryAspNetCoreOptions>(options =>
                    {
                        configureOptions(context, options);
                    });
                }
                logging.Services.AddSingleton<IConfigureOptions<SentryAspNetCoreOptions>, SentryAspNetCoreOptionsSetup>();
                logging.Services.AddSingleton<ILoggerProvider, SentryAspNetCoreLoggerProvider>();
                logging.AddFilter<SentryAspNetCoreLoggerProvider>(
                    "Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware",
                    LogLevel.None);
                logging.Services.AddSentry();
            });
            builder.ConfigureServices(c =>
            {
                c.AddTransient<IStartupFilter, SentryStartupFilter>();
            });
            return builder;
}
```
**After**
```
 public static IWebHostBuilder UseSentry(
            this IWebHostBuilder builder,
            Action<WebHostBuilderContext, SentryAspNetCoreOptions>? configureOptions)
            => builder.UseSentry((context, sentryBuilder) =>
                sentryBuilder.AddSentryOptions(options => configureOptions?.Invoke(context, options)));


public static ISentryBuilder AddSentryOptions(this ISentryBuilder builder,
            Action<SentryAspNetCoreOptions>? configureOptions)
        {
            if (configureOptions != null)
            {
                builder.Services.Configure(configureOptions);
            }

            return builder;
        }
```
@dotnet-actwx-bot @dotnet/compat

**Comment by Junjun-zhao** [comment] 2021-09-16 09:41
Dears, is there any update for this bug? Please help assign if it is not belong to this area? Thanks.

**Comment by maryamariyan** [comment] 2021-09-16 22:18
Will need to check if this is a regression from 5.0 to 6.0

**Comment by Junjun-zhao** [comment] 2021-09-27 13:19
@maryamariyan Thanks for your update. This issue reproduced from .NET 6.0 RC2 and worked well on .NET 6.0 RC1(dotnet-sdk-6.0.100-rc.1.21451.16). Now we are in RC2 validation window, could you please help confirm whether it is a blocker for RC2? Thanks.

**Comment by maryamariyan** [comment] 2021-09-28 17:59
ok thanks. looking

**Comment by eerhardt** [comment] 2021-09-28 18:05
@maryamariyan @safern @vidommet -  I debugged this today and discovered this is a regression due to https://github.com/dotnet/runtime/pull/57204/files#diff-2e6f75e1d4f577e1c8c1b6a32d158ce7812a38ad8fcd3b4d762157b92c03e890R366.

https://github.com/dotnet/runtime/blob/e4a455f26a91932f5de398f0082be83cb9678c36/src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs#L369-L381

The new check added here for `ShouldBindSingleElementsToArray` is causing this code to get into the if, and it calls `CreateInstance`, which is throwing an exception.

It feels like there has been enough feedback on this change that maybe we should consider reverting it for 6.0. Thoughts?

**Comment by safern** [comment] 2021-09-28 18:23
> It feels like there has been enough feedback on this change that maybe we should consider reverting it for 6.0. Thoughts?

Yes, there is another regression caused by this change: https://github.com/dotnet/runtime/issues/58330

I think since this went in so late, we should revert it and then try doing it taking these issues into consideration for 7.0.0. 

I can take care of that. Thanks, @eerhardt for investigating.

**Comment by safern** [comment] 2021-09-28 20:09
I've submitted a PR to revert it on main: https://github.com/dotnet/runtime/pull/59716

**Comment by maryamariyan** [comment] 2021-09-28 20:18
thanks makes sense to revert the change

**Comment by safern** [comment] 2021-09-29 19:33
Closing as we reverted the breaking change.

**Closed by safern** 2021-09-29 19:33 UTC
Labels: area-Extensions-Configuration
