### ISSUE TITLE
Test failure: Interop\\PInvoke\\SizeParamIndex\\ReversePInvoke\\PassingByRef\\PassingByRefTest\\PassingByRefTest.cmd

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#36200] opened 2020-05-11 05:06 UTC
failed in job: [ runtime-coreclr gcstress0x3-gcstress0xc 20200510.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=638720&view=ms.vss-test-web.build-test-results-tab&runId=19856690&resultId=103584&paneView=debug)

Error message
~~~
Assert failure(PID 3248 [0x00000cb0], Thread: 7196 [0x1c1c]): SanityCheck()

CORECLR! MethodTable::Validate + 0x3F (0x00007ff80fb90263)
CORECLR! Object::ValidateInner + 0x130 (0x00007ff80faefc80)
CORECLR! Object::Validate + 0x118 (0x00007ff80faefb08)
CORECLR! GcInfoDecoder::ReportStackSlotToGC + 0x12A (0x00007ff80fd1ca7a)
CORECLR! GcInfoDecoder::ReportSlotToGC + 0x168 (0x00007ff80fd1c934)
CORECLR! GcInfoDecoder::ReportUntrackedSlots + 0x69 (0x00007ff80fd1cc35)
CORECLR! GcInfoDecoder::EnumerateLiveSlots + 0xD6E (0x00007ff80fd1baea)
CORECLR! EECodeManager::EnumGcRefs + 0x389 (0x00007ff80fc6a889)
CORECLR! GcStackCrawlCallBack + 0x2CC (0x00007ff80fdf7eac)
CORECLR! Thread::MakeStackwalkerCallback + 0x6B (0x00007ff80f8c8397)
 File: F:\workspace\_work\1\s\src\coreclr\src\vm\methodtable.cpp Line: 9765
 Image: C:\h\w\A4FA0917\p\CoreRun.exe


Return code: 1
Raw output file: C:\h\w\A4FA0917\w\A72609DB\e\Interop\PInvoke\Reports\Interop.PInvoke\SizeParamIndex\ReversePInvoke\PassingByRef\PassingByRefTest\PassingByRefTest.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\A4FA0917\p\corerun.exe" PassingByRefTest.dll 
ReversePInvoke C-Style Array marshaled by ref with SizeParamIndex attribute(by ref Array size).
Scenario 1 : byte ==> BYTE, Array_Size = byte.MinValue, Return_Array_Size = 20
MarshalByteArray_AsReversePInvokeByRef_AsCdecl Passed!
Scenario 2 : sbyte ==> CHAR, Array_Size = 1, Return_Array_Size = sbyte.Max
MarshalSbyteArray_AsReversePInvokeByRef_AsCdecl Passed!
Scenario 3 : short ==> SHORT, Array_Size = -1, Return_Array_Size = 20
MarshalShortArray_AsReversePInvokeByRef_AsCdecl Passed!
Scenario 4 : short ==> SHORT, Array_Size = 10, Return_Array_Size = -1
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\A4FA0917\p
> C:\h\w\A4FA0917\w\A72609DB\e\Interop\PInvoke\SizeParamIndex\ReversePInvoke\PassingByRef\PassingByRefTest\PassingByRefTest.cmd
Expected: True
Actual: False


Stack trace
   at Interop_PInvoke._SizeParamIndex_ReversePInvoke_PassingByRef_PassingByRefTest_PassingByRefTest_._SizeParamIndex_ReversePInvoke_PassingByRef_PassingByRefTest_PassingByRefTest_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x64.Checked\TestWrappers\Interop.PInvoke\Interop.PInvoke.XUnitWrapper.cs:line 7997
~~~

**Comment by AaronRobinsonMSFT** [comment] 2020-05-11 23:45
I am unable to reproduce this issue locally. I have tried Debug and Checked both with `COMPlus_GCStress=0xC` in a loop. Looking at the history of the test there isn't a lot of changes between when it last passed 8b02df8daca876d7eb28148d899ed9773f1cc495 and where I currently am 18f65b666bd4ff85ab649f4053f46b883541c3e7. I am going to close this for now. Please reopen if it repros.

**Closed by AaronRobinsonMSFT** 2020-05-11 23:45 UTC
Labels: GCStress, area-Interop-coreclr
