### ISSUE TITLE
Blocking scheme changes between 302 redirects

### ISSUE THREAD

**Issue by alpiii** [dotnet/runtime#98523] opened 2024-02-15 13:42 UTC
Hello,

When **HttpClient** is used with **AllowAutoRedirect** set to true, **HttpClient** follows the values provided in **302 replies** and does not complain about scheme changes like from **HTTPS** to **HTTP**. It might be good to have some configurable option to enable blocking scheme changes between redirects with **302 replies** especially from **HTTPS** to **HTTP** regarding security concerns. Is there any plan to add such option or if not, would you consider adding?

Thanks.

**Comment by MihaZupan** [comment] 2024-02-15 21:10
Duplicate of #98497

**Closed by MihaZupan** 2024-02-15 21:10 UTC
Labels: area-System.Net.Http, untriaged
