### ISSUE TITLE
ILC crashes on x64, works on arm64

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/runtime#99611] opened 2024-03-12 15:44 UTC
### Description

ILC crashes on x64, works on arm64.

In other words, this works:

> [...]/packages/runtime.osx-arm64.microsoft.dotnet.ilcompiler/9.0.0-preview.3.24157.12/tools/ilc" @"obj/Debug/net9.0-macos/osx-arm64/native/monotouchtest.ilc.rsp"

this does not:

> [...]/packages/runtime.osx-x64.microsoft.dotnet.ilcompiler/9.0.0-preview.3.24157.12/tools/ilc" @"obj/Debug/net9.0-macos/osx-arm64/native/monotouchtest.ilc.rsp"

### Reproduction Steps

Repro using --make-repro-path: [834971237_monotouchtest.zip](https://github.com/dotnet/runtime/files/14575056/834971237_monotouchtest.zip)

### Expected behavior

Same behavior between arm64 and x64 (preferrably no crashes in either).

### Actual behavior

Crash on x64: https://gist.github.com/rolfbjarne/bfa59a2999b165673b162e65e0c36d53

```
Thread 27 Crashed:
0   <translation info unavailable>	       0x1048c5da0 ???
1   libsystem_platform.dylib      	    0x7ff805c7eff3 _sigtramp + 51
2   libclrjit_universal_arm64_x64.dylib	       0x11b708c86 CodeGen::genCodeForCpObj(GenTreeBlk*) + 934
3   libclrjit_universal_arm64_x64.dylib	       0x11b571d51 CodeGen::genCodeForBBlist() + 1745
4   libclrjit_universal_arm64_x64.dylib	       0x11b56a725 CodeGen::genGenerateMachineCode() + 981
5   libclrjit_universal_arm64_x64.dylib	       0x11b571422 CodeGenPhase::DoPhase() + 34
6   libclrjit_universal_arm64_x64.dylib	       0x11b6aae38 Phase::Run() + 24
7   libclrjit_universal_arm64_x64.dylib	       0x11b56a2bd CodeGen::genGenerateCode(void**, unsigned int*) + 109
8   libclrjit_universal_arm64_x64.dylib	       0x11b578de2 Compiler::compCompile(void**, unsigned int*, JitFlags*) + 6482
9   libclrjit_universal_arm64_x64.dylib	       0x11b57af01 Compiler::compCompileHelper(CORINFO_MODULE_STRUCT_*, ICorJitInfo*, CORINFO_METHOD_INFO*, void**, unsigned int*, JitFlags*) + 1425
10  libclrjit_universal_arm64_x64.dylib	       0x11b57a228 Compiler::compCompile(CORINFO_MODULE_STRUCT_*, void**, unsigned int*, JitFlags*) + 1272
11  libclrjit_universal_arm64_x64.dylib	       0x11b57baab jitNativeCode(CORINFO_METHOD_STRUCT_*, CORINFO_MODULE_STRUCT_*, ICorJitInfo*, CORINFO_METHOD_INFO*, void**, unsigned int*, JitFlags*, void*) + 539
12  libclrjit_universal_arm64_x64.dylib	       0x11b57fd69 CILJit::compileMethod(ICorJitInfo*, CORINFO_METHOD_INFO*, unsigned int, unsigned char**, unsigned int*) + 121

```

### Regression?

Yes, this started happening in a maestro bump (https://github.com/xamarin/xamarin-macios/pull/20249).

So looks like somewhere in this range: https://github.com/dotnet/runtime/compare/5e603d595e63ddc5cdce9777a40608279abdcc37...8510651bc6b5181cf258664c2d0b4b4ff4de1c61

### Known Workarounds

Use an Intel Mac.

**Comment by rolfbjarne** [comment] 2024-03-12 15:45
CC @MichalStrehovsky

**Comment by EgorBo** [comment] 2024-03-12 16:26
Looks like it could be caused by https://github.com/dotnet/runtime/pull/99140

**Comment by EgorBo** [comment] 2024-03-12 16:27
Although, I am not sure, that change only changes arm64 inside the JIT so shouldn't affect x64 🤔

**Comment by EgorBo** [comment] 2024-03-12 16:29
@rolfbjarne I presume it happens on Rosetta, right?

**Comment by EgorBo** [comment] 2024-03-12 16:36
> @rolfbjarne I presume it happens on Rosetta, right?

Ah, it's x64 emitting code for arm64 target (crosscompile)

**Comment by rolfbjarne** [comment] 2024-03-13 07:25
> @rolfbjarne I presume it happens on Rosetta, right?

Both Rosetta and Intel macs.

**Comment by rolfbjarne** [comment] 2024-03-18 08:02
@EgorBo any updates on this?

**Comment by EgorBo** [comment] 2024-03-22 13:26
Sorry for the delay, the repro is not working for me, fails with 
```
System.InvalidOperationException: Expected field '_firstParameter' not found on type '[S.P.CoreLib]System.Delegate'
```
and I don't see an obvious bug in https://github.com/dotnet/runtime/pull/99140, so I decided to revert it in https://github.com/dotnet/runtime/pull/100143 and will take a look at it again later

**Comment by jkotas** [comment] 2024-03-22 15:22
> System.InvalidOperationException: Expected field '_firstParameter' not found on type '[S.P.CoreLib]System.Delegate'

This means that you are using mismatched versions of CoreLib and the compiler. You either need to build the runtime from the point the repro was created, or patch the runtime binaries in the repro.

**Comment by rmarinho** [comment] 2024-03-25 18:40
Seeems we need to test this actually fixes the issue https://github.com/dotnet/runtime/issues/100220

**Comment by rolfbjarne** [comment] 2024-04-05 17:44
@EgorBo any updates on this?

**Comment by EgorBo** [comment] 2024-04-05 18:07
> @EgorBo any updates on this?

Sorry, was busy with internal things. I am not sure I understand why my revert https://github.com/dotnet/runtime/pull/100147 was closed - it was supposed to revert the PR that uncovered this bug untill proper fix is landed into main. In order to unblock you. I am looking into it now

**Comment by rmarinho** [comment] 2024-04-08 14:42
This is blocking us from merging also new android versions of net9 on .net maui since they bump to preview4. Can we get some priority on this please? 

Thanks

**Comment by EgorBo** [comment] 2024-04-08 14:45
https://github.com/dotnet/runtime/pull/100289 is waiting for a review
Like I said, https://github.com/dotnet/runtime/pull/100143 could be used to unblock (was closed by @lewing) you.

**Comment by rolfbjarne** [comment] 2024-04-15 08:19
Looks like this has been fixed now, so I guess this can be closed?

**Comment by MichalStrehovsky** [comment] 2024-04-15 09:12
Yup, doesn't look like any other work to do. Resolved with https://github.com/dotnet/runtime/issues/100220.

**Closed by MichalStrehovsky** 2024-04-15 09:12 UTC
Labels: area-CodeGen-coreclr
