### ISSUE TITLE
UseWindowsService should support some method to invoke ServiceBase.RequestAdditionalTime

### ISSUE THREAD

**Issue by wasabii** [dotnet/runtime#75276] opened 2022-09-08 15:19 UTC
I run into this quite often, having a service which takes longer than 30 seconds to startup. After 30 seconds of startup, the Windows SCM kills the service.

The Windows SCM provides a way to request additional time. ServiceBase.RequestAdditionalTime can be invoked to do this. But it's not exposed inside the Hosting support for Windows Services, nor is there any decent way to get access to it, that I can find.

There's a few ways I can think of to alleviate my issue:

a) Allow me to specify something on WindowsServiceLifetimeOptions to simply request a single amount of time. This is a clean option: but does mean you have to get your time request correct initially. Usage of the API might be something like:

```
builder.UseWindowsService(o => o.ServiceName = sn, initialTimeRequest: TimeSpan.FromSeconds(60));
```

Optional parameter to the UseWindowsService method. At the top of the initialization of ServiceBase, it can just do this one-off. Easy.

b) Expose some sort of callback to the various Startup things that lets services add additional time to themselves. For instance, maybe IHostLifetime can grow a `bool TryRequestAdditionalTime` method, which is implemented by WindowsHostLIfetime, but not by Systemd, Console, etc. Or maybe IHostLifetime2, etc. Something like this.

**Comment by eerhardt** [comment] 2022-09-09 18:37
You can do this today by using a class derived from `WindowsServiceLifetime`, which is derived from `ServiceBase`.

In your builder code, add a Singleton service for `IHostLifetime` for your derived class, so it gets used, and call the method from OnStart :

```C#
builder.UseWindowsService(o => o.ServiceName = sn);
builder.Services.AddSingleton<IHostLifetime, AdditionalTimeLifetime>();
....

class AdditionalTimeLifetime : WindowsServiceLifetime
{
    protected override void OnStart(string[] args)
    {
        base.OnStart(args);

        RequestAdditionalTime(TimeSpan.FromSeconds(60));
    }
}
```

**Comment by jespersh** [comment] 2022-09-26 05:58
We're seeing from procmon boot logging that Windows gets tired of waiting for the service to load its dll's. I am not sure it even gets to OnStart, but investigation will look into this

**Comment by eerhardt** [comment] 2022-09-26 17:15
> We're seeing from procmon boot logging that Windows gets tired of waiting for the service to load its dll's. 

You may want to profile it to see where it is stalling out. One option is to use https://github.com/Microsoft/perfview#perfview-overview or https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-trace#dotnet-trace-collect

**Comment by eerhardt** [comment] 2022-09-26 18:32
> Does anybody agree that something should exist to make it a bit easier? Like something on UseWindowsService itself?

My thinking is that I wouldn't want to duplicate all of the things ServiceBase exposes, especially in a one-off fashion. So having a pattern for making these low-level specific changes is good so devs can do whatever they want/need.

If there was a setting that say 20-50% of apps needed to configure, I'd be open to putting something on UseWindowsService itself to make it easy. (Note if it was more than 50%, it should just be the default IMO.)

**Comment by wasabii** [comment] 2022-09-26 18:49
I think I probably disagree with the 50% figure. There a lot of well designed APIs that have usage well below that.

I would make my case by saying this is an extension method that applies specifically to Windows Services. It isn't used on any other platform than Windows. It really should expose the full functionality of Windows Services.

**Comment by eerhardt** [comment] 2022-09-26 18:58
> It really should expose the full functionality of Windows Services 

It does, in the way I outlined above. You can do anything with Windows Services using that approach. That's the way we designed the system - so the underlying functionality can be exposed without duplicating all the APIs.

> I think I probably disagree with the 50% figure. There a lot of well designed APIs that have usage well below that.

I was referring to the percentage of apps that call `UseWindowsService`.

**Comment by jespersh** [comment] 2022-09-26 19:00
> > We're seeing from procmon boot logging that Windows gets tired of waiting for the service to load its dll's. 
> 
> You may want to profile it to see where it is stalling out. One option is to use https://github.com/Microsoft/perfview#perfview-overview or https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-trace#dotnet-trace-collect

I found that a virtual server on shared SAS storage as our worst case didn't get to app.Run(). In some cases it didn't get much past CreateBuilder due to the constraints and loading all these assemblies it tried to do. 
What I ended up getting to work was on the first line was to create the ServiceBase instance and call its Run method, then add that into the builder Services.

**Comment by jespersh** [comment] 2022-09-27 05:54
Example of signaling Windows SCM as early as possible https://github.com/jespersh/SlowStartService/tree/master
Inserted Task.Delay to simulate what we observe. Our main only contains configuration and service setup like shown. Just more of it.

**Comment by davidfowl** [comment] 2022-09-27 05:58
Doesn't seem like there are many other things like this. It seems like a simple option to add to WindowsServiceLifetimeOptions. Does it solve your problem though? Can you verify that it does with @eerhardt's suggestion?

**Comment by jespersh** [comment] 2022-09-27 06:01
His example would require it reaches `app.Run()` before timing out

**Comment by tarekgh** [comment] 2022-09-27 21:08
@jespersh could you please log a new issue for the problem you have with the details and reproduce steps. Your issue is different than the original topic of this issue. 

Closing as @eerhardt suggestion address this issue. Feel free to send any question we can help with.

**Closed by tarekgh** 2022-09-27 21:08 UTC
Labels: area-Extensions-Hosting, needs-further-triage

**Comment by wasabii** [comment] 2022-09-27 21:10
@davidfowl I can, of course. When I posted this, I was not saying I had issue. I worked around this 5 years ago or something. I was suggesting a new extension method to expose what seems like appropriate functionality. Not a bug.

**Comment by tarekgh** [comment] 2022-09-27 21:18
Thanks for your reply @wasabii. @eerhardt already replied here https://github.com/dotnet/runtime/issues/75276#issuecomment-1258446954 about the exposure of the new API. If we see more demand on such API in the future, we can consider it at that time.
