### ISSUE TITLE
Test Failure: JIT/jit64/opt/cg/cgstress/CgStress1_ro/CgStress1_ro.cmd

### ISSUE THREAD

**Issue by WangyangZhou90** [dotnet/runtime#110176] opened 2024-11-26 05:41 UTC
Failed in:[runtime-cet 20240925.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=817779&view=results)
Error message:
> C:\h\w\AB0609D4\w\B16009B0\e\JIT\jit64\jit64_3\../opt/cg/cgstress/CgStress1_r/CgStress1_r.cmd
04:12:45.420 Passed test: JIT/jit64/opt/cg/cgstress/CgStress1_r/CgStress1_r.cmd
04:12:45.421 Running test: JIT/jit64/opt/cg/cgstress/CgStress1_ro/CgStress1_ro.cmd

Assert failure(PID 3384 [0x00000d38], Thread: 3696 [0x0e70]): !"If this ever fires, then this method should return HRESULT"

CORECLR! FieldDesc::GetAttributes + 0xFA (0x00007ffc`bb62552a)
CORECLR! CEEInfo::getFieldInfo + 0x577 (0x00007ffc`bb63ef97)
CLRJIT! Compiler::impImportBlockCode + 0x6212 (0x00007ffc`bc5caa02)
CLRJIT! Compiler::impImportBlock + 0x1AD (0x00007ffc`bc5c370d)
CLRJIT! Compiler::impImport + 0x48E (0x00007ffc`bc5c2b1e)
CLRJIT! Compiler::fgImport + 0x18 (0x00007ffc`bc55e848)
CLRJIT! Phase::Run + 0x76 (0x00007ffc`bc6bf3a6)
CLRJIT! Compiler::compCompile + 0x21F (0x00007ffc`bc4e7f1f)
CLRJIT! Compiler::compCompileHelper + 0xA2A (0x00007ffc`bc4ebd4a)
CLRJIT! Compiler::compCompile + 0x948 (0x00007ffc`bc4eab18)
    File: D:\a\_work\1\s\src\coreclr\vm\field.h:632
    Image: C:\h\w\AB0609D4\p\corerun.exe

App Exit Code: -1073740286
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
FAILED
[XUnitLogChecker]: 04:12:47.58: The full run will be done.
[XUnitLogChecker]: 04:12:47.59: Item 'jit64_3' did not finish running. Checking and fixing the log...
[XUnitLogChecker]: 04:12:47.59: XUnit log file has been fixed!

**Comment by mrsharm** [comment] 2024-11-26 18:23
Unassigning the GC team since this seems like a JIT based assertion failure that occurred while running the CET test suite. 

CC: @JulieLeeMSFT

**Comment by mangod9** [comment] 2024-11-26 19:25
Oh, I noticed Julie had moved it to VM area. Was this investigated and determined to be not an issue in codegen?

**Comment by amanasifkhalid** [comment] 2024-11-27 16:20
> Was this investigated and determined to be not an issue in codegen?

As far as I know, nobody on the codegen side has investigated this yet. cc @dotnet/jit-contrib

**Comment by EgorBo** [comment] 2024-11-27 16:26
> Was this investigated and determined to be not an issue in codegen?

The assert was failing on VM side, that is why it was moved to VM I guess.

**Comment by amanasifkhalid** [comment] 2024-11-27 17:23
I cannot reproduce this issue with a mainline build, or with the build from the failing run. The [latest run](https://dev.azure.com/dnceng-public/public/_build/results?buildId=880782&view=results) of `runtime-cet` passed, so maybe this was a one-off?

**Comment by JulieLeeMSFT** [comment] 2024-11-27 22:16
> The assert was failing on VM side, that is why it was moved to VM I guess.

That is right. 


> I cannot reproduce this issue with a mainline build, or with the build from the failing run. The [latest run](https://dev.azure.com/dnceng-public/public/_build/results?buildId=880782&view=results) of `runtime-cet` passed, so maybe this was a one-off?

Let's monitor some more runs and close this issue if it doesn't happen again.

**Comment by amanasifkhalid** [comment] 2024-11-28 16:28
> Let's monitor some more runs and close this issue if it doesn't happen again.

Assigning myself so I remember to check.

**Closed** 2024-12-02 15:07 UTC
Labels: area-CodeGen-coreclr
