### ISSUE TITLE
System.RuntimeType gives wrong Name and FullName for jagged multidimentional array.

### ISSUE THREAD

**Issue by ezverev** [dotnet/runtime#45777] opened 2020-12-08 18:27 UTC
### Description
```
var examinedType = typeof(System.DateTimeOffset[,,,][,][,,][]);
var name = examinedType.Name;
var fullName = examinedType.FullName;
```

I expect both name and FullName reflect the type definition. They do not. Actually they depict the array structure in **reverse order** of jaggedness i.e. both show:
`DateTimeOffset[][,,][,][,,,]`

### Configuration

.NETRuntime, Version=v.4.6.2
x64

### Other information

I deem this is just a bad recursion in 
https://github.com/dotnet/runtime/blob/18d1527c079e5f4c1e3ee0ccd1ca22f92f7969c9/src/coreclr/System.Private.CoreLib/src/System/RuntimeHandles.cs#L467

I created a workaround for myself which works this way:

(recursion for Type)
```
else if (type.IsArray)
{
    var arrayElementType = type.GetElementType();
    var arrayElementTypeString = arrayElementType.ToLogString(); //<- recursive call
    var arrayRankInfo = new String(',', type.GetArrayRank() - 1);

    if (arrayElementType.IsArray)
    {
        var arrayElementInfo = Regex.Match(arrayElementTypeString, @"(?<elementType>.*?)(?<elementRaknInfo>(?:\[,*\])+)$");
        result = $"{arrayElementInfo.Groups["elementType"]}[{arrayRankInfo}]{arrayElementInfo.Groups["elementRaknInfo"]}";
    }
    else
    {
        result = $"{arrayElementTypeString}[{arrayRankInfo}]";
    }
}
```

**Comment by svick** [comment] 2020-12-27 14:38
I believe there is nothing wrong here, both are valid approaches of representing jagged multidimensional arrays and [both have their advantages and disadvantages](https://ericlippert.com/2009/08/17/arrays-of-arrays/). It is unfortunate that C# and .Net chose different approaches, but I think neither one of them can switch at this point.

**Comment by ezverev** [comment] 2021-01-13 13:49
I don't quite get your linkage between the cause and effect.

>C# and .Net chose different approaches
Would you be so kind to clarify? Are you saying that .Net chose the order or representation returned from the ```ConstructName()``` function and thus it is stuck to it?

What I suspect is that the ```ConstructName()``` function generates a string in a manner of mere recursion and this is not linked to .Net array logic in any way other than fabricating ```Type.ToString()``` result. If indeed the internals of .Net are somehow bound to the ```ConstructName()``` result, I would agree with your judgement. If there is no such bond, I see no "switching" in changing the ```ConstructName()```.

**Comment by KalleOlaviNiemitalo** [comment] 2021-01-13 15:00
`Type.GetType("System.Int32[][,,]").Name` returns `"System.Int32[][,,]"`, i.e. the behavior is at least consistent between GetType and Name.

**Comment by buyaa-n** [comment] 2021-07-07 23:01
It might be by design, even it is not most likely we will not fix this at this point cc @steveharter

**Comment by steveharter** [comment] 2021-07-15 20:10
Having the name with reversed dimensions is inconsistent with the declaration, but changing that behavior would be breaking since `Type.GetType(string)` would likely change as well. Current behavior:
```cs
Console.WriteLine(Type.GetType("System.Int32[][,]") == typeof(int[][,])); // false
Console.WriteLine(Type.GetType("System.Int32[][,]") == typeof(int[,][])); // true
```

FWIW:
```cs
Type t1 = Type.GetType("System.Int32[][,]");
Console.WriteLine(t1); // System.Int32[][,]
var a1 = (int[,][])Array.CreateInstance(typeof(int[]), 1, 3);
Console.WriteLine(a1.GetType()); // System.Int32[][,]
Console.WriteLine(t1 == a1.GetType()); // true

Type t2 = typeof(int[][,]);
Console.WriteLine(t2); // System.Int32[,][]
Type t2_runtime = new int[1][,].GetType();
Console.WriteLine(t2_runtime); // System.Int32[,][]

Type t3 = typeof(int[,][]);
Console.WriteLine(t3); // System.Int32[][,]

Console.WriteLine(t1 == t2); // false
Console.WriteLine(t1 == t3); // true
```

**Comment by steveharter** [comment] 2022-10-27 17:34
Closing as not fixing - breaking change not worth the consistency issue.

**Closed by steveharter** 2022-10-27 17:34 UTC
Labels: area-System.Reflection
