### ISSUE TITLE
System.IO.Directory.GetFiles with System.IO.SearchOption.AllDirectories not working on network drive

### ISSUE THREAD

**Issue by segln** [dotnet/runtime#92152] opened 2023-09-15 20:16 UTC
### Description

`System.IO.Directory.GetFiles()` with `System.IO.SearchOption.AllDirectories` on Windows network drive freezing.

With `System.IO.SearchOption.TopDirectoryOnly` it works, but file paths include trailing '\0' (e.g. `Z:\test\test.txt\0`.

### Reproduction Steps

Network drive: `Z:\`

1. Create any file(s) in `Z:\test\`.
2. Execute `System.IO.Directory.GetFiles(@"Z:\test\", "*", System.IO.SearchOption.AllDirectories)`.

### Expected behavior

Get file paths in directory.

### Actual behavior

App freezes, sometimes throws `System.IO.PathTooLongException`.

### Configuration

Project .NET version: 8.0.100-rc.1.23455.8
OS: Windows 11 Pro
Arch: x64

```powershell
$ dotnet --list-sdks
7.0.401 [C:\Program Files\dotnet\sdk]
8.0.100-preview.7.23376.3 [C:\Program Files\dotnet\sdk]
8.0.100-rc.1.23455.8 [C:\Program Files\dotnet\sdk]

$ dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 8.0.0-preview.7.23375.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 8.0.0-rc.1.23421.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.0-preview.7.23375.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.0-rc.1.23419.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 8.0.0-preview.7.23376.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 8.0.0-rc.1.23420.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Other information

Maybe related: https://github.com/dotnet/runtime/issues/49803

**Comment by danmoseley** [comment] 2023-09-15 20:49
That's a puzzle. 
* does this happen even when there's very few files on the share?
* does this repro on 6.0 or 7.0?
* does this happen on any share?
* does `dir /s z:\test\*` work at normal speed?

another thing that can help here is breaking in to the process a few times in the debugger and looking at the callstack. if something's slow, you'll see most of the same callstack most times. perhaps grab that callstack and share here, so we can see where the time is.

**Comment by danmoseley** [comment] 2023-09-15 20:50
For the trailing null -- that seems like a separate issue. Is this file share a standard Windows SMB share or is anything special about it? 

Another thing to try is to share a drive on your own machine and try against that.

**Comment by jkotas** [comment] 2023-09-15 20:55
> For the trailing null -- that seems like a separate issue.

This looks like a duplicate of https://github.com/dotnet/runtime/issues/49803

Is this a WebDav file share?

**Comment by adamsitnik** [comment] 2023-09-22 18:11
> This looks like a duplicate of https://github.com/dotnet/runtime/issues/49803

@jkotas is correct, this is a duplicate of #49803, let's continue the conversation there.

**Closed by adamsitnik** 2023-09-22 18:11 UTC
Labels: area-System.IO, untriaged
