### ISSUE TITLE
Assertion failed during 'Mark local vars'

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#43508] opened 2020-10-11 07:28 UTC
Assertion failed '(varDsc->lvType != TYP_UNDEF) && (varDsc->lvType != TYP_VOID) && (varDsc->lvType != TYP_UNKNOWN)' in 'FullProof:Test():int' during 'Mark local vars'

JIT/Regression/VS-ia64-JIT/V2.0-Beta2/b309576/b309576

category:correctness
theme:needs-triage
skill-level:beginner
cost:small

**Comment by BruceForstall** [comment] 2020-10-16 17:47
@MichalStrehovsky How do you repro? I removed `<Optimize>True</Optimize>` from b309576.ilproj, rebuilt the test, then ran:
```
> c:\gh\runtime\artifacts\tests\coreclr\Windows_NT.x64.Debug\tests\Core_Root\CoreRun.exe C:\gh\runtime\artifacts\tests\coreclr\Windows_NT.x64.Debug\JIT\Regression\VS-ia64-JIT\V2.0-Beta2\b309576\b309576\b309576.dll
System.OverflowException: Arithmetic operation resulted in an overflow.
   at FullProof.Test()
   at FullProof.Main()
PASS
```

**Comment by MichalStrehovsky** [comment] 2020-10-16 20:19
I first hit it in runtimelab because I had a change to infrastructure that was ignoring this flag.

The repro in the runtime repo (and the associated jitdump) is based on simply running `ilasm /debug bug2.il` and running corerun on that.

**Comment by MichalStrehovsky** [comment] 2020-10-16 20:20
Oh, now I see in jitdump:

OPTIONS: compCodeOpt = BLENDED_CODE
OPTIONS: compDbgCode = true
OPTIONS: compDbgInfo = true
OPTIONS: compDbgEnC  = false

Is this about optimized debuggable code?

**Comment by jkotas** [comment] 2020-10-17 15:53
This repros it for me in current dotnet/runtime:master
```
build -rc checked
cd artifacts\bin\coreclr\Windows_NT.x64.Checked
copy D:\runtime\artifacts\bin\runtime\net6.0-Windows_NT-Debug-x64
copy D:\runtime\src\tests\JIT\Regression\VS-ia64-JIT\V2.0-Beta2\b309576
ilasm /DEBUG bug2.il
corerun bug2.exe
```

**Comment by JulieLeeMSFT** [comment] 2021-07-26 17:30
CC @jakobbotsch PTAL.

**Comment by jakobbotsch** [comment] 2021-07-26 21:14
I cannot reproduce this. Looks like it was fixed by #48152. After reverting that, I am able to reproduce it.

**Closed by jakobbotsch** 2021-07-26 21:14 UTC
Labels: area-CodeGen-coreclr, bug
