### ISSUE TITLE
System.Drawing.Graphics The drawing results are different on Unix and Windows NT.

### ISSUE THREAD

**Issue by aijkl** [dotnet/runtime#47122] opened 2021-01-18 13:33 UTC
The drawing results are different on Unix and Windows NT.
The same font is used.
Please let me know the cause and solution.
I used DeepL, sorry if this is rude. I like Microsoft.

Environment
NET Core 5.0
System.Drawing.Common 4.7.0
Unix(Debian)
Windows NT (Windows 10)

```
    class Program
    {        
        public static void Main()
        {
            Bitmap bitmap = new Bitmap(200, 100);
            using(Graphics graphics = Graphics.FromImage(bitmap))
            {
                graphics.FillRectangle(Brushes.LightGray, graphics.ClipBounds);                
                Font font = new Font(new FontFamily("Noto Sans JP"), 10, FontStyle.Regular);
                graphics.DrawString($"{Environment.OSVersion.Platform} {Environment.OSVersion.Version} \n{font.FontFamily.Name} {font.Style}", new Font(font.FontFamily, 10, FontStyle.Regular), Brushes.Gray, new Point(30, 33));
            }
            bitmap.Save(Path.Combine(Directory.GetCurrentDirectory(),$"{Environment.OSVersion.Platform}.jpeg"));
            Console.WriteLine("Complete");
            Console.ReadLine();
        }
    }   
```

![Unix](https://user-images.githubusercontent.com/51302983/104921268-6cebc500-59dc-11eb-9729-580afcd0491e.jpeg)
![Win32NT](https://user-images.githubusercontent.com/51302983/104921278-6fe6b580-59dc-11eb-8c2b-f03598177127.jpeg)

**Comment by huoyaoyuan** [comment] 2021-01-18 17:22
On Windows it uses Windows GDI/GDI+, but on Linux it uses a simulation `libgdiplus`.
It's ported by Mono for compatibility. If you care about the result, you should find some alternative. System.Drawing isn't truly cross-platform now.

**Comment by aijkl** [comment] 2021-01-19 03:13
![スクリーンショット 2021-01-19 121136](https://user-images.githubusercontent.com/51302983/104983127-80844380-5a4f-11eb-81a7-7acd13a02673.png)
I'm waiting for the quality of libgdiplus to improve!
Now I've dealt with it by hard coding the coordinates.
Thank you for your answer.

**Comment by safern** [comment] 2021-01-29 21:20
@aijkl libgdiplus at the moment is community driven, so I suggest opening an issue there instead of here as the root cause is libgdiplus and not System.Drawing.Common. We do hope to improve this painful differences in System.Drawing.Common cross plat in the future. Closing as there is no action on our side, please feel free to re-open if you disagree or want to keep discussion open.

**Closed by safern** 2021-01-29 21:20 UTC
Labels: area-System.Drawing
