### ISSUE TITLE
[API Proposal]: Add ICloneable<T>

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#77121] opened 2022-10-17 18:18 UTC
### Background and motivation

I suggest adding the generic ICloneable, as it is sometimes needed for immunitable programming in multi-threading, when you need to divide some instance into 100 threads, and so that each has its own copy. There is a non-generic version of this interface, but I suggest adding a generic.

### API Proposal

```csharp
interface ICloneable<out T> where T : ICloneable<T>
{ 
    public T Clone();
}
```

### API Usage

```csharp
using System;
using System.Linq;

var test = new Test();
var result = Enumerable.Range(1, 1000).Select(a => test.Clone())
    .Select(y =>
    {
        return Task.Run(() =>
        {
            y.text2 = "";
            return y.text1;
        });
    });
await Task.WhenAll(result.ToArray());

class Test :ICloneable<Test>
{
    public string Id { get; set; }
    public string text1 { get; set; }
    public string text2 { get; set; }
    public string text3 { get; set; }
    public string text4 { get; set; }
    public string text5 { get; set; }
    public string text6 { get; set; }
    public string text7 { get; set; }
    public Test Clone()
    {
        throw new NotImplementedException();
    }

 
}

interface ICloneable<out T> where T : ICloneable<T>
{ 
    public T Clone();
}
```

**Comment by teo-tsirpanis** [comment] 2022-10-17 18:35
Duplicate of #37561 and #49433.

**Closed by teo-tsirpanis** 2022-10-17 18:35 UTC
Labels: api-suggestion, untriaged

**Comment by Mr0N** [comment] 2022-10-17 18:38
> 



> Duplicate of #37561 and #49433.

I didn't see exactly the same implementation of the interface there.

**Comment by Mr0N** [comment] 2022-10-17 19:01
Well, then mark the interface as obsolete with an attribute

**Comment by huoyaoyuan** [comment] 2022-10-18 03:17
And also #77077
