### ISSUE TITLE
AddProviderTransparent_InvokeTypeMultipleTimes_Refreshes fails in CI

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/runtime#51877] opened 2021-04-26 16:48 UTC
```
    System.ComponentModel.Tests.TypeDescriptorTests.AddProviderTransparent_InvokeTypeMultipleTimes_Refreshes [FAIL]
      Assert.Equal() Failure
      Expected: 2
      Actual:   3
      Stack Trace:
        /_/src/libraries/System.ComponentModel.TypeConverter/tests/TypeDescriptorTests.cs(359,0): at System.ComponentModel.Tests.TypeDescriptorTests.AddProviderTransparent_InvokeTypeMultipleTimes_Refreshes()
```

Configuration: net6.0-Linux-Debug-x64-CoreCLR_release-RedHat.7.Amd64.Open

https://dev.azure.com/dnceng/public/_build/results?buildId=1107359&view=ms.vss-test-web.build-test-results-tab&runId=33804176&paneView=debug

**Comment by safern** [comment] 2021-04-26 17:08
Actually it seems like an issue for this was opened a couple of days ago. Closing as dupe of: https://github.com/dotnet/runtime/issues/51819

**Closed by safern** 2021-04-26 17:08 UTC
Labels: area-System.ComponentModel, blocking-clean-ci

**Comment by ViktorHofer** [comment] 2021-04-26 17:10
Sometimes I just hate GH's search 😈 Thanks for de-duping the issue.
