### ISSUE TITLE
Support ReadyToRun on mixed-mode assemblies

### ISSUE THREAD

**Issue by jkoritzinsky** [dotnet/runtime#12667] opened 2019-05-08 19:45 UTC
Right now we explicitly block crossgenning/ready-to-running any mixed mode assemblies (see dotnet/coreclr#24451). We should take a look at enabling it depending on cost of implementation and the perf difference for our partners such as WPF.

Originally part of dotnet/runtime#10333.

**Comment by trylek** [comment] 2023-05-03 23:16
Closing as a duplicate of https://github.com/dotnet/runtime/issues/83942.

**Closed by trylek** 2023-05-03 23:16 UTC
Labels: area-CrossGen/NGEN-coreclr, area-crossgen2-coreclr
