### ISSUE TITLE
Maybe a bug in Uri class

### ISSUE THREAD

**Issue by xiaorunOk** [dotnet/runtime#64245] opened 2022-01-25 00:50 UTC
new Uri("http://localhost/db/$med#Anti.%E5%AE%8C%E6%88%90%28%29", UriKind.Absolute).IsWellFormedOriginalString() will return false. but it should be true.

**Comment by karelz** [comment] 2022-01-25 11:05
Duplicate of #64249

**Closed by karelz** 2022-01-25 11:05 UTC
Labels: area-System.Net, untriaged
