### ISSUE TITLE
Test failure Regressions/coreclr/GitHub_16833/Test16833/Test16833.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#66568] opened 2022-03-14 01:53 UTC
Run: [runtime-coreclr gcstress0x3-gcstress0xc 20220313.1
](https://dev.azure.com/dnceng/public/_build/results?buildId=1661068&view=ms.vss-test-web.build-test-results-tab&runId=45721876&resultId=110795&paneView=debug)

Failed test:
```
CoreCLR OSX arm64 Checked gcstress0xc @ OSX.1200.ARM64.Open

- Regressions/coreclr/GitHub_16833/Test16833/Test16833.sh

```
**Error message:**
```
Return code:      1
Raw output file:      /tmp/helix/working/A59A092C/w/A38E0941/uploads/Reports/Regressions.coreclr/GitHub_16833/Test16833/Test16833.output.txt
Raw output:
BEGIN EXECUTION
/tmp/helix/working/A59A092C/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false Test16833.dll ''
Test Test2 failed. Expected "Test2:  1, 2, 3, 4, [5, 6], 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17", got "Test2:  1, 2, 3, 4, [5, 6], -9.255963134931783E+61, 0, 0, 0, 11, 12, 13, 14, 15, 16, 17"
Expected: 100
Actual: 1
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/tmp/helix/working/A59A092C/p
/private/tmp/helix/working/A59A092C/w/A38E0941/e/Regressions/coreclr/GitHub_16833/Test16833/Test16833.sh
Expected: True
Actual:   False


Stack trace
   at Regressions_coreclr._GitHub_16833_Test16833_Test16833_._GitHub_16833_Test16833_Test16833_sh()
```

**Comment by janvorli** [comment] 2022-06-20 11:34
I can repro this locally, but it takes about 100000 iterations of the test to reproduce. I can see that the bad floating point value binary representation is 0xcccccccccccccccc, which likely represents uninitialized memory. I suspect the issue that is going to be fixed by #69906 may be the culprit.

**Comment by janvorli** [comment] 2022-07-12 13:30
Unfortunately the #69906 doesn't fix the problem.

**Comment by VincentBu** [comment] 2022-07-19 01:51
Failed again in: [runtime-coreclr gcstress-extra 20220717.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1886479&view=ms.vss-test-web.build-test-results-tab&runId=49272476&paneView=debug&resultId=106969)

Failed test:
```
coreclr Linux arm Checked gcstress0xc_jitstress2 @ (Ubuntu.1804.Arm32.Open)Ubuntu.1804.Armarch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-helix-arm32v7-bfcd90a-20200121150440

- Regressions/coreclr/GitHub_16833/Test16833/Test16833.sh

```
**Error message:**
```
Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/Reports/Regressions.coreclr/GitHub_16833/Test16833/Test16833.output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false Test16833.dll ''
Test Test3 failed. Expected "Test3:  1, 2, 3, 4, 5, [6], 7", got "Test3:  1, 2, 3, 4, 5[6], 7"
Test Test6 failed. Expected "Test6:  1, 2, 3, 4, 5, [6, 7], 8, 9, 10, 11, 12, 13, 14, 15, 16, 17", got "Test6:  12, 3ꋐ4, 5[6, 7], 8, 9, 10, 11, 12, 13, 14, 15, 16, 17"
Test Test2M failed. Expected "Test2M: i1, 2, 3, 4, [5, 6], 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17", got "Test2M: i1, 23, 4[5, 6], 7, 8, 9, 10, 11, 1213, 1415, 16, 17"
Test Test1RB failed. Expected "Test1RB:  1, 2, 3, 4, [5, 6], 7 -> [-1, -2, -3]", got "Test1RB:  12, 3, 4, [5, 6], 7 -> [-1, -2, -3]"
Expected: 100
Actual: 1
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=/root/helix/work/correlation
/root/helix/work/workitem/e/Regressions/coreclr/GitHub_16833/Test16833/Test16833.sh
Expected: True
Actual:   False


Stack trace
   at Regressions_coreclr._GitHub_16833_Test16833_Test16833_._GitHub_16833_Test16833_Test16833_sh()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by AntonLapounov** [comment] 2022-08-09 00:44
According to the table above, the issue is not specific to macOS or ARM64, e.g., it fails on Ubuntu x64 as well.

**Comment by AntonLapounov** [comment] 2022-08-11 18:43
@VincentBu I am wondering whether this test is still failing.  How did you get the table of jobs in which this test failed?

**Comment by VincentBu** [comment] 2022-08-12 01:59
looks like the test didn't fail in the last 20 days. 
additionally, I get the table by querying Kusto

**Comment by AntonLapounov** [comment] 2022-08-12 02:03
Thank you. I am going to close this. If the test fails again, please reopen.

**Comment by AntonLapounov** [comment] 2022-08-12 20:41
Here is the latest failure I managed to [find](https://runfo.azurewebsites.net/search/tests/?q=started%3A2022-01-01+definition%3A661+name%3ATest16833.sh):

> Test Run: coreclr OSX arm64 Checked gcstress0xc @ OSX.1200.ARM64.Open
> Azure DevOps Build: [1910068](https://dev.azure.com/dnceng/public/_build/results?buildId=1910068)
> Definition: [runtime-coreclr gcstress0x3-gcstress0xc](https://runfo.azurewebsites.net/view/definition/?definition=runtime-coreclr%20gcstress0x3-gcstress0xc)
> Queue Time: 7/28/2022 1:44:18 PM
> ```
> Test Test2 failed. Expected "Test2:  1, 2, 3, 4, [5, 6], 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17", got "Test2:  1, 2, 3, 4, [5, 6], -9.255963134931783E+61, 0, 0, 0, 11, 12, 13, 14, 15, 16, 17"
> ```

**Comment by janvorli** [comment] 2022-08-18 14:28
This issue still occurs, I am able to repro it locally on macos ARM64 once in hundreds of thousands of iterations of the test.

**Comment by AntonLapounov** [comment] 2022-08-18 16:35
Someone with a macOS machine should investigate then.

**Comment by AntonLapounov** [comment] 2022-08-18 18:42
I see two failure modes here.  In one mode there are missing/garbled `", "` connector strings (observed on ARM32 and maybe x64):
```
Test Test3 failed. Expected "Test3:  1, 2, 3, 4, 5, [6], 7", got "Test3:  1, 2, 3, 4, 5[6], 7"
Test Test6 failed. Expected "Test6:  1, 2, 3, 4, 5, [6, 7], 8, 9, 10, 11, 12, 13, 14, 15, 16, 17", got "Test6:  12, 3ꋐ4, 5[6, 7], 8, 9, 10, 11, 12, 13, 14, 15, 16, 17"
Test Test2M failed. Expected "Test2M: i1, 2, 3, 4, [5, 6], 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17", got "Test2M: i1, 23, 4[5, 6], 7, 8, 9, 10, 11, 1213, 1415, 16, 17"
Test Test1RB failed. Expected "Test1RB:  1, 2, 3, 4, [5, 6], 7 -> [-1, -2, -3]", got "Test1RB:  12, 3, 4, [5, 6], 7 -> [-1, -2, -3]"
```
In another mode there are garbled floating point numbers:
```
Test Test2 failed. Expected "Test2:  1, 2, 3, 4, [5, 6], 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17", got "Test2:  1, 2, 3, 4, [5, 6], -9.255963134931783E+61, 0, 0, 0, 11, 12, 13, 14, 15, 16, 17"
```
If it is the same issue, then it is not ARM64-specific.  I could not reproduce the failure on Ubuntu x64 (with or without GCStress); however, I performed a significantly smaller number of iterations.

**Comment by janvorli** [comment] 2022-08-18 18:55
When reproing it locally on macOS arm64, I could only repro the garbled floating point numbers (at two other different positions, in the place of 5 or 6).

**Comment by mangod9** [comment] 2022-08-22 15:56
does this repro only with gcstress?

**Comment by janvorli** [comment] 2022-08-22 18:45
So far, we have only hit that with GC stress C. I am trying to run it locally to see if it repros without GC stress too.

**Comment by mangod9** [comment] 2022-08-25 20:25
Assigning to Jan but perhaps move to 8, but continue to investigate?

**Closed** 2022-09-12 18:19 UTC
Labels: os-linux, os-mac-os-x, GCStress, area-VM-coreclr, in-pr
