### ISSUE TITLE
Crash - JIT/CheckProjects/CheckProjects/CheckProjects.sh

### ISSUE THREAD

**Issue by karelz** [dotnet/runtime#76070] opened 2022-09-23 13:53 UTC
Affected test:
- **CheckProjects.sh** - `JIT/CheckProjects/CheckProjects/CheckProjects.sh`

Runfo failures in [last 30 days](https://runfo.azurewebsites.net/search/tests/?q=started%3A%7E30+definition%3Aruntime+name%3A%22jit%2Fcheckprojects%2Fcheckprojects%2Fcheckprojects.sh%22)

Day | Run | OS
-- | -- | --
9/23 | 2x PR [27320](https://runfo.azurewebsites.net/view/build/?number=27320) | mono Linux arm64 Release @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open<br/>mono Linux x64 Release @ Ubuntu.1804.Amd64.Open
9/23 | 2x Rolling run [27318](https://runfo.azurewebsites.net/view/build/?number=27318) | mono Linux arm64 Release @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open<br/>mono Linux x64 Release @ Ubuntu.1804.Amd64.Open
9/22 | 2x PR [27285](https://runfo.azurewebsites.net/view/build/?number=27285) | mono Linux arm64 Release @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open<br/>mono Linux x64 Release @ Ubuntu.1804.Amd64.Open
9/22 | 2x PR [27258](https://runfo.azurewebsites.net/view/build/?number=27258) | mono Linux arm64 Release @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open<br/>mono Linux x64 Release @ Ubuntu.1804.Amd64.Open
9/22 | 2x PR [27244](https://runfo.azurewebsites.net/view/build/?number=27244) | mono Linux arm64 Release @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open<br/>mono Linux x64 Release @ Ubuntu.1804.Amd64.Open
9/9 | 2x PR [11251](https://runfo.azurewebsites.net/view/build/?number=11251) | mono Linux arm64 Release @ (Ubuntu.1804.Arm64.Open)Ubuntu.1804.Armarch.Open<br/>mono Linux x64 Release @ Ubuntu.1804.Amd64.Open

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by karelz** [comment] 2022-09-23 14:06
It started blocking CI as of yesterday. Please disable the test ASAP as first step to unblock clean CI. Thanks!

**Comment by SamMonoRT** [comment] 2022-09-23 14:08
@naricc - seems likely caused by https://github.com/dotnet/runtime/commit/1061e89b3bede739596d21d31ecf85b4c42e1f9d

**Comment by naricc** [comment] 2022-09-23 14:34
Working on this with the highest priority. It seems like the llvmfullaot test is not working still and needs to be disabled.

**Comment by naricc** [comment] 2022-09-23 14:44
https://github.com/dotnet/runtime/pull/76074 <-- This should do it once merged.

**Closed** 2022-09-23 14:49 UTC
Labels: blocking-clean-ci, area-Codegen-JIT-mono, in-pr

**Comment by karelz** [comment] 2022-09-23 14:54
Awesome, thanks a lot for super-fast response time @naricc @SamMonoRT!
