### ISSUE TITLE
BackgroundService will not observe exceptions thrown in ExecuteAsync

### ISSUE THREAD

**Issue by Bpoe** [dotnet/runtime#68165] opened 2022-04-18 16:38 UTC
If an exception is thrown in the ExecuteAsync method of a class derived from BackgroundService, the exception is never observed on after StopApplication() is called. This causes the program to exit with Exit Code 0. This causes problems with orchestrators that will not restart a service if it ends with exit code 0.

This is due to this line of code:
https://github.com/dotnet/runtime/blob/a21b9a2dd4c31cf5bd37626562b7612faf21cee6/src/libraries/Microsoft.Extensions.Hosting.Abstractions/src/BackgroundService.cs#L76

Task.WhenAny returns a `Task<Task>`. The parent task will always be RanToCompletion with Exception as null. The Result needs to be awaited or checked for IsFaulted in order for the ExecuteAsync exception to be observed.

**Comment by Bpoe** [comment] 2022-04-18 16:42
My quick and dirty fix for my re-implementation of BackgroundService was this:
`        public virtual async Task StopAsync(CancellationToken cancellationToken)
        {
            // Stop called without start
            if (this._executeTask == null)
            {
                return;
            }

            try
            {
                // Signal cancellation to the executing method
                this._stoppingCts.Cancel();
            }
            finally
            {
                // Wait until the task completes or the stop token triggers
                var final = await Task.WhenAny(this._executeTask, Task.Delay(Timeout.Infinite, cancellationToken)).ConfigureAwait(false);

                // WhenAny returns a Task<Task>. Its own Task is RanToCompletion without any exceptions, so any exceptions
                // from _executeTask won't be bubbled up.
                // So we can await its result Task that completed and if it had any exceptions, those will now be observed.
                await final;
            }
        }`

**Comment by eerhardt** [comment] 2022-04-18 16:47
@Bpoe - can you attach a minimal reproduction?

See https://github.com/dotnet/runtime/blob/6732e2ee117e01f29ed81ad293983f9ca602ef37/CONTRIBUTING.md#writing-a-good-bug-report

**Comment by Bpoe** [comment] 2022-04-18 17:12
### Repro Step:
```
namespace BackgroundServiceRepro
{
    using System;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.Extensions.Hosting;

    public class Program
    {
        public static async Task Main(string[] args)
            => await Host
                .CreateDefaultBuilder(args)
                .ConfigureServices((hostContext, services) => services.AddHostedService<Repro>())
                .Build()
                .RunAsync();
    }

    public class Repro : BackgroundService
    {
        private readonly IHostApplicationLifetime hostApplicationLifetime;

        public Repro(IHostApplicationLifetime hostApplicationLifetime)
            => this.hostApplicationLifetime = hostApplicationLifetime;

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            await Task.Delay(2000, stoppingToken);

            try
            {
                throw new Exception("Oops!");
            }
            finally
            {
                this.hostApplicationLifetime.StopApplication();
            }
        }
    }
} 
```

### Expected Result
```
c:\>BackgroundServiceRepro.exe
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\bpoe\source\repos\BackgroundServiceRepro\BackgroundServiceRepro\bin\Debug\net5.0
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
Unhandled exception. System.AggregateException: One or more hosted services failed to stop. (Oops!)
 ---> System.Exception: Oops!
   at BackgroundServiceRepro.Repro.ExecuteAsync(CancellationToken stoppingToken) in C:\Users\bpoe\source\repos\BackgroundServiceRepro\BackgroundServiceRepro\Program.cs:line 32
   at BackgroundServiceRepro.BackgroundService2.StopAsync(CancellationToken cancellationToken) in C:\Users\bpoe\source\repos\BackgroundServiceRepro\BackgroundServiceRepro\Program.cs:line 110
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.WaitForShutdownAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at BackgroundServiceRepro.Program.Main(String[] args) in C:\Users\bpoe\source\repos\BackgroundServiceRepro\BackgroundServiceRepro\Program.cs:line 12
   at BackgroundServiceRepro.Program.<Main>(String[] args)

echo %errorlevel%
-532462766
```

### Actual Result 
```
c:\>BackgroundServiceRepro.exe
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\bpoe\source\repos\BackgroundServiceRepro\BackgroundServiceRepro\bin\Debug\net5.0
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...

echo %errorlevel%
0
```

**Comment by maryamariyan** [comment] 2022-04-27 16:14
Confirmed repro, and that it is not a regression. Thanks for the report.

**Comment by deeprobin** [comment] 2022-05-22 16:49
@maryamariyan I also noticed this behavior recently. I can very gladly take a look (since I am affected myself), if is not a big priority.

If that's okay with you, please assign me so I don't lose track.

**Comment by maryamariyan** [comment] 2022-05-24 21:27
@deeprobin how are you affected by this bug? 

Have you considered logging when you are calling StopApplication? 

Also you could consider using `BackgroundServiceExceptionBehavior` explained in https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/hosting-exception-handling. It stops the host as the default behavior when exception is thrown in background task

Closing as we have no plans to fix this.

**Closed by maryamariyan** 2022-05-24 21:27 UTC
Labels: bug, area-Extensions-Hosting

**Comment by Bpoe** [comment] 2022-05-25 16:08
@maryamariyan - Can you please provide an explanation of why you are not fixing this issue? An also why you closed it as Completed when nothing was done?

**Comment by deeprobin** [comment] 2022-05-25 16:58
Let me try to explain it in other words (as I understood the issue of @Bpoe):

In case the `BackgroundServiceExceptionBehavior` of the host is set to `StopHost` (as far as I know the default) and an exception occurs an error message is currently logged and the program exits with exit code 0 which means "Successful".

In case of an error, however, it is desired to return an exit code that is not 0.

---

I am not sure if this is a bug or an enhancement. Nevertheless, this is a good point.

**Comment by eerhardt** [comment] 2022-05-25 17:01
@Bpoe - In the repro program, why are you calling `StopApplication`? What is the scenario for throwing an exception, and then call `StopApplication()`?

Remove that line, and you will see the error logged.

As for the exit code - setting that to non-zero when an exception is thrown is tracked by #67146.

**Comment by deeprobin** [comment] 2022-05-25 17:02
> Can you please provide an explanation of why you are not fixing this issue?

I could imagine that would be a breaking change. 

I mean iirc the host does not terminate the application directly in case of an error but the context is passed to the calling method after termination (in your case probably Program.Main).
You could manually provoke an exit code of course. That would be, however, a (possibly tolerable) Breaking Change.
