### ISSUE TITLE
Test failure baseservices\\threading\\generics\\Monitor\\EnterExit04\\EnterExit04.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#70968] opened 2022-06-20 01:41 UTC
Run: [runtime-coreclr gcstress0x3-gcstress0xc 20220619.1 
](https://dev.azure.com/dnceng/public/_build/results?buildId=1833184&view=ms.vss-test-web.build-test-results-tab&runId=48491664&paneView=debug&resultId=100178)

Failed test:
```
coreclr windows x86 Checked gcstress0xc @ Windows.10.Amd64.Open

- baseservices\\threading\\generics\\Monitor\\EnterExit04\\EnterExit04.cmd

```
**Error message:**
```
Assert failure(PID 5068 [0x000013cc], Thread: 3096 [0x0c18]): CheckInstrBytePattern(epilogBase[offset] & X86_INSTR_RET, X86_INSTR_RET, epilogBase[offset]) || CheckInstrBytePattern(epilogBase[offset], X86_INSTR_JMP_NEAR_REL32, epilogBase[offset]) || CheckInstrWord(*PTR_WORD(epilogBase + offset), X86_INSTR_w_JMP_FAR_IND_IMM)

CORECLR! UnwindEspFrameEpilog + 0x1DC (0x7016735c)
CORECLR! UnwindStackFrame + 0x230 (0x70167760)
CORECLR! DoGcStress + 0x263 (0x7034911b)
CORECLR! OnGcCoverageInterrupt + 0x160 (0x7034976e)
CORECLR! IsGcMarker + 0x93 (0x7017b881)
CORECLR! CLRVectoredExceptionHandlerShim + 0xC5 (0x70170e15)
NTDLL! WinSqmEventWrite + 0x1C21A (0x7741f95a)
NTDLL! RtlUnwind + 0x1BA (0x773e011a)
NTDLL! KiUserExceptionDispatcher + 0xF (0x773f0dbf)
SYSTEM.PRIVATE.CORELIB! <no symbol> + 0x0 (0x6f32124e)
File: D:\a_work\1\s\src\coreclr\vm\eetwain.cpp Line: 3585
Image: C:\h\w\AFE009D4\p\corerun.exe

Return code:      1
Raw output file:      C:\h\w\AFE009D4\w\9E54093F\uploads\Reports\baseservices.threading\generics\Monitor\EnterExit04\EnterExit04.output.txt
Raw output:
BEGIN EXECUTION
"C:\h\w\AFE009D4\p\corerun.exe" -p "System.Reflection.Metadata.MetadataUpdater.IsSupported=false"  EnterExit04.dll
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:

set CORE_ROOT=C:\h\w\AFE009D4\p
C:\h\w\AFE009D4\w\9E54093F\e\baseservices\threading\generics\Monitor\EnterExit04\EnterExit04.cmd
Expected: True
Actual:   False


Stack trace
   at baseservices_threading._generics_Monitor_EnterExit04_EnterExit04_._generics_Monitor_EnterExit04_EnterExit04_cmd()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by janvorli** [comment] 2022-06-21 10:41
Duplicate of #68431

**Closed by janvorli** 2022-06-21 10:41 UTC
Labels: arch-x86, os-windows, GCStress, area-VM-coreclr, untriaged, blocking-clean-ci-optional
