### ISSUE TITLE
System.Text.Json converter append additional property during serialization

### ISSUE THREAD

**Issue by dazinator** [dotnet/runtime#56297] opened 2021-07-26 12:08 UTC
I'm implementing a converter for system.text.json
When writing / serializing the object I want to add an additional property that isn't part of its type definition.

Here is the method signature I have to implement for the converter:
```

 public override void Write(
            Utf8JsonWriter writer,
            TriggerConfig value,
            JsonSerializerOptions options)
        {


       }
```

`TriggerConfig` is an abstract class. I'm doing polymorphic serialisation / deserilisation here. I've followed the docs for the deserialisation side, by taking a clone of the reader (which is a struct) reading ahead to validate the descriminator property, then if it's allowed, using the original reader to read the full object.

This is because I want a flat json representation of the object:

```json
{
"MyDescriminator":"foo",
"PropA":"bar",
"PropB":"bat
}
```

However on the serialization side, when writing the object, I need to write the object, but first include this descrimator as an additional property.

The problem is, when implementing this `Write` method on the converter, I can't write the object, and then tag on an additional property because `JsonSerializer.Serialize(writer, value, value.GetType());` writes the start and end object tokens giving me no opportunity to add a shadow property (a property that isn't part of the type definition).

```
 JsonSerializer.Serialize(writer, derivedA, derivedType); // how to I now write the additional shadow property as part of this object? 
```

I can workaround this problem by changing the structure of the json so that descrimator property sits outside the object:

```json
{
"MyDescriminator":"foo",
"Object": {
  "PropA":"bar",
  "PropB":"bat
}
}
```

But that's un-necessary wrapper purely added to get around this underlying issue!

**Comment by eiriktsarpalis** [comment] 2021-07-26 12:20
Have you considered exposing a `MyDescriminator` property in the `TriggerConfig` base class? That would ensure that the default converter for each subtype would emit that information in one object. The other alternative I can think of is writing custom converters for each subtype that hardcodes the appropriate type discriminator (although that might require a lot of boilerplate).

Other than that, I would expect this issue to be addressed when #30083 is implemented.

**Comment by dazinator** [comment] 2021-07-26 12:41
> Have you considered exposing a MyDescriminator property in the TriggerConfig base class? 
Yes, I'd prefer not to do this for multiple reasons which I'd be happy to go into.

> The other alternative I can think of is writing custom converters for each subtype that hardcodes the appropriate type discriminator

Yeah thats not really going to be workable when you can have 10-15 derived types. I'd prefer a generic implementation so I can make proper use of generic types, and paramters so I don't have to write essentially the same class 10-15 times!

> Other than that, I would expect this issue to be addressed when #30083 is implemented.

Ok will keep my eyes peeled. Another alternative i've considered is:

- Serializing the derived instance to `json` in memory, then parsing the `json` into a modifiable structure like a `JsonDocument` then adding the property, then writing that. However I got stuck after parting the json into a JsonDocument because JsonDocument does not let me make modifications. I considered also not parsing the serialized json but treating it as a string, modifying it in memory to include the additional json property, and then trying to write that json as is, but that method also failed because the `Utf8JsonWriter` doesn't just let me write some arbitrary json, I have to write individual properties, or tokens which means I need a structured view of the JSON.

**Comment by dazinator** [comment] 2021-07-26 12:55
Thinking on it some more, I think i've found this workaround:

```
            writer.WriteStartObject();
            writer.WriteString(TypeDescriminatorPropertyName, name);

            var json = JsonSerializer.Serialize(value, value.GetType());
            var document = JsonDocument.Parse(json);

            var root = document.RootElement;
            if (root.ValueKind != JsonValueKind.Object)
            {
                throw new NotSupportedException();
            }            

            foreach (var property in root.EnumerateObject())
            {
                property.WriteTo(writer);
            }

            writer.WriteEndObject();
            writer.Flush();

```

**Comment by eiriktsarpalis** [comment] 2021-07-26 13:04
That might work, assuming you can tolerate the additional cycles used in the intermediate serializations and deserializations.

**Comment by dazinator** [comment] 2021-07-26 13:43
Side note related to same problem in different area of the stack: Even if this solves the problem for `System.Text.Json`, I have the same problem for `Microsoft.Extensions.Options` when binding an options class with a polymorphic list, to an `IConfiguration` section. In this case the a json file is first read by `ConfigurationBuilder.AddJsonFile("appsettings.json")` and ends up as essentially key value pairs. The descriminator property is now a key value pair in the IConfiguration. When materialising `IOptions` from this IConfiguration, there is now no JSON converter involved, so if I want to handle polymorphic lists I have to implement a seperate solution here, and it seems like there isn't a way to take control of binding yet.

**Comment by eiriktsarpalis** [comment] 2021-07-26 13:51
I've forked your last question into a separate issue. Assuming your initial question has been answered, I'm going to close this as a duplicate of #30083.

**Closed** 2021-07-26 13:52 UTC
Labels: area-System.Text.Json, customer assistance
