### ISSUE TITLE
Test failure: profiler/transitions/transitions/transitions.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#108829] opened 2024-10-14 01:54 UTC
**Failed in:** [runtime-coreclr gcstress-extra 20241013.1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841239&view=ms.vss-test-web.build-test-results-tab&runId=21811536&resultId=159658&paneView=debug)

**Failed tests:**
```
coreclr linux x64 Checked gcstress0xc_jitstress2 @ Ubuntu.2204.Amd64.Open
    - profiler/transitions/transitions/transitions.cmd
```

**Error message:**
```
 /datadisks/disk1/work/BCFB09B1/w/AF3209B7/e/profiler/profiler/../transitions/transitions/transitions.sh: line 470: 175470 Segmentation fault      (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"

Return code:      1
Raw output file:      /datadisks/disk1/work/BCFB09B1/w/AF3209B7/uploads/transitions/transitions/output.txt
Raw output:
BEGIN EXECUTION
/datadisks/disk1/work/BCFB09B1/p/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true transitions.dll ''
Profiler path: /datadisks/disk1/work/BCFB09B1/w/AF3209B7/e/profiler/transitions/transitions/libProfiler.so
Profilee STDOUT: Profiler.dll!DllGetClassObject
Profilee STDOUT: Profiler.dll!Profiler::Initialize
Profilee STDOUT: PInvoke received i=13
Profilee STDOUT: Profiler.dll!Profiler::Shutdown
Profilee STDOUT: PROFILER TEST PASSES
Expected: 100
Actual: 139
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 10/13/2024 11:23:38 PM
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> /datadisks/disk1/work/BCFB09B1/w/AF3209B7/e/profiler/profiler/../transitions/transitions/transitions.sh
```

**Stack trace:**
```
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor17|0_18(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by mdh1418** [comment] 2024-10-17 18:10
Looks like a duplicate of this flakey failure issue https://github.com/dotnet/runtime/issues/106243

**Closed by mdh1418** 2024-10-17 18:10 UTC
Labels: os-linux, GCStress, arch-x64, area-Diagnostics-coreclr, blocking-clean-ci-optional
