### ISSUE TITLE
Test failure: System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_SslProtocols_Http2_Test.GetAsync_SupportedSSLVersion_Succeeds(sslProtocols: Tls11, url: \"https://www.ssllabs.com:10302/\")

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#41249] opened 2020-08-24 06:29 UTC
failed in job: [runtime-libraries outerloop 20200823.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=784107&view=ms.vss-test-web.build-test-results-tab&runId=24668448&resultId=102382&paneView=debug)

net5.0-Windows_NT-Release-x64-CoreCLR_release-Windows.81.Amd64.Open

Error message
~~~
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.WinHttpException : Error 12029 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'A connection with the server could not be established'.


Stack trace
   at System.Net.Http.HttpClient.FinishSendAsync(ValueTask`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts, Boolean buffered, Boolean async, CancellationToken callerToken, Int64 timeoutTime) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 605
   at System.Net.Test.Common.RemoteServerQuery.Run[TResult](Func`1 testCode, Func`2 remoteExceptionWrapper, String serverName) in /_/src/libraries/Common/tests/System/Net/RemoteServerQuery.cs:line 34
   at System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test.GetAsync_SupportedSSLVersion_Succeeds(SslProtocols sslProtocols, String url) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.SslProtocols.cs:line 162
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult() in /_/src/libraries/Common/src/System/Threading/Tasks/RendezvousAwaitable.cs:line 63
   at System.Net.Http.WinHttpHandler.StartRequestAsync(WinHttpRequestState state) in /_/src/libraries/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs:line 876
~~~

**Comment by v-haren** [comment] 2020-08-25 03:11
failed again in job: [runtime-libraries outerloop 20200824.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=784721&view=ms.vss-test-web.build-test-results-tab&runId=24703022&resultId=104150&paneView=debug)

failed tests:
System.Net.Http.WinHttpHandlerFunctional.Tests.WinHttpHandlerTest.SendAsync_MultipleHttp2ConnectionsEnabled_CreateAdditionalConnections
System.Net.Http.WinHttpHandlerFunctional.Tests.WinHttpHandlerTest.GetAsync_SetCookieContainerMultipleCookies_CookiesSent


Error message
~~~
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.WinHttpException : Error 12002 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The operation timed out'.


Stack trace
   at System.Net.Http.HttpClient.FinishSendAsync(ValueTask`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts, Boolean buffered, Boolean async, CancellationToken callerToken, Int64 timeoutTime) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 605
   at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter[TResult](Task`1 task, TimeSpan timeout) in /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 55
   at System.Net.Http.WinHttpHandlerFunctional.Tests.WinHttpHandlerTest.SendAsync_MultipleHttp2ConnectionsEnabled_CreateAdditionalConnections() in /_/src/libraries/System.Net.Http.WinHttpHandler/tests/FunctionalTests/WinHttpHandlerTest.cs:line 203
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult() in /_/src/libraries/Common/src/System/Threading/Tasks/RendezvousAwaitable.cs:line 63
   at System.Net.Http.WinHttpHandler.StartRequestAsync(WinHttpRequestState state) in /_/src/libraries/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs:line 876
~~~

**Comment by v-haren** [comment] 2020-09-09 05:13
failed again in job:[runtime-libraries-coreclr outerloop 20200908.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=805217&view=ms.vss-test-web.build-test-results-tab&runId=25503256&resultId=103197&paneView=debug)

failed tests: 
System.Net.Http.WinHttpHandlerFunctional.Tests.WinHttpHandlerTest.GetAsync_SetCookieContainerMultipleCookies_CookiesSent


Error message
~~~
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.WinHttpException : Error 12002 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The operation timed out'.


Stack trace
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 736
   at System.Net.Http.WinHttpHandlerFunctional.Tests.WinHttpHandlerTest.GetAsync_SetCookieContainerMultipleCookies_CookiesSent() in /_/src/libraries/System.Net.Http.WinHttpHandler/tests/FunctionalTests/WinHttpHandlerTest.cs:line 161
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult() in /_/src/libraries/Common/src/System/Threading/Tasks/RendezvousAwaitable.cs:line 63
   at System.Net.Http.WinHttpHandler.StartRequestAsync(WinHttpRequestState state) in /_/src/libraries/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs:line 876
~~~

**Comment by v-haren** [comment] 2020-11-02 07:15
failed again in job: [runtime-libraries-coreclr outerloop 20201101.2 ](https://dev.azure.com/dnceng/public/_build/results?buildId=872534&view=ms.vss-test-web.build-test-results-tab&runId=27916824&resultId=104501&paneView=debug)

failed test: System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandlerTest.PostAsync_CallMethod_StreamContent(remoteServer: (BaseUri: https://corefx-net-http2.azurewebsites.net/, HttpVersion: 2.0), content: StreamContentWithSyncAsyncCopy { Headers = [] }, expectedData: [62, 23, 186, 150, 174, ...])

net6.0-Windows_NT-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c


Error message
~~~
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.WinHttpException : Error 12002 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The operation timed out'.


Stack trace
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, CancellationTokenSource cts, Boolean disposeCts, Int64 timeoutTime, CancellationToken originalCancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 547
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest.PostAsync_CallMethod_StreamContent(RemoteServer remoteServer, HttpContent content, Byte[] expectedData) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.cs:line 1817
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult() in /_/src/libraries/Common/src/System/Threading/Tasks/RendezvousAwaitable.cs:line 63
   at System.Net.Http.WinHttpHandler.StartRequestAsync(WinHttpRequestState state) in /_/src/libraries/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs:line 876
~~~

**Comment by v-haren** [comment] 2020-12-31 03:30
failed again in job: https://dev.azure.com/dnceng/public/_build/results?buildId=934303&view=ms.vss-test-web.build-test-results-tab&runId=29569858&resultId=104537&paneView=debug

failed test: System.Net.Http.Functional.Tests.PlatformHandlerTest_AutoRedirect.GetAsync_AllowAutoRedirectTrue_RedirectToUriWithParams_RequestMsgUriSet(remoteServer: (BaseUri: http://corefx-net-http11.azurewebsites.net/, HttpVersion: 1.1))

net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c


Error message
~~~
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.WinHttpException : Error 12002 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The operation timed out'.

Stack trace
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 550
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_AutoRedirect.GetAsync_AllowAutoRedirectTrue_RedirectToUriWithParams_RequestMsgUriSet(RemoteServer remoteServer) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.AutoRedirect.cs:line 298
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult() in /_/src/libraries/Common/src/System/Threading/Tasks/RendezvousAwaitable.cs:line 63
   at System.Net.Http.WinHttpHandler.StartRequestAsync(WinHttpRequestState state) in /_/src/libraries/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs:line 942
~~~

**Comment by VincentBu** [comment] 2021-02-08 02:56
Failed in run [runtime-libraries-coreclr outerloop 20210207.2](https://dev.azure.com/dnceng/public/_build/results?buildId=982379&view=ms.vss-test-web.build-test-results-tab&runId=30786246&resultId=104422&paneView=debug)

Failed test:
```
net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c

  -System.Net.Http.Functional.Tests.PlatformHandlerTest_AutoRedirect.DefaultHeaders_SetCredentials_ClearedOnRedirect(remoteServer: (BaseUri: http://corefx-net-http11.azurewebsites.net/, HttpVersion: 1.1), statusCode: 301)
```

**Error message:**
```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.WinHttpException : Error 12002 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The operation timed out'.

Stack trace
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 550
   at System.Net.Http.Functional.Tests.HttpClientHandlerTest_AutoRedirect.DefaultHeaders_SetCredentials_ClearedOnRedirect(RemoteServer remoteServer, Int32 statusCode) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.AutoRedirect.cs:line 570
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult() in /_/src/libraries/Common/src/System/Threading/Tasks/RendezvousAwaitable.cs:line 63
   at System.Net.Http.WinHttpHandler.StartRequestAsync(WinHttpRequestState state) in /_/src/libraries/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs:line 942

```

**Comment by VincentBu** [comment] 2021-02-25 02:52
Similar test failed in run [runtime-libraries-coreclr outerloop 20210224.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1009644&view=ms.vss-test-web.build-test-results-tab&runId=31479920&resultId=104119&paneView=debug)

Failed test:
```
net6.0-windows-Release-x64-CoreCLR_release-Windows.81.Amd64.Open
 -System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_SslProtocols_Http2_Test.GetAsync_UnsupportedSSLVersion_Throws(sslProtocols: Ssl2, url: \"https://www.ssllabs.com:10200/\")
```

**Error message:**
```
Assert.Throws() Failure
Expected: typeof(System.Net.Http.HttpRequestException)
Actual:   typeof(System.Net.Test.Common.RemoteServerException): Likely external issue with remote server : https://www.ssllabs.com:10200/
---- System.Net.Test.Common.RemoteServerException : Likely external issue with remote server : https://www.ssllabs.com:10200/
-------- System.Net.Http.HttpRequestException : An error occurred while sending the request.
------------ System.Net.Http.WinHttpException : Error 12002 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The operation timed out'.


Stack trace
   at System.Net.Test.Common.RemoteServerQuery.Run[TResult](Func`1 testCode, Func`2 remoteExceptionWrapper, String serverName) in /_/src/libraries/Common/tests/System/Net/RemoteServerQuery.cs:line 40
----- Inner Stack Trace -----
   at System.Net.Test.Common.RemoteServerQuery.Run[TResult](Func`1 testCode, Func`2 remoteExceptionWrapper, String serverName) in /_/src/libraries/Common/tests/System/Net/RemoteServerQuery.cs:line 40
----- Inner Stack Trace -----
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 548
   at System.Net.Test.Common.RemoteServerQuery.Run[TResult](Func`1 testCode, Func`2 remoteExceptionWrapper, String serverName) in /_/src/libraries/Common/tests/System/Net/RemoteServerQuery.cs:line 34
----- Inner Stack Trace -----
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult() in /_/src/libraries/Common/src/System/Threading/Tasks/RendezvousAwaitable.cs:line 62
   at System.Net.Http.WinHttpHandler.StartRequestAsync(WinHttpRequestState state) in /_/src/libraries/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs:line 942
```

**Comment by VincentBu** [comment] 2021-02-25 02:58
Failed again in [runtime-libraries-coreclr outerloop 20210224.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1009644&view=ms.vss-test-web.build-test-results-tab&runId=31479920&resultId=104120&paneView=debug)

Failed test:
```
net6.0-windows-Release-x64-CoreCLR_release-Windows.81.Amd64.Open
 -System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_SslProtocols_Http2_Test.GetAsync_SupportedSSLVersion_Succeeds(sslProtocols: Tls12, url: \"https://www.ssllabs.com:10303/\")
```

**Error message:**
```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.WinHttpException : Error 12029 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'A connection with the server could not be established'.


Stack trace
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 548
   at System.Net.Test.Common.RemoteServerQuery.Run[TResult](Func`1 testCode, Func`2 remoteExceptionWrapper, String serverName) in /_/src/libraries/Common/tests/System/Net/RemoteServerQuery.cs:line 34
   at System.Net.Http.Functional.Tests.HttpClientHandler_SslProtocols_Test.GetAsync_SupportedSSLVersion_Succeeds(SslProtocols sslProtocols, String url) in /_/src/libraries/Common/tests/System/Net/Http/HttpClientHandlerTest.SslProtocols.cs:line 185
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult() in /_/src/libraries/Common/src/System/Threading/Tasks/RendezvousAwaitable.cs:line 62
   at System.Net.Http.WinHttpHandler.StartRequestAsync(WinHttpRequestState state) in /_/src/libraries/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs:line 942
```

**Comment by antonfirsov** [comment] 2021-03-03 10:22
Probably regression from #48817 (similarly to #49028) I'm OOF today, will take care of it tomorrow, but if someone manages to prove the connection (eg by checking timeline data on Kusto), possible quick fix is to revert that PR.

**Comment by VincentBu** [comment] 2021-04-22 06:40
Failed again in [runtime-libraries-coreclr outerloop 20210421.5](https://dev.azure.com/dnceng/public/_build/results?buildId=1099506&view=ms.vss-test-web.build-test-results-tab&runId=33622666&resultId=104504&paneView=debug)

Failed test:
```
net6.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.Server19H1.Open
 -System.Net.Http.WinHttpHandlerFunctional.Tests.WinHttpHandlerTest.SendAsync_MultipleHttp2ConnectionsEnabled_CreateAdditionalConnections
```

**Error message:**
```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.Net.Http.WinHttpException : Error 12030 calling WINHTTP_CALLBACK_STATUS_REQUEST_ERROR, 'The connection with the server was terminated abnormally'.


Stack trace
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs:line 548
   at System.Net.Http.WinHttpHandlerFunctional.Tests.WinHttpHandlerTest.SendAsync_MultipleHttp2ConnectionsEnabled_CreateAdditionalConnections() in /_/src/libraries/System.Net.Http.WinHttpHandler/tests/FunctionalTests/WinHttpHandlerTest.cs:line 207
--- End of stack trace from previous location ---
----- Inner Stack Trace -----
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult() in /_/src/libraries/Common/src/System/Threading/Tasks/RendezvousAwaitable.cs:line 62
   at System.Net.Http.WinHttpHandler.StartRequestAsync(WinHttpRequestState state) in /_/src/libraries/System.Net.Http.WinHttpHandler/src/System/Net/Http/WinHttpHandler.cs:line 942
```

**Comment by karelz** [comment] 2021-04-23 14:31
This is a mix of failures which hit remote endpoints.
The original test failure `GetAsync_SupportedSSLVersion_Succeeds` happened 268x between 2021/2/24@11:31-12:09, then nothing since then. Closing as external.

**Closed by karelz** 2021-04-23 14:31 UTC
Labels: area-System.Net.Http, blocking-clean-ci-optional
