### ISSUE TITLE
Lots of file excluded from single-file in .Net 6 on Windows

### ISSUE THREAD

**Issue by ThomasGoulet73** [dotnet/runtime#50975] opened 2021-04-08 22:19 UTC
### Description
There is a lot more file out of the single-file executable when publishing for Windows x86 using .Net 6 compared to .Net 5.

I tested this in a "Hello world" console app. Here are my results:
<details>
   <summary>.Net 5 files</summary>

```
clrcompression.dll
clrjit.dll
coreclr.dll
mscordaccore.dll
Net5VsNet6.exe
Net5VsNet6.pdb
```
</details>

<details>
   <summary>.Net 6 files</summary>

```
api-ms-win-core-console-l1-1-0.dll
api-ms-win-core-console-l1-2-0.dll
api-ms-win-core-datetime-l1-1-0.dll
api-ms-win-core-debug-l1-1-0.dll
api-ms-win-core-errorhandling-l1-1-0.dll
api-ms-win-core-file-l1-1-0.dll
api-ms-win-core-file-l1-2-0.dll
api-ms-win-core-file-l2-1-0.dll
api-ms-win-core-handle-l1-1-0.dll
api-ms-win-core-heap-l1-1-0.dll
api-ms-win-core-interlocked-l1-1-0.dll
api-ms-win-core-libraryloader-l1-1-0.dll
api-ms-win-core-localization-l1-2-0.dll
api-ms-win-core-memory-l1-1-0.dll
api-ms-win-core-namedpipe-l1-1-0.dll
api-ms-win-core-processenvironment-l1-1-0.dll
api-ms-win-core-processthreads-l1-1-0.dll
api-ms-win-core-processthreads-l1-1-1.dll
api-ms-win-core-profile-l1-1-0.dll
api-ms-win-core-rtlsupport-l1-1-0.dll
api-ms-win-core-string-l1-1-0.dll
api-ms-win-core-synch-l1-1-0.dll
api-ms-win-core-synch-l1-2-0.dll
api-ms-win-core-sysinfo-l1-1-0.dll
api-ms-win-core-timezone-l1-1-0.dll
api-ms-win-core-util-l1-1-0.dll
API-MS-Win-core-xstate-l2-1-0.dll
api-ms-win-crt-conio-l1-1-0.dll
api-ms-win-crt-convert-l1-1-0.dll
api-ms-win-crt-environment-l1-1-0.dll
api-ms-win-crt-filesystem-l1-1-0.dll
api-ms-win-crt-heap-l1-1-0.dll
api-ms-win-crt-locale-l1-1-0.dll
api-ms-win-crt-math-l1-1-0.dll
api-ms-win-crt-multibyte-l1-1-0.dll
api-ms-win-crt-private-l1-1-0.dll
api-ms-win-crt-process-l1-1-0.dll
api-ms-win-crt-runtime-l1-1-0.dll
api-ms-win-crt-stdio-l1-1-0.dll
api-ms-win-crt-string-l1-1-0.dll
api-ms-win-crt-time-l1-1-0.dll
api-ms-win-crt-utility-l1-1-0.dll
clretwrc.dll
clrjit.dll
coreclr.dll
createdump.exe
dbgshim.dll
hostfxr.dll
hostpolicy.dll
Microsoft.DiaSymReader.Native.x86.dll
mscordaccore.dll
mscordaccore_x86_x86_6.0.21.20104.dll
mscordbi.dll
mscorrc.dll
Net5VsNet6.exe
Net5VsNet6.pdb
System.IO.Compression.Native.dll
ucrtbase.dll
```
</details>

And here are my publish profiles:
<details>
   <summary>.Net 5 publish profile</summary>

```
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration>Release</Configuration>
    <Platform>Any CPU</Platform>
    <PublishDir>bin\Net5</PublishDir>
    <PublishProtocol>FileSystem</PublishProtocol>
    <TargetFramework>net5.0</TargetFramework>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
    <PublishSingleFile>True</PublishSingleFile>
    <PublishReadyToRun>False</PublishReadyToRun>
    <PublishTrimmed>False</PublishTrimmed>
  </PropertyGroup>
</Project>
```
</details>

<details>
   <summary>.Net 6 publish profile</summary>

```
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration>Release</Configuration>
    <Platform>Any CPU</Platform>
    <PublishDir>bin\Net6</PublishDir>
    <PublishProtocol>FileSystem</PublishProtocol>
    <TargetFramework>net6.0</TargetFramework>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x86</RuntimeIdentifier>
    <PublishSingleFile>True</PublishSingleFile>
    <PublishReadyToRun>False</PublishReadyToRun>
    <PublishTrimmed>False</PublishTrimmed>
  </PropertyGroup>
</Project>
```
</details>

### Configuration
* Which version of .NET is the code running on? 6.0.100-preview.3.21202.5

### Regression?
I think it's a regression from .Net 5 because files that were previously included in the single-file are now excluded.

**Comment by vitek-karas** [comment] 2021-04-08 22:22
This is a duplicate of https://github.com/dotnet/sdk/issues/16487.

**Closed by vitek-karas** 2021-04-08 22:22 UTC
Labels: area-AssemblyLoader-coreclr, untriaged

**Comment by ThomasGoulet73** [comment] 2021-04-08 22:24
@vitek-karas Sorry, I only looked in dotnet/runtime 😄. Thank you
