### ISSUE TITLE
System.Text.Json.Tests.Utf8JsonWriterTests.WriteNumbers test failing in CI

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#79404] opened 2022-12-08 16:19 UTC
```
 System.Text.Json.Tests.Utf8JsonWriterTests.WriteNumbers(formatted: True, skipValidation: False, keyString: ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>") [FAIL]
      Assert.Equal() Failure
                                        ↓ (pos 465256)
      Expected: ···363,\n  "\u003e\u003eu003e\u003e\u003e\u003e\u003e\u003e\u003···
      Actual:   ···363,\n  "\u003e\u003e\u003e\u003e\u003e\u003e\u003e\u003e\u003···
                                        ↑ (pos 465256)
      Stack Trace:
        /_/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/JsonTestHelper.cs(752,0): at System.Text.Json.JsonTestHelper.AssertContentsAgainstJsonNet(String expectedValue, String value, Boolean skipSpecialRules)
        /_/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/JsonTestHelper.cs(728,0): at System.Text.Json.JsonTestHelper.AssertContents(String expectedValue, ArrayBufferWriter`1 buffer, Boolean skipSpecialRules)
        /_/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/Utf8JsonWriterTests.cs(5669,0): at System.Text.Json.Tests.Utf8JsonWriterTests.WriteNumbers(Boolean formatted, Boolean skipValidation, String keyString)
           at InvokeStub_Utf8JsonWriterTests.WriteNumbers(Object, Object, IntPtr*)
```

## Build Information
Build: https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_build/results?buildId=105778
Build error leg or test failing: System.Text.Json.Tests.Utf8JsonWriterTests.WriteNumbers
Pull request: https://github.com/dotnet/runtime/pull/79378

## Error Message
Fill the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section).

```json
{
  "ErrorMessage": "System.Text.Json.Tests.Utf8JsonWriterTests.WriteNumbers",
  "BuildRetry": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by eiriktsarpalis** [comment] 2022-12-12 12:59
Appears to be duplicate of #59678. Closing in favor of the older issue and transfering the labels.

**Closed by eiriktsarpalis** 2022-12-12 12:59 UTC
Labels: area-System.Text.Json, blocking-clean-ci, untriaged, Known Build Error

**Comment by jkotas** [comment] 2022-12-12 14:30
I have transferred `Known Build Error` label and error message description as well.
