### ISSUE TITLE
GCStress infrastructure assert running ManagedCallingNative.cmd

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#39571] opened 2020-07-17 23:58 UTC
Windows/x86 with:

```
set COMPlus_TieredCompilation=0
set COMPlus_GCStress=0xC
set COMPlus_ReadyToRun=0
set COMPlus_ZapDisable=1
```

```
    Interop\IJW\ManagedCallingNative\ManagedCallingNative\ManagedCallingNative.cmd [FAIL]
      
      Assert failure(PID 7732 [0x00001e34], Thread: 4064 [0x0fe0]): regDisp.PCTAddr == TADDR(gcCover->callerRegs.Esp)
      
      CORECLR! DoGcStress + 0x2D9 (0x6f07fa3e)
      CORECLR! OnGcCoverageInterrupt + 0x15A (0x6f07ffe8)
      CORECLR! IsGcMarker + 0x93 (0x6eec4dc5)
      CORECLR! CLRVectoredExceptionHandlerShim + 0xC5 (0x6eeba2d5)
      NTDLL! WinSqmEventWrite + 0x1C907 (0x77940317)
      NTDLL! RtlUnwind + 0x1BA (0x779003ea)
      NTDLL! KiUserExceptionDispatcher + 0xF (0x7791108f)
      <no module>! <no symbol> + 0x0 (0x08db5039)
      <no module>! <no symbol> + 0x0 (0x088e6389)
      <no module>! <no symbol> + 0x0 (0x088e3458)
          File: F:\workspace\_work\1\s\src\coreclr\src\vm\gccover.cpp Line: 1522
          Image: C:\h\w\A2B708FB\p\CoreRun.exe
      
      
      Return code:      1
      Raw output file:      C:\h\w\A2B708FB\w\A73E0902\e\Interop\IJW\Reports\Interop.IJW\ManagedCallingNative\ManagedCallingNative\ManagedCallingNative.output.txt
      Raw output:
      BEGIN EXECUTION
       "C:\h\w\A2B708FB\p\corerun.exe" ManagedCallingNative.dll 
      Beginning test case Call native method returning int at 7/12/2020 11:44:06 PM
      Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro
      
      
      Ending test case at 7/12/2020 11:44:14 PM
      Beginning test case Negative: Load IJW dll as byte array at 7/12/2020 11:44:14 PM
      Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro
      
      Expected: 100
      Actual: -1073740286
      END EXECUTION - FAILED
      FAILED
```

https://dev.azure.com/dnceng/public/_build/results?buildId=726589&view=ms.vss-test-web.build-test-results-tab&runId=22500688&resultId=101492&paneView=debug

I can repro this locally, maybe 1 out of 10 or 20 runs.

@AndyAyersMS @AaronRobinsonMSFT @jkoritzinsky

**Comment by AndyAyersMS** [comment] 2020-07-18 00:18
I'm not entirely sure what this bit of code in gccover it is trying to check. It seems we are putting gc stress interrupts into non-gc safe epilogs and prologs on x86 so we can stress the unwinder.

**Comment by BruceForstall** [comment] 2020-07-21 01:27
Failed again in the CI:

`CoreCLR Windows_NT x86 Checked gcstress0xc_jitstress2 @ Windows.10.Amd64.Open`
https://dev.azure.com/dnceng/public/_build/results?buildId=737350&view=ms.vss-test-web.build-test-results-tab&runId=22834310&paneView=debug
Interop\NativeLibrary\AssemblyLoadContext\ResolveUnmanagedDllTests\ResolveUnmanagedDllTests.cmd [FAIL]

**Comment by BruceForstall** [comment] 2020-07-21 01:32
Actually, there are quite a few failures in Windows x86 tests in this run:

https://dev.azure.com/dnceng/public/_build/results?buildId=737350&view=ms.vss-test-web.build-test-results-tab&runId=22834310&paneView=debug&resultId=101135

**Comment by v-haren** [comment] 2020-07-27 06:36
failed again in job: [runtime-coreclr gcstress-extra 20200726.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=746229&view=ms.vss-test-web.build-test-results-tab&runId=23131226&resultId=110438&paneView=debug)

failed test: Loader\\binding\\tracing\\BinderTracingTest.ResolutionFlow\\BinderTracingTest.ResolutionFlow.cmd


Error message
~~~
Assert failure(PID 1668 [0x00000684], Thread: 6128 [0x17f0]): regDisp.PCTAddr == TADDR(gcCover->callerRegs.Esp)

CORECLR! DoGcStress + 0x2D9 (0x6f38fe1e)
CORECLR! OnGcCoverageInterrupt + 0x15A (0x6f3903c8)
CORECLR! IsGcMarker + 0x93 (0x6f1d52f5)
CORECLR! CLRVectoredExceptionHandlerShim + 0xC5 (0x6f1ca805)
NTDLL! WinSqmEventWrite + 0x1C907 (0x779e0317)
NTDLL! RtlUnwind + 0x1BA (0x779a03ea)
NTDLL! KiUserExceptionDispatcher + 0xF (0x779b108f)
<no module>! <no symbol> + 0x0 (0x03049024)
<no module>! <no symbol> + 0x0 (0x03048be9)
CORECLR! CallDescrWorkerInternal + 0x34 (0x6f60c411)
    File: F:\workspace\_work\1\s\src\coreclr\src\vm\gccover.cpp Line: 1522
    Image: C:\h\w\C03D0A3E\p\CoreRun.exe


Return code:      1
Raw output file:      C:\h\w\C03D0A3E\w\A723094E\e\Loader\binding\Reports\Loader.binding\tracing\BinderTracingTest.ResolutionFlow\BinderTracingTest.ResolutionFlow.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\C03D0A3E\p\corerun.exe" BinderTracingTest.ResolutionFlow.dll 
[12:26:13 AM] Running AssemblyLoadContextResolving_ReturnNull...
[12:32:45 AM] Running AssemblyLoadContextResolving_LoadAssembly...
Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\C03D0A3E\p
> C:\h\w\C03D0A3E\w\A723094E\e\Loader\binding\tracing\BinderTracingTest.ResolutionFlow\BinderTracingTest.ResolutionFlow.cmd
Expected: True
Actual:   False


Stack trace
   at Loader_binding._tracing_BinderTracingTest_ResolutionFlow_BinderTracingTest_ResolutionFlow_._tracing_BinderTracingTest_ResolutionFlow_BinderTracingTest_ResolutionFlow_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x86.Checked\TestWrappers\Loader.binding\Loader.binding.XUnitWrapper.cs:line 916
~~~

**Comment by v-haren** [comment] 2020-08-03 04:36
failed again in job: [runtime-coreclr gcstress-extra 20200802.1 ](https://dev.azure.com/dnceng/public/_build/results?buildId=754417&view=ms.vss-test-web.build-test-results-tab&runId=23408610&resultId=108870&paneView=debug)

failed test: CoreMangLib\\system\\enum\\EnumIConvertibleToSingle\\EnumIConvertibleToSingle.cmd


Error message
~~~
Assert failure(PID 7444 [0x00001d14], Thread: 9252 [0x2424]): regDisp.PCTAddr == TADDR(gcCover->callerRegs.Esp)

CORECLR! DoGcStress + 0x2D9 (0x6f4501be)
CORECLR! OnGcCoverageInterrupt + 0x15A (0x6f450768)
CORECLR! IsGcMarker + 0x93 (0x6f295539)
CORECLR! CLRVectoredExceptionHandlerShim + 0xC5 (0x6f28aa65)
NTDLL! WinSqmEventWrite + 0x1C907 (0x77aa0317)
NTDLL! RtlUnwind + 0x1BA (0x77a603ea)
NTDLL! KiUserExceptionDispatcher + 0xF (0x77a7108f)
<no module>! <no symbol> + 0x0 (0x08f78a03)
<no module>! <no symbol> + 0x0 (0x08c8fe10)
<no module>! <no symbol> + 0x0 (0x08c8ecf8)
    File: F:\workspace\_work\1\s\src\coreclr\src\vm\gccover.cpp Line: 1522
    Image: C:\h\w\9DC80910\p\CoreRun.exe


Return code:      1
Raw output file:      C:\h\w\9DC80910\w\B0F409F3\e\CoreMangLib\system\Reports\CoreMangLib.system\enum\EnumIConvertibleToSingle\EnumIConvertibleToSingle.output.txt
Raw output:
BEGIN EXECUTION
 "C:\h\w\9DC80910\p\corerun.exe" EnumIConvertibleToSingle.dll 
Beginning test case EnumIConvertibleToSingle at 8/2/2020 11:50:42 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

[Positive]
Beginning scenario: PosTest1: Convert zero to single
Beginning scenario: PosTest2: Test a normal enum of value 3 
Beginning scenario: PosTest3: Convert an int32 to single
Beginning scenario: PosTest4: Convert an int64.MinValue to single
Beginning scenario: PosTest5: Convert a negative to single
Beginning scenario: PosTest6: Convert a negative zero to single

Expected: 100
Actual: -1073740286
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=C:\h\w\9DC80910\p
> C:\h\w\9DC80910\w\B0F409F3\e\CoreMangLib\system\enum\EnumIConvertibleToSingle\EnumIConvertibleToSingle.cmd
Expected: True
Actual:   False


Stack trace
   at CoreMangLib_system._enum_EnumIConvertibleToSingle_EnumIConvertibleToSingle_._enum_EnumIConvertibleToSingle_EnumIConvertibleToSingle_cmd() in F:\workspace\_work\1\s\artifacts\tests\coreclr\Windows_NT.x86.Checked\TestWrappers\CoreMangLib.system\CoreMangLib.system.XUnitWrapper.cs:line 1692
~~~

**Comment by davidwrighton** [comment] 2020-08-06 00:21
@AndyAyersMS This is a regression caused by one of your mitigation measures around GCStress that you've made recently. I didn't do the digging to find out which one in particular, but the RemoveGcCoverageInterrupt function should be safe to use on x86 once PR #40432 is merged.

**Comment by AndyAyersMS** [comment] 2020-08-06 00:34
Interesting; would be nice to understand why. Most of my changes recently were pinvoke call site related...

**Closed** 2020-08-06 23:48 UTC
Labels: GCStress, area-VM-coreclr
