### ISSUE TITLE
Restore and Build Product Error in Microsoft.Build.BackEnd.BinaryTranslator.BinaryWriteTranslator.TranslateDictionary

### ISSUE THREAD

**Issue by benaadams** [dotnet/runtime#40626] opened 2020-08-10 19:56 UTC
https://dev.azure.com/dnceng/public/_build/results?buildId=763662&view=logs&jobId=b226872e-8c83-547b-bd09-c26e54b2cebc&j=b226872e-8c83-547b-bd09-c26e54b2cebc&t=06e7eb07-5eae-539d-e778-5b3ef7042fdd

Restore and Build Product 
```
/ runtime (Libraries Build Linux x64 Debug)

Build log #L1971
Child node "4" exited prematurely. Shutting down. Diagnostic information may be found in files in "/tmp/" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
/tmp/MSBuild_pid-2555_75cd8686c9e7462d87e5a643d9ee969f.failure.txt:
UNHANDLED EXCEPTIONS FROM PROCESS 2555:
=====================
08/10/2020 16:31:12
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at Microsoft.Build.BackEnd.BinaryTranslator.BinaryWriteTranslator.TranslateDictionary[D,T](D& dictionary, ObjectTranslator`1 objectTranslator)
   at Microsoft.Build.Execution.ProjectItemInstance.TaskItem.Microsoft.Build.BackEnd.ITranslatable.Translate(ITranslator translator)
   at Microsoft.Build.BackEnd.BinaryTranslator.BinaryWriteTranslator.Translate[T](List`1& list, ObjectTranslator`1 objectTranslator)
   at Microsoft.Build.BackEnd.LogMessagePacket.TranslateTargetFinishedEvent(ITranslator translator, TargetFinishedEventArgs finishedEvent)
   at Microsoft.Build.Shared.LogMessagePacketBase.WriteToStream(ITranslator translator)
   at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
===================
```

Seen in https://github.com/dotnet/runtime/pull/40326#issuecomment-671533869

**Comment by danmosemsft** [comment] 2020-08-10 20:58
Duplicate of https://github.com/dotnet/msbuild/issues/5232

**Closed by danmosemsft** 2020-08-10 20:58 UTC
Labels: untriaged
