### ISSUE TITLE
InvalidProgramException when accessing struct IReadOnlyList<T> in Expression<T>

### ISSUE THREAD

**Issue by chrarnoldus** [dotnet/runtime#41674] opened 2020-09-01 13:47 UTC
### Description

The code included below crashes with the following exception:

```
Unhandled exception. System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at ConsoleApp1.Program.Main(String[] args)
```

I expected the code to do nothing at all, since I am not even evaluating the `IQueryable`.

```c#
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace ConsoleApp1
{
    internal struct ReadOnlyList<T> : IReadOnlyList<T>
    {
        public int Count
            => throw new Exception();

        public T this[int index]
            => throw new Exception();

        public IEnumerator<T> GetEnumerator()
        {
            throw new Exception();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        IEnumerator<T> IEnumerable<T>.GetEnumerator()
        {
            return GetEnumerator();
        }
    }

    internal class Program
    {
        private static void Main(string[] args)
        {
            var list = default(ReadOnlyList<string>);
            var unused = Array.Empty<int>()
                .AsQueryable()
                .Select(x => list[x]);
        }
    }
}
```

### Configuration

.NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.8.20417.9
 Commit:    fc62663a35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.8.20417.9\

Host (useful for support):
  Version: 5.0.0-preview.8.20407.11
  Commit:  bf456654f9

### Regression?

Yes, compared to 3.1.

### Other information

* Replacing the implemented interface `IReadOnlyList<T>` with `IEnumerable<T>` resolves the crash.
* Replacing the type argument of `ReadOnlyList<string>` with a value type resolves the crash.
* Turning the `struct ReadOnlyList<T>` into a `class` resolves the crash.
* The code where I originally discovered the issue did not use `IQueryable`, but a custom method accepting `Expression<T>`.

**Comment by wzchua** [comment] 2020-09-01 15:00
I have narrowed it down to a generic struct implementing an interface being used in an expression
```C#
public interface IInterface
{
    string this[int index] { get; }
    string B();
}

public readonly struct GenericStruct<T> : IInterface
{
    public string this[int index]
        => throw new Exception();

    public string B() => "B";
}

internal class Program
{
    private static void Main(string[] args)
    {
        Debugger.Break();
        Expression<Func<GenericStruct<string>, string>> funcE = x => x.B();
        Func<GenericStruct<string>, string> f = funcE.Compile();
    }
}
```
when you try to break on even on the first line, the debugger doesn't reach the line
![image](https://user-images.githubusercontent.com/13881045/91867607-687d7480-eca6-11ea-9106-bb9599399ee1.png)

**Comment by EgorBo** [comment] 2020-09-01 15:28
thrown in https://github.com/dotnet/runtime/blob/master/src/coreclr/src/vm/jitinterface.cpp#L3085
```
// There is a pathological case where invalid IL refereces __Canon type directly, but there is no dictionary availabled to store the lookup.
```

**Comment by ericstj** [comment] 2020-09-10 22:34
This is a regression from 3.1.  Doesn't appear to be specific to collections.  CodeGen team, have a look.  I reproed on RC1.  Could be important for 5.0.  cc @jeffschwMSFT @jeffschwMSFT

**Comment by jeffschwMSFT** [comment] 2020-09-10 22:41
@JulieLeeMSFT

**Comment by JulieLeeMSFT** [comment] 2020-09-10 23:07
@CarolEidt please take a look.

**Comment by jkotas** [comment] 2020-09-11 04:43
Regression introduced by my change #38229 . I will take a look.

**Comment by JulieLeeMSFT** [comment] 2020-09-15 21:25
Closing this because it is merged to RC2 now.

**Closed by JulieLeeMSFT** 2020-09-15 21:25 UTC
Labels: area-CodeGen-coreclr, blocking-release, bug, regression-from-last-release
