### ISSUE TITLE
Is it possible to track the value of the delegate to avoid reading problems under Release?

### ISSUE THREAD

**Issue by 1996v** [dotnet/runtime#44103] opened 2020-10-31 13:49 UTC
```c#
public void Test1()
{
    int i = 1;

    Task.Run(() => { i = int.MinValue; });

    do { }
    while (i > 0);
}
```
JIT likes to optimize the loop body. If conditions permit, JIT will store loop variables in registers as much as possible to avoid accessing it from memory.  

**In the above example, running this method under Debug will eventually exit the main thread correctly,
 while running this method under Release will cause endless loops**  

Here is the assembly code under [Sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxNMSAmIDUAfAAQAYACAgRgFYBuAWACgCBmEgVwDsoIAzOMgJhIAROGAD2JAN4MSsubOZkALCQAqcWOQAUAShny50+gZMkAluxjmSAXhLk6x0/IIA2AHQAlDlt22AfFLWdhYw7gCyFgBqEAA2rHDUJAC+Oo7O8pgSkin6GSQA7gAWZrF8WmYkgURpeQbJ8gzJDEA===) Debug,as you can see, the final comparison and assignment of the variable i are the same address
```assembly
L007e: cmp dword ptr [eax+4], 0  
mov dword ptr [eax+4], 0x80000000 
```
Here is the assembly code under [Sharplab](https://sharplab.io/#v2:EYLgtghgzgLgpgJwDQxNMAfAAgBgARYCMArANwCwAUFgMx4CuAdlBAGZwEBMeAInGAHs8Abyp5xE8bQIAWPABU4sQgAoAlGMkTRlLXrwBLRjEN4AvHkIVd+yVgBsAOgBKTFevMA+EaYtGYjgCyRgBqEAA29HCkeAC+ata2kgAmQsJxmkl4AO4AFgbhHCoGeN44CZlasZJUsVRAA=) Release, as you can see,the final comparison and assignment of variable i are not the same address
```assembly
L0037: mov eax, [esi+4]  
L003a: test eax, eax 
mov dword ptr [ecx+4], 0x80000000 
```
I know that c# is non-volatile for reads, so to make the program work under Release, you simply read the i using volatile.   
  
But I'm not concerned about this. What I care about is whether JIT can track and analyze the value of the delegate, so that the above code can run normally under Release?

**Comment by 1996v** [comment] 2020-10-31 14:05
@EgorBo

**Comment by EgorBo** [comment] 2020-10-31 15:34
CSE issue? cc @dotnet/jit-contrib

**Comment by briansull** [comment] 2020-11-02 20:17
The local variable 'i' should be declared as volatile, if you expect to observe changes made by a different thread of execution.

**Comment by briansull** [comment] 2020-11-02 20:25
> I know that c# is non-volatile for reads, so to make the program work under Release, you simply read the i using volatile.
> 
> But I'm not concerned about this. What I care about is whether JIT can track and analyze the value of the delegate, so that the above code can run normally under Release?

Why do you expect that the JIT should undertake such an analysis for this case?

Behind the scenes the C# compiler creates a struct and places any locals that escape the method into this struct.
And passes the address to this struct to the delegate.   If you need to observe changes across threads of execution the standard way is to declare the variable(s) as volatile. 

You could also raise this issue with the Roslyn C# team to get their viewpoint on this.

**Comment by erozenfeld** [comment] 2020-11-02 20:44
>> The local variable 'i' should be declared as volatile, if you expect to observe changes made by a different thread of execution.

You can't declare a local as `volatile`.  `volatile` can be used only on fields.

Isn't `i` address-taken in this example? Looks like a bug in jit optimizations.

**Comment by briansull** [comment] 2020-11-02 21:04
@erozenfeld  The variable 'i' is placed in a anonymous struct by the C# compiler and that struct is passed around by reference.

**Comment by erozenfeld** [comment] 2020-11-02 22:00
Ok, yes, Roslyn decided not to mark fields corresponding to captured locals as `volatile` and the proposal to add `volatile` for locals was rejected: https://github.com/dotnet/roslyn/issues/2234. So, the solution is to use `Volatile.Read`.  

>> What I care about is whether JIT can track and analyze the value of the delegate, so that the above code can run normally under Release?

No, when compiling `Test1` the jit has no idea that the field corresponding to the captures local is modified. Since the filed has no `volatile` modifier, the jit is allowed to optimize the read.

**Comment by 1996v** [comment] 2020-11-03 14:49
A delegate field defined in a method is usually promoted to a static(don't have to instantiate each call) field or resolved to a new object(each invocation is instantiated) by the compiler based on the object referenced by the delegate.

the delegate field does not assign, it is always unchanged, and its value is static, which means that the compiler can parse the expression in a number of phases, including parsing the contents of the delegate.
In this case, The delegate is resolved into a new object (including `i`), which is also used by the loop variable.

I want to take the opportunity to express whether JIT can discover or avoid the situation in this example in advance for this type of delegation?

**Comment by briansull** [comment] 2020-11-03 18:15
@VSadov This customer is also using a delegate to update a captured local variable which the JIT is enregistering since it is not using a Volatile access.  Is there a contact on the Roslyn team that we could loop in here?

**Comment by VSadov** [comment] 2020-11-03 20:26
Formally the behavior is correct from either C# or JIT points of view.

C# generally assumes that all reads/writes are ordinary, unless user specifies the need for Volatile. 
JIT assumes that ordinary reads are not sideffecting (thus subsequent reads of the same location may be combined into one), and since there is nothing in the loop that could possibly change the value of `i` , it is permitted to take the read out of the loop.

It is possible to get into this kind of trouble without lambdas too. This is a relatively common optimization, just the loops with bodies that have no sideeffects are not common. Otherwise we would see this more often.

The recommended way to suppress reordering or coalescing when reading variables that could be changes concurrently is to use `Volatile.Read`.

Adding any code with opaque sideefects in the loop body should solve the problem too. 
Since this is a spin-waiting pattern, doing something like `Thread.Yield()` or `SpinWait.SpinOnce()` might be a good idea anyways. 

CC @jaredpar

**Comment by AndyAyersMS** [comment] 2020-11-09 19:14
Seems like essentially the same issue as in #43787.

**Comment by VSadov** [comment] 2020-11-09 20:27
Yes, same as #43787.

**Comment by briansull** [comment] 2020-11-11 05:50
Duplicate of #43787

Volatile.Read and Volatile.Write are required to update state that is shared between different threads

**Closed by briansull** 2020-11-11 05:50 UTC
Labels: area-CodeGen-coreclr, untriaged
