### ISSUE TITLE
Test failure: System.Threading.Tests.ThreadLocalTests.RunThreadLocalTest8_Values

### ISSUE THREAD

**Issue by v-haren** [dotnet/runtime#44187] opened 2020-11-03 07:46 UTC
failed in  job: [runtime 20201102.59 ](https://dev.azure.com/dnceng/public/_build/results?buildId=873691&view=ms.vss-test-web.build-test-results-tab&runId=27950064&resultId=169008&paneView=debug)

net6.0-Linux-Release-x64-Mono_release-SLES.12.Amd64.Open

Error message
~~~
System.Threading.Tasks.TaskSchedulerException : An exception was thrown by a TaskScheduler.
---- System.ExecutionEngineException : Couldn't create thread. Error 0x0


Stack trace
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 1699
   at System.Threading.Tasks.Task`1[[System.Int32, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].StartNew(Task parent, Func`1 function, CancellationToken cancellationToken, TaskCreationOptions creationOptions, InternalTaskOptions internalOptions, TaskScheduler scheduler) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Future.cs:line 336
   at System.Threading.Tasks.TaskFactory.StartNew[Int32](Func`1 function, CancellationToken cancellationToken, TaskCreationOptions creationOptions, TaskScheduler scheduler) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TaskFactory.cs:line 629
   at System.Threading.Tests.ThreadLocalTests.RunThreadLocalTest8_Values() in /_/src/libraries/System.Threading/tests/ThreadLocalTests.cs:line 253
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 378
----- Inner Stack Trace -----
   at System.Threading.Thread.Start(Object parameter) in /_/src/mono/netcore/System.Private.CoreLib/src/System/Threading/Thread.Mono.cs:line 267
   at System.Threading.Tasks.ThreadPoolTaskScheduler.QueueTask(Task task) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/ThreadPoolTaskScheduler.cs:line 50
   at System.Threading.Tasks.TaskScheduler.InternalQueueTask(Task task) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/TaskScheduler.cs:line 237
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 1671
~~~

**Comment by jkoritzinsky** [comment] 2020-11-03 21:31
This is a duplicate of #43981

**Closed by jkoritzinsky** 2020-11-03 21:31 UTC
Labels: area-System.Threading, untriaged
