### ISSUE TITLE
Deserialize of DateOnly in System.Text.Json 9.0.0 returns incorrect date and year

### ISSUE THREAD

**Issue by experimentaltv** [dotnet/runtime#109892] opened 2024-11-16 19:28 UTC
### Description

```JsonSerializer.Deserialize```of a ```DateOnly``` field returns the incorrect date and year.

### Reproduction Steps

```
public class TestDateOnly
{
    public DateOnly? TestDate { get; set; } // same problem if not nullable
}

[TestMethod]
public void DateOnlyConverter()
{
    var testDate = new DateOnly(2001, 01, 25);

    var response = new TestDateOnly { TestDate = testDate };
    var json = JsonSerializer.Serialize(response); // serialization is correct

    var test = JsonSerializer.Deserialize<TestDateOnly>(json);
    Assert.IsNotNull(test);
    Assert.AreEqual(testDate, test.TestDate);
}
```

### Expected behavior

Test should pass.

### Actual behavior

Assert.AreEqual failed. Expected:<1/25/2001>. Actual:<1/1/0001>

### Regression?

Test passes with System.Text.Json 8.0.4.

### Configuration

Windows 10, .NET 9, x64

**Comment by eiriktsarpalis** [comment] 2024-11-16 20:59
I can't reproduce the issue using .NET 9. Are you certain the reproduction is correct?

**Comment by martincostello** [comment] 2024-11-16 21:02
Looks like the property in the test is never initialised and the local variable is being serialized and then the deserialized value being compared to the uninitialized property instead the local.

**Comment by experimentaltv** [comment] 2024-11-16 21:51
I dug into this a little deeper. It fails if I target .NET 6.0. If I target .NET 8.0 or .NET 9.0, it works correctly.

**Comment by eiriktsarpalis** [comment] 2024-11-16 22:16
This is expected, STJ 6 didn't have built in support for DateOnly.

**Comment by experimentaltv** [comment] 2024-11-16 23:03
To clarify: when I call System.Text.Json 9.0.0 from an app targeting .NET 6 (which compiles fine) it gives an incorrect result and one that is different from calling System.Text.Json 8.0.4. I consider this to be at best unexpected, at worst a data corruption issue.

**Comment by MichalPetryka** [comment] 2024-11-16 23:08
.NET 6 is out of support already so all issues related to it won't be actioned on.

**Comment by stephentoub** [comment] 2024-11-17 00:05
> when I call System.Text.Json 9.0.0 from an app targeting .NET 6 (which compiles fine)

I'd expect you to be getting a warning saying that's not supported.

**Comment by experimentaltv** [comment] 2024-11-17 00:26
I have <TreatWarningsAsErrors>true</TreatWarningsAsErrors> on in my project and it was only a unit test lingering from when I implemented my own json converter that saved me from corrupting data after updating all packages to 9.0.

I've read every lengthy blog post you've ever written and re-reviewed the System.Text.Json 9.0 notes before filing this issue. If you think it is acceptable I'll certainly defer, but it seems sub-optimal and frankly dangerous.

**Comment by eiriktsarpalis** [comment] 2024-11-17 00:39
> when I call System.Text.Json 9.0.0 from an app targeting .NET 6 (which compiles fine) it gives an incorrect result and one that is different from calling System.Text.Json 8.0.4. I consider this to be at best unexpected, at worst a data corruption issue.

The 9.0 NuGet package doesn't include net6.0 target since it's now out of support. I presume what's happening is your application ends up either not using it or referencing the ns2.0 build? A minimal repro would help.

**Comment by stephentoub** [comment] 2024-11-17 01:17
> I have <TreatWarningsAsErrors>true</TreatWarningsAsErrors> on in my project and it was only a unit test lingering from when I implemented my own json converter that saved me from corrupting data after updating all packages to 9.0.

I'd expect you to be getting a warning like:
```
1>C:\Users\stoub\.nuget\packages\system.text.json\9.0.0\buildTransitive\netcoreapp2.0\System.Text.Json.targets(4,5): warning : System.Text.Json 9.0.0 doesn't support net6.0 and has not been tested with it. Consider upgrading your TargetFramework to net8.0 or later. You may also set <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings> in the project file to ignore this warning and attempt to run in this unsupported configuration at your own risk.
```
unless you've set `SuppressTfmSupportBuildWarnings` in your project.

**Comment by eiriktsarpalis** [comment] 2024-11-17 12:33
> On a positive note, it's now been tested and it corrupts data. I understand that net6.0 is out of support but that doesn't make the regression any less surprising.

To clarify, "corrupts" in this context means that it returns the default value for `DateOnly`, correct?

**Comment by experimentaltv** [comment] 2024-11-17 12:37
Correct. Feel free to edit the issue title as necessary.

**Comment by MichalPetryka** [comment] 2024-11-17 13:24
I recall there being some bug where the SDK ignores TreatWarningsAsErrrors for warnings thrown from MSBuild files, that could be the case here.

**Comment by experimentaltv** [comment] 2024-11-17 13:28
@stephentoub I verified that the warnings do appear. I confess that I'm generally blind to NuGet output at this point and that unless the updates I request roll back, I generally do not scan it. I naively assumed I was protected via TreatWarningsAsErrors.

My project pre-dates much of the DateTime work and I registered a custom JsonConverter. That's why I had a unit test that caught this.

Whatever changed in System.Text.Json 9.0.0 overrides that converter, too. In testing, I deleted my custom converter and confirmed that JsonSerializer.Deserialize returned the default value for DateOnly in both cases.

**Comment by eiriktsarpalis** [comment] 2024-11-17 17:42
It's an unsupported scenario and you're confirming that the tooling is warning about it. Seems we can resolve the issue?

**Comment by stephentoub** [comment] 2024-11-17 17:54
@ericstj, is it expected that <TreatWarningsAsErrors>true</TreatWarningsAsErrors> doesn't impact the nuget warnings about unsupported packages? I just tried and I similarly see that my build completes successfully, with a warning but not with it elevated to error.

**Comment by experimentaltv** [comment] 2024-11-17 17:57
Subject to @stephentoub concerns above (and possible consideration that System.Text.Json 9.0.0 should just be marked incompatible with .net6.0) I'm ok with closing this issue.

**Comment by gregsdennis** [comment] 2024-11-18 01:10
How does the lack of support for net6 interact with the package still claiming support for netstandard2.0?  Even if the package doesn't list net6, the netstandard2.0 version will be used.

**Comment by stephentoub** [comment] 2024-11-18 01:12
net6.0 itself is out of support.

**Comment by gregsdennis** [comment] 2024-11-18 05:01
Yes, I understand that. But netstandard2.0 isn't, and net6 purported to support netstandard2.0, so the question bears investigating.

If System.Text.Json 9.0.0 was published with netstandard2.0 support, and net6 supports netstandard2.0 libs, it makes sense that net6 would support System.Text.Json 9.0.0.

**Comment by experimentaltv** [comment] 2024-11-18 05:30
The netstandard2.0 case, at least as it applies to this issue, is mitigated by the fact that netstandard2.0 does not support ```DateOnly```. 

Note that .NET 9 shipped on the same day that .NET 6 went out of support. I assume this was planned but it does incentivize having compatibility issues closed prematurely.

**Comment by eiriktsarpalis** [comment] 2024-11-18 10:17
The issue fundamentally is that netstandard2.0 builds of STJ do not ship converters for `DateOnly` and `TimeOnly` because `DateOnly` and `TimeOnly` are not available in netstandard2.0. If your application ends up referencing a ns2.0 build of STJ then it would be having the behaviour you are seeing.

**Comment by experimentaltv** [comment] 2024-11-18 18:34
I want to thank everyone for their attention to this. I filed the issue because nothing showed up in Google when I first discovered it. 

I'm going to plead a mix of ignorance and laziness regarding the broader issues here.

Clearly I'm spoiled by backwards compatibility as when I see a major version change in a library, I generally assume that if NuGet handles the dependencies and that if my code builds it will work. In my defense, I read every post on the topic and assumed that System.Text.Json went to 9.0.0 as part of the .NET 9 release. And, sure, I had a unit test that caught it.

But I didn't expect System.Text.Json 9.0.0 to stop processing a datatype that I wrote a JsonConverter for in the .NET 6 era until I moved my project to .NET 8 (!). It still seems a little odd to me.

**Comment by eiriktsarpalis** [comment] 2024-11-18 18:40
> But I didn't expect System.Text.Json 9.0.0 to stop processing a datatype that I wrote a JsonConverter for in the .NET 6 era until I moved my project to .NET 8 (!). It still seems a little odd to me.

Do you have a repro? I don't see a custom converter in the original post.

**Comment by osexpert** [comment] 2024-12-02 21:56
I remember reading several places suggesting that netstandard is dead, long live net6.0 as the "new" defacto netstandard. It may seem those people spoke to soon and did not anticipate problems like this.

**Comment by eiriktsarpalis** [comment] 2024-12-03 19:10
Closing as answered.

**Closed by eiriktsarpalis** 2024-12-03 19:10 UTC
Labels: area-System.Text.Json, untriaged
