### ISSUE TITLE
Memory leak in HttpClient

### ISSUE THREAD

**Issue by jordinl** [dotnet/runtime#108741] opened 2024-10-10 07:41 UTC
### Description

I have a script that iterates over a large number of URLs and makes a GET request for each URL using async tasks. With parallelism set at 100 and with 15K URLs a 1 vCPU / 2GB RAM AWS instance runs out of memory.

### Reproduction Steps

Added a project which can be used to reproduce the issue: https://github.com/jordinl/dotnet-http-client-memory-leak

The two only important files are the [main script](https://github.com/jordinl/dotnet-http-client-memory-leak/blob/main/Program.cs) which reads the [urls.txt file](https://github.com/jordinl/dotnet-http-client-memory-leak/blob/main/Program.cs) and makes the requests concurrently.

Running the program with `CONCURRENCY=100` and `LIMIT=15000` on a 1 vCPU / 2GB RAM AWS instance causes the instance to run out of memory. Even running it with smaller values it's obvious that the memory keeps increasing.

### Expected behavior

AWS instance not to run out of memory.

### Actual behavior

Memory grows indefinitely.

![Image](https://github.com/user-attachments/assets/09ab9082-2a16-4ef9-ab5b-165e4e3d7faf)

### Configuration

* .NET 8
* OS: Linux 6.10 / Fedora 39 and Linux 6.8 / Ubuntu 24.04
* x86_64

### Other information

Tried a couple of other things with the same results:

* Using `IHttpClientFactory` instead of a single `HttpClient`.
* `var tasks  = urls.Select(async url => ...` to launch each task and then call `await Task.WhenAll(tasks)`

**Comment by jordinl** [comment] 2024-10-14 10:14
Lowering `PoolConnectionIdleTimeout` seems to improve things, like I did on this [branch](https://github.com/jordinl/dotnet-http-client-memory-leak/compare/main...lower-connection-idle-timeout), but it doesn't seem to fix the issue completely.

Running the program on a 1 vCPU / 2GB RAM AWS instance with default connection idle timeout, `CONCURRENCY=100` and `LIMIT=10000` memory usage goes up to 66%:

```
ubuntu@ip-10-0-0-188:~/test$ sar -r 5
Linux 6.8.0-1016-aws (ip-10-0-0-188) 	10/14/24 	_aarch64_	(1 CPU)

09:59:23    kbmemfree   kbavail kbmemused  %memused kbbuffers  kbcached  kbcommit   %commit  kbactive   kbinact   kbdirty
09:59:28       668720   1484168    181956      9.70     24904    903112    899728     47.98    145004    896444       448
09:59:33       622196   1437092    222348     11.86     25168    908344   1296448     69.14    202668    895704       424
09:59:38       553632   1368844    288180     15.37     25168    908740   1377076     73.44    254252    895764       452
09:59:43       506980   1322524    331052     17.66     25168    909752   1438916     76.74    295024    895884       504
09:59:48       402904   1218812    430840     22.98     25168    910284   1470448     78.42    363896    895956       556
09:59:53       375480   1191892    453228     24.17     25168    911360   1490324     79.48    423612    896156       400
09:59:58       334128   1150844    491532     26.21     25168    911432   1514548     80.77    469684    896220       452
10:00:03       280120   1097100    542700     28.94     25184    911552   1560624     83.23    517588    896300       152
10:00:08       180860    998284    637196     33.98     25184    911688   1643480     87.65    614180    896400       252
10:00:13       139352    888940    742760     39.61     25180    844392   1697244     90.52    722816    828676       348
10:00:18       122660    804240    824816     43.99     25180    777068   1727016     92.11    797760    757924       260
10:00:23        81120    739312    886068     47.26     24576    754920   1732364     92.39    888044    701164       528
10:00:28        82844    664156    958244     51.11     23076    680000   1739576     92.78    953040    620704       588
10:00:33        62168    589864   1029192     54.89     22920    626668   1794400     95.70   1037320    580700       656
10:00:38        74932    497364   1119748     59.72     18716    526608   1848292     98.57   1109788    494664       268
10:00:43        62628    449228   1164044     62.08     18452    490972   1839756     98.12   1159372    452456       340
10:00:48        65708    362224   1248360     66.58     16256    404420   1864040     99.41   1232600    361656       404
10:00:53       152008    376860   1234080     65.82     14796    335708   1834636     97.85    581536    912692       364
```

With 1 second connection idle timeout, `CONCURRENCY=100` and `LIMIT=10000` memory usage goes up to 32%:

```
ubuntu@ip-10-0-0-188:~/test$ sar -r 5
Linux 6.8.0-1016-aws (ip-10-0-0-188) 	10/14/24 	_aarch64_	(1 CPU)

10:02:37    kbmemfree   kbavail kbmemused  %memused kbbuffers  kbcached  kbcommit   %commit  kbactive   kbinact   kbdirty
10:02:42      1239468   1477796    185900      9.91     16716    340500    900836     48.04    200544    270956       120
10:02:47      1192512   1434020    223188     11.90     17704    348812   1273916     67.94    258064    271924       452
10:02:52      1122980   1364688    290972     15.52     17712    349556   1347988     71.89    316820    272016       500
10:02:57      1091712   1333580    320060     17.07     17712    351920   1357944     72.42    326236    272144       564
10:03:02      1083676   1325608    327520     17.47     17712    352228   1372296     73.19    343512    272204       612
10:03:07      1069060   1311196    341736     18.23     17712    352620   1403648     74.86    363716    272408       212
10:03:12      1069060   1311252    341780     18.23     17712    352680   1419652     75.71    371160    272464       260
10:03:17      1019444   1261740    390808     20.84     17720    352932   1440568     76.83    404124    272536       288
10:03:22       997800   1240384    413508     22.05     17720    353472   1462896     78.02    448232    272784       404
10:03:27       971620   1214232    438512     23.39     17720    354424   1450120     77.34    455572    272852        12
10:03:32       944908   1187584    463664     24.73     17720    355104   1450744     77.37    474448    272916        72
10:03:37       918172   1160912    489120     26.09     17720    355436   1460104     77.87    501728    272980       136
10:03:42       918452   1161260    487896     26.02     17720    355708   1452176     77.45    514228    273048       204
10:03:47       899036   1141924    506212     27.00     17728    355860   1469156     78.35    545936    273120       308
10:03:52       867032   1109984    537300     28.66     17728    356144   1464832     78.12    566080    273184       372
10:03:57       851468   1094496    551764     29.43     17728    356752   1461692     77.96    587140    273260        88
10:04:02       794808   1037924    607436     32.40     17728    357392   1487648     79.34    619212    273344       124
10:04:07      1207900   1450804    209756     11.19     17768    344132    900836     48.04    204004    273384        48
```

So it seems to grow at a slower rate, but it still keeps growing. With `LIMIT=20000` memory goes up to 45%:

```
10:05:52    kbmemfree   kbavail kbmemused  %memused kbbuffers  kbcached  kbcommit   %commit  kbactive   kbinact   kbdirty
10:05:57      1223784   1468088    198064     10.56     18036    345224    900836     48.04    201628    273708         0
10:06:02      1163952   1407732    255460     13.62     18224    350652   1288144     68.70    268184    272856       404
10:06:07      1109304   1353164    309520     16.51     18224    350932   1381128     73.66    323260    272888       436
10:06:12      1074820   1318752    342088     18.24     18224    352644   1460984     77.92    356088    272948       496
10:06:17      1038068   1282112    378108     20.17     18224    352852   1439968     76.80    359008    273024       552
10:06:22      1041236   1285360    373760     19.93     18224    352932   1445228     77.08    369196    273096       616
10:06:27      1041236   1285404    373128     19.90     18224    353076   1455724     77.64    387888    273156       668
10:06:32      1009732   1254020    402824     21.48     18232    353532   1469672     78.38    422600    273236        28
10:06:37       977752   1222192    432832     23.08     18232    353816   1458548     77.79    438096    273364       156
10:06:42       947756   1192216    461888     24.63     18232    354156   1464188     78.09    460116    273424       216
10:06:47       919268   1163788    489044     26.08     18232    354660   1461608     77.95    480808    273484       272
10:06:52       914728   1159316    492572     26.27     18232    354920   1465788     78.17    503888    273552       340
10:06:57       894600   1139252    511340     27.27     18232    355412   1472680     78.54    524976    273616       400
10:07:02       876200   1120920    528428     28.18     18240    356056   1472932     78.56    542780    273684        56
10:07:07       863344   1108128    540100     28.80     18240    356624   1473236     78.57    561316    273748       124
10:07:12       836284   1081148    566256     30.20     18240    356960   1503208     80.17    598140    273820       188
10:07:17       754524    999476    647608     34.54     18240    357200   1510524     80.56    624352    273896       256
10:07:22       768344   1013484    633012     33.76     18240    358076   1497672     79.87    628504    274084       308
10:07:27       774896   1020096    625812     33.38     18240    358540   1542624     82.27    649592    274152       376
10:07:32       745184    990476    654584     34.91     18248    358880   1553912     82.87    679952    274236        12
10:07:37       735828    981204    663128     35.37     18248    358996   1543476     82.32    689628    274304        76
10:07:42       720200    965640    678112     36.17     18248    359532   1544968     82.40    704932    274368       140
10:07:47       691500    937104    705680     37.64     18248    360344   1546204     82.46    724800    274448       220
10:07:52       648664    894340    747900     39.89     18248    360492   1580520     84.29    765548    274516       268
10:07:57       644912    890652    751104     40.06     18248    360564   1609544     85.84    780336    274580       332
10:08:02       602940    848888    792596     42.27     18256    360808   1619940     86.40    798784    274796       456
10:08:07       609940    855960    785072     41.87     18256    360896   1623940     86.61    800932    274868       116
10:08:12       612208    858296    782380     41.73     18256    360996   1643708     87.66    798688    274936       184
10:08:17       612204    858360    782048     41.71     18256    361124   1661360     88.60    808328    275004       248
10:08:22       594588    840812    799516     42.64     18256    361208   1731392     92.34    821136    275072       316
10:08:27       544204    790492    849844     45.32     18256    361276   1832984     97.76    885488    275136       380
10:08:32       593440    839800    800536     42.69     18264    361340   1755548     93.63    817944    275208       444
10:08:37      1229324   1475672    181396      9.67     18304    346996    900836     48.04    202160    275256        48
```

**Comment by rzikm** [comment] 2024-10-14 16:10
I have done some experiments and so far have found that:
- A lot of memory gets used by the SslSessions cache (OpenSSL stores a lot of metadata for each session ticked, such as the X509Certificate of the server). I have seen as many as 12000 sessions when running with LIMIT=10000. You can disable the sessions cache by setting `DOTNET_SYSTEM_NET_SECURITY_DISABLETLSRESUME=1`. Unfortunately, it does not help much
- Next step was looking for native leaks via `heaptrack` with disabled TLS resume, `heaptrack` reports only a very small amount of memory leaked (likely some impl. detail of .NET Runtime). No memory was reported leaked from OpenSSL
- Disabling Revocation checking also does not seem to affect (in the past, there was a problem with long CRLs causing lots of space to be wasted in mallocs free lists.
- I tried running with malloc stats to see if we are hitting the free list issue anyway, but it does not seem to be the case.

For now, my suspicion is that the memory is being kept by the individual HttpConnectionPools inside the HttpClient. since we are sending requests to 10000 different hosts, it will create 10000 different connections and keep them alive (and keeping all buffers, OpenSSL structures etc allocated). I will continue tomorrow, I have some couple of ideas how to improve this.

**Comment by ManickaP** [comment] 2024-10-15 06:37
Just a suggestion, but if this is a crawler like scenario, where each url is hit just once, turning off connection pooling might be the best bet.

**Comment by jordinl** [comment] 2024-10-15 08:33
@ManickaP @rzikm thanks for looking into this. Yes, this is for a crawler. Not sure disabling connection pooling is the solution though, as it would make subsequent requests to the same host slower.

Regardless, I've actually tried to disable connection pooling and I'm not seeing an improvement over just setting `PooledConnectionIdleTimeout` to a low value. Don't know if I'm not doing correctly but the documentation is not clear.

I tried:

* Setting `PooledConnectionLifetime` to zero https://github.com/jordinl/dotnet-http-client-memory-leak/commit/da27f51ea1c93b8b14f8a4a799d0cfb1e2bd0e4c
* Setting `HttpClient.DefaultRequestHeaders.ConnectionClose = true` https://github.com/jordinl/dotnet-http-client-memory-leak/commit/8fa586d120fa5883754eb336dde5f64fbf696da8. Also I tried `HttpClient.DefaultRequestHeaders.Connection.Add("close")`
* Based on this comment, using an HtttpClient for earch request and setting connection close https://github.com/jordinl/dotnet-http-client-memory-leak/commit/f76aa9f370897e554e841c66822237999eaf3c25

**Comment by jordinl** [comment] 2024-10-15 09:38
@ManickaP 

This is what I did here https://github.com/jordinl/dotnet-http-client-memory-leak/commit/da27f51ea1c93b8b14f8a4a799d0cfb1e2bd0e4c. 
And also using a new HttpClient instance per request here: https://github.com/jordinl/dotnet-http-client-memory-leak/commit/f76aa9f370897e554e841c66822237999eaf3c25

There doesn't seem to be a difference between using a static HttpClient or a new instance. Things improve decently by setting `PooledConnectionLifetime = TimeSpan.Zero`, as does setting `HttpClient.DefaultRequestHeaders.ConnectionClose = true;` with the default HttpClient settings. There still seems to be a memory leak though.

With 10000 URLs memory goes up to 32%:

```
ubuntu@ip-10-0-0-188:~/test$ sar -r 5
Linux 6.8.0-1016-aws (ip-10-0-0-188) 	10/15/24 	_aarch64_	(1 CPU)

09:30:53    kbmemfree   kbavail kbmemused  %memused kbbuffers  kbcached  kbcommit   %commit  kbactive   kbinact   kbdirty
09:30:58       656824   1458092    205544     10.96     52972    861440    934996     49.87    393100    642344       136
09:31:03       656824   1458092    205544     10.96     52972    861440    934996     49.87    393100    642344       136
09:31:08       611760   1412296    244452     13.04     53100    866672   1327560     70.80    444452    641432       484
09:31:13       572220   1372820    282624     15.07     53100    867268   1358376     72.45    465972    641468       520
09:31:18       547076   1347724    306444     16.34     53100    867868   1439020     76.75    492712    641516       564
09:31:23       499844   1300572    351716     18.76     53100    868884   1442876     76.95    512940    641592       640
09:31:28       467344   1268148    382952     20.42     53100    869212   1451600     77.42    535732    641660       684
09:31:33       479660   1280524    369748     19.72     53100    869476   1473396     78.58    550860    641720       732
09:31:38       482456   1283392    365900     19.51     53100    869672   1492028     79.57    563576    641784        16
09:31:43       462552   1263584    384696     20.52     53100    869832   1496152     79.79    576272    641880       108
09:31:48       411384   1212512    434760     23.19     53100    870252   1502236     80.12    604404    641976       204
09:31:53       382136   1183316    463056     24.70     53100    870576   1515392     80.82    638744    642036       260
09:31:58       361748   1162988    482584     25.74     53100    870784   1524960     81.33    669968    642096         8
09:32:03       346372   1147676    497132     26.51     53100    871052   1518976     81.01    679632    642160        72
09:32:08       330992   1132364    511720     27.29     53108    871748   1541228     82.20    702228    642228       188
09:32:13       308812   1110252    533228     28.44     53108    872096   1560980     83.25    732104    642296       256
09:32:18       286884   1088400    554176     29.56     53108    872464   1563492     83.39    753916    642364       320
09:32:23       227912   1029504    612068     32.64     53108    872976   1596260     85.13    795928    642436       380
09:32:28       235812   1037444    603640     32.19     53108    873292   1566324     83.54    771288    642484        64
09:32:33       654600   1456040    197652     10.54     53132    861444    935128     49.87    394296    642508        52
```

With 20000 URLs memory goes up to 42%:

```
ubuntu@ip-10-0-0-188:~/test$ sar -r 5
Linux 6.8.0-1016-aws (ip-10-0-0-188) 	10/15/24 	_aarch64_	(1 CPU)

09:32:46    kbmemfree   kbavail kbmemused  %memused kbbuffers  kbcached  kbcommit   %commit  kbactive   kbinact   kbdirty
09:32:51       654600   1456040    197656     10.54     53132    861444    935128     49.87    394312    642508         8
09:32:56       577540   1378252    268588     14.32     53256    866860   1340604     71.50    468784    641600       496
09:33:01       532196   1332964    313176     16.70     53256    867528   1429108     76.22    513160    641644       540
09:33:06       512048   1312884    332176     17.72     53256    868580   1437664     76.67    515368    641712       600
09:33:11       495764   1296700    348288     18.58     53256    868684   1441944     76.90    522268    641800       688
09:33:16       493504   1294504    350196     18.68     53256    868968   1463404     78.05    531204    641864       284
09:33:21       479648   1280716    363728     19.40     53256    869260   1477756     78.81    558012    641924       336
09:33:26       449800   1250960    392412     20.93     53260    869728   1467732     78.28    569532    642016       320
09:33:31       366896   1168160    474472     25.30     53260    870036   1494992     79.73    615640    642120       424
09:33:36       366616   1167944    473832     25.27     53260    870444   1496352     79.80    641428    642184       484
09:33:41       374888   1176288    464748     24.79     53260    870924   1503644     80.19    667376    642256       556
09:33:46       364048   1165532    474532     25.31     53260    871128   1582868     84.42    676380    642320       416
09:33:51       344196   1145772    493704     26.33     53284    871520   1571872     83.83    699272    642412       632
09:33:56       291556   1093196    545704     29.10     53284    871872   1614368     86.10    752324    642476       468
09:34:01       284500   1086196    552052     29.44     53284    872424   1601300     85.40    753128    642532       524
09:34:06       232572   1034340    603408     32.18     53284    872940   1627736     86.81    795448    642604       584
09:34:11       222244   1024088    613420     32.72     53284    873256   1604712     85.58    788912    642676       656
09:34:16       212164   1014076    623352     33.25     53284    873388   1640584     87.50    817988    642744       324
09:34:21       195560    997584    639344     34.10     53292    873952   1663188     88.70    841752    642848       140
09:34:26       166072    968168    668416     35.65     53292    874368   1660640     88.57    853444    642916       208
09:34:31       136588    938748    697452     37.20     53292    874736   1695988     90.45    874216    642980       268
09:34:36       127320    929560    706332     37.67     53292    874936   1735568     92.56    909404    643060       348
09:34:41        96828    899136    736216     39.26     53292    875232   1757768     93.75    938288    643120       388
09:34:46        72740    875112    759696     40.52     53292    875468   1792528     95.60    961540    643184        56
09:34:51        76020    871240    763052     40.70     53296    868652   1798296     95.91    967904    635516        96
09:34:56        70292    843524    790308     42.15     51352    849116   1820608     97.10   1003896    594672       136
09:35:01        78168    851472    781768     41.69     51352    849420   1832480     97.73    995084    594744       388
09:35:06        77944    851312    781684     41.69     51352    849628   1851528     98.75    997292    594808       448
09:35:11        71896    845324    787540     42.00     51352    849804   1870164     99.74   1017532    594868       508
09:35:16        70068    839680    793212     42.30     51352    846028   1851860     98.76   1001644    591096       576
09:35:21        70032    823176    809824     43.19     51196    829852   1888644    100.73   1035544    573520       128
09:35:26        91236    844432    788532     42.05     51196    829900   1858268     99.11   1000440    573564       140
09:35:31        78384    831604    801384     42.74     51196    829940   1882996    100.43   1023724    573596       168
09:35:36       679040   1432068    216496     11.55     51220    815304    998056     53.23    416320    573620       116
```

**Comment by rzikm** [comment] 2024-10-16 08:23
Did a quick test and with following
- `PooledConnectionLifetime = TimeSpan.Zero`
- `PooledConnectionIdleTimeout = TimeSpan.Zero`
- `HttpClient.DefaultRequestHeaders.ConnectionClose = true;`
- `DOTNET_SYSTEM_NET_SECURITY_TLSCACHESIZE=100`

And the memory seems stable now.

We might consider changing the default size of the SslSession cache, but since this is usually hit only by crawlers which are rather niche and a workaround exists, I don't think it's worth it (and we could negatively affect other users).

**Comment by jordinl** [comment] 2024-10-16 14:21
@rzikm Tried it with 20K URLs and CONCURRENCY=100 and memory stayed around 20% all the time, so it seems to work.

I'll check tomorrow if all of these actually need to be set, at the very least only one of `PooledConnectionLifetime` or `PooledConnectionIdleTimeout` needs to be set to zero.

**Comment by jordinl** [comment] 2024-10-17 07:08
I tried again and it seems it's only necessary to use two of these options:
* Set env var `DOTNET_SYSTEM_NET_SECURITY_TLSCACHESIZE=100`
* And one of:
  * `PooledConnectionLifetime = TimeSpan.Zero`
  * `PooledConnectionIdleTimeout = TimeSpan.Zero`
  * `HttpClient.DefaultRequestHeaders.ConnectionClose = true`

**Comment by ManickaP** [comment] 2024-10-17 12:37
I read this that there's a setting that works well for your scenario. Also Radek confirmed that this is not a memory leak, but an inherent behavior of SSL session cache. So I'll close this issue as answered. Feel free to re-open or file a new issue if you encounter more problems.

**Closed by ManickaP** 2024-10-17 12:37 UTC
Labels: area-System.Net.Http, untriaged

**Comment by CoenraadS** [comment] 2024-11-05 22:42
We encountered the same issue, our software would gradually gain memory and crash. Setting `DOTNET_SYSTEM_NET_SECURITY_TLSCACHESIZE=100` fixed it, after weeks of trying to track down the cause. We are polling the same endpoint once a second on arm32 hardware (512MB RAM)

@ManickaP I think there is room for improvement here, if it wasn't for this github issue I would never have found the solution.

**Comment by ManickaP** [comment] 2024-11-06 09:16
> We are polling the same endpoint

Interesting, @rzikm is the cache supposed to grow even when connecting to the same peer?

**Comment by rzikm** [comment] 2024-11-06 12:44
> Interesting, [@rzikm](https://github.com/rzikm) is the cache supposed to grow even when connecting to the same peer?

It isn't. There used to be a bug, bug we fixed it and backported it to .NET 8.0 in https://github.com/dotnet/runtime/pull/102095

@CoenraadS This sounds like a bug. Is the target server public so that I can attempt to reproduce this? Do you know what TLS version is used?

Ideally, file a new github issue so that we can track this.

**Comment by CoenraadS** [comment] 2024-11-06 21:45
@rzikm I will discuss with my boss is we can put the target device online. I will make a new issue if that is possible. Thanks

**Comment by rzikm** [comment] 2024-11-06 21:59
Alternatively, I can try to reproduce it with other server, but it would be good to have a known reproducible example or get enough information so that I can try to replicate it.

**Comment by CoenraadS** [comment] 2024-11-06 23:18
I will try to see if I can reproduce it against a public website and provide sample code (in a new issue). However I will be on vacation next week so response may be delayed.

**Comment by CoenraadS** [comment] 2024-11-07 01:26
@rzikm 
I uploaded a pcap to https://github.com/dotnet/runtime/issues/109600
