### ISSUE TITLE
Infrastructure - Status/Health

### ISSUE THREAD

**Issue by jashook** [dotnet/runtime#702] opened 2019-10-16 17:36 UTC
Could not find definition

**Comment by sandreenko** [comment] 2019-12-09 19:29
@jashook does this issue need a new owner while you are on vacation?

**Comment by jashook** [comment] 2019-12-11 12:34
I assume the ownership is now shared. 

/cc @trylek @ViktorHofer @jkoritzinsky @dagood @jaredpar

**Comment by jkotas** [comment] 2019-12-17 03:08
Libraries Build Windows_NT x86 Release leg is failing 100% of time. See https://github.com/dotnet/runtime/pull/967

**Comment by trylek** [comment] 2019-12-17 09:07
Interesting. To me it looks like a code issue rather than an infra hiccup though:

<pre>
Fatal error. 0xC0000005
   at DynamicClass.WriteTypeWithDateTimeOffsetTypePropertyToJson(System.Runtime.Serialization.XmlWriterDelegator, System.Object, System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson, System.Runtime.Serialization.ClassDataContract, System.Xml.XmlDictionaryString[])
   at System.Runtime.Serialization.Json.JsonClassDataContract.WriteJsonValueCore(System.Runtime.Serialization.XmlWriterDelegator, System.Object, System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson, System.RuntimeTypeHandle)
   at System.Runtime.Serialization.Json.JsonDataContract.WriteJsonValue(System.Runtime.Serialization.XmlWriterDelegator, System.Object, System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson, System.RuntimeTypeHandle)
   at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.WriteJsonValue(System.Runtime.Serialization.Json.JsonDataContract, System.Runtime.Serialization.XmlWriterDelegator, System.Object, 
</pre>

Perhaps some traditional shenanigans regarding time zone settings on the test machines?

**Comment by ViktorHofer** [comment] 2019-12-17 11:04
cc @ahsonkhan @steveharter

**Comment by mikedn** [comment] 2019-12-17 12:10
That looks like it came from my #737, I'm pretty sure I know what the problem is. The odd thing is that the CI was green when the PR was merged and it's not very clear why.

**Comment by henrikse55** [comment] 2019-12-17 13:05
Looks like the same CI (Libraries Build Windows_NT x86 Release) failed in my PR #842  

https://helix.dot.net/api/2019-06-17/jobs/068da4f0-9282-4e18-a1de-c2baaecf32b0/workitems/System.Runtime.Serialization.Json.Tests/console

```
Fatal error. 0xC0000005
   at DynamicClass.WriteTypeWithDateTimeOffsetTypePropertyToJson(System.Runtime.Serialization.XmlWriterDelegator, System.Object, System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson, System.Runtime.Serialization.ClassDataContract, System.Xml.XmlDictionaryString[])
   at System.Runtime.Serialization.Json.JsonClassDataContract.WriteJsonValueCore(System.Runtime.Serialization.XmlWriterDelegator, System.Object, System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson, System.RuntimeTypeHandle)
   at System.Runtime.Serialization.Json.JsonDataContract.WriteJsonValue(System.Runtime.Serialization.XmlWriterDelegator, System.Object, System.Runtime.Serialization.Json.XmlObjectSerializerWriteContextComplexJson, System.RuntimeTypeHandle)
```

**Comment by safern** [comment] 2019-12-17 14:00
> That looks like it came from my #737, I'm pretty sure I know what the problem is. The odd thing is that the CI was green when the PR was merged and it's not very clear why.

The reason why your PR was green is because of the current state we’re in. 

1. In order to achieve building live live, we needed to disable running the libraries tests on coreclr PRs. 
2. The only pipeline that runs libraries tests is runtime-libraries which is conditioned to only run when the change includes a change to src/libraries/*. Since your change only touched coreclr, it didn’t run in your PR.

I’m working on fixing this and moving to a single pipeline that always run and libraries tests should run always when coreclr or libraries are touched.

**Comment by dagood** [comment] 2019-12-20 16:49
Added https://github.com/dotnet/runtime/issues/1089 to tracking, "When PR validation spans a UTC day, the Installer build may fail due to a package version mismatch".

**Comment by jkotas** [comment] 2019-12-22 13:31
CoreCLR Test Run Windows_NT arm legs are failing 100% for all PRs currently.

**Comment by jkotas** [comment] 2020-01-15 04:59
#129 Non-deterministic failure hit by CoreCLR tests: Assert failure(PID 2664 [0x00000a68], Thread: 3612 [0x0e1c]): pMethodDesc->GetCallCounter()->IsCallCountingEnabled(pMethodDesc)

**Comment by safern** [comment] 2020-01-16 21:29
Updated issue for failure in CoreCLR Pri0 Test Run Windows_NT x64 checked tests timing out: 
```
cmdLine:C:\h\w\A995095C\w\B9DA09DC\e\tracing\eventpipe\providervalidation\providervalidation\providervalidation.cmd Timed Out
      Test Harness Exitcode is : -100
      To run the test:
      > set CORE_ROOT=C:\h\w\A995095C\p
      > C:\h\w\A995095C\w\B9DA09DC\e\tracing\eventpipe\providervalidation\providervalidation\providervalidation.cmd
      Expected: True
      Actual:   False
```

cc: @josalem is working on fixing it.

**Comment by jkotas** [comment] 2020-01-26 18:19
https://github.com/dotnet/runtime/issues/2209: Unable to pull image mcr.microsoft.com/...

**Comment by jkotas** [comment] 2020-01-29 16:55
A lot of PRs are failing with:
```
Unhandled exception. System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (0x80131040 (FUSION_E_REF_DEF_MISMATCH))\nFile name: 'System.Runtime.CompilerServices.Unsafe, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

https://github.com/dotnet/runtime/pull/2344 is reverting the change that introduced the problem.

**Comment by safern** [comment] 2020-01-30 01:29
I just saw an issue related to helix in one of my PRs:

https://github.com/dotnet/core-eng/issues/8694

Adding to the description.

**Comment by jkotas** [comment] 2020-02-04 08:01
It is not convenient to keep updating this issue with all intermittent test failures hit by the CI. I have started marking issues that are intermittently causing CI failures with blocking-clean-ci label, This label did exist in the repo, but it was not used for a while - time to start using it again.

Query: https://github.com/dotnet/runtime/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Ablocking-clean-ci+

**Comment by jaredpar** [comment] 2020-02-04 16:22
> It is not convenient to keep updating this issue with all intermittent test failures hit by the CI

Agree. Going forward I would prefer this be more of a status page for the repository. A place to visit to quickly check if you're running into a known issue and link to a place to find more information. 

> I have started marking issues that are intermittently causing CI failures with blocking-clean-ci label, This label did exist in the repo, but it was not used for a while - time to start using it again.

+1

**Comment by dagood** [comment] 2020-02-04 23:16
A few above unpinnings were accidents (unclear what the unpin button means, or accidental clicks), so unless someone mentions a change in POR here, I'm repinning this whenever I notice it goes down because it's hard to find otherwise.

**Comment by sandreenko** [comment] 2020-02-25 23:08
Link #32835

**Comment by danmosemsft** [comment] 2020-06-23 16:56
Unpinning for a bit

**Comment by jaredpar** [comment] 2020-06-23 16:58
@danmosemsft why? This is pinned so that devs can find active infra issues easily.

**Comment by danmosemsft** [comment] 2020-06-23 17:06
Because we can only pin 3 issues and I added a new one. Which do you want to drop? :)

**Comment by jkotas** [comment] 2020-06-23 17:20
FWIW, I find the permanently pinned issues distracting. I am actively forcing myself to avoid clicking on the "x" button because it would unpin the issue for everybody. I have done it several times by accident. Muscle memory: you see "x" next to a thing that you do not want to see anymore, so you automatically click it to make it go away. I wish github allowed me to hide the pinned issues that I have seen hundred times already.

**Comment by danmosemsft** [comment] 2020-06-23 17:36
I hear you - I don't know we have any better way to communicate with the community. Unless we add something to the top of the readme, which may not be noticed.

**Comment by jkotas** [comment] 2020-06-23 18:30
I am wondering who is the target audience for the pinned issues. The pinned issues communicate the following currently:

- We have 12 overarching themes that we are working on in .NET 5. Should this rather be mentioned next to the roadmap link in the readme?
- We have 30 different sources of CI and official build flakiness
- We are using 5.0 as the milestone for .NET 5.0 issues
- We are going to rename the test directory in two weeks

Are these the most important things you want everybody in the community to know?

**Comment by danmosemsft** [comment] 2020-06-23 19:33
😁 
Maybe the stickies should only be for announcements (sticks around for a week or two only) and anything else should be linked from the readme. My guess is that nobody reads the readme after they've read it once, of course.

**Comment by ViktorHofer** [comment] 2020-09-26 07:38
@jaredpar I don't think we have updated this issue for quite some time. Do we have some better to track now? Should we close this?

**Comment by jaredpar** [comment] 2020-09-28 13:32
The issue itself gets updated about every 15 minutes. The reason it appears static is that we're not following up on the individual issues here: closing for instance when the issues are resolved. My first instinct would be to focus on that.

**Comment by ViktorHofer** [comment] 2020-09-28 13:36
Great to hear that the issue is still updated. Should we pin it again after closing stale issues?

**Comment by jaredpar** [comment] 2020-09-28 14:46
Think so.

**Comment by JulieLeeMSFT** [comment] 2023-01-26 04:07
Can we add a column for Issue number? It will be easier to search.

**Comment by akoeplinger** [comment] 2023-12-14 14:27
This is no longer used, closing.

**Closed by akoeplinger** 2023-12-14 14:27 UTC
Labels: area-Infrastructure
