### ISSUE TITLE
.NET 5.0 System.Text.Json Serialize/Deserialize throw exception

### ISSUE THREAD

**Issue by jacksonwj** [dotnet/runtime#45221] opened 2020-11-25 18:39 UTC
Here is class and extend function

```
// class
public class Res
{
    public int Code { get; set; }
    public string Msg { get; set; }

    public Res(int code = 200, string msg = "Success")
    {
        Code = code;
        Msg = msg;
    }
}

public class Res<T> : Res
{
    public T Body { get; set; }

    public Res(T body = default, int code = 200, string msg = "Success")
        : base(code, msg)
    {
        Body = body;
    }
}
```

```
// Extend function ToJson()
public static class Ext
{
    private static readonly JsonSerializerOptions _opts;

    static Ext()
    {
        _opts = new JsonSerializerOptions
        {
            // ... default configuration
        };
    }

    // Serialize to JSON string from entity
    public static string ToJson(this object data, JsonSerializerOptions options = null)
    {
        if (data == null)
        {
            return string.Empty;
        }

        return JsonSerializer.Serialize(data, options ?? _opts);   // throw exception when data has Value Type body
    }

    // Deserialize to entity from JSON string
    public Static T ToJson<T>(this string json, JsonSerializerOptions options = null)
    {
        if (string.IsNullOrWhiteSpace(json))
        {
            return default;
        }

        return JsonSerializer.Deserialize<T>(json, options ?? _opts);   // throw exception when data has Value Type body
    }
}
```

When I serialize an entity to JSON string by `System.Text.Json.JsonSerializer (.NET 5.0)`, it throw an exception.
Deserialize also has the same exception.

```
var res0 = new Res();
var res0Json = res0.ToJson();   // Success (Correct JSON string)

var res1 = new Res<string>("a");   // body is Reference Type
var res1Json = res1.ToJson();   // Success (Correct JSON string)

var res2 = new Res<int>(1);   // body is Value Type
var res2Json = res2.ToJson();   // Fail (Throw an exception: Object reference not set to an instance of an object.)
```

**It seems that: Value Type CANNOT Serialize/Deserialize, but Reference Type CAN**

How do I resolve the exception?

Thanks

**Comment by huoyaoyuan** [comment] 2020-11-26 03:00
It should be an internal bug. `NullReferenceException` should never be thrown in library code. Arguments verification failure should throw other exceptions.

**Comment by jacksonwj** [comment] 2020-11-26 06:07
> It should be an internal bug. `NullReferenceException` should never be thrown in library code. Arguments verification failure should throw other exceptions.

The code **CAN RUN without exception** in .NET Core 3.1 or before.

**Comment by benaadams** [comment] 2020-11-29 03:13
Duplicate of https://github.com/dotnet/runtime/issues/43757

Workarounds https://github.com/dotnet/runtime/issues/43757#issuecomment-719714319

Fix https://github.com/dotnet/runtime/pull/43831

**Comment by layomia** [comment] 2020-12-01 03:11
Closing as dup of https://github.com/dotnet/runtime/issues/43757. I'll propose porting the fix (https://github.com/dotnet/runtime/pull/43831) to a servicing release for .NET 5.0.

**Closed by layomia** 2020-12-01 03:11 UTC
Labels: area-System.Text.Json, untriaged
