### ISSUE TITLE
Rolling build test failure:  JIT.HardwareIntrinsics.X86.Avx1

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/runtime#67655] opened 2022-04-06 16:49 UTC
- Rolling build results: https://dev.azure.com/dnceng/public/_build/results?buildId=1700961&view=results
- Pipeline: `CoreCLR Pri0 Runtime Tests Run windows arm64 checked`
- Job: https://dev.azure.com/dnceng/public/public%20Team/_build/results?buildId=1700961&view=logs&j=bb94f37e-a09b-5b51-09b2-ab78e7aa5103&t=506cadc9-3cc4-5d96-6847-011f75a33382&l=186
- Log (not very helpful): https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-heads-main-d88db0e579f84abba9/JIT.HardwareIntrinsics.X86.Avx1/1/console.2f3a79fa.log?sv=2019-07-07&se=2022-04-25T21%3A34%3A31Z&sr=c&sp=rl&sig=XoECTxfQmIhanVqL%2BwhOJfemW%2BRs1ohsfIE1W60c8GA%3D

Message:
```
Console log: 'JIT.HardwareIntrinsics.X86.Avx1' from job d88db0e5-79f8-4abb-a9f7-33fe2e5cdddf workitem 3d0e323b-ca51-4649-b013-60e98088f750 (windows.10.arm64v8.open) executed on machine DDARM64-077
```

@dotnet/area-system-runtime-intrinsics  please triage and disable the test if necessary, or submit a fix asap.

**Comment by tannergooding** [comment] 2022-04-06 17:15
Dupe of https://github.com/dotnet/runtime/issues/67233

**Comment by tannergooding** [comment] 2022-04-06 17:16
Noting the tests in question are supposed to be excluded on Arm64: https://github.com/dotnet/runtime/blob/main/src/tests/issues.targets#L249-L252

**Closed by tannergooding** 2022-04-06 17:15 UTC
Labels: area-System.Runtime.Intrinsics, blocking-clean-ci, untriaged

**Comment by carlossanlop** [comment] 2022-04-06 17:17
Thanks Tanner. I am also mentioning this issue here: https://github.com/dotnet/core-eng/issues/15847

**Comment by trylek** [comment] 2022-04-06 20:33
I think I finally have the answer to Tanner's comment that the test actually shouldn't run: the problem is basically tied to the way the legacy XUnit wrappers are constructed and executed in Helix and will be fixed after switching over to using merged wrappers that Jeremy and I are working on. What basically happens is that a "larger" XUnit wrapper gets generated that covers the entire JIT/HardwareIntrinsics subtree. In the XUnit wrapper, the X86 test cases are indeed filtered out for the arm64 run, however src/tests/Common/testgrouping.proj partitions these wrappers into smaller execution subsets for Helix; one of these subsets is JIT.HardwareIntrinsics.X86.Avx1 (the subsets are hard-coded in the file as a way of empirically balancing the duration and disk size of the individual groups, IIRC Egor Chesakov was the last person to work on this) and so it gets sent to Helix even though the XUnit wrapper filtering would have ended up with zero test cases to execute; however we haven't gotten to that as the ARM64 machine somehow malfunctioned (the known infra problem). In other words it's a slight inefficiency but not a real bug which is a relief, I was worried that we unsettled parts of this logic in our preparatory changes for the merged wrapper support. In AzDO UI you can see that there only is a "work item" failure but no detailed "test case" failures.
