### ISSUE TITLE
Multiplication with 8 not optimized to left-shift?

### ISSUE THREAD

**Issue by znakeeye** [dotnet/runtime#106239] opened 2024-08-11 21:02 UTC
**Version Used**: 
`.NET 8.0.724.31311` on `x64`

**Steps to Reproduce**:
Compile the code below and check `JIT Asm`. Or head over to [sharplab.io](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABAZgAJiAmcgYXIG8BYAKHPfIAcoBLAN2wYY5SADtcGcj1GSAstgQBlHgC9hAXnIAOANysO5fR279BwiMABWMMBgDaAXXICANgFcYucptEwA7uQW1rZ28kqqwgBU5GHKag56LEbsZJQo5IowGAAU0pJQEH5oUjIiEO74osVBNpIQAJTJjE0Grh64dgUB0bER5ADUZRWiTpoQiQYAvqyTQA).

Multiplying with `2`, `4` and `8` does not produce a left-shift whereas larger values will. E.g. `16` seems to produce a left-shift. I understand multiplication and left shifting have different overflow behavior, but coming from the native world I kind of expect multiplication with 8 to get replaced by an `shl` instruction. When playing around with the code above, it seems the multiplication with 8 is **not** replaced with left-shift 3. **Why?**

```c#
public class C {
    private const int MaxSize = 8;
    
    private object[] values = new object[MaxSize * MaxSize];

    public void Set(int row, int column, object o)
    {
        values[row * MaxSize + column] = o;
    }
}
```
For `MaxSize = 8` we get a multiplication?
```il
C.Set(Int32, Int32, System.Object)
    L0000: sub rsp, 0x28
    L0004: lea edx, [r8+rdx*8]     // Multiplication? Or JIT Asm syntax iffiness?
```
For `MaxSize = 16` we do get a left-shift!
```il
C.Set(Int32, Int32, System.Object)
    L0000: sub rsp, 0x28
    L0004: shl edx, 4              // Ah, there you are!
    L0007: add edx, r8d
```

**Comment by CyrusNajmabadi** [comment] 2024-08-11 21:18
Moving to dotnet/runtime.  Roslyn is not responsible for asm emit.

**Comment by tannergooding** [comment] 2024-08-11 22:09
This is simply using the built-in `SIB` (scale-index-base) addressing functionality that is native to xarch and is by design.

The disassembly shows `* 2`, `* 4`, and `* 8` in the LEA but it doesn't actually multiply at the hardware level.

**Closed by tannergooding** 2024-08-11 22:09 UTC
Labels: area-CodeGen-coreclr, untriaged

**Comment by huoyaoyuan** [comment] 2024-08-12 03:18
It's just a disassembly flavor of the complex addressing mode. It's actually `<<` instead of `*` and you will only see 1(omitted), 2, 4, 8 in the scaling factor.
