### ISSUE TITLE
Test failure System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException

### ISSUE THREAD

**Issue by VincentBu** [dotnet/runtime#54260] opened 2021-06-16 01:51 UTC
Run: [runtime-libraries-coreclr outerloop 20210615.3](https://dev.azure.com/dnceng/public/_build/results?buildId=1187626&view=ms.vss-test-web.build-test-results-tab&runId=35678872&resultId=104107&paneView=debug)

Failed test:
```
net6.0-windows-Release-x86-CoreCLR_release-Windows.7.Amd64.Open

- System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException

```
**Error message:**
```
Assert.Throws() Failure
Expected: typeof(System.InvalidOperationException)
Actual:   (No exception was thrown)


Stack trace
   at System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceControllerTests.netcoreapp.cs:line 16
```

**Comment by VincentBu** [comment] 2021-06-28 06:41
Failed again in [runtime-libraries-coreclr outerloop 20210627.4](https://dev.azure.com/dnceng/public/_build/results?buildId=1208254&view=ms.vss-test-web.build-test-results-tab&runId=36130646&resultId=103584&paneView=debug)

Failed test:
```
net6.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.ServerRS5.Open

- System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException

```
**Error message:**
```
Assert.Throws() Failure
Expected: typeof(System.InvalidOperationException)
Actual:   (No exception was thrown)


Stack trace
   at System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceControllerTests.netcoreapp.cs:line 16
```

**Comment by adamsitnik** [comment] 2021-07-01 10:50
@Anipik @ViktorHofer could you please take a look at these failures? Recently I've seen them for every outerloop run.

Related issue: #54955

**Comment by VincentBu** [comment] 2021-07-06 02:18
Failed again in [runtime-libraries-coreclr outerloop 20210705.5](https://dev.azure.com/dnceng/public/_build/results?buildId=1220600&view=ms.vss-test-web.build-test-results-tab&runId=36381272&resultId=104101&paneView=debug)

Failed test:
```
net6.0-windows-Release-x64-CoreCLR_release-Windows.81.Amd64.Open

- System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException

```
**Error message:**
```
Assert.Throws() Failure
Expected: typeof(System.InvalidOperationException)
Actual:   (No exception was thrown)


Stack trace
   at System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceControllerTests.netcoreapp.cs:line 16
```

**Comment by VincentBu** [comment] 2021-07-13 03:17
Failed again in [runtime-libraries-coreclr outerloop 20210712.5](https://dev.azure.com/dnceng/public/_build/results?buildId=1232439&view=ms.vss-test-web.build-test-results-tab&runId=36693224&resultId=104296&paneView=debug)

Failed test:
```
net6.0-windows-Release-x64-CoreCLR_release-Windows.81.Amd64.Open

- System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException

net6.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.ServerRS5.Open

- System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException
net6.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.Server19H1.Open

- System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException

net6.0-windows-Release-x86-CoreCLR_release-Windows.7.Amd64.Open

- System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException

```
**Error message:**
```
Assert.Throws() Failure
Expected: typeof(System.InvalidOperationException)
Actual:   (No exception was thrown)


Stack trace
   at System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceControllerTests.netcoreapp.cs:line 16
```

**Comment by AriNuer** [comment] 2021-07-21 01:38
Failed again in [runtime-libraries-coreclr outerloop 20210720.6](https://dev.azure.com/dnceng/public/_build/results?buildId=1248051&view=ms.vss-test-web.build-test-results-tab&runId=37073226&resultId=101876&paneView=debug)

Failed test:
```
net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c
- System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException

net6.0-windows-Release-x64-CoreCLR_release-Windows.81.Amd64.Open
- System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException

net6.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.ServerRS5.Open
- System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException

net6.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.Server19H1.Open
- System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException

net6.0-windows-Release-x64-CoreCLR_release-(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-08e8e40-20200107182504
- System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException

net6.0-windows-Release-x86-CoreCLR_release-Windows.7.Amd64.Open
- System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException

net6.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.ServerRS5.Open
- System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException

net6.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.Server19H1.Open
- System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException

```
**Error message:**
```
Assert.Throws() Failure
Expected: typeof(System.InvalidOperationException)
Actual:   (No exception was thrown)


Stack trace
   at System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceControllerTests.netcoreapp.cs:line 16
```

**Comment by VincentBu** [comment] 2021-07-29 02:58
Failed again in [runtime-libraries-coreclr outerloop 20210728.5](https://dev.azure.com/dnceng/public/_build/results?buildId=1263342&view=ms.vss-test-web.build-test-results-tab&runId=37427364&paneView=debug&resultId=104315)

Failed test:
```
net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c
- System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException

net6.0-windows-Release-x64-CoreCLR_release-Windows.81.Amd64.Open
- System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException

net6.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.ServerRS5.Open
- System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException

net6.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.Server19H1.Open
- System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException

net6.0-windows-Release-x64-CoreCLR_release-(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-08e8e40-20200107182504
- System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException

net6.0-windows-Release-x86-CoreCLR_release-Windows.7.Amd64.Open
- System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException

net6.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.Server19H1.Open
- System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException

net6.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.ServerRS5.Open
- System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException

```
**Error messages:**
```
Assert.Throws() Failure
Expected: typeof(System.InvalidOperationException)
Actual:   (No exception was thrown)


Stack trace
   at System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceControllerTests.netcoreapp.cs:line 16
```

**Comment by VincentBu** [comment] 2021-08-06 01:53
Failed again in [runtime-libraries-coreclr outerloop 20210805.1](https://dev.azure.com/dnceng/public/_build/results?buildId=1277814&view=ms.vss-test-web.build-test-results-tab&runId=37785796&resultId=104156&paneView=debug)

Failed test:
```
net6.0-windows-Release-x64-CoreCLR_release-Windows.81.Amd64.Open
- System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException

net6.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.ServerRS5.Open
- System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException

net6.0-windows-Release-x64-CoreCLR_release-Windows.10.Amd64.Server19H1.Open
- System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException

net6.0-windows-Release-x64-CoreCLR_release-(Windows.Server.Core.1909.Amd64.Open)windows.10.amd64.server20h1.open@mcr.microsoft.com/dotnet-buildtools/prereqs:windowsservercore-2004-helix-amd64-20200904200251-272704c
- System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException

net6.0-windows-Release-x64-CoreCLR_release-(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-08e8e40-20200107182504
- System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException

net6.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.Server19H1.Open
- System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException

net6.0-windows-Release-x86-CoreCLR_release-Windows.7.Amd64.Open
- System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException

net6.0-windows-Release-x86-CoreCLR_release-Windows.10.Amd64.ServerRS5.Open
- System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException

```
**Error message:**
```
Assert.Throws() Failure
Expected: typeof(System.InvalidOperationException)
Actual:   (No exception was thrown)


Stack trace
   at System.ServiceProcess.Tests.ServiceControllerTests.Stop_FalseArg_WithDependentServices_ThrowsInvalidOperationException() in /_/src/libraries/System.ServiceProcess.ServiceController/tests/ServiceControllerTests.netcoreapp.cs:line 16
```

**Comment by danmoseley** [comment] 2021-08-10 05:07
Dupe of #57115

**Closed by danmoseley** 2021-08-10 05:07 UTC
Labels: arch-x86, area-System.ServiceProcess, os-windows
