### ISSUE TITLE
MSB4018 "Multiple entries with the same BundleRelativePath" using -PublishSingleFile=true

### ISSUE THREAD

**Issue by erikma** [dotnet/runtime#48112] opened 2021-02-05 21:44 UTC
### Issue Description
When attempting to make use of the new .NET 5.0.2 'dotnet publish --self-contained true -p:PublishSingleFile=true' command on a Windows build for an app that was previously working without '-p:PublishSingleFile=true' an MSB4018 "System.ArgumentException: Invalid input specification: Found multiple entries with the same BundleRelativePath" error results, console exception text noted below.

The related csproj file is for a .NET 5.0.2 app with default exe AnyCPU:

    <OutputType>Exe</OutputType>

The package does make extensive use of ~100 packages.

C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1016,5): error MSB4018: The "GenerateBundle" task failed unexpectedly. C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1016,5): error MSB4018: System.ArgumentException: Invalid input specification: Found multiple entries with the same BundleRelativePath
C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1016,5): error MSB4018:    at Microsoft.NET.HostModel.Bundle.Bundler.GenerateBundle(IReadOnlyList`1 fileSpecs)

### Steps to Reproduce
No minimal repro at this time, this is a large existing project, MS-internal, contact me via internal email for repro or to debug.

### Expected Behavior
A self-contained single (or 3 based on blog posts) file application for Windows with no errors in compilation, publish, or execution.

### Versions & Configurations
- .NET 5.0.2 SDK.
- Windows Enterprise client OS
- msbuild -version: Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
16.8.3.61104

This problem reproduces outside of MSBuild when running the 'dotnet publish' command solo.

**Comment by vitek-karas** [comment] 2021-02-16 11:03
This is basically a dupe of https://github.com/dotnet/sdk/issues/10621, or https://github.com/dotnet/sdk/issues/3465. It's unclear if the problem is in host-model or SDK at this time.

**Comment by vitek-karas** [comment] 2021-02-18 13:49
https://github.com/dotnet/runtime/pull/48336 adds a better error message which will contain the conflicting file paths. It will take a couple of day to flow to dotnet/installer, but once there it should be possible to take a nightly build of .NET 6 SDK and build the app with it to get the info from it.

**Comment by erikma** [comment] 2021-03-24 23:08
@vitek-karas  Thanks, I verified I can get the new error output in net6-preview2. What's interesting is that the duplicate entries are the same package in this case:

MSB4018	System.ArgumentException: Invalid input specification: Found entries 'C:\Users\erikmav\.nuget\packages\buildxl.win-x64\0.1.0-20210323.5\x64\BuildXLNatives.dll', 'C:\Users\erikmav\.nuget\packages\buildxl.win-x64\0.1.0-20210323.5\x64\BuildXLNatives.dll' with the same BundleRelativePath 'X64\BuildXLNatives.dll' 

The grouping is only showing the first collision, but I wonder could this be from different casing? `var bundleRelativePathCollision = fileSpecs.GroupBy(file => file.BundleRelativePath)` should probably be grouping by an OS-specific path comparer (OrdinalIgnoreCase for Windows, Ordinal for other OSes).

**Comment by erikma** [comment] 2021-03-25 00:37
The new error message is better but at root the problem is actionability: Why does a duplicate bundle matter, what does it mean to the developer, what actions can be taken to mitigate? What settings should I be fixing, or what duplication of package inputs should I fix, such that I can get this resolved and get on with the next bug or issue on my plate? As a dev I'm just trying to reduce the size of my binaries in a complicated (but not excessively so) package-based repo with ~45 projects.

**Comment by vitek-karas** [comment] 2021-03-25 12:35
@erikma We're basically just trying to figure out when this happens. Internally we saw it basically once - and it was a badly authored nuget package causing it - so it didn't really warrant action as we thought it's going to be very rare (and indication of a real error).
That's obviously incorrect and it happens more often - but we still have no idea why. I added the better error message to get a better insight in what are the cases where this is problematic.

So far, almost all cases seem to be the exact same filepath duplicated on the input. As mentioned above, to get this properly fixed it would need to be done in the SDK itself, but I'm considering if the single-file bundler should be made resilient to exact duplicates on the input.

Note that I still don't know why this happens - where does the duplication come from. That's the main reason I'm hesitant to "hide" it - as it will just keep on being hidden until it shows up in another place breaking something else.

So if you can share a repro with us - that would be VERY helpful.
On the other hand I think we should make the bundler resilient to this - and maybe make it just a warning - or even an info message (I still don't want to completely hide - it doesn't feel right).

**Comment by vitek-karas** [comment] 2021-03-29 12:56
I created dotnet/sdk#16576 based on the repro to track the SDK wide issue.
As for single-file we're discussing making the bundler resilient to exact duplicates here: https://github.com/dotnet/sdk/issues/16311

**Comment by vitek-karas** [comment] 2021-04-02 14:06
https://github.com/dotnet/runtime/pull/50476 is now merged and should show up in the nightly builds on dotnet/installer in a couple of days. I verified that it fixes the problem seen by the repro provided to me by @erikma .

**Comment by blennster** [comment] 2021-07-02 13:47
Hi!

I see that this issue is still open and it appears that there are no minimal repro. I have found one that is kind of minimal or atleast could help isolate the issue.

Repro: [dotnetplay.zip](https://github.com/dotnet/runtime/files/6754947/dotnetplay.zip) (Only one `.cs` file and `BenchmarkDotNet` as package but not referenced in code)

Running the command
```
dotnet publish -r win10-x64 -c release -p:PublishSingleFile=true --self-contained=true
```

yields

```
Microsoft (R) Build Engine version 16.10.1+2fd48ab73 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored C:\Users\emilblennow\source\repos\dotnetplay\dotnetplay.csproj (in 513 ms).
  dotnetplay -> C:\Users\emilblennow\source\repos\dotnetplay\bin\release\net5.0\win10-x64\dotnetplay.dll
C:\Program Files\dotnet\sdk\5.0.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1017,5): error MSB4018: The "GenerateBundle" task failed unexpectedly. [C:\Users\emilblennow\source\repos\dotnetplay\dotnetplay.csproj]
C:\Program Files\dotnet\sdk\5.0.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1017,5): error MSB4018: System.ArgumentException: Invalid input specification: Found multiple entries with the same BundleRelativePath [C:\Users\emilblennow\source\repos\dotnetplay\dotnetplay.csproj]
C:\Program Files\dotnet\sdk\5.0.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1017,5): error MSB4018:    at Microsoft.NET.HostModel.Bundle.Bundler.GenerateBundle(IReadOnlyList`1 fileSpecs) [C:\Users\emilblennow\source\repos\dotnetplay\dotnetplay.csproj]
C:\Program Files\dotnet\sdk\5.0.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1017,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateBundle.ExecuteCore() [C:\Users\emilblennow\source\repos\dotnetplay\dotnetplay.csproj]
C:\Program Files\dotnet\sdk\5.0.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1017,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [C:\Users\emilblennow\source\repos\dotnetplay\dotnetplay.csproj]
C:\Program Files\dotnet\sdk\5.0.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1017,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\Users\emilblennow\source\repos\dotnetplay\dotnetplay.csproj]
C:\Program Files\dotnet\sdk\5.0.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(1017,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\Users\emilblennow\source\repos\dotnetplay\dotnetplay.csproj] 
```

Additional info:
```
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.301
 Commit:    ef17233f86

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.301\

Host (useful for support):
  Version: 5.0.7
  Commit:  556582d964

.NET SDKs installed:
  5.0.301 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Have a nice day!

**Comment by vitek-karas** [comment] 2021-07-08 19:15
Thanks for the simple repro.
I verified that it is fixed (for this repro) in .NET 6 Preview 5.

**Closed by vitek-karas** 2021-07-08 19:15 UTC
Labels: area-HostModel, untriaged
