### ISSUE TITLE
DateTime format render wrong format in Community Edition. Its work fine in Professional Edition

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#53580] opened 2021-06-02 08:45 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/DateTime-format-render-wrong-format-in-C/1407321)._

---
[severity:I'm unable to use this version] [regression] [worked-in:16.9.4]
Hello Microsoft Team,

Below is my code.

```
static void Main(string[] args)
        {
            DateTime dt = DateTime.Now;
            Console.WriteLine(dt. ToString("dd/MMM/yyyy HH:mm:ss"));
            Console.Read();
        }
```

When we execute in Visual Studio Community Edition (16.9.4) then its return **25-Apr-2021 21.35.02** instead of **25/Apr/2021 21:35:02**

Same code if we execute in Visual Studio Professional Version  (16.9.4) then its works fine. its always return **25/Apr/2021 21:35:02**. 

This particular this happens with all project types like .net5, Core 3.1,  .net standard framework, .net 4.5 ( console, web, Xamarin, WPF AND Desktop Application.

Can someone guide what is an issue?

---
#### Feedback Bot on 4/26/2021, 05:04 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### kapil.dave@globalsolgroup1.onmicrosoft.com on 5/5/2021, 03:27 PM: 

(private comment, text removed)
#### Marie Píchová on 6/2/2021, 10:45 AM: 

<p>Interestingly, I got <code>02.cvn.2021 10:34:15</code> in VS Code and command line (.NET 6 - 6.0.0-preview.1.21102.12). My regional settings is Czech and language is ENG US. I would expect the output to strictly follow the formatting if a custom one is provided. I’ll transfer the issue to runtime repo for further investigation.</p>

---
### Original Solutions
(no solutions)

**Comment by svick** [comment] 2021-06-02 10:24
What is your `CultureInfo.CurrentCulture` in the case when it works the way you expect and what is it when it doesn't work?

**Comment by stephentoub** [comment] 2021-06-02 12:28
>  I would expect the output to strictly follow the formatting if a custom one is provided

It does... but strictly following it means interpreting the symbols in the format according to their meaning, and as outlined at https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#:~:text=%20Custom%20date%20and%20time%20format%20strings%20,custom%20format%20specifier%20represents%20the%20most...%20More%20, colon and slash are used to represent the time and date separators associated with the culture being used.  As @svick alludes to,  the issue is almost certainly not a bug in DateTime but rather that the current culture is set differently in the different environments.

**Comment by tarekgh** [comment] 2021-06-09 15:40
The `/` in the date formatting pattern means the date separator and not means slash character. The date separator is picked up from current culture (i.e. user settings) If you need to force the slash character you need to do something like:

```C#
Console.WriteLine(dt. ToString("dd'/'MMM'/'yyyy HH':'mm':'ss"));
```

I am closing the issue but feel free to respond with any more questions.

**Comment by KapilDave** [comment] 2021-06-25 11:15
Have you checked what we are asking ?

static void Main(string[] args)
        {
            DateTime dt = DateTime.Now;
            Console.WriteLine(dt. ToString("dd/MMM/yyyy HH:mm:ss"));
            Console.Read();
        }


Execute above code in Visual Studio 2002, 2005, 2008, 2010, 2012, and reply what you are getting as output.

Then execute aboce code in 2019 Lastest Version (as on 25-Jun, 2021) lastest version is 16.10.2.

please compate both output and reply.

**Comment by tarekgh** [comment] 2021-06-25 17:09
@KapilDave 

I don't think the issue is related to VS at all. The behavior depends on the .NET versions you are using and the OS you are running on. Here is some summary that may help explaining more:

- If you are using the Full Framework, you'll get the Windows NLS behavior. (NLS is the Windows Win32 globalization APIs).
- If running with .NET Core (1.x, 2.x, 3.x)
    - if running on Windows OS, you will get the same behavior as the Full Framework (the NLS behavior).
    - if running on Linux/MacOs, we'll use `ICU` library for the globalization. You may notice some differences than NLS behavior.
- if using .NET (5.0 or 6.0 previews):
    - by default, we use `ICU` library. You may notice some differences than the NLS behavior.
    - you can switch the behavior back to use NLS. Consult the [doc](https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/globalization-icu#use-nls-instead-of-icu) for more info how to do that.

To easy diagnose your issue, please provide the following information with every run:
    - CultureInfo.CurrentCulture
    - The OS version `RuntimeInformation.OSDescription`
    - The framework version `RuntimeInformation.FrameworkDescription`

We understand you need to resolve the issue from your side. Don't worry, we'll help till you do that. Just reply with the information and questions and we'll be happy to help. Also, I hope you pay attention to my previous comment https://github.com/dotnet/runtime/issues/53580#issuecomment-857811608 just in case the formatting behavior is not clear to you.

**Closed** 2021-07-17 07:01 UTC
Labels: area-System.Runtime, needs author feedback, no recent activity
