### ISSUE TITLE
crossgen2 codegen for with AVX instructions differs from crossgen1 generated one

### ISSUE THREAD

**Issue by janvorli** [dotnet/runtime#32175] opened 2020-02-12 14:41 UTC
In both cases, the code was compiled with optimizations on.
One example of part of code of a method with such a difference is `System.Numerics.Matrix4x4 System.Numerics.Matrix4x4.CreateConstrainedBillboard(System.Numerics.Vector3, System.Numerics.Vector3, System.Numerics.Vector3, System.Numerics.Vector3, System.Numerics.Vector3)`:
Crossgen1:
```asm
    movaps xmm1, xmm0
    dpps xmm1, xmm0, 113
    movss xmm2, dword ptr [0x7ec50]
    ucomiss xmm2, xmm1
    jbe 0x007D
```
Crossgen2:
```asm
    movaps xmm2, xmm0
    mulps xmm2, xmm0
    movaps xmm1, xmm2
    shufps xmm1, xmm1, 129
    addps xmm2, xmm1
    shufps xmm1, xmm1, 15
    addps xmm2, xmm1
    movss xmm1, dword ptr [0x13cba0]
    ucomiss xmm1, xmm2
    jbe 0x008B
```
There are more differences in the body of the method, this is just a small example.

**Comment by janvorli** [comment] 2020-02-12 14:43
Here is a gist with full disass of the method for crossgen 1 and 2: https://gist.github.com/janvorli/e80da2329748dc15a23a445246c65028

**Comment by janvorli** [comment] 2020-02-12 14:43
cc: @davidwrighton

**Comment by davidwrighton** [comment] 2020-02-29 02:06
This is actually a bug in crossgen 1. It should be generating the longer sequence instead of the dpps instruction.

**Comment by davidwrighton** [comment] 2020-02-29 02:58
There is also a similar bug in crossgen 1 around use of the insertps instruction, and plausible future bugs around min, max and abs.

There are bugs in the crossgen2 compilation in that popcnt isn't generated directly. (In particular, the SSE41, SSE42 and POPCNT instructions aren't marked as eligible for the jit to generate for corelib). This both causes the `popcnt` bug in crossgen2, and causes the bugs noted here where we incorrectly generate `insertps` and `dpps` into the R2R for System.Private.CoreLib.

**Comment by benaadams** [comment] 2020-02-29 03:13
Also issue with `Vector128<byte>.Zero` which remains a call at crossgen https://github.com/dotnet/runtime/issues/32714

**Comment by damageboy** [comment] 2020-03-03 14:04
I'm also having crossgen related issues in a draft PR.
As a clear example:
https://github.com/damageboy/runtime/commit/8f3d72107c74a361f728a7a55315237ec657a31e#diff-54c667fe59347842036834f5b31c5411R340

```csharp
                    Console.WriteLine("Here");
                    if (Avx2.IsSupported)
                    {
                        Console.WriteLine("With AVX2");
                        if (typeof(T) == typeof(int))
```

Will not enter the branch under the Avx2.IsSupported condition until the R2R image is replaced by a freshly JIT'd version (30 calls + startup delay)

Is there a workaround to get this working on the first attempt you could recommend?
Or is this "correct-by-design" behavior?
I was under the impression, that combining Intrinsics (`AVX2` code) with crossgen would be properly supported by emitting a runtime check testing for `AVX2` support at the CPU level.

Given that I'm working on "CorLib" sorting code, it would be very weird for the first 30 sort operations to run at a 11x the time than the 31<sup>st</sup> attempt...

**Comment by MichalStrehovsky** [comment] 2020-03-03 14:53
> Or is this "correct-by-design" behavior?

This is by design right now (in CoreLib only). AVX2 support is a global switch in RyuJIT - it enables VEX encoding everywhere (including outside the IsSupported-guarded regions). We can't allow RyuJIT to use it because it would generate code that cannot run without VEX.

Outside CoreLib, using VEX2 instructions in the method body would disqualify the method from crossgenning completely. Within corelib, we still pregenerate the code, but with VEX disabled. This is because VEX intrinsics are used in code paths that are parts of the startup path and we don't want to JIT them every time we start.

ReadyToRun is a startup optimization, not a throughput optimization. Similar restrictions apply to other ReadyToRun code - the code is not ideal by design (e.g. it needs to be version resilient) - we need reJIT to achieve optimal throughput.

**Comment by davidwrighton** [comment] 2020-03-03 23:05
I'm working on adding an ability to specify to crossgen2 the minimal instruction set support, and hopefully that will allow the faster code to kick in more quickly for more scenarios, but the current model is that for CoreLib ONLY, Avx2.IsSupported will return false from the R2R code, and will change to true when it is re-tiered. (This requires your code to work in such a situation, we decided we could code review changes to CoreLib to make this safe.). For non-CoreLib, we simply disable generation of the code in crossgen entirely, and rely on the jit which has unfortunate startup time effects.)

**Closed** 2020-03-04 00:09 UTC
Labels: area-crossgen2-coreclr

**Comment by damageboy** [comment] 2020-03-05 12:44
> > Or is this "correct-by-design" behavior?
> 
> This is by design right now (in CoreLib only). AVX2 support is a global switch in RyuJIT - it enables VEX encoding everywhere (including outside the IsSupported-guarded regions). We can't allow RyuJIT to use it because it would generate code that cannot run without VEX.

Thanks I read up on the crazy state transitions in various Intel processors w.r.t to this issue and I now completely understand why you must disallow this when targeting SSE2.
