### ISSUE TITLE
[API Proposal]: Add CutAll method

### ISSUE THREAD

**Issue by Mr0N** [dotnet/runtime#78324] opened 2022-11-14 16:43 UTC
### Background and motivation

Add CutAll method.
https://github.com/dotnet/runtime/issues/77795
Add a similar method, only that it returns Enumerable values, that is, that it returns all the cut substrings from the string.

### API Proposal

```csharp
public static class MyClass
{
    public static IEnumerable<string> CutAll(this string text, string begin, string end)
    {
        int endIndex = 0;
        int beginIndex = 0;

        while (true)
        {
            beginIndex = text.IndexOf(begin, endIndex);
            if (beginIndex == -1) yield break;
            int beginIndexCut = beginIndex + begin.Length;
            endIndex = text.IndexOf(end, beginIndexCut);
            if (endIndex == -1) yield break;
            yield return text.Substring(beginIndexCut, endIndex - beginIndexCut);
            endIndex += end.Length;
        }
    }
}
```

### API Usage

```csharp
var result =
    "dsiooisdoisd<h1>4343 </h1> <h1>2 </h1>osdopsdopds".CutAll(
    "<h1>", "</h1>");
foreach (var item in result)
{
    Console.WriteLine(item);
}
Console.ReadKey();
```

**Comment by Mr0N** [comment] 2022-11-14 16:54
example use two class
```
using CustomRecordException;
var result =
    ("dsiooisdoisd<h1>43<a>39049043</a>43 </h1> " +
    "<h1>skdk<a>9023902930</a>jskj</h1>osdopsdopds")
    .CutAll("<h1>", "</h1>")
    .Select(a => a.Cut("<a>", "</a>"));
foreach (var item in result)
{
    Console.WriteLine(item);
}
Console.ReadKey();
public static class MyClass
{
    public static IEnumerable<string> CutAll(this string text, string begin, string end)
    {
        int endIndex = 0;
        int beginIndex = 0;

        while (true)
        {
            beginIndex = text.IndexOf(begin, endIndex);
            if (beginIndex == -1) yield break;
            int beginIndexCut = beginIndex + begin.Length;
            endIndex = text.IndexOf(end, beginIndexCut);
            if (endIndex == -1) yield break;
            yield return text.Substring(beginIndexCut, endIndex - beginIndexCut);
            endIndex += end.Length;
        }
    }
}
public static class Ext
{

    public static string Cut(this string text, string begin, string end, bool exception = false)
    {
        if (string.IsNullOrEmpty(text)
            && string.IsNullOrEmpty(begin) &&
            string.IsNullOrEmpty(end))
        {
            throw new NullReferenceException();
        }
        int beginIndex = text.IndexOf(begin);

        if (beginIndex == -1 && exception == true)
            throw new Exception();
        else if (beginIndex == -1 && exception == false)
            return null;

        int endIndex = text.IndexOf(end);

        if (endIndex == -1 && exception == true)
            throw new Exception();
        else if (endIndex == -1 && exception == false)
            return null;

        beginIndex = beginIndex + begin.Length;
        return text.Substring(beginIndex, endIndex - beginIndex);
    }
}
```

**Comment by viacheslav-boiko** [comment] 2022-11-14 17:39
Are you shitt*ng us? It's a joke or something that caused by one of the brain damage form? FYI: 
str.split(var1).Select(x =>x.substring(x.IndexOf(var2)))

**Comment by jaredpar** [comment] 2022-11-14 17:57
@viacheslav-boiko I've hidden your comment because it violates our [code of conduct](https://dotnetfoundation.org/about/policies/code-of-conduct). Please keep your comments respectful to others.

**Comment by teo-tsirpanis** [comment] 2022-11-14 20:46
Looks like far too specific for a LINQ method.

**Comment by Mr0N** [comment] 2022-11-14 21:03
> endIndex = text.IndexOf(end, beginIndexCut);

this method not for linq

**Comment by Barbedx** [comment] 2022-11-14 23:08
Hello dear mister @Mr0N . You can just use existing a very simple existing method like "Substring" for achieve this, for example   the next code give you literally the same result 



```
var str = "dsiooisdoisd<h1>43<a>39049043</a>43 </h1> " +
    "<h1>skdk<a>9023902930</a>jskj</h1>osdopsdopds";  

var res =  str.Split(var1)
    .Where(x => x.Contains(var2))
    .Select(x => x.Substring(0, x.IndexOf(var2))); 

```
IMHO it's ridiculous to add so specific code to runtime for one simple case.

**Comment by Clockwork-Muse** [comment] 2022-11-15 01:38
> the next code give you literally the same result

Not for nested token pairs, and it imposes a large performance penalty.

@Mr0N - Like I said in the issue about the single-case method, an example using HTML is concerning.  If you are intending to use such a method to parse real-world HTML, **it will fail** (notably, on any nested tokens, but perhaps more relevant is that HTML doesn't actually require closing tags), and you would be better off using a purpose-built HTML parser.  
If you have some other real-world usecase, please use that as an example instead.

**Comment by Mr0N** [comment] 2022-11-15 04:14
> Hello dear mister @Mr0N . You can just use a very simple existing method like "Substring" for achieve this, for example, the next code give you literally the same result
> 
> ```
> var str = "dsiooisdoisd<h1>43<a>39049043</a>43 </h1> " +
>     "<h1>skdk<a>9023902930</a>jskj</h1>osdopsdopds";  
> var var1 = "<h1>";
> var var2 = "</h1>";
> var res =  str.Split(var1)
>     .Where(x => x.Contains(var2))
>     .Select(x => x.Substring(0, x.IndexOf(var2))); 
> ```
> 
> IMHO it's ridiculous to add so specific code to runtime for one simple case.

No 

> 

Such methods can be used if it is necessary for the PC to consume the CPU, 10 times more than necessary, it is better to write the regex then!

**Comment by Mr0N** [comment] 2022-11-15 04:21
> 



> > the next code give you literally the same result
> 
> Not for nested token pairs, and it imposes a large performance penalty.
> 
> @Mr0N - Like I said in the issue about the single-case method, an example using HTML is concerning. If you are intending to use such a method to parse real-world HTML, **it will fail** (notably, on any nested tokens, but perhaps more relevant is that HTML doesn't actually require closing tags), and you would be better off using a purpose-built HTML parser. If you have some other real-world usecase, please use that as an example instead.

Well, first of all, the example from above cannot be parsed using Fizzle or Angle.Sharp, because the html is broken there, there are many other examples where you can use this method. The Substring method used here) this is its modified version.The Substring method is also used, and this is essentially it, only easier to use

**Comment by Mr0N** [comment] 2022-11-15 04:33
```
var result =
    "dsiooisdoisd|h1|4343 |h1| |h1|2 |h1|osdopsdopds".CutAll(
    "|h1|", "|h1|");
foreach (var item in result)
{
    Console.WriteLine(item);
}
Console.ReadKey();
```

**Comment by Mr0N** [comment] 2022-11-15 04:37
https://sharplab.io/#gist:2ca355142c5b58f79497d5ddbd9fc953

**Comment by Mr0N** [comment] 2022-11-15 10:38
Examlpe use:https://sharplab.io/#gist:0b8a8ba38b8fd88160b725941d00f6bb
```
/*
  SharpLab tools in Run mode:
    • value.Inspect()
    • Inspect.Heap(object)
    • Inspect.Stack(value)
    • Inspect.MemoryGraph(value1, value2, …)
*/
using System;
using System.Collections.Generic;

var result =
    "Hello, my name is Mr. Anderson, I earn $2000 a month, my wife earns $1230 a month.".CutAll(
    "$", " ");
foreach (var item in result)
{
    Console.WriteLine(item);
}

```

**Comment by eiriktsarpalis** [comment] 2022-11-22 13:57
I don't believe this method meets the bar for inclusion in the string type. It seems simple enough (and specific enough) to define as a helper method in your own code.

**Closed by eiriktsarpalis** 2022-11-22 13:57 UTC
Labels: api-suggestion, area-System.Linq, untriaged

**Comment by Mr0N** [comment] 2022-11-22 15:30
> I don't believe this method meets the bar for inclusion in the string type. It seems simple enough (and specific enough) to define as a helper method in your own code.

For a Microsoft engineer, it may be simple method) and for someone  complex, who knows.

**Comment by Mr0N** [comment] 2022-11-22 15:34
This is just an example of the method, I thought you would exclude 3-time search by line, and write your implementation, which is faster.
