### ISSUE TITLE
Shared framework is missing correct RID fallback chain for manjaro

### ISSUE THREAD

**Issue by badgerwild** [dotnet/runtime#62554] opened 2021-11-25 23:52 UTC
### Describe the bug
A embedded systems project that I am working on uses a C# program as a serial loader to send data to an Arduino Nano. I have installed dotnet and adding the `System.Io.Ports` package on the host machine. When trying to run the project, I get an error saying that `System.Io.Ports` is only available on windows.  This same code and installation process works on Ubuntu 18.04, the latest version of Arch Linux, and Mac without issue.

### Exceptions (if any)
```
Unhandled exception. System.PlatformNotSupportedException: System.IO.Ports is currently only supported on Windows.
   at System.IO.Ports.SerialPort..ctor()
   at SerialComPort.Main(String[] args) in /home/jason/collective/soen-422/SOEN422-PROJ/vm/task5/Lecture8_SerialLoader.cs:line 121
```

### Further technical details
Project is built and run through the CLI using the command `sudo dotnet run <file>` 
`dotnet --info` on the Manjaro system

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     manjaro
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  6.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

output of `dotnet list package `:
```
Project 'csloader' has the following package references
   [net6.0]: 
   Top-level Package      Requested   Resolved
   > System.IO.Ports      6.0.0       6.0.0   
```
Here is `dotnet --info` on the Arch and Ubuntu systems where the `System.Io.Serial` does work on this project: 
```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /snap/dotnet-sdk/147/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  6.0.100 [/snap/dotnet-sdk/147/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [/snap/dotnet-sdk/147/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [/snap/dotnet-sdk/147/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
  ```

```
❯ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  6.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
  ```

**Comment by ericstj** [comment] 2021-12-08 22:43
```
 RID:         arch-x64
```
This should load [net6.0-unix](https://github.com/dotnet/runtime/blob/cfb9e77032ad77f703ff8cc69bdc778daa184363/src/libraries/System.IO.Ports/src/System.IO.Ports.csproj#L7) implementation in the runtimes/unix/lib/net6.0 folder per https://github.com/dotnet/runtime/commit/00d8f8e378be27edeb37a4f5655ccd831f1cf891#diff-896c6652ae24cab2b91d7d5ab1696fced448d15514a344b7ea9d08552275d817R286

But instead is loading the platform-agnostic implementation (net6.0), which (BUG) should update its [resource string](https://github.com/dotnet/runtime/blob/57bfe474518ab5b7cfe6bf7424a79ce3af9d6657/src/libraries/System.IO.Ports/src/Resources/Strings.resx#L224-L226).  It could be caused by how your referencing the Ports (make sure to use the package) or loading it (make sure its listed in your project's deps file).

Can you run just the output of the project, with host tracing enabled?  That should indicate which RID the host is using and what assemblies it's considering when you load System.IO.Ports.dll.

**Comment by ericstj** [comment] 2021-12-09 23:28
Here's how you can capture a host trace: https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/default-probing#how-do-i-debug-the-probing-properties-construction

**Comment by PRIMETSS** [comment] 2021-12-14 01:22
Pretty sure that OS Exception is thrown here
[https://github.com/PRIMETSS/runtime/blob/release/6.0/src/libraries/System.IO.Ports/src/System/IO/Ports/SerialPort.Unix.cs#:~:text=%23endif,PlatformNotSupportedException(SR.PlatformNotSupported_SerialPort_GetPortNames)%3B](url)

I'd say it's not detecting Manjaro as a supported version of Linux?
[https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md](url)
Haven't found exactly where it checks for LinuxOSPlatform, but somewhere in `System.Runtime.InteropServices` 
[https://github.com/PRIMETSS/runtime/blob/1208ca1d9b18de80897cceb4a414b4175371108b/src/libraries/System.Private.CoreLib/src/System/OperatingSystem.cs#L161](url)

**Comment by keithblows** [comment] 2022-01-19 15:23
Arch and Alpine Linux variants/derivatives raise this exception with .NET 6.0.1

**Comment by Joelius300** [comment] 2022-01-27 13:02
Any updates on this? I couldn't find any workarounds so as of now I simply can't work on my application because of this targeting bug. It would be great to have a fix, even if it's just a temporary one.

I searched through the sources and found some msbuild (I think) entries and copied them to my code to see what variables are set. However, I have never worked with msbuild directly and I'm not sure if I understand; please correct me if I'm wrong.

The following .csproj builds correctly on my 5.16.2-1-MANJARO which would indicate that
- it's not a partial facade assembly
- I don't target any OS (?)
- I don't target windows
- I don't target Unix (?)

If any of those conditions weren't true, the build would throw an error indicating that that file could not be found.

```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="System.IO.Ports" Version="6.0.0" />
    </ItemGroup>
    
    <PropertyGroup>
      <IsPartialFacadeAssembly Condition="$([MSBuild]::GetTargetFrameworkIdentifier('$(TargetFramework)')) == '.NETFramework'">true</IsPartialFacadeAssembly>
    </PropertyGroup>
  
    <ItemGroup>
      <Compile Condition="'$(IsPartialFacadeAssembly)' == 'true'" Include="PartialFacadeAssembly == true" />
      <Compile Condition="'$(TargetsAnyOS)' == 'true'" Include="TargetsAnyOS == true" />
      <Compile Condition="'$(TargetsWindows)' == 'true'" Include="TargetsWindows == true" />
      <Compile Condition="'$(TargetsUnix)' == 'true'" Include="TargetsUnix == true" />
    </ItemGroup>
</Project>
```

In the following snippet there's a condition for generating the not-supported warnings with "ISN'T a partial facade assembly AND DOES target any OS". I don't know when these conditions are checked. If they are checked when I build _my_ project, I don't understand why these warnings are generated, since only the first of those two conditions apply to my project.

https://github.com/dotnet/runtime/blob/19291ccf33f1ca130c08eebd3f1cabbee751cd7c/src/libraries/System.IO.Ports/src/System.IO.Ports.csproj#L18

Also more of a side-note but "System.IO.Ports is currently only supported on Windows." hasn't been true for quite a while now.

https://github.com/dotnet/runtime/blob/19291ccf33f1ca130c08eebd3f1cabbee751cd7c/src/libraries/System.IO.Ports/src/Resources/Strings.resx#L225

**Comment by Joelius300** [comment] 2022-01-27 13:12
> Arch and Alpine Linux variants/derivatives raise this exception with .NET 6.0.1

According to https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md#linux, Alpine Linux should be fully supported, so that's even worse than the Manjaro case I guess.

I also just now for the first time realized that .NET doesn't support Arch Linux derivatives. That's very unfortunate, I've been using it on Manjaro (arch based) for a while now without issues until this struck. I really hope .NET can support Arch distros in the future!

**Comment by Joelius300** [comment] 2022-02-05 11:32
Any updates on this? Or any workarounds?

**Comment by Joelius300** [comment] 2022-02-22 07:24
Bump

**Comment by PRIMETSS** [comment] 2022-03-03 05:02
> Arch Linux

OK I just downloaded latest version of Manjaro 21.2.4 and created a USB boot version (just for quick test on laptop)
Installed latest version of dotnet SDK 6.0.102 with installer `dotnet-installer.sh`
[dotnet-install.sh](https://docs.microsoft.com/en-gb/dotnet/core/install/linux-scripted-manual#scripted-install)
Built this simple Serial Test utility I wrote years ago for testing ports on Pi's
[Repo GITHUB](https://github.com/PRIMETSS/runtime_SerialPort_TestApp)
Added package reference to .csproj file to latest preview (removed the <Hint> that was pulling System.IO.Ports from local dotnet Repo I was previously working on System.IO.Ports/SerialPorts, fixed version to the preview)

`  <ItemGroup>
    <PackageReference Include="System.IO.Ports" Version="7.0.0-preview.1.22076.8" />          
  </ItemGroup>
`
Did a dotnet restore and rebuild to pull down package reference
Connected a USB FTDI Serial port/device
And ran the Test app, and it found the serial port and opene
![Screenshot_2022-03-03_04-39-52](https://user-images.githubusercontent.com/11331370/156498814-2618c5c0-dd56-47d7-9a26-e735e0cb5202.png)
d it.
Was expecting a failure or not found. But seems to work.
I havent tried it older v5 SDK of dotnet

So have you tried the latest build and latest preview of `System.IO.Ports` ?

**Comment by Joelius300** [comment] 2022-03-03 06:58
Unfortunately that doesn't work for me.

`dotnet --info` (I didn't use the installer script because I've never encountered issues with the official repo version unlike others)
```
.NET SDK (reflecting any global.json):
 Version:   6.0.102
 Commit:    49861cb924

Runtime Environment:
 OS Name:     manjaro
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.102/

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  3.1.120 [/usr/share/dotnet/sdk]
  6.0.102 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.20 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

My os is:
```
5.16.11-2-MANJARO x86_64 GNU/Linux
```

csproj of test-project:
```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="System.IO.Ports" Version="7.0.0-preview.1.22076.8" />
    </ItemGroup>

</Project>
```

I still get the same exception as soon as the constructor is called:
```
System.PlatformNotSupportedException: System.IO.Ports is currently only supported on Windows.
   at System.IO.Ports.SerialPort..ctor()
   at Program.<Main>$(String[] args) in .../Program.cs:line 20
   at Program.<Main>(String[] args)
```

Ps. your repo is probably private, I can't view it.

**Comment by PRIMETSS** [comment] 2022-03-03 08:12
5.16.11-2-MANJARO x86_64 GNU/Linux ? I can find that version, but might be just be a different reported version format.
What's it running on?

**Comment by Joelius300** [comment] 2022-03-03 10:06
@PRIMETSS 

I just did `uname -srmo` to get `Linux 5.16.11-2-MANJARO x86_64 GNU/Linux`. 5.16.11-2 is just my linux kernel version. My Manjaro is fully updated so if you did that after installing, you should have the same system package wise.

Again, the more interesting difference might be how .NET was installed. Could you try installing .NET SDK 6.0.2 from the package manager and see if that works?

> What's it running on?

Not sure what you mean. It's bare-metal, not a VM, if that's what you mean.

**Comment by PRIMETSS** [comment] 2022-03-03 11:21
@Joelius300 Didn't want to make that repo public as it's just a very simple junk hack test util. But Ive added you as contributor so you can try it so comparing like for like.
Is there a way to contact you out of band so we don't spam this topic unless worth while to share.
Interesting to find out why I didn't have issue today from a new install. (as above)
Did a `uname ` and was 'Linux 5.15.25-1-MANJARO x86_64 GNU/Linux' Interesting older Kernel than yours.. (Was stable branch though)

**Comment by Joelius300** [comment] 2022-03-03 13:22
Let's talk in an issue of your repo. We can update this issue here with our findings when we have some.

**Comment by Joelius300** [comment] 2022-03-04 09:18
The issue was fixed for me when installing the .NET SDK using the [installer script](https://docs.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual). I'm assuming the error is with the RID. Comparing the outputs of `dotnet --info` on the package install vs the script install reveals that the package install sets the RID as `arch-x64` as opposed to `linux-x64`. This would also match with the OP, where the RID was set to `arch-x64` and they couldn't get it working; and with @PRIMETSS observations as they got it working with their RID being set to `linux-x64`.

However, my IDE (rider) isn't happy quite yet. When I go to the definition of SerialPort for example, it still shows me the shims which just throw (see below). This also means I don't see the XML summaries. I'm assuming this is a caching issue but I've not managed to solve it even after invalidating all rider caches and deleting all NuGet caches.

![image](https://user-images.githubusercontent.com/52202086/156732747-8121205f-5500-4c5a-972d-6e4dc97dd99c.png)

**Comment by PRIMETSS** [comment] 2022-03-08 01:50
Wont port all the other comments across re Manjaro, Tried same on Latest Ubuntu

---
Just out of interest
Installed Ubuntu, updated, installed DotNet 6.0.120 SDK from "Ubuntu Software"/Store install
And got same results you had previously with Manjaro, with SerialPort test app
"SerialPort only supported on Windows"
Runtime [6.0.2]

Ran dotnet-install.sh [SDK 6.0.102]
Got same exception error!
Rebooted
Ran app again: Got same exception error!
Deleted and dotnet Rebuild app
Ran app again: Got same exception error!

Modified (Was not forcing versioning before)
Rebuilt
Ran app again: Worked and opened serial port successfully.

So def got fixed from 6 to 7-preview1

Looking...
And believe it actually got fixed starting here https://github.com/dotnet/corefx/pull/30903
So now (7.1prev) working on Manjaro & Ubuntu (20.04.4 LTS)

[Close it?]

**Comment by Joelius300** [comment] 2022-03-08 07:56
Ubuntu _should_ work fine but I've not tested it 🤔 the PR you linked is from 2018, that should definitely have been included in .NET 6 already.

On the other hand, https://github.com/dotnet/runtime/pull/64500 and https://github.com/dotnet/runtime/commit/9ebe0efa4850fb2e451befe1fdf7c2d3cbb5c862, which weren't included in .NET 6, might have solved some issues as they mention RID and framework-targeting but I don't have a deep enough understanding of these libraries that I could say this with certainty.

**Comment by Joelius300** [comment] 2022-03-23 05:50
Bump: This issue has not been resolved. It would be great to at least have clarification on the RID difference when using different ways of installing. Also I don't understand why this specific package only works with `linux-x64` but not `arch-x64` while other packages worked perfectly fine. `arch-x64` is not listed as one of the [most common RIDs](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog#linux-rids) (I can understand that) but it seems that `arch-x64` should at least include `linux-x64` (see below) so why does `linux-x64` behave differently than `arch-x64`?

https://github.com/dotnet/runtime/blob/c5d40c9e703fd257db1b26ef4fd1399bbae73ab0/src/libraries/Microsoft.NETCore.Platforms/src/runtime.json#L643-L653

Ps. I believe all of this has already been said by @ericstj [here](https://github.com/dotnet/runtime/issues/62554#issuecomment-989286705) but wasn't followed up by @badgerwild .

**Comment by ericstj** [comment] 2022-03-23 19:57
Here's a brief description of how the RID comes into play when loading libraries.  I still can't tell if you're reporting any problem with this process or not.
1. The application is built with RID-specific assets described in the deps.json file.  For a given library it might have many RID specific assets, the host is responsible for selecting the best one.
2. The host calculates the current RID based on what it sees on the system.  There's also an override for this.  Different versions of the host have [different logic for calculating RIDs](https://github.com/dotnet/runtime/blob/ea4ebaa3c5162bcabc63284ba3b59aa683912af4/src/native/corehost/hostmisc/pal.unix.cpp#L570-L835).  There's also some environment variables that can override this.
3. The shared framework's deps file lists the set of "compatible RIDs" that the runtime knows about.  It's a flattened version of the graph from the `runtime.json` that lists the RIDs in order of precedence.
4. When the host loads an app, it looks at the current RID from 2, the list of compatible RIDs from 3, to select the best runtime asset from 1.

If this library doesn't work it probably means a difference in something in one of the above steps.  The best way to diagnose that is to look at a COREHOST trace like I suggested above.  No-one has yet provided that trace so this issue is still in `needs-author-action`.  Anyone who can reproduce the failure is free to capture a trace and share it and we can have a look.  When doing so tag me and I can walk you through it.

> However, my IDE (rider) isn't happy quite yet. When I go to the definition of SerialPort for example, it still shows me the shims which just throw (see below). 

IDEs should never use RID-specific assets.  Those are only used at runtime.  The fact that its disassembling the PNSE assembly is expected.  A feature in the IDE could be for it to allow the user to explore other potentially applicable runtime asseets.  I'm not aware of anyone doing this for "go to definition".  I am aware of some designers fetching runtime assets though - so they can use load some runtime specific implementations in the designer process that needs to run code and not just compile against it.

> This also means I don't see the XML summaries.

I see the XML is present in the package next to the PNSE assemblies. The IDE should be able to find it.

**Comment by Joelius300** [comment] 2022-03-24 15:24
Thanks for the response @ericstj 

I just recorded COREHOST traces for both the working state (RID=linux-x64 .NET 6 installed via installer script) and the faulty state (RID=arch-x64 .NET 6 installed via Manjaro's official repository) along with the respective outputs of `dotnet --info`.

Since they are thousands of lines long and contain some paths (but probably not more sensitive data right?) I wanted to ask first of all if that's expected or if I need to decrease verbosity or something like that and secondly, how should I provide these files? Should I just upload them as files here or would you like them in a gist or repo?

As for the XML summaries part, I don't see them when hovering over methods/types in Rider (without going to definition), not sure why it can't find those. Going to definition opens the .notsupported.cs file as seen in a previous post of mine. I think we can disregard that for now as you said that this might be expected IIRC.

Here's my setup for testing:

serial-port-testing.csproj (generated with `dotnet new console`)
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>serial_port_testing</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Ports" Version="6.0.0" />
  </ItemGroup>

</Project>
```
Program.cs
```csharp
using System.IO.Ports;

Console.WriteLine(string.Join(", ", SerialPort.GetPortNames()));
```

Command:
```bash
COREHOST_TRACE=1 COREHOST_TRACEFILE=./COREHOST.TRACE dotnet run
```

Exception in faulty case:
```
Unhandled exception. System.PlatformNotSupportedException: System.IO.Ports is currently only supported on Windows.
   at System.IO.Ports.SerialPort.GetPortNames()
   at Program.<Main>$(String[] args) in /.../serial-port-testing/Program.cs:line 3
```

**Comment by ericstj** [comment] 2022-03-24 18:09
> COREHOST_TRACE=1 COREHOST_TRACEFILE=./COREHOST.TRACE dotnet run

Don't trace `dotnet run` -- this does a full build and you'll be tracing a lot more than you need.  Build it first, then run just
`bin/debug/net6.0/serial-port-testing` with tracing.

You can zip them up and drop them in the issue (GitHub supports hosting files), post a gist, email them to me if you prefer -- using the email in my profile, or suggest some other way to share them.  The logs would contain some paths.  I looked through and didn't see anything sensitive and am sharing mine.

I've done the same thing on my windows machine and will walk you through the load process, just in case you want to diagnose yourself.

[Host identifies it's RID ](https://gist.github.com/ericstj/8d8ce51cb6b9981bebb248eab52ce7ee#file-corehost-trace-L660)
```
HostRID is win10-x64
```

You can see the [fallback chain for this RID](https://gist.github.com/ericstj/8d8ce51cb6b9981bebb248eab52ce7ee#file-corehost-trace-L582-L594) by finding the entry that begins with the RID from above followed by `=>`
```
win10-x64 => [
win10, 
win81-x64, 
win81, 
win8-x64, 
win8, 
win7-x64, 
win7, 
win-x64, 
win, 
any, 
base, 
]
```
If there is no chain here for the host RID that would be a cause of the problem.  That would mean that the host would not consider any compatible fallback RIDs for loading assets.   For example, if the host said it was using `win12-x64` then it wouldn't consider any fallbacks.

You can then see the host consider which of the rids in the list above are best for each library.  [Here ](https://gist.github.com/ericstj/8d8ce51cb6b9981bebb248eab52ce7ee#file-corehost-trace-L661)it chooses `win` since that's the best and excludes assets from the other runtimes.  Also note that since this is windows none of the native assets from this package's dependencies apply.

**Comment by Joelius300** [comment] 2022-03-24 19:47
Thanks, that's more manageable :)

I did this and summarized the results in [this gist](https://gist.github.com/Joelius300/71d5b26c6cd2999b73d3ff6c908f8c4b).

I've also taken the liberty to try and interpret the fallback chain you mentioned.
Extract from Line 418 to 428:
```
The rid fallback graph is: {
arch-x64 => [
arch, 
linux-x64, 
linux, 
unix-x64, 
unix, 
any, 
base, 
]
}
```

In addition, a little below on the lines 438-439:
```
HostRID is manjaro-x64
Falling back to base HostRID: linux-x64
```

If I understand correctly, the fallback chain is correct. It correctly falls back to `linux-x64` (and further) with which I've managed to confirm it working.

However, [just below the second snipped I posted](
https://gist.github.com/Joelius300/71d5b26c6cd2999b73d3ff6c908f8c4b#file-corehost-trace-L440-L470), there might something more interesting:

```
The targeted framework does not support the runtime 'linux-x64'. Some native libraries from [System.IO.Ports/6.0.0] may fail to load on this platform.
The targeted framework does not support the runtime 'linux-x64'. Some native libraries from [System.IO.Ports/6.0.0] may fail to load on this platform.
The targeted framework does not support the runtime 'linux-x64'. Some native libraries from [System.IO.Ports/6.0.0] may fail to load on this platform.
The targeted framework does not support the runtime 'linux-x64'. Some native libraries from [runtime.osx-x64.runtime.native.System.IO.Ports/6.0.0] may fail to load on this platform.
The targeted framework does not support the runtime 'linux-x64'. Some native libraries from [runtime.osx-x64.runtime.native.System.IO.Ports/6.0.0] may fail to load on this platform.
The targeted framework does not support the runtime 'linux-x64'. Some native libraries from [runtime.osx-x64.runtime.native.System.IO.Ports/6.0.0] may fail to load on this platform.
The targeted framework does not support the runtime 'linux-x64'. Some native libraries from [runtime.osx-arm64.runtime.native.System.IO.Ports/6.0.0] may fail to load on this platform.
The targeted framework does not support the runtime 'linux-x64'. Some native libraries from [runtime.osx-arm64.runtime.native.System.IO.Ports/6.0.0] may fail to load on this platform.
The targeted framework does not support the runtime 'linux-x64'. Some native libraries from [runtime.osx-arm64.runtime.native.System.IO.Ports/6.0.0] may fail to load on this platform.
The targeted framework does not support the runtime 'linux-x64'. Some native libraries from [runtime.linux-x64.runtime.native.System.IO.Ports/6.0.0] may fail to load on this platform.
The targeted framework does not support the runtime 'linux-x64'. Some native libraries from [runtime.linux-x64.runtime.native.System.IO.Ports/6.0.0] may fail to load on this platform.
The targeted framework does not support the runtime 'linux-x64'. Some native libraries from [runtime.linux-arm64.runtime.native.System.IO.Ports/6.0.0] may fail to load on this platform.
The targeted framework does not support the runtime 'linux-x64'. Some native libraries from [runtime.linux-arm64.runtime.native.System.IO.Ports/6.0.0] may fail to load on this platform.
The targeted framework does not support the runtime 'linux-x64'. Some native libraries from [runtime.linux-arm64.runtime.native.System.IO.Ports/6.0.0] may fail to load on this platform.
The targeted framework does not support the runtime 'linux-x64'. Some native libraries from [runtime.linux-arm.runtime.native.System.IO.Ports/6.0.0] may fail to load on this platform.
The targeted framework does not support the runtime 'linux-x64'. Some native libraries from [runtime.linux-arm.runtime.native.System.IO.Ports/6.0.0] may fail to load on this platform.
The targeted framework does not support the runtime 'linux-x64'. Some native libraries from [runtime.linux-arm.runtime.native.System.IO.Ports/6.0.0] may fail to load on this platform.
Adding runtime asset serial-port-testing.dll assemblyVersion= fileVersion= from serial-port-testing/1.0.0
Adding runtime asset lib/net6.0/System.IO.Ports.dll assemblyVersion=6.0.0.0 fileVersion=6.0.21.52210 from System.IO.Ports/6.0.0
Reconciling library serial-port-testing/1.0.0
Parsed runtime deps entry 0 for asset name: serial-port-testing from project: serial-port-testing, library version: 1.0.0, relpath: serial-port-testing.dll, assemblyVersion , fileVersion 
Reconciling library runtime.linux-arm.runtime.native.System.IO.Ports/6.0.0
Reconciling library runtime.linux-arm64.runtime.native.System.IO.Ports/6.0.0
Reconciling library runtime.linux-x64.runtime.native.System.IO.Ports/6.0.0
Parsed native deps entry 0 for asset name: libSystem.IO.Ports.Native from package: runtime.linux-x64.runtime.native.System.IO.Ports, library version: 6.0.0, relpath: runtimes/linux-x64/native/libSystem.IO.Ports.Native.so, assemblyVersion , fileVersion 0.0.0.0
Reconciling library runtime.native.System.IO.Ports/6.0.0
Library runtime.native.System.IO.Ports/6.0.0 does not exist
Reconciling library runtime.osx-arm64.runtime.native.System.IO.Ports/6.0.0
Reconciling library runtime.osx-x64.runtime.native.System.IO.Ports/6.0.0
Reconciling library System.IO.Ports/6.0.0
Parsed runtime deps entry 1 for asset name: System.IO.Ports from package: System.IO.Ports, library version: 6.0.0, relpath: lib/net6.0/System.IO.Ports.dll, assemblyVersion 6.0.0.0, fileVersion 6.0.21.52210
```


I don't want to say more than that, I'm wildly underqualified, but I hope this helps. I didn't redo the trace with the working setup but if it would help I can.

**Comment by Joelius300** [comment] 2022-03-25 07:49
I decided to try out the AUR packages as well, as they seem to work better than the official ones by many reports. I installed `dotnet-sdk-bin` and `aspnet-targeting-pack-bin` and repeated the steps described above.

The results are in [this gist](https://gist.github.com/Joelius300/e931369c0763f6adc7f4302687f1b9a2).

Some observations:
- there are many more fallback chains but none of them contain manjaro
- HostRID is still `manjaro-x64` and fall back to base HostRID `linux-x64`
- working trace contains line "Chose unix, so removing rid (win) specific assets for package System.IO.Ports/6.0.0 and asset type runtime" which can't be found anywhere in the failing one

**Comment by Joelius300** [comment] 2022-04-17 14:05
Is there anything else I can do/provide?

**Comment by Joelius300** [comment] 2022-05-02 19:21
Bump

**Comment by ericstj** [comment] 2022-05-02 21:58
@Joelius300 sorry for the delay in getting back to you.  Let me just restate what I'm seeing where I think things are going wrong.

1) FAILING: https://gist.github.com/Joelius300/71d5b26c6cd2999b73d3ff6c908f8c4b
```
HostRID is manjaro-x64
Falling back to base HostRID: linux-x64
The targeted framework does not support the runtime 'linux-x64'. Some native libraries from [System.IO.Ports/6.0.0] may fail to load on this platform.
```
2) Succeeding: https://gist.github.com/Joelius300/e931369c0763f6adc7f4302687f1b9a2
```
HostRID is manjaro-x64
Falling back to base HostRID: linux-x64
Chose unix, so removing rid (win) specific assets for package System.IO.Ports/6.0.0 and asset type runtime
```

If you examine the fallback-RID chain's present in the success case, you'll see that a chain is defined for `linux-x64` that begins with `linux-x64 =>`.

In the case of the failing runtime, the shared frameworks deps file does not have this fallback chain.  The only one present is for `arch-64`  Since this chains neither starts with the actual RID (`manjaro-x64`) nor the fallback rid (`linux-x64`) the host will not use it.  @vitek-karas does this sound correct?

If you would like for that failing case to better support falling back to the `linux-x64` RID then you should make sure it has that fallback chain added to the shared framework's deps file.  I think this is controlled by the flag @jkoritzinsky added here: https://github.com/dotnet/arcade/commit/d4dc3682cbad0314b6f138017411ee03ea51096b
Any idea how those official manjaro packages are building and how to make such a change?

**Comment by Joelius300** [comment] 2022-05-03 07:32
No worries, thanks for investigating :)

> Any idea how those official manjaro packages are building and how to make such a change?

No idea, I'm sorry.

If you need anything from my end, I'll be happy to assist where I can.

**Comment by vitek-karas** [comment] 2022-05-03 11:01
This feels almost like a dupe of https://github.com/dotnet/sdk/issues/23390.
Basically the RID fallback graph is wrong in this case.

Short description of how the RID stuff works in the host:
* Host loads the RID fallback graph. For framework dependent apps this comes from the `Microsoft.NETCore.App.deps.json`. For self-contained apps it comes from the `app.deps.json`. Ultimately it's produced by the SDK.
* Host determines a very specific RID, on Linux this is typically `<distroname>.<version>-<arch>`. In the Manjaro case it got `manjaro-x64`. The code for this is rather complicated and differs a lot across platforms: https://github.com/dotnet/runtime/blob/288de113d01c183d5e323005728096911dc03c55/src/native/corehost/hostmisc/pal.unix.cpp#L708 (and around)
* It tries to find this very specific RID (`manjaro-x64`) in the RID fallback graph. If it's there, great, it uses it.
* If it's not there it constructs a fallback RID - this one is [hardcoded in the host](https://github.com/dotnet/runtime/blob/288de113d01c183d5e323005728096911dc03c55/src/native/corehost/hostmisc/pal.h#L78-L89) - it is basically `<platform>-<arch>`, so in this case `linux-x64`.
* It then looks for this in the RID fallback graph again - if it's there, uses it.
* If it has RID in the fallback graph it starts from the RID it found (so `linux-x64` in this case) and sees if a given entry has asset for the RID, if not, it goes one step down in the graph and looks again and so on. This is how in the success case it found the `unix` RID and found the asset (`runtimes/unix/lib/net6.0/System.IO.Ports.dll`) for it.
* If even the fallback RID is not in the graph it will not be able to fully resolve RIDs, and so it looks for exact match to the fallback RID only - this is the second failing case - since there's no asset for `System.IO.Ports.dll` for RID `linux-x64`, so in this case it adds the RID-less asset `lib/net6.0/System.IO.Ports.dll` which is probably just an empty shell with throws everywhere.

I think the fix for this is effectively the same as the fix for https://github.com/dotnet/sdk/issues/23390 - that is to never get a RID fallback graph which is incomplete. The `arch-x64` fallback graph in the failing case is incomplete because it defines fallbacks for `arch-x64`, but not fallbacks of those fallbacks. Essentially each fallback graph should have a path from any RID through any of its fallbacks all the way down to `any`/`base` RID. This one doesn't.

**Comment by ericstj** [comment] 2022-05-17 19:31
It could be that https://github.com/dotnet/runtime/issues/53550 helps here.

**Comment by Joelius300** [comment] 2022-06-07 14:19
Bump :)

**Comment by agocke** [comment] 2022-06-14 23:41
We don't plan to make any changes for this area for .NET 7. For .NET 8, we're investigating https://github.com/dotnet/runtime/issues/59803, which may address this scenario directly, or cause us to take a different change for this.

In the meantime I see two potential solutions:

1. Use the Microsoft-provided zip files for portable linux-x64 (i.e. from https://dot.net/download)
2. Contact the maintainer of the dotnet package for the distro and have them manually fix up the runtime.json file to contain all the appropriate fallbacks

**Comment by Joelius300** [comment] 2022-06-16 06:12
Thank you the clarification.

For any Manjaro users stumbling into this issue, a third solution is using the AUR packages (e.g. `dotnet-sdk-bin` and `aspnet-targeting-pack-bin`) instead of the official ones, as those seem to work perfectly fine.

**Comment by kleisauke** [comment] 2022-12-14 06:24
FWIW, this also causes issues with other NuGet packages distributed in a multi-target manner, see e.g. https://github.com/kleisauke/net-vips/issues/186.

The symptoms are the same, it causes to reference `lib/<TargetFramework>/*.dll` (which are usually specific to Windows) instead of `runtimes/unix/lib/<TargetFramework>/*.dll`  or `runtimes/linux/lib/<TargetFramework>/*.dll`.

**Comment by agocke** [comment] 2023-06-26 20:27
Closing as RIDs are no longer resolved in the same way: https://learn.microsoft.com/en-us/dotnet/core/compatibility/deployment/8.0/rid-asset-list

**Closed by agocke** 2023-06-26 20:27 UTC
Labels: area-Host
