### ISSUE TITLE
Bumping min supported iOS/tvOS/macCatalyst version to 12 in .net 9

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#94345] opened 2023-11-03 14:20 UTC
Context: https://github.com/dotnet/runtime/pull/94298/files#r1381512661

**Comment by vcsjones** [comment] 2023-11-03 14:54
I think this is a duplicate of https://github.com/dotnet/runtime/issues/91736.

**Closed** 2023-11-03 15:11 UTC
Labels: area-VM-meta-mono
