### ISSUE TITLE
Cannot serialize/deserialize entity with default value of nullable enum type

### ISSUE THREAD

**Issue by Magomed26** [dotnet/runtime#72674] opened 2022-07-22 13:45 UTC
### Description

When trying to serialize or deserialise entity that has property of nullable enum type with some default value except null serialization/deserialization falls with cast exception

### Reproduction Steps

```
//Deserialization
var json = @"{""name"": ""John Doe"", ""age"": 24}";
var deserialize = JsonSerializer.Deserialize<User>(json);
//Serialization
var user = new User("John Doe", 24);
var result = JsonSerializer.Serialize(user);
Console.WriteLine(result);

public record User(string Name, int Age, UserType? GroupType = UserType.Manager);

public enum UserType
{
    Unknown,
    Manager,
    Admin
}
```

### Expected behavior

Expects that the serialized string would be:
`{"Name":"John Doe","Age":24,"GroupType":1}`

### Actual behavior

throws
```
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.Nullable`1[UserType]'.
   at System.Text.Json.Serialization.Metadata.JsonParameterInfo`1.InitializeDefaultValue(JsonPropertyInfo matchingProperty)
   at System.Text.Json.Serialization.Metadata.JsonParameterInfo`1.Initialize(JsonParameterInfoValues parameterInfo, JsonPropertyInfo matchingProperty, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.InitializeConstructorParameters(JsonParameterInfoValues[] jsonParameters, Boolean sourceGenMode)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.Configure()
   at System.Text.Json.Serialization.Metadata.ReflectionJsonTypeInfo`1.Configure()
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo.EnsureConfigured()
   at System.Text.Json.JsonSerializerOptions.GetOrAddJsonTypeInfo(Type type)
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type runtimeType)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)

   at Program.<Main>$(String[] args) in Program.cs:line 6
```

**Comment by feiyun0112** [comment] 2022-07-23 15:47
same as #68647

plan to solve in .NET 8

**Comment by eiriktsarpalis** [comment] 2022-07-25 08:20
Closing as dupe of https://github.com/dotnet/runtime/issues/68647.

**Closed by eiriktsarpalis** 2022-07-25 08:20 UTC
Labels: area-System.Text.Json, untriaged
