### ISSUE TITLE
GC slows down use of multiple instances of LinkedList and SortedSet in parallel environment

### ISSUE THREAD

**Issue by 21a1ss3** [dotnet/runtime#93745] opened 2023-10-19 17:18 UTC
### Description

Hi. Recently I started some side project which will involve work with big numbers and I require to have an BigInteger collections, but atm tested it on a smaller scale. My solution is basically generating some numbers and then feeding them up into multiple collections in most case on 1-1 relation. I wrote some code which involved multiple tasks (equal to CPU core amount) and expected to see 100% (or about to it) CPU load, but instead my values was way lower than this. After doing some experiments I discovered that it is related to the fact of adding number into collection. Once I drop that part of the code - load gets back to 100% CPU.

Later I isolated that test scenario into that project: https://github.com/21a1ss3/BigIntPerfIssue .

In that project you can see multiple test cases (currently 9) with parallel code based on tasks which generates numbers and adding them into collections on relation 1 task - 1 collection. If you launch (don't forget to adjust amount of cores) cases from 1-5, 7 and 9 you will see that your CPU is not loaded to 100%, instead load will be around 50-60% despite you do not have any synchronization locks in your code. 

### Configuration

Tested on:
.NET Core 3.1.415
.NET 7.0.1.31918
.NET 7.4.223.48029

CPU: 
Intel i7-4750HQ
Intel i5-2310

Windows 10 x64 (don't think it matters significantly)

### Data

My benchmarking showing CPU load around 50-70% of the overall system CPU usage on both setups when I launched solution without debugging for slow test cases (1-5, 7, 9). And 100% (or about to it) for cases 6 and 8.

### Analysis

Initially I suspected BigInteger (based on tests 1-6), but later with few more tests I discovered that it is not the case, problem caused by node structure.

I've used `Concurrency Visualizer` to try to analyze the source of the problem, but because it hasn't picked up my managed code correctly I only been abnle to see a fraction of the results. Although the results there where pointing towards `new` operator and GC.

**Comment by eiriktsarpalis** [comment] 2023-10-20 18:04
The issue is that the reproducing project hasn't been configured to use GC Server mode. You can check this by adding this line at the start of your `Main` method:
```C#
Console.WriteLine(GCSettings.IsServerGC);
```
Once I add `<ServerGarbageCollection>true</ServerGarbageCollection>` to the project configuration most methods that I checked immediately saturate all my CPU cores. 

Here's a minimal reproduction:
```C#
const int Capacity = 1_000_000;
int n = Environment.ProcessorCount;

Console.WriteLine($"IsServerGC: {GCSettings.IsServerGC}");

Parallel.For(0, n, i =>
{
    var list = new List<BigInteger>(Capacity);

    BigInteger iter = 0;
    while (true)
    {
        list.Add(iter * n + i);
        iter++;

        if (list.Count == Capacity)
        {
            list.Clear();
            if (i == 0)
            {
                Console.WriteLine(iter);
            }
        }
    }
});
```

**Comment by 21a1ss3** [comment] 2023-10-21 15:11
Hi @eiriktsarpalis, that's quite interesting, because I thought that I turned on Server mode through `runtimeconfig.json` as shown in example just above section `Flavors of garbage collection` in https://learn.microsoft.com/en-us/dotnet/core/runtime-config/garbage-collector#flavors-of-garbage-collection. That might explain that weird behavior.

Then I have the next question - why  `runtimeconfig.json`  had no effect on GC mode?

**Comment by eiriktsarpalis** [comment] 2023-10-21 17:33
Seems related to how runtimeconfig.template.json [works](https://learn.microsoft.com/en-us/dotnet/core/runtime-config/#example-runtimeconfigtemplatejson-file):

> If you're placing the options in the template JSON file, omit the runtimeOptions property.

Using this configuration in a template.json works as expected:

```json
{
    "configProperties": {
        "System.GC.Server": true,
        "System.GC.Concurrent":  true
    }
}
```

**Comment by 21a1ss3** [comment] 2023-10-21 17:44
> Seems related to how runtimeconfig.template.json [works](https://learn.microsoft.com/en-us/dotnet/core/runtime-config/#example-runtimeconfigtemplatejson-file):
> 
> > If you're placing the options in the template JSON file, omit the runtimeOptions property.
> 
> Using this configuration in a template.json works as expected:
> 
> ```json
> {
>     "configProperties": {
>         "System.GC.Server": true,
>         "System.GC.Concurrent":  true
>     }
> }
> ```

I see now what was the issue. Thanks for highlighting it.

I think it very easy to confuse new file formats and make an error as I did. It might be worth to briefly mention at least once about that difference inside GC article with link to the page which you provided.

Anyway thanks for helping with current case.

**Comment by eiriktsarpalis** [comment] 2023-10-21 17:50
You're welcome. I'm going to close the issue now since it seems resolved.

**Closed by eiriktsarpalis** 2023-10-21 17:50 UTC
Labels: question, area-System.Collections, tenet-performance, needs-further-triage
