### ISSUE TITLE
FusedMultiplyAdd ridiculously slow on Xeon E5-2697

### ISSUE THREAD

**Issue by RaceRalph** [dotnet/runtime#34450] opened 2020-04-02 11:21 UTC
My application does heavy maths and uses System.Math.FusedMultiplyAdd(double, double, double) wherever possible to improve performance.  It works like a charm on many computers except the one with Xeon CPU E5-2697 v2 @2.7GHz, where the application is ridiculously slow.  I mean: about 40 times slower!  As soon as I replace all FusedMultiplyAdd calls with standard multiplication and addition, it works at full speed.

Windows 10 x64
Windows Desktop Runtime 3.1.3 (x64) installed.
The C# project targets .NET Core 3.1.  Platform: x64.

**Comment by EgorBo** [comment] 2020-04-02 11:24
Your Xeon (Ivy Bridge) doesn't support FMA set so it falls back to `fma` call via internal call.
I wonder if JIT should just do `=> a * b + c` instead as a fallback.

cc @tannergooding

**Comment by tannergooding** [comment] 2020-04-02 14:58
> I wonder if JIT should just do => a * b + c instead as a fallback.

This isn't safe to do because it changes the result of the computation. I'd be fine with exposing some `IsFusedMultiplyAddAccelerated` property that users can key off of as an alternative for when falling back to non fused arithmetic is acceptable.

**Comment by tannergooding** [comment] 2021-01-15 18:05
Closing as this is "by design". Doing fused operations isn't fast if the hardware doesn't support it.

**Closed by tannergooding** 2021-01-15 18:05 UTC
Labels: area-System.Numerics
