### ISSUE TITLE
Don't fail silently when an object is passed to JsonSerializer.SerializeAsync<T>

### ISSUE THREAD

**Issue by yringler** [dotnet/runtime#32801] opened 2020-02-25 17:37 UTC
In #31223 there was confusion about why a class was serializing to an empty object when using JsonSerializer.SerializeAsync<T>.
It was happening, as @yruson explained there, 

> because System.Text.Json.Serializer is a generic method and it uses the generic parameter, not the runtime type.

So if it's given a value of type Object, it'll serialize as empty.

I had the same issue, and found #31223. Calling `JsonSerializer.SerializeAsync(stream, value, value.GetType())` works, but I'll probably switch to generics.

I think JsonSerializer.SerializeAsync<T> should either call GetType() if its passed an Object or throw an exception?
I can't think of a use case where someone wants his data serialized as an empty object. If passing in an Object is ok, it should be serialized correctly. And if not, there should probably be an exception thrown.

**Comment by Mpdreamz** [comment] 2020-02-25 18:20
Also reported under: https://github.com/dotnet/runtime/issues/31464#issuecomment-589513848

**Comment by layomia** [comment] 2020-02-28 17:33
cc @steveharter

**Comment by layomia** [comment] 2020-02-28 21:22
This is a duplicate of https://github.com/dotnet/runtime/issues/31464.

**Closed by layomia** 2020-02-28 21:22 UTC
Labels: area-System.Text.Json, untriaged
