### ISSUE TITLE
Children could not evaluated in Blazor Web Assembly.

### ISSUE THREAD

**Issue by TanvirArjel** [dotnet/runtime#66401] opened 2022-03-09 16:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Getting the response as JSON from the API correctly but whenever trying to deserialize  the JSON it's saying **Children could not be evaluated** while trying to debug as follows:

```C#
 string countriesJson = await httpResponseMessage.Content.ReadAsStringAsync();
 JsonSerializerOptions options = new JsonSerializerOptions()
 {
     PropertyNameCaseInsensitive = true,
 };

 Country[] countries = JsonSerializer.Deserialize<Country[]>(countriesJson, options); // If try to see the countries it says : Children could not be evaluated
```

Then I have checked with the following code:

```C#
 List<string> items = new List<string> { "Tanvir", "Ahamad" };
 Console.WriteLine(items); // Here items says : Children could not be evaluated 
```

### Expected Behavior

The item should be seen in debugging.

### .NET Version

6.0.3

### Anything else?

Visual Studio Version: 2022 17.2.0 Preview 1.0

**Comment by mkArtakMSFT** [comment] 2022-03-09 17:17
@thaystg can you please look into this? Thanks!

**Comment by thaystg** [comment] 2022-03-09 17:20
@TanvirArjel can you please update this nuget package in your server project?
<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="6.0.3" />

**Comment by TanvirArjel** [comment] 2022-03-09 17:24
@thaystg Why server API project has to be updated? Server API app is a completely separated app. What if my sever API project is Java/NodeJs app?

**Comment by thaystg** [comment] 2022-03-09 17:29
In this package: Microsoft.AspNetCore.Components.WebAssembly.Server is where we pack the BrowserDebuggerProxy, which is what makes the debugger work. So you updated the runtime to use version 6.0.3 and you need to use the same version of the BrowserDebugProxy, that is why I asked you to update this package.

It was a mistake on our side to make this incompatibility, and it will be fixed on 6.0.4, you will be able to use a runtime version 6.0.4 and use a nuget package 6.0.0 for example.

**Comment by TanvirArjel** [comment] 2022-03-09 17:30
@thaystg Yes! I have updated all the packages to the latest version but still problem persists.

**Comment by thaystg** [comment] 2022-03-09 17:34
@TanvirArjel  Did you rebuild your server project after doing it?
Can you share your project then I can take a look on what is happenning?

**Comment by TanvirArjel** [comment] 2022-03-09 17:37
@thaystg What is server project? It's a web assembly project. Please tell clearly what you are actually trying to point to. I am struggling to understand your words!

**Comment by thaystg** [comment] 2022-03-09 17:37
![image](https://user-images.githubusercontent.com/4503299/157498878-f43b743f-55ec-4f52-af41-3cc173d1bb03.png)

**Comment by thaystg** [comment] 2022-03-09 17:41
If it's not an ASP.NET Core hosted you will not have it, but you should update the Microsoft.AspNetCore.Components.WebAssembly.DevServer.

![image](https://user-images.githubusercontent.com/4503299/157499555-1859b3c1-ff3b-4d55-a4f1-ce443e697682.png)

**Comment by TanvirArjel** [comment] 2022-03-09 17:44
The problem is still persisting.

![image](https://user-images.githubusercontent.com/14342773/157499999-0a9c30f0-7cd7-48d1-9cb8-4a3cfc551cb5.png)

**Comment by TanvirArjel** [comment] 2022-03-09 17:49
To reproduce the issue: Please create a brand new Blazor Web Assembly App with Visual Studio Version 17.2.0 Preview 1.0 selecting the latest 6.0.3 SDK.

**Comment by thaystg** [comment] 2022-03-09 17:59
As you can see in the content of this log: 
![image](https://user-images.githubusercontent.com/4503299/157502403-896b9820-b067-4a9b-8f4e-38df34b84588.png)

The runtime version that is being used is 6.0.1, so please, use the same version of the nuget packages, 6.0.1.

**Comment by TanvirArjel** [comment] 2022-03-09 18:02
@thaystg Look at here:

```
C:\Users\TanvirArjel>dotnet-info
'dotnet-info' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\TanvirArjel>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   7.0.100-preview.1.22110.4
 Commit:    129d2465c8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100-preview.1.22110.4\

Host (useful for support):
  Version: 7.0.0-preview.1.22076.8
  Commit:  405337939c

.NET SDKs installed:
  5.0.406 [C:\Program Files\dotnet\sdk]
  6.0.201 [C:\Program Files\dotnet\sdk]
  7.0.100-preview.1.22110.4 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-preview.1.22109.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-preview.1.22076.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-preview.1.22077.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**I didn't have 6.0.1 is even installed on my machine. Then where is it coming from?**

**Comment by thaystg** [comment] 2022-03-09 18:05
@lewing or @mkArtakMSFT , do you know how to answer this question, why it's using the runtime version 6.0.1, if he has the installed versions listed above?

**Comment by lewing** [comment] 2022-03-09 18:07
this problem is caused by building a net6 app with a net7 sdk.  the preview1 sdk appears to have 6.0.1 specfied as the net6 runtime

**Comment by TanvirArjel** [comment] 2022-03-09 18:14
@lewing Why is this mess? I am a big of .NET but I found .NET SDK versioning and interaction is a complete mess. If my app is on .NET 6.0 then it should be built on the latest .NET 6.0 found on the machine. If not any .NET 6.0 is not found on the machine then it should say, the required .NET version is not found on your machine.

**Comment by TanvirArjel** [comment] 2022-03-09 18:19
@lewing Now please help me! how can I point my app to be built on **.NET 6.0.3** insted of 6.0.1 without downgrading the the packges to  6.0.1.

**Comment by hez2010** [comment] 2022-03-09 18:24
Try creating a global.json and fix the sdk version to 6.0.201.

**Comment by lewing** [comment] 2022-03-09 18:24
I believe the instructions at https://docs.microsoft.com/en-us/dotnet/core/versions/selection can help

**Comment by ilonatommy** [comment] 2022-06-23 09:22
@TanvirArjel, thank you for filing the issue and helping us fix the bug. Could you please let us know if the suggestions above were helpful and if you still can reproduce it when versioning problem is sorted out?

**Comment by lewing** [comment] 2022-07-25 23:13
The remaining issues here are covered by other issues.

**Closed by lewing** 2022-07-25 23:13 UTC
Labels: arch-wasm, area-Debugger-mono
