### ISSUE TITLE
Async and sync boxed serialize differ in behaviour (System.Text.Json)

### ISSUE THREAD

**Issue by Mpdreamz** [dotnet/runtime#31464] opened 2019-11-11 15:53 UTC
```csharp
private static JsonSerializerOptions _jsonSerializerOptions = new JsonSerializerOptions { WriteIndented = false };

static async Task<int> Main(string[] args)
{
    var empty = new {};
    var valued = new {x = 1, y = true};

    Console.WriteLine("Generic");
    await Write(empty);
    await Write(valued);
    Console.WriteLine("Boxed");
    await BoxedWrite(empty);
    await BoxedWrite(valued);

    return 0;
}

private static async Task Write<T>(T x)
{
    var blocking = Serialize(x);
    var async = await SerializeAsync(x);

    Console.WriteLine("-- blocking --");
    Console.WriteLine(blocking);
    Console.WriteLine("-- async --");
    Console.WriteLine(async);
}
private static async Task BoxedWrite(object x)
{
    var blocking = Serialize(x);
    var async = await SerializeAsync(x);

    Console.WriteLine("-- blocking --");
    Console.WriteLine(blocking);
    Console.WriteLine("-- async --");
    Console.WriteLine(async);
}

private static string Serialize<T>(T data)
{
    using var stream = new MemoryStream();
    using var writer = new Utf8JsonWriter(stream);
    JsonSerializer.Serialize<T>(writer, data, _jsonSerializerOptions);
    return Encoding.UTF8.GetString(stream.ToArray());

}
private static async Task<string> SerializeAsync<T>(T data)
{
    using var stream = new MemoryStream();
    await JsonSerializer.SerializeAsync<T>(stream, data, _jsonSerializerOptions, default);
    return Encoding.UTF8.GetString(stream.ToArray());
}
```

emits:

```json
Generic
-- blocking --
{}
-- async --
{}
-- blocking --
{"x":1,"y":true}
-- async --
{"x":1,"y":true}
Boxed
-- blocking --
{}
-- async --
{}
-- blocking --
{"x":1,"y":true}
-- async --
{}
```

```csharp
            int maxPropertyIndex = JsonClassInfo.PropertyCacheArray.Length;
```

Is always `0` in the [`NextProperty()` for `WriteStackFrame`](https://github.com/dotnet/corefx/blob/master/src/System.Text.Json/src/System/Text/Json/Serialization/WriteStackFrame.cs#L132) in the case of an async serialize on a boxed value.

**Comment by ahsonkhan** [comment] 2020-02-21 06:10
@steveharter - please take a look

**Comment by steveharter** [comment] 2020-02-28 16:40
Verified fixed with https://github.com/dotnet/runtime/pull/32669. Will add tests to that PR.

The Stream code was missing a check for `typeof(object)` to enter the polymorphic mode by calling `object.GetType()`.

Also consider fixing in 3.1.

**Comment by steveharter** [comment] 2020-03-06 16:53
The work-around for 3.1\3.0 is to use the non-generic API that takes the `inputType` as an argument:
```
JsonSerializer.SerializeAsync(writer, data, typeof(T), _jsonSerializerOptions);
```

**Comment by ahsonkhan** [comment] 2020-03-13 00:57
> The work-around for 3.1\3.0 is to use the non-generic API that takes the `inputType` as an argument

Would that work for non-root types on which the caller can't call `.GetType()` on, or is the issue only isolated to root types?

**Comment by steveharter** [comment] 2020-03-13 19:30
The issue is only for root types.

**Comment by steveharter** [comment] 2020-03-13 19:31
Closing; tests added

**Closed by steveharter** 2020-03-13 19:31 UTC
Labels: area-System.Text.Json, bug, tenet-reliability
