### ISSUE TITLE
Implement the logic to support SoftwareWriteWatch in NativeAOT

### ISSUE THREAD

**Issue by cshung** [dotnet/runtime#77225] opened 2022-10-19 17:28 UTC
Right now, we are building Windows NativeAOT without `FEATURE_MANUALLY_MANAGED_CARD_BUNDLES ` and `FEATURE_USE_SOFTWARE_WRITE_WATCH_FOR_GC_HEAP` defined. 

Short term, this configuration exposed a bug in the implementation causing #76801

Long term, it would be a good idea to turn them on so that we can eventually get rid of the code.

**Comment by jkotas** [comment] 2022-10-27 05:34
Duplicate of https://github.com/dotnet/runtime/issues/75110

**Closed by jkotas** 2022-10-27 05:34 UTC
Labels: area-NativeAOT-coreclr
